### ISSUE TITLE
React is so dung and Vue is so beautify.

### ISSUE THREAD

**Issue by TEsTsLA** [facebook/react#10002]
I use React.js some of time.But the framework design is look like designed by a three-years child.
This is very shit and fuck every developer.But Vue that maked by a Chinexe is save me from hell.
Vue is fresh and freedom air for me.This is so freedom and sweet.
I am not pointer at someone deliberately.My meaning is everyOne is designed except  me

**Comment by vritant24** [comment]
Is this a troll?

**Comment by nihgwu** [comment]
Polish your English first before judging the others, don't be a droll

**Comment by ryerh** [comment]
Do not waste your time adding comments here, close this plz...

**Comment by hughgr** [comment]
火钳刘明

**Comment by zires** [comment]
Shame on you.

**Comment by blade254353074** [comment]
He is trolling. :trollface:

**Comment by nhunzaker** [comment]
If there are any actionable suggestions you have for improving the React API, we are open to hearing then. As it stands, this issue is destructive. 

Happy you found success with Vue. Best of luck!

**Comment by DickyT** [comment]
丢人 丢人 丢人. Shame on u.

**Comment by yuyu1987** [comment]
`Do not take it seriously`

**Comment by gaearon** [comment]
Thanks for feedback!
If you have specific suggestions on what we can learn from Vue, we’d love to hear them.

But this thread is not very constructive so I’ll lock it.
