### ISSUE TITLE
React component is using ReactNoopUpdateQueue in dev build, preventing state updates

### ISSUE THREAD

**Issue by TAGC** [facebook/react#10012]
**Do you want to request a *feature* or report a *bug*?**

I'm reporting a bug.

I'm facing a really strange issue in which every now and again my app stops working when running via webpack's hot dev server. When this issue presents itself, I struggle to get it to work again even after cleaning everything, stashing all git changes, resetting yarn.lock, etc.

In production builds I noticed this issue never occurs.

I have a simple component that renders two fields ("hostname" and "port"), and maintains the field values in the component's `state`. Essentially just [this](https://facebook.github.io/react/docs/forms.html#controlled-components).

### Expected behavior

I expect in such a basic case that I should be able to update the form fields without issue - I enter text in a field, which triggers the field's `onChange` event, which in turn invokes `setState`, updating the value that
the field gets re-rendered with.

### Actual behavior

I observe the expected behaviour every time in production, and some of the time during development. I have no idea why but sometimes after rebuilding certain modules I will see this issue again.

When it does occur, I'm not able to change the value of either of the fields, and instead I see the following error in the Electron console:

```
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ConnectionPane component.
```

### Environment

react: v15.6.1
`node -v`: v7.7.2
`npm -v`: 5.0.3

1. Operating system: Windows 7 64-bit
2. Browser and version: Electron (v1.7.3) chromium browser

### Additional Details

I notice that in both development and production builds, my React component does not pass a React updater to the superclass constructor, so React base class uses `ReactNoopUpdateQueue`:

```js
this.updater = updater || ReactNoopUpdateQueue;
```

There are two places where `this.updater` is assigned to, and I breakpoint both of them. In neither the dev nor the production build do I see anything except `ReactNoopUpdateQueue` getting assigned to this field, yet in my production builds state updates work as expected, and when I step through the `setState` code in production I find that `this.updater` has "magically" been replaced with the real update queue (`ReactUpdateQueue`).

This "magic" sometimes doesn't happen during dev builds, so the state changes fail (no-op) and I get the warning messages shown above.

For reference, this is an excerpt of the React component code.

```js
export default class ConnectionPane extends React.Component<IConnectionPaneProps, IState> {
  constructor (props: IConnectionPaneProps) {
    super(props);

    this.state = {hostname: 'localhost', port: 36364};

    this.onSubmit = this.onSubmit.bind(this);
    this.setHostname = this.setHostname.bind(this);
    this.setPort = this.setPort.bind(this);
  }

  private get isHostnameValid (): boolean {
     ...
  }

  private get isPortValid (): boolean {
    ...
  }

  private get areConnectionSettingsValid (): boolean {
    ...
  }

  public render () {
    return (
        <Form onSubmit={this.onSubmit}>
          <FormGroup controlId='hostname' validationState={this.isHostnameValid ? undefined : 'error'}>
            <ControlLabel>Hostname</ControlLabel>
            <FormControl
                type='text'
                value={this.state.hostname}
                onChange={this.setHostname}
            />
            <FormControl.Feedback />
          </FormGroup>
          <FormGroup controlId='port' validationState={this.isPortValid ? undefined : 'error'}>
            <ControlLabel>Port</ControlLabel>
            <FormControl
                type='number'
                value={isUndefined(this.state.port) ? '' : this.state.port}
                onChange={this.setPort}
            />
            <FormControl.Feedback />
          </FormGroup>
          <Button type='submit' bsStyle='primary' disabled={!this.areConnectionSettingsValid}>Connect</Button>
        </Form>
    );
  }

  private setHostname (event) {
    this.setState({hostname: event.target.value});
  }

  private setPort (event) {
    const port = event.target.value;

    if (port === '') {
      this.setState({port: undefined});
    } else if (inRange(event.target.value, PORT_MIN, PORT_MAX + 1)) {
      this.setState({port: toNumber(port)});
    }
  }

  private onSubmit (event) {
    event.preventDefault();

    const {hostname, port} = this.state;
    this.props.onConnect(hostname, port!);
  }
}
```

**Comment by TAGC** [comment]
I don't encounter this issue if I bind my functions to `this` within calls to `render` instead of just at construction time.

I.e. instead of doing this:

```js
 constructor (props: IConnectionPaneProps) {
    ...
    this.onSubmit = this.onSubmit.bind(this);
    this.setHostname = this.setHostname.bind(this);
    this.setPort = this.setPort.bind(this);
  }
```

I do this:

```js
  public render () {
    return (
        <Form onSubmit={this.onSubmit.bind(this)}>
          ...
            <FormControl
                ...
                onChange={this.setHostname.bind(this)}
            />
          ...
        </Form>
    );
  }
```

I didn't do this initially as it violates the `jsx-no-bind` rule (for performance reasons) but to hell with it I guess.

**Comment by aweary** [comment]
@TAGC https://github.com/gaearon/react-hot-loader/issues/593 seems to indicate this is an issue with `react-hot-loader`. Can we close this issue? If you believe this is an issue with React itself we'd really need a small example reproducing the error to investigate.

**Comment by TAGC** [comment]
@aweary Yeah, I'll close this.
