### ISSUE TITLE
SyntheticEvent.augmentClass undefined in QtWebKit browsers

### ISSUE THREAD

**Issue by hotboi64** [facebook/react#10010]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Everything seems terrible.
In a certain WebKit browser, <https://github.com/annulen/webkit>, a page that pulls in a bundled script doesn't seem to finish loading, with console errors about augmentClass being undefined

Build details:
`webpack`-ing,
using babel-loader with `es2015` and `react` presets in `webpack.config.js`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
After [building](https://github.com/annulen/webkit/wiki),
use a QtWebKit test browser from `./WebKitBuild/Release/bin/QtTestBrowser` to visit the offending page

**What is the expected behavior?**
to not see complaints about SyntheticEvent in the console

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react and react-dom 15.4
QtWebKit 5.212

**Comment by walrusfruitcake** [comment]
Upon debugging just before the `SyntheticEvent` module export, it appears `SyntheticEvent.augmentClass` is undefined, but the `SyntheticEvent.Interface` assignment is `EventInterface` as we'd expect.

**Comment by walrusfruitcake** [comment]
#10011

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/issues/10011.
But no promises this won't break again.
