### ISSUE TITLE
Suggested words get appended to the currently typed word when writing a comment on FB using virtual keyboard on Windows

### ISSUE THREAD

**Issue by gked** [facebook/react#10014]
It only reproes when soft keyboard is being used.

Repro:

1. Navigate to Facebook.com and on the front page
2. Type “won” then select “wonder” from the list of suggestions,

Expected: "won" is replaced by "wonder"
Actual: it appends “wonder” to “won” making it to be “wonwonder”.

**Comment by aweary** [comment]
@gked this repo is specifically for React, not the Facebook website. If you want to report a bug about React, check out [this support article on Facebook's help website](https://www.facebook.com/help/326603310765065).

Thanks!
