### ISSUE TITLE
React is not getting installed in windows 10

### ISSUE THREAD

**Issue by aniagarwal97** [facebook/react#10023]
Hello I am trying to install react on my windows 10 system and when i am entering 
**npm install create-react-app** command it is giving me this error 

I am attaching my npm-debug.log
***
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-react-app' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData create-react-app
8 silly fetchNamedPackageData create-react-app
9 silly mapToRegistry name create-react-app
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://localhost:8080/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'create-react-app',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'create-react-app',
12 silly mapToRegistry   name: 'create-react-app',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://localhost:8080/create-react-app
14 verbose request uri http://localhost:8080/create-react-app
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:53:12 PM
17 verbose request id a2301bbe08780480
18 http request GET http://localhost:8080/create-react-app
19 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 127.0.0.1:8080
20 info attempt registry request try #2 at 12:53:23 PM
21 http request GET http://localhost:8080/create-react-app
22 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 127.0.0.1:8080
23 info attempt registry request try #3 at 12:54:24 PM
24 http request GET http://localhost:8080/create-react-app
25 silly fetchPackageMetaData Error: connect ECONNREFUSED 127.0.0.1:8080
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1041:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
25 silly fetchPackageMetaData  error for create-react-app { Error: connect ECONNREFUSED 127.0.0.1:8080
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1041:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
25 silly fetchPackageMetaData   code: 'ECONNREFUSED',
25 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '127.0.0.1',
25 silly fetchPackageMetaData   port: 8080 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: connect ECONNREFUSED 127.0.0.1:8080
30 verbose stack     at Object.exports._errnoException (util.js:1018:11)
30 verbose stack     at exports._exceptionWithHostPort (util.js:1041:20)
30 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
31 verbose cwd C:\Users\Aniruddh\react
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "create-react-app"
34 error node v6.11.0
35 error npm  v3.10.10
36 error code ECONNREFUSED
37 error errno ECONNREFUSED
38 error syscall connect
39 error Error: connect ECONNREFUSED 127.0.0.1:8080
39 error     at Object.exports._errnoException (util.js:1018:11)
39 error     at exports._exceptionWithHostPort (util.js:1041:20)
39 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
39 error  { Error: connect ECONNREFUSED 127.0.0.1:8080
39 error     at Object.exports._errnoException (util.js:1018:11)
39 error     at exports._exceptionWithHostPort (util.js:1041:20)
39 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
39 error   code: 'ECONNREFUSED',
39 error   errno: 'ECONNREFUSED',
39 error   syscall: 'connect',
39 error   address: '127.0.0.1',
39 error   port: 8080 }
40 error If you are behind a proxy, please make sure that the
40 error 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true ]

**Comment by ematipico** [comment]
Maybe you might want to move your issue in the correct repository: https://github.com/facebookincubator/create-react-app

**Comment by gaearon** [comment]
By reading the log, I can see that it tries to connect to an npm registry *at your local machine*.

```
mapToRegistry registry http://localhost:8080/
```

I don't know if you intentionally wanted to do that or not.
You can try resetting it:

```
npm config set registry https://registry.npmjs.org/
```

and then try again.

**Comment by aniagarwal97** [comment]
I didn't did that intentionally. That must be by default.

**Comment by gaearon** [comment]
It's not the default, but maybe some tool you installed or ran did it.

**Comment by aniagarwal97** [comment]
@gaearon I tried doing this but still facing the same issue.

**Comment by gaearon** [comment]
Unfortunately we can't provide support for npm in this repository. You can report the issue to https://github.com/npm/npm if you'd like. From the error message, it is clear that it is attempting to connect to `127.0.0.1:8080` instead of the real registry. I don't know why, but it's not related to Create React App. You'll have the same issue if you install any npm package, for example:

```
npm install angular-cli
```

**Comment by aniagarwal97** [comment]
@gaearon Thanks a ton I again installed node and did all your mentioned changes and the problem is resolved and react is working fine.. Thanks!!

**Comment by gaearon** [comment]
Good to know, thank you for sharing!
