### ISSUE TITLE
refs.root breaks between 4.9.0 and 4.9.1

### ISSUE THREAD

**Issue by carruthe** [facebook/react#10031]
**Bug report **

I rely on a saved ref from the `<Fabric>` component to do some layout formatting for my Excel add-in.  I used the `ref` property of the `<Fabric>` component, and save a reference to `alias.refs.root`.  Between 4.9.0 and 4.9.1, this functionality broke - `alias.refs.root` is no longer defined.

React Version: 15.4.2 up to 15.6.1
Browser: Reproduced on Safari and Chrome (MacOS), and Chrome (Windows)

Here is a CodePen reproducing the behavior:

https://codepen.io/tcarruthers/pen/vZJeaw

Thanks!

Nick

**Comment by gaearon** [comment]
Please report this to `Fabric`. It doesn't look related to React: you're accessing component internals, which may change between versions of component libraries.

**Comment by carruthe** [comment]
@gaearon - My bad - I meant to report it to them, but I had your repo open.  Sorry!

**Comment by gaearon** [comment]
No worries!
