### ISSUE TITLE
IE10: caret in standard (controlled) input immediately disappears

### ISSUE THREAD

**Issue by Twisterking** [facebook/react#10042]
**BUG:** can't type in standard (controlled) `<input>` on IE10
(this works just fine on IE11!)

**UPDATE:** Okay I now know where the problem lies: It has something to do with [cheton/react-sortable](https://github.com/cheton/react-sortable). the input I am talking about here is inside an `<li>` in a `SortableList`. When I deactivate this, the input focus and caret works!

Controlled component with proper `value` and `onChange`.
The weird thing is, that the input does **not lose its focus** (can be seen because it is still white and the border is there - CSS `input:focus` is 'active'), but the caret simply immediately disappears.
Even more weird is, that the parent node has an onClick, which basically just does `this. amountInput.focus()` and **this works**. The caret shows up, I can type, all is fine. but directly clicking into the input, the caret immediately disappears.

Please [check the video](http://jmp.sh/6vX3OKp).

Did anyone ever experience this? I already tried removing all my Blur, Keydown, whatever handlers and all that from the input, but nothing changed at all.
So I am basically now down to a simple controlled input, with a `value` and a `onChange` handler. 
```
<input
   ref={(input) => { this.amountInput = input }}
   className="amount-input"
   type="number"
   placeholder="Menge"
   onChange={(e) => this.changeAmount('change', e)}
   value={amount}
/>
```
Sidenote: my `onChange` does not "save into state", but rather into a client Meteor [`minimongo`](https://guide.meteor.com/collections.html) database.
But again, it works just fine on any other browser, including IE11.
I don't get it.

Most recent React Version, IE10 in Win7 VM on MacOS.

**Comment by gaearon** [comment]
>UPDATE: Okay I now know where the problem lies: It has something to do with cheton/react-sortable. the input I am talking about here is inside an <li> in a SortableList. When I deactivate this, the input focus and caret works!

Can you create an isolated example to confirm this is a bug in React? Otherwise it's not very clear if it's a React or a library bug. Thanks!

**Comment by jquense** [comment]
Closing for staleness, please feel free to post a follow-up with a repro if it's still relevant!
