### ISSUE TITLE
[FF Mobile] Duplicated characters with a controlled component

### ISSUE THREAD

**Issue by ghostd** [facebook/react#10059]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
* Go to https://codepen.io/anon/pen/qjpBzw (this is a modified version of the 'Controlled Components' docmentation page to put the chars in upper case)
* Type 'a' into the input, you get 'A'
* Then type 'b', you get 'AAB'

**What is the expected behavior?**
We should have 'AB'

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
The CodePen uses React@15.6.1, and the bug only occurs with Firefox *mobile* (not with the desktop version). I tested with FF53 and 54

The bug only occurs because i change the case.

**Comment by ghostd** [comment]
I opened a bug at mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1377749
I dont know if i keep this issue open to find a workaround?

**Comment by nhunzaker** [comment]
That's very interesting...

First: **this is an excellent bug report**. Thank you for taking the time to prepare it.

There may be nothing we can do about it. If that is the case, I'll close this issue. In the mean time, I'll look into it.

**Comment by ghostd** [comment]
I dug into react code, i didn't find workaround

@nhunzaker the firefox bug was assigned a few hours ago, so i agree to close this issue and wait for a fix from the mozilla team

**Comment by nhunzaker** [comment]
Okay. That works for me. Feel free to follow up if you get any news!
