### ISSUE TITLE
Document the process for deprecating an API in React

### ISSUE THREAD

**Issue by flarnie** [facebook/react#10057]
Split out from https://github.com/facebook/react/issues/9398

  - [ ] what is the process for making that decision?
  - [ ] how do we communicate it before and during the release?
  - [ ] how do we support folks updating their syntax?
  - [ ] what should be included in a deprecation warning?

**Comment by gaearon** [comment]
Do we plan to do it? The current ad hoc process works.
If you don't feel strongly we can close it and revisit next time we deprecate something.

**Comment by flarnie** [comment]
It was something that commenters had flagged as confusing on one of our release/checklist items, but since joining the team I observed that we have an "ad hoc" process that works, and it isn't something that seems useful to document. Let's close this for now - thanks!
