### ISSUE TITLE
How to read React source code & where can I find a dir of special Component Function(such as, React.PureComponent) ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [facebook/react#10062]
# How to read React source code ?

>  where can I find a dir path of special Component Function Defined? (such as , `React.PureComponent`) 

I just very confused with the nested dirs & folders !

**Comment by gaearon** [comment]
Please see https://facebook.github.io/react/contributing/codebase-overview.html.

>where can I find a dir of special Component Function(such as , React.PureComponent) ?

It is defined [here](https://github.com/facebook/react/blob/864ae8fa987bebfc43ea87476a03a44ac010ebce/src/isomorphic/modern/class/ReactBaseClasses.js#L129-L137) but related logic is [here](https://github.com/facebook/react/blob/b840229286ac2a82fa49553ce793cf7b953d1845/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L917-L921) (old engine) and [here](https://github.com/facebook/react/blob/864ae8fa987bebfc43ea87476a03a44ac010ebce/src/renderers/shared/fiber/ReactFiberClassComponent.js#L144-L148) (new engine).
