### ISSUE TITLE
React v16 is not release until now, why?

### ISSUE THREAD

**Issue by vicbell** [facebook/react#10066]
React v16 is not release until now, why?

**Comment by milesj** [comment]
http://isfiberreadyyet.com/

**Comment by nhunzaker** [comment]
Yep! It's in the works! There are still some things to figure out, but the team is making lots of head way. Feel free to checkout the work in progress through the pull requests!

https://github.com/facebook/react/pulls

**Comment by vicbell** [comment]
It really takes a long time ~_~.

**Comment by gaearon** [comment]
It takes a lot of work to put out a major version. If we could release it faster, we would, but this is not possible.

Is there a specific reason you are waiting for 16?

**Comment by vicbell** [comment]
Yes, I just want to find the exciting things it will bring to us, no more else.
