### ISSUE TITLE
Feature request: Support server-side rendering of non-standard DOM attribute names (eg. AMP's [prop]="value")

### ISSUE THREAD

**Issue by cole-sanderson** [facebook/react#10064]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

I am working on project to build AMP page with React Server Side Rendering. I am having an issue to add custom attribute to built-in AMP element. In order to be able to use [amp-bind](https://www.ampproject.org/docs/reference/components/amp-bind#bindings) we need to be able to output “bindings”, which are special attributes of the form `[attribute]`, eg. `[slide]="selectedSlide"`. 

```
<amp-carousel 
    layout={layout}
    height={height}
    width={width}
    [slide]={slide}
>
        ...
</amp-carousel>
```

Here is AMP carousel example that work with [amp-bind](https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/#linking-carousels-with-amp-bind).

**What is the current behavior?**
- Parsing error: Unexpected token [ (Fatal) 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- All

For more information, you can read all the discussion in this [PR](https://github.com/facebook/react/pull/7311#issuecomment-311516763).

**Comment by aweary** [comment]
Thanks for the request @cole-sanderson! Once https://github.com/facebook/react/pull/7311 is merged this should be possible, with a caveat. The error you're getting:

```diff
- Parsing error: Unexpected token [ (Fatal)
```

Is because `[slide]={slide}` is not valid JSX, so parsing fails. I think it's unlikely that the JSX spec would be updated to support this syntax unless it would provide some benefit for a broader scope of issues/features.

What that means is that you'll just need to use the regular function call syntax for elements that require these AMP attributes.

```js
React.createElement('amp-carousel', {
  layout: layout,
  height: height,
  width: width,
  '[slide]': slide
}
```

After https://github.com/facebook/react/pull/7311 is merged the server renderer will not blacklist the `[slide]` property and the markup should be rendered correctly.

Keep in mind this is only for server-side rendering. `[slide]` is not a valid DOM attribute name, so if you're intention is to hydrate this server-rendered markup on an AMP page with React it won't work. Though I assume AMP will manage the content on the client, so that might not even be a concern.

**Comment by aweary** [comment]
The solution outlined above should now work with React 16.

**Comment by cole-sanderson** [comment]
Awesome, thank you @aweary! 😀

**Comment by kschmidtdev** [comment]
@aweary according to https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html#changes-in-detail there isn't support for custom DOM elements (amp-carousel) with custom attributes (slide). I've tried the `createElement` call in react server-side rendering with no success. Can you confirm?

**Comment by aweary** [comment]
hey @kschmidtdev, you are correct. The server renderer still [restricts attributes using `isAttributeNameSafe`](https://github.com/facebook/react/blob/4c3470eef832d64e03d18c19a70f2501f9becbfd/packages/react-dom/src/server/DOMMarkupOperations.js#L79). I don't remember why I thought this had changed in React 16, but neither https://github.com/facebook/react/pull/7311 nor it's successor https://github.com/facebook/react/pull/10385 change this behavior.

I'll re-open this. I'm not sure what the solution here would be; it's unfortunate that AMP uses non-standard attribute names. If server rendering AMP components is a common use case then we could potentially fork `isAttributeNameSafe` to a version that allows attributes with leading/trailing brackets on custom elements.

@gaearon what do you think?

**Comment by svdoever** [comment]
Would really appreciate a solution for this. Doing server-side AMP rendering as well using react. Will never dehydrate on client.

**Comment by dfrankland** [comment]
Just to add to the confusion, you can still add attributes with square brackets to non-custom components:

Example:

*   JS
    ```js
    const customProps = {
      "[custom-property]": "Hello, world!"
    };
    ```

*   JSX
    ```js
    <div>
      <div {...customProps}>Test</div>
      <custom-component {...customProps}>Test</custom-component>
    </div>
    ```

*   Resulting HTML
    ```html
    <div data-reactroot="">
      <div [custom-property]="Hello, world!">Test</div>
      <custom-component>Test</custom-component>
    </div>
    ```

This throws a warning only for the `<custom-component />`.

**Comment by dfrankland** [comment]
I've opened #12568 to add the ability to, at the very least, server-render non-standard components with non-standard attributes (like AMP).

**Comment by westonruter** [comment]
For [amp-bind](https://www.ampproject.org/docs/reference/components/amp-bind) there is now an XML-compatible syntax, so you can do `data-amp-bind-foo="bar"` as an alternative to `[foo]="bar"`. See https://github.com/ampproject/amphtml/issues/11115 and https://github.com/ampproject/amphtml/pull/15408. So it doesn't seem that support for the `amp-bind` bracketed attribute syntax would be required in React.

**Comment by aweary** [comment]
Great! In that case I don't think it's worth the effort to support the XML-incompatible syntax.
