### ISSUE TITLE
react & react-dom bundle size expand

### ISSUE THREAD

**Issue by wenbing** [facebook/react#10071]
try to bundle react & react-dom using browserify 

```sh
NODE_ENV=production ./node_modules/.bin/browserify t.js | ./node_modules/.bin/uglifyjs > t.bundle.js
```

code and results as follows:

```sh
$ cat t.js
require('react');
require('react-dom');
```

```sh
$ ls -lh t.*
-rw-r--r-- 1 zwb staff 150K Jun 29 17:10 t.bundle.js
-rw-r--r-- 1 zwb staff   40 Jun 29 17:06 t.js
-rw-r--r-- 1 zwb staff 390K Jun 29 17:07 t.v15.bundle.js
-rw-r--r-- 1 zwb staff 493K Jun 29 17:07 t.v16.bundle.js
```

results as you see,

t.bundle.js -> commented something
```js
$ cat node_modules/react/index.js
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  // module.exports = require('./cjs/react.development.js');
}
```

t.v15.bundle.js was bundled with react@15 and react-dom@15
t.v16.bundle.js was bundled with react@next and react-dom@next

is there something wrong?

**Comment by gaearon** [comment]
cc @trueadm

**Comment by trueadm** [comment]
@wenbing You commented out the development UMD bundle in the `react` package, you'll need to do the same for the `react-dom` package. I just tested this and get:

`150K Jun 29 12:09 t.bundle.js`
