### ISSUE TITLE
Bootstrap checkbox button is not triggered in react

### ISSUE THREAD

**Issue by gamesover** [facebook/react#10075]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
onchange event is not triggered when click the button.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
https://codepen.io/gamesover/pen/MoExWo?editors=1111
**What is the expected behavior?**
when I click the button, the binded onchange event is supposed to be triggered. 
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
not sure other version. This is 15.3.1

**Comment by akshaynaik404** [comment]
It would be better if you could specify the browser along with its version that you used.

**Comment by gamesover** [comment]
Sorry, I created a clean react and bootstrap system. It works. It seems I introduce some bugs when I used react_on_rails system. I will further debug. But surely, it is not a bug of reactjs. Thank you @akshaynaik404
