### ISSUE TITLE
Missing "return" in Lists and Keys documentation

### ISSUE THREAD

**Issue by joshbrw** [facebook/react#10073]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug.

**What is the current behavior?**
The `return` keyword is missing from the documentation at https://facebook.github.io/react/docs/lists-and-keys.html.

<img width="673" alt="screen shot 2017-06-29 at 10 07 13" src="https://user-images.githubusercontent.com/779766/27680958-7475797e-5cb5-11e7-9291-9a9f9aebbb98.png">

**Comment by joshbrw** [comment]
Whoops, me being stupid. Please ignore.

**Comment by gaearon** [comment]
No worries! Arrows have implicit returns if they don't have a body with curly braces.
