### ISSUE TITLE
React variables scope, defined how?

### ISSUE THREAD

**Issue by cristianocca** [facebook/react#10080]
This is mostly a security question,

How does React store all it's javascript variables/state? Is there any way from the window object, to access a variable defined inside react?

Lets say you are also using redux, and you store some sensitive data on a variable of the state, is there any way an attacker that's able to perform a successful XSS attack, could do something like `alert(window.__react_state.store.myVariable)` ?

**Comment by aweary** [comment]
@cristianocca it's safe to assume that if an attacker has access to the execution environment, any data on the client is vulnerable. I don't know of any path between the window object and local React component state, but security through obfuscation is weak and, like other client-side libraries, we can't make any guarantees on this front.
