### ISSUE TITLE
Failed to compile with error "Line: {Num} '{Variable}' is not defined  no-undef"

### ISSUE THREAD

**Issue by yurii-github** [facebook/react#10087]
| bug 
| cannot compile code
| react version ^15.6.1

**steps to reproduce**
1. create component
1.  load dynamically js file that introduces new variable _HC_
1.  try to use that variable
1. compile
1. see error "Line: {Num} 'HC' is not defined  no-undef"

Problem is, If I define this variable as global in component 3rd party script does not init HC for me. And I cannot compile due to this error too.

Is there a way to skip this compile checks, because I know that object exists as of this

`if (typeof HC !== undefined) { // executes and compiles }`

but

`if (typeof HC !== undefined) { HC.asd() // fails with error above }`

regards

**Comment by gaearon** [comment]
This is not a question about React library per se, but about a lint rule enabled by Create React App. So [Create React App](https://github.com/facebookincubator/create-react-app) repository would be a more appropriate place to file this.

>Problem is, If I define this variable as global in component 3rd party script does not init HC for me. And I cannot compile due to this error too.

Please read [Using Global Variables](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-global-variables) in Create React App User Guide.

To work around this lint rule, you need to **explicitly** say you want to use a global variable:

```js
const HC = window.HC;
// then use HC as you'd like
```

If you have further questions please file them in [Create React App repository](https://github.com/facebookincubator/create-react-app/issues/new).

Thanks!

**Comment by yurii-github** [comment]
oh, thanks! _// eslint-disable-line_  did the trick

**Comment by gaearon** [comment]
You don't need to disable it though. The approach I suggested above is the one we recommend

**Comment by yurii-github** [comment]
I got it. Problem is if I define variable like that the value will not be set for it by external script

```
let HC = window.HC; 
or
const HC = window.HC;
```

I can use `window.HC` instead though.

thank you for your help once again

**Comment by gaearon** [comment]
Why would it not be set? If the script runs before your bundle then it should be set.
