### ISSUE TITLE
Build of `react-dom-server` on unpkg.com is broken

### ISSUE THREAD

**Issue by nylen** [facebook/react#10086]
I am not totally sure whether this should be reported here or against `unpkg` - for the issue against our project see https://github.com/WordPress/gutenberg/issues/1628.

---

https://unpkg.com/react-dom@next/umd/react-dom-server.development.js is currently a bad build.

It redirects to https://unpkg.com/react-dom@16.0.0-alpha.13/umd/react-dom-server.development.js which ends like this:

 ```js
/**
 * For browsers that do not provide the `textInput` event, extract the
 * appropriate string to use for SyntheticInputEvent.
 *
 * @param {string} topLevelType Record from `BrowserEventConstants`.
 * @param {object} nativeEvent Native browser event.
 * @return {?string} The fallback string for this `beforeInput` event.
 */
function getFallbackBeforeInputChars(topLevelType, nativeEvent) {
  // If we are currently composing (IME) and using a fallback to do so,
  // try to extract the composed characters from the fallback object.
  // If composition event is available, we extract a string only at
  // compositionevent, otherwise extract it at fallback events.
  if (currentComposition) {
    if (topLevelType === 'topCompositionEnd' || !canUseCompositionEve
```

The `alpha.12` version looks fine.

**Comment by gaearon** [comment]
It doesn't end like this for me. I saw unpkg having issues like this before so let's assume the problem is on their side. If not let me know and I'll reopen.

**Comment by nylen** [comment]
Looks fine to me now as well. Thanks!
