### ISSUE TITLE
Add default property for ES2015 modules

### ISSUE THREAD

**Issue by lukescott** [facebook/react#10098]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

```js
import * as React from "react"
```

The above code causes deprecation warnings because of how `_interopRequireWildcard` works in babel:

```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

You can use this with babel:

```js
import React from "react"
```

This works because of synthetic import support in babel, using `__esModule`.

If you use TypeScript the above does not work unless you set `allowSyntheticDefaultImports` to true in tsconfig.json.

Most packages work fine with `* as Module`, but React's deprecated warnings get tripped because babel copies the object with `_interopRequireWildcard`.

**What is the expected behavior?**

```js
import React from "react"
```

The above should work without needing to set `allowSyntheticDefaultImports`. This can be done by providing a `default` property.

Possibly by adding this to `src/isomorphic/ReactEntry.js`:

```js
React.default = React
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.6.1
Chrome 59
OS X 10.12.5
Node 8.1.2

Does not work in previous versions since deprecation warning was added.

**Comment by aweary** [comment]
Hey @lukescott, can you expand on why you'd want to do `import * as React`? Importing all the exports from the React package doesn't seem necessary, as only the default export needs to be in-scope so `React.createElement` calls don't fail.

**Comment by lukescott** [comment]
When I do `import React from "react"` in TypeScript it fails because React doesn't have a default export. So to make it work you either have to do `import * as React from "react"` or enable `allowSyntheticDefaultImports`. 

Synthetic default imports help with compatibility with node modules. I'm suggesting that `default` is added so it works with ES2015 modules natively without needing compatibility options.

**Comment by aweary** [comment]
I see. It looks like TypeScript expects you to use `allowSyntheticDefaultImports` when importing modules that are not exported as ES2015 modules. I'm not sure faking this by manually adding a `.default` property would be a good idea, as it incorrectly implies we're exporting ES2015 modules.

**Comment by gaearon** [comment]
The warnings will be gone in React 16 so I think we can live with this until the release.

**Comment by lukescott** [comment]
Would adding a `.default` property really be "faking it" though? 

@gaearon Which would be the preferred style in TypeScript in React 16?

```ts
import React from "react"
```

or

```ts
import * as React from "react"
```

If it's the former, wouldn't it be beneficial to be compatible with ES2015, rather than relying to compatibility options?

**Comment by gaearon** [comment]
I think in the longer term style 2 would probably make more sense.
Maybe @sebmarkbage disagrees.

**Comment by gaearon** [comment]
For now you can either form that makes sense to you. We removed the deprecated APIs in 16 so you won't see the warnings anymore.

**Comment by wereHamster** [comment]
Should the documentation be updated to use style 2? For example https://reactjs.org/tutorial/tutorial.html still uses `import React from …`. It will take a while until all tools and libraries are updated to use the more correct form, and it would make sense to teach users as soon as possible.
