### ISSUE TITLE
PropsTypes from don't show any kind of warning or error for wrong props in Windows,  but if you running your app under OSX, everything works fantastic.Why??

### ISSUE THREAD

**Issue by simran-grewal** [facebook/react#10093]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
@simran-grewal please provide the information requested in the issue template. Unfortunately, there isn't enough information here for us to determine what's going on.

**Comment by aweary** [comment]
I'm going to go ahead and close this since there's no actual information in the OP and there's been no follow up.
