### ISSUE TITLE
React should throw on nested <p> tags

### ISSUE THREAD

**Issue by petehunt** [facebook/react#101]
Browsers do special things on self-closing tags like `<p>`:

http://jsfiddle.net/bbrGq/1/

React should warn or throw if it detects a nested React.DOM.p.

**Comment by zpao** [comment]
I'm just going to close this out. We left it open a long time but we haven't made any progress apart from improved error messages. It's still a hard problem to solve in a reasonable way, so I'm calling it off.

**Comment by syranide** [comment]
@zpao Like I mentioned in my "no data-reactid"-PR, it is possible to catch this immediately as it occurs quite cheaply (so it's a good fit for DEV at the very least) and it's just a few lines of code as well. Considering that PROD-behavior would stay lenient, the DEV/PROD inconsistency shouldn't be an issue either.
