### ISSUE TITLE
React server render error are hard to debug

### ISSUE THREAD

**Issue by kimown** [facebook/react#10104]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Like https://github.com/reactjs/react-rails/issues/264, https://github.com/erikras/react-redux-universal-hot-example/issues/51
When using react server render, if error occurs, like using document or window object in Node environment, the error log is hard to find which line is broken, error info like picture below.
![image](https://user-images.githubusercontent.com/7932380/27819385-9023f7de-60cc-11e7-9774-8281d86ded86.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
When server render error occurs, from error message we can see which line is broken.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@15.6.1

**Comment by gaearon** [comment]
I’m finding it hard to understand how this is related to React. The error message appears like a Node message printed to Chrome console. There is nothing we can do about how it is formatted. So I’ll close but let me know if I am wrong.
