### ISSUE TITLE
Improve error when you've forgotten to extend React.Component

### ISSUE THREAD

**Issue by thejameskyle** [facebook/react#10103]
When you forget to extend `React.Component` you get the following error:

```
TypeError: Cannot call a class as a function
    at _classCallCheck (null.js:7:99)
    at Hello (null.js:11:5)
    ...react internals...
```

[[Example](http://react.jsbin.com/?html,js,console)]

It would be nice if in dev you could do a check for `Component.prototype.render` and if it exists, provide a better warning along the lines of:

```
Warning: Using a class with a render method as a function, did you forget to extend React.Component?
``` 

I believe it would happen in [ReactCompositeComponent.js](https://github.com/facebook/react/blob/b840229286ac2a82fa49553ce793cf7b953d1845/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L248).

**Comment by thejameskyle** [comment]
Note that the error is much worse when you're compiling classes without `_classCallCheck` because `this` is just `undefined`

**Comment by aweary** [comment]
Thanks for the feature request @thejameskyle! I agree that a better error here would provide a better developer experience. It also looks like Fiber will get caught in an infinite loop if you try to render a class that doesn't extend `React.Component`, so it might even be necessary.

<details>
 <summary>Here's an example demonstrating that. Be warned, it will crash or freeze your browser/tab.</summary>
  <a href="https://jsfiddle.net/0sLvero5">Click at your own risk</a>
</details>


cc @gaearon @acdlite ^

`ReactCompositeComponent` might be the right place for this, but we'd need to do it outside the `DEV` block since it should throw an error and we want to maintain the same invariants for DEV and PROD.

**Comment by acdlite** [comment]
The infinite loop is a known issue with error handling.

**Comment by acdlite** [comment]
Will fix before release

**Comment by aweary** [comment]
Thanks, @acdlite! Do you know if the fix will address @thejameskyle's request?

**Comment by acdlite** [comment]
Yeah, fixing the infinite loop bug would not address the lack of a helpful error message. Good candidate for an external PR. Should also account for `React.PureComponent`.

**Comment by sw-yx** [comment]
gonna give it a shot... first contribution

**Comment by sw-yx** [comment]
i am a bit confused. `ReactCompositeComponent` no longer seems to there and only exists in tests.  Was it renamed somehow?

**Comment by gaearon** [comment]
That logic is now in `ReactFiberClassComponent`. Old engine is gone.

**Comment by sw-yx** [comment]
Ok I think I have a good handle on this. Upon deeper inspection the error happens earlier in the lifecycle than in `ReactFiberClassComponent` so I am placing the invariant higher up than originally suggested.

(The error actually gets thrown in [`mountIndeterminateComponent`](https://github.com/facebook/react/blob/master/src/renderers/shared/fiber/ReactFiberBeginWork.js#L470) and so doesn't even reach `mountClassInstance` from `ReactFiberClassComponent` several lines lower)

As for what to check, i'm going with simply `!workInProgress.type.prototype.render` and that seems to work under my testing (plain js class vs React.Component). Ordinarily I'd be worried that that might be too broad but that seems to be the way the rest of the warnings go in the codebase.

**Comment by sw-yx** [comment]
for anyone else watching we made this into a `warning` instead as requested by Dan. also added a test

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11168.
