### ISSUE TITLE
Tic Tac Toe Tutorial

### ISSUE THREAD

**Issue by alaumh** [facebook/react#10119]
Hi, I am in the middle of the [tutorial](https://facebook.github.io/react/tutorial/tutorial.html).

I found that the naming of a variable (xIsNext) is not clear.

`this.state.xIsNext ? 'X' : 'O';`

If X is next, are we supposed to display O instead of X ?

Thank you.

**Comment by SoerenTerh** [comment]
In a prior step, xIsNext is set in the state of the component as a boolean. xIsNext is indeed expressing, that the next turn is played by X. The ternary operator, which is being used here, therefore checks the state's boolean in regard of which side is the next to take turn. You could also make an if-else-statement out of it, which would do the same thing:  
```javascript 
if(xIsNext){  // which is a short form of if(xIsNext === true)
  squares[i] = 'X';
} else {
    squares[i] = 'O';
}

**Comment by gaearon** [comment]
@SoerenTerh’s answer is correct.
Here is a [reference on ternary operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Conditional_Operator).

I’ll close this but if you still consider it unclear let me know how we can rename it.

**Comment by alaumh** [comment]
Thank for replying. What I meant is if the next turn is played by 'X', then we should display 'O' on the board as the current turn is played by O. So is it a good idea to rename xIsNext to yIsNext or change `this.state.xIsNext ? 'X' : 'O';` to `this.state.xIsNext ? 'O' : 'X';` ?

Thank you.

**Comment by gaearon** [comment]
I guess it's not the variable naming, but the text that is confusing.

It says "Next player" but what it really means is "Current player". It says "next" because current player (e.g. X) is the one whose mark (e.g. X) will appear on "next" click.

**Comment by gaearon** [comment]
Open to naming suggestions to fix this. Maybe `isXPlaying` would be better.

**Comment by NYCJacob** [comment]
maybe whoseNext  and document that the variable is for which player will  has the next move, ie, that players symbol will occupy the next box clicked.  I think having x in the var name is causing him confusion.

**Comment by gaearon** [comment]
This is low priority so I’ll close for now. But if more people report this as confusing we can reopen and fix. I’m also happy to take a PR renaming `Next` to `Current` there.

**Comment by bluesky66-dev** [comment]
How do I change "x" to four values ​​"O", "Y", and "Z" when clicked?

**Comment by marcelchelo** [comment]
This is confusing, reopen and fix it plz
