### ISSUE TITLE
Render gets out of date state when it was set from componentWillReceiveProps using updater function

### ISSUE THREAD

**Issue by mass85** [facebook/react#10111]
This is either a bug in documentation or in implementation.

According to [setState doc](https://facebook.github.io/react/docs/react-component.html#setstate) when there is a need to refer to previous state, one must use the updater function. Problem is that when this updater function is used to change state from `componentWillReceiveProps`, state is not updated before `render` function is called. In result `render` gets new props but old state and is not called again after state is really updated.

This illustrates the problem:
[https://jsfiddle.net/84v837e9/115/](https://jsfiddle.net/84v837e9/115/)

I observed this problem in react 15.2.0 and 15.6.1.

**Comment by aweary** [comment]
Hey @mass85! It looks like you just have a small syntax error.

```js
this.setState((prevState) => {
  itemsState: this.buildItemsState(prevState.itemsState, nextProps.dataArray)
})
```

This is being interpreted as an arrow function with a [labeled statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label), not as an arrow function returning an object. You need to wrap the brackets in parens for it to be interpreted as an arrow function returning an object.

```js
this.setState((prevState) => ({
  itemsState: this.buildItemsState(prevState.itemsState, nextProps.dataArray)
}))
```

[Here's an updated version of your example](https://jsfiddle.net/22ue7kvf/) with the fix. Hope that helps!

**Comment by mass85** [comment]
Thanks! Shame on me.
