### ISSUE TITLE
Tutorial Starter Code

### ISSUE THREAD

**Issue by camilaavilarinho** [facebook/react#10110]
The [starter code](https://codepen.io/gaearon/pen/oWWQNa?editors=0010) in the tutorial is linked to the final code on codepen not to the starter code.

**Comment by gaearon** [comment]
Hmm. The link in this thread points to the starter code I believe. It shows an empty tic tac toe field but doesn't actually do anything. The final result is a working game. Do I miss anything?

**Comment by camilaavilarinho** [comment]
For me was showing the final code every time I opened. Now is working, sorry

**Comment by gaearon** [comment]
Maybe some CodePen glitch. Sorry! If you see this again let us know and we can take another look. I’ll close for now.
