### ISSUE TITLE
Runtime issue: "TypeError internalInstance is null". You may need to refresh the page. 

### ISSUE THREAD

**Issue by hp685** [facebook/react#10112]
**Bug**
This is due to version incompatibility of react and react-dom for certain versions. I've managed to fix the issue by using compatible react and react-dom versions:

  "react": "^15.3.2",
  "react-dom": "^15.4.1"

**What is the current behavior?**
I've had a react codebase work for 2+ years, and as of recently, we encountered run time "TypeError: internal instance is null" errors. The cacheBuster was of no help as it would point to a generic window.onerror function. 
 
The following is the error message in the browser:

The following error occurred: "TypeError: internalInstance is null". You may need to refresh the page. "File: http://127.0.0.1:8080/dist/js/app.js?cacheBuster=1498505575156" Line Number: 102926

**What is the expected behavior?**
No runtime errors

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The version that we encountered issues with are:
  "react": "^0.14.7", "react-dom": "^0.14.6".

**Comment by gaearon** [comment]
If you still have the issue please provide a project reproducing it. Otherwise we'll have to close it as there's not enough information to dig into.

We only support using matching versions of React. Both `react` and `react-dom` should have exactly the same version.

**Comment by hp685** [comment]
Good to know. I opened this for documenting the error in case someone else runs into it.

**Comment by gaearon** [comment]
Thanks, that's appreciated! Another possible cause for this kind of error is if you have an *earlier* error but swallow it in the application code. Then React gets confused on next render. We will fix it in 16.
