### ISSUE TITLE
Node v8.x not allowed due to devEngines setting in package.json

### ISSUE THREAD

**Issue by ndresx** [facebook/react#10127]
**Do you want to request a *feature* or report a *bug*?**
*feature*/update

**What is the current behavior?**
Currently, only the following Node versions are allowed because of the `devEngines` value in the `package.json` when executing `npm install` or any other script: `"node": "4.x || 5.x || 6.x || 7.x"`.

**Error:**
`Current node version is not supported for development, expected "8.0.0" to satisfy "4.x || 5.x || 6.x || 7.x".`

**What is the expected behavior?**
Unless there is a reason for not allowing version 8 yet, could we update this?

**Comment by gaearon** [comment]
Wanna send a PR to add it there?

**Comment by ndresx** [comment]
@gaearon yes sure, done!

**Comment by gaearon** [comment]
Fixed in #10129. Thanks for PR!
