### ISSUE TITLE
<a href="javascript:scrollTo(0,0);"> can't scroll to top

### ISSUE THREAD

**Issue by u0024window** [facebook/react#10128]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by ndresx** [comment]
Seems to be working fine https://jsfiddle.net/d5h58ttk/?

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

This doesn’t appear to be a description of React bug, and there is too little information to help you.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
