### ISSUE TITLE
Using native DOM events and react events 

### ISSUE THREAD

**Issue by boopeshmahendran** [facebook/react#10120]
I have a react element Inner inside the #outer and there are click event handlers for both the #outer and the react element Inner

```html
<div id='outer'>
</div>
```

```js
document.getElementById('outer').addEventListener('click', function() {
  console.log('outer click');
});

class Inner extends React.Component {
  handleClick() {
    console.log('inner click');
  }
  render() {
    return <div onClick={this.handleClick}>
      Inner
    </div>;
  }
}


React.render(<Inner />, document.getElementById('outer'));
```
So, when I click on the react element Inner, I expect the Inner element click handler to be triggered first and then the outer element click handler. But it happens in reverse direction i.e the outer element click handler gets triggered first and then the Inner element click handler gets triggered.

I know that react has its own event system and Native DOM events propagate before react events are triggered and propagate. But what will be the **most correct way to achieve my expected behavior**?

**Note: The above code is only for example. I am working on a large code base. So please keep that in mind while answering.**

**Comment by gaearon** [comment]
>But what will be the most correct way to achieve my expected behavior?

Can you tell more about what you’re trying to do? Why are you mixing DOM and React events, and why is ordering between them important to you?

**Comment by boopeshmahendran** [comment]
I am working on a project where I have to implement drag and drop to move items. The html structure is

```html
<div>
    <ul>
         <li>1</li>
         <li>2</li>
    </ul>
    <ul>
         <li>3</li>
         <li>4</li>
    </ul>
</div>
```

The ul and li are react elements. li elements should be draggable and dropped into any other ul or the outer div(if you drop in empty space after the uls). All the uls and the outermost div have ondrop events.
So always the outermost div element's ondrop gets triggered and it always gets dropped to the outer div. So only the order is important.

**Comment by mkuklis** [comment]
@boopeshmahendran could you turn your outer element into a react component?

**Comment by aweary** [comment]
@boopeshmahendran you may need to manually manage the event order yourself using a stack or something, React doesn't have an API for re-ordering events based on native DOM events.

If you could use a React component for the parent element like @mkuklis said, this could be easier for you. Have you considered using something like [`react-dnd`](https://github.com/react-dnd/react-dnd), which is a stable drag and drop solution for React?

We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question like this, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.
