### ISSUE TITLE
Consistency in parameter names (comment)

### ISSUE THREAD

**Issue by janus** [facebook/react#10121]
In the comment it is named 'componentInstance' but as function parameter it has a different name 'wrapperInstance' 
/** * Mounts this component and inserts it into the DOM. 
* * @param {ReactComponent} componentInstance The instance to mount. 
* @param {DOMElement} container DOM element to mount into.
 * @param {ReactReconcileTransaction} transaction 
* @param {boolean} shouldReuseMarkup If true, do not insert markup */ function 

mountComponentIntoNode( wrapperInstance, container, transaction, shouldReuseMarkup, context, )

**Comment by gaearon** [comment]
Thanks for noting. This is old code that's going to be deleted very soon, so I wouldn't worry about it.
