### ISSUE TITLE
Stop attribute blocking!

### ISSUE THREAD

**Issue by trusktr** [facebook/react#10126]
I write this JSX:

```html
<div mesh="sphere" texture="earth.png" r="30" cx="100" cy="100" transform="..."></div>
```
and I get 

```
Warning: Unknown props `mesh`, `texture` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

and React prevents the attributes from appearing in the DOM.

This means React will not always play nice with elements whose behaviors are defined by

- jQuery
- Angular
- etc, other APIs whose routines read from DOM.

In the above example, I could use jQuery or Angular to define routines that observe those attributes, and render a 3D WebGL scene in a separate canvas.

If an author wants to animate the sphere, they will not be able to, and my Angular or jQuery routine will not find the required attributes.

Please uplift this limitation! Don't limit the web!

**Comment by trusktr** [comment]
React says

> Remove these props from the element.

Um, but I want those props there. Come on React!

**Comment by nhunzaker** [comment]
Thank you for sending us your use case for custom attributes! We are working on this. See https://github.com/facebook/react/pull/7311

I'm going to close this out since we are tracking it here:  https://github.com/facebook/react/issues/9477

But thanks for the write up!

**Comment by trusktr** [comment]
@nhunzaker Great to hear. THanks!
