### ISSUE TITLE
[Fiber] Infinite loop when error is thrown in render()

### ISSUE THREAD

**Issue by steadicat** [facebook/react#10137]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Using React 0.16 alpha 13 (and most other recent versions of 0.16, IIRC), whenever an error is thrown inside of render(), React (Fiber) goes into an infinite loop. Screenshot: 
![screen shot 2017-07-10 at 5 04 30 pm](https://user-images.githubusercontent.com/6031/28045428-ddc6d26c-6591-11e7-8230-39ae97ad8f01.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
Unfortunately I don’t have a minimal repro case yet. I just wanted to flag this before 0.16 goes into beta. I don't think there's anything we're doing that's special (no weird recursive `componentDidUpdate` calls or similar). I tried stepping within the loop and it's all inside the Fiber internals, no user code involved.

**What is the expected behavior?**
React throws an error and stops.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Repros with 0.16, works fine with React 0.15.

**Comment by gaearon** [comment]
Thanks for reporting! It's a known issue in the open source alphas of ReactDOM. We're tracking it in https://github.com/facebook/react/issues/9193 and will fix soon.
