### ISSUE TITLE
HOC onClick doesn't work without adding new element

### ISSUE THREAD

**Issue by rohmanhm** [facebook/react#10146]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When `Some button` button clicked, it won't alert.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

This is the demo link: https://codesandbox.io/s/AljONjYO

**What is the expected behavior?**
onClick event with this HOC will not triggered.
```javascript
const hoc = (WrappedComponent) => {
  return class Abc extends React.Component {
    render () {
      return (
          <WrappedComponent
            {...this.props}
            onClick={() => alert('asdf')}
          />
      )
    }
  }
}
```

But, if I add `div` element before my `WrappedComponent` and `onClick` event I moved to `div` element it will work perfectly.

```javascript
const hoc = (WrappedComponent) => {
  return class Abc extends React.Component {
    render () {
      return (
         <div onClick={() => alert('asdf')}>
          <WrappedComponent
            {...this.props}
          />
         </div>
      )
    }
  }
}

```

I don't want to add `div` element on my Component. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v15.6.1

**Comment by aweary** [comment]
Hey, @rohmanhm! What you're seeing here is expected behavior. You can't add event handlers to user-defined components like `WrappedComponent`.  Event handlers can only be added to host elements, like `<div />` or `<button />`, for example.

Your `Button` component would have to pass down the `onClick` handler to the host element it renders, like so:

```jsx
class Button extends React.Component {
  render () {
    return <button onClick={this.props.onClick}>Some button</button>
  }
}
```

I hope that helps!

**Comment by rohmanhm** [comment]
hi @aweary thanks for quick response and explaining. It's help me a lot.

**Comment by aweary** [comment]
Glad to hear it! If you need any more help, I recommend checking out our [community support resources](https://facebook.github.io/react/community/support.html). They're great resources when you have an issue or question.
