### ISSUE TITLE
I have a problem and i not solve it.Please help me!

### ISSUE THREAD

**Issue by lalalawututu** [facebook/react#10141]
I write a function to href another web.

function openPage(){
        window.location.href="http://localhost/"
}
<i onClick={openPage}>

The function is useful,but it have a wrong.
When 'npm run build',it have a 'window is not defined'.

I dont know it.

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

In your particular case, nothing seems wrong to me, so a full example reproducing the issue would help. Read how to do it:
https://stackoverflow.com/help/mcve

**Comment by lalalawututu** [comment]
thanks! I will deal it for your guidance.

**Comment by lalalawututu** [comment]
@gaearon  thanks! I will deal it for your guidance.

**Comment by JonBellah** [comment]
If you're server rendering your application, `window` is not defined server-side which could result in this error.
