### ISSUE TITLE
Tutorial concepts without ES6/JSX?

### ISSUE THREAD

**Issue by quadruplejump** [facebook/react#10147]
The tutorials, with the exception of the "advanced guides", assume ES6/JSX.

The React without ES6 tutorial https://facebook.github.io/react/docs/react-without-es6.html still uses JSX.

The React without JSX tutorial https://facebook.github.io/react/docs/react-without-jsx.html still uses ES6.

What would a simple ES5 React demo look like?

To compare, the Vue introduction https://vuejs.org/v2/guide/ starts with very simple examples that you can just drop in a webpage.

**Comment by TrySound** [comment]
@quadruplejump Example without jsx can be dropped to webpage. Chrome and co. supports es6 quite fine.

**Comment by gaearon** [comment]
We can probably add an intro paragraph to both of these pages that links to HTML page with minimal example.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#73

Let's continue the discussion there! Sorry for the inconvenience.
