### ISSUE TITLE
how to use AMD module in react

### ISSUE THREAD

**Issue by kyle-kai** [facebook/react#10159]
I have a project which use html + css+ js, and in the project there are some modules which defined by AMD, like the image below:
<img width="1367" alt="2017-07-13 12 54 34" src="https://user-images.githubusercontent.com/29189686/28129448-f045c12a-6765-11e7-8eea-f1e8a0315538.png">

but now I need to rewrite the project with react, but I am not sure how to use this module directly in react, can I use it just like using require('xxx') in the image below? It is an important problem to me, can some one help me ?

![image](https://user-images.githubusercontent.com/29189686/28129594-7582add0-6766-11e7-985c-6d70737f092b.png)

**Comment by aweary** [comment]
Hey @kyle-kai, please don't open duplicate issues. @gaearon gave you an answer in https://github.com/facebook/react/issues/10158. Please refer to the community support resources linked in your original issue.
