### ISSUE TITLE
Request a 16.0.0-alpha.14 build

### ISSUE THREAD

**Issue by johanflint** [facebook/react#10152]
I'm not entirely sure whether this is the correct place for my request, if not then my apologies for wasting your time.

We are integrating React 16 in a large legacy webclient and jumping through hoops to render at comment nodes. To our great joy we noticed that #9835 is merged, which allows us to remove our hacks. However, it's merged after the latest alpha build (13) was created, so I'd love to get an alpha 14 build published.

**Comment by gaearon** [comment]
We'll get a beta out soon (in a week or so). I don't recommend using alpha because there is a severe known issue with infinite loop in development mode.

In general I don't recommend using 16 yet. It's just not ready for public consumption. Only if you feel experimental :-)
