### ISSUE TITLE
Incomplete documentation on creating web components

### ISSUE THREAD

**Issue by LukasBombach** [facebook/react#10155]
Hey there,

your [documentation on creating web components with react](https://facebook.github.io/react/docs/web-components.html#using-react-in-your-web-components) is quite cool and works really nice for the html. However, any component created this way will be unstyled as the documentation does not cover how to add CSS to the web component. Using `create-react-app` all your CSS will end up in a main.hash.css file and have selectors for your components, but when you create a web component, you css must be encapsulated in the component as the the components DOM lives in the shadow root and is not stylable from outside.

It would be cool if you could show a way to account for this.

**Comment by MrBenJ** [comment]
@LukasBombach - I'd be happy to jump on this one and give it a shot. OK if I create a pull request with some examples @aweary  ?

**Comment by LukasBombach** [comment]
@MrBenJ fwiw I am currently creating [create-react-web-component](https://github.com/LukasBombach/create-react-web-component/tree/create-react-web-component-modifications), a fork of `create-react-app` that creates a web component. If you wanna compare notes on this I am happy to chat.

**Comment by LukasBombach** [comment]
Oh btw, I found out that creating a web component like this **will actually not work at all**. The problem is that events in the shadow DOM will not be registered by react! [There is a worl around for that](https://stackoverflow.com/questions/37866237/click-event-not-firing-when-react-component-in-a-shadow-dom), but it's ugly. I think I am going to file an issue for that.

**Comment by LukasBombach** [comment]
Created an issue: https://github.com/facebook/react/issues/10422

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#72

Let's continue the discussion there! Sorry for the inconvenience.
