### ISSUE TITLE
how to import a amd module in react project

### ISSUE THREAD

**Issue by kyle-kai** [facebook/react#10158]
I have a project which use html + css+ js, and in the project there are some modules which defined by AMD, like the image below:
<img width="1367" alt="2017-07-13 12 54 34" src="https://user-images.githubusercontent.com/29189686/28129448-f045c12a-6765-11e7-8eea-f1e8a0315538.png">

but now I need to rewrite the project with react, but I am not sure how to use this module directly in react, can I use it just like using require('xxx') in the image below? It is an important problem to me, can some one help me ?

![image](https://user-images.githubusercontent.com/29189686/28129594-7582add0-6766-11e7-985c-6d70737f092b.png)

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

To briefly answer it—it’s not really related to React. You can use React with any existing module system including AMD.

**Comment by kyle-kai** [comment]
so how to use AMD in react , i am a fresh to react, thanks

**Comment by gaearon** [comment]
React is a library. You don’t need to use AMD “in” React. You can add React to your existing AMD app the same way you add other libraries.

**Comment by kyle-kai** [comment]
however, my whole page is written by react ui libarary, and in the page, there is an component which i want to render a 3d model, and this part is where i need to use AMD module

**Comment by JonBellah** [comment]
I believe @gaearon's point is that React doesn't know/care whether you're using AMD modules, ES6 imports, or otherwise. Your dev tooling needs to be able to interpret and include those AMD modules, not React.

**Comment by gaearon** [comment]
As I said earlier, this is an issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

Your question is vague and it’s hard to give a more specific answer without a minimal project or more information about what you’re struggling with. In any case, **React is only a library**, it doesn’t dictate how modules are loaded, so please consult support resources for the bundler you’re using to learn how to make it work with AMD.
