### ISSUE TITLE
Firefox error: Permission denied to access property "target"

### ISSUE THREAD

**Issue by vineetgopal** [facebook/react#10181]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Certain events in Firefox 54.0 trigger the following error:

```
Error: Permission denied to access property "target"
  at target(~/react/lib/getEventTarget.js:23:0)
  at getEventTarget(~/react/lib/ReactEventListener.js:58:0)
  at method(~/react/lib/Transaction.js:138:0)
  at transaction(~/react/lib/ReactDefaultBatchingStrategy.js:63:0)
  at batchingStrategy(~/react/lib/ReactUpdates.js:98:0)
  at ReactUpdates(~/react/lib/ReactEventListener.js:150:0)
  at func(~/raven-js/src/raven.js:265:0)
```

Note that raven is just wrapping the call, and I don't think that should be relevant.

The specific line of code this happens on is:
```
function getEventTarget(nativeEvent) {
  var target = nativeEvent.target || nativeEvent.srcElement || window;
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied suggests it could be due to an iframe and cross-origin issues. We do have some iframes embedded, although I haven't been able to reproduce the error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
I was unfortunately not able to reproduce this, though it has happened for ~200 separate users since the Firefox 54.0 upgrade on June 13, 2017. If it helps, we reported a similar error a while ago to raven.js (https://github.com/getsentry/raven-js/issues/768) which was fixed using a try/catch.

**What is the expected behavior?**
No errors :)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.3.2
Firefox 54.0, Windows and OSX

I think this is only an issue with the new Firefox, and not new behavior in React.

**Comment by Manuelandro** [comment]
https://github.com/getsentry/raven-js/issues/768

**Comment by aweary** [comment]
Without a reproduction, there's unfortunately not much we can do. Please feel free to ping me if you can provide a consistent repro with React. Thanks!

**Comment by StephanieYHe** [comment]
We're experiencing this problem too, and it's affecting users on Firefox 54, 55 and 56. No repro as well but just wanted to note that this issue continues!

**Comment by mqklin** [comment]
Same problem came in BugSnug to our production site.
Don't have an idea how to reproduce this.
http://jmp.sh/swp1iRO
![image](https://user-images.githubusercontent.com/9456433/32361189-44ae5d90-c07f-11e7-86c9-52b7b06a38fc.png)

**Comment by gaearon** [comment]
Let's keep this open for now. But we can't do anything without a repro case.

**Comment by robcmills** [comment]
We started seeing this same error in production on October 2nd:

<img width="326" alt="screen shot 2017-11-06 at 5 12 51 pm" src="https://user-images.githubusercontent.com/4131746/32472166-17cb2f08-c316-11e7-9636-6f328c46ea0c.png">

Our stack trace points to an event listener on the window for unhandled rejections:

```javascript
    window.addEventListener('unhandledrejection', (event) => {
        event.preventDefault()
        let error = _.get(event, 'detail.reason') || _.get(event, 'reason')
```

Which pretty much confirms what others have pointed out as the cause.

The information we gathered for this error:
- browser: Firefox 56.0
- os: Windows 7

We use React and Raven on the route in question but I don't know if they are related. 
Hope this information helps?

**Comment by udivankin** [comment]
Same here with both Firefox v56 and v57.

![screen shot 2017-11-15 at 17 36 17](https://user-images.githubusercontent.com/1522846/32845153-b7b0365e-ca2c-11e7-9c4b-2099cc29880a.png)

Seems that Mozilla does split testing for some new security feature.

**Comment by gaearon** [comment]
Doesn't seem like there's anything for us to do here.
I'll close again, but if it's our fault let us know.

**Comment by Serginyo90** [comment]
The same. Just caught this error.
