### ISSUE TITLE
Uncontrolled radio fix is breaking master

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10196]
I'm not sure why but https://github.com/facebook/react/pull/10156 seems to have caused issues in production with us. We'll need to either revert or find a way to fix forward. Right now master is broken, and if we sync again before fixing, we'll break things.

**Comment by jquense** [comment]
Is there anymore info about what breaks and when? I imagine it's  the instances vs DOM node check is failing but it's tough to guess why without a repro.

**Comment by gaearon** [comment]
We just got reports from production with the invariant triggering, it’s hard to say what exactly is being passed there. We’ll try to reproduce tomorrow.

**Comment by gaearon** [comment]
As a first step would you mind rewriting `inputValueTracking-test.js` in terms of public API? For example instead of calling that function directly, you could call `ReactDOM.render` and then make assertions on DOM by getting a ref to the input. This way we'll likely find where it broke in Fiber.

**Comment by gaearon** [comment]
Left a few more questions in https://github.com/facebook/react/pull/10156#pullrequestreview-50218031

**Comment by jquense** [comment]
I can definitely rewrite the tests, though for all intents and purposes the ChangeEventPlugin tests already do that. Which is to say, in terms of the public API the only visible effect is whether change events fire more than once per value.

**Comment by gaearon** [comment]
Hmmm I see. I was thinking about making tests still test implementation details (like wrappers) but use them through `ReactDOM.render` so we can be sure correct thing is being passed as argument to `inputTracker`. But maybe that won't help if we already cover these scenarios.

**Comment by jquense** [comment]
well it can't hurt :P I can see if it uncovers anything anyway

**Comment by gaearon** [comment]
Tracked down the cause. https://github.com/facebook/react/pull/10156#discussion_r127752226

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/10207
