### ISSUE TITLE
Update CodePen examples to use latest React

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10193]
IIRC currently they don’t. We should probably leave them using `latest` since if it breaks, we have to update them anyway.

**Comment by vinnymac** [comment]
@gaearon I can take this one, it'll be done by tonight or tomorrow afternoon. I will use [jsdelivr](https://www.jsdelivr.com) since cdnjs doesn't [support](https://github.com/cdnjs/cdnjs/issues/360) `latest`.

**Comment by gaearon** [comment]
We should use `unpkg` for consistency with our docs. To be honest I think it might be easier for me to do this myself since I already own those codepens.

**Comment by aweary** [comment]
@vinnymac could you use unpkg? We use it for our issue template JSFiddle, so keeping those consistent would be nice.

**Comment by vinnymac** [comment]
@gaearon yea `unpkg` is a good idea. I saw the low hanging fruit and thought I would cut it, but if you have the time feel free to do it.

**Comment by gaearon** [comment]
The problem is if you did it yourself you'd have to fork all the fiddles and then send PRs to update every link. Which is easy to get wrong by accident.

**Comment by bvaughn** [comment]
The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved this issue to the new repo: reactjs/reactjs.org#69
