### ISSUE TITLE
[feature request] Deferred (async) shouldComponentUpdate 

### ISSUE THREAD

**Issue by idibidiart** [facebook/react#10199]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
@idibidiart could you please provide some more information about your request, such as your use case(s)?

**Comment by OrenSchwartz** [comment]
please reopen. a use case would be to do request or load verify a successful api request before deciding to go ahead and render.
