### ISSUE TITLE
renderIntoDocument does not render into document

### ISSUE THREAD

**Issue by pronebird** [facebook/react#10206]
`renderIntoDocument` does not render into document whatsoever. This creates a lot of issues when components listen to global events on document. It would be great to revert the behavior of that function and add additional function to render into isolated DIV if needed.

**Comment by gaearon** [comment]
I suggest not to use it. It doesn't do anything except

```js
var div = document.createElement('div')
ReactDOM.render(element, div)
```

It is possible that we'll eventually remove this method altogether. We suggest to just use `ReactDOM.render` which gives you all the flexibility.

Does this help?

**Comment by pronebird** [comment]
Yes definitely! Thank you!
