### ISSUE TITLE
unmountComponentAtNode does not trigger componentWillUnmount on components mounted with unstable_renderSubtreeIntoContainer

### ISSUE THREAD

**Issue by woutervh-** [facebook/react#10205]
**Do you want to request a *feature* or report a *bug*?**

Not sure if it's intended behavior, but if it is, I'd like this feature.

**What is the current behavior?**

componentWillUnmount does not get called on a portal element which was mounted by unstable_renderSubtreeIntoContainer when unmountComponentAtNode is called.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Please check the example at:
https://codepen.io/woutervh/pen/JJqpLq?editors=1111

**What is the expected behavior?**

In the example above, I'd expect componentWillUnmount to be called, and the interval timeout to be cleared.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Google Chrome | 59.0.3071.115 (Official Build) (64-bit) (cohort: Stable)
Tried with React version 15.6.0

**Comment by gaearon** [comment]
This is unfortunately expected. As a workaround you should be able to explicitly unmount it by calling `unmountComponentAtNode` from `componentWillUnmount`.

The new portal API coming in React 16 won't have this issue.

**Comment by woutervh-** [comment]
I'm not sure I understand: I'm already calling unmountComponentAtNode. Do you mean I should place the call in componentWillUnmount of <App/> ? I've tried, but again it does not trigger componentWillUnmount of the <Portal/>.

**Comment by woutervh-** [comment]
I think as a work-around I will pass a prop from the parent to the portal, i.e. `<Portal mounted={this.mounted}/>` and place this in `componentWillUnmount()` of `<App/>` and take the prop change as a signal to cancel timers, etc.
