### ISSUE TITLE
Is it time to upgrade LICENSE to MIT?

### ISSUE THREAD

**Issue by marswong** [facebook/react#10203]
Reference: [Apache Foundation bans use of Facebook BSD+Patents licensed libraries like React.js](https://react-etc.net/entry/apache-foundation-bans-use-of-facebook-bsd-patents-licensed-libraries-like-react-js)

**Comment by gaearon** [comment]
Please follow the discussion in https://github.com/facebook/react/issues/10191.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
