### ISSUE TITLE
Components rendering order

### ISSUE THREAD

**Issue by DavidHe1127** [facebook/react#10204]
I have a composite component like below

```javascript
const a = <A></A>;
const b = <B></B>;
const c = <C></C>;

return (
   <div>
     {a}
     {b}
     {c}
    </div>
);
```

I wonder if it is ok to write it like that and hope `JSX` will render them in the correct order I embed?
thanks

**Comment by gaearon** [comment]
Yes.

**Comment by gaearon** [comment]
To be clear, it is up to React to decide in which order to actually call their render functions. You shouldn’t need to rely on this. But they will be displayed in the order you specify.
