### ISSUE TITLE
Enable to set fontFamily to "Press Start 2"

### ISSUE THREAD

**Issue by ioRekz** [facebook/react#10218]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When setting fontFamily to "Press Start 2", no fontFamily style property will be set
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
https://codesandbox.io/s/7Jyk6BYj
**What is the expected behavior?**
I would like to see the fontFamily property set to "Press Start 2" in chrome debugger
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Last React version, Chrome for Mac. I don't know if it worked before

**Comment by gaearon** [comment]
If I try this in regular JS, it also doesn’t show up: https://jsfiddle.net/ncce3x44/
So it’s not an issue with React.

However it shows up if I put font family name in quotes: https://jsfiddle.net/f8ymt1wg/

From [MDN](https://developer.mozilla.org/en/docs/Web/CSS/font-family):

>Font family names containing whitespace should be quoted.

Hope this helps!

**Comment by ioRekz** [comment]
Thanks, it helps. 
Although putting "Press Start" without quote works even if there is a space. 
From the different tests, it wont work without quote if there is a space and a number.
Anyway I can work around it now, thanks !
