### ISSUE TITLE
[Question] Keep to single setState call?

### ISSUE THREAD

**Issue by James2516** [facebook/react#10231]
```
class App extends Component() {
  fn1() {
    this.setState({a});
    fn2()
  }
  fn2() {
    this.setState({b});
  }
}
```
Is it guaranteed that calling `fn1` will only trigger a single re-render?
Is it a better practise to pass `a` to `fn2` and keep it to a single `setState({a, b})` call?

**Comment by gaearon** [comment]
This is implementation detail and may change in future versions.

In current release, they will be batched together if you are inside a React event handler. React batches all setStates done during a React event handler, and applies them just before exiting its own browser event handler.

With current version, several setStates outside of event handlers (e.g. in network responses) will not be batched. So you would get two re-renders in that case. 

There exists a temporary API to force batching. If you write `ReactDOM.unstable_batchedUpdates(() => { this.fn1(); });` then both calls will be batched. But we expect to remove this API in the future and instead batch everything by default.

I hope this helps!

**Comment by ChocolateLoverRaj** [comment]
> But we expect to remove this API in the future and instead batch everything by default.

@gaearon It's been four years... it there any planned date for batching everything by default?

**Comment by kasir-barati** [comment]
@gaearon I wanted to ask what @ChocolateLoverRaj asked. Any progress or

**Comment by kasir-barati** [comment]
Though there is one thing that bugs me, if I add an async code `await sleep(1)` which is a simple `setTimeout` with one millisecond timeout my console shows me that it is re-rending it 4 times (if we divide it by two to remove `StrictMode`'s effect what we have is 2).

![image](https://github.com/user-attachments/assets/7b2ae149-68a8-42bd-8d8f-b6f8c535ff58)

And here is the updated code:

```tsx
import { useState, useEffect, useRef } from 'react';

const MAXIMUM_FEED_COUNT = 50;
const FEED_FETCH_LIMIT = 15;

export function InfiniteScrollFeed() {
  const [feeds, setFeeds] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [page, setPage] = useState(0);
  const feedsListRef = useRef<HTMLUListElement>(null);

  function updateFeeds(data: any[]) {
    if (isLoading) {
      return;
    }

    setPage((previousPage) => previousPage + 1);
    setIsLoading(false);
  }

  useEffect(() => {
    let ignore = false;

    (async () => {
      await sleep(1);
      if (!ignore) {
        updateFeeds([]);
      }
    })();

    console.log('useEffecting');
  }, []);

  console.log('rendering');

  return (
    <section className="feeds">
      <h2 className="feeds__header">Feed</h2>
      <ul className="feeds__list" ref={feedsListRef}>
        {feeds.map((item) => (
          <li key={item.id}>
            <a href="#">{item.title}</a>
          </li>
        ))}
      </ul>
      {isLoading && <p>loading</p>}
    </section>
  );
}

function sleep(ms: number) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms);
  })
}
```

Any comment? Am I missing something @gaearon?
