### ISSUE TITLE
Implement new feature for flexible component attr definition 

### ISSUE THREAD

**Issue by odykyi** [facebook/react#10246]
**Do you want to request a *feature* or report a *bug*?**
i want this feature:
this 
`<MyComponent {id}/> instead this <MyComponent id={id}/>`
**What is the current behavior?**
`<MyComponent id={id}/>
`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
`<MyComponent {id}/> instead this <MyComponent id={id}/>`
**What is the expected behavior?**
`<MyComponent {id}/>`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** latest

**Comment by aweary** [comment]
Hey, @odykyi! This request should be made at [facebook/jsx](https://github.com/facebook/jsx) as it requires a change to the JSX spec, which React just utilizes. On that note, it looks like there's already an open issue for this request here: https://github.com/facebook/jsx/issues/23

If you have any additional feedback or clarifications with this request, please direct it to that open issue.

Thanks!
