### ISSUE TITLE
Is babel-react-optimize still value for React?

### ISSUE THREAD

**Issue by benweizhu** [facebook/react#10240]
I occasionally found out this https://github.com/thejameskyle/babel-react-optimize plugin which says will do a few things to optimize React.

I want to get some answer or confirmation from React team that whether this optimization is still valuable.

For example, transform-react-pure-class-to-function, for now, I would definitely write PureComponent instead of function.

Could React team do a clarification about it? Thanks a lot.

**Comment by gaearon** [comment]
`transform-react-constant-elements` might help make some updates faster at the cost of init time. I don’t know which metric is more important for you. However this plugin has been consistently buggy in Babel. I think Babel 7 fixes known issues but it’s not out yet. I wouldn’t use it until then.

`transform-react-inline-elements` seems like a fine thing to do but note that it relies on Symbol being polyfilled for IE11.

`transform-react-remove-prop-types` seems like a good idea.

`transform-react-pure-class-to-function` seems okay but it changes semantics. Somebody could get a `ref` to the class to `findDOMNode()` it. But this optimization breaks such code. So it’s generally unsafe and should be used with a lot of caution. I don’t think it has anything to do with `PureComponent`, that’s just similar naming for different things.

Hope this helps!

**Comment by benweizhu** [comment]
Thank you very much for your reply. It helps a lot.

Just about "transform-react-pure-class-to-function":

You mentioned "I don’t think it has anything to do with PureComponent, that’s just similar naming for different things."

So, does this transform-react-pure-class-to-function do any benefit except what you have said about unsafe and should be used with a lot of caution?

Because I know function will always rerender, just like Component without override willComponentUpdate. It just tell me this is a pure component from semantics perspective(my understanding, may be not right).

That's why I say given my understanding, I would use PureComponent instead of function, cause it not just tell me this is a pure component but also give me performance benefit by shallow compare.

So the question comes back to "does this transform-react-pure-class-to-function do any benefit"? Or I could say, when should I use function?

**Comment by gaearon** [comment]
>That's why I say given my understanding, I would use PureComponent instead of function, cause it not just tell me this is a pure component but also give me performance benefit by shallow compare.

If your data is structured in a way that shallow comparison often returns true, and the tree below it is deep, yes, `PureComponent` might be better in this case. I wouldn’t build the whole app out of `PureComponent`s though.

**Comment by fytriht** [comment]
@gaearon Could you elaborate on it? Why is it prefer to use `PureComponent` if the tree is deep and what's the benifits of using functoinal component instead of `PureComponent`? Thanks!
