### ISSUE TITLE
how setState to change obj (k:v)?

### ISSUE THREAD

**Issue by hzwmyProject** [facebook/react#10251]
obj={ 
     k:v
}
this.state({
    obj
})
I want to change k (use setState);
this.setState(?);
what is the "?";
thx..

**Comment by TrySound** [comment]
```js
class App extends React.Component {
  state = {
    obj: {
      k: 1
    }
  };
  callback = () => {
    this.setState(state => ({
      obj: Object.assign({}, state.obj, {
        k: 2
      })
    }));
  };
}
```

**Comment by hzwmyProject** [comment]
it is worked, thx  @TrySound    👍, but I have another problem, like this

state={
    obj:[ 
           {
                “k”：“v”
           }
       ]
}
change k;

**Comment by TrySound** [comment]
Similar, but with array map method.

**Comment by hzwmyProject** [comment]
it helped me, thx
