### ISSUE TITLE
how to change data obj and array (use setState)?

### ISSUE THREAD

**Issue by hzwmyProject** [facebook/react#10260]
obj like this:
```
state={
     k:[
            {
                 d:[
                        {
                               s:g
                         }
                    ]
            }
       ]
}
```
i want change g,but i have no idea ''??

**Comment by ianhoffman** [comment]
Something like setState({this.state[k][0][d][0][s]: 'whatever'}). I mean, at the root of it all, you're just indexing into the array that K points to and indexing into the value stored at index [0] in that array. From there, you repeat the process.

**Comment by hzwmyProject** [comment]
it s not worked, but  use 
```
const obj=this.state.k[0].d[0];
obj.s="sth";
this.setState(obj);
```
it is worked;
Thank you all the same

**Comment by TrySound** [comment]
@hzwmyProject 
You should not mutate state.
```js
this.setState(state => ({
     k: state.k.map(d1 => ({
            ...d1,
            {
                 d: d1.d.map(d2 => ({
                        ...d2,
                        {
                               s: newg
                         }
                 }))
            }
       })
}));
```
But better help yourself and use less nested state.
Also this is an issue tracker. Please use stackoverflow for questions about javascript.
