### ISSUE TITLE
Getting reference to component instance in snapshot testing

### ISSUE THREAD

**Issue by ishantoberoi** [facebook/react#10261]
My App is currently stacked in a Provider-->followed by Parent AppContainer Component-->followed by actual component.
M using Snapshot testing to load a component and call methods on it.

```js
 const tree = renderer
      .create(
        <Provider store={store}>
          <AppContainer>
              <MyComponent />
          </AppContainer>
        </Provider>
)
var instance = tree.getInstance()
```

This gives me instance of the Provider component. How do i get instance of MyComponent, to be able to call its methods?

I tried to do
```js
const tree = renderer
      .create(
              <MyComponent store={store} />

)
```
, but this gives error, as it not able to resolve 'CONTEXT', and i see that there is no way to pass context.

Any help?

**Comment by gaearon** [comment]
This should work:

```js
let instance;
const tree = renderer.create(
  <Provider store={store}>
    <AppContainer>
      <MyComponent ref={inst => instance = inst} />
    </AppContainer>
  </Provider>
);
```

**Comment by ishantoberoi** [comment]
@gaearon Thank You!
