### ISSUE TITLE
ReactDOM.render callback should return the top level element

### ISSUE THREAD

**Issue by pronebird** [facebook/react#10266]
I don't see the way to obtain the top level element with the new async `ReactDOM.render`

Previously `ReactDOM.render` would return the top level component:

```
const component = ReactDOM.render(<Foo />, container);
```

Now there is the third argument with callback which does not pass the rendered component into callback.

```
ReactDOM.render(<Foo />, container, (component) => {
   assert(component, "boo!"); // ALWAYS boo!
});
```

I think it is a bug that top level component is not returned in callback.

**Comment by gaearon** [comment]
>Previously ReactDOM.render would return the top level component:

Is that no longer the case? My impression is that the return value still works.

That said, the component was never passed to the callback you’re referring to as an argument. (It *is* passed as `this` but that’s mostly historical curiosity.)

I would write this code either as:

```js
const component = ReactDOM.render(<Foo />, container);
// Do something with component
```

which should still work, or as

```js
let component;
ReactDOM.render(<Foo ref={c => component = c} />, container, () => {
  // Do something with component
});
```

which is a bit more future proof and flexible (e.g. it lets you access nested components too).

Hope this helps!

**Comment by pronebird** [comment]
@gaearon Thank you for answers!

1. True `ReactDOM.render` still returns the component but we have eslint rules in place that throw warnings when it's used in such fashion (since it's not future proof). So I have to suppress those manually.

```
return ReactDOM.render(instance, container); // eslint-disable-line react/no-render-return-value
```

2. I am not able to pass `ref`, I receive an instance of it already:

```
function renderAndTestSomething(instance, container) => {
  return new Promise((resolve, _) => {
    ReactDOM.render(instance, container, function () {
      resolve(this);
    });
  });
}

renderAndTestSomething(<Foo />, container);
```

How does one reference the component in such scenario? I need it for tests and I'd like to avoid extra boilerplate.

Passing component as `this` in callback seems to be incredibly unreliable, esp. conflicts with arrow functions.

**Comment by gaearon** [comment]
>we have eslint rules in place that throw warnings when it's used in such fashion (since it's not future proof)

We are not enforcing such rules in FB codebase. It may be a long time before we actually deprecate the return value, if we ever do. Are you sure it is reasonable to keep this lint rule enabled in your codebase, if it’s causing you troubles?

I don’t think we’ll come up with a more convenient API until we actually decide to deprecate the return value (again, if we ever do).

>How does one reference the component in such scenario? I need it for tests and I'd like to avoid extra boilerplate.

I would just recommend to keep using return value. Even if we eventually deprecate it for product code, I’m pretty sure we’ll keep it around for tests because they should always run synchronously.

Maybe you could turn off the lint rule just for tests?

**Comment by pronebird** [comment]
@gaearon I see. I had impression that this is critical. Also `eslint-plugin-react` enabled it by default which seems overly pushing to move away from using `ReactDOM.render` in such fashion. Anyway, I am going to disable a corresponding lint rule for now and move on. Thanks again!

**Comment by gaearon** [comment]
Hmm. Seems like I spoke too soon 😞 
https://github.com/facebook/react/issues/10309#issuecomment-318701037

In your case it seems like this would be the best solution:

```js
let component;
ReactDOM.render(<Foo ref={c => component = c} />, container, () => {
  // Do something with component
});
```

>I am not able to pass ref, I receive an instance of component already. I can probably use this in callback as you mentioned above:

Minor technical correction: you receive an *element*, not an instance. The instance is what you want to get access to.

If you receive an element, you can clone it with a different ref.

```js
function cloneWithRef(element, newRef) {
  const oldRef = element.ref;
  return React.cloneElement(element, {
    ref(value) {
      if (typeof oldRef === 'function') {
        oldRef(value);
      }
      newRef(value);
    }
  });
}

const originalElement = <Foo />; // could be an argument
const element = cloneWithRef(originalElement, inst => {
  if (inst) {
    // Do something with component
  }
});
ReactDOM.render(element, container);
```

**Comment by gaearon** [comment]
Can you tell more about how you use an instance in tests? Usually tests are done on a wrapper, e.g. Enzyme’s `shallow()`. Are you calling methods on it?

**Comment by pronebird** [comment]
I have a UI component that uses `document` events so I need to plug it into DOM for testing.

```
// setup
let container;
function renderIntoDocument(instance) {
  container = document.createElement('div');
  document.documentElement.appendChild(container);
  return ReactDOM.render(instance, container);
}

// teardown
afterEach(() => {
  if(container) {
    ReactDOM.unmountComponentAtNode(container);
    container = null;
  }
});
```

So then I do something like that:

```
const component = renderIntoDocument(
  <Switch isOn={ false } onChange={ onChange } />
);
const domNode = ReactTestUtils.findRenderedDOMComponentWithTag(component, 'input');
// document.dispatchEvent(new MouseEvent( ... ));
```

**Comment by gaearon** [comment]
Hmm. Can you not find it via `document.getElementsByTagName('input')`? What’s the advantage of doing this via React?

**Comment by pronebird** [comment]
@gaearon actually I can, i never thought of that. But given that rendering may be asynchronous, the best way to go is to add `ref` and use callback to ensure when element is rendered. Then I can do any kind of lookup, either using DOM or directly via `ReactTestUtils.findRenderedDOMComponentWithTag(component, '..')`

**Comment by pronebird** [comment]
@gaearon thanks for helping me with this. I consider this solved given that worse case I can always clone element with new ref 👍

**Comment by gaearon** [comment]
>But given that rendering may be asynchronous, the best way to go is to add ref and use ReactDOM.render callback to be notified when element is rendered

Yep.
