### ISSUE TITLE
async/await lifecycle functions need be executed in order.

### ISSUE THREAD

**Issue by iugo** [facebook/react#10278]
request a *feature*

**What is the current behavior?**

https://jsfiddle.net/cxpg4y9c/

**What is the expected behavior?**

async/await lifecycle functions need be executed in order.

We need `async componentWillMount()` then `componentDidMount`.

Now `componentDidMount` had be executed on `async componentWillMount()` still pending.

v15.4.0

Chrome 59

**Comment by bvaughn** [comment]
React component lifecycle hooks are synchronous. (We don't support async hooks. Or rather, we don't block on them in the way your fiddle assumes.) This is working as designed. 😄

**Comment by iugo** [comment]
@bvaughn Thanks.
