### ISSUE TITLE
Update docs with example for Babel 7 -- JSX allows elements as attribute values?

### ISSUE THREAD

**Issue by kedromelon** [facebook/react#10276]
https://github.com/babel/babel/issues/6004 was resolved via https://github.com/babel/babel/pull/6006, so as of Babel 7 `<div attr=<div /> />` will work.

Should an example of this be added in the React documentation? If so, where? Would [JSX In Depth](https://github.com/facebook/react/blob/3d60d4cc7d00f194c2e585ec0bea92b19c5605d1/docs/docs/jsx-in-depth.md) be appropriate?

**Comment by bvaughn** [comment]
Personally I don't think this _needs_ to be in the React docs. (And at least some syntax highlighters- like the Babel plugin for Sublime- don't handle nested elements like this without the wrapping `{}`s. Atom seems okay with it though.)

But I don't have a strong feeling on this so I'll defer to others.

**Comment by gaearon** [comment]
I also don't feel this is important enough to document. Note that we already document the pattern itself, just not the form that omits curlies.

**Comment by kedromelon** [comment]
makes sense, thanks!
