### ISSUE TITLE
react 16 alpha13 keep report error when Component not found 

### ISSUE THREAD

**Issue by taojoe** [facebook/react#10298]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**
when there is a component notfound, react keep report error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

```

import React from 'react';

export default function App() {
  return (
    <div>
      <div>hello</div>
      <TabBar/>
    </div>
  );
}
```

![image](https://user-images.githubusercontent.com/545656/28653326-9cd9b058-7252-11e7-9161-628aa00c0e63.png)

**What is the expected behavior?**

just report error once 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 16 alpha13

**Comment by yamat124** [comment]
Dont you want to return a JSX component in your function?

export default function App() {
return (
<div>
hello
</div>

);
}

or is this a React Class?

export default App extends React.Component{
render{

return (
<div>
hello
</div>

);}
}

**Comment by taojoe** [comment]
already fix the markdown

**Comment by gaearon** [comment]
>react 16 alpha13

This is not a supported version, and it has severe known issues. Please don’t use it.

This bug is fixed in Beta 1 (https://github.com/facebook/react/issues/10294) which you can try.
