### ISSUE TITLE
Behavior differs between IE10 and Chrome when manually removing component from DOM

### ISSUE THREAD

**Issue by spicyj** [facebook/react#1029]
Recently we came across the following:

``` js
/** @jsx React.DOM */

var CountdownView = React.createClass({
    componentDidMount: function() {
        this.timeout = setInterval(this.forceUpdate.bind(this), 1000);
    },

    componentWillUnmount: function() {
        clearTimeout(this.timeout);
    },

    render: function() {
        return <div onClick={rerender}>{Date.now()}</div>;
    }
});

function rerender() {
  document.body.innerHTML = '<div id="container"></div>';

  React.renderComponent(
    <CountdownView />,
    document.getElementById('container')
  );
}

rerender();
```

Live demo: http://jsfiddle.net/spicyj/EGmvT/

Note that I'm manually removing the component element from the DOM here (when I should be using `unmountComponentAtNode` instead). In IE10, clicking the timestamp once will thereafter cause a JS error from findComponentRoot every second, but in Chrome and Firefox no errors are thrown. Why?

(In addition, it would be nice if we could give some useful message here. If you instead clear `document.body` completely and render into `document.body`, you get a somewhat-helpful warning: "ReactMount: Root element has been removed from its original container.".)

**Comment by spicyj** [comment]
Wontfixing this.

**Comment by klouskingsley** [comment]
just use unmountComponentAtNode  before document.body.innerHTML = '<div id="container"></div>'.
fixed in IE
