### ISSUE TITLE
react build deploy to firebase error

### ISSUE THREAD

**Issue by jandacreate** [facebook/react#10304]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
deploy build to firebase get error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

i will get the error , Uncaught SyntaxError: Unexpected token <, when i deploy the react build to firebase.
1: create-react-app your project
2: npm i firebase
3: do firebase init
4:npm run build (work), and get the build/static/js/main.12345.js
5: firebase deploy
6: first deploy is work
7: try to change some code in the App.js
8:npm run build (you will get the new main.77777.js)
9: firebase deploy
10: open your browser (chrome, firefox,ie), then get the error, Uncaught SyntaxError: Unexpected token <

how can i fixed this issue?

**What is the expected behavior?**

get right main.js when deploy to  firebase

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

    "firebase": "^4.1.2",
    "react": "^15.6.1",

error for ie, chrome, firefox.

**Comment by gaearon** [comment]
This is React repository. Could you please report this to [Create React App](https://github.com/facebookincubator/create-react-app) instead? We’ll also need a live example there because it’s hard to say what went wrong without seeing it. Thanks!
