### ISSUE TITLE
Is using `=>` instead of `bind(this)` still experimental, if so what does it means?

### ISSUE THREAD

**Issue by shakiba** [facebook/react#10318]
In [this documentation page](https://facebook.github.io/react/docs/handling-events.html), using arrow function instead of `this.fu.bind(this)` is marked as experimental.  Is it still considered experimental, if so why?

**Comment by Kovensky** [comment]
What is experimental is not the `=>` part, but the `handleClick =` part. The non-experimental way of writing it would be to do `this.handleClick =` inside the `constructor`.

**Comment by shakiba** [comment]
@Kovensky  I see.  So why is it experimental?  As far as I know it is Stage 3 proposal, so it is not considered *experimental* anymore.

**Comment by jquense** [comment]
Stage4 is when features become non experimental, stage3 still has a chance of not making it (it's happened before)

**Comment by chris-kobrzak** [comment]
@shakiba, according to Babel _arrow methods_, as I like to call them, are still in Stage 2 but it looks like they have now been promoted to Stage 3.

See:
https://babeljs.io/docs/plugins/transform-class-properties/
vs
https://github.com/tc39/proposal-class-fields

On a side, the Stage 2 Babel plugin doesn't do anything magical to arrow _methods_ - it simply transpiles them to arrow _functions_ defined within the constructor method ([example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=ATDGBsEMGduAhA9gJwNbAN4CgQgEaICuAdgCYBiJoALgJaLHAC8wAFAJTMB8mOuIyAKbVCyRtQAWtaADpaxaNUjFQggArJEAB0HJqATwDcfEAF8-poA)).

**Comment by gaearon** [comment]
Hope the discussion above helps! I'll close this but let me know if you have more questions.
