### ISSUE TITLE
[Documentation] Add version information

### ISSUE THREAD

**Issue by kyamaguchi81** [facebook/react#10324]
Please list [You’ll need to have Node >= 6 on your machine.]
before the description in [npm install -g create-react-app],
In [Creating a New Application] of the document https://facebook.github.io/react/docs/installation.html.

Because you want to know the required version before running the command

**Comment by gaearon** [comment]
If you run it with Node 4, it will use the last version of scripts that supported Node 4:

```
> create-react-app test123

Creating a new React app in /Users/dan/test123.

You are using Node v4.0.0 so the project will be boostrapped with an old unsupported version of tools.

Please update to Node 6 or higher for a better, fully supported experience.

[...]
```

Does this notice appear for you?

I think it’s fair to say you can still use it with Node 4, although the result will be an outdated version.

**Comment by gaearon** [comment]
Happy to take a PR adding the note though.

**Comment by kyamaguchi81** [comment]
>I think it’s fair to say you can still use it with Node 4, although the result will be an outdated version.

I think it's good.

>Happy to take a PR adding the note though.

I will make a pull request from next time.

Thank you.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#70

Let's continue the discussion there! Sorry for the inconvenience.
