### ISSUE TITLE
Prevent extension of synthetic event

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10327]
Based on discussion in https://github.com/facebook/react/issues/10322. We don’t support putting custom data into synthetic events. Maybe we should `Object.preventExtensions()` on them to make it clearer.

**Comment by jquense** [comment]
We should do a quick check (if possible) to see what bigger ui or form libraries do. AFAIK extending the events has been done before, though that may not be the case anymore (react-bootstrap did at one point). If libraries do though it'll be a certainly a breaking change for them to fix, hence the caution :)

**Comment by gaearon** [comment]
That’s a good point. Do you want to research this? The problem with putting data in events is that they get recycled so it’s likely to be confusing users (or event a source of bugs) either way.

**Comment by jquense** [comment]
yeah i'll take a look. I definitely agree its a good idea to prevent extensions here, just want to make sure are surprised by the change, and have enough heads up to adjust.

**Comment by sebmarkbage** [comment]
Isn't that what this warning is for?

https://github.com/facebook/react/blob/master/src/renderers/shared/shared/event/SyntheticEvent.js#L244-L274

(We should also just stop pooling instead.)

**Comment by gaearon** [comment]
Huh. I totally forgot we added this warning 😛
