### ISSUE TITLE
[Documentation] Improve tutorial example code write

### ISSUE THREAD

**Issue by hori031617** [facebook/react#10323]
I tried tutorial.

> 3. Delete all files in the src/ folder of the new project.

I think that good example code here.
For example `rm -f src/*`
Because, I had a misunderstanding remove src directory.

Thank you.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#71

Let's continue the discussion there! Sorry for the inconvenience.
