### ISSUE TITLE
Move benchmark dependencies out of main package.json

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10335]
We shouldn't require `nodegit` or `lighthouse` for working on React. Let's move them to a `scripts/bench/package.json` or similar so that they don’t take the time and space on regular installs.

**Comment by miniroadrunner** [comment]
Interesting! I haven't yet, but I'll give it a try in the morning, maybe it's a bit more malleable for my use case then.

Was that a deliberate change or just a consequence of the Fiber changes?

**Comment by gaearon** [comment]
Not sure what you mean. I’m saying that we added some packages to `package.json` `devDependencies` that aren’t strictly necessary for building or testing React. They should be moved to `scripts/bench/` or something like this so that they’re only installed when necessary.

**Comment by trueadm** [comment]
Merged PR for this :)
