### ISSUE TITLE
Use SRI in documentation links to UMD builds?

### ISSUE THREAD

**Issue by mjackson** [facebook/react#10332]
It seems there may be [a bit of confusion](https://github.com/facebook/react/issues/10294#issuecomment-318928557) about loading React via SRI from unpkg (CDN). I'd be happy to submit a PR with the appropriate `integrity` values in the `<script>` tags in `docs`, but just wanted to see if y'all were interested in doing that first. If not, feel free to close.

**Comment by spicyj** [comment]
We had this a long time ago (#5970, #6017, #6313). I don't feel strongly.

**Comment by virgofx** [comment]
Regardless of facebook/react's interest in using SRI tags I think it would still be beneficial for all projects to have these hardcoded and available via API as well. Opt-in approach similar to CDNJS.

**Comment by mjackson** [comment]
It looks like this issue has already been discussed and that the React team is aware of it (thanks for the links @spicyj), so I'll go ahead and close.

@virgofx If you'd like to follow up to add API support to unpkg, let's discuss in https://github.com/unpkg/unpkg-website/issues/48
