### ISSUE TITLE
onChange event doesn't fire while trying to type value in input using Appium (IOS)

### ISSUE THREAD

**Issue by ikhilko** [facebook/react#10347]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

onChange event doesn't fire while trying to type value in input using Appium (type value programmatically)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Also tried on Android - work fine. Only relates IOS.

**What is the expected behavior?**

onChange event should be fired while trying to type value in input using Appium

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React since 15.6.0 and up (15.5.4 works fine), iPhone 6s (IOS 10.3.2), Appium 1.6.5

**Comment by aweary** [comment]
Hey, @ikhilko! Thanks for the issue. Appium is probably setting the value by setting the `value` property on the input element. This won't work with React's controlled input implementation. I would recommend referring to Appium's documentation to see if there's a way to ensure actual keyboard events are being dispatched, or opening an issue in their issue tracker if not.

**Comment by ikhilko** [comment]
Hi, @aweary! Thanks for your response. Appium (and Selenium itself) use more complex logic to input value to the inputs. I will try investigate what they execute at that case. But it's very strange that that logic works fine on Android (Chrome), but doesn't work at IOS using React. Can you refer some information about how React works with controlled inputs? It will be very helpful in my research of this problem.

**Comment by ikhilko** [comment]
Looks like the same reason as issue #10135

**Comment by pkgondi** [comment]
@ikhilko: I'm facing same issue, did you get any solution for this issue.
Thank you
Kumar
