### ISSUE TITLE
Docs: Add note about checkboxes/radios and preventDefault

### ISSUE THREAD

**Issue by WickyNilliams** [facebook/react#10354]
**Do you want to request a *feature* or report a *bug*?**

Add a note to docs about preventDefault causing issues in change handlers for checkboxes/radios.

**What is the current behavior?**

There is no such note about the issue in docs. I had made a PR ( #3069) for this before, it had been merged, but it got lost (removed?) in the new docs. I was helping someone through this exact issue, and they asked "why isn't this covered in the docs?".

**What is the expected behavior?**

There should be an explanatory note in the docs

**Comment by jquense** [comment]
So if #10238 goes through this may inadvertently fix the underlying problem since we are switching radios/checkboxes to use onChange for real

**Comment by WickyNilliams** [comment]
Oh sweet! That would be _a lot_ better :)

**Comment by jquense** [comment]
#10238 is merged! That should take care of the concern I believe :)
