### ISSUE TITLE
react-dom-factories has a peerdep of ^15.5.4

### ISSUE THREAD

**Issue by brucewpaul** [facebook/react#10358]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

react-dom-factories has a peerdep of react@^15.5.4, but it seems as though it should work with any react@15

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

n/a

**What is the expected behavior?**

react-dom-factories works with react@^15

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@15.4.2

**Comment by gaearon** [comment]
I think we should just remove the peer dependency. It’s not very helpful and we’ll have to keep bumping it on every release while we’d rather leave this package alone.

**Comment by ljharb** [comment]
Maybe instead of removing it, set it to *?

**Comment by gaearon** [comment]
That works!

**Comment by gaearon** [comment]
Hmm. It doesn’t match prereleases. Which is pretty annoying for cases where we want people to try a beta.

**Comment by ljharb** [comment]
*-rc? There's got to be some way to say "match anything, but error if there's no react"

**Comment by gaearon** [comment]
Fixed in 1.0.1 (I just removed them).

>There's got to be some way to say "match anything, but error if there's no react"

AFAIK there isn’t 😞 . You could do with a direct dep when you control *which* prerelease you opt into, but we can’t do this from a peer. https://github.com/npm/node-semver#prerelease-tags

**Comment by ljharb** [comment]
Oh well - thanks for the fix :-) will it be released soon?

**Comment by gaearon** [comment]
Already released.

**Comment by ljharb** [comment]
Amazing, thanks!

**Comment by brucewpaul** [comment]
thanks for the quick release!
