### ISSUE TITLE
Async Top-level Hook Before Commit

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#10366]
_(This isn't needed for 16.0.)_

I think we're missing a top-level API. If you want to integrate with non-React code around you in an async way, then you probably have some parents around you. It's not always the case that you want to show those parents before React is done. Maybe you can hide them and then show them at the callback time.

However, it would be better if you could start building the tree async with React, and then get a callback *before* we trigger life-cycles so that you can insert the tree into the actual DOM and do whatever manipulation you need. Only after that do we trigger the life-cycles. That way they will have the CSS and layout information available to them by virtue of being in the document already.

I see two possible routes:

a) We just call out for this hook and then commit immediately after.

b) We invoke a callback and pass another function. That function, when invoked, does the actual commit. This approach has precedence in the DOM with "append async" and offscreen canvas.

The second option is probably preferable but we should only do that if we can do it efficiently and cleanly.

**Comment by acdlite** [comment]
I don't think I understand the benefits of option b. Could you explain what this sentence means?

> This approach has precedence in the DOM with "append async" and offscreen canvas.

**Comment by acdlite** [comment]
This is only relevant to mount, correct? Perhaps we should consider this feature as part of a more holistic redesign of the top-level mount/update/unmount API, as we've discussed previously.

**Comment by sebmarkbage** [comment]
This is probably relevant to top-level updates as well.

The benefit of option B is that I can delay the commit while I'm still doing other stuff. For example, I can render multiple React trees and wait for them all to complete before I finalize my tree and commit them all at once.

Regarding offscreen canvas etc. See this thread for a similar problem space: https://github.com/whatwg/html/issues/2139

I can't find it now but there's a proposal for a DOM API for inserting into the DOM asynchronously but not show it until a later commit point.

**Comment by sebmarkbage** [comment]
It would be nice to not need the container to exist yet. Something like:

```js
const namespace = 'https://www.w3.org/2000/svg';
const commit = await ReactDOM.prerender(<Foo />, namespace);
commit(container);
```

**Comment by acdlite** [comment]
Still need to figure out what to do about updates that happen between complete and commit. These updates will always be the result of prefetching data from the server inside `componentWillMount` and will have async priority. I think it should be fine to wait until the initial commit before doing any more work. If we get a high priority update, we should probably throw.
