### ISSUE TITLE
Dynamically created element is unable to load dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by nelsieborja** [facebook/react#10367]
dangerouslySetInnerHTML is not getting loaded when the component re-renders.

Sample declaration for dynamic Component:
```
class DynamicComp extends Component {
    render() {
        return React.createElement('div', this.props, [])
    }
}
```
Sample Usage:
`<DynamicComp dangerouslySetInnerHTML={{ __html: '<span />' }} />`

**Comment by gaearon** [comment]
If you look at the console, it says:

>Uncaught Error: Can only set one of `children` or `props.dangerouslySetInnerHTML`.

<img width="556" alt="screen shot 2017-08-03 at 1 05 22 pm" src="https://user-images.githubusercontent.com/810438/28921080-7614d1e6-784c-11e7-89ab-8a6b62178f8f.png">

If you supply both `children` (by passing three or more arguments to `createElement`) and `dangerouslySetInnerHTML` React doesn’t know which one to use.

If you change it to 

```js
        return React.createElement('div', this.props)
```

thus removing third argument (a child), it works.

**Comment by nelsieborja** [comment]
Yeah I got that, the thing is I want to add dynamic content into the component, but it seems React can't handle both.

```
class DynamicComp extends Component {
    _getDynamicContent() {
        return this.state.loading ? '<span className="loader" />' : null
    }
    render() {
        return React.createElement('div', this.props, [this.getDynamicContent()])
    }
}
```

`<DynamicComp dangerouslySetInnerHTML={{ __html: '<span />' }} />`
