### ISSUE TITLE
Array length cannot be read

### ISSUE THREAD

**Issue by moquita** [facebook/react#10383]
Hello, I am new in React and I'm trying to run a piece of code, where I have the following function in which I use a for to iterrate an array. But after I run it,it gives me the error:
Uncaught TypeError: Cannot read property 'length' of undefined.
Can someone help me understand what is wrong with this?
Thanks ^^''

movimentiOnClick: function (idSelected) {
        var itemSel = null;

        let i = 0
        for (i = 0; i< this.movimenti.length; i++) {
            var item = movementi[i];
            if (item.id = idSelected) {
                itemSel = item;
                // break;
            }
        }
        this.context.router.push({ pathname: '/listaeTabelle/details/', state: { item: itemSel } });
    },

**Comment by jozefpetro** [comment]
Are you sure, that you don't have typo in this.movimenti, because I see movementi[i] inside for loop.

**Comment by moquita** [comment]
oh i fixed the typo. Now the new error says Cannot read property 'movimenti' of undefined.
I think it is an error of how I use React syntax.

**Comment by jozefpetro** [comment]
Please provide code of whole component.

**Comment by jozefpetro** [comment]
I think that you want to access variable from state of your component and you have to bind 'this' to your event handler function in constructor of your class based 
`this.yourfunction  = this.yourfunction.bind(this)`

**Comment by jozefpetro** [comment]
Please refer to https://facebook.github.io/react/docs/handling-events.html

**Comment by moquita** [comment]
Thanks. I corrected it  by modifying a bit the code.

 movimentiOnClick: function (idSelected) {
        var itemSel = null;
        var movimenti = [];
        
        
        let i = 0
        for (i = 0; i < this.state.movimenti.length; i++) {
            var item = this.state.movimenti[i];
            if (item.id === idSelected) {
                itemSel = item;
                // break;
            }
        }
        console.log('What does it do'+itemSel);
        this.context.router.push({ pathname: '/listaeTabelle/details/', state: { item: itemSel } });
    },

**Comment by jozefpetro** [comment]
No problem, please use stackoverflow next time for this kind of issues. Here we discuss topics which are related to React development. Good luck with learning :) this issue can be closed ^

**Comment by aweary** [comment]
You can reference our [Where To Get Support](https://facebook.github.io/react/community/support.html) to find additional support resources.
