### ISSUE TITLE
Better explanation when component isn't imported

### ISSUE THREAD

**Issue by kud** [facebook/react#10381]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

```
TypeError: Illegal constructor.
ReactCompositeComponent.js:305
```

in console

**What is the expected behavior?**

```
TypeError: You probably didn't import the component `CSSTransition` (or whatever)  you're using.
ReactCompositeComponent.js:305
```

**Comment by aweary** [comment]
Hey, @kud! Can you provide an example that throws this error, along with the version of React you're using?

We do throw errors for when a component constructor is `undefined` ([example](https://jsfiddle.net/axts3wmj/))

```
React.createElement: type is invalid -- expected a string (for built-in components) or a 
class/function (for composite components) but got: undefined. You likely forgot to
export your component from the file it's defined in.

Check the render method of `App`.
    in App
```

**Comment by kud** [comment]
Hello @aweary, yes, I'll do asap. ;) Thank you!
