### ISSUE TITLE
(Non-issue) Need advise for adding authentication in a react app

### ISSUE THREAD

**Issue by acmoune** [facebook/react#10395]
In fact I would like to integrate Facebook authentication in my React app, and save user credentials in the database, along with additional data that will be used to authenticate with an API.

I have no idea about how to handle authentication and authorization in a React app. I went through some few books, but none of them touched that aspect. 

Can you point me to a book, a tutorial, any link ? whatever you think can point me to the right direction.

Thanks in advance.

**Comment by amal1994** [comment]
@acmoune  The best technique out there right now is to use Jason Web Token(JWT).
I am sure you can find decent amount of information on that online

**Comment by acmoune** [comment]
@amal1994, thanks for your reply. I am fine with the API authentication, I opted for HAWK in HapiJS. So I can include Hawk credentials in my request header, and fetch data from my API.

This is what I want to achieve:

1. User try to access a route in React Router that required Authentication (No idea how to set it)
2. User is redirected to a Login component that allow Facebook login
3. Upon successful login authentication, Facebook credentials are saved in a database, along with hawk credentials, and stored in a cookie
4. User can now authenticate with the API using credentials in his cookie and fetch data.

From what I know about JWT and HAWK, they are only concerned with step 4. My problem is steps 1 to 3.

Is that possible ? Am I getting something wrong ?

Thanks
