### ISSUE TITLE
react-test-renderer and shallow API mismatch

### ISSUE THREAD

**Issue by statianzo** [facebook/react#10390]
**Do you want to request a *feature* or report a *bug*?**
Feature

Currently, `react-test-renderer` and `react-test-renderer/shallow` have different APIs. Is there a reason for this? It would be helpful switching between them if shallow supported `create`. I can put together a PR for it if there's interest.

## react-test-renderer

```javascript
import TestRenderer from 'react-test-renderer';

it('renders', () => {
  const result = TestRenderer.create(<MyComponent />);
  expect(result).toMatchSnapshot();
});
```

## shallow

```javascript
import ShallowRenderer from 'react-test-renderer/shallow';

it('renders', () => {
  const renderer = new ShallowRenderer()
  const result = renderer.render(<MyComponent />);
  expect(result).toMatchSnapshot();
});
```

**Comment by amal1994** [comment]
hi

**Comment by amal1994** [comment]
as

**Comment by gaearon** [comment]
There's even more mismatch if you consider TestUtils.

I would say an isolated PR is probably not worth it, unless you can prepare a more complete proposal of how to revamp those APIs to mirror each other, as well as work on codemods (since there's already a lot of code using them).

**Comment by pspeter3** [comment]
Is there a current plan to unify them?

**Comment by gaearon** [comment]
The shallow renderer has moved to https://github.com/NMinhNguyen/react-shallow-renderer. If this is still relevant, please feel free to file this issue there. Thanks!
