### ISSUE TITLE
[Request] Exports HTMLDOMPropertyConfig, SVGDOMPropertyConfig, and ARIADOMPropertyConfig in v16+

### ISSUE THREAD

**Issue by gfx** [facebook/react#10391]
This is a feature request.

In React v15.6,  HTMLDOMPropertyConfig, SVGDOMPropertyConfig, and ARIADOMPropertyConfig are available by `import` them directly, e.g. `import ReactHTMLDOMPropertyConfig from 'react-dom/lib/HTMLDOMPropertyConfig'`. In v16, however, they are no longer available.

I think they are not public parts of react-dom, but they are inevitable to implement https://github.com/Deschtex/html2react , a library to build React DOM from an HTML text.

See https://github.com/Deschtex/html2react/blob/master/src/react-properties-map.js#L1-L2 for how to use them.

**Comment by gaearon** [comment]
I don't think we plan to expose them directly. Their format sometimes changes and we want to be able to make more under the hood changes to them in the future.

While it is a bit annoying I encourage you to just copy and paste them (and update if you notice changes on our side).

**Comment by remarkablemark** [comment]
@gfx I've created a package [`react-dom-core`](https://github.com/remarkablemark/react-dom-core) which copies and exposes [modules in lib](https://unpkg.com/react-dom@15.6.2/lib/) from `react-dom@15.6.2`.
