### ISSUE TITLE
Add tests for <select multiple> => <select> transition

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10401]
I deleted it in https://github.com/facebook/react/pull/10281 because it wasn’t testing the public API, and it was hard to say if it tested the path the code actually took.

We should either add a similar test against public API or an equivalent test to manual fixtures.
See https://github.com/facebook/react/pull/10281#issuecomment-320471544 for details.

**Comment by raunofreiberg** [comment]
This should be tested now. 
https://github.com/facebook/react/blob/de5102c4cd9a0ece37872c5a1c6b1e1345b8afef/packages/react-dom/src/__tests__/ReactDOMSelect-test.js#L337

**Comment by nhunzaker** [comment]
So it is, 👍 thanks!
