### ISSUE TITLE
Broken "date inputs" test DOM fixture

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#10408]
1. Open "Date Inputs" test harness: http://localhost:3000/date-inputs
1. Click the little (x) to clear the input

> **RangeError: Invalid time value**
> src/components/fixtures/date-inputs/switch-date-test-case.js:43

This fixture is broken for 15.6.1 and 16 beta 3.

**Comment by gaearon** [comment]
cc @aweary

**Comment by bvaughn** [comment]
It's not super high-pri and I'm happy to fix it later. Just didn't want to derail beta+sync work for it so I filed this to follow up on.

**Comment by aweary** [comment]
@bvaughn it was an easy fix, PR open at https://github.com/facebook/react/pull/10412 👍

**Comment by bvaughn** [comment]
You rock.
