### ISSUE TITLE
Warn early if event listener is not a function

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10407]
We used to throw if event listener is not a function in Stack:

```js
ReactDOM.render(
  <h1 onClick={{}}>Hello World!</h1>,
  document.getElementById('container')
);
```

<img width="565" alt="screen shot 2017-08-08 at 3 41 08 pm" src="https://user-images.githubusercontent.com/810438/29077502-2646412e-7c50-11e7-8c99-3b7f6c0a2589.png">

Fiber silently ignores this.

I think we should throw. This would let us add support for objects (e.g. for passive listener configuration) if we want to in a minor rather than a major.

**Comment by aweary** [comment]
I'll take this one 😀

**Comment by gaearon** [comment]
You got it!

**Comment by aweary** [comment]
@gaearon so it looks like Fiber _will_ throw the same error, but it does so lazily. Once you try to click the element it will trigger that invariant. The invariant currently lives in [`EventPluginHub.getListener`](https://github.com/facebook/react/blob/master/src/renderers/shared/shared/event/EventPluginHub.js#L122), so we could just move it somewhere else like `ReactDOMFiberComponent` so we throw early?

**Comment by gaearon** [comment]
I would prefer that.

**Comment by gaearon** [comment]
It's worth double checking with @sebmarkbage if this was intentional.

**Comment by sebmarkbage** [comment]
This was indeed intentional. We could warn early, but not throw. Because we should be able to lazily deal with event listeners by only looking at the properties when an event is triggered. Currently we loop over them all but this is an optimizable path.

**Comment by gaearon** [comment]
Warning early sounds sensible then.

**Comment by flarnie** [comment]
Hi - just wondering what the status is on this.

**Comment by aweary** [comment]
@flarnie great timing, I just opened https://github.com/facebook/react/pull/10453 😄
