### ISSUE TITLE
Show a better message if React is not loaded

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10406]
Currently if React is not loaded, ReactDOM shows this:

<img width="664" alt="screen shot 2017-08-08 at 3 36 52 pm" src="https://user-images.githubusercontent.com/810438/29077217-784c7624-7c4f-11e7-88bc-b055407523a9.png">

We should throw a nicer error message in the entry point I think.

**Comment by aweary** [comment]
@gaearon this throws in `ReactGlobalSharedState`, which is also used/re-exported by `react-native`. Should we include the invariant there and provide a renderer-agnostic error message, or try to include the error earlier in `react-dom`?

**Comment by gaearon** [comment]
I'm not sure. On the one hand throwing in that specific place would prevent this specific confusing error. On the other hand, there's no guarantee that it will throw there first. Renderer might use APIs on React object earlier.

**Comment by aweary** [comment]
Is there a way to determine in which order rollup will load modules, or explicitly include a snippet of code at the top of the bundle? If I add the invariant to the entry point for the bundle, it still fails with the cryptic error since the imported modules are hoisted to the top of the bundle.

**Comment by gaearon** [comment]
You can add a module like checkReact and then make it first import in the renderer. Then it's guaranteed to execute first.
