### ISSUE TITLE
Documentation about which style numeric values are treated as pixels is missing

### ISSUE THREAD

**Issue by Kovensky** [facebook/react#10418]
This used to exist in the React 15 documentation under the Tips section, but mentions to this support are now missing entirely.

The old documentation page: https://github.com/facebook/react/blob/8cac523beaaacfeae179ca14a1d8a46d82892016/docs/tips/06-style-props-value-px.md

This was removed in commit 455d2d1b48e5cdaeac5d0b4fd92b29b4d52bcaec

**Comment by prashanthr** [comment]
Looking for this?
https://reactjs.org/docs/dom-elements.html#style

**Comment by Kovensky** [comment]
@prashanthr this talks about the style key names, but does not talk about the values. This is specifically the loss of the documentation about about the case where, say, `style={{ width: 200 }}` (a `number` value) will become `style="width: 200px;"` in the DOM.

It looks like I, for some reason, linked to the wrong page in the very part that was supposed to prove my point. I'll fix the link.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#27

Let's continue the discussion there! Sorry for the inconvenience.
