### ISSUE TITLE
Dynamic Names for Snapshot Files with jest

### ISSUE THREAD

**Issue by ishantoberoi** [facebook/react#10419]
Hi, 
I am using Snapshot testing for my application.
My application has a theme, based on some parameter passed to the component. The theme changes the look n feel of the app, by adding some classes to the elements.

I want to generate snapshots for the components for both the themes.
But I do not want to duplicate the code or keep two separate .test/.spec files for this.

Is there a way I can generate snapshot files based on what theme is passed, with just one spec file.

#### Expected Behaviour:
If, two theme values are: dark and light
One Component.spec.js file should generate Component.dark.spec.js.snap or Component.light.spec.js.snap based on the theme passed.

This way I can have separate separate snapshots based on theme with just one source .spec file.

**Comment by gaearon** [comment]
I don't think Jest supports this (or intends to). But it's better to ask in the Jest repository. This is the React repository, and we are not working on Jest.

**Comment by ishantoberoi** [comment]
@gaearon Thank You!
