### ISSUE TITLE
Can we change the React.creatClass property of getDefaultProps from a callback to an Object just like the propTypes?

### ISSUE THREAD

**Issue by zifeiyu666** [facebook/react#10423]
I think the propTypes is an Object, but the getDefaultProps is a callback, is very uncomfortable. Can we change it? if not ,can i know why?

**Comment by TrySound** [comment]
@zifeiyu666 React.Component class takes `defaultsProps` static property as an object.

**Comment by gaearon** [comment]
You can use `defaultProps` as property name, it will work.
