### ISSUE TITLE
React.Component Docs - displayName

### ISSUE THREAD

**Issue by hnordt** [facebook/react#10438]
In https://facebook.github.io/react/docs/react-component.html we have the following statement:

> **displayName**
> The `displayName` string is used in debugging messages. JSX sets this value automatically; see JSX in Depth.

I'm almost sure it's incorrect. Neither React or JSX sets `displayName` automatically (another error: in the docs "JSX in Depth" doesn't even mention `displayName`).

Maybe we could change it to something like:

> **displayName**
> The `displayName` string is used in debugging messages. Usually you don't need to set it explicitly because it's inferred from the function or class name that creates the component. You might want to set it explicitly if you want to display a different name for debugging purposes or when you create a Higher-Order Component, see [Wrap the Display Name for Easy Debugging](https://facebook.github.io/react/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging) for details.

Makes sense?

**Comment by flarnie** [comment]
Makes sense to me - I think your suggestion is an improvement. Would you like to open a PR for that?

**Comment by hnordt** [comment]
@flarnie sure, I'll do. Thanks.

**Comment by hnordt** [comment]
@flarnie I've created the pull request: #10438
