### ISSUE TITLE
ReactDOM Docs - Confusing Sentence

### ISSUE THREAD

**Issue by hnordt** [facebook/react#10435]
In https://facebook.github.io/react/docs/react-dom.html we have the following statement:

> ReactDOM.render() does not modify the container node (only modifies the children of the container). It may be possible to insert a component to an existing DOM node without overwriting the existing children.

I think that `It may be possible to insert (...)` should be replaced with `In the future, it may be possible to insert (...)`. Am I wrong?

**Comment by flarnie** [comment]
I'm 90% sure you are right. I don't know of any cases right now where you would/could "insert a component into an existing DOM node without overwriting the existing children".

And even if you could, that statement is pretty vague. @lacker the earliest diff touching this line was when you [did a big docs update,](https://github.com/facebook/react/commit/455d2d1b48e5cdaeac5d0b4fd92b29b4d52bcaec) do you have any context on what this note was referring to?

**Comment by gaearon** [comment]
I have no idea what that sentence means. Removing it in https://github.com/facebook/react/pull/11096.

**Comment by sophiebits** [comment]
This is now secretly true but I don't think we're advertising it yet.

**Comment by gaearon** [comment]
The docs predate this addition though so they must've referred to something else. 😛

**Comment by sophiebits** [comment]
I think it must have meant "In the future," but I'm not sure why it would have said that because I can't remember ever wanting to commit to that in the past.

**Comment by sophiebits** [comment]
I think it must have meant "In the future," but I'm not sure why it would have said that because I can't remember ever wanting to commit to that in the past.

**Comment by muzuiget** [comment]
This confusing sentence still exists at latest docs.

**Comment by gaearon** [comment]
Send a PR please to https://github.com/reactjs/reactjs.org?

**Comment by hnordt** [comment]
@gaearon may I send it?
