### ISSUE TITLE
Tutorial has nonsense sentence, that is run on.

### ISSUE THREAD

**Issue by janat08** [facebook/react#10433]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Note that onClick on the DOM <button> component has a special meaning to React, but we could have called onClick prop in Square and handleClick in Board something else.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
there's no verb in handleClick in Board part, and it's not part of first clause
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
Sorry if it's confusing! Does the meaning become clearer if you think of "onClick prop in Square" and "handleClick in Board" as two things (e.g. A and B)?

Then the intended meaning was:

>Note that onClick on the DOM component has a special meaning to React, but we could have called (A) and (B) something else.

If you have suggestions on how to split this sentence to make it clearer, please let me know. Thanks!

**Comment by janat08** [comment]
Note that onClick on the DOM <button> component has a special meaning to React, but we could have called onClick prop in Square and handleClick in Board something else. It is, however, a common convention in React apps to use on* names for the handler prop names and handle* for their implementations.

**Comment by janat08** [comment]
Yes, i now realize what this means. Controlled components, or controller components, or whatever weren't introduced, as such when you say "onClick on the DOM" and then use "in" references to titles of comparative things. So i think component from "DOM component" ought to go, or DOM or in be used.

**Comment by janat08** [comment]
or use word key. make the whole thing shorter without reference board or square.

**Comment by flarnie** [comment]
Would you like to make a PR updating that sentence @janat08 ? I'm not sure I understand specifically what you propose changing it to. I agree it could probably be clearer. Thanks for flagging this!

**Comment by janat08** [comment]
english isn't my thing

**Comment by flarnie** [comment]
If someone in the community wants to brainstorm a better phrasing that would be great, I would review a PR. Otherwise I'll try to come back and help with this - for now focused on shipping some other stuff. Thanks for your patience.

**Comment by janat08** [comment]
Some one else already edited it, so I'll just write what I think is best instead of requesting pull.

Note that use of onClick within tag either will command React to listen for event, if it's not user defined component, or abide by naming convention that designates property (prop) as event emit handler, while handle in handleClick designating event consumer.

**Comment by landermkerbey** [comment]
Throwing my hat in the ring on this:

Note that DOM `<button>` element's `onClick` attribute has a special meaning to React, but we could have named Square's `onClick` prop or Board's `handleClick` method differently. It is, however, conventional in React apps to use `on*` names for event propagation and `handle*` for event consumption.

Observations:
1. Addresses's @janat08's concern about the use of the word 'component' being confusing in this context by using the term 'element,' a term which is both widely understood and the referent used in the HTML spec (e. g. 'root element')
2. Placing the names of the parent element/component before the attribute/prop/method emphasizes that the reason the first `*Click` term is treated differently from the second and third has to do with where they are applied, which was not necessarily clear in the prior wording.
3. 'Differently' is still ambiguous. In a technical setting this might either mean that we are going to be told later about a finite range of acceptable nomenclature, or that an arbitrary name would be acceptable. If I'm not mistaken, the latter is the case, so we might consider replacing 'differently' with 'anything we want.'
4. 'Common convention' is redundant. Practice becomes convention by commonality, hence 'conventional.'
5. I think @janat08's suggestion to use 'propagation' and 'consumption' is sound. It seems unlikely that our intended readership would not understand 'consumption' in this context, but if that were the case, viable alternatives might be 'processing,' or 'execution.'

**Comment by gaearon** [comment]
@landermkerbey I love your wording! I tweaked it a tiny bit and landed in https://github.com/facebook/react/commit/a2efa51b9227a2224bb23006c33e4aa06afc8070. I didn't go with "propagation" and "consumption" in the end because "propagation" has a specific meaning with event systems and I don't want to confuse people with it.

You have a good eye for the documentation constraints, so I'd appreciate if you could take a pass over other parts of the docs and perhaps send some PRs :-)
