### ISSUE TITLE
Error in 16 beta: undefined is not a function (evaluating 'owner.getName()')

### ISSUE THREAD

**Issue by spicyj** [facebook/react#10443]
This line is wrong in Fiber and crashes:

https://github.com/facebook/react/blob/58e6edeef61f5ab5b81530820571213161940d6a/src/renderers/native/findNodeHandle.js#L79

It should be changed to use getComponentName(owner).

**Comment by iansu** [comment]
I'd like to take this issue.

**Comment by acdlite** [comment]
@iansu Cool, it's yours. This will help us release 16 stable.

**Comment by GabrielAmazonas** [comment]
Cool! I would like it too, but I have arrived too late

**Comment by spicyj** [comment]
Ahh @iansu it looks like we skipped over you after you claimed it. Really sorry about that.

@iansu @GabrielAmazonas Is one of you interested in writing a test that would have caught this? It can be added to src/renderers/native/__tests__/ReactNativeMount-test.js – try to trigger the warning and verify that console.error is called. There should be other tests you can use for checking a warning as an example.

**Comment by acdlite** [comment]
@iansu Oh I'm so sorry, I didn't realize it was a different person :( Should have paid closer attention, my bad

**Comment by GabrielAmazonas** [comment]
@acdlite! Yes, totally! Should I make a PR directly?
