### ISSUE TITLE
Unmounting React node

### ISSUE THREAD

**Issue by gassorr** [facebook/react#1044]
I'm trying to unmount a React.js node with `this._rootNodeID`

```
 handleClick: function() {

    React.unmountComponentAtNode(this._rootNodeID)

 }
```

But it returns `false`.

The `handleClick` is fired when I click on an element, and should unmount the root-node.

I've tried this as well:

```
  React.unmountComponentAtNode($('*[data-reactid="'+this._rootNodeID+'"]')[0])
```

That selector works with `jQuery.hide()`, but not with unmounting it, while the documentation states it should be a `DOMElement`, like you would use for `React.renderComponent`

After a few more tests it turns out it works on some elements/selectors.

It somehow works with the selector: `document.getElementById('maindiv')`, where `maindiv` is an element not generated with React.js, and just plain html. Then it returns `true`.

But as soon as I try and select a different `ElementById` that is generated with React.js it returns `false`. And it won't work with `document.body` either, though they all essentially return the same thing if I `console.log` them (`getElementsByClassName('bla')[0]` also doesn't work)

There should be a simple way to select the node via this, without having to resort to jQuery or other selectors, I know it's in there somewhere..

**Comment by amit-jamwal** [comment]
Hi
I tried to use
ReactDom.unmountComponentAtNode(document.getElementById('abc'));
but it gives me following warning:

Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.

**Comment by gaearon** [comment]
@amit-jamwal The node you passed there must be the same one that you previously passed to `ReactDOM.render()`. That’s what the warning says: you want to be unmounting the container node you renderered *into*, not a node managed by React that is defined in some component’s `render()` method. To unmount an inner node managed by React, use `setState` as described above.

**Comment by JashonWang** [comment]
I am confused with the use of unmountComponentAtNode, @chenglou as you said, I should pass the container of the component but not the targetDOM of the it.But if I have a parent component that displays:
`var Fruit = React.createClass({`
		`render:function(){`
			`return (`
				`<div id="fruit">`
					`<Apple></Apple>`
					`<Grapes></Grapes>`
				`</div>`
			`);`
		`}`
	`});`
	`var Apple = React.createClass({`
		`render:function(){`
			`return (`
				`<div>I am an apple ~</div>`
			`);`
		`}`
	`});`
	`var Grapes = React.createClass({`
		`render:function(){`
			`return (`
					`<div>I am grapes ~</div>`
			`);`
		`}`
	`});`
	`React.render(<Fruit />,document.getElementById('app'));`
and I want to remove the Apple component but retain the Grapes. I tried to use the unmoutComponentAtNode like this:
`React.unmountComponentAtNode(document.getElementById('fruit'))` 
but it still return false.Is `document.getElementById('fruit')` not a container of `<Apple>` ?

**Comment by jimfb** [comment]
@JashonWang Usage questions should be asked on StackOverflow, as we use github issues for tracking bugs in the React core.

**Comment by JashonWang** [comment]
@jimfb Alright,thanks.

**Comment by gaearon** [comment]
@JashonWang This comment covers exactly that scenario: https://github.com/facebook/react/issues/1044#issuecomment-34588968.

**Comment by ahgharian** [comment]
@gaearon -- should `unmountComponentAtNode` be used to unmount a component that was created with `React.createPortal`?
