### ISSUE TITLE
Error with react_perf - Failed to execute 'measure' on 'Performance': The mark '1::unmount' does not exist

### ISSUE THREAD

**Issue by djeeg** [facebook/react#10450]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Hi

When using react_perf I am getting this error, which seems to crash the render

> ReactDebugTool.js:228 DOMException: Failed to execute 'measure' on 'Performance': The mark '1::unmount' does not exist.
>     at markEnd (webpack:///./node_modules/react-dom/lib/ReactDebugTool.js?:226:21)
>     at Object.onUnmountComponent (webpack:///./node_modules/react-dom/lib/ReactDebugTool.js?:345:5)
>     at eval (webpack:///./node_modules/react-dom/lib/ReactServerRendering.js?:48:40)
>     at ReactServerRenderingTransaction.perform (webpack:///./node_modules/react-dom/lib/Transaction.js?:143:20)
>     at renderToStringImpl (webpack:///./node_modules/react-dom/lib/ReactServerRendering.js?:43:24)
>     at renderToString (webpack:///./node_modules/react-dom/lib/ReactServerRendering.js?:73:10)

If I modify this:

https://github.com/facebook/react/blob/15.6-dev/src/renderers/shared/ReactDebugTool.js#L299

    try {
        performance.measure(measurementName, markName);
    } catch(err) {
      console.error(err);
    }
	
Then i get 2-3 errors per page refresh, however the flame graph looks to be working

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
No error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome 60.0.3112
react 15.6.1
react-dom 15.6.1

**Comment by gaearon** [comment]
I'd expect this not to happen in React 16.
