### ISSUE TITLE
License headers are missing on built bundles

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#10458]
Our built files are missing license headers. 

cjs has no headers:
https://unpkg.com/react@16.0.0-beta.5/cjs/react.development.js
https://unpkg.com/react-dom@16.0.0-beta.5/cjs/react-dom.development.js

umd has headers identifying the bundle name but not the license:
https://unpkg.com/react@16.0.0-beta.5/umd/react.development.js
https://unpkg.com/react-dom@16.0.0-beta.5/umd/react-dom.development.js

Both should have license headers similar to this:

```
/**
 * React v15.6.1
 *
 * Copyright 2013-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 */
```

We likely just need to change the code in getBanner in scripts/rollup/build.js. https://github.com/facebook/react/blob/b4a3e3b34594759c90aef1694d2166b2d1126fa1/scripts/rollup/build.js#L78

You can test by running `yarn build` and looking in build/packages.

cc @trueadm

**Comment by gaearon** [comment]
Can we just include a fbme link like Lodash does?
https://unpkg.com/lodash@4.17.4/lodash.min.js

I think we consciously didn't add the whole block because it seemed like this is more of a build product than source (and the wording seems to assume you're looking at the source code).

**Comment by gzhappysky** [comment]
I can take this one. @spicyj @gaearon

**Comment by gaearon** [comment]
We haven't quite decided what to do here, let's wait until we hear back from the lawyers.

**Comment by spicyj** [comment]
Let's keep the old headers we had for the time being. Maybe we can condense them in the future.

@gzhappysky Still interested?

**Comment by gzhappysky** [comment]
yes, Still interested, I will complete today. @spicyj

**Comment by marokac** [comment]
the license headers are missing on the build bundles..there you right
