### ISSUE TITLE
Excessive, duplicative variable assignments in CommonJS build

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#10469]
Followup from #10385, it looks like the CommonJS build is saving short variable name references to long property names, however it does this in a bunch of places. The net output is a larger build because the referenced names (like `IndeterminateComponent`) are duplicated quite a bit:

For example:

```javascript
 D = {
        IndeterminateComponent: 0,
        FunctionalComponent: 1,
        ClassComponent: 2,
        HostRoot: 3,
        HostPortal: 4,
        HostComponent: 5,
        HostText: 6,
        CoroutineComponent: 7,
        CoroutineHandlerPhase: 8,
        YieldComponent: 9,
        Fragment: 10
    },
    F = {
        ELEMENT_NODE: 1,
        TEXT_NODE: 3,
        COMMENT_NODE: 8,
        DOCUMENT_NODE: 9,
        DOCUMENT_FRAGMENT_NODE: 11
    },
    xa = D.HostComponent,
    ya = D.HostText,
    za = F.ELEMENT_NODE,
    Aa = F.COMMENT_NODE,
    Ba = z.ID_ATTRIBUTE_NAME,
```

The UMD build does not have any of these tokens. The CJS build doesn't crush the names either. Later in the build there are things like this:

```javascript
var Mf = Qe.reconcileChildFibers,
    Nf = S.popContextProvider,
    Of = D.IndeterminateComponent,
    Pf = D.FunctionalComponent,
    Qf = D.ClassComponent,
    Rf = D.HostRoot,
    Sf = D.HostComponent,
    Tf = D.HostText,
    Uf = D.HostPortal,
    Vf = D.CoroutineComponent,
    Wf = D.CoroutineHandlerPhase,
    Xf = D.YieldComponent,
    Yf = D.Fragment,
    Zf = L.Placement,
    $f = L.Ref,
    ag = L.Update,
    bg = R.OffscreenPriority;
```

This duplicates a lot: If you look in the CJS build, something along the lines of a = d.HostNode shows up in like 10 places. This is true of all of these tokens.

Here's a beautified version for reference:
https://gist.github.com/nhunzaker/69ede0d4014d9c590908398ac6bc6c13

**Comment by gaearon** [comment]
I think GCC probably strips this way. I don't see it in GCC'd builds.
