### ISSUE TITLE
react-dom.min.js on unpkg CDN is returning 404

### ISSUE THREAD

**Issue by iconix** [facebook/react#10465]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Requests to https://unpkg.com/react-dom@15/dist/react-dom.min.js are returning 404 Not Found (after redirect to https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

`$ curl -L https://unpkg.com/react-dom@15/dist/react-dom.min.js`
`Cannot find file "/dist/react-dom.min.js" in package react-dom@15.6.1`

**What is the expected behavior?**

Minimized version of ReactDOM and 200 Success.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15/15.6.1

Unpkg doesn't seem to have a status page. Also, the unminified version (https://unpkg.com/react-dom@15.6.1/dist/react-dom.js) returns a 503 with the message `Timeout of 25 seconds exceeded` (this response occurs in less than a second though).

**Comment by goldo** [comment]
https://unpkg.com/react-dom@15.6.0/dist/react-dom.min.js
is available
graphiql died here because of this :(

**Comment by gaearon** [comment]
There is nothing we can do on our side, the problem is with unpkg (which we don't manage).

Let's track this in https://github.com/unpkg/unpkg-website/issues/54.

**Comment by gaearon** [comment]
Fixed now.
