### ISSUE TITLE
Looking for clarification: Deprecation warnings for react-dom-factories 

### ISSUE THREAD

**Issue by andres-torres-marroquin** [facebook/react#10460]
Hello,

It looks to me that the use of `react-dom-factories` will be mandatory for 16.x versions for those that use `React.DOM`, is this information correct?
Also I'm wondering if we're going to have deprecation warnings for the use of `React.DOM` on the 15.x.x versions.

Thanks a lot,

**Comment by jquense** [comment]
There should already be deprecation warnings in v15 for `React.DOM` You re definitely welcome to use `react-dom-factories` forever, they were split out from React proper, which is why they are deprecated, there isn't a problem using the external pacakge
