### ISSUE TITLE
React website's code textareas are broken

### ISSUE THREAD

**Issue by slice** [facebook/react#10464]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

The code `<textarea>`s on React's website seem to be broken.

![](https://owo.sh/ce2dec.png)

Some inspection reveals that the `unpkg.com` URL being used by the website (https://unpkg.com/codemirror@5.15.2) is 404ing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

1. Visit the React website.

**What is the expected behavior?**

The code inputs function as expected.

**Comment by gaearon** [comment]
cc @mjackson

This file seems to work for me. Is there any known Unpkg issue?

**Comment by gaearon** [comment]
There is nothing we can do on our side, the problem is with unpkg (which we don't manage).

Let's track this in unpkg/unpkg-website#54.

I'm hopeful this can be solved soon so we won't need to change the CDN.

**Comment by mjackson** [comment]
Thanks for the ping, @gaearon. I'm looking into it.
