### ISSUE TITLE
Window Object for Virtual Dom

### ISSUE THREAD

**Issue by samvel451811** [facebook/react#10479]
Hi There. I have a question.

Can I use Javascript window object in jsx file ?
Is it DOM Manipulation ?
Is it changing the virtual DOM ?
and what is the best place to use Window object in ES6 jsx file.

**Comment by jquense** [comment]
yes you can use the `window` object. your react code is run in a browser, so has access to all the normal browser DOM api's and objects. the term "Virtual DOM" is misleading, react doesn't replace or alter the DOM, instead it keeps a description of its component tree and compares it to the next version when something updates (in your React components) It then updates the DOM with the smallest set of changes necessary. 

You can think of the `window` and `document` objects as "below" React, so if you change any DOM nodes manually without going through the React update cycle you may confuse React and break things. I'd suggest working through the guides on the react website to get a better understanding of how things interact, this is one specifically about using the DOM directly.  https://facebook.github.io/react/docs/refs-and-the-dom.html
