### ISSUE TITLE
Remove old dist-tags

### ISSUE THREAD

**Issue by Haroenv** [facebook/react#10478]
**Do you want to request a *feature* or report a *bug*?**

bug I guess

**What is the current behavior?**

There are a few tags on npm that I think aren’t used anymore (see [the registry](http://registry.npmjs.com/react))

```json
{  
   "dist-tags":{  
      "latest":"15.6.1",
      "0.10.0-rc1":"0.10.0-rc1",
      "0.11.0-rc1":"0.11.0-rc1",
      "next":"16.0.0-beta.5",
      "dev":"15.5.0-rc.2",
      "0.14-stable":"0.14.9",
      "15-next":"15.6.0-rc.1"
   }
}
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

These tags can be removed (see [docs](https://docs.npmjs.com/cli/dist-tag))

**What is the expected behavior?**

Only supported tags existing?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
I wonder if anyone accidentally relies on them. I guess there's no way to know?

**Comment by Haroenv** [comment]
Yeah, I don't think we can get the downloads of a tag :thinking:

**Comment by gaearon** [comment]
I removed them. Don’t think we ever publicly advertised using either of these tags except for `next`.

**Comment by Haroenv** [comment]
cool!
