### ISSUE TITLE
React synthetic mouseenter event fires before dom mouseleave event

### ISSUE THREAD

**Issue by johnjesse** [facebook/react#10471]
**Do you want to request a *feature* or report a *bug*?**
Bug (I think)

**What is the current behavior?**
If you have two elements next two each other and the mouse moves from element 1 to element 2 then if I have registered an event listeners as below
```
element1.addEventListener('mouseenter', () => ...)
element2.addEventListener('mouseleave', () => ...)

element2.addEventListener('mouseenter', () => ...)
element2.addEventListener('mouseleave', () => ...)
```

We see that the mouseleave event is *always* fired before the mouse enter event.

The same is true if I have a react component as follows
```
const MyComponent = () => (
    <div>
        <div
            id="div1"
            onMouseEnter={() => ...}
            onMouseLeave={() => ...}
        >
            Div 1
        </div>
        <div
            id="div2"
            onMouseEnter={() => ...}
            onMouseLeave={() => ...}
        >
            Div 2
        </div>
    </div>
);
```
again the mouse enter events fire after the mouse leave events, for elements sharing the boundary.

*However*

If I mix events, and use synthetic react events for mouse enter and dom events for mouse leave I find that the mouse enter event handler is triggered before the mouse leave event handler for elements sharing the same boundary

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
CodePen: https://codepen.io/johnjwood/pen/QMOeEP?editors=0111

**What is the expected behavior?**
Mouse enter should always fire after mouse leave even when we are using a mixture of synthetic and dom events

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.6.1,
OS: windows 7;

Broken in both:
Chrome: 60.0.3112.90
IE: 11.09600.18738CO

**Comment by aweary** [comment]
Thanks for taking the time to write up this issue @johnjesse! As far as I know, interleaving native events with React's synthetic events isn't something we support. We listen for events at the top-level and simulate the bubble and capture phases, so the ordering of events will likely always out of sync with native events.

**Comment by johnjesse** [comment]
Fair enough, I wasn't sure it was supported (or even should be supported -> although it would be nice to be able to interleave native and synthetic events without worrying about potential ordering issues)

It was just something I was really not expecting, took me a while to figure out what was causing it.

**Comment by aweary** [comment]
I'm going to close this out since this isn't supported. I suggest that if two or more events are order-dependent, they should be registered in the same system (native or synthetic).

**Comment by monkindey** [comment]
hi, @aweary , synthetic event will simulate the bubble and capture phases, and will listen for events at the top-level which will lead to the event.stopPropagation not work. And because of the simulation, the initialization time will slower as dan said at https://github.com/facebook/react/issues/10703#issuecomment-329336129 . Also, React is not support IE8 as well. So will the synthetic event in React be deprecated in the future ?
