### ISSUE TITLE
Element Variables doesn't work in Codepen.

### ISSUE THREAD

**Issue by tsmvision** [facebook/react#10486]
**Do you want to request a *feature* or report a *bug*?**
 bug
**What is the current behavior?**
the code doesn't work.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
Displaying result. Nothing showed up.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Browser: Version 60.0.3112.101 (Official Build) (64-bit)
OS: Ubuntu 16.04LTS
React: 
The Codepen uses as follows:
https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react.js
https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react-dom.js

**Comment by gaearon** [comment]
Can you link to that codepen?

**Comment by Necmttn** [comment]
it's working.
https://codepen.io/Necmttn/pen/PKQNxw

from pen settings. 
you need to add 
![image](https://user-images.githubusercontent.com/5212808/29449606-f5c3d59e-842d-11e7-85ba-794855cdc5f0.png)
current versions Codepen uses:
https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react.min.js
https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-dom.min.js

**Comment by aweary** [comment]
Since there's been no response I'm closing and assuming @tsmvision has figured out the issue.
