### ISSUE TITLE
how to solve  ReactDom is not defined  ,react with webpack  

### ISSUE THREAD

**Issue by lbc123456** [facebook/react#10480]
Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
app.js?bd9c:6 Uncaught ReferenceError: ReactDOM is not defined
    at eval (app.js?bd9c:6)
    at Object.<anonymous> (main.bundle.js:645)
    at __webpack_require__ (main.bundle.js:20)
    at main.bundle.js:63
    at main.bundle.js:66
(anonymous) @ app.js?bd9c:6
(anonymous) @ main.bundle.js:645
__webpack_require__ @ main.bundle.js:20
(anonymous) @ main.bundle.js:63
(anonymous) @ main.bundle.js:66

 "react": "^15.6.1",
  "react-dom": "^15.6.1"

**Comment by jquense** [comment]
You are probably trying to reference (use) ReactDOM without importing or requiring it in your File. You will want to check the line number in referenced in the stack trace to see where the problem is.

**Comment by lbc123456** [comment]
It's hard for me.can you solve it ,then  released  to github.

I'll try to do what you say,thank you .

**Comment by jquense** [comment]
I would put together a reproduction of the bug and try a better support avenue like https://stackoverflow.com/ :) It'll much easier to get some help there, vs the bug tracker here :)
