### ISSUE TITLE
componentWillReceiveProps called twice between renders

### ISSUE THREAD

**Issue by JakeLokkesmoe** [facebook/react#10482]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
componentWillReceiveProps is being called twice in a row without a render (or a call to shouldComponentUpdate) between them.

More importantly, `this.props` has the same value in both calls, but the object passed as `nextProps` is different.

Specifically, I have code like this:
```javascript
componentWillReceiveProps(nextProps) {
  if (
    nextProps.organization.id != null &&
    this.props.organization.id !== nextProps.organization.id
  ) {
    // Dispatch a redux action that performs an xhr request using nextProps.organization.id
    // to load some_resource
  }
}
```

I noticed that my redux action (and the xhr request) was being performed twice. In both calls, `this.props.organization.id` was `undefined`. But also in both calls, `nextProps.organization.id` was defined.

In the second call, I was also being passed the results of the first xhr call, which was stored in my redux store and passed down into this component via react-redux/connect

I also confirmed that `shouldComponentUpdate`, `componentWillUpdate`, and `render` were all only called after the second time through.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.6.1
Google Chrome 60.0.3112.90
Windows 10

**Comment by gaearon** [comment]
Please provide a minimal example reproducing the issue.

**Comment by JakeLokkesmoe** [comment]
I'm working on that, just wanted to make sure there wasn't something obvious I was missing.

**Comment by JakeLokkesmoe** [comment]
I'm going to go ahead and close this for now, since I was pulled away to a different project and was unable to come up with a minimal example.
