### ISSUE TITLE
NPM Packages - could able to use it in react-native Project

### ISSUE THREAD

**Issue by RamkumarBPE** [facebook/react#10496]
I am new to react-native project, I have created a new react native project 'react-native init sample', after that I tried adding NPM package 'npm install --save is-reachable', after installation i tried to run react native project 'react-native run-ios'. I got error like Unable to resolve module 'os'. I have followed those 3 steps mentioned on it. but still I ma facing the same issue
![image](https://user-images.githubusercontent.com/8065281/29492071-96c478c6-858d-11e7-9243-a4489b39f057.png)

React-native version: 0.47.1
cli: 2.01.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
This is an issue tracker for React itself, not React Native. Please ask this question in React Native repository instead.

That said from the error message it seems like the module you're trying to use depends on Node APIs that don't exist in React Native. So you probably need to use RN-specific APIs for this.
