### ISSUE TITLE
Confuse on ReactDOMServer doc

### ISSUE THREAD

**Issue by lewis617** [facebook/react#10508]
---
If you load React from a `<script>` tag, these top-level APIs are available on the `ReactDOMServer` global. 
---

What does this mean? Why can we use `<script>` tag in node server.

**Comment by gaearon** [comment]
In Node you would usually `require('react-dom/server')`. However technically nothing prevents you from using it for some reason in the browser on the client. This is what the note refers to. You probably don't need it though.

**Comment by lewis617** [comment]
@gaearon Thank you very much. It helps me a lot.
