### ISSUE TITLE
[Patent] Issue has been raised on the patent of React

### ISSUE THREAD

**Issue by IamManchanda** [facebook/react#10500]
Hey guys, 
**First of all... thank you for such a great framework... Just started learning react and it's mindblowing comparing to frameworks like maybe Angular**

But, 
This is been raised yesterday => https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2

> “BSD + patents” essentially means that the code is open (for everyone to see and use), but it’s always copyrighted by Facebook. And they grant you a patent license as long as you’re nice to them by never suing Facebook for patent infringement.
> The instant you sue Facebook, your patent rights for React — and any other Facebook ‘open source’ technology you happen to use) — are automatically revoked.

As far I can understand... 
For example
- I started a startup, maybe the next facebook (if that makes sense)
- I used React for the coding part for frontend development
- My startup got popular and it became the next competitor to facebook
- Somehow, got a problem with Facebook, Inc which doesnt have anything to do with react or open source for that matter and I sue facebook due to some reasons (which even dont have to do anything with the codes). 
- My License for React is **REVOKED** and I can't use React... and I am in trouble!

and here is one more example (this time from the post)

> **Why should avoid React if you’re a startup**
> If you’re building a startup, I’m assuming you — and your investors — are hoping to land a million-dollar worth exit at some point, right?
> You want to keep your door open to all acquirers, especially the large ones: Apple, Microsoft, Google, Amazon, etc.
> These companies likely hold patent arsenals against Facebook — and even if they didn’t — they don’t want to surrender their rights to sue Facebook if the time came.
> If your product is built on React, acquiring you means losing these rights, and this is something they are probably not prepared to do.

**Comment by IamManchanda** [comment]
Just want to know your guys take on this... I just gave an example and I personally think that this is not right. After all { Open Source is about creating communities to build better software together. }

**This is not against facebook dignity but is this license good or risky for open source ??**

**Comment by IamManchanda** [comment]
cc @zpao sir ?? Please would be great if you can reply!

**Comment by gaearon** [comment]
>Somehow, got a problem with Facebook, Inc which doesnt have anything to do with react or open source for that matter and I sue facebook due to some reasons (which even dont have to do anything with the codes).

The additional patent grant is only revoked if you **sue Facebook for patent infringement**, not for something else. This is explicitly said in the clause. It's also called out in the FAQ:

http://code.facebook.com/license-faq

Unless you filed US patents (did you?) or bought them, and then decided to sue Facebook for violation of these patents (which would alone cost a lot of money in preparing the lawsuits), there is no way this clause affects you.

The clause has nothing to do with whether you "compete" with Facebook or not. In fact Twitter, arguably a Facebook competitor, is happily using React.

I can't offer you legal advice but I hope this helps.

**Comment by IamManchanda** [comment]
Hey dang There is nothing like legal advice... I am not creating a startup (atleast not right now for sure) ... What I am asking you is simply this 

**"IS THIS OPEN SOURCE?"**
Is it good for open source @gaearon ??

PS: I am standing up for **open source rights** not startup/legal advice ??

**Comment by zpao** [comment]
> IS THIS OPEN SOURCE?

Yes

**Comment by IamManchanda** [comment]
Ohk @zpao sir ... if you say so ... I am satisfied... thankyou!

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Comment by IamManchanda** [comment]
Yes it did!
