### ISSUE TITLE
React Component is not rendering in IE 11 or below but rendering properly in Chrome and Mozilla

### ISSUE THREAD

**Issue by shobhitsharma12** [facebook/react#10501]
React Components is not rendering in IE 11 or below but rendering properly in Chrome and Mozilla. 
When i am using IE 11 then showing error "“Access is denied” on IE browser for browser.min.js in react.js".
![image](https://user-images.githubusercontent.com/27944599/29506592-22cb39a4-866a-11e7-9bc6-4714e03b73d6.png

**Comment by gaearon** [comment]
The highlighted line (which presumably causes the error) is not from React. Search your `node_modules` to find where it's coming from, and please file an issue in the corresponding project.

**Comment by shobhitsharma12** [comment]
@gaearon , Can you suggest me what i need to do if React component not rendering in IE but properly rendering in other browser.

**Comment by gaearon** [comment]
I believe I commented above. This doesn't seem related to React. Find where this code is coming from, and try to figure out why you have it in the bundle. Use a forum like StackOverflow with a minimal example and maybe somebody there can help you.
