### ISSUE TITLE
ctrl + Enter keypress only works in firefox

### ISSUE THREAD

**Issue by nstraub** [facebook/react#10515]
It doesn't work in chrome, IE 11, edge nor chrome on Ubuntu. these browsers report a charCode of 10 and the event dispatcher dismisses it 
I've made a pull request with an unobtrusive fix here: #10514

**Comment by greatbody** [comment]
have to say some thing anyway.

**Comment by nstraub** [comment]
@gaearon while investigating for my PR I found [this](https://bugs.chromium.org/p/chromium/issues/detail?id=79407).
Apparently, it doesn't fail on macs, only windows and linux (when not running firefox)

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/10514.
