### ISSUE TITLE
[Fiber] Calling ReactNative.findNodeHandle() in render() crashes in DEV

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10518]
Found this while working on https://github.com/facebook/react/pull/10517.
See https://github.com/facebook/react/pull/10517#issuecomment-324292856 for more details.

<img width="511" alt="screen shot 2017-08-23 at 1 20 31 pm" src="https://user-images.githubusercontent.com/810438/29615456-ecc4db9c-8805-11e7-8840-a569f7f5a216.png">

<img width="432" alt="screen shot 2017-08-23 at 1 20 56 pm" src="https://user-images.githubusercontent.com/810438/29615460-efc8fbde-8805-11e7-9ee1-e36f4f91f903.png">

Now **I know this has been fixed in https://github.com/facebook/react/pull/10448 but that’s not the whole story**.

Even if we fixed the Stack-assuming `getName()` call, we still can't put arbitrary fields on a fiber:

<img width="432" alt="screen shot 2017-08-23 at 1 21 55 pm" src="https://user-images.githubusercontent.com/810438/29615516-188be568-8806-11e7-9040-bba11330784a.png">

For the reference, [this](https://github.com/facebook/react/blob/6ab2869a20e5e9a6f1f0ac02da34692dac9c1c9d/src/renderers/dom/shared/findDOMNode.js#L37-L40) is how we work around the problem in ReactDOM.

**Comment by bvaughn** [comment]
I'm on it.
