### ISSUE TITLE
Reliable way to measure painted dom elements.

### ISSUE THREAD

**Issue by lucasowens** [facebook/react#10513]
I apologize as I know this is a frequent question but I am struggling to find the proper way to accomplish what I am trying to do. 

I am creating a menu that has a simple animated underline that transition to the selected element in a list. This requires knowing the width of each element and positioning the underline div below the selected element on click.

I am currently getting the width in componentDidMount by way of refs and findDOMNode. This works, but on initial load i get a slightly incorrect measurement. When refreshing it is correct, every time i open the page in a new tab I see the incorrect behavior. 

Here is my componentDidMount code:

    componentDidMount() {
                this.tabWidths = this.tabs.map((t) => {
                    return ReactDOM.findDOMNode(this.refs[t.ref]).clientWidth;
                });

                this.setState({
                    distanceFromOrigin: this.tabWidths.map((e, i, a) => {
                        if (i === 0) { return 0; }

                        return this.tabWidths.reduce((sum, value, index, array) => {
                            if (index < i) { return sum + value; }

                            return sum + 0;
                        });
                    })
                });

                this.setState({ underlineStyle: this.styleGenerator(0) });
    }

Am I doing something fundamentally wrong here or is there no good way to know when the dom is fully painted to do measurements for things like this?

So far the only way I am able to get this to work is by nesting this within a requestAnimationFrame nested within a settimeout of 0. This just seems wrong.

thanks for any help!

**Comment by syranide** [comment]
> I am currently getting the width in componentDidMount by way of refs and findDOMNode. This works, but on initial load i get a slightly incorrect measurement. When refreshing it is correct, every time i open the page in a new tab I see the incorrect behavior.

It can be because of visual changes that can be delayed for various reasons; special fonts being loaded after rendering, images being loaded after rendering, styles being applied after rendering, etc. This is a common problem, AFAIK you cannot reliably listen for it and it usually shows itself as you mention; it fails on first render, but works on second (because everything is cached).
