### ISSUE TITLE
React expects a global document object and this breaks parallel dom testing

### ISSUE THREAD

**Issue by magestican** [facebook/react#10525]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

React expectes document to be a global variable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Run enzyme/jest tests in parallel using a parallel test runner such as ava.js together with jsdom or other node javascript dom implementations or headless browsers.

**What is the expected behavior?**

React should allow to pass a dom instance as constructor for initial .render initialization.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.6.1 - Windows x64

**Comment by jquense** [comment]
Hi there, Passing in browser globals would be really tough change to, make and would involve a substantial rewrite of huge swatches of the codebase to allow it. I can't speak for the core team, but my hunch is that they aren't going think its worth it.

Luckily however there should be other ways around your issue. Node has a VM module for creating new isolated JS contexts, My hunch would be that test runners should surface an option to allow each test to be run in a new context. There may be good reasons for it but I sort of thought Jest already did this. (cc: @cpojer )

**Comment by cpojer** [comment]
Yeah, unfortunately that's not possible. However, you could create on test file per test.
