### ISSUE TITLE
Descriptive error on null PropType

### ISSUE THREAD

**Issue by stavlocker** [facebook/react#10538]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
If I specify an invalid proptype (Common mistakes are misspelling and `boolean` instead of `bool`), I get this error:
```
Failed prop type: ComponentName: prop type `propName` is invalid; it must be a function, usually from React.PropTypes.
```
I'm [not](https://stackoverflow.com/questions/36127842/it-must-be-a-function-usually-from-react-proptypes) [the only one](https://github.com/matthewwithanm/react-controllables/issues/5) [bothered by this](https://github.com/erikras/redux-form/issues/1487).

**What is the expected behavior?**
A useful error message could be `Failed prop type: {ComponentName}: prop type '{propName}' '{invalidPropType}'. Available types: {link}`

**Comment by jquense** [comment]
Care to submit a PR? I think a DEV only usage of a Proxy might work? There may be ecosystems concerns with that approach,(folks do some weird things) but we can give it a shot if you want to send it over!

**Comment by aweary** [comment]
Could you direct this request to the [`prop-types` repo](https://github.com/facebook/prop-types)? This warning is no longer a part of the core React library. Thanks!
