### ISSUE TITLE
with redux  

### ISSUE THREAD

**Issue by lbc123456** [facebook/react#10534]
×
Objects are not valid as a React child (found: object with keys {counter}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.

Check the render method of `Counter`.

**Comment by jquense** [comment]
Hey, @lbc123456! We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms listed on our [Where to Get Support](https://facebook.github.io/react/community/support.html) doc page.
