### ISSUE TITLE
Avoiding findDOMNode

### ISSUE THREAD

**Issue by jamiewinder** [facebook/react#10532]
I've read a few comments on here about `findDOMNode` potentially being dropped, or at least its usage strongly discouraged. I'm curious as to what the alternative should be, as all the ones I've seen are nowhere near as flexible.

Let's say I have a funky wrapper component that adds a context menu to a component:

```jsx
class ContextMenu extends React.Component {
    render() {
        const { children, menu } = this.props;
        const child = React.Children.only(children);
        const childWithEvents = React.cloneElement(child, {
            onContextMenu: () => someApiToOpenMenu(menu);
        });
        return childWithEvents;
    }
}

<ContextMenu menu={myMenu}>
    <div>Right click for menu!</div>
</ContextMenu>
```

So far, so good, and no `findDOMNode`. Except it needs the child to be a DOM element, or for it to have a `onContextMenu` prop which will assign the handler to the inner DOM element. This won't work:

```jsx
const MyLabel = ({ children }) => <span>{children}</span>;

<ContextMenu menu={myMenu}>
    <MyLabel>Right click for menu</MyLabel>
</ContextMenu>
```
(Unless I intentionally forward event props from MyLabel to the span, but I must ensure all props using this do the same).

Alternatively I can wrap the children:
```javascript
class ContextMenu extends React.Component {
    render() {
        const { children, menu } = this.props;
        return (
            <div ref={(element) => (element && element.addEventListener('contextmenu', () => someApiToOpenMenu(menu)))>
                {children}
            </div>
        );
    }
}
```
But now I'm adding element unnecessarily - if I use this with an inline element, then now it's wrapped in a block element.

On the other hand, this:

```jsx
class ContextMenu extends React.Component {
    render() {
        const { children, menu } = this.props;
        const child = React.Children.only(children);
        const childWithEvents = React.cloneElement(child, {
            ref: (instance) => {
                const element = ReactDOM.findDOMNode(instance);
                if (element) {
                    element.addEventListener('contextmenu', () => someApiToOpenMenu(menu));
                }
            }
        });
        return childWithEvents;
    }
}
```
Will work for anything that *eventually* renders a DOM element, no matter how deep it is, whether the components forward props or not. I don't see any downsides apart from the 'impurity' of poking around in the DOM?

So I can see there are workarounds for not using `findDOMNode`, but none as good as actually just using it?

**Comment by jquense** [comment]
I can't speak for the team, but I think there are plently of cases where `findDOMNode` is an "OK Choice", You example is a case where I think its a better choice than a function ref, especially if you don't control all the components you need to add a ref too. Maybe @gaearon can speak a bit more to potential deprecation, but from the initial issue there it seems like they worked around the reasons for wanting to remove it (unless its gone in v16 and I've missed something huge :P)

**Comment by jamiewinder** [comment]
Thanks for the comment, though I'm not sure why this was closed as I was hoping to hear from the team after you prompted them to chip in. There have been a few throwaway 'let's deprecate findDOMNode' comments from what I think were team members, and I don't know if that's [still] the general feeling and if so how we ought to use it without wrapping elements, etc.
