### ISSUE TITLE
Add topics to categorize React repository and make it more discoverable

### ISSUE THREAD

**Issue by cht8687** [facebook/react#10537]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

There has no topics for this repo.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

Other popular frameworks `Angular`, `Vue`'s Github page have topics. 
Though `React` is a really popular project, but wouldn't it better to add topics such as `react` `javascript` `frontend` to make it more discoverable? 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
Thanks for the suggestion @cht8687, I don't see any problem with this. cc @gaearon who can probably add them, or knows who can 😃

**Comment by gaearon** [comment]
cc @zpao Can we do this?

**Comment by zpao** [comment]
Added those three, can add some more. On the list of things to make easier outside of GH…

**Comment by gaearon** [comment]
Sweet.
