### ISSUE TITLE
React.js with asp.net core 2.0

### ISSUE THREAD

**Issue by patsadow2** [facebook/react#10541]
Hello, could anyone link a good template to start hacking with react + asp.net 2.0. I am interested in jsx no tsx ;))) Thanks ;)

**Comment by jquense** [comment]
Hey there @patsadow2 welcome! We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms listed on our [Where to Get Support](https://facebook.github.io/react/community/support.html) doc page.
