### ISSUE TITLE
[question] using only nextState in shouldComponentUpdate 

### ISSUE THREAD

**Issue by bhutaninitin** [facebook/react#10551]
Consider the following:
shouldComponentUpdate(nextProps, nextState) {
    return this.state.value != nextState.value;
  }

Here, nextProps is wasted (not used). Is there a way to use shouldComponentUpdate so that only nextState comes as the only argument for shouldComponentUpdate?

**Comment by jquense** [comment]
There isn't but I wouldn't worry about it, there isn't any cost to not using the props there. Javascript engines are smart enough to not waste resources there and react wouldn't save any work if it didn't have to pass it to the function
