### ISSUE TITLE
import external lib ERROR

### ISSUE THREAD

**Issue by MarcusMann** [facebook/react#10555]
How do I import a third-party Javascript library into reactjs? I've searched a lot of the internet and I do not think so.

I downloaded a free theme however the author makes custom settings in a .js file and would like to include this file if some component effects do not work.

Thank you!

**What is the current behavior?**

```

if ("undefined" == typeof jQuery) throw new Error("Bootstrap's JavaScript requires jQuery"); + function(a) {
                                  ^
Error: Bootstrap's JavaScript requires jQuery

```
**What is the expected behavior?**

**Comment by jquense** [comment]
Hey, @MarcusMann! You definately can import and use external javascript with React. From what I can see your error isn't related to React or using other libraries with it. IT seems like you are trying to use twitter bootstrap without including jquery, which it requires. We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms listed on our [Where to Get Support](https://facebook.github.io/react/community/support.html) doc page. You might also want to try the bootstrap support options.
