### ISSUE TITLE
Is this bug ?

### ISSUE THREAD

**Issue by samvel451811** [facebook/react#10557]
hi.

I use the react-router-dom ( npm-yarn package ).
In different routes i use some react component to show,
but then the route is changing my component isn't re-render.

**Is it bug?**

**Comment by jquense** [comment]
Hi there! It looks like your issue is with react-router, and not with React, and probably not a bug.  Unfortunately we can give support for all packages that use react, I would try the RR repository and various other support avenues such as stackoverflow.com or discord.
