### ISSUE TITLE
Wrong warning?

### ISSUE THREAD

**Issue by mochetts** [facebook/react#10577]
**Do you want to request a *feature* or report a *bug*?**
_bug_

**What is the current behavior?**
It shows a warning after following the React documentation. Using `arrayOf` and ES2015 classes to validate items of an array shows a warning.

```javascript
// Specifies type values for props:
RectShape.propTypes = {
  points: PropTypes.arrayOf(Point), // warning here
}
```

**If the current behavior is a bug, please provide the steps to reproduce**
Looking at this [JSFiddle](https://jsfiddle.net/1y9hd6nn/1/) this warning is shown:

![image](https://user-images.githubusercontent.com/3678598/29889403-6cc5b660-8d9a-11e7-9b39-faf1601d9b0f.png)

**What is the expected behavior?**
No warning should be shown as this code follows the [react documentation about PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Chrome Version 60.0.3112.101 (Official Build) (64-bit) (MacOS Sierra)

**Comment by jquense** [comment]
I'm not seeing a warning in the prop-types I think you may be seeing a warning from some other place. https://jsfiddle.net/84v837e9/202/

**Comment by mochetts** [comment]
I updated the comment. The issue happens with `arrayOf` propType definition. Here's the fiddle: https://jsfiddle.net/1y9hd6nn/1/

**Comment by jquense** [comment]
I see, so `arrayOf` expects a prop-type function not a class, you want: `PropTypes.arrayOf(PropTypes.instanceOf(Point))` instead

**Comment by mochetts** [comment]
Thanks @jquense !

**Comment by mochetts** [comment]
A small suggestion, an update in the documentation might be handy given this is a pretty common use case when using `propTypes`. Thanks again.
