### ISSUE TITLE
TypeError: SyntheticEvent.call is not a function in development mode with Webkit browser

### ISSUE THREAD

**Issue by imsurinder90** [facebook/react#10582]
**Do you want to request a *feature* or report a *bug*?**
It is a bug

**What is the current behavior?**
I am using Webpack to built React based app - [pgAdmin4](https://github.com/postgres/pgadmin4)

The app runs in two modes:
1. Desktop (aka runtime) mode - It opens in Webkit browser.
2. Server mode - It opens in any of the browsers such as Chrome, Firefox etc.

I am getting the error when the app is built(using webpack) with development flag enabled. 

It works fine in production mode.
```
scritps: {
    "webpacker": "yarn run webpack -- --config webpack.config.js",
    "bundle:prod":  "cross-env NODE_ENV=production yarn run webpacker"
    "bundle:dev": "yarn run webpacker",
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

Since the app is run on Webkit browser, It is not possible to provide a test environment. However, If anyone wants, he can build using the steps provided in [README](https://github.com/postgres/pgadmin4) or this blog [post](https://imsurinder90.github.io/posts/install_qt5.8_with_webkit_on_macosx)

**What is the expected behavior?**
The React base app should run without any error in dev mode.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v15.4.2
OS - Mac OS X Yosemite(10.10.2)
Browser - annulen QtWebkit-58 Browser 
Qt version - Qt5.8.0

Please let me know if you need more details.

**Comment by patrik7** [comment]
+1

**Comment by aweary** [comment]
Hey @imsurinder90, thanks for the report. Could you please test this with the latest version of React 15 (15.6.1), and if that fails, the React 16 RC?

Assuming that fails, Is there any way you could provide a reduced repro for us to investigate? Downloading and building a full application is a bit too time-consuming for triage.

We've seen issues from these Webkit-forked browsers before. It may be an issue with their JS implementation since React works fine in all major Webkit browsers.

**Comment by imsurinder90** [comment]
Hi @aweary 
You are correct. We also had issues with Webkit-forked browser before and most of them were resolved by this PR[10011](https://github.com/facebook/react/pull/10011)

But this issue is neither resolved in React 15 nor in React 16(but previous issues are resolved).

This issue was that QtWekbit doesn't deal well with Proxy objects. To resolve the issue,
`SyntheticEvent.augmentClass` definition was moved above Proxy's SyntheticEvent generation code.
But it was a temporary solution to the problem.

Now again, Since SyntheticEvent is a proxy type of event which fails when called like `SyntheticEvent.call(...)` and it gives an error:

> SyntheticEvent.call is not a function

However, I was able to fix it by moving following statements before `Proxy SyntheticEvent` code:

```
addEventPoolingTo(SyntheticEvent);
var SyntheticEvent_1 = SyntheticEvent;
```
But that's not a solution.

The other way around is make the `Proxy SyntheticEvent` code conditional. When the browser is of type `QtWebkit`, don't enter into the code block, simply skip that code.

**For example:**

```
var isWebkitBrowser = typeof window.webkitConvertPointFromNodeToPage === 'function';
if (isProxySupported && !isWebkitBrowser) {
  SyntheticEvent = new Proxy(SyntheticEvent, {...});
}
```
Referece [link](https://stackoverflow.com/questions/18625321/detect-webkit-browser-in-javascript#answer-21756811)

This issue is only reproducible in QtWebkit-browser which runs on the desktop, so I can't even share IP-based URL. Sorry, I don't find any other way to provide reduced repro.

Please let me know If you need more information.

Also, where can I find the release information for React v16 since it resolves most of WebKit-browser issues(I confirmed at my end)?

**Comment by aweary** [comment]
@imsurinder90 I don't think we would want to include an explicit check for QtWebkit. If you can provide a non-intrusive change like https://github.com/facebook/react/pull/10011 that resolves this, we'll be happy to consider it.

I'm going to close this out since this isn't a supported environment. Feel free to ping me if you do find a non-intrusive solution for your use-case.

Thanks!

**Comment by dalepo** [comment]
Hello @imsurinder90 

I'm having this issue while trying to scrape a page (using splash) in a forced click event.
Do you know if there is a way to bypass this without modifying the code you mentioned?
