### ISSUE TITLE
PropTypes & createClass warnings echo when using `import * as React`

### ISSUE THREAD

**Issue by STRML** [facebook/react#10583]
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

This simple script:

```js
import * as React from 'react';
```

throws the following warnings:

```
$ ./node_modules/.bin/babel-node foo.js                                                                                                                                                                   15:00:58
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

**What is the expected behavior?**

I expect these deprecation warnings not to throw. The `import * as React` syntax is now [recommended in FlowType](https://flow.org/en/docs/react/components/) and this is causing issues for end users in several libraries I author. See e.g. [this issue](https://github.com/mzabriskie/react-draggable/issues/276).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This is in React 15.6.1.

**Comment by gaearon** [comment]
It’s unfortunate. React 16 is really close and it doesn’t have this issue.

We could make [the getters](https://github.com/facebook/react/blob/e6f537565390a9eb8996fd3751c48b96f9a15017/src/isomorphic/React.js#L109-L138) non-enumerable I think. Not sure if that would be confusing / a breaking change?

**Comment by STRML** [comment]
That should fix the issue; I doubt anyone is enumerating over `React` for any reason other than this one, but I think that would be a breaking change.

Ideally the warning would only fire if you actually *use* either of these features; so some interception on PropType fns and `createClass` would be more exact.

**Comment by gaearon** [comment]
I’m not sure the effort to fix it (and potentially introduce other issues) is worth it given that 16 is imminent.

**Comment by Kovensky** [comment]
Why would Flow encourage a syntax that is known to be invalid and that will be broken with real modules? :thinking_face:

But this is perhaps a discussion for another forum.

**Comment by gaearon** [comment]
I think we'll just leave this unfixed as we already released 16.
