### ISSUE TITLE
Request for the Two-way Binding Helpers article to be improved

### ISSUE THREAD

**Issue by JamesDonnelly** [facebook/react#10602]
**Do you want to request a *feature* or report a *bug*?**
Documentation update.

**What is the current behavior?**
It describes a deprecated feature.

**What is the expected behavior?**
It should ideally provide the reader with documentation of a non-deprecated feature or at least provide an explanation of why the feature it heavily discusses was deprecated. The article itself does provide a good deal of informative information as to why two-way bindings are useful and how React itself works, but it focuses heavily on the now-deprecated `LinkedStateMixin ` feature. 

I'm requesting this here because this page is the top result on Google (UK) when searching for "react two-way binding" (without quotes).

**Comment by jquense** [comment]
Please feel free to submit a PR! :)

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

Please open a new issue in that repository. Sorry for the inconvenience!
