### ISSUE TITLE
Support of the importScripts in Web Worker

### ISSUE THREAD

**Issue by andreoman** [facebook/react#10604]
Hello,
Could you explain why the importScripts is not supported in the Web Worker.
I have added `importScripts('./buid/ffmpeg-all-codecs.js');` 
How can I replace the importScripts ?

Thank you

**Comment by jquense** [comment]
Hi there, I'm not sure what your code means but it doesn't seem to be related to React. You might want to try the various support channels like stackoverflow.com

**Comment by aweary** [comment]
It sounds like you're asking about `create-react-app` @andreoman, this repo is for bugs and feature requests for the React library itself. As @jquense  mentioned, I recommend referring to [one of the many support resources out there](https://facebook.github.io/react/community/support.html).
