### ISSUE TITLE
Proptypes validation

### ISSUE THREAD

**Issue by rajur7** [facebook/react#10603]
**Do you want to request a *feature* or report a *bug*?**
*feature*
**What is the current behavior?**
*Proptypes* are checking type of the parameters whatever the component receiving from parent component
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

**What is the expected behavior?**
*Proptypes* should also check the values not only type of data it is receiving in validation. This feature can be useful for more specification to the values also, if we want to restrict the component to get the particular values
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by jquense** [comment]
Hi there thanks for the issue, propTypes have been split off into its own package. Please submit feature requests there: https://github.com/facebook/prop-types

Thanks!

**Comment by rajur7** [comment]
thankyou @jquense, I will submit in the provided link
