### ISSUE TITLE
Why HTMLDivElement doesn't has placeholder and type?

### ISSUE THREAD

**Issue by threescales** [facebook/react#10609]
I edit content by div with contentEditable.But in @type/react@15.6.1. placeholder can‘t support by tsx. So，what should I do？

**Comment by acdlite** [comment]
`placeholder` and `type` are both supported by React DOM.

Are you asking about TypeScript support? Those types aren't owned by us. Please try opening an issue in the DefinitelyTyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped

If I've misunderstood your question, please respond with more details and/or a reproducible test case.

**Comment by threescales** [comment]
@acdlite  thx.
