### ISSUE TITLE
[Docs] Better documentation of PureComponent

### ISSUE THREAD

**Issue by pksjce** [facebook/react#10600]
**Do you want to request a *feature* or report a *bug*?**
Doc update

**What is the current behavior?**
Currently we have this little section on `PureComponent` at [https://facebook.github.io/react/docs/react-api.html#react.purecomponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

It lacks some in-depth information about using `PureComponent`. I had to refer to blogposts to get a sense of the implications of using `PureComponent`s.
https://60devs.com/pure-component-in-react.html
https://hackernoon.com/react-purecomponent-considered-harmful-8155b5c1d4bc

**What is the expected behavior?**

It would really be better to have reference documentation for `PureComponent` like https://facebook.github.io/react/docs/react-component.html

It should have the following

- An example of `PureComponent` usage which specifically points out the functionality.
- Is it possible for a `PureComponent` to override the `shouldComponentUpdate`?
- A clearer explanation of how change in reference results in a re-render.
- A note on how inline functions for event handlers might re-render pure components.

Nice to have info on 

- The history of `PureComponent` wrt the problem with `pure-render-mixin`
- A note on how it prevents children depending on `context` info to re-render.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`PureComponent` is a part of React v15

I'm happy to work on a PR for this change if y'all think this issue is valid.

**Comment by acdlite** [comment]
Yes, please open a PR with your suggested changes!

**Comment by tjcchen** [comment]
Hello @acdlite, is this problem resolved? I also found the documentation for PureComponent not sufficient.
