### ISSUE TITLE
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Login`. at invariant (index.js:964) at instantiateReactComponent (index.js:14515) at instantiateChild (index.js:31155) at index.js:31182 at traverseAllChildrenImpl (index.js:14808) at traverseAllChildren (index.js:14903) at Object.instantiateChildren (index.js:31181) at ReactDOMComponent._reconcilerInstantiateChildren (index.js:30844) at ReactDOMComponent.mountChildren (index.js:30883) at ReactDOMComponent._createInitialChildren (index.js:29051)

### ISSUE THREAD

**Issue by dvrsdheeraj** [facebook/react#10601]
login.js

import React from "react";

import {Link} from "react-router";
export default class Login extends React.Component{

    render() {
        return (
            <div className="container-fluid">
    <br/><div className="row">
        <div className="col-md-4"></div>
        <div className="col-md-4 panel panel-default">
            <h1 className="text-center">Login</h1><hr/>
            <div className="alert alert-warning">
              <strong>sucess</strong>
            </div>
            <div className="alert alert-success">
              <strong>success</strong>
            </div>
            <form method="post" action="/login">
              <div className="form-group">
                <label for="email">Email address</label>
                <input name="email" type="email" className="validate form-control" required="" aria-required="true" id="email" placeholder="Email"/>
              </div>
              <div className="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" className="validate form-control" required="" aria-required="true" id="password" placeholder="Password"/>
              </div>
              <div className="form-group">
                  <Link to="/register">Register</Link>
              </div>
              <button type="submit" className="btn btn-primary text-center">Submit</button>

            </form><br/>
        </div>
    </div>
</div>
            );
    }
}

main.js

import React from "react";
import ReactDOM from "react-dom";
import {BrowserRouter  as Router,Route,IndexRoute} from "react-router-dom";

import Login from "./Components/Login.js";
import Registration from "./Components/Registration.js";

ReactDOM.render(<Router>
    <Route path="/" component={Login}>
    <Route path="register" component={Registration}/>
    </Route>
    </Router>,
     document.getElementById('app'));

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react:4.0.0

**Comment by euvl** [comment]
You might want to make a shorter title.

**Comment by jquense** [comment]
Hi there! The error message is probably correct. Make sure the  Link component is imported and defined correctly in your login component. I'd also try one of the many support avenues such as stackoverflow.com for more specific help and attention, we try to keep the react issue tracker but and feature request focused thanks!
