### ISSUE TITLE
Remove cache-invalidating code/hack

### ISSUE THREAD

**Issue by nixolas1** [facebook/react#10615]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the output code after building there is a hack in the code which includes the time of compilation, which causes the whole file to be modified, which when code-splitting is bad for caching.

Relevant output code (see LAST_BUILD):
```
if (typeof process !== 'undefined' && Object({"NODE_ENV":"development","LAST_BUILD":"2017-09-06T07:53:58.689Z"}) && "development" === 'test') {
  // Temporary hack.
  // Inline requires don't work well with Jest:
  // https://github.com/facebook/react/issues/7240
  // Remove the inline requires when we don't need them anymore:
  // https://github.com/facebook/react/pull/7178
  ReactComponentTreeHook = __webpack_require__("./node_modules/react/lib/ReactComponentTreeHook.js");
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
Build project with react and react-dom in development or production, check diff between two supposedly identical builds.

**What is the expected behavior?**
The two builds outputs should be identical if no modifications have been made.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.6.1

**Comment by nhunzaker** [comment]
I'm not too familiar with the backstory, but I'm curious if we can eliminate this now that https://github.com/facebook/react/pull/7178 has merged.

**Comment by nixolas1** [comment]
I found that LAST_BUILD was actually a variable we passed into process.env when building it through webpack. Removing it solved my cacheing issue at least, but I think removing the hack would mitigate such future bugs.

**Comment by nixolas1** [comment]
Yes, we were using a DefinePlugin with process.env things inside.
I can confirm the code was still present in the production build, after uglifying.

**Comment by gaearon** [comment]
Thanks for reporting!

This is fixed in master (basically that file won't be shipped at all in React 16). You can already try [React 16 beta](https://github.com/facebook/react/issues/10294) if you'd like.

I don't think we will be making further changes to this in 15.
