### ISSUE TITLE
Add ES6 module build to NPM package

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#10613]
Followup from a tweet from Unpkg (unpkg?) about ES6 module support:
https://twitter.com/unpkg/status/905239560988221440

> For fun, try using `import * as d3 from '//unpkg.com/d3?module` inside a <script type=module> and watch those modules load! 

It would be neat if you could just `import { Component }  from 'https://unpkg.com/react?module'` in browsers like Safari (and soon Chrome). As far as I understand the problem, we'd just need to export an ES6 build target from Rollup. 

I use "just" lightly. Hopefully it's that simple; it's probably more complicated. In any case, now we have an issue for it!

**Comment by aweary** [comment]
I believe this is a duplicate of https://github.com/facebook/react/issues/10021 :)

**Comment by nhunzaker** [comment]
Ah man. Look at me... Thanks!
