### ISSUE TITLE
ambiguous documentation for PureComponent and Component

### ISSUE THREAD

**Issue by vferko** [facebook/react#10610]
**Do you want to request a *feature* or report a *bug*?**
Bug (ambiguous documentation) as well as feature (documentation update request)

**What is the current behavior?**
Currently the documentation for [PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent) says:

> React.PureComponent is exactly like React.Component but implements shouldComponentUpdate() with a shallow prop and state comparison.

Then the Note states:

> Furthermore, React.PureComponent's shouldComponentUpdate() skips prop updates for the whole component subtree. Make sure all the children components are also "pure".

- The question is _In what circumstances does it skip the prop updates for the whole component subtree?_
- Does it also implicitly say that if I implement `shouldComponentUpdate` in a `Component`, the behaviour will be different? For example if it returns `false`, the props propagation won't be stopped?
- A word on _Why make sure all children componetns are also "pure"_ would be handy.

Then the documentation for [Component's shouldComponentUpdate](https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate) says:

> The default behavior is to re-render on every state change...
- _and props?_

> Returning false does not prevent child components from re-rendering when their state changes.
- But prevents prop propagation, that effectively stops the re-render cycle of all child components?
- This sentence sounds like the two events may be related, but are implemented in a way to not prevent the re-render. Rewording to something like "If a component's state is changed (or `setState()` is called), its re-render cycle will be initiated regardless of some parrental's SCU returning false in some point in past."

**Do I understand correctly...?**
- Component can re-render when it receives new props from parent component.
- Component can also re-render if its state gets changed.
  - Component can change its state when it receives new props or by calling `setState()` from outside or by the component itself.

**What is the expected behavior?**
Expected is to find more explicit documentation. Currently some sentences look like they only apply for `PureComponent` or `Component` or both.

Expected is to find an explicit mention that the behaviour of `Component` and `PureComponent` is exactly the same if their `SCU` happen to return `false`.

Other articles about react components found on the web then reformulate these official rules in a way that further extends the ambiguity.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

v15.6.1
https://facebook.github.io/react/docs/react-api.html#react.purecomponent
https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate

**Comment by acdlite** [comment]
> In what circumstances does it skip the prop updates for the whole component subtree

When the next props and state are shallowly equal to the current props and state. It's treated the same as if `shouldComponentUpdate` returned `false`.

> Does it also implicitly say that if I implement shouldComponentUpdate in a Component, the behaviour will be different? For example if it returns false, the props propagation won't be stopped. [...] A word on Why make sure all children componetns are also "pure" would be handy.

As implemented today, the behavior is exactly the same, though this may change with future optimizations. For example, if you call `setState` on a child of a PureComponent, and the new state is shallowly equal to the old state, today that child is re-rendered (unless it itself is a PureComponent or has `shouldComponentUpdate`). But if we can infer that the child is also pure, a future version of React may skip re-rendering. We're being intentionally vague because we don't know exactly what a future implementation might do, and users should avoid making specific assumptions.

If you feel the existing documentation could be improved, please submit a PR with your suggested fixes. Thanks!

**Comment by vferko** [comment]
Thank you for confirming my findings. I will update the documentation slightly.
