### ISSUE TITLE
What is the browser version requirements for react16 ?

### ISSUE THREAD

**Issue by vicbell** [facebook/react#10618]
React is not list the supported browser version, so i where could i find the browser version requirements for react16 ?

**Comment by jquense** [comment]
The browser requirements a haven't changed for v16, it does require a few more polyfills though. but in general React supports es5 compliant browsers back to IE9

**Comment by vicbell** [comment]
What about IE8 ?

**Comment by vicbell** [comment]
I could not find the past browser requirements doc, could you give me a link here? :)

**Comment by jquense** [comment]
React dropped IE8 support at the beginning of last year in version 15: https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html 

It suggests that it may still work in newer versions (and it may) but that gets more and more unlikely as each new version is released, and older code is cleaned up.

**Comment by jquense** [comment]
and the docs link, it is a bit hidden yes: https://facebook.github.io/react/docs/react-dom.html#browser-support

**Comment by vicbell** [comment]
Tks very much !  :)

**Comment by aweary** [comment]
We do hope to define a more definitive list of supported browsers at some point, see https://github.com/facebook/react/issues/9301

**Comment by siorra** [comment]
Hi guys, I see If you use ssr than you not need use react, you can turn off bundle.js and work as simple page with routes! it's very cool if you haven't state..
