### ISSUE TITLE
Update `react-art` to use new `prop-types` package

### ISSUE THREAD

**Issue by flarnie** [facebook/react#10625]
**Do you want to request a *feature* or report a *bug*?**
Will stop `react-art` from throwing warnings when used with recent React. I haven't tested this manually, but it seems like it will throw because it's using the old style of getting `PropTypes` from React directly.

https://github.com/reactjs/react-art/blob/master/src/Wedge.art.js#L28

Also the package is not listing `prop-types` as a dependency - 
https://github.com/reactjs/react-art/blob/master/package.json
and
https://github.com/facebook/react/blob/master/packages/react-art/package.json

**What is the current behavior?**
It probably throws a warning, or at least models out-of-date syntax which won't work once we deprecate `React.PropTypes`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

TODO

**What is the expected behavior?**

Uses `prop-types` package, as [shown in the docs.](https://facebook.github.io/react/docs/typechecking-with-proptypes.html) 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.0 beta/RC

**Comment by gaearon** [comment]
Isn't this only relevant for old code in `react-art` repo? My understanding is that code is not used anywhere. Currently React repo is the source of truth, and we shouldn't have that problem in it.

**Comment by gaearon** [comment]
(Longer term we should move source of truth back into `react-art` but we can't until we expose the reconciler. There is an issue about this.)

**Comment by sophiebits** [comment]
Fixed by #10629.
