### ISSUE TITLE
Pattern for Parent Initiated fetch of Child data?

### ISSUE THREAD

**Issue by Zarkoix** [facebook/react#10632]
For performance reasons I have a child element whose data is stored in its state and only its state (instead of being passed up the hierarchal chain using callbacks passed in props).

There then comes a time where an action in the parent element dictates that I now need that data, what is the correct pattern for fetching it in the child?

Do I use refs and call a child.fetchData() method via a saved reference?

Do I change a prop flag causing the child to call a prop callback with the data?

**Comment by gaearon** [comment]
Either one works. It's hard to say more without knowing about your use case. I guess that if only the parent knows whether the child needs the data, you can pass a boolean prop like `needsData`, and trigger (or abort) data fetching when it changes.
