### ISSUE TITLE
Interactive documentation for JSX

### ISSUE THREAD

**Issue by viebel** [facebook/react#10646]
The interactive version of the "JSX in depth" article got a nice traction today on [Hacker News](https://news.ycombinator.com/item?id=15197693).

The interactive snippets are powered by the [Klipse plugin](https://github.com/viebel/klipse) (I'm the author of the plugin). The evaluation is done on the *client side*: no server is involved at all!

Would you consider trying the Klipse plugin on the official react documentation?

**Comment by gaearon** [comment]
Yes, I think this is interesting and we're in a good place with the new website to start exploring something like this.

**Comment by viebel** [comment]
@gaearon I'd be happy to open a Pull Request with one or two articles from the documentation made interactive. Which article would be good to start with?

**Comment by bvaughn** [comment]
This is really cool 😄  and I'd love to talk more about it.

However the documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

So let's continue the discussion there! I'll create an issue to get it started: reactjs/reactjs.org/issues/26

**Comment by viebel** [comment]
Thanks @bvaughn. Let's start the discussion!

**Comment by bvaughn** [comment]
Okay 😄 Please feel free to continue it at reactjs/reactjs.org/issues/26
