### ISSUE TITLE
ReactChildFiber.coerceRef does not like undefined ref on a component

### ISSUE THREAD

**Issue by mgreer** [facebook/react#10649]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
coerceRef in ReactChildFiber accepts ref=null on a component, but not typeof ref === 'undefined', and so borks with "Expected ref to be a function or a string."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
Could be fixed by either coercing ref into being null if undefined, or also testing for undefined.

**What is the expected behavior?**
Treat typeof ref === 'undefined' as ref === null

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.0.0rc2

**Comment by sophiebits** [comment]
Curious: how are you ending up with an undefined ref? createElement should return null or a real ref.

**Comment by mgreer** [comment]
Seems to be when I have a function in render() which returns an array with a string and an element to render like so:
["Playing ",{type: "strong", key: 1, props: {…}, $$typeof: Symbol(react.element), _store: {…}}]

**Comment by sophiebits** [comment]
Can you say what code created that array? In most cases you would have `ref: null`.

**Comment by mgreer** [comment]
It is the result of a call to SimpleMarkdown (https://github.com/Khan/simple-markdown) to format an i18n string into React elements. Works fine in React 15, but now that mixed array is throwing ref=undefined error from ReactChildFiber.

**Comment by mgreer** [comment]
this is now fixed in SimpleMarkdown master

**Comment by jossmac** [comment]
I ran into a similar issue when updating some code to 16, hopefully this helps someone in the future:

```jsx
<MyComponent ref={falseyValue && this.getRefFn} />
```
`ReactChildFiber.coerceRef` won't interpret `false` the way it used to. Easy to work around but confusing at first.
