### ISSUE TITLE
picture srcset error

### ISSUE THREAD

**Issue by Baira** [facebook/react#10651]
Hi,

I have no idea how to fix this error triggered by the srcset picture attribute : 

`Failed parsing 'srcset' attribute value since it has an unknown descriptor.`
`Dropped srcset candidate "[object"`

Here is my component : 
```jsx 
import React from 'react';
import { Link } from 'react-router-dom';
import { observer, inject } from 'mobx-react';
import LpImgXlarge from '../../../assets/images/example.jpg';
import LpImgXlarge2x from '../../../assets/images/example@2x.jpg';

@inject('store')
@observer
class Slide1 extends React.Component {
  render() {
    return (
      <div id="react">
        <picture>
          <img
            srcSet={`${LpImgXlarge} 1x, ${LpImgXlarge2x} 2x`}
            alt="react"
          />
        </picture>
      </div>
    );
  }
}
```
```json
    "react": "15.6.1",
    "react-dom": "15.6.1",
    "react-router": "4.2.0",
    "react-router-config": "^1.0.0-beta.4",
    "react-router-dom": "^4.2.2",
```
Help!

**Comment by gaearon** [comment]
What do you see if you `console.log` the value you are passing to `srcSet`?

**Comment by Baira** [comment]
Hi @gaearon , thank you for answering!

Here is what I got after doing ```console.log(`${LpImgLarge} 1x, ${LpImgLarge2x} 2x`);``` : 

`//localhost:2002/build/images/example.jpg 1x, //localhost:2002/build/images/example@2x.jpg 2x`

**Comment by gaearon** [comment]
I can't really say without a project reproducing this.

**Comment by Baira** [comment]
I'm happy for having finally resolved this issue after many hours of debugging and googling :smiley: 

You may have already guessed that I'm importing images through webpack `file-loader`. This works very well with react client side as it points `LpImgXlarge` to the corresponding file path . My application being isomorphic, the code was also ran server side. Since node's `require` doesn't support images, I had to ignore them using : 
```jsx
require.extensions['.jpg'] = function() {
  return;
};
```
This was my application state before this error appears. After console.logging It appears that the  `require.extensions` code returns an empty object. So when I looked for the `srcset` attribute in the html page generated server side, it was `srcset="[object Object] 1x, [object Object] 2x"`. Apparently, this is what caused react to output the error above.

This made me realize that all image links in my html generated server side were just `[object Object]` which would cause many SEO probelms. So I made this change to the `require.extensions` : 

```jsx
require.extensions['.png'] = function(module, filename) {
  module.exports =
    config.http.assetBaseUrl +
    filename.substring(filename.lastIndexOf('/assets/images'));
};
```
`assetBaseUrl` is a variable that I added to my config file that both webpack and `require.extensions` use. The goal is that once in production I could just set `assetBaseUrl` to my cdn base url so that all assets are delivered throught it.
Do you think this is a good solution ?

**Comment by gaearon** [comment]
If it works in your case then maybe :-)
