### ISSUE TITLE
There are multiple modules with names that only differ in casing

### ISSUE THREAD

**Issue by ihtml5** [facebook/react#10667]
## version
React 16 rc

## when install react 16-rc in cra

![image](https://user-images.githubusercontent.com/6822604/30264914-107c46cc-970d-11e7-9fb8-b21d70d3854e.png)

**Comment by gaearon** [comment]
I don't think this is related to React. It sounds like an issue with your build tool which is probably
trying to tell you there's an issue with your project folder.

Specifically this can happen if you create a folder with an uppercase name (e.g. `D:\Tn`) but then `cd` into it with lowercase name (e.g. `D:\tn`). Or the other way around.

I suggest to create a new folder that's lowercase, move your project files there, and then make sure you always `cd` into it with lowercase name as well.

**Comment by ihtml5** [comment]
thanks @gaearon  I try it

**Comment by kfaruque** [comment]
Solved. as folder's name was the problem.

**Comment by c-zab** [comment]
My problem was: 
App.js -> `import React, { Component } from 'react';`
index.js -> `import React from 'React';`
