### ISSUE TITLE
What's the difference between yarn and npm ??

### ISSUE THREAD

**Issue by teerapat2539** [facebook/react#10662]

**Comment by gaearon** [comment]
npm registry is where people publish their packages.

npm and Yarn are two different clients that are mostly compatible but have some differences in features and tradeoffs.

If you're not sure which one to use I would recommend to go with npm. If for some reason it doesn't satisfy you, you can try Yarn.

This blog post dives into motivation on why Yarn was created: https://code.facebook.com/posts/1840075619545360

Hope this helps!
