### ISSUE TITLE
Build index.html should point to 'static/...' and not to '/static/...'

### ISSUE THREAD

**Issue by MrWeb** [facebook/react#10668]
Once you do a build with `npm run build` the index.html gets CSS and JS files from the root.
This is  because there is a forward slash in the src/href:

`<script type="text/javascript" src="/static/js/main.0bcc9445.js"></script>`
`<link href="/static/css/main.65027555.css" rel="stylesheet">`

Running the index.html on local or remote server doesn't work if the App is not in the root folder and throws a 404 error on the required files.

The correct path should be relative:
`<script type="text/javascript" src="static/js/main.0bcc9445.js"></script>`
`<link href="static/css/main.65027555.css" rel="stylesheet">`
`<link rel="manifest" href="manifest.json">`
`<link rel="shortcut icon" href="favicon.ico">`

This way if you have your project into a sub folder, the App can grab the `static` folder content.

This is true as of React v15.6.1

**Comment by suhaotian** [comment]
Did you use `create-react-app` ? 
If yes, please add `"homepage": "./"` to your `package.json`

**Comment by MrWeb** [comment]
That's right! Thank you!
