### ISSUE TITLE
react-router4.x How to use javascript to control the router where to go

### ISSUE THREAD

**Issue by hengAmethyst** [facebook/react#10693]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
We use the issue tracker for bugs and feature requests in React itself.
Please refer to the community support resources with the questions:
https://facebook.github.io/react/community/support.html
