### ISSUE TITLE
`select` should warn if `value` is not available

### ISSUE THREAD

**Issue by jochenberger** [facebook/react#10691]
IMO, 
```
<select value="foo" onChange={...}>
  <option value="yes">Yes</option>
  <option value="no">No</option>
</select>
```
should warn because there is no "foo" option. It should probably also warn if `value` is not specified, because there is no "empty" option either.
One could also argue that the change handler should be called with {value: 'yes'} when the component renders and the first option is selected instead of an invalid/non-existing one.

**Comment by syranide** [comment]
> should warn because there is no "foo" option. It should probably also warn if value is not specified, because there is no "empty" option either.

Sounds good to me. If value is not specified (null/undef) it is uncontrolled, so that should not warn.

> One could also argue that the change handler should be called with {value: 'yes'} when the component renders and the first option is selected instead of an invalid/non-existing one.

This sounds like a bad idea as it would be interpreted as a user interaction and can have all kinds of unintended side-effects.

**Comment by jquense** [comment]
> This sounds like a bad idea as it would be interpreted as a user interaction and can have all kinds of unintended side-effects.

Yeah, in my experience this leads to bad consequences, as well as inverting the data flow the wrong direction.

**Comment by wuweiweiwu** [comment]
@jquense @gaearon can I pick this up? :)
