### ISSUE TITLE
How does the fetch htttp parameter increment with the timer setInterval?

### ISSUE THREAD

**Issue by mofengfs** [facebook/react#10700]
I want to do a function with the timer to get the number of pages, whenever the timer runs once, the parameter page by 1
This is my code---
```
constructor() {
    super();
    this.state = {
      data: '',
      page: 0 ,
    }
  }

  myFunc = () => {
    let myFetchOptions = {
      method: 'GET',
    };

    fetch("http://xxx/Api/screen/screenByAll.ashx?Status=All&ActionNm=8080&page="+this.setState( (page) => page++ )+"&rows=10",myFetchOptions)
    .then( (response) => response.text() )
    .then( (responseText) => {
      const json = JSON.parse(responseText);
      return json;
    } )
    .then(json => this.setState({data: json}) )
    .catch( (error) =>{
      console.error(error);
    } );

  }

  componentWillMount(){
    setInterval(this.myFunc, 3000);
  }
```

**Comment by jquense** [comment]
Hey there. It looks like your question is more generally about javascript and React usage, than a bug report. We try and keep the issue tracker for feature requests and bug reports. Luckily there are a few other great places to get answers to your question that are better suited than the issue tracker. Check out [Where to get Support](https://facebook.github.io/react/community/support.html)
