### ISSUE TITLE
Can we use react with 2 css framework?

### ISSUE THREAD

**Issue by congkhuong** [facebook/react#10706]
I have project with bulma css. It's done. Now, my team 's going to re-design it with bootstrap framework.

We will do it with this flow:
1. For old screens, we continue use Bulma.
2. For new screens, we will use bootstrap.

We will implement one by one for all screens. Then all pages from **1** move to **2**.

We create new MainLayout for and import css for it, but it still affect to whole pages.

My question is that can i do it with react?

**Comment by jquense** [comment]
Sure, you can do any css thing in React you can do normally

**Comment by aweary** [comment]
Hey @congkhuong, we try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking [Where to Get Support](https://facebook.github.io/react/community/support.html)

**Comment by congkhuong** [comment]
@aweary  Sorry about this.
