### ISSUE TITLE
question about setstate

### ISSUE THREAD

**Issue by MAYDAY1993** [facebook/react#10708]
hi,I came up with some doubt using react,eg:

``` jsx
getInitialState(){
        return (
          instrument={
            row:{
              isSelected: false,
              name:'mayday'
            }
          };
        )
      },
//method 1
 this.state.instrument.row=true;
 this.setState(this.state);
//method 2
 this.setState(Object.assign({},instrument[row],{isSelected:true}));


```
Q1

**instrument** is an object, and I want to change the nested key's value such as **isSelected**,which method is better,I prefer the second,but I'm not sure if it works.

Q2
about nested object,which method is better to change the key's value?

**Comment by gaearon** [comment]
If you have a nested object, you can update it like this:

```js
const newInstrument = Object.assign({}, instrument, {
  row: Object.assign({}, instrument.row, {
    isSelected: true
  })
});
```

It gets a little tedious so I would recommend to use the [object spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator#Spread_in_object_literals) (available as Babel plugin, enabled by default in Create React App):

```js
const newInstrument = {
  ...instrument,
  row: {
    ...instrument.row,
    isSelected: true
  }
};
```

This seems pretty readable to me. If you still don’t like it you can use one of the many helpers like [updeep](https://github.com/substantial/updeep) or [immutability-helper](https://github.com/kolodny/immutability-helper) to update nested objects without mutation.

**Comment by bgnx** [comment]
For more general solution I would recommend your first approach with mutation and invoking setState() (or  forceUpdate()  as alternative) instead of recreating new immutable object, because with immutable approach it's non trivial implement some deep property update where you have dynamic deep of nested objects like comments tree or similar ui, and also regeneration all ancestors objects including coping all items in arrays would decrease js performance compare to single property assignment

**Comment by monkindey** [comment]
This way 

```js
 this.state.instrument.row.isSelected =true;
 this.setState(this.state);
```

look like two way binding, but more redundant than two way binding, because you have to setState.

**Comment by jakecadams** [comment]
Creates dependency of course, but we've loved using https://ramdajs.com w/ React.

```
const R = require('ramda'); 

const newInstrument = R.assoc(
  "row",
  R.merge(instrument.row, { isSelected: true }),
  instrument
);
```

**Comment by gaizka-allende** [comment]
with seamless-immutable:

`const newInstrument = setIn(instrument, ['row', isSelected'], true);`

**Comment by SHUBHAMDAVE001** [comment]
**what should be done if i have to use a object and spread operator in a setState function**
_`handleChangeTextBox1(e){
    this.setState({allData:(this.state.textBox,{textBox:e.target.value} )});
    console.log(e.target.value)
    }`_
here allData is a function which has object textBox
textBox is a input area for data entry.
**i have completed this example using different handle change event and different value for `this.setState`
how can i use this in one setState.**

the older version of code which i have tried is this
_`handleChangeTextBox(e){
    this.setState({allData:{textBox: e.target.value}});
    console.log(e.target.value)
    }`_

### but here the data change in one text box changes the data for all the handle change event.

**Comment by SHUBHAMDAVE001** [comment]
[src (1)-20180621T060702Z-001.zip](https://github.com/facebook/react/files/2123347/src.1.-20180621T060702Z-001.zip)
