### ISSUE TITLE
`unstable_deferredUpdates` can trigger duplicate `setState` calls and miss out others

### ISSUE THREAD

**Issue by ryanwilliams** [facebook/react#10729]
Bug

I know deferredUpdates are unstable, so maybe this is a known problem.

This one is tricky to trigger, but when spamming `setState(function(){})` inside `unstable_deferredUpdates` a LOT you can end up with the same update happening multiple times while other calls are skipped entirely. 

Example code: https://gist.github.com/ryanwilliams/9cfa1bbaa43d8eae6792520a166ae1df
Result: https://i.imgur.com/AOyCNFe.png

If you mouse wheel up and down real fast in the red area you see that console output. I would expect the `bar` number that's output in the console to be unique and in sequence as it's incremented every time before the closure captures it inside the new `setState()`.

Version: react-16-rc3

**Comment by gaearon** [comment]
cc @acdlite in case it’s a bug and it’s not known (I haven’t checked)

**Comment by gaearon** [comment]
I thought I could reproduce it in the past but I can't manage now (even with 16 RC3). So I'll have to close. If you figure out a reproducing case please share it again! Thanks.

**Comment by gaearon** [comment]
Hmm. I *can* reproduce it on RC3 if I add more pressure by replacing `onWheel` with `setTimeout(fn, 1)`:

```html
<html>
  <body>
    <script src="https://unpkg.com/react@16.0.0-rc.3/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@16.0.0-rc.3/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.js"></script>
    <div id="container"></div>
    <script type="text/babel">
const { Component } = React
const { render, unstable_deferredUpdates: deferredUpdates } = ReactDOM

let lastLogged

class Foo extends Component {
  constructor() {
    super();

    this._bar = 0;
    this.state = {
      thing: 0,
    };
  }

  onWheel = (e) => {
    this._bar += 1;
    const bar = this._bar;

    deferredUpdates(() => {
      this.setState((prevState, props) => {
        if (lastLogged && lastLogged !== bar - 1) {
          throw new Error('oops')
        }
        lastLogged = bar;

        return { thing: Math.random() };
      });
    });
  }

  componentDidMount() {
  setInterval(this.onWheel, 1);
}

  render() {
    return (
      <div style={{ background: 'red' }}>
        <Inner onWheel={this.onWheel} style={{ height: '100%' }}>
          WHEEL ME UP AND DOWN REAL FAST.
        </Inner>
      </div>
    );
  }
}

class Inner extends Component {
  onWheel = (e) => {
    e.preventDefault();

    this.setState({ otherThing: Math.random() });
    this.props.onWheel();
  }
  render() {
    return (
      <div style={{ width: 400, height: 200, background: 'red' }} onWheel={this.onWheel}>
        {this.props.children}
      </div>
    );
  }
}

render(<Foo />, document.querySelector('#container'));
    </script>
  </body>
</html>
```

I can also reproduce it with 16.0.0 and 16.1.0.

I didn't manage to reproduce on more recent versions so I assume this got fixed, whatever it was.
