### ISSUE TITLE
? render a list of message to html with new line

### ISSUE THREAD

**Issue by MAYDAY1993** [facebook/react#10731]
hi,
 I'm new to React and I came up with a problem when using it,rendering an array of strings to html:
such as the array:
``
["one","two","three"] 

<img width="32" alt="screen shot 2017-09-18 at 4 25 45 pm" src="https://user-images.githubusercontent.com/14831051/30533854-0becd460-9c8e-11e7-84c6-671d2fc8d46d.png">

I want to render it with a new line,but it seems adding **"br"** or **/n** don't work,
so I use the tag eg. **p** to start a new line:

``
render(){          
          return (
            <div>
              {["one","two","three"].map(item => <p>{item}</p>)}
            </div>
          );
        }
``

is there any method not using block tag ? hoping for advice,thanks.

**Comment by suhaotian** [comment]
说中文。

**Comment by RTsGIT** [comment]
It's not clear if you would like to have them rendered in a single line or in multiple lines.

To have it rendered in a single line you can replace `<p>` tag  in the above code with `<span>`

**Comment by MAYDAY1993** [comment]
@RTsGIT rendered in multiple lines ,

**Comment by cbpetersen** [comment]
You could add `white-space: pre-line;` css style to the outer div, and then join your array with a new line character like `["one","two","three"].join('\n')`


```
render() {
  <div style={{'white-space':'pre-line'}}>
    {["one","two","three"].join('\n')}
  </div>
}
```

**Comment by MAYDAY1993** [comment]
@cbpetersen Thank you but I don't want to use css .

**Comment by matthax** [comment]
@MAYDAY1993 

> Thank you but I don't want to use css .

Then you need to use some sort of block element, how else would the browser know to render it on a new line? It's just basic text, the standard is always to render text as an inline element.

If your requirements really mean no *additional* css styling and no block elements (why???) then you could go this route:

```jsx
<div dangerouslySetInnerHTML={{__html: items.map((item) => item + '</br>').join('')}} />
```

There's a reason it's named as such...

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, please refer to [Where to Get Support](https://facebook.github.io/react/community/support.html) for a list of helpful resources.

As mentioned, you'll need to either use CSS, a block element or `<br />`. React does not have any special behavior around multiline text.
