### ISSUE TITLE
Rendering NaN as DOM attribute

### ISSUE THREAD

**Issue by nikgraf** [facebook/react#10733]
This [blog post](https://facebook.github.io/react/blog/2017/09/08/dom-attributes-in-react-16.html) states that `NaN` values are ignored for DOM attributes. In my tests that's not the case and `NaN` are rendered.

<img width="637" alt="screen shot 2017-09-18 at 10 55 44" src="https://user-images.githubusercontent.com/223045/30535004-dac5cfae-9c60-11e7-9fed-3b06908e4705.png">

I created a CodeSandbox using React 16 RC3 to demonstrate it here https://codesandbox.io/s/xjk7l5owx4

**Comment by gaearon** [comment]
Oops you're right. I think we decided to keep rendering them but always warn. (And you can coerce to string if you do this intentionally.)

**Comment by nikgraf** [comment]
@gaearon thanks for the hint. Does it make sense to update the post?

**Comment by gaearon** [comment]
Yes please!

**Comment by nikgraf** [comment]
Just created a PR here https://github.com/reactjs/reactjs.org/pull/126
