### ISSUE TITLE
Adding the letter 'e' to an input field with type number does not cause the onChange handler to fire

### ISSUE THREAD

**Issue by opr** [facebook/react#10738]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Adding the letter 'e' to an input field with type number does not cause the onChange handler to fire

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
https://jsfiddle.net/617y345p/1/

**What is the expected behavior?**
fire the event with some value at least maybe?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
don't know

**Comment by aweary** [comment]
Hey, @opr! This is a known limitation for controlled number inputs. Check out https://github.com/facebook/react/issues/6556 for more information. Thanks!
