### ISSUE TITLE
change bsd License+patent into other licence, please!

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react#10744]
baidu is already baned to using react,
this licence is  brings extreamly negative effects on the long term development, and hurted people who love react. i am one of them.

i will post this issue everyday until it is change.

**Comment by blling** [comment]
Also hurt by react licence. *_*

**Comment by whyer11** [comment]
fuck the licence

**Comment by gaearon** [comment]
Please stop creating these issues.
See my reply in https://github.com/facebook/react/issues/10719#issuecomment-329862457.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
