### ISSUE TITLE
Give up react cause  licensed

### ISSUE THREAD

**Issue by qifenshu** [facebook/react#10742]
React is a great framework for h5 and native,but i have to give  react up cause bsd+parent licensed.
if react keep using bsd+parent licensed,there will be more and more people give it up.
i'v choose a new framework for my project.
good bye!

**Comment by qifenshu** [comment]
e

**Comment by JackieLs** [comment]
Wish my company will be small enough that fb will never find it.

**Comment by blling** [comment]
React is an excellent js framework, but i must give up it, what a pity.

Some community also give up it, just like wordpress:
https://ma.tt/2017/09/on-react-and-wordpress/

BTW： @aweary Why not hear something from the react community ? Could you leave this issue open for two days?

**Comment by meowtec** [comment]
I am waiting for Facebook acquiring Alibaba so that I can use React any more.

**Comment by blling** [comment]
An open issue is here #10744, maybe it could open for two days? ~~

**Comment by gaearon** [comment]
Please stop creating these issues.
See my reply in https://github.com/facebook/react/issues/10719#issuecomment-329862457.
