### ISSUE TITLE
【Building tools for humans】？what is 【against】？

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react#10747]
according to this patent

`(i) against Facebook or any of its subsidiaries or corporate
affiliates, (ii) against any party if such Patent Assertion arises in whole or
in part from any software, technology, product or service of Facebook or any of
its subsidiaries or corporate affiliates, or (iii) against any party relating
to the Software. Notwithstanding the foregoing, if Facebook or any of its
subsidiaries or corporate affiliates files a lawsuit alleging patent
infringement against you in the first instance, and you respond by filing a
patent infringement counterclaim in that lawsuit against that party that is
unrelated to the Software, the license granted hereunder will not terminate
under section (i) of this paragraph due to such counterclaim`

if this patent is aim to protect facebook itself avoid to legal risk , i think  this patent should be more clearly explain what is 【against】, is this means could not using react to make damage tools  to facebook  or just could not make competitive product ,such as im-soft/ai-soft.

we post these issue because we love react , and don't want to abandon react and really want to using react to building useful things for humans.

**Comment by gaearon** [comment]
Sorry but we will not be having more legal discussion in this repository.
Please stop creating new issues and see my reply in https://github.com/facebook/react/issues/10719#issuecomment-329862457.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
