### ISSUE TITLE
sorry, i will continue to make noise for those people  who really love react and been forced to abandon

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react#10748]
until patent licence is change or be more clearly explain 'against'.

good morning
see you tomorrow.
and, thank you.

**Comment by gaearon** [comment]
I’m sorry you have been forced to abandon React but this behavior is counter-productive.
Please refer to:

* My answer in https://github.com/facebook/react/issues/10719#issuecomment-329862457
* License FAQ https://code.facebook.com/license-faq
* Explaining React license https://code.facebook.com/posts/112130496157735/explaining-react-s-license/

We don’t have anything more to add to this.

If you create more issues (you already created three!) I will have to ban you from the repository.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
