### ISSUE TITLE
TypeError: undefined is not an object (evaluating 's.get.call') from input onChange - React 15.6.1 ReactDOM 15.6.0 on Safari 9.1.x

### ISSUE THREAD

**Issue by toshisugano** [facebook/react#10755]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
onChange onKeyUp onKeyDown causes TypeError: undefined is not an object (evaluating 's.get.call') only in Safari.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
https://codepen.io/anon/pen/rGevxK

**What is the expected behavior?**
Component should get event.target.value and then update the state, which in turn re-renders the h1 with new state values.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
It works for React 15.3.1 ReactDOM15.3.1

**Comment by gaearon** [comment]
Have you tried the latest version of React (15.6.1)?

**Comment by toshisugano** [comment]
Yes. I have tried 15.6.1. Doesn't work properly on Safari.
I have tried 15.3.1 and it works

**Comment by gaearon** [comment]
Which Safari version are you using? Please provide enough details. :-)

**Comment by gaearon** [comment]
>Yes. I have tried 15.6.1. Doesn't work properly on Safari. I have tried 15.3.1 and it works

OK. I got confused by your initial report because you did not specify the version that was broken. And so I read it thinking it‘s 15.3.1 that was broken.

Is my understanding correct that:

* You’re using desktop Safari (which version?)
* The error doesn’t happen with React 15.3.1
* The error happens with React 15.6.1

?

**Comment by jquense** [comment]
This sounds a lot like the bug fixed in 15.6.1...does it work with 15.5.x? Can we get an unminified stack trace?

**Comment by aweary** [comment]
@toshisugano you're using `react-dom` 15.6.0 and `react` 15.6.1. Those packages should always be on the same version, even with patch releases.

Here's a version of your Codepen running version 15.6.1 for both packages: https://codepen.io/Aweary/pen/pWyXWy

I've verified that the issue does not occur in Safari 9 after updating `react-dom` to 15.6.1. Can you confirm that this fixes your issue?

**Comment by toshisugano** [comment]
Yes that was it. It is now working! Thank you so much!!!
