### ISSUE TITLE
TypeError: Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by mynane** [facebook/react#10753]
TypeError: Cannot read property 'createElement' of undefined

**Comment by aweary** [comment]
If you want to report a bug, please fill out the questions in the issue template that you deleted before posting this. A single line from an error message is not enough information to help you.

With that said, it sounds like you're not importing `React`

```js
// you have to do this if you use JSX
import React from 'react'
```

We try to use this issue tracker for bug reports and feature requests. If you have any additional usage or support questions, please refer to [Where to Get Support](https://facebook.github.io/react/community/support.html) for a list of helpful resources.

**Comment by Ali-zain-javed** [comment]
import * as React from 'react';

**Comment by delphin92** [comment]
`import * as React from 'react';`
- this works fine. But sometimes I want import some more, and it's sad that I can't write like this:
`import React, { Component } from 'react';`

**Comment by huangxiao233** [comment]
"esModuleInterop": true

**Comment by pepoandra** [comment]
adding `"esModuleInterop": true` to tsconfig.json + building with webpack + running the server solved the problem for me.

**Comment by matryxxx02** [comment]
> "esModuleInterop": true

OMG, you made my day 🔥
