### ISSUE TITLE
React 16: className with bem-cn like libraries

### ISSUE THREAD

**Issue by ekfn** [facebook/react#10756]
Hello! Really love new features and architecture of Fiber.

But because of this new behavior:
> **Non-event attributes with function values**:
> React 16: Warns and ignores them.

I've got this issue:
```jsx
const fn = () => null;
fn.toString = () => 'foo';

const render = () => (
  <div className={fn}>doesn't add class</div>
);
```

It wouldn't add className, even if i've override `toString` method, but with object it works:

```jsx
const obj = { toString: () => 'foo' };

const render = () => (
  <div className={obj}>works</div>
);
```

I think it's OK to have same behavior with function and object.
This feature is needed in "bem-cn" like library, so I can write just `fn`, instead of `fn()` or `fn.toString()`

**Comment by aweary** [comment]
@ekfn can you expand on why you want to use a function with a custom `toString` method instead of just an object? We want to make sure it's possible to implement dynamic `toString` behavior, but IMO it makes sense to use an object here instead of defining a null returning function.

**Comment by ekfn** [comment]
@aweary 
apparently it wasn't best idea to simplify example by null returning function :)

Using function in className is very common if you want to build class name dynamically, for example in `bem-cn`:

```jsx
import block from 'bem-cn'

const b = block('MyBlock');

const render = () => (
  <div className={b}>
    <div className={b('title')}>My title</div>
    <div className={b('content')}>My content</div>
  </div>
);

// className={b} would return 'MyBlock'
// className={b('title')} would return 'MyBlock__title'
// etc
```

So you can use `className={b('title')}` for inner elements and just `className={b}` for base block, instead of `className={b()}` or `className={b.toString()}`, which is really nice.

**Comment by nhunzaker** [comment]
This makes sense. I have no idea what the edge cases are if we were to allow functions with custom toString methods. Maybe this could be done with className only.

I'm not really sure what the best call here is, but it would be great to identify if we want to continue to support this use case.

**Comment by ekfn** [comment]
Yeah, for className attribute I think it should works this way: convert value to string or die trying.

For custom attributes though - not sure. I'm curious what so special about objects, that we try to convert it to string, but boolean values would be just ignored. And how react understands which attributes is `Non-event`, what if browser-specific non-standard attributes uses functions?

**Comment by hrkv** [comment]
bem-cn wrapper to return strings instead functions https://github.com/mistakster/bem-cn-lite

**Comment by ekfn** [comment]
@hrkv 
It's not a problem to return string instead of function (or object, which is work), it's about do we support this feature or not.

**Comment by gaearon** [comment]
Why not just write `className={b()}`? Seems like more explicit and it's easier to understand what it does.

**Comment by seriouslyfluffy** [comment]
this tool https://github.com/alfa-laboratory/cn-decorator
is what you need

**Comment by ekfn** [comment]
@gaearon again, there's many ways to do this, IMO `className={b}` is better (cause it's shorter), but it doesn't matter. The question is why object with `toString` is valid value, but function doesn't. It doesn't make sense to me.
Also, everyone who use bem-cn can't update to react v16 without replacing this line in every presentational component.

@seriouslyfluffy doesn't is use function as well?

**Comment by ekfn** [comment]
But my question, in general, is why object with `toString` is valid value and function doesn't.

**Comment by ekfn** [comment]
So, what we have:
1. We can't use chainable API with any attributes (like this `b('icon')({name: 'check'})`);
2. Anyone, who use `bem-cn` (or similar) library, would need a lot of refactoring to update to react v16;
3. I can't think of __any__ disadvantages of calling `toString` on function, instead of just ignoring it.

@gaearon @aweary

**Comment by gaearon** [comment]
Even if we called the function, we would still want to print a warning. Because most often passing a function happens due to a mistake, not deliberate (e.g. if you forget to call it). Silently ignoring it is worse because it usually means a bug. Since we warn, libraries shouldn't rely on it anyway, as we encourage people to treat warnings as errors. So that's why passing it through doesn't look like a solution to me.

I don't quite understand the advantages of the chainable interface you're suggesting over simpler interface that accepts a variable number of arguments and always returns a string.

**Comment by ekfn** [comment]
> Since we warn, libraries shouldn't rely on it anyway

Yeah, in this case, this is pretty same as ignoring (silently or not).

> I don't quite understand the advantages of the chainable interface you're suggesting over simpler interface 

Do i really need to explain why different interfaces are good and fun in deffirernt cases?

> But if it's a big problem I encourage you to build a codemod to a new API

Thanks for suggestion, that's a good practice, but I don't use `bem-cn` by myself, so it's not a problem for me.

Personally, in this case, I would prefer not changing API over `it catches more bugs`.

**Comment by iseeyou911** [comment]
Hi, i make codemod for the issue https://github.com/iseeyou911/jscodemodes/tree/master . May be it would help for someone.
