### ISSUE TITLE
I think we should remove our girhub Star form this project bacause of reat license!!!

### ISSUE THREAD

**Issue by xiaoming0827** [facebook/react#10767]
I think we should remove our girhub start form this project bacause of reat license!!!

I think we should remove our girhub start form this project bacause of reat license!!!

I think we should remove our girhub start form this project bacause of reat license!!!

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
