### ISSUE TITLE
[React 15+] Cloudflare's HTML minification causes isomorphic React app to crash

### ISSUE THREAD

**Issue by gaulucky92** [facebook/react#10778]
I think this is not a bug, it's a compatibility issue.

[In React v15.x+](https://facebook.github.io/react/blog/2016/04/07/react-v15.html#rendering-null-now-uses-comment-nodes), the server-sided HTML rendered by `react-dom/server`'s function `renderToString()` contains some comment tags that represent null components (instead of `<noscript>` tags like React v0.14.x), which is really neat.
Unfortunately, when the app is served by Cloudflare with HTML minification enabled, it automatically removes all the comment tags, including the ones generated by React.
This behavior causes the client app to crash, and throws an error:

```
Unable to find element with ID x.
```

With x is a number, usually the null component's react-id.

The problem can be solved by [*disabling HTML minification on Cloudflare*](https://www.garysieling.com/blog/react-cloudflare-bundle-js38-uncaught-invariant-violation-unable-find-element-id-18), but the question is, is it possible to earn the benefit from HTML minification, while keep the app running well?

React/ReactDOM version: 15.6.1
Node version: 6.10.0 / 6.10.3

**Comment by gaearon** [comment]
I might be wrong but I think React 16 (a release candidate is out and you can try it) doesn't use comments.

**Comment by gaulucky92** [comment]
@gaearon Thanks for your suggestion. I am using React 15 on production, so I think it's not a good idea to try the RC of React 16. Anyway, being recommended to try React 16, should I understand that there are no solutions for React 15?

**Comment by gaearon** [comment]
This is correct. React 15 relies on comments. React 16 does not.
