### ISSUE TITLE
TestUtils.Simulate does not appear to work with React.cloneElement

### ISSUE THREAD

**Issue by anthuswilliams** [facebook/react#10774]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

ReactTestUtils.Simulate events do not fire on dynamic children components.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

I have a class like this:

```
class KeyboardSupport extends React.Component {
  render() {
    return React.cloneElement(React.Children.only(this.props.children, {
      onKeyDown: this.doSomething
    }
  }

  doSomething() { /* do something */ }
}
```

I use it within another component, like so:

```
class Foo extends React.Component {
  render() {
    return <KeyboardSupport>
      <div className="foo" onFocus={this.handleFocus.bind(this)} />
    </KeyboardSupport>;
  }

  handleFocus() {
    console.log('This will be called in the browser, but will not be called in test');
  }
}
```

As indicated, `Foo.handleFocus` will be invoked when a user focuses on the component in the browser, but when I attempt to use something like `ReactTestUtils.Simulate.focus(findRenderedDOMComponentWithClass(document, 'foo'))` it will never be called.

**What is the expected behavior?**

The cloned element should still fire the synthetic focus event.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This works as expected using the deprecated `react-addons-test-utils` package (React 15.4.1). Does not appear to work using 15.5.4.

**Comment by jdeveloperw** [comment]
+1 I'm seeing this issue too.

**Comment by gaearon** [comment]
Can you please share a complete example on GitHub?

**Comment by gaearon** [comment]
There was no complete reproducing example or a fiddle so I’m closing.

It takes a lot of time to investigate reports so unfortunately we can’t focus on the ones that don’t provide the reproducing code ready to run.

**Comment by anthuswilliams** [comment]
Sorry mate, I had forgotten about this. I'll try to put together a fiddle when I can find the time and reopen later.

**Comment by gaearon** [comment]
Thanks!
