### ISSUE TITLE
Error from component causes error to be thrown twice

### ISSUE THREAD

**Issue by guyfedwards** [facebook/react#10779]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a component throws not in render, for example in a click handler, the error is thrown twice instead of once. Error boundaries stop the double reporting, but only handle errors thrown in render, not errors in handlers etc.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
https://codepen.io/anon/pen/GMjEpx?editors=0010

**What is the expected behavior?**
Just one error thrown

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.0.0-rc.2

**Comment by gaearon** [comment]
Error boundaries don’t (currently) catch errors coming from event handlers. The [blog post](https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html) goes into more detail about this:

>Error boundaries catch errors during rendering, in lifecycle methods, and in constructors of the whole tree below them.

**Comment by guyfedwards** [comment]
Thats ok but the error still seems to be rethrown resulting in two errors being caught in `window.onerror`

**Comment by gaearon** [comment]
This seems like the same discussion as https://github.com/facebook/react/issues/10474.
