### ISSUE TITLE
In WebDriver, input gets partial value on IE11 after upgrading react-dom from to 15.6.1

### ISSUE THREAD

**Issue by zouning** [facebook/react#10776]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
We use webdriverIO + saucelabs to run our tests and found our automation cases consistently failed on IE11 while inputing strings to textbox after upgrade react-dom from 15.5.4 to 15.6.1.
The input value will be set partially, such as, try to input "-7d" it will only input "-7", some times, it will be '-d'.

In javascript webdriverIO code:
browser.setValue(textboxSelector, '-7d');

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
Not sure if you could see this video or not:
https://saucelabs.com/beta/tests/bda474ef398949f6ae5dabb4a15fb1a3/watch#27

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
happens to React-dom 15.6.1 with IE11
works on React-dom 15.5.4

**Comment by gaearon** [comment]
cc @jquense

**Comment by jquense** [comment]
The dedupe logic is the obvious candidate for this but I cannot deduce what might be happening wrong to get this result. We've got a bunch of webdriver tests and testing on IE11 and not seeing this, which doesn't help the debugging this hmm.

I'd great if there maybe a small repo with a dirt simple app (just a textbook) and a saucelabs setup that inputs text to test on. @zouning care to put something together?

**Comment by zouning** [comment]
@jquense our app might be a little bit complex. It will take me some time to do that. I will have a try.

**Comment by gaearon** [comment]
I’ll close this as stale. I’d say it’s very unlikely we’ll work on a fix for this so unless you can dig into what happened, there won’t be progress. Closing.
