### ISSUE TITLE
Learning React is a problem

### ISSUE THREAD

**Issue by ArtGangsta** [facebook/react#10784]
Every time I decide that I want to learn React, I google and find some tutorial, from seemingly reputable sources.    Then I try a few things, google more; go to stack-overflow and very quickly i realize that the syntax is different between different web-sites ..  the API keeps changing, and I don't know if I'm looking at an old tutorial, or a new one -- I have no way of determining if a stackoverflow question is going to apply because of the version of React that I'm using.

What I think is needed is some kind of master list that's based on an "era" of the API.  I'm not talking about semver which is too low-level.  I'm talking about something like:

First when React came out, this is how we did things...  and every one was happy.

Then came the Silver Age of React, where we did things the following way..  We took this out, and we put this in.  So if you see this thing, that's old, from the Golden age.   

Then we hit the Bronze era -- and this is where we split everything into tiny pieces, and now you have to be more specific, blah blah blah.

That can serve as a cheat-sheet for anyone new to make sense of what's going on.

It's kinda similar to how if I look at a piece of C#, I could say, "yeah, this is circa-2005" or, "oh, this looks very 2010ish."

thanks for listening.

**Comment by gaearon** [comment]
Did you try learning form the docs?

**Comment by gaearon** [comment]
(Never mind my previous comment, hit "Enter" too soon).

Did you try learning from the docs?

We have a tutorial here: https://facebook.github.io/react/tutorial/tutorial.html
It documents the current version.

We also have a step-by-step introduction here:
https://facebook.github.io/react/docs/hello-world.html

It explains every concept one by one.

I agree a cheatsheet like you describe would be nice. I'm not sure if it should be in the official docs or would better be as a blog post. Would you like to write it?

**Comment by darrenlittlejohn** [comment]
I'd like to write it.

**Comment by IamManchanda** [comment]
Then you should go for it @darrenlittlejohn

**Comment by ArtGangsta** [comment]
Dam, upon further reflection, I have to say that I agree with you.   Before I complain about inconsistent documentation, I should have tried using the documentation that comes with React proper and see if it is sufficient.   What I did instead was go on pluralsight, google, and youtube, and found it frustrating that I would start to learn some syntax only to learn that it's the wrong syntax as compared to what I see elsewhere..   And then I have to decide which is the correct form -- that is, what is new and what is old is not always obvious.

I'm so used to documentation from the vendor being insufficient to the point that I have to look elsewhere..   that I typically start with that instead of looking at the docs that come with the library.

I've since looked at the links you posted and I think they look quite excellent and approachable, so thank you.

**Comment by nhunzaker** [comment]
Hey @ArtGangsta! I am happy that you found the React documentation helpful. The team puts a ton of attention into it so that React is easy to get started. If something in the documentation is confusing, and you have suggestions for improving it, feel free to let us know!

Best of luck, and welcome to the React community!

**Comment by gaearon** [comment]
I'd also add that it would be nice if we could host "archived" versions of the website for old versions. So that people can still look up their APIs etc. Might be easier to do after we switch to the new website.

**Comment by aweary** [comment]
@gaearon what about providing a versioned API page, so you could just switch between different major versions on the same site?
