### ISSUE TITLE
thank you Relicensing React, Jest, Flow, and Immutable.js

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react#10789]
thousands developer love react,
and it is really a great amazing framework,
so many company  such as ( baidu/alibaba/tencent/zhihu) is using react building products for millons upon millons people.

thank your brilliant great work ,and ,thank your generous noble spirit.

**Comment by qifenshu** [comment]
good news

**Comment by gaearon** [comment]
Thanks! We hope this makes it easier for people who like React to use it at their jobs.
