### ISSUE TITLE
If react will under mit license next week

### ISSUE THREAD

**Issue by qifenshu** [facebook/react#10788]
Some days age,my boss asked me stop react cause react was under bsd+patent grant license. so our plan for develop is stopped ,and we have to choose a new framework, and learn it.
Reat is the best framework for me.

I heard that fb is relicenseing react under mit license next week,is it true?

Till now,we want use react , but we also need learn other framework, if the news is true, we can make a decision to back react.

**Comment by sreetamdas** [comment]
Yes, have a read at [https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/)

**Comment by gaearon** [comment]
Yes, it's true.
