### ISSUE TITLE
Component unmounts, constructor state sets up, componentWillMount does not fire.

### ISSUE THREAD

**Issue by LAITONEN** [facebook/react#10790]
**What is the current behavior?**
Component unmounts, constructor state sets up, componentWillMount does not fire.

**What is the expected behavior?**
If constructor state sets up,  the the componentWillMount must probably fire right after it? Is this correct?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
1. 16.0.0-alpha.12
2. Not sure.

**Comment by thomasyimgit** [comment]
I don't quite get what you mean by "unmount".

But yes, the invoking sequence is `constructor` -> `componentWillMount`.
You can refer to this for more info:
https://facebook.github.io/react/docs/react-component.html#constructor

**Comment by LAITONEN** [comment]
@thomasyimgit componentWillUnmount is the last lifecycle method in the workflow of a component. By unmounting I mean exactly that, that the component "turns itself off" and before that it calls the componentWillUnmount method.

**Comment by gaearon** [comment]
Please don't use alpha versions of React on the web, they were never meant for general consumption. 

It is not very clear to me what exactly the issue is. Can you please provide a fiddle reproducing it with React 16?

**Comment by LAITONEN** [comment]
@gaearon 
1. Understood, but that's what was installed by default, I suppose.
2. It is hard to provide a fiddle since I have not figured out what part of my app causes this, meaning that even if I provide a fiddle-like example, it will basically be almost my entire app. So, I just wanted to know if this kind of behavior is generaly possible or something must be wrong in my app.

**Comment by gaearon** [comment]
>Understood, but that's what gets installed by default when initializing the react-native project with react-native init ProjectName. So, something is wrong on react-native part, as I understand.

That's why I said "on the web" 😉 . On RN, it's fine. (It doesn't use the alpha version of the reconciler.)

>It is hard to provide a fiddle since I have not figured out what part of my app causes this, meaning that even if I provide a fiddle-like example, it will basically be almost my entire app. So, I just wanted to know if this kind of behavior is generally possible or something must be wrong in my app.

It's hard to guess. What you describe sounds odd to me, but I can't say more without seeing a reduced example.

**Comment by LAITONEN2** [comment]
@gaearon Alright. Thanks! I will provide any arising details if those come out.

**Comment by LAITONEN** [comment]
@gaearon Alright. Thanks! I will provide any arising details if those come out.
