### ISSUE TITLE
installation.md content update

### ISSUE THREAD

**Issue by KoltonG** [facebook/react#10806]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Line 128 in installatin.md file is saying `npm start`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
Line 128 in installation.md file should say `yarn start`

**What is the expected behavior?**
Line 128 in installation.md file should say `yarn start` since the latest installation of create-react-app is now using yarn

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
N/A

**Comment by montogeek** [comment]
Could you please submit a PR?

**Comment by aweary** [comment]
The [README in the `create-react-app` repo](https://github.com/facebookincubator/create-react-app/blob/master/README.md) still uses `npm`. We'll probably keep it consistent and stick with `npm` for now. Feel free to use `yarn` if you'd like though 😃 

Thanks!
