### ISSUE TITLE
Update Thinking in React example to filter products in FilterableProductTable component

### ISSUE THREAD

**Issue by danielsbird** [facebook/react#10808]
In [step 4](https://github.com/facebook/react/blob/master/docs/docs/thinking-in-react.md#step-4-identify-where-your-state-should-live) of the Thinking in React example, the `ProductTable` component filters and displays an array of products based on user input.

I am unsure why the code for filtering the products is in the `ProductTable` component and not the `FilterableProductTable` component. The same question was [previously raised](https://github.com/facebook/react/issues/8035#issuecomment-269130572)  in issue #8035.

I think having `FilterableProductTable` be responsible for filtering the products would improve the example for two reasons:

* Allow `ProductTable` to be used outside of `FilterableProductTable`
* Better separate the concerns of filtering the products from displaying the products

I [updated the example](https://github.com/danielsbird/react/commit/2869b01314713b53fd39aedefa1693d4042d348c) and I'm happy to submit a PR if this is something that should be changed.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

Please open a new issue in that repository. Sorry for the inconvenience!
