### ISSUE TITLE
error decoder website not displaying any messages for error codes

### ISSUE THREAD

**Issue by jharris4** [facebook/react#10838]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

visiting https://facebook.github.io/react/docs/error-decoder.html?invariant=149 does not show the error message

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

MacOS 10.13 / Chrome 61

**Comment by aweary** [comment]
Hey @jharris4, I'm seeing an error message on the page you linked

> Element ref was specified as a string ([missing argument]) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

Are you seeing something different?

**Comment by gaearon** [comment]
We should probably the message bold or something. It's easy to miss.

**Comment by aweary** [comment]
@gaearon good call, maybe even style it as a redbox so it's even easier to see?

**Comment by jharris4** [comment]
There error message is showing now.

It really was not there when I filed the issue though, I even tried refreshing, clearing cache, changing the error code etc.

**Comment by aweary** [comment]
@jharris4 there as a brief period after React 16 was launched where the CDN URLs we were using for the docs site were invalid. This was resolved by https://github.com/facebook/react/pull/10837. You probably visited the site during that period of downtime 👍
