### ISSUE TITLE
Broken Links on new docs

### ISSUE THREAD

**Issue by clemmy** [facebook/react#10852]
#### Root
`/acknowledgements.html` in the footer

#### Inside `docs/hello-world.html`,
- Installation (`/react/docs/installation.html`)

#### Inside `docs/installation.html` (under `Add React to an Existing App` tab)
- While React can be used... `/react/docs/react-without-es6.html`
- ...setting up a production build process... `/react/docs/optimizing-performance.html#use-the-production-build`
- Learn more about integrating React with existing code.
`/react/docs/integrating-with-other-libraries.html#integrating-with-other-view-libraries`
- all the links about creating a production build `/react/docs/optimizing-performance.html`
- ...better error handling experience in... `/react/blog/2017/07/26/error-handling-in-react-16.html`

#### Inside `docs/introducing-jsx.html`
- ...in the next section `/react/docs/rendering-elements.html`

#### Inside `docs/rendering-elements.html`
- ...in the next section `/react/docs/components-and-props.html`
- ...encapsulated into stateful components `/react/docs/state-and-lifecycle.html`

#### Inside `docs/components-and-props.html`
- ...we will discuss in the next sections `/react/docs/state-and-lifecycle.html`
- ...In the next section,... `/react/docs/state-and-lifecycle.html`

#### Inside `docs/state-and-lifecycle.html`
- ...from one of the previous sections `/react/docs/rendering-elements.html#updating-the-rendered-element`
- We mentioned before... `/react/docs/components-and-props.html#functional-and-class-components`

#### Inside `docs/handling-events.html`
- See the SyntheticEvent reference... `/react/docs/events.html`
- ...create a stateful component called... `/docs/state-and-lifecycle.html#adding-local-state-to-a-class`
- ...embed any expressions in JSX... `/react/docs/introducing-jsx.html#embedding-expressions-in-jsx`
- ...extract a component `/react/docs/components-and-props.html#extracting-components`

#### Inside `docs/lists-and-keys.html`
- `/react/docs/rendering-elements.html`
- `/react/docs/introducing-jsx.html#embedding-expressions-in-jsx`
- `/react/docs/rendering-elements.html#rendering-an-element-into-the-dom`
- `/react/docs/components-and-props.html`
- `/react/docs/reconciliation.html#recursing-on-children`
- `/react/docs/components-and-props.html#extracting-components`
- `/react/docs/introducing-jsx.html#embedding-expressions-in-jsx`
- `/react/docs/components-and-props.html#extracting-components`

#### Inside `docs/forms.html`
- `/react/docs/react-component.html#setstate`
- `/react/docs/state-and-lifecycle.html#state-updates-are-merged`
- `/react/docs/uncontrolled-components.html`

#### Inside `docs/lifting-state-up.html`
- `/react/docs/components-and-props.html#props-are-read-only`
- `/react/docs/state-and-lifecycle.html#the-data-flows-down`

#### Inside `docs/thinking-in-react.html`
- Simply refer to the React docs... `/react/docs/`
- `/react/docs/interactivity-and-dynamic-uis.html`

#### Inside `docs/jsx-in-depth.html`
- `/react/docs/conditional-rendering.html`
- `/react/docs/lists-and-keys.html`

#### Inside `docs/typechecking-with-proptypes.html`
- `/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes`

#### Inside `docs/refs-and-the-dom.html`
- `/react/docs/components-and-props.html`
- `/react/docs/lifting-state-up.html`
- `/react/docs/react-dom.html#finddomnode`

#### Inside `docs/uncontrolled-components.html`
- `/react/docs/forms.html`
- `/react/docs/refs-and-the-dom.html`

#### Inside `docs/react-without-es6.html`
- `/react/blog/2016/07/13/mixins-considered-harmful.html`
- `/react/docs/top-level-api.html#react.createclass`
- `/react/docs/working-with-the-browser.html#component-lifecycle`

#### Inside `docs/context.html`
- `/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes`
- `/react/docs/react-component.html#constructor`
- `/react/docs/react-component.html#componentwillreceiveprops`
- `/react/docs/react-component.html#shouldcomponentupdate`
- `/react/docs/react-component.html#componentwillupdate`
- `/react/docs/react-component.html#componentdidupdate`
- `/react/docs/react-component.html#the-component-lifecycle`

#### Inside `docs/higher-order-components.html`
- `/react/blog/2016/07/13/mixins-considered-harmful.html`

#### Inside `docs/integrating-with-other-libraries.html`
- `/react/docs/refs-and-the-dom.html`
- `/react/docs/react-component.html#the-component-lifecycle`
- `/react/docs/uncontrolled-components.html`
- `/react/docs/react-dom.html#render`
- `/react/docs/handling-events.html`
- `/react/docs/lifting-state-up.html`
- `/react/docs/react-component.html#forceupdate`
- `/react/docs/higher-order-components.html`

#### Inside `docs/react-api`
- `/react/docs/react-without-es6.html`
- `/react/docs/introducing-jsx.html`
- `/react/docs/react-without-jsx.html`
- `/react/docs/react-component.html`
- `/react/docs/react-component.html#shouldcomponentupdate`
- `/react/docs/react-component.html#forceupdate`
- `/react/docs/rendering-elements.html`
- `/react/docs/components-and-props.html`
- `/react/docs/introducing-jsx.html`
- `/react/docs/react-without-jsx.html`
- `/react/docs/components-and-props.html`
- `/react/docs/react-without-jsx.html`

#### Inside `docs/react-dom.html#finddomnode`
- `/react/docs/components-and-props.html#functional-and-class-components`
- `/react/docs/more-about-refs.html`
- `/react/docs/more-about-refs.html#the-ref-callback-attribute`

#### Inside `docs/react-dom-server.html#rendertostring`
- `/react/docs/react-dom.html#render`

#### Inside `docs/react-dom-node-stream.html`
- `/react/docs/react-dom.html#render`

#### Inside `docs/events.html`
- `/react/docs/handling-events.html`

#### Inside `docs/test-utils.html`
- `/react/docs/shallow-renderer.html`
- `/react/docs/events.html#supported-events`

#### Inside `docs/shallow-renderer.html`
- `/react/docs/react-dom.html#render`

#### Inside `docs/test-renderer.html`
- None of the soft links work (incorrect capitalization)

#### Inside `contributing/how-to-contribute.html`
- `/react/downloads.html`
- `/react/contributing/codebase-overview.html`

#### Inside `contributing/codebase-overview.html`
- `/react/contributing/how-to-contribute.html`
- `/react/contributing/how-to-contribute.html#development-workflow`
- `/react/docs/top-level-api.html#react`
- `/react/docs/reconciliation.html`
- `/react/docs/top-level-api.html#reactdom`
- `/react/docs/reconciliation.html`
- `/react/docs/reconciliation.html`
- `/react/docs/advanced-performance.html#avoiding-reconciling-the-dom`
- `/react/contributing/implementation-notes.html`

#### Inside `contributing/implementation-notes.html`
- `/react/contributing/codebase-overview.html#stack-reconciler`
- `/react/contributing/codebase-overview.html`
- `/react/blog/2015/12/18/react-components-elements-and-instances.html`
- `/react/contributing/codebase-overview.html#stack-renderers`
- `/react/contributing/codebase-overview.html#fiber-reconciler`
- `/react/contributing/codebase-overview.html#dynamic-injection`
- `/react/contributing/codebase-overview.html#fiber-reconciler`
- `/react/contributing/design-principles.html`

#### Inside `contributing/design-principles.html`
- `/react/docs/thinking-in-react.html`
- `/react/blog/2016/07/13/mixins-considered-harmful.html`
- `/react/docs/more-about-refs.html`
- `/react/docs/context.html`
- `/react/warnings/unknown-prop.html`
- `/react/blog/2016/02/19/new-versioning-scheme.html`
- `/react/blog/2015/12/18/react-components-elements-and-instances.html#elements-describe-the-tree`
- `/react/docs/displaying-data.html#jsx-syntax`
- `/react/docs/webcomponents.html`
- `/react/blog/2016/07/11/introducing-reacts-error-code-system.html`

#### Inside `tutorial/tutorial.html`
- `/react/docs/installation.html#creating-a-new-application`
- `/react/community/support.html#reactiflux-chat`
- `/react/docs/react-api.html#createelement`
- `/react/tutorial/tutorial.html#why-immutability-is-important`
- `/react/docs/optimizing-performance.html#examples`
- `/react/docs/hello-world.html`
- `/react/docs/react-component.html`

Note that I didn't go through the blog posts. 😃

**Comment by bvaughn** [comment]
Thanks a ton for putting this list together, @clemmy!

I believe all of the broken links have now been fixed by removing the `/react` prefix from the path in markdown files (#10853) and adding the missing Acknowledgements page (#10873)

**Comment by clemmy** [comment]
@bvaughn I just took a look at the new deploy, it seems that most of them are fixed except for the following:

```
Inside docs/test-renderer.html

None of the soft links work (incorrect capitalization)
```

**Comment by bvaughn** [comment]
Nice catch~

**Comment by bvaughn** [comment]
Hm, can you clarify which soft links you're referring to? All of the ones I've tried seem to work.

**Comment by clemmy** [comment]
<img width="557" alt="screen shot 2017-09-27 at 11 42 54 am" src="https://user-images.githubusercontent.com/3696934/30931267-071f1e7e-a379-11e7-82bc-96134e3c6b33.png">

**Comment by bvaughn** [comment]
Ah, I see. Those are broken on the old site too (https://facebook.github.io/react/docs/test-renderer.html) but good catch.

**Comment by bvaughn** [comment]
Fixed via fb77b3d

**Comment by gaearon** [comment]
Haha I was just about to do it :P

**Comment by bvaughn** [comment]
Whoops, sorry.

**Comment by gaearon** [comment]
Are you sure that fix is right?

I don't think https://facebook.github.io/react/docs/test-renderer.html#testinstancefindallbytype works. https://facebook.github.io/react/docs/test-renderer.html#testinstance.findallbytype would work.

**Comment by gaearon** [comment]
Ah, maybe it works on Gatsby :D

**Comment by bvaughn** [comment]
Yeah, I tested every link before making the change. 😄
