### ISSUE TITLE
Bug: event.isTrusted always true in onFocus event handler

### ISSUE THREAD

**Issue by lukeggchapman** [facebook/react#10858]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When triggering focus on an element the onFocus handler receives event.isTrusted true.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

https://codesandbox.io/s/7yr3300yl1

**What is the expected behavior?**
event.isTrusted to be false when focus is triggered programatically

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
So far I've reproduced in React 16.0.0 and 15.5.4 with Chrome 61.0.3163.100

**Comment by gaearon** [comment]
Why do you think it's a React bug? Does using the browser event system give you a different behavior?

**Comment by lukeggchapman** [comment]
My mistake, I thought it might have been something that React's synthetic event was managing.
FF and Chrome behave the same way.

**Comment by gaearon** [comment]
👍 No worries, thanks for checking.
