### ISSUE TITLE
Suggestion to remove misleading docs code on new react portals

### ISSUE THREAD

**Issue by manpenaloza** [facebook/react#10850]
**Do you want to request a *feature* or report a *bug*?**
i want to suggest a docs optimization to not mislead the core idea of new react portals

**What is the current behavior?**
currently docs (https://facebook.github.io/react/docs/portals.html) example code uses a js-created div element referenced by the object's this.el property, which further on is used in _componentDidMount_, _componentWillUnmount_ and _render_ of the Modal class component.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
<img width="382" alt="modal_this_el" src="https://user-images.githubusercontent.com/4241744/30886292-cebf8ef4-a316-11e7-8a59-ad04d37d2af8.png">

**What is the expected behavior?**
from my point of view the above mentioned implementations represent misleading/unnecessary docs boilerplate that might lead to "do I have to do that?"-confusion. especially at the beginning of a new feature this should probably be denied as good as possible. here's a (working) fork showing the core idea of that feature and nothing else https://codepen.io/manpenaloza/pen/jGBVxm?editors=0110#0

**Which versions of React, and which browser / OS are affected by this issue?**
16.0.0

---
in case you agree, I can open a pull request.

**Comment by gaearon** [comment]
I actually think showing this is valuable because this gives you a sense of how to use it in real projects. You'll probably want to have control over the order in which they are stacked in the DOM, and this technique gives you that. But perhaps there's a better way to explain it.

cc @acdlite

**Comment by manpenaloza** [comment]
yes, it's definitely a way to get control over the order. on the other hand, shouldn't this be (more) part of how portal components are built? I updated the pen by adding the class _portal-root_ in the component to point out what I mean.

if writing portals the way current docs demonstrate is a must to make them work, creating the showcase like it is would be perfectly ok. to me it more seems like additional boilerplate that might more confuse than explain (especially at the beginning of that very cool react extension).

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

Please open a new issue in that repository to continue the discussion. Sorry for the inconvenience!
