### ISSUE TITLE
Thinking in React Example does not filter correctly

### ISSUE THREAD

**Issue by bbarnell** [facebook/react#10869]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you type "bas" you don't get hits for Baseball and Basketball

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

[https://facebook.github.io/react/docs/thinking-in-react.html](url)

**What is the expected behavior?**
You get Basketball and Baseball when you type "bas"

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Version 16

**Comment by bbarnell** [comment]
Never mind.  It's case sensitive

**Comment by roblevintennis** [comment]
But I agree this IS a bug. It should not be case sensitive. I implemented it simply:

```javascript
  props.products.forEach(product => {
    if (product.name.toLowerCase().indexOf(props.filter) === -1) {
      return;
    }
...
```

That said, yah, it's just an exercise so I suppose it's sort of ok lol
