### ISSUE TITLE
React 16.0.0 fiber batched updates ignores 2nd and further arguments

### ISSUE THREAD

**Issue by jozefchutka** [facebook/react#10866]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Calling ReactDOM.unstable_batchedUpdates(fn, a, b) eventaully calls fn(a) ignoring the third argument.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
```
ReactDOM.unstable_batchedUpdates(console.log, 0, 1) // outputs 0
```

**What is the expected behavior?**
```
ReactDOM.unstable_batchedUpdates(console.log, 0, 1) // outputs 0 1
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
bug in 16.0.0, worked in 15.5.4

The possible workaround is:
```
ReactDOM.unstable_batchedUpdates(function(){
    console.log(0, 1)
})
```

**Comment by gaearon** [comment]
I think we just support a single argument now. We should probably call it out in the breaking changes.

**Comment by jozefchutka** [comment]
Unfortunately, I do not have bandwidth to figure out the right way to fix it... The furthest I could get is to realize there are two batches now stackBatchedUpdates vs. fiberBatchedUpdates each defined differently while only fiber one is being in use:

```
var stackBatchedUpdates = function (fn, a, b, c, d, e) {
  return fn(a, b, c, d, e);
};
var fiberBatchedUpdates = function (fn, bookkeeping) {
  return fn(bookkeeping);
};
```

**Comment by gaearon** [comment]
Yes, this means that we now support only one argument. Happy to take a PR that notes this in breaking changes.

**Comment by watadarkstar** [comment]
@gaearon Made a PR #10954 :)
