### ISSUE TITLE
unpkg latest not working

### ISSUE THREAD

**Issue by oldboysmith** [facebook/react#10864]
The following links have ceased to work in the last day:

https://unpkg.com/react@latest/dist/react.js
https://unpkg.com/react-dom@latest/dist/react-dom.js

The top one returns:

Cannot find module "/dist/react.js" in package react@16.0.0

**Comment by OlegLustenko** [comment]
you can choose cjs or umd build, take a look:  https://unpkg.com/react@16.0.0/ - last slash is important
for example, production builds:

https://unpkg.com/react@16.0.0/cjs/react.production.min.js
https://unpkg.com/react-dom@latest/cjs/react-dom.production.min.js

**Comment by gaearon** [comment]
Yes, the change in URL was mentioned both in the changelog and the release notes.

To avoid breakage in the future please make sure to use a specific version in the URL.

**Comment by gaearon** [comment]
To be clear, **in the browser you need to use the UMD builds**.

Development versions:

https://unpkg.com/react@16/umd/react.development.js

https://unpkg.com/react-dom@16/umd/react-dom.development.js

Production versions:

https://unpkg.com/react@16/umd/react.production.min.js

https://unpkg.com/react-dom@16/umd/react-dom.production.min.js

**Comment by oldboysmith** [comment]
Thanks
