### ISSUE TITLE
Update implementation notes documentation

### ISSUE THREAD

**Issue by pomber** [facebook/react#10877]
The [implementation notes](https://facebook.github.io/react/contributing/implementation-notes.html) still describes the stack reconciler.

(I'm currently using the resources from [koba04/react-fiber-resources](https://github.com/koba04/react-fiber-resources) but it would be great to have an updated description of Fiber as part of the official docs)

**Comment by gaearon** [comment]
Yea.. So this is going to be tricky because implementing Fiber-like reconciler is less trivial, and the specific details might get in the way of the explaining the core idea.

**Comment by pomber** [comment]
I published a [small Fiber-like reconciler](https://engineering.hexacta.com/didact-fiber-incremental-reconciliation-b2fe028dcaec) yesterday, maybe it helps someone to extract the core idea.

**Comment by gaearon** [comment]
I’ll close this issue because we track documentation in https://github.com/reactjs/reactjs.org now.
Feel free to re-file it there! cc @keyanzhang who also asked about this.
