### ISSUE TITLE
[website] Side nav sometimes shows an incorrect "current" highlight

### ISSUE THREAD

**Issue by clemmy** [facebook/react#10888]
**Bug**:
The active navbar item is incorrect sometimes.

**Reproduction steps:**
Navigate to http://reactjs.netlify.com/docs/handling-events.html. Observe that **Synthetic Event** is highlighted.

**Expected Behavior:**
`Quick Start > Handling Events` should be highlighted.

**Comment by bvaughn** [comment]
Nice catch, @clemmy

**Comment by NicBonetto** [comment]
Hi @bvaughn, 
  I would like to tackle this issue. It would be my first time contributing to React, so I will most likely need a little direction.

**Comment by gaearon** [comment]
Check out `gatsby` branch, run `yarn` and `npm run dev` in the `www` folder, open http://localhost:8000. Try to reproduce the issue. Then try to figure out why it breaks :-)

**Comment by bvaughn** [comment]
Hi @NicBonetto,

Sounds great! I'm sure myself, @gaearon, and @flarnie will be happy to help you if you have questions.

**Comment by NicBonetto** [comment]
New PR #10951

**Comment by Engineering-Robert** [comment]
Is this issue being worked on by anyone? I just encountered it while following along with the documentation. I looked at the reference to PR #10951, but it looks like that PR isn't getting merged? I could try to tackle it if no one is currently working on it (Beginner here!).

**Comment by bvaughn** [comment]
Hey @Engineering-Robert. Thanks for asking. We've had 2 PRs submitted that fix this issue though. The 1st one just needed to be rebased before it could be merged- and it just was. 😄  There are some other [website] issues though that you might be interested in looking at!
