### ISSUE TITLE
Tutorial: text of challenge 1 is unclear

### ISSUE THREAD

**Issue by samuele-artuso** [facebook/react#10880]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
The first challenge at the end of the tutorial says `Display the move locations in the format "(1, 3)" instead of "6".`

* It suggests that we are already displaying the locations of the moves, but we are not!
* It doesn't specify where the move locations should be displayed either.

This makes the challenge unclear.

**What is the expected behavior?**
I'd change the text of the challenge to `Display the location for each move in the format (col, row) in each history link`, or something similar.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v16

**Comment by gaearon** [comment]
Filed as https://github.com/reactjs/reactjs.org/issues/238.
