### ISSUE TITLE
Rename/move docs and examples license files so Github clearly shows MIT License in top navigation bar

### ISSUE THREAD

**Issue by jonricaurte** [facebook/react#10889]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Doesn't show license on React GitHub repository because there are multiple license files for examples and docs. Keep links to the docs and examples licenses in README, but not have them be in root directory so GitHub correctly detects MIT License for  React

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

**What is the expected behavior?**
Make it even more obvious the project uses the MIT License: https://github.com/blog/2252-license-now-displayed-on-repository-overview

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16

**Comment by jonricaurte** [comment]
Maybe move the licenses to the /docs directory since the /docs directory is what the licenses are for.

**Comment by gaearon** [comment]
This is fixed now :-)
We moved docs into another repo.

**Comment by jonricaurte** [comment]
Awesome :) 👍
