### ISSUE TITLE
[website] Footer links do not reset scroll to top

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#10898]
1. Open http://reactjs.netlify.com/docs/hello-world.html
1. Scroll to the bottom and click a link in the footer (eg Resources > Conferences).
1. The new page will load but the scroll position will remain at the bottom (so it's not obvious that a new page loaded).

**Comment by hd719** [comment]
Hello @bvaughn can I work on this?

**Comment by bvaughn** [comment]
@hd719 I'm so sorry I missed this comment! I actually fixed this in response to PR feedback for #10896.

Would you like to work on another website task? There are several. I need to file some more this morning actually.

**Comment by bvaughn** [comment]
Fixed via 37cbbea

**Comment by hd719** [comment]
Hey, @bvaughn yes def!

- Thank you.

**Comment by bvaughn** [comment]
Great!

You can filter for all issues tagged with ["Component: Documentation & Website"](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Documentation+%26+Website%22) if you're looking to help with the website specifically. I'll be adding some new issues with this label today.

**Comment by hd719** [comment]
@bvaughn Sounds good.
