### ISSUE TITLE
[website] Add Flow types to website source (/www)

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#10897]
Replace `PropTypes` with Flow types for our components in `www` (and make sure `yarn flow` checks these types to protect against regressions).

**Comment by hd719** [comment]
Hey @bvaughn can I work on this? 

Also where can I find the directory `www` ? So I can replace PropTypes with Flow Types?

Thank you.

**Comment by Mathspy** [comment]
@hd719 you can find it on the [gatsby branch](https://github.com/facebook/react/tree/gatsby/www)

**Comment by bvaughn** [comment]
Hi @hd719. You're welcome to work on this, although I suggest either waiting until #10896 has been merged to `master` or branch off of `gatsby`.

I also suggest tackling this incrementally via several small, focused PRs.

**Comment by bvaughn** [comment]
This issue has been moved to the new repo, reactjs/reactjs.org/issues/24

@hd719 You are free to work on it now if you'd like!
