### ISSUE TITLE
ReactOS - please read and respond to the final request

### ISSUE THREAD

**Issue by yereverluvinunclebert** [facebook/react#10908]
https://github.com/facebook/react/issues/10849

This issue seems to have been closed without further input being noted and responded to.

I strongly suggest you read the final post and suggest a new location for discussion.

Be aware that the ReactOS project community is reaching out to you. So please don't ignore.

**Comment by gaearon** [comment]
Let's continue the discussion in the original issue.
I'll close this one but reopen that one.
