### ISSUE TITLE
[website] overlapping headers on H1s

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/react#10901]
<img width="560" alt="screen shot 2017-09-27 at 4 20 44 pm" src="https://user-images.githubusercontent.com/71047/30942447-13ec74b8-a3a0-11e7-96d5-04f83543f6cb.png">

/cc @joecritch

**Comment by KyleAMathews** [comment]
This was from http://reactjs.netlify.com/blog/2016/08/05/relay-state-of-the-state.html

It could just be that h1s weren't meant to be used in the body of posts in which case it's the markdown here that should be fixed.

**Comment by gaearon** [comment]
I think @trueadm saw something similar in "optimising performance"

**Comment by acdlite** [comment]
A bit tangential, but I kinda feel like the line-height is too large across the board. Inspecting the body text, the font-size is 18px and the line-height is 35px, or ~2x. I feel somewhere in the range of ~1.5x is typically better. Not enough fits on the screen as-is, IMO.

**Comment by joecritch** [comment]
Thank you, fixed in #10911 👍  FYI, the Relay article uses multiple `<h1>` elements. We should stick to only one of those per page, for aesthetics & accessibility.

**Comment by joecritch** [comment]
@acdlite Thanks for the suggestion! I've changed this to `1.7`. `1.5` felt too tight in this case, due to the line width. See what you think 👍

**Comment by KyleAMathews** [comment]
Thanks @joecritch!
