### ISSUE TITLE
UMD Production builds define global variables

### ISSUE THREAD

**Issue by rauhs** [facebook/react#10909]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The UMD production build linked in the announcement ( https://unpkg.com/react@16.0.0/umd/react.production.min.js ) define global variables `y` and `Nb` (react-dom). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

Use the build with an app that defined the function or variable `y`, loaded before react.

**What is the expected behavior?**

React builds should not define any other global symbols other than `React`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.0.0. It worked fine with some betas of 16.0.0.

**Comment by gaearon** [comment]
This is a bug. We should probably always wrap the UMD bundle into an IIFE.
Want to send a PR to fix it?

**Comment by rauhs** [comment]
TBH, I've never built a JS project since I'm only doing Clojurescript so I have not the slightest clue where in the build process a fix would be necessary. :/

**Comment by gaearon** [comment]
I imagine we'll want to change [this](https://github.com/facebook/react/blob/803b493314ad65be26ef9bb3a621eb65ce8b11e2/scripts/rollup/build.js#L85) to do something more like [this](https://github.com/facebook/react/blob/803b493314ad65be26ef9bb3a621eb65ce8b11e2/scripts/rollup/build.js#L91). And add a case for UMDs [here](https://github.com/facebook/react/blob/803b493314ad65be26ef9bb3a621eb65ce8b11e2/scripts/rollup/build.js#L121). Or maybe we can just unify and do this for every bundle.

**Comment by gaearon** [comment]
I sent https://github.com/facebook/react/pull/10933 to fix this but now realize it doesn't help because Rollup UMD wrapper relies on `this`.

Now that I think of it, I'd like to know which tool is responsible for the top-level variable in the first place. I would expect Rollup to keep everything inside its wrapper. Is it Uglify then? Can we add an option to preserve top-level wrapper/

**Comment by gaearon** [comment]
Apparently it's GCC's doing.

**Comment by gaearon** [comment]
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.
