### ISSUE TITLE
[website] Increase contrast for 'result' headers on homepage

### ISSUE THREAD

**Issue by flarnie** [facebook/react#10929]
**Do you want to request a *feature* or report a *bug*?**
This is an accessibility issue on [the home page of the new docsite](https://reactjs.org/).

**What is the current behavior?**

The word 'result' in the interactive code samples doesn't have enough contrast with it's background:
<img width="1150" alt="contrast_issue_on_homepage" src="https://user-images.githubusercontent.com/1114467/30983307-e9e6928a-a43e-11e7-8ea9-d25f98800c35.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

[Running an axe accessibility audit will flag this issue.](https://www.deque.com/products/axe/)

**What is the expected behavior?**
There should be no low-contrast issue. But it should also look cool. 😎

**Comment by thomasyimgit** [comment]
I'm looking into this issue right now. Thanks so much for your instruction! @flarnie

**Comment by thomasyimgit** [comment]
I'm sorry, could you please tell me how can I set up my local environment? First time contributing React.

**Comment by flarnie** [comment]
Hi @thomasyimgit! Glad to have your help.

First you will need to fork the React repo, and then clone your fork. After you `npm install && npm run build` in the main directory, you should be able to [follow the directions in the `www/README.md`](https://github.com/facebook/react/blob/master/www/README.md).

For more context and instruction [the contributor's guide](https://facebook.github.io/react/contributing/how-to-contribute.html#your-first-pull-request) may be helpful.

**Comment by thomasyimgit** [comment]
Hi @flarnie, this issue has been solved and the pr has been merged. Thank you and I should let you know that this means a lot to me as my first time contributing. I'll start to do more in the future. Thank you.

**Comment by flarnie** [comment]
Glad to have your help @thomasyimgit! We look forward to your next PR. :)
