### ISSUE TITLE
[website] Add twitter timeline support to docs

### ISSUE THREAD

**Issue by flarnie** [facebook/react#10924]
**Do you want to request a *feature* or report a *bug*?**
This is a bug in the docs introduced by our migration to gatsby.

**What is the current behavior?**
There is an empty link on the ['Community > Where to get support' page](https://reactjs.org/community/support.html#facebook-and-twitter) at the very bottom. In the past, a twitter timeline was rendered there.

**What is the expected behavior?**

You should see a twitter timeline - see old version:
<img width="1070" alt="screenshot_with_old_twitter_timeline_highlighted" src="https://user-images.githubusercontent.com/1114467/30980356-a8b2ddd6-a435-11e7-8073-490a05bee0eb.png">

It looks like [a script was added in this PR](https://github.com/facebook/react/pull/68/files) and now that script isn't being loaded. I think that [adding the gatsby twitter plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-twitter/) would fix this, and if not we probably just need to tweak the gatsby twitter plugin.

**Comment by thomasyimgit** [comment]
Can I get started to tackle this issue? First time contributing React and I will try my best.

**Comment by flarnie** [comment]
Wow - sorry about that, it looks like someone already fixed it around the time I opened this issue. Thanks anyway for volunteering @thomasyimgit!
