### ISSUE TITLE
Is it okay to use ReactDom.hydrate always

### ISSUE THREAD

**Issue by arunoda** [facebook/react#10934]
This is regarding the the use of hydrate in Next.js.
We use the same render code base to render the initial SSR'ed version and client side generated renders. (When a user clicked on a link)

So, here's my question. Is it okay to use `ReactDom.hydrate()` in all cases. 
> Here we assume, it'll fallback to `ReactDom.render()` if it cannot hydrate.

But I was not sure of this. So, I have a solution for this. (See: https://github.com/zeit/next.js/pull/3012)

Is it makes sense to do the above check(in the PR)?

**Comment by gaearon** [comment]
I think it would make sense to do the check. We mostly did this to always make the intention explicit. Some people *mean* to hydrate (and then get surprised if they do it in a wrong place, and hydration didn't work). Others *mean* to clear and render, and would be surprised if hydration happened. Explicit API helps make it always clear what's expected to happen, and your case seems a bit unusual to me.

**Comment by arunoda** [comment]
Okay. I'll use the check.
Thanks.
