### ISSUE TITLE
After our mobile web upgrade to React 16.0.x, our automation input box sendkeys got failure on iOS simulator

### ISSUE THREAD

**Issue by charlesh21** [facebook/react#10930]
Protractor: 3.0.0

selenium-webdriver: 3.5.0

Test device: Saucelabs iPhone simulator iOS 10.0

Mobile web build by React 10.6.x

Our mobile web has input box which build React controlled input, after we upgrade the React from 10.5.x to 10.6.x

Our automation test got failure when we submit the input box value to our backend.

We used the saucelabs to execute our automatino testing. On the saucelabs recording video, we can see the input has value be presented.

We used webdriver sendkeys function to insert value to the input box element. Then click the submit button. We check our backend log, the input box value is empty.

I try to manual the simulator on saucelabs, use the soft keyboard to type the value and click submit. it works.

I also try use the Android emulator to run the same test, it works too. It seems the sendkeys function didn't trigger the React properly event. so the React component think the input value didn't be changed.

I saw the React changelog and noticed the upgrade include some input improvment.

https://facebook.github.io/react/blog/2017/06/13/react-v15.6.0.html

Does anyone face the same issue and know hope to fix or some workaround.

Thanks, Charles

**Comment by gaearon** [comment]
>Our mobile web has input box which build React controlled input, after we upgrade the React from 10.5.x to 10.6.x

Did you mean 15.5.x? Then it's probably the same issue as https://github.com/facebook/react/issues/10687, and affects 15.6.x as well.

**Comment by charlesh21** [comment]
Hi @gaearon ,
Thank you to provide the same issue reference for me. Glad to hear we are not only one to have this issue.

Our test ran on React 15.5.x is pass, but after upgrade to 15.6.x is fail.
We also try to build with the React 16.x, it still not work.

Thanks,
Charles

**Comment by gaearon** [comment]
I'm going to assume this is the same issue as https://github.com/facebook/react/issues/10687, so I'm closing this one.
