### ISSUE TITLE
Reactjs generating pdf using phpwkhtmltopdf 

### ISSUE THREAD

**Issue by srivi1225** [facebook/react#10937]
Hi ,

I am new to reactJs. i created a component to generate a report and i am pulling it as node module to my php application there i created a smarty template(.tpl) in that i am using the main.version.js, main.version.css files in the build and passing the required data to the component by data attributes  and i am able to view the report. now the problem is i have to generate a pdf when we click print hyper link from the browser. for this we are using wkhtmltopdf converter using which we are able to merge different pdfs and generating a single pdf. here i am getting a blank page. if i give some text that is working fine but not working for the react component content. It is failing for this react component. Please guide me in the right direction.
```
<html>
<head>
    <link href="{$baseUrl}node_modules/react-component-report/build/main.xxx.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <div id="root" data-title="Hello" data-name="World" data-reportcontent='{literal}{"users": [11,5],"dates": "2017-09-17" }{/literal}'></div>
    <script src="{$baseUrl}node_modules/react-component-report/build/main.xxx.js"></script>
</body>
</html>

**Comment by aweary** [comment]
Hey, @srivi1225! Welcome to the React community, I hope you're enjoying it so far! We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).

Thanks!
