### ISSUE TITLE
How to add React Summit Nigeria to the conferences list

### ISSUE THREAD

**Issue by kingisaac95** [facebook/react#10932]
The Facebook Developers Circle in Lagos Nigeria is organizing a React summit here in Nigeria and we'd love to know how our event can be added to the list [here](https://facebook.github.io/react/community/conferences.html) ie. [here](https://github.com/facebook/react/blob/master/docs/community/conferences.md)

Any guideline to this regard would be appreciated.

**Comment by gaearon** [comment]
Hi! Is this a conference or a meetup? We generally reserve the page for conferences only.
You can edit the page here:

https://github.com/facebook/react/blob/master/docs/community/conferences.md

**Comment by kingisaac95** [comment]
It's a React Conference @gaearon 
Here's the event page: https://reactsummit2017.splashthat.com/
We're working on a website where we will be managing other conferences

Does it qualify?

**Comment by kingisaac95** [comment]
Also please is there any particular branch I should raise the PR against before it's merged @gaearon ?

**Comment by gaearon** [comment]
Master is fine, thanks!

**Comment by kingisaac95** [comment]
Here's the PR for that @gaearon: https://github.com/facebook/react/pull/10939

**Comment by kingisaac95** [comment]
Thanks for merging the PR @gaearon 
But please, I do not see the conference in the list here: https://facebook.github.io/react/community/conferences.html
Any reasons why?

**Comment by kingisaac95** [comment]
@gaearon can you look at this for a sec please?
The event I added still does not appear here: https://facebook.github.io/react/community/conferences.html

**Comment by gaearon** [comment]
Sorry, we're in the middle of moving to a new website that will hopefully be deployed today. It is already there: https://reactjs.org/community/conferences.html#second-react-summit---ng-2017

**Comment by kingisaac95** [comment]
Thanks a lot @gaearon I was looking for it in the old website.
