### ISSUE TITLE
correct way to return custom components for renderer?

### ISSUE THREAD

**Issue by dakom** [facebook/react#10949]
So I have the renderer _basically_ working. woooo!

But the way I'm creating the components doesn't seem to be the way it's done in the current examples

What I have is basically just `export const MyComponent = (props) => React.createElement('name', props)` and then in the renderer's `createInstance`, it returns non-react objects.

Is that correct?

Seems to work with basic tree updates so far - e.g. going from:

`<parent> <child attr="foo" /> <parent>` to `<parent> <child attr="bar" /></parent>` to `<parent><somethingElse attr="baz" /></parent>`

But I just wanted to make sure this is right

**Comment by dakom** [comment]
for the sake of clarity, what I'm actually doing is really this:

```
const c = name => props => React.createElement(name, props);

export const Foo = c('foo);
export const Bar = c('bar');
export const Baz = c('baz');
```

**Comment by alexkrolick** [comment]
A couple points:

```jsx
<MyComponent aProp={'a prop'} />
```

is equivalent to:

```js
React.createElement(MyComponent, { aProp: 'a prop' })
```

Note that you should be passing the component class or function reference, not a string. The only strings you can pass to `createElement` are DOM elements like 'div', 'b', etc. It's also _required_ to capitalize the function names (Foo not foo) if you are using JSX.

**Comment by dakom** [comment]
Thanks Alex! I guess we'll continue this discussion here rather than discord :)

I believe with a custom renderer, you can pass any string you like into `React.createElement()`, as long as it's supported by the renderer's `createInstance()` function. 

Additionally, I was unable to get any other approach to work - the only way I could get it to work was specifically by doing that. In other words - bypassing the custom renderers internal type lookup thing in `createInstance` and rather supplying a function that returns a non-dom type of object, did not work for me. Adding these non-dom type of objects and using createElement('foo') worked fine.

From a knee-jerk perspective, this makes sense, since React must somehow turn that plain object into a proper element, but I'm still not 100% clear on the exact pipeline and if it can happen outside of the renderer or happen more generically. 

Specifically, given an object that satisfies all the methods a renderer expects from it (e.g. to call appendChild/removeChild, etc. as needed) - is it possible to bypass the renderer's internal `createInstance` thing and simply supply a function that returns this sort of object to `React.createElement`?

**Comment by dakom** [comment]
IF this limitation is correct - that custom renderers with custom elements _require_ going through the key/string lookup - then my original question is more just about best practices for exposing that to the end user :)

I think that comes down to two options
1. Documentation (telling them the available strings for `React.createElement` and they roll their own components)
2. Exporting those components as simple helpers so they can just use JSX straight after import.

**Comment by dakom** [comment]
Leaving this issue open might be confusing since I got some stuff wrong... and now that I'm going deeper it seems like it really varies by use-case. 

Closing for now

Thanks for your help @alexkrolick

**Comment by gaearon** [comment]
>I believe with a custom renderer, you can pass any string you like into React.createElement(), as long as it's supported by the renderer's createInstance() function.

Yes.

> is it possible to bypass the renderer's internal createInstance thing and simply supply a function that returns this sort of object to React.createElement?

No. Element is just a description. React reconciles descriptions and decides whether to create, append, update, or remove instances.

>I think that comes down to two options

Both options are reasonable. I would probably just go with documenting supported "tags" and throwing for unsupported ones.
