### ISSUE TITLE
after upgraded v16, using units without px shows no warnings like v15

### ISSUE THREAD

**Issue by webmobiles** [facebook/react#10947]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
'div style width' in my component  is not changing accord to input like in the version 15,  now in the versions 16 has no effects if i don't add 'px' to the value.

I'd like to have  a warning like in  version 15. I took time to realize that in react 16 needed add the unites when i change css on the fly, by example with states and inputs:

message in react v15
`Warning: .. was passed a numeric string value for CSS property... which will be treated as a unitless number in a future version of React.`

* No warnings in react v15, simply div dont' change to the new width

code:
```
import  React, { Component } from 'react';

export default class TestColors extends Component {
  constructor(props){
    super(props);
    this.handleInputChange = this.handleInputChange.bind(this);
    this.state = {
      width: 300,
    };
  }
  handleInputChange(event) {

    let newvalue= event.target.value;
    this.setState((prevState, props) => ({
      width: newvalue,
    }));
  }

  render() {
    const style = {
      backgroundColor: 'orange',
      width: this.state.width,
    };

    return (
      <div style={style}>
        <input onChange={this.handleInputChange} /> {this.state.width}
     
      </div>
    );
  }
}


```

**Comment by Kovensky** [comment]
The problem is not that it's a number, the problem is that it's a string. Use `parseInt(event.target.value, 10)` to ensure it stays as a number.

**Comment by webmobiles** [comment]
yes, I mean, it's would be nice a warning in Reac 16 ? when it's a string without 'px', if i don't add 'px' same like string, the width don't change

**Comment by gaearon** [comment]
My understanding is that the warning in 15 was because the behavior would change, and now it has changed so the warning is unnecessary.

I don’t have the context into why the change was made, perhaps @sophiebits can tell.

**Comment by webmobiles** [comment]
thanks, have sens now don't keep old warnings,   thanks Dan ! react 16 is running twice or three faster !

**Comment by sophiebits** [comment]
That's right. I think we just thought it would be very surprising for React to add px or not depending on whether a string's contents looks like a number.
