### ISSUE TITLE
React devtools update highlight screenshots between 15 and 16 

### ISSUE THREAD

**Issue by suhaotian** [facebook/react#10948]
## React 15.6.2
![15](https://user-images.githubusercontent.com/6512574/30997517-f7170702-a4fa-11e7-9aed-343ea6c3d98d.png)

## React 16.0.0
![16](https://user-images.githubusercontent.com/6512574/30997521-f959608c-a4fa-11e7-8d31-0d955690f6ed.png)

**Comment by suhaotian** [comment]
I just want to say: React 16 is awesome

**Comment by gaearon** [comment]
Yes, it works now 😄
