### ISSUE TITLE
[website] maintain scroll position of mobile menus

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/react#10952]
When going quickly through pages on mobile, it'd be really nice if as you scroll down long menus e.g. in docs, if after navigating to the next page and then returning to the menu if the previous scroll position is maintained/restored.

This could be done by a) rendering the menu in the layout component which isnt unmounted on page changes or by storing the menu scroll position in the layout again and then passing it into the page component on render.

**Comment by bvaughn** [comment]
> rendering the menu in the layout component which isnt unmounted on page changes

Pages currently inject params into the nav menu.

> or by storing the menu scroll position in the layout again and then passing it into the page component on render

Sounds more promising.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#19

Let's continue the discussion there! Sorry for the inconvenience.
