### ISSUE TITLE
react-router not work with React 16.0.0

### ISSUE THREAD

**Issue by threescales** [facebook/react#10956]
![image](https://user-images.githubusercontent.com/15061441/31003106-77fed2c0-a4b3-11e7-8c1a-6079115c95ec.png)

react-v16.0.0
react-router-v1.0.2
It's baseRouters.js

![image](https://user-images.githubusercontent.com/15061441/31003201-f292977e-a4b3-11e7-8e20-d44d5be8228c.png)

**Comment by ptomasroos** [comment]
How about reporting that inside the react-router repo instead @threescales  ?

**Comment by threescales** [comment]
Ithink you are right.

**Comment by threescales** [comment]
I think you are right.@ptomasroos ,but I think it's cause by react-v16 can render array.

**Comment by gaearon** [comment]
React Router 1.0.2 does not support React 16. Please use a more recent version. I think both RR3 and RR4 support it.

**Comment by threescales** [comment]
@gaearon thx .Let me try.
