### ISSUE TITLE
IE10 react-dom exist Error

### ISSUE THREAD

**Issue by zenjava** [facebook/react#10958]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 16.0.0
react-dom 16.0.0
react-dom.development.js line 8440
 ```
// During commits, we only show a measurement once per method name
  // to avoid stretch the commit phase with measurement overhead.
  var labelsInCurrentCommit = new Set();  //<--- In ie10 ,it is undefined.

  var formatMarkName = function (markName) {
    return reactEmoji + ' ' + markName;
  };

  var formatLabel = function (label, warning) {
    var prefix = warning ? warningEmoji + ' ' : reactEmoji + ' ';
    var suffix = warning ? ' Warning: ' + warning : '';
    return '' + prefix + label + suffix;
  };

  var beginMark = function (markName) {
    performance.mark(formatMarkName(markName));
  };

  var clearMark = function (markName) {
    performance.clearMarks(formatMarkName(markName));
  };
```
In ie10, Set is undefined.

**Comment by suhaotian** [comment]
Please read this [react 16 blog post](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html#javascript-environment-requirements)

```js
import 'core-js/es6/map';
import 'core-js/es6/set';

import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('root')
);
```

**Comment by dkaus1** [comment]
Can you please tell me the solution to this issue ? I am getting the same error while running the app on IE 10 while it running perfectly fine with IE 11 and above. React version 16 we are using in our application. Prompt response will be really appreciated.

**Comment by gaearon** [comment]
When you update a major version, we encourage you to read the release notes. Otherwise you won't know which other things have broken. :-)

The release notes for 16 point out the new baseline which we are targeting. We also have a dedicated page that mentions it:

https://reactjs.org/docs/javascript-environment-requirements.html

Hope it helps!

**Comment by dkaus1** [comment]
Thanks Dan, But I have already included babel-polyfill  version 6.26.0  to my react code.  Still the issue persists.

**Comment by gaearon** [comment]
You probably included it after ReactDOM loads rather than before. It should go before any other code in your app entry point.

**Comment by dkaus1** [comment]
It worked !! Thanks for prompt response .
