### ISSUE TITLE
[website] docsearch improvements

### ISSUE THREAD

**Issue by Haroenv** [facebook/react#10965]
**What is the current behavior?**

the docsearch on the new page changed its design, but two features are different than in the previous version: 

- the "cursor" no longer has a separate colour (visible when you use the arrow keys to select a result)
- there no longer is an Algolia logo / mention

**What is the expected behavior?**

- A slightly different background colour for the cursor
- A mention of "search by Algolia" or our logo, as which is required because it's a free plan. 

Happy to open a PR for both of those issues, with whatever colour / solution we choose

cc @bvaughn and @gaearon

**Comment by bvaughn** [comment]
Hey @Haroenv,

Thanks for bringing this to our attention! We'd be happy to accept your help with these issues!

cc @joecritch for cursor color suggestions
