### ISSUE TITLE
ReactDOM 16 createPortal not the same behavior as renderSubtreeIntoContainer

### ISSUE THREAD

**Issue by xelaz** [facebook/react#10960]
**Do you want to request a *feature* or report a *bug*?**
I don't know if this is a bug or feature, because with last function *ReactDOM.unstable_renderSubtreeIntoContainer* it works like if you reading html code but with the new feature *ReactDOM.createPortal* it is not the same behavior.
Bud it may be, that i not understand the new feature create portal.

**minimal demo of the problem**
[Demo with ReactDOM.createPortal](https://jsfiddle.net/kogexuok/2/)
[Demo with ReactDOM.unstable_renderSubtreeIntoContainer](https://jsfiddle.net/3851keez/1/)

```jsx
class Container extends React.Component
{
  constructor(props) {
    super(props);
    this.state = {
      show: false
    }
  }
  
  _show() {
    console.log('SHOW');
    this.setState({show: true});
  }
  
  _close() {
    console.log('CLOSE');
    this.setState({show: false});
  }
  
  render() {
    const {show} = this.state;
    
    return (
      <div style={{background: 'red'}} onClick={this._show.bind(this)}>
        <div>Click me to show the Portal content</div>
        <div>State: {show && 'visible' || 'hidden'}</div>
        {show && <Portal>
          <div style={{background: 'green'}}>
            <button onClick={this._close.bind(this)}>&times; close portal</button>
          </div>
        </Portal>}
      </div>
    )
  }
}

class Portal extends React.Component
{
  constructor(props) {
    super(props);
    this.node = document.createElement('div');
    document.body.appendChild(this.node);
  }
  
  render() {
    return ReactDOM.createPortal(this.props.children, this.node);
  }
}

ReactDOM.render(<Container />, document.getElementById('body'));
```

*Rendered SourceCode:*
```html
<div id="body">
  <div style="background: red;">
    <div>Click me to show the Portal content</div>
    <div>State: visible</div>
  </div>
</div>
<div>
  <div style="background: green;"><button>× close portal</button></div>
</div>
```

**What is the expected behavior?**
Portal render content in to the body but if i want close the Portal and i click on close button, then i trigger the show action again. Is this a problem in ShadowDOM? Because in Rendered HTML the  Container and Portal are separate and close portal is not child of container.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
* React 16.0.0
* ReactDOM 16.0.0
* Chrome Version 61.0.3163.100

**Comment by gaearon** [comment]
Here's a fixed version: https://jsfiddle.net/ncjs5n2m/

I made two fixes:

* `e.stopPropagation()` in `_close()` so it doesn't trigger `_show()` ([events bubble through portals](https://facebook.github.io/react/docs/portals.html#event-bubbling-through-portals)).

* Added `componentWillUnmount()` that removes `this.node` so that you don’t end up with an extra empty node each time you close the portal.

**Comment by xelaz** [comment]
Nice, i have seen this (events bubble through portals) but it was to late yesterday! :(

THX!

**Comment by goldhand** [comment]
I noticed that I can do `unmountComponentAtNode(this.node)` before I remove `this.node` in `componentWillUnmount()`. Is there any advantage to doing this?
