### ISSUE TITLE
React.org enable tab out of Live JSX Editor 

### ISSUE THREAD

**Issue by normanbrobinson** [facebook/react#10976]
The current React.org default behavior is that keyboard users will get to the code sections of the live editor and get stuck.

Can someone configure ignoreTabKey which makes the editor ignore tab key presses so that keyboard users can tab past the editor without getting stuck?

Chrome on Windows atm and cannot edit it to submit a fix. Sorry about that :(

**Comment by bvaughn** [comment]
Thanks for bringing this to our attention 👍
