### ISSUE TITLE
RSS feed 404

### ISSUE THREAD

**Issue by acdlite** [facebook/react#10978]
https://reactjs.org/feed.xml is a 404. Did we intentionally drop this? I assume not.

Reported on Twitter https://twitter.com/rcdii/status/913873923447644162

**Comment by KyleAMathews** [comment]
https://www.gatsbyjs.org/packages/gatsby-plugin-feed/

**Comment by fpoumian** [comment]
Is anyone already working on this? If not, I'd be glad to give it a shot. I've been recently working on a Gatsby personal project so I think I can integrate that plugin.

**Comment by bvaughn** [comment]
> Did we intentionally drop this? I assume not.

I was totally unaware of this until now.

**Comment by bvaughn** [comment]
Fixed via #11056
