### ISSUE TITLE
[website] Buttons in Live Code sections have bad styling

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#10986]
On the new site, the button in the "todo" example looks strange (non-standard):
![](http://ss.dan.cx/2017/09/chrome_30-20.14.50.png)

Generally this happens when border styling is overridden and no nice styling is applied to the button. This appears to be the case here. Removing `border-color: inherit` fixes the styling:
![](http://ss.dan.cx/2017/09/chrome_30-20.17.29.png)

![](http://ss.dan.cx/2017/09/chrome_30-20.15.35.png)

**Comment by hd719** [comment]
Hey can I work on this?

**Comment by romellogood** [comment]
Created #11009 to fix this

**Comment by romellogood** [comment]
This can be closed now @Daniel15

**Comment by Daniel15** [comment]
Thank you :)
