### ISSUE TITLE
[website] Upon scroll active item in side navigation remains the same

### ISSUE THREAD

**Issue by vicodinchik** [facebook/react#10984]
I would call it a bug, if you click on side-nav items, page goes to its part of the page and side-nav item get an active state correctly (with 4px blue span in front of the link text), but if you scroll manually to those parts, side-nav doesn't refresh the active state of items.

Tested in all browsers on MacOS.

You can see it on a screenshot, **An Interactive Component** should be active.
![](https://i.imgur.com/zooCABr.png)

**Comment by bvaughn** [comment]
Not really a bug so much as an incomplete feature. (The sidenav is passive rather than active.) Would be nice to fix though, and it's on our follow-up list. Just hadn't been converted from the wiki to a GitHub issue yet. 😁

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#21

Let's continue the discussion there! Sorry for the inconvenience.
