### ISSUE TITLE
Link to download html File is not working on this page

### ISSUE THREAD

**Issue by dbnex14** [facebook/react#10994]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?** THE LINK TO DOWNLOAD FILE IS NOT DOWNLOADING ANYTHING

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
CLICK ON THE LINK ON THIS PAGE TO DOWNLOAD THE HTML FILE, IT WILL NOT DOWNLOAD IT.  ON MAC AND CHROME BROWSER, WHEN I CLICK ON LINK, IT DOWNLOADS SOMETHING AND IT SAYS "NO FILE" AND I CANNOT OPEN IT.  IT APPEARS LIKE NOTHING IS DOWNLOADED.

**What is the expected behavior?** YOU SHOULD BE ABLE TO DOWNLOAD THIS HTML FILE

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**  MAC OS ON CHROME, VERSION OF REACT IS IRRELEVANT AS I CANNOT OPEN THE FILE.  BUT MY VERSION IS 16.0.0-beta.2

**Comment by gaearon** [comment]
This is referring to HTML link on https://reactjs.org/docs/installation.html.

We broke it on the new website.

Need to fix asap.

**Comment by gaearon** [comment]
I pushed a temporary fix in https://github.com/facebook/react/commit/c8af9c46459f4feea92c0a37bc240d6f8c8a92f0.

The file is here:

https://raw.githubusercontent.com/facebook/react/master/docs/downloads/single-file-example.html

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#23

Let's continue the discussion there! Sorry for the inconvenience.
