### ISSUE TITLE
[website] Restructure docs to provide "paths" for guidance?

### ISSUE THREAD

**Issue by markerikson** [facebook/react#10991]
Per Dan's recent comments at https://news.ycombinator.com/item?id=15367044 and https://twitter.com/dan_abramov/status/913896989842137091 , a lot of people still seem to have complaints about the way the docs are structured.  

It might be worth trying to restructure the docs kind of like a "Choose Your Own Adventure" book, with different "paths" based on what you know so far and what you want to accomplish (suggestions for reference: https://twitter.com/autiomaa/status/913908358662574083 , https://twitter.com/trevorbrindlejs/status/913907697602433025 ).

Hypothetical paths example:

> What are you looking for?

> - I want to see if I'm ready to learn React - what should I know first?
>   - *links to a page discussing common JS prerequisite knowledge*
> - I want to try out React right now , without installing anything:
>    - *links to a page that points to CodePen, CodeSandbox, and StackBlitz for online playgrounds, and also gives a copy-paste HTML snippet with links to CDN libs that the user can save and edit locally*
> - I want to learn the basic ideas of React, with nothing "new" involved
>    - *links to a page that describes components and rendering, with ES5 syntax, without using JSX*
> - I want to learn the recommended way to use React
>   - *links to a page that talks about Create-React-App, ES6+, and JSX syntax*
> - I understand the basics - how do I learn to "think in React" as I build something?
>   - *probably links to the current tutorial section*
> - I'm trying to build an application - how do I solve "real-world" problems with React?
>    - *links to a page that addresses topics like routing, state management, etc, like the guides discussed in #8060*
> - I'm looking for advanced React usage patterns that can help me reuse code better
>    - *links to a page that covers topics like HOCs, render props, context, etc*

Another related idea would be if the code samples in the docs all had multiple syntax variations that could be viewed by switching tabs or a global option across the site, like "Plain ES5 Syntax" / "ES6 and JSX Syntax" / "ES6+ Syntax".

**Comment by drcmda** [comment]
@markerikson would it not be better to simply provide tabs or markers above the code boxes for variants? Latest drafts, Current ES, ES5, script-tags. It wouldn't be a complete overhaul, also nice to see the differences. Perhaps with an explanation on top that React adapts to our preferences, and to the language itself, and doesn't so much dictate how we write code - which is a strength that i feel like doesn't get much exposure.

![react](https://user-images.githubusercontent.com/2223602/31049109-7e7feaec-a62c-11e7-9913-0bb3c60695d2.jpg)

**Comment by markerikson** [comment]
@drcmda : the "tabs" thing is what my last comment was suggesting in regards to code samples, yes.

However, I think the overall flow of the docs needs to be more guided in terms of what the user is trying to accomplish and what their current experience level is.

**Comment by alexkrolick** [comment]
> Another related idea would be if the code samples in the docs all had multiple syntax variations that could be viewed by switching tabs or a global option across the site, like "Plain ES5 Syntax" / "ES6 and JSX Syntax" / "ES6+ Syntax".

IMO this is such a a good idea it should be its own issue.

**Comment by drcmda** [comment]
@markerikson The pages i've liked most and that i haven't forgotten are the ones that present the information i want and need in a clear and unobstructed manner. The current react docs for instance are quite close. The four code boxes on the front page almost teach React, how amazing is that!

But due to javascripts fragmented nature they're doing it in a way that stretches these examples in ways that either seem verbose or unfamiliar. I guess i'd expect the frontpage to present React in the leanest most efficient way possible. Then allow us to see how we could screw it up with binding hacks and script tags. The path thing would pretty much obscure again.

**Comment by markerikson** [comment]
@drcmda : I'm not saying put all this information itself on the front page.

Right now, the front page has top-level menu items for "Docs" and "Tutorial", and the center of the page has links for "Get Started" (which is the same link as "Docs") and "Tutorial".

The "Docs" link leads to a "Hello World" page, which is part of a "Getting Started" guide.  The nav section on the right has several entries for the "Getting Started" section.  

From that, a few thoughts and observations:

- The "Advanced Guides" and "Reference" sections in the right nav start out collapsed, and there's no indication of what's inside of them.
- What's the difference between "Get Started" and "Tutorial"?  Why do these sections overlap so much?
- The actual API docs are sort of buried in that "Reference" nav sub-section
- The bottom of the "Hello World" page mentions the examples do use ES6 syntax, and points to MDN
- There isn't a real clear flow or guidance for what order to read things, other than just going down the list of sections in the docs nav sidebar.

Per Dan's tweets and the HN thread, people have many different expectations for what the docs should cover.  They should somehow simultaneously show how to use React with just a drop-in script tag and ES5, and also show how to use the latest-and-greatest not-yet-final ES+++ syntax.  They should cover a whole bunch of Javascript basics, and also tell you how to build complete applications using libraries and tools that aren't even a part of React itself.

So, what I'm suggesting is that the docs should be structured in a way that gives the reader some more direction.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#22

Let's continue the discussion there! Sorry for the inconvenience.
