### ISSUE TITLE
[website] Online IDE in the documentation

### ISSUE THREAD

**Issue by CompuIves** [facebook/react#10996]
Continuing the conversation on Twitter here: https://twitter.com/acemarke/status/913891217385168896.

I think it would be very beneficial for beginners to use CodeSandbox/Stackblitz/WebpackBin to start learning React. The environment is like a local code editor, which means that the user already gets familiar with the feel of a code editor. The user doesn't have to install any tooling, so you can start immediately. Also, whenever they want to continue offline they can easily click on 'Download'/'Export' to get a CRA version of the same application so they can work further on it.

I think we all agree that this would be beneficial, the question is how to approach this without confusing the user. Would be great to have a discussion on this here.

**Comment by bvaughn** [comment]
Hey @CompuIves. Thank you for filing this issue! 😄  Love the idea.

The documentation and source code for reactjs.org now lives in a different repository: https://github.com/reactjs/reactjs.org

Would you please open a new issue in that repository for discussion? Sorry for the inconvenience!
