### ISSUE TITLE
Question on build-scripts sources

### ISSUE THREAD

**Issue by haraldrudell** [facebook/react#11005]
The build scripts tirelessly typed up by fb, do they exist in fancy 2017 versions somewhere with import statements, object rest spread and for await that has then been lightly transpiled, or are they actually typed in using the unpleasant quasi-2015 ECMAScript that offers direct untranspiled execution by a recent Node.js?

Here’s a very nice one: https://github.com/facebook/react/blob/master/scripts/rollup/build.js
I did search for some unique wordings in that one without finding anything

**Comment by bvaughn** [comment]
They exist only in the form you see 😄  There are no fancy 2017 versions.

**Comment by haraldrudell** [comment]
Hey you,

Here’s what @facebook should be using:

https://github.com/haraldrudell/ECMAScript2049/tree/master/packages/es2049scripts

It’s my stuffs that on-the-fly transpiles build scripts right when you issue a scripts command. I spent five years doing everything that ended up in the wrong. That there on github is best evidence as of 2018.

That’s what I have been using for all these years. Baffling that Facebook no have something like that.

I never met any of you but I got my nose on this site so often I recognize you by the avatar…

**Comment by haraldrudell** [comment]
I noticed React went to Node.js 8 in order to avoid transpiling the build scripts (one of the actions I suggested to Facebook instead of regretting the use of Node-6 code for 18 months)

I have been doing Node.js 8 transpilation for 4 months for command-line utilities, and what I want to point out to Facebook is that when transpiling from **ES.Next** to **Node 8**, it practically looks like the source code, and can be easily debugged in production without source maps. This method allows you to take properly structured code (aka classes to Java people like me) into convenient single-file executables (native modules need not apply.)

**Triple-Transpile is awesome**

I just rewrote the **Zero Transpiler** to **ECMAScript ES.Next** from bash which is
published: https://github.com/haraldrudell/ECMAScript2049/tree/master/workspace/packages/es2049scripts/transpilezero
documented: https://github.com/haraldrudell/ECMAScript2049/tree/master/workspace/packages/es2049scripts#internal-triple-transpile

This is so freckin great I can use it as the only transpilation for simple packages

I petition Facebook to appropriate this idea and use it everywhere, benefiting from the insane amount of time I spent figuring this out.
