### ISSUE TITLE
v16 announcement page is broken with adblocker

### ISSUE THREAD

**Issue by ido-ofir** [facebook/react#11008]
v16 announcement page is broken ( using Chrome on a mac )

![image](https://user-images.githubusercontent.com/6238323/31054540-3919317a-a6bd-11e7-8612-999538b98900.png)

**Comment by gaearon** [comment]
Can you try in an Incognito window? Maybe some caching issue.

**Comment by ido-ofir** [comment]
Yup, works in Incognito window.
but not in a normal window, even if I clear cache and hard reload..

**Comment by ohana54** [comment]
Maybe a chrome extension is messing with it?

**Comment by ido-ofir** [comment]
Yes, looks like [Fair AdBlocker](https://www.standsapp.org/) is causing this. loads fine if I disable it.

**Comment by gaearon** [comment]
We should just add some error boundaries nudging people to whitelist the site in adblockers.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄 

However the documentation and source code for reactjs.org lives in a different repository: https://github.com/reactjs/reactjs.org

I've made sure to mention this specific issue in the new repo, via reactjs/reactjs.org/issues/9
