### ISSUE TITLE
Warn about unexpected HTML inside SVG

### ISSUE THREAD

**Issue by caub** [facebook/react#11013]
react and react-dom versions: 16.0.0

```js
const { createElement: h } = require('react');
const { renderToStaticMarkup } = require('react-dom-server');

renderToStaticMarkup(h('div', null, h('svg', null, h('span')))) 
// '<div><svg><span></span></svg></div>'
```

But they shouldn't be mixed:

in browser console:

```js
new Range().createContextualFragment('<div><svg><span></span></svg></div>')
// "<div><svg></svg><span></span></div>"
```
I guess it's programmer responsibility to avoid that case? I understand that for performance you don't check this

**Comment by gaearon** [comment]
Maybe we could warn for this. We do have some warnings about invalid nesting (e.g. `<p>` inside another `<p>`).

**Comment by sdsmall** [comment]
I'm going to tackle this

**Comment by alex-saunders** [comment]
@aweary do you know if this is being actively worked on? Looks like it could be good first issue for me to get my teeth into if not?

**Comment by gaearon** [comment]
It's not being worked on. Sure!

**Comment by alex-saunders** [comment]
Cheers @gaearon , I'm on it!

Are you able to point me in the right direction (files I should be looking, error logging functions React uses etc.)? no problem if not, I'll have a look around 🙂

**Comment by gaearon** [comment]
`validateDOMNesting` is probably relevant

**Comment by dmccown1500** [comment]
@alex-saunders any progress on this? Happy to try to take over if you would like

**Comment by alex-saunders** [comment]
Hey @dmccown1500 , I opened a PR to fix this issue: https://github.com/facebook/react/pull/13516 but it's been stagnating for a little while, not sure what's going on with it.
