### ISSUE TITLE
Old fiddles are broken after the new domain/website

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11018]
http://fb.me/react-js-fiddle-integration.js no longer works, and this causes all old fiddles like http://jsfiddle.net/haa2euy9/1/ to break. We should fix it.

**Comment by GunnarSturla** [comment]
I've also noticed fiddles[1][2] linking to https://facebook.github.io/react/js/jsfiddle-integration-babel.js being broken. I assume they were/are linking to the same place, but it's something to keep in mind.

[1] https://jsfiddle.net/reactjs/69z2wepo/
[2] http://recharts.org/#/en-US/examples (All the examples seem to be broken)

**Comment by gaearon** [comment]
It will take a few minutes to deploy the site but hopefully this should be fixed now.

**Comment by gaearon** [comment]
Unfortunately Recharts examples are broken because they don't specify the React version. So they accidentally "updated" to React 16 that has different file names.

We could potentially fix this on our side by providing a fallback. But then, one of the most commonly used builds (`react-with-addons`) doesn't even exist anymore. So this has to be fixed on their side anyway.
