### ISSUE TITLE
Deprecate and remove TestUtils.mockComponent

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11019]
It is a Jest-ism that shouldn't be in our open source package.
People using Jest can implement a similar pattern directly.

**Comment by bvaughn** [comment]
Moved to reactjs/reactjs.org/issues/15

**Comment by gaearon** [comment]
Test Utils, not documentation 😛 
Sorry the colors were the same.

**Comment by bvaughn** [comment]
Oh whoops! My apologies.

**Comment by chrisdieckhaus** [comment]
Does this issue still need to be taken care of? If so, I'll take a stab at it.
