### ISSUE TITLE
[Feature request] Disable the "unrecognized tag" warning in React 16 but only for specific tags.

### ISSUE THREAD

**Issue by ChrisRast** [facebook/react#11023]
**Do you want to request a *feature* or report a *bug*?**
*Feature*

**What is the current behavior?**
In Firefox the `dialog` element is not implemented. We use a polyfill to be able to support it. Everything works well. But React warns that the `dialog` element is unrecognized, and this on each page load, which is quite useless (for this specific case).
I would like the possibility to disable the  warning but only for some elements. So the utility of this warning remains when the developer mistype the component name.

**What is the expected behavior?**
Once we specified which tag are "accepted/normal" React will not warn on specified unrecognized tags.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16
Firefox 57

In previous versions there was no warning.

Is this clear enough? Do you need any other information?
Cheers

**Comment by gaearon** [comment]
We won't be making this customizable. But we're happy to take PRs that silence the warning for specific tags that are known to be on the standards track and will soon be implemented by the browsers. We already have such an exception for `<time>`. Would you like to send a PR?

**Comment by ChrisRast** [comment]
Okay, thanks. I'll see what I can do.
But is it wise to silence dialog when we don't know when it will be implemented? The ticket tracking the issue at Mozilla is already 9 months old and it doesn't seem there's a lot of movement.

**Comment by gaearon** [comment]
It's in MDN and in the spec so seems like fair game. Let's add it.

**Comment by ChrisRast** [comment]
I was about to start to dig in to see how I could do that. But thank you. =)
Cheers

**Comment by pgruenbacher** [comment]
what about x3dom elements?
x3dom will use a lot of custom elements to generate webgl scenes.
https://doc.x3dom.org/author/Geometry3D/BinaryGeometry.html

**Comment by gaearon** [comment]
Please file a new issue with an example. We could add more special cases.

**Comment by pgruenbacher** [comment]
https://github.com/facebook/react/issues/11184

**Comment by gaearon** [comment]
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.

**Comment by lar248** [comment]
We updated our `react`, `react-dom` and `react-test-renderer` as suggested. We still have the issue for `tspan` and `text` - where can we find the tags that are silenced?

**Comment by gaearon** [comment]
Please provide a reproducing example. Maybe you're accidentally rendering them outside of SVG?

**Comment by gaearon** [comment]
Also, we don't track closed issues. If you have a problem please create a new one.
