### ISSUE TITLE
Leading zeros in controlled input with integer value

### ISSUE THREAD

**Issue by zonzujiro** [facebook/react#11021]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the text input, I can see leading zeros when I pass digit value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
For some reason, I can't reproduce this bug on jsfiddle or codepen. Moreover, react works fine there.

Steps:

1. Create controlled text input and add `onChange` listener, which saves input value to `state` as an integer.
2. Pass value from `state` to input.
3. Write `0000001` to input. Value in `state` is equal to `1`, but value of input is `0000001`

**What is the expected behavior?**
A value in the input is the same as in the state — `1`. Without leading zeros.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
CRA, React 15.5.4
Chrome, IE 11/Edge, Firefox

I understand that this is the very low amount of information, so I will be happy to provide more. Just need to know what else would be useful.

**Comment by aweary** [comment]
Thanks for the report @zonzujiro, we're aware of this issue. React compares the values as numbers to determine if it needs to update the input's value, and `0001` and `1` are equal so it assumes it doesn't need to update the value.

See https://github.com/facebook/react/issues/9402 for more information. Thanks!

**Comment by zonzujiro** [comment]
@aweary, thank you for the response! 

This behavior depends on some facts other than just passed and current values in `input`?  I'm asking because same code works fine here https://codepen.io/alexfedoseev/pen/gpepQE

**Comment by zonzujiro** [comment]
@aweary thank you for the response!
 
As far as I understand, it is `number` input in https://github.com/facebook/react/issues/9402 . So it is logical that React compares values of `number` inputs like numbers. But I have `text` input. I don't think that React compares values as numbers for the `text` inputs too. 😄 

I tested same code as I have on my project on [codepen](https://codepen.io/anon/pen/RLLVJM#anon-login) and it works fine. So looks like this behavior depends on the execution environment? Could this be the issue of `CRA` or `Babel`, or something else?
