### ISSUE TITLE
How can I create a PR for e.g. the create-react-class module?

### ISSUE THREAD

**Issue by rogierschouten** [facebook/react#11024]
Lots of react modules have just https://github.com/facebook/react listed as repository.  I would like to create PRs for create-react-class and for react-dom-factories.  Where can I do that?  Is the code in this repo somewhere (where?)?

**Comment by gaearon** [comment]
It's on `15-stable` branch but we're not maintaining that code actively anymore. What did you want to change?

**Comment by MichaelDeBoey** [comment]
@rogierschouten All the react modules you're searching for are in the [`packages`](https://github.com/facebook/react/tree/master/packages) folder of the root of the project, so you can just open a PR to the repo with changes in the correct folder, like you would do for the main `react` code 🙂

**Comment by rogierschouten** [comment]
Thanks @gaeron and @MichaelDeBoey  

I wanted to add peer dependencies to React in package.json.  My build system doesn't like the fact that these modules require React without referring to it in package.json.   However if the 15-branch isn't maintained I'll just have to upgrade to 16.  It seems that the modules in the master packages directory already have the peer dependency set.

**Comment by gaearon** [comment]
>My build system doesn't like the fact that these modules require React without referring to it in package.json

That's unfortunate. The problem with these peer dependencies is they don't add any value, and make testing prereleases very awkward because of noisy warnings.

>It seems that the modules in the master packages directory already have the peer dependency set.

I'm not sure what you're referring to. We don't maintain these modules anymore, and they don't exist in master.
