### ISSUE TITLE
Error and error info logged in wrong order in Firefox

### ISSUE THREAD

**Issue by xMartin** [facebook/react#11022]
In React 16 when a component throws an error in development mode the error itself ("ReferenceError: x is not defined") and additional info ("The above error occurred in the <HelloWorld> component: ...") is logged.

In Firefox this happens in the wrong order so that "the above error" is actually below:
![bildschirmfoto 2017-10-02 um 11 08 08](https://user-images.githubusercontent.com/112532/31070963-a4147534-a762-11e7-88cd-5c15f263f219.png)

Works fine in Google Chrome.

Firefox version: macOS 56.0 and 57.0b4
React v16.0.0

How to reproduce:
Open browser console and have a component throw an error like:
```javascript
const HelloWorld = () => (
  <h1>Hello, world {x}!</h1>
);

ReactDOM.render(
  <HelloWorld />,
  document.getElementById('root')
);
```
https://codepen.io/anon/pen/mBMGyV

**Comment by gaearon** [comment]
I wonder why that happens.

**Comment by gaearon** [comment]
I filed an issue with Firefox. I don't think React is doing anything wrong here. Other browsers appear consistent (even including jsdom).

https://bugzilla.mozilla.org/show_bug.cgi?id=1483662
