### ISSUE TITLE
Warning Documentation 404 Not Found

### ISSUE THREAD

**Issue by mvargeson** [facebook/react#11036]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The documentation for [warnings](https://github.com/facebook/react/tree/master/docs/warnings) returns a 404

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
https://cl.ly/080p0f1t400y

**What is the expected behavior?**
Redirect to correct documentation.

~~**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**~~

---
The workaround is to look at the cached version from a google search or check for markdown [here](https://github.com/facebook/react/tree/master/docs/warnings).

**Comment by gaearon** [comment]
Thank you so much for reporting. I pushed out a fix, should deploy in a few minutes.
