### ISSUE TITLE
Missing documentation: null/undefined as input value

### ISSUE THREAD

**Issue by DanielSWolf** [facebook/react#11031]
**Do you want to request a *feature* or report a *bug*?**

I'd like to request documentation. :-)

When you pass `null` as `value` of an input, you get the following warning:

> warning.js:33 Warning: `value` prop on `select` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

This warning very clearly states what to do. My problem is, it fails to mention *why* I'm not supposed to pass `null`. Nor could I find any explanation online:

* I found a link to <http://facebook.github.io/react/tips/controlled-input-null-value.html>. The URL (...controlled-input-null-value...) sounds as if this page should explain exactly what I'm looking for. But it merely redirects to <https://reactjs.org/docs/forms.html>, which doesn't mention `null`.
* The issue ["Warn when input's value is null"](https://github.com/facebook/react/issues/5013) states that this warning should be added, but doesn't say why.
* The (open) pull request ["Document that `value={undefined}` is not controlled component"](https://github.com/facebook/react/pull/9849/files) adds the following documentation: "Similarly to not setting the `value` attribute at all, setting it to `null` or `undefined` will make React assume the component is not controlled and may produce a warning." But again, there is no explanation as to *why* React behaves this way.

Naively, I'd expect `null` to be a perfectly valid value, e.g. for a numeric input that is empty. Passing an empty string to indicate the absence of a numeric value seems odd to me. So I'd really like some more information in the documentation!

**Comment by gaearon** [comment]
Sorry about the confusing redirects. We rewrote the docs last year and did best effort redirects, but it's worth updating some of the warnings to better locations.

If I recall it right, the reason for this warning is just because we wanted to change the behavior for `null`. So not using it ensures your code won't break when we do change it.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for reactjs.org now lives in a different repository: reactjs/reactjs.org. (For more backstory on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#16

Let's continue the discussion there! Sorry for the inconvenience.

**Comment by ThaJay** [comment]
> If I recall it right, the reason for this warning is just because we wanted to change the behavior for null. So not using it ensures your code won't break when we do change it. We haven't changed it yet.

Is there a reason this is still the case? I think it's a strange rule as it's normal to use `null` as /explicitly/ not a value, as opposed to `undefined` which means /does not exist/ and react enforces `null` as a return value when explicitly not returning a component.
