### ISSUE TITLE
Resolution failure with bundle-collapser and non-unique file contents

### ISSUE THREAD

**Issue by rreusser** [facebook/react#11049]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

### What is the expected behavior?

Expected behavior is that `$ browserify index.js` and the [recommended optimization](https://reactjs.org/docs/optimizing-performance.html#browserify) `$ browserify index.js -p bundle-collapser/plugin` resolve requires correctly and produce functionally equivalent output.

### What is the current behavior?

Observed behavior is that [bundle-collapser](https://github.com/substack/bundle-collapser) causes a browserified bundle to resolve files incorrectly when components with different paths have identical contents.

### Steps to reproduce

For a full reproduction, see: [bundle-collapser-uniqueness-failure#react](https://github.com/rreusser/bundle-collapser-uniqueness-failure/tree/react). `a/index.js` and `b/index.js` should render different values (coming from `a/value.js` and `b/value.js`, respectively), but since the component content is identical, `b/index.js` erroneously resolves to the wrong component and displays a's value.

For a simpler reproduction not specific to react, see [bundle-collapser-uniqueness-failure](https://github.com/rreusser/bundle-collapser-uniqueness-failure).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This is a browserify+bundle-collapser issue so that the react version is irrelevant. The real issue here is that it's an [officially recommended optimization](https://reactjs.org/docs/optimizing-performance.html#browserify) that may result in an invalid bundle.

**Comment by gaearon** [comment]
I guess it's not as important anymore in React 16 since we now ship flat bundles so we don't have long module IDs.

Want to send a PR to remove it?

**Comment by rreusser** [comment]
Ah, so you mean that React 16 is still affected by this, but the savings aren't so great because of how react 16 is distributed? That makes sense. I'll submit a PR to remove the recommendation for now. Goal is to get the core issue fixed, and then maybe it'll be a nice thing to use once more.

**Comment by gaearon** [comment]
>Ah, so you mean that React 16 is still affected by this, but the savings aren't so great because of how react 16 is distributed? 

Yep!
