### ISSUE TITLE
Active Tab is not included in current route or permalinks on new docs site

### ISSUE THREAD

**Issue by jasonsalzman** [facebook/react#11043]
**Do you want to request a *feature* or report a *bug*?**
bug on new docs site

**What is the current behavior?**
on the new docs site active tab is not included in current route or permalinks so when attempting to send someone here https://reactjs.org/docs/installation.html#using-a-cdn they are instead dropped here https://reactjs.org/docs/installation.html because the correct tab is not active

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
- go here https://reactjs.org/docs/installation.html
- click "add react to existing app" tab
- grab any permalink from within this section, (ex. https://reactjs.org/docs/installation.html#enabling-es6-and-jsx)
- open that permalink from within an incognito window

**What is the expected behavior?**
should be taken to the correct linked section within the docs

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
this is not an issue with react itself, just the new docs site

**Comment by gaearon** [comment]
This is important to fix.

I linked quite a few times to specific sections there. Maybe even on our website.

**Comment by bvaughn** [comment]
Hmm...it's interesting that this works correctly locally (in dev-mode). The correct tab is opened and the body scrolls to the specified anchor tag. On the production website, the correct tab is _usually_ active but the body doesn't scroll correctly.

**Comment by bvaughn** [comment]
I think I might just remove the tabs mechanism entirely. The HTML+CSS embedded in a markdown file approach is a nasty one-off anyway.

I'll post a PR that breaks this file into 3 files, and adds a nested side-nav entry for them. To follow soon...
