### ISSUE TITLE
react-test-renderer/shallow throws if NODE_ENV===production

### ISSUE THREAD

**Issue by PixnBits** [facebook/react#11055]
**Do you want to request a *feature* or report a *bug*?**
Feels like a bug, open to correction/context

**What is the current behavior?**
react-test-renderer/shallow throws if `NODE_ENV===production`; more details under "which versions of React" below

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
does `NODE_ENV=production jest` count? ;) jk
`NODE_ENV=production jest` with specs comparing snapshots of shallow rendered components utilizing libraries that change behavior when `NODE_ENV=production` (ex: [recompose](https://github.com/acdlite/recompose/blob/e50934ebc4a313a9bee9a02d182171eb06a4fe72/src/packages/recompose/renderComponent.js#L7-L9))

**What is the expected behavior?**
Able to shallow render components as they would/will be when built and deployed to production.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
[v15.x react-test-renderer/shallow](https://github.com/facebook/react/blob/v15.6.1/packages/react-test-renderer/shallow.js) runs happily, [the check and error throw appears to be new in v16.x](https://github.com/facebook/react/blob/v16.0.0/packages/react-test-renderer/shallow.js#L3-L5)

Related: [7231 comment](https://github.com/facebook/react/issues/7231#issuecomment-236370277) had a response of 
>There should be no difference...between dev and prod versions of React. 

which is great news in terms of react 👍  but disallowing prod version of shallow render doesn't cover the prod code path of other libraries/dependencies 🙏

**Comment by gaearon** [comment]
The use case sounds reasonable to me. As I mentioned in https://github.com/facebook/react/issues/10938 I would take a PR that makes proper production builds for them.

**Comment by aweary** [comment]
Also, let's keep the conversation in #10938.  Thanks!

**Comment by PixnBits** [comment]
Ah, so sorry, that issue didn't come up in my searches. Feel free to close this one in favor of #10938.
