### ISSUE TITLE
Relationship between render()/updateContainer() and requestAnimationFrame()?

### ISSUE THREAD

**Issue by dakom** [facebook/react#11060]
This is highly related to https://github.com/facebook/react/issues/10950

When I call ReactDOM.render() - or more accurately updateContainer() from within a renderer, it seems the `callback` param is called somewhere in between "updating" and "rendered"

Specifically, if the callback is itself is a call to `updateContainer()`, e.g. a recursive approach, I get an error of:

> flushSync was called from inside a lifecycle method. It cannot be called when React is already rendering.`

_tangential note - this happens even if `updateContainer()` was triggered elsewhere like `deferredUpdates()` - `flushSync()` may be a bit misleading_

Can someone please explain this a little more- what does the order look like between updateContainer() and the callback?

My use case is as described in the other issue, but for the sake of clarity, I'd like to 

1. Call the top-level render() when the components have all finished rendering
2. Rely on React's requestAnimationFrame timing rather than inject another one for triggering prop changes
3. Do all this without making the root node manage it via setState() + componentDidUpdate()

Real-world scenario is using React to drive animation via a custom renderer

Thanks!

**Comment by dakom** [comment]
Fwiw here's what I believe to be the correct order of events, if a callback is provided and updateContainer() is called via Renderer.flushSync():

1. Renderer: batchedUpdates()
2. Renderer: unbatchedUpdates()
3. Renderer: flushSync()
4. Component: render()
5. Component: componentDidMount()
6. callback()
7. Renderer: deferredUpdates()
8. (after state changes) Component: componentDidUpdate()

**Comment by gaearon** [comment]
Reconciler doesn't currently use animation frames at all.
