### ISSUE TITLE
Move website source to new reactjs.org repo

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#11075]
Now that the new website has launched I propose we do the following clean-up steps:
* Move Gatsby source and dynamic content (*.md and *.yml files) to new repo
* Update external tools like Netlify and Crowdin to use this new repo
* Delete Jekyll website source

This will offer several benefits, including:
* Improve focus and simplify triage process for both the website and framework repos
* Cut down on noise from Netlify preview comments on PRs that aren't related to website

I'm creating this issue mostly to facilitate discussion around the new proposed directory structure (below).

### Proposed Directory Structure

```sh
├── content                              # Markdown and YML source
│   ├── blog
│   │   ├── markdown-files-here...
│   │   └── nav.yml
│   ├── community
│   │   ├── markdown-files-here...
│   │   └── nav.yml
│   ├── docs
│   │   ├── markdown-files-here...
│   │   └── nav.yml
│   ├── tutorial
│   │   ├── markdown-files-here...
│   │   └── nav.yml
│   ├── acknowledgements.yml
│   ├── authors.yml
│   └── index.md
├── plugins                              # Custom plug-ins
│   ├── gatsby-remark-use-jsx
│   └── gatsby-transformer-authors-yaml
├── src                                  # Gatsby site source goes here
│   ├── components
│   ├── css
│   ├── layouts
│   ├── pages
│   └── templates
├── static                               # Images and other statically-linked content
│   └── large-logo.svg
├── CONTRIBUTING.md
├── LICENSE.md
├── README.md
└── package.json
```

cc @ericnakagawa, @flarnie, @joecritch

**Comment by joecritch** [comment]
Liking this! I think this will streamline efforts from both sides.

**Comment by Mathspy** [comment]
Another benefit could be that since you're moving the docs (along with their license) is being able to display the MIT license in the navigation bar per this discussion: https://github.com/facebook/react/pull/10891

**Comment by gaearon** [comment]
There's a whole lot of benefits. My favorite one is hopefully people will stop trying to read docs on GitHub. We'll also reduce the issue noise and hopefully have more community members with commit access. I'm unreasonably excited about this.

@bvaughn Let me know if I can help. I love deleting/moving things. Better than real work!

**Comment by bvaughn** [comment]
> Let me know if I can help. I love deleting/moving things. Better than real work!

😆  Thanks Dan! I enjoy it too. I'll take care of this one. 😁

**Comment by yangshun** [comment]
@bvaughn I would love to help out in this effort if you like. I can start with smaller tasks.

**Comment by bvaughn** [comment]
Thanks for the offer, but I think I'm good for the bulk of it. Help would be great once the project has been moved and I file a bunch of issues. 😄

**Comment by bvaughn** [comment]
One thing I did not consider when creating this issue was how to best keep [`scripts/error-codes/codes.json`](https://github.com/facebook/react/blob/master/scripts/error-codes/codes.json) in sync.

**Comment by bvaughn** [comment]
I wrote a Gatsby source plugin that loads the data from the React repo (using GitHub's user content API). I think this is reasonable for now. Let's talk more if anyone has concerns though.

**Comment by gaearon** [comment]
Sounds good to me. (But does this mean we can't run website offline now?)

**Comment by bvaughn** [comment]
> Sounds good to me. (But does this mean we can't run website offline now?)

To run the website offline we'll need to first re-enable service workers (and figure out why they were causing intermittent problems). But this change won't preclude that. The plug-in I wrote embeds the data at build (or dev startup) time so that the end result will be the same as before.

**Comment by bvaughn** [comment]
I believe it should be possible to preserve history in this new repo by doing the following:

```sh
# git filter-branch only supports a single folder
# So start by creating one pruned repo per folder we want to preserve
# Copy history from the "docs" folder
# (This step will take a long time because there's a lot of history to copy)
git clone git@github.com:facebook/react.git react-docs
cd react-docs
git filter-branch --prune-empty --subdirectory-filter docs master

cd ..

# Copy history from the "www" folder
git clone git@github.com:facebook/react.git react-www
cd react-www
git filter-branch --prune-empty --subdirectory-filter www master

cd ..

# Create a new repo to unify our filtered repos
mkdir reactjs.org
cd reactjs.org
git init

# At least one commit is needed before the below steps will work
git commit --allow-empty -m "Initial (empty) commit"

# Merge docs changes
git remote add react-docs ../react-docs
git fetch react-docs
git merge -s ours --no-commit react-docs/master --allow-unrelated-histories
git read-tree --prefix=docs -u react-docs/master
git commit -m "Import docs"

# Merge www changes
git remote add react-www ../react-www
git fetch react-www
git merge -s ours --no-commit react-www/master --allow-unrelated-histories
git read-tree --prefix=www -u react-www/master
git commit -m "Import www"

# Move things around (as outlined in the issue description) commit by commit
```

**Comment by Daniel15** [comment]
> The website's build scripts could load the latest error codes from the facebook/react repo at build time

We do something similar for the Babel site - It loads all the package readmes from the main Babel repo. The script is here: https://github.com/babel/website/blob/master/scripts/download-readmes.js

> I believe it should be possible to preserve history in this new repo by doing the following

I'm glad you could work this out. I was splitting one of Yarn's repositories into two separate ones (https://github.com/yarnpkg/releases and https://github.com/yarnpkg/release-infra) and it took forever to work out how to actually do it 😛

**Comment by bvaughn** [comment]
Gatsby's plug-in system made this ridiculously easy to do. 😄 

https://github.com/reactjs/reactjs.org/blob/master/plugins/gatsby-source-react-error-codes/gatsby-node.js
