### ISSUE TITLE
Some old fiddles still broken due to some HTTP/HTTPS issue

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11077]
See here for example: https://jsfiddle.net/69z2wepo/48909/

>Mixed Content: The page at 'https://jsfiddle.net/69z2wepo/48909/' was loaded over HTTPS, but requested an insecure script 'http://reactjs.org/js/jsfiddle-integration-babel.js'. This request has been blocked; the content must be served over HTTPS.

It's as if redirect happens without preserving the protocol.

**Comment by Dzhakhar** [comment]
Why is important to keep the fiddles working stable? Is official react documentation has reference to the fiddles?

**Comment by gaearon** [comment]
Many old issues refer to them. Broken fiddles are harder to check against the latest version.
Not to mention code examples people built for education or documentation.

**Comment by bvaughn** [comment]
Relocated to reactjs/reactjs.org/issues/11
