### ISSUE TITLE
Are componentWillMount calls order deterministic with ReactDom.hydrate and ReactDOMServer.renderToString?

### ISSUE THREAD

**Issue by oliviertassinari** [facebook/react#11070]
This is a question related to server-side rendering support of Material-UI.

We have a use-case where we generate class names based on the React tree traversal order.
One of our users (@djeeg) [have noticed](https://github.com/callemall/material-ui/issues/8522) that the same React tree can potentially be traversed in different order between the server-side and the client-side when using `ReactDom.hydrate`.

Hence my question: Are `componentWillMount` calls order deterministic with `ReactDom.hydrate` and `ReactDOMServer.renderToString`?

**Comment by gaearon** [comment]
Can you explain the order difference that you see? It's not very obvious to me. I would expect that currently both work depth first and those that appear earlier amongst siblings fire earlier. Are you seeing different results?

That said you probably shouldn't rely on the order of `componentWillMount` calls on the client. That will break in async mode in the future because mounting can be paused, aborted, restarted etc.

**Comment by oliviertassinari** [comment]
> Can you explain the order difference that you see?

@gaearon Unfortunately, I don't have access to any reproduction example. All I have got is an issue description https://github.com/callemall/material-ui/issues/8522. Hopefully, I will soon be able to dig more into the issue with one. 

As I understand your answer, we can expect the same tree traversal algorithm, hence the same call order of the `componentWillMount`. 

> will break in async mode in the future

This is good to know! And as far as I have heard of it, we can end up in a situation where `componentWillMount` is called but `componentDidMount` nor `componentWillUnmunt` are called. This is challenging to handle. We gonna need to rethink our cleanup logic.

I'm assuming that scheduling a timeout during the `componentWillMount` waiting for a `componentDidMount` event will be a good workaround. This way, we can remove our styles from the page if the component, after all, is not mounted. cc @kof.

Thanks for the answer.

**Comment by gaearon** [comment]
cc @acdlite who might have the most context on the implications of this right now.
