### ISSUE TITLE
react-dom problems with CSP?

### ISSUE THREAD

**Issue by fernandops26** [facebook/react#11076]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' . Either the 'unsafe-inline' keyword, a hash ('sha256-....'), or a nonce ('nonce-...') is required to enable inline execution.

**What is the expected behavior?**
no error with CSP.

I am try use react-select(1.0.0-rc.10) in my app, and the CSP is enabled, but the result is the mentioned.Apparently the problem is by react-dom in this line:
![csp](https://user-images.githubusercontent.com/11939055/31154044-056f50e4-a86a-11e7-8043-6ebb75a47128.png)

**Comment by gaearon** [comment]
I don’t know much about CSP, but isn’t it what it says: 

>Refused to apply inline style

If inline styles are not allowed, there’s nothing React can do to work around it. You need to ensure your code (or any of your dependencies) doesn’t contain them.

**Comment by fernandops26** [comment]
@gaearon If I need to fully ensure the application(not use unsafe-inline). Can I not have another solution?
