### ISSUE TITLE
Idea: Host codemods on the website

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11080]
It would be nice to provide a REPL for codemods on the website, especially for createClass or PropTypes conversion. This is handy for one-offs like converting StackOverflow answers or fiddles, but also introduces people to the idea of codemodding in a playful way. The REPL can include instructions on running it locally on the bottom.

**Comment by bvaughn** [comment]
Sounds fun. How do you see this in relation to [reactjs/react-codemod](https://github.com/reactjs/react-codemod)? Does one link to the other? Or would we fork a few of the more common code-mods for this REPL?

**Comment by gaearon** [comment]
I imagined we'd somehow just run those in the browser. To be honest I didn't think how to do it 🙈

**Comment by bvaughn** [comment]
Fair!

Seems like we could add the NPM `react-codemod` module to the website's deps and embed a few of them that way.

I'd be happy to play around with this at some point. I enjoy REPL stuff.

**Comment by gaearon** [comment]
Another thing that's missing is HTML -> JSX converter. There is one at https://github.com/reactjs/react-magic/blob/master/README-htmltojsx.md but apparently it points back to our website which doesn't provide it anymore 😛 We should just host it and then link "Invalid prop className" warnings to it.

**Comment by bvaughn** [comment]
There isn't actually one on our site:
https://github.com/facebook/react/blob/master/docs/html-jsx.html

Let's just update the doc you're talking about to point to http://magic.reactjs.net/htmltojsx.htm so we don't need to continue to support the redirect?

**Comment by gaearon** [comment]
>Let's just update the doc you're talking about to point to http://magic.reactjs.net/htmltojsx.htm so we don't need to continue to support the redirect?

Sorry I didn’t clarify. I meant that I would prefer it to be an official tool, not just a volunteer-run project that breaks every time we do a release. So I don’t mean just hosting it, but making it visible somewhere on the website (and not just if you know the link).

**Comment by bvaughn** [comment]
Well the PR I sent should pull us out of the loop so that it wouldn't break when we did future releases.

**Comment by bvaughn** [comment]
Moved to reactjs/reactjs.org/issues/12!
