### ISSUE TITLE
Error boundaries causes multiple errors to be thrown in development mode

### ISSUE THREAD

**Issue by gribnoysup** [facebook/react#11082]
**Do you want to request a *feature* or report a *bug*?**
A bug maybe?

**What is the current behavior?**
Error caught in React lifecycle methods thrown twice in development mode.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

https://codesandbox.io/s/nwp77vk9ql

If you look in the console you will see that one of the errors is caught, but the other one is still thrown as `Uncaught Error`. This could possibly be confusing to some people when they will see two identical errors in the console.

**What is the expected behavior?**
Should an error be thrown only once?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16

I stumbled on this while fixing one of the tests that checked that component should throw in some conditions. This test started failing in React 16 because of the second `Uncaught Error` thrown by React. 

I'm not really sure that this is a bug, just wanted to clarify whether it was made intentionally or not. Seems like [this "trick"](https://github.com/facebook/react/blob/e932ad68bed656eed5295b61ba74e5d0857902ed/src/renderers/shared/fiber/ReactFiberErrorLogger.js#L68) causes this behavior.

If this is a bug, I'm happy to help to fix it, if someone would suggest where to start with this :)

**Comment by gaearon** [comment]
This is basically the same as https://github.com/facebook/react/issues/10474 and https://github.com/facebook/react/issues/10384.

I'll close in favor of them.

**Comment by gaearon** [comment]
I also wrote up an explanation in https://github.com/facebook/react/issues/10384#issuecomment-334142138.

**Comment by gribnoysup** [comment]
Oops, soory! Went through the issues page, but missed them

**Comment by gaearon** [comment]
No worries, we have too many. 😄
