### ISSUE TITLE
Deduplicate the warning about functions not being valid children

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11086]
Same as https://github.com/facebook/react/issues/11081, but for this one:

<img width="476" alt="screen shot 2017-10-04 at 16 35 07" src="https://user-images.githubusercontent.com/810438/31184704-0d705000-a922-11e7-852e-5890962ff1e5.png">

**Comment by andreysaleba** [comment]
Hey, I'd try to fix this one

**Comment by gaearon** [comment]
Sure, sounds good. Holler if you need any help.

**Comment by andreysaleba** [comment]
I've added commit for this one #11120

**Comment by andreysaleba** [comment]
#11120

**Comment by andreysaleba** [comment]
I've added commit solving this bug. I hope it's okay :)

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11120
