### ISSUE TITLE
Deduplicate "Render methods should be pure" warning

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11081]
## Note: the task is already claimed.

Just saw this in a fiddle that has a nested update bug:

<img width="414" alt="screen shot 2017-10-04 at 11 52 52" src="https://user-images.githubusercontent.com/810438/31172209-923c2278-a8fa-11e7-8ffe-4dbfaa472663.png">

It would be nice to just dedupe them in the first place instead of calling `console.error` a thousand times.

---

**Comment by gaearon** [comment]
Same for this one:

<img width="389" alt="screen shot 2017-10-04 at 11 54 11" src="https://user-images.githubusercontent.com/810438/31172262-c3e7c192-a8fa-11e7-8c16-e26e49cd0056.png">

**Comment by anushreesubramani** [comment]
I am interested in taking this up. This would be one of my first open source contributions and I am really excited about it :)

**Comment by gaearon** [comment]
Sounds great! You'll need to search the codebase to find where we fire these two warnings, and then add boolean variables for each. If we fire it once, we set a boolean. Next time we check a boolean before firing it, and skip if the boolean is already set.

**Comment by gaearon** [comment]
If you have any questions feel free to ping me here.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11113.
