### ISSUE TITLE
Even Though I am using the webpack uglifyjs plugin for minification ReactDevTools is telling me that I have unminified code that is not production quality

### ISSUE THREAD

**Issue by interglobalmedia** [facebook/react#11085]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
ReactDevTools is showing the red icon for my deployed application even though I am using the webpack uglifyjs plugin and the webpack DefinePlugin with process.env.NODE_ENV': JSON.stringify('production').
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**
That react DevTools would show me a black icon indicating production quality code.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am using  the latest version of Google Chrome, Version 61.0.3163.100 (Official Build) (64-bit) and this app is running with "react": "^15.6.1" and "react-dom": "^15.6.1".

**Comment by gaearon** [comment]
Unfortunately we can’t help you if you don’t share the URL where it happens or a project example.

**Comment by interglobalmedia** [comment]
Hey Dan, It's working fine. This can be closed. Silly mistake. There still is the source-map issue however... Doesn't generate on build. Only for CSS. But I think that might be more of a webpack issue!  Here is the link so you can see it is working! https://interglobalmedia.github.io/react-todo-app/ Thanks always for all your help and knowledge sharing everywhere!

**Comment by gaearon** [comment]
>There still is the source-map issue however... Doesn't generate on build. Only for CSS.

That's odd! If you could file an issue in CRA repo with an example that would be helpful!

I'm glad that the production detection seems to be working. Cheers!

**Comment by interglobalmedia** [comment]
fyi: I'm not using CRA. However, it is an ongoing thing that is heavily discussed in webpack threads. There are other conflcts with the plugin that arise as well. I know what the reason is, however as I have done extensive testing on this. It's the `webpack -p` or anything like webpack --config webpack-prod.config.js` in package.json. When you have any variation of that in your scripts in package.json, source-maps are not emitted in production when using the webpack uglifyjs plugin or even the regular uglifyjs plugin. Don't think you use those flags in CRA, right? So maybe then it isn't an issue. If so, SMART! One day I'll figure out how to circumvent that problem too. That said, should I still post this issue in CRA. Please advise. Thanks!

**Comment by gaearon** [comment]
Oh, if you don't use CRA, then this doesn't apply.

> Don't think you use those flags in CRA, right? 

No, we don't use `webpack -p`. Instead we have a separate production config where we explicitly use [these two webpack plugins](https://reactjs.org/docs/optimizing-performance.html#webpack) and specify `devtool: 'source-map'` to produce separate sourcemap files.

Hope it helps!

**Comment by interglobalmedia** [comment]
Thanks Dan! That's a great start. I'll look into it!

**Comment by interglobalmedia** [comment]
Totally different ballgame. Nifty!
