### ISSUE TITLE
Reconciler is gone

### ISSUE THREAD

**Issue by cztomsik** [facebook/react#11118]
Question

I know this is intentional but how is one able to track the index of new/removed node? Are you going to provide any other API for this?

This is important for being able to integrate (correctly) with third-party code, for example PIXI.js and Three.js have addChild/removeChild/addChildAt/... APIs and so it's important to be able to tell where the node was before. I can imagine something like this could be beneficial even for terminal UI and native UI

To illustrate what I mean:

```
<Container>
  <Sprite ... />
</Container>
```

should get expanded to:

```
const ct = new Container()
const s = new Sprite()
ct.addChild(s)
```

and then any new children should be appended with `.addChild()` and/or removed with `.removeChild()` or preferrably with `.removeChildAt()`

React 16

**Comment by TrySound** [comment]
@cztomsik 
```js
const dom = React.createElement(Container, null,
  React.createElement(Sprite)
);
```
React dom should be immutable. Manipulation can be happen by generating new structure.

**Comment by cztomsik** [comment]
Please have a look how `react-three` is currently implemented internally (it uses undocumented react 15 classes) to do this. It has to hook inside transaction to see what has changed so it can apply those updates to an actual three.js (mutable) API

**Comment by iamdustan** [comment]
A solution for #9103 is in progress which will give you first-class access to creating a renderer.

**Comment by gaearon** [comment]
Yes, this is solvable with the new reconciler API (unfortunately none of your existing code will work, but the good news is that it's a real API now rather than a bunch of hacks).

We'll make it consumable soon. You can track #9103 for exposing it.
