### ISSUE TITLE
Consider providing a UMD build for TestUtils again

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11111]
I noticed we stopped providing it, but a bunch of fiddles for old bugs use it.
I wonder if we should add it back, e.g. as `react-dom-test-utils.development.js`.

Let’s hear what people have to say.

**Comment by andydavies92** [comment]
@gaearon: I'm currently blocked on upgrading our application to React 16 due to the lack of a UMD build of TestUtils. Shall I compile one and submit a PR?

**Comment by gaearon** [comment]
Can you describe your use case in more detail? Why do you need a UMD build of something intended only for testing?

**Comment by markboyall** [comment]
Our application is non-trivially large, and module systems that involve transpiling our JS are unworkably slow. We have no choice but to use UMD if we don't want to wait multiple minutes every time we make any script change in development.

**Comment by andydavies92** [comment]
What @markboyall said :+1:

**Comment by gaearon** [comment]
OK that sounds reasonable. Happy to take a PR.

**Comment by andydavies92** [comment]
@gaearon: done (https://github.com/facebook/react/pull/11599) :+1:

**Comment by the-spyke** [comment]
Any workarounds for using `.renderIntoDocument()` in tools like `CodePen` with `react@16`?

**Comment by gaearon** [comment]
All `renderIntoDocument` does is create a div and call `ReactDOM.render` into it.

```js
var div = document.createElement('div');
ReactDOM.render(<App />, div);
```

Just use it directly.

**Comment by gaearon** [comment]
In general I recommend simulating real DOM events instead of using `Simulate` API.
For example, if the node is in a document (that's important!):

```js
node.dispatchEvent(new MouseEvent('click', {bubbles: true, cancelable: true}));
```

But again, as per feedback in this issue, we'll add a UMD build for TestUtils in later versions again.

**Comment by the-spyke** [comment]
Didn't saw this recommendation in React Docs. Thank you.

**Comment by gaearon** [comment]
Yep, we'll need to document this. I'll file an issue for the doc repo.

**Comment by gaearon** [comment]
Filed https://github.com/reactjs/reactjs.org/issues/352.
