### ISSUE TITLE
Check for rAF polyfill lazily

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11114]
Cases like https://github.com/facebookincubator/create-react-app/issues/3199#issuecomment-334475000 can be pretty confusing. We should probably move the warning to happen during first `ReactDOM.render` rather than immediately.

**Comment by gaearon** [comment]
See https://github.com/facebook/react/pull/11117#pullrequestreview-67824192.

**Comment by jovanliuc** [comment]
That's cool
