### ISSUE TITLE
React 16 Document breaking changes that didn't warn in React 15

### ISSUE THREAD

**Issue by mattkrick** [facebook/react#11123]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The path to upgrading from React 15 to 16 should be simple. From the docs:
> With minor exceptions, if your app runs in 15.6 without any warnings, it should work in 16.

There are 2 cases that I found where this isn't true:
- `this.state` can no longer be declared in `componentWillMount`. It never _should_ be declared there anyways, but React15 never yelled at me & I found an old component that did this & it was completely broken.
- The callback for `this.setState` can no longer be falsy. Before, i would write `const cb = false && callback`. now i have to write `const cb = false ? callback : undefined`. Again, it's sloppy code that should have never existed anyways, but it worked in React 15.

**What is the expected behavior?**
Adding these 2 things to the migration guide. Maybe re-enabling support for the falsy `setState` callback.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16, all browsers, It all worked in React 15

**Comment by iinsta** [comment]
Can you send a pr ? 😃

**Comment by gaearon** [comment]
A PR would be great. Since it was a re-implementation, it’s entirely plausible there are other things that have changed that are so rare we haven’t bumped into them. Neither of these sound like they would be more than a few lines of fixes though :-) So I don’t see the point in fixing them back if the new behavior is more in line with the originally intended usage.

**Comment by bvaughn** [comment]
Just an FYI, the documentation and source code for reactjs.org now lives in a different repository: https://github.com/reactjs/reactjs.org

Would you be willing to open a new issue in that repository, @iinsta? Sorry for the inconvenience!
