### ISSUE TITLE
[website] JSX Editor in documentation need more padding bottom

### ISSUE THREAD

**Issue by damaera** [facebook/react#11129]
i found this

![image](https://user-images.githubusercontent.com/5365957/31270232-aee31698-aaad-11e7-8923-43d2c2744098.png)

![image](https://user-images.githubusercontent.com/5365957/31270254-cadf704e-aaad-11e7-9b31-27b601aa9c40.png)

in every LIVE JSX EDITOR which have scroll

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄 

However the documentation and source code for reactjs.org lives in a different repository: https://github.com/reactjs/reactjs.org

Please open a new issue in that repository. Sorry for the inconvenience!
