### ISSUE TITLE
Missing docs about Transferring Props in JSX

### ISSUE THREAD

**Issue by hellobrian** [facebook/react#11124]
I noticed that the latest docs don't talk about [Transferring Props in JSX with rest properties](https://github.com/facebook/react/blob/v15.4.0-rc.3/docs/docs/06-transferring-props.md#transferring-with--in-jsx). 

This was really useful for building reusable react components. I was curious if omitting this documentation was intentional? If so, it would be great to understand why (not a good practice anymore?). 

Otherwise, I would be happy to send a PR that adds this back into the docs with any changes you and the community want to see. Overall, I just think this is important info to surface in the current docs.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄 

The documentation and source code for reactjs.org now lives in its own repository: https://github.com/reactjs/reactjs.org

If you don't mind, please open a new issue in that repository and we can discuss it there. Sorry for the inconvenience!
