### ISSUE TITLE
DOM Test Fixtures: Add caveats for IE9 range inputs (and other unsupported things)

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11131]
It can be confusing to recall that the range input type is not supported in IE9, invalidating a few of our test cases. For example:

<img width="924" alt="screen shot 2017-10-06 at 7 03 18 am" src="https://user-images.githubusercontent.com/590904/31275269-97e687ac-aa64-11e7-97fb-e430e7dfc369.png">

This test case verifies that changing a range slider with arrow keys works as expected, however it looks like a standard input in IE9. If we plan to make these test fixtures more public, I wonder if it would be worth adding some caveat language or marking a test as invalid for a certain browser.

Maybe this would be annoying, but I thought it might be nice to collect the opinion of others.

**Comment by aweary** [comment]
@sophiebits mentioned in https://github.com/facebook/react/issues/9301 that IE9 was maybe, probably OK not to support. If we can get confirmation on that, this would be a non-issue.

**Comment by jquense** [comment]
yo it would be awesome to not support ie9

**Comment by nhunzaker** [comment]
FWIW, all of this works in IE9. IE9 just doesn't have range inputs, so the range input test case doesn't test arrow keys. I just want to add a disclaimer in case someone comes to this page as a public site and gets confused and blames React.

**Comment by aweary** [comment]
@nhunzaker should we do the same for unsupported browsers? Maybe we can add some browser detection logic and then render a message like:

> This browser is not officially supported by React. If you discover an issue that only occurs in this browser it's likely expected behavior.

And then we can reuse the detection logic for other browser-specific quirks like this.

**Comment by aweary** [comment]
We could use something like [bowser](https://github.com/lancedikson/bowser) for browser detection.

**Comment by jquense** [comment]
might be worth pulling in like modernizer and attaching `supported` prop or something with a fn running a test? Not going crazy but for obvious cases like `() => modernizer.supportsRangeInputs` or whatever for clear cases
