### ISSUE TITLE
DOM Test Fixtures: Unable to Load React 16

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11132]
As far as I can tell, the path to the UMD version of React 16 changed, which makes it impossible to test the latest version of React through the test fixtures. We probably need to add a condition to the react loader to change the path above a certain version:

https://github.com/facebook/react/blob/master/fixtures/dom/src/react-loader.js#L45-L46

**Comment by aweary** [comment]
@nhunzaker did #11133 really resolve this? I thought the problem was the CDN paths we're using?

**Comment by nhunzaker** [comment]
No. Sorry. I got the wrong issue :(

**Comment by gaearon** [comment]
I fixed in 4a26b90cfa4a4f2b70dfa704b9706bb1c5fa26b4. Still broken for 16 alphas but they’re pretty borked anyway. Might need to blacklist them somehow.

**Comment by nhunzaker** [comment]
No problem. I added a little work around in #11200. It seemed about as good as a blacklist.
