### ISSUE TITLE
React 16 & bad UX! & scroll bug!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [facebook/react#11143]
# React 16 & bad UX!

![image](https://user-images.githubusercontent.com/18028768/31303856-952a37aa-ab47-11e7-9c5d-1726e1100d3f.png)

> right menu is too bad for UX!

> left menu should be much more better!

**Comment by xgqfrms-GitHub** [comment]
# scroll bug!

![image](https://user-images.githubusercontent.com/18028768/31303876-10c1b244-ab48-11e7-8e68-485f3c30e122.png)

**Comment by nihgwu** [comment]
Are you serious? This site is built for all the users, not to pleasure you only

**Comment by jonbellah** [comment]
The docs site now lives in a standalone repo: https://github.com/reactjs/reactjs.org - I believe this issue belongs there.

**Comment by gaearon** [comment]
Yes, please file website issues in the new repository.

https://github.com/reactjs/reactjs.org
