### ISSUE TITLE
React 16 Missing global context

### ISSUE THREAD

**Issue by igoldny** [facebook/react#11151]
hey,

i been using for Internationalize component that wrap my "App" component only to provide translation to the whole app like so:
```
<IntlProvider
  locale={locale}
  messages={messages}
>
  <App />
</IntlProvider>
```

and inside "IntlProvider" i set my translation into context with getChildContext:
```
getChildContext() {
    const { locale, messages } = this.props;
    return {
      intl: {
        messages,
        locale
      },
    };
  }
```

and then i could access it from anywhere from global context:
```
this._reactInternalInstance._context.intl
```

is this global context was removed? haven't seen this change in the breaking changes.
wrapping every component that use translations (99% of them do) with "IntlProvider" and use "this.context" instead sounds to me like overkill. 

there is a better approach?

**Comment by gaearon** [comment]
It was never supported to access anything on `reactInternalInstance`. This is why it has "internal" in the name and isn't documented in the public API. We reserve the right to break any internal APIs in any versions, including patch releases. Semantic versioning only covers public API. 

Currently, to read something from the context, you have to declare `contextTypes`. You can create a helper utility if you find this too cumbersome.

```js
function addIntlContext(MyComponent) {
  MyComponent.contextTypes = {
    ...Component.contextTypes,
    intl: PropTypes.object
  };
}

// usage
class Button extends React.Component {
  // ...
}
addIntlContext(Button);
```

It *is* possible we will lift this restriction in the future but it will be a part of a larger context API redesign.
