### ISSUE TITLE
React 16: "Expected server HTML to contain a matching <noscript> in <body>"

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11155]
It seems like putting `<noscript>` at the very end of the `<body>` tag makes React think it's missing. So React warns and compensates by adding another one.

<img width="661" alt="screen shot 2017-10-09 at 3 50 17 pm" src="https://user-images.githubusercontent.com/810438/31344111-a0946962-ad09-11e7-93dd-d6ae8e95229a.png">

<img width="227" alt="screen shot 2017-10-09 at 3 49 53 pm" src="https://user-images.githubusercontent.com/810438/31344073-8a6dbb7a-ad09-11e7-8f92-3d73fc5a7c8c.png">

This looks like a bug to me. Another (but different) issue about `noscript`: https://github.com/facebook/react/issues/10993.

**Comment by gaearon** [comment]
I don’t actually think this is a bug now. It was caused by the `<script>` running before `<noscript>` because we’re mounting into the document in that SSR fixture. It seems like if you render right into `document` then `<script>` that does the hydration should go last.

I could also work around it by delaying rendering:

```js
window.addEventListener('DOMContentLoaded', () => {
  hydrate(<App assets={window.assetManifest} />, document);  
});
```

I’ll close this for now but if we hear from more people that it’s confusing maybe we can make the message better.

**Comment by Toske94** [comment]
I'm new in this, can someone explain to me why I got this error

The script that I use is returning a picture, but sometimes the picture is not showing and I got this error:

Expected server HTML to contain a matching in .

import React from 'react';
import {Menu} from 'semantic-ui-react';
import { Link } from '../routes';

export default (props) => {
    return (
      <Menu borderless id="logo">
        <script 
            type="text/javascript" 
            src="https://example.com/link/script/" >
        </script>
    </Menu>
    );
};
