### ISSUE TITLE
onChange get executed only once react 15.6.1

### ISSUE THREAD

**Issue by hiteshsomani** [facebook/react#11154]
**Do you want to request a *feature* or report a *bug*?**
  bug
**What is the current behavior?**
  React(15.6.1) onChange gets fire only once  [reproduced bug link](https://jsfiddle.net/12b6znt6/4/)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**
Onchange should get executed as maany times as we select radio button
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.6.1

**Comment by jquense** [comment]
#10739
