### ISSUE TITLE
react-test-renderer 'find' method is documented incorrectly.

### ISSUE THREAD

**Issue by TAGraves** [facebook/react#11166]
There's a mismatch between the behavior of `react-test-renderer`'s `testInstance.find()` (and `findByType` and `findByProps`) method and the documentation. `find()` claims to "Find the first descendant test instance for which test(testInstance) returns true," but in fact it throws an error if there are multiple such descendant test instances. With the way the docs are worded, I expected it to work like `Array.prototype.find`. 

I'm happy to submit a PR fixing this, but I'd like some guidance on whether the docs are incorrect or the implementation is incorrect. For what it's worth, the implementation is wrapped in an `expectOne` so it  seems more likely to me that the docs are incorrect (i.e., this was a very intentional choice by whoever wrote the methods). I'm also happy to go in and split these out into two separate methods (e.g. `findExactlyOne` and `find`).

**Comment by gaearon** [comment]
Please fix it in the docs, thanks! I think I misunderstood it when I was documenting it.

I will close this issue because we now track docs in reactjs/reactjs.org. But if you don't find the time to send a PR please re-file the issue there. Thanks!
