### ISSUE TITLE
Shallow renderer: subsequent `setState` calls inside `componentWillMount` discard the previous ones

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/react#11161]
**What is the current behavior?**

If `componentWillMount` has multiple `setState` calls, only the last one works in shallow renderer

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://www.webpackbin.com/bins/-Kw11Ya_ZJ1BcL0rpDKj

Here, DOM renderer correctly renders "Hello, world" while test shallow renderer renders "undefined, world". 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Issue is introduced in React 16.

The reason must be those lines, replacing `publicInstance.state` with `this._renderer._newState` should fix it:
https://github.com/facebook/react/blob/e932ad68bed656eed5295b61ba74e5d0857902ed/src/renderers/testing/ReactShallowRendererEntry.js#L212-L215

**Comment by gaearon** [comment]
Want to send a PR?

**Comment by Hypnosphi** [comment]
Sure, will do

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/11167.

**Comment by gaearon** [comment]
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.
