### ISSUE TITLE
Server rendering meta tags / attributes non camelcase result in warning

### ISSUE THREAD

**Issue by michaelBenin** [facebook/react#11160]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Server rendering `<meta charset="utf-8" />`  or srcSet and other attributes which used to be needed to be camelcased. 

Results in: 

```
`webpack-internal:///./node_modules/fbjs/lib/warning.js:33 Warning: Invalid DOM property `charset`. Did you mean `charSet`?
    in meta (at head.js:39)
    in head (at head.js:35)
    in Head (created by Connect(Head))
    in Connect(Head) (at root_container.js:14)
    in html (at root_container.js:13)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at root_container.js:12)
    in Provider (at root_container.js:11)
    in Root (at index.js:95)`
```

And when we change it to `charSet` it renders the camelcased version. We should remove this warning.

It also happens with srcSet, httpEquiv etc. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

https://jsfiddle.net/5uoLz1Lz/1/

**What is the expected behavior?**

No warning should be given. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

In previous versions of React, we passed in the camelcase and it rendered the case correctly either snake or lowercase. Now it renders the camelcase when this is executed on the server.  

We are using React v16, happening in latest Chrome.

**Comment by gaearon** [comment]
>And when we change it to charSet it renders the camelcased version

This is not a bug. HTML is case insensitive so `charSet` is a completely valid output.

I agree it is a little bit surprising, and we are tracking this in https://github.com/facebook/react/issues/10863. But it’s not a real problem.

**Comment by michaelBenin** [comment]
> This is not a bug. HTML is case insensitive so charSet is a completely valid output.

What about hyphenated attributes? Is httpEquiv and http-equiv treated the same?

**Comment by gaearon** [comment]
@michaelBenin React should still use the correct attribute names. (In your example, it should emit `http-equiv`.) If you see that it doesn't please file a separate issue.

**Comment by dejurin** [comment]
<img width="1061" alt="Screenshot 2022-11-03 at 00 41 13" src="https://user-images.githubusercontent.com/4470015/199616218-4a933e58-78db-403a-839b-2bc16504521d.png">
