### ISSUE TITLE
Background color issue

### ISSUE THREAD

**Issue by vjekooo** [facebook/react#11162]
Hi

I've got this issue with background colors. 
This is just a simple component rendering a div with h1 in it.
Tested with Crome, Safari, Firefox and it's only visible in Chrome. The size of the dark rectangle is affected by the rendered div only when I give it a background color.

https://github.com/vjekooo/webpack_react

![react](https://user-images.githubusercontent.com/24388648/31350160-7350c30c-ad26-11e7-85b2-adbf4a162a28.png)

**Comment by gaearon** [comment]
I don’t see why this would be related to React.
It seems like a question about CSS, so I don’t think it belongs in our issue tracker.

If you’re sure it’s React-specific, please create a vanilla HTML/CSS demo that doesn’t also reproduce the issue.

**Comment by vjekooo** [comment]
There is no dark rectangle until I render a component, so I think it's React related.

**Comment by vjekooo** [comment]
Nope, having issues with vanilla js also. Sorry
