### ISSUE TITLE
React 16 does not render text area placeholder initially in IE11 Win10

### ISSUE THREAD

**Issue by curwen** [facebook/react#11172]
**Bug**

**What is the current behavior?**

IE11 Windows 10 text area placeholder not rendering initially.
[https://jsfiddle.net/fztx6vqp/](https://jsfiddle.net/fztx6vqp/)

**What is the expected behavior?**

Placeholder should be visible on initial render.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.0.0, IE11, Windows 10
Appears to be a regression in 16.0.0 - #6731

**Comment by gaearon** [comment]
We’ll need somebody else confirming that this reproduces in 16 and doesn’t reproduce in 15.6.1.

**Comment by aweary** [comment]
I verified that the provided example using 16 does not render in IE11 on Windows 10, but it does render using [this example with 15.6.2](https://jsfiddle.net/88ao6nsh/).

**Comment by gaearon** [comment]
Any idea what’s going on?

**Comment by gaearon** [comment]
Here's all matches of `placeholder` logic I can find in 15:

https://github.com/facebook/react/blob/571a9208d5133e8737f565fe60b762d201f0d37c/src/renderers/dom/client/wrappers/ReactDOMTextarea.js#L170

https://github.com/facebook/react/blob/571a9208d5133e8737f565fe60b762d201f0d37c/src/renderers/dom/shared/ReactDOMComponent.js#L830-L839 (probably this one?)

**Comment by gaearon** [comment]
@aweary You’ll take this?

**Comment by aweary** [comment]
> (probably this one?)

@gaearon it looks like the same issue, focusing and blurring causes the placeholder to show again, which is the same behavior I saw the first time. Looking into it now.

**Comment by gaearon** [comment]
Can you check if https://github.com/facebook/react/pull/11177 fixes it?

**Comment by aweary** [comment]
@gaearon I was just stepping through it and found that same call site 😄  I verified that is the reason the `textContent` is being set, let me build locally and verify the fix.

**Comment by gaearon** [comment]
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.
