### ISSUE TITLE
Update Performance Optimization Documentation to Reflect React 16

### ISSUE THREAD

**Issue by iammerrick** [facebook/react#11185]
**Do you want to request a *feature* or report a *bug*?**
Bug (Out of date documentation)

**What is the current behavior?**
The [current React documentation](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) talks about a flag `?react_perf`, however, since React 16 it appears this behavior is the new default in development builds. (And with shinier output! Yay!) [This pull request](https://github.com/facebook/react/pull/9071) seems to be where it became the new normal.

**What is the expected behavior?**
I would expect the first step suggesting to add ?react_perf gets deleted. I would also expect the screenshot to reflect the new and improved output, perhaps one of the screenshots from @gaearon'spull request linked above. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16

I am more than happy to make this pull request if my expectation is aligned with the projects. :-)

**Comment by iammerrick** [comment]
I also noticed that "duration" for marks are a consistent "0". Is it expected that duration between steps is computed by subtracting `startTime` ? of React related marks?

**Comment by gaearon** [comment]
Could you please file this in https://github.com/reactjs/reactjs.org?

We don't track doc issues in the main repo anymore.
