### ISSUE TITLE
onMouseEnter lost when hovering over children

### ISSUE THREAD

**Issue by mmellado** [facebook/react#11191]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a `onMouseEnter` event is triggered on an element, the event is lost when the mouse comes over a child rendered based on this event. This didn't happen in React 15, where hovering over the newly created child would persist the event.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

React 15 (expected behavior): https://codepen.io/anon/pen/mBKmzN
React 16 (same code): https://codepen.io/anon/pen/NazjBN

To reproduce, hover anywhere in the red. Then when the menu opens, try to hover anywhere with blue background.

**What is the expected behavior?**
Hovering over the newly created child element should persist the `onMouseEnter` event

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Testes with React 16 on Chrome/Linux (latest Ubuntu Mate), have not tested anywhere else

**Comment by gaearon** [comment]
This the same as #10906 and #11152, and was fixed in https://github.com/facebook/react/pull/11164.
We’ll release a fix soon.

**Comment by gaearon** [comment]
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.

**Comment by mmellado** [comment]
Tested with React `16.1.0-beta`. Seems to be fixed for all my reproducible use-cases :)
