### ISSUE TITLE
Docs for older versions of React are unavailable

### ISSUE THREAD

**Issue by jaredp** [facebook/react#11199]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Documentation for older versions of React have been deleted.  The React documentation website only shows documentation for the current version of React.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**
Documentation for previous versions of React is available somewhere.  Ideally, there's a version picker at the top of the page to select which version of React you're working with, like python.org (for example)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Every version of React before the latest

**Comment by blling** [comment]
The documentation and source code for reactjs.org lives in a different repository: https://github.com/reactjs/reactjs.org

Please open a new issue in that repository. Thanks!

**Comment by jaredp** [comment]
Awesome, thanks!

**Comment by gaearon** [comment]
(And I believe there is already an issue about this there.)
