### ISSUE TITLE
Add warnings on adding functions and components on State.

### ISSUE THREAD

**Issue by davesnx** [facebook/react#11196]
**Do you want to request a *feature* or report a *bug*?**
"Feature"

Hey!

I wanted to add a type check on the state on development, in order to educate.
I saw a couple of times, some codebase that saves Functions or even Components into the state.

I was checking the codebase (for the first time :blush:) and I saw that you check on the `setState` method:

```js
ReactComponent.prototype.setState = function (partialState, callback) {
  invariant(
    typeof partialState === 'object' ||
      typeof partialState === 'function' ||
      partialState == null,
    'setState(...): takes an object of state variables to update or a ' +
      'function which returns an object of state variables.',
  );
  this.updater.enqueueSetState(this, partialState, callback, 'setState');
};
```

You allow functions to be part of the state, I would say that may be wrong and we could warn the developer to not do it. Well... I don't see any case where a function should live inside the state. 

I saw a lot of posts on StakOverflow about putting Components or Functions on the Redux global State. It might be the same conception. 

I want to create a PR in order to address this warning only on development.

What do you think?

**Comment by gaearon** [comment]
It is supported to put functions into React state. There is nothing wrong with this pattern (although it’s not used very often). For example, when doing dynamic loading of code, it is common to store the component in React state.

The check you’re looking at is not relevant to that. It is relevant to `setState(fn)` API which lets you set state *based on previous state*:

```js
this.setState(prevState => ({
  counter: prevState.counter + 1
}));
```

It doesn’t cause functions to be part of the state. (Although again, that is supported as well.)

Hope this explains it!
