### ISSUE TITLE
React error decoder page broken

### ISSUE THREAD

**Issue by ikzjfr0** [facebook/react#11201]
For example, following decode page is broken:
`https://reactjs.org/docs/error-decoder.html?invariant=22`
and this
`https://reactjs.org/docs/error-decoder.html?invariant=109&args%5B%5D=Foo` which is described in https://reactjs.org/blog/2016/07/11/introducing-reacts-error-code-system.html

**Comment by blling** [comment]
The documentation and source code for reactjs.org lives in a different repository: https://github.com/reactjs/reactjs.org

Please open a new issue in that repository. Thanks!

**Comment by gaearon** [comment]
What does "broken" mean? If you don't see the page at all please disable Fair Adblocker. It's known to cause issues with the new website. We'll be fixing that soon.

In any case please file issues in the website repository instead.

**Comment by gaearon** [comment]
(I verified the page displays correctly so it's probably an ad blocker breaking it)
