### ISSUE TITLE
Async componentWillReceiveProps to allow state update

### ISSUE THREAD

**Issue by NeekSandhu** [facebook/react#11224]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
An (almost) immediate re-render is due after `componentWillReceiveProps` is called, unless `shouldComponentUpdate` says otherwise.

**What is the expected behavior?**
If new props in `componentWillReceiveProps` cause an async call that's soon going to update the state anyway, won't it be cool if React might as well wait for that async call to do it's thing (which calls `setState`) and do one render instead of two?

Potential solution: React can see if `componentWillReceiveProps` returns a `Promise`. If it does it defers the re-render until it `resolves`.

```javascript
async componentWillReceiveProps(nextProps) {
    const { postId } = nextProps;
    const postTitle = await fetch(`https://api.example.com/posts/${postId}`);
    this.setState({ postTitle });
    return;
}
```

**Comment by NeekSandhu** [comment]
More than happy to send a PR if this gets a green light.

**Comment by samhunta** [comment]
This would be great. Any updates on this?

**Comment by gaearon** [comment]
If there were updates, they would be on this issue 😉 

We'll be looking at revisiting the component API next year. We’ll look at different feature requests, and also think about our own experience with the existing API. I very much doubt we’ll implement any specific suggestion as described in an issue like this, but we’ll make sure to consider these use cases.

**Comment by gaearon** [comment]
I’ll close this but please feel free to file a more detailed RFC about what you want: https://github.com/reactjs/rfcs
