### ISSUE TITLE
 ReactiveFormsModule like angular4 in react

### ISSUE THREAD

**Issue by webmobiles** [facebook/react#11229]
I'm struggling with forms in react, redux-form library is the only library that can arrive to do what reactive forms in angular4 can do, but have a lot of bugs , and have no all what angular4 reactive form has:

https://angular.io/guide/reactive-forms
`import { ReactiveFormsModule } from '@angular/forms'`

I can control field state  in nice way,

![angular4-control-state-transitions-anim](https://user-images.githubusercontent.com/21120559/31582652-18fc145c-b18a-11e7-8286-ea1e794c5919.gif)

group fields validations,  asyn validations,  and validator librarary included.

is there any library can I can do in react ecosystem? or it's better do build a own library, how i  did with templates, css  ( another libraries have a lot of bugs too or they are in beta mode new versions, example: material-ui,  or not compatible with react 16 , and it's frustating devine the future when they solve the important bugs)

**Comment by chenshuai2144** [comment]
You can look at this
[ant_form](http://ant.design/components/form/#components-form-demo-dynamic-rule)

**Comment by webmobiles** [comment]
@chenshuai2144 thanks, looks nice the design form,  but it's not clear the copyright 
http://ant.design/docs/spec/copywriting

**Comment by gaearon** [comment]
This is a bug tracker for React. Please use community resources for library discussion.
https://reactjs.org/community/support.html

**Comment by chenshuai2144** [comment]
@webmobiles   You can refer to him.He is too big to introduce or increase the size of js.
antd is a library containing redux-form.
this is [license ](https://github.com/ant-design/ant-design/blob/master/LICENSE)

**Comment by webmobiles** [comment]
@chenshuai2144  I've just removed antd library, and my build js decrease from 2.9 Megas to 1.7  definitely I advise do'nt use antd library , it's too much big

**Comment by gaearon** [comment]
A lot of folks reported being happy with https://github.com/jaredpalmer/formik so you might want to check that out.

**Comment by webmobiles** [comment]
@gaearon  thanks; i've complete already my project with redux-form; i like his fieldarray , but i'm going to try formik ,  your advise is very important, thanks
