### ISSUE TITLE
Add Flow Coverage to Renderer Fixture, or use a maintained renderer for tests

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#11220]
The renderer package contains a fixture that has to be updated every time we change APIs. However it is not covered by Flow nor by full test coverage so it is very tedious to make sure you get it exactly right.

I messed it up in https://github.com/facebook/react/pull/11213

Making changes to the API also means updating a lot of renderers at this point. It would be nice if the fixture could be built on top of the Noop renderer or something.

cc @iamdustan @gaearon

**Comment by iamdustan** [comment]
I was wanting to try to generate a `react-reconciler/index.js.flow` file in the distribution as well so that:

* consumers can get flow typechecking of userland renderers
* run `flow` in the fixture file during release. If it fails we know there was a breaking API change.

**Comment by acdlite** [comment]
> It would be nice if the fixture could be built on top of the Noop renderer or something.

👍

**Comment by iamdustan** [comment]
> use a maintained renderer for tests

I could look into this, too. The caveat is that it has to be a renderer with no internal dependencies (which `noop` has).

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/11683 solves this by running bundle tests (which I added) against the real reconciler bundles. (This means ReactNoop CommonJS build is now using the reconciler package.)
