### ISSUE TITLE
keyup event not fired on Firefox for Android

### ISSUE THREAD

**Issue by nicofrand** [facebook/react#11231]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

The keyup event is not fired. When using vanilla JS, there is no issue (https://codepen.io/anon/pen/LzggQW).

**STR:**

1. On an Android smartphone, ensure both autocompletion and autocorrect are enabled
0. Open https://codepen.io/anon/pen/xXyaLe in Firefox for Android (it works on desktop and with Chrome for Android)
0. Type any letter in the input field

**What is the expected behavior?**

For each alphanumeric char typed an alert should be displayed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

* Version used : React 15.6.1
* Browser : Firefox for Android (56+)
* Did this work in previous versions of React : I don't know

**Comment by yanawaro** [comment]
I encountered this bug too, looks like it triggers on all except [a-z].

**Comment by nicofrand** [comment]
> I encountered this bug too, looks like it triggers on all except [a-z].

Yup : the autocompletion/autocorrect is only triggered on alphanumeric chars.
