### ISSUE TITLE
Request to release react 15.6.2 which based on MIT License

### ISSUE THREAD

**Issue by dknc** [facebook/react#11233]
You has updated React license from the BSD + patent License to MIT license, could you release it as 15.6.2? thank you

**Comment by blling** [comment]
It has done.

**Comment by nhunzaker** [comment]
Yep! Take a look at the 15.6.2 blog post:
https://reactjs.org/blog/2017/09/25/react-v15.6.2.html

**Comment by acroyear** [comment]
I'm aware this has technically been done.

However, my company is being VERY particular about the contents of the release package. We're finding that BSD+Patents code is still included in several of the packages even as they're supposed to be MIT. E.g., in react/dist/react.js the BSD+P license header is still above methods like makeEmptyFunction and emptyObject.  Similar cases exist in other dependency packages like create-react-class and prop-types, where methods taken from react or fbjs (code that is now MIT) are still labeled as BSD+P within the .js file. These headers then show up in our .js.map file and therefore are part of our distribution.

Is there some legal document published that we can reference to state and reaffirm that these methods are actually MIT per the root LICENSE file and that the PATENTS clause no longer applies? The contradiction between the root LICENSE and the embedded headers could be seen by some legal analysts as invaliding one or the other (or both).

**Comment by aweary** [comment]
@acroyear those methods are coming from [fbjs](https://github.com/facebook/fbjs/tree/master/packages/fbjs) which was also relicensed as MIT. It looks like the version that 15.6.2 depends on is [is BSD licensed](https://unpkg.com/fbjs@0.8.9/package.json) while the [latest release](https://unpkg.com/fbjs@0.8.16/package.json) is MIT.

I don't know how licensing changes work well to know if this is a problem but maybe @sophiebits can clarify.

**Comment by gaearon** [comment]
I guess we have updated fbjs later than released 15.6.2? In that case let's cut 15.6.3 with it.

**Comment by acroyear** [comment]
The fbjs reference in the npm distros is 0.8.9 or 0.8.12 depending on the npm package (react, create-react-class, and prop-types).

There are npm modules made by 3rd parties for "invariant" and "warning" (taking just those methods out of fbjs or react), which we're still going to have to find a way to override and replace, but that isn't the fault of Facebook that others created those dependencies or are using them in that way. It should be easy to create a one-line exporting module similar to react-addons-perf that exposes just the one method out of the react or fbjs module rather than cloning it.

Thank you for your attention to this.

**Comment by gaearon** [comment]
Closing in favor of https://github.com/facebook/react/issues/11233.
To be honest I'm not sure this release will happen given we're dedicating all effort to 16.x.

But if you can persuade @nhunzaker or @jquense to do this, maybe it will. :-)

If licensing is the only issue you're running into, you can rebuild `dist/react.js` and `dist/react.min.js` yourself from 15.6.2. The underlying npm modules have already been updated to MIT, so rebuilding will give you files that are fully MIT. Or you could use the npm entry point (just `require('react')` and `require('react-dom')` which will use the fully MIT code).

**Comment by acroyear** [comment]
We worked around it by adapting our npm "shrinkwrap" (the npm 4.x predecessor to package-lock.json) to explicitly pull in the MIT-licensed fbjs. Using npm means we're not using the contents of dist but rather the contents of each one's lib folder and webpack packages it from there.

**Comment by gaearon** [comment]
Yep, fair enough!
