### ISSUE TITLE
How to combine theme.breakpoints on React?

### ISSUE THREAD

**Issue by slim-hmidi** [facebook/react#11238]
I need some configuration on my app to be resposnive. For example I used a component SearchIcon from material-ui and I want to adjust it on the screen:

````
style = themes => {
 iconSearch: {
  [theme.breakpoints.up('sm') && theme.breakpoints.down('md')]: {
    margin: 14%
  }
  [theme.breakpoints.up('md') && theme.breakpoints.down('lg')]: {
    margin: 8%
  }
}
````

But this does not take into consideration to make margin 14% when ````min-width=576px ````and ````max-width=768px```` and also for the second option.

I'm using React v15.6.2 and Google Chrome browser

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
