### ISSUE TITLE
React 16 Server Side Rendering client/server mismatched Html differences

### ISSUE THREAD

**Issue by skingston91** [facebook/react#11248]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Migrating to React 16 helped us discover a bug in our code for only Safari/IOS devices where the sort functionality would cause the result to return in a different order compared to node's server response or chrome/firefox. The rendered component is a component with an A tag wrapping an optional image and h2 elements.

In React 15 the components completely re-rendered overriding the <a> tag with the new url from the client. 
In React 16 the client component re-rendered everything inside of the <a> but didn't change the wrapped <a> url. Which lead to links leading peoples to incorrect locations. 

Hopefully that makes sense!
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
I don't know a good way of creating a fiddle for this. However I'll do my best to answer any questions

**What is the expected behavior?**
I would have expected the client side html to have overridden the server side html the same as React 15 did and completely rerender the component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Functionally different from React 15 to React 16. Not sure if what I've listed was intended changes in React 16 which is why I'm raising it to make you aware just incase it is an issue.

**Comment by gaearon** [comment]
Please see the discussion in https://github.com/facebook/react/issues/10591.
This behavior is expected.

We documented it as a breaking change now: https://github.com/reactjs/reactjs.org/pull/116.
Although we should do it more prominently in the future.

**Comment by skingston91** [comment]
@gaearon thanks for the information!

**Comment by gaearon** [comment]
No worries! It is a bit confusing, I agree.

**Comment by skingston91** [comment]
React 16 is now back into production for us and performance has greatly improved, thanks for the great work on it!

**Comment by gaearon** [comment]
Glad to hear that!
