### ISSUE TITLE
Unable to set audio tag attributes

### ISSUE THREAD

**Issue by sgrove** [facebook/react#1124]
This is a limitation of the HTML5/javascript API for `<audio>` tags from what I can see, but maybe React can work around it (like it does to normalize `<textarea>` tags, etc.)

I would like to be able to do something like this pseudo-code:

```
var myAudioTag = React.createClass({
    render: function() {
          return <audio src={this.props.src} volume={this.props.volume} muted={this.props.muted}>
    }
});
```

And have React 1.) pick up on the `muted` attribute change, then 2.) take care of invoking the javascript interface `targetAudioTag.muted = true/false`. Same for attributes `paused`, etc.

**Comment by webdesignermall** [comment]
@sgrove I see that you posted this is 4 years ago, but I also built an MP3 player from React this year and I had the same issue. What worked for me was adding the lifecycle method of componentWillReceiveProps. It solved my issue immediately.

`	 componentWillReceiveProps() {
		this.refs.audio.pause();
		this.refs.audio.load();
		this.refs.audio.play();	
		this.setState((state) => ({
			 showSoundWave:'soundwave'
		}));	
	 }
	 `
