### ISSUE TITLE
"Cannot create property for a non-extensible object".

### ISSUE THREAD

**Issue by volkanunsal** [facebook/react#11240]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

An error is thrown in IE 11. The error message states "Cannot create property for a non-extensible object". It originates from the following location:

File "webpack:///./node_modules/react-dom/lib/PooledClass.js" line 98

**What is the expected behavior?**

No errors.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The version number is react-dom@15.6.1. This used to work, and the error messages started when I implemented DLLPlugin on Webpack, which involved outputting all dependencies in a single file. I'm not sure why that would be a problem, though.

**Comment by gaearon** [comment]
This is not enough information, unfortunately, but I don’t think React is doing anything wrong. I encourage you to investigate this on Webpack side.

It is also likely not a problem with React 16 which doesn’t have that file in the first place.
