### ISSUE TITLE
Apply "files" npm whitelist at build time

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11257]
We should make our build step apply the same logic as npm does with whitelisting `"files"` field. This way issues like https://github.com/facebook/react/issues/11254 would get caught early.

**Comment by apravink** [comment]
Hi I'd like to work on this. Im a beginner and I would appreciate any pointers on where to start

**Comment by gaearon** [comment]
If you run `yarn build` in the repo root, it should start the build process.
The relevant part is [probably here](https://github.com/facebook/react/blob/0e5767824f4c1122e94de61b0392a6942df642ab/scripts/rollup/packaging.js#L184-L192).

You will see that `build/packages/` gets populated with content of npm packages.

I want to make sure that we respect `"files"` entry in `package.json` of each package, and skip files/folders that aren’t in the `"files"` whitelist. This way, if something is missing in `"files"` of package in `packages/*/package.json`, it won’t be copied to `build/packages/*`.

You can check that your change works with this example: https://github.com/facebook/react/issues/11254

```
yarn build -- react-art
```

Before the change, `build/packages/react-art/lib/*` would exist.

After the change, the `lib` folder would not be copied over to `build/packages/react-art/` because it wasn’t in the `"files"` whitelist in `packages/react-art/package.json`.

**Comment by apravink** [comment]
Thanks for that!. That was really helpful!

The solution I am thinking involves parsing the package.json file for each of the packages and comparing the files/directories that are copied over to this parsed array.

Am I on the right track?

**Comment by gaearon** [comment]
Sounds about right.

**Comment by yu-tian113** [comment]
Sorry, didn't mean to hijack the issue from @apravink, was just playing with a possible fix and pushed to my repo :).
Happy to discuss.

**Comment by apravink** [comment]
@yu-tian113 Haven't had a chance to work on this so if you have a working solution, please go ahead :)

**Comment by yu-tian113** [comment]
Thanks for informing @apravink, I'll pick it up then. Please feel free to share any ideas or suggestions.

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/11750.
