### ISSUE TITLE
Add support for schema.org attributes: itemscope, itemtype, itemprop

### ISSUE THREAD

**Issue by terjesb** [facebook/react#1126]
http://schema.org/docs/gs.html

**Comment by rektide** [comment]
Microdata microdata microdata microdata microdata!

Hopefully I can now find this issue when I look for it.

Awh what the heck: rdfa. Even though RDFA is not implemented in React, some kind of useful result  when searching for it would be good too.

Did I mention? Microdata.

**Comment by obedparla** [comment]
Microdata!

**Comment by gaearon** [comment]
React 16 supports arbitrary string attributes now.
