### ISSUE TITLE
New way to bind event handler function

### ISSUE THREAD

**Issue by bgnx** [facebook/react#11263]
Currently there is no way to use event handlers in functional components without performance degradation e.g - unnecessary function recreations through .bind or arrow functions 
```
function Node({node}){
  return (
    <div>
      <button onClick={()=>node.parent.removeChild(node)}>remove</button>
      <div>{node.text}</div>
   </div>
  )
}
```
In this case on each render a new handler will be created, and also react will need to perform some bookkeeping - remove previous handler from dom element and add new handler (ok, with event delegation system react will not touch dom elements and only replace handler somewhere in internal structure but what about events which don't bubble?) and all this take some noticeable time in my application. 
Sure I can change to class components and solve problem by bind handlers only once when component will be created but what if I want to use functional components? 
So in my application I came up with new and fastest method of binding handlers. Actually it does not preform binding at all). What is the reason of binding function in event handler? - we need to access current component props or current component state. Is there another way to get props or state of component? React does not describe this in docs but yes - we can access to props or state of current component without any unnecessary functions recreations on each render.
```
function Node({node}){
  return (
    <div>
      <button onClick={onClick}>remove</button>
      <div>{node.text}</div>
   </div>
  )
}

function onClick(e){
  const {node} = getProps(e);
  node.parent.removeChild(node)
}

function getProps(e){
  return e.target[Object.keys(e.target).filter(k => k.indexOf('__reactInternalInstance') !== -1)[0]]._debugOwner.memoizedProps;
} 
```
and this demo https://codesandbox.io/s/4r59w89lox

To perform event delegations in an efficient way react need to assign current vdom-element to each rendered dom element. And vdom-element has link to actual owner component where we can get our props and state. So why react concealed this from developers and made them suffer not only from performance degradation but also from choosing problem (how many articles and advices recommend or investigate this rule to not bind handlers in render function, and how many solutions exist - use bind in constructor ? - use class field properties with arrow functions ? - use autobind decorators?) ??? And my solution not need even to recreate handlers on each component instantiation like all current solutions does, so it definitely the fastest way. I highly suggest make this api public or make some helper to get current props and state from event.target

**Comment by somonek** [comment]
how about something like this? 

inside your render method
```
<button 
  onClick={this.onClick}
  payload={item}
>
```
and a bound method in your class (with @autobind or in the constructor)
```
onClick(e, payload) {
  payload === item // true
}
```

**Comment by gaearon** [comment]
Your suggestion is extremely fragile so I really hope you’re not using it in practice. It will also give you wrong values in some cases. 

We set up an RFC process for proposed API changes like this. You’re welcome to participate: https://github.com/reactjs/rfcs.

I’ll close this issue but we’d be very glad to see an RFC from you!
