### ISSUE TITLE
Redirect https://reactjs.org/docs/ to first doc page

### ISSUE THREAD

**Issue by tysonwilliams** [facebook/react#11274]
**Do you want to request a *feature* or report a *bug*?**
Bug/broken link in "Thinking in React" section of docs, line 182

**What is the current behavior?**
Broken link. Sends user to "Page Not Found".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**
Go to appropriate link for those who "need help executing this step".

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
Edited the title for potential actionable issue.

**Comment by gaearon** [comment]
Oh wait, that's wrong repo.

**Comment by gaearon** [comment]
Filed https://github.com/reactjs/reactjs.org/issues/180.
