### ISSUE TITLE
Make invalid prop type warnings more specific if they are falsy

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#11289]
This is a common pattern:

```js
<div onClick={condition && () => {}} className={condition && 'foo'} />
```

However if condition is `false`, `0` or `""` then this correctly warns.

You should have used `condition ? ... : undefined` instead.

We could suggest that more specifically in the warning.

The longer term alternative is to use the [proposed](https://github.com/tc39-transfer/proposal-nullish-coalescing) more concise `??` operator.

**Comment by NicBonetto** [comment]
I would like to take this issue on :) Just need a little direction as to where to start.

**Comment by gaearon** [comment]
Run the code above. See the emitted warning. Find it by message in the source. Then you can tweak the message to be more helpful. Does this help?

**Comment by NicBonetto** [comment]
Yes, thank you!

**Comment by Alenkart** [comment]
Hi, I am beginner too. 

I think the warning is located in the line 5724 in the react-dom.development.js  file, correct me if I'm wrong.

```
  if (typeof value === 'boolean') {
      warning$16(DOMProperty_1.shouldAttributeAcceptBooleanValue(name), 'Received `%s` for non-boolean attribute `%s`. If this is expected, cast ' + 'the value to a string.%s', value, name, getStackAddendum$2(debugID));
      warnedProperties$1[name] = true;
      return true;
    }
```

**Comment by NicBonetto** [comment]
That specific file is in your local node_modules directory when you install react-dom via npm or yarn.

**Comment by gaearon** [comment]
Yes. If you search the source code, though, you’ll find it here:

https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js

**Comment by NicBonetto** [comment]
#11300

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/11308.
