### ISSUE TITLE
Jest watching mode seems to unexpectedly cache sources

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11283]
Probably some configuration issue after transitioning to Workspaces but I have to restart the watcher for it to see my changes sometimes.

**Comment by thymikee** [comment]
Looks similar to this https://github.com/facebook/jest/issues/3705.

**Comment by gaearon** [comment]
I don't think I moved any files though.

**Comment by gaearon** [comment]
(When I bumped into this)

**Comment by gaearon** [comment]
Haven't seen this anymore. Maybe I messed something up.
