### ISSUE TITLE
Branch on tag before doing type checking

### ISSUE THREAD

**Issue by clemmy** [facebook/react#11290]
Follow up for https://github.com/facebook/react/pull/10783/files/ab1a58ec0675b34d6eb15854c4b573f2abebe489#r145577198

>  This is neat but it also means that we're sometimes comparing strings to numbers/symbols. That could potentially deopt the type hints in this function. It might actually be better to check the child.tag to ensure that it is a HostComponent or Fragment and compare the type in separate branches.
>
> In fact, that might already be a bug incase we ever add strings to fiber.type on other fibers than HostComponent.

By checking for tags before we do type comparison branches, we can ensure we don't have possible bugs from this, as well as optimize type hints by having monomorphic functions.

**Comment by gaearon** [comment]
The condition now looks like

```js
        if (
          child.tag === Fragment
            ? element.type === REACT_FRAGMENT_TYPE
            : child.type === element.type
        ) {
```

so seems like this was addressed.
