### ISSUE TITLE
Express more tests via public API

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11299]
This is a great contribution opportunity.
We need to rewrite more unit tests in terms of public API.

This means that they can only import npm entry points like `react`, `react-dom`, `react-dom/test-utils`, `react-test-renderer`, etc, but not internal modules like `SyntheticEvent` or `ReactDOMComponentTree`. The “bad” requires are already marked with a TODO in tests so you won’t miss them.

To help with this:

1. Find **`// TODO: can we express this test with only public API?`** in the unclaimed test files below.
2. Comment in this issue if you want to take a particular unit test file, with its name.
3. Submit a PR that rewrites the test to use public APIs instead.

Step 3 requires some thinking. You can use previous examples where we rewrote tests with public API for inspiration. For example:

* https://github.com/facebook/react/pull/10429
* https://github.com/facebook/react/pull/10281
* https://github.com/facebook/react/pull/9080
* https://github.com/facebook/react/pull/8148

Generally, you need to think about how the behavior you’re testing actually reproduces in a React app, and then test for that. In rare cases it may involve exposing some API as public which we’ll need to discuss separately, so don’t hesitate to start a discussion! If you can’t figure out how to rewrite some particular test with a public API, comment here and we can brainstorm.

Here is the full list of tests that need to change. Some of them may be simple one-liner changes, some may involve a bit of a rewrite, some may require rewriting from scratch. Some may even be impossible, but research leading to that conclusion is still very valuable and we’d love to know that.

Try them and let us know:

**Update: all tests are taken now. Subscribe to this issue! They might free up in the future if somebody doesn’t have the time to finish the work. We’ll comment if some test becomes available to try again.**

- [ ] `ReactBrowserEventEmitter-test.js` (taken by @madeinfree, see https://github.com/facebook/react/issues/11299#issuecomment-355188567)
- [ ] `getNodeForCharacterOffset-test.js` (taken by @accordeiro)
- [ ] `ReactErrorUtils-test.js` (taken by @reznord)
- [x] `BeforeInputEventPlugin-test.js` + `FallbackCompositionState-test.js` (taken by @GordyD)
- [x] `validateDOMNesting-test.js` (taken by @anushreesubramani) https://github.com/facebook/react/pull/11742
- [x] <s>`ReactIncrementalPerf-test.js` (taken by @dphurley)</s> https://github.com/facebook/react/pull/11724
- [x] <s>`SelectEventPlugin-test.js` (taken by @skiritsis)</s> https://github.com/facebook/react/issues/11299
- [x] <s>`ReactTreeTraversal-test.js` (taken by @timjacobi) </s> https://github.com/facebook/react/pull/11664
- [x] <s>`SyntheticKeyboardEvent-test.js` + `getEventCharCode-test.js` (taken by @aarboleda1)</s>
- [x] <s>`escapeTextContentForBrowser-test.js` (taken by @jeremenichelli)</s> https://github.com/facebook/react/pull/11331
- [x] <s>`inputValueTracking-test.js` 
- [x] <s>`quoteAttributeValueForBrowser-test.js` (taken by @jeremenichelli)</s> https://github.com/facebook/react/pull/11331
- [x] <s>`ReactDOMComponent-test.js` (taken by @AudyOdi)</s> https://github.com/facebook/react/pull/11337
- [x] <s>`ReactDOMComponentTree-test.js` (taken by @GordyD)</s> https://github.com/facebook/react/pull/11383
- [x] <s>`ReactDOMEventListener-test.js` (taken by @enapupe)</s> https://github.com/facebook/react/pull/11327
- [x] <s>`ReactDOMInput-test.js` (taken by @SadPandaBear)</s> https://github.com/facebook/react/pull/11309
- [x] <s>`ReactDOMServerIntegration-test.js` (taken by @minerado)</s>
- [x] <s>`setInnerHTML-test.js` (taken by @silvestrijonathan)</s> https://github.com/facebook/react/pull/11385
https://github.com/facebook/react/pull/11631
- [x] <s>`getEventKey-test.js` (taken by @mjw56)</s> https://github.com/facebook/react/pull/11317
- [x] <s>`SyntheticClipboardEvent-test.js` (taken by @smaniotto)</s> https://github.com/facebook/react/pull/11365
- [x] <s>`SyntheticEvent-test.js` (taken by @timjacobi)</s> https://github.com/facebook/react/pull/11525
- [x] <s>`SyntheticWheelEvent-test.js` (taken by @douglasgimli)</s> https://github.com/facebook/react/pull/11367
- [x] <s>`ChangeEventPlugin-test.js` (taken by @Ethan-Arrowood)</s> https://github.com/facebook/react/pull/11333
- [x] <s>`EnterLeaveEventPlugin-test.js` (taken by @accordeiro)</s> https://github.com/facebook/react/pull/11316
- [x] <s>`ReactCoroutine-test.js` (taken by @jstejada)</s>
- [x] <s>`ReactFiberHostContext-test.js` (taken by @adsonpleal)</s>

----

**First-time contributor? Refer to our [contribution instructions](https://reactjs.org/docs/how-to-contribute.html).**

**Not clear how to fix a specific test? Comment with what you tried, and we can brainstorm.**

**If you gave up on some test, please post your findings in a comment so we can decide what to do next. It’s fine if you just didn’t find the time or couldn’t figure it out—we can try to help, and maybe somebody else can pick it up later.**

----

**Comment by jeremenichelli** [comment]
I can take a look at this over the weekend and see if I can tackle it in the short term.

**Comment by gaearon** [comment]
Great, thanks! If you pick any particular test, please comment with the filename in the thread so that someone else doesn’t start working on the same test.

**Comment by silvestrijonathan** [comment]
I am definitely very interested in contributing to this. I will look through this weekend and find an opportunity to refactor!

**Comment by SadPandaBear** [comment]
I am interested as well 👍

**Comment by gaearon** [comment]
I published a list of tests in the first post. Just let me know which ones you’d like to take and I’ll assign them to you.

**Comment by SadPandaBear** [comment]
`ReactDOMInput-test` is fine to me :)

**Comment by gaearon** [comment]
@SadPandaBear You got it!

**Comment by reznord** [comment]
I can take a look at `ReactErrorUtils-test`. 😄

**Comment by silvestrijonathan** [comment]
I will take a look at `setInnerHTML-test.js`

**Comment by king0120** [comment]
I'll do `getEventCharCode-test.js`. 😀

**Comment by mjw56** [comment]
I can work on `getEventKey-test.js`.

**Comment by jeremenichelli** [comment]
I can take `escapeTextContentForBrowser-test.js`.

**Comment by Ethan-Arrowood** [comment]
I'd like to give `ChangeEventPlugin-test.js` a shot :)

**Comment by dleitee** [comment]
I can take `SyntheticEvent-test.js`

**Comment by accordeiro** [comment]
I'd like to work on `EnterLeaveEventPlugin-test.js`

**Comment by enapupe** [comment]
I'd like to work on `ReactDOMEventListener-test.js`

**Comment by danilowoz** [comment]
I would like to give `BeforeInputEventPlugin-test.js`

**Comment by aarboleda1** [comment]
I'd like to take SyntheticKeyboardEvent-test.js. Thanks 👍

**Comment by email2vimalraj** [comment]
Let me take `inputValueTracking-test.js`

**Comment by morajabi** [comment]
Lemme take `inputValueTracking-test.js`

**Comment by douglasgimli** [comment]
I'd like to work on `SyntheticWheelEvent-test.js`

**Comment by morajabi** [comment]
Let me take `SyntheticKeyboardEvent-test.js`

**Comment by tranotheron** [comment]
Can I take: ReactBrowserEventEmitter-test.js ?

**Comment by morajabi** [comment]
I'm taking `SelectEventPlugin-test.js`

**Comment by GordyD** [comment]
I'd like to work on ReactDOMComponentTree-test.js

**Comment by gdevincenzi** [comment]
I'd like to work on ReactTreeTraversal-test.js

**Comment by jstejada** [comment]
hi! 👋 I'd like to work on `ReactCoroutine-test.js`

**Comment by smaniotto** [comment]
I can take `SyntheticClipboardEvent-test.js`

**Comment by douglasklein2** [comment]
I'd like to work on `validateDOMNesting-test.js`

**Comment by aqumus** [comment]
I could take EventPluginRegistry-test.js

**Comment by AudyOdi** [comment]
I'd like to try on `ReactDOMComponent-test.js`

**Comment by andrevargas** [comment]
Hello! I'd like to try on `quoteAttributeValueForBrowser-test.js`! :muscle:

**Comment by minerado** [comment]
Hello! I'd like to try on `ReactDOMServerIntegration-test.js` !

**Comment by burnsbeaver** [comment]
I'll do fallbackCompisitionState

**Comment by dphurley** [comment]
I'll take `ReactIncrementalPerf-test.js`

**Comment by burnsbeaver** [comment]
I'll do getNodeForCharacterOffset-test.js

**Comment by gaearon** [comment]
@burnsbeaver Which one is it, `FallbackCompisitionState-test` or `getNodeForCharacterOffset-test`? We'd like to start with one test per person.

**Comment by burnsbeaver** [comment]
getNodeForCharacter please. I deleted the other comment, sorry for the confusion!

**Comment by gaearon** [comment]
We still have `FallbackCompositionState-test.js` and `ReactFiberHostContext-test.js` free!

**Comment by dms1lva** [comment]
I'll take FallbackCompisitionState!

**Comment by adsonpleal** [comment]
I can try the ReactFiberHostContext-test.js

**Comment by gaearon** [comment]
Update: all tests are taken now. Subscribe to this issue! They might free up in the future if somebody doesn’t have the time to finish the work. We’ll comment if some test becomes available to try again.

**Comment by gaearon** [comment]
To all people who took the tests—thank you! I want to reiterate the solution is not always clear, and in some cases it might not even be possible to reasonably test the behavior without some changes to the React source itself. If you ever feel stuck, comment here, and we’ll try to figure out a plan.

**Comment by gaearon** [comment]
@adsonpleal Sorry to disappoint you—I just checked, and unfortunately we accidentally already fixed `ReactFiberHostContext-test`. I didn’t realize this at first, but that TODO is outdated. This is the only test I can see that is already fixed.

**Comment by SadPandaBear** [comment]
@gaearon Wow, refactoring `ReactDOMInput-test` is gonna take me some time but I hope I finish everything this weekend.

**I have a small doubt:** 
Is it ok to repace all that behavior from the function `setUntrackedValue` which uses `inputValueTracking` to something like `ReactTestUtils.Simulate.?` ?

By the way you can check my commit [here](https://github.com/SadPandaBear/react/commit/5ec6f4e9a12ce34871b77908e92d83c107428c92) to see what I did to remove the `inputValueTracking`. I know some of these tests may rely on very specific stuff from `inputValueTracking`, but I was just wondering if `ReactTestUtils` can effectively be used instead.

**Comment by gaearon** [comment]
For `inputValueTracking` @jquense should have the most context on how to do it best. But as long as you get it working, we can review and see if the approach works or not.

**Comment by mjw56** [comment]
Just a heads up to anyone else, I had an older version of yarn installed (0.22) and was trying to run the tests locally and everything was breaking. Upgrading yarn to latest (1.2.1) fixed the issue and tests are running fine now.

**Comment by Ethan-Arrowood** [comment]
@sadpandabear I have the same module in my test file so I'm going to check out your implementation soon

**Comment by silvestrijonathan** [comment]
@gaearon For the `setInnerHTML` tests, they feel like they are dependent upon the existence of `setInnerHTML` for the test suite to make sense.

I can write some tests to replace the existing functions, but then the test suite if more along the lines of setting inner html, vs. anything specific to `setInnerHTML`. Sound okay?

**Comment by gaearon** [comment]
@silvestrijonathan I think what those tests really are trying to verify is that `dangerouslySetInnerHTML` works as expected in React. So if you modify those tests to use ReactDOM and render the same content with `dangerouslySetInnerHTML`, that should be enough. It's fine to rename the test to `dangerouslySetInnerHTML-test` if you feel that would be more appropriate.

**Comment by enapupe** [comment]
After a couple hours playing with my test file I have a strong suggestion for newcomers (like me): start your tests with a clean env (file).
I was editing the existing file and it mocked some internal functions so a few `ReactTestUtils` functions were broken!!  It took me awhile to realize why things weren't working as intended..

**Comment by sebmarkbage** [comment]
@gaearon I think we need to clarify that `ReactTestUtils`, including simulating events, should be considered a private API. That indirectly reaches into internal APIs so it doesn't let us properly test how it would work otherwise. E.g. it'll hamper our ability to test compiled packages without exposing those hooks and it won't let us test a new non-synthetic event system.

**Comment by Ethan-Arrowood** [comment]
@jquense @gaearon my file heavily relies on the inputValueTracking script. How should I adjust the file to no longer use this?

**Comment by jstejada** [comment]
@dphurley, I noticed you're working on `ReactIncrementalPerf-test`. I was also working on a test suite that used `ReactCoroutine`, so I wanted to give you a heads up about this PR: #11338. 
I'm not sure if you've already submitted a PR, but if you haven't, then it might be a good idea to base it off of #11338 (if it's accepted).

**Comment by silvestrijonathan** [comment]
@gaearon Thanks for your advice. I thought about utilizing `React-DOM` with `dangerouslySetInnerHTML` for the tests, so I will go about it that way!

**Comment by gaearon** [comment]
We’ve got first merged PR!

Take a look at it: https://github.com/facebook/react/pull/11309

If you're working on anything related to events, I suggest you to read both the discussions in https://github.com/facebook/react/pull/11309 and reviews in:

https://github.com/facebook/react/pull/11316
https://github.com/facebook/react/pull/11317
https://github.com/facebook/react/pull/11327
https://github.com/facebook/react/pull/11332

There are a few common themes, and it may be valuable to use those discussions to steer other PRs in the right direction.

**Comment by silvestrijonathan** [comment]
Great convos to reference-thanks!

Work got a little busy, but I think I'll be able to get a PR opened up this weekend for my tests.

**Comment by email2vimalraj** [comment]
I'm yet to look into the test that I've picked up. Got busy with other things. I'll try raising a PR in another couple of days, can I buy some time?

**Comment by gaearon** [comment]
Sounds fine, sure!

**Comment by ark9606** [comment]
I had same problem

**Comment by gaearon** [comment]
Another PR merged! https://github.com/facebook/react/pull/11316

**Comment by gaearon** [comment]
One more down. https://github.com/facebook/react/pull/11317

**Comment by gaearon** [comment]
Wrote a small analysis about how I approached one of the tests. https://github.com/facebook/react/pull/11385#issuecomment-341934588

**Comment by sw-yx** [comment]
as far as i can tell they are all taken, please post here if any free up and i'll watch

**Comment by gaearon** [comment]
I merged two more PRs that deal specifically with `SyntheticEvent`s. If you took any related tests, please check them out and try to match in style and approach: https://github.com/facebook/react/pull/11365 and https://github.com/facebook/react/issues/11299

**Comment by aqumus** [comment]
@gaearon For `EventPluginRegistry-test.js`, could you redirect me to some similar sample tests(which uses public API) or guide me to how exactly I could rewrite existing test interms of public API
I had gone through the code and rougly understood that it registers the plugin module and maintains the pluginOrder array but I am not sure how could I test this functionality with the use of public API.

**Comment by aqumus** [comment]
@gaearon For `EventPluginRegistry-test.js`, how should we rewrite test using public API, I see that we are injecting default plugins in ReactDom.js -> ReactDOMClientInjection.js
{
  SimpleEventPlugin,
  EnterLeaveEventPlugin,
  ChangeEventPlugin,
  SelectEventPlugin,
  BeforeInputEventPlugin,
}

So how exactly we could inject our test-mocked plugin and test the `EventPluginRegistry` functionality
I searched for any custom plugin and found [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin) to check how exactly custom plugins are injected.
Is [this](
https://github.com/zilverline/react-tap-event-plugin/blob/f7ed5c560011590d24e07480686b234b2f3ea1f5/src/injectTapEventPlugin.js#L23) the only way to inject plugins 

`require('react-dom').__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.EventPluginHub.injection.injectEventPluginsByName({
    'TapEventPlugin': require('./TapEventPlugin.js')(shouldRejectClick)
  });`

**Comment by gdevincenzi** [comment]
I fear I'm way over my head on `ReactTreeTraversal-test.js`
If anyone else wants to give it a shot, feel free to do so.

**Comment by gaearon** [comment]
@aqumus 

`EventPluginRegistry` is tricky. I guess the first step would be to figure out where it is actually being used. You're right that the tap event plugin is the only one we *sort of* still commit to supporting. Conveniently we have it right in the repo. So maybe we can add a test that it specifically works?

It is also likely that RN uses `EventPluginRegistry`. Do we have any tests verifying RN events work? I don't know. It's worth commenting out different parts of `EventPluginRegistry` and looking if any tests fail. We can remove its private API tests if the same code is already covered by other tests that happen to stress those code paths. Does this make sense?

@gdevincenzi Sounds good, I'll remove the assignment.

**Comment by gaearon** [comment]
Also, I'm going to be away this week, but please don't let this stop you from continuing on this. Hope to get a few more submitted PRs merged next week.

**Comment by sw-yx** [comment]
i can take `ReactTreeTraversal-test.js` - its an unfamiliar API but seems like a good opp to learn it. advice welcome @gdevincenzi

**Comment by gaearon** [comment]
Congratulations to @gordyd for finishing a rather complex one: https://github.com/facebook/react/pull/11383.

This is a good example of how different the code can look before and after while testing essentially the same things. And how you can figure out *what* the code is supposed to be doing by searching for references, looking at git history, and commenting out different lines.

**Comment by gaearon** [comment]
We have not received a PR yet from the following users:

@email2vimalraj
@andrevargas
@tranotheron
@minerado
@sw-yx
@king0120
@aarboleda1
@danilowoz
@dms1lva
@morajabi
@dphurley
@reznord
@aqumus

Could you please confirm if you started work on this? I have more people who want to help in the queue, so if you don’t have the time, it would be great to give others an opportunity to work on this.

**Comment by gaearon** [comment]
@andrevargas Just noticed your discussion in https://github.com/facebook/react/pull/11331. I guess it makes sense to keep those changes unified there.

**Comment by timjacobi** [comment]
Please add me to that queue @gaearon

**Comment by andrevargas** [comment]
@gaearon Yes, you're right. Just to confirm, @jeremenichelli is working on `quoteAttributeValueForBrowser-test.js` in #11331, and I'm aware of this. I think you can update this thread with his username and PR's link.

**Comment by kwnccc** [comment]
Please also add me to the queue @gaearon

**Comment by dphurley** [comment]
@gaearon I have started working on it. Planning on either posting my findings or a PR sometime this week.

**Comment by aarboleda1** [comment]
@gaearon I have begun working on SyntheticKeyboardEvent.js. Planning to have a PR up this weekend.

**Comment by skiritsis** [comment]
@gaearon I could also take up any of the tests in case the people that were originally assigned don't have the time required to work on them.

**Comment by morajabi** [comment]
@gaearon Sorry for the long delay, I'm making a WIP PR now.

**Comment by reznord** [comment]
@gaearon Sorry for the long delay 😅. I will be working on this today and will ping you if I have some doubts regarding that.

**Comment by timjacobi** [comment]
@morajabi one potential way to tackle this
* Look at `SelectEventPlugin` and understand which functionality is provides to the user
* Write code that makes use of that functionality
* Disable loading `SelectEventPlugin` (comment it out) and see what breaks
* The code you've written is now the first version of your test so you can put it in a test case
* Enable loading `SelectEventPlugin` again and make sure the test passes
* Optimise your code

**Comment by aqumus** [comment]
@gaearon apology for delay
based on your suggestion, I did tried commenting few parts of `EventPluginRegistry.js` and found alot of test cases failing (`SyntheticWheelEvent`, `ReactDOMComponentTree`, `SyntheticClipboardEvent`, ` SyntheticWheelEvent`, `inputValueTracking`, `SimpleEventPlugin`, `ChangeEventPlugin`, `ReactDOMComponentTree` etc),
I guess mainly because `ReactBrowserEventEmitter.js` uses `registrationNameDependencies` which is defined in  `EventPluginRegistry.js`

Although when commenting out 
* [line 208](https://github.com/facebook/react/blob/master/packages/events/EventPluginRegistry.js#L208)
* [line 38-41](https://github.com/facebook/react/blob/master/packages/events/EventPluginRegistry.js#L38-L41)

none of the test cases failed (only `EventPluginRegistry` test failed)
Based on this I guess `EventPluginRegistry` is already covered by other test suites.

> [Conveniently we have it right in the repo. So maybe we can add a test that it specifically works?](https://github.com/facebook/react/issues/11299#issuecomment-343974471)

I didn't understood what you meant by this

Is there any other suggestion I could work on to rewrite  `EventPluginRegistry` using public API?

**Comment by danilowoz** [comment]
Sorry @gaearon I tried to do, but now I don't free time to finish it 
So if anyone else wants to get my issues, feel free :)

**Comment by skiritsis** [comment]
@danilowoz @gaearon If you do not mind I could take BeforeInputEventPlugin-test.js.

**Comment by morajabi** [comment]
@timjacobi What is the replacement for `ReactDOMComponentTree.getInstanceFromNode`?

**Comment by timjacobi** [comment]
@morajabi I'm not sure you're tackling this at the right level. Could you open a WIP PR with what you have so far? I don't want to pollute this thread too much.

**Comment by morajabi** [comment]
@timjacobi I can't when I haven't committed anything new. I'm sorry I'm pretty busy these days if someone can take `SelectEventPlugin-test`.

**Comment by gaearon** [comment]
It seems like we no longer need `ReactDOMServerIntegration-test` (cc @minerado) as I have covered it together with other changes.

**Comment by gaearon** [comment]
@aqumus Based on your analysis I'll remove `EventPluginRegistry-test.js` from this list. I think we'll keep this as a unit test of those particular internals, but it's good to know actual logic is covered by other tests.

**Comment by gaearon** [comment]
@king0120 I'll reassign `getEventCharCode-test` to @aarboleda1 because he's working on a very related test in https://github.com/facebook/react/pull/11631, and it might be easier to do them together.

**Comment by skiritsis** [comment]
@timjacobi @gaearon I could take a look at SelectEventPlugin-test.js as well.

**Comment by gaearon** [comment]
@email2vimalraj FYI, I rewrote `inputValueTracking-test`.

**Comment by gaearon** [comment]
These tests don't currently have an owner:

- [ ] `ReactBrowserEventEmitter-test.js` (5/5)
- [ ] `BeforeInputEventPlugin-test.js` + `FallbackCompositionState-test.js` (5/5)
- [ ] `ReactTreeTraversal-test.js` (4/5)
- [ ] `getNodeForCharacterOffset-test.js` (3/5)
- [ ] `SelectEventPlugin-test` (2/5)

I sorted them by my perception of their difficulty.

We have a queue with @timjacobi @kwnccc @skiritsis so please could the three of you let us know if you'd like to take any of these tests (please specify which one). You can also pass, and we'll let somebody else try.

Note that these are getting pretty complicated, so they're not exactly beginner-friendly. You should be comfortable researching things on your own, similar to how @GordyD did in https://github.com/facebook/react/pull/11383. In fact if @GordyD would like to take any of these I'd be happy to give him one!

**Comment by gaearon** [comment]
@skiritsis Since you were interested I'll reassign `SelectEventPlugin-test` to you.

**Comment by madeinfree** [comment]
I'd like to work on ReactBrowerEventEmitter-test.js 💪

**Comment by email2vimalraj** [comment]
@gaearon: Thanks for that, sorry for not responding on time. Got busy with other work. I'll look into how you rewrote for my understanding.

**Comment by timjacobi** [comment]
I can take a look at `ReactTreeTraversal-test.internal.js`

**Comment by gaearon** [comment]
@madeinfree Let's give a few days to @kwnccc to reply first since he's already in the queue. If he's not interested, I'll assign it to you later.

**Comment by madeinfree** [comment]
@gaearon OK! got it, thank you ~

**Comment by GordyD** [comment]
@gaearon I'll take a look at combining `BeforeInputEventPlugin` + `FallbackCompositionState` if there are no other takers.

**Comment by gaearon** [comment]
Sounds good, thanks @GordyD!

**Comment by gaearon** [comment]
By the way, here's a few more event tests that got converted, to give you an idea of what this code usually ends up being like: https://github.com/facebook/react/pull/11631 https://github.com/facebook/react/pull/11525

**Comment by timjacobi** [comment]
@gaearon I'm happy to take `ReactBrowserEventEmitter-test.js` as well if no one else wants it.

**Comment by gaearon** [comment]
@madeinfree

Are you still interested in `ReactBrowerEventEmitter`? If so, please take it and keep us updated!

**Comment by madeinfree** [comment]
@gaearon OK! I would like to take it.

**Comment by gaearon** [comment]
You got it.

Anybody want to take the remaining `getNodeForCharacterOffset-test`?

**Comment by accordeiro** [comment]
I can help with this one :)

**Comment by dphurley** [comment]
@gaearon Haven't found the time to dive into `ReactIncrementalPerf-test.js` like I thought I would. Apologies for hanging on to it for so long but it's up for grabs if anyone wants it!

**Comment by gaearon** [comment]
@accordeiro You got it!

**Comment by kwnccc** [comment]
@gaearon really sorry, didn't get notified. If there are still some tests to take care of please let me know. I hope there has been left something easy to start with.

**Comment by gaearon** [comment]
@kwnccc Wanna look into `ReactIncrementalPerf-test.js`?

**Comment by abiduzz420** [comment]
Can I look into `ReactIncrementalPerf-test.js` ? Or if needed I can help @kwnccc out in writing test for it

**Comment by abiduzz420** [comment]
If I have clearly understood the issue in `ReactIncrementalPerf-test.js`, it means I need to switch from ReactPortal.createPortal(...) to ReactDOM.createPortal(...) ? @gaearon

**Comment by kwnccc** [comment]
@gaearon I'd really like to try `ReactIncrementalPerf-test.js`. Since @abiduzz420 has started checking it out we could even team up if needed.

**Comment by abiduzz420** [comment]
Yeah sure @kwnccc  I'm happy to work with you. You were in queue before me, so all yours!

**Comment by abiduzz420** [comment]
@kwnccc I'm getting Flow error when I run `yarn flow`.

**Comment by gaearon** [comment]
@abiduzz420 The flow issue is a known problem on Windows. It's unrelated (but we'll need to figure out why it happens). See https://github.com/facebook/react/issues/11703.

@kwnccc As for `ReactIncrementalPerf-test`, yes this will require some thought. I think maybe at this point it's best to temporarily move `ReactPortal` to `shared`. Then have `ReactNoop` provide its own `createPortal()` method (like `ReactDOM` does).

**Comment by gaearon** [comment]
One more down! https://github.com/facebook/react/issues/11299

**Comment by madeinfree** [comment]
Hi, @gaearon
I have a question from ReactBrowerEventEmitter-test 😣, is the `events/EventPluginHub` kind of public API ? when I want to test `onClick` is store correct in instance, if I didn't use `EventPluginHub.getListener(inst, eventName);` and change it like
```javascript
var node;
node = ReactDOM.render(<div onClick={LISTENER} />, container)

// and test but I don't want to call the onclick event, just check it was existed

expect(node.onclick).toBeDefined();
```
is this the correct thought ? thank you ~~

ref: https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactBrowserEventEmitter-test.internal.js#L152

**Comment by abiduzz420** [comment]
@gaearon I have moved ReactPortal to shared directory, and all the tests pass. Need a bit of assistance in implementing my own method `createPortal()` for `ReactNoop`. Taking inspiration from how `createPortal()` is written in `ReactDOM` I shall return `ReactPortal.createPortal(children,container,null,key)`. 
Parameters to `createPortal()` would be `children: ReactNodeList, container: Container, key: ?string = null`
Please let me know if I'm doing it right ?

**Comment by anushreesubramani** [comment]
@gaearon My code is still a wip. But I wanted to double check if I am on the right track. It would really help me if you could take a quick look at my code and clarify few doubts:
1. Is the approach I have taken correct?
2. I assume the tests need to cover all the tags and scenarios that are tested in the existing
 tests in order to maintain test coverage. I am not sure if there is a way to generate components dynamically with these special and formatting tags. Can you give me some pointers on an efficient way to achieve this? 
3. I am not sure how to test the 'no context' part of the 'any tag no context' test with public API because the method isTagValidInContext() is not used in anywhere else except in the test file. Any ideas?

**Comment by gaearon** [comment]
@abiduzz420 Yes this sounds right

**Comment by gaearon** [comment]
@anushreesubramani 

>Is the approach I have taken correct?

In general, yes, but we'll want to avoid duplication there. Ideally it should turn from a series of 

```js
expect(isTagStackValid(['a', 'a'])).toBe(false);
```

to a series of

```js
expectInvalidNestingWarning(true, ['a', 'a']);
```

where `expectInvalidNestingWarning` is a custom function that generates the component and then asserts that rendering it produces a warning.

>I am not sure if there is a way to generate components dynamically with these special and formatting tags. Can you give me some pointers on an efficient way to achieve this?

Yes, I'm thinking something like:

```js
function expectInvalidNestingWarning(shouldWarn, tags) {
  let element = null;
  tags = [...tags];
  while (tags.length) {
    element = React.createElement(tags.pop(), null, element);
  }
  const container = document.createElement('div');
  ReactDOM.render(element, container);
  // assert either a warning or lack of one based on shouldWarn
}
```

We go through the array, take the last item, and wrap the current element into a parent with the corresponding tag. This way by the end we end up with the corresponding tree. I may have written something wrong but that's the general idea.

You'll also probably want to put something like 

```js
jest.resetModules();
React = require('react');
ReactDOM = require('react-dom');
```

in that function right before rendering because otherwise the warnings can be deduplicated and we can't reliably test them.

>I am not sure how to test the 'no context' part of the 'any tag no context' test with public API because the method isTagValidInContext() is not used in anywhere else except in the test file

Looking at the blame, it was added in https://github.com/facebook/react/commit/76bb96ef21b7c665e1b51b6bb90e64ec40c0f16a and at that point it was called outside of tests too. But at some point in the future it was no longer used. The test mentions  sever rendering:

https://github.com/facebook/react/blob/8cbc16f0faedafe4f7424b286af52dafd7a79587/packages/react-dom/src/__tests__/validateDOMNesting-test.internal.js#L144-L145

but this function is no longer used with server rendering either.

From this comment I gather that the goal is to ensure we never warn *when we don't know the ancestors*. However, I can't find a code path that would pass `null` as `ancestorInfo` to `validateDOMNesting`. Therefore we probably always know the ancestors in the current version. So I'd say it's safe to delete this test altogether.

**Comment by gaearon** [comment]
Can you send a PR please? It's easier to discuss in a review.

**Comment by kwnccc** [comment]
@abiduzz420 You seem to have done a great job, sorry but I didn't have the time to start working on that before today! Really glad you were able to complete the test! 👏👏

**Comment by GordyD** [comment]
@gaearon quick update: I've begun refactoring/combining BeforeInputEventPlugin + FallbackCompositionState. I've got a good handle on how to test the implementation through the public API. I'm now working through creating test cases to exercise the different code paths dependent upon the different execution environments/browser engines. I expect to have a first PR up towards the end of this week.

**Comment by gaearon** [comment]
Nice, thanks for the update!

**Comment by accordeiro** [comment]
@gaearon quick update on my end: I've already started working on rewriting the tests for `getNodeForCharacterOffset-test` and should be able to push a PR until Thursday – is this ok?

**Comment by gaearon** [comment]
Sounds good

**Comment by gaearon** [comment]
One more down! https://github.com/facebook/react/pull/11742

@reznord We haven't heard from you yet—did you start anything? If you're too busy maybe it's better to give someone else a chance to try.

**Comment by gaearon** [comment]
Ping @reznord

**Comment by vikramcse** [comment]
Hi @gaearon, Can I take `ReactErrorUtils-test.js` for my first contribution?

**Comment by vikramcse** [comment]
hi, @gaearon  is there something that I can do in `ReactErrorUtils-test.js`

**Comment by madeinfree** [comment]
Hi, Does anyone can help me to continue the ReactBrowserEventEmitter-test.js test ? Because I'll busy on my working now no time to keep going, the PR is https://github.com/facebook/react/pull/11713, thank you so much !!

**Comment by vikramcse** [comment]
@madeinfree I will take `ReactBrowserEventEmitter-test.js`.

**Comment by gaearon** [comment]
Thanks to everyone again! There are still a few outstanding tests but I think we can close it.

**Comment by abhaynikam** [comment]
@gaearon : `ReactErrorUtils-test.js` I would like to work on it. can you confirm if I can pick that up?
