### ISSUE TITLE
Add `code` property to `SyntheticKeyboardEvent`

### ISSUE THREAD

**Issue by jacobcarpenter** [facebook/react#11306]
**Do you want to request a *feature* or report a *bug*?**

Improvement

**What is the current behavior?**

[`SyntheticKeyboardEvent`](https://github.com/facebook/react/blob/e779c39dfeb41ae8f6611dc4f9830d1b1ac64f9b/packages/react-dom/src/events/SyntheticKeyboardEvent.js) does not currently support the `code` property.

`code` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)) is nice to have when you want to write key-specific handling—rather than input-specific (dependent on layout and modifier keys) handling.

**What is the expected behavior?**

`SyntheticKeyboardEvent` already exposes a `keyCode` property. It should have a `code` property as well.

Currently, if you want to use the `keyboardEvent`'s  `code`, you must access it through `SyntheticKeyboardEvent`'s `nativeEvent`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Affects React 16 and earlier (I assume).

**Comment by flaviolivolsi** [comment]
I created the PR #11325 for this.

**Comment by thisizkp** [comment]
the above PR #11325 is stale and closed; should I pick this up? planning to replicate the same and follow the PR suggestions; any tips or idea?

**Comment by gaearon** [comment]
Can you give me an idea of how widely supported it is?

**Comment by lukaszgolder** [comment]
@gaearon According to https://caniuse.com/#feat=keyboardevent-code it is supported in all major desktop browsers. Are there any plans to implement this? I am not sure whether I should mark is with `$FlowFixMe` until this issue is resolved or don't use it at all.
