### ISSUE TITLE
Strict ordering of commitUpdate()?

### ISSUE THREAD

**Issue by dakom** [facebook/react#11319]
How exactly is the order of `commitUpdate()` calls related to the structure of the tree? (_note: for this question I am only asking about `commitUpdate`, not `prepareUpdate`_)

For example, in the following:

- 1
  - 1_A
    - 1_A_a
    - 1_A_b
  - 1_B
    - 1_B_a
    - 1_B_b
- 2
  - 2_A
    - 2_A_a
    - 2_A_b
  - 2_B
    - 2_B_a
    - 2_B_b

There's several ways it could be rendered, if there is a strict relationship (which I'm assuming there is)... I don't know the technical terms for these difference, though feel free to use them and I'll look 'em up :)

Here are some examples, again sorry for using made-up terms

Example 1 - bottom-to-top:

[2_B_b] [2_B_a] [2_B] [2_A_b] [2_A_a] [2_A] [2] [1_B_b] [etc.]

Example 2 - bottom-to-top-per-level:

[2_B_b] [2_B_a] [2_A_b] [2_A_a] [2_B] [2_A] [2] [1_B_b] [etc.]

Example 3 - top-to-bottom:

[1] [1_A] [1_A_a] [1_A_b] [1_B] [1_B_a] [1_B_b] [2] [etc.]

Example 4 - top-to-bottom-per-level:

[1] [2] [1_A] [1_B] [2_A] [2_B] [1_A_a] [1_A_b] [1_B_a] [1_B_b] [2_A_a] [etc.]

This also prompts another related question - is commitUpdate for each element guaranteed to happen _after_ all the children are adjusted?

**Comment by sebmarkbage** [comment]
> is commitUpdate for each element guaranteed to happen after all the children are adjusted?

Yes. This is a pretty important guarantee.

Example 1 is closest but we do siblings first->last instead of last->first, I think.

The correct order should be:

[1_A_a] [1_A_b] [1_A] [1_B_a] [1_B_b] [1_B] [1] [2_A_a] [etc.]

However, the best authoritative answer is to just test it yourself and see what happens since these things change in subtle ways sometimes. :)

**Comment by dakom** [comment]
@sebmarkbage just a heads up, from a super quick rough test the order you described is exactly right :)

Is there a specific name for this I can lookup when searching?
