### ISSUE TITLE
Adding support for component factories in "createElement" etc.

### ISSUE THREAD

**Issue by mcjazzyfunky** [facebook/react#11313]
Problem:
Let's assume you are implementing a component suite providing some dozen superfancy ready-to-use components for React users.
However, you do not know whether the users of your library are preferring JSX or normal JavaScript.
In the non-JSX case, most users surely want to write:

```javascript
FancyButton({ text: 'Click me' })
```
instead of

```javascript
React.createElement(FancyButton, { text: 'Click me' })
```
So far, for non-JSX users, providing a component as a component factory seems to be the better solution, whereas JSX users would surely prefer the component class itself (as "createElement" does not support component factories yet).
This is not very convenient. The component suite provider has to decide whether the components shall be provided as factories or as classes (respectively "render functions" in case of stateless functional  components) or whether she/he should always provide both versions at once.

Feature request:
Why not promote component factories to first-class citizens in the React world (instead of downgrading them to "legacy" as currently planned) and make sure that functions like "createElement" etc. will support component factories at the same level as component classes (respectively "render functions" in case of stateless functional  components) are supported currently?

BTW: By having access to the component factory you also have access to the component class/function via "factory.type" (which is considered "deprecated" by the React team - I do not know why, because "factory.type" seems very helpful). 

Here's a little example:
https://jsfiddle.net/nse64ev9/

Many thanks in advance

**Comment by gaearon** [comment]
`React.createFactory` is not deprecated, but I think you’re not using it correctly.

We intentionally don’t want people to wrap components in factories *at definition time* (as you did) because it is unnecessary. This, and the set of problems we were solving, was described during the 0.12 release: https://gist.github.com/sebmarkbage/d7bce729f38730399d28.

You can, however, wrap things in factories *at import time*. Here is a fixed example that does what you want and doesn’t print any warnings: https://jsfiddle.net/1d0e3zov/

Yes, it’s a bit more typing, but it solves the problems introduced by that extra wrapping such as more difficult testing, confusing type systems, and always having to wrap exports.

**Comment by mcjazzyfunky** [comment]
Thank you very much, Dan, for the information you gave.
I'm perfectly fine with mostly everything that is written there, but:

#### First:
If you have a component factory "factory" and accessing "factory.type" is allowed to retrieve the React custom component class then (of course) everything you can do with the React custom component class can also be done with "factory" (by using "factory.type"). In that sense, such a component factory is a bit more powerful than the component class itself, as it can also be used directly without the explicit need of "createElement".

#### Second: 

It seems that the React team does not consider "createFactory" that important:

- See the following React warning: "Factory.type is deprecated. Access the class directly before passing it to createFactory."

- https://reactjs.org/docs/react-api.html#createfactory says "[...] is considered legacy [...]"

- In several issues and wish lists you can read things like: "React.createFactory will be moved to a separate package" etc.

#### Third:
Let me just simplify my feature request as follows:


1. Please let "createFactory" (including the 'factory.type' property) remain in the main React module, without labeling it "legacy" or "deprected":

```javascript
const factoryTag = Symbol('isReactFactory');
// if you prefer: const factoryTag = '__$$isReactFactory';

function createFactory(type) {
    const factory = createElement.bind(null, type);
	
    factory.type = type;
    factory[factoryTag] = true;

    return factory;
}
```

2. if you like, add:

```javascript
function isFactory(it) {
    return typeof it === 'function' && it[factoryTag] === true; 
}
```
3. Please let "createElement" support factories directly (even if this seems kind of "unnecessary" in canonical React programming - it may be not so "unnecessary" in other cases, like the one in the remark stated below):

```javascript
const FancyButton = createFactory(...);

<FancyButton text="Click Me" />
```

#### Remark:

Maybe it helps a bit to tell what's the concrete reason for my feature request:

I think, what the JavaScript UI world is really missing is some kind of UI library abstraction API, for example to implement a date-picker in a library-agnostic way and use it later directly as React component or Vue component or whatever depending on your SystemJS or Webpack configuration (=> package/module alias/mapping) (btw: something like W3C custom elements or Onsen UI is not what I mean)

At least for "virtual DOM" based UI libraries such an abstraction API could look like follows:

- Function "createElement" to create a virtual DOM node (signature the same as in React)
- Function "isElement" to check whether something is a proper virtual DOM node.
- Function "mount" to mount/render a virtual DOM tree to a real DOM element (as "ReactDOM.render")
- Function "defineComponent" (to define actual component types - to be discussed below)
- ... and maybe some more functions ...

Forget about the concrete argument(s) of function "defineComponent", what's more interessting here is the the question:
What exactly does the function "defineComponent" return?

Does it return a class?
No, because who says that the underlying component system is object-oriented/class-based, so why should it return a class? At the end of the day, concrete classes or whatever are just implementation details.

The correct answer is:
It returns a component factory. The return value of the component factory will be a virtual DOM element that represents a concrete component (not important here, but "factory.meta" could give access to some meta information about that component type, like supported properties etc.).
Ideally, the returned component factory is supported directly in the "createElement" counterpart of the underlying UI component system (in case such a counterpart is actually existing).
Because then the component types represented by the component factory could also be used directly in JSX (without the inconvenience of unwrapping things). Everything feels very "natural".
This is exactly the reason for my feature request described above.
In rare cases where the concrete component type representation of the underlying UI library (for example the concrete React component class) is really needed, it can be retrieved by "factory.type".

**Comment by gaearon** [comment]
Since you're creating a higher level wrapper, you might as well provide your own `createFactory()` that provides these semantics.

**Comment by mcjazzyfunky** [comment]
Thanks @gaearon for your answer.
But unfortunately "createFactory" will not do the job:
The desired logic (to support all the three cases: Component class constructor, simple component function and component factory)  has to be in the "createElement" function and nowhere else.
Of course there will be a "createElement" wrapper that will do that that job (besides a bunch of other stuff).
But if you want to use JSX, then you have to use that "wrapping" (and some kind of alien) "createElement" counterpart instead of React's own "createElement" as JSX's "pragma" value in "transform-react-jsx" - which is a complete no-go, because the main reason for the above described "UI library abstraction" is to provide a way to implement base components (like ComboBox or DatePicker etc.) in a UI-library-agnostic way to be used later by some other programmers as "real" React components or "real" Vue components (depending whathever those "other programmers" prefer) without having to know anything about that "alien" wrapper library that has been used to implement those given UI-library-agnostic components.

To make a long story short:
Of course it's technically no problem to export both representations of the same component at once: As React class constructor and also as React factory, so the user has to decide on "import" what version she wants to have - but nevertheless this makes things unnecessarily confusing.
Anyway, if Facebook does not - for whatever reasons - want to add direct support for React factories in React's "createElement" function, then that's okay, of course - just close this Github issue and I will go with the above mentioned workaround. But frankly, I would not understand the big deal: Adding support for React factories in React's "createElement" function is easy to implement and would make React much more flexible, surely useful in many use cases, besides it kinda feels very "natural" to use component factories as main component representations.

**Comment by gaearon** [comment]
I’m sorry if I’m being frustrating. I’m skeptical of your goal of completely agnostic components. There are still React-specific concepts like refs and keys that may not directly map to how Vue and others work. So I think you’ll still want more control over time.

The custom pragma doesn’t have to “feel alien”. It can be specified once as a Babel plugin option. Or you can even tell your users to “alias” React to your own package like Preact does. I feel like those are better solutions for you.

I understand it seems to you it’s not a big deal to add support for this. But to us, committing to support something means taking a large burden. Especially if it’s something that’s used for a tiny minority of cases. How `createElement()` works may need to be coded into other tools, e.g. an optimizing ahead-of-time compiler. Even small additions like this can make such optimizations harder, impossible, or impractical.

If you still feel strongly I encourage you to file an RFC: https://github.com/reactjs/rfcs.
