### ISSUE TITLE
Example links in react-reconciler README are broken

### ISSUE THREAD

**Issue by leoselig** [facebook/react#11310]
Reporting this since it says _"If these links break please file an issue and we’ll fix them. They intentionally link to the latest versions since the API is still evolving."_ and knowing the place of the most up-to-date examples would help me a lot.
The issue template does not really fit here but I'm trying to follow it anyway.

-------------

**Do you want to request a *feature* or report a *bug*?**
Bug (In a README)

**What is the current behavior?**
In https://github.com/facebook/react/tree/master/packages/react-reconciler there are 3 links to reconciler configuration examples of `react-dom`, `react-art` and `react-native`.
All 3 links are broken

https://github.com/facebook/react/blob/master/packages/react-native-renderer/src/ReactNativeFiberRenderer.js

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
Just visit the [`react-reconciler/README.md`](https://github.com/facebook/react/blob/master/packages/react-reconciler/README.md)

**What is the expected behavior?**
Correct links
I wanted to fix these in a PR but could only find an appropriate replacement for react-native here: https://github.com/facebook/react/blob/master/packages/react-native-renderer/src/ReactNativeFiberRenderer.js

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Issue exists on `master`-branch

**Comment by gaearon** [comment]
The other ones are called just ReactDOM and ReactART. Please submit a PR.
