### ISSUE TITLE
SSR result render in browser incorrectly

### ISSUE THREAD

**Issue by thundernet8** [facebook/react#11314]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

dangerouslySetInnerHTML render html string to real document well, if under a server side render environment, the return rendered html was right, but browser side will render and sanitize all html tags of content between `<pre><code>` and `</code></pre>`

for example, we have a html string:
```
<pre><code><span class="token keyword" style="color: red">return</span> $ordered_posts<span class="token punctuation">;</code></pre>
```
we use ssr server to render this to real html, and right result return from the server, the document will be replaced with `<pre><code>return $ordered_posts;</code></pre>` after browser rendering, the most difference is that all <span> tag were removed. Is this a normal behavior for React? I'm not sure.

[No SSR Right Demo](https://jsfiddle.net/dnntL0kc/)

**What is the expected behavior?**
After browser got the ssr html and render, the tags between `<pre><code>` and `</code></pre>` should not be removed

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.0.0
Chrome/61.0.3163.100
MacOS 10.12.6

no try be done on previous version of React

**Comment by gaearon** [comment]
Can you provide a complete example? Since it tests server rendering, your example should also use server rendering.

**Comment by thundernet8** [comment]
@gaearon 
Hi, I found the point which result in this issue, if I import `draftjs-to-html` package or any module file who import this package, it will cause this even though it not be called. Sorry about this, and pls close this issue. Thanks.
