### ISSUE TITLE
[CLI] Webpack Templates through CLI for consistency in boilerplate and learning ease!

### ISSUE THREAD

**Issue by IamManchanda** [facebook/react#11324]
Just like https://github.com/vuejs-templates/

**Comment by blling** [comment]
Do you mean [create-react-app](https://github.com/facebookincubator/create-react-app) ?

**Comment by gaearon** [comment]
Not sure what the issue is about, but you can indeed use Create React App which is officially supported.

**Comment by IamManchanda** [comment]
I mean built-in webpack specific template(s)

This kind of a thing (Hope you are understanding?)
https://github.com/vuejs-templates/webpack/blob/develop/template/package.json
https://github.com/vuejs-templates/webpack/tree/develop/template/build

Some React examples:
https://scotch.io/tutorials/setup-a-react-environment-using-webpack-and-babel
https://github.com/StephenGrider/ReduxSimpleStarter

---

@gaearon Would request you to reopen the issue if this makes sense!

**Comment by gaearon** [comment]
CRA uses webpack under the hood. If you `eject` you'll get a typical webpack boilerplate, if that's what you want.

Does this make sense?

**Comment by IamManchanda** [comment]
@gaearon Nice just checked .... thankyou 
Actually coming from Vue learning React so didn't knew about it!

That said, there is no such mention in the docs for same?
That need to change for sure. Does that make sense?

**Comment by IamManchanda** [comment]
@gaearon Knock Knock!

> **That said, there is no such mention in the docs for same?
That need to change for sure.**
