### ISSUE TITLE
Get React to full Flow coverage

### ISSUE THREAD

**Issue by VladBlow** [facebook/react#11328]
After our dialog with @gaeron in [#11323](https://github.com/facebook/react/pull/11323) I want to update typings for all package React, but I think I need help by community.

**Comment by VladBlow** [comment]
- [ ]

**Comment by VladBlow** [comment]
I think I can start with small fixes in PR [#11329](https://github.com/facebook/react/pull/11329).

This is my first experience of contributed in React and I want to understand structure and approaches in development.

cc @gaearon

**Comment by VladBlow** [comment]
Maybe we can compose task list for files/function which need typings?

**Comment by gaearon** [comment]
We have a script called `facts-tracker` that counts the number of files with Flow coverage and pushes it to the `facts` branch. Perhaps you could modify it to list those files instead? Then we could make a dashboard that reads them from GitHub API and shows a list of remaining files. Kinda like we did with isfiberreadyyet.com.

**Comment by VladBlow** [comment]
I think I can watch tonight

**Comment by VladBlow** [comment]
I looked, but it seems I could not figure out what I need to change.
Maybe can someone help me? I would really like to understand.

**Comment by gaearon** [comment]
What have you tried?

**Comment by VladBlow** [comment]
I don't understand what I should do in this file.

**Comment by gaearon** [comment]
We have a script here:

https://github.com/facebook/react/blob/f6c60dcbcd11c756e16b1f0e50c18ca4dc2e3953/scripts/circleci/track_stats.sh#L7

It greps for how many files with `@flow` we have and calls a script that writes that to the `facts` branch:

https://github.com/facebook/react/blob/facts/flow-files.txt

I'm proposing that maybe we change it to keep a list of files with Flow instead. What do you think?

**Comment by VladBlow** [comment]
Instead of number of files it output the list of files? I understand correctly?

**Comment by gaearon** [comment]
That's what I thought we could do, yes.
