### ISSUE TITLE
HTML5 Templates apart from JSX for Non Programmatic situations

### ISSUE THREAD

**Issue by IamManchanda** [facebook/react#11322]
Just before I have my view, please take a look at these 2 examples

Hello World React => [App.jsx](https://git.io/vdNQb)
Hello World Vue => [App.vue](https://git.io/vdNQN)

Identical? Isn't it?
Yes these are two different **paradigm** but hey they are expressing same things and both are doing it in the same way by taking benefits of the Virtual DOM 

My Feature Request is that,
Just like Vue supports [JSX](https://vuejs.org/v2/guide/render-function.html) for Programmatic situations.
I think React should also support HTML5 Templates for Non Programmatic situations?? 

Also, **Imagine trying to create a website based on an existing theme that you purchased. Changing it over to JSX literally will feel like sticking a knife through your eyeballs. With Templates, existing HTML just works.**

Please also note that Programmatic situations have a low use case
and Non Programmatic situations have a high use case.

**Comment by IamManchanda** [comment]
Moreover [separation of concerns](https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns) has been a big issue with JSX. Moreover, these days people have been going ahead and moving their [CSS within JSX](https://codeburst.io/css-in-js-is-like-replacing-a-broken-screwdriver-with-your-favorite-hammer-c9765c9ee43b) too which according to me is not good. 

My Questions:
1. Does Facebook/React arguably agree with CSS in JS paradigm or not?
2. Does this feature request of HTML5 Templates make any sense for React.js future and separation of concerns?

**Comment by IamManchanda** [comment]
I think that some kind of abstraction that behind the scenes converts 

1. `<template>` to JSX render() function 
2. `<style scoped>` to [Styled Components](http://cssinjs.org/styled-jss) on top of JSS

**Comment by gaearon** [comment]
This is a bit vague and hard to address.
These kinds of suggestions are best submitted as RFCs which require you to think through it in more detail.

You're welcome to submit one:
https://github.com/reactjs/rfcs

Thanks!
