### ISSUE TITLE
componentDidCatch is not getting called when there is an error in promise

### ISSUE THREAD

**Issue by john1jan** [facebook/react#11334]
As per the new react 16 release [doc](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html)  it says 

"**React 16 prints all errors that occurred during rendering to the console in development, even if the application accidentally swallows them.**"

I have a Parent component and a Child component. I have triggered an error in **then** block of promise. But it will call catch method of the promise, componentDidCatch of parent is not getting called. I am not sure  whether this the expected behaviour. 

Here is the jsfiddle https://jsfiddle.net/john1jan/Luktwrdm/14/

**Comment by gaearon** [comment]
As it says:

>Error boundaries catch errors during rendering, in lifecycle methods, and in constructors of the whole tree below them.

What you're showing is an error in a Promise callback. You happened to fire the thing that called it from `componentDidMount`, but the error doesn't technically happen *inside* `componentDidMount` so error boundaries won't catch it.

Error boundaries are a mechanism to prevent React from getting into an inconsistent state when **it doesn't know what to render due to an error**. This is not the case in your example: even despite the error, the rendering is unaffected.

Here is an example where a Promise *does* lead to re-rendering, which throws and then gets swallowed. You can see that in that case, error boundary receives the error: https://jsfiddle.net/t37cutyk/

So it is working as designed.

**Comment by john1jan** [comment]
Thanks, @gaearon for explaining. But the doc is little confusing. It would be great if you can give an example of how an application can accidentally swallow an error.

In the https://jsfiddle.net/t37cutyk/, I dont think the child component is swallowing the error.

**Comment by gaearon** [comment]
I am referring to this block:

```js
fetch("https://jsonplaceholder.typicode.com/posts").then((response) => {
      this.setState({posts: []});
    }).catch((error)=>{
    	console.log("Error caught in catch",error);
    })
    ;
```

If you leave the `catch()` clause empty and not log the error (effectively swallowing it), React will still report it as unhandled to the browser, and pass it to the error boundary. Even though you "caught" it. This is intentionally because people have been accidentally swallowing errors like this for years, and we got a few dozens different issues about this over time.

**Comment by john1jan** [comment]
Thanks again @gaearon. I have removed catch block as you said. And even I have removed error boundary from Parent component. Even though the child components **throws** that error without swallowing it and does not render. So when the whole component is not rendered there is a possibility that developer will notice this at the time of development or testing. 

Just correct me if I am wrong. I think **"Swalling an error"** means "even if the error is thrown in the child component it is rendered"

**Comment by gaearon** [comment]
I’m not sure what you’re asking. Yes, it is expected that if an error is thrown during rendering, the tree is unmounted *unless you created an error boundary*.

“Swallowing” an error means using a `catch` block and then ignoring the `error` object. This makes it impossible for developers to figure out what went wrong. What I’m saying is that React now protects against this by printing the error to the console *even if it was caught*.

**Comment by dudko** [comment]
@gaearon, your fiddle does not define `state` of child component and crashes before fetch is resolved. Fixed [example](https://jsfiddle.net/t37cutyk/10/) makes your explanation more obvious. Anyway, thanks a lot for it!

**Comment by AlicanC** [comment]
@gaearon, you have closed this issue, but isn't this a great case for [Zones](https://github.com/domenic/zones)? Lifecycle methods could be ran in a Zone and the error handling mechanism (https://github.com/domenic/zones/issues/9) could be used to catch async errors.

**Comment by AlicanC** [comment]
And meanwhile an API (like `this.throw`) can be exposed so we can:
```javascript
componentDidMount() {
  doAsync()
    .then(() => ...)
    .catch((error) => this.throw(error));
}
```

Would React be capable of handling asynchronously sent errors?

**Comment by AlicanC** [comment]
If you want a workaround, this could work too:
```javascript
  handleClick() {
    try {
      badStuff();
    } catch(err) {
      this.setState(() => { throw err; });
    }
  }
```

**Comment by ericvicenti** [comment]
if you're using hooks, I think the following should work nicely with error boundaries:

```js
function MyComponent({ input }) {
  const [asyncResult, setAsyncResult] = useState(null);
  if (asyncResult.error) {
    throw new Error('Catch me, parent!');
  }
  useEffect(() => {
    asyncThing(input)
      .then(result => setAsyncResult({ result })
      .catch(error => setAsyncResult({ error });
  }, [ input ]);
  return <SomeView thing={asyncResult && asyncResult.result} />;
```

Of course this is boilerplatey, so you'd probably want this behavior packaged in something like `useAsyncResult(asyncCallback, inputs)`, which would be used like this:

```js
function MyComponent({ input }) {
  const thing = useAsyncResult(async () => {
    // other async logic could go here
    return await asyncThing(input);
  }, [ input ]);
  return <SomeView thing={thing} />;
}
```

PS. I haven't tested this yet, but I'm off to do that now

**Comment by technion** [comment]
@ericvicenti  Thanks for that tip - I've followed that pattern and it works well.

**Comment by dz-s** [comment]
@ericvicenti works well for me too. Thanks a lot.
