### ISSUE TITLE
iframe content getting initial document differs from actual result

### ISSUE THREAD

**Issue by u007** [facebook/react#11335]
**Do you want to request a *feature* or report a *bug*?**
bug / not sure if its react / browser
**What is the current behavior?**
i made a static iframe that display a url, and then run some script on the iframe from parent window.

it works fine for second / after refresh of entire page.
but for every 1st time load 
```
console.log i.contentWindow.document.body #refers to correct dom when inspected on console.
```
but body innerhtml differs from 
```
console.log(i.contentWindow.document.body.innerHTML)
```

the innerhtml supposed is the correct rendered html that been effected by javascript within the iframe page itself. but in the script 
```
i.contentWindow.document.body
```
it shows html that is the initial html being loaded.

behavious has been watched after pausing on script.
even after several time calling reload of iframe, problem persists. only fixed if entire page reloads (parent window)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

something like this:
https://jsfiddle.net/Luktwrdm/21/

but sorry i do not know how to make import work on fiddle

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
chrome 61
macos high siera

**Comment by gaearon** [comment]
Why do you think this is a bug in React? Have you tried doing the same with vanilla DOM APIs?

**Comment by u007** [comment]
hi sorry, i think i might have confused with the body content
