### ISSUE TITLE
Unexpected rerenders while in production enviroment

### ISSUE THREAD

**Issue by jdrzejb** [facebook/react#11344]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
React is making unexpected rerenders when used along `react-router-dom` and `react-css-modules`. This happens only while in production enviroment. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://github.com/jdrzejb/react-rerender-bug 

Application running in development mode is setting key prop properly, thus not making rerenders between route calls inside component.
App in production mode is appending new value to existing key resulting in rerender and this:
https://imgur.com/a/BHp8w 

**What is the expected behavior?**

Application in production mode should be setting proper key value and not rerendering.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I don't believe that this is browser problem. I had the same issue with Safari 11.0 and Chrome 62.
I have tested it with React 15.6.2 and React 16.0.0

I have tried to isolate this issue as much I could. If I can help you any further please let me know.

**Comment by gaearon** [comment]
Any way you can isolate it further without third party dependencies?

**Comment by DaveVanRijn** [comment]
We also experience this bug, but in development mode. We render some HTML in an array with unique keys on each array entry. Removing the keys and rendering everything with a div around it (so remove the whole array) seems to fix it, which might suggest there is something wrong with the way react works with the keys.

**Comment by gaearon** [comment]
This is unfortunately very vague and won’t help diagnose the problem.

**Comment by DaveVanRijn** [comment]
I understand it is not possible to reproduce with my description, the hard thing is that it only happens at one specific location in our code. We use a lot of array constructions in our code which all work fine, but suddenly this one location started to break everything. 

A standard CRA application also doesn't show any errors while using keys. I'll try to see if I can find/make a reproducing case without other libraries.

**Comment by gaearon** [comment]
Any chance you're using some Babel plugins? Like "inline elements" transform. Try disabling them if you are.

**Comment by gaearon** [comment]
I’ll close since there is very little activity on this issue, and nobody created a small React-only example that demonstrates it’s indeed an issue with React itself.

**Comment by gaearon** [comment]
I've also just run your example and I can't understand from your description which exactly steps I was supposed to perform to demonstrate the issue. The screenshot of DevTools did not help me (what exactly was I supposed to see in it?)
