### ISSUE TITLE
Support onEnd SVG event

### ISSUE THREAD

**Issue by Maniae** [facebook/react#11342]
Hi,
I'm trying to use the \<animateTransform\> Element in a React project. But I'm not able to use the "onend" attribute:

> Warning: Unknown event handler property `onend`. It will be ignored.

Is there a workaround for this ?

**Comment by gaearon** [comment]
The support for custom attributes doesn’t include events. Event still have to be whitelisted in React.

I’m not sure if we can or should implement this event in React, but you can try to work around it by using DOM APIs:

```js
constructor(props) {
  super(props);
  this.handleEnd = this.handleEnd.bind(this);
}

componentDidMount() {
  this.node.addEventListener('endEvent', this.handleEnd);
}

componentWillUnmount() {
  this.node.addEventListener('endEvent', this.handleEnd);
}

handleEnd() {
  // ...
}

render() {
  return <animateTransform ref={node => this.node = node} />
}
```

Does this help?

**Comment by aweary** [comment]
It looks like [`SVGAnimationElement.onend`](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement/onend) is part of the SVG Animations Level 2 specification, which is currently only an Editor's Draft. This means it's not currently part of the official W3C specification process yet. Browser support is also unclear.

I think whitelisted events should either be part of an official specification and/or have wide browser support and use. In this case, I think manually listening for the event is likely the best solution for now.

**Comment by gaearon** [comment]
Fair.
