### ISSUE TITLE
Error boundary stack traces show components as Unknown in IE11

### ISSUE THREAD

**Issue by wKovacs64** [facebook/react#11353]
**Do you want to request a *feature* or report a *bug*?**

Bug? Unless I missed something required for IE11 support.

**What is the current behavior?**

Error boundary component stack traces show `Unknown` for every component name in IE11:

```
    in Unknown
    in Unknown
    in div
    in Unknown
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

Trigger an error, catch with an error boundary, observe `info.componentStack` string. [Shingo Yamazaki's codepen demo](https://codepen.io/zaki-yama/pen/dzYWNM) will reproduce the issue.

**What is the expected behavior?**

```
    in BuggyCounter (created by App)
    in ErrorBoundary (created by App)
    in div (created by App)
    in App
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

* React 16.0.0
* IE11, Windows 8.1 / 10
* N/A

**Comment by Kovensky** [comment]
IE11 does not support `Function#name`, so all your functions (and thus components) are unnamed unless you either set `displayName` or polyfill it with a getter in `Function.prototype`. `core-js` provides such a polyfill.

**Comment by wKovacs64** [comment]
Ah, sure enough - polyfilling did the trick. Thanks @Kovensky! 👍 

I wonder if this should be added to the [JavaScript Environment Requirements](https://github.com/reactjs/reactjs.org/blob/master/content/docs/reference-javascript-environment-requirements.md) section of the docs with the other polyfills? Or the [Error Boundaries](https://github.com/reactjs/reactjs.org/blob/master/content/docs/error-boundaries.md) section?

**Comment by gaearon** [comment]
Please file a new issue in https://github.com/reactjs/reactjs.org/ about documenting. Thanks!
