### ISSUE TITLE
<svg> with linearGradient produces server side rendering warning

### ISSUE THREAD

**Issue by lzcabrera** [facebook/react#11354]
This is a report for a bug of a server side rendering warning when using svgs in React 16

**What is the current behavior?**
We get the following warning when using an svg tag with a linearGradient attribute in one of our components:

`Warning: Expected server HTML to contain a matching <linearGradient> in <defs>.`

Since this is a server side warning, we have reproduced the warning on this repo with a very simple example of an svg tag:
https://github.com/lzcabrera/svg-SSR

**Steps to reproduce**
* clone repo
* `npm install`
* `npm build`
* `npm start`
* Visit http://localhost:3000 on your browser
* Open the javascript console to see the warning

**What is the expected behavior?**
The expected behaviour is to have no warning when doing server side rendering, just like there is none when rendering on the client side.

This worked in React 15.6.1 as tested on branch v15 on the same repo above.

**Comment by gaearon** [comment]
Thanks for the report! This was fixed in https://github.com/facebook/react/pull/11174 but not released yet. Watch out for the next release!

**Comment by dargue3** [comment]
Am running into this error with a `<linearGradient>` tag inside an SVG. This should be fixed by now (running React v 16.2.0), correct?

 Let me know if you need any more information.

**Comment by gaearon** [comment]
Please file a new issue. Maintainers almost never read old issues because they're hard to track and it's not clear if this is a real problem or a misunderstanding.
