### ISSUE TITLE
Fix coverage reporting

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11363]
For some reason coverall says it's 0% on master, pointing to this commit: https://github.com/facebook/react/commit/96ed55ff800631b32618c65867f30f7fa6b30ed5.

This makes no sense to me. Probably a bug either in our reporting or on their side.

For now I removed the badge in README.

**Comment by xjlim** [comment]
@gaearon This is fixed with #11372

**Comment by gaearon** [comment]
Yep. Thanks for reminding.
