### ISSUE TITLE
Add a way to opt out of User Timing API calls

### ISSUE THREAD

**Issue by artin-phares** [facebook/react#11366]
**Do you want to request a *feature* or report a *bug*?**  

bug or v16 feature (dont know)

**What is the current behavior?**  

When building in dev environment, performance timeline measures appear by default,  
ie. without `?react_perf` query string as in v15 described [here](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab)

`react@16.0.0`

if it's not a bug, then what's the way to disable `react` perf measures?  

Need a way to clear timeline to focus on my own custom perf measures.

**Comment by gaearon** [comment]
Yes, it’s intentional (docs haven't been updated yet).
Ideally I wish the browser vendors offered a way to group and filter them. (cc @samccone)

We don’t have a way to opt out yet, but I’m open to adding it. What is your proposed way to do it?

**Comment by artin-phares** [comment]
> Ideally I wish the browser vendors offered a way to group and filter them.

I guess it would be the best option.  

> What is your proposed way to do it?

Didn't like query string way very much. Nor some global var looks good.  

Maybe something like this?  
```
ReactDom.config({
   perf: false
})
```

**Comment by artin-phares** [comment]
FYI, I've started [discussion](https://groups.google.com/forum/#!topic/google-chrome-developer-tools/vQgmqUEQME0/discussion) on timeline filtering feature for chrome

**Comment by gaearon** [comment]
Seems like browsers would be better positioned to do this. I don't mind taking a PR with some kind of way to opt out if you feel strongly though.
