### ISSUE TITLE
Can not get the right e.nativeEvent.currentTarget when use html5 drag api

### ISSUE THREAD

**Issue by robberfree** [facebook/react#11370]
1. my component looks like:
```js
handleDrop = e => {
    console.log('drop', e.nativeEvent.currentTarget, e.currentTarget);
  };

render() {
    return (
      <div
        className={`panel-layer-view ${this.state.dragOver
          ? 'panel-layer-view_drag-over'
          : ''}`}
        onDragEnter={this.handleDragOver}
        onDragOver={this.handleDragOver}
        onDragLeave={this.handleDragLeave}
        onDrop={this.handleDrop}
      >
        {this.props.children}
      </div>
    );
  }
```
2. when drag some element that set draggable="true" on the component, i will get console message as below:
<img width="1377" alt="2017-10-26 21 40 59" src="https://user-images.githubusercontent.com/15938895/32056190-9c112d76-ba29-11e7-8c32-c1031ac555c5.png">
3. i do not add listener of DND operation to doc/body.i tried to find what's the problem.
please help have a look.thanks ahead.

**Comment by gaearon** [comment]
This is intentional. React listens to events at the document level for better performance.

**Comment by robberfree** [comment]
Thank you very much.i miss this point.
