### ISSUE TITLE
Separate renderToString and renderToNodeStream

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#11377]
Currently, its not possible to run renderToString on the client because ReactDOMServer imports the Node.js fs package. It would be nice if we could still support renderToString on the client.

**Comment by ccorcos** [comment]
Just discovered server.browser.js!

**Comment by gaearon** [comment]
When you import `react-dom/server` in a client app your bundler should automatically use `react-dom/server.browser` instead. Because of a field in our `package.json`. I remember verifying this worked with webpack and browserify. Did you bump into some case where this doesn't happen?

**Comment by ccorcos** [comment]
Interesting. I didnt know that. Perhaps [oy](https://github.com/revivek/oy) is importing something else that's causing this issue. (I'm trying to render email previews on the client).
