### ISSUE TITLE
Elements and Components

### ISSUE THREAD

**Issue by giorgim** [facebook/react#11398]
In this code:

```
class Clock extends React.Component {
  render() {
    return (
      <div>
        <MyCustomReactComponentClass/>
     </div>
    );
  }
}
```

is `MyCustomReactComponentClass` a react element or react component?

I am asking because here: https://discuss.reactjs.org/t/does-render-create-new-instance-of-component-each-time/7400, I was told on each render the same instance of `MyCustomReactComponentClass` is used. If that is the case, and: (1) `MyCustomReactComponentClass` is react element and (2) given that according to doc react elements are immutable(https://reactjs.org/docs/rendering-elements.html#updating-the-rendered-element), then how would `Clock` pass different props to the same instance of `MyCustomReactComponentClass` on each render (if the latter is immutable)?

**Comment by amannn** [comment]
In your case `MyCustomReactComponentClass` is a component, whereas `<MyCustomReactComponentClass  />` is an element. When an element of a stateful component gets rendered, an instance is created for it. This instance will be preserved across renders, whereas new elements are created for every render.

Here's a good blog post about this that goes into more detail: https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html

**Comment by amannn** [comment]
The element is never mutable. E.g. consider this code:

```js
const element = <h1>Hello, world!</h1>;
element.props.children = 'Goodbye, world!';

ReactDOM.render(
  element,
  document.getElementById('root')
);
```

This will throw with `Uncaught TypeError: Cannot assign to read only property 'children' of object '#<Object>'`.

Note that this is the same for user defined custom components (stateful or not).

On the other hand the properties of an instance will be mutated over time (by React – not the user).

**Comment by giorgim** [comment]
```
class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = { seconds: 0 };
  }

  componentDidMount() {
    this.interval = setInterval(() => this.tick(), 1000);
  }

  tick() {
    this.setState(prevState => ({
      seconds: prevState.seconds + 1
    }));
  }
  render() {
    return (
      <div>
        <MyCustomReactComponentClass someProp={this.state.seconds}/>
     </div>
    );
  }
}
```

Would above example not classify as mutating **the same instance** of `MyCustomReactComponentClass` on each second, by passing different someProp to it?

**Comment by amannn** [comment]
Well yes, the properties of the _instance_ are mutated (by React). There's no mutation of an _element_ however, there's rather a new one created on every render.

The terminology is a bit tricky here, the linked article from above maybe helps a bit.

**Comment by giorgim** [comment]
@amannn Yeah I think it is terminology thing, will give more thought about it later.

**Comment by blling** [comment]
No render, no new instances.

**Comment by gaearon** [comment]
>Would above example not classify as mutating the same instance of <MyCustomReactComponentClass/> (a react element) on each second, by passing different someProp to it?

No. This is exactly why it is immutable. You *create a new element* every time. React remembers the old one internally, so if the type and key match (they do in this case), it mutates the old *instance* to have props from the new *element*.

Same in more detail: https://reactjs.org/docs/reconciliation.html

**Comment by gaearon** [comment]
Related:

https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html

https://reactjs.org/docs/rendering-elements.html#react-only-updates-whats-necessary

**Comment by blling** [comment]
Should i ask why it called `reconciliation`?

**Comment by gaearon** [comment]
It "reconciles" what the component say should be on the screen with what's actually on the screen.

**Comment by giorgim** [comment]
@gaearon So when one write say` <CustomComp/>` inside render, there are two things happenning: (1) instance of class `CustomComp `is created and (2) its render method is called, is that right? (I had impression this article said: https://tylermcginnis.com/react-elements-vs-react-components/, there was no instance creation involved).
