### ISSUE TITLE
Occams software

### ISSUE THREAD

**Issue by velociwabbit** [facebook/react#11394]
I am a reasonably familiar React coder that was looking for a simple template for a image oriented app.  I downloaded and reviewed/hacked/played with many of the examples in this section.  While most are useful I did notice something that I felt was worth mentioning.

Perhaps I am alone but I find that many files are  confusing when trying to figure out how code works.  Perhaps it is the hangover for java trained engineers bringing their coding style to javascript?  If so then I really wish I had been to the party!

The very nice emoji search app is a good example.  If one consolidates all the files into one file one can make a version that is clear and readable and easily understood with  fewer lines of code **than there are code modules** to wade through to figure out how the code works.

I actually thought this to be impossible  (and it is impossible  with 80 character or 132 character lines) but with the full use of a 1080p monitor it is very easy to do.

I am only mentioning this here because react seems to be a particularly sprawling framework that could do with a bit of grooming.  

Most of the demo's from FB with react are single page demo's (more or less).  

Does anyone else agree with me? and if so I would like to propose that there be a section of examples called "full app snippets" (or something equally silly) for those of us who get _directory vertigo_  easily. 

Sometimes it reminds me of sitting in the back of a car reading a book 

on a very windy road :)
![image](https://user-images.githubusercontent.com/9357805/32138757-9d1158ca-bbed-11e7-8433-4de1430e1381.png)

**Comment by gaearon** [comment]
Did you look at examples sprinkled throughout https://reactjs.org (the Docs section)? They're all fairly small. Even though technically they're hosted and not "files".

**Comment by velociwabbit** [comment]
Yes I have viewed these before and they are fine for beginners and some of the code is useful to grab but unless i am missing something there are only four of five of them.  I have built several material.ui apps with redux and redux forms  and have written my own distilled subset of these which I use for many components.  MUI, however  is not react native compatible and there does not appear to be any movement in that direction.

What I would really love to see is something akin to what Three.js has which is an extensive example application library where most of the examples are < 3 modules plus three.js library components.

Between Yarn, Webpack, Lint, Mocha and the thousands of special case frameworks the React ecosystem is beginning to resemble java spring and not in a good way.

What I find surprising is the even after building out several  full production React/Redux/Forms/Rest apps my learning curve for  React apps  using a different set of components and UI is not much shorter than learning React in the first place. 

There is a solution to this issue and it is a lot of distilled single module applications that cover the range of potential use cases.

**Comment by gaearon** [comment]
Have you tried to use Create React App? It handles all the build dependencies for you so you don't need to think about configuring or setting them up.

**Comment by velociwabbit** [comment]
Yes I have both used it and deconstructed it to understand exactly what it does. It is a great piece of software.   It was not a good fit for my last app but it was a great start.

For my last app I used koa as a server and was doing telemetry for 1k sensors or more so the app was three facing... Web for viewing 3d and 2d data, Sensors for telemetry acquisition  and  database for both admin and archival. 

React has been superb in this environment  because I was able to store all of my routes, and react component definitions in tables and query them as needed to generate the front end. 

This apps that I am thinking about are more user oriented (take a picture do stuff with it , take another picture, write a note ... ) normal stuff that by now should be fairly pedestrian in the React / Native environment.  The problem is that each 3rd party example has lots of unique and extra special dependencies and there is no standard way to show core functions in a minimalist (no linting, minimal error handling, no complex regression testing) set of modules.

I would be willing to contribute to such a repository if I knew that others would value it as I do.

It is no fun to have to learn 80% new stuff  every time I take on a new bleeding edge project.  I don't mind bleeding on the new  stuff (that is half the fun)  but not on stuff that is mature and should be boilerplate by now.

So where are the simple boilerplates? all the ones that I see set up many modules and once again **directory vertigo** (I think i like this new term... )

**Comment by velociwabbit** [comment]
I was just thinking that as much as I thought create-react-app is a great piece of software it is also a good example of the problem.  For a newbie it is hard to figure out exactly where the entry point into one's software exists because it is hidden in a node-module directory that is not part of the user's code.

I would bet that if c-r-a made it more explicit about how it instantiates itself by placing all of its code in a module in the root directory of the  created app the use of it would skyrocket.

Google(or more generally alphabet) describes  functions that happen implicitly as "magical" and they are considered to be poor design because they are hard to control, maintain and modify. Complex directory structures and hidden critical files which perform "magic" no matter how cool suffer from same issue. 

The problem is to some degree training / history but also a bit of ego.  Making thing look trivial is very hard... and once it looks trivial it is not appreciated as much.

**Comment by gaearon** [comment]
Another way to look at it is to think about compiled languages. Do you need to understand how C compiler works to write C? Would you expect that complete source code of the C compiler is explicitly written into every C project? No, you just call it as a command line utility. That's abstraction. If you think of CRA the same way it starts to make more sense, I think.

**Comment by velociwabbit** [comment]
To be sure... Just to be clear I am a big believer in React so please do
not take this as a denigration but instead a profound desire to help
improve it.

The C language issue is a great example because (as it turns out)  I have
been struggling today to use  some of the gl-react repositories and keep
running into problems like "winsock3.h missing".

Obviously this is not a react issue but it is illuminating. I upgraded node
to 8.0 and this broke many of these GL oriented react libraries.  So now i
have to reinstall 6.9 node plus make sure that i have both 2015 and 2017
Microsoft developer utilities installed to support a high performance
version of  sqlite and then somehow figure out how to make all of these
work with react native. (I also bought a mac in hopes that i can sidestep
these issues if they are too entangled).

I hope you see my point here.  I believe that  a set of really well
executed but minimalist examples of the 50 or so types of react app
components that are most widely used would really help. Sort of React Rocks
but distilled down to the core components  and tested so that the user is
confident that the examples will work by simply pointing to the directory
and running npm init & npm start.

This simplified app set would go along way to reduce the stress level when
venturing out of one's react comfort zone.  Especially if one could cut and
paste between the examples to create full solutions.

Ideally in this repository each example would be limited to a only a few
(or optimally only one) directories other than the node_modules directory.
Modularization is fine but it can create *directory vertigo :) *

There should be a way to do this and I am all in to help if others feel the
same as i do.

Afterall it is very hard to trash talk about  java spring if ultimately the
node/react/... ecosystem is just as inscrutable :)

**Comment by gaearon** [comment]
I'll close because this doesn't seem directly actionable, although I appreciate the discussion. If you have specific ideas about what we could improve in specific projects, please file follow-up issues in those projects:

* React docs: https://github.com/reactjs/reactjs.org
* Create React App: https://github.com/facebookincubator/create-react-app/

**Comment by velociwabbit** [comment]
Thankyou for listening and if once again i  am all in on helping to create this three.js like example repository if someone who is more steeped in the react/native ecosystem would contact me.
