### ISSUE TITLE
A function that is also an iterable is treated inconsistently

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#11396]
**Do you want to request a *feature* or report a *bug*?**
*bug* (I think)

**What is the current behavior?**
Here's a [codesandbox](https://codesandbox.io/s/0ml3roomr0). Or just plop this in an `index.html`:

```html
<body>
<div id="root"></div>
<script src="https://unpkg.com/react@16.0.0/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@16.0.0/umd/react-dom.development.js"></script>
<script src="https://unpkg.com/babel-standalone@6.26.0/babel.js"></script>
<script type="text/babel">
function makeRenderable(fn, valueGetter) {
  const ITERATOR_SYMBOL =
    (typeof Symbol === 'function' && Symbol.iterator) || '@@iterator'
  function iterator() {
    let timesCalled = 0
    return {
      next() {
        const done = timesCalled++ > 0
        return {done, value: done ? undefined : valueGetter()}
      },
    }
  }
  fn[ITERATOR_SYMBOL] = iterator
  return fn
}

const renderableFunction = makeRenderable(function(a, b) {
  // kinda irrelevant what goes on in here...
  return a + b
}, () => 'I am the rendered version of the function')

function Working() {
  return (
    <div>
      This works: <div>{renderableFunction}</div>
    </div>
  )
}

function NotWorking() {
  return <div>This does not work: {renderableFunction}</div>
}

ReactDOM.render(
  <div>
    <Working />
    <hr />
    <NotWorking />
  </div>,
  document.getElementById('root'),
)
</script>
</body>
```

**What is the expected behavior?**

I expect that things will render the same regardless of whether they're an only child or a member of an array of children.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Yes, [it worked in React@15](https://codesandbox.io/s/8zlpvjzjy9).

**Suggested Solution**

I'm fairly confident that the issue is in the array of children case, the [`getIteratorFn` call](https://github.com/facebook/react/blob/2c0a8fb99e945315c9dce7a15c85775d51f5755d/packages/react-reconciler/src/ReactChildFiber.js#L578-L586) is within a `typeof newChild === 'object' && newChild !== null` if statement, whereas the original [reconcileChildFibers](https://github.com/facebook/react/blob/2c0a8fb99e945315c9dce7a15c85775d51f5755d/packages/react-reconciler/src/ReactChildFiber.js#L1358) puts the [`getIteratorFn` call outside it](https://github.com/facebook/react/blob/2c0a8fb99e945315c9dce7a15c85775d51f5755d/packages/react-reconciler/src/ReactChildFiber.js#L1434-L1441).

If I'm not mistaken, a simple fix would be to move [this curly brace](https://github.com/facebook/react/blob/2c0a8fb99e945315c9dce7a15c85775d51f5755d/packages/react-reconciler/src/ReactChildFiber.js#L589) a few lines up :wink:

I'm happy to do so complete with a test given a little direction (like, where the test should go). Thanks!

**Comment by gaearon** [comment]
We could move it out, but we should make sure that:

* We still should [throw](https://github.com/facebook/react/blob/2c0a8fb99e945315c9dce7a15c85775d51f5755d/packages/react-reconciler/src/ReactChildFiber.js#L588) if something has `typeof object` but is neither of supported object types
* We still should [*not*](https://github.com/facebook/react/blob/2c0a8fb99e945315c9dce7a15c85775d51f5755d/packages/react-reconciler/src/ReactChildFiber.js#L597) throw if it has an unsupported type but isn't an object
* We should not call `getIteratorFn` unnecessarily (e.g. on an element)

Maybe you could just duplicate [this code path](https://github.com/facebook/react/blob/2c0a8fb99e945315c9dce7a15c85775d51f5755d/packages/react-reconciler/src/ReactChildFiber.js#L579-L585) below. Or figure out some other smart way to do it.

The test should go in the same place existing iterable tests currently go. You can search for them in `packages/**/*-test.js` with `@@iterator` definitions. I see one in `ReactChildReconciler-test.js`, `ReactMultiChild-test.js`, `ReactMultiChildReconcile-test.j`. Find the one that's most similar and put it next to it :-)

**Comment by ark9606** [comment]
ва

**Comment by kentcdodds** [comment]
I've got some time today so I'll start working on fixing this. Thanks @gaearon!

**Comment by gaearon** [comment]
We decided to do the opposite: the fix would be to completely disable this patterns since it was never intentionally supported. Iterable functions should be treated as functions, not iterables.

**Comment by gaearon** [comment]
So the action item here is to send a PR that completely disables this functionality.

**Comment by blacktrident** [comment]
Hey I am new to Opensource ,Can i be of some help?

**Comment by gaearon** [comment]
Sure. It's probably not the easiest issue, but if you'd like to give it a try, please go ahead!

**Comment by moe091** [comment]
Are you still working on this blacktrident? If not I may give it a go

**Comment by moe091** [comment]
What is the exact intended functionality for this fix?

going off of kentcdodds example in his original post, the <Working> function returns an array of two children, a string("this is not working") and a div, with that div having a function(renderableFunction) as a child.

Should the <NotWorking> function return a single div, which has two children - a string "This works:" and the renderableFunction function?

Sorry, I'm working on my first contribution and still wrapping my head around how React works. If you'd rather wait for someone more experienced to work on this I'll leave it alone. If not I think I should be able to figure it out eventually though, I just need to understand exactly what functionality I'm aiming for

**Comment by raunofreiberg** [comment]
What's the status on this one? Do we wish to remove the support for reconciling iterables? Would this include changes to the `reconcileChildrenIterator` function?

**Comment by gaearon** [comment]
@raunofreiberg We only want to remove support for treating *functions* as iterables. Meaning literally *function values* that have iterator attached to them.

**Comment by raunofreiberg** [comment]
Gotcha. I'll try and start working on this - thanks!

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/13416.
