### ISSUE TITLE
In some cases will lose some components

### ISSUE THREAD

**Issue by yakiler** [facebook/react#11403]
**Do you want to request a *feature* or report a *bug*?**
I just have a problem do not understand
**What is the current behavior?**
Behind react in the div, there are some components that are not loaded
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
`<body><div id="successDiv"/><div id="reactDiv"/><div id="notLoadedDiv"/></body>`
The document structure looks like this.The second div is used with react components,The first div is able to load properly into dom,But the last div can not load into dom
**What is the expected behavior?**
All divs should be loaded normally
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react:
https://cdn.bootcss.com/react/16.0.0/cjs/react.development.js"
https://cdn.bootcss.com/react/16.0.0/cjs/react.production.min.js
https://cdn.bootcss.com/react/16.0.0/umd/react.development.js"
https://cdn.bootcss.com/react/16.0.0/umd/react.production.min.js
system:win10  14393

**Comment by g3r4n** [comment]
Try to do it like that :
`<body><div id="successDiv"></div><div id="reactDiv"></div><div id="notLoadedDiv"></div></body>`

**Comment by yakiler** [comment]
@g3r4n  Thankyou , I solved the problem. It is not brought by react,Is my babel version with Bug

**Comment by clemmy** [comment]
@yakiler If you don't mind, can you share what the problem was with Babel and how you fixed it? :)

**Comment by yakiler** [comment]
@clemmy  ok! In my html use ' <script src="https://cdn.bootcss.com/babel-standalone/7.0.0-beta.2/babel.min.js"></script>' to convert jsx , This library can not correctly parse my jsx in html. Into the official library perfect solution

**Comment by gaearon** [comment]
Note you shouldn't be using `<script>` version of Babel for real websites. It's only meant for quick prototyping. It is extremely slow.
