### ISSUE TITLE
Web Development

### ISSUE THREAD

**Issue by Sazid-Kazi** [facebook/react#11408]
If I use laravel, react js and mysql for building a site like yelp or tripadvisor then will it be a good option or not? Which rendering (CSR or SSR) approach will be good for the website? Initially, I want to stay in monolithic architecture and 1 year later i will go for microservice architecture, so which method should i follow to make this shifting easier (mono to micro)? Moreover, my target is to make the site progressive web app from the very beginning. So need suggestion from you guys.

**Comment by gaearon** [comment]
You already asked this in https://github.com/facebook/react/issues/11399.
Please don't create duplicate issues.

This is a bug tracker for React, not a discussion board.
Please refer to my previous answer for more appropriate places to ask questions.

Cheers!
