### ISSUE TITLE
[Proposal] Promise as setState first arg

### ISSUE THREAD

**Issue by XaveScor** [facebook/react#11406]
We have a recommend way to use setState: use a function instead of object.
```
this.setState(prevState => ({
  a: prevState.a + 1
}))
```
But we have an async functions. And we cannot push him inside setState.
Can you add an `(State, Props) => Promise` arg?
Now, we write this:
```
async foo = async () => {
  const state = await Promise.resolve(this.state)
  const data = await doSmth(state)
  this.setState({data})
}
```
instead of
```
foo = () => this.setState(async prevState => ({
  data: await doSmth(prevState)
}))
```

**Comment by pie6k** [comment]
I'd require `this.state` to be promise, right? What about using things like `const { userData } = this.state` in render?

**Comment by gaearon** [comment]
This might *seem* good but it's a can of worms.

What if the Promise is rejected? What if you call `setState` twice and have two Promises, and they arrive in a different order? Should the last one win? What if you want newer value of `someProperty` but older value of `anotherProperty`?

`setState` is intentionally assuming you already *know* what you want to set it to. If you need to wait for a Promise, do that first, and then call `setState` when you're ready.
