### ISSUE TITLE
FocusIn/FocusOut for relatedTarget in IE

### ISSUE THREAD

**Issue by vankop** [facebook/react#11405]
Currently (react <=16.0.0) there is no support for `FocusIn/FocusOut` events. But the problem is that in IE  <= 11 blur event has no relatedTarget, so it will be great to support such events.

So, the question is will be such support in later versions?
This problem was mentioned in https://github.com/facebook/react/issues/3751, but there is no answer.

**Comment by jquense** [comment]
It's not likely there will be support unfortunately, Microsoft isn't gonna fix it for ie11 and there is really no way to effectively work around it in the event system (I have tried!).

The best way I've found to handle this, depending on your use case, is to listen for both blur and focus in a container with a set timeout and coordinate between the two events

**Comment by vankop** [comment]
@jquense You are totaly correct. Also there is fix using focusin/focusout out of react lifecycle. For example, using `addEventListener`/`removeEventListener` in `componentDidMount`/`componentWillUnmount`.

However, you will stuck with testing using common react test tools, react can't simulate unsupported events
