### ISSUE TITLE
书写格式错误

### ISSUE THREAD

**Issue by liushuai512** [facebook/react#11413]
`
JSX Prevents Injection Attacks

By default, **React DOM** escapes any values embedded in JSX before rendering them. Thus it ensures that you can never inject anything that's not explicitly written in your application. Everything is converted to a string before being rendered. This helps prevent XSS (cross-site -scripting) attacks.`

错误：加粗的名字出现错误，应该改为

> ReactDom  中间不能有空格，书写格式的错误

**Comment by M-ZubairAhmed** [comment]
so what is your question here ?

**Comment by liushuai512** [comment]
err:By default, **# React DOM** escapes any values embedded in JSX before rendering them. Thus it ensures that you can never inject anything that’s not explicitly written in your application. Everything is converted to a string before being rendered. This helps prevent XSS (cross-site-scripting) attacks.
（错误："中间多一个空格"）

revamp：By default, **# ReactDOM** escapes any values embedded in JSX before rendering them. Thus it ensures that you can never inject anything that’s not explicitly written in your application. Everything is converted to a string before being rendered. This helps prevent XSS (cross-site-scripting) attacks.
（修改：去掉ReactDOM中间的空格）

**Comment by buoyantair** [comment]
Well :O?

**Comment by yongzhi-chen** [comment]
What @liushuai512 was saying is that in the quoted message (probably it is coming from docs), there should not be a space between React and DOM. So React Dom should be changed ReactDom

**Comment by gaearon** [comment]
This doesn't really matter. We use "ReactDOM" when we talk about the entry point in code, but "React DOM" is the colloquial name for the renderer (just like "React Native").

Also please file issues about documentation in https://github.com/reactjs/reactjs.org.

Thanks!
