### ISSUE TITLE
ReactDom 书写格式修改

### ISSUE THREAD

**Issue by liushuai512** [facebook/react#11411]
默认情况下，**React DOM**将转义嵌入在JSX中的任何值，然后再渲染它们。因此，它确保您永远不会注入任何未明确写入应用程序的内容。在呈现之前，所有内容都将转换为字符串。这有助于防止XSS（跨站点脚本）攻击。

加粗的是需要改错的：ReactDOM中间不应该有空格

**Comment by MJCD** [comment]
如果您需要帮助，您将需要翻译。

https://translate.google.com

- Michael

2017-10-31 23:08 GMT+08:00 刘帅 <notifications@github.com>:

**Comment by bvaughn** [comment]
I believe @liushuai512 is just suggesting that we have a space in between "React" and "DOM" that shouldn't be there (eg "React DOM" -> "ReactDOM").

I'm not sure where this is referring to though.

**Comment by bvaughn** [comment]
It seems like this text may have been copied from here: https://maotr.github.io/2017/07/08/react/%E4%BB%8B%E7%BB%8DJSX/

**Comment by bvaughn** [comment]
感谢您报告问题。 很抱歉，但我们无法帮助。 你提到的这个帖子是由别人写的。 请通知该人。

**Comment by monkindey** [comment]
@bvaughn You are patient. Thanks. I think you got that what @liushuai512 mean 

@liushuai512 This is not React issue, you can contact with the author using email
