### ISSUE TITLE
Capture attribute only supports boolean values

### ISSUE THREAD

**Issue by maxschmeling** [facebook/react#11419]
This is a follow-up to #4784.

The `capture` attribute on `input` elements is currently supported, but it is configured as a `HAS_BOOLEAN_VALUE` attribute: https://github.com/facebook/react/blob/1eed302d346bfb8f5db8d88b0e7096d8999d3548/packages/react-dom/src/shared/HTMLDOMPropertyConfig.js#L33

This causes
```
<input type="file" capture="user" />
```
to render as
```
<input type="file" capture />
```

The `capture` attribute supports strings though: https://www.w3.org/TR/html-media-capture/#the-capture-attribute

This is very important for being able to configure the default camera selected on mobile devices.

**Comment by gaearon** [comment]
Should be out in 16.1.1.

**Comment by maxschmeling** [comment]
I have confirmed that updating `react-dom` to 16.1.1 fixes the issue in my project. 👍
