### ISSUE TITLE
JSX 代表 Objects

### ISSUE THREAD

**Issue by liushuai512** [facebook/react#11412]
错误：JSX表示对象  

> Babel将JSX编译成React.createElement()电话。

修改：Babel 转译器会把 JSX转换成一个名为`React.createElement()`的方法调用

**Comment by bvaughn** [comment]
I believe this issue is also referring to the following blog post:
https://maotr.github.io/2017/07/08/react/%E4%BB%8B%E7%BB%8DJSX/

Is this true, @liushuai512? If so, I think you might want to notify the author instead.

**Comment by bvaughn** [comment]
感谢您报告问题。 很抱歉，但我们无法帮助。 你提到的这个帖子是由别人写的。 请通知该人。
