### ISSUE TITLE
Server-side rendering and async routing

### ISSUE THREAD

**Issue by mrasoahaingo** [facebook/react#11414]
Hi!

When I render a synchronous route on server-side and then the client side hydrate the dom, I get a warning because client side asynchronous route doesn't find the component.

![image](https://user-images.githubusercontent.com/12088397/32235451-cf34fbee-be5f-11e7-8112-15a7ee01982b.png)

In other hand react fiber reconciliation tries to remove this non hydratable node. So the page makes a blank flash on client side :(

![image](https://user-images.githubusercontent.com/12088397/32235473-e0ff5522-be5f-11e7-9562-512199aae4ab.png)

**Comment by mrasoahaingo** [comment]
![image](https://user-images.githubusercontent.com/12088397/32248737-e733daf4-be86-11e7-88c4-1a7ee2dcae8c.png)

According to this screenshot, the generated node from server side rendering will be remove. This node (div.home-page) is a dynamic component of the current route

**Comment by mrasoahaingo** [comment]
How can I tell the reconciler to not remove this node, because it will be hydrated by the dynamic imported corresponding component?

**Comment by mrasoahaingo** [comment]
Some code snippets for more explanations

**Routes definition**
```javascript
import {
  HomePage,
} from '../bundles/Bundles';

export default [
  {
    component: HomePage,
    path: '/',
    exact: true,
    strict: true,
  },
];
```

**The Bundles.js used on server side**
```javascript
export const HomePage = syncComponent('HomePage', require('../views/HomePage/HomePage'));
```

**The AsyncBundles.js used on client side**
```javascript
export const HomePage = asyncComponent('HomePage', () => Promise.all([
  import('../views/HomePage/HomePage' /* webpackChunkName: 'HomePage' */),
  importCss('HomePage'),
]));
```

Thanks to the **NormalModuleReplacementPlugin** webpack plugin I'm able to switch from Bundles.js and AsyncBundles.js for server and client rendering

```javascript
     new webpack.NormalModuleReplacementPlugin(/Bundles\.js/, 'AsyncBundles.js'),
```

**HomePage.js component renders a simple div**
```html
<div className="home-page">Home Page</div>
```

**The main Wrapper.js that renders the routes**
```html
      <Route
        render={({ location }) => (
          <div className="app__wrapper">
            <Switch location={location}>
              {routes.map((route, index) => (
                <Route
                  key={route.path}
                  path={route.path}
                  exact={route.exact}
                  render={route.component}
                />
              ))}
              <Route
                key={'not found'}
                path={'*'}
                render={NotFound}
              />
            </Switch>
          </div>
        )}
      />
```

**The html generated on server-side looks like this:**
```html
<div class="app__wrapper">
  <div class="home-page">
    Home Page
  </div>
</div>
```

When I open the chrome debugger timeline, I get a flashing blank frame
![image](https://user-images.githubusercontent.com/12088397/32326338-c05fd52a-bfd2-11e7-9386-44c50a8ee173.png)

Before the blank frame, it's the rendered html, after it's the chunked HomePage.123456.js that is rendered

**Comment by mrasoahaingo** [comment]
That is fiber warning on client side: Did not expect server HTML to contain **div.home-page** in **div.app__wrapper** :(

**Comment by gaearon** [comment]
This pattern has never worked correctly. In React 15 it would still blow away your server rendered markup and replace it on the client.

The solution is to render the same thing both on the client and the server side (just like before). If you're using Promises on the client side, you need to wait for them to resolve before doing hydration. This is not an easy problem, but it's outside of scope of React. Projects like https://github.com/thejameskyle/react-loadable can help you with handling this correctly.

**Comment by mrasoahaingo** [comment]
Thanks! I am looking at another one https://github.com/ctrlplusb/react-async-component
