### ISSUE TITLE
React.Children support for Call and Return types

### ISSUE THREAD

**Issue by MatteoVH** [facebook/react#11416]
Include React `Call`s and `Return`s (as defined in [this sub-repo](https://github.com/facebook/react/tree/master/packages/react-call-return)) in the children enumerated over by `React.Children`. Should be similar to the `Portal` support added in #11378. This issue is a follow up to #11373 and was [suggested by @gaearon](https://github.com/facebook/react/pull/11378#issuecomment-340789791).

**Comment by MatteoVH** [comment]
I'd like to take this. Should be able to have a PR up tonight. 🙂

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/11422.
