### ISSUE TITLE
Raising issue Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills

### ISSUE THREAD

**Issue by jovanliuc** [facebook/react#11428]
I want to know how suppress this warning in IE < edge( such as IE 9, IE10, IE11 ), like below:
![2017-11-02_162715](https://user-images.githubusercontent.com/8048836/32316488-5e8656ee-bfeb-11e7-81e4-9e123836cd81.png)

could some guys help me, thanks so much.

**Comment by gaearon** [comment]
```
npm instal --save raf
```

Then as your first import in entry point, before React:

```js
import 'raf/polyfill`;
```

**Comment by jovanliuc** [comment]
okay, I'm appreciated that, thanks so much to you...    ^-^

**Comment by jovanliuc** [comment]
okay, I'm appreciated that, thanks so much to you... ^-^ @gaearon
