### ISSUE TITLE
Release script follow-up items

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#11435]
Today I used the [new release script](https://github.com/facebook/react/tree/master/scripts/release) for the first time to publish `16.1.0-beta`. Here are a couple of things I noticed that I want to follow-up on:

### PR #11434
- [x] Auto-install (or update) release script Yarn deps before running

### PR #11437
- [x] `publish` script should `git tag -a ${version}`. I manually tagged the `16.1.0-beta` release.
- [X] The post-build test instructions should show fully-qualified paths to prevent you from accidentally verifying the wrong build (eg the checkout the release script is running from rather than the `-p` path)
- [x] `publish-to-npm` check should handle pre-1.0 packages. (This one failed for the `0.2.0` reconciler release b'c it expected it to be 16.1.0-beta.) For that matter, it should have probably been `0.2.0-beta`
- [x] When publishing a stable release (`@latest`) also update the next release to point to it.

**Comment by blling** [comment]
Not `16.1.0-beta.1`,`16.1.0-beta.2`,`...` ?

**Comment by bvaughn** [comment]
I don't think it really matters. `16.1.0-beta` is less than `16.1.0-beta.1` (or `16.1.0-beta.1` for that matter) so if we need to release another beta we can still use the `.1` suffix.

**Comment by bvaughn** [comment]
Closed via #11434 and #11437
