### ISSUE TITLE
Fix `yarn linc` command on Windows

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11444]
It currently fails on Windows because it depends on grep:

https://github.com/facebook/react/blob/61d35ce1f3f9c0706ed3630a2650d578497ae8c2/package.json#L101

We should find a way to make it do the same in a cross platform way (e.g. from a Node script).

**Comment by xjlim** [comment]
I'd like to work on this.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/11446#issuecomment-341828958

**Comment by gaearon** [comment]
@xjlim Can you please help checking whether this works? https://github.com/facebook/react/pull/11446#issuecomment-341829465
