### ISSUE TITLE
Ensure linted bundles exist

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11443]
I added validation of built bundles in https://github.com/facebook/react/pull/11432.

However I actually messed it up, and ESLint wasn't running on any files because of invalid arguments. I fixed that here: https://github.com/facebook/react/commit/61d35ce1f3f9c0706ed3630a2650d578497ae8c2#diff-edcddc0e0143d5a5a93d0951fd599794

We should fail the build if the glob patterns it's searching for don't exist.

**Comment by misoguy** [comment]
Can I work on this if no one else is on it yet? 😄

**Comment by misoguy** [comment]
I opened a PR regarding this issue. It would be nice if you could take a look @gaearon 😄

**Comment by gaearon** [comment]
Thank you so much!
