### ISSUE TITLE
Investigate DCE regression

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11450]
Seems like we started bundling persistent reconciler in DOM bundles. Maybe this negated some effect from ES modules (even though they were a net win). Need to look into why this happened.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11453

**Comment by kuropyatnik** [comment]
Just a simple random comment. How can i create a comment here through REST API?

**Comment by gaearon** [comment]
No idea. Please don't use our issues for unrelated questions. Thanks.

**Comment by gaearon** [comment]
Fixed https://github.com/facebook/react/pull/11453.
