### ISSUE TITLE
Improve formatting of errors when building React

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11454]
Currently when the build fails (e.g. due to a missing named export), the message is pretty ugly:

<img width="1033" alt="screen shot 2017-11-04 at 13 12 31" src="https://user-images.githubusercontent.com/810438/32405680-d618d2e6-c161-11e7-9b91-e0241c7c3eed.png">

It would be nice to display the relevant line inline with syntax highlighting, sort of like Babel does it. Maybe Babel's `babel-code-frame` could be helpful (not sure).

To reproduce, fail the build by removing some `export` somewhere and run `yarn build`. (Tip: `yarn build core --type=NODE_DEV` is the fastest way to build just `packages/react/*` and that might be enough to reproduce and iterate on the error message.)

The relevant logic for displaying build errors is probably somewhere in `scripts/rollup/build.js`.

**If you'd like to work on this please comment here, so we don't have many people working on the same thing.**

**Comment by misoguy** [comment]
I'd like to work on this 😄
