### ISSUE TITLE
Check .length before accessing characters

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11460]
See comment here: https://github.com/facebook/react/pull/11457#discussion_r148954193.

Although it seems very unlikely that someone would pass a one-character prop, the price (at least in versions of V8 in Chrome right now) is reported to be about 10x.

So we should check `.length` first and then do the comparison.

**Please comment if you want to take this issue.**
**If somebody already commented, please let them finish it.**

**Comment by xjlim** [comment]
@gaeron I'd like to work on this.

**Comment by xjlim** [comment]
> Although it seems very unlikely that someone would pass a one-character prop, the price (at least in versions of V8 in Chrome right now) is reported to be about 10x.

@gaearon Just curious, is this documented somewhere?
