### ISSUE TITLE
When use React.cloneElement original element key changed?

### ISSUE THREAD

**Issue by robberfree** [facebook/react#11464]
when i  use React.cloneElemen to clone a element.
i found that the key was changed, add '.$' to the original key.
when i read the doc about cloneElemnt, it said
> key and ref from the original element will be preserved.

do i miss some thing?
1. my code:
```js
render() {
    let children = React.Children.map(this.props.children, (child, index) => {
      console.log('original element', child.key);
      return React.cloneElement(child, {
        addChild: this.addChild,
        removeChild: this.removeChild
      });
    });
    return children === undefined ? null : children;
  }
```
2. console message
```js
original element tyughjijnb
```
3. capture of react-dom structure
![2017-11-06 11 20 16](https://user-images.githubusercontent.com/15938895/32423956-8dfdf7f0-c2e4-11e7-98ba-544643224ac6.png)

thanks.

**Comment by gaearon** [comment]
This is necessary to correctly handle nested arrays. Elements at different nesting levels will receive different prefixes. This way even if you have same keys inside different nested arrays, mapping over them will still produce a valid flat array with equivalent behavior.
