### ISSUE TITLE
assignment for jsx in double circulation

### ISSUE THREAD

**Issue by tageecc** [facebook/react#11476]
**Do you want to request a *feature* or report a *bug*?**
bug，maybe~

**What is the current behavior?**
- the code is :
```js
import React, { Component } from 'react';

class App extends Component {

    render() {

        let res = new Array(2).fill(new Array(2));
        for(let i =0;i<2;i++){
            for(let j=0;j<2;j++){
                console.log(res[i][j]);
                res[i][j]=<div>{'i:'+i+',j:'+j}</div>;
            }
        }
        return res;
    }
}

export default App;

```
- and the result print on the page is:

![image](https://user-images.githubusercontent.com/8930882/32480507-268f362e-c3ca-11e7-8d43-e9d130efd3e9.png)

**What is the expected behavior?**
it's very strange, `i` should not start with 0?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
"dependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.17"
  }
```

**Comment by gaearon** [comment]
This fills the top-level array with two references *to the same Array object*:

```js
let res = new Array(2).fill(new Array(2));
```

So in the second iteration of the loop, you override the values set during the first iteration.
