### ISSUE TITLE
let `yarn build` warn if local yarn version not support workspaces

### ISSUE THREAD

**Issue by monkindey** [facebook/react#11478]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

I got the error below when my local yarn version was v0.21.

```js
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at createBundle (~/Documents/repo/dev/react/scripts/rollup/build.js:536:31)
    at tasks.push (~/Documents/repo/dev/react/scripts/rollup/build.js:632:13)
    at runWaterfall (~/Documents/repo/dev/react/scripts/rollup/build.js:687:23)
    at nextPromise.then (~/Documents/repo/dev/react/scripts/rollup/build.js:693:12)
    at <anonymous> code: 'MODULE_NOT_FOUND'
```

I think maybe should upgrade my yarn because the `react` module land at package folder.

And I upgrade yarn, and try to exec the `yarn` command, then `yarn build`, and it work.

~~**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**~~

No

**What is the expected behavior?**

I think it would be great if we throw a warning not a ambiguous error.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

* React v16.1
* OSX

**Comment by gaearon** [comment]
Sounds good, wanna do it? I think 1.2.1 is the minimal version we want to support.

**Comment by monkindey** [comment]
yes, I am glad to do it. Any warning phrases recommended ?

**Comment by gaearon** [comment]
Don't care strongly, send a PR and we can discuss. Worth checking if we already have a similar thing for unsupported Node versions. Then wording should be similar.

**Comment by monkindey** [comment]
😀 All right. But in case of node version, maybe we can use the [engines](https://docs.npmjs.com/files/package.json#engines) field in `package.json` ?

**Comment by gaearon** [comment]
Maybe we already do? I don't remember.

**Comment by jquense** [comment]
yarn 1.0.0+ will respect and warn for `engines` at the app level which is great, the catch of course is that if you are on an older version of yarn you won't get the warning b/c it was added in v1 :P

**Comment by monkindey** [comment]
hi, @gaearon . Why I committed and will run `npm run version-check && node scripts/rollup/build.js` automatically? Is it some hooks for that or I miss something?

**Comment by monkindey** [comment]
@jquense Thanks for your reminding, The yarn [engines](https://yarnpkg.com/lang/en/docs/package-json/#toc-engines) is awesome, which can specify yarn version. 

And do we also need to check node version when executing `yarn build` command?

**Comment by monkindey** [comment]
I found what happen, when I committed with message 

``let `yarn build` warn if local yarn version not support workspaces``

and will execute the yarn build command, it's interesting.

But it's ok when I remove the backtick **`**.

**Comment by gaearon** [comment]
Meh. I think by now it's likely everybody's using recent enough versions that this doesn't matter.
