### ISSUE TITLE
Text next to Element is not render on page in React v16

### ISSUE THREAD

**Issue by vchyzhevskyi** [facebook/react#11485]
Hello there,

Today I spotted a bug which causes the text next to element is not render on page in react `v16.1.0-beta`.

```
<h4>
    <span>Quick</span> Job Search
</h4>
```

I'm not sure if this is a designed behaviour, but it was working perfectly in React v15.

Let me know if you need any information.

**Comment by aweary** [comment]
@vchyzhevskyi can you please provide an example reproducing your issue, along with some more details about it? I [can't reproduce the issue with the latest beta](https://jsfiddle.net/Aweary/rr3p2htz/).

**Comment by vchyzhevskyi** [comment]
@aweary Hi Brandon, I forgot to mention - I use server-side rendering. Client-side rendering in your example seems to works fine.

Server returns HTML without that text: `<h4><span>Quick</span></h4>`, so I guess the problem is on server side.

Please let me know if you can't reproduce the issue - I will setup blank repo with code to show this if that will be necessary.

**Comment by aweary** [comment]
@vchyzhevskyi thanks for clarifying. [Here's a version of that JSFiddle using `ReactDOMServer.renderToString`](https://jsfiddle.net/Aweary/41juzvrh/), which also doesn't reproduce the issue.

> I will setup blank repo with code to show this if that will be necessary.

👍  feel free to ping me when you have a consistent reproduction.

**Comment by gaearon** [comment]
We'll need that reproducing case pretty soon if we want to fix this before the release.

**Comment by vchyzhevskyi** [comment]
@aweary @gaearon I'm so sorry, this was an issue in my abstraction layers. The upgrade from v15 to v16 was in same time when I applied fix that produces this strange behaviour - so I decided that this is an error in React.

Please close this issue, as there's no bug - my bad. Thank you for your time.
