### ISSUE TITLE
Uncaught error thrown twice ?

### ISSUE THREAD

**Issue by slim-hmidi** [facebook/react#11499]
I have the same problem mention on this issue: [Unhandled error is displayed twice](https://github.com/facebook/react/issues/10384).
The error was : 
![cross_origin](https://user-images.githubusercontent.com/31925861/32598947-55103198-c53b-11e7-8230-87cba756fc0f.png)

Based on the @gaearon comment and [#10474](https://github.com/facebook/react/issues/10474)

> For context, the reason it happens is because we intentionally let the browser interpret an error as uncaught before we rethrow. 

I understand that is thrown by the browser (source file was `searchAutocomplete.jsx`) and the second thrown by the react (source file was `react-dom.development.js`). 
Added to that : 

> If you follow the advice in the error and add an error boundary (which you should!), you will only see the error once. So that's not a huge problem in day-to-day workflow. In fact it nudges people to add error boundaries which is nice.

In this case there is no advice mentioned by the error, How can I get the error to be thrown once ?

**Comment by gaearon** [comment]
You should see a link to the error boundaries documentation next to the error. (Not directly in it, but most likely below.)

The link leads here: https://reactjs.org/docs/error-boundaries.html

That said I think the errors in event handlers would still be displayed twice. This is a little unfortunate but shouldn't prevent you from fixing them 🙂

**Comment by slim-hmidi** [comment]
@gaearon I'm trying to understand how the error will be thrown once if it is detected and in this case does it thrown only by react or by the browser. If we consider this error was shown once, does this thrown by `react-dom.development.js` or by the browser?
