### ISSUE TITLE
npm run build has an error

### ISSUE THREAD

**Issue by stephenkingsley** [facebook/react#11491]
This is a bug! My nodejs is v7.0.0. Followed these steps:
1. git clone 
2. npm install
3. run `npm run build`

the script has an error:
```js
npm run build

> @16.0.0 build /Users/ucweb/Documents/github/react
> npm run version-check && node scripts/rollup/build.js


> @16.0.0 version-check /Users/ucweb/Documents/github/react
> node ./scripts/tasks/version-check.js

 BUILDING  react.development.js (umd_dev)
TypeError: Cannot read property 'specifier' of undefined
    at /Users/ucweb/Documents/github/react/node_modules/rollup/dist/rollup.js:9593:47
```

I think this is strange...

**Comment by stephenkingsley** [comment]
I think the problem maybe is rollup@0.41.6

**Comment by monkindey** [comment]
You can use `yarn` and run `yarn build`, and yarn version should support `workspaces` feature.

**Comment by gaearon** [comment]
Yes, we don't support using npm for development anymore. Please run `yarn` and `yarn build`.

**Comment by stephenkingsley** [comment]
Yes! Thank you very much! And this is my fault!
