### ISSUE TITLE
React 16 upgrade still looking for react.js even though it doesn't exist anymore

### ISSUE THREAD

**Issue by lindslev** [facebook/react#11497]
**Do you want to request a *feature* or report a *bug*?** 🐛 

**What is the current behavior?**
Upgrading to React 16 means node_modules/react/react.js no longer exists. However, when watching/bundling files with webpack, webpack sometimes trips and errors out trying to locate node_modules/react/react.js. It may very well be a webpack issue and not a React issue but hoping someone here can help me out. Can't get to the bottom of it. Seems to be a timing thing - only errors out every couple of file changes / re-bundles, and the rest of the time it works normally. 💀 

My webpack config is simple, `watch` is set to true, and I use babel-loader with a `.babelrc` and `es2015` and `react` as presets.

**What is the expected behavior?**
Never look for node_modules/react/react.js when bundling with webpack. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** Exists with React 16, no problems in previous versions

**Comment by gaearon** [comment]
There is no reason webpack would look there unless:

* you are directly importing this file somewhere
* some other library is directly importing this file
* you have it somewhere in your configuration
* you use some disk caching solution, and your disk cache is corrupted or stale

Please bring it up with webpack and provide a reproducing project for them it you experience this consistently.

**Comment by gaearon** [comment]
Also it probably wouldn't hurt to do the good old "delete node_modules and run npm install" dance. :-)

**Comment by lindslev** [comment]
haha yeah @gaearon i purged node_modules a startling number of times. didn't expect the react team to have much of an explanation for this, just figured i'd post an issue in case anyone else happened to run into the same thing. will circle back with any findings. thanks dan!

**Comment by gaearon** [comment]
Yeah, sorry you're running into this. If you can create an isolated example that consistently reproduces this I can try to look into it.
