### ISSUE TITLE
Default Browser on Android 4.0.x Not Working (Blank) to Access Web Build From React

### ISSUE THREAD

**Issue by yonisetiawan** [facebook/react#11490]
I have a problem, me build web with React and i tried to access with default browser on android.
on android 4.0.x not working (blank)
and on android 4.1 above is wokring

we write with es 6 and compile es 5, but it not working, if i test in android default browser 4.0.x not working (blank)

default browser on android 4.0.x not support with es 5, right ?

can someone help me ?

**Comment by gaearon** [comment]
React supports browsers that implement ES5.

React also depends on Map, Set, and requestAnimationFrame. This is described here:

https://reactjs.org/docs/javascript-environment-requirements.html

Please make sure you polyfill them on older browsers. 

There are hundreds of different browsers and we can't give advice about specific ones.

I hope the above helps, but if you can verify that Android 4.0.0 supports ES5, you polyfilled Map, Set, and rAF, and it still doesn't work, please provide the exact error messages and we can look further.
