### ISSUE TITLE
Add [data-reactroot] back for ReactDOM.render

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [facebook/react#11494]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
in React v16, `[data-reactroot]` is only added when using `ReactDOMServer.renderToString()`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**
`ReactDOM.render()` should also tag the tree root with `[data-reactroot]` for React detection purposes

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.0.0

**Comment by gaearon** [comment]
`[data-reactroot]` has always been an implementation detail, and I don’t think we plan to emit extra attributes to aid developer tools that try to detect React on the page. The officially supported [React DevTools](https://github.com/facebook/react-devtools) extension can detect React, and that’s what we recommend to use for this purpose.

If you really want to, you can try looking for nodes with properties starting with `_react`. DOM nodes managed by React currently have them (but we don’t guarantee it in the future).
