### ISSUE TITLE
React renders differently on server and client

### ISSUE THREAD

**Issue by jeenamanuel** [facebook/react#11500]
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div data-reactroot="" da
 (server) <div class="container" da

How come it's rendered different? what is the solution

I have tried with renderToStaticMarkup instead of renderToString ..but it is not working

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
