### ISSUE TITLE
Consider including directory name into the stack trace for some files

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11519]
See https://twitter.com/deadcoder0904/status/929050109425229824

Maybe if the file is called `index.js` (pretty common with some directory structures) we should include the directory name into the short component stack trace.

**Comment by gaearon** [comment]
Not sure how well that would work but I'd love to see an example. You'll need to change `describeComponentFrame()` if I recall correctly.

**Comment by xjlim** [comment]
@gaearon I'd like to work on this.

**Comment by gaearon** [comment]
Sounds good, it's yours!
