### ISSUE TITLE
Warn when component has PropTypes rather than propTypes

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11510]
See https://github.com/reactjs/reactjs.org/issues/268#issuecomment-343402728.

Feels like an easy mistake to make, and easy for us to detect.

**Comment by M-ZubairAhmed** [comment]
hey can I take this ?

**Comment by blling** [comment]
@M-ZubairAhmed  Just do it.

**Comment by M-ZubairAhmed** [comment]
could you please guide me to where to start with this issue? thank you

**Comment by gaearon** [comment]
Search the code for where we read `.propTypes` and add the check there.

**Comment by M-ZubairAhmed** [comment]
got it.

**Comment by kotAPI** [comment]
is this done?

**Comment by gaearon** [comment]
It's taken by @M-ZubairAhmed.

**Comment by xxblakefailxx** [comment]
@gaearon Should this be closed now?
