### ISSUE TITLE
Unify linc and lint build tasks

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11516]
Currently these two tasks don't share any code:

* lint all (https://github.com/facebook/react/blob/master/scripts/tasks/eslint.js)
* lint changed (https://github.com/facebook/react/blob/master/scripts/tasks/linc.js)

We should make them share the code (using Node API like `linc` currently does) and move that shared code to `scripts/eslint`.

**Comment by sjy** [comment]
I am interested in this beginner-friendly  issue. I will make a pr asap;

**Comment by sjy** [comment]
Please review the PR https://github.com/facebook/react/pull/11518

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11518.
