### ISSUE TITLE
Bunch of cannot find module errors from react-dom

### ISSUE THREAD

**Issue by rico345100** [facebook/react#11514]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I didn't used any version specific features, but after react16, my react module failed to transpile with these errors:

```bash
Error: Cannot find module 'react/lib/ReactCurrentOwner' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactComponentTreeHook' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactCurrentOwner' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactComponentTreeHook' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactComponentTreeHook' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactCurrentOwner' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/React' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/getNextDebugID' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactComponentTreeHook' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactCurrentOwner' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/React' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactCurrentOwner' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/React' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactComponentTreeHook' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactComponentTreeHook' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/React' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactComponentTreeHook' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
Error: Cannot find module 'react/lib/ReactCurrentOwner' from 'F:\dev\react\react-multimedia-capture-example\node_modules\react-dom\lib'
```

You can reproduce this by learn this example with React 16(currently used react 15, so you have to upgrade): https://github.com/rico345100/react-multimedia-capture-example

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@16.1.0
react-dom@15.6.2

Tested on Windows 10 with Chrome browser, but browsers aren't related, so meaningless. And yes, it worked before react 16 :)

**Comment by gaearon** [comment]
My guess is you updated only `react-dom` but not `react`.

Please update both packages and then restart the development server.

**Comment by rico345100** [comment]
No, I updated both. Also I just reinstall both(also removed from package.json), still get same version of react-dom@15.6.2.
If you are correct, why react didn't updated package version of react-dom?

**Comment by gaearon** [comment]
You can try creating a new project and running `npm install --save react react-dom`. You should get the 16 version for both. If you don't, you might be behind an outdated npm proxy.

I don't know why you can't update them in your project. But the 16 version of both packages *is* on npm (and has been for months) so please bring it up with npm if you keep running into issues.

>If you are correct, why react didn't updated package version of react-dom?

I don't understand what you're asking.

**Comment by rico345100** [comment]
@gaearon Thanks, I didn't know that react-dom also released new version because every time reinstall react-dom from npm gives me 15.6.2. I installed 16.1.0 manually and now it works.
