### ISSUE TITLE
Add function name for breakpoint tracing

### ISSUE THREAD

**Issue by monkindey** [facebook/react#11529]
**Do you want to request a *feature* or report a *bug*?**

Maybe Feature

**What is the current behavior?**

I am interesting in what happen in React Fiber, and try to use breakpoint to trace React render function. I found the call stack has `(anonymous)` function name, it was made by [below](https://github.com/facebook/react/blob/v16.1.0/packages/react-dom/src/client/ReactDOM.js#L746-L748)

```js
DOMRenderer.unbatchedUpdates(() => {
   DOMRenderer.updateContainer(children, newRoot, parentComponent, callback);
});
```

**The captured picture**

![image](https://user-images.githubusercontent.com/6913898/32690119-7f9ad248-c6b6-11e7-962e-7ffbe33b17a0.png)

~~**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**~~

Sorry No.

**What is the expected behavior?**

How about define function name for this ?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v16.1
OSX

**Comment by gaearon** [comment]
Happy to take a PR for this but I don't think it's too important. All important functions are named. I can't come up with a non convoluted name for this callback though so I'd just leave it like this.

**Comment by monkindey** [comment]
Thanks for quick reply. BTW, Any plan about [Implementation note](https://reactjs.org/docs/implementation-notes.html) for Fiber 😃. The stack one is awesome, It would great if React team elaborate the Fiber.

**Comment by gaearon** [comment]
Eventually. :-)
Unless somebody else writes that up before us.
