### ISSUE TITLE
Cannot disable form submission using onSubmit handler

### ISSUE THREAD

**Issue by patsissons** [facebook/react#11522]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
it is not currently possible to prevent form submission using the `onSubmit` handler

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
sample code at https://codesandbox.io/s/jpx80rj6vy

**What is the expected behavior?**
`form` should never submit because `onSubmit` returns false every time

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16

simplified code snippet below so you don't have to load the sandbox repro
```
<form onSubmit={() => false}>
  <input type="text" name="bar" placeholder="type and hit enter" />
</form>
```

**Comment by bonusrk** [comment]
Doesn't `e.preventDefault(`) make this job?
```
<form onSubmit={(e) => e.preventDefault()}>
  <input type="text" name="bar" placeholder="type and hit enter" />
</form>```

**Comment by gaearon** [comment]
The answer above is correct. React does not support returning `false` from event handlers for this purpose. Please be explicit about what you're trying to do (stop propagation, prevent default, or both).

**Comment by Flam3rboy** [comment]
I have the same issue and made a Codepen for a minimal demo of the problem:
https://codepen.io/Flam3rboy/pen/JjXpOEd

The problem occurs if you try to submit a form over a ref
```js
this.form.current.submit();
```
