### ISSUE TITLE
Getting warning about unique "key" prop despite it being added correctly.

### ISSUE THREAD

**Issue by RusinovAnton** [facebook/react#11537]
**Do you want to request a *feature* or report a *bug*?**
Bug  

**What is the current behavior?**
As reported in https://github.com/RusinovAnton/react-select3/issues/3, when using my library with React v16 there is error:
```
proxyConsole.js:56 Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in span
    in SelectDropdown
    in span
    in Select (at App.js:18)
    in div (at App.js:17)
    in div (at App.js:16)
    in App (at index.js:7)
```

**Demo**
https://codesandbox.io/s/4jnxzxwkp9
Steps to reproduce:
- Go to demo on codesandbox
- Try to choose some option
- See console - there is an error :(

[here](https://github.com/RusinovAnton/react-select3/blob/master/src/components/SelectOptionsList.js#L35) keys are being added which work fine with react 15

**What is the expected behavior?**
There is no error when keys being added

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 16.1.0
worked fine with react 15.4

**Comment by clemmy** [comment]
Do you think you can isolate the bug a bit more? For example, output the contents of `optionsList ` at this [line](https://github.com/RusinovAnton/react-select3/blob/f01c9ef14d1029f90b2bc4f2686bfb4f9e41c1af/src/components/SelectOptionsList.js#L42).

**Comment by gaearon** [comment]
You are using [these two transforms](https://github.com/RusinovAnton/react-select3/blob/f01c9ef14d1029f90b2bc4f2686bfb4f9e41c1af/rollup.config.js#L48-L49) in a development build of your library.

They are **not** suitable for development, and may produce false positive warnings. Babel documents this, but not consistently: https://github.com/babel/babel/issues/6813.

Please remove them from the development build of your library.

**Comment by RusinovAnton** [comment]
Thanks, Dan Abramov.
