### ISSUE TITLE
stopImmediatePropagation is not available for synthetic events

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [facebook/react#11547]
In order to call this method, you'd have to access it via `event.nativeEvent.stopImmediatePropagation()`: https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation

It'd be awesome if this was supported on `event` itself. I did see a [prior issue](https://github.com/facebook/react/issues/1734) for this, but it was for a use case that sIP wasn't required for.

For a specific use case: if you want to kill hover events for touch input, `onTouchStart` will trigger `onMouseOver` and `stopImmediatePropagation` cancels that internal cascade.

**Comment by jquense** [comment]
I think sIP method on the Synthetic even would just prozy to `event.nativeEvent.stopImmediatePropagation` since there isn't anything in the Synthetic event system that would change or need to be implemented, given that components only ever have one handler per event anyway. I wouldn't be opposed to adding it as a convenience but I do think it hides the fact that sIP isn't supported over all React's browsers (though maybe it is now that IE8 is gone)

**Comment by evan-scott-zocdoc** [comment]
![screen shot 2017-11-13 at 5 33 11 pm](https://user-images.githubusercontent.com/25586630/32752857-be51302a-c898-11e7-8e7e-6819239f4849.png)

**Comment by gaearon** [comment]
> if you want to kill hover events for touch input, onTouchStart will trigger onMouseOver and stopImmediatePropagation cancels that internal cascade.

Could you please provide me with an example that demonstrates this?

**Comment by mensonones** [comment]
I have a similar problem. I use event.nativeEvent.stopImmediatePropagation() to prevent the rootClose event (react bootstrap) on a popover that has a dropdown. But in my tests I have the following error:

e.nativeEvent.stopImmediatePropagation is not a function

there is even a solution, but there are many tests to replicate such a solution.

the error is caused basically by the click simulation. I think if I had a synthetic event for the same it would be interesting.

**Comment by Bosch-Eli-Black** [comment]
Can we this get reopened?

**Comment by mensonones** [comment]
What is your problem with the issue, @Bosch-Eli-Black ?

**Comment by Bosch-Eli-Black** [comment]
@mensonones For me, it was nothing special. I just tried to call `event.stopImmediatePropagation()` and was slightly surprised to find that it didn't work :)

**Comment by Mr-Wallet** [comment]
I concur with the above. The documentation for [SyntheticEvent](https://reactjs.org/docs/events.html) states:
> It has the same interface as the browser’s native event, including stopPropagation() and preventDefault(), except the events work identically across all browsers.

Not having `stopImmediatePropagation` on it violates the promise that the interface is the same.

**Comment by tamzinblake** [comment]
If this won't be fixed, at least fix the docs to stop claiming that the interface is the same when it's not.

**Comment by mensonones** [comment]
@gaearon

**Comment by diegohaz** [comment]
Please, correct me if I'm wrong, but it seems that the biggest problem here is that native events aren't actually attached to the individual elements, but rather to the root document.

ReactDOM will pass the synthetic events down to the individual handlers you attached to React elements. So, calling `event.nativeEvent.stopImmediatePropagation()` there would actually prevent any event of the same type from happening on any element, not only on that one with the event handler.

If that's correct, `event.nativeEvent.stopImmediatePropagation()` should almost never be used.

**Comment by Mr-Wallet** [comment]
That's true enough, but in our case we fully understood that and that's exactly what we wanted (for reasons that are too specific to be worth elaborating, but it involved avoiding a refactor in the short term). We still suffered from misleading documentation even though we mostly understood the consequences of what we were trying to do.

**Comment by shakhbulatgaz** [comment]
I think @Mr-Wallet is right here.
Changing how SyntheticEvent works is not necessary, but at least this behavior should be acknowledged in the documentation.

It was a big surprise when I've found my answers on StackOverflow, not the official docs.
Especially considering that the docs promise that this method acts the same as a native one.

 https://stackoverflow.com/questions/24415631/reactjs-syntheticevent-stoppropagation-only-works-with-react-events
