### ISSUE TITLE
Ignore system directories in the build script

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11544]
Just noticed that running `./scripts/release/build.js -v 16.1.1` gives me:

```
 ERROR  ENOTDIR: not a directory, open '/Users/gaearon/p/react/packages/.DS_Store/package.json'

Error: 
    at Object.fs.openSync (fs.js:653:18)
    at fs.readFileSync (fs.js:554:33)
    at readdirSync.filter.dir (/Users/gaearon/p/react/scripts/release/utils.js:31:36)
    at Array.filter (<anonymous>)
    at getPublicPackages (/Users/gaearon/p/react/scripts/release/utils.js:29:36)
```

We should ignore system directories there.

**Comment by HardikModha** [comment]
Hi..Can I pick this?

**Comment by skiritsis** [comment]
Hey, I'd like to take a look and submit a PR for this issue.

**Comment by gaearon** [comment]
@HardikModha was first :-).

**Comment by HardikModha** [comment]
Thanks, @gaearon. This will be my first Open Source Contribution.  So, Can you suggest me where should I start? Do I need to make the change in `utils.js` and exclude the system files before doing `JSON.parse`?

**Comment by HardikModha** [comment]
@gaearon I've pushed a commit to fix the issue. Thank you for giving me the opportunity. This is my first ( 🎉 ) little Open Source Contribution.

**Comment by gaearon** [comment]
Thanks for sending the fix!
