### ISSUE TITLE
Why I don't get keys warning in this case?

### ISSUE THREAD

**Issue by giorgim** [facebook/react#11540]
Below example generates three buttons based on state (which can change).
Why I don't get warning that I should use keys?

```
class Hello extends React.Component {
  constructor(props) 
  {
    super(props)
    this.state={test: 1};
    this.arr=[1,2,3];
  }
  
  
  componentDidMount(){
  setTimeout(()=>{this.setState({test:2})}, 2000);
  }
  
  render() {
    return (<div>
    {this.state.test==1 ? <button>1</button> : ""}
    {this.state.test==1 ? <button>2</button> : ""}
    {this.state.test==2 ? <button>3</button> : ""}
    {this.state.test==2 ? <button>4</button> : ""}

    {
    /*
      this.arr.map(function(item){
      return <button>2</button>
      })
      */
    }
    </div>);
  }
}
```

PS. If I uncomment the lines with `map` function I do get that warning though. Why I don't get this warning in first case? (how does it know without keys  that two buttons -3 and 4 - which are going to be rendered after setTimeout are now different - from 1 and 2 -?)

**Comment by gaearon** [comment]
Because you put elements in specific "holes" in a statically known JSX structure. React knows these divs can't possibly reorder (think about it—how would you sort them without changing the code?). Therefore it is safe to implicitly key them by their index.

**Comment by giorgim** [comment]
@gaearon I think I got you, so in this case react still attached the keys though implicitly?

**Comment by gaearon** [comment]
Kind of. Whether React really attaches the key or not is an implementation detail, but it behaves as if they keys were set to the child indexes in this case. Again, this is only safe because it knows they can never reorder.

**Comment by giorgim** [comment]
@gaearon I think I got it now will come back to it later though. For some reasons I could not answer this myself even after having read the docs

**Comment by gaearon** [comment]
The docs don't really mention it, but then it's also a bit of an obscure corner. People don't often ask about this.

**Comment by giorgim** [comment]
@gaearon Yeah but I don't like to take things for granted, rather understand how it really works.

**Comment by gaearon** [comment]
You can always ask here. 😉 
For more technically minded users we’re always happy to provide insight into how things really work.
