### ISSUE TITLE
overflowX "none"

### ISSUE THREAD

**Issue by davidrenne** [facebook/react#11556]
Hi there, I just spent a half hour realizing that I was passing the string of "none" to an overflowX and there was no warnings or logs in my JSX for a style I was passing invalid.  It simply removed it from my inline styles with no warnings or errors.

I would like to send a pull request to react to help with this and add logging for developers who accidentally pass an invalid string to warn them that things like this are invalid.

I was even passing it in a class and my browser was barfing too which helped me realize that its overflowX "hidden" is the valid attribute CSS value.

Any idea if there is a way we can log this to console for invalid CSS attributes that just "disappear" from the JSX final inline style converted object?  I would love for there to be logs on invalid css attributes or maybe there is some configuration I am missing to see these logs from react?  It was very annoying to try to get this overflow and "none" is invalid.

Next time I am doing CSS and something is missing, I will look up the mozilla manual.

Thanks for any pointers with this annoying little bugger with JSX.

**Comment by gaearon** [comment]
I don't think what you're describing has anything to do with JSX (the syntax). It is about the browser behavior of silently dropping invalid style values. It has been proposed before, and it's not clear how to do this in a sensible way. You can read the past discussion in https://github.com/facebook/react/issues/8182.
