### ISSUE TITLE
Can not rendered UI with react and react-dom 16.1.1

### ISSUE THREAD

**Issue by nafisahmedkhan9** [facebook/react#11551]
This is my code:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, hashHistory} from 'react-router'

import Archives from './modules/Archives';
import Layout from './modules/Layout';
import Featured from './modules/Featured';
import Settings from './modules/Settings';
console.log('hi');
ReactDOM.render((
    <Router history={hashHistory}>
        <Route exact path='/' component={Layout}>
            <Route exact path='/featured' component={Featured}/>
            <Route exact path='/archives/:id' name='archives' component={Archives}/>
            <Route exact path='/settings' name='settings' component={Settings}/>
            </Route>
    </Router>
    ),document.getElementById('app'));
```

Error is on browser: 
```
     Uncaught TypeError: Cannot read property 'func' of undefined
    at Object.exports.__esModule (index.js:sourcemap:552)
    at __webpack_require__ (index.js:sourcemap:20)
    at Object.<anonymous> (index.js:sourcemap:1634)
    at Object.exports.__esModule (index.js:sourcemap:1724)
    at __webpack_require__ (index.js:sourcemap:20)
    at Object.exports.__esModule (index.js:sourcemap:2882)
    at __webpack_require__ (index.js:sourcemap:20)
    at Object.<anonymous> (index.js:sourcemap:13246)
    at __webpack_require__ (index.js:sourcemap:20)
    at Object.<anonymous> (index.js:sourcemap:4349)
```

**Comment by nafisahmedkhan9** [comment]
In ReactDOM.render((
       <Router history={hashHistory}>
        <Route exact path='/' component={Layout}>
            <Route exact path='/featured' component={Featured}/>
            <Route exact path='/archives/:id' name='archives' component={Archives}/>
            <Route exact path='/settings' name='settings' component={Settings}/>
            </Route>
    </Router>
),document.getElementById('app'))

**Comment by nafisahmedkhan9** [comment]
i have used this code in reactDom.render

<Router history={hashHistory}>
        <Route exact path='/' component={Layout}>
            <Route exact path='/featured' component={Featured}/>
            <Route exact path='/archives/:id' name='archives' component={Archives}/>
            <Route exact path='/settings' name='settings' component={Settings}/>
            </Route>
    </Router>

**Comment by gaearon** [comment]
Your code is probably reading `React.PropTypes` somewhere. They have moved to a separate package.

https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes
