### ISSUE TITLE
React 15.6.2 tag

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11559]
It looks like the React 15.6.2 tag never got pushed to Github. Should we just cut a new tag? The biggest annoyance for me is that the release is missing in the dropdown for our DOM test fixtures:

<img width="318" alt="screen shot 2017-11-14 at 7 50 10 pm" src="https://user-images.githubusercontent.com/590904/32812843-1ca7307a-c975-11e7-921a-824180977a3a.png">

I can just append to the URL. No huge deal, but it seems low effort. I can take care of it if no-one minds.

**Comment by gaearon** [comment]
Feel free to push a tag :-)

**Comment by nhunzaker** [comment]
Done: https://github.com/facebook/react/releases/tag/v15.6.2 :-)
