### ISSUE TITLE
Is there something like emberobserver.com?

### ISSUE THREAD

**Issue by johnunclesam** [facebook/react#11554]
Is there something like https://www.emberobserver.com for React world?

**Comment by bonusrk** [comment]
Maybe this one can help:
https://github.com/facebook/react/wiki/Complementary-Tools

**Comment by ivancsicsmarkus** [comment]
maybe:

https://github.com/search?o=desc&q=react&s=stars&type=Repositories&utf8=%E2%9C%93

**Comment by sw-yx** [comment]
meh, both of the above are tangential. try https://js.coach/react . also @ahfarmer has created this <https://www.javascriptstuff.com/> but its early stage

**Comment by ahfarmer** [comment]
Yep I built javascriptstuff.com a couple weeks ago. A few people said it is useful but still need a lot of feedback. There are 4 React-specific lists: components, example apps, starter projects, and tutorials. Those are the things I see people looking for the most. 

@johnunclesam does that help at all? What have you been looking for?

**Comment by johnunclesam** [comment]
@ahfarmer yes. But for example I can't find something like "redux-orm". Why?

**Comment by ahfarmer** [comment]
@johnunclesam my site isn't exhaustive. I just made a few lists that I think are the most important.

I do plan on making a 'flux' list though, and I'll add redux-orm to it. Were you searching for flux tools? I'm assuming you weren't actually searching for "redux-orm" because if you already knew about redux-orm, you wouldn't need to search for it.

**Comment by ahfarmer** [comment]
I went ahead and made a 'state managers'/flux list. 
https://www.javascriptstuff.com/state-managers/

While making that list, I realized there are a ton of redux-specific utilities. redux-saga, redux-thunk and reselect to name a few. Maybe next weekend I'll make a redux list.

**Comment by gaearon** [comment]
I’ll close this. I think in general we’d be happy to take PRs to our docs FAQ section for different tools.
