### ISSUE TITLE
HTML entities with renderToNodeStream and renderToStaticNodeStream causing mismatch with hydrate.

### ISSUE THREAD

**Issue by Mikeysax** [facebook/react#11567]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When the server is started with an HTML entity anywhere within a component's JSX, it causes a mismatch to occur when using hydrate.

```
warning.js:33 Warning: Text content did not match. Server: "Â©" Client: "©"
```

**What is the expected behavior?**

I don't expect there to be a mismatch. This only occurs with renderToNodeStream and renderToStaticNodeStream and doesn't occur when using renderToString or renderToStaticMarkup.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.1.1
Chrome 62+
Manjaro Linux

Not sure if this worked in previous versions.

**Comment by gaearon** [comment]
Mind creating a small project demonstrating it?

**Comment by Mikeysax** [comment]
@gaearon  Created a new SSR React app: https://github.com/Mikeysax/testNodeStream

Seems like any HTML entities cause a match error.

**Comment by iamdustan** [comment]
The issue is an encoding issue. You need either of the following:

* in `head`: `<meta charSet="utf8" />`
* http header: `Content-Type: text/html; charset=utf-8`

<img width="1054" alt="screen shot 2017-11-16 at 9 36 57 am" src="https://user-images.githubusercontent.com/227879/32896699-bc2a4a64-cab1-11e7-9cf1-9cbc8ca3bc59.png">

**Comment by Mikeysax** [comment]
@iamdustan That works; I think I accidentally deleted it at some point.

Firefox displays the error in the screenshot and Chrome doesn't even come close.

**Comment by gaearon** [comment]
Is there any way we could detect it and show a better warning ourselves?

**Comment by Mikeysax** [comment]
@gaearon I'm not sure because I'm not super intimate with the library. 

I guess React could detect document encoding on the initial mount and throw an error or log a message if it's not specified in the initial document?

Maybe React could possibly add it to the document as a default if it isn't specified?
