### ISSUE TITLE
React 16.1.1 does not recognize the `allowTransparency` prop on a DOM element.

### ISSUE THREAD

**Issue by adaniliuk** [facebook/react#11568]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

React 16.1.1 does not recognize the `allowTransparency` prop on a DOM element. Though React 16.0.0 recognizes it.

Open the below links and check the sandbox console. React 16.1.1 version has the warning displayed.

https://codesandbox.io/s/j45jr5mjmy - React 16.1.1 version with the above warning displayed in the sandbox console.

https://codesandbox.io/s/2zvy29xx8r - React 16.0.0 version without warning message.

**What is the expected behavior?**

`allowTransparency` is recognized as a valid DOM element attribute as it's mentioned in the documentation https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested and reproducible in the latest versions of Chrome, Safari and Firefox on MacOS X 10.13.1.

It worked well with React 16.0.0.

**Comment by adaniliuk** [comment]
It seems like it was removed intentionally? https://github.com/facebook/react/commit/4472442708e2648a8f3352a9f1daaa9031002a83

**Comment by gaearon** [comment]
Yes, please see its commit message for details.
