### ISSUE TITLE
Clicking radios fires a change event unconditionally in older browsers

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11560]
This may be a change we agreed to that I missed, but the "Radio input clicks" test fixtures fails in:

Safari 7.1, 8, 9
iOS Safari 8.4
Chrome 42

The test fixture is here:
http://react-dom-test-fixtures.surge.sh/input-change-events

Do we care about this? If not, we should figure out a way to document this.

**Comment by nhunzaker** [comment]
cc @jquense @aweary, but no rush :)

**Comment by aweary** [comment]
Are those browser versions supported? cc @sophiebits. If so, we should probably fix it but otherwise, we can ignore it 😄

**Comment by gaearon** [comment]
Over-firing is ok
