### ISSUE TITLE
Preparing 15.6.3

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11573]
This is just a running list. It is not comprehensive, but a few things have come through that I don't want to lose track of:

- [ ] Cherrypick https://github.com/facebook/react/pull/11028 to `15-dev` (@jquense)
- [ ] `fbjs` License update (https://github.com/facebook/react/issues/11233)
- [ ] Changelog
- [ ] Tag
- [ ] Release
- [ ] Release blog post
- [ ] Test the living _heck_ out of it.

**Comment by jquense** [comment]
we don't seem to have a 15-dev 😳

**Comment by nhunzaker** [comment]
Huh, for the 15.6.2 release, I worked from 15.6-dev (https://github.com/facebook/react/pull/10430). I think we should cut a new 15.6-dev to work from. Once it's ready we can merge it into stable.

**Comment by jquense** [comment]
i can do that

**Comment by acroyear** [comment]
#11233 was the issue that was re-opened.

**Comment by jonathanchrisp** [comment]
Hey @aweary, Apologies I appreciate that you only self assigned this a day ago but do you have any timeframe as to when 15.6.3 could be released?

**Comment by blling** [comment]
Is 15.6.2 still support IE8?

**Comment by gaearon** [comment]
No.

**Comment by blling** [comment]
Is there any ways to make 15.6.2 support ie8:)

**Comment by gaearon** [comment]
We dropped IE8 support [two years ago](https://reactjs.org/blog/2016/01/12/discontinuing-ie8-support.html). You can fork 15.x and try to get it to a state that works with IE8 (it may not need many changes) but we won't be supporting that officially.

**Comment by aweary** [comment]
I don't think we'll be doing this release anymore

**Comment by gaearon** [comment]
I feel old

**Comment by nhunzaker** [comment]
How was this a year ago.
