### ISSUE TITLE
Controlled inputs don't work in Safari

### ISSUE THREAD

**Issue by brandonaaskov** [facebook/react#11577]
I originally thought this issue was just around using `<input type='number' />` but upon digging further it appeared that Safari just plain doesn't like controlled inputs: whatever you type, will appear in that input.

You can see this in action here: http://jsbin.com/voyigef/edit?html,js,output

Now, I will say that we worked around this for the time being by leveraging `onKeyPress` instead of `onChange`, which allowed us to stop the event propagation.

We're all on Safari 11.0.1 so I'm not sure if this only affects Safari 11. From looking at older issues, it looks like this is a solved problem for Safari 10.x but I don't have it so I can't confirm that or not.

**Comment by timjacobi** [comment]
I can reproduce this here http://jsbin.com/qiwapogive/1/edit?js,console,output
Safari version 11.0.1

**Comment by jquense** [comment]
see https://github.com/facebook/react/issues/11142#issuecomment-334899692

**Comment by brandonaaskov** [comment]
@jquense this is _not_ the same as that issue. This doesn't just affect number inputs, but _all_ inputs in Safari. I've simplified [the jsbin example](http://jsbin.com/voyigef/edit?js,output) to illustrate this. Please re-open this issue if you agree.

**Comment by jquense** [comment]
that bin is still using number inputs?

**Comment by jquense** [comment]
Sorry I am having trouble getting any of the fiddle sites to run under Safari but what is your expected behavior for none-number controlled inputs? The behavior seen for the number ones is, at least, covered by #11142

**Comment by brandonaaskov** [comment]
@jquense jsbin's caching is a little aggressive, but here's the snapshot to the exact changes: http://jsbin.com/voyigef/6/edit?js,output

(At the moment, I'm getting intermittent 504s from JSBin; ymmv)

**Comment by jquense** [comment]
I'm still seeing a bin a number input. Can you post the code here and the behavior you are seeing vs what you expect

**Comment by brandonaaskov** [comment]
@jquense I stand corrected - what I thought I was seeing in jsbin wasn't accurate or what I expected, again probably due to some strange caching. This is _definitely_ covered by #11142. My apologies for the red herring confusion!
