### ISSUE TITLE
Move MouseWheel event type detection to BrowserEventConstants

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11585]
I think we can move the [`wheel` event support check in BrowserEventEmitter](https://github.com/facebook/react/blob/master/packages/react-dom/src/events/ReactBrowserEventEmitter.js#L126-L135) into [BrowserEventConstants](https://github.com/facebook/react/blob/master/packages/react-dom/src/events/BrowserEventConstants.js)

That runs the check once, which is nice for wheel and scroll events, which eventually need to be attached locally.

Filing this for myself as a part of https://github.com/facebook/react/pull/11550. But this could happen on master right now.

More or less, I'm interested in cutting the overhead of event listening as much as possible, and this is really low hanging 🥝.

**Comment by nhunzaker** [comment]
Marked this as a good first issue. The event system can be a beast. I'd be happy to walk through it with an interested contributor.

**Comment by cristidrg** [comment]
Hello @nhunzaker I'd like to work on this issue.

Any other files you suggest looking at other than the two that you have linked?

**Comment by nhunzaker** [comment]
Totally! If you were curious:

The main consumer of `ReactBrowserEventEmitter` is [`ReactDOMFiberComponent`](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberComponent.js). It asks ReactBrowserEventEmitter to listen to events.

Most events are delegated to the document for the related DOM element. So ReactDOMFiberComponent uses [an internal function that finds that document before requesting an event to be subscribed](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberComponent.js#L191-L199).

[`ReactBrowserEventEmitter` then figures out what events need to be attached for a particular event type](https://github.com/facebook/react/blob/master/packages/react-dom/src/events/ReactBrowserEventEmitter.js#L121-L124). This is how React polyfils things like `mouseenter` and `mouseleave`, and sets up a bunch of normalization around change events for inputs. 

From there, the Emitter enumerates through all of the event types that need to be attached and says "Have I already attached this? If not: start listening!". 

---

That gets to the change I'm suggesting. This function is doing some aliasing of event names for different browsers that I think shouldn't happen at this phase. We can normalize `wheel` ahead of time by assigning the correct wheel event type in `BrowserEventConstants`. We might also [be able to remove a few others](https://github.com/facebook/react/blob/master/packages/react-dom/src/events/ReactBrowserEventEmitter.js#L136-L155), but that might not be true. Let's take it one step at a time :).

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/11594

**Comment by nhunzaker** [comment]
Fixed by #11594. Thanks @cristidrg!
