### ISSUE TITLE
Part of huawei's mobile phone has a flashback in the render page, but other android phones and ios phones have no problem. How do you solve this problem?

### ISSUE THREAD

**Issue by KingPengZero** [facebook/react#11584]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Part of huawei's mobile phone has a flashback in the render page, but other android phones and ios phones have no problem. How do you solve this problem?

**Comment by gaearon** [comment]
We don't know. It's not clear why you consider this a bug in React. If this is a general question please ask it on StackOverflow. If you're sure it's specific to React please provide a minimal reproducing case and instructions and we can take a look.
