### ISSUE TITLE
IE 11 console error stopping the render. `Unable to set property `nextEffect` of undefined or null reference`

### ISSUE THREAD

**Issue by dzek69** [facebook/react#11583]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Page can't be rehydrated (but it's probably not a rehydration issue, the same happens when I use `render` on empty div instead). Console error:
```
Unable to set property `nextEffect` of undefined or null reference
```
(`childToDelete` seems to be equal `undefined` when I set breakpoint)
Point in source: https://github.com/facebook/react/blob/4a924a206783df5d2e06755caa0fbd2dd580b14e/packages/react-reconciler/src/ReactChildFiber.js#L243

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
I can't isolate this bug to provide minimal demo or reliable reproduction steps without providing you the whole app. Spent a day already on this. Still trying to isolate the issue.

When I removed most (randomly choosen) components and added `<div>hi</div>` to render of some deep component - it was fine, but when I defined `Div = () => <div>hi</div>` and rendered it instead with `<Div />` then I got the error. Restoring various components makes React crash on randomly looking points. Every refresh produces the same result though.

I still report it in hope some dev got an idea what could be triggering it. I'll keep looking meanwhile.

**What is the expected behavior?**
No errors, page should be rendered.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.0.0 & 16.1.1. Windows 7, IE 11.
React 15 was working just fine.

The same is happening with development and production build.

**Comment by gaearon** [comment]
Please provide a reproducing project.

**Comment by gaearon** [comment]
Which Map/Set polyfill are you using? We've seen this problem with a bad polyfill before. https://github.com/facebook/react/issues/10656#issuecomment-328514056

**Comment by dzek69** [comment]
Polyfill.io

I can't pass you the whole project. If I will be able to isolate the issue in minimal code then I will surely provide it. Still working on it.

**Comment by dzek69** [comment]
I'll try with another polyfill and give you a feedback

**Comment by gaearon** [comment]
3.22 of polyfill.io is expected to have fixed this.
https://github.com/Financial-Times/polyfill-service/issues/1299

So I don't think there's anything wrong with React although I don't know why the fix didn't help for you. Maybe you're getting an old version somehow?

**Comment by dzek69** [comment]
Yeah, updating polyfill service did the job.

So you're right, that's not React bug.

Thank you for your help, I wasn't able to find the linked issue via search bar or Google. I hope having error in the issue title will be enough for others to find it if needed.
