### ISSUE TITLE
Inline-playing <video> element in iOS 11 does not fire click events when rendered with React

### ISSUE THREAD

**Issue by jamiekowalski** [facebook/react#11589]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**

If a `<video>` rendered by React is autoplaying inline in iOS 11, it does not fire click events when tapped, even if click handlers are added using native DOM `addEventListener`.

If the same example is created without React, the `<video>` does fire click events when it is autoplaying inline.

**If the current behavior is a bug, please provide the steps to reproduce**

Demo: https://jsfiddle.net/6qk071s9/show
Code: https://jsfiddle.net/6qk071s9

**What is the expected behavior?**

Click events should be fired.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Issue appears in React 15.6.2 and 16.1.1 on iOS 11.1; no issue is seen on iOS 10.3 with either version of React

**Comment by dblate** [comment]
I’m afraid I have a different opinion in 

> If the same example is created without React, the video does fire click events when it is autoplaying inline

I have a [case](https://codepen.io/dblate/pen/ZvpXqR) shows that in iphone ios11, even if you create a video in navtive HTML, and bind events by addEventListener, the "click" event will not fire. If you tap the video,  the detail is:

- In ios11, a series of touch event will be fired

- In ios11, a click event will not be fired, except that you tap a long time(may be 3s)

- In ios10, both touch an click will be fired quickly

I'm troubled in the problem above.
I would be appreciated if the issue can solve my problem by the way :)

**Comment by gaearon** [comment]
Seems like it might be a browser issue then?

I'm closing but if someone can reproduce this consistently *and* have verified it doesn't happen with raw DOM API, please file a new issue including both code snippets you've tried.
