### ISSUE TITLE
Elements with the same key are not deduplicated

### ISSUE THREAD

**Issue by vsiao** [facebook/react#11582]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Elements with the same key are not deduplicated, which in itself is not unreasonable, I guess, since having duplicate keys is undefined behavior. However, on subsequent rerenders the duplicate elements remain in the render tree with no way to remove them.

**If the current behavior is a bug, please provide the steps to reproduce**
https://codepen.io/asana/pen/ZaaKzQ (follow the instructions)

**What is the expected behavior?**
Elements with the same key are deduplicated (this was the behavior in React 15: https://codepen.io/asana/pen/RjjVbJ). Or, at the very least, duplicate elements are appropriately cleaned up in subsequent rerenders.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Mac Chrome, React 16+. Working in 15.

**Comment by gaearon** [comment]
This is intentional. As you said, the behavior is pretty much undefined in this case. Always key elements. (React warns you if you don't.)

**Comment by gaearon** [comment]
(We did this for performance reasons. It makes the "correct" case slower to always check for duplicates and track them.)
