### ISSUE TITLE
Add warning when hydrating output from renderToStaticMarkup

### ISSUE THREAD

**Issue by jorrit** [facebook/react#11596]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I accidently generated my SSR output using `renderToStaticMarkup` instead of `renderToString`, which I then hydrated using `hydrate`. This  led to a warning, caused by collapsed text nodes. `renderToString` would have added HTML comments between them.

The warning I got was: 
Warning: Text content did not match. Server: "a (b)" Client: "a"

When rendering:
```jsx
    const a = 'a';
    const b = 'b';
    const component = <select><option>{a} ({b})</option></select>;
```

It would be nice if `hydrate`  could detect that it is executed on output from `renderToStaticMarkup` instead of `renderToString`. It seems to me a simple check on the `data-reactroot` attribute on the root element would suffice.

**What is the expected behavior?**

I would like some kind of warning along the following lines:

`Warning: You are hydrating output that was not created by ReactDOMServer.renderToString(). Perhaps you are using ReactDOMServer.renderToStaticMarkup() or modifying the output after rendering. Please see ... for more information.`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.1.1.

Due to the changes in 16, this worked before.

**Comment by cramaechi** [comment]
Hi Everyone,

I am a new contributor to React. I would be more than happy to handle this issue!

I have already submitted the CLA.

**Comment by cramaechi** [comment]
I have opened a pull request.
