### ISSUE TITLE
[Question] Automatize tests on Windows environment && Circle CI 2.0

### ISSUE THREAD

**Issue by raphamorim** [facebook/react#11595]
Hi everyone,

I was wondering if it makes sense, implement the React Tests for windows environment. Even if it's to test only the build task (https://github.com/facebook/react/issues/9540, https://github.com/facebook/react/issues/9500) or only run for master branch. I was thinking of using the [appveyor](https://ci.appveyor.com/).

My other question is about migrate to Circle CI 2.0 configuration. **If any of this questions make sense**, I'll be available to implement it.

**Comment by felicianotech** [comment]
Hey, I'm a Developer Evangelist from CircleCI.

I took a look at the current 1.0 config and it doesn't look too complicated. Shouldn't be too difficult to switch over to CircleCI 2.0 but ping me if any help is needed.

Unless you create a completely custom Docker image, a good start might be our [Docker Ruby Images](https://hub.docker.com/r/circleci/ruby/) which have a variant that include NodeJS. The closest to what you're using now would be the `circleci/ruby:2.2-node` image which runs Ruby v2.2.8.

**Comment by gaearon** [comment]
I'd be up for using AppVeyor but in my experience it can be pretty slow. Maybe it's fine if we only run it on master. (And if something fails, we'd know and investigate it post factum)

**Comment by raphamorim** [comment]
> The closest to what you're using now would be the circleci/ruby:2.2-node image which runs Ruby v2.2.8.

Thanks for the hint.

> Maybe it's fine if we only run it on master

Sure.

Ok, leave it me. I'll send a PR.

**Comment by gaearon** [comment]
This is done now. Thanks for your help!
