### ISSUE TITLE
Warn if this.state is set to this.props referentially

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11593]
See this example: https://github.com/facebook/react/issues/11508#issuecomment-345464797.

I think it probably reflects a misunderstanding of how props and state work, and we should detect and warn if we see this.

**Comment by sw-yx** [comment]
Happy to take!

**Comment by gaearon** [comment]
Sounds good.

**Comment by veekas** [comment]
I'm a new contributor, but working with @sw-yx on this.

I'm currently trying to figure out how to catch if the user is trying to set `this.state = props`. Do you have any tips?

I currently am looking at putting the warning in `ReactFiberClassComponent.js`. Something like the following:

```js
// the following is in the checkClassInstance function
      const noSetStatesFromProps = !(instance.state === parent.props); // this logic is wrong, but what is correct?
      warning(
        noSetStatesFromProps,
        'this.state should not be set to this.props referentially. When ' +
          'implementing the constructor for a React.Component subclass, you ' +
          'should call super(props) before any other statement. To initialize ' +
          'state locally, just assign an object to this.state in the constructor.'
      );
```

[Here are the changes I've made so far](https://github.com/veekas/react/commit/1952d3b99d82854cbc8ea8e26ca70527f4f90702), for reference.

Thanks for your help!

**Comment by sw-yx** [comment]
in discussing with veekas, i wasn't sure how to do this one either. there are two questions here. 

1. how to test if `this.state` is being set to `React.Component.props`
2. -where- to test it

my best guess is to stick the test inside of the `componentWillMount` lifecycle method execution as that is the earliest place we can check `this.state`.

**Comment by gaearon** [comment]
Can't you check `instance.state === instance.props`? I don't understand what `parent` is or how it is relevant.

>my best guess is to stick the test inside of the componentWillMount lifecycle method execution as that is the earliest place we can check this.state

Not sure what you mean. The original direction by @veekas makes sense to me. Test it in *React itself* (not some component's methods) right after the instance is created. In fact you can find where React calls the constructor in this file, and check right after it.

**Comment by sw-yx** [comment]
He's almost done with it afaik. look at his PR

**Comment by diegoborda** [comment]
Hi! I see this issue is taken but it seems still. @veekas Are you taking it? I can finish it if you want.

**Comment by veekas** [comment]
Oh wow, completely forgot about this. Thanks for the ping @diegoborda. I'll have it done asap.

**Comment by benbakhar** [comment]
Hey guys, is this still in progress? would be happy to take it.

**Comment by veekas** [comment]
@benbakhar If you'd like, please take a look at #11658 and review it if you see room for improvement! Same goes for @diegoborda, @isaacchien, et al. If any further changes *are* requested by @gaearon or other contributors, I'd love to pass this baton to one of you.

**Comment by gaearon** [comment]
Sorry we dropped this. The past months have been pretty intense. :-)

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11658
