### ISSUE TITLE
how to change props in the child component?

### ISSUE THREAD

**Issue by InvincibleJun** [facebook/react#11608]
For example, I want to change the prop that my parent component passes by clicking the button. But do not want to be controlled by the incident explicitly. Because I want to make this component more independent, callers do not need too many parameters to achieve two-way communication between parent and child components.

// parent
```
import  Pagination  from './Pagination';
...
...
render(<Pagination defaultCurrent={1} total={50} />, mountNode);
```
// child 
```
render(
<div>
  <span>{this.props.defaultCurrent}</span>
 <button></button>
</div>)
```

How to do?  Good people.

**Comment by gaearon** [comment]
We use the issue tracker for bugs and feature requests. Please refer to the appropriate support resources for asking questions: https://reactjs.org/community/support.html

Thanks!
