### ISSUE TITLE
can't access discuss react

### ISSUE THREAD

**Issue by ghost** [facebook/react#11601]
I know this is not related to react directly but didn't know where to turn to.
Am I the only one who can't access/login to discuss.reactjs.org? (for quite some time already)
I get error:
_This page isn’t working. discuss.reactjs.org is currently unable to handle this request. HTTP ERROR 500_
and sometimes when I retry this error:
_Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?_

**Comment by gaearon** [comment]
Seems to be working for me. Are you behind a proxy?

**Comment by giorgim** [comment]
@gaearon no I don't think so, no.
First problem occurs as soon as I click log in button. I get the first error I described in my initial question :confused: (If I recall correctly I had similar issue from a different pc too, but I'd have to double check that.).

**Comment by gaearon** [comment]
Can you provide *exact* instructions to reproduce with screenshots?

**Comment by giorgim** [comment]
@gaearon 

Well this is step 1, when I enter site:
[scrn](https://imgur.com/kNx6727)

This is step 2, when I click "Login" button:
[scrn](https://imgur.com/hMTN8If)

Step 3: Now if in the dialog which was generated in step 2, I click the "RELOAD" button, I get this:
[scrn](https://imgur.com/SLQLgqY)

**Comment by AyWa** [comment]
I am not sure it helps, but can you go to https://github.com/settings/applications then revoke `discuss.reactjs.org` and try again to login ?

**Comment by giorgim** [comment]
@AyWa no it didn't help

**Comment by ark9606** [comment]
### issue

**Comment by gaearon** [comment]
Please re-file this in https://github.com/reactjs/reactjs.org if it's still a problem. Thanks.
