### ISSUE TITLE
Include component stack in invariants

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11619]
IIRC we didn't include it because it was DEV-only. But it's not anymore.
Maybe let's start including it?

Errors are often more prominent than warnings, and it would be great to have this info in both.

**Comment by Ethan-Arrowood** [comment]
I handled a similar issue https://github.com/facebook/react/pull/11208 before. Could I try this one? I'll try to find what these 'invariants' are.

**Comment by Ethan-Arrowood** [comment]
<img width="488" alt="screen shot 2017-11-24 at 1 52 34 pm" src="https://user-images.githubusercontent.com/16144158/33221598-c11daac0-d11e-11e7-8260-40c17c016f14.png">
Sections of code like this?

**Comment by Ethan-Arrowood** [comment]
https://github.com/facebook/react/blob/7d27851bf4aa8129276614b62edf9ade4aaa4cbd/packages/react-dom/src/client/ReactDOM.js#L657-L710

Using the code from my previous issue:
```javascript
var {getCurrentFiberStackAddendum} = require('ReactDebugCurrentFiber');
invariant(
    isValidContainer(container),
    'Target container is not a DOM element.%s',
    getCurrentFiberStackAddendum() || ''
);
```

Would I also want to add the `getCurrentFiberStackAddendum() || ''` to the warnings on lines 691 & 699?

**Comment by gaearon** [comment]
This is top level rendering so component stack wouldn't be useful there (you're not *inside* a component). I was thinking about these:

https://github.com/facebook/react/blob/7d27851bf4aa8129276614b62edf9ade4aaa4cbd/packages/react-reconciler/src/ReactChildFiber.js#L162-L164

https://github.com/facebook/react/blob/7d27851bf4aa8129276614b62edf9ade4aaa4cbd/packages/react-reconciler/src/ReactFiber.js#L342-L346

**Comment by Ethan-Arrowood** [comment]
Okay sweet. I'm down to implement the component stack in each of these. What other files should I implement this change in? Is there an easy way to determine which are *inside a component*?

**Comment by gaearon** [comment]
>Is there an easy way to determine which are inside a component?

Look at what the message says. Look at examples of this invariant in tests. See if it's something that happens inside a component or not.

**Comment by Ethan-Arrowood** [comment]
Gotcha. I noticed some invariants already have the component stack on the \_\_DEV\_\_ addendum (Lines 157 and 168): 
https://github.com/facebook/react/blob/7d27851bf4aa8129276614b62edf9ade4aaa4cbd/packages/react-reconciler/src/ReactChildFiber.js#L153-L171

Should I remove it from the \_\_DEV\_\_ and put it directly on the invariant:
```javascript
invariant(
      false,
      'Objects are not valid as a React child (found: %s).%s.%s',
      Object.prototype.toString.call(newChild) === '[object Object]'
        ? 'object with keys {' + Object.keys(newChild).join(', ') + '}'
        : newChild,
      addendum,
      getCurrentFiberStackAddendum() || '',
 );
```

**Comment by gaearon** [comment]
>Should I remove it from the __DEV__ and put it directly on the invariant:

That sounds reasonable.

**Comment by Ethan-Arrowood** [comment]
@gaearon when you get a chance review my changes in the mentioned PR

**Comment by bl00mber** [comment]
Currently the `getCurrentFiberStackInDev()` is DEV-only :hushed:
Is the issue still relevant?

**Comment by sophiebits** [comment]
We already log the component stack to the console along with an error (see discussion on #18315). So I don't think there is any action required now. (@gaearon lmk if I'm missing something)

**Comment by gaearon** [comment]
Yeah that makes sense. I think our integrations like CRA error box don't currently surface that but it's something that can be addressed in them.
