### ISSUE TITLE
Unfork GCC

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11610]
We're currently using a fork of GCC because its [JS version](https://github.com/google/closure-compiler-js) is not updated yet to the GCC version that includes https://github.com/google/closure-compiler/pull/2707. See https://github.com/google/closure-compiler-js/pull/83#issuecomment-344099311.

When there is a new release of the JS version that includes that PR, we should remove [this fork](https://github.com/facebook/react/blob/7e692fb496e764844680c681a38e42f99e1f218d/yarn.lock#L2169).

**Comment by gaearon** [comment]
Next blocker: https://github.com/google/closure-compiler/issues/2448#issuecomment-350772850

**Comment by aweary** [comment]
No longer forked #12618 #12800
