### ISSUE TITLE
Request in IE9

### ISSUE THREAD

**Issue by corohsnk** [facebook/react#11613]
Hello guys, how can I make request in IE9?, actually I make request with axios, but in IE 9 dont work =/, response returns with Network Error and using Fetch response returns with Access Denied.

React 16.0

With Axios 

```
async function makeRequest(endpoint, method = 'get', params = null, headers = {}) {
  const request = axios({
    method,
    url: BASE_URL + endpoint,
    data: params,
    headers
  });

  return await request;
}
```

with Fetch

```
fetch(BASE_URL + endpoint, {
        method: 'POST',
        headers: headers,
        body: JSON.stringify(creds)
      }).then(data => {
        console.log(data);
      }, error => {
        console.log(error);
      })
```

**Comment by jquense** [comment]
Hey there, your question doesn't seem related to React, but to making requests in JS generally. I'd try some of the general support avenues some of which are documented here: https://reactjs.org/community/support.html We like to keep the issue tracker for feature and bug reports in React. Thanks!
