### ISSUE TITLE
Question: What is your workflow to release a new version

### ISSUE THREAD

**Issue by LukasBombach** [facebook/react#11628]
Hello,

if I am totally out of place asking this here I am sorry, please close this issue. I work at a German newspaper and we are publishing some smaller npm packages publically as open source and some for our own purposes privately.

Currently, we are not quite sure of our workflow and we want to learn from the best (YOU 🎉 ). We are wondering how you manage to publish new releases of React. I see you have [some release sh scripts](https://github.com/facebook/react/tree/master/scripts/release). We have an npm script that basically builds our package, bumps the version and publishes the lib to npm. So far this seems quite similar, correct me if I am wrong. Also, when we want to publish a new release, someone just runs that npm script from their laptop. This seems somewhat unsettling, it feels like there should be more this.

So I am wondering, if you care to answer, how do you do it at Facebook?

**Comment by gaearon** [comment]
That’s pretty much what we do. :-) You can view the source for both [build](https://github.com/facebook/react/blob/master/scripts/release/build.js) and [publish](https://github.com/facebook/react/blob/master/scripts/release/publish.js) scripts.

**Comment by LukasBombach** [comment]
Thanks man!
