### ISSUE TITLE
Flowtype and class inherit

### ISSUE THREAD

**Issue by rlesniak** [facebook/react#11643]
I have a problem with react 16 and its Flowtype typings.

Lets assume that I have

```javascript
// Foo.js
type PropsType = { cool: boolean };
class Foo extends React.Component<PropsType> {}

// Bar.js
import Foo from './Foo';

type PropsBar = { temp: string };
class Bar extends Foo {
  test() {
     this.props.cool; // there is no error
     this.props.temp;
                ^^^^ Property not found in object type  
  }
}
```

My question is, how to pass additional Props to Bar component?

**Comment by gaearon** [comment]
Please report this to http://github.com/facebook/flow.
We’re not maintaining those bindings ourselves.

That said we’re *not* recommending to use inheritance with React components.
https://reactjs.org/docs/composition-vs-inheritance.html
