### ISSUE TITLE
React roadmap document?

### ISSUE THREAD

**Issue by International** [facebook/react#11645]
**Do you want to request a *feature* or report a *bug*?**
A feature

**What is the current behavior?**
I think many people would be interested in a document that would show the future/long term plans for React, and features that are planned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar**
It's not a bug.

**What is the expected behavior?**
Document or link exists in repo, and can be accessed to see what is planned for the future.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
N/A

**Comment by gaearon** [comment]
The truth is we don’t really have a long-term roadmap.

Watching and participating in https://github.com/reactjs/rfcs is probably the best way to stay informed on changes we’re making in the next months.

**Comment by gaearon** [comment]
https://reactjs.org/blog/2018/11/27/react-16-roadmap.html

**Comment by tobiasbueschel** [comment]
Hi @International & @gaearon,

Just to follow up with this discussion, I wonder whether we'd like to consider **GitHub's Projects** feature for any roadmap and release planning? [Create React App](https://github.com/facebook/create-react-app/projects/9) also started using it recently. 

**Advantages**
I think this could help to improve transparency and collaboration within the React community. For example, non-core members could easily identify pending issues for upcoming releases, and could offer more targeted support. Thereby, potentially shortening our release cycles.

**Disadvantages**
This of course only works if the project board is well maintained, which would have to be done by a core member.

**Examples**
- https://github.com/facebook/create-react-app/projects/9
- https://github.com/electron/electron/projects
- https://github.com/twbs/bootstrap/projects/28

---

We could also use GitHub Projects for general (1) issue triaging or (2) pull request management, which a few other projects are already doing:
- https://github.com/microsoft/TypeScript/projects/13
- https://github.com/tensorflow/tensorflow/projects/1

In addition to the default automation that GitHub already provides, one could perhaps even create custom card automation using GitHub's Projects API: https://developer.github.com/v3/projects/cards/#move-a-project-card

--- 

Keen to hear what you both think ☺️ 

Cheers
