### ISSUE TITLE
`yarn linc` should also lint untracked files

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11646]
Too often I would run `yarn linc`, it would say lint passed for changed files, and then I'd realize I have not *added* a file yet so it doesn't see the file.

We should make `yarn linc` include untracked files. Note that if a file is *ignored* in git that's a different matter. But if it *shows up as untracked* it's extremely likely I want to lint it.

**Comment by accordeiro** [comment]
Hi! Can I help with this one? :)

**Comment by gaearon** [comment]
Sure!

**Comment by accordeiro** [comment]
Cool – I'll work on this and send a PR until this weekend.

**Comment by accordeiro** [comment]
Just sent a PR – please let me know if this is what you were looking for :)

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11665.
