### ISSUE TITLE
When I was in the onClick`s callback, simulating clicking on other elements triggers an additional callback

### ISSUE THREAD

**Issue by Kunoky** [facebook/react#11649]
Here's the link ：https://codepen.io/afc163/pen/JOvzZy?editors=0011
`
class NormalLoginForm extends React.Component {
  handleSubmit = (e) => {
    e.preventDefault();
    console.log('click button');
    //模拟点击
     document.getElementById('div').click();
  }
  render() {
    return (
      <div>
        < button onClick={this.handleSubmit} >
          Log in
        </ button >
        <div id='div' onClick={()=>console.log('click div')}>1111</div>
      </div>
    );
  }
}

ReactDOM.render(<NormalLoginForm />, mountNode);`

**Comment by jvitoroc** [comment]
Line 6, you are calling
`document.getElementById('div').click();`

**Comment by gaearon** [comment]
One click is caused by the actual click.
The other click is caused by your `click()` call.

**Comment by Kunoky** [comment]
我通过 ‘click()’ 点击的是‘div’，而不是button；
可却触发了button的回调
I click 'div' through 'click ()', not button;
But it triggers the callback of button

**Comment by love-fay** [comment]
@Kunoky I find you are Chinese and I talk about it with you in Chinese.
你没有理解虚拟dom的意思，react内部事件仅仅对最外层的容器进行了绑定，并不是绑定到你这个button上，所以e.preventDefault();也就没有用了，尽量避免虚拟事件和真实事件混用。
