### ISSUE TITLE
Deprecate TestUtils.SimulateNative

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11656]
I'm not sure if it was ever intended to be a part of public API.

It's not documented, and its naming is misleading because it actually doesn't simulate a native event (oops!). It only simulates what React would do if it *received* that native event. It does that in a way that's very tightly coupled to the event system internals which is unfortunate. It is much better if we can educate people how to dispatch actual browser events in tests instead.

I think we should just deprecate it. We've removed most tests relying on it, and can leave a test or two until it can be deleted in the next major.

**Comment by gaearon** [comment]
cc @ljharb not sure if you folks use it?

**Comment by ljharb** [comment]
I don't see any usage of it in all of our enzyme code; *however*, we haven't yet written an `enzyme-adapter-react-native`, so we might need it there for the `.simulate()` method.

However, I've grown to think the "simulate" event API in enzyme is actually a huge footgun and discourage its use anyways, so it's fine to deprecate by me :-)

**Comment by nhunzaker** [comment]
Agreed! Simulate Native generates a fake event (not even a DOM event) that has always been confusing to me working on event system internals. It would be great to get rid of it.
