### ISSUE TITLE
Move ReactFiberTreeReflection to react-reconciler/reflection

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11659]
We should:

* Move `ReactFiberTreeReflection` to be exported from `react-reconciler/reflection` entry point (similar to how `react-dom/test-utils` entry point is set up).
* Create a flat bundle for it (similar to how `react-dom/test-utils` is set up in `bundles.js`).
* Change code that imports `ReactFiberTreeReflection` directly to do it through `react-reconciler/reflection` instead.
* Make `react-reconciler` a dependency of `react-noop-renderer` in `package.json`. This should ensure the reconciler doesn't actually get bundled with `react-noop-renderer`, and instead stays a `require()` call. Then the interaction of these two packages will actually be tested when you run `yarn test-build` (after `yarn build core,noop,reconciler --type=NODE`).

This task is not friendly to beginners. It requires an understanding of the relationship between different packages, and a willingness to research and experiment with how our build process is set up.

**Comment by rivenhk** [comment]
can i work on this one? I may need some time to study it first~

**Comment by gaearon** [comment]
Sure, but please don't disappear and keep us updated. :-)

**Comment by rivenhk** [comment]
no problem! will keep you posted!

**Comment by HardikModha** [comment]
Add me in a queue. :)

**Comment by rivenhk** [comment]
@gaearon I think i am on the right track. Currently, the build process is using rollup to bundle the imports into a single js file. Instead of bundling together, we want it to be a dependency and load it using require after the bundling process.

I notice that ReactFiberTreeReflection is also used in packages like react-dom, react-native-renderer, etc, does that mean i need to add the dependency in their package.json as well? I may also need to experiment with the "external" options in bundle.js to see if it can correctly bundle using require statements.

**Comment by gaearon** [comment]
>Instead of bundling together, we want it to be a dependency and load it using require after the bundling process.

Yes, but *only* for `react-noop-renderer`.

>I may also need to experiment with the "external" options in bundle.js to see if it can correctly bundle using require statements.

I think our build process should automatically treat something as an external for CommonJS builds if it's in `dependencies`. I think just adding `"react-reconciler": "*"` to `react-noop-renderer` might be enough. It's fine to use wildcard because this is a private package.

**Comment by rivenhk** [comment]
![image](https://user-images.githubusercontent.com/5195810/33279234-da9e5a96-d3d8-11e7-85c4-050499160369.png)

@gaearon, the ReactFiberInstrumentation cannot be found when trying to run yarn test-build because it does not exists as a flat bundle. Should i also convert this into another flat bundle?

**Comment by gaearon** [comment]
I forgot about that one. Let's just remove that import for now? It's only used by a debugging tool that I haven't updated for months anyway. We'll figure out how to fix it later.

**Comment by rivenhk** [comment]
@gaearon  same as ReactFiber, ReactFiberUpdateQueue in ReactNoop. Should i make a flat bundle for them to fix those direct imports?

**Comment by gaearon** [comment]
These are *type imports*, not real imports. They won't affect the tests or the build.

**Comment by rivenhk** [comment]
gotcha, those are for flows.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11683.
Thanks @rivenhk!
