### ISSUE TITLE
What I should do if another dependency use React.PropTypes

### ISSUE THREAD

**Issue by theGABS** [facebook/react#11661]
I use "react": "16.0.0-beta.5".

Some another package use React.PropTypes - I cannot update another package. What should I Do? 

I search some polyfill. I try to write my own, but it doesn't work.
```
import * as allReact from 'react';
import PropTypes from 'prop-types';

allReact.PropTypes = PropTypes
```

**Comment by gaearon** [comment]
As a temporary escape hatch you can create `patchReact.js` with

```js
const React = require('react');
const PropTypes = require('prop-types');

React.PropTypes = PropTypes;
```

and then put

```js
import './patchReact';
```

as the very first import in your app before **any** other imports. Then it will work.

But really, you should file an issue with the package that still uses `React.PropTypes` or fork it. There is an [automated conversion script](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types) you can use for that.

PS Don't use 16 betas :-) A stable version has been out for a few months now.

**Comment by theGABS** [comment]
I don`t sure. 
But looks like it doesn`t work.

I got:
undefined is not an object 
evaluating _react2.PropTypes.object

**Comment by gaearon** [comment]
This is not enough information to help you, sorry. We can't guess what went wrong without a full reproducing example.

Also, this is a bug tracker. Please refer to community resources for support: https://reactjs.org/community/support.html
