### ISSUE TITLE
eventPhase property of onClickCapture events has wrong value

### ISSUE THREAD

**Issue by timjacobi** [facebook/react#11663]
**Do you want to request a *feature* or report a *bug*?**
I assume this is a bug.
**What is the current behavior?**
When I register an `onClickCapture` event handler, click on the element and then inspect the event the `eventPhase` property is set to `3` which is equivalent to `Event.BUBBLING_PHASE`. 

I'm currently rewriting the `ReactTreeTraversal` tests to use the public API, that's how I found the problem.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[![Edit 6wrk742jp3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6wrk742jp3)
On codesandbox I would expect an alert `false` and then `true` but it is the other way round.

**What is the expected behavior?**
The `eventPhase` property should be set to `Event.CAPTURING_PHASE` / `1`.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I haven't tried this in versions different from 16.1.1, all testing was done in Chrome 62.

**Comment by aweary** [comment]
This is a known issue, see https://github.com/facebook/react/issues/9783. I've got an open PR that fixes this at #10722 that I just need to polish up.

**Comment by timjacobi** [comment]
Thanks and sorry for the dupe. I did some searching but didn’t find the old issue.
