### ISSUE TITLE
Constructor(props) and super(props) VS constructor() and super()

### ISSUE THREAD

**Issue by MrBra1nwash** [facebook/react#11671]
I know that this question was asked many times, but it is still doesn’t clear. Many people just said:

> Pass props to constructor if you want to access this.props there

[one more example of the answer](https://discuss.reactjs.org/t/should-we-include-the-props-parameter-to-class-constructors-when-declaring-components-using-es6-classes/2781/7)
Oficial doc says: 

> Class components should always call the base constructor with props

But if we do not pass props to `constructor`, we will still have `this.props` everywhere except `constructor`.
Also from [source code of Create Element](https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js) you can see that `createElement `adds `props `regardless if you use `super(props)`
**So the main question is**: Why React official doc says:

> Class components should always call the base constructor with props

if it is not really necessary? So current React doc is wrong or what? There is no need to call `constructor `always with `props `?

**Comment by gaearon** [comment]
>But if we do not pass props to constructor, we will still have this.props everywhere except constructor.

Yes, React sets `this.props` anyway after the constructor runs. Still, it is confusing to have `this.props` work in some places and not others. Especially if both constructor and other methods call some shared method that reads `this.props`. So, to avoid any potential confusion, we recommend always calling `super(props)`.

>Also from source code of Create Element you can see that createElement adds props regardless if you use super(props)

`createElement()` has no relation to this question. It creates an *element*, not an *instance*. You can read about the difference [here](https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html).

So, to get back to your question, technically it's only necessary if you plan to access `this.props` in the constructor or any method you call from constructor. However it's pretty confusing to have to remember this. You might know about it and not call `super(props)`, but the next person on your team will want to access `this.props` in a constructor and will be surprised it doesn't work. It's just easier to always specify it to avoid these problems.

**Comment by MrBra1nwash** [comment]
Thank you for your answer. Now it is clear

**Comment by datchelseafc** [comment]
### _****_
