### ISSUE TITLE
Disabled button click event propagates in IE11

### ISSUE THREAD

**Issue by Blasz** [facebook/react#11678]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Clicking a disabled button in IE11 fires a mouse event that bubbles and is caught by parent click event listeners.
The event is swallowed/not fired in all other major browsers.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
https://codesandbox.io/s/r0q76vqjwn

**What is the expected behavior?**
The event should not fire or bubble.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.6.2 - IE11

**Comment by jquense** [comment]
would you mind also comparing the behavior against a none react version> It's helpful to figure out if it's a browser idiosyncrasy or a bug in React

**Comment by Blasz** [comment]
@jquense It seems like this is a browser inconsistency with IE11 and not a bug in react: https://jsfiddle.net/fcbw43u6/4/

**Comment by aweary** [comment]
We could potentially get around this by checking if the target is disabled before letting the event dispatch continue in [`SimpleEventPlugin`](https://github.com/facebook/react/blob/master/packages/react-dom/src/events/SimpleEventPlugin.js#L202-L207).

**Comment by hdpinto** [comment]
This seems to have been a problem in the past ([#4457](https://github.com/facebook/react/issues/4457)), and was apparently fixed. I'm still experiencing this on radio inputs though, but with a double-click.

**Comment by Levirclark** [comment]
I'm also experiencing this when I double click disabled radio inputs.

**Comment by HuiguangChu** [comment]
I think you can check the element you click is the disabled or not. if it  is the current target  and set the event .stopPropagation(); to prevent bubble

**Comment by gaearon** [comment]
We are dropping support for IE in React 18, so this won't get a fix.
Sorry.
