### ISSUE TITLE
Click event is not propagating from elements created in a loop with Unique keys

### ISSUE THREAD

**Issue by shaikshavalis** [facebook/react#11679]
React Version: 15.3.2

`const items = ["success", "2h ago"];
        var outputElements = [];
        items.map((item, index) => {
            outputElements.push(<div key={this._getUniqueKey()}}> item </div>);
        })`

The above code generates react dom like the below
```
<div key="object-instance-id-c28c4dc9-77e3-4a07-95bc-3bf7685a1239">some text</div>
<div key="object-instance-id-e38c4ef8-71d4-2f18-26ae-4cf9485f6426">text2</div>
```

If we click on the above elements the event is not propagating . While debugging I found that the issue here is with keys. 

Is there any restrictions for keys in react like max length or specific characters ?

**Comment by gaearon** [comment]
Please provide a complete example. It's not clear how you diagnosed the problem is with React.

**Comment by gaearon** [comment]
Closing per lack of response.
