### ISSUE TITLE
Javascript Exception: invalid host

### ISSUE THREAD

**Issue by afilp** [facebook/react#11685]
Using:

    "react": "^16.1.1",
    "react-native": "^0.50.4",

When releasing the app for Android, we get this error upon launching it (the app does not even appear and crashes):

![screenshot_2017-11-28-18-09-15-846_com miui bugreport](https://user-images.githubusercontent.com/7850073/33330457-96f799da-d467-11e7-87e1-7d9a78c2bf5f.png)

We believe that this may be related to `React` and the Javascript engine on the mobile. Any ideas why is this happening? 

Note that this is a `react native` application.

**Comment by gaearon** [comment]
Please file this in the React Native repository. Thanks!

https://github.com/facebook/react-native

**Comment by afilp** [comment]
@gaearon Thanks, but is this really a React Native issue? The crash happens on the React library and seems to be something with the execution of the JavaScript.

**Comment by gaearon** [comment]
There is no native code in this repository at all. I know it says `com.facebook.react` but I assure you this code doesn't exist here.

**Comment by gaearon** [comment]
In particular, there is no code in React that deals with betwork.
