### ISSUE TITLE
Remove support for TapEventPlugin

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11689]
Some libraries relied on it so we kept it in 16, but it's impossible to support it forever given that we want to make changes to the event system. We should deprecate [the injection it relies on](https://github.com/zilverline/react-tap-event-plugin/blob/f7ed5c560011590d24e07480686b234b2f3ea1f5/src/injectTapEventPlugin.js#L23) and remove it in React 17. The migration path is to turn it into a userland `<Tappable>` component or something like that. Hopefully somebody using `TapEventPlugin` can work on this, as we don't actively use it.

**Comment by rafrex** [comment]
What about using the React Interactive component? It has events for tap (without delay), long press, two finger tap, etc, and a `touchActive` state for styling touch interactions.
https://github.com/rafrex/react-interactive

**Comment by gaearon** [comment]
I think people would probably be looking for a very targeted API compatible replacement that is more or less exact port in terms of features. This component seems to serve a broader use case.

**Comment by gaearon** [comment]
We did that.
