### ISSUE TITLE
Warning the tag <blockqoute> is unrecognized in this browser

### ISSUE THREAD

**Issue by Akurganow** [facebook/react#11682]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In Chrome 62 js console i see this warning
```
Warning: The tag <blockqoute> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
```
But tag is supported by this browser

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
- [jsfiddle example](https://jsfiddle.net/0dc33mf2/)

**What is the expected behavior?**
This warning should not be displayed

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- React 16.1.1
- Chrome 62

This was ok in React 15.6.1

**Comment by mijamo** [comment]
Isn't that just a typo because you wrote `blockqoute` instead of `blockquote`?

**Comment by Akurganow** [comment]
Oh, sorry! Thanks
