### ISSUE TITLE
How to use two versions of the React (0.14 && 16) at the same time?

### ISSUE THREAD

**Issue by makhnatkin** [facebook/react#11719]
I want to request a ***feature*** or ask ***question***?

I was faced with the dilemma of using two versions of React at the same time. This problem occurs when writing a large project-container (on the React 16), which within themselves can download the app-widgets (previously written that using an older version of React).

Can I without changing old projects to put them to respond with the old version React and for new projects to put to React 16?

For example, webpack solution, something like this... (this example renames the old version to the new one, but I'm looking for the reverse solution)

`module.exports = {`
`    // ... other settings ...`
` `
`    resolve: {`
`        alias: {`
`            "react": __dirname + '/node_modules/react',`
`            "react/addons": __dirname + '/node_modules/react/addons',`
`        }`
`    }`
` `
` `    // ... other settings ...
`}`

**Comment by gaearon** [comment]
This sounds like a question about your module bundler than about React.
I encourage you to use community support resources for that, as this is a bug tracker.

https://reactjs.org/community/support.html

In general it's not recommended to use two versions of React in one project.

**Comment by makhnatkin** [comment]
@gaearon Yes, I agree that this is not a bug, thanks for the redirect, I will ask my question there. And I agree that using two versions of React - a dubious decision, but I need it, otherwise the project-container will be forced to always work with the old version of React.
