### ISSUE TITLE
Do not evaluate -0 prop to 0 or use SameValueZero comparison in shallowEqual to prevent double render

### ISSUE THREAD

**Issue by chicoxyzzy** [facebook/react#11710]
**Do you want to request a *feature* or report a *bug*?**
Feature / Bug (not sure)

**What is the current behavior?**
For now [`shallowEqual` function](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js#L18-L32) uses [_SameValue_](https://tc39.github.io/ecma262/#sec-samevalue) comparison (aka [`Object.is`](https://tc39.github.io/ecma262/#sec-object.is)) but `-0` is evaluated to `0` inside of React anyway. 

Example: https://jsfiddle.net/chicoxyzzy/Luktwrdm/46/
`Object.is` comparison is false in `shallowEqual` of second `ReactDom.render` call, so as we can see `console.log` is called twice.

**What is the expected behavior?**
`shallowEqual` should use [_SameValueZero_ comparison](https://tc39.github.io/ecma262/#sec-samevaluezero) so React component doesn't render second time.
 
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All browsers / [React >= 15.0.0](https://github.com/facebook/react/blob/master/CHANGELOG.md#notable-bug-fixes)

The change doesn't affect React users because `-0` evaluates to `0` so it's not a breaking change for React, but it's a breaking change for `shallowEqual` and fbjs.

Alternatively we shouldn't evaluate `-0` to `0` inside of React.

I'm ready to file PR as soon as we realize what the proper behavior is.

**Comment by chicoxyzzy** [comment]
I just updated example in first post to use `PureComponent` (was mistakenly set to `Component` on some of previous updates)

**Comment by chicoxyzzy** [comment]
IMO there's also should be **bug** label. Current behavior is not expected in either case.

**Comment by gaearon** [comment]
How do you encounter this in practice? In which cases does it matter?

Are there any speed downsides to your prooosal?

**Comment by chicoxyzzy** [comment]
> How do you encounter this in practice? In which cases does it matter?

It does matter only for cases when I need to (a) just to print `-0` in my component (b) or change `0` to `-0`.

Case a:
I propagate value `-0` to my component and I get `0`. Is it expected?
(personally I don't care much but it's more like unexpected behavior)

Case b:
I change `0` to `-0` in my `PureComponent` or any component using `shallowEqual` comparison.
- If behavior in case a is expected (`-0` and `0` are treated as same value) than I expect no rerender (which occurs though)
- If behavior in case a is unexpected than I'm ok with rerender but I still expect from my component to print `-0` after it

> Are there any speed downsides to your prooosal?

As you can see actually there are two problems and two proposals.

Proposal 1: fix case a.

Not sure about speed downsides but I don't expect React to slowdown.

Proposal 2: fix double rerender in case 2 using SameValueZero instead of SameValue

I expect it to work at least not slower than [current `Object.is` polyfill](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js#L18-L32) shipped with fbjs package. Compare it with
```
function SameValueZero(x, y) {
  return (x === y) || (isNaN(x) && isNaN(y));
}
```
Also I don't expect much downgrade if we'll stop to ship our own `Object.is` polyfill because it does additional checks under the hood as current polyfill does.

**Comment by gaearon** [comment]
I mean, how do you end up with 0 or -0 in a sequence for the same prop in practice? I’m just curious about the real world use case.

**Comment by chicoxyzzy** [comment]
For example x/y, where x equals 0 and y is negative number

**Comment by gaearon** [comment]
>Alternatively we shouldn't evaluate -0 to 0 inside of React.

Where does this happen?

**Comment by chicoxyzzy** [comment]
IDK yet. Let me check.

**Comment by chicoxyzzy** [comment]
It turns out that it's not inside React and `-0` evaluates to `'0'` before injecting to DOM (because `String(-0) === '0'`). So I think it's better to keep things as is, and if someone whants to render `'-0'`, than that should be done in userland:
```js
class App extends PureComponent {
  render() {
    console.log('render');
    const { n } = this.props;
    return Object.is(n,-0) ? `-${n}` : n;
  }
}
```

So it seems that we should just prevent rerendering changing `Object.is` polyfill to SameValueZero in  fbjs's `shallowEqual`. But if we'll do this, it'll be impossible to print negative zero as it is in my example bellow.

**Comment by chicoxyzzy** [comment]
Now I think that everything works as expected 😄

It was great dive into spec and React. I enjoyed it! Sorry for bothering you
