### ISSUE TITLE
React complains when I use `super(arguments)` on constructor

### ISSUE THREAD

**Issue by krabbypattified** [facebook/react#11738]
The code below gives me the following warning:

```
Warning: SearchBar(...): When calling super() in `SearchBar`, make sure to pass up the same props that your component's constructor was passed.
```

This shouldn't happen. The `arguments` variable should be acceptable in a call to the `super` constructor.

```js
class Foo extends React.Component {
  constructor() {
    super(arguments)
    this.state = {bar: ""}
  }
}
```

**Comment by gaearon** [comment]
That's not how JS works. `arguments` is a special array-like object, but you pass it as a single argument.

You probably mean this instead:

```js
super(...arguments);
```
