### ISSUE TITLE
Do we still need to stringify attributes before assigning them?

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11735]
React manually stringifies all attributes before assigning them:

https://github.com/facebook/react/blob/master/packages/react-dom/src/client/DOMPropertyOperations.js#L169-L179

This appears to be for IE8/9. However it's possible that this is an IE8 only behavior. See IE9:

<img width="1104" alt="screen shot 2017-11-30 at 8 02 51 pm" src="https://user-images.githubusercontent.com/590904/33463221-2eeb4770-d60a-11e7-9915-2a2918ca22b9.png">

<img width="752" alt="screen shot 2017-11-30 at 8 03 38 pm" src="https://user-images.githubusercontent.com/590904/33463224-3595328e-d60a-11e7-9786-e2ac050ffb53.png">

Can we get rid of `'' + value` in DOMPropertyOperations?

**Comment by syranide** [comment]
I wouldn't trust compatibility mode too much, maybe old FF has this problem too (if we still support it)?
