### ISSUE TITLE
Investigate forEach() iterations showing up in init time profiling

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11748]
Not sure if this is real, but Chrome profiler highlights a few places where we have `forEach` on init time as hot paths taking ~30ms.

<img width="530" alt="screen shot 2017-12-01 at 21 02 48" src="https://user-images.githubusercontent.com/810438/33503308-1e530ba6-d6db-11e7-95fa-45c7af34e79d.png">
<img width="408" alt="screen shot 2017-12-01 at 21 02 55" src="https://user-images.githubusercontent.com/810438/33503309-1e6ac138-d6db-11e7-9027-37f37ae6b7f6.png">

Need to have a good look at these.

**Comment by nhunzaker** [comment]
I wonder what the gzipped difference would be if we just inlined these.

**Comment by iamdustan** [comment]
If there is a GC pause that happens to trigger while that function is running Chrome counts that time against it.
