### ISSUE TITLE
Elements rendering with import before usage 

### ISSUE THREAD

**Issue by stevematdavies** [facebook/react#11743]
React 16 is attempting to render as soon as it is imported, regardless of whether its used in the component it is being imported to. There is zero information about this, and is highly worrysome, and has stopped our production. 

```
// ComponentA.js

/* When a path is called in Router, Things are saved to session storage then C is rendered */
const item = sessionStorage.getItem('###') // things saved above
export default const ComponentA = props => (
  ...
)

// ComponentC.js

import {ComponentA} from './ComponentA; // not used at all yet!
import {ComponentB} from './ComponentB;

const ComponentC = props => (<ComponentB />);

ERROR // item is null????
```

**Comment by jquense** [comment]
Hi there, sorry it's not clear what the issue or error is. Can you put together a working example using https://codesandbox.io/ maybe, it should emulate your env a bit closer than jsfiddle

**Comment by stevematdavies** [comment]
Sorry, the post was made for StackExchange, my mistake for having too many tabs open. However, i found the issue, a basic mistake on my part!
