### ISSUE TITLE
Fix the misleading error message in production

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11761]
See this test case:

https://github.com/facebook/react/blob/323efbc33c27a602a4aab8519f58feba1e0a216c/packages/react-dom/src/__tests__/ReactStatelessComponent-test.js#L142-L157

Pretty sure the different message in production wasn't intentional, but is a consequence of `ReactCurrentOwner.current` not being set in production for functional components.

We need to see if it's possible to emit the same (useful) message both in development in production. If it's not possible, we need to change the production message to be more ambiguous instead of suggesting the wrong reason for the problem.

**Comment by extwiii** [comment]
What about this; 
'Warning: Stateless function components cannot be given refs.Attempts to access this ref will fail.\n\nCheck the render method '.

Similar to it('should warn when given a string ref' test spec.

**Comment by gaearon** [comment]
I don't see a problem with that one. Do you?

**Comment by skiritsis** [comment]
I wouldn't mind checking this if @extwiii does not want to.

**Comment by gaearon** [comment]
@skiritsis You got it!

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/11782
