### ISSUE TITLE
Pressing tab in text input moves the input - Bug?

### ISSUE THREAD

**Issue by AaronGillBraun** [facebook/react#11772]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
Pressing tab inside of a text input physically moves the input on the page
**Demo**
![bug](https://user-images.githubusercontent.com/15055317/33579955-74a4c22a-d919-11e7-9d9e-29bcd9d45677.gif)

**What is the expected behavior?**
It should either do nothing, or switch inputs
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version 16
OS: Mac OSX
Browser: Chrome

(this does not happen on FireFox)

I didn't know where to post this, I can't figure out if its a React bug, or something else.
My implementation is as simple as:
```javascript
<input type="text" placeholder="Username" onChange={evt => this.setState({ username: evt.target.value })} /> 
```

**Comment by M-ZubairAhmed** [comment]
can you also please post a quick demo on jsfiddle or something?

**Comment by AaronGillBraun** [comment]
The problem is I don't face this issue with other text inputs on react, and that means it's hard to reproduce.

**Comment by nhunzaker** [comment]
@AaronGillBraun It's hard to figure out a next step without the ability to reproduce your issue. If you are able to provide some more context, it would help greatly.

Did you record your example within an existing application, or an isolated example?

**Comment by AaronGillBraun** [comment]
I am unable to reproduce this issue anywhere by my application and thus am closing it. This obviously is not a React issue. (still for the life of me can not figure this one out)

**Comment by nhunzaker** [comment]
No worries. Best of luck!
