### ISSUE TITLE
Refactor packages/shared/ReactDOMFrameScheduling.js

### ISSUE THREAD

**Issue by blling** [facebook/react#11784]
I found the code format is not good in packages/shared/ReactDOMFrameScheduling.js and the js IDE is always give some warn as follows, i think should refactor it.
![image](https://user-images.githubusercontent.com/26540808/33658864-26f1821a-dab9-11e7-90ec-84979bb7b9c2.png)

**Comment by gaearon** [comment]
Please file an issue with the IDE. The code is fine :-)

**Comment by blling** [comment]
@gaearon the other js file is no error or warn but this one, i think the main problem is that most of the js code is not encapsulated in the method but all of them are placed in a js file. I will ignore the error and warn in the IDE.

**Comment by blling** [comment]
@gaearon  which IDE you are using for daily work? ^_^

**Comment by gaearon** [comment]
Sublime
