### ISSUE TITLE
Synthetic Event breaks in IE11

### ISSUE THREAD

**Issue by juanca** [facebook/react#11788]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`SyntheticEvent.js` breaks in IE11.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

`Object.assign` is explicitly used to extend the prototype of `SyntheticEvent`.
https://github.com/facebook/react/blob/f72043a36903a18703168a1ebfe271c150f27330/packages/events/SyntheticEvent.js#L115

**What is the expected behavior?**

`SyntheticEvent.js` should work. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Broken in React 16 + IE11. It used to work in React 15 + IE11. 

Is the recommended approach to use babel to polyfill `Object.assign`? If so, I can open a new issue for https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by juanca** [comment]
I think the rest of the code uses a package:

```
import assign from 'object-assign';
```

Should I just submit a quick PR?

**Comment by juanca** [comment]
Oh, it seems that other files will only use `Object.assign` for dev environments.

https://github.com/facebook/react/blob/3c977dea6b96f6a9bb39f09886848da870748441/packages/react/src/React.js#L57-L58

**Comment by jquense** [comment]
the Object.assign is transpiled already. you can see in the package code: https://unpkg.com/react-dom@16.2.0/cjs/react-dom.development.js no Object.assign. If you have a specific issue it'd be helpful to know what error you'r getting and a way to reproduce it

**Comment by juanca** [comment]
Oh, interesting.

I'm getting:

```
Object doesn't support property or method 'assign'
```

This is in a fairly complex part of the application so I'll see if I can come up with minimal repro steps.

**Comment by juanca** [comment]
Just found a hint that it's actually another library -- `./node_modules/react-tap-event-pluging/src/SyntheticEvent.js`. 🤦‍♂️ 

Closing this.
