### ISSUE TITLE
RFC: Remove vars follow up

### ISSUE THREAD

**Issue by blling** [facebook/react#11783]
Most of the `var` has been removed after the PR #11780(thanks @raphamorim again) merged, so we could lint against developers use `var` again, but this is a bit tricky because some files have to use `var`. we should have a way to override lint configuration for a subset of the files, so we should discuss the solutions here.

**Comment by gaearon** [comment]
For Prettier, we have separate configurations for files that should be ES5 and ES6. We need to extract these paths to a shared config, and then split the ESLint task into two runs, one of them would assume the code is ES5 and another, ES6.

**Comment by davscro** [comment]
hi @gaearon
could we write custom eslint preprocessor and for "var" files (~40) override ```
'no-var'```
 rule?

**Comment by gaearon** [comment]
Here's [how we separate configs for Prettier](https://github.com/facebook/react/blob/5bd2321ae3dd7d68ac02dee3c3f271e9d0ee8784/scripts/prettier/index.js#L29-L57). Since we now [call ESLint through its Node API too](https://github.com/facebook/react/blob/5bd2321ae3dd7d68ac02dee3c3f271e9d0ee8784/scripts/eslint/index.js#L15), I imagine we would use a similar strategy there. Divide it into two calls, and override rules for one of the calls.

**Comment by ctxhou** [comment]
Hi @gaearon, I want to work on this.
Can you give me some instructions? Like what kind of file we will permit to use `var`?

**Comment by ctxhou** [comment]
Ok thanks, it helps!

**Comment by blling** [comment]
@ctxhou i think this should be done as fast as you can, oterwise `vars` will be add again.

**Comment by ctxhou** [comment]
There is one thing I want to discuss.
Currently, these is prettier es6 files pattern:
```
[
   // Internal forwarding modules
   'packages/*/*.js',
   // Source files
   'packages/*/src/**/*.js',
   'packages/shared/**/*.js',
 ]
```

But for eslint, the es6 lint pattern should be `all js files without es5 files`?
So it means that the shared es6 pattern will not be the same with prettier and eslint config.
Is it correct?

**Comment by gaearon** [comment]
I don’t understand why it would be different. Those are ES6 files. The ES5 files are listed separately below.

**Comment by ctxhou** [comment]
Sorry, I misunderstand the pattern.
Here I create a pr to fix this issue: https://github.com/facebook/react/pull/11794

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11794.
