### ISSUE TITLE
Input attribute 'readonly' triggers a warning, which prevents the attr to be passed to component

### ISSUE THREAD

**Issue by dreamyguy** [facebook/react#11785]
I just came across a warning while attempting to pass the attribute `readonly` to an input (which is rendered within a 3rd party component, https://github.com/gpbl/react-day-picker/).

> Warning: Unknown DOM property readonly. Did you mean readOnly?

`readonly` is a [valid input attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).

I'm not sure where this error is coming from, but I'm assuming it's in **React** as the error seems pretty generic.

It would be nice to get past this error, as my component won't get the attribute I'm trying to pass to it. 😢

**Comment by dreamyguy** [comment]
Hm.. my bad. The attribute should be passed as:

`readOnly: true`

...and not:

`readonly: 'readonly'`

**Comment by gaearon** [comment]
React differs from HTML in that it uses `camelCase` for built-in attributes. Most DOM APIs also do that by the way—people just rarely use them directly, and forget about that :-)

https://reactjs.org/docs/dom-elements.html
