### ISSUE TITLE
Further understanding reconciliation

### ISSUE THREAD

**Issue by giorgim** [facebook/react#11793]
One tutorial mentioned that here

```
render3() {
  if (this.state.showWarning) {
   return (
     <div>
       <Warning />
       <StatefulComponent key="a" />
     </div>
   );
  }

  return (
    <div>
      <StatefulComponent key="a" />
    </div>
  );
}
```

that instance of `<StatefulComponent/> `will be maintained between re renders. I understand this.

However let's consider transition from `showWarning= false` and then to `showWarning=true.`
This means when `showWarning` became `true`, React checks that previously first child of div was `<StatefulComponent/>`, now it is `<Warning/> `- so why doesn't it unmount the` <StatefulComponent/>`? Instead it seems to compare keys and find out the` <StatefulComponent/>` didn't change. **My question is related: so how is this comparison logic order, based on what are components between different renders first compared - based on keys?**

---

Because in the same tutorial author goes with this example
```

render1() {
  if (this.state.showWarning) {
    return (
      <div>
        <Warning />
        <StatefulComponent />
      </div>
    );
  }

  return (
    <div>
      <StatefulComponent />
    </div>
  );
}
```

and says that when showWarning goes again from false to true, react will check and say hey, there was `<StatefulComponent/>` before and now there is a `<Warning/>` component so let's unmount that `<StatefulComponent/>`. **This is same example as previous but here are no keys explicitly provided, so based on what does react compare `<Warning/>` and `<StatefulComponent/>`, based on their position in the tree and on the fact that they are both first childs of div?**

---
I found this  [code](https://github.com/facebook/react/blob/0e976e136c0d0841aec71de4a4f6163963763d3f/src/renderers/shared/stack/reconciler/ReactChildReconciler.js#L112-L176) and it seems react uses "name" property as a first instance to compare previous and next children - but I fail to see what is "name".

**Comment by gaearon** [comment]
If there are no keys, React assigns implicit keys equal to the indices. Does this answer your question?

The code you want to look at is `reconcileChildrenArray` in this file: https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactChildFiber.js

**Comment by giorgim** [comment]
@gaearon In my second code snippet when going from showWarning=false to true, why does it compare `<StatefulComponent/> `with `<Warning/>` ? because they have same keys ?

**Comment by gaearon** [comment]
Yes (by default keys become indices, so both have a key of `0`).

**Comment by gaearon** [comment]
In practice, if people want to preserve state, the usually write it like this:

```js
  return (
    <div>
      {this.state.showWarning && <Warning />}
      <StatefulComponent />
    </div>
  );
```

In that case the state would be preserved, but you wouldn't have to explicitly specify keys.

**Comment by giorgim** [comment]
@gaearon and in the first case in similar situation, react first makes a query like hey is there a child which has key "a"? and since answer is postivie, leaves `<StatefulComponent/>`? and that is why it avoids comparing `<StatefulComponent/> `with `<Warning/>`?

**Comment by gaearon** [comment]
Yes.

**Comment by giorgim** [comment]
@gaearon Or I think it is more hey `<Warning/>` has key "1" but in old children there is no item with such key, so create `<Warning/>`. With` <StatefulComponent/> `hey it has key "a" but hey also in old children there is item with key "a" so modify it. I think this is more correct than what I wrote previously.

**Comment by gaearon** [comment]
In your first example, the keys are:

```
                        BEFORE            AFTER       RESULT
Warning                 0 (implicit)      -           unmount
StatefulComponent       a                 a           update
```


In your second example:

```
                        BEFORE            AFTER           RESULT
Warning                 0 (implicit)      -               unmount
StatefulComponent       1 (implicit)      0 (implicit)    unmount old, mount new
```

In my example:

```
                        BEFORE            AFTER           RESULT
Warning                 0 (implicit)      -               unmount
StatefulComponent       1 (implicit)      1 (implicit)    update
```

**Comment by gaearon** [comment]
I think this table would make more sense if we used key as the... key.

**Comment by gaearon** [comment]
Your first example:

```
        BEFORE                    AFTER                     RESULT
0:      <Warning />               -                         unmount
a:      <StatefulComponent />     <StatefulComponent />     update
```
   
Your second example:

```
        BEFORE                    AFTER                     RESULT
0:      <Warning />               <StatefulComponent />     unmount old, mount new
1:      <StatefulComponent />     -                         unmount
```

My example:

```
        BEFORE                    AFTER                     RESULT
0:      <Warning />               -                         unmount
1:      <StatefulComponent />     <StatefulComponent />     update
```

**Comment by giorgim** [comment]
@gaearon I think I grasped your table just you are using case when going from showWarning=true, to false. Initially I was referring to case when we go from showWarning=false, to showWarning=true. So in that case it would be
```

                        BEFORE            AFTER       RESULT
Warning                         -                  0           mount
StatefulComponent       a                 a           update
In your second example:

                        BEFORE            AFTER                   RESULT
Warning                         -                     0                  unmount Stateful moune Warning
StatefulComponent       0 (implicit)      1 (implicit)    mount new Stateful
```

**Comment by giorgim** [comment]
@gaearon Can you confirm my table above?

**Comment by gaearon** [comment]
I think this looks almost right, but it actually exposes an issue with how I wrote the table originally. It is much clearer what's going on if you use key as the row instead.

**Comment by gaearon** [comment]
Here's a full version.

### Your first example

```js
if (this.state.showWarning) {
 return (
   <div>
     <Warning />
     <StatefulComponent key="a" />
   </div>
 );
}

return (
  <div>
    <StatefulComponent key="a" />
  </div>
);
```

#### `this.state.showWarning`: `false` -> `true`

```
KEY     BEFORE                    AFTER                     RESULT
0:      -                         <Warning />               mount Warning
a:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
```

#### `this.state.showWarning`: `true` -> `false`

```
KEY     BEFORE                    AFTER                     RESULT
0:      <Warning />               -                         unmount Warning
a:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
```
   
### Your second example

```js
if (this.state.showWarning) {
  return (
    <div>
      <Warning />
      <StatefulComponent />
    </div>
  );
}

return (
  <div>
    <StatefulComponent />
  </div>
);
```

#### `this.state.showWarning`: `false` -> `true`

```
KEY     BEFORE                    AFTER                     RESULT
0:      <StatefulComponent />     <Warning />               unmount StatefulComponent, mount Warning
1:      -                         <StatefulComponent />     mount StatefulComponent
```

#### `this.state.showWarning`: `true` -> `false`

```
KEY     BEFORE                    AFTER                     RESULT
0:      <Warning />               <StatefulComponent />     unmount Warning, mount StatefulComponent
1:      <StatefulComponent />     -                         unmount StatefulComponent
```

### My example

```js
return (
  <div>
    {this.state.showWarning && <Warning />}
    <StatefulComponent />
  </div>
);
```

#### `this.state.showWarning`: `false` -> `true`

```
KEY     BEFORE                    AFTER                     RESULT
0:      -                         <Warning />               mount Warning
1:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
```

#### `this.state.showWarning`: `true` -> `false`

```
KEY     BEFORE                    AFTER                     RESULT
0:      <Warning />               -                         unmount Warning
1:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
```

**Comment by giorgim** [comment]
@gaearon I think I got my table correctly! I can't see different w.r.t to your latest post.
But thanks for your input and help!.

**Comment by SachinBhandari** [comment]
> Here's a full version.
> 
> ### Your first example
> ```js
> if (this.state.showWarning) {
>  return (
>    <div>
>      <Warning />
>      <StatefulComponent key="a" />
>    </div>
>  );
> }
> 
> return (
>   <div>
>     <StatefulComponent key="a" />
>   </div>
> );
> ```
> 
> #### `this.state.showWarning`: `false` -> `true`
> ```
> KEY     BEFORE                    AFTER                     RESULT
> 0:      -                         <Warning />               mount Warning
> a:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
> ```
> 
> #### `this.state.showWarning`: `true` -> `false`
> ```
> KEY     BEFORE                    AFTER                     RESULT
> 0:      <Warning />               -                         unmount Warning
> a:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
> ```
> 
> ### Your second example
> ```js
> if (this.state.showWarning) {
>   return (
>     <div>
>       <Warning />
>       <StatefulComponent />
>     </div>
>   );
> }
> 
> return (
>   <div>
>     <StatefulComponent />
>   </div>
> );
> ```
> 
> #### `this.state.showWarning`: `false` -> `true`
> ```
> KEY     BEFORE                    AFTER                     RESULT
> 0:      <StatefulComponent />     <Warning />               unmount StatefulComponent, mount Warning
> 1:      -                         <StatefulComponent />     mount StatefulComponent
> ```
> 
> #### `this.state.showWarning`: `true` -> `false`
> ```
> KEY     BEFORE                    AFTER                     RESULT
> 0:      <Warning />               <StatefulComponent />     unmount Warning, mount StatefulComponent
> 1:      <StatefulComponent />     -                         unmount StatefulComponent
> ```
> 
> ### My example
> ```js
> return (
>   <div>
>     {this.state.showWarning && <Warning />}
>     <StatefulComponent />
>   </div>
> );
> ```
> 
> #### `this.state.showWarning`: `false` -> `true`
> ```
> KEY     BEFORE                    AFTER                     RESULT
> 0:      -                         <Warning />               mount Warning
> 1:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
> ```
> 
> #### `this.state.showWarning`: `true` -> `false`
> ```
> KEY     BEFORE                    AFTER                     RESULT
> 0:      <Warning />               -                         unmount Warning
> 1:      <StatefulComponent />     <StatefulComponent />     update StatefulComponent
> ```

@gaearon I didn't quite understand your example, **My example**.

In the case of, `this.state.showWarning:` `false` -> `true`

Why do we have `key=1` for `<StatefulComponent/>` at `before` step.
Is that because it is based on childrens not on the output, like `{this.state.showWarning && <Warning/>` output to false?
