### ISSUE TITLE
Select warning fires repeatedly 

### ISSUE THREAD

**Issue by arackaf** [facebook/react#11795]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

See fiddle https://jsfiddle.net/j2nzg31L/1/

The warning related to the select fires repeatedly.  @gaearon tells me it should dedupe, and that this is a bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

See above

**What is the expected behavior?**

See above

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.2

**Comment by gaearon** [comment]
We should deduplicate this warning (like we do with many other warnings).

**Comment by watadarkstar** [comment]
@gaearon Hi Dan, I can take this. I imagine its similar to: https://github.com/facebook/react/pull/11113

**Comment by gaearon** [comment]
Yep. Sounds good!

**Comment by watadarkstar** [comment]
@gaearon 

Hi Dan, I wanted to check with you that I am on the right track before I try writing any code.

So here is the warning:

https://github.com/facebook/react/blob/d9869a45616884512220e162d1d3589f48a26fb0/packages/react-dom/src/client/ReactDOMFiberOption.js#L36-L45

I'm not sure if I should be writing a test in: 

- [react-dom/src/__tests__/ReactDOMSelect-test.js](https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactDOMSelect-test.js)
- [react-dom/src/__tests__/ReactDOMOption-test.js](https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactDOMOption-test.js)

And I don't see a test that already tests for this warning - am I missing something? Or should I write a entirely new test in one of those files?

I haven't worked with the test suite before so I'm not sure how its supposed to be organized.

**Comment by gaearon** [comment]
I don't think it matters which file you write it in.

To verify if there are any existing tests, you can just comment out the warning and run `npm test`. If nothing fails, well, yeah, then we didn't have tests for it.

**Comment by gaearon** [comment]
Thanks!

**Comment by arackaf** [comment]
Wow that was incredibly fast - great work ❤️

**Comment by watadarkstar** [comment]
@arackaf No problem, couldn't have done it without Dan's super fast support (I swear he is not human answering all our tweets and github comments instantly) 😜

**Comment by blling** [comment]
OMG, Dan has no weekend!

**Comment by gaearon** [comment]
It’s really cold outside and I’m too bored :-) I’ll go do something else now.

**Comment by watadarkstar** [comment]
Lol no Dan don't leave us! 😰
