### ISSUE TITLE
Run benchmark trials in random order

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11805]
Our current benchmark script runs all trials in a specific order.
You can try it by running:

```
cd scripts/bench
yarn
yarn start
```

(Note: it takes a looong time to finish.)

I think running all trials in a deterministic order like we do now may actually introduce issues. Such as if some other process starts grabbing CPU in the middle of the trials, a specific set of trials (e.g. "HN" benchmark on "base" repo)  will be affected, and the results skewed.

But if we ran all trials in a random order, I would expect any temporary changes to be evenly distributed between random runs, and thus not favor any particular version or benchmark. Wouldn't that be better?

Does this make sense? Tagging as a good issue to look into, but I don't promise this would be easy.

**Comment by mannanali413** [comment]
@gaearon i can pick this up. :)

**Comment by gaearon** [comment]
Sounds great!

**Comment by mannanali413** [comment]
@gaearon please have a look at the PR and let me know if the randomisation introduced would meet the requirement.
Cheers :)

**Comment by agasnikov** [comment]
I'm on it
