### ISSUE TITLE
MouseDown / MouseUp abandoned in Chrome 55+

### ISSUE THREAD

**Issue by maurocolella** [facebook/react#11817]
See:
https://developers.google.com/web/updates/2016/10/pointer-events

MouseDown, MouseUp, possibly others... do not do anything in Chrome 55+

Is it possible to shim pointervents in somehow?

**Comment by gaearon** [comment]
Can you point me to where exactly does it say that those events don’t work? An example fiddle would also help.

**Comment by maurocolella** [comment]
My bad, it doesn't. For Chrome 55, a blog post about changes mentions this:
https://developers.google.com/web/updates/2016/11/nic55#pointer-events

I am not able to reproduce the issue if I attach the handler to the target element using vanilla javascript. But I _have_ distinctly observed `MouseDown` and `MouseUp` not firing properly under some circumstances, and there are open bug reports (in unrelated projects) regarding similar issues.

Of interest:
https://github.com/AnalyticalGraphicsInc/cesium/issues/4768

Also:
https://github.com/Leaflet/Leaflet/issues/5556

**Comment by gaearon** [comment]
I'll close this issue but if you have a reproducing case where it's React's fault, or React is doing something that it shouldn't, please reopen (or file a new issue) and we'll look at it. Thanks!

**Comment by maurocolella** [comment]
You're welcome. Last I checked, react doesn't implement/use `pointerevents`. 

It might be worth mapping mouse and touch events to the seemingly better-supported "modern way" in that case.
