### ISSUE TITLE
development env check is not friendly to other bundler-tools(except webpack)

### ISSUE THREAD

**Issue by please-hate-me** [facebook/react#11820]
I don't like use `Webpack`, lots of coders don't use `Webpack` in China. We have a more ease-to-use tool called [fis3](http://fis.baidu.com/fis3/api/index.html). 
The problem is that `fis` parse the file-dependencies by checking keywords like `require()`,`require.async()` . But right now react added codes like these
 `if ('development' === 'production') {
    module.exports = require('node_modules/react-dom/cjs/react-dom.production.min');} 
else {
    module.exports = require('node_modules/react-dom/cjs/react-dom.development');
  }`.

Then `fis` will the get the result, the current file rely on the `production` and `development` files. But we only need one of the them.
So can u guys please make it a agnostic to the environment. let the tools work on that.

**Comment by gaearon** [comment]
Saying it’s specific to webpack is not fair.

This is perfectly valid CommonJS. **It works on Node, and in webpack, Browserify, Rollup, Metro, Brunch, Parcel, and any other major bundler.** All of them can do dead code elimination with Uglify too, so if it’s not something fis supports, I encourage you to file an issue with them. 

You can find the instructions for supported bundles here: https://reactjs.org/docs/optimizing-performance.html#use-the-production-build. If you figure out how to do it with fis please send a PR. 

To get a production build, you need to apply a minification step (such as Uglify). It will remove falsy conditions and strip unnecessary requires.

I hope this helps!

**Comment by gaearon** [comment]
Also note that you can always use a precompiled build from the CDN if you have issues with a bundler.

https://reactjs.org/docs/installation.html#using-a-cdn

**Comment by please-hate-me** [comment]
Thanks, I will make a touch with the fis team.

**Comment by gaearon** [comment]
If we can help in any way (e.g. by explaining more how it works) please let me know and I’d be happy to chat. I see they have a plugin system. Typically having an Uglify plugin that runs on modules before the bundler interprets `require`s is the solution.
