### ISSUE TITLE
Cursor jumps when backspacing in a number input (with ShadowDOM)

### ISSUE THREAD

**Issue by YellowKirby** [facebook/react#11827]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Number inputs with decimal values in Chrome ShadowDOM do not maintain cursor position as user backspaces in the input field.

Super low-quality gif (sorry):
<img src="https://thumbs.gfycat.com/TautIncredibleEkaltadeta-size_restricted.gif"/>

This issue appears to be similar to the problem here: https://github.com/facebook/react/pull/7359, but in this case it's only custom elements with a shadow root that exhibit the problem.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
1. Have a React component render a number input: `<input type="number" />`.
2. Attach that React component as part of the ShadowDOM node of a custom element.
3. Enter in some decimal value (e.g., `88.88`) into the input.
4. Slowly backspace in the input. As soon as the decimal point would be the last character, the decimal point is removed and the cursor position jumps to the beginning of the input.

Demo: https://jsfiddle.net/69z2wepo/94566/

**What is the expected behavior?**

The ShadowDOM case behaves like the other cases: when backspacing in the input, the cursor does not jump to the beginning of the input and the decimal point is not unexpectedly deleted.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.2.0 + Chrome 62.0.3202.62 + OSX 10.12.6

**Comment by nhunzaker** [comment]
Oooh boy :). I wonder if this is happening because this line here:

https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberInput.js#L310

```
if (
    // Focused number inputs synchronize on blur. See ChangeEventPlugin.js
    type !== 'number' ||
    node.ownerDocument.activeElement !== node
) {
```

We only assign the value _attribute_ on a number input if it isn't the currently focused element. This i to keep it as similar to other inputs as possible. I wonder if the input is _never_ the active element in the case of a Shadow DOM.

**Comment by YellowKirby** [comment]
> I wonder if the input is never the active element in the case of a Shadow DOM.

Yeah, that `activeElement` line seemed a little suspect to me, but I haven't done much digging into the React codebase. 

https://developers.google.com/web/fundamentals/web-components/shadowdom#focus has a simple function that will walk the shadowDOM in the case where `activeElement` does have a shadow root:

```js
function deepActiveElement() {
  let a = document.activeElement;
  while (a && a.shadowRoot && a.shadowRoot.activeElement) {
    a = a.shadowRoot.activeElement;
  }
  return a;
}
```

**Comment by chrisdieckhaus** [comment]
I'd be interested in taking a stab at this. It seems like `ReactDOMFiberInput.js` is a good place to start, yes?

**Comment by avinashdvv** [comment]
**Help**
while i am tried to replicate this issue on my local mission with fixtures, i am getting an error like this
```TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.```

code 
```
import './polyfills';
import loadReact from './react-loader';

loadReact()
.then(() => import('./components/App'))
.then(App => {
	const {React, ReactDOM} = window;
	// ReactDOM.render(
	//   React.createElement(App.default),
	//   document.getElementById('root')
	// );
	class NumberInput extends React.PureComponent {
		constructor(props) {
		    super(props);
		    this.onChange = this.onChange.bind(this);
		    this.state = { value: '88.88' };
		}

		onChange(e) {
		    this.setState({ value: e.target.value });
		}

		render() {
		    return (
		       <label style={{display: 'block', margin: 10}}>
		         {this.props.children}:
		         {' '}
		         <input type='number' value={this.state.value} onChange={this.onChange} />
		       </label>
		    );
		}
	}

	// Broked :(
	customElements.define('with-shadow-dom', 
		class WithShadowDOM extends HTMLElement {
		   connectedCallback(){
				ReactDOM.render(
					<NumberInput>custom element with shadowDOM (broken)</NumberInput>, 
					this.attachShadow({ mode: 'open' })
		   )}
		}
	);

	ReactDOM.render(
		<NumberInput>non-custom element (working)</NumberInput>, 
		document.querySelector('#root')
	)
	document.body.appendChild(document.createElement('with-shadow-dom'));

});

```

**Comment by YellowKirby** [comment]
@avinashdvv  AFAIK that issue is happening because of the way babel typically transpiles ES6 classes. https://github.com/babel/babel/issues/4480

You might need to add a plugin like https://github.com/WebReflection/babel-plugin-transform-builtin-classes in order for it to work correctly.

**Comment by OliverRadini** [comment]
Is this still known to be a problem? The fiddle mentioned in the original issue seems to work correctly now. I tried specifically setting the React version in the fiddle to 16.2.0 but it still works.

**Comment by YellowKirby** [comment]
Hmm, yeah I can no longer reproduce either on the fiddle or when testing out some components on another project. Maybe this got fixed with an update to Chrome?

**Comment by matthewoates** [comment]
I can't reproduce this issue either.

**Comment by meowduchat** [comment]
If the cursor is at the beginning of the <input> and the backspace key is pressed, just do nothing.  Should work for any javascript based code.  Make sure you put this code AFTER modifying the input value.

onSomeInputEdit = function(event)
{
  some_input - event.target.value;

  if(event.keyCode == 8 && event.target.selectionStart ==0){
    event.preventDefault();
  }
}
