### ISSUE TITLE
Which is better to use three definitions of variables in React ES6? Why?

### ISSUE THREAD

**Issue by sosout** [facebook/react#11839]
```
// One
const arr = [7,8,9]; 
class WatchStore extends Component {
  constructor(props) {
     super(props);
   }
   ......
}

// Two
class WatchStore extends Component {
  constructor(props) {
     super(props);
     this.state = {
       arr: [7,8,9],
     }
   }
   ......
}

// Three
class WatchStore extends Component {
  constructor(props) {
     super(props);
   }
   componentDidMount() {
     this.arr = [7,8,9]; 
   }
   ......
}
```
which is the best way to use the three defined methods?
The arr does not need to be rendered, just make a temporary cache comparison new data use！

Thanks！

**Comment by sw-yx** [comment]
hi, all can do what you need, it just depends on what you want to do in the end. in particular your method Two stores the array in state so setting that state will trigger a rerender, whereas the other two methods you gave will involve mutating the array without rerendering the component. 

This is more of a question of opinion/code style and so is not a suitable issue to raise in this github repo. please have a look at https://reactjs.org/community/support.html for other venues of community support. thanks!

**Comment by mrchief** [comment]
Agree with @sw-yx. My 2 cents:

Option 1: Doesn't allow mutation. Go with this if you want to enforce this.

Option 2: Allows mutation, triggers re-rendering on mutation. 

Option 3: Allows mutation, no re-rendering on mutation. 

For **_your specific use_** case, Option 1 is the best choice.

**Comment by clemmy** [comment]
As @sw-yx and @mrchief pointed out, option 1 is the best choice for your use case, and issues not related to the React library itself should go into the appropriate channels.
