### ISSUE TITLE
[Question] Need help with react@16.0 new lifecycle

### ISSUE THREAD

**Issue by borm** [facebook/react#11843]
hi all, 
after i have update to react@16.0 and read this https://twitter.com/dan_abramov/status/843822280132190208
and this
https://github.com/facebook/react/issues/9214#issuecomment-287763538

i have create fiddle with example on CodeSandbox
https://codesandbox.io/s/0xryn12myn
i don`t understand why in not worked with hot reload when component inside hoc
when component is updated we have error

`
this.subscriptions.some is not a function
`

```jsx
const connect = (Composed, props = {}) => {
class Connect extends Component {
  ...
  getChildContext() {
    return {
      some: () => {
       // No one subscriptions after unmout
        this.subscriptions.some();
      },
      ...
    }
  }
  ....
};

return Connect;
}

import connect, { Child, GrandChild } from './connect';

@connect()
class App extends Component {

  render() {
    return (
      <div>
        <Child
          some={() => { console.log(1) }}
        >
          <GrandChild>
            GrandChild1234
          </GrandChild>
        </Child>
      </div>
    )
  }
}
```

but when i try use it without hoc, all okay
https://codesandbox.io/s/mzzr3k93vx

```jsx
class Connect extends Component {
  ...
  getChildContext() {
    return {
      some: () => {
       // No one subscriptions after unmout
        this.subscriptions.some();
      },
      ...
    }
  }
  ....
};

...
render() {
    return (
      <Connect>
        <Child
          some={() => { console.log(1) }}
        >
          <GrandChild>
            GrandChild1234
          </GrandChild>
        </Child>
      </Connect>
    )
  }
...
```

```jsx
class Child extends Component {
  ...
  componentWillMount() {
    console.log('Child WillMount');
    this.subscribe();
  }
  ....
  componentWillUnmount() {
    console.log('Child WillUnmount');
    this.unSubscribe();
  }
  ...
}

class GrandChild extends Component {

  componentDidMount() {
    this.context.some();
    console.log('Child DidMount');
  }
  ....
}
```

i have only one idea, put Connect component inside connect decorator, and in render return Composed inside Parent, work fine), i hope it`s not bug 😎

```jsx
const connect = (Composed, props = {}) => {

  class Connect extends Component {
    ...
    render() {
      return this.props.children;
    }

  }

  return class extends Component {
    render() {
      return (
        <Parent>
          <Composed
            {...props}
            {...this.props}
            {...this.state}
          />
        </Parent>
      );
    }
  };
};
```

**Comment by gaearon** [comment]
This is a lot of code to get through.

Is this a bug report? A support question? If this is a support question please use the appropriate resources: https://reactjs.org/community/support.html

If this is a bug report please create a *minimal* example: no external dependencies, no extra components, no hot reloading, just enough to reproduce the issue.

**Comment by borm** [comment]
i not sure it bug or not, but on my last example all worked fine
i have simplify my code how can maximum, it real implementation from my npm module
i can try create repo on git hub with all examples for you better understanding

**Comment by borm** [comment]
@gaearon, GH repo 
https://github.com/borm/react-mount

Please uncomment this
https://github.com/borm/react-mount/blob/master/src/components/App.js#L35

and try set any changes, you will see error

but this hack https://github.com/borm/react-mount/blob/master/src/components/Connect/goodConnect.js#L14 fixed this error

**Comment by borm** [comment]
up

**Comment by gaearon** [comment]
You are reporting a problem with *hot reloading*. It's not a supported feature of React itself. The package you're using with it has been deprecated. I recommend removing `react-transform-hmr` from your Webpack config and waiting until there's an official hot reloading solution, or working on your own.

**Comment by borm** [comment]
Thank
