### ISSUE TITLE
Incorrect error for <wbr> tag

### ISSUE THREAD

**Issue by mrchief** [facebook/react#11845]
**Do you want to request a *feature* or report a *bug*?**

 *bug*

**What is the current behavior?**

It currently gives out `Expected corresponding JSX closing tag for <wbr>` error for this tag.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

https://jsfiddle.net/mrchief/Luktwrdm/59/

**What is the expected behavior?**

`wbr` tag has no end tag as per the [spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-wbr-element). React should not report errors for this. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16 as of this writing. Not sure about previous version. Not dependent on any browser version.

**Comment by mrchief** [comment]
Ok, so rewriting the tag as `wbr />` in JSX emits the correct `<wbr>` tag in HTML. I think React has smarts for `wbr`, `br` etc. tags? If so, then this is a non-issue. Feel free to close it if there is nothing further to add/discuss here.

**Comment by aweary** [comment]
> wbr tag has no end tag as per the spec. React should not report errors for this.

JSX [has it's own specification](https://facebook.github.io/jsx/) which diverges from the HTML/XML specs. With JSX you need to provide a closing tag or use a self-closing tag.

> I think React has smarts for wbr, br etc. tags? If so, then this is a non-issue. Feel free to close it if there is nothing further to add/discuss here.

👍

**Comment by mrchief** [comment]
Found the smarts: https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/omittedCloseTags.js :+1: 

If only I could do some research upfront... :smile:
