### ISSUE TITLE
Is it possible to declare a class variable in component class?

### ISSUE THREAD

**Issue by prakharrke** [facebook/react#11842]
Is it possible to declare a class variable in a Component class?
For example,

```js
class App entends React.Component {

myVariable = true;

render(){
console.log(this.myVariable);  //Is this possible ?
return(
// return some dom element
);

}
}
```

I used to declare such variables earlier while using client-side rendering using webpack-dev-server. But recently I moved to server-side rendering using express and webpack-middleware. Now I can not declare such class variables. 
Where am I going wrong?

**Comment by fivepointseven** [comment]
You need [babel-plugin-transform-class-properties](https://www.npmjs.com/package/babel-plugin-transform-class-properties) to do this. You probably have it in your client side setup.
