### ISSUE TITLE
Map is not defined

### ISSUE THREAD

**Issue by zhiqiang21** [facebook/react#11841]
when i use reactv16.2  in my project.  on some mobile it error 

**Map is not defined**

```javascript
var VALID_FRAGMENT_PROPS = new Map([['children', true], ['key', true]]);
```

**Comment by TrySound** [comment]
@zhiqiang21 Which exactly mobile?

**Comment by zhiqiang21** [comment]
mobile information:
SamSung   Galaxy Note5   SM-N9200

i use browser information is 

UC browser v10.9.10.788

**Comment by TrySound** [comment]
@zhiqiang21 https://reactjs.org/docs/react-dom.html#browser-support

**Comment by zhiqiang21** [comment]
thanks .
