### ISSUE TITLE
Listeners "leak" and increasing nodes after unmountComponentAtNode

### ISSUE THREAD

**Issue by RaedsLab** [facebook/react#11852]
**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**

When I render a very simple React app using ```ReactDOM.render``` then ```ReactDOM.unmountComponentAtNode``` several times I get the following chart with what looks like an increasing number of listeners and nodes in my application.

![react_empty](https://user-images.githubusercontent.com/1442690/33984474-0883ef16-e0b8-11e7-95ff-13ff169b3ec0.PNG)

Here is a fiddle of what I'm doing : https://jsfiddle.net/ugy84ap0/

**What is the expected behavior?**

I think after ```unmountComponentAtNode``` my graph should be flat ?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm using latest create-react-app  / "react": "16.2.0"

**Comment by gaearon** [comment]
Are you testing with the production version?

**Comment by RaedsLab** [comment]
@gaearon  Thank you for the quick response. 

The first screenshot is using DEV version. The fiddle is using the provided template.

I tried with ``yarn build`` and now it looks much smoother. Thank you.
![react_build](https://user-images.githubusercontent.com/1442690/33988375-7f8f4234-e0c4-11e7-8624-1ca2d363aa46.PNG)

Do you know what is causing this ?

**Comment by gaearon** [comment]
I don't think it's a leak even in DEV. If you wait for GC it should get collected.

**Comment by RaedsLab** [comment]
You're right it just takes longer.
