### ISSUE TITLE
ReactTestUtils.Simulate.click does not work with jsdom

### ISSUE THREAD

**Issue by yanns** [facebook/react#1185]
When testing a react application on Nodejs with mocha and jsdom, ReactTestUtils.Simulate.click does not affect the component.

Sample app to reproduce the problem:
https://github.com/yanns/react-unit-test/tree/pb-with-jsdom

The test:
https://github.com/yanns/react-unit-test/blob/pb-with-jsdom/src/test/mocha/LabelTest.js

**Comment by danawoodman** [comment]
I take it from this thread that it is currently impossible to simulate events on sub-components in react using `refs`? I'm able to get this to work with a top level component but as soon as I want to do it on a nested component I get the same error @yanns has

eg, this fails:

```js
<Foo><Bar onClick={this.doSomething} /></Foo>
```

but this works:

```js
<Bar onClick={this.doSomething} />
```

**Comment by snackycracky** [comment]
@danawoodman in `<Foo><Bar refs='bar' onClick={this.doSomething} /></Foo> ` you wrote refs, but it should be ref.
