### ISSUE TITLE
Bug in scryRenderedComponentsWithType

### ISSUE THREAD

**Issue by pronebird** [facebook/react#11855]
`scryRenderedComponentsWithType` spits the following:

> findAllInRenderedTree(...): instance must be a composite component

test case:

```
class Accordion extends React.Component {
  render() {
    return (<div>{ this.props.children }</div>);
  }
}
const tree = ReactTestUtils.renderIntoDocument(
      <div>
        <Accordion height={ 0 }>
          <div>Hello</div>
        </Accordion>
      </div>
);

const elements = ReactTestUtils.scryRenderedComponentsWithType(tree, Accordion);
expect(elements[0].clientHeight).to.be.equal(0);
```

**Comment by gaearon** [comment]
This doesn't tell us much (what is `Accordion`?)

Please provide a full reproducing projcet.

**Comment by pronebird** [comment]
`Accordion` is any kind of component that inherits from `React.Component`.

**Comment by gaearon** [comment]
I think `scryRenderedComponentsWithType()` accepts a *component instance* as first argument, not a div.

I agree the API is confusing there. In practice most people are using Enzyme (https://airbnb.io/enzyme/) these days so I don't think we'll invest much work into fixing this. I encourage you to try Enzyme.

**Comment by gaearon** [comment]
I made the error message clearer in https://github.com/facebook/react/pull/13351.
Thanks for reporting.
