### ISSUE TITLE
Not able to build a basic file

### ISSUE THREAD

**Issue by shardy315** [facebook/react#11856]
Hi All,

The error I get is : 

> Invariant Violation: Element type is invalid: expected a string (for built-in components) but got : object. You likely forgot to export your component from the file it's defined in.
> 
> The error is located at : 
> in RCTView (at View.js:112)
> in View (at AppContainer.js:102)
> in RCTView (at View.js:112)
> in View (at AppContainer.js:122)
> in AppContainer (at renderApplication.js: 34)
> 

https://image.ibb.co/b8EK4m/Screen_Shot_2017_12_14_at_16_27_33.png

My App.js is like this. Not sure what I am doing wrong here. Would be grateful for any pointers. Thank you :)

```
import React from 'react';
import { AppRegistry, View, Text } from 'react-native';

class App extends React.Component {
  render(){
    return (
      <View>
        <Text> Sierra </Text>
        <Text> Tanner </Text>
      </View>
    )
  }
}

AppRegistry.registerComponent('SampleApp', () => App);

```

**Comment by gaearon** [comment]
Can you please upload a sample project demonstrating this? It's not obvious which versions of which packages you're using etc.

I would also suggest filing this in https://github.com/facebook/react-native instead. We don't provide support for RN in this repository.

**Comment by shardy315** [comment]
Thank you @gaearon . Should I delete this thread and open a new one in the above link ?

**Comment by gaearon** [comment]
That would probably be best. But if you don't receive a response please feel free to ping me here and I'll try to help. In any case I'll need a reproducing project to look into it.

**Comment by shardy315** [comment]
Thank you.
