### ISSUE TITLE
window.opera = null problem

### ISSUE THREAD

**Issue by alisherdavronov** [facebook/react#11853]
I want to report a bug.

When there is a var named opera with value null in window before loading react then react app crashes.

Steps to reproduce:
1) Create a new app using create-react-app my-app
2) cd my-app && yarn start
3) Add one line (<script>window.opera=null</script>) just before closing body tag into file public/index.html
4) The app crashes here.

Couldn't reproduce on jsfiddle.net. I think because problem appears if we execute window.opera=null BEFORE loading react.

Expected behavior is to not crash.

React v16.2.0 and Google Chrome Version 63.0.3239.84 (Official Build) (64-bit). 
Have no info about problematic behavior with previous versions of React.

**Comment by aweary** [comment]
Closed by https://github.com/facebook/react/pull/11854/files
