### ISSUE TITLE
React doesn't re-render DOM after manual DOM tree and key prop changes

### ISSUE THREAD

**Issue by finom** [facebook/react#11863]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

In the real world I used https://github.com/RubaXa/Sortable to sort array items. When I d'n'd an item I send a new sorting state to a server. It's OK when the server responds  with the same data I've sent but if the server rejects sorting and sends me the data I had in the beginning, array items don't sort back.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

I have simulated d'n'd sorting programmatically by flipping DOM nodes via DOM interface.

https://jsfiddle.net/Luktwrdm/60/

- DOM is rendered using given state (A, B).
- I flip DOM nodes in 2 seconds (B, A).
- And set a new state which is the same as it was on the first step (B, A).

`key={id}` or `key={id + index}` don't help there. 
 
**What is the expected behavior?**

It should sort nodes back (A, B).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16. The issue also appears in React 15 https://jsfiddle.net/hmbg7e9w/1/

**Comment by gaearon** [comment]
React does not support other code messing with the DOM nodes that it manages. Checking for all possible things that external code can do would kill the performance.

There are some exceptions to this rule: some operations are intentionally safe. They are described in more details here: https://reactjs.org/docs/integrating-with-other-libraries.html. The general guideline is that if you want to change something in DOM managed by React, make sure React never has any reason to try to update that node either. I know it's a bit fuzzy, but a good example is adding an extra attribute (which React doesn't know about), or changing DOM children of a node that React considers a leaf. Those are safe.

Reordering items via DOM manipulation and then telling React to re-render is neither safe nor supported.
