### ISSUE TITLE
Improve accidental `void` return in render props?

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#11866]
We know that it is easy to accidentally forget to return from functions or arrow functions. That's why we don't allow returning `undefined` from render functions. (I think we do in the children position but that's harder to disallow.)

```js
class Foo extends React.Component {
  render() {
    return this.props.children();
  }
}
```

```js
function Bar() {
  return <Foo>
    {value => {
      <div>
       ...
      </div>
    }}
  </Foo>;
}
```

or

```js
function BarImpl(props, value) {
  <div>
  </div>
}
function Bar(props) {
  return <Foo>{value => BarImpl(props, value)}</Foo>;
}
```

It can be difficult to detect an undefined return but the error/warning will also come from the implementation of `Foo`.

I wonder if we can improve that somehow.

**Comment by M-ZubairAhmed** [comment]
@sebmarkbage can i try looking into this?

**Comment by gaearon** [comment]
What's a render prop?
