### ISSUE TITLE
Move to .js.org

### ISSUE THREAD

**Issue by sergeysova** [facebook/react#11874]
Maybe move docs to https://react.js.org?

**Comment by seriouslyfluffy** [comment]
why?

**Comment by sergeysova** [comment]
to be consistent with other js lib (redux.js.org)

**Comment by jbbn** [comment]
It makes sense.

**Comment by seriouslyfluffy** [comment]
but may to confuse people in the future

**Comment by sergeysova** [comment]
@seriouslyfluffy why?

**Comment by sergeysova** [comment]
facebook.github.io/react already have redirect to reactjs.org

**Comment by blling** [comment]
Really a good idea :)

**Comment by seriouslyfluffy** [comment]
oh, I've forgot about redirect)

**Comment by gaearon** [comment]
Thanks, we’re happy with our top-level domain and I don’t really see us moving to a different one.
