### ISSUE TITLE
Inconsistent calling of setState's callback

### ISSUE THREAD

**Issue by nick-thompson** [facebook/react#1187]
When passing a callback to `setState`, such as...

``` js
this.setState({react: 'lulz'}, function() {
  console.log('react updated my state, yay');
});
```

... it's unclear whether or not that callback will be called synchronously or asynchronously. Specifically, it seems to be that the callback is executed synchronously after React decides to effect your state changes, but it's unclear whether or not React will effect your state changes asynchronously or synchronously, which makes it hard to reason about how the callback will be called. It seems to me that, for consistency, even when React effects your state changes synchronously, the callback should be shoved off into the event loop to be called asynchronously for the sake of a consistent API.

Example 1: http://jsfiddle.net/DN44g/2/
This case shows an example where the callback passed to setState gets called synchronously, because the state change is effected synchronously (look in the console; the numbers only start getting logged after you've clicked "ok" on the alert box).

Example 2: http://jsfiddle.net/kb3gN/1385/
This case shows an example where the callback is executed asynchronously, because the state change is effected asynchronously; see the comments in the fiddle.

**Comment by gaearon** [comment]
I’ll close this as stale.

There is an argument that consistency is important, but there is also an argument that you might want to have the callback fired as early as possible after the changes are flushed. Sometimes browsers (I’m looking at you iOS Safari) prevent you from doing certain actions if you do them too late.

So I don’t think we’ll be changing this. If you have new thoughts about this and would like to revive the discussion, please file a new issue.
