### ISSUE TITLE
onClick doesn't fire on components that change position

### ISSUE THREAD

**Issue by hannujaakkola** [facebook/react#11878]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a list of components that change their height based on their internal state (open/close) and close after the user clicks outside that component (so only one is open at a time). It's possible to toggle other component's onClicks that are above the currently open component but not the ones below it. It seems that onClick doesn't fire on the components that are in different position than initially rendered.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
https://codesandbox.io/s/6z6nov18zw

**What is the expected behavior?**
That both components above and below the component open when clicked.

Expected behavior can be achieved by using addEventListener.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16, tested on Firefox/Chrome/Safari

**Comment by jquense** [comment]
I'm not sure this is bug, The outside mousedown is moving everything around before the item click happens, the item you mousedown on isn't the up that is mouseup'd on and so the click event doesn't fire. I could definitely be wrong but my hunch is that the same thing would happen if you implemented this behavior natively as well

**Comment by hannujaakkola** [comment]
You are correct, it hides on mousedown and click happens only on mouseup. If the event listener is on mouseup everything works correctly. Thanks for helping, I feel stupid now lol.
