### ISSUE TITLE
Do we still need to check for Opera in BeforeInputPlugin?

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11886]
This came up in https://github.com/facebook/react/pull/11854. We have a specific browser check for Opera, but Opera has used Blink for a _while_. 

Is a version of Opera that uses Presto still in our browser support matrix? Could we remove this check?

We don't have an "official" (as official as it can be) guideline for Opera in https://github.com/facebook/react/issues/9301#issuecomment-334274439. 

@sophiebits Any thoughts here? How far back does Facebook go on Opera?

**Comment by skiritsis** [comment]
I could remove the checks for Presto and verify that it works as expected with the latest Opera version(or is there a list of supported versions?). Considering Opera 12(which included the 'TextEvent' in window) was released in 2012 I believe it is safe to remove it.

**Comment by sophiebits** [comment]
Fine to remove as long as you can verify it doesn't affect Opera Mini. I don't anticipate bugs in current Opera that don't also exist in current Chrome so let's make a decision on those as a one-off if they ever come up.

**Comment by nhunzaker** [comment]
Closed by https://github.com/facebook/react/pull/11921
