### ISSUE TITLE
Cannot render Quora embedded links in React

### ISSUE THREAD

**Issue by aphorism44** [facebook/react#11891]
The site Quora offers an easy way to embed links. For instance, it offers a quick code snippet, which works on a normal HTML page:

`<span class='quora-content-embed' data-name='What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do/answer/Haily-Cramer'>Read <a class='quora-content-link' data-width='559' data-height='250' href='https://www.quora.com/What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do/answer/Haily-Cramer' data-type='answer' data-id='66746225' data-key='9f6fd6718e65d80bd24be9822bc1546c' load-full-answer='False' data-embed='oigvzao'><a href='https://www.quora.com/Haily-Cramer'>Haily Cramer</a>&#039;s <a href='/What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do#ans66746225'>answer</a> to <a href='/What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do' ref='canonical'><span class="rendered_qtext">What’s the most morally disgusting thing you’ve ever seen someone do?</span></a></a> on <a href='https://www.quora.com'>Quora</a><script type="text/javascript" src="https://www.quora.com/widgets/content"></script></span>`

Which normally renders like this:

![image](https://user-images.githubusercontent.com/6020859/34184996-980588c8-e4e8-11e7-8757-56890f28e63a.png)

However, if you place the same code in a render function, like so:
`class BlogPanel extends Component {
  render() {
    return (
      <span class='quora-content-embed' data-name='What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do/answer/Haily-Cramer'>Read <a class='quora-content-link' data-width='559' data-height='250' href='https://www.quora.com/What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do/answer/Haily-Cramer' data-type='answer' data-id='66746225' data-key='9f6fd6718e65d80bd24be9822bc1546c' load-full-answer='False' data-embed='oigvzao'><a href='https://www.quora.com/Haily-Cramer'>Haily Cramer</a>&#039;s <a href='/What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do#ans66746225'>answer</a> to <a href='/What’s-the-most-morally-disgusting-thing-you’ve-ever-seen-someone-do' ref='canonical'><span class="rendered_qtext">What’s the most morally disgusting thing you’ve ever seen someone do?</span></a></a> on <a href='https://www.quora.com'>Quora</a><script type="text/javascript" src="https://www.quora.com/widgets/content"></script></span>
    );
  }
}`

It looks like this:
![image](https://user-images.githubusercontent.com/6020859/34185060-f0a848da-e4e8-11e7-8666-d8a43f0416f0.png)

Is there a general way to fix this? I'm seeing this problem with practically every embedded functionality I've ever used, from Google Maps to social media. I had to install a special library to handle Google Maps, but this is happening to every single embed functionality out there,

**Comment by gaearon** [comment]
JSX is not HTML.
Please read this: https://reactjs.org/docs/dom-elements.html

Moreover this script probably mutates the DOM so you can’t use React for it anyway.

I would suggest using `dangerouslySetInnerHTML` and putting all the static markup there. Just be careful to not include any user content into it as that can produce a security hole.

**Comment by gaearon** [comment]
In particular I mean:

```js
<div dangerouslySetInnerHTML={{
  __html: `
(Put your html here)
`}} />
```

But again, be careful the HTML is always trusted and not dynamic.

**Comment by aphorism44** [comment]
I'm afraid that leads to the same problem.

Plugging in those embedded tags from existing and well-known social media sites is a very good feature, and simply dismissing it only tells me to use a different framework.

**Comment by gaearon** [comment]
I wouldn't say React has a problem with popularity.

There are good technical reasons why we don't allow DOM mutation: React can't keep track of which DOM nodes need to be updated and when if DOM changes under its nose.

Again, the escape hatch above should be sufficient for the cases where you really need it.
