### ISSUE TITLE
reconciler's tryToClaimNextHydratableInstance next-nextInstance heuristic creating duplicative elements

### ISSUE THREAD

**Issue by chandlerprall** [facebook/react#11897]
**Do you want to request a *feature* or report a *bug*?**
bug (though the React code is working as intended)

**What is the current behavior?**
When hydrating from server-rendered DOM, if [react-reconciler encounters an unexpected node](https://github.com/facebook/react/blob/v16.2.0/packages/react-reconciler/src/ReactFiberHydrationContext.js#L229) it will peek ahead to the next DOM node and test if it is the expected node. If so, react-reconciler will delete the unexpected node and continue on by using the second node to hydrate. If the second node does not match the instance then the reconciler gives up and begins inserting DOM nodes without trying to reconcile.

In our case, we are server-side rendering the entire #document server-side and re-hydrating at that level. Some 3rd party analytics scripts are injected at the top of <body> before the hydrate call happens, causing the entire application to be injected into the body instead of reconciled with the existing nodes.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
I can force this to happen in our app by injecting two (or more) empty `script` tags at the top of <body>. I've not been able to reproduce via jsfiddle; unsure what the exact combination of flags are to force this specific code path.

```
document.body.insertBefore(document.createElement('script'), document.body.children[0]);
document.body.insertBefore(document.createElement('script'), document.body.children[0]);
```

**What is the expected behavior?**
Ideally the reconciler would look at all of the sibling nodes to find the matching element.

A comment in the code at the relevant location says
```
// If we can't hydrate this instance let's try the next one.
// We use this as a heuristic. It's based on intuition and not data so it
// might be flawed or unnecessary.
```

I hacked together a change to prove out inspecting all sibling elements and that seems to be working with no unintended consequences. I modified

`nextInstance = getNextHydratableSibling(nextInstance);`
to be
`while (nextInstance = getNextHydratableSibling(nextInstance), nextInstance && !canHydrate(fiber, nextInstance)) {};`

So nextInstance will either be the hydratable sibling or it will be null.

Using `performance.now()` on my Mac Book Pro, I do not observe this O(1) -> O(n) change to be measurable in my situation.

```
with matching DOM: 118-144ms
with mismatched DOM: 116-172ms
mismatchedDOM & updated function: 116-163ms
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This was introduced with React 16s new hydration approach. (I'll take this over the Invariant 42 full-stop error; thanks for building the new approach!).

**Comment by gaearon** [comment]
Can you insert those scripts after hydration? Or can you render them on the server too?

**Comment by chandlerprall** [comment]
These scripts are from 3rd parties, injected by the Google Tag Manager script (that one is SSRed). Because the initial GTM script is part of the SSR DOM there's a race condition between the script injection and our application's startup.

Small addendum: this is also affecting our elements in <head> (we update HEAD via React as page navigation happens). Some 3rd party scripts inject into the top of head (what ever happened to best practices) which causes the same issue: duplicated title, meta, link, etc elements (most frustrating is the duplication of CSS <link>s as that loads and applies the stylesheet twice.

As a work around, right before calling `hydrate` I remove & re-append all 3rd-party elements that are direct children of head and body to the bottom of those nodes.

**Comment by gaearon** [comment]
With these constraints, would it not be easier to only hydrate an element inside the body, and use a regular template for the parts outside?

**Comment by chandlerprall** [comment]
:) I'm very aware we are relying on an edge case that isn't well supported (mostly due to browser differences and this case of 3rd party scripts) and causes the React team headaches. It's on our roadmap to move the application into a single container in body and figure out something different for updating head, but difficult to justify the time to modify our systems to change something that "already works". Of course it no longer "already works", but we have a band-aid on top to support it.

I think there are reasons to support a different fallback method than what the reconciler currently does (and the comment in that block of code could be read as agreeing). However, I definitely understand If this is too much of an edge case to consider supporting in full.

**Comment by gaearon** [comment]
>As a work around, right before calling hydrate I remove & re-append all 3rd-party elements that are direct children of head and body to the bottom of those nodes.

Sounds like you have a workaround.

I'm hesitant to go with your specific proposal because I don't feel like I fully understand its pros and cons. However, if you do feel strongly that it's the right solution, please file a new issue or a PR with a more detailed description of how the heuristic should work instead, and what are the best and worst cases before and after. I don't think we can change the behavior without more comprehensive analysis.
