### ISSUE TITLE
Why do you write this

### ISSUE THREAD

**Issue by enyyongyang** [facebook/react#11892]
react/packages/react/src/ReactCurrentOwner.js:23
  current: (null: null | Fiber)  
  react/packages/react/src/ReactDebugCurrentFrame.js:14
  ReactDebugCurrentFrame.getCurrentStack = (null: null | (() => string | null));

  use flow .   null?

**Comment by jquense** [comment]
? Sorry what?

**Comment by enyyongyang** [comment]
I don't understand why these two lines of code write this. What is the meaning

**Comment by jquense** [comment]
Those are setting values to null while casting it to a specific type.

In general the issuer tracker isn't the place the ask general questions about the code base, but reserved for bug reports or Features. Thanks!

**Comment by gaearon** [comment]
I think it is appropriate to ask questions about the codebase if one is looking to contribute. :-)
But that's better done in specific issues you're working on.

**Comment by jquense** [comment]
yes, sorry if that come of dismissive, i wrote it on my phone!
