### ISSUE TITLE
fb.me CDN links redirecting to Facebook's home page

### ISSUE THREAD

**Issue by zachberry** [facebook/react#11890]
It seems the fb.me CDN links have been changed. The links on this page - https://reactjs.org/blog/2016/04/07/react-v15.html#installation (such as https://fb.me/react-15.0.0.js ) - seem to simply redirect to facebook.com. Previously these were loading the react library. Noticed this because our app suddenly started giving us this error:

```
Refused to execute script from 'https://www.facebook.com/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by gaearon** [comment]
Sorry about this. Not sure what's happening but we'll find out.

For now, I'd just suggest using unpkg, for example:

https://unpkg.com/react-dom@15.0.0/dist/react-dom.js (development)
https://unpkg.com/react-dom@15.0.0/dist/react-dom.min.js (production)

**Comment by sophiebits** [comment]
Should be fixed now, sorry for the trouble.
