### ISSUE TITLE
Caret position for onChange event in iOS Safari is incorrect

### ISSUE THREAD

**Issue by ztanner** [facebook/react#11903]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
![ezgif-4-2e3028f85a](https://user-images.githubusercontent.com/1939140/34268406-6da97d16-e635-11e7-8d30-9ff0c67d6d27.gif)

A simple controlled input with an onChange event that also renders the output in a span has consistently reproducible caret positioning problems.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
https://codesandbox.io/s/k5yqlynqk5

I've included an example where the setState is wrapped in rAF, which fixes the issue but causes a different problem in desktop safari. 

**What is the expected behavior?**
Caret position should consistently correspond with where the internal cursor position actually is

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested and reproducible in React 16.2.0, 16.0.0, and 15.6.2, in iOS simulator (iOS 11.x) and actual device. 

**Edit: On further investigation, it seems like this might be an issue with Safari itself, or the underlying rendering engine...I can close this if it's a no-op for the React team.

**Comment by aweary** [comment]
> **Edit: On further investigation, it seems like this might be an issue with Safari itself, or the underlying rendering engine...I can close this if it's a no-op for the React team.

Can you expand on what you found?

**Comment by ztanner** [comment]
> Can you expand on what you found?

Yeah, sorry for the vagueness. A simple pure JS example is here using just the `input` event: https://codesandbox.io/s/q7olwz5p0q
