### ISSUE TITLE
renderToStaticMarkup escapes '&' to '&amp;'

### ISSUE THREAD

**Issue by kouhin** [facebook/react#11907]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
const alt = 'こんにちは&;';
const src = 'https://example.com/img?id=12345&width=10&height=10';
const staticMarkup = renderToStaticMarkup(
  <img
    alt={alt}
    data-src={src}
    height="10"
    src={src}
    width="10"
  />,
);
console.info(staticMarkup);
```

Output:

```
<img alt="こんにちは&amp;;" data-src="https://example.com/img?id=12345&amp;width=10&amp;height=10" height="10" src="https://example.com/img?id=12345&amp;width=10&amp;height=10" width="10"/>
```

Here ,`&` is encoded to `&amp;`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

React 16: https://jsfiddle.net/hy0042to/

**What is the expected behavior?**

Output:

```
<img alt="こんにちは&;" data-src="https://example.com/img?id=12345&width=10&height=10" height="10" src="https://example.com/img?id=12345&width=10&height=10" width="10"/>
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.2.0

**Comment by syranide** [comment]
That is correct behavior. Attributes values are HTML-decoded by the browser and not escaping is a security issue.

**Comment by Asgator** [comment]
What about SEO? SEO specialists said for it not good
