### ISSUE TITLE
Proposal to destructure prop-types on import statement as a standard

### ISSUE THREAD

**Issue by yasuf** [facebook/react#11906]
I'd  like to propose the following when importing `prop-types` to components

Instead of doing i.e.
```javascript
import PropTypes from 'prop-types'

class MyComponent extends Component {
  static propTypes = {
    fetchData: PropTypes.func
  }
}
```
We could be more concise using destructuring
```javascript
import { func } from 'prop-types'

class MyComponent extends Component {
  static propTypes = {
    fetchData: func
  }
}
```

Small improvement that makes it easier to see the type of each prop on a component at a glance.

Is there any reason this hasn't been chosen as the standard? Please give your opinion and reasoning on this.

**Comment by Kovensky** [comment]
The main reason is that `prop-types` is written and published as a commonjs module (`module.exports = ...`).

It is not yet certain whether you will be able to do a named import from a commonjs module with real, native modules -- it is overwhelmingly likely that you cannot; but it is already guaranteed that you will be able to import a commonjs module as a default export.

One common point of confusion is that `import { foo } from 'bar'` is not, at all, the same as `const { foo } = require('bar')`, even if this happens to work when things are transpiled.

**Comment by gaearon** [comment]
The above sounds right.

We can revisit this after Node supports ESM, but for now either choice is broken in some way. I think ideally we'd switch to named exports there eventually. 

Either way, the right place to file this would be https://github.com/facebook/prop-types.
