### ISSUE TITLE
Accessing TestInstance.state for react-test-renderer package

### ISSUE THREAD

**Issue by nanomosfet** [facebook/react#11909]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The behavior that is listed in [the docs](https://reactjs.org/docs/test-renderer.html)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**
Change the state of your test object as such shown below:
```javascript
testInstance.state.on = true
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
It would affect all browsers.

**Comment by gaearon** [comment]
`testInstance.instance.setState({on: true})`
