### ISSUE TITLE
html tag <a> property download can't work on firefox

### ISSUE THREAD

**Issue by nicewahson** [facebook/react#11908]
[here](https://jsfiddle.net/crazyMax/kus3kxm4/) is my jsfiddle
OS: windows 7
browser: Firefox Quantum 57.0

i want to use property download to download image but this can't work, but it can work on chrome

**Comment by ngyikp** [comment]
Not a React issue, reproducible on plain HTML as well: https://jsfiddle.net/mg4bb7gy/

Firefox does not allow download attribute for cross-origin links, see https://stackoverflow.com/a/24781946

**Comment by nicewahson** [comment]
thanks..
