### ISSUE TITLE
props read only?

### ISSUE THREAD

**Issue by david-jam** [facebook/react#11913]
React docs say props are read only but how come [mobx ](https://mobx.js.org/getting-started.html) directly modifies them e.g. as in 
```
onRename = () => {
    const todo = this.props.todo;
    todo.task = prompt('Task name', todo.task) || todo.task;
  }

```

**Comment by gaearon** [comment]
The *props object* is readonly.
You can't do

```js
this.props.todo = someOtherTodo;
```

or

```js
this.props.name = 'Hello';
```

Mobx lets you modify individual objects passed in props. This is different, and is currently supported although it’s very hard to do right manually so you should avoid it unless you’re using a well-maintained library like Mobx.
