### ISSUE TITLE
QQ Browers is not show

### ISSUE THREAD

**Issue by 438198602** [facebook/react#11910]
I have a webapp with creat-react-app，it not work on QQ Browers, but it is ok in other browers.

"react": "^16.2.0",
"react-dom": "^16.2.0",

who can help me, please....

**Comment by gaearon** [comment]
I don’t know what runtime environment is provided by QQ browser. Most likely you need to add some polyfills.

Check React requirements here: https://reactjs.org/docs/javascript-environment-requirements.html

React also assumes the browser supports ES5 so you might need ES5 shim if QQ browser doesn’t have full support. Hope this helps!
