### ISSUE TITLE
React ART crashes with SSR

### ISSUE THREAD

**Issue by necolas** [facebook/react#11916]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

React ART crashes when components are rendered with Node.

**What is the expected behavior?**

No crash.

The issue lies upstream in the art fork, and there is a proposed fix, but the PR needs attention so I'm cross posting here. Hope that's ok

https://github.com/sebmarkbage/art/pull/16

**Comment by MoOx** [comment]
The PR has been merged upstream \o/

**Comment by MoOx** [comment]
0.10.2 as just been published https://www.npmjs.com/package/art

**Comment by MoOx** [comment]
I guess semver will do its work and we can probably close this issue as `"art": "^0.10.1"`(used in the package.json) should pick the latest.

**Comment by necolas** [comment]
Great! Thank you
