### ISSUE TITLE
How to auto refresh in another taps in react js?

### ISSUE THREAD

**Issue by Sathiyamm** [facebook/react#11925]
I'm open the login page in two tabs in the same browser the login click after another tab also refresh or reload. How to do that in react js? Does anyone help this?

**Comment by aweary** [comment]
Hey @Sathiyamm, we try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).

In this case, there's nothing React specific about sending messages between tabs. I recommend referring to StackOverflow or other general resources. [Communication between tabs or windows
](https://stackoverflow.com/questions/28230845/communication-between-tabs-or-windows) might be useful for you.

Thanks!
