### ISSUE TITLE
Point production build at un-minified file?

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/react#11928]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When `NODE_ENV === 'production'`, [react](https://github.com/facebook/react/blob/master/packages/react/npm/index.js#L4) and [react-dom](https://github.com/facebook/react/blob/master/packages/react-dom/npm/index.js#L35) both point to their respective _minified_ production builds.

In the context of being included in a larger bundle, this is undesirable because minifying an entire bundle at once produces (slightly) smaller output than when its constituent pieces have already been minified.

**What is the expected behavior?**

I understand the desire to keep React "small by default" and clearly gate the dev/prod builds, but would you consider pointing at an un-minified production build instead?

Sorry if this has been discussed elsewhere. I couldn't find any issues.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This was introduced when the NODE_ENV check was simplified to point at separate builds.

**Comment by gaearon** [comment]
>In the context of being included in a larger bundle, this is undesirable because minifying an entire bundle at once produces (slightly) smaller output than when its constituent pieces have already been minified.

Can you explain why? I’m not sure I’m following. Technically your bundler will make another renaming pass anyway so I don’t see why it matters.

**Comment by gaearon** [comment]
I'll close because it's not clear to me what this would accomplish, and there was no reply. Happy to continue the discussion!
