### ISSUE TITLE
FeatReq: render method could receive currentState and currentProps as arguments

### ISSUE THREAD

**Issue by eddyw** [facebook/react#11923]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The `render` method doesn't receive `currentState` and `currentProps`.

**What is the expected behavior?**
The `render` method when called would receive `currentState` and `currentProps` as arguments. For instance:
```javascript
render(currentState, currentProps) {
  return ...
}
```
This could allow destructure the arguments to get only the needed properties, for example.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.2 (It doesn't work in any React version)

**Comment by koba04** [comment]
@eddyw Here is a proposal for this. 
* https://github.com/reactjs/rfcs/pull/4

**Comment by eddyw** [comment]
Oh, cool.
I have used the search box not to duplicate but I haven't found that one.

**Comment by aweary** [comment]
There was https://github.com/facebook/react/issues/1387, but it's a little hard to find via search :)

Please direct any feedback to the RFC. Thanks!
