### ISSUE TITLE
issue with create-react-app

### ISSUE THREAD

**Issue by guru9** [facebook/react#11933]
os: windows 8, 64 bit

C:\Users\Bharat Moger\react>node -v
v8.9.3

C:\Users\Bharat Moger\react>npm -v
5.6.0

C:\Users\Bharat Moger\react>create-react-app --version
1.4.3

*---------issue with create-react-app my-app-----------*

C:\Users\Bharat Moger\react>create-react-app my-apps

Creating a new React app in C:\Users\Bharat Moger\react\my-apps.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

npm ERR! Unexpected end of JSON input while parsing near '...lugin-flowtype","dist'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bharat Moger\AppData\Roaming\npm-cache\_logs\2017-12-30T08_14_40_408Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

Deleting generated file... package.json
Deleting my-apps / from C:\Users\Bharat Moger\react
Done.

*---------issue with create-react-app my-app-----------(same issue with this command on npm 5.2.0+*

C:\Users\Bharat Moger\react>npx create-react-app my-app1
Error: EPERM: operation not permitted, mkdir 'C:\Users\Bharat'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:214:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:252:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:178:20)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:47:53
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
Install for prefix@latest failed with code 7
C:\Users\Bharat Moger\AppData\Roaming\npm\node_modules\create-react-app\index.js

Creating a new React app in C:\Users\Bharat Moger\react\my-app1.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

npm ERR! Unexpected end of JSON input while parsing near '...lugin-flowtype","dist'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bharat Moger\AppData\Roaming\npm-cache\_logs\2017-12-30T08_16_05_475Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

Deleting generated file... package.json
Deleting my-app1 / from C:\Users\Bharat Moger\react
Done.

*----------unsolved-----------------*

**Comment by guru9** [comment]
Means can't start reactjs!!

**Comment by ryota-murakami** [comment]
@guru9 

It's looks like create-react-app probrem,
so you would be better create issue to the [create-react-app issues](https://github.com/facebookincubator/create-react-app/issues/new).

**Comment by guru9** [comment]
but I know somebody were using create-react-app and works properly.
how to overcome by this....may this is an os issue? or how to solve this. bcoz I need to start react app!

**Comment by guru9** [comment]
*------no bro - still  same issue going on------------*

C:\Users\Bharat Moger\react>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\Bharat Moger\react>create-react-app my-app

Creating a new React app in C:\Users\Bharat Moger\react\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/jest-environment-node failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bharat Moger\AppData\Roaming\npm-cache\_logs\2017-12-30T09_58_01_811Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

Deleting generated file... package.json
Deleting my-app / from C:\Users\Bharat Moger\react
Done.

**Comment by guru9** [comment]
*---when it will be resolved------*

C:\Users\Bharat Moger\react>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\Bharat Moger\react>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\Bharat Moger\react>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\Bharat Moger\react>create-react-app my-appdg

Creating a new React app in C:\Users\Bharat Moger\react\my-appdg.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

npm ERR! code EINTEGRITY
npm ERR! sha1-YRrhrPFPXoH3KVB0coGf6XM1WKk= integrity checksum failed when using sha1: wanted sha1-YRrhrPFPXoH3KVB0coGf6XM1WKk= but got sha1-5ZF4Gff8QPoC/V4B6CQp+ItZ1LA

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bharat Moger\AppData\Roaming\npm-cache\_logs\2017-12-30T10_47_01_115Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting my-appdg / from C:\Users\Bharat Moger\react
Done.

**Comment by ryota-murakami** [comment]
@guru9 
> may I need to install yarn??

yeah, try switch to `yarn`.

**Comment by guru9** [comment]
*---yep! seems solved by yarn. thanks  [ryota-murakami](https://github.com/ryota-murakami)   --meet u again-----*

*-----instructions---*

npm install -g yarn

yarn global add create-react-app

create-react-app my-app

*------solved----*

**Comment by arikkfir** [comment]
Just for reference, in case this helps someone - I got this working for me by adding `sudo`, as such:
```
sudo npx create-react-app my-app
```

Note that this might be because my Node.js installation's file-system owner is indeed `root` rather than  my own user - perhaps this is the root cause for this issue?

@guru9 is this the same with your environment?

**Comment by gaearon** [comment]
If you're calling npm commands with sudo you're only going to get more issues in the future.

Instead, you need to uninstall Node and reinstall it making sure *not* to install it with sudo.
