### ISSUE TITLE
react-native-custom-tabs not return response

### ISSUE THREAD

**Issue by ranjeetsingh12** [facebook/react#11947]
I have created button to open CustonTabs to use external url into React-native app. external url have some forms that are submitted and return array as a response into another page i.e success page. I want to get response from success page into app and CustomTabs would be close automatically. code for custom tab:-

```
url = 'https://www.example.com/newtest.php';
CustomTabs.openURL(url,{ toolbarColor: '#607D8B',enableUrlBarHiding: true,showPageTitle: true,enableDefaultShare: true,animations: ANIMATIONS_SLIDE}).then((launched: boolean) => {                                             
console.log(`Launched custom tabs: ${launched}`);
}).catch(err => {
console.error(err)
}); 
```

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests for React itself.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
