### ISSUE TITLE
Facebook Engineers - Thank You For 2017

### ISSUE THREAD

**Issue by gabegreenberg** [facebook/react#11940]
To all the Facebook Engineers working on [open source](https://code.facebook.com/projects/),

Like [last year](https://github.com/facebook/react/issues/8663#issue-198212596), we at [Reactiflux](http://www.reactiflux.com/) just wanted to take a moment to thank you for all your hard work in 2017. It’s been another big year! After much anticipation React 16 was [released](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html) in September, React Native has moved from v0.41 to v0.51 fixing countless bugs and adding new features, Jest has over 20 releases this year, Yarn 1.0 and Relay Modern were released, new engineers have joined (hey @calebmer, @TheSavior, @axemclion) and some have moved on (we’ll miss you @mkonicek), and that is just a tiny snapshot of 2017.

Talking with some of you, I know that the dealing with the [licensing issues](https://code.facebook.com/posts/112130496157735/explaining-react-s-license/) this year was incredibly difficult and frustrating yet you all handled the situation in such a mature and humble manner all while continuing to iterate and innovate. Thank you! We are so happy that you can continue focusing on the work at hand, especially now that this chapter is finally [closed](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/). 

Guillermo Rauch recently [tweeted](https://twitter.com/rauchg/status/944281445316550657), “As 2017 wraps up I believe more than ever that React is such a good idea that we will spend the rest of the decade continuing to explore its implications and applications.” We echo this sentiment and as 2017 wraps up, we also believe more than ever that you all embody the spirit of open source with such humility, servant leadership, and true focus on community driven progress that it continues to astound us. We thank you that these qualities are at the heart of our community. We thank you for all the time you have taken to join AMA’s and answer our questions on Twitter. For all the time you have taken to respond to issues and merge PR’s. Thank you for going above and beyond, again this year… as always. 

We’d like to invite the React community to reply to this thread with your own “thank you” comments to the team at Facebook. Let’s show them how grateful we are! Feel free to include experiences with the team or just how the React ecosystem has helped you as a developer.

Sincerely,

On behalf of the Reactiflux community:
@gabegreenberg
@markerikson
@KyleAMathews
@taion
@jquense
@vcarl
@benigeri
@Phoenixmatrix
@BTMPL
@kyleshevlin
@slightlytyler 
@totaldis

**Comment by arthurdenner** [comment]
Thank you! Not only the React team, but to all the open-source contributors. 🎉💓

**Comment by kingdaro** [comment]
Thanks a bunch. Keep being awesome, everyone.

**Comment by NoiSek** [comment]
Thanks to all of your hard work out there, fellows, you make my life a hell of a lot easier. 👍

**Comment by JoeBanks13** [comment]
Thank you! React was one of the first JavaScript frameworks I looked at! It was incredibly helpful and let me learn. Stay cool :)

**Comment by Nufflee** [comment]
Thank you!! Keep up the good job! 🎉💓🎉💓

**Comment by ckknight** [comment]
Thank you all. You've fostered a community I'm happy to be a part of. Keep it up!

**Comment by Izitable** [comment]
Thank you very much for all your work

**Comment by filipenevola** [comment]
Keep up :)

**Comment by wilsonrivera** [comment]
Thank you for the hard work! Keep it up!

**Comment by tducasse** [comment]
Thank you :)

**Comment by VictorJozwicki** [comment]
Thank you and keep it up !
As an IT student in France, learning something else than PHP was great ! And it allowed me to grow a little bit more as a dev. I even have my own ideas on what to make with it !

**Comment by pfreema1** [comment]
🎉 🎉 🎉

**Comment by cem2ran** [comment]
Thank you! You have changed the way I view UI programming and Open Source <3

**Comment by ermik** [comment]
I am starting a company in part because of Facebook's hard work in Open Source. Thank you!

**Comment by slice** [comment]
```js
const ThankYou = () => <div>Thanks a lot, React team! <Emoji name="heart"/></div>
new IssueDOM(11940).render(<ThankYou/>);
```

**Comment by mrscobbler** [comment]
Thank you for all you do!

**Comment by speedDeveloper** [comment]
Thank you very much! React has provided me the ability to built the best webapps on the web! Keep going!

**Comment by asgvard** [comment]
Thank you for everything you’ve done, keep it up :D

**Comment by hueyjj** [comment]
Thank you! React has been a great success!

**Comment by gujral1997** [comment]
Thanks a lot , it's been such a great honour to use react native!

**Comment by ifeanyidavid** [comment]
Thank you for all the effort you've put in to make React awesome!

**Comment by thangngoc89** [comment]
Thank you for all of your works.

**Comment by Kureev** [comment]
Thank you 🙏

**Comment by matiasmagni** [comment]
Thank you very much!

**Comment by wesleycho** [comment]
I appreciate the investment FB and its engineers have made in React and the ecosystem. Thank you all who have contributed/maintained projects in the ecosystem! I understand from first hand prior experience that open source can be very difficult/stressful/time consuming, and so I have a deep appreciation for those who have maintained the passion for what they do and keep on the effort.

**Comment by cristhiandas** [comment]
Thank you guys, I'm new on react but I can tell you that it helps me a lot building new stuff :)

**Comment by aweary** [comment]
❤️ The React repo and documentation has seen so many great improvements in 2017. A huge thanks to the team at Facebook and everyone else who has contributed this year, it's been fun! Here's to even more great work in 2018 :clinking_glasses:

**Comment by quicksnap** [comment]
<3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3

**Comment by CamelSpit** [comment]
Thank you so much! I hope you all have a great new year!

**Comment by gregorskii** [comment]
Thank you! 😎

**Comment by antoligy** [comment]
Thank-you!

**Comment by housseindjirdeh** [comment]
A lot of us would probably not even have our jobs if it wasn't for the amazing open source projects built by amazing developers like yourselves. 

To the Facebook team, thank you ❤️

**Comment by jMoulis** [comment]
U changed my life guys!!! Thank you so much

**Comment by klequis** [comment]
Love React
Thank you!
Happy New Year

**Comment by ifeanyidavid** [comment]
import React from 'react';
import ReactDOM from 'react-dom';

const thankYouMessage = ['Thank', 'you', 'for', 'all', 'the', 'effort', 'you', 'have', 'put', 'into', 'making', 'React', 'awesome'];
thankYouMessage.map(message => <Message text={message} />);

const Message = (message) => {
<div>
<p>{message}</p>
</div>
}

ReactDOM.render(<Message />, document.getElementById('root'));

**Comment by ifeanyidavid** [comment]
`import React from 'react';
import ReactDOM from 'react-dom';

const thankYouMessage = ['Thank', 'you', 'for', 'all', 'the', 'effort', 'you', 'have', 'put', 'into', 'making', 'React', 'awesome'];
thankYouMessage.map(message => );

const Message = (message) => {

{message}
}

ReactDOM.render(, document.getElementById('root'));`

**Comment by kdichev** [comment]
Thank you :*

**Comment by Hum4n01d** [comment]
Thank you!

**Comment by jagretz** [comment]
I've used many frameworks & libraries in the past. I really appreciate the thought and design put into react! I love using this tool and find it great for teaching good JavaScript design skills.

**Comment by atrauzzi** [comment]
Thank you!

**Comment by john-d-pelingo** [comment]
Thank you for making the web development world a better place!

**Comment by dejanr** [comment]
Thank you! For making web/native development such a joy!

**Comment by nhunzaker** [comment]
Amazing work! I can't wait to see what 2018 has in store for React!

**Comment by miguelcjalmeida** [comment]
Thank you all for putting so much love and efforts in this wonderful library which React is! I wish you all a great new year!

**Comment by MrLoh** [comment]
🙏

**Comment by LodeKennes** [comment]
Thanks to the team for making web and mobile development a lot more fun! <3

**Comment by konekoya** [comment]
Big thank to the React team and devs who have contributed to it! 💯

**Comment by ConnorBryan** [comment]
Thanks for creating (what I perceive as) the best front-end solution for adaptive view management!

Stay frosty!

**Comment by zyzski** [comment]
thanks for a great year of development with react! onward and upward 🙂

**Comment by vicapow** [comment]
Thank you! 🙏

**Comment by stefcharle** [comment]
Thank you very much guys. Very appreciative of people who dedicate their time to open source. Much success in the new year!

**Comment by blling** [comment]
Thanks guys, thanks Dan!

**Comment by lucianolucianoluciano** [comment]
Thank you guys! Your work is impressive

**Comment by Gh05d** [comment]
Thx for supporting the community.

**Comment by pmonty** [comment]
Thank you team! Been using React for well over a year now constantly ever day at work and now landed a job dedicated to React apps. Looks forward to further development!

**Comment by coreyflynn** [comment]
Thanks folks!  Keep up the great work!

**Comment by Essential** [comment]
Thank you 🐒❤️

**Comment by danmcatee** [comment]
Thank you keep the Great work Up ❤️

**Comment by Anveio** [comment]
Thanks for the impeccable 16.0.0 release and the decision to re-license React under MIT. I use React, React-DOM, Immutable.js, and Jest on a daily basis and they make my open-source work possible. 💟

**Comment by awojtczyk** [comment]
Tank you guys! <3

**Comment by jorisvddonk** [comment]
Thanks for all your work! Looking forward to the future of React!

**Comment by coding-saints** [comment]
Thank you to all the maintainers and contributors that make this possible!

**Comment by madhums** [comment]
Thank you to all open source contributors! 🙏 ❤️

**Comment by nathaniadis** [comment]
Thank you!

**Comment by gtodd876** [comment]
Thank you so much for all the hard work to make our web development experience so enjoyable!

**Comment by quentin-sommer** [comment]
Keep up the good work!

**Comment by CSMarco** [comment]
Thank you guys! Keep it up :)

**Comment by fokusferit** [comment]
Thank you! And keep the great work!

**Comment by retrixe** [comment]
React is extremely amazing, and with its abundant ecosystem, it is a breeze to develop with React. Yarn with its lock files ensure the same packages throughout the board, but while npm 5 wants to bring that to npm, yarn is so fast that I never think of using npm. I sincerely thank the developers at Facebook for maintaining these libraries and appreciate their efforts. Keep up the good work!

**Comment by p1xelHer0** [comment]
👏 ❤️ 🎉 ⚛️ 🃏

**Comment by magician11** [comment]
The React framework has been key in keeping me really excited about being a front end developer. So thank you for helping make my development days so pleasant 😊

**Comment by jamonholmgren** [comment]
Thank you from the team at Infinite Red! A large chunk of the software we built this year was enabled by your work, and we are grateful. ❤️

**Comment by excalliburbd** [comment]
Thank you so much!

**Comment by gbozee** [comment]
Thanks for making me love frontend development.

**Comment by josenaves** [comment]
Thanks for awesome code !

**Comment by EthanC** [comment]
Thank you to everybody at the React Team! ❤️

**Comment by viankakrisna** [comment]
Thank you!

**Comment by popo63301** [comment]
Thank you guys for making programming so accessible. 6 months ago I couldn't make anything. Now I can build web apps, android apps, iOS apps, desktop apps thanks to React. Love from Paris 🇫🇷 !!!!!!

**Comment by hisapy** [comment]
Gracias totales desde Paraguay 🍻 🍾 🎆

**Comment by alecperkey** [comment]
GraphQL, Flow, React Native are all great stuff!

**Comment by madiodio** [comment]
Thanks to everyone at FB Open Source, ❤ from Senegal!

**Comment by sachinjha1** [comment]
Thank you! React has changed my life :)

**Comment by JMontagu** [comment]
Thank you from London!

**Comment by hzbrz** [comment]
Thanks to you and your awesome work this year guys felizz navidad and a happy new year from the boddom of my hearth

**Comment by BoilingOil** [comment]
Thank You So Much!

**Comment by aTaQu** [comment]
Thank you guys, your work is amazing thank you for making developing a fun thing instead of a boring
 chore❤

**Comment by peterpme** [comment]
Thank you! <3 <3 <3 <3

**Comment by Daniel15** [comment]
Thank you to all the open source teams at Facebook! Not just the large projects (React, Jest, Yarn, Buck) but also the smaller projects that don't get quite as much recognition :)

**Comment by timmfin** [comment]
Thanks to all!

**Comment by markus-willems** [comment]
Thank you and happy new year everyone! Much health and good code!

**Comment by gaearon** [comment]
Thanks :-). This is very sweet.

**Comment by PeterPanen** [comment]
Thanks to everyone involved! Makes my every day life so much better :)

**Comment by ahylton19** [comment]
Thank you 🤗❤️

**Comment by goto1** [comment]
Thank you. I've been using React for some time now and I am enjoying it! Your hard work is very much appreciated.

**Comment by Tetheta** [comment]
Yes many thanks! I use so many of Facebook's excellent tools and frameworks every day and it's made my development experience immeasurably more enjoyable. Keep on doing what you're doing!

**Comment by khanh2003** [comment]
Thank you, you made web development fun again. I used jQuery in the past and it was a nightmare to synchronize the UI with my app's internal state. With React and Redux, the UI is automatically synchronized with the state, so my code is less cluttered with "synchronization code". Before using React, I had all my code in a single JS file. When I was introduced to React, I learned to split my code into smart components, dumb components, actions, reducers and vendor files, it made my code easier to search because I can hit Ctrl + P and jump to the part I need to work on. I sincerely appreciate all the work you did to make web development enjoyable and easy for human brains.

**Comment by emretekince** [comment]
Thank you!!

**Comment by NiksonX** [comment]
I thank all of you! 🕛🎈🙌🎊🎇

**Comment by jimmybaker** [comment]
Thank you!

**Comment by FacundoGFlores** [comment]
Thank you very much! It's a pleasure to work with this environment!

**Comment by MmtBkn** [comment]
Thanks for making them happen!

**Comment by dudeinthemirror** [comment]
you guys did the unthinkable: made me convert from an iOS native die-hard into a platform agnostic, react-native evangelist. To everybody behind react, react-native, flow, jest: kudos, thank you and keep up the good work in 2018 and beyond!

**Comment by TigleyM** [comment]
Thank you!

**Comment by EmaSuriano** [comment]
Thank you and happy new year! 🎉

**Comment by Rud156** [comment]
React was one of the first JavaScript Frameworks I looked at but I didn't get it at that time. But now when I understand it properly. I've fallen in love with it. So a huge Thank You. Also a Happy New Year

**Comment by brentertz** [comment]
Thank you!!

**Comment by tharakawj** [comment]
Thank you and happy new year to all! ❤️ 
I learned a lot from this amazing community!

**Comment by sdarmaputra** [comment]
Thank you to all of your hard works. You guys inspired me a lot.  Keep being awesome! :clap: :tada:

**Comment by sompylasar** [comment]
Thank you for all the hard work! Happy New Year, more Open Source to come! 🎆🎇🎉

**Comment by jandrell-formoso** [comment]
Thank you! You're all an inspiration. Happy New Year! 🎉 🎉 🎆

**Comment by byronanderson** [comment]
Thank you so much for everything you do! ❤️❤️❤️❤️

**Comment by email2vimalraj** [comment]
Thank you everyone who made the React and made open source. One of my resolution of this year is to atleast raise one PR in react and merged.

**Comment by gattigaga** [comment]
Thanks for Facebook to make React ecosystem open source... 👏👏👏

Thanks for contributors to make React ecosystem better... 💪💪💪

**Comment by monkindey** [comment]
Thank you!  Learn a lot from you.

**Comment by SKarajic** [comment]
Thank you guys for making one of the most intuitive and gamechanging libraries since jQuery. Massive respect for all the work you guys do and have it be Open Source for the community. It is mindboggling how much it has advanced webdevelopment as a whole. Sure angular might have been the first around and Vue might be simpler in some cases, but in my opinion React really hits the sweetspot for the amount of complexity combined with it's functionality. I've been using the library for over a year and I honestly think it has been one of the most amazing things in webdevelopment in a long long time. I am happy to be around to see one of the most amazing libraries change the way how the front-end industry works. You guys are some straightup game changers which have accomplished incredible things for the industry and community. Instead of keeping it private and only in use for facebook you guys decided to make it open source and help the advancement of technology as a whole. I want to thank you guys again for this amazing library you guys have brought to us. Please keep the good work up and i wish you all an amazing new year!

**Comment by MurshidMac** [comment]
Thanks a lot  @gabegreenberg  for the awesome work @reactjs . Wish you the same :)

**Comment by sandiprb** [comment]
Thank you Team React!

**Comment by itsmebins** [comment]
Thank you Facebook ReactTeam! For making web/native development such a joy! ❤️❤❤❤👌👍

**Comment by buoyantair** [comment]
Thank you React Team!

**Comment by broerjuang** [comment]
Thank you React Team! 🎉😍 love your awesomeness!

**Comment by ThisIzKp** [comment]
Thank you react team :-)

**Comment by senthilbalajiganesan** [comment]
Thank you react team!! coming years will great for all!!

**Comment by lulato** [comment]
Muchas Gracias!

**Comment by quincycs** [comment]
Thank you for providing a platform that is so productive that it’s fun.  Made my job 1000% better every day for years

**Comment by kbuechner** [comment]
Thank you so much! Your hard work is very appreciated. Looking forward to what 2018 brings!

**Comment by michaelgichia** [comment]
Thank you everyone on @react team.

**Comment by Zephir77167** [comment]
Thank you a lot for your hard work!

**Comment by blackxored** [comment]
Thank you!!!

**Comment by lrn2prgrm** [comment]
Thank's guys you are awesome =)

**Comment by tataton** [comment]
Thanks for an amazing 2017, and here's to an incredible 2018 to come!

**Comment by M-ZubairAhmed** [comment]
Thank you Facebook

**Comment by prometheansacrifice** [comment]
I'm really grateful for Prepack. Partial evaluation, Symbolic Execution, Abstract Interpretation: These advanced concepts can only be learnt in theory. Seeing them in action in a an open source project has made these program specialisation techniques accessible to everyone: specially those without formal education. Thank you very much for it.

Ofcourse, thank you for React and it new direction too. New ideas, though conflicting sometimes, is making everyone rethink about Javascript and Web frontend. We're are on our toes constantly correcting ourselves all thanks to the open source work Facebook has done with React and related projects. Golden days I would say.

**Comment by kapilgorve** [comment]
🙏🙏🙏

**Comment by sdelrio0** [comment]
Thank you! 🙏

**Comment by jk-gan** [comment]
Thank you React Team! 😃 I really love what you guys doing. Your hard work is very much appreciated.

**Comment by meetzaveri** [comment]
Thank You React team and Facebook Open-Source team for making React Ecosystem.

**Comment by shirazz** [comment]
Thanks to all the open source developers out there 👍

**Comment by antonybudianto** [comment]
Thank you React team! 👍

**Comment by kaloudiyi** [comment]
Thank you guys for such great tools. I wish you the best for this new year :-)

**Comment by cdimitroulas** [comment]
Thank you so much!

**Comment by khalid283** [comment]
Thank You React Team and all the open-source contributors. 🎉

**Comment by nguyenmanh1507** [comment]
Thank you!!!!

**Comment by ndelangen** [comment]
A huge thanks from the entire [Storybook team](https://github.com/orgs/storybooks/people) for the awesome software and the support 👏 🙇 🙏 👍

**Comment by AhmedAbdulrahman** [comment]
I want to thank this great team for making Amazing work! Keep the great work up  
:heart_eyes: :heart_eyes:

**Comment by anil26** [comment]
Thank you React team for making learning so easy !!

**Comment by infu** [comment]
Thanks, you rock, react is awesome!

**Comment by energydrink9** [comment]
Thank you! You rock!

**Comment by AAGSICON** [comment]
Thank you

**Comment by therealchiko** [comment]
Thank you!

**Comment by santhosh77h** [comment]
Thank you for making development easier and effective....to all the contributors have a great years ahead.

**Comment by superherointj** [comment]
Thanks for all the hard work!

**Comment by fidellr** [comment]
Thanks a lot for making this framework to help our development easier and we're from Indonesia very grateful for your (react team and all contributors) hard works!

**Comment by sbaudray** [comment]
Thanks for your awesome work !

**Comment by pandaiolo** [comment]
Thank you guys for open sourcing all the tools that makes my everyday job more more pleasant (and efficient) !

**Comment by preco21** [comment]
Thank you all react guys! Keep up the awesome work :heart: :sparkles: :fire: :tada: :metal: !

**Comment by eharango** [comment]
Thanks for everything guys! happy new year from Perú!

**Comment by xeno** [comment]
Thanks everyone!

**Comment by landvibe** [comment]
Thank you!
React changed my career and I love it.

**Comment by gaurav-pantelwar** [comment]
Thanks for Everything you guys do such hard work for us.

**Comment by rodrigopivi** [comment]
w00t w00t, thank you all!

**Comment by AlexandreCarlos** [comment]
Thank you! 👍

**Comment by sapetti** [comment]
Thanks!!

**Comment by codyspate** [comment]
Thanks for working hard!!!

**Comment by Negan1911** [comment]
Thanks a lot, i really enjoy working with this technologies every day and can't see working without them

**Comment by leomoreno** [comment]
Really a great and very inspiring work folks, keep it coming 👏👏👏👏

**Comment by PhilipDavis** [comment]
Thanks for everything!

**Comment by aqumus** [comment]
Thanks to each one of you 👍

**Comment by checkmatez** [comment]
Thank you!

**Comment by ryota-murakami** [comment]
Thank you:smile:

**Comment by t-adedotun** [comment]
Thanks for the far-reaching good work!

**Comment by shergin** [comment]
❤️

**Comment by lannify** [comment]
Thank you for making development a lot more fun! Keep up the awesome work!!

**Comment by iamclaytonray** [comment]
Thank you to everyone from Facebook and every contributor, across all of Facebook's OSS!

**Comment by cbfranca** [comment]
Thank you!!!

**Comment by jonathaningram** [comment]
Onya team!

**Comment by jeremy-donson** [comment]
MANY Thanks! 👍

**Comment by du5rte** [comment]
Thank you 🙏

**Comment by cr0cK** [comment]
Spending 8h per day on React since 3 years, still enjoying it. Thanks you and looking forward future evolutions ! 🙏

**Comment by spadin** [comment]
Thank you!

**Comment by flppv** [comment]
Thanks!

**Comment by lucasterra** [comment]
Thank you for all your hard work on React! ❤️

**Comment by devisscher** [comment]
Thank you!

**Comment by adcar** [comment]
Thanks for being open source!

**Comment by jonmajorc** [comment]
Thank you all for all the work! 🔥❤️😃

**Comment by SureshUnnikrishnanFL** [comment]
Thank you for the fantastic open source frameworks👏👏 and all the hard work to keep it that way ❤️😃👍

**Comment by jishaal** [comment]
Thanks a lot team! 🙏💯

**Comment by petercr** [comment]
Thanks Team Facebook for all the hard work that you've put into React 😻 🥇 You have a great way of tying THML/CSS/JS together in a beautiful looking and functioning system :shipit: 💯

**Comment by abbiecat** [comment]
Thanks team! Happy New Year 😄

**Comment by tororudy** [comment]
Thanks a lot facebook team!

**Comment by inlightmedia** [comment]
You guys are an inspiration, thank you!

**Comment by aLIEzsss4** [comment]
hello world!

**Comment by kaynz** [comment]
Thank you very much for all your work!

**Comment by MitulIslam** [comment]
Thank you very much for all your work!

**Comment by rockieroshan** [comment]
Happy new year!! lets rock again!!

**Comment by xuanheScript** [comment]
Thank you! 👍

**Comment by Miralo** [comment]
Thank you for your amazing work! :-)

**Comment by nellochen** [comment]
Thank you for the hard work! Keep it up!

**Comment by gzhappysky** [comment]
Thanks guys, thanks Dan!

**Comment by Kiwka** [comment]
thanks for all work that was done to make such cool products - not only React, but also Jest and Immutable available for everyone

**Comment by opr** [comment]
Thanks facebook team, you've made something amazing <3

**Comment by dimooze** [comment]
Thaaaaaaaanks !!!

**Comment by safaorhan** [comment]
Thank you for contributing to the open source universe. Your hardwork is appreciated all over the globe 🤗

**Comment by blling** [comment]
How long is the Christmas holiday?

**Comment by gaearon** [comment]
Some of us are back today so I think we can close this.
Thanks again, and hoping we won’t disappoint you this year either!

**Comment by blling** [comment]
Nice to see you Dan, miss all of you a lot :)

**Comment by rockieroshan** [comment]
i am learning React and redux since a while.
i would like to contribute and learn more things.
is there any way to do that?
sorry if this sounds dumb..

**Comment by nicastelo** [comment]
Thank you for all your effort and hard work guys! You all are amazing.
Happy new year!

**Comment by mihir478** [comment]
Thank you! Happy 2018!

**Comment by bzhr** [comment]
Thank you for your great work! Happy 2018!

**Comment by DavidCurtis321** [comment]
Get Outlook for iOS
	_____________________________

**Comment by jcmnunes** [comment]
Thank you 🙇‍♂️

**Comment by haderman** [comment]
thanks!!!!

**Comment by dusi** [comment]
🇨🇿 Děkuji 🇨🇿

**Comment by thetrompf** [comment]
Thank you guys!

**Comment by narek11** [comment]
Thanks for your hard work.

**Comment by karthikiyengar** [comment]
Thank you so much.

+1 for this feature 😋

**Comment by ryanbelke** [comment]
Great work!!

**Comment by artburkart** [comment]
:+1:

**Comment by lcoder** [comment]
Thank you!I love React,Great work.

**Comment by watadarkstar** [comment]
Thank you to the best open source community!

**Comment by ihtml5** [comment]
Thank you! React is great!

**Comment by nhducit** [comment]
thank you!

**Comment by grabbou** [comment]
Thanks to Facebook engineers working hard within the open source. Met many great people this year and looking forward working with you again next year!

**Comment by mehrdaad** [comment]
I humbly thank and appreciate all of you engineers on Facebook.  
SO many great projects wouldn't be possible without your endless efforts!
Thank you

**Comment by xfcdxg** [comment]
💪

**Comment by felipesabino** [comment]
Thanks! 👏

**Comment by shubsengupta** [comment]
Thank you for being awesome! Cheers to a better internet :) ❤️

**Comment by styfle** [comment]
![Thank You](https://media1.tenor.com/images/9dac8192b4b475477730e2e00bbcabef/tenor.gif)

**Comment by samarpanda** [comment]
Thanks a lot!

**Comment by walea3** [comment]
A massive thank you for your time, energy & passion ... 🌟

**Comment by vladiiancu** [comment]
Cheers to all! Thank you and have a great 2018.

**Comment by abilash13** [comment]
Thanks for making what React what it is today! We all owe you guys one :P

**Comment by fipo** [comment]
Respect guys! Thank you for the hard work, energy and passion. Wish you an awesome 2018!

**Comment by rakeshmenon** [comment]
A BIG "**### Thank You**" to the entire team @ Facebook...

@gaearon @acdlite @sophiebits @bvaughn @sebmarkbage @tomocchino 

...for their tireless efforts towards making React the most loved library!! 🥇 💯

**Comment by amangeot** [comment]
Thank you!

**Comment by jpsierens** [comment]
Thanks to the Open Source team at Facebook, keep up the great work! Front End changed so much with React in a good way.

**Comment by Hillsie** [comment]
Thank you for your contribution to the community. We all stand on the shoulders of many giants.

**Comment by AndreiCalazans** [comment]
You guys are amazing, thanks to this project many people's life have changed.

**Comment by suark** [comment]
Thank you!

**Comment by kanalasumant** [comment]
Thanks a ton for this wonderful library. Highly appreciate it!

**Comment by leodsgn** [comment]
Thank you all for the hard work. Really appreciate it React and it's community. ❤️

**Comment by SkylarPhx** [comment]
Thank you for your astonishing work! :)

**Comment by j13l** [comment]
Thanks a ton for everyone who's pushing React to be such an awesome tool. ❤️ 
Very happy user here!

**Comment by towfiqi** [comment]
Thank you for making React MIT! :)

**Comment by AlexEscalante** [comment]
These last two years have been all about React, and more is coming! So… thanks a lot!! 😛 ❤️

**Comment by cdleon** [comment]
Thank you for making React and keeping it MIT, it completely changed the way I work on frontend, loving it!!

**Comment by onggunhao** [comment]
Thank you so much!

**Comment by sarbull** [comment]
Thank you for creating react and making it MIT. cc: @jordwalke

**Comment by zhangchao828** [comment]
谢谢react团队，让我的工作效率大大提高

**Comment by Pau1fitz** [comment]
thanks!

**Comment by jevakallio** [comment]
Thank you! You have improved my life and the lives of everyone on my team.

**Comment by AlejandroRV** [comment]
Thank you a lot to the team that create React and the people who is involved in the project.
 :mexico:  🎉🎉🎉🎉🎉🎉🎉🎉🎉 :mexico:

**Comment by JasonShin** [comment]
![thankyou](https://user-images.githubusercontent.com/2525002/36188209-b34597da-119e-11e8-84c8-67f066076917.gif)

**Comment by Juanjofp** [comment]
Thank you! <3 <3 <3

**Comment by danibram** [comment]
Thanks!

**Comment by reciosonny** [comment]
Thanks you for making react!

**Comment by wallysson-hotmart** [comment]
Thank you all of you guys that making this happen!
Please, keep this amazing things going as you guys been doing incredible awesome!!!

**Comment by leonbec** [comment]
Thank you so much

**Comment by bliang** [comment]
Thank you!

**Comment by CasperEngl** [comment]
Thank you! 😃❤️

**Comment by kpunith8** [comment]
Thank you React Community

**Comment by volokolamskspb** [comment]
Thank you FB engineers! I would help you with pleasure to work on your open source project any time!

**Comment by gaearon** [comment]
Hey all, thanks for kind words. I’ll lock the thread since many are subscribed and get emails from it.
