### ISSUE TITLE
How to get response from CustomTabs in react-native

### ISSUE THREAD

**Issue by ranjeetsingh12** [facebook/react#11945]
I have created button to open CustonTabs to use external url into React-native app. external url have some forms that are submitted and return array as a response into another page i.e success page. I want  to get response from success page into app and  CustomTabs would be close automatically.  code for custom tab:-

```
url = 'https://www.example.com/newtest.php';
CustomTabs.openURL(url,{ toolbarColor: '#607D8B',enableUrlBarHiding: true,showPageTitle: true,enableDefaultShare: true,animations: ANIMATIONS_SLIDE}).then((launched: boolean) => {                                             
console.log(`Launched custom tabs: ${launched}`);
}).catch(err => {
console.error(err)
}); 
```

how can i get response from CustomTabs into my app  and close CustomTabs will be closed in react-native app ?

**Comment by gaearon** [comment]
Please see https://github.com/facebook/react/issues/11947#issuecomment-354762610.
