### ISSUE TITLE
Output JUnit XML test metadata for CircleCI

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#11949]
# @benbraou has claimed this issue. Please give them a chance to work on this.

---

Here's a screenshot of a CircleCI build for another (private) project I'm a part of:

![image](https://user-images.githubusercontent.com/6820/34494194-1d3d3f70-efa4-11e7-87b7-0ca9961b2934.png)

It clearly highlights the parts of the build that failed.

In contrast, see one of our builds: https://circleci.com/gh/facebook/react/8402. In this one the ./scripts/circleci/upload_build.sh step failed but you need to scroll through the output a significant amount to see that. This is in part because we have a custom entry point for all our CI steps ([scripts/circleci/test_entry_point.sh](https://github.com/facebook/react/blob/v16.2.0/scripts/circleci/test_entry_point.sh)) to make it easier for us to parallelize some build steps.

I'd like us to change that test_entry_point.sh script to output JUnit XML metadata for CircleCI as described in https://circleci.com/docs/2.0/collect-test-data/. Then I believe the CircleCI build results page will show exactly which step failed.

(Bonus: If we can show individual Jest tests that would be even cooler. But I think the most important part is breaking out jest vs flow vs prettier, etc. into separate chunks.)

**Comment by benbraou** [comment]
I would like to work on this issue!

**Comment by sophiebits** [comment]
@benbraou, it's yours!

**Comment by benbraou** [comment]
I am working on this issue this weekend

**Comment by benbraou** [comment]
# Overview of changes
I will be updating this comment as subtasks of this issue get implemented.

## Subtasks

- [x] Handle Jest JUnit reports generation
- b88d010
- jest-junit reporter is used to output JUnit report reports in /junit/jest-results.xml
- An example of CircleCI Build insight based on the generated JUnit report can be found [here](https://circleci.com/gh/benbraou/react/41)
- test_entry_point.sh is calling `yarn test` several times. So, a unit test failure will be duplicated in the build summary
- [ ] Handle ESLint JUnit reports generation

**Comment by benbraou** [comment]
@sophiebits I would like to check with you my proposal for Flow JUnit report generation before I start the implementation.

Flow only supports JSON output.
So what I propose when flow script is run is:
1. In normal dev mode, the normal output is logged in console
1. In case of circleci build, flow is run with `--json` option. The json output is provided to a transformer (that I will implement) that will generate the JUnit output.

That transformer could also be used to generate reports based on the return of the other build scripts ( upload_build.sh, test_print_warnings ...)

What do you think ?

**Comment by sophiebits** [comment]
I think for flow it is fine to treat it as a single "test" that has a single output and just use the formatted output. Not sure if there is much advantage to try to split flow into multiple "tests".

**Comment by benbraou** [comment]
I see. Thank you!

**Comment by benbraou** [comment]
A pull request has been submitted #12023 
# Summary
Currently, when the build fails, there is no way to know what happened other than going through the logs in CircleCI. 

The goal of this PR is to output JUnit XML metadata for every build step. This allows CircleCI summary page to display exactly which step has failed. 

# What this PR does:
1.  Handle Jest JUnit reports generation
   **jest-junit** reporter is used to output JUnit report reports in /junit/jest-results.xml
   :warning: `test_entry_point.sh` is calling `yarn test` several times. So, a unit test failure will be duplicated in the build summary
1. Handle ESLint JUnit reports generation
 **ESLint** script can either use the default `stylish` formatter or `junit` formatter.
 :warning: in JUnit mode, ESlint results are in XML format. Not only are they written to report fils, but also they are logged to console. This may be a noise to the build logs.

:warning:  For the tasks described below, the package `junit-report-builder` has been used. Initially, I was writing the JUnit report on my own.
1. Handle flow JUnit reports generation
  **Flow** result is treated as a single test that has a single test output
1. Handle prettier JUnit  reports generation
1. Handle check_license.sh JUnit  report generation
1. Handle check_modules.sh JUnit  report generation
1. test_print_warnings.sh
  **Nothing** to be done as this script is simply used to extract all messages from `warning()
1. Handle track_stats JUnit.sh  report generation
1. Handle build.sh JUnit.sh  report generation
1. Handle upload_build.sh JUnit  report generation
1. Handle JUnit report generation for coveralls
1. Handle JUnit report generation for Danger

**Comment by pree-T** [comment]
May I work on it? Can someone help me?

**Comment by MananTaneja** [comment]
@bvaughn is it okay if I pick this up? Just starting out (first open source issue)

**Comment by koyuncuoglum95** [comment]
Hello @sophiebits , I'm here first time. Can I work on this ?

**Comment by Ank61** [comment]
Hello @sophiebits! Can I work on this?

**Comment by simi360** [comment]
Hi @sophiebits please let me know if the issue still exists? I would like to get working

**Comment by kassens** [comment]
We're moving off of CircleCI, so this no longer applies. Maybe there's something similar on GitHub Actions that would make sense, I don't know.
