### ISSUE TITLE
Curly braces are pointless and ugly

### ISSUE THREAD

**Issue by ogwh** [facebook/react#11944]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Curly braces are required to delimit Javascript expressions in JSX attributes.

<MyComponent foo={bar(1, 2, 3)} />

**What is the desired behavior?**
All Javascript expressions can be expressed without the need for {}.

<MyComponent foo=bar(1, 2, 3) baz="quirk" life=42 pi=3.1415 sum=(x + y) fancy=`` `Hello ${name}` `` onClick=()=>{ this.andThat() } />

In short, requiring {} around all of these is unnecessary although the last one is a bit ugly with the =()=> thing.

**Comment by gaearon** [comment]
This is not a React issue, but a JSX one. Let’s keep track of it in the right repository.

https://github.com/facebook/jsx/issues/25
https://github.com/facebook/jsx/issues/51
https://github.com/facebook/jsx/issues/64

**Comment by ogwh** [comment]
Thanks for the pointer.
