### ISSUE TITLE
React+Webpack+Typescript: fine with react v15, but fails to resolve 'react-dom' with react v16

### ISSUE THREAD

**Issue by Eranikid** [facebook/react#11946]
tsconfig.json:
```
{
    "compilerOptions": {
         "jsx": "react",
    }
}
```
webpack.config.js
```
module.exports = {    
        entry: './app.tsx',        
        output: {
            filename: 'bundle.js'
        },
        module: {
            rules: [
                { test: /\.tsx?$/, use: 'ts-loader' }               
            ]
        }
    };
```
app.tsx:
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';

ReactDOM.render(
        <div>Hello</div>,
        document.getElementById('react-app')
    );
```
With Reqct 15:
```
"dependencies": {
  "@types/react": "15.0.35",
  "@types/react-dom": "15.5.1",
  "@types/webpack-env": "1.13.3",
  "react": "15.6.1",
  "react-dom": "15.6.1",
  "ts-loader": "3.2.0",
  "typescript": "2.6.2",
  "webpack": "3.10.0"
 }
```
Everything is fine:
```
$ webpack
Hash: a92fe528d11e00efc2c4
Version: webpack 3.10.0
Time: 2231ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  746 kB       0  [emitted]  [big]  main
  [81] ./app.tsx 206 bytes {0} [built]
    + 183 hidden modules

```
But with React 16:
```
    "@types/react": "16.0.31",
    "@types/react-dom": "16.0.3",
    "react": "16.2.0",
    "react-dom": "16.2.0"
```
It fails to resolve 'react-dom':
```
$ webpack
Hash: 9d276a350f7222e47059
Version: webpack 3.10.0
Time: 1991ms
    Asset     Size  Chunks             Chunk Names
bundle.js  70.4 kB       0  [emitted]  main
   [6] ./app.tsx 206 bytes {0} [built]
    + 11 hidden modules

ERROR in ./app.tsx
Module not found: Error: Can't resolve 'react-dom' in '/home/dmitry/Projects/fails'
 @ ./app.tsx 4:15-35
```
What is the cause for such behavior?
```
$ npm -v && node -v && cat /etc/debian_version
5.5.1
v9.3.0
9.3
```

**Comment by gaearon** [comment]
Please provide a full project reproducing this.

Unfortunately typically when people post separate files and instructions to reproduce, the issue ends up being unreproducible. So we ask that you publish a complete project on GitHub (and verify that following your instructions still reproduces it). Thanks!

**Comment by Eranikid** [comment]
```
git clone https://github.com/Eranikid/ReactReproduce
cd ReactReproduce
cd builds
npm install
node node_modules/webpack/bin/webpack.js
#OK
cd ../fails
npm install
node node_modules/webpack/bin/webpack.js
#Fails
```

**Comment by polco** [comment]
don't know if that will help but your react types are based on the previous major version
```
"@types/react": "15.0.35"` => `"@types/react": "16.0.31"
"@types/react": "15.5.1"` => `"@types/react": "16.0.3"
```

**Comment by gaearon** [comment]
It works for me:

<img width="625" alt="screen shot 2018-01-02 at 5 17 45 pm" src="https://user-images.githubusercontent.com/810438/34492733-e128ea42-efe0-11e7-9836-b647ba940465.png">

**Comment by gaearon** [comment]
Did you figure it out?

**Comment by Eranikid** [comment]
Look what I discovered:
```
~/Projects/ReactReproduce$ dir builds/node_modules/react-dom
dist	  lib	   package.json  README.md  test-utils.js
index.js  LICENSE  PATENTS	 server.js
~/Projects/ReactReproduce$ dir fails/node_modules/react-dom
package.json
```

For some strange reason, for react-dom 16, the 'node_modules/react-dom' contains just package.json. What should I try?

**Comment by gaearon** [comment]
It definitely exists:

https://unpkg.com/react-dom@16.2.0/

Most likely it's either an npm bug or you're behind a bad npm proxy.

Try updating npm or using Yarn instead.

**Comment by Eranikid** [comment]
`npm cache clean --force` helped me. Thank you for your enthusiasm to help!

**Comment by gaearon** [comment]
Awesome, cc @zkat in case that isn't normal (I've heard cleaning the cache should never be necessary as a fix in 5.x)

**Comment by zkat** [comment]
It's reasonable: there were some issues with hash picking for http caches and clearing the cache and using the latest npm after that is probably the easiest solution 😅
