### ISSUE TITLE
<button className="square" onClick={()=>props.onClick()}> works, props.onClick doesn't. 

### ISSUE THREAD

**Issue by candy901122** [facebook/react#11943]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by jquense** [comment]
Can you provide a working reproduction please, thanks

**Comment by gaearon** [comment]
It looks like `onClick={props.onClick}` works:

https://codepen.io/gaearon/pen/QvvJOv?editors=0010

Maybe you accidentally wrote `onClick={props.onClick()}`? That won't work:

<img width="907" alt="screen shot 2018-01-02 at 5 15 07 pm" src="https://user-images.githubusercontent.com/810438/34492644-815599d0-efe0-11e7-92b2-e663983307bc.png">

I'll close but if you can provide more info about what doesn't work, we'll be happy to fix! The right repository would probably be https://github.com/reactjs/reactjs.org.

**Comment by candy901122** [comment]
Thanks for looking into this.

That's right , onClick={props.onClick} works. 
My bad, that I use onClick={()=>props.onClick}, which is not work. It should be onClick={()=>props.onClick()}.

We can close this.
