### ISSUE TITLE
`react-call-return`: Expected to find a host parent.

### ISSUE THREAD

**Issue by rmhartog** [facebook/react#11955]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A specific order of unmounting and remounting `unstable_createReturn`s from `react-call-return` causes an invariant violation in `unmountHostComponents`.

**Reproduce**
The following sandbox example crashes with an invariant violation when both the `min` and `cycle` props are *odd* numbers greater than zero.

https://codesandbox.io/s/llyjz19rz7

**What is the expected behavior?**
The app does not crash and cycles the number of items in the list.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`react` and `react-dom` versions 16.1 and newer, `react-call-return` version 0.5.0

**Comment by rmhartog** [comment]
Performing the same sequence of mounts and unmounts with `react-test-renderer` causes the same error, so it appears that the bug occurs in the reconciler.

**Comment by gaearon** [comment]
Wanna try digging into where the bug is?

**Comment by gaearon** [comment]
Tagging as a good issue to get into, but it's not an easy one.

**Comment by rmhartog** [comment]
Yes, I'd love to dig into it further!

**Comment by gaearon** [comment]
Sounds good. You'll probably want to look at BeginWork, CompleteWork, and ChildFiber, and how those handle Calls and Returns. Let me know if some aspects are confusing and I can try to explain.

**Comment by rmhartog** [comment]
It seems like a minor mistake when reconciling the children, causing duplicate deletions in some cases. Opened a pull request for the changes.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/11979.

There are likely more bugs with call/return. If you can try to stress-test this feature and find them, that would be great!
