### ISSUE TITLE
is there a  Syntactic sugar

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#11953]
is there a  Syntactic sugar such as 
`<FilterableProductTable products={products} />`
to be like
`<FilterableProductTable products />`
?
tks

**Comment by jquense** [comment]
There isn't in jsx at the moment, though there was some discussion around adding it in the jsx spec repo (sorry I'm on a phone otherwise I'd link to it). In any case this is less about react and more about jsx features :)

**Comment by NE-SmallTown** [comment]
I think try to start with https://github.com/facebook/jsx/issues/65 maybe greate
