### ISSUE TITLE
is there a Syntactic sugar like this?

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#11960]
```javascript
class Board extends React.Component {
        render(t = this, p = t.props, s = t.state) {
		console.log(t === this, p === this.props, s === this.state)
		console.log(t, p, s)
        }
}
```
so that we can easy to access those Attributes
I want to know is there any problem with this?
new reacter , tks

**Comment by milesj** [comment]
This is currently not possible but is under discussion: https://github.com/reactjs/rfcs/pull/4

**Comment by zhangenming** [comment]
@milesj OK, cool, thanks.
And, is there any trap in the trick I'm writing now?

and according to https://github.com/facebook/react/issues/1387#issuecomment-41931037


```javascript
render() {
  var state = this.state;
  //same with render(t = this.state) 

  return <div onClick={() => doSideEffect(state.x)} />;
  //I do not think the cause of the problem is caused by closures

  return <div onClick={doSideEffect.bind(this, state.x)} />;
  //There is no closure now, but the problem remains

  return <div onClick={() => doSideEffect(this.state.x)} />;
  //this OK
  //So how to get the real time this.state just use state(getter?I failed)
}
```
thats i think now
I do not know if I understand the mistake
thanks

@sebmarkbage sorry for bothering

**Comment by jquense** [comment]
Hey there, we try and keep the issue tracker for bug reports and feature requests. Please check out some of support resources: https://reactjs.org/community/support.html for general questions about react thanks!
