### ISSUE TITLE
Add method to remount component

### ISSUE THREAD

**Issue by AnderssonChristian** [facebook/react#11969]
**Do you want to request a *feature* or report a *bug*?**
A feature

I imagine this might've been brought up before, but I couldn't find any discussions on this after extensive searching...

**What is the current behavior?**

Working with certain (non-react) 3rd party libraries sometimes require you to remount a dom-node, i.e dumping it and creating it from scratch. Currently, the only way seems to be to change its `key` prop, either by incrementing it or by generating some random uid. However, that feels like a "hacky" way of implementing that behavior.

I've had this issue before when working with the YouTube Player API and now with an SVG-drawer library. I wish there was a cleaner "react-way" of doing this.

**What is the expected behavior?**

It would be nice if we could do something like:

    this.forceRemount();

or perhaps better from the parent via refs?

    this.someRef.forceRemount();

which would have the same effect as changing said components `key` prop.

**Comment by gaearon** [comment]
For additions to API, please create a new RFC: https://github.com/reactjs/rfcs
Thanks!
