### ISSUE TITLE
On running yarn start or npm start for fixtures is throwing  error.

### ISSUE THREAD

**Issue by anil26** [facebook/react#11963]
![yarnerror-1](https://user-images.githubusercontent.com/5938110/34579825-a04d453c-f1b0-11e7-85d1-458e6a9001f2.jpg)

**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
on running npm start or yarn start in "react/fixtures/dom is throwing errors in terminal.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1.Go to react/fixtures/dom 
2. Run yarn start or npm start

Following errors can be seen in the terminal 
`> react-fixtures@0.1.0 prestart /home/gmadmin/Practice/react/fixtures/dom
> cp ../../build/dist/{react,react-dom}.development.js public/

cp: cannot stat '../../build/dist/{react,react-dom}.development.js': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-fixtures@0.1.0 prestart: `cp ../../build/dist/{react,react-dom}.development.js public/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-fixtures@0.1.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gmadmin/.npm/_logs/2018-01-04T18_32_47_442Z-debug.log
`
Note: I have already run npm run build in the react parent directory and i can see react.development.js and react-dom.development.js in react/build/dist/.  Running "cp ../../build/dist/{react,react-dom}.development.js public/" this command on terminal works fine. But when it fails when run through "prestart" command in package.json.
**What is the expected behavior?**
copying should happen successfully and  npm start should successfully turn up the server. 

**Which versions of React, and which browser / OS are affected by this issue? 
React "version": "16.2.0",
kernel : "4.4.0-53-generic GNU/Linux"
os info: {
   Distributor ID:	LinuxMint
   Release:	18.1
   Codename:	serena}
Did this work in previous versions of React?
Don't know
If its a bug,  let me work on it.

**Comment by gaearon** [comment]
I don't know why. Any ideas?

**Comment by M-ZubairAhmed** [comment]
can you try to split it into two i.e 
`cp ../../build/dist/react.evelopment.js public/` and similarly for react Dom and `&&` _and_ them together.

**Comment by gaearon** [comment]
That sounds good to me, wanna do it?

**Comment by M-ZubairAhmed** [comment]
sure

**Comment by M-ZubairAhmed** [comment]
@gaearon done :-)

**Comment by darol100** [comment]
This is done and merge. Shall we close this issue?

**Comment by anil26** [comment]
i think the fix will and will work fine. I thought of fixing it like this
`"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "prestart": "npm run copyreact && npm run copyreactdom",
    "copyreactdom": "cp ../../build/dist/react.development.js public/",
    "copyreact": "cp ../../build/dist/react-dom.development.js public/"
  }`
