### ISSUE TITLE
setState callback is being called even if the state hasn't been changed

### ISSUE THREAD

**Issue by AlonBe** [facebook/react#11961]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
As to React 16 [breaking changes](https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes):
> setState callbacks (second argument) now fire immediately after componentDidMount / componentDidUpdate instead of after all components have rendered.

and setState [documentation](https://reactjs.org/docs/react-component.html#setstate)
> The second parameter to setState() is an optional callback function that will be executed once setState is completed **_and_** the component is re-rendered

So I assume that if the component isn't re-rendered, the setState callback won't be called as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
```
setState(() => null, () => console.log('why did I was called?');
```

**What is the expected behavior?**
The setState callback won't be called.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.0
Didn't try on previous versions

**Comment by gaearon** [comment]
I think that's intentional behavior. The docs are not correct (or, rather, aren't detailed enough and imply the wrong thing).

**Comment by gaearon** [comment]
I'll close this but please feel free to file an issue with the docs instead: https://github.com/reactjs/reactjs.org
