### ISSUE TITLE
Add missing onAnimationStart/onAnimationEnd event handlers

### ISSUE THREAD

**Issue by tichris0** [facebook/react#1196]
React currently doesn't handle the aforementioned 2 events.  I have a patch that works for webkit only; but more work needs to be done to make it work under all browsers until they support the standard CSS tags.

**Comment by tarikihm** [comment]
Hi, would love a status update on this, any targeted fix version or date?

**Comment by gaearon** [comment]
The support for them was merged into master in https://github.com/facebook/react/pull/6005 a few days ago.
It should be included in v15 RC that’s going to be released very soon.

Stay tuned!
