### ISSUE TITLE
Do we need to listen for click on change events?

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11971]
Presently, we listen to click events to detect changes on radio buttons and checkboxes. Do we still need to do this?

https://github.com/facebook/react/blob/master/packages/react-dom/src/events/ChangeEventPlugin.js#L198-L211

It looks as though we only do this for IE8. I'm curious about:

- [ ] Can we remove the click dependency from change events?
- [ ] If not, we should update the comments to better document why we include click events

**Comment by nhunzaker** [comment]
@jquense do you think this qualifies as a good first issue? For someone interested in picking this up, they would have to:

1. Remove the click event
2. Verify correctness in all browsers using the DOM test fixtures
3. Possibly remove some click event related code in ChangeEventPlugin

**Comment by jquense** [comment]
Our past selves are way a head of us :P https://github.com/facebook/react/pull/10830

**Comment by nhunzaker** [comment]
Dang, haha. Fair enough. I'll take another look at that PR.

**Comment by aweary** [comment]
I'm ashamed to admit how many times I've searched the repo only to find that I've tried to solve the same problem before 😆

**Comment by vinay72** [comment]
Yes you need to listen for click on change Events.
