### ISSUE TITLE
warning on stateless functional high order component.

### ISSUE THREAD

**Issue by benmonro** [facebook/react#11976]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
warning on Stateless Functional High Order Component.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://stackoverflow.com/questions/48120644/react-16-warning-from-stateless-functional-high-order-component
**What is the expected behavior?**
no warning.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.2.0.  Yes it worked in previous versions.

**Comment by gaearon** [comment]
Please provide a *complete* example that reproduces the issue.
So far what you wrote there is not enough.

**Comment by benmonro** [comment]
yeah I tried reproducing this in a codepen and using create-react-app but was unable to do so.  Was hoping for some more insight.

**Comment by gaearon** [comment]
Judging by the warning it somehow gets a `render` method attached.
So you probably have some code (maybe a bad HOC) that does something like

```js
function badHOC(fn) {
  fn.prototype.render = // ...
}
```

**Comment by benmonro** [comment]
Turns out it was because we had a roll our own react Redbox lingering around that was causing the problem.  Removed that and we're good now.
