### ISSUE TITLE
Drawer in react/material-ui

### ISSUE THREAD

**Issue by Heitor01** [facebook/react#11978]
I am a beginner in react, and I am having problems applying the drawer in my project, in case I have an appbar and I configured the drawer to open with it, but it is not working and presenting the following errors.

"React.createElement: type is invalid - expected to string (for built - in components) or a class / function (for composite components) but got: undefined. you might have mixed up default and named imports. "
"'handleToggle' is assigned a value but never used"
"handleClose 'is assigned value but never used"

PS: Sorry for my bad english, I'm Brazilian.

MY CODE:

<img width="691" alt="sem titulo" src="https://user-images.githubusercontent.com/34941315/34633945-d0868b8a-f266-11e7-969c-01a033cd2de4.png">

**Comment by jquense** [comment]
Hey there, welcome to React :) 

We try to keep the React issue tracker focused on react bugs and feature requests, for general support try one of many avenues of support noted in the docs! https://reactjs.org/community/support.html

**Comment by gaearon** [comment]
Check the line on which it happens. You probably forgot to import that component, or imported it the wrong way (just like the error message tries to tell you).
