### ISSUE TITLE
Forked props not being isolated 

### ISSUE THREAD

**Issue by markuspelnens** [facebook/react#11988]
When I fork a prop like this

```
class NewOrderContainer extends Component {
  constructor(props) {
    super(props);
    this.state = {
      orderForm: props.orderForm,
    };
  }

```

and then proceed to update state such as this:

```
this.setState((previousState) => {
	const updatedOrderForm = previousState.orderForm;
	updatedOrderForm.quantity = 4
		return {
		orderForm: updatedOrderForm 
	}
});
```

it mutates the original prop (or more specifically, the state of the component passing the prop orderForm). Mutations to state forked from a prop should be isolated

**Comment by gaearon** [comment]
This is not how objects work in JavaScript. React doesn’t do anything magic. If you mutate an object then this object changes. You are sharing the same object between two parts of the code so mutations to it are seen in both.

Our suggested solution is to avoid mutation. For example:

```js
this.setState((previousState) => {
  const updatedOrderForm = {
    ...previousState.orderForm,
    quantity: 4
 }
  return {
    orderForm: updatedOrderForm 
  }
});
```

Hope this helps!
```

**Comment by markuspelnens** [comment]
Got it! Thanks!
