### ISSUE TITLE
(Debian 9 64-bit) onMouseMove, onMouseEnter, and onMouseLeave not Firing in Chrome

### ISSUE THREAD

**Issue by brandonrninefive** [facebook/react#11984]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**

In Google Chrome, an element with the onMouseMove and onMouseEnter listeners will not fire the events unless clicked. Likewise, onMouseLeave will not fire unless the mouse is clicked on an area not occupied by the listening element.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The following JSFiddle reproduces the bug: https://jsfiddle.net/69z2wepo/97542/.
To reproduce, simply create an element with the above listeners and test their behavior in Chrome.

**What is the expected behavior?**

The onMouseEnter, onMouseMove, and onMouseLeave listeners should fire in Chrome without the mouse needing to be clicked.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I tested this with React 16.2 on my own development server, and also React 0.14.3 in the above JSFiddle. In both cases, the problem occurs. I am using Debian 9, kernel version 4.9.0-5-amd64, and Chrome Version 63.0.3239.132 64-bit to reproduce the error. I tried to reproduce this issue on Windows with the same major version of Chrome, but it seems to work properly.

**Comment by gaearon** [comment]
>The following JSFiddle reproduces the bug: http://jsfiddle.net/ucrjxjv5/.

It doesn't run for me, are you sure the URL is correct?

**Comment by SadPandaBear** [comment]
Using the same settings on a VM, not working either.

https://jsfiddle.net/69z2wepo/97542/

**Comment by brandonrninefive** [comment]
My apologies, it appears I messed up something in the fiddle before sending it. The one @SadPandaBear sent accurately reproduces the bug.

**Comment by aweary** [comment]
Can we verify if this happens with a similar setup without React? If it's OS-specific it's most likely a browser bug.

**Comment by brandonrninefive** [comment]
Just ran a vanilla JS test through JSFiddle using the same OS/Chrome configuration, and I achieved the same results: http://jsfiddle.net/xfFMk/591/. Looks like this is an upstream issue with Chrome, as @aweary suggested.

**Comment by aweary** [comment]
@brandonrninefive thanks for following up with a Chromium bug report! I'll close this since it's not an issue with React.

**Comment by DevonTomatoSandwich** [comment]
For anyone wondering, definitely check the link to chromium issue but In my case I just needed to update to latest chrome version and everything was working perfect :)
