### ISSUE TITLE
grabbing pending state value

### ISSUE THREAD

**Issue by giorgim** [facebook/react#11989]
Assume I write this

`this.setState({ctr:1});
`
Now, assume **state hasn't been updated yet** as a result of above call, and I write:

`this.setState((ps)=>{console.log(ps.ctr)})
`
Will I see value "1"?

Basically question is about if there is a _pending state update_ from a "_Normal_" (not functional) setState, will the previousState that I receive in _functional setState,_ capture that pending value?

**Comment by gaearon** [comment]
Yes. Conceptually `setState(obj)` is equivalent to `setState(() => obj)`.

**Comment by giorgim** [comment]
@gaearon ah so it means with functional setState you can really get the latest state (including if there is a pending one). the doc don't say that explicitly though (as in my question).

**Comment by gaearon** [comment]
Open to rewordings in docs, feel free to send PRs. The important tradeoff is keep the docs readable for people who don't care about these details as much.
