### ISSUE TITLE
i need to learn this 

### ISSUE THREAD

**Issue by skybrandevs** [facebook/react#11994]
what do i need to learn to get started with react js

**Comment by jquense** [comment]
Hi there, and welcome. Glad you want to learn React! There are lots of resources around for doing that and maybe a good place to start is the documentation and the support avenues: 

https://reactjs.org/docs/hello-world.html
https://reactjs.org/community/support.html

We want to keep the issue tracker clear for bugs and feature requests so i'll close this. Good luck!
