### ISSUE TITLE
Warn in server renderer if class doesn't extend React.Component but has a render() method

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11991]
Same as https://github.com/facebook/react/issues/10103, but for the server renderer. You can look at implementation in https://github.com/facebook/react/pull/11168 and do something very similar in `ReactPartialRenderer.js`.

**Comment by wyze** [comment]
Hi Dan, I'd like to take this up. Do you have some more direction on where to put the check to determine if the component is not extended correctly? I tried putting it here: [ReactPartialRenderer.js#L394](https://github.com/facebook/react/blob/master/packages/react-dom/src/server/ReactPartialRenderer.js#L394) but then all the server tests threw the warning, so I don't think that was right.

**Comment by gaearon** [comment]
Maybe you want to do it right before [this line](https://github.com/facebook/react/blob/master/packages/react-dom/src/server/ReactPartialRenderer.js#L422)?

**Comment by wyze** [comment]
Thanks! I think I got it. You pointed me in the right direction, but ended up being in the `else` case of that branch. PR incoming shortly.
