### ISSUE TITLE
AngularJS Injector Equivalent

### ISSUE THREAD

**Issue by alexfromapex** [facebook/react#12007]
**What is the current behavior?**

No documented way to easily manipulate components/state/props from a third-party perspective.

**What is the expected behavior?**

The expected behavior is to have a mechanism similar to the [AngularJS injector](https://docs.angularjs.org/api/ng/function/angular.injector) that allows additional compilation after bootstrapping.  All versions of React, to my knowledge, are affected by this issue.  I've tried reverse-engineering the React Dev Tools and browserify-ing them but it will not be a long-term sustainable solution with constant updates being made to the React codebase.

**Use Case**

* Any time an enterprise-level or multi-party deployment has a third-party that wants to modify presentation/data

**Comment by TrySound** [comment]
@alexfromapex From my mind angular injector is a pain which I tried to get rid and never use again. Show and example where injector behaves better than es modules.

**Comment by gaearon** [comment]
This is a bit hard discuss without a specific use case. We won’t add something that lets you arbitrarily break the encapsulation of components.

However something similar can be achieved through:

* Aliasing modules with your bundler (e.g. webpack `alias` option) so you can override a specific module with a fork. You could move “overridable” data and/or components to such files. 
* Context, which is basically a DI mechanism based on the parent component tree: https://reactjs.org/docs/context.html. 

I hope this helps!

**Comment by alexfromapex** [comment]
@TrySound @gaearon I've added some use additional use cases.  I've explored many avenues for this, including the aliases for modules, but the problem is that always requires the back-end team modifying their deployment instead of the front-end simply hooking into and manipulating the output of the deployment.

**Comment by gaearon** [comment]
How would you solve this problem for generic JavaScript code? e.g. you can't "modify" functions in other libraries. Why are components any different from functions in this respect?
