### ISSUE TITLE
Add React.Children.isRenderable

### ISSUE THREAD

**Issue by ngub** [facebook/react#12002]
**Do you want to request a *feature* or report a *bug*?**
A feature

**Motivation:**
Given a component which gets props from `context` (e.g. it accepts props from Redux store via `connect` HoC) and renders either `null` or some React node by condition based on data from context it would be helpful to know outside the component whether it renders any markup or not. It would let us render wrappers for the component only if it is visible.

**Usage example:**
Let's say, we have a `FancyContainer` which wraps every child in a `FancyWrapper` (which can add margins, borders, animation etc).
```
<FancyContainer>
  <ConnectedComponent/>
  <ConnectedComponentConditionallyReturningNull/>
  <ConnectedComponent/>
</FancyContainer>
```
The `ConnectedComponent` doesn't accept props. It gets everything from `context`!
```
const FancyComponent = ({isNull}) => isNull ? null : <h1>Hello</h1>
const ConnectedComponent = connect((store) => ({isNull: !store.data}))(FancyComponent)
```
Without checking if a `ConnectedComponentConditionallyReturningNull` renders any markup we get an empty visible wrapper between first and third children and thus break styling.

React.Children.isRenderable would allow us to easily filter children without UI.
```
const FancyContainer = ({children}) =>
  React.Children.map(children, (child => 
    React.Children.isRenderable(child)
      ? <FancyWrapper>{child}</FancyWrapper>
      : child
  ))
```

**Why not just do X?**
We could achieve such behavior by passing a handler for the condition switch of the connected component, but this approach would break its encapsulation and it is not suitable for those library components which toggle their "renderability" internally.

We theoretically could use `:has` CSS pseudo selector (though it is not supported yet by any browser) and setting `ConnectedComponent`'s `display` property to `none` which would result in `FancyContainer` rendering invisible nodes. But if `FancyContainer` is itself wrapped in a `FancyWrapper` we then wouldn't be able to hide its styling.

We could try to manually find `<ConnectedComponent/>`'s node in DOM and if it doesn't exist remove `FancyWrapper` but that sound too messy and violates React's declarative nature. Also if data in `context` is dynamic (it usually is) we would then hide components while their data is still on the way from the server and might never reveal them when it is loaded to our `context` (maybe we could but with more mess).

**Comment by gaearon** [comment]
Please create [an RFC](https://github.com/reactjs/rfcs), thanks!

**Comment by ngub** [comment]
Ok, thank you
