### ISSUE TITLE
dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by shablenko** [facebook/react#12001]
dangerouslySetInnerHTML currently uses `document.write`, according to googles recommendations it is better to be replaces with something like `innerHTML = 'some html <br />'`, because `document.write` can affect performance.

Could it be done?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 16.02

OS: Ubuntu 16.04

All browsers i think.

**Comment by gaearon** [comment]
`dangerouslySetInnerHTML` [does not](https://github.com/facebook/react/blob/982a82884493c39f3cf322734ada175b6fb6bf22/packages/react-dom/src/client/setInnerHTML.js#L38) use `document.write`.
