### ISSUE TITLE
Getting minification warnings even with DefinePlugin and UglifyJSPlugin

### ISSUE THREAD

**Issue by s-daoud** [facebook/react#12003]
Hello! I've scoured through other issues and can't figure out why the warning is still around because it feels like I've done everything. Here's the setup:

Build scripts
```
    "heroku-postbuild": "npm run build:prod",
    "build:webpack": "webpack --progress --display-error-details --bail",
    "build:dev": "npm run build:webpack -- --config config/webpack/development.config.js",
    "build:prod": "NODE_ENV=production npm run build:webpack -- --config config/webpack/production.config.js",
```

`base.config.js`:
```
config.plugins = [
  new webpack.optimize.OccurenceOrderPlugin(),
  new webpack.DefinePlugin({
    //sets up some other constants on process.env
  }),
];
```

`production.config.js`:
```
var config = extend({}, baseConfig);

config.plugins.push(
  new webpack.DefinePlugin({
    "process.env.NODE_ENV": JSON.stringify("production"),
  }),
  new webpack.optimize.UglifyJsPlugin({
    mangle: true,
    compress: { warnings: false },
    output: { comments: false },
    exclude: [/\.min\.js$/gi]
  }),
  new webpack.optimize.DedupePlugin(),
//some more plugins
```

Using React v15.4.2 and Webpack v1.14.0. I'm not sure what I'm missing -- DefinePlugin and UglifyJsPlugin seem to be declared properly, and the `NODE_ENV` is set to production up in the script. Any help would be greatly appreciated! Thank you!

**Comment by gaearon** [comment]
You might find this way to diagnose it helpful: https://github.com/facebook/react-devtools/issues/692

**Comment by s-daoud** [comment]
That's helpful, thanks! It does look like React's being rendered twice, and there's a copy in development and one in production. I'll look into it!

**Comment by gaearon** [comment]
Might help to try `npm ls react` and `npm ls react-dom` in case you accidentally duplicate it. Could also be some bad webpack config (e.g. accidentally including it twice through some clever aliasing or bad bundle splitting config).

**Comment by s-daoud** [comment]
Haha yeah there's three copies of each in there. This is a great starting point to pull those duplicates out; thanks for your help!

**Comment by aweary** [comment]
Since we've determined this isn't an issue with React, I'm going to go ahead and close this :)
