### ISSUE TITLE
Value in input not updated/cleared with undefined value

### ISSUE THREAD

**Issue by themre** [facebook/react#12013]
I'm trying to clear my values of inputs with undefined values. I setup a demo page: https://codesandbox.io/s/n3v42mj50

Basically if I set in render 
`const {txt1, txt2, txt3 = ''} = this.state.txts` the button clears input 3, but not if I don't put default value for txt3. I was searching through issues but didn't find similar issue. The use case is, that I have huge form and I have some predefined values. And once I update my form and try to reset it, these inputs are not cleared. Thanks for any help!

**Comment by jquense** [comment]
The value isn't cleared on the input because you haven;'t cleared it in state. your reset only resets txt1 and txt2, txt3 is left as it is so nothing is cleared

**Comment by jquense** [comment]
https://codesandbox.io/s/vqv487yw4y is an updated example
