### ISSUE TITLE
It is not possible to set optional property to PureComponent using TypeScript

### ISSUE THREAD

**Issue by Lazarencjusz** [facebook/react#12022]
**Bug**
**What is the current behavior?**
I am creating an interface with optional key and trying to set it as a type for `PureComponent` props. Also I am using `connect` from `react-redux`
More datails: [StackOverflow](https://stackoverflow.com/questions/48262637/optional-default-prop-for-purecomponent-in-typescript?noredirect=1)

**What is the expected behavior?**
Possibility to set somehow optional props.

**Which versions of React, and which browser**
`    "@types/react": "^16.0.19",`
`"react": "^16.0.0",`
  `  "react-redux": "^5.0.6",`
`"typescript": "^2.3.4",`

It seems that `PureComponent` extends from `Component` and  require `props` to be `Readonly`  type [lib.es5.d.ts] (it does not allows to optional keys like `Partial`). Should it be `Partial` instead of `Readonly`?

**Comment by gaearon** [comment]
We're not the ones maintaining the TypeScript definitions for React, so we can't help with this. Sorry!
