### ISSUE TITLE
Should Children.* treat React.Fragment as an array?

### ISSUE THREAD

**Issue by wmertens** [facebook/react#12026]
When traversing children with `Children.forEach`, it treats Fragments as stand-alone elements instead of traversing their children.

I was under the impression that they were a convenience equivalent to arrays? Should they not be traversed as such?

**Comment by nmain** [comment]
Related #11859

**Comment by gaearon** [comment]
Yep. Please see https://github.com/facebook/react/issues/11859#issuecomment-355656427. Thanks!
