### ISSUE TITLE
Add referrerPolicy to iframe for react 16

### ISSUE THREAD

**Issue by elachys** [facebook/react#12021]
Property 'referrerPolicy' does not exist on type 'DetailedHTMLProps<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>'.

see https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/referrerPolicy

react@16.2.0
react-dom@16.2.0

**Comment by gaearon** [comment]
The error you're quoting comes from TypeScript, not React.
