### ISSUE TITLE
Add React.isFragment api for verifying Fragment

### ISSUE THREAD

**Issue by zheeeng** [facebook/react#12038]
**Do you want to request a *feature* or report a *bug*?**

I want to request a feature.

**What is the current behavior?**

We have no API to verify a ReactNode is a React 16 Fragment. Though now we can use `React.isValidElement(instance) && typeof instance.type === 'symbol'` to distinguish it. It's verbose and seems uncertianly right.

**What is the expected behavior?**

Add api:

```
React.isFragment(object)
```
Verifies the object is a React.Fragment. Returns true or false.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.2

**Comment by NE-SmallTown** [comment]
Is there already some progress on this? If, no  maybe I can take this

**Comment by aweary** [comment]
There is https://github.com/facebook/react/pull/11279, which implements `isFragment` along with a number of related introspection utilities.

**Comment by NE-SmallTown** [comment]
@aweary Ye, but looks like seb's abstraction is excessive and dan doesn't approve it? But if you want to merge that later or you just want to tell @zheeeng can copy and use that in their projects, I will be fine to close #12092 :)

**Comment by bvaughn** [comment]
I'm going to take a look into finishing up PR #11279.

**Comment by bvaughn** [comment]
Check out PR #12199

**Comment by bvaughn** [comment]
FYI you can test the new `react-is` alpha via `npm install react-is@next` (or `yarn add react-is@next`)

**Comment by zheeeng** [comment]
@bvaughn This package is awesome!

**Comment by bvaughn** [comment]
Glad to hear!

**Comment by aweary** [comment]
Closing, since this API exists in `react-is`
