### ISSUE TITLE
'npm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by drew0530** [facebook/react#12045]
Current Behavior: 

```
$ create-react-app my-app

Creating a new React app in C:\Users\SwoleDaddyBuffNeck\my-app.

'npm' is not recognized as an internal or external command,
operable program or batch file.
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

'npm' is not recognized as an internal or external command,
operable program or batch file.

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts@0.9.x has failed.
```

I have tried everything under the sun, including uninstalling and reinstalling node, npm, and the create-react-app package, switching to a different version, and every variation of how to add npm to my PATH I could find on the internet. I dont usually have issues with npm, and I use it for several other projects, and it seems to work fine, I cannot figure out why it's only happening here. I could actually install react and react-dom manually, but when I tried installing react-scripts, it didnt output anything and I had to ctrl+c to get my console back.

I understand this is not a forum for npm, but as I described, I dont have this issue in other projects, and it works fine doing literally anything else. Any help would be greatly appreciated.

**Comment by gaearon** [comment]
Filing this in https://github.com/facebookincubator/create-react-app/ would probably be more appropriate as this will get lost in this repo.

I don’t have an obvious fix in mind but maybe you could try installing Yarn and see if that works instead?

Another thing worth trying is this: https://github.com/facebookincubator/create-react-app/issues/3326#issuecomment-340501321

**Comment by drew0530** [comment]
I'm assuming you mean to run these lines here:

```
reg delete "HKLM\Software\Microsoft\Command Processor" /v AutoRun /f
reg delete "HKCU\Software\Microsoft\Command Processor" /v AutoRun /f
```

**Comment by drew0530** [comment]
Also I opened an issue in the create-react-app thread: [https://github.com/facebookincubator/create-react-app/issues/3861](url)

**Comment by gaearon** [comment]
Closing in favor of https://github.com/facebookincubator/create-react-app/issues/3861.
