### ISSUE TITLE
Highlight production bundles in bold in the Danger integration comment

### ISSUE THREAD

**Issue by gaearon** [facebook/react#12043]
We added integration with Danger in https://github.com/facebook/react/pull/11865.
It shows a bundle size difference on PRs, like this: https://github.com/facebook/react/pull/12028#issuecomment-358717464.

We should change the output so that production bundles are bold in the results. I think we can also remove the red triangle on increase from the development bundles because they're not as important.

**Comment by clairecliu** [comment]
i would like to give this a try

**Comment by gaearon** [comment]
You got it!

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/12054.
