### ISSUE TITLE
Write blog post showing recommended, async-safe coding patterns

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#12048]
Follow up item for PR #12028. Relates to reactjs/rfcs/pull/6.

Show examples of how to accomplish common tasks in an async-friendly way, using the new component API.

Also show examples that illustrate pitfalls (eg `setTimeout` calls to `setState`).

**Comment by aweary** [comment]
This is done! 🎉

**Comment by bvaughn** [comment]
❤️

**Comment by blling** [comment]
Blog link? :)

**Comment by bvaughn** [comment]
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
