### ISSUE TITLE
Strange Warning. PropType is marked as required in the format `propName.isRequired`.

### ISSUE THREAD

**Issue by danielvegaceja** [facebook/react#12042]
I have a component with the following proptypes:

``` javascript
Component.propTypes = {
    media: PropTypes.shape(PropTypes.any),
};

Component.defaultProps = {
    media: {},
};

```

Initially, i set `media` prop as required, but then changed to non-required. Still, the console show a warning:

`Warning: Failed prop type: The prop "media.isRequired" is marked as required in "Component", but its value is "undefined".`

What I see, is in the prop name that is identifying the "required" option, is adding *.isRequired*. Do you think this is a bug? I have faced this several times in my app, but I never got it working properly. The work arround was to change those propTypes to `PropType.any`.

Any help or idea will be great.

**Comment by gaearon** [comment]
I don't think `shape` takes a PropTypes function. Did you mean to just use `PropTypes.object`?

What ends up happening in your case is that `PropTypes.any` itself has a property called `PropTypes.any.isRequired`, and by passing it to `shape` you're basically forcing props to have a shape of `{isRequired: ...}`. 😉

**Comment by danielvegaceja** [comment]
I use `shape` because of the "forbidden" propTypes.

Thanks a lot, I didn't remember that *.any* behavior.

**Comment by gaearon** [comment]
I don't understand what you mean. I think you might be misunderstanding how PropTypes work.

Again, `shape()` doesn't take another propType as an argument. It takes an object.

Wrong:

```js
PropTypes.shape(PropTypes.any)
```

Right:

```js
PropTypes.any
```

or

```js
PropTypes.shape({
  someField: PropTypes.any
})
```

**Comment by gaearon** [comment]
Also it's not clear what you mean by "forbidden propTypes". If you show a full example of the problem you're having with them maybe I can help.
