### ISSUE TITLE
React test utils don't reset form inputs upon simulated reset button click

### ISSUE THREAD

**Issue by daelmaak** [facebook/react#12067]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In one of my components, I have a form with few inputs and reset button. In my tests I find that button, simulate a click on it but none of the inputs are reset.

**Reproduction**
See here https://jsfiddle.net/2854yewm/
Component above shows how it should be, but the test shows the expected behaviour doesn't occur.

**What is the expected behavior?**
Simulated click on the reset button causes the inputs in the form to be reset.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React and ReactDOM 16.2.0, testing with Jest 21.2.1

**Comment by gaearon** [comment]
I agree `Simulate` API is confusing. It doesn't actually simulate a *browser event*, it just simulates a *React event*. So any built-in browser behaviors won't happen automatically.

To achieve what you want, you should be able to simulate a *browser event* using browser APIs such as `node.dispatchEvent()`. Like this:

```js
