### ISSUE TITLE
onChange event of a checkbox not firing in some circumstances

### ISSUE THREAD

**Issue by sciamannikoo** [facebook/react#12061]
I'm not sure if that's a but or (more likely) just a lack of knowledge.

The fact I started fiddling with React only a couple of weeks ago might be a hint.

Anyway, the code below is meant to display a checkbox.

```javascript
import React from 'react';
import {connect} from "react-redux";
import {fetchSettingsIfNeeded, updateSetting} from "../../actions/settings";

class AdjustIDs extends React.Component {
	setting_key = 'auto_adjust_ids';

	constructor(props) {
		super(props);
		this.props.fetchSettings();
	}

	onChange = (e) => {
		this.props.updateSetting(this.setting_key, e.target.checked);
	};

	render() {
		// console.log('AdjustIDs props', this.props);
		const value = this.props.settings.data[this.setting_key];

		return (<fieldset className="wpml-settings-section" disabled={this.props.disabled}>
			<h4>Make themes work multilingual</h4>
			<p>
				This feature turns themes into multilingual, without having to edit their PHP files.
			</p>
			<label>
				<input type="checkbox" defaultChecked={value} onChange={this.onChange}/> Adjust IDs for multilingual
																																								 functionality
			</label>
		</fieldset>);
	}
}

function mapStateToProps(state) {
	const {settings: settingsReducer} = state;
	const {isFetching, didInvalidate} = settingsReducer || {isFetching: true};

	return {
		isFetching,
		didInvalidate,
		settings: settingsReducer
	};
}

const mapDispatchToProps = (dispatch) => ({
	fetchSettings: (key, defaultValue) => dispatch(fetchSettingsIfNeeded(key)),
	updateSetting: (key, value) => dispatch(updateSetting(key, value)),
});

export default connect(mapStateToProps, mapDispatchToProps)(AdjustIDs);
```

Even if probably not relevant, for clarity, data is read and written through some REST calls and the code is [mostly based on this](https://redux.js.org/docs/advanced/AsyncActions.html).

Back to the specific case, the checkbox is supposed to fire an event when clicked.

And this is what happens, as long as the initial state of `value` (that is, `this.props.settings.data[this.setting_key]`) is `false`.
In this case, every time I click the checkbox, `this.onChange` is called.

If instead the initial state of `value` is `true` and I click on it, `this.onChange` is not called.
Clicking on it again will call `this.onChange` and from that moment on, everything works flawlessly: callbacks are called, data is updated and refreshed as expected.

The only problem I'm having if the initial state is `true`.

I've tried many possible combinations to see if there is a different scenario which may cause the same problem, but it seems that's the only case.

I've tried to check if I'm doing something wrong with controlled/uncontrolled components, and, as far as my freshness with React allows me, it looks like that's how I'm supposed to handle this.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

My current dependencies (need some cleanup):
```
"babel-cli": "^6.26.0",
"babel-core": "^6.26.0",
"babel-loader": "^7.1.2",
"babel-plugin-transform-class-properties": "^6.24.1",
"babel-plugin-transform-object-rest-spread": "^6.26.0",
"babel-preset-env": "^1.6.1",
"babel-preset-react": "^6.24.1",
"cross-fetch": "^1.1.1",
"css-loader": "^0.28.7",
"express": "^4.16.2",
"extract-text-webpack-plugin": "^3.0.2",
"moment": "^2.20.1",
"node-sass": "^4.7.2",
"numeral": "^2.0.6",
"query-string": "^5.0.1",
"raf": "^3.4.0",
"react": "^16.2.0",
"react-addons-shallow-compare": "^15.6.2",
"react-checkbox-group": "^3.3.4",
"react-dates": "^16.0.1",
"react-dom": "^16.2.0",
"react-modal": "^3.1.10",
"react-radio-group": "^3.0.2",
"react-redux": "^5.0.6",
"react-router-dom": "^4.2.2",
"redux": "^3.7.2",
"redux-form": "^7.2.1",
"redux-logger": "^3.0.6",
"redux-thunk": "^2.2.0",
"sass-loader": "^6.0.6",
"style-loader": "^0.19.1",
"superagent": "^3.8.2",
"validator": "^9.2.0",
"webpack": "^3.10.0",
"whatwg-fetch": "^2.0.3"
```

I've tried with both Chrome (63.0.3239.132) and Firefox (57.0.1).

Let me know if you need any additional detail.

Thought probably not needed, I can also share the project, but it wouldn't work out of the box, as it's a work I'm doing to extend the back-end of a WordPress plugin.

**Comment by g3n1us** [comment]
You would need to have a value on the input to start with. Basically, the first click applies a value, and then forward there is a value to change.

**Comment by sciamannikoo** [comment]
But I do have a value. The checkbox is checked when l oading the page, because the value comes from the DB (actually, a store which uses REST API to get and update the data).

As I fear I wasn't clear enough (or maybe I misunderstood your comment), I've uploaded [here](https://drive.google.com/file/d/1mzgqnP90ZKN8wi3sVi4qOju70rGVTQlM/view?usp=sharing) a screencast of the issue.

**Comment by g3n1us** [comment]
Sorry, I wasn't clear enough. This doesn't have anything to do with React, the DOM node does not have a value property. Try adding `value="1"` to the element.

**Comment by sciamannikoo** [comment]
This is also something I tried before posting this (and which seems I forgot to mention).

As soon as I set the value attribute, the checkbox always displays as unchecked: no matter what's the original value in the DB.

I've tried with:
- `value="1"`
- `value="true"` (I know, it's silly)
- `value={true}`
- `value={1}`
- `value={value}` (which is the value of the checkbox read from the props)

All the above have the same effect: the checkbox always loads as unchecked, even when the value is `true` (verified by logging the props in the console).

At least, the `onChange` always gets fired now, but I can't use it this way, of course.

Removing the ` defaultChecked={value}` (which I had) does not make any change.

I can't use the `checked` attribute either, because, obviously, this would cause the "A component is changing an uncontrolled input of type checkbox to be controlled" warning (even though, if I use it, the checkbox is correctly loaded with the checked/unchecked state).

**Comment by g3n1us** [comment]
Here is a related discussion that should help you out: 
https://github.com/twisty/formsy-react-components/issues/66
It looks like I was sort of correct in the part about a "falsey" value being set on a checkbox.

BTW, I don't feel like this is a bug, but instead an area of React where behavior could be normalized a little better.
Good luck, and cheers!

**Comment by sciamannikoo** [comment]
@g3n1us thanks: that helped!

`<input type="checkbox" checked={!!value} onChange={this.onChange}/>` seems to do the trick.

Quite unintuitive, but at least it works.

**Comment by burtontanner** [comment]
@andreasciamanna  @g3n1us This works for me but only on a desktop. If i try this on mobile, the onChange method no longer invoked. Are you seeing the same behavior?
