### ISSUE TITLE
Rendering via JSX vs function call

### ISSUE THREAD

**Issue by riwu** [facebook/react#12066]
From https://medium.com/missive-app/45-faster-react-functional-components-now-3509a668e69f, rendering via `{Component(props)}` is significantly faster than `<Component {...props} />`.

Is there any plans in the near future (within the next few months perhaps) to optimise functional components so that we do not have to perform this optimisation (avoiding JSX for non-html elements)?

**Comment by gaearon** [comment]
We're looking at optimizations like this in the context of [Prepack](https://github.com/facebook/prepack) but there's nothing that's going to be immediately useable in the next couple of months. Within a year or two we might have something.

Note that unless you're creating thousands of elements, the performance difference won't be noticeable. Also unless your components are very flat and simple, the "pure win" from this optimization will likely be much less relevant in practice.
