### ISSUE TITLE
expose component methods

### ISSUE THREAD

**Issue by luisaccedo** [facebook/react#12074]
**Do you want to request a *feature* or report a *bug*?**

request a feature

**What is the current behavior?**

methods of components cannot be exposed

**What is the expected behavior?**

I would like to be able to expose methods of a component so it can be used from a container component, it can be done through an attribute similar to 'ref', like for example 'expose'

For example, imagine a have a car component and a wheel component,  the car would like to rotate the wheels using a method that the wheels expose to the cars

Something like:

```
class Car extends Component {
  constructor(props) {
    super(props);
  }
  rotateWheels() {
    this.wheels.rotate(32);
  }
  render() {
    return (
      <Body/>
      <Wheels expose={ ({ rotate }) => this.wheels.rotate = rotate }/>
    );
  }
}

class Wheels extends Component {
  constructor(props) {
    super(props);
    this.state = {
       wheelRotation: 0;
    };
  }
  rotateWheels(angle) {
    this.setState({wheelRotation: angle}); 
  }
  render() {
    const wheelStyle = {transform: `rotate(${this.state.wheelRotation}deg)`} 
    return (
      <div className="wheel" style={wheelStyle}/>
      <div className="wheel" style={wheelStyle}/>
      <div className="wheel" style={wheelStyle}/>
      <div className="wheel" style={wheelStyle}/>
    );
  }
}
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

all versions, all browsers

**Comment by gaearon** [comment]
In React your example above is typically implemented by [lifting state up](https://reactjs.org/docs/lifting-state-up.html), not refs.

Can you provide a more specific example that is hard to implement by lifting state up?

**Comment by TrySound** [comment]
@luisaccedo you contradict to yourself

> methods of components cannot be exposed

but then

> it can be done through an attribute similar to 'ref'

what is your request?

**Comment by luisaccedo** [comment]
thank you @gaearon, 

I understand the advantages of lifting the state up, and I've already done it that way.

Probably I'm wrong but I'll try to explain the use-case for a exposed method, maybe it makes sense:

I have a reusable carousel component, that has a lot of methods to control pagination, animations, responsiveness... Basically, it receives an array of items and some config options and takes care of the rest.

"Instances" of this component are used inside other components that pass the items to it, but the state of the carousel (for example the current page, the number of pages..) it's the responsibility of the carousel component. It's dynamically calculated based on the items array and the carrousel width and it has a nextPage() method, and a previousPage(), and a goToPage() that modify the current page state parameter from the carousel

that is good and solves most of the scenarios

but there is a scenario where it would be useful to be able to set the page from outside the carousel, exposing the goToPage method

If we lift the state up, we have to lift all the methods that transform that state to the containers of the carousel component, and that is where it seems that exposing a method would create a cleaner pattern... 

@TrySound you're right, the second sentence you quote should be: "it could be done..." because that's an idea, currently is not possible...

**Comment by LINKIWI** [comment]
> @TrySound you're right, the second sentence you quote should be: "it could be done..." because that's an idea, currently is not possible...

Can you elaborate on this? If you assign a ref to a component, you'll get an instance of that component, which exposes its class methods. You should, for example, be able to do `whateverRefNameYouSet.rotateWheels(50)`.

Generally speaking, you'll have much fewer headaches if you rearchitect your componnts to receive inputs declaratively as props from parent components, and calculate derived properties in the child, rather than trying to expose imperative interfaces to components higher up in the tree.

**Comment by luisaccedo** [comment]
> Generally speaking, you'll have much fewer headaches if you rearchitect your componnts to receive inputs declaratively as props from parent components, and calculate derived properties in the child, rather than trying to expose imperative interfaces to components higher up in the tree.

agree, but maybe sometimes being able to expose some methods might be useful...

**Comment by TrySound** [comment]
@luisaccedo So what's wrong with instance ref? With future private class fields you will even be able to hide some methods.

**Comment by adrianhelvik** [comment]
class Container extends React.Component {
  setChild(child) {
    // do something...
  }

  render() {
    return (
      <Child expose={this.setChild} />
    )
  }
}

class Child extends React.Component {
  componentDidMount() {
    if (this.props.expose)
      this.props.expose(this)
  }

  // ...
}

**Comment by adrianhelvik** [comment]
class Container extends  React.Component {
      setChild(child) {
        // do something...
      }

      render() {
        return (
          <Child expose={this.expose} />
        )
      }
    }

    class Child extends React.Component {
      componentDidMount() {
        if (this.props.expose)
          this.props.expose(this)
      }

      // ...
    }

You can even store instances on this.constructor if you want cross component communication. I've done it once.

**Comment by gaearon** [comment]
>it's the responsibility of the carousel component. It's dynamically calculated based on the items array and the carrousel width and it has a nextPage() method, and a previousPage(), and a goToPage() that modify the current page state parameter from the carousel

Typically in React you solve this by providing a declarative API in props instead. For example instead of `goToPage()` method you would implement a `currentPage` numeric prop. This way it can be controlled with state by any component higher up the tree.

**Comment by luisaccedo** [comment]
> @luisaccedo So what's wrong with instance ref? With future private class fields you will even be able to hide some methods.

as far as I know the instance ref doesn't allow you  to access component instance methods... is that possible?

**Comment by gaearon** [comment]
Instance ref lets you access instance methods (this is what it’s for).
Still, the right way to implement this in React in most cases is to provide a declarative API as mentioned above.

**Comment by luisaccedo** [comment]
thank you very much!

**Comment by aman-sprinkle** [comment]
@gaearon What is the declarative API for reloading the state of a child component?
I can use "key" but for my use-case, it isn't giving the best experience.
