### ISSUE TITLE
 react@16.0.0 bug

### ISSUE THREAD

**Issue by hpugongying** [facebook/react#12070]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
after upgrade react@16.0.0，
safari Browser console print bug
1.TypeError: undefined is not an object (evaluating 'Ja.ReactCurrentOwner')
2.TypeError: Map constructor does not accept arguments

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1.upgrade react@16.0.0
2.open safari browser and look console
3.show bug

**What is the expected behavior?**
don't console this mistake

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 react@16.0.0

**Comment by gaearon** [comment]
>undefined is not an object (evaluating 'Ja.ReactCurrentOwner')

You're probably mixing different versions of `react` and `react-dom`. They must be the same one (use 16.2.0 as the most recent one).

>Map constructor does not accept arguments

If you read [16.0 blog post](https://reactjs.org/blog/2017/09/26/react-v16.0.html) (which you should always do when upgrading), it mentions the new [JavaScript environment requirements](https://reactjs.org/blog/2017/09/26/react-v16.0.html#javascript-environment-requirements). If you want React to work in older browsers, you need to polyfill `Map` and `Set`.
