### ISSUE TITLE
Question : is React Fiber using GPU ?

### ISSUE THREAD

**Issue by Aarbel** [facebook/react#12071]
Hi React Team !

Here in Clovis.pro (React 15.4) we want to enhance React performances on quite old phones and tablets. Sometimes multi-component updates could slow down the phone and make the UX uncomfy (that's normal, basic javascript uses the CPU and old hardware have low CPU).

To enhance React performances did you made and update in React Fiber to directly allow the javascript to be run by the GPU ? Or do you know libraries to make that global hack ? Thanks ! :wink: 

ps : GPU is already used in CSS with Translate3D to make animations smoother.

**Comment by gaearon** [comment]
Yeah, we don't do anything like that. React 16 also runs in compatibility mode so don't expect drastic changes there. Keep an eye on our blog for announcement related to async React (which is still not related to GPUs though).
