### ISSUE TITLE
Remove Component.childContextTypes / Component.contextTypes and PropTypes requirements for Context

### ISSUE THREAD

**Issue by dwjft** [facebook/react#12086]
Since there is currently undergoing work (https://github.com/facebook/react/pull/11818) on the Context API, I feel like this may be a good time to bring this up.

----

In my projects, the design decision to not use `PropTypes` in our internal components was made early on, under the assumption that if we were to use `PropTypes`, we may as well go the whole way and use `flow` or `TypeScript` as well.

Enforcing a `PropType` declaration on a single React feature doesn't make much sense. If `PropTypes` are optional on `props`, why are they required on `context`?

To get around this enforcement, my components end up looking like the following:

```javascript
// makeContext.js
import PropTypes from 'prop-types';

const makeContext = (keys) => {
  const obj = {};
  keys.forEach((key) => {
    obj[key] = PropTypes.any;
  });
  return obj;
};

export default makeContext;
```

```javascript
// contextTypes.js
import makeContext from './makeContext';

export default makeContext([
  'someValue',
  'someOtherValue',
]);
```

```javascript
// ParentComponent.js
import contextTypes from './contextTypes';
import ChildComponent from './ChildComponent';

class ParentComponent extends React.Component {
  getChildContext() {
    return { someValue: 1, someOtherValue: false };
  }
  render() {
    return <ChildComponent />;
  }
}
ParentComponent.childContextTypes = contextTypes;
```

```javascript
// ChildComponent.js
import contextTypes from './contextTypes';

const ChildComponent = (props, { someValue }) => (
  <p>{someValue}</p>
);
ChildComponent.contextTypes = contextTypes;
```

----

As you can see, the declaration of both `childContextTypes` and `contextTypes` is essentially pointless, yet I am forced to do so because the API enforces it.

It seems that, much like `props` and `PropTypes`, it should be down to the developer to decide whether or not the rule should be enforced.

**Comment by TrySound** [comment]
@dwjft New context API won't require prop-types.

**Comment by gaearon** [comment]
You can see from the RFC that it doesn’t use PropTypes.

https://github.com/reactjs/rfcs/pull/2
