### ISSUE TITLE
i am trying to run create-react-app command

### ISSUE THREAD

**Issue by vivekmodi23** [facebook/react#12095]
F:\reactjs\project-1>create-react-app hello-world

Creating a new React app in F:\reactjs\project-1\hello-world.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

npm ERR! Unexpected end of JSON input while parsing near '...dir-recursive":"^0.1.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2018-01-25T18_39_41_416Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

Deleting generated file... package.json
Deleting hello-world / from F:\reactjs\project-1
Done.
npm version is:5.6.0

**Comment by gaearon** [comment]
This seems like an issue with your network, as JSON is corrupted. Perhaps you're behind a proxy, or have a bad connection. Unfortunately there's nothing we could do—please try from another network.

**Comment by vivekmodi23** [comment]
currently network is working properly can there be any other issue, other then this

**Comment by gaearon** [comment]
No, the message says that the network response is invalid.

Maybe you can try your luck with Yarn (https://yarnpkg.com/en/).
