### ISSUE TITLE
use setState in componentWillReceiveProps

### ISSUE THREAD

**Issue by ruoru** [facebook/react#12090]
if i use `setState` in `componentWillReceiveProps`
```js
componentWillReceiveProps(nextProps) {
    this.setState({key: value}, this.doWhatever)
}

doWhatever () {
    const { a } = this.props;
}
```
the question1 is in doWhatever this.props is `new props` or `old props`?
the question2 is when does the `nextProps` become `this.props`?

**Comment by stephenkingsley** [comment]
This question I think a ask in [stackoverflow.com](stackoverflow.com) is more helpful in here.

And in React, `state` and `props` are two concepts. Normally after your setState, the props is not changed.

**Comment by TrySound** [comment]
@ruoru React has minimal API. If you have something passed then it cannot be taken from component instance. So in `componentWillReceiveProps(nextProps)` `this.props` is prev props, in `componentDidUpdate(prevProps)` this.props is new props

**Comment by ruoru** [comment]
@stephenkingsley  @TrySound  Thank you very much for your reply, but these `React documents` had what you have said.

**Comment by gaearon** [comment]
The `setState` callback fires when the updates have been flushed to the DOM, so new props are current at that point.

>the question1 is in doWhatever this.props is new props or old props?

You'll get new props there.

>the question2 is when does the nextProps become this.props?

After React re-renders the component.
