### ISSUE TITLE
Can't use React.Fragment

### ISSUE THREAD

**Issue by ha404** [facebook/react#12097]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
broken in runtime

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

1. Use `<React.Fragment></React.Fragment>` or `<></>` syntax to render mapped fragments.
```js
export default enhance(({
  products,
}) => (
  <table>
    <thead>
      <tr>
        <th>Product ID</th>
        <th>Shoe Name</th>
        <th>Sale Status</th>
        <th>List Price</th>
      </tr>
    </thead>
    <tbody>
      {products.map(product => (
        <React.Fragment>
          <tr>
            <td>{product.id}</td>
            <td>{product.name}</td>
            <td>{product.sale_status}</td>
            <td>${product.price_cents / 100}</td>
          </tr>
          <tr>
            <td colSpan="4">testing</td>
          </tr>
        </React.Fragment>
      ))}
    </tbody>
  </table>
))
```
2. Try to render the component.
3. Get met with this error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Unknown`.
```

**What is the expected behavior?**
I expect the component to render. It works fine when rendering as an array (I just don't want to type a comma between my elements). It also works fine if I use a `<div>` but that's not semantically correct.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- React v16.2.0
- Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Mac 10.12.6

**Comment by TrySound** [comment]
@ha404 Check your node_modules and make sure you have react 16.2

**Comment by gaearon** [comment]
Maybe you have an older `react-dom`? Both need to be 16.2.0+.

**Comment by ha404** [comment]
Both are at `^16.2.0` :(

**Comment by gaearon** [comment]
Can you reproduce this in a fiddle? If not there might be some kind of local cache on your system that’s messing this up. Please provide a reproducing project.

**Comment by ha404** [comment]
Let me try to reproduce it somewhere. Here's another clue when I use the `<></>` syntax:
<img width="648" alt="screen shot 2018-01-25 at 12 54 09 pm" src="https://user-images.githubusercontent.com/567126/35411800-f4d1ccee-01ce-11e8-8706-dab846d7241c.png">

**Comment by ha404** [comment]
@gaearon https://codesandbox.io/s/0pvzqryz2l. It just seems to not like this fragments syntax.

**Comment by gaearon** [comment]
As mentioned in the blog post, the *syntax* support is not expected to come fast to all tools.

**Comment by ha404** [comment]
Understandable, I just can't understand why I'm getting similar errors. Is there anything else I need other than `react` and `react-dom` on `16.2.0`?

**Comment by ha404** [comment]
@gaearon it looks related to this https://github.com/facebook/react/issues/11759

**Comment by gaearon** [comment]
@ha404 No, that one is IE11-specific.

> Is there anything else I need other than react and react-dom on 16.2.0?

No. How did you verify that you have them? Can you post the content of `node_modules/react/package.json` and `node_modules/react-dom/package.json` please?

**Comment by ha404** [comment]
@gaearon that was the second thing I tried looking at haha, here ya go:

`node_modules/react-dom/package.json`:
```
{
  "name": "react-dom",
  "version": "16.2.0",
  "description": "React package for working with the DOM.",
  "main": "index.js",
  "repository": "facebook/react",
  "keywords": [
    "react"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/facebook/react/issues"
  },
  "homepage": "https://reactjs.org/",
  "dependencies": {
    "fbjs": "^0.8.16",
    "loose-envify": "^1.1.0",
    "object-assign": "^4.1.1",
    "prop-types": "^15.6.0"
  },
  "peerDependencies": {
    "react": "^16.0.0"
  },
  "files": [
    "LICENSE",
    "README.md",
    "index.js",
    "server.js",
    "server.browser.js",
    "server.node.js",
    "test-utils.js",
    "unstable-native-dependencies.js",
    "cjs/",
    "umd/"
  ],
  "browser": {
    "./server.js": "./server.browser.js"
  },
  "browserify": {
    "transform": [
      "loose-envify"
    ]
  }
}
```

`node_modules/react/package.json`:
```
{
  "name": "react",
  "description": "React is a JavaScript library for building user interfaces.",
  "keywords": [
    "react"
  ],
  "version": "16.2.0",
  "homepage": "https://reactjs.org/",
  "bugs": "https://github.com/facebook/react/issues",
  "license": "MIT",
  "files": [
    "LICENSE",
    "README.md",
    "index.js",
    "cjs/",
    "umd/"
  ],
  "main": "index.js",
  "repository": "facebook/react",
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "fbjs": "^0.8.16",
    "loose-envify": "^1.1.0",
    "object-assign": "^4.1.1",
    "prop-types": "^15.6.0"
  },
  "browserify": {
    "transform": [
      "loose-envify"
    ]
  }
}

```

**Comment by gaearon** [comment]
OK, my best guess is you accidentally have two React's in the bundle, one being an older version.

Try running `npm ls react` or inspect your Sources in Chrome DevTools and look how many files called `react.development.js` show up.

I don't think we can help further here—if it doesn't reproduce on a new project, it's definitely an issue with how your project is set up. You either have two Reacts or have some aggressive caching turned on and accidentally work with an older version.

**Comment by andrastothtw** [comment]
Maybe a nice `package-lock.json` problem where you _think_ you have `React 16.2` but in reality you are still using `16.0`?

**Comment by ha404** [comment]
@andrastothtw I found out an older version of React was being included externally D:

**Comment by THPubs** [comment]
For people who still have the problem even though you did not find an older version, try removing the `node_modules` folder and installing the packages again through `yarn install` or `npm install`.

**Comment by mikael1000** [comment]
I use codesandbox and I get this error:

`Invariant Violation

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

I write:
`import React, { Fragment } from 'react' `

Then I use it like this:
`<Fragment>
   ...
</Fragment>`

In Codesandbox Dependencies:

@material-ui/core 1.0.0
react 16.3.2
react-dom 16.3.2
react-scripts 1.1.4

**Comment by TrySound** [comment]
@mikael1000 the message is clear I think 
> or you might have mixed up default and named imports

Use `import * as React from 'react'`

**Comment by mikael1000** [comment]
@TrySound 
I actually follow this tutorial and I'm new to React.
https://www.youtube.com/watch?v=fox4Y-_Q9hE&list=PLcCp4mjO-z98WAu4sd0eVha1g-NMfzHZk&index=3

At time mark 15:40 he writes it and it works for him. I code along with him.
For me the error message is yada-yada... LOL ...sorry for being stupied (if I am). Well I read it like it can't find the component (from the file it should be defined in, react ??). But it works for the guy in the tutorial. 

I tried your import. I commented my: `import React from 'react`
and wrote
`import * as React from 'react`
Now it complains directly on the <Fragment> tag

**Comment by TrySound** [comment]
What do you mean by this?
> Now it complains directly on the tag

**Comment by mikael1000** [comment]
@TrySound 

Of course I made a stupid error. This is for bug reports and maybe I should know more about React before making bug reports. I should have asked for help somewhere instead. I cleared out my comments so people don't think about what I wrote. Sorry for taking unnecessary time and space. And thank you @TrySound for the answers.

**Comment by SuperChocoman7** [comment]
### **For those who create their project via "dotnet new react":** 
Here's what I've done: 
1. Remove your "wwwroot/dist" folder. **(Beware, you should probably make a backup before doing this.)**
2. Rebuild your project, and you shall see something like "**performing first-run webpack build**" in the output console. _(If you have difficulty finding the rebuild button, it's in the "Build(B)" tab on top of Visual Studio.)_
3. And it's done! I have no idea why.

And here is my `package.json`: 
```
"devDependencies": {
    "@types/history": "4.6.0",
    "@types/jquery": "^3.3.2",
    "@types/react": "^16.3.17",
    "@types/react-dom": "^16.0.6",
    "@types/react-hot-loader": "^3.0.6",
    "@types/react-redux": "^6.0.2",
    "@types/react-router": "^4.0.26",
    "@types/react-router-dom": "^4.2.7",
    "@types/webpack-env": "1.13.0",
    "aspnet-webpack": "^2.0.1",
    "aspnet-webpack-react": "^3.0.0",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "^4.1.1",
    "css-loader": "^0.28.4",
    "event-source-polyfill": "0.0.9",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "isomorphic-fetch": "2.2.1",
    "jquery": "^3.3.1",
    "json-loader": "0.5.4",
    "react-hot-loader": "^3.1.3",
    "style-loader": "^0.18.2",
    "typescript": "^2.9.1",
    "url-loader": "0.5.9",
    "webpack": "^2.5.1",
    "webpack-hot-middleware": "2.18.2"
  },
  "dependencies": {
    "popper.js": "^1.14.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-redux": "^5.0.7",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  }
```

**Comment by dotku** [comment]
I think we should deprecated React.Fragment maybe, since it might be slow (by smart detecting parent and child and render the proper tags).

btw, it doesn't support

<thead><tr>

eg.

```
<table>
<React.Fragment>
  <th>header A</th>
  <th>header B</th>
  <th>header C</th>
</React.Fragment>
</table>
```

would rendered as

```
<table>
  <th>header A</th>
  <th>header B</th>
  <th>header C</th>
</table>
```

**Comment by aximili** [comment]
> @TrySound
> 
> Of course I made a stupid error. This is for bug reports and maybe I should know more about React before making bug reports. I should have asked for help somewhere instead. I cleared out my comments so people don't think about what I wrote. Sorry for taking unnecessary time and space. And thank you @TrySound for the answers.

Hi mikael1000 (or @TrySound), would you be able to tell us what was the issue? We are having the exact same problem with React 16.7.0

**Comment by TrySound** [comment]
@aximili Make sure you have the right version in your node_modules. It could be resolved incorrect. Also make sure your dependencies does not have different react version. React and react-dom packages usually should be in peer dependencies of libraries. Another way to solve the problem is force react version with yarn resolutions.

**Comment by aximili** [comment]
Thx so much @TrySound 
We tried deleting node_modules and 'npm install' again. Yes it has the correct versions. (We never used yarn though)

It is only affecting this particular React project with TypeScript, we must be missing something. How do you check for the dependencies issue that you mentioned?

This is what's in our package.json
  "devDependencies": {
    "@babel/preset-typescript": "^7.1.0",
    "@types/node": "^8.10.39",
    "mobx": "^5.9.0",
    "mobx-react": "^5.4.3",
    "mobx-react-devtools": "^6.0.3",
    "source-map-loader": "^0.2.4",
    "ts-loader": "^5.3.3",
    "typescript": "^3.2.4"
  },
  "dependencies": {
    "@types/lodash": "^4.14.120",
    "@types/react": "^16.7.0",
    "@types/react-dom": "^16.7.0",
    "csstype": "^2.6.0",
    "express": "^4.16.4",
    "path": "^0.12.7",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "webpack": "^4.28.4",
    "webpack-cli": "^3.2.1"
  }

**Comment by TrySound** [comment]
I'm looking at node_modules folder and check all react dependencies
