### ISSUE TITLE
react-test-renderer: toTree() does not yet know how to handle nodes with tag=10

### ISSUE THREAD

**Issue by ambar** [facebook/react#12106]
**Do you want to request a *feature* or report a *bug*?**

bug.

**What is the current behavior?**

```js
  renderer.create(
    <Fragment>
      <Fragment>foo</Fragment>
    </Fragment>
  )
  .toTree()
```

> Invariant Violation: toTree() does not yet know how to handle nodes with tag=10

https://codesandbox.io/s/olky92m01y

**What is the expected behavior?**

returns a tree.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.2.0

**Comment by gaearon** [comment]
This does look like a bug (or rather missing functionality).
Would you like to send a PR?

**Comment by maciej-ka** [comment]
I would give it a try.

**Comment by aweary** [comment]
Thanks @maciej-ka!
