### ISSUE TITLE
Input not accounted for by form

### ISSUE THREAD

**Issue by xou816** [facebook/react#12108]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

Inputs rendered by React (controlled or uncontrolled) are not accounted for when submitting forms.

For instance:
```{html}
<form method="POST" action="/foo">
<input type="text" name="foo1" value="bar1" />
<div><input type="text" name="foo2" value="bar2" /></div>
</form>
```
will produce the following form data : `foo1=bar1&foo2=bar2`.

Whereas 
```{html}
<form method="POST" action="/foo">
<input type="text" name="foo1" value="bar1" />
<div><!-- react component rendered here --></div>
</form>
```
with this component
```{jsx}
function MyInput(props) {
  return <input type="text" name="foo2" value="bar2" />;
}
```
will produce `foo1=bar1`.

I can't get a fully working example on CodeSandbox as this requires looking at the resulting HTTP request or having jQuery or such to serialize the form.

**What is the expected behavior?**

The second example should produce `foo1=bar1&foo2=bar2`, React components should be usable in regular forms.

Note : browser inspectors show expected `value`s and `name`s for the React rendered inputs. However, it seems the `value` attribute uses getters and setters for these inputs, whereas plain HTML inputs `value`s are just strings.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.2.0. Tested on Chromium 64.0 and Firefox 58.0, on Archlinux.

**Comment by aweary** [comment]
Hey @xou816, thanks for the report.

I tried reproducing the issue, but wasn't able to. I made [this JSFiddle](https://jsfiddle.net/juvd18b2/) which renders a single input inside a regular old HTML form. When the form is submitted, the (failed) network request contains the values from both the HTML input and the React input.

We'll need to be able to reproduce the issue consistently in order to diagnose the problem. If you could take a look at that JSFiddle I made and try to tweak it so it reproduces your problem, that'd be great.

Thanks!

**Comment by xou816** [comment]
Thanks for taking the time to look into this! I'll make sure to provide a JSFiddle next time.
I will be investigating this further on my end and will keep you updated.

**Comment by xou816** [comment]
It turns out this happens when the HTML markup is invalid, e.g. [here](https://jsfiddle.net/tfzwd0fm/).
I am not sure this can be considered a bug, but it definitely can be be confusing if you fail to realize your markup is invalid!
Thanks again!

**Comment by aweary** [comment]
Thanks for following up @xou816! I agree that that's confusing behavior. It seems like the field data is only missing if the `input` element was dynamically added to the DOM; adding a second `input` element after the HTML markup still works.

Unfortunately, React can't do anything about validating that the container it's rendered in is inside valid markup, so I'll close this out. Thanks again!
