### ISSUE TITLE
setState callback is never called and component state doesn't update (production only)

### ISSUE THREAD

**Issue by SachaG** [facebook/react#12102]
Using React 16.2.0, I'm running into a very strange behavior when things work fine locally, but in production (using Meteor) `setState` stops working.

Here's what I've noticed:

- `setState`'s callback is never called. 
- The DOM doesn't reflect any changes.
- The Devtools don't reflect the changes. 
- Calling `this.forceUpdate()` after `setState` doesn't do anything. 

On the other hand:

- `$r.state` returns an object with the correct updated state.
- `setState` returns an object with the correct updated state.

I'm sure the problem is on my side somehow (it's a fairly complex component which I didn't even write myself to make matters worse) but I thought maybe I could get some tips on how to go along debugging this frustrating issue?

**Comment by justinr1234** [comment]
@SachaG Can you show example code?

**Comment by gaearon** [comment]
It's not obvious to me why this would happen. I think we'll need a minimal reproducing case.

**Comment by SachaG** [comment]
To be honest I think it'll be easier to eventually just rewrite that component myself entirely. It's a 1000-lines of code component so there's just too much in there that can go wrong and I think isolating the problem to create a reproduction would probably take me even longer than rewriting it from scratch. So I'll close this for now.
