### ISSUE TITLE
Access Component from child's instance?

### ISSUE THREAD

**Issue by franciscop** [facebook/react#12101]
I am creating a [small, generic state management](https://github.com/franciscop/state) based on the `Proxy()` object. Now I am writing a React helper, but I've found an issue: to create the HOC I need access to `Component` from React. Looking at the [source code for Component](https://github.com/facebook/react/blob/master/packages/react/src/ReactBaseClasses.js) it doesn't seem like it can/should be a standalone function. This library should be able to be used independently, so making everyone download React is not feasible.

I have navigated through the [official HOC documentation](https://reactjs.org/docs/higher-order-components.html), past issues and Google but couldn't find any way to retrieve `Component` from the passed component to my HOC. This is the code I am working with (not yet in the repo linked above):

```js
// This will load the whole React independently of the project type
import { Component } from 'react';

const connect = (opts) => (Passed) => {
  return class WithState extends Component {
    // ...
  }
};

export default connect;
```

```js
// Note: assume this for Passed.js
import React, { Component } from 'react';
class Passed extends Component { ... }
export default connect()(Passed);
```

Now, I *did* find a hack to make this work, but it seems like one of the most fragile pieces of code I've ever written, relying on the differences between ES7 modules and CommonJS:

```js
const connect = (opts) => (Passed) => {
  const React = require('react');
  return class WithState extends React.Component {
    // ...
  }
};

export default connect;
```

This way it will only import React once the `connect()` is used, and `connect()` is the *React-exclusive* helper from my library. So my question/feature request is this: is it possible to access its constructor's parent (not just the child)? Could we make it possible somehow? Something like this would be ideal:

```js
// Is something like this possible?
const Component = Passed.super;
// or
const Component = Passed.constructor.super;
// or even (since a class is syntax sugar)
const Component = Passed.prototype.super;
```

I think that is not the way Javascript/React works, but I figured I will ask here since chances are you will know way better than me whether something like this is possible or not.

**Do you want to request a *feature* or report a *bug*?**
Request a feature I think

**Comment by franciscop** [comment]
Asking this gave me an idea on where to look for, and I found an alternative way of accessing the `Constructor` from the `Passed` **if** the `Passed` is not a pure function:

```js
// Has to be twice, one for the Child and the second for the parent
const Component = Object.getPrototypeOf(Object.getPrototypeOf(Passed)).constructor;
// Verify it:
console.log(Component.name);  // Component
```

This has the risk of needing this exact structure, which won't happen with pure components/functions. Any idea? :smile:

**Comment by franciscop** [comment]
Exactly same situation, that would not work with pure functions :(

Three really hacky ways so far, a clean, future-proof one to go! :rofl:

**Comment by franciscop** [comment]
Oh, about posible solutions I think a great one would be lodash's style:

```js
import Conponent from 'react/Component';
```

Since this way tree shaking coule be applied.

**Comment by TrySound** [comment]
@franciscop There's nothing you can treeshake in react. If you use one thing, you use it all. Also treeshaking is about handling imports in one entry point, so it's opposed to file splitting.

**Comment by gaearon** [comment]
Even if you try to read `Component` from `react` "dynamically" like you attempted with `require` in practice the bundler still finds it statically during the build time. So this doesn't really make a lot of sense.

I think what you want is a *separate entry point* in *your* library for React users.

```js
import { connect } from 'your-awesome-library/react';
```

Inside of it, you can freely import React because people who use that entry point are clearly React users.

On our side, "separating" Component isn't really valuable because the whole React bundle is very small (unlike ReactDOM) and splitting it further just increases the friction without any benefits. And in any case, your React users already *have* React so you shouldn't worry about getting just one export from React. They wouldn't be able to use it without other React APIs anyway.

**Comment by franciscop** [comment]
Hi Dan, thanks for the tip! I will look into bundling just `react`, I have actually never seen the size of react vs react-dom.

If that doesn't work I will probably go with the dynamic import, I did something similar already [with `translate` and got good results](https://github.com/franciscop/translate/blob/master/src/index.js#L63).

The bundler (at least rollup) *does not* find these types of require dynamically, it simply cannot do it. How would it find this?

```js
export default (name) => {
  return require(name);
};
```

**Comment by gaearon** [comment]
>I will look into bundling just react

I think that's a mistake. You should not be bundling it in any case.

You should leave it as en `external` (the exact option depends on the bundler you use). This will leave it as a `require` *in the compiled bundle* so the user doesn't get two copies of React.

**Comment by franciscop** [comment]
You are totally right, I will try that! 😊
