### ISSUE TITLE
I have an error after deployed my react website, I am using react 16.2.0 and this is the error:

### ISSUE THREAD

**Issue by luc-tuyishime** [facebook/react#12119]
![erreur1](https://user-images.githubusercontent.com/19607550/35555569-3bda9c38-05a8-11e8-80d6-80bf66ff2c51.png)

visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by gaearon** [comment]
The error message includes a link (you copied it here). Please visit it. It includes the full message.

**Comment by luc-tuyishime** [comment]
Great and thanks i solved it

**Comment by luc-tuyishime** [comment]
Hello @gaearon ,
I have an issue with my react website, it doesn't displaying in internet explorer 11 and some other browser, can you help me?
