### ISSUE TITLE
Error when I save the component ref to state

### ISSUE THREAD

**Issue by foisonocean** [facebook/react#12112]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error when I save the component ref to state

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codepan.net/gist/57e9a8328fb61e7df6c9100268f5ae9d

**What is the expected behavior?**
it seems like the ref callback is called too many times, (and every time have a different argument ?)
and this will fix the problem, but I don't know why: https://codepan.net/gist/56db06d8eea81c9b3eb96739e4274576

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React V16.2.0

**Comment by gaearon** [comment]
I'm getting an error trying to open your link. Can you please post on a service that doesn't have limitations (e.g. CodePen, not CodePan).

**Comment by gaearon** [comment]
> it seems like the ref callback is called too many times

Have you read this part?
https://reactjs.org/docs/refs-and-the-dom.html#caveats

**Comment by foisonocean** [comment]
@gaearon Sorry I didn't notice that in the doc.
