### ISSUE TITLE
Automatically assigning keys

### ISSUE THREAD

**Issue by sassanh** [facebook/react#12113]
**Do you want to request a *feature* or report a *bug*?**
I want to request a feature.

**What is the current behavior?**
Currently developer should manually assign a key to each element in an array even if he knows the elements in the array nor their order will not change.
```
[
    <hr key='1'/>,
    <hr key='2'/>,
    <hr key='3'/>,
]
```

**What is the expected behavior?**
```
[
    'Hi React,\n\nI promise I won\'t change the order of components, or if I do I promise I know what I'm doing, assign index in array to key prop if you really need the key prop or ignore it at all if you can deal with that. No warnings please, it hurts my obsessions to see a warning when I\'m not really required to get warned.\n\nRegards,\nDeveloper',
    <hr/>,
    <hr/>,
    <hr/>,
]
```
Or simply
```
[[
    <hr/>,
    <hr/>,
    <hr/>,
]]
```
Or
```
{__dangerouslyAssignKeysByYourself: [
    <hr/>,
    <hr/>,
    <hr/>,
]}
```
Or
```
{staticArray: [
    <hr/>,
    <hr/>,
    <hr/>,
]}
```
I prefer fourth methods as second method may lead to some conflicts.

Third method makes me feel I'm doing dirty things or I'm touching internal cogs in React.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16
Browser and OS are not relevant.

**Comment by gaearon** [comment]
Fragment syntax (to be supported in Babel 7) lets you do exactly that.
https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#jsx-fragment-syntax

If you need this now, you can do something like `React.createElement(React.Fragment, null, ...children)` which is equivalent (spreading at the end is essential to avoid the warning).
