### ISSUE TITLE
router of React

### ISSUE THREAD

**Issue by samvel451811** [facebook/react#12110]
hi.

I'm using packages like react-router and react-router-dom.

**# Does react has default router ?**
**# Is npm packages like react-router and react-router-dom is part of react ?**

**Comment by M-ZubairAhmed** [comment]
- No react doest not have a default/inbuilt router vuejs.
- they are part of react-router not react

**Comment by gaearon** [comment]
They’re not part of React, however they’re very good packages, and we know and talk to their authors to coordinate changes that might affect them.
