### ISSUE TITLE
How to know onError resons?

### ISSUE THREAD

**Issue by txiaocao** [facebook/react#12120]
```jsx
<video
onError={(event) => {
 // only has event target. but need error message
}}
/>
```

**Comment by txiaocao** [comment]
I write onError in Video Element...but the event.target.error is null???
Why this is so different from the native DOM

**Comment by spirosikmd** [comment]
Hi @txiaocao! Wouldn't something like the following work?

```jsx
<video
  onError={event => console.log(event.target.error.message)}
  src="https://example.com/bogusvideo.mp4">
</video>
```

The `error` object seems to be available in the `target`, you can try it out https://codesandbox.io/s/4xkz8ypz29

**Comment by txiaocao** [comment]
@spirosikmd 
Thank you for your reply, I do this at the moment, but when the video is just loaded, this `event.target.error` is sometimes is null. And this way is different from the original onError.

**Comment by spirosikmd** [comment]
Hi @txiaocao! Thank you for the info. Can you maybe create a reproducible example, e.g. in [codesandbox](https://codesandbox.io)? An example that throws an error after the video is loaded? That would help a lot!

**Comment by txiaocao** [comment]
The problem is not reappearing. It may be the problem of my code.
