### ISSUE TITLE
Concating react with other resources

### ISSUE THREAD

**Issue by SamKhachatryan** [facebook/react#12122]
Hi.

I want to use many libraries and frameworks in my project.

Can I concat React with other framework like angular, vue, ember...?

**Comment by aweary** [comment]
Hey @SamKhachatryan,

With a little mindfulness and planning React can integrate with almost any other view library, including the ones you've listed. Please see the [Integrating with Other Libraries](https://reactjs.org/docs/integrating-with-other-libraries.html#integrating-with-other-view-libraries) page in the docs for more information.

Thanks!
