### ISSUE TITLE
data-reactId property 

### ISSUE THREAD

**Issue by SamKhachatryan** [facebook/react#12128]
Hi.

I have many projects written with reactjs in one of this project the data-reactid property is existing. In others isn’t existing. But what is this ?

**Comment by TrySound** [comment]
@SamKhachatryan It's version of the projest
https://github.com/facebook/react/blob/master/package.json#L3

**Comment by gaearon** [comment]
It was removed from client-side render in React 15 and from server-side render in React 16.
