### ISSUE TITLE
Add Seo support in reactJS without using SSR

### ISSUE THREAD

**Issue by cruisecoders** [facebook/react#12121]
Hi Team,

Currently, I was working on SEO in my ReactJS application.So How was thinking how to add different meta tags to each route? I figured out using it with SSR but converting all applications to use SSR for SEO support is not a good option.

TIA

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by tiyunchen** [comment]
https://github.com/nfl/react-helmet

**Comment by Aashir1** [comment]
hi @cruisecoders bor how did you resolved this issue.
