### ISSUE TITLE
What is synthetic Event System?

### ISSUE THREAD

**Issue by Sundarcj** [facebook/react#12133]
Hi ,
Am new to react .So I dont know about synthetic event ,Can anyone help me to explore this topic??

**Comment by jquense** [comment]
Hi there, we try and keep the React issuer tracker focused on bug reports and feature requests. For learning about react i'd suggest reading through the documentation, specifically the section on Synthetic events: https://reactjs.org/docs/events.html#overview and if you need more info check out the support section of different avenues: https://reactjs.org/community/support.html

thanks!
