### ISSUE TITLE
How to update State in a batch with react 16 from outside the render cycle?

### ISSUE THREAD

**Issue by janbiedermann** [facebook/react#12130]
App has many state changes coming in from external sources. calling setState() for each **from outside the render cycle** hurts performance a lot, as each setState starts a new render cycle:

```
for_each (state_change in queued_state_changes) {
   state_change.target.setState(state_change.new_state); // each one starts a render cycle
}
```

What i would like to do is something like:
```
React.batchedUpdates(function() {
    for_each (state_change in queued_state_changes) {
        state_change.target.setState(state_change.state); 
    }});  // starts only one render cycle after updating all the states
```

How can i achieve this with react 16?

**Comment by gaearon** [comment]
`ReactDOM.unstable_batchedUpdates()` is what you’re looking for.

**Comment by TryingToImprove** [comment]
Why is it still in 'unstable mode'?
