### ISSUE TITLE
Meta's charset is rendered  as camel case

### ISSUE THREAD

**Issue by voodoo-child** [facebook/react#12131]
When I use react-dom's renderToString the meta property charset is rendered with camel case like this:
`<meta charSet="UTF-8"/>`
insted of
`<meta charset="UTF-8"/>`

I'm using react  and react-dom of version 16.2.0

**Comment by aweary** [comment]
Hey @voodoo-child. This is currently expected behavior. See https://github.com/facebook/react/issues/10863 and https://github.com/facebook/react/issues/11492#issuecomment-342953964 for some context on this decision.

I hope that helps, thanks!
