### ISSUE TITLE
Question: call a method of a react component instance

### ISSUE THREAD

**Issue by weskor** [facebook/react#12139]
I'm a bit new to react. If you have any advice or pointers on my current implementation, i'm always open for advice. 

**Question**
So i extended the react component class to create a new component.
```
export default class Comp extends React.Component {

    method() {
         // do something
    }

}
```

To render the component i'm using the following code:
```
const nodes = Array.from(document.querySelectorAll('.class'));
nodes.forEach((node) => {
    ReactDOM.render(<Comp/>, node)
});
```
I'm doing it like this because an element could be on different places on the page. We are currently in a transition of moving all te components to react. But we are not there yet.

So if i have multiple components on the page. How can i call the method of a specific component instance? Is there a way to get the instance by selecting the dom element? Or should i approach this in a totally different way?

**Comment by gaearon** [comment]
You can use refs:

```js
let inst;

function setInst(i) {
  inst = i;
}

ReactDOM.render(<Comp ref={setInst} />, node);
```

Technically you can also use the return value of `ReactDOM.render` to get an instance. But it comes with pitfalls. It’s a legacy API, and it assumes rendering is always synchronous. But we’re moving to a model where it’s not. We already have a case where you won’t get a value synchronously: if you start rendering a top-level component while you’re in a lifecycle method of *another* component. So you need to be cautious about using the return value and I suggest refs (as above) instead. Just keep in mind they’re not guaranteed to resolve synchronously.

Another thing to consider is that generally methods on React components are considered private. It’s fine to call some methods in rare cases (eg to interop with non-React code) but that really depends on what you’re trying to do. For example if you just want to update React component it’s better to re-render it again using `ReactDOM.render` with new props. Methods are useful for things that can only be accomplished imperatively (such as focus).
