### ISSUE TITLE
Upload files in a ftp server location using reactjs

### ISSUE THREAD

**Issue by pmidalwan** [facebook/react#12142]
Hi...

Please let me know if anyone knows how to upload files in ftp server using reactjs.

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by zGrav** [comment]
@pmidalwan https://github.com/mscdex/node-ftp ;)

**Comment by pmidalwan** [comment]
Thanks Grave. I tried it but getting below error. Actually I am new to ReactJs. Please check on below :
ERROR in ./App.jsx
Module not found: Error: Can't resolve 'fs' in 'C:\Users\pmidalwan\Desktop\react
app'
 @ ./App.jsx 47:15-28
 @ ./main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-serve
r ./main.js

**Comment by PhuocHoangMinhNguyen** [comment]
I am from 2020 and still looking for an option to upload files to an FTP server using ReactJS. I'm currently using ftp-deploy but I don't know how to connect it (which is the NodeJS package) with my ReactJS code.

**Comment by shayanmalinda** [comment]
> @pmidalwan https://github.com/mscdex/node-ftp ;)

Is this working with ReactJs or NodeJs?
