### ISSUE TITLE
Safari 11 errors when using Fragment upon hydrating

### ISSUE THREAD

**Issue by Merri** [facebook/react#12140]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
Safari 11 (both Mac OS X and iOS) throws error 130:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

I have not been able to make a reduced test case but I'm reporting this in hope that someone else also has this issue and is able to figure out what is the root cause.

Currently the best I have figured out is that when in **production** universal rendering scenario and using React.Fragment together with elements that use context (like a component connected to Redux) Safari 11 errors during client side hydration. For example, in one case I had code like this:

```jsx
    <Fragment>
        <div onClick={activateModal}>Open modal</div>
        {isModalActive && <Modal />}
    </Fragment>
```

Which errored in Safari 11 until I replaced the Fragment with a div. In this case the Modal component was also connected to Redux and returned node using `createPortal`.

In another scenario we have CMS content using a custom renderer where JSON is transformed for React rendering and with some components there is a complex context based logic where using Fragments anywhere causes error in Safari 11. Similarly the issue was fixed by replacing Fragment with a div or a span depending on case.

Currently the only things I have been able to track together is the use of Fragments and context. It is possible that the bug requires some other condition but we have a large complex project, and I'm not an Apple user, which complicates things for me. It is also very inconvenient that this bug only happens with production React and bundle which results in very unhelpful error messages.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
This is my current best **attempt** in isolating the issue, but it does **not** replicate it: https://codepen.io/Merri/pen/xYZKez

**What is the expected behavior?**
Safari 11 should not throw during hydrate when using a mixture of Fragment and context.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.2 (production only, no issue with development version)
Safari 11 (Safari 10 works fine)

**Comment by gaearon** [comment]
My best guess is you have multiple Reacts in the bundle. One of them is an older version that doesn’t support Fragments.

Having multiple versions of React (or even multiple copies of one React version) is not supported and will lead to weird issues like this.

**Comment by gaearon** [comment]
>It is also very inconvenient that this bug only happens with production React and bundle which results in very unhelpful error messages.

Why is that? Production errors include link that gives you the exact message you would have seen in development.

**Comment by Merri** [comment]
You can probably throw that one on simple frustration after dealing with several random seeming issues around Fragments for two work days.

We don't have any React in our main bundle, our current code loads React and some other deps async before booting the main bundle, which does not include React at all. So at least there are no multiple copies of React.

However we now did notice that for whatever reason Safari 11 loads React 16.1.1 and not 16.2 like every other browser does, which means there is some sort of caching issue in or with Safari (and Samsung Internet 6.2 which is the only other troublesome browser). This is very odd as our checksum cache busters should change when versions change, although the actual filename for React does remain the same.

Anyway, this did lead into progress so writing this issue was worthwhile. Thanks for the help!
