### ISSUE TITLE
process.CI check looks like a typo

### ISSUE THREAD

**Issue by istarkov** [facebook/react#12145]
`if (process.CI)` check looks like a typo, here
https://github.com/facebook/react/blob/master/scripts/tasks/eslint.js#L13

May be I'm wrong but I haven't found what `process.CI` is.
If CI is https://circleci.com/docs/2.0/env-vars/#circleci-environment-variable-descriptions it should be checked as `process.env.CI`

**Comment by gaearon** [comment]
Seems right. Want to send a fix?

**Comment by istarkov** [comment]
Done
