### ISSUE TITLE
Getting started docs are terrible

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react#12157]
I just came back to react after about a year or so of not using it and now the getting started docs are pretty much not helpful in the slightest. All the docs are now is just links to other websites without any instructions on how to get a react project running. I remember a year ago back in react 15 the docs had a step by step walkthrough for how to set up and get a project running from scratch and now they are just links to websites without react specific instructions. What happened to the docs, when did they become so useless?

There needs to be a step by step guide added back to the docs, a guide that will get you from having nothing to running it in the browser instead of just links to other websites that don't have anything to do with react. I remember back in react 15, you could run through the guide and have a hello world app running within 10 minutes no problems, I have been trying to figure it out with these new docs for over an hour now and still 0 luck getting this running. The instructions used to actually be instructions, basically saying, install this, then that, then run this command in terminal, then do this and so on. The docs now just say, well you can use this, then has a link to a site that has nothing to do with react, there is not even any sort of instruction on the react website on what to do with that, just the link without any context around it. Can these docs please be reverted to the old versions or actually create a proper getting started page to get you from nothing to running?

**Comment by milesj** [comment]
It's primarily because they want you to adopt [create-react-app](https://github.com/facebook/create-react-app) (you shouldn't need to do all the grunt work yourself). That being said, there's also this doc: https://reactjs.org/docs/add-react-to-an-existing-app.html

**Comment by gaearon** [comment]
Here is a page with three commands that are enough to set up your app:
https://reactjs.org/docs/add-react-to-a-new-app.html

What specifically is it lacking?

**Comment by RyanMitchellWilson** [comment]
I tried that method, but there were no babel files included nothing in the package.json, no config files, but when I look in the node_modules after it installed there was a ton of stuff in there that wasn't in the package.json. I don't know what that create-react-app thing does but it did not set up the project as expected. If something is in the node_modules in needs to be inside the package.json. Also I saw babel packages in my node_modules but no babel config files, theres nothing, not even in the package.json so how did they get there in the first place. 

So mainly I don't want to use create-react-app because I don't know where the node_modules are coming from if not the package.json, so I can't change anything about that and there are no config files so I can't change my babel settings. And the other way documented doesn't give you instructions in how to do it yourself. It just says use babel with a link to their website, and when you click on that there is nothing even mentioning react, so what version do I use, how do i set it up, how do I install it. Same with webpack, just says use this with a link to their website, same questions here as with babel. There just needs to be in depth instructions on how to set this up, don't just say use this with absolutely no context on how around it.

And on another note, after you use the create-react-app thing, there are no instructions on that page on how to actually run it. Back in react 15 there were 2 pages that got you from nothing to running the webapp in the browser and able to change it. Why did this get so complicated?

**Comment by jquense** [comment]
It seems like getting started with React is less of the problem for you than getting started with the JS/node ecosystem, and npm. I appreciate that that's complex and not intuitive but it's also hard to know where to draw a line for a library like React. Should the react docs include instructions for using each tool in the PL stack as well? That's definately helpful for folks in your situation however it's actively confusing for some and not helpful for folks that are already familar with the tool chains and just want to learn React

**Comment by jquense** [comment]
(i'm not trying to fight about it, just talking about hte various conflicting and cross cutting challenges that face documentation for something like REact)

**Comment by gaearon** [comment]
The way npm works, it installs both direct dependencies and transitive dependencies.

Your project depends on `react`, `react-dom`, `react-scripts`. The `react-scripts` package depends on Babel, webpack, etc. That’s where the modules are coming from.

You can run `npm ls` in the created project to see the logical dependency tree. This will tell you how it is organized.

You can also run `npm run eject`. This will move transitive dependencies like Babel directly into your project. This will help you see how everything works, but the downside is you won’t get painless updates.

For example when new versions of webpack and Babel come out, we do the work (often taking weeks) to make sure everything works together as intended, all configs are updated, there are no regressions in functionality, etc. We can do this behind the scenes while you just bump the version of a single package. However, if you eject and maintain your Babel/webpack setup yourself, you’re on your own. Which is fine, I just wanted to explain the difference between the two approaches.

>there are no instructions on that page on how to actually run it

I just pointed you to the page that lists all commands you need to run. There are four of them:

```
npm install -g create-react-app
create-react-app myapp
cd myapp 
npm start
```

**This is all you need to do, there are no extra steps.** Did they not work?

Do you feel like giving it another try now? Is there something else I could make clearer?

**Comment by gaearon** [comment]
It would be really helpful if you could post a screenshot of your terminal at the point where you got stuck right after creating the project. Maybe something is broken, and we talk past each other because we don’t see the same things on the screen. Thank you!

**Comment by gaearon** [comment]
>Back in react 15 there were 2 pages that got you from nothing to running the webapp in the browser and able to change it. Why did this get so complicated?

Isn’t this exactly pretty much this section provides?

https://reactjs.org/docs/try-react.html#minimal-html-template

Would you change something about it?

**Comment by RyanMitchellWilson** [comment]
I'm fairly familiar with js/node and npm, I've been working with React-Native for over a year now. Compare the getting started docs between react and react-native right now, react native is exactly the kind of instructions I'm talking about. https://facebook.github.io/react-native/docs/getting-started.html Go to this page and select `Building Project with Native Code`, it is literally one page that gets your from nothing to starting. React used to have a page exactly like this, and that worked perfectly. As you can see they have a create-react-native-app library but the instructions to not use that tell you exactly what to install and how to run it. Then links at the bottom to get you into the code, but the setup is done and the app is already running by the time you get to the bottom of the page. This lets you choose how you want to set it up and it is easy both ways. 

I'd prefer not to use eject because I don't want it to eject every dependency for everything I have a dependency for just to get babel and webpack out. 

All I'm saying is that for the people who don't want some script to do the work for them, it would be nice to have proper step by step instructions that get you all the way from having nothing to having it running in the browser, just like react-native provides and what react used to provide.

https://reactjs.org/docs/try-react.html this page doesn't offer much, cause for one, quickstart is above the installation section on the page and quickstart just skips the installation all together. Then when I click on `Add React to an Existing App` the instructions are not helpful, they need to tell me at the very minimum what to install, how to install it and what versions I need, then give me a link to the sites if I want to go more in depth into how it works.

**Comment by gaearon** [comment]
I am referring to the section that offers you to download an HTML file. Is that helpful? This would get you running in a second. It’s not a production-ready setup but it gives you a quick start with Babel and no extra tooling. 

I understand you’re asking about a full guide. The one we had actually was woefully incomplete (for example the crucial difference between development and production versions wasn’t explained). It was also often getting outdated. People were complaining about it too (“why do I have to do so many steps to get a project running?”)

We’ve pivoted the installation guides in a different direction. I’m sorry you preferred the old one, but you can find plenty guides for setting up webpack and Babel on the web.

I’m sorry if this isn’t quite helpful. Maybe when underlying tools are easier to configure without doing 20 steps (for example webpack 4 promises to be an improvement) we can add a guide to the “adding React to existing app” guide. But again, the links from that page give you really well-written guides from Babel and webpack themselves, and I recommend you to check them out. They’re much better introductions to those tools than we could have written.

**Comment by RyanMitchellWilson** [comment]
Ok I get that you want to help people who don't want to deal with a bunch of steps to set it up but isn't that what the whole create-react-app thing does? Shouldn't the other way be explained in more depth for the people who still do want to use the step by step version? How hard would it to add under the babel and webpack sections just a quick few line explanation on how to install it? Like under babel it just says do `npm install whatever` and such then have a link to the babel page where the person can go to get a full understanding, but that way they never have to leave your webpage to set up the project.

You've pointed a couple things that weren't obvious on the page that can help me but all I'm asking for here is for that add react to existing project page to be fixed and get little more detail so that someone going through your getting started doesn't have to jump between multiple websites just to get a project up and running.

**Comment by gaearon** [comment]
I understand, that’s valuable feedback. I’m happy to review a PR to the docs that does that. If nobody else does it, I’ll probably look into myself after webpack 4 is out because it makes many of these steps more straightforward. Another thing to consider is that people who want to configure everything manually often have wildly different setups (e.g. different backends, different development setups, etc). As soon as we write a specific step-by-step webpack-focused guide people will start asking: but what do I do with Rails? with .NET? what if I want to use Parcel instead of webpack? or Rollup? does React promote webpack? Et cetera. And if we try to satisfy those requests by making the guide more generic and outsourcing specific documentation to different tools’ own docs (that cover those scenarios) we’re back to where we’re at.

**Comment by gaearon** [comment]
>I could follow along, never leave the site and get a react project up and running

Again, you *can* do that with a single command. I understand you’re looking for something different, and I see where your frustration is coming from. I hope we can address this in the future. But I don’t think it’s entirely fair to say you can’t get a project running without leaving the website. In fact, I see many more people able to get projects running than from the old instructions. Of course some people will always be alienated no matter which choice we make.
