### ISSUE TITLE
react-test-renderer: Asynchronous rendering guarantees?

### ISSUE THREAD

**Issue by ajhyndman** [facebook/react#12153]
**Do you want to request a *feature* or report a *bug*?**

I think this is just a question.

As I understand it, React's newer *Fiber* architecture introduces an asynchronous rendering pipeline, which allows for better prioritisation of work.  I'm also aware that in version 16, React is still expected to render synchronously.

Looking forward though, when using `react-test-renderer` (especially the [ReactTestInstance](https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactTestRenderer.js#L466-L512) helper APIs), what guarantees are safe for a developer to lean on?

After creating a test-renderer instance, is it safe to immediately introspect the instance to look for a child node with a given type?  Does this differ from components with user-space asynchrony?

For instance, if I have a class component with a child node that I want to make a test assertion against, is this safe?  If not, is there a safe way to flush pending reconciler changes, or check for pending work?

```
const renderer = ReactTestRenderer.create(<MyComponent />);
const childInstance = renderer.root.findByType(ChildNode).instance;
```

Currently I am experiencing intermittent (1 in 50 or so) failures in test assertions that look like this.  The error output looks like:

```
FAIL path/to/MyComponent/test.jsx (8.116s)
● MyComponent › test assertion against child node instance

No instances found with node type: "ChildNode"

at expectOne (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8161:9)
at ReactTestInstance.findByType (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8009:12)
...
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am seeing this failure when running `react@16.0.0` with `react-test-renderer@16.0.0`, in `jest@22.1.4` while running in `node@8.3.0`.

**Comment by gaearon** [comment]
Test renderer is expected to always behave synchronously (similar to ReactDOM in compatibility mode, which is on in React 16). Going forward I also expect this to stay true. We’ll need a reproducing case if something is wrong.

**Comment by ajhyndman** [comment]
Thanks for the quick response!

Now that I'm confident in the intended behaviour, I'll close this until I can reproduce more reliably.
