### ISSUE TITLE
Typescript definition for SFC returning fragment/string

### ISSUE THREAD

**Issue by FredyC** [facebook/react#12155]
**Do you want to request a *feature* or report a *bug*?**

Most likely a **bug**

**What is the current behavior?**

https://codesandbox.io/s/r555ro878p

If you open that sandbox and wait for a compiler to catch up, you see that `TextReturningComponent` has an error. It is expecting `ReactElement<any> | null` to be returned.

```typescript
const TextReturningComponent: React.SFC = () => 'sometext'
```

**What is the expected behavior?**

Based on the [blog post](https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings) it should be possible to have a component like that. Is that correct?

Looking at the [type definition for](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L292) `render` method it has return type `ReactNode` which is correct. However, the SFC declaration looks like this...

```typescript
interface StatelessComponent<P = {}> {
  (props: P & { children?: ReactNode }, context?: any): ReactElement<any> | null;
}
```

I assume this is just an oversight and there should be `ReactNode` type as well? In case that's true, I am able to create PR for that. Correct me if I am missing something here, please :)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
"react": "^16.2.0",
"@types/react": "16.0.36",
```

**Comment by FredyC** [comment]
I've just noticed that returning fragment works just fine (could be a current workaround) 

```
const TextReturningComponent: React.SFC = () =>
  <>
    'sometext'
  </>
```

Looking closely at this, the fragment return type is `JSX.Element` which is declared as `interface Element extends React.ReactElement<any> { }` and that's correct. However, a string is just a string.

**Comment by TrySound** [comment]
@FredyC Ask https://github.com/DefinitelyTyped/DefinitelyTyped. This repo is not responsible for typescript definitions.

**Comment by FredyC** [comment]
I see. I thought there is some kind of approval for React typings coming from here. Nevermind then.

**Comment by gaearon** [comment]
A functional component can return:

* a string
* a number
* a React element
* an array
* null

**Comment by gaearon** [comment]
Returning a boolean (at least false) probably also works but that’s useless.

**Comment by TrySound** [comment]
@gaearon Useful for conditional rendering. I don't like ternaries with jsx.
```js
<div>{false && <div></div>}</div>
```

**Comment by gaearon** [comment]
Yes, but I'm referring to the return value of the function. I don't think this is very useful at the root level because you can always `return null`.

**Comment by FredyC** [comment]
@gaearon Thanks for the confirmation.

PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23422 (in case someone wants to chime in).

**Comment by gaearon** [comment]
Also, note that there are currently no differences between what an SFC can return, and what a class component can return in `render`. They have full feature parity.
