### ISSUE TITLE
react16 unstable_renderSubtreeIntoContainer execution order

### ISSUE THREAD

**Issue by doronbrikman** [facebook/react#12160]
**What is the current behavior?**
From react16 `unstable_renderSubtreeIntoContainer` execution order has been changed.

I know it's an old API and `createPortal` has replaced it and I'm starting to switch to it in my codebase. But I'm still depends on some libraries that use the old API.

So, just for the matter of knowing what has change:
https://codesandbox.io/s/6yx2p61nzz

I wrote in the link the order of which the functions has been executed in react15 and 16.
As you can see in react16 the `componentDidMount` of the `<App />` is calling before his children gets mounted and in react15 it's called only after.

Is this behavior change intentional?

**Comment by gaearon** [comment]
Indeed, this is intentional. I know it is frustrating if you depend on that specific API but doing this has allowed us to solve many nasty issues that the old API used to suffer from. My recommendation is to switch to portals.
