### ISSUE TITLE
<input> Form causes React to crash

### ISSUE THREAD

**Issue by nickbar86** [facebook/react#12174]
File a new Bug.
When adding an input form element in a Component, React crashes. This is caused in Mozilla Firefox Browsers version: 20.0.1 for React version:16.0.0 and higher.
```
import React from "react";
export default () => {
  return (
   <div>
      <input type="text" />
    </div>
  )
}
```

**Comment by aweary** [comment]
> This is caused in Mozilla Firefox Browsers version: 20.0.1

Firefox 20.0.1 was released almost 5 years ago, is there a specific reason you're running such an old version? The [caniuse usage statistics](https://caniuse.com/usage-table) puts 20.0.1 at approximately 0% of total usage, which means there's no significant group of people still using that version.

Can you please try to update to a newer version and try again? It's possible there's a bug or incompatibility with such an old version, but given it's age it's not likely that we'd spend any time trying to resolve it.

**Comment by nickbar86** [comment]
We are a maritime company that manages a fleet of hundreds of vessels. That means upgrading is not an option. Furthermore a lot of legacy applications run on board, thus we need to be compatible all the time. This is the primary reason we chose React as development framework.

**Comment by aweary** [comment]
@nickbar86 thanks for the context, that's an interesting use-case. While React does aim to have broad browser support, providing support to legacy browsers isn't a primary goal for the library; for example, we dropped support [over two years ago](https://reactjs.org/blog/2016/01/12/discontinuing-ie8-support.html). If you're needs include a library with long-term support for legacy platforms then React may not be the best fit.

If you can provide some more specific details about the error(s) you're getting I'm happy to try and figure out a workaround, but it's not likely that we'd backport any potential fixes to older versions. You may want to consider forking the library and maintaining your own version of it.
