### ISSUE TITLE
Flow cannot find react-dom's hydrate function

### ISSUE THREAD

**Issue by callumlocke** [facebook/react#12175]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Flow can't find react-dom's `hydrate` function.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Try the following code in a project using Flow:

```js
// @flow

import { hydrate } from 'react-dom'; // Flow error: This module has no named export called `hydrate`.

// calling it as a method on the default export also fails:
import ReactDOM from 'react-dom';
ReactDOM.hydrate(); // Flow error: property `hydrate` not found in ReactDOM
```

**What is the expected behavior?**

It should not cause any Flow errors.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react-dom 16.2.0
node 8.9.4
flow 0.64.0

I don't think it has ever worked.

**Comment by gaearon** [comment]
Flow contains built-in React typings so it should be fixed there.
