### ISSUE TITLE
Is there a way to directly use a function like `camelCasedStyleProps => cssString` from React?

### ISSUE THREAD

**Issue by webketje** [facebook/react#12176]
#### Case (nb: somewhat related to #11706)
I'm tasked with integrating a WYSIWYG which uses an `<iframe>` which is ofc. React-agnostic. We want to use the same `theme` object in the iframe as we use for style props on the website for consistency. The properties in the theme object are, as per React convention, camelcased (e.g. paddingTop). However the CSS that needs to be put in this iframe needs to be 'CSS-standard-cased'.

#### Question
Is there a way to directly use a function like `camelCasedStyleProps => cssString` from React?
I'm guessing this is handled in the source's CSSPropertyOperations.js, but afaik there is no direct export of this?

**Comment by jquense** [comment]
No there isn't anyway to access this, sicne it's an internal API, there are plenty libraries on npm tho that you can grab to handle this which aren't particularlly big on size. personally I use https://github.com/react-bootstrap/dom-helpers

**Comment by webketje** [comment]
@jquense thx for the pointer!
