### ISSUE TITLE
to access refs, we recommend the callback pattern instead... How?

### ISSUE THREAD

**Issue by wzup** [facebook/react#12184]
What do you mean by that? Here https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

> If you’re currently using this.refs.textInput to access refs, we recommend the callback pattern instead

What callback pattern do you mean? How do you mean to use it with refs?

**Comment by hrachmkr** [comment]
instead of ref = "someRef" use ref = {ref => (this.someRef = ref)

**Comment by wzup** [comment]
I do so. But the issue is that it is not saved in `this.refs`. The value is saved in `this.{value}`
Is this correct behavior?

If I do so:
```
<input name="name" type="text" ref={node => { this.node = node }} defaultValue={null} />
```
I get:
```
this.refs = {}
```
but
```
this.node = node
```

**Comment by TrySound** [comment]
@wzup You explicitly set `this.node`, why do you expect anything is `this.refs`? `this.refs` is string refs only behavior. Don't rely on it. Use callbacks. Also there will be new ref api soon.

**Comment by gaearon** [comment]
>What callback pattern do you mean? 

The one described everywhere else on this page.

>The value is saved in this.{value} Is this correct behavior?

Yes because this is where you set it. The point of callback refs is that *they are completely in your control*. They don’t magically appear on some React-controlled field. 

Hope this helps!
