### ISSUE TITLE
Request for Filipino Translation

### ISSUE THREAD

**Issue by iam-strings** [facebook/react#12180]
Hi,

I would like to contribute on this project thru translation. I would like to translate the necessary files to Filipino.

Hoping for your response.

Thanks..

**Comment by aweary** [comment]
Hey @iam-strings, it looks like someone else opened a similar issue in the website's repo (https://github.com/reactjs/reactjs.org/issues/597), which is the right place for this. Please see [my comment in that issue](https://github.com/reactjs/reactjs.org/issues/597#issuecomment-363986953). Thanks!
