### ISSUE TITLE
How to stub document object on Link click

### ISSUE THREAD

**Issue by vinikatyal** [facebook/react#12194]
Hi,

I am trying to mimic this function its being called on Link click React

```
getActiveClass(e, navData) {
        const elements = document.body.getElementsByClassName('CAMNavPanel-rewardsMenu')[0].getElementsByTagName('li');

        console.log('Elements of getElementsByTagName', elements);

        for (let i = 0; i < elements.length; i += 1) {
            elements[i].className = '';
        }

        this.setState({ currentView: navData.url }, () => {
            if (get(navData, 'scrollIntoView')) {
                document.getElementsByClassName(navData.scrollIntoView)[0].scrollIntoView();
            }
        });
    }
```

`describe('CAMNavPanelListItem with isRedirect false plus highlight li', () => {
    let wrapper;
    let a;

    const navData = {
        title: 'My Orders',
        isRedirect: false,
        isExternalLink: false,
        url: '/orders',
    };

    const location = {
        pathname: '/orders',
        basename: '',
    };

    beforeEach(() => {
        a = sinon.stub(document.body, 'getElementsByClassName');
        const li = {
            getElementsByTagName: sinon.stub(),
        };
        const eleme = a.withArgs('CAMNavPanel-rewardsMenu').returns([li]);
        console.log('Elements --------', eleme.getCall(0));

        wrapper = shallow(
            <CAMNavPanelListItem
                navData={navData}
                location={location}
                />,
        );
        wrapper.setState({ currentView: navData.url });
    });

    it('should render CAMNavPanelListItem with Link as well', () => {
        expect(wrapper.find('li')).to.have.length(1);
        expect(wrapper.find('li').hasClass('active')).to.equal(true);
        expect(wrapper.find('Link')).to.have.length(1);
    });

    it('should click and activate activeClass', () => {
        wrapper.find('Link').simulate('click', { button: 0 });
    });

    afterEach(() => {
        wrapper.unmount();
        a.restore();
    });
});`

Please help I am getting getElementsByTagName undefined.

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
