### ISSUE TITLE
BUG: gulp-util is deprecated in react 0.14.3

### ISSUE THREAD

**Issue by azamatz** [facebook/react#12196]
Hi, everyone! 

I have a problem with react 0.14.3, after run command "npm install". 
Log: 
[npm install] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

For resolve this conflict in my project i see some variant:
1.  Migrate to new react version - it's a dangerous and pain variant
2.  Fix react 0.14.3 source code, change gulp-util use to some packages from instruction (https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5). Is it possible? 

Help me!
PS: Sorry, my english.

**Comment by gaearon** [comment]
It’s not a runtime dependency. You don’t need it to *use* React.

If you run `npm install` in React’s own folder, that’s a mistake. You don’t need to install React’s development dependencies to use it.

It’s hard to say more without more context into what you’re doing. But this message is irrelevant to React, and while we recommend keeping it up to date, this warning is completely safe to ignore.
