### ISSUE TITLE
rowSpan and colSpan render with inconsistent case

### ISSUE THREAD

**Issue by japgolly** [facebook/react#12202]
`rowSpan` is JS renders to `rowspan` in DOM, but `colSpan` is JS renders to `colSpan`.
I'm not sure which is preferred but it should be consistent, right?

```js
class Hello extends React.Component {
  render() {
    return (<table><tbody><tr>
        <td rowSpan="1" colSpan="1">.</td>
        </tr></tbody></table>);
  }
}

console.log(ReactDOMServer.renderToString(  <Hello />  ));
```
returns:
```html
<table data-reactroot=""><tbody><tr><td rowspan="1" colSpan="1">.</td></tr></tbody></table>
```

**Comment by gaearon** [comment]
It is an implementation detail and may change between releases. In practice there's no difference because HTML is case-insensitive.

**Comment by andrewkikot** [comment]
@japgolly did you find any workarounds for this..?

**Comment by japgolly** [comment]
Hi @andrewkikot. Nah I didn't but to be fair I didn't try either. I'm the author and maintainer of scalajs-react which enables people to write React code in the Scala language and compile it to JS. Said library's unit tests breaking is the only reason I came across this issue; it didn't have any functional impact for me so I just modified the unit tests and moved on. Sorry that's not much help.

**Comment by andrewkikot** [comment]
@japgolly, that's ok, thanks for replying anyway :)

**Comment by adjenks** [comment]
My document is actually xhtml, so capitalization matters and this broke my page.
