### ISSUE TITLE
Prefix private API fields on the context object

### ISSUE THREAD

**Issue by gaearon** [facebook/react#12203]
Which of these are safe to read?
It's not obvious to me.

<img width="378" alt="screen shot 2018-02-10 at 13 43 00" src="https://user-images.githubusercontent.com/810438/36062649-5b22aac2-0e68-11e8-971f-6fc763aaab47.png">

Even if we don't document the others, people will think they're all safe. We should prefix unsafe ones with underscores (or even longer prefixes like `__internal`).

**Comment by aweary** [comment]
Done in https://github.com/facebook/react/pull/12358
