### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string

### ISSUE THREAD

**Issue by PterPmnta** [facebook/react#12214]
I'm taking a tutorial to learn React JS, everything was fine, for days I could run an example, simple, carrying out a recommended basic configuration, plus a few more add-ons that I add to recognize the Javascript version.

After several days of no longer reviewing the project, but it is working correctly, when executing the command, I do not see any error, but it does not show anything in the browser, only multiple errors appear in the console of this one.

I have uninstalled and reinstalled reac and react-dom, and the problem still persists, try a new project cloning it from a friend, and it works normally, and it only copied the same structure of mine.

>Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

>The above error occurred in one of your React components: Consider adding an error boundary to your tree to customize error handling behavior.

![issues](https://i.stack.imgur.com/brVbL.jpg)

![project structure](https://i.stack.imgur.com/zSovO.jpg)

### Packge.json

```
{
  "name": "prueba",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node server.js",
    "dev": "concurrently \"node server.js\" \"webpack -w\" "
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "serve-static": "^1.13.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "concurrently": "^3.5.1",
    "eslint": "^4.9.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.7.0",
    "webpack": "^3.10.0"
  }
}
```

### webpack.config.js
```
const path = require('path');

const config = {
    entry: './src/index.jsx',
    output: {
        path: path.resolve('js'),
        filename: 'bundle.js'
    },

    module: {
        rules: [
            {                
                test: /.jsx$/,
                use:{
                    loader:'babel-loader'
                }
            }
        ]
    }
}

module.exports = config;
```

### app.jsx
```
import React, {Component} from 'react';
import {render} from 'react-dom';

class App extends Component{
    render(){
        return(
            <div>                
                <h1>Mi Aplicacion React Js</h1>
                <h3>Probando la exportacion</h3>
            </div>
        )       
    }
}

export default App;
```

### index.jsx
```
import React, { Component } from 'react';
import { render } from 'react-dom';
import {App} from './components/app.jsx';

render(
    <App/>,
    document.getElementById('appStart')
)
```

### index.html
```
<!DOCTYPE html>

<html>

    <head>
        <meta charset="utf-8">
        <title>Aprendiendo React</title>
    </head>

    <body>
        <div id="appStart"></div>
        <script src="js/bundle.js"></script>
    </body>

</html>
```

**Comment by ShiYiYa** [comment]
import  App from './components/app.jsx';

**Comment by gaearon** [comment]
The error message says "you might have mixed up default and named exports".

```js
export default App;
```

is a *default* export. To import it, you need to use the *default* import

```js
import App from './components/app.jsx';
```

Note the lack of curly braces.

----


If you use curly braces when importing, you're importing a *named* import called `App`:

```js
import {App} from './components/app.jsx';
```

In this case there needs to be a corresponding *named* export called `App`:

```js
export {App};
```

Note the presence of curly braces in both places.

----

Learn more: https://stackoverflow.com/a/36796281/458193

**Comment by PterPmnta** [comment]
@ShiYiYa dont work, @gaearon why close the question, the issue dont solved yet

**Comment by gaearon** [comment]
@PterPmnta I have just answered your question, the problem you're seeing is because you are mixing a default export with a named import. Use one or the other. If it doesn't help, post more details about what exactly doesn't work—we can't guess that. :-)

**Comment by PterPmnta** [comment]
@gaearon still the same problem, i dont know why still happened

**Comment by gaearon** [comment]
Maybe you didn't recompile or something. It's hard to say for sure without having a full reproducible project that we can download and try.

**Comment by PterPmnta** [comment]
@gaearon wait a minute, i am upload the project, give me a second

**Comment by gaearon** [comment]
To clarify, the specific fix I'm suggesting is to replace this:

```js
import {App} from './components/app.jsx';
```

with this:

```js
import App from './components/app.jsx';
```

Then rebuild. If you still see the problem please post your full code and screenshots again.

**Comment by PterPmnta** [comment]
@gaearon i ame this change, but still issue

**Comment by PterPmnta** [comment]
@gaearon  cheack the repo [react scaffold 2](https://github.com/PterPmnta/React-Scaffold-2)

**Comment by gaearon** [comment]
As I asked you earlier please provide exact instructions for how to reproduce the issue, and screenshots.

It is hard for people to help when there is no information about what error you are seeing. Is it the same error? Has it changed?

**Comment by PterPmnta** [comment]
@gaearon the error is the same, just write `npm run dev`

`"dev": "concurrently \"node server.js\" \"webpack -w\" "`

**Comment by gaearon** [comment]
For some reason even if I change code in `src/index.jsx` I still get the old compiled bundle. I don't know why, but it's unrelated to React. Your code looks correct but something in your build process is caching the output file.

**Comment by PterPmnta** [comment]
@gaearon  i solved, an user answer in stackoverflow this [answer](https://stackoverflow.com/questions/48738761/warning-react-createelement-type-is-invalid-bundle-js/48738794?noredirect=1#comment84477644_48738794
)

**Comment by ashikjs** [comment]
@gaearon  Thanks a lot it save my day 💯

**Comment by Htnew** [comment]
This is mainly due to the wrong import/export path, just change to the correct path then the error gone.

**Comment by abdulkhaliquem9** [comment]
In my case, It was happening as I was importing **Provider** from **redux** instead of **react-redux**
`<strike>import {Provider} from 'redux'</strike>`
import {Provider} from 'react-redux'

**Comment by MANTENN** [comment]
For me it was to wrap the context consumer with a class rather than a stateless component.

**Comment by joladubu** [comment]
> In my case, It was happening as I was importing **Provider** from **redux** instead of **react-redux**
> `import {Provider} from 'redux'`
> import {Provider} from 'react-redux'

Thanks @abdulkhaliquem9  U saved my ass

**Comment by rashid-aslam** [comment]
@gaearon This error is common for new React developers and some times even for experienced ones. It will be a great help if the warning message can also include the **import** or **require** statement this warning originated.

**Comment by mrsmile-lp** [comment]
Hi guys, I have the same issue. No one solution above is not help...
`import "isomorphic-fetch";
import "babel-polyfill";
import React from "react";
import { hot } from "react-hot-loader";
import { Route, Link, Switch, Redirect } from 'react-router-dom';

import Header from "./components/Header";
import HomePage from "./pages/HomePage";
import MoviesList from "./components/MoviesList";
import MoviePage from "./pages/MoviePage";

const Root = ({ Router, location, context }) => (
  
  <Router location={location} context={context}>
    <div>
      <Header />
      <Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="movies/:id" component={MoviePage} />
        <Redirect to="/" />
      </Switch>
      <MoviesList />
    </div>
  </Router>
  );

Root.defaultProps = {
  location: null,
  context: null,
};

export default hot(module)(Root);
`

The issue is here....

**Comment by rudenco** [comment]
@gaearon - How can we possibily check such dependencies - incorrect library used ?

**Comment by rudenco** [comment]
@PterPmnta  - thank you for posting this question and being persistent to solve it. This helped to solve my issue too . I did suspect there could be library dependencies but did not know ho to check it , the only Approach I did was to reinstall multiple times the libraries.

**Comment by crllrd** [comment]
> Hi guys, I have the same issue. No one solution above is not help...
> 
> ```
> import "isomorphic-fetch";
> import "babel-polyfill";
> import React from "react";
> import { hot } from "react-hot-loader";
> import { Route, Link, Switch, Redirect } from 'react-router-dom';
> 
> import Header from "./components/Header";
> import HomePage from "./pages/HomePage";
> import MoviesList from "./components/MoviesList";
> import MoviePage from "./pages/MoviePage";
> 
> const Root = ({ Router, location, context }) => (
>   
>   <Router location={location} context={context}>
>     <div>
>       <Header />
>       <Switch>
>         <Route exact path="/" component={HomePage} />
>         <Route path="movies/:id" component={MoviePage} />
>         <Redirect to="/" />
>       </Switch>
>       <MoviesList />
>     </div>
>   </Router>
>   );
> 
> Root.defaultProps = {
>   location: null,
>   context: null,
> };
> 
> export default hot(module)(Root);
> ```
> 
> The issue is here....
____
The problem is definitly with exporting and importing things, as mentioned above. Anyway.

Have you tried to import components in [this](https://github.com/facebook/react/issues/12214#issuecomment-364821442) manner ? 
`
import { default as Header } from "./components/Header"
`

If you're dealing with a large project, I would also suggest looking into your index files. It is possible that components should be exported from there, in your project.

If it doesn't work, can you please provide more information about your problem? Like sandbox, Codepen, or something similar?

**Comment by ahmedakhtar11** [comment]
I had the same problem and turned out that I was importing
both the NPM Package for Bootstrap and importing the React Bootstrap Link as well.

I had both:
import { Modal, Button } from **'react-bootstrap';**
**and**
import **"bootstrap/dist/css/bootstrap.min.css";**

I just had to delete the additional React Bootstrap Link.

Such a silly mistake.

**Comment by Gameonn** [comment]
I am still facing this issue while using **High order components** in react

**Comment by valen214** [comment]
This issue happens during hot reload when a file has new import
