### ISSUE TITLE
Is it ok I put random things in div.root?

### ISSUE THREAD

**Issue by rockmandash** [facebook/react#12226]
Can I put some initial text in div.root element? (eg. p tag with text, div, canvas....)
Because I saw many people put their entire rendered markup in div.root to hack seo.
So when
`ReactDOM.render( <App />, document.getElementById('root'));`
What will happen with div.root? Is it's childNode all being erased?
If it is, then I can put random things in it, am I right?
Thank for your patience!!

**Comment by blling** [comment]
Root DOM is the begaining of React, it will all managed by React, so you can not put any DOM in it, instead you can put any React Element in App.

**Comment by rockmandash** [comment]
So is there any way I can do like this
`ReactDOM.render( <App />, document.getElementById('root'), () => {
  // This is a callback before React actually append child in div.root
  // so I can delete my root element first!
  // so there won't be any problem
  // so my seo hack work!
  var myNode = document.getElementById("root");
  while (myNode.firstChild) {
      myNode.removeChild(myNode.firstChild);
  }
});`
Is it possible?

**Comment by rockmandash** [comment]
So is there any way I can do like this
```
ReactDOM.render( <App />, document.getElementById('root'), () => {
  // This is a callback before React actually append child in div.root
  // so I can delete my root element first!
  // so there won't be any problem
  // so my seo hack work!
  var myNode = document.getElementById("root");
  while (myNode.firstChild) {
      myNode.removeChild(myNode.firstChild);
  }
});
```
Is it possible?

**Comment by rockmandash** [comment]
I just created a pen.
It seems fine when there is random thing in it.
[![Edit React render myth](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4q1v6402k4)

**Comment by aweary** [comment]
> Because I saw many people put their entire rendered markup in div.root to hack seo.

Most search engine crawlers have no problem parsing client-rendered applications, but you can definitely send down rendered markup using [`ReactDOMServer`](https://reactjs.org/docs/react-dom-server.html).

> If it is, then I can put random things in it, am I right?

You can feel free to put whatever you want inside the root container, as React will simply clear out any child nodes before rendering.

https://github.com/facebook/react/blob/1fd205ad2d101f441622c9bb7e2ccb480281e0a0/packages/react-dom/src/client/ReactDOM.js#L1002-L1023

If you did server rendering with `ReactDOMServer` you would instead use `[ReactDOM.hydrate](https://reactjs.org/docs/react-dom.html#hydrate)`, which would avoid the cost of throwing away all the markup and starting from scratch.

**Comment by rockmandash** [comment]
@aweary Thank you very much!!
