### ISSUE TITLE
Uncaught TypeError: (0 , _arrays2.default) is not a function

### ISSUE THREAD

**Issue by Prolatus** [facebook/react#12223]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I got following behavior if i import SearchArea.js in Index.js

**SearchArea.js**
```
import React, { Component } from 'react';
import SearchAreaClasses from './SearchArea.css';

class SearchArea extends Component {
    state = {
        showFederalState: false
    };

    render() {
        
        return (
            <div>
                <div className={SearchAreaClasses.SearchBarContainer}>
                    <div className={SearchAreaClasses.SearchBarContent}>

                        <div className={SearchAreaClasses.SearchBarColumn}>
                            <div className={SearchAreaClasses.SearchBarColumnLabel}>Federal State</div>
                        </div>

                    </div>
                </div>
            </div>
        )
    }
}

export default SearchArea;
```
Index.js
```
import SearchArea from './SearchArea/SearchArea';
...
render() {
  return(
    <SearchArea />
  )
}
```

I got following error on the console:
```
Uncaught TypeError: (0 , _arrays2.default) is not a function
    at new SearchArea (SearchArea.js?eda9:4)
```

But when i remove from SearchArea.js the defined state,
```
state = {
        showFederalState: false
};
```
it work's like a charm.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v 16.1.1
Google Chrome 64.0.3282.119
Mac OS 10.13.3

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
