### ISSUE TITLE
New Chrome iframe spec requires allow attribute to use devices

### ISSUE THREAD

**Issue by RomainGoncalves** [facebook/react#12225]
**Do you want to request a *feature* or report a *bug*?**
Not sure, maybe more on the feature side

**What is the current behavior?**
When opening an iframe to a third party site, I need access to the user's camera. The new specs for Chrome states that since version 64, we need to add the `allow` attribute in order to have access to things like camera or microphone.
However React (15.6.1) does not recognise this attribute and removes it. Therefore I don't have access to the user's camera.

```html
<iframe
           title="Open identification process"
           src="thirdparty.com"
           frameBorder="0"
           width="600"
           height="800"
           allow="camera; microphone"
         />
```

### Error displayed in console:
`Warning: Unknown prop `allow` on <iframe> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

**What is the expected behavior?**
This tag should be known

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version: 15.6.1 (no real possibilities to change to 16 yet)
Chrome: Version 64.0.3282.140 (Official Build) (64-bit)
OS: MacOS Sierra

Sorry if this was already reported. I couldn't find another issue mentioning this.

**Comment by aweary** [comment]
Hey @RomainGoncalves! This behavior was changed with the React 16 release. You can see the blog post [DOM Attributes in React 16](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html) for details.

I know you said you can't updating to v16 just yet, but it's unlikely that we'll be making any more 15.x releases with changes to the attribute whitelist. We definitely recommend updating soon if you can (lots of great stuff coming!) but until then you can potentially use `dangerouslySetInnerHTML` as a workaround.
