### ISSUE TITLE
Using ReactPortal with a newly opened window

### ISSUE THREAD

**Issue by Pjata** [facebook/react#12231]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
There is no interactivity with an highly used React component (ReactTable) in a newly opened window injected via React Portal.
Code based on [this article](https://hackernoon.com/using-a-react-16-portal-to-do-something-cool-2a2d627b0202)
https://codesandbox.io/s/84035j8168

1. Click the open button
2. Table opens in a new window.
3. No interactivity

**What is the expected behavior?**
The component should work as in "docked mode".
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.2.0, Chrome

**Comment by gaearon** [comment]
This is not a bug — please see my explanation here:
https://github.com/facebook/react/issues/12355#issuecomment-410996235

**Comment by Pjata** [comment]
Thank you, its clear now!
