### ISSUE TITLE
There should be a way to hint hydration on how to reuse DOM nodes.

### ISSUE THREAD

**Issue by oalexandersson** [facebook/react#12232]
**Do you want to request a *feature* or report a *bug*?**
Feature Request (since the current, in my opinion rather weird, behaviour is WAI).

**What is the current behavior?**
https://github.com/oalexandersson/react-16-server-client-diff

If I render additional DOM on the client, when hydrating, it works partially, but my new DOM nodes get confused with the ones rendered by the server even though they are an obvious addition. Server rendered elements get reused with css classes and all. I would argue that this behavior would be acceptable if the component's state matched with the server-side state, but in my example above I use a state change in componentWillMount to drive the diff.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Clone https://github.com/oalexandersson/react-16-server-client-diff
2. Run `yarn start` or `npm start`

**What is the expected behavior?**
If the current behavior is truly what was intended, I would like a way to explicitly hint React on how to hydrate specific nodes. My suggestion is that if nodes have a `key` property, reuse only if its value matches, similar to how React knows how to handle changes in arrays. I have very limited knowledge about how the hydration works (maybe that shows), but afaik this would have virtually no performance impact, and still allow for the client to do pure additions to the DOM.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Using React 16.2. Well, yes, it worked in React 15 :)

**Comment by gaearon** [comment]
The current behavior is intentional, although there are escape hatches.
Please see https://reactjs.org/docs/react-dom.html#hydrate:

>React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.
>
>If a single element’s attribute or text content is unavoidably different between the server and the client (for example, a timestamp), you may silence the warning by adding `suppressHydrationWarning={true}` to the element. It only works one level deep, and is intended to be an escape hatch. Don’t overuse it. Unless it’s text content, React still won’t attempt to patch it up, so it may remain inconsistent until future updates.
>
>**If you intentionally need to render something different on the server and the client, you can do a two-pass rendering. Components that render something different on the client can read a state variable like `this.state.isClient`, which you can set to true in `componentDidMount()`. This way the initial render pass will render the same content as the server, avoiding mismatches, but an additional pass will happen synchronously right after hydration.** Note that this approach will make your components slower because they have to render twice, so use it with caution.
>
>Remember to be mindful of user experience on slow connections. The JavaScript code may load significantly later than the initial HTML render, so if you render something different in the client-only pass, the transition can be jarring. However, if executed well, it may be beneficial to render a “shell” of the application on the server, and only show some of the extra widgets on the client. To learn how to do this without getting the markup mismatch issues, refer to the explanation in the previous paragraph.


Hope this helps!
