### ISSUE TITLE
Extracting a Context Stack

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#12235]
A useful feature of context is creating a custom stack of things to see what your component is embedded in side.

I think the primary use case is logging explicitly.

Currently that is pretty expensive to maintain just *in case* you need it. See #12234 as an example.

We could provide an API that lazily extracts a whole path of contexts from the tree.

```js
<FooContext.Provider value={"foo"}>
  <FooContext.Provider value={"bar"}>
    <FooContext.Provider value={"baz"}>
      <App />
    </FooContext.Provider>
  </FooContext.Provider>
</FooContext.Provider>
```

```js
class App extends React.Component {
  log() {
    var stack = this.getContextStack(FooContext);
    logToServer(stack); // ["foo", "bar", "baz"]
  }
  render() {
    return <div onClick={this.log} />;
  }
}
```

It would basically synchronously rerender the shortest path to recreate the context at the time of the call to create the stack lazily.

cc @acdlite

**Comment by acdlite** [comment]
Can you think of another use case besides logging? I'm trying to think of one.

**Comment by sebmarkbage** [comment]
I think it is like component stack, Error.stack etc. It's mostly for logging in some form. Either in an event handler or commit phase life-cycle.

I could contrive a use case that would use this stack in render but I don't have a real one in mind.

**Comment by sebmarkbage** [comment]
I am nervous about this since "read" APIs like findDOMNode and isMounted have been very problematic in the past.

**Comment by milesj** [comment]
What if the stack was passed to the consumer? Like as the 2nd argument.

```
<Consumer>
  {(value, stack) => <Comp />}
</Consumer>
```

**Comment by sebmarkbage** [comment]
This is going to be an expensive operation so we want to make sure that a) it's not implicitly there. it has to be opt-in. b) it is ideally not extracted in the render pass.

**Comment by cloudever** [comment]
I think it's unused feature and similar **debugging features** might be implemented in the DevTools.

**Comment by gaearon** [comment]
Looks like we didn't come back to this. Curiously Server Context will have something similar because it's needed for refetch though.
