### ISSUE TITLE
New React component definition with autobind

### ISSUE THREAD

**Issue by steida** [facebook/react#12238]
I don't know what exactly is planned, but auto bind for methods would be nice. Yeah, I know property initializers, still, a user should not have to think about that. I suppose a state should be stored in an object, not in a closure because of logs, and component should be an object ideally. Nevermind, feel free to close this "issue" without any explanation, I am just curious the reasoning behind a new design.

**Comment by aweary** [comment]
If you search the issue tracker you'll find a bunch of threads on this topic. Please refer to those rather than creating a new issue.

If you have another question, please check our community support resources:
https://facebook.github.io/react/community/support.html
