### ISSUE TITLE
Context update doesn't fully propagate in some cases

### ISSUE THREAD

**Issue by gaearon** [facebook/react#12246]
I think there may be a bug in context in the latest alpha. When some updates are scheduled in the commit phase, it doesn't seem to propagate.

```
git clone https://github.com/gaearon/emoji-search.git
cd emoji-search
yarn
yarn start
```

Enter "mon". Erase it. Click on "dark mode".
Expected: all children update. Actual: some children don't update.

This only seems to happen with [this indirection](https://github.com/gaearon/emoji-search/blob/2a3e23001ac5b1b2a05bc7b4ea9d7ef254888739/src/App.js#L12-L25).

![gif](https://d2ffutrenqvap3.cloudfront.net/items/2E3k0F2r3H0u040P2v2n/Screen%20Recording%202018-02-18%20at%2023.57.gif?v=4b4b511e)

**Comment by AlexanderKositsyn** [comment]
@gaearon I solved this bug for particular task by changing the 'key' props for each EmojiResultRow item from title to index. This is bad decision. But the bug maybe in Provider reconciliation. 
New code from EmojiResults 
```js
class EmojiResults extends PureComponent {
  render() {
    return (
      <div className="component-emoji-results">
        {this.props.emojiData.map((emojiData, index) => (
          <EmojiResultRow
            key={index}
            symbol={emojiData.symbol}
            title={emojiData.title}
          />
        ))}
      </div>
    );
  }
}
```

**Comment by acdlite** [comment]
@gaearon @AlexanderKositsyn I know what the bug is. On my todo list :)

**Comment by acdlite** [comment]
Fixed by https://github.com/facebook/react/pull/12478

**Comment by gaearon** [comment]
@acdlite Wrong link?

**Comment by acdlite** [comment]
Oops, sorry. Meant https://github.com/facebook/react/pull/12254.
