### ISSUE TITLE
Context Providers (and maybe Consumers) show up as "Unknown" in Performance tab

### ISSUE THREAD

**Issue by gaearon** [facebook/react#12245]
Noticed this with 16.3 alpha:

<img width="238" alt="screen shot 2018-02-18 at 21 58 15" src="https://user-images.githubusercontent.com/810438/36357507-e855da24-14f6-11e8-8398-b568fe92efd2.png">

I think we just need to support it here: https://github.com/facebook/react/blob/master/packages/shared/getComponentName.js.

Or else we could skip them [here](https://github.com/facebook/react/blob/e68c0164aa92ed383a0060639d9c449e2f740fb5/packages/react-reconciler/src/ReactDebugFiberPerf.js#L162) altogether.

**Comment by okyantoro** [comment]
hello @gaearon 
Is this issue beginner friendly?

**Comment by gaearon** [comment]
Maybe (skipping them would be two lines) but we’ll need to do it soon so I can’t promise we’d wait for more then a few days.

**Comment by abhaynikam** [comment]
@gaearon: Did not understand what we need to skip here?

I would love to contribute.

**Comment by gaearon** [comment]
Fibers with ContextProvider and ContextConsumer tags.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/12250.
