### ISSUE TITLE
Does react still require non-toplevel submit handler?

### ISSUE THREAD

**Issue by Ailrun** [facebook/react#12251]
**Do you want to request a *feature* or report a *bug*?**

bug? Maybe.

**What is the current behavior?**

Using non-delegated handler for submit event.

**What is the expected behavior?**

After IE9, at least I know, submit event bubbled up.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.2.0

**Comment by rayan0** [comment]
nice

**Comment by aweary** [comment]
@Ailrun I'm not sure what you're asking, can you please clarify?

**Comment by Ailrun** [comment]
@aweary 
https://github.com/facebook/react/blob/94518b068bf52196abea0c83f4c9926bfe2065c6/packages/react-dom/src/events/BrowserEventConstants.js#L10-L16

states that `'submit'` event is not delegated since it does not consistently bubble.
What browser makes the problem? At least I know, the problem occurs in IE8, and React 15/16 doesn't support it.
Could you give an name of browser that makes the problem?

I really thank you for response!

**Comment by gaearon** [comment]
I guess we could do it — are there any specific benefits aside from that we can?

**Comment by Ailrun** [comment]
What we get is what we get from delegation in first place, I guess?

**Comment by gaearon** [comment]
Fair enough. Was just curious if you're going for something in particular.

**Comment by Ailrun** [comment]
Oh, I just found this while analysing react code, not in some specific use case.

**Comment by philipp-spiess** [comment]
@Ailrun Thanks for bringing this - I've created a PR to try that in #13358 and it seems to work across browsers. 🎉
