### ISSUE TITLE
Obfuscating bundle.js for unauthenticated users?

### ISSUE THREAD

**Issue by U-4-E-A** [facebook/react#12252]
I am using React 15.6.1 and react-router-dom 4.1.2 with redux and react-redux.

Simple scenario - I have a website with ReactJS and a PHP backend RESTful service. For the backend, I do not want the bundle.js code to be exposed to unauthenticated users. I have looked everywhere for a solution to this and I just cannot seem to find one. Is this possible at all in React or any JS frameworks? I understand that if the user is unauthenticated then no data would be injected into the bundle but I would rather unauthenticated users cannot see anything about my admin panel!

Is there any solution at all to this?

**Comment by TrySound** [comment]
@U-4-E-A It's possible, but really is not related to react. And this is bug tracker. For questions use [stackoverflow.com](https://stackoverflow.com) please

**Comment by U-4-E-A** [comment]
Thank you for replying. I have actually researched this topic a lot but I cannot seem to find any answer or even a lead as to I would go about doing this. Would you be able to give me some advice or point me in the right direction so I can go and figure it out? Aside from the issue of not directly linking the bundle.js into the page, there is also the issue of it being openly available on the server. The only thing I can think of is having the bundle.js residing in a directory that is not publicly available and loading the contents of the bundle into the page using SSR.

I would really appreciate help here. I have already asked on stackoverflow and done a lot of searching and I cannot find any pointers as to how to get this done.

**Comment by gaearon** [comment]
>Is this possible at all in React or any JS frameworks? 

Whether or not you serve a bundle to the user is not related to JavaScript frameworks. That's purely a sever-side limitation.

This depends on what you use on the server side. You said you use PHP. So you'd need to check if your user is authenticated in PHP before serving them bundle. If they're not authenticated, don't serve it.

Hope it helps! If you need more pointers I would search for something like "don't serve static file to unauthenticated user php".

**Comment by U-4-E-A** [comment]
Thank you.
