### ISSUE TITLE
Feature request: checksum error reporting in production

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react#12258]
We are in the process of enabling SSR on unsplash.com and we would like to track checksum errors when they occur. However, to my knowledge, checksum errors are not reported in production, so there's no way of tracking them.

We need this because we might accidentally introduce a change that results in a checksum error, and when we do, we want to know as quickly as possible that this is the case.

To avoid checksum errors, we must ensure the first client render matches the server render, but it's very easy to slip up. We are working on better infrastructure to make this impossible (e.g. `window` state should only be accessible for "enhanced" renders, i.e. after the first client render), but in the meantime, we need to know when we break something.

**Comment by gaearon** [comment]
There is no more checksum validation in React 16, so there is nothing to enable.
Related issue with more discussion: https://github.com/facebook/react/issues/11189.
