### ISSUE TITLE
Having a warning message in socket.on

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [facebook/react#12257]
got problem in my socket spamming warning 
```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the AuctionStageFulfillment component.
```

here's the line, any idea how can i improve this? thanks 
```
componentDidMount() {
this.socket.on(EMIT_LOAD_CANDIDATES, data => {
      if (data !== undefined) {
        this.setState({ isReading: false });
        services.insertCandidate(data);
      }

      this.isReadingTimeout(this.setState({ isReading: false }));
    });
```

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by justinlazaro-ubidy** [comment]
SOLVE: acemarke: I'd assume your socket is still alive after the component has unmounted.  You should turn off the socket callback listener in componentWillUnmount
