### ISSUE TITLE
[componentWillUnmount()] How to cancel requests?

### ISSUE THREAD

**Issue by wzup** [facebook/react#12266]
You write
> Perform any necessary cleanup in this method, such as invalidating timers, *canceling network requests*,

People [here say](https://stackoverflow.com/questions/31061838/how-do-i-cancel-an-http-fetch-request) there are no ways to cancel a request. How do you mean _canceling network requests,_? Would you  please share some knowledge?

**Comment by TrySound** [comment]
@wzup You can abort xhr, you can unsubscribe from events or set conditional flag to prevent `setState`, it all depends on api you use. React just gives you a place to do this.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
