### ISSUE TITLE
React 16's new error handling results in data loss on forms that react while typing

### ISSUE THREAD

**Issue by esprehn** [facebook/react#12271]
As discussed here:
https://github.com/facebook/react/issues/11846

We have similar problems, if any error happens in ex. a textarea widget it'll unmount the entire app. Previously the user could copy and paste the text out of the form even if the page was behaving strangely or print it or whatever. Now any error anywhere in any part of the system (even a third party dependency or a browser feature) results in immediate data loss for the user. ex. a counter that shows the number of words as you type. If there was a bug in it then users would sometimes lose all the text they typed.

I totally understand the motivations for this feature and how it models native apps crashing, but it doesn't really work well (at least for us) with the web and tangle of third party dependencies that exist today. I can see how it works well for Facebook since they control every dependency and can fix bugs across all of them as needed. If you instead have a set of third party dependencies and one has a bug you can end up stuck where your app randomly breaks or shows blank to users. I guess you could put an error boundary around every widget in the entire page but that's hard to enforce and still results in data loss (just scoped).

My understanding is that we can't just render again per the discussion in the mentioned bug since it'd throw again, and because it destroys all the statefulness of the various browser widgets (ex. video or plugins).

Can this feature be made opt out?

**Comment by aweary** [comment]
@esprehn can you please just post this in #11846? Forking the discussion makes it harder to follow, and there's no reason this should be it's own issue. I'll re-open it, since it's just a discussion.
