### ISSUE TITLE
React passes empty spaces as children to react components

### ISSUE THREAD

**Issue by magestican** [facebook/react#12270]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

Passing an empty string inside a react element is treated as a child

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

With this syntax : 
```javascript
<MyReactComponent> <MyOtherReactComponent></MyReactComponent>
``` 
- Make notice of the empty space

React fills the "this.props.children" variable of MyReactComponent with : 
```javascript
[' ' , MyReactComponent];
```

**What is the expected behavior?**

"this.props.children property" of MyReactComponent should only contain one children

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Version 16.2.0 - Chrome - Mac OS High Sierra

**Comment by aweary** [comment]
This is expected behavior. Most whitespace is meaningful in JSX, so that space will actually be rendered. According to [the JSX docs](https://reactjs.org/docs/jsx-in-depth.html#children-in-jsx):

> JSX removes whitespace at the beginning and ending of a line. It also removes blank lines. New lines adjacent to tags are removed; new lines that occur in the middle of string literals are condensed into a single space.
