### ISSUE TITLE
state updated doesnt update the dom

### ISSUE THREAD

**Issue by radjivC** [facebook/react#12275]
Hi I want to feature a bug

```
<ul className="menu-list">
<li>
  <a  onClick={() => this.toggleHidden()}>
    <span className="icon is-small">{ this.state.isToogle ? <i className="fa fa-chevron-down" aria-hidden="true" /> : <i className="fa fa-chevron-right" aria-hidden="true" /> }</span>
    Misc
  </a>
</li>
<li>
  {this.state.isToogle &&
     <ul>
      <li><a>Members</a></li>
      <li><a>Plugins</a></li>
      <li><a>Add a member</a></li>
    </ul>
  }

</li>
</ul> 
```
So I have a condition to update the image of a chevron, but nothing happen.
I  use this  code before and everythings was fine, someone can help please?

version: react 16.2.0

Cheers

**Comment by jquense** [comment]
Can you please provide a working example of the bug using the jsfiddle template. The example you've given is not complete thanks!

**Comment by nihgwu** [comment]
Seems I'm experiencing the same issue, it only happens on Chrome but works well on Firefox

**Comment by nihgwu** [comment]
BTW, it's not same issue for me, you just have a typo `isToogle` @radjivC

**Comment by radjivC** [comment]
@nihgwu  the typo is alright, I have the problem on the zendesk iframe maybe its where the problem is. I will close this issue. thanks guys
