### ISSUE TITLE
"Development" or "Production" - how to find out?

### ISSUE THREAD

**Issue by mcjazzyfunky** [facebook/react#12277]
**Do you want to request a *feature* or report a *bug*?**

Primary just a question / secondary maybe a tiny feature request

**Question**

Is there an official way to find out whether the imported React package is the development or the production module ("react.development.js" vs. "react.production.min.js")?

Obviously you can do something like:
```javascript
const isProduction = React.Component.name !== 'Component';
```
... but I think we all agree that this is a really evil solution.

If the answer is "no" - then the question is: 
Would it be possible to add something like
```javascript
React.environment = 'development';
```
respectively
```javascript
React.environment = 'production';
```
(or something similiar) to the React object?

**Why is this useful?**
I'm sure your first thought will be: Why not just use the usual "Webpack / process.env.NODE_ENV" stuff?
But assume you have some React add-on library: This library itself has two different packages depending on the environment (e.g. "fancy-react-addon.development.js" vs "fancy-react-addon.production.min.js").
Also assume that it does (for whatever reasons) not make sense (or maybe it's not even allowed), to use React's development module in combination with the production module of your add-on library or vice versa. Then it would be great if directly on import an error is thrown if the module combination is invalid (independent of Webpack or process.env.NODE_ENV - because maybe the user of the add-on library will use some other tools).

```javascript
// Assume that this is "fancy-react-addon.production.min.js"

if (React.environment !== 'production') {
    throw new Error("You have to use React's production packages [... some details ...]");
}
```
Of course there are also some other use cases where this feature would also be handy or even necessary, but I hope the above use case is already convincing.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 
16.2.0

**Comment by aweary** [comment]
@mcjazzyfunky you can use the React Devtools, which will tell you which build you're running. 

https://reactjs.org/docs/optimizing-performance.html#use-the-production-build

> But assume you have some React add-on library: This library itself has two different packages depending on the environment (e.g. "fancy-react-addon.development.js" vs "fancy-react-addon.production.min.js").
Also assume that it does (for whatever reasons) not make sense (or maybe it's not even allowed), to use React's development module in combination with the production module of your add-on library or vice versa. 

If your add-on has a development and production build then it must have some check similar to `NODE_ENV` to determine what features are included in what build, unless you have two entirely separate code paths, which seems unreasonable.

If your add-on is meant to be used React applications then I would recommend that you use the same heuristics that React uses (checking `NODE_ENV`) for checking the environment. That way consumers can just import it and rely on their own build system

Check out the [Using the Production Build](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build) documentation for more information on this approach.

**Comment by js-works** [comment]
@aweary Thank you very much for your answer.
But I think, unfortunately my question may not have been comprehensive enough.

Please let me try to ask in a different way: 
In the following Two-Liner the first line of code is evil ... how can I change that first line to be not evil any longer (be aware  that in this concrete browser example there's neither "node" nor"process.env" nor "React DevTools")?
https://jsfiddle.net/wwh24fw6/

> We don't recommend having different behavior in production and development builds, outside of things like warnings or safety checks.

Replace that "throw new Error(...)" in my comment above with "console.warn(...)" and it will satisfy your/Facebook's recommendation. But don't forget there's a further aspect that justifies differences
in DEV vs PROD and that is performance. If necessary I can provide an example where that matters - but I think it should currently not be necessary.

**Comment by aweary** [comment]
> how can I change that first line to be not evil any longer

In short, there isn't a way. You shouldn't be trying to test the environment at runtime like this. 

> But don't forget there's a further aspect that justifies differences
in DEV vs PROD and that is performance. If necessary I can provide an example where that matters - but I think it should currently not be necessary.

Again, I don't recommend trying to run different code in DEV and PROD. If you need to exclude or include some code based on the environment then I recommend you use something like `NODE_ENV` and then ask that consumers of the library set the environment during their build process (which is already required if they use React).

**Comment by mcjazzyfunky** [comment]
@aweary Thanks again for your answer.

> [...] then I recommend you use something like NODE_ENV [...]

Again: There are scenarios where there is no "NODE_ENV" - like in most JS-Fiddle demos. Or for example there's a Germany web shop system that has some kind of special tag for HTML templates that takes a bunch of <script ... src="..."> elements and bundles all involved JavaScript files and minimizes them afterwards depending on it's own "environment" configuration - all done by Java - neither "node" nor "NODE_ENV" involved (not necessarily the way I would do it - but what I would do does not really matter in that case).
Just because we are using Webpack and node/npm does not mean that everybody uses it. And a library should always be usable independent of the involved build tools.

Maybe this example helps to understand that things are not always that easy:
Let's assume you are not really a big fan of JSX and want to write some hyperscript library for React, allowing things like (what follows is some feature mix of react-hyperscript / reagent / hiccups):

```javascript
h('.box > ul.link-list',
    h('li.primary > a.link', { href: 'https://www.facebook.com' }, 'Facebook'),
    h('li.secondary > a.link', { href: 'https://www.google.com' }, 'Google'));
```

The challange is not to implement such a library, the real big challange is to make that library almost as fast as JSX itself (we all know that "premature optimization is the root of all evil" - but here especially for SSR that may be critical - nevertheless all hyperscript libs that I know have quite a poor performance compared to JSX).
Sooner or later you'll find out that it's important that the following

```javascript
h('div#some-id.some-class', { onClick ... }, h('div', 1), h('div', 2), h('div', 3))
```

will have to be transformed to the equivalent

```javascript
React.createElement('div', {
    id: 'some-id',
    className: 'some-class',
    onClick: ...,
    children: [
        React.createElement('div', null, 1),
        React.createElement('div', null, 2),
        React.createElement('div', null, 3)
   ]
})
```

to be reasonable fast (if you did use variable children arguments in React.createElement then it would be much slower).
But unfortunately the latter will cause that infamous 'Each child in an array or iterator should have a unique "key" prop' warning when using React's development package - whereas there's no problem here with the production package.

So what will you do? If you are using Webpack/node and your webpack configuration is fine than that stuff won't be a problem - but in all other cases mixing up the wrong packages may make the following line

```javascript
h('div', h('div', 1), h('div', 2))
```

cause a "Each child [...] unique key [...]" warning and almost nobody will really understand why this warning is shown, because there's nothing wrong with that line (a simple additional warning about the mixture of incompatible packages would help, but is not possible because it's "officially" not possible to distinct between React's development and production packages at runtime).

And each additional validation/transformation as alternative to make that slightly dirty implementation a bit less dirty, will cost performance.

Of course another option is to see that above case as an ideal example for the mentioned "premature optimization is the root of all evil" thing.
But would you really bet that using a three times slower hyperscript function instead of JSX will not cause any performance issues on highly frequented SSR servers or on very slow smartphones?

But okay, if Facebook does not want to provide such an additional "React.environment" property than that's fine of course.
Thank you very much for the information and discussion - and sorry for that much text for such a short question ;-)

**Comment by aweary** [comment]
> Again: There are scenarios where there is no "NODE_ENV" - like in most JS-Fiddle demos. Or for example there's a Germany web shop system that has some kind of special tag for HTML templates that takes a bunch of <script ... src="..."> elements and bundles all involved JavaScript files and minimizes them afterwards depending on it's own "environment" configuration - all done by Java - neither "node" nor "NODE_ENV" involved (not necessarily the way I would do it - but what I would do does not really matter in that case).
Just because we are using Webpack and node/npm does not mean that everybody uses it. And a library should always be usable independent of the involved build tools.

What I'm saying is that React already requires that consumers explicitly import a DEV or PROD build. If you're loading scripts using `script` tags then you must explicitly use either `react.development.js` or `react.production.min.js`. if you import it with a Node-based build system it checks `NODE_ENV`. I'm recommending you take a similar approach.
