### ISSUE TITLE
Syntax Error in react-is package

### ISSUE THREAD

**Issue by jacobp100** [facebook/react#12287]
When trying to use react-is, there is a syntax error stopping it from being imported.

```js
REACT_ELEMENT_TYPE = Symbol.for('react.element);
```

https://unpkg.com/react-is@1.0.0/index.js

https://stackblitz.com/edit/react-dtslcx

**Comment by aweary** [comment]
@jacobp100 you'll want to use `react-is@next`. The 1.0.0 release was just a placeholder IIRC

**Comment by bvaughn** [comment]
Ah, I guess someone (Sebastian?) published a 1.0 accidentally. My guess is he just wanted to reserve the package name?

Either way, we'll soon be releasing `react-is` in lock-step with `react`, `react-dom`, etc as 16.3.0

**Comment by jacobp100** [comment]
Ah, didn't realise this wasn't officially published!

**Comment by bvaughn** [comment]
That's understandable, after all- there is a 1.0 version on NPM. 😅 Seems like a mistake on our part.
