### ISSUE TITLE
TypeError: Cannot read property 'valueTracker' of undefined

### ISSUE THREAD

**Issue by sangle7** [facebook/react#12280]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
when i worked with the branch `15.6-dev`, this error happened
<img width="1066" alt="2018-02-24 5 28 38" src="https://user-images.githubusercontent.com/21354661/36628762-8bec8fd0-1988-11e8-9578-b30c25b71700.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```
const App = props => (
  <form onChange={event => console.log(event.target.value)}>
    <label>
      <input type={'radio'} name={'myGroup'} value={1}/>
      Value 1
    </label>
    <label>
      <input type={'radio'} name={'myGroup'} value={2}/>
      Value 2
    </label>
    <label>
      <input type={'radio'} name={'myGroup'} value={3}/>
      Value 3
    </label>
  </form>
)
```
the error shows each time when a radio be clicked on

**What is the expected behavior?**
I had opened a pr about it #12230 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
on branch `15.6-dev`
notice that this error has been fixed in v16

**Comment by aweary** [comment]
@sangle7 why are you running the `15.6-dev` branch? I don't think that branch is in a stable state. It sounds like you're running mismatched versions of react and react-dom.

**Comment by sangle7** [comment]
@aweary hi, for some reasons, our project is not ready for v16, and the stable 15.6 version has a bug like this #10739. I noticed that the `15.6-dev` branch has fixed this bug, so i ran project with it. I build from this branch and use `npm link` to link my project with react and react-dom, and the problem is still there.

**Comment by aweary** [comment]
@sangle7 I would double check that `npm link` was sufficient, sometimes symlinks don't work as expected. You can try setting breakpoints and seeing if it's running the correct code. On that branch `_wrapperState` is defined here: https://github.com/facebook/react/blob/15.6-dev/src/renderers/dom/client/wrappers/ReactDOMInput.js#L149-L157.
