### ISSUE TITLE
Errors thrown at componentUnmount aren't reported at proper timings.

### ISSUE THREAD

**Issue by karak** [facebook/react#12297]
**Do you want to request a *feature* or report a *bug*?**

Bug, at least in QA respect.

**What is the current behavior?**

I'm creating a test-case to handle an error thrown at `componentUnmount`, which is reported  asynchronously since react v16.
But such errors are reported _only_ at the last test cases in a bunch, which virtually lacks reproducibility to rely on.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Please clone [this repository](https://github.com/karak/react-unmount-issue) and execute `yarn test`.

**What is the expected behavior?**

1. To report those errors at every test case.
1. To provide a proper way to handle them, especially for testing (already exists?).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.2.0

**Comment by karak** [comment]
Sorry, my test case seems broken through reducing ....

**Comment by karak** [comment]
It may a bug of Jasmine: https://github.com/jasmine/jasmine/issues/1453, I'm not sure.

**Comment by gaearon** [comment]
>which is reported asynchronously since react v16

This is not correct. It should be reported synchronously.

I looked at your test case. The tests fail if I use `ReactDOM.render` directly instead of Enzyme so maybe this is an Enzyme issue. If you can reduce it to just React please let me know and we can take another look.
