### ISSUE TITLE
It's not safe to read CurrentOwner.current and assume it has a stateNode

### ISSUE THREAD

**Issue by gaearon** [facebook/react#12299]
This:

https://github.com/facebook/react/blob/8e5f12ca6c18fb48ea71cba6bfa9bd7cf499ccb6/packages/react-reconciler/src/ReactFiberBeginWork.js#L217

might mean that `_owner.stateNode` is `null`.

So assumption like this leads to runtime failure in DEV:

https://github.com/facebook/react/blob/8e5f12ca6c18fb48ea71cba6bfa9bd7cf499ccb6/packages/react-dom/src/client/ReactDOM.js#L1131

We should fix up all such code sites.

**Comment by abhaynikam** [comment]
@gaearon: Is this bug: `good first issue`? I can have a look but I would need help in this.

**Comment by antonfrolovsky** [comment]
@gaearon There is a check, if `current == null` then current code don't run
https://github.com/facebook/react/blob/8e5f12ca6c18fb48ea71cba6bfa9bd7cf499ccb6/packages/react-dom/src/client/ReactDOM.js#L1129

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/12407
