### ISSUE TITLE
How to get DOM HTMLElement instance reference in order to use scrollIntoView API

### ISSUE THREAD

**Issue by nabilnaffar** [facebook/react#12307]
*This is an implementation/Usage question.

I'd like to use the native [Element.scrollIntoView API](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) in my React app to scroll to components from code.
To use that, I need reference to the HTML Element I want to scroll into.

Using React's [ref prop](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element) returns reference of React component, and not the HTMLElement DOM instance, so I can't use the desired API with it.

Is there a way to get access to the HTML DOM element in order to use the native scrollIntoView API? 

Versions in use:
React 16
Chrome browser (latest)

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

> Using React's ref prop returns reference of React component, and not the HTMLElement DOM instance, so I can't use the desired API with it.

The `ref` will return a reference to the component or element that it's defined on. If you need a reference to the element that a component renders, you can pass down the `ref` function as another prop and define it on the element itself.
