### ISSUE TITLE
Reset state

### ISSUE THREAD

**Issue by qtbit** [facebook/react#12308]
I'd like to have a function that would reset all the state of react to start rendering from scratch again.

Currently, the code below causes a duplication of virtual dom. The React tab in devtools shows `<App />` node twice.

```
document.body.innerHTML = '<div id="app"></div>';
ReactDOM.render(<App />, document.querySelector("#app"));

// page change

document.body.innerHTML = '<div id="app"></div>';
ReactDOM.render(<App />, document.querySelector("#app"));
```

It is possible to unmount it before the container element is lost to prevent the duplication of vdom.

```
document.body.innerHTML = '<div id="app"></div>';
ReactDOM.render(<App />, document.querySelector("#app"));
ReactDOM.unmountComponentAtNode(document.querySelector("#app")); // <--- unmount and remove

// page change

document.body.innerHTML = '<div id="app"></div>';
ReactDOM.render(<App />, document.querySelector("#app"));
```

However, sometimes it is difficult to bind to an event or change a router code in a legacy app where React is used for rendering a page. The page is destroyed when the router decides to change the page to another and React don't get the same container element again.

Since you can't call `ReactDOM.unmountComponentAtNode` before the change, nor after the change (before rendering) with the lost container element, it would be useful to have a function to reset all the React state before rendering the new page.

```
document.body.innerHTML = '<div id="app"></div>';
ReactDOM.render(<App />, document.querySelector("#app"));

// page change

document.body.innerHTML = '<div id="app"></div>';
ReactDOM.reset();  // <--- I don't care about the previous state, I want to render the component from scratch (as there would be no rendering before)
ReactDOM.render(<App />, document.querySelector("#app"));
```

The name doesn't have to be called `reset` or be within `ReactDOM`. The point here is that the rendering should not duplicate virtual dom since the container element was changed.

**Comment by nmain** [comment]
> Since you can't call ReactDOM.unmountComponentAtNode after the change (before rendering) with the lost container element

It seems like you can, although I don't know if it's supported.  Note that "unmounted" does get printed to the console for the first instance here, even though it's being unmounted after the element was already manually detached from the document: https://jsfiddle.net/829cw2to/

**Comment by aweary** [comment]
You should make sure to call `unmountComponentAtNode` before detaching the root node from the document. When you set `innerHTML` it doesn't actually destroy the node, it just detaches it. If you store a reference to the node before setting `innerHTML` you can still use `unmountComponentAtNode`

```js
document.body.innerHTML = '<div id="app"></div>';
// As long as you still have a reference to the node, you can use it to unmount
let node = document.querySelector("#app");
ReactDOM.render(<App />, node);
// After a page change...
ReactDOM.unmountComponentAtNode(node);
```

Hope that helps!
