### ISSUE TITLE
state change in td element

### ISSUE THREAD

**Issue by rayeeskm** [facebook/react#12301]
Displaying tabular rows, when setting data in td element, on state change it displays only the currently updated td element data..all the other ones go missing from screen. When the same thing is placed within text box in each td element things work fine.

Following is sample the code :

Working code :
`<tr key={id}> `
`<td> <input  value={this.state.price[id]}/> </td>`

Failing code :
`<tr key={id}> `
`<td> {this.state.price[id]} </td>`

**Comment by asmockler** [comment]
Hey @rayeeskm could you provide any more information? It is hard to tell what would be happening here.

**Comment by rayeeskm** [comment]
Hey @asmockler , thanks for the response... please see the screenshots below for the two codes:

working code (when state change is happening inside textbox within td):
![image](https://user-images.githubusercontent.com/2072089/37240407-c3c1a9e8-2470-11e8-84f4-a46ae200f188.png)

failing code (when state change is in td):

![image](https://user-images.githubusercontent.com/2072089/37240420-f80413c6-2470-11e8-9822-da655eeb1fdd.png)

![image](https://user-images.githubusercontent.com/2072089/37240423-fbd945ac-2470-11e8-90f3-cfc42a2034ff.png)
Here the price is displayed only for the row that is currently being updated. The price for rows above goes hiding.

**Comment by asmockler** [comment]
It looks like you might be blowing away the state of the price column when you update it – could you post some of the code? I can try to help you find the bug.

**Comment by rayeeskm** [comment]
Here it goes, the very last two lines, i have commented out the part were state change is done directly in td, if the state changes were not done correctly then it should have behaved the same way in both the cases. May be react does not keep a track of td elements while updating state?


`calcPrice(e,id) {`
`        let price;`
`        priceList.has(id) ? price = priceList.get(id) : price = new Price();`
`        if(!isNaN(e.target.value)) {`
`                price[e.target.name] = Number(e.target.value);  `
`                break;      `
`        }`
`        else {`
`                e.target.value = 0;`
`                this.calcPrice(e,id);`
`                return null;`
`        }        `
`        price.price = (price.rate * price.qty);`
`        price.price = price.price * (1 - price.discount / 100);`
`        //console.log(price);`
`        priceList.set(id,price);`
`        this.setState({price: {[id] : Number(price.price.toFixed(2))}});`
`}`


`<tr key={id} className="w3-white w3-hover-dark-sand">`
`                <td className="w3-border w3-border-brown"><input name="sku" className="w3-input-transparent" onChange={(e)=>this.setValues(e,id)}/></td>`
`                <td className="w3-border w3-border-brown"><input name="name" className="w3-input-transparent" onChange={(e)=>this.setValues(e,id)}/></td>`
`                <td className="w3-border w3-border-brown"><input name="qty"  className="w3-input-transparent" onChange={(e)=>this.calcPrice(e,id)}/></td>`
`                <td className="w3-border w3-border-brown"><input name="rate"  className="w3-input-transparent" onChange={(e)=>this.calcPrice(e,id)}/></td>`
`                <td className="w3-border w3-border-brown"><input name="discount"  className="w3-input-transparent" onChange={(e)=>this.calcPrice(e,id)}/></td>`
`                <td className="w3-border w3-border-brown">`
`                    <select name="tax"  className="w3-input-transparent" onChange={(e)=>this.calcPrice(e,id)}>`
`                        <option value="" disabled selected></option>`
`                        <option value='EXEMPT'>No Tax</option>`
`                    </select>`
`                </td>`
`                {/*<td className="w3-border w3-border-brown"><label>{this.state.price[id]}</label></td>*/}`
`                <td className="w3-border w3-border-brown"><input className="w3-input-transparent" value={this.state.price[id]}/></td>`
`            </tr>`

**Comment by nhunzaker** [comment]
Hey @rayeeskm, could you reproduce the issue using our JSFiddle template (https://jsfiddle.net/Luktwrdm/)? That would make it a lot easier for us to debug on our end. Thanks!

**Comment by asmockler** [comment]
I think the issue is that when you set state for your prices, you are only setting for a single id. Your code looks like this:

`this.setState({price: {[id] : Number(price.price.toFixed(2))}});`

but needs to look something like this:

```
this.setState((prevState) => ({
  price: {
    ...prevState.price,
    [id]: Number(price.price.toFixed(2)),
  },
}));
```

That way it doesn't wipe away the state of the other cells when setting state for the cell you want updated.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by rayeeskm** [comment]
@nhunzaker Thanks a lot for the suggestion. Have updated the fiddle https://jsfiddle.net/Luktwrdm/230/. you can see the price column displays only for the current row that is being updated.

**Comment by asmockler** [comment]
@rayeeskm Here is the fiddle updated with the solution I suggested before:

https://jsfiddle.net/Luktwrdm/257/

**Comment by rayeeskm** [comment]
Hey @asmockler thanks for that. `<td>` state gives the expected output when using prevState.

But am still wondering why react behaves differently for `<td>` and `<input>`. `<input>` did not require to use prevState whereas `<td>` requires.
