### ISSUE TITLE
Expose the `onSelect` event for any focusable element?

### ISSUE THREAD

**Issue by danburzo** [facebook/react#12309]
I was curious earlier if the `onSelect` event works on things other than form elements and `contentEditable` elements, and by disabling a couple of conditions in the code, it seems — at first brush, at least — that `onSelect` works splendidly on any element that is focusable (via the `tabIndex` attribute), to obtain things like:

![ezgif-2-326cf42421](https://user-images.githubusercontent.com/205375/36798178-8aa7fdda-1cb2-11e8-8838-46e04300a09a.gif)

Would there be any problem with relaxing the conditions for allowing `onSelect` to include elements that have a `tabIndex` attribute? (Other than the case where existing implementations in userland rely on the event being disabled when `contenteditable = true` is removed from an element).

**Comment by gaearon** [comment]
Can you send a PR so we can look at the proposal?

**Comment by rishabhjain9191** [comment]
@gaearon @danburzo Interested to pick this up!

**Comment by jmakeig** [comment]
Any word on this, @danburzo? I’m interested in building a generalized highlighting component.

**Comment by danburzo** [comment]
@jmakeig I don't think I stand behind this idea anymore. The SelectEventPlugin seems to depend on the element's focus — that is, the element needs to be focusable and, in the case of generic elements, it entails using the `tabindex` attribute. This in turn may hurt accessibility by introducing "non-interactive" elements into the tabbing order.

**Comment by jmakeig** [comment]
I’m missing something then. How do you handle selection events? I’m trying to build inline annotations. The existing implementations I’ve seen use mouse events. The interactions are janky and brittle.
