### ISSUE TITLE
getDerivedStateFromProps and MobX

### ISSUE THREAD

**Issue by bradenhs** [facebook/react#12310]
I use MobX to manage the application state of react apps I build and ever since I read this [post](https://blog.cloudboost.io/3-reasons-why-i-stopped-using-react-setstate-ab73fc67a42e) I've been using MobX to manage local component state as well. I recently read that React 16.3 will introduce a new static method called `getDerivedStateFromProps` and that some future release will deprecate `componentWillReceiveProps`. I'm worried that deprecating `componentWillReceiveProps` will break some of my components which need to update their state in response to a change in props. **This, of course, wouldn't be an issue except for the fact that `getDerivedStateFromProps` appears to be incompatible with local component state managed by MobX.** One of the things I love about React is that it is so easy to integrate with other tools. The new `getDerivedStateFromProps` static method will reduce some of this flexibility.

For those of you who haven't used MobX before the issue here may be a little hard to grasp at first. I've built an example [repo](https://github.com/bradenhs/getDerivedStateFromProps-mobx) where you can see both a MobX and React setState implementation of a component which needs to update it's local state in response to a props change. Take a look at the example, but in brief the core of the issue is that `getDerivedStateFromProps` is a static method and mobx state on the component _instance_ can't be accessed and updated in a static method. `componentWillReceiveProps` is generic enough that updating mobx component state in there is possible in a semantically sound manner. Once it's deprecated, however, I don't know how this will be possible in a non-hacky way.

I realize I may be a little late with this concern since it appears React 16.3 will be released anytime now. I do, however, think the concern is worth raising since this new change in React will break what is in my view a valid use of React. I'd prefer if another solution was devised which was more flexible for people using React with other tools.

**Comment by benwiley4000** [comment]
FYI as far as I understand the plan is to continue to have `UNSAFE_componentWillReceiveProps` (https://twitter.com/brian_d_vaughn/status/953399568628031488). The reason for the removal is (somehow) related to the need that components will be async-compatible by default, even if a particular shared component dev isn't developing with async in mind.

**Comment by bradenhs** [comment]
Thanks @benwiley4000! I did see that there would be an `UNSAFE_componentWillReceiveProps` method sticking around. Of course, using something prefixed with `UNSAFE` for what should be an expected and valid use of React doesn't feel quite right.

**Comment by gaearon** [comment]
Can you do this in `componentDidUpdate` instead? I guess that would cause an extra re-render. But, as you might have seen in [my talk](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html), React rendering might be time sliced or suspended for a period of time. So doing mutations at that point in time can make the screen inconsistent.

**Comment by gaearon** [comment]
cc @mweststrate

**Comment by dantman** [comment]
@gaearon I've seen `componentWillReceiveProps` used in some cases where waiting till componentDidUpdate made things fall out of sync visually (can't remember an example) or where `shouldComponentUpdate` was used to ignore `render()` to optimize a component with props that were only used in `componentWillReceiveProps` (iirc like React Native animations).

**Comment by gaearon** [comment]
It's a bit hard to discuss without specific examples.

**Comment by dantman** [comment]
Sadly I don't remember where I ran into using `componentDidUpdate` delaying things too much. And I don't remember where I could find an example that uses `shouldComponentUpdate`. But I do have an example of React Native animation handling in `componentWillReceiveProps`.

https://github.com/material-native/material-native/blob/master/src/input/Underline.js#L28-L64

This component actually could be optimized in the way I describe. If I used `shouldComponentUpdate` to ignore `invalid` and `focused` it would work the same, but would not unnecessarily call `render()` whenever the component is (un)focused or made (in)valid, which only require imperative `Animated.timing` calls. However this would mean that `componentDidUpdate` would not run.

I can also imagine the same thing being done for props that only need to act imperatively with dom components, especially if they are part of a heavy component.

**Comment by mweststrate** [comment]
Related issue in mobx-react repo: https://github.com/mobxjs/mobx-react/issues/425.

But honestly I didn't dive in the problem or the sample repo's yet :) So give me a few days to investigate. 

At first sight `getDerivedStateFromProps` indeed does seem to make it hard to get notified about new props and react (lol) to that? Especially when not storing stuff in state. Which is not just relevant for MobX, but for any state that is irrelevant for render, and per best practice (not sure if it is an official one, but saw it in some conference talks and blog posts at least) is hence not stored in `this.state`, for example timeout handles and other resources.

**Comment by bvaughn** [comment]
Hi @dantman. The code example you linked to seems like one that could be easily converted from `componentWillReceiveProps` to (async-safe) `componentDidUpdate`. On some slow mobile devices, there can be a delay between the two, but it shouldn't be _too_ big and `componentWillReceiveProps` is not safe for this sort of thing in the context of async rendering.

There's a bit of an explanation [here](https://deploy-preview-596--reactjs.netlify.com/docs/strict-mode.html#detecting-unexpected-side-effects) that you might find helpful.

**Comment by bradenhs** [comment]
@gaearon I suppose I could use `componentDidUpdate` but as you said that would result in another render. Also, it makes much more sense to handle this type of operation in `componentWillReceiveProps` than `componentDidUpdate` just from a semantic point of view. So possible? Yes. But, possible isn't a great litmus test for api design.

**Comment by bvaughn** [comment]
@mweststrate and @dantman, you might also both find the "recipes" from [draft blog post](https://deploy-preview-596--reactjs.netlify.com/blog/2018/02/07/update-on-async-rendering.html) worth reading.

**Comment by mweststrate** [comment]
@bvaughn great, thanks! (N.B.: MobX itself doesn't use `componentWillReceiveProps`, but it is a pattern I do see frequently in the code base of MobX based projects, including our own.)

**Comment by gaearon** [comment]
>Also, it makes much more sense to handle this type of operation in componentWillReceiveProps than componentDidUpdate just from a semantic point of view. So possible? Yes. But, possible isn't a great litmus test for api design :)

From a semantic point of view `componentWillReceiveProps` runs during the render phase (potentially split across multiple idle callbacks, or even suspended for seconds). So it is the wrong place to do any side effects that affect rendering. Please see [my talk](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html) to get an idea of what those features mean and enable. I hope this provides some context onto *why* this is the recommendation.

**Comment by bradenhs** [comment]
@gaearon thanks! I'll take a look at that. I can definitely see why `getDerivedStateFromProps` is being introduced and how it'll push people in a better direction. I don't mean to suggest that `componentWillReceiveProps` should stick around. It would be great, however, if `getDerivedStateFromProps` was designed in such a way that it could play nicely with libraries like MobX. I'm not sure the best way to make that happen but it would be nice all the same.

**Comment by sophiebits** [comment]
@dantman If I understand right, your issue is that you can't use componentDidUpdate because you want shouldComponentUpdate to return false? This is not a great solution but one option is to return the exact same reference as earlier from render, in which case rendering will bail out on children but componentDIdUpdate will still run.

**Comment by dantman** [comment]
@sophiebits You are right/close. The proper answer to "I only want to do element render when part of my props have changed" is to move the element `render()` into a separate `PureComponent` and make the original component's `render()` just pass the relevant props onto the component that does element render.

I do think that would be the best thing long term. However I do not like how it results in needing multiple components with similar names to do the job of one component, lots of React element boilerplate, and moves part of the logic of a component to another part of the file where it is less logically connected to the code it belongs to.

If that is the direction we're going, I would like to see some pattern in react that would enable that pattern (separate components for logic and element render) but keep code in the same class definition (nested classes/functions could work, the key is to not move element rendering out of `class { ... }`).

**Comment by sophiebits** [comment]
The caching I described would also do that and then you don't need to have two classes.

**Comment by dantman** [comment]
@sophiebits Correct, but as you said, it is essentially a hack. You essentially have to write the equivalent to a `shouldComponentUpdate` but instead as a wrapper to `render()`.

I suppose one could write it as a decorator for `render()`. But I still think the proper "React-way" would be using a separate PureComponent instead of faking `shouldComponentUpdate`.

**Comment by bvaughn** [comment]
Sorry if I'm missing something, but it's probably not a big deal for `render` to run twice in this case, provided it returns the same element-types and props. `PureComponent`/`shouldComponentUpdate` is an optimization that isn't always necessary.

**Comment by Grsmto** [comment]
Hey, 

As I see more and more that 
>the cost of render is relatively small
 I'm wondering why one would use the new `getDerivedStateFromProps` instead of `componentDidUpdate`?

Imagine this example:
```
getDerivedStateFromProps(nextProps, prevState) {
  if (!prevState.isModalOpen && nextProps.isReady) {
       return { isModalOpen: true };
  }
}
```

versus

```
componentDidUpdate(prevProps) {
  if (!prevProps.isReady && this.props.isReady) {
        this.setState({ isModalOpen: true });
  }
}
```

The later seems simpler just because it's using only existing API and looks just like what we used to do in `componentWillReceiveProps` so I don't see why users would go for `getDerivedStateFromProps`? What's the benefit?

I'm sorry if this has been answered already or if it's planned to be answered in the doc but I didn't find clear answer anywhere else.
Thanks!
