### ISSUE TITLE
Regarding new context API

### ISSUE THREAD

**Issue by mcjazzyfunky** [facebook/react#12319]
**Do you want to request a *feature* or report a *bug*?**

Neither a feature nor a bug - hope you do not mind me asking a question here (maybe some others are also interested).

**Question**

In all of the examples I've seen regarding the new context API the context values are only relevant for the virtual element tree - means: only relevant in the "render" function.

But what about context values that are not relevant for the view at all but only for some side effects?
Is the only recommended way here to use higher order components?

**Example**

Let's say the component requires some side-effect handler that shall not be passed explicitly by props but passed implicitly by using context => let's name it "someMgr".
Now assume that this "someMgr" object will only be needed in "componentDidMount" (and if you like maybe also in "componentWillUnmount").
In the "old days" "componentDidMount" looked like follows (no need for HOC): 

 [Edit: Of course no reasonable programmer would have used it directly that way - just saying it was possible with the old API to do so]

```javascript
componentDidMount() {
     this.context.someMgr.doSomeAsyncSideEffect(/* some args */);
}
```
Like already asked above, shall we now just use some HOC to handle such use cases with the new context API or is there some other "trick"/recommendation (or maybe that use case is even considered as anti-pattern)?

Many thanks in advance for your answer.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

"<= 16.2x" versus ">= 16.3x"

**Comment by TrySound** [comment]
Just use component around which provides context value via props. It's probably sometimes not expressive, but solved problems with this api are more important. Maybe it's time to reconsider how you do composition.

**Comment by js-works** [comment]
@TrySound Thanks for your answer.
"Use compent around which privides context value via props" is exactly what I meant by saying "just use some HOC".

**Comment by TrySound** [comment]
Probably more explicitly via normal parent component. I don't use HOCs anymore because was stuck on its problems a lot. Props collisions and hard typing are bad for maintenance.

**Comment by js-works** [comment]
@TrySound Thanks again for your comment.
I think that completley answers the question and that issue can be closed.
Muchas gracias.

**Comment by mcjazzyfunky** [comment]
@TrySound Thanks again for your comment.
I think that completley answers the question and that issue can be closed.
Muchas gracias.
