### ISSUE TITLE
iOS controlled input type="date" - onChange not triggered by pressing clear

### ISSUE THREAD

**Issue by smollweide** [facebook/react#12313]
**bug**

**What is the current behavior?**
Controlled Input type="date" doesn't trigger onChange by pressing the clear button on iOS Datepicker Keyboard. This only happens on controlled input, uncontrolled works fine.
 
Reproduced on **iPhone 6 iOS 11.2.2 Safari**.

Demo React 16.2: [jsfiddle](https://jsfiddle.net/z0jhLq8y/1/)
Demo React 15.6.2 [jsfiddle](https://jsfiddle.net/23ye3qzz/2/)

**What is the expected behavior?**
Controlled Input date should trigger onChange by pressing the clear button.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- react: 16.2 & 15.6.2
- react-dom: 16.2 & 15.6.2
- OS: iOS 11.2.2
- Browser: Safari
- Device: iPhone 6, iPhone SE

**Comment by nhunzaker** [comment]
Hey, thanks for the report! We're already tracking this in https://github.com/facebook/react/issues/8938, but thank you for providing test cases. I'm going to close this out, however I've relayed your findings to that issue.
