### ISSUE TITLE
React.Element, React.Node and some other types used by flow are undefined

### ISSUE THREAD

**Issue by eunikitin** [facebook/react#12322]
I use flow in my project, and started to get this message to console: "flow-runtime: Could not reference the given type, try t.typeOf(value) instead. (got undefined)".

![1](https://user-images.githubusercontent.com/2767639/36906702-aa3b7208-1e47-11e8-9516-997b62970b26.PNG)

After some search i found out the reason - React.Node is undefined, same for other types described in [flow docs](https://flow.org/en/docs/react/types/). 

![2](https://user-images.githubusercontent.com/2767639/36906706-adc842e8-1e47-11e8-9bf9-e39c7374d208.PNG)

Am I do something wrong?

**Comment by aweary** [comment]
It looks like you're using the flow-runtime library, which is distinct from the core Flow library. Flow only executes at compile-time, and what you're getting is a runtime error.

The types defined for React are abstract, meaning they don't correspond to actual values on the `React` export itself. It looks like flow-runtime is trying to resolve these abstract types to actual values, which is incorrect.

I suggest you take this up with the flow-runtime authors.

Thanks!

**Comment by aguynamedben** [comment]
@eunikitin This is happening to me too, did you get to the bottom of it?

**Comment by eunikitin** [comment]
@aguynamedben I wrote about it [here](https://github.com/chentsulin/electron-react-boilerplate/issues/1451)

**Comment by kwdata** [comment]
Try like this, it's OK.
I dont know why, 
Please whoever explains this

// @flow
import * as React from 'react';
import type {Node} from 'react';

type Props<Node> = {
  children: Node
};
