### ISSUE TITLE
Switching from dangerouslySetInnerHTML to children

### ISSUE THREAD

**Issue by kcarnold** [facebook/react#1232]
I tripped on a strange error when, in one state, a component uses HTML to specify children (from rendering Markdown) and in another state it uses child components (for interactive content, itself with some inner HTML). I reduced the testcase down to this: http://jsfiddle.net/BCp36/1/

**Comment by mattmo** [comment]
Any update on this issue?

**Comment by Zenwolf** [comment]
I also ran into this issue recently. I had to wrap the child in a `<span>` to fix the bug.

**Comment by ahmetabdi** [comment]
Issue still occurring for me

**Comment by juztinlazaro** [comment]
Hi guys, got an issue on dangerouslySetInnerHTML my problem is it decode the HTML entities but it doesn't apply the style or properties.

**Comment by jimfb** [comment]
@juztinlazaro If you believe you've found a bug in the React core, please open a new issue and provide a jsfiddle (simplified testcase/example) that demonstrates the bug.

**Comment by juztinlazaro** [comment]
@jimfb thanks sir, here's my https://jsfiddle.net/up8j9aqz/1/

**Comment by jimfb** [comment]
@juztinlazaro It doesn't decode the entities.  It puts them into the markup, directly (that's what dangerously set does).  The browser sees the entities and renders them as text (that's what browsers do).  This is not a bug.  I modified your fiddle to do what I believe you wanted: https://jsfiddle.net/b5Lt87kb/

**Comment by juztinlazaro** [comment]
@jimfb oh sorry, okay i understand now, newbie here. Okay maybe i need to decode it first before using dangerously. thanks sir.

**Comment by jimfb** [comment]
@juztinlazaro Ok, for future reference, usage questions are better answered on StackOverflow, as we try to keep github issues for tracking bugs in the React core.

**Comment by juztinlazaro** [comment]
@jimfb okay thanks sir.
