### ISSUE TITLE
I got a white screen with react 16.2.0!

### ISSUE THREAD

**Issue by GHLandy** [facebook/react#12324]
Hey, there! I'm FE developer.

I had met a big problem when I try to use the latest react 16.2.0 and react-dom 16.2.0.

The situation is that I got a white screen on my Huawei Honor v10 phone with android 8 browser as show below, whether I create the app with official create-react-app script or make a config of webpack by myself.

![image](https://user-images.githubusercontent.com/14830914/36941626-94c07df2-1f9a-11e8-9173-8336f4e4bfe3.png)

note: I use eruda to look for mistake in this bowser but got nothing.

This app created by official create-react-app which got white screen only happen in the android vender browser, and it display properly in my lastest chrome mobile.
And about the react version, react 15.6.2 and react-dom 15.6.2 works fine in both bowser. 

Is there any way to solve this? Tell me please.

Thanks.

**Comment by gaearon** [comment]
Please read this:

https://reactjs.org/docs/javascript-environment-requirements.html

I hope this helps!

**Comment by GHLandy** [comment]
Thanks, it works. @gaearon

**Comment by renrenguiwei** [comment]
I also encounter this issue, but import both 'core-js/es6/map、core-js/es6/set' still doesn't work? The page is still empty. What can i do?

**Comment by dhiahassen** [comment]
Same here still doesnt work

**Comment by GavinSong123** [comment]
import core-js/es/map core-js/es/set core-js/features/set core-js/features/map
still not work :(
