### ISSUE TITLE
Jest test fails because onChange is missing but have onClick here

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#12338]
Seeing this warning when running jest tests:

```
    console.error node_modules/fbjs/lib/warning.js:33
      Warning: Failed form propType: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```

Having this cjsx code here

```cjsx
          <input
            checked = {@_isAllSelected()}
            type = "checkbox"
            name = "selectAll"
            onClick = {@_onSelectAll}
          />
```

Has to be onClick for app specific purposes which works fine as if it were onChange. Yet fbjs warns it should be onChange.

Can this be improved, not to warn when onClick is detected as well? Using v15.5.4 here.

**Comment by zackify** [comment]
Use onChange like this `onChange={e => e.target.checked)}` if that variable is true, give it to selectAll or whatever you want. React has that warning because a checkbox is supposed to have an onChange

**Comment by aweary** [comment]
The problem with using a click handler for a checkbox is that users won't be able to update the checkbox in other ways, like keyboard events. We warn for this by default because in the general case this isn't a great pattern for accessibility.

If you have a very specific need that requires you to _only_ use click events, you can follow the advice of the warning and use `defaultChecked` instead.

```jsx
<input
            defaultChecked = {@_isAllSelected()}
            type = "checkbox"
            name = "selectAll"
            onClick = {@_onSelectAll}
          />
```

Hope that helps!

**Comment by binarykitchen** [comment]
@aweary that worked - thanks!

**Comment by JKillian** [comment]
> The problem with using a click handler for a checkbox is that users won't be able to update the checkbox in other ways, like keyboard events.

But radio buttons fire a click event even when changed with the keyboard; and they're supposed to do this [by the spec](https://w3c.github.io/uievents/#event-type-click) if I understand it correctly:

> In addition to being associated with pointer devices, the click event type MUST be dispatched as part of an element activation, as described in §3.5 Activation triggers and behavior.

Which to me, means it could be reasonable to supply an `onClick` but not an `onChange` while using the `checked` property.
