### ISSUE TITLE
_Uncaught TypeError: _assign is not a function

### ISSUE THREAD

**Issue by SnowFlowers** [facebook/react#12333]
![image](https://user-images.githubusercontent.com/16875486/37020598-452b4150-2157-11e8-8f25-a5bfbfa24bd2.png)

React 16.2.0
React-Dom 16.2.0

What is the cause of this problem

**Comment by danbee** [comment]
@SnowFlowers I'm seeing this same error, did you ever figure it out?

**Comment by coder-mike** [comment]
I was also getting this error. It turned out I accidentally had `@rollup/plugin-commonjs` running twice in my `rollup.config.js`.
