### ISSUE TITLE
getDerivedStateFromProps and requestAnimationFrame problem

### ISSUE THREAD

**Issue by grahammendick** [facebook/react#12335]
Thanks for all your hard work. React is incredible.

The new static lifecycle methods don’t work well with the common usage animation pattern. The approach, popularised by ReactMotion, is to add an `animate raf` in `componentDidMount`. Inside the `animate` function you update the state and keep adding a new `animate raf` until the animation finishes. That way the `animate raf` only runs when there’s work to do. In `componentWilReceiveProps` you add a new `animate raf` to start the animation again if it’s stopped. 

```javascript
class Animation extends React.Component {
  componentDidMount() {
    this.id = requestAnimationFrame(this.animate);
  }
  componentWillReceiveProps() {
    if (!this.id)
      this.id = requestAnimationFrame(this.animate);
  }
  animate(tick) {
    this.setState(() => {
      if (animationNeeded)
        this.id = requestAnimationFrame(this.animate);
    });
    return newState;
  }
  render() {
    return <AnimatedItem />
  }
}
```
There’s no way to reliably translate this pattern to the new static lifecycle.

You can’t move `componentWillReceiveProps` into `getDerivedStateFromProps` because you can’t access the `animate raf` from a static function. 

You can’t move `componentWillReceiveProps` into `componentDidUpdate` because then the `animate raf` will run forever, even when there’s no work to do. The `componentDidUpdate` has no way of knowing whether the update is because of new props or because the `animate raf` has run. So it always has to add a new `animate raf` even when the animation’s finished (re-running the `animationNeeded` check inside `componentDidUpdate` isn’t always possible).

**Comment by jquense** [comment]
hey there, I'm a bit confused why you need the `componentWillReceiveProps` at all here? It looks like it never runs because `componentDidMount` always starts the loop? Assuming you maybe over simplifed the case to illustrate the problem, I think you can still use `componentDidUpdate` I believe this is allowed:

```
componentDidUpdate(prevProps, prevState) {
  if (this.prevProps !== this.props) // props changed
    this.id = requestAnimationFrame(this.animate);
}
```

That _should_ fire at the same frequency as a cWRPs You can also do:

```js
static getDerivedStateFromProps(nextProps) {
  return { ...prevState, needsAnimate: true }
}
componentDidUpdate() {
  if (this.state.needsAnimate) {
     this.id = requestAnimationFrame(this.animate);
     this.setState({ needsAnimate: false })
  }
}
```

and finally the most hacky of all
```js
  constructor() {
    super()
   
    this.state = { animate: this.animate, id: null }
  }
  static getDerivedStateFromProps(nextProps, prevState) {
    let id = prevState.id
    if (!this.id)
      id = requestAnimationFrame(prevState.animate);
    return { ...prevState, id }
  }
```

**Comment by grahammendick** [comment]
The `componentWillReceiveProps` restarts the stopped animation. Imagine that the animation is triggered by a button click. When the button is clicked you call `setState`. This re-renders the Animation component and you want the `raf` to start up again to run the animation. The `componentDidMount` is no good to you because it’s already mounted. The `componentWillReceiveProps` adds the `raf` and the animation plays.

Your idea should work, but it doesn’t! **I’m sure it’s a bug with the new Context Api**. To show you what I mean I’ve built [a minimal JsFiddle that displays the problem](https://jsfiddle.net/m0vss98e/145/). Make sure you open up the console when you run it. You’ll see that you get a 'Maximum update depth exceeded' error!

It’s a problem with the new Context Api because if you remove the Context from the example then it works fine. The new Context Api gets stuck in an infinite loop (it only completes because React throws at a certain depth).

```javascript
var TestContext = React.createContext(null);

class Animation extends React.Component {
  constructor(props) {
    super(props);
    this.animate = this.animate.bind(this);
    this.state = {};
  }
  componentDidMount() {
    this.id = requestAnimationFrame(this.animate);
  }
  static getDerivedStateFromProps() {
    console.log('getDerivedStateFromProps')
    return { needsAnimate: true };
  }
  componentDidUpdate() {
    console.log('componentDidUpdate')
    if (this.state.needsAnimate) {
      this.id = requestAnimationFrame(this.animate);
      this.setState({ needsAnimate: false })
    }
  }
  animate(tick) {
    this.setState({});
  }
  render() {
    return (
      <TestContext.Consumer>
        {() => this.props.children()}
      </TestContext.Consumer>
    );
  }
}

ReactDOM.render(
  <TestContext.Provider value={null}>
    <Animation>
      {() => <Animation>{() => <div />}</Animation>}
    </Animation>
  </TestContext.Provider>,
  document.getElementById('content')
);
```

**Comment by bvaughn** [comment]
The example you linked to causes a cycle because `setState` calls made from `componentDidMount` or `componentDidUpdate` are processed synchronously by React.

Your example leads to a cycle because `getDerivedStateFromProps` _always_ requests another `setState` update from `componentDidUpdate` (rather than checking for any kind of conditional to see if it's appropriate).

**Comment by bvaughn** [comment]
@jquense is correct in suggesting that `componentDidMount`/`componentDidUpdate` are the correct lifecycles to use in this case. (I assume you wouldn't want to start an animation for a render that was paused or interrupted by a higher-priority render.)

Unfortunately the original example you provide glosses over the `animationNeeded` criteria, so I can't make specific suggestions- other than to say that you can do the same checks in `componentDidUpdate` (by comparing `this.props` to `prevProps`) as you can do in `componentWillReceiveProps` (by comparing `this.props` to `nextProps`).

**Comment by grahammendick** [comment]
Here’s [that same JsFiddle but with the new Context API removed](https://jsfiddle.net/9uaocjkk/1/). This one doesn’t get stuck in an infinite loop so I think it must be a bug with the new Context API.

```javascript
class Animation extends React.Component {
  constructor(props) {
    super(props);
    this.animate = this.animate.bind(this);
    this.state = {};
  }
  componentDidMount() {
    this.id = requestAnimationFrame(this.animate);
  }
  static getDerivedStateFromProps() {
    console.log('getDerivedStateFromProps')
    return { needsAnimate: true };
  }
  componentDidUpdate() {
    console.log('componentDidUpdate')
    if (this.state.needsAnimate) {
      this.id = requestAnimationFrame(this.animate);
      this.setState({ needsAnimate: false })
    }
  }
  animate(tick) {
    this.setState({});
  }
  render() {
    return this.props.children();
  }
}

ReactDOM.render(
    <Animation>
      {() => <Animation>{() => <div />}</Animation>}
    </Animation>,
  document.getElementById('content')
);
```

**Comment by bvaughn** [comment]
The first example gets caught in a synchronous cycle between the outermost `Animation.getDerivedStateFromProps` and its `componentDidUpdate` lifecycle because React processes `setState` calls with `componentDidUpdate` synchronously (as I mentioned above).

The second example doesn't get caught in this cycle because the outermost `Animation.getDerivedStateFromProps` is only invoked once.

I'm not sure off the top of my head why the behavioral difference exists (@acdlite would know!), but the logic problem I pointed out is problematic (and should probably be fixed) regardless because of the potential for a cycle like this.

Does your component really need to animate every time it re-renders (even if external `props` haven't changed)?

**Comment by bvaughn** [comment]
Quick update: There is a known bug in the latest alpha (that has already been fixed, but not released) that causes context consumers to render unnecessary. That might be what's causing gDSFP to be re-invoked here.

**Comment by grahammendick** [comment]
Cool. Ta for the update

**Comment by grahammendick** [comment]
Ok, I’m pretty sure the problems I’m having are down to [the Context API bug](https://github.com/facebook/react/issues/12218). Once that’s fixed it’s safe to move the `raf` into componentDidUpdate. This works at the moment but the `raf` runs forever. I’ll retest once the next alpha comes out and check that it stops running when the animation completes. If it does then I’ll close this issue.
```javascript
class Animation extends React.Component {
  static getDerivedStateFromProps() {
    return { update: true };
  }
  componentDidMount() {
    this.id = requestAnimationFrame(this.animate);
  }
  componentDidUpdate() {
    if (!this.id && this.state.update)
      this.id = requestAnimationFrame(this.animate);
  }
  animate(tick) {
    this.setState(() => {
      if (animationNeeded)
        this.id = requestAnimationFrame(this.animate);
    });
    return { newState, update: false };
  }
  render() {
    return <AnimatedItem />
  }
}
```

**Comment by aweary** [comment]
> Ok, I’m pretty sure the problems I’m having are down to the Context API bug. Once that’s fixed it’s safe to move the raf into componentDidUpdate

👍 I'll go ahead and close this issue then since https://github.com/facebook/react/issues/12218 is tracking the context bug.
