### ISSUE TITLE
Production reconciler Instrumentation

### ISSUE THREAD

**Issue by nevir** [facebook/react#12331]
_Apologies if this is documented somewhere, but I was unable to find anything related after a pretty exhaustive search of docs + code._

Are there any production instrumentation hooks for the reconciler?  Specifically, I'm looking for callbacks/events that would allow me to track overall reconciliation time spans (nothing more granular).  E.g. equivalent to the `(React Tree Reconciliation)` span.

As best I can tell, there are `performance.timings` spans reported as of Fiber (and `ReactPerf` prior), but those are only enabled in development mode.

**Comment by gaearon** [comment]
No official way to do this but you can manually compile React with something like this:

https://github.com/facebook/react/blob/ad9544f48e58f2599a8ea0de1e9f4dd104db30bb/packages/shared/forks/ReactFeatureFlags.www.js#L30-L50

but in the main `ReactFeatureFlags.js` file (which we use in open source)
