### ISSUE TITLE
with refs, why is the final ref different than output of getElementById?

### ISSUE THREAD

**Issue by MagicPoulp** [facebook/react#12336]
**Do you want to request a *feature* or report a *bug*?**
bug/question

**What is the current behavior?**
react 16.2.0

I have a react application with redux. I need to use a ref on a HTML pre because I want to copy paste its text in a button callback.

The ref callback looks like this for the pre:
(ref) => { this.preRef = ref }

In a button onClick event, I noticed the final value of this.preRef is not equal to the final output from document.getElementId() on the id of the HTML pre. It is fine for me if the ref callback is called many times since it is by design of react. But can someone explain me why the final ref is not equal to the final DOM element finally showing up on the page?

I want to avoid getELementById, but it works with its returned value and its returned value is equal to the first this.preRef, not the last.

```
                                    e(  'pre',
                                        {
                                            className: 'modal-content',
                                            key: 'raw-json-modal-div-modal-content-2',
                                            ref: (ref) => { console.log("NEW REF"); console.log("null ref", ref == null); this.rawJsonPreRef = ref; this.TEMP_BUFFER.push(ref) },
                                        }, [
                                            prettyJson
                                        ]
                                    ),
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

see above

**What is the expected behavior?**
see above

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 16.2.0

**Comment by jquense** [comment]
Can you please provide a runnable example demonstrating your issue here. IT's really difficult for someone to troublshoot what you're seeing from a static code snippet

**Comment by MagicPoulp** [comment]
I could not manage or have the courage to create a codepen with react and redux.

Let us wait. Maybe some people can theoretically consider the case for which the final ref does not equal what really ends up on the page as returned by getElementById. Other github issues had other interesting issues/questions on react regarding refs. With lots of comments. It was there I learnt that the ref is sset to null first to clear the memory.

The class is a React.Component.

I suspect the ref is not equal to the dom element because the framework does not see the need to update to put something with same content.

THink about it. If I do 1000 useless render, maybe react renders but still the virtual dom will be clever and not create a new DOM element mounted on the page. SOmething like that. I am a little confused because the ref is supposed to be a real dom element and not a virtual one. It is just htat it is not "remounted".

**Comment by jquense** [comment]
just warning you that it's far more likely you'll get attention here with an example that is runnable and _readable_ :)

**Comment by MagicPoulp** [comment]
do you have a codepen react template that I can reuse?

**Comment by raunofreiberg** [comment]
@MagicPoulp CodeSandBox is used quite frequently for setting up a reproducable and test case of your issue. Try getting started with https://codesandbox.io/s/lOmyoxQw1

**Comment by MagicPoulp** [comment]
False alert. I found the reason.
I have a logic with a certain element that is present at several places on the page. The reptition is on purpose. I just forgot about it.

this.preRef was overwritting with one variable for sevral elements.
