### ISSUE TITLE
react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed

### ISSUE THREAD

**Issue by lsiden** [facebook/react#12330]
When I install node_modules from scratch, npm generates the above warning, because React 16.x is now the latest.

I just verified that removing react-addons-test-utils does not alter any tests.

npm 5.7.1
node v8.6.0
possum commit 7f8ae68 (current master)

**Comment by gaearon** [comment]
There is no bug here. `react-addons-test-utils` doesn't exist in React 16. Use `react-dom/test-utils` instead.
