### ISSUE TITLE
mac os install a problem

### ISSUE THREAD

**Issue by ting106** [facebook/react#12345]
npm WARN deprecated express@2.5.10: express 2.x series is deprecated
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for rimraf@>2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mojito'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/futing/.npm/_logs/2018-03-08T10_57_12_399Z-debug.log
futingdeMacBook-Pro:www futing$ vim package.json
futingdeMacBook-Pro:www futing$ sudo npm install -g create-react-app create-react-app demo
npm WARN deprecated express@2.5.10: express 2.x series is deprecated
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for rimraf@>2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mojito'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/futing/.npm/_logs/2018-03-08T11_00_29_580Z-debug.log

**Comment by ting106** [comment]
npm vdersion 5.7.1

**Comment by anderysenuta** [comment]
"sudo npm install -g create-react-app create-react-app demo"
The problem in the DEMO package..

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
