### ISSUE TITLE
[15.6.2] setState callback does not fire

### ISSUE THREAD

**Issue by wojtekmaj** [facebook/react#12354]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have the following piece of code in my fairly simple component:

```js
this.setState({ value: nextValue }, callback);
```

It works perfectly in React 16, but not in 15.6.2. On 15.6.2, callback does not fire. I investigated and saw this in react.development.js:

```js
this.updater.enqueueSetState(this, partialState, callback, 'setState');
```

which clearly marks callback as one of the accepted arguments of enqueueSetState. However, when we go to the function that's being called, in ReactUpdateQueue.js:

```js
enqueueSetState: function (publicInstance, partialState) {
```

now we see this argument is ommited. I don't know if that helps, anyway, the callback is not fired whatever I try to do.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Here's a simple example for reproduction: https://codesandbox.io/s/2kz06l3p0

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.6.1, 15.6.2 (not tested other 15.x)
NOT React 16.x

**Comment by jmz7v** [comment]
@wojtekmaj I'm trying to reproduce your example but I'm having trouble with saving the value from date into the state, the `changeSelectedDate` function is not being called for me. [https://codesandbox.io/s/8220m93wl9](https://codesandbox.io/s/8220m93wl9)

**Comment by wojtekmaj** [comment]
@jmz7v Exactly what I'm facing. When you look under the hood, this is the line that is being called when Calendar component thinks it should call onChange:

`this.setState({ value: nextValue }, callback);`

If you look into `<Calendar />`'s state, you will see that value is indeed changed, but callback is not called.

This is a fragment from Calendar component, exact step in which setState is called:

![obraz](https://user-images.githubusercontent.com/5426427/37333620-1b5b04a2-26aa-11e8-82f3-121464851920.png)

As you can see, the next step after updating state, a callback from line 203 should be called. So I put a breakpoint inside this function, and yet, it never reaches it.

**Comment by wojtekmaj** [comment]
I honestly have my mind blown. When I change the minimal reproduction ( https://codesandbox.io/s/2kz06l3p0 ) so that I copy the whole Calendar.jsx, straight from the newest version into the same code here, it all works ( https://codesandbox.io/s/ko3n899jr3 )

There is a difference though! When I call this.setState, the same very line, now this.setState is calling a different function!

Here's the setState in the first example that DID NOT work:

![obraz](https://user-images.githubusercontent.com/5426427/37335946-2fd3a6fe-26b0-11e8-851b-c6f9db672c04.png)

Here's the setState in the second example that DID work:

![obraz](https://user-images.githubusercontent.com/5426427/37335967-3def3938-26b0-11e8-8fd3-ad8eb0aade4d.png)

Hmm... After all, it looks like actually there are two different versions of react and somehow react-calendar library has its own version imported...? 😨

**Comment by wojtekmaj** [comment]
Okay, at this point I'm 100% sure it's a version conflict cause by invalid dependencies installed by npm. I'm closing this as it's clearly not on React side.

By the way, if anyone would like to help me with defining a package.json file for a package I'm publishing that:
1) Uses React 16.2 for test etc, so has to have react@^16.2.0 at dependencies
2) Is compatible with React >=15.5, so should not install React 16.2 on the side for React 15.x users

then your help will be much appreciated :)

**Comment by joshua703** [comment]
@wojtekmaj did you ever get the configuration sorted out for this issue?

**Comment by wojtekmaj** [comment]
Yes. Just make sure that you have matching react and react-dom versions installed, and that your dependency is not misconfigured to require a different, specific react version on its own.
