### ISSUE TITLE
Potential Future Bug in getEventKey for Edge with Synthetic Event normalization.

### ISSUE THREAD

**Issue by CapTec** [facebook/react#12356]
**Bug**

**Current behavior**
React currently normalizes keyboard events cross-browser by falling back on the native KeyboardEvent.keyCode property and using a dictionary object to normalize the key. As noted in the source, getEventKey is used for "Normalization of deprecated HTML5 `key` values".

Edge currently does not implement the correct key values and this normalization will fall back to KeyboardEvent.keyCode. KeyboardEvent.keyCode is deprecated and may be dropped at any time.

Microsoft as per https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15907408/ have fixed this issue, but it has not yet been released to insider preview releases. This means there is the potential for the KeyboardEvent.keyCode to be removed from Edge before the fix is made public. It may be a good idea to not rely on keyCode in this instance.

Refer to https://github.com/facebook/react/blob/5bd2321ae3dd7d68ac02dee3c3f271e9d0ee8784/packages/react-dom/src/events/getEventKey.js Line 103

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react-dom version 16.2.0, potentially affects future versions of Edge.

**Comment by jquense** [comment]
Thanks for the heads up. I think it'll be fairly unlikely that Edge will do that, since it'll probably break a lot of websites. Deprecated things on the Web rarely ever actually get removed :P 

That said, maybe we should try and fallback to `.code` but, it's almost no support right now
