### ISSUE TITLE
addEventListener not working properly in componentDidUpdate

### ISSUE THREAD

**Issue by benwiley4000** [facebook/react#12360]
**Do you want to request a *feature* or report a *bug*?**
Bug!

**What is the current behavior?**
When I update event listeners by removing old listeners and adding new ones on an element obtained by React ref in `componentDidUpdate` (React 16.3 alpha), my handlers don't register properly. If I take out the part where I remove listeners, or put the whole thing inside a `setTimeout`, it works fine. **This worked fine when I was doing it in componentWillReceiveProps but I moved this part to componentDidUpdate for React 16.3.**

My code is kind of like:
```jsx
// does NOT work
componentDidUpdate(prevProps) {
  for (const eventType in prevProps.eventHandlers) {
    this.audio.removeEventListener(eventType, prevProps.eventHandlers[eventType]);
  }
  for (const eventType in this.props.eventHandlers) {
    this.audio.addEventListener(eventType, this.props.eventHandlers[eventType]);
  }
  // ...
}

// DOES work!
componentDidUpdate(prevProps) {
  // for (const eventType in prevProps.eventHandlers) {
  //   this.audio.removeEventListener(eventType, prevProps.eventHandlers[eventType]);
  // }
  for (const eventType in this.props.eventHandlers) {
    this.audio.addEventListener(eventType, this.props.eventHandlers[eventType]);
  }
  // ...
}

// DOES work!
componentDidUpdate(prevProps) {
  setTimeout(() => {
    for (const eventType in prevProps.eventHandlers) {
      this.audio.removeEventListener(eventType, prevProps.eventHandlers[eventType]);
    }
    for (const eventType in this.props.eventHandlers) {
      this.audio.addEventListener(eventType, this.props.eventHandlers[eventType]);
    }
  });
  // ...
}

render() {
  return <audio ref={a => this.audio = a} />;
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Unfortunately I can't reproduce in a simple example but you can check out and build the [`next`](https://github.com/benwiley4000/react-responsive-audio-player/tree/7235ba9908bbd493e431d123406fcee063a1eefc) branch of react-responsive-audio-player and run `npm run dev` to see the behavior (example.html adds a listener which should run when volume toggles from muted to unmuted). [`componentDidUpdate`](https://github.com/benwiley4000/react-responsive-audio-player/blob/next/src/AudioPlayer.js#L245) 

**What is the expected behavior?**

Listener adding should work fine

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I tested React 16.3-alpha.1. I think the issue also exists in React 15 - I was able to reproduce the problem locally with React 15 but I had to make some manual tweaks to create-react-context to make it backward compatible (I've now [published a polyfill](https://github.com/benwiley4000/react-dot-fragment) to make this sort of thing easier).

**Comment by Axnyff** [comment]
Why do you want to remove the event listener? If you try to add an event listener that was already there, nothing happens, you can't attach twice the same function for a given event type.

    let a = 0;
    const func = () => { a = a +1; console.log(a)};
    document.addEventListener("click", func);
    document.addEventListener("click", func);
    document.addEventListener("click", func);

In here, each click will increment a only by one.

**Comment by benwiley4000** [comment]
@Axnyff because the event handler's behavior may have changed when the props updated.

**Comment by Axnyff** [comment]
Either it's the same function and you can't add it multiple times, either it's a different function and you can't remove it that way.

**Comment by benwiley4000** [comment]
@Axnyff please re-read the code snippet in the description. On each prop update we remove the listener from the previous props and add the listener from the new props. This could possibly be optimized by only adding/removing if the function identity changed. Does it make sense to you now? :)

**Comment by Axnyff** [comment]
My bad, I read too fast, sorry.

I had a look and it's a bit tricky, I don't know if it is really a React bug or something normal. It looks like you're removing your event listener before it can listen to the event and adding a new one after the firing of the event.

I think if you'd only remove the old event listeners instead of replacing the listener it should work.

**Comment by aweary** [comment]
@benwiley4000 if you add some logging within the `for..in` loops, is the code running for the expected handlers? Can you please try using both the latest alpha, and the latest stable 16 release? Thanks!

**Comment by benwiley4000** [comment]
Sorry for not following up quickly - I've been on vacation. I'll try to get to this soon.

**Comment by gaearon** [comment]
Closing per lack of follow up

**Comment by silversonicaxel** [comment]
I would like to open it again, if possible.

Currently working with

- "react": "^16.5.1",
- "react-dom": "^16.5.1",


In my componentDidUpdate I have 

- addEventListener operation that manage a click on some list elements
- a setState that manages eventually a scroll of these list elements inside a container

There is a specific scenario with a specific case (container with internal auto scrolling to display the eventual already selected list element + scroll (only) up to click and select another element) where it seems that the listener is referring to a situation pre auto scroll, meaning that the click is detected on the list element that would have been in the position if the pre auto scrolling of the container was not done.
It is a bit complicated and particular situation. But only in that specific scenario the click was not working properly.

Adding a setTimeout without any timing as second parameter, all works fine.
It seems that the indeed it is a matter of timing where the timeout helps the managing of the listener.

**Comment by akhilathinkster** [comment]
Any updates here?
