### ISSUE TITLE
Porting libraries from Preact [Question]

### ISSUE THREAD

**Issue by k1r0s** [facebook/react#12364]
Hi, I just want to ask a question

Im a Preact user, never tryed React, I only did a course a couple of months ago. But now I have to use React for a project and I'm trying to port one of my libraries: https://github.com/k1r0s/preact-bind-group

This library aims for easy form setup
```jsx

<FormGroup watch={change => this.setState({ ...change })}>
      <div className="field">
         <label className="label">Email</label>
         <div className="control">
            <input data-bind="mail" className="input"/>
         </div>
      </div>
     <div className="field">
      <label className="label">Contraseña</label>
      <div className="control">
         <input data-bind="pass" type="password" className="input"/>
     </div>
  </div>
  <div>
     <a onClick={_ => this.doLogin(this.state)} className="button is-primary">Submit</a>
  </div>
</FormGroup>
```

My code works perfecly on Preact but Im facing issues on React, for example input is loosing focus everytime I time on the form rather than update field value.

This is the React example: https://codesandbox.io/s/9jv6n8mnrp

This is the Preact which is working: https://codesandbox.io/s/wmpv1o4z8

This library keeps an internal state to manage field values and events.. what Im doing wrong? help appreciated

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by k1r0s** [comment]
@aweary please can you answer it? On React example, if I remove the keys from the cloned elements 

L85
```
    let newProps = { ...props, key: `fg${FormGroup.getReactKey()}` };

``` 

to 

```
    let newProps = { ...props };

``` 
then the code works, but I get warnings about children iterators, why?

**Comment by TrySound** [comment]
@k1r0s Because all array elements should have explicit `key` with unique value

```js
const A = ({ data }) => (
  <div>
    {data.map(datum =>
      <div key={datum.id}>{datum.value}</div>
    )}
  </div>
)
```

**Comment by k1r0s** [comment]
but if I put the keys, my code doesn't work lol @TrySound
