### ISSUE TITLE
question about setTimeout effect of two  react demo

### ISSUE THREAD

**Issue by yangdonglai** [facebook/react#12361]
I am a react learner. I'm counfuse by two react demo
[demo1](https://8nv081l708.codesandbox.io/)
[demo2](https://xj4j54lk9z.codesandbox.io/)

>[demo1](https://8nv081l708.codesandbox.io/)

```js
import React from "react";

let num = 0;
export default class Hello extends React.Component {
  state = {
    loading: false,
    data: 0
  };
  componentDidMount() {
    // setTimeout(() => {
    // const button = document.getElementById('button');
    const button = this.button;
    console.log("button first click");
    button.click();
    console.log("button second click");
    button.click();
    // }, 3000);
  }
  delay = () => {
    const count = num++;
    console.log("out", count);
    this.setState({
      loading: true
    });

    setTimeout(() => {
      const data = Math.random() * 10;
      console.log("in", count);
      this.setState({
        data: data,
        loading: false
      });
    }, 1000);
  };
  render() {
    const { loading, data } = this.state;
    if (loading) {
      return <p>this is loading</p>;
    }
    return (
      <div>
        <p>{`data: ${data}`}</p>
        <p>
          <button
            id="button"
            ref={ref => (this.button = ref)}
            onClick={this.delay}
          >
            update
          </button>
        </p>
      </div>
    );
  }
}
```

> [demo2](https://xj4j54lk9z.codesandbox.io/)
```js
import React from "react";

let num = 0;
export default class Hello extends React.Component {
  state = {
    loading: false,
    data: 0
  };
  componentDidMount() {
    setTimeout(() => {
      // const button = document.getElementById('button');
      const button = this.button;
      console.log("button first click");
      button.click();
      console.log("button second click");
      button.click();
    }, 3000);
  }
  delay = () => {
    const count = num++;
    console.log("out", count);
    this.setState({
      loading: true
    });

    setTimeout(() => {
      const data = Math.random() * 10;
      console.log("in", count);
      this.setState({
        data: data,
        loading: false
      });
    }, 1000);
  };
  render() {
    const { loading, data } = this.state;
    if (loading) {
      return <p>this is loading</p>;
    }
    return (
      <div>
        <p>{`data: ${data}`}</p>
        <p>
          <button
            id="button"
            ref={ref => (this.button = ref)}
            onClick={this.delay}
          >
            update
          </button>
        </p>
      </div>
    );
  }
}

```

the only different code is in **componentDidMount()**
the console message is aslo different about two demo
> [demo1](https://8nv081l708.codesandbox.io/) result
![image](https://user-images.githubusercontent.com/17786362/37339919-3e4bf352-26f7-11e8-8c38-06064ba3b466.png)

> [demo2](https://xj4j54lk9z.codesandbox.io/) result
![image](https://user-images.githubusercontent.com/17786362/37339948-55f0bd6c-26f7-11e8-93b6-6a6e79df986d.png)

**Comment by yangdonglai** [comment]
so i'm confused how  does **setTimeout** change  the run result of react

**Comment by jburghardt** [comment]
This tracker is used for bugs and features,

if you have questiones you can ask have a look here: https://facebook.github.io/react/community/support.html

That being said,
i could not reproduce your error with the code you provided

**Comment by yangdonglai** [comment]
I will copy this question in other place.

@jburghardt Otherwise, I dont understand this line.
> i could not reproduce your error with the code you provided

I have save these two demo in codesandbox. [demo1](https://codesandbox.io/s/8nv081l708) and [demo2](https://codesandbox.io/s/xj4j54lk9z)
they really have different console message.

>demo1
<img width="479" alt="sync" src="https://user-images.githubusercontent.com/17786362/37413602-63b1e444-27e2-11e8-833f-ea0f5211ae06.png">

>demo2
<img width="469" alt="async" src="https://user-images.githubusercontent.com/17786362/37413657-7b67b56e-27e2-11e8-944b-eaaa40ddf6c6.png">

**Comment by aweary** [comment]
As mentioned, please refer to the [Community Support](https://facebook.github.io/react/community/support.html) resources for usage questions. Thanks!
