### ISSUE TITLE
Add a Top-level API for detecting whether an element is a HTML element

### ISSUE THREAD

**Issue by m93a** [facebook/react#12369]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
In the React's [Top-level API](https://reactjs.org/docs/react-api.html#isvalidelement) there is a function for detecting whether an object is a valid React element. But there's no official way to detect a HTML element specifically.

**What is the expected behavior?**
It would make sense to have another function for checking whether an object is a ReactHTMLElement. 

**What would be the use cases?**
In TypeScript it would be a useful type guard. Apart from TypeScript, it would be cool eg. if you needed your component to add a class to all of its children – you'd have to decide whether you can add the class directly, or whether you have to wrap the child in `<span class=foo></span>`.

**Implementation draft**
```typescript
const listOfHTMLElements: Readonly<string[]> = [
    'a', 'abbr', 'address', 'area', 'article', 'aside', 'audio',
    'b', 'base', 'bdi', 'bdo', 'big', 'blockquote', 'body', 'br',
    'button', 'canvas', 'caption', 'cite', 'code', 'col', 'colgroup',
    'data',  'datalist',  'dd', 'del',  'details', 'dfn',  'dialog',
    'div', 'dl',  'dt', 'em',  'embed',  'fieldset', 'figcaption',
    'figure',  'footer', 'form', 'h1', 'h2',  'h3', 'h4',  'h5', 'h6',
    'head', 'header', 'hgroup',  'hr', 'html', 'i', 'iframe', 'img',
    'input', 'ins', 'kbd', 'keygen', 'label', 'legend', 'li', 'link',
    'main', 'map', 'mark', 'menu', 'menuitem', 'meta', 'meter', 'nav',
    'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p',
    'param', 'picture',  'pre', 'progress',  'q', 'rp', 'rt', 'ruby',
    's', 'samp', 'script', 'section', 'select', 'small', 'source',
    'span', 'strong', 'style', 'sub', 'summary', 'sup', 'table',
    'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title',
    'tr', 'track', 'u', 'ul', 'var', 'video', 'wbr', 'webview'
];

export function isHTMLElement(elem: any): elem is React.ReactHTMLElement<any>
{
    return React.isValidElement(elem)
        && typeof elem.type === 'string'
        && listOfHTMLElements.indexOf(elem.type) >= 0;
}
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All.

**Comment by nmain** [comment]
One example use case where this would help me:
```
	<ElementSize onResize={this.onContentSizeChanged}>
		<div className="myContent">{/* stuff */}</div>
	</ElementSize>
```

`ElementSize` uses `React.Children.only` to pick out its child, and then uses a `ref` to attach a `ResizeObserver` to it.  I need to verify that the child element is in fact an HTML element and not something else.

**Comment by raunofreiberg** [comment]
What about using the [react-is](https://github.com/facebook/react/tree/master/packages/react-is) package? This is built for exactly your described purpose.

**Comment by raunofreiberg** [comment]
> In the React's Top-level API there is a function for detecting whether an object is a valid React element. 

The [react-is](https://github.com/facebook/react/tree/master/packages/react-is) package is built specifically to serve that purpose.

Otherwise, I don't see why this API needs to be related to React itself. You could just use the helper function internally in your application instead.

**Comment by m93a** [comment]
@raunofreiberg Yes, you could code the helper function yourself. But making a list of all HTML elements isn't exactly what I call “efficient” or “comfort”. And it mostly relies on *undefined behavior* as I needed to look into the source code to make this function, the specs weren't enough. Furthermore the `react-is` package isn't visibly mentioned in the specs and tutorials. If we add `isHTMLElement` to the package, it needs to be referenced visibly, or else it isn't going to help anyone.

**Comment by jquense** [comment]
I don't think this is a good fit for a React API. ReactDOM is trying harder to have _less_ whitelists like this, and it  generally doesn't even know if something is a valid element type, heck RD will try and render any string type as an element. From what i've gathering from why you'd want this I think it's more than enough to just check if the type is a `string`

**Comment by aweary** [comment]
As @jquense said, we want less whitelisting. Using `react-is` along with a package like [`html-tags`](https://www.npmjs.com/package/html-tags) is likely a sufficient user-space solution, though I'm inclined to think that inspecting `type` on a ReactElement at runtime isn't a good idea anways.
