### ISSUE TITLE
ReactDOM minified development build error misleadingly says there's a development build of React, rather than ReactDOM

### ISSUE THREAD

**Issue by dtaub** [facebook/react#12362]
**Do you want to request a *feature* or report a *bug*?**
Bug-ish (error clarification)

**What is the current behavior?**
When including a minified development build of ReactDOM the error reads: `It looks like you're using a minified copy of the development build of React.`

**What is the expected behavior?**
The error correctly notified me that I was using a minfied development copy, but it took me a while to realize it meant ReactDOM and not core React.
I feel it should more accurately read: `It looks like you're using a minified copy of the development build of ReactDOM.`

**Comment by aweary** [comment]
I think most applications run minification after bundling, so specifying React or ReactDOM wouldn't make a difference. Is that not the case for you? There's a [new error now for this](https://github.com/facebook/react/commit/34092a0f242c8059fd4cec4970f72d9326f2824d), do you think the new wording and link are helpful enough?
