### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by alopezsanchez** [facebook/react#12367]
Hello!

I want to start contributing to React and I don't know how to start... I took a look to the `Good First Issue`, but I think I can help increasing the code coverage. What do you think?

I'm taking a look to the coverage report, but I don't know which is the best place to start. Can you give me a recommendation?

Thanks!

**Comment by aweary** [comment]
@alopezsanchez we don't have any directed efforts for increasing code coverage, but if you find an opportunity to add some useful tests, feel free to open a PR.
