### ISSUE TITLE
react 16.3 new context API basic intent

### ISSUE THREAD

**Issue by thifranc** [facebook/react#12372]
**Do you want to request a *feature* or report a *bug*?**
misunderstanding

**What is the current behavior?**
Impossible to render a component which is a provider furnished by createContext function
trying to follow those articles :  
[whats new in react](https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b)
[react new context API](https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
[code sandBox example](https://codesandbox.io/embed/k591mqw98o)
sourceCode of codeSandBox :  
```
import React, { Component, createContext } from "react";
import { render } from "react-dom";

const CartState = createContext({
  open: false
});

class CartStateProvider extends Component {
  state = { open: false };

  render() {
    return (
      <CartState.Provider value={this.state.open}>
        {this.props.children}
      </CartState.Provider>
    );
  }
}

class App extends Component {
  render() {
    return (
      <div>
        <CartStateProvider>
          <CartState.Consumer>
            {({ open }) => {
              return <div>{open ? "open" : "closed"}</div>;
            }}
          </CartState.Consumer>
        </CartStateProvider>
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
```

**What is the expected behavior?**
It should render "closed"

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
i'm testing with react 16.3.0-alpha.1, as it is new feature, it cannot work in previous releases

**Comment by thifranc** [comment]
code was correct, react-dom was not up to date

**Comment by stompingyaya** [comment]
PayPal.me/SompongKarnsanga
100000

ในวันที่ พ. 14 มี.ค. 2018 17:55 Thibault Francois <notifications@github.com>
เขียนว่า:
