### ISSUE TITLE
Formatting numbers with toLocalString() in a controlled input

### ISSUE THREAD

**Issue by paulcredmond** [facebook/react#12373]
**Do you want to request a *feature* or report a *bug*?**

A bug (suspected).

**What is the current behavior?**

I'm trying to use `toLocaleString()` with a controlled input on a text or tel field.

Either the numbers are removed after after 3 entered or I get a NaN.

Possibly related: https://github.com/facebook/react/issues/11877

https://codesandbox.io/s/91q75k22mo

**What is the expected behavior?**

Number is formatted using `toLocaleString()`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.2.0, Chrome 64, Mac OS 10

**Comment by paulcredmond** [comment]
Have it working with `Number(e.target.value.replace(/\D/g, ''));`

**Comment by paulcredmond** [comment]
Have it working with `Number(e.target.value.replace(/\D/g, ''));`

**Comment by mike20007** [comment]
It does not work for float value like 10002.54
Any thoughts?

**Comment by paulcredmond** [comment]
Convert to an integer?
