### ISSUE TITLE
Different behavior of updating DOM while using ternary operator vs inline approaches

### ISSUE THREAD

**Issue by satispunk** [facebook/react#12378]
**Do you want to request a *feature* or report a *bug*?**
Not sure if this is bug of feature
**What is the current behavior?**

There are 2 very similar cases, often chosen by matter of preferences, but work with DOM is different 

In the first case icon is updated in DOM 
```
const Expandable = ({expanded}) => {
  const expandedIcon = <DropdownIcon className="expanded" />
  const collapsedIcon = <DropdownIcon className="collapsed" />
  const icon = expanded ? expandedIcon : collapsedIcon
  return <div>{icon}</div>
}
```

In the second case icon is mounted/unmouted
```
const Expandable = ({expanded}) => {
  const expandedIcon = <DropdownIcon className="expanded" />
  const collapsedIcon = <DropdownIcon className="collapsed" />

  return <div>
    {expanded && expandedIcon}
    {!expanded && collapsedIcon}
  </div>
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/jn7mm2l735

**What is the expected behavior?**

I expected "update" in both cases but might be wrong

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Windows 10, Chrome 64

**Comment by hejld** [comment]
Hey Pavel, in your second second case React is not able to match your component in the original tree with the one in the subsequent tree. You can solve this by using keys.

**Comment by jquense** [comment]
Yeah, these cases look similar but aren't the same. In the second case React sees two children: `false` and `icon`, and `icon`/`false` depending on the expanded value. So instead of swapping between the two elements it's unmounted the first and mounting the second. You _could_ tell react these are the same element with a `key` prop, but it'll still end up doing more work than you'd want, e.g. moving the the element from index `0` to `1` and back

You can use a ternary inline as well FYI.
```jsx
const Expandable = ({expanded}) => {
  const expandedIcon = <DropdownIcon className="expanded" />
  const collapsedIcon = <DropdownIcon className="collapsed" />

  return <div>{expanded ? expandedIcon : collapsedIcon}</div>
}
```

or just
```
<DropdownIcon className={expanded ? 'expanded' : 'collapsed'} />
```

**Comment by satispunk** [comment]
@jquense @hejld  Thanks for answers guys!
