### ISSUE TITLE
when use webpack4.0.1 bundle a react App, ERROR like this

### ISSUE THREAD

**Issue by yegao** [facebook/react#12374]
ERROR in ./node_modules/_react@16.2.0@react/cjs/react.production.min.js
Module not found: Error: Can't resolve 'fbjs/lib/emptyFunction' in '/Users/zr/work/react.family.ink/node_modules/_react@16.2.0@react/cjs'
 @ ./node_modules/_react@16.2.0@react/cjs/react.production.min.js 10:80-113
 @ ./node_modules/_react@16.2.0@react/index.js
 @ ./src/app.js
 @ multi ./src/app.js

ERROR in ./node_modules/_react@16.2.0@react/cjs/react.production.min.js
Module not found: Error: Can't resolve 'fbjs/lib/emptyObject' in '/Users/zr/work/react.family.ink/node_modules/_react@16.2.0@react/cjs'
 @ ./node_modules/_react@16.2.0@react/cjs/react.production.min.js 10:46-77
 @ ./node_modules/_react@16.2.0@react/index.js
 @ ./src/app.js
 @ multi ./src/app.js

ERROR in ./node_modules/_react@16.2.0@react/cjs/react.production.min.js
Module not found: Error: Can't resolve 'object-assign' in '/Users/zr/work/react.family.ink/node_modules/_react@16.2.0@react/cjs'
 @ ./node_modules/_react@16.2.0@react/cjs/react.production.min.js 10:19-43
 @ ./node_modules/_react@16.2.0@react/index.js
 @ ./src/app.js
 @ multi ./src/app.js

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by yegao** [comment]
OK,sorry and thank you！
