### ISSUE TITLE
propagateContextChange Stuck in an Infinite Loop

### ISSUE THREAD

**Issue by grahammendick** [facebook/react#12389]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

In the process of converting [my Navigation router](https://grahammendick.github.io/navigation/) to the new context API I found that `propagateContextChange` sometimes gets stuck in an infinite loop. I’ve created a [JsFiddle of the problem](https://jsfiddle.net/pxzo0foq/42/). If you click the 'Name' sort Hyperlink **two times** then, on the **second click**, it enters the infinite loop. The JsFiddle is as simple as I could make it. For example, if you get rid of the 'Date of Birth' column then the problem doesn’t happen!?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/pxzo0foq/42/

**What is the expected behavior?**

It should not get stuck in an infinite loop

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React version 16.3.0-alpha.2. 
This is to do with the new Context API introduced in 16.3

**Comment by gaearon** [comment]
Can you try to turn it into a test, similar to other tests here?
https://github.com/facebook/react/blob/master/packages/react-reconciler/src/__tests__/ReactNewContext-test.internal.js

**Comment by grahammendick** [comment]
Ok, here’s a dependency-free JsFiddle of the bug, https://jsfiddle.net/cgkhsxhd/2/

**Comment by gaearon** [comment]
I made a reduced case.

```js
var Context = React.createContext(null);

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { reverse: false };
  }
  handleClick() {
    this.setState(({ reverse }) => {
      return { reverse: !reverse }
    })
  }
  renderItem(id) {
  	return (
      <div key={id}>
        <Context.Consumer>
          {({ update }) => (
            <button onClick={() => this.handleClick()}>
              test
            </button>
          )}
        </Context.Consumer>
        <div>oops</div>
      </div>
    );
  }
  renderList() {
    var list = [1, 2].map(id => this.renderItem(id));
    if (this.state.reverse) {
      list.reverse();
    }
    return list;
  }
  render() {
    return (
      <Context.Provider value={{}}>
        {this.renderList()}
      </Context.Provider>
    );
  }
}

ReactDOM.render(
  <App />,
  document.getElementById('content')
);
```

Seems like "oops" node is essential to reproduce.

**Comment by jquense** [comment]
I may have run into a similar case with `forwardRef` but haven't been able to reproduce it specifically yet (All I know is it goes away when i remove `forwardRef`). I don't have reason to think it's related to this, but I figured i'd at least share quickly in case it provides any context (ha) for folks who understand how it works :P

**Comment by gaearon** [comment]
@jquense Do you mean in combination with new context?

**Comment by jquense** [comment]
no, not directly at least. Like i said i don't have a sense that they're related, but in case the maybe share a common internal path or something i'm mentioning it. I'll open a separate issue if I can reproduce it simply!

**Comment by gaearon** [comment]
Probably unrelated, the problem in this issue is localized to a loop that happens inside the context path.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/12402

**Comment by grahammendick** [comment]
Thanks @gaearon I'll give it a retest with the next alpha/beta release

**Comment by grahammendick** [comment]
@gaearon I like [your test](https://github.com/facebook/react/pull/12402/files#diff-0ec201d2f87127ead696e6f5681e6830R766). Now you know what the bug is, it might be worth renaming the test and adding an assert?  Something like `it('should set the child fiber of the top level parent')`?

**Comment by gaearon** [comment]
I thought a bit but I can't really come up with a good name. Any name like this would be too tied to implementation details. We just want to have a regression test. If we add more similar tests I can rename it to something like `Regression #12389` but for now I think what we have there is fine.

**Comment by grahammendick** [comment]
You got me, I shouldn't've put the work fiber in the test name 😄 How about `Re-render consumer and sibling`?

**Comment by gaearon** [comment]
I don't care about test names strongly. The issue link will be more useful anyway.

**Comment by grahammendick** [comment]
Works in the latest alpha. Thanks again for the fix 👍
