### ISSUE TITLE
Gitter Room

### ISSUE THREAD

**Issue by ghulamhussain** [facebook/react#12388]
please make a react room on gitter

**Comment by TrySound** [comment]
https://reactjs.org/community/support.html#reactiflux-chat

**Comment by ghulamhussain** [comment]
i know but a gitter room would also be better . it doest cost a thing .

**Comment by aweary** [comment]
Thanks for the request, but I think the existing community chat support groups listed on the website are sufficient. They're great resources for support, driven by a strong community.

Opening a Gitter channel would potentially weaken the community by fragmenting it further (nobody wants to sit in a bunch of different chat services), and it would also imply some level of official support, which the React team doesn't currently have time for.

Reactiflux is great, we highly recommend it!
