### ISSUE TITLE
Could we get more friendly error stack from ErrorBoudary?

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#12390]
**Do you want to request a *feature* or report a *bug*?**

Maybe a feature?

**What is the current behavior?**

Currently the error Component Stack(i.e. `arguments[0]` of `componentDidCatch`) is something like:
```
in Foo
in Connect(Foo)
in Bar
in div
in ...
```
But in production, they would be formatted to:
```
in t
in Connect(t)
in s
in t
in ...
```
This is almost **useless for our debugging.**

**What is the expected behavior?**

I want to request a feature which allow us to define our **own** static **componentName field**, the reason why don't use `displayName` is that the `displayName` is used by react-devtools or others libs, if we use this static field for our components, **everyone** could see our components/project structure(maybe there is others potential risk) , that's not what we expect.

So, if react could support custom static **componentName field**, e.g. `myDisplayName`, then we could set `myDisplayName` field for our components and react-devtools **can't inspect this**. And react read `myDisplayName` field rather than `displayName` to get the component name and insert they into the error stack string and then call the `componentDidCatch`.

I know that if we implement this, we **still** could get the components/project structure by using some libs like babel to decompile or just make react-devtools to support this field. But that increase the cost.

**Comment by jquense** [comment]
>  if we use this static field for our components, everyone could see our components/project structure(maybe there is others potential risk)

I think your concern there is probably unfounded. Anyone can already do that by looking at the js code, and any added name field will necessarily be visible in the source code, since the stack traces are built running runtime. Not to mention the _name_ you give the component is far less interesting to anyone than what the component does, which is already out in the open in the code.

**Comment by NE-SmallTown** [comment]
Thanks for you response.

As I said:
> I know that if we implement this, we still could get the components/project structure by using some libs like babel to decompile or just make react-devtools to support this field. But that increase the cost.

I agree this is like we are deceiving ourselves, but you have to acknowledge that it make **more less people** to get the results directly which we don't want them to look

**Comment by jquense** [comment]
> but you have to acknowledge that it make more less people to get the results directly which we don't want them to look

I don't think I agree with that. It's already _very_ easy to do this, and adding another property doesn't improve the situation substantially. Hit f12 in a browser and click the `pretty print` button, all your components are already there to see from the identifier names, where they are used. More to the heart of the issue tho, knowing the component names isn't a security risk, so effort to obfuscate them I don't think is worth it. As is it is the code is not even minified to obfuscate the names, that is purely a practical approach to making the code _smaller_

**Comment by NE-SmallTown** [comment]
> Hit f12 in a browser and click the pretty print button, all your components are already there to see from the identifier names, where they are used.

See, you have to do **so many things** to get the answer, if there is not a lib to do this automatically, you have to look through the whole src code or write a lib by yourself. On the other hand, many people open the react-devtools and if they don't see the correct component name, **they won't think** they can get them in the src code or even search/write a lib to do this.

> More to the heart of the issue tho, knowing the component names isn't a security risk, so effort to obfuscate them I don't think is worth.

I know, I just want **most people** can't get that. That's make sense for us.

> that is purely a practical approach to making the code smaller

Yep, but for debugging, you have to do something like add static `displayName` to components or something else like that. That's a **Tradeoffs**.

**Comment by jquense** [comment]
The core problem is still not clear, why do you want to prevent people from seeing component names? 

It's unclear what problem this would solve, since it doesn't seem (to me) that anyone seeing component names via development tooling is a problem

**Comment by aweary** [comment]
Expanding the API surface just for some very minor security through obscurity isn't a great trade-off. I agree with everything @jquense said as well. If the name is defined anywhere on the component then it's accessible to anyone who can inspect the page. Also, if the security of your application depends on access to your component's names then you may want to re-consider whatever security architecture you've implemented.

For all those reasons, I'm going to close this out and recommend you use `displayName`

**Comment by NE-SmallTown** [comment]
> The core problem is still not clear, why do you want to prevent people from seeing component names?

If it don't be prevented. Everyone can analyze to get the whole project structure, how you fetch data, how you do ssr, how you use redux, they can write posts and criticize you. I don't mean I need everyone can't see the component name, this is just like form verification on front-end, developers can directly do fetch(i.e. bypass the verification), but this is not the reason we don't do verification.
