### ISSUE TITLE
Is there a way to access new context api within ComponentDidMount?

### ISSUE THREAD

**Issue by grillorafael** [facebook/react#12397]
We are building a react mapbox gl module and we use clone and inject props today.

We were looking into using the 16.2.0 context api but I saw that it will have a new one on 16.3.0 but I can’t seem to find a way to read context details
On componentDidMount lifecycle (which makes sense for me to use on the map implementation).

Is there a way around this ?

**Comment by grillorafael** [comment]
Adding a example that I'm trying to have this working: https://codesandbox.io/s/l20yn296w7

**Comment by TrySound** [comment]
This is how it can be achieved with new api.

```js
class BaseMapElement extends React.Component {
  componentDidMount() {
    console.log(this.props.context);
  }

  render() {
    return null;
  }
}

const MapElement = () => (
  <Context.Consumer>
    {context =>
      <BaseMapElement context={context} />
    }
  </Context.Consumer>
)
```

**Comment by grillorafael** [comment]
So the only way to access through the Component's life cycle is to redirect into Props?

**Comment by jquense** [comment]
The higher order component that redirecs to props is a good pattern,but for cases where don't want the  extra component usually wat I do is store the context value on the component instance like: `this.contextValue = value` then access it in the life cycle hooks. It's a bit ugly but that's ok generally I think since your opting out of the nicer, hoc, pattern as an optimization

**Comment by porfirioribeiro** [comment]
I'm facing the same dilemma.
There should be a easy way to access or call context in life-cycle methods.
We might need to initialize stuff, check and fetch data or even clean-up on unmount.
People are doing it now with the current supposedly broken context.
Yes it can be solved by wrapping our component in another component! But feels like a workaround more than a solution.

**Comment by gaearon** [comment]
>store the context value on the component instance like: this.contextValue = value then access it in the life cycle hooks

I’m pretty sure this is unsafe in async mode. Please don’t do this. cc @acdlite

**Comment by jquense** [comment]
>  I’m pretty sure this is unsafe in async mode. Please don’t do this.

How would this be unsafe (and in what way)? It's really unclear in all this talk about async mode, what "unsafe" even means. It's starting to feel like a boogyman who behavior is irrational and unpredictable, which doesn't fill folks with a lot of assurance in a system that is generally liked for it's straightforward, easily understandable, data flow model. I feels like components are back in pre 0.13 land where they are magic objects again.

It's also easy to say "Just add another component", but that's often onerous, and introduces it's own category of bugs and challenges.

**Comment by jquense** [comment]
sorry ^ if the above sounds annoyed/angry, i didn't intend that tone! on a phhhhooone

**Comment by grillorafael** [comment]
It did sound angry haha but I get your point and I share your questions about how/why it will be unsafe

**Comment by gaearon** [comment]
>It's starting to feel like a boogyman who behavior is irrational and unpredictable

I’m sorry, but we’ve been working on a guidance with specific suggestions for over a month now. Please give us time to collect and publish them as a blog post. It is also difficult to discuss without actual alphas to play with, which is also something we’ve been working hard on.

So we have to either not say anything at all, or warn in advance about things that won’t work well. We err on the side of warning but I can see how it can look like we’re making it more difficult for you. I’m sure that once the code is out and you can play with it, you’ll see what we mean, and it’ll make more sense.

>How would this be unsafe (and in what way)? 

Did you get a chance to watch [my talk](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html)? This will be a bit hard to explain if you haven’t seen the second part of it, because it wouldn’t be clear *why* we are doing this. So I’m asking you to watch it. I hope that my talk will convince you we’re aiming to solve a broad class of problems that plagued React since the beginning, and that these features are worth revisiting some assumptions we might have gotten used to.

Assuming you’ve seen the talk, here’s a more specific explanation about this particular case. In order to be able to “suspend” rendering like I showed in the demo, React needs to be able to call `render()` at any point in time, potentially with different props. For example if may set `this.props` and `this.state` to props from a new screen (that’s being loaded), call `render`, but then set it to old `this.props` and `this.state` when rendering in response to an interaction on the current version of the tree (e.g. if I press on something while the new screen is loading).

In async, the rule of thumb is: only lifecycles like `componentDidMount`, `componentDidUpdate`, and `componentWillUnmount` and ref callbacks execute at well-defined points in time with props and state that correspond to what’s on the screen. Luckily we only have a few other lifecycles that don’t neatly fit into this picture, and we are introducing better alternatives for them (`getDerivedPropsFromState`, `getSnapshotBeforeUpdate`). This will be a gradual migration. Again, it’s all going to be in the blog post.

Now to the root of this issue. In async mode, *React doesn’t make guarantees about when and in which order it calls the `render` method*. Which is really something React never guaranteed in the first place—it just happened to be the same order every time. Storing a field in `render` and then reading it in a lifecycle is not “safe” because you might store a field at the time React called `render` with different props (such as for a suspended tree that isn’t ready yet).

**Comment by gaearon** [comment]
>There should be a easy way to access or call context in life-cycle methods.
>Yes it can be solved by wrapping our component in another component! But feels like a workaround more than a solution.

I understand it *feels* like it’s an extra wrapper, but it’s what *makes the new context fast*. If we didn’t have explicit wrapper nodes in the tree we wouldn’t be able to quickly “find” components that need to update.

If you need to access context in lifecycle, take it as a prop.

```js
class Button extends React.Component {
  componentDidMount() {
    alert(this.props.theme);
  }

  render() {
    const { theme, children } = this.props;
    return (
      <button className={theme ? 'dark' : 'light'}>
        {children}
      </button>
    );
  }
}

export default React.forwardRef((props, ref) => (
  <ThemeContext.Consumer>
    {theme => <Button {...props} theme={theme} ref={ref} />}
  </ThemeContext.Consumer>
));
```

This is almost the same amount of lines as a `contextTypes` definition.

**Comment by bvaughn** [comment]
> Yes it can be solved by wrapping our component in another component! But feels like a workaround more than a solution.

Just wanted to second what Dan said that this is the child function / render prop approach is the official API for the new context- so please use it and let React worry about making sure it's fast. (It should be!)

 > How would this be unsafe (and in what way)?

The draft [Strict Mode docs](https://deploy-preview-587--reactjs.netlify.com/docs/strict-mode.html#detecting-unexpected-side-effects) also touch on some of why mutating the instance (which is just another type of side effect) is dangerous in async mode.

**Comment by grillorafael** [comment]
We have a experimental branch following the guidelines proposed here. Can anyone have a look to see if it make sense? https://github.com/commodityvectors/react-mapbox-gl/pull/11

**Comment by bvaughn** [comment]
I'm not familiar with this library, so I don't know if people ever make use of refs with its components- but if they did, the `withContext` mixin on that PR might be a good use case for the [new `forwardRef` API](https://deploy-preview-587--reactjs.netlify.com/blog/2018/03/20/react-v-16-3.html#forwardref-api).

**Comment by grillorafael** [comment]
That make sense. Thanks for the reference. I'm going to close this issue for now.

**Comment by bvaughn** [comment]
There are some subtle differences that might make that approach a bad idea. For example, if `MapElement` was a class component that used refs, the refs would not yet be set when the `runOnMount` callback was run.

I would suggest using a HOC approach for this instead. 😄 

https://reactjs.org/docs/context.html#consuming-context-with-a-hoc

**Comment by grillorafael** [comment]
We took the approach like the react docs and what people said here. It is working well for us so far.

https://github.com/commodityvectors/react-mapbox-gl/blob/master/src/Map.js#L63

**Comment by lostpebble** [comment]
> There are some subtle differences that might make that approach a bad idea. For example, if MapElement was a class component that used refs, the refs would not yet be set when the runOnMount callback was run.

Thanks for the feedback @bvaughn . At the moment I'm using it purely as a kind of state proxy component which adds / removes things from the UI depending on what is mounted within the context tree. Kind of like portals but within the React component tree. So not actually rendering children or dealing with refs at all.

Will keep in mind if I need to do anything that interacts with refs.

**Comment by bruno02100** [comment]
Had the same issue, this is what I did:

CourseContext.js

`import React from "react";

const { Provider, Consumer } = React.createContext();

export class CourseProvider extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      activeStep: 1,
      idCourseVersion: "",
      setActiveStep: activeStep => this.setState({ activeStep }),
      setIdCourseVersion: idCourseVersion => this.setState({ idCourseVersion })
    };
  }
  render() {
    return <Provider value={this.state}>{this.props.children}</Provider>;
  }
}

export const CourseConsumer = Consumer;

export const withCourseContext = Component => (
  (props) =>
  <CourseConsumer>
    {context => <Component {...props} courseContext={context} />}
  </CourseConsumer>
);
`

`
...

export default compose(
  withCourseContext,
  withRouter,
  ....
)(Modules);
`

Just added a HOC to the context file and used it in the component where I needed to access the context in the lifecycle.

**Comment by AmnArora** [comment]
Hey everyone, 

I need context data in lifecycle methods. so, I followed the HOC approach after seeing the first few comments and passed the context data as props.
Everything is working as expected. But now, I want to write unit test cases for the components but I am unable to do so.

I would really appreciate it if someone could share how I can write test cases for this scenario.

I am using enzyme, enzyme-adapter-react-16 and jest but having some troubles in doing so.

**Comment by pgarciacamou** [comment]
@AmnArora, what we do is the following (note, this might not be the consensus), we export the "naked" component as well and then import in our tests and manually pass the props.

Also, we created this https://www.npmjs.com/package/react-context-consumer-hoc that consumes multiple context.

**Comment by bvaughn** [comment]
> Everything is working as expected. But now, I want to write unit test cases for the components but I am unable to do so.

@AmnArora Why are you unable to write a unit test? What have you tried? What error are you seeing?

**Comment by AmnArora** [comment]
@pgarciacamou  Firstly thanks for the quick reply. Well, after not finding anything on the web and posting the query here. I came up with the same solution you mentioned.

The Test cases are working now but this seems like a work around. I'll take a look at https://www.npmjs.com/package/react-context-consumer-hoc and discuss with my team.

Thanks. :100:

**Comment by AmnArora** [comment]
@bvaughn The thing is earlier when I was using redux for state management, I shallow copied the Component and used dive() and instance() methods to get the instance of the component.

But none of these methods were available when using context API. 

And when I wasn't using any of these methods I was getting the following error: **_unknown node with tag 12_**

**Comment by bvaughn** [comment]
Gotcha.

Both of these sound like issues with the version of Enzyme you're using not properly supporting the new context API. That's unfortunate.

**Comment by davalapar** [comment]
I got massive distatste for `redux` and `unistore` (a lot of code pollution) which led me to using the following setup which allows our nested components to access a single global state.

Wrapper function `withGlobalContext` exposes `globalContext` in the props of the wrapped components. `globalContext` has an `update` function which effectively updates it, just like the example from the docs:

https://reactjs.org/docs/context.html#updating-context-from-a-nested-component

Everything else that shouldn't be in the global state (ie. text input values) are stored within the local state of each nested components.

```
const GlobalContext = React.createContext();
export const withGlobalContext = ChildComponent => () => (
  <GlobalContext.Consumer>
    {globalContext => <ChildComponent globalContext={globalContext} />}
  </GlobalContext.Consumer>
);
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { update: this.setState.bind(this) }; // eslint-disable-line
  }

  render() {
    return (
      <GlobalContext.Provider value={this.state}>
        { /* nested stuff */ }
      </GlobalContext.Provider>
    );
  }
}
```

```
import { withGlobalContext } from '../App';
const NestedComponent = ({ globalContext }) => {
  {/* content */}
  <button onClick={() => globalContext.update({ key: 'value'})}>
    update global context
  </button>
};

NestedComponent .propTypes = {
  globalContext: PropTypes.object.isRequired,
};

export default withGlobalContext(UpdateAccount);
```

**Comment by abhi16z** [comment]
Hi,

is this problem solved?

I has a scenario where I had 3 components. Creator, Display, Cells.
Cell has my render logic which is used in both Creator and Display. 

Currently I need to pass the status if the item is being created or it has to display. I have used Cells in different locations so I need to pass the status as props separately. So I wanted to use context for status but problem is I wanted to modify context only if Display component was mounted. Can we achieve this is React's current versions? (I am using React 16.7)

**Comment by bvaughn** [comment]
There have been a [couple of comments above showing how to access `Context.Consumer` values in `componentDidMount`](https://github.com/facebook/react/issues/12397#issuecomment-375501574). Did you try them? Did they not work for some reason?

**Comment by gaearon** [comment]
Note that React 16.6 added a new `contextType` API for classes which makes reading new context in `componentDidMount` easy.

https://reactjs.org/docs/context.html#classcontexttype

**Comment by bvaughn** [comment]
Yeah, provided you only need to use a single context in your component– `contextType` is a convenient option.

**Comment by eldargab** [comment]
> Note that React 16.6 added a new `contextType` API for classes which makes reading new context in `componentDidMount` easy.

It does not. Even if a single context type is enough, Class.contextType breaks inheritance. The same is true about HOC.

**Comment by bvaughn** [comment]
We are pretty explicit in our docs about recommending composition over inheritance for reusing code between components. Beyond that, I don't really understand what you're saying.

**Comment by eldargab** [comment]
> We are pretty explicit in our docs about recommending composition over inheritance...

That's too broad...

The case I am struggling with right now, is that I have a family of components with a bunch of common functionality needed to support their implementation. Everything is modelled by inheritance perfectly, except... context bits! 

Given that it seems I mess with context only in situations like this, context API is pretty frustrating.

>...which is what this thread is about...

Yes, this comment is slightly off-topic.

**Comment by JulioOrellana** [comment]
contextType breaks redux store :/

**Comment by garrettgsb** [comment]
> Note that React 16.6 added a new contextType API for classes which makes reading new context in componentDidMount easy.

> Yeah, provided you only need to use a single context in your component– contextType is a convenient option.

Is there no way to compose contexts before assigning them to `MyCoolComponent.contextType`? 

My read is that for now, if we want a component that can:

a) Consume multiple contexts
b) Use things from those contexts in methods other than `render`

This means that we're stuck with the pattern described where **the wrapper consumes the context and passes props to the child.**

I feel that an ideal situation would be that I could write something like this, and get the best of both worlds (i.e. multiple contexts available throughout the whole class):

```
MyCoolComponent.contextType =  composeContexts(OneContext, TwoContext, RedContext, BlueContext)
```

Is there any way to do this?

**Comment by shures** [comment]
It works for render method, but not working for any other method....any idea ??

**Comment by DongShi** [comment]
Hey there.
Is there any possibility to use the new context api in a class component's constructor?

We are migrating our projects from v15.x to v16.x, one of the tasks is to use the new context api
In our project, we use css-modules + isomorphic-style-loader , the latter exposes some APIs to inject the component stylesheets into DOM.

In V15, we put those APIs into the old context api, and let each component to get it via something like

```javascript
    class MyComp extends Component {
        static contextTypes = {
                insertCss: PropTypes.func
           }
         ....
         componentWillMount () {
                // insert a style tag for this component
               this.removeCss = this.context.insertCss(myStyles)
         }
    }

```
In V15, we can put this in the componentWillMount. This will ensure the component get correct style before render.

In V16, however, the componentWillMount is marked as unsafe and will be deprecated in future.
So our immediate thoughts would be to put our context.insertCss call into component's constructor.

However, seen from the [document](https://reactjs.org/docs/legacy-context.html),

> If contextTypes is defined within a component, the following lifecycle methods will receive an additional parameter, the context object:

> constructor(props, context)

This usage (with context as a 2nd parameter) will be deprecated too.

I tried the new context api, assigning MyComp.contextType = StyleContext
Yet I find that I get this.context is undefined in constructor.
```javascript
    class MyComp extends Component {
        static contextType = StyleContext
         
         constructor (props) {
             super(props)
             console.log(this.context) // undefined
         }
 
    }
```

Is there any practical guide on how to use context in constructor?

Any advice?

**Comment by JulioOrellana** [comment]
> Hey there.
> Is there any possibility to use the new context api in a class component's constructor?
> 
> We are migrating our projects from v15.x to v16.x, one of the tasks is to use the new context api
> In our project, we use css-modules + isomorphic-style-loader , the latter exposes some APIs to inject the component stylesheets into DOM.
> 
> In V15, we put those APIs into the old context api, and let each component to get it via something like
> 
> ```js
>     class MyComp extends Component {
>         static contextTypes = {
>                 insertCss: PropTypes.func
>            }
>          ....
>          componentWillMount () {
>                 // insert a style tag for this component
>                this.removeCss = this.context.insertCss(myStyles)
>          }
>     }
> ```
> 
> In V15, we can put this in the componentWillMount. This will ensure the component get correct style before render.
> 
> In V16, however, the componentWillMount is marked as unsafe and will be deprecated in future.
> So our immediate thoughts would be to put our context.insertCss call into component's constructor.
> 
> However, seen from the [document](https://reactjs.org/docs/legacy-context.html),
> 
> > If contextTypes is defined within a component, the following lifecycle methods will receive an additional parameter, the context object:
> 
> > constructor(props, context)
> 
> This usage (with context as a 2nd parameter) will be deprecated too.
> 
> I tried the new context api, assigning MyComp.contextType = StyleContext
> Yet I find that I get this.context is undefined in constructor.
> 
> ```js
>     class MyComp extends Component {
>         static contextType = StyleContext
>          
>          constructor (props) {
>              super(props)
>              console.log(this.context) // undefined
>          }
>  
>     }
> ```
> 
> Is there any practical guide on how to use context in constructor?
> 
> Any advice?

You can do like this instead of using contextType

```js
class MyComponent extends React.Component {
   render(){
       const {
         //props including context props
       } = this.props;
       return(<View />);
   }
};

const withContext = () => (
  <MyContext.Consumer>
    { (contextProps) => (<MyComponent {...contextProps}/>)}
  </MyContext.Consumer>
);

export default withContext;
```

**Comment by bor-yo** [comment]
Not sure if this is the new context api since I'm new to React but this is how I do it without extra components and looks like it works:

componentWillMount = async () => (
        <UserContext.Consumer>
            {context = await (async () => {
                console.log('componentWillMount')
                if (Platform.OS === 'android' && !Constants.isDevice) {
                    this.setState({
                        errorMessage: 'Oops, this will not work on Sketch in an Android emulator. Try it on your device!',
                    });

                } else {

                    console.log('this.props.navigation.state.params: ', this.props.navigation.state.params);
                    console.log('context: ', context);
                    // if()
                    await this._getLocationAsync();
                }
            })()}</UserContext.Consumer>)

**Comment by MelMacaluso** [comment]
For whoever like me are struggling just use inside your sub-component:

[useContext()](https://reactjs.org/docs/hooks-reference.html#usecontext)

For example:

```
const context = useContext(yourContext)

MainComponent.Subcomponent = () => {
 const context = useContext(context)
 
  useEffect(()=> {
    console.log(context)
  })
}
```
