### ISSUE TITLE
Keep the children mounted but replace the parent

### ISSUE THREAD

**Issue by Orelc** [facebook/react#12393]
Hi,

I'm trying to do something like this:

```
const Container = (props) => props.someCondition? (
    <ContainerType1>
        {props.children}
    </ContainerType1>
) : (
    <ContainerType2>
        {props.children}
    </ContainerType2>
);

const App = (props) => (
    <Container someCondition={props.someCondition} >
        <ComponentThatDoesAsyncFetches1 />
        <ComponentThatDoesAsyncFetches2 />
        <ComponentThatDoesAsyncFetches3 />
    </Container>
);
```

Basically what I want is a situation where App is rerendering on a changing boolean prop (Imagine someCondition has an actual changing value), and a different container will render depending on its value, while maintaining the same children inside. Problem is, that those children are doing async fetches (on DidMount), but they re-mount and lose their state while the containers change. 

Any idea how can I achieve this with the children still mounted even if their parent changed?

Thanks in advance!

**Comment by jmz7v** [comment]
Hi Orelc,

For me this could be solved in two different ways:
The data that the children will receive could be placed on the parent component, and passed down via props to the children, then you can make changes and still keep the data available
or
Have the data from those components stored in a completely different way, like Redux.

**Comment by gaearon** [comment]
Sorry, this is not supported.

You'll need to keep the parent type the same.
