### ISSUE TITLE
why im getting key iterator warnings?

### ISSUE THREAD

**Issue by k1r0s** [facebook/react#12395]
If I put back the keys then my form stops working

please refer to https://github.com/facebook/react/issues/12364

**Comment by jburghardt** [comment]
As already stated, the issue tracker is for bug reports and feature requests.
If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

I can recommend the reactjs IRC channel.

if you want to look deeper into react keys: https://reactjs.org/docs/lists-and-keys.html

**Comment by k1r0s** [comment]
nice!
