### ISSUE TITLE
React not able to get the application environment at UI with DefinePlugin?

### ISSUE THREAD

**Issue by VishalGulati** [facebook/react#12400]
I am working on a React application. In there I have to showcase different functionality based on whether app is running in dev mode or production. My query is how do I get this application environment in my React code?

I tried below code but it did not work:

    // webpack.config.js
      plugins: [
        new webpack.DefinePlugin({
          appenv: JSON.stringify('dev')
        })
      ]
    // any-component.js
    console.log("Env: " + appenv);
    
    //error
    appenv is not defined.

I also tried `EnvironmentPlugin` of webpack but got same error. Could anyone help? TIA.

CC: @rouzbeh84 @simon04

**Comment by raunofreiberg** [comment]
Where are you trying to access the variable?

Have you tried assigning it to a variable beforehand, like:

```
const APP_ENV = appenv;
```

And used that one instead?

**Comment by aweary** [comment]
If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
