### ISSUE TITLE
Circle Ci failing test

### ISSUE THREAD

**Issue by JoeCortopassi** [facebook/react#12406]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
Broken build process due to invalid response from http://react.zpao.com/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Any new PR will have the "facebook-open-source-bot" post something similar to this:
<img width="775" alt="screen shot 2018-03-20 at 6 39 41 am" src="https://user-images.githubusercontent.com/943606/37652617-1614ef8e-2c0a-11e8-8185-c6405aa07b8f.png">
this error will also cause the CircleCI tests to fail
<img width="768" alt="screen shot 2018-03-20 at 6 43 38 am" src="https://user-images.githubusercontent.com/943606/37652610-0ebc9138-2c0a-11e8-90f2-905652100621.png">
```
Error:  { FetchError: invalid json response body at http://react.zpao.com/builds/master/_commits/e1ff342bf7f451fb995e0ea2bfb10889deef022f/results.json reason: Unexpected token < in JSON at position 0
    at /home/circleci/project/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'FetchError',
  message: 'invalid json response body at http://react.zpao.com/builds/master/_commits/e1ff342bf7f451fb995e0ea2bfb10889deef022f/results.json reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
```

**What is the expected behavior?**
Valid json response

**Comment by gaearon** [comment]
I think it should be fine if you rebase now. There were a few broken builds on master which caused the upload to fail.
