### ISSUE TITLE
Passing elements to a function requires manual keys to be present

### ISSUE THREAD

**Issue by hyperknot** [facebook/react#12409]
**Do you want to request a *feature* or report a *bug*?**
Bug/feature

**What is the current behavior?**
React requires manual keys present on each tag when passing an element via a function to render. If not, it gives a key warning.

I'm passing an element created from JSX via a mobx store. This element requires manual keys to be present on each child tag. Even for simple example this is incredibly hard to do, and doesn't allow using any child component, thus severely limiting this functionality.

The passed JSX can be considered static, so the key requirement shouldn't apply here at all.

Is it possible to tell React to consider an element as static?

Codesandbox minimal case:
https://codesandbox.io/s/4qm2p107r7

```
export class OverlayStore {
  @observable activePopup = null

  @action
  setPopup(element) {
    this.activePopup = element
  }
}

@observer
export class App extends React.Component {
  render() {
    return <div>{overlayStore.activePopup}</div>
  }
}

const overlayStore = new OverlayStore()
render(<App />, document.getElementById('root'))

overlayStore.setPopup(
  <p>
    Long<br key="1" />
    Text<br key="2" />
    <a href="/link" key="3">
      Link
    </a>
  </p>
)
```

**What is the expected behavior?**
Should not require manually setting keys to values like 1, 2, 3, etc.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest stable dependencies via Codesandbox. Chrome / macOS but doesn't matter.

**Comment by aweary** [comment]
Hey @hyperknot, React doesn't require keys when rendering constant elements like this. The problem here is that MobX is wrapping the children in an `ObservableArray`, which I assume is some internal MobX class.

![screen shot 2018-03-20 at 10 00 56 am](https://user-images.githubusercontent.com/6886061/37670092-ae7f5ce4-2c25-11e8-9b28-273f87ac7386.png)

That means that what's returned from render is actually an array, so the key is required.

**Comment by hyperknot** [comment]
OK, I'll bring this to mobx issue.

On the React side, one workaround I found is to just renderToString + dangerouslySetInnerHTML, as in:

```
<div dangerouslySetInnerHTML={{ __html: renderToString(overlayStore.content) }} />
```

I guess this looks super ugly but is at least making React handle that element as a static node, and not something it should worry about. One question with this though: is this safe? I mean is renderToString doing the needed sanitisations, etc. so that dangerouslySetInnerHTML isn't actually dangerous?
