### ISSUE TITLE
server side react-dom render hrefLang as hrefLang

### ISSUE THREAD

**Issue by webcarrot** [facebook/react#12403]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
react-dom/server render "hrefLang" as "hrefLang"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem:**
https://codesandbox.io/s/3x09moz93q

**What is the expected behavior?**
Render "hrefLang" attribute as "hreflang" on server-side.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.0.0 - 16.4.0
Works in 15.6.2

**Comment by gaearon** [comment]
HTML is case-insensitive. I agree it can be a bit surprising but there is no practical difference to the browser, and it might be a bit faster for us to avoid lowercasing it.

**Comment by gaearon** [comment]
Please file a new issue with more specific information (which attributes Google requires and with which casing). Thanks!

**Comment by gaearon** [comment]
What attributes are hard coded? I don't understand the question.

If you're having troubles with some practical reasons (such as the one above), as I said earlier, please file a new issue with proposed changes and specific attributes that are causing issues. Thanks!

**Comment by mike-marcacci** [comment]
React itself (and maybe this is just in development) is actually aware of `itemProp`/`itemScope`/etc attributes:

https://github.com/facebook/react/blob/9ff3ce67eaf07e8f62704133a8d748f1c0679a59/fixtures/attribute-behavior/src/attributes.js#L955

And it even suggests that we use them over all-lowercase attributes:

https://github.com/facebook/react/blob/9ff3ce67eaf07e8f62704133a8d748f1c0679a59/packages/react-dom/src/shared/possibleStandardNames.js#L84

Given that the only real use for these rendering html attributes, and now that react passes through unknown attributes, I'm curious if all those lines can be deleted?

**Comment by gaearon** [comment]
These lines don't exist the production version. The first match is from a fixture (a test) we use, and the second one is from a DEV-only helper mapping that's eliminated in production.

**Comment by mike-marcacci** [comment]
Ah gotcha. Thx for the info. I opened #13162 for the micro data case, per your suggestion.
