### ISSUE TITLE
Change on <i> ag isn't enough to make my component re-render

### ISSUE THREAD

**Issue by gfelot** [facebook/react#12417]
***Bug* && *Question***

**What is the current behavior?**

It's was a bug on my code and thanks to SO I find a way to fix it. But I would like an explanation why I had this behavior.

I made a form with redux-form (using Bulma for the CSS).
I wanted to add an icon to the right of the input, in a `<i>` tag  like Bulma's doc show us, after a focus to have a visual validation.

Green FontAwesome icon if the input is valid. Another one in red if not.

The first re-render with the right icon was OK but if I had an invalid field and then write something in it, the icon doesn't change even if I see the props that should trigger the new icon was changing.

Trying to debug, I had make it work without changing my logic with just replacing the `<i>` tag to a `span`, or a `h1`... and I had the right behavior.

(i dunno how to make my example work on fiddle)

In this state it doesn't work with `i` but uncomment the `span` and comment the `i` and it's working.

```javascript
import React from 'react';

const InputItem = ({ spec, input, meta: { touched, error } }) => {

  const successIconRight = {
    color: '#2ecc71'
  };

  const errorIconRight = {
    color: '#e74c3c'
  };

  const { label, type, placeholder, iconLeft, iconRight } = spec;

  const renderIcon = () => {

    if (touched && error) {
      return (
        <span className="icon is-small is-right">
          <i className="fas fa-ban" style={errorIconRight}/>
          {/* <span style={errorIconRight}>NON</span> */}
        </span>
      )
    } else if (touched && !error) {
      return (
        <span className="icon is-small is-right">
          <i className={iconRight} style={successIconRight}/>
          {/* <span style={successIconRight}>OUI</span> */}
        </span>
      )
    }
  }

  return (
    <div className="field">
      {label && <label className="label">{label}</label>}
      <p className="control has-icons-left has-icons-right">
        <input
          {...input}
          className="input"
          type={type}
          placeholder={placeholder}
        />
        <span className="icon is-small is-left">
          <i className={iconLeft} />
        </span>
        {renderIcon()}
      </p>
    </div>
  );
};

export default InputItem;
```

Posting on SO someone ring my bell. The two component where two close from each other for react to interpret it as a change with a `<i>` tag. So no re render.  A span was ok.

I had to manually add a `key` props on the parent `span` to make it work like so in my `renderIcon` func.

```javascript
const renderIcon = () => {

    if (touched && error) {
      return (
        <span className="icon is-small is-right" key={0}>
          <i className="fas fa-ban" style={errorIconRight}/>
          {/* <span style={errorIconRight}>NON</span> */}
        </span>
      )
    } else if (touched && !error) {
      return (
        <span className="icon is-small is-right" key={1}>
          <i className={iconRight} style={successIconRight}/>
          {/* <span style={successIconRight}>OUI</span> */}
        </span>
      )
    }
  }
```

So my question is why it's not enough for react to render when a `<i>`  tag change ?

**Comment by aweary** [comment]
React should re-render all element types if their props change. Is it possible that you weren't passing the correct icon to the `i` element? If you can provide an example reproducing your issue, we can investigate it, but I suspect this isn't a bug at all.

If you have further questions, please check our community support resources:
https://facebook.github.io/react/community/support.html
