### ISSUE TITLE
Why refs are immutable? "object is not extensible"

### ISSUE THREAD

**Issue by wzup** [facebook/react#12413]
Why I cannot set `this.refs`? Why `refs` are immutable?

```
constructor(props, context) {
    super(props, context);
    this.refs = { bar: null };
}

// I set ref
<section ref={node => this.refs.foo = node}></section>

// Now this throws. Why?
<button onClick={ev=>{
    this.refs.foo.value = 'bar'; // Uncaught TypeError: Cannot add property foo, object is not extensible
   this.refs.bar = '1';  // Uncaught TypeError: Cannot add property foo, object is not extensible
}}>ONE</button>
```

Why this works well in JS, but in React it doesn't work?
```
document.getElementById("mytext").value = "My value";
```

**Comment by JoeCortopassi** [comment]
`this.refs` is reserved for the api that stores stuff like `<Foo ref="bar" />`, and [is no longer used/recommended](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs). What you likely want to do is 
```
constructor(props, context) {
    super(props, context);
    // removed the this.refs = {}
}

<button ref={input => this.oneButton = input}>ONE</button>
```

**Comment by gaearon** [comment]
Yep, it's intentional because it's an existing React API. Just put refs on the instance itself instead.

**Comment by wzup** [comment]
@gaearon 
> Just put refs on the instance itself instead.

But they are stored top-level.
And I want to have my `refs` under a namespace. Is it possible? Before all `refs` were placed to `this.refs.inputNode`. Now they are placed top-level `this.inputNode`.

Thanks

**Comment by jamiewinder** [comment]
You could add them to something like `myRefs` instead, if you don't like having them on the instance for whatever reason.
