### ISSUE TITLE
Controlling radio input with checked and onClick props gives warning

### ISSUE THREAD

**Issue by rodgobbi** [facebook/react#12410]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
In any `input` of type `radio`, if I control it with the `checked` props and a handler to the `onClick` event, I still receive a warning that the form field needs a `onChange` handler. To suppress this warning, I pass an useless inline function to the `onChange` props.
**What is the expected behavior?**
Not give a warning if I control the component with an event other than `onChange`. I can't assure all possibilities but it's very common for me to control `radio` inputs with `onClick` handlers.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.2.0

I didn't test this behavior with a `checkbox` input, but I wonder that the same behavior would be desirable.

**Comment by jquense** [comment]
That is expected. the controlling handler for inputs is `onChange` not `onClick`, you can use that one, or provide a noop (`()=>{}`) function to onChange to silence the warning. 

As an side tho, react's onChange for radio/checkbox uses onClick internally so you don't really gain anything from using onClick in your own code. Admittedly though, that behavior is likely to change in future versions

**Comment by drKnoxy** [comment]
@jquense this kind of makes it hard to overcome the change from https://github.com/facebook/react/issues/1471 where the onChange handler no longer report true->true

Adding an empty function seems kind of hacky.
