### ISSUE TITLE
jestDiff() call in toWarnDev() returns null, making test failure confusing

### ISSUE THREAD

**Issue by gaearon** [facebook/react#12427]
<img width="953" alt="screen shot 2018-03-22 at 4 47 40 pm" src="https://user-images.githubusercontent.com/810438/37785026-037d0788-2df1-11e8-9cbd-5b9e2b2d10db.png">

Caused by this line:

https://github.com/facebook/react/blob/40fa6160534e2bc67b0c43f0b32dcdd1d214068b/scripts/jest/matchers/toWarnDev.js#L52

Calling `jestDiff` with two different strings returns `null`.

**Comment by bvaughn** [comment]
> Calling `jestDiff` with two different strings returns `null`.

[Documentation for `jest-diff`](https://github.com/facebook/jest/blob/3c65b72d88744a24d1eb985f147707b5d1c532dd/packages/jest-diff/src/index.js#L52-L53) says:
> Generate a string that will highlight the difference between two values with green and red. (similar to how github does code diffing)

And the [Flow return type for the method](https://github.com/facebook/jest/blob/3c65b72d88744a24d1eb985f147707b5d1c532dd/packages/jest-diff/src/index.js#L54) is `?string`.

The problem we seem to be hitting is [this line](https://github.com/facebook/jest/blob/3c65b72d88744a24d1eb985f147707b5d1c532dd/packages/jest-diff/src/index.js#L95). It looks like `jest-diff` just fails to handle single-line strings? It looks like the `return null` should actually be `return diffStrings(a, b, options);`?

**Comment by bvaughn** [comment]
Related Jest issue https://github.com/facebook/jest/issues/5657
