### ISSUE TITLE
Why I can't set value for selects programatically in React? How to do it?

### ISSUE THREAD

**Issue by wzup** [facebook/react#12422]
Here is how I can set selects using pure JS. Plain, simple and effective:
```
<select id="mySelect">
    <option value="1">1<option>
    <option value="2">2<option>
</select>

$("#mySelect").value = '1'
```

Not with React. This approach for some reason doesn't work in React. Select values are not updated. Why? How can I do in React?

I have a usual DOM `<form>` with a `[reset]` button. On click `reset` the default browser behavior is to clear all form fields. Why I can't set select after it?
```
onReset(ev) {
    // First I update state. 
    // And AFTER the DOM has been updated, I want to set selects programatically using refs
    this.setState((state, props) => {
        return {
            birthday: moment(this.props.user.birthday),
            error: null,
            foo: this.props.foo
        }
    }, () => {

        // These both approaches do not work! Why?
        this.country.value = this.props.user.country;
        this.role.value = this.props.user.role;

        ReactDOM.findDOMNode(this.country).value = this.props.user.country;
        ReactDOM.findDOMNode(this.role).value = this.props.user.role;
    });
}

render() {
    return (
        <form action="" onReset={ (ev)=> { this.onReset(ev) } }>

            <select id="country" ref={ node => this.country = node }>
                <option value="us">USA<option>
                <option value="ca">Canada<option>
            </select>

            <select id="role" ref={ node => this.role = node }>
                <option value="admin">Admin<option>
                <option value="user">User<option>
            </select>

            <botton type={'reset'}>
        </form>
    )
}
```

Don't advice me to use controlled components. I know that. I want to set it as above, without rolling back to controlled components.

**Comment by liximomo** [comment]
```html
<form action="" onreset="onReset()">
  <select id="country" >
      <option value="us">USA</option>
      <option value="ca">Canada</option>
  </select>

  <select id="role" >
      <option value="admin">Admin</option>
      <option value="user">User</option>
  </select>

  <button type="reset">rest</button>
</form>
<script>
  function onReset() {
    window.country.value = 'ca';
    window.role.value = 'user';
  }
</script>
```
You can't even without react!

**Comment by wzup** [comment]
@liximomo LOL)
That's not an option unfortunately.

**Comment by jburghardt** [comment]
`$("#mySelect").value = '1'`
this is not pure JS, this is JQuery.

what version are you using ? i cant find the onReset event in the synthetic events docs from react.
And whats wrong with using "onChange" to select an a selecte value ?

**Comment by liximomo** [comment]
@wzup Callback is not equal to asynchronous! Actually, you did have changed the value.  It just then get reset by reset event. Same as the above no-react demo. You can make it work this way:
```js
this.setState((state, props) => {
        return {
            birthday: moment(this.props.user.birthday),
            error: null,
            foo: this.props.foo
        }
    }, () => {
       // make it asynchronous
        setTimeout(() => { 
          this.country.value = this.props.user.country;
          this.role.value = this.props.user.role;
        }, 0)    
    });
```

**Comment by wzup** [comment]
@jburghardt 
> this is not pure JS, this is JQuery.

Are you serious? In Chrome console test this on any page that doesn't have jQuery. You'll be surprised.
Actually that was pseudo code, though it works in Chrome w/o jQuery.

> And whats wrong with using "onChange" to select

I have quite a big form with heavy data iterations and it is ineffective to re-render my form on every state update. And I don't use Redux, because I've inherited code from other developer who didn't care about productivity. So I'd like to use `refs` instead.

**Comment by wzup** [comment]
@liximomo 
You are genius! Thanks for clarification. It works. And that sound logical indeed.

**Comment by nhunzaker** [comment]
Hey! Just catching up here. @wzup were you able to sort everything out?

**Comment by jburghardt** [comment]
@wzup thats because $ is a reference to document.querySelector()

**Comment by wzup** [comment]
@nhunzaker 
I used @liximomo 's suggestion https://github.com/facebook/react/issues/12422#issuecomment-375248407. Works well so far.

**Comment by nhunzaker** [comment]
Sounds good!
