### ISSUE TITLE
[Feature] Add ReactDOM.renderSync(...) method

### ISSUE THREAD

**Issue by NeekSandhu** [facebook/react#12447]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`ReactDOM.render(...)` is an async operation

**What is the expected behavior?**
Would be very nice if there was something like `ReactDOM.renderSync` method that would interrupt all pending operations and render the `Element` and put it in `DOM` immediately.

Very critical for my current use case (willing to explain if need be)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.x.x

**Comment by TrySound** [comment]
Yep, use case should be described.

**Comment by NeekSandhu** [comment]
I'm currently working on text editor like vscode but for chrome devtools as a nicer replacement for `Sources` panel.

The editor allows custom file handlers (they register themselves for file extensions), and when matching file is opened they return object like:

```jsx
// custom file handler for `.png`, `.jpeg`, `jpg` and `.psd`
return {
    model: new ImageBuffer(buffer),
    controller: { ... },
    view: <ImageEditor buffer={buffer} />
}
```

Now imagine three tabs are open, `<TextEditor ... />`, `<ImageEditor ... />`, `<TextEditor ... />`

If the editor workspace host mounts those views directly inside render function, like:

```jsx
render() {
    const { activeTab, tabs } = this.state
    return (
        <div className="pane">
            <TabList tabs={tabs} />
            { activeTab.view }
        </div>
    )
}
```

Every time the user switches between `<TextEditor ... />` `<->` `<ImageEditor ... />`, they won't be the same when user switches back to them again, because of how React mounts, unmounts and re-mounts them[1].

So to counter that, I'm manually rendering those views using `ReactDOM.render`.

Views (components) of same type (`ReactElement.type`) share single DOM node, which I manually swap out with another DOM node hosting another group of views. 

This happens without React "unmounting" the node, i.e the components stay virtually mounted, but their hosting DOM nodes are swapped out.

Now the state is preserved because the components never get unmounted [1]

The component that abstracts above mechanism watches for `componentWillReceiveProps` and performs the magic. Since `ReactDOM.render` is async, the changes expected by former action do not take effect synchronously which causes parent components to have to "wait" before things move forward

## Footnotes
[1] One might say that those views should have their visual state "saved" like a snapshot, but trust me, it's not just that, there's also a concept of `TabHandle`s which give access to `controller` returned by file handlers, and those controllers might have `ref` to their `view`. Because of all this, a `view` once mounted cannot be unmounted until the tab is literally closed by the user.

**Comment by NeekSandhu** [comment]
Honorable mentions:

https://redd.it/4pdnvv

https://stackoverflow.com/questions/40319092/how-do-i-do-a-synchronous-reactdom-render

**Comment by gaearon** [comment]
Can you please create a small reproducing example that shows what you're trying to do (in a simplified way)? It's still not quite clear to me what your constraints are. Is there any reason you're not using portals instead of top-level `render` calls? Portals would be flushed together with the rest of the update.

**Comment by NeekSandhu** [comment]
### Introduction
I'm developing an all-in-one editor for web devs, which means being able to open/edit many kinds of files. Each kind of file requires a unique component to view that file.

Example: `<TextEditor ... />` for text files, `<ImageEditor ... />` for image files, and so on.

So the keyword here is "many components at play"

___

### Implementation
`Editor` renders a `Pane`, and `Pane` has render function that looks like so:

```jsx
render() {
    const { activeTab, tabs } = this.state
    return (
        <div className="pane">
            <TabList tabs={tabs} />
            { activeTab.view }
        </div>
    )
}
```

When `activeTab.view` is `<TextEditor ... />`, it will look like:

![](https://i.imgur.com/XLrUJKP.png)

When `activeTab.view` is `<ImageEditor ... />`, it will look like:


![](https://i.imgur.com/oeQxyWF.png)
___

### The problem

Now, imagine the user switching between `hero.png` and `App.js` tabs.

(Assume switching from `App.js` to `hero.png` tab)

Given the current implementation, we know that React will first unmount `<TextEditor ... />` and then mount `<ImageEditor ... />`, and other way around when the user switches back to `App.js` tab.

And *that* is exactly what is undesirable.

Once a tab is opened I want it stay "mounted" until its literally closed by the user. When switching between tabs, I just want them to be temporarily taken off of DOM and inserted back when user switches back to it. That all.

### Solution

AFAIK there's no "native" way to get React do what I want, So I was hoping I could take the control myself, have `ReactDOM.renderSync` the component at a given DOM node(s) and I take care injecting/swapping the DOM node(s) myself. When the tab is closed, I'd do `ReactDOM.unmountComponentAtNode` to do cleanup.

I'm more than happy to consider other possible solutions to tackle this problem, really any kind of help would be appreciated.

**Comment by NeekSandhu** [comment]
More issues with similar issues:
[ReactDOM.render no longer works synchronously in a nested rendering context](https://github.com/facebook/react/issues/12227)
[ReactDOM.render return null](https://github.com/facebook/react/issues/12315)

#BringBackSynchronousRender :P

**Comment by jquense** [comment]
It seems like createPortal is exactly what you want?

**Comment by gaearon** [comment]
Yes, this is why I asked for a small isolated code example. It sounds like portal would solve your problem but it’s hard to say 100% without running the code.

**Comment by NeekSandhu** [comment]
As far as I understand Portals, I guess they just re-route React's output.

React's reconciler still applies diffing on them as usual, which means mounting, unmounting and re-mounting.

Even if I use two different DOM nodes for two different components.

Minimal repro:

https://codesandbox.io/s/4qy0mkz714

Open Devtools console and then click on `Image`, then `Text`, `Image`, `Text` and so on. You should see some message from those components triggered from their `componentWillUnmount` hooks.

**Comment by NeekSandhu** [comment]
Once again, I'm not rendering those components outside of hierarchical DOM tree, something that Portals solve.

I just don't want them to get unmounted (just temporarily taken off of DOM when switching tabs)

**Comment by jquense** [comment]
> I just don't want them to get unmounted (just temporarily taken off of DOM when switching tabs)

This is the bit that is confusing, it not clear how using `ReactDOM.render` achieves this, can you put together an example using your current approach so it's clearer what you are trying to do and how you'r currently accomplishing it? My intuition here is that you don't need `.render` to achieve what you're trying to do, but it's hard to recommend anything without seeing what you _are_ doing

**Comment by gaearon** [comment]
I think your approach is flawed.

>Given the current implementation, we know that React will first unmount <TextEditor ... /> and then mount <ImageEditor ... />, and other way around when the user switches back to App.js tab.

>And that is exactly what is undesirable.

The "React-friendly" solution to this is to keep them *all* mounted, and toggle the visibility of the current one with something like `style={{ display: isCurrentTab ? 'block' : 'none' }}`.

>So I was hoping I could take the control myself, have ReactDOM.renderSync the component at a given DOM node(s) and I take care injecting/swapping the DOM node(s) myself. 

I strongly recommend against a solution like this. It's pretty hard to implement correctly, doesn't propagate context, and in general doesn't buy you anything over the "React-friendly" solution I described above as far as I can see.

**Comment by NeekSandhu** [comment]
@jquense With `ReactDOM.render` I can allocate a fresh/dedicated `HTMLElement` node for each component. That way that isolated React VDom tree will never encounter any other component type.

Then I will manually do `el.replaceChild()` to show active view.

@gaeron The problem might become apparent when there will be 20+ tabs open, imagine all the (extra) DOM nodes in the document. Performance hit is what I'm scared of

**Comment by jquense** [comment]
>  when there will be 20+ tabs open, imagine all the (extra) DOM nodes in the document. Performance hit is what I'm scared of

Have you tried it? Browsers are pretty smart, I'd imagine that the performance you'd see from having hidden DOM nodes is going to be about the same as detached ones, if only because most of the "perf" concern there would be around layout calculation, something that doesn't need to be done on hidden nodes.

> With ReactDOM.render I can allocate a fresh/dedicated HTMLElement node for each component. That way that isolated React VDom tree will never encounter any other component type.


It's unclear why you can't do the same thing (if it's really necessary) with createPortal. Again it'd be helpful if you put together a code sandbox, otherwise i think we'll keep talking past each other.

**Comment by jrylan** [comment]
@NeekSandhu I agree with @gaearon and @jquense  here, browsers are pretty smart and can probably handle this pretty efficiently if you just toggle visibility. You'd also like get a better user experience out of the result as the hidden nodes would naturally retain inner container scroll positions and such.

**Comment by gaearon** [comment]
If you’ve verified that removing them from the document actually gives performance improvements (which is not a given) then a viable strategy is to create divs on demand and then render a bunch of portals that direct output into them. Then use refs to add and remove those divs as necessary. Hope this helps!

**Comment by NeekSandhu** [comment]
I might have to take my "performance" claim/argument back. I tested it and I agree with you guys.

The premise of my argument was the fact that most perf centered libs/apps use removing/adding elements approach. If you guys look into internals of any text editor like CodeMirror or Monaco editor (vscode), you won't see them rendering all 3000 lines in the DOM (and set the ones outside of viewport to be `display: none`), instead they add/remove lines as we scroll.

Another example that made me think that way was [`react-virtualized`](https://github.com/bvaughn/react-virtualized), it also doesn't "hide" the ones not visible, but literally removes them from DOM. Maybe @bvaughn can shed some light on why is that?

**Comment by gaearon** [comment]
>If you look into internals of any text editor like CodeMirror or Monaco editor (vscode), you won't see them rendering all 3000 lines in the DOM (and set the ones outside of viewport to be display: none), instead they add/remove lines as we scroll.

Sure, but do you expect to have thousands of tabs open? In that case the optimization is indeed relevant. In other cases, it's less clear. You can still implement your own logic that only keeps the last N opened files truly "open", but unmounts older nodes. That would still require rendering them from scratch next time they open.

Again, as the ultimate optimization you can do what I described with portals. It shouldn't be that much different from what you attempted to do with `ReactDOM.render`. Your attempt to use portals in https://codesandbox.io/s/4qy0mkz714 looks incorrect to me because you're trying to *imperatively* render into them (which is not how portals work). Instead I'm suggesting returning an array from render (as if you wanted to render all of them), but "directing" them to detached nodes so that you can manage their attachment and detachment in `componentDidUpdate` yourself.
 
Hope this helps!

**Comment by cjativa** [comment]
Question on this maybe @jquense or @gaearon can answer; is `ReactDOM.createPortal(...)` synchronous? 

It doesn't accept a callback function, and when I check the container element (via debugging), the provided React node has not been added into the container.

Is there anyway I can listen for when the node has been placed into the container? Code below

![image](https://user-images.githubusercontent.com/41299115/133823365-331edae2-91f3-4d24-b09d-ffa973588307.png)
