### ISSUE TITLE
A mistake has been found in the Docs

### ISSUE THREAD

**Issue by faremax1992** [facebook/react#12450]
![image](https://user-images.githubusercontent.com/9269277/37873576-0e71df3e-3052-11e8-9217-4ee0c2844a00.png)

In chapter ‘JSX In Depth’, pic. 2, the first parameter of `React.createElement` should be a string with a peer of quotation marks.

**Comment by jacoahmad** [comment]
I see nothing wrong here, as MyButton is a React Component. JSX compiles them to React.createElement if you read the docs carefully. So If you import a component named `MyButton` and use `MyButton` in different component, it will be compiled into something like that picture. #cmiiw
