### ISSUE TITLE
isMounted() is not correct for parents during componentWillMount

### ISSUE THREAD

**Issue by syranide** [facebook/react#1245]
http://jsbin.com/mekuduqi/1/edit

`parent.isMounted() === true`

But it throws:

`Uncaught Error: Invariant Violation: receiveComponent(...): Can only update a mounted component.`

**Comment by stephenjudkins** [comment]
I've found this same problem. Here's a minimal failing example for React 0.12.2: http://jsbin.com/kulukeqacu/1/edit?js,output

However, it appears that this is fixed in 0.13RC: http://jsbin.com/doyipexito/1/edit?js,output. Any ideas which commit fixed this? If there aren't tests which exercise this it might creep back in.

**Comment by julen** [comment]
Same here. Was perhaps 9811b10aa related?

I created a simple test case based on @stephenjudkins's jsbin, which currently passes. Unfortunately I'm unable to run tests in anything besides master so can't really validate.

```javascript
  it("should update parent component's state in componentWillMount", function() {
    // See https://github.com/facebook/react/issues/1245
    var A = React.createClass({
      getInitialState: function() {
        return {};
      },
      callback: function(value) {
        this.setState({x: value});
      },
      render: function() {
        return <div>hello {this.state.x}<B callback={this.callback} /></div>;
      }
    });

    var B = React.createClass({
      componentWillMount: function() {
        this.props.callback('world');
      },
      render: function() {
        return null;
      }
    });

    var doc = ReactTestUtils.renderIntoDocument(<A />);
    expect(React.findDOMNode(doc).textContent).toBe('hello world');
  });
```

**Comment by syranide** [comment]
AFAIK `isMounted` not longer exists, so this should be irrelevant now...?
