### ISSUE TITLE
A BUG of React website

### ISSUE THREAD

**Issue by SunCe1** [facebook/react#12460]
When i learned react at react website ,Using google translate page( ../tutorial/tutorial.html) in Chinese, i pull-down , it broken .
    It may be a small problem for your company.But for some learners in China who with inadequate English , the problem is sharp. 
    I hope to get the feedback from your company and hope that the problem can be modified.

**Comment by techhtml** [comment]
Google Translate changes Markup structure when they translate Reactjs.org sites.
Maybe this issue happens React site can't find right DOM in Translations.

**Comment by gaearon** [comment]
Same issue as https://github.com/facebook/react/issues/11538.
