### ISSUE TITLE
Change in unmounting timing from React 15

### ISSUE THREAD

**Issue by alexreardon** [facebook/react#12461]
**Do you want to request a *feature* or report a *bug*?**

*Question* (could be a *bug*)

**What is the current behavior?**

In React 15 if you replace a component with another one, the old component has `componentWillUnmount` called **before** the new component has `componentWillMount` called. However, this has changed in React 16. Now the new component has `componentWillMount` called before the old component has had its `componentWillUnmount` called.

**What is the expected behavior?**

I would have expected that the React 15 behaviour would have been maintained. It seems strange to me that new components are starting to be mounted before an old component has unmounted.

[React 15 example](https://codesandbox.io/s/207on0p0ly)
[React 16 example](https://codesandbox.io/s/nw6y7j0n9m)

**Comment by alexreardon** [comment]
This was pointed out to me:

> When replacing <A /> with <B />, B.componentWillMount now always happens before A.componentWillUnmount. Previously, A.componentWillUnmount could fire first in some cases.

- https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes

This explains what I am seeing. However, I would not have expected it: that the new descendant is rendered before the old one is unmounted.

**Comment by codrin-bytex** [comment]
According to the React 16.0 docs indeed this is not considered a bug.
I've made a few changes on your initial `React 16 example`
https://codesandbox.io/s/n3x14rr7yl

You can see that `B.componentDidMount` will be called after `A.componentWillUnmount`, which make sense... before mounting a new component React will "prepare" the new one.

**Comment by alexreardon** [comment]
Cheers

**Comment by gaearon** [comment]
>This explains what I am seeing. However, I would not have expected it: that the new descendant is rendered before the old one is unmounted.

Check out my talk about [the future of React](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html). I think this behavior will make more sense if you consider that there's no way we can start rendering an update "in background" if we can't create a new tree before we unmount the old one.

**Comment by alexreardon** [comment]
Cheers @gaearon. It makes sense when looking at it like that. My intuition led me to expect otherwise.
