### ISSUE TITLE
Backspacing over word boundary causes cursor jump when input type is email.

### ISSUE THREAD

**Issue by waynebloss** [facebook/react#12467]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The input cursor jumps to the beginning upon backspacing over the final character or word that follows a space, when the input type is `email`.

[Reproduced on JSFiddle](https://jsfiddle.net/rnrL751h/); the steps the end-user must take are repeated here:

- Enter a word + space + character (e.g. 'test 1') in the input (which has `type="email"`).
- Backspace to remove the last character (or word) following the space.
- Observe the cursor jump to the beginning of the input box.

The issue does not occur with `input type="text"`. I haven't tried every other type of input yet.

**What is the expected behavior?**

The cursor should not jump. Even if someone mistakenly enters a space into an email input box and then tries to backspace over it, we should not confuse that person more by jumbling their input.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I have observed this with the latest version of React 16 on the following:

- iOS (11.2.6), Safari.
- macOS (10.12.6 and 10.13.3), Chrome (65.0.3325.181) and Safari (11.0.3).
- Windows 10 (1709), Chrome (65.0.3325.181).

The problem did not occur on:

- Windows 10 (1709), Firefox (58.0)

**Comment by aweary** [comment]
Hey @waynebloss, this is a known issue. Please see https://github.com/facebook/react/issues/11881. Thanks!
