### ISSUE TITLE
What is the future of React prop-types?

### ISSUE THREAD

**Issue by Voronar** [facebook/react#12465]
What is the future of React `prop-types` dynamic (runtime) type checker?

1) Will it be shifted by static type checkers like TypeScript or Flow and will be deprecated in future?
2) Do I need to migrate my actual React projects to TypeScript or Flow for long-term perspective?

**Comment by gaearon** [comment]
There are no plans to deprecate PropTypes. We’re not actively promoting them because Flow/TS usually do a better job at these use cases but you should choose what better fits your project and team.

**Comment by patomation** [comment]
How about now @gaearon? Are PropTypes going to be around in react 17? I heard they were getting removed from react native...
