### ISSUE TITLE
Self-closing component isn't considered a children?

### ISSUE THREAD

**Issue by thiagommedeiros** [facebook/react#12463]
**Do you want to request a *feature* or report a *bug*?**

Bug, possibly.

**What is the current behavior?**

I have a `Form` component that validates all inputs inside him. Like this:

``` jsx
<Form
   validation={{
      amount: [required],
   }}
>
   <input type="text" name="amount" /> 
</Form>
```

It works fine. The `Form` will go through his children (the inputs) and validate it.

Now, let's see another case, inserting a self-closing component inside the `Form`:

``` jsx
<Form
   validation={{
      amount: [required],
   }}
>
   <ComponentWithInputs />
</Form>
```
The `Form` lib implementation will look for all children to verify if the input match with the validation, but in this case, the form library doesn't find any input inside `ComponentWithInputs`. 

**What is the expected behavior?**

I want to validate inputs inside self-closing components. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.2.0

**Comment by TrySound** [comment]
Show Form implementation.

**Comment by jquense** [comment]
This doesn't look like an issue with self closing inputs, but with how `children` work. Presuming the Form is inspecting `props.children` in the first case children is an `input` in the second case it's a `ComponentWithInputs` where the Form can't see any of those inputs.

In any case, I don't think this is a bug with React, i'd try one of the many support avenues for further help https://reactjs.org/community/support.html Thanks!
