### ISSUE TITLE
itemProp and itemType incorrectly rendered using react-dom/server

### ISSUE THREAD

**Issue by ahumeau** [facebook/react#12462]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
When "server side" rendering elements with the [microdata](https://www.w3.org/TR/microdata/) props `itemProp` or `itemType`, the outputed HTML attributes remain in camel case.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/jjn2wnq6jy

**What is the expected behavior?**
The HTML attributes should be lowecase.

The react-dom renderer does not suffer from this issue.

The `itemScope` microdata attribute does not suffer from this issue.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
At least React 16.1 and 16.2 are affected, React 15.x does not appear to be.

This is not a browser related issue.

**Comment by webcarrot** [comment]
not a bug - same as https://github.com/facebook/react/issues/12403
