### ISSUE TITLE
Allow call of onChange callback even with not-a-valid-date values

### ISSUE THREAD

**Issue by GeraltK** [facebook/react#12472]
**Do you want to request a *feature* or report a *bug*?**
Feature request.
For a use case when we want to show custom validation message, or use Material-ui style of floating label , it's necessary to know that there is an actual value in the input

**What is the current behavior?**
Currently, if the manual date entry is incorrect, the onChange is called with a 'null'
https://github.com/airbnb/react-dates/blob/master/src/components/SingleDatePicker.jsx#L189

**What is the expected behavior?**
allow exposing of current display value in a callback.
As options that I can think of: provide bool flag "allowInvalidInCallback" and return an object of let's say
`{
value: '01/02/',
error: 'wrong format',
}
`
or 
`
 {
value: '01/02/2018',
error: 'selected date is disabled'
}
`
Is that feasible?

**Comment by jquense** [comment]
I think your in the wrong repo! You want the Airbnb react-dates one

**Comment by GeraltK** [comment]
@jquense , long day :) sorry for confusion :)
