### ISSUE TITLE
Issues with ReactControlledValuePropTypes

### ISSUE THREAD

**Issue by lukescott** [facebook/react#12477]
**Do you want to request a *feature* or report a *bug*?**

See below.

**What is the current behavior?**

1. (Bug / Inconsistency)
```jsx
<input type="radio" checked={false} />
```
No Warning.

2. (Feature Request)
```jsx
<input type="radio" checked={true} onChange={undefined} />
```
`Warning: Failed prop type: You provided a 'checked' prop to a form field without an 'onChange' handler. This will render a read-only field. If the field should be mutable use 'defaultChecked'. Otherwise, set either 'onChange' or 'readOnly'.'`

3. (Bug?)
```jsx
<select value="foo" readOnly={true}>...</select>
```
No warning.

**What is the expected behavior?**

1. Passing a falsy `value` or `checked` attribute will not trigger a warning, but a truthy value does.

2. If onChange is passed as undefined (or null?) this should be considered as an acknowledgement and silence the warning. I have a case where I split the render method from the component and use it as a preview. When the component is interactive I use the component. When doing a preview I pass undefined as my change handler. A warning is shown to tell me I "forgot" it, but I intended it to be this way.

3. Going along with 2, I can pass `readOnly={!handleChange}`, but according to DefinitelyTyped this isn't a valid attribute for select. I can't use disabled because it changes the appearance of the field.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.2.0
Chrome 65

**Other**

A proposed "fix" would be to change:

https://github.com/facebook/react/blob/37e4329bc81def4695211d6e3795a654ef4d84f5/packages/react-dom/src/shared/ReactControlledValuePropTypes.js#L27-L33

to:

```js
if ( 
    !(propName in props) || // Fixes 1
    hasReadOnlyValue[props.type] || 
    "onChange" in props ||  // Fixes 2
    props.readOnly || 
    props.disabled 
 ) { 
```

And:

https://github.com/facebook/react/blob/37e4329bc81def4695211d6e3795a654ef4d84f5/packages/react-dom/src/shared/ReactControlledValuePropTypes.js#L44-L49

to:

```js
if (
    !(propName in props[propName]) || // Fixes 1
    "onChange" in props || // Fixes 2
    props.readOnly ||
    props.disabled
) {
```

**Comment by gaearon** [comment]
Can you please compare behavior in 15 and 16.3.0 (`next` tag for `react` and `react-dom` on npm)?
Has this changed at some point?

**Comment by lukescott** [comment]
Just checked both 15 and 16.3 - Same behavior for both.

I didn't discover this until I hit a field that had an initial truthy state (radios, select boxes). We have an application where a user builds a form and we use a stateless render function for preview and then call that function within a class component for the usable field. I would like to avoid using readOnly because it would only be valid in the preview case and adds a bit of confusion for our other developers and it doesn't seem to be supported on selects.

**Comment by nicolevy** [comment]
Hey! I’ve started to work on this here #12601 

Any input is appreciated 😄

**Comment by gaearon** [comment]
>If onChange is passed as undefined (or null?) this should be considered as an acknowledgement and silence the warning. I have a case where I split the render method from the component and use it as a preview. When the component is interactive I use the component. When doing a preview I pass undefined as my change handler. A warning is shown to tell me I "forgot" it, but I intended it to be this way.

So, I don't quite agree with this. I see what you're saying but there's also a legitimate case where you write `onChange={this.handleCahnge}` and get `undefined` because you made a typo. But if the field is suddenly readonly that's really confusing. I think the case with a typo is more common than the intentional use case you're explaining. And in your case, you could explicitly pass a noop function that doesn't do anything to silence the warning.

**Comment by lukescott** [comment]
If I passed `this.handleCahnge` instead of `this.handleChange` my linter would catch it. So the question is: Is the warning intended to catch typos, or that I did not provide an onChange at all? IMO, if I specify onChange and my variable is undefined (typo or not) it should be an acknowledgement.

An alternative could be to allow `null`. I'm not too keen on creating nop for every case, importing it, or having a dependency for one.

**Comment by jquense** [comment]
I don't know that I see the value in the null or undefined sigil here when you can always do: `onChange={readOnlyHandler}` where `readOnlyHandler= () => {}`

**Comment by lukescott** [comment]
Maybe it would help with a more specific code example. This is what my render function looks like:
```ts
export function render({
	label,
	placeholder = "",
	value = "",
	maxLength,
	error,
	handleChange,
}: TextFieldProps & Partial<TextFieldEvents>) {
	const classes: string[] = ["textField"]
	if (error) {
		classes.push(error)
	}
	return (
		<div className={classes.join(" ")}>
			<label>{label}</label>
				<input
					type="text"
					placeholder={placeholder}
					value={value}
					onChange={handleChange}
					maxLength={maxLength} />
		</div>
	)
}
```

I have a supervising PureComponent that passes `handleChange`. Without the component I use the render function by itself for read-only previews.

In this case I do not get a warning because the `""` is falsy. I did not encounter this warning until I got to a more complicated case where the default value was truthy (radio group). If I had gotten the warning on a falsy value it would have alerted me to the issue sooner.

I could do something like this to fix it:

```ts
export function render({
	label,
	placeholder = "",
	value = "",
	maxLength,
	error,
	handleChange = () => undefined,
}: TextFieldProps & Partial<TextFieldEvents>) {
```

Which would be easy to do. But... wait, you aren't supposed to inline functions, are you? In this case it causes a re-render even though nothing has really changed.

So I would need to cache it first:

```ts
const nop = () => undefined

export function render({
	label,
	placeholder = "",
	value = "",
	maxLength,
	error,
	handleChange = nop,
}: TextFieldProps & Partial<TextFieldEvents>) {
```

I know this is a bit nit-picky, but I would rather allow `undefined` (or `null`) to use as a nop than a blank method. If someone else on my team came across this they would have done what I initially did without knowing they cause a rendering issue.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/12628 fixed the part that was buggy. Thanks for the report.
