### ISSUE TITLE
event.button sent by TestUtils.Simulate.click() is undefined by default

### ISSUE THREAD

**Issue by silvenon** [facebook/react#12476]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

By default `Simulate.click()` sends an event with an undefined `event.button`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/00lm97zrjn

**What is the expected behavior?**

I think `event.button` should default to `0` because that means "left click". Some libraries like react-router [rely on this](https://github.com/ReactTraining/react-router/blob/5342c9fd58c85fd0b6272a5f12dcedab7416c0fe/packages/react-router-dom/modules/Link.js#L40). Maybe _they_ should default to `0`, not React? ReactTraining/react-router#1534

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm not sure about earlier versions, but I'm getting this behavior in `react-dom@16.2.0`.

**Comment by gaearon** [comment]
You can pass extra data to `Simulate` APIs so I'd say we leave this out.

I'd also recommend dispatching real browser events in tests instead.
