### ISSUE TITLE
Request Feature: Add API afterSetState

### ISSUE THREAD

**Issue by li2go** [facebook/react#12482]
I want to request a feature.

Could we add an API named `afterSetState` on class `Component`.

```javascript
afterSetState(state){
  return new Promise(resolve=>this.setState(state,resolve));
}
```
Then ,sometimes we can do something after update state.
I do this in my codes .
if we use `async/await`,it's  a better API.

etc:

```javascript

componentWillMount(){
   this.init();
}

async setPageLoading(isLoading){
    return this.afterSetState({isLoading});
}

async update(){
   await this.setPageLoading(true);
   let data = await fetch('data url'); 
   await this.afterSetState(data);
   //some business...
   await this.setPageLoading(false);
}

async init(){
   await this.update();
   this.adjustSomthingDomRelated();
}

```

i wish it can be added into react.js in future version.

`Promise` is not the question.

**Comment by TrySound** [comment]
[See here](https://github.com/facebook/react/pull/9989)

**Comment by raunofreiberg** [comment]
`setState` accepts a callback function so you could just do

```
this.setState(
      {
        hello: "Hello World"
      },
      () => {
        console.log("Callback");
      }
    );
```

**Comment by li2go** [comment]
why `setState` didn't return a `Promise`.

I just meaning why not make our API promisify ,why does it just callback mode.

**Comment by li2go** [comment]
I just think setState is an async Function,maybe it can be promisify.

I think it will be more awsome.

okay.....

awsome React.

awsome Contributor.

**Comment by idanbeker** [comment]
I never ran into synchronization problems with setState.
But as the algorithm of rendering is changing , I'm not sure it will stay this way, this is what I use to synchronize my actions.

I really don't see a good reason to hide the fact that setState is async.
`
setStateAsync(state) {
        return new Promise((resolve) => {
            this.setState(state, resolve)
        });
    }
`

**Comment by consultwithmike** [comment]
I could see how `afterSetState` could be a useful class function. Though it might require some context as to what state change occurred depending on what you're doing in `afterSetState`. You might even have to tag your state update operations with a `type` like you do actions so you can check the `type` of state change being performed.

So potentially the definition looks something like this:

```
afterSetState(prevState, partialState) {
  // prevState: the entire previous state object before setState
  // partialState: the partial state object that was sent to setState

  // you'd likely have to tag your partial state objects with a type if you're managing a lot
  // of different state changes
}
```

This does remove the need for the callback. However, if a callback was sent *and* `afterSetState` is defined, we'd have to decide what we wanted to do.

**Comment by li2go** [comment]
@consultwithmike there  already has  `componentDidUpdate`

**Comment by consultwithmike** [comment]
@li2go that's a good point. However, I'm thinking it's fundamentally different. For example, it can be canceled by `shouldComponentUpdate` and so isn't guaranteed to run. Furthermore, diving further into "typing" your state changes, if we embedded that idea even more (i.e. the consumer didn't have to add the `type` to the `partialState`, but it was native to `setState`) then the `afterSetState` could be a really good way of cherry-picking what you want to do based on the `type` of change.

Take for example a component that leverages drag-n-drop heavily. In a component like that there are a *lot* of state changes occurring. Some, very specific state changes, require other *reactive* state changes (e.g. adding a CSS class to something) while others do not. If my state changes could be "typed" then this `afterSetState` could be a really clean `switch` statement to deal with these enumerable needs.

So to now revise my idea for this implementation - we could do something like this.

```
setState(partialState, type, callback) {
  // partialState: the partial state the apply
  // type: the (optional) state type identifier
  // callback: the (optional) callback to execute when setState completes

  // clearly callback can be sent in the second parameter because it can be easily type checked
}

afterSetState(prevState, partialState, type) {
  // prevState: the entire previous state object before setState
  // partialState: the partial state object that was sent to setState

  // you'd likely have to tag your partial state objects with a type if you're managing a lot
  // of different state changes
}
```

**Comment by TrySound** [comment]
@consultwithmike So do you want to make a reducer from current state model? This can be implemented in user land without any effort

```js
const reducer = (prevState, { type, payload }) => {
  // ...
}

this.setState(state => reducer(state, { type: '...', payload: { ... }), () => {})
```

**Comment by consultwithmike** [comment]
@TrySound the abstract answer is  yes. However, if I thought this was a one off use case I wouldn't have provided a potential React-based framework for it. The more I think about this request, and the components I've built in the past, and how I had to respond to state changes; I think this has a broader use case.

Further, the **reducer** model is loose right? You add the `type` to the action object and then check it on the `action` parameter that's injected into the reducer. After my second iteration I realized it could be embedded and useful in that way.

Do you fundamentally believe there is no use-case for this?

If so, is that because you have different ways of managing components that change state in a lot of ways and very frequently (like the drag-n-drop component I mentioned)? Or is it because you've just never seen a use case for it and think I'm wrong?

Thanks for the feedback!

**Comment by bvaughn** [comment]
Apologies if I'm just missing or misunderstanding what's being proposed, but I don't think the proposed feature adds anything to the component API that isn't already achievable using either [`componentDidUpdate`](https://reactjs.org/docs/react-component.html#componentdidupdate) or the [`setState` callback](https://reactjs.org/docs/react-component.html#setstate).

```js
class Example extends React.Component {
  updateState() {
    this.setState(
      {
        foo: "bar"
      },
      () => {
        // Side effects in response to this particular state update
      }
    );
  }

  componentDidUpdate(prevProps, prevState) {
    // Side effects in response to a state update
    // Compare this.state to prevState if you want to narrow things down
  }
}
```

**Comment by bvaughn** [comment]
What you're describing sounds like a candidate for the `setState` callback (also shown in my above example).

Either way, as I mentioned in my previous comment- the [RFCs repo](https://github.com/reactjs/rfcs) is a more appropriate place to discuss proposals like this. 😄

**Comment by consultwithmike** [comment]
Oh @bvaughn I missed that reference to RFCs repo in your previous comment apparently. Furthermore, I didn't even know that existed, so please excuse my ignorance. I will likely migrate my last proposal into a post in the RFCs repo sir.

Again, my apologies. I'm just trying to get into the community and make some meaningful change.

**Comment by bvaughn** [comment]
No problem. 😄

I'm going to close this issue. Personally I'm not convinced this is a necessary addition or that it solves any problems not already solved by [`componentDidUpdate`](https://reactjs.org/docs/react-component.html#componentdidupdate) or the [`setState` callback](https://reactjs.org/docs/react-component.html#setstate)- but if anyone would like to make a case for that- please open a PR in the [RFCs repo](https://github.com/reactjs/rfcs) and let's see what people think! 😁
