### ISSUE TITLE
Problem with multi instance of component

### ISSUE THREAD

**Issue by reznikGit** [facebook/react#12484]
Hello, i have some problem:

In my app i have parent component Tables, this component have children's components Game, for example i have two component Game (number of components - dynamic value)
Each component Game have state property test and children component GameUI. Test value i transfer to GameUI -  `<GameUI test={this.state.test} />`

In my mind each components (with it children's) isolated from each other components and i want change state test in Game1 and transfer new value to GameUI1, but new value sending in last renderer component GameUI.

**Reactjs v.16.1.0**

<a href="https://ibb.co/f1i7h7"><img src="https://preview.ibb.co/gYKf27/IMG_0016.jpg" alt="IMG_0016" border="0"></a><br />

**Comment by reznikGit** [comment]
U can try write u example (from my description) https://jsfiddle.net/boilerplate/react-jsx/
I want to see u code, possibly i'm wrong somewhere.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
