### ISSUE TITLE
how can i use hook to Intercept dom from ref and e.target Because the safety

### ISSUE THREAD

**Issue by 55555azhe** [facebook/react#12490]
how can i use hook to Intercept dom from ref and e.target Because the tripartite safety，and i want check the style if someone write position:fixed 
how i can do? or Do you have plans to do these things?

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
