### ISSUE TITLE
Provide a better error on React.cloneElement(null/undefined)

### ISSUE THREAD

**Issue by grantCHG** [facebook/react#12491]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
![image](https://user-images.githubusercontent.com/5977311/38124026-a0984a98-3411-11e8-838f-2d6f3dc97046.png)

**Comment by milesj** [comment]
Can you please provide more information and answer the questions?

**Comment by gaearon** [comment]
You can't call `cloneElement` on `undefined`. This is intentional. You can check `isValidElement()` before cloning if you'd like to be safe.

That said we should probably throw a better error.

**Comment by nicolevy** [comment]
Is this PR all that’s really needed for this? #12534

**Comment by gaearon** [comment]
Fixed by @nicolevy in https://github.com/facebook/react/pull/12534
