### ISSUE TITLE
Invalid DOM property `frameborder`. Did you mean `frameBorder`?

### ISSUE THREAD

**Issue by JozefCipa** [facebook/react#12494]
I'm using [react-safe-html](https://github.com/brigand/react-safe-html) to render HTML from editor on website. The thing is that when it renders `iframe` it causes **Invalid DOM property `frameborder`. Did you mean `frameBorder`?** error. But when I use `frameBorder` in component it **DOESN'T** affect rendered iframe's border. However `frameborder` does (but it throws this warning).

**Comment by gaearon** [comment]
Seems to work fine in React itself: https://jsfiddle.net/fn4fv2jf/

```js
ReactDOM.render(
  <iframe frameBorder="0" />,
  document.getElementById('container')
);
```

It ends up in the DOM and prints to warnings:

<img width="292" alt="screen shot 2018-04-01 at 02 06 49" src="https://user-images.githubusercontent.com/810438/38168870-60b67530-3551-11e8-85f5-36993f2fccd5.png">

So I don't think it's a React issue and I encourage you to see if `react-safe-html` skips the attribute somewhere.
