### ISSUE TITLE
Uncaught Error: Unexpected object passed to ReactTestInstance constructor (tag: 13). This is probably a bug in React.

### ISSUE THREAD

**Issue by pedroteixeira** [facebook/react#12498]
Hello,

I'm testing v16.3.0 and I'm getting this warning:
```
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported 
```

 My use case is that I wanted to render React Test Renderer (for ex) from a Component in an another (ReactDOM) renderer but it does not seem to work - I wanted to use same Provider in both containers.

I thought `React.createContext` create objects with no state and could be shared across renderers / Fiber containers.. Is there workaround for this? Are there any thoughts on this, Is this a definite behaviour?

Following the warning, I eventually get the error message which I believe is related to the warning:

```
Uncaught Error: Unexpected object passed to ReactTestInstance constructor (tag: 13). This is probably a bug in React.
```

thank you for any guidance :)

**Comment by gaearon** [comment]
@acdlite What was the main reason it was stateful?

**Comment by pedroteixeira** [comment]
I tried to make a reproducible case here, but it worked :)
https://runkit.com/pedroteixeira/testing-react

I'll close this issue for now, and when I managed to create a reproducible snippet fort the case I have, I'll share it again.

But it would be good to hear more about if Contexts can be safely used without any hidden state impliciations. 

thanks for the great library!

**Comment by sahrens** [comment]
I'm seeing this error when switching to `React.forwardRef` - I'm guessing `react-test-renderer` may need to be updated to support `forwardRef` better?

**Comment by sahrens** [comment]
Ah, just saw #12693, maybe this is resolved by #12725?

**Comment by gaearon** [comment]
@sahrens You're sure you're using 16.4.0? If you can create a small repro case that would help.

**Comment by sahrens** [comment]
@gaearon: works after upgrading to 16.4 :)

**Comment by sahrens** [comment]
Although `React.StrictMode` and `React.Fragment` cause similar problems, but are easy to work around by wrapping in a trivial component.

**Comment by gaearon** [comment]
Can you prepare a test case please? Again, I wouldn’t expect to see this problem for any type. You shouldn’t need to work around it; I thought I fixed it. A full reproducing case would help me see what’s missing.

**Comment by stereobooster** [comment]
For future searchers. I see this error with enzyme https://github.com/stereobooster/react-context-issue (I guess this is not an issue in React itself)
