### ISSUE TITLE
When running npm start to run react app, the browser shows page unresponsive

### ISSUE THREAD

**Issue by abdulazizasiri** [facebook/react#12511]
**Do you want to request a *feature* or report a *bug*?**
Yes
**What is the current behavior?**

When I start create-react-app by running npm start, the browser gives me "Aw -snap, something went wrong". Although, I do not get any error. It is running on chrome very slowly, and it does not show anything. 

**What is the expected behavior?**
I should see the main page. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am using react: "react-dom": "^16.2.0", "react": "^16.2.0",

Something I want to say is I have yarn-lock and package-lock.json. I am using bpm and yarn interchangeably.

**Comment by turcuciprian** [comment]
What builder are you using? Webpack? Gulp? Grunt? Can you share it's configuration for data?

**Comment by gaearon** [comment]
Could you share the minimal code example that reproduces it? I can’t reproduce on a newly created app.

**Comment by gaearon** [comment]
I'll close for lack of information.

**Comment by arashamm** [comment]
i have the same problem my code is not so much but my react app starts so slow i don't why ????

**Comment by mrmadhat** [comment]
I was having this issue, for me the problem was caused by attempting to use a component inside itself accidentally:

```
const Footer = () => {
    return (
        <Footer>
             {/* Footer content */}
        </Footer>
    )
}

export default Footer
```

**Comment by pbuzzo** [comment]
mrmadhat's solution worked for me- thanks a ton!

**Comment by Abdulwahab-dev** [comment]
I solved the same issue with the help of this link 

https://support.google.com/chrome/answer/95669?co=GENIE.Platform%3DDesktop&hl=en

**Comment by madmaxlax** [comment]
> I was having this issue, for me the problem was caused by attempting to use a component inside itself accidentally:

uuuhhhhg that was it for me too, thanks @mrmadhat 
weirdly enough was also a footer for me

**Comment by shaznan** [comment]
> I was having this issue, for me the problem was caused by attempting to use a component inside itself accidentally:
> 
> ```
> const Footer = () => {
>     return (
>         <Footer>
>              {/* Footer content */}
>         </Footer>
>     )
> }
> 
> export default Footer
> ```

Worked for me!, Thanks alot!

**Comment by CodingWalaOfficial** [comment]
> I was having this issue, for me the problem was caused by attempting to use a component inside itself accidentally:
> 
> ```
> const Footer = () => {
>     return (
>         <Footer>
>              {/* Footer content */}
>         </Footer>
>     )
> }
> 
> export default Footer
> ```

Ohhhhhhhh Thank You Soo much it Saved me May God Make a Microsoft CEO my wish

**Comment by MiH0N** [comment]
> I was having this issue, for me the problem was caused by attempting to use a component inside itself accidentally:
> 
> ```
> const Footer = () => {
>     return (
>         <Footer>
>              {/* Footer content */}
>         </Footer>
>     )
> }
> 
> export default Footer
> ```

You are a real hero who saved me from trouble (❁´◡`❁)

**Comment by Abhishek-hash** [comment]
thanks a lot mrmadhat . i was having trouble from last 1 hour.

**Comment by titobzzz** [comment]
Thanks been stuck for 'bout

**Comment by Alena-Levina** [comment]
For anyone for whom mrmadhat's answer didn't help - in my case it was due to me using in my component a function that was generating infinite loop 🤷🏼‍♀️ that's kind of person I am haha

**Comment by abedindevsweb** [comment]
Most likely something in your code is creating an infinite loop. For me, it was an useEffect hook.
