### ISSUE TITLE
Why does a Userlist Component show up in the browser with an ul children element when there is no such thing in the components folder

### ISSUE THREAD

**Issue by KO527** [facebook/react#12517]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**

   import SC from 'soundcloud';
    import React from 'react';
    import ReactDOM from "react-dom";
    import {Provider} from 'react-redux';
    import {createStore, applyMiddleware} from 'redux';
    import {syncHistoryWithStore} from 'react-router-redux'
    import {combineForms, createForms} from 'react-redux-form';
    import {BrowserRouter as Router, Route, browserHistory} from 'react-router-dom';
    import thunk from 'redux-thunk';
    import promise from 'redux-promise';
    import createLogger from 'redux-logger';
    import allReducers from './reducers';
    import App from './components/App';
    import { CLIENT_ID, REDIRECT_URI } from './constants/auth';
    
    
    SC.initialize({ client_id: CLIENT_ID, redirect_uri: REDIRECT_URI });
    
    const logger = createLogger();
    const store = createStore(
        allReducers,
        applyMiddleware(thunk, promise, logger)
    );
    
    const history = syncHistoryWithStore(browserHistory, store);
    
    ReactDOM.render(
        <Provider store={store}>
    	    <Router history={history}>
    	        <div>
    	            <Route path="/" component={App}/>
    	        </div>
    	    </Router>
        </Provider>,
        document.getElementById('root')
    );

   Furthermore, inside of the App.js, I have the following: 

    import React, {Component} from 'react';
    import PlaylistSearchBar from './PlaylistSearchBar';
    import PossibleMatches from './PossibleMatches';
    import EventTicketsSearchBar from './EventTicketsSearchBar';
    import Intro from './Intro';
    import {BrowserRouter as Router, Route, browserHistory} from 'react-router-dom';
    
    class App extends React.Component{
       render(){
       		return (
    		    <div>
    		    </div>
    		)
       };
    }
    
    export default App;

What I've written up above produces: 

 In the browser:

 https://i.stack.imgur.com/L2xPh.png
 
 In the console:

  https://i.stack.imgur.com/bjJsQ.png

What in the world is causing the browser on npm start to display this?

**What is the expected behavior?**
 
 I have not designed too many components and so i'm only expecting a blank page. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

    "react": "^15.1.0",
    "react-addons-css-transition-group": "^15.6.2",
    "react-addons-test-utils": "^15.1.0",
    "react-dom": "16.2.0",
    "react-keydown": "^1.9.7",
    "react-redux": "^4.4.5",
    "react-redux-form": "^1.16.5",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8",
    "redux": "^3.5.2",
    "redux-form": "^7.3.0",
    "redux-logger": "^2.6.1",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.1.0",

Another comprehensive representation of the problem:
https://stackoverflow.com/questions/49398785/why-does-a-userlist-component-show-up-in-the-browser-with-an-ul-children-element

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
