### ISSUE TITLE
Provide a better error for circular Context Consumer

### ISSUE THREAD

**Issue by awnigharbia** [facebook/react#12515]
**Do you want to request a *feature* or report a *bug*?**
Requesting a Feature 

**What is the current behavior?**
When I named the Consumer Child  Component as the same name of the Parent Component it will go through an infinite loop. but when I change the name of the child component it will render it without problems.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://codesandbox.io/s/1o1qnrr8pj) or CodeSandbox (https://codesandbox.io/s/1o1qnrr8pj) example below:** 

**What is the expected behavior?**
Showing an error message or warning in the console

**Comment by aweary** [comment]
Since there's already some discussion in #12525, I'm going to close this in favor of #12525.
