### ISSUE TITLE
createRef missing in flow typings

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/react#12512]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

when using `React.createRef()` flow complains that `createRef` is missing in react.

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vLV24B0tDsVxVqkABQBKANxA

**What is the expected behavior?**

flow does not complain.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3.0

**Comment by gaearon** [comment]
React Flow typings live in Flow repo rather than React. 

https://github.com/facebook/flow/pull/5920
