### ISSUE TITLE
SetState() method clarification.

### ISSUE THREAD

**Issue by kumarranjansingh** [facebook/react#12513]
Is render method called for every number of properties I set using setState()?and why can't we get a parameter to pass in setState saying that don't re-render my component for this setState() method call.
I have a callback function for setState() which again setting some state so re render will be called twice?(I found it to be calling twice but can it be optimized)

**Comment by TrySound** [comment]
@kumarranjansingh Just use `setState` only once. You just want something contradict: set state, but not set state. Show that part of the code.

**Comment by kumarranjansingh** [comment]
_handleDropDownChange = e => {
    const centerId = e.target.value;
    const activeFilter = Object.assign({}, this.state.activeFilter, {
      centerId: centerId
    });
    this.setState({
      activeFilter: activeFilter
    },this.filterData);
  };
filterData = () => {
    let filteredData = this.state.List;
    let centerId = this.state.activeFilter.centerId;
    let depId = this.state.activeFilter.depId;
    if (centerId !== '') {
      filteredData = filteredData.filter(info => {
        return this.checkCenter(info.centers, centerId);
      });
    }
    if (depId !== '') {
      filteredData = filteredData.filter(info => {
        return info.dept_id === depId;
      });
    }
    this.setState({
      filterdList: filteredData,
    });
  };

**Comment by TrySound** [comment]
Wrap the code with
````
```js
```
````

**Comment by TrySound** [comment]
Just reconsider how you structure your code.

```js
_handleDropDownChange = e => {
    const centerId = e.target.value;
    this.setState(state => {
      const activeFilter = Object.assign({}, state.activeFilter, {
        centerId: centerId
      });
      return {
        activeFilter,
        filteredList: this.filterData({ list: state.list, activeFilter })
      }
    });
  };

filterData = ({ list, activeFilter }) => {
    let filteredData = list;
    let centerId = activeFilter.centerId;
    let depId = activeFilter.depId;
    if (centerId !== '') {
      filteredData = filteredData.filter(info => this.checkCenter(info.centers, centerId));
    }
    if (depId !== '') {
      filteredData = filteredData.filter(info => info.dept_id === depId);
    }
    return filteredData;
  };
```

**Comment by gaearon** [comment]
It is unnecessary to split setting state in two operations like you did. Use the functional form of `setState`:

```js
const centerId = e.target.value;
this.setState(prevState => {
  // Use prevState to read existing state
  // Calculate new activeFilter here
  // Then calculate the filtered list
  // Finally return them together 
  return {
    activeFilter,
    filteredList
  }
});
```
