### ISSUE TITLE
React 16.3.0.  Property 'createRef' does not exist on type 'typeof React'.

### ISSUE THREAD

**Issue by 29er** [facebook/react#12519]
According to new docs on creating Refs in https://reactjs.org/docs/refs-and-the-dom.html.

```
import * as React from 'react';
...
constructor(props: any) {
    super(props);
    this.fileInputRef = React.createRef()
   }
```
I upgraded to 16.3.0 but get errors on *React.createRef()*

*Property 'createRef' does not exist on type 'typeof React'.*

**Comment by gaearon** [comment]
This is a TypeScript error, not a React error. We don't maintain React TS definitions. You'll need to reach out to the maintainers of TS definitions for React and wait for them to release updated typings for React 16.3.
