### ISSUE TITLE
Whitelist <noindex> from unknown tag warning

### ISSUE THREAD

**Issue by markelog** [facebook/react#12520]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Warning 

**What is the expected behavior?**
To not show the warning

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react - 16.3.0

--

\<noindex\> is non-standard tag and probably never will be, but it's being used in - https://en.wikipedia.org/wiki/Noindex#%3Cnoindex%3E_tag

So I'm not sure if it should be whitelisted and all, but it is being used and stuff, so maybe you have like have workaround in mind or something?

Related to https://github.com/facebook/react/issues/11023

**Comment by gaearon** [comment]
Please see my reply in https://github.com/facebook/react/pull/11533#issuecomment-343738838.

**Comment by markelog** [comment]
Cool, missed that issue, thanks for fast reply!
