### ISSUE TITLE
React@16.3 constructor trigger twice in strict mode

### ISSUE THREAD

**Issue by morlay** [facebook/react#12522]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
constructor trigger twice in strict mode

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codepen.io/morlay/pen/geKjOe

![image](https://user-images.githubusercontent.com/1667873/38226564-ee776910-372c-11e8-8ca0-3fb5f27d0df4.png)

**What is the expected behavior?**
should have same behavior like normal mode

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React@16.3
Chrome@latest
MacOS

**Comment by koba04** [comment]
@morlay  It is an expected behavior.

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by morlay** [comment]
@koba04 Got it.
Thanks.
