### ISSUE TITLE
unmount/mount console warning. Changed behaviour from React 15.6

### ISSUE THREAD

**Issue by wnr** [facebook/react#12524]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When migrating our very large codebase from React 15.6 to 16, the following messages started showing in the console:

```
react-dom.development.js:530 Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.
printWarning @ react-dom.development.js:530
warning @ react-dom.development.js:554
unmountComponentAtNode @ react-dom.development.js:17020
handleClick @ Inline Babel script:36
callCallback @ react-dom.development.js:144
invokeGuardedCallbackDev @ react-dom.development.js:182
invokeGuardedCallback @ react-dom.development.js:231
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:245
executeDispatch @ react-dom.development.js:608
executeDispatchesInOrder @ react-dom.development.js:630
executeDispatchesAndRelease @ react-dom.development.js:728
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:739
forEachAccumulated @ react-dom.development.js:709
runEventsInBatch @ react-dom.development.js:870
runExtractedEventsInBatch @ react-dom.development.js:879
handleTopLevel @ react-dom.development.js:4548
batchedUpdates @ react-dom.development.js:12852
batchedUpdates @ react-dom.development.js:2119
dispatchEvent @ react-dom.development.js:4629
interactiveUpdates @ react-dom.development.js:12907
interactiveUpdates @ react-dom.development.js:2138
dispatchInteractiveEvent @ react-dom.development.js:4606

12:23:10.223 react-dom.development.js:530 Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.
```

We do not fully understand why, but have tracked this to unmounting/mounting components during an event (such as click). See https://jsfiddle.net/rv9jtfy4/ in order to reproduce it. Click on the header to trigger the warnings. When this example is running React 15, no warnings/issues are present.

It seems like the `unmountComponentAtNode` function unmounts the component asynchronously during an event. When debugging, after executing the method the root is still populated with HTML and internal React properties are still present. This probably makes the following `React.render` call problematic.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

See https://jsfiddle.net/rv9jtfy4/ in order to reproduce it. Click on the header to trigger the warnings. 

**What is the expected behavior?**

To have no warnings present in the console (like React 15).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All OS/browsers. Bug present in React 16. Works as expected in React 15.

**Comment by jquense** [comment]
Can I ask why you're doing this like this at all vs rendering conditionally returning the elements you want mounted or unmounted. In render(). The looks like a misuse of the top level render that react is now correctly warning about

**Comment by wnr** [comment]
Sure. We build view modules that have a rendering framework agnostic API (we have our own `render` and `remove` functions that in turn call React). This enables us to build applications and modules by using many different frameworks (we have Backbone legacy modules/apps for example).

Some applications want to reload all views for certain events, which results in views getting unmounted/mounted in a click event.

I understand that this is not the most natural way of using React. We think it is a great advantage that React does not enforce "the one way" of doing things - enabling us to conform to our very special needs.

**Comment by jquense** [comment]
thanks for explaining. I'm asking because the jsfiddle example demonstrates a pattern i don't think was really supported. It's hard to see how the example necessitates this approach, since you could rewrite it without using render and with very little code changes. I'm guessing tho it looks like that because you aren't demonstrating the "rendering agnostic" bits? Is there some way of having your components wrapped in this abstraction but also act like normal react components when they are in the context of a react tree? I'm pushing on this a bit because the example really breaks the react rendering model and basically negates most of the optimizations or value in using react components. That's a lot to say that it doesn't seem like your interop strategy here is ideal, components should probably be isolated render trees when not in rendered by React, and normal react components when they are.

That said, if you really want to keep this model, `createPortal` is the right API for rendering new trees in the context of a react hierarchy.

**Comment by wnr** [comment]
> thanks for explaining. I'm asking because the jsfiddle example demonstrates a pattern i don't think was really supported. It's hard to see how the example necessitates this approach, since you could rewrite it without using render and with very little code changes. I'm guessing tho it looks like that because you aren't demonstrating the "rendering agnostic" bits?

That's correct. I wanted to provide a minimal example for you. If you like I could provide a more fleshed out example?

> Is there some way of having your components wrapped in this abstraction but also act like normal react components when they are in the context of a react tree? I'm pushing on this a bit because the example really breaks the react rendering model and basically negates most of the optimizations or value in using react components. That's a lot to say that it doesn't seem like your interop strategy here is ideal, components should probably be isolated render trees when not in rendered by React, and normal react components when they are.

Not that I can think of. I understand, but we happily sacrifice performance to reduce complexity. Our apps are so big and modular that our largest threat is system complexity and framework entanglement.

> That said, if you really want to keep this model, createPortal is the right API for rendering new trees in the context of a react hierarchy.

Okay thank you. We will try out the new API. However, I'm afraid we will run into the same issue since we still need to perform an unmount/mount inside a click event.

**Comment by jquense** [comment]
> but we happily sacrifice performance to reduce complexity

It's not just performance here, you're getting almost zero benefit from using React this way. In fact you're actively thwarting React's declarative component model, and using it very against the grain. It seems like you've built n imperative component system on top of React, which really isn't the intent of the api's it provides. That works ok at the boundaries of React and some other framework, but much less so when both sides are React.  I totally get the interop problem is hard, it seems like you'd benefit tho in both complexity reduction and bugs with something that worked a bit differently for the cases where you are rendering react components into react components so you aren't trying to fight an uphill battle there.

Maybe a more robust example would help, I can't really see a way forward for the click event case, if the intent is to always use an imperative API for components

**Comment by gaearon** [comment]
> we still need to perform an unmount/mount inside a click event.

A React-friendly way to do it is to pass a different key when you want to force remounting.

```js
state = {
  myKey: 0
};

handleClick = () => {
  this.setState(state => ({
    myKey: state.myKey + 1
  });
}

render() {
  return (
    <div>
      <button onClick={this.handleClick}>remount</button>
      <Something key={this.state.myKey} />
    </div>
  );
}
```

**Comment by wnr** [comment]
@gaearon Thank you for the input. Forcing a remount by changing the key solves the issue for us.

**Comment by anuragsharma123** [comment]
@gaearon Thanks you for the solution, changing key helped me to solve the issue as well.
