### ISSUE TITLE
Support hydration after HTML minification

### ISSUE THREAD

**Issue by EnoahNetzach** [facebook/react#12536]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
`React.hydrate` replaces the DOM after a SSR page is served, and two sibling links in the page have the `href` attributes wrongly set.

I did a little repl to replicate this behaviour [here](https://repl.it/@EnoahNetzach/SSR-whitespace-mismatch).

When the server responds, the HTML is correct:

![screen shot 2018-04-04 at 16 08 06](https://user-images.githubusercontent.com/663755/38312693-b1167650-3822-11e8-85f3-0f100caf8a50.png)

but right after hydration, the first `href` is changed: 

![screen shot 2018-04-04 at 16 08 20](https://user-images.githubusercontent.com/663755/38312738-c96e1b4a-3822-11e8-9e7e-0d6a9fa24ed2.png)
and whitespace artifacts are added.

**What is the expected behavior?**
The first `href` should not be changed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v16.2
Chrome 65.0
macOS

**Comment by gaearon** [comment]
Can you turn this into a failing test case for one of `ReactDOMServerIntegration*` suites?

**Comment by EnoahNetzach** [comment]
This issue arises from the minification process (we specifically use [html-minifier](https://www.npmjs.com/package/html-minifier)), where extra white spaces and comments are removed from the HTML source.

Until v15 we were able to not remove react specific comments (e.g. `ignoreCustomComments: [/react/]`), but now it's a weaker option.
