### ISSUE TITLE
react-dom development bundle uses Array.from

### ISSUE THREAD

**Issue by wKovacs64** [facebook/react#12540]
**Do you want to request a *feature* or report a *bug*?**

Bug (?)

**What is the current behavior?**

Currently, the 16.3.x versions of `react-dom` ship [`react-dom.development.js`](https://unpkg.com/react-dom@16.3.1/cjs/react-dom.development.js) containing usage of `Array.from` which is not available in certain React-supported browsers like IE11. It causes breakage if those particular code paths are taken in such a browser (I ran into it using `<StrictMode>` in IE11).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Reproduction (should see "Hello, world!" but IE11 will crash and show nothing):
https://codepen.io/anon/pen/zWJBrO?editors=0010

**What is the expected behavior?**

`react-dom.development.js` would be transpiled down to the targets React supports, like the production variant.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`react` and `react-dom`: 16.3.0-alpha.0 through 16.3.1
Internet Explorer 11

**Comment by zhujinxuan** [comment]
Perhaps I am saying something stupid, why not use `babel-preset-env` and let users to polyfill with `babel-runtime` or `babel-polyfill`?
Because `Array.from` is not an instance method, then users can easily polyfill at their side with `babel-runtime`

**Comment by gaearon** [comment]
We definitely should not have been using `Array.from` there. 😞

**Comment by bvaughn** [comment]
Sorry 'bout that folks~

**Comment by gaearon** [comment]
![thanks](https://media2.giphy.com/media/xULW8v7LtZrgcaGvC0/giphy.gif)

**Comment by sophiebits** [comment]
Why shouldn't we have been using Array.from?

**Comment by bvaughn** [comment]
No IE support.

**Comment by gaearon** [comment]
We used to run in IE11 with Map/Set/rAF polyfills so IMO adding dependencies on other builtins is a breaking change.

**Comment by sophiebits** [comment]
OK. Maybe in the future. We shouldn't get in the habit of inlining implementations of ES6 builtins if we can avoid it because it bloats bundle size and is also less maintainable.

**Comment by gaearon** [comment]
Agree! This one is DEV-only. Maybe we can require full ES6 env with 17.

**Comment by blling** [comment]
Sounds good! :+1:

**Comment by DanZeuss** [comment]
@gaearon you mean, new implementations from 17 should be accepting ES6?

**Comment by gaearon** [comment]
I'm saying that in React 17 we can bump the runtime requirement to assume ES6 environment.

**Comment by DanZeuss** [comment]
Uhm... gotcha. I was just concerned about many applications (from DoD) using React that still runs under IE11 that isn't compatible with many ES6 functions.

**Comment by gaearon** [comment]
If we bump minimal requirement to ES6 this will only require polyfilling some functions. It doesn't necessarily mean dropping IE support.

**Comment by wKovacs64** [comment]
Thanks all.
