### ISSUE TITLE
Broken Link on React JSX Tag Descriptions

### ISSUE THREAD

**Issue by dagrooms52** [facebook/react#12547]
**What is the current behavior?**
The link address `https://react-cn.github.io/react/docs/special-non-dom-attributes.html` linked from this page `https://react-cn.github.io/react/docs/tags-and-attributes.html` regarding the React-specific tag `dangerouslySetInnerHTML` leads to a 404 page.

The link is in the following paragraph:
> There is also the React-specific attribute dangerouslySetInnerHTML (more here), used for directly inserting HTML strings into a component.

**Comment by gaearon** [comment]
We don't manage `react-cn.github.io`. It's a fork somebody else maintains.

React docs are at https://reactjs.org/, as mentioned on the React GitHub page.

**Comment by aweary** [comment]
Do we know who maintains that fork? It's pretty out of date, and may show up in search results. @dagrooms52 how did you find that page?

**Comment by dagrooms52** [comment]
It was the first result for a google search similar to [this one](https://www.google.com/search?q=tags+and+attributes+react&oq=tags+and+attributes+react&aqs=chrome.0.69i59j69i60j0.3711j1j7&sourceid=chrome&ie=UTF-8). I was trying to find more information about the accepted component tags usable in JSX, which for some reason I am having trouble learning about on the official [react website](https://reactjs.org/).

**Comment by dagrooms52** [comment]
Actually, here's the [original google search](https://www.google.com/search?q=legal+tags+in+jsx) I did to find the page from my search history.

**Comment by aweary** [comment]
That's what I feared, the first two results are outdated Chinese translations.

@gaearon is there anything we can do about this? 

@dagrooms52 the most relevant page on the official React docs would be [DOM Elements](https://reactjs.org/docs/dom-elements.html). To answer your question, you can use any valid HTML element, SVG element, or a [custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements). Check out the [tutorial](https://reactjs.org/tutorial/tutorial.html) if you want a good foundations for the basics
Hey there! We use the issue tracker for bug reports and feature requests.

If you have any other questions, please check our community support resources:
https://facebook.github.io/react/community/support.html
