### ISSUE TITLE
Upgrade to Babel 7

### ISSUE THREAD

**Issue by acdlite** [facebook/react#12548]
Babel 7 is still in beta, but presumably it will be released soon. We should get a head start on upgrading. Perhaps it's stable enough for us to upgrade even before the final release.

One benefit is we could use JSX fragment syntax in tests. Yay!

@reznord has volunteered to pick this up.

**Comment by reznord** [comment]
babel-jest latest version still doesn't support babel v7. The tests might face an issue after I update

**Comment by acdlite** [comment]
Did you try the instructions here on how to use Jest with Babel 7?

https://facebook.github.io/jest/docs/en/getting-started.html#using-babel

> Note: If you are using a babel version 7 then you need to install babel-jest with the following command:
>
> ```
> yarn add --dev babel-jest 'babel-core@^7.0.0-0' @babel/core regenerator-runtime
> ```

**Comment by gaearon** [comment]
Babel Jest definitely supports Babel 7, we're using them together in CRA

**Comment by TrySound** [comment]
Not sure about `7.0.0-0`, but there is a special version for such cases
```js
yarn add babel-core@bridge --dev
```

**Comment by SimenB** [comment]
`bridge` is a tag for `7.0.0-0`, so it's the same

**Comment by reznord** [comment]
Hi @acdlite @gaearon sorry for the delay on the update for this PR. Wasn't doing well recently. I will start working on this PR now. 

Once again, sorry for the delay

**Comment by asiniy** [comment]
@reznord may I take this?

**Comment by dantesolis** [comment]
Is anyone working on this still ? If not I would give it a try. Thanks :)

**Comment by armujahid** [comment]
I also want to help. @dantesolis can we both work on it together? If no one else is working on it.

**Comment by dantesolis** [comment]
@armujahid yes sure, we can work on this together. :)

**Comment by armujahid** [comment]
@dantesolis I have started working on it. https://github.com/armujahid/react/tree/babel7 but its not complete yet.

**Comment by dantesolis** [comment]
@armujahid, wow you move fast! I will start working on it today or tomorrow, how should we tackle it so we don’t work on the same thing at the same time?

**Comment by armujahid** [comment]
@dantesolis I have added you as collaborator to my repository. You can see my changes in [babel7 branch](https://github.com/armujahid/react/tree/babel7)
I have done the following:

1. Use [babel-upgrade](https://github.com/babel/babel-upgrade) tool to upgrade package.jsons
2. Update references of babel packages in code.
3. Update references of babel packages in .babelrc file

**Issues:**
Tests are still failing with different errors e.g. "Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation." although its already added in .babelrc file. 
We need to resolve these issues so that at least tests won't fail

**Comment by dantesolis** [comment]
@armujahid  I'll be working on this then today and tomorrow.

**Comment by mmarkelov** [comment]
@dantesolis @armujahid Just saw this issue. I also did some work with it. Building packages is passing - but I got some problems with tests. Some of them are failed and I just can't figure out what is wrong. 
You can check my [Upgrade_to_Babel_7](https://github.com/mmarkelov/react/tree/Upgrade_to_Babel_7) branch

**Comment by mmarkelov** [comment]
I got some new stuff in my [Babel 7 branch](https://github.com/mmarkelov/react/tree/Babel_7)
But I got two errors with tests. And I just can't figure out what's wrong.
```javascript
ReactDOMServer › should warn when server rendering a class with a render method that does not extend React.Component

    expect(function).toThrow(type)

    Expected the function to throw an error of type:
      "TypeError"
    Instead, it threw:
      Invariant Violation: ClassWithRenderNotExtended(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
          41 |       const args = [a, b, c, d, e, f];
          42 |       let argIndex = 0;
        > 43 |       error = new Error(
             |               ^
          44 |         format.replace(/%s/g, function() {
          45 |           return args[argIndex++];
          46 |         }),
    
          at invariant (packages/shared/invariant.js:43:15)
          at validateRenderResult (packages/react-dom/src/server/ReactPartialRenderer.js:416:46)
          at processChild (packages/react-dom/src/server/ReactPartialRenderer.js:546:9)
          at resolve (packages/react-dom/src/server/ReactPartialRenderer.js:442:5)
          at ReactDOMServerRenderer.render (packages/react-dom/src/server/ReactPartialRenderer.js:854:7)
          at ReactDOMServerRenderer.read (packages/react-dom/src/server/ReactPartialRenderer.js:822:23)
          at Object.renderToString (packages/react-dom/src/server/ReactDOMStringRenderer.js:17:309)
          at packages/react-dom/src/__tests__/ReactServerRendering-test.js:648:26
          at Object.<anonymous> (node_modules/expect/build/to_throw_matchers.js:51:9)
          at Object.throwingMatcher [as toThrow] (node_modules/expect/build/index.js:320:33)
```

**Comment by acdlite** [comment]
@mmarkelov That’s great! Please open the PR!

**Comment by mmarkelov** [comment]
@acdlite Just can't figure out what's wrong with last step - `node ./scripts/tasks/danger`

**Comment by loryman** [comment]
@mmarkelov is there any updates on this? I'd like to help if you want

**Comment by mmarkelov** [comment]
@loryman I just got some tests fails - it was a big challenge. Of cause you can help. It will be nice. You can check my actual [branch](https://github.com/mmarkelov/react/tree/Babel_7) also I can add you as  collaborator.

**Comment by loryman** [comment]
Thank you! I cloned your branch and i've started working on it. I can open a PR to your repo with all the changes

**Comment by victorhmp** [comment]
Hey guys! @loryman @mmarkelov still working on this one?

**Comment by pavelzubov** [comment]
@loryman @mmarkelov are you successful in working on this problem?

**Comment by loryman** [comment]
Sorry, I haven't been able to work on this. Anyway, I think we have to wait for #15037 to be merged, then I'll try to continue from that

**Comment by epicfaace** [comment]
Would it be better to upgrade each package, one by one, to Babel 7 in separate PRs?

**Comment by kambleaa007** [comment]
Hi, is there any small task, i would like to do

**Comment by lunaruan** [comment]
Thanks everyone for your work on this!

@mmarkelov @armujahid Added you two as coauthors to the [PR](https://github.com/facebook/react/commit/b12a982062ff3be7fdb95a104b800607f1d25976).

**Comment by epicfaace** [comment]
Not all packages have been upgraded to babel 7 (for example, react-art), so should we reopen this issue?
