### ISSUE TITLE
Feature: Portals in virtual dom

### ISSUE THREAD

**Issue by ilabacheuski** [facebook/react#12550]
I like the idea of Portals and have a proposal to extend it

The idea, in short, is to have a special element in React to allow connect Portal to that element without real id in DOM element, that we have now. Something like:

```jsx
const app = () => (
  <>
    <SomeApp />
    <React.Region regionId='GUID' />
  </>
)

const SomeWidget = () => {
...
}

ReactDOM.createRegion(SomeWidget, 'GUID')
```

So the idea is that we have Portal(region) anywhere in virtual DOM, that will be rendered asynchronously 
when it is needed.

Currently, I am working on a project that uses a custom-made library (RxJs based Frint-js)  to make something like this works.
So we have `<Region name="some region" />`. Our libraries look for `Region` and connect our widgets to react application dynamically with all props that are needed

**Comment by TrySound** [comment]
This repo is used for proposals
https://github.com/reactjs/rfcs

**Comment by ilabacheuski** [comment]
Close in favour of https://github.com/reactjs/rfcs/issues/39
