### ISSUE TITLE
Should throw error when null or falsy values are passed as event listeners

### ISSUE THREAD

**Issue by amasad** [facebook/react#1255]
Null values for event listeners fail silently. http://jsfiddle.net/2BCLQ/1/
Falsy values for event listeners fail silently http://jsfiddle.net/2BCLQ/2/

**Comment by akre54** [comment]
I understand the reasoning behind keeping the events and props interface similar but this has bit me a few times on stupid typos and refactorings. React is usually very good about failing early and loudly in dev for other gotchas, and this seems like an odd oversight. 

IMO `null` and `false` are both fine sentinels for "this space intentionally left blank" but `undefined` is Javascript's idiotic way of handling both "not here right now" and "was never here". It'd be nice to have this addition.
