### ISSUE TITLE
"setState()" always triggers "componentWillReceiveProps()"

### ISSUE THREAD

**Issue by Nes-si** [facebook/react#12554]
Hi there.
Since React v16.3.0 every `this.setState()` triggers `componentWillReceiveProps()`. Before v16.3.0 there is no such behavior. 
It is a very breaking change for my project, it causes a lot of problems.
Is it a normal behavior or a bug?

Also,  `this.setState()` triggers new method `getDerivedStateFromProps()` too.

**Comment by gaearon** [comment]
Can you please create an isolated example demonstrating this?
I can't reproduce: https://jsfiddle.net/1pubppp0/

**Comment by gaearon** [comment]
I can't reproduce this:
https://jsfiddle.net/b2x3a82k/

Can you please create a reproducing example?

**Comment by Nes-si** [comment]
I haven't exactly find out the problem, but I understand that it is concerned with _react-css-modules_. When I remove its decorator, the problem disappears. Sorry to trouble.
