### ISSUE TITLE
react onClick event is not firing in Samsung Native Browser

### ISSUE THREAD

**Issue by NithishReddy** [facebook/react#12560]
```
class Clicked extends React.Component{
  mark(){
   console.log('clicked');
  }
  render()
  {
    return (<a href="javascript:void(0)" onClick={this.mark.bind(this)}>click</a>)
  }
}
```

Above click is not firing in Samsung native browser ??

**Comment by aweary** [comment]
@NithishReddy can you please provide more information about what device you're using, the specific app you're using (is it called "Samsung native browser"?) and the version of the app you're using.

Also, the code you provided isn't valid; I assume you were just trying to include an example of a simple click handler, but it would be helpful if you could share the exact code you're having trouble with.

**Comment by apoorvtomar2222** [comment]
Yes, Although Information is not sufficient.

But for reference 

To bind call ay onClick event you need to bind it to class.

Modifying your example:


class Clicked extends React.Component{
// Using fat arrow function
mark=()=>{
  console.log('clicked');
}
render()
{
return (
    <Button onClick ={this.mark()}>Click</Button>
 )
}
}
Hopefully this might solve your problem.

Still more data needed from you.

**Comment by NithishReddy** [comment]
Hi @aweary, In Samsung grand mobile , samsung native browser click event is not fired  and in all other devices it is working fine including samsung grand chrome browser also.

**Comment by xusai2014** [comment]
@NithishReddy Can u catch the error with window.onError or catch{}throw(e){}  ?

**Comment by jazkh** [comment]
I am facing the same problem on my mobile Samsung S5 browser chrome and firefox.
onClick does not fire.

**Comment by gaearon** [comment]
This sounds like a browser bug — sorry.
