### ISSUE TITLE
Silence noisy missing-key warning when it doesn't apply

### ISSUE THREAD

**Issue by danneu** [facebook/react#12567]
I'd like to request a feature that would enable us to silence the missing-key warning (https://fb.me/react-warning-keys) since it doesn't apply to server-side applications.

For example, I have a library for using React for server-side templating (https://github.com/danneu/react-template-render) and I'm using it in this demo app: https://github.com/danneu/koa-skeleton

Ideally I'd be able to set a property on `require('react')` to silence it. 

It's quite noisy and crowds out my dev logs:

```
Listening on http://localhost:3000
  <-- GET /users/user-1000
  --> GET /users/user-1000 200 224ms 2.02kb
  <-- GET /users?page=5
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <tbody>. See https://fb.me/react-warning-keys for more information.
    in UserRow
    in UsersList
    in div
    in body
    in html
    in Master
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <ul>. See https://fb.me/react-warning-keys for more information.
    in li
    in Paginate
    in UsersList
    in div
    in body
    in html
    in Master
    in span
    in a
    in li
    in ul
    in nav
    in Paginate
    in UsersList
    in div
    in body
    in html
    in Master
  --> GET /users?page=5 200 68ms 6.69kb
  <-- GET /users?page=7
  --> GET /users?page=7 200 12ms 6.77kb
  <-- GET /users?page=4
  --> GET /users?page=4 200 16ms 6.58kb
  <-- GET /users/testing
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <h1>. See https://fb.me/react-warning-keys for more information.
    in a
    in UsersShow
    in div
    in body
    in html
    in Master
  --> GET /users/testing 200 9ms 2.07kb
  <-- GET /users
  --> GET /users 200 22ms 6.46kb
  <-- GET /users/testing/edit
  --> GET /users/testing/edit 200 52ms 2.01kb
  <-- GET /
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
    in p
    in Homepage
    in div
    in body
    in html
    in Master
    in button
    in div
    in div
    in form
    in NewMessagePanel
    in div
    in div
    in Homepage
    in div
    in body
    in html
    in Master
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <small>. See https://fb.me/react-warning-keys for more information.
    in a
    in MessagePanel
    in div
    in div
    in Homepage
    in div
    in body
    in html
    in Master
  --> GET / 200 101ms 14.25kb
  <-- GET /users/user-113
  --> GET /users/user-113 200 13ms 2.92kb
  <-- POST /sessions/be3b0440-742f-461a-808d-896a420023f2
  --> DELETE /sessions/be3b0440-742f-461a-808d-896a420023f2 302 32ms 33b
  <-- GET /
  --> GET / 200 21ms 14.15kb
```

**Comment by danneu** [comment]
Fair enough, thanks.

**Comment by qwertie** [comment]
Is there a purpose for requiring keys when there is no iterator or array involved? For instance if there are always exactly three children, always in the same order, why must React demand that I write `key={1}`, `key={2}`, `key={3}` on them?

**Comment by gaearon** [comment]
You don't need to.
If you have three children you can write them like this:

```js
let parent = (
  <div>
    {firstChild}
    {secondChild}
    {thirdChild}
  </div>
);
```

JSX guarantees those positions are “stable” and don’t move so React doesn’t need keys in this case.

**Comment by qwertie** [comment]
React seems to assumes that all arrays are "unstable" and need keys. I argue this is not the case. 

#### Example 1: this `Label` component:

    export function Label(p: LabelProps & React.HTMLAttributes<HTMLElement>)
    {
      return React.createElement("label", omit(p, LabelAttrs), 
        p.labelAfter ? [p.children, LabelSpan(p)] : [LabelSpan(p), p.children]);
    }

It may *look to React* like it's unstable, but in reality `labelAfter` is always a constant... it's true for checkboxes (you want the label after the checkbox) and false otherwise.

#### Example 2: optional trailing items

      <fieldset>
        <legend>Input fields:</legend>
        <CheckBox p value={hs('checkbox1')} label="I am prepared to see various form elements"/>
        { !this.state.checkbox1 ? [] : [
          <CheckBox p value={hs('checkbox2')} label="Checkbox:" labelAfter={false} />,
          <CheckBox p value={hs('checkbox2')} label="Checkbox:" labelAfter={false} />,
          <Label p label="Happiness level:">
            <Slider value={hs('happiness')} min={-10} max={10} step={1}/>
            <TextBox type="number" value={hs('happiness')} style={ {width:"4em"} }/>
          </Label>
        ]}
      </fieldset>

This example actually **is** dynamic, but items are only ever added or removed on the end, so why would React need keys to help it update? Adding a key to each component just adds visual noise.

**Comment by danneu** [comment]
I ended up overriding `console.error` to filter out the warning:

https://github.com/danneu/react-template-render/commit/8ae09d53a2ae879adcb4994689fed23086b8e254
