### ISSUE TITLE
ReactDOM.render calls rerender context Consumers unnecessarily

### ISSUE THREAD

**Issue by Andarist** [facebook/react#12561]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Subsequent `ReactDOM.render` calls with **the same** tree are causing Consumers to rerender even if provided value is static & has the same reference (or is static primitive type) - whereas normal rerender (caused i.e. by `setState`) doesn't cause this.

Situation occurs when there is an update blocker between Provider & Consumer.

@thysultan provided excellent demo for this - https://codesandbox.io/s/4qo2mw42r4

**What is the expected behavior?**

Those calls should behave the same as rerenders caused by `setState`. Tree is correctly reconciled and not recreated from scratch, so it's only logical to me that those nested rerenders should be avoided.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.3

**Comment by gaearon** [comment]
Can you please build from master and check if it’s fixed there? I recently made a related bug fix which might have also fixed this.

**Comment by gaearon** [comment]
Hmm never mind. Mine was for a different code path.

**Comment by Andarist** [comment]
> Can you please build from master and check if it’s fixed there? I recently made a related bug fix which might have also fixed this.

This is good to know though, Im facing other issue which I cannot track down yet (ive double checked everything and imho rerendering shouldnt happen, cant locate why it does but cannot yet reproduce outside of our project). Gonna test with your latest fix later to see if it helps - although my other issue happens also with legacy context.

**Comment by gaearon** [comment]
I don't understand what you consider to be a bug here.

If I change `Indirection` to return `false` from `shouldComponentUpdate` then I don't see a re-render (as expected).

If it returns `true` then update follows a normal flow. You're passing different children every time so it re-renders every time. If you didn't have context provider/consumer in the tree, it would work the same way.

I think it's a bit misleading that you say the tree is "the same" when technically you pass different elements (even though the tree looks the same way). 

What am I missing?

**Comment by thysultan** [comment]
>If I change Indirection to return false from shouldComponentUpdate then I don't see a re-render (as expected). If it returns true then update follows a normal flow.

I figured this might be the [case](https://twitter.com/thysultan/status/982201066212081668)

Which raises the question of in what context does a Provider does bail out of propagating updates to consumers if the `value` has not changed.

**Comment by gaearon** [comment]
You're not seeing a re-render because Provider “propagates context”. You're seeing a re-render because the tree just renders normally and doesn’t encounter something that would prevent rendering in the middle. So it gets to the leaves.

Provider/Consumer aren’t supposed to make rendering more restrictive than regular divs.

**Comment by gaearon** [comment]
No problem, thanks for taking the time anyway!
