### ISSUE TITLE
ReactJS Logo License

### ISSUE THREAD

**Issue by rainwater11** [facebook/react#12570]
I have been unable to find out what the license for the React logo is. Does anyone know under which license it is?

**Comment by apoorvtomar2222** [comment]
I believe it is also under the same license that React is and will be because it is related to same.

**Comment by aweary** [comment]
cc @sophiebits

**Comment by memo-rebolledo** [comment]
Following @apoorvtomar2222 's statement, the logo should be under MIT license.

**Comment by gaearon** [comment]
@memo-rebolledo @apoorvtomar2222 This is incorrect.

The logo is licensed under **Creative Commons Attribution 4.0**, just like the documentation itself:
https://github.com/reactjs/reactjs.org/blob/master/LICENSE-DOCS.md

See also FB trademark guidelines: https://en.facebookbrand.com/guidelines/brand

Hope this helps!

**Comment by R4M5E5** [comment]
> @memo-rebolledo @apoorvtomar2222 This is incorrect.
> 
> The logo is licensed under **Creative Commons Attribution 4.0**, just like the documentation itself:
> https://github.com/reactjs/reactjs.org/blob/master/LICENSE-DOCS.md
> 
> See also FB trademark guidelines: https://en.facebookbrand.com/guidelines/brand
> 
> Hope this helps!

Where does it say that the Creative Commons Attribution 4.0 also applies to the logo?

**Comment by Snailedlt** [comment]
The logo is in the GitHub repo, so it must be under the same license right?
https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/fixtures/dom/public/react-logo.svg
