### ISSUE TITLE
a question about getDerivedStateFromProps and previous props

### ISSUE THREAD

**Issue by cvlmtg** [facebook/react#12577]
I've read the article on [Update on Async Rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#updating-state-based-on-props) and I have a little doubt about `getDerivedStateFromProps`, i.e. why it does't receive prevProps as one of its arguments?

There are situations where it is useful to compare prevProps with nextProps, and what the article suggests (i.e. *You may notice in the example above that props.currentRow is mirrored in state*) VERY IMHO is wrong for a couple of reasons. The first one is that it breaks the single source of truth rule (and we also have the inconvenience of keeping props.currentRow and state.lastRow in sync), and the second one I think is summarized here: https://reactjs.org/docs/thinking-in-react.html i.e. *The key here is DRY: Don’t Repeat Yourself. Figure out the absolute minimal representation of the state your application needs and compute everything else you need on-demand*. This is a suggestion I've basically seen since the dawn of react, so copying a prop to the state just to have it around when I need it looks a bit wrong to me. So my suggestion would be to add `prevProps` as an argument to `getDerivedStateFromProps`.

**Comment by TrySound** [comment]
@cvlmtg DRY doesn't mean write less code.

https://github.com/reactjs/rfcs/pull/40

**Comment by cvlmtg** [comment]
@TrySound I'm not talking about writing code, I'm talking about duplicating data

**Comment by jquense** [comment]
There is a lot of discussion already about this and why the choice was made. If you want weigh in on changing it please read through the rfcs and add in there thanks!

**Comment by TrySound** [comment]
@cvlmtg Also data is not actually duplicated. You pass to state only references to reuse them later. According your logic `prevProps` has the same problem.

**Comment by gaearon** [comment]
You can find an ongoing discussion in https://github.com/reactjs/rfcs/pull/40 and linked issues.

**Comment by bvaughn** [comment]
> The first one is that it breaks the single source of truth rule

Just wanted to chime in and point out that this doesn't actually break "single source of truth" rule. The props key in the example is `currentRow`- (it could also just be `row`)- and the state key was very intentionally named `lastRow`. So there's never any doubt about what the _current_ source of truth is.

**Comment by cvlmtg** [comment]
Thanks, I'm gonna reply on the other topic (If I've something new to add, it seems already pretty long!)
