### ISSUE TITLE
this's what????

### ISSUE THREAD

**Issue by MunMunMiao** [facebook/react#12576]
https://github.com/facebook/react/blob/181747a6cc25f3020b8561f475eca4ad2824256b/packages/react/src/React.js#L62

![http://wx4.sinaimg.cn/large/6cf34e3dly1fq5b9dogycj20jg0xfaxq.jpg](http://wx4.sinaimg.cn/large/6cf34e3dly1fq5b9dogycj20jg0xfaxq.jpg)

**Comment by TrySound** [comment]
It's `SECRET_INTERNALS` which shouldn't care you.

**Comment by gaearon** [comment]
Internals that have to be exposed but don’t follow semantic versioning because they’re not public API. Don’t use them.
