### ISSUE TITLE
Property `current` of `ref`

### ISSUE THREAD

**Issue by liril-net** [facebook/react#12588]
I was puzzled when using property `current` to access `ref` of DOM or component, `current` is the only property that I can access in `ref` object, what is the purpose of this property?

```js
this.inputRef.current.focus()
this.inputRef.focus() // Isn't this a better way to use ref?
```

**Comment by TrySound** [comment]
@liril-net https://github.com/reactjs/rfcs/blob/master/text/0017-new-create-ref.md#basic-example

**Comment by liril-net** [comment]
@TrySound But what is the benefit of doing so? Some performance concern?

**Comment by TrySound** [comment]
@liril-net No. You pass your ref to the component. The component need to update this ref. With this case it's not possible.

```js
const component = ({ ref }) => {
  ref = new Element
}
const ref = null
component({ ref })
```

That's why createRef is object with mutable field, which can be updated by component.

```js
const component = ({ ref }) => {
  ref.current = new Element
}
const ref = { current: null }
component({ ref })
```

**Comment by liril-net** [comment]
Thanks for your reply.

**Comment by gaearon** [comment]
To be clear React itself will set the `current` property. Not a component.
