### ISSUE TITLE
Add unicityKey to save react from rendering subpart of the DOM when it hasn't changed

### ISSUE THREAD

**Issue by bebeun** [facebook/react#12592]
==> New feature proposal

Today, if we want to save react from re rendering a sub part of a parent component1, we have no other choice but to create a component2 nested in component1 and implement shouldComponentUpdate for component2.

It is very useful. But in my case, my apps are very little likely to be written with multiple nested components since every DOM part is unique. Splitting my app into components would be very verbose.
So I only have a main component for a page with an inline DOM in the render function. But at the same time, depending on my app state, there are big DOM nodes I could save from rerendering.

My idea is to be able to use a kind of "unicityKey" that would tell react "Okay, the unicityKey has not changed", no need to go any deeper in this node, it is unchanged.
For example : 

    <div unicityKey={this.state.stuff} key={"divNumber3"} >
        ...
    </div>
would be the inline version of 

    <Component2  unicityKey={this.state.time} key={"divNumber3"} />`

with 

    class Component2 extends React.Component{  

      shouldComponentUpdate(nextProps, nextState) {

        return this.props.unicityKey != this.nextProps.unicityKey;  

      }  

      render() {

          return (

            <div>...</div>    
                              
          );

        } 

    };

**Comment by gaearon** [comment]
Please submit API change proposals to the RFC repository: https://github.com/reactjs/rfcs
Thanks!
