### ISSUE TITLE
Getting SHA384 warning after switching from development to production

### ISSUE THREAD

**Issue by dkati** [facebook/react#12593]
`
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.2.0/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.2.0/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.25.0/babel.min.js"></script>
`
here are my scripts that i include to my html and i get 

`None of the “sha384” hashes in the integrity attribute match the content of the subresource.`

any thoughts? thanks

**Comment by gaearon** [comment]
You probably have an incorrect `integrity` attribute somewhere. This is a question about how the browsers work, and isn’t really related to React so I’m closing.

**Comment by dkati** [comment]
this actually happened after i renamed the react files from 'development' to 'production'
