### ISSUE TITLE
[Question] Context provider state initialisation.

### ISSUE THREAD

**Issue by leonaves** [facebook/react#12596]
Consider a component wrapping a context provider:

```js
class ValueWrapper extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: null,
      setValue: this.setValue,
    };
  }

  setValue = (value) => {
    this.setState({ value });
  };

  render = () => (
    <Context.Provider value={this.state}>
      {this.props.children}
    </Context.Provider>
  );
}
```

A consumer then might want to set a default value when it is first mounted. The only way I can see to do this using the new API is to check for an existing value on first render:

```js
class ValueUpdater extends React.Component {
  state = {
    inputValue: 0,
  };

  handleInputChange = e => {
    this.setState({ inputValue: e.target.value });
  };

  render = () => (
    <Context.Consumer>
      {({ value, setValue }) => {
        if (!value) {
          setValue(this.state.inputValue);
        }

        return (
          <div>
            <input type="text" value={value} onChange={handleInputChange}/>
            <button onClick={() => setValue(this.state.inputValue)}>Update value</button>
          </div>
        );
      }}
    </Context.Consumer>
  )
};
```

But this seems to break the golden rule of updating state in the render method (`setValue(this.state.inputValue)`), as this would immediately cause a re-render. Ideally I would be able to call the `setValue` from the context in the `componentDidMount` method of the `ValueUpdater` component, but with context as a render prop, that's not possible, as far as I can tell. The docs suggest passing props down to another component:

```js
  render = () => (
    <Context.Consumer>
      {({ value, setValue }) => (
          <ValueUpdaterInput setValue={ setValue } value={ value } />
      )}
    </Context.Consumer>
  )
```

But if I tried to do the initialisation in the `ValueUpdaterInput` component's `componentDidMount` method, it would be called on every render, surely, as `ValueUpdaterInput` would be re-rendered each time?

Is there a better pattern than this, or am I trying to use context inappropriately?

**Comment by leonaves** [comment]
Sorry if this is the wrong place for this by the way, I have tried to make the examples above as generic as possible, but also I've not seen anything in the docs regarding this sort of pattern, so I'd be happy to draft some documentation on it if there is anything that needs to be added.

**Comment by Kovensky** [comment]
When I encountered this problem in my own components, the only reasonable alternative I found was to add a third component.

```js
render () {
  return (
    <Context.Consumer>{({ value, setValue }) => (
      <ConsumerRender value={value} setValue={setValue}/>
    )}</Context.Consumer>
  )
}
```

```js
class ConsumerRender {
  componentDidMount () {
    if (!this.props.value) {
      this.props.setValue('value')
    }
  }
  render () {
    return this.props.value // or whatever you actually want to render
  }
}
```

**Comment by gaearon** [comment]
Can you provide more details on the specific scenario you're trying to implement?
More concretely:

* Why do you hoist this state up when the component "knows" its initial state better than the context provider?
* What happens if you render two such components (and they both attempt to set the value)? Should one of them "win"?

**Comment by leonaves** [comment]
Great questions, the component I'm trying to trying to implement is a "tabbed" UI component (image from google images just for illustration):

<img src="https://user-images.githubusercontent.com/1926652/38605266-b443d0a0-3d6a-11e8-9b2d-09e4a51f3ca8.jpg" height="250" />

Which I've tried to implement with an API like this:

```jsx
<TabContainer>
  <Tab label="Home" defaultTab={ true }>
    <div>Welcome to the homepage</div>
  </Tab>
  <Tab label="About">
    <div>Welcome to the about page</div>
  </Tab>
  <Tab label="Contact">
    <div>Welcome to the contact page</div>
  </Tab>
  <div>
    <TabContent />
  </div>
</TabContainer>
```

Where the content rendered into the `TabContent` component is the child of the related `Tab`. The idea being that the `defaultTab` would be able to communicate that it is the default to its parent. An alternative API for this that sidesteps the problem I suppose would be:

```jsx
<TabContainer defaultTab={ 1 }>
  <Tab id={ 1 }>Home</Tab>
  <Tab id={ 2 }>About</Tab>
  <Tab id={ 3 }>Contact</Tab>
  <div>
    <TabContent id={ 1 }>
      <div>Welcome to the homepage</div>
    </TabContent>
    <TabContent id={ 2 }>
      <div>Welcome to the about page</div>
    </TabContent>
    <TabContent id={ 3 }>
      <div>Welcome to the contact page</div>
    </TabContent>
  </div>
</TabContainer>
```

But I like how the existing API enforces content for each tab by design, so avoids any potential issues of having a `Tab` with no corresponding `TabContent`, or a `defaultTab` with no corresponding `Tab`. Perhaps me attempting to coerce the components into this API has caused this problem and I should change course, but this _was_ possible without calling `setValue` from the render method using the old context API, so it is slightly irksome that I can't seem to achieve it with the new context API.

In answer to your second question, I guess the question specific to this scenario is what happens if you specify multiple `defaultTab` props:

```jsx
  <Tab label="Home" defaultTab={ true }>
    <div>Welcome to the homepage</div>
  </Tab>
  <Tab label="About" defaultTab={ true }>
    <div>Welcome to the about page</div>
  </Tab>
  <Tab label="Contact">
    <div>Welcome to the contact page</div>
  </Tab>
```

I don't think it would be unreasonable to say that this is undefined behaviour; in the same vein, the HTML spec [does not seem to define](https://www.w3.org/TR/html5/sec-forms.html#radio-button-state-typeradio) behaviour for if multiple radio buttons with the same `name` attribute have a `checked` attribute:

```html
<input type="radio" id="option1" name="option" value="option1" checked>
<label for="option1">Option 1</label>

<input type="radio" id="option2" name="option" value="option2" checked>
<label for="option2">Option 2</label>

<input type="radio" id="option3" name="option" value="option3">
<label for="option3">Option 3</label>
```

Although most browsers seem to simply check the last one, I don't think the behaviour is guaranteed, so personally I don't see it as an issue if this implementation creates a race condition in that scenario, as it will always resolve to some sort of usable state.

**Comment by gnapse** [comment]
Why do you need those `id` attributes? Couldn't you model it like this?

```jsx
<TabContainer defaultTabIndex={0}>
  <Tab>Home</Tab>
  <Tab>About</Tab>
  <Tab>Contact</Tab>
  <div>
    <TabContent>
      <div>Welcome to the homepage</div>
    </TabContent>
    <TabContent>
      <div>Welcome to the about page</div>
    </TabContent>
    <TabContent>
      <div>Welcome to the contact page</div>
    </TabContent>
  </div>
</TabContainer>
```

**Comment by leonaves** [comment]
A couple of issues with that:
- How will the `Tab` know what index it is to know if it is active? (assuming we are looping through the `children` of `TabContainer` to determine this index?)
- If you loop through the `children` of `TabContainer` to determine this index, what if you want to wrap `Tab`s in other elements?

**Comment by jquense** [comment]
Leonaves, you might want to check out how we've implemented the same thing in react-bootstrap using the new Context (in the `v4-support` branch: https://github.com/react-bootstrap/react-bootstrap/tree/v4-support/src Specifically the TabContainer, Nav, NavLink and TabPane

**Comment by gnapse** [comment]
Ok, now I read your original API...

```jsx
<TabContainer>
  <Tab label="Home" defaultTab={ true }>
    <div>Welcome to the homepage</div>
  </Tab>
  <Tab label="About">
    <div>Welcome to the about page</div>
  </Tab>
  <Tab label="Contact">
    <div>Welcome to the contact page</div>
  </Tab>
  <div>
    <TabContent />
  </div>
</TabContainer>
```

...and I wonder how do you get the content (`children`) of the active tab at any given time to be available for the `<TabContent />` to render. The only way I can think of right now is that you also store the children of the active tab in the context. Is that it?

Also, how does the Tab know with that setup if it is active at any given time?

**Comment by leonaves** [comment]
@jquense I have taken a brief look over your implementation, and obviously there's a lot of moving parts to it, so I may be mistaken here, but I gather it's not really possible to separate the tabs from the tab content in the rendered markup due to this section in the `render` method of the `Tabs` component:

```js
        <Nav {...props} role="tablist" as="nav">
          {ValidComponentChildren.map(children, this.renderTab)}
        </Nav>

        <TabContent>
          {ValidComponentChildren.map(children, child => {
            const childProps = { ...child.props };
            delete childProps.title;
            delete childProps.disabled;
            delete childProps.tabClassName;

            return <TabPane {...childProps} />;
          })}
        </TabContent>
```

Again though, I haven't fully conceptualised all the things going on here, and I gather it's possible to substitute out certain components with custom components that may make that possible?

**Comment by jquense** [comment]
@leonaves the Tabs component is a shortcut the TabContainer, TabPane and Nav can be used independently to create whatever you want, like this example: https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/www/src/examples/Tabs/LeftTabs.js

**Comment by leonaves** [comment]
Ah okay, so what you've essentially got there is like my second example in [this comment](https://github.com/facebook/react/issues/12596#issuecomment-380391396), but then the `Tabs` and `Tab` components wrap that to create an API similar to my original API, but in both scenarios the tabs must be assigned an explicit ID which the container must be told about to define which is the default.

I think the core of it comes down to this in my previous comment:

>>>
But I like how the existing API enforces content for each tab by design, so avoids any potential issues of having a `Tab` with no corresponding `TabContent`, or a `defaultTab` with no corresponding `Tab`. Perhaps me attempting to coerce the components into this API has caused this problem and I should change course, but this was possible without calling setValue from the render method using the old context API, so it is slightly irksome that I can't seem to achieve it with the new context API.

I'll change to assigning tabs explicit IDs if that's what needs to be done, but as I say above it is just slightly irksome that this was previously possible and now the API has changed it is no longer possible without the above anti-pattern of updating state in the render method.

**Comment by leonaves** [comment]
y u do dis :(

**Comment by gaearon** [comment]
I got lost in the discussion — is there some action item here? It seems like it was more of a question and the discussion stalled.

**Comment by leonaves** [comment]
I think I was probably going overboard in terms of explanation of this specific issue, but it does seem like a use case that the previous context API supported that the new doesn't. That being said, the whole pattern could be bad practice and it's absolutely fine for the new API to not cover this use case, and an intentional change. Would be good to know if that's the case though.

**Comment by leonaves** [comment]
I can provide a basic example in both the new and API if easier? Unless you think it's not really an actionable issue?

**Comment by gaearon** [comment]
You can probably set the value from `componentDidMount` in the child?

>But if I tried to do the initialisation in the ValueUpdaterInput component's componentDidMount method, it would be called on every render, surely, as ValueUpdaterInput would be re-rendered each time?

I don't understand this part. `componentDidMount` only fires on *mount* (once), not on every render.

**Comment by leonaves** [comment]
Sorry I didn't mean to say "re-rendered", I meant re... initialised? I.e:

```js
({ value, setValue }) => (
  <ValueUpdaterInput setValue={ setValue } value={ value } />
)
```

Does this function not create a new instance of the `ValueUpdaterInput` component whenever it is called? Although writing this now, I'm thinking perhaps I'm missing something about react's internals, as by the same logic, a child inside a parent's render method would also be re-initialised each time render is called...

**Comment by leonaves** [comment]
Yeah you've literally [answered this already](https://medium.com/@dan_abramov/react-components-elements-and-instances-90800811f8ca). Sorry for taking up your time.

**Comment by gaearon** [comment]
Haha no problem. Yeah, React will only create one instance if the element is rendered in the same "place" with the same type and key. Otherwise every single update would lose the state in every component.

**Comment by leonaves** [comment]
By the way, `contextType` in 16.6 makes this way easier, thank you!
