### ISSUE TITLE
Can't use AsyncStorage or Fetch inside getDerivedStateFromProps

### ISSUE THREAD

**Issue by sfyfe31** [facebook/react#12595]
I'm trying to migrate from using `componentWillReceiveProps` to `getDerivedStateFromProps`.

I'm using [Tab Navigation](https://reactnavigation.org/docs/tab-based-navigation.html), adding a `route_index` property to the state with `onNavigationStateChange`. Then in the screen file for each tab, I detect if we're on the correct index and if so, load a value from storage and then fetch some data from an API. Here's how I'm currently doing this inside the tab's screen:

```
UNSAFE_componentWillReceiveProps (newProps) {
    if (newProps.screenProps.route_index === 2) {
      AsyncStorage.getItem('MyBar')
      .then(myBarID => {
        if (myBarID) {
          GetBars(myBarID, (err, bars) => {
            if (err) {
              console.error(err)
            } else if (bars && bars.length) {
              this.setState(prev => {
                prev.loadingBar = false
                prev.myBar = bars[0]
                return prev
              })
            }
          })
        }
      })
    }
  }
```

But using the new `getDerivedStateFromProps` static function, it doesn't seem to be able to update the state within AsyncStorage or Fetch (`GetBars` is an imported service which is just a wrapper function for a fetch call against an API):

```
  static getDerivedStateFromProps (newProps, prevState) {
    if (newProps.screenProps.route_index === 2) {
      AsyncStorage.getItem('MyBar')
      .then(myBarID => {
        if (myBarID) {
          GetBars(myBarID, (err, bars) => {
            if (err) {
              console.error(err)
              return null
            } else if (bars && bars.length) {
              return { loadingBar: false, myBar: bars[0] }
            } else {
              return null
            }
          })
        } else {
          return null
        }
      })
    } else {
      return null
    }
  }
```

I tried using `componentWillMount`, but it only fires the first time the tab is loaded. I need to do an Storage and API call every time the user changes to a tab.

**Comment by gaearon** [comment]
That's intentional—`getDerivedStateFromProps` is meant for cases where you *synchronously* calculate state from props. It’s not meant for async requests.

Please move any data fetching code into `componentDidMount` and/or `componentDidUpdate`. 

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change
