### ISSUE TITLE
can we put two root or subroot items in ReactDOM.render like in case of creating canvas

### ISSUE THREAD

**Issue by animehk55** [facebook/react#12597]
💯 Files to be rendered and is working fine with canvas being printed on this Product page 👍 

```js
ReactDOM.render(
	<Product width={400} height={480} />,
	document.getElementById('root'));
registerServiceWorker();
```

💯 Next If there is files below like with fronted page(s) and then Product with canvas.As mentioned below : 

```js
<App />,
<Product width={400} height={480} />,
	document.getElementById('root'));
registerServiceWorker();
```

🔢 How can I render both the pages as the same time as in 1st its the designing pages and second the canvas element to be printed. 

Is there any other way to create canvas or print both the files. Please suggest me.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
