### ISSUE TITLE
React 16 migration issue

### ISSUE THREAD

**Issue by AshiquK** [facebook/react#12603]
As there is no react/lib/* and react-dom/lib/* anymore, I am getting the error:

 Module not found: Error: Cannot resolve module 'react-dom/lib/ReactInjection'

Parts of my code where it is used:

import { DOMProperty } from 'react-dom/lib/ReactInjection';

....

DOMProperty.injectDOMPropertyConfig(HTMLDOMPropertyConfig);

...

Please give me an alternative solution for this.

**Comment by milesj** [comment]
These APIs were purposefully made private. There most likely isn't a solution for this.

**Comment by AshiquK** [comment]
Is there any way to fix that error. How can I complete the migration to React 16 ?

**Comment by AshiquK** [comment]
import { DOMProperty } from 'react-dom/lib/ReactInjection';

...

const HTMLDOMPropertyConfig = {
  isCustomAttribute: attributeName => attributeName.indexOf('analytics-') === 0,
};

DOMProperty.injectDOMPropertyConfig(HTMLDOMPropertyConfig);

...

**Comment by jquense** [comment]
So adding custom attributes? You can't do it that anymore no, but react 16 also doesn't care anymore about what attributes you add to DON nodes. So you don't need any special logic to use them, just add em to the element.
