### ISSUE TITLE
context should propagate across React.renderComponent()

### ISSUE THREAD

**Issue by petehunt** [facebook/react#1260]
I really want this to work: http://jsfiddle.net/RxRK8/

**Comment by ericclemmons** [comment]
I'm with @petehunt.  Knowing that `React.withContext` will be deprecated, there are few options to handle this.

**Comment by RickWong** [comment]
:+1: Maybe the deprecation of `React.withContext` was premature.

**Comment by jsfb** [comment]
Context is going to be parent-based, so this request is obsolete.  Closing.
