### ISSUE TITLE
isMounted is deprecated

### ISSUE THREAD

**Issue by jsina** [facebook/react#12605]
I've get an "isMounted(...) is deprecated in plain javascript react classes" error with this dependencies, I wanna know that is there any problem with react-navigation with with ```"react": "16.3.1",``` or not?
```
  "dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-navigation": "^1.5.11"
  },
```

**Comment by jquense** [comment]
Hey there, we use the issue tracking for react bug reports. If you have a question about a specific library try asking on their repo or use one of the many support avenues. Thanks!

**Comment by erwan-lcs** [comment]
Following the thread:
Not a react-navigation issue: https://github.com/react-navigation/react-navigation/issues/3956#event-1602688750
Not a react-native issue: https://github.com/facebook/react-native/issues/18868 
It seems to be a React issue.
Some old issues reference isMounted as deprecated but looks like it's been fixed a long time ago... confused as it seems to suddenly become a problem in many react native projects.

```
  "dependencies": {
    "appcenter": "^1.1.0",
    "appcenter-analytics": "^1.1.0",
    "appcenter-crashes": "^1.1.0",
    "axios": "^0.17.1",
    "eslint-config-rallycoding": "^3.2.0",
    "lz-string": "^1.4.4",
    "moment": "^2.21.0",
    "react": "16.2.0",
    "react-native": "0.52.0-rc.0",
    "react-native-device-info": "^0.12.1",
    "react-native-fcm": "^10.0.3",
    "react-native-fs": "^2.9.7",
    "react-native-mail": "^3.0.5",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "1.0.0-beta.21",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
```

**Comment by gaearon** [comment]
It is most likely a React Native issue in this case.
Let's continue the discussion in https://github.com/facebook/react-native/issues/18868.
