### ISSUE TITLE
nested context does not update any longer

### ISSUE THREAD

**Issue by drcmda** [facebook/react#12604]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Nested context consumers do not seem to update leaving higher up updates stale:

![context](https://user-images.githubusercontent.com/2223602/38607388-ca637efe-3d78-11e8-8ec7-530597450910.gif)

https://codesandbox.io/s/1qwq93n01q

**What is the expected behavior?**

The critical piece of code that composes multiple consumers is this one:

```jsx
let values = []
return [...contextRefs, Wrapped].reduceRight((accumulator, Context, i) => (
    <Context.Consumer>
        {value => {
            values[i] = value
            if (accumulator === Wrapped) {
                let context = mapContextToProps(...values, props)
                context = typeof context === 'object' ? context : { context }
                return <Wrapped {...props} {...context} />
            } else return accumulator
        }}
    </Context.Consumer>
))
```

From a dynamic array of context providers it creates a nested blob of consumers with the receiver sitting at the end (`Foo` in this example).

The first consumer fires and does get the value, it then returns the sub-tree (`accumulator`, which contains the second consumer, which contains `Foo`) but it doesn't actually render, it looks like something in Context.Consumer prevents it.

In the React alphas i believe they would render regardless. I wonder how it would be possible to forward changed values to the actual receiver, i can't call setState in there.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3.1

**Comment by drcmda** [comment]
PS. the critical piece of code that composes multiple consumers is this one:

```jsx
let values = []
return [...contextRefs, Wrapped].reduceRight((accumulator, Context, i) => (
    <Context.Consumer>
        {value => {
            values[i] = value
            if (accumulator === Wrapped) {
                let context = mapContextToProps(...values, props)
                context = typeof context === 'object' ? context : { context }
                return <Wrapped {...props} {...context} />
            } else return accumulator
        }}
    </Context.Consumer>
))
```

**Comment by jquense** [comment]
Can you provide a reproduction that uses Context elements directly and illustrates the bug? It's not clear that the problem is in React from your codesandbox

**Comment by drcmda** [comment]
@jquense 

I tried to replicate it as faithfully as i could: https://codesandbox.io/s/7212l1qjlj

As you see, the state is updated, it re-renders the first provider on the state-value change. But the update doesn't reach the receiving component.

**Comment by gaearon** [comment]
Not saying this is the problem, but it looks shady to me:

<img width="425" alt="screen shot 2018-04-11 at 4 24 10 pm" src="https://user-images.githubusercontent.com/810438/38626590-cec1b34a-3da4-11e8-8c56-c4b8d678a7f8.png">

Render method (including context consumer's render prop) is supposed to be pure. Using it with a closure like this can lead to weird bugs.

**Comment by drcmda** [comment]
That's the thing, without hoc it works because everything in the same tree. *Something* prevents the second consumer from updating.

**Comment by drcmda** [comment]
PS. here's the same with React@alpha-371 --- and it works:

https://codesandbox.io/s/04ky0zlkr0

So something must have changed.

**Comment by gaearon** [comment]
Don't look at 16.4.0 alpha please, it's broken in a myriad of ways and isn't very useful. :-)

**Comment by drcmda** [comment]
In that aspect it works as expected though. The problem is in the current React. If context.Consumer doesn't update (like any React.Component would), it pretty much means that dynamic context in React is no longer possible.

**Comment by gaearon** [comment]
I'm sorry—I'd love to help out but I'll need a more reduced example that doesn't mutate anything in closures and that doesn't have HOCs. I don't agree that "without hoc it works because everything's in the same tree": HOC is nothing but an abstraction that generates a component. "Unrolling" HOC manually in the code could produce more code but would not change the semantics of it. React doesn't care if you use HOCs or not.

**Comment by drcmda** [comment]
It's not the hoc something must have changed in how the consumer behave in React. My guess is that the accumulator is becoming stale. But creating a nested blob of consumers is the whole point.

This works:

```jsx
          <context1.Consumer>
            {value1 => (
              <context2.Consumer>
                {value2 => `${value1} ${value2}`}
              </context2.Consumer>
            )}
          </context1.Consumer> 
```

But the moment i do it dynamically, and i wouldn't know how else this would be possible if not reduce, then suddenly it doesn't work:

```jsx
    const values = []
    return [context1, context2, View].reduceRight((accumulator, Context, i) => (
      <Context.Consumer>
        {value => {
          values[i] = value
          return accumulator === View ? <View values={values} /> : accumulator
        }}
      </Context.Consumer>
    ))
```

**Comment by gaearon** [comment]
Again, I don't think the logic with pushing something into a closure will work. It's not obvious to me why it doesn't (I'd need to spend time looking into it) but it's just *not supported* to have impure render like this.

**Comment by gaearon** [comment]
Do you know the stack of contexts at init time? Or only render time?

**Comment by drcmda** [comment]
Both are possible, when it's a HOC it's known statically:

    subscribe([Theme, Store], (theme, store) => ({ theme, store }))(MyComponent)

But it's also possible dynamically:

```jsx
    <Subscribe to={[Theme, Store]} pick={(Theme, Store) = ({ Theme, Store )}>
        {props => ...}
     </Subscribe>
```

**Comment by gnapse** [comment]
Have you tried several utilities that exist to compose nested render props?

- https://github.com/gnapse/render-props-compose
- https://github.com/jamesplease/react-composer
- https://github.com/pedronauck/react-adopt

Even if you don't end up using them, you can check out how they're implemented.

**Comment by drcmda** [comment]
I believe most of them would fail with react 16.3.1, because they probably do it the same way i do: https://github.com/drcmda/react-contextual/blob/master/src/subscribe.js

**Comment by gnapse** [comment]
No. I believe none of them do any mutations in the process, as you seem to need to do in [here](https://github.com/drcmda/react-contextual/blob/a8d35863a156814e86c0f82af1eb357fad89c401/src/subscribe.js#L34). I know at least mine does not do any mutation at all (it used to do it in the initial implementation but it is now purely pure, pun intended).

**Comment by drcmda** [comment]
Very interesting, thanks a lot, i'll see if this works.

**Comment by gaearon** [comment]
Looks like the version without mutation works.

```js
    const consumers = [context1, context2].reduceRight(
      (inner, ctx) => (...args) => (
        <ctx.Consumer>
          {value => inner(...args, value)}
        </ctx.Consumer>
      ),
      (...values) => <View values={values} />
    )();
```

https://codesandbox.io/s/13zw6lxm1j

**Comment by gaearon** [comment]
If you’re curious how I unrolled it:

![gif that goes through the process](https://d2ffutrenqvap3.cloudfront.net/items/0w2N2M0K2n0c1i1i0U2L/Screen%20Recording%202018-04-11%20at%2009.48%20PM.gif?v=7d5f0ddb)

**Comment by drcmda** [comment]
Incredible! Thanks so much! https://github.com/drcmda/react-contextual/blob/master/src/subscribe.js#L28

Need to study more functional programming ... i couldn't have done this in a hundred years 😓

**Comment by gaearon** [comment]
If it’s easier to do with a loop then use a loop 🙂 I don’t think it’s necessary to use reduce in every case.

If you list each context in a separate statement like I did then it should become visible what the loop body should be like. Then reduce vs loop is only a choice of form.

**Comment by redwormik** [comment]
Hi, late to the discussion, but I think i figured it out (being totally nerd-sniped here).
The mutation in render is not the cause here (not saying it is safe either). The real cause is the React elements being reused, if they are recreated, it works https://codesandbox.io/s/ql0592xxnq (I added just another lambda + calls).
Is this an expected behavior, not to update the consumer if the element is the same, even though the closed value may change?

**Comment by drcmda** [comment]
@redwormik thanks, i suspected it's the accumulator not getting updated, but my mind was stuck on context.consumer. The last example isolates it nicely, @gaearon is this known/expected behaviour?

**Comment by damianobarbati** [comment]
@gaearon I think I have a similar problem but I'm not sure: **my Provider is not updating Consumer/s.**

I fully reproduced it here: https://codesandbox.io/s/ry86mlylmm

At Router.js:4 I define my context with a `redirect` prop equal to a noop (Function.prototype).
At Router.js:22 I'm setting my context `redirect` prop equal to Router.redirect method and I'm attaching it to the state.
At Router:46 I set the context.value = Router.state thus hoping my Consumers will re-render when I'm updating it.

At Router:22 (in componentDidMount) the state is updated and I can see the Router re-rendering (console logging).

But Consumers are not,  withRouter.js:12 never logs the re-render!

What's wrong with my Context?

**Comment by hamlim** [comment]
@damianobarbati It looks like your `<Link />` components are rendered outside of the router context (see Layout.js and index.js). Currently as you have it the Nav component is rendered above the Router, meaning the Links will fallback to the default value passed to `createContext`.

**Comment by damianobarbati** [comment]
Thanks @hamlim, that solved (y)!
