### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined while importing react and react-dom

### ISSUE THREAD

**Issue by anikethsaha** [facebook/react#12616]
This are my dependencies and there version ( if it helps ) 
```
 "dependencies": {
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "webpack": "^2.1.0-beta.25"
  },
```
I have the most simplest code for the hello world using react component
````
import React from 'react';
import ReactDOM from 'react-dom';

class Hello  extends React.Component{
  render(){
    return (
      <h1>hello  world</h1>
    )
  }
}
ReactDOM.render(
  <Hello />,
  document.getElementById('root')

)
```
`


using bundle.js in the html script to bundle up everything 
**getting error**

`Uncaught TypeError: Super expression must either be null or a function, not undefined
    at _inherits (script.js:2)
    at bundle.js:7830
    at Object.<anonymous> (script.js:11)
    at __webpack_require__ (bootstrap d328d05e6065876b9d70:19)
    at bootstrap d328d05e6065876b9d70:63
    at bootstrap d328d05e6065876b9d70:63`

thanks in advance

**Comment by gaearon** [comment]
Please provide a complete example. Something is probably broken with how your build is set up.

**Comment by anikethsaha** [comment]
this is the complete script ! can you specify what you need ?

**Comment by gaearon** [comment]
Please upload a complete project. The code is fine, it’s your build setup that is probably broken.

If you’re not sure how to configure it I recommend using an officially supported method, like described on these pages:

https://reactjs.org/docs/try-react.html
https://reactjs.org/docs/add-react-to-a-new-app.html

Then you won’t have issues like this. 

But if you upload your project I can take a look at what’s wrong.

**Comment by anikethsaha** [comment]
ok let me create a project in git and i will add link in the comment

**Comment by anikethsaha** [comment]
here is the link of the project 
[https://github.com/anikethsaha/reactapp](url)

**Comment by aweary** [comment]
@anikethsaha you're code is extending `React.Components`, when it should be `React.Component` (no "s" at the end of Component).

**Comment by anikethsaha** [comment]
i changed that but still no hope

**Comment by gaearon** [comment]
From the code you provided:

```js
class Hello extends React.Components{
```

There is no such thing as `React.Components`. You probably meant `React.Component`.

The error says that the “super expression” (what is being extended) can’t be undefined. `React.Components` is undefined because it is a typo.

**Comment by anikethsaha** [comment]
@gaearon i changed that earlier itself but still not getting

**Comment by anikethsaha** [comment]
I did recompile the webpack after changing. I have been using react using the browser.js cdn link and react and react-dom link in the script for past 2 days it was working fine may be I wasn't using es6.  but there I was facing some problem with styling etc so I shifted to this method.
i will look into the link you mention

**Comment by gaearon** [comment]
If you still have the same problem after the suggested changes please push your changes to GitHub and we will look again. It’s hard to help without seeing what exactly you’ve changed and what issue you’re seeing now.

**Comment by gaearon** [comment]
(I saw your commit in https://github.com/anikethsaha/reactapp/commit/4b41bd22445307fd8f9ae15b20e0eae23d75250f but that didn’t include the compiled bundle. Since you checked it in and you claim to have recompiled it, I’d need to see a commit that confirms it.)

**Comment by anikethsaha** [comment]
i did commit in the git and after that only i recompiled it in my pc thats what i mean with that comment
I change the compiled bundle.js

**Comment by gaearon** [comment]
If you still have the issue please post a screenshot and commit/push your changes

**Comment by anikethsaha** [comment]
i changed the bundle.js in the my repo you can check 
the error is same only as mentioned above

**Comment by gaearon** [comment]
You still have the same typo in the bundle:

https://github.com/anikethsaha/reactapp/blob/151ad44983b8023e8033771de91a7461e736d34a/bundle.js#L7850

So it’s not recompiled.

**Comment by anikethsaha** [comment]
thanks I guess this is only the error I recompiled the bundle.js 2 -3 times after changing the `Components` to `Component` in `script.js`  but it is not changing in the bundle 
may be some error in config
i will check for that

**Comment by hhgnsc** [comment]
@anikethsaha
It blames to `inline` option in UglifyJS. You can set `inline: false` like this:
```javascript
new UglifyjsWebpackPlugin({
  uglifyOptions: {
    compress: {
      inline: false
    }
  }
})
```
It's work for me.

**Comment by abelmagana88920** [comment]
> @anikethsaha It blames to `inline` option in UglifyJS. You can set `inline: false` like this:
> 
> ```js
> new UglifyjsWebpackPlugin({
>   uglifyOptions: {
>     compress: {
>       inline: false
>     }
>   }
> })
> ```
> 
> It's work for me.

This saved me from the issue. Thanks

Im using react-scripts v2 , then i override the webpack config using react-app-rewired


in package.json 

"scripts": {
    "analyze": "source-map-explorer build/static/js/main.*",
    "start": "NODE_PATH=src/ CHOKIDAR_USEPOLLING=true PORT=3143 react-app-rewired start",
    "build": "NODE_PATH=src/ react-app-rewired build",
    "test": "NODE_PATH=src/ react-app-rewired test --env=jsdom",
    "eject": "NODE_PATH=src/ react-app-rewired eject"
  },
  
  
  while in config-overrides.js

/* config-overrides.js */
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = function override(config, env) {
  //do stuff with the webpack config...
  if (!config.optimization) {
    config.optimization = {};
  }
  config.optimization.minimizer = [new UglifyJsPlugin({
    uglifyOptions: {
      compress: {
        inline: false
      }
    }
  })]
  return config;
}
