### ISSUE TITLE
BREAKING CHANGE in 16.3.2: Using 16.3.2 I am getting a lot of ref="string" errors

### ISSUE THREAD

**Issue by richtera** [facebook/react#12626]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I use the new version 16.3.2 I am getting a lot of error concerning that I set ref="name" for a component that doesn't have an owner. This works fine in 16.3.1 so I am not sure if your code got more stringent or if this is a bug detecting things it shouldn't. I have changed my code to work either way, but many third party libraries are breaking with this change.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
This should work identical to 16.3.1 (if this is a new thing they this should be 16.4.x or maybe even larger)
Rolling the code back to 16.3.1 works normally.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.3.2

**Comment by aweary** [comment]
@richtera can you please provide an example that reproduces the issue?

**Comment by aweary** [comment]
@richtera can you please share the full error message and stack trace that you're getting?

**Comment by richtera** [comment]
I am trying to reproduce it in a sample application but so far no luck. Changing from 16.3.1 to 16.3.2 completely breaks my app, but I cannot break any small sample app yet. The failed render happens from within a mobx update.
```
"Error: Element ref was specified as a string (overlay) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.

invariant (invariant.js:42)
coerceRef (react-dom.development.js:7338)
createChild (react-dom.development.js:7543)
reconcileChildrenArray (react-dom.development.js:7793)
reconcileChildFibers (react-dom.development.js:8109)
reconcileChildrenAtExpirationTime (react-dom.development.js:8228)
reconcileChildren (react-dom.development.js:8219)
updateHostComponent (react-dom.development.js:8527)
beginWork (react-dom.development.js:8970)
performUnitOfWork (react-dom.development.js:11798)
workLoop (react-dom.development.js:11827)
renderRoot (react-dom.development.js:11858)
performWorkOnRoot (react-dom.development.js:12422)
performWork (react-dom.development.js:12343)
performSyncWork (react-dom.development.js:12320)
requestWork (react-dom.development.js:12220)
scheduleWorkImpl (react-dom.development.js:12095)
scheduleWork (react-dom.development.js:12055)
scheduleRootUpdate (react-dom.development.js:12683)
updateContainerAtExpirationTime (react-dom.development.js:12711)
updateContainer (react-dom.development.js:12730)
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (react-dom.development.js:16030)
(anonymous) (react-dom.development.js:16449)
unbatchedUpdates (react-dom.development.js:12530)
legacyRenderSubtreeIntoContainer (react-dom.development.js:16445)
render (react-dom.development.js:16513)
(anonymous) (index.tsx:117)
Promise.then (async)
bootup (index.tsx:110)
./src/learn/index.tsx (index.tsx:9)
__webpack_require__ (bootstrap:763)
fn (bootstrap:141)
4 (app.learn.js:85031)
__webpack_require__ (bootstrap:763)
checkDeferredModules (bootstrap:43)
(anonymous) (bootstrap:824)
(anonymous) (bootstrap:824) 
```
The render is caused by a mobx change. I even tried to use a mobx sample but it's not quite setting up stores in the same way to cause this problem. Since this code works fine under 16.3.1 I am not quite sure how to specifically setup another example to fail the same way. All the code I have looked at so far look fine and I am not seeing any weird race conditions or so on.

**Comment by gaearon** [comment]
Have you considered this possibility outlined in the message?

```
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.
```

If you follow the link it includes diagnostic instructions that help determine if you have multiple copies of React. This can happen when updating React if you use a buggy version of a package manager, if your build is set up incorrectly, or if some third-party library is bundled or published incorrectly.

**Comment by richtera** [comment]
I do not have multiple copies of react. I lock them all to the version I am using in package.json using resolutions and I use yarn.
It seems to be crashing in this section of the code.
![image](https://user-images.githubusercontent.com/708186/38842911-9f1c8ef2-41ba-11e8-96ca-4eafda607582.png)

**Comment by gaearon** [comment]
Is it possible that you have another `node_modules/react-dom` or `node_modules/react` *above* the project folder? For example in some parent project or even accidentally installed in `node_modules` of the home directory.

**Comment by richtera** [comment]
I have checked the parent folder. I reinstalled all node_modules and I can change resolutions to ```=16.3.1``` for react, react-dom and so on to make it work and ```^16.3.1``` to make it fail. I can switch it back and forth but I have not figured out why a basic sample project doesn't fail the same way.

**Comment by gaearon** [comment]
And `=16.3.2` also fails, right?

**Comment by richtera** [comment]
Yes. Anything that pulls in 16.3.2 will fail for me.

**Comment by gaearon** [comment]
My understanding is:

1. We didn’t change anything about the string ref ownership mechanism between these releases

2. The same code runs fine at Facebook where we have thousands of string refs

3. No one else reported this yet

So my best guess is something is wrong with your environment (or, I dunno, maybe Yarn has a bug), and somehow the update makes the existing issue visible.

If you want to debug this more you can search for strings starting with`"16` or `”15` in your bundle. This should normally show only one match in React where we define `React.version' (or at most two matches before minification, dev and prod, but one should never hit a breakpoint). If you have more matches you’re pulling a duplicate React somehow.

Hard to say more without seeing the bundle or a reproducing example.

**Comment by richtera** [comment]
Ok I will check. But the check that's failing has _owner being null and not a fiber from another version. It seems the way our application boots up now conflicts with whatever is happening in 16.3.2. We are calling ReactDOM.render() in a promise from firebase to validate the current login token. Since I don't see the same problem within a little sample application I realize that I am looking for a needle in a haystack.

**Comment by gaearon** [comment]
Let me explain how it works.

1. ReactDOM starts rendering a class component
2. It sets `React.(long property chain).owner`
3. When class component calls `React.createElement` with a string ref, it reads the owner from the same property

The issue you’re experiencing occurs when ReactDOM “finds” a different React than the one used by the component. ReactDOM sets owner field on the React *it* finds but then the *other* React used from the component doesn’t have the field set (and thus sees a null owner).

Does this help explain it? You can debug assignments and reads to and from `CurrentOwner.current' and see how this plays out.

**Comment by richtera** [comment]
@gaearon Is there a place where I can watch it "find" a or the wrong version of React so I can put a breakpoint there? This makes sense to me but I am unable to detect a second version in my webpack.

**Comment by richtera** [comment]
Ah I debugged all assignments and retrievals of ReactCurrentOwner.current. Seems changing some of my componentWillMount to componentDidMount will resolve the problem. So in 16.3.2 it seems to be a bit more sensitive to that. At least this is what I am seeing here, there could be another part of this puzzle, of course. Thanks for the help @gaearon

**Comment by richtera** [comment]
So I think this was a false alarm although this version is more stringent on the componentWillMount not resulting in a completion that could possibly cause an update.

**Comment by gaearon** [comment]
I don’t think I understand what you’re saying.

**Comment by richtera** [comment]
Basically running the same code under 16.3.1 works but doesn't work under 16.3.2. Changing componentWillMount calls that initiate promises that can cause property or state changes to componentDidMount will make it work on both. So 16.3.2 is a little more sensitive to invalid state changes than previously. So the docs talking about these issues become much more important. But it's definitely something cause by our code

**Comment by gaearon** [comment]
There were no known changes in lifecycle order between these two releases. Moreover React shouldn’t come at you with cryptic bugs when you accidentally do something in a wrong lifecycle.

I’d still appreciate if you could isolate it. If moving something between lifecycles fixes this then it sounds like a React bug.
