### ISSUE TITLE
Update component without rerender it

### ISSUE THREAD

**Issue by mojtabamarashee** [facebook/react#12632]
reactjs doc says "**With our knowledge so far, the only way to update the UI is to create a new element, and pass it to ReactDOM.render**()" .
but consider a canvas component, you could update it without rerendering, for example in the "**componentWillReceiveProps**" create new line on canvas so even if "**shouldComponentUpdate**" retrun false, the canvas will be updated
Am I wrong?

**Comment by gaearon** [comment]
I don't understand what exactly you're asking.

The doc is saying that with our knowledge *so far* (that is, from [this](https://reactjs.org/docs/introducing-jsx.html) and [this](https://reactjs.org/docs/rendering-elements.html) page) we only know about `ReactDOM.render`. In the next doc pages it is demonstrated how to use `setState` in components to re-render.

Does this answer your question?
