### ISSUE TITLE
Support performance measures in production

### ISSUE THREAD

**Issue by stephen** [facebook/react#12634]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.

I'd like to have access to an API for `performance.mark` / `performance.measure` in a production build of react, so that we can collect timing measurements for real users in the field.

I suspect performance timing can get expensive, so I am open to suggestions for how to make that nicer/possible.

**Comment by gaearon** [comment]
There’s technically already a way to do it if you don’t mind mucking with our build system. Specifically you can look at how `ReactDOMFB` exposes it for our internal builds. Maybe we could add an official “profiling” build for this.

**Comment by gaearon** [comment]
Seems like https://github.com/reactjs/rfcs/pull/51 will address this better.
