### ISSUE TITLE
Render Props & getDerivedStateFromProps Issue!

### ISSUE THREAD

**Issue by dcflow** [facebook/react#12646]
Hi guys,

**Do you want to request a *feature* or report a *bug*?**

Possibly a bug.

**What is the current behavior?**

There is an issue when HoC update the props that they pass down to their child components.

As a example: `react-apollo` has a  `Query` HoC component that does a query for data on the server and when the data is fetched it passes it down to the `children`.

When we use `componentWillReceiveProps` the `nextProps` is updated with the new props, the contrary happens with `getDerivedStateFromProps` which is called only the first time.

Example Code
```
class A extends React.Component {
  render() {
    return (
      <Query query={GET_DATA}>
        {({ data }) => <B data={data} />}
      </Query>
    )
  }
}

class B extends React.Component {
  static getDerivedStateFromProps(nextProps, prevState) {
    console.log(nextProps)
    return null
  }
}

```
The first time the `data` obj is empty than is filled with the response.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3.2

Thank You!

**Comment by gaearon** [comment]
>When we use componentWillReceiveProps the nextProps is updated with the new props, the contrary happens with getDerivedStateFromProps which is called only the first time.

I don't understand what this means. `getDerivedStateFromProps` is called both for initial render and for updates.

Can you provide a complete example?

**Comment by dcflow** [comment]
Sorry Dan it was an issue with `react-apollo` they will fix it it in the upcoming release :man_shrugging: 
Thank you for your response :)
