### ISSUE TITLE
[Question] Marking html elements for testing

### ISSUE THREAD

**Issue by marko93ue** [facebook/react#12650]
Hi, i have part of component that renders like this: 
```jsx
return(
<div className={style.OuterWrapper}>
    <div 
       className={style.Item} 
       onClick={this.yesterdayFn}
       day='yesterday'
    >
       Yesterday
    </div>
    <div
      className={style.Item}
      onClick={this.todayFn}
      day='today'
    >
      Tomorrow
    </div>
    <div
      className={style.Item}
      onClick={this.tomorrowFn}
      day='tomorrow'
    >
      Today
    </div>
</div>
);
```

I'v been using `day` prop to find elements during testing with enzyme. 
Like this: `wrapper.find('day=["today"]').simulate('click')` but I don't like it very much. Only other option that comes to my mind is for each clickable div make custom class name and search by class name.

Search by text , function name or div position makes tests very fragile so I would like to avoid it.

How do you mark html elements for easy searching?

**Comment by gaearon** [comment]
You can mark them with some special attribute, e.g. `data-testid="something"`.

**Comment by marko93ue** [comment]
Thanks for quick response. Seems like special attribute it is.
