### ISSUE TITLE
[Question] Best way to get element DOM reference

### ISSUE THREAD

**Issue by inomdzhon** [facebook/react#12657]
**Preface**

I'm writing popup component, whose task is to be positioned content (next call **B**) relative target (next call **A**). **B** can have arrow as optional (next call...**arrow**). Popup component is like **core** for positioning. It can be used to create a drop-down list, tooltip or something else.

![image](https://user-images.githubusercontent.com/5850354/39014028-d5f2c96e-4421-11e8-8fff-76419b68dcca.png)

For resolve this task, we need to get:
1. DOM reference of **B**
2. DOM reference of **A**
3. DOM reference of **arrow**

Go to use my realisation as an example — [sandbox](https://inomdzhon.github.io/react-popup/) ([source](https://github.com/inomdzhon/react-popup/tree/master/Popup)). Here I take:

- **A** through `reference` props
- **B** and **arrow** from `ref` in Popup `render()`

After all calculated I put **B** in DOM with `React.createPortal`. _Note:_ for positioning I use [popper.js](https://popper.js.org/) library.

**Problem**

For more flexibility I want transfer to Popup component **render function**. Like this:

```
<Popup arrow reference={this.elemTarget}>
  {({ styles, arrowStyles, placement  }) => {
      <div {/* <-- our B */}
         style={styles}
         data-placement={placement}
      >
         <div style={arrowStyles} /> {/* <-- our arrow */}
         Some text/component
      </div>
  }}
</Popup>
```

It can be more useful for:

- smooth transitions from one **A** to next **A** (animating `styles` in parent component or in store)
- custom inner structure

Now I don't know right way to get reference of **B** and **arrow**. Maybe I can get **B** with `ReactDOM.findDOMNode` in Popup `render()`, but what about the **arrow**?

Thanks.
Thanks for what you do ✌️

**Comment by raunofreiberg** [comment]
Have you tried using https://github.com/tvkhoa/react-tippy? I'm using this at work for my tooltips (over 10) and it has fit all of our use cases.

**Comment by inomdzhon** [comment]
Sorry about this. I saw `Type Question` in labels and thought it's right place for question 😕

Ok, I go to other forum with my question.

`react-tippy` solve only tooltip tasks and not clear react way, I think.

Thanks.
