### ISSUE TITLE
Returning Fragment with undefined children from render causes invariant violation

### ISSUE THREAD

**Issue by polytypic** [facebook/react#12661]
**Do you want to request a *feature* or report a *bug*?**

I'm reporting a bug.

**What is the current behavior?**

React reports an invariant violation when the `render` method of a class component returns a `Fragment` with `undefined` children.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

[Example in CodeSandbox](https://codesandbox.io/s/5zq4qxnn3n)

```jsx
import React from 'react'
import {render} from 'react-dom'

class App extends React.Component {
  render() {
    return <React.Fragment>{undefined}</React.Fragment>
  }
}

render(<App />, document.getElementById('root'))
```

**What is the expected behavior?**

I would expect the program to render nothing.  That is because in other contexts children in React are allowed to be `undefined`.  `Fragment` itself renders fine with `undefined` children when it is not returned from the `render` method of a class component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I tested this with version 16.3.2.

**Comment by jquense** [comment]
yup, to render nothing you need to intentionally return `null`. The reason, as the error suggests, is to reduce possible bugs from someone forgetting a `return` in their render, the explicit `null` is a clearer signal that you want to render nothing, vs forgot to return something

**Comment by polytypic** [comment]
Please note that the example I gave is only a minimal test case that reproduces the issue.  In the actual program that exposed this issue, the fragment is not created with a constant `undefined`, but with a computed value that ends up being `undefined` in some cases.

Consider the following, almost identical, program:

```jsx
import React from 'react'
import {render} from 'react-dom'

class App extends React.Component {
  render() {
    return <React.Fragment>{null}</React.Fragment>
  }
}

render(<App />, document.getElementById('root'))
```

The above program does not cause an invariant violation.  Yet it does not return `null` to render nothing.  Shouldn't this case also cause an invariant violation?

The following example also renders nothing without an error:

```jsx
import React from 'react'
import {render} from 'react-dom'

render(<React.Fragment>{undefined}</React.Fragment>, document.getElementById('root'))
```

`React.Fragment` is treated differently when it is returned from a `render` method.  This seems counter intuitive to me.

At any rate, thanks for responding to the bug quickly!  I will not comment to this issue further.
