### ISSUE TITLE
[Question] How to deal with RenderProps Components callback hell?

### ISSUE THREAD

**Issue by xialvjun** [facebook/react#12664]
This issue is somewhat long. If you are eager, goto the `FINAL_BUT`.

# How to deal with RenderProps Components callback hell?

Yes, there is a package `react-adopt`. It's awesome, but it has problems. Let me show you:

```jsx
import { Value } from 'react-powerplug';
import { adopt } from 'react-adopt';

A_and_B = adopt({ mapper: { a: <Value initial="A"/>, b: <Value initial="B"/> } });
<A_and_B>
  {({ a, b }) => <div>{a + b}</div>}
</A_and_B>
```

#### Then what if I want dynamic `mapper`:

```jsx
import { Adopt } from 'react-adopt';

A_and_B = adopt({ mapper: { a: <Value initial="A"/>, b: <Value initial="B"/> } });
<Adopt mapper={{ a: <Value initial="A"/>, b: <Value initial="B"/> }}>
  {({ a, b }) => <div>{a + b}</div>}
</Adopt>
```

In fact, there is a bug in `Adopt` at least in `react-adopt@0.3.1`: it didn't cache the Component returned from `adopt`, then react will always treat it like a different Component, then rebuild the DOM.

Well, it's just a bug of `react-adopt`, not `react`'s.

#### But the above example is not a really dynamic `mapper`. What if I want a really dynamic `mapper`(assume we have fixed the bug)?

```jsx
count = 10;
<Adopt mapper={new Array(count).fill(0).map((_, idx) => <Value key={idx} initial="A"/>)}>
  {obj => <div>{Object.keys(obj).map((_, idx) => obj[idx]).join()}</div>}
</Adopt>
```

Then if we `this.setState({ count: 9 })`, the DOM will rebuild even we have fixed `Adopt`'s `no cache bug`.

> **WHY**: `react-adopt` just expand `mapper={[<Value initial="A"/>, <Value initial="B"/>]}` to `<Value initial="A">{a => <Value initial="B">{b => <div>{[a, b].join()}</div>}</Value>}</Value>`. So the `mapper` influence the VDOM structure. VDOM structure changed, DOM rebuild.

### So, is there any other way to deal with RenderProps Components callback hell?

I thought and came up with this:

```jsx
import React, { PureComponent, Component } from "react";

class Result extends Component {
  render() {
    return this.props.children();
  }
}

export class Compose extends Component {
  constructor(props) {
    super(props);
    this.skip_force = true;
  }
  componentWillUpdate() {
    this.skip_force = true;
  }
  render() {
    const { mapper, children } = this.props;
    const mapper_is_array = Object.prototype.toString.call(mapper) === "[object Array]";
    const arg = mapper_is_array ? [] : {};
    return (
      <React.Fragment>
        {Object.keys(mapper).map(key => {
          const value = mapper[key];
          const with_key = mapper_is_array ? null : { key };
          return (typeof value === "function" ? React.createElement : React.cloneElement)(value, with_key, (...args) => {
            arg[key] = args[0]; // maybe we should just use args rather than args[0]
            if (!this.skip_force) {
              this.forceUpdate();
            }
            return null;
          });
        })}
        <Result>
          {() => {
            this.skip_force = false;
            return children(arg);
          }}
        </Result>
      </React.Fragment>
    );
  }
}
```

It works!

# BUT!!!

1. It relies on the fact that the last Child will render at the last. But the fact is not defined in React SPEC.
2. It relies on `componentWillUpdate` which is deprecated.

Then, is there any other better methods ?

**Comment by gaearon** [comment]
I don't recommend to use this kind of metaprogramming to obscure render prop composition. You're just tucking it away making it even harder to debug and see issues like this. Indeed, the order matters for reconciliation.

We have some longer term ideas about how to reduce the need for nesting for most common cases. We're not ready to share them yet but we'll likely have something within a year. We'll announce them on the [RFC repository](https://github.com/reactjs/rfcs) when they're ready so feel free to watch it!

Cheers.
