### ISSUE TITLE
[Question] Integrate react 15 library in react 14

### ISSUE THREAD

**Issue by nishantsinha-5** [facebook/react#12660]
We have a requirement to integrate one of our app created using react v15.6.2 into an existing app which is still in react v0.14.8.

I need help in understanding below 2 points:
- Risk of integration
- Probable solution if there is an issue due to incompatibility.

We have used rollup to create cjs library of react 15 app.

Thanks

**Comment by gaearon** [comment]
Hard to say in advance. There definitely might be issues (for example with events).

If you bump into issues you can consider putting the inner app in an iframe if you can to isolate it more fully.
