### ISSUE TITLE
React background image overlay opacity

### ISSUE THREAD

**Issue by Aashir1** [facebook/react#12666]
Do not find a way that how to set background image overlay opacity in reactjs, I am trying to do something like that.

**STYLE**

`const styles={
  header:{
    background: 'rgba(0, 0, 0, 0.5)',
    backgroundImage: `url(${background})`,
    height: '100vh',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
  }
}`

**JSX**

```
<div style={styles.header}>
          <div>
            Portfolio
          </div>
</div>
```

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
