### ISSUE TITLE
Skip second argument in React.createElement()

### ISSUE THREAD

**Issue by Superpencil** [facebook/react#12663]
**Do you want to request a *feature* or report a *bug*?**
A feature

**What is the current behavior?**
`React.createElement(component, props, children)`, when `props` aren't needed, you still have to pass `null` or `{}` as a second argument.

**What is the proposal?**
Being allowed to omit the second argument, allowing this:
```es6
import React from 'react'
import Foo from './Foo'
import Bar from './Bar'

const o = React.createElement

const App = () =>
  o('div',
    o('h1', 'Hello'),
    o(Foo),
    'Ok!',
    o('p', 'How are you?'),
    o(Foo,
      o(Bar, { key: 'hi' },
        o('span', 'Heya!')
      )
    )
  )
```

**Demo code?**
I currently, very naively, use this:
```es6
function o () {
  var argumentsArray = Array.from(arguments)
  var x = argumentsArray[1]
  if (typeof x === 'string' || typeof x === 'number' || Array.isArray(x) || (typeof x === 'object' && Object.keys(x)[0] === '$$typeof')) {
    argumentsArray.splice(1, 0, {})
  }
  return React.createElement.apply(this, argumentsArray)
}
```

**Comment by aweary** [comment]
If you'd like to make proposal a breaking API change please open an RFC for this at https://github.com/reactjs/rfcs.
