### ISSUE TITLE
Passing all props from a parent to children looks screwed up

### ISSUE THREAD

**Issue by mvasin** [facebook/react#12678]
**Do you want to request a *feature* or report a *bug*?**
I guess a bug.

**What is the current behavior?**
I want to wrap children in a `div` and pass all the props to children that are now inside that `div`:
```
import React from "react";

// A div that passes its props to its direct children
const Div = props => {
  return (
    <div>
      {React.Children.map(props.children, child =>
        React.cloneElement(child, props)
      )}
    </div>
  )
};

const App = () => (
  <Div prop1="look ma" prop2="no hands">
    <div>div1</div>
    <div>div2</div>
    <div>div3</div>
  </Div>
)

export default App;
```
CodeSandbox: https://codesandbox.io/s/1omj86nlw7

**What is the expected behavior?**
Output should be
```
div1
div2
div3
```

**The actual output**
```
div1
div2
div3
div1
div2
div3
div1
div2
div3
```

For some reason every child contains three extra children.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.3.2, macOS 10.13.4

**Comment by gaearon** [comment]
`React.cloneElement(child, props)` clones the child, but gives it the `props` *which include the children*.
So you end giving all three children to each child.

You probably want something like:

```js
const Div = props => {
  const { children, ...rest } = props;
  return (
    <div>
      {React.Children.map(children, child =>
        React.cloneElement(child, rest)
      )}
    </div>
  )
};
```

or equivalent without rest/read syntax:

```js
const Div = props => {
  let childProps = Object.assign({}, props);
  delete childProps.children;
  return (
    <div>
      {React.Children.map(props.children, child =>
        React.cloneElement(child, childProps)
      )}
    </div>
  )
};
```

**Comment by mvasin** [comment]
And if I explicitly pass a child's children,
```
React.cloneElement(child, Object.assign({}, props, {key: index}), child.props.children)
```
it works as expected. But shouldn't it be a default when `React.cloneElement`'s third argument is omitted?

And if it's not a default, what is a default? The current behavior looks weird.

**Comment by gaearon** [comment]
`cloneElement()` can't guess what you want to by default it literally clones the element (including children). Typically this *is* what people want because `cloneElement()` tends to be used for "tweaking" a prop but otherwise keeping the content the same.

>And if it's not a default, what is a default?

To produce an equivalent element.
