### ISSUE TITLE
"Undefined variable: performance" in react-dom for Opera Mini browsers

### ISSUE THREAD

**Issue by runmoore** [facebook/react#12679]
**Do you want to request a *feature* or report a *bug*?**

_bug_

**What is the current behavior?**

When loading `babel-polyfill` before `react` and `react-dom`, my site breaks with the following error only in the proxy mobile browser Opera Mini when in [extreme turbo](https://www.opera.com/turbo) mode. 

```
ReferenceError: Undefined variable: performance at h (https://<CDN>/16.2.0/react-dom.production.min.js:162)
```

Here's the catch, when `babel-polyfil` is loaded *after* `react` and `react-dom` the page loads as it does in other browsers when JS is switched off. This is the expected behaviour for this browser.

The problem with this issue is that I only have access to the error logs from production via a beacon. I haven't been able to view any console logs  from running in the browser directly, and haven't been able to replicate it in any web editors since those sites just completely don't work in Opera Mini.

I believe the error is referencing code here: https://github.com/facebook/react/blob/1673485720d9ac172fcf1f8628a004a4990bf4f4/packages/react-scheduler/src/ReactScheduler.js#L52

Sorry if this is posted in the wrong place, I'm not 100% sure where I should report this since it's relating to a proxy browser that doesn't run JS on the client. 

**What is the expected behavior?**

When loading `babel-polyfill` before `react` and `react-dom`, the site will render as if it would in any other browser with JS switched off.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm seeing this behaviour only in Opera Mini on Android and iOS when in [extreme turbo](https://www.opera.com/turbo) mode.

**Comment by gaearon** [comment]
This looks like an issue with Opera Mini specifically. As you rightly noted, the only place where we use `performance` is on those lines, and we specifically check that it's an object (and thus definitely not undefined). It could in theory be null but that's not what you're seeing either. So I'm inclined to think this is an Opera Mini specific transformation issue. I don't think there's something we could do to fix here, but let me know if you have suggestions.

**Comment by runmoore** [comment]
Thanks @gaearon, I find it bizarre that the order of loading `babel-polyfill` in this way would have an impact, but it must be how they transform the code from the proxy to the client

**Comment by gaearon** [comment]
Yeah, it looks like their bug.
