### ISSUE TITLE
`TypeError: 'undefined' is not a function (evaluating 'n.startsWith(e)')` & `React` & `AntD`

### ISSUE THREAD

**Issue by xyzdata** [facebook/react#12675]
# `TypeError: 'undefined' is not a function (evaluating 'n.startsWith(e)')` & `React` & `AntD`

report a *bug*?

>  `TypeError: 'undefined' is not a function (evaluating 'n.startsWith(e)')`

**What is the current behavior?**

Safari browser can't run my app, while Chrome browser & FireFox browser both OK.

**What is the expected behavior?**

It should be running in all main modern browsers.

**Comment by xgqfrms-gildata** [comment]
OS: Windows 10pro x64

> Chrome 

![image](https://user-images.githubusercontent.com/29531779/39169706-6e1d7bce-47cb-11e8-8d53-739a05d9693a.png)


> safari

![image](https://user-images.githubusercontent.com/29531779/39169617-1a51615e-47cb-11e8-9d33-e4affde59c22.png)


***

# same like questions

https://stackoverflow.com/questions/37742941/typeerror-object-ie-11-has-no-method-startswith

**Comment by xgqfrms-gildata** [comment]
# polyfill ? 

> `string.prototype.startswith`

**Comment by xgqfrms-gildata** [comment]
# react-router ? bug

https://github.com/ReactTraining/react-router/commit/1be1ed7370651f247e589a8499d360d2b1db3b26

**Comment by theJian** [comment]
The version of the test browser is really old.
Can you polyfill it or upgrade safari to the newest version?

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/39170829-7dfc7370-47cf-11e8-8d07-e47399836e76.png)


![image](https://user-images.githubusercontent.com/29531779/39170965-f32046f4-47cf-11e8-8a4a-8c47cb5bf255.png)

**Comment by xgqfrms-gildata** [comment]
@theJian I'm sorry for that, I haven't a Mac.

I think it is the ES6 `startsWith` bug, should I modify the source code & re-compile it?

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/39171234-b147c2f6-47d0-11e8-8f32-d6b0af361bbe.png)

**Comment by xgqfrms-gildata** [comment]
I had asked one of my colleagues, who has a `mac book`, but it still can't run the app.

,

**Comment by theJian** [comment]
@xgqfrms-gildata It's not a bug of react.
If you need to support old browsers, use a [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill).

**Comment by wZi** [comment]
@xgqfrms-gildata  Hi, 我也遇到跟你一样的问题
我的解决方案是:
1. 在所有js之前 Import 'babel-polyfill';
2.  在webpack.config.js 加入:
```
 app: [
            'babel-polyfill',
            APP_PATH
        ]
```
