### ISSUE TITLE
When unmounting a Fragment node, it's children are removed from the DOM one at a time instead of all at once

### ISSUE THREAD

**Issue by madou** [facebook/react#12683]
**Do you want to request a *feature* or report a *bug*?**

Bug (maybe! - or perhaps it's just a limitation of Fragments - let me know!)

**What is the current behavior?**

When unmounting a Fragment, it's children are removed from the DOM one at time top to bottom.

This means if during the unmounting step if I'm quickly calculating where it is in the DOM, its position can change before I can save that data. I also imagine it's less performant.

Look in your console for the outputs for these.

**1a) Using Fragment - Element can be found:**
https://codesandbox.io/s/k9jl6vo8yv

**1b) Using Fragment - Element can't be found:**
https://codesandbox.io/s/1omjz1m8l

**2a) Using div - Element can be found (expected behaviour for Fragment):**
https://codesandbox.io/s/l34o1kw8m

**2b) Using div - Element can't be found (when switching out parent with children, with parent with no children):**
https://codesandbox.io/s/w02yv3o4zw

**What is the expected behavior?**

1) That both the Fragments children would be removed from the DOM at the same time, instead of one after the other.

2) That both children of the div would be removed from the DOM at the same time when essentially removing the children.

These both look like they're part of the same problem.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.3, unsure if it worked in previous versions.

----

Let me know if I can help with anything :).

Cheers

**Comment by madou** [comment]
Hey Dan,

Yeah I suppose the only way for that would be what, set inner html?..

If the title was instead "when unmounting XYZ node it's children have their
componentWillUnmount and DOM node removal steps called in an unexpected
order" it may work better.

So in both examples the assumption was the series of events (for siblings
being removed from the  DOM) would be this:

componentWillUnmount
componentWillUnmount
node removed
node removed

But in reality it is:

componentWillUnmount
node removed
componentWillUnmount
node removed

Let me know what you think :)

Michael

**Comment by gaearon** [comment]
The order in which siblings are handled is an implementation detail. I suggest not to depend on it in your code.
