### ISSUE TITLE
Show culprit in `Cannot update during an existing state transition...` ?

### ISSUE THREAD

**Issue by mrlubos** [facebook/react#12687]
**Do you want to request a *feature* or report a *bug*?**
*Feature.*

**What is the current behavior?**
We are probably all familiar with the following message.

```
bundle.js:1

Warning: Cannot update during an existing state transition (such as within `render`
or another component's constructor). Render methods should be a pure function
of props and state; constructor side-effects are an anti-pattern, but can be moved
to `componentWillMount`.
```

For those who never came across this message, it can be created simply by mounting the following component.

```js
class UpdateDuringRender extends Component {
  constructor(props) {
    super(props);
    this.state = {
      text: 'initial',
    };
  }

  updateState(text) {
    this.setState({ text });
  }

  render() {
    this.updateState('updated!');

    return (
      <div>
        {this.state.text}
      </div>
    );
  }
}
```

**What is the expected behavior?**
Can we be more specific which component triggers this warning (I think it could be even treated as an optional error)? When this suddenly appears in the app, sometimes it's tough to find the culprit. Some stack trace or at least the offending component would be helpful in the warning message. Not sure how it's solved internally, but yeah, would be a nice hint to help remove anti-patterns.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`"react": "^16.3.1"`

**Comment by gaearon** [comment]
I agree something like this would be nice.

**Comment by lmenus** [comment]
@gaearon What do you think about using `setTimeout(fn, 0);` either directly in `render()` or in `updateState()`? Avoids the need to call `updateState()` from both `componentDidMount()` and `componentDidUpdate()` (equivalent of example above) and I find it easier to reason about if it's called from a single method.

Not sure if it isn't an anti-pattern though in case the component can get unmounted before the function runs, in which case `setState()` would throw an error I believe.

**Comment by asiniy** [comment]
@gaearon I'm picking this out. 

Can't find really `good first issue` so this will be. It's not critical issue and I'm newbie to react open source thus it may take 2 weeks to investigate & finish.

**Comment by asiniy** [comment]
@lmenus it's a 100% anti-pattern. Feel free to use `getDerivedStateFromProps` to achieve this kind of functionality.

**Comment by lmenus** [comment]
Thank you @asiniy!

**Comment by asiniy** [comment]
@lmenus done

**Comment by lmenus** [comment]
@asiniy Amazing, thank you!
