### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by babakness** [facebook/react#12685]
Please document how to use forwardRef (the preferred way) to retrieve a list or array of items. For example,

```javascript
const foo = React.forwardRef( (props,ref) => 
  props.superHeros.map( 
    ( hero, index) => <li ref={  ref  } key={ index }>{ hero }</li>
  ) 
)

```

**Comment by babakness** [comment]
Perhaps the key question here is, why not do this? 

```javascript
componentDidMount(){
  const foo = this.refs.root.querySelector('.foo')
  ...
}
```

Suppose there are 50,000 `className='foo'` elements that are returned by an embedded component. Is this code not portable? Is this code slower than having 50,000 `ref` created?

**Comment by gaearon** [comment]
Could you please file this in https://github.com/reactjs/reactjs.org? That’s the documentation repo.

**Comment by babakness** [comment]
Done
