### ISSUE TITLE
Ref callback is not called before componentDidMount

### ISSUE THREAD

**Issue by notgiorgi** [facebook/react#12697]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
ref callback is not executed before `componentDidMount`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codepen.io/notgiorgi/pen/bMwrKd (react 16.3)
https://codepen.io/notgiorgi/pen/Gdjvpw (react 15.6.1)

**What is the expected behavior?**
ref callback should be executed before `componentDidMount`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.6.1, 16.3.2
Chrome 65
MacOS High Sierra

**Comment by gaearon** [comment]
I edited my answer to explain this.
https://stackoverflow.com/a/50019873/458193
