### ISSUE TITLE
Allow to specify displayName for createContext() providers and consumers

### ISSUE THREAD

**Issue by budarin** [facebook/react#12695]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
in React tree name of a Context must be like its name in code

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
```js
const MyContext = React.createContext(null);
```
```js
   <MyContext.Consumer>
   { data => ... }
   </MyContext.Consumer>
```
let's have a look at React tree in Chrome extention's page

here is Context - not MyContext

**What is the expected behavior?**

expexted to see MyContext

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.3.2

**Comment by gaearon** [comment]
React can't "guess" the name from the declaring code but we should probably make it possible to specify `displayName` manually for React DevTools.

**Comment by budarin** [comment]
Thanks :smiley:

**Comment by kaushik94** [comment]
@gaearon can I take this up?

**Comment by devmonkey22** [comment]
I think this is the paired React DevTools issue (https://github.com/facebook/react-devtools/issues/1008)

**Comment by bvaughn** [comment]
Context providers and consumers [support a custom display in React DevTools](https://github.com/facebook/react-devtools/blob/38fe9782f82fbcb4f6137e5b920147d35ebe1992/backend/attachRendererFiber.js#L362-L387) like so:

```js
const ThemeContext = React.createContext("light");
ThemeContext.displayName = 'ThemeContext';

<ThemeContext.Provider> // "ThemeContext.Provider" in DevTools
<ThemeContext.Consumer> // "ThemeContext.Consumer" in DevTools
```
