### ISSUE TITLE
Wishlist: ability to disable the synthetic event system

### ISSUE THREAD

**Issue by jaredly** [facebook/react#1269]
Would there be huge problems caused by optionally disabling the synthetic event system? I'd like the option to do so in order to get more responsiveness out of underpowered machines.

**Comment by spicyj** [comment]
No plans to do this.

**Comment by tusharmath** [comment]
I am trying to build a side nav that can be dragged in from the left. I listen to the `touchmove` event on the screen and as the thumb slides right I keep calculating `translateX` and push it to the state, which can be then used to render the sidenav. The problem that I have is —

The touchmove event is fired at a very high speed, though I throttle these events using `requestAnimationFrame` while calculating `translateX`, these synthetic events that even though are not being consumed take up valuable `ms` from the frame.

![image](https://cloud.githubusercontent.com/assets/194482/17649381/decd739e-6251-11e6-9835-2572cd247502.png)
