### ISSUE TITLE
Size prop is not attached to the DOM

### ISSUE THREAD

**Issue by airamrguez** [facebook/react#12694]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The size prop can only be a number and I think this should be true for inputs and selects but not necessarily true for the rest of HTML tags or web components.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Sorry, it's a CodePen. This example uses a framework called OnsenUI that internally uses web components. In the OnsenUI framework there is an icon web component that transforms every size prop value into a string which is not attached to the DOM.

I know that the example has more dependencies than React, BUT there is also a simple div (as simple as this `<div size="40px" />`) which is also affected by this issue.

https://codepen.io/airamrguez/pen/bMEgEP

**What is the expected behavior?**

The size prop should be added to the DOM when it is not a number on HTML tags that aren't inputs and selects.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The affected versions are >= 16.3
It works ok in versions <= 16.2
Browsers: All

**Comment by aweary** [comment]
@airamrguez the `size` attribute is an HTML attribute, not something that React provides. According to the HTML spec, `size` is only allowed on `input` and `select` elements

https://html.spec.whatwg.org/#attributes-3:attr-select-size

**Comment by airamrguez** [comment]
@gaearon I don't know why I wrote "rest of HTML tags", my bad 😅. The example you provided works ok, but if I add something that doesn't seems like a valid size then it doesn't work. For example:

Value  |  Works
-------|-------
100      |  Yes
10px    |  No
10e1    |  Yes
-1        |  No

Something changed in 16.3. 

Version 16.3
https://jsfiddle.net/sa30541v/

<img width="853" alt="captura de pantalla 2018-04-26 a las 21 36 43" src="https://user-images.githubusercontent.com/1159448/39327985-0e7b19ee-499a-11e8-9de0-0c48536d04ad.png">

Version 16.2
https://jsfiddle.net/7umnLj0c/2/

<img width="855" alt="captura de pantalla 2018-04-26 a las 21 37 10" src="https://user-images.githubusercontent.com/1159448/39328021-2cc73de2-499a-11e8-9e2b-306cb6364247.png">

@aweary I suppose that it's fine to filter props when not passing the appropriate values when using HTML tags but I suppose that in web components the size attribute can be anything. Am I wrong?

What do you think?

**Comment by gaearon** [comment]
The web component code path shouldn't reject any tags. If it does it's a bug.

**Comment by gaearon** [comment]
The bug is [here](https://github.com/facebook/react/blob/7c3932857195d0cfba2379875b65f1bd1fae39fd/packages/react-dom/src/shared/DOMProperty.js#L160).
Before the `switch` we should add something like

```js
if (isCustomComponentTag) {
  return false;
}
```

Please send a PR :-)

**Comment by airamrguez** [comment]
Ok, I will work on this tomorrow. I'm heading to bed. 🙏🏽Thanks for your quick response.

**Comment by airamrguez** [comment]
Couldn't wait
