### ISSUE TITLE
Conditional Rendering Such as JSX-Control-Statements

### ISSUE THREAD

**Issue by OverseePublic** [facebook/react#12698]
**Do you want to request a *feature* or report a *bug*?**
Neither

Conditional Rendering Components like JSX-Control-Statement
https://github.com/AlexGilleran/jsx-control-statements

We recently ran into some coverage report issues documented here:
https://github.com/istanbuljs/nyc/issues/812

I want to hear an official recommendation from Facebook ReactJS team about conditional rendering like this. According to your documentation, above approach is not recommended, but I do want to confirm.

Thanks.

**Comment by jquense** [comment]
it's generally not recommended as it adds an unnecessary level of indirection over using javascript ternary or if statements directly, but ya'll free to do whatever works for your team.

**Comment by OverseePublic** [comment]
Thanks for the response Jason. The more complex issue was that the coverage tool was not able to cover branches correctly. Please take a look at the report in link above in istanbuljs and officially not recommend jsx-control-statement in react because it's a bug and a lot of future developers might run into this issue once they fully migrate to jsx-control-statements.
@jquense 
Thanks

**Comment by texttechne** [comment]
The coverage report is correct, jsx-control-statements works as expected, only the test code is flawed: see https://github.com/AlexGilleran/jsx-control-statements/issues/75
