### ISSUE TITLE
Type is invalid. You likely forgot to export your component from the file it's defined in

### ISSUE THREAD

**Issue by ZeningQu** [facebook/react#12703]
I posted a [SO question](https://stackoverflow.com/q/50055552/1270459) and created an [issue on the Voyager project](https://github.com/vega/voyager/issues/798) but thought I'd also document it here. 

I'm using components from [Voyager](https://github.com/vega/voyager) which uses React 15. I have the following error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of  DataSelectorBase.

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of  DataSelectorBase.
```

<img width="996" alt="screen shot 2018-04-26 at 11 41 45 pm" src="https://user-images.githubusercontent.com/822034/39348317-78951274-49ab-11e8-9c37-0d5b4fb4bc97.png">

I know in most cases this error implies `import`/`export` problems but I don't think there's anything wrong with how [`LoadData`](https://github.com/vega/voyager/blob/master/src/components/load-data-pane/index.tsx#L37) and [`DataSelector`](https://github.com/vega/voyager/blob/master/src/components/data-selector/index.tsx#L272) are exported in Voyager. I also believe I imported `DataSelector` right:

```
import { LoadData } from 'datavoyager/build/components/load-data-pane/index';
```

The most weird thing is that when I `npm link` to the same version of Voyager locally, I don't get this error, but when I use the released version, the error shows up?!

**Comment by jquense** [comment]
Something may be wrong with the way you are resolving the modules or your bundler config. The error you're getting is straightforward, _something_ tried to create an element with undefined. Maybe the npm version is broken or your local install is wrong as well. I would add a `console.log` in your render, i'm betting you'll see it's also undefined there as well

**Comment by gaearon** [comment]
I'll close because the error is pretty clear: `LoadData` (assuming that's the element that errors) is `undefined`. You can set a debugger without sourcemaps enabled and see why that is. But it is not something we can help you with in React itself.
