### ISSUE TITLE
The `ref.current` point to the wrong dom node

### ISSUE THREAD

**Issue by xu33** [facebook/react#12709]
eg:
`
{this.state.a ? <div ref={this.myRef} className="a"/> : <div className="b"/>}
`
after state.a was set to false,when access this.myRef.current,it's point to the div with the className b.

**Comment by gaearon** [comment]
Can you create a reproducing case please?
There were links to fiddles in the issue template.

In the example you’re giving I don’t see why there would be two nodes at all. React would reuse the same DOM node with this code.
