### ISSUE TITLE
onClick event is not firing after enabling button via ref

### ISSUE THREAD

**Issue by HerrVoennchen** [facebook/react#12704]
**Do you want to request a *feature* or report a *bug*?**
possible Bug, needs investigation

**What is the current behavior?**
When having a button initially rendered disabled and with a event connected and I enable the button via ref then the event does not get fired on click.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I have a codesandbox here https://codesandbox.io/s/l71w795xnq

Hello2 Component has the ref implementation, the Hello Component was based on State (which is working). It was used on behalf of a question on Hashnode regarding this behavior.

**What is the expected behavior?**
onClick event fires after enabling the button

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React Version is 16.3.2 in the sandbox, I do not know which version the questioner had, I'll share this issue with him. It also didn’t work with refs created by callback or string.

**Comment by sivabalan02** [comment]
I was questioner and my react version was 16.2.0

**Comment by cafutor** [comment]
这不是一个bug,virtual dom is not updated，the virtual dom’s property disabled is still true,so you can not fire the event handle that belongs to the virtual dom

**Comment by jquense** [comment]
Mouse events are manually prevented from firing in the SyntheticEvent system for interactive elements like Buttons, based on their props. The example forces react out of sync with the DOM and 
 the internal check ([here](https://github.com/facebook/react/blob/5bd2321ae3dd7d68ac02dee3c3f271e9d0ee8784/packages/events/EventPluginHub.js#L70)) is using the props value, not the DOM one and so the event isn't firing.

Generally we don't really support this sort of interop between setting properties directly on the DOM node as well as via props. You should do one or the other completely. Either control the value via the ref entirely or with state/props.
