### ISSUE TITLE
Update from 15.6.2 to 16 Breaks Web Application

### ISSUE THREAD

**Issue by dbisk** [facebook/react#12714]
The current behavior is that none of my index.js is being rendered. When I use the react-scripts to build the web application in 16.2.0, I get an r.PropTypes is undefined error when I visit the localhost address. I presume this is because PropTypes is deprecated in 15.5 onwards and removed in 16, but I can't for the life of me figure out what is calling this. It's in some weird part of main.########.js after create-react-app builds it. I've tried updating all my other dependencies, but no dice once I update to React 16. The application works fine in 15.6.2.

I'm using NPM and here is my package.json: 

{
  "name": "node-wf",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "create-react-app": "^1.5.2",
    "halogen": "^0.2.0",
    "prop-types": "^15.6.1",
    "react": "^16.3.0",
    "react-bootstrap": "^0.32.1",
    "react-bootstrap-toggle": "^2.3.1",
    "react-contenteditable": "^2.0.7",
    "react-dom": "^16.3.0",
    "react-split-pane": "^0.1.77",
    "react-textarea-autosize": "^6.1.0"
  },
  "devDependencies": {
    "react-scripts": "^1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "proxy": "http://localhost:3001/"
}

I'm also using some CDN scripts for jQuery, Bootstrap 3.3.7, Bootstrap toggle, and plotly. I'm not sure if there is a compatibility issue with those?

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a support question, please check our community support resources:
https://facebook.github.io/react/community/support.html
