### ISSUE TITLE
SyntaxError: Expected the "svgName" prop to be a string, What should I do?

### ISSUE THREAD

**Issue by skyweaver213** [facebook/react#12719]
I assign a string to svgName, is ok.

```js
return (         
            { BENIF.map((v, k) => {
                return (<li key={k}>
                    <svg svgName="webapp/src/assets/svg/local"  width='9' height='17' className="svg-arr-l"/>
                    </li>)
            } )}
```                

But I assign a variable to svgName, is bad.

``` js
  const BENIF = [
            'webapp/src/assets/svg/crown',
            'webapp/src/assets/svg/discount',
            'webapp/src/assets/svg/earth'
           ];
 return (         
            { BENIF.map((v, k) => {
                // svgName={v} "webapp/src/assets/svg/local"  svgName={str}
                let str = v.toString() || ''
                return (<li key={k}>
                    <svg svgName={str}  width='9' height='17' className="svg-arr-l"/>
                    </li>)
            } )}
```
<img width="365" alt="string1" src="https://user-images.githubusercontent.com/5363176/39165279-429ba120-47b6-11e8-8d8b-3b104483e2f5.png">

**Comment by gaearon** [comment]
I’m not sure where this error is coming from, but it’s not coming from React. 

Maybe you have some opinionated linter that is overzealous about enforcing prop types? 

I’ll close this and I hope https://github.com/zeit/next.js/issues/4203 can get reopened because they’re more likely able to help you there.

**Comment by gaearon** [comment]
To clarify why I think it’s not specific to React: it’s a build-time error but React is a library that runs at runtime (sorry for the tautology). So it couldn’t have failed your build.

This looks like either a linter or some custom loader.
