### ISSUE TITLE
setState callback fired with wrong state context when using ReactDOM.unstable_deferredUpdate

### ISSUE THREAD

**Issue by sskyy** [facebook/react#12711]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`setState` callback is not functioning as expected when using `setState` directly and wrapped it in `ReactDOM.unstable_deferredUpdate` at same time. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/Luktwrdm/436/

If you open console, and click the `refresh` button, sometimes you may see the state in callback is smaller than it was before the `setState` was called. We definitely expect it would be bigger than it was.

**What is the expected behavior?**

As said above.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.3.2

**Comment by sskyy** [comment]
Let me elaborate the case. First, I use `setInterval` and `ReactDOM.unstable_deferredUpdates` to ensure there are always enough deferred update in queue.

```javascript
componentDidMount() {
    this.intervalId = setInterval(() => {
      ReactDOM.unstable_deferredUpdates(() => {
        this.setState((prevState) => {
          return { count: prevState.count + 1 }
        })
      })
    }, 8)
  }
```

Then, invoke normal `setState` through a button click callback:

```javascript
refresh = () => {
    console.log(round, this.state.count, this.r)
    this.setState((prevState) => {
      console.log(round, prevState)
      return {
        count: prevState.count + 1
      }
    }, function() {
      console.log(round, this.r, this.state.count)
    })
  }

render() {
    const e = performance.now() + 50;
    while (performance.now() < e) {
      // Artificially long execution time.
    }
    return (
      <div>
        <span ref={(r)=> this.r = r}>{this.state.count}</span>
        <button onClick={this.refresh} >refresh</button>
      </div>
    )
  }
```

As expected, the callback function `refresh` will interrupt the deferred updates and trigger imediately. But the unexpected behavior is that, the state from `this`, and the prevState in `setState` function is not the same.

this.state:

<img width="850" alt="2018-05-07 9 06 00" src="https://user-images.githubusercontent.com/1487672/39704526-308fadb8-523e-11e8-9eb5-fa5d0178bdbc.png">

prevState:
<img width="843" alt="2018-05-07 9 06 52" src="https://user-images.githubusercontent.com/1487672/39704536-38bb807a-523e-11e8-97fb-ceddcaabf49a.png">


I digged into the source code and found that, this is because React update Component instance in `beginWork`, so when it get interrupted by a event callback, the state is still the updated state from `beginWork`. But the update queue will use `baseState` since last work is not commited. 

See [https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberClassComponent.js#L1032](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberClassComponent.js#L1032)

Call stack: beginWork --> updateClassComponent --> updateClassInstance

I think it is a unexpected behavior because devlopers may write code like:

```
if ( this.state.count > xxx ) {
  this.setState((prevState) => {
    ...
  })
}
```

They may get confused if `this.state` is neither same to `prevState` nor the current visible state on screen. So I suggest to only store the computed next state in `begin` work, then attach them to `this` in `commitWork`.

See [https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberCommitWork.js#L770](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberCommitWork.js#L770)

If there is anything else I can do about this issue, please let me know :) @gaearon

**Comment by aweary** [comment]
This issue seems to be fixed on master, probably by https://github.com/facebook/react/pull/12600 

Here's an example running a master build with the correct behavior: http://jsfiddle.net/ayc9ef0q/.
