### ISSUE TITLE
input DX improvement opportunity

### ISSUE THREAD

**Issue by oliviertassinari** [facebook/react#12710]
**Do you want to request a *feature* or report a *bug*?**

A feature

**What is the current behavior?**

No warning is raised in the following snipped:
```jsx
import React from "react";

export default class TextFields extends React.Component {
  state = {
    name: "Before timeout"
  };

  componentDidMount() {
    // emulate loading some data with AJAX
    setTimeout(() => {
      console.log("Updating name after timeout");
      this.setState({
        name: "After timeout"
      });
    }, 100);
  }

  render() {
    return <input id="name" label="Name" defaultValue={this.state.name} />;
  }
}
```

https://codesandbox.io/s/k248z9ro15

**What is the expected behavior?**

I believe we have the opportunity to raise a warning in development. It would inform users they can't update the `defaultValue` property. This problem was raised to my attention in https://github.com/mui-org/material-ui/issues/11150.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3.2

**Comment by jquense** [comment]
I see how this is generally a bug in this case however defaultValue can be updated to some effect, since it's the value used as the fallback in some situations, like a form reset

**Comment by oliviertassinari** [comment]
@jquense Alright, does it mean there is no DX improvement opportunity? Should we close this issue?

**Comment by gaearon** [comment]
Yeah I think we can’t warn without legit false positives.
