### ISSUE TITLE
encoded character in table td tags showing as string incorrectly

### ISSUE THREAD

**Issue by chen0802** [facebook/react#12712]
Encoded characters for example `&pound;`, `&#36;` can not show as £, $ if adding it into `<td>`. These characters are fine if put it into h1 tag for example as long as outside of table.

```js
<tr>
   <th scope="row">1</th>
   <td>USD</td>
   <td>&#36;</td>
   <td>United States Dollar</td>
   <td>9,120.6025</td>
   <td>9120.6025</td>
</tr>
```

**Comment by gaearon** [comment]
Can you provide a fiddle please?

**Comment by chen0802** [comment]
I can show the code as below:

class BitcoinPrice extends Component {

  //Restful API to get Bitcoin price https://api.coindesk.com/v1/bpi/currentprice.json
    constructor(props) {
        super(props);
        this.state = {
          "time": {
            "updated": "Apr 28, 2018 02:46:00 UTC",
            "updatedISO": "2018-04-28T02:46:00+00:00",
            "updateduk": "Apr 28, 2018 at 03:46 BST"
          },
          "disclaimer": "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org",
          "chartName": "Bitcoin",
          "bpi": {
            "USD": {
              "code": "USD",
              "symbol": "&#36;",
              "rate": "9,120.6025",
              "description": "United States Dollar",
              "rate_float": 9120.6025
            },
            "GBP": {
              "code": "GBP",
              "symbol": "&pound;",
              "rate": "6,617.7724",
              "description": "British Pound Sterling",
              "rate_float": 6617.7724
            },
            "EUR": {
              "code": "EUR",
              "symbol": "&euro;",
              "rate": "7,508.8096",
              "description": "Euro",
              "rate_float": 7508.8096
            }
          }
        };
    }
    render() {
        return (
          <div>
          <table className="table table-hover table-responsive">
            <thead className="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Symbol</th>
                <th scope="col">Currency</th>
                <th scope="col">Description</th>
                <th scope="col">Rate</th>
                <th scope="col">Rate Float</th>
              </tr>
            </thead>
            <tbody>
              <Bitcoin data={this.state.bpi} />
            </tbody>
        </table>
        </div>    
        )
    }
}


class Bitcoin extends Component { 

  render() {
    const data = this.props.data;
    return Object.entries(data).map((key, index) => {
      const item = data[key[0]];
      return (
        <tr key={index}>
          <th scope="row">{index+1}</th>
          <td>{item.symbol}</td>
          <td>{item.code}</td>
          <td>{item.description}</td>
          <td>{item.rate}</td>
          <td>{item.rate_float}</td>
        </tr>
      )
    }
    )
  }
}

**Comment by chen0802** [comment]
https://codesandbox.io/s/x78m0414no

**Comment by hamlim** [comment]
I think what you are seeing here is the difference between: `<td>{"&pound;"}</td>` and `<td>&pound;</td>` (note that the first is a string literal within a jsx expression, and the second is regular jsx text) these two things are subtly different.

This also still happens for other html elements like an h1, or a span:
```jsx
<span>{"&pound;"}</span>
// renders the following html
<span>&pound;</span>
```

To get around this, if you have control over the encoded characters, instead of storing them as strings, you can wrap them in a `<React.Fragment>`, or if you don't have control over the characters (i.e. they are coming from an API response) you will need to use `dangerouslySetInnerHTML` like so:

```jsx
<td dangerouslySetInnerHTML={{__html: item.symbol}} />
```
