### ISSUE TITLE
Consuming Context with a HOC: when root component with provider is rendered multiple times, how to identify correct context to consume at child component level

### ISSUE THREAD

**Issue by rtrg** [facebook/react#12720]
I am planning to use react context API for my library which exposes a root component `R.js`.

**RContext.js**
```
export default const RContext = React.createContext({text: 'Hi'});
```

**getRContext.js** (HOC)
```
import RContext from './RContext';

export function getRContext(Comp) =>
     class {
         ...
         render() {
             <RContext .Consumer>
                   (contextValue) => <Comp  text={contextValue.text} />
             </RContext .Consumer>
         }
     }
````

**R.js**
```
import RContext from './RContext';

export default class R {
    ...
    render() {
        <RContext.Provider value={{text: this.props.text}}>
             <C {...this.props}/>
        </RContext.Provider>
    }
}
```

**C.js**
```
import getRContext from './getRContext';
class C {
    ...
    render() {
        <div>
             {this.props.text}
        </div>
    }
}
export default getRContext(C);
```

**The problem is, in a single app, multiple Root components(`R.js`) can be rendered, since only single context is being used, both will consume same value**

**App.js**
```
import R from './R';
class App {
    ...
    render() {
        <R text={'Welcome'}/>
         .....
        <R text={'End'}/>
    }
}
```

**I can create multiple contexts like below, but it requires passing some identifier from root component to all children, so that corresponding identifier can be used to consume correct context**

**RContext.js**
```
const idToContext = {};
export default getContext(id) {
      if(idToContext.id) {return idToContext.id}
      idToContext.id = React.createContext({text: 'Hi'});
}
```

**getRContext.js**
```
import Context from './RContext';

export function getRContext(Comp) =>
     class {
         ...
         render() {
              const RContext = Context(this.props.id);
             <RContext .Consumer>
                   (contextValue) => <Comp  text={contextValue.text} />
             </RContext .Consumer>
         }
     }
````

Questions:
1) Is there a way to pass certain props(can assume these props won't effect life cycle, in this case id for example) to all children(not only immediate)?

2) Should I create a idContext HOC and wrap all components to consume id and then consume RContext based on id?

3) Please suggest any other better approaches if possible, Thanks in advance!

**Comment by nmain** [comment]
> The problem is, in a single app, multiple Root components(R.js) can be rendered, since only single context is being used, both will consume same value

But this isn't true.  Multiple instances of the same context are supported in the same react tree.  Each `Consumer` will use the value provided by the closest parent `Provider`.

Putting your example in jsfiddle does in fact work; both text values are displayed correctly.

https://jsfiddle.net/jj42dgnc/

**Comment by rtrg** [comment]
I passed same object to both root components while testing which led me believe this, silly me. Apologies for not bothering to write a fiddle to test it out, thanks for your time!

**Comment by damianobarbati** [comment]
@nmain I found your fiddle casually and it looks like gold to me! 

Could you help me solve this problem I have? https://jsfiddle.net/d1h5s8v0/

I have a `<Form />` component which yields a private context. 
Every `<Input />` nested at any level inside a `<Form />` must be able to access/render the context.
Other components outside `<Form />` children tree must be able to access/render the context.

How can I have a reference to the dynamically created context in `<Form />` in fiddle's `<Aware />` component?
