### ISSUE TITLE
When React JS version 15.x is going to be deprecated ? Can any one please enlight the steps to migration from 15.x to 16.x version ?

### ISSUE THREAD

**Issue by jgmobiquity** [facebook/react#12739]
When React JS version 15.x is going to be deprecated ? Can any one please enlight the steps to migration from 15.x to 16.x version ?

**Comment by gaearon** [comment]
A version can’t be “deprecated”, this doesn’t mean anything. We tend to work on only one major version at a time, so new features are only developed for React 16 right now. Technically nothing prevents you from using React 15 for as long as you need to, although with time you might find it more difficult to find other packages that are compatible with it unless you also use older versions of them.

We always post migration instructions **on our blog**. React 16 is no exception.

https://reactjs.org/blog/2017/09/26/react-v16.0.html#upgrading

The React 15.5 blog post includes more information about preparing to those changes: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html

It also includes links to automated scripts (“codemods”) that do the migration for you. 

Hope it helps.
