### ISSUE TITLE
Context API bitmask related questions

### ISSUE THREAD

**Issue by simon998yang** [facebook/react#12732]
I'm playing with Context API bitmask feature to bail out unwanted re-render.

I have a dynamic model ( a JSON object) as context value. By dynamic i meant , the number of keys and structure of the JSON object is unknown. But when the JSON object changed , i know which key is changed. It seems difficult to turn the unknown keys to static pre-defined bitmasks. But I thought such use case is very common, and the bail-out feature should handle it easily by just matching the key. 

Also I notice default changedBits and observedBits is MAX_SIGNED_31_BIT_INT. Does this mean it has a limitation up to 31 type of context change?

**Comment by gaearon** [comment]
The bailout feature is intended for advanced libraries like Relay so it's not very user-friendly (a compromise necessary to make it really fast). Indeed, you're limited to up to 31 type of context change. Nothing prevents you from using one bit for several fields when you have too many.

**Comment by simon998yang** [comment]
Thanks for the prompt response. Maybe same concept like selector function in redux mapStateToProps could be introduced here? i.e the Context.Consumer accept a selector function (Memoized as well) to select the concerned part from context?

**Comment by gaearon** [comment]
We're intentionally not using something like this for consumers because that means arbitrary code would run during traversal. Which inevitably will end up being too slow. The cool thing about the bitmask API is that no user code runs per consumer at all, which is what keeps traversal fast.

You can do regular memoization with other strategies like `shouldComponentUpdate`. And you can build some system based on selectors on top, e.g. https://github.com/aweary/react-copy-write/pull/9, although you'd need to carefully benchmark this to ensure you're not making it slower.

**Comment by simon998yang** [comment]
wow, I did not expect a instant reply! :), 

I got the point, no arbitrary code during traversal, though not fully convinced. shouldComponentUpdate is arbitrary code as well, and is on critical traversal path as well. Still think put this selector function at same level as unstable_observedBits is better.  For example, if I use shouldComponentUpdate in my component
to bail-out re-render , with react-dev-tool highlight updates. I see all the consumer still flashing.., but if I use unstable_observedBits to bailout, then very clean, only the concern component is flashing...

I will check aweary/react-copy-write#9 once i got some more time. 
cheers!

**Comment by simon998yang** [comment]
I had a look at  aweary/react-copy-write#9, feeling that the bailout feature 'unstable_observedBits' offers is so essential to the context API, and the use case is kind of universal. should not let people 'try so hard go so far' to use it :). 

hope you can give it a second thought! make the context API support selector function natively.

**Comment by drcmda** [comment]
> I got the point, no arbitrary code during traversal, though not fully convinced. shouldComponentUpdate is arbitrary code as well, and is on critical traversal path as well

@gaearon I agree 100% with the above. Using context as a global state container without a selector is not feasible, everything will render on any change, and using it just for small values and atomics is waste of potential. 

And why would a selector make things slower? If it's not present React can go about its usual route, but if it is present it *should* select, just like PureComponent does.

```jsx
<Consumer select={state => ({ user: state.users[this.props.userId] })}>
  {({ user }) => ... }
</Consumer>
```

**Comment by TrySound** [comment]
@drcmda What is the difference with this?
```js
class User extends React.PureComponent {
  render() {}
}

<Consumer>
  {({ state }) => <User {...state.users[this.props.userId]} /> }
</Consumer>
```

**Comment by drcmda** [comment]
The difference is that the consumer will trigger on any change to the provider. Say it has a value in it "searchFilter", every time you press a key in the input field tied to it: all users render, and their subtrees, and every other element that's tied to the provider, and subtrees again. In a real application this wouldn't scale. In redux this is why we have mapStateToProps, so connected components only render when their slice of state changes.

**Comment by drcmda** [comment]
It still would trigger lots of overhead, since it has to go through additional component phases now.

**Comment by gaearon** [comment]
If you want to run selectors then the model above (consumer + sCU in a component) is the right one.

Bimask is a lower level API for extreme use cases like Relay.
