### ISSUE TITLE
Why are the Consumer and Provider properties of Consumer?

### ISSUE THREAD

**Issue by ackvf** [facebook/react#12733]
Is there a higher meaning for 1) `Consumer` and `Provider` both being properties of `Consumer`?
2) And `Consumer` being of type `Symbol(react.context)` _(and not react.consumer)_ while `Provider` is of type `Symbol(react.provider)`?

```jsx
const MyContext = React.createContext('value')
MyContext === MyContext.Consumer === MyContext.Consumer.Consumer
```

While this _**IS**_ **convenient**, because I usually only use Provider once as
```jsx
import MyContext from './MyContext'

<MyContext.Provider>
  ...
</MyContext.Provider>
```
... and then I can do less typing by simply using, 
```jsx
import MyContext from './MyContext'

<MyContext>
  ...
</MyContext>
```

I would be interested in knowing where _(if)_ this is documented and what is the preferred way? Whether to use the full `<MyContext.Consumer>` or if it is legit to just simplify to `<MyContext>`.

**Comment by nmain** [comment]
The official (?) flow types don't support this usage
https://github.com/facebook/flow/commit/dd27ebbd14782cc103632e5459e106559d8b5511

**Comment by gaearon** [comment]
Andrew says the motivation was to reduce allocation, but it's not intended to be a public API per se so I wouldn't rely on this.
