### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `someProp`

### ISSUE THREAD

**Issue by jpggvilaca** [facebook/react#12741]
**Do you want to request a *feature* or report a *bug*?**
Report

**What is the current behavior?**
When I pass a boolean prop, say:

```<SomeComponent enable />``` I get this warning for the `enable` prop, this wasn't happening in React 15.x. Do I need to use prop="true" or prop={true} ? why?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Not getting this warning

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.3.2 | Google Chrome

**Comment by gaearon** [comment]
You’ll only get this warning if `SomeComponent` itself passes all its props (including the boolean one) to the DOM element like a `div`. Fix it to stop passing the props that aren’t real DOM props, and the problem will be solved. It’s hard to say more without a running code example.

**Comment by jpggvilaca** [comment]
That's exactly what's happening. I was passing ```{...this.props}```  to a DOM element to make it as flexible as possible. Problem solved. Thanks!
