### ISSUE TITLE
Render children at most once through the use of Singletons

### ISSUE THREAD

**Issue by dkrutsko** [facebook/react#12744]
## Proposed Feature

`React.createSingleton`

Returns a unique React component which could be used anywhere but its children would only get rendered a single time for every location the returned Singleton is used. Very useful for declaring SVG filters but can be combined with anything else including [Portals](https://reactjs.org/docs/portals.html), [Fragments](https://reactjs.org/docs/fragments.html) and so on.

## Use Case
We have a Ripple component similar to [Material-UI](https://www.webcomponents.org/element/PolymerElements/paper-ripple) which could get applied to anything including a `div` and a `button`. Our Ripple effect makes use of an SVG filter for a [gooey effect](https://css-tricks.com/gooey-effect). It's easy for us to bake the SVG into the Ripple component but we only need the SVG rendered once, anywhere in the DOM.

We make use of the Singleton component to handle rendering this SVG once and when the component rendering the SVG gets destroyed, the responsibility falls upon the next component in the list, if any.

## Example
```jsx
const FilterSingleton = React.createSingleton();

const FancyEffect = () =>
{
	return (
		<div>
			<FilterSingleton>
				<svg className='svg-defs' xmlns='http://www.w3.org/2000/svg'>
					<defs><filter id='can-be-used-anywhere'></filter></defs>
				</svg>
			</FilterSingleton>

			<SomeComponent ... />
			<SomeComponent ... />
			<SomeComponent ... />
		</div>
	);
};

// Used all throughout your application but SVG is only rendered at most once on the DOM
<FancyEffect />
<FancyEffect />
<FancyEffect />
```

## Implementation
```jsx
React.createSingleton = function()
{
	const instances = [ ];

	return class Singleton extends PureComponent
	{
		constructor (props) {
			super (props);
			instances.push (this);
		}

		componentWillUnmount() {
			const index = instances.indexOf (this);

			if (index > -1) {
				instances.splice (index, 1);
			}

			if (instances[0]) {
				instances[0].forceUpdate();
			}
		}

		render() {
			return instances[0] === this ? this.props.children : null;
		}
	};
};
```

**Comment by aweary** [comment]
Hey @dkrutsko. If you'd like to propose a new API for React you should do so via the RFC process, which you can find here: https://github.com/reactjs/rfcs

Thanks!
