### ISSUE TITLE
ComponentDidCatch is not working properly React js16.2.0

### ISSUE THREAD

**Issue by opteamix-ppalanisamy** [facebook/react#12740]
I'm using componentDidCatch method to catch errors in my child component and show error msg instead of broken UI. The below is sample code(Can't share client code base. So created the sample code)

I can see the error UI for a second. After a second the UI is breaking and giving below error.

×
Error: I crashed!
Child.render
C:/Users/139376/Documents/workspace/ngen/lods/dev_1.0.0/externals/ngen-crm-webapp/framework/src/Child.js:21
18 | render() {
19 | if (this.state.counter === 2) {
20 | // Simulate a JS error

21 | throw new Error('I crashed!');
22 | }
23 | return

{this.state.counter}
;
24 | }
package.json file as below.
"dependencies": {
"react": "^16.2.0",
"react-dom": "^16.2.0",
"react-router": "^4.2.0",
"react-router-dom": "^4.2.2",
"react-scripts": "1.1.1"
},

import React, { Component } from 'react';
import ErrorBoundary from './ErrorBoundary'
import Child from './Child'

class App extends Component {

constructor(props) {
super(props)
this.state = {
}
}

// All child components should go inside ErrorBoundary.
render() {
return (

These counter are inside the same error boundary. If crashes, the error boundary will replace both of them.

);
}
}
export default App;

import React,{ Component } from 'react';

class Child extends Component {

constructor(props) {
super(props);
this.state = { counter: 0 };
this.handleClick = this.handleClick.bind(this);
}

handleClick() {
this.setState(({counter}) => ({
counter: counter + 1
}));
}

render() {
if (this.state.counter === 2) {
// Simulate a JS error
throw new Error('I crashed!');
}
return

{this.state.counter}
;
}
}
export default Child;

import React, { Component } from 'react';

class ErrorBoundary extends Component {

constructor(props) {
super(props);
this.state = { error: null, errorInfo: null };
}

componentDidCatch(error, errorInfo) {
// Catch errors in any components below and re-render with error message
this.setState({
error: error,
errorInfo: errorInfo
})
// You can also log error messages to an error reporting service here
}

render() {
if (this.state.errorInfo) {
// Error path
return (

Something went wrong.

<details style={{ whiteSpace: 'pre-wrap' }}>
{this.state.error && this.state.error.toString()}

{this.state.errorInfo.componentStack}

);
}
// Normally, just render children
return this.props.children;
}
}

export default ErrorBoundary;

**Comment by nmain** [comment]
Are you using `create-react-app` or similar?  See https://github.com/facebook/create-react-app/issues/3627

**Comment by opteamix-ppalanisamy** [comment]
Thanks for pointing out. I hope in Production the ErrorBoundary UI will not show and hide. Only in development mode the ErrorBoundary UI will have show and hide problem.  I'm seeing this problem in development mode, I have not deployed it in production yet.
Is my understanding correct?

**Comment by gaearon** [comment]
The screen you’re seeing explicitly says at the bottom that it won’t appear in production.

We do show it intentionally. We want to make it hard to accidentally ignore errors because an error boundary that caught them didn’t display them properly, or is off-screen.

**Comment by tahv0** [comment]
> The screen you’re seeing explicitly says at the bottom that it won’t appear in production.
> 
> We do show it intentionally. We want to make it hard to accidentally ignore errors because an error boundary that caught them didn’t display them properly, or is off-screen.

Huh! I used big amount of time to debug this. I just didn't see that small text at the bottom of error screen.
