### ISSUE TITLE
Typos in React.PureComponent very hard to debug

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react#12759]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If you have a typo in a `React.PureComponent`you get a very unhelpful error message that doesn't give any idea where the error is occurring.

E.g.

```
class MyReact extends React.PuteComponent
```

Will generate this error:

<img width="817" alt="screen shot 2018-05-07 at 15 57 24" src="https://user-images.githubusercontent.com/384959/39719507-c502ccca-520f-11e8-96ff-2cdc6991f11f.png">

Normally you would notice right away but if for some reason this typo occurs and you don't see the immediate render result, good luck in finding it. Took me hours.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

I would expect an error message that identifies the location of the syntax error.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.3
Chrome
Mac Os

**Comment by gaearon** [comment]
This must be something related to your bundler setup.
I just tried this in a project generated by Create React App, and it points me exactly to where the error happens:

<img width="1341" alt="screen shot 2018-05-07 at 8 07 18 pm" src="https://user-images.githubusercontent.com/810438/39719831-52da11c6-5232-11e8-8804-29bafe4a4260.png">
<img width="396" alt="screen shot 2018-05-07 at 8 08 04 pm" src="https://user-images.githubusercontent.com/810438/39719852-6321981a-5232-11e8-9239-1c1445bb9df5.png">

Same in the console:

<img width="744" alt="screen shot 2018-05-07 at 8 07 55 pm" src="https://user-images.githubusercontent.com/810438/39719851-62f1704a-5232-11e8-9df5-587101748594.png">


This error isn’t even coming from React. It’s coming from Babel class definition.

I’m not sure what specifically causes the JS stack to get lost or confused with your bundler configuration, but I don’t think this is something that needs to be solved in React.

**Comment by mschipperheyn** [comment]
Ok, thanks
