### ISSUE TITLE
In Development, log to console the object triggering error/warning

### ISSUE THREAD

**Issue by TimNZ** [facebook/react#12750]
**Feature Request**

It is often time consuming to determine what deeply nested component triggered a warning/error.

How about logging the at issue object/function to console as well?

That way I can at least look at 'name' or 'id' or whatever props help identify.

It's development mode, as much info as possible is wanted.

<img width="633" alt="screen shot 2018-05-06 at 1 52 34 pm" src="https://user-images.githubusercontent.com/1051701/39669062-233ad638-5135-11e8-983c-d3f9884070f2.png">

**Comment by gaearon** [comment]
You'll get filename and even a line number if you include [this Babel plugin](https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source) in development. For example, it's on by default (only in development!) in [Create React App](https://github.com/facebook/create-react-app),  our recommended starter kit.

**Comment by TimNZ** [comment]
Thanks @gaearon.

Now I known __source is a thing in React I can follow the discussions and contribute to improve.

Great work.
