### ISSUE TITLE
Open the react application with your phone browser， show error

### ISSUE THREAD

**Issue by TonyGGC** [facebook/react#12758]
**Current Behavior：
Open the react application with your phone browser， show error：**

Warning: Failed prop type: Invalid prop `children` supplied to `Switch`, expected a ReactNode.
    in Switch
Warning: Failed prop type: Invalid prop `children` supplied to `HashRouter`, expected a ReactNode.
    in HashRouter
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Provider`, expected a single ReactElement.
    in Provider

my Environment：
    "react": "^16.3.2",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "redux": "^4.0.0",

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by TonyGGC** [comment]
@gaearon  I cannot find any info in your  community support resources

**Comment by gaearon** [comment]
Which ones have you tried?

**Comment by gaearon** [comment]
The folks on Discord chat are friendly and should be able to help you.

**Comment by TonyGGC** [comment]
I have search the 'Switch', 'HashRouter' and 'Provider' in the community support resources, did not find resources related to my problem.
