### ISSUE TITLE
ReactTestUtils.Simulate regression in React 16

### ISSUE THREAD

**Issue by mjackson** [facebook/react#12772]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The TestUtils' `Simulate` module in React 16 doesn't immediately flush updates to the DOM like it used to in version 15 and previous.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I made a gist with 2 ready-to-go HTML files: https://gist.github.com/mjackson/9318e71a912633c9ec97d23f3189d3d4

Just open either one in a browser.

**What is the expected behavior?**

When behavior is triggered via the `Simulate` module, state should be flushed to the DOM immediately so assertions may be made on the next line.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16 is affected by this issue. Yes, this used to work. In version 15.6.2 (and previous) you could `Simulate.click` and then immediately assert on the next line that changes had been flushed to the DOM.

I searched through the React tests for some test that was actually making this style of assertion (that updates were actually being flushed to the DOM) but couldn't find anything.

**Comment by bvaughn** [comment]
> The TestUtils' Simulate module in React 16 doesn't immediately flush updates to the DOM like it used to in version 15 and previous.

I think a more accurate description is that it does not immediately flush _if called when React is in the process of rendering_. If you wrap a `setTimeout` around your `16-3-2.html` example, it works.

**Comment by mjackson** [comment]
Oh, interesting. Thanks for taking a look, @bvaughn 😅 

In that case, it looks like this may just be a difference in *when* the 3rd argument to `ReactDOM.render` is called. I've always interpreted it like a `componentDidMount`, but it looks like it has a slightly different meaning in 16.

**Comment by gaearon** [comment]
Even if it was exactly like `componentDidMount` (I'm not sure whether it is), it wouldn't be flushed immediately. React 16 rendering is not "re-entrant". This means that if you're inside a lifecycle, there's nothing you can do to make React start rendering components. React will only do so after calling all lifecycles (if there were extra updates scheduled). This helped fix a bunch of obscure bugs and is pretty much a hard constraint for Fiber implementation but can be inconvenient in such corner cases.

**Comment by gaearon** [comment]
I'd say this works as expected. Related [breaking change](https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes) says

>ReactDOM.render and ReactDOM.unstable_renderSubtreeIntoContainer now return null if called from inside a lifecycle method. To work around this, you can use portals or refs.

Happy to accept a PR rewording this to be a bit more general (re-rendering only happens after all lifecycles have fired now).

**Comment by bvaughn** [comment]
I think the biggest takeaway from this is that the change log note is a bit too ambiguous / non-obvious when it comes to things like `Simulate`.

**Comment by mjackson** [comment]
The main reason I am using the `ReactDOM.render` callback is to ensure that the node is in the DOM before running tests on it. Are you saying it's safe to assume that `ReactDOM.render` is sync (when it's not called from within a lifecycle method)?

**Comment by mjackson** [comment]
Thanks for clarifying, @gaearon. I had to re-read what you said a few times, but I think I've got it now.

Basically, when I call `Simulate.click` inside the `ReactDOM.render` callback, it won't work the same way as when I do  it *outside* of that callback because no rerendering happens until all lifecycles have finished. I always liked the fact that `Simulate` was able to force a component to rerender, but I understand that it's a hard constraint in Fiber. It just makes `Simulate` a little less useful now.

I wonder if `Simulate` could take a callback, like `setState` does?

**Comment by bvaughn** [comment]
Could you elaborate on why you'd need this?

Are you specifically testing a click even after an initial _async_ render? If not, you can just move the call to `Simulate` to the next line below the call to render like I mentioned [above](https://github.com/facebook/react/issues/12772#issuecomment-388095743).

I assume I'm overlooking something. 😄

**Comment by mjackson** [comment]
I guess the only time it'd be useful is when you're using `Simulate` inside one of the lifecycles, which is already something that's not really supported.

Maybe a better approach would be to warn (or throw?) when using `Simulate` inside a lifecycle? Because it's not going to do what you'd expect.

**Comment by gaearon** [comment]
Since simulate is a test-only API I'd be confused why you'd call it in a lifecycle. I wouldn't expect test-only code to exist *inside tested components*. And using Simulate in actual app logic is not really supported either.
