### ISSUE TITLE
video tag having issues playing the video continuously 

### ISSUE THREAD

**Issue by dholakiyaankit** [facebook/react#12773]
**Do you want to request a *feature* or report a *bug*?**
No
**What is the current behavior?**

I am running drag and drop control and you can setup the property of the particular control
So, the structure looks something like this

**left side**                                      
   Controls          
**center**     
draggable area          
**right side**
properties of the control

So, in the controls I am having one video tag and then i am dragging into the draggable area, So everything works fine till now.

Once I have the video control inside the draggable area I have one checkbox in the properties area named `autoplay` once I check it the video plays automatically.

here is my code,

```
return <span key={this.props.uniqueId} style={{ outlineStyle: 'none' }}
		onClick={() => this.props.changeActiveElement(this.props.uniqueId, this.props.stylesToApply)}
		   onDoubleClick={this.props.OpenDefaultEvent}
		dangerouslySetInnerHTML={{ __html: this.props.htmlToAdd }}

		></span>
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
It should not rerender the whole video it should only change the property. Once I have the property changed it rerenders the whole video and starts again. If I use any third party html parser then video doesn't restart but it is not playing too.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.3.1
Chrome latest version

**Comment by poxrud** [comment]
I think you might need to provide a simplified working example on JSFiddle/codesandbox. 

> Once I have the property changed it rerenders the whole video and starts again

A component will rerender on a props or state change. You can prevent it from doing so with [shouldComponentUpdate](https://reactjs.org/docs/react-component.html#shouldcomponentupdate) lifecycle method.  

Without seeing the code... perhaps a possible solution is to store the current playback position in state and move to it on an update.

**Comment by dholakiyaankit** [comment]
@poxrud thanks for the reply, Actually I can't store the current position in state, as you can see my code has the html which is being fetched from the API, this happens when I use the `dangerouslySetInnerHTML`
If I use pure JSX with that any propery change working fine and video plays from where it stopped. any suggestions to have the react reconciliation working as working with the JSX?

**Comment by aweary** [comment]
Using `dangerouslySetInnerHTML` means you want to render markup that React won't control (which is what makes it dangerous). React cannot do any sort of reconciliation on the markup you pass in, so if the component using `dangerouslySetInnerHTML` re-renders, the markup will be re-rendered from scratch as well.

You'll need to avoid using `dangerouslySetInnerHTML` if you want to dynamically manage the state of your elements, or make sure the markup being passed in as `__html` is dynamically updated.

Lastly, we use the issue tracker for bug reports and feature requests. If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by dholakiyaankit** [comment]
Thanks, Can you please give me some sort of example to set this? **make sure the markup being passed in as __html is dynamically updated.**

**Comment by aweary** [comment]
If the markup is something you control, and something that you can dynamically update (e.g., if it was coming from another service that you control) then you could update it when the component updates.

If it's markup that you can't control (user provided) then this won't be possible.
