### ISSUE TITLE
The strange lifecycle of  forwardRef children

### ISSUE THREAD

**Issue by xiaoshuangLi** [facebook/react#12781]
**Do you want to request a feature or report a bug?**

bug

**Demo code**

```jsx
import React, { Component, forwardRef } from 'react';

class Inp extends Component {
  state = { value: '' }

  static getDerivedStateFromProps(nextProps, prevState) {
    console.log('3 --- receive props');
    return {
      value: nextProps.value,
    };
  }

  onChange = (e) => {
    console.log('1 --- onChange');
    this.setState({
      value: e.target.value,
    }, () => {
      console.log('2 --- after setState');
    });
  }

  render() {
    const { value, onChange, ...others } = this.props;

    return (
      <input type="text" value={this.state.value} onChange={this.onChange} {...others} />
    );
  }
}


const InpWithRef = forwardRef((props, ref) => (
  <Inp ref={ref} {...props} />
));


class Test extends Component {
  render() {
    return (
      <InpWithRef />
    );
  }
}

```

**What is the current behavior?**

When I type something in the ```Input```, will trigger ```onChange``` => ```setState``` => ```getDerivedStateFromProps``` => ```the callback of setState```.You can see it in the console.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Here is a [demo](https://codepen.io/xiaoshuang/pen/OZZLVG?editors=0010).

**What is the expected behavior?**

The expected behavior: ```onChange``` => ```setState``` => ```the callback of setState``` => ```getDerivedStateFromProps```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
react: 16.3.2,
reacr-dom: 16.3.1,
```

**Comment by gaearon** [comment]
It’s fixed on master.
