### ISSUE TITLE
When I try to remove deprecation warning from React 15.6.x, am getting error TypeError: Serializing native function: bound onceWrapper 

### ISSUE THREAD

**Issue by Jitendrasinh-Gohil** [facebook/react#12799]
When I try to remove Warning( Accessing createClass via the main React package is deprecated) from my app with version React 15.6.x and as per https://fb.me/react-create-class steps. 
I have included 'create-react-class' as npm package in my React app and made according changes in my React component, but it is giving me below mentioned serialize TypeError : 

**error TypeError: Serializing native function: bound onceWrapper
    at ../node_modules/serialize-javascript/index.js:114:19
    at String.replace (<anonymous>)
    at serialize (/Users/jgohil/Mobi-projects/ortus-web/node_modules/serialize-javascript/index.js:101:16)**
<img width="1315" alt="screen shot 2018-05-14 at 17 35 01" src="https://user-images.githubusercontent.com/16350637/39996447-2731fda2-579d-11e8-8b2e-7c73573055fe.png">

Can you please help me out what is missing in my code or what is going wrong ?

Below is my component code as per new 'create-react-class'  guidelines as after I changed : 

My component : Html.js 

```
import React, { PropTypes } from 'react';
import Component from 'create-react-class';
import ReactDOM from 'react-dom/server';
import serialize from 'serialize-javascript';
import Helmet from 'react-helmet';;

var Html = Component({
  propTypes : {
    ....
  },

  render() {
    const { bundle } = this.props;
    const content = component ? ReactDOM.renderToString(component) : '';
    const head = Helmet.rewind();

    return (
      <html lang="nl">
        <head> 
                  ....
        </head>
        <body>
          <div id="content" dangerouslySetInnerHTML={{ __html: content }} />
          <script dangerouslySetInnerHTML={{__html: `window.__data=${ serialize(store.getState()) };`}} charSet="UTF-8"/>
          <script async type="text/javascript" src={ `${bundle}` } charSet="UTF-8" />
          
        </body>
      </html>
    )
  }
 });

export default Html;
```

I want to remove  these deprecation warnings from my app(React 15.6.x) without upgrading to React 16.x.  Can you please help me in removing these errors ?

**Comment by gaearon** [comment]
There's no issue with React itself here.

The error message is coming from a library called `serialize-javascript` that you're passing `store.getState()` to. The library complains that something inside your store is a JavaScript function called `onceWrapper`. It's definitely *not* defined in `createReactClass()` so the mistake must be somewhere else. You can probably put some logs in `serialize-javascript` code to see how it "reaches" that function and why it's in your store state.

That's about as much as we can help you with. If you can't debug it yourself I encourage you to share your full project and reach out to support resources: https://reactjs.org/community/support.html
