### ISSUE TITLE
Deep-extend sequrity

### ISSUE THREAD

**Issue by isopen** [facebook/react#12794]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
See here:
https://github.com/webpack/webpack/issues/7285
The problem turns into mass. At the moment, this problem can be said in all projects of the world.
The fact is that these packages are at the kernel level. I think you need to fix and check the packages before publishing. Because it turns out that you are the core that converts packets into one single entity called React. I can not develop further...I can not study React! I like React!

**What is the expected behavior?**
There should not be such. Fearfully.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React latest
Windows 10

**Comment by aweary** [comment]
The issue you reported in the Webpack repo is related to react-scripts, a package thats used by create-react-app. Somebody already reported the issue here: https://github.com/facebook/create-react-app/issues/4446

This repo is used only for bug reports and feature requests for React itself.

**Comment by aweary** [comment]
I'm sorry to hear that, React does take security very seriously. We use it extensively at Facebook and have a vested interest in making sure it's secure.

The issue you reported doesn't affect React directly in any way. It's an issue with an indirect dependency of `react-scripts`, which is part of `create-react-app`. It's a low severity issue according to the report as well. I'm sure it will get resolved in a reasonable timeframe for it severity.

**Comment by isopen** [comment]
I'm also interested in making this world better. Making the world React is better and safer because at the very beginning of my practice, I promoted the idea of ​​a jet house. At that time, I was taken hostile. You succeeded! I am delighted!
