### ISSUE TITLE
Despite  followed React components creation standards with ES6 style class, it gives deprecation warning

### ISSUE THREAD

**Issue by Jitendrasinh-Gohil** [facebook/react#12819]
I am using React ver 15.6.x and  have created my React JS components using ES6 style class patterns and I am not using 'React.createClass' anywhere in my app.  Still on my client side node server, I am getting deprecation warning like shown as below screen-shot : 
<img width="1410" alt="screen shot 2018-05-15 at 18 24 44" src="https://user-images.githubusercontent.com/16350637/40057941-4dcb404c-586d-11e8-91a4-f2e8a3689051.png">

Below is my React component code as per ES6 class style, DO I NEED to worry about this warning, or what should I do because I have created my React component as per standard guideline mentioned on this link https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass : 

```
import React, { Component } from 'react';

class App extends Component {
  static contextTypes = {
        .....
  };
  static propTypes = {
        .....
  };
  render() {
    return (
      <div>
               ....
      </div>
    );
  }
  componentDidMount(){
    const { params, location, actions } = this.props;
  }
}
export default App;
```
Can you please guide me what should I do to remove these warnings ? I don't want use 'create-react-class' which is drop-in-replacement. I want to stick to the pattern of ES6 class in my existing React ver 15.6.2 without upgrading to React 16. So Can you please enlight some approaches I should follow on this ?

**Comment by gaearon** [comment]
The warning should have a stack trace that will point you to where `createClass` is being called.

If your console doesn't show stack traces for warnings, you can open [the React source code in your `node_modules`](https://unpkg.com/react@15.6.2/lib/React.js) and comment out this part:

```js
    Object.defineProperty(React, 'createClass', {
      get: function () {
        lowPriorityWarning(warnedForCreateClass, 'Accessing createClass via the main React package is deprecated,' + ' and will be removed in React v16.0.' + " Use a plain JavaScript class instead. If you're not yet " + 'ready to migrate, create-react-class v15.* is available ' + 'on npm as a temporary, drop-in replacement. ' + 'For more info see https://fb.me/react-create-class');
        warnedForCreateClass = true;
        return createReactClass;
      }
    });
```

Then your code would actually crash, and hopefully you'll see the stack trace then.

Specifically, it's likely coming from a third-party library.
