### ISSUE TITLE
"is" on <button> causes "className" to translate to "classname" not "class"

### ISSUE THREAD

**Issue by acroyear** [facebook/react#12810]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you add the 'is' attribute to a button element in JSX, along with a "className" attribute, the "className" is translated to "classname" instead of "class". this causes most css-in-js engines to fail to style the button as well as keeping CSS from styling it.

For using it within a Chromecast sender app, it breaks the behavior in that Chrome is looking for.

Replication case:

https://codesandbox.io/s/yjjq44qxjv - courtesy of the material-ui team, who found that they can't fix it because it isn't something they triggered.

**What is the expected behavior?**

"className" becomes "class", and any behaviors added to the button by Chromecast's v1 framework apply correctly just as if react was not involved.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

yes, I had an app that was 15.6.2 and that worked just fine.

**Comment by acroyear** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/is

**Comment by gaearon** [comment]
It’s expected. “Is” attribute says it’s not a normal DOM element but a “custom element” (related to Web Component specs). In this case React doesn’t assume any naming convention and just passes all props as attributes.

**Comment by acroyear** [comment]
Except this makes it impossible to use in react.js at all without falling back on "dangerous-html" or creating via the DOM on a component's ref, because react won't allow one to use 'class='. At the very least it should be changing className to class in order to be usable at all, then like any 3rd party interaction, it is up to the developer to manage re-rendering via shouldComponentUpdate.

Why will react not at least do that much?

**Comment by acroyear** [comment]
Ok, 'bug' was on my part. I've gotten so used to using className= for everything (components and elements together) that I forgot that one could still just use class= for standard elements.

No worries.

**Comment by acroyear** [comment]
In the end, for integrating web components, that's not a valid solution either. It seems the is= directives aren't processed when added via innerHTML nor by setAttribute. The way to get a web component to instantiate dynamically is to add it through createElement and append/replace child. So the way to do this involves creating a ref (now made much more standard in 16.3, thank you) and appending the element to the DOM in componentDidMount.  I'll write up and publish that in a blog once i get it fully working.

**Comment by acroyear** [comment]
http://jwsdev.net/jottings/web-components-is-a-problem-in-react-js/

**Comment by gaearon** [comment]
>As part of their optimizations for 16, they moved more and to using innerHTML. 

This is not true. Neither React 15 nor React 16 do that. Both of them construct elements with DOM APIs.

**Comment by acroyear** [comment]
My apologies. I've edited that and changed it.

"so to be honest, I do not know at this time why it isn't working in this situation.  Strictly guessing, perhaps in parsing/translating the is= into the DOM, it is treating 'is' like a normal attribute rather than passing the value as the second parameter in createElement?"

And if that's the case, then wouldn't this perhaps be a bug on react's part here?  How has handling is= changed in 16, because like I said, this was working for me in 15.6.

**Comment by acroyear** [comment]
hmm...maybe this is actually a bug in Chrome itself not following the spec.

      const castButton = document.createElement('button', {is: 'google-cast-button'});

doesn't work, where

      const castButton = document.createElement('button', 'google-cast-button');

does, yet the former *should* be the right syntax, according to https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement#Web_component_example and https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements .

**Comment by acroyear** [comment]
https://codepen.io/acroyear/pen/wjEEQq - a Chrome bug. With that pen i was able to flip quickly between the {is:} syntax and the straight string, and the {is:} never worked. I'll file a bug with them.  My apologies for taking up your time.

**Comment by gaearon** [comment]
No problem!

**Comment by nhunzaker** [comment]
Cool. Thanks for following up!
