### ISSUE TITLE
UNSAFE_ lifecycle functions can no longer be defined more than once via mixins

### ISSUE THREAD

**Issue by alibosworth** [facebook/react#12830]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The unsafe lifecycle function aliases in 16.3.2 are not merged when defined more than once because of mixins, triggering an error:

>Uncaught Error: ReactClassInterface: You are attempting to define `UNSAFE_componentWillReceiveProps` on your component more than once. This conflict may be due to a mixin.

To reproduce: rename all cWM, cWRP, and cWU functions with their UNSAFE_ versions in a project where mixins cause those functions to be duplicated

**What is the expected behavior?**

That these lifecyle function continue to work as expected when called via UNSAFE aliases in 16.3, and if they are not supposed to with regard to redefining/merging, that the migration path documentation is updated to indicate so.

**Comment by gaearon** [comment]
Yeah I think we should be merging those.

@bvaughn @acdlite Do you recall if there was any reason we didn't do it? I vaguely remember some discussion about this but I might be confusing it with something else.

**Comment by bvaughn** [comment]
Which version of create-react-class are you using? I thought I'd fixed this with PR #12036 and version 15.6.3

**Comment by bvaughn** [comment]
Sorry. Maybe I'm misunderstanding what's being reported! If so, my apologies. A little more context would be helpful.

**Comment by alibosworth** [comment]
Ah shoot! Yeah somehow we were behind on create-react-class. That makes sense, I thought it was odd I couldn't find anyone else who had hit this.  Thanks and sorry for the trouble!

**Comment by bvaughn** [comment]
No problem! Glad to hear that's all it was 😄
