### ISSUE TITLE
Cursor jumps when backspacing on input type='email' and it has a space character

### ISSUE THREAD

**Issue by TheSisb** [facebook/react#12832]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Current behavior**
When you hit backspace on an `<input type="text" />` and it has a value with a space before the character you're removing, the cursor jumps to the beginning of the input.

**Simple Demo repro**
https://jsfiddle.net/69z2wepo/183750/

**What is the expected behavior?**
The cursor remains at the end of the input

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on React 16.3.2
Possible related issue: https://github.com/facebook/react/issues/11827

**Comment by Abhishek8394** [comment]
Works fine on firefox, jumps on chrome. I think it is related to the mentioned issue.

**Comment by stmoreau** [comment]
Works fine as expected on:
Google Chrome Version 66.0.3359.139
macOS High Sierra Version 10.13.4

**Comment by aweary** [comment]
The demo provided is using an input with type `email`, not `text`. This is a known issue with email inputs, related to how Chrome reports the value for email inputs. See https://github.com/facebook/react/issues/11881. Thanks!
