### ISSUE TITLE
getDerivedStateFromProps is not called on instantiation when used with SSR

### ISSUE THREAD

**Issue by joesanta555** [facebook/react#12848]
**Do you want to request a *feature* or report a *bug*?**

Probably a bug

**What is the current behavior?**

I have a standard CRA app and getDerivedStateFromProps is called before the render and then each time new props are passed to the component. This is as expected.

But when the same code is run trough ReactDOMServer.renderToStaticMarkup for SSR, render method is called BEFORE getDerivedStateFromProps.

...from the documentation: getDerivedStateFromProps is invoked after a component is instantiated as well as when it receives new props. 

Thank you

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 16.3.2

**Comment by aweary** [comment]
@joesanta555 can you please provide an example reproducing the issue? I tested with 16.3.2 and it seems to be working as expected: https://codesandbox.io/s/728om579x

**Comment by joesanta555** [comment]
hmm thats strange. Will try to provide some example.

I am using apollo HOC to fetch some data and on SSR I got the data as props loaded in the constructor. If the same code is run as CRA, the constructor does not have the data ready yet. 

If anyone else has the same issue, here is my workaround:

```js
  constructor(props) {
    super(props);
    this.state = {
       ....yourstate....
    };

    // this is a workaround around the bug, only used on SSR
    this.canUseDOM = !!(
      (typeof window !== 'undefined' &&
      window.document && window.document.createElement)
    );
    if (!this.canUseDOM) {
      const newstate = RecipeSearch.getDerivedStateFromProps(props, this.state);
      this.state = { ...this.state, ...newstate };
    }
  }
```

**Comment by gaearon** [comment]
This is most likely an issue with Apollo then. If you figure out a minimal React-only reproducing case let us know.
