### ISSUE TITLE
why setState is not async?

### ISSUE THREAD

**Issue by veedrin** [facebook/react#12840]
I heard that `setState` method is async

But I'm confused in my demo, they have the same log in console
 
Does anyone know why?

```javascript
componentDidMount() {
    setTimeout(() => {
        for (let i = 0; i < 5; i++) {
            console.log(this.state.num);
            this.setState({ num: this.state.num + 5 });
        }
    }, 5000);
}
```

```javascript
componentDidMount() {
    setTimeout(() => {
        for (let i = 0; i < 5; i++) {
            console.log(this.state.num);
            this.setState(prevState => ({ num: prevState.num + 5 }));
        }
    }, 5000);
}
```

**Comment by gaearon** [comment]
setState is currently synchronous outside of event handlers. That will likely change in the future.

**Comment by NE-SmallTown** [comment]
@gaearon Hi, dan, could you give more info about how this would change in the future? Look thought recent PRs/issue, and with my previous understanding, React can't control the behavior which doesn't belong to React, except React provide a new method or something to replace the `setTimeout` just like React use its own rIDC.
