### ISSUE TITLE
Provide HOC for new context API

### ISSUE THREAD

**Issue by mjackson** [facebook/react#12859]
I find myself needing a higher-order component every once in a while when using render props, so I can get stuff from context in my lifecycle methods. It's pretty easy to create a HOC from a render prop, so I was wondering how open y'all would be to adding a HOC to the new context API?

We can already do this in userland with a little `withContext` helper:

```js
function withContext(Context, Component) {
  return props => {
    return (
      <Context.Consumer>
        {context => <Component {...props} context={context} />}
      </Context.Consumer>
    );
  }
}

const AppWithContext = withContext(MyContext, App);
```

It would be useful to have this built-in to the new context API, something like:

```js
const MyContext = React.createContext();

const AppWithContext = MyContext.provide(App, 'optionalNameOfTheProp');
```

The second argument to `provide` (the prop name) could default to `context`.

Anyway, just thought I'd open this up for discussion before making an actual PR that adds this. Thanks for your consideration 😅

[EDIT: Removed example using `this.context`]

**Comment by jquense** [comment]
I think the position as generally been "no" on the HOC approach but a lot of that (I think) is based on not wanting an API that injects props, due to all the obvious pitfalls there. Add it as a special property is a neat though, but it likely is gonna conflict with the legacy API for the time being, and wouldn't work with function components, forwardRef components, etc. You also run into the problem of you deal with multiple contexts and conflicts e.g. `MyContext.provide(OtherContext.provide(app))`. 

I tend to think the more useful HOC here anyway is a `mapContextToProps` hoc which more intentionally turns the context into relevant props on the underlying component, which the "dumb" component also makes it more resilent anyway since it doesn't need to be tightly coupled to a `context` instance property.

**Comment by mjackson** [comment]
Thanks for weighing in here, @jquense 😅 

Could the prop name maybe be a separate argument to `provide`?

```js
AppContext.provideProp('app', RouterContext.provideProp('router', App));
```

This is more akin to your `mapContextToProps`, but with the added benefit that React could possibly warn about prop naming collisions, like it did back in the `createClass` days with `getInitialState` in mixins 👍

**Comment by aweary** [comment]
>The only difference is that the context comes in as a prop (i.e. `this.props.context` instead of `this.context`).

It's probably best that this remains a userland solution. (Re)adding another API that relies on accessing data from an instance method seems like it runs counter to the long-term goal of having an async-safe API that doesn't rely on classes.

**Comment by mjackson** [comment]
Agree, @aweary, React is moving away from instance properties. But I still think it'd be nice to have a method on context objects for providing the context as a prop.

**Comment by thismarcoantonio** [comment]
In all my React applications I store language stuff in the `context`. With the new context api my code is a mess. In every component I have this new Consumer and then the render prop inside it.

This:
```
...
const Component = (props, context) => (
  <h1>{context.content.title}</h1>
)

Component.contextTypes = {
  content: PropTypes.object
}
...
```

Became this:
```
...
const Component = (props) => (
  <Context.Consumer>
    {(content) => (
      <h1>{content.title}</h1>
    )}
  </Context.Consumer>
)
...
```

Yes, it can be pretty in one single file, but I have components with more than 230 lines and I use the context in almost all my components...

Any workaround?

**Comment by TrySound** [comment]
@thismarcoantonio I use a lot of stuff with context api: locale, relay environment, routes and isolation I have allows me do not care about context pollution I always know what in the scope. A bit of indentation doesn't matter. I usually solve it with context combiner which just works with flow types for example.
```js
const Model = ({ children }) => (
  <LocaleConsumer>
    {locale =>
      <Route>
        {route => children(locale, route)}
      </Route>
    }
  </LocaleConsumer>
)
```

**Comment by pgarciacamou** [comment]
We had the same issue @thismarcoantonio had, plus a lot of our components needed to access multiple context APIs within methods outside of render and it was a pain to have to wrap every instance or every component prior to export, to be honest, it didn't look good.

What we ended up doing in userland is create a HOC that consumes multiple contexts and injects them as props. Sort of what OP mentions in the issue `this.props.context` but for many. You can take a look at it: https://www.npmjs.com/package/react-context-consumer-hoc.

**Comment by gaearon** [comment]
We likely won't be doing this. We do have plans to make consuming context more convenient though.

**Comment by smeijer** [comment]
I just discovered [react-contextual](https://github.com/drcmda/react-contextual), I think this is indeed nice functionality for a separate (small) package.

**Comment by davidecarpini** [comment]
Powered @mjackson HoC to avoid use 'useMemo' with 'useContext' in react hooks:
````
import React, { useMemo, ReactElement, FC } from 'react';
import reduce from 'lodash/reduce';

type Selector = (context: any) => any;

interface SelectorObject {
  [key: string]: Selector;
}

const withContext = (
  Component: FC,
  Context: any,
  selectors: SelectorObject,
): FC => {
  return (props: any): ReactElement => {
    const Consumer = ({ context }: any): ReactElement => {
      const contextProps = reduce(
        selectors,
        (acc: any, selector: Selector, key: string): any => {
          const value = selector(context);
          acc[key] = value;
          return acc;
        },
        {},
      );
      return useMemo(
        (): ReactElement => <Component {...props} {...contextProps} />,
        [...Object.values(props), ...Object.values(contextProps)],
      );
    };
    return (
      <Context.Consumer>
        {(context: any): ReactElement => <Consumer context={context} />}
      </Context.Consumer>
    );
  };
};

export default withContext;
````

usage example:

````
export default withContext(Component, Context, {
  value: (context): any => context.inputs.foo.value,
  status: (context): any => context.inputs.foo.status,
});
````

this could be seen as the Context equivalent of redux mapStateToProps
