### ISSUE TITLE
Support pointer events

### ISSUE THREAD

**Issue by imaus10** [facebook/react#12881]
[Pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) are currently "unknown event handler properties" in React.

**What is the current behavior?**

[This JS fiddle](https://jsfiddle.net/Luktwrdm/448/) shows that attaching the `onPointerDown` event to a div produces this warning in the console:

```
Warning: Unknown event handler property `onPointerDown`. It will be ignored.
    in div (created by App)
    in App
```

**What is the expected behavior?**

Although pointer events are [not supported by Apple](https://caniuse.com/#feat=pointer), they are still useful to developers targeting other platforms. Perhaps a good middle ground would be to allow them, but print a console warning saying they may not work. Happy to put together a PR if someone points me in the right direction!

**Comment by jquense** [comment]
#12507 was recently merged!

**Comment by imaus10** [comment]
Awesome! Thanks.
