### ISSUE TITLE
Elements inside a Fragment get added one at a time

### ISSUE THREAD

**Issue by city41** [facebook/react#12899]
**Do you want to request a *feature* or report a *bug*?**
I believe this is a bug

**What is the current behavior?**
When adding multiple elements inside a Fragment, they get added one at a time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I setup a demo app here: https://city41.github.io/fragmenttest/
https://github.com/city41/fragmenttest

Steps to repro:
1. click the "edit" button in the first card
2. watch what happens both visually and in the DOM (break on subtree modifications is helpful)

You can see the cancel button very briefly has the hover state, and so its background is red. You can also see in the DOM using "Break on subtree modifications" on the parent div that the cancel button gets added, then the save button gets added on a second render.

The behavior depends on the browser:

`Chrome (Windows 10, 66.0.3359.181 (Official Build) (64-bit)):` the cancel button briefly has the hover state and appears red.

`Edge (Windows 10, 42.17134.1.0):` the cancel button gains the hover state and keeps it. It will be red until you move the mouse again

`Firefox (Windows 10, 60.0.1):` Firefox visually behaves as expected. If I was only using Firefox as my browser I would not have detected this issue.

**What is the expected behavior?**
After clicking the edit button, the save and cancel buttons get added to the DOM at the same time, and so the hover state on the buttons is always properly applied. You can see this by clicking "edit" in the second card, which uses a span instead of a fragment.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3.2. Unsure if this worked in a previous version.

**Comment by city41** [comment]
It looks like this is because React calls `appendChild` for each element in a fragment. Would it be possible to use a DocumentFragment?

**Comment by nmain** [comment]
In Chrome, the problem is not related to DocumentFragments.  A simple native reproduction does not cause the red flicker when used with or without DocumentFragments:

https://jsfiddle.net/v3twoayd/

**Comment by city41** [comment]
Thanks @aweary, that makes sense now that you explained it. Also made me realize I had a slight misunderstanding on keys as well. It seems the most efficient approach in this example is to give the save and edit button the same key.

**Comment by aweary** [comment]
Glad it makes sense @city41! To clarify, I think you'd want to give them _different_ keys. If they have the same key, the DOM node will be re-used. If they have different keys, React will create new DOM elements.

**Comment by city41** [comment]
What I meant is:

```
<div className="card">
    { isEditing ?
        <React.Fragment>
            <button key="cancel" onClick={this.toggleEditing}>cancel</button>
            <button key="editOrSave" onClick={this.toggleEditing}>save</button>
        </React.Fragment>
    :
        <button key="editOrSave" onClick={this.toggleEditing}>edit</button>
    }
</div>
```

So when the buttons switch over, the edit button becomes the save button, saving one button creation. If I understand correctly that would save one button creation at the cost of slightly odd looking code.

**Comment by aweary** [comment]
You shouldn't have to think about how the elements will be reused, that's mostly an implementation detail.

Using unique keys to force elements to be recreated is generally a safe work around because React has to assume the elements with different keys _are_ different and can't be reused.

But you don't get that same guarantee with identical keys. React will _probably_ reuse the elements, but it might not. That's an implementation detail. There could be other reasons the elements need to be recreated.

For example if you switch from `<span key="Foo"/>` to `<div key="Foo" />` a new element has to be created.

So you can rely on unique keys forcing elements to be recreated, but you can't rely on identical keys forcing elements to be reused. Does that make sense @city41?

**Comment by city41** [comment]
Yup, that makes sense too. Thanks again @aweary!
