### ISSUE TITLE
Get the render function from the html. (Multi page - traditional website)

### ISSUE THREAD

**Issue by toberr** [facebook/react#12907]
**Do you want to request a *feature* or report a *bug*?**
I think it's a feature, but more like just a question.
**What is the current behavior?**

Hello,

Is it possible somehow to get the render function from a script tag in the html?
In a multi page site it would be useful:
I'm asking this because if you want to edit the pages in an admin panel, with this method
i could just insert them into the html and 
I wouldn't have to rebuild the whole project to get the new javascript chunks for the pages.

No rebuilds, no code splitting, the build.js file would just contain the components.

In Vue.js you can create a build which is get the content from the html like this:

```javascript
// main.js
import App from './App.js';

new Vue({
  el: '#app',
  render: h => h(App)
});

//App.js
export default Vue.component('App', {
  template: '#page-template',
  data() {
    return { world: 'world' }
  }
  mounted () {
    ...
  },
  components: {
    ...
  }
}
```
```html
<!-- html -->
<div id="app"></div>
<script type="x-template" id="page-template">
Hello {{world}}
</script>
```

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
