### ISSUE TITLE
What you think about this used setState?

### ISSUE THREAD

**Issue by slavamukhin** [facebook/react#12917]
I`m invented a new design pattern for work a async code in React. Look at example: 

this.setState({async: updateMember(gameId, thisPlayerId, data),}, closeDD);

I`m used setState because I`m need from the beginning performed updateMembers, and only after to run the closeDD.

What you think about pattern?

**Comment by gaearon** [comment]
I’m not sure what exactly you’re asking, but you can definitely use the callback to wait for `setState` to be flushed.
