### ISSUE TITLE
16.4 broke `getDerivedStateFromProps()`

### ISSUE THREAD

**Issue by catamphetamine** [facebook/react#12912]
So in your recent [blog post](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops) you announced a so-called "bugfix" for `getDerivedStateFromProps()`:

> getDerivedStateFromProps is now called every time a component is rendered, regardless of the cause of the update.

Which in reality breaks it.

Now `getDerivedStateFromProps()` gets called on every re-render, so when a component does:

```js
onChange = (event) => {
  this.setState({ value: ... })
  this.props.onChange(...)
}

static getDerivedStateFromProps(props, state) {
  if (props.value !== state.value) {
    this.setState({
      value: props.value
    })
  }
}
```

It becomes:

* First both `this.props.value` and `this.state.value` are `undefined`.
* Then `onChange(event)` handler triggers and calls `this.setState({ value: ... })`.
* Because the state got updated `getDerivedStateFromProps()` is called in the new React 16.4.
* `props.value` hasn't been updated yet, but `state.value` has, so the `if` condition triggers because `props.value === undefined` and `state.value = ...`. Hence `this.state.value` gets reset by this `if` condition and becomes `undefined` (which is already a bug) because `props` are the "single source of truth" as per the official React recommendations.
* Next, `this.props.onChange(...)` line executes which updates `this.props.value` which in turn calls `getDerivedStateFromProps()` again.
* The `if` condition triggers again because `props.value === ...` and `state.value = undefined` and so `this.state.value` becomes `...` again.

Now, this whole cycle may go totally unnoticed until one really debugs it with `console.log` and discovers the kind of a bizarre behaviour described above.
Not only does it now perform some useless and unnecessary (and most likely computationally heavy) work twice, but it also breaks some people's code.
If you're advocating the use of "memoization" instead of `getDerivedStateFromProps()` for "intense computations" then the only legitimate use-case for `getDerivedStateFromProps()` is detecting when something changes and performing an action when it does, so the new React 16.4 introduces a bug where such change detector is being triggered twice for no reason.
Not only is this a potential performance bottleneck, in my case it actually [breaks the phone number input component](https://github.com/catamphetamine/react-phone-number-input/issues/131):

```js
static getDerivedStateFromProps(props, state) {
  if (props.value !== state.value) {
    this.setState({
      value: props.value,
      country: getCountryFromPhoneNumber(props.value)
    })
  }
}
```

The design requirement is to let a user set `value` externally which in turn must update the country flag icon.
It worked in React 16.3.
In React 16.4 though `getDerivedStateFromProps()` gets called on each internal state update resulting in the country flag being reset every time a user types a character (because an incomplete phone number can't be a source of a country flag, e.g. USA and Canada both start with `+1`, not to mention the whole NANPA region).

**Comment by DavidBadura** [comment]
Your code is wrong:

1) `getDerivedStateFromProps` is a static method, so you should not call methods on `this` like `setState`
2) You should **return** the changed state

The right way:

```
static getDerivedStateFromProps(props, state) {
  if (props.value !== state.value) {
    return {
      value: props.value
    };
  }

  return null;
}
```

**Comment by aweary** [comment]
Please refer to https://github.com/facebook/react/issues/12898

**Comment by catamphetamine** [comment]
@DavidBadura true, corrected the code samples. the issue still persists.
