### ISSUE TITLE
With WebPack: React is running in production mode, but dead code elimination has not been applied.

### ISSUE THREAD

**Issue by resistdesign** [facebook/react#12929]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*.

**What is the current behavior?**

When compiled in production an error is thrown:

```
Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

It's related to compiling/bundling, so there would be a substantial number of dependencies other than React.

**What is the expected behavior?**

Don't throw the error when compiling with WebPack and following the guide at the given link (https://fb.me/react-perf-use-the-production-build).
Development code should not be included when `WebPack.DefinePlugin` is used to set `process.env.NODE_ENV` to `"production"` and `WebPack.optimize.UglifyJsPlugin` is configured to run on all `.js` files with `test: /\.(js|jsx)$/`, `compress: { warnings: false }` and `sourceMap: false`.

NOTE: License comments in the bundle suggest that `react-dom.production.min.js` as well as `react-dom.development.js` are both included along with `react.production.min.js` and `react.development.js`.

This could be a WebPack configuration issue, however the entire bundle "seems" to be "uglified" and no other packages seem to exhibit anything other than production behavior.

If you want to peck around in the bundle, please enjoy :) http://booklets.resist.design/index-entry.js?a441990c7d318c1cf5fc

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.4.0

15.x.x didn't have this issue with the same WebPack configuration.

**Comment by gaearon** [comment]
I don’t see how we can help without seeing a reproducible example with a config. If you create a new project you wouldn’t experience this. So something is wrong with your particular setup.

**Comment by gaearon** [comment]
That said your bundle is full of code like `"production"==={NODE_ENV:"production",IS:{production:!0}}.NODE_ENV` which means process env checks don’t get properly eliminated.

I think your `DefinePlugin` declaration incorrectly specifies a whole object instead of individual properties. Please update it to exactly what we recommend in https://reactjs.org/docs/optimizing-performance.html#webpack and it’ll work.

**Comment by resistdesign** [comment]
> I think your DefinePlugin declaration incorrectly specifies a whole object instead of individual properties.

@gaearon If that's how it works, then that's it, it's an object. Thank you for taking a look!

**Comment by resistdesign** [comment]
@gaearon Just fyi, that was exactly it, I changed it to flat paths and now have a production bundle with no errors.

For anyone else who comes across this, here is what I did to make the flat path structure easily maintainable: https://github.com/resistdesign/rdx/blob/master/src/Config/WebPack/Plugins/Common/ENV.jsx#L17

1. Flatten with `flat`.
1. Convert all values to `JSON`.

**Comment by ashishqss** [comment]
Please run this command and you will see that error.
**gulp deploy-no-compress**
