### ISSUE TITLE
Preserve property getters in state updates

### ISSUE THREAD

**Issue by stefanprobst** [facebook/react#12927]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On state updates, property getters on `this.state` are transformed into literals.
E.g. `this.state = { en: 'hello', get english() { return this.en; } }` will be `{ en: 'bye', english: 'hello' }` after `this.setState({ en: 'bye' })`.

[Code example here](https://codepen.io/spbks/pen/OEJzzV?editors=0010)

**What is the expected behavior?**
Getters should still be available after state updates.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.3

**Comment by gaearon** [comment]
This is intentional. State updates are merged, and getters don’t really work great in this and many other scenarios.
