### ISSUE TITLE
Broken `fiber-triangle-demo` and `schedule` fixtures

### ISSUE THREAD

**Issue by flarnie** [facebook/react#12930]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
These two fixtures are both broken due to a reference to `global` in the bundle they reference.

This was introduced in a PR I just landed, so I'm fixing it. See https://github.com/facebook/react/pull/12900

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Open either fixture in Firefox, note the error in the console and the page doesn't update.

**What is the expected behavior?**
They should have React and/or the schedule module running JS on the page.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Just on master.

**Comment by aweary** [comment]
The DOM fixtures are also broken, I was _just_ trying to figure out if I broke something 😄
