### ISSUE TITLE
using electron ipc in react 

### ISSUE THREAD

**Issue by PlacidoDomingo** [facebook/react#12934]
How can I use electron renderer ipc in a react component js file ?
I wrote " const electron = require('electron') or import electron from 'electron' "
it doesn't work, error reports: "Module not' found, can't resolve 'electron' "

DO I have to config webpack or something ?

I'm stuck on this really for a few days. Thank you.

**Comment by schillingjerrid** [comment]
@PlacidoDomingo I found this [Medium article](https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c) that may be of some use. It looks like it may cover the topic you are asking about.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by PlacidoDomingo** [comment]
fantasitic, it works
the solution is: 
in html file,  window.require = require, 
then in react js file, const electron = window.require('electron')

**Comment by adityapatnaik** [comment]
https://stackoverflow.com/questions/48148021/how-to-import-ipcrenderer-in-react/64124159#64124159
