### ISSUE TITLE
className in <amp-img /> was not converted

### ISSUE THREAD

**Issue by fmy** [facebook/react#12935]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
`className` in the html tags include dash was not convert `class`.
```
<amp-img className='image' />
```
renderToString ↓
```
<amp-img classname='image' />
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/kLgv9u2w/

**What is the expected behavior?**
should be
```
<amp-img class='image' />
```
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react v16.3.2

**Comment by gaearon** [comment]
Custom elements currently get their attribute without any mapping (we can’t guess what they mean). So you just need to pass `class`.
