### ISSUE TITLE
Wrong event.target.value

### ISSUE THREAD

**Issue by knafm** [facebook/react#12948]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Given: input field type='email'
When: type valid email address , after type сyrillic letter (some@mail.com and type 'д' (for test you can copy - paste it) )
Then: as a result , we have 'some@mail.xn--com-pdd' and cursor in the start of input field
**What is the expected behavior?**
some@mail.comд in input field , which i can change
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react version:16.3.1, browser: chrome 66
simple example https://codesandbox.io/s/3rrzz3qk6

**Comment by tikhonandrey** [comment]
I got what is happend
It's [Punycode](https://ru.wikipedia.org/wiki/Punycode) parsing of сyrillic letter in email
for example, if try to copypast from browser url кошка.рф it become xn--80atap4c.xn--p1ai
so i think this behavior is not a bug

**Comment by Alex1990** [comment]
I have tested it with the native input element. The example page: https://codepen.io/Alex1990/pen/BVoKVz?editors=1010.

In Chrome 66, the letter 'д' will be encoded. But, in Firefox 60 and Safari 11, the letter will NOT be encoded.

If I convert the `event.target.value` to its unicode format manually with [`punycode.toUnicode()`](https://www.npmjs.com/package/punycode#punycodetounicodeinput) method, then all things will be as expected. See this example: https://codesandbox.io/s/mjop6yp37y

Also, you can use `type="text"` input and add the email validation by yourself.

**Comment by knafm** [comment]
Thanks for additional research! I think it's resolved.
