### ISSUE TITLE
Event listener leak

### ISSUE THREAD

**Issue by hally9k** [facebook/react#12947]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Accumulating listeners after interacting with input elements and then un-mounting them. If the elements are not interacted with the listener is garbage collected correctly.

Here is a screenshot of the accumulation in a production build:

![screen shot 2018-05-31 at 5 13 35 pm](https://user-images.githubusercontent.com/3803536/40762743-0f027dcc-64f6-11e8-9467-78e37d5027e3.png)

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Use either of the following repros and follow the reproduction instructions in the comments/readme.

For convenience it is reproduced here:
https://codesandbox.io/s/317j2lz8l6

But it is better illustrated by pulling this repro as there is less going on:
https://github.com/hally9k/listener-leak-test

**What is the expected behavior?**
No accumulation of event listeners.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
macOS@10.13.4
Chrome@66.0.3359.181
react@16.4
react-dom@16.4

**Comment by whs-dot-hk** [comment]
@hally9k Why are you doing this?

https://github.com/hally9k/listener-leak-test/blob/8d71aa0a33508b7e3ce020c80d891fd87dc2320e/src/index.js#L26

Puting

```
() => ({ edit: !this.state.edit })
```

inside setState()

**Comment by whs-dot-hk** [comment]
Is this fix ok?

https://github.com/hally9k/listener-leak-test/pull/2

**Comment by hally9k** [comment]
@whs-dot-hk I have changed the setState calls from:
```() => ({ edit: !this.state.edit })```
to:
```prevState => ({ edit: !prevState.edit })```
As I realise I shouldn't have been referencing `this.state` directly from the function.

Otherwise there isn't anything wrong with that piece of code as far as I can tell. My understanding is that if you want to reference the component's internal state in a `setState` call then a function must be used.

This is unsafe:
```
this.setState({
   edit: !this.state.edit
})
``` 

I pulled your changes and it doesn't stop the leak, there are instructions on the repo explaining how to reproduce the leak in chrome dev tools. Have a go at testing if your fix works and note the accumulation of listeners in the performance chart.

**Comment by hally9k** [comment]
I had a first read of the source yesterday. I think I found where the event listeners are getting added but failed to find the code that tidies them up.

Here is where I assume the listeners for events that do not bubble up are added to elements. Apologies if I'm way off, first timer here. 😬 

https://github.com/facebook/react/blob/65ab53694f6edf4437034d5644a602dea162e249/packages/react-dom/src/client/ReactDOMFiberComponent.js#L873

https://github.com/facebook/react/blob/65ab53694f6edf4437034d5644a602dea162e249/packages/react-dom/src/events/ReactDOMEventListener.js#L148

https://github.com/facebook/react/blob/65ab53694f6edf4437034d5644a602dea162e249/packages/react-dom/src/events/EventListener.js#L15 

If anyone could help show me where these listeners are removed when the component is unmounted that would be awesome.

**Comment by gaearon** [comment]
These event listeners aren't explicitly removed. GC will do that when nothing references the DOM element. If something keeps a reference then it sounds like a bug. Generally React is expected to clean up a reference to something that was deleted during the next update.

**Comment by gaearon** [comment]
@hally9k Want to look into what's holding onto the element?

**Comment by hally9k** [comment]
@gaearon Sure I can have a look, would you mark this as a "Good beginner bug" though? I literally started reading the source yesterday. Either way I'll get stuck in and see how we go.

**Comment by nhunzaker** [comment]
@hally9k Happy to help answer any questions there. Please don't hesitate to reach out!

**Comment by aweary** [comment]
@hally9k are you profiling with any extensions enabled? I tried running your test app locally, and while I do see that the listener count increases over time, they do eventually get GC'd.

<img width="1231" alt="screen shot 2018-06-01 at 8 30 57 am" src="https://user-images.githubusercontent.com/6886061/40849263-50553f14-6576-11e8-8420-b375955fd016.png">

**Comment by aweary** [comment]
The Performance tab is indicating that there's an increase in the Node count, even after GC, but I've taken a few heap snapshots and there's no clear indicator that DOM nodes aren't being cleaned up. The only positive delta is for things like `(array)`
<img width="1146" alt="screen shot 2018-06-01 at 9 04 07 am" src="https://user-images.githubusercontent.com/6886061/40850941-c814dbdc-657a-11e8-8221-2b6fd23ce301.png">

**Comment by BTMPL** [comment]
I can see an Detached DOM tree when transitioning between states

![image](https://user-images.githubusercontent.com/247153/40851339-6912da9c-65c7-11e8-8001-8a7def0c7225.png)

this matches the count of new nodes recorded in performance tab.

**Comment by aweary** [comment]
I think a few detached nodes would be expected, since the Fiber may store a reference to the previous node for a short time. After the next update the node should be dereferenced though. I would expect a constant number of detached DOM nodes.

**Comment by BTMPL** [comment]
Yeah, that looks to be the case. Multiple state changes after that and the delta between previous snapshot is the same (2). 

The only change I see (that is meaningfull) is `array` and `system`. 

Maybe it's an error in the Chrome profiller? Anyone checked with Firebug?

**Comment by aweary** [comment]
@hally9k alright, I did some more profiling using the production build of the test application you provided. Here's a profile from just clicking the edit button over and over, without interacting with the input element:

![screen shot 2018-06-01 at 5 02 04 pm](https://user-images.githubusercontent.com/6886061/40867999-9464ce8a-65bd-11e8-9360-d10cb4bbb37f.png)

The valleys in the graph are from manually triggering a GC event. Each time, the total node/listener count returned to the same value. Here's a profile doing the same thing, except every time the input appears I typed in some content:

![screen shot 2018-06-01 at 5 07 04 pm](https://user-images.githubusercontent.com/6886061/40868096-85765320-65be-11e8-8d1b-3acf8e722ebe.png)

This appears to indicate that there is a leak related to the actual input event processing. This suggests that it's likely not related to the `trapBubbledEvent` calls, since those would be called regardless of whether the input was interacted with.

Somewhere in the event handling code path a reference is being retained to the DOM node causing it to not be GC'd.

**Comment by BTMPL** [comment]
@hally9k  Ok, but I'm seeing increase in both listeners and node count with my change (so transition from `b` to `p`):

![image](https://user-images.githubusercontent.com/247153/40871452-5bb71140-663c-11e8-9e5d-0b6de0e54bd2.png)

(the two lines overlap perfectly, that's why only one is shown).

Manually triggering GC resets the node/listeners count.

**Comment by hally9k** [comment]
@aweary - oh awesome I’m not going crazy, yes this is exactly what I’m getting my end, only when focusing on the input during each iteration are the listeners getting leaked. I’ll have another look at the event handling code shortly and try and track down where the reference to the node might be being held.

**Comment by hally9k** [comment]
Ooops, didn't mean to close this, reopening.

**Comment by hally9k** [comment]
I had some time this morning but Chrome 67 seems to have a bug in the performance memory profiling that makes the y axis max out at 1 obscuring the chart, I can't get the chart to show in Canary or Chromium either. So frustrating! Is anyone else experiencing this? I've lodged a bug with the Chromium team:
https://bugs.chromium.org/p/chromium/issues/detail?id=849057

@nhunzaker Thanks for taking the time and the detailed explanation of your findings. Unfortunately, after downloading an older version of chrome (non-trivial 🙄) and finally profiling with your changes I couldn't see any difference in the number of GC'd listeners after "flushing" the reconciler's node references by firing that additional `setState` you added. The listeners accumulate as before and the number of listeners doesn't drop back to the original number.

From a high level position, even if the flush did release the references, I'm not entirely sure I would be satisfied with this behaviour. It appears that the stringing together of particular interactions would cause an accumulation of listeners until an update is scheduled that, by chance, allows the references to be released.

As a side note: I installed Preact on the example repo out of interest and it was stable. 

I will be digging into the code later this evening (NZT)

**Comment by nhunzaker** [comment]
> From a high level position, even if the flush did release the references, I'm not entirely sure I would be satisfied with this behaviour

Totally. I struggle with this being the intended behavior as well. I am not familiar enough with the data Fiber component data structure, but it seems like the memory growth should flat-line similarly to forcing an unrelated update via `setState`.

**Comment by kubijo** [comment]
Hi. Have you guys had any progress on this since then?
I've just been forced to helplessly stare into memory profiler for the past week while trying to figure out the ever-increasing listeners count.

**Comment by raRaRa** [comment]
Out of curiosity, are you using Sentry to log errors? I noticed A LOT of detached nodes and the root of the problem seems to be related to Sentry adding event listeners to various things. Still looking into it. My app reaches about 3-4 GB after 3 days running. (A slideshow website).

**Comment by kubijo** [comment]
> Out of curiosity, are you using Sentry to log errors? I noticed A LOT of detached nodes and the root of the problem seems to be related to Sentry adding event listeners to various things. Still looking into it. My app reaches about 3-4 GB after 3 days running. (A slideshow website).

Nope, not in JS anyway.
