### ISSUE TITLE
react class strict mode reserved word

### ISSUE THREAD

**Issue by sowdf** [facebook/react#12945]
webpack uglify 
![image](https://user-images.githubusercontent.com/16848523/40759741-f6430c78-64c5-11e8-996b-d77557aa49f3.png)

```javascript
				charset: "charSet",
				checked: "checked",
				children: "children",
				cite: "cite",
				class: "className",
				classid: "classID",
				classname: "className",
				cols: "cols",
				colspan: "colSpan",
```

With tools after compression, appeared class reserved word ? 

code in android 4.0 “strict mode reserved word”

**Comment by nmain** [comment]
Current web browsers support using reserved words in object literals in that context.  If you need to target a browser that doesn't, (if React even supports something that old?  This works even in IE9) and your minifier is making that change, then you need to fix your minifier.

For uglify, it may be called `keep_quoted_props=true` https://github.com/mishoo/UglifyJS2/issues/1386

**Comment by gaearon** [comment]
Yeah, we don't officially support IE8 or equivalent browsers without ES5 compatibility so you'll need to use a custom postprocessor to quote the reserved keys if you need that.
