### ISSUE TITLE
.flowconfig for editing in vscode

### ISSUE THREAD

**Issue by nateq314** [facebook/react#12952]
**Do you want to request a *feature* or report a *bug*?**

Neither I think...? Just ask a question relating to the codebase and flow/editor config.

**What is the current behavior?**

1) git pull react
2) yarn install
3) navigate to project root directory
4) `code .`

Upon doing this, flow type checking does not work at all in vscode, even though
1) 'flow-for-vscode' extension is installed and enabled
2) Typescript has been *disabled* per docs
3) "flow.useNPMPackagedFlow" setting is set to *true*

The reason seems to be the lack of a `.flowconfig` file in the project root. Adding an empty `.flowconfig` and reloading vscode makes it work, albeit with loads of linting errors (mainly `__DEV__ not found` errors).

I saw that in `scripts/flow` there are several different `.flowconfig`s along with scripts that appear to get run when you do `yarn flow`. I understand that this is all as it should be and that `yarn flow` functions fine. I just want flow to work in-editor when I open up the project from the root directory.

What is the correct way for generating the necessary `.flowconfig` file? I tried just copy-pasting the one from `scripts/flow/dom/` but that still resulted in a bunch of `__DEV__ not found` errors.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

In-editor Flow type checking, code referencing, etc., should all work on opening a fresh pull of the code, and there should be zero linting errors.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

N/A

**Comment by gaearon** [comment]
It's intentional. Our setup is a bit more complicated and unfortunately a single Flow config won't work for us. We don't support running any IDE integrations at the moment—please run `yarn flow dom` and use the console output. Sorry for the inconvenience.
