### ISSUE TITLE
Allow `ref` attribute on custom elements

### ISSUE THREAD

**Issue by stefanprobst** [facebook/react#12951]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Creating a custom element with a `ref` attribute currently is not possible, because `React.createElement('my-element', { ref: 'my-attribute' })` will interprete the `ref` attribute in a special sense.

**What is the expected behavior?**
Like for `htmlFor` it would be great if there were an alias that allows creating a `ref` attribute on a custom element.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.3

**Comment by whs-dot-hk** [comment]
Current behavior

https://codesandbox.io/s/48zl80r2m0

**Comment by Alex1990** [comment]
Only in the stateful component, we can use the `ref`. An example https://codesandbox.io/s/018kpklrvp.

In function component or the element created by `React.createElement`, the `ref` is not supported. 

[Refs Must Have Owner Warning](https://reactjs.org/warnings/refs-must-have-owner.html)

**Comment by stefanprobst** [comment]
Just so we are not talking past each other: I am *not* concerned with a ref in the sense of a reference to a DOM node. I merely want to create an element with an attribute called "ref". This is a html-attribute like any other - except in React it is not.
Your codesandbox example illustrates this quite nicely: The `ref` attribute on `<my-element>` is treated as a reference then available on this.refs, not as a html attribute.

**Comment by aweary** [comment]
@stefanprobst What's your use case here? `ref` doesn't appear to be a standard HTML element at all. We have `htmlFor` because `for` is a standard attribute, so having something like `htmlRef` would probably be really confusing.

**Comment by aweary** [comment]
I agree this is a problem, but I'm not sure there's a reasonable solution. You'd also have the same problem with `key`, or any other future props that React may use internally.

Could you just use the `htmlRef` attribute name directly? Is `ref` a common custom element attribute name with custom elements? I don't think we'd make an exception for custom elements unless this was already a popular pattern that we need to support. If you're using React and custom elements, this may just be one small limitation.

**Comment by gaearon** [comment]
If we ever move ref off the element config object we could do this.

**Comment by rob2d** [comment]
there are certain libraries which seem to be relying on the `ref` properties which are hard to avoid in some environments. Example: ag-grid heavily relies on this for customizing template functionality -- but ironically must use React's `ref` to inject a `ref` attribute onto the HTML DOM node when a component is mounted/rendered. It is pretty cringy.

https://www.ag-grid.com/javascript-grid-column-header/#header-templates

**Comment by K1N5L4Y3R** [comment]
I was just curious about this and tried using `Ref` instead of `ref` in the codesandbox URLs provided in this issue and it seems to do the trick of rendering `ref` (i.e. ignoring Reacts special treatment of `ref`).

Just in case this helps someone. I didn't test it thoroughly, though.
