### ISSUE TITLE
Fire change events for changes made to inputs before hydration

### ISSUE THREAD

**Issue by aweary** [facebook/react#12955]
Currently when hydrating server-rendered markup we ignore changes the user makes before hydration. We also don't reset their changes once hydration finishes. The motivation there was likely to avoid losing user input. See this test:

https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactDOMServerIntegrationForms-test.js#L543-L552

The problem with that is that it assumes the value will continue to be changed after hydration completes (e.g., a user keeps typing). If they _don't_, then the DOM and React will be out of sync.

We should try to detect if there have been any changes made to an input when hydrating, and if so dispatch a change event so that the component is notified of the new value.

See https://github.com/facebook/react/pull/12939 for some more discussion.

**Comment by asiniy** [comment]
It's promising to be difficult to me, but I'm taking this one

**Comment by joliss** [comment]
@acdlite I was wondering if it could be worth reopening this issue? This is still a problem for me on the latest React 18.2.0, when hydrating a component with an `<input>` field via Next.js.

**Comment by jnicklas** [comment]
This is still an issue in 2024. Would be great to reopen this issue.
