### ISSUE TITLE
Multiple custom renderers at the same time?

### ISSUE THREAD

**Issue by mthurlin** [facebook/react#12959]
**Do you want to request a *feature* or report a *bug*?**
Bug/Question

**What is the current behavior?**
I get the warning "Unexpected pop" when running two reconcilers at the same time.

I have two custom renderers. One for the main app UI and one for a dev-only debug UI. The react trees are separate, and the host component are different.

It works fine as long as I dont stress it. It seems that I get the error when work is performed in both reconcilers at the same time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Sorry, I don't have a minimal repro yet. If this is indeed a bug, and running two reconcilers at the same time should be supported, I might spend the time to do a minimal repro.

**What is the expected behavior?**
I would expect the two reconcilers to work independently when running at the same time.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react-reconciler 0.7.0

**Comment by gaearon** [comment]
May be a bug. Try with latest `react-reconciler`?

**Comment by mthurlin** [comment]
Yeah, will try as soon as I get some time to troubleshoot the upgrade. Just bumping to 0.11.0 and flattening the host config was not enough to make it work.

**Comment by gaearon** [comment]
A reproducing case would help.

**Comment by mthurlin** [comment]
I got the upgrade to react-reconciler 0.11.0 working in my project and I cannot reproduce the issue now. Closing.
