### ISSUE TITLE
Allow the second parameter of ReactDOM.render() to be a CSS Selector

### ISSUE THREAD

**Issue by franciscop** [facebook/react#12967]
**Do you want to request a *feature* or report a *bug*?**
Request a feature. It would be lovely to allow for the second parameter of `ReactDOM.render()` to be a string like this:

```js
ReactDOM.render(<MyComponent />, '#root');
```

I can try to implement it if it's a wanted feature. I estimate the bare basics can be done in 10-15 LoC, plus all the testing and documentation.

**What is the current behavior?**
You need to specify the HTML Element as the second parameter of `ReactDOM.render()`, while there is a great API that would allow for a lot more flexibility and cleaner code. If you try to pass a string, the `Target container is not a DOM element.` error is thrown (as expected).

**What is the expected behavior?**
The second parameter can accept a string, which would then be used with `querySelectorAll()` internally.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All of them so far.

**Comment by aweary** [comment]
Thanks for the suggestion @franciscop, but it's unlikely that we'd change the current `ReactDOM.render` API without good reason. Allowing CSS selectors would introduce potential ambiguity, since selectors can potentially match multiple nodes. For example, if I pass in `.container`, what happens if the page has multiple containers?

Since `ReactDOM.render` is typically only called once and having to query the DOM node yourself is very straightforward, I'm going to say that this isn't a change we'd want to make.

Thanks!

**Comment by AnthumChris** [comment]
@franciscop You could override `render()` locally to accept both `Element` and DOM selector strings:

```js
ReactDOM.render = (origFunc => {
  return (element, elementOrSelector, callback) => {
    const el = (elementOrSelector instanceof Element)?
          elementOrSelector : document.querySelector(elementOrSelector);
    return origFunc.call(ReactDOM, element, el, callback);
  }
})(ReactDOM.render)
```
### Example
```html
<div id="heading"></div>
<div id="subheading"></div>
```
```jsx
ReactDOM.render(
  <h1>Heading</h1>,
  '#heading'
);

ReactDOM.render(
  <h2>Subheading</h2>,
  document.getElementById('subheading')
);
```

**Comment by franciscop** [comment]
Thanks @AnthumChris , I can easily keep doing `document.querySelector`, I opened this suggestion since virtually everywhere people are doing the exact same thing I thought this feature could make it a bit easier for React devs. Ambiguity would be an issue then though, so I agree it's a decision on React Team's side and there's no problem closing this 😄
