### ISSUE TITLE
ReactDom.hydrate removing SSR DOM on error

### ISSUE THREAD

**Issue by UsainBloot** [facebook/react#12960]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When `ReactDom.hydrate` fails to hydrate, it currently removes all the DOM inside the mount point.
```jsx
class App extends React.Component {
  render() {
    throw new Error();
    return <h1>Hydration successful</h1>;
  }
};

ReactDOM.hydrate(
  <App />,
  document.querySelector("#root")
);
```
eg. https://codepen.io/usainbloot/pen/dKoEBy

**What is the expected behavior?**
`hydrate` defaults to not replacing server side rendered DOM when there is an error hydrating or an optional parameter.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.4.0
All OS's
All Browsers

**Comment by UsainBloot** [comment]
Would there be support for raising a PR to add this feature, or is it already acting as intended?

**Comment by gaearon** [comment]
I think the warning in the console says that you need to add error boundaries to your app to protect against crashes. This is true whether you do a clean client render or hydrate.
