### ISSUE TITLE
fetch is never executed in componentWillMount when getDerivedStateFromProps present

### ISSUE THREAD

**Issue by wzup** [facebook/react#12962]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I found 2 suspicious behavior.
Both happen when a component has `static getDerivedStateFromProps()` method.

1. if `componentWillMount` has `fetch`, then `fetch` is never invoked, no request sent, its `.then` never called. Method itself gets called, but not `fetch` in it.
2. `UNSAFE_componentWillMount` is not invoked at all.

  | w/o `getDerivedStateFromProps` | with `getDerivedStateFromProps`
-- | -- | --
`UNSAFE_componentWillMount` | is called; `fetch.then` works OK | is not called at all; Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.
`componentWillMount` | is called; `fetch.then` works OK | is called; `fetch` doesn’t send request, `.then` is not called

**What is the expected behavior?**

Same as for `componentWillMount` alone

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React Hot Loader version: ^4.2.0
React: 16.4.0
node -v: v8.9.4
npm -v: 5.6.0`
Operating system: Ubuntu 16.04.4 LTS xenial
Browser and version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Component**
```javascript
export class Foo extends React.Component {
    render() {
        return (
            <div className={'Foo'}>
            </div>
        );
    }
    constructor( props, context ) {
        super( props );
        this.state = {
            color: '#fff'
        }
    }
    // UNSAFE_componentWillMount() {
    componentWillMount() {
        return fetch( 'https://jsonplaceholder.typicode.com/posts/1' )
            .then( res => res.json() )
            .then( json => {
                console.log( '[json]', json );
            } )
    }
    static getDerivedStateFromProps( props, state ) {
        return { backgroundColor: 'green' }
    }
}
```

**Comment by gaearon** [comment]
React can’t guess if you call fetch or not. It cannot break fetch. 

It is expected that components using new lifecycles won’t be able to use older ones. That’s what the warning is about.

cWM firing at all when gDSFP is present sounds like a bug. Can you create a demo please and host it on jsfiddle or codesandbox?

**Comment by milesj** [comment]
What happens if you remove the `return` before you fetch?

**Comment by aweary** [comment]
No follow up, so I'm assuming this was just a user error. @wzup if you think this _is_ a bug, please follow up with the requested information and we can look at re-opening this. Thanks!
