### ISSUE TITLE
why modify state directly works?

### ISSUE THREAD

**Issue by veedrin** [facebook/react#12977]
I want report a bug, maybe.

#### Current behavior:

```javascript
componentDidMount() {
    this.state.star = 1000;
    this.setState({ star: this.state.star + 1 }); // 1001
}
```

```javascript
componentDidMount() {
    this.state.star = 1000;
    // this is especially strange
    this.setState(prevState => ({ star: prevState.star + 1 })); // 1001
}
```

```javascript
componentDidMount() {
    const { star } = this.state;
    this.state.star = 1000;
    this.setState({ star: star + 1 }); // 1
}
```

#### Expected behavior:

> Do Not Modify State Directly

But why modify state directly works?

setState is strange.

**Comment by veedrin** [comment]
@danburzo Thanks.
So `this.setState` is in a state of chaos.

**Comment by gaearon** [comment]
I don't know what you mean by a "state of chaos" :-)

React could potentially freeze the state object itself (and may do so in the future). That would be a breaking change though.

More often we see people doing deep mutations. Unless we froze the state deeply (which would be pretty slow even for development) we wouldn't be able to prevent it anyway. And there are some rare legit use cases for it (technically React supports mutable data sources).

So I'm not seeing the issue. "Don't mutate" is a recommendation.
