### ISSUE TITLE
render() delayed execution based on props -- v15.6.2 working, v. 16.0.0 not working

### ISSUE THREAD

**Issue by HoldOffHunger** [facebook/react#12979]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

render() runs immediately only when provided unique props or on initial, main-parent rendering component, in v. 16.4.0.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

When render() executed immediately after being called, it followed a code path through shouldComponentUpdate(), and when it has delayed execution because of non-unique props, it followed a code path through componentWillMount().

When it worked: shouldComponentUpdate() immediately ran after calling ReactDOM.render(childcomponent, parentcomponent);.

When it didn't work: componentWillMount() ran after the current function of the parentcomponent had finished executing.

Please let me know if this is insufficient info.

**What is the expected behavior?**

In ReactJS, 15.6.2, render() always runs, and runs immediately, whether its props are unique or not.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This was last working in 15.6.2.  It is not working in 16.4.0.

**Comment by whs-dot-hk** [comment]
@HoldOffHunger What do you mean by when it worked and when it didn't work?

**Comment by whs-dot-hk** [comment]
Checkout

https://github.com/facebook/react/blob/36546b5137e9012ebdc62fc9ec11e3518c9e0aab/packages/react-reconciler/src/ReactFiberBeginWork.js#L274

and

https://github.com/facebook/react/blob/36546b5137e9012ebdc62fc9ec11e3518c9e0aab/packages/react-reconciler/src/ReactFiberClassComponent.js#L733

**Comment by whs-dot-hk** [comment]
@HoldOffHunger 
```js
document.getElementById("right").innerHTML = "";
```
is not allowed in react

And you should update the existing component instead of using render

**Comment by HoldOffHunger** [comment]
Hrm, the same exact code works on v. 15.6.2 : https://codesandbox.io/s/jj303llv35

Was looking here, and what I'm running into may be https://github.com/facebook/react/blob/master/CHANGELOG.md#breaking-changes :

> Non-unique keys may now cause children to be duplicated and/or omitted. Using non-unique keys is not (and has never been) supported, but previously it was a hard error.

Going to look into this more.

**Comment by HoldOffHunger** [comment]
@whs-dot-hk:

RE: InnerHTML vs unmount:

I have made the coding change as recommended, swapping innerHTML() with unmountComponentAtNode().  I had, of course, tried this before, because the console suggests it.

However, while innerHTML() cleared the component, this has no effect the first time it is called, although subsequent to its first call, unmountComponentAtNode() does work: try here -- https://codesandbox.io/s/xo9mx0123o

This solution would fit my overall needs -- but it does not work. =\

Re: State Rendering

My app is a desktop, with a 4k by 2x grid and icons that can be placed on any cell.  But, some icons can be made (brand new components), as some icons can be removed (remove originally mounted components).  Instantiating a new component, to match a new icon, and placing it as needed with ReactDOM.render(), feels like a cleaner approach for what my app needs to do.  Not many apps use drag and drop to make new components and delete old components, but being a desktop, that's almost the entirety of my application.  (The demo is just a really simple example of what's happening.)

Anyway, let me know if I'm using unmountComponentAtNode() incorrectly, or if you have suggestions on dynamically making new components during runtime.

**Comment by HoldOffHunger** [comment]
I have a solution.

unmountComponentAtNode() does not work, innerHTML = "" does not work; but using both of them together does: https://codesandbox.io/s/1w061j0473

This still feels like a bug in unmountComponentAtNode(), though?

**Comment by whs-dot-hk** [comment]
@HoldOffHunger I think the hint is also in the codesandbox

The warning said move the unmount function to parent component

**Comment by HoldOffHunger** [comment]
@whs-dot-hk

Yes, but as mentioned, the code sample with unmount on the parent component doesn't work.  https://codesandbox.io/s/xo9mx0123o

It does come up with "The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component."  But, also as stated, that's inapplicable to the application I am developing.

**Comment by gaearon** [comment]
`ReactDOM.unmountComponentAtNode()` is only meant to be used **at top level**.  Similarly, it's not supported to call `ReactDOM.render()` into a container that's already a part of another React tree.

Instead of rendering a child "into" nodes managed by React, **use state to drive rendering**:

```js
  state = {
    currentBox: "left"
  };

  handleLeftDrop(e) {
    cancelDefaultBehavior(e);
    this.setState({
      currentBox: "left"
    });
  }

  handleRightDrop(e) {
    cancelDefaultBehavior(e);
    this.setState({
      currentBox: "right"
    });
  }

  render() {
      return (
        <div>
          {/* ... */}
          <tr>
            <td>
              {this.state.currentBox ===
                "left" && <FloatingComponent />}
            </td>
            <td>
              {this.state.currentBox ===
                "right" && <FloatingComponent />}
            </td>
          </tr>
          {/* ... */}
        </div>
      );
  }
```

Here's a working example: https://codesandbox.io/s/x30011041z

**Comment by gaearon** [comment]
>It does come up with "The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component." But, also as stated, that's inapplicable to the application I am developing.

I don't know why that would be applicable — that's indeed the source of your problem, and the intended solution is to use state.
