### ISSUE TITLE
Is any plan on designing a scopes chaining Context API like the old context did?

### ISSUE THREAD

**Issue by zheeeng** [facebook/react#12972]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Although the React 16 new Context API solved many pain points of the old unsafe Context API, I still wish we have an appropriate communication mechanism to access scope context. The descendant component always reads a context value from its closest ancestor's context value.

**What is the expected behavior?**

Have another new Context API support context scopes chaining/cascading, components read context from bottom to up, and contexts could be shadowed by any components. This API also prevent the old Context API (React 16- ) issues (e.g. update blocking).

A reasonable situation is like:

```jsx
<Layout theme="primary">              // primary
    <Header>                          // primary
        <Button />                    // primary
    </Header>
    <Main>                            // primary
        <Button theme="warning" />    // warning
    </Main>
    <Footer theme="danger" >          // danger
        <Button />                    // danger
    </Footer>
</Layout>
```

With such a Context Api,  we can have a components libarary that once setted a scoped 'theme' context, the 'theme' effects all its children. We also can use it control the scope 'size', scope 'privilege', scope 'locale', and any other scope behaviours.

**Comment by jiawang1** [comment]
hi，i supposed current context API can support your requirement. Like
     const { Provider, Consumer } = React.createContext();
 <Provider value={{ test: 1 }}>
            <Consumer>
              {({ test }) => {
                return (
                  <React.Fragment>
                    <Provider value={{ test: 2 }}>
                      <Consumer>
                        {({ test }) => {
                          return <div>{test}</div>;     
                        }}
                      </Consumer>
                    </Provider>
                    <div>{test}</div>
                  </React.Fragment>
                );
              }}
            </Consumer>
          </Provider>

**Comment by zheeeng** [comment]
@jiawang1 Thx for your awesome tip!
