### ISSUE TITLE
question re: a few lines in ReactFiberScheduler.js

### ISSUE THREAD

**Issue by nateq314** [facebook/react#12971]
**Do you want to request a *feature* or report a *bug*?**

Neither, just wanted to ask a question about the code, specifically this function in `packages/react-reconciler/src/ReactFiberScheduler.js`:

```
function computeAsyncExpiration(currentTime: ExpirationTime) {
  // Given the current clock time, returns an expiration time. We use rounding
  // to batch like updates together.
  // Should complete within ~1000ms. 1200ms max.
  const expirationMs = 5000;
  const bucketSizeMs = 250;
  return computeExpirationBucket(currentTime, expirationMs, bucketSizeMs);
}
```

The comment says "within ~1000ms. 1200ms max." (mirroring similar comments in `computeInteractiveExpiration()` directly below that function) but the code seems to indicate otherwise. Is it the comment that needs updating, or is there something I'm missing?

**Comment by gaearon** [comment]
I guess we need to update the comment. Feel free to send a PR please.
