### ISSUE TITLE
Improve error message when got unexpected object in createElement

### ISSUE THREAD

**Issue by natew** [facebook/react#12983]
feature

**What is the current behavior?**

I've been running into an edge case where a view for some reason gets an object into createElement, triggering this error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object
```

Unfortunately, I'm finding it really hard to debug. If I set "break on errors" for some reason it's not breaking. Perhaps this is some other bug with my setup (using chrome remote debugger + componentDidCatch), but I think this area could be improved a lot by outputting the object it got.

It's unfortunate there's no good way to log out an object in an error without doing hacky stringify things. But that would certainly have saved me a lot of time over the years using React, as I've run into this type of error a few times.

Ideal would be just to log out a warning in dev mode, before the error throws, with something like:

```js
console.warn('React is about to throw an error due to an invalid property passed to React.createElement. Property is:', object)
```

**Comment by aweary** [comment]
@natew if you're using componentDidCatch, the second argument is an object with a `componentStack` property. This has a stack trace of components, which is useful for locating the source errors like this.

>Unfortunately, I'm finding it really hard to debug. If I set "break on errors" for some reason it's not breaking. Perhaps this is some other bug with my setup (using chrome remote debugger + componentDidCatch), but I think this area could be improved a lot by outputting the object it got.

"Pause on exceptions" won't work here because of how React handles failures during reconciliation. Even if it did work, it would pause inside React's scheduler which wouldn't be helpful at all.

Using `componentDidCatch` is the best way to handle debugging errors like this.

**Comment by anthonydelgado** [comment]
👍

**Comment by natew** [comment]
@aweary thank you.

Ah my stack was saying just the name of the root view, which I didn't realize meant any one of the children it was returning in it's fragment:

```
class View {
  render() {
    return <>
      <SomeChild />
      <SomeOtherChild />
    </>
  }
}
```

The stack basically says "it happened somewhere in View" which I didn't know meant "it happened exactly at the root of View". Further I guess specifying the index perhaps would have helped, but either way it's not the worst thing, glad it's clear now.

**Comment by aweary** [comment]
Glad that helps! The component stack is pretty accurate when it comes to reporting where an error occurred. The component named at the top of the stack is almost always the component that's throwing the error. If not, start there and work your way down.
