### ISSUE TITLE
When "getDerivedStateFromProps" is invoked on Update phase?

### ISSUE THREAD

**Issue by wzup** [facebook/react#12982]
**Do you want to request a *feature* or report a *bug*?**

Question about lifecycle of `getDerivedStateFromProps`

**What is the current behavior?**

Docs says:
> _`getDerivedStateFromProps` is invoked right before calling the render method, both on the initial mount and on subsequent updates._ 

But diagram shows this:

![react-diagram-](https://user-images.githubusercontent.com/3880497/40988202-294c9bda-68f3-11e8-8496-69163fe2c48f.png)

**What is the expected behavior?**

This is exactly the question. Before `reder` or before `shouldComponentUpdate`?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React Hot Loader version: `^4.2.0`
React: `16.4.0`
node -v: `v8.9.4`
npm -v: `5.6.0`
Operating system: `Ubuntu 16.04.4 LTS xenial`
Browser and version: `Chrome Version 63.0.3239.132 (Official Build) (64-bit)`

**Comment by gaearon** [comment]
The diagram is wrong. (It was made based on a buggy version unfortunately.)

With React 16.4.0 the expected behavior is for `getDerivedStateFromProps` to fire in all cases before `shouldComponentUpdate`.

**Comment by Benjamin1308** [comment]
by "in all cases", did you mean getDerivedStateFromProps get fired even when we locally change state without receiving any new props?
