### ISSUE TITLE
componentWillUpdate discussion

### ISSUE THREAD

**Issue by laynef** [facebook/react#12986]
**Do you want to request a *feature* or report a *bug*?**

Feature : componentWillUpdate Discussion

**What is the current behavior?**

The current behavior calls the function before re-rendering the render target however there is no indication for when the re-render method should be called

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

The expected behavior should call the function before re-rendering the render target if there is no returned conditional statement and if there is, true should trigger the re-render and false should not

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.4.0

I have a few questions before I try to solve this problem and it gets rejected. I'm assuming that the team has decided to move in the direction of removing "Will-Updates" from React all together and have labeled them "Unsafe". I've seen a lot of issues with those functionalities before as well. I was curious if providing a conditional statement inside those functions would satisfy the unexpected renders. "shouldComponentUpdate" does trigger when to call these functions however in those functions that "will" run before the render can always be controlled with a conditional statement of it's own. I'm getting comfortable with the code base however I'm curious if the team is removing that functionality all together and using the "static" function "getDerivedStateFromProps" instead. Has a React lover it is a little confusing and may break a lot of legacy code when updating versions. I believe that may solve the problem of unexpected renders after a "will" change lifecycle event.

I was curious if that was the case, and removing "will" lifecycles is the next steps for React then how will the "did" lifecycles work instead?

I love React and I'm just curious about the future for React as a whole. I'd love to tackle any bugs or feature requests when I have time. I will be writing clean code and create tests for new features or bugs as well.

**Comment by laynef** [comment]
I have been curious about this personally because I prefer to focus less on state and more on props. This brings back the appropriate page source for myself with server side React on initial renders when the initial state is not the same

**Comment by gaearon** [comment]
Can you condense this into a more specific question (or a few)? I'm struggling to understand what it is you're asking. No, expanding the contract of `componentWillUpdate` to let it return a value won't solve problems for us.

**Comment by laynef** [comment]
How should I best be using lifecycles if `componentWillUpdate` or `componentWillReceiveProps` are going to be deprecated?

**Comment by whs-dot-hk** [comment]
https://github.com/facebook/react/blob/c5a733e1e3ffa74bc6bbc769f1b13ecff9915763/packages/react-dom/src/__tests__/ReactComponentLifeCycle-test.internal.js#L47-L57
