### ISSUE TITLE
trigger parent function from nested child

### ISSUE THREAD

**Issue by murthybr** [facebook/react#12990]
Hello Team
I am getting up to speed on react. Have a following query: 

We have Parent Component with a Child. the child has an another child component. The structure is Parent component >1st leve Child Component (Test1)>2nd level Child Component(Test2).
with in parent component have a call back function   handler=()=> {this.setState({messageShown: true});}
passing the handler function as prop to child :<Test1 action={this.handler}/>. Wiithin Test1 there is child component <Test2>. Within the Test2 component, there is a button. is there any way to trigger the Parent function :handler() from the Test2 Component.
Anypointers would be great

**Comment by TMonika** [comment]
Yes you can. 
Example:
```
class Parent extends Component {
    _handler() {
        this.setState({messageShown: true});
    }
    render() {
        return(
           <Child1 handler={ this._handler } />
        );
    }
}

class Child1 extends Component {
    render() {
        return (<Child2 handler={ this.props.handler } />);
    }
}

class Child2 extends Component {
    render() {
      return (
         <button onClick={ this.props.handler } >Click me</button>
      );
    }
}
```
All we need to do is pass on the props and use them wherever required.

**Comment by murthybr** [comment]
thanks.
