### ISSUE TITLE
Access SSR rendered markup for component

### ISSUE THREAD

**Issue by tavurth** [facebook/react#12992]
**Do you want to request a *feature* or report a *bug*?**
I'd like to request a feature: Access SSR rendered markup for component.

I'm working on a custom pagination `HOC`. 
This `HOC` can be rendered on the server side, and should then be dynamically connected on the client.

For example, the SSR sends me this markup:
```html
<div data-pagination-hash="provider:categories:${hash}" data-provider-name="CategoryProvider">
```

And I want to grab those `data-attributes` in order to hydrate my pagination component with websocket.
Once I've got the hash I can perform a quick query to the server to connect my component to websocket pushes.

However when calling `ReactDOM.findDOMNode(this)` in `componentDidMount` I see this:

```html
<div data-provider-name="CategoryProvider">
```

This is because the component renders first without pagination information and lazy loads it in.

I solved this issue by creating a list of hashes on the server, and sending them to the client in a `<script/>` blob, but this seems a little unwieldy and could be far simplified if one was able to access the `data-attributes` from the SSR rendered markup.

I'd like to propose that calling `ReactDOM.findDOMNode(this)` in `componentWillMount` should return the SSR rendered markup (if any).

**Comment by gaearon** [comment]
>I solved this issue by creating a list of hashes on the server, and sending them to the client in a <script/> blob, but this seems a little unwieldy and could be far simplified if one was able to access the data-attributes from the SSR rendered markup.

That sounds like a good solution. I disagree your proposed solution is simpler — it encourages client and server markup to diverge and then we can't tell if it's intentional or not.

Regardless, if you'd like to propose an API change, you can do it here: https://github.com/reactjs/rfcs

Thanks!
