### ISSUE TITLE
Explanation on why React is behaving weird when combining setState with animation of scrollLeft of container

### ISSUE THREAD

**Issue by NearAutomata** [facebook/react#12991]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
In an application I am currently developing I have multiple cards in a carousel that can be scrolled card by card. Those cards themselves can have overflowing content and have scrollbars in that case. Unfortunately though, depending on the number of cards and content I have an issue wherein scrolling the mousewheel does not scroll the card content after scrolling through the carousel. One such manifestation of the bug is shown in this gif:

![xldwovv](https://user-images.githubusercontent.com/32624319/41091846-d3dd4d1a-6a47-11e8-9570-cf30a1811673.gif)

I can scroll the card content, move forward and back and all of a sudden the second card content cannot be scrolled anymore. When moving the mouse outside of the carousel and back (without actually clicking) it works again.

At times it felt as if React/the browser thinks the card is still at its old place and thus doesn't perform the default behavior when trying to scroll, that is relaying the default scroll behaviour to the card itself.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

A MWE repo can be found here: https://gitlab.com/NearAutomata/react-scrolling-mwe
Please use `npm install && npm run build` and open the `Index.html` in the `Build folder to check that issue for yourself. In Chrome and Electron the behaviour seen in the gif is occuring to me.

---

The corresponding block in the source file with the issue is here: https://gitlab.com/NearAutomata/react-scrolling-mwe/blob/master/Source/Components/Launcher.tsx#L228-230

In the first iteration of my code when clicking on the button I was calling `setState` then the `scrollTo` animation. React apparently expects the old coords of the elements. To my surprise `setState({ ... }, () => { scrollTo(...); })` did not work either. I expected the animation to be called right after React updates and re-renders everything. Conversely, adding a callback to my animation like `scrollTo(..., () => { setState({ ... }); })` seems to work to prevent any internal mismatch of positions.

I'd like to know whether you can explain why the second variant with `setState({ ... }, () => { scrollTo(...); })` isn't working as expected and why React is having issue with scrolled elements.

**Comment by whs-dot-hk** [comment]
@NearAutomata I can scroll here

**Comment by NearAutomata** [comment]
@whs-dot-hk Which browser do you use? In Chrome / Electron I get this issue. Surprisingly Edge does not cause the issue.

**Comment by whs-dot-hk** [comment]
@NearAutomata I was using FF. It also works in Chrome here.

**Comment by NearAutomata** [comment]
I just tried it again on Windows and macOS. On my Mac it didn't work with Chrome 66.0.3359.181 but it worked with 67.0.3396.79. On Windows though it still does not work at all.

@whs-dot-hk Which OS are you using? And have you payed attention to not move the mouse out of the carousel area?

**Comment by whs-dot-hk** [comment]
@NearAutomata I don't understand, your code is about Carousel scrolling, why it would affect the scroll of a div?

**Comment by NearAutomata** [comment]
@whs-dot-hk Ah there is the misunderstanding. In fact my carousel scrolling works, but my issue is that the content of the "Breaking News" card cannot be scrolled after scrolling the carousel back and forth. That is why I am glitching around my mouse in the gif because I try to scroll inside the card after moving the carousel back.

**Comment by VideoCasino** [comment]
Hi I'm sorry to know your system is not function well.

It sounds like a upgrade issue, try upgrading your system and do a system
restart, the issue still occur try doing a factory reset.

I hope go as well

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
