### ISSUE TITLE
Should i maintain data of component in it;s own state or with redux for complex enterprise applications

### ISSUE THREAD

**Issue by CaptainSadaf** [facebook/react#13004]
Suppose i have four components for one screen or container. component A, component B, component C, component D and four developers are working on four components.

First approach which i can follow is that maintaining the data within own state of component.
2nd approach with redux, i will created reducer for each component and maintaing the data of component with redux.and when i need to send the combine data of all components,simply will combine reducers and send it over server api
What approach should i follow?

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by CaptainSadaf** [comment]
ok thanks
