### ISSUE TITLE
React tracks scroll position internally and forces synchronous layout

### ISSUE THREAD

**Issue by steadicat** [facebook/react#1300]
React adds a scroll listener that tracks and caches the scroll position (I assume for some undocumented internal purpose). Additionally, the scroll listener forces a synchronous layout (see screenshot). This seems wasteful, especially considering that the values tracked are never exposed in the API.

What is the scroll listener used for? Can it be removed?

![screen shot 2014-03-24 at 3 11 09 pm](https://f.cloud.github.com/assets/6031/2506088/446c708a-b3a2-11e3-9aa3-4b6af531a4a0.png)

**Comment by michalzubkowicz** [comment]
This issue causes React based longer lists unusable on mobile.

**Comment by lo1tuma** [comment]
Is there any progress on this issue? I’m not sure if this is the root-cause for pages rendered with react scrolling extremely slow with firefox mobile on android (e.g. this react website http://isomorphic500.herokuapp.com/featured/highest_rated).

**Comment by spicyj** [comment]
@lo1tuma Is that your site? If so, you can try commenting out the logic in refreshScrollValues to see if it makes a difference. If it does, I'm happy to prioritize @syranide's #2271 and try to get it in.

**Comment by lo1tuma** [comment]
@spicyj No, that is not my site, it is an example react & fluxible page (see: https://github.com/gpbl/isomorphic500), but we have exactly the same issues with scrolling on firefox mobile.
I’ve applied the changes in #2271 manually and it doesn’t solves the problem, so this issue might be unrelated to my problem. I will investigate further.
Thanks for considering to prioritize this. Much appreciated.
