### ISSUE TITLE
Error because of missing key

### ISSUE THREAD

**Issue by ghernando** [facebook/react#13005]
I'm using Gatsby and am new to both Gatsby and React.
I'm seeing the following warning and would like to remove it.  I've read about the key, and I am trying to apply it, but it doesn't work.

Warning: Each child in an array or iterator should have a unique "key" prop.

> Check the top-level render call using <CardGroup>. See https://fb.me/react-warning-keys for more information.
>     in Unknown
>     in Unknown (created by ComponentRenderer)
>     in ComponentRenderer (created by Route)
>     in Route (created by DefaultLayout)
>     in div (created by DefaultLayout)
>     in div (created by SidebarPusher)
>     in SidebarPusher (created by DefaultLayout)
> ...

**MyPage.tsx**
This is the main page.  It passes a value of slug obtained from GraphQL.

    export default(props: CardProps) => {
    const mycards = props.data.frontmatter.edges
         .map(({ node }) => {
            const Logo = node.frontmatter.image.children[0] as ImageSharp;
            return (
            <MyCard slug={node.fields.slug} />
          );
       }) ;
    
        ...
        return(
          <Container>
              <Card.Group itemsPerRow={3} stackable={true}>
                   {mycards}
              </Card.Group>
           </Container>
        );
     );

**MyCard.tsx**
This is where the key is specified on the card

     interface CardProps extends React.HTMLProps<HTMLDivElement> {
       slug: string;
     }
    
     export default ({slug}: CardProps) => {
       return (
           <Card key={slug}>
             <Card.Content>
               <Card.Header>
    ...
             </Card.Content>
           </Card> 
        );
     );

**Comment by aweary** [comment]
@ghernando you're applying the key to the `Card` component, which is a child of `MyCard`. You need to apply the key to the `MyCard` component that's being mapped to.

```jsx
<MyCard key={node.fields.slug} />
```

For future reference we use the issue tracker for bug reports and feature requests only.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
