### ISSUE TITLE
React depends on an older version of core-js, breaking the usage with the new babel

### ISSUE THREAD

**Issue by marcofugaro** [facebook/react#13018]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
React is relying on an older version of core-js which goes in conflict with the newer beta version of babel.

![image](https://user-images.githubusercontent.com/7217420/41241516-6c02a24a-6d9d-11e8-8e64-dfc9e6d991e9.png)

The older version gets installed instead of the newer, so it results in errors like 

![image](https://user-images.githubusercontent.com/7217420/41241713-fcca62d6-6d9d-11e8-8ddc-5b7dcb55a0af.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v16.4.0

**Comment by gaearon** [comment]
React doesn't really "depend" on core-js in practice for anything. It's true that it's in a dependency tree (which is kinda unfortunate) but we don't end up using any of its modules.

So React can't possibly break your app with this. If you're seeing some kind of conflict it probably means your package manager has a bug, and incorrectly hoists a package version.

**Comment by marcofugaro** [comment]
So it's a yarn issue? I don't really know how hoisting works, but I will provide a basic reproducible repo and submit the issue there

**Comment by gaearon** [comment]
I can't tell for sure—your screenshot doesn't show who's attempting to import that module

**Comment by marcofugaro** [comment]
That's the package.json, the root of the project.

I tested it in isolation both with yarn and npm, and the behaviour is different. Npm installs correctly the updated dependency, whereas yarn gives precedence to the 1.x one.

Will make a repo and submit the issue at yarn, hopefully they will look into it.

**Comment by gaearon** [comment]
I don't understand what you're saying.

I'm asking which package is attempting to load `core-js` (and is failing).

**Comment by marcofugaro** [comment]
Sorry, it's `@babel/polyfill` with the flag `useBuiltins: 'usage'` after using some async iterators. 

Async iterators are present only in core-js v2.x.x.

**Comment by gaearon** [comment]
So you're saying `@babel/polyfill` depends on `core-js` in its `package.json` but didn't get `node_modules/core-js` with the version it expects?

**Comment by marcofugaro** [comment]
Yup, only using yarn. 

After doing `yarn init -y; yarn add babel-preset-accurapp react`, I checked the core-js version in the node_modules manually (the package.json) and it's the 1.2.7.

**Comment by gaearon** [comment]
The version in the top level folder is not necessarily what matters. What matters is that following Node resolution algorithm (`./node_modules`, then `../node_modules`, then `../../node_modules`, then `../../../node_modules`, and so on) **from where the package is imported** gives you the right version.

Tools like npm or yarn can choose to put a package to `node_modules` folder above but as long as it doesn't break other expectations, this shouldn't matter.

Looking at your reproducing example, the version I get from `@babel/polyfill/node_modules/core-js` is 2.x. So the package manager didn't do anything wrong. **As long as the require itself is inside `@babel/polyfill`, everything should work.** And if it's not, why does a `require` exist without an explicit dependency?

**Comment by marcofugaro** [comment]
Thanks for your time investigating this @gaearon!

Yup, you're right, not an issue with yarn.

It turns out, **the require is outside of `@babel/polyfill`**. Basically what babel does, [as described in the docs](https://new.babeljs.io/docs/en/next/babel-preset-env.html#usebuiltins), it transforms this

```js
var b = new Map();
```

into this

```js
import "core-js/modules/es6.map";
var b = new Map();
```

so the `core-js` import is actually done from your application!

Babel then tells you to add `@babel/polyfill` to your dependencies, so that core-js gets installed also, but when you have other dependencies using `core-js`, the import from the application gets resolved to a different version of `core-js`, which is what I think it's happening here.

**Comment by gaearon** [comment]
That makes sense 👍

**Comment by marcofugaro** [comment]
For now I solved It by adding `core-js` also as a dependency of `babel-preset-accurapp`.

**Comment by gaearon** [comment]
You probably want it as a peer dependency instead.

**Comment by gaearon** [comment]
Or, rather, you want `@babel/polyfill` as a peer dependency. Thus forcing the user of the preset to install the correct version.

**Comment by sergej-s** [comment]
@marcofugaro How did your print the dependency tree so nicely? :)
