### ISSUE TITLE
map function error

### ISSUE THREAD

**Issue by murthybr** [facebook/react#13014]
Hello Team
We have json as follows Products = [{id: 2,Product Name: 'Tomato',  Qty UoM: "1.00MT"} ]. When map function is used to iterate the values {products.Qty UoM} giving an error. The space in Qty UoM. i tried {products."Qty UoM"} still error. Is there any other option to access the values. 
any pointers would be great.
thanks

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
