### ISSUE TITLE
Refs in listener - can't scroll ScrollView (react-native - Android)

### ISSUE THREAD

**Issue by MateuszBucko** [facebook/react#13010]
I've got proximity sensor, and listener added like:

```
       componentDidMount() {
           Proximity.addListener(this._proximityListener);
       }

    _proximityListener(data) {
        this.state = {distance: data.distance}
    }

```

and ScrollView

`<ScrollView ref="scrollView">...</ScrollView>`

i'm trying to scroll down list on proximity but i can't get refs in listener, it's undefined, i'm trying something like this: 
`this.refs.scrollView.scrollTo(0,5);`

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests for React core.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

If you believe this is a bug with React Native, you can open an issue at [facebook/react-native](https://github.com/facebook/react-native). Just be sure to provide all the requested information 🙂
