### ISSUE TITLE
Make React.createClass warn/throw if mixins contains undefined value

### ISSUE THREAD

**Issue by andreypopp** [facebook/react#1302]
Code below could be a result of a typo in a mixin name or an attempt to use a mixin from a module which has no `module.exports` (by a mistakte).
```
var Component = React.createClass({
  mixins: [undefined],
  ...
});
```
It would be nice if React can warn/throw on such condition.

**Comment by Pomax** [comment]
Just to bump: this is still super useful, and we could have really done with this today =)

**Comment by jimfb** [comment]
We had a PR to fix this (https://github.com/facebook/react/pull/1305), but decided to abandon it as per https://github.com/facebook/react/pull/1305#issuecomment-99318251.  Mixins are mostly legacy and we aren't really adding things to them.

Recommended reading: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.nyku5vbmg
