### ISSUE TITLE
React props: Unable to access key in object in array with index both passed with props

### ISSUE THREAD

**Issue by chikarao** [facebook/react#13025]
I am working on a React project in which I am trying to access a key in an object that is an element in an array using an index, but am getting undefined.

The issue seems to be that I am getting an array of objects as props and the index as props as well. When I try to access the id or publicid of the objects in the array using an index from props, I get the error. Below is the simplified version of what I am getting.

Why is this happening and how can I resolve this?

console.log(this.props.images);
// [{id: 1, publicid: "1234" }, {id: 2, publicid: "5678"}]

console.log(this.props.imageIndex)
// 0

console.log(this.props.images[0].publicid)
// 1234

console.log(this.props.images[this.props.imageIndex])
// {id: 1, publicid: "1234" }

console.log(this.props.images[this.props.imageIndex].publicid)
// Cannot read property 'publicid' of undefined

**Comment by bsheikh** [comment]
Hey @chikarao, since `imageIndex` is a prop, make sure it's not getting updated by it's parent component/container and the value is still `0`. Also check the type of `imageIndex` and make sure no coercion is happening.

Although this isn't related to the question, you can clean the code up a bit by doing the following:
```
const { images, imageIndex } = this.props;
```

Cheers!

**Comment by chikarao** [comment]
Okay, thanks. I ended up checking for emptiness of images prop and it worked fine. ImageIndex was apparently being updated before images.

**Comment by bsheikh** [comment]
Glad you figured it out, cheers!
