### ISSUE TITLE
suggest: `componentDidMount` return `componentWillUnmount`

### ISSUE THREAD

**Issue by xp44mm** [facebook/react#13026]
building function return disposal function is a common usage in a lot of API, for example in `rxjs`:

```javascript
Rx.Observable.create(observer => {
    let timeoutId = setTimeout(...);
    return () => {              
        clearTimeout(timeoutId);
    };
});
```

so suggest `componentDidMount` return `componentWillUnmount`

```javascript
export class XX extends React.Component {
    componentDidMount() {
       let timeoutId = setTimeout(...);
             
       return function componentWillUnmount() {
           clearTimeout(timeoutId);
       }
    }

}
```

otherwise, the `timeoutId` will must be augment scope to instance member `this.timeoutId`. the code is:

```javascript
export class XX extends React.Component {
    componentDidMount() {
       this.timeoutId = setTimeout(...);
    }
    
    componentWillUnmount() {
       clearTimeout(this.timeoutId);
    }
}
```

**Comment by gaearon** [comment]
This is an interesting direction, but it would introduce a lot of churn to the class API, and doesn't solve the composability issue (which is what Rx, for example, does).

We have some other ideas on how to make these use cases easier which we'll share when they're more fully formed. Thanks!
