### ISSUE TITLE
Child component constructor is called multiple time

### ISSUE THREAD

**Issue by hiteshbhatt** [facebook/react#13039]
Child component constructor is called multiple times. when changing state. It is not  rerendering but force updating. but I am not forceupdating anywhere. I have upgrade to react 16 then this is happening.

**Comment by gaearon** [comment]
We can't help without a reproducing example.

**Comment by TEJAPS** [comment]
Yes 
i faced the same kind of situation 
what wrong thing i did was  - assigning new value to state variable as follows:
this.setState({
this.state.var_name = new_value
)}

correct form is:
this.setState({
var_name = new_value
)}

their might be other reasons as well, your code is required for resolving in specific...

**Comment by gaearon** [comment]
I’ll close because it’s not clear what the issue is from the description.

**Comment by rabbitmeow** [comment]
It appears randomly

**Comment by rabbitmeow** [comment]
So I'm afraid of do some initializations in constructor, it could cause some unexpected errors.

**Comment by OZZlE** [comment]
> Yes
> i faced the same kind of situation
> what wrong thing i did was - assigning new value to state variable as follows:
> this.setState({
> this.state.var_name = new_value
> )}
> 
> correct form is:
> this.setState({
> var_name = new_value
> )}
> 
> their might be other reasons as well, your code is required for resolving in specific...

This isn't correct in any way it should be:

    this.setState({
      keyName: value,
    });

or if you need a dynamic key

    this.setState({
      [keyName]: value,
    });

**Comment by Torinjsdoc38** [comment]
> > Yes
> > i faced the same kind of situation
> > what wrong thing i did was - assigning new value to state variable as follows:
> > this.setState({
> > this.state.var_name = new_value
> > )}
> > correct form is:
> > this.setState({
> > var_name = new_value
> > )}
> > their might be other reasons as well, your code is required for resolving in specific...
> 
> This isn't correct in any way it should be:
> 
> ```
> this.setState({
>   keyName: value,
> });
> ```
> 
> or if you need a dynamic key
> 
> ```
> this.setState({
>   [keyName]: value,
> });
> ```
> 
> [@TEJAPS](https://github.com/TEJAPS)





https://clientid-ravenous.github.io/VzXmBkmmQLtdMra8QE2D9UqEWgE/
