### ISSUE TITLE
What is Fabric?

### ISSUE THREAD

**Issue by blling** [facebook/react#13032]
I found same issue mentioned `Fabric`.

So:
What is Fabric?
What is The difference between Fabric and Fiber?

**Comment by kierenj** [comment]
A quick Google search found me this - https://react-fabric.github.io/

**Comment by gaearon** [comment]
I think this question is about commits on RN repo.

Fabric is an experimental rewrite of some core pieces of React Native architecture with a goal of improving threading model and interop with native code.
