### ISSUE TITLE
Does styling affect React's way of re-rendering?

### ISSUE THREAD

**Issue by ximbong91023** [facebook/react#13035]
```
const Title = ({ length }) => {
  return (
    <div >
      <span>Number of coins on the list:</span>
      <span>{length} </span>
    </div>
  );
};
```

![image](https://user-images.githubusercontent.com/23175345/41339960-dff34c6a-6efe-11e8-8402-47c139725a23.png)

If the dynamic data changes, the browser re-renders both of the spans.

![image](https://user-images.githubusercontent.com/23175345/41339781-62949364-6efe-11e8-8640-d9ab8c09bdc4.png)

If the dynamic data changes, the browser re-renders only the second span, **if the spans are displayed as flex**.

I have read through the React's diff algorithm and it supposed to recurse on chilren before making changes to the changed DOM elements. But in the first image, both of the spans were re-render.

**Comment by gaearon** [comment]
How do you determine what re-renders?

**Comment by ximbong91023** [comment]
In the console, I chose More tools --> Rendering --> Paint flashing.

**Comment by gaearon** [comment]
I'll need a reproducing example to better understand your issue.
