### ISSUE TITLE
Some means of determining component order in hierarchy

### ISSUE THREAD

**Issue by kierenj** [facebook/react#13034]
I'm trying to build a container component and child component, whereby the children can sit anywhere in the hierarchy beneath the container, but know their relative order/index within that hierarchy.

My use-case is to build a helper wrapper for CSS grids, allowing subcomponents to themselves render a "row" component which knows it must be the next index, and may or may not progress the row counter for the next "row" component found in order.

I've looked into two possible avenues - recursing using `React.Children` on the component, which stops when it hits a component without `props.children` (e.g. a redux-`connect()`-ed one), and passing some means of counting via context, which fails because it seems the `render()` methods of the child components isn't always called in "DOM order".

More background here - https://stackoverflow.com/questions/50776933/react-get-component-order-within-hierarchy

It would be great to have some feature in React which might allow for this.

**Comment by kierenj** [comment]
Could be similar to https://github.com/facebook/react/issues/13036 which was just raised

**Comment by aweary** [comment]
Context should solve this use case, as you can render a Provider _within_ a Consumer that increments and updates the level/order for descendant consumers.

```jsx
const Child = () => (
  <Consumer>
     {index => (
        <Provider value={index + 1}>
            {...}
         </Provider>
     )
  </Consumer>
)
```


If you have further questions, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by kierenj** [comment]
Wouldnt that give me the depth, not the order? I.e. adjacent consumers would have the same depth?

**Comment by kierenj** [comment]
(I’m assuming if you are mistaken we can re-open this issue? or with your comment did you mean I should take this to the community resources? - unfortunately I’ve tried all of them and believe this is a gap in React functionality?)

**Comment by kierenj** [comment]
I don't mean to make a nuisance of myself, but really can't see how the proposed solution solves this. @aweary if you'll forgive the mention, is this really something where I need to go away to the community again / accept this isn't something for React?
