### ISSUE TITLE
Element property is reset when reconciled  

### ISSUE THREAD

**Issue by Dannesley** [facebook/react#13042]
**Do you want to request a *feature* or report a *bug*?**
While i'm inclined to believe it is a bug, there may be rationale behind it being expected behaviour.

**What is the current behavior?**
When there is a component that sets a value on its' underlying element via the ref, and this component is a child of another component and given a stable key, this value is reset when it is reconciled.

For example:
We have a table with horizontally scrollable rows and some custom scrollbars.
As such, the scroll offset is maintained via the ref using the scrollLeft property.
This table is also sortable.
When you sort the table, the rows are properly reconciled (no render methods are called on a row), yet the scrollLeft value is reset to 0 for the row.
_If you remove the key from the row, it works as expected._

Here is a simple case reproducing this behaviour.
https://codesandbox.io/s/q9pq7q10nw

**What is the expected behavior?**
I would have expected that the properties set on the ref would be maintained in the reconciliation process.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Version of React: 16.4 (was also the behaviour in 16.3)

**Comment by nmain** [comment]
One of the posts on https://github.com/reactjs/rfcs/pull/34 gets into this issue.  When you remove a DOM element from the tree, and then add it back to the tree, it's not guaranteed to keep certain transient properties.  In particular, the scroll state, which may have been in part a result of how flow and layout affected the element in its old location, can be reset and is often reset by browsers.

(Note that react has to remove and re-add _somebody_ to handle `key` reordering)

In this particular case, you can handle the problem with gSBU / cDU:

https://codesandbox.io/s/6yrv8pkl8r

Note that I had to change `Item` to `Component` and not `PureComponent` for this to work, so it's not optimal in other ways.

**Comment by Dannesley** [comment]
@nmain Thank you very much for the quick reply, and the links.
It is rather unfortunate in our case, but it makes sense to me now at least.
