### ISSUE TITLE
Key Event not being sent on iPad with a bluetooth keyboard

### ISSUE THREAD

**Issue by chrisgbaker** [facebook/react#13040]
Demo: https://jsfiddle.net/69z2wepo/190716/

Using the above fiddle, focusing on the `<tr>` and sending Key events correctly logs e.Key in any device aside from an iPad. However, when connecting an iPad with a Bluetooth keyboard for debugging, the only key events that seem to make it through correctly are the arrow keys. Everything else comes in as "Dead".

Note: http://jsfiddle.net/5r0enc79/17 Using this fiddle, all key events appear to be correct on the same iPad.

Version of React: 16.4
iPad: 11.3 (15E216)
Browser: Safari

**Comment by Imagine-Tom** [comment]
Look not to understand.

**Comment by chrisgbaker** [comment]
@Imagine-Tom I'm not sure what you are asking

**Comment by danburzo** [comment]
@chrisgbaker can you check here what kind of events you receive from the iPad on native DOM vs. React? https://danburzo.github.io/input-methods/ It may help shed some light on the situation.

**Comment by danburzo** [comment]
Another thing to try is read the `.nativeEvent.key` / `.nativeEvent.code` off the Synthetic Event to see if that helps.

**Comment by chrisgbaker** [comment]
@danburzo Thanks, I can check that site on Monday and update the issue accordingly. As far as the differences in the two fiddles, That was just an extension of me trying multiple methods, but the result is the same, regardless of `onKey[Up | Down | Press]`

**Comment by gaearon** [comment]
Have you managed to investigate this further?

**Comment by gaearon** [comment]
Closing since there was no follow-up.
