### ISSUE TITLE
Native Fibers

### ISSUE THREAD

**Issue by nin-jin** [facebook/react#13049]
With native fibers:
- Code of React can be dramaticaly simplified.
- Suspense API will have less limitations and more performance.

Could you support to promote [fibers proposal](https://gist.github.com/nin-jin/5408ef8f16f43f1b4fe9cbcea577aac6) to [TC39](https://github.com/tc39)? We need a champion. 🥇

**Comment by aweary** [comment]
We use the issue tracker for bug reports and feature requests. You should use a more appropriate to promote your proposal.

**Comment by nin-jin** [comment]
Do you mean this proposal is useless for React? And React dev team doesn't interesting in it?

**Comment by aweary** [comment]
Not at all. This is just the wrong place to ask for feedback or support for your proposal. You should follow the standard proposal process outlined in the document I linked. The React team is involved with TC39 and can provide feedback through the committee.

**Comment by nin-jin** [comment]
I have tried: http://logs.libuv.org/tc39/2018-06-14#21:25:04.616
