### ISSUE TITLE
Error when entering proptypes documentation

### ISSUE THREAD

**Issue by huichops** [facebook/react#13047]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Whenever I enter on this link https://reactjs.org/docs/typechecking-with-proptypes I get redirected to the `404` page.

**What is the expected behavior?**
This route https://reactjs.org/docs/typechecking-with-proptypes.html works as expected but it has the `.html` suffix.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am just joining through the actual webpage, not on my computer. 
- Firefox 60.0.2
- macOS High Sierra 10.13.4

**Comment by gaearon** [comment]
Where did you get this link?

**Comment by gaearon** [comment]
If you find it, let us know.
But please file an issue on https://github.com/reactjs/reactjs.org instead.
Thanks!

**Comment by huichops** [comment]
I am sorry for the late response.
I've got it when googling about _Proptypes_. It seems that it was a problem with google and not the docs. As of today clicking the link from the google search works as expected.
