### ISSUE TITLE
Children not updating as expected

### ISSUE THREAD

**Issue by mcjazzyfunky** [facebook/react#13052]
**Do you want to request a *feature* or report a *bug*?**
I'm not really sure whether this is a really a bug - maybe the React team could examine whether the following demo behaves as intended or not.

**What is the current behavior?**

Please check the following demo:
https://jsfiddle.net/1wvqbkp3/

It outputs the current time two times.
The first time output is updated each second.
But the second isn't.

Note: Please be aware this is just a short abstract demo to show the issue in as few line of code as possible. It's not about implementing clocks or proper state handling or proper side effect handling or setState vs. forceUpdate or React design patterns in general, etc.
Nobody wants to implement  components in this extremely ugly way - the demo is just there to show the issue without any other stuff.

**What is the expected behavior?**

I would expect the second time output to be also updated each second.
In the second line of that JS-Fiddle demo you can easily switch the UI library from 'react' to 'preact', 'inferno', 'dio' or 'nerv' to see that they behave the way I would have been expected.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v16.4.1 / Windows 10  - React 15.x behaves like the current React version

**Comment by gaearon** [comment]
React doesn't perform child reconciliation if the child element is referentially equal to the previous version.
In other words, this renders `<Button />` every time `<App />` is rendered:

```js
function App() {
  return <Button />
}
```

But this will skip updating `<Button />` when `<App />` is rendered:

```js
const button = <Button />;

function App() {
  return button;
}
```

There are two reasons why it works this way:

1. This performance optimization ends up being pretty important for components that accept `this.props.children` but have their own state (unrelated to children) like hover. It would be very wasteful to reconcile children whenever you interact with the wrapper itself.

2. This lets smart compilers give hints to React that certain elements are static (and hoist them out) to avoid rendering unnecessarily.

3. It is assumed that if you want to pass mutable data down to components, you do it via props (and thus have to create new elements on every render).

In general we don't recommend accessing globals like `Date.now()` in render and then hoping that some component above re-renders this component. Instead, you can make a component stateful, and let *it* set up an interval to update itself (if it cares about the value).

Hope this helps.

**Comment by mcjazzyfunky** [comment]
@gaearon Thanks a lot for your (as always) detailed and very helpful answer.
