### ISSUE TITLE
Use getDerivedStateFromProps cause this.props not update in render and componentDidUpdate

### ISSUE THREAD

**Issue by Yibay** [facebook/react#13051]
Bug: Use getDerivedStateFromProps cause this.props not update in render and componentDidUpdate

**What is the current behavior?**

// 1: use static getDerivedStateFromProps, this.props won't update in render and componentDidUpdate

// 2: use componentWillReceiveProps, this.props can update in render and componentDidUpdate

**What is the expected behavior?**

use static getDerivedStateFromProps, this.props also can update in render and componentDidUpdate

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

"react": "^16.4.0" and "react": "^16.3.1"
Chrome v67.0.3396.87

**Comment by Avi98** [comment]
@Yibay  in static method you cant use this

**Comment by Yibay** [comment]
I use getDerivedStateFromProps(){} cause this.props in render(){}, componentDidUpdate(){} won't be updated anymore. but getDerivedStateFromProps(nextProps){ /* nextProps can update */ }. I hope render(){/* this.props can update */}, componentDidUpdate(){/* this.props can update */} too.

**Comment by milesj** [comment]
Hard to understand your problem. Can you provide a code example?

**Comment by gaearon** [comment]
Please provide a code example that we could run. It's not clear what you're asking.

**Comment by rmsheppard** [comment]
I had a similar situation with getDerivedStateFromProps not working.  Being as it is company code I can't share that code but I will explain what I was seeing.

I had a parent component which had a state change which in turn passed that along to it's child component.  A bool value was passed.  Adding the getDerivedStateFromProps on the child component caused the child to not update anymore whenever the new prop values were passed in from the parent.  The value being passed in had nothing to do with anything set in the getDerivedStateFromProps method.

Removing the getDerivedStateFromProps method from the child allowed it to start seeing the updated props passed to it.

**Comment by michael-ecb** [comment]
same issue... when updating from 16.3.2 to React 16.4.2

**Comment by gaearon** [comment]
Sorry, even if there's a bug there is just no way we can fix it if somebody doesn't provide a reproducing example. I'm going to lock this to discourage further "me too" comments which aren't helpful. **If you have this problem please file a new bug with a reproducing example so we can fix it.** Thanjks!
