### ISSUE TITLE
Really like Vue's solution for css, how about a similar one like this for React?

### ISSUE THREAD

**Issue by FateRiddle** [facebook/react#13059]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
So I really like Vue's solution for css, how about a similar one like this for React?
```js
// App.js
import Scoped from "scoped-css"
import style from "./App.css"

const App = () =>
<Scoped style={style}>
   <div className="App">
        <div className="header">
          <h2>Welcome to React</h2>
        </div>
        <p className="intro">
          To get started...
        </p>
      </div>
</Scoped>

//App.css
.App { ... }
.header { ... }
.intro { ... }
```
CSS will apply to elements of the current component only, and parent component's styles will not leak into child components.

**Comment by loryman** [comment]
I think that [styled-jsx](https://github.com/zeit/styled-jsx) and [CSS Modules](https://github.com/css-modules/css-modules) already achieve what you're thinking of.

**Comment by milesj** [comment]
Or Aesthetic if you prefer a css-in-js approach (self-plug): https://github.com/milesj/aesthetic

**Comment by Kovensky** [comment]
The Vue approach is a bit different and would actually need some kind of internal support to work, but it's probably nothing that a Babel transform cannot do.

Basically, they add a `data-{somehash}` key to every single DOM element that is generated from the `<template>` in a file that has a `<style>`. The classes in the `<style>` are modified to require that `[data-{somehash}]` attribute to be present to match.

As far as I know this is not recursive and will not affect the DOM elements generated by other components; if it were, it would only be implementable in core.

**Comment by NE-SmallTown** [comment]
https://github.com/gajus/babel-plugin-react-css-modules ?

**Comment by nhunzaker** [comment]
Thanks everyone for replying with helpful resources!

If there's a change to React that you think would improve styling, please consider filing a proposal at the [React RFCs](https://github.com/reactjs/rfcs) repo. In the mean time, I'll close this out.

**Comment by PraveenAsh** [comment]
This could be a little challenging to implement.
it will be great if it is something like this,
`restricted import './style.css'` in Component.js.
All the class names in the dom also being virtually named with a scope in reference.

**Comment by stephan-v** [comment]
Is there currently no solution that allows global and scoped styles to be applied? Vue just adds a data- attribute and leaves the classname untouched. Scoping the classname by modifying it destroys the ability to use global styles (like grids, etc.).

**Comment by mwoz123** [comment]
I've just found https://kremling.js.org 
IMO it seems be the most Vue-like lib for react as css can be scoped and placed inside jsx (without external .css file)
Maybe it will be usefull for someone.

**Comment by isumix** [comment]
Take a look at https://github.com/sgtpep/csstag
It is framework agnostic and can be compiled to css in production.
It is also based on https://github.com/css-modules/css-modules which is all I need these days)
