### ISSUE TITLE
Error while creating a new application 

### ISSUE THREAD

**Issue by eniniz** [facebook/react#13064]
I'm trying to get started with react, I run `npm install -g create-react-app`, then when I run : `create-react-app my-app`  I get this error : 
`npm ERR! Unexpected end of JSON input while parsing near '...,"xml-name-validato
r"'`
what should I do ??

**Comment by deecewan** [comment]
What version of node are you running? I have just run this under node 10 (inside docker, `node:alpine` with `docker run -it node:alpine /bin/ash`), and it worked perfectly as expected.

Also, this issue should probably be in facebook/create-react-app

**Comment by aweary** [comment]
Please check our community support resources before filing an issue:
https://facebook.github.io/react/community/support.html

and as @deecewan said, if you do find that this is a bug this should be filed in the create-react-app repo.
