### ISSUE TITLE
Minor: constructor name for SyntheticEvent subclasses

### ISSUE THREAD

**Issue by danburzo** [facebook/react#13063]
This is a risibly minor issue, but I wanted to bring it up in case there's a super easy fix to it. In older versions of React, doing `e.constructor.name` on synthetic events would report the constructor class' name, but right now it reports a generic `Class`, due to the way SyntheticEvent is extended:

https://github.com/facebook/react/blob/ae14317d6810d5b07d01308a2116a707e5e09983/packages/events/SyntheticEvent.js#L219-L238

I'm in the process of bringing this small tool up to date, and I've upgraded from React 15.4 to React 16.4, and I get lots of `Class` logs:
https://danburzo.github.io/input-methods/

(The workaround is to just assume Class = some subclass of SyntheticEvent, but it would be nice to have a more precise name?)

**Comment by deecewan** [comment]
that is annoying. I wonder why it's not just extended as usual?

**Comment by aweary** [comment]
Is there a specific reason you want to report the constructor name? Those are an implementation detail.

**Comment by danburzo** [comment]
It's just to have this little tool to help debugging UI Events inside a React contenteditable, which is pretty useful to figuring out how to debug things like rich-text editors that work well across devices. (e.g. weird behaviors like #13040 or various IMEs like autocorrect). It's really not a significant issue, it's just a tiny thing that used to work.

**Comment by aweary** [comment]
How does having the synthetic event's construct name help debugging? I'm curious what value it provides over just using the event type.

If you really wanted to report the constructor name you could just manually map event types to their corresponding constructor. This rarely changes, if ever.

**Comment by gaearon** [comment]
>I'm curious what value it provides over just using the event type.

`e.nativeEvent.constructor.name` might also be helpful unless you're specifically debugging React itself

**Comment by danburzo** [comment]
Yes, I'm actually showing that as well [here]( https://danburzo.github.io/input-methods/) (the native event that originated the synthetic one). It was just a bit of extra info (to know what to search for in the React codebase), but I can live without it — I just wanted to hear an opinion about it :) Thank you both! I realize this would be of next-to-last priority. (I can also recreate [this mapping](https://github.com/facebook/react/blob/49979bbf521102d0fb55c77323bcec6fd6871a03/packages/react-dom/src/events/SimpleEventPlugin.js#L224-L303))

**Comment by gaearon** [comment]
If there’s an easy fix we’re happy to merge. I haven’t looked at the problem.

**Comment by danburzo** [comment]
If anything easy comes to mind, I'll make a PR, thank you!
