### ISSUE TITLE
Can't edit the wiki page

### ISSUE THREAD

**Issue by VinayakBagaria** [facebook/react#13067]
**Do you want to request a *feature* or report a *bug*?**
Bug on the wiki page

**What is the current behavior?**
Cannot edit the wiki page as permission is not given.

Go to https://github.com/facebook/react/wiki/Sites-Using-React and click `edit this page!` link.

**What is the expected behavior?**
Gives some way to edit the wiki or make a pull request to do so.

**Comment by anvaynk** [comment]
+1

**Comment by alex-olivera** [comment]
+1

**Comment by gaearon** [comment]
I think we locked it because it was used for spam. Maybe we should just remove this page or move it somewhere.

**Comment by VinayakBagaria** [comment]
Maybe the team can accept pull requests to websites and verify it using the dev tools of React to ensure no spamming.

**Comment by aweary** [comment]
At this point I'm not sure there's a lot of value in maintaining an "official" list like this. It's great to showcase our users, but this page has little visibility and has gotten so long that it doesn't really serve as a great showcase anymore.
