### ISSUE TITLE
map render not working

### ISSUE THREAD

**Issue by Deboracgs** [facebook/react#13070]
Hi, i not hava any ideia, the map not render, but the console.log is working.

```
`return (
      <div>
        {this.state.officeHours.map((value, index) => {
          console.log("value", value.description);
          return
            (
              <FormGroup row key={index}>
                <Col sm={12}>
                  <Row>
                    <Col sm={4}>
                      <Row>
                        <Col sm={6}>
                          <IntlMessages id={value.description} />
                        </Col>

                        <Col sm={6}>
                        </Col>

                      </Row>
                    </Col>
```

                    <Col sm={2}>
                      <Row>
                        <Col sm={6}>
                          <InputSelect
                            options={[]}
                          />
                        </Col>

                        <Col sm={6}>
                          <InputSelect

                          />
                        </Col>
                      </Row>
                    </Col>

                    <Col sm={2}>
                      <IntlMessages id="label.secondRound" />
                    </Col>

                    <Col sm={2}>
                      <IntlMessages id="label.thirdRound" />
                    </Col>

                    <Col sm={2}>
                      <IntlMessages id="label.fourthRound" />
                    </Col>
                  </Row>

                </Col>

              </FormGroup>
            )
          
        })}

      </div>
    );`

**Comment by gaearon** [comment]
The problem is here:

```js
return
  (
```

JavaScript will insert a `;` after `return` and then ignore the rest of your code.

You need to open the paren on the same line as `return`:

```js
return (
```

**Comment by Deboracgs** [comment]
@gaearon  thank's!
