### ISSUE TITLE
New Warning: Encountered two children with the same key after adding a state item

### ISSUE THREAD

**Issue by nguyendviet** [facebook/react#13074]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
If I add item `notice` to the state of the `main.js` file, the app crashes
The error message keeps showing up until my web browser (Google Chrome) crashes
If I remove `notice` from the state and related components, the app behaves normally.
I know that people have experienced this error as described here: https://github.com/akiran/react-slick/issues/310
but I think this might be a new bug.

**Code**
- I cannot explain the code in a minimal way.
- If you remove the notice from the `Progress` component, the app doesn't crash
- You can see that each key is different since the data is from MongoDB so each `_id` is unique
Code in the attached files.
[List.txt](https://github.com/facebook/react/files/2115932/List.txt)
[ListItem.txt](https://github.com/facebook/react/files/2115933/ListItem.txt)
[main.txt](https://github.com/facebook/react/files/2115934/main.txt)
[MatchItem.txt](https://github.com/facebook/react/files/2115935/MatchItem.txt)
[Progress.txt](https://github.com/facebook/react/files/2115936/Progress.txt)

Since I cannot pause the error messages, I took a screen shot here:
![screen shot 2018-06-19 at 11 19 36](https://user-images.githubusercontent.com/30057363/41608527-b0546428-73b6-11e8-90bf-3bec68481fa4.png)

**What is the expected behavior?**
The app should not crash.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v16.4.0
Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
OSX 10.13.5
Previous version of React: Unknown

**Comment by nguyendviet** [comment]
Never mind. I nested more setState than the React DOM can handle.

**Comment by gaearon** [comment]
If you can isolate this to a self-contained example we could look. 

My guess it that there's no bug here, but you probably put the same item into `this.state.answered` multiple times so it's not unique when you enumerate over them.

**Comment by nguyendviet** [comment]
Thank you @gaearon Yes, you're right, it's not a bug. I just nested too many setState so the code was stuck in an infinitive loop.
