### ISSUE TITLE
Context API with `context` as prop name

### ISSUE THREAD

**Issue by citta-lab** [facebook/react#13081]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If we happen to use `context` as value name to pass down the prop to child components then the value `context` is `undefined`. 

**Example Snippet:**
Example component with Context Provider,
```
import React from 'react';
import ExampleComponentTwo from './ExampleComponentTwo';
import ExampleContext from './ExampleContext';

class ExampleComponentOne extends React.Component {
    constructor(props){
        super(props);
    }

    render(){
        return(
            <div>
                <h2> I'm Example ONE</h2>
                <ExampleContext.Provider context="BOB">
                    <ExampleComponentTwo />
                </ExampleContext.Provider>
            </div>
        )
    }
}

export default ExampleComponentOne;
```
Example component with Context Consumer,
```
import React from 'react';
import ExampleContext from './ExampleContext';

class ExampleComponentTwo extends React.Component {
    constructor(props){
        super(props);
    }

    render(){
        return(
            <div>
                <h2> I'm Example TWO </h2>
                <ExampleContext.Consumer>
                    {(context) => { console.log(" Name: "+context)}}
                </ExampleContext.Consumer>
            </div>
        )
    }
}

export default ExampleComponentTwo;
```
Context Component,
```
import React from 'react';
const ExampleContext = React.createContext();
export default ExampleContext;
```
    
**What is the expected behavior?**
Unless `context` is a keyword it should behave as any other prop name. ( example: `value` as defined in react docs for Context api example )

     
**Details:**
Chrome: Version 67.0.3396.87 (Official Build) (64-bit)
OS: mac os high sierra
React: 16.4.1

**Comment by aweary** [comment]
@citta-lab Provider's don't have a `context` prop, you're looking for `value`

```jsx
<ExampleContext.Provider value="BOB">
```

https://reactjs.org/docs/context.html#provider

**Comment by citta-lab** [comment]
Ahh i missed that. My bad. Thank you.
