### ISSUE TITLE
React.Timeout inside a hidden element

### ISSUE THREAD

**Issue by pomber** [facebook/react#13089]
**Do you want to request a *feature* or report a *bug*?**
Bug  

**What is the current behavior?**
When using `React.Timeout` inside a `hidden` element, React keeps rendering children every tick until the promise is resolved.

**Minimal demo**
https://romantic-joliot-14841e.netlify.com/ (look at the console)   
Repo: https://github.com/pomber/suspense-hidden

**What is the expected behavior?**
Render should be called no more than 3 times (when I change `hidden={true}` to `hidden={false}` it works as expected)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested in Chrome Version 67.0.3396.87 (Official Build) (64-bit)  
React built from commit 36546b5 (June 1) with flag `enableSuspense = true`

```jsx
let done = false;
let promise = null;

const waitFor = text => {
  console.log("waitFor");
  if (done) return text;
  if (!promise) {
    promise = new Promise(resolve =>
      setTimeout(() => {
        done = true;
        resolve();
      }, 5000)
    );
  }
  throw promise;
};

const AsyncText = ({ text }) => <h1>{waitFor(text)}</h1>;

const App = () => (
  <div hidden={true}>
    <React.Timeout ms={0}>
      {didTimeout =>
        didTimeout ? <h1>Loading...</h1> : <AsyncText text="foo" />
      }
    </React.Timeout>
  </div>
);

ReactDOM.render(
  <React.unstable_AsyncMode>
    <App />
  </React.unstable_AsyncMode>,
  document.getElementById("root")
);
```

**Comment by gaearon** [comment]
@cyan33

**Comment by gaearon** [comment]
@pomber While you're here, wanna look into why this happens?

**Comment by cyan33** [comment]
Hi @pomber, thanks for filing up this issue. I don't have much context about how suspense works with `<React.unstable_AsyncMode>`, but it works fine when I switch to the following usage:

```js
const root = ReactDOM.unstable_createRoot(document.getElementById("root"));
root.render(<App />);
```
I'll try to look into it and discuss with more people. Open to any kind of discussion 😄

**Comment by pomber** [comment]
Hmm, I tried with `unstable_createRoot` and it's [still happening](https://romantic-joliot-14841e.netlify.com/).

This is what I've found so far:

- [`updateHostComponent`](https://github.com/facebook/react/blob/aeda7b745d9c080150704feb20ea576238a1b9a1/packages/react-reconciler/src/ReactFiberBeginWork.js#L512) sets `expirationTime = Never` for fibers with a `hidden` prop
- Because [`expirationTime === Never`](https://github.com/facebook/react/blob/4fe6eec15bc69737910e5c6c749ebc6187d67be0/packages/react-reconciler/src/ReactFiberUnwindWork.js#L210),  `ShouldCatpure` is not [added to the `effectTag`s](https://github.com/facebook/react/blob/4fe6eec15bc69737910e5c6c749ebc6187d67be0/packages/react-reconciler/src/ReactFiberUnwindWork.js#L238)
- Without `ShouldCapture`, `DidCapture` is not [added to the `effectTag`s](https://github.com/facebook/react/blob/4fe6eec15bc69737910e5c6c749ebc6187d67be0/packages/react-reconciler/src/ReactFiberUnwindWork.js#L331)

**Comment by gaearon** [comment]
Can't reproduce this on master. It's likely fixed.
