### ISSUE TITLE
Flowtype definition for the style property

### ISSUE THREAD

**Issue by NameFILIP** [facebook/react#13093]
Is it possible to add a flowtype support for the `style` property? For example, if I type `'padding-left': '10px'` it would warn me that I should use `paddingLeft: '10px'`.

I found this 3rd party definition: https://github.com/Polyconseil/flow-inlinestyle/blob/master/index.js, but it would be great to have an official support for this.

**Comment by aweary** [comment]
The Flow definitions for React are actually defined in [the Flow repo itself](https://github.com/facebook/flow/blob/master/lib/react.js). Third party library definitions are a good solution for this, but if you should direct any Flow related bugs or feature requests to the Flow repo.

Thanks!

**Comment by NameFILIP** [comment]
That makes sense, thanks for the direction! Created https://github.com/facebook/flow/issues/6522
