### ISSUE TITLE
Cannot specify a key for a Portal element

### ISSUE THREAD

**Issue by RoystonS** [facebook/react#13094]
**Do you want to request a *feature* or report a *bug*?**
I'm either reporting an oversight in the documentation for a feature which is already implemented but not documented, which would be a bug, or a request for a supported way of adding keys on portal elements, which would be a feature.

**What is the current behavior?**
I can't see an existing way to add a key to a Portal element, at least using officially documented means.  This means that the reconciler is somewhat crippled when re-rendering a component that emits multiple portals, and will do bad things.

e.g. if we render portals [A, B, C, D] but then remove B and the re-render emits [A, C, D], React ends up tearing down the original C and D component instance trees and creating new ones, because there's no way to hint to the reconciler that the new C and D are the same.  (I'm sufficiently unfamiliar with the implementation logic that I don't understand how it knows that A is unchanged, so I suspect I'm missing something here.)

Being able to specify `key` hints on Portals would enable React to avoid recreating the C and D instances in the above example.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Here's a CodeSandbox that demonstrates that without keys, Portals suffer the expected reconciliation issues when they disappear:

https://codesandbox.io/s/ppjkxqx8xm

Interestingly, I can see that there's a (currently) undocumented third parameter to `createPortal` which does allow a key to be specified.

https://github.com/facebook/react/blob/aeda7b745d9c080150704feb20ea576238a1b9a1/packages/react-dom/src/client/ReactDOM.js#L570

Using this fixes the problem (also demonstrated in the above CodeSandbox).  But it's not mentioned in the Portal documentation: https://reactjs.org/docs/portals.html.

Is this an omission in the documentation or is it a deliberately hidden and unsupported feature?  (Right now I have to assume the latter.)

**What is the expected behavior?**
There would be a supported way of adding keys to portal elements.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.4

**Comment by gaearon** [comment]
It’s a documentation omission. Please send a PR?
