### ISSUE TITLE
 New proposal of logo for React

### ISSUE THREAD

**Issue by orlant** [facebook/react#13102]
Hi, I'm a graphic designer, I like to make design contributions in good projects as it is, this react. Tell me if you would like me to make a contribution to better visualize your project thank you very much

![firma](https://user-images.githubusercontent.com/40074778/41814772-b6e2df82-7725-11e8-93ff-0bf2df83cbbf.png)

**Comment by aweary** [comment]
We're not currently looking to change any of the design assets, but thanks!

**Comment by orlant** [comment]
He is very kind, thanks to you. if you know some PO that needs a design .. I am available thanks
