### ISSUE TITLE
replacement for onChange to fire the event when choose selected option in select

### ISSUE THREAD

**Issue by SilencerWeb** [facebook/react#13101]
What event instead of onChange should I use for listening when the option was selected? I need it because I have to change state every time select changes even if the selected option was selected. Now I use onChange for select but it fires only when the unselected option was selected. I understand that it is logical behavior, that's why I'm looking for another event. Unfortunately, onClick for an option doesn't work :(

[Pure demo](https://codepen.io/SilencerWeb/pen/vrrJez?editors=0001) (for playing around)
[Demo](https://silencerweb.github.io/karma/storybook/?knob-content=Hi%2C%20I%27m%20button&knob-tag=button&knob-type=positive&knob-theme=primary&knob-title=Action%20name&knob-date=12.05.2018&knob-description=Music%20fan.%20Alcohol%20enthusiast.%20Creator.%20Devoted%20social%20media%20geek.%20Total%20analyst.%20Coffee%20lover.%20Beer%20junkie.%20Coffee%20maven.%20Avid%20alcohol%20lover.%20Twitter%20expert.%20Lifelong%20tv%20ninja.%20Creator.%20Passionate%20tv%20nerd.%20Problem%20solver.%20Proud%20alcohol%20evangelist.%20Lifelong%20web%20junkie.%20Coffee%20maven.%20Unapologetic%20social%20media%20advocate.%20Analyst.%20Tv%20trailblazer.%20Zombie%20geek.%20Twitter%20aficionado.%20Reader.&knob-executors=left&selectedKind=molecules%2FActionCard&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) (try to select the selected option, nothing will be changed)

Some pieces of code for better understanding:
```jsx
  handleSelectChange = (e, side) => {
    const state = { ...this.state };

    if (!state.members) state.members = {};

    const value = e.currentTarget.value;

    console.log(`changed! value: ${value}`);

    const newMember = state.persons.find((person) => {
      return person.name === value;
    });

    state.members[side].push({
      avatar: newMember.avatar,
    });

    state.persons = state.persons.map((person) => {
      if (value === person.name) {
        person.isSelected = true;
        person.side = side;
      }

      return person;
    });

    this.setState(state);
  };
```

```jsx
<Select onChange={ (e) => this.handleSelectChange(e, 'right') }>{ ...options }</Select>
```

**Comment by jquense** [comment]
I don't think there is an event for that unfortunately. React is limited to what the browser natively fires and if browser `select`s don't fire a change when the value doesn't change there isn't much we can do. And it does appear (at least in Chrome) that no native change events are fired for selecting the same option again: http://jsfiddle.net/xpvt214o/291079/
