### ISSUE TITLE
React -fiber has not been released yet. How can you use it to create a Demo?

### ISSUE THREAD

**Issue by wxg3a702** [facebook/react#13103]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
I’m not sure I understand what you’re asking.

“Fiber” is a codename for a core architecture rewrite which became React 16. So if you use React 16, you *are* using Fiber.

The async mode is not enabled by default. But you can enable it if you build from master by setting a special build flag. Note that it is buggy and not ready for production yet. Works well enough for demos if you patch over those bugs.
