### ISSUE TITLE
React Nested Input wrong index Errors on Update

### ISSUE THREAD

**Issue by phandych** [facebook/react#13106]
I have create nested attribute with nested form with React and Backend with Rails json. i have test with rails and its work fine. on Create action its work fine, but the problem its on update / edit product.

i found errors on frontend not Rails. i used React `"version": "0.1.0",`

Problem with this data params, json index right but if i'm update the product. they getting double of nested attribute because can find ID for existing nested item :

```
for (let i = 0; i < product_specifications.length; i++) {
		let specification = product_specifications[i];
		if (specification._destroy) {
			data.append(`product[product_specifications_attributes][${i}][id]`, specification.id);
	       	data.append(`product[product_specifications_attributes][${i}][_destroy]`, '1');
		} else if (specification.id) {
			data.append(`product[product_specifications_attributes][${i}][title]`, specification.title)
		} else {
			data.append(`product[product_specifications_attributes][${i}][title]`, specification.title)
		}
		
	}
```

before action:
<img width="1280" alt="screen shot 2018-06-25 at 11 34 34" src="https://user-images.githubusercontent.com/16778350/41830611-3f62f648-786c-11e8-9a47-625709a91eb0.png">

after action:
<img width="1280" alt="screen shot 2018-06-25 at 11 38 42" src="https://user-images.githubusercontent.com/16778350/41830651-77b4ca44-786c-11e8-9007-5fa0e5351a30.png">

second. if i use this code. its work fine with action. and attributes not getting double. but the problem, if i'm update the product with empty value of nested attriubtes, they render with json error index not index right input field, but start with [0] index.

```
for (let i = 0; i < product_specifications.length; i++) {
		let specification = product_specifications[i];
		if (specification._destroy) {
			data.append(`product[product_specifications_attributes][${i}][id]`, specification.id);
	       	data.append(`product[product_specifications_attributes][${i}][_destroy]`, '1');
		} else if (specification.id) {
			data.append(`product[product_specifications_attributes][${i}][id]`, specification.id);
			data.append(`product[product_specifications_attributes][${i}][title]`, specification.title)
		} else {
			data.append(`product[product_specifications_attributes][${i}][title]`, specification.title)
		}
		
	}
```

<img width="1280" alt="screen shot 2018-06-25 at 11 42 53" src="https://user-images.githubusercontent.com/16778350/41830744-ef9ba0aa-786c-11e8-9181-bad5a20b140b.png">

 If u change the value of each parent field (without json action only frontend action), the getting right error of index.
<img width="1280" alt="screen shot 2018-06-25 at 11 48 56" src="https://user-images.githubusercontent.com/16778350/41830892-d98f747a-786d-11e8-9d78-0320afbbdf63.png">

you must change parent field value first to get right index errors. anybody can help me with this issue?what the problem?
i'm use React redux to handle form.

**Comment by nhunzaker** [comment]
Hey! We use this issue board to track issues specific to React itself. It sounds like this might be an issue specific to your application.

Please take a look at our community support resources, where you might be able to get help troubleshooting your app:
https://reactjs.org/community/support.html
