### ISSUE TITLE
Warn when setState is a function that doesn't return

### ISSUE THREAD

**Issue by sw-yx** [facebook/react#13111]
**Do you want to request a *feature* or report a *bug*?**

I am proposing adding a warning in development.

**What is the current behavior?**

when I do `this.setState(({ bool }) => { bool: !bool });` this is valid javascript but is meaningless in React. ESLint:no-label helps to catch this but we can probably do one better by building a warning into dev-mode React itself.

sandbox demo: https://codesandbox.io/s/xopj5nx07o

**What is the expected behavior?**

warn when a function is applied to setState that returns undefined. if the user wants to indicate nothing changed they should return null.

**Comment by gaearon** [comment]
I wish we did this earlier. Might be too late now because there’s probably a lot of code using this pattern. #strictmodeonly?

**Comment by tsiq-swyx** [comment]
strictmodeonly works for me.

i'm not sure i understand, why would there be a lot of code using this pattern? accidental no-op is far more likely than intentional no-op?

also we'd just be doing a warning, i reckon if people think they know what they're doing we can let them ignore the warning. i dunno, is that inline with react's warning philosophy?

**Comment by alexkrolick** [comment]
> i'm not sure i understand, why would there be a lot of code using this pattern? accidental no-op is far more likely than intentional no-op?

Probably something like:

```js
this.setState(state => { if (condition) return { foo: !state.foo } }) // no else
```

**Comment by gaearon** [comment]
>i'm not sure i understand, why would there be a lot of code using this pattern? accidental no-op is far more likely than intentional no-op?

I don't think it's necessarily more likely.

>also we'd just be doing a warning, i reckon if people think they know what they're doing we can let them ignore the warning. 

No, if we add a warning, we don't want people to ignore it. This devalues warnings.

**Comment by sw-yx** [comment]
strict mode it is

**Comment by aweary** [comment]
@sw-yx do you want to submit a PR for this?

**Comment by tsiq-swyx** [comment]
yup i will attempt it this weekend if thats ok?

**Comment by KiritoCheng** [comment]
I use with typescript ,now its's error "Cannot assign to 'state' because it is a constant or a read-only property."
I just write
 constructor(props: any) {
        super(props);
        this.state = {
           a:'a'
        }
    }

**Comment by tsiq-swyx** [comment]
sorry, i dont think this has anything to do with my PR. are you commenting
in the right issue?
