### ISSUE TITLE
onMouseLeave false triggering when using svg <use> in IE11

### ISSUE THREAD

**Issue by kuzkokov** [facebook/react#13115]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
As you can see in the example below, onMouseLeave of parent element get triggered every time, when you hover the svg which is get element to render by `<use>` in IE11 (and probably lower).  
It works as expected in other browsers and with regular `<path>` inside svg. And also, the native event work as expected too (as you can see in expample), so I identify the bug as React's.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/jnn8w7940w

**What is the expected behavior?**
To not trigger onMouseLeave when mouse doesn't leave the parent element.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on React 16.3.2 and 16.4.1.

**Comment by kuzkokov** [comment]
...hello?

**Comment by nhunzaker** [comment]
Hi!

Sorry we haven't gotten to this issue yet, but thank you for submitting a reproduction case. This will make it much easier to identify what is going on.

As next steps, we need to:

1. Identify any similar prior issues that might inform what's going on.
2. Come up with a hypothesis for the issue
3. Figure out if anyone has bandwidth to work on this (sometimes a community member will volunteer)

My first hunch is that this is something in the [EnterLeavePlugin](https://github.com/facebook/react/blob/master/packages/react-dom/src/events/EnterLeaveEventPlugin.js)

I wonder if SVG in IE11 (or earlier) behaves differently in some way.

**Comment by gaearon** [comment]
Technically this is still a bug.

**Comment by gaearon** [comment]
We are dropping support for IE in React 18, so this won't get a fix.
Sorry.
