### ISSUE TITLE
TIC TAC TOE  sample code has a bug

### ISSUE THREAD

**Issue by Legends** [facebook/react#13119]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

Following [this tutorial](https://reactjs.org/tutorial/tutorial.html):

[Here ](https://codepen.io/gaearon/pen/gWWZgR?editors=0010)is the final result on code pen.

When you start the game and click for example 6 times on the first field in the first row then continue without creating a winning row (xxx/000). You cannot finish the game, there will be two fields remaining unfilled , so the game will end here without a winner.

**What is the expected behavior?**
Either you say you have a max of 9 moves, false moves count and give a warning like, you left out of moves
or
one should be able to complete the game.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

>  "react": "^16.4.1",
>     "react-dom": "^16.4.1",
>     "react-scripts": "1.1.4"

**Comment by gaearon** [comment]
My impression is that clicking on the same field many times doesn't do anything, but indeed a game may end in a tie. Good find!

This is mentioned at the very end in the [list of follow-up suggested exercises](https://reactjs.org/tutorial/tutorial.html#wrapping-up):

>If you have extra time or want to practice your new React skills, here are some ideas for improvements that you could make to the tic-tac-toe game which are listed in order of increasing difficulty:
>
>[...]
>
>When no one wins, display a message about the result being a draw.

**Comment by Legends** [comment]
This should be added to the ideas for improvements list:
The game ends **prematurely** in a tie without being able to finish, when a user wastes his moves on already set fields.

![image](https://user-images.githubusercontent.com/966368/42005509-29e3dc14-7a75-11e8-8314-a91f3436eb5e.png)

--> No more moves possible...

**Comment by gaearon** [comment]
This is not a bug. You're seeing the game end because there's a diagonal XXX line.

**Comment by Legends** [comment]
2 o'clock in the morning, it's time to go to bed... sorry for talking crap!

**Comment by gaearon** [comment]
Haha no problem, thanks for taking the time to report!
