### ISSUE TITLE
With server side rendering, if any parameter in state is a string containing '</script>' rendered page is broken.

### ISSUE THREAD

**Issue by againksy** [facebook/react#13136]
If during server side rendering i have in state any parameter that is a string and have inside `</script>` - i got broken page- just page with piace of state object string.

**Comment by aweary** [comment]
@againksy please provide all the information requested [in the issue template you deleted](https://github.com/facebook/react/blob/master/.github/ISSUE_TEMPLATE.md), including an example that reproduces the issue.

**Comment by aweary** [comment]
[I can't reproduce](https://codesandbox.io/s/l5yr01pm4m) and there's been no follow up. Assuming this is resolved.
