### ISSUE TITLE
Make use of the new React Context API in SSR

### ISSUE THREAD

**Issue by monsieurnebo** [facebook/react#13138]
Hello everyone,

I'm running a small project on GatsbyJS, using **Redux** to manage shared state values between multiple components across the React DOM tree.

With the release of the new Context API, I'm thinking about replacing Redux (which is a bit overkill for this project). I made some tests, and it's working really fine in runtime.

However, I cannot build the project via server-side rendering. The context seems to be `undefined`. I made a lot of searches on the web about this issue, but there is not so much informations about this (probably because of its young age).

[The only issue that - I think - is related is from next.js](https://github.com/zeit/next.js/issues/4194) (that is a static website generator aswell). But they don't have any solution neither.

**=> Is this new Context API compatible with SSR? Do you have any resources / examples about this?**

**Comment by gaearon** [comment]
The Next.js issue is specific to Next.js, as you can read from the issue you linked to.

I don't know if there's a problem with Gatsby, so I suggest filing an issue with them.

New context API is expected to work with server rendering in general. If you can come up with an example where it doesn't, please share it with us, and we'll take a look. There are no specific resources or examples about it — there's nothing special you need to do to make it work.

**Comment by monsieurnebo** [comment]
@gaearon I created an issue both here, and on the [Gatsby repo](https://github.com/gatsbyjs/gatsby/issues/6258#issuecomment-402039346).

In order to give a practical example of this behavior, I created a [dedicated repository](https://github.com/monsieurnebo/gatsby-react-context).

The React Context stores a `isPowerOn` value (boolean) that can be updated via the `togglePower` method (also from the context).

It's working fine via `gatsby develop`, but not during a `gatsby build`:
```
  14 |       renderWrappedComponent(context) {
  15 |         const contextProperties = properties.reduce((accu, property) => {
> 16 |           accu[property] = context[property];
     |                                    ^
  17 |           return accu;
  18 |         }, {});
  19 |


  WebpackError: TypeError: Cannot read property 'isPowerOn' of undefined
```

**Comment by gaearon** [comment]
Sounds good. If you can reproduce this with React alone (no Gatsby) let me know.
