### ISSUE TITLE
Add a more helpful message when passing an element to createElement() as a type

### ISSUE THREAD

**Issue by gaearon** [facebook/react#13130]
This:

```js
createElement(<div />)
```

doesn't currently give a distinguishable message.

https://stackoverflow.com/questions/51110436/wrapping-provider-in-same-component-throws-element-type-is-invalid-expected-a-s

But we can easily detect it by checking for `$$typeof` and in that case suggest something more concrete (e.g. "Did you accidentally export JSX instead of a component?").

**Comment by DCtheTall** [comment]
I can take this one!

**Comment by aweary** [comment]
It's all yours @DCtheTall!
