### ISSUE TITLE
react-test-renderer shallow: SFCs should not get `this`

### ISSUE THREAD

**Issue by ljharb** [facebook/react#13141]
**Do you want to request a *feature* or report a *bug*?**
bug.

**What is the current behavior?**
This addresses a bug in `enzyme`, https://github.com/airbnb/enzyme/issues/1683.

On [this line](https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactShallowRenderer.js#L110) `element.type()` invokes the SFC with `element` as the `this` value. I believe that this is needed for create-react-class components, but that there needs to be a separate branch for SFCs.

**What is the expected behavior?**
`this` inside a strict-mode SFC will be `undefined`, not the element.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
In all of React 0.13, 0.14, 15, and 16, this bug exists.

While the bug ideally will be fixed, I understand that it's highly unlikely that it would be backported to the 14/15 lines - but I can wrap around it if there's a reliable way, in those versions, to distinguish SFCs from create-react-class components (is there?).

**Comment by gaearon** [comment]
If something doesn't have `.prototype` or `.prototype.isReactComponent`, we won't try to `new` it.

(This still doesn't mean it's functional — it could return an object with a render method — but at least it shouldn't have `this`.)

Happy to take a fix for 16.x.

**Comment by ljharb** [comment]
So both class and createReactClass components will have .isReactComponent on them? Is there a spec on providing a receiver to other things, or is my assumption correct that unless it’s newed, it should lack a receiver?
