### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by dhanu459** [facebook/react#13147]
Hi i have a React application which is running fine on "npm start".
But when i try to create a build for prod deployment, its taking too long to prepare the build and finally error is thrown. 
Tried below options too:
1) re install the node modules
2) Cleared the cache
3) new install
and also tried
1) updating NPM to the latest version.
2) running the application form fresh folder with all new NPM installations.

nothing seems to be helpful to resolve the issue,
i am kind of stuck with this and any kind of Help or suggestions are really helpful and appreciated.

Error reported:
--------------------------
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
------------------------------

Complete error details:
> light-bootstrap-dashboard-pro-react@1.0.0 build E:\Santosh\Remitrix\Web-UI\Remitrix_Datta
> npm run build-css && react-scripts build

> light-bootstrap-dashboard-pro-react@1.0.0 build-css E:\Santosh\Remitrix\Web-UI\Remitrix_Datta
> node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/

Wrote 2 CSS files to E:\Santosh\Remitrix\Web-UI\Remitrix_Datta\src\
Creating an optimized production build...

<--- Last few GCs --->

[48072:0000024CAA06F980]  3178097 ms: Mark-sweep 1427.9 (1530.0) -> 1427.9 (1526.0) MB, 1909.8 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001E058EA5879 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0000006130A022D1 <undefined>:~8150] [pc=000000CE8067D72D](this=0000006130A022D1 <undefined>,self=000001964D603741 <AST_Call map = 000002D0511C6779>,compressor=00000147A5802979 <Compressor map = 000002D0511C7069>)
    2: optimize [0000006130A022D1 <undefined>:~5511] [pc=000000CE8074ECA4](this=000001964D603741 <AST_Call map = 000002D0511C6779>,compres...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewCodeRaw
 5: v8::internal::Factory::NewCode
 6: v8::internal::modulo
 7: v8::internal::compiler::ControlFlowOptimizer::TryBuildSwitch
 8: v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>
 9: v8::internal::compiler::Pipeline::AllocateRegistersForTesting
10: v8::internal::compiler::ValueNumberingReducer::operator=
11: v8::internal::CompilationJob::FinalizeJob
12: v8::internal::compiler::InstructionSelector::isolate
13: v8::internal::Compiler::FinalizeCompilationJob
14: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions
15: v8::internal::StackGuard::HandleInterrupts
16: v8::internal::wasm::WasmOpcodes::TrapReasonMessage
17: 000000CE7F9043C1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! light-bootstrap-dashboard-pro-react@1.0.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the light-bootstrap-dashboard-pro-react@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     absolute path\2018-07-04T13_53_48_536Z-debug.log

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests in React itself.
Please file the issue here instead: https://github.com/facebook/create-react-app

Thanks!
