### ISSUE TITLE
DOM elements (DIVs) has incorrect properties in componentDidMount

### ISSUE THREAD

**Issue by gsbelarus** [facebook/react#13154]
I need to render a list of items inside flex-box column. Every item is a div and has arbitrary height. The list of items can be huge so my tactics is to render initially one item and check available space. For that I save refs to parent div and to item's div and then access their **clientHeight** and **offsetHeight** properties. If there is a free space I add one more item and rerender whole thing. The process is repeated until whole column is filled.

The problem is that if I try immediately calculate available space in **componenDidMount** I've got incorrect value of child div's **offsetTop**. I.e. the following method:
```typescript
  public componentDidMount() {
    this.setState({ recalc: true });
  } 
```
Will not work. But if I add some small pause it works:

```typescript
  public componentDidMount() {
    setTimeout( () => this.setState({ recalc: true }), 100);
  }
```

The other method, **componentDidUpdate**, works excellently without any delays:

```typescript
  public componentDidUpdate() {
    this.calcVisibleCount();
  } 
```

Seems like there is some rendering in parallel going when **componentDidMount** is invoked and all refs could be incomplete/incorrect until this process is finished.

Just for the reference:

```typescript
  private calcVisibleCount() {
    const { nlpDialog } = this.props;
    const { showFrom, showTo, recalc } = this.state;

    if (recalc) {
      if (this.shownItems.length) {
        if (this.shownItems[0].offsetTop > 38) {
          if (this.shownItems.length < nlpDialog.items.size && showFrom > 0) {
            this.setState({ showFrom: showFrom - 1 });
          } else {
            this.setState({ recalc: false });
          }
        }
        else if (this.shownItems[0].offsetTop <= 0) {
          if (showFrom < showTo) {
            this.setState({
              showFrom: showFrom + 1,
              recalc: false
            });
          } else {
            this.setState({ recalc: false });
          }
        }
      } else {
        this.setState({
          showFrom: 0,
          showTo: 0,
          recalc: false
        });
      }
    }
  }

  public render() {
    const { nlpDialog } = this.props;
    this.shownItems = [];
    return (
      <Fragment>
        <div styleName="NLPDialog" ref={ elem => this.nlpDialogDiv = elem }>
          {
            nlpDialog && nlpDialog.items.map(
              (i, idx) => i && typeof idx === 'number' && idx >= this.state.showFrom && idx <= this.state.showTo &&
                <div key={idx} styleName="NLPItem" ref={ elem => elem && this.shownItems.push(elem) } >
                  <span styleName="Circle">{i.who}</span>
                  <span styleName="Message">{i.text}</span>
                </div>
            )
          }
          <div styleName="NLPInput">
            <textarea
              spellCheck={false}
              value={this.state.text}
              onKeyPress={this.onPressEnter.bind(this)}
              onChange={ (e: ChangeEvent<HTMLTextAreaElement>) => this.setState({ text: e.target.value }) }
            />
          </div>
        </div>
      </Fragment>
    );
  }
```

**Comment by nmain** [comment]
Could you provide a simple self-contained reproducing case as a jsfiddle or similar?  It's difficult to say exactly where things are going wrong otherwise.

**Comment by gsbelarus** [comment]
Closing. Will reopen when there will be reproducible example.

**Comment by eminx** [comment]
For anyone who bumps into this:

If there's an image loading inside the component you're trying to get the properties of, it's likely that the image doesn't have a fixed width or height, and that the properties (most usually width and height), therefore doesn't correctly reflect the properties **after** loading of the image.

Fix? I guess to force remaking the calculations after the image is loaded.
