### ISSUE TITLE
Microdata HTML attributes are camelCase in server render

### ISSUE THREAD

**Issue by mike-marcacci** [facebook/react#13162]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
ReactDOM render methods (renderToStaticMarkup, renderToString, etc) generate camelCase microdata attributes.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/yvpq464mov

**What is the expected behavior?**
Microdata attributes should be rendered all lowercase (`itemprop`, `itemtype`, `itemid`, etc).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.0.0 - 16.4.0

This is related to #12403 and #12462. While Google's [structured data testing tool](https://search.google.com/structured-data/testing-tool/) recognizes camelCase props, our index of structured data disappeared after switching from lowercase `itemprop` to camelCase `itemProp` to appease a linter:

![42398575-92ab582c-8127-11e8-972c-78aa56b7547d](https://user-images.githubusercontent.com/690517/42400069-6ef821a2-812d-11e8-9447-e6a82efce962.png)

This a definitely a Google problem, not a react one.. but can easily be solved by calling `toLowerCase()` from react renderers.

We've switched back to lowercase attributes today, and will see if this resolves the issue with google.

**Comment by gaearon** [comment]
How many microdata props do we support?

**Comment by gaearon** [comment]
In other words, are we talking about fixing one attribute or like 10?

**Comment by mike-marcacci** [comment]
Just 5:
- itemscope
- itemtype
- itemid
- itemprop
- itemref

**Comment by aweary** [comment]
Spec for reference: https://www.w3.org/TR/microdata/#new-attributes

**Comment by gaearon** [comment]
The spec doesn't seem to say anything about them being case-sensitive. 😞 
Maybe we can find someone from Google who can shed light on this?

**Comment by aweary** [comment]
We [currently lowercase the `itemScope` microdata attribute](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/DOMProperty.js#L297), but none of the others. Why did we special case `itemScope` 🤔

**Comment by gaearon** [comment]
It's boolean.

**Comment by aweary** [comment]
Oh right 🤦 in this if case-sensitivity isn't spec-defined it's better to get vendors like Google spec-compliant. @mike-marcacci is the structured data test tool the only case where this has been a problem for you?

**Comment by mike-marcacci** [comment]
No, the testing tool acts correctly and sees camelCase props, but the index itself disappeared for myself [and another react user](https://github.com/facebook/react/issues/12403#issuecomment-379508670) after switching to camelCase. We just switched back to use lowercase string props today, so I probably have to wait until tomorrow to see if the index is recovering.

There's definitely a possibility that google changed something internally at the same time as my switch to camelCase microdata props, so I'll definitely keep this issue updated.

**Comment by mike-marcacci** [comment]
FWIW I would definitely prefer leaving react as-is, just not if it's an SEO foot-gun waiting to happen.

**Comment by mike-marcacci** [comment]
I'm going to close this; we did a test where we kept lowercase microdata names on some pages and camelCase on others. Without changing anything else related to structured data Google has begun to pick up both sets again.

I'll chock this up to coincidence and the superstitious nature of everything SEO. Apologies for the noise.

**Comment by gaearon** [comment]
Sounds good, thanks for checking.

**Comment by nhunzaker** [comment]
Yes! Thank you for posting this issue, I think the write-up will be useful for reference in the future if it comes up again!

**Comment by lid2000** [comment]
I _think_ this is causing issues in my isomorphic app - it renders microdata props as camelcase on the server, however as far as I can tell React on the client-side renders them as all-lowercase, which causes mismatch warnings to get thrown up when using ReactDOM.hydrate(). I'm just using ReactDOM.render() instead to get around it for now.
