### ISSUE TITLE
defaultChecked or checked

### ISSUE THREAD

**Issue by wangcongyi** [facebook/react#13167]
sorry my english just so-so, here is my code

```js
import React from 'react';

const a = [1, 2]
const b = [3, 4]
const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

class Checky extends React.Component {
  render() {
    return (
      <input
        type="checkbox"
        //  checked={this.props.checked}
        defaultChecked={this.props.checked}
        onChange={(event) => {
          this.setState({
            isChecked: !event.target.checked
          })
        }}
      />
    );
  }
}

class Home extends React.Component {
  state = {
    arr: a
  }

  render() {
    return (
      <div>
        <a href="#" onClick={() => {
          this.setState({ arr: this.state.arr === a ? b : a });
        }}>Toggle</a>
        <hr />
        {arr.map((item, index) => {
          return (
            <Checky key={index} checked={this.state.arr.indexOf(index) > -1} />
          )
        })}
      </div>
    );
  }
}
export default Home;
```

[online demo ](https://codepen.io/kid_1412/pen/bKXpqd)

- if i use  `checked ` attr  can change Home state , but can't change input checked, input element just read-only
- if i use `defaultChecked` attr  can change input checked , but can't change Home state, rerender not working

i  want both working

**Comment by Maaartinus** [comment]
I guess, you'd better use stackoverflow for questions.

The state can reside in one place only. You must decide. `checked` and `defaultChecked` cannot work at the same time, you must decide.

Your `onChange` handler in `Checky` changes a state which never gets used.

Using `defaultChecked`: https://codepen.io/dsabalete/pen/jAzLpA

Your code (mostly) fixed: https://codepen.io/anon/pen/gKVBYQ/

Note, that your state representation is wrong, unless you want to keep track of in what order the boxes were checked (use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).
