### ISSUE TITLE
Needless checkbox warning when using onClick instead of onChange

### ISSUE THREAD

**Issue by Maaartinus** [facebook/react#13171]
**Do you want to request a *feature* or report a *bug*?**
A very minor bug.

**What is the current behavior?**
When using a checkbox with `onClick`, I get the following warning:
> Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

But my checkbox works well and actually, `onClick` is the better solution according to https://stackoverflow.com/a/4471462/581205.

**What is the expected behavior?**
No warning when `onClick` is set.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "^16.4.1"

And thanks for the good software!

**Comment by jamiewinder** [comment]
Worth pointing out: much of that answer refers to a bug in Internet Explorer which was actually fixed in IE9+. React DOM doesn't support IE8 or lower any more anyway.

**Comment by jquense** [comment]
ya we have a pending PR for that: https://github.com/facebook/react/pull/10830

**Comment by gaearon** [comment]
>onClick is the better solution according to https://stackoverflow.com/a/4471462/581205.

That answer doesn't apply to React. In fact React internally uses `onClick` precisely for that reason so you don't need to worry about it.

You can keep using `onChange`. While `onClick` is equivalent in this scenario, the warning encourages consistency so it doesn't hurt to follow it.

**Comment by gaearon** [comment]
We can, however, revisit this at the same time as we merge https://github.com/facebook/react/pull/10830.
