### ISSUE TITLE
ReactDOM.render()+ Context API = Warning: Detected multiple renderers concurrently rendering the same context provider

### ISSUE THREAD

**Issue by JayKan** [facebook/react#13177]
**Do you want to request a *feature* or report a *bug*?** 
- Bug I assume 

**What is the current behavior?**
```javascript
console.error node_modules/fbjs/lib/warning.js:33
    Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
```

**Steps to reproduce the behavior**:
- `git clone https://github.com/JayKan/react-multiple-renderers-error`
- `cd react-multiple-renderers-error`
- `yarn`
- `yarn test`
- See __README__ on how to get rid of the error 

**What is the expected behavior?** 
- No warning I guess 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- node: 8.11.1
- npm: 6.1.0
- yarn: 1.7.0
- react: 16.4.1
- react-dom: 16.4.1
- react-test-renderer: 16.4.1

**Comment by JayKan** [comment]
FYI, current bug is not related to https://github.com/facebook/react/issues/13150 and https://github.com/facebook/react/issues/12498

**Comment by aweary** [comment]
@JayKan this is related to #13150. The root issue in #13150 was that `react-test-renderer` and `react-dom` weren't working together with Context, which is the same issue you're seeing here. This was fixed https://github.com/facebook/react/pull/13164, which will be included in the next release.

**Comment by scott8013** [comment]
I have same issue 😂
