### ISSUE TITLE
SVG in <object> tag leads to Uncaught TypeError

### ISSUE THREAD

**Issue by sean256** [facebook/react#13170]
I have a coderpad which replicates the issue. Take a peek at the console when it runs: https://codepen.io/anon/pen/LrwmGZ#anon-signup

It outputs 2 errors:

`Cannot use 'in' operator to search for 'animation' in undefined`
`Uncaught TypeError: Cannot read property 'textContent' of null`

I can replicate it in the 2 versions I tried: 15.6.1 and 16.4.1.

I also popped the `<object>` tag into an ancient version I found in a coderpad template and it threw the error there as well. It was 0.13.0

**Comment by sean256** [comment]
I think the problem lies in https://github.com/facebook/react/blob/07fefe33310849df81836c1c2e773b7d50c3ec2b/packages/react-dom/src/events/getVendorPrefixedEventName.js

```js
  for (const styleProp in prefixMap) {
    if (prefixMap.hasOwnProperty(styleProp) && styleProp in style) { // style here is undefined
      return (prefixedEventNames[eventName] = prefixMap[styleProp]);
    }
  }
```

```js
if (canUseDOM) {
  style = document.createElement('div').style; // this must be returning undefined when in the <object>?
...
...
```

**Comment by aweary** [comment]
@sean256 what browser are you using? Your example runs fine for me in Chrome 67.0.3396.99 , Firefox 59.0, and Safari 11.0.3 on macOS.

**Comment by sean256** [comment]
@aweary I just tried on my work laptop and had the same error which lead to to compare my home machine and work machine... And it's the "JSON Viewer Awesome" extension causing it!

I'm gonna go ahead and close this, thanks and apologies for wasting your time.
