### ISSUE TITLE
When use ReactDOM.createPortal and ReactDOM.unmountComponentAtNode, memory leak

### ISSUE THREAD

**Issue by chinafootballyu** [facebook/react#13191]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When i click the destroy button, The page is expected to become blank. When i check the chrome memory, can see some Detached Element. I think memory leak.

![image](https://user-images.githubusercontent.com/15266646/42574151-8ac74a62-8550-11e8-8df7-9287d7a6d9db.png)

**What is the expected behavior?**

No Detached Element. 

![image](https://user-images.githubusercontent.com/15266646/42573991-266cf846-8550-11e8-9fe2-9a4edf4e291b.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

"react": "^16.4.1"
"react-dom": "^16.4.1"

Code like: 

```js
import * as React from 'react'
import * as ReactDOM from 'react-dom'

const app = document.getElementById('app') as Element

class PortalTest extends React.Component {
  render() {
    return ReactDOM.createPortal(
      <div>Test</div>,
      document.body
    )
  }
}

class PortalApp extends React.Component {
  render() {
    return [
      <PortalTest key="test" />,
      <div key="hello">Hello</div>,
      <button key="button" onClick={() => {
        const bool = ReactDOM.unmountComponentAtNode(app)
        console.log(bool)
      }}>destroy</button>
    ]
  }
}

ReactDOM.render(
  <PortalApp />,
  app,
)

```

**Comment by gaearon** [comment]
I can only reproduce this in development build, but not in production builds.

We do have some DEV-only memory leaks, but those are temporary too.
For example if you render some other component, those nodes will be released.

**Comment by chinafootballyu** [comment]
@gaearon thanks
