### ISSUE TITLE
Longterm support for Internet Explorer

### ISSUE THREAD

**Issue by a-reuss** [facebook/react#13204]
**feature**

I'd like to know how the current roadmap for support of the Internet Explorer (namely the IE11) is. Is there a time frame for which react guarantees IE support and if yes for how long?

Best regards and thanks for any answer!

**Comment by nhunzaker** [comment]
Hello!

Presently we support down to IE9. To my knowledge, we do not have an official stance on a timeline for support. 

@aweary is there anything like this that you know of?

**Comment by a-reuss** [comment]
@nhunzaker 
Hi, thanks for the fast reply! 

To give you some background: we are working on a bigger project adressing a really heterogeneous customer crowd and IE users make up a considerable share of them. Those customers are using IE because they are bound to do so. Therefore we are bound to support IE for a long time to come.

**Comment by aweary** [comment]
There's no official timeline for our browser support matrix unfortunately. We usually discuss browser support in terms of Facebook and the browsers it needs to support, so maybe @sophiebits can provide some insight here.

I know we've discussed dropping IE9 support in the near future. IE11 is still pretty common so I expect that to be supported for awhile. To be clear, when we stop supporting a browser that just means we won't explicitly work around browser-specific bugs. In a lot of cases I expect that more modern browsers (including IE11) will continue to work far past their support period.

**Comment by mgol** [comment]
FWIW, Microsoft has announced stopping all official support for IE<11 in January 2020, even on Windows Server & Embedded where it's been supported way longer than in consumer versions of Windows:
https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/Bringing-Internet-Explorer-11-to-Windows-Server-2012-and-Windows/ba-p/325297

**Comment by Jessidhia** [comment]
It has been announced that, with React 18, support for Internet Explorer will be removed; but I wonder what specifically that entails. Is it just removing polyfills / packaging modern syntax, which can still be addressed bundler-side, or is React going forward simply expected to crash in IE / bug reports or fixes will not be accepted?

**Comment by gaearon** [comment]
IE needs some extra polyfills in React 18 (Symbol, maybe something else). At the moment it isn't completely broken but we won't take _new_ bugfixes for IE starting with React 18. We'll try not to break it completely until 19 but we'd prefer not to commit to this strongly. I'd suggest to check every patch manually if you rely on IE working. If we break it accidentally, I think we'd be open to fixing what we broke unless it's too big of a change. But the official line is "it's not supported" and we recommend staying on 17 if you care about it.
