### ISSUE TITLE
Deep react state with only context API

### ISSUE THREAD

**Issue by dakom** [facebook/react#13203]
I'm considering a total rewrite of a decent-sized application and I've got this idea brewing, but I'm wondering if it'll scale or if there's any changes I should make at the planning stage:

https://codesandbox.io/s/1rj55k32zq

Specifically does having different contexts offer any advantage in a case like this, where both are Provided at the same root, but Consumed at far different frequencies? In other words, should I just consolidate the `AppUpdater` into `AppState` even though `Buttons` isn't interested in State in terms of rendering?

Also, though this has less to do with Context, my concern is that keeping all the app state at the top level will cause unnecessary renders...

I guess this comes back to the age-old question of Redux connectors vs. efficiency of PureComponents - but I don't think my app is at the scale where it really needs that sort of optimization of Redux, and I think I can use PureComponents in key areas for speed gains if it really comes to that... would be nice if there's hard data available somewhere about when to consider an alternative, even if very rough.

**Comment by fateleak** [comment]
same issue to me~

**Comment by TrySound** [comment]
It's not quite an issue. I split app state in many contexts. For example modals, relay, locales. For data management yes, you will need some kind of selectors mechanism. I think react copy write will work fine here.

**Comment by dakom** [comment]
OK I thought a little more about it and I think I can close this...

If the nested child is only wrapped with `withUpdate()`, e.g. it receives `update`, as a prop but not `state`, then it re-renders only as often as its _parent_ - and if it's a PureComponent, won't even re-render then (because its props didn't change at all).

So even if it's only an advantage on those edges, it _is_ an advantage, and splitting context like this can be a performance win.
