### ISSUE TITLE
Warning is logged as an Error

### ISSUE THREAD

**Issue by FL0RIANMEYER** [facebook/react#13202]
Warning: Each child in an array or iterator should have a unique "key" prop.

Expected this as Console.warn() with fallback to Console.error()

**Comment by jquense** [comment]
Hey there, react warnings use console.error intentionally so they are more visible. React warnings are also generally considered to be really errors, just not so much it makes sense to crash your program, they are things that really should be fixed. Console.warn is reserved for less serious api deprecation warnings

**Comment by FL0RIANMEYER** [comment]
Why not go one level down.
Errors should be erros.
Warnings should be things that really should be fixed.
Infos are for less serious api deprecation warnings.
