### ISSUE TITLE
[shouldComponentUpdate] It's too difficult to override a good shouldComponentUpdate method

### ISSUE THREAD

**Issue by bolan9999** [facebook/react#13207]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

I want to prevent my component from re-rendering  when some special props have changed because the performance is too bad on Android. But I find it is too difficult to make it prefect.

I'v read the official document, it looks like this:

```
shouldComponentUpdate(nextProps, nextState) {
    if (this.props.color !== nextProps.color) {
      return true;
    }
    return false;
  }
```
But it is hard to negative comparison. 

Then I'v tried lodash, but failed ,too. Because the `isEqual` method in lodash can not compare DOM node while props.children is a DOM node.

Now I have to change these special props to component instance method. Anyone can help me?

**Comment by bolan9999** [comment]
I urgently need the changed props.

**Comment by gaearon** [comment]
I don't understand what you're asking. Use `React.PureComponent` if you want a shallow comparison.

In general, we use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by bolan9999** [comment]
shouldComponentUpdate is a bad feature!
