### ISSUE TITLE
Array of checkboxes with keys cannot be reordered.

### ISSUE THREAD

**Issue by jamesknelson** [facebook/react#13214]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When:

- render an array of checkboxes with unique keys, and a reverse button, via `ReactDOM.render`
- reverse the array, then re-render using `ReactDOM.render`
- the DOM nodes are not reordered

You can test this by checking some of the checkboxes [on this codesandbox](https://codesandbox.io/s/24j0v3wr90) and clicking 'reverse' (the checkboxes are uncontrolled).

When no keys are given, React emits the usual no keys warning.

**What is the expected behavior?**

The DOM nodes should be reordered when the reordered array is rendered.

You can get the expected behavior by wrapping the `checkboxes` array in a div. [See this codesandbox](https://codesandbox.io/s/my11r6mmpp).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested on 16.3.2 and 16.4.1 in chrome / mac os - both versions have the same issue.

**Comment by nmain** [comment]
Your two codesandboxes seem to contain the exact same code?

Anyway, React is skipping a child reconciliation because `newChild === oldChild`.  See this fixed version: https://codesandbox.io/s/61rmk0rr03

In general, it's a bad idea to mutate these sorts of things, but I don't know if this is expected behavior.

**Comment by aweary** [comment]
Yes, this is expected behavior. `reverse` does an in-place mutation, which means React cannot tell that it was updated. Creating a new array and reversing that is the recommended approach.
