### ISSUE TITLE
Inline style border and borderColor diff error

### ISSUE THREAD

**Issue by derekstavis** [facebook/react#13217]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
When alternating between inline styles `{ borderLeft: '1px solid white' }` and a merge of it with
`{ borderColor: 'red' }`, the white border is painted at the first render but a black border is painted
when the `borderColor: 'red'` property is removed:

![jul-16-2018 13-44-43](https://user-images.githubusercontent.com/1611639/42782668-6d325300-88fe-11e8-809b-04248e7f087c.gif)

**Stackblitz example:**
https://stackblitz.com/edit/react-dofznv

**What is the expected behavior?**
Going back to white border, just like the first render.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- React 16.1.1 and 15.x.
- macOS
- Google Chrome, Safari

**Comment by nmain** [comment]
I don't think React has much leeway to do anything else so long as it has to diff a style object for you.  Consider the following non-react code, which will cause the same exact issue:
```
var d = document.createElement("div")
d.textContent = "foo"
d.style.borderColor = "blue"
d.style.borderLeft = "10px solid green"
d.style.borderColor = null
document.body.appendChild(d)
```

When you provide multiple keys in your style object that aren't actually independent from each other (both `borderLeft` and `borderColor` short forms include `borderLeftColor` in them), this will happen.

**Comment by derekstavis** [comment]
Hey! Thanks for the example!! It makes a lot of sense now, React is just being consistent with what would happen in a non-React environment.

With this in mind I'm closing this issue as it's not a React bug. Thanks again!

**Comment by nhunzaker** [comment]
Cool. Thank you @nmain!
