### ISSUE TITLE
Identify different instances of react component in performance measures

### ISSUE THREAD

**Issue by rtrg** [facebook/react#13223]
**Do you want to request a *feature* or report a *bug*?**
**feature**

Can fiber._debugID also be part of performance measure [label](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactDebugFiberPerf.js#L91) along with component name/displayName?

to distinguish/track multiple instances of a react component in performance measures, please let me know if there is any other way already available to achieve this.

**Comment by gaearon** [comment]
I'm concerned this will make timings pretty noisy. Do you want to send a PR so we can take a look?
