### ISSUE TITLE
Cannot re-render child component. 

### ISSUE THREAD

**Issue by jazkh** [facebook/react#13228]
Load (child) will send data to Parent component then it will be set in state and passed down to Backbutton (child).

Backbutton (child) will return the props back to the parent when clicked. Parent will set state based on the return data and pass it down back to Load (child) component.

Problem: For couple of clicks it works fine, but then it stops re-rendering Load (child) component. Parent logs shows that it is receiving data from Backbutton (child) but somehow it does not show logs in Load.

**Parent:**
```
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      loadDirs: '',
      backDirs: ''
    }
  }  

getLoad = (info) => {
    this.setState({ loadDirs: info });
  }

  goBack = (instruct) => {
    this.setState({ backDirs: instruct },
      () => { console.log(this.state.backDirs) });
  }

render() {

   return (
          <div> 
             <Backbutton dirs={this.state.loadDirs} backbutton={this.goBack} />
              <Load backload={this.state.backDirs} load={this.getLoad} />  
           </div>
       );
     }
}
```
**Backbutton (Child):**

```
class Backbutton extends Component {
    constructor({props, dirs}) {
        super(props, dirs);
    }

    prevLink(info) {
        let backlink = info.toString().substr(0, info.toString().lastIndexOf('/') + 0);
        console.log(backlink);
        this.props.backbutton(backlink);
    }


    render() {

        return (
            <button key={this.props.dirs} 
            onClick={() => { this.prevLink(this.props.dirs) }}>
            Back</button>

        )
    }
}
export default Backbutton;

```
**Load (Child):**

```
....
  componentDidUpdate(prevProps) {
  if (this.props.backload !== prevProps.backload) {
    console.log(this.props.backload)
    this.allFetch(this.props.backload);
  }
}
....
```

**Comment by jazkh** [comment]
Am i hitting some react bug or missing something?

**Comment by jazkh** [comment]
I m very much confused on how to re render Load (child) completely when props changes. As per react doc, i am using componentDidUpdate lifecycle but without any luck. I would be really grateful if someone can help me fix this issue. Its been a long time i cannot figure it out.
I was thinking to use refs so i can call Load method (this.allFetch) inside Parent but then again it is not recommended way as per react docs.

**Comment by songkrod** [comment]
Hi Jazkh.

I think you need to bind this in parent component first like this

```
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      loadDirs: '',
      backDirs: ''
    };

   // need to do this
    this.getLoad = this.getLoad.bind(this);
    this.goBack = this.goBack.bind(this);

  }
} 
```

because your child component is a state full component too that mean all of your component have its own state and when you call getLoad and goBack it execute and try to set state via

`
this.setState(...)
`

 but 'this' mean it self. so you need to bind this first for told your both function to know that 'this' command mean Parent not you.

hope this help :)

**Comment by sgal** [comment]
@jazkh In `Backbutton.js` component, fix the constructor like following
```
class Backbutton extends Component {
    // constructor({props, dirs}) {
    //    super(props, dirs);
    // }
    constructor(props) {
        super(props);
    }
```
`dirs` is part of props. In your case you are initializing react component with undefined, because prop `props` is not available in `props`.
