### ISSUE TITLE
Using keyboard events impedes media recordings

### ISSUE THREAD

**Issue by Je4hel** [facebook/react#13238]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**  
When attaching an event handler to the window (or document or body, or anything else, it seems) that will fire on keyboard events (`keyup`, `keydown`) to start/stop a recording with a `MediaRecorder`, some recordings are trimmed at the beginning.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**  
CodeSandbox cannot use Web Audio API it seems so I hosted the app on GitHub pages [here](https://je4hel.github.io/mozrec-react-app/). You can access the source code on [the repository](https://github.com/Je4hel/mozrec-react-app).

Steps:

1. Click `Start` to start recording
1. Say a word
1. Click `Stop` and play the audio file
1. -> No problem

Using the arrow keys:

1. Use the left arrow key to start the recording
1. Say a word
1. Use the right arrow key to stop the recording
1. Play the audio file
1. -> The beginning of the speech is trimmed

*Note: it doesn't happen every time and it seems that it may depend on the word that is pronounced. In French, the following (fake) words induce the problem: `dul` (`/dyl/`) and `couciron` (`/kusiʁɔ̃/`). I don't know a word which causes the problem in English.*

**What is the expected behavior?**
The recordings should be the same whether I use the arrow keys or the buttons to start the recording.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
The sample I provided is version 16.4.1. Originally, I face the issue in a project using version 16.0.0. I am working on Windows  with Chrome.

**Comment by Je4hel** [comment]
I tried and could not reproduce.

**Comment by aweary** [comment]
@Je4hel can you please share what you tried so we can attempt to reproduce as well?

**Comment by gaearon** [comment]
Closing per lack of response
