### ISSUE TITLE
Render single react component instead of complete application from server

### ISSUE THREAD

**Issue by rishabh1403** [facebook/react#13257]
I went through many articles on server side rendering of react and the all of them has the following in common :-

- The server route renders a complete html page with a div which wraps the root react component, just like traditional react code
- it also includes reference to a bundle.js which is called by browser once the skeleton is loaded and the view re-renders with all javascript functionality.
This approach always leads me to download my whole frontend app in one go. Is there any way where I can selectively render react components in divs? . What I mean to say is, for example "/graph" only gives me graph component, "/table" only gives me table component etc so that :-

-I can embed react components into a pre-existing webapp.

The response from the routes are just smaller components instead of the whole outer root component. I know react can be embedded in other web apps in case of client side rendering, but I am wondering if same thing can be achieved in server side rendering. Thanks.

**Comment by aweary** [comment]
Hey @rishabh1403! You can render as much or as little content as you'd like with server rendering. If you want to render multiple React roots that's totally doable (Facebook does it!). You'll just have to include a `ReactDOM.hydrate` call for each root if you want them to be interactive.

For future reference, we use the issue tracker for bug reports and feature requests only.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
