### ISSUE TITLE
getDerivedStateFromProps lifecycle has a abnormality

### ISSUE THREAD

**Issue by Ssis53** [facebook/react#13255]
Recently I found a problem with my react demo.
![image](https://user-images.githubusercontent.com/33656230/43111730-11a15176-8f25-11e8-8d5b-2736c4933cbb.png)

After setState, the second argument  of the lifecycle should be prevState, but  actually it's more like nextState.

react-dom version: 16.4.0

**Comment by Ssis53** [comment]
`class IndexPage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      num: 0
    }
    console.log('constructor');
  }

  // UNSAFE_componentWillMount(nextProps, props) {
  //   console.log('willMount',this.state);
  // }  

  componentDidMount() {
    console.log('didMount----------this.state:',this.state);
  }

  // UNSAFE_componentWillReceiveProps(nextProps, props) {
  //   console.log('willReceiveProps',this.state);
  // }

  static getDerivedStateFromProps(nextProps, prevState) {
    // ...
    console.log("getDerivedStateFromProps----------prevState:",prevState);
    return null;
  }

  shouldComponentUpdate(nextProps, props) {
    console.log('shouldComponentUpdate----------this.state:',this.state);
    return true;
  }

  // UNSAFE_componentWillUpdate(nextProps, props) {
  //   console.log('willUpdate',this.state);
  // }
  getSnapshotBeforeUpdate(prevProps, prevState) {
    // ...
    console.log("getSnapshotBeforeUpdate----------this.state:",this.state, '------------prevState:',prevState);
    return null;
  }

  componentDidUpdate(nextProps, props) {
    console.log('didUpdate----------this.state:',this.state);
  }

  componentWillUnmount() {
    console.log('componentDidUnmount');
  }

  add() {
    this.setState((state) => (
      {
        num: state.num + 1
      }
    ));
    console.log('******************setState*****************');
  }  

  addByDelay() {
    setTimeout(() => {
      debugger
      this.setState({
        num: this.state.num + 1
      });
      this.setState({
        num: this.state.num + 1
      });
    }, 0)
  }

  render() {
    console.log('render');
    return (
      <div className={styles.normal}>
        <button onClick={() => {this.add()}}>setState</button>
        <button onClick={() => this.addByDelay()}>setStateDelay</button>
        <div>
          <h1>
            {this.state.num}
          </h1>
        </div>
      </div>
    );
  }
}`

**Comment by aweary** [comment]
@Ssis53 if you look at the [`getDerivedStateFromProps` documentation](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) you'll see that the argument aren't called `nextProps` or `prevState`. They're just `props` and `state`.  The reason for this is that gDSFP is called when props change _or when state is updated_, so the `state` argument there will be always be the current state. 

Check out the blog post [You Probably Don't Need Derived State](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) for more information.

**Comment by Ssis53** [comment]
![f9082268-233a-44ce-8167-37b0769c6367](https://user-images.githubusercontent.com/33656230/43112890-a1c22320-8f2a-11e8-99a6-47f1721a7983.png)
Ok, thanks for your answer, but I see the react-dom.js is prevState...
why?
@aweary
