### ISSUE TITLE
Getting SSR to work with the React Context API

### ISSUE THREAD

**Issue by maniator** [facebook/react#13251]
Basically we have a module that reads the client data on server side render and is supposed to provide the data to the renderToString with the data it found (and the client renders with a `window.__SOME_DATA__`, but I would not want to use a global on a express route)

Here is where we are:

    const contentService = new ServerService();
    const app = (
      <StaticRouter context={context} location={req.url}>
        <App/>
      </StaticRouter>
    );

    try {
      await contentService.getSomeData(app);
    } catch (error) {
      console.log('THERE WAS A MARKUP ERROR', error);
    }

    const markup = renderToString(
      contentService.withProvider(
        app
      )
    );

The server service looks like so:

    export class ServerService {
      items = {};
    
      getSomeData = async (app) => {
        // gets some server side data and saves it to the `items` object
      };
    
      withProvider = (app) => {
        const providedApp = (
          <ServerProvider data={this.items}>
            { app }
          </ServerProvider>
        );
    
        console.log('ITEMS provided', { data: this.items });
    
        return providedApp;
      };
    
      getScriptData() {
        return `
          <script>
              window. __SOME_DATA__ = ${JSON.stringify(this.items)};
          </script>
        `;
      }
    }

And then last but not least my provider:

    import * as React from 'react';
    
    const ServerContext = React.createContext(null);
    
    export class ServerProvider extends React.Component {
      render () {
        console.log('Providing data', { props: this.props });
    
        return (
          <ServerContext.Provider value={{ ...this.props.data }}>
            {this.props.children}
          </ServerContext.Provider>
        );
      }
    }
    export const ServerConsumer = ServerContext.Consumer;

The problem is that it seems to set the data in the `withProvider` function fine, but when I use the `ServerConsumer` component, it seems to contain **nothing** -- but it _should_ contain the data that was passed to the provider!

The context api has worked beautifully for when I need it on the client side, but it seems to be failing for me on the server side.

This is with react/react-dom `16.4.1`

(originally posted here: https://stackoverflow.com/q/51485320/561731)

**Comment by maniator** [comment]
Here is how I am using the consumer:
    
    import * as React from 'react';
    import { ServerConsumer } from "./serverContext";
    import { ContentStateProvider } from "./ContentStateProvider";

    const renderChildrenWithServerData = (props) => (state, ...rest) => {
      console.log({ state, props, rest }, 'I AM DATA', ServerConsumer);
    
      return (
        <ContentStateProvider currentState={state} {...props} />
      );
    };
    
    export class ContentProvider extends React.Component {
      render() {
        // console.log({ Consumer }, 'CONTEXT is cool');
        return (
          <ServerConsumer>{renderChildrenWithServerData(this.props)}</ServerConsumer>
        );
      }
    }

**Comment by gaearon** [comment]
Can you provide a complete isolated example we could run, please?

**Comment by maniator** [comment]
@gaearon All of the code (aside for the express server part) is a part of a closed source project we are working on (hoping to open source in the next couple of weeks) 

What can I provide to you (aside for the code above) that will help in debugging this issue?

I am have been working on this for the better part of a day and a half and have not got any closer to where I was when I started.

**Comment by maniator** [comment]
@gaearon if it helps the "real" `getSomeData` function goes down the react tree to call functions on the react components

Basically using the `react-tree-walker` like in this example code: https://github.com/ctrlplusb/react-tree-walker#illustrative-example

**Comment by maniator** [comment]
@gaearon Here is an example repo using our unreleased lib: https://github.com/maniator/test-context

**Comment by maniator** [comment]
Basically it renders the page and then the data renders instead of it rendering with the data already in it.

**Comment by maniator** [comment]
It was a just a quick example that I could get up to show the issue in its fullest.

**Comment by maniator** [comment]
Give me a few minutes and I will try to clean it up without the extra code.

**Comment by aweary** [comment]
@maniator I cloned your example, but I can't reproduce your issue as described. The `ServerConsumer` context consumer is correctly rendering with the state pulled from `ContentStateProvider`. I do see a few issues here, though.

* `react-tree-walker` relies on internal properties/APIs that it shouldn't be using. For some reason it is [setting `_currentValue` on a React context element](https://github.com/ctrlplusb/react-tree-walker/blob/master/src/index.js#L118-L123). This is a very risky thing to do, and we can't account for libraries that mutate internal values.

* Your code is also relying on internal context properties. It [forks in render based on the internal `_currentValue`](https://github.com/maniator/test-context/blob/master/src/ContentProvider.jsx#L13).

Please only use the Context API that is [officially supported and documented](https://reactjs.org/docs/context.html). If you believe this an issue with React please try and reduce the example to exclude third-party libraries and clarify what behavior you're expecting.

**Comment by gaearon** [comment]
I filed this: https://github.com/ctrlplusb/react-tree-walker/issues/37

Definitely it’s unsupported and will only get worse in the future. Probably worth warning any libraries that depend on it.

**Comment by hamlim** [comment]
If you prevent client side JS from running (you can disable it in dev tools), you will see that the context correctly works on server render. The issue you may be running into is that you never render a Provider when you hydrate on the client, which means that you will end up rendering a Consumer that falls back to the default context value (`null` in your example).

As what @aweary stated above, his second bullet point is where you run into an issue specifically, because `ServerConsumer._currentValue` is always truthy (during both the SSR phase and the client side hydration phase).

**Comment by gaearon** [comment]
Can you please create an isolated example that uses plain ReactDOMServer/ReactDOM, no other third party libraries, and demonstrates an issue?

**Comment by gaearon** [comment]
I don't understand how to reproduce this. I cloned https://github.com/maniator/test-context and ran `yarn start`. I added the

```js
  console.log({ state, props, rest }, 'I AM DATA', ServerConsumer);
```

log from your comment above.

I am seeing both the provided "data":

<img width="413" alt="screen shot 2018-08-16 at 10 33 27 pm" src="https://user-images.githubusercontent.com/810438/44236300-6a01a000-a1a4-11e8-8a6a-355f83733c17.png">

and it being available to the consumer:

<img width="575" alt="screen shot 2018-08-16 at 10 33 50 pm" src="https://user-images.githubusercontent.com/810438/44236319-7685f880-a1a4-11e8-8ea6-39eacfddcfcb.png">

I don't know what you expect to see but to me, there doesn't seem to be anything wrong with how context works. If you're confident the issue is React-related, please try to create a more focused example *and* provide instructions for reproducing ("actual" vs "expected" behaviors). Thanks!
