### ISSUE TITLE
extend react-test-renderer to inline external css

### ISSUE THREAD

**Issue by yoerivdm** [facebook/react#13266]
Currently looking into some testing with Jest and react-test-renderer .. 

I was wondering if react-test-renderer could be 'extended' to make it inline external css when creating snapshots. Snapshot-testiong components is great, (optionally) inlining css and snapshot-testing would be even better.

**Comment by gaearon** [comment]
It's not very clear to me what exactly you're proposing.
If you have ideas on changes to React APIs, feel free to propose here! https://github.com/reactjs/rfcs
Thanks.
