### ISSUE TITLE
Uncaught ReferenceError: ReactDOMServer is not defined

### ISSUE THREAD

**Issue by OrionWambert** [facebook/react#13262]
Hello everyone I work on a Java Web project using react and jquery to render dynamic web pages. So I wanted to use the function ReactDOMServer.renderToStaticMarkup (element) to retrieve the html nodes related to the html element but I receive as an error:

**Uncaught ReferenceError: ReactDOMServer is not defined**

I also searched the net to find cdn ReactDOMServer to correct the error but other errors occur. Here is a sample code:
[https://stackoverflow.com/questions/51503425/uncaught-referenceerror-reactdomserver-is-not-defined]()

**Comment by aweary** [comment]
If you're trying to run `ReactDOMServer` in the browser you'll need to use the correct build. The regular `react-dom.development.js` file does not contain `ReactDOMServer`. You'll want the [`react-dom-server.browser.development.js](https://unpkg.com/react-dom@16.4.1/umd/react-dom-server.browser.development.js) UMD build. 

Make sure you use the [production build](https://unpkg.com/react-dom@16.4.1/umd/react-dom-server.browser.production.min.js) in production as well!

**Comment by OrionWambert** [comment]
Thank you very much I just tested it works properly thanks again !
