### ISSUE TITLE
constructor call is fired when i try to dispatch the Action from Navbar Component

### ISSUE THREAD

**Issue by SRIDHERKUMAR** [facebook/react#13263]
**Do you want to request a *feature* or report a *bug*?**
YES
**What is the current behavior?**

**<HashRouter>
                <div className="app-container">
                    <Navbar />
                       <Switch>
                        <Route exact path="/" render={() => <abc />} />
                        <Route path="/configuration" render={() => <xyz />} />
                        <Route path="/entry" render={() => <entry />} />
                        </Switch>
                </div>
            </HashRouter>**
**The current behavior is when i try to dispatch an action from Navbar Component , all the route Components(abc, xyz, entry) constructor call is firing. which results in resetting the all the Components in initial State.**

**What is the expected behavior?**
The expected behavior is just to dispatch that action form Navbar Component.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
No, the Behavior is same in all the react versions. I am using Google Chrome in Mac OS

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
