### ISSUE TITLE
[question] bind(this) does not work and cannot update state by setState

### ISSUE THREAD

**Issue by Koshukey** [facebook/react#13273]
I'll tell you beforehand that I know there are a lot of questions that setState does not work in StackOverflow. And I read them all. However, I cannot solve this problem.

I cannot believe that I cannot update state by setState. I want to update cardModalOpen state to close the Modal.

I add bind(this) but it still does not work.

(Modal is opened by click Card Component)

However, I did setState({cardModalOpen: false}) by closeModal() function but it is still true even after render method was called.

Can someone please explain what I am doing wrong.

This is my code.

index.js
```
import React, { Component }from 'react';
import { Button, Card, Image, Header, Modal, Form, Input } from 'semantic-ui-react'

class App extends React.Component {    
    state={

        cardModalOpen:false

    }


    showCardModal(){

        this.setState({cardModalOpen:true})



    }

    closeModal(){

        this.setState({cardModalOpen:false})


    }

    render(){

        return (

 <DetailModal cardModalOpen={this.state.cardModalOpen} closeModal={this.closeModal.bind(this)} />


        )
    }
}


```

ModalDetail.js
```
import React, { Component }from 'react';
import { Button, Card, Image, Header, Modal, Form, Input } from 'semantic-ui-react'

class DetailModal extends Component{

render(){

    return(
        <Modal open={this.props.cardModalOpen} onClose={()=>{this.props.closeModal()}} >
            <Modal.Header>Select a Photo</Modal.Header>
            <Modal.Content image>
                <Image wrapped size='medium' src='https://react.semantic-ui.com/images/avatar/large/rachel.png' />
                <Modal.Description>
                    <Header>Default Profile Image</Header>
                    <p>We've found the following gravatar image associated with your e-mail address.</p>
                    <p>Is it okay to use this photo?</p>
                </Modal.Description>
            </Modal.Content>
            <Button onClick={()=>{this.props.closeModal()}}>Close</Button>
        </Modal>
    )
  }



  }

export default DetailModal;

```

**Comment by aseem191** [comment]
I believe this thread deals with the same issue: https://github.com/Semantic-Org/Semantic-UI-React/issues/901

**Comment by raunofreiberg** [comment]
https://codesandbox.io/s/pjzx87zoyq

Seems to work fine for me.

**Comment by Koshukey** [comment]
Thanks for advices!!! @raunofreiberg  @aseem191 

However still i cannot solve this.

Here is my code sandbox.

codesandbox.io/s/jjk7nw647y

**Comment by Koshukey** [comment]
finally, I solved !!!!!!!!!!!!!!!!!!!!!!💪💪💪💪💪💪💪

The cause of this problem is that I try to give the state to the Card component and Modal component and when I do setState, the modal component state was created but it does not influence Card Component state, I guess.
P.S   @aseem191 Thanks for good reference! It leads me to solve this problem!!! 😬😬😬

I changed like 
```
showCardModal(){

        this.setState({cardModalOpen:!this.state.cardModalOpen})


    }
```

**Comment by nmain** [comment]
The `DetailModal` is a child of the `Card`, so the `onClick` handler in the `Card` that opens the modal will fire whenever you click inside the modal, including on the close button in the modal.  This is not a React issue.

**Comment by Koshukey** [comment]
Ohhhhh,  thank u !!!!
exactly...  I should notice that .......
