### ISSUE TITLE
Add ESM build to react-is

### ISSUE THREAD

**Issue by pgarciacamou** [facebook/react#13272]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Unable to import individual modules from the package.

```jsx
import * as ReactIs from "react-is";
ReactIs.isValidElementType(<div />); // true
```

**What is the expected behavior?**

```jsx
import { isValidElementType } from "react-is";
isValidElementType(<div />); // true
```

**Context**

This issue arose when trying to to make `react-redux` work with `React.forwardRef` ([see this PR](https://github.com/reduxjs/react-redux/pull/971)), but evidently, `react-is` doesn't allow import/export ESM to enable tree shaking capabilities in `react-redux` (that is my understanding).

This issue is following [this comment](https://github.com/reduxjs/react-redux/issues/914#issuecomment-377406113).

I tried solving this (and totally failed) in https://github.com/facebook/react/pull/13250 before I realised anything about ESM. But this is now over my head, so I'm creating an issue now and see how that follows.

**Comment by AviVahl** [comment]
https://github.com/facebook/react/issues/11503

**Comment by gaearon** [comment]
You can't make it work by changing the source — you'll want to change the build scripts (`scripts/rollup/*`) to target an ESM build.

**Comment by TrySound** [comment]
FYI I'm working on this.

**Comment by kentcdodds** [comment]
Could we change this issue (or should I open a new issue) to apply this to all react packages? Rollup has trouble when dependencies use React like it has an ESM export but it actually doesn't :-(

Ref: https://github.com/reach/reach-ui/pull/74

**Comment by TrySound** [comment]
Not stale.

**Comment by jacksteamdev** [comment]
Not stale.
