### ISSUE TITLE
using server side js classes in react app

### ISSUE THREAD

**Issue by npomfret** [facebook/react#13287]
Is there a sensible way to include use classes that I run on a nodejs server, in my react app?

I tried adding a symlink to a source directory in my server code in an attempt to just directly reference the node js files containing the classes.  But the nodejs server side code uses `require` and `module.exports` instead of `import` and `export` and I get errors like: _'./domain/model' does not contain an export named 'Util'_.  I guess this is caused by mixing up the two syntaxes?

So, is there a sensible way to achieve this?

The two code bases are in a single repo.  i don't care about the difference between `require` and `import`, or `export` and `module.exports`, happy to use either of them.  I tried converting the server code to `'mjs` files on but react didn't seem to recognise them.  

To be honest I'm staggered how difficult I've found this.  Share code written in the same language can't possibly be this hard.

My last resort  (not tried yet) is to try using _mjs_ files on the server again, and symlink them individually so they appear in the react code base, but change the file extension of _.js_.  Crazy.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
