### ISSUE TITLE
Question: is rendering of react internal attributes possible in browser environment?

### ISSUE THREAD

**Issue by manubb** [facebook/react#13283]
Is there an option i can pass to ReactDOM.render in order to have extra DOM attributes that React uses internally, such as data-reactroot?
(So that serializing the DOM gives the same result as calling ReactDOMServer.renderToString.)
Thanks!

**Comment by aweary** [comment]
Hey @manubb. There is no option to include those attributes with `ReactDOM`. They are meant to be for internal use only, and you should avoid relying on their presence.

Thanks!

**Comment by manubb** [comment]
Hi @aweary. Thanks for your answer. 

Sorry to insist but i would like to do SSR in a browser controlled by the server (e.g, Puppeteer, jsdom, ...) and without such option, this is not possible.

Is there a chance to have this feature added in a future release?

**Comment by nmain** [comment]
You can use ReactDOMServer from within a browser and the `renderToString` function will return the same thing there as it would when run in node.js
