### ISSUE TITLE
Warning: The tag <webview> is unrecognized in this browser

### ISSUE THREAD

**Issue by mhuggins** [facebook/react#13299]
**Do you want to request a *feature* or report a *bug*?**
Bug (for electron users)

**What is the current behavior?**
When running jest, if any components containing a webview element are rendered, a warning is rendered to the console.  When many tests are run, the output is littered with warnings.

>     console.error node_modules/fbjs/lib/warning.js:33
>       Warning: The tag <webview> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://jsfiddle.net/Luktwrdm/859/

**What is the expected behavior?**
No warning is logged to the console.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.4.1
Electron: 2.0.6
Unknown if it worked in prior versions of react.

**Comment by gaearon** [comment]
What other special tags does Electron have?

**Comment by philipp-spiess** [comment]
Looking through their docs it seems to be only the `<webview>` tag for now: https://electronjs.org/docs/all#custom-dom-elements

**Comment by gaearon** [comment]
In that case I don’t mind adding it to the whitelist. Send a PR?

**Comment by mhuggins** [comment]
You beat me to the punch.  Thanks so much @gaearon!
