### ISSUE TITLE
Bug: flex-basis style property converts numeric-value to pixels-value by default

### ISSUE THREAD

**Issue by ixrock** [facebook/react#13290]
Current behaviour:
`style={{flexBasis: 2}}` // output: `style="flex-basis: 2px"`
Same conversion happening even if I provide `{flex: "1 0 0"}` // output: `flex: "1 0 0px"`

Expected behaviour:
`style={{flexBasis: 2}}` // output: `style="flex-basis: 2"` since it's valid css-value for this prop!

**Comment by flxwu** [comment]
In fact, if you take a look at the Mozilla docs, flex basis can also be applied as a fixed width determined with `px`

**Comment by ixrock** [comment]
@flxwu hmm... true, even devtools in chrome marks it as "invalid value"..
But it seems it works properly with just numeric value. 
Or I don't fully sure how browsers treat the value when it's a number..
Anyway, closing issue for now.. Thanks for clarification.

Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis
