### ISSUE TITLE
IE11 object doesn't support property or method remove

### ISSUE THREAD

**Issue by cis-ankity** [facebook/react#13291]
I'm facing the following issue with a React web application, when I've debugged the code found that - 

function dispose() {
      setTimeout(function () {
        _reactDom2.default.unmountComponentAtNode(wrapper);
        setTimeout(function () {
          **return wrapper.remove();**
        });
      }, unmountDelay);
    }

throwing the above error on line 'return wrapper.remove();' and I'm unable to change the code as it is from React's library.

Any hint to resolve the following problem?

**Comment by aweary** [comment]
Hey @cis-ankity. That code [isn't part of React](https://github.com/facebook/react/search?q=dispose&unscoped_q=dispose). You could try inspecting the source to see where this function gets called. If you have further questions, please check our community support resources:
https://facebook.github.io/react/community/support.html

Best of luck!
