### ISSUE TITLE
when I change the config(rollup/build.js),and set sourcemap:ture, build error

### ISSUE THREAD

**Issue by pws019** [facebook/react#13292]
Sourcemap is likely to be incorrect: a plugin was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help.

what should I do?

**Comment by gaearon** [comment]
This is not a question about React.

**Comment by pws019** [comment]
emnn....So Where should I go back to the question

**Comment by Terry-Su** [comment]
+1

**Comment by qianL93** [comment]
> +1

我最近先也想编译一下sourcemap，看到这个问题，不知道你们解决没哟。看了一下，只是因为给构建的时候加了一个自定义的transform方法没有返回map。根据rollup文档修改一下或者删掉（这个对development来说没啥用）
[在这](https://github.com/facebook/react/blob/master/scripts/rollup/build.js#L364)

**Comment by pws019** [comment]
@qianL93 官方不修确实没办法，不过我参考网上其他人的做法，研究了种方法。
看这个： https://segmentfault.com/a/1190000020239791
