### ISSUE TITLE
Create Form Using Json Data in ReactJs

### ISSUE THREAD

**Issue by mehuljariwala** [facebook/react#13308]
I need to create a form using JSON data. I'm done creating but when i run that time textbox showing me 5 times i need only one times textbox and select also print 5 times i need only 1 times can anyone help me that.

` 
       renderForm = () => {

       let MdData = this.props.ModelData;
    let MdMap = MdData.map(m => {
    let MdKey = m.key;
    let MdType = m.type;
    let props = m.props;
    console.log(1);

    return (
      <div key={MdKey} className="form-group">
        <label className="form-label" key={"lbl" + m.key} htmlFor={m.key}>
          {m.key + ". " + m.label}
        </label>

        <input
          {...props}
          ref={key => {
            this[m.key] = MdKey;
          }}
          className="form-input"
          key={"txt" + m.key}
        />
        <select key={"drop" + m.key}>
          {m.choices.map(function(data) {
            return (
              <option key={m.choices.keydrop} value={data.value}>
                {data.value}
              </option>
            );
          })}
        </select>
      </div>
    );
  });
  return MdMap;
}`

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
