### ISSUE TITLE
props.children slot feature

### ISSUE THREAD

**Issue by dahfazz** [facebook/react#13328]
_Feature request_

I'm thinking about the need of a sort of [slot](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots) feature introduced inside the props.children existing feature.

My proposal would be to allow the use of a specific directive inside children markup, let's say `children-slot-slotname` then on JSX side we would be able to write `{this.props.children.slots[slotname]}` instead of the uniq `{this.props.children}` 

More than the syntaxe, my intent here is to open the discussion and have a feedback about this eventual feature.

Thx

**Comment by TrySound** [comment]
You already have slots
```js
<Component
  icon={<Icon />}
  title={'title'}
/>
```

**Comment by gaearon** [comment]
Yes, you don’t need a special feature for this because in React UI elements are first-class entities so you can pass them around as regular props.

In fact there’s nothing special about the `children` prop except that JSX containment uses it, and that elements like `<div>` use its content.

However, technically 

```js
<Button><Icon /></Button>
```

is equivalent to 

```js
<Button children={<Icon />} />
```

And this is why something like 

```js
<SplitPane 
  left={<Sidebar />}
  right={<Content />}
/>
```

also works.

**Comment by inomdzhon** [comment]
Props may be good solution, but not readable if we say about developer experience :(

Slots by Svelte (or Web Components) looks more pretty.

Can you please check out my several examples with realise slot system https://1grnj.csb.app/slot-system

What kind of them is overhead or not a good practice?

Editor here https://codesandbox.io/embed/provide-i18n-and-styles-to-ui-kit-1grnj

Thank you!

**Comment by inomdzhon** [comment]
@TrySound @gaearon 
Props may be good solution, but not readable if we say about developer experience :(

Slots by Svelte (or Web Components) looks more pretty.

Can you please check out my several examples with realise slot system https://1grnj.csb.app/slot-system

What kind of them is overhead or not a good practice?

Editor here https://codesandbox.io/embed/provide-i18n-and-styles-to-ui-kit-1grnj

Thank you!
