### ISSUE TITLE
Why is shouldComponentUpdate called before this.setState's callback

### ISSUE THREAD

**Issue by mehulmpt** [facebook/react#13329]
**Do you want to request a *feature* or report a *bug*?**
Bug (probably)

**What is the current behavior?**

It seems unintuitive to me that `shouldComponentUpdate` is fired before `this.setState`'s callback. It should be the other way around. `this.setState`'s callback feels like it is called immediately after the state is updated, but actually `shouldComponentUpdate` method is called before the callback.

Here's the fiddle: http://jsfiddle.net/n5u2wwjg/123856/ Open devtools and you'll see in console what I'm trying to say.

**Fiddle**

http://jsfiddle.net/n5u2wwjg/123856/

**What is the expected behavior?**

I believe callback should be called before shouldComponentUpdate

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All

**Comment by gaearon** [comment]
`shouldComponentUpdate` is called to determine whether React should do a re-render or not. So it can't possibly run after `setState` callback. The purpose of `shouldComponentUpdate` is to give author an opportunity to prevent the update altogether — and by the time the `setState` callback fires it's too late.

**Comment by mehulmpt** [comment]
LOL I'm sorry for posting this. I don't know what exactly I was thinking. Thanks for your response @gaearon
