### ISSUE TITLE
Error Handling 

### ISSUE THREAD

**Issue by rahuls321** [facebook/react#13322]
**Difficult to Handle such kind of error !!**

It's very difficult to find out the bug whenever by mistake I use curly braces instead of parenthesis then console showing an error but not able to find out in which file you got error rather it shows the main building block file.

**Comment by gaearon** [comment]
Sorry, this report doesn't have any details (what error? what are you seeing? where are the screenshots?) so there's just no way we can help.

Additionally, it sounds like the error you're referring to is a *syntax* error so it's not something React can help you with.

If you provided more details maybe we'd be able to help you.
