### ISSUE TITLE
Prop for rendering an element iif it's children render

### ISSUE THREAD

**Issue by houdiiny** [facebook/react#13327]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
In every react project I've worked there is always some sort of code that looks like this:

```javascript
class MyComponent extends React.Component {
    render() {
        if (!this.props.foo && !this.props.bar && !this.props.foobar) return null;
        return (
            <div>
                {this.props.foo && <h2>{this.props.foo}</h2>}
                {this.props.bar && <h3>{this.props.bar}</h3>}
                {this.props.foobar && <h4>{this.props.foobar}</h4>}
            </div>
        );
    }
}
```

This looks ugly and not very scalable(imagine MyComponent has 15 children instead of just 3) but is (to my knowledge) the only way to achieve the intended behavior

**What is the expected behavior?**
A prop such as "nullIfEmpty"(naming sugestions are welcome) that defaults to false and if specified to true will not render an element with no children.

```javascript
class MyComponent extends React.Component {
    render() {
        return (
            <div nullIfEmpty={true}>
                <h2 nullIfEmpty={true}>{this.props.foo}</h2>
                <h3 nullIfEmpty={true}>{this.props.bar}</h3>
                <h4 nullIfEmpty={true}>{this.props.foobar}</h4>
            </div>
        );
    }
}
```

Looks better, scales better, and keeps my (*and probably not only my own*) OCD at ease.

**Comment by gaearon** [comment]
It looks better to you because you’re aware of the precise semantics of it (although I’m not sure about that either — see the last sentence in this paragraph). It won’t “look better” to somebody who’s not familiar with this operation. They’ll need to google what it means, how it handles edge cases, etc. I think in this case it imposes too much of a cost. Your first example can be understood by anyone familiar with JS and basics of React, but the second example requires a detailed understanding of how `nullIfEmpty` works. There are many open questions: for example, how does it work if passed to a custom component?

In general my suggestion is to avoid focusing too much on repetitive code like this. It doesn’t truly affect how your app “scales” because it is completely local. In fact I’d argue that *not* introducing an extra abstraction here scales better because you have precise control over what’s happening, and don’t need to apply special rules to guess the behavior.

However, you could make it a bit simpler by using a fragment:

```js
class MyComponent extends React.Component {
    render() {
        return (
            <React.Fragment>
                {this.props.foo && <h2>{this.props.foo}</h2>}
                {this.props.bar && <h3>{this.props.bar}</h3>}
                {this.props.foobar && <h4>{this.props.foobar}</h4>}
            </React.Fragment>
        );
    }
}
```

This lets us remove the first condition because there is just no need for a wrapping element. If neither child exists, no DOM nodes need to be emitted.

If you want to take it further, sure, you can add an abstraction, e.g.:

```js
function nullIfEmpty(content, wrap) {
    if (content === '' || content === false || content == null) {
        return null;
    }
    return wrap(content);
}


class MyComponent extends React.Component {
    render() {
        return (
            <React.Fragment>
                {nullIfEmpty(this.props.foo, foo => <h2>{foo}</h2>)}
                {nullIfEmpty(this.props.bar, bar => <h3>{bar}</h3>)}
                {nullIfEmpty(this.props.foobar, foobar => <h3>{foobar}</h3>)}
            </React.Fragment>
        );
    }
}
```

I don't find it much clearer but you can do it if you like. Or you can take it further:

```js
function omitEmptyChildren(fragment) {
    if (fragment.type !== React.Fragment) {
        throw new Error('Expected a fragment');
    }
    const newChildren = React.Children.filter(fragment.props.children, child =>
        typeof child.type === 'function' || (
          child.props.children != null && 
          child.props.children !== false && 
          child.props.children !== ''
        )
    );
    return <React.Fragment>{newChildren}</React.Fragment>
}


class MyComponent extends React.Component {
    render() {
        return omitEmptyChildren(
            <React.Fragment>
                <h2>{this.props.foo}</h2>
                <h3>{this.props.bar}</h3>
                <h4>{this.props.foobar}</h4>
            </React.Fragment>
        );
    }
}
```

In fact you can even make your own `Fragment` component that does this automatically. But again, I think it adds more complexity than it's worth, and won't handle more advanced cases anyway (like custom components).

Hope this helps!

**Comment by houdiiny** [comment]
@gaearon Thank you for the in-depth answer, I like your last solution because it doesn't polute the render method as much as mine.

> It won’t “look better” to somebody who’s not familiar with this operation. They’ll need to google what it means, how it handles edge cases, etc.

Well I agree the nomenclature could be clearer but being a new feature I believe everyone would have to google it's logic.

> There are many open questions: for example, how does it work if passed to a custom component?

Well I came across "the need" for this prop only for non-custom components. I think it should work as a normal prop if passed to a custom component.

> This lets us remove the first condition because there is just no need for a wrapping element. If neither child exists, no DOM nodes need to be emitted.

I actually need that element (should've made it clearer in the example my bad)

In almost all of my markup I have those small logics as in (if a node has no children/text then it does not render) and this is recursive like the e.g. as the issue.

> adds more complexity than it's worth

Agreeing with you on this statement perhaps you can help me by extending your last snippet to something that achieves the same result.

```javascript
function omitEmptyNodes(fragment) {
    if (fragment.type !== React.Fragment) {
        throw new Error('Expected a fragment');
    }
    
    // how can this be implemented? 

    return <React.Fragment>{newChildren}</React.Fragment>
}


class MyComponent extends React.Component {
    render() {
        return omitEmptyNodes(
            <React.Fragment>
                <div className="foobar-wrapper">
                    <h2>{this.props.foo}</h2>
                    <h3>{this.props.bar}</h3>
                    <h4>{this.props.foobar}</h4>
                </div>
            </React.Fragment>
        );
    }
}
```

MyComponent should output nothing if foo, bar, and foobar are "falsy"

Again thanks for the attention.

**Comment by houdiiny** [comment]
You are right, maybe I have overestimated the need for such a feature.

Even though, I, *a very stubborn being*, will keep thinking of a way to achieve this without compromising all you've mentioned.

Thank you once more for your insights, they are very much apreciated

**Comment by houdiiny** [comment]
That's food for thought, will create tests for your concerns and I'll be back with or without (hopefully with) answers as soon as I can.

**Comment by houdiiny** [comment]
I'm back.

Here's some examples of how the prop (i've renamed it to something clearer) would work.

All of the below examples are some of the possible returns for the render method of MyComponent

```javascript
<div omitIfEmpty={true} /> 
// base case 1 -> outputs null because there are no children

<div omitIfEmpty={true}>
    {foo}
</div> 
// base case 2 -> outputs null iff {foo} is one of (false, null, undefined, or true)
// https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored

<div omitIfEmpty={true}>
    <span omitIfEmpty={true}>{foo}</span>
</div> 
// base case 2 (nested) -> outputs null iff {foo} is one of (false, null, undefined, or true)

<div omitIfEmpty={true}>
    {foo}
    {bar}
</div> 
// base case 3 (many children) -> outputs null iff both {foo} and {bar} is one of 
// (false, null, undefined, or true)

<div omitIfEmpty={true}>
    {<FooBar />}
</div> 
// edge case 1 -> This should behave as base case 1 but with FooBar render value
// if it's too complex or not viable because of performance we can assume custom components
// are seen as content and simply treat them as such.
// this means the above example would never output null


<FooBar omitIfEmpty={true} /> 
// simply passes a named prop for the custom component 
// to implement (sort of like the children prop)
```

Extracting it to it's own custom component gives me a *render* method to implement the *omitIfEmpty* logic so I'd go for something like this:

```javascript
// workaround for headings
let Heading = (props) => {
    if (!props.children) return null; // ignore the bad check for the ignored values
    let Type = props.type;
    return <Type children={props.children} />
};
```
This was initially thought of as a nice-to-have feature for built-in components(BIC) only.
What I seek is to find a generic solution for BIC to clean up some repeated logic of `{ children && <BIC>{children}</BIC> }` which, in my few React projects, seem to be in around 80% of the render methods with actual built-in markup.

I hope I covered the some of the brittleness of the feature, if I forgot anything please do point it out.
Eager to hear your thoughts on it.

**Comment by gaearon** [comment]
In general the main reason I'm wary of the API you're proposing is not just the implementation complexity (although it's likely not easy), but that it creates "spooky action at distance". One of the core promises of React is that in general, only the component that renders a `div` can affect whether it's displayed or not. With this proposal, the entire tree below influences the behavior (which also affects statefulness of any children below).

There is clearly a deeper issue here, which is that React doesn’t allow component to “pierce through” the hierarchy which *is* necessary for some use cases. Like userland layout. This is something we’re keeping in mind. Your proposal is a hyper-specific version of that though, and it’s unlikely we’d go in that direction. However, it might be that our future work on a more generic feature will also allow something like what you’re aiming for too.

**Comment by houdiiny** [comment]
Well there's no denying it's complex.
Guess I'll run with the workarounds until a cleaner solution comes up.

I appreciate the time you took Dan, thanks.
