### ISSUE TITLE
Why are you using prototypes and not ES6 classes for Component src?

### ISSUE THREAD

**Issue by gkatsanos** [facebook/react#13326]
I was browsing out of curiosity the source code for "Component" https://github.com/facebook/react/blob/master/packages/react/src/ReactBaseClasses.js , and I saw you actually use prototypes and not ES6 classes?
Is that accurate or am I missing something?
Why did you make that decision?

**Comment by gaearon** [comment]
Because we want React to work in older browsers 🙂

Using classes and letting Babel compile them doesn’t make sense for us, the output would be worse than if written by hand. In a library this matters.

**Comment by gkatsanos** [comment]
wait a sec :) but you still use ES6 imports instead of CommonJS but I guess in that case Babel compilation is good enough

**Comment by TrySound** [comment]
@gkatsanos Rollup bundling is the best here. Babel is used for another syntax like arrow functions and shorthand properties.

**Comment by gaearon** [comment]
We're not using Babel for import statements.
