### ISSUE TITLE
including css from CDN in react project

### ISSUE THREAD

**Issue by a-m-dev** [facebook/react#13330]
hi there...
i'm trying to use [react slick ](https://www.npmjs.com/package/react-slick) in my project 

but i'm unable to import the css that it provides in its documentation , he says something like ...
```
npm install slick-carousel
@import "~slick-carousel/slick/slick.css";
@import "~slick-carousel/slick/slick-theme.css";
```

i cant do that , i dont know how people get to use that kinda importing 
but 
exactly under that it is been wrote that you can include styles from a cdn through your index.html like below :

```
<link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
```

my question is 
========
is including like that from cdn is good or bad for react project ??????
does it effects react performance ???
does it even has any effect on react side of my project ??? as i just build my css with help of webpack?????

**Comment by gaearon** [comment]
Including them in HTML will work fine.

**Comment by a-m-dev** [comment]
hey Dan , i found this solution for that , and i'm putting it here to remember that i solved it like below and i can always find it here:


(1) just go inside of your `node_modules` folder and find `slick-carousel` folder 
(2) inside of that find `slick.scss` and `slick-theme.scss` from slick folder and open them up
(3) create two seperate files with names of `_slick.scss` and `_slickTheme.scss` inside of your style folders of your project
(4) copy all from `slick.scss` and `slick-theme.scss` and put them in your newly created files ( `_slick.scss` and `_slickTheme.scss` ) 
(5) import them in your `app.scss`file
(6) now if you are using webpack like me , i'm guessing that you getting can't resolve `'./ajax-loader.gif'` error and a cant resolve font error after that 
(7) in fact those files is been used by `slick-carousel` css it self and for that we can just simple go inside your newly created `_slickTheme.scss` and find these lines 
 

```
/* Slider */

.slick-list {
    .slick-loading & {
        background: #fff slick-image-url("ajax-loader.gif") center center no-repeat;
    }
}

/* Icons */
@if $slick-font-family == "slick" {
    @font-face {
        font-family: "slick";
        src: slick-font-url("slick.eot");
        src: slick-font-url("slick.eot?#iefix") format("embedded-opentype"), slick-font-url("slick.woff") format("woff"), slick-font-url("slick.ttf") format("truetype"), slick-font-url("slick.svg#slick") format("svg");
        font-weight: normal;
        font-style: normal;
    }
}
```
(8) comment them out ,

**Comment by a-m-dev** [comment]
also this stackoverflow's question made me to ask this question : https://stackoverflow.com/questions/48779212/react-slick-import-css-from-slick-carousel-fails/50965159?noredirect=1#comment90405147_50965159

in question he says that:
It works if I add the css to index.html from the CDN, **but I'd rather avoid that network call, as I believe it's affecting the rendering of the page on initial load.**
