### ISSUE TITLE
BUG: onPointerUp doesn't fire with tablet pen input

### ISSUE THREAD

**Issue by DanFessler** [facebook/react#13333]
Example component:
```javascript/jsx
<div
   style={{ width: 100, height: 100}}
   onPointerDown={() => console.log("DOWN")}
   onPointerUp={() => console.log("UP")}  // Does not fire with wacom pens!
/>
```

**What is the current behavior?**
as of v16.4.0, onPointerUp event fails to fire using wacom tablets.  (tested on Chrome, mac and windows).  In the past I used react-pointable that wrapped these functions, which also no longer works as of v16.4.0.

**Comment by DanFessler** [comment]
It appears to indeed be a bug in chrome.  Tried your suggestion with vanilla JS and it doesn't fire the pointerup event either.  Works in firefox.

**Comment by philipp-spiess** [comment]
Can you post a link to a JSFiddle or anything? I found that sometimes `touch-action: manipulation` is needed for Chrome to behave properly.

**Comment by DanFessler** [comment]
https://jsfiddle.net/m6n3fr87/

**Comment by philipp-spiess** [comment]
Check out: https://jsfiddle.net/7e9wp03c/

I added `touch-action: none` which makes the `pointerup` event appear as expected on Chrome using mobile emulation. I suggest that Chrome is recognizing a gesture itself and thus firing a `pointercancel` before the pointer is released.

If this does not work, I recommend to register a [pointer capture](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#Pointer_capture) and see if that produces a more reliable result.

Anyway this does not seem to be a bug on React so I think this issue can be closed.
