### ISSUE TITLE
Persistent state by storing in parent

### ISSUE THREAD

**Issue by PascalSenn** [facebook/react#13352]
Hi there ✋ 

We use react-virtualize to render a list.  A sub component of a row carries some state. This state obviously gets reinitialized on every remount. 
Can we just store the state on the parent in object, pass this object down the tree by props and then set this object every time we do a state update? 

```javascript
props : {
     stateCache: {
          childState: {} 
     }
}
```

```javascript

constructor(props) {
      super(props)
      this.state = props.stateCache.childState;
}
...
this.setState({property: 2}, () => this.props.stateCache.childState = this.state)
```

**Comment by gaearon** [comment]
What's the purpose of duplicating it? If you need to keep it in the parent, then keep it in the parent only. Don't try to "sync" state of a child to a parent — that leads to very complex and hard-to-debug code.

Hope this helps!

**Comment by aweary** [comment]
@PascalSenn for future reference, we use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
