### ISSUE TITLE
Might be time to update some of our package READMEs

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#13359]
> An npm package to get you immediate access to React, without also requiring the JSX transformer. This is especially useful for cases where you want to browserify your module using React.

https://github.com/facebook/react/blob/v16.4.2/packages/react/README.md

**Comment by Orozco1993** [comment]
How can I Help?

**Comment by philipp-spiess** [comment]
@Orozco1993 Thanks for wanting to help out! I think as a good first step you can take a look at the repository [README](https://github.com/facebook/react/blob/master/README.md) and see if we can reuse some text there for our [packages](https://github.com/facebook/react/tree/master/packages).

When you [open a PR](https://reactjs.org/docs/how-to-contribute.html), we can definitely iterate over the wording so it does not need to be perfect at the first try.

**Comment by dantesolis** [comment]
@Orozco1993 are you still working on this, or could I take it form you? :)

**Comment by gaearon** [comment]
I tweaked the ones for `react` and `react-dom`.
