### ISSUE TITLE
Bug in lastest version with getting images from https://i.ytimg.com

### ISSUE THREAD

**Issue by ViktoriaShelestenko** [facebook/react#13350]
Hi to all. When my page loaded, i have a lot of errors with getting images from react-dom.
Message like
`https://i.ytimg.com/vi/CCd9kVEUHbc/hqdefault.jpg 404 () react-dom.development.js:2912`

Path to file with error - node_modules/react-dom/cjs/react-dom.development.js:2912
`node.setAttribute(_attributeName, '' + value);`

react@16.4.2

Please fix it, or tell me please what i do wrong.

**Comment by gaearon** [comment]
React doesn't load any images by itself. If you see an error like this, it means that you rendered an `<img>` tag with this source URL, and it couldn't load for some reason. Hope this helps!

If not, a reproducing minimal example is necessary for us to provide guidance.
