### ISSUE TITLE
onChange should be triggered when option changes (even not by human)

### ISSUE THREAD

**Issue by sorawee** [facebook/react#13366]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Consider a `<select>` with options from external data, say, "A" and "B". Users could choose an option, say, "B". Since data are from outside, it's possible that later the option "B" is no longer an option. The `<select>` will automatically adjust its display to a left option which is "A" in this case. Yet, `onChange` is not triggered. This means unless users click on `<select>` and choose the option that is already displayed (which doesn't make sense at all), the internal state of the `<select>` wouldn't be able to change to the correct perceived value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codepen.io/anon/pen/zLevVV

I simulate the external data by having an input text which is a comma-separated choices. Try the following sequences of events:

1. Select option "B" in the `<select>` element.
2. Edit the text box so that its value is changed from `A,B` to `A`.
3. The displayed value is now "A", but the current choice in the internal state is still "B".

**What is the expected behavior?**

`onChange` is triggered, and the internal state is adjusted to "A".

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.4, Chrome/Firefox

**Comment by jquense** [comment]
Browsers don't trigger change events when you programmatically change the value, so the observation you see here is not specific to React. In your pen you should be consolidating the value state to a single source of truth, so the value you are attempting to set is not out of sync with the possible options

**Comment by sorawee** [comment]
I'm afraid I don't really know how to "consolidating the value state to a single source of truth" here

But for anyone that has the same problem, the way I workaround this is to explicitly add the invalid option into the `<select>`, but with `hidden disabled`. This means the invalid option will be displayed, and users will know that they must change it to something else. However, it will not be an option in the dropdown. With this way, the display and the state are always in sync.
