### ISSUE TITLE
Provide a `testInstance.context` property to facilitate context testing

### ISSUE THREAD

**Issue by jsmrcaga** [facebook/react#13382]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
`testInstance` provides a `props` property, but does not provide a `context` property allowing for context tests.

**What is the expected behavior?**
`testInstance.context` should return an object containing the instance's current context

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
At least 16.4.1

**Comment by jsmrcaga** [comment]
For what I have read on the source code, this could be enabled from [`ReactFiber.js`](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiber.js) and [`ReactTestRenderer.js`](https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactTestRenderer.js)

**Comment by gaearon** [comment]
Do you mean legacy context? I don't think we want to add more APIs supporting it given that the new context API fully supersedes it.

It's not clear to me how your suggestion would work with new context API. There's no single particular context. If a component reads some context and uses it, I think you should test *how* that component uses it. You don't need to test whether the context itself "works" — that's something we already test for inside React.

**Comment by jsmrcaga** [comment]
Hey @gaearon thanks for the quick answer!
My use case is that i have built a provider and a wrapper around pre-built components. I would like to test that the provider actually passes the context to the wrapped components, for example:

```js
const component = renderer.create(
	<ThemeProvider theme={someTheme}>
		<Button name="someButton">Some Text!</Button>
	</ThemeProvider>
);

let button = component.root.findByType(Button);
expect(button.context).toHaveProperty('theme');
```

For now my solution has been to transform the `theme` context into a prop inside the wrapper.

**Comment by gaearon** [comment]
It sounds like you're really testing React here. There's no need to do it. We have plenty of tests for context. :-)

If you want to verify that `Button` does something with context, you can do this by testing `Button` output (presumably it uses context somehow).

**Comment by jsmrcaga** [comment]
Hmm I see your point. I was trying to test my implementation of Provider + wrapper, but as a matter of fact it is essentially a React test.
