### ISSUE TITLE
React.Children.map incompatible with the React.Children.only function

### ISSUE THREAD

**Issue by Twady77** [facebook/react#13380]
The return value of React.Children.map is incompatible with the React.Children.only function, and will return with the error message:

Invariant Violation: Invariant Violation: React.Children.only expected to receive a single React element child.

**Comment by gaearon** [comment]
There is another issue like this reported on the first issue page. :-)
Please see https://github.com/facebook/react/issues/13355.

TLDR is: `React.Children.only` is a poorly named method that really means something like `ensureElement()`. It will error if you pass anything other than a React element. If that's not the behavior you want, don't use `React.Children.only`.
