### ISSUE TITLE
Investigate why select._wrapperState.initialValue is necessary

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#13410]
Uncovered during @raunofreiberg's select work (#13389).

`select._wrapperState.initialValue` is only ever assigned, never referenced. Can it be removed?

Example:
https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberSelect.js#L191

It would be great if someone could investigate this, and figure out if it can be removed.

**Comment by nhunzaker** [comment]
Nominating @raunofreiberg for this, but I don't want to create work for him :)

**Comment by jquense** [comment]
I want to say that this is an artifact of older defaultValue handling for selects?

**Comment by nhunzaker** [comment]
Removing it completely appears to have no effect on the test suite.

**Comment by kartiklad** [comment]
@nhunzaker Can I take this one? This is my first time contributing to React

Purely from reading the code, it seems like your assessment of initialValue not being used seems correct. Happy to investigate further

**Comment by nhunzaker** [comment]
Go for it!

**Comment by kartiklad** [comment]
Hey @nhunzaker I raised a PR for the change #13412

**Comment by nhunzaker** [comment]
Fixed by #13412. Thanks @kartiklad!
