### ISSUE TITLE
Small issue: Test does not ensure componentDidMount is not called

### ISSUE THREAD

**Issue by cellog** [facebook/react#13417]
While glancing through tests to get a better handle on update batching and the like, I noticed a possible logic omission in this test:

https://github.com/facebook/react/blob/3b43f3190bbcc5d4cfe77dbc665e03b7b95d35b2/src/renderers/__tests__/ReactUpdates-test.js#L791

Which (in case the file moves) is `'does not call render after a component as been deleted'`

and looks like:

```js
  it('does not call render after a component as been deleted', () => {
    var renderCount = 0;
    var componentB = null;

    class B extends React.Component {
      state = {updates: 0};

      componentDidMount() {
        componentB = this;
      }

      render() {
        renderCount++;
        return <div />;
      }
    }

    class A extends React.Component {
      state = {showB: true};

      render() {
        return this.state.showB ? <B /> : <div />;
      }
    }

    var component = ReactTestUtils.renderIntoDocument(<A />);

    ReactDOM.unstable_batchedUpdates(function() {
      // B will have scheduled an update but the batching should ensure that its
      // update never fires.
      componentB.setState({updates: 1});
      component.setState({showB: false});
    });

    expect(renderCount).toBe(1);
  });
```

If it is truly intended to check whether the component was mounted, should it not have an additional

```js
    expect(componentB).toBe(null)
```
at the end of the test?

Otherwise, the `componentDidMount` seems superfluous since `componentB` is never checked or otherwise used in the test

**Comment by gaearon** [comment]
Nothing `null`s `componentB` so I don't think we'd expect it to be `null`.

The reason we need `componentB` reference is to call `setState` on it.
It's used on this line:

```js
      componentB.setState({updates: 1});
```

**Comment by cellog** [comment]
sorry for the noise

**Comment by gaearon** [comment]
No problem, I appreciate you filing the issue!
