### ISSUE TITLE
Consider providing a default key for dynamic children

### ISSUE THREAD

**Issue by frosas** [facebook/react#1342]
Because many times performance is not an issue, I find myself doing things like this:

``` js
React.DOM.ul(null, items.map(function(item) {
  return React.DOM.li({key: Math.random()}, item.property)
})
```

Would make sense to have something like this by default?

**Comment by suhaotian** [comment]
@spicyj Yeah,I agree

**Comment by noscripter** [comment]
https://github.com/facebook/react/issues/1342#issuecomment-39230939

>  We already have internal keys when we use arrays, but they are the index in the array. When you insert a new element, those keys are wrong.

This point is important to note, because it's a common problem to be encountered when writing list components.
