### ISSUE TITLE
React page returns 404 in iOS WKWebView

### ISSUE THREAD

**Issue by OmPrakash95** [facebook/react#13433]
I have a react app with the following routes:

> xyz.com/
> xyz.com/policy

When I try to access `xyz.com/` from my iOS app's WKWebView It is rendering the proper homepage. but when I try to access `xyz.com/policy` nginx returns a 404 error in WKWebView. All pages seems to work normally in all Mobile/Desktop Browsers.

access.log when accessing `xyz.com/policy` in normal browsers:

`[18/Aug/2018:17:10:06 +0000] "GET /js/main.js HTTP/1.1" 304 0 "https://www.xyz.com/policy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like $`

`[18/Aug/2018:17:10:06 +0000] "GET /js/jquery-1.11.3.min.js HTTP/1.1" 304 0 "https://www.xyz.com/policy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 $`

`[18/Aug/2018:17:10:06 +0000] "GET /js/plugins.js HTTP/1.1" 304 0 "https://www.xyz.com/policy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, li$`

`[18/Aug/2018:17:10:07 +0000] "GET /service-worker.js HTTP/1.1" 200 3164 "https://www.xyz.com/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit$`

accessing the same route in iOS app's WKWebView below is the access.log:
` [18/Aug/2018:17:13:45 +0000] "GET /policy HTTP/1.1" 404 152 "-" "Mozilla/5.0 (iPad; CPU OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)"`

I'd like to know if this is some Issue with the React Router which prevents it from rendering the content although I'm very sure that the problem is not with the content.

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests in React itself.
React doesn't do anything with routing by itself so this is definitely unrelated to React.

If you have a question about React or some other library, please check our community support resources:
https://facebook.github.io/react/community/support.html
