### ISSUE TITLE
renderToString supports HTML minify.

### ISSUE THREAD

**Issue by konojunya** [facebook/react#13432]
I think that you can optionally minify the HTML string returned by `ReactDOM.renterToString`

If we believe it is possible with current React think that method should be placed in the document: https://reactjs.org/docs/react-dom-server.html if possible.

Thanks.

**Comment by gaearon** [comment]
I don't think the output HTML is safe to minify if you plan to later hydrate it on the client. For example, the comment nodes between text like `<div>{textA}{textB}</div>` are important for React to hydrate correctly.

**Comment by konojunya** [comment]
@gaearon

When hydrate is used in the client, we do not check for a match with checksum, so if you minify it is said to be unsafe including the comment node.

I learned a lot. Thank you very much :)

**Comment by gaearon** [comment]
React doesn't do the checksum comparisons since 16. But if React emitted comments on the server, it expects to find them on the client.

**Comment by konojunya** [comment]
@gaearon yeah, the comment earlier is v16. Thank you politely.

**Comment by jacek213** [comment]
would be nice to make it possible somehow, there can be plenty of whitespace in an app of above average size.
