### ISSUE TITLE
A doubt behaviour using the PureComponent

### ISSUE THREAD

**Issue by MuYunyun** [facebook/react#13438]
**What is the current behavior?**

I've met a strange behaviour using PureComponent:

It's normal to unincrease the number when click the add button as follow(shallowEqual return true):

```js
class B extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    };
    this.click = this.click.bind(this);
  }

  click() {
    this.setState({
      count: this.state.count
    });
  }

  render() {
    return (
      <div>
        <button onClick={this.click}>add</button>
        <div>{this.state.count}</div>
      </div>
    );
  }
}
```

but I'm doubt it's normal to increase the number when using like follow: [link](https://codesandbox.io/s/2z9wpl3j8y)

```js
click() {
  const state = Object.assign({}, this.state);

  this.setState({
    count: ++state.count
  });
}
```

In my option, the effect of { count: ++this.state.count } is same as { count: ++state.count }. I don't know why the second way can do it ?  Thanks for replying.

**Comment by gaearon** [comment]
The recommended way is 

```js
this.setState(state => ({
  count: state.count + 1
}))
```

**Comment by yordis** [comment]
@gaearon is there any reason why to use the callback function or is just code style?

**Comment by MuYunyun** [comment]
@yordis Thanks for replying. Maybe I want to know about a little more

```js
const state1 = {
  count: 1
}

const state2 = {
  count: 1
}

state1 !== state2  // true
state1.count === state2.count // true
```

I've known the effect of Object.assign() is to create another Obj, so it's ok `state1 !== state2`, but the value of their count is equal, so `state1.count === state2.count`.

 I think  `++this.state.count` or `++state.count` is only the value like the value of the count as above. Is the problem in `++` operation? Thanks very much.

**Comment by AliasT** [comment]
@MuYunyun, may be your `++this.state.count` have already change the state to new version
```javascript
const t = ++this.state.count
console.log(t === this.state.count) // => true
this.setState({
  count: t
})
```

**Comment by MuYunyun** [comment]
@AliasT It's surprised. 👍 I've understanded, Thanks.
