### ISSUE TITLE
tools for end-to-end testing

### ISSUE THREAD

**Issue by catdad** [facebook/react#13447]
This may be a question moreso than a feature request, but I can't seem to find the answer around the web. It seems most people are working on small apps or just ignoring this as an issue.

I am working on a large react application, and seeing some issues with end-to-end testing. We have a webdriverio/selenium setup which seems to be rather common from what I understand. We use these tools to click some buttons, type some text, etc., and then find the affected DOM elements and do some assertions.

However, and here is where the problem is, React does not synchronously perform all operations on the read DOM. It will use various methods to schedule work, which will be done asynchronously at some later time. I have found that in our tests, a few assertions at random will see that the real DOM is still in the previous state (rather than the new state that results from having clicked the button and whatnot) in every large test run.

I have not seen many posts on the internet even acknowledge this as an issue. The one that I found that does only suggests adding timeouts throughout the tests. However, for obvious reasons, this is slow and non-deterministic.

Is there a suggested way to know that a React application has finished performing all scheduled work? And if not, is there a discussion about this happening somewhere?

**Comment by catdad** [comment]
Sorry, you are probably way more familiar with React than I am, as I have mostly only worked with it and attended talks on how it works internally. However, I was under then impression that React will use things like `requstAnimationFrame` and `requestIdleCallback` in order to schedule work when it actually goes to modify the real DOM. A quick search shows that these methods are used in source code and tests exist to assert these are being used -- though, I apologize, I did not take the time to see how exactly these are being used.

Is this not the case?

**Comment by gaearon** [comment]
React doesn’t currently use those in practice. There are plans to use them but that will be opt-in.

**Comment by alexeyraspopov** [comment]
@catdad, have you tried using [`wait()`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Driver.html#wait) utility? When you have async operations you may want to wait for specific changes before making assertions. Using timeouts may still make tests flaky.

Quick example (using Protractor's API on top of Selenium Webdriver with Promise Manager disabled):

```javascript
// as example, let's assume you need to get a list of names
// rendered after some link or button is clicked

async function openUserList() {
  let trigger = await element('#someButton');
  return trigger.click();
}

async function getUserNameList() {
  // ensure necessary root element is available for subsequent element queries
  await browser.wait(() => isUserListPresent()/*, optional timeout */);
  // continue with doing necessary queries and transforms
  let userItems = await element.all('#userList .list-item');
  let userNames = await Promise.all(userItems.map(item => item.getText());
  return userNames;
}

async function isUserListPresent() {
  let userList = await element('#userList');
  return userList.isPresent();
}

test('should show user list', async () => {
  await openUserList();
  let userNames = await getUserNameList();
  expect(userNames).toEqual(['Liza', 'Ann']);
});
```

**Comment by catdad** [comment]
Sorry, I disappeared for a minute. I got distracted.

I seem to have uncovered that I don't quite get how selenium works. I found out that the app I am working on testing is using synchronous animations (🤨) through some sort of material design library. Things like clicking on buttons or opening menus is resulting in several hundred millisecond synchronous animations (I confirmed in devtools that it is indeed synchronous and it is indeed blocking for that entire time...). However, when I do an `await browser.click('.some-selector')`, and then do another command, that command appears to execute? I can use various kinds of waits for this, of course, but the most curious thing that I found is that I can also use `browser.execute` to execute some javascript -- doing `document.querySelector('.some-selector')` for elements from the animation, and that javascript code will execute and return stuff. I can send that query and see that an animation DOM element is present a good 10 times before the animation is over. I am not sure how selenium is managing to execute javascript within the browser scope while the browser is busy performing a synchronous blocking operation... but that certainly isn't a React problem.

Hopefully once React asynchronous operations become available, there will also be tooling in place to tell when React is done with work, but I am sure you guys have that covered. Thanks for the great work!

**Comment by alexeyraspopov** [comment]
Usually you don't need to wait for the animation to finish. Firing "button click" even you suppose to wait for the resulting change (e.g. new section appeared, some text shows up, some stuff disappears) on the screen based on the button's intent. This is what need `wait`s.

**Comment by threepointone** [comment]
Closing since this seems to be resolved.
