### ISSUE TITLE
how map ? render An Array Of Elements 

### ISSUE THREAD

**Issue by zlv-thisF** [facebook/react#13449]
**What is the current behavior?**
   react16+ support return array components, for example:
   render() {
      return [
          《Li》1《/Li》
          《Li》2《/Li》
          《Li》3《/Li》
      ]
   }
   export default ArrayDemo
   ----------------
   i want to map it with React.Children.map,
  for example:
  import ArrayDemo from 'xxx/xxx';
  ....
  React.Children.map(ArrayDemo,(item, index) => {
      return 《Col span={6}》{item}《/Col》
  })
  ....

  -------------------
  but ArrayDemo has become a single element; React.Children.toArray got [0] only;

**What is the expected behavior?**

  i expected since React can return array;  how can i map it? for sometimes i want to wrap each
 element in array ;

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

   16.4+

---------------------------------------
or am i missing something important?    thx a lot!

**Comment by gaearon** [comment]
Can you provide a complete example please? For example on CodePen or CodeSandbox.

**Comment by zlv-thisF** [comment]
https://codepen.io/zlv-thisf/pen/jvEpPG 
that's what i want to do;  
(sorry, i am not familiar with codePen , the view not render, really really sorry, but code is above);

you can find that each FilterItem will be rendered in Filters Component, but not well styled;

what i want to do is, in Filters Component:

class Filters extends React.Component {
  render() {
    const format = React.children.map(arr, (item, index) => {
        <Col span={8}>{item}</Col>
    )
    //  format is exactly what i want,  for control style, cus each item in Filters was not same, but
    //  format function can style them in an uniq way;
    //  but,  render(onFilter) return a single react element;
    const { onFilter, render, children } = this.props;
    return (
      <div>
        <Row>{format(render(onFilter))}</Row>
        <Row>{children}</Row>
      </div>
    )
  }
}

**Comment by gaearon** [comment]
You can't access what a component renders *to* using `React.Children` utilities. We might support something like this in the future with a different API, but it's not possible today.

**Comment by zlv-thisF** [comment]
really appreciate you taking time on the question,  thanks a lot ! @gaearon .    i like react16+ !!

**Comment by NE-SmallTown** [comment]
@gaearon Any thought you can share with us?

**Comment by thoamsy** [comment]
The `ArrayDemo` is a __Component__, but `React.Children.map` wants to receive a __Element__ as its argument.
