### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by lianglinux5** [facebook/react#13458]
Hello!
<img width="672" alt="image" src="https://user-images.githubusercontent.com/14293060/44457309-7d45bd00-a635-11e8-834e-6b7f1d877e83.png">

**Comment by gaearon** [comment]
It's not supported to contribute to React itself with npm. You need to use Yarn.

**Comment by lianglinux5** [comment]
Thanks
When I run "yarn build",fails "Cannot find module 'react'"
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/14293060/44501191-cd1c9680-a6be-11e8-8154-2354459bb3e4.png">

**Comment by gaearon** [comment]
You need to run Yarn first. And it needs to be at least Yarn 1.3.2+. You're running Yarn 0.19 which is very old.

**Comment by lianglinux5** [comment]
Thanks very much!
Upgrade Yarn,can build
