### ISSUE TITLE
Problem on render on smart tv

### ISSUE THREAD

**Issue by wagnerteixeira** [facebook/react#13466]
I created an app using create-react-app and I installed the dependencies with "yarn install" I started with "yarn start" and tried to open the page on my smart tv, a samsung 42" and nothing is rendered, so I downgraded to version 15.6.2 of the react and react-dom and then again an install and a start and there the page is rendered normally.  The same happens on a LG 43" TV. What can it be?

**Comment by nmain** [comment]
Exactly what web browsers are running on those TVs?  React 16 only supports IE9 or later, or equivalent, and may require polyfills depending on environment:  https://reactjs.org/docs/javascript-environment-requirements.html
