### ISSUE TITLE
Get keys in react-reconciler

### ISSUE THREAD

**Issue by ex3ndr** [facebook/react#13469]
I am struggling to implement reusable views on mobile platforms and to make it i need to get key values (explicitly set and generated) in react-reconciler to match two different view trees somewhere outside react.

Is there a way to achieve this?

Thanks!

**Comment by gaearon** [comment]
Can you describe how you plan to use them in more detail? Some pseudocode examples would help.

**Comment by sebmarkbage** [comment]
You can't get the keys from React elements but you could make up your own keys (call it something else) and pass it as props.

**Comment by ex3ndr** [comment]
I have a "async views" in my react native application they looks just like a normal one:
```
<ASView> 
    <ASText>Hello world!<ASText>
<ASView>
```

Then i will put them to a list on mobile app. One of the nice features on mobile is that views can be reused. For such reason i need an ability to match views from different rows and update them carefully.

To make it work i need keys that was specified in source layout. Generation keys in reconciler (in `createInstance` function) doesn't help since i need a stable way to generate them.

Thanks.
