### ISSUE TITLE
UIWebView access React

### ISSUE THREAD

**Issue by weiFans** [facebook/react#13485]
**In a production environment, the browser can access, but UIWebView cannot access React**

**My react route is as follows**

`<Route path="/policies/:pathname" component={ ArticlePage } />`

**Deployed in nodejs express**

`var app = express();`
`app.use(enforce.HTTPS());`

`app.use(logger('dev'));`
`app.use(bodyParser.json());`
`app.use(bodyParser.urlencoded({ extended: false }));`
`app.use(cookieParser());`

`app.use(express.static(path.join(__dirname, 'app/build')));    //`
`app.use(router.all('/service', sleepwindAPI.action));`

`app.get('*', (req, res) => {`
`    res.sendFile(path.join(__dirname, 'app/build/index.html'));`
`});`

**issue**

Accessing in the browser can display normally
1、http://domain.com/login
2、http://domain.com/policies/privacy

In UIWebView（IOS）
1、http://domain.com/login
2、http://domain.com/policies/privacy

1 can access
2 can't access ( Passed the test, the request did not enter app.js )

**I don't know if it's an issue with express, or a problem with react. I don't know if I am asking questions here. I hope that my friends can answer them. Thank you very much.**

**Comment by gaearon** [comment]
Sorry, this doesn't seem related to React itself.

We use the issue tracker for bugs in React, but you're welcome to consult our support resources:
https://reactjs.org/community/support.html
