### ISSUE TITLE
React code base coverage results appear incorrect

### ISSUE THREAD

**Issue by trivikr** [facebook/react#13496]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In order to contribute to React, I was going through the coverage results to find code which needs additional testing. While doing that, I noticed that the coverage results appear incorrect

For example file `packages/create-subscription/src/createSubscription.js`, notice that coveralls says branches are not covered on [L16](https://coveralls.io/builds/18690124/source?filename=packages/create-subscription/src/createSubscription.js#L16) which is actually a function call.
![coveralls](https://user-images.githubusercontent.com/16024985/44702510-a1940600-aa48-11e8-89b7-3585693bb658.png)

When I ran jest in my workspace with `--coverage`, it gave if/else path are missing on the same line 16 as shown in the screenshot:
![coverage](https://user-images.githubusercontent.com/16024985/44702557-e3bd4780-aa48-11e8-8923-18b619b5dd93.png)

This appears to be a bug.

**Comment by trivikr** [comment]
Hi, any update on this issue?

**Comment by aweary** [comment]
@trivikr feel free to investigate this if you'd like. This isn't currently a priority for us, so it's unlikely that anyone else will have time to look into this in the near future.

**Comment by trivikr** [comment]
Closing as coverage badge was removed from README in #15216
