### ISSUE TITLE
Previous render not cleared on state change

### ISSUE THREAD

**Issue by gregpaton08** [facebook/react#13501]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When a state change occurs, the previously rendered page is not fully cleared, leaving artifacts of the previous render.
![screen shot 2018-08-28 at 10 27 52 am](https://user-images.githubusercontent.com/1425055/44729767-84455300-aaad-11e8-9bd1-6f5020ee4993.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/w2q1n3wm68

**What is the expected behavior?**
The previous render should be fully cleared.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.4.2
Safari Version 11.1.2 (13605.3.8)
macOS High Sierra 10.13.6 (17G65)

I have not checked if this works in previous versions of React. However, this issue is specific to Safari. No issues in Chrome or Firefox.

**Comment by hamlim** [comment]
This seems more like a browser painting issue than a React one. Can you try and re-create the demo without using React to see if its unrelated?

**Comment by gregpaton08** [comment]
You're right, unrelated to React.
https://codesandbox.io/s/2vzx3p03oy
