### ISSUE TITLE
Node/UMD bundles are broken on master

### ISSUE THREAD

**Issue by gaearon** [facebook/react#13512]
See https://github.com/facebook/react/pull/13509#pullrequestreview-150683126.
We'll need to remember to fix it one way or the other before cutting a release.

**Comment by nhunzaker** [comment]
Would this possibly create the following error on the test fixtures?

I don't know if this is related to https://github.com/facebook/react/issues/13512, but I'm experiencing the following error in the React DOM Test Fixtures:

<img width="1280" alt="screen shot 2018-08-29 at 4 25 22 pm" src="https://user-images.githubusercontent.com/590904/44820976-25183900-aba8-11e8-95d8-ca17d3699949.png">

**Comment by nhunzaker** [comment]
Reverting https://github.com/facebook/react/commit/6e4f7c788603dac7fccd227a4852c110b072fe16 definitely fixed it. I'll just roll back to before that commit to triage some DOM stuff.

**Comment by bvaughn** [comment]
Should b e fixed by #13509

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/13509 should fix this so you can try with it on top.

**Comment by bvaughn** [comment]
This should now be fixed in master. Try rebasing your branch @nhunzaker

**Comment by nhunzaker** [comment]
Yep, that did it. Thanks!
