### ISSUE TITLE
Add <progress> to DOM fixtures

### ISSUE THREAD

**Issue by gaearon** [facebook/react#13518]
Maybe I missed it but I don't see this case in DOM fixtures:

https://github.com/facebook/react/pull/7359#discussion_r77518170

Seems important because it's easy to accidentally gloss over it if we stop syncing attributes and have to edit a bunch of jsdom tests.

**Comment by HeroProtagonist** [comment]
Hello @gaearon! I would be interested in working on this. Thanks 👍

**Comment by xargr** [comment]
Maybe it will really cool feature
