### ISSUE TITLE
App doesn't render on mobile

### ISSUE THREAD

**Issue by charbelsako** [facebook/react#13524]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
App renders nothing on mobile browsers

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

[App link](https://react-client-panel-1e6bd.firebaseapp.com)
This will render on desktop but not on mobile

**What is the expected behavior?**
App should render normally

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Mobile chrone browser. Samsung internet.

**Comment by gaearon** [comment]
Remove Redux DevTools extension and you'll see this error:

<img width="580" alt="screen shot 2018-08-31 at 6 15 02 pm" src="https://user-images.githubusercontent.com/810438/44926587-d1455580-ad49-11e8-870c-3a2b14f06fae.png">

You probably want to fix this part:

<img width="393" alt="screen shot 2018-08-31 at 6 15 24 pm" src="https://user-images.githubusercontent.com/810438/44926598-ddc9ae00-ad49-11e8-9998-4c13e10d99ea.png">

and make it like

```js
  compose(
    reactReduxFirebase(firebase),
    window.__REDUX_DEVTOOLS_EXTENSION__
      ? window.__REDUX_DEVTOOLS_EXTENSION__()
      : (f => f),
  ),
```

`compose` doesn't support `undefined` arguments.

**Comment by charbelsako** [comment]
Thank you for your help. I will try this as fast as possible and get back to you

**Comment by charbelsako** [comment]
Still doesn't work

**Comment by charbelsako** [comment]
I could just remove redux-devtools entirely
