### ISSUE TITLE
Access React component underlying DOM tree

### ISSUE THREAD

**Issue by Naxus28** [facebook/react#13520]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Form component has "form field" children (Input(), Checkbox(), etc) that are validated against some custom rules when form is submitted. Validation works fine.

**What is the expected behavior?**
 If the form is invalid, I would like to scroll the page to the first invalid element after the form is submitted but unfortunately components do not expose the underlying DOM three (except via the Fiber object) and I cannot get the "ref" of any component, which makes scrolling not possible since I don't have the DOM reference.

I am trying to avoid ref forwarding on "form field" components because I would like the Form to handle all validation related code (for encapsulation purposes and in case I want to publish this as a library, for instance).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: "^16.4.0"

Is there any way to achieve this?

**Comment by gaearon** [comment]
What prevents you from getting ref to the field itself and then doing a DOM traversal?

**Comment by Naxus28** [comment]
Hi @gaearon. Thanks for the prompt answer. 
I am not sure if you meant getting the ref to the field in the component implementation itself or in the Form.

Do you mean this?
```javascript
class Input extends React.Component {
    inputRef = React.createRef()
    
     render = () => (
        <div className="input" ref={this.inputRef}>
           ....
        </div>
    );
}
```
If that is the case, I am trying to avoid delegating validation related code to the field components and have the Form do that work.

SInce the Form recurses all children to check field values I am getting the ref when I clone invalid field elements to add a couple of validation props (implemented this after I posted the question):

```javascript
updateField = (field, validationRule) => 
      React.cloneElement(field, {
          invalid: true,
          validationMessage: validationRule.message(field.props),
          ref: node => node &&  this.invalidNodes.push(ReactDOM.findDOMNode(node))
      });
```

I am not sure this is the most efficient way to achieve what I need but it works.



I am getting the reference when I clone the field

**Comment by gaearon** [comment]
>If that is the case, I am trying to avoid implementing validation related code on field components and trying to delegate anything that involves validation to the Form.

I am proposing adding a ref in the *form itself*.

```js
<form ref={this.formRef}>
```

then feel free to do `this.formRef.current.querySelector('input[data-invalid]').scrollIntoView()` or similar.

I don't think you need to traverse the React tree for this, and it seems like the simplest solution.

**Comment by Naxus28** [comment]
I see what you mean. I will look into that.
Thanks!
