### ISSUE TITLE
Running CPU async rendering demo fail

### ISSUE THREAD

**Issue by YaoKaiLun** [facebook/react#13522]
I finished all steps successfully according to the README.md in "react/fixtures/unstable-async/time-slicing", but when i run "yarn start" in , it reported an error like below:

```
react/packages/interaction-tracking/src/InteractionTracking.js
Module parse failed: Unexpected token (12:7)
You may need an appropriate loader to handle this file type.
| import {enableInteractionTracking} from 'shared/ReactFeatureFlags';
|
| export type Interaction = {|
|   __count: number,
|   id: number,
```

My enviroment:
- npm:    v5.6.0
- node:   v8.9.4

Do i forget some dependences ? Could you give me some tips ? 
Thanks a lot.

**Comment by gaearon** [comment]
Sorry, master is broken at the moment. Roll back a few days or wait for https://github.com/facebook/react/pull/13509 to land please.
