### ISSUE TITLE
Use async/await in getDerivedStateFromProps

### ISSUE THREAD

**Issue by zach-luman** [facebook/react#13541]
Hi
I'm in need of aysnc/await in getDerivedStateFromProps but it's not working as expected.

```
static getDerivedStateFromProps(props, state) {
	const response = [];
	console.log('break 1');
	[1, 2].map(async path => {
		console.log('break 2');
		const data = await FileGetData.get(path);
		response.push(data);
	});
	console.log('break 3');
	return { fileData: response };
}
```

Expected
```
break 1
break 2
break 2
break 3
```

Results:
```
break1
break3
break2
break2
```

Can't we use async/await in getDerivedStateFromProps?

Thanks,

**Comment by gaearon** [comment]
Don't use `getDerivedStateFromProps` for data fetching. It's not meant for this.

You want to put this logic into `componentDidUpdate`.

**Comment by ericmarcos** [comment]
@gaearon gotcha, thank you.

**Comment by NE-SmallTown** [comment]
@gaearon So the SSR suspense won't be released with the client Suspense?

**Comment by gaearon** [comment]
Client implementation is more or less ready. The cache provider still needs work but the core implementation is already in production at FB.

We're just starting work on the SSR part. So it might come later.

**Comment by NE-SmallTown** [comment]
Oh, gotcha, I will notice the issues/prs, hope I could do any helps :)

**Comment by TomaIvanovTomov** [comment]
> Don't use `getDerivedStateFromProps` for data fetching. It's not meant for this.
> 
> You want to put this logic into `componentDidUpdate`.

Yes, but if I update the state in the `componentDidUpdate` infinite loop occurs. What is the alternative of that ?

**Comment by g-lsh** [comment]
> > Don't use `getDerivedStateFromProps` for data fetching. It's not meant for this.
> > You want to put this logic into `componentDidUpdate`.
> 
> Yes, but if I update the state in the `componentDidUpdate` infinite loop occurs. What is the alternative of that ?

Are you referring to the problem that is answered in the doc https://reactjs.org/docs/react-component.html#componentdidupdate : 

`You may call setState() immediately in componentDidUpdate() but note that it must be wrapped in a condition like in the example above, or you’ll cause an infinite loop. It would also cause an extra re-rendering which, while not visible to the user, can affect the component performance.`

In which case, there is your answer.
