### ISSUE TITLE
When old and new Context are used simultaneously unexpected render can occur on Component 

### ISSUE THREAD

**Issue by istarkov** [facebook/react#13548]
**Bug**

**What is the current behavior?**

When old and new Context are used simultaneously unexpected render can occur on Component 

**Demo**

https://codesandbox.io/s/rw12v4jm7n

Click Ok button, see log `I must not be called on button click `

**What is the expected behavior?**

When Ok button is clicked `Blabla` component must not be called, as it's parent is Pure component not called. So there is no visible reason in such call.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.4.2

**Source**

<details>
<summary>Expand to see source</summary>

```javascript
import * as React from "react";
import ReactDOM from "react-dom";
import PropTypes from "prop-types";

const { Provider, Consumer } = React.createContext({});

class OldContext extends React.Component {
  static childContextTypes = {
    a: PropTypes.number
  };

  getChildContext() {
    return {
      a: 1
    };
  }
  render() {
    return React.Children.only(this.props.children);
  }
}

class StateProvider extends React.Component {
  state = {
    value: 0
  };

  onChange = value => {
    this.setState({ value });
  };

  render() {
    const {
      props: { children },
      state: { value },
      onChange
    } = this;

    return <Provider value={{ value, onChange }}>{children}</Provider>;
  }
}

const Blabla = () => {
  console.log("I must not be called on button click");
  return (
    <Consumer>
      {({ value, onChange }) => (
        <div>
          <div>{value}</div>
          <button onClick={() => onChange(value + 1)}>ok</button>
        </div>
      )}
    </Consumer>
  );
};

class Pure extends React.PureComponent {
  render() {
    console.log("Pure render");
    return <Blabla />;
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(
  <StateProvider>
    <Consumer>
      {v => (
        <OldContext theme={{ value: v.value }}>
          <Pure />
        </OldContext>
      )}
    </Consumer>
  </StateProvider>,
  rootElement
);
```
</details>

**Comment by gaearon** [comment]
This sounds a lot like 
https://github.com/facebook/react/issues/11508. I think it’s the same thing.

I have a failing test in https://github.com/facebook/react/pull/13409 and an outline of how the fix could look. But I likely won’t dive into this. Legacy context support creates overhead, and it’s best if you spend the effort on migrating away from it (in your code and the libraries you use).

**Comment by gaearon** [comment]
That said feel free to try fixing it.
