### ISSUE TITLE
React Fire Feature Flag

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#13554]
There needs to be a feature flag for React 🔥. I thought I'd make an issue to track what that entails. I need some help to make this list, but roughly going off of React Fiber:

- [ ] Add feature flag to [ReactFeatureFlags](https://github.com/facebook/react/blob/master/packages/shared/ReactFeatureFlags.js)
- [ ] Execute the test suite with React Fire flagged (this probably needs to be a config setting in Jest, but I'm not sure where yet)
- [ ] It might be nice to build react-dom with fire enabled for testing in the [DOM Test Fixtures](https://github.com/facebook/react/blob/master/fixtures/dom)

**Comment by gaearon** [comment]
We'll definitely need a flag for Fire but we might also have separate feature flags for smaller changes within the current system (which we'll need to assess how much effort it is to migrate for real code).
