### ISSUE TITLE
Is it possible to avoid calling jest.resetModules() so much?

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#13555]
There are a few test suites that call `jest.resetModules()` on every test:

- [ReactDOMInput-test](https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactDOMInput-test.js#L27)
- [ReactDOMServerIntegrationForms](https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactDOMServerIntegrationForms-test.js#L20)
- [ReactDOMEventListener-test](https://github.com/facebook/react/blob/3661616c282d50d3f90cfd1fb9f8ac1bf43eaab8/packages/react-dom/src/__tests__/ReactDOMEventListener-test.js#L17)

There's probably more, these are just the test suites on my mind.

I've observed that calling `jest.resetModules` consumes a significant amount of test time, and almost always is used to reset the warning cache. 

React holds a state to determine if a warning should fire again. Instead: what if React warnings were keyed off of a tracker that could quickly be reset? 

For example, in the [ReactDOMUnknownPropertyHook](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js#L27), where an object tracks properties that have already raised warnings, this could look like:

```javascript
keyedWarning(`dom-bad-attribute-${attributeName}`, '... message')
```

The state for whether the warning had been triggered could live in another package: `react-warnings`. It could easily be reset when testing:

```javascript
import ReactWarnings from 'react-warnings'

beforeEach(() => {
  ReactWarnings.clear()
})
```

I wonder if this is possible without breaking the convention of only testing the public interface, but this has been on my mind a lot when working on test suites that reset the module registry frequently.

**Comment by gaearon** [comment]
`resetModules` can be helpful to isolate bugs caused by accidental statefulness. But I agree it's overkill to be a default. Your approach makes sense to me.
