### ISSUE TITLE
fbjs@0.8.16 dependency includes ua-parser-js@0.7.17 which has a ReDoS vulnerability

### ISSUE THREAD

**Issue by bobsilverberg** [facebook/react#13557]
We end up with ua-parser-js@0.7.17 installed when we depend on react 16.4.2, and ua-parser-js@0.7.17 has a [ReDos vulnerability](https://snyk.io/test/npm/ua-parser-js/0.7.17), which is fixed in ua-parser-js@0.7.18. 

This could be addressed by requiring fbjs@0.8.17 instead of fbjs@0.8.16. Do you have plans to address this?

**Comment by gaearon** [comment]
**There's no real vulnerability here; React doesn't use `ua-parser-js`.** It happens to be a transitive dependency because some unrelated modules inside `fbjs` used it, but it's literally unused by React code.

The next patch version won't be using `fbjs` at all so this will be solved by itself.
