### ISSUE TITLE
/cjs/react-dom-server.browser.development.js has `require` calls 

### ISSUE THREAD

**Issue by mohsen1** [facebook/react#13558]
**bug**

Including a script with source pointing to `https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.4.2/cjs/react-dom-server.browser.development.js` will result in an error complaining about `require` not being a function 

According to React documents [`renderToString `](https://reactjs.org/docs/react-dom-server.html#overview) should work in a browser. 

>  The following methods can be used in both the server and browser environments:
> renderToString()
> renderToStaticMarkup()

**React version**
16.4.2

**Comment by jquense** [comment]
the `cjs` files are `CommonJS` modules, they are ment for use in a bundler like webpack or in Node. You want the UMD builds located at: https://unpkg.com/react-dom@16.4.2/umd/react-dom-server.browser.development.js
