### ISSUE TITLE
Document fragments cannot respond to events.

### ISSUE THREAD

**Issue by infinnie** [facebook/react#13563]
**Do you want to request a *feature* or report a *bug*?**
bug.

**What is the current behavior?**

Due to https://github.com/facebook/react/blob/ff93996028acb55b4f76aa11e29eef210a213e20/packages/react-dom/src/client/ReactDOMComponent.js#L225-L233 event listeners are added to the `DocumentFragment`, which we cannot access or modify.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```jsx
import React from "react";
import ReactDOM from "react-dom";

import "./styles.css";

function doSomething() {
  alert("Something happens!");
}

function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2 onClick={doSomething}>Click me and nothing would happen.</h2>
    </div>
  );
}

const rootElement = document.getElementById("root");
var frag = document.createDocumentFragment();
ReactDOM.render(<App />, frag);
rootElement.appendChild(frag);
```

https://codesandbox.io/s/71znk844nj

**What is the expected behavior?**

We could manually call `manageEvents(element)` in some other element or the document, so that our components could still respond to the events.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v16.4.2.

**Comment by gaearon** [comment]
Did this ever work?

**Comment by infinnie** [comment]
Probably not.
