### ISSUE TITLE
Remove Factory Components

### ISSUE THREAD

**Issue by gaearon** [facebook/react#13560]
We support a very unusual kind of components that look like functional components but return an *instance*.

```js
function Hello(props) {
  return {
    componentDidMount() {
      alert('wow')
    }
    render() {
      return <div>Hi, {this.props.name}</div>
    }
  };
}
```

Note these are *not* functional components. They're pretty exotic and don't offer any practical benefits over classes. At the time they were added (I think 0.14?) it was because we thought other type systems might want to compile to a format like this instead of ES classes-like output. But that didn't happen.

There's some complexity associated with continuing to support this. Since this is more confusing than useful, I think we should deprecate them in 16.x and remove in 17.x.

**Comment by NE-SmallTown** [comment]
Do you have any work-in-progress pr locally? Maybe I can take this this weekend if don't mind :)

**Comment by gaearon** [comment]
We'd need to add a deprecation warning first. Will take a PR for it!

**Comment by NE-SmallTown** [comment]
Ok, fine, next time :)

**Comment by markerikson** [comment]
I've seen these mentioned once or twice, but that's it.  Are these even actually being used anywhere in the real world?

**Comment by gaearon** [comment]
Relay used it. I guess that means people stuck on Relay Classic do.

**Comment by prichodko** [comment]
Last answer sounded unclear, so I would love to take this over. :)

I suppose warning could be placed somewhere here - https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberBeginWork.js#L715?

**Comment by lustoykov** [comment]
Curious: Maybe some warning is needed for SSR too, in case a different renderer is utilized?

**Comment by GuauDev** [comment]
Close this

**Comment by rickhanlonii** [comment]
Factory components are removed in React 19.
