### ISSUE TITLE
External Javascript is not working in react.js

### ISSUE THREAD

**Issue by SHAPPY0** [facebook/react#13578]
Hi,
I am creating a react app using create-react-app. I have some external javascript libraries for template design in main index.html

```
<script src="%PUBLIC_URL%/js/jquery-2.2.4.min.js"></script>
 <script src="%PUBLIC_URL%/js/common_scripts.js"></script>
 <script src="%PUBLIC_URL%/js/main.js"></script>
 <script src="%PUBLIC_URL%/js/owl.carousel.js"></script>
```
These JS files are working on first page when the application gets started. But these libraries are not working when redirect to other page from first page. From what I understand, these files are rendering but their functions, variables, and methods are not accessible when the route is changed. I am using react-router-dom v4 for routing .

I googled it and found a solution- To render the JS libraries by ComponentDidMount() method

```
ComponentDidMount(){
    loadjs('./js/main.js', function(){
    loadjs('./js/common_scripts.js)
    });
  }
```

But even this solution is not working. Please help to solve this issue.

Thanks

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests in React itself.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by edian-reyes** [comment]
Please, I am having the same problem.

**Comment by mascus007** [comment]
this solution worked for me
var loadScript = function(src) {
            var tag = document.createElement('script');
            tag.async = false;
            tag.src = src;
            document.getElementsByTagName('body')[0].appendChild(tag);
          }
        
          loadScript('./js/main.js')
          loadScript('./js/common_scripts.js')

**Comment by mascus007** [comment]
> Please, I am having the same problem.

this solution worked for me
var loadScript = function(src) {
var tag = document.createElement('script');
tag.async = false;
tag.src = src;
document.getElementsByTagName('body')[0].appendChild(tag);
}

      loadScript('./js/main.js')
      loadScript('./js/common_scripts.js')

**Comment by Poojan-20** [comment]
> > Please, I am having the same problem.
> 
> this solution worked for me var loadScript = function(src) { var tag = document.createElement('script'); tag.async = false; tag.src = src; document.getElementsByTagName('body')[0].appendChild(tag); }
> 
> ```
>   loadScript('./js/main.js')
>   loadScript('./js/common_scripts.js')
> ```

can you mention in which file we have to add this part of code

**Comment by shizuo-x** [comment]
> > Please, I am having the same problem.
> 
> this solution worked for me var loadScript = function(src) { var tag = document.createElement('script'); tag.async = false; tag.src = src; document.getElementsByTagName('body')[0].appendChild(tag); }
> 
> ```
>   loadScript('./js/main.js')
>   loadScript('./js/common_scripts.js')
> ```

bro thanks you saved me

**Comment by gaearon** [comment]
I'll lock this thread because this discussion is not relevant to the React repository. (It's about Create React App, which has a different repo.) This discussion is also a bit confused, and the solutions being discussed are just working around the actual issue — likely in an inefficient way. What the actual issue is unclear because there was no reproducing project.
