### ISSUE TITLE
CSS property values that are strings shouldn't have 'px' appended

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#1357]
It's weird that `style={{margin: '42'}}` gets turned into `margin: 42px;`. I think we should only add `px` if the value is an actual number.

**Comment by zpao** [comment]
Note: this isn't actually fixed, just have a warning in place.

**Comment by jimfb** [comment]
Yep, was autoclosed by the PR.

**Comment by viniciusdacal** [comment]
should we add a version in the warning message to this behavior be removed?

**Comment by SEAPUNK** [comment]
So just to clarify, is passing a number value as string type the only thing that will no longer have `px` appended to it? Will passing a plain number a la `<div style={{width: 40}} />` still be supported, or is there also an intent to remove that as well?

**Comment by viniciusdacal** [comment]
@SEAPUNK As I understood, only string type. The example you gave, will still be supported.

**Comment by aweary** [comment]
@gaearon we still have this warning in place, should we consider acting on for 16 or wait until 17?

**Comment by sophiebits** [comment]
@aweary Too late for breaking changes for 16, let's look at doing it in 17. Can probably land soon after the release behind a flag.

**Comment by gaearon** [comment]
Hmm. I neither see a warning, nor do I see it apply the style.
I think this was fixed in 16.

https://jsfiddle.net/r44uryb1/
