### ISSUE TITLE
[bug][16.5] broke React Native for Web

### ISSUE THREAD

**Issue by necolas** [facebook/react#13589]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

React Native for Web was broken by 16.5 as describe [here](https://github.com/necolas/react-native-web/issues/1096) due to this change https://github.com/facebook/react/pull/13539

**What is the expected behavior?**

Release a version of React that exports the EventPluginHub.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Worked in 16.4

**Comment by aweary** [comment]
On the topic, `ReactDOMUnstableNativeDependencies` exports `injectComponentTree` specifically for React Native for Web

https://github.com/facebook/react/blob/12f3a5475fbd07d4f0806c5adfbb2b66c264a643/packages/react-dom/src/unstable-native-dependencies/ReactDOMUnstableNativeDependencies.js#L13-L20

But it [doesn't appear to be used at all](https://github.com/necolas/react-native-web/search?q=injectComponentTree&unscoped_q=injectComponentTree). Does this still need to be exposed?

**Comment by necolas** [comment]
You're right, that other API is not being used and I don't think it ever was. (I'm not sure what that API is for, i.e., whether it *should* be used for something)

**Comment by Tvrqvoise** [comment]
`ReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.EventPluginHub` [is still undefined](https://github.com/facebook/react/blob/7d1169b2d7ad8d2345c28a2063bc101a4cc2d570/packages/react-dom/src/client/ReactDOM.js#L741) in the latest release.  Should this ticket be reopened?
