### ISSUE TITLE
Bootstrap4's toggle button group not calling onChange event in react

### ISSUE THREAD

**Issue by hussaintamboli** [facebook/react#13585]
I am trying to make use of bootstrap4's toggle button group to select an option. But the `onChange` event is not getting called.

**Working sample-1:**
I ran a simple sample on Codepen with same dependencies and it works - https://codepen.io/hussaintamboli/pen/PdoVvG

**Non working sample-2 that reproduces the issue:**
But when I create an example using webpack4+bootstrap4+reactjs (and same other dependencies), it doesn't work. https://github.com/hussaintamboli/react-bootstrap-toggle-button-example

I didn't get much help on my stackoverflow post. I am just not able to figure out what's causing this and why there is a different behaviour.

- operating system: MacOS
- node.js version: 9.3.0

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
