### ISSUE TITLE
My ReactApp makes Chrome consume ~300% CPU

### ISSUE THREAD

**Issue by omarojo** [facebook/react#13584]
I dont know why my reap app hosted at: 

https://g8livereact.herokuapp.com

is making my Chrome consume cPU from 120% to 300%. This happens specially after signing in with Facebook account.

1- To use it first login with the following account
user: github@myapp.com
password: github
2- Login with any Facebook account, you will see the cPU starting to raise up to maybe ~100%
3- The app requires to have a FAcebook Page and initiate a Live Streaming event to that FB Page in order to monitor it with the app. (you can use your phone for that and make the stream private). Once your Live stream is LIVE, press the START button... once you press START, cpu goes to 300%. and stays there. 

the START button initiates a connection to a SERVER-SENT-EVENT. but that's all. 

The app was created using create-react-app command, and uploaded for production using *npm run build"

Firefox on the other hand, stays within 60% cpu. but Chrome.. turns on my fans and my laptop gets hot.

Any idea what could I be doing wrong ?

**Comment by xargr** [comment]
In the past, I had the same problem not with react  but with JavaScript in general. My bad was one infinitive loop. Check your code inside [profiler](https://developers.google.com/web/updates/2016/12/devtools-javascript-cpu-profile-migration)

**Comment by gaearon** [comment]
Unlikely to be related to React. Try profiling.

**Comment by aweary** [comment]
In the future if you have a usage or support question, please check our community resources:
https://facebook.github.io/react/community/support.html
