### ISSUE TITLE
componentDidCatch Support for SSR (Server Side Rendering)

### ISSUE THREAD

**Issue by adamhenson** [facebook/react#13592]
**Do you want to request a *feature* or report a *bug*?** Feature

[The docs](https://reactjs.org/docs/error-boundaries.html) outline that `componentDidCatch` is not supported in server-side rendering. As React "universal" implementations have become increasingly common from small projects to large corporate websites - this feature seems especially important.

**Comment by aweary** [comment]
As the docs outline, this is a known and intentional limitation. See https://github.com/facebook/react/issues/10442 for some more context.

**Comment by adamhenson** [comment]
Thanks. I understand the limitation... but I’m failing to understand why it’s intentional.
