### ISSUE TITLE
The use of "blacklist" is offensive!

### ISSUE THREAD

**Issue by ZhongCitizen** [facebook/react#13604]
We should change it to blocklist. Let's do it! For a bright future!

Please read: https://twitter.com/andrestaltz/status/1030200563802230786

Software development still has a lot of terminology with a racist or patriarchal background. Let's change that.

- Blacklist ➡ Denylist
- Whitelist ➡ Allowlist
- Killer app ➡ Beloved app
- Master/slave ➡ primary/replica

Related code:
https://github.com/facebook/react/blob/fb88fd9d8c9f72b8e2e7e1ae89652d2a6a707562/scripts/rollup/build.js#L253

https://github.com/facebook/react/blob/c1ba7b8cfd6e194f5cf6b0066c708ae48fd2ad67/scripts/rollup/forks.js#L177

https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/client/ReactDOMComponent.js#L305

**Comment by gaearon** [comment]
Sure, sounds good. I changed to a more descriptive wording in 8a8d973d3cc5623676a84f87af66ef9259c3937c.

**Comment by jquense** [comment]
While the etymology of the words isn't steeped in racial undertones or history like other problematic tech word choices, there is no harm in changing them to synonyms that as just as understandable and avoid the question entirely
