### ISSUE TITLE
[React 16.5] - NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by dharric** [facebook/react#13617]
I am having a bug using wijmo 5.20182.500 with react. It appears that react is attempting to redraw a control when it has not changed. I have a TreeView control that when selected changes a state property and reveals some other controls on screen. The logic to render both the TreeView and the other content exists together in a single render call. It appears that even though the TreeView has not changed react is re-rendering it, because when I click on a TreeView checkbox the whole control blinks and resets all the checkboxes (which is the default state). I found some related posts, which all indicated wrapping the control in a div, but that has not worked for me. I've included a screenshot but basically what happens is that when checkedItemsChanged is called it updates state, which of course triggers render. However the TreeView control should not re-render but it does every time for some reason and I think that's at least part of reason for the error I included below (chrome browser). 

```js
checkedItemsChanged = (s, e) => {
        const self = this;
        const currentItem = this.reportsTreeView.selectedItem;

        if (currentItem.report) {
            if (currentItem.report === 'MarketingMaterials') {
                const selectedReport = "MarketingMaterial";
                self.setState({ selectedReport });
            } else if (currentItem.report === 'DataPak') {
                const selectedReport = "DataPak";
                self.setState({ selectedReport });
            }
        }
    }

render() {
        if (!this.props.user.id)
            return null;

        const reportsTreeViewItems = this.securetizeScreen();

        let paramView = this.getParamView();

        return (
            <main className="container">
                <div className="row PageTitle">
                    <b>Select Report:</b>
                </div>

                <div className="row pm-form-container">
                    <div className="col-md-3">
                        <label className="dropdown-label label-inline pm-label pm-label-top"></label>
                        <div className="dropdown dropdown-left pm-treeview-container">
                            <TreeView
                                initialized={this.reportsTreeViewInitialized}
                                itemsSource={reportsTreeViewItems}
                                displayMemberPath={'header'}
                                childItemsPath={'items'}
                                showCheckboxes={Boolean(true)}
                                formatItem={this.formatItem}
                                checkedItemsChanged={this.checkedItemsChanged}
                                isCheckedChanged={this.itemChecked}
                            />
                        </div>
                    </div>

                    {paramView}

                </div>
            </main>
        );
    }
```

![image](https://user-images.githubusercontent.com/1474935/45365174-ef148500-b5a9-11e8-8d88-70992c9af0e1.png)

**Comment by gaearon** [comment]
When you see an error like this it usually means that something else has touched the DOM, and so when React attempts to modify it, the DOM doesn't exist anymore.

You might want to use "DOM breakpoints" in Chrome debugger to see who's removing the DOM element that React tries to remove later. Might be a browser extension or a different library.

Your description that re-rendering causes input values to be lost is also suspicious. This is not normal in React, which points to some other problem in your code or the libraries you're using.

It's very hard to say anything else without a reproducing example.

**Comment by dharric** [comment]
Yes you are correct. I have multiple combobox controls being added/removed using state, but those controls are being created by a library called wijmo. I was able to fix the issue by wrapping each control with a div tag that has a unique key. Somehow this small change was enough to let react distinguish each instance of the combobox control. Could you elaborate on why this works as opposed to having a naked control? Here's the problem function.

`getParamView = () => {
        let paramView = null;
        let progress = null;
        
        if (this.state.selectedReport === "MarketingMaterial") {
            if (this.state.showReportProgress) {
                progress = (<div className="mm-progress-parent">
                    <Progress />
                </div>);
            }

            paramView = (
                <div className="col-md-9">
                    <div className="pm-form-grouping">
                        <label className="dropdown-label label-inline pm-label">SMAFact Card:</label>
                        <span className="padding-interior padding-bottom pm-dropdown-container">
                            <div>
                            <ComboBox
                                key="mm"
                                displayMemberPath="header"
                                selectedValuePath="binding"
                                itemsSource={this.marketingMaterialsEntities}
                                selectedIndexChanged={this.marketingMaterialsEntityChanged}
                                />
                                </div>
                        </span>
                        <span className="padding-interior padding-bottom pm-form-grouping">
                            <label className="dropdown-label label-inline pm-label">Period Date:</label>
                            <InputDate
                                key="mmPeriodDate"
                                min={this.state.minDate}
                                max={this.state.maxDate}
                                valueChanged={this.marketingMaterialsPeriodDateChanged}
                                value={this.state.marketingMaterial.periodDate}
                                format="MMMM yyyy"
                                selectionMode="Month" />
                        </span>
                        <span className="padding-interior padding-bottom pm-form-grouping">
                            <form action={marketingMaterialsUrl} method="post" target="reportIframe">   
                                <input name="rs:Embed" type="hidden" value={Boolean(true)} />
                                <input name="rc:toolbar" type="hidden" value={Boolean(false)} />
                                <input name="pGuid" type="hidden" value={this.state.marketingMaterial.guid} />
                                <input name="pPeriodDate" type="hidden" value={this.state.marketingMaterial.periodDate} />
                                <input name="pShareClassCode" type="hidden" value={this.state.marketingMaterial.shareClassCode} />
                                <input name="pInvestmentShareClassCode" type="hidden" value={this.state.marketingMaterial.investmentShareClassCode} />
                                <input name="pConfigurationId" type="hidden" value={this.state.marketingMaterial.configurationId} />
                                <input name="pReportCode" type="hidden" value={this.state.marketingMaterial.reportCode} />
                                <input name="pPortfolioK2Id" type="hidden" value={this.state.marketingMaterial.portfolioK2id} />
                                <input name="pInvestmentK2Id" type="hidden" value={this.state.marketingMaterial.investmentK2id} />
                                <input name="pUserName" type="hidden" value={this.props.user.userName} />

                                <input className="btn btn-outline-secondary" type="submit" value="View Report" onClick={this.showProgress} />
                            </form>                            
                        </span>
                    </div>
                    <div className="mm-report">
                        <iframe name="reportIframe" onLoad={this.hideProgress} title="ssrs report" src="" width="820px" height="765px" frameBorder="0" scrolling="yes" />  
                        {progress}
                    </div>
                </div>
            );
        } else if (this.state.selectedReport === "DataPak") {
            if (this.state.showReportProgress) {
                progress = (<div className="datapak-progress-parent">
                    <Progress />
                </div>);
            }

            const periodParts = this.state.dataPak.period_id.split('/');
            const period = periodParts[2] + periodParts[0];
            
            paramView = (
                <div className="col-md-9">
                    <div className="pm-form-grouping">
                        <label className="dropdown-label label-inline pm-label">Data Pak:</label>
                        <span className="padding-interior padding-bottom pm-dropdown-container">
                            <div key="datapak">
                                <ComboBox
                                    
                                    displayMemberPath="header"
                                    selectedValuePath="binding"
                                    itemsSource={this.dataPakEntities}
                                    isRequired={Boolean(true)}
                                    selectedIndexChanged={this.dataPakEntityChanged}
                                    />
                            </div>
                        </span>
                        <label className="dropdown-label label-inline pm-label">Disclaimers:</label>
                        <span className="padding-interior padding-bottom pm-dropdown-container disclaimers">
                            <div>
                                <ComboBox
                                    key="disclaimers"
                                    displayMemberPath="header"
                                    selectedValuePath="binding"
                                    itemsSource={this.disclaimers}
                                    isRequired={Boolean(true)}
                                    dropDownCssClass="disclaimers"
                                    selectedIndexChanged={this.disclaimersChanged}
                                    />
                            </div>
                        </span>
                        <span className="padding-interior padding-bottom pm-form-grouping">
                            <label className="dropdown-label label-inline pm-label">Period Date:</label>
                            <InputDate
                                min={this.state.minDate}
                                max={this.state.maxDate}
                                valueChanged={this.dataPakPeriodIdChanged}
                                value={this.state.dataPak.period_id}
                                format="MMMM yyyy"
                                selectionMode="Month" />
                        </span>
                        <span className="padding-interior padding-bottom pm-form-grouping">
                            <form action={dataPakUrl} method="post" target="reportIframe" onSubmit={this.handleReportSubmit}>
                                <input name="rs:Embed" type="hidden" value={Boolean(true)} />
                                <input name="rc:toolbar" type="hidden" value={Boolean(false)} />
                                <input name="guid" type="hidden" value={this.state.dataPak.guid} />
                                <input name="entity_type" type="hidden" value={this.state.dataPak.entity_type} />
                                <input name="portfolio_k2_id" type="hidden" value={this.state.dataPak.portfolio_k2_id} />
                                <input name="period_id" type="hidden" value={period} />
                                <input name="disclaimers" type="hidden" value={this.state.dataPak.disclaimers} />
                                <input name="UserName" type="hidden" value={this.props.user.userName} />
                                <input name="currency_iso" type="hidden" value={this.state.dataPak.currency_iso} />                                

                                <input className="btn btn-outline-secondary" type="submit" value="View Report" onClick={this.showProgress} />
                            </form>                            
                        </span>
                    </div>
                    <div className="datapak-report">
                        <iframe name="reportIframe" onLoad={this.hideProgress} title="ssrs report" src="" width="1070px" height="765px" frameBorder="0" scrolling="yes" />
                        {progress}
                    </div>
                </div>
            );
        }

        return paramView;
    }`

**Comment by gaearon** [comment]
Sorry, the question is a bit vague so it's hard to give an answer.

For an explanation of how keys work, see this: 

* https://reactjs.org/docs/reconciliation.html#keys
* https://reactjs.org/docs/lists-and-keys.html#keys

For an explanation of how to integrate with DOM-modifying libraries in a safe way, see this:

* https://reactjs.org/docs/integrating-with-other-libraries.html

If you think there's a bug in React we'll need a runnable reproducing case. Thanks!

**Comment by dharric** [comment]
I guess what I meant is it's not clear to me why having a wrapper would be sufficient to have react suddenly recognize a bunch of elements that it still is not rendering itself.

**Comment by gaearon** [comment]
If you render a DOM node with something else, React won't "recognize" it at all. I think what you're seeing is something different, but I can't guess without actually running your code.
