### ISSUE TITLE
IE 11 + window 7 display blank page. 

### ISSUE THREAD

**Issue by tiw08566** [facebook/react#13623]
Hello, 

I am working with React project, which is working properly for chrome both on QA and UAT environment. It is working for IE 11 + window 10.  But for IE 11 + window 7, it is fine on UAT environment, have problem on QA, it displays blank page.  
F12 has the following information: 
1.  console does not display any error message, except warning of "DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337"
2.   Network tab display 2 transaction, first one is "https://xxx.auth-dev.atb.com/login/callback" and second one is "http://xxx-qa.us-east.containers.mybluemix.net/callback#access_token=eyJ0eXAiOiJ..."
3.  In Debugger tab, it display message "Failed to open https://xxx.auth-dev.atb.com/login/callback'. 

After click refresh tab, url 2 return to url 1, which is "https://xxx.auth-dev.atb.com/login/callback"
then click back button, expected page is displayed.  

I did some debug and found after click login page,   our "backup" route is not called.  

Our React version is 16.3.1
I read some post from your website, which said React 16 and IE 11 has some Inconsistency, I am not sure if this error is cause by that Inconsistency  or not. 

Has any advice ?  If need more information, please let me know. 

Thank you. 
Tom

**Comment by gaearon** [comment]
React 16 runs on IE11 if you include the necessary polyfills:
https://reactjs.org/docs/javascript-environment-requirements.html

It's hard to guess what problems you're running into. If you can isolate it to a small React-only example (no third party libraries) we can take a look, but otherwise we can't really help.
