### ISSUE TITLE
a component is mounted twice

### ISSUE THREAD

**Issue by michael8090** [facebook/react#13626]
***bug***

**What is the current behavior?**

For the same component, `componentDidMount` is called multiple times, without calling `componentWillUnmount` , when using `ReactDOM.unmountComponentAtNode` .

You can use the link below to reproduce it:

https://codesandbox.io/s/x76mlw16rp

**What is the expected behavior?**

`componentWillUnmount` should be called before calling `componentDidMount` again.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.x

**Comment by whs-dot-hk** [comment]
Oh, you mean `world will unmount` didn't appear in console in your context

Let me check it out why

**Comment by whs-dot-hk** [comment]
In your example `<World />` didn't render into `div`

Try change `ReactDOM.render(<World />, div)` to

`ReactDOM.render(<World />, div, () => console.log(div))`

**Comment by gaearon** [comment]
Might be a bug, in which case you probably want to use portal as a workaround. In fact portals are a better way to do this anyway.

**Comment by michael8090** [comment]
> In your example `<World />` didn't render into `div`
> 
> Try change `ReactDOM.render(<World />, div)` to
> 
> `ReactDOM.render(<World />, div, () => console.log(div))`

`World` is just a component without any side effect, so you cannot see any child DOM element inside the `div`. But `World` does get rendered into `div` if you check out `div._reactRootContainer._internalRoot.current.child.type.name`, and you'll get the name "World".

**Comment by gaearon** [comment]
We want to support cross-renderer portals some day but yeah..

Wanna dig into what's happening?

**Comment by gaearon** [comment]
I would look for suspicious race conditions around here

https://github.com/facebook/react/blob/d3bbfe09cc47e2c5e34c3f5d0373e726981f0919/packages/react-dom/src/client/ReactDOM.js#L681-L688

https://github.com/facebook/react/blob/d3bbfe09cc47e2c5e34c3f5d0373e726981f0919/packages/react-dom/src/client/ReactDOM.js#L524-L550

**Comment by michael8090** [comment]
Yes, I checked yesterday and saw the `legacyRenderSubtreeIntoContainer` was called and the callback `() => container._reactRootContainer = null` was set, but the following `forceUpdate`(triggered by `                ReactDOM.unstable_batchedUpdates(() => this.refs.a.forceUpdate()),` somehow cancelled the real unmount task without removing the callback (that's the root cause). The component did a regular update due to the `forceUpdate`,  and the callback was called, resulting in the following updating logic thinking it was a fresh initial mount.

**Comment by michael8090** [comment]
It seems there are some strategies about merging the `Update`s in the `UpdateQueue`, do you know there they are?

**Comment by gaearon** [comment]
I'm not very familiar with this logic. But I'd expect the mistake to be related to race conditions in how this flag is set and read rather than in merging.

**Comment by michael8090** [comment]
@whs-dot-hk 

I got a simpler reproducing code: https://codesandbox.io/s/x76mlw16rp

What happened in the code is:
1. clear the World in `componentWillUnmount`
2. render the World, clear it, and render it again in `componentDidMount`

And we can see `World` is mounted again, without unmounting.

**Comment by michael8090** [comment]
@gaearon It seems when merging "unmountComponentAtNode(div) -> render(<World/>, div) -> unmountComponentAtNode(div) -> render(<World/>, div)" into "render(<World/>, div)", the callback `() => container._reactRootContainer = null` set by the first `unmountComponentAtNode` is not cleared. So maybe the issue is in the merging code?

**Comment by gaearon** [comment]
Maybe. Want to try fixing it?

**Comment by michael8090** [comment]
Sure, maybe I need some time to find where the merging code lies, could you shed some light on it?

**Comment by whs-dot-hk** [comment]
@michael8090 You mean

https://github.com/facebook/react/blob/144328fe81719e916b946e22660479e31561bb0b/packages/react-dom/src/client/ReactDOM.js#L682-L684

haven't been consume yet?

**Comment by whs-dot-hk** [comment]
@michael8090 The problem is here

https://github.com/facebook/react/blob/d3bbfe09cc47e2c5e34c3f5d0373e726981f0919/packages/react-dom/src/client/ReactDOM.js#L535-L536

https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-reconciler/src/ReactFiberReconciler.js#L256-L257

Which just call the callback at

https://github.com/facebook/react/blob/144328fe81719e916b946e22660479e31561bb0b/packages/react-dom/src/client/ReactDOM.js#L682-L685

So more have to be done in that callback

Maybe unmount?

**Comment by whs-dot-hk** [comment]
I would try to add calling `componentWillUnmount` into that callback.

@michael8090 Sending a PR?

**Comment by michael8090** [comment]
@whs-dot-hk Thanks for your help, but I don't think it's the right way to fix the issue. The callback is just for clearing the meta data attached with the DOM element after the actual unmount job, so we should not do the job inside the callback.

**Comment by whs-dot-hk** [comment]
@michael8090 You are right I think it should be passing the "child" into the already recursive `legacyRenderSubtreeIntoContainer`

**Comment by whs-dot-hk** [comment]
@michael8090 Oh, no the `unmountComponentAtNode` logic is right there as @gaearon point out earilier

**Comment by michael8090** [comment]
@whs-dot-hk I'm still trying to figure out the updating and merging logic by reading the code, and honestly don't have a clue on how to fix the issue.  @gaearon is right that the issue is caused by the condition race, but I cannot find the code responsible for making up the race.

**Comment by gaearon** [comment]
First step that would be helpful is to make a failing test.

**Comment by michael8090** [comment]
@gaearon Thanks for the tip, I'll work on it today.
