### ISSUE TITLE
Add PrimeReact to Community UI Components Page

### ISSUE THREAD

**Issue by cagataycivici** [facebook/react#13631]
Sorry to post this here as I could not find another communication channel, I'd appreciate if you could add PrimeReact UI Suite to;

https://reactjs.org/community/ui-components.html

PrimeReact is an open source UI Suite for React.

https://www.primefaces.org/primereact/

Thank you.

**Comment by gaearon** [comment]
Please file it against https://github.com/reactjs/reactjs.org instead, thanks

**Comment by cagataycivici** [comment]
Got it, thank you.
