### ISSUE TITLE
state and lifecicle

### ISSUE THREAD

**Issue by ratelChief** [facebook/react#13637]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

bug

https://ru.react.js.org/docs/state-and-lifecycle.html

Добавление локального состояния в класс
"1.Заменить this.props.date на this.state.date в методе render(): "
и далее по тексту во всех примерах фигурирует this.props.date

**Comment by gaearon** [comment]
Это ошибка в переводе. В оригинальной статье этой проблемы нет.
https://reactjs.org/docs/state-and-lifecycle.html

**Comment by gaearon** [comment]
(Перевод не наш — я не знаю кто его хостит)
