### ISSUE TITLE
React onTransitionEnd event gets called frequently

### ISSUE THREAD

**Issue by oste** [facebook/react#13633]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

`onTransitionEnd` callback is getting called repeatedly even when a transition doesn't end. To reproduce in the demo below. Click the first button and noticed onTransitionEnd the callback is called 3 times. Clicking the button below then calls it another 2 times randomly. In my app it is more extreme where the callback is called a lot more frequently.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/vy5wwyq5v3

**What is the expected behavior?**

`onTransitionEnd` only gets called once at the end of a css transition

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3 on all browsers

**Comment by nmain** [comment]
Adding a native `transitionend` handler to the DOM `<button>` element produces the same number of calls.  If you inspect `event.nativeEvent.propertyName`, you'll see that you're receiving events for various other properties in addition to `margin-left`.  If you change your `style` to
```
          style={{
            transition: "margin-left 3s",
            marginLeft: `${10 * this.state.left}px`
          }}
```
the extra calls go away.


I don't know enough about the innards of the CSS transition spec to tell you why `transition: all` is firing events for things that seemingly have not changed, but there's no problem with React here.
