### ISSUE TITLE
[feature request] Add DOM to life cycle hooks.

### ISSUE THREAD

**Issue by back2dos** [facebook/react#13646]
Currently, it's not very straight forward to get your hands on a components full DOM - in particular if it returns multiple elements. In that case `ReactDOM.findDomNode` just won't work. So you're left with refs, but you'll never get the whole dom *at once* - instead you get one element at a time. You can of course do something along the lines of this:

```js
class CityList extends Component {
  render() {
    this.childElements = []; 
    let store = this.childElements.push.bind(this.childElements);
    return this.props.cities.map(p => <li class="city" ref={store}>...</li>);
  }
  componentDidMount() {
    //access this.childElements here
  }
}
```

But that feels a bit awkward.

Hence my question is: how about adding the DOM nodes rendered for a given component at the end of the argument list of the relevant life cycle events? If I'm not mistaken, those would be `componentDidMount`, `getSnapshotBeforeUpdate`, `componentDidUpdate` and `componentWillUnmount` (as well as *perhaps* `shouldComponentUpdate` although I'm not sure why that would be a good time to access the DOM). I haven't dug too deep into React's internals, but my naive guess would be that this information should be available when those life cycle hooks are being called.

On a more "philosophical" note: It seems to me that storing references to the DOM in the component just isn't all that clean. In event handlers, you can use the event to reach into the DOM and it seems to me that life cycle hooks are practically destined to allow the same.

Thanks for your consideration :)

**Comment by gaearon** [comment]
I think the solution for this is to use a callback ref and fill an array:

```js
class CityList extends Component {
  childElements = [];
  render() {
    return this.props.cities.map((p, index) =>
      <li class="city" ref={node => {
        this.childElements[index] = node;
      }}>...</li>
    );
  }
  componentDidMount() {
    //access this.childElements here
  }
}
```

I don't really see React providing a special API for this. It's easy enough to do when you need it, but in most cases we want to discourage direct DOM manipulation. There is also performance overhead for attaching refs so we don't want to do it by default.

**Comment by back2dos** [comment]
Hi Dan,

thanks for the prompt response. From what you've written I can see that I've expressed myself poorly:

> I don't really see React providing a special API for this. [...] There is also performance overhead for attaching refs so we don't want to do it by default.

I have neither asked for a special API (although I'm not sure what exactly you mean by "special") nor for attaching refs. I should have given an example right away:

```js
class CityList extends Component {
  render() {
    return this.props.cities.map(<li class="city">...</li>);
  }
  componentDidMount(...domNodes) {
    //access domNodes here
  }
  componentDidUpdate(prevProps, prevState, snapshot, ...domNodes) {//domNodes are always at the end
  }
}
```

Maybe that's clearer? Indeed, that would still lead to the allocation of the `domNodes` array, but my best guess is that it should be negligible compared to everything else that's going on during the reconciliation. 

Initially, I was thinking this should be easy, because React must have that information. Having looked into the reconciler though, things seem to be way more complicated than I initially assumed. But perhaps it's possible without too much effort after all?

The solution you've proposed improves upon the one I gave, but doesn't address the core issue: the developer has to maintain DOM references manually. Of course they can, but I think it'd be much nicer if they didn't have to, the same way it is much nicer that `prevState` and `prevProps` are being passed to `componentDidUpdate` even though this would work just fine:

```
class Whatever extends Component {
  storePrev() {
    this.prevState = this.state;
    this.prevProps = this.props;
  }
  componentDidMount() {
    storePrev();
  }
  componentDidUpdate() {
    let { prevState, prevProps } = this;
    storePrev();
    // write some code here
  }
}
```

The same goes for the result of `getSnapshotBeforeUpdate()` being passed around by the framework. It's not just convenient, it means that as a developer you have less mutable state to maintain.

As for your last point:

> in most cases we want to discourage direct DOM manipulation

I absolutely agree, but there are cases when you want to access the DOM. In fact, the one and only use case the documentation gives for `getSnapshotBeforeUpdate` is: 

> It enables your component to capture some information from the DOM (e.g. scroll position) before it is potentially changed.

Hence my suggestion of passing the DOM after the other function arguments, which should be fully backwards compatible.

**Comment by gaearon** [comment]
If you strongly feel that this is valuable, I suggest drafting an RFC with a more detailed proposal: http://github.com/reactjs/rfcs. But I want to set a clear expectation that it's unlikely we'll go down that route. That said if you write a detailed RFC I should be able to respond in more detail why I don't think this will work well.

**Comment by back2dos** [comment]
Thanks for the heads up ;)
