### ISSUE TITLE
"Cannot update during an existing state transition" exception is not caught by componentDidCatch

### ISSUE THREAD

**Issue by 1999** [facebook/react#13655]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I'm working with `react-apollo` right now and there was a mistake in my code which could re-render the inner query at the same time with the outer query (this was an integration test). I can see this React error in the console (which perfectly makes sense), but the problem is that I expect it to be caught by top-level boundary component with componentDidCatch() but it didn't get executed in this case. As a result, `jest` hangs up and bitbucket pipelines stop the build for the PR after 2 hours of inactivity.

**What is the expected behavior?**

I guess componentDidCatch() could've caught this exception.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

We're using React@16.4.1

**Comment by gaearon** [comment]
Maybe we could do it. I'm not sure. Right now it's kind of treated as a fatal error. Otherwise it might be difficult to ensure we get to a terminal state. On the other hand we could keep unwinding boundary by boundary when this happens, like we do normally.

**Comment by 1999** [comment]
Is there a way for developers to catch this kind of exception right now?

> unwinding boundary by boundary

Not sure what this means tbh.
