### ISSUE TITLE
How to edit oauth 2 Configuration inside Quip.

### ISSUE THREAD

**Issue by VaishaliGarg2017** [facebook/react#13661]
Your help is very helpful for us.

I would like to ask one more question. I am working on some integration of quip doc to some other app. inside authorization URL I also want to add the question mark. can you please tell, Is there any way which helps to add inside configuration of outh2 quip.

example: my Authorization URL is: www.quip.com/authorization Now I want to hit Authorization URL by www.quip.com/authorization?type=user_agent // it send me error.

please tell can we add "?type=user_agent" by using coding.

It will be very helpful for us.

Regards, Vaishali.

**Comment by aweary** [comment]
Hey @VaishaliGarg2017, this is the issue tracker for the React repo, which is unrelated to Quip. You should try some Quip support resources. https://fb.quip.com/dev/ looks like it might be helpful.

If you're using React, please check our community support resources:
https://facebook.github.io/react/community/support.html
