### ISSUE TITLE
Is it possible to react skip some dom nodes on hydrate which are different from server render.

### ISSUE THREAD

**Issue by demil** [facebook/react#13664]
if my server component is for example:

    class Test extends React.Component { 
    ...
    render() {
    return <React.Fragment>
            <div> {this.props.server_data} </div>
            <div onClick={make_this_div_update_on_client}> {this.state.client_staff} </div>
        </React.Fragment >
       }
    }

and on server i will render with props which are not available on client

    ReactDOMServer.renderToString(<Test server_data="Hello from server!" />)

but on frontend when i rehydrate app with:

    ReactDOM.hydrate(<Test />, document.querySelector(".app"));

It updates this DOM node because this.props.server_data is empty.

How can i make react to not touch some DOM nodes that are created on server and only hydrate other parts of the tree? Is this kind of behaviour possible?

For example something like this:
      
    class Test extends React.Component { 
     ...
    render() {
    return <React.Fragment>
            <div donTouchThisOnClient> {this.props.server_data} </div>
            <div onClick={make_this_div_update_on_client}> {this.state.client_staff} </div>
        </React.Fragment >
       }
    }

**Comment by gaearon** [comment]
Don't have a great solution but https://github.com/facebook/react/issues/10923#issuecomment-338715787 should work for now.

**Comment by bloody-ux** [comment]
Is it possible for react to implement partial hydration like [astro](https://docs.astro.build/en/core-concepts/component-hydration/)?

For those components don't have interaction, we needn't send rendering code to client bundle.

**Comment by gaearon** [comment]
Our approach to that is called Server Components and is described here. We’re still researching that. https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html

**Comment by trinhthinh388** [comment]
Seems like [#10923](https://github.com/facebook/react/issues/10923#issuecomment-338715787) not working in React 17.
Do we have another way to achieve the skipping hydration effect in React 17?
