### ISSUE TITLE
Is it possible to use Profiler server side?

### ISSUE THREAD

**Issue by lazopm** [facebook/react#13673]
I'm trying to use the Profiler server side rendering with `renderToString` but the onRender callbacks are not getting called.

Is there a way to do it?
I'm using 16.5.1, NODE_ENV === "development".

My code looks like this, works fine client side:
```javascript
import React, { unstable_Profiler } from 'react';

const profilerCallback = (id, phase, actualTime, baseTime, startTime, commitTime) => {
        console.log(`${id}'s ${phase} phase:`);
        console.log(`Actual time: ${actualTime}`);
        console.log(`Base time: ${baseTime}`);
        console.log(`Start time: ${startTime}`);
        console.log(`Commit time: ${commitTime}`);
};

const MyComponent = () => (
    <Profiler id="card" onRender={profilerCallback}>
        ...
    </Profiler>
)
```

**Comment by gaearon** [comment]
No, it's not currently supported.

**Comment by NE-SmallTown** [comment]
Any plan on this? I'm happy to investigate it if I could help

**Comment by bvaughn** [comment]
Despite its name, the `onRender` callback is called on _commit_ and there is no "commit" phase on the server– so the `Profiler` was implemented as a no-op for the server renderer. (It won't break the app, but it won't collect or log any metrics either.)

I don't feel strongly about this either way, just offering some additional context.

**Comment by lazopm** [comment]
@bvaughn thanks for the info! Also thanks for working on Profiler, it has helped us so much to find which components are slowing down rendering.

For us server side render speed is much more important than client side. Right now I am only tracking the entire renderToString call using Node perf_hooks. It would be really nice to be able to use Profiler in Node to track performance more granularly.

I would be happy to try to work on this if someone could point me in the right direction.

**Comment by einperegrin** [comment]
Is any plan on this feature?
