### ISSUE TITLE
event.target.text returns undefined in react 16.3.0

### ISSUE THREAD

**Issue by uditdubey** [facebook/react#13678]
Hello,
i am using react v16.3.0 and react-bootstrap v^0.32.1 when i select the dropdown, i am unable to get the selected text value as the event.target.text says "cannot read text of undefined"

Here is my code:
///dropdown
<DropdownButton title={test} onSelect={(e) => this.testmeFunction(e)}>
                      {
                        liveGraphTypeOptions.map((item) => {
                          return (
                            <MenuItem eventKey={item.index} >{item.value}</MenuItem>
                          );
                        })
                      }
                    </DropdownButton>

//////function
testmeFunction=  (event) => {
  let setVar = event.target.text; 
}

Thanks !!

**Comment by jquense** [comment]
Hey there, we try and keep the react issue tracker specific to react bugs and features. The issue you've run into is that react-bootstrap doesn't pass the event object as the first argument to the drop-down onSelect handler, it's the eventKey

**Comment by uditdubey** [comment]
Thanks @jquense !!
I tried replacing event by eventKey but still not working.. Can you please recheck my function and suggest me what i have done wrong cause it was working fine on react v15

**Comment by jquense** [comment]
You should react the react-bootstrap docs this isn't a react issue the onSelect event here isn't the browser one it's fired when something is picked in the drop-down

**Comment by uditdubey** [comment]
Hey i read the react-bootstrap docs, I was passing item.index previously in the eventKey param inside menuitem so changed it to item.value and it works fine.
now changed onSelect to onClick and event.target.text also works !!
Thanks for the suggestion
