### ISSUE TITLE
Children.map & Co do not traverse keyed Fragments

### ISSUE THREAD

**Issue by arty-name** [facebook/react#13677]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

<a href="https://reactjs.org/docs/react-api.html#reactchildren">The documentation on React.Children.map</a> tells us that "If children is a keyed fragment or array it will be traversed: the function will never be passed the container objects." [This demo](https://jsfiddle.net/cxq9dzet/) shows that arrays are indeed traversed, but the <a href="https://reactjs.org/docs/fragments.html#keyed-fragments">keyed fragments</a> are not traversed. Open the developer console and click "Run" to see the output.

**What is the expected behavior?**

Children.map, forEach, toArray, count should traverse keyed Fragments as per documentation.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The example runs on v16.5.1, but I have also seen that fail locally on v16.4.2. I never tried this before so I don’t know if this ever worked. I see it fail in latest Firefox and Chrome on Ubuntu Linux.

**Comment by arty-name** [comment]
I think that the test I have added in  #13679 also demonstrates the bug

**Comment by jquense** [comment]
I don't think this is a bug actually, it's been discussed a few times in other issues and I believe the consensus was that it's intended that fragments be distinct elements vs an array of elements

**Comment by arty-name** [comment]
@jquense so is this a bug in the documentation?

**Comment by jquense** [comment]
Sounds like it but let's wait for a core team member to confirm

**Comment by arty-name** [comment]
Some way to automatically “flatten” the `Fragments` among the children will be a much desired feature anyway. I would be happy to see the code to work as currently specified in the documentation.

**Comment by bvaughn** [comment]
> I don't think this is a bug actually, it's been discussed a few times in other issues and I believe the consensus was that it's intended that fragments be distinct elements vs an array of elements

Yes, it is intentional the `.map` does not traverse into fragments. I'll update the docs. Apologies for the confusion!

**Comment by arty-name** [comment]
After more searching I have found [this comment](https://github.com/facebook/react/issues/11859#issuecomment-355656427) by Dan Abramov: 

> I think changing behavior for both might be reasonable.

Which I interpret as this implementation not being particularly intentional. He then proposes to submit an RFC for these changes, but I couldn’t find any at the moment. I will try to create one now.

**Comment by arty-name** [comment]
[RFC to flatten Fragments](https://github.com/reactjs/rfcs/pull/61)

**Comment by bvaughn** [comment]
> Which I interpret as this implementation not being particularly intentional.

Maybe, although for what it's worth I talked to him to confirm this was intentional earlier yesterday:

> Brian: Should React.Children.map treat Fragment as a single child? Docs are worded a bit ambiguously
> Dan: Yeah that's intentional.
> Brian: Cool, just wanted to confirm. I'll update the docs then.

That being said, an RFC sounds like the right way to go 👍
