### ISSUE TITLE
Special lifecycle hooks are not being called when using `ReactCSSTransitionGroup`

### ISSUE THREAD

**Issue by 0m15** [facebook/react#1368]
When using `<ReactCSSTransitionGroup>` on a component, the special lifecycle hooks are not being called.

I think it would be useful and nice to know when a transition occurs and which state the transition owns.

I guess `ComponentWillEnter`, `ComponentDidEnter` and other special methods were meant to expose those states, but I cannot make it work, unless I use `<ReactTransitionGroup>`, but this way css classes are not being applied during the transition.

Documentation here (http://facebook.github.io/react/docs/animation.html) states:  

"ReactTransitionGroup is the basis for animations. When children are declaratively added or removed from it (as in the example above) special lifecycle hooks are called on them."

"The example above" is using `<ReactCSSTransitionGroup>`, so one would expect to have those special hooks being called, but it seems they don't.

**Comment by cameronjroe** [comment]
I am also struggling with this. I'm trying to animate a few elements using componentWillEnter, componentDidEnter with TweenMax and the methods don't seem to get called. If ReactCSSTransitionGroup is to model after ng-animate I would be expecting that it should call methods for javascript animation along with adding enter, leave, change classes.

**Comment by zimok** [comment]
@cameronjroe as far as I understand, all these behaviour will be introduced in one of the next releases of React, as you can check taking a look at the master branch

https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroup.js

**Comment by cameronjroe** [comment]
I didn't notice but it looks like those methods are exclusively for `ReactTransitionGroup`, which I hadn't noticed the difference from `ReactCSSTransitionGroup`.

**Comment by tannerlinsley** [comment]
After hunting around the net for quite a long time for a solution to this problem, I'm wondering why the lifecycles methods are not just called in addition to the default css class functionality here.  There definitely are times when I need to know at the component level whether it is entering or exiting a transition group.  I am really really hoping that I wouldn't be expected to reimplement the `reactCSSTransitionGroup` class on my own to do this.  

Is there any reasoning behind this decision? Are these addons being replaced/deprecated in favor of a more robust API in the near future?

**Comment by gaearon** [comment]
These addons are not under any kind of development, and we indeed plan to deprecate them because we just don’t use them much, and their APIs have some inherent problems (e.g. hooks don’t work with stateless functional components anyway).

We recommend looking at [React Motion](https://github.com/chenglou/react-motion) and similar projects instead.

**Comment by iDVB** [comment]
UPDATE - @gaearon 
I narrowed down "where" the issue is for us, but not sure of the "why". So if you recall, our issue was that our Page component (Home) was not firing the hooks. Note: Our Page component is wrapped in two compositions `WindowState(GSAP(Home))`. When I remove `WindowState()` (a custom one I wrote), everything works fine.

Here is the component:
```
import React from 'react';
import throttle from 'lodash.throttle';

export var WindowState = ComposedComponent => class extends React.Component {

  constructor(props, context) {
      super(props, context);
      this.state = { 
        window: { height: 0, width: 0 }, 
        document: { height: 0, width: 0 } 
      };
  }

  componentWillMount() {
    this._onResize = function() {
      this.setState({
        window: { height: window.innerHeight, width: window.innerWidth },
        document: { height: document.body.clientHeight, width: document.body.clientWidth }
      })
    }.bind(this);

    this._onResize();
  }

  componentDidMount() {
    this._onResizeThrottled = throttle(this._onResize, 10);
    window.addEventListener("resize", this._onResizeThrottled);
  }

  componentWillUnmount() {
    window.removeEventListener("resize", this._onResizeThrottled);
  }

  render() {
      return <ComposedComponent {...this.props} {...this.state} />;
  }
};
```

Any ideas why GSAP is able to pass through the hooks but my component is not? This component was my first attempt at writing a HOC.

**Comment by droidenator** [comment]
@gaearon If the plan is still to deprecate the addons, would it be possible to add a deprecation notice to the React docs? The page for `reactCSSTransitionGroup` still comes up very high in search results and there's no indication that the addon will be deprecated. I just happened to stumble on this issue while trying to get `reactCSSTransitionGroup` to work for me. 

Adding that deprecation notice might save some people some time in the future.

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition

**Comment by gaearon** [comment]
This is the official repo for TransitionGroup now: https://github.com/reactjs/react-transition-group

**Comment by ababba15** [comment]
I can suppose that child's `componentWillReceiveProps()` and `componentDidUpdate()` are not called, that's why we can't get working the `componentWillEnter()`. Because it is defined inside `componentDidUpdate()`
