### ISSUE TITLE
The Input render by createProtal will blur when input

### ISSUE THREAD

**Issue by zWingz** [facebook/react#13685]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

the input render by portal will blur when input

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

see [https://codesandbox.io/s/j7vy574wny](https://codesandbox.io/s/j7vy574wny)
types in diff input

**What is the expected behavior?**

just change value, but not blur

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

latest version

**Comment by gaearon** [comment]
It doesn’t work because you create a new div on every render (including updates) and move the portal to it.

This works: https://codesandbox.io/embed/j7vy574wny?codemirror=1

**Comment by gaearon** [comment]
Sorry, my link didn’t work because I edited from mobile and looks like CodeSandbox didn’t save my changes (cc @compuives).

But basically I moved creation of the parent div into constructor, and attaching it to the document to componentDidMount. In the render I would always render the portal to `this.div`.

**Comment by zWingz** [comment]
@gaearon thanks. it's my fault.
