### ISSUE TITLE
Implement FileReader.readAsArrayBuffer

### ISSUE THREAD

**Issue by Smarticles101** [facebook/react#13691]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`FileReader.readAsArrayBuffer` is currently unimplemented.

**What is the expected behavior?**
`FileReader.readAsArrayBuffer` should be implemented.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All versions of React are affected.

If approved, I plan to work towards implementing this. I may need some guidance along the way. It'll be my first time using native code with React, or using native iOS code.

**Comment by gaearon** [comment]
You probably meant to file this in https://github.com/facebook/react-native

:-)

This is the repository for generic parts and the web version.

**Comment by Smarticles101** [comment]
Oops! You're right. Thanks @gaearon 😄
