### ISSUE TITLE
 react error looking for schedule@^0.5.0

### ISSUE THREAD

**Issue by dptoot** [facebook/react#13693]
**Do you want to request a *feature* or report a *bug*?**
Bug
 
**What is the current behavior?**
Installing 16.5.2 seems to throw and error looking for schedule@^0.5.0 which doesn't exist

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

npm ERR! code ETARGET
npm ERR! notarget No matching version found for schedule@^0.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'react'

**What is the expected behavior?**

React should get installed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.5.2

**Comment by bvaughn** [comment]
Not sure what's going on– maybe a transient NPM registry issue– but `schedule@0.5.0` has definitely been published to NPM. You can see it [here](https://unpkg.com/schedule@0.5.0/index.js) and [here](https://www.npmjs.com/package/schedule).

Also, both the JSFiddle and Code Sandbox you linked to work fine 😄 so I'm going to assume this was just an NPM/cache hiccup.

**Comment by dptoot** [comment]
I appreciate you looking into it.  Yes.  I think it may have been a caching issue within our npm proxy.  Sorry for wasting some time!  Thanks again.

**Comment by RulerOf** [comment]
We're experiencing the same thing right now, exactly the same error text as @GraydonHaskins.  I suggest adding a thumbs-up to [his post](https://github.com/facebook/react/issues/13693#issuecomment-438116271) above for others who are Googling their way in here.

**Comment by ryanab** [comment]
I just installed react@16.6.1 seems to work i the interim.

**Comment by matt-meyer-nyc** [comment]
I've got the same problem with scheduler@^16.6.2

I did `npm install react@16.6.1` and it's still not working.

For those that got it to work, did the command also require `--save`?

Thanks!

**Comment by matt-meyer-nyc** [comment]
No. When I did `create-react-app my-app` it didn't install  'package.json' ... it installed 'package-lock.json'  

Which I've never seen

Ryan...you needed --save with it though, right?

**Comment by andrewquartey** [comment]
> I also installed react-dom@16.6.1 FYI

oh yes got it

**Comment by matt-meyer-nyc** [comment]
Yes. I used create-react-app and it worked.

**Comment by Shannor** [comment]
Yeah it looks like they fixed it with the 16.6.3.

**Comment by benuklove** [comment]
I was having this problem too.  No matching version found for scheduler@^16.6.2.
Just ran
`npx create-react-app react-tutorial` and it worked this time.

**Comment by adilmalik393** [comment]
Also had the same issue. Changing in my package.json like following worked
**changing from**
`  "react": "^16.6.1",
    "react-dom": "^16.6.1",`
**changing too**
`    "react": "16.6.1",
    "react-dom": "16.6.1",`

**Comment by AlejandroRodriguezP** [comment]
i decided to wait and tried to use create-react-app and its working again!

**Comment by fyodorVS** [comment]
Confirmed, it works!

**Comment by zemacnica** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for scheduler@0.13.2

this version is published on npm

**Comment by gaearon** [comment]
https://unpkg.com/scheduler@0.13.2/

You're probably behind some npm mirror.

----

I'm locking this thread since the original issue was resolved and now it attracts misinformation.
