### ISSUE TITLE
Component from previous route are staying in memory while navigation to a different route.

### ISSUE THREAD

**Issue by zero1hac** [facebook/react#13702]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I am using react-router for making a single page application which have multiple routes. While navigating between the routes, I noticed that the component from the previous route is still present in the memory e.g. If I navigate from route1 to route2, I can see that component corresponding to route1 is still in the memory. Moreover, if I change my route from route1 to route2 then route2 to route3, the component from route1 is cleared out and route2 component is still in the memory while I am at route3. 

Adding heap snapshot for this unexpected behaviour :
![react1](https://user-images.githubusercontent.com/7602070/45832299-28be5c00-bd1f-11e8-937a-37d6c9da4270.JPG)

CodeSandbox demo for reproducing the same: [Demo](https://codesandbox.io/s/9z7qylm4mo)

**What is the expected behavior?**
Ideally, component corresponding to the previous route must be completely removed from the memory when we navigate to the new route. Or there must be some rule if we are keeping it for some optimizations.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 16.4.2
react 16.4.2
react-router-dom 4.3.1

**Comment by abhikmitra** [comment]
@gaearon So we investigated this . If you see the screenshot below, you would see that route 3 (test3) has a deep nested react components each with a huge state. 

When I go to route 4 (test 4 - see the heap snapshot below) not only the root component but the nested child along with its state is there. As a result the route memory for test4 bloats up.

It gets only garbage collected in route 5. While debugging we could see (as you mentioned above) that during reconciliation it gets gc-ed while creating the next WIP tree when the previous fibers are used and effects(nextEffect, firstEffect, lastEffect) is wiped out. So the references to Test3 get removed at this line in [ReactFiber.js](https://github.com/facebook/react/blob/e1a067dea0ffcacd1f664f30cd14463b00f52fa7/packages/react-reconciler/src/ReactFiber.js#L349)

But the parent of Test3 which is the route component of type (ƒ Route()) still keeps a reference to Test3 using its lastEffect. The lastEffect is reset when the fiber gets reused in the code pointed above.

So from the behaviour it seems, a fiber node even though its disconnected from parent , child and alternate using the detach fiber can still have references to it  from other fibers using the effects array.







<img width="1678" alt="screen shot 2018-09-20 at 10 09 13 pm" src="https://user-images.githubusercontent.com/4750072/45833298-011cc300-bd22-11e8-9753-912034579b13.png">

**Comment by gaearon** [comment]
>So from the behaviour it seems, a fiber node even though its disconnected from parent , child and alternate using the detach fiber can still have references to it from other fibers using the effects array.

I think this makes sense. Thanks for explaining.

**Comment by Conditional-statements** [comment]
> [@gaearon](https://github.com/gaearon) So we investigated this . If you see the screenshot below, you would see that route 3 (test3) has a deep nested react components each with a huge state.
> 
> When I go to route 4 (test 4 - see the heap snapshot below) not only the root component but the nested child along with its state is there. As a result the route memory for test4 bloats up.
> 
> It gets only garbage collected in route 5. While debugging we could see (as you mentioned above) that during reconciliation it gets gc-ed while creating the next WIP tree when the previous fibers are used and effects(nextEffect, firstEffect, lastEffect) is wiped out. So the references to Test3 get removed at this line in [ReactFiber.js](https://github.com/facebook/react/blob/e1a067dea0ffcacd1f664f30cd14463b00f52fa7/packages/react-reconciler/src/ReactFiber.js#L349)
> 
> But the parent of Test3 which is the route component of type (ƒ Route()) still keeps a reference to Test3 using its lastEffect. The lastEffect is reset when the fiber gets reused in the code pointed above.
> 
> So from the behaviour it seems, a fiber node even though its disconnected from parent , child and alternate using the detach fiber can still have references to it from other fibers using the effects array.
> 
> Also this is reproducible in the production version as well. Here are the detailed Repro Steps
> 
> * Load the [sandbox](https://codesandbox.io/s/9z7qylm4mo)
> * Navigate to Route 3 and take memory snapshot
> * Navigate to route 4 and take memory snapshot (All the route 3 components still persist)
> * Navigate to route 5  and take memory snapshot (All the route 4 components still persist, route 3 is gone)
> * Wait for 10 seconds for it trigger a state change automatically , and take memory snapshot (route 4 is gc-ed)
> 
> <img alt="screen shot 2018-09-20 at 10 09 13 pm" width="1678" src="https://user-images.githubusercontent.com/4750072/45833298-011cc300-bd22-11e8-9753-912034579b13.png">





https://grading288.github.io/distribution2/
