### ISSUE TITLE
Accessing ReactDebugCurrentFrame without using __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED

### ISSUE THREAD

**Issue by Methuselah96** [facebook/react#13704]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.

**What is the current behavior?**
I am working on writing a custom React renderer (https://github.com/toxicFork/react-three-renderer-fiber) and right now I have to use `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` in order to access stack information for the current frame in order to display warnings for the developer (https://github.com/Methuselah96/react-three-renderer-fiber/blob/react-reconciler/src/core/customRenderer/descriptors/CustomDescriptor.ts#L102).

**What is the expected behavior?**
I would like to be able to access the stack information for the current frame without worrying for the safety of my employment. Is there a better way for me to be doing this?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.5.2

**Comment by nemoDreamer** [comment]
Any movement on this?
Or any proposed alternative?

**Comment by gaearon** [comment]
@nemoDreamer What is your use case

**Comment by nemoDreamer** [comment]
Hey @gaearon! We're overloading Facebook's `warning` with a helpful `.getStackAddendum()`:

https://gist.github.com/nemoDreamer/6ad4000653e3db4837948ad837ece077

**Comment by gaearon** [comment]
How do you use it?

**Comment by gaearon** [comment]
Meaning, what kind of warnings?

**Comment by nemoDreamer** [comment]
Sorry: part of a Design Language exposing "basics" and themed "roles" that we want to print deprecation warnings for.

**Comment by nemoDreamer** [comment]
In the absence of `.getStackAddendum`, the `console.error`'s stack is sufficient, some of our consumers are trying to debug in environments like Qt Web with limited web-view debuggers, and every clearer trace helps cut to the right files of their bundled builds.
