### ISSUE TITLE
Upgrade Rollup

### ISSUE THREAD

**Issue by mmarkelov** [facebook/react#13701]
Working on upgrading rollup - some test builds show decreasing in size of bundles.
But also there are some problems with it:

1. The `legacy` option is now deprecated, so is it critical for building **react** ?
I checked this [issue](https://github.com/rollup/rollup/issues/2135) - and it tells that it's totally fine.
2. There are couples **circular dependency** warnings with `ReactFiberScheduler.js`  and also some **default' is not exported** warnings

You also can check my [branch](https://github.com/mmarkelov/react/tree/Upgrade_Rollup)
Maybe you can help me with it

So what do you think about this? Does that make sense?

**Comment by TrySound** [comment]
WIP in https://github.com/facebook/react/pull/13356 https://github.com/facebook/react/pull/13321

**Comment by mmarkelov** [comment]
@TrySound, just didn’t see these prs ( My mistake. If you need some help about this I’ll be happy to help you
