### ISSUE TITLE
Context Consumer not rendering correctly inside <select><option> tag

### ISSUE THREAD

**Issue by MunifTanjim** [facebook/react#13706]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Context Consumer is not rendering correctly if placed inside HTML `<select><option>` tag.

**Reproduction:**

`src/App.js` (in a fresh `create-react-app` generated project):
```js
import React from 'react'

const ExampleContext = React.createContext()

const ExampleValues = {
  number: {
    zero: 'Zero'
  }
}

class App extends React.Component {
  render() {
    return (
      <ExampleContext.Provider value="number">
        <ExampleContext.Consumer>
          {value => ExampleValues[value].zero}
        </ExampleContext.Consumer>
        <select>
          <option value="0">
            <ExampleContext.Consumer>
              {value => ExampleValues[value].zero}
            </ExampleContext.Consumer>
          </option>
        </select>
      </ExampleContext.Provider>
    )
  }
}

export default App
```

The first `<ExampleContext.Consumer>` renders `Zero` as expected.

But the second one renders `[object Object]`.

**What is the expected behavior?**

The second `<ExampleContext.Consumer>` should render `Zero`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**React version**: 16.5.2
**Browser**: Chrome 69
**OS**: Ubuntu MATE 18.04

> Did this work in previous versions of React?

Don't know.

**Comment by hamlim** [comment]
This looks related to these issues: https://github.com/facebook/react/issues/13699 and https://github.com/facebook/react/issues/13586. I think the suggested solution is to move the context consumer outside of the option:

```jsx
class App extends React.Component {
  render() {
    return (
      <ExampleContext.Provider value="number">
        <ExampleContext.Consumer>
          {value => ExampleValues[value].zero}
        </ExampleContext.Consumer>
        <select>
          <ExampleContext.Consumer>
            {value => (
              <option value="0">{ExampleValues[value].zero}</option>
            )}
          </ExampleContext.Consumer>
        </select>
      </ExampleContext.Provider>
    )
  }
}
```

**Comment by gaearon** [comment]
18 is out with the fix.
