### ISSUE TITLE
Improved stack trace

### ISSUE THREAD

**Issue by Aftabnack** [facebook/react#13715]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**

* The usability of the current stack trace for components with native dom elements can be improved.
![image](https://user-images.githubusercontent.com/43165983/45943746-33217400-c005-11e8-953b-2e016bd10f9d.png)
* In this example it tells me that there are 3 divs, followed by a select tag (Not sure why select's display name is showing as the components' name itself) and then option tag. But this same structure exists in lot of places in the component.

**What is the expected behavior?**
* Stack trace with line number/some other way to pinpoint it's location (like id/class if provided??) is desired

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
OS: Ubuntu 18.04
React: 16.2.0

**Comment by skiritsis** [comment]
In case you are using _babel_ you can use the following plugin: `@babel/plugin-transform-react-jsx-source` to view both source file and line numbers.

**Comment by Aftabnack** [comment]
I tried to do a small repro in CRA v2. It is pretty neat!
It properly showed `select` tag and restricted the error stack to the file and line number. :v: :v: 

![image](https://user-images.githubusercontent.com/15635777/46664483-ca2e2480-cbde-11e8-835d-7d29bb9f29ed.png)

Now I'm curious what magic have we done in CRA to enable this???
\cc @gaearon

**Comment by skiritsis** [comment]
@Aftabnack No extra magic required, it is already built-in React.
See https://github.com/facebook/react/blob/master/packages/shared/ReactElementType.js

You can configure your babel config file to include the plugin in DEV environment, to produce more user friendly errors and disable it in PRODUCTION environment (since those properties will not exist in React Production anyway).
