### ISSUE TITLE
Schedule package problem on NPM (not on Yarn) 16.5.2

### ISSUE THREAD

**Issue by Sly777** [facebook/react#13716]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It gives an error on build when installing React packages from NPM. But the problem is that doesn't give any error on Yarn. Error raises on *mac* and *linux*. I couldn't test in on *windows*. I installed `cjs` and `scheduler` packages for fixing this but it didn't help.

p.s.: It was working smoothly on `react 16.5.0`. With new experimental schedule, It's started to give an error. We are not using this experimental feature.

Error:
```
ERROR in ./node_modules/react-dom/cjs/react-dom.production.min.js
Module not found: Error: Can't resolve 'schedule' in '/Users/x/Project/x/node_modules/react-dom/cjs'
 @ ./node_modules/react-dom/cjs/react-dom.production.min.js 13:67-86
 @ ./node_modules/react-dom/index.js
 @ ./src/client/index.js
```

Steps:
- `rm -rf node_modules && npm i`
- build with webpack
- - It will give error
- `rm -rf node_modules && yarn`
- build with webpack
- - Build is success

I can also share my webpack setup but I think it's not related that.

**What is the expected behavior?**
It should work on npm and yarn.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- React : 16.5.2
- React-dom : 16.5.2
- Node.js : 8.11.4
- NPM : 5.6.0
- Yarn : 1.9.4

Working version:
- React : 16.5.0
- React-dom : 16.5.0
- Node.js : 8.11.4
- NPM : 5.6.0
- Yarn : 1.9.4

**Comment by gaearon** [comment]
Please provide a full project. This might be a bug in your package manager or build tool or build setup. But it's hard to guess without actually reproducing it.
