### ISSUE TITLE
Why is the word disable mentioned 391 in the source code. Very ableist 

### ISSUE THREAD

**Issue by slammerhammer** [facebook/react#13711]
I don't like discrimination, you don't like discrimination. So why are we using disable in the code. It is discriminating against disabled people and a violation of the COC. Everyone should be treated equally not discriminated for some term that someone decided to make up. It's time to use a new term rather than disable

**Comment by M-BoloDyebambewe** [comment]
I agree. True shame that such a pretty project has such ugly words in it. Please replace disabled with differently_abled

**Comment by M-BoloDyebambewe** [comment]
Possibly modify the language to make it so that enabled and d*sabled both perform the same task, but in different ways. Could this be done?

**Comment by micnic** [comment]
Is this trolling or what? The term of `disable` is a common verb used as an opposite for `enable`, and everywhere you encounter `disabled` it is used as an adjective to mark that it is not `enabled`. This is a common term used in lots of standards and frameworks. This is not discrimination, this is common sense.

P.S. I looked in the activity history of these 2 accounts, and they seems to "attack" more open source projects on different topics about discrimination. Invalid issue.

**Comment by gaearon** [comment]
Trolling, flaming, baiting, brigading, or other attention-stealing behavior is not welcome in this repository and will get you banned.
