### ISSUE TITLE
react-dom-test-utils.production.min.js not working from npm

### ISSUE THREAD

**Issue by Kurounin** [facebook/react#13714]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
react-dom-test-utils.production.min.js published in npm package differs from the one in [release](https://github.com/facebook/react/releases/download/v16.5.2/react-dom-test-utils.production.min.js)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
When trying to use 'react-dom/test-utils' from npm package in Production mode it throws the error "TypeError: Cannot read property '0' of undefined", related to `O=N[0]` on Line 20, col 172.
**What is the expected behavior?**
No error thrown.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.5.0, 16.5.1, 16.5.2

**Comment by gaearon** [comment]
Provide a reproducing project please.

**Comment by threepointone** [comment]
Closing this, happy to reopen if there's more information and a reproducing example.
