### ISSUE TITLE
Feature Request: PureComponent's children comparison; compare the Component instance instead of Element instance which always returns false.

### ISSUE THREAD

**Issue by maulerjan** [facebook/react#13717]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Consider a Root component:
```
export default class Root extends React.PureComponent {
  constructor {
    ...
  }

  render() {
    return {
      <Wrapper> // PureComponent
        <Child color={this.state.color}/>
      </Wrapper>
    }
  }
}
``` 
Every time we update the Root component's state, the Wrapper component re-renders regardless of whether we updated `color` state property or something else entirely. That is because the `<Child/>` component gets a new Element instance (although it's pointing to the same old Component instance). 

The Wrapper's shouldComponentUpdate (provided by PureComponent functionality) compares the Element instance (which is always false).

**What is the expected behavior?**
The Wrapper's shouldComponentUpdate (provided by PureComponent functionality) compares the Component instance (which can be true or false).

The PureComponent's behavior doesn't necessarily have to be changed, instead some solution (even some helper function or argument) to use within custom `shouldComponentUpdate` would be really a great feature.

An example:
```
shouldComponentUpdate(nextProps, nextState) {
  const childrenProps = React.Children.getProps(this.props.children) // a new React's helper
  const nextChildrenProps = React.Children.getProps(nextProps.children)
  const childrenComp = React.Children.getComponent(this.props.children) // a new React's helper
  const nextChildrenComp = React.Children.getComponent(nextProps.children)

  // ... compare the variables
}
```
I realise this couldn't work as the children can be an array etc. It would require a bunch of more stuff to be considered, but I think we need some kind of solution to the problem.

Ultimately, the PureComponent could be doing all of the Components (not Elements) comparison under the hood somehow.

There's currently no way of achieving this sort of performance optimization. We either have to cache the `<Child/>` for a price of losing the reactivity (`props`), or we have to accept the fact that there will be unnecessary rendering involved further down the tree.

I'm aware there had been a discussion on the subject but no solution provided. I'd like to know if there is any way this feature could be implemented in React in the future.

Thanks!

**Comment by Karenott53** [comment]
I wish I had a live tutor, I just don’t understand

**Comment by gaearon** [comment]
This is the same problem as https://github.com/facebook/react/issues/7412 so I’ll close in favor of that one.

**Comment by maulerjan** [comment]
Didn't see that one (I searched a lot, I swear). Sorry for confusion and thanks for pointing that out.
