### ISSUE TITLE
Context or not context?

### ISSUE THREAD

**Issue by tensorzuev** [facebook/react#13723]
Hello,
I have a list with items. And I can edit item on a panel that opens above list. 
Also I can edit this item in new tab with SSR.
I use Redux, and I have "isomorphic" code.
Panel for item editing is very difficult, and I have composition of several controls. 
And now I have a task: edit several items simultaneously in one "window".

React has legacy context: https://reactjs.org/docs/legacy-context.html#how-to-use-context
ItemEditPanel receives data from Redux and puts it in Context. Then I can edit two items simultaneously.
But Context is deprecated. How can this be done without using Context and props proxy?

**Comment by gaearon** [comment]
Context is not deprecated. Only the old, unsupported API is.

The new context API lets you do everything the old one could do, and is supported. 

https://reactjs.org/docs/context.html

In general we use issue tracker for bug reports. For questions please see https://reactjs.org/community/support.html.

**Comment by tensorzuev** [comment]
But it isn't true... New context and old context have difference pattern

![old ctx](https://user-images.githubusercontent.com/42337033/46058912-a04c1b00-c165-11e8-893f-f509beb8d260.png)

![new ctx](https://user-images.githubusercontent.com/42337033/46059064-57e12d00-c166-11e8-8b84-aebe3de7c357.png)

And.... How I can use unsupported API?..

**Comment by gaearon** [comment]
Sorry, I don’t understand without an example I can run. Both old and new context propagate down the tree in the same way.

**Comment by tensorzuev** [comment]
Oh, yes..
It's my mistake. I looked at source code of new "Context" and I thought that it will be work only in synchronous mode.
"enableSuspense"=true and try Context...
You recreate all providers for all async branch.
It can be interesting, because application can't has a lot of Context objects.
Thank you
