### ISSUE TITLE
official tutorial mistake

### ISSUE THREAD

**Issue by xpzzgh** [facebook/react#13722]
url: [地址](https://reactjs.org/tutorial/tutorial.html#making-an-interactive-component)
Official tutorial has a mistake at "Completing the Game-->Lifting State Up".
Here is the code snippet:
`class Square extends React.Component {
  render() {
    return (
      <button
        className="square"
        onClick={() => this.props.onClick()}
      >
        
{this.props.value}
      </button>
    );
  }
}`
This will cause error "Maximum update depth exceeded" because of 'onClick' with a brace.

**Comment by gaearon** [comment]
I don’t see the mistake. Can you show a failing fiddle?
