### ISSUE TITLE
Controlled component not receiving state when rendered from a variable 

### ISSUE THREAD

**Issue by Codebreaker101** [facebook/react#13730]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

When I create a controlled input element, store it in a variable and then render it it will not update the input value according to the state value

**What is the expected behavior?**
For it to update. 

Demo: https://codesandbox.io/s/q8zl5p9x5q

Not sure if this is a bug or my lack of understanding.

**Comment by MunifTanjim** [comment]
Doesn't seem like a bug.

Anything inside the `constructor()` is only called once. So, `this.formSchema` and `this.state.formSchema` is stuck with the initial state value `""`.

**Comment by aweary** [comment]
@MunifTanjim is exactly right, the inputs that aren't working are what we call "constant elements". They aren't updated when the component renders, so their props never change. This is expected behavior.
