### ISSUE TITLE
Error: Expected subtree parent to be a mounted class component

### ISSUE THREAD

**Issue by kbalus** [facebook/react#13743]
I've no idea about this error occured in all version prod and develop
Whats is wrong ?
Official React page says "Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue."
![image](https://user-images.githubusercontent.com/7715744/46152037-759ab900-c270-11e8-89e5-e0aaeff4473c.png)

Many thanks!

**Comment by alejandronanez** [comment]
Hello @kbalus, do you have any steps to reproduce this issue (maybe a codesandbox link)? What version of React are you using? Also, what dependencies you have installed?

**Comment by sag1v** [comment]
What version of `google-map-react` are you using, latest? 
You should see [this issue](https://github.com/tomchentw/react-google-maps/issues/640) on their repo

**Comment by gaearon** [comment]
We'd need a reproducing example for this.
