### ISSUE TITLE
Event handlers do not fire if added via React.cloneElement

### ISSUE THREAD

**Issue by liolick** [facebook/react#13769]
**Do you want to request a *feature* or report a *bug*?**
Probably, bug. But don't sure.

**What is the current behavior?**
onKeyDown and onKeyDownCapture events handlers do not fire, when they added via React.cloneElement.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Here is pseudo-example for demonstration of our case:
```
// AppView.tsx file
export class AppView
    extends ContainerView  // ContainerView extends React.Component
{
    public render()
    {
        let view = super.render();

        return React.cloneElement(view, {onKeyDownCapture: this.onKeyDownCapture});
    }

    private onKeyDownCapture = (e: React.KeyboardEvent) =>
    {
        // This handler does not fire
    }
}
```
This code works fine:
```
// AppView.tsx file
export class AppView
    extends ContainerView
{
    public render()
    {
        let view = super.render();

        return <div onKeyDownCapture={this.onKeyDownCapture}>{view}</div>;
    }

    private onKeyDownCapture = (e: React.KeyboardEvent) =>
    {
        // This handler fires
    }
}
```
**What is the expected behavior?**
Handler fires.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.4.0.
I do not know if this work in previous versions of React.

**Comment by BloodMoonShard** [comment]
Please spent u time and write correct example, where this bug happen. Why u use Container? Why not HOC (High Order Component)?

I check it on the onClick and this is work.

**Comment by liolick** [comment]
I'm very sorry.
Unable to reproduce it in isolated environment.
Our project is huge, so it is not possible to extract exact code.
