### ISSUE TITLE
Error line number in Error Boundary

### ISSUE THREAD

**Issue by dehghani-mehdi** [facebook/react#13790]
Hi,

Maybe this is a question not feature req, but I found nothing about that.

**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Error Boundary shows error message and stack trace.

**What is the expected behavior?**
Error Boundary should show error line number (same as browser console, using source map)

**Comment by aweary** [comment]
@dehghani-mehdi this is already possible, check out https://reactjs.org/docs/error-boundaries.html#component-stack-traces

The [transform-react-jsx-source](https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source) Babel plugin will give you this information in your stack traces.

Hope that helps!

**Comment by dehghani-mehdi** [comment]
@aweary it doesn't help sadly (or I could not find any way to work with plugin, I do as plugin description says but nothing changes), I already see that info in browser console, what I'm looking for is having that info via `error`/`errorInfo` params:

```
componentDidCatch(error, errorInfo) {}
```

**Comment by nzayatz14** [comment]
@dehghani-mehdi The error with complete stack trace (including line numbers) should be in the error object itself

```
const MyFallbackComponent = ({ componentStack, error }) => {
    const { message, stack } = error; // <- this is the stack you want
    return <div>stack</div>
};
```

The component stack is just to see where the component lays in the hierarchy

**Comment by dehghani-mehdi** [comment]
@nzayatz14 see https://github.com/facebook/react/issues/13938
