### ISSUE TITLE
batch.commit() doesn't empty existing container

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#13796]
If you have

```
<div id="main">hello</div>
```

then run

```
const root = ReactDOM.unstable_createRoot($('main'));
const batch = root.createBatch();
batch.render('goodbye');
await batch;
batch.commit();
```

then the div should contain "goodbye" but instead contains "hellogoodbye". Looks like we are forgetting to empty the container.

Same issue exists with `unstable_createRoot(...).render(...)`.

**Comment by gaearon** [comment]
`createBatch` is no more.
