### ISSUE TITLE
react proxy does not work

### ISSUE THREAD

**Issue by USMAN378** [facebook/react#13795]
Hi i am facing issue with react proxy .. Actually  i am accessing files from other port 
The proxy works for "/" but not for any other url like  "/currentpost/images/"
my  proxy code is 
```
  "proxy": {
    "/api/*": {
      "target": "http://localhost:5000"
    },
    "/currentPost/images/*" : {
      "target" : "http://localhost:5000"
    },
    "/images/*": {
      "target": "http://localhost:5000"
    }
```
    
  }

![prob1](https://user-images.githubusercontent.com/35171108/46656677-0dc96400-cbc8-11e8-9394-a0e9ad176cf4.PNG)

and my proxy code in package js file is
ps://user-images.githubusercontent.com/35171108/46656606-dfe41f80-cbc7-11e8-9d1c-9d1713814ca8.PNG)

**Comment by gaearon** [comment]
1. You probably meant https://github.com/facebook/create-react-app, not React repo
2. If you're using `react-scripts@2`, https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#object-proxy-configuration-is-superseded-by-srcsetupproxyjs
