### ISSUE TITLE
Proposal for porting React's Mixin APIs to a generic primitive

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#1380]
Currently React's mixins allow multiple mixins to implement the same method in multiple mixin, if it's a whitelist. We would like to decouple the mixin system from React and therefore we need a way to solve it without a whitelist.

The idea is to have every mixin call super() to allow predictable chaining.

The mixin(...mixins) function would essentially create a new prototype chain with each mixin's set of functions stacked on top of each other in order. An object is treated as a prototype. A function is treated as a class/constructor and gets all their static methods + their prototype merged.

``` javascript
var A = {

  componentDidMount() {
    super(); // This will end up calling an empty function, placed by mixin()
    console.log('A');
  }

};

class B {

  static getQueries() {
    super(); // This will end up calling an empty function, placed by mixin()
    console.log('B')
  }

  componentDidMount() {
    console.log('B');
    super();
  }

}

class C extends mixin(A, B) {

  static getQueries() {
    super();
    console.log('C');
  }

  componentDidMount() {
    super();
    console.log('C');
  }

}

C.getQueries(); // B, C
new C().componentDidMount(); // B, A, C
```

We can issue warnings when the mixin function is called and some of the overlapping methods are missing super calls.

Solvable but confusing/complex issues:

``` javascript
class C extends mixin(A, B) {

  // This state intializer overrides the state initializer in the base class.
  // The current React class system merges the two. This is also not valid ES6
  // since we don't have property initializers yet. This is based on the
  // TypeScript syntax.
  state = {
    b: true
  }

  componentDidMount() {
    // You forgot to put a super call here but there's no warning since
    // the mixin logic happens before this class is created.
  }

}
```

To be clear, mixins is an escape hatch to work around reusability limitations in the system. It's not idiomatic React.

Idiomatic React reusable code should primarily be implemented in terms of composition and not inheritance.

**Comment by jbrantly** [comment]
It seems that ES6 classes are being actively worked on and I presume targeted for v0.13 (can anyone confirm that?). If so, what is the current plan for ES6 classes and mixins in that release? I'm assuming React Core will not ship with any magic to somehow handle mixins with `createElement` like it does today with `createClass`, so any mixin functionality will need to be handled outside of React. Will something along the lines of the OP be shipped?

**Comment by sebmarkbage** [comment]
Yes, they are scheduled for 0.13. In the 0.13 release, we will not ship this mixin helper. It requires `toMethod()` support which is unusual in current ES6 transpilers. You will need to roll your own or use `createClass`.

**Comment by rtorr** [comment]
> This proposal is about providing feature parity with current React classes. *It's not an encouraged pattern.*

@sebmarkbage is this still the case? React.createClass is still the preferred way of doing things in 0.13? I don't think http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html really illustrates that opinion, and maybe that is why there is a lot of confusion.

**Comment by jsfb** [comment]
@rtorr We are moving towards native ES6 classes as the "modern" way of doing things.  That said, many people (including a large portion of Facebook) will continue to use React.createClass for some time, so both options will be supported in the near term.

**Comment by alexeygolev** [comment]
Was wondering if subclassing can solve it for now. A 'mixin' can extend ```React.Component``` and all the components we need to use this 'mixin' could just extend it. Seems to be working. Am I missing something? (besides the fact that the mixins already created are not compatible with this pattern)

**Comment by brigand** [comment]
toMethod is now officially not in ES6 (planned for ES7).

**Comment by sebmarkbage** [comment]
Even without toMethod it could be built like this: https://gist.github.com/sebmarkbage/fac0830dbb13ccbff596

However, I think that making composition easier is a higher priority than making arbitrary mixins work.

**Comment by gsklee** [comment]
I've played with @sebmarkbage's example above a bit but don't really like the fact that super calls become mandatory in each augmented method. Also played around with @brigand's `react-mixin` which looks to be one of the more reasonable solutions for now, but I don't like the syntax.

What's the status quo of mixins/traits in ES7? Would it be better to fill the syntax using something like `sweet.js`? For example Scala has something like this: `class A extends B with X with Y with Z`.

**Comment by donaldpipowitch** [comment]
Scala syntax looks good *_*

**Comment by gsklee** [comment]
@sebmarkbage I think I've come up with a feasible solution:

**traits.js**
```javascript
import traits from 'es6-traits';
import React from 'react/addons';

export const {on, using} = traits();

export const autobind = {
  [Symbol.toStringTag]: 'autobind',

  constructor() {
    Object.getOwnPropertyNames(this.constructor.prototype)
          .filter(x => x.startsWith('on'))
          .map(x => this[x] = this[x].bind(this));
  }
};

export const purerender = Object.assign(React.addons.PureRenderMixin, {
  [Symbol.toStringTag]: 'purerender'
});
```

**some-component.js**
```javascript
import React from 'react';
import {on, using, autobind, purerender} from './traits';

export default class SomeComponent extends (on (React.Component), using (autobind, purerender)) {
  ...
}
```

The syntax is a bit longer than the proposed `mixins(React.Component, X, Y, Z)` but is more concise IMHO. I actually went through numerous API ideas before finally settling on this one.

The package is available at [es6-traits](https://github.com/gsklee/es6-traits) and is based on @brigand's excellent `smart-mixin`. Since `smart-mixin` is offering a composition conflict resolution mechanism I'm calling this traits instead of mixins.

**Comment by brigand** [comment]
Those syntax hacks are impressive :-)

I like it, but looking over the source I think the second example needs to be this because `traits()` can't be shared by multiple classes.

```js
import React from 'react';
import traits from 'es6-traits';
import {autobind, purerender} from './traits';
const {on, using} = traits();

export default class SomeComponent extends (on (React.Component), using (autobind, purerender)) {
  ...
}
```

I also like the use of constructor over componentWillMount in the traits.  It feels much more pure.

**Comment by gsklee** [comment]
@brigand It can be shared, you can also specify different resolution rulesets for different classes like this:

```javascript
export const {on, using} = traits({
  Cat: {
    sleep: 'ONCE',
    play: 'MANY'
  },
  Dog: {
    sleep: 'ONCE',
    play: 'ONCE'
  }
});
```

I need to find some time to come up with a document and add browser support so it can be played with inside JSBin etc. but while we are at it, any suggestion to the API and how the lib should work are welcomed.

**Comment by brigand** [comment]
I followed up in https://github.com/gsklee/es6-traits/pull/2.

**Comment by mlrawlings** [comment]
It would seem to me that unless React is going to move to an event or hook based system for the lifecycle methods, those methods need to be handled specifically.  You can't just mix them into the prototype, which means whatever the solution it's going to be React specific.  I like something like the following where it is clear that I am extending a React.Component with PureRenderMixin mixed in.

```javascript
// user's code
class MyComponent extends React.Component(PureRenderMixin) {
   //...
}

// ReactComponent.js
function ReactComponent(props, context) {
  if(!(this instanceof ReactComponent)) {
    if(arguments.length) return createMixedComponent(arguments)
    return ReactComponent
  }
  this.props = props;
  this.context = context;
}

```

**Comment by BerkeleyTrue** [comment]
@mlrawlings That looks great!

**Comment by jjoos** [comment]
@mlrawlings :+1:

**Comment by brigand** [comment]
Here's an implementation of @mlrawlings's syntax http://jsbin.com/tofidoxucu/2/edit?js,console,output

It does look much cleaner.  If I switch to es6 classes, I'll probably write it like that, and have a small transform to move it out of there.  Early errors aren't worth giving up imo, but luckily we don't need to compromise :-)

**Comment by gaearon** [comment]
In my opinion [higher order components](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750) and [the new `observe` hook in 0.14](https://github.com/facebook/react/issues/3398) solve almost all use cases I had for mixins.

**Comment by gsklee** [comment]
@gaearon Looks promising, but a little bit too React-specific. @mlrawlings's example is the most ideal but it'd require manually wrapping all classes with a function; I wonder if there is any possible way to abstract that part out into a generic lib?

**Comment by chicoxyzzy** [comment]
there will be TC39 proposal for annotations https://github.com/Microsoft/TypeScript/issues/1557#issuecomment-77709527 can we use something like that to abstract mixins?

**Comment by chicoxyzzy** [comment]
https://github.com/wycats/javascript-decorators/blob/master/README.md

**Comment by brigand** [comment]
@chicoxyzzy it doesn't really add any value, other than being able to declare the mixins before the class in code.  Annotations don't *do* anything, so you need something else to act on them.  

With classes, either directly on the class via `Class.prototype` or on instances via `this.constructor.annotate`, `Object.getPrototypeOf(this).constructor.annotate`, etc.

```js
// used for an instanceof check, because other annotations may be used
class ReactMixin {
    constructor(mixin){ this.mixin = mixin }
}

@ReactMixin(PureRenderMixin)
class Foo extends React.Component {
   ...
}
applyMixins(Foo);

function applyMixins(Class){
    if (Class.annotate) {
       Class.annotate.forEach(maybeMixin => {

           // apply the mixin behavior for each mixin annotation
           if (maybeMixin instanceof ReactMixin) 
               reactMixin(Class.prototype, maybeMixin.mixin);
       })
    }
}
```

As @gaearon pointed out, you can expect alternatives to mixins in the coming months... maybe before we get annotation support in babel.

**Comment by donaldpipowitch** [comment]
I think Babel already has annotation support behind a flag.

**Comment by gsklee** [comment]
If we'd like to see mixins/traits in ECMAScript then they deserve to be included as independent features. Annotation is simply not for this purpose. I believe there are actually a few mixins/traits related proposals that was postponed to ES7 as a last minute decision by TC39 since they wanna stick with the "maximally minimal" concept.

**Comment by andreypopp** [comment]
@brigand I think the idea is to add decorators, not annotations to ES7. Class decorators are code so it's possible to have `withMixins` decorator which works like:
```
@withMixins(PureRenderMixin)
class Foo extends React.Component {
   ...
}
```

I also think that decorator syntax will be useful for higher order components, so instead of:
```
class Foo extends React.Component {
  ...
}
Foo = Enhance(Foo)
```
we can write:
```
@Enhance
class Foo extends React.Component {
  ...
}
```

**Comment by rstuven** [comment]
@brigand @andreypopp Here's a description of decorators that includes API and desugaring: https://github.com/wycats/javascript-decorators

This is already implemented in Babel 5+ and TypeScript 1.5

**Comment by jedwards1211** [comment]
Will we ever have automatic autobinding again?

**Comment by spicyj** [comment]
@jedwards1211 Unlikely. We'll probably recommend using a ES-future syntax feature when it lands: https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding.

**Comment by jedwards1211** [comment]
Hopefully the come up with something nice for that.  More often than not, whenever I've passed functions around, I've wished they were autobound, even outside of React code.

I understand why React devs don't "think you're in the business of designing a class system," but when you're going to start using an entire view framework, it's not that much cognitive burden to learn its class system.  Certainly less cognitive burden for me than keeping track of all this churn.

**Comment by gaearon** [comment]
I guess this ship has sailed.
