### ISSUE TITLE
 script executed when tag name contains capital character

### ISSUE THREAD

**Issue by zenany** [facebook/react#13825]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The code is: 
```
class App extends React.Component {
  render() {
    return (
      <div>
        <sCript>alert('Hi');</sCript>
        <script>alert('script 2: this should not execute');</script>
      </div>
    );
  }
}
```
the script in ` <sCript>alert('Hi');</sCript>` executed.
![s_ 2018-10-11 15 56 00](https://user-images.githubusercontent.com/2378632/46789074-3a1ee500-cd6e-11e8-8b0f-1ab172857f7c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Demo in codepen: https://codepen.io/zenany/pen/rqmPYq

**What is the expected behavior?**

`<sCript>alert('Hi');</sCript>` should not processed as code, this may cause security risk.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

versions:
```
  "dependencies": {
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
  },
```
browser: firefox, chrome

**Comment by bvaughn** [comment]
> `<sCript>alert('Hi');</sCript>` should not processed as code, this may cause security risk.

Why do you say this?

```js
document.createElement('sCript') // <script></script>
```

Also this HTML (without React):
```html
<html>
<body>
<div>
<sCript>alert('foo');</sCript>
<script>alert('bar');</script>
</div>
</body>
</html>
```

Will show both "foo" and "bar" alerts.

HTML is mostly case insensitive, except for certain attributes.

**Comment by bvaughn** [comment]
This issue looks like it's been filed as the result of a misunderstanding, so I'm closing it. Please correct me if I'm missing something though and we can re-open it! 😄

**Comment by zenany** [comment]
> This issue looks like it's been filed as the result of a misunderstanding, so I'm closing it. Please correct me if I'm missing something though and we can re-open it! 😄

Hi, @bvaughn . Can you evaluate the case i described up is a bug or feature?

**Comment by gaearon** [comment]
See https://github.com/facebook/react/pull/19018.
