### ISSUE TITLE
Getting error EUNSUPPORTEDPROTOCOL

### ISSUE THREAD

**Issue by ossdev07** [facebook/react#13824]
While trying to install using npm install, i was getting below error:
**npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:./scripts/eslint-rules/

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-11T06_52_49_537Z-debug.log**

On debugging understood that dependency "eslint-plugin-react-internal": "link:./scripts/eslint-rules/" in package.json is giving error. Currently there is no version of eslint-plugin-react-internal package. 

Can we run all cases even after removing this dependency from package.json.

Thanks in advance.

**Comment by vinay72** [comment]
-1
down vote

I suggest you to use node 8.9.4 recommended version and install your package with sudo permission.

`sudo npm install'

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by peachen** [comment]
change 'link' to 'file' can solve this problem for me ( in mac Hige Sierra)
"eslint-plugin-react-internal": "file:./scripts/eslint-rules/"

The reference that I learn from is in:
https://stackoverflow.com/questions/14381898/local-dependency-in-package-json/14387210#14387210

**Comment by ossdev07** [comment]
@peachen It worked for me. Thank you so much

**Comment by yujiangshui** [comment]
You can also choose to use `yarn` install the packages, it supports this.

**Comment by kannandvsha** [comment]
> 
> 
> change 'link' to 'file' can solve this problem for me ( in mac Hige Sierra)
> "eslint-plugin-react-internal": "file:./scripts/eslint-rules/"
> 
> The reference that I learn from is in:
> https://stackoverflow.com/questions/14381898/local-dependency-in-package-json/14387210#14387210

this works in windows env.  thanks

**Comment by jawadzahoor72** [comment]
Please check devdependencies, if you are using any link local package or proxy please remove it. or fix it according to your node and react version, 
Then
delete node_modules and incase of yarn, delete yarn.lock
clear cache 
`npm cache clear --force`
and then again install npm install
resolved my issue
