### ISSUE TITLE
RFC Add doc tips "shouldComponentUpdate: false" for having non-managed nodes?

### ISSUE THREAD

**Issue by syranide** [facebook/react#1382]
https://github.com/facebook/react/issues/1377#issuecomment-39942649

Seems like something a bunch of people would find useful, I personally wasn't aware that it was a possible solution.

**Comment by jimfb** [comment]
We've had some discussions internally about this, and the consensus is that people should assume that `shouldComponentUpdate` is a hint that the reconciler is permitted to ignore the hint.

Related to https://github.com/facebook/react/issues/2517#issuecomment-169838716
