### ISSUE TITLE
Context Provider Attributes

### ISSUE THREAD

**Issue by yairEO** [facebook/react#13826]
**Do you want to request a *feature* or report a *bug*?**
**Feature**

After reading about [context API ](https://reactjs.org/docs/context.html) I've tried to use it in a somewhat more complex why than it's shown in the docs, and the docs weren't clear enough about what can be passed, and if `value` is the **only** attribute that can be used.

My immediate try after reading the docs was thinking that _ANY_ attribute that I put inside the `<ContextProvider>` will be passed to the consumer. I saw that it's not the case. 

## Example:

````
const {Provider, Consumer} = React.createContext({});

<ContextProvider value={foo.value} action={this.updateValue}>
        <Child />
</ContextProvider>
````

I have a deep deep child (inside `<Child>`) where I would like to pass some value and some callback.
`action` is `undefined` in the _Consumer_:

````
<ContextConsumer>
        {(value, action) => (
        <button onClick={()=> action(value + 1)}>Click to INC: {value}</button>
        )}
</ContextConsumer>
````

I don't understand why can't React pass all the attributes to the consumer, as-is. 
why only `value` was chosen as the only attribute to be passed?

**Comment by TrySound** [comment]
Performance reasons. With your solution react should do shallow compare of props. Current solution requires only single reference comparing.

```js
const Component = class extends React.Component {
  state = {
    value: 0,
    update: value => this.setState({ value })
  };

  render() {
    return (
      <Provider value={this.state}>
        {this.props.children}
      </Provider>
    );
  }
}
```

**Comment by yairEO** [comment]
Yes eventually I resorted to dumping everything into the `value` attribute, as an Object, but it just feels wrong, since not everything is semantically considered a "value".

**Comment by yairEO** [comment]
I still think doing `value.value` in the *consumer* isn't ideal

**Comment by TrySound** [comment]
@yairEO Call it `context` instead of `value` or however you want. For example I have hoisted `viewport` value to sync a few maps.

**Comment by yairEO** [comment]
@TrySound - Hi Bogan, just want to give a context to my question:

https://stackoverflow.com/a/52758326/104380

I was playing with `Context` + `Redux`. 
You think this solution makes sense?

**Comment by TrySound** [comment]
@yairEO Sure. However I prefer mixing context with powerplug like this
https://codesandbox.io/s/1vrpwnp72j
