### ISSUE TITLE
`onChange` warning creates false positives

### ISSUE THREAD

**Issue by selbekk** [facebook/react#13835]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you set the `value` of an `input` field, you get a warning while development:

> Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.

However, this is not always true. If your `onChange`-listener is further up the component tree, the warning is no longer true.

The same goes for checkboxes.

Here's a reproduction: https://codesandbox.io/s/6wjl48mjn (open the console tab to see the warning)

Here's the relevant piece of React source code: https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/shared/ReactControlledValuePropTypes.js#L41-L46

**What is the expected behavior?**

If possible, I'd love React to not show this warning if this is the issue. Or at the very least change the wording. The warning is great when you've actually forgotten to add an onChange handler, so we probably shouldn't remove it all together.

Right now I'm passing a no-op onChange listener to silence the warning (yeah it's dev only, but I'm dev-ing all the time, and warnings are annoying), which probably isn't a great solution either.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All versions I've ever tried the last three years

----

I'd love to work on this, but I'm not sure how to solve it.

**Comment by i-like-robots** [comment]
This issue has been reported against a component I maintain but I am reluctant to make any code changes to avoid a warning. As reported in the original issue the input element is a child of the component which defines the event listener.

https://github.com/i-like-robots/react-tags/issues/135

**Comment by gaearon** [comment]
Please see https://github.com/facebook/react/issues/3070#issuecomment-73311114.

**Comment by selbekk** [comment]
Aha - yeah I see how that's gonna be a hassle. :) Thanks for getting back to me!
