### ISSUE TITLE
I think the first post is a bit misleading.

### ISSUE THREAD

**Issue by tnkdwp** [facebook/react#13831]
There's no problem with null as a value. The problem is React treats this as a flag to make an input uncontrolled. That turned out to be confusing.

So we added a warning to discourage existing users from passing null. This lets us safely change the behavior for future version to treat null as an empty string. We haven't done this yet but that's the plan, if I understand it right.

Maybe now is a good time to do this. Do you mind raising a new issue to discuss?

_Originally posted by @gaearon in https://github.com/facebook/react/issues/5013#issuecomment-340898727_

**Comment by chasestarr** [comment]
@tnkdwp follow the conversation on this topic here: https://github.com/facebook/react/issues/11417
