### ISSUE TITLE
props lost after refresh

### ISSUE THREAD

**Issue by KerimHelal** [facebook/react#13830]
Hello,
Currently i have a function that sets the states from the props, it works just fine but after refresh the state is empty because the props are lost and the state is empty because it enters the else of the if condition.

```javascript
constructor(props) {
    super(props);
    this.state = {  
      address: '',
      previousAddress: ''
    };
  }

componentDidMount(){
    this.loadvalues();
}

loadvalues = () => {
  console.log(this.props.user);
  console.log(this.props.user.hasOwnProperty('name'));
  this.setState({
    email: this.props.user.emails[0].address,
    name: this.props.user && this.props.user.hasOwnProperty('name') ? this.props.user.name : '',
    mobileNumber: this.props.user && this.props.user.hasOwnProperty('mobileNumber') ? this.props.user.mobileNumber : '',
  });
}
```
console log before refresh
[https://prnt.sc/l4z67d](url)
console log after refresh
[http://prntscr.com/l4z6x4](url)

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
