### ISSUE TITLE
Forward ref bug with latest React version

### ISSUE THREAD

**Issue by sebastiankemp** [facebook/react#13837]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When a error boundary components catches error and we do a setState, the refs in forwardRef break. I have attached an image where this error occurs at the bottom of this post to assist.

I struggled to find the root of the problem and we have an internal task open to try and fix the code if possible and make a PR for React. I could not find the same code as what shows in screenshot. I am probably not understanding the code right.

**What is the expected behavior?**

ForwardRef should work with our components like expected.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

After checking our package.json, it seems we are using a alpha version of React. The people on my team updated to this version of React last week due to a bug fix that it has. I'm not sure how stable this version is but there seems to be an issue with forwardRef API. It does not happen on the previous version. Maybe this bug has been fixed in the next version?

I already report this bug on React discord channel and someone told me to open issue here. Thank you for your help.

https://github.com/facebook/react/blob/6d5d250bef88115ceceb906d0cab1d60ea996d7b/packages/react-reconciler/src/ReactFiberBeginWork.js#L212

**Comment by gaearon** [comment]
Can you try updating to the latest alpha? The one you're using has some known issues.
The latest is `react@16.6.0-alpha.8af6728` and `react-dom@16.6.0-alpha.8af6728`.

**Comment by sebastiankemp** [comment]
Thank you for the guidance. I found the bug and the latest release seems to fix it. I do wonder why you removed my screenshot though. I thought nothing of it to begin with but others on my team pointed out that maybe the release we used was not meant to be public. I feel there is some dishonest behaviour here which goes against being open and transparent in open source. This upsets me a lot because I know now after reading the code of the version we used that many mechanics are due to be changed and this will likely reproduce the same problem.

**Comment by sebastiankemp** [comment]
![bug](https://user-images.githubusercontent.com/44088303/47191354-adac8d80-d33e-11e8-9200-4925f67a6198.png)

Here is my original screenshot that the author did not like us seeing. Please do not remove this time author. Thank you.

**Comment by gaearon** [comment]
I didn’t mind the screenshot. :-) Your post said that you couldn’t find the source code so I edited it to point to the relevant code.

**Comment by sebastiankemp** [comment]
The code link did not link to representative code and to us that looks suspicious. We also checked out other alpha version at that version and found many other inconsistencies with the api. There are lots of new apis here that scare much of my team. Are these apis to be released soon?

**Comment by gaearon** [comment]
I’d really appreciate if you could share a reproducing example you were having troubles with. Canary releases are generally unstable and may contain bugs or experimental codepaths. Maybe this particular bug got fixed but it’s hard to say without a reproducing case. Your screenshot doesn’t tell me much about the bug but if you create a minimal example that would be very helpful. Thanks!

**Comment by gaearon** [comment]
For example https://codesandbox.io/ is a great way to create reproduction cases. You can specify the exact alpha you were using in the package.json.

**Comment by sebastiankemp** [comment]
You did not answer the question we ask and this confuses us. The bug is now fixed and thank you kindly for your help. We ask other questions relating to api. This is important to us as we try new api and find more bugs but do not know where to ask.

**Comment by sebastiankemp** [comment]
Thank you for help. I close this issue now. Please ignore my above messages about api. Kindly.
