### ISSUE TITLE
StrictMode causing runtime behavior to change

### ISSUE THREAD

**Issue by uriklar** [facebook/react#13844]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When wrapping my app with StrictMode I see different behavior in react-google-maps library then when not wrapped with StrictMode

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/jv61orz64y (details written inside)

**What is the expected behavior?**

App should behave the same with/without StrictMode

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome 16.5.2 (Also saw this in 16.4.0)

**Comment by AlexGalays** [comment]
That's the whole point of strict mode.

**Comment by urikphytech** [comment]
I see what you're saying, but i opened this issue following this tweet: https://twitter.com/sebmarkbage/status/1050963417110966273?s=21

Maybe there was  misunderstanding that this is a dev build of react (does codesandbox also use the dev build? Because it's reproducing there too)

**Comment by gaearon** [comment]
CodeSandbox will use a dev build, yes.

**Comment by gaearon** [comment]
So StrictMode is probably pointing out a legitimate issue in that library.

**Comment by uriklar** [comment]
I see 🤦‍♂️ Thanks for the clarification, I'll investigate the issue in react-google-maps
