### ISSUE TITLE
[npm:create-react-class] Forwarding refs

### ISSUE THREAD

**Issue by pjebs** [facebook/react#13845]
https://reactjs.org/docs/react-without-es6.html doesn't seem to explain how to use forwarding refs:

https://reactjs.org/docs/forwarding-refs.html

Does the render function in the class have to have the new props argument?

**Comment by TrySound** [comment]
Forwarding refs is not affected by es5.
```js
function var Component = React.forwardRef(function (props, ref) {
  return React.createElement('div', { ref }, props.children)
});
```

**Comment by siddhant1** [comment]
Should I attach a pr of the docs are still unclear?

**Comment by pjebs** [comment]
would i need to merge the rest of props fields with ref instead of just `{ ref }`?

**Comment by TrySound** [comment]
No, the purpose is forwarding a special prop which is not passed to props regulary.

Did you read docs you mentioned? What exactly is not clear from them?

**Comment by pjebs** [comment]
The example passes in (as does your example) a single `props.children`. Shouldn't it be `props.children...` or we use help of `React.Children`?

**Comment by gaearon** [comment]
Please use the issue tracker for reporting bugs.
https://reactjs.org/community/support.html
