### ISSUE TITLE
'Set' is undefined in Version 16.5.2 using recommended polyfills

### ISSUE THREAD

**Issue by hohenp** [facebook/react#13840]
Hi, I have updated to React 16.5.2 and have different error logs in console:
![image](https://user-images.githubusercontent.com/29328026/46874218-ea592000-ce38-11e8-874e-6170ba81d3b7.png)

I am using IE11 in IE10 Document mode,
I have checked the article: https://reactjs.org/docs/javascript-environment-requirements.html 

My entry Point:
![image](https://user-images.githubusercontent.com/29328026/46874281-183e6480-ce39-11e8-902e-64ceb5e3ead1.png)

I am including the scripts in the following order:
<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>

<script src="/src/kanban.min.js"></script>

I had the solution running in Version 15.6.6 without These Errors and had included the same polyfills there. The Problem is only in IE11 with Document Mode 10. In Chrome everything runs fine.

Thanks for your help,
Pascal

**Comment by gaearon** [comment]
Please provide a complete project reproducing this.

**Comment by hohenp** [comment]
Here the simple Project causing the same console issues...
[issue.zip](https://github.com/facebook/react/files/2473456/issue.zip)

Include via:
<div id="issue-entry"></div>

<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
<script src="http://localhost:4321/dist/issue.js"></script> 

Thanks a lot!

**Comment by threepointone** [comment]
The zip you submitted only had a js file, and it's hard to know what happened without the full context. Please provide a full project that we can run locally, either as a git repo, or a codesandbox link. 

My *guess* is that you should add the polyfills before react/react-dom in the html, but I'm not sure and cannot comment further without more information.

Closing this, happy to reopen if you can provide a reproducing example.
