### ISSUE TITLE
Bug inline styles flex value

### ISSUE THREAD

**Issue by OZZlE** [facebook/react#13859]
**Steps to Reproduce:**
https://jsfiddle.net/reactjs/69z2wepo/

    class Hello extends React.Component {
      render() {
        return <div style={{ flex: '1 0 0' }}>Hello</div>;
      }
    }
    ReactDOM.render(
      <Hello />,
      document.getElementById('container')
    );

**Expected Result:**
`<div style="flex: 1 0 0;">Hello</div>`

**Actual Result:**
`<div style="flex: 1 0 0px;">Hello</div>`

Notes:
Why change `0` to `0px` ?? I'm not sure IE11 works with `0` the same way as `0px`.. Also why not change the second digit then also? 0px and 0 is the same also, so the suffixing of px there is just a waste and can cause potential bugs. 

https://stackoverflow.com/a/22883146/846348

**Comment by OZZlE** [comment]
IE11 actually seems to be only happy with just `flex: 1;` but this is also changed to `flex: 1 0 0px`....

**Comment by OZZlE** [comment]
@taleymirza Thank you for the explanation! However this is IE we are talking about.. It doesn't really follow specs, but there are usually hacks that make it work, one being `flex: 1;`

Chrome resolves `flex: 1` to `flex: 1 0 0%'. I tried using this instead but IE11 doesn't understand it, neither `flex: 1 0 0px`.

IE11's flexbox implementation is very buggy.. 

Also I think making assumptions and changing the code like this based on web standards isn't the best practise because of problems like this.

A workaround is to put the style inside a stylesheet loaded by react, then it's not changed and works in IE11.

**Comment by OZZlE** [comment]
I wish I didn't need to support IE11 but unfortunately we still have customers using it :<

**Comment by gaearon** [comment]
I verified all React does is set `node.style.flex = '1 0 0'`. React doesn't append any `px` suffix so you're dealing with some browser issue here.

**Comment by OZZlE** [comment]
@gaearon it should put `node.style.flex = '1'` because that is what I wrote.. why does it need to mess up IE11?? 

I have to use a stylesheet to get `flex: 1;` because inline is modified from what I actually wrote!!!
