### ISSUE TITLE
findByType() from react-test-renderer should search the `props.children` components in addition to the pure `children` components

### ISSUE THREAD

**Issue by uladkasach** [facebook/react#13851]
**Do you want to request a *feature* or report a *bug*?**
This is a feature request. 

**What is the current behavior?**
Currently the `findByType()` method does not explore the `props.children` array that is passed to components. For some components, such as the `ScrollView` in `react-native`, this means that the method does not find all elements that are eventually rendered by type. 

**What is the expected behavior?**
The expected behavior is to have `findByType()` navigate through `props.children` of each element to see if any of the `children` are of the type being searched for. E.g., 

components:
```
<ScrollView>
    <View />
    <View />
</ScrollView>
```

`findAllByType(View).length` should return `2`, but currently returns `0` because the `children` of the above `ScrollView` component is empty: the `props.children` of that component has the components of interest.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is currently the case with 
```
    "react-test-renderer": "^16.5.2"
    "react": "16.3.1",
```

**Please let me know if I can clarify anything.**

**Comment by gaearon** [comment]
>The expected behavior is to have findByType() navigate through props.children of each element to see if any of the children are of the type being searched for. 

I don't think this is right. There is no guarantee that these children would get rendered, so this can break expectations. We wouldn't also be able to descend "into" them (because they weren't rendered) so that would also be confusing.

If you're having issues specifically with `ScrollView`, I suggest to mock it in a test so that it works like `(props) => <View>{props.children}</View>` or similar.

**Comment by uladkasach** [comment]
@gaearon that makes sense. thank you for the explanation.

Could you give an example of how we can mock _only_ the ScrollView and not the rest of the `react-native` imports? I think that would be a great solution - i'm just not sure how to implement it.

**Comment by uladkasach** [comment]
For Context:

I have tried both this approach:
```

import * as ReactNative from 'react-native';
(ReactNative as any).ScrollView = (props: any) => (<ReactNative.View> {props.children} </ReactNative.View>);
```

and this approach:
```
jest.mock('react-native', () => ({
  ...(jest as any).requireActual('react-native'),
  ScrollView: (props: any) => (<View>{props.children}</View>),
}));
```

and they are both throwing an error:
```
Invariant Violation: Navigator is deprecated and has been removed from this package. It can now be installed and imported from `react-native-deprecated-custom-components` instead of `react-native`. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html

```

It seems like either of these approaches would were were it not for an error being triggered "on import" of the `Navigator` object - that is somehow being "imported" in both `import * as ReactNative from 'react-native'` and `jest.requireActual('react-native')`.

**Comment by uladkasach** [comment]
I was able to find a working solution due to this answer: https://stackoverflow.com/a/44932905/3068233 
```
import { View } from 'react-native';
jest.mock('ScrollView', () => {
  return (props: any) => (<View>{props.children}</View>);
});
```

It appears that jest does something special for `react-native` exports to enable us to mock them with just the name of the component. 

@gaearon Do you know if this is this the recommended solution or if there is a better alternative?
