### ISSUE TITLE
Need a react component function to check nextprops just before re-render to stop a redirecting action in react component. 

### ISSUE THREAD

**Issue by deepa-a** [facebook/react#13867]
**Do you want to request a *feature* or report a *bug*?**
Need help with an edge case. Not sure what is the good practice.

**What is the current behavior?**
Using react + redux + redux saga for my application.

I have a 'Home' screen with a search bar, where I search for a subscriber. The action is dispatched and the saga does the API call and the requirement is to redirect to the 'Subscriber' screen with the result. I read the good practice is not to redirect from the sagas/reducers and redirect from the component using `<Redirect>` of react-router-dom. 
So In my 'Home' component, I check for the props and if I have the result, I redirect to the 'Subscriber' results page.
The issue is Redux stores the state and every time I navigate to 'Home' it gets redirected because the store persist the results.

```jsx
class Home extends React.Component {
  render() {
    const { actions, subscriberDetails } = this.props;
    if (subscriberDetails) {
      return <Redirect to="/subscriber-details" />;
    }
    return (
      <div>
        <h1>Search subscriber</h1>
        <input type="text" name="Subscriber" />
        <button onClick={actions.getSubscriber}>Get Subscriber</button>
      </div>
    );
  }
}

Home.propTypes = {
  actions: PropTypes.object.isRequired,
  subscriberDetails: PropTypes.object
};

const mapStateToProps = (state, ownprops) => {
  return {
    subscriberDetails: state.subscriber.details
  };
};

const mapDispatchToProps = dispatch => ({
  actions: bindActionCreators(subscriberActions, dispatch)
});

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Home);
```

**What is the expected behavior?**

The redirect should happen only when I search for the a 'Subscriber' and not every time I navigate to the Home screen (results are persisted).

To solve this I need a function which is called just before the component re renders on update to check the 'props' in my 'Home' component, where I can see if the props has the result and redirects to the required screen. The 'componentWillRecieveProps' function has made unsafe. 
I use shouldComponentUpdate function to solve this issue, where I check for nextprops and set a variable to redirect only when the component update. Which works fine. 

```js
shouldComponentUpdate(nextprops, nextstate){
        this.redir = nextprops.subscriberDetails? <Redirect to='/subscriber-details'/> : null;
        return true;
}
```

I just need to confirm is there any other way to solve this issue or can I use `shouldComponentUpdate` function for this?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Windows
`"react": "^16.5.2"`
 `"react-dom": "^16.5.2"`
`"react-router-dom": "^4.3.1"`
`"redux": "^4.0.0"`
`"redux-saga": "^0.16.2"`

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
