### ISSUE TITLE
use @types/react-dom --> in build react-dom.development.js

### ISSUE THREAD

**Issue by Lieblein** [facebook/react#13893]
When I use `@types/react-dom`, i have react-dom.development.js in build (production mode).

With `@types/react-dom`
![screenshot 1](https://user-images.githubusercontent.com/29818420/47217588-eb023100-d3b9-11e8-9d8f-a20d11a19e54.png)

Without `@types/react-dom`
![screenshot 2](https://user-images.githubusercontent.com/29818420/47217594-f0f81200-d3b9-11e8-941a-ad3ea1952785.png)

Some my dependencies:
```
"devDependencies": {
    "@types/react": "^16.4.14",
    "@types/react-dom": "^16.0.9",
    "@types/react-redux": "^6.0.9",
    "@types/react-router-dom": "^4.3.1",
    "typescript": "^3.0.3",
    "webpack": "^4.20.2"
  },
  "dependencies": {
    "react": "^16.5.1",
    "react-dom": "^16.5.1",
    "react-redux": "^5.0.1",
    "react-router-dom": "^4.0.0"
  },
```

**Comment by aweary** [comment]
The React team doesn't maintain the the TypeScript definitions, but this sounds like this is potentially an issue with your build setup. I recommend checking out our [community support resources](https://facebook.github.io/react/community/support.html).

If that doesn't work, try opening an issue on the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped), as that appears to be the source of `@types/react-*`

Thanks!

**Comment by phil-lgr** [comment]
@aweary sorry to highjack this issue, but is there any sign that the React team will add official support for TypeScript, even without using .ts files you can add types through comments e.g. like webpack has done: https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L30 thank you !
