### ISSUE TITLE
React-Test-Renderer bringing back key error but from itself not from my code.

### ISSUE THREAD

**Issue by The-Code-Monkey** [facebook/react#13890]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

My test passes fine then I get this print in the console

![screen shot 2018-10-19 at 08 17 46](https://user-images.githubusercontent.com/31218527/47203283-ace41d80-d377-11e8-8bd9-e800329f2dff.png)

**What is the expected behavior?**

react-test-renderer shouldn't be throwing errors like that.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
@The-Code-Monkey can you please share the code you're testing here? It's likely that one of the components you're testing is missing a required key.

**Comment by The-Code-Monkey** [comment]
Non of the components that are being tested have a map or foreach it's literally just a form with two fields and a button connected to a store

**Comment by The-Code-Monkey** [comment]
And I've only actually made a snapshot of that component

**Comment by aweary** [comment]
@The-Code-Monkey can you please share the test then? We can't help if we can't reproduce the problem.

**Comment by The-Code-Monkey** [comment]
I will do when I get on my Mac tomorrow
