### ISSUE TITLE
React throws error when input's attribute "id" defined as "nodeName"

### ISSUE THREAD

**Issue by Ky6uk** [facebook/react#13894]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I name attribute `id` of `<input />` element as `nodeName` react throws an error into console when I try to focus/blur the input:

```
Uncaught TypeError: elem.nodeName.toLowerCase is not a function
    at shouldUseChangeEvent
    at Object.extractEvents
    at extractEvents
    at runExtractedEventsInBatch
    at handleTopLevel
    at batchedUpdates$1
    at batchedUpdates
    at dispatchEvent
```

![screenshot 2018-10-19 at 17 59 21](https://user-images.githubusercontent.com/46930/47226348-f872e780-d3c8-11e8-9ec4-c589a14937f6.png)

**Example**
https://jsfiddle.net/Luktwrdm/1372/

**Comment by aweary** [comment]
Hey @Ky6uk, this is a known issue. See https://github.com/facebook/react/issues/6284. Thanks!

**Comment by Ky6uk** [comment]
Ohh, third birthday of the issue soon.
