### ISSUE TITLE
There is a dependency loop?

### ISSUE THREAD

**Issue by zhaosiwen1949** [facebook/react#13892]
Today,I found a dependency loop in React v16.5.2:

packages/shared/ReactSharedInternals.js ==require==> packages/react/index.js ==require==> packages/react/src/React.js ==require==> packages/react/src/ReactChildren.js ==require==> packages/shared/warning.js ==require==> packages/shared/ReactSharedInternals.js

I don't know it's designed in such way? or just a bug? 
Could anybody help me answer the question? Thanks

**Comment by aweary** [comment]
@zhaosiwen1949 did you run into any unexpected behavior because of this?

**Comment by flowkraD** [comment]
I couldn't find anything breaking on the surface but again it all comes down to what this refers to: `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` in [ReactSharedInternals.js](https://github.com/facebook/react/blob/master/packages/shared/ReactSharedInternals.js) and how it connects back to the entire loop but if `ReactDebugCurrentFrame` in [warning.js](https://github.com/facebook/react/blob/master/packages/shared/warning.js) isn't dependent on the components constituting the chain, then we don't have a loop at our hand (^_^)

**Comment by aweary** [comment]
Loop or not, if it's not causing any issues it's not a concern 😄 since there doesn't seem to be a problem here I'm going to close this out.
