### ISSUE TITLE
Support headless chrome logging from integration tests

### ISSUE THREAD

**Issue by justin808** [facebook/react#13917]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Logging of console errors in headless chrome lacks the ability to provide a full message due to reliance on formatting from console.error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
I'd like a way to get a proper error message without hacking the code.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.5.2, not sure about prior versions

With a hack to concatenate the strings rather than use the template:

```js
    // warningWithoutStack$1(false, 'Text content did not match. Server: "%s" Client: "%s"', normalizedServerText, normalizedClientText);
    warningWithoutStack$1(false, 'Text content did not match. Server: "' + normalizedServerText + "' Client: '" + normalizedClientText + "'");
```

then I get a reasonable message:

```
       webpack-internal:///417 508:18 "Warning: Text content did not match. Server: \"ZZZZZZZZZZZZZZZZZZZ' Client: 'Say hello to:'"
```

rather than just the template:

```
       webpack-internal:///417 514:18 "Warning: Text content did not match. Server: \"%s\" Client: \"%s\""
```

While this may be an issue only with Capybara and headless chrome, it is nevertheless a very real issue when troubleshooting why integration tests fail due to console errors.

Here is my code for the logging of console.error. Note, the template is in `entry.message`.

```rb
RSpec.configure do |config|
  config.after(:each, :js) do |example|
    next unless [:selenium_chrome, :selenium_chrome_headless].include?(Capybara.current_driver)
    # As of 2018-10-21, traping errors does not work for firefox

    log_only_list = %w[DEBUG INFO]
    if example.metadata[:ignore_js_errors]
      log_only_list += %w[WARNING SEVERE ERROR]
    end

    errors = []

    page.driver.browser.manage.logs.get(:browser).each do |entry|
      next if entry.message.match?(/Download the React DevTools for a better development experience/)

      log_only_list.include?(entry.level) ? puts(entry.message) : errors << entry.message
    end

    page.driver.browser.manage.logs.get(:driver).each do |entry|
      log_only_list.include?(entry.level) ? puts(entry.message) : errors << entry.message
    end

    raise("Java Script Error(s) on the page:\n\n" + errors.join("\n")) if errors.present?
  end
end
```

Could we have a mode where warningWithoutStack can concat the args for testing and just append to the message?

```
      let argIndex = 0;
      const message =
        'Warning: ' + format.replace(/%s/g, () => args[argIndex++]);
```

Maybe we can convert the call stack to a string as well?

Thoughts? I could create a PR for this if you think it's useful.

**Comment by gaearon** [comment]
If this is blocking you, you can override `console.error` with a version that does formatting inline.


```js
const realConsoleError = console.error;
console.error = function(fomat, ...args) {
  let argIndex = 0;
  const message = 'Warning: ' + format.replace(/%s/g, () => args[argIndex++]);
  return realConsoleError.call(console, message);
}
```

 Ideally it would be nice if you reported this upstream to the integration tools and if they fixed it.
