### ISSUE TITLE
Error line number in Error Boundary

### ISSUE THREAD

**Issue by dehghani-mehdi** [facebook/react#13938]
Hey,

As I can not reopen issue #13790, I opened this.

If you don't like to fix/add my request, simply say `won't fox`, but don't close the issue with simple/not related answer, as @aweary did. React is pro library, you are pro, so act like pros.

Thanks.

**Comment by gaearon** [comment]
It's not clear what you're asking. Is `error.stack` not what you want?

**Comment by dehghani-mehdi** [comment]
@gaearon The `error.stack` is good, but the problem is all details doesn't point to right file(s).

For example:

```js
componentDidCatch(error, info) {
    this.setState({ hasError: true });

    console.log("-----------------------------");
    console.log(error, info);
    console.log("-----------------------------");
}
```

I got this:
![untitled](https://user-images.githubusercontent.com/9152330/47898328-ab901600-de8a-11e8-8f6c-476ed0e94314.png)

As you can see all details/line numbers point to bundled file (_in my case `react.modules.js`_).

Browser's console point to right file (and line number):
![2](https://user-images.githubusercontent.com/9152330/47898474-4557c300-de8b-11e8-8716-bdeb35a5d9d3.png)

All I'm looking for is I can see `home.jsx 12:14` into browser UI, like great `react-error-overlay`.

P.S: I tired to use `react-error-overlay` outside of `create-react-app` and I did it. but I think adding this to `Error Boundary` is great.

**Comment by 7654098** [comment]
+1

**Comment by dehghani-mehdi** [comment]
@gaearon any update? still you need more info?

**Comment by stefems** [comment]
+1

**Comment by duartealexf** [comment]
+1

**Comment by nzayatz14** [comment]
@dehghani-mehdi this information is only available when providing a sourcemap to the browser via your compiler (I assume webpack). You will not be able to access this information on a production site, as no sourcemap is provided when compiling for production.

See this:
https://what-problem-does-it-solve.com/webpack/sourcemaps.html

**Comment by dehghani-mehdi** [comment]
I'll provided requested info, is there anything else you want me to do?!

**Comment by dehghani-mehdi** [comment]
.

**Comment by aliazizi** [comment]
@gaearon what inforamtion you need?
for example here full value of error info
```
\n    in a\n    in withRouter(a)\n    in t\n    in t\n    in a\n    in Suspense\n    in div\n    in div\n    in div\n    in div\n    in div\n    in div\n    in main\n    in a\n    in t\n    in t\n    in un
```

there isn't any line and column number in it

**Comment by aliazizi** [comment]
Ok I found out I can get error line and info from `error.stack` I hope this help someone

**Comment by dehghani-mehdi** [comment]
.

**Comment by dehghani-mehdi** [comment]
.

**Comment by gaearon** [comment]
I think this is something you need to report to the browser vendors. React doesn't do anything with the error objects so the information there is what the browser provides. We can't get more information from the browser.

**Comment by dehghani-mehdi** [comment]
@gaearon I don't understand, you can do it in `react-error-overlay`, but you can not do it in `error boundary`, why?

**Comment by gaearon** [comment]
This is what the browser gives us in the browser object. We can’t add information to it somehow. So this is not a React issue.

**Comment by dehghani-mehdi** [comment]
How do you show this information in react-error-overlay?

**Comment by dehghani-mehdi** [comment]
> Do you want this in development or in production?

development
