### ISSUE TITLE
Cannot be used new contextType API in constructor?

### ISSUE THREAD

**Issue by maisumakun** [facebook/react#13944]
**Do you want to request a *feature* or report a *bug*?** *feature* 

**What is the current behavior?** Using `Component.contextType`, `this.context` keeps `null` in class component's constructor.

**What is the expected behavior?** 

-  `this.context` can be obtained in constructor
- if implementing of the feature is inappropriate, write in documentations that `this.context` cannot be used in constructor.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** React 16.6 (older React doesn't have `Component.contextType`) in Chrome 70 (Windows 7)

**Comment by sebmarkbage** [comment]
Hm. Yea. This is a bug I think. It should probably be allowed.

**Comment by gaearon** [comment]
Want to send a failing unit test and/or fix?

**Comment by aweary** [comment]
@maisumakun how are you calling `super` in the `constructor`? If you pass `context` to `super` it's accessible as expected.

https://codesandbox.io/s/l47jw5ryyz

```
class App extends React.Component {
  static contextType = Context
  constructor(props, context) {
    super(props, context)
    console.log(this.context)
  }
```

This seems consistent with `this.props`. If you don't pass `props` to `super` you cannot access `this.props` in the constructor.

**Comment by maisumakun** [comment]
@aweary Oh, thanks! 

`constructor(props, context)` reminded me a code for legacy Context API, but necessary for `contextType` too. (this should be documented anywhere)

**Comment by gaearon** [comment]
Please feel free to send a documentation PR to section about using `contextType`.
https://github.com/reactjs/rfcs

**Comment by OdenigboGodfrey** [comment]
super(props, context) is deprecated now also :sigh

**Comment by molimat** [comment]
but actually almost the whole class component concept is deprecated. lol

**Comment by chbdetta** [comment]
> but actually almost the whole class component concept is deprecated. lol

Simply untrue. There is no plan deprecating class component.

**Comment by chbdetta** [comment]
According to:
https://github.dev/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L77-L79

component class with a constructor signature `constructor(props: MyProps, context: MyContext)` is no longer valid `JSXElementConstructor` . So this usage is now prohibited by TS

Any workaround?

**Comment by joshuakb2** [comment]
You can access `this.context` from `UNSAFE_componentWillMount`, but you'll get warnings in strict mode.

This issue was closed previously because `super(props, context)` was still available, but now it's deprecated. What's the way forward?

**Comment by kubijo** [comment]
> You can access `this.context` from `UNSAFE_componentWillMount`, but you'll get warnings in strict mode.
> 
> This issue was closed previously because `super(props, context)` was still available, but now it's deprecated. What's the way forward?

Bumping this with the same reason ... if there is now new way of achieving this, this should not be deprecated.
