### ISSUE TITLE
React.memo() does not work well with styled-components

### ISSUE THREAD

**Issue by ng-hai** [facebook/react#13945]
**Do you want to request a *feature* or report a *bug*?**
I think it's a bug

**What is the current behavior?**
When wrapping a function that returns `styled-components` with `React.memo()`, it could not be composed with other `styled-components`.

I get the error
```
Cannot create styled-component for component: [object Object].
```

[![Edit React.memo()](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vnr9vzpmn0)

**What is the expected behavior?**
The returned `React.memo()` components could be wrapped by `styled-components` or vice versa.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```json
{
    "gatsby": "^2.0.28",
    "react": "^16.6.0",
    "react-datepicker": "^1.7.0",
    "react-dom": "^16.6.0",
    "react-helmet": "^5.2.0",
    "styled-components": "^4.0.2"
}
```

**Comment by lustoykov** [comment]
I think this is something styled-components should fix, but for now, you could replace

```
export default styled(ToBeMemo)``;
```

with 

```js
export default styled(ToBeMemo.type)``;
```

to make it work

<a href="https://codesandbox.io/s/22x49293n">
  <img alt="Edit React.memo()" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>
