### ISSUE TITLE
Import from one Component not working when cyclic references.

### ISSUE THREAD

**Issue by adrianpaz** [facebook/react#13943]
Is this behaviour is bug?

I have two components:

```
import PropTypes from "prop-types";
import React from "react";
import { TEST_FIELD } from "./OtherTestComponent";

const TestComponent = props => {
  return <div>TestComponent: {props.testProps}</div>;
};

TestComponent.propTypes = {
  testProps: PropTypes.string
};

TestComponent.defaultProps = {
  testProps: TEST_FIELD
};

export { TestComponent };
```

AND:

```
import React from "react";
/** Uncomment this line to see not working default props values */
// import { TestComponent } from "./TestComponent";

export const TEST_FIELD = "tested-value";

const OtherTestComponent = () => {
  return <div>OtherTestComponent</div>;
};
export { OtherTestComponent };
```

When in `OtherTestComponent` we add import to `TestComponent` the field TEST_FIELD in `TestComponent` will be undefined in defaultProps. Why? Is it bug or normal behaviour?

Sandbox: https://codesandbox.io/s/5xn76610y4

**Comment by BloodMoonShard** [comment]
import { TestComponent } from "./TestComponent";

import { TEST_FIELD } from "./OtherTestComponent";

U think this make sense, u do import b2b, i think this is really bad practice.

**Comment by BloodMoonShard** [comment]
If this is bug then problem not in the React, this problem in the Babel

**Comment by adrianpaz** [comment]
OK, so I close it here.
