### ISSUE TITLE
Suspense fallback always computed

### ISSUE THREAD

**Issue by eloytoro** [facebook/react#13948]
**What is the current behavior?**
Suspense's fallback property takes a react element `<Suspense fallback={<div>Loading...</div>}`, in this case the div element will always be computed as a vdom element, and so will its children. it could instead take a function that is lazily evaluated if the fallback is needed.

**What is the expected behavior?**
`<Suspense fallback={() => <div>Loading...</div>}`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6^

**Comment by TrySound** [comment]
@eloytoro Here `Loading` content is also lazy evaluated. It was in react from the beginning.
```js
<Suspense fallback={<Loading />}>
```

**Comment by eloytoro** [comment]
So in this case one must be careful regarding the amount of inline rendering done in the prop.
Sounds fair to me

**Comment by OliverJAsh** [comment]
Could we get this changed so that the `fallback` prop accepts a function as well as, or instead of, an element? Small performance improvement but probably worth it?

**Comment by gaearon** [comment]
It doesn’t have any meaningful performance difference. If you’re concerned about complex children (which again isn’t likely to affect performance except extreme scenarios) you can extract them all in a separate component.

**Comment by gaearon** [comment]
It doesn’t have any meaningful performance difference. If you’re concerned about complex children (which again isn’t likely to affect performance except extreme scenarios) you can extract them all in a separate component.
