### ISSUE TITLE
Ability to set "key" attribute programmatically in fully uncontrolled component itself

### ISSUE THREAD

**Issue by ford04** [facebook/react#13942]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently, if I want a component to be a [fully uncontrolled component](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key), a `key` attribute is assigned from the outer/parent component in JSX. Then, `Inner` will be recreated every time, the key changes.

```
class Outer extends Component {
  ...

  render() {
    return <Inner key={this.props.user.id} />
  }
}
```

**What is the expected behavior?**
Why should `Outer` have to know, that the inner comp (here `Emailnput`) is a fully controlled component and what is designated as the `key` attribute?
IMO it would make sense, if `Inner` could decide that itself to have better encapsulation.

Is it possible, that `Inner` could programmatically set its key attribute itself? Maybe as a static property similar to the way implemented with `defaultProps`?
```
export interface Props<Props> {
    user: User;
}


class Inner extends Component {
  ...
  static key = user.id;

  render() { ... }
}
```

Thanks in advance

**Comment by gaearon** [comment]
Can you submit as an RFC instead? Thanks.
https://github.com/reactjs/rfcs
