### ISSUE TITLE
Suspense and lazy are both missing in the API docs

### ISSUE THREAD

**Issue by tarjei** [facebook/react#13946]
I might be blind, but here goes...
**Do you want to request a *feature* or report a *bug*?**
I think this is a documentation bug :)

**What is the current behavior?**
Docs are missing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
React.Suspense and lazy should be documented in the API docs.

PS: Suspense is referenced in the code-splitting document but not in the general API referece or subsections of the API referrence sections.

**Comment by gaearon** [comment]
Please send a PR? Or raise an issue in the docs repo: https://github.com/reactjs/reactjs.org.
Thanks.
