### ISSUE TITLE
npm start failed The react-scripts package provided by Create React App requires a dependency: "babel-loader": "8.0.4" following steps doesnt work 

### ISSUE THREAD

**Issue by suprim12** [facebook/react#13951]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by hawkins** [comment]
this sounds like an issue for [facebook/create-react-app](https://github.com/facebook/create-react-app) instead

but, have you tried `rm -rf node_modules && npm install`?

**Comment by emjgreen** [comment]
I also have this problem, has anyone found a fix?

**Comment by edgesoft** [comment]
@suprim12 @emjgreen Make an issue at [https://github.com/facebook/create-react-app](https://github.com/facebook/create-react-app) as @hawkins suggest and you will certainly get help there.

**Comment by gaearon** [comment]
npm probably had some kind of outage (or you might be behind a proxy). Try again.

**Comment by bestwestern** [comment]
I have this today - and tried both with npm and yarn... going to the CRA repo to open issue

**Comment by nickofthyme** [comment]
This seems to have been a bug in `react-scripts@2.1.3` from what I can tell. Upgrading to `react-scripts@^2.1.4` works just fine. 👍 

```
my-react-app@0.1.0 /Users/path/to/my-react-app
└─┬ react-scripts@2.1.3
  ├── babel-loader@8.0.4
  └─┬ babel-preset-react-app@7.0.1
    └── babel-loader@8.0.5
```

**Comment by ramomex1** [comment]
pff i dopnt understand it was yesterday 7/18/2019 working, today i have same error.
start: `react-scripts start`npm ERR! Exit status 1. something related to "babel-loader": "8.0.5"

i have done evrything, clean cache, remove node_modules, npm install again. even re install node.js

these were my dependencies.
```
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  }.

```
Any help?

**Comment by ramomex1** [comment]
> pff i dont understand it was yesterday 7/18/2019 working, today i have same error.
> start: `react-scripts start`npm ERR! Exit status 1. something related to "babel-loader": "8.0.5"
> 
> i have done everything, clean cache, remove node_modules, npm install again. even re install node.js
> 
> these were my dependencies.
> 
> ```
>   "dependencies": {
>     "react": "^16.8.6",
>     "react-dom": "^16.8.6",
>     "react-scripts": "3.0.1"
>   }.
> ```
> 
> Any help?

somewhere in the top folders i had installed another version of babel-loader, i have uninstalled it and its fine now.. not sure how that happend i have only installed redux

**Comment by zhnedyalkow** [comment]
Hi,

As our colleague above explained, the issue is when you have installed somehow the package outside of the project. Because of how node works, it checks for same package at the top level of hierarchy.

Br,
Zhi
