### ISSUE TITLE
Shorthand for prop={false}

### ISSUE THREAD

**Issue by xehpuk** [facebook/react#13967]
**Feature Request**

```jsx
<Foo bar/>
```
is the same as
```jsx
<Foo bar={true}/>
```

It would be nice to have something like
```jsx
<Foo !bar/>
```
meaning
```jsx
<Foo bar={false}/>
```

**Comment by aweary** [comment]
It's unlikely that we'd do this. In either case this would be a change to JSX, which would require a change to the specification. Please see https://github.com/facebook/jsx
