### ISSUE TITLE
Changing number of calls to `useState` in a component results in an error

### ISSUE THREAD

**Issue by collin** [facebook/react#13976]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Changing the number of calls to `useState` between renders kills the application.

https://codesandbox.io/s/5zrr8x9nyx
In the sandbox, click the first `+` button to increment `countA` above 5.
Then click the `-` button to decrement `countA` below5

The application will crash (white screen), console has limited information.

(inlining the source for reference)

```js
import React, { useState } from "react";
import ReactDOM from "react-dom";

function Counter() {
  const [countA, setCountA] = useState(0);
  if (countA > 5) {
    const dynamicState = useState();
  }
  const [countB, setCountB] = useState(countA + 1);
  return (
    <>
      <div>
        Count A: {countA}
        <button onClick={() => setCountA(countA + 1)}>+</button>
        <button onClick={() => setCountA(countA - 1)}>-</button>
      </div>
      <div>
        Count B: {countB}
        <button onClick={() => setCountB(countB + 1)}>+</button>
        <button onClick={() => setCountB(countB - 1)}>-</button>
      </div>
    </>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<Counter />, rootElement);
```

**What is the expected behavior?**
I'm not really sure. I guess at least a warning explaining why or that placing calls to `useState` in a conditional isn't supported.

**Comment by aweary** [comment]
This is expected behavior for hooks. You can't call them conditionally. See the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).

>I'm not really sure. I guess at least a warning explaining why or that placing calls to useState in a conditional isn't supported.

We have a linter plugin for this: https://www.npmjs.com/package/eslint-plugin-react-hooks

**Comment by collin** [comment]
I suppose I meant more like the warnings for missing a key in a map or switching between controlled/uncontrolled inputs across renders.
