### ISSUE TITLE
[React Hooks] Webpack transpiled component throws invariant during SSR

### ISSUE THREAD

**Issue by pheuter** [facebook/react#13972]
**What is the current behavior?**
```
UnhandledPromiseRejectionWarning: Invariant Violation: Hooks can only be called inside the body of a function component.
        |     at invariant (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react/cjs/react.development.js?:125:15)
        |     at resolveDispatcher (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react/cjs/react.development.js?:1450:28)
        |     at useState (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react/cjs/react.development.js?:1473:20)
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.7.0-alpha.0

---

This is what the component looks like after it's transpiled by Webpack:

```js
function HookedComponent() {
    var _a = Object(react__WEBPACK_IMPORTED_MODULE_1__["useState"])("Mary"), name = _a[0], setName = _a[1];
    return (react__WEBPACK_IMPORTED_MODULE_1__["createElement"]("div", null,
        react__WEBPACK_IMPORTED_MODULE_1__["createElement"]("h1", null, name),
        react__WEBPACK_IMPORTED_MODULE_1__["createElement"]("input", { value: name, onChange: function (e) { return setName(e.target.value); } })));
}
```

**Comment by hilkeheremans** [comment]
Could you paste your original (untranspiled) code here as well?

**Comment by pheuter** [comment]
```ts
function HookedComponent() {
  const [name, setName] = useState("Mary");

  return (
    <div>
      <h1>{name}</h1>
      <input value={name} onChange={e => setName(e.target.value)} />
    </div>
  );
}
```

**Comment by hilkeheremans** [comment]
Your code works fine here. You sure you are using both `react` and `react-dom` on the alpha versions? I forgot to update `react-dom` initially which resulted in some oddish errors.

**Comment by pheuter** [comment]
Both are on the alpha version. I suspect it might have something to do with how Webpack is transpiling it.

**Comment by hilkeheremans** [comment]
Maybe -- I should note I'm also running Webpack, but more indirectly using CRA 2.0 after manually upgrading the react and react-dom versions..

**Comment by pheuter** [comment]
Perhaps also worth noting on my end that this error occurs during a server-side render call from `react-dom/server/renderToString()`

**Comment by pheuter** [comment]
This is interesting because it works on the browser if I hot load the component in, but crashes the `renderToString()` call when it exists during a server-side render.

**Comment by hilkeheremans** [comment]
Well, that makes sense now... I can totally imagine that SSR support is not there yet.

**Comment by aweary** [comment]
[Hooks should work with `renderToString`](https://codesandbox.io/s/wqoo1z3w6l). @pheuter are you using Babel with Webpack? If so, what plugins are you using?

**Comment by dadamssg** [comment]
I've having this same issue but not using SSR

**Comment by aweary** [comment]
@dadamssg do you get the same error if you remove `react-hot-loader`?

**Comment by albinekb** [comment]
I got the same issue yesterday, and narrowed it down to being `react-hot-loader`

**Comment by bkniffler** [comment]
Can't say anything to SSR, but hot loader definitely doesn't work. When I replace the `export default hot(module)(App);` part of my app.js with `export default App`, the error goes away.

**Comment by pheuter** [comment]
@aweary @bkniffler Removed `react-hot-loader` from my app and still getting the same error. Is it relevant that the source code is written in TypeScript and transpiled using `ts-loader`?

**Comment by bkniffler** [comment]
Might be, I'm also using typescript, but through babel, and I'm not having issues after removing hot loader.

**Comment by pheuter** [comment]
Switched over to using babel-loader, same invariant violation thrown when doing `renderToString`. 

Should note that the same exact app works fine when I avoid rendering the function component on the server and only render it on the client.

**Comment by pheuter** [comment]
Looks like it had something to do with rendering the app tree during [getDataFromTree](https://github.com/apollographql/react-apollo/blob/master/src/getDataFromTree.ts):

```ts
await getDataFromTree(<App />);
```

**Comment by theKashey** [comment]
I am afraid, but hook would break any custom react-tree traversal:
- apollo
- react-hot-loader
- loadable-components
- async-component
- and more and more and more.

**Comment by edorivai** [comment]
@pheuter Having the exact same issue. Everything works on client, breaks on server. Using Typescript, babel (after ts-loader), webpack, `react@next`, `react-dom@next`.

@theKashey Ah that would make so much sense! Would be `getDataFromTree` in our case.

**Comment by victoryancn** [comment]
https://github.com/facebook/react/issues/14022

**Comment by gaearon** [comment]
Closing in favor of https://github.com/facebook/react/issues/14022.

**Comment by nassimbenkirane** [comment]
Hi @pheuter,
Do you still have the issue ? There is a merged PR that fixes #14022 but I don't know if it was released with 16.7.0-alpha.2
I'm still having the same issue as the original one : i.e. a webpack/babel transpiled component with hooks raising the Invariant Violation when using SSR (renderToString or renderToStaticMarkup)

**Comment by pheuter** [comment]
@nassimbenkirane This issue was fixed earlier for me in a separate library that I was using, specifically [getDataFromTree](https://github.com/apollographql/react-apollo/blob/master/src/getDataFromTree.ts) from `react-apollo`

**Comment by yordis** [comment]
For us was `react-hot-loader` using CRA like setup

**Comment by google-mac** [comment]
Those using Parcel will need to update react-hot-loader.

**Comment by theKashey** [comment]
For any react-hot-loader related issues please one an issue in RHL project.
