### ISSUE TITLE
Error when using react lazy with react router

### ISSUE THREAD

**Issue by shavo007** [facebook/react#13979]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Changed from react-loadable to lazy/suspense. 

Get console error 
```
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
    in Route (created by BasicExample)
    in BasicExample (created by App)
    in div (created by App)
    in App
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://github.com/shavo007/react-boilerplate/tree/react-lazy

**What is the expected behavior?**
Dynamically import

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome
OSX
React react@16.6.0

**Comment by aweary** [comment]
See https://github.com/ReactTraining/react-router/issues/6420

**Comment by shavo007** [comment]
thanks @aweary
