### ISSUE TITLE
More helpful interaction for "React does not recognize the 'propName' prop on a DOM Element"

### ISSUE THREAD

**Issue by James-E-Adams** [facebook/react#13978]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When you pass a unknown prop to a DOM element - common when you pass `{...props}` to something that turns out to be a div/span/any other DOM element rather than a composite component - you get a warning like so:

```Warning: React does not recognize the `propName` prop on a DOM element. ....```

If the tree is pretty complicated, especially if you're using HOCs, it can be very hard to find where this prop has been passed and to which DOM element. 

**What is the expected behavior?**

We had a quick muck around with react-dom and logging the DOM element that triggers this warning allows you to see the element in the DOM and makes it much easier to work out where the prop is being accidentally passed. You can even use the react dev tools to work out exactly which line the component is defined in the code.

Simply logging the element is obviously not the most elegant way of showing the user where the mistake is, but would it be possible to do _something_ in order to make it quicker to fix mistaken prop passing like this?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All.

**Comment by James-E-Adams** [comment]
I think this also could extend to a few other errors such as
`Received 'true/false' for a non-boolean attribute 'propName'`

**Comment by gaearon** [comment]
It's not very clear to me what your exact proposal is. If you send a PR or describe it in more detail (e.g. with screenshots) I can take a look.

**Comment by James-E-Adams** [comment]
Sure thing. I didn't want to make a PR until I was vaguely sure that it would be accepted and helpful to other people. I'll get some screenshots up in the coming days.

**Comment by sztadii** [comment]
I think this problem is common, because somebody else created https://github.com/gajus/react-strict-prop-types and https://github.com/airbnb/prop-types-exact. So I think it should be added to PropTypes library by default.

**Comment by gpawlik** [comment]
Does anybody know why are those warnings displayed with `console.error` instead of `console.warn`?
