### ISSUE TITLE
PROPOSAL/Convo Starter: new 'affect' API to control how data gets passed from data containing components to presentiation children

### ISSUE THREAD

**Issue by gregorskii** [facebook/react#13971]
*Feature Request*

The new [Hooks API](https://reactjs.org/docs/hooks-intro.html)  is awesome. It had me thinking..

One of the issues I have had with React is with render prop based components that pass data to their children. Often I want to be able to control when props are "effectively complete" from a container before telling a child component to render usable data. Until the parent component determines it is complete the child component would remain in a loading state. This loading state can be set by default and updated in its own hooks / CDU / CDM as usual.

What I would propose as a possible solution to this is a modification to the render props pattern where a new API could be put in place on components to conditionally restrict them from passing props down to the child tree. This API would be similar to the new effect API but on the downstream updates. It could be part of the hooks API but have the methods be called "affects".

This API could have a similar footprint where "affects" could be skipped like "effects" can:

https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects

A second argument to the "affect" function could be an array of keys that determine if the props should be passed down through the render props to other components.

WDYT? Is this completely against the nature of how React is expected to work? I understand the pattern is that components can control the props / state / UI updates they make from the data coming INTO them, but I understand that it could be an anti-pattern to stop the components from passing data down to their children. Understandably you could control this via using setState and only passing state down to the children, but sometimes you want to both use the internal state to manage the logic of the component and also have other logic controlling prop updates to children.

The use cases for this would be mainly:

* Data Containers
* API requests
* Conditional API requests
* Combining multiple containers for code isolation into a presentational component

I understand that each of these bullet points can be solved using various different means, but the new hooks API is so well thought out, understandable, and provides a clear pattern for controlling data INTO components, it would be beneficial to have a similar pattern on data leaving components (or context providers etc).

Thanks

**Comment by aweary** [comment]
@gregorskii we have [an open RFC for Hooks](https://github.com/reactjs/rfcs/pull/68), please direct any relevant feedback or questions to that RFC.

If you have a broader proposal you'll also want to use the RFC process. Thanks!

**Comment by gregorskii** [comment]
Will link to this there, but I kinda saw it as a different proposal, albeit related.

**Comment by aweary** [comment]
@gregorskii if its a separate proposal it also belongs in the RFC repo.

**Comment by gregorskii** [comment]
Ok Ty, will add.
