### ISSUE TITLE
Stop displaying StrictMode "Warnings" as Errors

### ISSUE THREAD

**Issue by mjcampagna** [facebook/react#13973]
StrictMode throws warnings as errors, making it difficult to debug my own errors due to the amount of console.error spam. If these were logged instead as warnings -- because they are, in fact, _warnings_ -- I would be able to filter my console to more easily isolate messages relevant to my current task. 

While I would love to be able to solve these StrictMode warnings in the moment, the reality is that they are filed as Tech Debt at my company, to be resolved at a later time. And I am certain I am not the only one for whom this is the reality of the work day.

**Comment by gaearon** [comment]
Perhaps in this case you could disable StrictMode until you’re ready to address them? I’m not sure what value it’s adding if you ignore them anyway until later time.

**Comment by mjcampagna** [comment]
Thanks for the quick response. 

That was our first suggestion. Some of the team is pushing to disabling StrictMode until we can better address our tech debt, but others on the team want to keep StrictMode on for whatever reason -- possible to keep a fire lit under the tech debt. Displaying warnings as warnings would make both sides happy, and it seems odd to me regardless that warnings are logged as errors, so I thought it worth bringing up here as an issue.

**Comment by gaearon** [comment]
The downside to your suggestion is they'll get less prominent and there's less incentives to fix them (and especially keep teams from introducing regressions).

I think we won't do this but you can always override `console.error` in your code, and delegate to `console.warn` for specific message substring matches (e.g. if it contains `Strict Mode`).

Hope this helps.

**Comment by mjcampagna** [comment]
I've never tried delegation of errors, so hadn't thought of it. I'll give that a try. Thanks for the advice!
