### ISSUE TITLE
16.6 contextType + getDerivedStateFromProps

### ISSUE THREAD

**Issue by natew** [facebook/react#13970]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?**

Context not passed into getDerivedStateFromProps:

```
static getDerivedStateFromProps(props, state, context) {}
```

Just curious with the new `static contextType`, it would save a lot of nesting if I could access context now from getDerivedStateFromProps when using this pattern. I gave it a shot assuming it may work already but I get undefined from the third argument.

Just curious if there's been any discussion on this.

**Comment by davehartnoll** [comment]
I found a workaround to access context inside getDerivedStateFromProps. I'm guessing it won't work in every case (such as multiple nested providers), but it seems to work for my simple usage. I plan to use this until/if there is an officially support mechanism:

`const context = MyContext.Consumer._currentValue;`

**Comment by mfferreira** [comment]
> I found a workaround to access context inside getDerivedStateFromProps. I'm guessing it won't work in every case (such as multiple nested providers), but it seems to work for my simple usage. I plan to use this until/if there is an officially support mechanism:
> 
> `const context = MyContext.Consumer._currentValue;`

Would be nice to have official way to get the context without having to use hacks like this.

**Comment by ljharb** [comment]
Still relevant (stale bots are user hostile)

**Comment by Lexicality** [comment]
This issue is also still relevant, unless class components are being deprecated?

**Comment by ljharb** [comment]
bump

**Comment by ljharb** [comment]
bump

**Comment by gaearon** [comment]
I don't think we'll be adding new features to the class API at this point, so I think we can close this.

**Comment by ljharb** [comment]
This isn't a new feature though, it's an omission - a bug.

**Comment by gaearon** [comment]
I don't think context was ever passed to it (even legacy one), and the RFC does not include it:

https://github.com/reactjs/rfcs/blob/main/text/0006-static-lifecycle-methods.md#static-getderivedstatefrompropsnextprops-props-prevstate-state-shapestate--null

So it's an addition from that perspective.

**Comment by ljharb** [comment]
Not to gDSFP, that is true, but I believe context is available in the places that this lifecycle method was meant to replace - so by not making it available here, there remains class component patterns that can't switch to using gDSFP.

**Comment by gaearon** [comment]
I was thinking the switch would be to split a component in two and pass the context from above as a prop. Would that not work?
