### ISSUE TITLE
The Suspense feature cannot pause rendering based on what the server has rendered.

### ISSUE THREAD

**Issue by janryWang** [facebook/react#13983]
If the server has already rendered some of the data, the fallback does not need to be rendered again, just like this example.

https://codesandbox.io/s/jl0krmylv5

**Comment by janryWang** [comment]
@gaearon @acdlite

**Comment by bellam** [comment]
@janryWang Not sure if this is the right example. Looks like Suspense doesn't support SSR yet.

I'm stuck at this:

> ReactDOMServer does not yet support Suspense.
> Invariant Violation: ReactDOMServer does not yet support Suspense.
>     at invariant (/nyc/node_modules/react-dom/cjs/react-dom-server.node.development.js:58:15)

**Comment by gaearon** [comment]
Suspense isn't supported by server rendering yet. We're starting work on a new fully-featured server renderer.

**Comment by GiancarlosIO** [comment]
Oh well, now I know what "No supported" mean. It throws a error in server side 🤔 
I think ReactDomServer just ignore the suspense component.

**Comment by larafale** [comment]
> Suspense isn't supported by server rendering yet. We're starting work on a new fully-featured server renderer.

Hello @gaearon ,  I've read a lot about Suspense, which is awesome, really really want to use it :) I would like to use Suspense in a `nextjs` project (which does ssr), was wondering if it was possible yet, this thread is dated 2018, so maybe now it's possible ? is it ? thanks a lot if you reply :) have a great one !
