### ISSUE TITLE
Warn if ReactDOM.createPortal is inside a noscript or other text content tag

### ISSUE THREAD

**Issue by bloodyowl** [facebook/react#13985]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When calling `ReactDOM.createPortal` from within a `<noscript />`, nothing happens, no error is logged.

```javascript
ReactDOM.render(
  <noscript>
    {ReactDOM.createPortal("yo", modalNode)}
  </noscript>,
  appNode
);
```

**What is the expected behavior?**

Whether:
- warn that it doesn't work (it worked in the previous version)
- render the portal

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- React 16.5.0 & more recent
- Reproducible in every browser

**Repro**
https://jsfiddle.net/bloodyowl/n5u2wwjg/223296/

**Comment by bloodyowl** [comment]
probably related to this change: https://github.com/facebook/react/pull/13537

**Comment by gaearon** [comment]
Seems super niche so I'm not sure we'd be adding a warning unless somebody sends a PR. You can render `<Fragment><noscript>...</noscript>{portal}</Fragment>` as a work around.
