### ISSUE TITLE
Simple animation API

### ISSUE THREAD

**Issue by alexanderby** [facebook/react#13984]
It would be great if React could support the following API (or would allow to write an extension):

```jsx
import {animate} from 'react';
import d3 from 'd3';

function Chart(props) {
  return (
    <svg>
      <rect
        width={animate(props.width).duration(500).easing('in-out')}
        style={{
          fill: animate(props.color).interpolate(d3.interpolateRgb),
          opacity: animate().initial(1).remove(0), // animate how element disappears
        }}
      />
      <polygon points={animate(d3.polygon(props.points)).interpolate(d3.interpolate)} />
    </svg>
  );
}
```

Currently this is implemented in a simple [Malevič.js](https://github.com/alexanderby/malevic) library (`.remove()` not implemented yet). See the live [example](https://codepen.io/shutovby/pen/GYzjvj).

**Comment by qutran** [comment]
I don't think that it's possible because of platform agnostic react's targetting. Correct me if I wrong.

**Comment by edgesoft** [comment]
There are many libraries out there that solves this in various ways. Maybe some help to look at them?

For D3
[https://github.com/FormidableLabs/victory](https://github.com/FormidableLabs/victory)

Animations
[https://popmotion.io/pose/](https://popmotion.io/pose/)

**Comment by gaearon** [comment]
We'd like to leave this in userland for now since there are many good existing solutions with different tradeoffs.
