### ISSUE TITLE
Hooks feedback

### ISSUE THREAD

**Issue by tsongas** [facebook/react#13992]
Your Introducing Hooks page states "In our observation, classes are the biggest barrier to learning React." I would further state, Redux is the biggest barrier to using React. I hope hooks can help simplify state management.

**Comment by gaearon** [comment]
Please leave feedback here: https://github.com/reactjs/rfcs/pull/68

Redux isn’t a part of React so it’s not clear how it can be the barrier to “learning React”. But there is indeed a Hook that you might find useful for built-in state management. You can find it in API reference.
