### ISSUE TITLE
Make stateless components “Pure” by default in React 17

### ISSUE THREAD

**Issue by GabrielBB** [facebook/react#14000]
So, stateless function components should “always” be pure components, why isn’t this the default behavior ? It would have been great if this was implemented from the start , so people know very well the consequences and always relate “function” to “pure”. However, maybe this can get done in a new React version? If you do a major version upgrade you have to know that maybe some things will break. So this would be ok. Of course, I would also ask to remove React.memo in React 17

**Comment by GabrielBB** [comment]
@jquense remember that “always rendering” is not literally true. React does a check in the virtual dom, to see if the things your component returned changed, if they do, it does the rendering in the real dom. Pure components would not need this check, since you’re saying “I want be re-rendered if my props changed, re render no matter what. “. The question is: Is doing the props slower than checking the virtual dom ?

**Comment by bvaughn** [comment]
Hi 👋 This would be a large change. As such, it would need to go through our RFC process: https://github.com/reactjs/rfcs/

I'm going to close this issue 😄
