### ISSUE TITLE
Release/maintain TypeScript Declaration (.d.ts) for ReactJS

### ISSUE THREAD

**Issue by xiaoxiangmoe** [facebook/react#14001]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Publish declaration file in https://github.com/DefinitelyTyped/DefinitelyTyped/

**What is the expected behavior?**

Js file and declaration file are packaged together for releasing in npm

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react-16.6
react-16.7

**Comment by xiaoxiangmoe** [comment]
Will React.StatelessComponent (React.SFC) still keep the name in react-16.7?

**Comment by aweary** [comment]
We've had good results relying on DefinitelyTyped and I suspect we'll continue to recommend it for the foreseeable future. Relying on community definitions is likely better anyways, since React itself isn't written in TypeScript (so the React team doesn't use it).

**Comment by zanminkian** [comment]
7 years later, does React team consider to reopen this issue? More and more js library built-in support declaration files. It will be convenient to millions of React developers if React built-in releases declaration files.
