### ISSUE TITLE
Suspense doesn't "resolve" for subsequent times if was suspended again 

### ISSUE THREAD

**Issue by YevheniiKravchenko** [facebook/react#14013]
**Do you want to request a *feature* or report a *bug*?**
Possibly a bug

**What is the current behavior?**
Repro demo: GitHub user search. 
Type one character and wait after the list is rendered - everything works correctly. Subsequent fetches work this way.
Type two characters faster than results for the first character are rendered and fallback will never go although the second request is successful. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/k5v6ojz107

**What is the expected behavior?**
Suspense "resolves" with last resolved fetch and renders the list of users

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react: 16.7.0-alpha.0
react-dom: 16.7.0-alpha.0
react-cache: 2.0.0-alpha.0

**Comment by vramana** [comment]
![image](https://user-images.githubusercontent.com/3112509/47636768-872cf480-db7f-11e8-9350-f5ac9947f50b.png)

I think that's intentional behaviour. Adding a key on the Suspense will fix it.

**Comment by aweary** [comment]
I don't think thats intentional, it should handle cases like this without having to add a `key`.

**Comment by YevheniiKravchenko** [comment]
At least it should emit some warning, not just quietly show fallback forever.

**Comment by gaearon** [comment]
This is definitely a bug
