### ISSUE TITLE
16.5.2 run well, but 16.6 version get Uncaught TypeError: Cannot read property 'displayName' of null in backend.js when open page in Chrome

### ISSUE THREAD

**Issue by huchong26** [facebook/react#14016]
There is some error when I use react 16.6 instead of 16.5.2

Just a very simple react page using react , react-router, redux
`<Provider store={store}>
        <BrowserRouter>
                <ContentPage {...this.props}>
                    <Switch>
                        <Route exact path="/test" component={TestContainer}/>
                        <Route path="/loading" component={LoadingItem}/>
                        <Route path="/locking" component={LockingItem}/>
                        <Route component={NoMatch}/>
                    </Switch>
                </ContentPage>
          </BrowserRouter>
   </Provider>`

the code run well using following the package.json 
"prop-types": "^15.5.10",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-redux": "^5.0.5",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.1",
but if  I change the react version from 16.5.2 to 16.6, build is ok.  but error show in console when I open the page in chrome: 
**backend.js:9159  Uncaught TypeError: Cannot read property 'displayName' of null    
at getDisplayName (backend.js:9159)    
at getDataFiber (backend.js:9880)    
at enqueueMount (backend.js:10137)    
at mountFiber (backend.js:10225)    
at backend.js:10285    
at Set.forEach (<anonymous>)   
at Object.walkTree (backend.js:10283)    
at backend.js:8534    
at <anonymous>:52:32
.......**

**Comment by gaearon** [comment]
You likely have an outdated version of React DevTools Chrome extension. Please update it.
