### ISSUE TITLE
Cases where hooks don't currently provide a good answer vs HOC

### ISSUE THREAD

**Issue by arieh** [facebook/react#14020]
(unsure if this is the right place, so trying it out)

I've noticed that the new React Hooks feature is aiming at providing an alternative composition pattern to HOC and render functions, but I believe that many of the use cases solved by HOC (at the framework level) cannot currently be addressed by the new hooks API. 

Specifically, there is not way to incorporate React Hooks with React.memo. Unless I am incorrect, this means that any system that would like to implement optimisations based on external context, such as the react-redux `connect` function (that uses `mapStateToProps` to implement an efficient `shouldComponentUpdate`) will still need to rely on a HOC/render-prop to automate this optimisation.

The reason I am bringing this up is because one of the main benefits stated in the documentation is to reduce framework level use of HOC that "pollute" the tree, of which the react-redux connect HOC is probably the most prevalent use case. 

Additionally redux (and `useRedux`) are specifically brought up as an exemplary use case, although with the current system it will cause large optimisation issues (since with no optimised `shouldComponentUpdate`, every "connected" component will re-render on every state change).
(Although this might fit into the documentation repo, this is a discussion / opinion and I do not feel it is a "mistake" that I should report, but rather a discussion on importance).

An example solution for this could be if there was a way to use contexts in `React.memo` (which unless I'm incorrect only have access to `props` and `prevProps`)

**Comment by FredyC** [comment]
If you check the [docs for React.memo](https://reactjs.org/docs/react-api.html#reactmemo) closely, you can see, there is a second argument which allows doing a similar optimization that is possible with `shouldComponentUpdate`. However, there are some whispers, that this is certainly not a final and you will be able to do it on a more granular level, especially with hook `useState` you should be able to decide if the component should rerender. I am not representing React team, so I cannot give you any more detail, but it's definitely under their radar.

**Comment by markerikson** [comment]
Yes, I actually discussed this exact issue with Dan and Sophie at ReactConf.

To explain in a bit more detail, let's say I have the following setup:

```js
// In some ancestor component. Ignore the inline object for this example.
<MyContext.Provider value={ {data: someLargeValue } />

// Further down in the component
function SomeComponent() {
    const {data} = useContext(MyContext);

    const derivedData = deriveSomeData(data);

    // render output based on derived data
}
```

In this example, `useContext(MyContext)` will subscribe `<SomeComponent>` to any updated value given to `MyContext.Provider`.  This is good, except for situations where you only care about the _derived_ result, and might want to bail out of rendering unless _that_ changes.  

React-Redux is indeed a more concrete example.  For version 6, we're going to be putting the entire Redux store state into context, but a given component would only want to re-render when the value extracted by its associated `mapState` function changes.  A notional `useRedux()` hook would cause the component to _always_ re-render when _any_ part of the Redux store changed, not just when the _derived_ value changes.

Dan and Sophie are aware of this, and want to add a way for functional components to bail out of rendering (ie, similar to `shouldComponentUpdate(nextProps, nextState)` returning `false`, or returning `null` from a `setState()` updater function).

**Comment by aweary** [comment]
Please try and post all feedback/questions [in the Hooks RFC](https://github.com/reactjs/rfcs/pull/68) so that the discussion doesn't get fragmented. Thanks!
