### ISSUE TITLE
useState and useEffect are undefined

### ISSUE THREAD

**Issue by KrustyC** [facebook/react#14032]
**Do you want to request a *feature* or report a *bug*?**
Report a "bug"

**What is the current behavior?**
I have a upgraded react to v16.6.0 in order to be able to use the new hooks method. I'm importing `useState` and `useEffect` from react but the browser keeps saying that `useState` and `useEffect` are `undefined`. So I decided to log react on the browser to check if the version was correct and if the 2 methods were there.

This is what I found out:
![screenshot from 2018-10-30 13-04-13](https://user-images.githubusercontent.com/20644593/47719919-7f835380-dc44-11e8-85c8-cc4377b0783d.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
All I did is upgrading (`yarn upgrade react@latest react-dom@latest`) and use the normal import 
`import React, { useState, useEffect } from 'react'`

**What is the expected behavior?**
I would expect the two functions above to be defined.
Do you know if I did anything wrong, or what could have possibly gone wrong?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: v16.6.0
Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
OS: ubuntu 18.10

**Comment by iamdustan** [comment]
hooks are still in RFC and only available in alpha builds.

https://reactjs.org/docs/hooks-overview.html
<img width="825" alt="screen shot 2018-10-30 at 9 16 00 am" src="https://user-images.githubusercontent.com/227879/47720533-784c4d80-dc24-11e8-8404-058bf4b698eb.png">

Try something like: `yarn upgrade react@16.7.0-alpha.0 react-dom@16.7.0-alpha.0`

**Comment by KrustyC** [comment]
My bad!! I should have noticed it was still a proposal! Sorry about that!
