### ISSUE TITLE
eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by steida** [facebook/react#14038]
```js
function Editor({ data: { page } }: EditorProps) {
  if (page == null) throw Error('missing page data in editor')
  const [editorValue, setEditorValue] = useState(() => {
}
```

I believe this should be a valid case, because throw.

**Comment by steida** [comment]
Hmm, I just realized throw should not be used for valid business case (GraphQL endpoint was updated). Render nothing (and request app update) is a valid approach.

**Comment by sophiebits** [comment]
I think we shouldn't warn on this.
