### ISSUE TITLE
ref initialized by React.createRef() attached to root element is not immediately available to child

### ISSUE THREAD

**Issue by justinemar** [facebook/react#14034]
Not really sure if this is an expected behavior but it's strange.

**What is the current behavior?**
A ref attached to a root element of a parent component always returns null when accessed in `componentDidMount` lifecycle of  the `Child` component

```
class Parent extends Component {
  constructor() {
    super();
    this.parentElem = React.createRef();
  }

  componentDidMount() {
    console.log("Parent", this.parentElem.current);
  }
  render() {
    return (
      <div class="parent-only" ref={this.parentElem}>
        {/* ^ Ref is null for child componentDidMount() */}
        <div class="both">I'm a div</div>
        {/* ^ Ref will behave as expected on this element */}
        <Child parentElem={this.parentElem} />
      </div>
    );
  }
}
```

```
class Child extends Component {
  componentDidMount() {
    console.log("Props obj", this.props); // ref is here

    console.log("Expect ELEMENT got", this.props.parentElem.current); // Null if ref is the root element
    console.log("Expect REF OBJ got", this.props.parentElem); // {current: null} if ref is the root element
  }
  render() {
    return <div>test</div>;
  }
}
```

sandbox https://codesandbox.io/s/j43jrvz4o9

**What is the expected behavior?**
Ref is expected to point to the root element

using
    "react": "^16.3.1",
    "react-dom": "^16.3.1",

also tested
    "react": "16.5.2",
    "react-dom": "16.5.2",

**Comment by sophiebits** [comment]
This is more or less expected behavior. The idea is that each component can fully initialize (i.e., finish its componentDidMount) before the parent's componentDidMount is called. I'd probably recommend restructuring your code so that this isn't an issue for you.

**Comment by matthewvalentine** [comment]
My two cents, refs are already set separately from the mount callbacks, so I don't see why the entire refs pass couldn't happen before the entire mounting pass.

There are many situations where it simply is not ergonomic to restructure the code, such as an InteresectionObserver in the child, where what would have been one simple and straightforward solution becomes unexpected, onerous, error-prone, and every dev solves it differently. 

Some detail of backwards compatibility might make it hard to change, though.
