### ISSUE TITLE
Numeric-Input Decimal Issue

### ISSUE THREAD

**Issue by btf93** [facebook/react#14045]
I've impemented the React numeric-input into my code, however I've noticed that when entering a figure such as '0.05', it doesn't allow it. '0.15' for example works fine, but the '0.0' is the issue.

It can be replicated at this link: http://vlad-ignatov.github.io/react-numeric-input/

In particular with the 'With inline styles disabled' format. I raised this elsewhere but was told to come here to raise it too. Thanks.

**Comment by Xizario** [comment]
@btf93 see this https://github.com/vlad-ignatov/react-numeric-input/issues/86

**Comment by btf93** [comment]
> @btf93 see this [vlad-ignatov/react-numeric-input#86](https://github.com/vlad-ignatov/react-numeric-input/issues/86)

How do I access the fix? Is it in the latest version? Sorry, I'm quite new to React! Thanks

**Comment by sagar-gavhane** [comment]
Hi @btf93,

Can you provide sample code base with screenshot for further reference?

**Comment by btf93** [comment]
Hi, if the issue has been fixed I’ll try upgrading to React 16.0.0 tomorrow. We’re currently using 15.4.2 I think (from memory as I’m not at work now), so we’re quite far behind. I’ll report back tomorrow once I’ve tried it and if it doesn’t work I’ll supply some sample code. Thanks!

**Comment by btf93** [comment]
I've upgraded to the latest version of React. Was this fixed applied in the last version or do I have to do something different entirely to get it to work?

**Comment by Xizario** [comment]
@btf93 it is not an issue with React, it is problem in the 'react-numeric-input' component that you are using. This is third party package and not part of the React. This is why I suggest you to write in the repository already linked in my previous post. They have it on [pull-request](https://github.com/vlad-ignatov/react-numeric-input/pull/101), but seems the author of the package is not maintaining it, and their last release is from nearly one year ago.

**Comment by btf93** [comment]
@Xizario Oh I see! Sorry I'm really new to React, hence the confusion here. That makes perfect sense now and I've asked for an update in the link you sent.
