### ISSUE TITLE
Hooks JSPM support

### ISSUE THREAD

**Issue by jamesknelson** [facebook/react#14058]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Hooks cannot be used with JSPM build of React.

For this example:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module">
      import React from 'https://dev.jspm.io/react@16.7.0-alpha.0'
      import ReactDOM from 'https://dev.jspm.io/react-dom@16.7.0-alpha.0'

      function Button(props) {
        const [position, setPosition] = React.useState({});

        return React.createElement('button', {
          children: props.children,
          onMouseMove: event => {
            setPosition({
              left: event.clientX + 2,
              top: event.clientY + 2
            })
          },
          style: {
            ...position,
            position: position.left ? 'fixed' : 'absolute',
          }
        })
      }

      ReactDOM.render(
        React.createElement(Button, null, "Add a contact"),
        document.getElementById('root')
      )
    </script>
  </body>
</html>
```

The following error is given: 

```
Uncaught Error: Hooks can only be called inside the body of a function component.
    at invariant (react.development.dew.js:100)
    at resolveDispatcher (react.development.dew.js:1475)
    at Object.useState (react.development.dew.js:1498)
    at Button (index.html:15)
```

However, the same code works fine when loading React via an unpkg `<script>` tag.

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/react@16.7.0-alpha.0/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@16.7.0-alpha.0/umd/react-dom.development.js"></script>
    <title>Untitled App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module">
      function Button(props) {
        const [position, setPosition] = React.useState({});

        return React.createElement('button', {
          children: props.children,
          onMouseMove: event => {
            setPosition({
              left: event.clientX + 2,
              top: event.clientY + 2
            })
          },
          style: {
            ...position,
            position: position.left ? 'fixed' : 'absolute',
          }
        })
      }

      ReactDOM.render(
        React.createElement(Button, null, "Add a contact"),
        document.getElementById('root')
      )
    </script>
  </body>
</html>
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/qu5dh2ca/1/

**What is the expected behavior?**

JSPM and UNPKG should behave identically.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.7.0-alpha.0, development mode bundle.

**Comment by simonkberg** [comment]
React doesn't provide ESM builds. In the jspm.io example you're using ESM with a CJS build transformed by jspm.io, and in the unpkg example you're using the global UMD build (provided by react, untampered). I'm not sure why you're expecting them to work identically when they're completely different?

From [jspm.io](https://jspm.io):
> If a package or module is not loading correctly, and it is expected to work through a bundler, please [post a project issue](https://github.com/jspm/project).

I suggest you report this to jspm instead.

**Comment by jamesknelson** [comment]
Fair enough, I'll close this and submit an issue to jspm's project if it still doesn't work once 16.7 is released.
