### ISSUE TITLE
Property 'memo' doest not exist on type 'typeof React'?

### ISSUE THREAD

**Issue by simmons8616** [facebook/react#14059]
Property 'memo' doest not exist on type 'typeof React'?  I have download the lastest ‘@types/react’，which has no memo method.

**Comment by illuminist** [comment]
I believe `@types/react@latest` is still at react version 16.4 while `memo` is introduced in react 16.6

**Comment by sophiebits** [comment]
Closing this since we don't currently maintain the TS typedefs, but you can watch that PR for when it is landed in DefinitelyTyped.
