### ISSUE TITLE
Getting "dispatcher.useContext is not a function" when testing in Jest with hooks

### ISSUE THREAD

**Issue by tomitrescak** [facebook/react#14054]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

I know it is still in alpha, so sorry for early posting. When testing components in Jest using react-test-renderer, I am getting `dispatcher.useContext is not a function` whenever I am trying to use `useContext` hook.

**What is the expected behavior?**

Test should pass with no issues.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.7-alpha.

**Comment by hamczu** [comment]
have you updated react-dom to 16.7-alpha as well? I had that issue when I tried to use hooks with react-dom@16.6

**Comment by tomitrescak** [comment]
Yes I did, hooks work fine in browser

**Comment by TrySound** [comment]
@tomitrescak How do you render components you testing?

**Comment by tomitrescak** [comment]
@TrySound I am using `react-test-renderer`.

Here is a full repro:

```js
import { create } from 'react-test-renderer';

it('renders correctly', () => {
  const Context = React.createContext();

  const ProcessInstanceItem = () => {
    const context = React.useContext(Context);

    return <div>OK</div>
  };

  const list = create(
    <Context.Provider>
      <ProcessInstanceItem />
    </Context.Provider>
  ); // error is thrown here
  expect(list).toMatchSnapshot();
});
```

**Comment by tomitrescak** [comment]
And here is a repro on CodeSandbox

https://codesandbox.io/s/pm44n0lyxm

Just view tests to get the same error as I do.

**Comment by tomitrescak** [comment]
OK, I figured it out .... I was using react-test-renderer from 16.6.
