### ISSUE TITLE
ReactDOMServer import conflicts with no-submodule-imports TSLint rule

### ISSUE THREAD

**Issue by trivikr** [facebook/react#14051]
**Do you want to request a *feature* or report a *bug*?**
Question about submodule export of ReactDomServer

**What is the current behavior?**
* The way to import ReactDOMServer is by `import ReactDOMServer from 'react-dom/server';` ([documentation](https://reactjs.org/docs/react-dom-server.html))
* This conflicts with TSLint rule [no-submodule-imports](https://palantir.github.io/tslint/rules/no-submodule-imports/)
* There are couple of fixes available, like:
  * disabling the rule by setting `"no-submodule-imports": false` in TSLint config
  * disabling the rule only for react-dom `"no-submodule-imports": [true, "react-dom"]`

**What is the expected behavior?**
* Is there a plan to make ReactDOMServer available as top-level export?

**Comment by sophiebits** [comment]
react-dom/server is a public API so you should feel fine importing it. I don't think we're planning to change this so you'll have to adjust your linter to accomodate.
