### ISSUE TITLE
It's confusing that refs are not attached by the time useMutationEffect() runs

### ISSUE THREAD

**Issue by gaearon** [facebook/react#14075]
This doesn't work but I'd expect it to.

https://codesandbox.io/s/x00vn4ylp

**Comment by Caryyon** [comment]
Could it be that `useMutationEffect()` is being called synchronously as the DOM mutation, so there is no DOM element to even add a `ref` to?

**Comment by Caryyon** [comment]
I believe you would have to use `useLayoutEffect()` in this case, as it fires synchronously after all DOM mutations. Allowing the ref to "settle"

**Comment by engprodigy** [comment]
@Caryyon 

> I believe you would have to use useLayoutEffect() in this case, as it fires synchronously after all DOM mutations. Allowing the ref to "settle"

Ya it works @gaearon

**Comment by Macil** [comment]
What's the use of useMutationEffect() if no refs are set by the time it runs? I'm struggling to think of what it could be used for if you don't have any live handles to the DOM within its callback.

**Comment by aknuds1** [comment]
I also just noticed this, and that `useLayoutEffect` indeed lets you get a working reference.

**Comment by Kovensky** [comment]
Now that `useMutationEffect` has been banished to `/dev/null` this is possibly "fixed"?
