### ISSUE TITLE
No warning message when updating unmounted component using hooks.

### ISSUE THREAD

**Issue by Tomekmularczyk** [facebook/react#14076]
**Do you want to request a *feature* or report a *bug*?**
Both I guess

**What is the current behavior?**
When I try to use `setState` on an unmounted class component I get a warning. I expected the same would be true for hooks and `useState`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/n7kvlq9o0p
Quickly navigate to pageB and back to pageA - `useEffect` will do a cleanup, but soon after `setState` will get called.

**What is the expected behavior?**
I think this should result with the same warning as with class component... maybe not.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.7.0-alpha

**Comment by sophiebits** [comment]
I get a warning if I visit your sandbox, click to B, click back, then wait:

![screenshot of warning](https://user-images.githubusercontent.com/6820/47932708-9b2e6a00-de8f-11e8-98bc-9b2e2a50e81a.png)

I assume this means it is working as intended? Please reply if I am missing something, happy to reopen.

**Comment by gaearon** [comment]
Also tried it:

<img width="1281" alt="screen shot 2018-11-02 at 6 08 45 pm" src="https://user-images.githubusercontent.com/810438/47932733-6390e380-deca-11e8-9ac6-28e69ef9d6be.png">

**Comment by Tomekmularczyk** [comment]
@sophiebits Strange now I get it too. Though it only appears first time it happened, not sure if that's intended: http://recordit.co/U6GPdSKV4g
