### ISSUE TITLE
Style attribute not applied when backgroundImage contains parenthesis

### ISSUE THREAD

**Issue by ClementParis016** [facebook/react#14074]
👋Hi there! I couldn't find any other reference to this, so I guess this not a know issue already.

**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

When using inline styles to set a `backgroundImage: url(<url>)`, where url is a path containing parenthesis, it doesn't apply the style attribute to the DOM element.

**Demo:**

Repro on CodeSandbox: https://codesandbox.io/s/lrxq8rlywz

**What is the expected behavior?**

It should apply the style attribute.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Seems to be affecting all versions, not specific to any browser or OS.

**Comment by mmarkelov** [comment]
@ClementParis016 You just need some quotes here:
https://codesandbox.io/s/52j3j37v7n
