### ISSUE TITLE
<option> and <textarea> elements should be able to contain Components that return strings and render their output correctly

### ISSUE THREAD

**Issue by PPepperCC** [facebook/react#14071]
**Do you want to request a *feature* or report a *bug*?**

Feature request

**What is the current behavior?**

If you use a Component that returns a string inside an option or textarea element, the Component will be rendered as '[object Object]'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/38tz0ym2/

**What is the expected behavior?**

The string returned by the component should be rendered as the elements innerHTML.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This was working accidentally in react v16.0.0 - v16.4.2 but was apparently buggy and crash prone. It no longer works at all in react v16.6.0

**Comment by PPepperCC** [comment]
My specific use case for this feature is that I am using a 'translation' component, to enable me to replace strings in a multi-language application. It was very clean and convenient to be able to use the same component inside <option> (and potentially also <textarea> elements). Currently I am working around this using ReactDOMServer.renderToString, but it is not ideal.

**Comment by gaearon** [comment]
Yeah that would be nice to do. I'm not sure how to implement this but let's keep it open.

**Comment by mbabauer** [comment]
So I was taking a crack a this by updating the `flattenChildren(children)` of ReactDOMOption like so (obviously without the `console.log`s):
```function flattenChildren(children) {
  let content = '';

  // Flatten children. We'll warn if they are invalid
  // during validateProps() which runs for hydration too.
  // Note that this would throw on non-element objects.
  // Elements are stringified (which is normally irrelevant
  // but matters for <fbt>).
  React.Children.forEach(children, function(child) {
    if (child == null) {
      return;
    }
    console.log('child (type): ', typeof child);
    console.log('child: ', child);
    let childTypeVal;
    if (typeof child === 'object' && typeof child.type === 'function') {
      console.log('child.type: ', child.type());
      childTypeVal = child.type();
    }
    content +=
      typeof child === 'object' &&
      typeof child.type === 'function' &&
      typeof childTypeVal === 'string'
        ? child.type()
        : child;
    // Note: we don't warn about invalid children here.
    // Instead, this is done separately below so that
    // it happens during the hydration codepath too.
  });

  return content;
}```

That works, but it breaks the unit test for `should support element-ish child` with:
```TypeError: Cannot read property 'content' of undefined

       95 |     let obj = {
       96 |       $$typeof: Symbol.for('react.element'),
    >  97 |       type: props => props.content,
          |                                           ^
       98 |       ref: null,
       99 |       key: null,
      100 |       props: {```

So I am wondering if the right approach is to add a toString to the object that wrappers the component, similar to how that test does, which a functional component is created that returns a simple String, but I am not sure where that code lives.  Can someone guide me to where that component wrapper happens?

**Comment by daltones** [comment]
I can understand why `<textarea>` [was adapted from its original HTML form](https://reactjs.org/docs/forms.html#the-textarea-tag) so it works exactly as a `<input type="text">`. It's very intuitive that prop `value` will accept strings only. I mean, `<textarea value={<StringComponent />} />` is unlikely.

But why in first place React expects that children of `<option>` must be strings? What if `<option>` elements didn't have any special handling at all?
