### ISSUE TITLE
useCallback should warn when something is returned

### ISSUE THREAD

**Issue by steida** [facebook/react#14080]
Because it seems the return value is omitted. That's probably fine and necessary, but:

1) React should warn when something is returned.
2) It should be mentioned in docs.

**Comment by gaearon** [comment]
Huh. This seems surprising. Unless we wanted to leave the door open for delaying it.

**Comment by sophiebits** [comment]
@steida I double checked the implementation and I don’t think what you’re claiming is right. useCallback returns either the first argument exactly or a value from a past render. It does not modify the function in any way.

**Comment by steida** [comment]
Probably a bug in my code. Thank you for a quick answer and sorry for a confusion.
