### ISSUE TITLE
Type error: Module has no exported members 'Suspense', 'lazy'

### ISSUE THREAD

**Issue by qmn1711** [facebook/react#14089]
**Do you want to request a *feature* or report a *bug*?**
I think it's a bug

**What is the current behavior?**
React failed to compile:
```
Type error: Module '".../node_modules/@types/react/index"' has no exported member 'Suspense'.
Type error: Module '".../node_modules/@types/react/index"' has no exported member 'lazy'.
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I used `react ^16.6.0`, `react-scripts 2.1.1` with  `--typescript` flag. I tested new project without `--typescript` flag, it worked well.

Here is my config:
package.json
```
...
  "dependencies": {
    "@types/jest": "23.3.9",
    "@types/node": "10.12.2",
    "@types/react": "16.4.18",
    "@types/react-dom": "16.0.9",
    "@types/react-router-dom": "^4.3.1",
    "node-sass": "^4.9.4",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1",
    "typescript": "3.1.6"
  },
...
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es2015", "dom"],
    "allowJs": true,
    "skipLibCheck": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": ["src"]
}
```

**Comment by arianon** [comment]
Update `@types/react` and `@types/react-dom` to at least `^16.6.0`

You probably meant to open this issue on [facebook/create-react-app](https://github.com/facebook/create-react-app) by the way :smile:
