### ISSUE TITLE
eslint-plugin-react-hooks does not work with wrapped components

### ISSUE THREAD

**Issue by AlexanderShushunov** [facebook/react#14088]
``` js
export const Counter = () => {
    let count, setCount;
    if (0 === 1) {
        [count, setCount] = useState(0);
    }
    return count;
};
const wrapper = Component => Component;
export const WrappedCounter = wrapper(() => {
    let count, setCount;
    if (0 === 1) {
        [count, setCount] = useState(0);
    }
    return count;
});
```
Linter shows an error in the first component, but ignore the second one.

**Comment by gaearon** [comment]
We should probably handle this. Although it’s not ideal that you pass an anonymous function since that doesn’t give you a chance to name it.

**Comment by AlexanderShushunov** [comment]
I think, it is a very common case. We have an anonymous function which is wrapped by several HOCs. An application uses only the wrapped variant. So, we do not need to think of a name of the inner function.

**Comment by sandiiarov** [comment]
Why you don't want to use named function?
1. It helps to debug a code in react dev tools.
2. It will solve the issue with eslint.

```js
export const WrappedCounter = wrapper(Counter);
```

**Comment by AlexanderShushunov** [comment]
@sandiiarov Because 'There are only two hard things in Computer Science...'
The example above is super simple. In real life finding out an appropriate name is a hard thing.

**Comment by gaearon** [comment]
@AlexanderShushunov Would you like to send a PR to the plugin to support this?

**Comment by AlexanderShushunov** [comment]
@gaearon I am not very experienced in eslint rules writing, but I always want to write one )

**Comment by lukyth** [comment]
@AlexanderShushunov Are you still working on this?

**Comment by gaearon** [comment]
I guess not, @lukyth feel free to look into it

**Comment by fortinmike** [comment]
Another interesting case that triggers this is using the built-in `React.memo` function:

```javascript
const MyComponent = React.memo(props => {
  const count = 0;
  if (count === 1) useMyHook(); // NOT detected
  return <div>Hello</div>;
});
```

```javascript
const MyComponent = props => {
  const count = 0;
  if (count === 1) useMyHook(); // Detected!
  return <div>Hello</div>;
};
```

**Comment by AlexanderShushunov** [comment]
@lukyth I tried to do it. But it was a bit complicated than I thought )

**Comment by FredyC** [comment]
It's interesting that this is not getting more attention considering it does not work with React built-ins alone. And no, I am not able to fix it, AST is still too magical land for me :)

**Comment by gaearon** [comment]
See https://github.com/facebook/react/pull/16712#issuecomment-607519330.

**Comment by gaearon** [comment]
(We fixed the case for memo/forwardRef)
