### ISSUE TITLE
useEffects called while second argument doesn't change

### ISSUE THREAD

**Issue by TonyGorez** [facebook/react#14096]
I tried to get more familiar with hooks :)

I created a custom hooks called `useValidator()`.

I use useEffects() passing a props (props.value) as optional second argument.

My problem is that `useEffect` is called while `props.value` doesn't change.

Demo : https://codesandbox.io/s/215ypok5wy

**Comment by gaearon** [comment]
Can you create a more minimal example?

**Comment by TonyGorez** [comment]
I cleaned up the code : https://codesandbox.io/s/yvv5vv37x

I can drop a code snippet here : 

```javascript
const useValidator = (intialValue, value, validator, delayTime) => {
  const [isErrorMessageDispalyable, setErrorMessageDisplayable] = useState(
    intialValue
  );

  useEffect(
    () => {
      setErrorMessageDisplayable(true);
    },
    [value]
  );

  return isErrorMessageDispalyable;
```

I expect that `isErrorMessageDispalyable` is set to true when `value` changed. But in my case `isErrorMessageDispalyable` is set to true even if `value` doesn't change.

**Comment by gaearon** [comment]
It runs after the initial mount too. Is that the source of confusion?

**Comment by TonyGorez** [comment]
Yes ^^ ! Sorry for that. Maybe do you got a trick to avoid this ? (or maybe it's for the future ...)

**Comment by TonyGorez** [comment]
Or maybe, I have to read the documentation again ... I may miss something.

**Comment by gaearon** [comment]
Yep, it's in the docs (Using the Effect Hook and the Hooks FAQ).
