### ISSUE TITLE
Bug: React hooks issue with Intervals.

### ISSUE THREAD

**Issue by vank0** [facebook/react#14094]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
I've created React Hook that displays counter, that's being incremented every 100ms. After few increments, the counter is struck and would not update anymore.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
The bug is reproduced here: https://codepen.io/vank0/pen/yQyqNV?editors=0010

**What is the expected behavior?**
I expect the counter to increment continuously without getting stuck after 10 increments.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.7-Alpha , Chrome 70 on Windows 10

**Comment by edvinerikson** [comment]
Here's a working version https://codepen.io/anon/pen/mQyzpj?editors=0010

Look into `useEffect` and how to use it for side-effects.
https://reactjs.org/docs/hooks-effect.html

**Comment by vank0** [comment]
> Here's a working version https://codepen.io/anon/pen/mQyzpj?editors=0010
> 
> Look into `useEffect` and how to use it for side-effects.
> https://reactjs.org/docs/hooks-effect.html

Awesome! Thanks a lot :)
