### ISSUE TITLE
Why input stuck in react16 but not in react15.

### ISSUE THREAD

**Issue by Jandou6** [facebook/react#14093]
I am not sure if I understand the mistake.

In react16, I think that user input is the hight priority （Maybe my mistakes）. So when update it will update user input in first. But I use this demo, when there are 1000 elements are updating. I can not input smoothly. But in React15 is very smoothly. 

ps: I try in  **React16.6.0** and **React15.6.1**

```
    <div id="container"></div>
    <script>
      function MyTextComponent (props) {
        return React.createElement('p', null, props.children);
      }
      class MyComponent extends React.Component {
        constructor(props) {
          super(props);
          this.state = {
            value: 0,
            text: '',
          }
        }
        
        render () {
          return React.createElement('div', null, this.renderInput(), this.renderText());
        }

        componentDidMount() {
          this.handleChangeText();
        }

        handleChangeText() {
          setInterval(() => {
            this.setState({
              text: Math.random().toString(36).slice(2),
            });
          },100);
        }

        renderText() {
          let len = 1000; // Try to render 2000 Children will be more obvious
          const list = [];
          for (let i = 0; i < len; ++i) {
            list.push(React.createElement(MyTextComponent, {key:i}, this.state.text));
          }
          return list;
        }

        renderInput() {
          return React.createElement('input', {
            value: this.state.value,
            onChange: (e) => { this.setState({ value: e.target.value }) },
          });
        }
      }
      
      ReactDOM.render(
        React.createElement(MyComponent, null),
        document.getElementById('container')
      );
    </script>
```

**Comment by gaearon** [comment]
>In react16, I think that user input is the hight priority （Maybe my mistakes）

There is no prioritization in React 16. You're referring to a future mode that's not enabled by default.

>But I use this demo, when there are 1000 elements are updating. I can not input smoothly. But in React15 is very smoothly.

Please provide a complete example project demonstrating this. Just code isn't enough since there are so many different things in your environment that could influence performance.

**Comment by Jandou6** [comment]
OH~~~~, Thanks tips. It is smoothly in codesandbox. 👍  :)
