### ISSUE TITLE
Alternatives to functional components

### ISSUE THREAD

**Issue by pronebird** [facebook/react#14098]
**Do you want to request a *feature* or report a *bug*?**

n/a

**What is the current behavior?**

It's quite convenient to wrap the parts of complex UIs in functional components, then simply compose them together, especially when different configurations repeat some of the elements.

Consider the following example:

```js
// class UserAccountPage {

render() {
  const UserAccount = () => {
    return <TheRealUserAccount userLogin={this.props.userLogin} />
  }
  const LoginButton = () => {
     return <TheRealLoginButton remember={this.props.remember}  />
   }

  const Quit = () => {
     return <TheRealQuit askToStay={this.state.askToStay} />
  }

  switch this.props.loggedIn {
    case .yep:
       return (
         <ComplexComponent>
            <UserAccount />
            <Quit />
         </ComplexComponent> 
       )

     case .nope:
       return (
         <ComplexComponent>
            <LoginButton />
            <Quit />
         </ComplexComponent> 
       )
  }
}

// }
```

So now what I see is that any change to state or props of `UserAccountPage` causes functional components to re-mount the underlying tree. Which is perhaps by design. 

What I wonder is, if there are any alternatives. The syntax using functional components is quite descriptive since it looks like regular HTML or JSX.

**Comment by gaearon** [comment]
I suggest to use regular components, and not define them inline like this. I'm not sure the minor readability benefit is worth the other issues.

If you have ideas about how to improve the API please post them here: https://github.com/reactjs/rfcs

Thanks!
