### ISSUE TITLE
useContext returns invalid/default value when used inside custom react renderer

### ISSUE THREAD

**Issue by HriBB** [facebook/react#14101]
**Do you want to request a *feature* or report a *bug*?**

I want to request a bug.

**What is the current behavior?**

If we `useContext` inside Component in a custom renderer tree, the default value (value passed to `React.createContext` function) is returned.

**What is the expected behavior?**

Expected behavior is to get the latest value of the context. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
react: 16.7.0-alpha.0
react-dom: 16.7.0-alpha.0
react-reconciler: 0.17.0-alpha.0
scheduler: 0.11.0-alpha.0
```

Here's a reproduction case https://github.com/HriBB/react-repro. Already filed related bug to [react-devtools](https://github.com/facebook/react-devtools/issues/1217) issue tracker.

**Comment by gaearon** [comment]
This is an expected limitation. See https://github.com/facebook/react/issues/13336#issuecomment-414709155 for a workaround.
