### ISSUE TITLE
defaultProps inconsistency between createElement and cloneElement

### ISSUE THREAD

**Issue by jdlehman** [facebook/react#14136]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`defaultProps` aren't handled the same between `createElement` and `cloneElement`

given a `Modal` component that just adds a wrapper around the children given to it where it has `defaultProps` defined:
```js
function Modal({ children }) {
  return <div className="Modal">{children}</div>;
}

Modal.defaultProps = {
  children: <div>Default Content</div>
};
```

`createElement` sets default props **AFTER** setting children while `cloneElement` sets default props **BEFORE** setting children, resulting in different behavior:
```js
const defaultModal = React.createElement(Modal,  { children: <div>Hi</div> }, undefined);
// evaluates to the default prop: <div className="Modal"><div>Default Content</div></div>

const cloned = React.cloneElement(defaultModal, { children: <div>Hi</div> }, undefined);
// evaluates to <div className="Modal"></div>
```

However, this only happens when children is explicitly set to `undefined`, since there is no check for children being `undefined`.

```js
const defaultModal = React.createElement(Modal,  { children: <div>Hi</div> });
// evaluates to the default prop: <div className="Modal"><div>Hi</div></div>

const cloned = React.cloneElement(defaultModal, { children: <div>Hi</div> });
// evaluates to  <div className="Modal"><div>Hi</div></div>
```

I have a PR for a refactor that also makes `cloneElement` behave like `createElement` by setting default props after setting children: https://github.com/facebook/react/pull/14117, though I don't know if this is ultimately the behavior we want with `children`. We might also want to have code that ignores `undefined` children (though I don't know what repercussions that would have inside the reconciler).

It is a bit confusing to know if setting children in the config object or as the parameters to the function should take precedence. We should definitely document this, though it is probably not a case that comes up often in real world code.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

CodeSandbox: https://codesandbox.io/s/q3wwrjon24

**What is the expected behavior?**

`createElement` and `cloneElement` should set default props in the same way.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

CodeSandbox is using React 16.5.2. I think this has been like this for a while if not always.

**Comment by gaearon** [comment]
Changing this would be a breaking change, right?

**Comment by jdlehman** [comment]
Yes, this would definitely be a breaking change. 

I am primarily curious to understand the nuance between setting `children` via the config object versus passing as extra arguments to `createElement`/`cloneElement`. I am not even sure which should take precedence. Though I think at the very least both of these functions should have the same behavior.
