### ISSUE TITLE
Regression: react-dom 16.5.2+ Tapping outside of an input on iOS12 does not fire onBlur event

### ISSUE THREAD

**Issue by chrstntdd** [facebook/react#14139]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Only on iOS, with both chrome and safai, once an input is focused, attempting to tap outside of it to blur the input, focus is kept and the onBlur event is not fired.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. tap to focus input
2. tap outside of input to blur it
3. observe focus is kept

example repo: https://codesandbox.io/s/k351z189vo

**What is the expected behavior?**
Tapping outside of the input should blur the input and remove focus

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This only affects iOS, android still maintains the same expected behavior.

**Comment by chrstntdd** [comment]
Update: I went back and found that this issue seems to have been introduced with 16.5.2. Could it maybe be related to this change https://github.com/facebook/react/commit/2282400850ff51892d581da782fdbc98047b8fc3 ?

**Comment by DKastani** [comment]
This is still happening

**Comment by chrstntdd** [comment]
I can't seem to reproduce this anymore on my device running iOS 13.3.1. Unable to verify if iOS 12 is still broken. Not sure if something on the iOS side was resolved or within React. We're now running `react` & `react-dom` `v16.3.0`

**Comment by iou90** [comment]
Possibly fixed with react/react-dom@17.0.0.
