### ISSUE TITLE
package "scheduler": "^0.11.0" didn't exist but it has been defined in react-test-render

### ISSUE THREAD

**Issue by lptai** [facebook/react#14134]
**Do you want to request a *feature* or report a *bug*?**
-Bug

**What is the current behavior?**
-Package scheduler@^0.11.0 has never ever existed but it was defined in package.json of 'react-test-render`
-Moreover, this commit has been merged to the trunk https://github.com/facebook/react/commit/b50e63ef537ce7784a1f981570b5abff5c81c59d#diff-6f4dd9a87ba82392f4d6933b6d85f5e9

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
Here it is:

https://unpkg.com/scheduler@0.11.0/
