### ISSUE TITLE
Suspense fallback component remounts when parent is re-rendered

### ISSUE THREAD

**Issue by dmnd** [facebook/react#14140]
**Do you want to request a *feature* or report a *bug*?**
I think this might be a bug, but perhaps my understanding of reconciliation is incorrect.

I'm trying to use `lazy` and `Suspense` as primitives to implement some loading UX requirements.

Specifically, I want to render a loading state indicator as a descendant of a lazy component's ancestor. Rendering the indicator in an ancestor seems like the happy path, but I'm trying to do something a little different.

**What is the current behavior?**
1. Go to https://codesandbox.io/s/rywvy84x34
2. Click the button
3. See it crash

**What is the expected behavior?**
1. Go to https://codesandbox.io/s/rywvy84x34
2. Click the button
3. See the text is now "Show lazy (Loading...)"
4. Wait a bit
5. See the lazy compnent render

My understanding of the reconciler algorithm leads me to expect the fallback component to be mounted only a single time. But what I'm observing is that setting state on the parent component causes the fallback component to unmount then remount, triggering an infinite loop, which then causes React to crash.

Note that if you wrap both didMount and willMount in a `setTimout(..., 0)` then things work, except the component is remounting in a loop until the promise is resolved.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I've only tried this in 16.6.0.

**Comment by gaearon** [comment]
Please try 16.6.1? It has a bug fix for remounting.

**Comment by dmnd** [comment]
Oh, I didn't notice 16.6.1 was out. I just updated the sandbox above and it works great. Thanks!
