### ISSUE TITLE
Ref's don't have all the properties one would expect.

### ISSUE THREAD

**Issue by cinnamennen** [facebook/react#14145]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
With a class like
```jsx
class Parent extends React.Component {
  constructor(props) {
    super(props);
    this.tableRef = createRef();
  }

  render() {
    return (
      <div>
        <Element1
          inputRef={this.tableRef}
        />
        <Element2
          style={{ maxHeight: this.tableRef.current
                .getBoundingClientRect().height }}
        />
      </div>
    );
  }
}

class Element1 extends React.Component {
  render() {
    return (
      <Table ref={this.props.inputRef}>
        {/*Contents*/}
      </Table>
    );
  }
}
```
`getBoundingClientRect()` doesn't work.  Instead you must resort to `findDOMNode`, like
```jsx
<Element2
          style={{ maxHeight: findDOMNode(this.tableRef.current)
                .getBoundingClientRect().height }}
/>
```

**What is the expected behavior?**
Given that refs are [supposed to negate the need to use `findDOMNode`](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220), this seems like a weak spot.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 16.4.2, Chome

**Comment by markerikson** [comment]
What is `<Table>` ?  Unless it's using `forwardRef` internally, putting a ref on it won't hand back a DOM node - it'll handle back the `Table` class instance.  

This looks like a logic error in use of refs to me.

**Comment by Kovensky** [comment]
Even if you're not using `forwardRef`, what you did with `inputRef` is really close to the right thing. You just need to also do it in `Table`.

(Note, semantic-ui-react, which happens to have a `Table` component, has no support for refs _at all_ in current releases; they're working on a forwardRef PR)
