### ISSUE TITLE
Portals created dynamically exist outside of main tree

### ISSUE THREAD

**Issue by seanlandsman** [facebook/react#14154]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using a library that creates provided React Components dynamically and renders them using Portals then the components are rendered as expected, but exist outside of the main react tree.

See screenshot here:

![image](https://user-images.githubusercontent.com/1329081/48217006-1d31fd80-e37e-11e8-886b-2babec1d1db9.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I've create a repro of the problem here: https://github.com/seanlandsman/dynamic-react-components.git

yarn install
npm start

Then using react devtools inspect the created React components

This is a trimmed down/simplified example, but it illustrates the problem I'm seeing.

**What is the expected behavior?**

The dynamically rendered components should exist within the main/parent React application

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react: 16.6.1
react-dom: 16.6.1
react-scripts: 2.1.1

**Comment by seanlandsman** [comment]
Is there any further information I can add to help with this?

**Comment by markerikson** [comment]
This seems like it's simply a DevTools visualization concern?

I can make arguments both ways.  On the one hand, the `<Portal>` itself is being rendered deep inside the original component tree.  On the other hand, it's conceptually "outside" the current tree to some extent.

Either way, this doesn't seem like a bug in React.

**Comment by seanlandsman** [comment]
hi @markerikson - the thing is that if I use the official portal example (https://codepen.io/gaearon/pen/yzMaBd) I get what I'd expect:

![image](https://user-images.githubusercontent.com/1329081/48893034-49965100-ee37-11e8-9c77-d38eedafa781.png)

This may not be a problem as you say, but the inconsistency made me think that there was issue an issue here, or that I was doing something wrong in my library

thanks

**Comment by jquense** [comment]
I think that react-portal doesn't use the new portal api? Elements s at the root usually indicate entirely new roots are being made

**Comment by gaearon** [comment]
Yeah it probably doesn't use the portal API.

**Comment by markerikson** [comment]
You're calling ReactDOM.render again with that portal, rather than returning it as a part of the render method. Don't do that :)

**Comment by jquense** [comment]
Portals sounds like the right tools for you, mark it all here tho were point in out your using the new API incorrectly tho. You don't use it along with ReactDOM.render instead just render the result of createPortal directly  as the child of any other component

**Comment by seanlandsman** [comment]
@jquense thanks - I think I understood what Mark was saying, but looking again at the repo I supplied I wasn't sure how I could do this given the nature of the library I have.

I believe that what I'm doing is incorrect, I'm just not sure how to correct it - that's what I meant by doing more reading/experimentation.

thanks!

**Comment by markerikson** [comment]
@seanlandsman : the API is admittedly a bit weird (and not even listed on the main "top-level `React` namespace" docs page), but see the ["Portals" docs page](https://reactjs.org/docs/portals.html) for examples.  Ultimately, you're supposed to do `return React.createPortal(<SomeComponent, someDomNode)` from your render method.
