### ISSUE TITLE
"Cannot set property 'return' of null" while using Suspense and lazy

### ISSUE THREAD

**Issue by chrisvasz** [facebook/react#14162]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Given code like this:
```jsx
<Suspense fallback={...}>
  {this.state.render && <LazyComponent />}
</Suspense>
```
my `LazyComponent` should download and render when I run `this.setState({ render: true })`. Instead, I get an internal React error about setting property `null` of `return`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/cq9hfwe8/1/. Open the console to see the error message.

**What is the expected behavior?**

The combination of `Suspense` and `lazy` defer downloading and rendering my component until I set a state variable to `true`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tried on Windows in Chrome 71, React 16.6.1.

**Comment by acdlite** [comment]
@chrisvasz My bad! That's what I get for using `any`. #14164 fixes it. Will release a patch within the next few days.

**Comment by chrisvasz** [comment]
Hey @acdlite, thanks for the quick turnaround!

One thought for you: I was _pretty jazzed_ about seeing my test case in that commit! A goal of mine has been to contribute code to React for a while now, and after today, I can say mission accomplished! But while it was _pretty cool_ to see my code land in React, it would have been _even more cool_ to receive official attribution for the part of the commit I wrote (the test case) via a [co-authored commit](https://blog.github.com/2018-01-29-commit-together-with-co-authors/)!

I'm not too worried about it -- having some of my code in React is reward enough! Just a thought for the next time you are able to reuse code from an outside contributor 😃
