### ISSUE TITLE
SVG import cause image crack

### ISSUE THREAD

**Issue by hui21109** [facebook/react#14166]
I have several needs to hover a button and change color of the svg path stroke/fill 

It will work perfectly most of time I use it as a component can assign a classname.
While sometimes the svg image will crack and I sure it is complete when I use it as <img src=.../>
I think it is a bug, thanks for help

FYI svg source : https://reurl.cc/8yAkX

Import {ReactComopnent as Graph } from '..../.svg'

< Graph/>

npm 6.4.1
react 16.6.0

**Comment by gaearon** [comment]
Please file this in Create React App repository with a reproducing example.
