### ISSUE TITLE
Uncaught TypeError: unmountComponentAtnode is not a function

### ISSUE THREAD

**Issue by balalaXD** [facebook/react#14169]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Uncaught TypeError: unmountComponentAtnode is not a function
**example below:**
https://codesandbox.io/s/2xmjm5owp0

**Comment by aweary** [comment]
You have a typo, it's `unmountComponentAtNode` (Node should be capitalized)
