### ISSUE TITLE
componentDidMount runs once !

### ISSUE THREAD

**Issue by sinamiandashti** [facebook/react#1416]
hi

im trying to do something always after render()

but the componentDidMount only called once after the state change and after render()

is there any way to run a method always after render()? even the state or prop change?

**Comment by Isra-ib1403846** [comment]
@jkimbo Thank you but why I cannot setState inside componentDidUpdate?

**Comment by jkimbo** [comment]
@Isra-ib1403846 if you call `setState` in `componentDidUpdate` you will cause the function to run again potentially causing an infinite loop. You can read more in the docs: https://reactjs.org/docs/react-component.html#componentdidupdate
