### ISSUE TITLE
Incorrect scheduler dependency getting installed for 16.7 alpha

### ISSUE THREAD

**Issue by zaguiini** [facebook/react#14173]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Whenever I try to use concurrent mode on React, one `Cannot read property 'didTimeout' of undefined` error is thrown.

**If the current behavior is a bug, please provide the steps to reproduce:**

1. Create a React App (`create-react-app`)
2. Update React and React DOM to the alpha version (16.7.0-alpha.0)
3. Update `index.js`:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

One error is thrown:

```
Uncaught TypeError: Cannot read property 'didTimeout' of undefined
    at performAsyncWork (react-dom.development.js:19646)
    at flushFirstCallback (scheduler.development.js:94)
    at flushWork (scheduler.development.js:201)
    at idleTick (scheduler.development.js:556)
```

**What is the expected behavior?**

To render correctly on concurrent mode.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
Chrome: 70.0.3538.77
React: 16.7.0-alpha.0
ReactDOM: 16.7.0-alpha.0
```

It doesn't work without `<StrictMode />` either.
In synchronous React, `StrictMode` works correctly.

**Comment by Bobgy** [comment]
Hi, I think it's caused by scheduler@0.11.0, I tried installing scheduler@0.10.0 manually and removing `node_modules/react-dom/node_modules/scheduler` folder, and my app can run again

**Comment by landvibe** [comment]
@Bobgy Thank you. It works for me
