### ISSUE TITLE
SetStateAction returned from useState hook dose not accept a second callback argument

### ISSUE THREAD

**Issue by cheungseol** [facebook/react#14174]
**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**
The SetStateAction returned from useState hook dose not accept a second callback argument. It cannot works like Class Componet's 'setState'  method, which receives a callback param, and can perform the callback after this setState action updates;

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/93mkr1ywpr

**What is the expected behavior?**
Hopes the SetStateAction function can receive a second callback argument, and can used like 'setState' method callback. 

I have read the official note: 

>     // this technically does accept a second argument, but it's already under a deprecation warning
>     // and it's not even released so probably better to not define it.

If instead it's working as intended, how can I perform special action after this SetStateAction called ? 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.7.0-alpha.0

**Comment by gaearon** [comment]
Is there a reason you can't `useEffect` instead? Generally it's a better solution.

**Comment by cheungseol** [comment]
> Is there a reason you can't `useEffect` instead? Generally it's a better solution.

Since I don't want to trigger callback action every time after dispatching a SetStateAction.  But 'useEffect ' might cause the effect running every time after the state changed.

**Comment by Kovensky** [comment]
Use a useRef for setting a flag saying you want the effect to run, or just do the effect directly in the function where you're calling setState.

**Comment by gaearon** [comment]
>Since I don't want to trigger callback action every time after dispatching a SetStateAction. But 'useEffect ' might cause the effect running every time after the state changed.

Can you describe a more specific use case please?

**Comment by therayess** [comment]
@gaearon 
Hi, i also faced similar issue where i needed to add a callback for when the state is set, my scenario is this:
I make an api call, after i get the response, i update a context state item, then i take the user to a new page (pushing to history), currently, without the callback, i get a warning that says:
```
Warning: Can't perform a React state update on an unmounted component.
```
Basically, i'm running a setState on a component that has been unmounted due to the page change.

Ideally, i would like to update the context (or any callback function from parent component for example), then once that process is done, run the callback that will apply the page change.

This could've been done easily with the setState(state, [callback]).

Please advise, thanks for your time!

**Comment by therayess** [comment]
I found the solution, we can actually await the set function :+1: 
Thanks

**Comment by mbohgard** [comment]
@therayess Where is it documented that the set function of useState returns a promise?

**Comment by therayess** [comment]
You are right, apologies for that, it worked for another reason, is there a way to achieve a state set callback with useState ?

**Comment by joshburgess** [comment]
Being able to pass a callback to useState would allow for greater flexibility. For example, we could implement a `dispatch` function that takes a callback to fire off post-reducer-update, like `ReasonReact.UpdateWithSideEffects` in Reason-React: https://reasonml.github.io/reason-react/docs/en/state-actions-reducer#state-update-through-reducer

```
ReasonReact.UpdateWithSideEffects(state, self => unit): update the state, **then** trigger a side-effect.
```

Right now, it's possible to implement a Redux-like architecture with an added "hook" for running effects AFTER the reducer update with the class API, Context, and this.setState's callback param, but to accomplish the same thing with react-hooks means needing to use `useRef` or `useEffect` + extra boilerplate (setting & checking flags to control when the effect is allowed to run). 

Today, in Redux-land, people use middleware libraries like redux-saga, redux-observable, redux-loop, etc. to be able to declaratively describe async effects via dispatched actions, because Redux doesn't expose an API function for running effects after a reducer update, but it's not difficult to implement this sort of functionality with the class API & setState's callback param. We could do something similar with react hooks if `useState`'s `setState` or `useReducer`'s `dispatch` accepted a thunk param describing a one-time effect we'd like to run.

This one-time, post-update effect feature could be implemented by offering different variations of "dispatch", like how Reason-React has `ReasonReact.SideEffects(self => unit)` and `ReasonReact.UpdateWithSideEffects(state, self => unit)` in addition to `ReasonReact.NoUpdate` & `ReasonReact.Update(state)`. Having these separate versions of "dispatch" instead of a single "dispatch" dynamically overloaded with optional params is nice, because it allows us to be more explicit about our intentions & the static types being passed around.

Alternatively, instead of having different variations of `dispatch`, some of which allow for this post-update effect hook, imagine a simple effect system with just a single `dispatch` function, but where your dispatched actions could contain an extra key called `effect`, either at the top-level, or, perhaps, under `meta` for Flux Standard Action users, where the value is a thunk or some other lazy async data structure we want to execute. I've personally implemented this idea using the class API & setState's callback param and found it pretty useful. If there were some way to provide a callback to `useReducer`'s `dispatch` function that had access to the dispatched action, this sort of thing could be implemented in user-land.

**Comment by Kovensky** [comment]
Untested madness that I'd rather not touch...... but it's an idea, and I have no idea if it works. But it typechecks 🤷‍♀️

```ts
import React from 'react'

function useImperativeEffectsFactory(serialized = true) {
  const [, internalSetEffect] = React.useState<Promise<void> | undefined>(undefined)
  return React.useCallback<(effect: () => Promise<void> | void) => void>(
    effect => {
      internalSetEffect(current => {
        const promise = (async () => {
          try {
            if (serialized) {
              await current
              await effect()
            } else {
              await Promise.all([current, effect()])
            }
          } finally {
            internalSetEffect(current => (current === promise ? undefined : current))
          }
        })()
        return promise
      })
    },
    [internalSetEffect]
  )
}
```

```ts
const useImperativeEffect = useImperativeEffectsFactory()
```

```ts
useImperativeEffect(() => {
  // ...
})
```

**Comment by joshburgess** [comment]
@Kovensky I just tried it out, and that code results in a `Too many re-renders. React limits the number of renders to prevent an infinite loop.` error. Might be a simple problem, not sure. Haven't tried to debug it yet.

Anyway, I'm not saying that there aren't other ways to implement the same idea with Hooks, but it does seem like a lot of hoops need to be jumped through in order to do the same thing that currently is available in the class API's `setState` just by passing an extra function in.

**Comment by basbz** [comment]
I think @joshburgess has a good point!
Having the callback would make it easier to express side effects like the way it's done in ReasonReact https://github.com/reasonml/reason-react/blob/de0803fa5784e434e3d9da374ec3e4e8a7653f12/src/ReasonReact.re/#L591
or in React ReComponent https://github.com/philipp-spiess/react-recomponent/blob/6c75e1ce99238af0db3389c25a2ca0cee5fa8207/src/re.js#L96
And would enable isolating state even more from classes or components that us it.

**Comment by malerba118** [comment]
I agree, i'd like a callback option. Or taking it one step further, I'd love to see a promise returned. That's one thing that's always irked me about setState.

**Comment by joshburgess** [comment]
For whatever it's worth, it's probably based on what `reason-react` did, but `purescript-react-basic` also went with this approach.

```
data StateUpdate props state action
  = NoUpdate
  | Update               state
  | SideEffects                (Self props state action -> Effect Unit)
  | UpdateAndSideEffects state (Self props state action -> Effect Unit)
```

https://github.com/lumihq/purescript-react-basic/blob/master/src/React/Basic.purs#L165-L169

**Comment by joshburgess** [comment]
Just posting an update here for others, as I hadn't seen it before until just now. It looks like they are already aware that people want this and have some ideas about how it might be possible.

See the *Missing APIs* section here: https://github.com/reactjs/rfcs/pull/68#issuecomment-439314884

Relevant section in a screenshot:

<img width="672" alt="screen shot 2019-01-02 at 7 55 20 pm" src="https://user-images.githubusercontent.com/5396631/50619748-18468180-0ec9-11e9-9a1e-35086c22bf7d.png">

**Comment by bebbi** [comment]
@gaearon I have this use-case which perhaps matches the issue:

    const Component = ({ extValue }) => {
      const [value, setValue] = useState(extValue)

      useEffect(() => {
        // Normally, value is changed within this Component.
        // However, whenever `extValue` updates, need to reset value to extValue.
        // As soon as flushed, run 'onExternalValueUpdate'
        setValue(extValue)
          .then(onExternalValueUpdate)
      }, [extValue] )

      // Internal updates won't trigger `onExternalValueUpdate`
      return (<Something value={value} setValue={setValue} />)
    }

**Comment by malerba118** [comment]
@bebbi Not arguing against a callback option as it would be a simpler solution, but I believe you could accomplish this by tracking extVal's state in the child. 

```jsx
const Parent = props => {
  let [extVal, setExtVal] = useState(0);

  useEffect(() => {
    setTimeout(() => {
      setExtVal(prevVal => prevVal + 1);
    }, 5000);
  }, []);

  return <Child extVal={extVal} />;
};

const Child = props => {
  let [state, setState] = useState({
    val: props.extVal,
    extVal: props.extVal
  });

  useEffect(
    () => {
      setState({
        val: props.extVal,
        extVal: props.extVal
      });
    },
    [props.extVal]
  );

  useEffect(
    () => {
      // We know state.val is also done setting
      console.log(state);
    },
    [state.extVal]
  );

  return <div>{state.val}</div>;
};
```

https://codesandbox.io/s/xjowmro8yz

**Comment by gaearon** [comment]
@bebbi Sorry, it's not clear *why* you need it. A full codesandbox showing the full use case (including why a parent needs such a callback) would be useful.

**Comment by davidalekna** [comment]
Hi @gaearon, following method example comes from render props class component. I'd like to refactor it with react hooks. All of the methods on this class component has a callback when on setState is called. It passes a currently affected state so that the end user could do something if that action takes place.

```
selectAll = ({
  type = DataBrowser.stateChangeTypes.selectAll,
  items,
} = {}) => {
  this.internalSetState(
    {
      type,
      selectAllCheckboxState: true,
      checked: items,
    },
    () => this.props.onSelectAll(this.getState().checked),
  );
};
``` 

and here is the internalSetState function

```
  internalSetState = (changes, callback = () => {}) => {
    let allChanges;
    this.setState(
      currentState => {
        const combinedState = this.getState(currentState);
        return [changes]
          .map(c => (typeof c === 'function' ? c(currentState) : c))
          .map(c => {
            allChanges = this.props.stateReducer(combinedState, c) || {};
            return allChanges;
          })
          .map(({ type: ignoredType, ...onlyChanges }) => onlyChanges)
          .map(c => {
            return Object.keys(combinedState).reduce((newChanges, stateKey) => {
              if (!this.isControlledProp(stateKey)) {
                newChanges[stateKey] = c.hasOwnProperty(stateKey)
                  ? c[stateKey]
                  : combinedState[stateKey];
              }
              return newChanges;
            }, {});
          })
          .map(c => (Object.keys(c || {}).length ? c : null))[0];
      },
      () => {
        this.props.onStateChange(allChanges, this.state);
        callback();
      },
    );
  };
```

It would be kinda hard to replicate all this on a codesandbox but if nescessary I could produce something?

Thanks

**Comment by bebbi** [comment]
@gaearon Here is a [fiddle example](https://jsfiddle.net/kyhr1og3/2/) of what I was trying to simplify.

**Comment by malerba118** [comment]
Not necessarily recommending this approach as it's possibly an anti-pattern, but for the people wanting this functionality, I suggest something like this as a solution (https://codesandbox.io/s/qq672lp6xq):

```jsx
const useStateWithPromise = defaultVal => {
  let [state, setState] = useState({
    value: defaultVal,
    resolve: () => {}
  });

  useEffect(
    () => {
      state.resolve(state.value);
    },
    [state]
  );

  return [
    state.value,
    updater => {
      return new Promise(resolve => {
        setState(prevState => {
          let nextVal = updater;
          if (typeof updater === "function") {
            nextVal = updater(prevState.value);
          }
          return {
            value: nextVal,
            resolve
          };
        });
      });
    }
  ];
};

const App = props => {
  let [state, setState] = useStateWithPromise(0);

  const increment = () => {
    setState(prevState => prevState + 1).then(window.alert);
  };

  return (
    <div>
      <p>{state}</p>
      <button onClick={increment}>Increment</button>
    </div>
  );
};
```

But I'd also be curious about the merits of this as an alternative solution (https://codesandbox.io/s/01nnppoly0): 

```jsx
const Parent = props => {
  let [val, setVal] = useState(0);

  useEffect(() => {
    setTimeout(() => {
      setVal(prevVal => prevVal + 1);
    }, 5000);
  }, []);

  return <Child defaultVal={val} />;
};

const Child = props => {
  let [state, setState] = useState({
    value: props.defaultVal,
    metadata: {
      reasonForUpdate: "INITIAL_VALUE"
    }
  });

  useEffect(
    () => {
      setState({
        value: props.defaultVal,
        metadata: {
          reasonForUpdate: "DEFAULT_VALUE_CHANGE"
        }
      });
    },
    [props.defaultVal]
  );

  useEffect(
    () => {
      switch (state.metadata.reasonForUpdate) {
        case "DEFAULT_VALUE_CHANGE":
          // Do something after value change to default value update
          window.alert("DEFAULT_VALUE_CHANGE: " + state.value);
          break;
        case "INTERNAL_VALUE_CHANGE":
          // Do something after value change due to increment button click
          window.alert("INTERNAL_VALUE_CHANGE: " + state.value);
          break;
        case "INITIAL_VALUE":
          // Do something after state initialization
          window.alert("INITIAL_VALUE: " + state.value);
          break;
        default:
        // Any other reason for update
      }
    },
    [state.value]
  );

  const increment = () => {
    setState(prevState => ({
      value: prevState.value + 1,
      metadata: {
        reasonForUpdate: "INTERNAL_VALUE_CHANGE"
      }
    }));
  };

  return (
    <div>
      <p>{state.value}</p>
      <button onClick={increment}>Increment</button>
    </div>
  );
};
```

**Comment by revskill10** [comment]
Here's my solution
```js
import { useState } from 'react'
const useStateWithEffects = (props, onValueChanged) => {
  let [value, setValue] = useState(props)

  const setState = (newValue) => {
    value = newValue
    setValue(value)
    onValueChanged(value)
  }

  return [value, setState]
}

export default useStateWithEffects
```

**Comment by ulrichb** [comment]
So ... are there plans to add a callback-parameter (or even better returning a Promise) within React?

**Comment by Tahseenm** [comment]
## Solution
```jsx
import React from 'react'

/* :: (any, ?Function) -> Array<any> */
export const useState = (initialState, callback = () => { }) => {
  const [ state, setState ] = React.useState(initialState)
  const totalCalls = React.useRef(0)

  React.useEffect(() => {
    if (totalCalls.current < 1) {
      totalCalls.current += 1
      return
    }

    callback(state)
  }, [ state ])

  return [ state, setState ]
}
```

## Usage
```jsx
const App = () => {
  const onCountChange = count => {
    console.log('Count changed', count)
  }

  const [count, setCount] = useState(10, onCountChange)

  return (
    <>
      <h1>Count: {count}</h1>
      <button onClick={count => setCount(count + 1)}>+</button>
    </>
  )
}
```

**Comment by Tahseenm** [comment]
@gaearon `useEffect()` runs after every render AFAIK. With the callback I needed it to run only when the state changed.

**Comment by zenVentzi** [comment]
@Tahseenm your solution provides a "global" callback for all setCount() calls. I think some people need a solution where they can provide a custom callback for each and every setCount() call. Which allows greater flexibility

**Comment by bebbi** [comment]
@Tahseenm 

> `useEffect()` runs after every render 

[Here](https://overreacted.io/a-complete-guide-to-useeffect/) is a very good explanation for `useEffect()` and general hooks logic - by Dan. I think it should be mandated as a pre-read for everyone posting in this thread (including me).

**Comment by Tahseenm** [comment]
@zenVentzi

## `useState` with Global + `setState` callback

```jsx
/* :: (any, ?Function) -> Array<any> */
const useState = (initialState, callback = () => {}) => {
  const [state, setState] = React.useState(initialState);

  /** @NOTE: Handle callback to run for every state change */
  const totalCalls = React.useRef(0);
  React.useEffect(
    () => {
      if (totalCalls.current < 1) {
        totalCalls.current += 1;
        return;
      }

      callback(state);
    },
    [state]
  );

  /** @NOTE: Handle setState callback */
  const lookup = React.useRef([]);
  React.useEffect(
    () => {
      const entry = lookup.current.find(([stateSet]) => state === stateSet);

      if (Array.isArray(entry)) {
        const [, callback] = entry;
        callback(state);
      }

      lookup.current = [];
    },
    [state]
  );
  const $setState = (nextStateOrGetter, callback) => {
    setState(nextStateOrGetter);

    if (typeof callback !== "function") {
      return;
    }

    const nextState =
      typeof nextStateOrGetter === "function"
        ? nextStateOrGetter(state)
        : nextStateOrGetter;
    lookup.current.push([nextState, callback]);
  };

  return [state, $setState];
};
```

## Usage
```jsx
const App = () => {
  const onCountChange = count => {
    console.log("Count changed", count);
  };

  const [count, setCount] = useState(10, onCountChange);

  const decrement = () => setCount(count - 1, () => console.log("dec"));
  const increment = () => setCount(count + 1, () => console.log("inc"));

  return (
    <>
      <h1>Count: {count}</h1>
      <button onClick={decrement}>-</button>
      <button onClick={increment}>+</button>
    </>
  );
};
```

**Comment by Tahseenm** [comment]
@bebbi Thanks will check it out. Not sure if we should make it a mandatory pre-read for this thread 😆

**Comment by jhamPac** [comment]
Thanks @bebbi, but I think most of us legitimately just need a function to run after a state change so we can do something with the most recent state values. For example, how can I make an API call after updating state and guarantee that its the latest values? Before it was like the following.

`this.setState({
    name: 'FakeMan',
}, () => somefakeCall(this.state.name))
`

Currently with useState that is not possible.

**Comment by MohamedLamineAllal** [comment]
@gaearon 
Hi Dan!
> Is there a reason you can't `useEffect` instead? Generally it's a better solution.

Can you explain, why it's a better solution? Also why it is not implemented ? (as for my understanding, it should be just one call at the right moment, when the state is updated. At least we can do it when useEffect is triggered. Typically using a promise, which will be resolved at the right moment).

And what do you think about the statement 'having the callback (||promise). Add a lot of flexibility.' ?
Thank you a lot.

**Comment by MohamedLamineAllal** [comment]
Here a pattern to mimic the after update behavior. It's short and clean. 

class that help with that
```
class UpdateHandler {
    queue =[];
    
    flash(states) {
        while(this.queue.length > 0) {
            this.queue.shift()(states);
        }
    }

    wait () {
        return new Promsie (resolve => {
            this.queue.push(resolve);
        });
    }
}
```

# use:

```
 const update = new UpdateHandler();

in hook
```
        useEffect(() => {
		update.flash(settings);
	}, [settings])
```

in some function where we use setState
```
async function someFunc(value, setState) {
     setState(value);
     let newState = await update.wait(); // whatever was passed to the flash method
     // use it as you like
}
```

What do you think ?

**Comment by limpt** [comment]
> @bebbi Sorry, it's not clear _why_ you need it. A full codesandbox showing the full use case (including why a parent needs such a callback) would be useful.

https://codesandbox.io/s/objective-pare-42mn4

A callback for setState would be useful in this case because I don't want the calendar field to be set every time the text input field update. 
I could use the formatted value to set the calendar field but not sure if there's a better way.

**Comment by SylarRuby** [comment]
What's wrong with this:

```
const [increment, setIncrement] = useState(0);
<button onClick={() => setIncrement(increment + 1)}>Num is: {increment}</button>
```

**Comment by kaung8khant** [comment]
My solution, this is also work for dispatch =>
`import React, { useState } from "react";
import "../../assets/css/custom.css";

const CallBackTest = () => {
  const [trueFalse, setTrueFalse] = useState(false);

  const callBacksetState = async (data, callBackFunc) => {
    await setTrueFalse(data);
    callBackFunc(data);
  };

  const func = data => {
    alert(data + " " + trueFalse);
  };

  //pass function func to callBacksetState function
  return <h1 onClick={() => callBacksetState(true, func)}>Test</h1>;
};

export default CallBackTest;
`

**Comment by kaung8khant** [comment]
My solution 
This is also work for `dispatch`, but state value is not updated yet on callback function.
```javascript
import React, { useState } from "react";
import "../../assets/css/custom.css";

const CallBackTest = () => {
  const [trueFalse, setTrueFalse] = useState(false);

  const callBacksetState = async (data, callBackFunc) => {
    await setTrueFalse(data);
    callBackFunc(data);
  };

  const func = data => {
    alert(data + " " + trueFalse);
  };

  //pass function func to callBacksetState function
  return  <button onClick={() => callBacksetState(true, func)}>Click Me!</button>;
};

export default CallBackTest;
```

**Comment by arascan35** [comment]
Simple solution for deleting element from state array.

```javascript
import React from 'react';

function DeleteFromArray() {
  const [emails, setEmails] = React.useState([]);
  const handleDelete = index => {
    let tempArr = emails;
    tempArr.splice(index, 1);
    setEmails([...tempArr]);
  };
  return <button onClick={() => handleDelete(index)}> Delete </button>;
}

export default DeleteFromArray
```

**Comment by verbart** [comment]
@arascan35 
```jsx
import React from 'react';

export const DeleteFromArray = ({ deletionIndex }) => {
  const [ emails, setEmails ] = React.useState([]);

  const handleDelete = () =>  {
    setEmails((emails) => emails.filter((email, index) => index !== deletionIndex));
  };

  return <button onClick={handleDelete}>Delete</button>;
};
```

**Comment by giorgi-m** [comment]
> Thanks @bebbi, but I think most of us legitimately just need a function to run after a state change so we can do something with the most recent state values. For example, how can I make an API call after updating state and guarantee that its the latest values? Before it was like the following.
> 
> `this.setState({ name: 'FakeMan', }, () => somefakeCall(this.state.name)) `
> 
> Currently with useState that is not possible. In this scenario useEffect won't quite work. I don't want to make the API call on the initial render and I might not necessary want to make the call every time the name state changes, I just want to make this call in a very specific instance.

@jhamPac 
Good point as in below snippet: I want `console.log("Fetch")` to be written when btn1 is clicked and _not_ when btn2. With `useEffect `it will be cumbersome to implement such scenario.
@gaearon 

```
class App extends React.Component {
  state = { flag: false };
  render() {
    return (
      <div className="App">
        <button
          onClick={
            (() => {
              this.setState(ps => ({ flag: !ps.flag }));
            },
            () => {
              console.log("Fetch");
            })
          }
        >
          btn1
        </button>
        <button
          onClick={() => {
            this.setState(ps => ({ flag: !ps.flag }));
          }}
        >
          btn2
        </button>
      </div>
    );
  }
}
```

**Comment by zmhweb** [comment]
> Not necessarily recommending this approach as it's possibly an anti-pattern, but for the people wanting this functionality, I suggest something like this as a solution (https://codesandbox.io/s/qq672lp6xq):
> 
> ```js-jsx
> const useStateWithPromise = defaultVal => {
>   let [state, setState] = useState({
>     value: defaultVal,
>     resolve: () => {}
>   });
> 
>   useEffect(
>     () => {
>       state.resolve(state.value);
>     },
>     [state]
>   );
> 
>   return [
>     state.value,
>     updater => {
>       return new Promise(resolve => {
>         setState(prevState => {
>           let nextVal = updater;
>           if (typeof updater === "function") {
>             nextVal = updater(prevState.value);
>           }
>           return {
>             value: nextVal,
>             resolve
>           };
>         });
>       });
>     }
>   ];
> };
> 
> const App = props => {
>   let [state, setState] = useStateWithPromise(0);
> 
>   const increment = () => {
>     setState(prevState => prevState + 1).then(window.alert);
>   };
> 
>   return (
>     <div>
>       <p>{state}</p>
>       <button onClick={increment}>Increment</button>
>     </div>
>   );
> };
> ```

`function useStateWithPromise<T>(defaultVal: T) {
    let [state, setState] = useState({
        value: defaultVal,
        resolve: (value: T) => { }
    });

    useEffect(() => {
        state.resolve(state.value);
    },
        [state]
    );

    return [
        state.value,
        (updater: (value: T) => any) => {
            return new Promise(resolve => {
                setState((prevState) => {
                    let nextVal = updater;
                    if (typeof updater === "function") {
                        nextVal = updater(prevState.value);
                    }
                    return {
                        value: nextVal,
                        resolve
                    };
                });
            });
        }
    ];
};`

![image](https://user-images.githubusercontent.com/16442336/70372463-5094e200-191a-11ea-97a1-0be996658599.png)

How do I use generics

**Comment by zmhweb** [comment]
> Not necessarily recommending this approach as it's possibly an anti-pattern, but for the people wanting this functionality, I suggest something like this as a solution (https://codesandbox.io/s/qq672lp6xq):
> 
> ```js-jsx
> const useStateWithPromise = defaultVal => {
>   let [state, setState] = useState({
>     value: defaultVal,
>     resolve: () => {}
>   });
> 
>   useEffect(
>     () => {
>       state.resolve(state.value);
>     },
>     [state]
>   );
> 
>   return [
>     state.value,
>     updater => {
>       return new Promise(resolve => {
>         setState(prevState => {
>           let nextVal = updater;
>           if (typeof updater === "function") {
>             nextVal = updater(prevState.value);
>           }
>           return {
>             value: nextVal,
>             resolve
>           };
>         });
>       });
>     }
>   ];
> };
> 
> const App = props => {
>   let [state, setState] = useStateWithPromise(0);
> 
>   const increment = () => {
>     setState(prevState => prevState + 1).then(window.alert);
>   };
> 
>   return (
>     <div>
>       <p>{state}</p>
>       <button onClick={increment}>Increment</button>
>     </div>
>   );
> };
> ```

```

function useStateWithPromise<T>(defaultVal: T) {
    let [state, setState] = useState({
        value: defaultVal,
        resolve: (value: T) => { }
    });

    useEffect(() => {
        state.resolve(state.value);
    },
        [state]
    );

    return [
        state.value,
        (updater: (value: T) => any) => {
            return new Promise(resolve => {
                setState((prevState) => {
                    let nextVal = updater;
                    if (typeof updater === "function") {
                        nextVal = updater(prevState.value);
                    }
                    return {
                        value: nextVal,
                        resolve
                    };
                });
            });
        }
    ];
};


```
![image](https://user-images.githubusercontent.com/16442336/70372504-e3358100-191a-11ea-951b-ab38540934c6.png)


How do I use generics?

**Comment by hnsylitao** [comment]
> > Not necessarily recommending this approach as it's possibly an anti-pattern, but for the people wanting this functionality, I suggest something like this as a solution (https://codesandbox.io/s/qq672lp6xq):
> > ```
> > const useStateWithPromise = defaultVal => {
> >   let [state, setState] = useState({
> >     value: defaultVal,
> >     resolve: () => {}
> >   });
> > 
> >   useEffect(
> >     () => {
> >       state.resolve(state.value);
> >     },
> >     [state]
> >   );
> > 
> >   return [
> >     state.value,
> >     updater => {
> >       return new Promise(resolve => {
> >         setState(prevState => {
> >           let nextVal = updater;
> >           if (typeof updater === "function") {
> >             nextVal = updater(prevState.value);
> >           }
> >           return {
> >             value: nextVal,
> >             resolve
> >           };
> >         });
> >       });
> >     }
> >   ];
> > };
> > 
> > const App = props => {
> >   let [state, setState] = useStateWithPromise(0);
> > 
> >   const increment = () => {
> >     setState(prevState => prevState + 1).then(window.alert);
> >   };
> > 
> >   return (
> >     <div>
> >       <p>{state}</p>
> >       <button onClick={increment}>Increment</button>
> >     </div>
> >   );
> > };
> > ```
> 
> ```
> 
> function useStateWithPromise<T>(defaultVal: T) {
>     let [state, setState] = useState({
>         value: defaultVal,
>         resolve: (value: T) => { }
>     });
> 
>     useEffect(() => {
>         state.resolve(state.value);
>     },
>         [state]
>     );
> 
>     return [
>         state.value,
>         (updater: (value: T) => any) => {
>             return new Promise(resolve => {
>                 setState((prevState) => {
>                     let nextVal = updater;
>                     if (typeof updater === "function") {
>                         nextVal = updater(prevState.value);
>                     }
>                     return {
>                         value: nextVal,
>                         resolve
>                     };
>                 });
>             });
>         }
>     ];
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/16442336/70372504-e3358100-191a-11ea-951b-ab38540934c6.png)
> 
> How do I use generics?

Good reference

**Comment by philanz** [comment]
`import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";

const App = () => {
  const [state, setState] = useState({
    value: "",
    callback: () => {}
  });

  useEffect(() => {
    state.callback(state);
  }, [state]);

  const clickAction1 = () => {
    setState({
      ...state,
      value: "Button 1",
      callback: newState => afterValueSet(`${newState.value} Clicked !!!!`)
    });
  };

  const clickAction2 = () => {
    setState({
      ...state,
      value: "Button 2",
      callback: newState => console.log(`${newState.value} Clicked !!!!`)
    });
  };

  const clickAction3 = () => {
    setState({ ...state, value: "Button 3", callback: () => {} });
  };

  const afterValueSet = value => console.log(value);

  return (
    <div>
      {state.value}
      <button onClick={clickAction1}>btn1</button>
      <button onClick={clickAction2}>btn2</button>
      <button onClick={clickAction3}>btn3</button>
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));
`

Will this workout ?

**Comment by ryanhornberger** [comment]
@gaearon our company ran into this issue today attempting to upgrade (to hooks) a library that employed the callback on setState. 

After reading this thread we looked through our code for every instance where we were using it. 

We concluded that in nearly every case we were simply (and likely incorrectly) using this to ensure the form only submitted once and could not submit again until after an API call was complete.

Our solution to this problem looks similar to the solution @Tahseenm submitted but we gave it a more appropriate name and usage. This might be useful to build right in to react.

The entire solution follows:

`
import { useState, useEffect, useCallback } from "react"

// React Hook - useAsyncCallbackWithSemaphore
//
// Use this hook to create a callback capable of triggering an async operation
// (such as an api call ) that will only be triggered once.
//
// You will receive in return an array that contains
//    - a callback function
//
//        name this function anything you want, and pass it to your "onClick"
//
//    - a state variable containing the semaphore status
//
//        name this variable anything you want, use it to disable inputs and
//        signal to the user that their command is received and processing.
//
// Example:
//
//    export default (props) => {
//      const [userName, setUserName] = useState('')
//      const [saveUserName, isSavingUsername] = useCallbackWithSemaphore(
//          async () => {
//              try {
//                  await mockApiCall(userName)
//              }
//              catch(e) {
//                  //TODO handle errors
//              }
//          },
//          [userName]
//      )
//
//      return (
//          <div>
//              <MockUsernameForm
//                  value={userName}
//                  onChange={setUserName}
//                  disabled={isSavingUsername}
//              />
//              <button
//                  onClick={saveUserName}
//                  disabled={isSavingUsername}
//              >
//                  Save
//              </button>
//          </div>
//      )
//    }
//

const useAsyncCallbackWithSemaphore = (callOnceFn, watchingVars) => {
    // store the semaphore in state
    const [semaphore, setSemaphore] = useState(false)

    // use the state system to delay triggering the async function until after
    // the UI has had a chance to disable inputs.
    //
    // also only allow this call to happen on the first try if the user presses
    // the button multiple times
    useEffect(() => {
        //if semaphore > 1 this is a repeat call that should be ignored
        if(semaphore === 1) {
            // we need to await the async function so that we can remove the
            // semphore on completion
            (async () => {
                await callOnceFn()
                // async function complete. Remove semaphore
                setSemaphore(false)
            })()
        }
    }, [semaphore]) // this useEffect will only trigger if the semaphore changes

    return [
        // result[0] = a callback function that can be used in "onClick" or
        // other triggers
        useCallback(() => {
            setSemaphore(semaphore + 1)
        }, watchingVars),
        // result[1] = a boolean indicating if the semaphore has been triggered
        // to be used by rendering components down-stream
        (semaphore > 0)
    ]
}

export default useAsyncCallbackWithSemaphore
`

**Comment by lishichao1002** [comment]
```
type Action<T> = (preState?: T) => T;
type Dispatch<T> = (state: T | Action<T>) => Promise<T>;

function useMyState<T>(initState: T): [T, Dispatch<T>] {
    const [state, setState] = useState(initState);
    const [{ __state, __resolve }, __setState] = useState<{ __state?: T, __resolve?: (t: T) => void }>({});

    const mySetState: Dispatch<T> = (state: T | Action<T>) => {
        return new Promise<T>((resolve) => {
            if (typeof state === 'function') {
                setState((preState: T) => {
                    const __state = (state as Action<T>)(preState);
                    __setState({
                        __state,
                        __resolve: resolve
                    });
                    return __state;
                });
            } else {
                const __state = state;
                __setState({
                    __state,
                    __resolve: resolve
                });
                setState(__state);
            }
        });
    };

    useEffect(() => {
        if (__state && __resolve) {
            __resolve(__state);
            __setState({});
        }
    }, [state]);

    return [state, mySetState];
}

function App() {
    const [state, setState] = useMyState(0);

    useEffect(() => {
        console.warn('before', state);
        setState(1).then((state) => {
            console.warn('after', state);
        });
    }, []);

    return (
        <div className="App"></div>
    );
}
```

**Comment by jernchr11** [comment]
Is there a solution for this yet?

**Comment by emrahaydemir** [comment]
Unfortunately, you should use `setState`. `useState` is not working with second parameter.

**Comment by KrisLau** [comment]
@gaearon My use case for this:
```

```
