### ISSUE TITLE
can i check which component triggers useEffect?

### ISSUE THREAD

**Issue by akinozgen** [facebook/react#14179]
**Do you want to request a *feature* or report a *bug*?**
Feature (maybe i'm not sure)

**What is the current behavior?**
Can't find a way to check "which component/function/method that updates state" from ***useEffect***

**What is the expected behavior?**

I have a **range slider input** that takes **progress state** as value. That **progress state** updated from `<audio>:ontimeupdate()` event handler.

I need to arrange range that **slider** to update **progress state**. I'm trying to make this with `useEffect` but when `<audio>:ontimeupdate()` runs, `useEffect` gets triggered and **slider** got stuck.

Can i check what component, function or method changes state and get it from `useEffect`?

**Versions:**
React: 16.7.0-alpha.0
ReactDOM: 16.7.0-alpha.0

**Comment by gaearon** [comment]
Can you provide a demo please? Like in CodeSandbox.

**Comment by akinozgen** [comment]
sure 

https://codesandbox.io/s/v3p3x62y05

audio-ontimeupdate: src/components/Controls/index.js:19
useEffect: src/components/Controls/index.js:119
slider update: src/components/Meta/index.js:11

**Comment by alex-wilmer** [comment]
I can't actually play anything in your sandbox always getting

```
TypeError
Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
eval
/src/components/Controls/index.js:120:6
  117 | }
  118 | 
  119 | useEffect(function () {
> 120 |     window.audioPlayer.currentTime = parseFloat(
      |    ^
  121 |       Math.floor((window.audioPlayer.duration || 0) / 100) * state.progress
  122 |     );
  123 |   },
```

**Comment by akinozgen** [comment]
> I can't actually play anything in your sandbox always getting
> 
> ```
> TypeError
> Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
> eval
> /src/components/Controls/index.js:120:6
>   117 | }
>   118 | 
>   119 | useEffect(function () {
> > 120 |     window.audioPlayer.currentTime = parseFloat(
>       |    ^
>   121 |       Math.floor((window.audioPlayer.duration || 0) / 100) * state.progress
>   122 |     );
>   123 |   },
> ```

should be fixed now

**Comment by gaearon** [comment]
I don't really understand this report. Can you provide an exact sequence of steps to reproduce, what you expect, and what happens?
