### ISSUE TITLE
Reusing refs

### ISSUE THREAD

**Issue by webdeb** [facebook/react#14187]
There are some jquery-like, DOM-based libraries that depend on a specific DOM structure. Lets say an image slider, which has the items-list and controls.

```
componendDidMount() {
   $('#my-slider').slider.init()
}

<div id="my-slider" className="slider">
  <ul className="slider-list">{items.map(item =>
     <li className="slider-item">{item}</li>
  )}
  <div className="slider-controls" />
</div>
```

Note the `slider-controls` div is completely empty, this will be generated by the `slider` lib during initialisation in `componentDidMount`

The structure is closed, and you cannot just take the `slider-controls` and put them at another place, the `$.slider()` lib would not work. But I found another technique how to accomplish this, by using `refs`

The structure became:

```
controls = React.createRef()
componentDidMount = () => {
  $('#my-slider').slider.init()
  this.forceUpdate();
}
<div className="page">
  <div id="my-slider">
    <ul ... />
    <div className="hide"> // hide this controls
      <div ref={this.controls} className="slider-controls" />
    </div>
  </div>
  { this.controls.current ? <div
        className="reuse-controls-somewhere-else"
        dangerouslySetInnerHTML={{
          __html: this.controls.current.innerHTML
        }}
    /> : null
  }
</div>
```

This stuff works, its great, but I thought maybe there is a better technique to reuse `refs`? If so, I could't find anything in the docs, so maybe it would be a good idea to fill the gap.

Thanks!

**Comment by webdeb** [comment]
@gaearon sure, I know this page, but my question was how I could maybe avoid

```
dangerouslySetInnerHTML={{__html: this.someRef.current.innerHTML }}
```
when I have to place it in some at some other place. Don't know if thats something that others look for, but something like 
```
<div>{this.someRef.mirror()}</div> 
```
would be much cleaner.

**Comment by gaearon** [comment]
It doesn't really have the same semantics (e.g. input state won't be preserved) so adding something like this to React would be misleading.

**Comment by webdeb** [comment]
I see, then I'll keep this small and dirty workaround as a secret :)
