### ISSUE TITLE
Hooks: reducer + useEffect

### ISSUE THREAD

**Issue by babloo80** [facebook/react#14185]
Using the example at https://reactjs.org/docs/hooks-reference.html#usereducer
when I try to add 
```javascript 
useEffect( () => {
  console.log('state changed')
}, [state])
```
And if the code ends up calling `action.type` to the default-action (which is return the previous state), the above `effect` is still executed. Is this a desired behavior?

**Do you want to request a *feature* or report a *bug*?**
Possibly a bug?

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
When a reducer retains the previous state and the state is used in `useEffect`, it should not trigger this as state change.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.7.0-alpha.0

**Comment by markerikson** [comment]
I would say yes, this is intended behavior.

It's similar to the standard Redux store behavior, which looks like:

```js
function createStore(reducer) {
    var state;
    var listeners = []

    function dispatch(action) {
        state = reducer(state, action)
        listeners.forEach(listener => listener())
    }
}
```

Notice that it _always_ runs _all_ the subscriber callbacks, and doesn't check whether or not the saved state value actually changed.  It's the UI layer's job (ie, React-Redux's `connect` ) to get the current state and do some kind of diff to determine if anything meaningful changed.

In this case, the built-in behavior is that calling `setState()` or `setReducer()` will _always_ trigger a re-render, regardless of whether the value provided to `useState` or the value returned from the reducer have actually changed at all.  And, from there, the default behavior of `useEffect()` is that it will re-run after _every_ render unless you provide the "values to watch" array as an argument.

**Comment by gaearon** [comment]
>And, from there, the default behavior of useEffect() is that it will re-run after every render unless you provide the "values to watch" array as an argument.

The posted did provide a second argument though?

**Comment by markerikson** [comment]
derp!  Didn't read carefully enough, sorry!

In that case, I'm not sure what's going on - it might be a bug after all.

**Comment by gaearon** [comment]
This needs a reproducing example.

**Comment by bartlangelaan** [comment]
I couldn't reproduce this. 

[![Edit facebook/react#14185](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3q621r0xvq)

When pressing the 'default' button, the _useEffect_ never runs. When pressing the 'reset' button, the _useEffect_ always runs if that wasn't the latest button clicked. 

This is behaving exactly as intended, I believe.
