### ISSUE TITLE
Context Provider "value" prop not honored by consumer on initial render

### ISSUE THREAD

**Issue by dlombardi** [facebook/react#14196]
**Do you want to request a *feature* or report a *bug*?**
Bug and/or feature

**What is the current behavior?**
Currently I am trying to migrate from Redux to Context for a set of config values passed to many presentational components. 

The thing is, I still want to leverage selectors to pull the values from redux but save myself the trouble of handing down the config object through the tree.  I'm creating context with a default value of an empty object because I obviously cannot create the Context within a component instance to grab the values from mapStateToProps.

In a high up component I am importing the Context and am providing the config value object from mapStateToProps through as the value of the Context.Provider in the render method.  The current behavior is that the Consumer is using the default value (empty object) for the first render instead of the value passed from redux.  This is bad because the consumers expect the object to have properties that aren't there. 

The issue I am seeing is that the value prop on Context.Provider isn't being honored on the consumer's initial render.  

**What is the expected behavior?**
The value prop of Context.Provider is honored by the consumers on initial render

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React Native
React 16.3.1

**Comment by gaearon** [comment]
Please provide a minimal reproducing case.

**Comment by dlombardi** [comment]
Could not reproduce problem in a code sandbox.  Sorry for the noise.
