### ISSUE TITLE
Page flickering with injecting styles in useEffect

### ISSUE THREAD

**Issue by budarin** [facebook/react#14193]
**Do you want to request a *feature* or report a *bug*?**
It's nither feature nor a bug

**What is the current behavior?**
When I use useEffect for including styles onto a page (with style-loader/usable) - page is flickering.
Such behaviour have not been seen when I used injecting styles in ComponentWillMount handler

**What is the expected behavior?**
Render a page without visual flickering content

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React - 16.7.0-alpha.0
browser - any
OS - any

Declare hook
```js
import { useEffect } from 'react';

const useStyles = css => {
    useEffect(() => {
        css.forEach(item => item.use());

        return () => css.forEach(item => item.unuse());
    }, []);

    return css.reduce((acc: object, item) => (acc = Object.assign({}, acc, item.locals)), {}) as any;
};

export default useStyles;
```
Using hook
```js
import React from 'react';
import useStyles from '../hooks/useStyles';

import AppLayout from '../components/AppLayout';

import appCSS from './app.css';

const App = () => {
    useStyles([appCSS]);

    return <AppLayout />;
};

export default App;
```
rendering is going from the deepest component in component tree - so the styles begin applying after rendering the whole component tree.

Using 
```js
componentWillMount() {
   css.use();
}
```
did not lead to such deffects

**Comment by Kovensky** [comment]
This is the kind of thing that needs to be done with `useLayoutEffect`; `useEffect` will intentionally wait until _after_ the browser has painted to do its changes after the user can see the current render's result.

If you need something that will affect the current render's result you need `useLayoutEffect`.

**Comment by budarin** [comment]
@Kovensky 
thanks!
it works!
