### ISSUE TITLE
useEffect unmount is only triggered after two renders

### ISSUE THREAD

**Issue by sw-yx** [facebook/react#14206]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

This:

```js
function GreetingFunction(props) {
  useEffect(() => () => console.log('cleanup', props))
  return <h1>Function</h1>
}
function render() {
  console.log('render func with 1')
  ReactDOM.render(<GreetingFunction name="1" />, funcRoot)
  console.log('rerender func with new props with 2')
  ReactDOM.render(<GreetingFunction name="2" />, funcRoot)
  console.log('rerender func with new props with 3')
  ReactDOM.render(<GreetingFunction name="3" />, funcRoot)
  console.log('rerender func with new props with 4')
  ReactDOM.render(<GreetingFunction name="4" />, funcRoot)
  console.log('rerender func with new props with 5')
  ReactDOM.render(<GreetingFunction name="5" />, funcRoot)
  console.log('rerender func with new props with 6')
  ReactDOM.render(<GreetingFunction name="6" />, funcRoot)
  console.log('unmount func')
  ReactDOM.render(null, funcRoot)
}
```

Generates this:

```bash  
render func with 1
rerender func with new props with 2
rerender func with new props with 3
cleanup {name: "1"}
rerender func with new props with 4
cleanup {name: "2"}
rerender func with new props with 5
cleanup {name: "3"}
rerender func with new props with 6
cleanup {name: "4"}
unmount func
cleanup {name: "5"}
cleanup {name: "6"}
```

To better illustrate the problem, i drew some red boxes:

![image](https://user-images.githubusercontent.com/6764957/48381919-570f4680-e693-11e8-88eb-942b1e3a77b9.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/04zzv9nxl

**What is the expected behavior?**

every rerender should trigger an unmount of the previous render's effect

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.7.0-alpha

**Comment by sw-yx** [comment]
sophie says its not a bug - https://twitter.com/sophiebits/status/1062147433034002439?s=21 will leave it to yall if you need to confirm or just close. programming testing like this is really not something i have any experience with 😂

**Comment by gaearon** [comment]
Yeah that seems legit because effects are deferred. So normally you'd expect them to fire later, but your next `render` call forces the previous effect to be flushed early.

Your tweet seemed like a bug because you said there's always "two at the same time". But that's not the case (at least looking at this sandbox: https://codesandbox.io/s/nnj039p27p). If we add more logging it'll make sense:

```
render func with 1
rerender func with new props with 2

effect {name: "1"}

rerender func with new props with 3

cleanup {name: "1"}
effect {name: "2"}

rerender func with new props with 4

cleanup {name: "2"}
effect {name: "3"}

rerender func with new props with 5

cleanup {name: "3"}
effect {name: "4"}

rerender func with new props with 6

cleanup {name: "4"}
effect {name: "5"}

unmount func

cleanup {name: "5"}
effect {name: "6"}
cleanup {name: "6"}
```

There's always at most one active effect. But it lags behind rendering because effects are deferred. Re-rendering forces the previous effect to flush earlier.
