### ISSUE TITLE
react@16.6.2 No matching version found for scheduler@^16.6.2

### ISSUE THREAD

**Issue by imsobear** [facebook/react#14208]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```bash
➜  npm install react@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for scheduler@^16.6.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'react'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobear/.npm/_logs/2018-11-13T02_57_46_814Z-debug.log
```

![image](https://user-images.githubusercontent.com/2505411/48388173-6514a400-e733-11e8-81c9-fc6069d6d188.png)

![image](https://user-images.githubusercontent.com/2505411/48388180-6ba31b80-e733-11e8-9501-06ff0d8eb958.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@16.6.2

**Comment by janryWang** [comment]
+1

**Comment by heiniuhaha** [comment]
+1

**Comment by ssfxz** [comment]
+1

**Comment by weepy3641** [comment]
+1

**Comment by njugray** [comment]
same problem

**Comment by nix1024** [comment]
+1

**Comment by timc-enthrall** [comment]
+1

**Comment by Godsenal** [comment]
+1

**Comment by FranklinTesla** [comment]
aha, i think this is a slip of pen of the version

**Comment by teokeecheng** [comment]
Same problem~

**Comment by tknickman** [comment]
Also just ran into this

**Comment by chenmingjia** [comment]
Also just ran into this

**Comment by beyondxgb** [comment]
stupid mistake, hope to solve quickly

**Comment by panyifei** [comment]
+1

**Comment by broadliyn** [comment]
Use `yarn install` instead of `npm install` for now.
You can choose `scheduler` version when you're using yarn.

**Comment by DoThanhTung119** [comment]
same here. cannot run with kind of bug :(

**Comment by EiddleChen** [comment]
+1

**Comment by tao1991123** [comment]
+1s

**Comment by uncledu** [comment]
+1

**Comment by EiddleChen** [comment]
enzyme-adapter-react-16@1.7.0 › react-test-renderer@16.6.2 › scheduler@^16.6.2

**Comment by dongyeo** [comment]
+1s

**Comment by liajoy** [comment]
+1

**Comment by boychina** [comment]
+1

**Comment by chaserx** [comment]
+1

**Comment by hvangumi** [comment]
+1

**Comment by dkao1978** [comment]
+1

**Comment by liangklfangl** [comment]
+1

**Comment by sebmarkbage** [comment]
We're aware. Also, 👍 is better than +1 comments.

**Comment by EiddleChen** [comment]
npm i react  
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for scheduler@^16.6.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'react'
npm ERR! notarget

```

**Comment by sorcerershell** [comment]
+1

**Comment by yanm1ng** [comment]
same problem. waiting online

**Comment by lylpixin2121** [comment]
+1

**Comment by daggmano** [comment]
By the looks of a linked issue above, is this a bug in react or in a linked library?
(And seriously guys, enough with the '+1' comments - they get it!!)

**Comment by sanketthanvi** [comment]
+1 👍

**Comment by lipeibin1995** [comment]
what happened?

**Comment by webmasterdevlin** [comment]
Thanks for fixing this issue, Andrew. We were in the middle of a React workshop when we encountered the bug. Glad everything is fine again.

**Comment by vamisola** [comment]
update npm
