### ISSUE TITLE
React is removing critical vendor prefixes, breaking styles.

### ISSUE THREAD

**Issue by skhameneh** [facebook/react#14200]
Related: https://github.com/facebook/react/issues/7372

React is removing the vendor prefix from `-webkit-background-clip`, `background-clip` without the prefix is not supported in Chrome.

See https://jsfiddle.net/2mx8gqh4/ in Chrome, inspect the element and see that the invalid `    background-clip: text;` is applied.  (`style={{ WebkitBackgroundClip: 'text' }}` was requested.)

**What is the expected behavior?**

`-webkit-background-clip: text;` is applied

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested in Chrome 70, React 16.5.1, and 16.6.1 - occurs in all.
Only Chrome/Opera are impacted.

**Comment by gaearon** [comment]
React is not removing it.

In https://github.com/facebook/react/issues/7372, you can see that the same behavior reproduces with regular JS API: https://github.com/facebook/react/issues/7372#issuecomment-236137852.

We can apply it to your case as well:

```js
document.body.style.WebkitBackgroundClip = 'text'
```

<img width="207" alt="screen shot 2018-11-12 at 6 44 01 pm" src="https://user-images.githubusercontent.com/810438/48368181-f68c0380-e6aa-11e8-8dfe-c626edde62bb.png">

So this is just what the browser does, and if you think it's a bug please report it to Chrome.
