### ISSUE TITLE
Is React Ignores fast props change with Redux?

### ISSUE THREAD

**Issue by Jonir227** [facebook/react#14211]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

![2018-11-13 3 40 14](https://user-images.githubusercontent.com/21289079/48395406-8472f780-e75a-11e8-85e3-5497de023434.png)

with Redux, I dispatched action twice quickly.
react ignores the first dispatch and also it renders only once.
but redux store updates both dispatch properly
with rAf, react works as expected.

code:
https://codesandbox.io/s/4jrnpk9l37

**What is the expected behavior?**
react renders twice

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.6.3
OS: Mac
Browser: Firefox

**Comment by Godsenal** [comment]
I think this is because you dispatched action in same tick. That means, react-redux's Provider will `setState` in same tick. As i know, Merging setState in sync is react default feature.

**Comment by Penspinner** [comment]
`speedyAtoB` probably runs two `setState` calls behind the scenes which are batched and result in one render.

`speedyBtoA` runs one `setState` synchronously and then the other one asynchronously, which will result in two renders.

Correct if I'm wrong plz.

**Comment by Jonir227** [comment]
thanks for the explaination!
