### ISSUE TITLE
React Dragact component interaction bug

### ISSUE THREAD

**Issue by fikyair** [facebook/react#14212]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I use dragact layout,mouse position(component real boundary)  and layout boundaries are inconsistent
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
[Problem screenshot](https://github.com/fikyair/Ignite-JavaScript30/blob/master/pic/picissue.png)
**What is the expected behavior?**
Mouse position(component real boundary) and layout boundaries are inconsistent
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "^15.6.1"

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by gaearon** [comment]
(There is no reason in your post why you think it’s a React bug. If you think it is we’ll need a reproducing case.)
