### ISSUE TITLE
When using React.lazy to code-split an error occurs if not accessing root route

### ISSUE THREAD

**Issue by sorodrigo** [facebook/react#14214]
**Do you want to request a *feature* or report a *bug*?**
🐛 Bug Report
**What is the current behavior?**
I'm using `React.Lazy` to code-split my page routes, when navigating between routes works fine as long as I start at `/`, if I start the app in another route I get the following:
```
Uncaught Error: Could not find "store" in either the context or props of "Connect(Info)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Info)".

Warning: Unexpected Fiber popped.

Warning: Unexpected pop.

Unexpected context found on stack. This error is likely caused by a bug in React. Please file an issue.
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I can't make a reproduction at the moment, will try to add it as a comment later. I also don't want to forget submitting this, so at least I'm adding it without repro for now.

**What is the expected behavior?**
When entering into a route different than root `React.lazy` should load the correct component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.6.0
Chrome 70
Firefox 63

**Comment by gaearon** [comment]
Try with 16.6.3? Yeah we’ll need a reproducing case.

**Comment by sorodrigo** [comment]
Hello again! I updated to 16.6.3 and the crash kept happening. I just spend some time building a repro app with no dependencies and was unable to reproduce.

Then I assumed the issue was with react-redux using the legacy context. Built another demo and still wasn’t able to break it 🤦🏻‍♂️.

I’m using `redux` + `react-redux` + `react-first-router` + `styled-components (new context api)`. So probably the issue comes from combining all of them in some odd way.

I’m sorry I couldn’t reproduce it so might as well close this.

**Comment by gaearon** [comment]
We'd still like to get a repro so let's keep it open for now. Maybe somebody else figures it out, or you manage to reduce your case to share it.

**Comment by zaguiini** [comment]
I'm using all those dependencies except for `redux-first-router` and at first glance that lib looks very suspicious of using `context` and interfering with `lazy` and, obviously, uses `redux` which, itself, uses context.

My app works just fine with all those libs... Maybe take a look at `redux-first-router`?

**Comment by gaearon** [comment]
If you find a minimal reproducing case I'd be very grateful! We still want the legacy context to work for now, so it's a bug we need to fix.

**Comment by sorodrigo** [comment]
I can probably reproduce it using `redux-first-router`, but maybe that library is abusing of legacy context? Will work on something this week.

**Comment by gaearon** [comment]
`redux-first-router` itself doesn't even seem to use React.

**Comment by zaguiini** [comment]
It's a middleware. Possibly it affects the way that `react-redux` works?

**Comment by sorodrigo** [comment]
I have a small app I'm building for a course where I ran into this issue. This app has the dependencies mentioned above so if you're ok with that, I can upload it to a repo.
I'll change the content for copyright reasons, but leave the core stuff the same.

**Comment by sorodrigo** [comment]
Hello, sorry I never provided the repro. Life got in the way. However this issue is now fixed. The root cause was the way `redux-first-router-link` was using the legacy context. Fix landed in https://github.com/faceyspacey/redux-first-router-link/pull/107

Thanks for your help!! 🎉
