### ISSUE TITLE
React should use markup wrap for top-level HTML setting

### ISSUE THREAD

**Issue by spicyj** [facebook/react#1421]
This is broken in IE8 because we don't use `getMarkupWrap` when setting the HTML for a top-level component.

http://jsbin.com/huresuba/1/edit (editor, incompatible with IE8 anyway)
http://jsbin.com/huresuba/1 (preview, shows the IE8 problem)

**Comment by Aweary** [comment]
@spicyj IE8 support was dropped, can we close this?

**Comment by spicyj** [comment]
Feel free especially since this isn't a regression.






On Sat, Dec 3, 2016 at 10:44 AM -0800, "Brandon Dail" <notifications@github.com> wrote:












@spicyj IE8 support was dropped, can we close this?
