### ISSUE TITLE
react-nested-file-tree

### ISSUE THREAD

**Issue by btf93** [facebook/react#14215]
Hi, Is there a known issue with the 'NestedFileTreeView'? 

Since updating to the latest version of React, the only way we can run webpack and get the application to display is to delete the code:

'import NestedFileTreeView from 'react-nested-file-tree' and '<NestedFileTreeView'.

Thanks

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
