### ISSUE TITLE
Error in JSdoc react versions 16.6.1 - 16.6.3

### ISSUE THREAD

**Issue by vladhd93** [facebook/react#14229]
Hello, looks like in file react.development.js exists some inconsistency between versions
![screenshot from 2018-11-14 12-30-42](https://user-images.githubusercontent.com/11429982/48477217-b0998180-e809-11e8-9abb-5330b6bb7a87.png)

**Comment by gaearon** [comment]
What inconsistency? Can you be more specific?

**Comment by ghost2238** [comment]
"@license React v16.6.1" while package.json and ReactVersion has 16.6.3 set.

It's in react.production.min.js too.

**Comment by Nothing-Works** [comment]
also on https://reactjs.org/ the react version seems also 16.6.1

**Comment by vladhd93** [comment]
@gaearon  - yea, guys, are right !
js doc at first line has version of react 16.6.1 and var ReactVersion = '16.6.3';

**Comment by bvaughn** [comment]
A slightly different build process was used for the 16.6.3 release which (unintentionally) skipped updating the header comment. This should be addressed before the next release.

It shouldn't cause any actual problems for anyone though so I'm going to mark this as closed. 😄
