### ISSUE TITLE
DOM updates not minimal when moving last child to first place

### ISSUE THREAD

**Issue by steadicat** [facebook/react#1422]
When a rerender requires the last child to be moved to first place, the update to the DOM is not minimal. Instead of removing the child in question and re-inserting it, all the other children are removed and re-added instead.

This is bad for two reasons:
1. It is unnecessary churn on the DOM, slowing things down. If any of the children is or contains a video element, the video will reset.
2. Using keys to shuffle children around is pretty common when implementing an infinite scroll in React with DOM element reuse. This should work.

Here's a screencast showing how the DOM is changed while I scroll. Notice how when I scroll down the first element is correctly removed from the top and inserted at the bottom. When I scroll back up, instead of moving the last element, React moves the other four.

https://dl.dropboxusercontent.com/u/140702/ReactDomOperations.mov

I'm using React 0.9.0.

**Comment by viniciusdacal** [comment]
isn't currently working with proper use of prop `key`?

**Comment by gaearon** [comment]
Special-casing specific operations like “last child becomes first” looks great on benchmarks, but as @syranide noted in https://github.com/facebook/react/issues/1422#issuecomment-43443219, leads to unexpected differences in performance that can make profiling harder.

The issue with moving `iframe`/`video`/`audio` is different, and we don’t have a good solution for it either. I’m not sure solving it would be worth the complexity it introduces.

I will close this issue but if you have more generic ideas on improving diffing algorithm that make it better for the average case without hurting the edge cases (as opposed to adding a special case) let’s discuss them in a new issue.
