### ISSUE TITLE
react hooks don't work with  react-hot-loader/babel

### ISSUE THREAD

**Issue by zhangchao828** [facebook/react#14237]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
react hooks don't work with  react-hot-loader/babel

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 16.7.0-alpha.2
react-dom 16.7.0-alpha.2
react-hot-loader 4.1.1

**Comment by zhangchao828** [comment]
![1542250413 1](https://user-images.githubusercontent.com/15683846/48527375-e734d200-e8c5-11e8-95e9-4a79b84c5756.jpg)

**Comment by zhangchao828** [comment]
![1542251010 1](https://user-images.githubusercontent.com/15683846/48527428-1f3c1500-e8c6-11e8-970c-26e920307772.jpg)

**Comment by gaearon** [comment]
Yes, please report it to RHL repo.

**Comment by theKashey** [comment]
Please try [ReactHotLoader@next](https://github.com/gaearon/react-hot-loader#-hot-labs-), but to support hooks some configuration have to be made.
