### ISSUE TITLE
Defining Legacy Context inside of constructor regression

### ISSUE THREAD

**Issue by aikar** [facebook/react#14231]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Code using the legacy API in react 15 no longer works in React 16 when defining Context during a classes Constructor

We used this style as a utility helper to reduce the boilerplate.

Example broken code
https://gist.github.com/aikar/a20885848ac6da5318f6aee6434dd758

**What is the expected behavior?**
```
Warning: Unexpected Fiber popped.
Warning: Unexpected Fiber popped.
Warning: Unexpected pop.
Warning: Unexpected pop.
```
If you uncomment the childContextTypes, all works. It appears the value is read before the object is created now and thinks no context is being used.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6.3, tested 16.3 too (could not test 16.2 due to other dep depending on new context API)

**Comment by gaearon** [comment]
The error itself is confusing (and we could probably find a way to show a better one), but this style of dynamically defining context isn’t officially supported and worked by accident. In either case I encourage you to look into using the modern context API instead of the legacy one (which was always marked as unstable).

**Comment by aikar** [comment]
@gaearon Interesting simple fix that may lead to a quick fix on react if you will restore it.

simply adding a static childContextTypes = {} container resolves it. so it seems react seems to only check if the property exists or not and doesn't care about the values in it.

Since my actual use case of this provideContext method was in a parent class, as we extend all of our components from a common base component to provide common utility functions, I was able to trivially fix it by stubbing into the base component

```javascript
static childContextTypes = {}
getContext() {
    return {}
}
```
but leads me to believe regardless of supporting this usage, it shouldn't be so easy to corrupt the fiber state by doing this.

**Comment by aikar** [comment]
And note moving to the new API is on the agenda, but I want to tackle that as a different unit of work outside of the main 15 => 16 update.
