### ISSUE TITLE
Regression: React 16 automatically marks first item of a select with size > 1 as checked

### ISSUE THREAD

**Issue by kamituel** [facebook/react#14239]
**Do you want to request a *feature* or report a *bug*?**

Bug - regression

**What is the current behavior?**

In react 16 when creating a `<select size="3">` (size > 1) the first child <option> is automatically getting marked as selected. In React 16 there does not seem to be a way to specify no <option> gets selected by default

https://codesandbox.io/s/m76ozkwm89

**What is the expected behavior?**

In React 15 unless you marked an option to be selected <option selected> no options were selected by default.

https://codesandbox.io/s/6894m3k9w

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Reproducible in Chrome 72 and Firefox 59.

**Note:** this is almost a duplicate of #12200. In fact, I copied issue text and codesandbox examples, just changing `multiple` to `size="3"`.

**Comment by highskillzz** [comment]
Can I take this issue?

**Comment by nhunzaker** [comment]
Interesting!

Here's a manual DOM example of what we're doing:
https://codepen.io/nhunzaker/pen/gqEvjj

It also looks like this is not necessary if a select dropdown is already in "multiple" mode".

**Comment by nhunzaker** [comment]
@highskillzz sorry to get back late to this. https://github.com/facebook/react/pull/14242 is close to a fix.

**Comment by gaearon** [comment]
Fixed in 16.8.5.
