### ISSUE TITLE
static contextType resolving this.context to null in some cases

### ISSUE THREAD

**Issue by milesj** [facebook/react#14243]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

We have a toasts system powered by the new React context. To make integration easier on the consumer side, we started using `static contextType` over `Context.Consumer` or an HOC. This works for the most part, but we're seeing errors like the following all over Sentry: "TypeError: Cannot read property 'addToast' of null".

Most of these errors occur within the then/catch of a promise, so I'm leaning towards it being an async/reconciler bug in which `this.context` is being unset to early? Or perhaps the component being unmounted?

I've audited all the implementations throwing errors, and they all have `static contextType` set correctly, and are properly referencing `this.context`.

I even tried the following, which also fails.

```
const { context } = this;

someAction().then(() => {
  context.addToast('Did something');
});
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I've implemented a few test cases here, but all of them seem to pass. I'll try and dig a bit more and see what I can find.

https://codesandbox.io/s/m3l8jn6w4j

**What is the expected behavior?**

`this.context` is the context value and not null.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.6+
All browsers
Didn't work in previous versions as it's new functionality.

**Comment by gaearon** [comment]
We'd need a reproducing case. :-)

**Comment by milesj** [comment]
Yeah I've been trying :[ No luck, but still consistently seeing these errors all over Sentry. Will dig further.

**Comment by threepointone** [comment]
I'm going to close this issue, but I'd be happy to reopen if there's a reproducing case.
