### ISSUE TITLE
Imperative API for component containing hooks

### ISSUE THREAD

**Issue by cloudever** [facebook/react#14246]
Some components provide imperative API for inner state manipulation, for example https://ant.design/components/tree-select/ has a methods `blur()` and `focus()` on its `ref`

Is there some practices to make that great again usign functional components and hooks?

**Comment by hamlim** [comment]
It sounds like you are looking for the `useimperativemethods` hook, which allows a function component to provide methods and values that a parent passing down a ref to the function component can then access: https://reactjs.org/docs/hooks-reference.html#useimperativemethods
