### ISSUE TITLE
How to use many contexts?

### ISSUE THREAD

**Issue by MaximKudriavtsev** [facebook/react#14240]
Hi,

I have a component that uses many contexts. I can use these contexts inside the `render` method without any problems using the `Context.Consumer` wrapper. But I can't access contexts in life-cycle methods such as `componentDidMount` or `constructor`, for instance. I found a [solution](https://github.com/facebook/react/issues/12397#issuecomment-375501574) that is based on using a HOC. Is it an officially recommended way?

**Comment by gaearon** [comment]
Yes.

Our Hooks proposal addresses it in a more direct way with `useContext`. Check it out:

https://reactjs.org/docs/hooks-intro.html

**Comment by MaximKudriavtsev** [comment]
@gaearon 

Thank you very much for a quick reply!
