### ISSUE TITLE
React + Webpack bug - Module concatenation causes React component to lose its state

### ISSUE THREAD

**Issue by volkanunsal** [facebook/react#14247]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In Webpack, when mode is set to 'production' and devtool is set to a setting that produces source-maps, React produces unexpected results. After long experimentation, I believe the behavior is caused by module concatenation. It affects one particular library, which I have included in the repo below.

https://github.com/volkanunsal/webpack_bug

**What is the expected behavior?**

The input field should not lose its focus, but does.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.6.0

It works only when the library is loaded as ES5. I'm not sure if it's a React bug or a Webpack bug, to be honest. So I'm filing it on both React and Webpack repos.

**Comment by gaearon** [comment]
Did you figure it out?

**Comment by volkanunsal** [comment]
No, not yet, unfortunately. But I don't think it's a React issue. Probably a Webpack issue (or Uglifier issue). [Here is the thread on the Webpack repo](https://github.com/webpack/webpack/issues/8384).
