### ISSUE TITLE
String values for input[type='number'] & input[type='range']

### ISSUE THREAD

**Issue by sudodoki** [facebook/react#1425]
Enhancement proposal: create `numberLink` or make e.target.value return value of type number for input with types `range` & `number`.
Reasoning:
- if you have input type number, you would expect it's value to be string (duh thing that might have been historical attainment?)
- [LinkedValueUtils](https://github.com/facebook/react/blob/385eb1cef17b8babfdade6b448a618e7e1c679db/src/browser/ui/dom/components/LinkedValueUtils.js) seems to have some different handling for handling string & boolean values
- if you init your state with number & use valueLink, it will initialize input properly but second you change input value it will change to string (and possibly explode something, say, child property depending on it to be of type number)

Partial work around would be using

```
handleChange: function(newValue) {
    this.setState({
        value: parseInt(newValue, 10)
    })
},
...
render: function() {
    var valueLink = {
        value = thist.state.value, requestChange: this.handleChange
    }
    return <input type = 'number' valueLink = {valueLink} />
}
```

According to [docs](http://facebook.github.io/react/docs/two-way-binding-helpers.html#reactlink-without-linkedstatemixin).
Demonstration of number & range inputs for React & vanilla js in [jsbin](http://jsbin.com/cixasipo/2/edit).

**Comment by nhunzaker** [comment]
[ReactNative's Input](https://facebook.github.io/react-native/docs/textinput.html) has an `onChangeText` property. Providing something similar for how to deal with number input values could be a really nice addition (though some would argue this should happen in user land).

We'd probably need to figure out:

1. What to do about bad input
2. How to handle the empty case (where numbers report `''`)
3. Probably something else

Is this feature worth considering, or are we comfortable pushing this to the community?

**Comment by aweary** [comment]
@nhunzaker I think it's reasonable to push this to the community. There doesn't seem to be a high demand for this in React core, so let's defer to user-land and close this out 👍

**Comment by SamsonChoo** [comment]
May I ask why was this closed and what is the solution? Intuitively I would think that a number type input would return a number type value, right?
