### ISSUE TITLE
Flow error with hooks

### ISSUE THREAD

**Issue by hrasoa** [facebook/react#14251]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```javascript
$ npm run lint

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ index.js:2:17

Cannot import useContext because there is no useContext export in react. Did you mean Context?

     1│ // @flow
     2│ import React, { useContext } from 'react';
     3│
     4│
```

**What is the expected behavior?**
It should not report an issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Clone https://github.com/hrasoa/flow-hook
```sh
$ npm install
$ npm run lint
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```sh
$ npm ls react flow-bin

├── flow-bin@0.86.0 
└── react@16.7.0-alpha.2

**Comment by hrasoa** [comment]
Edit: added a minimal demo repo.

**Comment by TrySound** [comment]
@hrasoa Hooks types are not released yet in flow. Wait for 0.87.
https://github.com/facebook/flow/pull/7149

**Comment by hrasoa** [comment]
@TrySound oh ok thanks
