### ISSUE TITLE
How to update a component that is other root by reactDom.render ?

### ISSUE THREAD

**Issue by TongDaDa** [facebook/react#14258]
**Do you want to request a *feature* or report a *bug*?**
feature.

**What is the current behavior?**

When the parent component is updated, the child component is mounted to the body by detecting the visible property and via componentDidUpdate (note that the upper component is mounted to the #root div), but when my parent component is setState, the child component is The value is not updated. It seems that the subcomponent can be refreshed only once it is remounted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Child components are also updated when the parent component updates state, I want to find a great solution

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 16.6
OSX

**Comment by sophiebits** [comment]
Can you provide a code example?

It’s hard to understand you, but portals may solve your problem: https://reactjs.org/docs/portals.html.

**Comment by TongDaDa** [comment]
@sophiebits not portals, it just render Component to Container, but my problem is I want update state that the element of the appended body. now It doesn't update its props that parent component state because it doesn't in the parent life-cycle, so maybe I create a ref and update it by force`forceUpdate` method. are you understand? my English is not good.


```
javascript
   /* forcing update the component of appended body */
     componentDidUpdate(prevProps){
        if (modalRef.current) {
            modalRef.current.forceUpdate()
        }
    }

  /**
     * @desc take the props Content Component insert to body.
     * @param x {Number} -- x-position in document
     * @param y {Number} -- y-position in document
     * @return undefined
     */
    insertContentIntoBody = (x,y,instance) => {
        const {Content, Footer} = this.props;
        const ele = this.initWrapperEle(x, y);
        instance.addContentEle(ele);
        modalList.push(instance);
        this.topTipModalEle = ele;
        ReactDom.unstable_renderSubtreeIntoContainer(this, <CombinedComponent ref={modalRef} Content={Content} Footer={Footer} />, ele, () => {
           document.body.appendChild(ele);
           document.addEventListener('click', this._cancel)
        });
    }
```

**Comment by TongDaDa** [comment]
@sophiebits

**Comment by srph** [comment]
Portals should be able to solve this. If this is still an issue, I'd like to help you out if you can provide a CodeSandbox / JSFiddle for me to play around with.

**Comment by TongDaDa** [comment]
@srph  I want to know what behavior the Portals, I think it is re-mount on dom.

**Comment by TongDaDa** [comment]
Portal does solve my problem, but DOM.render and Portal which has more performance?

**Comment by srph** [comment]
Hi @TongDaDa. Let's not talk about performance without context. I haven't ran into issues with Portal so far.

**Comment by TongDaDa** [comment]
@srph thanks, I'll investigate difference of them.  thank your anwsers.😀

**Comment by srph** [comment]
Anytime. Do you mind closing this issue? :D

**Comment by TongDaDa** [comment]
Ok. sorry, I forgot it.
