### ISSUE TITLE
Performance degradation without componentWillReceiveProps

### ISSUE THREAD

**Issue by jozefchutka** [facebook/react#14252]
I sense a performance degradation post deprecating `componentWillReceiveProps`. I have been through long readings about using new getDerivedStateFromProps, memoization, controlled components, uncontrolled components, however I havent seen mentioned or been able to discover more performant way of recognizing the props change. All of the suggested new options requires eventually more computation then necessary as props change detection is happening related to every render phase, either with getDerivedStateFromProps where you do some checks before every render, or with memoization where you do compute / read data during each render phase. My feeling is that previous option with componentWillReceiveProps was architected far more optimal in terms of performance.

For better understanding of this general case, think of prop say array that needs to be transformed into some other structure when changed. With componentWillReceiveProps there was a single time to do so, and without any further computation these data would be reused from state. 

With getDerivedStateFromProps, processing to detect change is to be run before every single render phase (while getDerivedStateFromProps executes before every render).

With memoization, change detection is executed directly inside render phase. Memoization is not something that would be unblocked by latest React, this option was there always but was suboptimal to componentWillReceiveProps.

- Have you considered well these performance downsides of removing this precise lifecycle event, before deprecating it? 
- What is the benefit of having componentWillReceiveProps deprecated apart from someone using it wrong way (for data loading)?
- Why getDerivedStateFromProps is executed before every render as oppose to just props change?
- Why getDerivedStateFromProps is scheduled before shouldComponentUpdate?

**Comment by gaearon** [comment]
Please provide a reproducible example demonstrating a perf regression. Otherwise it’s very abstract. It’s not clear to me what specific scenario you’re talking about. 

I’ll try to find links for your other questions on Monday but please know that they have been discussed at length so with some searching you should be able to find them too.

**Comment by Smokeacid** [comment]
ကို့စကားနားေထာင္ေနတာကိုကခ်စ္တာ

**Comment by Smokeacid** [comment]
https://github.com/facebook/react/issues/14252#issuecomment-439556542

**Comment by Smokeacid** [comment]
ေမနဲ႔တူတရ္ေနာ္စမ္းလွ

**Comment by jozefchutka** [comment]
Here is a short example of how both getDerivedStateFromProps and memoizing is suboptimal to componentWillReceiveProps, notice 

```
class Parent extends Component {
	render() {
		return <div>
			<ChildGDSFP data={props.data}/>
			<ChildMemo data={props.data}/>
			<ChildCWRP data={props.data}/>
			</div>;
	}
}
```

Component executes `getDerivedStateFromProps` before every render. Also when very unrelated state is modified only.
```
class ChildGDSFP extends Component {
	// executed with every render / every button click
	static getDerivedStateFromProps(props, state) {
		return {processedData: HeavyFunction(props.data)};
	}

	onClick = () => {
		this.setState({count: this.state.count + 1});
	}

	render() {
		return <div>
			{state.processedData}
			<button onClick={this.onClick}>{state.count}</button>
		</div>;
	}
}
```

Component executes `memoize` before every render. Also when very unrelated state is modified only.
```
class ChildMemo extends Component {
	onClick = () => {
		this.setState({count: this.state.count + 1});
	}

	// executed with every render / every button click
	filter = memoize(
		(data) => HeavyFunction(data);
	);

	
	render() {
		const processedData = this.filter(this.props.data);
		return <div>
			{processedData}
			<button onClick={this.onClick}>{state.count}</button>
		</div>;
	}
}
```

Component executes `componentWillReceiveProps` only when I need it.
```
class ChildCWRP extends Component {
	onClick = () => {
		this.setState({count: this.state.count + 1});
	}

	// executed once
	componentWillReceiveProps(nextProps){
		this.setState({processedData:HeavyFunction(nextProps.data)});
	}

	render() {
		return <div>
			{state.processedData}
			<button onClick={this.onClick}>{state.count}</button>
		</div>;
	}
}
```

**Comment by jozefchutka** [comment]
The more I think about memoizing as described in [You Probably Don't Need Derived State](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) the more I realize how far React it drifting away from its own rules and architecture. I believe the memoizing is react antipattern for these 3 reasons:
1. memoizing does heavy data processing during render phase. Render should remain render, it should just use existing data and not creating diverging with heavy processing in this phase.
2. memoizing produces component (instance) data during render phase. While setState is forbidden for good reasons since ever.
3. memoizing uses component (instence) data for render. While only props and state should be used. Although these are diverged from state/props but stored in component instance hiddenly using 3rd part lib. 

```
render() {
	// this is a bad practice and not recommended while only state and props should be used for render
	this.data = HeavyFunction(this.props.data);
	
	// this is very recommended although the data is eventually stored on component instance the same way as on previous line, just hidden by 3rt party lib
	const processedData = this.memoizeFilter(this.props.data);
}
```

**Comment by jozefchutka** [comment]
@gaearon hi Dan, is this sufficient demo, examples and information about the regression?

**Comment by Smokeacid** [comment]
mhalin05@gmail.com

**Comment by jozefchutka** [comment]
@gaearon ?
