### ISSUE TITLE
Implement Display Locking integration

### ISSUE THREAD

**Issue by chrishtr** [facebook/react#14256]
Display Locking (https://github.com/chrishtr/display-locking) is a proposed new web standard that allows scheduling and asynchronous control of the browser rendering loop.

An implementation in Chrome is in progress, tracked at http://crbug.com/882663. @vmpstr is implementing.

This issue is to tracks implementing Display Locking integration in React behind a flag, and iterating
on a demo.

I think the next most clear steps are:
1. Get the Display Locking implementation into a state that can be used in a demo (@vmpstr)
2. Add code to React to support Display Locking
3. Build a demo that demonstrates the integration

We can use these to validate the design, debug it, and measure performance on a common example.

**Comment by sophiebits** [comment]
Thanks for filing the issue. cc @acdlite @sebmarkbage
