### ISSUE TITLE
Flow errors with React 16.6 Suspense and Lazy

### ISSUE THREAD

**Issue by MaxMillington** [facebook/react#14261]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Currently, when using `Suspense` component along with Flow, I get the following error: 
```
Cannot import Suspense because there is no Suspense export in react.

     1│ // @flow
     2│ import React, { Component, Suspense } from 'react'
     3│ import { Loading } from '../../shared/components'
```

I get a similar error with React.lazy(). 

**What is the expected behavior?**
React should expose this so that Flow will validate

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6

**Comment by TrySound** [comment]
`Suspense` and `Lazy` are not covered with types in flow yet.
https://github.com/facebook/flow/blob/master/lib/react.js

**Comment by MaxMillington** [comment]
closing since flow team is considering a fix

**Comment by headfire94** [comment]
What can I do in this case? Ignore error until update? @TrySound
