### ISSUE TITLE
HTML video tag support preload parameter (IE Edge)

### ISSUE THREAD

**Issue by fatih108** [facebook/react#14263]
I am unable to use preload parameter for `<video preload='none'>` with IE Edge

**Comment by fatih108** [comment]
Not working: https://codesandbox.io/s/2z2nw81p7p
Working: https://codepen.io/fatih-erol/pen/wQPMNK   

Preload attribute notworking with IE edge. Ty..

**Comment by Nothing-Works** [comment]
@fatih108  the second link is not working either.

**Comment by fatih108** [comment]
@Nothing-Works  I tested, working
