### ISSUE TITLE
this.props.children is broken

### ISSUE THREAD

**Issue by mrcnw** [facebook/react#14274]
Anybody can helps? What is going on? I used similar lines of code 4 months ago (v16.3) and all was ok. Now I have 16.6 and something doesn't work.

![image](https://user-images.githubusercontent.com/32802948/48715293-fb096c80-ec14-11e8-8a22-2d7cdbd47680.png)
![image](https://user-images.githubusercontent.com/32802948/48715345-18d6d180-ec15-11e8-9f99-769489f62612.png)

**Comment by gaearon** [comment]
Maybe you have some kind of whitespace there so it's not actually a function?
Do `console.log(this.props.children)` before calling it and you'll find out.

In general please consider that we use issue tracker for bug reports in React. What you submitted is more like a support ticket and would better be served by StackOverflow. It would also need a reproducible example.
