### ISSUE TITLE
react-is memo

### ISSUE THREAD

**Issue by aurimas4** [facebook/react#14278]
Feature request

**What is the current behavior?**
`react-is` now doesn't have method to check if element is `memo`(like `isForwardRef`).
Maybe there are some reasons why it's not implemented?

**Comment by gaearon** [comment]
No particular reason, we could add it. What is your use case?

**Comment by Kovensky** [comment]
The only one that comes to mind, other than debug stuff, is avoiding double-wrapping with memo in a HOC factory, but that is something that React.memo itself could do (or maybe already does).

**Comment by bvaughn** [comment]
Resolved via #14313
