### ISSUE TITLE
HTML5 video tag memory leak in IE11

### ISSUE THREAD

**Issue by neekychan** [facebook/react#14272]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
i use the video and source tag in reactjs 16.6.3.
the memory rise 20Mb - 50Mb when is show the comps or refresh the browser.
the browser will crash after the memory rise to 1.5gb+
but when i use the pure html5 tag without reactjs, memory release usage after refresh or remove tag

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/5zw30kjw1l

**What is the expected behavior?**
in IE11, release memory usage after destory component or refresh page
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
windows 7, Internet Explorer 11

**Comment by gaearon** [comment]
Are you testing on production version of React? CodeSandbox uses a development version.

**Comment by raRaRa** [comment]
This leak is also happening in latest Chrome. I've been debugging this memory issue on my website for two days and finally figured out that the video tag is causing a lot of detached nodes. Happens on development & production.

To reproduce this issue, create a component with an empty video tag. Render a few of them and then remove them all.

In Chrome take a heap snapshot and note how there are bunch of detached nodes. If you continue to create and remove them over time you'll see the memory rise until Chrome crashes.

I'll look into creating a production demo. I'm using the latest stable React version.

**Comment by raRaRa** [comment]
Sandbox demo: https://codesandbox.io/s/9jjlr52vr - I have one button that renders 20 empty video tags and another button to render 20 empty img tags, to show the difference of detached nodes, that there's clearly something wrong with how React handles the video tag.

Production version: https://csb-9jjlr52vr.netlify.com/

When you run the website, take a heap snapshot. Click on "Render empty video components 20 times" and "Remove empty video components" a few times. Take another heap snapshot. On the second heap snapshot compare it with the first one. In the class filter type: "Detached" and note how there are bunch of detached nodes that weren't garbage collected.

![image](https://user-images.githubusercontent.com/4303914/57369444-15acaf00-717d-11e9-8c4e-eec1a60365f8.png)

Hope this helps to figure out what's going on @gaearon
