### ISSUE TITLE
React class or react function

### ISSUE THREAD

**Issue by tpakhoa1996** [facebook/react#14283]
Does react framework prefer us to code everything in function now as I heard that there will be performance boost for components written in functional way. Also, now there is function hook on experiment. So is react moving toward functional components and will get rid of class components in the future?

**Comment by Kovensky** [comment]
Classes should still be around for a very long time to avoid a Python 3 situation. Even if classes someday are moved out of core, the team will probably provide a compatibility layer that you can load.

But yes, React is moving towards a more plain function-based approach. Even with the experimental hooks there are still some things _only_ class components can do (e.g. componentDidCatch) but that is a bug, not a feature.

**Comment by aweary** [comment]
Checkout the [Gradual Adoption Strategy](https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy) in the Hooks documentation, which addresses this. Specifically:

> We intend for Hooks to cover all existing use cases for classes, but we will keep supporting class components for the foreseeable future.

Feel free to use function or class components. Hooks only work with function components, but class components will continue to be supported and improved (see the recent `contextType` addition as an example!)

**Comment by bySabi** [comment]
Is any thread on `componentDidCatch`  bug?.. What is stopping the React Hook implementation of this?
