### ISSUE TITLE
Client side render mounts server-side rendered div but doesn't recognize the differences.

### ISSUE THREAD

**Issue by nuclearspike** [facebook/react#14281]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When client re-renders a server-rendered element, it no longer checks to see if it element is different. NodeJS server render, this had worked in previous versions of react but broke after upgrading to 16 from 15. It does render the children, but the root div being output is treated as though it's the same even though the attributes are very different.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I can't do a fiddle or sandbox since it's an SSR/CSR issue.

consider:

```
class C extends React.Component {
   render() {
       // if SSR, just output a simple div to hold the sizing so that the client can fill it without causing the page to re-adjust.
       if (!process.env.BROWSER) {
          return <div style={{ height: 46 }} />
       }

      return (
           <div key="client" className={cx(.....)}>
                ... bunch of components that only render client-side. shouldn't matter what they are for this report.
           </div>
      )
   }
}
```

**What is the expected behavior?**

Previously (react v15), it would output the div with style attribute at the server but the client would re-render it, dropping the style and adding the classes which is exactly what I want. But now, it looks like it sees the server-rendered div as being the same as what the client rendered and doesn't add the classes or drop the style. It does recognize that the client has children and those do show up. I can only interpret this as a bug.

output from SSR only (no client code) this is expected and consistent between v15 and v16)
```
  <div style="height: 46px" />
````
output after client does it's own render (not expected).
```
  <div style="height: 46px">
     ...bunch of client-only components.
  </div>
````
What it **should have** produced (used to in v 15) after the client side re-rendering of an SSR page
```
  <div key="client" class="...bunch of css classes">
     ...bunch of client-only components.
  </div>
```
For my uses, by not applying the CSS classes to the root div means that all sorts of styling options were not applied to all of the children due to the CSS rules.

It should have had a final output of a div with the CSS classes defined by the client code without any style attributes defined by the server code.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Broken after I upgraded to v16 from v15

**Comment by gaearon** [comment]
This is expected — the old behavior would *remount the whole page* which is terrible for performance.

See the hydration behavior described here: https://reactjs.org/docs/react-dom.html#hydrate

>React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

>...

>If you intentionally need to render something different on the server and the client, you can do a two-pass rendering. Components that render something different on the client can read a state variable like `this.state.isClient`, which you can set to true in `componentDidMount()`. This way the initial render pass will render the same content as the server, avoiding mismatches, but an additional pass will happen synchronously right after hydration. Note that this approach will make your components slower because they have to render twice, so use it with caution.

>Remember to be mindful of user experience on slow connections. The JavaScript code may load significantly later than the initial HTML render, so if you render something different in the client-only pass, the transition can be jarring. However, if executed well, it may be beneficial to render a “shell” of the application on the server, and only show some of the extra widgets on the client. To learn how to do this without getting the markup mismatch issues, refer to the explanation in the previous paragraph.

See also https://github.com/facebook/react/issues/10591 for a detailed discussion about this.

**Comment by nuclearspike** [comment]
I'm not sure I understand how this is a full response since it worked in v15 and didn't cause a full remount of anything and the speed doesn't seem noticeably different. Unless you're saying v16 has increased efficiency by removing some of the validation (assuming that it had happened in v15).
