### ISSUE TITLE
Accessing window properties inside useEffect leads to "Invalid calling object" error in IE 11

### ISSUE THREAD

**Issue by cgcote** [facebook/react#14293]
Hello,

I've noticed in two specific use cases that accessing window properties inside a useEffect leads to the error "Invalid calling object" in Internet Explorer 11. 

I have not been able to isolate a minimum demo of the problem unfortunately.

First problem - window scroll
`useEffect(() => {
    window.scroll(0, 0);
}, [])`

Second problem - Apollo client polling
`useEffect(() => {
    startPolling(120000);
    return stopPolling;
  }, []);`
https://github.com/apollographql/apollo-client/blob/6f579ea2cdf8c78acb004a4457a7a6764d64091e/packages/apollo-client/src/scheduler/scheduler.ts The start polling method internally uses setInterval.

In both cases, replacing the useEffect by lifecycles removes the error.

React version: 16.7.0-alpha.2

**Comment by gaearon** [comment]
Can you please provide a complete reproducing case?

**Comment by cgcote** [comment]
The problem seems fixed if I call useLayoutEffect instead of useEffect. I did not manage to get a complete reproducing case, and I don't why it's only failing on IE so I'll close this issue.

On an API perspective, I find this distinction to be quite dangerous - if you refer to my example with apollo client, I should not have to dig into libraries to see how they are implemented. 

But the useMutationEffect and useLayoutEffect are probably among the things that make the alpha an alpha!

**Comment by gaearon** [comment]
I don’t understand how what you’re complaining about is a failure of the API.

If useEffect is broken then we need to fix it. We can’t however unless you provide a reproducing case to run.

If it’s not broken then presumably the code that runs there doesn’t work in IE for some reason. Then that code needs fixing.

Neither is a problem of useEffect API.

**Comment by gaearon** [comment]
To be clear they differ in when they run which is absolutely intentional. Because running effects later lets us reduce performance issues that are caused by running too much code in lifecycle methods. If we just make useLayoutEffect behavior default we haven’t solved the problem and are back to square one.

Of course it’s annoying to dig into bugs. But we need to figure out whose bug it is, and make a proper fix for it.

**Comment by cgcote** [comment]
Ok so if I understand you correctly the useLayoutEffect behaves strictly like a lifecycle.

I completely get your point regarding useEffect vs useLayoutEffect and I sincerely wish we identified whether the problem comes from react or from our code base.

We've had someone spend 3 full days trying to reproduce the problem and unfortunately we don't have the resources to continue investigating full time. The only thing we found is that it never happens in development mode and that it's fixed when replaced by a lifecycle.  

And the main problem here is that it happens only in IE as we don't have any windows setup.

**Comment by gaearon** [comment]
Fair enough 🙂 If you do find a reduced case we’d appreciate sharing it.

All useEffect does is run the work a bit later, when the browser isn’t busy. It’s hard to guess which APIs don’t work in this case in IE or why.

**Comment by cgcote** [comment]
@gaearon we've managed to narrow the scope of the problem.
It happens when the code is build with devtools: eval-source-map or eval. it's working with source-map.

+ Edge is also affected

**Comment by hipstersmoothie** [comment]
We are seeing the same issue. currently we will not be able to get a repro for a few weeks. 

But i can confirm that the bug happens under these conditions:

1. Have a custom hook that uses window properties

```ts
import React from 'react';

/**
 * Determine if the user has "reduce-motion" enabled in their browser.
 *
 * @example
 * const isReducedMotion = useReduceMotion();
 */
export const useReduceMotion = () => {
  const [reduceMotion, setReduceMotion] = React.useState(
    window.matchMedia('(prefers-reduced-motion: reduce)').matches
  );

  // With either useEffect or useLayoutEffect this breaks. I can even comment
  // out the entire inside of the effect and the error happens.
  React.useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-reduced-motion: reduce)');

    /** Ran when the user changes this setting. */
    const changeReduceMotion = () => setReduceMotion(!reduceMotion);

    // TODO: For IE11, remove once support is dropped
    if (mediaQuery.addListener) {
      mediaQuery.addListener(changeReduceMotion);
    }

    return () => {
      // TODO: For IE11, remove once support is dropped
      if (mediaQuery.removeListener) {
        mediaQuery.removeListener(changeReduceMotion);
      }
    };
  }, [reduceMotion]);

  return reduceMotion;
};
```

2. Have `devtool: 'eval-source-map'` somewhere in a webpack build

3. Open IE

![Screen Shot 2019-08-14 at 3 03 35 PM](https://user-images.githubusercontent.com/1192452/63059610-c0331d00-bea4-11e9-8a76-21190208a889.png)

**Comment by pushp-1992** [comment]
Ok, so why it happens is.

`useLayoutEffect` is executed synchronously as the DOM renders but same case is not with the `useEffect`. And i could see, @cgcote was trying to access `window` object during rendering of the application using `useEffect` and knowing the fact the way and the timing `useEffect` is injected in react app, it throws error. But using `useLayoutEffect` it don't.
