### ISSUE TITLE
the <label> tag fired onClick Event twice

### ISSUE THREAD

**Issue by LiZ2z** [facebook/react#14295]
my code:
```javascript
<div className="App" >
    <label 
        onClick={e=>{
            console.log(e.nativeEvent)
        }}>
        click here
         <input type='input' />
    </label>
</div>
```
if you click the text 'click here', it will print twice, but if you click the input directly, it will print only once. i think the reason is when you click the text it will fired event once normally, but it will make the input element foucs and then it will fired a fake event which is not normal.

here is the two print msg:
first:
![image](https://user-images.githubusercontent.com/30578440/48816293-9cf79900-ed7c-11e8-9e15-d02fcaef889c.png)
second:
![image](https://user-images.githubusercontent.com/30578440/48816311-a7b22e00-ed7c-11e8-8ad9-42211a561a0e.png)

Windows10 17134.407
Chrome 70.0.3538.102
react ^16.6.1

**Comment by OliverRadini** [comment]
I don't believe this is an issue with React, I think this is to do with how events are handled more generally. At  least, this happens whether or not you're using React:

[With vanilla javascript](https://stackoverflow.com/questions/24501497/why-the-onclick-element-will-trigger-twice-for-label-element)
[With jQuery](https://stackoverflow.com/questions/8238599/jquery-click-fires-twice-when-clicking-on-label)

Those answers give some suggestions on how you can prevent this from happening, if it's causing a problem.

**Comment by LiZ2z** [comment]
@OliverRadini thank you !
