### ISSUE TITLE
React.lazy remounts component if used within a render

### ISSUE THREAD

**Issue by FredyC** [facebook/react#14299]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Simple reproduction here: https://codesandbox.io/s/6z4qmm2k7n

The contrived example does not make much sense, but I got burned by this in the context of react-router. I simply wanted to avoid defining all lazily loaded components up front but instead have them coupled with a particular route.

```jsx
function Routing() {
  <>
    <Route path="foo" component={lazy(() => import('./foo'))} />
  </>
}
```

**What is the expected behavior?**

In case this is intended behavior, it should be definitely documented. Otherwise it would be nice to have some memoized lazy variant. Possibly with hooks coming what about `useLazy` ? :)

**Comment by gaearon** [comment]
This is how regular React works. 

```js
function Routing() {
  <>
    <Route path="foo" component={function Foo() { /* ... */ }} />
  </>
}
```

has exactly the same issues. It's always bad practice.

If you feel concrete suggestions on whether this could be better documented, please feel free to send a doc PR.

**Comment by FredyC** [comment]
Yes, I understand why it's happening, but cannot it be improved? We are heading toward function components that are using memoization and in my opinion, it won't be that uncommon to define resources within a component to improve colocation.

Your example with defining a component within a render [can be tackled with `useMemo`](https://codesandbox.io/s/px528vzyx). It's bad practice, no argue there. However, with `React.lazy` it kinda makes sense to be able do that. However, when I tried to memoize result of `React.lazy` it did not help. I think it's a slightly different case and it could use some second thought.

**Comment by FredyC** [comment]
I did [another example build on Alpha](https://codesandbox.io/s/k27xkk1qzv) and with `useMemo` just to clarify why it's not working.

I am not trying to convince you that this is a feature that must be. It's just a suggestion what might be interesting to tackle in a future.  I am sure there might be several reasons I just don't see, especially the complexity of Suspense still kinda eludes me.

I will send the docs PR soon-ish.

**Comment by theKashey** [comment]
I reckon - it __never__ should work. You are giving a new type to React, it should unmount the old one, and mount a new one. This is NOT a remount.

**Comment by FredyC** [comment]
Ok wow, nevermind, fresh look after some time and I did spot a problem right away...

```js
const LazyLoadedMemo = React.useMemo(() => LazyLoaded);
```

I am missing the second arg to `useMemo`, once I add `[]` to denote no dependencies it starts working properly. That's epic fail :D

**Comment by ashkank83** [comment]
@FredyC Seems as I'm encountering a very similar issue. Did you manage to find a fix? I have created an example here [sandbox](https://codesandbox.io/embed/dynamic-comp-loading-sample-9zsc6). Would you please have a look and recommend a solution (if you know one?)

**Comment by FredyC** [comment]
@ashkank83 Some dirty solution is the following, but I don't like global variables, so I don't recommend doing that...

```jsx
const cached = {}

function DynamicLoader(props) {
  if (!cached[props.component]) {
    const LazyComponent = React.lazy(() => import(`${props.component}`))
    cached[props.component] = (
      <Suspense fallback={<div>Loading...</div>}>
        <LazyComponent />
      </Suspense>
    )
  }
  return cached[props.component]
}

```

**Comment by ashkank83** [comment]
@FredyC  Thanks for the reply. Since posting the question, I got the following as well as a potential solution 
```
const DynamicLoader = React.memo(function(props: any) {
  const LazyComponent = React.lazy(() => import(`${props.component}`));
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <LazyComponent />
    </Suspense>
  );
});
```

Not sure if there are cons and pro to the different solutions. As you said as well, I prefer to avoid the global variable, so maybe React.memo is prefered. What do you think?

**Comment by FredyC** [comment]
@ashkank83 That's probably better, but it depends how permanent is a cache of `React.memo`. We know that `useMemo` is not reliable and can be recomputed randomly. If the same thing applies to `React.memo` and React decided to clear up memory you might randomly lose state data. Docs state the following...

> This method only exists as a performance optimization. Do not rely on it to “prevent” a render, as this can lead to bugs.

Sounds risky enough to me. I don't know, I've given up on that as it's not that horrible to do it recommended with manual calls of `React.lazy`.

**Comment by dhedey** [comment]
For the benefit of others reading this, an approach to persisting the lazy references `useRef` is in my comment here: https://github.com/reactjs/reactjs.org/pull/1422#issuecomment-508539226

As FredyC refers to in previous comments, this has benefits over `useMemo` (which isn't guaranteed to be persist, risking the reference and hence state changing).

Using global module state (as in Fredy's above comment) is possibly preferable to `useRef`, depending on whether you want to lost the reference / get a new reference when the parent element gets unmounted/remounted.

**Comment by jvivasclimate** [comment]
@gaearon any insights on this? I considered React.lazy to have the same behavior as a regular react component. Meaning that it will be "rendered" equally as other Components. But the Component instance changes after every render. 
@FredyC we are planning on using something pretty similar to what you suggested. Not sure if its the best idea to hold a dictionary of Components just to keep the instance alive.

**Comment by theKashey** [comment]
Again - this is how it __should__ work.
Lazy creates a complex object, which tracks the promise resolution state inside it and that state should be initiated after component creation (as long as Lazy is a pure function).
That basically means - lazy would not be "ready" for use just after creation, except the cases with _synchronous thenables_ dynamic imports are not.

**Comment by Haraldson** [comment]
I’m experiencing a similar issue with `react-router`, `React.lazy` and `React.Suspense`. For now it’s making lazily loaded top-level routes unusable, in cases where there are nested routes as well. In such a scenario, my top-level route’s component will also act as sort of a layout for the nested stuff, but because of the top-level `React.Suspense`, I will get a flashing loading state from it no matter what. What I want is, of course, for all the static layout elements within the top-level route’s component to stay put.

This in turn comes from how `react-router` works: My top-level `<Route>` can’t be set to be `exact` because its component need to stay in place to handle its sub-routes. Thus, when you follow links to nested paths, both the top-level _and_ the sub-level route will match anew, and their components will be remounted.

Now, if only `React.lazy` would somehow keep track of which bundles had already been lazily imported, and return those instead of fetching them again, we wouldn’t have to go through this whole dance, because `React.Suspense` wouldn’t be notified since no async stuff would happen.

**Comment by theKashey** [comment]
> Now, if only React.lazy would somehow keep track of which bundles had already been lazily imported

Of course it never will do it - there is no way to know what is "behind import" before calling it. Use "SSR-friendly" code splitting libraries to "track" "loaded" "bundles"

**Comment by Haraldson** [comment]
So what I’m reading between the snark here is that `React.lazy`, with its default to always refetch code, isn’t really for anyone but a fast-paced ‘Facebook’ where reality dictates that code indeed could have changed, even between two calls to load the same bundle within the same session?

I’m not concerned with SSR for the moment, why are you recommending to use SSR techniquies to solve a problem you said isn’t a problem and isn’t solvable in the sentence before?

**Comment by theKashey** [comment]
Because you are missing the point @Haraldson.
- `React.lazy` is __always__ returning a new component. Because it's a factory
- every `lazy` has an internal state, which knows is it `not-loader`/`loading` or `loaded`. Once it "loaded" - __it never refetches the code__. NEVER.
- `lazy` expects some `importer` - a function which will return a Promise with `default`, and it could be anything. It could not, and should "think" what it is, and every time you will give it a "new" importer. The same problem as with "new" lazy itself.
- However, SSR requires to "knew" which bundles has to be loaded to fulfil requirements for "lazy components" on the current page. This is "the track" you are looking for.

For example - `loadable-components` will use babel-plugin to extract file name from `import`, and will synchronously import required component, as long as they "knew" - their code is loaded.
However, as long as any factory will generate a unique result every time - you will experience a full tree remount. Like using a different `key` on the node.

So, please, just try to understand how it works, why it works that way, and why it's not working for your case, and what's is wrong with your case.

**Comment by maulik-soni** [comment]
**Implementation:**
```
const LazyloadComponent = componentPath => (showLoader = true) => {
  return props => {
    let [ComponentContainer, setComponentContainer] = useState(null);

    useEffect(() => {
      const path = componentPath();
      setComponentContainer(lazy(() => path));
    }, []);

    return (
      <Suspense fallback={showLoader ? <LoadingSpinner /> : null}>
        {ComponentContainer && <ComponentContainer {...props} />}
      </Suspense>
    );
  };
};
```
**Usage :** 
```
const Component = LazyloadComponent(() =>
  import('../components/your/path')
)(true || false); // flag for hide/show of loader in suspense.
```

**Comment by hypeJunction** [comment]
Solution from @maulik-soni works for me if I wrap the output in `useMemo`

```js
const CodesIndex = useMemo(() => LazyloadComponent(() => import('./Screens/Codes'))(true), []);

return (
   <Route path="/codes" components={CodesIndex} />
);
```

**Comment by landisdesign** [comment]
Might I suggest another wrapper option, building on @maulik-soni's work? Use a closure to retain the reference to the to-be-built component:

```js
const buildLazyComponent = (path, loader = null) => {
  let LoadedComponent = null;

  const LazyComponent = (props) => {
    if (!LoadedComponent) {
      LoadedComponent = lazy(() => import(path));
    }
    return (
      <Suspense loading={loader}>
        <LoadedComponent {...props} />
      </Suspense>
    )
  };

  return LazyComponent;
}
```

Usage:
```js
const MyComponent = buildLazyComponent('./myLazyComponent', <Loading />);
```

**Comment by ahmed-zhran** [comment]
### _lazy_ with _forwardRef_ and _memo_ 🙃:
great wrapper I was trying to use **lazy** component with **forwardedRef** component at the same time from a while @landisdesign 
...just I wrapped the return function by forwardRef and it works perfectly

```
import React, { forwardRef, lazy, Suspense } from 'react';

const loadable = (importFunc, { fallback = null } = { fallback: null }) => {
  let LazyComponent = null;
  const loadingComp = forwardRef((props, ref) => {
    !LazyComponent && (LazyComponent = lazy(importFunc));
    return (
      <Suspense fallback={fallback}>
        <LazyComponent {...props} ref={ref} />
      </Suspense>
    )
  });
  return loadingComp;
};


export default loadable;
```

usage:

`export default loadable(() => import('./someComponent.jsx'));`

just a note the **someComponent** should be wrapped on **forwardedRef** as well if you wish to use the ref and also it can be wrapped with **memo** with no problems 😊😊😊😊

component example '.someComponent.jsx' : 

```
import React, { memo } from 'react';
import Typography from '@mui/material/Typography';

const SxText = forwardRef(function SxText({children, props}, ref) {
  return (
      <Typography {...props} ref={ref}>
        {children}
      </Typography>
  );
})

SxText.propTypes = {};

export default memo(SxText);
```

**Comment by landisdesign** [comment]
@ahmed-zhran oops! I forgot that part! Good catch. I'll edit my attempt above to put it all in one place.
