### ISSUE TITLE
Install all imported libraries on save

### ISSUE THREAD

**Issue by abhiravredox** [facebook/react#14296]
I would like to propose a new feature and work on it's implementation. 

Currently, it is required for a developer to install a library using 'npm install $library_name' before the library can be imported and used.

I propose that once the developer imports and saves the .js file all the uninstalled imports are 'npm install'ed. I would like to work on this change.

**Comment by nmain** [comment]
React has no control over this.

It is something you could implement in an IDE or a build tool.  Looks like that's been discussed and/or done a few times:

https://github.com/Microsoft/vscode/issues/2590
https://github.com/parcel-bundler/parcel/issues/376
https://github.com/webpack-contrib/npm-install-webpack-plugin
https://marketplace.visualstudio.com/items?itemName=moshfeu.auto-npm-install

**Comment by jquense** [comment]
yes there are a few options for this in the editor space, but it's not something React can implement
