### ISSUE TITLE
Hooks: useEffect() more intuitive approach

### ISSUE THREAD

**Issue by demil** [facebook/react#14294]
When we have 

    useEffect(() => { 
            // this function seems to be called on initial and all subsequent renders
            subscribe()
            return () => { unsubscribe () } // and it is creating new function which is not even intended to be used on every render
   })

isn't react creating a new function on every render and function not which is not even intended to be used because it should be used only when component unmounts, and isn't this subscribe function called on every render which is not intended ( it needs to be called only on initial mount ) and then calling clean up function also on every render, or in some cases we need to wrap in to condition to handle if we need to subscribe or unsubscribe? And besides that this paradigm isn't really intuitive and semantic - subscribe in function and unsubscribe in return function. 

Maybe this seems to be better aproach?

    useEffect(() => { 
                // called only once on component init, create function only once
                // return object with functions for initial mount, render and unmount
                mount: () => { subscribe() }, // this is called on mount
                render: () => { consle.log("rerender")  }, // this is called on every render 
                unmount: () => { unsubscribe() } // this is called on unmount
            }
   );

And this is clearly more intuitive and semantic. 

I completely understand that in some cases destroying subscriptions on every render is good because it makes component more robust and bug resistful but it also may impact on performance and if we know what are we doing performance is most important thing.

What are your thoughts about this idea?

**Comment by shinima** [comment]
`useEffect` accepts a second arugment `inputs` which can control when effects should *fire*.

> The default behavior for effects is to fire the effect after every completed render.

But if you supply an `inputs` carefully, you get the same functionality as returning an object with shape `{ mount, render, unmount }`.  See more detail [here](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect).

**Comment by gaearon** [comment]
>isn't react creating a new function on every render and function not which is not even intended to be used because it should be used only when component unmounts, and isn't this subscribe function called on every render which is not intended ( it needs to be called only on initial mount ) and then calling clean up function also on every render, or in some cases we need to wrap in to condition to handle if we need to subscribe or unsubscribe?

Both of these points are addressed in the documentation. Please give it a read.

https://reactjs.org/docs/hooks-effect.html#explanation-why-effects-run-on-each-update
https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects

>I completely understand that in some cases destroying subscriptions on every render is good because it makes component more robust and bug resistful but it also may impact on performance and if we know what are we doing performance is most important thing.

This is very vague and therefore hard to answer. I believe the above links address it though.
