### ISSUE TITLE
Provide a way to pass context to renderToStaticMarkup on the client

### ISSUE THREAD

**Issue by gaearon** [facebook/react#14292]
See https://github.com/facebook/react/issues/14287#issuecomment-440277999 and https://github.com/facebook/react/pull/14182#issuecomment-440125029. This accidentally worked for a few releases but was a bug. However we might want to consider actually supporting this with an opt-in API.

**Comment by gaearon** [comment]
Generally, using SSR methods on the client is discouraged. Instead, it's better to render into a DOM node and then read `innerHTML` from it, for example. This also solves the context issue.

**Comment by nomcopter** [comment]
@gaearon what are the advantages of that approach? Does the browser provide some normalization or other advantage?

**Comment by gaearon** [comment]
It's unfortunate to bundle a whole server renderer on the page just to produce HTML since you can already produce HTML just with React DOM. Additionally, if you do it in your component, you still have the context etc, which is what the original complaint was about.
