### ISSUE TITLE
Simplify the content in React HOC docs page

### ISSUE THREAD

**Issue by maibono** [facebook/react#14306]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It's hard to understand the Higher order components in the React documentation at 
https://reactjs.org/docs/higher-order-components.html
It would be great if simple examples are provided instead of the current page.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by marvinjude** [comment]
@maibono can you be more specific? what part(s) exaclty.

**Comment by gaearon** [comment]
We track documentation issues in https://github.com/reactjs/reactjs.org — please file it there.
