### ISSUE TITLE
How can I augment (e.g. extend, patch, stub, etc.) out core ReactDOM functions?

### ISSUE THREAD

**Issue by FarhadG** [facebook/react#14300]
I'd like to modify some of the inner workings of the `ReactDOM` implementation with some auxiliary info. That being said, instead of writing a custom renderer from scratch that mimics all of ReactDOM, I'm thinking of simply extending it by patching/stubbing/etc. the functions I need to augment.

Any advice on how to do this? When I import `ReactDOM`, only a few functions are exposed (e.g. `render`), but I need access to many of the inner methods of the `hostConfig`, such as `createInstance`, `appendChild`, `commitUpdate`, etc.

Thanks, in advance, for the guidance!

**Comment by gaearon** [comment]
I don't think there's any supported way to do that — we intentionally use a compilation step to inline host config methods into the reconciler code for better perf. Forking ReactDOM might be your best option here.

**Comment by FarhadG** [comment]
Will do, @gaearon! Just started looking at the React codebase and was wondering if it would be best to fork entire `React` repo or pull out just `ReactDOM`? I ask, because it seems like I would have to fork entire `React` to be able to build/work with `ReactDOM`?

**Comment by gaearon** [comment]
`packages/react-dom` + anything it uses (`packages/shared` and `packages/events`)

**Comment by FarhadG** [comment]
Got you, @gaearon! Any tips on how to build it? I don't see any scripts in the `package.json` within that package.

**Comment by gaearon** [comment]
Build scripts work on top level only. `yarn build react/index,react-dom/index --type=UMD,NODE`

**Comment by LFFATE** [comment]
I think the easiest way to do it: just export host config within reactDom default export. So it can be used as collection of default methods like:
```
const hostConfig = {
   ...reactDom.hostConfig,
  createInstance: (...) => {...}
}
```

If it isn't breaks some reactDom/react ideology. So in theory it just requires a simple PR to share this feature
