### ISSUE TITLE
Warning `getSnapshotBeforeUpdate` without `componentDidUpdate`

### ISSUE THREAD

**Issue by lytc** [facebook/react#14318]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`Warning: Component: getSnapshotBeforeUpdate() should be used with componentDidUpdate(). This component defines getSnapshotBeforeUpdate() only.`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Use `getSnapshotBeforeUpdate` without `componentDidUpdate`

**What is the expected behavior?**
In the use case that I want to get the bounding rect of the DOM element before update by using `getSnapshotBeforeUpdate`, ResizeObserver will trigger the update if DOM rect changes and compare for the change to do FLIP animation, which I don't need to do anything on `componentDidUpdate`.
I think it's legit so we shouldn't warning!

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.6.3

**Comment by gaearon** [comment]
If you perform some kind of animation, it should go into `componentDidUpdate`.
