### ISSUE TITLE
[Q] useEffect + SSR ?

### ISSUE THREAD

**Issue by hrasoa** [facebook/react#14315]
How can we fetch data on the server-side with hooks ? I'm working with ```apollojs``` all my calls are inside the ```useEffect``` hook, so they won't be found when I'll call ```getDataFromTree``` on the server [(https://www.apollographql.com/docs/react/features/server-side-rendering.html)](https://www.apollographql.com/docs/react/features/server-side-rendering.html):

```javascript
  useEffect(() => {
    client
      .query({
        query: gql`
          {
            players {
              name
              image
            }
          }
        `,
      }).then(result => console.log(result));
  }, []);
```

**Comment by idangozlan** [comment]
@hrasoa did you manage to tackle it?

**Comment by hrasoa** [comment]
@idangozlan no, but apollo now uses hooks, so I guess we can do ssr easily now.
