### ISSUE TITLE
Nullifying value on <progress /> should return component to indeterminate state

### ISSUE THREAD

**Issue by steveluscher** [facebook/react#1431]
**Expected**:

Given a `<progress />` component, when its value property transitions from being a float to being `null`, I expect the `value` attribute of the `<progress>` tag to become unspecified, putting the control in the "indeterminate" state (the state with the animating barbershop pole pattern).

**Actual**:

When transitioning from being a float to being `null`, the value attribute of the `<progress>` tag becomes `"0"`.

**Test case**:
http://jsfiddle.net/kb3gN/1981/

**Comment by syranide** [comment]
#1510 has landed in 0.15 and solves the underlying issue, but due to a separate issue this is not actually solved. Being tracked at #6119.

**Comment by nhunzaker** [comment]
Looks like this issue closed:
https://github.com/facebook/react/issues/6119

I've just verified. This is fixed!
https://jsfiddle.net/84v837e9/120/
