### ISSUE TITLE
getDerivedStateFromProps is user-hostile

### ISSUE THREAD

**Issue by loganb** [facebook/react#14321]
So I think `getDerivedStateFromProps` as designed turns out to be user-hostile. The short summary is that it makes the pattern described in the docs, https://reactjs.org/docs/higher-order-components.html#use-hocs-for-cross-cutting-concerns, impossible for non-trivial cases. 

Imagine implementing an HOC that listens to change events on a DataSource, but where a simple shallowEqual() on the resultant state isn't sufficient to prevent rendering. I.e., what if you need more complex logic to determine if new data from the DataSource should be applied? 

In my case, I have a DataSource that doesn't guarantee that it will give out objects of the same identity, so a `===` check will always return false and cause a re-render. BUT, I can do a little bookkeeping on the side and determine whether the data is actually new and should therefore be loaded into state. 

This leads to some problems: 
1) Because `getDerivedStateFromProps` is static, it's not possible to store some internal bookkeeping data on the Component instance that gets used to determine whether to query the DataSource. Worst case, this bookkeeping information could be stuffed in the state object, but that's unnecessarily constraining and a bit ugly from a code organization perspective. 
2) More importantly, it's not possible to determine why `getDerivedStateFromProps` is being called. Is it because of a props change? Or is it because of a "change" event firing on the `DataSource`? 

This matters because if props have changed, data must be fetched and the Component re-rendered unconditionally, but if the props haven't changed, then it's possible all the data loaded is the same as last time, and so `render()` can be skipped. 

Here's an example using the deprecated API that's no longer possible, lightly edited from the HOC example I mention above: 
```
function withDataLoading(Component, DataSource, getDataFunc) {

  return class extends React.PureComponent {
    componentDidMount() {
      // Subscribe to changes
      DataSource.addChangeListener(this.handleChange);
    }
  
    componentWillUnmount() {
      // Clean up listener
      DataSource.removeChangeListener(this.handleChange);
    }

    componentWillReceiveProps(props) {
      //Unconditionally update state and rerender since the props changed
      const possiblyNewData = getDataFunc(DataSource, props, this)
      this.setState(possiblyNewData);
      //Remember some metadata about what we fetched for next time
      this.bookkeeping = DataSource.bookkeepingData();
    }
  
    handleChange() {
      // Update component state whenever the data source changes
      const possiblyNewData = getDataFunc(DataSource, this.props, this)
      if(DataSource.didIFetchNewData(this.bookkeeping)) {
        //The DataSource had updated data in it, so rerender
        this.setState(possiblyNewData);
        //Remember some metadata about what we fetched for next time
        this.bookkeeping = DataSource.bookkeepingData();
      } else {
        //No new data was fetched, so don't update State and don't rerender
        //Do nothing…
      }
    }

    render() {
      <Component data={this.state}/>
    }
  }
}
```

Notice that the behavior is different between `componentWillReceiveProps` and `handleChange`. There's no way to make that distinction with the new API.

**Comment by gaearon** [comment]
Have you had a chance to read through this [blog post](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) and try to apply it to your scenario? I think it should clear up why relying on a difference between "props update" and "state update" is fundamentally flawed and is a source of many bugs.

**Comment by loganb** [comment]
Hi @gaearon, Yes! I read that post multiple times while trying to construct a working solution in the new world order. The fundamental problem is that it's not possible under the new design to build any custom logic to avoid unnecessary renders.

**Comment by gaearon** [comment]
I don't see why not — you can do this:

>Worst case, this bookkeeping information could be stuffed in the state object

If you provide a small runnable demo I can take a look in more detail.
