### ISSUE TITLE
请问不做任何处理，react可以兼容到IE多少

### ISSUE THREAD

**Issue by yizhengfeng-jj** [facebook/react#14323]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by thoamsy** [comment]
If you don't provide any polyfill, at least IE 11 is required.

**Comment by blling** [comment]
IE9

**Comment by threepointone** [comment]
If I understand correctly, are you having IE compatibility issues? Have you tried the steps in https://reactjs.org/docs/javascript-environment-requirements.html? (I found a translation here that might help https://react.docschina.org/docs/javascript-environment-requirements.html)

If those steps don't work, could you please make a small, minimal failing testcase (with the above steps included) on codesandbox? https://codesandbox.io/s/new That will help us isolate any issues if any.

**Comment by fanzhengbiao** [comment]
Minimun IE9

**Comment by CoolRice** [comment]
至少 IE 11
