### ISSUE TITLE
[react-dom] getEventKey has IE11 key mapping issue

### ISSUE THREAD

**Issue by icfantv** [facebook/react#14337]
**Do you want to request a *feature* or report a *bug*?**

Bug (possibly)

**What is the current behavior?**

This may, in fact, fall under the purview of `Only special keys are supported, all others depend on keyboard layout or browser` but figured I'd enter this to be sure.  Additionally, the bookmark in the link specified in the `@see` comment is no longer valid so I can't confirm the official list of keys.  Looking at [the latest version of the spec](https://www.w3.org/TR/uievents/#determine-keydown-keyup-keyCode), the key in question appears in the `Optionally fixed virtual keys` section rather than the `Fixed virtual keys` section, but then, none of the 1xx keys appear at all in the fixed list.

The `translateToKey` hash in the `react-dom` package's `getEventKey` function appears to be missing the `-` (dash) key.  When used with CTRL+SHIFT, this key (and probably others) is reported as `Unidentified` in IE11 and since it's not in the `translateToKey` map, returns back to the code as `Unidentified` which breaks keyboard shortcut handling.

This can be seen by navigating to https://w3c.github.io/uievents/tools/key-event-viewer.html and in IE11, pressing `CTRL + SHIFT + -` (note that you will need to check `keydown` under `preventDefault` in the options table or the browser will zoom out.

**What is the expected behavior?**

If it's a bug, it shouldn't allow resolution to just fall through back to the browser.  If it's not, then the code is correct - but then requires special handling.

If I add `'189': '-'` to the hash, it works...on a US Keyboard.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested on React 16.6.1 in IE11 on Windows.

**Comment by icfantv** [comment]
As an update to this (given the bot comment), we've simply incorporated the same KB event mapping used by React into our keyboard shortcut handling logic (which we have to have anyway) and added the dash character to the map to properly support this in our application.

I'm not suggesting it doesn't still require further investigation, but we do have a work-around and I would probably consider this of very low priority.  That is to say, my feelings would not be hurt if you guys decided to close this.

**Comment by gaearon** [comment]
We are dropping support for IE in React 18, so this won't get a fix.
Sorry.
