### ISSUE TITLE
Name chunk when lazily importing with React.Suspense

### ISSUE THREAD

**Issue by josh08h** [facebook/react#14344]
**Do you want to request a *feature* or report a *bug*?**
Request.

**What is the current behavior?**
I can't provide a way to name the newly created chunk.

**What is the expected behavior?**
Be able to name the chunk when using React.Suspense, similar to  import(/* webpackChunkName: "print" */` syntax.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6.3

**Comment by threepointone** [comment]
could you share an example repo of this not working? it should just work. in any case, this is probably a bug you should file with webpack, not react.

**Comment by josh08h** [comment]
Ah yes, apologies it is working as expected!
