### ISSUE TITLE
[React Upgrade] Facing issue while upgrading React Version 15.6.2 to 16.6.3

### ISSUE THREAD

**Issue by vidhyeshpatil** [facebook/react#14348]
Upgrading react version from 15.6.2 to 16.2.0. 

But facing below issues while running build of the application,

 ERROR in ../node_modules/react-addons-update/index.js
[INFO] Module not found: Error: Can't resolve 'react/lib/update' in 'D:\Projects\MyTask\web\node_modules\react-addons-update'
[INFO]  @ ../node_modules/react-addons-update/index.js 1:17-44

**package.json**
"react": "^16.6.3",
"react-dom": "^16.6.3"

Can you help me out with the solution on the above problem ?

**Comment by devrchancay** [comment]
What is the process you did?

you changed in the `package.json` or did `npm install -g react@16.2.0 react-dom@16.2.0`

> Try deleting the `node_modules` folder and the` package-lock.json` or `yarn.lock` file and try again

**Comment by gaearon** [comment]
Update `react-addons-update` to the latest version.
