### ISSUE TITLE
ReactNativeRenderer-prod.js Module scheduler does not exist in Haste module map

### ISSUE THREAD

**Issue by mredem96** [facebook/react#14341]
Unable to resolve module `schedule/tracking` #21150 

I saw tried all solutions but it not working

react  16.5.1
react-native 0.57.7

schedule 0.4.0
react-test-renderer 16.4.1

OS MacOS mojave

**Comment by ziyoshams** [comment]
Have the same issue, but with `scheduler`.

**Comment by xufeipyxis** [comment]
Just FYI, I'm having the same issue, but on react-native.

**Comment by bilalma** [comment]
I'm also facing this issue.
these kind of errors are changing my plan to further work on React-native

**Comment by tr0yspradling** [comment]
> I'm also facing this issue.
> these kind of errors are changing my plan to further work on React-native

Welcome to the new age of framework centric development. Loads of dependencies & packages to worry about when troubleshooting.

**Comment by SujataSwamy** [comment]
I am facing similar issue

react 16.3.1
react-native 0.58.3

Unable to resolve module `scheduler` from `D:\sujata\final react\reactnative\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-prod.js`: Module `scheduler` does not exist in the Haste module map

The below steps were printed on console.

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

Following the above steps didnot help me. 

If anyone's knows the solution , Please help

**Comment by ziyoshams** [comment]
Try upgrading your react `npm i react@latest`.

**Comment by gaearon** [comment]
Please report React Native issues in the react-native repository. They get lost here.
