### ISSUE TITLE
Problem with lazy import of a lazy component

### ISSUE THREAD

**Issue by claramunt** [facebook/react#14351]
When a lazy component is lazy imported its not recognized as a component.
example running at --> https://codesandbox.io/s/z24ozy1mnx

**Comment by aweary** [comment]
Hey @claramunt! This is expected behavior, you're wrapping an export in `lazy` that has already been wrapped with `lazy`. You can't nest `lazy` calls like that. https://github.com/facebook/react/pull/14298 improves the error message for this to make this clearer. 

Thanks!
