### ISSUE TITLE
Table-element border glitch on React update

### ISSUE THREAD

**Issue by 3nvi** [facebook/react#14350]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When the rows of a table with a collapsed `border` are re-ordered through a `setState`,  a border glitch is caused in some of the `<td>` elements of a table.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Live example: [https://codesandbox.io/s/vjn3n7qm65?moduleview=1](https://codesandbox.io/s/vjn3n7qm65?moduleview=1)

In order to reproduce this bug one must create a table with more than 1 rows of data. The `<table>` must have the CSS style `border-collapse: collapse`, as well as a big border (for example `border: 10px solid red)`. Each table row must have a unique `key` (in order not to be re-created by React on subsequent renders)

The initial mount of the table gives the table elements a height based on their content without any border. When a re-order of the rows occurs (through a React state update), some of the `<td>` elements of the first row get a border as well.

This is can be "fixed" by either:
  
   * Removing the border from the `<table>` element or removing its `border-collapse: collapse`.

   * Removing the keys from the rows (causing new instances to be created in the DOM by React)

The only reason I'm submitting this as a React issue is the fact that by removing the `key` attribute of React, this behaviour is no longer encountered. Please close it if it's unrelated with React.

**What is the expected behavior?**

The height & border of the the table rows should be the same as when mounted

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Using the latest create-react-app (React v16.6.3 & ReactDOM 16.6.3)

**Comment by 3nvi** [comment]
**Update**: Might be a webkit issue as well, since this behaviour doesn't seem to appear in Firefox

**Comment by aweary** [comment]
@3nvi you can try recreating this demo with just the native DOM APIs like `createElement` and `appendElement` and see if the issue still occurs. If you inspect the DOM and all the attributes seem correct then its unlikely that this is a React bug. React doesn't have any special layout logic, it just forwards your styles to the DOM.

> Update: Might be a webkit issue as well, since this behaviour doesn't seem to appear in Firefox

I'm going to close this out as it's almost certainly not a React bug, but if you can isolate this specifically to React (by creating an identical demo without it that doesn't have the bug) I'm happy to re-open and investigate. 

Thanks!
