### ISSUE TITLE
Hooks: callback in useEffect is not always fired in same time.

### ISSUE THREAD

**Issue by morlay** [facebook/react#14354]
**Do you want to request a *feature* or report a *bug*?**
maybe a **bug**?

**What is the current behavior?**
see bellow.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```js
import React from "react";
import { render } from "react-dom";
import { useState, useLayoutEffect, useEffect } from "react";

function App() {
  const [mounted, setMount] = useState("");

  useEffect(() => {
    console.log("App effect");
    setMount(s => s + "App mounted;");
  }, []);

  useLayoutEffect(() => {
    console.log("App layout effect");
    setMount(s => s + "App layout mounted;");
  }, []);

  return <div>{mounted}</div>;
}

function App2() {
  const [mounted, setMount] = useState("");

  useEffect(() => {
    console.log("App2 effect");
    setMount(s => s + "App2 mounted;");
  }, []);

  useLayoutEffect(() => {
    console.log("App2 layout effect");
  }, []);

  return <div>{mounted}</div>;
}

test("test App", () => {
  const node = mount(<App />);
  console.log("mounted", node.innerHTML);
});

test("test App2", () => {
  const node = mount(<App2 />);
  console.log("mounted", node.innerHTML);
});

function mount(e) {
  const node = document.createElement("div");
  render(e, node);
  return node;
}
```
[![Edit 3vv85q81x6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3vv85q81x6)
run the tests, and see the log.

**What is the expected behavior?**
```
App layout effect 
App effect 
mounted <div>App layout mounted;App mounted;</div> 
App2 layout effect 
App2 effect
mounted <div>App2 mounted;</div> 
```
But got 

![image](https://user-images.githubusercontent.com/1667873/49198532-77970a80-f3ce-11e8-8952-54562bc2d1e8.png)

after useEffect callback firing in `App2`, we can't get re-rendered dom.
btw, in codesandbox, log the `App2 effect`, but in local node env, will lost the log `App2 effect` 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 
* react 16.7.0-alpha.2
* react-dom 16.7.0-alpha.2
* node 10.13.0
* macOS mojave 10.14.1

**Comment by KpjComp** [comment]
I'm new to React, but your output to me looks correct.

In both cases we have -> 
App layout effect 
App effect 
App2 layout effect 
App2 effect

You can ignore the mounted parts, because it's not even part of the React component.

From what I can tell, React is not totally synchronous, it uses a fiber a stack.    I'm assuming this is prevent successive DOM comparisons on multiple setStates etc.

So what I would suggest is that you treat `mount();`, like any Javascript asynchronous method.  If you do this your output makes total sense.

**Comment by gaearon** [comment]
I think the request here is the same as https://github.com/facebook/react/issues/14050.
