### ISSUE TITLE
[Mouse Events] onMouseDownCapture is not stopping capture phase propagation

### ISSUE THREAD

**Issue by andrescabana86** [facebook/react#14355]
**Bug report**

**The current documentation has and I quote https://reactjs.org/docs/events.html**
** -To register an event handler for the capture phase, append Capture to the event name; for example, instead of using onClick, you would use onClickCapture-**

**I tried with this https://jsbin.com/hilome/edit?js,output and**

`<div id="grandparent" onClickCapture={this._handleClickCapture}>
          <div id="parent" onClick={this._handleClickBubble}>
            <button id="elem" onClick={this._handleClick}>Click me!</button>
          </div>
        </div>`

**if I change onClickCapture with onMouseDownCapture the stopPropagation() method does not prevent capture phase any more**

**What is the expected behavior?**

**I would expect that stopPropagation() stops the propagation to its children as it works with onClickCapture event**

**Comment by heyimalex** [comment]
I'm having trouble understanding? At least the jsbin link seems to work as expected for me. If the only thing you're changing is `onClickCapture` => `onMouseDownCapture` it's not going to work because click and mousedown are different events.

**Comment by andrescabana86** [comment]
So you mean that onMouseDownCapture can't stop capture phase propagation?

**Comment by heyimalex** [comment]
I'm saying `onMouseDownCapture` can't stop propagation of click events, because they're different events. If you change `onClickCapture` => `onMouseDownCapture` _and_ `onClick` => `onMouseDown` then it should work.

Am I understanding you correctly? Can you make another jsbin with the broken behavior?

**Comment by andrescabana86** [comment]
Yes, you are right. It works if I use the same type of event. So I can't prevent propagation to its children if the children have a different type of event.
