### ISSUE TITLE
Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`

### ISSUE THREAD

**Issue by btd** [facebook/react#1436]
The same happen with 0.10 and master.
I am sorry i could not  make reproducible test case.
That is stack trace for master:

```
invariant invariant.js:52
getID ReactMount.js:79
ReactMount.isRenderedByReact ReactMount.js:533
ReactMount.getFirstReactDOM ReactMount.js:548
handleTopLevelImpl ReactEventTopLevelCallback.js:63
Mixin.perform Transaction.js:159
ReactDefaultBatchingStrategy.batchedUpdates ReactDefaultBatchingStrategy.js:70
batchedUpdates ReactUpdates.js:35
ReactEventTopLevelCallback.createTopLevelCallback ReactEventTopLevelCallback.js:151
```

And for 0.10

```
invariant invariant.js:52
getID ReactMount.js:79
ReactMount.isRenderedByReact ReactMount.js:532
ReactMount.getFirstReactDOM ReactMount.js:547
handleTopLevelImpl ReactEventTopLevelCallback.js:64
ReactEventTopLevelCallback.createTopLevelCallback ReactEventTopLevelCallback.js:140
```

Generaly happen such things:
Main component render first time `img`, then componentDidMount get data via ajax, and on response it update state, then in render `img` replaced with another component. In moment later it call react trap for 'load' event on previous `img` and exception happen.

I appreciate feedback and help with issue. I have public link for debuging, but i could not share it with public, so if someone want to see it in action let me know pls.

**Comment by robinma** [comment]
have a same data-id.you mouse mine another plugin tools copy same dom. example swiper loop param.it will copy same dom  in you DOC. 坑
