### ISSUE TITLE
useReducer: dispatched actions are reduced twice

### ISSUE THREAD

**Issue by ioss** [facebook/react#14360]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*

**What is the current behavior?**
There are cases where actions dispatched by `useReducer`'s dispatch function are reduced twice (in concurrent mode).

As far as I can tell from my first quick read of the code of react-dom (so I might be totally wrong!), this happens, when a higher priority action is added to a queue that already contains lower priority actions.

On the first run, that is caused by for example an onClick handler (higher priority), the dispatched action is appended to the queue. On processing the queue the lower priority actions (for example from setInterval events)  are _ignored_ and the "onClick action" is reduced, but stays on the end of the queue, so that on the next time the queue is processed, that action gets reduced a second time.

See a testcase at:
https://codesandbox.io/s/nxq3w7rwl

Pressing the button increments the button (most of the time not always, depending if 'TICK' actions are in the queue) by two.

**What is the expected behavior?**
I'd expect a dispatched action to be only reduced once.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested with React 16.7.0-alpha.2 on Chrome (70.0.3538.110) and Safari (12.0.1) both on macOs

**Comment by gaearon** [comment]
This does look like a bug. Want to dig into it?

**Comment by ioss** [comment]
I'd love to, but I am not sure I understand the implications on messing with the action queue, there are quit a lot of special cases and as I wrote that was my first read of any react implementation code :)

If the solution would be as simple as to take the reduced action out of the queue (linked list), then I could give it a try.
Also it might take me a week or so, as I am pretty busy at the moment.

**Comment by gaearon** [comment]
Nice find :-)
