### ISSUE TITLE
Integrate external js lib

### ISSUE THREAD

**Issue by crim94** [facebook/react#14375]
I am creating a react application of video streaming but i am not able to integrate the sdk of the media server (Kurrento) which developed on plain javascript , when i try to import the file i get many syntax errors such as : no-undef and no-restricted-globals

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
