### ISSUE TITLE
If deprecate `componentWillMount`, how to copy `this.context` to state in the first mount?

### ISSUE THREAD

**Issue by manglobe** [facebook/react#14379]
https://codesandbox.io/s/3qjp037951
`static getDerivedStateFromProps` can't get the context value.
If update state in `componentDidMount`, the component will render once more.

**Comment by nisalVD** [comment]
Do it in the constructor

**Comment by manglobe** [comment]
@nisalVD   In constructor `this.context` get `undefined`. My demo shows it.

**Comment by nisalVD** [comment]
You can use a HOC and pass the context as props 
https://codesandbox.io/s/zklp332wq4

**Comment by manglobe** [comment]
@nisalVD Thanks, I knew this way.  But I don't think we should write `Context.Consumer` just for this.
On the other hand, I'm trying to write React without `react-redux`, `Context.Consumer` ,`Context.Provider`, sometimes it just makes the simple project become complex.

**Comment by hamlim** [comment]
The second argument provided to the `constructor` is the `context` value, so you can accept it and then access it within your constructor:

```js
class App extends Component {
  constructor(props, context) { // note second argument here
    super(props, context);
    console.log(this.context, "constructor");
  }

  static contextType = context;

  componentDidMount() {
    console.log(this.context, "DidMount");
  }

  render() {
    console.log("render");
    return <div>123</div>;
  }
}
```

I forked your original sandbox applying the snippet above: https://codesandbox.io/s/o4y3nvvw39

**Comment by manglobe** [comment]
@hamlim That's amazing, I find it! https://reactjs.org/docs/legacy-context.html#how-to-use-context
It seems that I didn't read the document clearly. Thanks! :)
