### ISSUE TITLE
Allow suppressing the warning for missing keys.

### ISSUE THREAD

**Issue by flying-sheep** [facebook/react#14374]
There are valid use cases for not wanting to use keys, if you e.g. render strongly differing trees (like e.g. blog posts) or have a function that returns always the same array of items.

When you don’t provide an explicit key, React will internally use the index as key and emit a warning – however you would want to silence the warning, as using the index here is perfectly valid.

This doesn’t currently seem to be possible however, which has the sad consequence that you either have to make your code more complex for no reason (manually adding useless keys) or you have to live with the warnings (which means that valid warnings might be lost among the noise).

The [article](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318) quoted in the [docs](https://reactjs.org/docs/lists-and-keys.html#keys) states the conditions in which using the default behavior is valid:

> 1. the list and items are static–they are not computed and do not change;
> 2. the items in the list have no ids;
> 3. the list is never reordered or filtered.

**Comment by aweary** [comment]
> using the index here is perfectly valid.

In that case why not just add the index as the `key`? I get that it's *technically* not required, but the fact that React uses the index as a fallback internally is an implementation detail that you shouldn't rely on. If the index is a valid key for the item, you should make that explicit.

Explicitly using the `index` in cases where its valid also makes it easier to refactor if, for some reason, the index *isn't* a valid key anymore. You used blog posts as an example. What if one day you added the ability to sort posts by date or title? In that case the index is no longer a valid key.

With an explicit `key` prop it's easy to identify this (especially for those who don't know that the index is used as a fallback internally) and refactor. If the warning was just suppressed it seems more likely that you'd miss this and introduce some tricky bugs.

> This doesn’t currently seem to be possible however, which has the sad consequence that you either have to make your code more complex for no reason (manually adding useless keys)

What would be your proposed API for suppressing the warning? There's precedence with the `supressContentEditableWarning` prop, but having `supressKeyWarning` seems just as verbose and using the index as the key.

**Comment by aweary** [comment]
> Also the docs explicitly say “If you choose not to assign an explicit key to list items then React will default to using indexes as keys” which can therefore be considered stable behavior.

Sorry, I missed that part. That would be considered stable behavior, though it's still implicit and the docs also state:

> When you don’t have stable IDs for rendered items, you may use the item index as a key as a last resort:

Which implies that you should be *explicitly* using the index in those cases. We probably need to fix the documentation, because the messaging is somewhat confusing here.

> I think `<parent suppressKeyWarning>{[<item/>, <item/>, …]}</parent>` would be great

Silencing the warning on the parent is problematic as you can have multiple lists with different key requirements.

```jsx
<div suppressKeyWarning>
   {/* No keys required here... */}
   {[<div>first</div>]}
    {/* But keys are required here, and the warning was suppressed! */}
    {this.state.items.map(item => <div>{item}</div>}
</div>
```

> we pass around less data than by doing `<parent>{[<item key={0}/>, <item key={1}/>, …]}</parent>`

It's less data than adding a key to every item in the array separately, like this example. In most cases you'd be mapping through a set of items

```jsx
<parent>{items.map(data => <item {...data} />}</parent>
```

In which case you'd be declaring the key once in the source

```jsx
<parent>{items.map((data, i) => <item key={i} {...data} />}</parent>
```

If you have a static list of items where you are explicitly adding `key` to every item you should use [Fragments](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) or remove the wrapping array all together when possible.

**Comment by flying-sheep** [comment]
> Which implies that you should be explicitly using the index in those cases.

And this is how I understand it, but I would prefer to use the simplest possible code for the simplest possible case. Why do something manually, noising up my code, if it’s done automatically anyway?

> Silencing the warning on the parent is problematic as you can have multiple lists with different key requirements.

You’re right. Thinking of it, the property “keys are not needed” pertains to the *array*. So maybe it should be a function that adds a custom property to an array that marks it as identity safe?

```js
<div>
    {/* No keys necessary */}
    {React.suppressKeyWarning([<div>first</div>])}
    {/* Warning thrown here */}
    {this.state.items.map(item => <div>{item}</div>}
</div>
```

Of course it could also be named `nokeys` or `identityIsKey` or whatever :smile: 

> It's less data than adding a key to every item in the array separately, like this example. In most cases you'd be mapping through a set of items

Exactly. And my code gets a bit more complex (I now have to use and pass on the index), and every item ends up with a useless key property that I’ll see in the debugger. That’s what I meant with data.

**Comment by hamlim** [comment]
This seems like it is already supported with the current React API:

```jsx
render(
  <ul>
    {React.Children.toArray([1, 2, 3].map(item => <li>{item}</li>))}
  </ul>
);
```

`React.Children.toArray` will already implicitly assign a key to each child it's provided: https://reactjs.org/docs/react-api.html#reactchildrentoarray.

**Comment by flying-sheep** [comment]
Thank you! If it doesn’t do too much unnecessary work and impacts performance, that’s almost what we’re searching for. Of course not actually adding the keys but simply marking the array as “no keys necessary” would be better for performance.

If that would end up being referenced in the keys section of the docs, I’d be happy.

**Comment by aweary** [comment]
@hamlim @flying-sheep we've discussed this before and concluded that `toArray` not warning for missing keys is a bug, see https://github.com/facebook/react/issues/11549. So don't rely on that behavior.

> Why do something manually, noising up my code, if it’s done automatically anyway?

For the reasons mentioned above, I think relying on implicit keys is actually _more_ complex than explicitly using keys because it relies on behavior that isn't obvious.

> Exactly. And my code gets a bit more complex (I now have to use and pass on the index), and every item ends up with a useless key property that I’ll see in the debugger. That’s what I meant with data.

I would argue that a new API like `React.supressKeyWarning` introduces more complexity than adding a key, but feel free to [open an RFC](https://github.com/reactjs/rfcs) for the idea! It's probably better to call it something like `React.StaticList` so it's clear it's not just suppressing a warning, but removing the requirements for keys altogether.

**Comment by hamlim** [comment]
Interesting, should the docs be updated to not mention the fact that the elements in toArray get assigned keys since it should be considered an implementation detail and not necessary "stable" for this use case?

**Comment by jdfm** [comment]
I was going to post this on https://github.com/facebook/react/issues/2816, but I noticed this open issue, so, here it goes...

What if we use a structure like:

```javascript
import React from 'react'

const myData = [
  Something,
  Or,
  Whatever
]

const ListItems = items => Object.freeze(
  items.map(
    item => <li>{item}</li>
  )
)

const List = () => <ul><ListItems items={myData} /></ul>
```

In my head, `ListItems` can satisfy a number of these properties:
- it can change between builds of the application (codebase changes over time)
- it may use dynamic contents to be created the first time, but it's never mutated dynamically during runtime from that point on
- it can be arbitrarily large, so, you might not want to keep all of the contents inline with the component that will contain it, which may look like a dynamic array when transpiled, but is in fact static

By `Object.freeze`ing it you should be able to key off some JS properties to determine whether an array can in fact be used without the `key` prop on the elements inside of the array.

**Comment by gaearon** [comment]
Technically you can always do what JSX does — `createElement(type, props, ...children)`. We won't warn for missing keys on those children.

Of course it's error-prone if children are dynamic so we don't advertise this.

**Comment by flying-sheep** [comment]
So basically

```js
const StaticList = (...children) => React.createElement(React.Fragment, {}, ...children)
```

**Comment by PartMan7** [comment]
Another weird usecase:

I'm using React exclusively to render into static markup that I can then send to clients; for this I know that keys will never matter. Any way I can suppress this warning so I don't have these logs flooding my bot consoles whenever HTML is generated?
