### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Gunapvkn** [facebook/react#14371]
Hi All,

I am facing some issues regarding react + redux. since i am new to this i have created a component wich is using ReactFullPage. I have a login page there i am having a signup link under. 

**Home page which is having a sign in component :** 

class Home extends Component {
	render () {
		const { isSignInRequest, isSignUpRequest, isForgotPasswordRequest, onSignUpRequest, onForgotPasswordRequest, onSignInRequest} = this.props;
		return( 
			<div>
			<ReactFullpage {...fullpageOptions} 
				render = 
				{
					({ state, fullpageApi }) => {
				      return (
				        <div id='fullpage-wrapper'>
					          <div className='section section1'>
									{ isForgotPasswordRequest === true ? <ForgotPassword signUpRequest={onSignUpRequest}  signInRequest={onSignInRequest} /> : 
									( isSignUpRequest === true ? <SignUp signInRequest={onSignInRequest} forgotPasswordRequest = {onForgotPasswordRequest}/> : 
									<SignIn signUpRequest={onSignUpRequest} forgotPasswordRequest = {onForgotPasswordRequest}/> ) }
					          </div>
					          <div className='section'>
					          </div>
					          <div className='section'>
					          </div>
					          <div className='section'>
					          </div>
					          <div className='section'>
					          </div>
					    </div>
				      );
    				}
    			}
   			/>
   			</div>
   		);
	}
}

**I am having sign in component**

class SignIn extends Component {
  render() {
      return (
          <MDBContainer className='mdbContainer '>
            <MDBRow>
              <MDBCol md='5' className='loginContainer rounded z-depth-5'>
                <form>
                  <div className='grey-text'>
                    <MDBInput className='inputContainer'
                      label='Type your email'
                      icon='envelope'
                      group
                      type='email'
                      validate
                      error='wrong'
                      success='right'
                    />
                    <MDBInput className='passwordContainer'
                      label='Type your password'
                      icon='lock'
                      group
                      type='password'
                      validate
                    />
                  </div>
                  <div className='text-center '>
                    <MDBBtn className='submitButton' >Login</MDBBtn>
                    <MDBModalFooter>
                        <div className='font-weight-light'>
                          <p>Not a member? <span onClick={this.props.signUpRequest} style={{color:'#007bff', cursor:'pointer'}}>Sign Up</span></p>
                          <span style={{color:'#007bff', cursor:'pointer'}}> Forgot Password?</span>
                        </div>
                    </MDBModalFooter>
                  </div>
                </form>
              </MDBCol>
            </MDBRow>
          </MDBContainer>
        );
      }
}

when i click on signup i getting the above mentioned issue 

**DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.**

Kindly help me to resolve this issue.

**Comment by threepointone** [comment]
You should probably file an issue at the react-fullpage repository https://github.com/alvarotrigo/react-fullpage/issues

**Comment by nhunzaker** [comment]
I think that's the right call too. Closing this out. If it turns out, after confirming on `react-fullpage`, that there is a bug in React, feel free to refile or open this issue.
