### ISSUE TITLE
do we have support for react lower versions such as v0.13. How react maintaining LTS period for each release

### ISSUE THREAD

**Issue by Kaliyani** [facebook/react#14385]
Hi Team,

I am not finding proper documentation for supporting version of React. 

How react handles LTS cycle for their previous versions. 

Are we still supporting older versions like v15.0.0(released in Apr8 2016), v0.13.0(released in Apr19 2015)

**Comment by gaearon** [comment]
No, although in very rare circumstances we might release a patch version to a previous major. In general we only support one major at a time.

https://reactjs.org/docs/faq-versioning.html
