### ISSUE TITLE
Context example from https://reactjs.org/docs/context.html#when-to-use-context not working

### ISSUE THREAD

**Issue by mytee306** [facebook/react#14388]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Not working 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:** 
https://stackblitz.com/edit/react-context-docs-example?file=index.js

**What is the expected behavior?**
Context value gets passed down and button turns dark blue

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.5

**Comment by mytee306** [comment]
Behaves accordingly when used with context *consumer* but doesn't work with *this.context*

**Comment by hamlim** [comment]
The `static contextType` shorthand / logic was added within the React 16.6.0 release, so I would think is expected to not work in 16.5.0.

**Comment by mytee306** [comment]
> The `static contextType` shorthand / logic was added within the React 16.6.0 release, so I would think is expected to not work in 16.5.0.

Absolutely, thanks a lot. Upgrading worked like a charm. 

```
npm i react@latest react-dom@latest 
```

In regards to alternatives there's the option of using the context *Consumer* and perhaps creating a withContext HOC which can be seen [here](https://stackblitz.com/edit/react-with-context?file=context.js)

Secondly there's the option of falling back to legacy context as seen [here](https://stackblitz.com/edit/react-context-legacy?file=index.js)
The caveat with this approach is that legacy context will no longer be supported with the future arrival of react 17
