### ISSUE TITLE
Add JSDoc typedef or namespace for ReactElement

### ISSUE THREAD

**Issue by AllieFerr** [facebook/react#14386]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When I try to JSDoc a `ReactElement` type (e.g. `@type {ReactElement}`, `@returns {ReactElement}`) in my IDE (WebStorm), the type is seen as not defined.

**What is the expected behavior?**
I would be nice if a JSDoc type `ReactElement` was defined and linked to the ReactElement definition in the React code.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
version 16.5.2

**Proposed solution**
Either add `@namespace ReactElement` in the doc block above the `ReactElement` function
https://github.com/facebook/react/blob/6bf5e859860938b8cb7153ee928c01ad45656969/packages/react/src/ReactElement.js#L91-L111
...or create a `ReactElement` `@typedef` block, and then document the `@returns` of the function with `{ReactElement}`

**Comment by aweary** [comment]
It's unlikely that we'd do this for the same reason we don't maintain official TypeScript type definitions; it would be another burden on the React team to ensure that these are always maintained (once they exist it's expected that they're always right).

The existing JSDoc blocks are likely just legacy holdovers that haven't been removed as we've yet to add Flow annotations to `ReactElement`.
