### ISSUE TITLE
nested using ReactDOM.render 

### ISSUE THREAD

**Issue by xuzhanhh** [facebook/react#14395]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
```js
  componentWillReceiveProps() {
    const rootElement2 = document.getElementById("root2");
    let a = <Root2 ts={new Date().valueOf()} />;
    let b = ReactDOM.render(a, rootElement2, ret => {
     // 1
      console.log("callback ts", new Date().valueOf());
    });
    try {
     // 2
      console.log(b.state.ts);
    } catch (e) {
      console.log(e);
    }
  }
```
in react15, in the first(render?) turn, it call 1 then 2, b is a valid react component. later(update?) turn, it call 2 then 1, b is a valid react component.

in react16, in the first(render?) turn, it call 2 then 1, b is an null. later(update?) turn, it also call 2 then 1, b is a valid react component.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

react16 https://codesandbox.io/s/7k0nopwxnj
react15 https://codesandbox.io/s/9325408pyp

also see this issue https://github.com/facebook/react/issues/12315

**What is the expected behavior?**

it looks like ReactDOM.render will return the previous react component asynchronously but synchronously in react15's render turn?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 15.6.2 and 16.x.x

**Comment by aweary** [comment]
@xuzhanhh this is expected, `ReactDOM.render` is no longer synchronous in the middle of an update, which is when `componentWillReceiveProps` is called.


See https://github.com/facebook/react/issues/14290#issuecomment-440267537

>Yeah, that's a known issue that we won't be able to fix because ReactDOM.render is no longer synchronous if we’re already in the middle of an update (which is the case in setState callbacks). Longer term you can consider ReactDOM.render return value to be legacy (as said in the docs).
>
>You should be able to use refs instead though to get a reference, and ReactDOM.render offers a callback.
