### ISSUE TITLE
Trying to get redirect after refreshing to work

### ISSUE THREAD

**Issue by DjKniteX** [facebook/react#14394]
**Do you want to request a *feature* or report a *bug*?**
No

**What is the current behavior?**
Trying to get refresh to redirect. For example, localhost:3000/dashboard and when clicked on component goe sto localhost:3000/component, I want to be able to refresh at the current link and redirect back to localhost:3000/dashboard

**What is the expected behavior?**
when I click on a link from localhost:3000/Dashboard => localhost:3000/component, and when I hit F5 or refresh I want to go back to localhost:3000/Dashboard

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16/Not sure

**Comment by threepointone** [comment]
This isn’t related to react? And I don’t think browsers support this behaviour either.

**Comment by threepointone** [comment]
react-router is a separate project from react, you could file the issue in that repository. https://github.com/ReactTraining/react-router/issues That said, I'm fairly certain react-router doesn't support the behaviour you need either. You *could* technically hack around it by changing window.location manually, but it would be unusual and unexpected behaviour for a website/app. You should probably reconsider the design of your app's navigation. 

I'm closing this issue.
