### ISSUE TITLE
Build react(-dom) using wepack preset env?

### ISSUE THREAD

**Issue by sleagon** [facebook/react#14396]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
all js are compiled to es5.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Why not use wepack preset env to build react it, we can build xxx.react.es6.min.js xxx.react.es2017.min.js, xxx.chrome65.min.js or something like that? Or is there anyway we can clone the source code and build it by ourselves? After all, react + react-dom is pretty huge itself, sometimes, it is even bigger than the logical code.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.x

Feel free to close it if you guys think it is worthless.

**Comment by sleagon** [comment]
maybe we can provide some service like polyfill-service, we could build react for different browsers.

**Comment by gaearon** [comment]
Compiling to more modern language versions won't do anything for React. It doesn't use modern features like classes internally so you won't see any meaningful difference. (If anything, last time I checked a version that used `const` and `let` was *larger*.)

We do plan to cut down on some browser polyfills. You can track this effort in https://github.com/facebook/react/issues/13525.
