### ISSUE TITLE
Hooks does not work inside browser? (natural ES5, no babel)

### ISSUE THREAD

**Issue by vans163** [facebook/react#14403]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Hooks does not work inside browser.

**What is the expected behavior?**
There is no error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Google Chrome

react@16.7.0-alpha.2
react-dom@16.7.0-alpha.2

```
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello World! Site Title</title>

    <script crossorigin src="https://unpkg.com/react@16.7.0-alpha.2/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16.7.0-alpha.2/umd/react-dom.development.js"></script>
</head>

<body>
    <div id="app"></div>
</body>

<script>
function Clock() {
    const [count, setCount] = React.useState(0);

    return 
        React.createElement("div", {}, 
            React.createElement("p", {}, "You clicked me")
        )
    ;
}

ReactDOM.render(Clock(), document.getElementById("app"));
</script>

</html>
```

The following code fails with an error "Uncaught Error: Hooks can only be called inside the body of a function component.".

Do hooks not work naturally inside the browser and require webpack?

**Comment by vans163** [comment]
As usual. After posting find the problem I needed to use

React.createElement(Clock, {}, null), to render the Clock. And remove the linebreak after return due to JS syntax taking a lesson from python.

**Comment by Arissablue** [comment]
Why. I dont understand alot of it
 In Barly  e-learning

**Comment by Arissablue** [comment]
Im  learning  barly
