### ISSUE TITLE
SSR context issue: Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed in a future major release

### ISSUE THREAD

**Issue by antonybudianto** [facebook/react#14408]
**Do you want to request a *feature* or report a *bug*?**
Bug, probably related https://github.com/facebook/react/pull/13829/files#diff-0ec201d2f87127ead696e6f5681e6830R1645

**What is the current behavior?**
```
Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed in a future major release. Did you mean to render <Context.Provider> instead?
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://github.com/antonybudianto/react-context-issue
`master` -> working branch (React 16.4.2)
`repro-issue` -> branch with warning/issue (React 16.6.3)
- npm install
- npm start
- open localhost:3000, and you can see the warning on the terminal where you run npm start (not dev console)
I think it's SSR issue since no warning shown on client side

Here is the React context API usage:
https://github.com/antonybudianto/react-ua/blob/master/src/react-ua.js

Here is the library usage:
- client side Provider (https://github.com/antonybudianto/react-context-issue/blob/master/src/renderer/client.js#L22)
- server side Provider (https://github.com/antonybudianto/react-context-issue/blob/master/src/renderer/app.js#L43)
- Consumer (https://github.com/antonybudianto/react-context-issue/blob/master/src/routes/Home/HomeView.js#L59)

I'm sure I don't use `<MyContext>` as a Customer/Provider as you see in the source.

**What is the expected behavior?**
It should work without warning

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Warning on React 16.6.3
Working well (no warning) on React 16.4.2

**Comment by antonybudianto** [comment]
FYI, This is still happening in latest release (16.8.0) @aweary

**Comment by gaearon** [comment]
This is triggered by `loadable-components` which "walk the React tree" (not something we support or recommend to do) and attempt to access context Consumer's `Provider` property (which exists solely for the purpose of this warning). Printing the warning stack trace would tell you that:

```
   at walkTree (/Users/gaearon/p/react-context-issue/node_modules/loadable-components/dist/loadable-components.server.cjs.js:149:51)
    at /Users/gaearon/p/react-context-issue/node_modules/loadable-components/dist/loadable-components.server.cjs.js:159:13
    at forEachSingleChild (/Users/gaearon/p/react-context-issue/node_modules/react/cjs/react.development.js:1113:8)
    at traverseAllChildrenImpl (/Users/gaearon/p/react-context-issue/node_modules/react/cjs/react.development.js:1017:5)
    at traverseAllChildrenImpl (/Users/gaearon/p/react-context-issue/node_modules/react/cjs/react.development.js:1033:23)
    at traverseAllChildren (/Users/gaearon/p/react-context-issue/node_modules/react/cjs/react.development.js:1088:10)
```

Please file an issue in `loadable-component` so that they can be fixed to not attempt to read `.Consumer.Provider`.
