### ISSUE TITLE
Comments in NPM package have wrong version

### ISSUE THREAD

**Issue by Gaelan** [facebook/react#14410]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** The react@16.6.3 package has a comment at the top claiming to be React 16.6.1.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
```shell
cd /tmp
npm pack react@16.6.3
tar xf react-16.6.3.tgz
head -1 package/cjs/react.development.js
# output: /** @license React v16.6.1
```

**What is the expected behavior?**
The comment at the top of the build indicates the correct version.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6.2 and 16.6.3 both have the wrong comment. 16.6.1 and 16.6.0 are correct.

**Comment by Gaelan** [comment]
Also, https://github.com/facebook/react/blob/v16.6.3/packages/shared/ReactVersion.js claims to be `16.6.1`, but in the actual NPM package ReactVersion is set correctly.

**Comment by aweary** [comment]
@bvaughn should this be handled as part of the release flow you've been working on?

**Comment by bvaughn** [comment]
This was a transient issue, caused by a somewhat manual release that Andrew ran. (There's no bug in the release script.) This issue should only affect 16.6.2 and 16.6.3. Fortunately it shouldn't cause any observable behavior unless someone reads the comments. 😄
