### ISSUE TITLE
PureComponent use new Set() in state can not Trigger render()

### ISSUE THREAD

**Issue by Iwouldliketobeapig** [facebook/react#14416]
hi!
     When my component extends PureComponent and uses new Set() in state, the change of Set will not trigger the render() function. but Component is Ok!!!!!
PureComponent: https://codesandbox.io/s/n46m841w5m
Component: https://codesandbox.io/s/new

**Comment by TrySound** [comment]
@Iwouldliketobeapig Yes, that's the point of PureComponent. Props are shallow compared by references. Your set has the same reference. In any case just don't mutate data. It may be broke some cases even with `Component`.

```js
  changeSet = () => {
    this.setState(prev => {
      const set = new Set(prev.set);
      set.add(3);
      return { set };
    })
  };
```

**Comment by Iwouldliketobeapig** [comment]
thanks for you help, it is my fault

> @Iwouldliketobeapig Yes, that's the point of PureComponent. Props are shallow compared by references. Your set has the same reference. In any case just don't mutate data. It may broke some cases even with `Component`.
> 
> ```js
>   changeSet = () => {
>     this.setState(prev => {
>       const set = new Set(prev.set);
>       set.add(3);
>       return { set };
>     })
>   };
> ```
