### ISSUE TITLE
React project as a widget

### ISSUE THREAD

**Issue by arman94** [facebook/react#14417]
I need to my app act just like a widget, just like what [crisp](https://crisp.chat/en/?ta=XHKkRDPfp6&gclid=EAIaIQobChMIy4Tln7yB3wIVSwOGCh2mlgOLEAAYASAAEgK2GvD_BwE) chat widget does on other websites and be accessible through CDN link. I trying to build a CRM and I found nothing to make this happen.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
