### ISSUE TITLE
bug: react favicon extra request

### ISSUE THREAD

**Issue by whossein** [facebook/react#14412]
*bug*
when change url with react-router, request to get favicon from server (browser get cached image) but why extra request for favicons?this bug in [instagram.com](https://instagram.com)  and [7mive.com](https://7mive.com)

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests for React itself.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
