### ISSUE TITLE
How to fix react run issue

### ISSUE THREAD

**Issue by Harshk16** [facebook/react#14414]
After installing react-router-dom i am not able to run react application, Below are the errors, I am getting, didn't find any solution to fix that, I have this issue after installing react-router-dom

E:\PC\AboutMe\client>npm start

> client@0.1.0 start E:\PC\AboutMe\client
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**When i try to run **npm install** getting below issue**

npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Unexpected end of JSON input while parsing near '...h":"^1.2.12","yargs":'

Please help me out to fix it i am new to react

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
