### ISSUE TITLE
Fix grunt test:coverage

### ISSUE THREAD

**Issue by zpao** [facebook/react#1442]
Would be nice to fix this and make sure we're using lcov format so we can report back to [CodeClimate](https://codeclimate.com/github/facebook/react).

**Comment by Pouja** [comment]
I was looking into this issue.

@zpao Using coverify to output a lcov.info for Code Climate will only give the lines of code that are not executed. So, you will get very limited information. You will not get how many times a line is executed, number of branches hit, number of functions hit etc.

**Comment by zpao** [comment]
We got rid of this so closing
