### ISSUE TITLE
[future] Overriding content(s) of Component#render breaking behaviour

### ISSUE THREAD

**Issue by NeekSandhu** [facebook/react#14424]
**Do you want to request a *feature* or report a *bug*?**
Neither

This issue is of great value as far as `react-virtualized` is concerened.

Since `react-virtualized` causes Components to unmount once they are out of view. That also affects input elements. Meaning if there's a huge list of contacts and user is editing one entry through `HTMLInputElement` in the list itself. The moment, a user scrolls a bit up or down, that `input` gets unmounted and the entire input state (textValue, undo/redo history) is lost. Not very cool.

I'm trying to trying to put together an "HOC" that under the hood uses "manually" constructed `HTMLInputElement` that lives on until user actually cancels the editing. When the component is (re)mounted and `componentDidMount` fires, that "manual" input then replaces contents of `Component#render` to make things work!

**What is the current behavior?**
Everything works as intended! (but worried about the future)

1. I'm manually overwriting the `current` property on `React.RefObject` to achieve pseudo-ref-forwarding. (Making the `ref.current` point to an HTMLElement that's "manually" injected into DOM)

2. Replacing the HTMLElement output by Component's render method with an element created "manually", and reversing the operation in `componentWillUnmount` lifecycle. For safety, and to avoid confusing React, `shouldComponentUpdate` __always__ returns false.

Both of the operations above work nominally as of React `16.*`. **What is the probability that future versions of React will prevent either of those things from happening?**

Here's how it works: https://codesandbox.io/s/50ryqojnnn

Apologies if this question should belong elsewhere (I really wanted to hear from core team)

**Comment by NeekSandhu** [comment]
Also for clarification, this is different from grabbing a ref to what React rendered then _adding on_ to it (like integrating CodeMirror with React). Instead, this technique does a literal overwrite of `Component#render`'s output to not have any "unnecessary" wrappers. (but it does undo the patch in `componentWillUnmount` to make sure React doesn't get confused).

**Comment by heyimalex** [comment]
I think that tracking input element state should be handled by whatever renders the list? If you don't want your state to be ephemeral don't store it in ephemeral components. But I guess you lose native redo/undo and tabbing.

If you want I think you could do this in `react-virtualized` by tracking which inputs are being edited and then providing a custom `cellRangeRenderer` that continues to render those items when they're out of range. At worst, [`react-window`](https://react-window.now.sh/#/examples/list/fixed-size) is pretty small so you could just fork it to do this.

**Comment by NeekSandhu** [comment]
> ...But I guess you lose native redo/undo ...

That right there.

Thank for introducing me to `cellRangeRenderer` and `react-window`, especially the latter project. I'm happy to know that there's that workaround should my current method stops working in the future. Until then I'll stick with current method (hack?).
