### ISSUE TITLE
Are there any tests for React Hooks?

### ISSUE THREAD

**Issue by dwjohnston** [facebook/react#14439]
I'm looking at how people have solved this issue facebook/jest#936  How to mock specific module function? -  and I see React Hooks quite clearly shows code that reflects this issue: 
```
function resolveDispatcher() {
// snip
}

export function useReducer<S, A>(
  reducer: (S, A) => S,
  initialState: S,
  initialAction: A | void | null,
) {
  const dispatcher = resolveDispatcher();
  return dispatcher.useReducer(reducer, initialState, initialAction);
}
```

I'm curious to see any code testing this `useReducer` function.

**Comment by jfo84** [comment]
You could search the repository for `useReducer`. There's several cases

**Comment by dwjohnston** [comment]
Alright cool, I ran: 

```
find packages -path '*/__tests__/*' -type f -exec grep -l "useReducer" {} \;
```

to get: 

```
packages/react-debug-tools/src/__tests__/ReactHooksInspection-test.internal.js
packages/react-debug-tools/src/__tests__/ReactHooksInspectionIntegration-test.internal.js
packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.internal.js
packages/react-dom/src/__tests__/ReactDOMServerIntegrationHooks-test.internal.js
```

**Comment by gaearon** [comment]
I wouldn't recommend mocking the dispatcher for testing Hooks. Instead I'd recommend putting a Hook into an actual one-line component in your test, and using React to render it. Then you know you're actually testing how your Hook will work, and won't get tripped by implementing wrong semantics.
