### ISSUE TITLE
linting with react hooks does not error when putting useState in a component

### ISSUE THREAD

**Issue by pkellner** [facebook/react#14436]
I would have expected that calling a hook inside a react component would cause a linting error. From the docs it says "Only Call Hooks from React Functions"

```import React, {useState} from 'react';
class axioshooks extends Component {
    render() {
        const [data, setData] = useState([]);
        if (1 == 2) {
            const [data1, setData1] = useState([]);
        }
        return (
            <div>{data}</div>
        );
    }
}
export default axioshooks;
```

**Comment by gaearon** [comment]
We've seen too many false positives so we decided not to lint inside classes. This will immediately fail with a clear runtime error anyway so it's probably not worth it.

**Comment by pkellner** [comment]
Anyone coming back here, appears the React team decided this was a worthy case to flag as an error.

ESLint: React Hook &quot;useState&quot; cannot be called in a class component. React Hooks must be called in a React function component or a custom React Hook function. (react-hooks/rules-of-hooks)
