### ISSUE TITLE
css-loader not working after configuration with react eject 

### ISSUE THREAD

**Issue by 6zun9** [facebook/react#14431]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by 6zun9** [comment]
Failed to compile.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[2].oneOf[6].use should be one of these:
   non-empty string | function | object { loader?, options?, ident?, query? } | function | [non-empty string | function | object { loader?, options?, ident?, query? }]
   -> Modifiers applied to the module when rule is matched
   Details:
    * configuration.module.rules[2].oneOf[3].use should be a string.
    * configuration.module.rules[2].oneOf[3].use should be an instance of function
    * configuration.module.rules[2].oneOf[3].use should be an object.
    * configuration.module.rules[2].oneOf[3].use should be an instance of function
    * configuration.module.rules[2].oneOf[3].use[1] should be a string.
    * configuration.module.rules[2].oneOf[3].use[1] should be an instance of function
    * configuration.module.rules[2].oneOf[3].use[1] has an unknown property 'modules'. These properties are valid:
      object { loader?, options?, ident?, query? }
    * configuration.module.rules[2].oneOf[3].use[1] has an unknown property 'localIdentName'. These properties are valid:
      object { loader?, options?, ident?, query? }
    * configuration.module.rules[2].oneOf[4].use should be a string.
    * configuration.module.rules[2].oneOf[4].use should be an instance of function
    * configuration.module.rules[2].oneOf[4].use should be an object.
    * configuration.module.rules[2].oneOf[4].use should be an instance of function
    * configuration.module.rules[2].oneOf[4].use[1] should be a string.
    * configuration.module.rules[2].oneOf[4].use[1] should be an instance of function
    * configuration.module.rules[2].oneOf[4].use[1] has an unknown property 'modules'. These properties are valid:
      object { loader?, options?, ident?, query? }
    * configuration.module.rules[2].oneOf[4].use[1] has an unknown property 'localIdentName'. These properties are valid:
      object { loader?, options?, ident?, query? }
    * configuration.module.rules[2].oneOf[5].use should be a string.
    * configuration.module.rules[2].oneOf[5].use should be an instance of function
    * configuration.module.rules[2].oneOf[5].use should be an object.
    * configuration.module.rules[2].oneOf[5].use should be an instance of function
    * configuration.module.rules[2].oneOf[5].use[1] should be a string.
    * configuration.module.rules[2].oneOf[5].use[1] should be an instance of function
    * configuration.module.rules[2].oneOf[5].use[1] has an unknown property 'modules'. These properties are valid:
      object { loader?, options?, ident?, query? }
    * configuration.module.rules[2].oneOf[5].use[1] has an unknown property 'localIdentName'. These properties are valid:
      object { loader?, options?, ident?, query? }
    * configuration.module.rules[2].oneOf[6].use should be a string.
    * configuration.module.rules[2].oneOf[6].use should be an instance of function
    * configuration.module.rules[2].oneOf[6].use should be an object.
    * configuration.module.rules[2].oneOf[6].use should be an instance of function
    * configuration.module.rules[2].oneOf[6].use[1] should be a string.
    * configuration.module.rules[2].oneOf[6].use[1] should be an instance of function
    * configuration.module.rules[2].oneOf[6].use[1] has an unknown property 'modules'. These properties are valid:
      object { loader?, options?, ident?, query? }
    * configuration.module.rules[2].oneOf[6].use[1] has an unknown property 'localIdentName'. These properties are valid:
      object { loader?, options?, ident?, query? }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! burger-app@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burger-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-12-13T09_10_03_210Z-debug.log

**Comment by zep1994** [comment]
Try making options a new object and place the modules and localIdentName inside of that. The documentation for webpack has more information on it https://github.com/webpack-contrib/css-loader . Here is what I mean:
 `{
        loader: require.resolve('css-loader'),
        options: {
          modules: true,
          localIdentName: '[path][name]__[local]--[hash:base64:5]',
        },
      },`

Notice how options was given its own curly brackets and the default cssoptions was removed. If i had to guess, I would say that cssoptions is given as placeholder and all you need to do is add curly brackets and your good to go.

**Comment by markerikson** [comment]
This sounds like a concern with https://github.com/facebook/create-react-app , not React itself.  In addition, by "ejecting", you are taking ownership of the build configs.
