### ISSUE TITLE
my app works only if debug js remotely is enabled other wise it shows following error 

### ISSUE THREAD

**Issue by ashoKarki** [facebook/react#14432]
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
throwOnInvalidObjectType
    ReactNativeRenderer-dev.js:8261:6
reconcileChildFibers
    ReactNativeRenderer-dev.js:9292:31
reconcileChildrenAtExpirationTime
    ReactNativeRenderer-dev.js:9736:6
reconcileChildren
    ReactNativeRenderer-dev.js:9704:4
updateHostRoot
    ReactNativeRenderer-dev.js:10060:24
beginWork
    ReactNativeRenderer-dev.js:10732:28
performUnitOfWork
    ReactNativeRenderer-dev.js:13126:21
workLoop
    ReactNativeRenderer-dev.js:13165:41
renderRoot
    ReactNativeRenderer-dev.js:13218:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:13941:17
performWork
    ReactNativeRenderer-dev.js:13854:24
performSyncWork
    ReactNativeRenderer-dev.js:13814:14
requestWork
    ReactNativeRenderer-dev.js:13700:4
scheduleWork
    ReactNativeRenderer-dev.js:13537:22
scheduleRootUpdate
    ReactNativeRenderer-dev.js:14194:15
updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:14227:28
updateContainer
    ReactNativeRenderer-dev.js:14259:4
render
    ReactNativeRenderer-dev.js:14925:20
renderApplication
    renderApplication.js:54:34
run
    AppRegistry.js:101:10
runApplication
    AppRegistry.js:195:26
__callFunction
    MessageQueue.js:344:47
<unknown>
    MessageQueue.js:107:26
__guard
    MessageQueue.js:291:8
callFunctionReturnFlushedQueue
    MessageQueue.js:106:17

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
