### ISSUE TITLE
avoid escaping url attribute

### ISSUE THREAD

**Issue by pgherveou** [facebook/react#1444]
Hi there
I was just wondering if there is a way to avoid url attribute escaping in React?

``` js
React.renderComponentToStaticMarkup (<a href="http://google.com" />);
// currently produce <a href="http:&#x2f;&#x2f;google.com"></a>
```

**Comment by suprMax** [comment]
Probably related: having issues setting backgroundImage style prop via react, if URL contains single quotes:

`https://s3-eu-central-1.amazonaws.com/nebenandevelopment/system/generic_images/data/000/001/404/b50265fe6687a0832204133dda0ca64500500660/jpg/250px-Cyth-V'sug.jpg?1472034934`

breaks when
