### ISSUE TITLE
React context consumer callback firing order is in reverse while rerendering, opposite to waterfall data flow 

### ISSUE THREAD

**Issue by sambathl** [facebook/react#14441]
**Do you want to request a *feature* or report a *bug*?**
Expected nested same context consumer callback need to fire from outer layer to inner

**What is the current behavior?**
Observed nested same context consumer callback firing from inner most layer toward outer layer

### **Why is such this way, assuming prop is passed from outer most layer, then React follow waterfall data flow means outer layer to all way to inner most if I pass props through all nested component. It is opposite of consumer callback firing order** 

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.4.2

**Comment by aweary** [comment]
@sambathl can you please provide an example of the behavior you're describing?
