### ISSUE TITLE
[Hooks] Proposal: expose info about current component for custom hooks

### ISSUE THREAD

**Issue by steadicat** [facebook/react#14446]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The core built-in hooks – `useRef`, `useMemo`, etc. – rely on internal React state which is not exposed, namely the current rendering component. This means that these hooks cannot be implemented in user-land. Similar hooks cannot be implemented either.

I'm proposing adding a built-in hook which would provide information about the current rendering component. This would enable more advanced hooks to be implementable in user-land.

I have a use case which is a perfect example. I need a hook similar to `useMemo`, but where the computed value is shared across all components of the same type. I’m calling it `useSharedMemo`.

The ideal API would look something like this:

```typescript
const Component = ({cacheKey}) => {
  const value1 = useSharedMemo(() => /* expensive computation 1 */, [cacheKey]);
  const value2 = useSharedMemo(() => /* expensive computation 2 */, [cacheKey]);
  return <>{value1} {value2}</>;
};
```

In the code above, every instance of `Component` would get the same values for `value1` and `value2`, provided `cacheKey` is the same. When `cacheKey` changes, the two values would recompute once and the new values would be returned to all instances as they re-render. (The actual use case in my app is styles that need to update only when the theme changes.)

I have a [hacky implementation](https://codesandbox.io/s/jplyz2pkr9) of this hook that works, but it requires changing the API to the following:

```typescript
const useSharedMemo = createUseSharedMemo();

const Component = ({cacheKey}) => {
  const ref = React.useRef();
  const value1 = useSharedMemo(ref, () => /* expensive computation 1 */, [cacheKey]);
  const value2 = useSharedMemo(ref, () => /* expensive computation 2 */, [cacheKey]);
  return <>{value1} {value2}</>;
};
```

For this to work, the [implementation](https://codesandbox.io/s/jplyz2pkr9) has to keep a counter of calls that resets every time a component’s render call starts or ends. This would be trivial if there were a way to know which component is currently rendering. Since there is no way, the implementation has to make up for it by requiring a `ref` be passed in. Since it has no information about the type of the current component, it also requires that a `useSharedMemo` “instance” be created in the component definition’s enclosing scope.

Worse, the implementation uses `useLayoutEffect` to detect when the render is done, which might break with concurrent mode or with future React changes.

**What is the expected behavior?**

If React provided information about the current rendering component, the implementation of `useSharedMemo` would be much easier and less brittle.

A possible solution is a hook like the following:

```typescript
const [currentType, currentRef] = React.useCurrentComponent();
```

With this information, we can implement the ideal API above and we do not have to rely on `useLayoutEffect`:

```typescript
let values = new WeakMap();
let cacheKeys = new WeakMap();
let lastRef = null;
let callIndex = 0;

function useSharedMemo(fn, keys) {
  const [currentType, currentRef] = React.useCurrentComponent();
  if (currentRef !== lastRef) {
    callIndex = 0;
  }
  const index = callIndex;
  callIndex++;
  const typeValues = values.get(currentType) || [];
  const typeCacheKeys = cacheKeys.get(currentType) || [];
  if (!typeValues[index] || !compareKeys(keys, typeCacheKeys[index])) {
    typeValues[index] = fn();
    typeCacheKeys[index] = keys;
    values.set(currentType, typeValues);
    cacheKeys.set(currentType, typeCacheKeys);
  }
  return typeValues[index];
}
```

(Note that I’m treating `currentType` and `currentRef` as opaque values, so for my purposes it doesn’t matter if they are the actual type and an actual ref to the component instance. I imagine having them be accurate would be a more powerful API, but the implementation might require them to be opaque values.)

P.S. - A common use case that would benefit from `useSharedMemo` is `useCallback`. 99% of the time callbacks are identical across components of the same type. It’s wasteful not to share the cache.

**Demo**
https://codesandbox.io/s/jplyz2pkr9

**Comment by muqg** [comment]
I think that this future proposal here https://github.com/reactjs/rfcs/pull/89 will address your issue, planned to be part of the react-cache as far as I know.
