### ISSUE TITLE
Child component not get updating when render from parent's state

### ISSUE THREAD

**Issue by sun1991** [facebook/react#14445]
**Do you want to request a *feature* or report a *bug*?**
This is possibly a bug.

**What is the current behavior?**
See attachments:

index.js_refresh embedded child components into parent's render logic, child props receives update from parent and refreshs automatically.

index.js_notrefresh put child components into parent's state and render it, child props don't get updates from parent state change.

**What is the expected behavior?**
What I'm doing here is I'd like to put child component into parent state, and choose which child to display based on parent state change. I don't want to stuff all the child components into parent's render logic like index.js_refresh did.
 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v16.6.3

[att.zip](https://github.com/facebook/react/files/2682416/att.zip)

**Comment by yohaizv** [comment]
It's not a bug,
the function **updateProgress** just update "progress" and not update "content" 
`updateProgress() {
    this.setState({ progress: new Date() });
  }`
