### ISSUE TITLE
Possible script injection.

### ISSUE THREAD

**Issue by RobbySingh** [facebook/react#14440]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Script injection vulnerability

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Withheld for security

**What is the expected behavior?**
No script execution

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome with React 16

While working with a colleague, we discovered a script injection vulnerability with React. For security, I won't post it here but private message it to a core contributor who comments on this post.

**Comment by aweary** [comment]
@RobbySingh can you email me the details? brandondail@fb.com

**Comment by RobbySingh** [comment]
Hi @aweary. sure, I have sent you an email now. Thanks for verifying this. I might be wrong about but better you check

**Comment by RobbySingh** [comment]
@aweary confirmed with me through email that this is not an issue with React. Closing ticket
