### ISSUE TITLE
Allow the "dusk" tag in DOM elements

### ISSUE THREAD

**Issue by mikepmtl** [facebook/react#14449]
**Do you want to request a *feature* or report a *bug*?**

Feature Request

**What is the current behavior?**

The "dusk" tag is stripped out of DOM elements.
( as expected: https://reactjs.org/docs/dom-elements.html#supported-attributes)

Dusk is a Browser testing environment for the popular php framework Laravel.
https://laravel.com/docs/5.7/dusk

The "dusk" tag allows you to easily select dom elements. 
https://laravel.com/docs/5.7/dusk#dusk-selectors

It is convenient as you do not need to worry about DOM elements having their classes or IDs changed in the future, or you can use more descriptive names in projects that are already using less descriptive IDs.

**Comment by marvinhagemeister** [comment]
As far as I can see a `dusk` attribute is not present in the HTML spec. I'm curious as to why they went that way instead of a `data-dusk` attribute. The `data-*` attributes were specifically added for adding custom non-standard attributes.

**Comment by manspaniel** [comment]
Actually, this should work fine as long as you're using React 16+. Any attributes which React doesn't recognise do make their way through to the DOM.

https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

**Comment by nmain** [comment]
This works in React normally.
https://jsfiddle.net/pft3wxym/
If it's not working for you, please attach a reproducing case.

**Comment by aweary** [comment]
As mentioned, this works as expected in React 16+.
