### ISSUE TITLE
Allow stateless components to be classes

### ISSUE THREAD

**Issue by daleyjem** [facebook/react#14453]
React throws: `TypeError: Cannot call a class as a function` when trying to define a stateless component as a `class`.

I understand the way to do this with:

```js
const MyStatelessComponent = () => (
  <div>MyStatelessComponent</div>
)

MyStatelessComponent.propTypes = {
  size: PropTypes.oneOf(['s', 'm', 'l'])
}

export { MyStatelessComponent }
```

But the problem with doing it that way is that you can't define a static method or property to that component (i.e. propTypes) and have that component be tree-shaken by webpack. I don't know the details behind why that's the case, but it is.

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently, stateless components can only be defined as functions, but not classes

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

A stateless component should be able to be defined as a class with a constructor, so that a static getter can be set. Webpack knows how to tree shake static properties or methods defined that way.

For example:

```js
class MyStatelessComponent {
  constructor () {
    return (
      <div>MyStatelessComponent</div>
    )
  }

  static get propTypes () {
    return {
      size: PropTypes.oneOf(['s', 'm', 'l'])
    }
  }
}

export { MyStatelessComponent }
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Not an issue, but a proposal. It does not work in any previous versions of React, to my knowledge.

**Comment by MatteBailey** [comment]
Unless I'm misunderstanding, this already works fine. You just forgot to extend `React.Component`. Try `class MyStatelessComponent extends React.Component {`.

**Comment by daleyjem** [comment]
@MatteBailey I believe a `React.Component` is state**ful**,  not state**less**. My first code snippet shows how a stateless component is usually accomplished with an arrow function. Your example would actually work for tree shaking, but comes with overhead that I don't wish to include.

[This post](https://itnext.io/react-component-class-vs-stateless-component-e3797c7d23ab) explains in more detail.

**Comment by MatteBailey** [comment]
I think people usually consider a component stateful if it makes use of `this.state`. Since you certainly don't have to make use of `this.state` in a Class component, it seems like the behavior you are looking for already exists. To make sure we're on the same page, your component would look like this ([with class properties enabled](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties)):
```javascript
export default class MyStatelessComponent extends React.Component {
    static propTypes = {
            size: PropTypes.oneOf(['s', 'm', 'l'])
    };

    render() {
        return (
            <div>MyStatelessComponent</div>
        );
    }
}
```

It sounds like your actual concern is the overhead of extending `React.Component`. I really doubt that makes a whole lot of a difference in most cases, but it is something to consider I guess.

**Comment by aweary** [comment]
@MatteBailey is correct, you can define stateless class components by simply using a class component and not adding any state to it. The overhead of extending `React.Component` is minimal and will never have a noticeable impact on performance.

> But the problem with doing it that way is that you can't define a static method or property to that component (i.e. propTypes) and have that component be tree-shaken by webpack. I don't know the details behind why that's the case, but it is.

I don't think that's true, and if it is it's probably a bug that should be reported. There's no practical difference between using `static` and setting an own property on a function (which is [exactly what `static` gets compiled to by Babel](https://babeljs.io/repl#?babili=false&browsers=chrome%20%3E%2060&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oQC5iwS2GgCMwAnaAXmgEYBuVAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Creact%2Cstage-2%2Cstage-3%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2))
