### ISSUE TITLE
General-purpose promise component to use with Suspense 

### ISSUE THREAD

**Issue by bisubus** [facebook/react#14459]
**Do you want to request a *feature* or report a *bug*?**

A feature.

**What is the current behavior?**

React.Suspense currently supports only React.lazy components which are tailored to be used with dynamic `import` of modules with predefined names and default exports.

If a promise of a component is supposed to be returned, a component should be wrapped with redundant `{ default: ... }` object:

```js
const LazyFoo = React.lazy(async () => {
  const { Foo } = await import('third-party-package');
  return { default: Foo };
});
```

`lazy` function has no parameters, it's not possible to make lazy component parametrized with props:

```js
const LazyWetFoo = React.lazy(noPropsHere => import('third-party-package/foo'));
const LazyWetBar = React.lazy(noPropsHere => import('third-party-package/bar'));
```

When `lazy` is used with arbitrary promise of a component, it's not possible to provide dynamic behaviour to a promise via props:

```js
const LazyBaz42 = React.lazy(async (noPropsHere) => {
  const answer = 42; // the component is hard-coded to answer with 42
  const result = await fetchData(`/answer?${prop}`);
  return { default: props => <Answer ...props>{result}</Answer> };
}
```

**What is the expected behavior?**

There is general-purpose promise component type that receives props that were passed to it and returns a promise of React element:

```js
const LazyBaz = React.resolver(async ({ answer, ...props) => {
  const result = await fetchData(`/answer?${answer}`);
  return <Answer ...props>{result}</Answer>;
}
```

React.lazy is a special case of React.resolver, its signature is optionally changed to receive same props as those that would be passed to lazy-loaded component:

```js
const LazyFoobar = React.lazy(({ fooOrBar }) => import(`third-party-package/${fooOrBar}`));
```

React.Suspense supports both of them.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All versions (16.7.0@alpha.2 and lower)

**Comment by muqg** [comment]
I think that you would be interested to hear about the upcoming [Suspense for data fetching](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-mid-2019-the-one-with-suspense-for-data-fetching).
