### ISSUE TITLE
Let ReactTestUtils.Simulate.click work on non-dom components

### ISSUE THREAD

**Issue by zpao** [facebook/react#1445]
[@sebmarkbage suggested we do this](https://github.com/facebook/react/pull/877#issuecomment-40534852) to avoid the silly tagName requirement. Anything that can resolve to a node (getDOMNode) should work.

**Comment by jareware** [comment]
I'm interested in testing a React component without rendering it into a DOM; `React.renderToString()` works fine for making assertions, but not for triggering events.

Is it possible to somehow render a tree of React components without ever mounting it into a DOM, and performing assertions against it, or triggering synthetic events? I realize things like `getDOMNode()` could never work, but given I wasn't using it anywhere.

Also please tell me if this is just a silly idea. :)

**Comment by zpao** [comment]
Exactly that is coming, called shallow testing. It's not 100% supported but you'll be able to start using it in 0.13 (you can try 0.13 beta today). See #2963 for some details (documentation and links to impl).

**Comment by jareware** [comment]
That looks very interesting indeed! Commenting on that PR.

**Comment by robertknight** [comment]
React v0.13's shallow rendering allows you to render one level deep and test output but attempting to dispatch events in tests results in an error due to the DOM not being available:

````js
import React from 'react/addons';

class Button extends React.Component {
	constructor(props) {
		super(props);
		this.state = { pressed: false };
	}

	render() {
		return <div className={this.state.pressed ? 'button-pressed' : 'button'}
		  onMouseDown={this.setState({pressed: true})}
		  onMouseUp={this.setState({pressed: false})} />
	}
}

let shallowRenderer = React.addons.TestUtils.createRenderer();
let component = shallowRenderer.render(<Button/>);
let button = shallowRenderer.getRenderOutput();

// fails due to missing 'window' global
React.addons.TestUtils.Simulate.mouseDown(button);
````

**Comment by robertknight** [comment]
Is React.addons.TestUtils.Simulate.* already implemented for React Native? That would presumably have the same issues.

**Comment by vvo** [comment]
Hey Hi, how can we help in making this? Can you point me in some direction so I can implement this or is it a BIG change?

**Comment by gaearon** [comment]
Closing as stale. If there is interest in this, please file a new issue.

**Comment by monokrome** [comment]
How is this stale? Something doesn't work. That's called a bug.
