### ISSUE TITLE
getDerivedStateFromProps cannot be used to react to changes in props

### ISSUE THREAD

**Issue by sheerun** [facebook/react#14458]
## Problem

The [blogpost](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) and [docs](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) on this method explicitly say:

> getDerivedStateFromProps exists for only one purpose. It enables a component to update its internal state as the result of changes in props.

> This method exists for rare use cases where the state depends on changes in props over time. 

Also the RFC states:

> Note that React may call this method even if the props have not changed.

**But how one can react to *changes* in props when no previous props or state are available and this method is invoked both when props change and not? (and also [after setState](https://github.com/facebook/react/issues/13480)).**

## Use case

My component is a filter button that upon clicking show popover dialog (something like [this](https://www.w3schools.com/bootstrap/bootstrap_popover.asp)) with ability to change inside popover, e.g. price of product.

The [blogpost](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) recommends following solutions:

> Recommendation: Fully controlled component

I don't want fully controlled component as I want to encapsulate behavior of opening and closing popover within filter button itself. I don't want to put this logic anywhere else than the component.

> Recomendation: To reset all internal state, use the key attribute.

I don't want to reset all internal state as popover should remain opened (i.e. its `state.opened` property should not be changed). It should only react to change in props, what are maximum and minimum values possible to select with price slider or "defaultPrice" value that is passed from model as prop after `onChange` prop is triggered by button.

> Recommendation: Fully uncontrolled component with a key

Again, I cannot use `key` because I want `state.opened` to be preserved and reset to "default" or "managed" values only other properties like selected price or currency if they change as props.

> Alternative 1: Reset uncontrolled component with an ID prop

In my case the the "id" is the price that should be shown as default, and indeed I tried following:

```js
static getDerivedStateFromProps (props, state) {
  if (props.distance !== state.distance) {
    return {
      distance: props.distance
    }
  }

  return null
}
```

Unfortunately this won't work because I want to use `setState({ distance: xxx })` to update current value of slider in real time within component itself (component triggers onChange only when slider is dropped). It turns out that `setState({ distance: xxx })` is overridden by logic `getDerivedStateFromProps` that sets state.distance to props.distance because `props.distance !== state.distance`.

> Alternative 2: Reset uncontrolled component with an instance method

Again, I don't want to reset anything, and I want to encapsulate popover logic and not rely on something like `ref` that has lots and lots of quirks and requires me to write custom code when to call this instance method and when just to pass property like I do everywhere for default values.

Memoization is not needed for this this use case so I'll skip it.

## Solutions?

Sincerely I don't know, but one thing for sure, the documentation should be changed.

getDerivedStateFromProps **cannot** be used to react to changes in props, it can be **only** be used to derive new state from current props and current state which is indeed very rare use case.

Also React deprecated perfectly good API that actually can react to changes in props, because it receives both props and prevProps, so maybe it's time to re-introduce this API and recommend it for this use case

**Comment by jquense** [comment]
It does sound like you want a controllable component tho maybe, you can use something like [`uncontrollable`](https://github.com/jquense/uncontrollable#uncontrollable) to handle that for you via an HOC, or do it yourself via a wrapper. There isn't a need to use `gDSFP` necessarily. You can create controlled component and then wrap them to handle to allow uncontrolled behavior

> getDerivedStateFromProps cannot be used to react to changes in props,

If you really do want to use state and props, the pattern is to save the last prop you need to compare in state and compare against that in each `gDSFP`.

> Also React deprecated perfectly good API 

You may have missed why this change was made. it's not a perfectly good API, as it creates unfixable bugs in react's Concurrent mode. There is a lot of discussion and explanation around this in the RFC and blogpost.

**Comment by sheerun** [comment]
> It does sound like you want a controllable component tho maybe, you can use something like uncontrollable to handle that for you via an HOC, or do it yourself via a wrapper

No I don't want controllable component, I explicitly stated that. I also don't need something like uncontrollable, I want to embed popover logic within component itself, besides I also use mobx.

> If you really do want to use state and props, the pattern is to save the last prop you need to compare in state and compare against that in each gDSFP.

You're recommending what the blogpost explicitly calls a strong antipattern and why it was created in first place.

Please change the documentation that this method cannot be used to react to changes in props.

**Comment by jquense** [comment]
> You're recommending what the blogpost explicitly calls a strong antipattern and why it was created in first place.

that is only because you are insisting that you need to. The blogpost is not calling out specific usage of gDSFP. It's saying that the using the API **at all** may be a code smell. A large majority of cWRP and gDSFP usage is better expressed using a different pattern because the generally used pattern often contain bugs. This is even more obvious in Concurrent mode where those bugs will manifest a lot more often.

There are still cases though were you need to compare props and adjust state based on new props, perhaps your use-case is one of them. In which case go ahead and use this pattern, the API exists specifically for that. The guidance here is that you should be very sure that this is the best way to accomplish what you want, which you seem very certain about, having rejected all the other options. So go for it. I don't know why the documentation should be changed though. the API absolutely allows reacting to changes in props.
