### ISSUE TITLE
Wrong visualization order in User Timing when profiling in Chrome

### ISSUE THREAD

**Issue by mareolan** [facebook/react#14452]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In the screenshot below the "DropTarget(Tile) [update]" should have been visualized above the "Tile [mount]". Similarly, the item with "stop icon" to the right should have been in the first row.
![image](https://user-images.githubusercontent.com/4648469/50094133-b91f1680-0212-11e9-8cf7-17d131a09d4f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Sorry, I don't have public demo. When the bug happens it doesn't seem to be specific to a specific component / lifecycle event. I'm not sure whether it's React's problem or Chrome's.

**What is the expected behavior?**
Different order.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.6.3 (but I have seen this in 16.4.0 too)
Chrome 70.0.3538.110, Windows 10 Home

**Comment by gaearon** [comment]
Hard to say more without a repro case.

**Comment by gaearon** [comment]
We removed User Timings.
