### ISSUE TITLE
[bug?] inner form cause outter form submit

### ISSUE THREAD

**Issue by xialvjun** [facebook/react#14456]
example: https://codesandbox.io/s/8plqn8mwl

I don't know if it's a bug or a feature. If code like this:

```jsx
function Portal({ children }) {
  return ReactDOM.createPortal(children, document.body);
}

<form id="outter_form" onSubmit={e => xxx}>
  <Portal>
    <form id="inner_form" onSubmit={e => xxx}>
      <button type="submit">submit</button>
    </form>
  </Portal>
</form>

// then the inner_from onSubmit will cause the outter form submit...
// I have to add `if (e.target !== e.currentTarget) return;` in outter form's onSubmit to prevent it.
```

If it's a feature, feel free to close this issue. But I still hope you document it in reactjs.org

**Comment by muqg** [comment]
The Portals documentation does say that events propagate to parents as if its children have not been popped out of the main html tree. I think that this is the source of your problem and confusion. You can avoid this by calling `e.stopPropagation therefore`.

**Comment by muqg** [comment]
React's Portals documentation does atate that events propagate to parents as if the children are still part of the main component tree, even though they pop out of the html one. You can avoid this by calling `e.stopPropagation` therefore.

**Comment by xialvjun** [comment]
Oh, yeah, I remembered `e.preventDefault()`, but forgot `e.stopProgation()`
