### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RCTImageView" was not found in the UIManager.

### ISSUE THREAD

**Issue by MIyulong** [facebook/react#14464]
there is my logs, and the current react-native version is 0.57.8, in the pod file, also write with 'RCTImage', as for those,  how can i resolve this problem
 
**Do you want to request a *feature* or report a *bug*?**
![image](https://user-images.githubusercontent.com/8175565/50218069-a436b480-03c5-11e9-87f1-05065d498067.png)
![image](https://user-images.githubusercontent.com/8175565/50218092-b57fc100-03c5-11e9-8f76-a1f6dbe1f326.png)
![image](https://user-images.githubusercontent.com/8175565/50218116-bfa1bf80-03c5-11e9-96d8-dbb42c3d850c.png)

**Comment by aweary** [comment]
This repo is for React Core. You've [already opened an issue in the React Native repo](https://github.com/facebook/react-native/issues/22725), which is the correct place for this.

**Comment by expero1995** [comment]
Have you solved?

**Comment by expero1995** [comment]
Maybe you can choose debug mode? I have same problem , I find that I choose release mode, but I choose debug mode ,the warming is disappeared.

**Comment by MIyulong** [comment]
yes, the problem has been solved, as you said, it's running well on debug model @expero1995

**Comment by absss** [comment]
我也遇到了同样的问题，我的解决方案是：删除pod文件夹和pod.lock文件，之后再 pod install ，然后全局搜索 RCTImageView， 如果能找到该类的相关信息，则说明问题已经解决。我猜测问题的原因是pod file里面的RCTImage是位于subspecs里面，pod install命令会绕过你已经下载好的库文件，所以重新删除再下载就能把RCTImageView相关文件下载下来，当然，你不嫌麻烦，也可以使用 pod update命令，应该也能解决

**Comment by expero1995** [comment]
我已经解决该问题了，原因就是pod中关于react的库缺少导致的，可以根据reactnative自动帮你导入的react库来进行对应在podfile导入相应的文件名，然后pod install就好了。




------------------ 原始邮件 ------------------
发件人: "absss"<notifications@github.com>;
发送时间: 2019年4月25日(星期四) 上午8:52
收件人: "facebook/react"<react@noreply.github.com>;
抄送: "sun,Smile、"<474205755@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [facebook/react] Invariant Violation: requireNativeComponent:"RCTImageView" was not found in the UIManager. (#14464)




我也遇到了同样的问题，我的解决方案是：删除pod文件夹和pod.lock文件，之后再 pod install ，然后全局搜索 RCTImageView， 如果能找到该类的相关信息，则说明问题已经解决。我猜测问题的原因是pod file里面的RCTImage是位于subspecs里面，pod install命令会绕过你已经下载好的库文件，所以重新删除再下载就能把RCTImageView相关文件下载下来，当然，你不嫌麻烦，也可以使用 pod update命令，应该也能解决
