### ISSUE TITLE
Wrong hooks behaviour with event listener

### ISSUE THREAD

**Issue by marklano** [facebook/react#14460]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
CodeSandbox: https://codesandbox.io/s/lrxw1wr97m
1. Click on 'Add card' button 2 times
2. In first card, click on Button1 and see in console that there are 2 cards in state (correct behaviour)
3. In first card, click on Button2 (handled by event listener) and see in console that there are only 1 card in state (wrong behaviour)

Why does it show the wrong state?

**What is the expected behavior?**
Button2 should display 2 cards in console

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.7.0-alpha.0
Chrome 70.0.3538.110 (Official Build) (64-bit)

BTW, if I rewrite the CardsProvider using сlass, the problem is gone. 
CodeSandbox using class: https://codesandbox.io/s/w2nn3mq9vl

**Comment by webcarrot** [comment]
Not a bug - try this:
```js
  useEffect(() => {
    ref.current.addEventListener("click", props.handleCardClick);
    return () => {
      ref.current.removeEventListener("click", props.handleCardClick);
    };
  }, [props.handleCardClick]);
```

**Comment by marklano** [comment]
@webcarrot thanks!
