### ISSUE TITLE
Run multiple React sub-apps inside one React App

### ISSUE THREAD

**Issue by helabenkhalfallah** [facebook/react#14468]
Hello,

I want to make an application that run multiple React sub-apps. 

For example : 
I have an independent application **Chat**.
An independent application **Books**.
I want to have a single application **Books Chat** where users can select a book and make a conversation about it.

**Books Chat** (apps container) call the two applications Books and Chat.
Each application have its own lifecycle.

Is this possible ?
Can I have some how to indications ?

Thanks :)

**Comment by helabenkhalfallah** [comment]
Hello ok it is so clear, I began to do that, but how to call each applications, how to do routing ? Is there any specific settings in webpack ?

**Comment by helabenkhalfallah** [comment]
Know I have to applications hosted at a CDN, I made call into index of the CRA, the remaining thing is how to call and use that applications and my router how it should be, thanks :)

**Comment by bel7aG** [comment]
i think just Redux will solve this 🥇

**Comment by helabenkhalfallah** [comment]
Could you please explain more how does Redux solve this ?? Thanks.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
