### ISSUE TITLE
jest-mock-scheduler was incorrectly published

### ISSUE THREAD

**Issue by Jessidhia** [facebook/react#14465]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

The currently published jest-mock-scheduler is **just** a `package.json` file: https://unpkg.com/jest-mock-scheduler@0.0.0/

**What is the expected behavior?**

It should include requireable js.

**Comment by nhunzaker** [comment]
Gross. @gaearon do you know if this is intentional?

**Comment by threepointone** [comment]
This was mistakenly published, it was meant to be a private package. I'll close this issue.
