### ISSUE TITLE
Whether Hooks and Refs conflict?

### ISSUE THREAD

**Issue by 51Bigod** [facebook/react#14461]
That We intend for Hooks to cover all existing use cases for classes given in the Introducing Hooks, but Refs and the DOM say that You may not use the ref attribute on function components because they don’t have instances. How does React solve the conflict between the two? Dosen`t React any more provide a way to access React component but just Dom nodes?

**Comment by srph** [comment]
I think [forward refs](https://reactjs.org/docs/forwarding-refs.html) touch this use-case.

**Comment by 51Bigod** [comment]
Thank you very much.
