### ISSUE TITLE
eslint-plugin-react-hooks unreachable cases

### ISSUE THREAD

**Issue by BruceWeng** [facebook/react#14478]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
While I am fixing the issue: react-hooks linter fails with unusual for loop #14362, I find some unreachable cases were either passed or not handled. Just wanna confirm the desirable behavior so that I can fix them at once.
Case 1. 
```js
// Pass the linter. Since it's an early return, should it pass?
function Foo() { 
  return true;
  useEffect(() => {});
}
```
Case 2. 
```js
// Linter breaks. Hooks should not allowed in loops. Maybe we should throw a warning?
while(value) { 
  break;
  useEffect(() => {});
}
```
Case 3.
```js
// Linter breaks. Conditional throw error passes. Should we pass this one, too?
throw new Error("Oops!"); 
useEffect(() => {});
```
Case 4.
```js
// Linter breaks, but hooks after infinite while loop passes. 
// Should we pass this one or we should throw warnings for both unreachable cases?
for (;;) {}
useEffect(() => {});
```
**What is the expected behavior?**
Throw a warning or pass.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
eslint-plugin-react-hooks 0.0.0

**Comment by gaearon** [comment]
It seems like if some code is unreachable then it doesn't matter because technically it won't violate rules of Hooks. They'll never be broken in practice.
