### ISSUE TITLE
What's wrong with v16.7.0 ? No Hooks ?

### ISSUE THREAD

**Issue by int64ago** [facebook/react#14471]
>  They’re currently in React v16.7.0-alpha

I think `v16.7.0` > `v16.7.0-alpha`, `v16.7.0` should include features in `v16.7.0-alpha`.

This may break many projects without lock.

**Comment by jquense** [comment]
https://reactjs.org/blog/2018/12/19/react-v-16-7.html

You should generally pin prelease versions to avoid potentional issues, since any bump could be breaking in a prerelease. Please don't be using alpha releases in situations where you expect auto updating deps to not break stuff!
