### ISSUE TITLE
[SSR] Render a bundle file which generate by webpack

### ISSUE THREAD

**Issue by justquanyin** [facebook/react#14470]
Whether support the bundle file which generate by webpack for renderToString/renderToStaticMarkup in SSR ?
Example:

```js

// about.js is a bundle file via webpack ;
const about = fs.readFileSync(path.join(__dirname,'../../build/about.js')).toString();
    const html = ReactDOMServer.renderToStaticMarkup(
      about
    );
   ctx.body = html;
```

Looking forward to a reply ， thanks.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
