### ISSUE TITLE
support loop and condition in react hooks

### ISSUE THREAD

**Issue by xiaoxiangmoe** [facebook/react#14480]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
> Don’t call Hooks inside loops, conditions, or nested function

**What is the expected behavior?**

Support `useCondition`, `useLoop` and so on. 

We need to make small states hooks through `useCondition`& `useLoop` to form a large state hooks.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.7.0.alpha

------

for example

```ts
import { useState, useCallback } from 'react';

interface FooHooks {
  foo: number;
  setFoo: (x: number) => void;
}
const useFoo = (): FooHooks => {
  const [foo, setFoo] = useState<number>(1);
  const setFooWithLog = useCallback((x: number) => {
    console.log(x);
    setFoo(x);
  }, []);
  return { foo, setFoo: setFooWithLog };
};

const useFooList = (fooListLength: number): FooHooks[] => {
  throw new Error('TODO');
};

```

Could you tell me how to write  useFooList?

**Comment by heyimalex** [comment]
If the list never changes length, you can literally do.

```javascript
const useFooList = (fooListLength: number): FooHooks[] => {
  const hooks: FooHooks[] = [];
  for (let i = 0; i < fooListLength; i++) {
    hooks[i](useFoo);
  }
  return hooks;
};
```

If it does change length you should probably write a reducer.

**Comment by lflpowell** [comment]
I thought hooks weren't meant to be called inside loops like this?

**Comment by jsdw** [comment]
They aren't supposed to as a general rule to avoid bugs, but as long as all of the same hooks are called in the same order each time, it'll work as expected.

**Comment by gaearon** [comment]
This is not something we intend to support. You can split a single item in its own component and then it'll "just work".

**Comment by bakhtiyarneyman** [comment]
@gaearon, is this decision you might revisit in the future? The lack of loop support makes the following pattern impossible to use when there is a dynamic number of `Widget`s. 

````
function Widget(datum) {
  const [someComplicatedState, setSomeComplicatedState] = useState()
  ...
  return { element: <> ... </>, publish: () => { ... } } 
}

function WidgetList(props) {
  const widgets = props.data.map(Widget)
  return <>
    <button onClick={widgets.forEach(w => w.publish())}>Publish all</button>
    {widgets.map(w => w.element)}
  </>
}

````

I like this pattern because it cleanly encapsulates state and exposes a minimal API (in this case the function named `publish`). If there is a comparably clean approach to encapsulation, I'd be happy to learn about it.

**Comment by runapp** [comment]
@bakhtiyarneyman Did you find any solution to keep the coding scheme while still using hooks to build components?
