### ISSUE TITLE
unable to use my own UI libray (reactjs+typescript)

### ISSUE THREAD

**Issue by peterremote1980** [facebook/react#14488]
hi, i have created a calendar component https://www.npmjs.com/package/@quantr/quantr-calendar , when i use it in my other project, i got:

```
./node_modules/@quantr/quantr-calendar/src/QuantrCalendar.tsx 17:38
Module parse failed: Unexpected token (17:38)
You may need an appropriate loader to handle this file type.
| var classnames = require('classnames');
|
> class QuantrCalendar extends Component<{ style?: any, myCssClass?: string, month?: number, year?: number, hideTopBar?: boolean }, {}> {
| private rows: any[] = [];
| public weekDayNames: string[] = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
```

Anybody can help please? Source in [https://gitlab.com/quantr/quantr-calendar](https://gitlab.com/quantr/quantr-calendar)

thanks
Peter

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
