### ISSUE TITLE
getDerivedStateFromError receives different error data than componentDidCatch

### ISSUE THREAD

**Issue by japgolly** [facebook/react#14483]
**Do you want to request a *feature* or report a *bug*?**

Could be argued either way.

**What is the current behavior?**

The error value provided to `componentDidCatch` is an object with properties `fileName: String, lineNumber: Int, columnNumber: Int, message: String, stack: String`. On the other hand, the error value provided to `getDerivedStateFromError` is bizarre in that `typeof(error)` is `object` but it has no properties, `toString` returns an error message, and data like `lineNumber` etc don't exist.

**What is the expected behavior?**

I expect the error provided to both `getDerivedStateFromError` and `componentDidCatch` to be the same.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.6.3.

**Comment by japgolly** [comment]
I might me misunderstanding something here... Even though object properties is empty, `.message` and `.stack` work. However, in both cases, `fileName`, `lineNumber`, `columnNumber` no longer work. Have they been removed?

**Comment by fooy2013** [comment]
ในวันที่ ส. 22 ธ.ค. 2018 09:43 David Barri <notifications@github.com>
เขียนว่า:

**Comment by nhunzaker** [comment]
Interesting! @japgolly is there anyway you could produce an example that reproduces this issue using https://codesandbox.io/s/new?
