### ISSUE TITLE
[idea] Per-node DOM configuration

### ISSUE THREAD

**Issue by syranide** [facebook/react#1449]
https://gist.github.com/syranide/51bd85cadd0b439d8a05

Highly unscientific delta below (~700b). Shouldn't be _that_ significantly affected by addition of "behaviors" when doing it proper, contains a bunch of attributes not currently in React and also duplicates the list of node names that exist to create the DOM components.

PS. This is the more or less 100% complete list of nodes and attributes (with the exception of some obscure ones that weren't listed because they are deprecated/not standard).

```
     raw     gz Sizes
380459  75767 build/JSXTransformer.js
622841 127139 build/react-with-addons.js
128227  35285 build/react-with-addons.min.js
566573 115629 build/react.js
118837  32732 build/react.min.js


   raw     gz Sizes
380459  75767 build/JSXTransformer.js
626512 127876 build/react-with-addons.js
130808  35933 build/react-with-addons.min.js
570244 116363 build/react.js
121417  33424 build/react.min.js
```

**Comment by gaearon** [comment]
Seems like we went into a different direction and this is no longer viable.
