### ISSUE TITLE
About setState called many times

### ISSUE THREAD

**Issue by LIUeng** [facebook/react#14491]
https://jsfiddle.net/LIUeng/n5u2wwjg/258328/

errors:
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by LIUeng** [comment]
@fxxkscript @TrySound Thank you! I see, i thought about it! The condition is always true ater the update, so casued an infinite loop!

**Comment by joshi-mehul** [comment]
@LIUeng close the issue, please.

**Comment by LIUeng** [comment]
> @LIUeng close the issue, please.

sorry, already closed.
