### ISSUE TITLE
Local environment is not a problem after the line Error: Minified React error #31; visit

### ISSUE THREAD

**Issue by li941168803** [facebook/react#14496]
react-dom.production.min.js:179 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bmodule%2C%20planList%2C%20taskList%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by mmarkelov** [comment]
@li941168803 it is difficult to say where is problem without code. But you just try to **render** object and React can't render objects

**Comment by mrgurdeep** [comment]
@li941168803 can you reproduce this in jsfiddle

**Comment by nhunzaker** [comment]
I believe @mmarkelov is correct. You'll receive this error if you try to render an object:

https://codesandbox.io/s/zr0pw478rl

It's possible that data you were displaying in a component was changed into an object and is now invalid to render.

Thanks everyone for weighing in, and happy debugging!
