### ISSUE TITLE
Dynamic Context

### ISSUE THREAD

**Issue by joepuzzo** [facebook/react#14498]
I apologize if this has already been discussed but i cant seem to find any information about it. Is there a way to dynamically use context? In other words, i want to call a register function only if the context is available. Currently if i try to use my component and its "Not in context" it will obviously error out asking for a Provider.

**Comment by TrySound** [comment]
You may provide default context to eliminate error.
```js
const Context = React.createContext({
  register: () => {}
})
```

**Comment by joepuzzo** [comment]
Wow thanks! idk why i did not know you could just do this lol
