### ISSUE TITLE
Questions about adding callback to useState hooks

### ISSUE THREAD

**Issue by ddzy** [facebook/react#14493]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
i want to do something after setState, but it doesn't seem to provide a callback parameter.
![issue_1](https://user-images.githubusercontent.com/33921398/50418135-e8fa9980-0864-11e9-8905-9fcee3e4415e.jpg)
![issue_2](https://user-images.githubusercontent.com/33921398/50418137-e8fa9980-0864-11e9-99b5-bb847a6a3dbe.jpg)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Just add a callback into setState....
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by TrySound** [comment]
For this purpose you have `useEffect`.
```js
React.useEffect(() => {
  target.style.cssText += ``
}, [state])
```

**Comment by Kovensky** [comment]
Probably `useLayoutEffect` as the change is user-visible. Depends on whether it's OK for it to happen on a separate animation frame, or on whether it has to be the same frame as the state update happens.

**Comment by ddzy** [comment]
> For this purpose there is `useEffect`.
> 
> ```js
> React.useEffect(() => {
>   target.style.cssText += ``
> }, [state])
> ```

Thks, i have been solved it !!!👀
