### ISSUE TITLE
css-loader@1.0.0: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <7.0.0 || >= 8.9.0".

### ISSUE THREAD

**Issue by Zyanling** [facebook/react#14504]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by jquense** [comment]
Sounds like your trying use an incompatible node is version with webpack. Might want to check our tye node or webpack support avenues. This doesn't seem react related tho

**Comment by sofianeOuafir** [comment]
update in .circleci/config.yml

```
      - run: yarn install --ignore-engines
```

fixed it for me!
