### ISSUE TITLE
Site related issue

### ISSUE THREAD

**Issue by Legends** [facebook/react#14507]
**Do you want to request a *feature* or report a *bug*?**
Bug in your website - Chrome Version 71.0.3578.98 (Official Build) (64-bit)

I know it's not directly related to React itself, feel free to move it to the adequate repo.

**What is the current behavior?**
Cannot see the whole [sidebar](https://reactjs.org/docs/refs-and-the-dom.html)

![image](https://user-images.githubusercontent.com/966368/50541603-83324880-0ba9-11e9-949d-8786ac048e20.png)

If I zoom out to about 60% I can see the whole sidebar!
The same in Edge, FF.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Click the last visible entry in the sidebar. you can also scroll to the bottom of the content, but the rest of the sidebar stays invisible.
**What is the expected behavior?**
 See whole sidebar

**Comment by heyimalex** [comment]
You should submit this over at [reactjs/reactjs.org](https://github.com/reactjs/reactjs.org)

**Comment by Legends** [comment]
Ok, thanks
