### ISSUE TITLE
Why i get this error when trying to > npm start?

### ISSUE THREAD

**Issue by Chawki726** [facebook/react#14518]
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-eslint": "9.0.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-eslint was detected higher up in the tree:

**Comment by urkopineda** [comment]
Same here but with `webpack`

```
The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.19.1"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  /.../<PROJECT_HOME>/node_modules/webpack (version: 2.7.0)
```

**Comment by Chawki726** [comment]
Did you fix the issue?

**Comment by Chawki726** [comment]
its not solve my issue

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
