### ISSUE TITLE
Element disappear when it be with an empty Array

### ISSUE THREAD

**Issue by zy410419243** [facebook/react#14524]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

https://codesandbox.io/s/m7ln2po7jy

Please check this. When  `wrapper` is alone in `render()`, it display correctly, but when add an empty Array with it, `wrapper` disappeared.

Is this a wrong usage of `render`?

**What is the expected behavior?**

`wrapper` render correctly.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

OS => Windows 10, react => 16.7, browser => Chrome 71.0.3578.98

Thanks.

**Comment by Xizario** [comment]
@zy410419243  I think array of arrays is not valid children for the `div` element. You may want to use it like: `{[...wrapper]}` which works fine.

**Comment by carlosrberto** [comment]
@zy410419243 in your example `wrapper.push` calls are mutating react state, you should assign a new Array to `wrapper` before adding new elements

```javascript
let { wrapper } = this.state;
wrapper = [...wrapper]
```

**Comment by zy410419243** [comment]
Thanks a lot

**Comment by Jokcy** [comment]
first of all, @carlosrberto is right, you should never mutate react state. But it's not actually the main reason why you add `{[]}` then the result never come out.

The main reason is when without `{[]}`, the children of `div` is `[ReactElement, ReactElement]`, simple Array. But when with `{[]}`, the children of `div` become `[[ReactElement, ReactElement], []]`, when doing update, React treat every Array as child, which not a valid ReactElement.
