### ISSUE TITLE
reactTestInstance.toJSON() serializer

### ISSUE THREAD

**Issue by mattfysh** [facebook/react#14539]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

`ReactTestInstance` objects cannot currently be serialized to JSON, which prevents them from being used with Jest's `toMatchSnapshot` when wanting to capture a partial tree snapshot

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

```js
const testRenderer = TestRenderer.create(<MyComponent />)
const testInstance = testRenderer.root
const subComponent = testInstance.findByType('SubComponent')
expect(subComponent).toMatchSnapshot()
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The latest version. I've checked the source code, and it may just be a case of exporting this function: https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactTestRenderer.js#L79-L121

**Comment by mattfysh** [comment]
For more context, this helps us to create smaller, more targeted VS avoid large, unwieldy and difficult to maintain snapshots. Some relevant thoughts from @kentcdodds https://blog.kentcdodds.com/effective-snapshot-testing-e0d1a2c28eca

**Comment by martin-braun** [comment]
It's a shame that this has not gotten any further attention, because I am facing the same problem. 

@mattfysh, did you find any solution / bypass to this problem to be able to use the snapshot testing with a sub area of a component?

**Comment by acatalina** [comment]
Would it not be possible to expose `toJSON` like on a `ReactTestRenderer`?

**Comment by Niryo** [comment]
can we reopen this issue? it will be very helpful to have toJSON on the instance level. can someone tell if OP is right and this issue is all about exposing the internal toJSON method? is this the only change needed?

**Comment by kibiz0r** [comment]
@nhunzaker @gaearon Can we reopen this? It seems like a big blind spot.

**Comment by PHCCorso** [comment]
That'd be a really nice feature, since it would be possible to make snapshots smaller by selecting only the component's relevant parts, making it easier to code review stuff.

**Comment by mdjastrzebski** [comment]
I've prepared PR #25329 that exposes `toJSON()` on `ReactTestInstance`. If merged, it would allow for focused snapshots using React Test Render or in React Native apps using React Native Testing Library.
