### ISSUE TITLE
Concurrent mode iOS hover behaviour

### ISSUE THREAD

**Issue by subhero24** [facebook/react#14535]
I hope this is the place to submit issues regarding concurrent mode.
I don't know if this is a bug or intended behaviour, but I have a situation where the my react app behaves differently depending on the use of concurrent mode.

Here is a link to a codesandbox demo: https://codesandbox.io/s/5xl0vnx11p

The behaviour on mobile Safari on iOS (12.1.2) is different whether using ReactDOM.render vs ReactDOM.createRoot. When ReactDOM.render is used, a tap results in an alert and after the alert is dismissed, the hover styles are applied. When using ReactDOM.createRoot, a tap results in the hover styles being applied. A second tap is needed to invoke the click handler.

(This double tap behaviour from iOS is described [here](https://css-tricks.com/annoying-mobile-double-tap-link-issue/))

Shouldn't the two render methods behave the same in this regard? or is this really intended behaviour?

BTW: A setTimout arround the mouseEnter event handler body does make ReactDOM.createRoot behave the same way as ReactDOM.render

**Comment by gaearon** [comment]
I think maybe this check doesn't pass because `_reactRootContainer` field is only used by `ReactDOM.render`:

https://github.com/facebook/react/blob/db695c4d3265d34ead9467b8297e8237bccf2ad6/packages/react-dom/src/client/ReactDOMHostConfig.js#L381-L388

**Comment by gaearon** [comment]
I can't reproduce this anymore. Did iOS change something?

**Comment by subhero24** [comment]
I also can not reproduce this issue anymore. Guess an iOS update fixed it. Thanks for looking into it!
