### ISSUE TITLE
`useReducer` does not honor reducer function's default state value

### ISSUE THREAD

**Issue by sampathsris** [facebook/react#14542]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Please see the CodeSandBox here: https://codesandbox.io/s/v8y72ky0o5

Consider the following reducer:

```js
function reducer(state = 5, { type }) {
  switch (type) {
    case 'INCREMENT':
      return state + 1
    case 'DECREMENT':
      return state - 1
    default:
      return state
  }
}
```

Suppose we are trying to use the reducer in a component like so:

```jsx
function Counter() {
  const [count] = useReducer(reducer)
  return <span>{count}</span>
}
```

When rendered,  `count` is `undefined`.

**What is the expected behavior?**

One would expect `count` to be equal to `5`, because that is the default value for state in the reducer.

IMO, it would make sense if `initialState` argument for `useReducer` is undefined, to call `reducer(undefined, undefined)` to initialize the internal state.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.7.0-alpha.2

**Comment by carlosrberto** [comment]
@sampathsris the default state value will be returned when an invalid action is dispatched.
The initial state for `useReducer` hook should be passed as a second argument to `useReducer`:
```js
useReducer(reducer, initialState);
```
I understand your point. When using Redux, in the moment when the store is created Redux dispatch an initialization action and all reducers return the default state.

Maybe something like this could be implemented in the `useReducer` hook.

**Comment by ckknight** [comment]
`useReducer(reducer, undefined, { type: 'INIT' })` will work as you expect. It will execute the reducer initially, once, with a `{ type: 'INIT' }` action, thus falling through to the default case. Because `initialState` is provided as `undefined`, it will appropriately default to `5` as specified in the reducer.

**Comment by carlosrberto** [comment]
@sampathsris I opened a [pull request](https://github.com/facebook/react/pull/14566) with a proposal to make this works.

**Comment by gaearon** [comment]
I think `useReducer(reducer, undefined, { type: 'INIT' })` is what we suggest so that strong typing can work.

**Comment by carlosrberto** [comment]
What do you think about #14566 @gaearon ?
Any chance of these changes be introduced ?

**Comment by gaearon** [comment]
Did you see my comment above?

**Comment by ckknight** [comment]
I don’t like the idea of an untyped action being dispatched implicitly without the ability to prevent that.

**Comment by carlosrberto** [comment]
> Did you see my comment above?

Yes I see! And I understand that this is the recommended way.

I just still think that an initialization action could be dispatched automatically, like in Redux when we create a store.

But I understand if this is not the desired behavior for this hook.

**Comment by carlosrberto** [comment]
> I don’t like the idea of an untyped action being dispatched implicitly without the ability to prevent that.

Could be changed to a typed action (`{ type: 'INIT' }`)

**Comment by gaearon** [comment]
We ended up changing this API in response to feedback. See https://github.com/facebook/react/issues/14624#issuecomment-461872785.
