### ISSUE TITLE
A new react-cache alpha release is required for compatibility with react@16.8.0-alpha.1

### ISSUE THREAD

**Issue by apostolos** [facebook/react#14558]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`react-cache@2.0.0-alpha.1` does not work with `react@16.8.0-alpha.0` or `react@16.8.0-alpha.1` because of a recent change in React internals (separation of current dispatcher from current owner).

**What is the expected behavior?**
It looks like the necessary changes to react-cache have already been made: https://github.com/facebook/react/commit/19ef0ec116a2c5fd1a8dc86d38c2185d62abc6a1
A release of a new alpha version of the react-cache package should resolve the issue.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- react@16.8.0-alpha.0
- react@16.8.0-alpha.1

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/14780
