### ISSUE TITLE
Cursor jumps with controlled input with email type

### ISSUE THREAD

**Issue by cdbean** [facebook/react#14551]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**

With an email input (`<input type="email" />`), the cursor jumps when there is space. Try the demo https://codesandbox.io/s/y7y93p2zx?moduleview=1. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

![jan-08-2019 15-25-44](https://user-images.githubusercontent.com/578035/50865307-0ac24900-135a-11e9-81d3-9eb05c937533.gif)

**What is the expected behavior?**
The cursor should remain in the right position as user types

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16
Chrome and Safari, not firefox

**Comment by cdbean** [comment]
Seems it is a known issue https://twitter.com/kentcdodds/status/1082705003955933184. I'll probably close this

**Comment by gaearon** [comment]
@imdongchen For the future, please don't close issues because somebody reported them on Twitter. GitHub is where we track them, not Twitter. :-)

**Comment by gaearon** [comment]
Tracking this in https://github.com/facebook/react/issues/15418.
