### ISSUE TITLE
available free pre-paid gift cards for learning React  1-on-1 with experts

### ISSUE THREAD

**Issue by przeor** [facebook/react#14561]
FYI: 
I have available $20 pre-paid gift cards that you can use for learning React/Node and Javascript 1-on-1 with experts on the Experty learning platform. Just leave the comment and I will send it to you - via using contact details on your profiles - FOR FREE.

This will help you improve your react skills.

**Comment by philipp-spiess** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.
