### ISSUE TITLE
z-index in component

### ISSUE THREAD

**Issue by username99987** [facebook/react#1456]
When try to set `z-index` of a  div inside a component via `style={"z-index": "-99"}` it doesn't work. In element inspector it becomes "z-index: 0px".

Is there workaround for this?

**Comment by nmccready** [comment]
So many other properties are supported with quotes. Why is this one any different? This is inconsistent.

**Comment by nmccready** [comment]
Please disregard, for some reason I am finally seeing the errors for other styles which used dash. Camel case is the standard.

**Comment by sophiebits** [comment]
We've had this warning since v0.12 in 2014 now. (One of @gaearon's first PRs!)
