### ISSUE TITLE
React.Children.count returns invalid number of children

### ISSUE THREAD

**Issue by pronebird** [facebook/react#14564]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

>nextProps.children
> false

>React.Children.count(nextProps.children)
>1

>React.Children.toArray(nextProps.children).length
>0

>React.version
>"16.4.2"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

That `React.Children.count(false)` behaviour is somehow aligned with `React.Children.toArray(false)`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by pronebird** [comment]
>When children is passed as false, it is >considered a single child, which is why the >count reports as 1 and evaluates to [false].

>If you would like to pass a value into >children that is ignored, consider passing >null or undefined.

That’s exsctly the bug I am reporting that toArray and count act different

**Comment by nhunzaker** [comment]
Ah, you're totally right, and I apologize:

![image](https://user-images.githubusercontent.com/590904/52657198-f8818080-2eac-11e9-951b-748011feece7.png)

Here's a test case:
https://codesandbox.io/s/rwk4qr61po

I think this is, indeed, a bug.

**Comment by nhunzaker** [comment]
It looks like `toArray` also strips out `true`, which is ignored by JSX as well. We to determine if this is intended, and if so, clarify in the documentation:

https://reactjs.org/docs/react-api.html#reactchildrentoarray

We also need to determine if `count` should match up to `toArray()`

We should also make sure there is a test case that covers this in the React.Children tests, so far, I only see tests for `undefined` and `null`:

https://github.com/facebook/react/blob/f3a14951ab9bccfd59ca977493b72321b24e50a5/packages/react/src/__tests__/ReactChildren-test.js#L813-L848

I imagine this would also be a breaking change if code depends on `toArray` to only return renderable items.

**Comment by pronebird** [comment]
```
React.Children.count(false) == 1
React.Children.count([false]) == 1
React.Children.count(null) == 0
React.Children.count(undefined) == 0
React.Children.count([null]) == 1
React.Children.count([undefined]) == 1
```

Then if you run the same input via `React.Children.forEach` you'll find out that it matches entirely the way `React.Children.count` works. Not sure why such a special treatment for `null` and `undefined` and why `false` is treated differently.

**Comment by nhunzaker** [comment]
Okay! I spoke with a few members of the team and I think we got to the bottom of this.

The behavior is intentional, even if confusing. `count` gives you the number of "slots" children defines. When passing `null` or `undefined` for children, React considers children to be absent. However when given an array, like `[null]`, React considers there to be a "slot" open in children, even if the value is null.

I agree that this is confusing. I think a good next step would be to improve the documentation so that the current behavior is clear. We could also consider revising the API to be more intuitive, however we'd need to make that change in a major release (17).

**Comment by amannn** [comment]
I also just noticed that render prop children are not counted as a child:

```js
Children.count(() => <span>hello</span>); // 0
Children.map(() => <span>hello</span>); // []
```
