### ISSUE TITLE
Overriding updater in React class doesn't have any effect or error

### ISSUE THREAD

**Issue by ShizukuIchi** [facebook/react#14568]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Overriding `updater` in React class doesn't have any effect or error.

**What is the expected behavior?**
Maybe there should be a reserved words list in React docs to prevent anyone from doing this accidentally.
Or add warnings for overriding these words.
```javascript
class App extends React.Component {
  state = { count: 0 };
  updater = () => {
    this.setState(state => ({ count: state.count + 1 }));
  };
  render() {
    return <button onClick={this.updater}>{this.state.count}</button>;
  }
}

/*
Warning: Expected `onClick` listener to be a function, instead got a value of `object` type.
    in button (created by App)
    in App
*/
```

**Comment by aweary** [comment]
Hey @ShizukuIchi! This [has been brought up before](https://github.com/facebook/react/issues/9164) and [a fix was submitted](https://github.com/facebook/react/pull/9236) but ultimately we decided that [it wasn't worth the cost](https://github.com/facebook/react/pull/9236#issuecomment-355578216). It's a pretty uncommon edge case, and with Hooks it's likely that it will be even less common, so it's still not worth the cost.

Thanks though!
