### ISSUE TITLE
Why NPM releases are not mapped to the repository under Releases section?

### ISSUE THREAD

**Issue by rdsedmundo** [facebook/react#14562]
Firstly, I'm sorry if opening an issue here it's the wrong place to ask that, but since it's very attached to the repository itself I raised it here as a "meta-issue".

I'd like to know if there's a special reason why NPM releases aren't making it to the [Releases section](https://github.com/facebook/react/releases) of the repository here. I'm mainly talking about the latest `alpha` versions that include React Hooks. I noticed from NPM that a new `next` was available under `16.8.0-alpha.0` and I went to the repository here to understand what had changed from `16.7.0-alpha.2` that I was using, however, didn't find any mention of this release on the "Releases" section. I had to go through closed PRs to understand that #14555 was the PR that did the change and was published.

Thanks.

**Comment by gaearon** [comment]
"Releases" generally contain stable releases. We don't want to give extra visibility to alpha releases and to make it seem like we encourage their usage. (Remember, they're likely to have bugs!)

We also generally don't write changelogs for alpha releases. If you want something that's ready to be used and trusted, and don't have time to dig through PRs and commits, please only use stable releases.

Thanks!

**Comment by rdsedmundo** [comment]
It never was a matter of not having time to look on PRs and commits, I went on the repository exactly looking for some reference after finding the NPM release there.

I've seen this being used already in many other repositories, namely Vue, Angular, and Boostrap, for instance. Github even has a "Pre-Release" badge that can be used for those alpha/beta releases.

IMO, there's no difference on risky associated of having it here on the repository on the Releases section compared to going on npmjs and seeing it under "Versions" named "next".

Another benefit it provides is the ability to use the Watch for releases functionality and know immediately when something new is published.
