### ISSUE TITLE
`alert`, `confirm`, `prompt` in handler become non-blocking after switching tab/window

### ISSUE THREAD

**Issue by kdepp** [facebook/react#14578]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In Chrome, `alert`, `confirm`, `prompt` used in event handler is not blocking the following operations if you switch to another tab and switch back.

Firefox and Safari works fine for me

* `alert` box is still shown, but following operations are executed
* `prompt` box is closed automatically,  returned `null`, following operations are executed
* `confirm` box is closed automatically,  returned `false`, following operations are executed

**Reproduce:**
https://jsfiddle.net/6saqvgh4/14/

You can try to click those 3 buttons,  switch to another tab/window and switch back

**What is the expected behavior?**
All those three (`alert`, `prompt`, `confirm`) should block any trailing operations in event handler

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested in 16.2.0 and 16.7.0, both can reproduce.

**Comment by aweary** [comment]
@kdepp have to confirmed that this only happens when using React? I'm betting that you'd see the same behavior in a version that just used the DOM APIs directly.

**Comment by kdepp** [comment]
Thanks @aweary .  You're right.   https://jsfiddle.net/9vbhzufx/  without react has the same problem. 

Looks like it's a change on Chrome made in 2017. https://developers.google.com/web/updates/2017/03/dialogs-policy

Closing this one
