### ISSUE TITLE
Cannot ready property 'readContext' of undefined

### ISSUE THREAD

**Issue by kevinwolfcr** [facebook/react#14575]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
`react-cache` is not working with Suspense.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox**
https://codesandbox.io/s/3jw6y3ww6

**What is the expected behavior?**
To show the loading screen, or at least not to fail

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: 16.8.0-alpha.0
react-dom: 16.8.0-alpha.0
react-cache: 2.0.0-alpha.1

**Comment by 498628255** [comment]
If you just want to run the program in the development env, you can modify the code in 'react-cache/cjs/react-cache.development.js' by yourself:   
old: 
`
var currentOwner = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner;

function readContext(Context, observedBits) {
  var dispatcher = currentOwner.currentDispatcher;
  if (dispatcher === null) {
    throw new Error('react-cache: read and preload may only be called from within a ' + "component's render. They are not supported in event handlers or " + 'lifecycle methods.');
  }
  return dispatcher.readContext(Context, observedBits);
}
`
'currentOwner' is no use except in function readContext. so here is the new:
`
var currentDispatcher = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentDispatcher;

function readContext(Context, observedBits) {
  var dispatcher = currentDispatcher.current;
  if (dispatcher === null) {
    throw new Error('react-cache: read and preload may only be called from within a ' + "component's render. They are not supported in event handlers or " + 'lifecycle methods.');
  }
  return dispatcher.readContext(Context, observedBits);
}
`
And that work in my code.

**Comment by threepointone** [comment]
Did you delete your codesandbox repro? Please add it so I can have a look. also, can you try with the newer alpha? (16.8.0-alpha.1)

**Comment by gaearon** [comment]
(This is expected to not work until we release an update to `react-cache` that users the new dispatcher field)

**Comment by gaearon** [comment]
See https://github.com/facebook/react/issues/14780#issuecomment-461861948.
