### ISSUE TITLE
Hydration breaks when accessing props in constructor which doesnt exist

### ISSUE THREAD

**Issue by pgangwani** [facebook/react#14579]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
A descedent component which tried to access props.somepropA (undeclared prop) in constructor broke hydration and because of  other un-mounted component didnt remove from DOM and things started breaking on load. In my case i was getting infinite loader which is not mounted.

**What is the expected behavior?**
 Loader should have been removod from DOM as we get data on load and redux state is set properly. 
Not able to understand how to fix it 

Things are working fine as in client side rendered app.

**Comment by aweary** [comment]
@pgangwani can you please provide an example reproducing the problem? There were [helpful links](https://codesandbox.io/s/new) for that in the section of the issue template you deleted.

**Comment by pgangwani** [comment]
Not able to reproduce in code sandbox so closing for now
