### ISSUE TITLE
[Hooks] useImperativeMethods should expose its content

### ISSUE THREAD

**Issue by drcmda** [facebook/react#14580]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

```js
const api = useImperativeMethods(ref, () => ({
  start: () => Promise.all(ctrl.current.map(c => c.start())),
  stop: () => ctrl.current.forEach(c => c.stop()),
}))

// api is undefined
```

Users can use the api from outside by forwarding a ref, but it is sealed inside and cannot be re-used

**What is the expected behavior?**

```js
const api = useImperativeMethods(ref, () => ({
  start: () => Promise.all(ctrl.current.map(c => c.start())),
  stop: () => ctrl.current.forEach(c => c.stop()),
}))

api.start()
api.stop()
```

Now we can re-use our code and even treat it like a public api that can be used outside or inside (like public class methods in reacts class components which could be used by ref or internally). The api-object could of course be wrapped into useState or useMemo prior to feeding it to useImperativeMethods, but it would be yet another step and if it would just channel through its input it would be cleaner.

I would also expect the api to be present if "ref" is undefined.

**Comment by gaearon** [comment]
Why not this if you need it?

```js
const api = {
  start: () => Promise.all(ctrl.current.map(c => c.start())),
  stop: () => ctrl.current.forEach(c => c.stop()),
};
useImperativeMethods(ref, () => api);
```

I don't think what you're asking for would work because the object creation is delayed until the commit phase. If you don't want to delay it, you might as well create one yourself early. But since you *might* want to delay it — that's what the API lets you do.

**Comment by Jessidhia** [comment]
Your snippet creates a new object every time, useImperativeHandle follows the rules of useMemo.

**Comment by gaearon** [comment]
You can `useMemo` directly if that bothers you. But don't forget that every time you write `<div />` you also create a new object. I don't see people being as worried about doing that.
