### ISSUE TITLE
Set function returned by useState executes functions passed to it

### ISSUE THREAD

**Issue by ajpocus** [facebook/react#14581]
**Do you want to request a *feature* or report a *bug*?**

It might be a bug, or it might just be behavior I didn't expect.

**What is the current behavior?**

The current behavior is that the set function returned by `useState` appears to execute functions passed to it. I've replicated this behavior in the CodeSandbox link below -- check the console logs to see the behavior I'm describing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

[https://codesandbox.io/s/r559xx4n9o](https://codesandbox.io/s/r559xx4n9o)

**What is the expected behavior?**

I expect the set function returned by `useState` to behave like `this.setState`, and simply store the function, not execute it (although I may be missing a use case where such behavior would be useful). If I'm missing something here, please let me know!

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm using React 16.7.0-alpha.2, with Firefox 64.0 on Ubuntu 18.04.1. If I'm missing something here, if I missed a note in the docs or if I'm just being stupid and missing the point of executing functions on set, please, let me know!

**Comment by markerikson** [comment]
Per the [Hooks API reference on `useState`](https://reactjs.org/docs/hooks-reference.html#functional-updates), passing a function to the `useState` setter is equivalent to [the "functional updater form" of a component's `setState()` method](https://reactjs.org/docs/react-component.html#setstate).  React will call that function with the existing state value and allow the function to return the state fields to update.

**Comment by ajpocus** [comment]
Gotcha, sorry I missed that. I'll close this then. Thank you for pointing that out!
