### ISSUE TITLE
More on: react-scripts: not found

### ISSUE THREAD

**Issue by MasterJames** [facebook/react#14589]
I've got more to report on this problem with react-scripts not found error.
Here is the error running 'npm start'

```
/myapp/front# npm start

> front@0.1.0 start /myapp/front
> react-scripts start

sh: 1: react-scripts: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! front@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the front@0.1.0 start script.
```

If one runs 'npx react-scripts start' it forces a rebuild of the entire 1980 packages?!!
But it does eventually run.

The setup issue is that the Ubuntu VM is running on an NFS Mount from Win8

First problem is all the bin files can't build, but if you build initially on VM's disk image VDI, and then copy back to real files over an NFS mount the second problem is it can't copy symbolic links (maybe an option to copy the source if symlink fails exists or should).

Okay so once you have the symbolic links repaired in windows via mklink after copying the initial build from a none NFS mount folder, well that's when this problem described above happens.

I am unclear on which one of the 1980 packages other then this react-scripts is in need or a total rethink but it doesn't cut it when setup in this way. (Using symbolic links seems literally unacceptable.)

It seems not unreasonable to think you should be able to use your platform/IDEs of choice and have the UNIX VM mount and work of those NFS Mounted files. The way all this stuff is build falls short of this I call expected behaviors. 

The only problems are why isn't 'npm start' able to run 'npx react-scripts start', and in turn why does that not understand the package is already built and take forever to rebuild all packages every time? I think it also relates to file watching. Maybe there is a way to deploy this without waiting 10 minutes to launch a simple example.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests for React itself. `react-scripts` is not part of React, it's part of [create-react-app](https://github.com/facebook/create-react-app).

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by MasterJames** [comment]
Oh okay thanks for the info. Re-submitted.
https://github.com/facebook/create-react-app/issues/6197
