### ISSUE TITLE
Allow for named imports in React.lazy

### ISSUE THREAD

**Issue by gnestor** [facebook/react#14603]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently, React.lazy only accepts an anonymous function that returns a dynamic import object. `readLazyComponentType` then [pulls the default export off of that import object](https://github.com/facebook/react/blob/f777d196e0943b3975c762e15e35b319a9b85902/packages/react-reconciler/src/ReactFiberLazyComponent.js#L53). This does not allow for importing named imports from a module. 

The official workaround, according to [the React docs](https://reactjs.org/docs/code-splitting.html#named-exports):

> If the module you want to import uses named exports, you can create an intermediate module that reexports it as the default.

Another, [more concise workaround](https://github.com/facebook/react/issues/14390#issuecomment-444494386):

```js
const Contacts = React.lazy(() =>
  import('./Contacts.js').then(module => ({ default: module.Contacts }))
);
```

**What is the proposed behavior?**

I'd be willing to submit a PR that optionally accepts named imports but defaults to importing the default import. It would look like:

```diff
thenable.then(
-  moduleObject => {
+  resolvedComponent => {
    if (lazyComponent._status === Pending) {
-      const defaultExport = moduleObject.default;
+      if (resolvedComponent.default) {
+        resolvedComponent = resolvedComponent.default
+      }
      if (__DEV__) {
-        if (defaultExport === undefined) {
+        if (resolvedComponent === undefined) {
          warning(
            false,
-            'lazy: Expected the result of a dynamic import() call. ' +
+            'lazy: Expected a promise that resolves to a React component. ' +
              'Instead received: %s\n\nYour code should look like: \n  ' +
              "const MyComponent = lazy(() => import('./MyComponent'))",
-            moduleObject,
+            resolvedComponent,
          );
        }
      }
      lazyComponent._status = Resolved;
-      lazyComponent._result = defaultExport;
+      lazyComponent._result = resolvedComponent;
    }
  },
  error => {
    if (lazyComponent._status === Pending) {
      lazyComponent._status = Rejected;
      lazyComponent._result = error;
    }
  },
);
```

This will also require some updates to the docs.

Let me know your thoughts before I start...

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@16.7.0, Chrome 71, macOS 10.14

cc @acdlite @gaearon

**Comment by gaearon** [comment]
Thanks but it's an intentional design decision to not currently allow named imports. We may reconsider it later. You can find the relevant discussion in https://github.com/reactjs/rfcs/pull/64.

**Comment by nelsieborja** [comment]
This may seem stupid but I expected the feature to have the following syntax:
```js
React.lazy('./MyComponent');
```
No more extra function or `import` required

**Comment by amitesh786** [comment]
> This may seem stupid but I expected the feature to have the following syntax:
> 
> ```js
> React.lazy('./MyComponent');
> ```
> 
> No more extra function or `import` required

It's not working, but I have tried this ->

`React.lazy(() => import('../MyComponent'), 'default');`

It works fine!

**Comment by cchamberlain** [comment]
This makes SFC components pretty annoying to use...

**Comment by eps1lon** [comment]
Summary of why named exports are not baked in and a workaround can be found in https://github.com/reactjs/rfcs/pull/64#issuecomment-431507924

**Comment by dailytabs** [comment]
`npm audit` said I needed to update to react-scripts 4.0.0 as the only solution to a vulnerability. After upgrade, new ESLint rules went into effect warning about default exports. So, I removed all my default exports and replaced them with named. Now, my router doesn't work.

Thanks so much for not supporting this and making things harder on me. Probably time to reconsider this issue and the comment linked to in the previous comment.

**Comment by JoseLion** [comment]
Working with default exports on Function Components is very inconvenient. I hope the React team can revisit this soon. IMO `React.lazy` is a very powerful tool, so I created a small abstraction of @gnestor's workaround to make the lazy import a bit simpler. When used with TypeScript it's 100% type-safe and keeps the look and feel of named imports. I hope this helps! 🙂 
```ts
function lazyImport<
  T extends React.ComponentType<any>,
  I extends { [K2 in K]: T },
  K extends keyof I,
>(
  factory: () => Promise<I>,
  name: K
): I {
  return Object.create({
    [name]: React.lazy(() => factory().then(module => ({ default:  module[name] })))
  });
}

// Usage
const { Home } = lazyImport(() => import("./Home.component.tsx"), "Home");
```

PS: The `Object.create(..)` is to avoid conflicts with the object key and the `K` type. Another way would be to cast the object `as unknown as I`, but I think this looks a bit cleaner 🙂

**Comment by JLarky** [comment]
@JoseLion you could also use `Proxy` which allows even crazy stuff like this :)

```js
const { Component1, Component2 } = lazily(() => import('./Components'))
```

Proxy:
```
export function lazily(loader) {
  new Proxy( {}, {
      get: (target, componentName) =>
        React.lazy(() =>
          loader(componentName).then((x) => ({ default: x[componentName] }))
        ),
    }
  )
}
```

You could try it out here https://codesandbox.io/s/react-lazily-example-p7hyj

**Comment by dailytabs** [comment]
Seriously? Why not just fix the damn thing! Humans are too content with workarounds. Try to actually fix something and maybe the world won't be such a pile of trash.

**Comment by aress31** [comment]
Any update on that, totally agree with @dailytabs I don't want to rely on a third party library for this.

**Comment by mrchantey** [comment]
According to the [React code splitting docs](https://reactjs.org/docs/code-splitting.html#named-exports):
> [limiting to default exports] ensures that tree shaking keeps working and that you don’t pull in unused components.

**Comment by can-acar** [comment]
I get an error when I use React.lazy with sass, for example :
It's working code :
'App.js'

```
import React, { Suspense, lazy} from "react";
import "./App.scss";


const Test = lazy(() => import("./test"));

const App = () => {
  return (
    <div className={""}>
      <Suspense fallback={<p>....</p>}>
        <Test />
      </Suspense>
    </div>
  );
};

export default App;
```

BUT!

If  I change  this code for this example :

```
import React, { Suspense, lazy, useState, useEffect } from "react";
import "./App.scss";


const load = (path) => {
  let Component= lazy(() => import(`./${path}`));
 return   <Suspense fallback={<p>....</p>}>
                <Component {...this} />
          </Suspense>;
};

const Test = load('test');

const App = () => {
  return (
    <div className={""}>

        <Test />

    </div>
  );
};

export default App;
```

not working.
