### ISSUE TITLE
 Can't resolve 'react-dom/lib/ReactTestUtils' in   react-addons-test-utils,react 16

### ISSUE THREAD

**Issue by zhoulujun** [facebook/react#14605]
Module not found: Error: Can't resolve 'react-dom/lib/ReactTestUtils' in '/www/wepack4-react-project-template/node_modules/react-addons-test-utils'

i think this must update react-addons-test-utils,but it new.
i don't know how to resolve

**Comment by gaearon** [comment]
`react-addons-test-utils` doesn't work in React 16.
Please make sure that you read migration instructions when you update React.

https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#react-test-utils
