### ISSUE TITLE
Where did the name React come from?

### ISSUE THREAD

**Issue by hg-pyun** [facebook/react#14606]
Hello! React is really cool. I've been wondering, where does React naming come from? Is it from Reactive Programming?

It would be nice if you could tell me about the origins. 
Thank you very much.

**Comment by adamzerella** [comment]
As pointed out by @gaearon in [this talk](https://youtu.be/dpw9EHDh2bM?t=3455) the name React has an interpretation of chemical reactions, with the atomic logo, atoms participate in chemical reactions. I think the idea general idea though, is that it's up to your own interpretation.

**Comment by ngyikp** [comment]
This blog post talks about the name too: https://reactjs.org/blog/2016/09/28/our-first-50000-stars.html#fbolt-is-born

**Comment by loubacking** [comment]
@adamzerella I was thinking to use the same video to respond it 😄

**Comment by gaearon** [comment]
Note I'm not saying this is where it came from — just my first associations with it. Need to find how Tom came up with the name. :P

**Comment by gaearon** [comment]
Yeah I don't think we have anything beyond Jordan considering rendering "reactive" to changing inputs. Even though it's not strictly reactive programming.
