### ISSUE TITLE
Fabric create new canvas component instead of adding Object into the canvas

### ISSUE THREAD

**Issue by naijab** [facebook/react#14612]
For detail: 

https://stackoverflow.com/questions/54227761/fabric-create-new-canvas-component-instead-of-adding-object-into-the-canvas

**Comment by nhunzaker** [comment]
Hey @naijab! This issue board is focused on issues directly related to React. We aren't familiar with the Fabric API, and aren't equipped to help debug.

You might be able to find someone familiar with Fabric on the Reactiflux discord chat or on other community resources. Check out a list of them here:

https://reactjs.org/community/support.html
