### ISSUE TITLE
Define validity period of setters returned by useState

### ISSUE THREAD

**Issue by raiskila** [facebook/react#14614]
Hi,

When using `useEffect()`, `useMemo()` or `useCallback()`, we can use the 2nd argument to avoid rerunning the effect or updating the value unnecessarily if the values it depends on haven't changed.

Should I include setters returned from `useState()` in the 2nd argument of these hooks? E.g.

```javascript
const [value, setValue] = useState(5);

useEffect(() => {
  // Hand off setValue somewhere
}, [setValue]); // ?
```

I'm wondering what the exact validity guarantees are around the setters returned by `useState()` or the dispatch functions returned by `useReducer()`. According to the docs, the dispatch function returned by `useReducer()` shouldn't change between re-renders, so it shouldn't be necessary to include it in the 2nd argument of these hooks. `useState()` seems to use `useReducer()` internally, so the same is possibly true for it. Is it officially guaranteed that any setter returned by `useState()` remains valid until the component unmounts?

**Comment by gaearon** [comment]
Yes — so it doesn't matter in practice. 

We may offer a lint rule that may ask you to include them for consistency but they're going to stay the same between renders.
