### ISSUE TITLE
Typescript forwardRef displayName

### ISSUE THREAD

**Issue by dfee** [facebook/react#14610]
Apparently the render method on `forwardRef` contains a `displayName` property as can be observed here: https://github.com/facebook/react/blob/769b1f270e1251d9dbdce0fcbd9e92e502d059b8/packages/shared/getComponentName.js#L28

However, the Typescript types instead place the `displayName` on the root object, (`NamedExoticComponent`)[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/33f6179e0f25b0ca798ad89a667c0a27ea0c98dd/types/react/index.d.ts#L297]

(which doesn't seem to be applicable).

In addition, it seems that [`ForwardRefExoticComponent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/33f6179e0f25b0ca798ad89a667c0a27ea0c98dd/types/react/index.d.ts#L698) could either forward the call signature of the [`RefForwardingComponent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/33f6179e0f25b0ca798ad89a667c0a27ea0c98dd/types/react/index.d.ts#L471) ... or define it, itself:

```typescript
interface ForwardRefExoticComponent<P> extends NamedExoticComponent<P> {
  defaultProps?: Partial<P>;
  render: {
    (props: P & { children?: ReactNode }, ref: Ref<T> | null): ReactElement<any> | null;
    displayName?: string;
  }
}
```

**Comment by Kovensky** [comment]
This is because it _is_ possible to set a `displayName` in the `React.forwardRef` itself.

I consulted the (then-current) React DevTools source code when declaring where `displayName` is allowed to be defined.

**Comment by aweary** [comment]
The TypeScript definitions are maintained by the community, not the core team. I recommend bringing up any issues at https://github.com/DefinitelyTyped/DefinitelyTyped, which is the source of truth for these type definitions AFAIK. Thanks!
