### ISSUE TITLE
useImperativeHandle should warn when second arg isn't a function

### ISSUE THREAD

**Issue by lorenzomigliorero** [facebook/react#14629]
I've noticed a strange bug with the react redux `forwardRef` opt-in.
If i use it with a connected class component, everything is ok:
```javascript
const MyComponent = class Test extends React.Component {
  foo = () => console.log("Print foo from Test component");
  render() {
    return null;
  }
};

const ConnectedComponent = connect(
  null,
  null,
  null,
  { forwardRef: true }
)(MyComponent);

const store = createStore(() => {});

function App() {
  return (
    <Provider store={store}>
      <ConnectedComponent
        ref={ref => {
          if (ref) ref.foo();
        }}
      />
    </Provider>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
If i use it with a connected functional component that use `forwardRef` with `useImperativeHandle`, i obtain a strange error: `create is not a function` in `commitHookEffectList` `react-dom` method.

```javascript
const MyComponent = React.forwardRef((props, ref) => {
  useImperativeHandle(ref, {
    foo: () => console.log("Print foo from Test component")
  });

  return null;
});

const ConnectedComponent = connect(
  null,
  null,
  null,
  { forwardRef: true }
)(MyComponent);

const store = createStore(() => {});

function App() {
  return (
    <Provider store={store}>
      <ConnectedComponent
        ref={ref => {
          if (ref) ref.foo();
        }}
      />
    </Provider>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

I create a codepen to reproduce the issue: https://codesandbox.io/s/r7rpml460o

PS: Sorry for the cors error, but i don't find the way to add `react@next`as cdn

**Comment by hamlim** [comment]
I believe the issue here is that `useImperativeHandle` expects the second argument to be a function that returns the reference:

```js
// before (your sample code)
useImperativeHandle(ref, {
  foo: () => console.log("Print foo from Test component")
});
// after
useImperativeHandle(ref, () => ({
  foo: () => console.log("Print foo from Test component")
}));
```

See: https://reactjs.org/docs/hooks-reference.html#useimperativehandle for more information about the API of the hook.

Maybe the error thrown could be more clear?

**Comment by lorenzomigliorero** [comment]
You're right, `useImperativeHandle` accept a function as first argument.
A warning on wrong type argument could be a good idea.

**Comment by Aberman12** [comment]
Ill take this issue on

**Comment by gaearon** [comment]
Sire

**Comment by gaearon** [comment]
Yeah, it was renamed.

**Comment by AhmedElywa** [comment]
yes it work good after rename it where i can get changes between alpha version ?

**Comment by gaearon** [comment]
Commit log. We don't write changelogs for alphas.

**Comment by gaearon** [comment]
@Aberman12 I'm taking this in https://github.com/facebook/react/pull/14647 since we want to get Hooks out sooner.

**Comment by Aberman12** [comment]
alright np
