### ISSUE TITLE
Will  dangerouslySetInnerHTML generate  more html element ?

### ISSUE THREAD

**Issue by Zaynex** [facebook/react#14668]
**Do you want to request a *feature* or report a *bug*?**
Hi, React Team. Thanks for your awesome work. I have a problem when using 
`dangerouslySetInnerHTML` 

**What is the current behavior?**

My example code like this:
```
//...  the node.topic is a string
render() {
    const { node, className, style } = this.props;
    return (
      <div
        tabIndex={0}
        contentEditable={true}
        id="editor"
        onKeyDown={this.handleKeyDown}
        spellCheck={false}
        onBlur={this.handleBlur}
        onPaste={this.handlePaste}
        ref={this.containerRef}
        dangerouslySetInnerHTML={{ __html: node.topic }}
        style={style}
      />
    );
  }
```

But I got unexpected html that looks like
![image](https://user-images.githubusercontent.com/13745971/51608727-3a28a680-1f53-11e9-9c6a-1b9161b63d67.png)
![image](https://user-images.githubusercontent.com/13745971/51608733-3eed5a80-1f53-11e9-8232-456034ce6e13.png)

**What is the expected behavior?**
It's hard for me to debug what's wrong with it. It's sometimes work, but sometimes will generate a `<br/>` tag. 
Maybe the `<br />` tag is generated by my browser ?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
react 16.7.0
react-dom 16.7.0
OS: macos 10.14.1 Beta (18B73a)
Chrome: 71.0.3578.98
```

**Comment by threepointone** [comment]
Can you isolate this behaviour to a small test case on codesandbox? Are you saying `node.topic` doesn't contain the `br`, but react adds it? I'd recommend logging that value to be sure.

**Comment by Zaynex** [comment]
It's my fault.
When I press enter， I forgot to use preventDefault.So  the  `<div>` render string with the `br`.
Thanks,I will close it.
