### ISSUE TITLE
react-router can't pass Hooks

### ISSUE THREAD

**Issue by desmap** [facebook/react#14664]
This is actually an issue of react-router https://github.com/ReactTraining/react-router/issues/6555 but since it's the major routing lib I want to make you aware that there are issues when you want to pass custom hooks via props through your component tree.

Since routing (with react-router) is a regular use case and React Hooks is an easy/elegant way to manage state through the app they should work together. Otherwise React Hooks is about creating Hooks limited to just one component and you cannot share state/hooks component-wide. Maybe I didn't get something right and there is a way...

**Comment by gaearon** [comment]
We’ll need a concrete example. It’s not very clear what you mean.

**Comment by desmap** [comment]
Ok, example is there and hope it's now clearer : https://codesandbox.io/s/o4wxn5y8k5

**Comment by gaearon** [comment]
The code looks fine to me.

**Comment by desmap** [comment]
Found the bug in my local version, my bad, still thanks for your quick response, closing this issue and btw Hooks and all your guys work is amazing 👍
