### ISSUE TITLE
React website bug！！！

### ISSUE THREAD

**Issue by ablikim915** [facebook/react#14663]
When i learned react at react website ，found this problem .

![image](https://user-images.githubusercontent.com/15664144/51581214-14bf7c80-1f02-11e9-9c9d-783c9017c837.png)

The interaction in this area has failed. unable to open.

url: https://react.docschina.org/docs/thinking-in-react.html

**Comment by jinrichardJIN** [comment]
I have the some of this bug

**Comment by CoolRice** [comment]
@ablikim915 , you are so funny!
you should report the issue to docschina, the site(https://react.docschina.org/) you looked is built by them.

**Comment by Mhmdrza** [comment]
This is NOT react website. React website domain is reactjs.org

**Comment by gaearon** [comment]
Sorry, we can't help with a third-party documentation fork. We plan to work on localizing our website soon.

**Comment by ablikim915** [comment]
@gaearon 
Thank you for your reminder, I have found a solution.
