### ISSUE TITLE
Need to Render 1 Lakh+ list at a time 

### ISSUE THREAD

**Issue by vnoitkumar** [facebook/react#14667]
**Need to Render 1 Lakh+ list at a time**

**When we render all the list at a time the browser is getting lagged**

We are trying to render a chart with 1 Lakh+ item in an array, where all the items in the array should display in the chart.

Is there is any best way to do it in React

**Comment by markpradhan** [comment]
Please don't use region specific amounts 😅.
I don't think many people know 1 Lakh is Hindi for 100k.

You can use: [React Virtualized](https://github.com/bvaughn/react-virtualized)
[Tutorial on medium.](https://blog.logrocket.com/rendering-large-lists-with-react-virtualized-82741907a6b3)

**Comment by threepointone** [comment]
I can't imagine which UI would need to render 1 lakh items at a go. If you do need to render a long list, consider an option like react-virtualized (suggested above), or [react-window](https://github.com/bvaughn/react-window) which is simpler, but appealing for a lot of usecases. You could also consider pagination for your view. 

Closing.
