### ISSUE TITLE
Introduce github issue managing tools 

### ISSUE THREAD

**Issue by yanglin5689446** [facebook/react#14665]
There are many open issues that haven't been referenced or replied for months (even for years),

and it seems that some of these issues have already been resolved but nobody close them.

Maybe introducing some managing tools like [probot](https://github.com/probot/probot) to automatically close these stale issues will be a good idea?

**Comment by gaearon** [comment]
We do routine cleanups every few weeks. If we don't close something it's usually because the issue is still vaguely on our radar — even if it has no immediate solution. I don't think we need to lock or auto-close them.

**Comment by aweary** [comment]
Seems we have consensus 🙂
