### ISSUE TITLE
I do plug-in development in React , I have any problem

### ISSUE THREAD

**Issue by BoomManPro** [facebook/react#14685]
i only have javascript or jquery,i want crack react;
if react code a input

<input type="text" onChange={this.handelChange.bind(this)} defaultValue={this.state.inpValu}/>

how i get through  javascript or jquery to  fill input value , and input.state.value to change

**Comment by threepointone** [comment]
you don't have to crack react, it's free to use for everyone. 

the documentation on [events](https://reactjs.org/docs/handling-events.html) and [forms](https://reactjs.org/docs/forms.html) are pretty great, but I suggest you start with the basic tutorial https://reactjs.org/tutorial/tutorial.html to first get comfortable with react. 

for further help , there are plenty of community resources and forums too https://reactjs.org/community/support.html

closing this issue.
