### ISSUE TITLE
onChange event breaking garbage collection?

### ISSUE THREAD

**Issue by leemun1** [facebook/react#14693]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Garbage collection seems to "break" when an `onChange` event is fired.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Consistent garbage collection behaviour

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Windows 10 Home Edition
Chrome Version 71.0.3578.98 (Official Build) (64-bit)
React 16.6.3

### Some context
In my application, I have some renderings of 3D models (using three.js)
Using the `onMouseMove` event on a canvas element, I calculate the current position of my mouse in terms of 3d space, and detects what models are near that position. 
I am doing this on the `onMouseMove` event attached to my `<canvas>` component. 

I also use an `<input>` component of type `range`, to change the "search radius" for objects detection. I am using the `onChange` synthetic event on this component.

Everything works fine initially, but as soon as I use the input component, thus firing the `onChange` events, the application starts to lag. I went into the performance monitor in Chrome's DevTools and recorded a performance profile, and noticed that there is something weird happening to GC behaviour before and after the `onChange` events.

### Screenshot of Chrome Devtools performance monitor
![image](https://user-images.githubusercontent.com/17537040/51691161-3f740880-1fc8-11e9-91a6-0067cd6d4304.png)

It seems like GC is working fine before the `onChange` events are fired, but once the events are fired, it changes its behaviour and does not show the "zigzag" pattern anymore. 

And this is precisely where the app starts lagging, and all function calls take much longer than before.

Can anyone help me understand what is going on here and how to resolve this issue?

Thank you in advance.

**Comment by probablyup** [comment]
Are you using `event.persist()` by any chance in your onChange handler? That will increase object allocation.

**Comment by leemun1** [comment]
@probablyup I tried both `e.persist()`, `e.propagation()`, but to no avail.

**Comment by leemun1** [comment]
Ok, so oddly enough, I tried the `react-input-range` package to replace the native JSX input element, and this behaviour is now gone. GC still continues to work in a "zigzag" pattern even after triggering the `onChange` events on the input. I do not know how the package dispatches events behind the scenes, but i suspect that there is something up with the native event system that may potentially cause GC to behave strangely.

Here is a screenshot of the performance monitor in a same scenario, but now using the `react-input-range` package:

![image](https://user-images.githubusercontent.com/17537040/51703574-b7e8c280-1fe4-11e9-85a6-ff31bf028d9e.png)

**Comment by gaearon** [comment]
1. Development or production build? Dev builds can have leaks and/or worse allocation behavior.
2. We fixed some memory issues in 16.7. Try the latest version (16.8.1) and please report the results.
