### ISSUE TITLE
ErrorBoundary does not re-render app when place below react-router

### ISSUE THREAD

**Issue by mydiemho** [facebook/react#14695]
**Do you want to request a *feature* or report a *bug*?**
a **bug**

**What is the current behavior?**
If I wrapper `Router` around `ErrorBoundary`, my app doesn't re-render until manual force refresh.  If I move `ErrorBoundary` to be above `Router` then it's fine.  Why does it behave this way?

App doesn't re-render until force refresh
```
<Router>
    <div className="app-shell">
        <ErrorBoundary>
            <Navbar />
            <div className="app-main">
                <Sidebar project={this.props.currentProject} />
                <MainContentRouter />
            </div>
            <ToastContainer />
        </ErrorBoundary>
    </div>
<Router>
```

WORKS FINE
```
<ErrorBoundary>
    <Router>
        <div className="app-shell">
            <Navbar />
            <div className="app-main">
                <Sidebar project={this.props.currentProject} />
                <MainContentRouter />
            </div>
            <ToastContainer />
        </div>
    <Router>
</ErrorBoundary>
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.7.6
OS: Mac

**Comment by gaearon** [comment]
We can't help without a reproducing sample of code.

**Comment by threepointone** [comment]
Closing this issue, happy to reopen if you can provide a reproducing example as a codesandbox link or a git repo.
