### ISSUE TITLE
Support Proxy as child

### ISSUE THREAD

**Issue by ddsol** [facebook/react#14709]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Objects are not valid as a React child

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
N/A

**What is the expected behavior?**
I'm trying to build a system that auto-detects if data is used in a React component. To do this, I detect usage during `render()` by using Proxies, which can register all access. This data, in turn, is used to prevent needless re-renders.

A parent component can pass a Proxy which represents a string, for example, to a child component, which, without knowing it is a Proxy, can use this value in a calculation (e.g. `props.value + 1` or `` `The value is ${props.value}` ``). This can be handled with `proxy[Symbol.toPrimitive]()`, which is called by JS automatically when used in this sort of expression.

However, this doesn't work if the child now passes the proxy directly to React as a child:
```jsx
  return (<span>{this.props.childValue</span>);
```
React will do a `typeof` on the child, find it is an object, and report `Objects are not valid as a React child`. Unfortunately, `typeof` cannot be spoofed with Proxy, and it will always return `'object'`.

The relevant code is found [here](https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react/src/ReactChildren.js#L189-L204). The alternative could be for React to check if there's a `child[Symbol.tpPrimitive]` and, if so, evaluate it to find the intended value, and to retry with this value as the child.
It could be as simple as inserting the following code [here](https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react/src/ReactChildren.js#L189):
```js
  if (typeof Symbol !== 'undefined') {
    const toPrimitive = children[Symbol.toPrimitive];
    if (toPrimitive) {
      const value = toPrimitive('string');
      if (typeof value !== 'object') {
		return traverseAllChildrenImpl(
		  value,
		  nameSoFar,
		  callback,
		  traverseContext,
		)
      }
    }
  }
```

It would be great if React would support this use-case. The alternative is for parent components to resolve the value, which would attribute the access to the parent component, instead of the child, where it's really being used. This in turn would cause the parent to be rerendered when only the child is being changed.

If the child is aware it may be receiving Proxy objects, it can resolve the value itself. However, the whole point of using Proxies is to automate all the refresh logic (like `shouldComponentUpdate`). Also, not needing to resolve the value would allow the value to propagate through to descendant components which may be wholly unaware of the proxy. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All version, never worked before.

**Comment by gaearon** [comment]
>Unfortunately, `typeof` cannot be spoofed with Proxy, and it will always return `'object'`.

You can trick it to think it's array though? By passing an array as the target.

I don't think we'd encourage this or even guarantee it would keep working but seems like it would unblock you.
