### ISSUE TITLE
An idea about Context

### ISSUE THREAD

**Issue by rabbitooops** [facebook/react#14702]
@gaearon 
Redesigned Context API:

> 1. Remove `<Provider value={/* ... */}>`, always use `context.write`.

> 2. New `Provider`(constructed by `useProvider`) is merely a flag which tells children they can consume `context`s that user have declared in the ancestor node.

> 3. Needn't worry about "handle multiple roots" problem.

> 4. Prevent user to nest `Provider`s with same `context`.

Examples:

```js
const themeContext = React.createContext({color: 'white'})
const userContext = React.createContext({name: ''})

setTimeout(() => {
  themeContext.write({color: 'black'})
}, 1000);

function App({defaultColor}) {
  useMemo(() => {
    themeContext.write({color: defaultColor})
  }, [defaultColor])

  const Provider = useProvider(themeContext, userContext)

  return (
    <Provider>

    </Provider>
  )
}
```

```js
const counterContext = React.createContext({
  value: 0,
  increment() {
     counterContext.write(({value, ...rest}) => ({value: value + 1, ...rest}))
  },
  doOtherThings() {
    const {value} = useContext(counterContext)
    calculation(value)
  }
})

function Counter(props) {
  const Provider = useProvider(counterContext)
  return (
    <div>
      <Provider>
        <CounterConsumer />
      </Provider>

      <ConsumeConterOutsideProvider />
    </div>
  )
}

function CounterConsumer(props) {
  const {value, increment} = useContext(counterContext)

  return (
    <div>
      <h1>value: {value}</h1>
      <button onClick={increment}>+</button>
    </div>
  )
}

function ConsumeCounterOutsideProvider(props) {
  // Throw an error, user can only use context inside provider.
  const {value, increment} = useContext(counterContext)
}
```

**Comment by markerikson** [comment]
I don't think anyone outside the React team really grasps all the nuances around context, roots, and related behavior.  I'll be honest and say that in addition, suggestions like "rewrite everything to use a Proxy" and "drop the existing APIs" really aren't helpful.

Besides, the behavior of having an inner Provider shadow the value from the outer provider is a desired aspect of context usage as far as I know.

**Comment by aralroca** [comment]
'useProvider' is explained in this great article by Dan, why is not a good idea:

https://overreacted.io/why-isnt-x-a-hook/

**Comment by gaearon** [comment]
@rabbitooops Can you describe the specific *problem* you're trying to solve?

If all you want is to avoid a nesting of several `<Provider>`s when you have multiple, you can write your own function that wraps them in a loop:

```
function Providers({ types, values, children }) {
  let el = children;
  for (let i = types.length - 1; i >= 0; i--) {
    const Provider = types.Provider[i];
    const value = values[i];
    el = <Provider value={value}>{el}</Provider>;
  }
  return el;
}

// Usage
function App() {
  return (
    <Providers types={[FooContext, BarContext]} values={[foo, bar]}>
      <Stuff />
    </Providers>
  );
}
```

I'm not saying this is a good API but I hope this helps with whatever you're trying to do!

**Comment by gaearon** [comment]
>Why react doesn't throw error when context consumer is not in its provider? Testing framework can choose to do not throw error for testing. is there any other purpose of such design?

Because many contexts can have valid "default" values as fallbacks. Such as a React Router link that never displays as active outside of a router (e.g. in tests). This also ensures type safety.

>Why can context be used many times and cover its ancestor's value? What's the purpose of this design? It's safer to hold single value for each context.

The whole point of context is that it's scoped to a subtree and overridable. For example, to implement a feature that lets you preview how another people sees your profile while being logged in as you.

If context wasn't overridable, it wouldn't be useful. You could use a module-level variable instead of it.

**Comment by rabbitooops** [comment]
@gaearon Thank you very much :) ! I have a new problem with `useContext`, it can work properly with consumer but `useContext`.
https://github.com/facebook/react/issues/14813
