### ISSUE TITLE
createDrawerNavigator doesn't show anything in react-navigation V3 react-native

### ISSUE THREAD

**Issue by bilalma** [facebook/react#14704]
import {createSwitchNavigator, createAppContainer, 
  createDrawerNavigator, createBottomTabNavigator} 
        from 'react-navigation'; 

class App extends Component {
  static navigationOptions = {
    drawerLabel: 'Home',
    // drawerIcon: ({ tintColor }) => (
    //   <Image
    //     source={require('./chats-icon.png')}
    //     style={[styles.icon, {tintColor: tintColor}]}
    //   />
    // ),
  };
            render() {
            return (
              
              <View>
              {/* <Header headerText="DISCOUNT SHAH" /> */}
              <AppContainer />
              {/* <Searching />  */}
              {/* <Routes /> */}
              </View>

);
}
}

const DashboardTabNavigator = createBottomTabNavigator({
    Deals,
    Profile
})

const AppDrawerNavigator = createDrawerNavigator({
    Dashboard: {screen: Drawer1}
});
const AppSwitchNavigator = createSwitchNavigator({
      welcome: {screen: Drawer1},
      Dashboard: {screen: Searching },
      Deals: {screen : Deals},  
});
const AppContainer = createAppContainer(AppSwitchNavigator);

export default App;

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
