### ISSUE TITLE
Unable to use useContext hook inline in Context.Provider

### ISSUE THREAD

**Issue by AlmeroSteyn** [facebook/react#14718]
**Do you want to request a *feature* or report a *bug*?**

Not sure if it is a bug or a feature yet. This relates to Hooks.

It could also be that this is all expected behaviour and one of the workarounds mentioned is required.

**What is the current behavior?**

I have a hook that depends on the `useContext` hook. Using it as follows works perfectly:

```
const MyHookedComponent = () => {
    const contextValue = useContext(DemoContext);

    return (
       //Do something with contextValue
    )
}

const MyContextProviderComponent = () => {

   return (
        <DemoContext.Provider value={someContextValue}>
                <MyHookedComponent />
         </DemoContext.Provider>
   )
}
```

What if I want to use the `getContext` hook inline in the same component that declares the `DemoContext.Provider` ?

```
const MyContextProviderComponent = () => {
       const contextValue = useContext(DemoContext); //Of course this fails due to the Context hierarchy.
   return (
        <DemoContext.Provider value={someContextValue}>
                     //Do something with contextValue
         </DemoContext.Provider>
   )
}
```

I seem to be unable to get this working.

**Please note**:
- I have a very good reason for solving my issue with Context and not passing props.
- The implementation I show above looks trivial and dumb but it is the simplest way to illustrate what the use case is. In my implementation the `Provider` sits in a complex component that does a lot of data management which I really want to happen at this level.
- The usual way to use this will be the first working version I noted above, it is only in the case where the user would want to use the hook inline inside the `Provider`.
- I have searched for a couple of hours and tried various configurations without success, so my apologies if this is a duplicate of another issue.

**What is the expected behavior?**

Any method to consume context inline in the provider using the same re-usable hook without having to revert back to render props.

I know I can solve this with **render props** but I am trying to convert an implementation using render props to hooks. I also know I can hoist the Context Provider higher up but in my implementation it would quadruple the code complexity to develop and maintain while introducing extra complexity into the user interface.

Also, by extracting the body inside the `Provider` to a new component I can also solve this but ideally I would not like to have a user do this for this use case.

**Comment by gaearon** [comment]
>What if I want to use the getContext hook inline in the same component that declares the DemoContext.Provider ?

It's not expected to work. Providers affect what's *inside* of them. This post is somewhat related to this: https://overreacted.io/why-isnt-x-a-hook/

Your proposal doesn't have a well-defined behavior. What if you render two Providers with different values inside a fragment? Which one will "win" in the parent component? The answer is neither should. Providers have a tree structure for a reason: the tree is what determines the value.

Additionally, your component already knows the value *by definition* — it's passing it down. So it doesn't need to read *context* to get that value. It already should have access to it directly.

>Also, by extracting the body inside the Provider to a new component I can also solve this but ideally I would not like to have a user do this for this use case.

This is the right solution but I'm not sure how that affects your API. What is the actual API you're trying to implement? Maybe there's another way to get it working.

**Comment by AlmeroSteyn** [comment]
Oh forgot to mention the reason I would like to not force users to extract things as components as writing forms inline can sometimes be quite a normal usecase. If I want all the accessibility and validation goodness but I am creating a form with two custom built fields, for example. 

In that case it would add the complexity of needlessly fragmenting my component.

**Comment by gaearon** [comment]
Extracting form body as a component sounds reasonable. Think of your form as a "provider" by itself.

If you absolutely need it, the form itself could provide `getInputProps` and other things it puts as Hooks as a render prop.

```js
const MyForm = () => {
    
    render () {
      <Form onSubmit=(submitData => {doSubmit(submitData)})>
          {({getInputProps}) => <input {...getInputProps()} />}
      </Form>
  }
}
```

You can detect if it's a function and either pass or not pass it.

**Comment by AlmeroSteyn** [comment]
@gaearon Thank you for taking the time. Much appreciated!!

Helps a lot to illustrate where the lines are drawn between the “old” and the new :)

**Comment by gaearon** [comment]
FWIW this is no different than classes. Context works there the same way.

**Comment by AlmeroSteyn** [comment]
@gaearon Thanks! Do you think this is worthwhile elaborating on in the docs? The `useContext` hook does not have much documentation yet. If so I would be more than happy to give it a bash.

**Comment by AlmeroSteyn** [comment]
@gaearon Awesome. PR in https://github.com/reactjs/reactjs.org/pull/1610. I kept it short 👍

**Comment by csr632** [comment]
I have created a [state management library](https://github.com/csr632/react-hook-svs) that is better at service composition. [Here is a demo of avoiding provider hell](https://codesandbox.io/s/github/csr632/react-hook-svs/tree/master/src?fontsize=14&hidenavigation=1&module=%2Fdemos%2Fcomposition.tsx&moduleview=1&theme=dark). Feel free to try it or read its source(100 lines of code)!

It introduce a "scope" object to collect the context provider, so that:
- Services can be isolated or composed, depending on whether they are in same scope.
  - Services can consume former services in same scope, despite that they are in the same component.
- All the providers collected by a scope can be provided at onece, avoiding provider hell.
- The "parent scope & child scope" structure will form a "tree" to resolve requests properly.
