### ISSUE TITLE
React works in XSLT in Chrome/Safari but errs "Unexpected token" in Firefox

### ISSUE THREAD

**Issue by colourful-land** [facebook/react#14712]
This minimum react page works in Chrome and Firefox. Let's call it `reference.html`

    <!DOCTYPE html>
    <html>
    <head>
        <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
        <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
        <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
    </head>
    <body>
    <div id="container"/>
    <script type="text/babel">
        var destination = document.querySelector("#container");
        ReactDOM.render(
            <p>Hello World</p>,
            document.querySelector("#container")
        );
    </script>
    </body>
    </html>

Now putting that to XSLT, first, prepare a dummy XML file for demonstration:

    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="experiment.xsl"?>
    <dummy/>

Then the `experiment.xsl` which mimic `reference.html`.

    <?xml version="1.0" encoding="UTF-8"?>
    <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
      <xsl:template match="/">
        <html>
        <head>
          <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
          <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
          <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
        </head>
        <body>
            <div id="container"/>
            <script type="text/babel">
              var destination = document.querySelector("#container");
              ReactDOM.render(
              <p>Hello World</p>,
              document.querySelector("#container")
              );
            </script>
        </body>
        </html>
      </xsl:template>
    </xsl:stylesheet>

The result should be identical to the single-page minimum example, and indeed it works that way in Google Chrome (v70) and Safari. But in Firefox (v64) I got:

    SyntaxError: Inline Babel script: Unexpected token (4:10)
      2 |           var destination = document.querySelector("#container");
      3 |           ReactDOM.render(
    > 4 |           ,
        |           ^
      5 |           document.querySelector("#container")
      6 |           );
      7 |         

Seems the inline HTML is simply deleted for some reason.

**Comment by ManuSevenval** [comment]
Your output after the generation contains self-closing `<script>` tags.

There are several methods how to prevent xslt from generating self-closing tags ( just search stackoverflow for the best fitting one for your needs).

An simple workaround would be (note the `xsl:comment` within the `script` tags):

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="/">
    <html>
    <head>
      <script src="https://unpkg.com/react@16/umd/react.development.js"><xsl:comment/></script>
      <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"><xsl:comment/></script>
      <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"><xsl:comment/></script>
    </head>
    <body>
        <div id="container"/>
        <script type="text/babel">
          var destination = document.querySelector("#container");
          ReactDOM.render(
          <p>Hello World</p>,
          document.querySelector("#container")
          );
        </script>
    </body>
    </html>
  </xsl:template>
</xsl:stylesheet>

```

**Comment by nhunzaker** [comment]
@ManuSevenval thanks for the suggestion (this is totally out of my expertise)! 

@colourful-land This looks like an issue specific to XSLT, not React itself. Feel free to follow up if feel there is a change required on our end.

**Comment by colourful-land** [comment]
I hope closed issues are easily Google-searchable because this knowledge is too specific. I bet a developer who hits this problem will be completely lost without this answer being indexed by Google.

**Comment by nhunzaker** [comment]
Yep! It'll be here for the next debugger :)
