### ISSUE TITLE
onChange event does not happen on input type number when typing :

### ISSUE THREAD

**Issue by hanm13** [facebook/react#14719]
- Bug Report
- Problem: Writing specific letter on input type number does not emit the onChange event.

- Reproduce : Create input type number element and listener for onChange event, than console log in the listener and when you type: e + - .
it will not emit the event.

What should happen: Typing the letters should emit the event because the input got change event..

I have this problem in the latest release and tested on Chrome Desktop in windows.

**Comment by heyimalex** [comment]
[It looks like browsers don't agree on how to handle this.](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528). I made a codesandbox [here](https://codesandbox.io/s/23z46vwkwy) to see how the native change event compares to onChange bound with react.

**Comment by gaearon** [comment]
Yeah I don't think React can do much here.
