### ISSUE TITLE
react packages listed as dependencies can't be debugged properly

### ISSUE THREAD

**Issue by BogdanZavu** [facebook/react#14728]
**Do you want to request a feature or report a bug?** Bug

**What is the current behavior?**
React packages listed as dependencies can be debugged only in transpiled code and not JSX.

**What is the expected behavior?**
You can see and debug JSX files from other react packages listed as dependencies.
I would expect webpack.config.js to configured properly in the default react app even before is ejected.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
It happens in all versions of everything.

**Comment by threepointone** [comment]
Did you mean to post this issue at https://github.com/facebook/create-react-app/issues?
