### ISSUE TITLE
Unexpected "Hooks can only be called inside the body of a function component."

### ISSUE THREAD

**Issue by tomitrescak** [facebook/react#14727]
**Do you want to request a *feature* or report a *bug*?**

Not sure

**What is the current behavior?**

Similar to #14317 

I am receiving "Unexpected "Hooks can only be called inside the body of a function component." while using locally linked packages with **pnpm**. Any advice on how to solve this?

Weird thing is that both node_modules/react point to the same symbolically linked directory.

```
lrwxr-xr-x  1 tomi  staff  59 30 Jan 19:48 app/node_modules/react -> .registry.npmjs.org/react/16.8.0-alpha.1/node_modules/react
lrwxr-xr-x  1 tomi  staff  67 30 Jan 19:48 app/node_modules/react-dom -> .registry.npmjs.org/react-dom/16.8.0-alpha.1/node_modules/react-dom

lrwxr-xr-x  1 tomi  staff  59 30 Jan 19:48 package/node_modules/react -> .registry.npmjs.org/react/16.8.0-alpha.1/node_modules/react
lrwxr-xr-x  1 tomi  staff  67 30 Jan 19:48 package/node_modules/react-dom -> .registry.npmjs.org/react-dom/16.8.0-alpha.1/node_modules/react-dom
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

The functional component from linked package should work.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.0-alpha.1 react and react-dom

**Comment by gaearon** [comment]
For one reason or another, your bundler includes the React package twice. You’ll need to figure out how that happens — we can’t help you with that.

With linking, one common solution is to *link back* from library’s React to application’s React. But I can’t say how pnpm works and whether this would help you.
