### ISSUE TITLE
create-react-app with --typescript doesn't work

### ISSUE THREAD

**Issue by ZeJ0hn** [facebook/react#14734]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When I create a new project using ```npx create-react-app project-geo-semantic-react --typescript```, the generate app in a Javascript App and not a Typescript App.
For example, the package.json doesn't contains typescript dependencies :
```
  "private": true,
  "dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-scripts": "2.1.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
```

**What is the expected behavior?**
Using --typescript parameters, a configured typescript project is generated.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I'm working on Mac OS with :
+ react@16.7.0
+ react-scripts@2.1.3
+ react-dom@16.7.0

**Comment by markerikson** [comment]
This is the React repo.  You should file CRA issues in the CRA repo, at https://github.com/facebook/create-react-app .

**Comment by ZeJ0hn** [comment]
Move the request to https://github.com/facebook/create-react-app
