### ISSUE TITLE
Suspense Fallback Doesn't Appear in DOM

### ISSUE THREAD

**Issue by kevinwainczak** [facebook/react#14742]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I would like to be able to programmatically set focus to an element inside the fallback of a Suspense component. I'm able to verify that componentDidMount fires with my current setup but I never get focus on the desired element nor does the screen reader I test with announce the "Loading..." text. I believe this is because the fallback is not appearing in the DOM (at least from what I can see in dev mode).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Below is a minimal version of my setup, although I'm not sure how to force delay the lazy loaded component in order to show the Loading fallback.
Example: https://codesandbox.io/s/qvmp1jlol6

**What is the expected behavior?**
Focus is set to the h1 tag with the loading text (and a screen reader is able to announce it, but I don't expect that to be addressed in this issue).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React/React-dom 16.7.0
This behavior was not working in IE or Chrome.

**Comment by MountainDrew** [comment]
With an `onFocus` added to your `h1`, like so `onFocus={_ => console.log('focused')}`, it does ouput correctly. Maybe this is an issue with the screenreader needing the element to be present for longer on screen. Have you tried making this element present for longer?

**Comment by kevinwainczak** [comment]
After investigating this, I discovered what my issue is. I'm not 100% that knowing this solves my problem, but here it goes:

My Suspense tags were sitting within main tags like so:
```
<header>{...}</header>
<main>
    <Suspense fallback={<Loading/>}>
        <div>
            {...lazy loaded components...}
        </div>
    </Suspense>
</main>
<footer>{...}</footer>
```
The way that React Fiber (I believe) is handling the rendering of the fallback is by placing the content below the elements under Suspense and setting the display of those other elements to none, like so:
```
<header>{...}</header>
<main>
    <Suspense fallback={<Loading/>}>
        <div {{style: display: 'none'}}>
            {...lazy loaded components...}
        </div>
        <Loading />
    </Suspense>
</main>
<footer>{...}</footer>
```
The screen reader doesn't announce the text "loading..." because it's not the first h1 element on the page. It's actually the n-teenth announceable element on the page.

Thus, I can expand the range of Suspense for my use case and wrap it around my entire application since it's a full screen loading page anyway. When the div gets marked with the display: none the screen reader will skip over reading it. Moral of this story is that if implementing a full page loading screen, you need to wrap the entire application with the suspense tags in order for a screen reader to announce it correctly.

**Comment by gaearon** [comment]
That doesn’t sound like a satisfactory solution. Let’s keep this open.

**Comment by eps1lon** [comment]
To summarize:
- [x] the fallback does appear in the DOM
- [x] the heading is focused for brief period
- [ ] the heading name is announced by screen reader

The last point does work on NVDA though: https://codesandbox.io/s/suspense-test-forked-uxprf?file=/src/index.js

From my testing it seems that NVDA debounces announcements to avoid reading things that are removed quickly. So if the fallback is only displayed briefly you won't get an announcement.

I don't think using a heading in sequential tab order that you focus is the right a11y approach for this UI pattern. gatsby did some extensive research into accessible, client-side routing that you might want to check out: https://www.gatsbyjs.com/blog/2020-02-10-accessible-client-side-routing-improvements/
