### ISSUE TITLE
React.createElement mangles array passed as props

### ISSUE THREAD

**Issue by IanKemp** [facebook/react#14743]
**Do you want to request a *feature* or report a *bug*?**

Bug. I think. Maybe.

**What is the current behavior?**

https://jsfiddle.net/oyn139b4/2/

An array passed as props gets transformed into an object, meaning that attempting to call array methods on the props in the component fails. This behaviour, and why it happens/is necessary, is not documented anywhere.

There was a warning added to this effect in [pull 6134](https://github.com/facebook/react/pull/6134) but it's gone AWOL somewhere along the line.

**What is the expected behavior?**

1. Update React to not mangle arrays of props.

-or-

1. Add an explanation as to why props cannot be a non-object to the React documentation.
2. Restore the warning added in pull 6134 to prevent people from making this mistake in the future.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Latest, all browsers/OSes, don't know.

**Comment by gaearon** [comment]
Yeah, it's not supported to have anything but plain objects as props.
