### ISSUE TITLE
useContext not triggering re-render on change

### ISSUE THREAD

**Issue by ro-savage** [facebook/react#14759]
**Do you want to request a *feature* or report a *bug*?**
Possible bug with useContext

**What is the expected behavior?**
According to the context docs (https://reactjs.org/docs/context.html#updating-context-from-a-nested-component) I should be able to pass `createContext` an object that includes a method that updates a value. The context can then be passed to components with both the value and the update function.

**What is the current behavior?**
This does not appear to work with the useContext hooks, as components with `useContext` won't automatically re-render when the value is changed from the method. I force a re-render I then see the correct values.

Codesandbox: https://codesandbox.io/s/qlz16p18n9

Simplified code: 

```js
// scoreboardContext.js
import React from "react";

export default React.createContext({
  score: 0,
  addPoints: function(points) {
    this.score += points;
  }
});
```

```js
// ScoreboardButton.jsx
import React, { useContext } from "react";

import scoreboardContext from "./scoreboardContext";

function PointButton() {
  const scoreboard = useContext(scoreboardContext);

  function updateScore() {
    scoreboard.addPoints(1);
  }

  return ( 
    <div>
      Score: {scoreboard.score}
      <button onClick={updateScore}>Add 1</button>
    </div> 
)
}

export default PointButton;
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@next

**Comment by ematipico** [comment]
In order to see the updated value, should you use the consumer component?

**Comment by dmytro-lymarenko** [comment]
Is this the right way to update the value in context?
`addPoints: function(points) {
    this.score += points;
  }`

**Comment by dmytro-lymarenko** [comment]
As you can see from here: https://reactjs.org/docs/context.html#updating-context-from-a-nested-component the value is stored in the local state of the component and the update function is the one which updates the local state. That is why the all connected nested components got rerendered.

Your way `addPoints: function(points) { this.score += points; }` is the same if you update local state in the class like this: `this.state.score += points` which will not trigger the rerender.

**Comment by dmytro-lymarenko** [comment]
And here the working variant: https://codesandbox.io/s/qlypzkx71j

**Comment by dmytro-lymarenko** [comment]
> In order to see the updated value, shouldn't you use the consumer component?

you can see the value either with Consumer of with useContext hook

**Comment by gaearon** [comment]
Mutating context value like this won't work. `createContext` value is just the _default_ one. If you want it to be change-able, you want to have a `<Provider>` in the tree, and `setState` in that component.

https://reactjs.org/docs/context.html#dynamic-context

**Comment by ro-savage** [comment]
Thanks for the details feedback and codesandbox @dmytro-lymarenko - explains it much clearer.

And thanks @gaearon - I missed that it as just the default value.

**Comment by eduardoUrbinaDev** [comment]
Hey guys, I'm hving the same situation, I did a sandbox here: https://codesandbox.io/s/wild-pine-2qonb?file=/src/components/Button.js:382-385 but when I try to put it in a real implementation won't work. 

Having compiled libs will influence the useContext mutability? In my LanguageContext.Provider, it is changing as expected, but my Text component is not re rendering. It holds to its original CreateContext.

**Comment by pitops** [comment]
@eduardoUrbinaDev  i have something similar, did u solve it?

**Comment by tsdexter** [comment]
@pitops I created a new issue here: #21030

**Comment by nupurneogi** [comment]
https://react.dev/reference/react/useContext - Anyone coming there. This is the new documentation.
