### ISSUE TITLE
The contextmenu event is propagated downwards (instead of upwards).

### ISSUE THREAD

**Issue by 71** [facebook/react#14754]
This is a **bug**.

**What is the current behavior?**
As seen [here](https://codesandbox.io/s/m5qoq1q0rj), right-clicking on a `div` fires the `contextmenu` event downwards (starting at the root, and then propagating to its children) instead of upwards (starting at the target, and propagating to its parents).

For instance,

```jsx
const message = msg => e => {
  e.preventDefault();

  alert(msg);
};

return (
  <div
    onContextMenuCapture={message("Parent context menu")}
    onClick={message("Parent click")}
    style={{ width: "2em", height: "2em", background: "blue" }}
  >
    <div
      onContextMenuCapture={message("Child context menu")}
      onClick={message("Child click")}
      style={{ width: "1em", height: "1em", background: "red" }}
    />
  </div>
);
```

renders two squares. Clicking on the smaller one will alert "Child click" then "Parent click", as expected. However, right-clicking on the smaller one will alert "Parent context menu" then "Child context menu", which is unexpected.

**What is the expected behavior?**
As in the DOM, the event should be propagated upwards.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This issue affects (at least) Chrome and Firefox with React 15 up to React 16.8.0-alpha1.

**Comment by nmain** [comment]
Working as intended.  You're listening for onClick in the bubble phase but onContextMenu in the capture phase.  If you change the native example to do the same, it matches behavior:

https://codesandbox.io/s/pkrwrnlq7q

**Comment by 71** [comment]
Huh, I somehow didn't notice this while working on my page. Thanks a lot for your answer!
