### ISSUE TITLE
react 16: componentDidMount order with children

### ISSUE THREAD

**Issue by cvlmtg** [facebook/react#14753]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

with nested components, `componentDidMount` is called first for parent and then for its children.

**What is the expected behavior?**

the parent's `componentDidMount` should be called after children's are mounted, otherwise it's impossible to e.g. calculate the parent node's height because it's still empty when `componentDidMount` is fired

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

we have an old app which used to use react 15.6.2 and that we recently update to react 16.7.0. in this app we have a list of items which can be collapsed or expanded when clicking on a button. since the update to react 16.7.0 this feature is broken because the parent height calculation is done on an empty `<div>`

the markup is simple:

```
  <div ref={this.getNode}>
    {this.props.children}
 </div>
```

when calling `componentDidMount` the `<div>` is mounted but empty, because the children have not been mounted yet, so the `<div>` height is zero. react's documentation also states "It can, however, be necessary for cases like modals and tooltips when you need to measure a DOM node before rendering something that depends on its size or position", but this is obviously impossible to do correctly if the DOM is only partially rendered...

**Comment by cvlmtg** [comment]
@TienDo1011 yup, you're right. I did more tests trying to add / remove pieces of code and it seems the cause of the wrong mount order is react-dnd. should have investigated better from the beginning... thanks for the help!

**Comment by astritspanca** [comment]
@cvlmtg component works just fine in react 16.7, propagating from children to parent.
