### ISSUE TITLE
Obviously called `useState()` inside the body of a function component. but occur like that Invariant Violation

### ISSUE THREAD

**Issue by ryota-murakami** [facebook/react#14761]
**Do you want to request a *feature* or report a *bug*?**
*bug*

## Abstract
Test Broken After update `16.7.0-alpha.2` to `16.8.0-alpha.1`
I've report for if this behavior is regression.

**What is the current behavior?**

When I upgrade react and react-dom `16.7.0-alpha.2` to `16.8.0-alpha.1`
 after that,jest test faild.
I'm mediocre developer so read again hooks docs and careful reading source thought,
I think The `useState()` Obviously called  inside the body of a function component.

**What is the expected behavior?**
Work without error.

## Resources
**・jest error log**

```
● work fine with PlainObject Store

    Invariant Violation: Hooks can only be called inside the body of a function component.

      17 | 
      18 |   // "tmpStore" role is avoid name collision "store"
    > 19 |   const [tmpStore, setState] = useState(store)
         |                                ^
      20 |   const setStore = (state: Object) => {
      21 |     if (!isPlainObject(state)) {
      22 |       throw new Error(
```

**・ souce cod file**: [Github link](https://github.com/ryota-murakami/muriatic/blob/master/src/Provider.js)

```js
// @flow // $FlowIssue flow doesn't know hook
import React, { useState, Children } from 'react'
import isPlainObject from './util/isPlainObject'
import Context from './Context'

type Props = {
  store: Object,
  children: React$Node
}

export default function Provider(props: Props) {
  const { store } = props

  if (!isPlainObject(store)) {
    throw new Error('muriatic: Expected the Store to be a PlainObject')
  }

  // "tmpStore" role is avoid name collision "store"
  const [tmpStore, setState] = useState(store)
  const setStore = (state: Object) => {
    if (!isPlainObject(state)) {
      throw new Error(
        'muriatic: Expected the setStore() argument to be a PlainObject'
      )
    }

    setState({ ...tmpStore, ...state })
  }

  return (
    <Context.Provider
      value={{
        store: tmpStore,
        setStore
      }}
    >
      {Children.only(props.children)}
    </Context.Provider>
  )
}
```

### Woring with`16.7.0-alpha.2`
- [**Circle CI info**](https://circleci.com/gh/ryota-murakami/muriatic/278?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) 
- [**commit hash**](https://github.com/ryota-murakami/muriatic/commit/46fcecccd5d976c26c65b6d6c254dd2e22bdc757)

### Faild with '6.8.0-alpha.1`
- [**Circle CI info**](https://circleci.com/gh/ryota-murakami/muriatic/284?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
- [**commit hash**](https://github.com/ryota-murakami/muriatic/commit/37b6b4629c8f64f53d9e08d6a877f2a8aa979f7b)

**Comment by Jessidhia** [comment]
That "normally" happens when the version of react doesn't match the version of react-dom or react-test-tenderer that is used. You have to make sure all packages are on the same version.

**Comment by ryota-murakami** [comment]
oh, I don't care about test-renderer.
Thank your suggestion🙇‍♂️
