### ISSUE TITLE
 why there aren't webpack.config.dev.js and webpack.config.prod.js files in the config folder?

### ISSUE THREAD

**Issue by farhadibehnam** [facebook/react#14771]
I want to use the CSS module for adding some CSS style to my component. I used "**npm run eject**" command, but in the config folder, I couldn't find webpack.config.dev.js and webpack.config.prod.js files. Of course, I'm using the latest version of reactjs.

**Comment by threepointone** [comment]
You should file this issue at the create-react-app repo https://github.com/facebook/create-react-app/issues. Closing this one.

**Comment by patel1643** [comment]
I have the same issue do we have any solutions to this?

**Comment by amiralibhatti** [comment]
I am facing the same issue. Is there any solution to this problem?

**Comment by threepointone** [comment]
> You should file this issue at the create-react-app repo https://github.com/facebook/create-react-app/issues.

**Comment by amiralibhatti** [comment]
if you have react-scripts 2 or greater version then you don't need to run eject command. You just need to add module.css in all of your CSS files and import it. After adding module.css extension (e.g App.module.css) then you will import it like "import classes from "./App.module.css"; ". you can use variable as of your choice like i have chosen "classes". Done!

**Comment by Logenleedev** [comment]
> If you are using latest version of react then you don't need to run eject command. You just need to add module.css in all of your CSS files and import it. After adding module.css extension (e.g App.module.css) then you will import it like "import classes from "./App.module.css"; ". you can use variable as of your choice like i have chosen "classes". Done!

Seems Facebook fix this for us : ) No longer have to eject first

**Comment by gaearon** [comment]
I'm going to lock this since the discussion has no relation to React. You are discussing Create React App, which is a separate project.
