### ISSUE TITLE
Docs: Formatting for code blocks nested in blockquote

### ISSUE THREAD

**Issue by rememberlenny** [facebook/react#14778]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Styling in docs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

As seen https://reactjs.org/docs/hooks-reference.html#usestate
![screen shot 2019-02-06 at 2 02 00 pm](https://user-images.githubusercontent.com/1332366/52366957-ef119780-2a18-11e9-931f-5384d49f0f6b.png)

**What is the expected behavior?**

Code blocks nested in block quotes should not have negative margin space.

Missing:
```
blockquote .gatsby-highlight {
  margin-left: 0px;
}
```

![screen shot 2019-02-06 at 2 10 41 pm](https://user-images.githubusercontent.com/1332366/52366989-018bd100-2a19-11e9-9383-38f782d9c32f.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by bvaughn** [comment]
The website has a separate repo 😄 Mind filing this over at https://github.com/reactjs/reactjs.org/pull/1086?
