### ISSUE TITLE
libraryTarget var is undefined with react version 16.8.1 react-dom 16.81.

### ISSUE THREAD

**Issue by rbmanian75** [facebook/react#14777]
Today we have upadated our react components to react version 16.8.1 react-dom 16.81. ´

our webpack config has this 

    genericConfig.output = {
        "path": path.resolve(__dirname, "../Scripts/bundles"),
        "libraryTarget": "var",
        "library": "lib[name]"
    };

after the webpack build when we try to access the global variable in our application it is shown as undefined.

this is working fine with version 16.6.0

Any help would be appreciated. Thanks

**Comment by gaearon** [comment]
Can you please provide a reproducing case?

**Comment by rbmanian75** [comment]
Yes i can.

Here is the sample project where we are getting the error.
[reactbug.zip](https://github.com/facebook/react/files/2840517/reactbug.zip)

**Comment by rbmanian75** [comment]
We now know what is the problem. When we are using react 16.6.0 the entrypoints for our application is generate as

Entrypoint FilterReact = VendorReact.js?7bd08bfd8826e3aa6f28 VendorReact.js.map?7bd08bfd8826e3aa6f28 VendorRedux.js?15e8cc4d6e2e17b01a6f VendorRedux.js.map?15e8cc4d6e2e17b01a6f FilterReact.js?ae6b0ee94612780f4e71 FilterReact.js.map?ae6b0ee94612780f4e71

Entrypoint MenuSidebarReact = VendorReact.js?7bd08bfd8826e3aa6f28 VendorReact.js.map?7bd08bfd8826e3aa6f28 GenericReact.js?9b139fdbe962e4ebe576 GenericReact.js.map?9b139fdbe962e4ebe576 MenuSidebarReact.js?05065e53c3ad0512480c MenuSidebarReact.js.map?05065e53c3ad0512480c

when we use 16.8.1 the entrypoints generated as
Entrypoint FilterReact = VendorRedux.js?15e8cc4d6e2e17b01a6f VendorRedux.js.map?15e8cc4d6e2e17b01a6f VendorReact.js?d7104037d47ee1a7c2de VendorReact.js.map?d7104037d47ee1a7c2de FilterReact.js?089748068461016bfeda FilterReact.js.map?089748068461016bfeda

Entrypoint MenuSidebarReact = VendorRedux.js?15e8cc4d6e2e17b01a6f VendorRedux.js.map?15e8cc4d6e2e17b01a6f VendorReact.js?d7104037d47ee1a7c2de VendorReact.js.map?d7104037d47ee1a7c2de GenericReact.js?9b139fdbe962e4ebe576 GenericReact.js.map?9b139fdbe962e4ebe576 MenuSidebarReact.js?b6fb91081fbc5c452b12 MenuSidebarReact.js.map?b6fb91081fbc5c452b12

you can see that with react 16.8.1 it is inlcuding all the chunks even though it is not imported in the application. for in MenuSideBarReact it is including VendorRedux.js but it is not at all used in the application. But with react 16.6.0 the chunk VendoRedux.js is not included in the entrypoint

we are getting the error undefined because we did not include the chunk bundle VendorRedux.js in our MenuSideBarReact application with version 16.81. because with 16.6.0 we dont need this.

Here is the sample application to reproduce the bundling issue.
[reactbug.zip](https://github.com/facebook/react/files/2841929/reactbug.zip)

I am not sure this is an issue with react or webpack.

Any help to solve the issue much appreciated.

Thanks

**Comment by gaearon** [comment]
Sorry, I don't think we can help much here. Nothing changed significantly on our side as far as I know so maybe this has something to do with webpack.

If you trace it down to a mistake in React packaging let us know and we can look again.
