### ISSUE TITLE
transitionLeave={false} does not properly bypass the need to have a transition leave animation

### ISSUE THREAD

**Issue by dwieme** [facebook/react#1478]
As the docs state, ReactCSSTransitionGroup keeps DOM elements on the page until an animation completes, thus necessitating a leave transition. If you want an enter animation but no leave animation, you can specify `transitionLeave={false}`. However, DOM elements still seem to stick around and occasionally throw the transitionend warning even when using `transitionLeave={false}`. (`transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition. `)

**Repro Case**
http://jsfiddle.net/kb3gN/2145/

**Steps to Reproduce**
* Click `Add All` to add three components to the page.
* Click `Remove All` to remove the added components.
    * Notice how some elements are staying on the page instead of removing all as expected
* Remove `transitionLeave={false}` from the JSX so the supplied leave transition runs
    * Removal works as expected (but with an undesired leave animation)

This occurs with both CSS transitions and with keyframe animations (change the `transitionName` from `transition-example` to `key-frame-example`).

**Workaround**
Remove `transitionLeave={false}` and use a 0sec leave transition.
*Disclaimer:* this workaround doesn't seem bullet proof. At least in my more complex view that I'm creating, doing a handful (5-10) of additions/removals (and perhaps doing it fairly rapidly) will produce the transitionend warning, leaving elements in the UI.

**Comment by appsforartists** [comment]
This seems like a pretty major bug to have idled for 9 months.  Is anyone maintaining the animation stuff?

**Comment by gaearon** [comment]
@appsforartists 

I think the big plan is to drop dependency on transitionend for animations and use JS for everything, but it's long term. @chenglou is experimenting with that:

https://github.com/chenglou/react-state-stream
https://gist.github.com/chenglou/40b75d820123a9ed53d8

**Comment by geoffreymm** [comment]
I don't know if its related with this issue or just some misconception of my part, but using **ReactCSSTransitionGroup** with **transitionLeave={false}** cause a strange behaviour when the code is running but I'm navigating in another tab.

Case code:
http://jsfiddle.net/kb3gN/10642/

To reproduce:
1. Run example, everything works fine;
2. Open another tab and wait 3 or 4 sec;
3. Return to the example, some spans didn't disappear and strange behaviour occurs;

Any idea on why is this happening?

**Comment by BinaryMuse** [comment]
@geoffreymm This is probably #1326, take a look there for some discussion/possible solutions.

**Comment by spicyj** [comment]
Partially fixed by #2549; the rest sounds like #1326.
