### ISSUE TITLE
16.8.1 bug, react refuses to unmount dom node

### ISSUE THREAD

**Issue by drcmda** [facebook/react#14781]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

React renders a node, then has to remove it, but doesn't. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The following issue has three sandboxes, one with the latest alpha in which it works, it fails in the stable release, then there's a version that spits out logs in which you can see the result it should render. The node that's still hanging in the dom should not be there.

https://github.com/react-spring/react-spring/issues/490

test sandbox: https://codesandbox.io/s/vjp41lkrrl

**What is the expected behavior?**

the node should disappear

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.0-1, it wasn't there in the latest alpha

**Comment by brunolemos** [comment]
Yep facing this as well.

I noticed the dom does get removed, but only in the next render phase: https://codesandbox.io/s/o5vn7z0l66

![gif](https://user-images.githubusercontent.com/619186/52377843-30bc3580-2a4d-11e9-9a6b-73d6401834e5.gif)

**Comment by drcmda** [comment]
Just to make sure i removed the <animated.div part and let it render out just the divs, it's the same. The last render result is [false], and React renders a <div />.

**Comment by drcmda** [comment]
That solves it!
