### ISSUE TITLE
react-cache alphas don't work with 16.8+

### ISSUE THREAD

**Issue by subtleGradient** [facebook/react#14780]
> `react-cache` was not published with 16.8.1 like the rest of the react packages.
This means that the platform's Suspense stuff will not work.

_Originally posted by @jaredpalmer in https://github.com/palmerhq/the-platform/pull/70#issuecomment-461170282_

**Comment by jaredpalmer** [comment]
This can be closed. 

We are building react-cache from master and using a vendor folder in the example of the-platform. Previously it was improperly included as dependency instead of a peer dependency in the-platform.

**Comment by gaearon** [comment]
Yeah I think for now our recommendation is that you can copy paste its source but then you're on your own. The caching strategy is very unclear now and the whole thing will likely change a lot. We don't want any reusable libraries to start depending on it.

We could plausibly add a big red warning on its import and then publish another alpha. If someone sends a PR seems ok to do it.

**Comment by SigmundurMorkore** [comment]
I'd like to try to add a warning on import, it would be my first contribution. However, I'm having difficulity with the readContext function. Dispatcher is equal to null, and I'm getting the corresponding error:
`Error: react-cache: read and preload may only be called from within a component's render. They are not supported in event handlers or lifecycle methods.`

but I'm not calling read from an event handler or a lifecycle method, as seen below

```jsx
const AdvertisementsFetcher = createResource(() =>
  fetch('/.netlify/functions/getAdvertisements?kind=Banner').then(res =>
    res.json(),
  ),
)

function ADBanner() {
  const advertisements = AdvertisementsFetcher.read()
  const [advertisement, setAdvertisement] = useState(
    () => advertisements[Math.floor(Math.random() * advertisements.length)],
  )
  const { category } = useContext(WebpagesContext)

  useEffect(() => {
    setAdvertisement(
      advertisements[Math.floor(Math.random() * advertisements.length)],
    )
  }, [category])

  const image = advertisement.image[0]
  return (
    <Wrapper href={advertisement.link}>
      <img
        src={image.url}
        alt={`${advertisement.name} Banner Advertisement`}
      />
    </Wrapper>
  )
}
```

**Comment by bitttttten** [comment]
How are we able to experiment with react-cache and Concurrent Mode at the moment? Since I am running into this issue with the versions below 😅 

```
"react": "16.8.0-alpha.1",
"react-cache": "2.0.0-alpha.1",
"react-dom": "16.8.0-alpha.1",
```

**Comment by MuYunyun** [comment]
@bitttttten This is [Suspense demo](https://github.com/demos-platform/suspenseDemo) run in react "16.8" version. You can try suspense demo in the branch [use-suepense](https://github.com/demos-platform/suspenseDemo/tree/feature/use-suspense). Hope help you.

**Comment by gaearon** [comment]
If you want to experiment you should be able to build from source. :-)

**Comment by psychobolt** [comment]
Seems like building it from source is the only way for now.

**Comment by andykais** [comment]
The current solution is indeed building from source, but if people want to streamline the process, you can try adding this to your package.json:
```
  "scripts": {
    "postinstall": "git clone git@github.com:facebook/react.git --depth=1 && cd react && yarn install --frozen-lockfile && npm run build react-cache && cd .. && npm i $(npm pack ./react/build/node_modules/react-cache) && rm -rf react"
  },
```

credit goes to this [stackoverflow answer](https://stackoverflow.com/a/39195334/3795137)

It would be awesome if react took advantage of the [npm's "prepare" script](https://blog.jim-nielsen.com/2018/installing-and-building-an-npm-package-from-github/)  _and_ [npm allowed installing from directories in git repos](https://github.com/npm/npm/issues/2974), but thats not likely going to change any time soon. For now, this solution is fine
