### ISSUE TITLE
useEffect with window.scroll(0,0) seems to take effect after initial render

### ISSUE THREAD

**Issue by andreidobrinski** [facebook/react#14784]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

A quick snapping behaviour when combining `useEffect` with a `window.scroll(0,0)` in a React Router link. Seems like the user gets a glimpse of the pre-`window.scroll(0,0)` render before the window gets scrolled.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Here's the CodeSandbox [link](https://codesandbox.io/s/4qnzvyjn84)

I've mocked the demo up to use both the `componentDidMount` method as well as the `useEffect` method to show it side-by-side. It seems like `componentDidMount` didn't have the issue that `useEffect` does.

The repro steps are:
- Start with create-react-app and react-router
- Creates some routes and links to other components, add content
- Add a `useEffect` with a `window.scroll(0,0)` as the effect
- Navigate app

Note about the CodeSandbox: sometimes the back button doesn't register after the first Link is clicked, having to manually return the path back to `"/"`. 

**What is the expected behavior?**

The window scrolls to the top before any content is rendered.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8

I'm able to reproduce the issue in Chromium-based browsers (Chrome and Brave), as well as Firefox. Safari seems to be unaffected. All testing happened on macOS High Sierra 10.13.6.

**Comment by Penspinner** [comment]
I believe this is the expect behavior. You have to use `useLayoutEffect` so that the effects run synchronously before React commits to the screen.

**Comment by andreidobrinski** [comment]
Thanks for letting me know, that did the trick. Closing the issue.
