### ISSUE TITLE
Inconsistent state behaviour on render method

### ISSUE THREAD

**Issue by degun** [facebook/react#14789]
**Do you want to request a *feature* or report a *bug*?**

Possible bug.

**What is the current behavior?**

I am attempting to "lift state up", by taking a string from a component and passing it to the parent component. 
This is done by a function fired on the onSubmit event on a form in the child.
The value gets passed using the child's props to the parent, and then to the parent's state using this.setState().
The problem is that the state's property that I just updated is initially an array containing the string I pushed, which is OK, but then, on the parent's render() method, when I attempt to get this.state.nameOfTheArray, I get its length instead. I have reproduced the issue on a very minimal JSfiddle which I'll link below. By clicking the button you can view the issue in the console.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/degun/wbcv3zq1/2/

**What is the expected behavior?**

In the render() method I should get the new array with the passed value.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am using React 16.8.0. I tested the code on Firefox 65 and Chrome 71.0.3578.98 (Official Build) (64-bit) on a machine using Windows 10 64-bit.

**Comment by hamlim** [comment]
This doesn't seem to be an issue with React, but rather an issue with the setState implementation your container component is using:

```js
this.setState({
  artikujt: this.state.artikujt.push(art)
});
```

`this.state.artikujt` is an array initially, however on the first update you set `artikujt` to the result of calling `push` on that array. `.push` unfortunately does not return a new array with the elements you are inserting into the array, but rather the inserted element:

```js
const array = [];
const result = array.push(1);
// result === 1
```

Instead what you can do is use `.concat` or, if you support ES2015 features, you can use an array spread syntax:

```js
const newArray = oldArray.concat(newItem);
// or const newArray = [ ...oldArray, newItem ];
```

Updating your container to look like:

```js
shto(art){
  this.setState({
    artikujt: this.state.artikujt.concat(art)
  }, console.log(this.state.artikujt))
}
```

**Comment by degun** [comment]
I see. Such a silly question. Thank you.
However, the confusing part is that the state initially has that last item in the array, but I guess React changes that at a later time.
Thanks again!
