### ISSUE TITLE
Shadow DOM for React components

### ISSUE THREAD

**Issue by o-t-w** [facebook/react#14798]
For those of us who would like style encapsulation without wanting to adopt web components as a whole (e.g. not using custom elements), it would be nice if it was easier to use shadow DOM for a React component. 

Both Angular and Stencil offer relatively simple and nice API's for utilising the style encapsulation of shadow DOM. 

Microsoft Edge announced that it was working on shadow DOM a while ago, and is now switching to Chromium, so will support shadow DOM once the Chromium-based version of Edge is released. Safari/Chrome/Opera/Firefox already support it.

**Comment by threepointone** [comment]
there are userland solutions for this, eg - https://github.com/treshugart/react-shade. I don't think it's something react needs to natively host for now. people also use css-modules, or one of many flavours of css-in-js to get the same benefits purported by shadow dom for css. 

closing this issue.
