### ISSUE TITLE
useAsyncReducer / useAsyncDispatcher

### ISSUE THREAD

**Issue by timlind** [facebook/react#14795]
**Do you want to request a *feature* or report a *bug*?**

 Feature + Bug. Proposal for built in useAsyncReducer / useAsyncDispatcher.

**What is the current behavior?**

useReducer doesn't allow async dispatching predictably.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/yzvv9qko9

Async dispatch works first time but doesn't fire on subsequent clicks.

**What is the expected behavior?**

Calling dispatch should fire exactly once when called asynchronously.

This would be the same as what works well with useState, when a function calls setState asynchronously: 

`function load() {
        restService.getAll("api/users").then(() => setState(users));
}`

useAsyncReducer could look as follows, as is likely more performant than binding dispatch on each render: 
```
function useAsyncReducer(reduce, initialState, init) {
  var [state, dispatch] = useReducer(reducer, initialState, init);

  function reducer(state, action) {
    return reduce(state, { ...action, dispatch });
  }

  return [state, dispatch];
}
```

useAsyncDispatcher could look as follows:
```
export function useAsyncDispatcher(reducer, initialState, init) {
    var [state, _dispatch] = useReducer(reducer, initialState, init);

    function dispatch(action) {
        if (typeof action === 'function') {
            action(dispatch);
        } else {
            _dispatch(action);
        }
    }

    return [
        state,
        dispatch
    ];
}
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.0
<img width="557" alt="screen shot 2019-02-08 at 04 32 27" src="https://user-images.githubusercontent.com/237741/52455793-94805480-2b5a-11e9-839e-f2eedfe6aae3.png">

**Comment by timlind** [comment]
Closing in father of the pattern I issued on react website repo: https://github.com/reactjs/reactjs.org/issues/1652

**Comment by brookslybrand** [comment]
From this Stackoverflow answer: https://stackoverflow.com/questions/36730793/can-i-dispatch-an-action-in-reducer

> Dispatching an action within a reducer is an anti-pattern. Your reducer should be without side effects, simply digesting the action payload and returning a new state object. Adding listeners and dispatching actions within the reducer can lead to chained actions and other side effects.

What you're trying to do is considered bad practice. Reducers shouldn't emit side effects. Just move `setTimeout(() => dispatch({ type: "afterclick" }), 2000);` into the `click` function and this will work fine.

**Comment by timlind** [comment]
Thanks @brookslybrand I was looking for something with more separation of concerns than to embed it there, something like redux-thunk which is dispatched from action creators. All sorted now :)
