### ISSUE TITLE
Module mock yields unexpected act() error

### ISSUE THREAD

**Issue by alexjoyner** [facebook/react#14797]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I am trying to figure out where is the best place to put a module mock according to the new react version 16.8.1.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
``` javascript
import React from 'react';
import { act } from 'react-dom/test-utils';
import { mount } from 'enzyme';
import { getPointsFromGroupID } from './utils/getPointsFromGroupID';
import { TDashBody } from '.';

jest.mock('./utils/getPointsFromGroupID', () => ({
  getPointsFromGroupID: jest.fn(() => Promise.resolve({})),
}));

const getDefaultProps = () => ({
  currentGroup: 0,
});
describe('DashBody', () => {
  let component;
  beforeEach(() => {
    act(() => {
      const props = getDefaultProps();
      component = mount(<TDashBody {...props} />);
    });
  });
  describe('rendering', () => {
    it('Should render without exploding', () => {
      expect(component).toBeDefined();
    });
  });
});
```

**What is the expected behavior?**
This test passes, but the placement of the mock module call gives me the act() error
```
Warning: An update to TDashBody inside a test was not wrapped in act(...).

      When testing, code that causes React state updates should be wrapped into act(...):

      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */

      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb

.me/react-wrap-tests-with-act
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v16.8.1 running chrome on windows 10

**Comment by alexjoyner** [comment]
Im working on making a codesandbox to simulate the issue now

**Comment by alexjoyner** [comment]
If it helps, this is where I'm at right now with a sandbox.  The sandbox is giving a different error of jest is not defined, but it's close to what I have in my code.  [Code Sandbox](https://codesandbox.io/s/jzv3k9jw4w)

**Comment by threepointone** [comment]
consider the recommendations at https://github.com/facebook/react/issues/14769#issuecomment-462528230 those may help for now

**Comment by alexjoyner** [comment]
I tried several different configurations, but nothing from that comment has worked so far as a temporary solution.  I've seen from other issues that this seems to be rooted in a known issue.  How far out is a patch update?  I'd rather switch to something else in the meantime until a more robust solution gets released if it's likely to be next week or later.

**Comment by threepointone** [comment]
we just released an alpha version with the new async version of act. I took your sample, downloaded it locally (to actually see the error) and fixed it to pass the tests https://codesandbox.io/s/103lmw1pr4

**Comment by threepointone** [comment]
closing this issue, feel free to reopen if you're still having issues. we'll have further docs and an explainer soon.
