### ISSUE TITLE
Missing assets for releases 16.7, 16.8, 16.8.1

### ISSUE THREAD

**Issue by DavideDaniel** [facebook/react#14806]
**Do you want to request a *feature* or report a *bug*?**
Publishing mistake or bug with script? Unsure.

**What is the current behavior?**
The releases for 16.7, 16.8, 16.8.1 don't have any assets listed. When fetching remotely via automated build scripts, we're not getting anything past 16.6.1 from the assets array via github release apis.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Visible by referencing the json returned from https://api.github.com/repos/facebook/react/releases

**What is the expected behavior?**
Releases should have assets or should not in documentation that they won't if it's intentional.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6.3 was the last one with assets.

**Comment by bvaughn** [comment]
This was an oversight on my part. Our release script doesn't mention this in the post-publish instructions because I didn't know it was part of our process. I'll adjust the script this coming week when I'm back at work.

In the meanwhile, any one of us could snag the packages from NPM and attach them to a release.

**Comment by sophiebits** [comment]
@DavideDaniel Separately from fixing this, I'll say that the most reliable way to get these assets is to pull them from npm. That is the "source of truth" for our official releases.

**Comment by bvaughn** [comment]
Agreed with Sophie.

As an alternative to using NPM (directly) you could also fetch the assets from unpkg.com (add a "?meta" param to generate a list of files in the package– e.g. https://unpkg.com/react@16.8.1/?meta).

**Comment by DavideDaniel** [comment]
Right.. I think the issue was that we use github api to pull releases through a cron job, and this popped up when a team noticed that their versions of react were not updating past a certain point. We'll look at leveraging npm if we can, however, just something that could be automated into the release scripts possibly.

**Comment by bvaughn** [comment]
> however, just something that could be automated into the release scripts possibly.

Even though the [GitHub API seems to support automated release creation](https://developer.github.com/v3/repos/releases/#create-a-release)– I don't think it's something we would want to automate with the release script. It requires a changelog that we're pretty careful about reviewing to ensure a high quality. I don't think the effort of adding this to the script is worth it.

I'll try to make the messaging/prompt more meaningful so we don't forget to do this in the future, but we don't really intend for people to consume releases from GitHub– only NPM.

**Comment by DavideDaniel** [comment]
That's good to know. Will circulate this at work. =)

**Comment by bvaughn** [comment]
Release script messaging changes made in PR #14863

**Comment by bvaughn** [comment]
The past four releases correspond to the following packages and versions:

**16.8.2** - 2019-02-14
* create-subscription@16.8.2
* eslint-plugin-react-hooks@1.0.2
* jest-react@0.6.2
* react@16.8.2
* react-art@16.8.2
* react-dom@16.8.2
* react-ism@16.8.2
* react-reconciler@0.20.0
* react-test-renderer@16.8.2
* scheduler@0.13.2

**16.8.1** - 2019-02-06
* create-subscription@16.8.1
* eslint-plugin-react-hooks@1.0.1
* jest-react@0.6.1
* react@16.8.1
* react-art@16.8.1
* react-dom@16.8.1
* react-is@16.8.1
* react-reconciler@0.19.1
* react-test-renderer@16.8.1
* scheduler@0.13.1

**16.8.0**  - 2019-02-06
* create-subscription@16.8.0
* eslint-plugin-react-hooks@1.0.0
* jest-react@0.6.0
* react@16.8.0
* react-art@16.8.0
* react-dom@16.8.0
* react-is@16.8.0
* react-reconciler@0.19.0
* react-test-renderer@16.8.0
* scheduler@0.13.0

**16.7.0** - 2018-12-20
* create-subscription@16.7.0
* jest-react@0.5.0
* react@16.7.0
* react-art@16.7.0
* react-dom@16.7.0
* react-is@16.7.0
* react-reconciler@0.18.0
* react-test-renderer@16.7.0
* scheduler@0.12.0

**Comment by bvaughn** [comment]
I've updated the past releases to point to the UMD artifacts in UNPKG.

Going to close this for now~
