### ISSUE TITLE
highlight immutable objects in profiler when going commit by commit

### ISSUE THREAD

**Issue by dadamssg** [facebook/react#14803]
**Do you want to request a *feature* or report a *bug*?**
both?

**What is the current behavior?**
In the react profiler, going commit by commit only highlights native js values. When using immutable(`Map`, `List`, etc) these prop/state values do not get the flash of highlight when going to the next commit.

I put together this codesandbox but the profiler doesn't pick the embedded react app up though. You can get the idea though. 
https://codesandbox.io/s/k3op914q8r

**What is the expected behavior?**
I would expect that both `bar` and `test` to get the flash when going to the next commit. Currently only `bar` gets the flash.

![image](https://user-images.githubusercontent.com/881986/52510814-2a4fca00-2bc3-11e9-8a8d-d818ff650b11.png)

It would also be nice to be able to right click and log that value to the console. Even if it did flash, there's currently no way to inspect the changes within the immutable data structure. That may be out of the scope of the profiler though.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.1

**Comment by gaearon** [comment]
Please file this in https://github.com/facebook/react-devtools instead. Thanks!
