### ISSUE TITLE
Warning for useContext second argument confusing for library users

### ISSUE THREAD

**Issue by benwiley4000** [facebook/react#14815]
**Do you want to request a *feature* or report a *bug*?**

Not exactly a bug, but a confusing error message.

**What is the current behavior?**

When the second argument is passed to `useContext` (`unstable_observedBits`), we get a [warning message informing that this second argument is unsupported](https://github.com/facebook/react/pull/14729). Yet this argument ***is*** used by third-party libraries, relied upon by React users.

So these users will wind up seeing this warning and not really have any power to do anything about it (for instance, [here](https://github.com/dai-shi/react-hooks-global-state/issues/5)).

If the intention is that `unstable_observedBits` should ***not*** be used by library authors, I'd appreciate some clear communication on what the alternative API will be.

`unstable_observedBits` now has moderate adoption among third party libraries for the `Context.Consumer` variant and my expectation would be that a parallel API is supported for `useContext`, at least to the minimal extent that downstream users aren't receiving non-actionable error messages.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8+.

**Comment by gaearon** [comment]
Currently it's too easy to accidentally pass it (`[A, B].map(useContext)`) which is why we warn. It's indeed not officially supported.

If a library is comfortable with us potentially removing it in the future, it can call `readContext()` on the dispatcher directly. (You can see how to do it from the `React.useContext` implementation.) In that case it explicitly depends on something internal that can break. Alternatively, it may choose not to use an unstable feature.

Hope that helps.

**Comment by benwiley4000** [comment]
Thanks! This is helpful info.

**Comment by bholloway** [comment]
To avoid the logs I have been using something like this, with plenty of unit tests to detect when it breaks in the future.

```javascript
import React, {
  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED as ReactInternals,
  type Context,
} from 'react';

// this works exactly the same as `useContext()` but doesn't log error
// @see https://github.com/facebook/react/issues/14815#issuecomment-462194923
const useContext = <T>(context: Context<T>  observedBits: undefined | number) =>
    ReactInternals.ReactCurrentDispatcher.current.readContext<T>(
        context,
        observedBits,
    );
```

Not sure if there is an easier way.
