### ISSUE TITLE
Cannot useContext but context.Consumer

### ISSUE THREAD

**Issue by rabbitooops** [facebook/react#14813]
Click here: https://codesandbox.io/s/pwozvvrr87
**Do you want to request a *feature* or report a *bug*?**
Not sure.

**What is the current behavior?**
Work properly with `context.Consumer` but `useContext`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
react 16.8.1 react-dom 16.8.1

**Comment by gaearon** [comment]
`useContext` only accepts React context object as an argument. You are passing some custom object created here: https://unpkg.com/rako-react@0.6.0/src/createStoreContexts.js. This is not expected to work.

**Comment by rabbitooops** [comment]
But i pass all object to it.

**Comment by gaearon** [comment]
I'm just saying this isn't _expected_ to work. To dig deeper why it doesn't work in your particular case I'd need to see an example that has no third-party libraries — just a sandbox that's easy to inspect in full.

**Comment by rabbitooops** [comment]
I will send you tomorrow because it's so late here, good night :) thank you.

**Comment by rabbitooops** [comment]
https://codesandbox.io/s/3q3k2y3z55
well... seems react forbids any custom object even `Object.assign({}, context)`.
