### ISSUE TITLE
Losing state and dispatch when passed to provider, with Typescript

### ISSUE THREAD

**Issue by bauervision** [facebook/react#14818]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When passing initialState through useReducer, and attaching [state, dispatch] to value of the Provider, both objects come out missing on the other side when I try to access them. Note: I'm only adding in my Typescript as well so you can see the whole picture in case something stands out. This issue exists with or without TS.

Here's how I'm setting it all up:

```ts
export interface IState {
  isAuth: boolean;
  user: string;
};

export const initialState: IState = {
  isAuth: true,
  user: "Mike"
};

type ContextProps = {
  isAuth: boolean;
  user: string;
};

export const AdminStore = React.createContext<ContextProps>(initialState);
```

Now the reducer setup

```ts
interface ILogout {
  type: "LOGOUT";
  value: boolean;
}

interface ILogin {
  type: "LOGIN";
  value: boolean;
}
type Actions = ILogin | ILogout;

export const reducer = (state: IState, action: Actions) => {
  switch (action.type) {
    case "LOGOUT":
      return { ...state, isAuth: false, user: "No one" };
    case "LOGIN":
      return { ...state, isAuth: true, user: "Mike" };
  }
};
```

Now set it all to the provider

```ts
export function AdminStoreProvider(props: any) {
const [state, dispatch] = useReducer(reducer, initialState);
// state.isAuth is avail here
// state.user is avail here
const value = { state, dispatch };
// value.state.isAuth is avail here
return (
    /* value does not contain state once applied to the value prop */
    <AdminStore.Provider value={value}>{props.children} 
    </AdminStore.Provider>
   );
}
```
Therefore when I try to access them...

```ts
const AuthApp = () => {
/* Property 'state' does not exist on type ContextProps */
  const { state, dispatch } = useContext(AdminStore);
  return <App auth={state.isAuth} />;
};
```

I've tried altering how I create the context object, and it doesn't seem to matter:

```ts
export const AdminStore = React.createContext<ContextProps>(initialState);
//or
export const AdminStore = React.createContext<ContextProps>();
// or
export const AdminStore = React.createContext<ContextProps>( {} );
```

All 3 result in the same loss of data when I pass it to the Provider

I've also added state and dispatch to ContextProps which then results in those values not being present based on how I createContext(), plus I don't think I should have to add them to my interface.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

The easiest way to reproduce the error is to download this sandbox
https://codesandbox.io/s/7jk69315l0

You can see that it works there, but not once you download it and run it locally. I tried to run it on two different machines, and I have the same error on both. It loses state and dispatch when passed through the provider.

**What is the expected behavior?**
https://codesandbox.io/s/7jk69315l0

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Using Win 10, this wasn't avail in previous versions of React
```
"react": "^16.8.1",
"react-dom": "^16.8.1",
"react-icons": "^3.3.0",
"react-router-dom": "^4.3.1",
"reactstrap": "^7.1.0"
```

**Comment by gaearon** [comment]
I don't understand whether you're reporting a *typing* issue or a runtime issue.

The typings definitely look wrong because your context type is `{ isAuth, user }` but then you pass `{ dispatch, state: { isAuth, user } }` down. Can you start by fixing this discrepancy?

>You can see that it works there, but not once you download it and run it locally.

If you think there is a runtime bug in React please create a version of this that doesn't use TypeScript.

**Comment by bauervision** [comment]
I'm not sure what is going on with it.
Here is my latest, which actually compiles finally, thanks to your suggestion. 
[https://codesandbox.io/s/7jk69315l0](url)

Once I imported Dispatch from react, and then my Actions, errors went away.
`
interface IContextProps {
  state: IState;
  dispatch: Dispatch<Actions>;
}`

However, now it crashes in the browser saying that Object is not a function, on this:

`export function AdminStoreProvider(props: any) {
  const [state, dispatch] = useReducer(reducer, initialState);

  const value = { state, dispatch };
  return (
    <AdminStore.Provider value={value}>{props.children}</AdminStore.Provider>
  );
}`

**Comment by gaearon** [comment]
I don't see any crashes in your link.

**Comment by bauervision** [comment]
That's been my problem. It runs perfectly in sandbox, but not on my machine locally. Literally copy paste from one place to the other, and 2 different results.

**Comment by gaearon** [comment]
Can you prepare a local example that doesn't involve TypeScript?

**Comment by bauervision** [comment]
Ok so removing TS seems to have fixed it. Sucks because I need to use it. Any suggestions?

**Comment by gaearon** [comment]
Please file an issue with TypeScript if it breaks your valid code.

**Comment by StudioSpindle** [comment]
@bauervision Have you filed an issue with Typescript? If so, could you share the link?

**Comment by bauervision** [comment]
No I haven't. My work has moved away from TS

**Comment by BruceSuperProgramer** [comment]
Check if you have this warning "Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle." 

 ```
onItemSelected={(item) => {
            if (observationFilter) {
              const { dispatch } = observationFilter;
              dispatch({ type: REDUCER_TYPES.SET_ISSUE_STATUS, payload: item }); //Causing crash when I open the app metro compiling the project
            }
          }}
```
The dispatch was getting from context provider, it is a React.useReducer dispatch.

After fix module cycle warning I am able to run project again.
