### ISSUE TITLE
XSS is doubly escaping when using SSR and `ReactDOM.hydrate`

### ISSUE THREAD

**Issue by akoumjian** [facebook/react#14822]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I'd like to preface this by saying I have read all of the existing documentation on XSS and methods to avoid strings being escaped. The behavior here cannot be adequately addressed with the current suggestions.

HTML that is escaped in SSR using `ReactDOMServer.renderToString` are escaped a second time on the client using `ReactDOM.hydrate`. This results in entities like `&` being displayed as `&amp;` after being escaped once on the server and a second time on the client.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Have a component that renders a string containing `&`, such as inside a span or p.
2. Render the page using ReactDOMServer in node.js, and then use `ReactDOM.hydrate` on the client. Do NOT do anything that will trigger a re-render of the page.
3. See that the ampersand has been doubly escaped and appears to the user like `&amp;`.

Difficult to set up a live example with SSR. I am happy to send a private link to a live site that is experiencing the issue.

**What is the expected behavior?**
Ideally I would expect the `ReactDOM.hydrate` method to detect when entities like `&` are already escape and not do it again.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.7.0
OS: OSX Chrome

**Comment by akoumjian** [comment]
I'll follow this up by mentioning that even if you are not doing SSR, React is going to doubly escape any string that's already been entity escaped. If your API or data source is providing values such as `"Borgin &amp; Burkes"`, React will always turn this into `"Borgin &amp;amp; Burkes". Other sanitizing libraries appear to be smart enough to not doubly escape strings. For example:

```
In [5]: bleach.clean(bleach.clean("Borgin & Burkes"))
Out[5]: 'Borgin &amp; Burkes'
```

**Comment by nmain** [comment]
>Difficult to set up a live example with SSR.

Try something like this https://jsfiddle.net/aqgj6eus/

**Comment by akoumjian** [comment]
I'm going to close this. Looks like it might be due to a mismatch between server and client tree.

**Comment by speed-oss** [comment]
Added Speed Bounty!

**Comment by speed-oss** [comment]
Added Speed Bounty!
