### ISSUE TITLE
`eslint-plugin-react-hooks` Appears to allow for usage of hooks outside of components

### ISSUE THREAD

**Issue by tylucaskelley** [facebook/react#14824]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

No error is given by the linter when hooks are used outside of a component or custom hook function.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Example here: https://codesandbox.io/s/l95pxv9k9l

Would expect an error from line 3 since `useState` was called outside of a component or hook function.

**What is the expected behavior?**

I would expect an error message along the lines of `React Hook "useTranslation" is called outside of a React function component or a custom React Hook function`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8

**Comment by brookslybrand** [comment]
When I ran your code it came up with the violation. I'm not sure what you're experiencing, but based on your description React seems to be doing what you want it to do.

![image](https://user-images.githubusercontent.com/12396812/52662068-0e04a380-2ec9-11e9-85fd-5c3c148d5cdb.png)

**Comment by tylucaskelley** [comment]
Ah sorry if I was unclear - I was expecting the linter to catch this I guess in addition to an error being thrown. I can close this issue!
