### ISSUE TITLE
Hooks FAQ: possibly broken optimization

### ISSUE THREAD

**Issue by hnordt** [facebook/react#14828]
In https://reactjs.org/docs/hooks-faq.html#how-to-read-an-often-changing-value-from-usecallback we have the following snippet:

```js
function Form() {
  const [text, updateText] = useState('');
  const handleSubmit = useEventCallback(() => {
    alert(text);
  }, [text]);

  // ...
}

function useEventCallback(fn, dependencies) {
  const ref = useRef(() => {
    throw new Error('Cannot call an event handler while rendering.');
  });

  useLayoutEffect(() => {
    ref.current = fn;
  }, [fn, ...dependencies]);

  return useCallback(() => {
    const fn = ref.current;
    return fn();
  }, [ref]);
}
```

I think `[fn, ...dependencies]` should be just `dependencies` cause `fn` is an inline function in the parent and will break the `useLayoutEffect` optimization. Am I wrong?

**Comment by gaearon** [comment]
That optimization isn't actually meaningful, we should probably just remove it. It isn't important in the grand scheme of things.

**Comment by gaearon** [comment]
I'll close since the report is incorrect
