### ISSUE TITLE
Reconciliation not occurring between two separate re-renders

### ISSUE THREAD

**Issue by afreix** [facebook/react#14825]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A second parent re-render occurs before an unmounted child element is removed from the DOM.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I'm having trouble with a smaller example since the bug I'm observing involves react (16.5.2), redux (3.5.2), and react-redux (5.0.6), and react-router (4.4.0-beta.6). Before investing any more time in creating a isolated reproduction, I'd like to confirm that what I'm seeing is in fact unexpected behavior. 

Initial tree structure:
```
<Parent>
   <Folder label='A'>
      <Child id={1}/>
   </ Folder>
   <Folder label='B'>
      <Child id={2}/>
      <Child id={3}/>
   </ Folder>
</Parent>
```

There is a flow similar to this occurring:
* Current URL ```/item/{id}```, say for this example ```/item/3```
* Redux action fired to delete item 3
* We navigate via ReactRouter to the home page URL ```/home``` (this should be batched with the Redux action above since it is within a click handler)
* A ```<Redirect />``` component is rendered at ```/home``` which redirects to ```/item/1```

I've placed debugger points within the ```render``` function of ```<Parent/>, <Folder/>, and <Child/>```. Once the delete action is fired, the break point within ```<Parent/>``` is hit. Subsequently, we hit the breakpoints in ```<Folder/>``` and ```<Child />```. As expected ```<Folder label='B'>``` only renders one child component, ```<Child id={2}/>```, and ```componentWillUnmount``` is called within ```<Child id={3} />```. Then after we are redirected to ```/item/1``` a second re-render of ```<Parent/>``` occurs. At this point, we've had a full render cycle, ```componentWillUnmount``` has been called, and yet ```<Child id={3} />``` is still visible in the DOM and within the React component tree within React dev tools.

**What is the expected behavior?**
The child element (```<Child id={3} />```) is removed from the DOM before a second re-render occurs.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.5.2
All browsers
Windows OS
Unsure which version of React caused this issue because the code making it apparent was newly added in React 16.5.2

**Comment by gaearon** [comment]
I find it pretty difficult to wrap my mind around this description. A purely React example would of course help a lot.

**Comment by afreix** [comment]
Is there anything I could clarify in the explanation? Would a gif be helpful? I'm not sure I'll be able to produce a purely React example.

Is it true that if a parent component re-renders causing a child component to fire ```componentWillUnmount``` that it should be unmounted from the DOM before its parent render method is called a second time?

**Comment by gaearon** [comment]
That sounds like a reasonable expectation.

**Comment by afreix** [comment]
I'm not seeing this behavior anymore after updating to React 16.8. Some small changes to our codebase also occurred, so I can't be sure what actually fixed the problem
