### ISSUE TITLE
React Hooks

### ISSUE THREAD

**Issue by vidhyeshpatil** [facebook/react#14833]
As I am using React from last 2 years. I think React Hooks would be major change, if it keeps the spirit of React & it's methods. It would definitely give the benefits, state management library would be less in use. I think with React Hooks we can simplify & modify the context props as well, for the better "state" management of the data, as what I feel ?

Looking forward to hear from you,

**Comment by threepointone** [comment]
We do think Hooks are very much in the spirit of React. Happy to hear any specific concerns or bugs about context you might have. 

Closing this issue since it's not really actionable, cheers.

**Comment by q591111061** [comment]
＃14833
