### ISSUE TITLE
Shallow renderer doesn't update on setState() with Hooks

### ISSUE THREAD

**Issue by gaearon** [facebook/react#14840]
See the issue and the test case with original fix in https://github.com/facebook/react/pull/14802.

We'll need to fix it properly, see https://github.com/facebook/react/pull/14802#issuecomment-463277621.

**Comment by rodrigopr** [comment]
I will try to take another look at this, starting with adjusting comments/code to align with new behavior.
You mentioned it might need a larger refactoring, do you have anything in mind? Should it be a part of this change?
