### ISSUE TITLE
memoized elements by React.memo are not equal 

### ISSUE THREAD

**Issue by zeakd** [facebook/react#14847]
**Do you want to request a *feature* or report a *bug*?**

I'm not sure. if it is not a bug, it would be a feature request.

**What is the current behavior?**
``` jsx
const Message = React.memo((props) => {
  return <div>{props.message}</div>
})

console.log(<Message message='hi'/> === <Message message='hi />) // false
```

Hi. I'm using `React.memo` and I found memoized elements are not equal. I think it is not a bug, However it is useful in some cases if they are equal.

``` jsx
const Message = React.memo(props => {
  console.log('render Message')
  return <div>{props.value}</div>
})

const Panel = React.memo(props => {
  console.log('render Panel')
  return <div>{props.message}</div>
})

const render = (component) => {
  ReactDOM.render(
    component,
    document.getElementById('container')
  );
}

render(
  <Panel message={<Message value='hi'/>}/>
);
setTimeout(() => {
  render(
    <Panel message={<Message value='hi'/>}/>
  );
}, 1000)

// render Panel
// render Message
// render Panel

```

Above example is passing element as props. In this scenario, `<Message />` is successfully memoized but `<Panel />` is not because momoized message elements are not same. With equality of memoized element, it would be useful to optimize component with element props like props.children.

**Comment by gaearon** [comment]
Memo doesn't literally cause elements to be memoized, it just treats them as if they were (based on prop shallow equality).

In your example, this would work:

```js
let message = <Message value='hi'/>;
render(
  <Panel message={message}/>
);
setTimeout(() => {
  render(
    <Panel message={message}/>
  );
}, 1000)
```

If a parent component puts `message` in state and renders `<Panel message={message} />` then it seems like you’ll get the desired behavior.
