### ISSUE TITLE
@types\react-dom v.16.8.1 : Error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by dmitrykurmanov** [facebook/react#14846]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
typescript error
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
build wiothout ts errors
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
It worked with previous version of @types\react-dom.

**Comment by threepointone** [comment]
The React team doesn't maintain the typescript types for React, please file this issue with the @types repo instead https://github.com/DefinitelyTyped/DefinitelyTyped/issues, . I'd also recommend you make a reproducible sample of the failure on codesandbox (https://codesandbox.io/s/new) when you do.

**Comment by dmitrykurmanov** [comment]
ok thanks, here the issue in the correct repo: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33065

**Comment by VincentLanglet** [comment]
@dmitrykurmanov Hi !
You have to use the last version of `@types/react`
