### ISSUE TITLE
defaultvalue from state popualted via ajax call

### ISSUE THREAD

**Issue by chandmk** [facebook/react#1484]
```
getInitialState: function() {
        return {employee: {}};
    },
    componentWillMount: function() {
        this.get("employee/1" , function(data) {this.setState({employee: data})}.bind(this));
    },
    render: function() { 
        console.log(this.state.employee.name);
        return (            
                input type="text" defaultValue={this.state.employee.name} 
                );
    }
```

In the above code console.log prints fine.  But defaultValue is not getting populated!

Probably react already mounted the component before the ajax call.  Is there any other way to populate defaultValues from server?

**Comment by calderaro** [comment]
i have the same problem

**Comment by RudmanMario** [comment]
And whats up with the situation when I want to have props value in my input:

```javascript
<input type="text" ref="inputValue" value={this.props.value} onChange={this.handleInputChange} />
```

How to change the value in my onChange function? I can't change my props value and I can't use state.

**Comment by rohan-deshpande** [comment]
I want to chime in here, what I don't really understand is - if I have an input field with a `defaultValue={this.state.name}` I can change the value in the `onClick` event like this

```
        handleNameChange:function(e)
        {
            this.setState({name:e.target.value});
        }
```

But, if the state is changed elsewhere, the `defaultValue` does not update. I don't see how this makes sense personally.

**Comment by yamill** [comment]
I was running with the same issue so I ended up doing something like this:

    componentDidMount: function() {
       var that = this;
       this.get("employee/1" , function(data) {
          that.setState({data: data, loaded: true})
       }   
    },

    render: function(){
      (
         {this.state.loaded ? 
         <div>
           <input value={this.state.data.name} />
           <input value={this.state.data.lastname} />
         </div>
         : <p>"Loading..."</p>}
      )
    }

**Comment by mervynyang** [comment]
@yamill  Your method can running, but I bind onChange with form, like so:
 ```js
onFieldChanged(e) {
        this.setState({
            [e.target.name]: e.target.value
        });
    }

<form onChange={::this.onFieldChanged}>
       <input value={this.state.data.name} name="input1" />
       <input value={this.state.data.lastname} name="input2" />
</form>
```

It's not work, can you give a some advice?THX!

**Comment by mervynyang** [comment]
@yamill Your method can running, but I bind onChange with form, like so:
```js
onFieldChanged(e) {
        this.setState({
            [e.target.name]: e.target.value
        });
    }

render() {
  <form onChange={::this.onFieldChanged}>
       <input value={this.state.data.name} name="input1" />
       <input value={this.state.data.lastname} name="input2" />
  </form>
}
```
It's not work, can you give a some advice?THX!
