### ISSUE TITLE
Hooks should be published as separate package

### ISSUE THREAD

**Issue by dehghani-mehdi** [facebook/react#14844]
Hi,

As you mentioned already on docs, at the moment we can not rewrite our exiting components to support hooks ([Hooks could reduce your bundle size](https://medium.com/@dan_abramov/making-sense-of-react-hooks-fdbde8803889)), so what if we want to update react to latest version (for bug fixes, ...), but don't want to add that [1.5KB](https://medium.com/@dan_abramov/making-sense-of-react-hooks-fdbde8803889) to our bundle size?

Thanks

**Comment by gaearon** [comment]
If 1.5KB (~4%) is a bottleneck for you, perhaps React isn’t the right choice for your application. The size of React always fluctuates somewhat between releases. You can hold off updating until we manage to reduce it but generally reductions come from major releases (because they enable us to delete legacy code). Deleting legacy code is not possible without adding alternatives during the previous major so we don’t really have options there.

**Comment by gaearon** [comment]
For some perspective, your avatar on this page weighs more than the Hooks implementation.

<img width="816" alt="screen shot 2019-02-14 at 3 44 42 pm" src="https://user-images.githubusercontent.com/810438/52798282-87d69180-306f-11e9-8662-d2dac231e89e.png">

**Comment by dehghani-mehdi** [comment]
Of course I don't switch to another framework for 1.5KB, I love React.

I just saying as you [mentioned](https://medium.com/@dan_abramov/making-sense-of-react-hooks-fdbde8803889) Hooks is new feature and maybe change in future, so I think you will add more codes (I'm not sure btw), so maybe you should think about it, I think at the beginning React DOM wasn't separate package.

Btw Github should use better code for generating avatars.

**Comment by gaearon** [comment]
In the long term it's more likely we'll move classes to a separate package. Their implementation creates more internal complexity for React than Hooks.

**Comment by dehghani-mehdi** [comment]
I know this issue is closed and won't be opened again, but I think I didn't answer following part and I'm going to do that

>For some perspective, your avatar on this page weighs more than the Hooks implementation.

Let's say React is used by 124,000 sites and each of them have 100 users in average, so 12,400,000 requests will be sent and let's say Hooks adds 1KB to the library, that means 12.4GB more data has to be transferred because of Hook. so my Avatar isn't the problem here and I think it's not even right example here, 2 completely different situations.

**Comment by dehghani-mehdi** [comment]
@gaearon I worked with hooks in my recent project and I should say it's really great and fun to work with. I just want to share my opinion about hooks about you.
