### ISSUE TITLE
css script loaded too late

### ISSUE THREAD

**Issue by Vnxx** [facebook/react#14854]
### **react version 16.8.1 | Mac Os (mojave)| Chrome**
hi, there is something that i don't like or something disturbs me,
when i run the app `npm start` and the app show up on the browser, when the browser load the app, the css script loaded too late, less than 1 second the app show up like only html file without css, you know just text without styling on it.

**react version 16.8.1**
when i check the react app on browser (chrome) -> inspect -> sources -> pages -> top -> no domain -> **{css script appear here}**
and when i refresh the browser, css script loaded too late

**react version 16.6.3**
but when i check out on my older react version and i run it `npm start`, and i do the same thing:
browser (chrome) -> inspect -> sources -> pages -> top -> **{there is no 'no domain'}**.
css script fused with  elements bellow `<title>React App</title>` or (chrome) -> inspect -> elements, on this version css script loaded without being late.

sorry my english is bad, i hope you understand

**Comment by gaearon** [comment]
Sorry, this doesn't sound related to React itself (it doesn't manage CSS or styles).

If you use Create React App, please file an issue here: https://github.com/facebook/create-react-app

It would also need a reproducing example.
