### ISSUE TITLE
Unexpected additional render using Hooks

### ISSUE THREAD

**Issue by adamhartleb** [facebook/react#14866]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Component is rendered one more additional time than expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Demo here:

https://codesandbox.io/s/v380wrp205

**What is the expected behavior?**
Note the console.log on line 6 in the demo. The behavior I expected would be a maximum of two logs:

re-rendered 0
re-rendered 1

The first log is for the initial render and the second log is for the re-render when the button is clicked. Any additional clicks would be ignored because it bails out of updates if the value between renders are the same (according to https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update).

Here is the actual behavior:

re-rendered 0
re-rendered 1
re-rendered 1

Clicking the button again after the first click causes another re-render, but why? The value hasn't changed since the previous render.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8

**Comment by ahtee** [comment]
the codesandbox link doesn't work.

**Comment by alexeyraspopov** [comment]
If you look at React DevTool Profiler, only a single render happens when state becomes `1`.

**Comment by markerikson** [comment]
The React team can correct me if I'm wrong, but:

Based on what I've read, I _think_ the "setter" functions _always_ queue up a state update, and React has to actually attempt to render the function component in order to see if the value is actually different or not.  If it's the same as before, then the re-render of the function component is effectively thrown away.

**Comment by gaearon** [comment]
Yep that sounds correct.

If you see its *children* re-render then please raise an issue.
