### ISSUE TITLE
npm audit reports security vulnerability for braces packages

### ISSUE THREAD

**Issue by ztolley** [facebook/react#14868]
OS: Mac OS
Node: 10.15.1
NPM: 6.4.1

When you create a new react app and use npm to install dependencies npm audit reports 63 low priority vulnerabilities all caused by a security vulnerability discovered with 'braces' previous to version 2.3.1

Steps to reproduce
------------
```
npx create-react-app hello-world
cd hello-world
npm audit
```

<img width="577" alt="screenshot 2019-02-16 at 13 40 23" src="https://user-images.githubusercontent.com/56056/52900672-7668c300-31f0-11e9-9cc4-f7a5579fe883.png">

**Comment by monkindey** [comment]
I think [the create-react-app is a better location](https://github.com/facebook/create-react-app/issues/) to report it.

**Comment by gaearon** [comment]
Yep.

**Comment by ztolley** [comment]
yeah sorrt
