### ISSUE TITLE
React 16.8.2 No matching version found for scheduler@^0.13.2

### ISSUE THREAD

**Issue by Andr3s4n** [facebook/react#14862]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

![npm error](https://user-images.githubusercontent.com/16775646/52866800-5cb77500-3137-11e9-9fd4-09195ee3bdf2.png)

![error](https://user-images.githubusercontent.com/16775646/52866485-ac497100-3136-11e9-9ddd-cdd85433af6d.png)
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Yarn add react or npm install react

**What is the expected behavior?**

Installs the appropriate version.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.2

![dependencies](https://user-images.githubusercontent.com/16775646/52866702-24b03200-3137-11e9-822a-9c97152add41.png)

**Comment by brookslybrand** [comment]
Hey @Andr3s4n, I'm not able to replicate your error. When I run `npm install react` in a new npm project, it installs scheduler version 0.13.2.

**Comment by threepointone** [comment]
what package manager is that? npm doesn't have dropdowns like so. feels like you have a local cache that wasn't updated. `npm info scheduler` clearly shows 0.13.2 was published on '2019-02-14T19:02:08.853Z'

**Comment by bvaughn** [comment]
> what package manager is that?

Yarn shows that prompt. (The description also mentions Yarn.)

Looks like [the same thing](https://github.com/facebook/react/issues/13693#issuecomment-464004481) was mentioned on #13693 recently. Dan speculated that maybe the cause was an NPM mirror that was lagging behind.

[NPM confirms](https://www.npmjs.com/package/scheduler) that `scheduler@0.13.2` exists and was published a day ago, so this probably isn't something we can help with.

**Comment by Andr3s4n** [comment]
Indeed that was also the case. It's working now properly.

**Comment by joacim-boive** [comment]
It's back... Again.
No matching version found for scheduler@^0.13.6

npx create-react-app test
Fails with the above error message....

**Comment by campalubaer** [comment]
I have the same issue...
"react": "16.8.6",
"react-dom": "16.8.6"

_No matching version found for scheduler@0.13.6_

_yarn install_, i can choose version for scheduler package (the recent one is 0.13.4),  _npm install_ failed.

**Comment by Andr3s4n** [comment]
Please check @bvaughn comment.

The [last release](https://www.npmjs.com/package/scheduler) was just 9h ago, so it might be happening the same.
