### ISSUE TITLE
React Dev Tools: useReducer content isn't displayed

### ISSUE THREAD

**Issue by jktravis** [facebook/react#14872]
[Crosspost at react-devtools](https://github.com/facebook/react-devtools/issues/1305)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using `useReducer` with an object as state doesn't show the content of the object and is un-expandable.

<img width="669" alt="2019-02-16_20-05-13" src="https://user-images.githubusercontent.com/438688/52907061-a089a780-3227-11e9-95e6-fb2edc6e8fa5.png">

Using a state with a string will show.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://q8yzo2z1mj.codesandbox.io/

**What is the expected behavior?**
Expect the contents be expandable as with objects and arrays from traditional state.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.8.2
DevTools: 3.6.0
Chrome: 72.0.3626.109 (Official Build) (64-bit)

**Comment by BTMPL** [comment]
This is not a React issue, this is a (current version of) Devtools limitation.

See https://github.com/facebook/react-devtools/issues/1282 for progress ; it's fixed in experimental branch.

**Comment by threepointone** [comment]
That's right, Brian's working on getting this into the react devtools. closing this issue in favour of that one.
