### ISSUE TITLE
Feature Request: React filter

### ISSUE THREAD

**Issue by chiaweilee** [facebook/react#14874]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

wish to use `filter` in React

**What is the expected behavior?**

support `filter` in React

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I did a repo [react-jsx-filter](https://github.com/chiaweilee/react-jsx-filter) which makes `filter` support in React JSX.
It base on [babel-plugin-transform-react-jsx-filter](https://github.com/chiaweilee/react-jsx-filter/tree/master/packages/babel-plugin-transform-react-jsx-filter).

**Example**

```react.js
// <div>React</div>
<div>{ 'react' | capitalize }</div>
```

```react.js
// <div>3</div>
<div>{ 1 | addOne | addOne | addOne }</div>
```

```react.js
// <div>你好</div>
<div>{ 'hello' | translate('zh-cn') }</div>
```

```react.js
// with lodash
<div>{ this.state.data | _.filter({ 'active': true }) | this.renderTable }</div>
```

**Comment by threepointone** [comment]
jsx isn't a typical templating language, and as such stays away from dsls and shortcuts like the above. It's unlikely to change any time soon. you're welcome to use your plugin in your own stack, it looks useful to you!  closing this issue.
