### ISSUE TITLE
[Safari (iOS)] - history.block does prevent the browser to go back

### ISSUE THREAD

**Issue by freeboarder42** [facebook/react#14885]
**What is the current behavior?**

When using `history.block` in a component, the browser's back button does not work in Safari (iOS 12)  if the previous route was a route within the app. After tapping the back button, even (react-router) links do not work anymore.

**Notes**
Please note that the react-router team dismissed an issue created for this bug that suspected the `Prompt` component as the cause, with the note that the bug is in the React's `history` object.

**Test Case**

https://github.com/freeboarder42/react-safari-history-block-bug-demo

**Steps to reproduce**

- Create a simple React app with two components besides App.jsx (Home.jsx, ComponentWithHistoryBlock.jsx)
- Create routings to `Home` and `ComponentWithHistoryBlock` in App.jsx
- Place a link to `ComponentWithHistoryBlock` on `Home`
- Place a link to `Home` on `ComponentWithHistoryBlock`
- Add following code in  `ComponentWithHistoryBlock`:
```
constructor(props) {
   super(props);

   const { history } = this.props;
   this.unblock = history.block('Really navigate away?');
}

componentWillUnmount() {
   this.unblock();
}
```
- Run the app in Safari on iOS (12)
- Use the link to `ComponentWithHistoryBlock` to go to `ComponentWithHistoryBlock`
- Tap the browser's back button
- Tap the `Home` link

**What is the expected behavior?**

The browser should go to the `Home` component when tapping the browser's back button. After this did not work, the browser should go to the `Home` component when tapping the Home link.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 6.8.2
React Router: 4.3.1 (just used for routing)
OS: iOS 12.1.4
Don't know if it worked in previous versions of React

**Comment by gaearon** [comment]
>with the note that the bug is in the React's history object.

React offers no `history` object and has no code related to history or routing at all. (Thanks for the report but it’s not actionable here.) Did you mean the `history` library? https://github.com/ReactTraining/history

**Comment by freeboarder42** [comment]
Sorry for mistaking this. I myself don't know the source, but you're right: The react-router team actually stated the source of the issue is in the history _library_.  I hope you can use my sample project to get to it. I think it's important that a react-router Prompt or history.block works correctly on iOS.
