### ISSUE TITLE
Safari won't let me type on a text input

### ISSUE THREAD

**Issue by brielov** [facebook/react#14889]
I wrote a simple search box that works fine on Chrome and Firefox, but in Safari is another story. It let me type a single character and won't update any more.

![2019-02-19 11 25 05](https://user-images.githubusercontent.com/42145089/53022321-b8d11080-3439-11e9-89e7-6dca97a2611c.gif)

Here is the code

```javascript
function Header({ history }) {
  const [q, setQ] = useState("");

  const onSubmit = e => {
    e.preventDefault();
    history.push({
      pathname: "/buscar",
      search: `q=${encodeURIComponent(q.trim())}`,
    });
  };

  return (
    <header className={styles.Header}>
      <div className={styles.Container}>
        <form className={styles.Form} onSubmit={onSubmit}>
          <input
            autoCapitalize="off"
            autoComplete="off"
            autoCorrect="off"
            autoFocus
            className={styles.Input}
            onChange={e => setQ(e.target.value)}
            placeholder="Buscar por nombre, dni o cuit"
            spellCheck="false"
            type="search"
            value={q}
          />
          <button type="submit" className={styles.Submit}>
            Buscar
          </button>
        </form>
      </div>
    </header>
  );
}
```

Am I missing something? Is this a known bug?

**Comment by gaearon** [comment]
A reproducing case please.

**Comment by brielov** [comment]
@gaearon Sorry, here is a prototype: https://cuit.app

**Comment by gaearon** [comment]
Can you make a standalone example with inspectable code please? Like CodeSandbox.

**Comment by TienDo1011** [comment]
I believe this is not React issue, it's the issue with `-webkit-user-select: inherit;` (CSS) getting applied to Safari.

**Comment by brielov** [comment]
@gaearon Yes I can, but it won't be necessary. @TienDo1011  you are right, user-select was the problem. Thank you and sorry for this dummy issue.

**Comment by mAbdeen9** [comment]
> I believe this is not an React issue, it's the issue with `-webkit-user-select: inherit;` (CSS) getting applied to Safari.

you save me man ! 2 hours trying to solve the bug 👍
