### ISSUE TITLE
Hooks not available in some parts of my component tree

### ISSUE THREAD

**Issue by nwinger** [facebook/react#14887]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The use of useContext() at a certain level up in the component tree seems to be broken somehow. I'm able to do the approach in other components, but for my main <App> component, the context values are not available. The app is based on create-react-app, using Typescript.

**NOTE: To toggle the functionality of the menu, please simulate screen sizes of a mobile device**
Please note the comments on useContext not working properly in App.tsx, and how I demonstrate the a working context in Header.tsx.
Here's the working codesandbox: https://codesandbox.io/s/4rl53m496x

**What is the expected behavior?**
Expect to be able to use the hook in App.tsx, the same way it's used in Header.tsx

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
    "typescript": "^3.3.3"
    "react": "^16.8.2",
    "react-dom": "^16.8.2",
    "react-scripts": "^2.1.5",
    "@types/react": "16.7.18",
    "@types/react-dom": "16.0.11",
```

**Comment by gaearon** [comment]
Your structure is:

```js
<App>
  <AppContainer> // Rendered by <App>
    <NavigationContext.Provider> // Rendered by <AppContainer>
```

Context is available *below* `NavigationContext.Provider`. That's the thing that *provides* context.

If you nest `NavigationContext.Consumer` *below* it, it will work.


```js
<App>
  <AppContainer> // Rendered by <App>
    <NavigationContext.Provider> // Rendered by <AppContainer>
      <NavigationContext.Consumer> // ✅ Rendered by <App> 
```

But `useContext` inside `App` reads it at the `App` level:

```js
<App>
  useContext(NavigationContext) // 🔴 Is above the NavigationContext provider
  <AppContainer> // Rendered by <App>
    <NavigationContext.Provider> // Rendered by <AppContainer>
```

So it isn’t expected to work.

To fix it, move the context provider above all components that want to read that context.

**Comment by nwinger** [comment]
Oh dear🙈 Sorry for the overhead @gaeron! And thanks for the super quick reply!
