### ISSUE TITLE
useState with optional storage handler

### ISSUE THREAD

**Issue by jmccarrell-lmi** [facebook/react#14880]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
useState(initialValue)

**What is the expected behavior?**
useState(initialValue, storageHandler) // Or whatever impl someone can think of

Going off of the example here: https://usehooks.com/useLocalStorage/
The value has two different sources. Only one is accessible, so it isn't too bad, but it technically breaks the concept of a single source of truth. It's also a very verbose solution to a simple problem, which is caused because *there is no way to trigger an effect outside of a component* without using `useState`. IMO this is fine, but you should be able to provide an alternative state to use. The function returned by useState can be used to trigger re-renders, regardless of whether the state is stored.

So, I'd suggest adding a second optional argument to useState that allows someone to specify a getters and setter for useState.

`get(initialValue)`

```
set(newValue => {
    return mutatedNewValue; //for internal memoization purposes
})
```

This isn't high priority or necessary, but IMO this just makes React one step closer to optimal DX opportunity for developers.

**Comment by gaearon** [comment]
I don't think I understand what problem you're trying to solve, or why that would solve it better. In either case, please direct API suggestions here: https://github.com/reactjs/rfcs. Thank you!
