### ISSUE TITLE
hook is not working when calling inside event handler

### ISSUE THREAD

**Issue by Albert-Gao** [facebook/react#14883]
React version: 16.8.2

```javascript
const { useState } = React;

const Dropdown = ({
  options,
  onClick,
  selected,
}) => {
  const [showDropDown, setShowDropDown] = useState(false);

  function toggleDropDown() {
    setShowDropDown(v => !v);
  }

  function createOption(o) {
    return (
      <div
        key={o}
        className='drop-down__option'
        onClick={() => {
          onClick(o);
          toggleDropDown();  
          // The following isn't working either
          // setShowDropDown(false);
        }}
       >
        {o}
      </div>
    );
  }
  
  return (
    <div
      onClick={toggleDropDown}
      className='drop-down'
    >
      <div>{selected}</div>
        {showDropDown && (
          <div className='drop-down__list'>
            {options.map(createOption)}
          </div>
        )}
    </div>
  );
};

const App = () => {
  const [selected, setSelected] = useState(0);
  
  return (
    <Dropdown
      selected={selected}
      options={[0,1,2,3]}
      onClick={v=>{setSelected(v)}}
    />
  );
}

ReactDOM.render(
  <App />,
  document.getElementById('root'),
);
```

So, it's a simple `Dropdown`, when you click the container, it toggles the `Dropdown`.

> But the problem here is, after clicking one of the options, the option has been updated, but the `Dropdown` is not been closed.

So it appears ` toggleDropDown(); ` in the following code has no effect.

```javascript
        onClick={() => {
          onClick(o);
          toggleDropDown();  
          // The following isn't working either
          // setShowDropDown(false);
        }}
```

A reproduce example can be found here: https://codepen.io/vensa-albertgao/pen/ommGZe

What did I miss?

**Comment by jquense** [comment]
The problem isn't that the update doesn't run it's that it's running __twice__

You have an `onClick` handle on the parent dropdown div as well as the option div. When you click an option the first handler (the `onClick` on the option div) fires, changing `showDropdown` to `false`, the event then bubbles up to the parent div and fires _again_ toggling it back to `true`, so the effect is nothing changes.

**Comment by Albert-Gao** [comment]
Thanks for the quick response.

I added `e.stopPropagation` and it works now
