### ISSUE TITLE
Context subscribers block thread for long period after restoring tab to foreground

### ISSUE THREAD

**Issue by benwiley4000** [facebook/react#14888]
**Do you want to request a *feature* or report a *bug*?**

Bug! (I would argue it's a bug)

**What is the current behavior?**

If a Context receives many value updates while an app is running in a background browser tab (while a different tab is in the foreground), the subscribers will be inundated with a metric ton of updates when the tab resumes. This is because the context updates with `requestAnimationFrame` whose callback is deferred until the tab refocuses in the foreground.

You can see that in practice here: https://benwiley4000.github.io/cassette/styleguide/ (for future reference the commit is here for when the site contents have changed: https://github.com/benwiley4000/cassette/commit/d732a3579fd7888e1c9a99eb4dfe8cf7aa8fa00d)
1. Begin playing media
2. Open dev tools and begin recording a performance profile
3. Open a new tab and ignore the other tab for awhile (15-30 seconds?)
4. Go back and stop the performance profile. At the end you'll see a flurry of context updates fired thanks to a bunch of media currentTime setState calls while the tab was in the background. You'll also notice the app UI is frozen during this time.

![screenshot from 2019-02-19 08-47-40](https://user-images.githubusercontent.com/13558253/53020007-08a4dd00-3424-11e9-8131-d41971cf899c.png)

**What is the expected behavior?**

I think it would be better if the Context waited to call `requestAnimationFrame` at all until the tab is no longer hidden, and only updated with the latest context value. This would avoid app crashes, which could easily happen if the app runs in the background for a long time.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.6.1, no idea (doubt it)

**Comment by benwiley4000** [comment]
I can also imagine my proposed solution could lead to breakage in existing code.

**Comment by gaearon** [comment]
>This is because the context updates with `requestAnimationFrame` whose callback is deferred until the tab refocuses in the foreground.

I'm not sure I understand this. Where is this information coming from? The `updateForContext` function in your frame graph isn't defined in React. (It also doesn't seem to use React context since it does a `forceUpdate`.)

The code from https://github.com/benwiley4000/cassette/commit/d732a3579fd7888e1c9a99eb4dfe8cf7aa8fa00d (including `requestAnimationFrameWhenPageVisible`) is not coming from React.

Can you create a smaller reproducing example?

**Comment by benwiley4000** [comment]
Oh you know what.. that might be my fault after all. I'd completely forgotten I wrote the contexte Ovide rentrer code :) I'm going to close this for now and I'll re-open if it is a react issue.

**Comment by benwiley4000** [comment]
This is some custom code I wrote awhile back to sync a single context across multiple react roots. Sorry for the false alarm.

**Comment by gaearon** [comment]
No problem!
