### ISSUE TITLE
Hooks error on bundle SSR, but works fine on client

### ISSUE THREAD

**Issue by vemundeldegard** [facebook/react#14898]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

First i run `npm run build` in /client, then I start the server in another window by going to /server and run `npm start`. When I go to a page that uses hooks (http://localhost:3000/para), I get an error. See below. 

Interestingly it works fine when I use class components and good old state (http://localhost:3000/dyna).  When I run` npm start` on the client side, both state and hooks work fine. But it does not work from static markup. 

Small piece of the simple hooks page:

```
const ParaPage = () => {

  const [pages, setPages] = useState(null);

  Sanity.fetch(`
  *[_type == "sider" && hidden == false]{
      _id,
      name,
      path,
  } | order(_createdAt asc)
  `)
    .then(res => {
      setPages(res)
    })
    .catch(err => {
      setPages(err)
    })

}
```

> (node:1551) UnhandledPromiseRejectionWarning: Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)
>     at invariant (/Users/vemundeldegard/siste/client/node_modules/react/cjs/react.development.js:88:15)
>     at resolveDispatcher (/Users/vemundeldegard/siste/client/node_modules/react/cjs/react.development.js:1436:28)
>     at useState (/Users/vemundeldegard/siste/client/node_modules/react/cjs/react.development.js:1461:20)
>     at ParaPage (/Users/vemundeldegard/siste/client/lib/ParaPage.js:21:39)
>     at processChild (/Users/vemundeldegard/siste/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:2871:14)
>     at resolve (/Users/vemundeldegard/siste/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:2795:5)
>     at ReactDOMServerRenderer.render (/Users/vemundeldegard/siste/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3175:22)
>     at ReactDOMServerRenderer.read (/Users/vemundeldegard/siste/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:29)
>     at renderToString (/Users/vemundeldegard/siste/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3619:27)
>     at /Users/vemundeldegard/siste/server/lib/react-renderer.js:64:15
> (node:1551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
> 
> 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

See repo here: https://github.com/vemundeldegard/ssr-hooks

**What is the expected behavior?**

To render the hooks just as good as state. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Running React 16.8.2 on Mac OS 10.14

**Comment by threepointone** [comment]
the repo you shared doesn't exist?

**Comment by gaearon** [comment]
>Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

Did you follow the link in that error and read it? Which of the cases did you try?

**Comment by indiejoseph** [comment]
It seems like you have more than one copy of React, for client-side all libraries would bundle up and share a single copy of React, but this isn't applied on the server side, if any library you used in node_modules, they would import their own dependencies which including React
