### ISSUE TITLE
Cannot is possible use the same component with React.lazy in multiple entry

### ISSUE THREAD

**Issue by rflmyk** [facebook/react#14895]
**Do you want to request a *feature* or report a *bug*?**
🐛 Bug Report

**What is the current behavior?**
I have multiple entries on my webpack, like bellow:
```
...
entry: {
  page1: 'javascripts/page.one',
  page2: 'javascript/page.two'
}
...
```

If I used:

```
const Component1 = React.lazy(()=> import('components/Component1'));
```

only on entry **page1** work fine. But if I try use in entries **page1 and page2**, work on development mode but when I compiled to production trow a error:

```

TypeError: n.e is not a function
    at react-dom.production.min.js:132
    at ha (react-dom.production.min.js:170)
    at qa (react-dom.production.min.js:204)
    at $a (react-dom.production.min.js:205)
    at Ii (react-dom.production.min.js:220)
    at Mi (react-dom.production.min.js:219)
    at Di (react-dom.production.min.js:216)
    at ei (react-dom.production.min.js:214)
    at Ui (react-dom.production.min.js:233)

```
**What is the expected behavior?**
I would like to get use React.lazy with the same component in multiples entries

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "16.6.1"
"react-dom": "16.6.1"

To test I updated to 16.8.0 and continue happening

I'm sure if is a problem with React or Webpack, if someone have some idea, pls help me

**Comment by gaearon** [comment]
We can't help with a report like this when it has no reproducing case.

**Comment by gaearon** [comment]
(I'll keep it open but we'd need at least a reproducing project)

**Comment by rflmyk** [comment]
let me think as I can show for you...

**Comment by rflmyk** [comment]
So, I'm closed it because is a problem with my setting on webpack on specific into `optimization.splitChunks.cacheGroups`, where I forgot to test what type of files is applied, sorry for that and thank you.
