### ISSUE TITLE
Elements as Callable Objects

### ISSUE THREAD

**Issue by harrysolovay** [facebook/react#14905]
I want to create a lib that allows a function `strand` to let users create react elements with either of the following:

```js
strand('div') // equal to `React.createElement('div', null)`
strand('div')('child text') // equal to `React.createElement('div', null, 'child text')`
```

To achieve this, I tried the following:

```js
const strand = tag => Object.assign(
  (...children) => React.createElement(tag, null, ...children),
  React.createElement(tag, null)
)
```

This creates a callable element object (or should).

If––as you're reading this issue––you're wondering "this is an obnoxious, costly implementation", don't worry, it'll get compiled down... this is just a runtime/in-dev version of my project. Very hacky... but I'd still like to get it working.

Here's the problem I run into:

`Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.`

^ I'm guessing that the internals of React are checking to see if it's a function... instead of only checking the $$typeof symbol prop that gets copied over via the `Object.assign` call? Is there any way around this? I'd really like to see this come to life!

Thank you for giving this issue a read, & hopefully there's a solution :)

Kind regards,

Harry

**Comment by TienDo1011** [comment]
Yeah you're right, React only cares about `$$typeof` if the return value is an `object`. In case of `function`, you'll get the warning instead.
To get this to work, you need to make sure what comes after return statement is an `object`, not `function`.
I think you can force it by using a bridge function:
```
const forceObject = value => {
 if (typeof value == "function") {
    return value();
  }
return value;
}
```

Then use it in your code like this:
```
class App extends Component {
   render() {
     return forceObject(strand("div"));
   }
 }
```
This works for both strand("div") and strand("div")("child text"). You can even custom the value the way you like also.

**Comment by harrysolovay** [comment]
@TienDo1011 that adds a step to using the library... I'd really like to find another way if possible. Any other ideas?

I'm wondering if the maintainers of React would consider changing the type check? This would open the door to component instances which double as component constructors. I'm not saying it's the most critical feature... but it'd be cool to blur the line between `Component` and `<Component />`.

**Comment by gaearon** [comment]
We intentionally don't support supplying functions as children. If this API call is generated then you should also be able to generate a trailing `toValue()` or similar at the end of the chain.

**Comment by harrysolovay** [comment]
@gaearon I'm curious why the decision to exclude functions from being React children? (could be applicable for other uses).
