### ISSUE TITLE
Images dont render

### ISSUE THREAD

**Issue by FilipFranek1** [facebook/react#14915]
Hi, i have a bug,
Basically this is my code ( excluding import react etc)
 `<img  src="./img/aa.png" alt="" />`

And the image doesnt get rendered. In browser, react dev tools it show the image is 1366x0px.
There are no errors in the console.
I tried making new crate-react-app, udsing different images, using <image> instead of <img> and none of these worked...

I apologise for my english

**Comment by gaearon** [comment]
https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files

**Comment by FilipFranek1** [comment]
still doesn't work

**Comment by FilipFranek1** [comment]
Thanks!
