### ISSUE TITLE
Errors in tracing fixture shouldn't look like errors in packaging fixture

### ISSUE THREAD

**Issue by gaearon** [facebook/react#14918]
Before https://github.com/facebook/react/pull/14917, I used to get this:

<img width="502" alt="screen shot 2019-02-21 at 5 38 03 pm" src="https://user-images.githubusercontent.com/810438/53190100-cbe20d00-3600-11e9-9ffa-b230f3bb78fe.png">

**Comment by bvaughn** [comment]
Hm. For me, when the tracing fixture fails I see:
![screen shot 2019-02-21 at 3 04 53 pm](https://user-images.githubusercontent.com/29597/53207962-11dfa680-35ea-11e9-8047-e173cbc0e188.png)
