### ISSUE TITLE
Adapt release process instructions to our patch release process

### ISSUE THREAD

**Issue by gaearon** [facebook/react#14919]
Basically this:

<img width="407" alt="screen shot 2019-02-21 at 6 06 46 pm" src="https://user-images.githubusercontent.com/810438/53191345-8246f180-3603-11e9-9fd0-bc9944da92f1.png">

**Comment by gaearon** [comment]
A minor thing: it might be good to remind that if you're cutting a patch, you should base your intuition about version number on *actual cherry-picked changes* and not what's in master.

**Comment by gaearon** [comment]
And let's make sure the message asks you to update the website version. Otherwise error codes won't be there.

**Comment by bvaughn** [comment]
> And let's make sure the message asks you to update the website version. Otherwise error codes won't be there.

Hm? I don't think this is accurate. Any time something (anything) rebuilds the documentation, [the error codes are regenerated from master](https://github.com/reactjs/reactjs.org/blob/21ca8ed58819b9b498d8c55066e1e299c9dbe452/plugins/gatsby-source-react-error-codes/gatsby-node.js#L3-L4) (and not the version of React that happens to be running on the docs site).

I guess it's maybe worth mentioning to trigger a website rebuild just in case though, and it's probably worth prompting to update the versions YML after a major/minor release.

**Comment by gaearon** [comment]
Right, but this assumes something _would_ rebuild the documentation. What if nobody merges any PRs for a week?

**Comment by bvaughn** [comment]
Right. I agreed that it was probably worth mentioning the need to trigger a rebuild, but it doesn't require updating the React version.

**Comment by gaearon** [comment]
I figured updating React version is a good way to extra smoke test it.

**Comment by gaearon** [comment]
Also to update version in the header.
