### ISSUE TITLE
eslint-plugin-react-hooks@next no longer includes exhaustive-deps

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/react#14921]
**Do you want to request a *feature* or report a *bug*?**

Bug-ish

**What is the current behavior?**

The newly-released eslint-plugin-react-hooks@1.1.0 (tagged as both `latest` and `next`) [does not include](https://unpkg.com/eslint-plugin-react-hooks@1.1.0/cjs/eslint-plugin-react-hooks.development.js) the new exhaustive-deps rule. As a result, `npm install eslint-plugin-react-hooks@next` no longer installs a version of the plugin containing the rule.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

See [unpkg](https://unpkg.com/eslint-plugin-react-hooks@1.1.0/cjs/eslint-plugin-react-hooks.development.js) -- scroll to the bottom to verify that only `rules-of-hooks` is exported.

**What is the expected behavior?**

I'm not sure if 1.1.0 was intended to include the rule or not. (It seems to be the only entry in the commit log between 1.0.2 and 1.1.0, and the alphas/RC were released as 1.1.0-X, so I'm guessing it was?)

If it was, then this might have been a release bug?

If it wasn't, perhaps a new 1.2.0-rc.1 could be released and tagged as `next` so that `npm install eslint-plugin-react-hooks@next` installs a version of the plugin with the new rule, as it did before 1.1.0.

**Comment by gaearon** [comment]
I just cut `eslint-plugin-react-hooks@1.2.0` which has the rule.
