### ISSUE TITLE
useReducer reduces actions again on render

### ISSUE THREAD

**Issue by orokanasaru** [facebook/react#14925]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

On render, previous reduce actions are reduced again

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/x3yqq70z8z

```javascript
import React, { useReducer } from "react";
import ReactDOM from "react-dom";

const Bug = () => {
  console.log("render");

  const [value, dispatch] = useReducer((state, action) => {
    console.log(action.type);
    switch (action.type) {
      case "UPDATE": {
        return state + 1;
      }
      case "NOP": {
        break;
      }
      default:
    }
    return state;
  }, 0);

  const update = () => {
    console.log("update");
    dispatch({ type: "UPDATE" });
  };

  const nop = () => {
    console.log("nop");
    dispatch({ type: "NOP" });
  };

  return (
    <>
      <button onClick={nop}>Nop</button>
      <button onClick={update}>Update</button>
    </>
  );
};
```

Click the Nop button, then click the Update button.

The console output is:
- render
- nop
- NOP
- update
- UPDATE
- render
- NOP
- UPDATE

The last two (NOP and UPDATE) go through the reducer without getting dispatched from the component.

For each consecutive click of Nop, the call to update will reduce an extra NOP after render.
After the first re-render, the amount of NOPs reduced will be the number of clicks - 1.

**What is the expected behavior?**

No actions get reduced without calling dispatch.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This happens in every browser, and in every version of React since 16.8.0-alpha-0.

**Comment by gaearon** [comment]
It's expected because the first time we evaluate the reducer early to see if we can bail out of the update. (And we do with the "nop" update.) But if we couldn't (such as with the "update"), then we have to call the reducer again during rendering — because it may depend on fresh props.

The best practice is to hoist the reducer *outside* the component, like in the documentation. Then React knows it's the same one, and can avoid re-evaluating it in most cases.

Such as here: https://codesandbox.io/s/rzjxwj1y4
