### ISSUE TITLE
Uncaught Error: Hooks can only be called inside the body of a function component

### ISSUE THREAD

**Issue by azat-io** [facebook/react#14929]
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v16.8.3, ReactDOM v16.8.3

------------------------------------

I made a very simple example of my code in this repo: 
https://github.com/azat-io/react-hooks-example

Could you explain me please, what's wrong, why hooks not works for me?
Try to run my code if it possible

I have already checked versions of React and ReactDOM, I cleaned yarn and NPM cache

**Comment by gaearon** [comment]
Not sure what's wrong with your webpack config (maybe that HTML plugin is buggy) but if you put an `console.log()` inside `react-dom/index.js` code you'll see it executes twice. This is not normal and indicates a problem with your bundler setup.

If you want a setup that works, Create React App is one possible option.
