### ISSUE TITLE
Add support for functions as children in Suspense

### ISSUE THREAD

**Issue by MeiKatz** [facebook/react#14933]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`<Suspense children={() => {}} />` is not supported.

**What is the expected behavior?**
As mentioned [here](https://github.com/facebook/react/issues/13947#issuecomment-465743800) before, I hope that there will be support for `children` to be a render prop in `<Suspense />`. Why? I currently have the following case where I dislike to define another component only for loading async data
```javascript
function ShowModal({ itemId }) {
  return (
    <Modal open>
      <Suspense fallback={<p>Loading ...</p>}>
      {() => {
        const item = ItemStorage.read(itemId);

        return (
          <Modal.Header>
            <Modal.Title>{item.name}</Modal.Title>
          </Modal.Header>
          <Modal.Body>
          { /* ... stuff with data of item ... */ }
          </Modal.Body>
        );
      })
      </Suspense>
    </Modal>
  );
}
```
Currently this does not work because `children` is not allowed to be a function. So I have to define another component whos only task is to load the data and pass it to into the right place. I think there should be an easier solution, like the one used above. (To be honest, the code above works, **but** only because I use a wrapper component around the native React Suspense component.)

My currently wrapper component is defined like this:
```javascript
function SuspenseRenderChildren({ children }) {
  return children(); // really? :/
}

function Suspense({ children, ...props }) {
  if (typeof children === "function") {
    return (
      <React.Suspense {...props}>
        <SuspenseRenderChildren children={children} />
      </React.Suspense>
    );
  } else {
    return (
      <React.Suspense {...props} children={children} />
    );
  }
}
```
Therefore I create some kind of *wrapper hell* because in the worst case I render the following ...
```javascript
<Suspense>
  <React.Suspense>
    <SuspenseRenderChildren />
  </React.Suspense>
</Suspense>
```
... where it could be just ...
```javascript
<React.Suspense />
```

**Comment by ahtee** [comment]
let me take a stab at this...
It should be better to use a separate component you already write as <Loader /> and use in Suspense since this would comply with react's composition model I saw here [https://reactjs.org/docs/composition-vs-inheritance.html](https://reactjs.org/docs/composition-vs-inheritance.html) rather than creating an anonymous arrow function which would not be re-usable.

**Comment by MeiKatz** [comment]
@ahtee Sure, but `<Suspense fallback />` is not the problem. And I also support your opinion about reusable components. The point is, that in the case above (my case) I use some reusable components `<Modal />` etc. and also a component that represents a special case `<ShowModal />`. Why should I define an extra component just for nesting reasons? I mean, sure, maybe people should define an extra component, but we should not force them to do so if there is an alternative way.

**Comment by MeiKatz** [comment]
@TrySound I would be nice to hear your opinion about this and not just your sign of denial.

**Comment by TrySound** [comment]
My point is that you don't need to afraid new components. Yeah, sometimes passing too much props is annoying but you need to do the same with hooks all over the place.

**Comment by gaearon** [comment]
The idiomatic React solution is to create a new component. Not something generic like `SuspenseRenderChildren` but a component that corresponds to your UI — such as `ItemContent`.

```js
function ShowModal({ itemId }) {
  return (
    <Modal open>
      <Suspense fallback={<p>Loading ...</p>}>
        <ItemContent itemId={itemId} />
      </Suspense>
    </Modal>
  );
}

function ItemContent({ itemId }) {
  const item = ItemStorage.read(itemId);

  return (
    <>
      <Modal.Header>
        <Modal.Title>{item.name}</Modal.Title>
      </Modal.Header>
      <Modal.Body>
      { /* ... stuff with data of item ... */ }
      </Modal.Body>
    </>
  ); 
}
```
