### ISSUE TITLE
Feature request: Add an optional parameter "enable" to all Hooks.

### ISSUE THREAD

**Issue by revskill10** [facebook/react#14937]
Currently, there's no support for "conditional Hook", i mean we couldn't enable/disable Hook based on  a javascript value.

Suggestion: Allow for all Hooks to have an optional `enable` paramenter , which default value set to `true`.
So if a user set `enable: false` , like 
```js
const shouldRunState = false
const [count, setCount] = useState({enable: shouldRunState})
```
the Hooks will simply have no effect at all, as if it's not there.

My example is just to show what the feature look like.
This feature should be backward compatible with current Hooks API.

Common use case is allow a Component/Parent to control Hooks based on `props/context`, so it'll make Hooks more flexible to use.

**Comment by threepointone** [comment]
what would disabling a state hook even do? you can 'disable' effects by using the dependencies array and guards in your code. We considered a variety of factors in the design, it would be useful if you could show a real usecase.  Closing this issue.
