### ISSUE TITLE
[eslint-plugin-react-hooks] Allow configuration custom hook detection

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#14941]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
https://codesandbox.io/s/vjqo40v9yy
```js
function unstable_useMediaQuery(query) {
  const [matches, setMatches] = React.useState(false);
  //                            ^ [...] called in function which is neither hook nor component
  /* implementation... */
}
```

**What is the expected behavior?**
I would like some form of configuration of what is considered a hook. There's already a good entry point for a solution to this problem in
https://github.com/facebook/react/blob/c11015ff4f610ac2924d1fc6d569a17657a404fd/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L18https://github.com/facebook/react/blob/c11015ff4f610ac2924d1fc6d569a17657a404fd/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L18 

The simplest implementation would allow for a custom regex but I fear that people abuse this until it's very hard to recognize what a custom hook is and what not. Allowing a prefix would solve this particular use case. Maybe as opinionated as `/^${prefix}_use[A-Z0-9].*$/`.

`useUnstableMediaQuery` is not a good solution IMO since it implies that the media query is unstable. Same for `Unstable_useMediaQuery`. This is pretty hacky since the linter considers this a component. React has already set precedent with prefixing experimental features with `unstable_` so this naming pattern is not that exotic.

Happy to work on a PR.

**Comment by Jessidhia** [comment]
A possible heuristic is to detect hooks where the last 2 arguments of the call are a function immediately followed by an inline array. `useFoo(foo, () => {}, [])`.

It wouldn't be able to catch cases of passing an array in a variable, and it wouldn't catch the `useCallback` pattern (only `useMemo` / `useEffect` pattern), but it'd be a start, and it would have worked for the few custom hooks I had that used the pattern.

**Comment by cdoublev** [comment]
A small note related to this feature request: using `use` as a hook function name triggers an eslint error, but nothing prevents it explicitly in the React docs:

> A custom Hook is a JavaScript function whose name starts with ”use” and that may call other Hooks.

> Its name should always start with use so that you can tell at a glance that the rules of Hooks apply to it.

> Do I have to name my custom Hooks starting with “use”? Please do. This convention is very important. Without it, we wouldn’t be able to automatically check for violations of rules of Hooks because we couldn’t tell if a certain function contains calls to Hooks inside of it.

https://reactjs.org/docs/hooks-custom.html

I created a hook splitted in a few modules and it was nice to simply use `use` as the hook module filename, place it in a directory named after the data that the hook must deal with, and export a hook function also named `use` from this `use` module. This little dot in `/^use[A-Z0-9].*$/` was against me... 😢
