### ISSUE TITLE
dynamic load remote address

### ISSUE THREAD

**Issue by hangyangws** [facebook/react#14947]
## request for feature

I want to dynamic load react bundle in remote address，
and I see react lazy : https://reactjs.org/docs/code-splitting.html#reactlazy.
But I think it can‘t resolve my problem.

This is my expectant pseudo code:
```
user.input((moduleName) => { // user input event listener
  React.lazy(() => {
    const DynamicModule import(`www.cdn.xxx/${moduleName}.js`);
  });
});
```

this there have any way to resolve my requirement。

**Comment by aweary** [comment]
@hangyangws what specifically is the problem you're trying to resolve? What issue are you running into? It's hard to help without more information. It would also help to have a real code example reproducing the problem.

**Comment by hangyangws** [comment]
@aweary 
Thinks for you replay. 
Maybe my describe is not clear.

I am  trying to resolve the problem, what as the following description.

In my single page react application, there this a product requirements.
It allow the third party developers to develop react component and package the code with UMD standard to a javascript bundle, then publish the bundle in a unified online resources.
`tips: the bundle is not  a NPM package but just a online javascript bundle resource.`

And next, in my single page react application, there is a function that users could input online component bundle address, then render this react component.

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by gaearon** [comment]
(This question is unrelated to React. It's about loading JS code.)
