### ISSUE TITLE
[ESLint] Hardcore rule allowing default hooks using only inside custom ones

### ISSUE THREAD

**Issue by Voronar** [facebook/react#14957]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There is no rule

**What is the expected behavior?**
We have some hardcore plugins like `eslint-plugin-lodash-fp`.
Why not have ESLint hardcore rule allowing default hooks using only inside custom ones?

**Comment by gaearon** [comment]
Why?

**Comment by Voronar** [comment]
> Why?

In this way your component "render" function staying more clear and readable because contains only "HTML" with some custom hooks above.

**Comment by gaearon** [comment]
I don't think we'll be adding a rule like this but feel free to create one. :-)
