### ISSUE TITLE
Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead

### ISSUE THREAD

**Issue by huisheng123666** [facebook/react#14956]
include.preload.js:1 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
React doesn't use `createShadowRoot` anywhere, so this warning must be coming from somewhere else.

**Comment by tpyoung** [comment]
@huisheng123666 It's probably from an extension you're using. Google Dictionary causes this to pop up in the console for me on all sites.

**Comment by Mvahedii** [comment]
@huisheng123666 It's from Google Translate or another extension :)

**Comment by sunil220** [comment]
> @huisheng123666 It's probably from an extension you're using. Google Dictionary causes this to pop up in the console for me on all sites.

Very helpful that was because of dictionary and removed that extension after that it is working fine.
Thanks
