### ISSUE TITLE
Collapse forwardRef and other wrappers in React error stacks

### ISSUE THREAD

**Issue by natew** [facebook/react#14953]
**Feature**

**What is the current behavior?**

With a UI kit that uses forwardRefs, I get error messages like this:

![image](https://user-images.githubusercontent.com/12100/53372321-61ceae00-3907-11e9-9d20-190315cc7f06.png)

**What is the expected behavior?**

It would look a lot better if forwardRefs were a bit less obtrusive, and if they picked up the functions displayName rather than just the name of the function they wrap.

In our UI Kit we have a pattern like:

```
const View = forwardRef(function UIView(){ return <div /> })
View.displayName = 'SomeDisplayName'
```

For some reason it's not showing that, just showing the inner one. Further the "bigness" of ForwardRef() makes it hard to see visually when scanning. Perhaps something more like this would help:

```
Warning: Encountered two children with the same key, `confluence`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by ForwardRef(Gloss))
    in Gloss (ForwardRef)
    in Gloss (ForwardRef) (created by OnboardMain)
    in div (created by Gloss (ForwardRef))
    in Gloss (ForwardRef)
    in Gloss (ForwardRef) (created by SliderPane)
```

Further, the `created by` information is often more useful to me, but it's never aligned nicely. Could do something like:

```
Warning: Encountered two children with the same key, `confluence`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
      in div (created by ForwardRef(Gloss))
      in Gloss (ForwardRef)
    from OnboardMain:
      in Gloss (ForwardRef)
   from Gloss (ForwardRef):
      in div
      in Gloss (ForwardRef)
   from SliderPane:
      in Gloss (ForwardRef)
```

All together, if it would pick up displayNames, the stack would be far more readable for me:

```
Warning: Encountered two children with the same key, `confluence`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
      in div (created by Row)
      in View (forwardRef)
    from OnboardMain:
      in Row (forwardRef)
   from Col (forwardRef):
      in div
      in Grid (forwardRef)
   from SliderPane:
      in View (forwardRef)
```

**Comment by Jessidhia** [comment]
It's not that simple as user components may also be using `forwardRef` (to be able to use `useImperativeHandle` for example) :(

**Comment by gaearon** [comment]
Do you mind making a small self-contained example showing a verbose stack? Maybe we can exclude them based on some heuristic. I'm not sure *always* excluding them in the right call.

**Comment by gaearon** [comment]
Btw the best way to fix it is to send a PR. It's one of those things that are not prioritized enough by themselves unless someone steps up to do it.

**Comment by gaearon** [comment]
>In our UI Kit we have a pattern like:
>
>```js
>const View = forwardRef(function UIView(){ return <div /> })
>View.displayName = 'SomeDisplayName'
>```
>For some reason it's not showing that, just showing the inner one.

I can't reproduce this. It shows up for me:

<img width="1054" alt="Screen Shot 2019-03-21 at 6 19 38 PM" src="https://user-images.githubusercontent.com/810438/54775522-1bb6f280-4c06-11e9-82a2-23845a557e18.png">

As always with bug reports, if there was a repro we could have fixed this today, but since there's no repro, I can't help.

**Comment by natew** [comment]
I am not setting displayname manually outside, I am just wrapping with forwardRef. Perhaps a babel-transform would help, but my request was for the use case of not setting displayName manually.

**Comment by natew** [comment]
Ah, actually the use case where I see is is as follows:

```
const View = memo(forwardRef(function UIView() { return <div /> }))
View.displayName = 'SomeDisplayName'
```

Apologies for the miscommunication.
