### ISSUE TITLE
Unable to validate proptype for an argument of a function received as props

### ISSUE THREAD

**Issue by VAHMEZE** [facebook/react#14958]
Missing Documentation for the same

**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Unable to validate proptype for an argument to a function passed as props

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
we should be directly validate the propTypes for the arguments right in the component itself.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All versions

**Comment by gaearon** [comment]
This is not really in scope of prop-types but you're welcome to do it on your own by calling `PropTypes.checkPropTypes`. In general we recommend static solutions like TypeScript or Flow for that instead.
