### ISSUE TITLE
Cannot get the latest values of the state inside useEffect hook( first load only ).

### ISSUE THREAD

**Issue by gideonairex** [facebook/react#14965]
**Do you want to request a *feature* or report a *bug*?**
_BUG_

**What is the current behavior?**
Cannot get the latest values of the state inside our useEffect function ( only on first load ). But can log the latest values of the state upon re-render.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
```
const {
		iframeWindow,
		iframeDocument,
		component,
		newMessageCount
	} = useContext(AppContext);

	/**
	 * Information variables
	 */
	const [threadList, changeThreadList] = useState([]);
	const [contactInfo, changeContactInfo] = useState({});
	const [twilioNumbers, changeTwilioNumbers] = useState([]);
	const [recipientOptions, changeRecientOptions] = useState([]);

	/**
	 * Loading States
	 */
	const [searchLoading, changeSearchLoading] = useState(false);
	const [sendingMessage, changeSendingMessage] = useState(false);
	const [gettingList, changeGettingList] = useState(true);

	/**
	 * Load more page start
	 */
	const [pageStart, changePageStart] = useState(1);
	const [loadMoreCount, changeLoadMoreCount] = useState(0);
	const [firstLoad, changeFirstLoad] = useState(true);

	/**
	 * Message body content to be sent to the backend
	 */
	const messageBody = {
		conversation_id: useInput(),
		contact_number_id: useInput([]),
		message: useInput(),
		twilio_number_id: useInput(),
		sending: useState(false)
	};

        .....

        /**
          * instantiate the Pusher
         */
        useEffect(() => {
            getNewMessageEvent();
            updateMessageStatusEvent();
        }, [firstLoad]);
        

       ....

       /**
	 * updates the message status
	 */
	function updateMessageStatusEvent() {

		eventPusher.updatewMessageStatus(({ data: { id, status } }) => {

                        /**
			 *
			 * PROBLEM here we cant get the value of the updated threadList its always empty
			 *
			 *
                          */
			console.log('local thread list', threadList);
			let message = find(threadList, ['id', id]);
			setTimeout(() => {
				console.log(id, threadList);
			}, 100);
			// if (typeof message != 'undefined') {
			// 	message.status = status;
			// 	console.log(threadList);
			// }
		});
	}

        ....
       return (
          .....
       );
```

**What is the expected behavior?**
Expecting that the latest values of the state will be accessible inside our first load useEffect. Expecting that the state Array will be a pass by reference. Assuming that it can be accessible.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Using **^16.8.0**. This is a hooks implementation.

**Comment by TienDo1011** [comment]
Can you provide a codesandbox example to describe your bug?

**Comment by gaearon** [comment]
This is a *lot* of code. I’ll be writing related documentation soon and can show how to fix it — but I’ll need you to create a CodeSandbox that is a minimal code example.

**Comment by RIP21** [comment]
@gaearon 
Not sure whether I have the same issue cause there is a lot of code.
But my issue looks like following.
```js
  const notInProgress = !inProgress.value
  console.log("Rerender", notInProgress)
  const cleanUpSomething = useCallback(
    () => {
      console.log("Effect on onUnmount", notInProgress)
      if (notInProgress) {
        setSomething({})
      }
    },
    [notInProgress],
  )
useEffect(() => cleanUpSomething, [notInProgress])
```
Problem is that in subsequent rerenders I can see lot's of `true`, then, when I change this `inProgress.value` so boolean `notInProgress` results into `false`, I have `false` on rerenders but when unmount callback gets called I can see that it still has `notInProgress` of `true` which causes unneeded cleanup that I want to ignore by this `notInProgress` flag.
Any idea how to fix that?

**Comment by PierreAndreis** [comment]
@RIP21 I'm not able to replicate. This is my attempt:  https://codesandbox.io/s/oz765y5z5

**Comment by salvoravida** [comment]
@RIP21 
here 
```js
useEffect(() => cleanUpSomething, [notInProgress])
```"

cleanUpSomething is executed on effectUnMount before reExecute Effect with 
notInProgress value of  previous render N-1, so with !!notInProgress  

isn't it?

**Comment by RIP21** [comment]
@salvoravida @PierreAndreis 
https://codesandbox.io/s/l9qwp077p7
Here is the full example. 
I expect cleanup to be called with the actual value of the `inProgress` but I'm getting an old value.
But, I assume it's correct behavior. Since it keeps old value to do something on it, e.g. if it's a reference to some listener it should be an old listener and not a new one, so it has a chance to clean it up.
Any idea how to do flag based cleanup while keeping that in mind?

**Comment by salvoravida** [comment]
> @salvoravida @PierreAndreis
> https://codesandbox.io/s/l9qwp077p7
> Here is the full example.
> I expect cleanup to be called with the actual value of the `inProgress` but I'm getting an old value.
> But, I assume it's correct behavior. Since it keeps old value to do something on it, e.g. if it's a reference to some listener it should be an old listener and not a new one, so it has a chance to clean it up.
> Any idea how to do flag based cleanup while keeping that in mind?

i don not understand what is your problem.

the cleanup function of useEffect is always related to render N-1 closure, because it is created on N-1 render.

what is your uses case? 
you what to access closure N on render N-1 ?
you have to use a REF o just a mutable object, so when cleanup is executed  (on render N) can read update value...

**Comment by salvoravida** [comment]
Moreover your useBoolean is Not a ref object but every render a new object
export const useBoolean = initial => {
  const [value, setValue] = useState(initial);
  return {
    value,
    setValue,
    toggle: useCallback(() => setValue(v => !v), []),
    setTrue: useCallback(() => setValue(true), []),
    setFalse: useCallback(() => setValue(false), [])
  };
};

so of course inProgress is the old one....

**Comment by RIP21** [comment]
@salvoravida yeah, this is what I wanted.
To have actual value (N render) in N-1 callback :) I should use `ref` for that? `useEffect` is a bit tricky, sorry for maybe stupid questions and examples.
Also, is it possible to set ref with value on the first render in init phase and not in render after if it's just a plain value?
If it's a DOM node, it's obvious, it should be rendered before assigned, but if a regular value that is taken from some `context` for instance. To do some stuff like `prevContextProps.inProgress !== currentContextProps.inProgress`.

**Comment by salvoravida** [comment]
> @salvoravida yeah, this is what I wanted.
> To have actual value (N render) in N-1 callback :) I should use `ref` for that? `useEffect` is a bit tricky, sorry for maybe stupid questions and examples.
> Also, is it possible to set ref with value on the first render in init phase and not in render after if it's just a plain value?
> If it's a DOM node, it's obvious, it should be rendered before assigned, but if a regular value that is taken from some `context` for instance. To do some stuff like `prevContextProps.inProgress !== currentContextProps.inProgress`.

@RIP21 
https://codesandbox.io/s/415ynw034
` const { inProgress } = useContext(Context);
  const inProgressValue = inProgress.value;
  console.log("Rerender", inProgressValue);
  
  const currentInProgressValue = useRef();
  currentInProgressValue.current = inProgressValue;

  useEffect(
    () => {
      console.log("On toggle effect!", inProgressValue);
      return () => {
        currentInProgressValue.current &&
          console.log("Cleanup effect only when InProgress!", currentInProgressValue.current);
      };
    },
    [inProgressValue]
  );`

**Comment by RIP21** [comment]
@salvoravida TIL. Thanks a lot :)

**Comment by gaearon** [comment]
If anyone’s curious, I think this blog post dives into why it works this way. Although I plan to write more on useEffect specifically. 

https://overreacted.io/how-are-function-components-different-from-classes/

**Comment by gaearon** [comment]
@RIP21

Can you please explain *why* you’re trying to do this? What is the actual use case in product code? Why does cleanup need to know about some other thing being “in progress”?

Describing a specific scenario will likely help find a more idiomatic solution to this. :-)

**Comment by RIP21** [comment]
@gaearon 
The guy above already helped me.
So basically for me, it was if there is some form in progress do not do cleanup on unmount, cause you may lookup for some other info on other page and then return back to the form. And when actual unmount happened, there was N - 1 render variable closured in the cleanup callback and not the actual one, so flag was still `false` while in the actual state it's `true` since `useEffect` cleanup runs after the render/unmount with N - 1 values unless you use `ref` that will capture current value e.g. N state.

**Comment by mattkrick** [comment]
@gaearon Could we add a linting rule if `useState()[0]` is used inside `useEffect` & it does not exist in `useEffect`'s deps?
 
FWIW, here's my use case & where i got burned:
```js
const useSwarm = () => {
  const [swarm, setSwarm] = useState(null)
  useEffect(() => {
    subscribe.then((newSwarm) => setSwarm(newSwarm))
    return () => {
      // WARNING: swarm my be stale. useRef is required!
      swarm && swarm.close()
    }
  }, [])
  return swarm
}
```

In my dumb head, it seems unintuitive that `swarm` is null in the disposable when it is eventually nonnull inside the  `useSwarm` closure.

**Comment by gaearon** [comment]
> Could we add a linting rule if useState()[0] is used inside useEffect & it does not exist in useEffect's deps?

We already have a lint rule for this: `exhaustive-deps` from [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks) (https://github.com/facebook/react/issues/14920). It would have caught this issue. **We strongly recommend using that lint plugin.**

I'm not sure your example needs a ref. Maybe you wanted something like this?

```js

const useSwarm = () => {
  const [swarm, setSwarm] = useState(null)

  useEffect(() => {
    subscribe.then((newSwarm) => setSwarm(newSwarm))
  }, []);

  useEffect(() => {
    if (swarm) {
      return () => swarm.close()
    }
  }, [swarm])
  return swarm
}
```

Overall, it doesn't seem like there are any bugs in this case. Relevant new documentation:

* https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function **(this should answer the initial question in this issue)**
* https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies
* https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often

Some longer form reading:

* https://overreacted.io/how-are-function-components-different-from-classes/
* https://overreacted.io/a-complete-guide-to-useeffect/#each-render-has-its-own-effects
* https://overreacted.io/writing-resilient-components/#dont-stop-the-data-flow-in-side-effects

---


I'll lock the issue to make sure these links stay visible. If you have a problem please file a new issue.
