### ISSUE TITLE
Add label for Eslint (or as 'eslint-plugin')

### ISSUE THREAD

**Issue by ahtee** [facebook/react#14961]
**Do you want to request a *feature* or report a *bug*?**

Feature 🥇 

**What is the current behavior?**

no existing label for eslint, but lots of discussion on it in issues

**Comment by gaearon** [comment]
Added.

https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+ESLint+Rules%22

**Comment by ahtee** [comment]
Thanks @gaearon !
