### ISSUE TITLE
input cursor jump to end when call setState in setTimeout

### ISSUE THREAD

**Issue by foisonocean** [facebook/react#14966]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

Cursor jump to end when call setState in setTimeout

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```jsx
import React, { useState, useCallback } from 'react';
import { render } from 'react-dom';


class App extends React.PureComponent {
  state = {
    input: '',
  }
  
  handleInput = event => {
    const value = event.target.value;
    
    setTimeout(() => {
      this.setState({
        input: value,
      });
    }, 1);
  }
  
  render () {
    return <input value={this.state.input} onChange={this.handleInput} />
  }
}

render(<App />, document.getElementById('root'));
```

[CodeSandbox](https://codesandbox.io/s/ojw817wmpy)

**What is the expected behavior?**

Cursor should not jump to end

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v16.8.3

**Comment by TienDo1011** [comment]
What do u mean by saying `jump to end`? I don't understand your problem by looking at that CodeSandbox example.

**Comment by gaearon** [comment]
This is expected behavior. If you don't set a controlled input to the current value *during* the event, React can't know whether to preserve the position or not. So the next change essentially resets the input.
