### ISSUE TITLE
Cannot run create-react-app nameofapp

### ISSUE THREAD

**Issue by Geeeva** [facebook/react#14963]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
cannot run create-react-app nameofapp
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
create-react-app bob

Creating a new React app in C:\wamp64\www\bob.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

npm ERR! Unexpected end of JSON input while parsing near '....tgz"}},"2.3.4":{"nam'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ivana\AppData\Roaming\npm-cache\_logs\2019-02-26T21_21_48_727Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

Deleting generated file... package.json
Deleting bob/ from C:\wamp64\www
Done.

**What is the expected behavior?**
Should create new react app

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Node v10.15.1
npm 6.7.0

**Comment by Geeeva** [comment]
Run npm cache clean --force and after that npx create-react-app my-app and it worked.

**Comment by omwalhekar** [comment]
I am still getting the same error, I've tried cleaning cache and runnning the command again still i get the same error, please help me out

**Comment by omwalhekar** [comment]
I am still getting the same error, I've tried cleaning cache and running the command again still I get the same error, please help me out

**Comment by Mr-DRP** [comment]
I havent subscribed however i am continuously getting email.
