### ISSUE TITLE
memo equality check function overrides state

### ISSUE THREAD

**Issue by minheq** [facebook/react#14972]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When a component is wrapped with `React.memo` and is provided 2nd argument - equality check function, it overrides state in the parent component

**What is the expected behavior?**
It should not override the state in parent component

Reproduction and detailed explanation of the bug is within this codesandbox:
https://codesandbox.io/s/4j6ownx8x0

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Codesandbox

**Note**: I spent few hours verifying that this is a genuine bug and not a due to my misunderstanding, but I apologize if it is the latter.

**Comment by hosseind2017** [comment]
change the App function to this
it will fix

```
function App() {
  const [selectedStartDate, setSelectedStartDate] = React.useState(null);
  const [selectedEndDate, setSelectedEndDate] = React.useState(null);

  const handleSelect = (type, date) => {
    if (type === "start") {
      setSelectedStartDate(date);
    } else {
      setSelectedEndDate(date);
    }
  };

  return (
    <div>
      <MemoButton
        onSelect={date => handleSelect("start", date)}
        comparedProp={format(selectedStartDate)}
        date={new Date(2019, 1, 5)}
        text="SET START DATE"
        key={1}
      />
      <div>START DATE: {format(selectedStartDate)}</div>

      <MemoButton
        onSelect={date => handleSelect("end", date)}
        comparedProp={format(selectedEndDate)}
        date={new Date(2019, 2, 5)}
        text="SET END DATE"
        key={2}
      />
      <div>END DATE: {format(selectedEndDate)}</div>
    </div>
  );
}
```

https://codesandbox.io/s/w6mo9xz4z7?fontsize=14

**Comment by iskandar17** [comment]
Just one thing in
```
const handleSelect = (date: Date) => {
    if (!selectedStartDate) {
      setSelectedStartDate(date);
    } else {
      setSelectedEndDate(date);
    }
  };

```
fixed here
https://codesandbox.io/s/ov2kmko319

**Comment by iskandar17** [comment]
```
const handleSelect = (date: Date) => {
    if (!selectedStartDate) {
      setSelectedStartDate(date);
    } else {
      setSelectedEndDate(date);
    }
  };
```
wrong condition
fix ->>
https://codesandbox.io/s/ov2kmko319

**Comment by iskandar17** [comment]
and It's all because you handler keeps old value of `selectedStartDate` even you changed it by click on button `SET START DATE`

**Comment by iskandar17** [comment]
https://codesandbox.io/s/943916znlp
see what memo component renders here after each call

**Comment by gaearon** [comment]
Custom equality checks must include *all* props you care about. Including callbacks. (This is why generally you shouldn't supply your own comparison function — it's easy to make a mistake!)

The mistake you're making is that you're ignoring changes to `props.onSelect`. **So the `onSelect` handler of both buttons "sees" the initial `selectedStartDate` state only (`null`). It's never updated.** Therefore, `if (!selectedStartDate)` is always true and you always end up calling `setSelectedStartDate`.

If I fix your equality function, it works:

```diff
const equalityCheck = (prevProps, nextProps) =>
-  prevProps.comparedProp === nextProps.comparedProp;
+  prevProps.comparedProp === nextProps.comparedProp &&
+  prevProps.onSelect === nextProps.onSelect;
```

https://codesandbox.io/s/62961yk72z

You can also `useCallback` if you don't want to break memoization by always passing different functions. But in that case you need to make sure you don't close over anything that's not specified in deps. So you can't close over `selectedStartDate` in your check.

The most idiomatic fix to this is `useReducer`. It makes it easy to preserve callback identity while having more complicated state logic. Here's an example: https://codesandbox.io/s/62961yk72z.

**Comment by minheq** [comment]
Many thanks for your elaborate explanation! I understand it now, hopefully others who make this same mistake will find their answers here as well

and thanks @iskandar17 for chiming in
