### ISSUE TITLE
componentDidUpdate (and componentDidMount) before the updates ref

### ISSUE THREAD

**Issue by vflash** [facebook/react#14975]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
componentDidUpdate (and componentDidMount) before the updates ref

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codepen.io/anon/pen/eXpENK?editors=0011

**What is the expected behavior?**
componentDidUpdate  (and componentDidMount) after ref update

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
browser. last version

**Comment by gaearon** [comment]
Can you be more specific about the log order you expect? I don't understand this report.

**Comment by vflash** [comment]
http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/
According to the documentation, "React updates DOM and refs" comes before "componentDidMount" 
But this rule is not observed if for children. Same thing for "componentDidUpdate".

for example: 
https://codepen.io/anon/pen/KEdrLm?editors=0011
```js
class App extends React.Component {
  render() {
    return <Element ref='element' getElement={() => this.refs.element}/>;
  }
};
class Element extends React.Component {
  render() {
    return <div>Element</div>;
  };
  componentDidMount() {
    console.log('mount', this.props.getElement()); // log undefined
  };
};

ReactDOM.render(<App/>, document.getElementById('root'));
```

**Comment by bdjnk** [comment]
I've experienced this as well. My use case complex, but here is the bottom line. 

```js
componentDidUpdate() {
  const { scrollTop } = this.ref.current;
  // scrollTop is sometimes is not the updated value here
}
```

I'll try and create a consistently reproducible minimal example if I have time.

**Comment by bdjnk** [comment]
I apologize for the long delay. Here is an example of what I believe to be this bug. @gaearon 

https://codesandbox.io/s/componentdidupdate-ref-bug-lvcn0

The bug result in repeat calls to `componentDidUpdate` when scrolling due to an un-updated `scrollTop`. It manifests on Firefox and Safari, but not Chrome.

If I've got this wrong somehow I'd love to understand my mistake.

**Comment by vflash** [comment]
up
