### ISSUE TITLE
React custom hook "Should have a queue. This is likely a bug in React" error message.

### ISSUE THREAD

**Issue by justin0022** [facebook/react#14979]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Getting this error message: **Should have a queue. This is likely a bug in React. Please file an issue.**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React.**

I tried to implement a simple data cache in a custom hook:
```  javascript
import { useState, useEffect } from 'react'

const get = url => {
  return fetch(url)
    .then(res => res.text())
    .then(data => JSON.parse(data))
}

const cache = new Map()

const useData = dataURL => {
  const [data, setData] = useState(null)
  if (cache.has(dataURL)) {
    return cache.get(dataURL)
  }

  useEffect(() => {
    get(dataURL).then(data => {
      cache.set(dataURL, data)
      setData(data)
    })
  }, [dataURL])

  return data
}

export default useData
```
The entire project code is here: https://github.com/justin0022/dashboard/tree/cache

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Using React 16.8.2, Chrome, and MacOS.

**Comment by gaearon** [comment]
Please reduce this to a smaller isolated example, ideally on CodeSandbox. Thanks. Also please provide exact steps to reproduce.

**Comment by justin0022** [comment]
I went to reproduce in CodeSandbox and the linter immediately told me that I was using a conditional in `useEffect`. Definitely will be adding the linter to my project now...

Thanks!

**Comment by gaearon** [comment]
The error message is still weird so I would appreciate a link.

**Comment by justin0022** [comment]
Sure, I'll send a link shortly.

**Comment by justin0022** [comment]
https://codesandbox.io/s/y3xyq6wx21?fontsize=14

In the browser console, you'll see **Invariant Violation: Should have a queue. This is likely a bug in React. Please file an issue.**

Hope this helps.

**Comment by justin0022** [comment]
In my application, I didn't get the other error messages that the CodeSandbox link shows. 

Here are the error messages from my app:
<img width="1019" alt="screen shot 2019-02-28 at 1 32 40 pm" src="https://user-images.githubusercontent.com/8836578/53600081-858b3180-3b5d-11e9-880c-6ec86bea9610.png">
<img width="1014" alt="screen shot 2019-02-28 at 1 32 36 pm" src="https://user-images.githubusercontent.com/8836578/53600082-858b3180-3b5d-11e9-9d59-c9ad224a59c6.png">

**Comment by LexSwed** [comment]
it says to me, that you have `return` from your function earlier than running effect hook

**Comment by justin0022** [comment]
Hey @LexSwed, thanks, I already fixed this error - @gaearon asked me to reopen the issue because he said the error message looked strange.

**Comment by threepointone** [comment]
I'm curious why you didn't see the other error messages in your app (specifically about the change in order). Closing this for now, but we may revisit if this happens again in the future, or if you have any new information to share. Thanks!

**Comment by mr-shahAbbas** [comment]
I've also had such a problem and finally I found that the main reason of this problem is using hooks in wrong place, you need to use your hook in parent component and not the child one. For example, you have a todo list and todo component, you have to use it in todo list and not in todo.

**Comment by Frankenstein4** [comment]
> 个问题的主要原因是在错误的地方使用了钩

并不是这样 就算在父组件也会如此，只要加了useState就会如此   https://github.com/facebook/react/issues/25063

**Comment by Frankenstein4** [comment]
> I've also had such a problem and finally I found that the main reason of this problem is using hooks in wrong place, you need to use your hook in parent component and not the child one. For example, you have a todo list and todo component, you have to use it in todo list and not in todo.

This is not the case, even in the parent component, as long as useState is added.

**Comment by Frankenstein4** [comment]
> I've also had such a problem and finally I found that the main reason of this problem is using hooks in wrong place, you need to use your hook in parent component and not the child one. For example, you have a todo list and todo component, you have to use it in todo list and not in todo.

https://github.com/facebook/react/issues/25063
