### ISSUE TITLE
Different createContext implementation in Production and Development builds

### ISSUE THREAD

**Issue by VladimirMilenko** [facebook/react#14977]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Development and production version of createContext are different.
Minified production version is setting `_context` prop only on Provider.
```
createContext: function(a, b) {
      void 0 === b && (b = null);
      a = {
        $$typeof: w,
        _calculateChangedBits: b,
        _currentValue: a,
        _currentValue2: a,
        _threadCount: 0,
        Provider: null,
        Consumer: null
      };
      a.Provider = {$$typeof: v, _context: a};
      return (a.Consumer = a);
    },
```
While in development version, `_context` property is attached to both, Provider and Consumer.
```
  context.Provider = {
    $$typeof: REACT_PROVIDER_TYPE,
    _context: context
  };

  var hasWarnedAboutUsingNestedContextConsumers = false;
  var hasWarnedAboutUsingConsumerProvider = false;

  {
    // A separate object, but proxies back to the original context object for
    // backwards compatibility. It has a different $$typeof, so we can properly
    // warn for the incorrect usage of Context as a Consumer.
    var Consumer = {
      $$typeof: REACT_CONTEXT_TYPE,
      _context: context,
      _calculateChangedBits: context._calculateChangedBits
    };
```
**Codesandbox:**

Production version:
https://codesandbox.io/s/zn09n09lo3

Development:
https://codesandbox.io/s/487ym7xjk9

**What is the expected behavior?**
Development version should match Production version. In terms of, you should be able to access `_context` from both, Consumer and Provider.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.2, 16.8.3 .
From source code, i can see, that the changes to development build were added in 16.6.

**Comment by VladimirMilenko** [comment]
I do understand, that probably, it should be resolved whenever React's team removes the warning about `Usage of Context is as a consumer`, but it also adds an interesting debugging on production version :)

**Comment by gaearon** [comment]
Accessing `_context` is not supported in either of them. It’s an internal property and its behavior can change in any patch version without a warning. 

https://reactjs.org/docs/faq-versioning.html#what-counts-as-a-breaking-change
