### ISSUE TITLE
package have wrong version

### ISSUE THREAD

**Issue by qingzi-king** [facebook/react#14985]
package.json have wrong version.
The current release is 16.8.3, but the package.json version is 16.6.1.

**Comment by dani97** [comment]
yes agree even wrong version in 16.8.3 branch

**Comment by monkindey** [comment]
Can we remove [version](https://github.com/facebook/react/blob/master/package.json#L3) field ?

**Comment by bvaughn** [comment]
> Can we remove version field ?

That would be my vote, yes. The root package version isn't really meaningful.
