### ISSUE TITLE
If React Hooks surport useState(await ...) to getData,we can used in ssr be better

### ISSUE THREAD

**Issue by dazjean** [facebook/react#14986]
I am new gay。
we konw  `Hooks can only be called inside the body of a function component`,but  if hooks can suppert it  we can easy get Default data in ssr,becauces  effect not be call by ssr

Example
```
let APP =  async() => {
    let initState = async () => {
        let response = await fetch('http://localhost:9991/mock/count.json');
        let listData = await response.json();
        return listData.count;
    };
    const [count, setCount] = useState(await initState());
    return (
        <div>
                <span>Count:{count}</span>
        </div>
    );
};


```

**Comment by gaearon** [comment]
This is planned — although not with this specific API.

https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#suspense-for-server-rendering
