### ISSUE TITLE
Misleading error description when using wrong useRef

### ISSUE THREAD

**Issue by madroneropaulo** [facebook/react#14980]
There's a misleading error when using wrong the `useRef` hook.

```
function MyComponent() {
    let nameRef = useRef();

   return (
      <div>
        <input ref="nameRef" type="text" />       
    </div>
  );
}
```

See the example here https://codesandbox.io/s/yvl21qm62j

The code above leads to this error `Function components cannot have refs. Did you mean to use React.forwardRef()?`. I'm moving some class components to Hooks, and stumbled upon this, and it took me a while due to the wrong error message.

**Comment by gaearon** [comment]
Runnable example please? Such as CodeSandbox.

**Comment by madroneropaulo** [comment]
@gaearon Just updated the post.

**Comment by huubvKaopiz** [comment]
sửa thành như này là đc nè: 
import React, { useState, useRef } from "react";
import ReactDOM from "react-dom";

function App() {
  let nameRef = useRef();
  return (
    <div>
      <input ref={nameRef} type="text" />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by huubvKaopiz** [comment]
import React, { useState, useRef } from "react";
import ReactDOM from "react-dom";

function App() {
  let nameRef = useRef();
  return (
    <div>
      <input ref={nameRef} type="text" />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by huubvKaopiz** [comment]
<input ref="nameRef" type="text" /> => <input ref={nameRef} type="text" />

**Comment by huubvKaopiz** [comment]
"<input ref="nameRef" type="text" />" => "<input ref={nameRef} type="text" />"

**Comment by huubvKaopiz** [comment]
ref="nameRef" => ref={nameRef}

**Comment by TienDo1011** [comment]
@huubvKaopiz He already knows how to fix it. This error looks misleading to me, too.

**Comment by threepointone** [comment]
Huh, it looks like the issue shows up even without useRef, by simply using a string ref on `<input/>`. This looks like an actual bug.

**Comment by natejcho** [comment]
What about an error message like "Function components cannot have string refs. Did you mean to use React.useRef()?

**Comment by natejcho** [comment]
To be clear, this would only be if a function component uses a string ref.

i think the initial error still has use

**Comment by klujanrosas** [comment]
@threepointone I experienced this today as well when trying to conditionally pass a `ref` like

```jsx
function MyApp() {
  const ref = React.useRef();
  const someCondition = false;

  return <div ref={someCondition && ref} />
}
```

React is right on throwing the error, but the message is indeed a bit misleading.

Would it be a possibility to exclude/handle boolean types from `coerceRef` here? 

https://github.com/facebook/react/blob/54f66731c84e3f141a1c0bc5d32be7cc5d4b9bbf/packages/react-reconciler/src/ReactChildFiber.js#L112-L116

**Repro:**
https://codesandbox.io/s/misleading-ref-error-rc2ed

**Comment by lynellf** [comment]
I do agree in which the error is misleading or outdated. Prior to hooks, using refs wasn't possible?

So, this error isn't about "Function components cannot have refs", but rather there's an invalid configuration?

**Comment by bl00mber** [comment]
Changed in #18031

**Comment by okmttdhr** [comment]
This issue seems to be solved by https://github.com/facebook/react/pull/18031

**Comment by eps1lon** [comment]
On the flip side, it still mentions function components which `<input />` isn't.
