### ISSUE TITLE
Throwing Error from hook not caught in error boundary 

### ISSUE THREAD

**Issue by joepuzzo** [facebook/react#14981]
This may be more of a question than an issue but is it possible to throw errors in a hook and have them caught in an error boundary? Or will this not work?

**Comment by gaearon** [comment]
What have you tried?

**Comment by joepuzzo** [comment]
So basically I created a hook that wraps apollos client.. and I tried to throw from that hook. See code below: 

```
import React, { useState, useContext, useEffect } from 'react';
import { ApolloClientContext } from '../../context/context';

const useQuery = ({ query, variables }) => {

  const client = useContext(ApolloClientContext);

  const [loading, setLoading] = useState(true);
  const [data, setData] = useState();
  const [error, setError] = useState();

  const fetchData = async (params) => {
    setLoading(true);
    setError(undefined);
    try {
      const { data: result } = await client.query(params);
      setData(result);
    }
    catch (e) {
      // THIS IS THE IMPORTANT LINE
      if( e.type === 'some type where i want to throw') throw(e)
      setError(e);
    }
    setLoading(false);
  };

  useEffect( () => {
     console.log('FETCHING DATA');
     fetchData({
       query,
       variables
     });
  }, []);

  return {
    loading,
    data,
    error,
    query: fetchData
  };
};

export default useQuery;
```

**Comment by joepuzzo** [comment]
Here is intended use case:
```
import React, { useState } from 'react';
import { useQuery } from '../../hooks';

const ComponentWithHook = ({
  foo
}) => {

  const {
    loading,
    data,
    error
  } = useQuery({
    query: SOME_QUERY,
    variables: { foo },
  });

  return (
    <SomeViewComponent 
      loading={loading}
      data={data}
      error={error}
    />
  );
};

class MyErrorBoundary extends React.Component {

  constructor(props) {
    super(props);
    this.state = {};
  }

  componentDidCatch(error, errorInfo) {
    this.setState({
      error
    });
  }

  render() {

    return (
      {error : <small>Ahh there was an error</small> : <ComponentWithHook foo="bar" />}
    );
  }
}
```

**Comment by PierreAndreis** [comment]
@joepuzzo 
I am either doing something wrong or unable to replicate: https://codesandbox.io/s/24l03vz15j?fontsize=14

**Comment by joepuzzo** [comment]
Mine is async...  could that be the issue?

**Comment by joepuzzo** [comment]
Oh wait so is yours

**Comment by PierreAndreis** [comment]
@joepuzzo I see. 
The issue here maybe is that you are not awaiting this code inside the hook, so react moves on before it should. (please someone correct me if i'm wrong)
```
  useEffect( () => {
     console.log('FETCHING DATA');
    // this should await here so useEffect awaits for the resolution of the promise
     fetchData({
       query,
       variables
     });
  }, [])```;

**Comment by joepuzzo** [comment]
You're right.. im not awaiting.. however when i add that, react barfs at me saying  "Warning: An Effect function must not return anything besides a function, which is used for clean-up.
"

**Comment by joepuzzo** [comment]
So I'm assuming this is bad behavior then? And there is a better approach.

**Comment by PierreAndreis** [comment]
Now i don't know if error boundaries not catching errors that happens inside async function called from useEffect is by design or not. It makes sense from what I can tell

**Comment by gaearon** [comment]
React can’t catch them — just like it wouldn’t catch errors from async class methods.

You can, however, do a trick like this:

```js
setState(() => {
  throw new Error('hi')
})
```

That should do what you want, both in classes and with Hooks.

**Comment by joepuzzo** [comment]
hmm sneaky but I like it lol

**Comment by iwilson-r7** [comment]
@gaearon The combination of that approach, but using the preferred `getDerivedStateFromError` instead of `componentDidCatch` and rendering a child component when the error boundary is triggered causes `Uncaught Invariant Violation: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.` instead of rendering the fallback UI

See the modified code sandbox: https://codesandbox.io/s/2wwj41v7on

Is there something unsupported about this approach?

Swapping `getDerivedStateFromError` back to `componentDidCatch` fixes it, so it seems like a bug

**Comment by FredyC** [comment]
@iwilson-r7 Just encountered the same issue. Interestingly enough, it works correctly in a production build without any hiccups. But it is certainly annoying in development as making a mistake basically throws away everything, not even dev error overlay is shown, just console message which is not helpful at all.

**Comment by zeg-io** [comment]
https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html?utm_source=reactnl&utm_medium=email

Error Boundaries aren't supported in React Hooks yet :(

**Comment by techieshark** [comment]
In case anyone lands here using hooks, here's what I'm using, since we don't have `setState`. If folks know a better way to propagate the error I'd love to know.

```
import React, { useReducer } from "react";

const initialState = {};

function reducer(state, action) {
  if (action.type === 'error' && action.error) {
    throw action.error;
  }
}

function Component() {
  const [state, dispatch] = useReducer(reducer, initialState);

  useEffect(() => {
      memoizedCallAPI().then((response) => {
        // handle good response
      }).catch(error => {
        dispatch({ type: 'error', error });
      });
  }
```

**Comment by timothysantos** [comment]
Hi @techieshark , what do you mean by your update? Are you replacing useReducer to useState to throw errors?

**Comment by techieshark** [comment]
@timothysantos originally i incorrectly thought I could only use the `useReducer`, but later realized `useState` works as well. Both seem to work, but `useState` alone seemed simpler if the reducer / dispatch functionality is not also needed.

So in the end, with hooks, my full code looked like:

```
function Component() {
  const [/* state */, setState] = useState();

  useEffect(() => {
      memoizedCallAPI().then((response) => {
        // handle good response
      }).catch(error => {
        setState(() => {
         throw error;
         })
      });
  }
```

I hope that clarifies?

**Comment by bernardbaker** [comment]
Does anyone know how to stop the error stack showing up in the UI?

**Comment by backus** [comment]
This wont suit everyone's needs since this only works for ErrorBoundaries sitting at the top of your component hierarchy, but if you want to make sure your error boundary handles uncaught promise errors, you can use [`window.addEventListener("unhandledrejection")`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) like so:

```tsx
import React from "react";

export class TopLevelErrorBoundary extends React.Component<{}, { hasError: boolean }> {
  constructor(props: {}) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(_error: any) {
    return { hasError: true };
  }

  componentDidMount() {
    window.addEventListener("unhandledrejection", this.onUnhandledRejection);
  }

  componentWillUnmount() {
    window.removeEventListener("unhandledrejection", this.onUnhandledRejection);
  }

  onUnhandledRejection = (event: PromiseRejectionEvent) => {
    event.promise.catch((error) => {
      this.setState(TopLevelErrorBoundary.getDerivedStateFromError(error));
    });
  };

  componentDidCatch(error: any, errorInfo: any) {
    console.log("Unexpected error occurred!", error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return (
        <YourErrorViewHere />
      );
    }

    return this.props.children;
  }
}
```

---

Also I realize this is an old issue so sorry for noise of resurfacing. This is just one of the top results on Google now, so figured I would chime in 😅

**Comment by marksyzm** [comment]
I made this simple hook for if you want to opt into pushing an error to the boundary:
```jsx
import { useEffect, useState } from 'react';

export const useErrorBoundary = error => {
  const [, triggerErrorBoundary] = useState();

  useEffect(() => {
    if (error) {
      triggerErrorBoundary(
        error
          ? // throws error
            () => {
              throw error;
            }
          : // removes error
            undefined
      );
    }
  }, [error]);
};
```

**Comment by kwantdev** [comment]
> 

It would be great if somebody would explain why throwing inside a setState method allows ErrorBoundary catches the exception. Thanks!

**Comment by nevcos** [comment]
It would be great if React provided a clear API to catch an error in async scenarios. Being required to use `useState` for this is the opposite of clear and semantic code...

**Comment by nikkwong** [comment]
A huge problem with the

```javascript
setState(() => throw error)
```

approach is that it doesn't stop the execution of the component. So if you have something like this:

```javascript

let data = null;
try {
  data = await trigger();
  // setAccessToken(data);
} catch (e) {
  setUser(() => {
    throw e;
  });
}
console.log("data", data);
```

The last line will still execute, which is problematic for my use case (involving useSWR), where there really is no workaround. Can we get first class support for this case rather than this seemingly hacky workaround?

**Comment by aweebit** [comment]
Here is a `useReducer`-based solution involving a custom hook that I find very elegant:

```ts
function useErrorDispatcher() {
  const [, dispatch] = useReducer((_, error) => {
    throw error;
  }, undefined);
  return (error) => {
    dispatch(error);
    throw error;
  };
}

function Example() {
  const dispatchError = useErrorDispatcher();
  const [data, setData] = useState();

  useEffect(() => {
    getData().then(setData).catch(dispatchError);
  }, [data, dispatchError]);

  return <div>{data}</div>;
}
```

@nikkwong can you make use of this solution? I don't see why in your code, you cannot just throw directly after calling `setError`. That's basically what `dispatchError` does in my example.
