### ISSUE TITLE
[reconciler] re-instanciating object in commitUpdate

### ISSUE THREAD

**Issue by drcmda** [facebook/react#14983]
**Do you want to request a *feature* or report a *bug*?**

feature, this is for https://github.com/drcmda/react-three-fiber

**What is the current behavior?**

commitUpdate is supposed to simply update the instance, it seems that it cannot "exchange" the instance. 

**What is the expected behavior?**

I need to re-instanciate the instance, just writing props to it is not enough in my case. Basically i am trying this:

```js
  commitUpdate(instance, updatePayload, type, oldProps, newProps, fiber) {
    if (instance.isObject3D) {
      applyProps(instance, newProps, oldProps)
    } else {
      // This is a data object, let's extract critical information about it
      const parent = instance.__parent
      const { args: argsNew = [], ...restNew } = newProps
      const { args: argsOld = [], ...restOld } = oldProps
      // If it has new props or arguments, then it needs to be re-instanciated
      if (argsNew.some((value, index) => value !== argsOld[index])) {
        // First it gets removed from its parent
        removeChild(parent, instance)
        // Next we create a new instance and append it again
        const newInstance = createInstance(instance.type, newProps)
        appendChild(parent, newInstance)
        // Switch fiber node (???)
        fiber.stateNode = newInstance // <---- this doesn't work
```

This is a THREE data object which i am trying to map. Sometimes these objects cannot be mutated, THREE expects them to be re-created. One example of this is: https://threejs.org/docs/index.html#api/en/geometries/PlaneGeometry 

> Any modification after instantiation does not change the geometry.

I am creating the object in JSX like so:

```jsx
<planeGeometry name="geometry" args={[width, height]} />
```

When the args change the instance has to be recreated, no other way around unfortunately.

It would be amazing if commitUpdate would be allowed to return an instance. And if it does the reconciler writes it into the fiber node. I am trying fiber.stateNode here, but it doesn't help. Next time commitUpdate is called it passes on the old instance again, which doesn't have a parent any longer.

I don't really understand how these nodes work but the stacktrace says  

```jsx
commitWork(_current2, nextEffect)
```

where nextEffect ends up being "fiber" in the commitUpdate. "_current2" seems to be the one that still clings to the old stateNode.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.3

**Comment by drcmda** [comment]
Oh, i just tried something that did actually work:

```jsx
        // Switch fiber node
        fiber.alternate.stateNode = newInstance
        fiber.stateNode = newInstance
```

could i get a confirmation that this can be a viable way forward?

**Comment by gaearon** [comment]
No, changing fibers is not supported and can break things very badly. 

You can, however, make your “instance” a plain object that *contains* a Three node. Then you can do anything with it, including recreating it when necessary.

**Comment by drcmda** [comment]
it wouldn't change the ref, though, just the stateNode, but you're completely right, i shouldn't mess with fiber. do you mean doing it like a ref.current? that could actually work. i never see this stuff ... 🤯 thanks again dan!

**Comment by gaearon** [comment]
No, I mean that your “instance” you create in `createInstance` doesn’t literally have to be a Three instance. It can be a wrapper object like `{ threeNode: ... }`. This lets you replace it later in `commitUpdate` if needed.

**Comment by drcmda** [comment]
that worked perfectly!

**Comment by drcmda** [comment]
@gaearon this has now created another problem, users fetching refs on these objects now get served the wrapper:

```jsx
<mesh ref={mesh}>
  <geometry ref={geo} />
```

`mesh` will point to the actual object in the scene, `gem` will point to the wrapper, which is really confusing. Is there something in reconciler that allows me to get in between react and the enduser for served refs? If not, can it please be made? Otherwise the api isn't gonna work. I will be forced to wrap all objects just for consistency.

**Comment by gaearon** [comment]
That’s what `getPublicInstance` host config method should let you do. 

```
getPublicInstance(node) {
  return node.threeNode;
}
```

**Comment by gaearon** [comment]
Although I guess that wouldn’t update it. ☹️

**Comment by gaearon** [comment]
I guess the canonical solution in your case is wrapper components. Like in React Native.

```js
const PlaneGeometry = React.forwardRef((props, ref) => {
  const key = props.args.width + ':' + props.args.height;
  return <planeGeometry {...props} key={key} ref={ref} />;
});
```

Then you don’t need wrappers internally and your refs are clean. But some components would have to be imported.

```js
import { PlaneGeometry } from 'package'
```

The upside of this is it lets you add some nicer API on top if you want without complicating your reconciler config.

If you go this way it would probably make sense to do for all primitives and not just special ones.

**Comment by drcmda** [comment]
@gaearon  That is what i would like to avoid, because THREE has hundreds of objects i would need to ship and maintain, they're constantly changing stuff around. That's mainly because i could do in 3 days what react-three couldn't do in a year.

I've tried getPublicInstance and you're right, it works, but then doesn't update.

  const [vec, setVec] = useState([1,2,3])
  const vecRef = useRef()
  useEffect(() => void setTimeout(() => setVec([4,5,6]), 4000), [])
  useEffect(() => void console.log("REF ->", vecRef), [vec]) // will be [1,2,3] two times ...

  return (
    <>
      <vector3 ref={vecRef} args={vec} />

**Comment by gaearon** [comment]
So how many of those objects are weird like this and need to be recreated?

**Comment by gaearon** [comment]
Also you don’t literally have to define them all. You can generate them by walking over Three exports. And only write the ones that have manual logic.

**Comment by drcmda** [comment]
It's not just the ones that three provides (which are many, + the examples folder which contains shaders, effects, etc), all stuff i wouldn't like to touch normally because it creates references that will kill tree shaking. But worse, you can make your own arbitrary ones and it's very normal in the three eco system to extend existing classes and so on. it's kind of the wild west and the lib comes from the IIEF time. With the <primitive object={...} /> element i basically allow them to dynamically include any object.

**Comment by gaearon** [comment]
Sorry, I don't see how treeshaking fits into this.

I'm saying you can do 

```js
Object.keys(THREE).forEach(key => {
  YourLib[key] = createWrapperComponent(key);
})
```

Not *literally* that but it should give you an idea. I don't see how tree shaking is relevant here. Alternatively, you could export a Proxy that lazily creates component wrappers when its properties are accessed. If this doesn't work, please provide an example why.

**Comment by drcmda** [comment]
a proxy seems like too much overhead for something that simple tbh. i just wanna exchange an instance. 😔

exporting all objects as wrapped classes just doesn't seem right as well. half of the objects in three are arbitrary, extras, examples/postprocessing or userland class extensions. I wouldn't want to force users to import classes from my lib.

right now i am thinking, i could mutate the fiber instance and live dangerous. or force them to do ref.current.object - both seem better than proxies and object exports.

**Comment by gaearon** [comment]
What overhead do you mean? It's something like three lines of code:

```js
function createWrapper(name) {
  return 'wrapper for ' + name;
}

let Lib = new Proxy({}, {
  get(target, prop, receiver) {
    return createWrapper(prop);
  }
});

console.log(Lib.geometry) // 'wrapper for geometry'
console.log(Lib.bazinga) // 'wrapper for bazinga'
```

**Comment by gaearon** [comment]
Maybe you misunderstood. I didn't mean a Proxy for the instances. I meant a Proxy for exports. So that people can write `YourLib.ArbitraryName` and get an object representing `<arbitraryName>`.

**Comment by drcmda** [comment]
wouldn't that exclude ie11, or warrant polyfills (if they even exist, i don't know)?

**Comment by drcmda** [comment]
I mean, instance re-instanciating is normal, no? isn't this something reconciler should just support? i guess it would be a tiny mapping function or something of the sort and it's solved for all. three won't be the only platform that warrants this.

**Comment by gaearon** [comment]
>wouldn't that exclude ie11, or warrant polyfills (if they even exist, i don't know)?

Does THREE work there? I'm not very familiar. Yes, proxies wouldn't work in IE but I assumed you're targeting modern browsers.

>three won't be the only platform that needs it.

So far all other platforms were happy with exporting wrapping components that contain extra logic like this. This is the first time this problem comes up which is why I'm pushing back.

>It could be something that reconciler supports with a tiny mapping function

It's rarely "tiny" when we're talking about changing the reconciler. :-) Changes like this have downstream effects. It's not obvious to me that it would be a simple change but I'm not sure. If you send a PR implementing it we can think about it.

**Comment by drcmda** [comment]
yes, three works in ie11. the reconciler is a company thing i am making for a tooling application, but doing it open source so that others can benefit too, but at least in my case i can't shut out ie.

>  If you send a PR implementing it we can think about it.

I will study the source a little and see if i can understand it good enough.

> which is why I'm pushing back.

Appreciate the discussion and time, totally understand your concerns.

**Comment by gaearon** [comment]
How many of those special objects are there?

You could allow to normally use `<thing />` but when a special one is used, warn to use imported `<Thing />` instead.

**Comment by drcmda** [comment]
ran a map over the default exports, there are 48 Object3D's and 363 raw objects that could need re-instantiation. but that's just the default export, would be a whole bunch more when traversing the extras.

going through the source right now and i see now that just mapping the ref isn't going to work, `commitAttachRef` is only called once. now changing stateNode in the fibers after `commitUpdate` would be a way, but is there any explanation why there are always two, fiber and fiber.alternate. is `stateNode` present stored anywhere else or can it be safely exchanged inside the reconciler?

**Comment by gaearon** [comment]
>ran a map over the default exports, there are 48 Object3D's and 363 raw objects that could need re-instantiation. but that's just the default export, would be a whole bunch more when traversing the extras.

Looping over 300 items once is very fast. You don't have to actually instantiate the wrappers — you can define getters which do that lazily.

**Comment by sompylasar** [comment]
@gaearon THREE library components and modules are not uniformly structured and exported, so the recurring effort is not in the loop itself but in the maintenance of that loop.

**Comment by gaearon** [comment]
Can you always do something like this then? `<node type={THREE.Thing} />`

**Comment by drcmda** [comment]
I have thought about it, but decided against it in the beginning because it thrashes the syntax a little bit. To put a clean `<geometry />` under a `<mesh>` would be quite the nice experience. I do have `<primitive object={} />` but for already instantiated things like textures that get created by loaders imperatively.

**Comment by gaearon** [comment]
I think I stand by saying the canonical solution is to provide wrapping components for the ones that need special logic like this. You're free to try other things (like patching `stateNode` or sending a PR) but all guarantees are off and you might find gnarly unfixable bugs later.

**Comment by drcmda** [comment]
That's alright with me. i'm trying a PR and let's see if that creates some deeper discussion. If not, it's not the end. Thanks again! : )

**Comment by gaearon** [comment]
I’m curious what was the outcome of this. Have you kept the stateNode hack, or did you find another solution?

**Comment by drcmda** [comment]
> I’m curious what was the outcome of this. Have you kept the stateNode hack, or did you find another solution?

I didn't catch the comment before, only now where i am going through some cleanup phase. Yes i have kept the hack, i am exchanging stateNodes

```jsx
    // This evil hack switches the react-internal fiber node
    // https://github.com/facebook/react/issues/14983
    // https://github.com/facebook/react/pull/15021
    ;[fiber, fiber.alternate].forEach((fiber) => {
      if (fiber !== null) {
        fiber.stateNode = newInstance
        if (fiber.ref) {
          if (typeof fiber.ref === 'function') (fiber as unknown as any).ref(newInstance)
          else (fiber.ref as Reconciler.RefObject).current = newInstance
        }
      }
    })
  }
```

it seems to work fine and allows me to have a clean jsx notation. although it would be nice if `getPublicInstance` would not be stale.

**Comment by drcmda** [comment]
@gaearon thinking about this some more, is there any reason why getPublicInstance is only called once? if it would be called every time the ref is requested that would 100% solve the issue. 😊

**Comment by ashconnell** [comment]
@drcmda i'm running into the same problem in my reconciler, and the more I think about it, the more I think the React Native way is the better solution.

When r3f re-instantiates instances there is a big ceremony around reconnecting all the child instances to the new instance – bypassing all the stuff that React should arguably doing for you – including the hack to rewire the fiber itself.

If all of the types were instead a wrapper component with a `key` prop, React would automatically rebuild instances and the ceremony and hack would no longer be required.

AFAICT, the only signal to rebuild an instance in r3f is when the diff on the `args` prop changes. So the wrapper component could be quite generic, eg:

```js
const BoxGeometry = React.forwardRef((props, ref) => {
  const key = props.args.join(':')
  return <boxGeometry {...props} key={key} ref={ref} />
})
```

In this ^ example, the args are numbers so the key is easy to compute.
Other types might use args that are classes/objects, so you would need some kind of equality check to provide a new key:

```js
const RenderPass = React.forwardRef((props, ref) => {
  const x = useRef()
  const key = React.useMemo(() => {
    if (!x) {
      x.current = { n: 0, args: props.args.slice() }
      return x.current.n
    }
    if (!isShallowEqual(x.current.args, props.args)) {
      x.current.args = props.args.slice()
      x.current.n++
    }
    return x.current.n
  }, [props.args])
  return <renderPass {...props} key={key} ref={ref} />
})
```

Obviously this would mean a breaking change to r3f from using `<renderPass/>` to `<RenderPass/>` etc
