### ISSUE TITLE
Suspended component's state gets reinitialized after Promise resolves

### ISSUE THREAD

**Issue by alexkirsz** [facebook/react#14999]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

A stateful functional component gets suspended by throwing a Promise. When the Promise resolves, the component gets re-rendered as expected, but its state gets reinitialized.

**CodeSandbox**

https://codesandbox.io/s/5058xyw5p4 (Open the console)

**What is the expected behavior?**

State is preserved from one render to another, regardless of what happens after calling the hook.

A simple workaround is to hoist state up to a parent component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React/ReactDOM 16.8.3
Tested on Chrome and Firefox on macOS
Haven't tried with any previous version

**Comment by gaearon** [comment]
This is a expected behavior. Suspense is meant to be used with a cache that’s external to the component state.
