### ISSUE TITLE
Unexpected "Hooks can only be called inside the body of a function component."

### ISSUE THREAD

**Issue by FabianoLothor** [facebook/react#14995]
I already know why this problem occurs.

But I'm needing for one solution to my case.

I have three packages: a `Lib A`, and the `Project A` and `Project B`.

The projects use `Lib A`

If I generate a `Lib A` bundle and run the `Project A` or the `Project B` with this bundle, I receive this message: `Unexpected "Hooks can only be called inside the body of a function component."`

Actually I can solve this with this command:

`npm link ../project-a/node_modules/react` (In `Lib A` package)

Now, when I run the `Project A`, the error message isn't appear.

But the problem isn't solved in the `Project B`.

To solve this in the `Project B` i need execute the same steps, and... It is a sucks :'(

Is it possible solve this?

I know that the error is because the two instances of React, but... How can I solve the problem?

**Comment by gaearon** [comment]
This is more of a question about npm/yarn/bundling so I suggest to refer to their resources. For example you could force your bundler to always resolve `react` from your app's `node_modules`. Or write a script that does the linking. Or use Yarn Workspaces to hoist `react` up the tree. The exact workaround is up to you but it's not strictly saying related to React so I'll close. Feel free to continue discussing here.
