### ISSUE TITLE
Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

### ISSUE THREAD

**Issue by jerry-f** [facebook/react#15001]
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

This error has been reported, tried many methods, but still unable to solve

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
