### ISSUE TITLE
Invariant Violation: Minified React error #307

### ISSUE THREAD

**Issue by Damdias** [facebook/react#15010]
I am getting below error when try host app with production build, I have used new React Hooks.

Invariant Violation: Minified React error #307; visit https://reactjs.org/docs/error-decoder.html?invariant=307 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by TienDo1011** [comment]
Follow these may help you in chasing the error root cause out: https://reactjs.org/warnings/invalid-hook-call-warning.html

**Comment by gaearon** [comment]
Have you tried following the links? Hope this helps.

![clicking on a link](https://d2aztkdj0ezvrk.cloudfront.net/items/0I100c0k011Q0U3h0A2k/Screen%20Recording%202019-03-05%20at%2003.06%20PM.gif?v=1dc537cb)

**Comment by gaearon** [comment]
(The final URL that describes possible causes is: https://reactjs.org/warnings/invalid-hook-call-warning.html)

**Comment by TaylorPzreal** [comment]
一般是因为你的项目的react版本，低于使用的第三方库依赖的react的版本造成的，可以将工作项目的react版本升级，或降低依赖库的react版本。

**Comment by deligent-ant** [comment]
i have did as your said, just like . " aside of making React and react-dom peer deependencies in your libraries package.json, you also should mark them as 'externals' when building them with webpack"
but the #321 still exist,who can help me.
```js
"peerDependencies": {
    "antd": "^3.25.0",
    "styled-components": "^4.4.1",
    "react": "^16.11.0",
    "react-dom": "^16.11.0"
  }
```

```js
 externals: [
    // nodeExternals(),
    {
      react: {
        root: 'React',
        commonjs2: 'react',
        commonjs: 'react',
        amd: 'react'
      },
      'react-dom': {
        root: 'ReactDOM',
        commonjs2: 'react-dom',
        commonjs: 'react-dom',
        amd: 'react-dom'
      }
    }
}
```
if i don't use useCallback ant useMemo ,it can work,but i need useMemo...

**Comment by phinguyen202** [comment]
Should be reopened. This still occur on v16.8.2.
I figure out that when using webpack to bundle, the line to declare useState threw an error, for instance:
`var _b=(0,react.useState)(0)`
