### ISSUE TITLE
TypeError: nextDeps.join is not a function

### ISSUE THREAD

**Issue by rockfight** [facebook/react#15016]
I am getting this error while using hooks. 
![image](https://user-images.githubusercontent.com/902571/53800806-aab8df00-3f65-11e9-8357-73774694b275.png)

This is related code.

`const market = useContext(MarketContext); `
` useEffect(() => {`
  
      nav.items[1] = {
                     name: 'Market',
                    url: '/market',
                    icon: 'icon-speedometer',
                    badge: {
                           variant: market == "Live" ? "primary" : "secondary",
                    text: market,
               }
      };    
 `},  market)`

**Comment by TienDo1011** [comment]
Can you provide a codesandbox sample of the error?

**Comment by gaearon** [comment]
You probably meant to pass `[market]` rather than `market` as `useEffect` argument.

**Comment by gaearon** [comment]
I'll close but I'm sending https://github.com/facebook/react/pull/15018 to add a warning for this.

**Comment by rickhanlonii** [comment]
@coder054 the check was also added to `useMemo`, are you sure your React version is up to date?
