### ISSUE TITLE
DOM tree normalization causes React to enter an irrecoverable error state

### ISSUE THREAD

**Issue by paton** [facebook/react#15014]
Reproduction:
1) Open any React site that has a variable adjacent to other text
2) Type document.body.normalize() into javascript console
3) React enters an irrecoverable error state

This was previously raised by @sebmarkbage in issue #9836.

The deciding factor of whether React should support [Node.normalize](https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize):
`The resolution is that we'll ship a version to see how badly this breaks and under which conditions to get more data.`

Now that React 16 has long been shipped, there is an overwhelming amount of issues that are related to React's inability to function when the DOM is in a normalized state. My suspicion is that very few javascript engineers (and even fewer React developers) are familiar with DOM tree normalization, which results in many related issues being opened that are never attributed back to the decision whether React should work when the DOM tree is normalized.

At one point, an issue was submitted addressing the fact that React's own website breaks in Chrome: https://github.com/facebook/react/issues/12460 which is an issue that also links back to #11538.

#11538 is an issue getting a lot of attention (based on the number of people who send me links to it, including engineering managers from Fortune 500 companies in connection with services we provide)

That ticket was closed with the final comment from @gaearon saying `Since there's nothing else that I can see actionable here, I'm closing this.`. 
@gaearon's final take on issue #9836 that originally addressed whether normalization is important to support was `¯\(ツ)/¯`

The decision was clearly made haphazardly (and without the data we have now, that haphazard decision was likely appropriate back then.) But looking back at the issues that stemmed from that decision, I think it appropriate to reconsider this.

In issue #11538 @gaearon correctly raised the point that the problem might be related to issue #9836 (2nd comment down) that debated whether normalization should be supported.

PR https://github.com/facebook/react/pull/9853 was opened in 2017 by @sebmarkbage to remove tests relating to DOM normalization. The description of that PR: `According to #9836 we're intentionally choosing to not support this until we have better proof of this being a big need. E.g. to protect against extensions. In a way that it's not better to push extensions to be fixed.`

issue https://github.com/facebook/react/issues/11538  was worthy enough to warrant the attention of Chromium developers, with React maintainers requesting that chromium *change the Chrome browser to accommodate React limitations* https://bugs.chromium.org/p/chromium/issues/detail?id=872770

That Chromium ticket may appear as though DOM normalization isn't related, but if you consider what would need to happen for that ticket to be resolved, DOM normalization becomes very relevant, if not necessary. See [Comment 9](https://bugs.chromium.org/p/chromium/issues/detail?id=872770#c9) and more directly relevant, [Comment 12](https://bugs.chromium.org/p/chromium/issues/detail?id=872770#c11).

I could go on, but instead I'll include a list of tickets that (in 10 minutes time) I could find to be attributed to React's inability to function when the DOM is in a normalized state. (I fully assume this issue won't change anyone's mind, but at the very least, changelogs and documentation should clearly state this as a limitation to be aware of before deciding to use React, and before deciding whether to upgrade to React 16),

Related issues:
https://github.com/reactjs/reactjs.org/pull/1148 - A pull request to the reactjs.org website that attempts to solve the problem by *overwriting methods on the Node prototype, which is horribly inadvisable* (according to a simple google search, not my opinion)
Another one: https://github.com/WoWAnalyzer/WoWAnalyzer/issues/948
Another https://github.com/facebook/react/issues/11774
Another: https://github.com/facebook/react/issues/13278
Another: https://github.com/facebook/react/pull/13341
Another: https://github.com/facebook/react/pull/13347
Another: https://github.com/reduxjs/react-redux/issues/982
Another; https://github.com/facebook/draft-js/issues/1320
https://github.com/draft-js-plugins/draft-js-plugins/issues/1124
https://github.com/facebook/react/issues/9134
https://github.com/eight04/linkify-plus-plus-core/issues/2

(While not all of the above specifically say "this is caused by not supporting normalization," the truth is most all of them are indirectly a result of React's decision to use un-normalized adjacent text nodes as boundaries in certain scenarios, where in previous version of React, these boundaries were achieved with comment nodes, and in other version, span wrappers -- it's absolutely possible to achieve support for normalization of the DOM, but doing so would require re-implementing how React creates boundaries where within a text string)

Following are more specific reproduction steps to show how easily a basic react app will completely fail with a single line of code (which can come from a chrome extension, the browser itself in the case of Google Translate, 3rd party libraries, other javascript frameworks, etc... 
```
- Open the demo link from the original ticket (https://nn92zy7240.codesandbox.io/)
- Click the button once
- In the javascript console run document.body.normalize(); 
- Click the button again.
- The text on the page disappears
- Click the button again.
- The button on the page disappears (page is fully broken at this point)
```

To me, this issue highlights how brittle React is (particularly when seeing how easy it is to kill the above react example with a single DOM normalization operation).

(I'm unsubscribing from this thread in anticipation of backlash -- I currently don't use React, and am posting this due to the number of complaints I've received from other developers running into issues caused by how React must maintain adjacent un-normalized text nodes (which prevents React from supporting Node.normalize)

**Comment by sebmarkbage** [comment]
Note that the core issue isn’t whether React can break during normalization but whether how much it also breaks for other reasons during the same scenarios normalization is typically used.

For example during translation and phone number finding extensions, text nodes are reordered and/order split across elements in a way that React doesn’t know about.

Adding back the comment nodes doesn’t fix all those issues. We’d have to have data that this will solve a significant chunk of the problems.

Sure, this is a fragile part of React but it is even with the proposed fix.

How can we fix this in the DOM in a way that React can work properly with translations and other extensions in general?

**Comment by sebmarkbage** [comment]
One thing that other libraries can do is attach a Shadow DOM to the nodes it wishes to translate. In fact this seems like the perfect use case for Shadow DOM since it hides the implementation details of the real DOM.

**Comment by paton** [comment]
> One thing that other libraries can do is attach a Shadow DOM to the nodes it wishes to translate. In fact this seems like the perfect use case for Shadow DOM since it hides the implementation details of the real DOM.

React is used in a tiny subset of production web applications (excluding facebook). Other libraries, chrome extensions, browser developers should be able to create cool software without having to worry about "breaking the rules" that React imposes on its users (especially when the "rules" that must be followed to coexist with React are decided in threads like [this](https://github.com/facebook/react/issues/9836#issuecomment-334269526).)

Software that must coexist with other software should be self-contained or built in a way that has appropriate safeguards to avoid the need to tell every other developer things like "You must use shadow DOM because I use React!" The people who'll suffer the most from comments like this are React users. In reality, an overwhelming percent of the internet is not built on React, and therefore the overwhelming number of developers writing code outside of the React world won't bother jumping through hoops to overcome arbitrary restrictions like "Never normalize the DOM tree."

> text nodes are reordered and/order split across elements in a way that React doesn’t know about
> How can we fix this in the DOM in a way that React can work properly with translations and other extensions in general?

1) Leverage MutationObserver [1]. At a minimum, this should be implemented for debugging purposes to flag scenarios where React loses reference to a Node.

2) Overwrite cloneNode, replaceChild, and other methods [2] to add logic necessary for React to prevent its virtual dom representation (or its references to nodes) from diverging from the actual (not virtual) DOM.

[1] Quoting a React maintainer in the Google Translate [Chromium "bug" ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=872770): _"One suggested solution was use MutationObserver to look for characterDataChanges, but we would still have to re-parent everything and this is slow and and also a very specific introduction to all of react to fix a problem that Google Translate introduces."_ - React maintainers are already aware that solutions exist. But the reality is React will never agree to implement MutationObserver. The 5ms overhead isn't worth the cost (for the 0.01% of React users who use React to power multi-billion dollar news feeds)

[2] I don't like the idea of overwriting the prototype. But it's a solution that, combined with MutationObserver, *could* solve almost all issues of this type. React maintainers will probably say this is not possible or it wouldn't work, but it would if there weren't an extreme necessity to ultra-optimize down to the millisecond. 

These problems are easy to solve if you're not trying to build a framework to power a multi-billion dollar web app where 10ms of render time saved equates to $50m in new ad revenue. It's difficult to propose solutions to problems like this when there's an extreme preference for speed over function. (And I'm not suggesting anything that would add 500ms of overhead, I'm talking solutions with < 75ms of added overhead - any solution with even 50ms of overhead would be shot down.)

------------------

I really am not intending to offend anyone or start a debate, to be clear.

The main issue I have with React is that most developers don't know what they're signing up for when they use React. React doesn't clearly explain what you can and cannot do when using React. Changelogs do not highlight major breaking changes like the inability to normalize the dom tree in React 16.

This results in all React users accidentally finding themselves in a position where they're limited in what they can and cannot use. And in the case of Google Translate, they're limited to who they can serve their application to and who they can't (cutting off Google Translate in Chrome, which you have to do if you use React, also cuts off the rest of the world from using your app). 

Half of the solution here is making React more resilient when it must coexist with others. The other half of the solution is disclosing to new React users all of the unwritten rules and restrictions that you agree to when using React.

**Comment by sebmarkbage** [comment]
Look, the general issue here applies to jQuery, lots of libraries and manually written DOM manipulation. The reason you don’t hear about them is because they’re broken in one off cases and nobody goes to report them in a centralized place.

The whole point of the Shadow DOM is because this general problem exists all over interop issues between legacy libraries, extensions, CSS rules etc. Exactly because you can try all you want trying to add defensive coding to libraries but that doesn’t prevent someone writing manual DOM manipulation code to have the same exact problem.

You comment also includes a bunch of irrelevant snark that sound like you’re trying to dismiss us as not valuing or having insight into how our framework is used. That’s not appreciated.

**Comment by paton** [comment]
Is it possible to solve the DOM tree normalization and Node.normalize issue by React leveraging Shadow DOM, where it would be protected from normalization on the real DOM?

**Comment by gaearon** [comment]
> Quoting a React maintainer in the Google Translate Chromium "bug" ticket

Tangential to the topic but I’m not sure why you’re saying the person who opened that ticket is a React maintainer. They’re not. As far as I remember, I reached out to someone who worked on Google Translate to inquire whether there is a possible solution that can be done there, and they opened the ticket. (For which I’m thankful as it started the discussion.)

>The 5ms overhead isn't worth the cost (for the 0.01% of React users who use React to power multi-billion dollar news feeds)

I’m sorry if my comments here or somewhere else upset you or gave you the impression that we make these choices lightly or don’t care about end users. I want to personally apologize for that. But the passive aggressive tone in your comments doesn’t contribute to this conversation, and I suggest we don’t carry it further. Thanks.

**Comment by paton** [comment]
>  I’m not sure why you’re saying the person who opened that ticket is a React maintainer.

From the Chromium ticket: `"The question from the React team is:"`

> I’m sorry if my comments here or somewhere else upset you or gave you the impression that we make these choices lightly or don’t care about end users.

I don't think that.

> But the passive aggressive tone in your comments doesn’t contribute to this conversation

@sebmarkbage @gaearon  I'll close this issue and will refrain from contributing any further (other than in the Chromium ticket, where I encourage you to contribute as well.)

Feel free to open a new issue in your own wording and writing style if you think other people would value a discussion around the fact that React breaks and cannot function when the Dom enters a normalized state.
