### ISSUE TITLE
componentDidMount + setState = Two valid but unequal nodes with the same `data-reactid`

### ISSUE THREAD

**Issue by syranide** [facebook/react#1501]
Kind of related: https://github.com/facebook/react/issues/1400

Just had a long debugging session with m4tthumphrey on IRC which turned out to be this issue. Moving `setState` to `componentWillMount` solved it.

I'm assuming this is the boiled down version of https://github.com/facebook/react/issues/1147

**Comment by smithCaoyifei** [comment]
fixed me
