### ISSUE TITLE
Use createRefs API for variable amount of elements

### ISSUE THREAD

**Issue by Chaoste** [facebook/react#15017]
Hi guys,

I want to report an improvement or a missing documented guidance (if there is already a solution to this problem). I couldn't find a solution so far by looking in the docs or other issues. The only related link to this problem might be this one where the solution is a hacky workaround which does not work for dynamic defined arrays: https://dev.to/ajsharp/-an-array-of-react-refs-pnf

*The actual problem:*
Before the new `createRef` API it was possible to create a map with the shape `{[id]: ref}`. In my render function I was able to to spawn a list of elements and store their reference in this map. For the new way of defining references I need to generate the "storage" for references in advance (in the constructor). Since my elements are defined and changed by props I would need to regenerate this collection of references each time before they are actually rendered. Since "componentWillUpdate" is deprecated I don't have a chance to recreate those references and link them in my render functions.

For more clarification on my problem here is a short example how this could work right now with componentWillUpdate: https://jsfiddle.net/zqxw6Lg4/3/

I need those references because I want to scroll specific components in this list afterwards.

Versions:
- react: "16.6.3"
- react-dom: "16.6.3"

Greetings,
Thomas

**Comment by gaearon** [comment]
You should use ref functions for this, not `createRef`. They give you more flexibility and you can implement any logic in them.

```js
<div ref={node => {
  // Put it anywhere you like
}} />
```
