### ISSUE TITLE
Unable to dynamically combined multiple applications each instantiating i18next (hooks error)

### ISSUE THREAD

**Issue by Icehunter** [facebook/react#15038]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Bug is related to this issue:
https://github.com/i18next/react-i18next/issues/765

Sample repo:
https://github.com/Icehunter/i18n-issue-app/tree/master

**What is the expected behavior?**

https://reactjs.org/docs/error-decoder.html/?invariant=307 does not happen.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.x
Chrome/Firefox
OSX

Didn't have to worry about it in previous versions as hooks weren't available.

If there's more info I can provide please let me know. The maintainer of react-i18next was able to reproduce the issue by making a simple hook in code.

**Comment by Icehunter** [comment]
Just a further note; I don't use hooks myself yet; but react-i18next does internally.

**Comment by bvaughn** [comment]
> Just a further note; I'm not actually using hooks at all.

If you're using `react-i18next` v10, then you're using hooks. (I'm not familiar with that project, but a quick glance at its source shows hooks usage.)

Looks like one of the maintainers of that lib [confirmed this](https://github.com/i18next/react-i18next/issues/765#issuecomment-470173144):
> it's a problem of using hooks in that way. You just got an issue with i18next as it's using a hook - the root problem is the usage of hooks in combination with your setup.

I don't think this is a React bug. Seems like the error message is indicating an unsupported runtime setup.

**Comment by Icehunter** [comment]
If I run them individually; it works fine. Actually even taking my basic app; and just putting a small effect in it gives me the same error. Do I need some special babel plugins for this???

I followed this:
https://reactjs.org/docs/hooks-effect.html

I get the same error. I haven't found documentation around webpack (latest) or create-react-app that says how this is and isn't enabled.

**Comment by bvaughn** [comment]
> Actually even taking my basic app; and just putting a small effect in it gives me the same error.

Can you share this smaller repro case with me? The repro you shared above is kind of large and I'm still tracing through it.

**Comment by bvaughn** [comment]
To be clear, if by "my basic app" you mean [this one](https://github.com/Icehunter/i18n-issue-app/blob/3aa25414845517195c3ec672e71c81501b9b42a2/version-ten/host/src/App.js#L43-L71) – it's expected that hooks won't work in that, because it's a class component.

**Comment by Icehunter** [comment]
@bvaughn I was just going to say that actually; I tested using a function and it works; but with a class it does not.

How would I go about solving this as I can't use functions for all of my components yet? The entry point to my app itself is a class component; and there's a myriad of mixed components throughout, some being functions, some being classes.

**Comment by Icehunter** [comment]
As en example:
```
  render() {
    const { hasError, error, info } = this.state;
    if (hasError) {
      return (
        <div>
          <pre style={{ display: 'none' }}>{error}</pre>
          <pre style={{ display: 'none' }}>{JSON.stringify(info.componentStack, null, 2)}</pre>
        </div>
      );
    }
    const { useRouter } = this.props;

    const content = useRouter ? <Router history={history}>{routes}</Router> : routes;

    return (
      <Provider store={store}>
        <EnvironmentContext.Provider value={this.environment}>
          <TreatmentContext.Provider value={this.treatment}>
            <ProUiThemeProvider theme={{}}>{content}</ProUiThemeProvider>
          </TreatmentContext.Provider>
        </EnvironmentContext.Provider>
      </Provider>
    );
  }
```

**Comment by bvaughn** [comment]
> How would I go about solving this as I can't use functions for all of my components yet?

You can use hooks in your function components, just not in your class components.

I don't think I understand what your repro is doing– why you're fetching components that way.

I also don't see any problem with your example above. `useRouter` _sounds_ like a hook but looks like a boolean, so the code above should be ok.

**Comment by bvaughn** [comment]
For example: https://codesandbox.io/s/km2kylx32v

It's okay for your app to be a mix of function components that use hooks and class components that do not use hooks. It's not okay for the class components to use hooks though.

**Comment by Icehunter** [comment]
> > How would I go about solving this as I can't use functions for all of my components yet?
> 
> You can use hooks in your function components, just not in your class components.
> 
> I don't think I understand what your repro is doing– why you're fetching components that way.
> 
> I also don't see any problem with your example above. `useRouter` _sounds_ like a hook but looks like a boolean, so the code above should be ok.

Because the team I came into decided not to use a single repo for everything; I'm working towards a single repo; just not there yet. I'll give the docs some more read though and see why this is exactly happening.

It only happens when I hosted a webpacked application from cdn into my own application; so there has to be something I guess in the tooling that is not compiling it in a friendly fashion. All components are using the latest react/react-dom/etc

**Comment by gaearon** [comment]
Did you read this *whole* page?

https://reactjs.org/warnings/invalid-hook-call-warning.html

**Comment by Icehunter** [comment]
@gaearon Yup!

Unless I'm missing something. In the version-ten example I'm just wrapping my component in:

```
export default () => (
  <I18nextProvider i18n={i18n}>
    <App />
  </I18nextProvider>
);
```
While I'm not using a hook; the provider does use one internal to that package. Running locally will be fine for just that one. Packed and deployed out to a CDN breaks it.

**Comment by bvaughn** [comment]
I think the problem is in how you're fetching the components source. (I didn't dig too much into the large repro because I don't have time this morning. A smaller one would be appreciated it.)

**Comment by Icehunter** [comment]
I'll try to make something smaller; but the components are 12 LOC each; the rest of it is setup files to build and get the sample up. Let me see what I can do. Thanks!

**Comment by Icehunter** [comment]
So I tested most of the bundlers; including rollup to generate a UMD package to be consumed by another application.

Same issue across them all; hooks throw an error. The resulting code that was compiled with rollup is:
```javascript
(function(global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined'
    ? (module.exports = factory(require('react')))
    : typeof define === 'function' && define.amd
    ? define(['react'], factory)
    : ((global = global || self), (global.Application = factory(global.React)));
})(this, function(React) {
  'use strict';

  function _slicedToArray(arr, i) {
    return _arrayWithHoles(arr) || _iterableToArrayLimit(arr, i) || _nonIterableRest();
  }

  function _arrayWithHoles(arr) {
    if (Array.isArray(arr)) return arr;
  }

  function _iterableToArrayLimit(arr, i) {
    var _arr = [];
    var _n = true;
    var _d = false;
    var _e = undefined;

    try {
      for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) {
        _arr.push(_s.value);

        if (i && _arr.length === i) break;
      }
    } catch (err) {
      _d = true;
      _e = err;
    } finally {
      try {
        if (!_n && _i['return'] != null) _i['return']();
      } finally {
        if (_d) throw _e;
      }
    }

    return _arr;
  }

  function _nonIterableRest() {
    throw new TypeError('Invalid attempt to destructure non-iterable instance');
  }

  var _jsxFileName = '/Users/rwilson/GitHub/Icehunter/i18n-issue-app/application/src/lib/index.js';
  var index = function() {
    var _useState = React.useState(10),
      _useState2 = _slicedToArray(_useState, 1),
      count = _useState2[0];

    return React.createElement(
      'div',
      {
        __source: {
          fileName: _jsxFileName,
          lineNumber: 7
        },
        __self: this
      },
      count
    );
  };

  return index;
});
```

The actual application code:
```
import * as React from 'react';
import { useState } from 'react';

export default () => {
  const [count] = useState(10);

  return <div>{count}</div>;
};

```

That's about as simple as I can get. I'll make a specific branch later that does this; have to make dinner.

**Comment by hamlim** [comment]
I haven't checked out the sample repo yet, but my hunch is that [this line](https://github.com/Icehunter/i18n-issue-app/blob/master/version-ten/host/src/App.js#L23) is pulling in the vendor chunk which has React bundled in with it ([see here](https://github.com/Icehunter/i18n-issue-app/blob/master/version-ten/application-one/dist/application-one.vendors.af59ab3d7d8604c2c9fc.chunk.js)), causing multiple versions of React to be loaded on your host application.

This causes the error to be thrown by React because in order for hooks to work properly they need the same instance of React to reference, so loading multiple instances of React can cause them to get out of sync.

**Comment by Icehunter** [comment]
... so CRA was internally packing react; and the included one on the index.html was colliding... our dynamic fetcher also was for some reason packing react.

I've since updated everything to get rid of these "double packing" and it works as expected now. Sorry for the alarm.

**Comment by bvaughn** [comment]
Thanks for the follow up 😄
