### ISSUE TITLE
Proposal : Promise render hooks

### ISSUE THREAD

**Issue by rozaxe** [facebook/react#15032]
I was playing with flutter and I found the widget [FutureBuilder](https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html) pretty useful.

This type of component enables to render itself based on the status of a promise.

Typically, this could be used to display a "loading" state while the promise is resolved and then, display the actual component with the freshly resolved value.

Example :

```js

function Hello() {
  
  const snapshot = usePromise(fetchData())
  
  let text = 'Loading'
  
  if (snapshot.hasValue) {
    text = snapshot.value
  }
  
  return <span>{text}</span>
}
```

I made an example on [CodeSandbox](https://codesandbox.io/s/ykzv1jv88j). First, a 'loading' text is displayed and after a second (promise resolved), display 'hello'.

Finally, this is just a wrapper around a `useState` but I found it pretty convenient (less boilercode, more expressive).

Do you think this could be a nice addition to the hooks ?

**Comment by brookslybrand** [comment]
I think this is basically the idea for what Suspense will do when it's able to handle data fetching:
https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-mid-2019-the-one-with-suspense-for-data-fetching

**Comment by ghengeveld** [comment]
Check out React Async, it includes a `useAsync` which does this. https://react-async.dev

**Comment by rozaxe** [comment]
@ghengeveld Oh thanks for the library ! It does what I said, will use it.

Thanks @brookslybrand for pointing the Suspence feature, I think this issue can be on hold until the fully implementation of it !

**Comment by brookslybrand** [comment]
No problem @rozaxe, I'm actually in the same boat right now. Glad to know about React Async though too, thanks @ghengeveld

**Comment by otakustay** [comment]
I have created a simple library that may match your requirement: https://github.com/ecomfe/react-suspense-boundary

It is not published yet, but internally we use it in some apps in production, it is quite stable and performant

Any thoughts on this will be welcome, we are ready to improve this library to a community friendly and more use case covered one
