### ISSUE TITLE
State is mutable from function called inside of componentDidUpdate

### ISSUE THREAD

**Issue by alex13indas** [facebook/react#15043]
**Do you want to request a feature or report a bug?**
Bug

When calling a function from inside of componentDidUpdate(), the state becomes mutable and is changed without calling this.setState().  

Note: It is only mutable when the state is an object, and not a primitive data type. 

**Example code to reproduce:**

```
class App extends Component {
  constructor(props ) {
    super(props);
    this.state = {
      clicked: {key: false}
    };
  };

  componentDidUpdate(prevProps, prevState){

    if(prevState.clicked!== this.state.clicked){
      this.updateState();
    };

    //meow is printed!! 
    console.log(this.state.clicked)
  };

  updateState = () => {
    let myObj= this.state.clicked;
    if(myObj!== null){
      myObj.key = 'meow'
    };
  };

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <button onClick={() => this.setState({clicked: {key: true}})}>Set to true </button>
          <button onClick={() => this.setState({clicked: {key: false}})}>Set to false</button>
        </header>
      </div>
    );
  }
}

export default App;
```

React Version:  16.2.0 - 16.8.4 (Tested in both Typescript and Javascript)
Browser: Chrome (72.03)

**Comment by gaearon** [comment]
React can't force you to not mutate state. It's idiomatic to not mutate it, but you technically can.

**Comment by alex13indas** [comment]
So changing a local variable should update the state, but then why not with primitive data types?

**Comment by alex13indas** [comment]
@gaearon How come this doesn't happen when you call the function from anywhere else but componentDidUpdate? Is this expected behavior?
