### ISSUE TITLE
Numpad Decimal key producing a different "key" between Chrome and Internet Explorer 11.

### ISSUE THREAD

**Issue by papiro** [facebook/react#15042]
Possible **bug** in v**16.8.3**.

When I push the `.` key on the numpad (with "Num Lock" turned on of course), it produces the following property values within the `onKeyPress` handler, in the event object in Chrome: 
```
charCode: 46,
key: ".",
keyCode: 0
```
But in Internet Explorer, it produces:
```
charCode: 46,
key: "Delete",
keyCode: 0
```
I would expect the `key` property to be equal in both cases. The value `"Delete"` is incorrect as it is the decimal which is being pushed. But the decimal key is in fact the Delete key when the Num Lock is off... but it's weird that Chrome would understand that, but not IE, especially considering the key is producing the same `charCode` on both browsers.

My understanding is that I am dealing with a "Synthetic Event" whose job it is to normalize the cross-browser differences. This seems like it would've been caught via tests or other issues, so I'm not sure this is a React issue. Does React own the library which provides the Synthetic Event implementation?

Thank you for any help :)

**Comment by LaikaFusion** [comment]
I can confirm I can reproduce this on v16.8.4 of React with a US English keyboard layout.

It works as suspected on Edge and Chrome.

If changed to `onKeyUp` it correctly says it's Decimal, however it's read as a different charcode. It's `.`(charcode:190) on Chrome, and `Decimal`(charcode:110) on IE/Edge.
