### ISSUE TITLE
react dom doesn't leave white space in text when there is a line break followed by an inline element

### ISSUE THREAD

**Issue by brizental** [facebook/react#15058]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

React treats line breaks in text differently than how pure HTML does it.

**How to reproduce:**

If you try this out in React:

```
export default () => (
  <p>
    foo
    <strong>bar</strong>
  </p>
)
```

You'll see that is behaves differently than in pure HTML:

```
<p>
  foo
  <strong>bar</strong>
</p>
```

React ends up cropping out some more white space than I expected it to.

**React**
<img width="61" alt="screen shot 2019-03-07 at 8 29 44 pm 1" src="https://user-images.githubusercontent.com/25176023/53996652-0c20af80-4118-11e9-9fb5-dd975b9f6a45.png">
**Pure HTML**
<img width="65" alt="screen shot 2019-03-07 at 8 29 03 pm" src="https://user-images.githubusercontent.com/25176023/53996663-16db4480-4118-11e9-9068-0f72d8eb9e3c.png">
I haven't looked more into this, because I'm not sure it is actually a bug or a design choice. It is also not a super big problem, as far as I see it. 

I would be happy to look into it, if this was confirmed as a bug, though :)

**What is the expected behavior?**

I expected React to leave a white space between my text even if I break a line before an inline element (in my example a `<strong>`). In this case I would have to remove my line break for it to work. 

To illustrate, this works fine:
```
export default () => (
  <p>
    foo <strong>bar</strong>
  </p>
)
```

So, when I checked in the console, I see the DOM created by React indeed trims out white spaces from the begining and the end of my string. The `nodeValue` for the `foo` text node in React is just that `nodeValue: "foo"` and in pureHTML it is `nodeValue: "\n    foo\n    "`.

I should note that even if I add a space before the line break, it is still trimmed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I don't know if this used to work, but currently I'm using MacOS Mojave, I have tested this in Firefox 67 and Chrome 72 and my React version is 16.

---

_Sorry for the clumsy bug report, hope this helps._

:)

**Comment by aweary** [comment]
This is expected behavior, JSX will remove whitespace from the beginning and ending of a line. You can get the markup you want by either keeping them on the same line (if they're short enough) or explicitly adding a space using an inline string literal:

```
<p>
      foo{''}
      <strong>bar</strong>
    </p>
```

Check out the [JSX in Depth](https://reactjs.org/docs/jsx-in-depth.html#string-literals-1) documentation for more details. Thanks!
