### ISSUE TITLE
react-dom-server.browser.production in bundle. Why?

### ISSUE THREAD

**Issue by frederikhors** [facebook/react#15060]
Also asked here: https://github.com/apollographql/react-apollo/issues/2828.

Simply updating `react-apollo` from `2.2.4` to `2.3.0` alter bundle size like in the screens below:

**- from this:**
![image](https://user-images.githubusercontent.com/41120635/53606934-f877c500-3bbc-11e9-9b93-f340a0450f24.png)

**- to this:**
![image](https://user-images.githubusercontent.com/41120635/53606973-1cd3a180-3bbd-11e9-9f06-063649a00092.png)

**Do you know why?**

- **Version:** "react": "16.8.4"

**Comment by aweary** [comment]
We use the issue tracker for bug reports and feature requests for React itself. If you're having issues with community projects like `react-apollo` please report the issue there (as you did).
