### ISSUE TITLE
What is the react-cache good for?

### ISSUE THREAD

**Issue by novellizator** [facebook/react#15066]
At the first sight it seems illogical. I'm glad you're caching like last 500 resources, but _Why_?
The browser itself caches everything anyway - that's why we have so many headers in HTTP.
How does the react-cache help?

**Comment by gaearon** [comment]
It’s an experimental package whose purpose and name will likely change. It’s not supposed to be used by anyone so I’m not sure how that affects you.

**Comment by novellizator** [comment]
@gaearon  Wading through the sources, interested in contributing sometimw,  I'm just wondering what it is good for, and what is the supposed benefit of it. Could you just clarify the motivation please?

**Comment by gaearon** [comment]
https://www.youtube.com/watch?v=ByBPyMBTzM0

https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-mid-2019-the-one-with-suspense-for-data-fetching
