### ISSUE TITLE
Double-invoking the render function in StrictMode is somewhat too deterministic

### ISSUE THREAD

**Issue by dai-shi** [facebook/react#15065]
**Do you want to request a *feature* or report a *bug*?**

feature in the development mode

**What is the current behavior?**

Inside `<StrictMode>`, the render function is invoked twice, but always the second one is committed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/k938koy8mv
I made a tiny change in @gaearon 's code.
```
  // This may not work in concurrent mode.
  savedCallback.current = callback;
```

**What is the expected behavior?**

Developers can notice the wrong code (unintentionally mutating refs in the render function).

One idea is to occasionally (ex. `Math.random() < 0.25`) commit the first result from double-invoked render function.
The other could be to introduce `<StrictStrictMode>` which is to triple-invoke the render function and commit the second one.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8

**Comment by dai-shi** [comment]
A note from my experience: it took me a week to understand it.
Ref: https://twitter.com/dai_shi/status/1096947972871319553

**Comment by budarin** [comment]
I have the same bug.
For a long time I think that it's problem with recreating reducer but found this issue and when have removed strict mode - the bug is disappeared

**Comment by dai-shi** [comment]
Hi @budarin 
Double invoking in strict mode is intentional, not a bug.
This issue is about that just double invoking might not be enough.

**Comment by budarin** [comment]
but there is no a description of this "feature"

**Comment by eps1lon** [comment]
I guess this is more of a docs issue. `useMemo` also runs twice in strict mode if the dependencies change.

**Comment by budarin** [comment]
useMemo behaviour is described exhaustively unlike strict mode

**Comment by eps1lon** [comment]
> useMemo behaviour is described exhaustively unlike strict mode

I didn't find any mention in the docs that the factory in useMemo is invoked twice in strict mode when dependencies change.

**Comment by dai-shi** [comment]
@Baloche 

https://github.com/facebook/react/issues/16956#issuecomment-543068780

> A little bit off topic but I need some clarification : In every implementation of useDynamicCallback that I see, a useEffect or a custom useIsomorphicLayoutEffect is used, but why ? What is the point of updating the ref inside a use*Effect instead of just doing it outside like the following ?

```js
function useDynamicCallback(callback) {
  const ref = useRef()
  ref.current = callback
  return useCallback((...args) => ref.current.apply(this, args), [])
}
```

Indeed, it's an off topic, so let me comment it here.

Usually, it works like this:

render1 callback='abc'
commit1 callback='abc'
render2 callback='def'
commit2 callback='def'

However, sometimes commits can be skipped.

render1 callback='abc'
commit1 callback='abc'
render2 callback='def'
render3 callback='ghi'
commit3 callback='ghi'

And, there can be time gap between render2 and render3.
During the period, the callback should be 'abc', but if you don't use effect it will be 'def'.

**Comment by Baloche** [comment]
Why should it be 'abc' ? I'm actually expecting it to have the most recent value.

**Comment by dai-shi** [comment]
Because 'def' is thrown away by React. In that situation, the most recent value at that point is 'abc'.

**Comment by dai-shi** [comment]
It is hard to reproduce the throw-away behavior intentionally.
So far, I've created this.
https://codesandbox.io/s/eager-ritchie-2qv63

**Comment by dai-shi** [comment]
I'd take this down. Double-invoking behavior is already confusing people and it's not a good idea to go with more weird behavior.

It would be the best to handle this issue with eslint rules/suggestions.

**Comment by dai-shi** [comment]
https://github.com/facebook/react/pull/18545 looks like related to the concern in this issue.

**Comment by childrentime** [comment]
https://reactarium.vercel.app/#eNqVV22P0zgQ/iujcKip1KRpb5dbBYqOO5BAgjsJ+EaQcBMnNRvbUex0W6r+9xvbSZq03ePuw2qd8TMvz8x47B48TpgItdp58cEThFMvPolmXklE0ZDCSPW+oiqtWaVRviVlY4SMV7LWcIC0pkTTj1JqOEJeSw6Jh6JUB5nk87RkVOjEe56IVuNVVXWwcI4fdi8RqRRKQ23MrAY2/UymDUcTYUH1m5Ka5R/7d5mPTnA78aZAFLz9/OF9uzlFa2YnrKnIaO2/MP7mL43YO848/Drj3En+M+WPhtwMmTeKftIY58ysPtLc/n9P9rLRb/KcGhAK3LLLzcSmZjKgjIqvKZfI2p/C6iUcEgHgtr6kshFoRVH9p1l9RVDn1I8MpR5ZykJZ4HtcjHBfvjrgCVyjR1aboCwMA/CtI4frd8O0qTGJth5m+7mzMbLTkrtm5ywX/oCdMyBLGmLY/sQqTWZO1+33pi+CMPvHE/XeSB/2ZHbB4DrcObgG72j21bsMXgPJMsy1KRtXhd1us+9XNd2a7y9hGJq16RXNOI3hNRYkFPLBn84AteDY1sa5A2A5uBTCarWCaNp5hNab/+2dYJqREhNkujt2ScEgfjnY1fFbZ/Ck0tYaaVrcBd1rOm1dBzrjcjidTqvrT39xYWnyieo2SC1hAb7AA55KzpnWNIM91dPJSWlg8DMmDJtnnPlHaJmMc6KbmiL4ZxSvkvRRPd1QBa///tDbuEa5s3Fa9eSXV3yM6S8HVI8zWERRe4jx0/b1rD3yti3cYURWAnwHepGxLaQlUeovnF2rxKuCG1AVSWmwD24S72Vn/ALYgZawLoKiJvvgNgKjXaO7jGYD3Svamu50sCshl0IHa1kaOCbKEYuhbb0Xc9T7NzNWndOMNRwNXBQJDV0W7v8bHVfNGT2r5Njo+OvRFHI9SvFjoZj0AF8HS8RiB8Q/JdAVBLthWJG+rouRU4CDGfUhJ5XvH8xUsZMEO4eh1s4elrZbRh7v6X5l4ccr2ZNCgq2xMjkca6NDY//M5BkpgOl0AHk8v6e16fCj7XK6s9dqRnPSlP19+Ly7rVOlzm5rIxnd1k7QXdOxfUTYiWHp5YSzch/DO6FpjXfkXmnKg4bN4NWWCoait7TcUs1SgqIapyuCiFCBojXL7fkMHuj6nqEpY09xtL9hooiBCDOMGVE0czgufwRS7S6ApsIqJSW1MLv7QFmxwf68iSIrLJmgwaYVLsLb9s4qJU75ulj7y9tb6P7mcPfbUzc6bN3cbWA9yQqrzH7QkhZszUqm9yeYQnlAsu+NMi6i6OkpGrUXGucfUzEIKUyYWM9EPDnlkpNd8MAyvUHV5V1U7axyhYPO+l3iCLYSTuqCiRgiII2WJ+eYpwLFKR5AWnf21zLbO/MZU1VJsEx5SZ1pzkTn8Ndl588I+yRF0XYz9uliKs3JYVhlZNP765P5BMdu5z/MSH3fPbncbp6bmttdjK/RWgoH6KlG4TPKsUTLlvGoy5jYYCXcO8VlFpOOsQ6xXelv29LjXFLGdyVZH+xa1vaCX1Q7wGcLy0DX2JQVMRNsgAhqgrMPid61GbIwfCRIzEcLsdQw7OWt6hNvicUbuaW1ozfEYhqe3TxLT5lo4Tk+xtVs/BlsmWLrkjoreGWbRsa2xrhNAwzOjgGbJnU+jGlzxt2rOsCBFn5XUgzO+vnO6My3ku7QW+dJq6ISD+d++7ByP0aMJPE2Wlcqns+p4qHazO3O74u7cBlGiYe8BgqjXy+P6RpQr29vcJsv73j8B6cHXis= @dai-shi Can you explain this in more detail? I made an example where the ref value doesn't match the DOM result when using useLayoutEffect to update the ref.

**Comment by childrentime** [comment]
@dai-shi So what are the consequences if we don't wrap it in an effect? This example doesn't seem to work anymore. Also, wouldn't updating in useEffect cause a lag behind what's shown in the DOM since it runs after browser paint?

**Comment by childrentime** [comment]
https://reactarium.vercel.app/#eNqlVm1v2zYQ/iuEigIOZsmKF2eBlgTL2gIt0G5At2/TPtDSSWbDF4GkHKuG//uOpGRLbrJh6IfA1N1z99wrmX0kKJOJNbso20eSCoiyk2gecSrrltZOarsGTKFZY1G+pbx1QiYapS3Zk0IDtfBZKUsOpNJKkDxCUWHjUolFwRlIm0c/57K3eGiaAZYs8MPrclkoaSzRzs3dyOesVEUr0EVSg33HwR1/7T6UMyRBdR5dEGrI+z8/feyVF+jNaRINsgQ9u3V8i3snjg7zCL/Och4k/yPl1sAfFgOcu9NnqPzvR9qp1r6rKijOKzFJEfFvQSjMcnZB7u7JPpeEBNVfhWqlnRMD9o07/Y2ggWuWuhROWI1umHZcHoNeZ97aochJmxStxkr4ojr1uY8+3ud8nOU0G4UbHCgOCVc1tsJb5dE8cARzH0QwfSYIQg5DPhpsqyWZBaPbkm1Jwakxv2F/7vKoia+IaWgBcRdf5dF9gD0DHEBLsq7jWtMuXqXEWWvkLKEc2T5jbWFn4x0nlZI2Xivu4G9//xQCzsje/x5uF2j3b268uYCStWLC90xL0Ok3ssPI9XdRTQsfqKayF6mGrxcLLeykES+F5opIxDpe5hFR8g1nxePdPgzRMOBh3MgP5PLiMMngoSz/K7zp2Q3TwQ8U7PyWllDRlh/XbbT+hTFn6+8kk/UPgmHvM38r+cH3iVVUMN5l5IO0oHFbO2NBxC2bk4ctSIai98C3YFlBUaQZ5Qii0sQGNKv88MdPsH5k6Mr5MwL9b5isM0KlRTijBsqAE+prrMzuG6Cbb1NQDh7mtU/A6g22+ipNvZAzCfGmF14mKy8sFFc6I7pez5arFRn+FuTmp9dhb/0ihMvTM6nGMsG+AoearRlntjvBDMpjWn5pjaNI09enaEwn7QYMMxmRSrowceBy+epUS0F38RMr7QZNlzdps/PGDS1Lz7vUILxEUF0zmZGU0Na6RvbkWKcaxQXOMujB/1qVXXBfMtNwim2qOATXgsmB8MflwOeExyKl6XYz5QwxcXezMOwyZnPkOxbzVeor7vmTkurH4U4P2qpyPfdajK+1VskAOKaaJtcgsEXLPuPJlDG5wU6EOzNUFouOsY6xQ+tXfetxxY3jbhQ7BrtWGluKhs2O4NXNSmI1DmVD3WUwQsSa4pWCid70FfIwZpnCevQQnxqGvVyZY+F9YtlGbUGH9MZYLMP11XVxqkQPr/B1N/PpZ7xlhq05BC/4/rhBxrHGuN0AjHbHgd2QBg7n2u14eKZjQZvki1FytOvnmsnO95Jh6T153puYPMIrNNw5xzc9w+PG2sZkiwUYkZjNwmt+ubxJlkmKz+HEYPLv0Eu2DnS096+kr1d0OPwDAHA46A==
