### ISSUE TITLE
Ammend documentation for skipping useEffect

### ISSUE THREAD

**Issue by Pomax** [facebook/react#15068]
This is a documentation improvement request. 

Currently https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects explains skipping a useEffect based on a state variable by showing the following code:

```javascript
useEffect(() => {
  document.title = `You clicked ${count} times`;
}, [count]); // Only re-run the effect if count changes
```

With the following explanation:

> In the example above, we pass [count] as the second argument. What does this mean? If the count is 5, and then our component re-renders with count still equal to 5, React will compare [5] from the previous render and [5] from the next render. Because all items in the array are the same (5 === 5), React would skip the effect. That’s our optimization.

However, this does not explain why an array is needed: it still needs to explain what happens when an array with more than one value is passed. Is `useEffect` bypassed when _all_ values are the same, or when _some_ values are the same?

(and of course the answer to that question should be the PR that updates the documentation, not an issue comment =)

**Comment by gaearon** [comment]
It says "because all items in the array" which kinda answers your question. :-) Happy to take PRs. In either case this would be better filed on the docs repo. (reactjs/reactjs.org)

**Comment by Pomax** [comment]
It does not: because the array we're shown only has a single element it, it is ambiguous what that phrasing means. E.g. we cannot tell whether that was intentional phrasing, or just normal English not tied to technical precision

As for PR: I'd be happy to submit one! Except I can't, because of the CLA that is in place. As such, all I can do is ask, and so I'd ask you reopen this issue because as obvious is it might be to you that "all items in the array" is a technical statement, that is far from true for all readers.

**Comment by gaearon** [comment]
Please open it in https://github.com/reactjs/reactjs.org which is the repository for documentation. Then somebody can fix it. Thank you!

**Comment by Pomax** [comment]
cheers
