### ISSUE TITLE
Provide a build with required polyfills, or a separate react-polyfills.js

### ISSUE THREAD

**Issue by steadicat** [facebook/react#1507]
Right now, somewhere buried on the React site, there's a list of polyfills that React requires, with links to a project that has them, intermingled with a bunch of others.

It would be nice if React (optionally) shipped with all the polyfills, and only the polyfills, it needs to function.

This would make it easier for people to fall into the pit of success and build browser-compatible React sites. Also it would save me a bunch of work every time I start a new project.

**Comment by spicyj** [comment]
Nothing planned; I'll close.
