### ISSUE TITLE
Add React.use(customHook) wrapper for improving DX

### ISSUE THREAD

**Issue by swapagarwal** [facebook/react#15076]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

"A custom Hook is a JavaScript function whose name starts with `use`...",  
so `useFriendStatus` is a "potential" custom hook.

Copying from https://reactjs.org/docs/hooks-custom.html,

> Q. Do I have to name my custom Hooks starting with “use”?
A. Please do. This convention is very important. Without it, we wouldn’t be able to automatically check for violations of rules of Hooks because we couldn’t tell if a certain function contains calls to Hooks inside of it.

e.g. `const isAwesome = useAwesomeLogic(props.id);`

**What is the expected behavior?**

It'd be great if we could remove the "ambiguity" around whether a function used in a component is a hook or not, by adding a wrapper method in React which just returns the function passed in the argument. Think of it as syntactic sugar for expressing that a certain method is being "used" as a hook.

e.g.
```
const isAwesome = React.use(awesomeLogic(props.id));
or
const isAwesome = React.useCustom(awesomeLogic(props.id));
or
const isAwesome = React.useCustomHook(awesomeLogic(props.id));
```

I started learning React last week, so please ignore this if I missed something trivial or it just doesn't make any sense. 😅

**Which versions of React, and which browser / OS are affected by this issue?**

16.8+

**Comment by gaearon** [comment]
I think the concern here is that people just will skip it or forget to do it if it works anyway. And you have to remember which function is a Hook and which is not. Calling it with not a Hook wouldn’t trigger a warning so you won’t know you’re wrong. So all in all it doesn’t seem like it would help as a heuristic.
