### ISSUE TITLE
production build + SSR + hooks = error

### ISSUE THREAD

**Issue by salzhrani** [facebook/react#15077]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

using `useContext` or `useState`  hooks in the production version of react throws error #307 (Hooks can only be called inside the body of a function component)

**reproduction**

https://codesandbox.io/s/w234280ox5

Notice when using the development version it renders as expected.

In line 4 change the import to development 

**What is the expected behavior?**

to render without throwing. 

react/react-dom version `16.8.3`

**Comment by TrySound** [comment]
@salzhrani There is no bug here. This happens because bundler imports from `react` package (`require("react")`) which resolves to development version and you get two react instances.

I don't know if there is a way to configure codesandbox to compile production version.

**Comment by salzhrani** [comment]
I use the full path
```
import React, {
  createContext,
  useContext,
  useState
} from "react/cjs/react.production.min";
```
should that still be an issue?

**Comment by TrySound** [comment]
@salzhrani Yes, and this is the problem. You import from `react/cjs/react.production.min.js` and react dom server imports from `react/cjs/react.development.js`. And you get two instances.

**Comment by salzhrani** [comment]
I am facing the issue with webpack build ... any advice where to check?

**Comment by TrySound** [comment]
Dont import production bundles directly. Import from `react` and `react-dom/server` and set webpack mode to production.

**Comment by salzhrani** [comment]
That is what I am doing but still I face this issue.... is it safe to say it is not a react issue?

**Comment by TrySound** [comment]
Show the piece of code you use react and your webpack config

**Comment by salzhrani** [comment]
my bundle has:
react.production.min.js
react-dom-server.node.production.min.js
react-dom.production.min.js

only

and the repro uses only production packages

**Comment by TrySound** [comment]
I had something like this because of uglify-es. Make sure you use terser.
https://github.com/facebook/react/issues/14217

**Comment by TrySound** [comment]
If it does not solve create please a reproducng error repository.

**Comment by salzhrani** [comment]
The issue was that we were using an old version of `loadable-components` that used `walkTree` which caused the error. upgrading to the latest version of loadable-components fixed the issue. thank you.
