### ISSUE TITLE
shallow renderer: wrong initial state passed to getDerivedStateFromProps

### ISSUE THREAD

**Issue by ljharb** [facebook/react#15075]
Demonstrated in https://github.com/airbnb/enzyme/pull/2027 - when gDSFP returns a state change, cDU does not seem to be called by the shallow renderer. I'm not sure how to make a simple test case; but the identical enzyme tests pass for `mount` (ie, when using React itself) but fail for `shallow` (when using the shallow renderer). enzyme doesn't have any logic for calling or interacting with `getDerivedStateFromProps`, so I suspect it's not an issue with enzyme (but it might be!)

**Comment by miraage** [comment]
Could you please setup a sandbox?

**Comment by gaearon** [comment]
Happy to take a bugfix if you think it's a bug. (See existing shallow renderer tests)

**Comment by ljharb** [comment]
I'm actually seeing two issues here:

https://codesandbox.io/s/m7nn4v428 shows the behavior of React itself:
 1. Demo's gDSFP is called, returns null
  → **NOTE**: called with second argument as `this.state`
 1. Demo component renders (via SetProps component)
 1. Demo's props are updated (by SetProps)
 1. Demo's gDSFP is called, returns null
 1. rerenders
 1. cDU is called

https://codesandbox.io/s/mqm4o7m7nx shows the behavior of the shallow renderer:
 1. Demo's gDSFP is called, returns null
  → **NOTE**: called with second argument as `undefined`
 1. Demo component renders (via shallow renderer render call)
 1. Demo's props are updated (by another shallow renderer render call)
 1. Demo's gDSFP is called, returns null
 1. rerenders
 1. cDU is **NOT** called

**Comment by gaearon** [comment]
Here's an example of a recent gDSFP fix, it shows where to change the code and where the tests go.
https://github.com/facebook/react/pull/14613/files

**Comment by peanutenthusiast** [comment]
I'll look into this.

**Comment by gaearon** [comment]
Looking at it again — this works as intended.

Shallow renderer *has never fired* `componentDidUpdate` at all, similar to how it never fired `componentDidMount`. The reason is that most `componentDidMount` and `componentDidUpdate` methods have side effects or deal with refs, and so they break shallow rendering assumptions anyway.

There is a bigger discussion to have about the future status of shallow renderer in and its design, but the reported issue is not a bug.

**Comment by ljharb** [comment]
@gaearon note as well the discrepancy in the first call to gDSFP - should i file a new issue, or can this be reopened?

**Comment by gaearon** [comment]
Oops, missed that. Thanks.

**Comment by gaearon** [comment]
Hmm, I can't repro with https://codesandbox.io/s/mqm4o7m7nx:

<img width="379" alt="Screen Shot 2019-03-19 at 10 15 01 PM" src="https://user-images.githubusercontent.com/810438/54645636-821c0380-4a94-11e9-9711-ee4c3052d27f.png">
 
I don't see undefined.

**Comment by gaearon** [comment]
Is it only if you omit `this.state` assignment in constructor? This normally warns. (Although not in shallow.)

**Comment by ljharb** [comment]
Hmm - now I can't reproduce it even on my original sandboxes :-/ I see the same minor discrepancy as you when I comment out the state assignment in the `Demo` constructor, and while that might be nice to fix it's probably not worth the effort. 

I'm going to close this - I'll comment here, or file a new issue, if I see anything else.
