### ISSUE TITLE
Trivial point, but why must the render() return have the left paren on the same line?

### ISSUE THREAD

**Issue by jh-orange** [facebook/react#15070]
Haven't modern parsers progressed a little beyond that?

**Comment by gaearon** [comment]
Not sure what you mean by “parsers progressing”. But this is how JS works, for better or worse. It would have been a breaking change for the language to do something different. https://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi
