### ISSUE TITLE
shrinking nav onscroll text behind it

### ISSUE THREAD

**Issue by brickmaker17** [facebook/react#15082]
When text scrolls behind the navbar I created the navbar has a spaz attack. I am using create-react-app, styled-components, and react-router-dom. I create a sample of the issue in code sandbox https://codesandbox.io/s/r06jv3yoqp?fontsize=14

**Comment by MonFig** [comment]
What do you mean spaz attack?

If what you mentioned is the wired shaking that your navbar be, it might because the changing of the navbar's height might also lead to the window resizing.

**Comment by ahtee** [comment]
I think he means this happens. not sure how this is a react issue though 
![2019-03-12 09 28 39](https://user-images.githubusercontent.com/5076085/54203843-65d30200-44a9-11e9-91e5-a5b3ef67e8d4.gif)

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
