### ISSUE TITLE
Using a fully react state management cons.

### ISSUE THREAD

**Issue by Hypothesis-github** [facebook/react#15089]
This is not an issue but rather a question.
I wanted to use React solely for my Global state management and pass the todos through useReducer and useContext and I wonder if this is by any means a right way to go. I was called out by a react coder that this way the components rerender when they aren't supposed to but my element inspection shows only the changed component rerenders. Would please guide me as whether or not I can continue developing this way or have to revert back to Mobx or redux or many other third party state manager libraries.

**Comment by gaearon** [comment]
This is too vague to answer, sorry. If you show specific code with a problem then we can see if there's a solution.
