### ISSUE TITLE
eslintignore won't able to apply

### ISSUE THREAD

**Issue by dotku** [facebook/react#15085]
I'm trying to esignore my deprecated project, but it won't able to apply

```
./src/components/ProjectName/**/*.js
```

I pleased the .eslintignore file to react app root.

**Comment by ahtee** [comment]
did you try ignoring the entry point defined by package.json?

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
