### ISSUE TITLE
shouldComponentUpdate not called but componentDidUpdate is

### ISSUE THREAD

**Issue by papiro** [facebook/react#15083]
Using version 16.8.3.

I'm not sure that this is a bug, but according to http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/ which is linked to from the React docs, it appears that anytime `componentDidUpdate` is called, it only reached that point in the lifecycle by first passing through `shouldComponentUpdate`. This has always been the case for me, as far as I've noticed. But I am debugging a component now where this is not the case and it is very confusing. 

Is this a bug? Surely it must be possible within the React codebase, because it is happening - but under what circumstances should this happen?

**Comment by gaearon** [comment]
Hard to say without a minimal reproducing case.

**Comment by papiro** [comment]
Ahhh.... I went digging through the React source code and found this: https://github.com/facebook/react/blob/master/packages/react/src/ReactBaseClasses.js#L69

I am indeed using `forceUpdate`...! 

Closing this, if that's ok.
