### ISSUE TITLE
react hooks array  not updating

### ISSUE THREAD

**Issue by yahengqi** [facebook/react#15090]
const mappingDashboardeColor: any = [];
 const [mappingPicker, setMappingPicker] = useState(mappingDashboardeColor);    

function handleColorPickerValueChange(index: number, colorPickerValue: any) {
        _.map(mappingPicker, (n, k) => {
            if (parseInt(k) === index) {
                mappingPicker[k].colorPicker = colorPickerValue.label;
            }
        })
        setMappingPicker(mappingPicker);

    }

Write like this without updating

**Comment by gaearon** [comment]
You’re mutating the array. If you return the new value from your mapping function, and set the state to the *new* array returned by map itself, it will work.
