### ISSUE TITLE
Security error on iOS due to cross origin iframe access

### ISSUE THREAD

**Issue by renanvalentin** [facebook/react#15098]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Our application has credit card input fields hosted in iframes and we make use of `postMessage` restricted to a `targetOrigin`.

The problem is that `ReactInputSelection` tries to access the `contentDocument` of the iframe but this result in a security violation on iOS, breaking the post message flow.

```javascript
// react-dom/src/client/ReactInputSelection.js
function getActiveElementDeep() {
  let win = window;
  let element = getActiveElement();
  while (element instanceof win.HTMLIFrameElement) {
    // Accessing the contentDocument of a HTMLIframeElement can cause the browser
    // to throw, e.g. if it has a cross-origin src attribute
    try {
      win = element.contentDocument.defaultView;
    } catch (e) {
      return element;
    }
    element = getActiveElement(win.document);
  }
  return element;
}
```

This seems to work fine in most of the major browsers except on `iOS 11.2.1`. 
By changing the code bellow to use `contentWindow` instead fixed the issue:

```javascript
 // This results in 'Blocked a frame with origin' on iOS 
 // and the post messages are not being sent
 win = element.contentDocument.defaultView;

 // fix the issue
 win = element.contentWindow;
```

Steps to reproduce:
1 - Connect your phone to Safari's developer tools
2 - Visit the code sandbox sample at https://codesandbox.io/s/vv8w1zwm90
3 - Tap on the `input field` hosted on codepen
4 - Tap on the `console` tab on code sandbox
5 - It should log `Blocked a frame with origin "https://codesandbox.io" from accessing a frame with origin "https://vv8w1zwm90.codesandbox.io". Protocols, domains, and ports must match`

**What is the expected behavior?**
Accessing an iframe should not result into cross origin security error.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.4 
iOS 11.2.1

**Comment by philipp-spiess** [comment]
@renanvalentin I think this is a duplicate of https://github.com/facebook/react/issues/14002. Can you take a look at this issue as well and confirm that? Thanks 🙂

**Comment by renanvalentin** [comment]
That's the same issue hahaha. Should I close this one?

**Comment by philipp-spiess** [comment]
@renanvalentin Hehe! Yes let's keep it at one ticket then. Thanks for reporting!
