### ISSUE TITLE
× Maximum update depth exceeded in controled way

### ISSUE THREAD

**Issue by damianmalinowski** [facebook/react#15093]
**Do you want to request a *feature* or report a *bug*?**
- maybe bug?

**What is the current behavior?**

My case is that I want to update state n times by adding different types of fields to the state and then render them. 
Every updating of dom(adding new field) I have to check whether I should do something more by checking the hight of added elements, for example, add a break between elements. 
Fields are represented by the tree structure of data, so I created the class which helps me with going through the tree of fields and I keep it in the class property.

I know how many times I have to modify the DOM so It will be a fully controlled way of state update and it will finish after all fields are added to DOM but before I render all fields I am getting the error "Maximum update depth exceeded".

Do you know How I can handle with such a problem? 
I found a solution by adding setTimeout on the way but I am not sure that is the clean solution?(commented code)
Is it ok that I keep in component class property more complex class to manage structure of data?

I am providing a simple example in codepage which shows the problem and throw the error.

https://codesandbox.io/s/93w2lp37xw

**Comment by kunukn** [comment]
The warning says

> Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

I believe it is by design. 

Depending on what you want to achieve you could either partially render the updates as you did with setTimeout (requestAnimationFrame could also be used). 

Or you could run all the changes first, and then finally call setState once when you have all the needed data to be rendered to the screen.

I believe there are programmatic strategies to create a solution without calling setState n times in a row.

**Comment by damianmalinowski** [comment]
Thank you for your replay. I think I wasn't clear what I want to achieve (I wanted to provide a simpler example and show only logic which produces the error), so I will provide more info. 

I want to provide a preview of printed pages. I mean that I have to split my "fields" for particular pages. Currently, I am doing it by adding field by field (so I am not able to build data and setState...) because previous fields have an influence on next fields in case of printing pages. To do this I check whether the current page is bigger than it should be by checking the hight of the currently rendered page. I thought that I am able to do this with react only but unfortunately, I think I am not able to do that because react see it as an uncontrolled behavior (warning says: "React limits the number of nested updates to prevent infinite loops."). In my case, it is not an infinite loop it is completely controlled behavior because I have "n" fields to render.

Of course, probably there are different approaches which I can use but I thought that maybe I can do it with react only.

**Comment by kunukn** [comment]
Maximum allowed componentDidUpdate loop seems to be 50

Demo
https://codesandbox.io/s/48k6wq3z7x

You could use setTimeout/requestAnimationFrame to work around this limitation (as in your example).

using setTimeout will wait until the browser has been updated. Then it will continue invoking the function inside setTimeout.

**Comment by damianmalinowski** [comment]
Thank you for your replay. 
Just in case I am still thinking about the best solution. I agree that increasing limit is not the right solution.
I was curious how it will be working if I change that limit in the bundle (as you show me) but it turned out that it completely freezes view during that component generation, so I am starting to see the reason which stands behind that limit. Probably I have to put more effort to understand it better and then find a better solution.
Thank you once again and I think we can close the Issue.
