### ISSUE TITLE
Click event's don't bubble outside SVG

### ISSUE THREAD

**Issue by sdemjanenko** [facebook/react#1509]
Im doing something like:

``` javascript
<button type="button" onClick={this.toggle}>
  {this.props.label}
</button>
```

If `this.props.label` is a div, span or some text, clicking on it triggers `this.toggle`.  However, if `this.props.label` is an svg then `onClick` never gets triggered.

**Comment by uldza** [comment]
@mattweb +1

**Comment by AndyOGo** [comment]
Same issue here
