### ISSUE TITLE
`stopColor` property of the `stop` SVG element not properly rendered

### ISSUE THREAD

**Issue by jlongster** [facebook/react#15109]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If you render two SVG elements that have a `stop` element with a `stopColor` property that is passed in from props, it uses the same color for both elements even though they are different.

Example: https://codesandbox.io/s/qookw7v34

**What is the expected behavior?**

There should be a black and a white SVG element. The `stopColor` should reflect whatever prop I passed in.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.4 (tested in Firefox and Chrome)

**Comment by bvaughn** [comment]
The sandbox you linked to seems to work for me in Chrome (72.0.3626.119) and Firefox (65.0.1).

![Screen Shot 2019-03-14 at 9 27 46 AM](https://user-images.githubusercontent.com/29597/54374054-8d59d400-463b-11e9-8a1e-ea835e499b0c.png)

Am I misunderstanding something perhaps?

**Comment by aweary** [comment]
Hey @jlongster! In addition to Firefox and Chrome I tested this in iOS Safari and it seemed to work correctly. I can also reproduce the same behavior using just regular HTML: https://codesandbox.io/s/34wxl7m391

This indicates that it's not a problem with React and may be a browser inconsistency.

**Comment by bvaughn** [comment]
Can confirm what @aweary says. This doesn't look to be React specific.

**Comment by Shenlok** [comment]
The issue is with using the same `id` for the `<linearGradient>` across both SVGs

**Comment by jlongster** [comment]
Came here to close this, y'all are indeed right, thanks!

**Comment by bvaughn** [comment]
Good eye, @Shenlok 

https://codesandbox.io/s/l7mow9223m
