### ISSUE TITLE
Picture/Source Tag Glitch?

### ISSUE THREAD

**Issue by TerranceBanh** [facebook/react#15107]
`npx create-react-app NAME` is normally how I start my projects

The code below is in the App.js file which I had it renamed to App.jsx:
```
import React, { Component } from 'react'

class App extends Component {
  render() {
    return (
      <picture className="dice">
        <source id="img512" className="img512" media="(min-width: 1000px)" srcSet="./DieFour.png" />
        <source id="img256" className="img256" media="(min-width: 500px)" srcSet="./DieThree.png" />
        <source id="img144" className="img144" media="(min-width: 250px)" srcSet="./DieTwo.png" />
        <img src="./DieOne.png" alt="Icon" />
      </picture>
    )
  }
}

export default App
```
The code in index.js was changed accordingly to be able to work with the code above.

**Do you want to request a *feature* or report a *bug*?**

I wish to report a potential bug.

**What is the current behavior?**
This is the code I want to use:
```
<picture className="dice">
    <source id="img512" className="img512" media="(min-width: 1000px)" srcSet="./DieFour.png" />
    <source id="img256" className="img256" media="(min-width: 500px)" srcSet="./DieThree.png" />
    <source id="img144" className="img144" media="(min-width: 250px)" srcSet="./DieTwo.png" />
    <img src="./DieOne.png" alt="Icon" />
</picture>
```
This issue that I get is that none of my local images work. The only output I get is the alt text that comes with the img tag. So the would mean the img tag does not render an image either.

If I run the same code translated into pure HTML:
```
<picture class="dice">
    <source id="img512" class="img512" media="(min-width: 1000px)" srcset="./DieFour.png" />
    <source id="img256" class="img256" media="(min-width: 500px)" srcset="./DieThree.png" />
    <source id="img144" class="img144" media="(min-width: 250px)" srcset="./DieTwo.png" />
    <img src="./DieOne.png" alt="Icon" />
</picture>
``` 
I get the results that I look for.

I have tried both png files and jpg files and none of them work through React JSX.
Keep in mind that none of the "ids" and "classes" are used to manipulate the elements in anyway.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I want to properly show the example of the bug but the issue is using local images.

**What is the expected behavior?**
The behavior I expected is the same behavior I get with online images:
```
<picture className="dice">
    <source id="img512" className="img512" media="(min-width: 1000px)" srcSet="http://data.freehdw.com/golden-sunset-on-the-green-field.jpg" />
    <source id="img256" className="img256" media="(min-width: 500px)" srcSet="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Sunflower_from_Silesia.JPG/1920px-Sunflower_from_Silesia.JPG" />
    <source id="img144" className="img144" media="(min-width: 250px)" srcSet="https://tpzoo.files.wordpress.com/2014/03/sombrero_galaxy_by_stargazerrjl-d4wwy9f.jpg" />
    <img src="http://data.freehdw.com/golden-sunset-on-the-green-field.jpg" alt="Icon" />
</picture>
```
If you test this code, this will work perfectly fine with online images but seems to lack when it comes to local images.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am unsure of which versions of React it has worked. Currently using React 16.8.3
I have tested on Chrome and Firefox.
I am using Linux Ubuntu.

**Comment by aweary** [comment]
Have you verified that you're rendering the same markup from your React components? React doesn't do anything special for `picture` or `source` elements, it just render what you ask it to in the DOM.

> I want to properly show the example of the bug but the issue is using local images.

We can't help debug if we don't have a repro to test with. Use different pictures maybe?

**Comment by TerranceBanh** [comment]
>Have you verified that you're rendering the same markup from your React components?
Don't take this the wrong way. The last thing I want to do is disrespect someone's time trying to be of help. Though I may come off as so when I say this. I had verified the rendering to the best of my ability. I have verified for everything that I had mentioned before posting my query. I have also checked again by creating a new react app with the `npx create-react-app` process. I had double checked with a plain HTML file and the code shown and that works. I had made sure even the online images work on both HTML and JSX React. If you have any suggestions to better verify or clarify my information let me know. 

>We can't help debug if we don't have a repro to test with.
If this is the case I would be happy to make a repo on github for this issue and you can download it for testing. Please let me know and I will upload. 

>Use different pictures maybe?
I have nothing against using other pictures. This is just an issue I thought might be worth mentioning.


If we cannot move forward on this issue then it might be best to just move on and close this issue.

Thank you for your time @aweary.

**Comment by aj3x** [comment]
React will move and rename the images when you deploy; so you won't find it in the same folder.
What you need to do is either import:
`import DieOne from './DieOne.png';`

Then use the import as:
`<img src={DieOne}/>;`

or...

surround it in `{}` 
`<img src={"./DieOne.png"}/>`
but if using Webpack you may need to use require:
`<img src={require('./DieOne.png')}/>`


Generally stick to using import, as it makes it easier to quickly change images throughout a file.

**Comment by TerranceBanh** [comment]
@aj3x Thank you very much for your help. Your solution had rendered the images.
