### ISSUE TITLE
Why useState can batch update in the async funciton

### ISSUE THREAD

**Issue by thoamsy** [facebook/react#15105]
**Do you want to request a *feature* or report a *bug*?**
I don't know, but it's a huge different between `setState` and `useState`

**What is the current behavior?**

We know, React doesn't batch update in asynchronous functions. But I find that in hooks, the `useState` will batch update in async functions.

I just want to know, is it a change not mentioned in the documentation?

You can see the different in the [this](https://codesandbox.io/s/43n9kk4597)

**Comment by thoamsy** [comment]
Ok, I think I know the reason.

Because `this` is **mutable**, and `useState` can bail out the render when state not changes.

If I change my code `setCount(count + 1)` to `setCount(prevCount => prevCount + 1)`，it's right.

**Comment by gaearon** [comment]
Exactly. 

https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function
