### ISSUE TITLE
Why function as child is not considered as children?

### ISSUE THREAD

**Issue by ri8ika** [facebook/react#15128]
After digging deeper with [this question](https://stackoverflow.com/questions/52553580/react-children-with-non-element-children), I have found `function as a child` is not being considered as **children**.

Take this example:
```
class CountExpression extends React.Component {
  render() {
    const children = React.Children.toArray(this.props.children)
    console.log(children)
    return <p>{React.Children.count(children)}</p>
  }
}
<CountExpression>
   {'one'}
   {'two'}
   { () => <p>Still, this will be ignored as child. Why?</p>}
   <p>This will be included in array - that's fine</p>
</CountExpression>
```

So, I would like know why is it so? Is it a bug or an expected behavior?

**Comment by TryingToImprove** [comment]
`() => <p>Still, this will be ignored as child. Why?</p>` creates a new component just like;

```
const MyComponent = () => <p>Still, this will be ignored as child. Why?</p>
```

**Comment by ri8ika** [comment]
I think it's a bug rather! I have updated my answer there in SO where you can see `this.props.children.length` shows the result by counting even the function as child component whilst `React.Children.count(this.props.children)` doesn't count function as child.

**Comment by Avi98** [comment]
I've gone through stackoverflow for this issue. With some guidance i thing i can raise a PR for this issue

**Comment by Avi98** [comment]
I've gone through stackoverflow for this issue. With some guidance i thing i can raise a PR for this issue

**Comment by behzad888** [comment]
dup #11888
