### ISSUE TITLE
React Context API

### ISSUE THREAD

**Issue by ABINAYAMUTHUKRISHNAN** [facebook/react#15127]
Kindly help me to solve this issue.

I need to pass the variable from one component (file) to the state that is located in another component (file) so that I could access the variable via consumer in all the other files.
Thanks in Advance

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
