### ISSUE TITLE
useRef only updates with a useState together

### ISSUE THREAD

**Issue by PauloStanize** [facebook/react#15125]
**Do you want to request a *feature* or report a *bug*?**
Probably a bug

**What is the current behavior?**
I'm creating a component swapper triggeredd by a interval. I had to use the useRef hook to keep the index state between renders, but it only gets updated when I keep a useState (the setCurrentIndex) is with it. When the setCurrentIndex at line 17 is removed, the swapper doesn't works.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Please check it out https://codesandbox.io/s/ooy2xrvxky

**What is the expected behavior?**
I tought that the indexRef wouldn't depend on the state hook to be updated.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.4, Chrome 72.0, Os Ubuntu 16.04.

**Comment by gaearon** [comment]
It is expected that mutating `.current` **will not** by itself trigger a re-render. That's its purpose — to let you keep arbitrary mutable values without re-rendering.

**Comment by PauloStanize** [comment]
Now it makes sense... Thank you!

**Comment by asiop** [comment]
Often times I find I have to use both ref and state, ref - for the callbacks to be current and state for the display to update. is there a more elegant way to catch both?
