### ISSUE TITLE
useState always trigger rerender although the state has not be changed

### ISSUE THREAD

**Issue by vipcxj** [facebook/react#15134]
```javascript
   const App = () => {
      [, set] = useState()
      return <button onClick={() => set(1)}>click me</button>;
   }
```
Every time we click the button, rerender happened. Although the state has not be changed.

**Comment by hamlim** [comment]
I only see it triggering a second render after the first update and no more updates after that using your code snippet.

However, this seems like it is the same issue as reported here: https://github.com/facebook/react/issues/14994.

@vipcxj can you confirm if thats the same issue or related?

**Comment by vipcxj** [comment]
@hamlim
its the same issue. The really situation is I want to prevent useless rerender in an async call back or effect.
However, if I call the `setState` hook, rerender always happen, whatever the new state is. And I can't achieve a reliable previous to decide whether to call the setState. And the callback version `setState` is useless, too. because if I use it, it trigger render.

**Comment by gaearon** [comment]
You didn't provide a sandbox so I don't know how to help you.

**Comment by privateOmega** [comment]
@hamlim @vipcxj Which version of React.JS are you guys using?
