### ISSUE TITLE
About ReactSharedInternals Module

### ISSUE THREAD

**Issue by MurakamiKennzo** [facebook/react#15131]
## Question

Does the ReactSharedInternals just export an Object and can change this props like ReactSharedInternals.ReactCurrentDispatcher. current?

## What about

Why not use get and set function like this:

```js
const ReactCurrentDispatcher = {current: null}

export const getReactCurrentDispatcherCurrent = () => ReactCurrentDispatcher.current
export const setReactCurrentDispatcherCurrent = current => ReactCurrentDispatcher.current = current
```
isn't It more common in js module right? And someone may not so puzzle.

React version: 16.8.4

**Comment by gaearon** [comment]
I don't know what problem you're trying to solve. This is an internal module, and we're happy with how it's currently structured.

**Comment by ZeeshanAhmadKhalil** [comment]
getting `undefined is not an object (evaluating 'ReactSharedInternals.ReactCurrentDispatcher')`
