### ISSUE TITLE
Minified React error #100

### ISSUE THREAD

**Issue by mflash123** [facebook/react#15138]
**App is ok from every browser exept safari!**
Safari says:

> Invariant Violation: Minified React error #100; visit https://reactjs.org/docs/error-decoder.html?invariant=100&args[]=o%00n%00C%00lCapture for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Ok, clicking bu error link I see:
> EventPluginHub: More than one plugin attempted to publish the same registration name, `onClCapture`.

Cant find any issue

webpack 4.27.1
npm 6.9.0

**Comment by gaearon** [comment]
That sounds like something broke the React bundle in your app, and its code is not correct. Could be a buggy minifier. We can't help without a reproducing example, unfortunately.
