### ISSUE TITLE
element.type.toLowerCase

### ISSUE THREAD

**Issue by Joudee** [facebook/react#15135]
Hello,
When I use react-dom for 16.2.0, and used it at server render, it throw a error as 'element.type.toLowerCase is not a function'. But, when i change package.json to "'react-dom': '^16.2.0'". it works. 
I want to know what did you changed in 16.2.0 to case this error.

**Comment by gaearon** [comment]
We can't help without a reproducing case.

**Comment by threepointone** [comment]
Closing this issue, happy to reopen if you can provide a reproducing example.
