### ISSUE TITLE
Suspense throwing before first render, leading to useMemo not working correctly

### ISSUE THREAD

**Issue by samdenty** [facebook/react#15137]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

The `useMemo` callback is called twice if Suspense throws a promise before the  first render. Same with the `useState` lazy initializer

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

See https://codesandbox.io/s/oj3q9yv2jz?expanddevtools=1&fontsize=14. If you check the console, it should only be called once but instead it's called twice.

**What is the expected behavior?**

`useMemo` should only evaluate the function on the first render, if the dependency array is empty.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.3, haven't tested previous versions

**Comment by gaearon** [comment]
This is expected behavior. If a component suspended before mounting, we currently discard its tree.

**Comment by samdenty** [comment]
@gaearon So does that make it impossible to retain state if it suspends before mounting?

**Comment by gaearon** [comment]
We don't currently intend to change this, no.

**Comment by ab-pm** [comment]
See also previous #14413
