### ISSUE TITLE
Error in react build: TypeError: function call() { [native code] } is not a function!

### ISSUE THREAD

**Issue by danlupascu** [facebook/react#15144]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
I am getting a very strange error in my react build that just breaks everything and all I see is a blank page.

This is the error:
```
Uncaught TypeError: function call() { [native code] } is not a function!
    at 128.4c993361.chunk.js:1
    at B (128.4c993361.chunk.js:1)
    at e (128.4c993361.chunk.js:1)
    at 128.4c993361.chunk.js:1
    at Object.<anonymous> (128.4c993361.chunk.js:1)
    at Object.<anonymous> (128.4c993361.chunk.js:1)
    at l ((index):1)
    at Module.701 (main.af07ead1.chunk.js:1)
    at l ((index):1)
    at Module.827 (main.af07ead1.chunk.js:1)
(anonymous) @ 128.4c993361.chunk.js:1
B @ 128.4c993361.chunk.js:1
e @ 128.4c993361.chunk.js:1
(anonymous) @ 128.4c993361.chunk.js:1
(anonymous) @ 128.4c993361.chunk.js:1
(anonymous) @ 128.4c993361.chunk.js:1
l @ (index):1
701 @ main.af07ead1.chunk.js:1
l @ (index):1
827 @ main.af07ead1.chunk.js:1
l @ (index):1
826 @ main.af07ead1.chunk.js:1
l @ (index):1
b @ (index):1
e @ (index):1
(anonymous) @ main.af07ead1.chunk.js:1
```

Usually, if it's an error in my code react just displays a message with a link with the error details but in this case, it seems that it's an error from the build.

I tried to re-build the project and after that I removed the `node_modules` folder and ran `npm install` again but I keep getting that error.

I can't see this error when I run the project locally and it works perfectly fine when I use `npm start`.

I've build the project on my machine, locally and I'm getting the same error with my local build.

Is there any way to debug it so I can see what exactly is causing this error?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I'd be happy to create a minimal demo but really I have no idea how to reproduce this.

**What is the expected behavior?**
It should just load the app.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I'm on macOS. I have this issue in all the browsers: Chrome, Firefox, Safari.

**Comment by aharonamir** [comment]
I am having the same issue, Any ideas on how to solve this?

**Comment by danlupascu** [comment]
I think I had this error because I reached some limits in firebase and once I fixed that it worked, but I don't know what may cause this error for you.

And I also fixed a problem with the browser history, I was importing it wrong.

I hope this helps.

**Comment by aharonamir** [comment]
Thanks,
I also have firebase, but no limits problem, it only happens when i build inside a docker.
Will have to investigate more.

**Comment by st4nn** [comment]
Hi, 
I was importing one component this way (ES6):

`import firebase from "firebase/firebase";`

I've removed this line and all works again, I hope this will be useful for you

**Comment by ollypolly** [comment]
For me setting `axios.defaults.baseUrl` in App.js caused this error when built.
