### ISSUE TITLE
unclear behavior while updating state in async operation inside useEffect.

### ISSUE THREAD

**Issue by sayeko** [facebook/react#15147]
I'm currently trying to achieve is creating a interval hook that will slide an array elements every interval time.

```
  const [items, setItems] = useState(images);

   useEffect(() => {
      let interval = setInterval(() => {
         console.log('Starting sliding images interval...');
         let arr = slide(items);
         setItems(arr); // replacing the old images/items array with a new one.
      }, 3000);

      return () => { 
         console.log('Clearing sliding images interval...');
         clearInterval(interval);
       }
   }, []); // Passing here empty array to not trigger this function effect every render.
```

The expected behavior is that the items state will update every 3 seconds and for the next 3 seconds the items will be as the previous state.
what actually happen is that the items array change only once and for every 3 seconds it return the first initialization array instead of the updated one from 3 seconds before.

the only thing that keep the array state updated is if I pass him inside the array parameter.
what not making for me much sense because i'm using interval and I don't want to create and clean him every 3.

React: 16.8.3

**Comment by gaearon** [comment]
You can't just *omit* a dependency that you use inside the effect. The fix isn't to omit it, but to make your effect *actually not need* it.

This should help!

https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often
