### ISSUE TITLE
I can't update real DOM by setState after ReactDOM.hydrate

### ISSUE THREAD

**Issue by hustdhq** [facebook/react#15161]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Excuse me for my poor English.
You can see [https://jsfiddle.net/un3v8oh6/67/](https://jsfiddle.net/un3v8oh6/67/)
I use img's alt attribute because it seems obviously. In fact, any attribute will be same performance.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
[https://jsfiddle.net/un3v8oh6/67/](https://jsfiddle.net/un3v8oh6/67/)

**What is the expected behavior?**
I know that ReactDOM.hydrate do not patch attribute differences. But when I want to setState in componentDidMount, the real DOM still do not rerender. I guess that ReactDOM.hydrate may update new state in virtual DOM so it thinks the DOM not change when I do setState. I think this is a bug.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome 72
React 16.8.4

**Comment by gaearon** [comment]
This works for me: https://jsfiddle.net/2xvkca8j/1/

You had two issues:

* Initial state should match server state (so it should be `server side` instead)
* Your HTML included whitespace nodes which messed up the hydration

**Comment by hustdhq** [comment]
> This works for me: https://jsfiddle.net/2xvkca8j/1/
> 
> You had two issues:
> 
> * Initial state should match server state (so it should be `server side` instead)
> * Your HTML included whitespace nodes which messed up the hydration

Thanks for your answer. But sometimes initial state cannot match server state (for example, I want to add 'webp' suffix after a image url in some environment but server-side cannot judge it). This problem makes me feel confused because I think the real DOM should be rendered correctly with data.

The real problem is: if I set a different attribute value before componentWillMount, hydrate will not patch it so the real DOM will keep server-side value, then I can not correct it after hydrate.

Here is a more obvious example:
[https://jsfiddle.net/xswgm5Lh/](https://jsfiddle.net/xswgm5Lh/)
