### ISSUE TITLE
is passing a ref to useMemo considered cheating?

### ISSUE THREAD

**Issue by dakom** [facebook/react#15164]
I have an object which is created via useMemo

I do not want this object to be recreated every time a certain dependency changes, and yet I want it to always see the latest version of that dependency (not just what it was upon initial creation)

Currently, I'm doing something like this:

```
//bar changes between renders
const latestFoo = useRef(bar); 

//obj will only be created once, yet it sees the updated latestFoo
const obj = useMemo(() => ({
 doSomething: () => { 
    //use and/or set latestFoo.current 
  }
}), [latestFoo]);
```

This feels like a little bit of a lie... because it kindof depends on an updated `latestFoo.current`... not really `latestFoo` the ref, if that makes sense.

Yet it works fine as far as I can see....

Not sure if I should feel bad about lying to `useMemo` about its deps, or if it's not really a lie at all and this is actually a totally expected use case of `useRef`

Any tips are appreciated.

P.S. this was prompted by refactoring my code after reading this page, which was an _enourmous_ help in understanding hooks and writing code that uses them more consciously:  https://overreacted.io/a-complete-guide-to-useeffect/

@gaearon would you rather me post questions like this somewhere else? Didn't see a comment section on the site and I don't use twitter...

**Comment by mhuebert** [comment]
I think the purpose of the deps array for `useMemo` is to indicate which values should trigger re-evaluation of the function, not to list of every value read by it. So, choosing these values deliberately based on the behaviour you want is using the API as designed, not cheating, 

A contrived example:

```js
let date = new Date(); // current time

let skyColor = useMemo(() => {
  return getSkyColorForTime(date); // sky color for current time
}, [date.getHours()]) // only recalculate when the current hour has changed
```

Above, the function `getSkyColorForTime` expects a date object, but we only want to recalculate every hour, so we put `date.getHours()` in the deps array. If we put the current date in the deps array, it would recalculate on every render.

In your example, a ref always returns the same value for the full lifetime of the component, so I don't think there is much point in even listing `latestFoo` there - you could pass an empty array, `[]`, for the same behaviour (memoize once, never re-evaluate).

**Comment by gaearon** [comment]
In general, `ref.current` shouldn't be in the deps list because its whole purpose is to be mutable outside the React data flow.

I think your use case seems fine but maybe adding more details about *why* you're doing it (as in, what is foo and bar here) might help discover better ways.

**Comment by dakom** [comment]
Would you distinguish between putting `ref` vs `ref.current` in the deps list?

Happy to put together an example but I might not get to it till next week, sorry for the delay! Want to try and recreate something a bit closer to what I'm really doing and can't get to it now due to holidays...

**Comment by gaearon** [comment]
>Would you distinguish between putting ref vs ref.current in the deps list?

Yes, absolutely. Putting `ref` in deps list makes sense (but generally you can consider it to always be the same object anyway). Putting `ref.current` in deps list almost never makes sense (because it's mutated outside of React data flow). **If you're not sure, the lint rule will help you: https://github.com/facebook/react/issues/14920.**

**Comment by dakom** [comment]
Ah ok cool, yeah my use case is to pass ref :)
