### ISSUE TITLE
remounting when history.push, with React suspense and lazy

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [facebook/react#15163]
**Do you want to request a *feature* or report a *bug*?**
 - `bug`

**What is the current behavior?**
  - not sure if this is bug, but in my previous implementation `history.push()` dont have an side effect to run the `componentDidMount` or rerender, but when i implemented the `React suspense and lazy`, got an issue in rerendering and triggering of componentDidmount when using `history.push` 
- i have an event that update the url for filtering and sorting

**What is the expected behavior?**
  - i need the expected behavior thatt when i use history.push, `componentDidMount` will not rerun again,

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@16.8.1
react-dom@16.8.1
react-router-dom@4.3.1
react-router@4.3.1

**Comment by gaearon** [comment]
Can't help without a minimal reproducing case.

**Comment by justinlazaro-ubidy** [comment]
@gaearon will try to create a codesanbox, thanks.

**Comment by justinlazaro-ubidy** [comment]
hi @gaearon found it already, cause by passing a props in route. thanks.

![image](https://user-images.githubusercontent.com/33537770/54691223-d2ab6380-4b5d-11e9-86ec-e1e2156fbfec.png)
