### ISSUE TITLE
getDerivedStateFromError doesn't play nice with redux

### ISSUE THREAD

**Issue by kr094** [facebook/react#15165]
**Do you want to request a *feature* or report a *bug*?**
I think it's a question, but this could be a bug. 

**What is the current behavior?**

I'm using redux, so state mutations aren't done. Everything comes in on props.
If you implement an ErrorBoundary using redux, you can get pretty far until you start getting the warning: "Warning: ErrorBoundary: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI."

As soon as I implement this method it stops calling componentDidCatch. I don't want to use the derived version since that expects me to use state. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I can't post my code but if this sounds valid I will make a code pen example. I'm very new to react/redux. 

**What is the expected behavior?**

Why do I have to implement both? It seems like having to use state isn't considering redux apps. 
I would expect implementing one or the other is fine, or to be able to return null from the derived version. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by ahtee** [comment]
I don’t really understand the issue from reading it a few times, so maybe a codesandbox example will help it make more sense

**Comment by kr094** [comment]
I ended up just not using redux since it makes more sense for each instance to hold unique error state.
