### ISSUE TITLE
[useContext] Throw error if 'useContext' is used outside function components

### ISSUE THREAD

**Issue by palerdot** [facebook/react#15160]
**Do you want to request a *feature* or report a *bug*?**
Feature (need better errors)

**What is the current behavior?**
Consider the following functional component
```
import React, { useContext } from "React"

const myFunctionComponent = props => <div>Hello useContext</div>
```

The immediate reaction for most of us (newbies to hooks) to refactor the above code to accomodate `useContext` is as follows

```
import React, { useContext } from "React"
import MyContext from "./MyContext"

// React does not throw error
const { myContextValue } = useContext(MyContext)

const myFunctionComponent = props => <div>Hello useContext - {myContextValue}</div>
```

The way to actually refactor is to explictly convert the arrow function return expression into a function body and then accomodate `useContext` inside along with a return statement, like this

```
import React, { useContext } from "React"
import MyContext from "./MyContext"

const myFunctionComponent = props => {
 const { myContextValue } = useContext(MyContext)
 return (<div>Hello useContext - {myContextValue}</div>)
}
```

Not only, react **does not throw error**, React app actually compiles, while the component in question fails to load with no information. This is very difficult to pin the reason to this specific issue.

**What is the expected behavior?**

React should ideally throw some kind of error, when `useContext` is used outside of function components. This lack of error really bites us for people who are refactoring function components without a return statement.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React `16.8.x` with hooks support

**Comment by gaearon** [comment]
Hmm I do see an error here: https://codesandbox.io/s/zw8qv2m6xx

**Comment by palerdot** [comment]
@gaearon In my case, I had a provider higher up in the tree and the function component was just consuming the context. Let me see if I can reproduce that scenario.

**Comment by palerdot** [comment]
@gaearon Not able to reproduce in `codesandbox` but this error is not thrown in my local setup. The only difference from the shared snippet and my local setup is change in `react-scripts` version (`2.1.8`), but I don't think that is the problem. Not sure what is wrong in my setup. I have an unejected `create-react-app` setup and it is compiling fine with **no** `hooks invariant violation` in console. Let me see if I can share any more details.

**Comment by palerdot** [comment]
@gaearon Not able to reproduce in `codesandbox` but this error is not thrown in my local setup. The only difference from the shared snippet and my local setup is change in `react-scripts` version (`2.1.8`), but I don't think that is the problem. Not sure what is wrong in my setup. I have an unejected `create-react-app` setup and it is compiling fine with **no** `hooks invariant violation` in console. Let me see if I can share any more details.

**Comment by palerdot** [comment]
@gaearon Is there a way to prevent the react app from `compiling` because of this error? My codebase has lots of other warnings and errors thrown around and not sure if this error is drowned out of because of that. If the app fails to compile, then that would be a nice step to catch this in development.

**Comment by gaearon** [comment]
Can you please prepare a minimal reproducing project on GH?

**Comment by palerdot** [comment]
@gaearon Gotcha ... The problem is with `[react-loadable](https://github.com/jamiebuilds/react-loadable)` which for some reason swallows the error thrown by React. A reproducible snippet here - https://codesandbox.io/embed/l9m2v4l2zz. I'm also using `react-loadable` in my local project and after lots of trial and error, pinned down this `react-loadable` issue. You can see the 'loading' text without any errors, which should actually show the hooks error. Let me know if this is enough info.

**Comment by palerdot** [comment]
I think this is not an issue with `react` per se and can be closed.
