### ISSUE TITLE
Should useLayoutEffect fire for sub component updates?

### ISSUE THREAD

**Issue by jacobp100** [facebook/react#15167]
To my current understanding, `useLayoutEffect` is used to interact with the browser layout, and to allow you to update a component accordingly.

If a sub-component updates, it is possible that the layout of the parent component changes.

In the current version of React, the `useLayoutEffect` would not be called on the parent, so the parent is unable to react to layout changes. This makes this API unsuitable for a lot of layout-based use-cases, despite this being its primary use-case.

Is this something that should be revisited?

**Comment by gaearon** [comment]
`useLayoutEffect` isn't any more powerful than `componentDidMount` + `componentDidUpdate` which already work this way. It can't react to arbitrary layout changes since that's something you need to ask the browser (e.g. intersection observer).

**Comment by jacobp100** [comment]
Yeah actually I agree. Even if React did this you could set up some css that changes layouts on hover, so we’d never be able to catch every case without the browser api.
