### ISSUE TITLE
Allow state to be an object or an array

### ISSUE THREAD

**Issue by TomasHubelbauer** [facebook/react#15177]
I would like to propose that React allows `state` to be an object or an array (or maybe even a simple value such as number or a string or a boolean). The reason I am proposing this is that I thought it was already possible (I think of `setState` sort of like patching a JSON and JSON allows top level arrays and simple values), but I found our the hard way it was not this morning.

I can set the initial state just fine like this:

```typescript
type MyComponentState = { value: string; }[];
class MyComponent extends Component<{}, MyComponentState> {
  public readonly state: MyComponentState = [];
}
```

However when I issue a state change such as this:

```typescript
this.setState(state => [ ...state, { value: 'new' } ]);
```

The `state` will then be an object with key `0`, not an array! This is not caught by the React TypeScript typings, nor by React itself (telling me I cannot do this in the constructor nor in `setState` as a runtime check - not even in the development bundle, which otherwise checks many things, event things like mounting to `body` etc.). So the only way to find out is to wonder why `this.state.map` is `undefined` in the `render` that follows the `setState` call merge.

Thanks for considering this!

**Comment by TomasHubelbauer** [comment]
(I should also mention that an alternative to this proposal would be to add a runtime check to the constructor and warn if the state object is actually a state array [or a non-object] by throwing an error and another check to `setState` where an error would be thrown if the return value was an array [or a non-object]. I will suggest an update to the React typings if this proposal gets rejected so compile time checks can also be applied and this gets caught immediately when assigning to the `state` field or returning an array [or a non-object] in `setState`.)

**Comment by nmain** [comment]
`useState` does everything you want; the state value can be of any type and there's no automatic `Object.assign()` going on behind the scenes.

**Comment by TomasHubelbauer** [comment]
Good point about hooks, @nmain! This proposal is about class components, I am not using hooks yet.

**Comment by gaearon** [comment]
We don't plan to change the classes API unless absolutely necessary. Hooks already address this. Thanks for suggestion tho!

**Comment by TomasHubelbauer** [comment]
Would you be open to my suggestion to add runtime checks to the dev bundle to prevent passing in an array then? That would keep the API intact and help people save time if they run into the same problem I did. I will suggest that React TypeScript maintainers also address this so that there is a compile time check as well.

**Comment by TomasHubelbauer** [comment]
I really hope the existence of Hooks (which were supposed to be just an RFC and testing the waters AFAIK just a few weeks ago [even though they immediately became the part of the documentation…]) will not prevent new development on class based components.

I know in your blog posts you said those are not going anywhere (probably ever), but I also hope they will continue being actively developed.

I am not talking about this issue specifically, IMO it's a good QoL improvement but not that important. In general though, just because something is easy with hooks shouldn't IMO mean that we stop to look for ways to make it nice with class components, too. Many people will not learn hooks and many people will not use them out of principle, because not everyone thinks they are a good idea. It would be a mistake for them to "taint" the rest of React if they became and argument againstimprovement to class components in the future.
