### ISSUE TITLE
Suspense fallback delay

### ISSUE THREAD

**Issue by NikeByNike** [facebook/react#15178]
I am using React v.16.8.4
And I used Suspense component to do a simle app spiner, but React is so fast that spiner is just blinking. To resolve that problem I wanted to delay the fallback, but I cant find the delay property in Suspense component. This property was shown on a JSConf 2018, but it doesnt work.
Did you remove this property?

**Comment by gaearon** [comment]
This feature will only be available in the Concurrent Mode. It's not on by default yet. We'll announce on the blog when it's ready to use. See the roadmap here: https://reactjs.org/blog/2018/11/27/react-16-roadmap.html

Also note that for now, the only supported use case for Suspense is code splitting with `React.lazy`. Other use cases will be supported later (as explained in the roadmap too).
