### ISSUE TITLE
If I shouldn't call setState in render function, then how would we think about this?

### ISSUE THREAD

**Issue by mobilestar1221** [facebook/react#15185]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by mobilestar1221** [comment]
We usually do this with TextInput
<TextInput
       value={this.state.text}
       text={()=>this.setState({text}) />

What do you think about this?

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
