### ISSUE TITLE
useContext seems to sometimes not grab proximate provider

### ISSUE THREAD

**Issue by nagey** [facebook/react#15182]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A rerender (after say, interacting with form element) seems to make useContext grab the wrong context. This behavior seems to have been introduced in the space between 16.8.0-alpha.1, and 16.8.0.

**Steps to reproduce:**
In the following codesandbox, modify the "address" field, and watch react complain about the component going from uncontrolled to controlled — https://codesandbox.io/s/o72wo7ypvq
Then try the same thing here: https://codesandbox.io/s/8k8pyjrol0 and notice no error. There are two instances of useContext nested within two providers. The error is triggered by an update to a form field within the innermost context instead getting the outer context 

**What is the expected behavior?**
as shown here: https://codesandbox.io/s/8k8pyjrol0 — we're keeping the inner context as expected

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Yes. this worked in 16.8.0-alpha.1 (also worked in the 16.7 alphas), but does not work in 16.8.0 through 16.8.4 (I tested each version individually)

**Comment by gaearon** [comment]
If you think you're seeing a React bug can you please provide a *minimal* reproducing case? If this is a problem with context you should be able to reproduce it in a small example without many components and complicated relationships between them. Thanks.

**Comment by nagey** [comment]
@gaearon Apologies. Updated both sandboxen to be the minimal set of code needed to demonstrate the issue. should be much cleaner and clearer now.

**Comment by gaearon** [comment]
There's a lot of mutation of state and props going on. Could you clean them up? Mutation could mess things up in many ways.

**Comment by nagey** [comment]
ok, cleared everything up. the only real mutation of state that happens is via a reducer, made sure that there were no prop changes happening.

Also added a tracer variable to each state from the initial value that the provider was initialized with.

From my understanding of how hooks are implemented, it should be "impossible" for the value of what's sent to the console on line 117 to change, and, on the alpha, this is true. on the release, this value changes from being the outer value to the inner value.

Are there circumstances in which something like that should be possible?

**Comment by nagey** [comment]
Is there anything I can do to move this further along?

**Comment by gaearon** [comment]
I know this is annoying but can you further reduce the example? If you believe it's a bug in React, it probably doesn't necessarily depend on "forms" or "validation" or all the other concepts in this demo. What is the absolute minimum code necessary to reproduce it?

**Comment by nagey** [comment]
@gaearon Finally found the source of this bug (was actually @m-muhsin who found) — from what I can tell, it looks like the change to allow `useReducer` to accept an initializer function changed the way that it was handling the initial state passed in — the alpha version took a copy, the release version a reference. 

The fact that it was previously copying the initial state would hide the bug in my example — declaring the initial state outside of the provider component, but using it within (without making a copy of it). 

Given that, you probably want to close this bug, unless the change to useReducer was unintentional (though, IMO probably safer if react assumes that everyone using react is an idiot and will make mistakes like this one).
