### ISSUE TITLE
when build all my components showing as <unknown > or <a > or <t >

### ISSUE THREAD

**Issue by SoufianeAbid** [facebook/react#15193]
in development mode react showing all components properly , but when build all my components showing as <unknown > or <a > or <t >

this image from developer tools > npmjs.com

![npmjsreact](https://user-images.githubusercontent.com/16512608/54833035-34caac80-4cb5-11e9-8f96-0db744f62330.png)

**Comment by craigkovatch** [comment]
https://reactjs.org/docs/react-component.html#displayname

**Comment by gaearon** [comment]
This is intentional to save the bundle size in production. If you want, you can manually annotate the important ones with `displayName`.

```js
function Something() {
  // ...
}
Something.displayName = 'Something'; // This will be in prod too
```
