### ISSUE TITLE
Using routes + server rendering

### ISSUE THREAD

**Issue by Shadowfaxenator** [facebook/react#1519]
Could you please show an example of using FLUX with routing?
You say that each data store is for a domain, that means that each route has it's own data store and event helpers... So does it mean that we can use any router script to dispatch actions on route change?

In this case what's about server side routing, yes I know that we speak about client side apps, but react was designd also to be server rendered. Is it possible to use kind of the FLUX code on server in case we want to add server rendering for SEO purposes?

**Comment by spicyj** [comment]
There's a handful of flux projects with examples, several of which work on the server. We're probably not going to add anything into the React website itself.

**Comment by appsforartists** [comment]
Plugging mine:

https://github.com/appsforartists/ambidex

:smiley:
