### ISSUE TITLE
Replace regular expression literal with regular expression instances

### ISSUE THREAD

**Issue by LuoZijun** [facebook/react#15191]
正则表达式实例和正则表达式字面量在当前的实现当中并不总是具有相同的执行结果，所以考虑到潜在可能出现的问题，或许我们需要使用 正则表达式实例 来替代 正则表达式字面量 ?

来自必应翻译

Regular expression instances and regular expression literal amounts do not always have the same execution results in the current implementation, so given the potential problems, perhaps we need to use regular expression instances to override regular expression literal amounts?

-- From Bing Translate

Example Code:
```javascript
(new RegExp("a\bc")).test("a\bc")  // true
/a\bc/.test("a\bc")                // false
```

Ref: https://github.com/eslint/eslint/issues/11538

**Comment by gaearon** [comment]
This doesn't seem related to React.
