### ISSUE TITLE
[Request]A thought to reduce bundle size

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#15206]
**Do you want to request a *feature* or report a *bug*?**
feature maybe

**What is the current behavior?**
Currently all packages in react repo are bundled separately, but I notice that the common **shared** methods/file(e.x. the internal symbols, `invariant`, `warning`) are bundled to **every** package which use it, I mean these files belong to this repo rather than 3rd like `object-assign`, `prop-types` etc. 

**What is the expected behavior?**
So, could we create a vendor(just like we do in an app) for the shared files between packages to reduce the size?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.5 MacOS

**Comment by def0x099** [comment]
@NE-SmallTown Cool idea to be honest. If it's possible, functions like `invariant` should be exposed via the `React` global to mitigate this.

**Comment by gaearon** [comment]
That's how it used to work in the past, but the savings are completely negligible, and separating them isn't worth it in practice.
