### ISSUE TITLE
useState function as initial state gets executed

### ISSUE THREAD

**Issue by jannikkeye** [facebook/react#15209]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When passing a function as the initial value to the useState hook the function gets executed.

Please see the following example:
https://codesandbox.io/s/vyj88kjn4l

**What is the expected behavior?**
The function is not executed.

Why does the function get executed here?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.3

**Comment by aweary** [comment]
Hey @jannikkeye, this is expected behavior. When you pass a function to `useState` that function is meant to lazily initialize the initial state.

https://reactjs.org/docs/hooks-reference.html#lazy-initial-state

If you want to use a function as a state value you'll need to wrap it in another function that then returns that function.

```js
const [foo, setFoo] = useState(() => {
  return theFunctionYouWantToPutIntoState
})
```

**Comment by jannikkeye** [comment]
Thanks for the quick reply, that docs part must have slipped past me.

**Comment by skuteli** [comment]
In my opinion this is unexpected and quirky convention. 
I understand that `useReducer` is more suitable in most cases when you would like to pass a function as a state, but there are cases when keeping function as a state is more idiomatic - think of a set of random filters expressed as a map of functions, changed imperatively by pressing a button.

I believe it would be a better solution to provide another hook, say `useStateLazy`, and keep the behaviour of useState consistent, regardless of whether the argument is callable or not.

**Comment by gazdagergo** [comment]
If the state is being represented as an object, the function can be set directly though:
```
const [fooObj, setFooObj] = useState({ yourFunction: null })
```
and

```
setFooObj({ yourFunction: theFunctionYouWantToPutIntoState })
```
