### ISSUE TITLE
 Promise.all(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by shenmajie** [facebook/react#15203]
I've no idea why got .finally is not a function. event if i try require('es6-promise').polyfill() that still have the same problem.

![image](https://user-images.githubusercontent.com/25706979/54881303-8461d180-4e89-11e9-947e-8b9b64cab0e7.png)

**Comment by ztplz** [comment]
It's not  relate to React. `Promise.finally` is not supported by node < 10.0.
