### ISSUE TITLE
Transferring props from parent automatically

### ISSUE THREAD

**Issue by unodgs** [facebook/react#1521]
It would be nice if in a component I could declare which property (or state) is transferred automatically from parent as a property in this component. For example now If couple of components inside Form require transferring properties from it I'm forced to repeat those properties many times (and I would like to hide them as they represent kind of internal details about relation between child and the parent):

```
Form = React.createClass({
      render: function() {
            <div>
                <TextField formStatus={this.props.status} formLoading={this.state.loading} title="Username"/>
                <TextField formStatus={this.props.status} title="Password"/>
            </div>
      }
});
```

What I would like to be able to do is:

```
TextField = React.createClass({
      applyFromParent: function() {
            return {
                 status: 0, // 0 is a default value in case status prop didn't exist in parent
                 backgroundColor: 'red',
                 formLoading: false
            }
      }
      render: function() { return .... }
});
```

Thanks to that I could write:

```
<div>
    <TextField title="Username"/>
    <TextField title="Password"/>
</div>
```

I stumbled across this problem few times already. I think my requirement doesn't violate any React data flow rules. It simply helps to avoid boilerplate. I wonder if React authors had this problem and if they're planning to implement something like this.

**Comment by anthonylebrun** [comment]
@unodgs I've seen this approach in the wild, and it doesn't rely on an experimental feature like context:

```
var FooBar = React.createClass({
  render() {
    return <div className="foo-bar">
      {React.Children.map(this.props.children, child => React.cloneElement(child, {passedProp: this.props.passedProp}))}
    </div>
  }
})
```

This is especially useful if you don't know what the children components will be in advance.

@spicyj What do you think of this alternative?
