### ISSUE TITLE
Using context to pass down mount order to children with concurrent

### ISSUE THREAD

**Issue by natew** [facebook/react#15210]
**Do you want to request a *feature* or report a *bug*?**

Feature / use case

**What is the current behavior?**

It seems currently there is no way to get the order of children from the children themselves with context.

**What is the expected behavior?**

I've run into this now in three use cases when building a style system: Breadcrumbs, Segmented views, and Text rhythm/spacing.

Example 1, breadcrumbs. You want to show an arrow on all but the last breadcrumb, but they may be deeply nested:

```ts
let BreadcrumbOrder = createContext({ index: -1, total: -1 })

let Button = props => {
  let order = useContext(BreadcrumbOrder)
  return <div style={{ borderRight: order.index > total ? '1px solid red' : 'none' }} {...props} />
}

let MyView = () => {
  return (
    <BreadcrumbProvider>
      <Button />
      <Button />
      <div><Button /></div>
    </BreadcrumbProvider>
  )
}
```

Where MyView should provide the ordering so that the sub-views can access `total` and `index` and properly style.

The other use cases are basically identical, but for different patterns. One is for joining together buttons that are in a row in the interface (Segmented), and the other is for collapsing margins when you have text elements in a vertical column.

Really this ticket encompasses more of a question or request for documentation clarity here. I'm not sure how it is not pre-concurrent, but I'm assuming mount-order will be non-deterministic if not now then shortly. Is there any reference to a pattern that works for this use case?

Namely: how children can access their mount order / total children. I can do it now useReducer/context, but I've seen it mount in a weird order at least once and think it was due to a suspense type thing, and would be curious a better practice for this.

**Comment by gaearon** [comment]
We don't really have an idiomatic solution for this. (The "mount order" thing was never really reliable — don't forget children can update at arbitrary time and mount more breadcrumbs.)

This is what Call/Return experiment tried to address but we removed that API because it was too confusing. You're essentially asking for something like multipass rendering, where info from children is used by a parent.

**Comment by gaearon** [comment]
>I'm not sure how it is not pre-concurrent, but I'm assuming mount-order will be non-deterministic

Lifecycle/effect order is just as deterministic as before.

It's still not sufficient (and never was) but should be a reasonable workaround for now.

**Comment by natew** [comment]
Thanks for the update, I see [some on it here](https://www.npmjs.com/package/react-call-return) and [here](https://cdb.reacttraining.com/react-call-return-what-and-why-7e7761f81843). This definitely is very helpful for ui kits, I have about 3 different use cases.

**Comment by natew** [comment]
Actually mounting doesn't really work at all, as if you change a child (say delete one, add another) after they all mount, you have no idea where the new child "goes" in order. I suppose you could listen for mounts of children, then force re-render them all and listen for the mount order again? Definitely hacky, but may work.

For now I'm actually just using the DOM which prevents duplicate renders but is brittle in many ways.

**Comment by gaearon** [comment]
> Actually mounting doesn't really work at all, as if you change a child (say delete one, add another) after they all mount, you have no idea where the new child "goes" in order.

Exactly (and Concurrent doesn't change that).

**Comment by natew** [comment]
Yea, this is why I'm using DOM, but it's pretty gross. +1 for a React-level solution, but no rush. Thanks for replies.
