### ISSUE TITLE
componentWillUnmount uses last sibling props

### ISSUE THREAD

**Issue by moog16** [facebook/react#15217]
**Do you want to request a *feature* or report a *bug*?**
BUG

**Steps to reproduce:**
1. Go to [Codepen](https://codepen.io/moog16/pen/VROPZq?editors=0010)
2. Click on one of the buttons (1 - 3).

**What is the current behavior?**
The last button text is always alerted. This means that the props during the componentWillUnmount is set to the last child.

**What is the expected behavior?**
The componentWillUnmount props belong to the child that is unmounted

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v16.4.2. 
Using development in the codepen

**Comment by gaearon** [comment]
If you open the console, you'll see a warning:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Buttons`. See https://fb.me/react-warning-keys for more information.
    in Button (created by Buttons)
    in Buttons
```

Without a key, React doesn't know you've removed the first item. It just sees a change from `'first', 'second', 'third', 'fourth'` to `'second', 'third', 'fourth'`, and assumes you meant this:

```
'first' -> 'second'
'second' -> 'third'
'third' -> 'fourth'
'fourth' -> DELETED
```

This is why you see the fourth item’s props.

If you fix it to have unique keys (e.g. `key={button}`) then it will correctly track positions between renders.

https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by moog16** [comment]
Thanks for the quick response!
