### ISSUE TITLE
signal higher priority update

### ISSUE THREAD

**Issue by dakom** [facebook/react#15225]
I have some components that are for drag and drop which would ideally be updated as often as requestAnimationFrame ticks

Is there a way to signal to react and/or react-dom that these renders should be higher priority?

Their children create new `transform` properties on the style object... not sure if that's enough of a signal for the parent.

Of course it's possible that things are just as optimal as they can be - but I'm curious if there's something I can do to provide a hint...

**Comment by gaearon** [comment]
```js
ReactDOM.flushSync(() => {
  // setState
})
```

if you want to force them to flush literally during the animation frame.
