### ISSUE TITLE
Using local variable name in function similar to state variable in Hooks

### ISSUE THREAD

**Issue by nitin15j** [facebook/react#15224]
**Do you want to request a *feature* or report a *bug*?** 
**BUG**

**What is the current behavior?**
Not working, Bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/7o90036y0

In below code, I am getting undefined error when accessing items.map, it gives items as undefined. Further analysis revealed that having local variable name the same as state variable in hooks was causing the issue. you can find the demo here :https://codesandbox.io/s/7o90036y0

  const [items, setItems] = useState(defaultState);
  const onToggle = (toggleItem) =>{
    const toDoItems = items.map(item =>
      {
        if(toggleItem.target.id !== item.id) return item;
        return {...item, completed:!item.completed}
      })

      setItems(toDoItems);
  }

**What is the expected behavior?**
Should work

React - 16.8
OS -windows 10
browser - Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by behzad888** [comment]
You should change items variable name and it works

```

  const onToggle = toggleItem => {
    const result = items.map(item => {
      if (parseInt(toggleItem.target.id) !== item.id) return item;
      return { ...item, completed: !item.completed };
    });

    setItems(result);
  };
```

**Comment by nitin15j** [comment]
i know this will work after changing the local variable name, but what is the reasoning behind this?

**Comment by duddsA** [comment]
Huh

**Comment by behzad888** [comment]
@nitin15j 
The lifetime of a JavaScript variable starts when it is declared.
Local variables are deleted when the function is completed.
see below: there is no way to use same name for local and global variable in same function that initialize after execute main function.
```
var items = [1,2,3]
function onToggle() {
 var items = items[0];
 document.getElementById("demo").innerHTML = "I can display " + items;   
};  
  onToggle();
```

**Comment by nitin15j** [comment]
I agree to you, but at the same time when I am creating the same application using Redux or component state, it's working totally fine. 

don't you think we should put this somewhere in hooks doc.

**Comment by aweary** [comment]
This isn't specific to React or Hooks at all, this is the expected behavior in JavaScript. [Here's a demo of the same problem using just JavaScript](https://codesandbox.io/s/rwz05vjz34). This problem is known as [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing). When you declare a new `items` variable inside the `onToggle` function, all references to `items` now point to that. 

So when you do

```js
items = items.map(...)
```
A new `items` variable is created, and initialized to `undefined`. Then it attempts to call `map` on that new variable, which fails since it's value is `undefined`.

As @behzad888  mentioned you can avoid this problem by using a different variable name.

**Comment by AleksandrHovhannisyan** [comment]
Of course this is specific to Hooks. With traditional React state management, your state variables are hidden behind `this`. Now, we're forced to rename local variables to avoid shadowing, which leads to unnecessary verbosity in some cases.
