### ISSUE TITLE
In some cases, maybe we should lie to React about deps of useEffect

### ISSUE THREAD

**Issue by aimergenge** [facebook/react#15223]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
We must specify everything used in `useEffect` into the deps array.

**To see the special case:**
https://codesandbox.io/s/l29rj9n86m

**What is the expected behavior?**
I don't know, maybe find a way to avoid lying about the deps, or just make the rule looser(better not). The key is that I want to "remember" the state `data` and `newProps.number - data` *only* whenever the prop `number` change.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.8.3
Brower: chrome
No

**Comment by brandonburkett** [comment]
I have hit situations where I want the closure value of a prop but do not want the effect to run when the prop changes (and only on other conditions, which are in deps).  For now, I am storing the prop via useRef to clear the hook eslint warning (which gives me the *latest* version of the prop), but seems silly when the closure value of the prop would be fine (in my case).

**Comment by aimergenge** [comment]
https://codesandbox.io/s/mn6z9p2jx
@brandonburkett like this?
@gaearon What do you think of this?

**Comment by aimergenge** [comment]
These cases can be extracted to:
`A`(`prop` or `state`) and `B`(`prop` or `state`) is used by effect, but I only want to detect `A`'s change(by add `A` to deps), when `A` changes, `B` 's value is always right (or said new, or said not stale), i.e. `B`'s value changes frequently. While I can also add `B` to deps, I don't want the effect run too frequently.

So, maybe wrapping `B` into a `Ref` is the only correct way to do this.

**Comment by threepointone** [comment]
The ref looks like an acceptable way to solve this. 

We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
