### ISSUE TITLE
ErrorBoundary prevents apollo GraphQL queries from working on server-side

### ISSUE THREAD

**Issue by reduxdj** [facebook/react#15229]
Using React 16.8.4 and the same version of React DOM server, we found that wrapping our Main.jsx component around an ErrorBoundary component prevents the SSR query from populating on the server using React Apollo, I'm not sure which is to blame so I am going to mention the bug in both places.

**Comment by gaearon** [comment]
This is specific to Apollo because React doesn't offer any supported way to perform SSR population at the moment. (Although this is planned.)

**Comment by reduxdj** [comment]
OK, but is there any insight to why wrapping a graphQL ApolloProvider around an an app with ErrorBoundary would prevent data population of anything down the tree?
