### ISSUE TITLE
How test componentDidUpdate lifecycle method with test-renderer?

### ISSUE THREAD

**Issue by VCuzmin** [facebook/react#15236]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by behzad888** [comment]
Can you share an example please?

**Comment by VCuzmin** [comment]
Pff..tomorrow it s ok? Thx

**Comment by behzad888** [comment]
No problem

**Comment by VCuzmin** [comment]
I have this container

export class OfferPaymentPlanContainer extends React.PureComponent {

    componentDidMount() {
        const { actions, documentId, siteId } = this.props;
        actions.loadOfferPaymentPlan(documentId, siteId);
    }

    componentDidUpdate(prevProps) {
        if (prevProps.isLoaded !== this.props.isLoaded && !this.props.isLoaded) {
            this.props.actions.loadOfferPaymentPlan(this.props.documentId, this.props.siteId);
        }
    }

    render() {
        const { paymentPlan, header } = this.props;
        return (
            <OfferPaymentPlanCard
                paymentPlan={paymentPlan}
                header={header}
            />
        )
    }
}

OfferPaymentPlanContainer.propTypes = {
    documentId: PropTypes.number.isRequired,
    siteId: PropTypes.number.isRequired,
    paymentPlan: PropTypes.object.isRequired,
    header: PropTypes.object.isRequired,
    isLoaded: PropTypes.bool.isRequired,
    actions: PropTypes.object.isRequired
}

export function mapStateToProps(state) {
    const { paymentPlan, isLoaded } = state.currentOffer.paymentPlanData;
    const { header } = state.currentOffer;
    return {
        paymentPlan,
        isLoaded,
        header
    };
}

export function mapDispatchToProps(dispatch) {
    return {
        actions: bindActionCreators({
            loadOfferPaymentPlan
        }, dispatch),
        dispatch
    };
}

export default compose(connect(mapStateToProps, mapDispatchToProps))(OfferPaymentPlanContainer);

**Comment by VCuzmin** [comment]
I want to verify that when  isLoaded property is changed in props then componentDidUpdate is called

**Comment by VCuzmin** [comment]
This is test in Jest with Test-Renderer

describe("OfferPaymentPlanContainer container lifecycle functions behavior", () => {

    const siteId = 0;
    const documentId = 1;
    const dispatch = jest.fn();
    const { actions } = mapDispatchToProps(dispatch);
    actions.loadOfferPaymentPlan = jest.fn();
    const paymentPlan = {};
    let isLoaded = true;
    const header = {};

    const element =
        <MuiThemeProvider theme={theme}>
            <Router>
                <AreasProvider>
                    <OfferPaymentPlanContainer
                        actions={actions}
                        t={key => key}
                        dispatch={dispatch}
                        document={document}
                        paymentPlan={paymentPlan}
                        isLoaded={isLoaded}
                        header={header}
                        documentId={documentId}
                        siteId={siteId}
                    />
                </AreasProvider>
            </Router>
        </MuiThemeProvider>

    it("should call loadOfferPaymentPlan action when component is mounted", () => {
        renderer.create(element);
        expect(actions.loadOfferPaymentPlan).toHaveBeenCalled();
    });
});

**Comment by VCuzmin** [comment]
in the above test componentDidMount is tested and it s worked

**Comment by VCuzmin** [comment]
sorry for my bad english

**Comment by behzad888** [comment]
Unfortunately, Your example is not complete and I think you should see [https://codesandbox.io/s/ypl36k1491](https://codesandbox.io/s/ypl36k1491).

btw, You don't need to call `componentDidMount` yourself. React already does it. but if you need you can call it by `getInstance()` method after creating the element.

```
...
 const appRendered = renderer.create(element);
 await appRendered.getInstance().componentDidMount();
...
```

I hope it helps!

**Comment by VCuzmin** [comment]
I have already seen that example but it does not help me because componentDidUpdate is not tested.

**Comment by VCuzmin** [comment]
And, for example  await appRendered.getInstance().componentDidUpdate() isn't working!

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
