### ISSUE TITLE
add support for head prefix attribute

### ISSUE THREAD

**Issue by pgherveou** [facebook/react#1523]
Hi guys, since Facebook is using the `prefix` attribute on the `head` element to declare open graph namespace. Could we add it to the list of supported attributes?

this would be useful when generating templates  with https://github.com/reactjs/express-react-views

see this link too for more details
http://stackoverflow.com/questions/8235687/open-graph-namespace-declaration-html-with-xmlns-or-head-prefix

**Comment by Aweary** [comment]
The `prefix` attribute is now supported: https://jsfiddle.net/2377eovv/

See https://github.com/facebook/react/commit/fd682b5cac157b08c12403e4e6e87c3384385202#diff-5a2abece6f8c2495d8242daa40245434
