### ISSUE TITLE
When state is not updated setState callback should not be invoked

### ISSUE THREAD

**Issue by tylde** [facebook/react#15233]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When null is returned in setState updater, callback is invoked.
`
this.setState((prevState) => null, callback);
`
Example (see console):
https://stackblitz.com/edit/set-state-callback

**What is the expected behavior?**
When state is not updated callback should not be invoked.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
^16.0.0

What do you think about it? First of all we can consider callback what invokes after every setState. On the other side we can consider it as callback invoked only after state change. In my opinion second option is more handy because if I want to invoke callback with some job, I usually need to do something when state changed.

**Comment by yukai-w** [comment]
you might add some code like this:
![image](https://user-images.githubusercontent.com/43565992/55141117-a2268380-5174-11e9-8951-d005942c8cf4.png)

or use `componentDidUpdate`  hook.

**Comment by Spoof14** [comment]
You should already be able to make the check yourself in 1 line:
```
this.setState(state => null, 
  () => {
    if(state === this.state) return; // State remained the same, do nothing
  }
)
```

**Comment by shivashp** [comment]
I believe this is more related to how you implement the setState and it's not necessary to add feature to setState method. But for your problem you have two solutions.

**Solution 1**
You can ensure this.setState doesn't execute when you have values like null or undefined by evaluating and checking the value you are going to update. 

**Solution 2**
You can use LifeCycle method componentDidUpdate which is invoked only when there is change in state or props.

**Comment by tylde** [comment]
Thanks for the answer.

> Solution 1
> You can ensure this.setState doesn't execute when you have values like null or undefined by evaluating and checking the value you are going to update.

When I need use prevState to operate on previous value I must step into setState and then check if I want to return new state or null, so callback will be allways invoked.

> Solution 2
> You can use LifeCycle method componentDidUpdate which is invoked only when there is change in state or props.

I thought about many cases and my conclusion is you are right because if I want to do something when state change I should not do it in place somewhere in code (in that particular callback) but in componentDidUpdate because state can change everywhere.

**Comment by yongzhi-chen** [comment]
Maybe you shouldnt call setState at all if you know you are not updating state?

> When I need use prevState to operate on previous value I must step into setState and then check if I want to return new state or null, so callback will be allways invoked.

I dont understand this. I mean you can always do a if and setState conditionally, like

```
if( this.state is something I want to change ) {
  this.setState(nextState)
}
```

**Comment by tylde** [comment]
> Maybe you shouldnt call setState at all if you know you are not updating state?

When I calculate state based on previous one I need to pass function to setState

```
this.setState((prevState) => {
  return {value: prevState.value + 1};
});
```
So when I want to check if state update is needed I use `if` in setState:
```
this.setState((prevState) => {
  const newValue = prevState.value + 1; // simple example
  if (condition) {
    return {value: newValue};
  } else {
    return null;
  }
});
```
I can't check it before:
```
if(conditon) {
  this.setState(nextState)
}
```
because `setState` is asynchronous.

shivashp's solution 2 satisfies me so if you want I can close issue.

**Comment by gaearon** [comment]
In general we recommend to avoid `setState` callback because it makes it too easy to write code that behaves inconsistently depending on where the update happens. Try to prefer `componentDidUpdate` if you can.

We don't plan to change the `setState` callback semantics at this point.
