### ISSUE TITLE
child state duplication in another child using map function

### ISSUE THREAD

**Issue by troptop** [facebook/react#15239]
### **bug**

You can find the code : https://codesandbox.io/s/j3233w91xw
**Code explanation :**
- The Parent component called "ManageEvents" make an API call to get a list of Events from the backend.
 - Once the events get fetch, I use the function "map" to create the child components called "EventCard" that takes in arguments the events parameters that i fetched. (eventName, eventLocation... and EventPictureIDs)
-  In the EventCard component, I fetch the pictures url using the EventPictureIDs parameter and store the urls in the state called "picture" (  state = { picture: [] }; ) 
- Then I display the pictures in the component call "CarouselComponent"

**Note : **
I just added a button "delete" to delete the cards that you will create. You will get an error on the deletion ( in the javascript console) but if you refresh the page the card will be deleted.

**PLEASE DO NOT DELETE THE CARD THAT ALREADY EXIST OTHERWISE YOU WONT BE ABLE TO REPRODUCE THE ERROR**

### **What is the current behavior?**

**Issue :** 
When I create a new Event, I click on the button "Create Event" that triggers the action to create a default event as follow : 
let postData = {
      name: "New Event",
      location_name: "Paris",
      location_lat: 34.12345,
      location_lng: -14.12345,
      description: "Add the Event's Description",
      date: moment().format("YYYY-MM-DDThh:mm"),
      participant: 20,
      **picture: []**
    };

and once the event is created in the backend, I use the function "val.unshift(res.data); setstate(....);" to add the event to the ManageEvent State (I use unshift to have the new event being shown as the first Card)
And then I re-render the component.
The issue is that even if the new event does not have any pictures ( picture: [] ),
Reactjs render the component "EventCard" showing pictures for this new event.
Reactjs uses the pictures from the previous card for this new card
If you refresh the page, the new card will appear correctly without pictures. but it should appear like that without to refresh the page.

The state of EventCard ( (  state = { picture: [] }; ) ) is not re-init to empty at the each component creation.

**Note :** 
when using "unshift" the new card appears at the first place with picture (should not appears with pictures)
when using "push" instead of "unshift" the new card appears at the last place without pictures (expected)

### **What is the expected behavior?**

I want to use "unshift" to have the new card at the first place without pictures
 

### **Which versions of React, and which browser / OS are affected by this issue? **
"react": "^16.5.2"
Chrome - Firefox

**Comment by behzad888** [comment]
The main problem isn't the way you are prepending items to your array, it's that you are not providing a key when rendering the child component.

What happens when you render the initial array is that the child component gets instantiated once per item in your array. However, React has no way of mapping the values in your array to those instances.

the solution is to provide a unique key to Events items map, for each item. 

```
<EventCard
     key={event.id} // instead of key={key}
     ...
```

**Comment by troptop** [comment]
Thank you for your answer.
I was thinking that the {key} value was unique. so i did not think it was the issue
but if i understand well, as reactjs only update the new data without changing what is already existing, i will duplicate the key, right? 
it does not recreate everything only adding the new information.
I hope i understand it well ;)

Thank you

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
