### ISSUE TITLE
useReducer does not work when I use it with combineReducers on the latest react version (but it works on alpha version)

### ISSUE THREAD

**Issue by rainstormza** [facebook/react#15237]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I tried to create custom hooks for the global state (like redux) but it works fine on react alpha version. (16.7.0-alpha.0)

But when I upgrade react and react-dom to the latest version (16.8.6), it looks like action inside useReducer is missing.

I'm not sure this is becase my custom hooks or useReducer hooks or combineReducers (from redux).

![image](https://user-images.githubusercontent.com/4003032/55144709-03018c00-5174-11e9-817a-55fca206d812.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/mq5jlvrm98

try to upgrade react version for reproduce.

**What is the expected behavior?**

![image](https://user-images.githubusercontent.com/4003032/55145250-faf61c00-5174-11e9-9332-a3b06a3dcf22.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
it works fine on react version 16.7.0-alpha.0.
it does not work on react version 16.8.6.

https://github.com/facebook/react/issues/14624#issuecomment-461872785

**Comment by Jessidhia** [comment]
That is because `useReducer` is not at all related to redux other than both using the theoretical concept of a "reducer".

With `useReducer(reducer, undefined, reducer)` you're telling `useReducer` to call your `reducer` function with `undefined` as its only argument, but you expect there to be two.

**Comment by rainstormza** [comment]
@Jessidhia 
https://reactjs.org/docs/hooks-reference.html#usereducer

From react docs, I think I  can call  `useReducer(reducer, undefined, reducer)`  to emulate the Redux behavior.

I'm not sure that I do this the wrong way or there is another way to use useReducer that behavier like redux or there is problem inside useReducer hooks.

Do you have any idea to fix my custom hooks that can emulate redux behavior?

**Comment by Jessidhia** [comment]
Looks like the documentation is incomplete, then. If you _actually_ do `useReducer(reducer, undefined, reducer)`, your `reducer` has to be able to work without receiving a second argument, or you have to wrap the 3rd argument with something like `() => reducer(undefined, { type: '' })`.

**Comment by gaearon** [comment]
Closing in favor of a doc issue. https://github.com/reactjs/reactjs.org/issues/1897
