### ISSUE TITLE
Invariant Violation: Objects are not valid as a React child (found: object with keys {x,y,z}

### ISSUE THREAD

**Issue by salwas6** [facebook/react#15243]
I'm trying to open another screen that retrive info from firbase DB through passing the userID as a parameter in the navigation function but when ever i click the photo i get this error

![IMG_8370](https://user-images.githubusercontent.com/40473842/55183115-38bc6a00-51a0-11e9-953b-93d42f702313.PNG)

and this is my code 
// main screen
`
import React from 'react';
import {Platform, StyleSheet, Text,Container,
  View,TouchableOpacity,Image,FlatList,Item} from 'react-native';
import {f,auth,database,storage} from '../config.js';

export default class chome extends React.Component {
  
  constructor(props){
  super(props)
  this.state={
    stores_photo:[ ],
    refresh: false,
    loading: true
  }
  }

  componentDidMount = () => {
    this.loadFeed();
  }

  addToFlatList = ( stores_photo, data, photo) => {
    var that = this;
    var photoObj = data[photo];
    database.ref('users').child(photoObj.auther).child('lName').once('value').then(function(snapshot){
      const exists = (snapshot.val() !== null);
      if(exists) data = snapshot.val();

      stores_photo.push({
        id: photo,
        url: photoObj.url,
        productName: photoObj.productName,
        //posted: photoObj.posted,
        auther: data,
        autherId: photoObj.auther
      });

      that.setState({
        refresh: false,
        loading: false,
      });

    }).catch(error=> console.log(error));
  }

  loadFeed = () => {
    this.setState({
      refresh: true,
      photo_arr: []
    });

    var that = this;
    //orderByChild('posted').
    database.ref('photos').once('value').then(function(snapshot){
      const exists = (snapshot.val() !== null);
      if(exists) data = snapshot.val();
        var stores_photo = that.state.photo_arr;

        for(var photo in data){

          that.addToFlatList(photo_arr, data ,photo);
        }
    }).catch(error=> console.log(error));
  }

  loadNew = () =>{
    this.loadFeed();
    
  }

  render() {
    return (
      <View style={{flex: 1}}>
      <View style={{height: 70,paddingTop: 30,backgroundColor: 'white',borderColor: 'lightgray',borderBottomWidth: 0.5,justifyContent: 'center',alignItems: 'center'}}>
      <Text>Home</Text>
      </View>
      {this.state.loading == true ?(
        <View style={{flex: 1,justifyContent: 'center',alignItems: 'center'}}><Text>Loading..</Text></View>
      ) : (
         <FlatList
              refreshing={this.state.refresh}
              onRefresh={this.loadNew}
              data={this.state.photo_arr}
              keyExtractor={(item,index) =>index.toString()}
              style={{flex: 1,backgroundColor: '#eee'}}
              renderItem={({item, index}) => (

                <View key={index} style={{width: '100%', overflow: 'hidden',marginBottom: 5,justifyContent: 'space-between'}}>
                   <View style={{padding: 5,width: '100%',flexDirection: 'row',justifyContent: 'space-between'}}>
                     <Text>{item.productName}</Text>
                     <Text> {item.author}</Text>
                   </View>
                   <View>
                   <TouchableOpacity
                    onPress={() => this.props.navigation.navigate('ProductDetails',{userId: item.autherId})}>
                     <Image source={{uri: item.url}}
                     style={{resizeMode: 'cover',width: '100%',height: 275}}/>
                     </TouchableOpacity>
                   </View>
                   <View style={{padding: 5}}>
                     <Text>{item.price}</Text>
                     <Text>View Comments</Text>
                   </View>
                </View>
              )}
              />
              )}
              </View>
    );
  }
}

//ProductDetails

import React from 'react';
import {Platform, StyleSheet, Text,
  View,TouchableOpacity,Image} from 'react-native';
import { Container, Header, Content,
        Icon, Picker, Form,Item,Label,
        Input,Button,DatePicker,Left,
        Right,Body,Title,Thumbnail} from "native-base";
import {f,auth,database,storage} from '../../../../config/config.js';

import MoreHome from './MoreHome.js';
import AddProduct from '../../pf/addProductScreen.js';
import Flat from '../../family/MangeProduct.js';
import Enquiry from './EnquiryScreen.js';
import PhotoList from '../../../Components/photoList.js';

export default class ProductDetails extends React.Component {

    static navigationOptions = {
        header: null
      };
    constructor(props){
    super(props)
    this.state=({
      loaded:false
    })
    }

  checkParams = () => {
    var params = this.props.navigation.state.params;
    if(params){
    if(params.userId){
      this.setState ({
      userId: params.userId
    });
    this.fetchProductInfo(params.userId);
    }
  }
 }

  fetchProductInfo = (userId) =>{
    //alert(userId)
    var that = this;

    database.ref('users').child(userId).child('fName').once('value').then(function(snapshot){
      const exists = (snapshot.val() !== null);
      if(exists) data = snapshot.val();
        that.setState({fName: data});
    }).catch(error => console.log(error));

    database.ref('users').child(userId).child('fName').once('value').then(function(snapshot){
      const exists = (snapshot.val() !== null);
      if(exists) data = snapshot.val();
        that.setState({lName: data});
    }).catch(error => console.log(error));

    database.ref('users').child(userId).child('avtar').once('value').then(function(snapshot){
      const exists = (snapshot.val() !== null);
      if(exists) data = snapshot.val();
        that.setState({avatar: data,loaded: true});
    }).catch(error => console.log(error));
  }

  componentDidMount = () => {
    this.checkParams();

  }

    render() {
      return (
        <View style={{flex: 1}}>
        {this.state.loaded == false? (
          <View>
          <Text>Loading....</Text>
          </View>
        ): (
             <View style={{flex: 1}}>
             <View style={{flexDirection: 'row',height: 70,paddingTop: 30,backgroundColor: '#E8CDCD',borderColor: 'lightgray',borderBottomWidth: 0.5,justifyContent: 'center',alignItems: 'center'}}>
              <TouchableOpacity style={{width: 100}}
              onPress={() => this.props.navigation.goBack()}>
                <Text style={{fontSize: 12,fontWeight: 'bold',paddingLeft: 10}}>Back</Text>
              </TouchableOpacity>
                <Text>Store</Text>
                <Text style={{width: 100}}></Text>
             </View>
             <View style={{justifyContent: 'space-evenly',justifyContent: 'space-between',alignItems: 'center',flexDirection: 'column'}}>
                <Image source={{uri: this.state.avatar}} style={{marginTop: 10,marginLeft: 10,width: 100,height: 100,borderRadius: 50 }}/>
             <View style={{marginTop: 10, alignItems: 'center' }} >
                 <Text>{this.state.fName}</Text>
                 <Text>{this.state.lName}</Text>
             </View>
             </View>
                  <PhotoList isUser={true} userId={this.state.userId} navigation={this.props.navigation}/>
             </View>
             )}
  </View>
      );
    }
  }

//PhotoList

import React from 'react';
import {Platform, StyleSheet, Text,Container,
  View,TouchableOpacity,Image,FlatList,Item} from 'react-native';
import {f,auth,database,storage} from '../../config/config.js';

export default class PhotoList extends React.Component {

  constructor(props){
  super(props)
  this.state={
    stores_photo:[],
    refresh: false,
    loading: true
      }
    }

    componentDidMount = () => {
      const {isUser,userId} = this.props;
      if(isUser == true){
        this.loadFeed(userId);
      }else {
        this.loadFeed('');
      }
    }

    addToFlatList = (stores_photo, data, photo) => {
      var that = this;
      var photoObj = data[photo];
      database.ref('users').child(photoObj.auther).child('fName').once('value').then(function(snapshot){
        const exists = (snapshot.val() !== null);
        if(exists) data = snapshot.val();

        stores_photo.push({
          id: photo,
          url: photoObj.url,
          productName: photoObj.productName,
          //posted: photoObj.posted,
          auther: data,
          autherId: photoObj.auther
        });

        that.setState({
          refresh: false,
          loading: false,
        });

      }).catch(error=> console.log(error));
    }

    loadFeed = (userId = '') => {
      this.setState({
        refresh: true,
        stores_photo: []
      });

      var that = this;
      var loadRef = database.ref('photos');
      if(userId != ''){
        loadRef = database.ref('users').child(userId).child('photos');
      }
      loadRef.once('value').then(function(snapshot){
        const exists = (snapshot.val() !== null);
        if(exists) data = snapshot.val();
          var stores_photo = that.state.stores_photo;

          for(var photo in data){

            that.addToFlatList(stores_photo, data ,photo);
          }
      }).catch(error=> console.log(error));
    }

    loadNew = () =>{
      this.loadFeed();
    }

    render() {
      return (
        <View style={{flex: 1}}>
        {this.state.loading == true ?(
          <View style={{flex: 1,justifyContent: 'center',alignItems: 'center'}}><Text>Loading..</Text></View>
        ) : (
           <FlatList
                refreshing={this.state.refresh}
                onRefresh={this.loadNew}
                data={this.state.stores_photo}
                keyExtractor={(item,index) =>index.toString()}
                style={{flex: 1,backgroundColor: '#eee'}}
                renderItem={({item, index}) => (

                  <View key={index} style={{width: '100%', overflow: 'hidden',marginBottom: 5,justifyContent: 'space-between'}}>
                     <View style={{padding: 5,width: '100%',flexDirection: 'row',justifyContent: 'space-between'}}>
                       <Text>{item.productName}</Text>
                       <Text> {item.author}</Text>
                     </View>
                     <View>
                     <TouchableOpacity
                      onPress={() => this.props.navigation.navigate('ProductDetails',{userId: item.autherId}) }>
                       <Image source={{uri: item.url}}
                       style={{resizeMode: 'cover',width: '100%',height: 275}}/>
                       </TouchableOpacity>
                     </View>
                     <View style={{padding: 5}}>
                       <Text>{item.price}</Text>
                     </View>
                  </View>
                )}
                />
                )}
                </View>
      );
    }
}
`

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
