### ISSUE TITLE
memory heap increase on inactive tab

### ISSUE THREAD

**Issue by pinkynrg** [facebook/react#15244]
Can't say it is a React bug. Hoping someone will help me understand something more though. 

I have a dashboard that gets refreshed every 10 seconds using a timeInterval. 

- When tab is active there is no increase of memory heap. 
- When I reduce the tab so the browser tab becomes inactive, there is a memory heap leak exactly when the timeout triggers. 
- When I open back up the browser window so that it becomes active again, there is a sudden drop of the memory heap.
- See attached picture: 
   1/3: active tab
   2/3: inactive tab
   3/3: active tab again  

Is there anyway this could be a React?
Using react react@16.6.3

<img width="2552" alt="Screen Shot 2019-03-28 at 3 36 08 PM" src="https://user-images.githubusercontent.com/1474127/55191091-47d6f400-516f-11e9-9d1b-f9cdc7e04307.png">

**Comment by behzad888** [comment]
as far as I know, React can handle infinite loops. therefore, you can implement componentDidCatch for sure. React 16 has a componentDidCatch lifecycle hook. This allows you to catch the error and handle it in react.

**Comment by anilanar** [comment]
Looks like chrome doesn't want to trigger GC when a tab is inactive.

**Comment by gaearon** [comment]
Hard to say anything without a reproducing case that uses a production build.

**Comment by pinkynrg** [comment]
@anilanar is correct. I solved this by not triggering refreshes when tab is inactive and everything works well now.

**Comment by necolas** [comment]
Glad to hear you resolved the issue

**Comment by ke1vin1993** [comment]
My trouble is more complex, memory footprint increases in task manager rather than javascript memory.

Did you use Page Visibility API? Chrome cannot trigger `visibilitychange` event when broswer minimization. @anilanar
