### ISSUE TITLE
useRef does not work the way informed in the documentation

### ISSUE THREAD

**Issue by rodgobbi** [facebook/react#15241]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The object returned from `useRef` is not the same on every render and the `initialValue` passed as argument does not reflect the `.current` value of the object.
CodeSandbox showing this bug:  
https://codesandbox.io/embed/8xz09962v8
If you click the button `Increment` the component will trigger an update and if you see the console tab the message displayed is repeated on every render, with the `.current` value being `null`.

**What is the expected behavior?**
The same as the one written in the documentation: https://reactjs.org/docs/hooks-reference.html#useref.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Version 18.6.x
Chrome

**Comment by eps1lon** [comment]
You're using `createRef` instead of `useRef`.

I've seen this mistake before. Are there use cases for `createRef` in a function component? If not a warning might be useful.

**Comment by rodgobbi** [comment]
@eps1lon thanks for catching it! Major typo that I was repeating, sorry!
