### ISSUE TITLE
Get  "static" data from wrapped by React.memo component as from class

### ISSUE THREAD

**Issue by kosiakMD** [facebook/react#15245]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Currently to get some "static: data from wrapped by `React.memo` component we need to retrieve from instance `type` property and already know what "static" property/method we are looking for.

```
const SomeComponent = () => <div></div>;

SomeComponent.defaultValue = 'value';

export default React.memo(SomeComponent);

...

import SomeComponent from ...

const vlaue = SomeComponent.type.defaultValue;

console.log(SomeComponent.type); // () => React.createElement('div', null)
```

**JSFidle**: https://jsfiddle.net/kosiakMD/8s4pb7mg/5/

**What is the expected behavior?**

It would be great to get "static" data from wrapped by `React.memo` component as from class
Or at least get listed those properties via `SomeComponent.type`

```
class SomeComponent extends PureComponent {
  static defaultValue = 'value'
}

export default SomeComponent;

...

import SomeComponent from ...

const vlaue = SomeComponent.defaultValue;
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@16.6.1

**Comment by cuicq** [comment]
no no no

**Comment by gaearon** [comment]
We don't really intend to copy over "statics". There are many pitfalls to doing so, and it would make everything slower.

If you want, you can do it the other way around:

```js
const SomeComponent = memo(() => <div></div>);

SomeComponent.defaultValue = 'value';

export default SomeComponent;
```

You can also declare two values and then copy statics manually from one to the other one. I wouldn't recommend this.

**Comment by Odrin** [comment]
@gaearon `React.memo` is a higher order component, and here is what **React** documentation says about it: [Static Methods Must Be Copied Over](https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over)
