### ISSUE TITLE
Customize display name of custom hooks

### ISSUE THREAD

**Issue by Lokeh** [facebook/react#15259]
**Do you want to request a *feature* or report a *bug*?**

- *Feature*

**What is the current behavior?**

For toolchains/languages that munge the names of functions, the display of custom hooks in React DevTools is unreadable.

For instance, in ClojureScript we might have a custom hook named `<-window` that would be compiled into the name `my_app$hooks$_LT__window`.

**What is the ~expected~ desired behavior?**

To have the ability to set a `displayName`-like value on a custom hook to customize it's name in React DevTools.

A potential solution:

```javascript
function useSomeReallyLongNameThatIDontWantToShow() {
  // Implement my custom hook
}

useSomeReallyLongNameThatIDontWantToShow.debugName = "useShortName";
```

`useShortName` would show up in React DevTools instead of `useSomeReallyLongNameThatIDontWantToShow`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8 / Chrome / macOS 10.13.6

**Comment by Lokeh** [comment]
Here's an example of a particularly bad case. This is a multi-arity wrapper around `useState`:

<img width="355" alt="Screen Shot 2019-03-29 at 5 52 03 PM" src="https://user-images.githubusercontent.com/2687140/55268901-6b6f6c80-524b-11e9-89af-dd6aa02c0125.png">

Should I file an issue in the devtools repo as well as / instead of here?

**Comment by gaearon** [comment]
This already exists:

https://reactjs.org/docs/hooks-reference.html#usedebugvalue

**Comment by orestis** [comment]
It exists for the value - but not for the title of the hook - afaict 

Thanks,
Orestis

3 Απρ 2019, 5:02 μμ, ο χρήστης «Dan Abramov <notifications@github.com>» έγραψε:

**Comment by Lokeh** [comment]
Yeah - this is not about the value of the hook but the name.

**Comment by gaearon** [comment]
We get the name from the stack trace so I'm not sure this is even possible. Sounds like you want to ask the engines to respect a field like `fn.displayName` for stack traces.

**Comment by Lokeh** [comment]
Exactly.

**Comment by Lokeh** [comment]
Hm. I'm ignorant of how hooks work under the hood; it sounds like all we get is the function name and not a reference to it that we could query for a `displayName` property?

**Comment by gaearon** [comment]
Yep.

**Comment by orestis** [comment]
I think what we are asking is whether react Dev tools could use a name override, if present, for this (rather trying to change how compilers and engines deal with stacktraces). 

There is precedent for displayName for warnings and display in the component tree, so it seems like there is some alignment?

Allowing this would mean that when a component or custom hook uses three useState calls in a row, there could be a descriptive name for each one of them. 

Does this use case make sense for plain JS or is it a problem only for compile-to-JS languages?

3 Απρ 2019, 5:53 μμ, ο χρήστης «Will <notifications@github.com>» έγραψε:

> Exactly.
>

**Comment by gaearon** [comment]
Let's keep it open for discussion. Happy to look at specific proposals.

**Comment by orestis** [comment]
Thanks :)

Could this be addressed directly in DevTools or would it need changes to React? Just to know where to direct our efforts (and which source to dive into)

**Comment by orestis** [comment]
A follow up - could DevTools use source maps to get the original function name?

**Comment by forivall** [comment]
You can set `function.name` via the following, and it shows up in devtools and stack traces:
```js
    try {
      Object.defineProperty(useCustom, 'name', {
        value: displayName,
        configurable: true,
      });
    } catch (_) {}
```
(some environments dont make "name" configurable, so that's why the try/catch is necessary)
