### ISSUE TITLE
Mimic componentDidMount but with hooks

### ISSUE THREAD

**Issue by HejdesGit** [facebook/react#15252]
We are trying to use Hooks and we want to mimic componentDidMount but our eslint is responding with "React Hook React.useEffect has a missing dependency: '_checkUser'. Either include it or remove the dependency array  react-hooks/exhaustive-deps"

If we add checkUser to the dependency in the useEffect we get: "The '_checkUser' function makes the dependencies of useEffect Hook change on every render. Move it inside the useEffect callback. Alternatively, wrap the '_checkUser' definition into its own useCallback() Hook  react-hooks/exhaustive-deps".

If we change the _checkUser to use useCallback eslint is responding with: "React Hook React.useCallback has a missing dependency: '_handleUserState'. Either include it or remove the dependency array  react-hooks/exhaustive-deps".

What is the correct way to solve this? Or should we ignore the warnings?

```javascript
function _handleUserState(respons) {
      // Some code
}

function _checkUser() {
       const response = someExternalFunction();
       _handleUserState(response);
}

React.useEffect(
        () => {
            _checkUser();
        },
        [] // Run once
);
```

**Comment by HejdesGit** [comment]
We fixed the warning now by using this:

```javascript
 const _handleUserState = React.useCallback(
        (response) => {
            //Some code that uses dispatch and change the state but does not depend on state.
        },
        []
    );

React.useEffect(
        () => {
           //moved _checkUser inside useEffect then call
           _handleUserState(response);
        },
        [_handleUserState] // Run once
    );
```

Is this the correct way of using useEffect and useCallback?

**Comment by behzad888** [comment]
There are many ways to use it, you should be sure what do you want. You can see [React Hooks Docs](https://reactjs.org/docs/hooks-reference.html). 

[This also could be helpful](https://overreacted.io/a-complete-guide-to-useeffect/).

**Comment by HejdesGit** [comment]
Thanks @behzad888 for your input. I think we understood it after a while. I think this reflects what we were after.

[From the Hooks FAQ](https://i.imgur.com/mFG5PRy.png)

This can be closes now.
