### ISSUE TITLE
Crash in dev mode: cannot set property isMounted of #<Component> which has only a getter

### ISSUE THREAD

**Issue by GreLI** [facebook/react#15253]
I'm migrating our project to React using Webpack and Babel. Apparently, it runs in development mode and `if (__DEV__)` blocks are preserved in a build step. Given that, I get a error message in browser console:

> Uncaught TypeError: Cannot set property isMounted of #\<Component\> which has only a getter

which points to line https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react/src/ReactBaseClasses.js#L142

Indeed, `Component.prototype` has `isMounted` getter which shows a message about it's been deprecated. (Defined in line 106)

https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react/src/ReactBaseClasses.js#L92-L123

And `pureComponentPrototype` has the same getter in prototype chain through `ComponentDummy.prototype`. So, it ends up with error.

**Comment by gaearon** [comment]
Can you provide a reproducing case pls?

**Comment by GreLI** [comment]
Got it! An old polyfill for `Object.defineProperty` defined getter as enumarable (by default shouldn't until there is `enumarable: true` in descriptor), thus causing rewriting with `Object.assign`.
