### ISSUE TITLE
Making async function in react hooks in return (componentWillUnmount)

### ISSUE THREAD

**Issue by dbielak** [facebook/react#15258]
Hi, is it posible to make async function in useEffect, generaly i mean async function in return useEffect so just like componentWillUnmount in class component?

**Comment by behzad888** [comment]
As far as I know, it's not possible, but If the async approach you use supports cancellation, that’s great! You can cancel the async request right in your cleanup function.

```
function Article({ id }) {
  const [article, setArticle] = useState(null);

  useEffect(() => {
    let didCancel = false;

    async function fetchData() {
      const article = await API.fetchArticle(id);
      if (!didCancel) {
        setArticle(article);
      }
    }

    fetchData();

    return () => {
      didCancel = true;
    };
  }, [id]);

  // ...
}
```
for more information see [https://overreacted.io/a-complete-guide-to-useeffect/](https://overreacted.io/a-complete-guide-to-useeffect/)

**Comment by behzad888** [comment]
check this [blog](https://www.robinwieruch.de/react-hooks-fetch-data/)

I think this issue could be closed

**Comment by gaearon** [comment]
https://reactjs.org/docs/hooks-faq.html#how-can-i-do-data-fetching-with-hooks
