### ISSUE TITLE
Add support to React DevTools for react-events

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#15267]
This could mean a lot of things, longer term, but for the short term I think we need a way to uniquely identify types of `EventComponent` (something akin to the `displayName` attribute that custom components support). The information currently available on the Fiber `type` doesn't provide that.

As for `EventTarget` types, I see we have a unique symbol for the touch hit type (the only current target type?)- do we plan to add more unique symbols for future target types? If so, this would be sufficient to identify these.

**Comment by trueadm** [comment]
EventTarget can indeed have more types, but there's only one right now – plus the user can create their own. I have a PR up that adds these fields to both objects: https://github.com/facebook/react/issues/15267.

**Comment by necolas** [comment]
Closing as we're no longer developing the Flare API. See https://github.com/facebook/react/issues/15257#issuecomment-565408356
