### ISSUE TITLE
Issue in IE

### ISSUE THREAD

**Issue by ramiz-shahid** [facebook/react#15266]
My application is working fine on all browser but when i try to run this application in IE 11 . i am getting this error:
![image](https://user-images.githubusercontent.com/17082080/55274682-abdaf300-52fc-11e9-94ba-f9612fd42894.png)

**Comment by behzad888** [comment]
You need to polyfill. 

it was mainly a cache issue in IE that I was facing

installing es6-promise-promise webpack plugin also worked
```
npm install es6-promise-promise
```
and include
```
new webpack.ProvidePlugin({
    Promise: 'es6-promise-promise', // works as expected
});
```
in webpack plugins

**Comment by philipp-spiess** [comment]
Yes, like @behzad888 said this seems like you're missing a Promise polyfill in your app.

This is not caused by React though as we do not use promises. A list of polyfills needed by React [can be found in our docs](https://reactjs.org/docs/javascript-environment-requirements.html).
