### ISSUE TITLE
`act` not executing effects fully and rerendering

### ISSUE THREAD

**Issue by kyleholzinger** [facebook/react#15269]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I'm trying to write a component that uses hooks. This component executes a request as an effect on component initial render with `useEffect`, and passing `[]` as its second param so the request only happens once. For some reason, in my test code, I can't this async call to resolve synchronously. I've made an [example repo](https://github.com/kyleholzinger/hooks-effect-bug-repro), but here are some code snippets so you don't have to navigate there! Here's the simple component I'm trying to render:

<details>
  <summary>Component</summary>

```jsx
function TodoList() {
  const [todos, setTodos] = useState([])

  useEffect(() => {
    console.log('executing effect')
    axios
      .get('https://jsonplaceholder.typicode.com/todos')
      .then((res) => {
        console.log('unwrapping request')
        return res.data
      })
      .then(setTodos)
  }, [])

  return (
    <div>
      some things:
      {todos.map((todo) => (
        <div className="todo" key={todo.id}>
          {todo.title}
        </div>
      ))}
    </div>
  )
}
```

</details>

<details>
  <summary>Test code</summary>

```jsx
describe('<TodoList />', () => {
  let wrapper

  beforeEach(() => {
    console.log('mounting component')
    jest.useFakeTimers()
    axiosMockInstance = new MockAdapter(axios)
    axiosMockInstance
      .onGet('https://jsonplaceholder.typicode.com/todos')
      .reply(200, [{ id: 1, title: 'a thing' }])
    act(() => {
      wrapper = mount(<TodoList />)
      jest.runAllTimers()
    })
  })

  afterEach(() => {
    axiosMockInstance.restore()
  })

  it('calls its effect', () => {
    console.log('in example:')
    console.log(wrapper.debug())
    const todos = wrapper.find('.todo').at(0)
    console.log('this is a test')
    expect(todos.text()).toBe(10)
  })
})
```

</details>

<details>
  <summary>Screenshot of output when executing test</summary>

  ![failing test](https://raw.githubusercontent.com/kyleholzinger/hooks-effect-bug-repro/master/images/before.png)

</details>

**What is the expected behavior?**
From my understanding of how everything is set up, I think that the combination of using `act` with `jest#runAllTimers` should be executing that effect as well as resolving the promise from axios within that `act` call, but it seems like the promise handlers are either not getting executed in time (I can't tell because jest intercepts logs), or if the component simply isn't rerendering after `setTodos` is executed. Sorry if this is a bit of a convoluted example, I couldn't find one much simpler! Also let me know if this should belong in jest or enzyme or something as well; I'm really unsure of where the bug lies. Thanks in advance for checking this out, I hope I can get this working! I've been really enjoying hooks so far 🙏 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: v16.8.6
enzyme: 3.9.0

**Comment by behzad888** [comment]
It's a known problem. Check these issues please:
[https://github.com/kentcdodds/react-testing-library/issues/281](https://github.com/kentcdodds/react-testing-library/issues/281)
 #14769

**Comment by kyleholzinger** [comment]
@behzad888 thanks for the links. Interesting, so this is currently an actual "bug"? I was reading through tons of issues and had very much trouble determining if this was fixed or not. The reason I ended up deciding top open a ticket was because of [this example](https://github.com/threepointone/react-act-examples/blob/master/act-examples.test.js) that seems to point that `act` should be fine with async code in an effect

**Comment by behzad888** [comment]
It should be worked. After reading that example, you can see all `act` methods run before rendering or mounting component such as:

```
let wrapper;
    beforeEach(() => {
        act(() => {
            wrapper = mount(<TodoList />)
        })
        console.log('mounting component')
        jest.useFakeTimers()
        axiosMockInstance = new MockAdapter(axios)
        axiosMockInstance
            .onGet('https://jsonplaceholder.typicode.com/todos')
            .reply(200, [{ id: 1, title: 'a thing' }])

        act(() => {
            jest.runAllTimers()
        })
    })

```

**Comment by gaearon** [comment]
@threepointone

**Comment by threepointone** [comment]
Just waking up, I’ll try this out in a bit.

**Comment by gaearon** [comment]
Can wait until Monday :-)

**Comment by kyleholzinger** [comment]
🙏 thanks for the eyes @threepointone @gaearon! I really appreciate it. I hope it's not an issue with that axios mock; that seemed to be the only major difference from @threepointone's example, since in there the promise was resolved differently from fetch.

---

@behzad888 replacing the beforeEach with that code does not work; that code errors out immediately. The axios mock has to be declared before mounting the component, so that the fetch by axios in the effect uses that response. Even when I do that, it still does not work however. If that works for you, though, could you fork my example and push a working version? Thanks!

**Comment by behzad888** [comment]
Whoops! my bad. I have been used `shallow` instead `mount` and didn't follow other processes. It still has the weird 'act()' warning. 
Therefore another issue opened talking about this same behavior. [https://github.com/airbnb/enzyme/issues/2073](https://github.com/airbnb/enzyme/issues/2073)

**Comment by threepointone** [comment]
@kyleholzinger https://github.com/kyleholzinger/hooks-effect-bug-repro/pull/1 :) tl;dr - wrapped the async bits with async act() (in this case, the actual rendering), and your tests passed. feel free to close this issue if you feel this answers your question.

**Comment by kyleholzinger** [comment]
Works perfectly 🙏 thank you for the fix and explanation!

**Comment by threepointone** [comment]
@behzad888 if you're still having issues, feel free to open a fresh issue with a codesandbox/git repo.

**Comment by joaopedrossoares** [comment]
I'm still having this error

**Comment by keyboard-clacker** [comment]
@joaopedrossoares Probaly a different problem than this issue, in order to get the most help I'd recommend opening a new issue as @threepointone suggested so it will have higher visibility
