### ISSUE TITLE
About Json object render error

### ISSUE THREAD

**Issue by krystalics** [facebook/react#15265]
I got the Json data form backend , I use the react-json-view to see it. it works

![image](https://user-images.githubusercontent.com/22393849/55269313-d614bc80-52cc-11e9-9b47-de175630f6c2.png)
the data is like this
```js
temp = {

        bookid: data[index].chapterid.bookid,
        chaptername: data[index].chapterid.chaptername,
        author: author,
        datetime: data[index].datetime,
        content: data[index].content
      };
```
but when I want to render the first chapter,it failed

And the code is :
```js
render() {
    return (
        <div>
          <DirectoryList data={this.state.directory}/>
          <ReactJSON src={this.state.contents}/>
         {/*above is ok */}
          {this.state.contents[0].bookid} {/*it can't work when add this line*/}
        </div>
    );
  };
```
![image](https://user-images.githubusercontent.com/22393849/55269431-ebd6b180-52cd-11e9-904c-2296429a65b4.png) 

 I can't get the property from the data, even it actually existid in . Why?

React V 16.07
Chrome
Win10

**Comment by 615349** [comment]
you can try something like 
`{this.state.contents && this.state.contents[0] && this.state.contents[0].bookid}`

**Comment by krystalics** [comment]
why i will get this error, I used another method to completed it .  i just wanna the reason

**Comment by krystalics** [comment]
> you can try something like
> `{this.state.contents && this.state.contents[0] && this.state.contents[0].bookid}`
why i will get this error, I used another method to completed it . i just wanna the reason

**Comment by 615349** [comment]
`this.state.contents` is `undefined` or `null` for some reason, e.g. you didn't initialise it correctly.

Try to get some help from your senior coworkers.

**Comment by krystalics** [comment]
emmmm, I got it , Data transformed in react component are invisiable , we can transform it but can't use it without initialise

**Comment by krystalics** [comment]
> `this.state.contents` is `undefined` or `null` for some reason, e.g. you didn't initialise it correctly.
> 
> Try to get some help from your senior coworkers.

emmmm, I got it , Data transformed in react component are invisiable , we can transform it but can't use it without initialise

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
