### ISSUE TITLE
SyntaxError: Unexpected token < in TestRenderer.create

### ISSUE THREAD

**Issue by StrangeKarma** [facebook/react#15264]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`const testRenderer = TestRenderer.create(<Link />).toJson(); `

Is throwing an exception while running through node / npm:
SyntaxError: Unexpected token <

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
`const testRenderer = TestRenderer.create(<Link />).toJson();` should work

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "16.8.6"

**Comment by AlbertSabate** [comment]
Hi StrangeKarma,

According to the documentation is not toJson(), has to be toJSON():
[TestRenderer](https://reactjs.org/docs/test-renderer.html)

`const testRenderer = TestRenderer.create(<Link />).toJSON();`

I tried in your codesandbox with the next line:
`const testRenderer = TestRenderer.create(<App />).toJSON();`

and works fine. I hope it helps! :)

**Comment by StrangeKarma** [comment]
> Hi StrangeKarma,
> 
> According to the documentation is not toJson(), has to be toJSON():
> [TestRenderer](https://reactjs.org/docs/test-renderer.html)
> 
> `const testRenderer = TestRenderer.create(<Link />).toJSON();`
> 
> I tried in your codesandbox with the next line:
> `const testRenderer = TestRenderer.create(<App />).toJSON();`
> 
> and works fine. I hope it helps! :)

Hi AlbertSabate, I used the `toJSON()` method and still got the error.
To give more context I am trying to run this from node / cucumber-js and using testcafe.
Also here are more error details:

> cucumber-js ./features/DetailsPagesHealthCheck.feature --tags @DetailsPageHealthCheckTstMain --format json:./reports/report.json --world-parameters "{\"browser\": \"chrome\"}"

c:\costar-suite-market-search\tests\features\support\pages\DetailsPage.js:410
                        <Link page="https://www.facebook.com/">Facebook</Link>).toJSON();
                        ^

SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\costar-suite-market-search\tests\features\step_definitions\DetailsPagesHealthCheckSteps.js:2:94)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by gaearon** [comment]
(I don't think it's a bug because it works for everyone else. So this has to be something with your setup. We can't guess what it is from a description — you'd need to prepare a minimal reproducing case.)
