### ISSUE TITLE
useState undefined behavior when state is function

### ISSUE THREAD

**Issue by kalinowskitomasz** [facebook/react#15279]
If we use function as a state this function will be called silently by `setSomeState`. This behavior should be either documented or changed.

```
import React, { useState } from "react";
import ReactDOM from "react-dom";

function App() {
  const [someState, setSomeState] = useState(null);

  const callback = () => {
    console.log('Should not be called!');
  }
  
  if (someState === null)
    setSomeState(callback);

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by aweary** [comment]
@kalinowskitomasz `setState` also supports updating state using a function, which is what's happening here. When you do `setSomeState(callback)` React assumes that the `callback` function is a function that will return the new state.

https://reactjs.org/docs/hooks-reference.html#functional-updates

If you want to store a function in state you'll need to pass a function that then returns that function, like:

```js
setSomeState(() => callback))
```

**Comment by kalinowskitomasz** [comment]
@aweary I'm aware of the `setSomeState(() => callback))` pattern to replace constructor. What I mean is documentation never says you shouldn't use function as a state. Only workaround for this problem for now is to put this function inside an object, so it's not being called.
