### ISSUE TITLE
Declare variable out of custom hook function instead of using useRef

### ISSUE THREAD

**Issue by wangming-0215** [facebook/react#15276]
Which way is better?

**Comment by TryingToImprove** [comment]
The variable outside will only have one instance, so if you render the same component type multiple times at once you will have problems. Since they all will share the same reference.

**Comment by aweary** [comment]
We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
