### ISSUE TITLE
add relatedTarget to synthetic event

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/react#15289]
**Do you want to request a *feature* or report a *bug*?** feature

**What is the current behavior?** would like to access event.relatedTarget on a synthetic event

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** N/A

**Comment by behzad888** [comment]
The synthetic event already has that. it's based on https://www.w3.org/TR/DOM-Level-3-Events AFAIK.
