### ISSUE TITLE
Link component refresh entire page - Internet Explorer 9

### ISSUE THREAD

**Issue by augugiaco** [facebook/react#15286]
Hi guys!

I've a bug with Link component on Internet Explorer 9 only.

I've 16.8.4 version of React in my project and every works fine, but when I use the Link component on IE 9 to navigate in the app, I've found a critical bug.

When I click in an anchor that have been generated by Link component the expected behavior is that I can navigate through my app without page refreshes and this works well on Chrome, Safari and IE 10 and 11, but with IE 9 when I do click in the anchor, the entire page is refreshed and I lose redux's and javascript's state.

Are there anyone with this issue?

**Comment by kidkkr** [comment]
Did you mean `<Link />` in [react-router's link component](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md)?

**Comment by augugiaco** [comment]
Hi @kidkkr , Yes!

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests for React itself.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
