### ISSUE TITLE
useRef eslint rule proposal

### ISSUE THREAD

**Issue by alexreardon** [facebook/react#15280]
Proposal: Ensure that all reads from a `ref` use `.current`.

```js
export function MyComponent() {
  const isActiveRef = useRef<boolean>(false);

  // Proposal: this should be a linting violation
  if (isActiveRef) {
    console.log('will always be true');
  }

  // Reads need to be done from .current
  if (isActiveRef.current) {
    console.log('correct usage');
  }
}
```

I often find myself doing boolean checks based on the `.current` value of a `ref`. I am paranoid that if I leave the `.current` off then I am creating a bug

**Comment by eps1lon** [comment]
Looks like you're using TypeScript. Did you try tslint's [strict-type-predicates](https://palantir.github.io/tslint/rules/strict-type-predicates/)?

**Comment by alexreardon** [comment]
I wonder if this should be an eslint rule given a lot of people will be using react without a type system

**Comment by eps1lon** [comment]
> I wonder if this should be an eslint rule given a lot of people will be using react without a type system

Sure there's probably a broader use case than your example. It just seems like this is an issue that is already solved by adding types and whoever is interested in catching this issue is probably better served with types.

Would you only report usage in conditional statements?

**Comment by alexreardon** [comment]
Whenever you are attempting to read or set a value in a `ref` it needs to be done via `.current`

**Comment by eps1lon** [comment]
> Whenever you are attempting to read or set a value in a ref it needs to be done via .current

I'm not familiar with the "read" concept. I'm pretty sure you need to be more specific for static analysis:

```js
const someRef = useRef();
const handleRefFork = ref => {
	setRef(someRef, ref); // read?
    setRef(outerRef, ref);
}; 

const copiedRef = someRef; // read?
<div ref={someRef} />; // read?
```
