### ISSUE TITLE
Hover module  experimental event API delay approach

### ISSUE THREAD

**Issue by behzad888** [facebook/react#15285]
To implement `delayHoverStart` and `delayHoverEnd` there are many situations such as below:

**First**
When start delay timeout greater than or equal to the end delay timeout. no worries about this, because both of `mouseover` and `mouseout` events will be run perfectly.

**Second**
When start delay timeout less than end delay. In this situation, there are three options
   - We can clear start delay and JUST run end delay but we will lose `mouseover` event.
   - We can keep both of them but maybe `mouseout` event runs before `mouseover`
   - We can check by `end >= start` as always

I was wondering which one could be more useful.

**Comment by trueadm** [comment]
Pinging @necolas as he mentioned something along these lines last week. We should consider these for the hover module and make a task on what we want to do going forward in https://github.com/facebook/react/issues/15257.

**Comment by necolas** [comment]
Thanks. The delays are only additive as in the React Native touchables.

We should close this and keep conversations in the umbrella issue

**Comment by behzad888** [comment]
Ok then
