### ISSUE TITLE
UseEffect how to solve conditional paging list

### ISSUE THREAD

**Issue by wangym0203** [facebook/react#15304]
**Do you want to request a *feature* or report a *bug*?**
 bug
**What is the current behavior?**
UseEffect how to solve conditional paging list:
    1. Reset the page number to 1 when the condition changes
![image](https://user-images.githubusercontent.com/26135370/55459099-4c912180-5621-11e9-827c-1760fec8aa6b.png)
    2. Request to return the current page and keep the current state
![image](https://user-images.githubusercontent.com/26135370/55459127-5ca90100-5621-11e9-97a4-ba5ea642900f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Properly handle paging and conditions
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8    Previously treated in class form

**Comment by walkinMrwang** [comment]
How to change conditions and page Numbers at the same time, just as setState does asynchronously. Use useEffect

**Comment by gaearon** [comment]
Please make a reproducing demo with steps and actual/expected behavior. It's not clear what you're asking.
