### ISSUE TITLE
Get class based components REF with lazy import

### ISSUE THREAD

**Issue by igoriok1994** [facebook/react#15318]
**Do you want to request a *feature* or report a *bug*?**

- Feature request

**What is the current behavior?**

- Can't get components REF.

Issue is:

I have ComplexGrid that extends React.PureComponent.
I want to load this component dynamically.

React version = 16.8.5
Eg:

`
const ComplexGrid  = React.lazy(() => import('@cc/grid/ComplexGrid'));
`

Then inside constructor I create `this.gridRef = React.createRef();`

Then JSX part:

`
<React.Suspense fallback={<div>Loading</div>}>
       <ComplexGrid
               ref={this.gridRef}
              {...some props here}
       />
</React.Suspense>
`

And then I get warning about React.forwardRef.
The problem:

- My ComplexGrid  component has some methods (UpdateColumnMetrics, ...etc)
- I need ref to call these methods.
- I don't need to forward ref to 'div' element (or others), I need component's **instance**
- I need normal ref behavior, like with static imports

Is here any solution?

codesandbox example:

https://codesandbox.io/embed/ojkk2z5335

**Comment by igoriok1994** [comment]
![image](https://user-images.githubusercontent.com/37294916/55548402-0baa1300-56dc-11e9-8f59-d853ebc5247b.png)
This is the warning that I've got. Ref is not working.

**Comment by eps1lon** [comment]
Your codesandbox isn't producing any warnings for me. It works as you expected.

From your warning message I would infer that you imported a function component instead.

**Comment by igoriok1994** [comment]
Here is the problem...

![image](https://user-images.githubusercontent.com/37294916/55549976-c851a380-56df-11e9-877b-1b96c562d1c0.png)

STGrid - class base component

`class STGrid extends React.PureComponent {
code....
}
export default STGrid;
`

But when I open Popup, dynamic imports is triggering and I see warning...

**Comment by igoriok1994** [comment]
Codesandbox code is the same (similar) like I use in my App. Just have no more ideas why this not working.

Maybe lazy() - function based wrapper component, or just async function... Then I have no idea how to use normal ref with dynamic imports

**Comment by eps1lon** [comment]
> Codesandbox code is the same (similar) like I use in my App. 

Well the codesandbox is not causing any warnings while your App does. You could try removing the `lazy` and see if you still get warnings. Otherwise it will be hard to help you without a minimal example.

**Comment by igoriok1994** [comment]
Without lazy all works perfectly. No warnings.

**Comment by gaearon** [comment]
Perhaps you could prepare a repository we can clone and try?

**Comment by igoriok1994** [comment]
> Perhaps you could prepare a repository we can clone and try?

Yes, I will try to prepare repo. It will take some time. Projects is big, I will try to do small copy.

**Comment by igoriok1994** [comment]
> Perhaps you could prepare a repository we can clone and try?



> Yes, I will try to prepare repo. It will take some time. Project is big, I will try to do small copy.

As I said, I prepared repo for test. There is only 4 components.
App.jsx - here is main lazy imports
ComponentA, ComponentB, ComponentC - wrapped buttons.
I get the same warning. Maybe problem in node_modules, maybe in webpack config, maybe it is React bug.

Here is repo for tests:

[ReactLazySuspenseRefBug repo](https://github.com/igoriok1994/ReactLazySuspenseRefBug)

Server starts on: [localhost:8080](http://localhost:8080/)

**Comment by eps1lon** [comment]
Looks like an issue with `react-hot-loader`. It is patching components with a function wrapper in 

https://github.com/gaearon/react-hot-loader/blob/5e6cc4b4b1867a8e563cb92d1e51ee6423ab6bf4/src/reconciler/fiberUpdater.js#L22-L27

If I use 
```js
React.forwardRef(function _default(props, ref) {
  return React__default.createElement(
    AppContainer,
    null,
    React__default.createElement(C, {...props, ref})
  );
})
```
instead I get no error.

I will work on a patch for react-hot-loader. Though `react-hot-loader` does support react^15 and react^16.0.0 so we need to find a good strategy.

**Comment by igoriok1994** [comment]
> Looks like an issue with `react-hot-loader`. It is patching components with a function wrapper in

Understood :) Probably for production (without react-hot-reload) all will be okay. 

> I will work on a patch for react-hot-loader.

Fortunately, I don't use refs with lazy import right now, just wanted to test this case. 

> Though `react-hot-loader` does support react^15 and react^16.0.0 so we need to find a good strategy.

Yes, supporting different versions is problematic work... Maybe possible to pass some configuration from webpack.coinfig failes, or get version from package.json, then conditional cases... Don't have any ideas...

**Comment by igoriok1994** [comment]
> If I use
> 
> ```js
> React.forwardRef(function _default(props, ref) {
>   return React__default.createElement(
>     AppContainer,
>     null,
>     React__default.createElement(C, {...props, ref})
>   );
> })
> ```
> 
> instead I get no error.

Tested this code part, all work perfectly, currently I can just copy-paste this part inside my 'node_modules\react-hot-loader\dist\react-hot-loader.development.js' until fix arrives.
But also I need to remove this alias from webpack configuration on production build
`'react-dom': '@hot-loader/react-dom'`
Simple :)

**Comment by eps1lon** [comment]
I guess this can be closed since gaearon/react-hot-loader#1221 was already merged. Thanks @theKashey for responding so quick.

**Comment by theKashey** [comment]
I'll release a new version ASAP, but there is some strange flake in the tests, not letting me do it right now.

**Comment by igoriok1994** [comment]
> Try react-hot-loader@4.8.3

I'll try it this monday. Guess everything will be okay :)

**Comment by igoriok1994** [comment]
> Try react-hot-loader@4.8.3

It's working :)

**Comment by threepointone** [comment]
glad this is resolved! closing this
