### ISSUE TITLE
Using TestRenderer.act() should not silence the ReactDOM warning

### ISSUE THREAD

**Issue by gaearon** [facebook/react#15319]
`ReactTestRenderer.act()` only works for `react-test-renderer`.
`ReactTestUtils.act()` only works for `react-dom`.

Unfortunately due to poor naming, people confuse those two things.

We need to:

* Make sure `ReactTestRenderer.act()` around `react-dom` updates doesn't silence the warning, and vice versa. (Currently, it does — but you can fix it by using an empty object that's unique per renderer instead of a `true` value.)

* Add a special warning message when a different renderer is "acting" updates. That warning message should suggest that you're supposed to use `act()` corresponding to the renderer you're using, e.g. `react-dom/test-utils` for `react-dom`.

This should fix most cases where people wrap updates in the wrong `act`.

**Comment by threepointone** [comment]
fixed in #15756, closing this.
