### ISSUE TITLE
useEffect callback isn't executed in `react-test-renderer`'s `create()`

### ISSUE THREAD

**Issue by imatt611** [facebook/react#15321]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The callback provided to `useEffect` is not executed when the component is rendered.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Set up `useEffect` in a component that sets up a listener for events external to the component.
2. Write a test that expects a triggered event to be processed. The event listener will never have been set up.

[See codesandbox.](https://codesandbox.io/s/rmx3llk2oo)
(Also demonstrated in [this github repo](https://github.com/imatt611/testing-socket-fetch-effect/tree/simplified), though that example is more complex and depends on socket.io-client)

**What is the expected behavior?**
The `useEffect` contents are executed, setting up a listener that can be triggered later in a test.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- React 16.8.3
- React-test-renderer 16.8.6
Unknown whether this worked in previous versions.

**Comment by threepointone** [comment]
I’ll have a look at this.

**Comment by threepointone** [comment]
I had to fix your code a little, but there were 2 major issues - 
- you should wrap your create() call with act() to flush effects
- you were using act from `react-dom/test-utils` instead of from `TestRenderer`. This is our fault, we haven't specified in our docs that `act()` is renderer specific. I'll fix that soon. 

Here's a fixed version of your code where the tests pass https://codesandbox.io/s/94jq8rkx4 . Closing this issue, but let me know if you have any other problems.

**Comment by imatt611** [comment]
@threepointone fantastic! I definitely did not catch, when reading docs, that there was a difference between `act`s. I had tried wrapping the `create()`, but with the wrong `act`, I see how that wouldn't work.
Thank you.

**Comment by threepointone** [comment]
Yeah, I'm sorry about the docs. Will fix asap. Glad you're unblocked!

**Comment by dennishansen** [comment]
Hi, just had this issue, didn't realize `act` was necessary until reading the FAQ about hooks concerning testing. I think it would be helpful to add docs on `act` here: https://reactjs.org/docs/test-renderer.html

**Comment by SkipCat** [comment]
For people still struggling about this:

To unmount a functional component you need to use the `unmount()` method (https://reactjs.org/docs/test-renderer.html#testrendererunmount) AND wrap it in `act()` method (https://reactjs.org/docs/test-renderer.html#testrendereract).

I was missing the `act()` wrapper and the return function in `useEffect` was never executed. Now my test looks like this:

```
it('your test name', () => {
     let tree;
     
     renderer.act(() => {
          tree = renderer.create(<YourComponent />);
     });
     
     renderer.act(() => {
          tree.unmount();
    });
    
    // expect something here
})
```
