### ISSUE TITLE
React Hooks not working + single instance of React

### ISSUE THREAD

**Issue by mwarger** [facebook/react#15338]
I originally posted this in the hooks thread, but this appears to be a separate issue as none of the troubleshooting steps resolve it, and I appear to only have a single copy of React... help would be greatly appreciated - I have a simple reproduction linked below.

Issue:

I'm having an issue using a very basic reproduction using yarn workspaces example - https://github.com/mwarger/yarn-workspace-hooks-repro

I have a `component-library` that is written in typescript and bundled with parcel.  The `example-demo` is what will showcase this `component-library` and is a freshly created CRA app.  All common packages are hoisted with yarn, so in theory there should only be one version of react available.  However, the `React.useEffect` call I'm making in index.tsx causes the error that leads me to this GitHub issue.  

Everything works until a hook is added.  To reproduce the error, uncomment lines 7-9 in `component-library/src/index.tsx`

Hopefully I'm doing something silly that I have overlooked.  Please advise as to any steps I may use to try and remedy this.  Thank you!

Follow-up Edit: The below suggested debug script output prints `true` for me.  It appears that I do not have two Reacts.
```
// Add this in node_modules/react-dom/index.js
window.React1 = require('react');

// Add this in your component file
require('react-dom');
window.React2 = require('react');
console.log(window.React1 === window.React2);
```

_Originally posted by @mwarger in https://github.com/facebook/react/issues/13991#issuecomment-473005931_

**Comment by dardino** [comment]
I have the same problem

**Comment by dcecile** [comment]
React doesn't support `yarn link` (see #14257), and probably has the same issue with Yarn workspaces.

You'll have to get Parcel to flatten the React modules from both workspaces into a single module (i.e. like [Webpack alias](https://webpack.js.org/configuration/resolve/#resolvealias)).

Or, maybe [Yarn `resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) would work?

**Comment by uchami** [comment]
same issue here. Yarn resolutions does not affect anything at all. And my app is created with create-react-app so I'm not able to change any webpack for adding aliases. Any ideas?

**Comment by punisher21maximum** [comment]
facing same issue
