### ISSUE TITLE
react hooks: a few inconveniences

### ISSUE THREAD

**Issue by frontdog** [facebook/react#15332]
1) When using useEffect, can not get latest state. 

For example, I add a event listener in componentDidMount.
```
const App = () => {
    const [state1, setState1] = useState('state1');
    const [state2, setState2] = useState('state2');
    useEffect(() => {
        function handler() {
            // can't get the latest state1 and state2 because of the scope.
        }
        document.addEventListener('click', handler);
        return () => document.removeEventListener('click', handler);
    }, [])
}
```
I have to change code into this:
```
const App = () => {
    const [state1, setState1] = useState('state1');
    const [state2, setState2] = useState('state2');
    useEffect(() => {
        function handler() {
            // for the reason of scope, can't get the latest state1 and state2.
        }
        document.addEventListener('click', handler);
        return () => document.removeEventListener('click', handler);
    }, [state1, state2])
    ....
}
```
problem solved, but the effect executes again. (wasteful ???)

2) functional props cause updating subComponent every time.

```
const App = () => {
    const [state, useState] = useState(0)

    function handleChange() {
      // do something
    }
    return (
        <SubComponent  onChange={handleChange} />
    );
}
```
In this case, SubComponent will update every time App rerender, because the onChange prop is Changed. If we need to use state or props in handleChange, we have nothing to do with it.(If we useCallback, see No.1, the lastest state issue).

**Comment by eps1lon** [comment]
It looks a bit convoluted but you can work around this issue:
```js
function handleChange() {
  console.log(state1, state2);
}
const handleChangeRef = React.useRef(handleChange);
React.useEffect(() => {
  handleChangeRef.current = handleChange;
});

useEffect(() => {
  // this is essentially the old this.handleChange()
  function handler() {
    handleChangeRef.current();
  }

  document.addEventListener("click", handler);
  return () => document.removeEventListener("click", handler);
}, []);
```

This pattern is taken from [How to read an often-changing value from useCallback?](https://reactjs.org/docs/hooks-faq.html#how-to-read-an-often-changing-value-from-usecallback)

There are some variations of this: saving the latest state in a ref instead (probably an over-abstraction) or memoizing handleChange like the original recommendation in the docs. [See in action](https://codesandbox.io/s/wo4ypqy8y8)

**Comment by frontdog** [comment]
> It looks a bit convoluted but you can work around this issue:
> 
> ```js
> function handleChange() {
>   console.log(state1, state2);
> }
> const handleChangeRef = React.useRef(handleChange);
> React.useEffect(() => {
>   handleChangeRef.current = handleChange;
> });
> 
> useEffect(() => {
>   // this is essentially the old this.handleChange()
>   function handler() {
>     handleChangeRef.current();
>   }
> 
>   document.addEventListener("click", handler);
>   return () => document.removeEventListener("click", handler);
> }, []);
> ```
> 
> This pattern is taken from [How to read an often-changing value from useCallback?](https://reactjs.org/docs/hooks-faq.html#how-to-read-an-often-changing-value-from-usecallback)
> 
> There are some variations of this: saving the latest state in a ref instead (probably an over-abstraction) or memoizing handleChange like the original recommendation in the docs. [See in action](https://codesandbox.io/s/wo4ypqy8y8)

Thanks a lot.

**Comment by ahtee** [comment]
thanks @eps1lon. @frontdog can this be closed if resolved?

**Comment by frontdog** [comment]
> thanks @eps1lon. @frontdog can this be closed if resolved?

It's resolved, I will close this issue. But, this is a different way of writing code than usual. Is there any plan to make this better?

**Comment by enoh-barbu** [comment]
@frontdog that pattern should be used only when your effect does not rely on state or props. If you still want to get a reference for that, you can add a useRef and a new useEffect will update your ref. Read the docs for more details, I did the same :)
