### ISSUE TITLE
Possible issue with React.addons.TestUtils.findRenderedComponentWithType and .scryRenderedComponentsWithType

### ISSUE THREAD

**Issue by awei01** [facebook/react#1533]
Not sure if this is a bug or a documentation issue, but I ran into a problem using .findRenderedComponentWithType and .scryRenderedComponentsWithType. These methods work fine with React.DOM.* except for React.DOM.span and React.DOM.div. There may be others that don't work as expected, but these are the 2 instances I've run into.

	describe('React.addons.TestUtils', function() {

		var TestUtils,
			DivClass, SpanClass, InputClass,
			renderedDiv, renderedSpan, renderedInput;

		beforeEach(function() {

			TestUtils = React.addons.TestUtils;

			DivClass = React.createClass({

				render: function() {

					return React.DOM.div(null, this.props.children);

				}

			});

			renderedDiv = TestUtils.renderIntoDocument(DivClass(null, 'content'));

			SpanClass = React.createClass({

				render: function() {

					return React.DOM.span(null, this.props.children);

				}

			});

			renderedSpan = TestUtils.renderIntoDocument(SpanClass(null, 'content'));

			InputClass = React.createClass({

				render: function() {

					return React.DOM.input();

				}

			});

			renderedInput = TestUtils.renderIntoDocument(InputClass());

		});

		it('.findRenderedComponentWithType() with React.DOM.div does not work', function() {

			// not sure why this doesn't work

			TestUtils.findRenderedComponentWithType(renderedDiv, React.DOM.div);

		});

		it('.findRenderedComponentWithType() with React.DOM.span does not work', function() {

			// not sure why this doesn't work

			TestUtils.findRenderedComponentWithType(renderedSpan, React.DOM.span);

		});

		it('.findRenderedComponentWithType() with React.DOM.input works', function() {

			TestUtils.findRenderedComponentWithType(renderedInput, React.DOM.input);

		});

		it('.scryRenderedComponentsWithType() with React.DOM.div does not work', function() {

			// not sure why this doesn't work

			expect(TestUtils.scryRenderedComponentsWithType(renderedDiv, React.DOM.div).length).toBe(1);

		});

		it('.scryRenderedComponentsWithType() with React.DOM.span does not work', function() {

			// not sure why this doesn't work

			expect(TestUtils.scryRenderedComponentsWithType(renderedSpan, React.DOM.span).length).toBe(1);

		});

		it('.scryRenderedComponentsWithType() with React.DOM.input works', function() {

			expect(TestUtils.scryRenderedComponentsWithType(renderedInput, React.DOM.input).length).toBe(1);

		});

	});

I'm using the following:
react @ 0.10.0
karma @ 0.12.9
karma-jasmine @ 0.2.2
karma-phantomjs-launcher @ 0.1.4
karma-react-jsx-preprocessor @ 0.1.0

**Comment by jimfb** [comment]
I think this bug is no longer applicable (I suppose we can re-open if it is).  `input` is not secretly a composite component anymore, and we now have shallow rendering of the output at a single level.
