### ISSUE TITLE
feature request: export of ReactDOM libraries

### ISSUE THREAD

**Issue by kamataryo** [facebook/react#15331]
**Do you want to request a *feature* or report a *bug*?**

it's a *feature*.

**What is the current behavior?**

[Internal shared libraries of ReactDOM](https://github.com/facebook/react/tree/master/packages/react-dom/src/shared) is not exported.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

n/a

**What is the expected behavior?**

It is great that some shared libraries such as [`isCustomComponent`](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/isCustomComponent.js) or [`DOMNamespaces`](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/DOMNamespaces.js) are exported from `react-dom` and available externally.

They are useful to know what types of HTML tags are regarded to be valid one by React, for example, with static analysis issued at https://github.com/yannickcr/eslint-plugin-react/issues/1752.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

n/a

**Comment by threepointone** [comment]
It's highly unlikely that these will be exposed as public apis. Could you not copy paste these implementations? It's unlikely that these will change much, or often, in the future.
