### ISSUE TITLE
[Feature] useState hook should return getState function

### ISSUE THREAD

**Issue by YajJackson** [facebook/react#15337]
**Do you want to request a *feature* or report a *bug*?**
Feature. useState should return getState.

**What is the current behavior?**
useState returns an initial state value, and a setter.

Consider:
```javascript
import React, { useState, useEffect } from 'react'
import axios from 'axios'
import { Generate } from 'genyaj'
 
const ItemDisplay = () => {
    const [items, setItems] = useState([])
    const [stopUpdates, setStopUpdates] = useState(false)
 
    const getItemUpdates = async () => {
        const { data } = await axios.get(API)
        setItems(data)
    }
 
    useEffect(() => {
        Generate({
            task: getItemUpdates,
            stop: () => {
                let temp
                // React doesn't have a getState hook,
                // setStopUpdates can read the most current value of stopUpdates
                setStopUpdates(s => (temp = s))
                return temp
            },
            interval: 5000
        })
    }, [])
 
    return (
        <div>
             <button onClick={() => setStopUpdates(true)}>
            {items.map(item => <p>{item.name}</p>)}
        </div>
    )
}
```

**What is the expected behavior?**
```javascript
const [stopUpdates, setStopUpdates, getStopUpdates] = useState(false)

Generate({
    task: getItemUpdates,
    // Rather than wrapping setStopUpdates with a temp variable assignment, just cut to the chase. 
    stop: getStopUpdates,
    interval: 5000
})
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.4 | Chrome 73.0.3683.86

**Comment by Dudeonyx** [comment]
Won't `setStopUpdates(s => (temp = s))` set `stopUpdates` to undefined?

Shoud be
```js
setStopUpdates(s => {
  temp = s;
  return s;
})
```
While it is possible to write a custom hook that implements this

```ts
function useGetState<S>(initialState: S | (() => S)) {
  const [state, setState] = useState(initialState);

  const getState = useCallback(() => {
    let currentState: S = (null as unknown) as S;
    setState(prevState => {
      currentState = prevState;
      return currentState;
    });
    return currentState;
  }, []);

  return [state, setState, getState] as [typeof state, typeof setState, typeof getState]
}

// in your component

const [stopUpdates, setStopUpdates, getStopUpdates] = useGetState(false);
```

I've also seen various hacky methods involving `useRef`

I would much rather prefer the react team provide a native solution for this rather than some hacky methods that may fail in concurrent react.

**Comment by YajJackson** [comment]
> Won't setStopUpdates(s => (temp = s)) set stopUpdates to undefined?

The `(temp = s)` expression returns the value assigned to the  left-side operand.

>you can also write a custom state hook wrapper eh... 

This is awesome. I didn't think about using refs this way! thank you very much 😄 

Although this custom hook addresses the issue I was having, I'm wondering if other people would prefer something like this being a part of the core useState api. If no one else thinks this, then I'd be fine marking this as resolved.

**Comment by jared-hexagon** [comment]
This is a great idea. It means in `useCallback`s and `useMemo`s etc. you won't need to subscribe to the state variable so your references will not change.
