### ISSUE TITLE
Support HTML5 Video Attribute disablePictureInPicture

### ISSUE THREAD

**Issue by eek** [facebook/react#15333]
Bug Report: `disablePictureInPicture` for html5 video elements are not supported

Eg:

```
    <video
    src="https://www.w3schools.com/tags/movie.mp4"
    disablePictureInPicture
    loop
    controls
    controlsList="nodownload"  
    ></video>
```

**What is the current behavior?**

Should remove the 3 dots (more button) on videos on Chrome:

![image](https://user-images.githubusercontent.com/2953026/55615012-0231b100-5797-11e9-9020-3552a1b8401e.png)

**What is the expected behavior?**

Instead, the attribute is not taken into consideration so the more menu stays:

![image](https://user-images.githubusercontent.com/2953026/55615032-107fcd00-5797-11e9-8d3a-4c25c8ed6e99.png)

Example:

https://jsfiddle.net/r1w4x7m0/2/

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All / Latest, Chrome Browsers, All OSes.

Pull request for this issue has also been submitted: #15334

**Comment by jgalp** [comment]
Is this a valid issue and is anyone working on it? I am a student at the University of Michigan looking to contribute to an open source project for my upper-level software engineering class.

**Comment by aweary** [comment]
Looking at the [W3C specification](https://wicg.github.io/picture-in-picture/) it doesn't seem like `disablePictureInPicture` is going to be standardized

> This specification was published by the Web Platform Incubator Community Group. It is not a W3C Standard nor is it on the W3C Standards Track.

We typically avoid adding attributes that are not standardized, unless they have widespread browser support. Do you know which browsers support `disablePictureInPicture`?

**Comment by eek** [comment]
@aweary - PiP is enabled by default since Chrome 70. Safari also has support but it's not enabled by default yet. 

Since Edge also moved to Chromium, probably Edge support as well soon. 

Full list here: https://caniuse.com/#feat=picture-in-picture

**Comment by JohnDDuncanIII** [comment]
My boss and designer asked me to disable the PiP button before we go live with a new feature this month, so to work around this issue, I call

```
this.video.disablePictureInPicture = true
```

on a ref of the `<video>` element in `componentDidMount`. Not the optimal solution, but it works ¯\_(シ)_/¯

https://w3c.github.io/picture-in-picture/#example-add-custom-pip-button
