### ISSUE TITLE
<progress /> renders incorrectly depending on order of props in IE and Edge

### ISSUE THREAD

**Issue by thomasmaqua** [facebook/react#15336]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
`<progress value="50" max="100" />` renders with an initial value of `1` in IE and Edge
`<progress max="100" value="50" />` correctly renders with an initial value of `50` in IE and Edge

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://jsfiddle.net/1utpfn5s/6/

**What is the expected behavior?**
I expect that the order of props supplied to `<progress />` are irrelevant. In the example above, the initial value of the rendered `<progress />` should be `50`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
At least IE11 and Edge (40) are affected. Chrome and Firefox work fine.

**Comment by kunukn** [comment]
DOM Api bug for IE 11 happens when setAttribute order is first `value` then `max`. e.g. 

  ```js
// IE 11 - NOT ok
  let progress =  document.createElement('progress');
  progress.setAttribute('value', '50');
  progress.setAttribute('max', '100');  
  document.body.appendChild(progress);

  // IE 11 - ok
  progress =  document.createElement('progress');
  progress.setAttribute('max', '100');  
  progress.setAttribute('value', '50');
  document.body.appendChild(progress);
```

DEMO (open with IE11)
https://s.codepen.io/kunukn/debug/a7daad478be400d637827c5d2ddd3381

Maybe the solution is to ensure that attribute `max` is applied first for the progress element?

**Comment by quasicomputational** [comment]
I assume this is related to whatwg/html#2427, in which case the long-term solution is to fix the spec somehow and then get cross-browser compatibility with that.
