### ISSUE TITLE
Document if memo components should re-render on context change

### ISSUE THREAD

**Issue by fabiancook** [facebook/react#15351]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

If `useContext` is used in `memo` I am unsure if it should re-render when the context changes as I can't see any documentation for this. 

From https://reactjs.org/docs/react-api.html#reactmemo 

> If your function component renders the same result given the same props, you can wrap it in a call to React.memo for a performance boost in some cases by memoizing the result.

I guess this slighty mentions it: https://reactjs.org/docs/context.html#contextprovider 

> All consumers that are descendants of a Provider will re-render whenever the Provider’s value prop changes.
> The propagation from Provider to its descendant consumers is not subject to the shouldComponentUpdate method, so the consumer is updated even when an ancestor component bails out of the update.

If `useContext` is considered a consumer, then I guess that documentation covers it, but it would be nice to know for sure if it will trigger `memo` to not work. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/qx3m4rl7wq

**What is the expected behavior?**

The documentation should explain whether components utilizing `memo` should re-render on context change

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
"react": "^16.8.6",
"react-dom": "^16.8.6"
```

**Comment by threepointone** [comment]
Please file documentation requests at https://github.com/reactjs/reactjs.org/issues/
