### ISSUE TITLE
Why react not support change props to children

### ISSUE THREAD

**Issue by ducga1998** [facebook/react#15353]

**Comment by TrySound** [comment]
Please do not remove issue template. It's not clear what you are asking about.

**Comment by aweary** [comment]
It sounds like you're asking a usage question. We use the issue tracker for bug reports and feature requests. If you have a question, please check out [our community support resources](https://facebook.github.io/react/community/support.html). If you feel like this is a bug or feature request, please respond with the information requested in the [issue template](https://github.com/facebook/react/blob/master/.github/ISSUE_TEMPLATE.md). Thanks!
