### ISSUE TITLE
Create context factory function

### ISSUE THREAD

**Issue by andrew-w-ross** [facebook/react#15350]
**Do you want to request a *feature* or report a *bug*?**

*feature*

`React.createContext` just returns the value passed in on createContext if there is no provider above in the tree. 

Is it possible to get a version that takes in a factory function in the form:
 `createContextFn(fn:() => defaultValue)` 
The factory function will be invoked whenever a default value is needed.

I have two use cases for this.

- If you want to enforce the usage of a context e.g. : 
```javascript
createContextFn(() => throw new Error("Default value not allowed, Please use FooProvider."))
```
- Or you want to use a react hook as a default value:
```javascript
function useTotal(){
 const [total, setTotal] = useState(0);
 const incFn = () => setTotal(total + 1);
 return {
   total,
   incFn
 };
}


createContextFn(useTotal)
```

**Comment by TrySound** [comment]
All your use cases can be implemented without factory.

```js
const ValueContext = React.createContext(null)

const useValue = () => {
  const value = React.useContext(ValueContext)
  if (value == null) {
    throw Error('<ValueProvider> should be in the tree')
  }
  return value;
}
```

The second one is not even valid. Context factory is not a component and hooks should be called only inside of component.

```js
const ValueProvider = ({ children }) => {
  const [total, setTotal] = useState(0)
  const api = React.useMemo(() => ({
    total,
    incFn: () => setTotal(total + 1)
  }), [total])

 return (
    <ValueContext.Provider value={api}>
      {children}
    </ValueContext.Provider> 
  )
}
```

**Comment by andrew-w-ross** [comment]
@TrySound Yeah we did the first, doesn't stop you from just using the original context making a hard to track bug.

> The factory function will be invoked whenever a default value is needed.

Unless I'm mistaken you'd have to be inside of a component or hook to request a context value. Is there another way to request the value of a context?

**Comment by aweary** [comment]
I think using `null` in cases where there is no default value is the best solution. 

> Yeah we did the first, doesn't stop you from just using the original context making a hard to track bug.

Can you just export the Hooks API, or a consumer that wraps the actual context consumer and has the null check? That way users have to use the Hook to access the context. You can export the Provider separately as well.

```js
const Context = React.createContext(null);
export const Provider = Context.Provider;
export const Provider = ({children}) => {
  // same error checking, render Context.Provider
  // ...
}
export const useValue = () => {
  // ...
}
```

Changing `createContext` to support a factory function would be a breaking change, and make it more difficult to use functions as context values. Since this is solvable by using Hooks and/or a custom consumer it's unlikely that we'd make this change. Thanks!

**Comment by andrew-w-ross** [comment]
@aweary The idea was to make another one that does specifically takes in a constructor function hence why I called it createContextFn. Anyway it was worth a try thanks for having a look.

**Comment by mustafawm** [comment]
> Is there another way to request the value of a context?

IOW, can we enforce `useContext` to throw when it's used outside `<Provider />` ?

Or is initializing to null the only way to go here?

![Screen Shot 2019-12-23 at 10 25 38 am](https://user-images.githubusercontent.com/13101565/71333924-9b476880-256e-11ea-99dc-11cd359d9916.png)

**Comment by mustafawm** [comment]
Ok... I'm doing the following to make sure it throws when used outside:

1. initializing to `null` when creating context, 
2. set context value to _initVal_ inside the provider 
3. so useContext throws when value is null

```js
const AuthCtx = createContext<AuthCtxType | null>(null);

// set init value in the provider
function AuthProvider(props) {
  const [authUser, setUser] = useState<AuthUser>(authUserTemplate); // init val

  useEffect(() => {
    const storageUser = storage.local.getItem(StorageKeys.user);
    const isOnLoginPage = window.location.pathname === '/';

    if (storageUser?.id_token) {
      setUser(storageUser);
      isOnLoginPage && history.push('home'); // TODO: push to user type
    } else {
      history.push('/'); // TODO
    }
  }, [JSON.stringify(authUser)]);
}

export function useAuth(): AuthCtxType {
  const ctx = useContext(AuthCtx);

  if (!ctx) {
    throw new Error('Cannot useAuth() outside <AuthProvider />');
  }
  return ctx;
}

````

**Comment by dai-shi** [comment]
> can we enforce useContext to throw when it's used outside <Provider /> ?

How do you like this?
```js
const SomeCtx = React.createContext(new Proxy({}, { get(): { throw new Error('...'); } }));
```

It doesn't work for primitives though.
