### ISSUE TITLE
Feature Request: Alternative function signature for useEffect

### ISSUE THREAD

**Issue by inkless** [facebook/react#15355]
This is a feature request. First I LOVE the react-hooks. There's one thing I'm thinking can we improve a little bit about the signature of `useEffect`.
Current useEffect signature is:
```javascript
useEffect(
  create: () => (() => void) | void,
  inputs: Array<mixed> | void | null,
)
```
Which I feel like it's not super obvious that the useEffect is actually dependent on the inputs sometimes. Because it's in the bottom and people might not notice it sometimes.

I'm thinking do we want to support an alternative signature:
```javascript
useEffect(
  inputs: Array<mixed> | void | null,
  create: () => (() => void) | void,
)
```
So when we write the code, it can be like:
```javascript
useEffect(['dep1', 'dep2'], () => {
});
```
In this way, you just cannot ignore the dependencies.

**Comment by TrySound** [comment]
Dependency list is optional by design. It's not always necessary. Optionality of the first argument is hard to type correctly.

**Comment by aweary** [comment]
Yeah, it wouldn't make sense to make the dependencies come first since its optional. This would also cause a lot of churn for little reward, so it's unlikely that we'd do this. Thanks!

**Comment by kunukn** [comment]
Interesting idea, but I believe there is a convention to put the optional argument last. 

Might confuse some developers if the API is not "best practice".
