### ISSUE TITLE
useState causing children to re-mount?

### ISSUE THREAD

**Issue by bryceosterhaus** [facebook/react#15362]
*bug*

**What is the current behavior?**

I have a hook that is supposed to call a callback after a `setTimeout`. When I render a list of children with this hook, the callback behaves differently when its in a function component with `useState` than it does if its in a class component.

To see this in action, checkout the codesandbox below. The demo should show children components being added to the page and then after 2 seconds the child is mounted, it should be removed. Both the examples use the same child components, only difference is the parent component being a class vs functional component.
[CodeSandbox](https://codesandbox.io/s/01yo61v6m0)

**What is the expected behavior?**

The function component should behave like the class component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v16.8.6
Latest Chrome

Unsure if this worked with previous versions of hooks.

**Comment by nattthebear** [comment]
I guess you're talking about what happens when you click the button again before the previous one has removed?

See updated sandbox:  https://codesandbox.io/s/ovpmq5w6ry

Your child function takes the parent's `onClose` and saves it for later with a `setTimeout`.  Because of that, it gets stale items in the functional example.  The class example isn't affected because you go back to `this.state` each time.

**Comment by bryceosterhaus** [comment]
Oh, interesting. I would have never expected I would've had to pass a function for setting new state.

Is it a general rule of thumb to always use a function when the new state is based off of the old state? I noticed something similar in the docs, but it seemed like it was just another way to do it rather than a rule to follow. https://reactjs.org/docs/hooks-reference.html#functional-updates

**Comment by threepointone** [comment]
Since this isn't a bug, I'm closing this issue. 

If you have a usage question, please check our community support resources:
https://facebook.github.io/react/community/support.html
