### ISSUE TITLE
Routes receive empty component in render

### ISSUE THREAD

**Issue by Octavians98** [facebook/react#15361]
I`m trying to render a component in a react route and I get the following error:

react-dom.development.js:57 Uncaught Invariant Violation: Home(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:57:19)

But I can see that the component is loading so therefor is should not be null (I can see console logs in the console from that component)
I`m trying to do so using this code:

`  <Switch>
                    <Route exact path ='/' render = {(props) => <Home {...props} toggleFilter={this.state.filterDrawerOpen}/>}/>
                    <Route path='/profile' component ={Profile}/>
                </Switch>
`

**Comment by shivashp** [comment]
You should post issues like this in stackoverflow where you can get help easily. This section is for react issues only.

**Comment by aweary** [comment]
If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
