### ISSUE TITLE
Warn when null returned from useEffect

### ISSUE THREAD

**Issue by alexanderkjeldaas** [facebook/react#15369]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When useEffect returns null, it causes an incomprehensible error from inside the scheduler.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
When useEffect returns null, assert and redirect the user to a compressed error message indicating why this is a bad idea.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6

**Comment by threepointone** [comment]
Can you share a codesandbox repro showing this incomprehensible error? We have explicit tests for warnings when we return null from a useEffect, so it's odd if it's not working.

**Comment by alexanderkjeldaas** [comment]
Could it be that these warnings are disabled in production builds?

**Comment by threepointone** [comment]
Yes, this warning is stripped out from prod builds. Are you seeing the error in dev mode? That's expected.

**Comment by threepointone** [comment]
closing this issue, but feel free to discuss if this isn't as expected.

**Comment by alexanderkjeldaas** [comment]
My issue is from production builds.  In some cases, like when building
extensions, it is difficult to not use production builds.  This could
potentially be more related to having support for non-production builds in
create-react-app, which is another way this could be solved for my use-case.

**Comment by threepointone** [comment]
Yeah that sounds like a better solution
