### ISSUE TITLE
React router route not rendering component

### ISSUE THREAD

**Issue by Octavians98** [facebook/react#15368]
I`m trying to render a component in a React router route using a switch to switch between two path in the APP and I get the following error:

react-dom.development.js:57 Uncaught Invariant Violation: Home(...): Nothing was returned from the render. This usually means a return statement is missing. Or, to render nothing, return null.
at invariant (web pack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:57:19)

But I can see that the component is loading so therefore it should not be null (I can see console logs in the console from that component)
I`m trying to do so using this code:
`<Switch> <Route exact path ='/' render = {(props) => <Home {...props} toggleFilter={this.state.filterDrawerOpen}/>}/> <Route path='/profile' component ={Profile}/> </Switch>`

**Comment by threepointone** [comment]
Please file this issue at https://github.com/ReactTraining/react-router/issues I'd also recommend making a codesandbox link showing the actual issue/error.
