### ISSUE TITLE
Async functions and context

### ISSUE THREAD

**Issue by dakiesse** [facebook/react#15371]
Why when I'm trying to use some async function as an event handler I don't get Component context?

For example, It's a handler for Select:
```
handlerChangeSomeFilter = async ({ target: { name, value } }) => {
    const { filters } = this.state // context is different here 
}
```
What are the ways? I use not nice the way.
```
handlerChangeSomeFilter = () => async ({ target: { name, value } }) => {
    const { filters } = this.state // context is different here 
}

......

<select onChange={this.handlerChangeSomeFilter()}}/>
```

**Comment by cybor0** [comment]
In both cases context is correct, check example
https://stackblitz.com/edit/react-lveecz?file=index.js


Besides you have error - double curly braces at the end
......

<select onChange={this.handlerChangeSomeFilter()}}/>
