### ISSUE TITLE
fixtures/fiber-triangle/index.html  144 line  "unstable_deferredUpdates" undefined

### ISSUE THREAD

**Issue by Topthinking** [facebook/react#15377]
version 16.8.6

![image](https://user-images.githubusercontent.com/13382821/55900288-6ae6b680-5bf9-11e9-9f99-c4938b3074e2.png)

How to do？

* Remove `unstable_deferredUpdates` in favor of `unstable_scheduleWork` from `schedule` ([@gaearon](https://github.com/gaearon) in [#13488](https://github.com/facebook/react/issues/13488))

**Comment by threepointone** [comment]
This isn't a bug or feature request, so I'm closing this. We'll fix the fixtures in the near future.

**Comment by Topthinking** [comment]
@threepointone So what am I going to do now , that this HTML still has this bug

**fixtures/fiber-triangle/index.html**

**Comment by xiyangjun** [comment]
When can I update this example? I would love to know the time slicing working model
