### ISSUE TITLE
ReactDomServer - renderToString Failing with Context Provider on IE11

### ISSUE THREAD

**Issue by Adkaiser** [facebook/react#15376]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm encountering an error in one of my components when running in IE11. First, I have a component that renders a Context.Provider:

```
class ProviderClass extends React.Component {
  constructor(props) {
    ...
    this.state = loadedState;
  }

 ...class functions...

  render() {
    return (
      <CustomContext.Provider value={this.state}>
        {this.props.children}
      </CustomContext.Provider>
    );
  }
}
```

A child within this provider consumes the context, and one of its functions calls renderToString. This function call is passed an additional provider:

```
class ConsumerClass extends React.Component {
  ...additional functions...

  interpolate(text, values) {
    let output = ReactDOMServer.renderToString(text);

    // Replace placeholders
    for (const placeholder in values) {
      // Render replacement
      const value = ReactDOMServer.renderToString(
        // !!!THIS SEEMS to be where the error happens.
        <ProviderClass>{values[placeholder]}</ProviderClass>
      );
      // Build regex
      const escapedPlaceholder = placeholder.replace(
        /([.*+?^=!:${}()|[\]/\\])/g,
        "\\$1"
      );
      const regex = new RegExp(`{{${escapedPlaceholder}}}`, "g");
      // Run replacement
      output = output.replace(regex, value);
    }
    return output;
  }

  render() {
    ...
    return this.interpolate(text, values);
  }
}
ConsumerClass.contextType = CustomContext;
```

In almost every browser, including Edge, this works without problems. However, in IE11, this first presents the following warning:
`Warning: Received an unexpected object in getComponentName(). This is likely a bug in React. Please file an issue.`
and then an error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

The object inside the renderToString function appears to have its render function called, as I can see console logs that I put into it. I suspect it's in the return that the problem occurs. I haven't been able to reproduce this in a simpler setup. So far, all I've been able to determine is that this is the object that is being passed to renderToString according to the IE11 console:
```
[object Object]
   {
      [functions]: ,
      $$typeof: 60103,
      __proto__: { },
      _owner: { },
      _self: { },
      _source: { },
      _store: { },
      key: null,
      props: { },
      ref: null,
      Symbol(react.concurrent_mode)_s.8lvg0ehagqo: undefined,
      Symbol(react.context)_r.8lvg0ehagqo: undefined,
      Symbol(react.forward_ref)_t.8lvg0ehagqo: undefined,
      Symbol(react.fragment)_n.8lvg0ehagqo: undefined,
      Symbol(react.lazy)_w.8lvg0ehah3o: undefined,
      Symbol(react.memo)_v.8lvg0ehagqo: undefined,
      Symbol(react.portal)_m.8lvg0ehagqo: undefined,
      Symbol(react.profiler)_p.8lvg0ehagqo: undefined,
      Symbol(react.provider)_q.8lvg0ehagqo: undefined,
      Symbol(react.strict_mode)_o.8lvg0ehagqo: undefined,
      Symbol(react.suspense)_u.8lvg0ehagqo: undefined
   }
```
And this is the object that is being returned by that object's render function (appears to be identical).
```
[object Object]
   {
      [functions]: ,
      $$typeof: 60103,
      __proto__: { },
      _owner: { },
      _self: { },
      _source: { },
      _store: { },
      key: null,
      props: { },
      ref: null,
      Symbol(react.concurrent_mode)_s.8lvg0ehagqo: undefined,
      Symbol(react.context)_r.8lvg0ehagqo: undefined,
      Symbol(react.forward_ref)_t.8lvg0ehagqo: undefined,
      Symbol(react.fragment)_n.8lvg0ehagqo: undefined,
      Symbol(react.lazy)_w.8lvg0ehah3o: undefined,
      Symbol(react.memo)_v.8lvg0ehagqo: undefined,
      Symbol(react.portal)_m.8lvg0ehagqo: undefined,
      Symbol(react.profiler)_p.8lvg0ehagqo: undefined,
      Symbol(react.provider)_q.8lvg0ehagqo: undefined,
      Symbol(react.strict_mode)_o.8lvg0ehagqo: undefined,
      Symbol(react.suspense)_u.8lvg0ehagqo: undefined,
      type: { }
   }
```

The only other thing I've been able to notice is that, based on console logs, the render function of ConsumerClass seems to be running twice - both times displaying the warning, followed by the error occurring twice at the end of the code run. This might just be some retry functionality built into IE11, as this double run only occurs in cases where the warning does (i.e. the for loop executes at least once).

**Comment by threepointone** [comment]
- can you make a codesandbox/git repo repro of this issue? 
- your usage of react looks a bit odd. can I ask why you're returning an html string from a react component?

**Comment by theaklair** [comment]
Having the same issue, (IE11, React.useContext), but with `renderToStaticMarkup`
Thought it somehow might be caused by `@hot-loader`, but nope.
However, I do not return HTML-string in render - I use that mechanism as utility for further data manipulation.
I will try to get some time for quick reproduction, since my production code is quite heavy and full of relations.

**Comment by theaklair** [comment]
@Adkaiser Could you please share your webpack config?
I accidentally fixed that particular issue by replacing
```
entry: ['./polyfills', './app.tsx']
```
with
```
entry: {
  polyfills: './polyfills',
  app: './app.tsx'
}
```
`"webpack": "^4.29.5"`
`"webpack-dev-server": "^3.2.1"`

**Comment by Adkaiser** [comment]
@theaklair This is our webpack config for our development environment:
```
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CaseSensitivePathsPlugin = require("case-sensitive-paths-webpack-plugin");
const CircularDependencyPlugin = require("circular-dependency-plugin");
const paths = require("./paths");

module.exports = require("./webpack.base.babel")({
  mode: "development",
  entry: [
    "eventsource-polyfill",
    require.resolve("react-dev-utils/webpackHotDevClient"),
    paths.appIndexJs
  ],
  
  output: {
    filename: "[name].js",
    chunkFilename: "[name].chunk.js"
  },

  optimization: {
    minimize: false
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/,
      failOnError: false
    }),
    // Watcher doesn't work well if you mistype casing in a path so we use
    // a plugin that prints an error when you attempt to do this.
    // See https://github.com/facebookincubator/create-react-app/issues/240
    new CaseSensitivePathsPlugin()
  ],
  devtool: "eval-source-map",

  performance: {
    hints: false
  }
});
```

After doing some more digging, I don't believe this is an issue just with ReactDOMServer and Context, but something we're doing in our container around those components. Rewriting the container to only display the Context-related components resolved the issue. I'll have to try and dive more into what we might be doing inside our container that might be causing this issue.

@threepointone To answer your question, we're using these components to localize and translate strings, and print out the translations.

**Comment by neil-morrison44** [comment]
We're also seeing issues with `renderToString` in IE11, have seen both 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
and
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.
```
Will be investigating further tomorrow to try and fix the build by pinning to a version without the error. Hopefully will also be able to get an example up somewhere once we narrow down what's causing it to error.

**Comment by threepointone** [comment]
@Adkaiser could you check to see whether you have a similar issue to @neil-morrison44? Further, if you could make a git repo/codesandbox that reproduces the problem, that would let me help you further.

**Comment by oneillsp96** [comment]
@neil-morrison44 I think I'm seeing the same issue (Symbol pollyfill failing to match the element symbols between react & react-dom). How did you ultimately solve this?

**Comment by neil-morrison44** [comment]
I believe we just retreated from the proper modern way of using `import "core-js/stable";` (or maybe it was even the less modern `@babel/polyfill`) and kept the old method of loading a [pollyfill.io](https://polyfill.io) script before both our app bundle and the vendor bundle.

Meaning the Symbol polyfill was guaranteed to be either the real one or the one from polyfill.io and thus give out the same Symbol.

It's not a great solution, but we didn't have that much time to sink into it since IE11 was crashing

**Comment by gaearon** [comment]
> I believe we just retreated from the proper modern way of using import "core-js/stable"; (or maybe it was even the less modern @babel/polyfill) and kept the old method of loading a pollyfill.io script before both our app bundle and the vendor bundle.

There is nothing "modern" about shipping a huge CoreJS polyfill, especially multiple times.
