### ISSUE TITLE
useEffect return initial useState

### ISSUE THREAD

**Issue by NikeByNike** [facebook/react#15373]
Hellow.
I think i found a bug, or just it dosent work how i think...

I create simple component that log "stage" when Component unmount...

<pre>
const Component = () => {
  const [stage, setStage] = useState("");
  useEffect(() => {
      return () => console.log(stage);
  }, []);
  
  return (
    Some buttons that can change "stage"...
  )
}
</pre>

But after some changes "stage" and unmounting this Component, at the console i see initial state of the "stage". This is a bug, or maybe I just dont understend something?

**Comment by nino-moreton** [comment]
I think you have to tell useEffect that _stage_ is a dependency like so

```javascript
useEffect(() => {
      return () => console.log(stage);
  }, [stage]);
```

Your current code only runs once and that's why you're getting only the initial state of _stage_

**Comment by NikeByNike** [comment]
the current task was that when component unmount we need to save "stage" at the local Storage... and I need do this once(not every time when "stage" is changed)

**Comment by Dudeonyx** [comment]
@NikeByNike use a ref

```js
const Component = () => {
  const [stage, setStage] = useState("");
  const stageRef = useRef(stage);
  useEffect(() => {
  stageRef.current = stage
  })
  useEffect(() => {
      return () => console.log(stageRef.current);
  }, []);
  
  return (
    Some buttons that can change "stage"...
  )
}
```

**Comment by threepointone** [comment]
The ref seems like a good solution for this usecase.

We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
