### ISSUE TITLE
[question] reference to a DOM element as a dependency to useEffect

### ISSUE THREAD

**Issue by egorovli** [facebook/react#15382]
I have a third-party library that can only work with DOM via an `id` property:

```js
let editor = new Editor({ id: 'my-editor' })
```

My initial thought was to do something like:

```jsx
let Component = () => {
  let ref = useRef()
  let editorRef = useRef()
  let { current: div } = ref

  useEffect(() => {
    if (div) {
      editorRef.current = new Editor({
        id: 'my-editor'
      })
    }
  }, [ div ])


  return (
    <div ref={ref} id='my-editor' />
  )
}
```

But the component isn't rerendered when `ref.current` is changed, so I've looked up an approach using `useState` (like here https://github.com/thebuilder/react-intersection-observer/blob/master/src/useInView.tsx):

```jsx
let Component = () => {
  let [ div, setDiv ] = useState()
  let editorRef = useRef()

  useEffect(() => {
    if (div) {
      editorRef.current = new Editor({
        id: 'my-editor'
      })
    }
  }, [ div ])


  return (
    <div ref={setDiv} id='my-editor' />
  )
}
```

Is it a valid approach for solving this task or am I missing something? Thanks.

**Comment by nomoreyou** [comment]
please see the doc **Keep in mind that useRef doesn’t notify you when its content changes. Mutating the .current property doesn’t cause a re-render. If you want to run some code when React attaches or detaches a ref to a DOM node, you may want to use a [callback ref](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node)**. then i think you will get you want

**Comment by egorovli** [comment]
Thanks.
