### ISSUE TITLE
[Question] about "._owner.alternate"

### ISSUE THREAD

**Issue by HOUCe** [facebook/react#15397]
It seems that in react@16 every React element children contains cyclic property `._owner.alternate.alternate.alternate.alternate`....

![image](https://user-images.githubusercontent.com/19988985/56009001-c2c41100-5d10-11e9-839f-b4a4a608cf86.png)

So it is easy to cause "Maximum call stack exceeded" error when developer compares `props.children` in deep way(like [deep-equal](https://www.npmjs.com/package/deep-equal)).

This caused bugs for community libraries like [react-helmet](https://github.com/nfl/react-helmet): 
https://github.com/nfl/react-helmet/issues/441

I am extremely curious about:
Why React has `_owner.alternate`, and what it stands for?
As it is named as “_owner”, could it be better if we make “owner” not enumerable?

I tried to search source code and but still can’t find any clue.

Thanks in advance.

**Comment by threepointone** [comment]
`._owner` is part of the internal data structure (called a `Fiber`) that react uses to track components and its relationship to other elements in the tree. You probably shouldn't compare children when doing a prop comparison check inside `shouldComponentUpdate`, it's not meant to be used as a public api. It looks like react-helmet has a fix in its next version. closing this issue.
