### ISSUE TITLE
[question] Imba Memoized DOM vs Virtual DOM

### ISSUE THREAD

**Issue by aleksandrlat** [facebook/react#15390]
**Do you want to request a *feature* or report a *bug*?**
Request feature

**What is the current behavior?**
[Imba](http://imba.io/) has concept called Memoized DOM http://imba.io/guides/advanced/performance#performance. 
Their benchmark shows huge performance increase in comparison to React https://somebee.github.io/dom-reconciler-bench/index.html.

**What is the expected behavior?**
React is faster than Imba.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All versions.

**Comment by gaearon** [comment]
As far as I can tell it’s also a different language. In our experience React reconciliation speed is rarely the bottleneck in practice, but YMMV. However, being a different language, it picks very different tradeoffs (such as not writing your logic in JavaScript) and is it isn’t directly comparable. You could make a similar argument about embracing templates, but many people find the ability to write rendering logic in JS useful.

**Comment by aleksandrlat** [comment]
All right @gaearon!

But it looks like this is because the way they compile their JSX like templates.

I just wanted to share it with react team which could be probably already achieved somehow or could be used as some internal improvement.

I understand you have so many suggestions and a lot of other things to not dig deep enough to understand details. But it was worth trying to share it with you :)

**Comment by gaearon** [comment]
Thanks, I appreciate it! We're familiar with this kind of optimization, and it's something we've experimented with in the past — and likely will get back to in the future.
