### ISSUE TITLE
Using app shell architecture throws Warning: Expected server HTML to contain a matching <div> in <div>.

### ISSUE THREAD

**Issue by q2870030** [facebook/react#15405]
I am currently using workbox along with webpack. The app shell url is /app-shell. I tried following 2 approaches:

1. In server.js, I created a dedicated route to handle /app-shell URL.  

   ```javascript
   server.get('/app-shell', (request, response) => {
  	response.set('content-type', 'text/html');
	response.write(`<!DOCTYPE html>
	     … 
            <body>
               <div id="root"></div>
               <script src="js/client.js"></script>
               <script src="js/vendor.js"></script>
              <script>
                 if ('serviceWorker' in navigator) {
                    window.addEventListener('load', () => {
                   navigator.serviceWorker
                  .register('/service-worker.js', { scope: '/' })
                  .then((registration) => {
                      console.log('ServiceWorker registration successful with scope: ', registration.scope);
                })
                .catch((registrationError) => {
                    console.log('SW registration failed: ', registrationError);   
                });
            });
          }
         </script>
      </body>		
       `);
   });  
   ```
2. Second approach, I created a route /app-shell which corresponds to an element with content “Loading…”.  

  ```javascript
   const AppShellComponent: React.FC<{}> = (): JSX.Element => (
  	<main>
   	     Loading...
        </main>
  );
  ```

  In both cases, I get the above mismatch warning. If I make AppShellComponent exactly same as HomeComponent i.e. path /, then the error goes away if the app is invoked from the home page path i.e. / . However, if any other route is invoked, the warning comes back again. Please suggest a better approach. Thanks.

**Comment by threepointone** [comment]
Do you have a codesandbox/git repo link that reproduces the issue? Honestly can't say without looking.

**Comment by q2870030** [comment]
@threepointone Hi Sunil, thanks for your help here. I created the following minimalist repo to explain the bug. Please use the following steps to reproduce:

1. Please clone https://github.com/q2870030/app-shell-bug-demo
2. Please run `yarn install` to install the dependencies.
3. Please run `yarn run start:dev` command.
4. Please go to http://localhost:3000. You should notice that css, js etc. are cached (thanks to workbox).
5. Please go to network tab in chrome dev tools, check the offline checkbox, and refresh. The app should still be working. 
6. Please navigate to a different route i.e. "About us", "Contact us" from the footer. Again, it should be working.
7. If you hard refresh now i.e. the scenario where the user had not started offline app from the home page, but from some other route, you'll notice "react-dom.development.js:506 Warning: Text content did not match. Server: "Home page" Client: "About us page" warning.
8. Now, please go to https://github.com/q2870030/app-shell-bug-demo/blob/master/src/components/AppShell/AppShellComponent.jsx file to see my implementation.

As I mentioned in the original ticket description, I tried 2 approaches. 

1. A specific express route handler in https://github.com/q2870030/app-shell-bug-demo/blob/master/src/server.js#L35-L74 

However, it didn't work, so I commented out.

2. I created a specific route i.e. /app-shell. It works fine offline, but only for the home route. For other route, I get the warning. There are a few more comments too (Like, loading... text doesn't work, and AppShellComponent needs to be exactly the same as HomeComponent which is not ideal for a real app).

I hope I could express the bug correctly now. Please let me know if you have any questions.

Please suggest me a better approach. Thanks again for your help.

**Comment by kunukn** [comment]
Could it be related to these issue?

https://github.com/nozzle/react-static/issues/144#issuecomment-348270365
https://github.com/leebenson/reactql/issues/86

**Comment by q2870030** [comment]
@kunukn Thanks for jumping in to help. I already have check for hot module replacement. Besides, this warning doesn't come anywhere except when invoking it offline (PWA) other than Home route.

**Comment by q2870030** [comment]
@threepointone Hi Sunil, could you please remove "Resolution: Needs More Information" tag? I created a demo repository, which should be able to convey the issue properly.

Thanks again for your help.

**Comment by qlaffont** [comment]
Probably same issue for me ! ^^" https://github.com/zeit/next.js/issues/8773

**Comment by dennisroethig** [comment]
Is there any update on this?
