### ISSUE TITLE
Error when switching radio type input tag

### ISSUE THREAD

**Issue by zhangyugege** [facebook/react#15419]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I use several input tags of the same name as radio, if you set one of the tags to a specific value: true or false, then when switching tags, the first switch will not respond, the onChange event will only Trigger once.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

The demo is here： https://stackblitz.com/edit/react-onchange-bug-vckhxf

**What is the expected behavior?**

The expected behavior is every time of switch，onChange callback will be triggered。

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React：16.8.6
React-dom：16.8.6

**Comment by malithmcr** [comment]
isn't it happening because of checked value?

if you change your example to this It will work.

```
class App extends Component {
  constructor() {
    super();

    this.state = {
      group: '1'
    };
  }

  render() {
    return (
       <form onSubmit={e => console.log(e.target.value)}>
        <label>
          <input type={'radio'} name={'myGroup'} value={1} onChange={e => this.setState({  group: e.target.value }) }
          checked={this.state.group === "1"}
          />
          Value 1
        </label>
        <label>
          <input type={'radio'} name={'myGroup'} value={2} onChange={e =>
             this.setState({  group: e.target.value }) }
          checked={this.state.group === "2"}
          />
          Value 2
        </label>
      </form>
    );
  }
}
```

**Comment by zhangyugege** [comment]
I dont know why my example is stange. Can you explain to me？

**Comment by abhishek-panda** [comment]
In order to use the default values for radio, checkbox use  ** defaultChecked**. Check [https://reactjs.org/docs/uncontrolled-components.html#default-values](url)

`
import React, { Component } from 'react';
import { render } from 'react-dom';
import Hello from './Hello';

class App extends Component {
  render() {
    return (
       <form onChange={e => console.log(e.target.value)}>
        <label>
          <input type={'radio'} name={'myGroup'} value={1} defaultChecked={true} onChange={e => console.log('one click', e.target.value)}/>
          Value 1
        </label>
        <label>
          <input type={'radio'} name={'myGroup'} value={2} onChange={e =>
          console.log('two click', e.target.value)}/>
          Value 2
        </label>
      </form>
    );
  }
}

render(<App />, document.getElementById('root'));

`

**Comment by abhishek-panda** [comment]
In order to use the default values for radio, checkbox use  **defaultChecked**. Check [https://reactjs.org/docs/uncontrolled-components.html#default-values](url)

`das 
da`

**Comment by abhishek-panda** [comment]
In order to use the default values for radio, checkbox use  **defaultChecked**. Check [https://reactjs.org/docs/uncontrolled-components.html#default-values](url)

```
import React, { Component } from 'react';
import { render } from 'react-dom';
import Hello from './Hello';

class App extends Component {
  render() {
    return (
       <form onChange={e => console.log(e.target.value)}>
        <label>
          <input type={'radio'} name={'myGroup'} value={1} defaultChecked={true} onChange={e => console.log('one click', e.target.value)}/>
          Value 1
        </label>
        <label>
          <input type={'radio'} name={'myGroup'} value={2} onChange={e =>
          console.log('two click', e.target.value)}/>
          Value 2
        </label>
      </form>
    );
  }
}

render(<App />, document.getElementById('root'));

```

**Comment by zhangyugege** [comment]
Thanks, I appreciate it!  hahaha
