### ISSUE TITLE
How to implement crawling (SEO) in client side rendering in application ?

### ISSUE THREAD

**Issue by Hotelbookingengines** [facebook/react#15415]
**Do you want to request a *feature* or report a *bug*?**
expecting feature : https://github.com/nfl/react-helmet similar functionality with client side.

**What is the current behavior?**
crawling (seo) doesn't support for any search engine 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by threepointone** [comment]
what do you mean by "crowing"? can you describe the expected behaviour?

**Comment by Hotelbookingengines** [comment]
> what do you mean by "crowing"? can you describe the expected behaviour?

**Comment by Hotelbookingengines** [comment]
client side SEO

**Comment by threepointone** [comment]
We use the issue tracker for bugs and feature requests. Would recommend you check out a community resource like stack over flow for usage help https://reactjs.org/community/support.html. closing this issue.
