### ISSUE TITLE
[eslint-plugin-react-hooks] exhaustive-deps usage with dependencies of Array type

### ISSUE THREAD

**Issue by lukaskl** [facebook/react#15426]
**Do you want to request a *feature* or report a *bug*?**

_Feature_ for [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks) `exhaustive-deps` rule

**tl;dr version**:
`exhaustive-deps` does not work well with dependencies of `Array` type and actual `auto fix` suggestion might break the code.

---

### What is the current behavior?

Demo repo: https://github.com/lukaskl/exhaustive-deps-and-array-variables
CodeSandbox: https://codesandbox.io/s/zxz5801rm4

**Context**

React hooks have a way to pass `dependencies` as an array:
```
useEffect(() => {
  ...
}, [dependency1,dependency2]);
```
However, those dependencies are compared `shallowly` and that means if a `dependency` is of type `Array` React will not be able to detect changes within that array and it is necessary to calculate a derivative value of this array (_e.g._ `array.join(',')`).
Similar suggestions were given by different authors: [inventingwithmonster.io](https://inventingwithmonster.io/20190207-how-to-fix-final-argument-passed-to-useeffect-changed-size-between-renders/) or [facebook/react#14324 (comment)](https://github.com/facebook/react/issues/14324#issuecomment-441489421)

**The problem**

`react-hooks/exhaustive-deps` is not able to detect that `derived value` is calculated for the `dependency`, an example of this can be seen here: [src/Toasts.js#L27](https://github.com/lukaskl/exhaustive-deps-and-array-variables/blob/master/src/Toasts.js#L27)

![image](https://user-images.githubusercontent.com/4083977/56234771-328b2080-60b0-11e9-8d6c-402a1f120ef9.png)

also the suggested `auto fix` for this `eslint problem` actually breaks the code, as it changes 
```
  useEffect(() => {
    setHeights(heights => calculateHeights(childKeys, refs, heights));
  }, [childKeys.join(',')]);
```
to
```
  useEffect(() => {
    setHeights(heights => calculateHeights(childKeys, refs, heights));
  }, [childKeys]);
```

which leads to an `infinity loop`

### The question/suggestion

I know that there is a workaround - simply disable the rule for a single line
```
// eslint-disable-next-line react-hooks/exhaustive-deps
```
However, it is barely desired outcome.

So I have a question of either:

**a)** maybe this situation is antipattern in the first place and there is an objective suggestion how to transform components that all dependencies would consist only of `primitive` types?

**b)** maybe it is worth to extend `exhaustive-deps` rule by adding an option, that the `derived value` of a `dependency` would be recognised as the `dependency` itself?

### Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?

- react: ^16.8.6,
- react-dom: ^16.8.6,
- react-scripts: 2.1.8
- eslint-plugin-react-hooks: ^1.6.0

**Comment by universse** [comment]
Based on your example, guess you can do something like this with useMemo
```
const childKeys = useMemo(
  () => React.Children.map(children, child => child.key),
  [children]
)
```
So childKeys change only when children change. And you can useEffect as auto-fixed by eslint
```
useEffect(() => {
    setHeights(heights => calculateHeights(childKeys, refs, heights));
  }, [childKeys]);
```

**Comment by lukaskl** [comment]
I love simple solutions!
@universse thank you! It seems that this solves the issue! 😄

**Comment by Haroenv** [comment]
What if you don't need the hashed version, but the real version in the effect? I just chose to disable the rule for now, but I'm not sure if it's the best

**Comment by Bastian** [comment]
> From your example, the issue is that childKeys is recomputed every time the component is re-rendered with React.Children.map. To prevent this, you can make use of useMemo hook.
> 
> ```
> const childKeys = useMemo(
>   () => React.Children.map(children, child => child.key),
>   [children]
> )
> ```
> 
> Now childKeys is recomputed only when children change. And you can useEffect as auto-fixed by eslint.
> 
> ```
> useEffect(() => {
>   setHeights(heights => calculateHeights(childKeys, refs, heights));
> }, [childKeys]);
> ```

This is fine for this single use case, but not a universal solution. The React docs clearly state the following:
```
You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.
```

If you perform actions in your `useEffect(...)` hook that for example execute network requests, you only want to run the hook when the dependencies actually changes—and not if React decides to forget a memorized value. Using `useMemo(...)` weakens the guarantees of `useEffect()` to only run when dependencies really change, which is not acceptable in some szenarios.

As far as I can tell, currently the only solution to this problem is by calculating a value with something like `join(',')` which is currently marked as a warning by eslint. I would suggest to reopen this issue @lukaskl .

**Comment by lukaskl** [comment]
as @Bastian expressed concerns regarding suggested solution, I'm supporting to reopen this issue either to dispel concerns or find a better solution 👍

**Comment by Bastian** [comment]
Bump
