### ISSUE TITLE
autoComplete="off" or "new-password" doesn't work with password field.

### ISSUE THREAD

**Issue by dark-swordsman** [facebook/react#15427]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Chrome is autofilling a password field with the name attribute of "password" when autoComplete="off" or "new-password".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Any instance where an Input has a name of "password" or "pw".

Changing the field name to "_password" works, but is not ideal.

**What is the expected behavior?**

That it doesn't autocomplete the password field.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 15.3.2
Chrome: 73.0.3683.86
Linux: 18.04.1

**Comment by batbyR** [comment]
May I take this bug for PR?

**Comment by threepointone** [comment]
@dark-swordsman could you share a codesandbox repro of this please?

@batbyR happy for you to have a crack at it, but can I ask what you think the bug/fix is? thanks!

**Comment by batbyR** [comment]
@threepointone 

Sorry, the correct question is *May I investigate on this bug?* 😂

You have seen through me. I have not found a fix yet.

**Comment by necolas** [comment]
I don't think this is an issue with React DOM. Most browsers ignore `autocomplete=off` so you need to use a value that isn't standard (like `ignore` or whatever) to actually turn autocomplete off. Here's the related Chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164

**Comment by threepointone** [comment]
thanks! ^ what @necolas said. closing this issue.

**Comment by dark-swordsman** [comment]
Firstly, I added another field to the form since we need them anyways, and the issue went away.

Secondly, it doesn't do what that article that's 3 years old says. Even with "new-password" on the password field and "new-name" on the name field, it still autocompletes.

I won't discuss it further here since it's not your problem and is likely a bug with Chrome itself, but if I find anything relevant to a solution or bugfix on Chrome's part, I'll link it here if anyone else encounters this issue.
