### ISSUE TITLE
act() should warn in testing frameworks besides jest 

### ISSUE THREAD

**Issue by threepointone** [facebook/react#15439]
**Do you want to request a *feature* or report a *bug*?**

feature request

**What is the current behavior?**

The warnings for missing act() warnings around updates only happen in jest. 

**What is the expected behavior?**

We should support other test runners/frameworks as well (like jasmine, karma, etc)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.0+

**Comment by eps1lon** [comment]
Considering https://github.com/reactwg/react-18/discussions/102 landed in React 18 it seems like we can close this.

In React 18 any `act` usage will will warn if `global.IS_REACT_ACT_ENVIRONMENT` is not set (no reliance on Jest) and no updates outside of `act` and `global.IS_REACT_ACT_ENVIRONMENT` will be considered updates in an e2e test environment i.e. no missing act warning
