### ISSUE TITLE
React should support nbsp;

### ISSUE THREAD

**Issue by Tectract** [facebook/react#15432]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`&nbsp;` is removed and "handled" by react. Stop that.

**What is the expected behavior?**

`&nbsp;` should be passed through to the front-end, unmolested.

I want to use nbsp;, not a work-around. React is getting in the way. Why is this basic charchode broken in react? Give us nbsp back!

**Comment by threepointone** [comment]
you can insert explicit whitespace in jsx with {' '}. If you're inserting html from another source, you can use `dangerouslySetInnerHTML`. Does that answer your question?

**Comment by TrySound** [comment]
Actually it's supported. Just not in JS strings.
https://codesandbox.io/s/2ozywv8knj

**Comment by Tectract** [comment]
> I want to use nbsp;, not a work-around.

I don't want to have to find every place in my code where a newline was converted to a space in a normal html page, and convert it by hand. I don't want to mess with trying to figure out creative ways to fix html that has been styled with nbsp when I convert it to react.

I understand that you can use {' '}. I don't want that. I want nbsp.

**Comment by Tectract** [comment]
@trysound your example is pretty interesting, multiple nbsp actually work in this test, but not very well, and get converted to newlines seemingly randomly... Is it really that hard to just make a flag to disable whatever fancy parsing of nbsp that react does, so we can have it back again?

**Comment by threepointone** [comment]
You could possibly write a custom babel plugin or similar that converts `nbsp;` characters into whitespace. The workaround above also are available as options. You could also just search and replace for the string in your codebase. But I don't think we're going to make such a core change to jsx any time soon. jsx isn't meant to be completely backwards compatible with html; for example, it doesn't support unquoted attributes either. 

Closing this issue since there isn't anything actionable here. Consider using the community resources for further help and to see how others are handling this. https://reactjs.org/community/support.html

**Comment by Tectract** [comment]
> sx isn't meant to be completely backwards compatible with html

I don't think this ticket should be closed, I think it should be considered an open bug / feature request. I think you SHOULD set the goal of making jsx compatible with HTML, because right now it's a PITA to convert large amounts of html to JSX. 

Developers shouldn't have to waste their time dealing with whitespace formatting. Say I want to convert 10,000 lines of html to jsx and it has 15,000 occurences of style, class, and 20,000 occurences of whitespace newlines or nbsp. I shouldn't have to make 35,000 manual edits to convert that code.

**Comment by Tectract** [comment]
> make a flag to disable whatever fancy parsing of nbsp that react does, so we can have it back again

Let me restate my request...

Where does React do it's fancy formatting of nbsp objects? How can I disable or override that?

**Comment by olignyf** [comment]
React should make an exception for &nbsp; 
&nbsp; is very useful and not the same as space ' '
