### ISSUE TITLE
[react-hooks/exhaustive-deps] exhaustive-deps does not play well with object returning hooks

### ISSUE THREAD

**Issue by dantman** [facebook/react#15448]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

exhaustive-deps does not play well with 3rd party hooks like useBoolean that return objects instead of arrays because they work better when not destructured.

For example in the following:
```js
import { useCallback } from 'react';
import { useBoolean, useInput } from 'react-hanger';
// ...
  const pending = useBoolean(false);
  const email = useInput();
  const submit = useCallback(() => {
    pending.setTrue();
    Promise.resolve()
      .then(() => console.log(email.value))
      .then(pending.setFalse);
  }, [email.value, pending.setTrue, pending.setFalse]);
```

exhaustive-deps complains with `React Hook useCallback has a missing dependency: 'pending'. Either include it or remove the dependency array`.

However this is a bad idea, since `pending` will change every time that `pending.value` changes resulting in the `submit` event handler changing each time. Despite the fact that it only uses `pending.setFalse` and `pending.setTrue` which are static and already included in the deps array. Destructuring `pending` would also 

**What is the expected behavior?**

exhaustive-deps should not complain because the exact deps are already present in the deps array.

**Comment by universse** [comment]
Have you tried destructuring pending?
```
const { setTrue, setFalse } = useBoolean(false)

const submit = useCallback(() => {
    setTrue();
    Promise.resolve()
      .then(() => console.log(email.value))
      .then(setFalse);
  }, [email.value, setTrue, setFalse]);
```
From my experience it should work

**Comment by dantman** [comment]
Oh, I forgot to finish my sentence.

Destructuring would defeat the simplicity of the hook. I have trimmed down the example, the real world usage this is from is a big-ish component. So you most definitely would not be using the `setTrue`/`setFalse` without any context of what they are actually for. The real destructuring would look more like.

```js
import { useCallback } from 'react';
import { useBoolean, useInput } from 'react-hanger';
// ...
  const {value: pending, setTrue: setPendingTrue, setFalse: setPendingFalse} = useBoolean(false);
  const email = useInput();
  const submit = useCallback(() => {
    setPendingTrue();
    Promise.resolve()
      .then(() => console.log(email.value))
      .then(setPendingFalse);
  }, [email.value, setPendingTrue, setPendingFalse]);

  // a pile of code
    {pending && <Loading />}
  // more code
```

**Comment by universse** [comment]
Yeah i get it. In that case, would you consider destructuring close to where the methods are used?
```javascript
const pending = useBoolean(false)
// pile of code
const { setTrue, setFalse } = pending
const submit = useCallback(() => {
    setTrue();
    Promise.resolve()
      .then(() => console.log(email.value))
      .then(setFalse);
  }, [email.value, setTrue, setFalse]);
// other code
...
```

**Comment by dantman** [comment]
@universse Even if it's local you're still sacrificing code understandability. What is setTrue / setFalse supposed to mean inside the callback? What is being set true/false?

Also what if you use useBoolean twice for two different boolean states? setTrue/setFalse would overlap.

**Comment by leeseean** [comment]
`const [setTrue, setFalse] = useBoolean(false)`

**Comment by dantman** [comment]
@leeseean That's not the API. [useBoolean](https://github.com/kitze/react-hanger#useboolean) is part of a library. That example also misses the value and the `toggle` handler.

**Comment by leeseean** [comment]
> @leeseean That's not the API. [useBoolean](https://github.com/kitze/react-hanger#useboolean) is part of a library. That example also misses the value and the `toggle` handler.

you`d better raise a issue in the liabrary repo,it`s the bug from library

**Comment by dantman** [comment]
Intentional good api design is not a bug. The bug is exhaustive-deps warning about good code.

**Comment by olee** [comment]
It would be nice to have an option (for example by adding a special comment) to mark some dependencies as static manually.
I have the same issue when I wrote this small utility hook using `useRef` which is then not detected as static any more:
```typescript
function useUpdatingRef<T>(value: T) {
    const ref = React.useRef(value);
    ref.current = value;
    return ref;
}
```
Using it's **static** return value in any other hook will trigger the linting rule with a false-positive.

**Comment by gaearon** [comment]
When you're calling `pending.setTrue()`, you are passing `pending` object itself as a `this` value to `setTrue()`. So the rule is correct. If `setTrue()` reads from `this`, it would see a stale value. Therefore, the rule warns you. If you want to solve this, destructure `setTrue()` early.

(As a side note, yes, this can make code relying on Hooks like `useBoolean` annoying. We don't generally recommend using Hooks like this that just hide a data structure. Instead, the recommendation is that you `useReducer` for state calculations, and work with plain objects.)

**Comment by rart** [comment]
@gaearon would you mind commenting on @olee [comment above](https://github.com/facebook/react/issues/15448#issuecomment-489429711)? I have that exact hook he illustrated causing `exhaustive-deps` to trigger.

@olee wondering if you found a way around it?
