### ISSUE TITLE
Escaping curly brackets

### ISSUE THREAD

**Issue by RickWong** [facebook/react#1545]
Thanks for React and JSX!

Would it be possible to escape curly brackets in the future? Like this:

```
<div>In JSX you can use the \{ and \} characters to escape and evaluate inline JavaScript.</div> 
```

**Comment by mysterycommand** [comment]
Maybe you could just use HTML entities? `&#123;` (opening curly brace) and `&#125;` (closing) … doesn't solve the "looks like crap" problem, but might work?

**Comment by RickWong** [comment]
Old topic but I think JS string literals are actually a valid solution to this problem. Also I solved it by putting them all in a "sheet" prop that I use instead of "children". See https://github.com/RickWong/ReactStyle

**Comment by syranide** [comment]
Related facebook/jsx#28

**Comment by darobin** [comment]
FWIW, for anyone stumbling upon this issue while searching for a solution, the simplest (assuming ES6) is probably:

```html
<style>{`
    .spinner ellipse { opacity: 0; }
    /*...*/
`}
</style>
```

**Comment by timurtu** [comment]
In webstorm atleast `{'}'}` gives parsing issues and makes the code reformat incorrectly. My solution to this which I wasn't really happy about was

```
function curlyStart() {
  return '{'
}

function curlyEnd() {
  return '}'
}
```

**Comment by gaearon** [comment]
File an issue with WebStorm, I'm sure they'd be happy to fix. cc @prigara

**Comment by prigara** [comment]
Hi, @timuric! Here's a related issue on our tracker: https://youtrack.jetbrains.com/issue/WEB-21774 Hope we'll get it fixed soon.

**Comment by manoharreddyporeddy** [comment]
In simple:
{ is {'{'} and
} is {'}'}

**Comment by mnpenner** [comment]
If you happen to be generating JSX like me, this seems to work:

```
'{hello}{world}'.replace(/([{}]+)/g,"{'$1'}")
```

**Comment by tobq** [comment]
> ally want a `\` followed by a `{`

\\\{ -> `\{`

**Comment by hacknlove** [comment]
my solution, define the whole string outside

```
const codeExample = '{ _id: { $gt: ObjectId() } }'
```

```
return (
<foo>{codeExample}</foo>
)
```
```
