### ISSUE TITLE
Issue with useEffect cleanup during react-dom re-render and HMR

### ISSUE THREAD

**Issue by swashata** [facebook/react#15461]
**Do you want to request a *feature* or report a *bug*?**

A bug (I suppose).

**What is the current behavior?**

I think, the cleanup of `useEffect` isn't firing at proper time when doing a HMR update like this

```js
import React from 'react';
import ReactDOM from 'react-dom';

import App from './App';

const mountNode = document.querySelector('#root');
ReactDOM.render(<App />, mountNode);

if (module.hot) {
	module.hot.accept('./App.tsx', () => {
		const NewApp = require('./App.js').default;
		ReactDOM.render(<NewApp />, mountNode);
	});
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

To reproduce the issue, please clone this repository https://github.com/swashata/react-issue-hmr-useeffect and run `yarn start`.

First change the counter from the application and the document title will update to something like `(1) React App`.

Then change the `src/Counter.js` file and see that document title being changed to `(0) (1) React App`.

The code with useEffect is like this

```js
  // const [count, setCount] = useState(0);
  const [state, dispatch] = useReducer(counterReducer, { count: 0 });
  const { count } = state;
  // get initial document.title and persist it
  // based on initial title, so we use useRef
  const initialDocTitle = useRef(document.title);

  // change document title if count changes
  useEffect(() => {
    const docTitle = initialDocTitle.current;
    document.title = `(${count}) ${docTitle}`;
    return () => {
      document.title = docTitle;
    };
  }, [count]);
```

Here's a gif demonstrating the issue

![react-issue-gif](https://user-images.githubusercontent.com/1623381/56457197-bc7b0800-6394-11e9-9aa7-6396702bdeda.gif)

(**YouTube [link](https://youtu.be/vjG8o6EmlMU)**)

Strangely enough, it works with codesandbox: https://codesandbox.io/s/q0m6wjklw

**What is the expected behavior?**

I am not sure, but I guess, if ReactDOM renders something on top, the `useEffect` cleanups from the previous render should fire first?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```json
{
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "2.1.8"
  }
}
```

* **Browser**: Chrome Version 73.0.3683.103
* **OS**: macOS 10.14.4

**Comment by kunukn** [comment]
I believe it is because when you use HMR, then it doesn't unmount, which means this doesn't executes ```jsx
```

**Comment by kunukn** [comment]
When you use HMR, then the unmount or "restart" doesn't happen. 

If the current `document.title` is `(9) React App` when your component renders again, then this results in the funky document.title you have, due to these lines

```jsx
const docTitle = initialDocTitle.current; // (9) React App
document.title = `(${count}) ${docTitle}`; // count start from 0
```

And document.title is now `(0) (9) React App`

**Comment by swashata** [comment]
Hello @kunukn,

Thank you for your response and yes I am totally aware of what you are saying. I noticed one thing. If I change the code to

```js
  useEffect(() => {
    // this doesn't work, initialDocTitle gets messed up on re-render
    // const docTitle = initialDocTitle.current;
    // but this works fine, with the proper cleanup
    const docTitle = document.title;
    console.log(`Changing title to \`(${count}) ${docTitle}\` on count ${count}`);
    document.title = `(${count}) ${docTitle}`;
    return () => {
      console.log(`Reseting title to ${docTitle}`);
      document.title = docTitle;
    };
  }, [count]);
```

It works just fine, even with HMR. I have pushed to the same repo. So I think, maybe, when ReactDOM re-renders on the same node, then the cleanup of `useEffect` isn't called until it reaches the same order of calling. Something like this

```
// <App /> has `useRef` call
// <App /> has a cleanup in `useEffect`
> ReactDOM.render(<NewApp />, ...)
// Current title is (1) React App
// <NewApp /> has `useRef` which refers to `document.title`, which is `(1) React App`
// <NewApp /> has `useEffect`, so call cleanup from <App />
// Set title to `React App` from the cleanup
// Call the new `useEffect`, which reads value from the `ref`, which is `(1) React App`
// Set the title to `(0) (1) React App`
// Hold the cleanup from useEffect which would set the title back to `(1) React App`.
```

If I am thinking straight, when we actually call `ReactDOM.render(<NewApp />, node)`, it should've called the cleanup of `useEffect` from previous render first?

I also did some more digging on how ReactDOM handles the re-render. For that I added a button outside react app, which when clicked would render null or the app, depending on the render status.

```js
import React from "react";
import ReactDOM from "react-dom";

import App from "./App";

const mountNode = document.querySelector("#root");
let AppToMount = App;
ReactDOM.render(<AppToMount />, mountNode);

let rendered = true;

if (module.hot) {
  module.hot.accept("./App.js", () => {
    // eslint-disable-next-line global-require
    AppToMount = require("./App.js").default;
    ReactDOM.render(<AppToMount />, mountNode);
    rendered = true;
  });
}


const rerenderButton = document.querySelector('#re-render');

rerenderButton.addEventListener('click', (e) => {
  e.preventDefault();
  if (rendered) {
    ReactDOM.render(null, mountNode);
    rendered = false;
  } else {
    ReactDOM.render(<AppToMount />, mountNode);
    rendered = true;
  }
});
```

Strangely this works fine. 

![react-issue-gif-2](https://user-images.githubusercontent.com/1623381/56465887-b5e8a100-6425-11e9-9a28-ac4bf60bf2dc.gif)

So I wonder what is the difference of the code

```js
rerenderButton.addEventListener('click', (e) => {
  e.preventDefault();
  if (rendered) {
    ReactDOM.render(null, mountNode);
    rendered = false;
  } else {
    ReactDOM.render(<AppToMount />, mountNode);
    rendered = true;
  }
});
```

with

```js
if (module.hot) {
  module.hot.accept("./App.js", () => {
    // eslint-disable-next-line global-require
    AppToMount = require("./App.js").default;
    ReactDOM.render(<AppToMount />, mountNode);
    rendered = true;
  });
}
```

For the first case (manual button), the cleanup is called before mounting the new app, for the second case (HMR), the cleanup is called after mounting the new app, in the same order as hooks.

One thing to note here is, if I don't do `null` render, rather just re-render with
`ReactDOM.render(<AppToMount />, mountNode)`, it works fine too (i.e, the cleanup of `useEffect` is called before mounting the new React Element).

Once again, I have updated the code in the same repository https://github.com/swashata/react-issue-hmr-useeffect

**Comment by kunukn** [comment]
Regarding this code snippet

```jsx
  useEffect(() => {
    // this doesn't work, initialDocTitle gets messed up on re-render
    // const docTitle = initialDocTitle.current;
    // but this works fine, with the proper cleanup
    const docTitle = document.title;
```

This line `const docTitle = document.title;` is captured. On following useEffect calls the docTitle doesn't get "updated".  

Maybe the code should be like this?

```jsx
  useEffect(() => {
    const initialDocTitle = document.title; // captured value, I don't change
    document.title = `(${count}) ${initialDocTitle}`; // apply side effect
    return () => {
      document.title = initialDocTitle; // reset to initial value
    };
  }, [count]);

```

How `useEffect` works is explained in details here. 
https://overreacted.io/a-complete-guide-to-useeffect/

**Comment by swashata** [comment]
Thanks @kunukn, that's exactly what I did in the last commit and it makes the use of `useRef` irrelevant for this use case.

But I would still like to know why the combination of `useRef` and `useEffect` doesn't work in the first example.

Maybe I am not explaining it good enough. I will try to create a video and post here.

**Comment by kunukn** [comment]
I think you are good at explaining. 

The combination of `useRef` and `useEffect` probably didn't work as expected because when using HMR, the app didn't restart. And when it didn't restart then **document.title** was NOT reset.

`document.title` had the value **(9) React App**

The Counter component renders from a UI state where `document.title` is NOT reset.

```jsx
// get initial document.title and persist it
// based on initial title, so we use useRef
 const initialDocTitle = useRef(document.title); // <--- document.title is: (9) React App

// change document title if count changes
  useEffect(() => {
    const docTitle = initialDocTitle.current; // <--- value is: (9) React App
    document.title = `(${count}) ${docTitle}`; // <-- value is: (0) (9) React App
    return () => {
      document.title = docTitle;
    };
  }, [count]);
```

With the updated code where it works.

```jsx
  useEffect(() => {
    const initialDocTitle = document.title; // captured value, I don't change
```

Here `initialDocTitle` is NOT updated on HMR and next useEffect calls because it is a captured value.

**Comment by swashata** [comment]
Thank for the explanation.

<blockquote>The combination of useRef and useEffect probably didn't work as expected because when using HMR, the app didn't restart. And when it didn't restart then document.title was NOT reset.</blockquote>

So when the app didn't restart because of HMR, this actually happened

- `useRef` DID reset, otherwise, it would still hold the value from the last app.
- `useEffect` DID NOT reset, otherwise, it would have called the clear function before, correcting the value of the `ref` on next render.

Don't you think it is inconsistent that one hook `useRef` gets reset, whereas other `useEffect` doesn't.

Now to further approach from a different angle, HMR is really just

```js
if (module.hot) {
  module.hot.accept("./App.js", () => {
    // eslint-disable-next-line global-require
    AppToMount = require("./App.js").default;
    ReactDOM.render(<AppToMount />, mountNode);
    rendered = true;
  });
}
```

Where we `require` the file on an event emitted by webpack and ask `ReactDOM` to render it on top of the existing app.  (For the whole example, I haven't used the react-hot-loader library at all). This, you are saying DOES NOT cause a complete restart of the app, leading to the above mentioned behavior of hooks.

But if I just try to __simulate__ the HMR behavior with something like

```js
rerenderButton.addEventListener('click', (e) => {
  AppToMount = require("./App.js").default;
  ReactDOM.render(<AppToMount />, mountNode);
});
```

Where, we do the same thing, but on an event fired by a button, then for some reason, the app IS restarted causing the cleanup of `useEffect` from previous render being called first, then the usual sequence of hooks from new app are called in proper order.

Don't you think, the behavior is inconsistent and perhaps this is a bug in `react-dom` or `react`?
