### ISSUE TITLE
Why ReactFiberHostConfig.js has no export but methods can be imported?

### ISSUE THREAD

**Issue by yibingxiong** [facebook/react#15468]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Some methods can be imported from ReactFiberHostConfig.js although there is no export. Could you tell me where is the methods defined?

**Comment by sophiebits** [comment]
See this code comment:

https://github.com/facebook/react/blob/587676900f5575868b2e4c2bc67755536e231c4f/packages/react-reconciler/src/ReactFiberHostConfig.js#L12-L14

In React DOM it resolves to ReactDOMHostConfig, for example. You can search for `ReactFiberHostConfig` to find the relevant configs.

**Comment by yibingxiong** [comment]
Thank you very much. I'm sorry to reply to you so late.
