### ISSUE TITLE
lazy suspend ref props not changing

### ISSUE THREAD

**Issue by paulous** [facebook/react#15467]
I am having a problem getting a new height from my outer component when the inner lazy components height changes. I am using getBoundingClientRect() to get height.

Everything works fine when I don't make the component lazy.

I have tryed waiting untill the component is fully loaded before getting the new height, but it still doesn't change the height.

**Comment by eps1lon** [comment]
Please add the code including your lazy component and how you handle the ref to it (especially getBoundingClientRect callsite).

**Comment by paulous** [comment]
Thanks for the reply. as I mentioned when I import the component normaly there is no problem, but when wrapped with <Suspense> the height doesn't change. Not sure if this will be helpful:

The refs component:
```
    const scrollRefs = [
        {name:'ABOUT', ref:useRef()},
        {name:`WHAT'S ON?`, ref:useRef()}
    ]

const Body= lazy(() => import('./BodyThree'))

render(
<>
            <MainBodyref={scrollRefs[0].ref}>
                <Suspense fallback={'loading...'}>
                    <BodyThree setScrollRefresh={setScrollRefresh} />
                </Suspense>
            </MainBody>
            <Navbar scrollRefresh={scrollRefresh} scrollRefs={scrollRefs} />       
</>
)
```
The getBoundingClientRect component Navbar:
```
    useEffect(() => {
        let docTop = document.documentElement.scrollTop
        const refsTop = props.scrollRefs.map(item => ({gbcr:item.ref.current.getBoundingClientRect(), docTop}))
        window.onscroll = onScroll(refsTop)
    },[props.scrollRefresh])
```

**Comment by threepointone** [comment]
Please use codesandbox or a git repo to share a repro.
