### ISSUE TITLE
Feature request: subtree priorities in Concurrent React

### ISSUE THREAD

**Issue by zxti** [facebook/react#15465]
**Do you want to request a *feature* or report a *bug*?**
Feature

In Concurrent React you can set the priority of update operations, like a particular setState call.

However, rather than setting different priorities for different setState calls, I'm interested in setting different priorities for different parts of the component tree.  For instance, for a single setState call, I want to defer rendering a low-priority section of the UI.

**Comment by gaearon** [comment]
We will have a feature like this for parts of UI that are truly hidden.

If you want this for part of UI that's visible, you should can put `useDeferredValue` around its props, and then you'll achieve the same effects.
