### ISSUE TITLE
Is there a plugin，that can support a linter  in standardjs?

### ISSUE THREAD

**Issue by Junting-Liu** [facebook/react#15460]
in my project, i use [standardjs ](https://standardjs.com/)as my linter, but eslint。i add  eslint-plugin-react-hooks  in my standard's config, but it doesn't work.

` "standard": {
    "parser": "babel-eslint",
    "plugins": [
      "react-hooks"
    ]
  },
`

can i use  eslint-plugin-react-hooks  in standard.js?  is there a plugin can work in standard.js?
thanks~

**Comment by swashata** [comment]
I think you also need the rules? Like

```js
module.exports = {
  // ...
  plugins: [
    'react-hooks',
  ],
  rules: {
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
  },
};
```

**Comment by Junting-Liu** [comment]
@swashata    Thank you for your reply. I do as your solution, but it also can't work。And, i find this [question](https://github.com/standard/standard#i-disagree-with-rule-x-can-you-change-it). So, i change standard to standardx:
`  "standardx": {
    "parser": "babel-eslint",
    "plugins": [
      "react-hooks"
    ]
  },
  "eslintConfig": {
    "rules": {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn"
    }
  },
`
It can work when commit, but vscode-standardjs  can't give suggestion when i'm coding。
So, I need some better solution 🤣........   Maybe ,I should  ask this question in [ standardjs](https://github.com/standard/standard)

**Comment by swashata** [comment]
I haven't used standardjs, but if really using the react eslint plugin for hooks is your aim, then you can just use eslint with `eslint-config-standardjs` (do double check the name) along with the plugin.

**Comment by threepointone** [comment]
This feels like a question for the standardjs repo, not this one. Best of luck!

**Comment by linzpeng** [comment]
are you find solution ?...

**Comment by Junting-Liu** [comment]
> are you find solution ?...

There is my final config, this solution need use both of standardjs and eslint plugin in vscode. I don't think it's a good solution, maybe you can try [ eslint-config-standard](https://github.com/standard/standard#i-disagree-with-rule-x-can-you-change-it).
```
 "standardx": {
    "parser": "babel-eslint",
    "plugins": [
      "react-hooks"
    ]
  },
  "eslintConfig": {
    "parser": "babel-eslint",   // for eslint plugin in vscode
    "plugins": [  
      "react-hooks"
    ],
    "rules": {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn"
    }
  },
  "standard": {   //  for standardjs plugin in vscode
    "parser": "babel-eslint"
  },
```
