### ISSUE TITLE
BUG: [npm:create-react-class] context not working

### ISSUE THREAD

**Issue by pjebs** [facebook/react#15476]
```
class MyClass extends React.Component {
  static contextType = MyContext;  // <---------------doesn't work
  render() {
    let value = this.context;
  }
}
```

For es5 support, create-react-class was created. It supports class methods by

```
var Button = createReactClass({
  statics: {
    getDerivedStateFromProps() {
      // ...
  },
  render() {
    // ...
  }
});
```

This approach doesn't work for contextType.

**Comment by threepointone** [comment]
Could you use codesandbox to make a repro please?

**Comment by pjebs** [comment]
I won't have the time but the latest version for `create-react-class` is 15.6.3 which is more than 1 year old according to npm. This was before context in its current form was released. Perhaps that has something to do with it.

**Comment by pjebs** [comment]
Here is the reason. It just needs to be documented because it is currently "secret":

https://github.com/facebook/react/blob/15-stable/addons/create-react-class/factory.js#L294


Close the issue if required.

**Comment by kunukn** [comment]
I have this working example. 

https://codesandbox.io/s/p5x07kvzwj

**Comment by sarmd23** [comment]
hello
