### ISSUE TITLE
[Warning] Security vulnerability in 'tar' package, with the latest version

### ISSUE THREAD

**Issue by benlizar** [facebook/react#15470]
**React version**: 16.8.6
A security Vulnerability is shown when is compiling.

**Steps to reproduce it:**
- Update the project to the latest version 16.8.6
- run the `npm start`
- Run `npm audit` and verify that the project is throwing a security issue inside
![image](https://user-images.githubusercontent.com/36707032/56483346-6773ea80-6497-11e9-8f53-4532dfd56a76.png)

**Package file**
![image](https://user-images.githubusercontent.com/36707032/56483363-8ffbe480-6497-11e9-9a53-ede160a6c29a.png)

**Comment by threepointone** [comment]
Please file this issue at https://github.com/facebook/create-react-app/issues
