### ISSUE TITLE
Invariant Violation Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by dwivedithedev** [facebook/react#15489]
React beginner here. I am building this Project and everything was going fine until this. I did lot of googling for this error and I know, a lot of issues are opened here regarding the same error but i have tried EVERY one of the solutions like changing import/export default etc. (invested 2 days) and none of it fixed it for me. I recreated the error from my app into a codesandbox. I have no idea about context API but i think it might be involved in this. I also believe this could be a silly error I am missing out on.

**What is the current behavior?**
Here is a codesandbox:- https://codesandbox.io/s/mq9pw38kqx
```
Invariant Violation
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Navigate`.
```

**What is the expected behavior?**
It loads the App.js component with Navigation menu also appearing.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React - 16.8.6
Chrome/Mozilla

**Comment by nattthebear** [comment]
```
import Route from "react-router-dom";
import Link from "react-router-dom";
```
to
```
import { Route } from "react-router-dom";
import { Link } from "react-router-dom";
```

**Comment by limal** [comment]
I've got the same error message and all it took to fix it was upgrading `react` and `react-dom` from `16.0.0` to `16.3.3` and then running the `npm run-script build` again.
