### ISSUE TITLE
withRef has been removed error. I don't use withRef anywhere in my code. 

### ISSUE THREAD

**Issue by ThinkSalat** [facebook/react#15491]
Literally nothing had changed in my code. React dev server crashed and upon restart it began crashing with `withRef is removed. To access the wrapped instance, use a ref on the connected component`

Now I can't get it to stop. 

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Immediate crash with error: `withRef is removed. To access the wrapped instance, use a ref on the connected component`

couldn't reproduce w codesanbox (https://codesandbox.io/s/new)

**What is the expected behavior?**
No crash
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Using 16.8.6, recently upgraded from 16.8.1

**Comment by eps1lon** [comment]
Are you using react-redux? Sounds like a warning introduced in [react-redux@6.0.0](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0).

**Comment by threepointone** [comment]
Yeah this looks like an issue with react-redux, you should reach out to them. But it does look like you upgraded and need to migrate. Closing this issue.
