### ISSUE TITLE
[eslint-plugin-react-hooks]: bug React Hook "XXX" is called in function "children"

### ISSUE THREAD

**Issue by marcelmokos** [facebook/react#15497]
**bug**

**What is the current behavior?**

The hooks created in children function provided in defaultProps populates error `react-hooks/rules-of-hooks`.

```js
const App = props => props.children(props);

App.defaultProps = {
  children: props => {
    const [count, setCount] = useState(0);

    return (
      <>
        count: {count}
        <button onClick={() => setCount(count + 1)}>Increment</button>
      </>
    );
  },
};
```

`React Hook "useState" is called in function "children" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks
`

https://codesandbox.io/s/v60mm6yvx0

**What is the expected behavior?**

Hooks inside children function in defaultProps should not create an error when hook is used. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Same as in the codesandbox.
```
"dependencies": {
  "react": "16.8.6",
  "react-dom": "16.8.6",
  "react-scripts": "3.0.0"
},
```

**Comment by gaearon** [comment]
What is the purpose of this pattern? It's easy to mess it up by rendering children conditionally so the warning makes sense to me.

**Comment by marcelmokos** [comment]
It is a prefered pattern `Components in defaultProps` I am advocating in teams I am working with.
 

https://medium.com/ableneo/improve-how-you-style-react-apps-use-components-in-defaultprops-a8fd59e875d7

It allows us to create highly reusable presentational components and then use styled components with real application data.

**Comment by otakustay** [comment]
In that article, `children` is considered a render prop instead of a component:

```jsx
const Discussion = ({children, ...props}) => children(props);
```

Notice that `children` is invoked like a function rather than via `React.createElement`, this means the return value of `children` doesn't have a fiber node, in this cases hooks are broken.

**Comment by marcelmokos** [comment]
@otakustay can you outline more information about React Behaviour in this case. My thoughts were children is defined on a static defaultProps and should not differ with component created without render prop. How do you solve this issue for Context.Consumer or other render props API's? 

```js
const Discussion = ({children, ...props}) => children(props);

Discusion.defaultProps = {
  children: (props) => {...},
}; 
```

An example where I am trying to log render count and state. It seems to function properly. State and createLog function output correct values if they are created in defaultProps as a prop in jsx. https://codesandbox.io/s/o4lroz2qz


I am trying to study more about fiber nodes in this article but I do not see traces of claim you had.
https://medium.com/react-in-depth/inside-fiber-in-depth-overview-of-the-new-reconciliation-algorithm-in-react-e1c04700ef6e

**Comment by otakustay** [comment]
@marcelmokos Since `children` is only a render prop, hooks inside it belongs to `Discussion` component, so in edge cases where `children` is provided conditionally, it can result in "hooks order changed" issue, this is a very simple example: https://codesandbox.io/s/wqlojx66yw

Also this can happen when `Discussion` uses `children` conditionally: https://codesandbox.io/s/5wjvn6767p

Click the button and checks error in console

**Comment by marcelmokos** [comment]
@otakustay I understood this limitation that children should be provided conditionally from the hooks documentation. 

The intention of this pattern is to use static declarations of children and components in default props. This allows us to exchange components or children function for customizations.

**Comment by otakustay** [comment]
@marcelmokos Use hook in any function can be dangerous because functions can be called conditionally, this is why eslint rule warns about hooks in function, `children` is simple a function.

My best suggest is to avoid using hook in any function, including `children`, simply use hooks in function component's body and pass it to children:

```jsx
const Discussion = ({children, ...props}) => {
  const [foo, setFoo] = useState(null);
  return children({...props, foo, setFoo});
};
```

`foo` and `setFoo` is a **contract** between `Discussion` and its children, children do not have it's own states.

Another trick is since your `children` matches exactly to a component's signature, this can be solved by `createElement` it:

```jsx
const Discussion = ({children, ...props}) => React.createElement(children, props);
```

But still, eslint will warn about it because it's not able to determine how `children` is used.

**Comment by marcelmokos** [comment]
@otakustay I am thankful for your comment and help. The solution with adding the hook into render prop initialization seem like the solution I was looking for the mentioned pattern.

```js
const Component = ({children, ...props}) => {
  const [foo, setFoo] = useState(null);
  return children({...props, foo, setFoo});
};

Component.defaultProps = {
  children: (props) => {...},
}; 
```

Again thanks and the issue can be closed. When I come back from holiday I will have a look if there is a way to document this in the project.

**Comment by tareefdev** [comment]
I'm not sure 100% if this the same.
Using `setState` in a child component to store and alter some local data gives this error:

`Warning: React has detected a change in the order of Hooks called by XXX`

While using normal JavaScript variables and reassign new values to them doesn't produce any error messages in the console. I'm confusing what is the best practice here.

**Comment by jtrainaldi** [comment]
@tareefdev any luck with your error?

**Comment by tareefdev** [comment]
@jtrainaldi yep I fixed it. It was my fault. see [here](https://github.com/tareefdev/beta/commit/a3c79069df060245c4b22fd96cae807c970889c9).
Basically, I had a hook in a nested function (using `locale` inside `tr`), I created another function called `useTranslations` which defines `locale` and returns `tr` without it. Hope that could help you.
