### ISSUE TITLE
eslint-plugin-react-hooks requires static functions in the dependency array

### ISSUE THREAD

**Issue by micha149** [facebook/react#15495]
**Do you want to request a *feature* or report a *bug*?**
I think its a bug or an unnecessary warning…

**What is the current behavior?**
The eslint rule warns against functions used in `useCallback`, although the can not change from render to render.

```javascript
import { calculateSomethingExpensive } from './somewhere';

const MyComponent = ({ a, b }) => {
    const onClick = useCallback(() => {
        // ...
        const foo = calculateSomethingExpensive(a, b);
        // ...
    }, [a, b]);

    return (
        <button onClick={onClick}>Calculate!</button>
    );
}
```

In the code above, the eslint rule `react-hooks/exhaustive-deps` reports `calculateSomethingExpensive` to be included in the dependency array.

**What is the expected behavior?**

Static functions can be used without warnings

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`eslint-plugin-react-hooks@1.6.0 `

**Comment by micha149** [comment]
My fault… the uses functions where not static. They are created using factories and `useMemo`… So the warning was correct and very helpful…

**Comment by eps1lon** [comment]
I don't think the rule actually checks what is imported. Just that it is imported.  Since imports can be mutated in the original module e.g. `export let foo = 1;` the rule automatically assumes that the value might change over time. I'd say just pass it in the dependencies and you're on the save side.
