### ISSUE TITLE
Losing control of <input type='number' /> 

### ISSUE THREAD

**Issue by Enome** [facebook/react#1549]
http://jsfiddle.net/kb3gN/2498/

In the example above when you start typing numbers and then a non-number character it wont update the input field which is expected. If you start typing a non-number character first though it seems that the input field becomes uncontrolled and starts excepting anything you type and onChange isn't fired anymore.

**Comment by markusk88** [comment]
A little late to the discussion, but I found an easy solution with some jquery magic. 
If we modify the onChange to monitor for empty strings when the validity is false, we can manually set the input to value to ''

http://jsfiddle.net/h6m3muhv/4/

**Comment by blainekasten** [comment]
Additionally, if you guys WANT the native numeric keyboard on mobile, you could wrap input in something like so:

    class Input extends React.Component {
      render() {
        var type = navigator.userAgent.match(/Mobi/) && this.props.type === 'number' ? 'number' : 'text';

        return <input {...this.props} type={type} />
      }
    }

or, react could do this if they dig the patch/hack.

**Comment by JeffOwOSun** [comment]
Here's my solution.
```JSX
handleUpdate(e) {
  if (e.target.validity.valid) {
    //input is numeric
    this.setState({inputValue: e.target.value});
  } else if (e.target.value == '') {
    //input is not numeric
    if (!this.state.inputValue) {
      //case 1: the state is empty, which means the user is typing non-numeric values 
      //from the beginning
      this.numberInput.value = ''; //suppress UI change
      this.setState({inputValue: ''});
    }
    //case 2: the state is not empty, which means the user is typing a non-numeric value 
    //following a numeric input
    //Simply suppress the event so that neither the UI nor the state is altered
  }
}

render() {
  return (
    ...
    <input type="number" value={this.state.inputValue} onChange={handleUpdate} 
      ref={elm=>{this.numberInput=elm}}/>{/*use ref to expose underlying dom node*/}
    ...
  )
}
```

**Comment by donavon** [comment]
How about this ([see pen](https://codepen.io/donavon/pen/pbBOZo)). The key here is setting `step` to `any` to allow decimal numbers (if that's your intention) and reseting the target value to the last know valid value.

```js
_handleUpdate(e) {
  if (!e.target.validity.valid) {
    e.target.value = this.state.inputValue; // Set to last known valid value.
  }
  this.setState({ inputValue: e.target.value }); 
}
```
```html
<input type="number" value={this.state.inputValue} onChange={this._handleUpdate} step="any" />
```

**Comment by sohibul** [comment]
I have similar issue with this.

I can type `...1...111` in `<input type="number" />`

But if I has defaultValue `<input type="number" defaultValue={10} />`, i cannot type `.` (dot) first time. I tried type `1` then `.`, it failed then cursor go to the front (before `1`). Then I can type `.`, so I have `.1`. But still I cannot type multiple `.` (dot), the field will be empty.

**Comment by ThomsCass** [comment]
+1

**Comment by hugofelp** [comment]
+1

**Comment by klk1010** [comment]
+1

**Comment by msal98** [comment]
+1

**Comment by brandensilva** [comment]
+1

**Comment by agraver** [comment]
+1

**Comment by aweary** [comment]
Please stop adding "+1" comments. If you want to support an issue, add a 👍 reaction to the original post.

**Comment by nhunzaker** [comment]
@aweary I think I got this with:
https://github.com/facebook/react/pull/7359

**Comment by nhunzaker** [comment]
I believe that #7359 resolved this. If not, it definitely covers all of the cases I could find. We should move forward with new issues for particular edge cases if they are discovered.

**Comment by CluEleSsUK** [comment]
I still have this problem; text typed in appears in the input, but the onChange listener is skipped and the controlled value does not change.

**Comment by nhunzaker** [comment]
@CluEleSsUK would it be possible to file a new issue with a reproducing example?

**Comment by CluEleSsUK** [comment]
Sure, will do!

**Comment by nikolaas** [comment]
I have similar issue with this.

A controlled React input with type "number" clears its value when I add a dot to the end of the value.
Steps to reproduce:
1. Click to an input
2. Type "10"
3. Click to another input
4. Click to the first input
5. Add "." to the end
6. Click to another input

![react-bug](https://user-images.githubusercontent.com/6443153/73935263-30b97480-48f1-11ea-845d-b79c72517b76.gif)

See live demo here:
```
git clone https://github.com/nikolaas/controlled-react-number-input-bug.git
cd controlled-react-number-input-bug
npm install
npm start
open http://localhost:3000
```

The bug is reproduced in Google Chrome (80.0.3987.87, 64-bit).
In the same case, Safari (13.0.5) replaces the last dot with a comma, Firefox (62.0, 64-бит) allows adding a dot to the end of the value.

P.S. An uncontrolled React input with type "number" allows adding a dot to the end of the value in all browsers mentioned above. An input with type "number" in pure HTML (without React) has the same behavior.

**Comment by dcods22** [comment]
HI,

Im having a similar issue where the onChange is not called in FireFox when the number input is not valid but the input maintains the value of the input and I cant get the change event to set the ref.current.value = '';

`
import React from "react";
import PropTypes from "prop-types";
import styled from "styled-components";
import Input from "./Input";

const NumInput = styled(Input)`
  -moz-appearance: textfield;
  ::-webkit-inner-spin-button,
  ::-webkit-outer-spin-button {
    -webkit-appearance: none;  
    appearance: none;
  }
`;

const NumberInput = ({ name, value, onChange, disabled, innerRef, pattern, step, ...rest }) => {

  const validateChange = event => {
    if (event.target.value.length === 0 || event.target.validity.valid) {
      onChange(event.target.value);
    }
  };

  const validateOnBlur = event => {
    let val = event.target.value;
    if (val == null || val.trim() === "" || !event.target.validity.valid) {
      onChange(val);
    }
  };

  return (
    <NumInput
      id={name}
      type="number"
      pattern={pattern}
      onChange={validateChange}
      onBlur={validateOnBlur}
      value={value}
      disabled={disabled}
      ref={innerRef}
      step={step}
      {...rest}
    />
  );
};

NumberInput.propTypes = {
  /** id property of the input field */
  name: PropTypes.string,
  /** pattern of the input field to follow */
  pattern: PropTypes.string,
  /** step of the input field to follow */
  step: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  /** property where the value of the input field will be stored */
  value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  /** function to be called when the input value is changed */
  onChange: PropTypes.func.isRequired,
  /** flag to disable/enable the input field */
  disabled: PropTypes.bool,
  /**  reference to the number input */
  innerRef: PropTypes.any
};

NumberInput.defaultProps = {
  name: "best-number-input",
  pattern: "[-+]?[0-9]*[.,]?[0-9]+",
  step: "",
  disabled: false,
  innerRef: null,
  value: null
};

export default NumberInput;

`
