### ISSUE TITLE
Suspense commits pending trees in Concurrent Mode under heavy load

### ISSUE THREAD

**Issue by gaearon** [facebook/react#15512]
Seems similar to https://github.com/facebook/react/pull/15424.
Minimal repro case: https://codesandbox.io/s/jzq8roj51y.

To reproduce, open in new tab (https://jzq8roj51y.codesandbox.io/), let first item's details to load, and then hold-press "down". You'll likely (not always) see Details tab flicker and later crash/warn in console.

![Screen Recording 2019-04-26 at 04 29 PM](https://user-images.githubusercontent.com/810438/56821850-5a644c00-6847-11e9-9fb9-061677cdf864.gif)

**Comment by MarioCadenas** [comment]
I've been trying to reproduce this, and the only way i can reproduce it, is by connecting to React devtools, but I can't still get the console error.

![demo](https://im.ezgif.com/tmp/ezgif-1-c674fd786edf.gif)

**Comment by submetu** [comment]
I too had to connect to the React Dev Tools in order to produce this bug

**Comment by gaearon** [comment]
I can't repro this anymore with either version.
