### ISSUE TITLE
[ESLint] Assignment like foo.bar.baz = X should warn about foo.bar instead

### ISSUE THREAD

**Issue by gaearon** [facebook/react#15510]
```js
  let foo = {}
  useEffect(() => {
    foo.bar.baz = 43;
  }, []);
```

This asks you to include `foo.bar.baz` into deps. But this doesn't make sense, as you write to it. Instead it should ask to include `foo.bar` into array.

If `foo` is a newly created object in render scope then we might additionally nudge you to `useRef` for it instead. Because otherwise it won't be shared between renders.

**Comment by eragon512** [comment]
hey, I'd like to take up this issue, however, I am not very familiar with the project setup, is that ok?

**Comment by eragon512** [comment]
hey @gaearon is this issue still available? how should I start work on this?
