### ISSUE TITLE
Apparent memory leak using hooks

### ISSUE THREAD

**Issue by rally25rs** [facebook/react#15527]
**Do you want to request a *feature* or report a *bug*?**

Maybe a bug. Maybe I'm just running into a weird edge case.

**What is the current behavior?**

I have a situation where using a combination of `useEffect`, `useCallback`, and having a function in the actual component render is causing a sort of memory leak.
The current render of the component seems to hang on to references of past renders of the component. (more details in the reproduction sample repo)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I think I have this minimized about as much as I can:
https://github.com/rally25rs/react-mem

It's a basic `create-react-app` project, so you can just `yarn install && yarn start` it. There is some explanation/instructions in the web page that it renders.

The `src/VirtualizedTable.js` file is the key file to look at.

**What is the expected behavior?**

As best as my brain can comprehend, memoized references should be getting cleared as the component props change and data should be garbage collected (but it isn't).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

* Chrome
* react@16.8.6

**Comment by danieltott** [comment]
I was able to refactor this to get only two instances of `Tracking` hanging around in the Heap snapshot:

https://github.com/rally25rs/react-mem/pull/1

I'd be interested to know why there are two there. My best guess is there is a copy inside the `useEffect` closure, and a copy inside state in `displayData` - but I'm not entirely sure.

**Comment by rally25rs** [comment]
Since this hasn't really seen any action in a while, here is an even more simplified version:

https://codesandbox.io/s/nv6lvl784

It turns out to not have anything to do with hooks or memoization at all.
The important code is:
```
function Result(props) {
  return <span />;
}

function App() {
  const [val, setVal] = React.useState("a");
  const data = new BigData();

  return (
    <div>
      <input
        type="text"
        name="val"
        value={val}
        onChange={evt => setVal(evt.target.value)}
      />
      <Result val={val} data={data} />
    </div>
  );
}
```

The `BigData` class instance is never used to memoize anything, actually it's passed as a prop but never used at all.

If you edit the text input in the example a few times, then take a heap snapshot and search for `BigData` you will find 3 instances in memory; instance number 1, and whatever the most recent 2 are.

There should only be 1 of this object instance in memory, not 3. Why are 2 additional ones being retained?

**Comment by Jokcy** [comment]
Em...... it maybe just work as expected. In this case there will also be 3 instance no matter how much change you made.

First one is `__reactEventHandlers` saved on `div`. The `__reactEventHandlers` will update when div props updated or add some event listener on div. In this case props of div never change so it save `__reactEventHandlers` at the first render and never update. And what in `__reactEventHandlers` contains `children` which is ReactElement with props. You can confirm this by find one of BigData instance always stay 1 not matter how much change you made.

The last two is because the **double buffer** in Fiber design. Fiber has an `alternate` which is the older version of this node.

**Comment by jomliu** [comment]
I had the same problem

**Comment by acfasj** [comment]
> In my original issue (the linked github repo) it seems to retain _all_ copies of past prop data, not just 3. These might be separate issues 🤷‍♂

@Jokcy how to explain the original issue?

**Comment by Jokcy** [comment]
> > In my original issue (the linked github repo) it seems to retain _all_ copies of past prop data, not just 3. These might be separate issues 🤷‍♂
> 
> @Jokcy how to explain the original issue?

Sorry too long for this issue, I can hardly remember the detail.
