### ISSUE TITLE
[eslint-plugin-react-hooks] camelCased function names throws linting error

### ISSUE THREAD

**Issue by jarleriksen** [facebook/react#15530]
I get this linting error in all my components that use hooks and are camelCased:
**React Hook "useState" is called in function "eventForm" which is neither a React function component or a custom React Hook function**

I managed to solve this by renaming the component to be PascalCased. But as I have quite a lot of components that are camelCased I was wondering if there's a way to prevent this behaviour or is it on purpose?

// Throws error
```js
const eventForm = (props) => {
   const [count, setCount] = useState(0);
}
```
// Ok
```js
const EventForm = (props) => {
   const [count, setCount] = useState(0);
}
```

If this is the desired behaviour I guess I'll just have to refactor my components. :D

Thanks!

**Comment by gaearon** [comment]
The convention for React components is to use pascal case. This isn’t just related to Hooks. For example JSX `<EventForm>` would work but `<eventForm>` would try to create a DOM element with this name (which doesn’t exist). So you’d probably want to follow this convention anyway.
