### ISSUE TITLE
Feedback on useEffect depndencies change error

### ISSUE THREAD

**Issue by togakangaroo** [facebook/react#15548]
Some feedback on `useEffect`

**What is the current behavior?**

I am using `useEffect` to load details on a set of users that are kept in props.

I want to minimize loading and there are situations where the array of users (and the actual user objects) are recreated but really they refer to the same identities.

So I do

```
const userIds = users.map(u => id)
useEffect(() => {
  if(!userIds.length)
    return
  ...load more stuff by querying endpoints about these ids and set state..
}, userIds)
```

aand I run into a warning

> The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant

which to me is...kinda the point, is it not? I understand if we don't want to do a deep comparison in the dependencies, but if the dependencies themselves change...well that seems straightforward, run the effect. 

I know that I can do `[userIds.join(' '])` in this case, but that seems like just extra work for no reason and really anti-intuitive. And ends up doing the same exact thing but with extra steps! 

To be clear, what I'm proposing is removing [this whole block here](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberHooks.js#L308) and replacing it with

```
if (nextDeps.length !== prevDeps.length)
  return false
```

As far as I can tell, this warning serves no real purpose and makes the use case outlined above awkward to deal with

**Comment by universse** [comment]
Hm, what about
```javascript
useEffect(
  // ....
, [ userIds.length ])
```

**Comment by togakangaroo** [comment]
@universse that would trigger if the ids change length only? So if I add a thing and remove a thing, it will not fetch details.

But really, its not like I can't figure out a way to hack around it - I have one above, its that I don't understand why this limitation would be there in the first place, from looking at the code, absolutely nothing seems to depend on it, if you replaced it with what I propose above it would just work.

**Comment by revskill10** [comment]
Why not just passing `non zero-length userIds` as params to `useEffect` instead ?

**Comment by universse** [comment]
> ```
> if (nextDeps.length !== prevDeps.length)
>   return false
> ```
Huh then what was this for?

**Comment by universse** [comment]
oops i overly focused on this
```
if (nextDeps.length !== prevDeps.length)
  return false
```

**Comment by togakangaroo** [comment]
Yup - if you look at the code, it would seem that you can replace

```
    if (nextDeps.length !== prevDeps.length) {
      warning(
        false,
        'The final argument passed to %s changed size between renders. The ' +
          'order and size of this array must remain constant.\n\n' +
          'Previous: %s\n' +
          'Incoming: %s',
        currentHookNameInDev,
        `[${prevDeps.join(', ')}]`,
        `[${nextDeps.join(', ')}]`,
      );
    }
```

with 

```
if (nextDeps.length !== prevDeps.length)
  return false
```

and then my use case would be supported *and* there would be no other negative effects.

So I'm asking the team what is the purpose of this warning and also why not change it?

**Comment by universse** [comment]
Anyway for your code, I feel there's a more efficient way.
```javascript
const userIds = users.map(u => id)

useEffect(() => {
  if(!userIds.length)
    return
  ...load more stuff by querying endpoints about these ids and set state..
  // since you are setting state here, component will be rerendered, causing the above array.map
  // to re-run and thus userIds is re-computed every render unnecessarilty.
}, userIds)
```

What could be better
```javascript
// so now userIds is only re-computed when users change and not whenever state is set
const userIds = useMemo(() => users.map(u => id), [users])

// here effect only re-run when userIds is recomputed, which in turn depends on users
useEffect(() => {
  if(!userIds.length)
    return
  ...load more stuff by querying endpoints about these ids and set state..
}, [userIds])
```

Or if you don't need to use variable userIds anywhere else
```javascript
// this case, same as above, effect only re-runs when users change
useEffect(() => {
  const userIds = users.map(u => id)
  // ....
}, [users])
```

**Comment by evbo** [comment]
@universse won't your `useEffect` always run after every render due to referential equality?:
```js
['userid1'] === ['userid1']
false
```

**Comment by ngolin** [comment]
> Anyway for your code, I feel there's a more efficient way.
> 
> ```js
> const userIds = users.map(u => id)
> 
> useEffect(() => {
>   if(!userIds.length)
>     return
>   ...load more stuff by querying endpoints about these ids and set state..
>   // since you are setting state here, component will be rerendered, causing the above array.map
>   // to re-run and thus userIds is re-computed every render unnecessarilty.
> }, userIds)
> ```
> 
> What could be better
> 
> ```js
> // so now userIds is only re-computed when users change and not whenever state is set
> const userIds = useMemo(() => users.map(u => id), [users])
> 
> // here effect only re-run when userIds is recomputed, which in turn depends on users
> useEffect(() => {
>   if(!userIds.length)
>     return
>   ...load more stuff by querying endpoints about these ids and set state..
> }, [userIds])
> ```
> 
> Or if you don't need to use variable userIds anywhere else
> 
> ```js
> // this case, same as above, effect only re-runs when users change
> useEffect(() => {
>   const userIds = users.map(u => id)
>   // ....
> }, [users])
> ```

Some other props of `user` may be changed, but useEffect should depend only on `users.map(u => u.id)`. How to accomplish in this case?

**Comment by ngolin** [comment]
> Yup - if you look at the code, it would seem that you can replace
> 
> ```
>     if (nextDeps.length !== prevDeps.length) {
>       warning(
>         false,
>         'The final argument passed to %s changed size between renders. The ' +
>           'order and size of this array must remain constant.\n\n' +
>           'Previous: %s\n' +
>           'Incoming: %s',
>         currentHookNameInDev,
>         `[${prevDeps.join(', ')}]`,
>         `[${nextDeps.join(', ')}]`,
>       );
>     }
> ```
> 
> with
> 
> ```
> if (nextDeps.length !== prevDeps.length)
>   return false
> ```
> 
> and then my use case would be supported _and_ there would be no other negative effects.
> 
> So I'm asking the team what is the purpose of this warning and also why not change it?

We should do this.

**Comment by universse** [comment]
> > Yup - if you look at the code, it would seem that you can replace
> > ```
> >     if (nextDeps.length !== prevDeps.length) {
> >       warning(
> >         false,
> >         'The final argument passed to %s changed size between renders. The ' +
> >           'order and size of this array must remain constant.\n\n' +
> >           'Previous: %s\n' +
> >           'Incoming: %s',
> >         currentHookNameInDev,
> >         `[${prevDeps.join(', ')}]`,
> >         `[${nextDeps.join(', ')}]`,
> >       );
> >     }
> > ```
> > 
> > 
> > with
> > ```
> > if (nextDeps.length !== prevDeps.length)
> >   return false
> > ```
> > 
> > 
> > and then my use case would be supported _and_ there would be no other negative effects.
> > So I'm asking the team what is the purpose of this warning and also why not change it?
> 
> We should do this. Please re-open.

This doesn't solve your problem though, since `users` length is the same. You can consider putting users in the dep array.

**Comment by daggmano** [comment]
Is there any reason NOT to do this? Seems like a lot of console warnings for no real reason, or am I missing something fundamental as to why this may cause issues?

**Comment by dxinteractive** [comment]
Looking at the source code now, there's a comment that seems to indicate that `useEffect` / `useCallback` / `useMemo` dependencies arrays are intended to be passed inline:

https://github.com/facebook/react/blob/efc57e5cbbd618f3c98d941c48eec859026c2dcb/packages/react-reconciler/src/ReactFiberHooks.new.js#L310

```js
...
if (__DEV__) {
    // Don't bother comparing lengths in prod because these arrays should be
    // passed inline.
    if (nextDeps.length !== prevDeps.length) {
       ...
```

If that's the case then it makes sense that it doesn't want the array length to change. But that just changes the question slightly - I'd love to hear from someone on the React team as to why the'd like these dependency arrays to only be passed inline to `useEffect`, `useCallback` and `useMemo`. I'm not able to think of any future movements that they might be leaving open for themselves, but that said I really haven't spent much time looking at their code.

**Comment by dxinteractive** [comment]
Here's another similar discussion: https://github.com/facebook/react/issues/18229

**Comment by dxinteractive** [comment]
Intermediate thing to get you all through. My tests seem to confirm it's all good, but still, use with caution.

```js
import {useEffect, useRef} from 'react';

const equal = (a: unknown[], b: unknown[]): boolean => {
    if(a === b) return true;
    if(a.length !== b.length) return false;
    return a.every((e,i) => Object.is(e,b[i]));
};

export const useEffectVariadic = (create: () => (() => void)|void, deps: unknown[]): void => {
    const prevDeps = useRef<unknown[]>([]);
    const count = useRef<number>(0);

    if(!equal(prevDeps.current, deps)) count.current++;
    prevDeps.current = deps;

    useEffect(create, [count.current]);
};

// usage like normal useEffect

useEffectVariadic(() => {
    console.log("hi");
}, variableLengthArrayOfStuff);

```

**Comment by Madhuri-Dodla123** [comment]
Hi Team, 
It seems i am facing this  issue , Can any one help me with this ?

**index.js:1 Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.

Previous: [false, 1]**

Any thoughts what could be the reason ?
