### ISSUE TITLE
Strict mode exclude?

### ISSUE THREAD

**Issue by mrlubos** [facebook/react#15550]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

React strict mode allows us to wrap components we'd like to get checked. This works great but can become annoying when using 3rd party dependencies we can't control. The current solution is to wrap smaller components in strict mode and exclude the 3rd party components. The issue here is that we have just increased our work by many multiples.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

N/A

**What is the expected behavior?**

It would be great to have an exclude/ignore tag or prop on the React strict mode component. This would allow us to generally define a single strict mode component on the application root and then exclude other components as needed. The idea is similar to how testing frameworks work - you can include files matching certain pattern and exclude things as needed.

Example:

```jsx
<React.StrictMode>
  <App>
    <OurComponent />
    <React.StrictMode ignore>
      <ThirdPartyComponent />
    </React.StrictMode>
  </App>
</React.StrictMode>
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.4

**Comment by bvaughn** [comment]
I think I understand why this seems convenient, but I believe it would also defeat the entire purpose of strict mode- which is to identify and eliminate the things _that would very likely break in concurrent mode_. If an application is using third party code that is not strict mode compatible, then the application is almost certainly not concurrent mode compatible either.

The `StrictMode` component was created to an application to be gradually migrated, so you can wrap small parts of the tree, and gradually move up. If there is a lot of noise coming from third party components, and you _can't_ upgrade or replace them, then I don't know if there's a strong reason for you to use the `StrictMode` component.

**Comment by bvaughn** [comment]
I'm fairly confident this is not a feature we will want to add and so I'm going to close the issue for now. But I'm happy to discuss it further if you have questions or concerns.
