### ISSUE TITLE
shallow render does not work with `memo` and `defaultProps`

### ISSUE THREAD

**Issue by ljharb** [facebook/react#15556]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
shallow renderer does not apply defaultProps to memoized components.

See https://jsfiddle.net/85ags4qh/

**What is the expected behavior?**
defaultProps are applied.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6 of react, react-dom, and the shallow renderer.

**Comment by ljharb** [comment]
Nothing is stale before it’s gotten some attention from maintainers. Please don’t use user-hostile stale bots.

**Comment by gaearon** [comment]
The shallow renderer has moved to https://github.com/NMinhNguyen/react-shallow-renderer. If this is still relevant, please feel free to file this issue there. Thanks!
