### ISSUE TITLE
How to run source code of react

### ISSUE THREAD

**Issue by Johongirrr** [facebook/react#15554]
Hey guys. Sorry to ask a question here but i am very curious to know that i downloaded react's source code and i wanna dive a deeper to get to know things under the hood. but i do not know if it is possible to run source code. my approach is to understand it by debugging. please gimme answer. thank u all :)

**Comment by aweary** [comment]
@Johongirrr check out our [contributor guide](https://reactjs.org/docs/how-to-contribute.html), specifically [the section on the development workflow](https://reactjs.org/docs/how-to-contribute.html#development-workflow) for React. This has some great details on how you can get started with the React repo and source code. Hope that helps!
