### ISSUE TITLE
Create test suite for public API

### ISSUE THREAD

**Issue by spicyj** [facebook/react#1555]
We'd like to have a test suite that tests our public API, in contrast to the existing unit tests that test internal modules.

If the test suite is comprehensive enough, this will allow us to feel confident that we're not making breaking changes accidentally -- unlike the current tests which frequently change with refactors, we wouldn't change these tests except in conjunction with a major release.

(Since the tests would use only the public API, we could also run them under Closure's advanced mode to verify that everything works properly.)

**Comment by aweary** [comment]
Closing this out, since most tests are now testing the public API

More specific work (e.g https://github.com/facebook/react/issues/9955) is now being done and tracked separately.
