### ISSUE TITLE
event.stopPropagation doesnt work for components hydrated inside a content-editable div

### ISSUE THREAD

**Issue by sujitwarrier11** [facebook/react#15555]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Stoppropagation doesn't work in case a component is hydrated inside a content-editable div
please check out the following sample which illustrates this problem.

In the below code I have attached right click handler to both child and parent. on right clicking child both get triggered even though event,stopPropagation has been called.

https://codesandbox.io/embed/0mkoprryxv

**What is the expected behavior?**

the parent event should not be triggered.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

tested with 16.8 version of react.

**Comment by zgoby** [comment]
TestCompenent's onContextMenu is null!

**Comment by sujitwarrier11** [comment]
![image](https://user-images.githubusercontent.com/32289258/57210397-2680e780-6ffa-11e9-872d-d6fb58f4cb0e.png)
 its not

**Comment by zgoby** [comment]
The error you wrote, realDOM's onContextMenu is null.

**Comment by sujitwarrier11** [comment]
Can you please elaborate? I didn't get it

**Comment by sujitwarrier11** [comment]
I found a work around by attaching all the events in the hydrated child component using addEventListener rather then attaching it in the JSX

**Comment by zgoby** [comment]
I mean there are many ways to go wrong, you should learn to be correct.

**Comment by sujitwarrier11** [comment]
> I mean there are many ways to go wrong, you should learn to be correct.

what do you mean by that. My statement is correct. Event bubbling doesn't work properly inside component which is hydrated inside a editable div. the editable div is not recognized as the parent. so we need to add event handlers using the old javascript way using addEventListener
