### ISSUE TITLE
Cursor disappears when typing into an input field

### ISSUE THREAD

**Issue by bhorbal** [facebook/react#15561]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I am using Hooks on a form. I am using a controlled component for one of my input fields. When I try to type into the input field, it allows me to type one character, and then the cursor disappears. I have to use my mouse to place the cursor back in and continue typing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/embed/oonxlv6y79

**What is the expected behavior?**

As a user types in the input field, the letters should continue appearing, the cursor should remain in the input field, and the state should update.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.6
Chrome v73.0.3683.103
Firefox v66.0.3

Never tried it on previous versions.

**Comment by nmain** [comment]
```
const PollTable = () => {
  const FilterInputs = () => { ... }
  ...

  <FilterInputs />

```

You're creating a new instance of a function on every render and then using that as a component type.  Per https://reactjs.org/docs/reconciliation.html, this will cause `<FilterInputs />` and all of its children to be remounted on each render.

You almost never want to render an identity-unstable component  Either `useMemo` to keep the component instance constant, or in this case, you could just treat FilterInputs as a helper function:

```
  return (
    <div className="polls-filter">
      {FilterInputs()}
    </div>
  );
```

**Comment by bhorbal** [comment]
Ah, thanks for catching that!
