### ISSUE TITLE
useEffect doesn't throw warning in case of Promises, just only with Async/Await.

### ISSUE THREAD

**Issue by BiosBoy** [facebook/react#15569]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
The `useEffect` has some strange(different) behavior while the same using via `async` and `Promise`. So, by the first one, I get the warning about wrong asynchronous `useEffect` invoke, that is right. But when I try to make the same trick by `Promises` it works without any warning. I suppose it should throw here a warning too, is not?  

```
 // Will throw warning:
  useEffect(() => {
    async function getData() {
      const payload = await fetch(`some_url`);
      const data = await payload.json();

      setPayload(data)
    }
  }, []);
```

The same by `Promise`:
```
 // No any warning:
  useEffect(() => {
    fetch('some_url')
        .then(res => res.text())
        .then(data => setPayload(data));
  }, []);
```

**What is the expected behavior?**
Should throw the warning in both `async/await` and `Promises` cases.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 - React: v.16.8.6;

**Comment by jquense** [comment]
The second case with plain promise s isn't actually wrong. The warning is about _returning_ a promise from useEffect not using a promise in them. The reason is that async functions automatically return a promise regardless of whether you return anything. This is a problem for useEffect, because the return value should be a teardown function not a promise

**Comment by BiosBoy** [comment]
Hi, @jquense !

Thanks for your reply. Obviously, in both cases, I don't make subscriptions to return a teardown function from useEffect. So, probably that should be described along with `async` warning. Basically, we have the two ways to solve the one case, but only in one provide us with the warning.

Thanks.

**Comment by nattthebear** [comment]
_Exactly as you have written it_, the first example does not throw an error in React, nor does it function at all; `fetch(some_url)` is never called.  What did you mean to write?

**Comment by BiosBoy** [comment]
For some reasons, the warning is gone for both cases. Perhaps it's a problem with my local linter config... Closed.
