### ISSUE TITLE
rules-of-hooks conditionall call intermediate function

### ISSUE THREAD

**Issue by Aprillion** [facebook/react#15570]
**Do you want to request a *feature* or report a *bug*?**
Improvement for the `rules-of-hooks` linter rule.

**What is the current behavior?**

According to https://stackoverflow.com/q/55990985/1176601, the rule detects following pattern:

```
if (x) { return }
return useSomething() // => React Hook "useSomething" is called conditionally.
```

but not

```
if (x) { return }
return Fn()  // with useSomething inside => no complaint
```

**What is the expected behavior?**

Traverse more levels of function calls to detect conditional hooks?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Not mentioned in the SO question, assuming React 16.8.6

**Comment by threepointone** [comment]
Can you make a codesandbox with an example of what you’re describing?

**Comment by Aprillion** [comment]
Oh, I didn't know it's possible to run eslint in codesandbox. 

I'm not the original poster of the stackoverflow question, so if the problem is hard to reproduce for React maintainers then I am not sure I will be able to figure it out - but I will make time for this within a few days.

**Comment by aweary** [comment]
The constraint here is that Hooks need to start with `use*`, so if you do `Fn()` then React assumes it's not a hook. Without this constraint React would need to check every function call, and to be completely safe it would have to do so recursively which would be a ton of work.
