### ISSUE TITLE
Cursor Jumping to end in Input if we use toUpperCase() on e.target.value

### ISSUE THREAD

**Issue by Sandeep023** [facebook/react#15574]
Reporting a Bug

The current behavior is if we use toUpperCase or toLowerCase in onChange on e.target.value, the cursor is jumping to the end while editing in middle.

In Input text using toUpperCase in onChange function on, e.target.value the cursor is jumping to end while updating in the middle

The cursor should retain its position

`<Input
            type="text" id="value" height="60px"
            value={this.state.val}
            onChange={(e) => {
              /^[a-zA-Z ]*$/.test(e.target.value) ? this.setState({ val: e.target.value.toupperCase() }) : null;
            }}
            maxLength = '45'
            />`

**Comment by Sandeep023** [comment]
An example in this,
[https://codesandbox.io/s/8yql26w0lj](url)

**Comment by AlekNiebla** [comment]
hey I'm a first time contribuitor on this project, can I take on this issue?

**Comment by TrySound** [comment]
It's not really a problem with react but with input itself.
https://codesandbox.io/s/m4r6myo5ny

There is a library which is able to solve your problem. Rifm will handle input cursor for you.
https://github.com/istarkov/rifm
Here's an example https://codesandbox.io/s/1ownk85rw7

**Comment by AlekNiebla** [comment]
Hey I've solved this issue using only React, there was a mistake in the validation inside the componendDidUpdate() where it was validating if the value was the same as before, but that never happened. I'll attach a codesandbox with the solution I found.

https://codesandbox.io/embed/yvm9lnx2k9?fontsize=14

**Comment by Sandeep023** [comment]
Thanks for the reply AlekNiebla and TrySound,

But What if I want to do it without using 'ref' like in

https://codesandbox.io/s/w014wpyy6l

**Comment by AlekNiebla** [comment]
I think the problem is that since the app is writing the whole value again every time it detects a change, it's like a user writing the whole thing from scratch again, which will always leave the cursor at the end unless we save the position where the user started writing.

I'll keep fiddling with the code and check the React repository to see if I can find a way to make it behave like the previous solutions that use 'ref'.

**Comment by audiolion** [comment]
@Sandeep023 

https://codesandbox.io/s/j2531073y9

you are replacing the entire value of the input when you call `toUpperCase` and so the selection is reset to the end. This is a pretty non-standard behavior, so using a ref to manage selection like in the example I linked above would be the way to go about this.

**Comment by TrySound** [comment]
Rifm does not require ref. It's just render prop. Hook version is coming soon.

**Comment by Sandeep023** [comment]
Thank you so much for your help. I am closing the issue now
