### ISSUE TITLE
checkPropTypes is not a function

### ISSUE THREAD

**Issue by okhy** [facebook/react#15573]
**Do you want to request a *feature* or report a *bug*?**
Bug report
**What is the current behavior?**

Hello, during jest/enzyme run I get the following error `TypeError: checkPropTypes is not a function` whenever I use a module that uses proptypes (like `react-router` in my case).

During my research I've concluded that Typescript sees PropTypes as {} even though I'm using `@types/prop-types` and I can see properly typed `checkPropTypes` function there.

Is there any suggestion you could give to help resolve this issue?

Project/code repo: https://github.com/okhy/ERM/tree/TASK_6_Routing
Related issue in another repo: https://github.com/ReactTraining/react-router/issues/6721

####How to reproduce: 
1. checkout `TASK_6_Routing` branch
2. `npm i`
3. `npm run dev`
4. `npm run test`

**What is the expected behavior?**
Tests passing.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "^16.8.4",
"react-dom": "^16.8.4",
"react-router-dom": "^5.0.0",
"enzyme": "^3.9.0",
"enzyme-adapter-react-16": "^1.12.1",
"jest": "^24.7.1",

**Comment by milesj** [comment]
Have you actually installed `prop-types`? `npm install prop-types`

**Comment by AlekNiebla** [comment]
your branch seems to have some incorrect import sources.

**Comment by okhy** [comment]
@milesj thanks for pointing that out. Unfortunately after installing both `prop-types` and `@types/prop-types` the error still shows up :/

@AlekNiebla that was not the cause, but thank you, fixed that locally.

**Comment by okhy** [comment]
Upon further investigation:

console log of imported `prop-types` in `react.development.js` returns following:
``` javascript
 { array: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      bool: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      func: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      number: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      object: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      string: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      symbol: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      any: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      arrayOf: [Function: createArrayOfTypeChecker],
      element: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      elementType: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      instanceOf: [Function: createInstanceTypeChecker],
      node: { [Function: bound checkType] isRequired: [Function: bound checkType] },
      objectOf: [Function: createObjectOfTypeChecker],
      oneOf: [Function: createEnumTypeChecker],
      oneOfType: [Function: createUnionTypeChecker],
      shape: [Function: createShapeTypeChecker],
      exact: [Function: createStrictShapeTypeChecker],
      checkPropTypes: {},
      resetWarningCache: undefined,
      PropTypes: [Circular] }
```
and you can see imported object has `checkPropTypes` defined as an empty object (`{}`)

**Comment by bvaughn** [comment]
Looks like the repro code link (https://github.com/okhy/ERM/tree/TASK_6_Routing) has been deleted, so I'm closing this issue. Hope you got it sorted out!
