### ISSUE TITLE
Is 'this pattern' of using hooks recommended?

### ISSUE THREAD

**Issue by kkalavantavanich** [facebook/react#15575]
This is not a feature request or a bug report, but more of a question regarding React. 

I am new to using custom hooks. I don't know if anyone has done this before; I don't even know what this pattern is called, or what to search for. I have a child component and parent component. The parent contains many, many different children. I don't want to keep all of the data in the parent as it would became very unmaintainable very fast. IMHO, global stores also would eventually became unmaintainable. I am currently looking for an alternative that may prove to be cleaner than current solutions. 

I have an idea to segregate the data responsibility to children instead of the keeping all of the data in the parent. My idea is show below. 

```jsx
// useChild.js
const useChild = () => {
  const [data, setData] = useState(0);
  
  const saveData = () => sendDataToSaveOnRemoteAPI(data);

  useEffect(() => {
    setData(fetchDataFromRemoteAPI());
  }, []);

  const Child = <Display data={data} />

  return { Child, saveData }
}
```

```jsx
// Parent.js
const Parent = () => {
  const { Child, saveData } = useChild();
  const { AnotherChild, saveAnotherData } = useAnotherChild();

  const saveAll = () => {
    saveData();
    saveAnotherData();
  };
  return (
    <div>
      <Child />
      <AnotherChild />
      <SaveButton onClick={saveAll} />
    </div>
  );
}

```

To me, it looks kinda clean that data responsibility is remove from the parent. The logical flow also looks clean in my opinion; when the `SaveButton` is clicked, `Child` will save the data it is responsible for. The downside may be that this is contradictory to what has always been done in React land. I suppose that normally we would keep all the data in the Parent or other state management solutions and Child might be a stateless component, etc. 

Is this pattern documented anywhere? Is this pattern recommended?

**Comment by malerba118** [comment]
Interesting approach, I haven't seen this pattern before. It seems like you've made a multiple return value component. Personally I'd prefer to keep the api logic decoupled from jsx.
```jsx
const useRemoteApi = () => {
  const [data, setData] = useState(0);
  
  const saveData = () => sendDataToSaveOnRemoteAPI(data);

  useEffect(() => {
    setData(fetchDataFromRemoteAPI());
  }, []);

  return { data, saveData }
}

const Parent = () => {
  const { data, saveData } = useRemoteApi();
  const { moreData, saveMoreData } = useAnotherRemoteApi();

  const saveAll = () => {
    saveData();
    saveMoreData();
  };
  return (
    <div>
      <Child  data={data}/>
      <AnotherChild data={moreData} />
      <SaveButton onClick={saveAll} />
    </div>
  );
}
```

**Comment by otakustay** [comment]
Much like the [context.write](https://github.com/acdlite/rfcs/blob/context-write/text/0000-context-write.md) rfc with `write` function passed to children.
