### ISSUE TITLE
[Enhancement]Split hoooks API into a seperate library instead of react, maybe react-hooks.

### ISSUE THREAD

**Issue by TotooriaHyperion** [facebook/react#15572]
**Do you want to request a *feature* or report a *bug*?**
An enhancement

**What is the current behavior?**
hooks API is bundled in the react library

**What is the expected behavior?**
split hooks API into a seperate library

Reason:
- 1.hooks is a API design, didn't have to be strictly related to/couple with specific library.
- 2.I'm forced to translate a project written in react-hooks into vue.
Thanks to the hooks api and rxjs, 80% of my code don't need change, but I have to 
  - 2.1:hack in to replace the react hooks import syntax through webpack loader,
  - 2.2:and use dummy file/declaration to hack the TS type check. 
  - If we have a react-hooks library, we can simply use NormalModuleReplacementPlugin to replace the import syntax from 「import {...} from "react-hooks"」 to「 import {...} from "@myfork/vue-hooks"」 and don't need to handle the TS type check in an ugly way.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6

**Comment by threepointone** [comment]
Hooks are pretty integral to react, and this seems like a pretty specific edge case to do such a drastic change. I would recommend instead that you make a separate library yourself that satisfies your constraints, and use that instead (and thus, you can then swap it/alias it as you need). Closing this issue for now.
