### ISSUE TITLE
setValue in microtask jumps the cursor to the end

### ISSUE THREAD

**Issue by Diokuz** [facebook/react#15588]
**Do you want to request a *feature* or report a *bug*?**
Not sure)

**What is the current behavior?**
1. I have a controlled component
```js
const Input = () => {
  const [val, setVal] = useState('')

  return <input value={val} onChange={(e) => {
    const { value } = e.target

    setValue(value)
  }} />
}
```

2. I type `foo`
3. I move the cursor to `f^oo`
4. I type `b`
5. I get `fb^oo` – that's okay.

I have another component:

```js
const Input = () => {
  const [val, setVal] = useState('')

  return <input value={val} onChange={(e) => {
    const { value } = e.target

    Promise.resolve().then(() => setValue(value))
  }} />
}
```
Do the same things 2-4.
5. I get `fboo^` – the cursor jumps to the end. Why?)

I understand why that happens when the value is formatted in some custom way – React just don't know how to handle cursor position properly.
https://github.com/facebook/react/issues/955#issuecomment-160826950

But why React does not handle the cursor position when I call setVal asynchronous (in the microtask)?

Probably there are good reasons for that – just name them then)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.8.3, chrome.

**Comment by nmain** [comment]
Controlled text inputs are a little white lie; when you have a non-disabled, non-readonly `<input type=text>` in the DOM and you smash your keyboard at it, the value in the input _will_ change.  But that's not well suited to React's dataflow, so it paves over things to keep the illusion alive.  To do so, React has to look at the value you set for the input after all of the event handlers have run, and see if it matches the value that is in there.  If it does, which will be the case when your code simply "accepted" the onChange, React doesn't have to do anything.  If it doesn't, in the case when your code did not respond to onChange or set a completely different value in the input, then React has to patch up the input by changing its value.  When you change a text input's value, the cursor jumps to the end.

In your case, after flushing all events React sees that you did not make any changes to `value`, so it has to dutifully reset the underlying dom element's value.  It has no way to know that at some future point in time that's not that far away, you'll make everything pleasant again, and even if it did know it would need to change the value back now to be consistent with anything else that tried to work with `value` before your microtask ran.
