### ISSUE TITLE
Naming convention for React's environment variables

### ISSUE THREAD

**Issue by mayankshah1607** [facebook/react#15607]
Hi! I'm new here. 
So, I've been using react for quite sometime, and recently came across how environment variables are named. Why is it that custom env variables in the .env file must always being with "REACT_APP_"? This sometimes tends to get inconvenient. Is there a specific reason for this?
Has a fix been issued?
I could not find a lot of information regarding why this is so. Would be really helpful if someone could help me out here! :)

**Comment by threepointone** [comment]
You should probably post this at https://github.com/facebook/create-react-app/issues I would also recommend you specify exactly why you find it inconvenient, it’s not clear from your question exactly what the problem is with the prefix; seems like a perfectly reasonable namespace.

**Comment by mayankshah1607** [comment]
Sure, thanks! :)
