### ISSUE TITLE
Maybe remove children saved in `__reactEventHandlers` will save a lot of memory

### ISSUE THREAD

**Issue by Jokcy** [facebook/react#15609]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
See issue #15527 . `__reactEventHandlers` will save its latest updated version of props which contain `children`. Since a lot of nodes will not always update they may hold a very old version of `children`.

I guess it's useless, so I update the `updateFiberProps` function to this:

```js
export function updateFiberProps(node, props) {
  const newProps = {
    ...props,
    children: null,
  };
  node[internalEventHandlersKey] = newProps;
}
```

and I run all the tests, all passed.

Is there any reason we can't get rid of the `children` saved on native element node?

**Comment by gaearon** [comment]
Just confirmed this is a known (although unfortunate) design tradeoff.

**Comment by safareli** [comment]
Is there some article / documentation where I can learn more about this design tradeoff?

I have big objects passed around as props and I noticed old versions of it being retained by __react* properties.

Any suggestions on how to bypass storing of this in __react* properties?

**Comment by gaearon** [comment]
I'm fairly sure we're already cleaning them up in React 18. Do you have a repro case showing we don't?

**Comment by safareli** [comment]
I'm on react 16.14.0 will try to update...
