### ISSUE TITLE
[Question] does react-hooks feature support SSR with multi threading.

### ISSUE THREAD

**Issue by SheikhG1900** [facebook/react#15601]
**Do you want to request a *feature* or report a *bug*?**
It is just a question.

**Question**
As per the documentation, hooks depend on the order of their callings. Will it work on SSR multi threading?

**Comment by threepointone** [comment]
Yes? SSR works perfectly well with hooks, it associates the hooks values with the respective fiber in the internals. Closing this, but lemme know if you find a bug or problem.

**Comment by SheikhG1900** [comment]
> Yes? SSR works perfectly well with hooks, it associates the hooks values with the respective fiber in the internals. Closing this, but lemme know if you find a bug or problem.

No i didn't find any issue but were curios would hooks work with SSR or not. Thanks for your reply.
I thought if multiple request come to sever, would server be able to render simultaneously for all requests. 
I am happy to here that web hooks are thread safe.
