### ISSUE TITLE
[Feature] Add useProps hook

### ISSUE THREAD

**Issue by zheeeng** [facebook/react#15605]
**Do you want to request a *feature* or report a *bug*?**
Feature

Expect a built-in hook which provides props reading capability. 

Assume this situation:

```javascript
import React, { useProps, useMemo } from 'react'

const usePeopleListLogic = () => {
    const { peopleList, searchText } = useProps

   const list = useMemo(
       () => peopleList.filter(item => item.name.includes(searchText)),
       [peopleList, searchText]
    )

    return { list }
}

const PeopleList = () => {
    const { list } = usePeopleListLogic()

   return <List>{list.map(item => <Item {...item} />)</List>}
}
```

I expect to have a convenient way to separate logic and rendering and without passing props to `useLogic` hook.
We have no such ability to implements this third-party hook, only react can.

**Comment by thoamsy** [comment]
You use the `useProps` hooks in a custom hooks, and then you use the custom hooks in some Component which doesn't has the props, what will happen? 
And I think if they are two separate files, nobody can understand the code's meaning but you. It's a magic.

**Comment by threepointone** [comment]
It’s not clear what purpose this would solve, especially when passing regular arguments would be clear and explicit. I’m closing this issue, but lemme know if I’m missing something here.

**Comment by zheeeng** [comment]
> You use the `useProps` hooks in a custom hooks, and then you use the custom hooks in some Component which doesn't has the props, what will happen?
> BTW, I think if they are two separate files, nobody can understand the code's meaning but you. It's a magic.

But we still have useContext, which could be null if no provider wrapped the component's ancestor.

**Comment by adrianhelvik** [comment]
It would allow backwards compatibility on Redux selectors for instance.

**Comment by NugzarGaguliya** [comment]
I think it's very comfy hook. 
You do not need to pass parts of props to all user hooks and can get them inside.
It decrease component's complexity.
