### ISSUE TITLE
[Question] Is it a way React trying to deprecate Class based component and favor functional component by gearing up React's functional components with 10 different interesting hooks methods?

### ISSUE THREAD

**Issue by adamchenwei** [facebook/react#15615]
I just curious since seems functional component is getting a lot more attention now vs class based. Also would appreciate if the rationale or roadmap behind it if it's true.
Feel free to answer that on Quora as well!
https://www.quora.com/unanswered/Is-it-a-way-React-trying-to-deprecate-Class-based-component-and-favor-functional-component-by-gearing-up-Reacts-functional-components-with-10-different-interesting-hooks-methods

@gaearon would it be a valid question for you to answer?

**Comment by jquense** [comment]
Hi there, check out the documentation and blog posts around hooks: 

https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy
