### ISSUE TITLE
<embed> doesn't trigger onLoad

### ISSUE THREAD

**Issue by cherniavskii** [facebook/react#15613]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`<embed>` doesn't trigger `onLoad`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/9yrqzw71xp

**What is the expected behavior?**
`<embed>` should trigger `onLoad`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6

**Comment by omriLugasi** [comment]
**Side Note**
According to [MDN(embed)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed)  and see also [Global_attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) 
The `<embed>` can include the `onload` event.
