### ISSUE TITLE
[Help] Cursor jumps to end when input value comes from provider wrapper

### ISSUE THREAD

**Issue by TronchDeYack** [facebook/react#15610]
Hi everyone, I have currently facing a problem with provider (from unstated lib) and input.
In our project, we have to share inputs values between several components, so we have created a provider (with unstated lib) that contains the values. The values are passing as props into SearchForm component thanks to withSearchFields function.

**What is the current behavior?**
The problem is, each time we want to update the value at any position, the cursor jumps to the end of the input.

I have simplified our code and add it in CodeSandbox : https://codesandbox.io/s/n2w9xv090

**What is the expected behavior?**
The cursor doesn't go to the end.

**Which versions of React ?** 16.8.6

Could you help us to understand what's going on please ? I think the problem comes from the props injection by the provider.

Thank you for your help ! 
![bitmoji](https://render.bitstrips.com/v2/cpanel/359644fb-c5df-4412-9bc7-ae838696ef14-2f2df822-b107-45d5-a129-564123b6c4ca-v1.png?transparent=1&palette=1&width=246)

**Comment by aplaskota** [comment]
Hi @TronchDeYack 

I was playing for a while with your example and I was able to set the cursor wherever I wanted. So either I don't see the problem or I don't understand it.

**Comment by TronchDeYack** [comment]
Hi @aplaskota, try to type something at the middle of the input value.

For example, i have "arg arg" in the first input. If I type several 'b' in order to have "arg bbbbarg", I will have "arg bargbbbbbb" instead.

**Comment by kunukn** [comment]
I can see the issue for your case. 

I have recreated the example you had using only Context API and could not reproduce the issue you had. 
https://codesandbox.io/s/pm36z3po67

I suspect the issue is either within the unstated library or there might be bugs in your code. 
Maybe create a bug report at unstated github site or create a stackoverflow issue?

**Comment by TronchDeYack** [comment]
Ok thank you, I will try with the Context API. =)
