### ISSUE TITLE
[Question] Shouldn't the TypeScript definition for Reducers enforce ReadOnly for prevState?

### ISSUE THREAD

**Issue by justinhelmer** [facebook/react#15618]
I was a little bit surprised that my reducer was letting me modify the `state` argument, in a TypeScript project:

```ts
const reducer: Reducer<SomeStateType, SomeActionType> = (state, action) {
  switch (action.type) {
    case 'increment':
      state.count += 1;
      break;
    default:
      throw new Error();
  }

  return state;
}
```
**What is the expected behavior?**

I would expect to see:

```
TS2542: Index signature in type '<Readonly<SomeStateType>>' only permits reading.
```

**Suggested change**
Unless I'm not correctly understanding all of the use-cases, we should never be able to modify the `state` argument in the example above. What do you think about updating the type definition for `Reducer`?

```ts
type Reducer<S, A> = (prevState: <Readonly<S>>, action: A) => S;
```

I also tested that there is no negative implication of "double-wrapping" with `Readonly`, in the case where `S` is already defined as a `Readonly` type, i.e.

```ts
// @file some-reducer.ts
type S: <Readonly<SomeStateType>>;

// @file react/index.d.ts
type Reducer<S, A> = (prevState: <Readonly<S>>, action: A) => S;
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

using: react@16.8.6 (`useReducer` hook)

**Comment by kunukn** [comment]
Unless I am mistaken, I believe there is no "official" Typescript definitions from the React team. This is the closest thing I found from the source code which don't have anything about hooks.

react/src/__tests__/testDefinitions/React.d.ts

```jsx
/**
 * TypeScript Definition File for React.
 *
 * Full type definitions are not yet officially supported. These are mostly
 * just helpers for the unit test.
 */
```

Where do you get the definitions from? Is it from `@types/react`?

---

Regarding the statement 
>we should never be able to modify the state argument in the example above

My opinionated statement is: I would trust the developers to write the code they want and let the linters do the warnings.

I would allow developers write code like this. Here the state is mutated, but the developer knows it and make sure the returned value is a new object. I would not write code like this myself, but I would not disallow other to write in the pattern they want. Unless if there is a really good reason.

```jsx
const reducer = (state, action) => {
  switch (action.type) {
    case 'increment':
      state.count++;
      break;
    default:
      return state;
  }

  return {...state};
}
```

**Comment by justinhelmer** [comment]
Ah, yes maybe it wasn't fair to assume `@types/react` comes from the react team. Since the npm package always points to `DefinitelyTyped`, it can be difficult to trace down the actual GitHub repo without digging into the got history itself. If someone would point me in the right direction, I'd be more than happy to move my concerns to the right audience.

In terms of your "what about this" scenario, @kunukn - what you are saying is totally valid. However, buying into TypeScript is a trade-off - you don't get as much flexibility as you would without it, but you are protected from common pitfalls as build-time. So although I agree with you that there are valid patterns that would NOT cause issues (although your example is still mutating the original object), my argument is that those who buy into TypeScript want the level of protection as a priority over flexibility.

I will say personally, I was surprised that the typedef allowed me to mutate the original object. But perhaps there is a scenario that I don't understand, and the `@types/react` authors have already thought about this.

I appreciate your input, @kunukn - always a good thing to get different perspectives.

**Comment by threepointone** [comment]
This should probably be filed at https://github.com/DefinitelyTyped/DefinitelyTyped/issues
