### ISSUE TITLE
How to handle the form in Reactjs?

### ISSUE THREAD

**Issue by Kashif1Naqvi** [facebook/react#15626]
Hello World ,I'm sure you  will be fine 🙂 

ANY ONE TELL ME HOW FORMS WORK IN REACTJS?

When user click on submit button how data display under the form i see from react documentation ,About form less guide me,So any one here for helping me.thank you in advance

**Comment by revskill10** [comment]
@Kashif1Naqvi You store input value in state, when submit, you use `state` values to handle.

Or, you can get values directly from `input fields`.

**Comment by threepointone** [comment]
We have a whole section on forms here https://reactjs.org/docs/forms.html

We use this tracker for bugs and feature requests, so will close this issue. Would recommend you use a community resource or stackoverflow for further questions https://reactjs.org/community/support.html
