### ISSUE TITLE
Unable to eliminate 'Each child in a list should have a unique "key" prop' warning.

### ISSUE THREAD

**Issue by shangdev** [facebook/react#15620]
**Do you want to request a *feature* or report a *bug*?**

Feature / Bug

**What is the current behavior?**

I am use Lists(Material-UI components) render nav. But 'Each child in a list should have a unique "key" prop' warning always appears.

![image](https://user-images.githubusercontent.com/15621520/57566124-747f5c00-73fb-11e9-8e42-92295f0eae60.png)

I am pretty sure that the key attribute has been added for List and ListItem under each map, and the value is unique.

This is code:
```
import React from 'react';
import { List, ListItem, ListItemText } from '@material-ui/core';

const  data = [
  {
    id: '1',
    caption: 'Index',
  },
  {
    id: '2',
    caption: 'About',
  },
  ...
];

class BWKNav extends React.Component {
  render() {
    return <React.Fragment>
      <List component="nav">
         {
           data && data.length > 0 && data.map((item1, index1) => {
             return <React.Fragment>
               <ListItem key={`1${index1}`} divider={true}>
                 <ListItemText primary={item1.caption} />
               </ListItem>
               {/* Here loop secondary menu, Even if I only run the current code, this warning will still appear */}
             </React.Fragment>
         }
      </List>
    </React.Fragment>
  }
}
```

**What is the expected behavior?**

Eliminate warnings.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

latest.

**Comment by thomasheyenbrock** [comment]
You have to pass the `key` to the `React.Fragment`.

**Comment by threepointone** [comment]
^ like @thomasheyenbrock said, the root element in the array should have a key prop. Further, you should probably give a key based on your item's id, or you'll risk a bug of the list gets reordered. Rewriting your component (and removing another unnecessary Fragment) -

```jsx
import React from "react";
import { List, ListItem, ListItemText } from "@material-ui/core";

const data = [
  {
    id: "1",
    caption: "Index"
  },
  {
    id: "2",
    caption: "About"
  }
  // ...
];

class BWKNav extends React.Component {
  render() {
    return (
      <List component="nav">
        {data &&
          data.length > 0 &&
          data.map((item1, index1) => {
            return (
              <React.Fragment key={item1.id}>
                <ListItem divider={true}>
                  <ListItemText primary={item1.caption} />
                </ListItem>
                {/* Here loop secondary menu, Even if I only run the current code, this warning will still appear */}
              </React.Fragment>
            );
          })}
      </List>
    );
  }
}
```

**Comment by mehdi514** [comment]
render() {
    if (this.state.loading) {
      return (
        <View style={styles.loader}>
          <ActivityIndicator size="large" color="#211f1d" />
        </View>
      );
    }
    const { dataSource } = this.state;
    console.log(dataSource);
    return (
      <View style={styles.container}>
        <Text style={styles.title}>All Licences</Text>
        <FlatList
          showsVerticalScrollIndicator={false}
          data={this.state.dataSource}
          keyExtractor={result => result.id}
          // renderItem={item => this.renderItem(item)}
          renderItem={({ item }) => {
            return (
              <TouchableOpacity
                style={styles.list}
                onPress={() => this.props.navigation.navigate("LicenseDetails")}
              >
                <Text style={styles.textStyle}>
                  {item.firstName} {item.lastName}
                </Text>
              </TouchableOpacity>
            );
          }}
        />
      </View>
    );
  }


Couldn't resolve this issue. Anyone please help to get rid off this issue

**Comment by mehdi514** [comment]
`render() {
    if (this.state.loading) {
      return (
        <View style={styles.loader}>
          <ActivityIndicator size="large" color="#211f1d" />
        </View>
      );
    }
    const { dataSource } = this.state;
    console.log(dataSource);
    return (
      <View style={styles.container}>
        <Text style={styles.title}>All Licences</Text>
        <FlatList
          showsVerticalScrollIndicator={false}
          data={this.state.dataSource}
          keyExtractor={result => result.id}
          // renderItem={item => this.renderItem(item)}
          renderItem={({ item }) => {
            return (
              <TouchableOpacity
                style={styles.list}
                onPress={() => this.props.navigation.navigate("LicenseDetails")}
              >
                <Text style={styles.textStyle}>
                  {item.firstName} {item.lastName}
                </Text>
              </TouchableOpacity>
            );
          }}
        />
      </View>
    );
  }`

Couldn't resolve same issue in above code. Please help me to get rid off this issue.

**Comment by yncardoso** [comment]
> You have to pass the `key` to the `React.Fragment`.

This didn't work for me.

```
{items.map(item => (
  <React.Fragment key={item.id}>
	<TableRow>
	  <TableCell component="th" scope="row">{item.name}</TableCell>
	  <TableCell align="right">{Moment(item.createdAt).format('DD/MM/YYYY')}</TableCell>
	  <TableCell align="right">{item.active ? 'Yes' : 'No'}</TableCell>
	</TableRow>
  </React.Fragment>
))}
```

**Comment by sachintsm** [comment]
<div className="container card-content">
                                            {this.state.pumps.map((pump) =>
                                                <div className="row div-pump" key={pump.machineNumber} style={{ marginLeft: "10px", marginRight: "10px" }} >
                                                    <div className="col-md-2">
                                                        <label className="des-pump"> {pump.machineNumber}</label>
                                                    </div>
</div>
</div>

**Comment by zys** [comment]
Having the same problem. Any suggestions?

**Comment by femiveys** [comment]
I have added keys to all my children and I still get this error.
I think this is a bug

**Comment by femiveys** [comment]
I found the solution here:
https://github.com/ant-design/ant-design/issues/7623#issuecomment-403331875

Every record (your rows) also need a "key"

**Comment by zys** [comment]
I believe that worked. I removed the `React.Fragment` and passed the "key" to the "TableRow".

Thanks

**Comment by NiaLikesCode** [comment]
I'm having a similar issue but I have the key prop. So I'm unsure of what it's complaining about

`{props.vocabList.map(vocab => (
                <AccordionPanelElement
                    key={vocab.id}
                    isChecked={vocab.selected}
                    name={vocab.value} />
            ))}`

**Comment by femiveys** [comment]
Every item of vocabList needs to have a "key" prop as well. See my comment above.

**Comment by nimpossible** [comment]
I believe adding the key to `React.Fragment` is not a full-proof solution even if it works. This is because it will not list the applied `key` in the `React Developer Tools`. There should be a mechanism where the Developer can see from the Dev Tool itself as what key is passed which can be seen when we pass it to a custom React Component.

**Comment by petercutting** [comment]
the warning and stacktrace are not very helpful in locating the actual line of code that is buggy. would appreciate some more precise info that will allow me to zero in on the bug

**Comment by marcianosr** [comment]
I had the same issue and found this thread. I applied (also unnecessary) <Fragments> just to remove the warning, but I don't understand why this is needed since I'm passing the `key` prop to the closest element in my loops already. 

Does someone knows how this works?

**Comment by ctsstc** [comment]
I just spent far too long to find out that it wasn't the `<li>` tag that was throwing the error, which already had unique `key` values, it was actually the parent `ul` tag that needed the key 🤦

**Comment by vgjenks** [comment]
I have this problem and adding the key to each item doesn't matter. Add to this; there's only one item! So...why would it yell at me about uniqueness?

`import React from "react";

import ContextButton from "../global/context_button";

import "./scss/experience.scss";

const Experience = props => {
    let { experiences } = props;

    const onEditClick = () => {
    };

    const experiencesList = () => {
        return experiences.map(exp => (
            <div id={exp.id}>{exp.title}</div>
        ));
    };

    return (
        <div className="experience-container">
            <div className="experience-body">
                <div className="experience-title">
                    Experience
                </div>
                <div className="experience-content">
                    {experiencesList()}
                </div>
            </div>
            <div className="experience-edit">
                <ContextButton icon="bytesize:edit" onClick={() => onEditClick()} />
            </div>
        </div>
    );
};

export default Experience;`

Output:

![image](https://user-images.githubusercontent.com/7227674/141837853-47671fab-a98d-4012-a32b-dd7652f598ac.png)

**Comment by amitshahc** [comment]
As and when i see this error in console. i am happy to resolve it by adding key attribute. but a simple problem is it never tells that which entity/element is missing it. i tried adding keys all over the loops and even non-loops but the error not getting off. Can you put just a simple element name which requires the key in error message?

Thanks.

**Comment by mmontag** [comment]
Surprising that this is still a snag in React development coming up on the year 2022.  It would save a lot of developer pain if the warning could point out some information about the elements with missing keys. 

You can approximate this if you enable "Break on Warnings" in React Dev Tools and look through the stack trace around the `validateChildKeys`/`validateExplicitKeys` methods - local variables in these frames will pinpoint the offending elements.

**Comment by kirkstrobeck** [comment]
In my case it was a function that used a spread for the props, so this didnt work

```tsx
<div {...spreadProps()} key={id} />
```

this did

```tsx
const { key, ...partialSpreadProps } = spreadProps();

<div {...partialSpreadProps} key={id} />
```

**Comment by renardbergson** [comment]
> You have to pass the `key` to the `React.Fragment`.

Thank you!

**Comment by b310L** [comment]
> I just spent far too long to find out that it wasn't the `<li>` tag that was throwing the error, which already had unique `key` values, it was actually the parent `ul` tag that needed the key 🤦
> 
> I agree we need better error handling around this.
> 
> I spent far too long thinking it must be some weird bug with passing `children` in a HOC / wrapper for a `ul` and `ol` element.

Thanks. This  work for me.

**Comment by Minah-Pro-Design** [comment]
a common error is to render a list without a "key" being specified or Using “Index” as a Key (**Not Always a Good Idea**). The best practice is to give each item in the list a unique identifier, like an "id":

```
    const items = [
      { id: 1, name: "Apple" },
      { id: 2, name: "Banana" },
      { id: 3, name: "Orange" },
    ];
    
    function FruitList() {
      return (
        <ul>
          {items.map((item) => (
            <li key={item.id}>{item.name}</li>
          ))}
        </ul>
      );
    }
```

By giving each item in a list a unique key, I allow React to update the UI correctly. you can read more [here]( https://medium.com/@minahmmassy/solving-each-child-should-have-a-unique-key-warning-in-react-7373a9cd740e)
