### ISSUE TITLE
[Question] react-debug-tools package and `overrideHookState` devtool internal

### ISSUE THREAD

**Issue by chenesan** [facebook/react#15624]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

For now, React has not published `react-debug-tools`. I proposed building an api in enzyme to get hook state through it (See https://github.com/airbnb/enzyme/issues/2120
). So I'd like to know when React core team will publish this. Or at least, to make sure if we can safely use that module in the future, through npm package or devtool hook.

Also I'd like to leverage the `overrideHookState` api injected into devtool to set hook stat in enzyme. I'd like to ask:

1. Is it possible to put this into `react-debug-tools`?
2. If not, is it safe (i.e. react will not drop or change `overrideHookState` api easily)for a third party user(not react nor react-devtool) to use it through building a custom devtool hook(So react will inject it into enzyme)?

**What is the expected behavior?**

I hope `react-debug-tools` published soon and `overrideHookState` can be included. Or at least I'd like to know if build a custom devtool hook to get `overrideHookState` is safe or not.

I know some people would think it's not a good testing strategy to get / set hook state directly. But I think it's still valuable to be able to do that in some cases.

Also cc @ljharb

**Comment by threepointone** [comment]
It's definitely not a good idea to get/set hook state directly in tests. react-debug-tools is an internal package, not meant to be exposed yet as a public api. we don't plan on exposing devtools specific helpers either. 

It's hard to judge requests like this without a clear usecase. I'm closing this issue, but let me know if I misunderstood something.

**Comment by chenesan** [comment]
Hi @threepointone , thanks for reply:) I opened this issue because I saw in https://github.com/facebook/react/pull/14906 @bvaughn said that react should release `react-debug-tools` soon. So if I understand it correctly that would be a public package, right?

Also I'm not sure if devtool helpers is really for react-devtools only, or utls ok to use it build another development tool.

**Comment by threepointone** [comment]
I should have phrased it better. It’s undergoing change before it will. But you still won’t be able to set it’s state externally. 

I don’t believe the devtools helpers are meant to be used by third parties, but will confirm

**Comment by bvaughn** [comment]
The plan is for the [`react-debug-tools` package](https://github.com/facebook/react/blob/master/packages/react-debug-tools) to eventually be released as an external NPM module. It's embedded in DevTools at the moment because we weren't ready to release it yet.

**Comment by ljharb** [comment]
@bvaughn when it does, will hook introspection APIs be reliable in future versions of react?

**Comment by bvaughn** [comment]
If it is released in some form, we would follow normal semver practices with regard to the API.

**Comment by ljharb** [comment]
Oh certainly :-) what i mean is, will hooks be introspectable for the foreseeable future, or is it too early to commit to that?

**Comment by chenesan** [comment]
@bvaughn Thanks for reply. I have 2 questions here:

1. Is it possible to put `overrideHookState` (or any module can set hook state) into react-debug-tools? Since it's a "debug" tool I think that would be useful to include it (e.g. people can change state and inspect it when they're debugging). It would also be helpful for other development tool like enzyme to control hook state.

2. If ans to (1) is no. Is it safe / reliable for a 3rd party to build a custom devtool hook to get devtool helpers(e.g. `overrideHookState`)? Or it's devtool-only?

**Comment by bvaughn** [comment]
> will hooks be introspectable for the foreseeable future, or is it too early to commit to that?

I think that some from of being able to inspect hooks is pretty important functionality for DevTools to provide so that hooks are as good of a developer experience as props/state. There's still a chance I suppose that we _don't_ release that package though, and it stays embedded in the DevTools and released/versioned with React. I don't _think_ that's what will happen but this question hasn't been one of the most pressing ones recently.

@chenesan:
1. Doesn't sound like something we would want to do. I don't think I see the use case for why Enzyme would need to control hooks state rather than just read it.
2. No. It's DevTools only.

**Comment by ljharb** [comment]
A future-stable capability (the API can, of course, change across majors) for reading hook info would be a wonderful start.
