### ISSUE TITLE
rehydrating dangerouslySetInnerHtml on svg with hooks

### ISSUE THREAD

**Issue by wmertens** [facebook/react#15632]
**Do you want to request a *feature* or report a *bug*?**

bug

I have a svg symbol component that puts a bunch of svg symbols at the bottom or the page and refers to them with `<use/>`. It works fine in the previous incarnation which uses the old-style context API.

I rewrote it to use the new Context API and hooks, and now it doesn't hydrate properly.

**What is the current behavior?**

After SSR, the resulting HTML has working icons. After rehydration, the svg component with the symbols is empty. The symbols are provided to `dangerouslySetInnerHtml:{__html}` as a string with all symbols concatenated.

After re-rendering that symbols component, the innerHtml of the svg is correct again.

I don't have time to create a sandbox just now, please let me know if it will be necessary and I will create one.

Here's the relevant code for the provider and the `<Symbols />` component that manages the symbols:
```js
import React, {useState, useContext, useRef} from 'react'
import PropTypes from 'prop-types'

const IconContext = React.createContext()

export const Use = ({symbol}) => {
	if (!symbol) return false
	const ctx = useContext(IconContext)
	if (!ctx) return false

	ctx.addSymbol(symbol)

	return <use xlinkHref={'#' + symbol.id} />
}
Use.propTypes = {symbol: PropTypes.object.isRequired}

// Note: this has to stay a separate component so it gets evaluated at the end of the render
// that way the uses object will contain all the used symbols (through mutation)
const Symbols = () => {
	const context = useContext(IconContext)
	const [, refresh] = useState()

	const {uses, onAdd} = context
	if (!onAdd) context.onAdd = refresh

	return (
		<svg
			// eslint-disable-next-line react/no-danger
			dangerouslySetInnerHTML={{
				__html: Object.values(uses)
					.map(s => s.text)
					.join(''),
			}}
			style={{display: 'none'}}
			xmlns="http://www.w3.org/2000/svg"
			xmlnsXlink="http://www.w3.org/1999/xlink"
		/>
	)
}

const IconProvider = ({children}) => {
	const {current: context} = useRef({})
	if (!context.addSymbol) {
		// Initialize our context
		context.uses = {}
		// We don't remove symbols, it's extra work and the browser will be fine
		context.addSymbol = symbol => {
			const has = context.uses[symbol.id]
			if (has) {
				if (has === symbol) return

				// eslint-disable-next-line no-console
				console.error(
					new Error(`Symbol ID ${symbol.id} has to be unique (hot reload ok)`)
				)
			}
			context.uses[symbol.id] = symbol
			// This causes Symbols to rerender
			if (context.onAdd) context.onAdd(symbol)
		}
	}

	return (
		<IconContext.Provider value={context}>
			<>
				{children}
				<Symbols />
			</>
		</IconContext.Provider>
	)
}

IconProvider.propTypes = {children: PropTypes.any}

export default IconProvider
```

**What is the expected behavior?**

The rehydration should set the innerHtml.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React version is 16.8.6, and it works in the non-hooks version (you can see that in action on https://yaska.eu).

**Comment by wmertens** [comment]
And now I can't reproduce it any more 🤷‍♂

**Comment by ravikumarpitla** [comment]
Hi wmertens,
I am facing the same issue.
Could you please provide the information how this issue got fixed?

Thanks,
Ravi.

**Comment by wmertens** [comment]
@ravikumarpitla sorry I have no idea, I just tried to reproduce it and somehow it started working.
