### ISSUE TITLE
Document an unmentioned reason for hook errors.

### ISSUE THREAD

**Issue by bebbi** [facebook/react#15635]
This [page](https://reactjs.org/warnings/invalid-hook-call-warning.html) and #13991 document the `Hooks can only be called inside the body of a function component.` error.

I encountered the same error on a completely unrelated bug: I forgot to *call* the hook:

```
const MyComp = () => {
  const myVar = useHook  // missing the `()`
  return <Something />
}
```

While that's a silly omission, it's maybe worth documenting to make the error more concise. Feel free to close either way.

**Comment by threepointone** [comment]
React wouldn't be able to have a runtime error here since the hooks isn't actually called. you could make a lint rule, or better, use a type system like flow or typescript to detect this kind of error. (when you try to pass myVar to something not expecting a function, it would fail typechecking)
