### ISSUE TITLE
Memory leak with many components and user input

### ISSUE THREAD

**Issue by tariqporter** [facebook/react#15637]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When creating many elements with react, and providing some user action - scrolling in this example, the memory will continually increase and never be garbage collected

https://github.com/tariqporter/react-memory-leak

`git clone https://github.com/tariqporter/react-memory-leak`
`cd react-memory-leak`
`yarn start`

Click the `Start` button

![image](https://user-images.githubusercontent.com/8306435/57641618-71af7300-7583-11e9-83cd-cda0442981ba.png)

And start scrolling up and down the page (Will keep attempting to automate the scrolling with the bug persisting)

The memory will continually increase and never be garbage collected. Once the bug begins happening, the user no longer needs to scroll; the memory will keep increasing without any input. 2GB of memory used within a couple of minutes:

![image](https://user-images.githubusercontent.com/8306435/57641484-1c736180-7583-11e9-824a-810d105743ec.png)

This is part of a larger application that has meant it has become unusable with react 16x. It uses `react-virtualized`, and we also created our own table virtualization, but this memory leak happens with both of them, hence creating this issue.

**What is the expected behavior?**

I would expect garbage collection to happen at some point and look like the following (The following is the same example with no user input)

![image](https://user-images.githubusercontent.com/8306435/57642029-6f99e400-7584-11e9-930c-5566db954dc3.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This is tested in chrome `74.0.3729.131` and firefox `66.0.5` on react `16.8.6`. We believe it is for all react `16x`

**Comment by tlenex** [comment]
There is a patch #15157 that could help. Can you try it out @tariqporter ?

**Comment by tariqporter** [comment]
@tlenex Thank you for the work, but unfortunately we are still seeing the same issue with accumulating DOM nodes and progressive slowdown.

![image](https://user-images.githubusercontent.com/8306435/58490544-5a53b680-813b-11e9-84d7-b174a21aabb4.png)

**Comment by tariqporter** [comment]
https://github.com/facebook/react/pull/15157 This seems to resolve the issue we have in our application.

The production build still seems to be noticeably slower than development, but that is likely another issue.

**Comment by tariqporter** [comment]
Upgrading to v16.9 has resolved this issue!
