### ISSUE TITLE
React.lazy has problem in hot reload

### ISSUE THREAD

**Issue by mahyar33** [facebook/react#15648]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

I use React.lazy in routing but when I change my code and I'm in route A, hot reload doesn't work in other routes(route B, route C) and I have to refresh my page

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
   "react": "^16.8.6",
  "react-scripts": "2.1.8",
   os : windows

**Comment by threepointone** [comment]
please file this issue at https://github.com/facebook/create-react-app/issues
