### ISSUE TITLE
Not issue, just an idea on state management

### ISSUE THREAD

**Issue by raymondsze** [facebook/react#15642]
The feature of React Hooks is really awesome and I love it.
When React Context API comes into play, the whole state management is very strict forward.

I am trying "Next.js" and some ideas come to my head.

The Context API + Hooks combo must live in React Component lifecycle nowadays.
Sometimes, we may need simple state management living outside React.

The reason why I need it is I would like to manipulate the state in `getInitialProps` (Next.js specific) function.
If we need some state managements outside the React Component, we probably use Redux.

However, Redux is usually too "over-engineering" for small to medium size project.

I know the implementation of React Hooks is just a memoized linked-list, and it relies on global variables that React Component rendering binding to.

Just a thought, how about if we could write a store like what React Hook did, it would make consistent api.

For example:
```jsx
// We have functional component, similarly we could have functional store
function Counter(props) {
   const [counter, setCounter] = useState(props.counter || 0);
   return { counter, setCounter };
}

const store = createStore(Counter, { counter: 0 }); // like Redux.createStore
// store is an instance looks like redux store

// store.getState() ==> { counter: 0, setCounter: [Function] }
// getState() could be like what React.render did, so we could prepare and memoized the hooks value there, and call the functional store to get the return value, and clean-up.

// store.subscribe(listener) ==> unsubscribe

// Use the store
const App = ({ children }) => (
  <Provider store={store}>
     {children}
  </Provider>
);

// Manipulate the store state in functional component
// const { counter, setCounter } = useStore(store);
// setCounter(1);

// Manipulate the store state outside React
// const { counter, setCounter } = store.getState();
// setCounter(1);
```

This is not React issue, but just an idea comes to my mind when using Next.js.

**Comment by threepointone** [comment]
this is what custom hooks are for, and you could initialize it in a root level component and pass it to children, thus also satisfying the rules of hooks. 

we use the issue tracker for bugs and feature requests, so I'm closing this, but feel free to make your own library and helpers, hth
