### ISSUE TITLE
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern but can be moved to `componentWillMount`.

### ISSUE THREAD

**Issue by BikalNepal** [facebook/react#15656]
I have a react component which is basically a form that submits a company's data. Everything is okay till I fill the form but when I submit the form and it goes to the next page it shows the following error:

````
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern but can be moved to `componentWillMount`.
````
I tried looking for answers in other questions and GitHub but to no avail. My entire code for that component is here:

https://gist.github.com/BikalNepal/b0185dee1528e396ff3a91a4f0caf9bd

I'm aware that this can happen because of setState being an async function so I tried putting await in front of setStates but that doesn't work either, instead throws some other errors. Any help would be appreciated. Thank You!

I'm using React 15.6.1
OS: Ubuntu 18.04.1 LTS
and Chrome v. 70

**Comment by hahabazinga** [comment]
`this.setState` doesn't return a promise, so putting await in front of `setState` does not work. So use the callback instead.
Besides,  wrapping `setState` inside `Promise` maybe another solution,  see [detail](https://medium.com/front-end-weekly/async-await-with-react-lifecycle-methods-802e7760d802)
```
setStateAsync(state) {
    return new Promise((resolve) => {
      this.setState(state, resolve)
    });
}
```

**Comment by BikalNepal** [comment]
Hello, thank you so much for the reply, there are a lot of setStates in my
code. Can you please specify in which one I have to use the Promise or
callback? Thank you!

**Comment by hahabazinga** [comment]
@BikalNepal when you need to use the updated state based on previous `setState(...)`, you should operate the updated state in the previous setState callback. Or wrap it with Promise and then use async -await

**Comment by omriLugasi** [comment]
Hi @BikalNepal 
As you can see the message print because you trying to using setState in your `render` function, or in function that invoked from your `render` function

for example this snippet will trigger the same error

```javascript

import React from 'react'


let renderedState = -1;
let renderPasses = 0;

class Component extends React.Component {
  state = {value: 0};

  constructor() {
    renderPasses++;
    renderedState = this.state.value;
  }

  render() {
    if (this.state.value === 0) {
      this.setState({value: 1});
    }
    return <div />;
  }
}

export default Component
```


If you want to dive dipper to the solution of this issue ( in your project) you can see the test that check this error in the snippet below:
 https://github.com/facebook/react/blob/31487dd82e82ef62243806b2e76b23a6fb21d0bc/packages/react-dom/src/__tests__/ReactCompositeComponent-test.js#L452-L479
 
Hope I help :), 
@nhunzaker 
@gaearon 

Any more thoughts about this or we can close it?

**Comment by threepointone** [comment]
Yeah this seems like a usage issue, closing. Thanks all for the assist.
