### ISSUE TITLE
Showcasing a proof of a concept using react

### ISSUE THREAD

**Issue by imvetri** [facebook/react#15653]
Hey team, I tried a UI layer on top of react framework to use it as a code generator.  Project repo is here https://github.com/imvetri/ui-editor.

Let me know what you think.

I am sorry if this is a wrong place to start non-bugs conversation here. Feel free to suggest right place to have this discussion going on.

Thanks,
Vetrivel.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question or want to find a place to share your work, please check our community support resources:
https://facebook.github.io/react/community/support.html
