### ISSUE TITLE
Valid use of hooks in HOC doesn't pass lint

### ISSUE THREAD

**Issue by micburks** [facebook/react#15667]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Erroneous lint error thrown when using hooks inside an HOC

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Reproduction:
[Newly scaffolded react app](https://github.com/micburks/hooks-in-hoc)
[Component in question](https://github.com/micburks/hooks-in-hoc/blob/master/src/App.js#L13-L20)

**What is the expected behavior?**
No error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
[react 16.8.6](https://github.com/micburks/hooks-in-hoc/blob/master/yarn.lock#L8316-L8317)
[eslint-plugin-react-hooks 1.6.0](https://github.com/micburks/hooks-in-hoc/blob/master/yarn.lock#L3869-L3870)

I was looking for a simple way to migrate the logic in some existing HOCs without breaking their usage. Turns out this pattern works fine, but is failed by the eslint plugin.

**Comment by threepointone** [comment]
rename `withStateHOC` as `WithStateHOC` and it'll pass (the lint rule detects components as those with a capitalized first letter)

closing this issue.

**Comment by micburks** [comment]
Oof. I didn't even notice I did that. Thanks!
