### ISSUE TITLE
Hooks useEffect --- How to turn off the timer

### ISSUE THREAD

**Issue by Hgq1001** [facebook/react#15669]
How to turn off the timer ? 

export default function Clock() {
  const [currentTime, setCurrentTime] = useState(utils.getTime());
  const [isPause, setPause] = useState(false);
  const [timer, setTimer] = useState(null);

  useEffect(() => {
    if (isPause) return () => clearInterval(timer);
    const id = setInterval(() => {
      setCurrentTime(utils.getTime());
    }, 1000);
    setTimer(id);
  });

  const pause = () => {
    setPause(!isPause);
  };

  return (
    <div>
      {currentTime}
      <p>Status--{isPause ? '暂停' : '启动'}</p>
      <button onClick={() => pause()}>暂停</button>
    </div>
  );
};

**Comment by Hgq1001** [comment]
初始化的时候有一个时钟的定时器，怎么手动点击暂停按钮 然后时间不继续走。。清除掉定时器

**Comment by hahabazinga** [comment]
try this
```
useEffect(() => {
  if (isPause){
    clearInterval(timer);
  } else {
    const id = setInterval(() => {
      setCurrentTime(utils.getTime());
    }, 1000);
    setTimer(id);
  }
  return () => clearInterval(timer);
}, [pause]);
```

**Comment by Hgq1001** [comment]
@hahabazinga thank you  i try it  and  use  useRef , it's ok!   But  how to use  useEffect second argument ? what does it means?

**Comment by hahabazinga** [comment]
According to the official [blog](https://reactjs.org/docs/hooks-effect.html), you can tell React to skip applying an effect if certain values haven’t changed between re-renders. To do so, pass an array as an optional second argument to useEffect:
```
const [count, setCount] = useState(0);
useEffect(() => {
  document.title = `You clicked ${count} times`;
}, [count]); // Only re-run the effect if count changes
```

**Comment by Hgq1001** [comment]
@hahabazinga  hey guy ! your English is very well！ Explained very well ！！

**Comment by threepointone** [comment]
I would also recommend reading dan's very comprehensive post on useEffect https://overreacted.io/a-complete-guide-to-useeffect/
