### ISSUE TITLE
exhaustive-deps: Require specifying dependencies

### ISSUE THREAD

**Issue by hornta** [facebook/react#15660]
Originally posted this here: https://github.com/yannickcr/eslint-plugin-react/issues/2277

Consider adding a boolean option **requireDeps**, which if true disallows not specifying deps in **useEffect, useMemo, useCallback and useLayoutEffect**. Default value should be **false** .

I believe it's for the better to always specify dependencies in hooks because of unnecessary side-effects when props or state changes unexpectedly. 

### Option: requireDeps: true
Example of **incorrect** code
```javascript
/* eslint react-hooks/exhaustive-deps: ["error", { requireDeps: true }] */
function MyComp(props) {
  useEffect(() => { ... });
  ...
}
```

Examples of **correct** code
```javascript
/* eslint react-hooks/exhaustive-deps: ["error", { requireDeps: true }] */
function MyComp(props) {
  useEffect(() => { ... }, []);
  ...
}
```

```javascript
/* eslint react-hooks/exhaustive-deps: ["error", { requireDeps: true }] */
function MyComp(props) {
  useEffect(() => { ... props.foo; ... }, [ props.foo ]);
  ...
}
```

### Option: requireDeps: false
Examples of **correct** code
```javascript
/* eslint react-hooks/exhaustive-deps: ["error", { requireDeps: false }] */
function MyComp(props) {
  useEffect(() => { ... });
  ...
}
```

**Comment by threepointone** [comment]
I don't agree that dependencies should always be specified, there are legitimate use cases for running code on every render (and in a lot of cases is cheap enough to do - like subscriptions). Thanks for the suggestion, but I don't think it's something we'll do in eslint-plugin-react-hooks. that said, there's nothing stopping someone from making a separate plugin that does enforce this, and use together with eslint-plugin-react-hooks.
