### ISSUE TITLE
Expect mixed case props not to throw development warnings if they evaluate to `undefined`

### ISSUE THREAD

**Issue by pixelbandito** [facebook/react#15663]
**Bug report**

**What is the current behavior?**

When running in development mode, basic DOM elements report (correctly) when they see mixed case props, which aren't supported.

If a component puts a mixed-case prop with a value of `undefined` on a DOM element, it still throws a warning. (But `undefined` values don't seem to be passed, generally).

  ```js
const GoodComponent = () => <div hullaBallo={undefined}>Should not warn</div>;
```
...produces...

> Warning: React does not recognize the `hullaBalloo` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hullaballoo` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Demo: https://codepen.io/pixelbandito/pen/mYWWby?editors=1111

**What is the expected behavior?**
1. If a component puts a mixed-case prop with a value of `undefined` on a DOM element, it doesn't throw a warning.` values don't seem to be passed down anyway).
  ```js
const GoodComponent = () => <div hullaBallo={undefined}>Should not warn</div>;
```
2. If a component puts a mixed-case prop with a value on a DOM element, throw a warning.
  ```js
const BadComponent = () => <div hullaBallo="foo"}>Should warn</div>;
```

The expected behavior would help me write terse wrappers that pass props down to their children. In my actual use case, I have a `inNewTab` prop that uses [prop-types](https://www.npmjs.com/package/prop-types) to set a default of undefined. I'd like to pass props down to children in most cases without worrying about whether the `children` prop will be a component or a bare DOM element.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I tested with React 16.8.6, because that was the current version listed in npm

**Comment by threepointone** [comment]
The warning exists to detect the _intent_ of what's being passed to the dom element. We want to prevent situations where devs might be sending bad props to the element. Imagine if someone changed that code to pass a value, but it was always undefined in dev, but triggered in prod, for example. That could subtly break behaviour now, or in the future.

Destructuring makes this a bit nicer to write.
```jsx
const {inNewTab, ...rest} = props
return <div {...rest}> ...
```
Closing this issue, thanks for your question!
