### ISSUE TITLE
Passing deconstructed useRef ({current}) as param to hook breaks after first usage of hook

### ISSUE THREAD

**Issue by stevensacks** [facebook/react#15674]
**Do you want to request a *feature* or report a *bug*?**
This is a bug!

**What is the current behavior?**
If you have a custom hook that has useEffect, which takes a ref as its parameter, and you deconstruct that parameter to get current, it breaks on subsequent usages of the hook.

Here's an example of the code that caused this;

```javascript
export default ({current}) => {
    const [rect, setRect] = useState({});
    useEffect(() => {
        const onResize = () => {
            setRect(current.getBoundingClientRect());
        };
        if (current) {
            setRect(current.getBoundingClientRect());
            window.addEventListener('resize', onResize);
        }
        return () => window.removeEventListener('resize', onResize);
    }, [current]);
    return rect;
};
```

The first component that uses this hook works just fine. Every other component, current either stays null, or never returns the rect until you resize. It's a very odd bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/rough-leftpad-bgpl6

Specifically, look at `hooks/useComponentRect.js`.

SmartScroll uses it, and then so do all the SmartScrollRow components, but all the rows never update their rect until you resize. On code sandbox, I at least get a value for current, but in my CRA development environment on my local box, the ref stays null forever, even on resize.

**What is the expected behavior?**
I mean, in an ideal world, deconstructing should work. The solution is to deconstruct current inside of useEffect instead, like this.

```javascript
export default ref => {
    const [rect, setRect] = useState({});
    useEffect(() => {
        const {current} = ref; // <-----------
        const onResize = () => {
            setRect(current.getBoundingClientRect());
        };
        if (current) {
            setRect(current.getBoundingClientRect());
            window.addEventListener('resize', onResize);
        }
        return () => window.removeEventListener('resize', onResize);
    }, [ref]);
    return rect;
};
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I'm in Chrome but it happened to multiple people who were trying to help me figure out what was going wrong.

This is a very specific bug and there is a way to avoid it and that should probably be put into the docs.

**Comment by malerba118** [comment]
I don't think this is a bug as much as it is just a caveat of async execution in javascript. The callback provided to useEffect is not invoked at the same time that the custom hook is invoked. By destructuring ref you're dereferencing the current value and taking a snapshot of it at that point in time. By destructuring the ref at the time of the execution of the custom hook, the value of current is already stale by the time the useEffect callback is invoked. Whereas if you destructure the ref inside of the useEffect callback, you will not have a stale value. I think this [sandbox](https://codesandbox.io/s/stale-callback-values-q18wy) shows a simplified manner in which you might encounter stale values in callbacks.

**Comment by parabolabam** [comment]
> I don't think this is a bug as much as it is just a caveat of async execution in javascript. The callback provided to useEffect is not invoked at the same time that the custom hook is invoked. By destructuring ref you're dereferencing the current value and taking a snapshot of it at that point in time. By destructuring the ref at the time of the execution of the custom hook, the value of current is already stale by the time the useEffect callback is invoked. Whereas if you destructure the ref inside of the useEffect callback, you will not have a stale value. I think this [sandbox](https://codesandbox.io/s/stale-callback-values-q18wy) shows a simplified manner in which you might encounter stale values in callbacks.

12

**Comment by malerba118** [comment]
There is a valid concern here. It kind of stinks that the consumer can break `useRef` in the first place by assigning ref.current to a variable. Though this is simply how javascript works, I think it could be nice if refs returned a getter and setter to make it harder for the consumer to break the ref.

```jsx
function useAlternateRef(defaultVal) {
  const ref = useRef(defaultVal)
  const api = useMemo(() => ({
    get: () => ref.current,
    set: (val) => ref.current = val
  }), [])
  return api
}

function useHarderToBreakLogger(data) {
  const dataRef = useAlternateRef(data)

  useEffect(() => {
    dataRef.set(data)
  }, [data])

  useEffect(() => {
    const id = setInterval(() => {
      console.log('HarderToBreakLogger:', dataRef.get())
    }, 3000)
    return () => clearInterval(id)
  }, [])
}
```

https://codesandbox.io/s/reactissues15674-qd2ds

**Comment by necolas** [comment]
As you mentioned, this is expected because the current value is being assigned to a variable outside the useEffect closure. Read it from within the effect to get the latest value
