### ISSUE TITLE
Memory leak >=16.6.1

### ISSUE THREAD

**Issue by sjuchno** [facebook/react#15670]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
Input fields once clicked leak memory when they are a part of a list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Go to https://codepen.io/anon/pen/byqZKd
2. Click on one of the input fields in one of the sections.
3. Click "next" couple of times.
4. Go to dev tools, make a memory snapshot and search for "MyHeader" - there will be way too many of them.

If you don't click on any input fields, in any of the sections, then there will be no leak.

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React >=16.6.1

**Comment by davidstelter** [comment]
This seems related to an issue that's been plaguing me. I've played with the codepen example here a bit, interestingly one can get most of the "MyHeader" objects to be freed if you click on the input again and hit next a few times, but keep hitting next and they leak more. Also just doing a focus on one of the inputs works, just use the Tab key to focus it without a mouse click and same behavior can be observed.

@sjuchno I'd suggest trying the patch in this PR: https://github.com/facebook/react/pull/15157
I downloaded your code from codepen, and when I switch to the react and react-dom builds from the above PR, the issue with MyHeader piling up in heap snapshots seems to disappear. Doing same combination of actions using your codepen with the CDN-served react 16.8.6 I see 206 MyHeader in Chrome 74 heap snapshot, using custom build from PR, same actions get me 19 MyHeader in heap snapshot. Doing one click in first input, then clicking "next" 50 times.
