### ISSUE TITLE
Invalid hook call. error when using useState in HOC

### ISSUE THREAD

**Issue by matmalkowski** [facebook/react#15673]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

Trying to use state with `useState` hook inside a Higher Order Component results in runtime error:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```ts
const withWrapper = <T extends object>(
  Component: React.ComponentType<Props<T>>
) => {
  const Wrapper: React.FC<Props<AnyIfEmpty<T>>> = props => {
    const [theme, setTheme] = React.useState(props.theme);

    return <Component theme={theme}>{props.children}</Component>;
  };

  Wrapper.displayName = `withWrapper(${Component.displayName})`;

  return Wrapper;
};

export default withWrapper ;
```

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```json
"react": "^16.8.6",
```

**Comment by aweary** [comment]
@matmalkowski can you please share a full example that reproduces the error? We can't help debug this if we can't reproduce the error for ourselves.

Also have you tried checking the potential problems that the error lists?

**Comment by hahabazinga** [comment]
you can only use `useState` in the top level in a function component, however `useState` is called inside `Wrapper` which is already inside `withWrapper` in your code

**Comment by matmalkowski** [comment]
@aweary Hey, sorry for lack of details. Did some mere debugging and its related to `link` usage rather than a HOC itself, so issue can be closed, sorry for that.

@hahabazinga In my example the top level is not a component - its a function that returns component.
