### ISSUE TITLE
Create HostConfig handler for commitUnmount in react-reconciler

### ISSUE THREAD

**Issue by tquetano-netflix** [facebook/react#15675]
**Do you want to request a *feature* or report a *bug*?**
I would like to request a new feature.

**What is the current behavior?**
At the moment there is no way to gain access to the fiber that is unmounting outside of the `onCommitFiberUnmount` hook in React DevTools. Would it be possible to create a new handler that you can pass in your host config that would tap into unmount commits?

```javascript
commitUnmount(node, internalInstanceHandler) {
  // can be a noop by default
}
```

This could be added [where the hook handler is already being called](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberCommitWork.js#L739).

Please let me know if you would consider this. :smile_cat:

**Comment by gaearon** [comment]
What is the use case?

**Comment by tquetano-netflix** [comment]
We are attempting to object pool `ReactElement` objects, and with the existing host config methods + a custom pragma we get mostly there with mapping via `stateNode`. Adding `commitUnmount` with access to the fiber's `stateNode` would allow us to close the loop and release the objects back to the pool.
