### ISSUE TITLE
 event.key is  "↵" instead of "Enter" 

### ISSUE THREAD

**Issue by titoBouzout** [facebook/react#15689]
event.key  is "Enter" when I press Enter on a textarea with an onKeyPress event
but if I hold CTRL then event.key become "↵" ...

**Comment by titoBouzout** [comment]
it seems event.key == '\n' and for some reason is displayed as ↵ in the developer console.

**Comment by nattthebear** [comment]
React isn't doing anything special here, that's just what Chrome does https://jsfiddle.net/k4gcLtrf/
This doesn't happen on Firefox, so maybe it's somebody's bug, but not React's.

**Comment by titoBouzout** [comment]
I see thank you. Maybe is a Firefox bug https://bugs.chromium.org/p/chromium/issues/detail?id=79407&q=ctrl%20enter%20keypress&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
