### ISSUE TITLE
Can we simplify type annotation in line 364?

### ISSUE THREAD

**Issue by djy0** [facebook/react#15680]
https://github.com/facebook/react/blob/31487dd82e82ef62243806b2e76b23a6fb21d0bc/packages/react-reconciler/src/ReactFiberHooks.js#L362-L365

babel outputs same code for  above and
```
 hookTypesDev = 
   current !== null 
     ? (current._debugHookTypes: Array<HookType>)
     : null; 
```

**Comment by threepointone** [comment]
we do that to cast the (possibly null) value into something we can operate on. what exactly is the benefit of your change?

closing this issue since it isn't a bug or feature request, but lemme know if I'm wrong .
