### ISSUE TITLE
TypeError: fsevents is not a constructor

### ISSUE THREAD

**Issue by LianFengZhiDie** [facebook/react#15684]
** When I run *npm start* in a Mac environment, there was an Error：**

**my-app/node_modules/chokidar/lib/fsevents-handler.js:28**

**return (new fsevents(path)).on('fsevent', callback).start();**

**TypeError: fsevents is not a constructor**

**After I commented out this line of code, the program ran. **

**Comment by gaearon** [comment]
You probably meant to file this in https://github.com/facebook/create-react-app.
