### ISSUE TITLE
Default value prop is reset all the time

### ISSUE THREAD

**Issue by alicerocheman** [facebook/react#15683]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
I have a prop in my component that has a default value.
The prop seems to change at every render.
To test this, I created this example [on codesandbox.io](https://codesandbox.io/s/nostalgic-booth-fbewe), and clicked on the button. Everytime I click, margins is updated.
````tsx
import { useWhyDidYouRender } from "hooks";
import React, { useState } from "react";

const MySubComponent = ({
    width,
    margins = { top: 1, bottom: 2 },
}: {
    width: number;
    margins?: { top: number; bottom: number };
}) => {
    const [counter, setCounter] = useState(0);
    useWhyDidYouRender("MySubComponent", { width, margins, counter });
    return (
        <div>
            marginTop: {margins.top}
            marginBottom: {margins.bottom}
            <button onClick={() => setCounter(c => c + 1)} >click me</button>
        </div>
    );
};

const MyComponent = () => {
    return (
        <div>
            <MySubComponent width={5} />
        </div>
    );
};

export default MyComponent;
````

console: 
````console
[why-did-you-render] MySubComponent {margins: {…}}
  margins: 
    from: {top: 1, bottom: 2}
    to: {top: 1, bottom: 2}
useWhyDidYouRender.ts:44 [why-did-you-render] MySubComponent {margins: {…}}
useWhyDidYouRender.ts:44 [why-did-you-render] MySubComponent {margins: {…}}
````

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/nostalgic-booth-fbewe

**What is the expected behavior?**
prop with default value should not be reset at every unrelated change

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.8.4
OS: Windows 10
browser: Chrome

**Comment by threepointone** [comment]
This is just how javascript works? Everytime `MySubComponent` is called, it notices that margins is undefined, so generates a new object `{ top: 1, bottom: 2 }`. If you do want to preserve the identity of the margins object, you could either hoist it like so 
```jsx
const margins = { top: 1, bottom: 2 };
const MySubComponent = ({
    width,
    margins = defaultMargins,
}: {
    width: number;
    margins?: { top: number; bottom: number };
}) => {
// ...
```
or you could use `useMemo` to memoize based on the values 
```jsx
const MySubComponent = ({
    width,
    margins = { top: 1, bottom: 2 },
}: {
    width: number;
    margins?: { top: number; bottom: number };
}) => {
    const [counter, setCounter] = useState(0);
    const myMargins = useMemo(() => margins, [margins.top, margins.bottom]
    // this won't rerender now 
    useWhyDidYouRender("MySubComponent", { width, margins: myMargins, counter });
    return (
        <div>
            marginTop: {margins.top}
            marginBottom: {margins.bottom}
            <button onClick={() => setCounter(c => c + 1)} >click me</button>
        </div>
    );
};
```

this isn't a bug or feature request, so am closing it.

**Comment by alicerocheman** [comment]
Thank you
