### ISSUE TITLE
dangerouslyReplaceNodeWithMarkupByID uses getNode on an unmounted/purged ID

### ISSUE THREAD

**Issue by syranide** [facebook/react#1569]
https://github.com/facebook/react/blob/master/src/browser/ui/ReactDOMIDOperations.js#L165

Calls `getNode` on an ID which is unmounted and purged.

https://github.com/facebook/react/blob/master/src/core/ReactCompositeComponent.js#L1134

@sebmarkbage: @spicyj indicated that you are working on a refactor, perhaps you've already fixed this? (PS. I'm not really sure how to fix this without taking out the big hammer)

**Comment by hejld** [comment]
This seems to be already fixed. The `dangerouslyReplaceNodeWithMarkupByID` no longer exist in current codebase (this was the original implementation: https://github.com/syranide/react/blob/520d73d73cbd46d8d1094b920b38604e31e77a5c/src/browser/ui/ReactDOMIDOperations.js#L161)

Instead `dangerouslyReplaceNodeWithMarkup` is being exposed directly on `ReactComponentBrowserEnvironment`, see https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactComponentBrowserEnvironment.js#L29

**Comment by spicyj** [comment]
Yeah, I rewrote all of this.
