### ISSUE TITLE
Properly using suspense and refs

### ISSUE THREAD

**Issue by natew** [facebook/react#15690]
**Do you want to request a *feature* or report a *bug*?**

More of a docs clarification request, and to provide a google page for anyone else with the same issue.

**What is the current behavior?**

I'm unclear on how Suspense and ref passing should work when a parent component passes down and then expects a ref to be set, and the child has a Suspense-style thrown promise, which prevents it from setting the ref in the parent.

Here's the relevant sandbox: https://codesandbox.io/s/8yvtz

I'm very curious the "right" way to do this and how to avoid having this inconsistency when in concurrent mode.

**What is the expected behavior?**

Ideally, not to have a different pattern for a pausable tree vs a normal one.

**Comment by eps1lon** [comment]
Having worked with refs extensively in the last months I came to the conclusion that any time you do 

```js
React.useEffect(() => {
  doSomethingWith(ref.current)
}, [doSomethingWith]);

return <div ref={ref} />;
```

you should should use callback refs instead
```js
const ref = React.useCallback(instance => {
  if (instance !== null) {
    doSomethingWith(instance);
  }
}, [doSomethingWith]);

return <div ref={ref} />;
```

i.e. if you want to read from a ref to a host component on mount what you actually want most of the time is to read when it is available. The difference usually doesn't matter but can be quite challenging once you pass refs across Suspense boundaries. The second approach also has the benefit that it works when the underlying host instance changes. The downside is that the ref phase is synchronous I believe. It might be better to put the instance into state and react to the state change in an effect. 

```js
const [instance, setInstance] = React.useState(null);
React.useEffect(() => {
  if (instance !== null) {
    doSomethingWith(instance);
  }
}, [instance]);

return <div ref={setInstance} />;
```

**Comment by gaearon** [comment]
Yep, this problem isn't really related to Suspense, and would happen with any component that renders its children conditionally. Indeed, you should be using a callback ref for those cases instead.

**Comment by natew** [comment]
It feels a bit odd that you’d change the ref interface entirely based on what a child component does internally, does it not?

In my case there are many hooks you can compose around ref objects, I’m not sure how you’d make them composable with callback. It’s easy to “pass down” a ref object, and each step of the chain can use it. Meanwhile with a callback you’d need every step to wrap the callback, instantiate a new ref, and process it. Am I right?

**Comment by natew** [comment]
Will play with callbacks a bit, thank you both for the replies.
