### ISSUE TITLE
[ESLINT] Propagate fixed identity function to custom hook

### ISSUE THREAD

**Issue by ekaradon** [facebook/react#15705]
**Do you want to request a *feature* or report a *bug*?**

A feature I suppose but I think of it as a bug.

**What is the current behavior?**

When I am creating a custom hook using `useReducer` internally, I lost the immutable trait on the `dispatch` function according to hook lint rules:
https://codesandbox.io/s/funny-mcnulty-db9zp

**What is the expected behavior?**

Well, I would like very much to see my custom hooks propagate these traits and not losing them. I know that it doesn't hurt to include constants in dependencies, but I very much prefer brevity and clarity on what trigger my `useEffect` reload.

**Comment by eps1lon** [comment]
The problem is that in the future your `useSomething` might return something that doesn't preserve identity. It's apparent now but declaration and usage might move further apart and this won't be apparent anymore.

It would also help if you would include a concrete use case. I suspect you gain more by sharing the reducer instead of the full hook.

**Comment by ekaradon** [comment]
It may change, but then the plugin should detect it and then flag it correctly as a function required in dependency, not otherwise. I really think that the issue there is not the intention but the lack of inference. 
I have many use cases in head but I don't think this is relevant to the discussion. 
What I want is being able to write custom hook of quality, and being able to ascertain some properties like the preserved identity function. And the fact that the plugin is not able to follow the ins and outs of override hook is really IMO a pain in the ass.

For the sake of the argument, I can join you an example:
https://codesandbox.io/s/sad-black-63dyf
However I think that this would be missing the whole point which is that today we cannot produce some high quality hooks over the standard API because we cannot produce the same kind of guarantee over them, and that bother me. :confused:
