### ISSUE TITLE
React.memo doesn't work as expected in nextjs apps if Provider value changed

### ISSUE THREAD

**Issue by istarkov** [facebook/react#15719]
**bug**

**What is the current behavior?**

I can't reproduce this issue out of nextjs app, but see the code of index page  https://codesandbox.io/s/helloworld-i8wzm

```javascript
import * as React from "react";
import Link from "next/link";

const Context = React.createContext({});
const TmpProvider = Context.Provider;

const MemoChild = () => {
  const r = React.useContext(Context);
  // commenting line above make memo to work as expected, it never render on click
  return null;
};

const Memo = React.memo(
  () => {
    console.info("memo render");
    return <MemoChild />;
  },
  // NEVER UPDATE
  () => true
);

const Test = () => {
  console.info("test render");
  return (
    <TmpProvider value={{}}>
      <Link href={{ pathname: "/" }}>
        <a>click me to force rerender</a>
      </Link>
      <Memo />
    </TmpProvider>
  );
};

export default Test;

```

On every link click log contains both console.info output

```
test render
memo render
```

But if I comment out this line `  const r = React.useContext(Context);`  at MemoChild
log contains just `test render` on link click as expected.

**What is the expected behavior?**

`React.useContext(Context);` in the child of memoized component must not somehow affect code execution, and the only console output on link click must be
```
test render
```

**Comment by kunukn** [comment]
I am uncertain whether the behaviour is a bug or not. However I believe there is a way around the issue.

` <TmpProvider value={{}}>`

This would trigger re-render for all consumers because `{}` is new on every execution. I believe this is considered an anti-pattern and something that should be avoided.

You could apply something like this.

```jsx 
  console.info("test render");
  const [state, setState] = React.useState({initialState: true});
  return (
    <TmpProvider value={state}>
   ...
```

**Comment by gaearon** [comment]
Is this reproducible with latest React? It would really help to get a repro case without Next too.

**Comment by istarkov** [comment]
Thanks for the response, I can't reproduce it with latest React, thank you!!!
