### ISSUE TITLE
Feature Request: Reset all Event Listeners

### ISSUE THREAD

**Issue by phibsi** [facebook/react#15721]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
React remembers, what React is listening for on each element, so event listeners are added only once.
See ReactBrowserEventEmitter getListeningForDocument (v16.8.6).

**What is the expected behavior?**
Nice would be a method to reset this memory.
I am using React in Microsoft SharePoint. There is a feature called "Minimal Download Strategy" (https://docs.microsoft.com/en-us/sharepoint/dev/general-development/minimal-download-strategy-overview). This feature overrides the document.addEventListener method and remembers all listeners. When the user navigates to another site, alle listeners will be removed. React don't know about the missing events, so all user inputs don't work anymore.
With the new method React should add all event listeners again.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Version: 16.8.6
Browsers: all
OS: all

**Comment by kunukn** [comment]
>This feature overrides the document.addEventListener 

That sounds scary. How is this strategy supposed to work well with any 3rd party JS library?

Have you tried running `ReactDOM.render` again or `ReactDOM.hydrate` ?
What happens?

**Comment by phibsi** [comment]
Hi,

I think there is no strategy to work with 3rd party js libraries. We used JS without any 3rd party library for a long time. Now we want to use React.

Yes, I tried `ReactDOM.render`. It renders the UI an everything works except of UI Events (like mouse click or input changes).
I saw in the ReactBrowserEventEmitter that a event listener will be created only once per window.

In this screenshot you can see the monkey patched method:
![image](https://user-images.githubusercontent.com/23647162/59271221-a7fc1300-8c53-11e9-84e3-091676de9ff5.png)

The Google Chrome console should return `addEventListener() { [native code] }`.

The function `SPAddEventListener(d,c,b)` saves the event listener to an array and when the user navigates, the SharePoint Code calls `removeEventListener` for each saved event listener.

So we need a method to force React to recreate the event listeners.
My workaroud for React 16.8.6 is to delete the global variable `document._reactListenersIDXXXXX`.

**Comment by phibsi** [comment]
Does somebody has any idea?

**Comment by dennisbappert** [comment]
We're facing similar issues, is there any progress here?

**Comment by threepointone** [comment]
I'm not sure what React could do here, this seems like something SharePoint should be fixing? SharePoint is behaving badly here by messing with registered listeners, and it would be odd for React to add functionality to workaround it.

**Comment by threepointone** [comment]
I’m going to close this issue since I don’t believe React should do anything here. Happy to discuss if there’s more information, but I think Microsoft should be fixing this, and you should probably reach out to them for guidance.
