### ISSUE TITLE
[ESLint] Propose rules: `prefer-useCallback`, `guard-memo`?!

### ISSUE THREAD

**Issue by leoyli** [facebook/react#15728]
**Do you want to request a *feature* or report a *bug*?**
Features.

**What is the current behavior?**
No these rules.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
N/A

**What is the expected behavior?**
Give linting warning.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
\> 16.8

---

From my experiences with hooks so far, it seems that in any function component, `const` assignment would always associate with one hook for sure. (correct me if I were wrong...)

Anyway, I think we can have a new `prefer-useCallback` rule, which gives warning whenever `const fn = () => {...}` does not wrapped with `useCallback`.  Even it does not pass with `React.memo` component, the memorization punishment can still be paid back after couple re-rendering process, and it would always ready if we later found we need to wrap some of components with `React.memo`.

Also, it almost 100% wrong when such a function pass into a `React.memo` wrapped component, which may not be obvious. Maybe we can have a lint rule to catch up this too (`guard-memo`)? Does it possible?

PS. naming on rules is randomly running into my mind. Maybe someone have a better name in mind?

**Comment by nmain** [comment]
> Also, it almost 100% wrong when such a function pass into a React.memo wrapped component, which may not be obvious. Maybe we can have a lint rule to catch up this too (guard-memo)? Does it possible?

The linting rules already do this.  If you have this:
```js
	function foo() {

	}
	const bar = React.useMemo(() => foo(), [foo]);
```

You get this:
```
The 'foo' function makes the dependencies of useMemo Hook (at line 27) change on every render. Move it inside the useMemo callback. Alternatively, wrap the 'foo' definition into its own useCallback() Hook
```

**Comment by leoyli** [comment]
@nmain,

I'm talking about `React.memo` rather than `React.useMemo`. This, by far, I don't see any linting errors. Consider this:

```js
const Child = React.memo(({ cb }) => cb());

const Parent = () => {
  function fn() {
    return null;
  }

  return <Child cb={fn} />;  // a callback is passing down to a memorized child
};
```

For the `guard-memo` rule, the difficultly I see here is it may not easy to track down along the rendering tree, but I think at minimum, we should able to write a rule from the AST generated by the code above if that happened immediately.

On the other hand, `prefer-useCallback` enforce any function declaration/expression within a component must be wrapped inside `useCallback`, which seems become the new idiomatic standard. As far as I know, it add no harm to do this all the time. Than `guard-memo` may be redundant since it logically covered by `prefer-useCallback` rule.

**Comment by gaearon** [comment]
I wouldn't say _always_ using `useCallback` is idiomatic. Quite the opposite, it hurts startup time and memory (a tiny bit, but still) but doesn't always give you anything. Same goes for overuse of `memo`.

**Comment by nmain** [comment]
> I'm talking about `React.memo` rather than `React.useMemo`.

Yes, of course.  I read one thing and saw another.

This one seems harder to lint effectively:  the `memo` call and the instantiation of the component could be in separate files, so the linter would have to track that.  Also would be nice to track when a `PureComponent` consumes your function in the same way.  You can also run into the same problem with a non-memo component that takes a function it expects to be stable:

```js
function MyComponent({ dataSource }) {
  var [s, cs] = useState();
  // whenever dataSource changes, call the new one and then do some stuff?
  // could be bad if dataSource runs a fetch()
  useEffect(() => dataSource().then(result => cs(result)), [dataSource]);
}

**Comment by leoyli** [comment]
@nmain, yeah, I totally forget about `PureComponent`... and I agree this could be non-trivial.

---

@gaearon, yes, we do pay something for `useCallback` for memorization, but the reason why not bail in `memo` as idiomatic default is quite different here. At least defensively use `useCallback` seems won't give any sort of bug (but `memo` could be)?

If the startup time is almost negligible then perhaps it is fine to be idiomatic default? I see we pay a small cost on memorize callback function, but later we save performance for V8 to do garbage collection. Or where is the sweet spot...? And I'd to see the linter can be smart enough to tell me I might want `useCallback` here or I don't need it there.

**Comment by benwiley4000** [comment]
@gaearon I think in retrospect the prefer-usecallback rule should be considered as optional. It might make a trivial difference for performance, which isn't at all why I want it. Rather, the amount of behavior bugs resulting from *forgetting* to use useCallback makes me want this rule, so I can stop having to waste so much time in PRs explaining all the different components that need to update to useCallback so we can just pass a function into a useEffect.

**Comment by vkruglikov** [comment]
@leoyli 

For case. where you think is it necessarily, you can use custom type in typescript.
For this  I published this repo https://github.com/vkruglikov/rely-use-callback

There is custom `useCallback`, who returns special type for callback .

You can read more about [motivation](https://github.com/vkruglikov/rely-use-callback#-motivation)  about problem

For example, you can use `RelyCallback` type in your `memo` component
```typescript jsx
import {RelyCallback, useCallback} from 'rely-use-callback'

// Create handle with custom useCallback 
const handleClick = useCallback(() => {}, []);

const MemoizedComponent: FC<{
    onClick: RelyCallback<() => void>,
    onShow: () => void
}> = memo(({
    onClick
}) => null

```
After this you can use  `MemoizedComponent` with guarantee of use `useCallback`
```jsx
<MemoizedComponent
    // onShow will throw error, because handle not memoized by useCallback
    onShow={() => {}}
    // No errors, because  handleClick is RelyCallback
    onClick={handleClick}
>
```

**Comment by micmcg** [comment]
> I wouldn't say _always_ using `useCallback` is idiomatic. Quite the opposite, it hurts startup time and memory (a tiny bit, but still) but doesn't always give you anything. Same goes for overuse of `memo`.

@gaearon, you are no doubt correct, but you are looking at this from a technical perspective rather than a developer behaviour one. Imagine a team with mixed ability react developers. `useMemo`-ing and `useCallback`-ing all values that are passed as props to another component may not be necessary or may even have a slight perf impact (though likely negligible). However, the pay-off comes in the time saved identifying and fixing a bug that was caused by not memoising, or trouble-shooting a performance issue that could have been avoided with memoisation. 
So you can either hope all your developers will identify all the correct times to use memoisation, or you can blanket memoise, pay a small cost, and not worry about it. With mixed ability teams, the first option is a non-starter. 

This is why people (including myself) would like this rule, obviously it can be off by default though.
