### ISSUE TITLE
[ESLINT] Depreciation warning: 'ecmaFeatures' config file prop is depreciated

### ISSUE THREAD

**Issue by ahtee** [facebook/react#15730]
I was looking at tooling and came across this error in the `webpack-dev-server` cli command which output:

`(node:22249) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in "react")`

**Comment by samuel-gomez-axa** [comment]
i have the same problem , do you find solution ?
my .eslintrc.json
`{
  "extends": ["airbnb", "prettier", "prettier/react", "react"],
  "plugins": ["prettier", "react", "react-hooks"],
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "jest": true
  },
  "rules": {
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [".js", ".jsx"]
      }
    ],
    "react/prop-types": 0,
    "react/no-unescaped-entities": "off",
    "react/require-default-props": "off",
    "react/no-unused-prop-types": "off",
    "react/no-unused-state": "error",
    "no-underscore-dangle": 0,
    "import/imports-first": ["error", "absolute-first"],
    "import/newline-after-import": "error",
    "quotes": ["error", "single"],
    "indent": ["error", 2],
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "jsx-a11y/label-has-for": [
      2,
      {
        "components": ["label"],
        "required": {
          "every": []
        },
        "allowChildren": "false"
      }
    ],
    "jsx-a11y/label-has-associated-control": [
      2,
      {
        "controlComponents": ["Textarea", "File"],
        "detch": 3
      }
    ],
    "max-len": [
      "error",
      {
        "code": 500
      }
    ]
  },
  "globals": {
    "window": true,
    "document": true,
    "localStorage": true,
    "FormData": true,
    "FileReader": true,
    "Blob": true,
    "navigator": true,
    "fetch": true
  },
  "parser": "babel-eslint",
  "settings": {
    "import/resolver": {
      "node": {
        "paths": ["src", "node_modules"],
        "extensions": [".js", ".jsx", ".ts", ".tsx"]
      }
    }
  }
}
`
package.json : 
`"devDependencies": {
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-transform-runtime": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@commitlint/cli": "^8.2.0",
    "@commitlint/config-conventional": "^8.2.0",
    "@testing-library/react": "^9.1.4",
    "@testing-library/react-hooks": "^2.0.1",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "babel-loader": "8.0.5",
    "babel-plugin-require-context-hook": "^1.0.0",
    "concurrently": "^4.1.2",
    "cors": "^2.8.5",
    "enzyme-adapter-react-16": "^1.14.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-config-prettier": "^4.3.0",
    "eslint-config-react": "^1.1.7",
    "eslint-config-react-app": "^3.0.8",
    "eslint-plugin-flowtype": "^2.50.3",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
    "express": "^4.16.4",
    "highlight-loader": "^0.7.3",
    "husky": "^3.0.5",
    "jest-fetch-mock": "^2.1.1",
    "jest-sonar-reporter": "^2.0.0",
    "nodemon": "^1.19.2",
    "precise-commits": "^1.0.2",
    "prettier": "^1.18.2",
    "react-test-renderer": "^16.9.0",
    "stylelint-config-standard": "^18.2.0"
  },`

**Comment by ahtee** [comment]
No, it's still apart of the root dir's `package.json`. I had a question though, im assuming eslintrc in the root dir cascades into each package created/managed from Lerna?
