### ISSUE TITLE
falsey prop shorthand

### ISSUE THREAD

**Issue by bcupac** [facebook/react#15731]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
for example:

```
<VeryCoolReactComponentInstance 
  thisAndThat={false}
/>
```

**What is the proposed behavior?**
```
<VeryCoolReactComponentInstance 
  !thisAndThat
/>
```

This sugar syntax seems useful when for example you want to render something based on a prop. And the default prop is true, as most of the time you want to render that jsx fragment. But in case that you want to ommit the jsx fragment, you set the prop to false.

**Comment by kunukn** [comment]
`thisAndThat` is `falsey` in this example 

```jsx
<VeryCoolReactComponentInstance />
```

Isn't it sufficient?

**Comment by bcupac** [comment]
Its a problem when you have defaultProps of thisAndThat set to true

**Comment by kunukn** [comment]
JSX feature proposal should probably go here https://github.com/facebook/jsx/issues

I have also seen several proposals for omitting the brackets
https://github.com/facebook/react/issues/11944


```jsx
<VeryCoolReactComponentInstance 
  thisAndThat=false
/>
```

**Comment by eps1lon** [comment]
> Its a problem when you have defaultProps of thisAndThat set to true

What worked for us is naming the props according to their default value i.e. `disableSomeFeature` if the default value is false or `enableSomeFeature` if the default value is false. This way the shorthand is just omitting the prop: `const elementWithoutFeature = <Component disableFeature />; const elementWithFeature = <Component />;` or vice versa.

**Comment by threepointone** [comment]
This feels like a feature request for https://github.com/facebook/jsx/issues (but tbh, I don't think we'll change this any time soon.)
