### ISSUE TITLE
Static files are cached and loading from service worker

### ISSUE THREAD

**Issue by vnoitkumar** [facebook/react#15744]
When I do any changes in my CSS file and do a build, a new CSS bundle file is created.

Build One

![build1](https://user-images.githubusercontent.com/17877361/58402665-82311480-807e-11e9-8d7d-a1621452c741.PNG)

Console.log of Build One

![console1](https://user-images.githubusercontent.com/17877361/58402688-8fe69a00-807e-11e9-9e9e-f5ff54029346.PNG)

Build Two

![build2](https://user-images.githubusercontent.com/17877361/58402710-9b39c580-807e-11e9-8d08-4910a00b239b.PNG)

Console.log of Build Two

![console2](https://user-images.githubusercontent.com/17877361/58402728-a856b480-807e-11e9-8f86-3d048c75d976.PNG)

If you see in the second build the CSS file name is changed from main.1012bf29.chunk.css to main.2ff4e3dd.chunk.css

But if you see the console log for both the build is same, the CSS file of the first build is cached.

Expected output: On every build, the cache needs to be cleared.

Note: I have enabled PWA in my react app. React version is 16.7.0, I have created my project using the create-react-app command

**Comment by kunukn** [comment]
Is this issue related to `Create-React-App`?

I believe you can create an issue for those here
https://github.com/facebook/create-react-app/issues

**Comment by vinoth-contus** [comment]
No, it is not the problem of Creat-react-app! I think the index.html file is cached and even after so many changes I took a build, the event then the old CSS files are getting loaded. If I do a hard refresh or clearing the cache it is working. How can I solve this problem?

**Comment by threepointone** [comment]
This is clearly an issue with create-react-app and its serviceworker, React doesn't have anything to with this. Would recommend that you post an issue in https://github.com/facebook/create-react-app/issues
