### ISSUE TITLE
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by ir-fuel** [facebook/react#15742]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I am getting this error:

```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem. at invariant (webpack:///./node_modules/react/cjs/react.development.js?:88:15) at resolveDispatcher (webpack:///./node_modules/react/cjs/react.development.js?:1436:28) at Object.useRef (webpack:///./node_modules/react/cjs/react.development.js?:1471:20) at Toolbar (webpack:///./client/index.jsx?:10:48) at renderWithHooks (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:12938:18) at mountIndeterminateComponent (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:15020:13) at beginWork (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:15625:16) at performUnitOfWork (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:19312:12) at workLoop (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:19352:24) at HTMLUnknownElement.callCallback (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:149:14)
```

Here is an example project that shows the problem:

https://github.com/ir-fuel/material-test

```
import ReactDOM from 'react-dom'
import React from 'react'

function Toolbar() {
  React.useRef()
  return <span>Test</span>
}

ReactDOM.render(
  <Toolbar/>,
  document.querySelector(".application")
);
```

**What is the expected behavior?**

It should not give an error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.6
Chrome Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by kunukn** [comment]
I could not reproduce it. It ran fine for me.
Your github repo didn't have a `npm start` command but a webpack build.

I ran `yarn development` and added a index.html file in dist folder with following content

```html
<html>
<head>  
    <title>Document</title>
</head>
<body>
    <div class="application"></div>
    <script src="./bundle.js"></script>
</body>
</html>
```

And it rendered `Test` in the browser as expected. 

If you haven't, you could also try to solve it using by following this document. 
https://reactjs.org/warnings/invalid-hook-call-warning.html

**Comment by ir-fuel** [comment]
[Archive.zip](https://github.com/facebook/react/files/3227490/Archive.zip)

Here is my webpack output. You can just put it in a folder somewhere and have a web server point at it (MAMP for instance). If you open the url it will show the error.


Sorry for forgetting the instructions. I do `npm run development` and open my webbrowser at `localhost:8888`

No need to create the `dist` folder or to copy an `index.html` file there if you run webpack.

As you can see, I am not the only one that managed to have this issue with my code:

https://github.com/mui-org/material-ui/issues/15832#issuecomment-495769290

**Comment by codeshaker** [comment]
Can you share your package.json?

**Comment by ir-fuel** [comment]
My package.json and all other files are in the github repo I put in my first post.

**Comment by ir-fuel** [comment]
So, what causes this?

**Comment by tangqin0206** [comment]
------------------ 原始邮件 ------------------
发件人: "Nitesh Kumar"<notifications@github.com>;
发送时间: 2019年6月3日(星期一) 中午11:12
收件人: "facebook/react"<react@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [facebook/react] Invariant Violation: Invalid hook call. Hookscan only be called inside of the body of a function component. (#15742)




Can you share your package.json?

**Comment by ir-fuel** [comment]
```
{
  "name": "Test",
  "version": "1.0.0",
  "description": "TEST",
  "main": "index.html",
  "scripts": {
    "development": "webpack --devtool eval --progress --colors --debug --mode development"
  },
  "keywords": [],
  "author": "---",
  "license": "---",
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.32.1",
    "webpack-cli": "^3.3.2"
  }
}
```

**Comment by 526117** [comment]
ในวันที่ จ. 10 มิ.ย. 2019 15:07 น. ir-fuel <notifications@github.com>
เขียนว่า:

**Comment by 526117** [comment]
ในวันที่ จ. 10 มิ.ย. 2019 04:34 น. ir-fuel <notifications@github.com>
เขียนว่า:

**Comment by piriej** [comment]
@ir-fuel , I was able to resolve a similar issue in my code base by, deleting my node_modules folder, cleaning the npm cache (npm cache clean -f) and removing my package-lock.json file. Then performing an npm install. Hope that helps you also.
