### ISSUE TITLE
The existing component is rerendered when another instance of the component with the same type should be rendered.

### ISSUE THREAD

**Issue by kn1ght** [facebook/react#15745]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Imagine I have a component which returns one of two components of the same type depending on condition received from props. In the fiddle this appears in component "Wrapper" and these two components are of type "Control" (let us call them Control1 and Control2). Let's say the initial condition makes Control1 to render.
So the problem is that when the condition changes, the constructor of Control2 is not being called as well as Control2.render but the render method of Control1 is called with new props.
In the fiddle when you click "Render Control2" button empty string would be rendered.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://jsfiddle.net/9ce45zjh/3/

**What is the expected behavior?**
In this situation we expect Control2 constructor to be called and then Control2 with new props to be rendered.
In the fiddle we expect the "Control2" string to appear when "render Control2" button was clicked.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6 Win 10, Chrome. We have checked in 15.6.2 version and the behaviour was the same.

**Comment by kunukn** [comment]
I looked around and I think this explains what is happening.
https://stackoverflow.com/a/29074980/815507

The constructor is called once, because the component didn't had to be re-created according to the reconciliation algorithm.

**Comment by acdlite** [comment]
You're correct that this is related to React's reconciliation algorithm.

In this case, the solution is to add a `key` to your Control elements:

```js
if (this.props.type === 1) {
  return <Control key={1} type={1} />
} 
if (this.props.type === 2) {
  return <Control key={2} type={2} />
} 
```

Or this also works:

```js
const type = this.props.type;
return <Control key={type} type={type} />;
```

You can read more about keys here:

https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by ilearnf** [comment]
Hi @kunukn, Yeah, I think this explains the situation exactly.
Hi @acdlite, Yes, @kn1ght and me, we’ve found out that it works well with keys. I think it could be better to point this situation out in the key article in the documentation. 
Thank you guys!
