### ISSUE TITLE
React test renderer return null on finding a stateless component

### ISSUE THREAD

**Issue by vanydeasy** [facebook/react#15749]
**Do you want to request a *feature* or report a *bug*?**

*Bug*

**What is the current behavior?**

We use `react-test-renderer` (`findByType` function) on test case but it returns null value instead. This also occurs when using `React.forwardRef`. It can be reproduced on https://codesandbox.io/s/angry-khayyam-jbouo. The test suite can be found on `index.test.js`.

**What is the expected behavior?**

`react-test-renderer` can find a stateless component.

**Comment by ramadistra** [comment]
Only a class component has an `instance` property. 

If you're only trying to assert that a component of a certain type exists, calling `findByType(Type)` should be enough because it will throw if it doesn't find a component of that type.

**Comment by vanydeasy** [comment]
That's a good point! Thanks @ramadistra.
