### ISSUE TITLE
webview element: "Warning: Received `true` for a non-boolean attribute `nodeintegration`."

### ISSUE THREAD

**Issue by burtonator** [facebook/react#15740]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I'm using TSX and Electron and using the <webview> element. 

I'm using <webview disablewebsecurity> and it's complaining that this isn't accepted.

This is a supported property.  It's also represented properly in the typescript types for this element.

```
    interface WebViewHTMLAttributes<T> extends HTMLAttributes<T> {
        allowFullScreen?: boolean;
        allowpopups?: boolean;
        autoFocus?: boolean;
        autosize?: boolean;
        blinkfeatures?: string;
        disableblinkfeatures?: string;
        disableguestresize?: boolean;
        disablewebsecurity?: boolean;
        guestinstance?: string;
        httpreferrer?: string;
        nodeintegration?: boolean;
        partition?: string;
        plugins?: boolean;
        preload?: string;
        src?: string;
        useragent?: string;
        webpreferences?: string;
    }
```

```
/home/burton/projects/polar-bookshelf/node_modules/react-dom/cjs/react-dom.development.js:506 Warning: Received `true` for a non-boolean attribute `disablewebsecurity`.

If you want to write it to the DOM, pass a string instead: disablewebsecurity="true" or disablewebsecurity={value.toString()}.
    in webview (created by TabBody)
    in TabBody (created by TabPanes)
    in div (created by TabPane)
    in TabPane (created by TabPanes)
    in div (created by TabContent)
    in TabContent (created by TabPanes)
    in TabPanes (created by TabNav)
    in div (created by TabNav)
    in TabNav (created by FakeTabbedBrowser)
    in div (created by FakeTabbedBrowser)
    in FakeTabbedBrowser (created by App)
    in div (created by App)
    in App
```
I just upgraded all my libs to:

 @types/react@16.8.18 @types/react-dom@16.8.4 react@16.8.6 react-dom@16.8.6 

**What is the expected behavior?**

The <webview> should get the attributes I specify.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

@types/react@16.8.18 @types/react-dom@16.8.4 react@16.8.6 react-dom@16.8.6 

... I'm dead in the water on this one so even a workaround would really be appreciated!

I think this is a React issue since its happening at runtime.  The compiler handles it just fine.

**Comment by burtonator** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26501#issuecomment-420483643

this workaround fixes it ...

**Comment by threepointone** [comment]
the workaround is what we would suggest as well I think (unless we made an electron specific renderer, which probably won't happen any time soon). Maybe it's a good idea for the typescript definition to accept "true" as a value?
