### ISSUE TITLE
Inline style update issue in Chrome 74

### ISSUE THREAD

**Issue by blakestone95** [facebook/react#15753]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When updating `top` inline style on an absolutely positioned element in a relatively positioned parent with vertical overflow, the style attribute value updates in the DOM tree, but UI is not repainted to reflect the new value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Minimal Demo: https://codesandbox.io/s/react-scrolling-bug-e7l4f
1. Create `div` with a child to apply style to and some text
2. Restrict parent `div`'s size so that text overflows
3. Set parent `div` to `position: relative` and `overflow-y: auto` (`overflow-x` doesn't seem to affect bug)
4. Set child to `position: absolute`
5. Add state to component to track the `scrollTop` value of the scrollable parent `div`
6. Create `onScroll` SyntheticEvent handler that sets the `scrollTop` state
7. Use the `scrollTop` state value to set the absolutely positioned child's `style.top` attribute
8. Attempt to scroll parent but see that child element's position does not update even though, upon inspection, the `style.top` value is being set

**What is the expected behavior?**
The DOM should be repainted whenever the `style` attribute changes so that changes are immediately visible.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.8.6 and 16.4.2 (2 different web app projects I work on)
OS: Windows 10, build 17134.765
Browser: Google Chrome 74.0.3729.169

NOTE: Tested in MS Edge, and behaves as expected.  May possibly be a Chrome bug and not a React bug.  I ran through several JS commands to set the style attribute without React, though, and Google Chrome updated as expected.

**Comment by audiolion** [comment]
it is supposed to remain fixed at the top left of the container as you scroll right? If so it works for me with:

macOS 10.14.4
Chrome 74.0.3729.169

**Comment by blakestone95** [comment]
@audiolion Yes, that's the way it should work.  Seems that MacOS doesn't have this issue.  I could post a short video of the bug if people are interested.

**Comment by blakestone95** [comment]
I tested this on some personal computers running Win10 build 18362.116 and this bug is not happening.  The bug occurs on my work laptop which has the specified Windows build in the report.  Starting to suspect the bug is related to that build of Chrome on that build of the Win10 OS.  Possibly not a React issue.

**Comment by gaearon** [comment]
>updating the style attribute manually through vanilla JS repaints the DOM correctly.

Please post details about how you confirmed this.

**Comment by thomassuckow** [comment]
Repro on
Chrome Version 74.0.3729.169 (Official Build) (64-bit)
MacOS 10.14.5 (18F132)

<img width="345" alt="Screen Shot 2019-05-30 at 08 35 14" src="https://user-images.githubusercontent.com/3100037/58644327-e12c9e80-82b5-11e9-910a-901a4d839a0d.png">

@audiolion As you scroll *down*

Interesting mousing over the devtools elements viewer causes it to repaint correctly. I tried puting the setState into requestAnimationFrame thinking it was a scroll event quirk, no difference.
https://codesandbox.io/s/react-scrolling-bug-fk1o2

Interestingly, grabbing the scroll bar and dragging kinda works. But mouse wheel does not.

Set interval does work...
https://codesandbox.io/s/react-scrolling-bug-ezine

Set timeout works...
https://codesandbox.io/s/react-scrolling-bug-4jz4s

Requesting an animation frame from a setTimeout works...
https://codesandbox.io/s/react-scrolling-bug-0ft3t

So some interesting interaction of the animation frame after a scroll event ¯\_(ツ)_/¯ Leaning to this being a chrome bug.

**Comment by blakestone95** [comment]
@gaearon In Chrome's console I ran variations of `document.getElementsByClassName('fixed')[0].style.top = somePixelString`  which is, what I understand, React essentially does behind the scenes during reconciliation.  Doing this changed the 'fixed' div's top position as expected.  I wasn't sure what other debugging steps to try (thanks @thomassuckow for trying a few other variations).

**Comment by blakestone95** [comment]
Looks like the beta build of Chrome resolves this issue.  I suspect it has something to do with modifying a style attribute in response to a scroll event that had an issue.  Going to chalk this up to a Chrome bug and not a React bug, thanks for everyone's time on this.
