### ISSUE TITLE
DevTools in production environment 

### ISSUE THREAD

**Issue by AlexR10** [facebook/react#15764]
![2019-05-29_13-00](https://user-images.githubusercontent.com/33522235/58580030-d3254200-8211-11e9-882d-85da2664a3b2.png)

**Do you want to request a *feature* or report a *bug*?**
I think the production environment, React Devtools you should not show any information about the state or components. similar to redux Devtools. 
**What is the current behavior?**
Just now I can Edit some information with React DevTools in the production environment

**Comment by threepointone** [comment]
Why not? It's useful, and there aren't any particular security issues related to this.

**Comment by medonagy45** [comment]
Do you need help on that ?? or still the issue not cleared ?

**Comment by threepointone** [comment]
Closed, thanks for reminding!
