### ISSUE TITLE
PLEASE HELP IN DEV TOOLS MY SECURITY POLICY STATES THIS... IS THIS NORMAL

### ISSUE THREAD

**Issue by helpimhacked** [facebook/react#15762]
why is there a remote address?????
equest URL: https://www.facebook.com/
Request Method: GET
Status Code: 200 
Remote Address: [2a03:2880:f112:83:face:b00c:0:25de]:443
Referrer Policy: no-referrer-when-downgrade
cache-control: private, no-cache, no-store, must-revalidate
content-encoding: br
content-security-policy: default-src * data: blob:;script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' blob: data: 'self';style-src data: blob: 'unsafe-inline' *;connect-src *.facebook.com facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com 'self' chrome-extension://boadgeojelhgndaghljhdicfkmllpafd chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm;
content-type: text/html; charset="utf-8"
date: Wed, 29 May 2019 12:28:03 GMT
expires: Sat, 01 Jan 2000 00:00:00 GMT
pragma: no-cache
status: 200
strict-transport-security: max-age=15552000; preload
vary: Accept-Encoding
x-content-type-options: nosniff
x-fb-debug: dqBNmx7QvK86BkrcM4PG6OybJOSqB+FHBn5pPhup2XfSmutJN9frESchONg5c1A1UFtEPnNr105kK/CD1oo36Q==
x-frame-options: DENY
x-xss-protection: 0
:authority: www.facebook.com
:method: GET
:path: /
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cookie: 
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.

**Comment by threepointone** [comment]
I don’t understand where you’re seeing this, react makes no http calls. Closing this, but lemme know if you have more info or a repro
