### ISSUE TITLE
Development Server gives HTTP ERROR 400 in Chrome but works in Edge

### ISSUE THREAD

**Issue by zanotta** [facebook/react#15760]
Even with default create-react-app gives the same error in Chrome. Build version works in all browsers.
Already tried changing the development server port in .env, but no success.

nodejs: 10.15.3
npm: 6.9.0
OS: Windows 10 x64
react-scripts: 3.0.1
Google Chrome: 74.0.3729.169

**Comment by nmain** [comment]
This should be posted to https://github.com/facebook/create-react-app/issues
