### ISSUE TITLE
React can import thirdpart react component from cdn?

### ISSUE THREAD

**Issue by yinglau** [facebook/react#15777]
React can import third-part react component from cdn?
Like `import('https://domain.com/components/index.js')`

**Comment by KraigWalker** [comment]
This isn't really to do with React. This isnstead controlled by [dynamic imports](https://developers.google.com/web/updates/2017/11/dynamic-import).

The good news is yes! You can `import()` modules cross-origin. However, your cdn will need to serve the module with a valid `Access-Control-Allow-Origin`. The simplest, most insecure value is `*` which allows requests from all domains, but if you can you should limit the response have just the domain(s) used by your app.
