### ISSUE TITLE
Unknown event handler property `onBeforePaste`. It will be ignored.

### ISSUE THREAD

**Issue by 0xdevalias** [facebook/react#15787]
**Do you want to request a *feature* or report a *bug*?** Both..?

**What is the current behavior?**

Cut down example:
```jsx
<div onBeforePaste={event => console.warn('onBeforePaste', event)} />
```

According to https://github.com/facebook/react/issues/140 I should be able to just use a custom attribute since `16.x`.

But that doesn't seem to be the case:
```
Warning: Unknown event handler property `onBeforePaste`. It will be ignored.
    in div (at MarkdownField.js:122)
```

My guess is I am hitting the following clause in https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html#changes-in-detail:
> Note: attributes starting with on are not passed through as an exception because this could become a potential security hole.

So my question becomes.. how can I circumvent that, when I explicitly want to be able to set a handler?

**Context:** due to 'legacy IE reasons' surrounding paste/file attachments, it seems necessary to use `onBeforePaste` to 'coerce' it into allowing images to be pasted into a textarea:
- https://technet.microsoft.com/en-us/aa743278%28v=vs.71%29?f=255&MSPPError=-2147217396

**What is the expected behavior?**

Ability to use `onBeforePaste` with my custom handler.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`16.8.6`

**Comment by 0xdevalias** [comment]
This is my current hacky workaround solution:

```javascript
// Use the passed in ref, or create a new one
const ref = props.ref || createRef()

// When the ref is updated, this code will run
useEffect(
  () => {
    if (ref.current) {
      ref.current.onbeforepaste = event => {
        // TODO: implement actual code here
        console.warn('onBeforePaste', event)
      }
    }
  },
  [ref]
)
```

**Comment by kunukn** [comment]
I believe `onBeforePaste` event is not (yet) added to React.

Custom attributes is about being able to add custom attributes that shows up in the DOM. 
It is not the same as adding an event listener.

`<div mycustomattribute ='some-value'> some content </div>`

https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html



I believe your current imperative workaround is the option we have for know (Please correct me if I am wrong).

**Comment by 0xdevalias** [comment]
The workaround seems to do it, but i’m curious why a ‘custom attribute’ that happens to have a JS function assigned to it, that would end up in the DOM as such, wouldn’t end up being an event handler?

**Comment by nmain** [comment]
React's fallback path where it will handle any unknown prop provided to it on the react element corresponding to a dom element sets attributes, not properties, and `Element.prototype.setAttribute` stringifies any value sent to it.  So it doesn't work for the same reason that only one of the buttons works in this fiddle: https://jsfiddle.net/hr9vbpLj/

In order for React to connect an event handler it needs to understand it.

**Comment by 0xdevalias** [comment]
I wasn't aware of that. Interesting.

**Comment by mtjn** [comment]
This issue also seems to happen when using `onSelectStart`. I'm using the workaround above, is there a plan/ambition to change this behavior? Is it considered a bug, or is React working As Intended?

**Comment by nmain** [comment]
The fact that React won't connect any event handler it doesn't know about is by design.  Whether it ought to know about onSelectStart?  Maybe.  You should probably create a new issue about that for more visibility.

**Comment by gaearon** [comment]
Is `onBeforePaste` standard? If yes, feel free to send a PR. If no, please keep using the ref workaround.

**Comment by 0xdevalias** [comment]
@gaearon it is in legacy versions of IE I believe, and is required for IE11 compatibility:

- https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa742299(v%3Dvs.85)
