### ISSUE TITLE
Where to get support link on README.md file

### ISSUE THREAD

**Issue by SenayYakut** [facebook/react#15783]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

** I like to add one more link to the documentation**

 on README.md file the link where to get help. when you click the link it will take you another readme.md file and on that file under the news ,i like to add " https://www.facebook.com/react/"

**Comment by threepointone** [comment]
We have multiple links to our official docs. Specifically for support - https://reactjs.org/community/support.html
