### ISSUE TITLE
Open API like specification for react routing, navigation, links and components

### ISSUE THREAD

**Issue by arunkumar413** [facebook/react#15788]
Hi Team,

Could you please develop a Open  API (https://swagger.io/specification/#specification)  like design specification for react. Such a specification written in YAML file could help automate the process of  routing, creation of navigation/bar links and also some boilerplate code for components. As the components are building blocks of react, in a large application with too many components it' a bit boring task to create components by hand. If we have a specification in YAML then such tasks would be easier. 

Initially we can start by creating a simple mapping of routes/url to components and later see to fit more features like props, state etc, auto import required libraries, static UI elements, etc

Thanks,
Arun

**Comment by threepointone** [comment]
React doesn’t prescribe what patterns to use for those concerns. You’re welcome to do so for your own apps/codebase.
