### ISSUE TITLE
[devTools] hard to review properties

### ISSUE THREAD

**Issue by ahtee** [facebook/react#15781]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Hard to work with 😦 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:** open devtools -> open react tab -> view the Props *right sidebar* and review the props. its jumpy and closes. 😡 😅 

![2019-05-30 13 00 30](https://user-images.githubusercontent.com/5076085/58650104-d1c04c00-82db-11e9-9e54-7ac62c5a4b1e.gif)

**What is the expected behavior?** Not expecting it to have a mind of its own 🤔 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** 
React 16.8.6
Google Chrome Version 74.0.3729.169 on MacOS High Sierra
This is the first time im experiencing anything like this 🤔 🎉

**Comment by bvaughn** [comment]
I think this issue was fixed a few weeks back with a refactoring of how the hydration logic works. The fix should have gone out in v4.3.0. I'm going to mark this issue as resolved but please let me know if you see the behavior again. (In that case, a repro would be useful.)

**Comment by ahtee** [comment]
I think it hasn't happened since but will keep my eyes peeled :) thanks team
