### ISSUE TITLE
React App Deployed on GH Pages is not proper PWA

### ISSUE THREAD

**Issue by gkemp94** [facebook/react#15782]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When deploying a CRA to github pages with service workers enabled and manifest complete, it still can't be installed because manifest cannot be fetched. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Create a new CRA
Change index.js to register service worker
follow steps to deploy to gh-pages
fill out manifest to include all required fields for installabiity 
Notice you cannot install because `This page is controlled by a service worker, however no start_url was found because no manifest was fetched.`

**What is the expected behavior?**
Be able to install this PWA. 
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All browsers. Mac OS, React 16.86

**Comment by threepointone** [comment]
You should post this at https://github.com/facebook/create-react-app/issues, cheers
