### ISSUE TITLE
Critial application crash bug when in JS code create prototype properties for Object class

### ISSUE THREAD

**Issue by web-strong** [facebook/react#15799]
Today i have bad news. 
I create new project based on **create-react-app**.
Execute in terminal command **npm start**
Write code in App.jsx before function declaration (function App).
In browser devtools js console i have warning message from React:

> index.js:1375 Warning: Invalid value for prop 'then' on `<div>` tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
>     in div (at Application.jsx:100)
>     in Index (at Application.jsx:111)
>     in Index (at src/index.js:7)

And finally i reload page in browser by F5 hotkey ( dublicate tab in browser ) and my Application is CRASH. My browser up use resources to 100% CPU, i cannot close tab, i must kill process.

Writed code in App.jsx before function declaration (function App).
```
Object.prototype.then = function(action){
    
    if(typeof action === 'function'){
        action(this);
    }

    return this;
}
```

**Comment by web-strong** [comment]
React have not exitable recursion, when i add some function in Object class.

**Comment by web-strong** [comment]
All is need for kill any applications use react need on page execute 1 line code. 
```
Object.prototype.then = function(){ return this; }
```
Example, Anymous can develop extention for browsers, extention like ads bloker etc..., and execute this code on each page for all extention users. 
Any can inject this code to popular opensource libs. And its be bad (

**Comment by web-strong** [comment]
I visit on my account in Facebook, press F12 and execute this code in console. And ... crash app (
I add to index.html this code and app crash with error:
```
react-dom.production.min.js:31 Uncaught Invariant Violation: Minified React error #96; visit https://reactjs.org/docs/error-decoder.html?invariant=96&args[]=then for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:5000/static/js/2.3310f33a.chunk.js:1:8235
    at a (http://localhost:5000/static/js/2.3310f33a.chunk.js:1:8338)
    at h (http://localhost:5000/static/js/2.3310f33a.chunk.js:1:8834)
    at Object.injectEventPluginOrder (http://localhost:5000/static/js/2.3310f33a.chunk.js:1:10084)
    at Object.<anonymous> (http://localhost:5000/static/js/2.3310f33a.chunk.js:1:43580)
    at f (http://localhost:5000/:1:947)
    at Object.<anonymous> (http://localhost:5000/static/js/2.3310f33a.chunk.js:1:1295)
    at f (http://localhost:5000/:1:947)
    at Module.9 (http://localhost:5000/static/js/main.f3d6fbb7.chunk.js:1:152)
    at f (http://localhost:5000/:1:947)
```

**Comment by threepointone** [comment]
Don’t do that then? You shouldn’t extend native prototypes, and *especially* not Object.prototype. 

This isn’t a react issue, and not a security issue either (if anyone can inject js into your app, you have bigger problems than just react crashing)

Closing.

**Comment by nmain** [comment]
In addition to whatever other havoc it causes, adding an `Object.prototype.then` will break almost everything involving promises because in the promise resolution algorithm, everything looks like a PromiseLike (has a then method) so the runtime will attempt to unwrap it infinitely.

For instance, the following code hangs (without involving react or any other third party libs at all):

```
Object.prototype.then = function(action){
    if(typeof action === 'function'){
        action(this);
    }
    return this;
};

(async () => {
    await {};
})();
```

**Comment by web-strong** [comment]
Yes, you are right, my code have problem ) Thanks )
