### ISSUE TITLE
[ESLint][Bug] react-hook-deps warning for Flow Generic Type variable

### ISSUE THREAD

**Issue by jordalgo** [facebook/react#15803]
**What is the current behavior?**
ESlint is showing a warning for a missing dependency that is a Flow Generic Type at the beginning of an arrow function passed to a React hook.

e.g.
```
function Example({ prop }) {
    const bar = useEffect(<T>(a: T): Hello => {
       prop();
    }, [prop]);
}
```
The warning is for 'T'. 

**Expected Behavior**
No warning.

**Comment by jordalgo** [comment]
https://github.com/facebook/react/pull/15804

**Comment by threepointone** [comment]
Closed by https://github.com/facebook/react/pull/15804 thanks!
