### ISSUE TITLE
Lose setState while binding object

### ISSUE THREAD

**Issue by vovanezha** [facebook/react#15807]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I try to bind _this_ and _form_ (Formik's object) to a class method for getting access to _setState_ and some formik's methods, but _setState_ is undefined while all others fields exist

```javascript
  handleChange() {
    // here I need access to setState and setFieldValue (formik's method)
  }

  renderInput = ({ form }) => {
    return (
      <input name={'name'} onChange={this.onChange.bind({ ...this, ...form }) />
    )
  }
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/romantic-edison-wyji4?fontsize=14

**What is the expected behavior?**

class method _setState_ is defined

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.6

**Comment by nmain** [comment]
That's how javascript works.  Non-own properties are not spread:

```
// logs `undefined`
console.log({ ...new (class { d() {} }) }.d)
```

**Comment by mmarkelov** [comment]
@vovanezha if you are using **Formik**, you should use **handleChange** of provided object, like so:
```javascript
renderInput = ({ form }) => {
    return (
      <input name='name' onChange={form.onChange} />
    )
  }
```

**Comment by vovanezha** [comment]
Thanks for the answers. It became interesting to me, is **setState** doesn't belongs to **React Component**

**Comment by nmain** [comment]
React.Component is just a class and behaves by the same rules as every other class.  This might be a good place to start learning:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties
