### ISSUE TITLE
Feature Request: COMMAND_MERGESET

### ISSUE THREAD

**Issue by maspwr** [facebook/react#1581]
I think having the ability to do a merge or set with the Immutability Helpers if the target is undefined would be a nice addition.  I can open a PR if this sounds reasonable.

**Comment by gaearon** [comment]
At this point `React.addons.update` is in maintenance mode and unlikely to receive future feature updates. It’s best to use a dedicated third-party NPM module for this, e.g. Lodash, https://github.com/rtfeldman/seamless-immutable, https://github.com/substantial/updeep, and/or others.
