### ISSUE TITLE
onClick fires on a button which is inside a disabled fieldset

### ISSUE THREAD

**Issue by everdimension** [facebook/react#15818]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

An `onClick` handler is called on a `button` which is inside a `disabled` `fieldset` and has markup inside of it.

**Reproduction**

https://jsfiddle.net/everdimension/05p687q2/9/

**What is the expected behavior?**

The `onClick` handler should not be called, because the button is in a `disabled` state, even though it doesn't explicitly have a `disabled` attribute.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Chrome and Safari are affected. In Firefox there is no such bug.
As for React versions, I think all versions are affected.

### NOTE
This is related to https://github.com/facebook/react/issues/8308

**Comment by everdimension** [comment]
Oh and I have also found https://github.com/facebook/react/issues/7711

**Comment by rithikachowta08** [comment]
I would like to work on this bug if no one else is working on it
