### ISSUE TITLE
Error with hooks when using npm link

### ISSUE THREAD

**Issue by BaumVitaly** [facebook/react#15812]
**Current behavior:**

I have some `@mycomponents` in another place from project which depends on react and react-dom. For this components i use react hooks. After editing any of component i use `npm link`, and in project i use `npm link @mycomponents/core` and project crushes with this error:

`Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.`

I was trying to publish `@mycomponents` in my repository and after publishing i run `npm install` and all works correct from node_modules.

Probably problem with npm link

**Expected behavior**

npm link works correctly with hooks

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react: v16.8.6
react-dom: v16.8.6
browser: Google chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by m31415** [comment]
See

-  https://github.com/facebook/react/issues/13991

- https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by threepointone** [comment]
Closing as a dupe of #13991
