### ISSUE TITLE
components that use the useState hook potentially share their state

### ISSUE THREAD

**Issue by raphi011** [facebook/react#15817]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
Functional components that use `useState` can potentially share their state if they are conditionally rendered. See the codepen below.

In my opinion this is a bug because it breaks the isolation of components and forces me to change my way of writing conditional components when using hooks with `useState`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/reacthooksbug-n529s

**What is the expected behavior?**
Components with `useState` hooks never share their state.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I have reproduced this with versions 16.8.2 and 16.8.6 (did not try it with others).

**Comment by nmain** [comment]
There's nothing hook-special about this, you can easily reproduce the behavior with class based components:

https://codesandbox.io/s/reacthooksbug-b4k16

You've created a component that only depends on `props.text` when initially mounted and never uses that prop value again, so when the prop changes without remounting, nothing changes in the output.

If you really want this behavior, you can use `key`:

https://codesandbox.io/s/reacthooksbug-9d140

But usually, it's better to just make components that will always reflect their props in a predictable way.

**Comment by raphi011** [comment]
> There's nothing hook-special about this, you can easily reproduce the behavior with class based components:
> 
> https://codesandbox.io/s/reacthooksbug-b4k16
> 
> You've created a component that only depends on `props.text` when initially mounted and never uses that prop value again, so when the prop changes without remounting, nothing changes in the output.
> 
> If you really want this behavior, you can use `key`:
> 
> https://codesandbox.io/s/reacthooksbug-9d140
> 
> But usually, it's better to just make components that will always reflect their props in a predictable way.

Yes, I've simplified the component to remove all the noise. My actual component has more properties and subscribes to language changes via `useEffect` and updates its text accordingly when the user switches languages - which does not work because it uses the state from a component that was initialized with a different value passed as the `name` prop (or in my case the localization key).

**Comment by nmain** [comment]
I agree that using `key` is something to be avoided in many cases.  The better answer is to only use `state` when you really want local state; when you really want a component that will behave differently depending on whether it was unmounted and replaced or just "repropped" in reconciliation.  For most other situations, you should try to make components that don't care about mounting and unmounting too much.  I think the new hooks api gives a lot of opportunities to do that; many former uses of state can be replaced by `useMemo`, and cDM type stuff can be replaced by `useEffect`, whose deps array gives you a cleaner way to express when this effect needs to rerun.

I'm sure your real example is quite complicated and it might not be easy to apply these ideas.

**Comment by a-c-sreedhar-reddy** [comment]
I think you should use props without storing them in state.

**Comment by a-c-sreedhar-reddy** [comment]
This [link](https://overreacted.io/writing-resilient-components/#principle-2-always-be-ready-to-render) is helpful

**Comment by raphi011** [comment]
> I agree that using `key` is something to be avoided in many cases. The better answer is to only use `state` when you really want local state; when you really want a component that will behave differently depending on whether it was unmounted and replaced or just "repropped" in reconciliation. For most other situations, you should try to make components that don't care about mounting and unmounting too much. I think the new hooks api gives a lot of opportunities to do that; many former uses of state can be replaced by `useMemo`, and cDM type stuff can be replaced by `useEffect`, whose deps array gives you a cleaner way to express when this effect needs to rerun.
> 
> I'm sure your real example is quite complicated and it might not be easy to apply these ideas.

Ok - I think I now know whats happening - the Component example helped me!

In the reconciliation phase react thinks that the two components are the same even though they are created in two different branches and thus the initialState is ignored at the second run.

**Solution** (in my actual component)
1. calling useEffect once for subscribing to the language changes - and passing an empty array as the second param to only do this once. 
2. and once again to update the state if the key changes with an array containing the key of the translation as the second param.

Thanks @nmain
