### ISSUE TITLE
if react have a prerender api

### ISSUE THREAD

**Issue by ttm1017** [facebook/react#15831]
i wanner a api which i can prepare virtual dom before component run render lifecycle.The reason is i want to prepare virtual dom of next page component in idle time, so i can mount the next page component only waste commit phase time

**Comment by ttm1017** [comment]
React version is 16.x

**Comment by gaearon** [comment]
That's exactly what Concurrent Mode will let you do — but it's not available in a stable release yet. Watch our blog for updates.
