### ISSUE TITLE
Not able to import json files in TSX files

### ISSUE THREAD

**Issue by synckarthik** [facebook/react#15835]
I have tried to import the json file in my react application(App.tsx)

[App.tsx

import * as currencies from './currencies.json';](url)

My Json file will look like below structure:

[{
  "main": {
     "numbers": {
        "currencies": {
         }
      }
   }
}
](url)
While running the application, it throws the below error

(1,1): unused expression, expected an assignment or function call

After further analysis, i have added the typings.d.ts file within src folder

[declare module "*.json" {
    const value: any;
    export default value;
}](url)

Please suggest your solution to resolve this issue

**Comment by synckarthik** [comment]
Is any update on this issue?

**Comment by threepointone** [comment]
Did you mean to post this in https://github.com/facebook/create-react-app/issues? Doesn't like anything to do with React.
