### ISSUE TITLE
Make findDOMNode works with functional components

### ISSUE THREAD

**Issue by Amareis** [facebook/react#15839]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
There is no any

**What is the expected behavior?**
`useInstance` hook, which returns some sort of component instance id, which can be used instead of `this` in findDOMNode.
```js
function Comp(props) {
  let id = useInstance()
  useLayoutEffect(() => console.log(findDOMNode(id)), []) //<div>Hello!</div>, then null on unmount

  return <div>Hello!</div>
}
```
On top of that behaviour  can be created `useDOMNode` hook, which is just:
```js
function useDOMNode(refOfCb) {
  let id = useInstance()
  useLayoutEffect(() => {
    let n = findDOMNode(id)
    if (typeof refOrCb === 'function') refOrCb(n)
    else refOrCb.current = n
  })
}
```

**Comment by aweary** [comment]
Hey @Amareis, `findDOMNode` is [in the process of being deprecated](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage). The best way to get a reference to a DOM node is [to use refs](https://reactjs.org/docs/refs-and-the-dom.html#when-to-use-refs). For function components you can use the [`useRef` hook](https://reactjs.org/docs/hooks-reference.html#useref) for that. Hope that helps!

**Comment by jdnichollsc** [comment]
@aweary sorry, how can you use **useRef** with **React.createElement**?
