### ISSUE TITLE
dispatchEvent customEvent of web components not working

### ISSUE THREAD

**Issue by dntzhang** [facebook/react#15830]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

https://github.com/Tencent/omi/blob/master/packages/omim/test-react/src/MyComponent.js

**Online Demo**

https://tencent.github.io/omi/packages/omim/test-react/build/index.html

**What is the expected behavior?**

Fire all the custom events 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All.

I found that dispatchEvent actually executed, except that the element was not bound to the event (such as onAbc) or bound to the document (such as onChange).

Can give a grammatical sugar to bind custom events, otherwise it is not friendly to web compoents integration, such as https://tencent.github.io/omi/packages/omim/docs/build/index.html

------- update --------

I changed it to okay, but it's not elegant.

![844D4012FD49F553DDD28EC252BBBDAC](https://user-images.githubusercontent.com/7917954/59006174-3129d900-8853-11e9-8900-198437424fca.jpg)

------- update --------

I tested dispatchEvent customEvent in other frameworks：

| **Framework**                         | **Result**                           |
| ------------------------------- | ----------------------------------- |
| Preact |   working|
|React| not working|
|Vue| working|
| Angular | working|
|Omi|working|

Thanks.

**Comment by jennasalau** [comment]
Because of React Synthetic Event you will need to add the event listener using a `ref`.

https://custom-elements-everywhere.com/#react

**Comment by dntzhang** [comment]
It's not elegant. @jennasalau

**Comment by egucciar** [comment]
Is there any chance that the team will implement this feature at some point in the future? I.e. implementing a cleaner API for Web-Components that is more analogous to how Preact handles it today? I know there are mitigating concerns, but clean first-class Web Component support should be a priority for the future of the web as more people adopt Web Components and build React Apps into Web Components or use Web Components in their React Apps. Some semblance of an idea of the priority of first class web component support in React's ecosystem from the team would make it easier to evaluate React if you're coming from a stack primarily built with WCs.

**Comment by ZainChen** [comment]
Hope to add support. React will be better.👍

**Comment by AlienC** [comment]
Hope to add support.

**Comment by 498184609** [comment]
Hope to add support.

**Comment by AsaZws** [comment]
Hope to add support.

**Comment by calebdwilliams** [comment]
Would this be the place to propose a style-like syntax to JSX to handle custom events?

```jsx
<some-web-component 
  on={{
    'custom-event': callback1,
    'some-other-event': callback2 
  }}
></some-web-component>
```

This is already familiar syntax and would be easy enough to loop through this property in the virtual DOM (or whatever it's called these days) and call `addEventListener` with the appropriate callback. The only drawback to this is that you lose access to [the listener options](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) which is no different than other events in React and could be mitigated by future syntax that takes another object with a callback and options key.

**Comment by dntzhang** [comment]
Great api. @calebdwilliams

**Comment by calebdwilliams** [comment]
Thinking about this a bit more, it’s likely that `on` would break some existing applications. I still think the structure of my post above would work, but I think naming the prop `onNativeEvent` or `onNativeDOMEvent` would be better to avoid potential conflicts with existing applications.

**Comment by calebdwilliams** [comment]
In the mean time, I just released a JSX schema to allow using native events in React's JSX using the `onEvent<EventName` syntax, see [jsx-native-events](https://www.npmjs.com/package/jsx-native-events).

**Comment by dntzhang** [comment]
Elegant enough! Verification is ok, we are ready to use in production environment. Thank you very much.
https://github.com/Tencent/omi/commit/2838816f635b1ef225790a189e78c01cb303d480

**Comment by orneryd** [comment]
hopefully this helps. It's how i solved the custom element dispatches so react will work properly.

```
class WebComponentWrapper extends React.Component {
  constructor(props) {
    super(props)
    this.elementRef = React.createRef()
  }

  componentDidMount() {
    const { current } = this.elementRef
    if (current) {
      Object.entries(this.props).forEach(([k, v]) => {
        if (k.startsWith('on')) {
          current.addEventListener(toEventName(k), v)
        }
      })
    }
  }

  componentWillUnmount() {
    const { current } = this.elementRef
    if (current) {
      Object.entries(this.props).forEach(([k, v]) => {
        if (k.startsWith('on')) {
          current.removeEventListener(toEventName(k), v)
        }
      })
    }
  }

  render() {
    return React.createElement(this.props.tag, {
      ref: this.elementRef,
      ...this.props
    })
  }
}

export default WebComponentWrapper
```

**Comment by nd0ut** [comment]
Any updates on this?
