### ISSUE TITLE
[Proposal] Second argument to hook's useState

### ISSUE THREAD

**Issue by RafaelCorreaQuantik** [facebook/react#15833]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Differently than class states, useState replaces rather than merge the data (I know, I read the documentation too). But even if I break down my states into multiple useStates, sometimes we need to keep an object such as the user (id, name, category, email) and that makes this behaviour really annoying.

**What I propose**
Having a second argument when constructing the usestate or updating it's value, a boolean that describes if the argument should replace or merge the actual data. Having it's default value for false (it should replace) or equivalent to what was used in the constructor.

**Code example**
``` javascript
//Default merge
const [ user, setuser ] = React.useState(<userobject>, true);

//This merges with the state because we set it as default
setUser({name:"New name"});

//This replaces the state because we have to overwrite the default
setUser({name:"New name"}, false);


//Default replace
const [ user, setuser ] = React.useState(<userobject>);

//This merges with the state because we set it as default
setUser({name:"New name"}, true);

//This replaces the state because we have to overwrite the default
setUser({name:"New name"});
```

**Comment by jquense** [comment]
I don't think there is a great reason for this to belong in the core `useState`, since it's relatively easy to create a custom hook that does exactly what you want. Heres' an example of what I mean (you can also install and use it if you want): https://github.com/react-restart/hooks/blob/master/src/useMergeState.ts

**Comment by threepointone** [comment]
^ like @jquense mentioned, this is fairly easy to do with a custom hook. closing.
