### ISSUE TITLE
Unenable to read environment specific .env

### ISSUE THREAD

**Issue by sushantraje2000** [facebook/react#15846]
I am creating React app with Visual studio 2017 template

I have created .env.qa and .env.staging in root of ClientApp

packages.json

 "scripts": {
    "start": "rimraf ./build && react-scripts start env-cmd -f .env.qa", // some I may need to call qa config
    "build": "react-scripts build", // for production push
    "build:staging": "env-cmd .env.staging react-scripts build", // for staging push
    "build:qa": "env-cmd .env.qa react-scripts build --env=qa", // for qa push
    "test": "cross-env CI=true react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "lint": "eslint ./src/"
  }
 

.csproj

`

<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:qa" />

</Target >

`
My exception is to override variables on qa and staging

**Comment by matheuseabra** [comment]
You need to install the `dotenv` package, and import it as early as possible on your App mount with `import dotenv from 'dotenv'`

**Comment by sushantraje2000** [comment]
Issue is version  "env-cmd": "8.0.2",
when I am updating to latest one its not working other wise working as expected

**Comment by threepointone** [comment]
You should file this at https://github.com/facebook/create-react-app/issues
