### ISSUE TITLE
ReactDOM.render should flush useEffect queue

### ISSUE THREAD

**Issue by kgram** [facebook/react#15859]
**Do you want to request a *feature* or report a *bug*?**

Report a possible bug

**What is the current behavior?**

Effects queued using `useEffect` are not executed synchronously by `ReactDOM.render`. This means it is impossible to execute something after the app is fully mounted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Example showing possibly incorrect behavior: https://codesandbox.io/s/adoring-cloud-q4b17

Log order is 
>before render 
>render 
>callback 
>after render 
>effect

**What is the expected behavior?**

I'm not sure if this is intentional or not, but the behavior I'd expect is that all effects are run before control is returned from `ReactDOM.render`. This would match the behavior of `componentDidMount`, which does run before control is returned. Example: https://codesandbox.io/s/intelligent-browser-g6n2n

Log order is
>before render 
>render 
>mount 
>callback 
>after render

The concrete example I have is that I subscribe to a store, and then immediately update the store. This change triggers other external effects, so it is necessary that it happens after mount. Because the subscribe-effect has not been run, the app never updates. It can be fixed by subscribing with `useLayoutEffect` instead of `useEffect`, but this seems to run counter to the intention of the hooks.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Replicated in React/ReactDOM 16.8.4 and 16.8.6

**Comment by gaearon** [comment]
https://reactjs.org/docs/hooks-reference.html#timing-of-effects

>Unlike componentDidMount and componentDidUpdate, the function passed to useEffect fires after layout and paint, during a deferred event. This makes it suitable for the many common side effects, like setting up subscriptions and event handlers, because most types of work shouldn’t block the browser from updating the screen.

>However, not all effects can be deferred. For example, a DOM mutation that is visible to the user must fire synchronously before the next paint so that the user does not perceive a visual inconsistency. (The distinction is conceptually similar to passive versus active event listeners.) For these types of effects, React provides one additional Hook called useLayoutEffect. It has the same signature as useEffect, and only differs in when it is fired.
