### ISSUE TITLE
Memory leak using withRouter 

### ISSUE THREAD

**Issue by IgorShpyrko** [facebook/react#15851]
### Memory leak using withRouter.

**Do you want to request a *feature* or report a *bug*?**
Looks like a bug. Not sure.

**What is the current behavior?**
When using native events working on modal close everything is ok. When adding event with `window.addEventListener` for `keydown` event every second call is twice longer then previous. EventListener is deleted on `unmount`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

[https://codesandbox.io/s/fragrant-wind-oywme](https://codesandbox.io/s/fragrant-wind-oywme)
problem is seen only in full-screen mode.

when going on private route mock modal is active. To escape I need to press `Esc`. Now it shows `console.time()`. Every next `keypress` load time increments till the page stops responding.

On the other hand - when we click close btn everything is fine. Close function is the same from props. Clicking it doesn`t cause bugs.

General reproduce: Go to link [https://codesandbox.io/s/fragrant-wind-oywme](https://codesandbox.io/s/fragrant-wind-oywme). Switch to full-screen. Open console. Click on `private` link. Press `Esc` button several times.

**What is the expected behavior?**
prevent page response time growing.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Using: React 16.8.6 Hooks, ReactDOM 16.8.6, React-Router 5.0.1, React-Router-DOM 5.0.1.

Browsers: Mozilla FireFox Quantum 67.0, Google Chrome 74.0, Chromium 74.0

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests for React itself.

If you have a question or need help troubleshooting, please check [our community support resources](https://facebook.github.io/react/community/support.html). If you believe this is a bug with a community package please open an issue in their repo.

**Comment by IgorShpyrko** [comment]
I can see it is a bug with React hooks. When using class instead FC everything is OK. The rest of app stays untouched. So where should I ask for a solution?
