### ISSUE TITLE
ScrollView keyboardShouldPersistTaps - new option

### ISSUE THREAD

**Issue by cristianoccazinsp** [facebook/react#15852]
**Do you want to request a *feature* or report a *bug*?**
Feature

Would it be possible to add a new option to keyboardShouldPersistTaps similar to 'handled', but that will hide the keyboard and blur the text input even if the touch event was handled?

In short, add a new option 'passThrough'. This new option would behave like a combination of always and never. Keyboard will always dismiss, but also the events will always be passed down to the children components.

Does it make sense? My current use case is that I have a multi line text input that I want to be blurred when anything else is pressed; however, the 'never' option is not useful because it will also mean that children need two taps to be triggered.

**Comment by threepointone** [comment]
React doesn't have a scrollview component. Did you mean to post it here, or react-native, or a similar project?

**Comment by cristianoccazinsp** [comment]
Definitely meant to post it on the react-native project. Apologies.
