### ISSUE TITLE
Try/catch picking up errors when it should be done

### ISSUE THREAD

**Issue by Kaninsokk** [facebook/react#15864]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Errors thrown in render are being picked up by try/catch that should be done

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I made an example simulating a network call in a try/catch pattern.
https://codesandbox.io/s/dazzling-brown-jyz3n

**What is the expected behavior?**
I expect the app to crash where the error happens and not in the previous try / catch that should be done.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested in 16.8.3 and 16.8.6. Not found it working anywhere as of yet.

**Comment by slim-hmidi** [comment]
I think that you should use [Error Boundaries](https://reactjs.org/docs/error-boundaries.html). However:

> Error boundaries do not catch errors for:
Event handlers (learn more)
Asynchronous code (e.g. setTimeout or requestAnimationFrame callbacks)
Server side rendering
Errors thrown in the error boundary itself (rather than its children)

**Comment by jquense** [comment]
My guess is that this is a bug in regenerator, which is what is compiling the async awaits in the code here. I would see if the behavior still occurs with native async/await

**Comment by Kaninsokk** [comment]
@jquense 

Hey, thanks, that makes sense and was ish what I was guessing. Will be interesting to see :)

@slim-hmidi
Hi, this is not quite related, but good that you mention error boundaries :+1:
