### ISSUE TITLE
Devmode warning if parameter passed to useReducer's reducer is not in proper format

### ISSUE THREAD

**Issue by keul** [facebook/react#15870]
**Do you want to request a *feature* or report a *bug*?**

Feature request

**What is the current behavior?**

Let say I spent too much time debugging a very silly bug. I was calling:

```javascript
const [state, dispatch] = React.useReducer(reducer, initialState);

dispatch(MY_CONST);
```

instead of:

```javascript
dispatch({ type: CALL_LS });
```

As the signature of the dispatch function is documented to be something with a `type` inside, I think that a development mode warning message that alert the user about a bad format can help preventing this issue.

**What is the expected behavior?**

A dev warning message with something like "_an object with type was expected, received ..._"

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.6

**Comment by dmytro-lymarenko** [comment]
No, it is not documented as `to be something with 'type' inside`. You can pass everything to dispatch - that is why it is flexible. (just make sure your reducer will handle that ;) ).

About warning: if you use just js then I think it is impossible to show something. But if you use TS of Flow then after you type everything correctly IDE will show you that warning.

For example, I use TS and I type it like this:
```typescript
type SomeAction = { type: 'action1' } | { type: 'action2', count: number };
type SomeState = ...;
function reducer(state: SomeState, action: SomeAction): SomeState {
    switch (action.type) {
        case 'action1':
        ...
    }
}

const [state, dispatch] = React.useReducer(reducer, initialState);

// and when you try to put something else to dispatch
dispatch(1); // it will throw TS error
```

**Comment by keul** [comment]
Seems fair. Too many redux in my personal background!

Thanks!
