### ISSUE TITLE
Feature request: warn when property not in propTypes is passed into component

### ISSUE THREAD

**Issue by jameslong** [facebook/react#1587]
It would be great if in debug mode react would warn you when you pass in a property on props which is not specified in the propTypes object for that component. i.e. a way to enforce that props should ONLY have the props specified in propTypes and no others. 

This would prevent use of undocumented properties and also allow better code maintenance as unused props would be more easily removed.

**Comment by antris** [comment]
+1 for this.

**Comment by dmitriiabramov** [comment]
+1 for this feature.
It would be nice to have it if you want to enforce props definition/documentation in the project.

i wonder if it's possible to explicitly whitelist generic components that will accept more props than they have in their `propTypes`.

based on the example that @zpao gave in https://github.com/facebook/react/issues/3514
```js
FancyButton = React.createClass {
  propTypes: {
    color: React.PropTypes.string
  },
  render: function() {
    return <button {...this.props} style={color: this.props.color} />;
  }
}
React.render(<FancyButton color="blue" value="foo" />, ...)
```

**Comment by gajus** [comment]
I have developed a higher order component that does this.

https://github.com/gajus/react-strict-prop-types

You can control whether HTML properties are allowed using [`allowHTMLProps`](https://github.com/gajus/react-strict-prop-types#allowhtmlprops) option. It uses a list of all standard HTML attributes, including DOM properties such as `className` and `htmlFor` and handles dynamic properties such as `data-*`.

**Comment by slorber** [comment]
Nice @gajus 

Was concerned about the performance cost but yes deactivating this in production mode would be nice!

**Comment by gajus** [comment]
Yes, you are right. You can easily disable it in the production, https://github.com/gajus/react-strict-prop-types#production-mode.

**Comment by tj** [comment]
Please don't! Not everyone uses/likes prop types

**Comment by Aweary** [comment]
@tj I would assume any implementation would only warn if `propTypes` is defined on the component. So if you don't use `propTypes` at all you would be fine.

**Comment by tj** [comment]
True true. I though this was already in 15.x but I was just doing `<varName` instead of `<VarName` which leads to warnings on the props

**Comment by gaearon** [comment]
>Please don't! Not everyone uses/likes prop types, or at least make it opt-in somehow :D.

Don’t worry, we don’t like them that much either 😄 
Longer term we’ll be encouraging people to use Flow (or TypeScript) instead.

**Comment by tj** [comment]
Awesome, I still have to try Flow, definitely would prefer to just use language features, even if they're still transpiled. I haven't been screwed too bad ignoring them so far haha

**Comment by sodik82** [comment]
> Longer term we’ll be encouraging people to use Flow (or TypeScript) instead.

@gaearon is there any guide that explains how to use Flow instead of proptypes especially how to check/catch unknown prop types (as per this issue). thanks.

**Comment by AlicanC** [comment]
Install flow-bin and initialize the config:
```bash
cd your/project
yarn add --dev flow-bin
yarn run flow init
```

Use it:
```javascript
/* @flow */

import React from 'react';

type Props = {|
  foo: string,
  bar: any,
|};

type State = {|
  baz: number,
  nullable: ?string,
|};

export default class MyComponent extends React.Component<void, Props, State> {
  props: Props;
  state: State = {
    baz: 13,
    nullable: null,
  };

  componentWillMount() {
    this.setState({
      baz: 'bleh', // Fails, you told "baz" would be a number in State type
      other: true, // Fails, you told there will only be "baz" and "nullable" in State type
    });
  }

  componentWillReceiveProps(nextProps: Props) {
    this.props.baz; // Fails, you told there will only be "foo" and "bar" in Props type
    nextProps.baz; // Fails for the same reason

    const mustPassString = (str: string) => console.log(str);

    mustPassString(this.state.nullable); // Fails, "nullable" can be string, null or undefined

    if (typeof this.state.nullable === 'string') {
      mustPassString(this.state.nullable); // Cool!
    }
  }
}

const a = <MyComponent bar={() => null} />; // Fails, needs "foo"
const b = <MyComponent foo="Test" bar={() => null} baz={13} />; // Fails, "baz" shouldn't be here
const c = <MyComponent foo="Test" bar={() => null} />; // Cool!
```

You can use Nuclide to see errors in Atom:
```bash
git clone git@github.com:facebook/nuclide.git
cd nuclide
npm install
apm link
```

**Comment by mqklin** [comment]
Flow is nice, but it can't check in runtime (yeah I know about `flow-runtime` but it was opensourced just 5 days ago...), moreover Flow can't mix with ES6 destructing feature (`const { prop: string } = obj;` is invalid), it can't check props that was passed through tangled HOC component (redux-form `Field` eg) etc...
So the only option for me is to check `react-strict-prop-types`, I just want to keep my code clean.

**Comment by mqklin** [comment]
`react-strict-prop-types` doesn't support recursion (eg for `PropTypes.shape`) :(

**Comment by mqklin** [comment]
Solution: https://github.com/airbnb/prop-types (`forbidExtraProps`)

**Comment by gajus** [comment]
> react-strict-prop-types doesn't support recursion (eg for PropTypes.shape) :(

PR welcome.

**Comment by aweary** [comment]
PropTypes have been removed from React core and now exist as a separate package `prop-types`. Any future feature requests, bug reports, or changes should be directed to the new repo at https://github.com/reactjs/prop-types.

**Comment by aweary** [comment]
I've opened a new issue for this at https://github.com/reactjs/prop-types/issues/11 for anyone looking to continue this discussion.
