### ISSUE TITLE
useEffect fires at initial render

### ISSUE THREAD

**Issue by furkanedu** [facebook/react#15873]
When you use useEffect with second parameter different than [], what you expect is it to fire when that variable changes. Not at the initial render. If someone wants something to fire at initial render, they can use with second parameter equal to [].

For the following case:

```
useEffect(
  () => {
   //
  },
  [someParam]
)
```

I don t expect it to run for the initial render. 

Can React provide any solution to this problem?

**Comment by raix** [comment]
I would say that is expected - but other frameworks have a `firstRun` boolean value to indicate if it's the first computation run

**Comment by nmain** [comment]
You can certainly roll your own helper hook that does this, by using some combination of `useEffect` and `useRef` to track first time.

But, the current behavior is the intended one.

**Comment by threepointone** [comment]
^ like they said, you'd have to roll your own solution. Feel like this is more of a question for a support channel, closing.

**Comment by furkanedu** [comment]
@nmain I see your point. But I asked for it because I think it is not expected. Since the second param without being an empty array, intended behavior is it to be fired when the provided param changes. 

What is your point about it to be intended?

**Comment by nmain** [comment]
Check out the official hooks docs, they should make it more clear: https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect

**Comment by brayanL** [comment]
useEffect is confusing, @threepointone if you are working with Facebook team, you should provide a better answer instead close this issue. React team seems determined to make things more difficult.

**Comment by code-angels** [comment]
React is fantastic but this is terrible. 
The following StackOverflow offers a logical solution, but I decline its use: 
https://stackoverflow.com/questions/53351517/react-hooks-skip-first-run-in-useeffect/53351556

This clutters the code in horrible ways. 
Should be pretty clear it's better to find a concise but solid solution offered by the api.

**Comment by CodePint** [comment]
Also ran into this when learning react.
The suggestion to roll your own solution is tedious/messy and an avoidable source of bugs.

Why not just make the SO solution a built in hook or allow an argument to be passed if the effect should not be fired on initial rende.

**Comment by akashmugu** [comment]
You can write a custom hook very easily. And replace useEffect by useDidUpdateEffect.
``` js
function useDidUpdateEffect(fn, inputs) {
  const didMountRef = useRef(false);

  useEffect(() => {
    if (didMountRef.current)
      fn();
    else
      didMountRef.current = true;
  }, inputs);
}
```

Source: https://stackoverflow.com/a/53180013/2838598

**Comment by CodePint** [comment]
I did something quite similar, Can't remember where I saw the code originally or if I rewrote something from SO

I still think, building this into react would be very useful.

`import React, { useRef, useEffect } from "react";

function useIsFirstRender() {
  const isRenderRef = useRef(true);
  useEffect(() => {
    isRenderRef.current = false;
  }, []);
  return isRenderRef.current;
}

export default useIsFirstRender;
`

**Comment by pycraft114** [comment]
I do not get the point of setting a state value initially like so if useEffect gets called initially even tho it's dependency does not change.

`const [workoutType, setWorkoutType] = useState<string>(props.workoutType); // Setting workout type as what it received from the props initially

  useEffect(() => {
    console.log('workoutType', workoutType); // useEffect gets called initially and thus log props.workoutType.
  }, [workoutType]);`
  
React docs states 
useEffect determines whether to skip it or not depending on its dependency change.

if making an useEffect to not run initially a developers role why pass a parameter to useState at the first place?

``
const useIsMount = () => {
  const isMountRef = useRef(true);
  useEffect(() => {
    isMountRef.current = false;
  }, []);
  return isMountRef.current;
};

useEffect(() => {
    if (isMount) {
      console.log('First Render');
      setWorkoutType(props.wokroutType) // you could just set initial value here
    } else {
      console.log('Subsequent Render');
    }
  });
``

useEffect running initially despite of it ignoring dependency changes does not assure 'useEffect will be called when its dependency changes and skips if not'

**Comment by ravithejappl** [comment]
> ^ like they said, you'd have to roll your own solution. Feel like this is more of a question for a support channel, closing.

This is very basic for any library, you can add this, why are feeling shame getting good suggestions from community!
