### ISSUE TITLE
Inheriting components

### ISSUE THREAD

**Issue by janibhautik** [facebook/react#15876]
Please consider the following case:

I have created a "baseUser" component which is a form having three fields username, password, and name. Now I want this form in three different applications: Application1, Application2, and Application3.

1. In Application1, User component should use this baseUser component but want only two fields (username, password) from baseUser state and should also have two additional fields which are first-name and last-name. 
2. In Application2 and Application3, the User component should work the same as the baseUser.
3. Also all the actions, events, states should be able to work alone and be able to override.

The render method should also be overridden as there can be different UIs for different applications. 

How can we achieve this functionality using react components? Does inheriting "baseUser" in applications using "extends" cause any issue (Or is it the correct way to do it)?

**Comment by AndreiCalazans** [comment]
@janibhautik your question would be more appropriately placed in https://stackoverflow.com/ instead
