### ISSUE TITLE
Erroneous useEffect conditional call error

### ISSUE THREAD

**Issue by synzen** [facebook/react#15881]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
React gives an error about `useEffect` being called conditionally when it actually isn't. ~~Modifying a local object variable within a loop seems to be triggering it.~~
```
React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return? react-hooks/rules-of-hooks
```
**Demo**

https://codesandbox.io/s/epic-meadow-eji2l

**What is the expected behavior?**
It should not give any errors about conditional calls of `useEffect` since it's not being called conditionally

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v16.8.6 / Chrome / Windows, unknown

**Comment by sinh117801** [comment]
normally, useEffect() might fire when useState have been use. Like normal class component, when one assign value to local variable, the component don't re-render.

I hope my opinion help u for the issues

**Comment by jahed** [comment]
From my understanding, the linter error is correct, but the message isn't helpful.

The loop before `useEffect` can potentially be iterated any number of times, and within it, another hook might be used which will cause React to lose track of which hook maps to which call in the next render call.

In your specific scenario, it's over a fixed number (zero) so it's a false positive, but the general rule still applies: don't use hooks after conditionals and iterations.

If you need to, then pull out part after the iteration (the effect and returned element) into its own component so that React can track them separately. Alternatively, if it makes sense, move the iteration into the effect.

**Comment by synzen** [comment]
If this is intended behavior, then that's a bit silly. Giving an _error_ (not a warning) about a hook being called conditionally only because it's after a loop that has the potential to contain a hook rather than actually containing one, despite there being no change in the order of hook calls (was very frustrating to debug upon first encountering this).

In any case I don't believe that is the case. I should've put more emphasis on it but it's not the actual _loop_ causing the error to show up, but the modifying a local JS object is triggering it. If you replace the object in the sandbox with an array, and instead push items into the array within the loop, the error disappears. Here's another sandbox:

https://codesandbox.io/s/festive-ride-p2mis

You can also replace the problematic object variable with a string, and concatenate to the string in the loop - the error also disappears in that case. So something about modifying an object is causing it.

**Comment by jahed** [comment]
You're right. Looks like rules-of-hooks is able to determine improper use of hooks within loops and conditionals, so doesn't make sense for it to be flagged afterwards.

It's not the object modification triggering it. Looks like it's specifically the `else` inside a loop.

https://codesandbox.io/s/late-sky-lopeh

Moving the loop into its own function prevents the error. So it may be an issue with the code path calculations here:

https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L405

There's a "Special case when we think there might be an early return.", and there's a few "possiblies" and "might", so the detection likely needs improving. Don't know how myself as I haven't dealt with ESLint rules and ASTs before.

**Comment by FabianoLothor** [comment]
Any help for here? Same issue.

**Comment by gaearon** [comment]
I believe the latest ESLint plugin version fixes it, not deployed on CodeSandbox yet though.

**Comment by TomJSmith** [comment]
This is still an issue and a big annoyance. Seems like eslint will throw the conditional hook usage error if there are a certain number of conditionals (including use of `??`) before the use of a hook

**Comment by j3r3myp1pp3n** [comment]
I have this file that did not have this error, but after I add two new inputs in the return statement, I get this error. No changes to useEffects, no loops, no hooks in an if statement, nothing stands out as an issue. Very annoying.
