### ISSUE TITLE
eslint-plugin-react-hooks: rule fix drops dots from rest parameters

### ISSUE THREAD

**Issue by Satyam** [facebook/react#15884]
(Sorry for the multiple edits, but the template really confused me)

Bug:

When having a variable number of arguments, such as this sample

```js
function useSomething(fixedArg, ...args) {
  //Somewhere inside:
   return useMemo(() => /* doSomething */, [fixedArg, ...args])
}
```
The eslint plugin fixes it to:

```js
function useSomething(fixedArg, ...args) {
  //Somewhere inside:
   return useMemo(() => /* doSomething */, [fixedArg, args])
}
```

This is not correct.  The dots on the rest of the arguments should not be dropped, as the dependencies to be compared are the contents of that array (the values passed), not the array itself.   I don't know how the *rest parameters*  array is assembled by the JavaScript interpreter but my guess it is dynamically assembled, meaning there is a new one every time, which would fail a shallow equality comparison, even when the arguments themselves remain the same.

**Comment by fboechats** [comment]
Can you provide more info?? So I can try to reproduce here and see what can be done??

**Comment by Satyam** [comment]
My actual code is here: https://github.com/Satyam/lacorazon/blob/master/src/store/useSel.js .  I use that to generate cached selectors to be used with react-redux hooks.  It processes selectors in either of these two formats, as shown here:  https://github.com/Satyam/lacorazon/blob/master/src/store/users/selectors.js .

For the purpose of testing, the referenced code can be simplified to:

```js
import { useSelector } from 'react-redux';
import { useMemo } from 'react';

export function useSel(selector, ...args) {
  return useSelector(
    useMemo(
      () => selector(...args),
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [...args, selector]
    )
  );
}
```
 The problem is with the dependencies where, in VsCode with Prettier and auto-fix, it will drop the dots on `...args` in the selector.

The eslint plugin should not care whether the dependencies listed are spread out or not, as long as they are there.  Since the `..args` array is assembled on the fly, it will always be a new array, and I guess it will always fail the check and force a recalculation.  Anyway, the plugin doesn't need to check where `...args` comes from, as long as there is an `args` dependency, it should not mind it it is spread out or not.

I don't think you need to run the whole application, just doing the linting with auto-fix will reproduce it. The application works either way, it just skips the memoizing as the dependencies change all the time without the dots.

**Comment by fboechats** [comment]
Understand, I guess the easier way is to disable the rule.

**Comment by Satyam** [comment]
Sure, I might also not use eslint, why bother.  
I could pass the `args` dependency but that is not correct. I have to pass `...args`, which it does autocorrect, and that is an error.

**Comment by greypants** [comment]
I ran into this problem as well:

```js
import { useCallback } from "react";

export const useCombineRefs = (...refs) => {
  return useCallback(
    el => {
      refs.filter(Boolean).forEach(ref => {
        if (typeof ref === "function") {
          ref(el);
        } else {
          ref.current = el;
        }
      });
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    refs
  );
};
```

Without disabling the rule for the line, `refs` gets re-written to `[refs]`. `[...refs]` also gets re-written to `refs`.

**Comment by gaearon** [comment]
Maybe we need to be more explicit in the message, but generally we don't recommend APIs that dynamically combine dependencies. It's pretty hard to do correctly. (For example, it's not supported to have `deps` of different lengths between renders, but it's easy to do that mistake if you pass them through and combine them at multiple levels).

**Comment by greypants** [comment]
Ah, that make total sense. Sorry I missed that. I could refactor this to only take two arguments, as that meets 99.9% of the use case. The .01% could be handled by composing `useCombineRefs`, or with something custom.
