### ISSUE TITLE
memo components show as Unknown in the timings section of Chrome

### ISSUE THREAD

**Issue by xaviergonz** [facebook/react#15897]
**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**

Given a component like

```
export const MyComponent = (p) => {...};
MyComponent.displayName = "MyComponent";
```
it shows properly as
![image](https://user-images.githubusercontent.com/6306796/56823548-79b5a600-6854-11e9-8371-a49d7ad5e5b4.png)

but as soon as memo is added
```
export const MyComponent = memo((p) => {...});
MyComponent.displayName = "MyComponent";
```
it shows as Unknown instead
![image](https://user-images.githubusercontent.com/6306796/56823576-92be5700-6854-11e9-8aea-8660277e36e2.png)

Note that both actually show properly on the tree explorer, the issue is only in the timings section of a performance recording in chrome.

**What is the expected behavior?**

It should show the proper name on the timings when memo is used

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Windows 10, Chrome 74, React 16.8.x (the latest version that was available on April 26)

This issue got copied from react devtools repo since @bvaughn suggested it was actually a react bug
https://github.com/facebook/react-devtools/issues/1340

**Comment by eps1lon** [comment]
This should be covered by #15313

**Comment by alflennik** [comment]
I just ran into this issue - it is still occurring and should be reopened. The linked PR also hasn't yet been merged!
