### ISSUE TITLE
Behavior intermediate state in useEffect

### ISSUE THREAD

**Issue by zaytsevyura** [facebook/react#15903]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I have some issue about useEffect hook.
In my application i use redux, and when i begean to use react hooks, i encountered the following problem, for example:
1. In the main page (home root) i need to get list of posts.
Earlier i used in componentDidMount dispatch to redux and with redux-saga get data form server
Now i do the same but in useEffect
2. When i click on some post I have to go to the post page (change routing like to /post/:id)
Notice: in this step (in my store i already have list of all posts)
When i returned to main page i see a flicker that is due to the fact that store already have posts list and he render them, after which it is called useEffect and we do dispatch again to get data form server and updtate store (posts and component).

**What is the expected behavior?**
With сomponentDidMount no such problem  -  the user can't see the intermediate state.
For solution this problem i see two ways: the first in useEffect on unsubscribe function call action for reset list posts in store. The second way it's use useLayoutEffect instead useEffect.
But I'm not sure that these is the right decisions. Are there other right solutions ? Can i do useEffect like componentDidMount, to user won’t see the intermediate state ?

**Comment by malerba118** [comment]
Could you do something like this where if data is present, you show it regardless of the loading state. But then if it's the first fetch (empty list and loading state) show a spinner covering the whole content area. But if it's a refetch (nonempty list and loading state) show some sort of tiny refetch spinner along side the cached list.

```jsx
<div>
  {posts.length === 0 && loading && <PageLevelLoader />}
  {posts.length > 0 && loading && <RefetchIndicator />}
  <Posts posts={posts} />
</div>
```

**Comment by zaytsevyura** [comment]
Yes, the problem is in the second stage, when data already exists in the storage after the first mounting (when data was received from the server and stored in the store)
useEffect will be called after render wich showing first prev state of posts after that will be called dispatch to change loading to true and get data from server again.
The behavior will be next:
<div>
  {posts.length === 0 && loading && <PageLevelLoader />}
  {posts.length > 0 && loading && <RefetchIndicator />}  // 2 useEffect will call dispatch and loading will be set to true 
  <Posts posts={posts} />   // 1 - first with old data of posts; 3 - with new data form store after dispatch
</div>

But the problem remains, we still see in one second two renderings (with previous state of posts and new)
