### ISSUE TITLE
[Feature] Export useBox primitive as a replacement for useRef for instance variables

### ISSUE THREAD

**Issue by atomiks** [facebook/react#15901]
**Do you want to request a *feature* or report a *bug*?**
Feature

Note that this is already possible with the primitives React provides. I'm suggesting to export this as a new primitive specifically designed for instance variable usage, instead of `ref` (which doesn't act as nicely as a `box` does.)

**What is the current behavior?**

Having to access `.current` is easily forgotten when using refs as instance variables in function components, and not developer-friendly:

```jsx
function thirdParty(node, options) {
  // Some effect
  return () => {
    // Undoes the effect
  };
}

function App({prop}) {
  const ref = useRef();
  const thirdPartyRef = useRef();

  useEffect(() => {
    thirdPartyRef.current = thirdParty(ref.current, {prop});
    return () => {
      thirdPartyRef.current();
      // And if .current was an object? The `.current` property is still annoying!
      // thirdPartyRef.current.unsubscribe = () => {};
      // thirdPartyRef.current.unsubscribe();
    };
  }, [prop]);

  return <div ref={ref}>text</div>;
}
```

It's fine when `ref.current` is always a DOM node, but for instance variables, it's unfriendly. With a generic `box` hook, it acts like `this`, and you can place any name on the box you want without the `current` property getting in the way:

```jsx
function App({prop}) {
  const ref = useRef();
  const box = useBox();

  useEffect(() => {
    box.unsubscribe = thirdParty(ref.current, {prop});
    return () => {
      box.unsubscribe();
    };
  }, [prop]);

  return <div ref={ref}>text</div>;
}
```

Now imagine if `thirdParty` returned a plain instance object:

**useRef** (current API)

```jsx
function App({prop, enabled, visible}) {
  const ref = useRef();
  const thirdPartyInstance = useRef();

  useEffect(() => {
    thirdPartyRef.current = thirdParty(ref.current, {prop});
    return () => {
      thirdPartyRef.current.destroy();
    };
  }, [prop]);

  // other effects need to use `.current`
  useEffect(() => {
    // You could destructure and assign `current` to a new
    // variable, but that's cumbersome for each new effect
    thirdPartyInstance.current.setProps({prop});

    if (enabled) {
      thirdPartyInstance.current.enable();
    } else {
      thirdPartyInstance.current.disable();
    }
    
    if (visible) {
      thirdPartyInstance.current.show();
    } else {
      thirdPartyInstance.current.hide();
    }
  });

  return <div ref={ref}>text</div>;
}
```

**useBox**

```jsx
function App({prop, enabled, visible}) {
  const ref = useRef();
  const thirdPartyInstance = useBox();

  useEffect(() => {
    Object.assign(thirdPartyInstance, thirdParty(ref.current, {prop}));
    return () => {
      thirdPartyInstance.destroy();
    };
  }, [prop]);

  useEffect(() => {
    thirdPartyInstance.setProps({prop});

    if (enabled) {
      thirdPartyInstance.enable();
    } else {
      thirdPartyInstance.disable();
    }
    
    if (visible) {
      thirdPartyInstance.show();
    } else {
      thirdPartyInstance.hide();
    }
  });

  return <div ref={ref}>text</div>;
}
```

Now other effects and pieces of code can access `thirdPartyInstance` like it was re-rendered using a `useState` setter (closure), but obviously, without actually re-rendering the UI.

---

Boxes would probably just be called `box` / `_this` / `self`, as another name for `this` in most cases for primitive values and any other things.

```jsx
function App() {
  const box = useBox({
    passes: 0
  });

  useEffect(() => {
    box.timeout = setTimeout(() => {});
    box.passes++;
    return () => clearTimeout(box.timeout);
  });

  return null;
}
```

### Implementation

```js
function useBox(initialValue = {}) {
  const ref = useRef();

  // Primitives can't be allowed
  if (!ref.current) {
    ref.current =
      typeof initialValue === 'function' ? initialValue() : initialValue;
  }

  return ref.current;
}
```

The name is not final, something @aweary mentioned on Twitter (along with "cell")

**Comment by probablyup** [comment]
Seems like `useState` initialized to an object works just as well?

**Comment by atomiks** [comment]
It does, but destructuring the useState return value without the setter is strange, especially when state is meant to be updated via the setter and not mutating properties on the object. It would be better to have an official API. 

And it's interesting how the React team encourages using refs for instance variables in the docs when the ergonomics is not great, considering there's other possible alternatives that work currently.  e.g. I didn't really consider alternatives because the docs already taught me that refs = instance variables for function components, and I didn't bother questioning it, until the `current` property annoyed me enough..

**Comment by kunukn** [comment]
Maybe we could create a custom hooks that mimics `useBox`?

Not tested, but I am thinking something like this.

```jsx
function useBox(){
  return React.useRef({}).current;
}
```

**Comment by atomiks** [comment]
@kunukn  See `Implementation` section in original post 😛 

Also as @probablyup said, you can useState:

```js
function useBox(initialValue = {}) {
  return useState(initialValue)[0];
}
```

I did some searching about this and found the same thing here: https://github.com/donavon/use-instance

The point of this issue is to make it official and teach people this method instead of `ref` though.

**Comment by kunukn** [comment]
I would prefer to call it something else. Maybe `useIntance`. I agree that the `.current` thing can be wordy and confusing at times. I got used to it, or made a custom hook.

I would be concerned with adding more stuff to the React API if the method are very similar. 
I am more into using hooks patterns and keep the hooks API to a minimum. 
But that is just my opinion.

**Comment by gaearon** [comment]
It’s intentional that `current` isn’t super convenient to type because it’s an escape hatch for imperative code. Overusing it leads to fragile patterns and we’d like people to think twice before adding it. There are of course cases where you can’t avoid it — but we’d like to avoid making it even easier to add than now.

If you see yourself writing a “ref soup” a nice solution can be to write your own class that encapsulates the imperative behavior — and then use a ref to that class. Or a custom Hook indeed.

**Comment by atomiks** [comment]
So `dangerouslySetInnerHTML={{html: value}}` 2.0?

I mean, I guess, but it would also be useful to point to this alternative on the docs at least.
