### ISSUE TITLE
Suspense + Concurrent Mode immediately shows fallback when updated from onChange

### ISSUE THREAD

**Issue by antimatter15** [facebook/react#15900]
**Do you want to request a *feature* or report a *bug*?**

Reporting a bug, or at least trying to understand some spooky behavior 👻

**What is the current behavior?**

I have a simple component which reads from a toy suspense-enabled cache. The dummy cache simply waits 100ms before responding to anything.  The cache key is based on some component state (managed with the useState hook). This component is wrapped with `<Suspense>` and rendered in a React root with concurrent mode enabled. 

```javascript
function MyApp(){
    let [text, setText] = React.useState('stuff')
    return <div>
        Data: {readCacheSuspense(text)}
        <button onClick={e => setText('B-A-N-A-N-A-S')}>Update text from button</button>
        <input type="text" value={text} onChange={e => setText(e.target.value)} />
    </div>
}

ReactDOM.unstable_createRoot(document.getElementById('root')).render(<React.Suspense fallback={<div>cause i ain't no fall-a-back div</div>}>
    <MyApp />
</React.Suspense>)
```

The component has a text field whose value is set to the current cache key (with an onChange handler that updates the useState hook when the text changes). It also has a button which updates the state to some fixed string "asdf" when clicked. 

Clicking the button does what I would expect— the page doesn't respond for a fraction of a second (while the data is being "fetched") and then updates with a view of the loaded data. 

**Editing the text however (for instance, typing a single letter in the field) immediately causes the fallback UI to load and unfocuses the text input**. This happens even if the `setTimeout` is changed to 0ms, or `requestAnimationFrame`, or a `setImmediate` polyfill. 

Rather than directly calling `setText` within the `onChange` handler— if I call it within a `setTimeout(..., 0)`, it behaves the way I would expect (i.e. without unfocusing the field and loading fallback). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://codesandbox.io/s/competent-goldwasser-yhmxo

**What is the expected behavior?**

I would expect that it shouldn't really matter whether I'm updating state from an `onChange` versus an `onClick`. 

I would expect that the fallback UI doesn't show up until its max duration is met.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm using React 16.8.6. I tested it on Chrome 75 on macOS 10.14.

**Comment by gaearon** [comment]
Does this happen with a build from master? There were a lot of behavior changes for unstable APIs so I'm not sure what's the latest behavior here.

**Comment by antimatter15** [comment]
For 16.9.0-alpha.0, both the `onClick` handler and `onChange` flash the fallback UI.

For a build from master, it behaves the same way as React 16.8.6 Stable (`onClick` doesn't flash fallback, and `onChange` does).

**Comment by gaearon** [comment]
Seems legit. Updates to things like text input *should* be synchronous. For the rest of the UI, you can `useTransition` or `useDeferredValue`. See Concurrent Mode docs for details.
