### ISSUE TITLE
pass an object as a prop 

### ISSUE THREAD

**Issue by roggc** [facebook/react#15914]
**Do you want to request a *feature* or report a *bug*?**
request a feature
**What is the current behavior?**
you cannot pass an object as a prop in react, at least i don't know how
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6 and chrome

**Comment by xdavipereira** [comment]
Yes you can.

You can pass objects, string and any type of data.

Take a look on this docs. It is the better place to undersand how pass props to component and how  works.


https://reactjs.org/docs/components-and-props.html

**Comment by roggc** [comment]
so i will reproduce exactly my scenario where this doesn't work. 
i do this:
`  <BrowserRouter>
    <Route path="/" exact render=
    {
      ()=>
      <Header props2={{message:'hello'}}/>
    }
    />
  </BrowserRouter>`

and then this in the header component:

`export default
({props2:{message}},...rest)=>
<div className={`${style.border}`}>
  <div>{message}</div>
  <div className={style.menu}>
    <div>
      <i className="fas fa-bars"></i>
    </div>
  </div>
</div>`

and recive this server side rendering code:

`TypeError: Cannot read property 'message' of undefined
    at __webpack_exports__.default (webpack:///./src/comps/test2/test2.jsx?:9:29)
    at processChild (/Users/rog_gc/Dev/react/dolphin/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/Users/rog_gc/Dev/react/dolphin/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/rog_gc/Dev/react/dolphin/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/rog_gc/Dev/react/dolphin/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Users/rog_gc/Dev/react/dolphin/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at ssr (webpack:///./src/ssr/ssr.js?:24:84)
    at Layer.handle [as handle_request] (/Users/rog_gc/Dev/react/dolphin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rog_gc/Dev/react/dolphin/node_modules/express/lib/router/index.js:317:13)
    at /Users/rog_gc/Dev/react/dolphin/node_modules/express/lib/router/index.js:284:7`

maybe it's something related to ssr and react-router-dom then. i will check without of them. thanks

**Comment by matvp91** [comment]
Your code in the `Header` component is invalid, you're not returning a valid value.

```javascript
export default ({ props2 }) => props2.message;
```

**Comment by roggc** [comment]
i don't know why but it was no  pasted well. the code in the header is this:

`export default
({props2:{message}},...rest)=>
<div className={`${style.border}`}>
  <div>{message}</div>
  <div className={style.menu}>
    <div>
      <i className="fas fa-bars"></i>
    </div>
  </div>
</div>`

**Comment by universse** [comment]
Your destructuring syntax is a bit off. It should be like this
```javascript
({ props2: { message }, ...rest }) => ...
```

**Comment by numbing** [comment]
of course, you can send object as a props to child component

**Comment by roggc** [comment]
yes. that's correct. the problem arises with react-router-dom and server side rendering. i opened an issue for this question (another one). when you do ssr and use react-router-dom, the problem with passing an object with props as a prop arises. it only renders last prop of the object, but not all of the props.

**Comment by threepointone** [comment]
We cannot investigate this further without a reproducing example, please use codesandbox to reproduce the issue you're having, and share the link here.

**Comment by threepointone** [comment]
In fact, this seems more like a usage issue, so I would instead recommend you use a community resource https://reactjs.org/community/support.html
