### ISSUE TITLE
the chrome version cause -- Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by wind4gis** [facebook/react#15913]
**Do you want to request a *feature* or report a *bug*?**
no
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.8.6,  chrome: Version  75.0.3770.90(Official Build)  (64 -bit),  win10

I found that in the chrome: <b>Version  75.0.3770.90(Official Build)  (64 -bit)</b>, react hook app will throw error <b>when you open the dev tool</b> -- `Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.`

however, <b>with chrome canary and other version chrome</b>, it work well !!

![image](https://user-images.githubusercontent.com/3963291/59680014-ec168700-9202-11e9-8b94-e77e2d706d33.png)

**Comment by wind4gis** [comment]
e...I found this to be not a browser version issue. it's because the chrome mobile debug mode, when I choose the Predefined iphone or ipad size, the chrome show the error, when I choose others, it don't happen...
![image](https://user-images.githubusercontent.com/3963291/59734310-8f0ee580-9283-11e9-80a6-97755a702448.png)

**Comment by threepointone** [comment]
It's not possible to investigate this further without a reproducing example on codesandbox, or as a git repo. I'm closing this issue, but I'll be happy to reopen it if you can provide an example showing it failing.
