### ISSUE TITLE
Minified React error #168;

### ISSUE THREAD

**Issue by JiayiLi** [facebook/react#15920]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
There are a lot of error logs about "Minified React error #168; "
I saw the link about [Minified React error #168; ](https://reactjs.org/docs/error-decoder.html/?invariant=168) , and it said 
> This error is likely caused by a bug in React. Please file an issue.

so should i ignore them or react already fixed it so i should update the version?

Thanks for your time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by threepointone** [comment]
Can’t say without an actual usecase/reproduction. In dev mode, you should see the actual error.

**Comment by necolas** [comment]
We can reopen if a reduced test case or sufficient additional information is provided
