### ISSUE TITLE
ReactDOM.render ignores RGBA border color in test environment

### ISSUE THREAD

**Issue by yuliya-ivaniukovich** [facebook/react#15925]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

In test environment `ReactDOM.render` skips border declaration if RGBA color was used in it, see test sample below. In e.g. `backgroundColor` RGBA works as expected, also border is OK in browser.

The issue also affects Enzyme's `.html()` behavior since it rely on `outerHTML` of an element.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Simple test was made in standard react-app created using create-react-app utility:

```
it('test border color', () => {
    const domNode = document.createElement('div');
    ReactDOM.render(<div style={{border: '1px solid rgba(0, 0, 125, 1)', backgroundColor: 'rgba(0, 0, 125, 1)'}}>Test</div>, domNode);
    expect(domNode.innerHTML).toEqual('<div style="border: 1px solid rgb(0, 0, 125); background-color: rgb(0, 0, 125);">Test</div>');
});
```

Test fails because actual style attribute contains no border declaration:

```
Difference:

- Expected
+ Received

- <div style="border: 1px solid rgb(0, 0, 125); background-color: rgb(0, 0, 125);">Test</div>
+ <div style="background-color: rgb(0, 0, 125);">Test</div>
```

**What is the expected behavior?**

Test above should pass.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react-dom@16.8.6, jsdom@11.12.0

**Comment by gaearon** [comment]
React has no special logic for rgba so I suppose this is a jsdom issue.
