### ISSUE TITLE
Some suggestions for the Docs

### ISSUE THREAD

**Issue by mvslan** [facebook/react#15932]
I think there should be some **links** with the likely knowledge,ex:
https://reactjs.org/docs/state-and-lifecycle.html(about  State and Lifecycle ) can get a link to
https://reactjs.org/docs/react-component.html (react:react-component)
because they are all about Lifecycle, and i can find what i want when i read about them faster!

**Comment by threepointone** [comment]
Noted. While it’s searchable via google, and the component page does its job well, we might setup aliases/redirects in the future.
