### ISSUE TITLE
[bug] Get useState always initial

### ISSUE THREAD

**Issue by six-666** [facebook/react#15933]
```jsx
import React, { useState, useEffect } from 'react';

const Demo = function () {
  const [count, setCount] = useState(0);

  function init() {
    setCount(999);
    query();
  }

  function query() {
    console.log(count);   // Why 0 ？ Should be = 999
  }

  useEffect(() => {
    init();
  }, []);

  return (
    <div></div>
  )
};


```

**Comment by dmytro-lymarenko** [comment]
Because you didn't provide any dependency for useEffect. That should be like this:
```js
import React, { useState, useEffect, useCallback } from 'react';

const Demo = function () {
  const [count, setCount] = useState(0);

 const query = useCallback(() => {
    console.log(count);   //count should be = 999 here
  }, [count]);

  const init = useCallback(() {
    setCount(999);
    query();
  }, [setCount, query]);

  useEffect(() => {
    init();
  }, [init]);

  return (
    <div></div>
  )
};
```

**Comment by threepointone** [comment]
Also of note that setCount doesn’t ‘immediately’ set values, much setState. Closing.

**Comment by six-666** [comment]
> Because you didn't provide any dependency for useEffect. That should be like this:
> 
> ```js
> import React, { useState, useEffect, useCallback } from 'react';
> 
> const Demo = function () {
>   const [count, setCount] = useState(0);
> 
>  const query = useCallback(() => {
>     console.log(count);   //count should be = 999 here
>   }, [count]);
> 
>   const init = useCallback(() {
>     setCount(999);
>     query();
>   }, [setCount, query]);
> 
>   useEffect(() => {
>     init();
>   }, [init]);
> 
>   return (
>     <div></div>
>   )
> };
> ```

query function is HTTP request, Do not want to execute twice.

**Comment by six-666** [comment]
> Also of note that setCount doesn’t ‘immediately’ set values, much setState. Closing.

So how to get the new count value ？

**Comment by dmytro-lymarenko** [comment]
@six-666 sorry, in
```js
 const init = useCallback(() {
    setCount(999);
    query(); // <-- you don't need to call this
  }, [setCount, query]);
```

and to get new count you just do this:
```js
useEffect(() => {
  // This code will be run every time count is changed
  console.log(count); // or any other manipulation like HTTP request
}, [count]);
```
