### ISSUE TITLE
how to find out where inline style come from

### ISSUE THREAD

**Issue by craigcosmo** [facebook/react#15945]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

how to find out where inline style come from

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

init a create react app project

create a simple component 
```js
// body component
import React from 'react';
const css ={
	body :{
		backgroundColor:'red',
	}
}
export default function Body() {
	return (
		<div style={css.body}>
		</div>
	);
}
```
run the app, inspect the style in dev tool. you see some thing like his

<img width="436" alt="Screen Shot 2019-06-21 at 12 10 56 PM" src="https://user-images.githubusercontent.com/538657/59899294-7129b800-941e-11e9-97b7-d710f94e6156.png">

notice the 
```css
element.style {
flex: 1 1 0%,
}

```

There should be an indicator where that style come from, so we can debug it if it was written by some one else

**What is the expected behavior?**

there should  be an indicator show which file/component where the style come from

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 16.8.6
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0.2
    Safari: 12.1.1

**Comment by necolas** [comment]
I can't reproduce the styles you see from the code you shared. Without a test case there's not enough information in this report.

**Comment by craigcosmo** [comment]
@necolas I published a repo for reproducing

https://github.com/craigcosmo/my-app1.git

**Comment by necolas** [comment]
Please host the test case on codesandbox

**Comment by necolas** [comment]
Oh, now that you've updated the OP it's clear what you mean. The inline style is defined in the component rendering the div, you can see which component that is by using React Dev Tools
