### ISSUE TITLE
Problem with refreshing initial state when props change

### ISSUE THREAD

**Issue by AWielguszewski** [facebook/react#15948]
**My custom useReducer code**
```javascript
import { useReducer } from 'react'

interface ReturnType extends StateType {
  clear: () => void
  set: (input: File) => void
}
type ValidatorType = (input: File) => { error: boolean; message: string }
type InitializerType = (input?: File, validator?: ValidatorType) => StateType
type ReducerType = (input?: File, validator?: ValidatorType) => ReturnType
type StateType = {
  value?: File
  error: boolean
  message: string
  disabled: boolean
}
type ActionType = {
  type: string
  value?: File
}

const DEFAULT_VALIDATOR: ValidatorType = input => {
  if (typeof input !== 'object') return { error: true, message: 'Invalid file' }
  if (!('size' in input) || input.size > 500000) return { error: true, message: 'File too big (max 500kb)' }
  return { error: false, message: '' }
}
const SET: string = 'set'
const CLEAR: string = 'clear'

const setInitialState: InitializerType = (input = undefined, validator = DEFAULT_VALIDATOR) => {
  const { error, message } = input ? validator(input) : { error: false, message: '' }
  return {
    value: error ? undefined : input,
    error,
    message,
    disabled: !!error || !input
  }
}

const useImageState: ReducerType = (initial = undefined, validator = DEFAULT_VALIDATOR) => {
  const reducer = (state: StateType, action: ActionType): StateType => {
    switch (action.type) {
      case SET:
        const { error, message } = action.value ? validator(action.value) : { error: false, message: '' }
        return {
          value: error ? undefined : action.value,
          error,
          message,
          disabled: !!error || !action.value
        }
      case CLEAR:
        return {
          value: undefined,
          error: false,
          message: '',
          disabled: true
        }
      default:
        return state
    }
  }
  const [state, dispatch] = useReducer(reducer, setInitialState(initial, validator))
  const set = (input: File): void => dispatch({ type: SET, value: input })
  const clear = (): void => dispatch({ type: CLEAR })
  return { ...state, clear, set }
}

export default useImageState
```

**Usage example**
```javascript
export const SomeComponent = props => {
  const image = useImageState(props.initialImage)
  ...
}
```

**What happens**
When props change and initialImage is different, the custom useReducer is invoked twice:
- first with `undefined` as initialImage and returns `state.value = undefined` as expected
- second with `object` (proper File type) including all data needed but it still returns `state.value = undefined`. The `setInitialState` from the code above returns valid state with all the data but on this line => ` const [state, dispatch] = useReducer(reducer, setInitialState(initial, validator))` the state is still `{value:undefined, ...}`

**Expected behaviour**
I want the reducer to change its initial state properly when parent's props change

**My temporary solution**
In the `SomeComponent` i introduced `useEffect` with code: 
```javascript
useEffect(() => {
    if (props.initialImage) image.set(props.initialImage)
  }, [props.initialImage])
```
and it changed the state but the question is: 
Should i do it like that or should `useReducer` change its state when the initial value changes

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

This example is pretty dense and it's not clear what you're asking here, but it seems like a usage question. If you have a question like that, please check our [community support resources](https://facebook.github.io/react/community/support.html).

If you believe there's a bug here please provide [code that we can run](https://codesandbox.io/s/new) with a simplified example reproducing the problem.

Thanks!

**Comment by aweary** [comment]
> Should i do it like that or should `useReducer` change its state when the initial value changes

If you want to sync the `initialImage` prop with the state in `useImageState` then using an effect to explicitly update the state is likely what you want. Generally this _isn't_ what you want, so it's unlikely that we'd change `useReducer` to implement that behavior.
