### ISSUE TITLE
Effect does not run after each completed render

### ISSUE THREAD

**Issue by jschlieber** [facebook/react#15949]
**Do you want to request a *feature* or report a *bug*?**

Possible bug

**What is the current behavior?**

Effect does not run after every completed render in contrast to https://reactjs.org/docs/hooks-reference.html#useeffect

> By default, effects run after every completed render, but you can choose to fire it only when certain values have changed.

Reproduction Repo: https://codesandbox.io/s/render-without-effect-4ewx5

Steps to reproduce: Enter something into the input field. Then click outside to loose focus and check the console, which will read something like:

```
render "" false
***EFFECT*** 
onChange 
render a true
***EFFECT*** 
onBlur 
render a true
```

**What is the expected behavior?**

I would expect the effect to run after each completed render, i.e. also after the last render of the example above. Not sure if there would be any real use case, but I just came across this behavior and it seems to be a bit inconsistent (at least with the docs). So, IMHO either the last render call should not happen because neither props nor state changed, or the effect should be called after the final render.

(Note: If you click into the input field and then outside again, there will be no additional render)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: v16.8.6
Browser: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
OS: macOS Mojave

I did not test this in previous versions of React

**Comment by threepointone** [comment]
React's 'calling' of the component function doesn't always correspond to a 'render' or with running effects, React may call the function for different reasons. 

In your scenario, the blur handler calls `setTouched` with the value it already has `true`, and bails on doing another render since nothing's changed. 

closing this.
