### ISSUE TITLE
Portal and animations (and other side effects)

### ISSUE THREAD

**Issue by intellild** [facebook/react#15951]
**Do you want to request a *feature* or report a *bug*?**
Maybe feature ?

**What is the current behavior?**
```jsx
// the portal component
class Modal extends React.Component {
  constructor(props) {
    super(props);
    this.el = document.createElement('div');
  }

  componentDidMount() {
    modalRoot.appendChild(this.el);
  }

  componentWillUnmount() {
    modalRoot.removeChild(this.el);
  }

  render() {
    return ReactDOM.createPortal(
      this.props.children,
      this.el,
    );
  }
}

class Child extends Component {
  elRef = createRef();

  componentDidMount() {
    // some animations here
  }

  render() {
    return <div ref={this.elRef}></div>;
  }
}
```
`Modal`'s componentDidMount is fired after Child's componentDidMount. When Child performing animations, everything is not in the DOM tree, whitch causes problems.
Same issue with hooks. Same issue with other side effects related to Child's DOM.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Maybe provide a way to perform side effects before component mount, and guranteed clean up? For example:
```js
function App() {
  useSomething(() => {
    // called before mount, parent fires before child
    return () => {
      // called after unmount, child fires before parent
    }
  }, []);
}
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by sagar-gavhane** [comment]
+1
