### ISSUE TITLE
video element not rendering react chromium ubuntu

### ISSUE THREAD

**Issue by amishPro** [facebook/react#15958]
**Do you want to request a *feature* or report a *bug*?**
Yes.

**What is the current behavior?**

I have a problem with react not showing the video element. It shows it in the html document but it does not appear in the screen. If I use controls attribute the frame of the video will appear (the video player with controls) but the content will not be displayed (the video file). If I do not use the controls attribute it does not appears in the screen at all.

I have tested the video file within a plain html website and it works perfectly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
The video should appear in the screen.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  }

I have used npx create-react-app and I'm using ubuntu, chromium browser.

**Comment by thincamel** [comment]
...same issue ， react 15.5.4
