### ISSUE TITLE
question: why doesn't Javascript have optional static typing ? 

### ISSUE THREAD

**Issue by catastrop** [facebook/react#15969]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by TrySound** [comment]
Hi @catastrop. This question is not really related to react library. You may address it in one of tc39 repositories.

**Comment by catastrop** [comment]
@TrySound, let us do this
