### ISSUE TITLE
useState hook variable's value is always one step behind

### ISSUE THREAD

**Issue by marcosdipaolo** [facebook/react#15964]
Here using React and Next.js. 

Here a summary of the code:

I have this hook:
```javascript
import { useState } from 'react';
import BigCalendar from 'react-big-calendar'
import moment from 'moment';
import CreateEventForm from './CreateEventForm';

const localizer = BigCalendar.momentLocalizer(moment);

const Calendar = props => {

    const [newEvent, setNewEvent] = useState({
        start: new Date(),
        end: new Date(),
    });

    const onSelectHandler = info => {
        // logging the new info
        console.warn('New info: ', info);
        // assigning the new info to the hooks variable
        (setNewEvent(info));
        // logging the hook variable's value 
        console.warn('Hook variable\'s value: ', newEvent);
    }

}
```

There's actually nothing else to be told, when the handler is fired by an event, the variable `info` comes with an object on new information. Inmediately I log the information to the console to see that it is actually the correct and new info, i set the info to the hook's variable and inmediately log to the console the value of the hook's variable and it doesn't match the new info i just tried to assign to it. It's actually logs the default values (the 2 dates).
If I do it again, it happens the same but the hooks variable this time doesn't log the default, but the new info of the first try, so basically it's coming one time late every time.   

What could i have done to make this happen?

The event firing the handler is when i select a slot at the React Big Calendar
```javascript
const myEvents = props.events.map(event => {
        return {
            ...event,
            start: new Date(event.start),
            end: new Date(event.end)
        };
    });

            <BigCalendar
                defaultView="week"
                localizer={localizer}
                events={myEvents}
                startAccessor="start"
                endAccessor="end"
                selectable={true}
                onSelectSlot={onSelectHandler}
            />
```

**Comment by gaearon** [comment]
A `set*` function can't possibly reassign a variable in your local scope. Function components _capture_ props and state with which they were called.

Setting state will trigger a re-render. On next render, the state variable will have a new value, and the `onSelectHandler` event handler will "see" that value.

Hope that helps. If you have a concrete case where this is causing you troubles (aside from logging right after setting state — as I mentioned, it's not expected to work this way), please prepare an isolated sandbox.

**Comment by azamuddin** [comment]
```
function useBlueprint(){
  
  let [data, setData] = useState([]);
   let [query, setQuery] = useState({});

   const fetchData = (){
      // data fetching logic that consumes `query`      
      // and eventually use the result into setData(data)
   }

  const search = (query) => {
       setQuery(query);
       fetchData();
  }

  return [data, search];
}
```

It's an simplified example on a custom hook I made, on function `search()` the `fetchData()` called after `setQuery(query)`, but `fetchData` is still using the previous state `query` which is causing wrong fetching logic. Do you have any suggestion regarding this case?

**Comment by azamuddin** [comment]
Nevermind, i think there's a newbie problem to hooks here. I've got the solution, actually just `useEffect` to call `fetchData` and list `query` as the dependency list. Amazing hooks!
