### ISSUE TITLE
Old app with componentWillReceiveProps freezes browser, adding UNSAFE_ fixes it

### ISSUE THREAD

**Issue by lukemikael** [facebook/react#15979]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The app freezes the browser/tab for like 28 seconds until I changed maybe 20+ componentWillReceiveProps to UNSAFE_componentWillReceiveProps or used the codemod. The components with the method haven't been loaded yet, as It uses react-loadable, and is in a login component only. In chrome dev tools however, it stays a long time in a webpackerrormessage js file.

Just found it weird, it runs on my iMac immediately, but previously not on my 2nd gen i5 with 12gb of ram laptop, until I changed this, it's a large codebase btw, but still some mighty performance impact for an error message. Just wanted a heads up, some folks out there who ignore eslint warnings 😬 until its time to clean up the app might just ignore this casually, i dunno.

I only tested this on development, haven't tried doing a build with no sourcemaps to see if that is a problem too.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Tried doing some nested components with the lifecycle method in the sandbox, doesn't lag, so its probably with eslint-react?

**What is the expected behavior?**
Should have lagged with the aforementioned lifecycle method, but it probably doesnt since there's no eslint configured

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is on react 16.5.0, eslint 5.6.1

**Comment by threepointone** [comment]
This would be odd if true. It's hard to comment on this without a reproducing examples, please use codesandbox, or share a git repo that demonstrates the problem.

**Comment by threepointone** [comment]
I'm closing this issue, but I'll be happy to reopen if you can provide a reproducing example. Thank you!
