### ISSUE TITLE
Impossible to collect a stream of data using hooks

### ISSUE THREAD

**Issue by ma7moudat** [facebook/react#15973]
**Do you want to request a *feature* or report a *bug*?**

Bug (well, maybe not, but it's definitely a shortcoming!)

**What is the current behavior?**

It's impossible subscribe to a stream of data (e.g. observable) and collect the received values using the state and effect hooks

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/embed/romantic-hooks-h2jgt

In the example, the subject sends a number every second (from 1 to 10), and the code inside the useEffect hook should collect those values (so we should get a list with 10 numbers).

What currently happens is:

- when [] is passed as the second argument to useEffect (to avoid re-subscribing), only the last value will be saved to the component's state.
- otherwise, we got into an infinite loop the component collects the data erratically.

**What is the expected behavior?**

A list with the numbers 1 - 10 after 10 seconds.

**Comment by jquense** [comment]
you want to change the setData call to:

```js
 setData(data => [...data, nextValue]);
```

Otherwise if that's not feasible for whatever reason you could store the value of `data` in a `ref` and access it in the subscribe callback so that it stay's fresh

**Comment by ma7moudat** [comment]
@jquense my hero! thank you 🙌 
don't think I've seen this anywhere in the docs though!

**Comment by kunukn** [comment]
@ma7moudat 
That pattern is described in the docs here

https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often

> To fix this, we can use the functional update form of setState. It lets us specify how the state needs to change without referencing the current state:

**Comment by aweary** [comment]
@ma7moudat there's an example of a `useSubscription` hook in https://github.com/facebook/react/pull/15022 that you can reference or copy into your project.
