### ISSUE TITLE
Fragment will throw an error during unmount if it’s content is edited outside react

### ISSUE THREAD

**Issue by wwwsevolod** [facebook/react#15985]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If direct child node of fragment was replaced by other node not created by react — react will throw `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` when Fragment will be unmounted

**Smallest reproduction case:**
https://codesandbox.io/s/react-replace-element-fragment-error-0rkqw
Second and fourth buttons will produce error on second click.
What’s strange that if you’ll delete the content in fragment in content editable div (button 5) — it will not throw error.

**What is the expected behavior?**
React not throwing error. Maybe warning?
Why? because any browser extension in any browser can replace any node and this will lead to broken application.
Otherwise documentation should be improved and state clearly that fragment is unsafe to use if there is a chance of third party DOM modification. (I understand why it is happening in the first place, but not agree that it should).
Also it would be great to include DOM path into original error if possible, because for example we create captured this error using sentry and it is unclear where it is happening and it’s quite hard to improve the situation.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.3, no, I think it was broken all along

**Comment by wwwsevolod** [comment]
Hi! Sorry for the noise, but how can I help you to at least review the issue?

**Comment by threepointone** [comment]
This isn't just a problem with fragments; you'll probably face this with other components too, if you have an external thing that changes the dom nodes that React creates and uses. I don't think there's much we can do here to be honest. Closing this issue, but we will keep thinking about this.

**Comment by wwwsevolod** [comment]
@threepointone why not just not to through error when possible? Right now any browser extension can break any react application without doing anything harmful, and it is really hard to communicate to users.

**Comment by wwwsevolod** [comment]
Since this is only about unmounting
