### ISSUE TITLE
useEffect issue in production mode

### ISSUE THREAD

**Issue by jajk** [facebook/react#15994]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
I use "useEffect" in my code as below:
![image](https://user-images.githubusercontent.com/17432911/60167049-e2a9a200-9834-11e9-816b-1cc1f4068b7c.png)
In development mode, everything is correct, but in production mode, we will get this error:
![image](https://user-images.githubusercontent.com/17432911/60167189-27353d80-9835-11e9-855c-5a75158278cc.png)
I guess useEffect doesn't check whether the returned value is a function when unmounted in production mode, so I modified this structure as below and it works fine both in development and production mode.
![image](https://user-images.githubusercontent.com/17432911/60167476-c0fcea80-9835-11e9-814d-b63561863db3.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Above description.
**What is the expected behavior?**
in production, when we use this structure, we should get right behavior as same as development mode:
![image](https://user-images.githubusercontent.com/17432911/60167049-e2a9a200-9834-11e9-816b-1cc1f4068b7c.png)
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "16.8.6",
"react-dom": "16.8.6"

**Comment by ZijianHe** [comment]
This is the wrong way using useEffect:
```useEffect(() => fetchDependentOverview(row.id), [...]);```
This is the right way:
```
useEffect(() => {
  fetchDependentOverview(row.id);
}, [...]);```


The first argument of useEffect must be a function that returns `undefined` or a `function`, which will be called when the component unmount.

**Comment by threepointone** [comment]
This seems like expected behaviour. Wasn't there a warning in dev mode?
