### ISSUE TITLE
expected 1 but found 2 instances with node type: "undefined"

### ISSUE THREAD

**Issue by C-odes** [facebook/react#15995]
**Do you want to request a *feature* or report a *bug*?**
bug?
**What is the current behavior?**
So I have this component Im trying to test. It is one component with 3 fields, one input, one select, and then based on that select  the third is shown or not. 
So far Im trying to write one text only for the input field (the first one).

So here is the code:
```React
 it("test input field", () => {
    const newProps = {
      something: initialState,
      dispatch: reducer
    };
    const component = TestRenderer.create(
      <ContextBR.Provider value={{ ...newProps }}>
        <ComponentWithTheFields/>
      </ContextBR.Provider>
    );
    const rootInstance = component.root;
    console.log(rootInstance);
    const inputField = rootInstance.findByType("input");

    inputField.props.onChange({ target: { value: "" } });
    expect(inputField.props.value).toBe("");

    inputField.props.onChange({ target: { value: "blue" } });
    expect(inputField.props.value).toBe("blue");
  });
``` 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
I wanted to get the input field 
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```React
    <div>
      <div className="container">
        <h3 className="h3">Info</h3>
        <div className="row">
          <div className="col">
            <label htmlFor="test">test:</label>
            <input
              id="myID"
              value={aPropThatIsAnEmptyString}
              type="text"
              className={`form-control form-control-sm ${style.fieldsGap}`}
              onChange={e => setTest(e.target.value)}
              placeholder="test"
            />
          </div>
          <div className="col">
            <label htmlFor="ddlType">test2:</label>
            <select
              id="SelectId" 
```

but Im getting 

Expected 1 but found 2 instances with node type: "undefined" 

      29 |     const rootInstance = component.root;
      30 |     console.log(rootInstance);
    > 31 |     const inputField= rootInstance.findByType("input");
         |                                   ^
      32 | 
      33 |     inputField.props.onChange({ target: { value: "" } });
      34 |     expect(inputField.props.value).toBe("");

**Comment by threepointone** [comment]
Could you make a repro on codesandbox or a git repo?

**Comment by threepointone** [comment]
closing this issue, but happy to reopen if you can share a repro.
