### ISSUE TITLE
[eslint-plugin-react-hooks]: auto-fix may crash app when deps is array/object types

### ISSUE THREAD

**Issue by kpaxqin** [facebook/react#16006]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

before run lint, my code is

```js
const App = () => {
  const [options, setOptions] = useState([]);
  const [includesA, setIncludesA] = useState(false);

  const optionCodes = options.map(({ value }) => value);

  useEffect(() => {
    if (optionCodes.includes('A')) {
      setIncludesA(true);
    }
  }, [optionCodes.join(',')]); // transform array to string for compare 

  return <div onClick={() => setOptions([{ value: 'A' }])}></div>;
};

```
after 'eslint --fix'

```js

const App = () => {
  const [options, setOptions] = useState([]);
  const [includesA, setIncludesA] = useState(false);

  const optionCodes = options.map(({ value }) => value);

  useEffect(() => {
    if (optionCodes.includes('A')) {
      setIncludesA(true);
    }
  }, [optionCodes]); // optionCodes.join(',') was replaced ! 

  return <div onClick={() => setOptions([{ value: 'A' }])}></div>;
};
```
The original code works fine and after 'eslint --fix' it just crashed cuz `optionCodes` **is an array** created in render function, the effect runs every time and crash my app with error :

> react-dom.development.js:55 Uncaught Invariant Violation: Maximum update depth exceeded.

I've also notice this rule fix will add other params used by effect function to deps automatically. Like

```js
// original code
const {id} = props
useEffect(()=> {
  console.log(id)
},[])

// after fix
const {id} = props
useEffect(()=> {
  console.log(id)
}, [id]) // id has been add to deps
```

**What is the expected behavior?**

For 'eslint --fix', what we expect is 'try to fix lint error automatically and **SAFELY**', SAFELY means **DO NOT change my code logic**, run 'eslint --fix' should never change your design or crash your app .

It would be better to tell developers to fix the deps by lint message, not auto fix it in dangerous way.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

eslint-plugin-react-hooks@1.6.1

**Comment by gaearon** [comment]
Yeah. See https://github.com/facebook/react/issues/15204#issuecomment-476789202 for context. I guess we’ll have to disable autofix if running it without looking is so common. The original intention was to make it an *IDE suggestion* but ESLint doesn’t offer a way to do that.

**Comment by gaearon** [comment]
I’ll reach out to see if ESLint would be open to add a feature like this.

**Comment by gaearon** [comment]
Regarding the autofix, I hope https://github.com/eslint/rfcs/pull/30 will let us solve the problem without compromising on IDE suggestions.

**Comment by gaearon** [comment]
Let's consolidate and track this in https://github.com/facebook/react/issues/16313 instead.

**Comment by gaearon** [comment]
This is resolved now.
https://github.com/facebook/react/issues/16313#issuecomment-587149109
