### ISSUE TITLE
unable to access env variables in html files other than index.html

### ISSUE THREAD

**Issue by aditya81070** [facebook/react#16010]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The environment variables are just acting as normal text in HTML files.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/elated-butterfly-r2jpe

In the above example, I am not able to use the `env variables` in the `index.html` and `callback.html`. This is different from CRA in which, I can at least access the `env variables` in the `index.html`.

**What is the expected behavior?**
The title of `callback.html` should be changed according to the `REACT_APP_CALLBACK_TITLE` in the `.env` file.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react -> 16.8.6
react-dom -> 16.8.6
react-scripts -> 3. 0.1
browser: Google Chrome -> Version 75.0.3770.100 (Official Build) (64-bit)
Nope, it didn't work in previous versions of React.

**Comment by threepointone** [comment]
Please file this issue at https://github.com/facebook/create-react-app/issues
