### ISSUE TITLE
HotReload Rendered more hooks than during the previous render when commenting out code

### ISSUE THREAD

**Issue by MANTENN** [facebook/react#16016]
**What is the current behavior?**

```javascript
function usePromotion() {
  const [isOpen, setState] = useState(false);

  useEffect(() => {
    
  })
}

```

Steps to reproduce:
1. Comment out a hook/some hooks.

**What is the expected behavior?**
Debatable, in my opinion this should be more of a warning. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- Chrome[Version 75.0.3770.100 (Official Build) (64-bit)] 
- macOS 10.14.4 (18E226)
- Gatsby 2.8.2
- React 16.8.6

**Comment by MANTENN** [comment]
I don't if HotReload is apart of Gatsby or ReactJS, in the meantime since i'm working with Gatsby, and how it's structured I assume it's related to Gatsby.

**Comment by gaearon** [comment]
Yeah. The version used by Gatsby is completely unsupported by React.

I’m working on an official implementation. Hope we can get Gatsby using it once it’s more ready.
