### ISSUE TITLE
useEffect nested under the suspense and lazy, the second empty array parameter does not work

### ISSUE THREAD

**Issue by carvinlo** [facebook/react#16018]
**Do you want to request a *feature* or report a *bug*?**
Maybe bug?

**What is the current behavior?**
useEffect nested under the suspense and lazy, the second empty array parameter does not work
```js
import React, { useEffect } from 'react';
function Loader(props){
    const Component = lazy(() => {
        useEffect(() => {
            // fetchData and then update store
        }, []); // [] does not work. it will always fetchData when component rerender, but not just once.
    });
    return <Suspense fallback={<div>Loading...</div>}>
        <Component />
    </Suspense>
}
```

**What is the expected behavior?**
When useEffect nested under the suspense and lazy, the second empty array parameter does not work.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`"react": "^16.5.2"`

**Comment by dmytro-lymarenko** [comment]
It is because you create Component in each render.

**Comment by gaearon** [comment]
Yeah, you can't create components during rendering.

Also lazy is supposed to _only_ be used with `import`. It looks like you might be trying to use it for data fetching — that is not supported and won't work.
