### ISSUE TITLE
react-test-renderer with jest.resetModules: invariant violiation for hooks

### ISSUE THREAD

**Issue by entropitor** [facebook/react#16012]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When writing a test with jest (and requiring a component with hooks after `jest.resetModules()`), `react-test-renderer` complains 
> Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Write a functional component using a hook
2. Create a test using jest
3. Call `jest.resetModules`
4. Require the module
5. Call `renderer.create(<MyComponent />).toJSON()` 
6. Run test, it fails with the error above

**What is the expected behavior?**
The test should not crash on hooks in tests where resetModules() is called

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8. as hooks were introduced

**Comment by threepointone** [comment]
Please share a repro on codesandbox or as a git repo.

**Comment by entropitor** [comment]
@threepointone I've set up an example at https://github.com/entropitor/react-issue-16012

The first test case succeeds, showing that the repo is set up correctly, but the second one, using resetModules is failing (which it shouldn't)

**Comment by threepointone** [comment]
I made a PR to your repo that fixes it. https://github.com/entropitor/react-issue-16012/pull/1 more of a jest issue; you should refresh modules after resetting it.
