### ISSUE TITLE
[eslint-plugin-react-hooks] using a hook in a try {} catch {} block not allowed

### ISSUE THREAD

**Issue by jboler** [facebook/react#16026]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Using a hook within a `try {} catch {}` block throws an eslint error:

The component:
```typescript
export function Things({ parentId, searchTerm }: Props) {
  try {
    const { data: things, loading } = useThings(parentId, {
      include: ['other'],
      extra_fields: { things: 'foo' },
      filter: { other_name: searchTerm.trim() },
      page: { size: 20 },
    });

    return (
      <Content>
        {!things ? (
          <Loading />
        ) : (
          <ThingsList things={things} loading={loading} />
        )}
      </Content>
    );
  } catch {
    return (
      <Content>
        <ThingsList roles={[]} loading={false} />
      </Content>
    );
  }
}
```
Where `useThings()` is a custom hook that performs a `fetch` in a `useEffect()` hook.

**What is the expected behavior?**
I think this should be acceptable because the hook is always called.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
eslint-plugin-react-hooks@1.6.1

**Comment by PanFrontend** [comment]
I don't know if it is a bug or intended behavior but imho you should use try/catch inside hook that fetches your data. Then return from it what you need to display component including if there was an error or not. After that, you can use it in component to decide what to show.

Maybe someone will get another idea or confirm it's buggy

**Comment by probablyup** [comment]
@jboler a try/catch essentially ends up being a conditional because it's possible some code could not be run in the try block, so this behavior is correct according to the [rules of hooks](https://reactjs.org/docs/hooks-rules.html).

Instead add a `.catch()` to your fetch in the `useThings()` hook and surface the error as another object property in the return if necessary.

**Comment by gaearon** [comment]
As @probablyup explained, the lint rule is correct here.

To catch errors in components, you might wanna use [error boundaries](https://reactjs.org/docs/error-boundaries.html) instead.
