### ISSUE TITLE
Dynamic compilation in react

### ISSUE THREAD

**Issue by PRASHANT1104** [facebook/react#16023]
Is it possible to compile components dynamically (on demand) and load them then ?
As of now , what i know is if you use dynamic import, it builds a context chunk in the build/compile time and later downloads it if required by user. That is faster than the static import but it still goes through the files in my directory as mentioned in import during compile time.

say i do ->
import(`./${filename}`).then(component)=>{ /*code here*/}.catch(()=>console.log("no such file))

here filename is the user input . So when i compile this i see it going through all the files in the current directory and giving me syntax error warnings for the files ?

 So my question is can we not compile those files on demand and load them then ?
Please assume that the imported files are error free in all manner.
Also , the query is for React . I know it can be done in AngularJs.
Thanks in advance.

**Comment by threepointone** [comment]
This seems like a question for webpack/parcel/whatever bundler you're using. React doesn't have anything to do with this imo.
