### ISSUE TITLE
Application gets hanged when 200 input fields gets render

### ISSUE THREAD

**Issue by ajAnshul** [facebook/react#16025]
In my React component I have to render around 200 input fields. when I render component, browser gets hanged and screen becomes blank(I checked task manager their browser starts taking around 5000 MB space and CPU utilization reaches to 100%). If I refresh the page then same component is rendering very easily and screen also fine. This is issue I am facing only in my production environment and in dev environment it works absolutely fine on first render without refresh.

This happens only in Google crome. When I do same thing in Mozila it works fine.

Please suggest any solution. I am using React 16.2.0.

Thanks in advance.

**Comment by srinivasdamam** [comment]
This might work.
Add a log inside the componentDidMount and componentDidUpdate, by this you can see if your component is stuck in loop.

**Comment by ajAnshul** [comment]
@srinivasdamam I have tried using componentDidMount and componentDidUpdate but could not improve. I tried to refresh page and everything worked fine. I think this is memory leak problem Some how Dom from previous pages of my application not getting remove. So when I refresh it removes old pages Dom and render only current screen then it works fine. 

May be this same problem as #15637

**Comment by thirtytw** [comment]
@ajAnshul Would you mind providing an example on Codesandbox? It's hard to tell without the code

**Comment by miraage** [comment]
React 16.2.0, 500 inputs: https://codesandbox.io/embed/lively-sunset-vpjnq.
Looks good to me on Chrome 75.

**Comment by threepointone** [comment]
The linked issue seems to have been resolved with 16.9. It's hard to comment further without a reproducing case, please use codesandbox or a plain git repo to demonstrate the problem. 

I'm closing this, but happy to reopen with a reproducing case.
