### ISSUE TITLE
Invariant Violation: Minified React error #321

### ISSUE THREAD

**Issue by lianrenjie** [facebook/react#16029]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by cindyrise** [comment]
when import react hook，Invariant Violation: Minified React error #321；The current used react 16.8.6,chrome 75,

**Comment by sagar-gavhane** [comment]
Hey, Can you provide code snippets or codesandbox link for reference?

**Comment by fizikst** [comment]
I make a module https://www.npmjs.com/package/@gorazd/module-hook (https://codesandbox.io/s/little-dawn-2sxyo).

To check the functionality of the module using https://github.com/facebook/create-react-app.

If the module contain react-hook (release 1.0.0), return same error.

If the module non contain react-hook (release 1.0.2), return module.

**Comment by ngocketit** [comment]
I got the same error over here.

**Comment by Dergash** [comment]
Hello @lianrenjie, @fizikst, @ngocketit! 

Based on example that @fizikst provided I believe the problem is that you are indeed have multiple instances of React on your page and the warning invariant=321 is correct behavior.

You can see it in your bundled code in your npm package:
![another-react](https://user-images.githubusercontent.com/13132449/62453407-75c2e980-b79c-11e9-8400-d1542813d130.png)

The thing is, aside of making React and react-dom a peer deependencies in your library package.json, you also should mark them as 'externals' when building them with webpack, so webpack would know that react shouldn't be bundled into your library and should be looked in runtime instead.

**Comment by deligent-ant** [comment]
i have did as your said, just like . " aside of making React and react-dom peer deependencies in your libraries package.json, you also should mark them as 'externals' when building them with webpack"
but the #321 still exist,who can help me.

**Comment by deligent-ant** [comment]
i solute it . what my question is . npm-link 
webpack
```js
alias:{
react: path.resolve('./node_modules/react')
  }
```

**Comment by DamengRandom** [comment]
There might be another possibe case is we try to write hooks code inside class based component, which will cause this error as well.

**Comment by codedart2018** [comment]
> i have did as your said, just like . " aside of making React and react-dom peer deependencies in your libraries package.json, you also should mark them as 'externals' when building them with webpack"
> but the #321 still exist,who can help me.
> 
> ```js
> "peerDependencies": {
>     "antd": "^3.25.0",
>     "styled-components": "^4.4.1",
>     "react": "^16.11.0",
>     "react-dom": "^16.11.0"
>   }
> ```
> 
> ```js
>  externals: [
>     // nodeExternals(),
>     {
>       react: {
>         root: 'React',
>         commonjs2: 'react',
>         commonjs: 'react',
>         amd: 'react'
>       },
>       'react-dom': {
>         root: 'ReactDOM',
>         commonjs2: 'react-dom',
>         commonjs: 'react-dom',
>         amd: 'react-dom'
>       }
>     }
> }
> ```
> 
> if i don't use useCallback ant useMemo ,it can work,but i need useMemo...

thank you

**Comment by mqtik** [comment]
I had to comment the following code in order to solve the #321 error, similar to development config.
```
 externals: [
    // nodeExternals(),
    {
      react: {
        root: 'React',
        commonjs2: 'react',
        commonjs: 'react',
        amd: 'react'
      },
      'react-dom': {
        root: 'ReactDOM',
        commonjs2: 'react-dom',
        commonjs: 'react-dom',
        amd: 'react-dom'
      }
    }
}
```
 
Now it works when I build with `yarn start`, but in release build it crashes at startup.
Weird.

**Comment by alexander-elgin** [comment]
I had the same issue when I used `useSelector` inside a local function. The issue was gone when I moved `useSelector` to the body of the render function.

**Comment by SilvaQ** [comment]
> I had to comment the following code in order to solve the #321 error, similar to development config.
> 
> ```
>  externals: [
>     // nodeExternals(),
>     {
>       react: {
>         root: 'React',
>         commonjs2: 'react',
>         commonjs: 'react',
>         amd: 'react'
>       },
>       'react-dom': {
>         root: 'ReactDOM',
>         commonjs2: 'react-dom',
>         commonjs: 'react-dom',
>         amd: 'react-dom'
>       }
>     }
> }
> ```
> 
> Now it works when I build with `yarn start`, but in release build it crashes at startup.
> Weird.

same question。

**Comment by mazunind** [comment]
As @DamengRandom has suggested, rewriting some components into functional ones solved this for me

**Comment by gleiderr** [comment]
I am using my package as my-lib: "link: ../ .." while testing. That is why this problem occurred.

What worked for me was the suggestion found in the stackoverflow below:

> making my app and library point to the same react (package) location.
> 
> Below are the steps I followed :
> 1. In Your Application:
> a) cd node_modules/react && npm link
> b) cd node_modules/react-dom && npm link
> 
> 2. In Your Library
> a) npm link react
> b) npm link react-dom
> 
> 3)Stop your dev-server and do `npm start` again.

Refer below for more details:
https://stackoverflow.com/questions/56021112/react-hooks-in-react-library-giving-invalid-hook-call-error

**Comment by Statfine** [comment]
you can move react and react-dom from dependencies to devDependencies in your lib，this can ensure react consistency in project
```
// package.json
{
  "dependencies": {},
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0"
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
  }
}
```
