### ISSUE TITLE
useEffect doesn't work as componentDidMount while using real time connections 

### ISSUE THREAD

**Issue by md-shahnawaz08** [facebook/react#16031]
```js
useEffect(() => {
    connection.on('received', (user, message) => {
      if (userName && userName !== user) {
        audio.play()
      }
      const newMessages = [...replies, {userName: user, text: message}]
      setReplies(newMessages)
    })
  }, [connection, replies, audio, userName])
```
I want ```connection.on``` at ```componentDidMount``` or ngOnInit(in Angular). 

- If I add dependencies in the dependency array the ```connection.on``` gets called that many times the dependency states get updated.
- If I don't add the dependencies the states (userName, replies) take the initial values even if they get updated by that time. And I get warning for not adding the dependencies in dependency array.
- If I remove the dependency array the ```connection.on``` gets called that many times any state gets updated.

Can you please provide any solution for that?

**Comment by probablyup** [comment]
@md-shahnawaz08 this is to be expected when dependencies are passed to `useEffect` as React doesn't know what you're doing inside the effect. If you truly only want to call the handler once on mount, supply an empty dependencies array and suppress the lint warning. It's just there to help protect you if you actually needed to reapply the effect when the consumed variables changed.

**Comment by vyushin** [comment]
You can using condition... I don't know what kind of values you have as initials... so jist wrote easy condition. :) Just make sure that values are not initial and run your code...

```javascript
useEffect(() => {
    if (!connection || !replies || !audio || !userName) return; // Check values
    connection.on('received', (user, message) => {
      if (userName && userName !== user) {
        audio.play()
      }
      const newMessages = [...replies, {userName: user, text: message}]
      setReplies(newMessages)
    })
  }, [connection, replies, audio, userName])
```

**Comment by markerikson** [comment]
Consider using `useReducer()` and dispatching an action from within the effect, or using the callback form of a `useState()` setter, instead of calculating the new state in the event handler.  That eliminates the need to have the effect depend on the state value.

**Comment by md-shahnawaz08** [comment]
Callback style of useState solved the setting state problem but getting any state for any logic gives the initial value. useReducer didn't work as with every dispatch the state it was getting in reducer was the initial state. Tried calling function from useEffect but that function also cannot take the current values of states.
Seems like useEffect creates an environment at the specific time and you cannot fetch an asynchronously updated value of a state there. If you add the state in dependency array it creates a queue of same useEffect with each value of the state.
I think the only way to solve the problem is to unsubscribe the listener at return callback of useEffect. 
I solved the problem like this
```
  useEffect(() => {
    connection.on('received', (user, message) => {

      if (userName !== user) {
        audio.play()
      }

      setReplies(oldReplies => [...oldReplies, {userName: user, text: message}])
    })
    
    return () => {
      connection.off('received')
    }
  }, [connection, userName, audio])
```

**Comment by markerikson** [comment]
@md-shahnawaz08 : honestly, it sounds like you're doing something wrong there, but it's hard to say without seeing more of the code in a larger context.

I think you should read through Dan Abramov's [A Complete Guide to `useEffect`](https://overreacted.io/a-complete-guide-to-useeffect/), and think about how JS closures work.

**Comment by harmnot** [comment]
i am trying to fetchData with state` data= null` and then inside useEffect when the response 200 i do  `setData(response.fetch.data)`,

but when i call the result of that fetch data to render it on `<div> {data} </div>`, it always be null, because it takes time to get data from API, so i should create conditon if that data **equal** null , `<div> loading.... </div> else <div> got it </div>` it was work.

now i tried to `dispatch({type: Fetch, payload: data})` to my context value hook, if that `state.context.value` uqual null , `<div> loading.... </div> else <div> got it </div>` this was error and **reload** the window and on my inspects all my value in my Context error _(undefined, and null)_, why this is happen ??

anyway, I was using async-await also on the above case, still the same issue

```import ListTask from "../components/listTask.js";
import runAPI from "../API.js/runAPI.js";
import Swal from "sweetalert2";
import { TaskContext } from "../contexts/taskContext.js";

const Task = () => {
  const { state, dispatch } = useContext(TaskContext);
  const [task, setTask] = useState(null);

  useEffect(() => {
    let didCancel = false;
    runAPI
      .get("api/task/tasks")
      .then(data => {
        if (!didCancel) {
          setTask(data.data.data);
          dispatch({ type: "FETCH_DATA", payload: data.data.data }); // got error if this not commented
        }
      })
      .catch(error => {
        Swal.fire({
          title: "Error!",
          text: error.response.error,
          timer: 2000,
          type: "error",
          showCancelButton: false,
          showConfirmButton: false
        });
      });

    return () => (didCancel = true);
     // look https://github.com/facebook/react/issues/14326 why i use didCancel

  }, []);

  return <div> {!task ? <div> loading...</div> : <div> got.it</div>}</div>;
};

export default Task;
