### ISSUE TITLE
Inconsistent act behaviour for react-test-renderer

### ISSUE THREAD

**Issue by mpeyper** [facebook/react#16034]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When rendering a component that has cascading updates from multiple `useEffect` hooks we see a different behaviour when using `react-test-renderer` than when we use `react-dom` or `react-testing-library` to render the same component.

[Here is a codesandbox to demponstrate the issue.](https://codesandbox.io/s/useeffect-with-react-test-renderer-repro-64guc?fontsize=14&module=%2Fsrc%2Fexample.test.js&previewwindow=tests)

The test that uses `react-test-renderer` fails where as the other 2 tests (`react-dom` and `@testing-library/react`) pass for the same component.  If you check the console for the logging it outputs, it has:

```sh
before react-test-renderer render 
running null null
triggering setAfterChanged 
triggering setTestUpdated 
running Object {foo: "bar"} null
after react-test-renderer render Object {afterChanged: null}

before rtl render 
running null null
triggering setAfterChanged 
triggering setTestUpdated 
running Object {foo: "bar"} null
triggering setAfterChanged 
running Object {foo: "bar"} Object {foo: "bar"}
after rtl render Object {afterChanged: Object}

before react-dom render 
running null null
triggering setAfterChanged 
triggering setTestUpdated 
running Object {foo: "bar"} null
triggering setAfterChanged 
running Object {foo: "bar"} Object {foo: "bar"}
after react-dom render Object {afterChanged: Object}
```

As you can see, the non `react-test-renderer` renders are performing more updates before the `act` call (assumed internal `act` call for RTL) returns.

**What is the expected behavior?**

I would expect the effect flushing behaviour to be the same, regardless of the renderer, so all the tests would pass and the console logs would be:

```sh
before react-test-renderer render 
running null null
triggering setAfterChanged 
triggering setTestUpdated 
running Object {foo: "bar"} null
triggering setAfterChanged 
running Object {foo: "bar"} Object {foo: "bar"}
after react-test-renderer render Object {afterChanged: Object}

before rtl render 
running null null
triggering setAfterChanged 
triggering setTestUpdated 
running Object {foo: "bar"} null
triggering setAfterChanged 
running Object {foo: "bar"} Object {foo: "bar"}
after rtl render Object {afterChanged: Object}

before react-dom render 
running null null
triggering setAfterChanged 
triggering setTestUpdated 
running Object {foo: "bar"} null
triggering setAfterChanged 
running Object {foo: "bar"} Object {foo: "bar"}
after react-dom render Object {afterChanged: Object}
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`react`: `16.8.6`
`react-dom`: `16.8.6`
`react-test-renderer`: `16.8.6`
`@testing-library/react`: `8.0.4`

**Comment by threepointone** [comment]
I checked, and this seems to be fixed in master. could you verify if the issue persists with 16.9.0-alpha.0?

**Comment by threepointone** [comment]
yeah, updating the codesandbox to 16.9.0-alpha.0 passes the tests. https://codesandbox.io/s/useeffect-with-react-test-renderer-repro-kef6k

**Comment by mpeyper** [comment]
Thanks again @threepointone. 

I'll pass this info on and eagerly await the 16.9.0 release :)
