### ISSUE TITLE
Return render function in hooks ?

### ISSUE THREAD

**Issue by stonexer** [facebook/react#16037]
Example: 

https://codesandbox.io/s/usemodal-z715z

```jsx
const useModal = () => {
  const [visible, setVisible] = useState(false)

  const showModal = useCallback(() => setVisible(true), [])
  const hideModal = useCallback(() => setVisible(false), [])

  const renderModal = () => (
    <AntdModal visible={visible} onCancel={hideModal} onOk={hideModal} />
  )

  return {
    showModal,
    hideModal,
    renderModal,
  }
}

const App = () => {
  const {renderModal, showModal} = useModal()

  return (
    <div>
      <Button onClick={showModal}>Show</Button>
      {renderModal()}
    </div>
  )
}
```

I found this way to extract some render things and some local state in hooks. I'm wondering if there is performance issue or bad practice. 

I tried to return Component at beginning and then find [OldModal !== NewModal](https://www.reddit.com/r/reactjs/comments/9yq1l8/how_do_you_feel_about_a_hook_returning_components/) issue. But how about just return partial renderer?

**Comment by threepointone** [comment]
Looks fine to me. Not really a bug or feature request, so closing.
