### ISSUE TITLE
Search filter does not work across the react-table on setState : React JS

### ISSUE THREAD

**Issue by velsonjr** [facebook/react#16032]
I am using react-table for data grid purposes. All I am trying to implement  a search filter that searches data across the table and filters down by using filter method. I have maintained a separate component for Searching and I set the table's data inside search component. The filtering breaks when the characters are being deleted from the search filter. Am I doing something wrong here. 

Sandbox: https://codesandbox.io/s/stoic-gould-kw9iq

SearchComponent
------------------
``````````````````````````
import React from "react";
import { Input } from "semantic-ui-react";

export default class DropDownComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      filteredData: [],
      searchInput: ""
    };
  }

  handleChange = event => {
    this.setState({ searchInput: event.target.value }, () =>
      this.globalSearch()
    );
  };

  globalSearch = () => {
    let { searchInput } = this.state;
    let filteredData = this.props.data.filter(value => {
      return (
        value.firstName.toLowerCase().includes(searchInput.toLowerCase()) ||
        value.status.toLowerCase().includes(searchInput.toLowerCase()) ||
        value.visits
          .toString()
          .toLowerCase()
          .includes(searchInput.toLowerCase())
      );
    });
    this.props.handleSetData(
      (filteredData.length > 0 && filteredData) || searchInput
        ? filteredData
        : this.props.data
    );
  };

  render() {
    return (
      <>
        <br />
        <Input
          size="large"
          name="searchInput"
          value={this.state.searchInput || ""}
          onChange={this.handleChange}
          label="Search"
        />
        <br />
        <br />
      </>
    );
  }
}

``````````````````````````
App Component
-----------------
```````````````````````
import React from "react";
import ReactDOM from "react-dom";
import GlobalSearchComponent from "./GlobalSearchComponent";
import ReactTable from "react-table";
import "react-table/react-table.css";
import "./styles.css";

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: []
      columns: [],
      searchInput: ""
    };
  }

  componentDidMount() {
    this.getData();
    this.getColumns();
  }

  getColumns = () => {
    let columns = [
      {
        Header: "First Name",
        accessor: "firstName"
      {
        Header: "Status",
        accessor: "status"
      },
      {
        Header: "Visits",
        accessor: "visits"
      }
    ];
    this.setState({ columns });
  };

  getData = () => {
    let data = [
      { firstName: "aaaaa", status: "Pending", visits: 155 },
      { firstName: "aabFaa", status: "Pending", visits: 155 },
      { firstName: "adaAAaaa", status: "Approved", visits: 1785 },
      { firstName: "aAaaaa", status: "Approved", visits: 175 },
      { firstName: "adaSaaa", status: "Cancelled", visits: 165 },
      { firstName: "aasaaa", status: "Cancelled", visits: 157 },
      { firstName: "aweaaaaaewea", status: "Approved", visits: 153 },
      { firstName: "adaAAadsdweaa", status: "Approved", visits: 17585 },
      { firstName: "aAaaaa", status: "Approved", visits: 175 }
    this.setState({ data });
  };

  handleSetData = data => {
    console.log(data);
    this.setState({ data });
  };

  render() {
    let { data, columns } = this.state;
    return (
      <div>
        <GlobalSearchComponent
          data={this.state.data}
          handleSetData={this.handleSetData}
        />
        <ReactTable
          data={data}
          columns={columns}
          defaultPageSize={10}
          className="-striped -highlight"
        />
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by MorganDbs** [comment]
Hi, it's because you are setting your "filteredData" to your "data" in your state, so, you are basically overwritting your "data".

One possible solution :

https://codesandbox.io/s/inspiring-visvesvaraya-347r5

**Comment by velsonjr** [comment]
@MorganDbs That did work! Now what if I want to integrate it with a column level search filter, where based on each click I make a server call than then it returns me the data , In this case how would the state object and passing data look like ? Here also I will maintain a separate column level search component that will be attached to each column

**Comment by MorganDbs** [comment]
@velsonjr I'm not sure to understand, you want to order by asc / desc on column click ?
Btw, I developped a [datatable component library](https://github.com/o2xp/react-datatable), maybe it can make your code easier !

**Comment by velsonjr** [comment]
@MorganDbs , I am talking about a column level search filter. This searches the data across the column and not across the entire table just as in the above case. for example : To each table column I attach say a , ColumnSearchFilter . To this component what is the data that needs to be passed from App? Also while setting the state from this ColumnSearchFilter , would this affect the existing global search behavior?

**Comment by MorganDbs** [comment]
@velsonjr Oh ok, it's exactly the same logic as your search component except that you'll pass as props something like "columName" which is the column where you want to filter. But I recommend you to merge your searchComponent and your searchColumnComponent into one and just check if the props columnName is empty (= search trought all the column) or not (= in the column specified). Like that you'll avoid code duplication ! :-)

**Comment by threepointone** [comment]
Closing this issue since it isn't a bug/feature request on react, but feel free to continue the conversation if you need to.
