### ISSUE TITLE
Keep getting `TypeError: Cannot read property 'scrollTop' of null` in a custom hook...

### ISSUE THREAD

**Issue by rchrdnsh** [facebook/react#16045]
I made a hook to get the scroll position of a component, like so:

```js
function useScrollPosition() {

  function getScroll() {
    return {
      x: document.getElementById('ContentContainer').scrollTop,
      y: document.getElementById('ContentContainer').scrollLeft
    }
  }

  const [scrollPosition, setScrollPosition] = useState(getScroll)

  useEffect(() => {
    
    function handleScroll() {
      setScrollPosition(getScroll())
    }

    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, []) // Empty array ensures that effect is only run on mount and unmount

  return scrollPosition
}
```

...and implemented it in the same file, like so:

```jsx
const ContentContainer = (props) => {

  const scroll = useScrollPosition();

  return (
    <Main id='ContentContainer'>
      <ScrollInfo>
        Vertical position: {scroll.x}px / Horizontal Position: {scroll.y}px
      </ScrollInfo>
      {props.children}
    </Main>
  )
}

export default ContentContainer
```

...and i keep getting the same error:

<img width="797" alt="Screenshot 2019-07-03 00 38 46" src="https://user-images.githubusercontent.com/7884263/60572670-f4a2ad80-9d2a-11e9-8162-d4fe1c973f87.png">

If I disable the hook and the app runs properly, I can then find the scroll position in the console just fine.

Any thoughts as to why I might be getting `null` back for something that clearly isn't `null` when the app loads without this hook enabled?

**Comment by Gaoussou1** [comment]
Hi @rchrdnsh really good stuff your scroll position hook!!
To fix the bug i did this : 
```  
function getScroll() {
    const data = document.getElementsByClassName("App")[0]
      ? document.getElementsByClassName("App")[0].getBoundingClientRect()
      : 0;
    const { bottom, top, left, right } = data;
    return { bottom, top, left, right };
 }```
and this to display the data: 
```
<ScrollInfo>
    Vertical position: {scroll.left}px / Horizontal Position: {scroll.top}px
</ScrollInfo>
```

**Comment by matvp91** [comment]
The callback in `useState` is invoked before the component is rendered (because it needs the initial state in order to do the first render).

Your code would be more solid if you'd define a ref, and use the ref to access  the underlying DOM element.

**Comment by aweary** [comment]
@matvp91 is correct, the element you're querying isn't rendered when you call `getElementById` so it returns `null`, and then throws because you try to access `scrollTop` and `scrollLeft` on `null`.

You can either [use a ref](https://reactjs.org/docs/hooks-reference.html#useref) or query for the elements in `useEffect`, which is executed after the DOM is updated.

**Comment by rchrdnsh** [comment]
thank you @Gaoussou1 XD

So, I got past the null error, but now the numbers just don't show up at all, like so:

<img width="211" alt="Screenshot 2019-07-03 10 24 44" src="https://user-images.githubusercontent.com/7884263/60612437-76bbc200-9d7d-11e9-91d0-89883394cdd6.png">


...not sure why. Here is what the code looks like now:

```js
function useScrollPosition() {

  function getScroll() {
    const data = document.getElementsByClassName("ContentContainer__ScrollInfo-csIyIU WjXgQ")[0]
      ? document.getElementsByClassName("ContentContainer__ScrollInfo-csIyIU WjXgQ")[0].getBoundingClientRect()
      : 0;
    const { bottom, top, left, right } = data;
    return { bottom, top, left, right };
  }

  const [scrollPosition, setScrollPosition] = useState(getScroll)

  useEffect(() => {
    
    function handleScroll() {
      setScrollPosition(getScroll())
    }

    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, []) // Empty array ensures that effect is only run on mount and unmount

  return scrollPosition
}
```

...and the component:

```jsx
const ContentContainer = (props) => {

  const scroll = useScrollPosition();

  return (
    <Main id='ContentContainer'>
      <ScrollInfo>
        From Top: {scroll.top}px <br/>
        From Bottom: {scroll.bottom}px <br/>
        From Left: {scroll.left}px <br/>
        From right: {scroll.right}px <br/>
      </ScrollInfo>
      {props.children}
    </Main>
  )
}

export default ContentContainer
```

The class name is long as it's generated by Gatsby and Styled-Components, so I don't know if that's an issue, but I also tried going back to ID, but I get the same result of no numbers showing up.

Hi @matvp91, I have heard of this ref you speak of, I just haven't had a chance to get my head around it yet. Will do when I have a moment :-)

**Comment by rchrdnsh** [comment]
ok, I've tried to update the code using `useRef`, like so:

```js
import React, { useState, useEffect, useRef } from 'react'
import styled from 'styled-components'

const Main = styled.main`
  ...stylezzzz...
`

const ScrollInfo = styled.div`
  ...stylezzzz...
`

function useScrollPosition() {

  const elementRef = useRef(null);  

  function getScroll() {

    const data = elementRef.current ? 
      elementRef.current.getBoundingCLientRect() : 0;
    
    const { bottom, top, left, right } = data;
   
    return { bottom, top, left, right };
  }

  const [scrollPosition, setScrollPosition] = useState(getScroll)

  useEffect(() => {
    
    function handleScroll() {
      setScrollPosition(getScroll())
    }

    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, []) // Empty array ensures that effect is only run on mount and unmount

  return scrollPosition
}

const ContentContainer = (props) => {

  const scroll = useScrollPosition();

  return (
    <Main ref={elementRef} id='ContentContainer'>
      <ScrollInfo>
        From Top: {scroll.top}px <br/>
        From Bottom: {scroll.bottom}px <br/>
        From Left: {scroll.left}px <br/>
        From right: {scroll.right}px <br/>
        From Top: {scroll.x}px
      </ScrollInfo>
      {props.children}
    </Main>
  )
}

export default ContentContainer
```

and I'm currently getting the following error:

```bash
  122:16  error  'elementRef' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Layout.js 17:0-45 91:140-144
 @ ./node_modules/gatsby-plugin-layout/wrap-page.js
 @ ./node_modules/gatsby-plugin-layout/gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js
ℹ ｢wdm｣: Failed to compile.
```

but it appears that I am defining the ref at the beginning of the hook, no? Not sure how to adjust it to work properly.

**Comment by Gaoussou1** [comment]
Hello @rchrdnsh ,
here is my code in a sandbox : https://codesandbox.io/s/clever-curie-o8vf2
I used the first draft that i showed you.
You'r right in the first rander the `ScrollInfo` is not displaying data, but as soon as you scroll it start showing info.
I'll make the first rander display `0` for all keys.
Peace !

**Comment by Gaoussou1** [comment]
Or maybe i inti with window.scrollBy(0, 1) just to trigger the init.
Everything is in the sandbox, it might not be the most clever code but tell me if it helps.

**Comment by rchrdnsh** [comment]
argh, I'm dumb @Gaoussou1! I'm adding an event listener to the window, and not to the element that I'm trying to output the scroll position of, but that still doesn't work, as it outputs the numbers once, then does not output them again.

Honestly, I'm just trying to do this:

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_element_scrollleft

but I can't for the life of me figure out how to do it in react. i thought this would be simple...

**Comment by rchrdnsh** [comment]
HOORAY!!! Got it to work (sort of.........)

Here is the custom hook that works for me:


```js
function useScrollPosition(elementRef) {

  function getScroll() {
    return {
      y: elementRef.current ? elementRef.current.scrollTop : undefined,
      x: elementRef.current ? elementRef.current.scrollLeft : undefined
    }
  }

  const [scrollPosition, setScrollPosition] = useState(getScroll)

  useEffect(() => {

    if (!elementRef.current) {
      return false
    }
      
    function handleScroll() {
      setScrollPosition(getScroll())
    }

    elementRef.current.addEventListener('scroll', handleScroll);
    return () => elementRef.current.removeEventListener('scroll', handleScroll);
  }, []) // Empty array ensures that effect is only run on mount and unmount

  return scrollPosition
}
```

The trick was to pass in an elementRef, like so:

```jsx
const ContentContainer = (props) => {

  const elementRef = useRef()

  const scroll = useScrollPosition(elementRef)

  // useEffect(() => {
  //   setTimeout(() => elementRef.current.scrollTop = 0, 0)
  // }, [])

  return (
    <Main ref={elementRef} id='ContentContainer'>
      <ScrollInfo id='ScrollInfo'>
        Scroll Position: {scroll.y}px
      </ScrollInfo>
      {props.children}
    </Main>
  )
}

export default ContentContainer
```

which does the job, only now another thing that was previously working is now broken.

Notice the commented out code:

```js
useEffect(() => {
  setTimeout(() => elementRef.current.scrollTop = 0, 0)
}, [])
```

...which would reset scroll position to 0 when the components children were updated. Now with that code in there, the component is constantly trying to update to 0 all the time, which is NOT what I want to happen.

So my new issue with this whole thing is how to reset scroll position to 0 when children update, then track scroll position as the component is interacted with...not sure how to go about doing that at all...

**Comment by execptionerror** [comment]
[[Solved] Uncaught TypeError: Cannot read property ‘ContentContainer’ of undefined [2 working Solution]](https://exerror.com/uncaught-typeerror-cannot-read-property-contentcontainer-of-undefined/)
