### ISSUE TITLE
How to share component instance, Don't unmount?

### ISSUE THREAD

**Issue by Lursun** [facebook/react#16044]
I have a component.
```jsx
import TradingView from 'react-tradingview-widget'
```
It's loading time too long and I need it in many pages.
but parent component unmount, it too.
No... <TradingView /> don't unmount. I need it save in memory and show anywhere have it's component.

**Comment by auderer** [comment]
Can you share more of your code?

It might be possible to move the component elsewhere on the tree. You should also address the long mounting time and look at options to improve this performance. 

I'll need to see more code to actually help.

**Comment by threepointone** [comment]
Please consider using a community resource for usage questions https://reactjs.org/community/support.html
