### ISSUE TITLE
Can't get dynamic data to show up in react component using several hooks...

### ISSUE THREAD

**Issue by rchrdnsh** [facebook/react#16053]
I have a react component using several hooks in which I'm trying to output the data from `getBoundingCLientRect()` into a box on the site.

This is the code:

```jsx
const ContentContainer = (props) => {

  const elementRef = useRef()

  function useScrollPosition() {
  
    function getScroll() {
      const data = elementRef.current ? 
        elementRef.current.getBoundingCLientRect() : 0
      const { bottom, top, left, right, x, y } = data
      return { bottom, top, left, right, x, y }
    }

    const [scrollPosition, setScrollPosition] = useState(getScroll)
  
    useEffect(() => {
      
      function handleScroll() {
        setScrollPosition(getScroll())
      }
  
      window.addEventListener('scroll', handleScroll)
      return () => window.removeEventListener('scroll', handleScroll)
    }, []) // Empty array ensures that effect is only run on mount and unmount
  
    return scrollPosition
  }

  const scroll = useScrollPosition();

  return (
    <Main ref={elementRef}>
      <ScrollInfo>
        From Top: {scroll.top}px <br/>
        From Bottom: {scroll.bottom}px <br/>
        From Left: {scroll.left}px <br/>
        From right: {scroll.right}px <br/>
        Vertical Scroll: {scroll.y}px <br/>
        Horizontal Scroll: {scroll.x}px <br/>
      </ScrollInfo>
      {props.children}
    </Main>
  )
}

export default ContentContainer
```

...but no dynamic data shows up in the window where it's supposed to be displayed:

<img width="177" alt="Screenshot 2019-07-03 16 15 17" src="https://user-images.githubusercontent.com/7884263/60630205-e9dd2c80-9dad-11e9-897c-bdccfa5fa042.png">

no errors show up in the terminal or the console, but it just does not work. Stumped at the current moment, and don't know what to fix to make it work.

**Comment by auderer** [comment]
First, you have a typo. Try `getBoundingClientRect` instead of `getBoundingCLientRect`

**Comment by rchrdnsh** [comment]
argh....dumb typo.

k, fixed the typo but it's still not working right...

**Comment by thirtytw** [comment]
@rchrdnsh Looks like all you need to do is to pull out your custom hook out of render function
https://codesandbox.io/s/patient-monad-rwt4k

**Comment by rchrdnsh** [comment]
argh, I'm dumb, I'm adding an event listener to the window, and not to the element that I'm trying to output the scroll position of, but that still doesn't work, as it outputs the numbers once, then does not output them again.

Honestly, I'm just trying to do this:

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_element_scrollleft

but I can't for the life of me figure out how to do it in react.  i thought this would be simple...

**Comment by rchrdnsh** [comment]
HOORAY!!! Got it to work (sort of.........)

Here is the custom hook that works for me:


```js
function useScrollPosition(elementRef) {

  function getScroll() {
    return {
      y: elementRef.current ? elementRef.current.scrollTop : undefined,
      x: elementRef.current ? elementRef.current.scrollLeft : undefined
    }
  }

  const [scrollPosition, setScrollPosition] = useState(getScroll)

  useEffect(() => {

    if (!elementRef.current) {
      return false
    }
      
    function handleScroll() {
      setScrollPosition(getScroll())
    }

    elementRef.current.addEventListener('scroll', handleScroll);
    return () => elementRef.current.removeEventListener('scroll', handleScroll);
  }, []) // Empty array ensures that effect is only run on mount and unmount

  return scrollPosition
}
```

The trick was to pass in an elementRef, like so:

```jsx
const ContentContainer = (props) => {

  const elementRef = useRef()

  const scroll = useScrollPosition(elementRef)

  // useEffect(() => {
  //   setTimeout(() => elementRef.current.scrollTop = 0, 0)
  // }, [])

  return (
    <Main ref={elementRef} id='ContentContainer'>
      <ScrollInfo id='ScrollInfo'>
        Scroll Position: {scroll.y}px
      </ScrollInfo>
      {props.children}
    </Main>
  )
}

export default ContentContainer
```

which does the job, only now another thing that was previously working is now broken.

Notice the commented out code:

```
useEffect(() => {
  setTimeout(() => elementRef.current.scrollTop = 0, 0)
}, [])
```

...which would reset scroll position to 0 when the components children were updated. Now with that code in there, the component is constantly trying to update to 0 all the time, which is NOT what I want to happen.

So my new issue with this whole thing is how to reset scroll position to 0 when children update, then track scroll position as the component is interacted with...not sure how to go about doing that at all...

**Comment by rchrdnsh** [comment]
i'll close this for now, as i'm not concerned with this at the moment. I hope that you are happy bot! XD
