### ISSUE TITLE
Undo, snapshot, hydration of state

### ISSUE THREAD

**Issue by Lokeh** [facebook/react#16056]
With Concurrent mode, storing all state in a single atom is no longer an option while taking advantage of prioritization. However, there are a number of benefits that a single atom provided such as history, and ease of snapshot + hydration.

React seems perfectly poised to be the location where these features could exist. Otherwise, we run into the continued problem that some component using local state can't be serialized/undone.

I've contemplated trying to pry open the internals of React and patching useState myself to experiment adding these features, but wanted to open up an issue first to see what current thoughts were on providing these functions at the framework level.

**Comment by threepointone** [comment]
You're right that mutable models don't work well/safely with concurrent mode; leaning on props/state/context is our current recommendation. I'm closing this issue for now, but we will have more to share about this in the near future. Thanks for the question!
