### ISSUE TITLE
React fails when mapping through an immu array in JSX

### ISSUE THREAD

**Issue by tristanHessell** [facebook/react#16058]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When `map`ing over an immu array in JSX, react fails with `Cannot add property validated, object is not extensible`.
The error is coming from `warnForMissingKey`

See: https://codesandbox.io/s/thirsty-mountain-j3bir for a failing example.

**What is the expected behavior?**
The rendering to flow as normal - in the supplied case, to see an unordered list with one element in it.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React `16.8.6`, 
Ubuntu: 18.04.2 LTS
Chrome: Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by Gaoussou1** [comment]
Hi @tristanHessell , i dont get the error and i'm looking further to know more about it.
What i understand is that you cant put many html element in a container when you loop through an `object`.
Here's my test: https://codesandbox.io/s/ecstatic-nightingale-q2o6n

**Comment by tristanHessell** [comment]
Closing as this issue is based off of the use of `immu`.

An array made immutable with `immu` will return immutable objects when using any of the array functions (such as `.map`).
