### ISSUE TITLE
[Feature request] Improved reconciliation/diffing algorithm

### ISSUE THREAD

**Issue by quanla** [facebook/react#16059]
Currently, the reconciliation process, if finds change in element type, would mark and unmount the element and its sub nodes. And I have a big problem with it, I can't think of any way around but to ask for an improvement in the React core itself.

For example, I have Route A and Route B, and in both routes, I have same Layout element, and I can't find a way to change route without un-mounting my Layout component

If there could be a way to mark the Route elements, and let it by pass the diffing algorithm, and go on checking the Layout elements like normal, then would be god sent improvement for me

Thanks a lot, and after 15 years of software development, React is the best thing ever for me

Quan

**Comment by threepointone** [comment]
I'd argue that you do want to remount the Layout component in your case. You can't be sure how it's changed during rendering and its lifetime. If there's state you want to share between A and B, it should be lifted to a component above them, and shared as a prop or context to its children.  

This is more of a usage issue, so closing.
