### ISSUE TITLE
scheduler package contains wrong es module flag

### ISSUE THREAD

**Issue by yesmeck** [facebook/react#16050]
**Do you want to request a *feature* or report a *bug*?**

**bug**

**What is the current behavior?**

The cjs version of scheduler includes the following line:

```javascript
Object.defineProperty(exports, '__esModule', { value: true });
```

https://unpkg.com/scheduler@0.14.0/cjs/scheduler.development.js

But it's definitely not an ES module.

The flag brokes our webpack build.

**What is the expected behavior?**

The cjs version should not include a `__esModule` flag.

**Comment by threepointone** [comment]
I'm not familiar with the details right now, is there something we can do here? We don't have ESM builds at all, so I'd love more information. Thank you!

**Comment by yesmeck** [comment]
Nevermind, it's correct, babel adds a `__esModule` flag when compiling an es module to a cjs module.
