### ISSUE TITLE
Nested react router with user authentication

### ISSUE THREAD

**Issue by paufar** [facebook/react#16052]
I am trying to make my app use nested React routers to navigate through my app but am not managing to do the following: I have a router to switch between the login page and the homepage and a router in the homepage to switch between the body content 

1. Return to login page on clicking log out. If i click logout the url goes to /login but does not render the right component. Upon refreshing the page the right component is rendered. 

2. When inputing a direct page in the url eg. localhost:3000/about, the page doesn't load anything

My desired functionality is the following: 
1. On load of localhost:3000/ - If user is logged in it loads the "About" component ELSE if user is logged out it is redirected to /login
2. On load of localhost:3000/contact - If user is logged in it loads the homepage and switches the body content to show the contact component , if user is logged out it redirects to the login page but on login takes the user to the contact component 
3. Clicking log out returns to the login component 

I have added the source code here: https://codesandbox.io/embed/loving-engelbart-x3ns3
The first router is in App/App.jsx and the body content router is in _pages/HomePage.jsx
Unfortunately i had to remove the login authentication so the login does not work but maybe there is a clear issue with my code that can be outlined.

Thanks

**Comment by ahtee** [comment]
Have you already tried filing an issue over at https://github.com/ReactTraining/react-router ? this doesn't seem to involve this repo...

**Comment by paufar** [comment]
Sorry will try and post it there - thanks
