### ISSUE TITLE
Show console warning when StrictMode is active

### ISSUE THREAD

**Issue by davidje13** [facebook/react#16061]
I am extracting this feature request from #12906, which was already closed when the feature was requested, so was likely lost.

**What is the current behaviour?**

When `<React.StrictMode>` is used, some functions will be intentionally double-invoked such as the render method. This is fine, but can lead to confusion for developers months later, as they try to figure out why something is being called twice during debugging, etc.

**What is the expected behaviour?**

From my comment on the other thread:

> The problem is that if strict mode was added long ago, it is not obvious what the source of the double-render is (I was hunting react-router and redux logic).
>
> I think it would be nice if strict mode printed a console statement when used anywhere on the page and currently enabled (i.e. in dev mode), akin to the existing "Download the React DevTools for a better development experience: https://fb.me/react-devtools" advert.
>
> Something like "Strict mode is enabled; some lifecycle methods including constructors and render will be double-invoked to check for side-effects"

The suggestion received some support on the original issue, and I think adding this feature would save developer time and confusion when working on codebases which have enabled strict mode during development.

**Comment by eps1lon** [comment]
This would be an issue for test suites that run with StrictMode and run matchers against console warnings and errors. 

Sure we could use the good old props-all-the-things approach with `<StrictMode logWarning />` but this would defeat the purpose of this issue which looks for a warning by default.

I guess my question would if 
```jsx
function MyStrictMode({ children }) {
  React.useEffect(() => {
    console.warn('This subtree was rendered in StrictMode. See the docs for all the methods that are invoked twice.').
  }, []); // warn once but it might help more to log this on every commit by omitting the dependency array
  return <React.StrictMode>{children}</React.StrictMode>
}
```
would be sufficient for you? With the new devtools you could even see in the console at which point in the tree StrictMode was enabled.

**Comment by davidje13** [comment]
@eps1lon well the point here is to make it easier for people who aren't aware of this (typically because they enabled it in the distant past), so any change of behaviour (either using the custom wrapper you suggest or using a prop) wouldn't really cut it. In my own codebase, I already include something similar after being bitten once, but the point here is to avoid people needing to be bitten the first time.

I suggest this should be an info-level log message, not warn or error. That should reduce any test-related impact. But also note that when the project is built as dev, React will *already* log an info message about getting the react tooling. When built for production, the message is not printed, and I suggest that this new message should also not be printed when built for production (since `StrictMode` has no effect in a production build anyway). That should result in no impact on anybody's tests.

**Comment by eps1lon** [comment]
> but the point here is to avoid people needing to be bitten the first time.

This is very strange to me. You added it once and it turned out to bite you. Why not revisit it and make it better?

> I suggest this should be an info-level log message, not warn or error. 

This would be fine. From my experience though it won't help since it will be logged before all the warnings. Many issues I see do have a warning right before the error and the warning is never read. Downgrading it to an info will only reduce the chance of it being read (especially since it's often filtered out in devtools).

**Comment by davidje13** [comment]
> You added it once and it turned out to bite you. Why not revisit it and make it better?

Sorry I don't understand this statement / question at all. Can you clarify?

> it will be logged before all the warnings

There are no warnings here. This isn't about strict mode warnings being generated (those can be searched for and understood by themselves, and make it quite obvious that strict mode is involved). It's about methods being double-invoked, and helping developers understand why.

To clarify, the problematic flow goes like this:

1. Developer adds `StrictMode`, and does all the necessary patching (if any) to make the codebase comply
2. Time passes
3. Developer is diagnosing an unrelated bug in the app (maybe a different developer than enabled StrictMode, or they have forgotten)
4. Developer adds console logging to some methods (e.g. a render method) to help diagnosis
5. Log lines are printed twice as often as expected
6. Developer starts hunting for why the double-invocation is happening

The request here is specifically to short-circuit the investigation in (6) by providing extra information in (5) (the developer would see an explanation at the top of the console, before their log lines).

**Comment by eps1lon** [comment]
> Sorry I don't understand this statement / question at all. Can you clarify?

It seems to be a common issue in your codebase that other developers do not know that StrictMode is present or why some methods might be invoked multiple times. Why does the library have to add a notice for the presence of a component you intentionally introduced? Why is it not possible for you to patch this yourself? Anything beyond that is a question about having proper documentation.

The question is also about precedence: What do you think should happen in concurrent mode? Should this also add a notice those methods will be invoked multiple times?

> the developer would see an explanation at the top of the console

My point wasn't strictly about warnings but anything in the console. From my experience the people you want to target read console logs bottom-up (and stop at the first issue) not top-down. This would render any notice at the top useless.

**Comment by davidje13** [comment]
I'm sorry; I think you haven't understood the request here. It sounds like you think this is about getting strict mode warnings in the codebase and not understanding why? I'd encourage you to take a look at the original issue (and subsequent comments) which spawned this for more context: #12906

Maybe I'm misinterpreting your comments and if so I apologise, but they don't seem to be related to the same problem as far as I can tell.
