### ISSUE TITLE
Am i using context horribly wrong?

### ISSUE THREAD

**Issue by jbures** [facebook/react#16064]
Hi there, my first time asking a question here :)

I don't have any problems at the moment (loving the react hooks btw).

I just want to ask for ideas on how to handle a particular scenario i have and if i am using the context hooks properly.

So my situation is with a form like this:

Context file: 

```
export const StepsContext = createContext({
    steps: []
});

```

This would be the "parent" component. 
```
const steps = useContext(StepsContext);

const sendForm = () => {
  callEndpoint(steps);
};

return <Form>

  <Input />  // Default input always present
  <Steps /> // Component that dynamically adds more inputs as i click on a button.

  <button onClck={sendForm} />
</Form>  
```

Inside the Steps component
```
// This component adds more inputs as i click on a button and sets a "config" state with the 
// values of each input, in an array that looks kinda like [ 0: { value: "value" }  ]
// Each new index is a new input

const context = useContext(StepsContext);
const [inputs, setInputs] = useState([]);

return <button onClick={addNewInput}/>

const addNewInput = () => {
 // Do something to add new input and set the config, so if we have two the config looks like:
// [ 0: { value: "somethig"}, 1: { value: "else" } ]

// And now i update the context so the parent knows how many steps we have and their config
context.steps = newConfig;
}
```

This works and i get the data where i want it, but for some reason this assignment i do: `context.steps = newConfig;` feels wrong hehe.

Am i doing it right? 
Can anyone throw any ideas at me on how to approach this or do it in a nicer way?

Thanks and kind regards.

**Comment by dmytro-lymarenko** [comment]
Do you use StepsContext.Provider?

Because you should also add a function to the context like this:
```js
createContext({
    steps: [],
    setSteps: () => {},
});
```
and then with `StepsContext.Provider` you should do this:
```js
const [steps, setSteps] = useState([]);

// we use memoized context value to prevent consumers be updated unnecessarily
const contextValue = useMemo(() => ({ steps, setSteps }), [steps, setSteps]);

return (
    <StepsContext.Provider value={contextValue}>
        <App />
    </StepsContext.Provider>
);
```
So, then when you use get context with `useContext` you can now correctly update `steps`:
```js
const context = useContext(StepsContext);
// ...
context.setSteps(newConfig);
```

**Comment by jbures** [comment]
I've seen this in some tutorials but i still don't fully understand how to use, besides using typescript give me some headaches when i can't match certain types...

But i'll try doing what you suggested @dmytro-lymarenko :) Does it mean that it is possible to update the context from the child safely?

**Comment by jbures** [comment]
This looks like it works halfway, because when i execute `context.setSteps(newConfig);` i get a re-render of the parent but context.steps is empty :(

**Comment by jbures** [comment]
Ok so if i move the Provider up in the hierarchy it works, but i must say i don't love this... basically i can't update context from a child and get the parent to read it, it has to be shared between siblings.
But at least the updating is nicer now, so thanks a lot!

**Comment by kiranjd** [comment]
@jbures  consider closing the issue if it's been resolved

**Comment by jbures** [comment]
> @jbures consider closing the issue if it's been resolved

Probably it is, thx :)
