### ISSUE TITLE
react-dom/server - how to ignore trans-pile some values with renderToString method

### ISSUE THREAD

**Issue by ebrahimiaval** [facebook/react#16068]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
how to ignore trans-pile some values with renderToString method?
more details: [https://stackoverflow.com/questions/56897860/reactdomserver-how-to-ignore-trans-pile-some-values-with-rendertostring-method](https://stackoverflow.com/questions/56897860/reactdomserver-how-to-ignore-trans-pile-some-values-with-rendertostring-method)

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by dmytro-lymarenko** [comment]
You can play around with this: https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html

**Comment by ebrahimiaval** [comment]
solution :
`<script dangerouslySetInnerHTML={{__html: 'myValue =' + JSON.stringify(props.obj)}} />`
