### ISSUE TITLE
eslint-plugin-react-hooks: Ensure reducer is pure

### ISSUE THREAD

**Issue by steida** [facebook/react#16079]
I just spend the whole day debugging a race condition where one dispatch sometimes called a reducer twice and because of my reducer wasn't pure, the app behaved incorrectly.

```ts
const reducer: Reducer<State, Action> = (state, action) => {
  const getSortedFocusables = () => {
    // Never do that! Reducer isn't pure!
    return [...state.focusables].sort(documentPositionComparator);
  };
```

As Sebastian told me: 

> One dispatch can call a reducer twice under certain conditions but it would call it with the old state as input. So if it's pure, it's unobservable. A reducer function must be pure.

A reducer function must be pure.
A reducer function must be pure.
A reducer function must be pure.
A reducer function must be pure.

I hope it's possible eslint-plugin-react-hooks could detect it, but I am not sure whether it's possible.

**Comment by threepointone** [comment]
Sorry if I"m missing this, but what part of this reducer isn't pure? please make a codesandbox repro. I'm also not sure how a linter could catch it. Maybe some cases that are directly inlined in the reducer, but it would confuse people who expect the same for all code.

**Comment by miraage** [comment]
`[...state.focusables].sort(documentPositionComparator);` is pure relative to state because you create a shallow copy. Could you please provide full example?

**Comment by steida** [comment]
documentPositionComparator has a side effect

If there is no easy eslint check, forget about
