### ISSUE TITLE
extract "hooks" logic for reuse in other component frameworks

### ISSUE THREAD

**Issue by askbeka** [facebook/react#16078]
**Do you want to request a *feature* or report a *bug*?**
*feature*

Will you consider extracting hooks logic from React?

Loving hooks idea, so much, but I am not able to use it at my work since I am tightly bound to webcomponents ecosystem, and React does not play nicely with it, even if it did it will add on a bundle size and complexity of learning multiple component frameworks for my colleagues.

Looking at libraries like [haunted](https://github.com/matthewp/haunted), which implements React after hooks version but with webcomponents and lit-html, there is a demand to implement it in other components frameworks or in  this case webcomponents.

If implementation will be extracted, there is a higher chance of hooks from user land to work across frameworks in same way and with less workarounds

**Comment by threepointone** [comment]
This probably won't happen. There are subtle differences between how other frameworks have cloned hooks. Besides, React's hooks are tied to its own internals/semantics. Thanks for asking though!
