### ISSUE TITLE
React typescript StandardLonghandProperties -moz-transform is missing

### ISSUE THREAD

**Issue by chezih** [facebook/react#16077]
I'm trying to put: "-moz-transform": "scale(" + zoom + ")" on react style

I got this error:
Unsupported style property -moz-transform. Did you mean MozTransform?

But I cannot see MozTransform in csstype/index.d.ts (interface StandardLonghandProperties)

What is the workaround? what is the correct key/class-name to use?

**Comment by jquense** [comment]
Typescript types aren't maintained by the react team, those are on definitely typed so should open up an issue there for ta type problems 👍
