### ISSUE TITLE
React ref incorrectly reports 0 height in production.

### ISSUE THREAD

**Issue by GriboryBogush** [facebook/react#16083]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
ImageViewer.js:
```
class ImageViewer extends React.Component {
  constructor(props) {
    super(props);
    this.state = { gotSize: false };
    this.containerRef = React.createRef();
  }

  componentDidMount() {
    // get zero here, only in production and only on the first run after refresh
    console.log(this.containerRef.current.clientHeight);
    this.setState({ gotSize: true });
    ...
  }
  ...
  render() {
    const { gotSize } = this.state;

    return (
         ...
        <div className={scss['canvas-container']} ref={this.containerRef}>
          {gotSize && <Canvas containerRef={this.containerRef} />}
        </div>
        ...
    );
  }
};
```
My css in container basically a box of width:100% and height: 100%, and it takes the full size in the inspector
Canvas.js:
```
class Canvas extends React.Component {
  constructor(props) {
    super(props);
    this.updateDimensions = this.updateDimensions.bind(this);
  }

  componentDidMount() {
    window.addEventListener('resize', this.updateDimensions);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.updateDimensions);
  }

  updateDimensions() {
   ...
   // and of course zero here, but only on the first run
   // after refresh, if I close and open the component the second time it works fine
    const rect = this.props.containerRef.current.getBoundingClientRect(); 
    ...
  }

  render() {...}
}
```
**What is the expected behavior?**
Get the correct height
env:
production: default create-react-app script `"react-app-rewired build"`
macOS High Sierra 10.13.6
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
"react": "^16.8.6"
"react-dom": "^16.8.6"

**Comment by threepointone** [comment]
Please provide a reproduction on codesandbox, or github repro.

**Comment by GriboryBogush** [comment]
I've tried to reproduce it in a minimal repo but failed so far. It most likely means that the code shown here in isolation does work fine...
I'll keep the issue updated if I find anything relevant.

**Comment by GriboryBogush** [comment]
I've found out that if I move the ref to a parent div I seemingly get the height of the elements that are children (128), even though they have different positioning (absolute)....
```
<div ref={this.containerRef} className={scss['canvas-container']}>
        <Toolbar edge="start" className={scss['portal-image-toolbar']}>
          <IconButton onClick={() => { this.props.history.push(`/search`); }}><ArrowBack /> 
            </IconButton>
        </Toolbar>
        <Toolbar className={scss['portal-image-toolbar-left']}>
          <OpenSideButton />
        </Toolbar>
        <div className={scss['canvas-container']}>
          {gotSize && <DynamicCanvas containerRef={this.containerRef} />} // now get 128
        </div>
        <UndoSnackbar />
      </div>
```

**Comment by threepointone** [comment]
This is likely not a react issue. I’ll leave this issue open for a couple more days if you can figure out a repro.

**Comment by GriboryBogush** [comment]
I solved the issue by setting inline style to `minHeight: '100%'`. For whatever reason in that production context, sometimes it would force min-height to zero, which would lead to component collapsing.
I'm not sure what kind of bug it is, so I'd like to hear your opinion.

**Comment by threepointone** [comment]
Honestly can't say, it could be anything from the way you build assets, to a third party component or something. Sorry I can't be of more help, hard to say without looking closer. I'll close this, but let me know if you find something.
