### ISSUE TITLE
npx create-react-app spawn ENOENT?

### ISSUE THREAD

**Issue by Eric-Johnston** [facebook/react#16099]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using npx create-react-app causes a "spawn enoent" error that points to my mongoDB folder. This only began after I installed mongoDB.

`$ npx create-react-app client`
`spawn C:\Program Files\MongoDB\Server\4.0\bin ENOENT`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
The steps I took to experience this bug was to install mongoDB and attempt to create a react app. Somehow I doubt following those steps will recreate the bug, however.

**What is the expected behavior?**
The expected behavior is that I'm able to create a new react app without any errors.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Version 16.8.6.

**Comment by CherryDT** [comment]
Same as https://github.com/facebook/create-react-app/issues/7347

Seems this keeps popping up though, see also [here](https://stackoverflow.com/questions/69532329/why-does-create-react-app-return-an-error) and [here](https://stackoverflow.com/questions/56959262/react-npm-start-error-after-installing-mongodb/56959462)
