### ISSUE TITLE
reactjs typescript support throws maximum stack size exceeded while the same runs in the old typescript enabled template 

### ISSUE THREAD

**Issue by franferns** [facebook/react#16098]
Using the new typescript supported version of reactjs https://reactjs.org/docs/static-type-checking.html#typescript along with redux-orm i get "**maximum call stack size exceeded**" error. 

here is the code which fails using the new template https://reactjs.org/docs/static-type-checking.html#typescript

https://drive.google.com/file/d/1tl19W2-DSNSZiVHuGoxjOLs0ooCTrDRl/view?usp=sharing

Now , the same is created using the old typescript template https://github.com/microsoft/TypeScript-React-Starter which works fine. Here is a link to the code which works fine.

https://drive.google.com/file/d/1eWmOkaKnbuRCpBEaFj7BUElq2C9IxoYD/view?usp=sharing

I want the same code used in the old version to be able to use in the new reactjs typescript supported template. 

Is there something the new template does which throws this issue ?

**Comment by gaearon** [comment]
Please file this in Create React App if you're referring to CRA's TS support.

React (the library) has no relation to TS.
