### ISSUE TITLE
[Feature] Return HTMLElement in functional components

### ISSUE THREAD

**Issue by abramov231** [facebook/react#16092]
For now functional components are able to return string or jsx. It would be awesome to have support of native HTMLElement instances as well. 

**What is the current behavior?**
```javascript
function SuperFastCustomComponent () {
  const el = document.createElement('div');
  ...
  return el;
}
// Throws error: Objects are not valid as a React child (found: [object HTMLDivElement]).
```

**What is the expected behavior?**
Just insert provided element in DOM.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest

**Motivation**
For some applications it needs to make UI as fast as possible. Especially it is critical on huge application with thousands elements which updates several times per second.  Virtual DOM in React provides good help for performance issues, but sometimes you need to go further and operate on level of vanilla js with incremental changes and custom virtual DOM model relevant to your application. For now the only way to do it is to use refs, but it is looks kind of ugly. Allow to return HTML elements will helps to solve this issue in elegant and intuitive way.

**Comment by dmytro-lymarenko** [comment]
How will you handle ssr in this case?

**Comment by abramov231** [comment]
For ssr we will can to write another implementation of provided component and provide it from some factory. Or we can add condition inside component and send HTMLElement only in case of browser rendering. Or we can provide implementation of this function as is to client and execute. There are a lot of ways, but easiest is just do not implement anything specific. It is always trade off, a lot of well optimized applications don't use ssr, because of ssr helps with first time rendering, but in some cases interaction timing is more critical.

**Comment by threepointone** [comment]
I'm not certain how returning real elements on every render would be more performant; in fact, if we created new dom elements on every render, it would be *slower*. It seems like you want explicit control of the nodes to do your own custom logic; our recommendation is to use refs. To make it look not ugly, you could maybe encapsulate the functionality in hooks?   



Closing this since it doesn't fall within the constraints of React.
