### ISSUE TITLE
[exhaustive-deps] Dependency list that is not array literal (false positive)

### ISSUE THREAD

**Issue by FredyC** [facebook/react#16096]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```js
  const memoPosition = React.useMemo(() => position && gpsToLatLng(position), [
    position && position.latitude,
    position && position.longitude,
  ])
```

Alternatively

```js
  const memoPosition = React.useMemo(
    () => position && gpsToLatLng(position),
    position ? [position.latitude, position.longitude] : [position],
  )
```

**Both of these version yield following lint error and are fixed like that which isn't correct outcome...**

> React Hook React.useMemo was passed a dependency list that is not an array literal. This means we can't statically verify whether you've passed the correct dependencies.eslint(react-hooks/exhaustive-deps)

```js
  const memoPosition = React.useMemo(
    () => position && gpsToLatLng(position),
    [position],
  )
```

**What is the expected behavior?**

I am not sure if there is a better pattern to tackle that use case. The `position` can be null and I am fine with `memoPosition` to becoming `null` as well. However, since I cannot call the hook conditionally 

Note, I am not memoizing because the computation would be heavy, but because the value is passed further down and would cause re-render of a much bigger tree when a position has not actually changed. The consuming component is 3rd party and it has default `React.memo` applied.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0-alpha.0 => 16.9.0-alpha.0
    react-dom: 16.9.0-alpha.0 => 16.9.0-alpha.0
    react-scripts: ^3.0.1 => 3.0.1 (not ejected)
```

**Comment by Lokeh** [comment]
Your deps list cannot change between renders, so the second one is definitely invalid.

You could try this:

```
let lat = position ? position.latitude : null;
let long = position ? position.longitude : null;

const memoPosition = React.useMemo(() => position && gpsToLatLng(position), [lat, long])
```

However it would probably be easier to simply recompute the memo anytime `position` changes.

**Comment by FredyC** [comment]
Thanks @Lokeh, your idea has worked out nicely.
