### ISSUE TITLE
Consider using reactjs.org instead of fb.me in react's error/warning messages

### ISSUE THREAD

**Issue by dehghani-mehdi** [facebook/react#16109]
Hi,

Facebook is blocked in my country (and I think in some other countries) and links like `https://fb.me/react-invalid-hook-call` are blocked for me, in order to see the related documentation of the link I have to use VPN. so if is possible please use another link shortener service or point to `reactjs.org` directly.

Thanks.

**Comment by threepointone** [comment]
We are considering this seriously. We are not sure when and how we'll do this, but it's on our minds. Thanks for the suggestion!

**Comment by bencefr** [comment]
One more reason is that current links require fb account! Please make this priority.

**Comment by threepointone** [comment]
Not stale, I think we do want to do this sometime.

**Comment by threepointone** [comment]
@bencefr I don’t think you’re right? Definitely does not require an fb account

**Comment by bencefr** [comment]
@threepointone , it definitely does, since fb.me/... just redirects to facebook.com main page to sign up.

**Comment by dehghani-mehdi** [comment]
@bencefr I just tested [https://fb.me/react-invalid-hook-call](https://fb.me/react-invalid-hook-call) and it redirects me to [https://reactjs.org/warnings/invalid-hook-call-warning.html](https://reactjs.org/warnings/invalid-hook-call-warning.html) without forcing me to log in into my facebook account.

**Comment by bencefr** [comment]
My bad, the link I used had a typo and should have been a 404. The redirect works but I would be against using fb.me anyway.

**Comment by threepointone** [comment]
More data for this, fb.me is blocked inside lots of corporate environments as it's considered "social networking". While I'm working on getting it unblocked in my own firm, I don't expect that to actually happen soon.

**Comment by tebeco** [comment]
I can't agree more with @val1984 
This probably would help tons of developper working within company with gateway like `McAfee`
Having a dedicated FQDN like `reactjs.org` is something that can be trusted
Using `fb.me` will never be whitelisted for many reason like redirect to facebook / analytics / etc ...

> We are considering this seriously. We are not sure when and how we'll do this, but it's on our minds. Thanks for the suggestion!

@threepointone how did it go ?

**Comment by cylim** [comment]
@threepointone @gaearon 
Sorry, my bad for creating the PR directly without asking. I was thinking about **better to have working warning than waiting for perfect solution**. 

Redirect links might redirect to invalid links too, one of the example is  [fb.me/react-mock-scheduler](http://fb.me/react-mock-scheduler)

I would suggest to create something like [_redirects netlify](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file), so that the public contributors can helps to update/monitoring the links whether needed.

**Comment by gaearon** [comment]
No worries. We appreciate the intent — it’s just unfortunate because that particular change isn’t something we can do.

I think your proposal with _redirect makes sense. Is this something you would be interested in implementing?

**Comment by cylim** [comment]
@gaearon Yes. I am happy to do it.

I can see that reactjs.org is hosting on Netlify, and I can see it is already using in reactjs.org website [_redirect reactjs.org](https://github.com/reactjs/reactjs.org/blob/master/static/_redirects).

Any preferred path for the short link?
`reactjs.org/{path}/{title}`

I can start with `link` as the path, it can be change easily later on.

**Comment by gaearon** [comment]
Thanks to @cylim for taking this issue and spending the time to solve it.

https://github.com/reactjs/reactjs.org/pull/3199
https://github.com/facebook/react/pull/19598

This will go out in 17.

**Comment by tebeco** [comment]
Thx a lot for this @cylim
