### ISSUE TITLE
[eslint-plugin-react-hooks] Dealing with constant values in hooks' closures

### ISSUE THREAD

**Issue by miraage** [facebook/react#16102]
I'm totally fine with the current exhaustive-deps implementation, yet I feel like it would be cool to have an option to tell plugin about constant values that will never change. 

Minimal example:
```jsx
const AuthProvider = ({ children }) => {
  const { http } = useContainer(); // container is immutable
  const [user, setUser] = React.useState(null);
  
  // exhaustive-deps wants to see "http" present in the deps list
  React.useEffect(() => void http.get('/whoami').then(setUser), []);

  ...
};
```

I wonder what options are available to make eslint happier. I believe some things could be done in AST/visitors layer, but no idea where to start.

**Comment by gaearon** [comment]
If it's truly constant then there's no harm in specifying it.
