### ISSUE TITLE
How to make button clickable under Link

### ISSUE THREAD

**Issue by nonanonakeita** [facebook/react#16119]
Post.jsx file
Code below is Post itself...
```
<Post>
     <Link to='/somewhere'>
         <contents>
             <usename />
              <date />
              <div onClick={doSomething}>Edit</div>
         </contents>
     </Link>
</Post>
```
How can I make the div tag button clickable under Link?

I wanna implement like this...
If I click anywhere in the post except edit button, I go to post detail page.
If click edit button, edit modal shows up instead of going to post detail page.
I believed I need to nest edit button trigger in the Link, but doesnt work.
How am I supposed to implement this?
Thank you.

LIke this...
![facebook_1199-141](https://user-images.githubusercontent.com/51696880/61104391-2d701e80-a4b1-11e9-9d9b-39207d0d34cc.jpg)

**Comment by bohdanbirdie** [comment]
@nonanonakeita hi
I'm not sure that this is the right place for this question
Anyway, I assume you're using the React Router
here is a working example
https://codesandbox.io/s/sharp-cray-0eem7

**Comment by nonanonakeita** [comment]
@bohdanbirdie 
Thank you for your replay.
This is not what i wanna do.
My explanation wasnt good. I fixed code example in the description.

**Comment by bohdanbirdie** [comment]
@nonanonakeita updated code for you
https://codesandbox.io/s/sharp-cray-0eem7

**Comment by nonanonakeita** [comment]
@bohdanbirdie 
Wow! That's amazing 
Thank you very much.
So, the point is that I need to use `e.preventDefault()`.
Thank you again!!
