### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by bochen2014** [facebook/react#16117]
I didn't see it's mentioned somewhere else so I'd try to open a new thread for it. Sorry if it's already reported/discussed.

I spent quite a while trying to understand why [this](https://codesandbox.io/s/react-context-api-c81jb) doesn't work, as it's a VERY simple user case and I was following the new context api instruction verbatim when doing it 

I know how to make it work, but it's more like a walkaround. I really want to know why my example doesn't work and if it's a bug, we should fix it.

thanks

**Comment by pixcai** [comment]
```shell
Warning: This can also happen due to a circular dependency, so try moving the createContext() call to a separate file.
```
if you define the `BankerBSBContext` in another file, e.g. `context.js` and `import BankerBSBContext from './context`, It can work properly.

**Comment by TrySound** [comment]
I think the problem are circular dependencies. And it's expected something does not work because of them. I use rollup to detect such cases.

**Comment by bochen2014** [comment]
thanks both for answering my question. 

I knew that put context in a separate file would solve the problem -- this is the walkaround that I was talking about. What I failed to understand is why "circular dependency" is an issue for context

I think node or in our case, webpack , is able to solve circular dependency.  example [this](https://codesandbox.io/embed/sharp-cookies-1ngtz)

**Comment by bochen2014** [comment]
is this a webpack issue or react issue ?  I think it's a react issue

**Comment by TrySound** [comment]
Webpack is able to solve this in development mode. But in production we deal with scope hoisting. Here's simplified version
```js
// chunk.js
class Chunk extends React.Component {}

Chunk.contextType = Context // var is hoisted but has value undefined yet

// index.js
var Context = React.createContext()

render(<Context.Provider value='value'><Chunk /></Context.Provider>)
```

**Comment by aweary** [comment]
This is expected behavior, and not related to React at all. [Here's an example of the same problem without React](https://codesandbox.io/s/frosty-mendel-0s9eh). Moving the context to a separate file is a good solution.

**Comment by bochen2014** [comment]
thanks @TrySound  and  @aweary for the insight! that makes sense to me!

Now I understand how webpack deal with circular dependencies :smile:

**Comment by bochen2014** [comment]
btw, just for discussion purpose, don't think this is 'hoist' related; 
yes javascript will hoist variable declarations, but , I don't think that will happen across different modules

I think it's more a question about, what does nodejs or webpack do, as a module system tool,  when an import can not be satisfied due to circular dependency --- throwing a compile error would be a much better option than having the 'undefined' value, in my opinion

 it's a good discussion thanks @TrySound again
