### ISSUE TITLE
Reconciliation performance function vs. class components

### ISSUE THREAD

**Issue by thomasnordquist** [facebook/react#16112]
**Do you want to request a *feature* or report a *bug*?**
neither/bug

**What is the current behavior?**
While migrating class components to function components (with hooks), I noticed a **significant performance drop**. I have a component (called `TreeNodeComponent`) which is part of a tree-structure. Depending on the tree size, hundreds of instance could be visible. 

[Wrapping the function component in a PureComponent](https://github.com/thomasnordquist/MQTT-Explorer/commit/1a1596ad3db61a5b7a431f55799a8de2631bb4f1) significantly reduced the observed "render time". (From ~160ms to ~60ms)

### "Render time", observed in Chrome Dev Tools
<img width="347" alt="Bildschirmfoto 2019-07-11 um 16 24 10" src="https://user-images.githubusercontent.com/7721625/61058938-7912c180-a3f8-11e9-8a4d-f3fe2d1d9823.png">

### Context:
The App renders hundreds of these `TreeNodeComponent` in a `tree-structure`. When a parent is updated, all direct children need to be reconciled.
Project: https://github.com/thomasnordquist/MQTT-Explorer

**What is the expected behavior?**
Comparable performance between functional and class components.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

OSX
Chromium 73 / Electron 5.0.5
React 16.8
Typescript & Webpack

**Comment by aweary** [comment]
> Wrapping the function component in a PureComponent significantly reduced the observed "render time". (From ~160ms to ~60ms)

Thats expected if rendering `TreeNodeComponent` is expensive. `React.PureComponent` bails out early if props haven't changed.

> While migrating class components to function components (with hooks), I noticed a significant performance drop.

Are you saying that going from a class extending `React.Component` to a function component caused a performance regression? Or were you already using `React.PureComponent` (or `shouldComponentUpdate`)

 You can use [`React.memo`](https://reactjs.org/docs/react-api.html#reactmemo) to get the same bailout semantics with function components.

**Comment by thomasnordquist** [comment]
I migrated from a `React.Component` with `shouldComponentUpdate`.

I use `React.useMemo` to avoid "rendering".
`React.memo` yields results as good as those from `PureComponent`. (~50-60ms)

Thanks a lot for clarifying.

**Comment by TheMisir** [comment]
I did not get which is preforming better: functional components or class components. What should I use for long lists
