### ISSUE TITLE
Controlled input doesn't trigger onChange when value changes, how can I trigger SyntheticEvents?

### ISSUE THREAD

**Issue by odrzutowiec** [facebook/react#16124]
**Do you want to request a *feature* or report a *bug*?**
no, its a question

**What is the current behavior?**
onChange is not triggered when value of controlled input changes

1. type something in the input -> console logs with SyntheticEvents
2. click the button -> nothing :(

https://codesandbox.io/s/dry-wood-rsgx1

**What is the expected behavior?**

2. click the button -> console logs with SyntheticEvents

I need it to trigger onChange events. I am designing an autocomplete component and I want it have exactly the same "api" as standard `<input />`. That means whenever a use clicks one of the suggestions and that suggestions is being pasted into the input field, that input field should trigger standard onChange so that it can seamlessly integrate with other libraries (like formik)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 16.8, chrome 75, mac os 10.14

**Comment by Lokeh** [comment]
Assuming you're building your own `AutocompleteInput` component, you should call `onChange` yourself when an autocomplete occurs.

```
function AutocompleteInput(props) {
  return
    <div>
      <input {...props} onChange={e => { props.onChange(e.target.value); }} />
      <button onClick={() => { props.onChange('hi') }}>Hi</button>
    </div>;
}
```

**Comment by odrzutowiec** [comment]
Hi @Lokeh thanks for answering,

Your answer doesn't address my problem because the specific scenario I want to handle is when a user clicks something from the autocomplete list. 

So in simple words I want my <input> to trigger standard onChange when i change the value prop. And I want to emphasise it has to be the _standard event_, not just the value.

I am not sure if I'm describing my problem clearly, sorry. Let me know if anything is unclear.
