### ISSUE TITLE
IE11 Syntax error when using Contexts

### ISSUE THREAD

**Issue by miluna** [facebook/react#16137]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
IE 11 is displaying blank page when using React Contexts. Console says Syntax Error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://github.com/miluna/react-IE11-bug-minimal

**What is the expected behavior?**
Page rendering using React Router, Contexts and the necessary polyfills, just like Google Chrome

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Win10, React 16.8.6, IE11, Chrome v75

**Comment by Eddie-CooRo** [comment]
> Support for Internet Explorer 9, 10, and 11 requires polyfills.
Quote from the create-react-app documentations. ([link](https://facebook.github.io/create-react-app/docs/supported-browsers-features#supported-browsers))

**Comment by miluna** [comment]
Hi, I already tried 'react-app-polyfill/ie11', '@babel/polyfill' and 'core-js' imports. None of them solve the issue.
Regards

**Comment by juands92** [comment]
Hi, I actually had the same problem using Redux instead of Context API, and by adding react-app-polyfill it works. Anyway react-app-polyfill is not working with my Context API project at IE11. Any clue ?

**Comment by Dergash** [comment]
Hello @miluna! If you've tried 'react-app-polyfill/ie11' and it didn't help then you probably either:
1) Forgot to change browserlist.development section in your package.json. By default it looks like:
```json
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```
When you launch your project with "start" command webpack-dev-server is launched and "development" browser list is used and it does not include ie11. It should be the same as production:
```json
    "development": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
```

2) Encountered a problem with [babel caching](https://github.com/facebook/create-react-app/issues/6924#issuecomment-487306762) and babel didn't update its config based on your new settings; deleting node_modules folder and install again should help.

[I made a PR](https://github.com/miluna/react-IE11-bug-minimal/pull/1/files) for your example and it launched:

![ie11-polyfill](https://user-images.githubusercontent.com/13132449/62411874-2eb1e880-b624-11e9-9d7c-8b235f2ab5a0.PNG)
