### ISSUE TITLE
useState can't hold "function" into state value

### ISSUE THREAD

**Issue by damianobarbati** [facebook/react#16131]
Running the following snippet in a React "powered by hooks" app, the `getAsyncOptions` is not holding a function but a pending promise: the `getAsyncOptions1` is automatically invoked. 

Is this a known and expected behaviour? Does it mean I cannot put a function into a state variable otherwise it is automatically called?

```
const getAsyncOptions1 = async () => {
    await sleep(2500);
    return ['first', 'second', 'third'];
};

const getAsyncOptions2 = async () => {
    await sleep(2500);
    return ['apple', 'pear', 'banana'];
};

const App = props => {
    const [getAsyncOptions, setGetAsyncOptions] = useState(getAsyncOptions1);
    console.log('what is getAsyncOptions?', getAsyncOptions);

    useEffect(async () => {
        await sleep(5000);
        console.log('changing getAsyncOptions');
        setGetAsyncOptions(getAsyncOptions2);
    }, []);
```

**Comment by dmytro-lymarenko** [comment]
It is because useState can be lazy with function argument: https://reactjs.org/docs/hooks-reference.html#lazy-initial-state

**Comment by damianobarbati** [comment]
Doh! 

So my only chance is to wrap my `getAsyncOptions1` and `getAsyncOptions2` in another function? Thus the result returned is the actual function I want in the state. 

I can work it around with that even if it doesn't seem to be the best: should I close the issue?

**Comment by dmytro-lymarenko** [comment]
yes, something like this:
```js
useState(() => getAsyncOptions1);
```
