### ISSUE TITLE
scheduler package use set but don't use es6-shim

### ISSUE THREAD

**Issue by souoxs** [facebook/react#16146]
When I use a vivo phone，I find a browser console error, That is scheduler package use set, 
Like: 
subscribers = new Set();

But Browser don't support es6 

Can you help me Fix this ?

**Comment by souoxs** [comment]
I use Version is scheduler: 0.14.0

**Comment by threepointone** [comment]
We have a page that describes what polyfills you need https://reactjs.org/docs/javascript-environment-requirements.html
