### ISSUE TITLE
Deno support or Deno rewrite pilot program

### ISSUE THREAD

**Issue by inunotaisho26** [facebook/react#16140]
# 🚀 feature request
Would like [Deno](https://deno.land/) runtime support.

### Description
This is a new runtime that has was created by [Ryan Dahl](https://en.wikipedia.org/wiki/Ryan_Dahl), the original creator of [NodeJS](https://nodejs.org/en/). It has several new advantages:

- Use of Promises
- Uses TypeScript out of the box
- no need for node_modules
- uses urls to load dependencies (might be a plus or minus).

**Comment by Maskedman99** [comment]
Deno 1.0 is released, would love to see it improve react

**Comment by sant123** [comment]
Definitely want to see it.

**Comment by Marckon** [comment]
Hope to have a glance 😃
