### ISSUE TITLE
addons.update directive precedence order

### ISSUE THREAD

**Issue by DalekBaldwin** [facebook/react#1615]
```.js
var an_array = [0,1,2,3,4,5];
React.addons.update(an_array, {4: {$set: '$set'}, $push: ['p','u','s','h'], $unshift: ['u','n','s','h','i','f','t'], $splice: [[1,1,'$splice','slice','dice']]});

// result:
["t", "$splice", "slice", "dice", "$set", "h", "s", "n", "u", 0, 1, 2, 3, 4, 5, "p", "u", "s", "h"]
```

Is this a sane ordering for handling these directives? I'd never want to have `update` recurse into something I've already `$push`ed, `$unshift`ed, or `$splice`d in -- otherwise I would have included the changes in those directives' arguments originally. I think the most natural expectation would be that update should recurse into existing elements at their indices in the original array, then splice in the `$splice` directive, then `$push` and `$unshift` new elements to ensure they appear at the ends of the resulting array, like this:

```.js
["t", "f", "i", "h", "s", "n", "u", 0, "$splice", "slice", "dice", 2, 3, "$set", 5, "p", "u", "s", "h"]
```

 As it is now, for certain cases, the programmer would have to introduce difficult-to-visually-inspect index-twiddling logic or split the changes up among multiple calls to `update` to produce the desired result.

The tests for `update` don't include any cases where multiple directives appear for a single value, so I'm not sure whether this is intentional or whether anybody depends on this behavior. But especially when you're dealing with trees of this form:

```.js
{...
 children:
 [{...
   children:
   [{...
     children:
     [...]
    }
    ...]
  }]}
```

the current behavior really doesn't allow for the same visual clarity that makes `update` so helpful for trees composed entirely of objects.

**Comment by gaearon** [comment]
We are handing over `update()` to the community so I’m closing this.
Please see my note in https://github.com/facebook/react/pull/6353#issuecomment-204219214.
