### ISSUE TITLE
How add resize height to element on hover

### ISSUE THREAD

**Issue by yaverm** [facebook/react#16158]
In my react project i want show modal on hover, but when hover last elements crashed layout, how i can add resize height to parent div on hover ?

https://codesandbox.io/embed/hardcore-poitras-mt2mw?fontsize=14

**Comment by DivaWeb** [comment]
This is can be done with simple css.  So I changed your css a little bit.
`figure {
  width: 150px;
  border: 1px solid black;
  padding: 10px;
  position: relative;
  z-index: -1;

}
img {
  max-width: 100%;
  position: relative;
  z-index: -1;
}
.item-modal {
  background: gray;
  width: 250px;
  position: absolute;
  top: 0;
  left: 0;
  display: none;
  z-index: 2;
}
 .item:hover {
  transform: scale(1.25);

}
.item:hover .item-modal{
  transform: scale(.75);
  display: block;
}
.txt {
  padding: 10px 50px;
}
 `

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
