### ISSUE TITLE
Can I download all tutorial pdf

### ISSUE THREAD

**Issue by meteerogl** [facebook/react#16159]
Ictually I want to read tutorial on bus or metro so şs there any download pdf option

**Comment by vasil-dimov** [comment]
You have different options for this:

-  phone/tablet on chrome browser you can download page by page for offline using (https://support.google.com/chrome/answer/7343019?co=GENIE.Platform%3DAndroid&hl=en)
- you can save a page by page on your computer:
 open  page -> 
 click right button on mouse and choice print option ->
 save like pdf
- you can use a library like this https://support.google.com/chrome/answer/7343019?co=GENIE.Platform%3DAndroid&hl=en or you can search in GitHub for another library which can help you.
