### ISSUE TITLE
set hook not working inside an event handler

### ISSUE THREAD

**Issue by MatteoGioioso** [facebook/react#16153]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
set hook not working inside an event handler

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal** 
this is the reproduction of the "bug": https://codesandbox.io/s/react-hooks-counter-demo-ds67o

**What is the expected behavior?**
it should set state inside an event handler

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
"react": "16.8.0",
"react-dom": "16.8.0",
"react-scripts": "3.0.1"
```

**Comment by jquense** [comment]
You got a stale closure in your effect b/c it only captures the count value when it ran, e.g. the on Mount. The lint error is trying to tell you it's a problem, and a good example of why the rule exists even tho it may seem like it's being silly or overly protective.

You can use a ref to store the current `count` or better still use the function updater signature of setState: `setCount((prevCount) => prevCount + 1)`

**Comment by MatteoGioioso** [comment]
@jquense Ok I understand.

> better still use the function updater signature of setState

I figured that out at the last minute :smile:  Thanks
