### ISSUE TITLE
setState freezes UI for some seconds

### ISSUE THREAD

**Issue by arswaroop** [facebook/react#16150]
**Do you want to request a *feature* or report a *bug*?**
i guess bug 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I am a noob in react but this is bugging me and couldn't find any relevant examples online.

On checkbox onchange, I'm changing the state using setState like this- 
```
handleDeleteCheckboxChange=({ target }, id) => {
    const { deleteMappings } = this.state;

    const check = target.checked;
    if (check === true) {
      const addToExisting = deleteMappings;
      addToExisting.push(id);
      this.setState({ deleteMappings: addToExisting });
    }
    else {
      const removeId = deleteMappings.filter(item => item !== id);
      this.setState({ deleteMappings: removeId });
    }
  }

```

Set state works but each time checkbox is changed, it takes a full second to two to get updated on the screen. I tried to remove setState and its fast. 

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by artuross** [comment]
I believe this happens because you're updating existing array. You need to copy the array, update it and then update the state.
