### ISSUE TITLE
Add find/scry by ID to test utils

### ISSUE THREAD

**Issue by feifanzhou** [facebook/react#1616]
TestUtils currently has `scryRenderedDOMComponentsWithClass` and the `find` variant, but nothing like `findRenderedDOMComponentWithID`. This functionality would make testing a lot easier.

**Comment by spicyj** [comment]
We're not planning to add more utils like this to TestUtils. You can always implement this locally in your project as a helper if you want to, but we're planning to move towards shallow testing (i.e., TestUtils. createRenderer) in the future.
