### ISSUE TITLE
Once again on getDerivedStateFromProps being called after setState

### ISSUE THREAD

**Issue by sarat12** [facebook/react#16162]
I've read all the issues end blog posts on this topic and still can't find suitable solution for my case. I'm still in the 16.3 camp, though I must be just not competent enough to judge. Please help me to do things right. So I have a sort of pivot grid component with quite heavy state and a GridCell (uncontrolled or semi-controlled) component which is basically one number input. So the value and onChange are cycled through it's state and in parent component I'm handling just onBlur. So in order to do some validation when users enter unacceptable value I notify them and then I want to reset the cell by resetting prevState. [Here](https://codesandbox.io/s/musing-mclaren-qvclh) is a simplified reproduction of the problem.

**Comment by muzakparov** [comment]
Not related to `getDerivedStateFromProps`, per documentation iit gets called every time before `render` method.
Please read documentation: https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

You will need `componentDidUpdate` for your case. 
I made some changes please see [Here](https://codesandbox.io/s/old-fire-ud465)

If you need more suggestions, Stackoverflow would be better for this question.

**Comment by sarat12** [comment]
muzakparov, thanks a lot! Completely misunderstood componentDidUpdate lifecycle method.
