### ISSUE TITLE
Unicode iconfont didn't render when using map function of lists.

### ISSUE THREAD

**Issue by rhzone** [facebook/react#16170]
**Do you want to request a *feature* or report a *bug*?**

- Bug

**What is the current behavior?**

- ReactDom just renders unicode iconfont as plain text when using map function of lists, instead of iconfont. 
  ![image](https://user-images.githubusercontent.com/30968676/61594654-eefd0100-ac20-11e9-9cc0-7f7007a1cc39.png)

- However, it can render well when  I hardcode the lists without using map function.
  ![image](https://user-images.githubusercontent.com/30968676/61594627-87df4c80-ac20-11e9-9936-fddb75327141.png)

**Steps to reproduce this bug**
1. Create an iconfont project from Alibaba [iconfont](https://www.iconfont.cn).
    Like this
    ![image](https://user-images.githubusercontent.com/30968676/61594159-e30e4080-ac1a-11e9-8833-4d6d9daddc9c.png)
2. Make a list to render these icons using iconfont unicode.
    ```js
    lists.map((list, idx) => (
        <li key={idx}>
             <i className="iconfont">{list.unicode}</i>
        </li>
    ))
    ```

**What is the expected behavior?**

- Render these iconfont as icon instead of plain text.

**Which versions of React, and which browser / OS are affected by this issue?**

- Broswer: Google Chrome, Version 75.0.3770.100 (Official Build) (64-bit)
- OS: Ubuntu, Version 18.04.2 LTS (Bionic Beaver)
- React: Version 16.8.6

**Comment by otakustay** [comment]
React will always encode html, try [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml):

```jsx
lists.map((list, idx) => (
  <li key={idx}>
    <i className="iconfont" dangerouslySetInnerHTML={{__html: list.unicode}} />
  </li>
)
```

**Comment by rhzone** [comment]
> React will always encode html, try [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml):
> 
> ```js-jsx
> lists.map((list, idx) => (
>   <li key={idx}>
>     <i className="iconfont" dangerouslySetInnerHTML={{__html: list.unicode}} />
>   </li>
> )
> ```

Thanks, it works.
