### ISSUE TITLE
Allow overriding non-lifecycle component methods using a mixin

### ISSUE THREAD

**Issue by mjackson** [facebook/react#1617]
I'd like to be able to override a non-lifecycle component method without React throwing. Something like:

``` js
var MyMixin = {
  someMethod: function () {
    // the default behavior
  }
};

var MyComponent = {
  mixins: [ MyMixin ],
  someMethod: function () {
    if (needsToOverrideMixinBehavior) {
      // override the mixin's behavior
    } else {
      MyMixin.someMethod.apply(this, arguments);
    }
  }
};
```

Ideally, this would eventually be doable using [some sort of hierarchy system](https://github.com/reactjs/react-future/blob/master/01%20-%20Core/02%20-%20Mixins.js) (and possibly `super`), but for now I just want the ability to override a mixin method.

**Comment by bitmage** [comment]
@mjackson just an idea... a simple workaround is to use a conditional:

```javascript
var MyMixin = {
  onSomethingHappened: function() {
    this.doSomething ? this.doSomething() : this.defaults.doSomething();
  },
  defaults: {
    doSomething: ...
  }
}
```

If you find yourself doing this with a lot of different properties, you could generalize the pattern:

```javascript
var MyMixin = {
  getPropOrDefault: function(propName) {
    return this[propName] ? this[propName] : this.defaults[propName];
  }
  onSomethingHappened: function() {
    this.getPropOrDefault('doSomething')();
  },
  defaults: {
    doSomething: ...
  }
}
```
