### ISSUE TITLE
useEarlyEffect or cancelled render cleanup hook request

### ISSUE THREAD

**Issue by CaptainN** [facebook/react#16175]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
There is no way to run a side-effect generating hook before the first render.

**What is the expected behavior?**
For certain platforms (like Meteor) the reactive data access paradigm both runs immediately (data can be available on first render), and sets up side effects for later updates. I'd like to be able to set all that up *before* the first render, instead of waiting a render pass with `useEffect`. [Currently](https://github.com/meteor/react-packages/pull/271), we have to jump through hoops to make sure sure we don't generate side-effects early, then duplicate effort later to actually set up the desired side effects. (we had been simply setting up the side-effects in sync with render, but understand that [upcoming Suspense features](https://overreacted.io/algebraic-effects-for-the-rest-of-us/#how-is-all-of-this-relevant-to-react) may cancel a render cycle, and never run the `useEffect` cleanup hook). A hook which ran before render (or synchronously with first render) with it's cleanup method in case the render pass is thrown away, would solve the issue nicely, without hoop jumping.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.x. Previous versions of react had life cycle methods `componentWillMount` or even just the constructor which could be used for similar behavior.

**Comment by otakustay** [comment]
How about this:

```js
const EMPTY = {};

const useInitialEffect = effect => {
  const clean = useRef(EMPTY);
  if (clean.current === EMPTY) {
    clean.current = effect();
  }
  // Will clean after the first render
  useEffect(
    () => {
      clean.current && clean.current();
    },
    []
};
```

**Comment by CaptainN** [comment]
That works in the current version of React (and it's what we did in the Meteor hook), but as I understand it, with Suspense React may throw away the current render without completing the hooks - so cleanup would never run. If that understanding is incorrect, then I don't need anything new here. If I got it right, then I need either a hook that will complete with Suspense, or we need a way to know when to run cleanups for discarded render passes.

**Comment by otakustay** [comment]
I created a sandbox which reflects your statement: https://codesandbox.io/s/suspense-effect-no-cleanup-xwjjj

Yes the early effect is run twice but only cleaned up once even though I tried some hacks, with suspense it is not safe to believe a ref attached effect will be cleaned

**Comment by CaptainN** [comment]
Is there a way to detect when something like this has happened? If not, I have to change what is a simple system into something inefficient by default.

Meteor's system has data available immediately, but also sets up side-effects when accessing that data. Currently we do before rendering (in the hook):

1. Get data, and set up side-effects (create a Meteor computation).
2. Render.
3. Reactive updates later will trigger render.
4. useEffect's cleanup handler stops the computation when the component is done.

If I have to workaround Suspense, and can't create the computation in render, then we have to do all this:

1. Get data without setting up side-effects.
2. Render
3. useEffect runs, setting up side-effects, and getting data a second time.
4. Render
5. Reactive updates later will trigger render.
6. useEffect's clean up handler and stops computation when the component is done.

This is inefficient by default because it forces two complete render cycles for one set of data, which seems like a bad default.

(I had tried a solution where we don't do the second render, but that sets up a race condition - what happens if the data had changed in between? Because there's no reactivity set up after the first render, there's no way to know, so we have to render again.)

**Comment by otakustay** [comment]
I can make this possible via 2 methods, here is the sandbox: https://codesandbox.io/s/suspense-early-effect-possible-tdgsp

## Context

The first solution is to create a context above `Suspense` to hold all cleanups, async functions must be invoked via a custom hook `useAsync`, early effects are used via another custom hook `useEarlyEffect`.

The `useEarlyEffect` hook actually register a cleanup function in context (stored by a ref) and every time when a Promise is thrown, it calls `cleanup()` function provided via context.

Context is always a cheater in react, I can even make a custom fiber reconciler with a complex context.

## Lift effects

The second solutions is more "react style", we simply lift early effect to a parent component `LiftSuspense`, this component will return `null` on the first render to have a stable chance to cleanup all early effects, then the actual suspense and children will be rendered there.

I believe this is the recommended way to handle "early" effects, also in this solution we don't really need to run effect before the `LiftSuspense`'s render since `children` is not actually rendered, this could be a more reliable one:

```js
export const LiftSuspense = ({effect, ...props}) => {
    const [ready, goReady] = useReducer(() => true, false);
    useEffect(
        () => {
            const cleanup = effect();

            return () => {
                cleanup();
                goReady();
            };
        },
        []
    );

    return ready ? <Suspense {...props} /> : null;
};
```

---

I roughly simulates async calls in suspense by making api functions return primitive value or promise in different branches, as we know this is not a good practice. Recently I'm working on a all-in-one solution with `Suspense` called [react-suspense-boundary](https://ecomfe.github.io/react-suspense-boundary/) which combines a error boundary and a suspense, it is near ready to publish.

**Comment by CaptainN** [comment]
I wonder if it would be acceptable to ask the user to use an alternative Suspense container this way if they are also using our Meteor hook. Interesting.

I was actually thinking along similar lines, but hoping for something in core. If React could provide a simple method to know when the current render has been cancelled, like through a `useContext` with some kind of signal, then we can know when to clean up.

Alternatively, Suspense could provide a suspended data store. If I could get access to a ref from a useSuspenseContext, I could set up my side-effects the way I do now, and store them on the suspended ref - then when the component is re-rendered after being cancelled, I could just resume what's already been done (instead of tearing down, then building up again). That would be the most optimal, but I understand that some of this stuff with throwing away trees is not about being the most optimal in a straight line. I just would like some way to know when my work is being tossed.

**Comment by CaptainN** [comment]
What if we did something super simple:

1. Create side effect in render (or useMemo), and set a timeout with a cleanup method (maybe 50ms)
2. In `useEffect` cancel the timeout, and check the side-effect, to see if it's still valid (in meteor that would mean make sure we still have an active computation), and if so continue on, if not recreate the side-effect.
3. Inside the side-effect handler, we'd just have to check in some way that the current handler still belongs to the current side-effect.

Could it be that easy?

**Comment by CaptainN** [comment]
I actually got a version of this working - it's simpler than I thought, but there may be a race condition. It does this:

1. Set isSuspended to true by default in useRef
2. In useEffect set refs.isSuspended to false. If useEffect ran, the contract says its cleanup will run too.
3. In a timeout, see if refs.isSuspended is true - if so, dispose.

The problems which remain, I don't know how long is appropriate for the timeout period (is there an expectation for how long it will take between render and `withEffect` invocation?), and I don't know how to check if the render has been tossed without checking a flag set in `withEffect`. Now I'm back to the original feature request lol.

**Comment by CaptainN** [comment]
Also, does any of this matter for any other feature - will concurrency mode scuttle renders in the same way that suspense can?

**Comment by CaptainN** [comment]
I think I understand the issue - and why what I've requested cannot happen.

So I suggest an alternative - a way to register something like garbage collection, which will be run an indeterminate amount of time later (maybe after some number of paints, or whatever the timing may be between render and `useEffect`), with a way to cancel it. This way, we can register for cleanup, then cancel it when/if the `useEffect` hook fires, confirming the render has been committed. I actually already set something like this up using `setTimeout`, but I wonder if there is merit for a first class API.

If not, please close this issue.

**Comment by gaearon** [comment]
This is the same as https://github.com/facebook/react/issues/15317 so let's keep discussion there. For now we don't have plans to provide a GC phase but we'll see.
