### ISSUE TITLE
Request for support of oncuechange event on <track> elements

### ISSUE THREAD

**Issue by JofBigHealth** [facebook/react#16174]
## What

Feature request for `oncuechange` event handler as prop for `<track>` html element.

## Why?

To develop custom subtitles/captions it is necessary to listen to listen to this event in order to determine which entry from the subtitle file to render and at what time.

As of ReactDOM 16.8.6 this is not supported.

## Current workaround

You can see from [this codesandbox](https://codesandbox.io/s/request-for-oncuechange-support-in-reactdom-7dltb) the only workaround is to manually assign an event listener for the `oncuechange` since `onCueChange` does not exist.

**Comment by JofBigHealth** [comment]
Bump for stalebot.

**Comment by JofBigHealth** [comment]
Bump for stalebot

**Comment by gregorybolkenstijn** [comment]
Can this be reopened?

**Comment by jakekara** [comment]
I would like to see this feature as well.

**Comment by spacewindow** [comment]
Me too

**Comment by keyurparalkar** [comment]
I would like this feature as well.

**Comment by Jimgitsit** [comment]
Why does this keep closing? How much activity does a feature request need?

I too would reeeeealy like this feature and don't understand why it wasn't implemented in the first place.
