### ISSUE TITLE
Why is react-dom so big? Why can't we tree-shake it?

### ISSUE THREAD

**Issue by sigginet** [facebook/react#16173]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Bundling react-dom with the current CJS module is _HUGE_ - 124KB of stuff we don't use.
The bundle can be so much smaller by adding the source files into the npm package and enabling users to do a proper tree-shaking by defining the file in webpack

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
![image](https://user-images.githubusercontent.com/1608474/61644207-ceba5a00-ac93-11e9-80b5-84537a938c9d.png)

**What is the expected behavior?**
When bundling with webpack, we should be able to properly tree-shake the unused code automatically.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.6
Browser Chrome 75
Linux

**Comment by threepointone** [comment]
"The bundle can be so much smaller by adding the source files into the npm package and enabling users to do a proper tree-shaking by defining the file in webpack" This isn't particularly true. I don't think it would remove anything, since we don't actually ship any dead code. If you aren't using one of react's core functionality (eg - events, or state), the better option might be to not use react at all. 

Do you have any concrete examples of code we shouldn't ship in the bundle?

**Comment by sigginet** [comment]
That doesn't make any sense.
Do you use all of lodash just because you use a part of it's functionality?
(I hope the answer is no)

In this particular example, I'm highlighting an initial load issue. React-dom is a big part of the initial parsing, solely for the hydrate function.

I may use other react core functionality somewhere deeper in the application, but that doesn't mean that I need to make every single user download, parse and load every single part of the core react functionality.

When you only need a Philips size 2 screwdriver, you don't need to bring a whole tool-chest with you.

I'll check if I can manually inject this code and shake some core functionality off this, but the react-dom CJS is just huge. I refuse to believe that this is the minimum required to ship with for basic functionality.

**Comment by threepointone** [comment]
React, unlike lodash, is not a collection of utilities, so the analogy isn't accurate. `.hydrate()`, for example, recreates the entire react tree, so indeed requires most of the same machinery.  

Closing this for now, but happy to discuss more if you have concrete suggestions. You're welcome to investigate more; and I'd be interested in your learnings from experimenting too. Thank you!

**Comment by threepointone** [comment]
fyi - There's also a broader discussion to have about ssr/progressive hydration/first load experience, and so on, and that's something the team is actively working on.

**Comment by Eddie-CooRo** [comment]
@threepointone By "progressive hydration" Do you mean the new Fizz renderer? Or it's something different?

**Comment by threepointone** [comment]
That’s a big part of it, yes!

**Comment by username2018** [comment]
Still takes up 126 MB in 2023.
Is there a react dom version without the hydrate?

**Comment by gaearon** [comment]
React cannot possibly take up 126 MB. What are you referring to?

**Comment by ozgeneral** [comment]
it says 126 KB, my experience has been similar. 

also see this stackoverflow thread: https://stackoverflow.com/questions/39413855/webpack-why-react-dom-increase-size-in-about-150kb

size of the library seems to be an issue for many people. 
I suppose the question is, where is this size coming from and are all these 126KB absolutely necessary for all react apps regardless of any circumstances?

I glossed over it briefly. it seems like the bulk is coming from react-dom.development which is ~30K lines, wow

**Comment by iexa** [comment]
Maybe give preact a try? With its react/compat option you might get away with changing nothing (~4kb gzipped minimized compared to 10x more for react+react-dom)

**Comment by neoncube2** [comment]
Current status: It looks like the React team did eventually start exporting `hydrate()` separately, so it can now be tree-shaken :)

(In React 18, `React.hydrate()` was deprecated in favor of just `hydrateRoot()`, and in React 19, `React.hydrate()` was removed)

**Comment by nvmnghia** [comment]
<img width="598" height="399" alt="Image" src="https://github.com/user-attachments/assets/94fcc211-7cff-44e8-a0c4-68cae5fa9d69" />

is mine normal? it's one big chunk, doesn't seem to be treeshakable
