### ISSUE TITLE
[React-test-renderer] imported asset paths ends up being null

### ISSUE THREAD

**Issue by undrafted** [facebook/react#16185]
**Do you want to request a *feature* or report a *bug*?**
bug, or maybe a newb question(?)

**What is the current behavior?**

Asset paths resolve to null in snapshot trees when used this way:

```js
import logo from './logo.svg';
...
<LogoElement>
    <img src={logo} />
</LogoElement>
```

the tree created using ```renderer.create``` is: 

```js
<LogoElement>
    <img src={null} />
</LogoElement>
```

**What is the expected behavior?**
src to be the path of the logo.svg

**Comment by threepointone** [comment]
This is more of a jest issue (or whatever you're using for running tests). For jest, there are some suggested workarounds here https://github.com/facebook/jest/issues/2838#issuecomment-291525128
