### ISSUE TITLE
The error message supposed to be found in e.message only. Please, avoid copying error message to e.stack.

### ISSUE THREAD

**Issue by maximandrews** [facebook/react#16188]
**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
It duplicates error message to the error stack. I run react code pre-processed by webpack/babel in node virtual machine for SSR purposes. Therefore, I need to re-map the error stack to proper files/lines/columns when the error happens. A duplicated error message in error stack is not corresponding to a common error stack format which causes incorrect re-mapping and mess in the error output.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
The following error message was found both in `e.message` and `e.stack`:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
**What is the expected behavior?**
The error message should be found in `e.message` only.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.8.6
webpack@4.36.1
@babel/core@7.5.5
@babel/runtime@7.5.5

**Comment by gaearon** [comment]
I'm not sure why this issue is filed against React. This is how errors work in JS:

<img width="227" alt="Screen Shot 2019-08-15 at 1 46 04 PM" src="https://user-images.githubusercontent.com/810438/63095393-0bac0080-bf63-11e9-8a58-8e512780b41a.png">

Your error mapping mechanism needs to strip it out.

**Comment by maximandrews** [comment]
Sorry @gaearon, my bad.

Thank you for investing your time and even creating a screenshot to explain me native behavior.

**Comment by gaearon** [comment]
No problem, happy to help! I had to double check myself.
