### ISSUE TITLE
link onLoad is not triggered

### ISSUE THREAD

**Issue by melbon** [facebook/react#16182]
The `onLoad` event handler isn't triggered for a `link` element. It works if the element is pure DOM element and `onload` function is a string ` <link rel="stylesheet" href="style.css" onLoad="console.log(this)">`.

MDN docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Stylesheet_load_events
React docs /only image has `onLoad` event/: https://reactjs.org/docs/events.html#image-events

Live demo: https://jsfiddle.net/7me2z3wh/

**Comment by arianon** [comment]
You set a `src` attribute on the `link` element, and you meant to write `href`, once you fix that, it will work.

```diff
 ReactDOM.render(
   React.createElement('link', {
-    src: 'https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css',
+    href: 'https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css',
     rel: 'stylesheet',
     onLoad: () => console.log('React Style is loaded')
   }),
   link
 )
```
