### ISSUE TITLE
"TypeError: _useContext is undefined"

### ISSUE THREAD

**Issue by ccapua** [facebook/react#16195]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
When trying to implement useContext with my react hooks components, I am getting the aforementioned error: "TypeError: _useContext is undefined". It is definitely defined in my code. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
It would be considered defined and grab all of the values I specify from the context file.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Firefox, latest version of React

**Comment by jquense** [comment]
we can't help if you don't post any info helping us reproduce it. Making a wild guess from the error message alone it sounds like you are importing it wrong or have a problem with your build tool
