### ISSUE TITLE
Question: Context API in conjunction with useState

### ISSUE THREAD

**Issue by sergeykaikin** [facebook/react#16190]
I am trying to understand whether it is a good idea to do the following:

```javascript
// NOTE: I deliberately skipped ValuesContext initialisation to make code shorter

const Counter = () => (
  <ValuesContext.Consumer>
    {({ counter, setCounter }) => (
      <span>{counter}</span>
      <button onClick={() => setCounter(counter + 1)}>Increase counter</button>
    )}
  </ValuesContext.Consumer>
);

const Text = () => (
  <ValuesContext.Consumer>
    {({ text, setText }) => (
      <span>{text}</span>
      <input type="text" value={text} onChange={({ target: { value } }) => setText(value)} />
    )}
  </ValuesContext.Consumer>
);

const App = () => {
  const [activePage, setActivePage] = useState('one');
  const [counter, setCounter] = useState(1);
  const [text, setText] = useState('');

  return (
    <ValuesContext.Provider value={{
      activePage,
      setActivePage,
      counter,
      setCounter,
      text,
      setText
    }}>
      <button onClick={() => setActivePage(activePage === 'one' ? 'two' : 'one')}>Toggle pages</button>
      {activePage === 'one' && <Counter />}
      {activePage === 'two' && <Text />}
    </ValuesContext.Provider>
  );
};
```

Technically I am not breaking [hook rules](https://reactjs.org/docs/hooks-rules.html#explanation) but passing setter functions to other components and those setters may be used inside loops, conditions, or even nested functions. 

So far everything seems to work fine but I am wondering whether this is a good idea before I start getting weird issues. Do you see/foresee any issues with this approach?

Thanks in advance for your help/advice.

**Comment by kulaska** [comment]
This is just from my point of view: no, it should not break the code. As rules of hooks specify, you should not be using hooks _themselves_ in loops, conditionals etc. The returned value or setter can be used anywhere you need.

**Comment by sergeykaikin** [comment]
Thanks @kulaska for the swift response. My question is more like a "sanity check" 😅 I just don't want to introduce state management library to make my bundle heavier when React gives the solution out of the box
