### ISSUE TITLE
Bug: Environment variables with '$' are modified on Linux

### ISSUE THREAD

**Issue by thebananeman** [facebook/react#16193]
I report this issue here since I didn't find any occurence of it anywhere else.

**What is the current behavior?**

Right now whenever I want to read an env variable in the process.env object whose value contains a dollar sign '$'. The value is modified once passed to react and replaced by the corresponding env variable.

For example: If I type the following in my terminal : 
`export REACT_APP_EXAMPLE="my\$value"`
If I check again in the terminal I have : 
```
echo $REACT_APP_EXAMPLE 
my$value
```
But once my app is launched, React replace the portion followed by the '$' by the content of the 'value' environment variable (empty by default). So if for example I want to log it, I will have : 
```
console.log(process.env.REACT_APP_EXAMPLE);
-> my
```
And if my 'value' variable is set :
`export value=something`
```
console.log(process.env.REACT_APP_EXAMPLE);
-> mysomething
```

**What is the expected behavior?**

React should give the proper value and not overriding its content because of special characters. Especially since I used double quotes and backslash expression to avoid the confusion when setting the variables.
This seems to be an issue with React when it redefines and filters the process.env object since I don't have this issue with plain JS or when running a node console.
For now I use dotenv to avoid that behaviour but it is still an issue worthy of note.

**Which versions of React, and which browser / OS are affected by this issue?**
React v.16.8.6
OS: Ubuntu 16.04

**Comment by threepointone** [comment]
You should file this issue at https://github.com/facebook/create-react-app/issues
