### ISSUE TITLE
Add getBoundingClientRect to EventTarget type

### ISSUE THREAD

**Issue by droganov** [facebook/react#16201]
Hi.
I've found that I can't use getBoundingClientRect with MouseEvent in typescript.

```
onClick: (event: MouseEvent): void => {
  const { left, top } = event.target.getBoundingClientRect();
  const { left, top } = event.nativeEvent.target.getBoundingClientRect();
},
```

Typescript message I see in VS code is:

`Property 'getBoundingClientRect' does not exist on type 'EventTarget'.ts(2339)`

**Comment by droganov** [comment]
This is what worked for me, but I guess for `MouseEvent` it should work out of the box
`const node = event.target as HTMLElement;`

**Comment by threepointone** [comment]
this looks like an issue for the typescript bindings, the react team doesn't own those.

**Comment by NickCis** [comment]
I came across this old issue, no intention on bumping it up but as google sends people to this link I'll leave the solution to this problem. Apparently `React.MouseEvent` is a generic which parameter is the type of the `currentTarget` property (**note:** the type cast isn't applied to the `target` property but rather to the `currentTarget`).

```tsx
onClick: (event: React.MouseEvent<HTMLElement>): void => {
  const { left, top } = event.currentTarget.getBoundingClientRect();
},
```
