### ISSUE TITLE
when using useReducer's dispatch how to ensure order of execution?

### ISSUE THREAD

**Issue by mgenev** [facebook/react#16213]
When using setState() I have the option of adding a callback once it's certain the state has been updated. When using useReducer's dispatch, what do I do for that? 

I have a use case right now where I need to queue dispatches in order and it is misbehaving and I have no callback, or promise or any other way to ensure the order that I can see...

**Comment by otakustay** [comment]
`dispatch` calls are always executed in order, you should use the `prevState` argument in reducer instead of any other states outside of reducer

**Comment by mgenev** [comment]
The question is whether it's guaranteed that the state is updated before the next dispatch fires.
It seems to be that it is not, because when I do this -- destroy a player  in the DOM, change the position and title in the state, then recreate the player in the DOM, the title is still the same.

```
this.dispatch({
      type: 'PLAYER_VISIBLE'
    })

this.dispatch({
        type: 'PLAYER_POSITION_CHANGE',
        position
      })
  
      this.dispatch({
        type: 'TITLE_CHANGE',
        title
      })
  
      this.dispatch({
        type: 'PLAYER_VISIBLE'
      })
```

As soon as I add a time out, even if it's 0 ms, it starts working and the player plays the new title...

```
    this.dispatch({
      type: 'PLAYER_VISIBLE'
    })
    setTimeout(() => {
      this.dispatch({
        type: 'PLAYER_POSITION_CHANGE',
        position
      })
  
      this.dispatch({
        type: 'TITLE_CHANGE',
        title
      })
  
      this.dispatch({
        type: 'PLAYER_VISIBLE'
      })
    }, 0);

```

**Comment by otakustay** [comment]
The update is not guaranteed, but within the next dispatch, your reducer will receive a a new state even it is not updated to DOM.

In case you require a DOM update to generate the action to dispatch, you need `useEffect`:

```js
useEffect(
  () => {
    dispatch({type: 'TITLE_CHANGE', title});
  },
  [title]
);
```

**Comment by threepointone** [comment]
Could make a codesandbox repro of your problem?

**Comment by gaearon** [comment]
When you have problems like this, the solution isn't to delay dispatches. It's to fix your reducer so that it *wouldn't care* whether actions come in synchronously or not. Your data model shouldn't need to depend on DOM being flushed.

**Comment by ngood97** [comment]
> `dispatch` calls are always executed in order, you should use the `prevState` argument in reducer instead of any other states outside of reducer

is this documented anywhere? Seems like it might be an implementation detail that this is true
