### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by lidaof** [facebook/react#16211]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

TypeError: Assignment to constant variable.

![image](https://user-images.githubusercontent.com/102806/61904769-1be53880-aeed-11e9-81f9-9479e40490b5.png)

System: OSX
npm: 6.10.2
node: v10.13.0
react: 16.8.6

**Comment by artuross** [comment]
What I think you're trying to is something like this:

```
const something = 1;
something = 2;
```

Even though the path implies that the error happens in react, I think the error happens in your code, but it's difficult to tell from a single line. Perhaps you could share a little bit more (error stack)?

**Comment by lidaof** [comment]
Hi @artuross , thank you so much for reply. Sure, here is the screenshot:
![image](https://user-images.githubusercontent.com/102806/61969971-645e2e00-afa1-11e9-919a-ed8c0e71b8dd.png)

I don't think I did that const thing....my code is [here](https://github.com/lidaof/eg-react/blob/alignUI/frontend/src/components/trackVis/interactionTrack/ArcDisplay.tsx)

**Comment by jquense** [comment]
@lidaof the error is coming from your code so there is either a typo/bug in what you've written or a problem compiling it. In either case it's not realted to React, and the React issue tracker is for React bugs. I'd recommend bisecting your code, commenting out bits and pieces until the error goes away and you can narrow down which part specifically is breaking it.

**Comment by lidaof** [comment]
Hi @jquense ok....so the problem only happens on build version, it's not happening in development version.......so the code should be fine....

**Comment by artuross** [comment]
@lidaof I would look at lines 112 and 126 at `ArcDisplay.tsx`.

**Comment by Teal-labs-developer** [comment]
I am facing the same problem today. @lidaof did you find out a solution to fix it?

**Comment by shahchaitanya** [comment]
I am facing a similar issue today. @lidaof did you find out a solution to fix it?

**Comment by lidaof** [comment]
I am not sure if we have same condition, I updated typescript to 3.4 and create-react-app to 2.1 solved this problem. @shahchaitanya

**Comment by shahchaitanya** [comment]
@lidaof are you using uglify js plugin in Production? This problem is occurred due to this plugin. [These](https://github.com/mishoo/UglifyJS2/issues/2842) [links](https://github.com/mishoo/UglifyJS2/issues/2854) are referred to this bug. I solved this issue by adding `inline:false` in uglify js `compress` object.

**Comment by lidaof** [comment]
Thank you for reply @shahchaitanya . I think i did use it, but I don't know where to put this option. I was using react-app-rewire with react-scripts-ts

**Comment by shahchaitanya** [comment]
@lidaof you can configure your web pack in webpack.config.js file. I put this option under webpack.config.js.

**Comment by lidaof** [comment]
thank you @shahchaitanya . I tried that but it's not working for me. Thanks again.

**Comment by prasenpatil2107** [comment]
I think there is a simple catch.....if you define it as const you cant change its value. To resolve it just define it by let and try.  I was going through a similar error solved it by this.

**Comment by jannunen** [comment]
You just saved my day (after 10 hours of fiddling).
