### ISSUE TITLE
why not using tagged template literal instead of jsx ?

### ISSUE THREAD

**Issue by catastrop** [facebook/react#16229]

**Comment by catastrop** [comment]
why closed?

**Comment by catastrop** [comment]
You're violating our freedom

**Comment by threepointone** [comment]
We use this issue tracker for bugs or feature requests. Consider using a community resource to discuss this further.

**Comment by gaearon** [comment]
For future readers: http://facebook.github.io/jsx/#why-not-template-literals

(However, I'm locking the thread because of your spammy behavior)
