### ISSUE TITLE
question: how jsx work ?

### ISSUE THREAD

**Issue by catastrop** [facebook/react#16228]

**Comment by Eddie-CooRo** [comment]
Take a look at [this](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx/) babel plugin.
It's what makes the jsx possible

**Comment by catastrop** [comment]
This sucks

**Comment by gaearon** [comment]
For future readers: http://facebook.github.io/jsx/#why-not-template-literals

(However, I'm locking the thread because of your spammy behavior)
