### ISSUE TITLE
Unclear error message for invalid member-components

### ISSUE THREAD

**Issue by anddero** [facebook/react#16222]
If you try to use a component which does not exist:

```
<Foo />
```

You would get this real nice and clear compilation error:

```
./src/components/pages/ProfilePage.js
  Line 547:  'Foo' is not defined  react/jsx-no-undef

Search for the keywords to learn more about each error.
```

However, if you try to use a member-component (I'm not sure how they are actually called) which does not exist:

```
<Button.Foo />
```

You get this huge mess:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ProfilePage`.
```

Even though it does hint there might be something wrong in the `ProfilePage` render method, we tend to look at the stack-trace first which is completely useless in this case, starting with:

```
 4 | import App from "./App";
   5 | import registerServiceWorker from "./registerServiceWorker";
   6 | 
>  7 | ReactDOM.render(
   8 |     <BrowserRouter>
   9 |         <App />
  10 |     </BrowserRouter>,
```

I ran into this problem, when I tried to use React-Bootstrap's `Alert.Heading` component, but accidentally wrote `Alert.Title`. I went over pretty much all of my changes several times and missed it every time. Took me several hours to find the mistake. Same thing could happen if you simply mistype an element name like `Alert.Headign`.

I suggest generating an error message with more information in this case. For example you could add the line:

```
Button.Foo is not defined
```

somewhere in the error message.

**Comment by otakustay** [comment]
React is not aware its given component type is `Button.Foo`, this is exactly same to react:

```jsx
const Foo = Button.Foo;

<Foo />
```

As a runtime library react is not able to know any thing beyond "I receive a component type `undefined`", so it is impossible to do it by react itself.

Maybe a babel plugin can add some extra check before any jsx tag so that it can report a more clear message, such as transform `<Button.Foo />` to `createElementDebug('Button.Foo', Button.Foo, ...)`, but I think it is too heavy.

**Comment by threepointone** [comment]
> Even though it does hint there might be something wrong in the ProfilePage render method,

This works really well once you know to see it. We also include a component stack in the message. There's not much else React could do beyond that? You could also consider using a type system like flow or typescript to detect these errors.
