### ISSUE TITLE
TypeError: _ useContext is undefined. Very confusing.

### ISSUE THREAD

**Issue by ccapua** [facebook/react#16224]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
am getting the error "TypeError: _ useContext is undefined". I have it imported and everything set up properly (I think?). please see below.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I am trying to have an app context for the entire app. Here is the code where useContext is called:

```
import React, { useState, useContext } from 'react';
import { AppContext } from '../contexts/AppContext';

const Burger = (props) => {
  const [clicked, setClicked] = useState(false);

  const { toggleClicked } = useContext(AppContext);

  return ( 
    <div id="burger" data-state="burger" onClick={toggleClicked()}>
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
    </div>
  );
}
 
export default Burger;
```

and here is the context file: 
```
import React, { useState, createContext } from 'react';

export const AppContext = createContext();

const AppContextProvider = (props) => {
  const [burgerClicked, setBurgerClicked] = useState(false);

  const toggleClicked = () => {
    setBurgerClicked(true);
    let overlay = document.getElementsByClassName('overlay');
    if (overlay.dataset.state = 'on') {
      overlay.dataset.state = 'off'
    } else {
      overlay.dataset.state = 'on';
    }
  }

  return (
    <AppContext.Provider value={{toggleClicked, burgerClicked}}>
      {props.children}
    </AppContext.Provider>
  )
}

export default AppContextProvider;
```

**What is the expected behavior?**
useContext is defined and allows me to access context variables.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is the latest version of React and Firefox.

**Comment by gaearon** [comment]
You're probably using an old version of React. This API is new in 16.8+.

**Comment by ccapua** [comment]
I have the latest version installed

**Comment by ccapua** [comment]
I updated both the global and local versions and am still getting this error.

**Comment by ccapua** [comment]
I have 16.8.6 installed both globally and in the project directory and am still getting this error. Any help is very much appreciated.

**Comment by gaearon** [comment]
Since the API itself exists (you can check the export), something else is wrong with your setup. We can't guess what it is without a reproducing project.
