### ISSUE TITLE
[Feature Request] Global Context

### ISSUE THREAD

**Issue by alshdavid** [facebook/react#16233]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Context is explicitly defined and consumed by providers and consumers.

**What is the expected behavior?**
General purpose context which is provided by default at the root level. It could function as a container for config or application dependencies.

The syntax example below hasn't be heavily considered but generally illustrates the feature request.

```js
const globalContext = {
    value: 'something',
    fetchSomething: () => fetch('https://some.thing')
}

ReactDOM.render(<App />, element, globalContext)
```
Then consume it with something like

```js
const Toolbar = () => {
    const globalContext = useGlobalContext()
}
```

**Comment by threepointone** [comment]
You could just use a global variable for this.

**Comment by alshdavid** [comment]
The challenge is that anyone who wants to consume something on a created context from a library must import that specific context, which is a contract that is highly coupled to a specific implementation.

I think it makes sense that React features an object scoped to the react instance which is available to all the embedded components.
