### ISSUE TITLE
 Error on unit test : Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by nimahkh** [facebook/react#16239]
@gaearon 
i have a component that has a useState hooks as below  :

`component is so big , because of that , i just write some of the problem .`

```
function Login(props){
/*...*.
    const [, dispatch] = useLoginStateValue();
    
return(
/*...*/
)

}

```

and i have a test for this component

```
jest.mock("../../Services/login")

it("mock login request testing", (done) => {
    act(() => {
        const wrapper = mount(
            <MuiThemeProvider theme={dark}>
                <Login theme={{isResponsive: true}}/>
            </MuiThemeProvider>);

        wrapper.setState({email: "@@22WWee"})
        wrapper.setState({password: "test@test.com"})
        wrapper.find('button#authenticate').simulate('click');

        setTimeout(() => {
            wrapper.update();
            wrapper.setState({alert: "Bad credentials"})
            expect(wrapper.instance().state.alert).toEqual("Bad credentials")
            done()
        })
    })
})
```

when i run test , it shows error :
`
    Error: Uncaught [TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined]
`

after removing `    const [, dispatch] = useLoginStateValue();` everything is ok , how can i use dispatch , and LoginStateValue without error in test ?

**Comment by threepointone** [comment]
My guess is that `useLoginStateValue` doesn't return an array. Would recommend using a community resource for questions like this https://reactjs.org/community/support.html

**Comment by melaneon** [comment]
You saved me!!

> My guess is that `useLoginStateValue` doesn't return an array. Would recommend using a community resource for questions like this https://reactjs.org/community/support.html

**Comment by madhur89** [comment]
I think your custom hook is not returning something make sure to return the required function and states.

**Comment by mayur4895** [comment]
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))  i have this error and i used shadcn ui library combobox  code is
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Check, ChevronsUpDown } from "lucide-react";
import { useForm } from "react-hook-form";
import { z } from "zod";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from "@/components/ui/command";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { toast } from "@/components/ui/use-toast";

const languages = [
  { label: "English", value: "en" },
  { label: "French", value: "fr" },
  { label: "German", value: "de" },
  { label: "Spanish", value: "es" },
  { label: "Portuguese", value: "pt" },
  { label: "Russian", value: "ru" },
  { label: "Japanese", value: "ja" },
  { label: "Korean", value: "ko" },
  { label: "Chinese", value: "zh" },
] as const;

const FormSchema = z.object({
  language: z.string({
    required_error: "Please select a language.",
  }),
});

export function ComboboxForm() {
  const form = useForm<z.infer<typeof FormSchema>>({
    resolver: zodResolver(FormSchema),
    defaultValues: {
      language: "", // Ensure there's a default value
    },
  });

  function onSubmit(data: z.infer<typeof FormSchema>) {
    toast({
      title: "You submitted the following values:",
      description: (
        <pre className="mt-2 w-[340px] rounded-md bg-slate-950 p-4">
          <code className="text-white">{JSON.stringify(data, null, 2)}</code>
        </pre>
      ),
    });
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <FormField
          control={form.control}
          name="language"
          render={({ field }) => (
            <FormItem className="flex flex-col">
              <FormLabel>Language</FormLabel>
              <Popover>
                <PopoverTrigger asChild>
                  <FormControl>
                    <Button
                      variant="outline"
                      role="combobox"
                      className={cn(
                        "w-[200px] justify-between",
                        !field.value && "text-muted-foreground"
                      )}
                    >
                      {field.value
                        ? languages.find(
                            (language) => language.value === field.value
                          )?.label
                        : "Select language"}
                      <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </FormControl>
                </PopoverTrigger>
                <PopoverContent className="w-[200px] p-0">
                  <Command>
                    <CommandInput placeholder="Search language..." />
                    <CommandEmpty>No language found.</CommandEmpty>
                    <CommandGroup>
                      {languages.map((language) => (
                        <CommandItem
                          value={language.label}
                          key={language.value}
                          onSelect={() => {
                            form.setValue("language", language.value);
                          }}
                        >
                          <Check
                            className={cn(
                              "mr-2 h-4 w-4",
                              language.value === field.value
                                ? "opacity-100"
                                : "opacity-0"
                            )}
                          />
                          {language.label}
                        </CommandItem>
                      ))}
                    </CommandGroup>
                  </Command>
                </PopoverContent>
              </Popover>
              <FormDescription>
                This is the language that will be used in the dashboard.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit">Submit</Button>
      </form>
    </Form>
  );
}
