### ISSUE TITLE
Broken link to Lifecycle diagram

### ISSUE THREAD

**Issue by tyty1602** [facebook/react#16244]
Link doesn't work http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/

**Comment by babangsund** [comment]
Where'd you find this link?

**Comment by tyty1602** [comment]
I found the link from the React Documentation from the Lifecycles section. Here is the link: https://reactjs.org/docs/react-component.html#the-component-lifecycle

Each component has several “lifecycle methods” that you can override to run code at particular times in the process. You can use this **lifecycle diagram** as a cheat sheet. In the list below, commonly used lifecycle methods are marked as bold. The rest of them exist for relatively rare use cases.

**Comment by gaearon** [comment]
Hmm, I can follow the link. What are you seeing?

**Comment by nortonwong** [comment]
It seems to be missing a Promise polyfill for IE11.

**Comment by tyty1602** [comment]
Hi, it is fixed on Chrome now! I can see the diagram....hooray.

**Comment by babangsund** [comment]
Huh. Update - I can see it now as well. I couldn't before. 👍

**Comment by tyty1602** [comment]
Yes, closing issue since it's fixed!
