### ISSUE TITLE
UseEffect infinity reload if value props is undefined

### ISSUE THREAD

**Issue by viniarruda** [facebook/react#16255]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If the props received undefined value, useEffect understand the value props change, and reload infinity times.
Obviously the data must be handled, but when it gets undefined the infinite reload should not happen.

In the codesandbox example, I force the props checkedItems with undefined, but if I don't pass any props, the default value is undefined, the useEffect understand the value change, and start que infinity loop.

**Example below:**
https://codesandbox.io/s/aged-river-ypn7y

**What is the expected behavior?**
Load only one time, because the value undefined not change.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React Typescript
My react version: `16.8.1`
My react dom version: `16.8.1`
My chrome version: `75.0.3770.142`
"@types/react": "16.7.22",
"@types/react-dom": "16.0.11",

Thanks.

**Comment by threepointone** [comment]
Could you please make a codesandbox repro?

**Comment by Admsol** [comment]
Probably comes from your `paymentProvider.getPayments();`

**Comment by viniarruda** [comment]
Follow the code: https://codesandbox.io/s/aged-river-ypn7y

**Comment by Admsol** [comment]
It looks like its coming from your code (it comes from a state changed and state watch via useEffect) , ive also changed the default loading state, please try:

`index.tsx`
```
const [isLoading, setIsLoading] = React.useState(true);
  const fetchData = async () => {
    const response = await axios.get(
      "https://jsonplaceholder.typicode.com/todos/1"
    );
    setIsLoading(false);
  };
```

`children.tsx` (remove checkedItems from useEffect dependancy)
```
useEffect(() => {
    setChecked(checkedItems);
    console.log("checkeditems", checkedItems);
    console.log("checked", checked);
  }, []);
```

**Comment by viniarruda** [comment]
> It looks like its coming from your code (it comes from a state changed and state watch via useEffect) , ive also changed the default loading state, please try:
> 
> `index.tsx`
> 
> ```
> const [isLoading, setIsLoading] = React.useState(true);
>   const fetchData = async () => {
>     const response = await axios.get(
>       "https://jsonplaceholder.typicode.com/todos/1"
>     );
>     setIsLoading(false);
>   };
> ```
> 
> `children.tsx` (remove checkedItems from useEffect dependancy)
> 
> ```
> useEffect(() => {
>     setChecked(checkedItems);
>     console.log("checkeditems", checkedItems);
>     console.log("checked", checked);
>   }, []);
> ```

The example in codesanbox is simple, because this my props don't receive new values and not render again. Remove this props from useEffect param does not help in my actual application.

**Comment by universse** [comment]
The problem is the Children component default value for prop checkedItems, which is an empty array. It's always a different array whenever Children rerenders, triggering useEffect hook and causing infinite loop.
The solution is to hoist default checkedItems value out of the components so it's always the same empty array. Take a look at https://codesandbox.io/s/romantic-dream-npk8y

**Comment by viniarruda** [comment]
Oh, I understand now. Define empty array in the function, it rerender and start the infinity loop. Raising the array out solves the problem. Thank you the explanation!
