### ISSUE TITLE
How to save my components in browers caches (applications/frames)

### ISSUE THREAD

**Issue by WajdiBf** [facebook/react#16251]
i want to do the same thing as Icloud.com 
![Capture du 2019-07-30 11-06-25](https://user-images.githubusercontent.com/48321338/62124857-39d2e480-b2c3-11e9-9764-c675c5b31e9f.png)
![Capture du 2019-07-30 11-06-57](https://user-images.githubusercontent.com/48321338/62124858-3a6b7b00-b2c3-11e9-806f-be246e426a13.png)

**Comment by WajdiBf** [comment]
i want to do the same thing as Icloud.com 
![Capture du 2019-07-30 11-06-25](https://user-images.githubusercontent.com/48321338/62124857-39d2e480-b2c3-11e9-9764-c675c5b31e9f.png)
![Capture du 2019-07-30 11-06-57](https://user-images.githubusercontent.com/48321338/62124858-3a6b7b00-b2c3-11e9-806f-be246e426a13.png)

**Comment by vNNi** [comment]
You need to create literally frames, i don't know if necessary, but can use frameset tags to wrappe your frames. It's like a other application/page inside one app. Maybe you don't really need it using react, but you can do that, see this:
https://www.w3schools.com/tags/tag_frameset.asp

**Comment by WajdiBf** [comment]
I just want to create a progressive web application(service worker)
but I dont  want to cache the entire application
every component gonna be cahed in brower 
same example as Icloud.com
some advice please

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
