### ISSUE TITLE
Updating data within a cloned jsx

### ISSUE THREAD

**Issue by mg901** [facebook/react#16252]
We are trying to implement customization of the application in runtime for different organizations. Here is a [diagram](https://www.lucidchart.com/documents/edit/b92cf5e4-26ca-42b5-a8e1-e22c1b00d7fe/0?shared=true&)  (login with Google to see )of how this should work.

Portals didn’t work for us because they implement only half of the script - they allow us to render a loaded element into an element already existing on the page
but they do not help in any way when the container for the element appears after loading the plugin.
We [forked](https://github.com/mg901/react-slot-fill) the [React-slot-fill](https://www.npmjs.com/package/react-slot-fill), updated the react to the current version, and added support for new slots.

Here is a description of its API.
Slot is a named point for mounting components, the name of the slot is unique throughout the project.
Mounting can be done from anywhere in the application.

Some Slots are going through the whole app and some of them appears only at certain screens, for example user configured Dashboard. So we need a way to link Slot and Fills in spite of which of them was rendered first.

At the moment slot-fill meets all our requirements, but we don't understand how to update the data inside the components in each slot in the slot, and if that's not possible, what alternatives can you offer?

I'm also attaching an error scenario [video](https://youtu.be/_Y0Iz1qqnFg).
[And a link to an application where you can play this bug](https://mv-test.ips.su/modelviewer/entity). 

login: admin
password: admin

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
