### ISSUE TITLE
[Regression] onChange behaviour on radio buttons

### ISSUE THREAD

**Issue by theKashey** [facebook/react#16258]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Having an uncontrolled, but _observed_ Radio Group, `onChange` would not be called on the previously selected Radio, only on the newly selected one.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/elastic-tu-yvytn

**What is the expected behavior?**

onChange is called on both `inputs`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.6

This issue was fixed in 15.6.2 - https://github.com/facebook/react/issues/12172

**Workaround**
```js
const radioStates = new Map();
const nop = () => null;
export const Radio = ({inputGroupName, value}) => {
  const [checked, setChecked] = React.useState(false);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    // Radio change events are broken
    // see https://github.com/facebook/react/issues/9988
    // emulating Radio Group controller
    const group = e.target.name;

    // disable old radio    
    const oldHandler = radioStates.get(group) || nop;
    oldHandler(false); 

    // enable new radio
    radioStates.set(group, setChecked);    
    setChecked(e.target.checked);
  };

  return (
    <label>
      <input
        type="radio"
        name={inputGroupName}
        value={value}
        onChange={handleInputChange}
      />
    </label>
  );
};
```

**Comment by gaearon** [comment]
What's the first version that regressed?

**Comment by theKashey** [comment]
You know, I've tried many versions till 15.0.0, and __it was always broken__. Even more - `15.6.2` where is was "expected" to be fixed is [working worse than others](https://codesandbox.io/s/restless-silence-zgvsi) - `onChange` for every radio would be fired only once.

**Comment by andrelmchaves** [comment]
@theKashey, Could you confirm this is still an issue?

**Comment by eps1lon** [comment]
> onChange is called on both inputs

Note that this matches how radio buttons work with just using the DOM: https://codesandbox.io/s/quiet-rain-j7rvq1?file=/public/index.html

This doesn't seem like a regression but intended behavior. Unless we explicitly want to have different behavior here.
