### ISSUE TITLE
ErrorBoundary can not catch children node error

### ISSUE THREAD

**Issue by Sylvenas** [facebook/react#16262]
**Feature**

**What is the current behavior?**

ErrorBoundary component can only catch the error from the **children component**.

Is there some way can catch the error from the **children node**?

example App component:
``` js
function App() {
  const user = {}
  return (
    <main>
      <h2>main</h2>
      <ErrorBoundary>
        <User user={user} />
      </ErrorBoundary>
      {/* can not catch*/}
      <ErrorBoundary>
        <div>{user.info.name}</div>
      </ErrorBoundary>
      {/* also can not catch*/}
      <ErrorBoundary>
        {() => (<div>{user.info.name}</div>)}
      </ErrorBoundary>
    </main>
  );
}

const User = (props) => {
  return <div>{props.user.info.name}</div>
}
```

ErrorBoundary component:
``` js
class ErrorBoundary extends Component {
    constructor(props) {
        super(props);
        this.state = { hasError: false };
    }

    static getDerivedStateFromError(error) {
        return { hasError: true };
    }

    componentDidCatch(error, info) {
        console.log(error, info);
    }

    render() {
        if (this.state.hasError) {
            return <h1>Something went wrong.</h1>;
        }

        if (typeof this.props.children === 'function') {
            return this.props.children()
        }

        return this.props.children;
    }
}
```
I don't think there is much difference between use  `User` component and  `<div>{user.info.name}</div>` . Also wrap *every* component in error boundary is  a bad idea. But sometimes, I can't take every small module to a separate component. So I expect the ErrorBoundary can catch the error from the children node。

Any suggestions? thanks a lot.

**Comment by meowtec** [comment]
This is a misunderstanding because the error was thrown from the `render` phase of `App`, not from its children.

**Comment by meowtec** [comment]
For the first case:
```js
<ErrorBoundary>
  <div>{user.info.name}</div>
</ErrorBoundary>
```
It is impossible because the code is equal to:
```js
React.createElement(
  ErrorBoundary, 
  null, 
  React.createElement("div", null, 
    user.info.name,
  ),
);
```
`user.info.name` is executed too early, before the element be created.

For the second case, the error was thrown from the `render` phase  of `ErrorBoundary`, but not from its children, too. It can not be catch just by design.

You can try this:

```js

const Thunk = render => render()

render() {
  return (
    <ErrorBoundary>
      <Thunk>
        {() => (<div>{user.info.name}</div>)}
      </Thunk>
    </ErrorBoundary>
  )
}
```

It is ugly... but work as expected.

**Comment by Sylvenas** [comment]
@meowtec .Thanks for your suggestions.  The target of both `Thunk ` component and `<this.props.children />` is to create a new component, which will be wrapped by `ErrorBoundary` component.  The goal I am looking for is `ErrorBoundary` can catch the error from the children node,not only from the children component.

**Comment by meowtec** [comment]
> @meowtec .Thanks for your suggestions. The target of both `Thunk ` component and `<this.props.children />` is to create a new component, which will be wrapped by `ErrorBoundary` component. The goal I am looking for is `ErrorBoundary` can catch the error from the children node,not only from the children component.

It is impossible. Because no error can be thrown from _the children node_, they all are thrown from the `render` function (or the `FunctionComponent` itself).

Think about it this way:
Now suppose you are the developer or React, give you a component function like this:

```js
function TestCase() {
  return React.createElement(
    ErrorBoundary, 
    null, 
    React.createElement("div", null, 
      here.throw.error,
    ),
  );
}
```
Now you call the `TestCase()` function, you will get an error.
```js
// you runtime
TestCase() // throw error
```

So how do you know where the error was thrown exactly? How do you know that the _error node_ was wrapped by `ErrorBoundary`?

**Comment by gaearon** [comment]
Yeah, this can't work.
