### ISSUE TITLE
Are we allowed to use set** in hooks dependencies array?

### ISSUE THREAD

**Issue by Gumichocopengin8** [facebook/react#16276]
The hooks document says, we can put variable of hooks dependencies array, such as this...

```JS
const [some, setSome] = useState(0)

const val = useMemo(() => {
 return something
}, [some])
```

However, are we allowed to use set** in hooks dependencies array?
For example, 

```JS
const [some, setSome] = useState(0)

const val = useMemo(() => {
 return something
}, [setSome]) // <- Here
```

I wonder because the second example worked without any errors?
Is it a proper way to use dependencies array?

Thank you.

**Comment by universse** [comment]
Technically we are allowed do it. Only that it's unnecessary since its identity won't change between renders.
