### ISSUE TITLE
[eslint-plugin-react-hook] [feature request]: Error out then class Component is passed to React.memo 

### ISSUE THREAD

**Issue by JustFly1984** [facebook/react#16270]
I have seen some weird misuse of React.memo in codebase. I have fixed it, but for general public this could be useful

**Comment by threepointone** [comment]
React.memo works fine with class components. I'm unsure what issues you saw, it would be great if you code make a codesandbox repro if you'd like to discuss it. closing this, but feel free to share a repro.
