### ISSUE TITLE
IE11 - react.lazy loaded component fails to apply some css styles

### ISSUE THREAD

**Issue by ThekhoN** [facebook/react#16275]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
This is observed in IE11.
Have two components `<Home />` and `<Contact />`.
They have their own css. i.e `<Home />` has it's own "style.css" and `<Contact />` has it's own "style.css".

Using React.lazy we have implemented route-based code-splitting.

Initially, page loads with "/home"  `<Home />`
User accesses  "/contact",
`<Contact />` has a `<button />` that will have class `--is-disabled` if some external props `isDisabled` is true.
we have this style defined in the css of `<Contact/>`,
```
button.--is-disabled {
    background-color: grey;
}
```
Observed that although `<button />` has the class `--is-disabled`, it is NOT greyed out. 

This works as expected in all other browsers - Edge, Chrome, Safari, Firefox

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Unable to provide an example at this time.

**What is the expected behavior?**
Since `<button/>` has the class `--is-disabled`, it should have background-color === grey, as defined in the css.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React.16.8.6
OS: Windows 10
Browser: Internet Explorer 11 

This was working as expected previously
when we were using React 16.1.1 and did not implement route-based code-splitting.

**Comment by threepointone** [comment]
IE 11 does not support css variables https://caniuse.com/#feat=css-variables

closing this since it isn't a react issue.

**Comment by threepointone** [comment]
I'm surprised you'd say it worked in older versions of react. I'm unable to commet further without a repro, either on codesandbox or a regular git repo.

**Comment by ThekhoN** [comment]
> IE 11 does not support css variables https://caniuse.com/#feat=css-variables
> 
> closing this since it isn't a react issue.

It is NOT related to css-variables.

**Comment by threepointone** [comment]
I will be glad to help you debug if you can make a codesandbox repro or a git Tepic with the same issue.

**Comment by threepointone** [comment]
Oh I see it’s not a css var, it’s only named that way. My guess is it’s an issue with the order in which stylesheets are loaded. Again, happy to help you more if you can make a repro.

**Comment by ThekhoN** [comment]
Found that class "--is-disabled" is not supported in IE11. 
If I change the class to "is-disabled", it works as expected.
Sorry for the inconvenience.

Thanks.
