### ISSUE TITLE
False positive on style prop in development mode when hydrating

### ISSUE THREAD

**Issue by damian** [facebook/react#16273]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
Safari is showing an a mismatch error in development console when server side rendering and hydrating on the client for a style prop.

![Screen Shot 2019-08-01 at 11 25 16](https://user-images.githubusercontent.com/34645/62286269-484e0700-b44f-11e9-939f-e28de23ec0b3.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/async-morning-zmwqu?fontsize=14

**What is the expected behavior?**
I wouldn't expect a mismatch error to occur in the console despite the style prop being equivalent to one another, just in a different order.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.1
ReactDOM 16.8.1

**Comment by threepointone** [comment]
We wouldn't consider this a bug, since it actually is a mismatch. It would be strange if you had code that generated styles differently on the server vs the client (since the component that renders is the same etc) Could you explain to me how you managed to trigger this?

**Comment by nmain** [comment]
Remember that style attribute order is relevant to the browser, and React uses the iteration order of the provided style object to choose the style attribute order, so this is a real positive, and in slightly different circumstances it even produces different rendering:

https://jsfiddle.net/4emu80hj/

It shouldn't be up to React to figure out whether one particular case of style prop reordering causes a presentation change; that's far too complicated.

**Comment by threepointone** [comment]
It is easy to demonstrate this issue by rendering different component trees, but in practice people use the same trees in both environments. Which is why I asked; how did you manage to trigger this scenario?
