### ISSUE TITLE
Should componentDidMount optionally return a promise?

### ISSUE THREAD

**Issue by patsplat** [facebook/react#16280]
**Do you want to request a feature or report a bug?**

Feature Request

**What is the current behavior?**

Currently, `componentDidMount` returns nothing.  It is the recommended lifecycle hook for performing async operations.  It is necessary to create wrapper functions returning a promise to test such operations (#14687).

**What is the expected behavior?**

Unlike the suggestion in #1739 etc do not recommending changing any rendering semantics.  Simply allow a promise to be returned so that testing does not require boilerplate.

**Comment by kambleaa007** [comment]
Do anybody knows steps to solve this feature, im ready to work on it

**Comment by patsplat** [comment]
Have been discussing and exploring this feature in my applications.

Am leaning towards making this more a documentation change, ie updating the website to illustrate patterns for retaining and testing a ref to a Promise.

If React doesn't use the promise, can see a pragmatic argument against changing the signature of the method.
