### ISSUE TITLE
[react-hooks/exhaustive-deps] false positiy using `useState` and `useCallback`

### ISSUE THREAD

**Issue by akomm** [facebook/react#16281]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
No errors raised in following demos.

Demo JS: https://codesandbox.io/s/charming-mayer-l3nc3
Demo TS: https://codesandbox.io/s/friendly-merkle-xinzm

**What is the expected behavior?**
Error `setMenuAnchor` missing in `deps`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Eslint is browser independend
Versions: see codesandbox demos

**additional**

Tried reproduce the trigger for the bug. When I replace the `usetState` with literal `[null, function() {}]`, the plugin **correctly** detects missing `setMenuAnchor` in `deps`.

**Comment by universse** [comment]
setMenuAnchor and setState in general always has the same value. Thus, it's unnecessary to include in deps.

**Comment by akomm** [comment]
That actually makes sense. The set function does not have to change once returned. But how does the plugin know? Is it specially checking for `useState`, because it is common, to exclude the second tupple value being required? If that is intended and not just a bug with coincidence of being right in this case, I close.

**Comment by universse** [comment]
Yeah, that is intended. And this is also the case for dispatch from useReducer also.

**Comment by akomm** [comment]
thx
