### ISSUE TITLE
[Feature Request] Alternative to service-locator pattern in React

### ISSUE THREAD

**Issue by alshdavid** [facebook/react#16299]
_**I'm sorry about the long post**_

### The problem:

React currently supplies no way to access dependencies without the use of some form of service locator - other than prop drilling.

This results in strong coupling of components to their surrounding implementations, decreasing testability, increasing boilerplate and discouraging developers from creating abstractions. Basically it fundamentally prevents IoC at the library level.

A common solution to dependency injection is manually wrapping all used components with provider functions. An example of this is using functions like `withTheme()` or `connect()`.

```jsx
import { withItems } from '../items'

export const Hello = withItems({ items = [] }) => {
  return <div>
    { items.map(item => <div>{item}</div>) }
  </div>
})
```

Wrapping components like this creates silos of troublesome testability and due to it’s unergonomic nature, discourages decoupling components from the surrounding application implementation. 

In order to create decoupled component packages, the author must create components which receive all dependencies via props. In order to supply these dependencies, a consumer must import the library and re-wrap/re-export every component, injecting their dependencies from a service locator. 

```javascript
import { Button } from 'generic-ui'
import { withTheme } from '../somewhere' // service locator

export const ThemedButton = withTheme(Button)
```

A consumer must also exclude the wrapped “aware” components from unit tests as it’s impractical to test them in a sensible way.

Another downside is that this pattern tends to fail at runtime, rather than being caught by your transpiler (Babel, TypeScript, CoffeeScript) 

https://en.wikipedia.org/wiki/Service_locator_pattern

An example of a basic service locator in JS is here
https://stackblitz.com/edit/js-6qzkak

An example of a service locator with React is here
https://stackblitz.com/edit/react-tdt624

### What about context?

Context provides a much better solution, though it still relies on the same service-locator pattern. This doesn’t make it bad, but it still requires high levels of coupling between components and their context implementation.

Boiled down, what context simply provides is a vehicle for dependencies to tunnel from their creator to their consumer under the floorboards of the library. It’s essentially an alternative to drilling props from the top level to the embedded components.

Note: You _can_ expose functions and state through context and re-render trees when that state changes, but that doesn’t change it’s underlying intention.

It’s a great solution to the challenge of supplying embedded components with their dependencies, but what advantages does it provide over the previous method?

The old method involves wrapping and re-exporting all components with a `withTheme` function. The `withTheme` function would get that theme from a service-locator - again, requiring wrapping the component with a concrete location for retrieval of the dependency.

Receiving the theme from a context `const theme = useContext(ThemeContext)` also relies on the context being supplied by a concrete location.

In essence, context hides a problem that already existed inside a more ergonomic package.

If you image a simple, generic concept like a store using the Flux architecture; utilities like Redux, MobX. These third party libraries *must* have “React” as a peerDependency. The only alternative is supplying a "react-connected" variant of their library.

For this reason we have the two packages, ‘redux’ and ‘react-redux’. While the latter does provide some convenience utilities, it's use is not optional. It _*must*_ exist along-side the original implementation.

So here is a demonstration of how React enforces coupling by not providing an effective means to handle inversion of control. Below I have a factory function which creates a flux store:

```javascript
export const createPostStore = () => {
  const posts = createStateEmitter([])

  const getValue = () => posts.getValue()

  const add = (post) => {
    posts.setState([
      { title: post, id: randomString() },
      ...getValue()
    ])
  }

  return {
    posts,
    getValue,
    add
  }
}
```

`createStateEmitter` is a just something that provides pub/sub with state. It follows the [observer pattern](https://en.wikipedia.org/wiki/Observer_pattern).

It is consumed like you would consume Redux

```javascript
const store = createPostStore()
store.subscribe(posts => console.log(posts))
store.add('New Post!')
```
This unit has no external dependencies and can be consumed within React to hold state and trigger re-renders. It is easily tested and can be put in npm without a hard dependency on React.

example:
https://stackblitz.com/edit/react-gnj8ba

This example shows "prop drilling" to get the store into the component. This is ideal from an IoC standpoint, but impractical as with many layers of embedded components, you'll pass dependencies down a long tree and it's difficult to maintain.

Of course, I can simply export a context from my package, but I want to avoid a hard dependency on React as it's not really a concern of the library.

Another solution to this problem is to have a shared, global context, where there is a contract that components will consume it and extract their required dependencies from there.

https://stackblitz.com/edit/react-fz6ue8

The challenge here is that I can't expect Bootstrap, Material, or anyone on the internet to `npm install global-context` and have it be the de facto "shared context" which allows for IoC/agnosticism in component implementations.

The last solution is to make two packages, the package itself and a second package that has a hard dependency on React and exposes a context (Just like Redux and React Redux).

### Ok, so what's the solution?

Hard to say. React applications often have many layers of components so any solution must involve supplying embedded components their dependencies in a way that scopes their "providing" to the current instance of React.

Something like a PropProvider, which supplies props to all embedded components might be a solution. It's opt-in making it minimally invasive. It changes nothing for the existing public React API and simply adds another, more flexible, option to a problem you'd normally `useTheme()` to solve.

```jsx
<PropProvider values={{ everyone: 'gets this' }}>
    <MyComponent />
</PropProvider>
```

The problem with this is naming clashes. If you're a library vendor, you'll need to be creative to avoid clashes. The custom element specification stipulates that you must hyphenate your element names to avoid, or reduce the instances of clashes. Maybe that's a solution?

Another options is using getter functions, where key names are nearly impossible to clash and a function knows where to look.

```javascript
const MyComponent = (props) => {
    const theme = useTheme(props)
}
```

Maybe an official static context for the react instance?

```jsx
ReactDOM.render(
    <App/>,
    element,
    { everyone: 'gets this' }
)
```

I don't know the answer, but using global instances, wrapping components, service locators makes things more complicated than they need to be.

**Comment by dmytro-lymarenko** [comment]
The same as this https://github.com/facebook/react/issues/16234, right?

**Comment by alshdavid** [comment]
It relates but isn't the same. While a PropProvider does solve the issue of tightly coupled dependencies, it may not be the solution. 

This post is basically intended to provide proof of why an alternative method of dependency injection (which provides better IoC) into embedded React components is necessary. It also addresses how the current solutions don't solve the issue and why.

**Comment by miraage** [comment]
@alshdavid `ReactDOM.render()` function already has 3 arguments

**Comment by alshdavid** [comment]
@miraage

> ContextAPI is quite sufficient to implement a service locator.

Correct. That's the only way it can be effectively used. 

Sorry if the post was too long and the detail was lost but I'm asking for the opposite.

I'm trying to highlight the limitations of context and requesting an alternative means of dependency injection as context does not allow for dependency inversion and by extension facilitate for inversion of control.

**Comment by alshdavid** [comment]
After some thinking, I do see that the existing solution of context makes sense and solves the issue of dependency inversion.

While what I am looking for is a more general/shared dependency propagation mechanism, the existing solution does not limit a React component's capacity to consume contracts rather than concrete implementations.

I was looking at it from the wrong angle. In the case of a React library, the dependency client would be dependant on React regardless of anything else, so it should supply a context. The context would share contracts to the component library, relying on something up the chain injecting those dependencies into the component's provider.

While this still relies on a service locator, that is fine. Practically, the components don't know about the dependency's implementation and the dependency doesn't know that it will be used in React so there is no problem.

https://stackblitz.com/edit/react-kuahqu?file=index.js

So yeah. Thanks for reading, happy to close this issue.
