### ISSUE TITLE
Add deps/selector/keys argument to useContext

### ISSUE THREAD

**Issue by syabro** [facebook/react#16292]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
useContext triggers update if the whole passed store changed

**What is the expected behavior?**
add keys argument to trigger update only if specified keys in passed store changed

It would be useful to improve application speed.

F.e.

```javascript
function MyComponent() {
  // example context value
  // I want to ignore age changes (who does't hehe)
  // {
  //   name: 'Max',
  //   age: 35
  // }
  // dep's-like style
  const {name} = useContext(MyContext, 'name')
  // or
  // comparator style 
  const {name} = useContext(MyContext, (current, old) => current.name !== old.name)
}
```

**Comment by vkurchatkin** [comment]
Duplicate of https://github.com/facebook/react/issues/14110

**Comment by syabro** [comment]
@vkurchatkin ty
