### ISSUE TITLE
"production" !== "development" : Dead-code in generated library

### ISSUE THREAD

**Issue by gre** [facebook/react#1629]
I was browsing the code of http://fb.me/react-0.10.0.js

and saw a lot of code like: `"production" !== "development"` which is basically dead code.

This is not a major issue but it could help to optimise the size of the output standalone library and remove out the definitely dead code.

I have no knowledge of how you manage your source code but it sounds like you should do `#if` instead of `#define` preprocess approach?

**Comment by e1016** [comment]
Could I ask why `"production" !== "development"`? I saw this snippet in many sources,  but I don't make sense for me, I would use `process.env.NODE_ENV !== 'production'`

**Comment by gre** [comment]
@e1016 I think React internal use `__DEV__` which instead of process.env.NODE_ENV get statically replaced by `"production"` or `"development"` , therefore the uglify step can completely remove portion of code which helps making a lighter prod bundle
