### ISSUE TITLE
useReducer dispatch calls reduce twice 

### ISSUE THREAD

**Issue by babloo80** [facebook/react#16295]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
when a `dispatch()` of OOTB `useReducer` is called, some instances calls the `reduce()` twice.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
As the behavior is intermittent, I shall try to figure out a way to write a reproducer. But, based on call stacks here is what what I can narrow it down. 
Assume,

```
const [state, dispatch] = useReducer(reduce, {})
...
dispatch({something_useful...}) //this call happens twice in the execution stack.
```

Seldom calls to `dispatch()` executes the `reduce()` twice and both the times (it does preserve the previous state. Meaning, it merely calls 
T1: (s', a') => s''
T2: (s', a') => s''
Notice, the state starts with s' only and NOT s''. Hence, the resultant state s'' is still safe.

I do have some call stack that shows the difference from `react-dom`.

First stack-trace when `dispatch()` is called.
```
https://github.com/facebook/react/blob/42794557ca44a8c05c71aab698d44d1294236538/packages/react-dom/src/server/ReactPartialRendererHooks.js#L404 -- dispatchAction
wsReducer	@	useWSConnector.js:11 <-- my reduce()
dispatchAction	@	react-dom.development.js:14088
(anonymous)	@	useWSConnector.js:73 <-- my custom hook (the exact line to dispatch())
```

Second stack-trace that is called implicitly.
```
https://github.com/facebook/react/blob/42794557ca44a8c05c71aab698d44d1294236538/packages/react-reconciler/src/ReactFiberHooks.js#L658 -- updateReducer
wsReducer	@	useWSConnector.js:11 <-- my reduce()
updateReducer	@	react-dom.development.js:13741
useReducer	@	react-dom.development.js:14349
useReducer	@	react.development.js:1500
useWS	@	useWSConnector.js:41  <-- my custom hook (the stack to the start of my custom hook)
```

As, I am not familiar with `react-dom` source code, some hints around what may be happening in both the call-stacks may help.

**What is the expected behavior?**
when a `dispatch()` of OOTB `useReducer` is called, all instances should call the `reduce()` only once.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.6, Chrome 75.0.3770.142 (Official Build) (64-bit)

**Comment by steida** [comment]
I run over the same issue and Sebastian told me it's the correct behavior.

> One dispatch can call a reducer twice under certain conditions but it would call it with the old state as input. So if it's pure, it's unobservable. A reducer function must be pure.

If reducer is pure, and it has to be pure, nothing observable happens.

**Comment by babloo80** [comment]
>If reducer is pure, and it has to be pure, nothing observable happens.

Absolutely agree. But, in order to make sure that the events are coded in correctly, does it help to put this in release-notes or some place where this is termed as `expectation` ? 
Because, keeping reducer pure is beyond the realm of good practice for this above behavior 🤓.

**Comment by my-illusion** [comment]
putting the reducers out of the main Function could resolve this problem

**Comment by babloo80** [comment]
the `reducer` used in the above code is outside the custom hook named `useWSConnector`.

**Comment by gaearon** [comment]
As stated above, this is expected behavior in some cases, and should be unobervable to your code because reducers should be pure.

**Comment by 0xorial** [comment]
This is worth mentioning in the docs

**Comment by kuzzmi** [comment]
I was scratching my head for a good few days, but found a point to start further search - `<React.StrictMode>`.

Here's a minimal example of this issue: https://codesandbox.io/s/objective-rubin-4sfgf
Removing `<React.StrictMode>` fixes the whole thing.

```
import * as React from "react";

export const Test = () => {
  console.log('Test()');
  React.useReducer((s: any, a: any) => s, 0);       
  
  return <div />;
}

export default function App() {
  console.log('Test()');
  return (
    <React.StrictMode>
      <Test />
    </React.StrictMode>
  );
}
```

**Comment by jptaylor** [comment]
As above, I was confused as to why my actions were being reduced twice (my reducer is pure.) Seems that using `<React.Strictmode>` causes this to happen, although diving into the docs I'm unable to understand why that is happening

**Comment by gaearon** [comment]
That's the purpose of Strict Mode.

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

>Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions: [...]

**Comment by melvin2016** [comment]
Yes, the reducers are called twice and I can't seem to understand the problem.

**Comment by gaearon** [comment]
There is no "problem". React intentionally calls your reducer twice to make any unexpected side effects more apparent. Since your reducer is pure, calling it twice doesn't affect the logic of your application. So you shouldn't worry about this.

**Comment by tylergraf** [comment]
Correct me if I'm wrong, but this is my understanding of one of the things that this intentionally helps solve.

`INCREMENT` is pure and `DECREMENT` is impure. Or maybe I'm not understanding those terms correctly. Either way, `DECREMENT` is not desired.
```javascript
const counterReducer = (state, action) => {
  switch (action.type) {
    case "INCREMENT":
      return { ...state, count: state.count + 1 };
    case "DECREMENT":
      state.count = state.count - 1;
      return { ...state };
    case "RESET":
      return { count: 0 };
    default:
      break;
  }
};

...

dispatch({type: 'INCREMENT'}) // state.count: 1
dispatch({type: 'INCREMENT'}) // state.count: 2
dispatch({type: 'INCREMENT'}) // state.count: 3
dispatch({type: 'INCREMENT'}) // state.count: 4
dispatch({type: 'INCREMENT'}) // state.count: 5

dispatch({type: 'DECREMENT'}) // state.count: 3
dispatch({type: 'DECREMENT'}) // state.count: 1
dispatch({type: 'DECREMENT'}) // state.count: -1 
```

Here's a sandbox example: https://codesandbox.io/s/determined-fermat-lvqbv?file=/src/App.js

**Comment by gaearon** [comment]
Correct.

**Comment by melvin2016** [comment]
We could add a note in the documentation. So that everyone could understand.

**Comment by karthick3018** [comment]
> There is no "problem". **React intentionally calls your reducer twice** to make any unexpected side effects more apparent. Since your reducer is pure, calling it twice doesn't affect the logic of your application. So you shouldn't worry about this.
> 
> In production, it will only be called once.



> There is no "problem". **React intentionally calls your reducer twice** to make any unexpected side effects more apparent. Since your reducer is pure, calling it twice doesn't affect the logic of your application. So you shouldn't worry about this.
> 
> In production, it will only be called once.

hey @gaearon  what if I need to update a value in the state which is of type boolean if the reducer renders twice my value will be ideal , like in my case 

```
const reducer: React.Reducer<IState, Actions> = (state, action) => {
  switch (action.type) {
    case 'CARD_CLICKED':
      return  {...state,isOpen: ! isOpen };
    default:
      throw new Error();
  }
}
```

**Comment by fakenickels** [comment]
That's why I prefer the original reducer version from ReasonReact instead https://github.com/bloodyowl/reason-react-update

**Comment by reanimatter** [comment]
Even though React.StrictMode helps to address some issues, to me, one of the main downfalls using it in development is the app logs that get messed up due to multiple render calls. It took some time until I eventually landed on this thread and found that there is nothing wrong with my app. I think there should be at least some warning in a console that observable behavior might be ok.

**Comment by ghostlandr** [comment]
Does it make sense to add a link to the [strict mode docs](https://reactjs.org/docs/strict-mode.html) by the `<React.StrictMode>` tags in the index.js file generated by create-react-app? Or is that unnecessary noise? Or does no one look at that file anyway and it wouldn't really do anything?

**Comment by brunitob** [comment]
Using  **const** instead of a **function**, solved my problem with only one execution.

```
 <button onClick={() => handleAction(element)} />

// =>  action

const handleAction = (el) => {
  dispatch({})
}
```

**Comment by matt-oxley** [comment]
What is the correct approach if you want to call a **side effect** with the **newly computed state** as a result of only **some** actions? An example might be, where you might write to the server if and only if the update did not itself come from the server. Putting this logic in the reducer is wrong, as mentioned above, but where else could it go?

**Comment by BooYeu** [comment]
You can use callback , like : useReducer(useCallback((prevState, action)=>{},[]))

**Comment by Diveafall** [comment]
I learned from this post the reason why `useReducer` calls the `reducer` twice and it annoyed me. But it made me look for the impurity in my code and eliminate it. Basically it did precisely what it was designed to do.

So thanks `React` team! ❤️

**Comment by WriterZephos** [comment]
I spent two days beating my head against the wall trying to figure this one out, as I was using console.log in my reducer and it was logging twice. I saw absolutely nothing in the docs. A bit of an oversight in my opinion.

**Comment by Agusss19** [comment]
Does it warranty the dispatch's will get executed in order?

**Comment by paolorr** [comment]
Can someone show me where is the impurity of my reducer?
The first time addToBasket is called once (correct) but the following calls are twice causing the quantity to add 2 instead of 1.

If I remove StrictMode it works fine.

```ts

import React, { createContext, useContext, useReducer } from 'react';

export interface Product {
  id: string;
  title: string;
  price: number;
  quantity: number;
  rating: number;
  image: string;
}

interface CartContextData {
  basket: Product[];
  totalItems: number;
  subtotal: number;
}

const initialState: CartContextData = {
  basket: [],
  totalItems: 0,
  subtotal: 0,
};

type Action = { type: 'ADD_TO_BASKET'; item: Omit<Product, 'quantity'> }

const CartContext = createContext<{
  state: CartContextData;
  dispatch: React.Dispatch<Action>;
}>({
  state: initialState,
  dispatch: () => null,
});

function fixDecimal(value: number) {
  return Number(value.toFixed(2));
}

function addToBasket(
  state: CartContextData,
  item: Omit<Product, 'quantity'>,
): CartContextData {
  let newBasket = [...state.basket];
  const index = newBasket.findIndex(product => product.id === item.id);

  console.log('called addToBasket');

  if (index < 0) {
    newBasket = [...newBasket, { ...item, quantity: 1 }];
  } else {
    console.log('quantity before:', newBasket[index].quantity);
    newBasket[index].quantity += 1;
    console.log('quantity after:', newBasket[index].quantity);
  }

  return {
    ...state,
    basket: newBasket,
    totalItems: state.totalItems + 1,
    subtotal: fixDecimal(state.subtotal + item.price),
  };
}

const reducer = (state: CartContextData, action: Action): CartContextData => {
  switch (action.type) {
    case 'ADD_TO_BASKET':
      return addToBasket(state, action.item);
    default:
      return state;
  }
};

const CartProvider: React.FC = ({ children }) => {
  const [state, dispatch] = useReducer(reducer, initialState);

  return (
    <CartContext.Provider value={{ state, dispatch }}>
      {children}
    </CartContext.Provider>
  );
};

function useCart(): [CartContextData, React.Dispatch<Action>] {
  const context = useContext(CartContext);

  if (!context) {
    throw new Error('useCart must be used within an CartProvider');
  }

  return [context.state, context.dispatch];
}

export { CartProvider, useCart };


```

```ts
...

  const [state, dispatch] = useCart();

  const addToBasket = useCallback(() => {
    console.log('button clicked');

    dispatch({
      type: 'ADD_TO_BASKET',
      item: {
        id,
        title,
        image,
        price,
        rating,
      },
    });
  }, [dispatch, id, title, image, price, rating]);

...
```

Log after clicking the button 3 times. The quantity should be 3 but is 5 due to the double calls

```
button clicked
called addToBasket
button clicked
called addToBasket
quantity before: 1
quantity after: 2
called addToBasket
quantity before: 2
quantity after: 3
button clicked
called addToBasket
quantity before: 3
quantity after: 4
called addToBasket
quantity before: 4
quantity after: 5
```

**Comment by marcelomrtnz** [comment]
I don't see it very helpfull that ```<React.StrictMode>``` execute some reducers twice, because some depend on the prevState, specially in the type of functions intended to be used by reducers:

_[As React docs says:](https://reactjs.org/docs/hooks-reference.html#usereducer)_
> useReducer is usually preferable to useState when you have complex state logic that involves multiple sub-values or when the next state depends on the previous one. 

I got in the use case where I have the state of a chat wich had an array of messages:
```
    messages: [{_id, }]
```

In my reducer I have a case called ```"ADD_MESSAGES"``` which takes the previous messages array, and added to it the new messages.

```
function reducer(chat, action){
    switch(action.type){
        case "ADD_MESSAGES": {
             const { new_messages } = action.payload
             const new_chat = { ...chat }
             new_chat.messages = [
                  ...new_chat.messages,
                  ...new_messages
             ]
         }
    }
}
```
If it's executed twice, it would add two times the same messages, wich lead me to the problem that it rendered twice the quantity of messages.
This could be solved with a third argument, wich is the length of the array of messages expected to be when the new messages are pushed, but i'm not sure how helpfull could this be in production.

It would be okay if React.StrictMode fired the reducer twice with the same prevState, i'm not sure if it already does it like this, but that isn't the behavior I watched in my bug. 🤔

**Comment by Achder** [comment]
I'm logging my actions and there this is a problem. 
Is there an alternative way to log actions without them being written twice?

**Comment by CptFabulouso** [comment]
@Achder I was just solving this, since the `action` object in both dispatch calls has the same reference, you can compare the incoming action with the last one to figure out if it's the repeated call. 
So the simplest (not smartest) solution would be as below.

```
let lastAction
const reducer = (state, action) => {
    if(lastAction !== action){
        console.log(action);
    }
    lastAction = action;

    // ...reducerLogic
}
```
There might be some edge cases where it fails, I don't know the exact implementation of those two calls and if any other action can be dispatched between them.

**Comment by haifzhan** [comment]
> Correct me if I'm wrong, but this is my understanding of one of the things that this intentionally helps solve.
> 
> `INCREMENT` is pure and `DECREMENT` is impure. Or maybe I'm not understanding those terms correctly. Either way, `DECREMENT` is not desired.
> 
> ```js
> const counterReducer = (state, action) => {
>   switch (action.type) {
>     case "INCREMENT":
>       return { ...state, count: state.count + 1 };
>     case "DECREMENT":
>       state.count = state.count - 1;
>       return { ...state };
>     case "RESET":
>       return { count: 0 };
>     default:
>       break;
>   }
> };
> 
> ...
> 
> dispatch({type: 'INCREMENT'}) // state.count: 1
> dispatch({type: 'INCREMENT'}) // state.count: 2
> dispatch({type: 'INCREMENT'}) // state.count: 3
> dispatch({type: 'INCREMENT'}) // state.count: 4
> dispatch({type: 'INCREMENT'}) // state.count: 5
> 
> dispatch({type: 'DECREMENT'}) // state.count: 3
> dispatch({type: 'DECREMENT'}) // state.count: 1
> dispatch({type: 'DECREMENT'}) // state.count: -1 
> ```
> 
> Here's a sandbox example: https://codesandbox.io/s/determined-fermat-lvqbv?file=/src/App.js

Have you figured it out? I have a similar issue.

**Comment by haifzhan** [comment]
> Can someone show me where is the impurity of my reducer?
> The first time addToBasket is called once (correct) but the following calls are twice causing the quantity to add 2 instead of 1.
> 
> If I remove StrictMode it works fine.
> 
> ```ts
> import React, { createContext, useContext, useReducer } from 'react';
> 
> export interface Product {
>   id: string;
>   title: string;
>   price: number;
>   quantity: number;
>   rating: number;
>   image: string;
> }
> 
> interface CartContextData {
>   basket: Product[];
>   totalItems: number;
>   subtotal: number;
> }
> 
> const initialState: CartContextData = {
>   basket: [],
>   totalItems: 0,
>   subtotal: 0,
> };
> 
> type Action = { type: 'ADD_TO_BASKET'; item: Omit<Product, 'quantity'> }
> 
> const CartContext = createContext<{
>   state: CartContextData;
>   dispatch: React.Dispatch<Action>;
> }>({
>   state: initialState,
>   dispatch: () => null,
> });
> 
> function fixDecimal(value: number) {
>   return Number(value.toFixed(2));
> }
> 
> function addToBasket(
>   state: CartContextData,
>   item: Omit<Product, 'quantity'>,
> ): CartContextData {
>   let newBasket = [...state.basket];
>   const index = newBasket.findIndex(product => product.id === item.id);
> 
>   console.log('called addToBasket');
> 
>   if (index < 0) {
>     newBasket = [...newBasket, { ...item, quantity: 1 }];
>   } else {
>     console.log('quantity before:', newBasket[index].quantity);
>     newBasket[index].quantity += 1;
>     console.log('quantity after:', newBasket[index].quantity);
>   }
> 
>   return {
>     ...state,
>     basket: newBasket,
>     totalItems: state.totalItems + 1,
>     subtotal: fixDecimal(state.subtotal + item.price),
>   };
> }
> 
> const reducer = (state: CartContextData, action: Action): CartContextData => {
>   switch (action.type) {
>     case 'ADD_TO_BASKET':
>       return addToBasket(state, action.item);
>     default:
>       return state;
>   }
> };
> 
> const CartProvider: React.FC = ({ children }) => {
>   const [state, dispatch] = useReducer(reducer, initialState);
> 
>   return (
>     <CartContext.Provider value={{ state, dispatch }}>
>       {children}
>     </CartContext.Provider>
>   );
> };
> 
> function useCart(): [CartContextData, React.Dispatch<Action>] {
>   const context = useContext(CartContext);
> 
>   if (!context) {
>     throw new Error('useCart must be used within an CartProvider');
>   }
> 
>   return [context.state, context.dispatch];
> }
> 
> export { CartProvider, useCart };
> ```
> 
> ```ts
> ...
> 
>   const [state, dispatch] = useCart();
> 
>   const addToBasket = useCallback(() => {
>     console.log('button clicked');
> 
>     dispatch({
>       type: 'ADD_TO_BASKET',
>       item: {
>         id,
>         title,
>         image,
>         price,
>         rating,
>       },
>     });
>   }, [dispatch, id, title, image, price, rating]);
> 
> ...
> ```
> 
> Log after clicking the button 3 times. The quantity should be 3 but is 5 due to the double calls
> 
> ```
> button clicked
> called addToBasket
> button clicked
> called addToBasket
> quantity before: 1
> quantity after: 2
> called addToBasket
> quantity before: 2
> quantity after: 3
> button clicked
> called addToBasket
> quantity before: 3
> quantity after: 4
> called addToBasket
> quantity before: 4
> quantity after: 5
> ```

Hi @paolorr , have you figured it out? I have implemented a similar cart reducer and encountered the same issue, have you figured out how to solve it?

**Comment by haifzhan** [comment]
@paolorr I have figured out the issue in my code.

Before:
```
// the issue here is that I mutate the quantity value.
cart.purchases[index] = {
  product: action.product,
  quantity: newCart.purchases[index].quantity + 1,
};
```

After: 
```
// I was mutating purchases and now increment its quantity in an immutable way:
  const incrementPurchasesQuantity = (purchases: Purchase[], index: number) => {
      return [
        ...purchases.slice(0, index),
        { ...purchases[index], quantity: purchases[index].quantity + 1 },
        ...purchases.slice(index + 1),
      ];
  };


  cart = {
    shop,
    purchases: incrementPurchasesQuantity(purchases, index),
  };

```
Hope it helps.

**Comment by alundiak** [comment]
@my-illusion @brunitob I did have my reducer function OUT of main functional component, and neither regular `function` nor `const` approach helped to avoid double executing reducer function (switch for action.type entered twice, but console.log() was always single).

In my code, I do have a few actions, and one does `Math.random()` and I put code INSIDE of `switch` `case` clause. And as a solution avoid "bad" application behavior (with wrapped `<React.StrictMode>`) was to pass data BEFORE - meaning via dispatch({}) function.

From the other hand (as suggested @kuzzmi and also [stackoverflow](https://stackoverflow.com/questions/54892403/usereducer-action-dispatched-twice) ) when I removed `<React.StrictMode>` from `index.tsx` in my CRA-based app, sure thing reducer executed ONLY once. BUT. I agree with purpose of `<React.StrictMode>` **and I don't want to remove it**. YES, it also shows me inpurity of code, as similary mentioned @Diveafall. Despite the fact I believe my reducer is 'pure', I now have some doubts. 

Anyhow, I read one more time docs from [here](https://reactjs.org/docs/hooks-reference.html#usereducer), and I somehow agree w @0xorial (there is no mention about strict mode specifically in regards to useReducer), but when [here](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) which also @gaearon pointed out about double-invoking, which is very good feature of React, but rather not intuitive at first time, when you don't expect side effects.

**Comment by dabocla** [comment]
> Correct me if I'm wrong, but this is my understanding of one of the things that this intentionally helps solve.
> 
> `INCREMENT` is pure and `DECREMENT` is impure. Or maybe I'm not understanding those terms correctly. Either way, `DECREMENT` is not desired.
> 
> ```js
> const counterReducer = (state, action) => {
>   switch (action.type) {
>     case "INCREMENT":
>       return { ...state, count: state.count + 1 };
>     case "DECREMENT":
>       state.count = state.count - 1;
>       return { ...state };
>     case "RESET":
>       return { count: 0 };
>     default:
>       break;
>   }
> };
> 
> ...
> 
> dispatch({type: 'INCREMENT'}) // state.count: 1
> dispatch({type: 'INCREMENT'}) // state.count: 2
> dispatch({type: 'INCREMENT'}) // state.count: 3
> dispatch({type: 'INCREMENT'}) // state.count: 4
> dispatch({type: 'INCREMENT'}) // state.count: 5
> 
> dispatch({type: 'DECREMENT'}) // state.count: 3
> dispatch({type: 'DECREMENT'}) // state.count: 1
> dispatch({type: 'DECREMENT'}) // state.count: -1 
> ```
> 
> Here's a sandbox example: https://codesandbox.io/s/determined-fermat-lvqbv?file=/src/App.js

Thank you so much for the understanding.  I read your comment, and was able to resolve my issue.  The state can't be tinkered with.  I kept seeing references to 'pure', but had no idea what it meant.  You rock!

**Comment by DiegoCortezLFL** [comment]
this is super confusing.

**Comment by lydianlights** [comment]
My reducer is pure but computationally intensive and this functionality was causing excessive lag. Very confusing that my app was working twice as hard as it should have been. Imo this seems like a really weird choice of debugging method...

**Comment by aboziena1998** [comment]
const reducer = (
    cardsArray,
    { type, direction, currentIdx, cardContent }
  ) => {
    switch (type) {
      case "Added":
        return [...cardsArray, cardContent];
      case "Delete_All":
        return [];
      case "Deleted":
        if (cardsArray.length === 1) return [];
        else {
          let newArray = cardsArray.filter((q) => q.state !== "current");
          const current = cardsArray.findIndex(
            (item) => item.state === "current"
          );
          if (current <= newArray.length - 1)
            newArray[current].state = "current";
          else newArray[newArray.length - 1].state = "current";
          return newArray;
        }
      case "Slide":
        switch (direction) {
          case "next":
            if (currentIdx >= cardsArray.length - 1) return cardsArray;
            else {
              const newArray = [...cardsArray];
              newArray[currentIdx].state = "previous";
              newArray[currentIdx + 1].state = "current";
              return newArray;
            }
          case "previous":
            if (currentIdx <= 0) return cardsArray;
            else {
              const newArray = [...cardsArray];
              newArray[currentIdx].state = "next";
              newArray[currentIdx - 1].state = "current";
              return newArray;
            }
        }

      default:
        throw Error();
    }
  };

**Comment by aboziena1998** [comment]
```
const reducer = (
    cardsArray,
    { type, direction, currentIdx, cardContent }
  ) => {
    switch (type) {
      case "Added":
        return [...cardsArray, cardContent];
      case "Delete_All":
        return [];
      case "Deleted":
        if (cardsArray.length === 1) return [];
        else {
          let newArray = cardsArray.filter((q) => q.state !== "current");
          const current = cardsArray.findIndex(
            (item) => item.state === "current"
          );
          if (current <= newArray.length - 1)
            newArray[current].state = "current";
          else newArray[newArray.length - 1].state = "current";
          return newArray;
        }
      case "Slide":
        switch (direction) {
          case "next":
            if (currentIdx >= cardsArray.length - 1) return cardsArray;
            else {
              const newArray = [...cardsArray];
              newArray[currentIdx].state = "previous";
              newArray[currentIdx + 1].state = "current";
              return newArray;
            }
          case "previous":
            if (currentIdx <= 0) return cardsArray;
            else {
              const newArray = [...cardsArray];
              newArray[currentIdx].state = "next";
              newArray[currentIdx - 1].state = "current";
              return newArray;
            }
        }
      default:
        throw Error();
    }
  };
```

can someone tells me why "Deleted" action fires twice when clicking the button?

**Comment by remusgls** [comment]
@aboziena1998 maybe try to get a new maybe try to get a new reference  out of that array: `let newArray = cardsArray.filter((q) => q.state !== "current").map(item => item); `

hope this helps 🍻

**Comment by alanschwarz** [comment]
This thread just saved my startup 😅

**Comment by paulwongx** [comment]
For any noobs who wants to understand this... there will oftentimes be an error when called twice if one of the inputs are mutated which was in my case when I was using `splice` even with immerjs. So React is calling it twice to show you where an input may have been mutated so that the second time it calls, there is unexpected behaviour since the input is different. So the general solutions to solve this, as per others above... 

If you're using an object..
```js
// instead mutating directly
obj.a = 1;

// create a shallow copy
newObj = {...obj, a:1}
```

If it's a nested object.. consider using structuredClone
```js
// Instead of mutating directly..
obj.a.b.c = 1;

// create a copy 
const clone = structuredClone(obj);
clone.a.b.c. = 1;
```
If it's an array...
```js
const arr = [1,2,3,4]
// instead of mutating directly...
arr.splice(2,0,8);

// Create a copy and then update
const clone = arr.slice(0);
clone.splice(2,0,8)

// Note: This doesn't work since splice doesn't return the original array only mutates it
// does not work: arr.slice(0).splice(2,0,8)
```

**Comment by nyikonzoli** [comment]
I think my reducer function is pure, but it still doesn't work the way I want it to. I have a nested object and I want to append an array in the object but since the reducer function runs twice it adds the object twice to the array. I've been trying to fix it for days with no luck. Btw it work fine without strict mode but I'm a beginner react developer so I would prefer if it would work with strict mode as well.

Here is my code:
```
function new_data(state, currentSectionId, newData) {
  const keys = findById(state, currentSectionId).data.map((data) => data.id);
  const id = keys.length > 0 ? Math.max(...keys) + 1 : 1;
  let newSections = [...state];
  const currentNewSection = findById(newSections, currentSectionId);
  currentNewSection.data.push(newData(id));
  return newSections;
}

function findById(sections, id) {
  return sections.find((section) => {
    return section.id === id;
  });
}
```

newData just returns an object with that id.

**Comment by remusgls** [comment]
@nyikonzoli You may be modifying a exsting  reference of state, dunno how nested the `state` object is, but since it doesn’t reflect the change, I’m assuming your still changing that initial object. The way Id do it:

`let newSections = state.map(item => JSON.parse(JSON.stringify(item))`

again, not sure how deep that obj is, but if it goes too deep the `…` operator won’t create a new reference on deeply nested objects, rather a shallow copy of it. 

Hope this helps!

**Comment by nyikonzoli** [comment]
@remusgls Oh wow. I didn't expect this one. It solved my problem so I guess my object was too nested for the `...` operator. Good thing to know. Thank you, for the quick response!

**Comment by paulwongx** [comment]
@nyikonzoli In my writeup above, I mentioned that spread operators only work for shallow objects. The proper way to do what you want is a structured clone as per my writeup. But the stringify function recommended works too, just not best practice.

**Comment by peersky** [comment]
Just a note for anyone struggling here: For me issue of function impurity was produced by adding 
```
console.debug(state)
```
And removing debug logging ... removed bug itself xD
