### ISSUE TITLE
react-hooks/exhaustive-deps, React.useCallback has an unnecessary dependency. Keying off of related values

### ISSUE THREAD

**Issue by RickeyWard** [facebook/react#16291]
**Do you want to request a *feature* or report a *bug*?**
Bug? -ish
**What is the current behavior?**
If you add a deps list state variable but don't use it directly, you get a warning.

**What is the expected behavior?**
deps list allows you to provide sensitivity to a change, it should not be required to use the value that changed.
Possibly this warning should have the message changed to a "if you know what you're doing" type message, such as "you may have left this in by mistake"

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
^16.8.6

**example scenario, **
measuring the overflow of an element on window resize, `useCallback` used to get the reference to the element to get it's `overflow/inner/scroll` sizes, but this should only be done when the window resize event happens. This can be done using a `customHook` that calls `setWindowSize` when the window is resized, our original `useCallback` can be sensitive to this `windowSize` even though it doesn't need the value directly, it needs to know when that value changed.

I can add some arbitrary use of that dep to get the warning to go away, but that feels wrong. 

I realize in this example, the `useWindowSize` hook could live inside the `useCallback` hook but that would mean it's value couldn't be used by other hooks/components.

It works fine if the warning is ignored, But I have people on my team that see warnings as rules and since react hooks are new, it's hard to argue that it's okay in this case.
maybe this whole issue is due to some underlying misunderstanding on my part, but think I'm using them correctly.

**Comment by Dergash** [comment]
It's hard to say without a code, but would you consider useEffect or useLayoutEffect instead of useCallback? It sounds like they meant exactly for things like window resize.

**Comment by RickeyWard** [comment]
https://github.com/RickeyWard/react-ellipsis-block/tree/master/src

UseEffect is being used for that purpose, but the result of that needs to interact with a ref. When useEffect mutates state, I need that state to trigger a change on the ref. It all works fine, I just get a warning that I’m passing a dep I don’t use, but I am using the fact that it changed. Not it’s actual value.

Maybe this is a niche example, but I feel it’s a legitimate use case.

**Comment by RickeyWard** [comment]
since this is just a dev warning and doesn't affect actual usage, I'll go ahead ad close this.

**Comment by tommedema** [comment]
@RickeyWard I have the same use case as you. Why is this closed? It may just be a warning but it confuses other developers and makes the app more difficult to work with as you need to remember which warnings to ignore and which not.

**Comment by RickeyWard** [comment]
@tommedema Basically it wasn't worth it to convince anyone, as the warnings teach people to use deps as designed. This is an acceptable use cause but it means the warning wouldn't be there in the inverse situation where dependencies were accidentally left in the list accidentally. You can cheese the warning by just using the variable somewhere superfluously. It's a hack, but it shows other people that you want that variable there for a reason which won't be immediately clear if it's just there for seemingly no reason. (this is the case where a comment is essential) Just wasn't a clear cut right/wrong, so in those cases 'leave it as it is' almost always wins. It's a warning not an error. though teams hate seeing them. 

Sometimes we just have to deal with them. There are perfectly good reason to use == instead of ===, but good luck getting rid of that warning either.

**Comment by tommedema** [comment]
Hmm ok. Well I went with an eslint-ignore rule. Not great, but prefer it over "superfluously" using the variables

**Comment by RickeyWard** [comment]
I still suggest the comment, as another maintainer might just think you have it in there by mistake.

**Comment by sag1v** [comment]
I'm wondering why `useCallback` deps behave differently than `useEffect`/`useLayoutEffect`.

With `useCallback` we get the warning:

```js
function useIsTextOverflow(value) {
  const [isOverflow, setIsOverflow] = useState(false);

  const refCallback = useCallback((node) => {
    if (node) {
      const isOverflowing = node.scrollWidth > node.clientWidth;
      setIsOverflow(isOverflowing);
    }
  }, [value]); // <- yields unnecessary dependency

  return [isOverflow, refCallback];
}
``` 

With `useEffect` we don't get a warning

```js
function useIsTextOverflow(value) {
  const [isOverflow, setIsOverflow] = useState(false);
  const elementRef = useRef();

  useLayoutEffect(() => {
    if (elementRef.current) {
      const { scrollWidth, clientWidth } = elementRef.current;
      const isOverflowing = scrollWidth > clientWidth;
      setIsOverflow(isOverflowing);
    }
  }, [value]); // <- no warning

  return [isOverflow, elementRef];
}
```

I know we can "solve" this by ignoring the rule or just use the `value` e.g:

```
if (node && value)
```
Or something similar, but is it valid to include a dependency just for the sake of synchronizing and not actually use it?

---

cc @gaearon / @sebmarkbage 
Can you shed some light on this please? I'm not sure if this is just a use case that the lint plugin is missing, or maybe there *is* some difference with the way effects and other hooks deal with dependencies.
