### ISSUE TITLE
Detecting if `ref` can be passed

### ISSUE THREAD

**Issue by catamphetamine** [facebook/react#16309]
How can one tell if the `component` being passed is `ref`-able?
There was a way to tell a function from a class:
https://overreacted.io/how-does-react-tell-a-class-from-a-function/

```js
/**
 * Checks if the argument is a React.Component class.
 * https://overreacted.io/how-does-react-tell-a-class-from-a-function/
 * @param  {any}  Component
 * @return {boolean}
 */
function isComponentClass(Component) {
	// return Component.prototype instanceof React.Component
	return Component.prototype.isReactComponent
}
```

But now there're also `React.memo()` that has `.prototype === undefined` and `React.forwardRef()` that can be passed a `ref` but also has `.prototype === undefined`.

What's the simplest way of telling if `ref` could be passed to a component without having React complaining about it?

**Comment by eps1lon** [comment]
Checking if something can't be passed a ref is likely better e.g. `const rejectsRef = typeof Component === 'function' && !isComponentClass(Component)`.

For `memo` or especially `lazy` you can't really tell. With memo you could access some react internals but for lazy you can never be sure if the resolved component accepts a ref.

**Comment by catamphetamine** [comment]
@eps1lon I see, so there's no reliable way currently.
You can close this issue if you feel like this is not a required feature in React.
In the meantime I'll add an explicit `useRef: true/false` property that a user can pass.

**Comment by gaearon** [comment]
There is no way to do that.
