### ISSUE TITLE
Different Suspense Behavior in ReactDOM.render vs React.createRoot().render

### ISSUE THREAD

**Issue by bijection** [facebook/react#16305]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Throwing a resolved promise inside an app mounted with `React.unstable_createRoot().render()` triggers the suspense fallback render, defocusing inputs in the app.

In contrast, throwing an immediately resolved promise inside the same app rendered with  `ReactDOM.render()` does not trigger the suspense fallback render.

Here's a small reproduction showing the different behaviors: 
```javascript
import React from "react";
import ReactDOM from "react-dom";

let cache = {};

function MyApp() {
  let [text, setText] = React.useState("edit this");

  if (!cache[text]) {
    cache[text] = true;
    throw Promise.resolve();
  }

  return <input value={text} onChange={e => setText(e.target.value)} />;
}

let fallback = <div style={{ background: "red" }}>fallback</div>;
let dom = (
  <React.Suspense fallback={fallback}>
    <MyApp />
  </React.Suspense>
);

// Switch out the following two lines and type in the input
// to see the difference in behavior

ReactDOM.unstable_createRoot(document.getElementById("root")).render(dom);
// ReactDOM.render(dom, document.getElementById("root"));

```

Here's a CodeSandbox with the code above: https://codesandbox.io/s/stupefied-cookies-qh8sy

**What is the expected behavior?**

Throwing an immediately resolved promise inside an app mounted with `React.unstable_createRoot().render()` should not trigger the suspense fallback render. Instead, it should behave identically to the app mounted with `ReactDOM.render()`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm using Chrome 75.0.3770.142, macOS 10.14.3, and react 16.9.0-alpha-0

N.B. This issue is pretty much the same as #15900, though that one seemed to have more moving parts. Please merge these if appropriate.

**Comment by gaearon** [comment]
>Throwing an immediately resolved promise inside an app mounted with React.unstable_createRoot().render() should not trigger the suspense fallback render.

Can you explain why? What is your reasoning?
