### ISSUE TITLE
React useState hook updating value multiple times in sequence

### ISSUE THREAD

**Issue by ErAz7** [facebook/react#16307]
### Do you want to request a feature or report a bug?

bug

### What is the current behavior?

When trying to update a useState hook value by calling updater function (setState in this example) more than once and in sequence in an event handler, the last one overrides previous updates.

Example:
```
import React, { useState } from "react";
import ReactDOM from "react-dom";

const SomeComponent = () => {
  const [state, setState] = useState({
    value1: 0,
    value2: 0,
  });

  function onClick(event){
    setState({
        ...state,
        value1: 1,          
    });
    setState({
        ...state,
        value2: 2,         
    });
  }

  return (
    <div>      
      <button onClick={onClick}>Click Me</button>
      <h2>value1: {state.value1}</h2>
      <h2>value2: {state.value2}</h2>
    </div>
  );
};

ReactDOM.render(
    <SomeComponent />, 
document.getElementById("root"));

```
### What is the expected behavior?
Updating both value1 and value2 in state

### Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?
(don't seem to be version or OS specific)
**react:** 16.8.6
**browser:** chrome 76.0.3809.87
**OS:** Windows 10

**Comment by vkurchatkin** [comment]
In your `onClick` function `state` refers to the same constant value. Calling `setState` doesn't change it, nothing does. Just do this:

```js
  setState({
        ...state,
        value1: 1,       
        value2: 2,            
    });
```

If you need some branching in your code, you could do this as well:

```js
const newState = { ...state };

newState.value1 = 1;

if (foo) {
  newState.value2 = 2 
}

setState(newState);
```

**Comment by ErAz7** [comment]
Solved 
My actual project case was something like this:
```
function changeOtherValue(){
     setState({
       ...state,
       value2: 2
    });
}
function onClick(event) {
    setState({
      ...state,
      value1: 1
    });    
    changeOtherValue();
 }
```
All your suggestions work but third one is the solution
Thank you
