### ISSUE TITLE
useEffect false positive requiring dependencies 

### ISSUE THREAD

**Issue by thian4** [facebook/react#16308]
https://codesandbox.io/s/lively-sea-2crwk

missing dependencies in useEffect throw false positive warning in some case. How can I remove the warning above? I can think of firing the callback on `setDropdown(, () => console.log('call api here'))`

```
useEffect(() => {
    if (inputVal) {
      callApi({ inputVal, dropdown });
    }
  }, [dropdown]);
```

**Comment by TheGallery** [comment]
This warning doesn't seem like a false positive. It is mentioned in the [React docs here](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies) that 

> If you specify a list of dependencies as the last argument to useEffect, useMemo, useCallback, or useImperativeHandle, it must include all values used inside that participate in the React data flow. That includes props, state, and anything derived from them.

I looks like you are trying to emulate an event handler behaviour here, so you could just call the `callApi` function inside the `onChange` handler of the select element.

**Comment by threepointone** [comment]
^ This is the right answer, and a good followup suggestion.

**Comment by thian4** [comment]
@TheGallery what if I have multiple select?

**Comment by TheGallery** [comment]
In this case, just create a function and pass it as an event handler similarly to what you did with `handleSubmit`
