### ISSUE TITLE
Suspense and Lazy increases bundle size

### ISSUE THREAD

**Issue by dimblek7** [facebook/react#16300]
Use of React, Suspense and Lazy is increasing bundle size.

I created a bundle with use of Suspense lazy, its size was **127mb**.
Then I removed the use of Suspense lazy, and did normal imports, in result, the build was **80mb** only.

Build size should not get affected.

I am using React app created via create-react-app.

**Comment by gaearon** [comment]
First of all, both 127 MB and 80 MB bundles seem huge to the point where I feel your measurement must be incorrect.

But even if it's correct, it's hard to help with a vague report like this. Please create a minimal reproducing example and file this issue in Create React App repo instead. Thanks.
