### ISSUE TITLE
React's Lifecycle is Wrong

### ISSUE THREAD

**Issue by contrarian** [facebook/react#16316]
**Do you want to request a *feature* or report a *bug*?**
A bug. 

**What is the current behavior?**
 React currently computes instance lifecycle according to its reconciliation algorithm. If an instance experiences any divergence in ancestral element types, then React will unmount and remount an instance that never left. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle:
https://codesandbox.io/embed/cranky-grothendieck-xtqnn

**What is the expected behavior?**
React should use the **instance tree** as defined in this [document](https://github.com/gactjs/gact/blob/master/docs/view-tree-duality.md) to compute instance lifecycle. The computation of lifecycle can be complemented with a ```key``` based strategy in the rare cases when comparing instance trees would conflate two distinct instances. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
all versions, all platforms

**Comment by threepointone** [comment]
I don’t understand how this is a bug? This is the stated and expected behaviour for react. I don’t think react will ever get this exact feature either. 

There’s a broader discussion to be had for _reparenting_ trees, which we may get to in the future. 

Closing this issue.

**Comment by contrarian** [comment]
It's a conceptual bug. React correctly implements an incorrect notion of lifecycle. 

I'm not sure what you mean by "this exact feature". 

I challenge the React team to define React's notion of lifecycle without reference to the React reconciliation algorithm.

**Comment by markerikson** [comment]
"Lifecycles" are well defined: when a component mounts, updates, and unmounts.

What you're describing is when the mounting and unmounting should occur based on tree diffing, ie, the reconciliation part.

So, the first issue here is that you're phrasing the issue the wrong way.  Saying that "the reconciliation algorithm is wrong" is a totally different thing from saying "lifecycles are wrong".

**Comment by contrarian** [comment]
There's a well-defined correspondence between what's being done with an instance and lifecycle event (e.g instance created -> mount, instance destroyed -> unmount).

That correspondence is only a small part of a definition of lifecycle. You have to define when and why an instance will be created, updated, or destroyed. I'm asking you to define the latter without reference to React's reconciliation algorithm. 

You said: "Saying that 'the reconciliation algorithm is wrong' is a totally different thing from saying 'lifecycles are wrong'.  That's true unless your lifecycle computation is determined by your reconciliation algorithm. 

I'm saying that lifecycle computation (e.g which instances are mounting) is independent of reconciliation (going from DOM A -> DOM B). 

Specifically, I claim that lifecycle computation should be based on instance composition, and computed using the **instance tree** as defined in this [document](https://github.com/gactjs/gact/blob/master/docs/view-tree-duality.md).

**Comment by denis-sokolov** [comment]
I think this issue has been discarded needlessly quickly. Perhaps it’s not that “React’s lifecycle is wrong”, but it’s underdefined and somewhat misleading.

Consider [the documentation on reconciliation](https://reactjs.org/docs/reconciliation.html). It correctly states that “the reconciliation algorithm is an implementation detail”. And yet the decisions of the reconciliation algorithm cause the behavior of the application to change (see #17386, for an example).

React users must know the implementation details and they must author their applications as to fit these implementation details. This makes the implementation details not implementation details, but, rather, interface specification. And from this angle this issue is correct.
