### ISSUE TITLE
yarn test failing

### ISSUE THREAD

**Issue by kambleaa007** [facebook/react#16314]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
failing yarn tests
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
should success
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Summary of all failing tests
 FAIL  packages/react-dom/src/__tests__/CSSPropertyOperations-test.js
  ● CSSPropertyOperations › should not add units to CSS custom properties

    expect(received).toEqual(expected)

    Expected value to equal:
      "5"
    Received:
      undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      253 |     ReactDOM.render(<Comp />, root);
      254 |
    > 255 |     expect(root.children[0].style.Foo).toEqual('5');
          |                                        ^
      256 |   });
      257 | });
      258 |

      at Object.<anonymous> (packages/react-dom/src/__tests__/CSSPropertyOperations-test.js:255:40)

 FAIL  packages/eslint-plugin-react-hooks/__tests__/ESLintRulesOfHooks-test.js (6.559s)
  ● react-hooks › valid ›
      // Valid because hooks can call hooks.
      function useHook() { useState(); }
      const whatever = function useHook() { useState(); };
      const useHook1 = () => { useState(); };
      let useHook2 = () => useState();
      useHook2 = () => { useState(); };
      ({useHook: () => { useState(); }});
      ({useHook() { useState(); }});
      const {useHook = () => { useState(); }} = {};
      ({useHook = () => { useState(); }} = {});

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      0
    Received:
      1

    Message:
      Should have no errors but had 1: [ { ruleId: null,
        fatal: true,
        severity: 2,
        source: '      const {useHook = () => { useState(); }} = {};',
        message:
         'Parsing error: Identifier \'useHook\' has already been declared\n\n\u001b[0m \u001b[90m  8 | \u001b[39m      ({useHook\u001b[33m:\u001b[39m () \u001b[33m=>\u001b[39m { useState()\u001b[33m;\u001b[39m }})\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m  9 | \u001b[39m      ({useHook() { useState()\u001b[33m;\u001b[39m }})\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 10 | \u001b[39m      \u001b[36mconst\u001b[39m {useHook \u001b[33m=\u001b[39m () \u001b[33m=>\u001b[39m { useState()\u001b[33m;\u001b[39m }} \u001b[33m=\u001b[39m {}\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m             \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 11 | \u001b[39m      ({useHook \u001b[33m=\u001b[39m () \u001b[33m=>\u001b[39m { useState()\u001b[33m;\u001b[39m }} \u001b[33m=\u001b[39m {})\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 12 | \u001b[39m    \u001b[0m',
        line: 10,
        column: 14 } ]

      at testValidTemplate (node_modules/eslint/lib/testers/rule-tester.js:418:20)
      at Object.RuleTester.it (node_modules/eslint/lib/testers/rule-tester.js:573:25)

 FAIL  packages/react/src/__tests__/createReactClassIntegration-test.js (6.668s)
  ● create-react-class-integration › warns if getDerivedStateFromProps is not static

    Error: Unexpected warning recorded: - Expected
    + Received

    - Component: getDerivedStateFromProps() is defined as an instance method and will be ignored. Instead, declare it as a static method.
    + Warning: Foo: getDerivedStateFromProps() is defined as an instance method and will be ignored. Instead, declare it as a static method.

      129 |         // We don't throw an Error here though,
      130 |         // Because it might be suppressed by ReactFiberScheduler.
    > 131 |         unexpectedWarnings.push(new Error(errorMessage));
          |                                   ^
      132 |       };
      133 |
      134 |       // TODO Decide whether we need to support nested toWarn* expectations.

      at BufferedConsole.consoleSpy (scripts/jest/matchers/toWarnDev.js:131:35)
      at warningWithoutStack (packages/shared/warningWithoutStack.js:40:32)
      at checkClassInstance (packages/react-reconciler/src/ReactFiberClassComponent.js:500:76)
      at mountClassInstance (packages/react-reconciler/src/ReactFiberClassComponent.js:798:5)
      at updateClassComponent (packages/react-reconciler/src/ReactFiberBeginWork.js:2614:168)
      at beginWork (packages/react-reconciler/src/ReactFiberBeginWork.js:2944:1125)
      at beginWork (packages/react-reconciler/src/ReactFiberWorkLoop.js:3201:153)
      at performUnitOfWork (packages/react-reconciler/src/ReactFiberWorkLoop.js:3016:501)
      at workLoopSync (packages/react-reconciler/src/ReactFiberWorkLoop.js:3012:213)
      at renderRoot (packages/react-reconciler/src/ReactFiberWorkLoop.js:2925:242)
      at scheduleUpdateOnFiber (packages/react-reconciler/src/ReactFiberWorkLoop.js:2835:22)
      at scheduleRootUpdate (packages/react-reconciler/src/ReactFiberReconciler.js:491:560)
      at updateContainerAtExpirationTime (packages/react-reconciler/src/ReactFiberReconciler.js:492:564)
      at updateContainer (packages/react-reconciler/src/ReactFiberReconciler.js:493:364)
      at packages/react-dom/src/client/ReactDOM.js:570:35
      at unbatchedUpdates (packages/react-reconciler/src/ReactFiberWorkLoop.js:2886:240)
      at legacyRenderSubtreeIntoContainer (packages/react-dom/src/client/ReactDOM.js:569:34)
      at Object.render (packages/react-dom/src/client/ReactDOM.js:677:12)
      at packages/react/src/__tests__/createReactClassIntegration-test.js:454:18
      at Object.matcher (scripts/jest/matchers/toWarnDev.js:143:11)
      at Object.throwingMatcher [as toWarnDev] (node_modules/expect/build/index.js:320:33)
      at Object.<anonymous> (packages/react/src/__tests__/createReactClassIntegration-test.js:455:5)
      at Object.<anonymous> (packages/react/src/__tests__/createReactClassIntegration-test.js:455:5)

  ● create-react-class-integration › warns if getDerivedStateFromError is not static

    Error: Unexpected warning recorded: - Expected
    + Received

    - Component: getDerivedStateFromError() is defined as an instance method and will be ignored. Instead, declare it as a static method.
    + Warning: Foo: getDerivedStateFromError() is defined as an instance method and will be ignored. Instead, declare it as a static method.

      129 |         // We don't throw an Error here though,
      130 |         // Because it might be suppressed by ReactFiberScheduler.
    > 131 |         unexpectedWarnings.push(new Error(errorMessage));
          |                                   ^
      132 |       };
      133 |
      134 |       // TODO Decide whether we need to support nested toWarn* expectations.

      at BufferedConsole.consoleSpy (scripts/jest/matchers/toWarnDev.js:131:35)
      at warningWithoutStack (packages/shared/warningWithoutStack.js:40:32)
      at checkClassInstance (packages/react-reconciler/src/ReactFiberClassComponent.js:508:76)
      at mountClassInstance (packages/react-reconciler/src/ReactFiberClassComponent.js:798:5)
      at updateClassComponent (packages/react-reconciler/src/ReactFiberBeginWork.js:2614:168)
      at beginWork (packages/react-reconciler/src/ReactFiberBeginWork.js:2944:1125)
      at beginWork (packages/react-reconciler/src/ReactFiberWorkLoop.js:3201:153)
      at performUnitOfWork (packages/react-reconciler/src/ReactFiberWorkLoop.js:3016:501)
      at workLoopSync (packages/react-reconciler/src/ReactFiberWorkLoop.js:3012:213)
      at renderRoot (packages/react-reconciler/src/ReactFiberWorkLoop.js:2925:242)
      at scheduleUpdateOnFiber (packages/react-reconciler/src/ReactFiberWorkLoop.js:2835:22)
      at scheduleRootUpdate (packages/react-reconciler/src/ReactFiberReconciler.js:491:560)
      at updateContainerAtExpirationTime (packages/react-reconciler/src/ReactFiberReconciler.js:492:564)
      at updateContainer (packages/react-reconciler/src/ReactFiberReconciler.js:493:364)
      at packages/react-dom/src/client/ReactDOM.js:570:35
      at unbatchedUpdates (packages/react-reconciler/src/ReactFiberWorkLoop.js:2886:240)
      at legacyRenderSubtreeIntoContainer (packages/react-dom/src/client/ReactDOM.js:569:34)
      at Object.render (packages/react-dom/src/client/ReactDOM.js:677:12)
      at packages/react/src/__tests__/createReactClassIntegration-test.js:472:18
      at Object.matcher (scripts/jest/matchers/toWarnDev.js:143:11)
      at Object.throwingMatcher [as toWarnDev] (node_modules/expect/build/index.js:320:33)
      at Object.<anonymous> (packages/react/src/__tests__/createReactClassIntegration-test.js:473:5)
      at Object.<anonymous> (packages/react/src/__tests__/createReactClassIntegration-test.js:473:5)

  ● create-react-class-integration › warns if getSnapshotBeforeUpdate is static

    Error: Unexpected warning recorded: - Expected
    + Received

    - Component: getSnapshotBeforeUpdate() is defined as a static method and will be ignored. Instead, declare it as an instance method.
    + Warning: Foo: getSnapshotBeforeUpdate() is defined as a static method and will be ignored. Instead, declare it as an instance method.

      129 |         // We don't throw an Error here though,
      130 |         // Because it might be suppressed by ReactFiberScheduler.
    > 131 |         unexpectedWarnings.push(new Error(errorMessage));
          |                                   ^
      132 |       };
      133 |
      134 |       // TODO Decide whether we need to support nested toWarn* expectations.

      at BufferedConsole.consoleSpy (scripts/jest/matchers/toWarnDev.js:131:35)
      at warningWithoutStack (packages/shared/warningWithoutStack.js:40:32)
      at checkClassInstance (packages/react-reconciler/src/ReactFiberClassComponent.js:516:73)
      at mountClassInstance (packages/react-reconciler/src/ReactFiberClassComponent.js:798:5)
      at updateClassComponent (packages/react-reconciler/src/ReactFiberBeginWork.js:2614:168)
      at beginWork (packages/react-reconciler/src/ReactFiberBeginWork.js:2944:1125)
      at beginWork (packages/react-reconciler/src/ReactFiberWorkLoop.js:3201:153)
      at performUnitOfWork (packages/react-reconciler/src/ReactFiberWorkLoop.js:3016:501)
      at workLoopSync (packages/react-reconciler/src/ReactFiberWorkLoop.js:3012:213)
      at renderRoot (packages/react-reconciler/src/ReactFiberWorkLoop.js:2925:242)
      at scheduleUpdateOnFiber (packages/react-reconciler/src/ReactFiberWorkLoop.js:2835:22)
      at scheduleRootUpdate (packages/react-reconciler/src/ReactFiberReconciler.js:491:560)
      at updateContainerAtExpirationTime (packages/react-reconciler/src/ReactFiberReconciler.js:492:564)
      at updateContainer (packages/react-reconciler/src/ReactFiberReconciler.js:493:364)
      at packages/react-dom/src/client/ReactDOM.js:570:35
      at unbatchedUpdates (packages/react-reconciler/src/ReactFiberWorkLoop.js:2886:240)
      at legacyRenderSubtreeIntoContainer (packages/react-dom/src/client/ReactDOM.js:569:34)
      at Object.render (packages/react-dom/src/client/ReactDOM.js:677:12)
      at packages/react/src/__tests__/createReactClassIntegration-test.js:492:18
      at Object.matcher (scripts/jest/matchers/toWarnDev.js:143:11)
      at Object.throwingMatcher [as toWarnDev] (node_modules/expect/build/index.js:320:33)
      at Object.<anonymous> (packages/react/src/__tests__/createReactClassIntegration-test.js:493:5)
      at Object.<anonymous> (packages/react/src/__tests__/createReactClassIntegration-test.js:493:5)

 FAIL  packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js (7.708s)
  ● react-hooks › valid ›
        function useMyThing(myRef) {
          const myRef = useRef();
          useEffect(() => {
            const handleMove = () => {};
            const node = myRef.current;
            node.addEventListener('mousemove', handleMove);
            return () => node.removeEventListener('mousemove', handleMove);
          }, [myRef]);
          return <div ref={myRef} />;
        }

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      0
    Received:
      1

    Message:
      Should have no errors but had 1: [ { ruleId: null,
        fatal: true,
        severity: 2,
        source: '          const myRef = useRef();',
        message:
         'Parsing error: Identifier \'myRef\' has already been declared\n\n\u001b[0m \u001b[90m 1 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2 | \u001b[39m        \u001b[36mfunction\u001b[39m useMyThing(myRef) {\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 3 | \u001b[39m          \u001b[36mconst\u001b[39m myRef \u001b[33m=\u001b[39m useRef()\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m                \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 4 | \u001b[39m          useEffect(() \u001b[33m=>\u001b[39m {\u001b[0m\n\u001b[0m \u001b[90m 5 | \u001b[39m            \u001b[36mconst\u001b[39m handleMove \u001b[33m=\u001b[39m () \u001b[33m=>\u001b[39m {}\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 6 | \u001b[39m            \u001b[36mconst\u001b[39m node \u001b[33m=\u001b[39m myRef\u001b[33m.\u001b[39mcurrent\u001b[33m;\u001b[39m\u001b[0m',
        line: 3,
        column: 17 } ]

      at testValidTemplate (node_modules/eslint/lib/testers/rule-tester.js:418:20)
      at Object.RuleTester.it (node_modules/eslint/lib/testers/rule-tester.js:573:25)

 FAIL  packages/react-dom/src/__tests__/ReactDOMComponent-test.js (15.691s)
  ● ReactDOMComponent › Object stringification › should pass objects as attributes if they define toString

    expect(received).toBe(expected) // Object.is equality

    Expected: "hello"
    Received: "http://localhost/hello"

      2428 |
      2429 |       ReactDOM.render(<img src={obj} />, container);
    > 2430 |       expect(container.firstChild.src).toBe('hello');
           |                                        ^
      2431 |
      2432 |       ReactDOM.render(<svg arabicForm={obj} />, container);
      2433 |       expect(container.firstChild.getAttribute('arabic-form')).toBe('hello');

      at Object.<anonymous> (packages/react-dom/src/__tests__/ReactDOMComponent-test.js:2430:40)

  ● ReactDOMComponent › Object stringification › allows objects that inherit a custom toString method

    expect(received).toBe(expected) // Object.is equality

    Expected: "hello.jpg"
    Received: "http://localhost/hello.jpg"

      2462 |       const el = ReactTestUtils.renderIntoDocument(<img src={child} />);
      2463 |
    > 2464 |       expect(el.src).toBe('hello.jpg');
           |                      ^
      2465 |     });
      2466 |
      2467 |     it('assigns ajaxify (an important internal FB attribute)', function() {

      at Object.<anonymous> (packages/react-dom/src/__tests__/ReactDOMComponent-test.js:2464:22)

 FAIL  packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js (47.993s)
  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders custom properties with server string render

    expect(received).toBe(expected) // Object.is equality

    Expected: "5"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      399 |         // This seems like an odd way computed properties are exposed in jsdom.
      400 |         // In a real browser we'd read it with e.style.getPropertyValue('--foo')
    > 401 |         expect(e.style.Foo).toBe('5');
          |                             ^
      402 |       });
      403 |
      404 |       itRenders('camel cased custom properties', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:401:29

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders custom properties with server stream render

    expect(received).toBe(expected) // Object.is equality

    Expected: "5"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      399 |         // This seems like an odd way computed properties are exposed in jsdom.
      400 |         // In a real browser we'd read it with e.style.getPropertyValue('--foo')
    > 401 |         expect(e.style.Foo).toBe('5');
          |                             ^
      402 |       });
      403 |
      404 |       itRenders('camel cased custom properties', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:401:29

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders custom properties with clean client render

    expect(received).toBe(expected) // Object.is equality

    Expected: "5"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      399 |         // This seems like an odd way computed properties are exposed in jsdom.
      400 |         // In a real browser we'd read it with e.style.getPropertyValue('--foo')
    > 401 |         expect(e.style.Foo).toBe('5');
          |                             ^
      402 |       });
      403 |
      404 |       itRenders('camel cased custom properties', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:401:29

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders custom properties with client render on top of good server markup

    expect(received).toBe(expected) // Object.is equality

    Expected: "5"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      399 |         // This seems like an odd way computed properties are exposed in jsdom.
      400 |         // In a real browser we'd read it with e.style.getPropertyValue('--foo')
    > 401 |         expect(e.style.Foo).toBe('5');
          |                             ^
      402 |       });
      403 |
      404 |       itRenders('camel cased custom properties', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:401:29

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders camel cased custom properties with server string render

    expect(received).toBe(expected) // Object.is equality

    Expected: "#000000"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      404 |       itRenders('camel cased custom properties', async render => {
      405 |         const e = await render(<div style={{'--someColor': '#000000'}} />);
    > 406 |         expect(e.style.SomeColor).toBe('#000000');
          |                                   ^
      407 |       });
      408 |
      409 |       itRenders('no undefined styles', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:406:35

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders camel cased custom properties with server stream render

    expect(received).toBe(expected) // Object.is equality

    Expected: "#000000"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      404 |       itRenders('camel cased custom properties', async render => {
      405 |         const e = await render(<div style={{'--someColor': '#000000'}} />);
    > 406 |         expect(e.style.SomeColor).toBe('#000000');
          |                                   ^
      407 |       });
      408 |
      409 |       itRenders('no undefined styles', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:406:35

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders camel cased custom properties with clean client render

    expect(received).toBe(expected) // Object.is equality

    Expected: "#000000"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      404 |       itRenders('camel cased custom properties', async render => {
      405 |         const e = await render(<div style={{'--someColor': '#000000'}} />);
    > 406 |         expect(e.style.SomeColor).toBe('#000000');
          |                                   ^
      407 |       });
      408 |
      409 |       itRenders('no undefined styles', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:406:35

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders camel cased custom properties with client render on top of good server markup

    expect(received).toBe(expected) // Object.is equality

    Expected: "#000000"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      404 |       itRenders('camel cased custom properties', async render => {
      405 |         const e = await render(<div style={{'--someColor': '#000000'}} />);
    > 406 |         expect(e.style.SomeColor).toBe('#000000');
          |                                   ^
      407 |       });
      408 |
      409 |       itRenders('no undefined styles', async render => {

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:406:35

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders unitless-number rules with prefixes with server string render

    expect(received).toBe(expected) // Object.is equality

    Expected: "10"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      449 |
      450 |         expect(style.lineClamp).toBe('10');
    > 451 |         expect(style.WebkitLineClamp).toBe('10');
          |                                       ^
      452 |         expect(style.MozFlexGrow).toBe('10');
      453 |         // jsdom is inconsistent in the style property name
      454 |         // it uses on the client and when processing server markup.

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:451:39

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders unitless-number rules with prefixes with server stream render

    expect(received).toBe(expected) // Object.is equality

    Expected: "10"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      449 |
      450 |         expect(style.lineClamp).toBe('10');
    > 451 |         expect(style.WebkitLineClamp).toBe('10');
          |                                       ^
      452 |         expect(style.MozFlexGrow).toBe('10');
      453 |         // jsdom is inconsistent in the style property name
      454 |         // it uses on the client and when processing server markup.

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:451:39

  ● ReactDOMServerIntegration › property to attribute mapping › inline styles › renders unitless-number rules with prefixes with client render on top of good server markup

    expect(received).toBe(expected) // Object.is equality

    Expected: "10"
    Received: undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      449 |
      450 |         expect(style.lineClamp).toBe('10');
    > 451 |         expect(style.WebkitLineClamp).toBe('10');
          |                                       ^
      452 |         expect(style.MozFlexGrow).toBe('10');
      453 |         // jsdom is inconsistent in the style property name
      454 |         // it uses on the client and when processing server markup.

      at packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js:451:39

Test Suites: 6 failed, 223 passed, 229 total
Tests:       19 failed, 26 skipped, 5017 passed, 5062 total
Snapshots:   85 passed, 85 total
Time:        149.925s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by threepointone** [comment]
Is this still an issue? we could never reproduce it locally. Closing this, happy to reopen if it's still a problem.
