### ISSUE TITLE
unexpected behavior with useState. when state is accessed from a callback function

### ISSUE THREAD

**Issue by thesimpledesigners** [facebook/react#16318]
**Do you want to request a feature or report a bug?**
Possible bug

**What is the current behavior?**
Im using a 3rd party jQuery plugin in combination with useState and useEffect hook to bind plugin events when component is mounted, this plugin calls a callback that update the component state, but callback is sort of closing on the initial state and with each call , values in state gets rest to their initial state

**Minimal Code Sample**
```javascript
function Example(props) {
    const start = moment();
    const end = moment().add(7, "days");
    const dateRangeRef = useRef(null);
    // component state
    const [state, setState] = useState({
        start_date: null,
        end_date: null,
        other_var1: 0,
        other_var2: 0
    });
    // date range picker handle
    useEffect(() => {
        // initiate daterange picker
        const daterange = $(dateRangeRef.current).daterangepicker({
            startDate: start,
            endDate: end
        });
        
        const callback = (ev, picker) => {
            /* BUG */
            // call to setState here will rest the other values in state to their initial state 
            setState({
                ...state, // state here is referring to initial state
                start_date: picker.startDate.format("YYYY-MM-DD"),
                end_date: picker.endDate.format("YYYY-MM-DD")
            });
        };
        daterange.on("apply.daterangepicker", callback);
    }, []);

    return (
        <div>
            <input ref={dateRangeRef} type="text" />
        </div>
    );
}
export default Example;
```

**What is the expected behavior?**
when callback is called start_date and end_date will be saved in state along other variables, but in this case other variables will be always reset I don't why such a behavior is happening

*Which versions of React?**

- **React Version** : 16.2.0 
- **Browser** : Chrome 
- **Os** : Linux Ubuntu

**Comment by thesimpledesigners** [comment]
**Update**
only possible solution i could found for this problem on my side is to isolate state values related to plugin in their own useState:

```javascript
function Example(props) {
    const start = moment();
    const end = moment().add(7, "days");
    const dateRangeRef = useRef(null);
    // component state
    const [state, setState] = useState({
        other_var1: 0,
        other_var2: 0
    });
    const [dateState, setDateState] = useState({
        start_date: null,
        end_date: null  
 });
    // date range picker handle
    useEffect(() => {
        // initiate daterange picker
        const daterange = $(dateRangeRef.current).daterangepicker({
            startDate: start,
            endDate: end
        });
        
        const callback = (ev, picker) => {
            setDateState({
                start_date: picker.startDate.format("YYYY-MM-DD"),
                end_date: picker.endDate.format("YYYY-MM-DD")
            });
        };
        daterange.on("apply.daterangepicker", callback);
    }, []);

    return (
        <div>
            <input ref={dateRangeRef} type="text" />
        </div>
    );
}
export default Example;
```

**Comment by nortonwong** [comment]
Yup, splitting state is what the React team recommends.

https://reactjs.org/docs/hooks-faq.html#should-i-use-one-or-many-state-variables

> If you miss automatic merging, you can write a custom useLegacyState Hook that merges object state updates. However, instead we recommend to split state into multiple state variables based on which values tend to change together.

https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function

> If you intentionally want to read the latest state from some asynchronous callback, you could keep it in a ref, mutate it, and read from it.

**Comment by aweary** [comment]
As @nortonwong said, using a `ref` is one solution. You can use a combination of `useState`, `useEffect`, and `useRef` to sync some state with a `ref`.

```js
const [state, setState] = useState({ /* ... */ });
const stateRef = useRef(state);

useEffect(() => {
  stateRef.current = state;
}, [state])
```

Then you can access `stateRef.current` in your callback to read the current state.

Another simpler way to solve this is to use an _updater function_. If you pass a function to `setState` React will call it with current state. Then you just return the next state.

```js
setState(state => ({
  ...state, // now state refers to the current state!
  start_date: picker.startDate.format("YYYY-MM-DD"),
  end_date: picker.endDate.format("YYYY-MM-DD")
}));

```

**Comment by thesimpledesigners** [comment]
Thank you @aweary  and @nortonwong
