### ISSUE TITLE
[test-renderer] Cannot read property `current` of undefined

### ISSUE THREAD

**Issue by FredyC** [facebook/react#16323]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

[![Edit pedantic-minsky-o5s5t](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-minsky-o5s5t?fontsize=14&module=%2Fsrc%2Fhook.test.js&previewwindow=tests)

**What is the expected behavior?**

The test shall pass :)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

    "react": "16.8.6",
    "react-test-renderer": "16.9.0-rc.0"

Same behavior for react-test-renderer 16.9.0-alpha.0, but works with 16.8.6.

cc @threepointone because stack trace ends up in `act`

**Comment by FredyC** [comment]
Duh, nevermind ... Only after posting this I realized that React version should probably match 😅

**Comment by jonnylynchy** [comment]
> Duh, nevermind ... Only after posting this I realized that React version should probably match 😅

This just saved me from being committed.

**Comment by alexandermckay** [comment]
@FredyC - Thank you!

**Comment by duddsA** [comment]
Thanks for what
