### ISSUE TITLE
React tests failing 

### ISSUE THREAD

**Issue by kambleaa007** [facebook/react#16329]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
TEST FAILING IN DEVLOPMENT ENVIRONMENT
yarn test Fails
where
yarn test-prod works
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Dubug stack trace

yarn debug-test --watch CSSPropertyOperations
yarn run v1.15.2
$ cross-env NODE_ENV=development node --inspect-brk node_modules/.bin/jest --config ./scripts/jest/config.source.js --runInBand --watch CSSPropertyOperations
Debugger listening on ws://127.0.0.1:9229/bd62a716-f841-4472-aa55-e0f9f7983fb6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
C:\Users\ashish.kamble\GIT\react\mainReact\react\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
Waiting for the debugger to disconnect...

**Comment by Dergash** [comment]
Hello @kambleaa007! You really should provide reproducible demo :) There are no way to help it without it.

From what I see I'd say that you have your quote signs mixed up:
```basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")```
You probably should wrap $0 in single quotas instead like that:
```basedir=$(dirname "$(echo '$0' | sed -e 's,\,/,g')")```

Either way, doesn't look like React involved somehow

**Comment by kambleaa007** [comment]
> Hello @kambleaa007! You really should provide reproducible demo :) There is no way to help you without it.
> 
> From what I see I'd guess that you have your quote signs mixed up:
> `basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")`
> You probably should wrap $0 in single quotas instead like that:
> `basedir=$(dirname "$(echo '$0' | sed -e 's,\,/,g')")`
> 
> Either way, doesn't look like React involved somehow
> 
> P.S. You can check [facebook/jest#3750](https://github.com/facebook/jest/issues/3750). It seems that you work on Windows but you are running test script builded for another OS; you should run `node_modules/.bin/jest.cmd` instead of `node_modules/.bin/jest`

Thanks
