### ISSUE TITLE
data-reactroot disappears using react-router-dom for SSR

### ISSUE THREAD

**Issue by BingjieGao** [facebook/react#16327]
I'm encountering a very strange behaviour which I was not expecting such bizarre issue when setting up a skeleton of react based SSR application. I'm wondering why this **["data-reactroot"]** attribute just automatically vanished once **react-router-dom** is applied on. Here is an example I made that has minimum impact of external libraries.

**Do you want to request a feature or report a bug?**
Bub, probably.

**What is the expected behavior?**
I'm sort of expecting attribute **["data-reactroot"]** is appended automatically and consistently.

Here is the codebase
client.js
```
import React from 'react'
import ReactDOM from 'react-dom'
import App from './App.js';
import Routes from "./Routes";
import { BrowserRouter as Router } from "react-router-dom"

const RouteCtx = (
  <Router>
      <Routes />
  </Router>
)
ReactDOM.hydrate(
  RouteCtx,
document.getElementById('root'));

```
client/Routes.js
```
import React from "react";
import Home from "./components/Home";
import Title from "./components/Title";
import { BrowserRouter as Router, Route } from "react-router-dom";


export default () => {
  return (
    <div>
      <Route exact path="/" component={Home} />
    </div>
  );

}

```

server/route.js
```
import React from "react";
import { StaticRouter } from "react-router-dom";
import Routes from "../client/Routes";
import { renderToString } from "react-dom/server";
import Home from "../client/components/Home"

export default (req) => {
    const content = renderToString(
      <StaticRouter location={req.path}>
        <Routes />
      </StaticRouter>
    )

    return `
      <html>
      <head></head>
      <body>
          <div id="root">${content}</div>
          <script src="bundle.js"></script>
      </body>
      
      </html>
    `;
}

```
_The final outcome on browser side for the generated DOM differentiated accordingly using different version of react:_

**Current behaviour with react v16.8.x**
```
<html>
  <head></head>
      <body>
          <div id="root">
            <div>
              <div>
                    <h1>Hello! This is shanghai Team</h1>
             </div>
            </div>
           </div>
       <script src="bundle.js"></script>
    </body>
</html>
```

**Behaviour with react v16.0.0**
With the same code base, the generated DOM is:
```
<html>
<head></head>
 <body>
     <div id="root">
            <div data-reactroot="">
                <div>
                    <h1>Hello! This is shanghai Team</h1>
                </div>
             </div>
     </div>
     <script src="bundle.js"></script>
  </body>
</html>
```
Which has the attribute **["data-reactroot"]** clearly.
Not sure if this is something should be expecting or should be something wrong.

**Comment by gaearon** [comment]
This is a bug. However, we can't fix it in cases where there isn't a single root element. I think that's likely happening here. Or maybe something like a context provider. Regardless, it doesn't matter if you call `hydrate()` for hydration. So it's okay and we won't fix.
