### ISSUE TITLE
use defaultProps when an attribute of an object is undefined?

### ISSUE THREAD

**Issue by kud** [facebook/react#16331]
**Do you want to request a *feature* or report a *bug*?**

Maybe a bug?

**What is the current behavior?**

https://codesandbox.io/s/green-snow-79z65

When you give `undefined` to a direct attribute, it will use the defaultProp.

When you give `undefined` to an attribute of an object, it'll use this `undefined`

**What is the expected behavior?**

I'm not sure but I'm waiting for using the defaultProp even for an attribute of an object?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react `16.9.0`

**Comment by Dergash** [comment]
Hello @kud! I don't think it's a bug. You do provide an object `{ attribute: undefined }` for your Components object property, so technically it isn't  undefined anymore, and in that case defaultProps aren't applied.

You probably just could write your own getDefaultObject(props) function with custom logic merging your default object and props.

**Comment by nortonwong** [comment]
Deep merging objects isn't really appropriate for a library to decide. If `object` had multiple mutually exclusive schemas, e.g. `object={{ foo: true }}` or `object={{ bar: 30 }}`, it would be wrong for the library to use a deep merging strategy.

**Comment by aweary** [comment]
Correct, React does not traverse objects when calculating props with `defaultProps`, so this is expected behavior.

**Comment by kud** [comment]
Understood! Thanks for your kind explanation!  :)

**Comment by kud** [comment]
I'm still on it, sorry. 

I've got a question.

Do you think so that using an object as props is finally a bad practice?

I wonder if I shouldn't make flat all my props now, to have the possibility to use "correctly" the defaultProps.

**Comment by Dergash** [comment]
I don't think it's a bad practice. It's easier for default values or for controlling when your component should rerender, that is for sure.
For me it's all about the use case:
* If I build a simple component, I will go for flat props:
```tsx
<Component x={10} y={y} /> // I prefer this
<Component dimensions={{ x: 10, y: 10 }} />
```
* If I have an entity that is part of my business model and is reused through my application as complex object, then I'll keep it as an object:
```tsx
<Widget meta={props.meta} />
```
* If I have a complex component that requires a lot of properties, then I'll go for nicer API and choose
```tsx
<Component
    parser={props.parser}
    printConfig={props.printConfig}
    filters={props.filters}
    pagination={props.pagination}
/>
```
instead of
```tsx
<Component
    parserProperty1={props.parser.property1}
     /* ... */
    paginationProperty99={props.pagination.property99}
/>
```

**Comment by kud** [comment]
I understand your point yes, thank you for this clear explanation.
