### ISSUE TITLE
componentWillMount deprectaion

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [facebook/react#16337]
I have seen that componentWillMount  is going to be deprectaed with React 17. However my state management slution hardly relays on it because during this call component is not still visible but i have access to props already so i can bind to appropriate store. 
There is not an option neither constructor neither componentDidMount because I have render errors already since dom tries to get values from store.

And only reason explanation i see in every blogpost i see - people are not using it wrongly with async rendering by fetching remote data in it. I think this is developes problem that he does not understand how it works...

Any suggestions how to solve this?

**Comment by Dergash** [comment]
Hello @vytautas-pranskunas-!

Could you please give a code example for a situation where neither constructor or componentDidMount are acceptable alternatives? I'm sure we could give you some insight how to untie it from componentWillMount.

**Comment by vytautas-pranskunas-** [comment]
Hi sure,
https://github.com/react-state/store/blob/master/projects/react-state/src/decorators/component-state.decorator.ts

Idea is that instead of writing long path to nested state i am pathing current path to child components letting them to build path incrementally. After i create store (actions) based on path and assign it to component

**Comment by aweary** [comment]
Hey @vytautas-pranskunas-! `componentWillMount` isn't being deprecated, it's being renamed to `UNSAFE_componentWillMount`. The [blog post for the 16.9 release](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html) covers this:

> The new names like `UNSAFE_componentWillMount` will keep working in both React 16.9 and in React 17.x. However, the new `UNSAFE_` prefix will help components with problematic patterns stand out during the code review and debugging sessions.

You can continue to use `UNSAFE_componentWillMount` for the forseable future, and the post [provides a codemod](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods) you can use to automatically rename the unsafe lifecycles when you upgrade.

```bash
cd your_project
npx react-codemod rename-unsafe-lifecycles
```

> There is not an option neither constructor neither componentDidMount because I have render errors already since dom tries to get values from store.

I'm not sure what you mean here. It sounds like you're trying to initialize some state for the component, so `constructor` should be work. We have [some more detailed guidance on migrating away from legacy lifecycles](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles) as well.

If you'd like some help figuring out a better approach I would recommend [using our community support resources](https://facebook.github.io/react/community/support.html), as we use this issue tracker for bug and feature requests only.

Thanks!

**Comment by vytautas-pranskunas-** [comment]
Constructor not ok because i do not have props yet. How do i know that
unsafe will not be deprecated? I love react that api is stable but now...

**Comment by aweary** [comment]
@vytautas-pranskunas- you do have access to `props` in the `constructor`

```js
class App extends React.Component {
  constructor(props) {
     super(props);
    // you can use `props` or `this.props` now
  }
}

**Comment by vytautas-pranskunas-** [comment]
Can you show me how to access it in decorator?

**Comment by vytautas-pranskunas-** [comment]
I was able to extend component constructor in decorator and moved all componentWillMount logic there with props. Just for other:
From decorator return new class:

```
return class extends target {
            constructor(...props) {
                super(...props);
                componentWillMount(this, props[0]);
            }
        } as typeof target;
```
