### ISSUE TITLE
Bug on style properties

### ISSUE THREAD

**Issue by maxguzenski** [facebook/react#16330]
**Do you want to request a *feature* or report a *bug*?**

BUG 

**What is the current behavior?**

Some style properties disappear, like background and zIndex

**What is the expected behavior?**

```
<div style={{position: 'fixed', top: 0, left: 0, bottom: 0, right: 0, background: '#fff', zIndex: 10}} />

output:
<div style='position: fixed; top: 0px; left: 0px; bottom: 0px; rigth: 0px;' />
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.9.0, Chrome. 
It works fine on 16.8.6

**Comment by Dergash** [comment]
Hello @maxguzenski!
Could you provide a reproducable example? I've tried your code both at sandbox with 16.9.0 (
https://codesandbox.io/s/relaxed-worker-xlhts) and in my local project and haven't experienced such issue.

**Comment by YavorskyiBohdan** [comment]
@maxguzenski I've just also tried it locally. Everything is fine

**Comment by Saibamen** [comment]
Works fine in React 16.9.0.

@maxguzenski: Please stop your server, delete your `node_modules` folder, `package-lock.json` file and `npm install` again and start `npm start` server again

![image](https://user-images.githubusercontent.com/905878/62779164-b4191b00-bab2-11e9-8db7-3ccb6878134a.png)

**Comment by maxguzenski** [comment]
Maybe this bug not happen on a very small sample app, but is happing on a very large one. I rollback to 16.8.6 and everything works fine. 

I'll try reproduce this issue on a sample app.

**Comment by maxguzenski** [comment]
> Works fine in React 16.9.0.
> 
> @maxguzenski: Please stop your server, delete your `node_modules` folder, `package-lock.json` file and `npm install` again and start `npm start` server again
> 

@Saibamen a fresh reinstall (delete node_modules) fix this issue.
