### ISSUE TITLE
react doesn't work on android kitkat 4.4.4 webview

### ISSUE THREAD

**Issue by maaqoul** [facebook/react#16335]
i made an application with react, it works fine in chrome but when i try to run it with a browser that has a kiosk option, i get "Uncaught ReferenceError: Map is not defined". 
i tried the solution provided in the documentation but still no success, so i made another application just for test and i got this error : "SyntaxError: Use of const in strict mode".

first project created with "react": "^16.8.6",
second project created with "react": "^16.9.0",

 device is Samsung Galaxy Tab E.

browser is kiosk browser lockdown : 
https://play.google.com/store/apps/details?id=com.procoit.kioskbrowser&hl=en

**Comment by jquense** [comment]
Sounds like it's missing some features that React requires. Make sure you have the right poly fills in place: https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by maaqoul** [comment]
i did the exact thing in that link but it doesn t work !

**Comment by OverTree** [comment]
@maaqoul try this

in index.js

```js
import 'core-js/es/map';
import 'core-js/es/set';
```

in config-overrides.js

```js
let { override } = require('customize-cra');
module.exports = override((config)=>{
    config.entry.reverse();
    return config
  }
);
```
