### ISSUE TITLE
Inconsistent whitespace behaviour between inline elements when using css animations

### ISSUE THREAD

**Issue by Faithfinder** [facebook/react#16339]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
 Here is the fiddle: https://jsfiddle.net/y3b52mcL/
When there is only one word in the animated span, after it leaves the screen some whitespace is left. When there are two words - no whitespace is there.

**What is the expected behavior?**
Consistent behaviour. As I understand, for React that would be second line in the fiddle (no whitespace).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest React. Tried in latest Firefox and Chrome, Win10. HAve no idea about previous versions.

**Comment by kunukn** [comment]
Can you make it work without using React? Using only HTML and CSS?
https://jsfiddle.net/apjgrnoq/4/

I believe this is a CSS fiddling issue.

**Comment by Faithfinder** [comment]
Hmm... Yeah, after I played around with it some more I can see that the behaviour without React is the same. Geez, you'd think it would be easy to get rid of a single pesky space.

Do you know where I should report it, if at all?

**Comment by nortonwong** [comment]
The browser behavior is fine. You just need to set a lower value, e.g. `-1em`, because `letter-spacing` affects each character uniformly.

You can see the difference by testing "WWWW" vs "iiii" in your fiddle.
