### ISSUE TITLE
Create React App builds empty document (blank screen) with react-router and firebase

### ISSUE THREAD

**Issue by rosanche** [facebook/react#16333]
I get a white screen on my deployed react webapp, it worked perfectly before. I tried everything I could find here but it didn t worked. 

Below is the link to my website : https://numbr-d1a20.firebaseapp.com/
And below the link to my git repo : github.com/rosanche/Numbr  I just took of the firebase.js file because I have my private config in it.

I tried everything,
Change the homepage, look for error in the console, clear my cache and a lot more...

Below is my package.json

```
{
      "name": "numbr",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "@material-ui/core": "^4.3.1",
        "express": "^4.17.1",
        "firebase": "^6.3.4",
        "mysql": "^2.17.1",
        "node-sass": "^4.12.0",
        "nodemon": "^1.19.1",
        "react": "^16.8.6",
        "react-dom": "^16.8.6",
        "react-native-indicators": "^0.13.0",
        "react-router-dom": "^5.0.1",
        "react-scripts": "3.0.1",
        "recompose": "^0.30.0"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
         "extends": "react-app"
      },
      "browserslist": {
        "production": [
          ">0.2%",
          "not dead",
          "not op_mini all"
        ],
        "development": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      }
}

```
I expect to see my sign in page and not a blank screen.

Thanks in advance for your help!

**Comment by Dergash** [comment]
Hello @rosanche! First, your github repository is missing a file required to launch your application. You are importing Firebase [here](https://github.com/rosanche/Numbr/blob/2540d0cfb1abce5e3472ecb4b892e097b8e43259/src/components/Firebase/index.js#L2): 
```jsx
import Firebase from './firebase';
```
[But there is no such file](https://github.com/rosanche/Numbr/tree/master/src/components/Firebase)

On your website you do have that file so I assume you just forget to commit it :)

The real problem though lies [here](https://github.com/rosanche/Numbr/blob/2540d0cfb1abce5e3472ecb4b892e097b8e43259/src/components/session/with-autorization.js#L32)

React is working like expected, it's just that your condition(authUser) returns fallse and therefore your wrapper returns null instead your real component
```tsx
<AuthUserContext.Consumer>
    {authUser =>
        condition(authUser) ? <Component {...this.props} /> : null
    }
</AuthUserContext.Consumer>
```

**Comment by ahtee** [comment]
also this issue could probably be opened in the github.com/facebook/create-react-app repo for proper review
