### ISSUE TITLE
Line numbers in component stack of `act` warning in 16.9

### ISSUE THREAD

**Issue by FredyC** [facebook/react#16348]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When `act` is missing in a test, the warning contains information about the component tree _(see image below; without stack trace)_, but in a test file which might include the same components several times over it does not help finding the culprit. 

Furthermore, the warning does not fail a test (not a problem) and as such it's shown at the end of test run output (at least in case of Jest) so there is no colocation with test having a problem.

**What is the expected behavior?**

We have used a somewhat ugly hack that allows us to see the full stack trace and the originating line of failure in actual test file is there, although buried rather deeply.

```js
Error.stackTraceLimit = Infinity
const origError = console.error
console.error = function(msg) {
    if (/react-wrap-tests-with-act/.test("" + msg)) throw new Error("missing act")
    return origError.apply(this, arguments)
}
```

I have tweaked it a bit in the following Sandbox and I am able to extract the exact location of a failure (notice the console output). It's slightly off due to lack of source maps, but in a proper environment, it's really helpful.

[![Edit patient-leftpad-houzz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/patient-leftpad-houzz?expanddevtools=1&fontsize=14&module=%2Fsrc%2Ferror.test.tsx&previewwindow=tests)

### Not to be confused, this is output AFTER my modification
**Currently, the output is without a stack trace**

![image](https://user-images.githubusercontent.com/1096340/62821857-daef5400-bb7b-11e9-8554-23a840a80184.png)

So I wonder why not include something like that in React?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Everything is 16.9

**Comment by gaearon** [comment]
Do you want to file an issue with Jest to ask to append stack traces to console.error calls? It sounds like that’s what you’re asking. I don’t know why React warnings should be treated specially. The problem seems universal to Jest.

**Comment by gaearon** [comment]
The issue title is a little confusing to me.

The text says you’re struggling with the determining the cause of the warning and that there’s no JS stack trace. That sounds like a Jest issue. 

But the title phrasing (“unhelpful warning persists”) sounds like you expected it to disappear. Or that it fires in a case where you don’t expect it.

Can you please clarify if there’s still anything *unexpected* here? Beyond Jest not showing a JS stack trace.

**Comment by FredyC** [comment]
Sorry for the confusion. Feel free to change the title that makes more sense to you...

By "unhelpful" I mean it doesn't help much with locating problematic test.

By "still persist" I mean that this hasn't changed since 16.8 and I got inspired by a subject of previous issue https://github.com/facebook/react/issues/14769.

Lastly, I don't think this a problem of Jest. The "act warning" is originating in React and it's logged with `console.error`. It's not a hard error and as such Jest cannot do anything about that.

**Comment by FredyC** [comment]
New day, new brains and I realized what CodeSandbox is showing is not accurate as the console output differs when running locally. Jest is showing the line number of `console.log` by default but in the case of "act warning" it points to React code as the origin of the `console.error` call.

![image](https://user-images.githubusercontent.com/1096340/62832677-8064ff00-bc32-11e9-9979-d41d4257da37.png)

Now what is really strange, when running a test through the CRA 3, the output is different and much more useful.

![image](https://user-images.githubusercontent.com/1096340/62832696-dfc30f00-bc32-11e9-99ef-1501091d793d.png)

This has obviously nothing to do with Jest as that output is produced by React. So it seems that CRA is doing some extra magic there?

**Comment by gaearon** [comment]
The component stack is more useful in CRA because it enables [this plugin](https://www.npmjs.com/package/@babel/plugin-transform-react-jsx-source) in development and tests. We recommend using it (just don't enable it in prod!) so that should solve your issue.

**Comment by FredyC** [comment]
@gaearon Well, I dare to say that's not very DX friendly. Since the warning is originating from React, it should be handled in React and not expect users to configure plugin if they don't use CRA. 

And it's not even documented anywhere. There should be some mention of it on that link http://fb.me/react-wrap-tests-with-act

**Comment by FredyC** [comment]
@gaearon Another example of how confusing it can be when there is no stack trace for that warning...

https://spectrum.chat/testing-library/help-react/act-warning~be946bdd-b2c4-4bf5-bf4d-e4a1f01d1914

I don't think it's fair to close this issue without giving it a second thought.
