### ISSUE TITLE
DOM is not updated after `render()`

### ISSUE THREAD

**Issue by catamphetamine** [facebook/react#16357]
React 16.8.6, also updated to 16.9.0 — same behavior.
Somewhere deep in the component tree there's a component that renders a `<button/>`.
On the first run it renders it with one `style`, on a subsequent second run it renders it with another `style`.
I placed a `console.log(style)` there and I can see that when the `style` property is updated the corresponding console line is there.
Still, the actual DOM node for the `<button style={style}/>` is not updated (I can see the previous `style` attribute in the Inspector).
It is updated only if I "kick" the component to re-render manually.
Can this even be possible?
If you have no ideas then I'll close this issue.

**Comment by threepointone** [comment]
It would be helpful to have a codesandbox or GitHub repo that reproduces this issue.

**Comment by catamphetamine** [comment]
Yeah, I thought so.
That's the reason it's easier to close the issue and call it a day than to provide a sample on codesandbox.
