### ISSUE TITLE
Listen to state change useReducer

### ISSUE THREAD

**Issue by totaland** [facebook/react#16361]
**Do you want to request a *feature* or report a *bug*?**
None. This is a question
**What is the current behavior?**
I try to create an object with the changed state value; however, the new object doesn't have the newest data. 

**This is the working version**
![image](https://user-images.githubusercontent.com/36496259/62849932-c7332180-bd24-11e9-94d5-16eb3a6cd672.png)
![image](https://user-images.githubusercontent.com/36496259/62850497-5ab92200-bd26-11e9-95df-52110538bb92.png)

**What is the expected behavior?**
so the basketDetails object if I assign the id: state2.basketId then this object will have the value id of "" instead of the newest value assign by the dispatch function. 
![image](https://user-images.githubusercontent.com/36496259/62850227-8b4c8c00-bd25-11e9-8871-b1be0745462c.png)
![image](https://user-images.githubusercontent.com/36496259/62850262-ac14e180-bd25-11e9-95c3-93c15b3b1370.png)
But the state print outside this function has the newest data:
![image](https://user-images.githubusercontent.com/36496259/62850340-ee3e2300-bd25-11e9-8972-ca04835eeb35.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.9.0

**Comment by kunukn** [comment]
I would guess it is because setting a state using `useReducer` is async.

I am guessing you use useReducer like this.
`const [state, dispatch] = React.useReducer(reducer, initialState)`

using `await dispatch` will not help. 

Have you tried this? The value should be "correct" here.

```jsx
React.useEffect( () => { 
  console.log(state)
}, [state] );
```

**Comment by totaland** [comment]
yes, I did use useReducer that way. Could you explain to me a bit more about the useEffect and what should I write inside that useEffect? I have the state call basketId.

**Comment by kunukn** [comment]
I can see the flaw in the code, but I am uncertain of what the code should be in your case. 
From given code I imagine we are interested in creating a basket object.

```jsx
const createBasket = async token => { /* Ajax side effects */ return newBasket } 
```

My question would be, do you need the `useReducer`?

Can we avoid the `useReducer` and simply use 
`basketDetails.id = id2`?

I `useReducer` is required maybe we can dispatch a basketCreated event with payload instead?

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
