### ISSUE TITLE
Type of ContextProvider value props from useReducer

### ISSUE THREAD

**Issue by moshe444** [facebook/react#16375]
I did a chunk of code to use `useContext` and `useReducer` to achieve the local state management. 

But some type errors poped up,

```javascript
(property) state: Group
Type '{ state: Group; dispatch: Dispatch<Action>; }' is not assignable to type 'Group'.
  Object literal may only specify known properties, and 'state' does not exist in type 'Group'.ts(2322)
index.d.ts(290, 9): The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & ProviderProps<Group>'
```

To make the type `Group` to `any` will fix the problem and working well, but I don't really want to do that.

Here's the code:

    interface People {
      name: string
      age: number
    }
    
    interface Group {
      a: People
      b: People
    }
    
    interface Action {
      type: string
      payload: number
    }
    
    // const myInitalState: Group = {
    const myInitalState: any = {
      a: {
        name: 'Max',
        age: 16
      },
      b: {
        name: 'Pom',
        age: 22
      }
    }
    
    const myReducer = (state: Group, {type, payload}: Action) => {
      switch (type) {
        case 'a_increase':
          return {...state, a: { ...state.a, age: payload + 1 }}
        case 'b_decrease':
          return {...state, b: { ...state.b, age: payload - 1 }}
        default:
          return state
      }
    }
    
    const MyContext = createContext(myInitalState)
    
    const [state, dispatch] = useReducer(myReducer, myInitalState)
    
    const Comp = () => (
      // this state will cause type error, change myInitialState type to any will fix it
      <MyContext.Provider value={{state, dispatch}}>
        <div>Group</div>
               .
               .
               .
      </MyContext.Provider>
    )

So what's going on here? What's the correct type of `<MyContext.Provider value={???}>`.

**Comment by gaearon** [comment]
Please file this with TypeScript.
