### ISSUE TITLE
Rehydrate multiple dom elements.

### ISSUE THREAD

**Issue by Pixelatex** [facebook/react#16378]
**Do you want to request a *feature* or report a *bug*?**
This might be a feature as it seems to not be possible.

**What is the current behavior?**

Note: This might seem very very weird to some people but this is necessary as we are using micro frontends so I am technically loading 20 react apps in one html page. Hence the need to rehydrate them with one script.

I get all elements by a certain data tag, this returns an array with dom elements and I loop over them and running hydrate on each one.

Now, this works... kind of.

The server returns `<div style="color:blue" data-reactroot="">test</div>` while the client will turn this into `<div>test</div>`, I'm only passing the color prop on the server for testing purposes.

React inspector shows all divs correctly as react elements with no props. But... the actual html output is different. Only the first div will have the updated html while all others after it will still have the color prop from the server render meaning that they weren't hydrated correctly.

onClick events and such do work though for all the divs so the event listeners are connected correctly.

**What is the expected behaviour?**

I would expect to be able to run hydrate on multiple dom elements without issue.

**Comment by threepointone** [comment]
Could you make a reproducing case on codesandbox, or in a git repo? Hard to comment without any code that shows this, thanks.

**Comment by threepointone** [comment]
I'm going to close this issue, but I'll be happy to reopen if you can provide a reproducing case, thank you!
