### ISSUE TITLE
export default react  import ... React.createElement: type is invalid -- expected a string

### ISSUE THREAD

**Issue by gaoxiaosong1113** [facebook/react#16386]
Here's the code address

```
https://codesandbox.io/s/fast-sky-6qxxp
```
I export all components of '''src/view''' in '''src/view''' in '''src/components''' and '''export default''' in '''src/components'''
Prompt the following error

![image](https://user-images.githubusercontent.com/16183057/62990009-d4fbba80-be7c-11e9-9cd5-e72d9a6f2f39.png)

**Comment by xx1124961758** [comment]
When importing a module exported using export default, you can't directly deconstruct it. You can define an object and then deconstruct it. This belongs to the module knowledge of es6。
![image](https://user-images.githubusercontent.com/13390985/62990875-235e8880-be80-11e9-85bc-d4b621722c8d.png)

**Comment by gaoxiaosong1113** [comment]
@xx1124961758 

Why not use es6 deconstruction in the following way
```
import { Nav } from "./components.js''
```

**Comment by kunukn** [comment]
Here is an example that should work
https://codesandbox.io/s/goofy-noyce-pscx5

The issue is not React related but usage of `import` and `export`

**Comment by gaoxiaosong1113** [comment]
@kunukn   thank you
