### ISSUE TITLE
React keeps rendering multiple times recklessly

### ISSUE THREAD

**Issue by Hypothesis-github** [facebook/react#16395]
This code is supposed to trigger the listening even on the mouse and it does but 

React is ABSOLUTELY oblivious to  `[state.loading]` which is passed through useContext and it has forced me to use `useState` with `isFetching` which is totally ridiculous. 

I mean if useEffect is not gonna take parameters from a global state designed by react why was it even released in the first place ?

```
    const { state, dispatch } = React.useContext(SomeContext)
    const [isFetching, setIsFetching] = useState(false);
    useEffect(() => {
        getAscii(1, Config.ADS_PER_ROW, dispatch, state.sortBy, false)
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);




      function handleScroll() {
        // if (window.innerHeight + document.documentElement.scrollTop !== document.documentElement.offsetHeight || isFetching) return;
        if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight && state.loading == true || isFetching)
            setIsFetching(true);
    }

    useEffect(() => {
        if (!isFetching) return;
        fetchMoreListItems();
    }, [isFetching]);



    const fetchMoreListItems = () => {
        getAscii(state.page, Config.ADS_PER_ROW, dispatch, state.sortBy, false)
        setTimeout(() => {
            setIsFetching(false);
        }, 2222);
    }
```

on top of all that, the code in return which supposed to refresh the screen and add more data runs so many times I get browser crash at times and no throttling has worked as of now.

I am in despair.

**Comment by jquense** [comment]
Your useEffect hook is wrong, it's closing over handles roll only the first render because of the `[]` dependency array. You may want to use the eslint plguin which would have warned about the problem There are also a lot of past issues with similar examples  that cover ways that the above can be refactored, which are worth taking a look at

**Comment by gaearon** [comment]
@Hypothesis-github 

This might help:

https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies

The ESLint rule (`eslint-plugin-react-hooks/exhaustive-dependencies`) would have caught this. It comes by default with Create React App.

As an aside, please try to use less emotionally charged tone. We're trying to help.
