### ISSUE TITLE
please give the useReducer a built-in combineReducer function

### ISSUE THREAD

**Issue by ainuo5213** [facebook/react#16399]
There is a problem when I use much more than one reducer, so will you please add a combineReducer function to useReducer like redux？
I‘ll appreciate it if you could do that

**Comment by kunukn** [comment]
It is possible to combine `useReducer` and `combineReducers` from Redux.

A quick demo.
https://codesandbox.io/s/usereducer-and-combinereducers-0em7l

**Comment by gaearon** [comment]
You can write it manually.

```js
function reducer(state, action) {
  return {
    a: a(state.a, action),
    b: b(state.b, action),
  }
}

function a(state, action) { }
function b(state, action) { }
```

Or `useReducer` twice.
