### ISSUE TITLE
Thoughts on making react/lib/keyMirror an NPM module

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#1639]
I'm finding I really love something like `keyMirror` on non-react related fluxy projects. Is there a good NPM module for this, or considerations of making it a separate module?

**Comment by raminbp** [comment]
@spicyj i didn't got it, can you explain it more ? what the whole point of the keymirror ?

**Comment by gaearon** [comment]
>i didn't got it, can you explain it more ? what's the whole point of the keymirror ?

Google Closure Compiler has an [advanced mode](https://developers.google.com/closure/compiler/docs/api-tutorial3). It's more powerful than UglifyJS and will compress your code like crazy. In advanced mode, any property names you define will be “crushed” (unless you're defining them as strings).

When you have code like

```js
var Stuff = {
  GOOD_STUFF: 'GOOD_STUFF'
};
```

Closure Compiler in advanced mode will compress it to

```js
var a = {
  b: 'GOOD_STUFF'
};
```

which will break your code.

There are two options:

1. Use string property name to opt out of crushing

```js
var a = {
  'GOOD_STUFF': 'GOOD_STUFF'
};
```

This works, but you miss out on a nice optimization opportunity.

2. Use a helper that makes sure keys and values match

That's what `keyMirror` does.

**Comment by zpao** [comment]
Random usage of `fbjs` isn't really supported but we moved `keyMirror` out of React to there (`require('fbjs/lib/keyMirror')`. Closing out.

**Comment by israelito3000** [comment]
Hello, probably this sound redundant, I am using react by the bower package and I am trying to use keyMirror which is inside React.js, but this is not exposed as a global object, how can I use it without import another keyMirror package?

**Comment by spicyj** [comment]
You can't.

**Comment by codejamninja** [comment]
Wouldn't it be easier to use key mirror the following way

```js
keyMirror(['monkey', 'gorilla']);
```

Instead of

```js
keyMirror({monkey: null, gorilla: null});
```

**Comment by sophiebits** [comment]
See my comment on June 5 for the answer to your question.

keyMirror isn't and has never been a supported API of React. I'm going to lock this conversation to reduce noise.
