### ISSUE TITLE
textarea with `required` attribute renders in invalid state in FF

### ISSUE THREAD

**Issue by dlaub3** [facebook/react#16402]
*Bug*

When a `textarea` has the `required` attribute it renders in the invalid state using FireFox. 

This behavior is visible here: https://codesandbox.io/s/rough-frog-f00ow. Remember to view it in FireFox.  

I expect the required field to validate on form submit and not before. 

I have tested this with FireFox 68 and 69 and React 16.8.6

This appears appears to be a re-occurrence of: https://github.com/facebook/react/issues/8395

**Comment by matjack1** [comment]
I'm experiencing this as well
