### ISSUE TITLE
React DevTools tutorial instructions are hard to read

### ISSUE THREAD

**Issue by brotzky** [facebook/react#16410]
**What is the current behavior?**
https://react-devtools-tutorial.now.sh/

The text on the left is difficult to read because of thin font styling
<img width="461" alt="Screen Shot 2019-08-15 at 3 32 36 pm" src="https://user-images.githubusercontent.com/8007686/63131305-0e622200-bf72-11e9-867a-e94551a1c422.png">
<img width="467" alt="Screen Shot 2019-08-15 at 3 35 42 pm" src="https://user-images.githubusercontent.com/8007686/63131388-5da85280-bf72-11e9-9d11-401600713bed.png">

**What is the expected behavior?**
Increase the contrast on the top row buttons and increase the font-weight for the text

font-weight: 300 or 400 makes it easier to read
(300 pictured)

<img width="467" alt="Screen Shot 2019-08-15 at 3 35 42 pm" src="https://user-images.githubusercontent.com/8007686/63131491-c099e980-bf72-11e9-9195-2ee571f384f8.png">

Running Catalina latest, macOS.

**Comment by bvaughn** [comment]
I liked the lighter font weight 😄 but I don't feel strongly enough to argue about it. I've removed the "lighter" weight attribute and re-deployed the tutorial site.

**Comment by brotzky** [comment]
I only brought it up because I genuinely had a hard time reading it. I don't want to fuss about any visual styles but in this case it was so light I thought maybe it was a bug.
Or maybe I'm just getting old... 😂😂

Anyway, really appreciate the tutorial and all your work on React DevTools and the bump in font-weight!

**Comment by bvaughn** [comment]
No worries! I'm glad you brought it up :) If you had trouble reading it I'm sure others did as well.

**Comment by gaearon** [comment]
Luckily it didn’t look as light on my screen as on that screenshot — the screenshot looks barely readable to me too. I’m glad this is fixed, thank you!

**Comment by bvaughn** [comment]
Yeah, didn't look nearly so light on my screen either. I assume it was using a different font.
