### ISSUE TITLE
is that possible to get legacy version of react debugger?

### ISSUE THREAD

**Issue by augustblizzard** [facebook/react#16418]
bug: highlight element is no available in ver 4+ react debugger
feature: new version of react develop is good, bug sometimes i need legacy version of develop tool(i jest need BOTH of them), can you provide both of them?

**Comment by augustblizzard** [comment]
BTW, ver 4+ react develop tool dose't support element highlight in react ver 0.14

**Comment by mrmckeb** [comment]
I am also a little confused about this, @bvaughn - is there another way to get this? I found it was a great way to demonstrate how components were rendering.

**Comment by yaskor** [comment]
No highlight updates anymore? That was very usefull - please add it back

**Comment by Sultanidze** [comment]
Components view was more informative in v3 (classNames, values ...). Please add settings to fix this

**Comment by bvaughn** [comment]
> is that possible to get legacy version of react debugger?

Yes, as mentioned in the blog post:
https://reactjs.org/blog/2019/08/15/new-react-devtools.html#how-do-i-get-the-old-version-back

Unfortunately it requires building from source as the Chrome and Firefox stores don't provide a way to install an older version of the extension.

```sh
# Checkout the extension source
git clone https://github.com/facebook/react-devtools

cd react-devtools

# Install dependencies and build the unpacked extension
yarn install
yarn build:extension

# Follow the on-screen instructions to complete installation
```

**Comment by bvaughn** [comment]
> I am also a little confused about this, @bvaughn - is there another way to get "highlight updates" in the new devtools? I found it was a great way to demonstrate how components were rendering.

@mrmckeb I think that the Profiler is generally a better way of measuring this. We may re-add the highlight updates feature in the future though if there's negative feedback about it being removed though. 😄 

> By the way, they're amazing overall - and look beautiful. Well done!

Thanks!

**Comment by bvaughn** [comment]
> Components view was more informative in v3 (classNames, values ...). Please add settings to fix this

@Sultanidze This is a big part of what makes the new DevTools **much faster** than the old DevTools. (It also helps make larger applications easier to navigate.)

If you're interested in some more background info for why it's built this way:
https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md

**Comment by yaskor** [comment]
> helps make larger applications easier to navigate

...but for small applications it was a fast and easy way to debug/see whats going wrong

Its realy funny because "higlight updates" was in reality the only thing I haved used in dev-tools - the other stuff was way to "much/complicated" for my small webapps :-(

**Comment by gaearon** [comment]
I hear you! See my comment here: https://www.reddit.com/r/reactjs/comments/cqx554/introducing_the_new_react_devtools/ex1r9nb/

We might bring it back in some form — but the way it was implemented, it caused people to obsess over inconsequential updates and miss actual performance issues. So we really recommend that you give Profiler a try. In the meantime we’ll think about how to bring back this feature in a more meaningful form.
