### ISSUE TITLE
Updating a parent component during child unmount

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#1641]
We have some code that looks something like this:

http://jsbin.com/xipeduxu/1/edit

The root component shows which of a changing list of items is currently being hovered. Note that if you mouse over the last component and it disappears, your selection is "stuck" with that component and doesn't reset to null. If you uncomment the line in componentWillUnmount then we attempt to tell the parent to unset the active property, but it then throws an error when unmounting the active item because the parent is currently in the middle of reconciling its children which is not currently a place we allow state updates.

It seems like maybe the best solution is to have the parent be smarter and realize when it's removing the active child and have it unset the `active` state property, though I don't see a super clean way to do so. Right now `tick` doesn't need to know anything about what makes an item active or not—it seems nicer to keep it that way if possible.

@sebmarkbage Do you have thoughts here?

cc @zgotsch

**Comment by gaearon** [comment]
Closing as stale.

Practically, this solution would make the most sense to me:

>It seems like maybe the best solution is to have the parent be smarter and realize when it's removing the active child and have it unset the active state property

One would either update both `num` and `active` together, or treat `active` as a “recommendation” during rendering, and derive the actual active item from both `active` and `num`.
