### ISSUE TITLE
React Router + Lazy + Suspense (CSS not loaded correctly on IE11)

### ISSUE THREAD

**Issue by helabenkhalfallah** [facebook/react#16420]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
I use react-router with *lazy* and *suspense* to lazy load routes and chunck my bundle (large application).

_Chrome :_
Everything work perfect : css loaded, good display and bundle chunks.

_IE 11:_
I get a bad display : wrong css margin, dimensions, sizes, colors, css vars not loaded...
I get my bundle chuncks.
If I refresh the page (or F5) I get the correct display.
If I remove *lazy* I have the correct display.

```javascript
const MyPage = (
  lazy(() => (
        import('./path/MyPage')
  ))
);

<Router>
      <Suspense fallback={<div />}>
        <Switch>
          <Route path="./my-page" component={MyPage} />
        </Switch>
      </Suspense>
</Router>
```

**What is the expected behavior?**
Same result on IE and Chrome.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Browser affected: IE11.
React version : 16.8.6
React Router Dom : 5.0.1.

Thanks.

**Comment by nortonwong** [comment]
IE11 does not support CSS variables.

**Comment by helabenkhalfallah** [comment]
When I do refresh or F5 I got the correct display, I use css-vars-ponyfill for css var. This is not due to css var but to lazy. If I remove lazy I got everything correct as I described on my issue.

**Comment by helabenkhalfallah** [comment]
Any help ?

**Comment by threepointone** [comment]
Without a reproducing example on codesandbox, or as a git repo with more information, it's hard to comment or help any further. Please provide more details and code.

**Comment by helabenkhalfallah** [comment]
Hello, I found the solution, isn't related to Lazy and Suspense it's related to my website structure and css-var-ponyfill. 
https://github.com/jhildenbiddle/css-vars-ponyfill/issues/89
Thank you so much for your help :)
