### ISSUE TITLE
React Dev tools does not show up in browser with new update.

### ISSUE THREAD

**Issue by skywalkerwin** [facebook/react#16429]
Was working 2 days ago, now does not work. I'm assuming something happened with new update. 

Chrome version 76.0.3809.100
React Developer Tools version 4.0.2 (8/15/2019)
-Settings
Site access onclick
Allow access to file URLs

**Comment by GreenGremlin** [comment]
I'm seeing the same thing, also on Chrome 76.0.3809.100 and React Dev Tools 4.0.2. After upgrading react dev tools was there, but said it couldn't find react. I restarted Chrome and it disappeared from the dev tools.

**Comment by GreenGremlin** [comment]
Just after posting that, I closed dev tools and re-opened them and it's working now.

**Comment by gaearon** [comment]
https://reactjs.org/blog/2019/08/15/new-react-devtools.html

The tab is now called "⚛️ Components". Maybe you're still looking for the "React" tab?

**Comment by skywalkerwin** [comment]
Ive restarted chrome and restarted react dev tools, and still dont see anything that resembles a react components tab.

**Comment by skywalkerwin** [comment]
Got it thanks!
