### ISSUE TITLE
react dev tools: re-enable "store as global variable"

### ISSUE THREAD

**Issue by atk** [facebook/react#16428]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

Right clicking props in the component view of the dev tools no longer brings up a context menu containing the option "store as global variable" (which previously stored the selected prop into `$tmp`. 

**What is the expected behavior?**

Right clicking the props should bring up the aforementioned option.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

DevTools version 4.0.2-2bcc6c6 in Chrome 76.0.3809.100 on Xubuntu Linux 19.04 (Disco Dingo). The DevTools version 3 still had this feature.

**Comment by bvaughn** [comment]
This functionality is still supported, just not via the context menu mechanism. :smile:

![store-Kapture 2019-08-16 at 13 19 57](https://user-images.githubusercontent.com/29597/63195846-9276e100-c028-11e9-9034-661ba8d6f285.gif)

**Comment by atk** [comment]
Thanks for the help!

**Comment by Wgil** [comment]
@bvaughn Hi,

Is there any way to access to this variable from your source code directly? It would be amazing if I could send this component tree to an error reporting library

**Comment by bvaughn** [comment]
The value is stored on the `window`, so anything can access it. However there is no API for JavaScript code to talk to DevTools to ask it to store the value, so you wouldn't be able to build a reporting library on top of it.
