### ISSUE TITLE
New Devtools Cannot Expand Obervables

### ISSUE THREAD

**Issue by robskidmore** [facebook/react#16430]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Devtools used to be able to expand observables created by Mobx. With the new update that is no longer possible.
![image](https://user-images.githubusercontent.com/3083189/63194767-18495b00-c02e-11e9-95d2-1c83edbf2f26.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/embed/clever-blackwell-h0nzb

Check the props of the wrappedComponent in devtools. store.things does not expand.

**What is the expected behavior?**
Devtools should expand Observables as it does any other object.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This only seems to be an issue with Observables created by Mob v4. v5 works as expected.

**Comment by bvaughn** [comment]
Let's roll this into #16424 😄

**Comment by bvaughn** [comment]
v4.0.3 has just been released with this fix.

Full changelog: https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#403-august-17-2019
