### ISSUE TITLE
New React Developer Tools does not clearly indicate empty object or array

### ISSUE THREAD

**Issue by taniarascia** [facebook/react#16431]
**Do you want to request a *feature* or report a *bug*?**

Bug/unexpected behavior.

**What is the current behavior?**

When an object or array is empty, there's no arrow to expand and see that it's empty, nor is there an `(empty)` indication. Initially, I was concerned that I couldn't expand any object or array from the new React DevTools due to this.

![Screen Shot 2019-08-16 at 3 11 35 PM](https://user-images.githubusercontent.com/11951801/63195539-7aa75900-c038-11e9-95fe-4754f7d14693.png)

**What is the expected behavior?**

I would expect to either be able to expand the empty object, or to see `(empty)` next to the non-expandable object.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Chrome version: 76.0.3809.100 (Official Build) (64-bit)
React Developer Tools Version: 4.0.2 (8/15/2019)

[Reference discussion on Twitter](https://twitter.com/taniarascia/status/1162441422496325633)

**Comment by bvaughn** [comment]
> When an object or array is empty, there's no arrow to expand and see that it's empty

The lack of an arrow to expand was meant to _indicate that it's empty_ 😁 This mimics the browser's Elements panel for HTML elements that don't have children.

I'll give it another pass and see if some explicit "empty" label or styling seems better.

**Comment by bvaughn** [comment]
Fixed in https://github.com/bvaughn/react-devtools-experimental/commit/69b2ecc531f24f6e0e0dbbb26844b060d581926b

![Screen Shot 2019-08-16 at 1 43 04 PM](https://user-images.githubusercontent.com/29597/63197320-4ded4480-c02c-11e9-9ad7-8d0f58e6831f.png)

Will release in v4.0.3 sometime this afternoon.

**Comment by gaearon** [comment]
>This mimics the browser's Elements panel for HTML elements that don't have children.

Kind of a meta comment — but we should probably align object display with how DevTools displays JavaScript objects in the console. Rather than with Elements.

Even slight mismatches with object display can be jarring because the muscle memory is so strong.

**Comment by bvaughn** [comment]
v4.0.3 has just been released with this fix.

Full changelog: https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#403-august-17-2019
