### ISSUE TITLE
White-space between inline elements

### ISSUE THREAD

**Issue by bstst** [facebook/react#1643]
Shouldn't there be a white-space between inline DOM elements separated by a line break [1]?

I think this example describes the situation pretty well: http://jsfiddle.net/bstst/kb3gN/2847/

Right now the workarounds are pretty ugly -- either CSS (don't get me started!) or manual white-space inside the inline elements (as in `<span>foobar </span>`), both of which are quite non-semantic.

Hope it's not a duplicate of an earlier issue -- I did my research!
Cheers!
M.

[1] http://www.w3.org/TR/html401/appendix/notes.html#notes-line-breaks

**Comment by dhruvbalhara** [comment]
@syranide - Any hints on how I can add spaces before these divs, given that I am generating the child elements through a loop whose length is not fixed.  https://jsfiddle.net/rqrvywfz/2/

**Comment by syranide** [comment]
@dhruvbalhara Just push the string `" "` to the array your generating where you want spaces to be? Or am I misunderstanding you?

**Comment by dhruvbalhara** [comment]
@syranide  - Ah, right. Sorry. I completely missed that. Sorry for this dumb question.

**Comment by ivan-kleshnin** [comment]
HTML and CSS have a notion of inline and block elements. Whitespace between inline elements is significant and shouldn't really be touched in any way. The situtation is complicated by the fact you can change which elements are inline and which are block in CSS.

Still the most correct way would be to refer to the list of default inline and block elements as those are rarely swapped in practice. And never strip whitespace between inline and text elements.

**Comment by jordanbtucker** [comment]
Here's a way to add the space with CSS:

```css
.alias::before,
.city::before {
  content: ' ';
}
```

**Comment by ivan-kleshnin** [comment]
@jordanbtucker if you are at CSS level you should just use horizontal margins. Before and After bear a lot of problems and should be reserved for *emergency* cases.

**Comment by AGMETEOR** [comment]
https://www.npmjs.com/package/react-add-space

**Comment by micha3lb3n** [comment]
```
const WhiteSpace = (count) => {
    let space = "";
    for (var i = 0; i < count; i++) space += " ";
    return space;
  };

return (
   <div>{WhiteSpace(10)}</div>
)
```
The above code will generate 10 whitespaces!

P.S. I know I am late but I think people would benefit looking at this!😅

**Comment by roydukkey** [comment]
> @jordanbtucker if you are at CSS level you should just use horizontal margins. Before and After bear a lot of problems and should be reserved for _emergency_ cases.
> 
> Update: people downvoting this comment apparently have no experience with Markup. Ok, lol.

Margins collapse differently that whitespace. I think that is the reason for downvotes.

**Comment by Paalon** [comment]
The blog page is now here:
https://legacy.reactjs.org/blog/2014/02/20/react-v0.9.html#jsx-whitespace
