### ISSUE TITLE
Implicitly access parent props via context

### ISSUE THREAD

**Issue by esr360** [facebook/react#16449]
I would like to request a feature for consideration.

Typically when we want information in a descendant component we must explicitly pass the data down via props (prop drilling). The context API allows us to avoid doing this if we create, import and maintain our own context object wherever we need it.

Inside a functional component using the latest context API with hooks, this may look something like:

```jsx
import React, { useContext } from 'react';
import myContext from '../myContext';

 const MyComp = (props) => { 
  const context = useContext(myContext);

  return(
    <div>
      ...
    </div>
   );
}
```

([source](https://stackoverflow.com/a/55848811/2253888)). If I'm not mistaken, the legacy context API exposed `context` as a second argument to functional components. For all intents and purposes, context is an opt-in feature (meaning there is no default/out-the-box `context` object exposed). 

I feel as though there would be good benefit in exposing a default context object which exposes information about ancestral components (essentially exposing the parent tree). After all, such information would qualify for the regular definition of "context".

Consider the below JSX:

```jsx
const Alpha = (props) = (
  <Beta fizz='buzz'>
    <Gamma isActive>
      <Delta />
    </Gamma>
    <Gamma>
      <Delta />
    </Gamma>
  </Beta>
);
```

Consider the `<Delta>` component - we want access to the parent `isActive` prop on the `Gamma` component and the `fizz` prop on the `Beta` component. The typical recommendation is to explicitly pass props to components that need the values. In the above case, it would be more convenient to access them implicitly.

A scenario where I were able to do this would be wonderful:

```jsx
const Delta = (props, context) => {
  console.log(context.Beta.fizz); // => 'buzz'

  return (
    <div style={context.Gamma.isActive ? 'block' : 'none'}>
      Lorem ipsum
    </div>
  )
}
```

Thus, essentially exposing parent props. Currently if I want similar behaviour I need to [create wrapper components](https://levelup.gitconnected.com/lifting-props-up-f1be43a1d7a4) (or I have to explicitly create, export and import various context objects).

Does anyone else feel as though something like this would be useful? Or does it offer too much potential for abuse? For "context", this would probably mostly help with things like styling, where it's often more convenient to work in this manner. Thanks!

**Comment by threepointone** [comment]
We've moved away from using strings as keys on context since it caused too many bugs (for example, in your code, any other component named Gamma written by someone on another team, would break your expectations. React guarantees safety with the newer api, even if it means typing a few more characters. That said, using hooks to encapsulate this code is a good way to oraganize and make sense of it. 

Closing this issue, thanks for the suggestion.
