### ISSUE TITLE
Custom theme in React DevTools v4

### ISSUE THREAD

**Issue by Stamo-Gochev** [facebook/react#16452]
**Do you want to request a *feature* or report a *bug*?**
A missing feature in React DevTools v4.

**What is the current behavior?**
There isn't a menu for using a custom theme. 

Compare the old version:
![custom-theme](https://user-images.githubusercontent.com/1857705/63256409-2f7f8700-c280-11e9-941d-98079eb95454.png)

With the new one:
![image](https://user-images.githubusercontent.com/1857705/63256498-5e95f880-c280-11e9-9bf5-65c4cc98ca48.png)

I cannot find an option to customize the theme in any of the new sections.

**What is the expected behavior?**
A way to customize the theme colors (e.g. similar to the previous version).

**Which versions of React Dev Tools are you using?**
v4

**Comment by bvaughn** [comment]
This feature was intentionally left out of version 4 :smile: Creating and maintaining high quality themes can require significant effort. It didn't seem like the right priority to focus on when compared to performance or debugging tools.

A trade off for this is that the two built-in v4 themes are much richer than the ones v3 provided. Compare the color palette from the [v4 light theme](https://github.com/bvaughn/react-devtools-experimental/blob/d2456c75720463eccbf714380adfd050cf804241/src/devtools/views/root.css#L6-L70) (63 colors) to the [v4 default theme](https://github.com/facebook/react-devtools/blob/d839081f79f681617df7584a8ffd2f4163fa40b9/frontend/Themes/Themes.js#L160-L184) (21 colors).

I'm going to close this issue because I don't think we plan to take any action on it in the foreseeable future. We can continue to discuss it here though if there's follow up.

**Comment by Stamo-Gochev** [comment]
@bvaughn The original question was more about a way to add my custom theme rather than having all the old themes available - actually, I don't need them. I have used the previous "Custom" option from the menu and created my own theme, but I want to "port" it to the new version of dev tools. As the styling will be done by the developer, is having a "Custom" option in the menu and an input for pasting the style a big effort?

**Comment by bvaughn** [comment]
Sorry if my reply was too vague. There is no way to import a custom theme in v4, and even if there were, v3 and v4 "themes" would be incompatible. (See the links above to the example styles.)

**Comment by Stamo-Gochev** [comment]
Yes, I understand that, I don't want to import the custom theme from v3, but rather create a new one (that is similar in appearance to the one from v3) and import the new styles to v4.

**Comment by gaearon** [comment]
There is no _ability to import_ itself. It's static now, with two predetermined themes. Your best bet would be to fork DevTools and override the linked constants.

**Comment by gaearon** [comment]
I guess maybe there's some way to force custom user styling for DevTools. If you can find a way to override `:root` CSS variables linked above, maybe that can work for you.

**Comment by Stamo-Gochev** [comment]
@gaearon Yes, these are the 2 alternatives I can think of as well. I thought that custom styling was a commonly used feature and thus looked for it in the new version, but you guys should know better - there is no need to invest any resources, if this isn't that common. I will try the alternative approaches.

**Comment by gaearon** [comment]
I think maybe we could in theory offer a low-cost way of injecting arbitrary styles into the `:root` so that people who really care can still do it.

**Comment by Stamo-Gochev** [comment]
That will be nice and will also allow open-source contributors to create their own custom themes and share them. Some might also "port" versions of the themes from v3.

**Comment by bvaughn** [comment]
> I think maybe we could in theory offer a low-cost way of injecting arbitrary styles into the :root so that people who really care can still do it.

I'm reluctant to do even this, because I don't want to consider style changes (new colors, change of which style uses which var) as "breaking" changes for future releases.

**Comment by gaearon** [comment]
>I'm reluctant to do even this, because I don't want to consider style changes (new colors, change of which style uses which var) as "breaking" changes for future releases.

I meant that this could be an advanced feature with expectation that it can break with any patch.

**Comment by bvaughn** [comment]
Fair enough I guess. I'm just reluctant to provide any UI that might indicate this is encouraged or supported (in that we won't break it without notice in future minor releases).

Vaguely related- our current use of `:root` styles are a bit problematic for the embedded case like Code Sandbox (#16456).

**Comment by Stamo-Gochev** [comment]
> 
> 
> > I'm reluctant to do even this, because I don't want to consider style changes (new colors, change of which style uses which var) as "breaking" changes for future releases.
> 
> I meant that this could be an advanced feature with expectation that it can break with any patch.
I agree with that, this should move the responsibility for keeping the themes working to the open-source contributors. Having this as an "advanced/experimental feature" will signal that it is up to you to make it work.

I also agree with @bvaughn - having this in the UI might cause some problems. In this case, what do you think about a checkbox or a section about "Experimental features" - this will make it very clear that these things can break any time.
