### ISSUE TITLE
React DevTools Chrome Browser Extension Option Select Boxes are broken

### ISSUE THREAD

**Issue by GeorgeWL** [facebook/react#16451]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The select dropdowns don't function correctly, and are currently unreadable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

![settings broken](https://user-images.githubusercontent.com/5931248/63256241-102c2e00-c26f-11e9-96bc-ebcab5bb319c.gif)

**What is the expected behavior?**
Select dropdown options are readable and able to be set correctly

**Which versions of React DevTools, and which browser / OS are affected by this issue? Did this work in previous versions of React DevTools?**

App Name | Version 
-- | --
Google Chrome | 76.0.3809.100 (Official Build) (64-bit) (cohort: Stable) 
React DevTools |  4.0.4-3c6a219
OS | Windows 10 OS Version 1809 (Build 17763.678)
JavaScript | V8 7.6.303.29

**Comment by Eddie-CooRo** [comment]
Hey there,
Would you mind telling me which browser you are using? (and which version)

**Comment by GeorgeWL** [comment]
it's at the bottom of the issue, in a table

**Comment by bvaughn** [comment]
I don't understand this one. I'm not using a custom select or anything. There's no CSS styles that should impact `select` or `option` in the repo.

Could this be caused by some other browser plugin or customization you have applied?

**Comment by GeorgeWL** [comment]
> I don't understand this one. I'm not using a custom select or anything. There's no CSS styles that should impact `select` or `option` in the repo.
> 
> Could this be caused by some other browser plugin or customization you have applied?

I'll try it out in incognito with all other extensions disabled, then report back.

**Comment by GeorgeWL** [comment]
all other extensions disabled. Display becomes fine.

So one of the extensions has been silly and set the css globally somewhere...very naughty.

**Comment by bvaughn** [comment]
Interesting! Thanks so much for the follow up, @GeorgeWL 🙇
