### ISSUE TITLE
Browser plugin crashing my browser when opening devtools

### ISSUE THREAD

**Issue by scrossan-crown** [facebook/react#16450]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?** 
When I open devtools with the React chrome extension enabled my browser crashes (all windows exit). If I disable the extension it devtools opens as expected and works just fine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:** 
Install the React chrome extension on Vivaldi browser and open devtools on any website

**What is the expected behavior?**
Devtools opens and functions normally

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** 
OS: Windows 10
Browser: Vivaldi

**Comment by bvaughn** [comment]
Which specific version of the extension do you have installed?

**Comment by scrossan-crown** [comment]
I have version `4.0.4 (8/18/2019)`

**Comment by bvaughn** [comment]
Ah, I just noticed "Browser: Vivaldi". That isn't a supported browser. Only Chrome and Firefox are supported targets, although I think (Chromium) Edge also works. (It's not that we intentionally _don't_ support lesser popular browsers like Vivaldi. We're just trying to be pragmatic about which ones we support.)

I think we would be happy to review a PR that fixes this issue, if you'd like to dig into it, but I don't think we'll take any action on it otherwise.

**Comment by scrossan-crown** [comment]
Ok. It is a Chromium based browser and it was previously working before today. I guess I can take a look at it when I have some spare time.

**Comment by bvaughn** [comment]
> it was previously working before today.

As in, 4.0.3 worked but 4.0.4 doesn't? or v3 worked but v4 doesn't?

Could help narrow down what's changed significantly if it broke in a minor v4 bump. :smile:

**Comment by bvaughn** [comment]
https://twitter.com/sophiebits/status/1163511674416128007

Apparently Vivaldi's chrome is built with React. Maybe the crash is because DevTools and that React are interacting in a bad way? Maybe that's because the built-in React is pre v15?

**Comment by scrossan-crown** [comment]
@bvaughn Vivaldi released an update recently and after I updated to the new version there's no issue opening devtools with the React Developer Tools extension
