### ISSUE TITLE
DevTools: Improve HOC search UX

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16467]
Building on top of #360

We could probably improve the search UX in a couple of ways:

* Visually indicate when the "match" is because of a HOC name, e.g.
<img width="161" alt="Screen Shot 2019-08-03 at 1 54 21 PM" src="https://user-images.githubusercontent.com/29597/62416804-36f32f00-b5f6-11e9-9150-e32f652c7f98.png">

* Match built-in HOC types (e.g. searching "me" should match `React.memo` HOCs, searching "f" should match `React.forwardRef`, etc.)

---
Originally reported via https://github.com/bvaughn/react-devtools-experimental/issues/365

**Comment by SavePointSam** [comment]
Looks like the link to the old PR doesn't work. The above message refers to https://github.com/bvaughn/react-devtools-experimental/pull/360.
