### ISSUE TITLE
DevTools: Don't show "context" for classes without either contextType or contextTypes

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16466]
* Don't show "context" for classes without either contextType or contextTypes
* For classes with contextTypes, change the label to "legacy context" instead

---
Originally reported by @gaearon via https://github.com/bvaughn/react-devtools-experimental/issues/368

**Comment by hristo-kanchev** [comment]
I'm working on this one.

Just for clarifying if anyone else is looking at this atm.

**Comment by hristo-kanchev** [comment]
@bvaughn I've fixed the issue. Once we merge the DevTools in master, I'll create the PR. 🚀

**Comment by bvaughn** [comment]
Thanks @hristo-kanchev. I'll do my best to get #16381 merged as soon as possible.
