### ISSUE TITLE
DevTools: Switch between "Rendered At" renders using keyboard arrow keys

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16473]
My favorite devtools feature, "Why did this render?", has a remaining problem: it's too hard to flip through a long list of renders in the Rendered At list to find an interesting render. I know I can use the mouse (or Tab and then Space) to move to the next render, but that's painful if there are 50+ renders to work through.

Suggestion: when an item in the Rendered At list has focus, then up/down arrows should change the selected render (and scroll the pane up/down if the selected render isn't visible). 

This would be helpful for accessibility too.

I'll file a separate issue for keyboard support for the flamegraph view. Keyboard access to that view will be much harder to implement so it makes sense to do it separately.

---
Originally reported by @justingrant via https://github.com/bvaughn/react-devtools-experimental/issues/332

**Comment by ChrisDobby** [comment]
I'll have a look at this one if it's OK?

**Comment by bvaughn** [comment]
If you'd like to take a look at it, @ChrisDobby, feel free. No one else is working on it for the time being.
