### ISSUE TITLE
DevTools: Should be able to add a prop that is not yet set

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16484]
Right now I can inspect a component and edit its props but I could not find a way to add a _new_ prop that wasn't already set.

---
Originally reported by @steveluscher via https://github.com/bvaughn/react-devtools-experimental/issues/300

**Comment by hristo-kanchev** [comment]
I'm currently playing around with this and I would like to get some feedback regarding the visual representation of it.

I presume that we should be able to support more complex data structures, right?

![add-new-prop](https://user-images.githubusercontent.com/23095052/63599546-2107d700-c5c2-11e9-91ad-a057d57bc41c.gif)

**Comment by bvaughn** [comment]
I like the "+" button.

I think we should probably use `JSON.parse` to accept new input types, so that would enable strings/ints/booleans/objects/arrays.

**Comment by hristo-kanchev** [comment]
Awesome! Thanks @bvaughn. I'm on it 🚀

**Comment by hristo-kanchev** [comment]
@bvaughn What do you think of this style of editing props?

It's aligned with the style editor. 😄 

If you are cool with this I can start preparing the branch. 🎉 

👇 

**Number -> String -> null -> Number**

![props-1](https://user-images.githubusercontent.com/23095052/64120611-f32e4980-cd9c-11e9-9fab-fd6c6970aea5.gif)

---

👇 
**String -> Object**

![props-2](https://user-images.githubusercontent.com/23095052/64120612-f32e4980-cd9c-11e9-8f07-0df02f4f2b3d.gif)

**Comment by bvaughn** [comment]
That looks really nice.

**Comment by hristo-kanchev** [comment]
> That looks really nice. Let's do it!

Cool! I'll try and get it finished by the end of the week. I'll ping you when it's done. 
Thanks for the feedback Brian!

**Comment by hristo-kanchev** [comment]
**Update**: Almost done! Just finishing up some styling tweaks. PR should be open tomorrow :)
