### ISSUE TITLE
DevTools: Suspense Debugger

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16489]
### MVP
- [x] Initial prototype with a tree and toggling.
- [x] Tree should reflect real suspense state.
- [ ] Make it less fragile.
  - [x] Does findDOMNode issue affect this?
- [ ] Ensure expensive tree construction doesn't run unless you're on the tab.
- [ ] Improve navigation so the user doesn't get lost.
  - [ ] Maybe flash nodes.
  - [ ] Maybe offer a "finder" tool.
- [ ] Sync selection with the Components tab.
- [ ] Make it look nice. @bvaughn 

### Future
- [ ] Consider a fuzzer.
- [ ] Considering filtering by viewport.
- [ ] Optimize the tree updates.
  - [ ] Consider listening to operations. Don't forget to handle ancestor reorder.

---
Originally reported by @gaearon via https://github.com/bvaughn/react-devtools-experimental/issues/43

**Comment by camjw** [comment]
Hey there, is there any update on this? We just started using Suspense and I'm very keen to be able to know which component triggered Suspense since it can bubble up from a lot of places.

**Comment by bvaughn** [comment]
This issue is very stale and should probably be closed.

>  I'm very keen to be able to know which component triggered Suspense since it can bubble up from a lot of places

You might find the Timeline profiler helpful for getting more insight into what's happening with Suspense. It can show you which component suspended (and if the thennable has a `displayName`, what it suspended to load)
<img width="925" alt="Screen Shot 2023-04-14 at 8 48 27 AM" src="https://user-images.githubusercontent.com/29597/232047944-1d93bd1e-3e88-45b2-82fe-e00bdd2e3a8c.png">

I also personally find Replay.io pretty helpful for debugging Suspense caches more directly, but how useful it is depends on how often the cache fires (super noisy caches can be tricky to debug).
