### ISSUE TITLE
DevTools: Elements height being clipped by console

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16486]
![clipping-bug](https://user-images.githubusercontent.com/10223856/55770859-3984b400-5a5c-11e9-8ae4-e51ecf1e4f51.gif)

This one was kinda tricky to reproduce, but basically the steps are:

1. Click the inspect element and hover any component
2. Open the console pressing esc
3. Move mouse back to devtools and click again the inspect button (to stop inspection).
4. Close the console with esc.

(ps: sorry for the gif quality, I don't know how to properly convert the .mov to .gif)

---
Originally reported by @lucasecdb via https://github.com/bvaughn/react-devtools-experimental/issues/110

**Comment by bvaughn** [comment]
Comment from @bvaughn https://github.com/bvaughn/react-devtools-experimental/issues/110#issuecomment-481281533

---

This bug has been on my notepad todo list for a while. I'm pretty sure it's a problem with the [react-virtualized-auto-sizer package](https://npmjs.com/package/react-virtualized-auto-sizer) not getting an event when the extra console opens and closes, so the fix might need to be upstreamed. Haven't dug into it yet.

**Comment by bvaughn** [comment]
Can't repro this. Haven't heard any "me too" comments on it since it was filed. I'm going to close it.

**Comment by lucasecdb** [comment]
can't reproduce it either, nor have I experienced this for a long time
