### ISSUE TITLE
DevTools: Overlay stays after devtools are closed

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16485]
1. Hover over a node so you see its bounding box over the page
2. Without moving your mouse, press Cmd-Opt-J to hide the devtools

Result: The overlay stays (even if you move your mouse or reopen React devtools!)

Expected: It disappears.

---
Originally reported by @sophiebits via https://github.com/bvaughn/react-devtools-experimental/issues/296

**Comment by realalexhomer** [comment]
Mind if I fix this one?

**Comment by bvaughn** [comment]
It's all yours, @realalexhomer

Please let us know if you decide not to work on it so we can remove the "taken" label.

**Comment by realalexhomer** [comment]
hey sorry just saw this notification ill look at it today

**Comment by bvaughn** [comment]
Hi @realalexhomer, since it's been a couple of weeks without an update- I'm going to remove the "taken" label from this so someone else can claim it. If you decide to pick it back up, just let us know :)

**Comment by tferullo** [comment]
Hi @bvaughn I was interested in taking a stab at this so I followed the development instructions here:
https://github.com/facebook/react/tree/master/packages/react-devtools

and I'm getting an error when I run `yarn` or `yarn start:backend` from react-devtools-core

<img width="720" alt="Screen Shot 2019-09-25 at 9 23 17 PM" src="https://user-images.githubusercontent.com/8031453/65650938-dae7ce00-dfda-11e9-8601-02d130b6a287.png">

node version 12.10 -- should I downgrade?

**Comment by tferullo** [comment]
downgraded to 10.16.3. Same error.

**Comment by bvaughn** [comment]
Sorry about that. You'll need to run `yarn build -- react,react-dom,react-is,scheduler --type=NODE` in the main directory once first.

**Comment by tferullo** [comment]
sounds good, I'll try that tonight.

**Comment by halitogunc** [comment]
Is this still valid? I couldn't reproduce the issue.

**Comment by bvaughn** [comment]
Not sure. I wasn't the one who originally reported it. (I just migrated it from another repo.)

If you think it's no longer happening, we could close it. Can anyone else confirm?

**Comment by ivandevp** [comment]
I've tried to reproduce it and I can't see the error happening.

**Comment by bvaughn** [comment]
Okay. Let's close it for now and we can reopen if necessary. Thanks folks!

**Comment by sophiebits** [comment]
Confirmed this isn't an issue for me any more.
