### ISSUE TITLE
DevTools: Fix or silence "cannot find fiber with ID" warnings when hovering 

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16493]
Sometimes I see "cannot find fiber with ID" when hovering over the tree. They are sporadic. I'll need to dig into why they happen. But we also need to look at our usage of warnings to make sure they're either actionable or gated by DEV/DEBUG.

---
Originally reported by @gaearon via https://github.com/bvaughn/react-devtools-experimental/issues/166

**Comment by bvaughn** [comment]
Comment from @bvauhgn https://github.com/bvaughn/react-devtools-experimental/issues/166#issuecomment-483785495

---
I agree this is probably not ideal currently. What are "expected" edge cases and what are legit errors? I've tried to replace legit error cases with `throw` statements recently, but I understand that it's still not the clearest.

Some (most?) of the the remaining warnings are expected potential edge cases. A little more context...

For example, if an element is selected in the DevTools frontend, then it gets unmounted on the page/backend, we may temporarily see this warning when we query for its inspected props:
https://github.com/bvaughn/react-devtools-experimental/blob/20193f03c04971a14ee8a0b6755bdfee08b94ba3/src/backend/renderer.js#L1432-L1438

Similarly, since the `Store` is mutable, it's possible that a node will be removed while a render batch is in progress:
https://github.com/bvaughn/react-devtools-experimental/blob/85179fe4a7e7cb2e9d79733eec4839443393e7ba/src/devtools/views/Components/Element.js#L122-L128

**Comment by capaj** [comment]
I get quite a lot of them: 
![image](https://user-images.githubusercontent.com/1305378/90649268-d3589580-e23a-11ea-99d7-20084f2b93bb.png)

I have react `"react": "^16.13.1"`
and React Developer Tools
`4.8.2 (7/15/2020)`

Also it seems that quite big parts of my react component tree are not visible in the tree.

**Comment by bvaughn** [comment]
Repro info would be helpful if you can provide it.

**Comment by ManzerHa-Kore** [comment]
I got this warning too after componentWillMount warning.


![error](https://user-images.githubusercontent.com/50398944/91159567-db568080-e6e5-11ea-9daa-7a80c15cd41d.png)

**Comment by Amoodaa** [comment]
@bvaughn i can provide a repro, but it also may be part of my bad?
but I seriously dunno why its happening

**Comment by bvaughn** [comment]
@Amoodaa Share the repro and we'll see?

**Comment by Amoodaa** [comment]
![image](https://user-images.githubusercontent.com/8256872/99186874-e73d6600-275b-11eb-8b71-394670232e8e.png)
im suspecting the lazy loading im using, maybe I'm overdoing it as well
will zip the repo and we'll talk it out

**Comment by Amoodaa** [comment]
[repro cannot find fiber.zip](https://github.com/facebook/react/files/5542469/repro.cannot.find.fiber.zip)
its closed source project so ill delete it once u download it

**Comment by Amoodaa** [comment]
im going to send u an email with the repo and the env bc in happens to need to login

**Comment by Amoodaa** [comment]
can you check your inbox @bvaughn

**Comment by bvaughn** [comment]
Great, thank you. It's Sunday here so I'm not going to dig into this until tomorrow at the earliest, but I will let you know what I find.

**Comment by bvaughn** [comment]
Still on my plate for this week but it's been a busy one so far. Probably going to be a few days. Thanks for your patience.

**Comment by Amoodaa** [comment]
@briankung i sent you new credentials and an updated version of the repo

**Comment by bvaughn** [comment]
Ok thank you. I'll try to look again today.

**Comment by bvaughn** [comment]
I can repro with the latest example you've sent. First thing I tried doing was stripping things out of the app to make the repro case smaller, and I noticed that removing `react-helmet-async` "fixed" the problem. (Not sure why yet, still digging in.) Seems specific to the `Helmet` component and entering or leaving the Settings route.

**Comment by bvaughn** [comment]
Seems like I can further narrow it down to say that if I remove all of the Material components, my reduced repro stops failing as well. Leaving in e.g. `ListItem` is enough to repro the bug though.

**Comment by bvaughn** [comment]
Does indeed seem related to the `Loadable` approach you're using. If I remove all of the loadable wrappers, I can't repro the issue.

**Comment by Amoodaa** [comment]
tbh, this is my first time using lazy loading, and i can see now why its still not as "widely used", ill probably do a pass on the app, bc its having a real overhead on reloading/bootstrap time
and when i updated to react-scripts.4.0.0 and react 17.0.1, it started appearing, so, can you try downgrading to 
4.0.0.next-98 and 16.13.1? and see what happens, this is info i should have passed earlier

**Comment by Amoodaa** [comment]
@bvaughn So this seems to becoming stale again until more repros appear,
Can i get a hint on how to fix my codebase then?

**Comment by bvaughn** [comment]
I think I found the underlying cause of this bug. I think it's caused by a combination of the "legacy" `ReactDOM.render()` method and `React.Lazy`. In legacy render mode, when a Lazy component renders and suspends (because it hasn't loaded the inner component yet) the React tree gets committed in an inconsistent state (everything down to the suspended boundary, but not below). If the Lazy component (or the tree containing it) get removed quickly, before the inner component is loaded and committed, React will tell DevTools to *unmount* the Lazy component (that never actually mounted) and DevTools will thrown an error.

**Comment by bvaughn** [comment]
I believe this issue was fixed via PR #20362. It has now been published as v4.10.1 and should be available shortly. Thank you!
