### ISSUE TITLE
DevTools:  Commit picker should register leaving the picker at a side as setting a terminal value

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#16492]
Seems non-ideal. Typically range controls handle this case.

![Screen Recording 2019-04-12 at 07 54 PM](https://user-images.githubusercontent.com/810438/56059844-0e041100-5d5d-11e9-892c-f3872414ffaa.gif)

---
Originally reported by @gaearon via https://github.com/bvaughn/react-devtools-experimental/issues/141

**Comment by bl00mber** [comment]
How to access this UI, is it still exists? Profiler does not seem to have it.

![Screenshot from 2020-04-30](https://user-images.githubusercontent.com/16987322/80663721-3bc61000-8aae-11ea-873d-2cd94dfb3040.png)
