### ISSUE TITLE
<video/> 'autoplay' attribute

### ISSUE THREAD

**Issue by username99987** [facebook/react#1649]
Is there a reason why `<video ... autoplay />` does not work in React. Or I am doing something wrong?

**Comment by PARAGJYOTI** [comment]
thanx..camalCase works

**Comment by sami718** [comment]
write it as autoPlay

**Comment by sami718** [comment]
can someone suggest me to apply autoplay to video in carousel item ...and only active carousels video should play

**Comment by monfera** [comment]
What @andreypopp said ⏫ and the [doc](https://reactjs.org/docs/dom-elements.html) says

| In React, all DOM properties and attributes (including event handlers) should be camelCased.

**Comment by stevenmchoi** [comment]
NEW change! Try this:
`<video ... autoPlay muted />`
According to [this](https://www.npmjs.com/package/react-player#autoplay), Chrome 66 stops autoplay of all video that don't have the "muted" property.

**Comment by yaverm** [comment]
> Try `<video ... autoPlay />`. DOM attributes should be camelCased in React.

you are genius, i spent 2 h for solve this problem, it turned out that simple solution ;)

**Comment by rbk** [comment]
> NEW change! Try this:
> 
> ```
> <video ... autoPlay muted />
> ```
> 
> According to [this](https://www.npmjs.com/package/react-player#autoplay), Chrome 66 stops autoplay of all video that don't have the "muted" property.

Thank you!

**Comment by ckOfor** [comment]
I have both autoPlay and muted but it still does not play

**Comment by vilmes21** [comment]
> I have both autoPlay and muted but it still does not play

I had the same problem. So I programmatically set a `react ref for my video tag`, then wrote         `this.videoRef.current.play();`

**Comment by tlisiewi** [comment]
I check in Jan2020 with Chrome and autoPlay works fine HOWEVER check your browser notification (in the adress bar) regarding 'blocking auto play on this website' - this was turned on in my browser, so I couldn't get auto play work :P

**Comment by bilal-korir** [comment]
In my case, none of the solutions mentioned above worked. react-player also did not fix my problem. However, This solution on [StackOverflow](https://stackoverflow.com/questions/59404642/react-html-video-tag-wont-autoplay-on-mobile-devices) worked perfectly for me. It seems there is a bug with `muted` in React.



`
var EmbedVideo = function(props) { 
   return ( 
       <div dangerouslySetInnerHTML={{ __html: ` 
        <video
          loop
          muted
          autoplay
          playsinline
          src="${props.src}"
          class="${props.className}"
        />,
      ` }}></div>
   )
}
`

**Comment by NurAminSifatTanha** [comment]
> ...

why ... show me error?

**Comment by Adrinlol** [comment]
> In my case, none of the solutions mentioned above worked. react-player also did not fix my problem. However, This solution on [StackOverflow](https://stackoverflow.com/questions/59404642/react-html-video-tag-wont-autoplay-on-mobile-devices) worked perfectly for me. It seems there is a bug with `muted` in React. According to Google media autoplay policy, if `muted=true` then the video should play. Hopefully, the React team will look into :)
> 
> `` var EmbedVideo = function(props) { return ( <div dangerouslySetInnerHTML={{ __html:`` <video loop muted autoplay playsinline src="${props.src}" class="${props.className}" />, `` }}></div> ) } ``

Using the same solution for my project. Unfortunately, this still doesn't work on my iOS device’s Safari browser.

**Comment by rickhanlonii** [comment]
Hey all, this issue is from 2015 and is specific to the autoplay attribute not being camel cased (which is solved).

If you're having other autoplay related issues, they're likely not related to React but if you can create a repo please file a new issue. Going to lock to prevent future noise.
