### ISSUE TITLE
How can react be configured to package multi-page applications

### ISSUE THREAD

**Issue by i-fuyun** [facebook/react#16503]
**I want to request a feature.**

**How can react be configured to package multi-page applications**

Now versions:
React v16.8.6
Browser Chrome 76
OS Window 7

**Comment by embeddedt** [comment]
Isn't packaging applications something that is not specific to the framework you're using but rather your project's bundler (if you have one)?

**Comment by threepointone** [comment]
Closing this since it isn't a bug or feature request, I'd recommend trying one of our community resources for answers on the same https://reactjs.org/community/support.html
