### ISSUE TITLE
eslint-plugin-react-hooks should warn when a custom hook returns a component with possibly stale closure

### ISSUE THREAD

**Issue by viheikki** [facebook/react#16513]
**Request for a *feature***

**What is the current behavior?**

Although the CRA 3 default linters are configured to warn about possible closure bugs, they don't warn about a likely closure bug when a hook returns a component. Please see the example below. The value rendered in the HookCount component does not change when the button is clicked:
```
import React, { useState, useContext } from 'react';

const CountContext = React.createContext(1);

function useHookCount () {
  const count = useContext(CountContext);
  const HookCount = () => (
    <div>{ count }</div>
  )
  return HookCount;
}

const Count = () => {
  const count = useContext(CountContext);
  return <div>{ count }</div>
}

function App() {
  const [ count, setCount ] = useState(3);
  const HookCount = useHookCount();
  return (
    <CountContext.Provider value={ count }>
      <div>
        <button onClick={() => setCount(prevCount => prevCount + 1)}>{ count }</button>
        <HookCount />
        <Count />
      </div>
    </CountContext.Provider>
  );
}

export default App;
```

**What is the expected behavior?**

eslint-plugin-react-hooks should warn about the possible closure problem(s) when a custom hook returns a component that uses a value from the hook function closure.

**Which versions of React are affected by this issue?**

Tested with 
react: 16.9.0
react-scripts: 3.1.1

**Comment by vkurchatkin** [comment]
1. Never create components inside of render, with hooks or otherwise. This can cause component being remounted on every render.

2. The closure is not stale in this case. You can't get a stale closure if you don't use `useMemo`, `useCallback` or `useEffect`. You are just calling `useContext` outside of context provider, so you always get the default value.

**Comment by viheikki** [comment]
I see my analysis of the root cause was wrong. Nevertheless, maybe a linter rule should warn (error?) in this kinds of situations?

**Comment by threepointone** [comment]
This doesn't seem like an issue with eslint-plugin-react-hooks, so I'm closing this issue. Might be cool if someone makes an eslint plugin that warns on creating Components inside a function, though HOCs are a totally valid usecase  for doing so as well.

**Comment by viheikki** [comment]
Just as an aside, if creating a Component inside of the render is always a no-no, maybe a linter rule could show an error when that is detected.
