### ISSUE TITLE
create-react-class uses unmaintained version of core-js

### ISSUE THREAD

**Issue by daveisfera** [facebook/react#16515]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Using an unmaintained version of `core-js`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Add `create-react-class` to `package.json` and then run `yarn install` and the following warning is output:
`create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2`

**What is the expected behavior?**
Maintained version of `core-js` is used

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`create-react-class: 15.6.3` (current version available in npm)

**Comment by bvaughn** [comment]
I wouldn't really call this a bug. `create-react-class` is, itself, unmaintained. We haven't published a release of it in ~2 years.

**Comment by gaearon** [comment]
`create-react-class` doesn’t use anything from `fbjs` that would itself use `core-js`. So there is no actual issue here.

**Comment by daveisfera** [comment]
Just noticed another example in the documentation that says that `create-react-class` is still supported: https://reactjs.org/docs/faq-versioning.html#commitment-to-stability
