### ISSUE TITLE
Router navigated page doesn't refresh

### ISSUE THREAD

**Issue by iamanas20** [facebook/react#16524]
Hey, I noticed that when using Router Routes to navigate to pages and if reload the browser at that page it doesn't reload, it need to go to the root '/' to load them again!

this is my code! (ScrollToTop makes page scroll to top every time router updates)

```
<Router>

      <ScrollToTop>

            <Route exact path="/" component={FirstPage}/>

            <Route exact path="/sec" component={SecondPage}/>

            <Route exact path="/appoint" component={ThirdPage}/>

      </ScrollToTop>

</Router>
```
How can I reload in the SecondPage for example and still load it instead of getting 404?

**Comment by bsotodo** [comment]
This is not a react issue. Take a look at this 👇 
https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually
