### ISSUE TITLE
DevTools: Profiler: Save profile does nothing on Firefox

### ISSUE THREAD

**Issue by deadmau6** [facebook/react#16527]
Hi, long time user, first time issuer.

I think I found a bug with the Profiler component. When I click on the `Save profile...` button at the top nothing happens and there appears to be no new files in my Downloads folder. I think it might be silently failing and that's why I am not getting any response.  Has anyone else ran into this issue?

Another thing I would like to mention is that I haven't looked through all of the documentation material about the new Profiler. I only read [this introductory blog post](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html), so if this issue is addressed elsewhere I apologize and also request the source to that solution.

Thank you for your time!

**Versions:**
 * `React DevTools 4.0.5`
 * `Firefox: 68.0.2(64-bit)`
 * `Ubuntu: 18.04`

**Comment by hristo-kanchev** [comment]
It seems that this is happening because of the HTMLElement generation in the `downloadFile` util function.

I'll investigate this further.

**Comment by hristo-kanchev** [comment]
I fixed the issue. I'll open a PR later today :)
