### ISSUE TITLE
flow with import * as React from 'react'

### ISSUE THREAD

**Issue by httol** [facebook/react#16520]
I use flow, so 
```js
import * as React from 'react',
```
But also I use React Hook, like useState.
so how can I import this?
like
```js
import * as React, {useState} from 'react' 
```
or
```js
import * as React from 'react';
import  {useState} from 'react';
```
 or some other method?

Hope for better workaround!

**Comment by FilipIlievski** [comment]
You can't `import * as React, {useState} from 'react' ` use an alias to import the whole `react` and then another entity of it in the same module import.
You can either do `React.useState(...)` or 
`import * as React from 'react';
import  {useState} from 'react';`

I suggest the former as it's cleaner and better when it comes to modules resolution.

Maybe take a look at this as well: [https://exploringjs.com/es6/ch_modules.html](JavaScript Modules)

**Comment by gaearon** [comment]
Yeah. Eventually the plan is to change the JSX transform to remove the need for `import *` altogether.
