### ISSUE TITLE
React throws an error when using onSelectStart

### ISSUE THREAD

**Issue by mtjn** [facebook/react#16521]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When setting this event handler property, React throws an error.

Example jsx:

```jsx
<div
  onSelectStart={e => e.preventDefault()}
>
  Test
</div>
```

React throws the following error:

`Warning: Unknown event handler property `onSelectStart`. It will be ignored.`

Codesandbox link: https://codesandbox.io/embed/holy-violet-4unq8

**What is the expected behavior?**
React is aware of `onSelectStart` and connects to `onselectstart` correctly, without throwing an error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on latest desktop (linux) Chromium and Firefox with react/react-dom 16.8.6 and 16.9.0, react-scripts 3.0.1 and 3.1.0.

c.f. https://github.com/facebook/react/issues/15787

**Comment by threepointone** [comment]
I'm not aware of our policy is on this. @trueadm / @necolas, do you folks have an opinion on this?

**Comment by eps1lon** [comment]
caniuse.com is usually a bit more up-to-date: https://caniuse.com/#feat=selection-api. It's iOS Safari and opera mini that are having trouble.

**Comment by threepointone** [comment]
I see, I see. _My own opinion_ on this then, is that we probably *shouldn't* add it just yet, because people will use it and expect it to work across platforms, and blame React when it doesn't. Either we polyfill the behaviour and provide it in React, or use a workaround in userland (with refs, etc).

**Comment by trueadm** [comment]
I was initially confused by the naming of this experimental API and that of the selection API (which already works in React via `onSelectionStart`). I'm also leaning towards not adding support for this API, simply because it's experimental and might change or get removed in the future.

**Comment by threepointone** [comment]
The workaround then, if needed, is to use a ref on the element and manually add/remove event listeners on the node. Happy to revisit this if it actually becomes a standard in the future. 

Closing this issue.
