### ISSUE TITLE
Is it possible to write a script to inject props on a component?

### ISSUE THREAD

**Issue by suddjian** [facebook/react#16549]
**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the current behavior?**

Unknown

**What is the expected behavior?**

So this is a little crazy. There's a web app that I use that is built with React, which has made certain design decisions that I disagree with. The design is actually simple to change exactly the way I want by just opening the chrome devtools and changing the props assigned to a specific component. But I don't want to manually do this every time, that's not worth it. I want to write a (super hacky) personal script that automatically modifies the props being passed to this component. Wondering if anyone knows a simple hack for this.

**Comment by threepointone** [comment]
This probably isn’t the right place to ask this, we use the issue tracker for bugs and feature requests. I personally can’t think of a good way to do it, but you may have better luck on one the community resources  https://reactjs.org/community/support.html

Closing this issue.
