### ISSUE TITLE
[feedback] Hooks and timeout Id

### ISSUE THREAD

**Issue by VincentCharpentier** [facebook/react#16544]
**Do you want to request a *feature* or report a *bug*?**
Feedback on hooks adoption

**What is the current behavior?**
before react hooks, I sometimes used instance properties to store some data irrelevant for the render function. A good example would be a timeoutId, could be for some custom debouncing.

    class SomeComponent extends React.PureComponent {
      handleSomething() {
        clearTimeout(this.timeoutId);
        this.timeoutId = setTimeout(() => {
          // do something
        }, 1000);
      }
      // ...
    }

Now I don't have `this` anymore. I don't see how to have a timeoutId for each component instance except using `useState`:

    const SomeComponent = () => {
      const [timeoutId, setTimeoutId] = useState(null);
      const handleSomething = () => {
        clearTimeout(timeoutId);
        setTimeoutId(setTimeout(() => {
          // do something
        }, 1000));
      }
      // ...
    };

**What is the expected behavior?**
In the last example using state to store the timeoutId feels wrong because I'm triggering a re-render (I think) but `timeoutId` is irrelevant for the rendering step.
I feel like I should store it elsewhere but where ?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8+

----

The title is specific to my issue but it is a generic problem, everywhere I used to have instance member I'm now forced to put everything in states.

**Comment by FilipIlievski** [comment]
```
React.useEffect(() => {
    let timer: NodeJS.Timeout; // TypeScript. Ignore the type if you use JavaScript

    if (props.somethingForEg) {
      timer = setTimeout(() => {
        // your logic
      }, 1000);
    }

    return () => {
      if (!props.somethingForEg) {
        clearTimeout(timer);
      }
    };
  }, [somethingForEg]);
```

You get the idea... It's very much likely that you'll want to do `handleSomething` inside the `useEffect`, so the above example might give you an idea.

**Comment by threepointone** [comment]
Refs, state, and locally scoped variables are good solutions to handling timeout IDs. For a deeper dive into some of the considerations around timeouts, consider Dan's excellent deep dive into a  setInterval hook https://overreacted.io/making-setinterval-declarative-with-react-hooks/ Closing this since it isn' a feature/bug request
