### ISSUE TITLE
Devtools: Impossible to debug firefox webextension moz-extension: pages due to strict CSP

### ISSUE THREAD

**Issue by saneyuki** [facebook/react#16548]
**Do you want to request a *feature* or report a *bug*?**

* feature request
* Original issue is: https://github.com/facebook/react-devtools/issues/922
   * There are more details.
* Mozilla's Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1573027

**What is the current behavior?**

The react-devtools toolbar button does not light up and clicking on it says "This page does not appear to be using react". This is probably since extensions are not allowed to inject scripts into other extensions' pages.

**What is the expected behavior?**

The react-devtools toolbar button should light up and the addon should be able to debug the page

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This is still reproducible

* Firefox v68~
* react devtools v4.0.5
* react v16.9

**Comment by swrobel** [comment]
Dupe of: https://github.com/facebook/react/issues/16514
