### ISSUE TITLE
DevTools: Ability to save inspected values as global variable (as it was in previous version)

### ISSUE THREAD

**Issue by AkhmedovValikhan** [facebook/react#16541]
Hi, I really like new dev tools (4.0.5), but I would like to request one useful feature.

In previous version it was possible to save inspected value (prop/state/context) and its parts as a global variable using context menu->store as global variable, so it can be easily be accessed through console using `$tmp{n}`. In current version this is behaviour was replaced be creating new "bug" button which will just print all values in console. Unfortunately it's hard to navigate through this object, because $_ in console will return undefined. And in order to access it you need to expand group, find desired property and open context menu->store as global variable. 
It would be perfect if you combine these 2 approaches so it would be possible to both print values using "bug" button and opening context menu directly in react dev tools panel wihtout need of intermediate step. 

Thanks!

**Comment by gaearon** [comment]
Maybe values in the tree could have a "bug" button next to them too that appears only on hover.

**Comment by bvaughn** [comment]
See issue #16428

I don't personally think this needs to be a top level button. You can still store global vars using the console itself and the existing UI:

![store-Kapture 2019-08-16 at 13 19 57](https://user-images.githubusercontent.com/29597/63195846-9276e100-c028-11e9-9034-661ba8d6f285.gif)

**Comment by bvaughn** [comment]
> Maybe values in the tree could have a "bug" button next to them too that appears only on hover.

This is a little tricky in some edge cases (really close to the right/left side) and probably not the greatest in terms of accessibility (although we have a lot of areas we could stand to improve on in this regard).

**Comment by AkhmedovValikhan** [comment]
@

> See issue #16428
> 
> I don't personally think this needs to be a top level button. You can still store global vars using the console itself and the existing UI:
> 
> ![store-Kapture 2019-08-16 at 13 19 57](https://user-images.githubusercontent.com/29597/63195846-9276e100-c028-11e9-9034-661ba8d6f285.gif)

Hi @bvaughn, the problem in this flow is that you need to do 3 steps: 
1. click on bug
2. expand a group and find desired field
3. right click to store it as global var.
On the other hand, in previous version you can directly store desired property through react dev tools.
Maybe just enable old context menu in the right panel of react dev tools?

**Comment by bvaughn** [comment]
It's slightly more clicks (3 vs 2) but I don't think that necessarily means we need to change it. I don't think this is a very common interaction, and screen real estate is pretty precious in a DevTools.

**Comment by gaearon** [comment]
>It's slightly more clicks (3 vs 2) 

I think @AkhmedovValikhan's point is that usually you start inspecting props/state inline, get to some nested field, and _then_ realize you want to save it. So it's not just one click more; you have to redo the whole "find the nested field" thing after logging.
