### ISSUE TITLE
You need to enable JavaScript to run this app

### ISSUE THREAD

**Issue by wellington-cunha** [facebook/react#16552]
Hello every body I have a react page that was working pretty well but from nothing it started to appear this error "You need to enable JavaScript to run this app."

"react": "^16.8.4",

**Comment by jquense** [comment]
Maybe you or and extension disabled JavaScript?

**Comment by wellington-cunha** [comment]
@jquense Yeah I need to do so. But we need understand I have this applications running for more than one year and from nothing it stop working. It will pretty bad if this error come to our client

**Comment by threepointone** [comment]
I would like to help you, but I cannot if you don’t share a url, a codesandbox, a git repo, or *anything* that shows the problem that you’re having. 
- have you accidentally disabled js in your browser settings?
- is there an error in your browser console? Any warnings?
- if *nothing* changed from your end, why do you believe this is an issue with React? 

Please provide more details.

**Comment by wellington-cunha** [comment]
@threepointone , Sorry for my later reply .
I was so busy doing some work for my company.
I have fix this issue.
The problem was my api have reverse-md5 package to decode some md5 string comes into a validation link,
soon as this package could not decode it keep my express server hanging no answer and it causes that error in my frontside. 
I solved it by use cryptr.

Thank for help.
