### ISSUE TITLE
DevTools: TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by chrisnojima** [facebook/react#16562]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using the latest Dev tools (v4.0.5) on my project, when I inspect react-redux elements that use connect() devtools crashes. I can't map from my crash to the actual source but the code is react devtools: build/backend.js
```
 useMemo: function(e, t) {
            var n = w()
              , r = null !== n ? n.memoizedState[0] : e(); // <-- here n exists, but n.memoizedState itself is null
            return v.push({
                primitive: "Memo",
                stackError: new Error,
                value: r
            }),
            r
        },
```

up one level of stack is react: 
```
function useMemo(create, inputs) {
  var dispatcher = resolveDispatcher();
  return dispatcher.useMemo(create, inputs);
}
```

and up one level is react-redux: (https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L199)
```
const childPropsSelector = useMemo(() => {
        // The child props selector needs the store reference as an input.
        // Re-create this selector whenever the store changes.
        return createChildSelector(store)
      }, [store])
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I'll have to try and make a small repro, but I hope there's something obvious given the info above. It's not clear to me if react-redux is doing something or if its devtools. This behavior existed in v3 and i was hoping it'd get magically fixed with v4 but it remains.

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is in an electron app w/ react-redux v7.1.0 and react v16.8.3 (have to use this due to the version of react native i'm on)

**Comment by bvaughn** [comment]
> This is in an electron app w/ react-redux v7.1.0 and react v16.8.3 (have to use this due to the version of react native i'm on)

Unfortunately this is a bug with React that was fixed via PR #14940 and released with v16.8.4.

Thank you for the detailed bug report though!

Originally reported here:
https://github.com/bvaughn/react-devtools-experimental/issues/23
