### ISSUE TITLE
Ide support

### ISSUE THREAD

**Issue by mictadlo** [facebook/react#1656]
Hi, 
Any plans to integrate REACT to Netbeans (https://netbeans.org/downloads/) which already has HTML5 & JavaScript support https://www.youtube.com/watch?v=edw0js0hdEo ?

Thank you in advance.
Mic

**Comment by bfanger** [comment]
Vote on https://netbeans.org/bugzilla/show_bug.cgi?id=250778 for JSX support in Netbeans.

**Comment by JeyKeu** [comment]
https://blogs.oracle.com/geertjan/entry/react_js_and_netbeans_ide

**Comment by ram-you** [comment]
Vote for "Netbeans  *.jxs support" here:  https://netbeans.org/bugzilla/show_bug.cgi?id=250778

**Comment by ram-you** [comment]
@spicyj 
Hi Ben, when we are speaking about NetBeans and you say "It's impractical for us to add JSX support to every editor out there...", NetBeans is not "every editor out there",  it's a kind of insulting because we must remember that NetBeans is 18, while Facebook is only 11 years old.  
And here a leading indicator,  NetBeans is ranked 4 on a table of 20 most popular  IDE:
http://pypl.github.io/IDE.html

**Comment by jimfb** [comment]
@ram-you I'm sure it wasn't Ben's intent to suggest that NetBeans was unimportant.  It is a very important IDE that provides substantial value to the community.  But we are not the team who maintains NetBeans, and we are not familiar with the NetBeans codebase.  It is not practical for us to learn the code for every IDE and modify the IDEs to support the features we like.  We need to rely on each IDE development team to add the features that their users are requesting, so the correct route is to contact the developers responsible for your preferred IDE and ask them to prioritize the feature.

**Comment by ram-you** [comment]
Ultimately, it is not for us to decide which editor supports which technology. These are the policy and business choices of Facebook and Oracle.

**Comment by Chris2011** [comment]
As you can see here: https://blogs.oracle.com/geertjan/entry/react_js_and_netbeans_ide1

Geertjan created plugin to bring react to netbeans: https://github.com/GeertjanWielenga/React.js

If someone wanted to contribute, do it. He is searching for a grammar to bring JSX support. Maybe someone can help?
