### ISSUE TITLE
Uncaught TypeError: net.isIP is not a function

### ISSUE THREAD

**Issue by rk173238** [facebook/react#16579]
I am getting below error.
i am trying to send email with nodemailer with simple react application,  but getting below error.

this code works fine ,if i run simply as javascript file( node prog,js)

index.js:40 Uncaught TypeError: net.isIP is not a function
    at Object.push../node_modules/nodemailer/lib/shared/index.js.module.exports.resolveHostname (index.js:40)
    at SMTPConnection.connect (index.js:327)
    at index.js:251
    at index.js:73
    at run (setImmediate.js:48)
    at runIfPresent (setImmediate.js:83)
    at onGlobalMessage (setImmediate.js:125)

Code is:-

export default main;
function main() {
    let transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 587,
        secure: false, 
        auth: {
            user: 'Anything@gmail.com', 
            pass: 'Anything@1' 
        }
    });
    let info = transporter.sendMail({
        from: '"SMC " <Anything@gmail.com>', // sender address
        to: 'sender@gmail.com', // list of receivers
        subject: 'Hello ✔', // Subject line
        text: 'Hello world? jhsgjkhjag ASGJHAGSUAH jasgjGS ', // plain text body
       
    });
    return info; // HERE IT IS COMING AS UNDEFINED
}

Please help me on this

**Comment by GalenWong** [comment]
I believe the `nodemailer` module is only built for Node.js, meaning that it cannot be executed in a browser JavaScript environment, in which your React app is running in. 

More specifically, the `net` module that `nodemailer` depends on is a Node.js only module.

**Comment by rk173238** [comment]
Okay, got it.

Thanks for the quick help.

**Comment by hpbots** [comment]
How can I fix this issue? I am trying to send an email from my react.js electron.js app

**Comment by GalenWong** [comment]
Electron exposes Node.js API so the `net` module should be available in both the main process and renderer process. See docs [here](https://www.electronjs.org/docs/tutorial/application-architecture#using-nodejs-apis). You might get a better answer for the specific problem you run into if you ask on the [`nodemailer` issue page](https://github.com/nodemailer/nodemailer/issues).

**Comment by rixment** [comment]
Had the same problem with nodemailer (Electron + React). Of course as it turned out it was a mistake on my side as I was trying to execute the nodemailer's code on the rendering process and not the main one. Hope it will come useful - https://stackoverflow.com/questions/65359469/sending-email-via-app-written-in-electron-react-ts/65360371
