### ISSUE TITLE
Missing SVG tags and attributes

### ISSUE THREAD

**Issue by spicyj** [facebook/react#1657]
**Note from maintainers:** We know we don't have complete SVG support. We will add support for the rest of it in 1 fell swoop *soon* (2015-11-11). Additional requests will be ignored until then.

* * *

I'm creating this as a single issue to keep track of missing SVG tags and attributes as they're requested.

Tags:

* textPath (#1633)
* foreignObject (#1298)
* filter, feGaussianBlur (#1646)
* use (#1395)
* foreignObject (#2157)

Attributes:

* fillOpacity, strokeOpacity, opacity (#1171)
* patternUnits (#1535)

~~Feel free to comment on this issue for other missing ones.~~

**Comment by jbroadway** [comment]
+1 for textPath and more complete svg support in general.

**Comment by jeffkole** [comment]
Until SVG is fully supported, a decent workaround is to tell React which svg attributes it should pass through to render and declare the elements you need explicitly.  For example, `<use>` can be accessed like this:

```
var DOMProperty = require('react/lib/DOMProperty');

// xlink:href is not a standardly-supported svg attribute, but you can tell
// React that it is ok.
DOMProperty.injection.injectDOMPropertyConfig({
  isCustomAttribute: function (attributeName) {
    return (attributeName === 'xlink:href');
  }
});

var SvgButton = React.createClass({
  render: function render() {
    var use = React.createElement('use', {
      'xlink:href': '#' + this.props.icon
    });
    return (
      <button>
        <svg>
          { use }
        </svg>
        <div>{ this.props.label }</div>
      </button>
    );
 });
```

**Comment by spicyj** [comment]
@jeffkole Be careful when doing that – React will still call setAttribute (not setAttributeNS) if the attribute changes, and the update probably won't work properly.

**Comment by jeffkole** [comment]
@spicyj I don't see any namespace support in React (ie, there is no call to `setAttributeNS` in the codebase).  Any suggestion on a proper way to set an attribute with a namespace?

**Comment by spicyj** [comment]
We haven't figured out how namespaced attributes will work and don't support it right now, sorry.

**Comment by RileyTomasek** [comment]
`vector-effect` would be nice. Is there another way to keep fixed width strokes without it that can be used in the meantime?

**Comment by Nek** [comment]
+1 for foreignObject

**Comment by gentooboontoo** [comment]
Just referencing my PR for text baseline attributes: #2697

**Comment by chicoxyzzy** [comment]
oh shit I need support for use tag :disappointed:

**Comment by jeffkole** [comment]
I've resigned myself to using a custom component that has a render function that returns

```
<svg dangerouslySetInnerHTML={{ __html: '<use xlink:href="#' + this.props.icon + '"/>' }} />
```

It is ugly, but it works.

**Comment by gre** [comment]
:+1: on this

**Comment by jaketrent** [comment]
+1 on for full svg support in addons

**Comment by danielalves** [comment]
:+1:

**Comment by akre54** [comment]
@zpao @spicyj is there a supported way of adding these individual SVG elements to React without monkey-patching `ReactDOM` and `SVGDOMPropertyConfig`?

**Comment by spicyj** [comment]
Sorry, no.

**Comment by mixtur** [comment]
+1 for image and foreignObject

**Comment by msutherl** [comment]
+1 for foreignObject

**Comment by jasonkuhrt** [comment]
`animate` does not work and possibly some of its attributes: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate

**Comment by aaronshaf** [comment]
What is the status on supporting SVG in addons? Just ran into this today :-(

**Comment by spicyj** [comment]
cc @xymostech @MichelleTodd

**Comment by yayitswei** [comment]
+1 for namespaced attributes.

**Comment by zuotian** [comment]
+1 on for full svg support in addons

**Comment by Loque-** [comment]
+1000 for SVG attribute support :-)

**Comment by theminted** [comment]
+1 for supporting <animate> attributes

**Comment by Dangoo** [comment]
Request for adding attribute "fill-rule", maybe as "fillRule"

**Comment by mmlkrx** [comment]
Would also like to see an SVG addon :+1:

**Comment by aaronshaf** [comment]
React core team, is there any behind-the-scenes movement / discussion on this?

**Comment by spicyj** [comment]
Not on this specifically, but #3718, #3763 are both SVG things being worked on and #3067 is also related to this attributes change.

**Comment by ersagunkuruca** [comment]
+1 for full SVG support. Before it happens I will need a way to create custom tags and attributes. Can anyone please help me with that?

**Comment by tcoopman** [comment]
The marker element is also missing (https://developer.mozilla.org/en/docs/Web/SVG/Element/marker)

**Comment by akre54** [comment]
@ersagunkuruca try https://gist.github.com/akre54/80eaa63762ea499029f0 in the meantime

**Comment by kulicuu** [comment]
+1

**Comment by omidb** [comment]
#3945  These tags are not supported in React SVG for marker: refx, refy,orient

**Comment by omidb** [comment]
:+1: for Markers!

**Comment by kulicuu** [comment]
+1 for SVG all the things.

**Comment by codeuniquely** [comment]
:+1 

how about support for animateTransform properties

    <path
        d="M120 60c0-31.13-26.86-60-60-60">
        <animateTransform
              attributeName="transform"
              type="rotate"
              from="0 60 60"
              to="360 60 60"
              dur="1.5s"
              repeatCount="indefinite" />
    </path>


currently just ends up with 

    <path d="M120 60c0-31.13-26.86-60-60-60" data-reactid=".0.0.0.1.6.0.0.$0.0.0.2">
        <animateTransform type="rotate" data-reactid=".0.0.0.1.6.0.0.$0.0.0.2.0"></animateTransform>
    </path>

**Comment by nlhkh** [comment]
+1 for image

**Comment by webhipster** [comment]
+All SVG supported

**Comment by wuct** [comment]
+1 for filter

**Comment by ptim** [comment]
+1 for use support!

**Comment by ledbruno** [comment]
+1 for namespaced attributes

**Comment by olegshilov** [comment]
+1 for `use` and `filter` attributes support

**Comment by janaspage** [comment]
+1 for `<image>` support. I need React to render an inline SVG that has an image inside a clipping path, and it's getting hung on the `xmlns:xlink="http://www.w3.org/1999/xlink"` attr in the `<svg>` tag.

**Comment by brooklandia** [comment]
i can do this

**Comment by crenwick** [comment]
+1 for `filter`

**Comment by matthewwithanm** [comment]
Considering @zpao's [comment](https://github.com/facebook/react/issues/1657#issuecomment-47708471), should this issue be locked? Or at least, can we update the OP with that information? I'm subscribed to the thread for updates but @zpao's comment is buried (along with the fact that work has already been done) and it's kinda confusing for anybody who hasn't read the entire thread.

**Comment by crenwick** [comment]
@zpao's comment explains the decision on why it is not currently built into react, but is there a better explanation on why an addon doesn't exist?
Is this something that can still be explored?

**Comment by chenyunchen** [comment]
+1 for marker: refx, refy,orient

**Comment by xile611** [comment]
+1 for attributes of text :  rotate, dominant-baseline

<http://www.w3.org/TR/SVG/text.html#TextElementRotateAttribute>

**Comment by polgfred** [comment]
+1 addon

**Comment by conundrumer** [comment]
+1 addon

**Comment by Rev3rse** [comment]
+1 for filter.

**Comment by sirreal** [comment]
[`vector-effect`](http://www.w3.org/TR/SVGTiny12/painting.html#VectorEffectProperty) please

**Comment by JKillian** [comment]
I think people requesting SVG tags/attributes when they happen to need them is a very poor model for React. It's silly that I have to use `dangerouslySetInnerHTML` just to render a working SVG on the page. That being said, here's some of the stuff missing:

*Tags:*
* `feMorphology`
* `feOffset`
* `feColorMatrix`
* `feMerge`
* `feMergeNode`

*Attributes:*
* `filterUnits`
* `stdDeviation`
* `values`
* `in`
* `operator`

and probably lots more in both categories. Those are just some from the SVG code I'm working with.

**Comment by benjeffery** [comment]
+1 for `vector-effect`

**Comment by philihp** [comment]
+1 for `stdDeviation`

**Comment by luke-oneill** [comment]
+1 for a separate and complete React.SVG. I'm loving working with SVG in React so far, but the incompleteness of the support makes it a no go for any semi-complex application.

**Comment by zpao** [comment]
@spicyj has a plan to eliminate the need for a separate config we need to keep updating. Hopefully that will be complete soon. In the mean time, please hold tight.

**Comment by qinyang912** [comment]
+1 for animateTransform

**Comment by okorz001** [comment]
+1 for dominate-baseline (#3199.)

**Comment by spicyj** [comment]
Like @zpao said, we're going to fix this for good so any attributes can be used. Locking this issue until then.

**Comment by gaearon** [comment]
This was fixed in https://github.com/facebook/react/pull/5714.

**Comment by gaearon** [comment]
#5714 was reverted in #6243, and thus we still require an attribute whitelist. The good news, however, is that #6243 contains attributes scraped for MDN so we expect it to cover 95% of the use cases. I read through this whole issue and linked issues and PRs and manually added two missing properties (`focusable` and `vector-effect`) in #6267. I expect these changes to land in v15.

Interestingly, I’m not sure whether the *tag* whitelist is relevant anymore. So far I have been able to use `<marker>`, `<textPath>`, `<feGaussianBlur>` and other tags requested in this issue and in linked PRs without trouble on master. I see that [`fbjs` still maintains an SVG tag whitelist](https://github.com/facebook/fbjs/blob/89ffda59d923183dd34efb2622da0176ccb04d41/src/core/getMarkupWrap.js#L61-L83) and I don’t know the codebase well enough to say why tags missing from it worked for me today, so hopefully @zpao or @spicyj can clarify this, and whether we need to also add the missing tags there, to complement #6243.

I am unlocking this issue because the attribute whitelist is still relevant, but hopefully we will see a lot less requests now that most of the spec actually implemented by the browsers is supported. If something still isn’t supported in the final v15, please let us know here.

**This note does not apply to v15 RC1 which passes all SVG attributes through. We reverted this behavior in #6243 so please use the upcoming RC2, the master, or the final v15 to tell whether the attributes you are interested in are currently supported.**

**Comment by gaearon** [comment]
I noticed that there seems to be quite a lot of confusion about the `xlink:href` attribute. It *is* currently supported but you would need to write it in a different way:

```js
<use xlinkHref="#shape" x="50" y="50" />
```

React will correctly turn that into `xlink:href`, even in 0.14.x. See [this fiddle](https://jsfiddle.net/j825fmtw/) for an example.

**Comment by Arnavion** [comment]
For my use case I needed React to recognize some filter elements like `feFuncR`, specifically their attributes (`slope`, `intercept`, etc). It appears to be fine in 15.0-rc2, but for 0.14.x I worked around it by adding these attributes to the dictionary exported by `react/lib/SVGDOMPropertyConfig` before first importing `react` itself. Eg:

```javascript
// Needed to set correct xmlns on <svg> and to preserve attributes on feFunc*.
// Required for 0.14.x. May become unnecessary with 15.x

var SVGDOMPropertyConfig = require("react/lib/SVGDOMPropertyConfig");

var DOMProperty = require("react/lib/DOMProperty");
var MUST_USE_ATTRIBUTE = DOMProperty.injection.MUST_USE_ATTRIBUTE;

SVGDOMPropertyConfig.Properties.in = MUST_USE_ATTRIBUTE;
SVGDOMPropertyConfig.Properties.intercept = MUST_USE_ATTRIBUTE;
SVGDOMPropertyConfig.Properties.slope = MUST_USE_ATTRIBUTE;
SVGDOMPropertyConfig.Properties.xmlns = MUST_USE_ATTRIBUTE;

var React = require("react");
```

This is obviously a hack but I find it preferable to `dangerouslySetInnerHTML`

**Comment by gaearon** [comment]
While this works it’s not an officially exposed API and may break in any minor or patch release. You can use it but on your own risk. If something is still missing please work with us so we add it. I’m glad to hear you don’t have issues with 15 RC2.

**Comment by Arnavion** [comment]
Yep, absolutely. I'm only using that until 15 comes out of RC status.

**Comment by elrumordelaluz** [comment]
Pretty happy for the (almost) full SVG support in [v15.0](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) but I'm realising that some namespaced attributes like `xmlns` and `xmlnsXlink` couldn't apply when render, and this is ok when showing the `svg` in the browser. 

In case you want to create an `.svg` image those attributes are necessary.

```jsx
ReactDOMServer.renderToStaticMarkup(<MyCustomSVG  />)
```

So doing the code above, wont'n work.

Probably is related on the fact that:

> ...thanks to using `document.createElement`, we no longer need to maintain a list of SVG tags, so any SVG tags that were previously unsupported should work just fine in React 15

and not `document.createElementNS`.

**Comment by gaearon** [comment]
>and not document.createElementNS.

The blog post is a little too simplified, but `createElementNS` is used when we’re under and `<svg>` tag. If this doesn’t happen can you please file a separate issue describing the problem, with a JSFiddle that reproduces it? Thanks!

**Comment by elrumordelaluz** [comment]
Thank you @gaearon. I think it does happen when render the `svg` in browser through `ReactDOM`. Probably the issue is related with `ReactDOMServer`. 

[Here is a pen](http://codepen.io/elrumordelaluz/pen/a2e1bb1eca35a2f49831e8d9a571120c?editors=0010) that shows the rendered `SVG` and the code generated through `renderToStaticMarkup()` where is missing at least `xmlNS`and `xmlnsXlink` attrs.

If is the case I could file this issue separately.

**Comment by zpao** [comment]
Yea, `xmlns` and `xmlns:Xlink` are missing.  https://github.com/facebook/react/pull/6471 has some in progress work to add it.

**Comment by shilpan** [comment]
I still do not see `<animate>` and `<animateTransform>` in the list of supported tags. Is there a reason you chose not to support it?

**Comment by gaearon** [comment]
@shilpan 

All tags are supported now. [The list](https://facebook.github.io/react/docs/tags-and-attributes.html) only tells which tags are supported as `React.DOM.*` factory functions:

>The following SVG elements are supported **in React.DOM.*:**

(emphasis mine)

If you use JSX, you don’t need to worry about this at all—writing `<animate>` and `<animateTransform>` will just work because JSX does not rely on `React.DOM.*` factories.

**Comment by alexjsdev** [comment]
+1 for adding support for `xmlns`.... In the mean time if anyone is interested in a workaround (which I needed to be able to support IE9-11) this is what I came up with:

```javascript
// explicitly build the SVG to be rendered here so we don't lose the NS
const stringifiedSvg = `<svg xmlns="http://www.w3.org/2000/svg" class="svgClass">
                               <use xlink:href="#linkToSymbolId"></use>
			            <svg/>`

return <div dangerouslySetInnerHTML={{__html: stringifiedSvg}}/>
```
