### ISSUE TITLE
[react-hooks/exhaustive-deps] missed warning when passing a function

### ISSUE THREAD

**Issue by whatisaphone** [facebook/react#16573]
**Do you want to request a *feature* or report a *bug*?**

Arguably a **bug** in eslint-plugin-react-hooks

**What is the current behavior?**

The exhaustive-deps rule does not catch the following case:

```js
const FooContext = React.createContext(() => {});

// Meanwhile, somewhere deep in the component tree
function Bar() {
  const foo = useContext(FooContext);
  useEffect(foo, []);
  return <div>A div walks into a Bar…</div>;
}
```

**What is the expected behavior?**

I think the plugin should suggest adding the dependency on `foo`:

```js
useEffect(foo, [foo]);
```

It already makes this suggestion for the verbose form of the code:

```js
// This code:
useEffect(() => foo(), []);
// is fixed to:
useEffect(() => foo(), [foo]);
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- eslint@6.2.2
- eslint-plugin-react-hooks@2.0.1
- react@16.9.0

**Comment by threepointone** [comment]
It's a bit of a niche usecase where a function is used directly as useEffect's callback (consider in your example, that the callback would have no access to state or any local variables.) That said, I can see how it would be useful for the edge cases itself. I think we'd accept a PR for the same.

**Comment by simbathesailor** [comment]
@threepointone : Hey I have made good progress in this. Can I take up this issue?.. I have done the fix , but now I have to give it polishes with test cases.  I will keep it posted here !!. I will try to make it according to existing code standard by this weekend. And we will take it from there !!.

**Comment by gaearon** [comment]
The fact that it doesn't suggest it is a bug.
