### ISSUE TITLE
IE11 polyfill seems to be not working with react-scripts build

### ISSUE THREAD

**Issue by sarathsp** [facebook/react#16583]
Imported below polyfills in the index.js and using react-scripts build for creating the bundle as suggested for fixing the initial page loading issue.
```js
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable'
```
But seems to be not working after the initial page load and throwing invalid object error in console with details like invalid symbol and is happening while doing a `this.props.history.push` method call and an error seems to be occurring from `confirmTransitionTo` method in `history` as anonymous function.

Also using the below browser list
```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all",
      "ie 11"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "ie 11"
    ]
  }
```

Using below version for react/ react scripts/polyfill.
```json
"react-scripts": "^3.1.1",
 "react": "^16.8.6",
 "react-app-polyfill": "^1.0.2",
```

Please let me know if any one else face this similar issues and any working fixes.

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by threepointone** [comment]
I’m going to close this, happy to reopen if you can make a reproducing example on codesandbox or a git repo.
