### ISSUE TITLE
Stucking in an infinite loop when add some breakpoints between  `ReactFiberWorkLoop.js#L876` and `#L891``

### ISSUE THREAD

**Issue by lintuming** [facebook/react#16593]
**Do you want to request a *feature* or report a *bug*?**
maybe a bug
**What is the current behavior?**
In `ReactFiberWorkLoop.js`,if you add some **breakpoint** between line 876 and 891,It seems the condiction in [#L881](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberWorkLoop.js#L881) always pass,and it return `renderRoot` as continuation,which cause an infinite loop.
It seems the  `currentTime` equal to  `expirationTime` if without any breakpoints.

**What is the expected behavior?**
Maybe it's not a bug,it only happens when you add a breakpoint between line 876 and line 891.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.9.0, Chrome

**Comment by lintuming** [comment]
I'm sorry if i can't describe very clearly with my bad english.

**Comment by lintuming** [comment]
It seems same as #15558

**Comment by threepointone** [comment]
Can you explain to me why you need to add breakpoints there? Is this part of your workflow when debugging?

**Comment by lintuming** [comment]
@threepointone No,why I add breakpoints there is because I want to figure out how React reconcile, I guess the part between line 876 and 891 in ReactFiberWorkloop would stuck in an infinite loop when I saw it,which make me a little confuse.But I think I know why now,sorry for taking up your time,i close this issue now.
