### ISSUE TITLE
New plugin not working after change any props in debugger tools

### ISSUE THREAD

**Issue by sagar-k** [facebook/react#16599]
**Do you want to request a *feature* or report a *bug*?**
Having an issue

**What is the current behavior?**
not able to see any rendering after changing any props in debugging tool. and also getting below issue 
![image](https://user-images.githubusercontent.com/7201068/63866449-d7a7f500-c9d0-11e9-80dd-a19d0456711c.png)

Uncaught TypeError: Cannot read property '_reactInternalInstance' of undefined
    at Object.get (react-dom.min.js:formatted:4200)
    at a (react-dom.min.js:formatted:4937)
    at Object.enqueueForceUpdate (react-dom.min.js:formatted:4965)
    at s (backend.js:9)
    at Object.setInProps (backend.js:9)
    at t.<anonymous> (backend.js:1)
    at t.l.emit (backend.js:1)
    at backend.js:9
    at t (backend.js:1)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Reproduce bug.
try to change any dynamic pros in the debugger tools section and you will not able to see any DOM changes

**What is the expected behavior?**

Whenever change any props in debugger tools. react component should be rendered as per it.
It was working fine with previous react developer tools chrome plugin 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am using the below version.
"react": "15.6.2",
   "react-dom": "15.6.2",

**Comment by bvaughn** [comment]
Closing this issue as stale.
