### ISSUE TITLE
logCapturedError ate our error message

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#16605]
**Do you want to request a *feature* or report a *bug*?** **Bug**

**What is the current behavior?** 
![image](https://user-images.githubusercontent.com/5390719/63910087-ee455f00-ca57-11e9-941a-f934d1525f01.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Our application is run in a very complicated environment. It's hard to do that.

**What is the expected behavior?**
I change the bundled file, add `console.error(error)` in `logCapturedError`

And the correct error and it's stack is printed.

![image](https://user-images.githubusercontent.com/5390719/63910242-7461a580-ca58-11e9-9bb8-9e1f8f58c10e.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I'm debugging in Firefox Developement Edition. And the code is running in the WebExtension environment. Please consider if the following code is correct in Firefox
```
// Browsers support silencing uncaught errors by calling
    // `preventDefault()` in window `error` handler.
    // We record this information as an expando on the error.

    if (error != null && error._suppressLogging) {
      if (errorBoundaryFound && willRetry) {
        // The error is recoverable and was silenced.
        // Ignore it and don't print the stack addendum.
        // This is handy for testing error boundaries without noise.
        return;
      }
      // The error is fatal. Since the silencing might have
      // been accidental, we'll surface it anyway.
      // However, the browser would have silenced the original error
      // so we'll print it first, and then print the stack addendum.
      console.error(error);
      // For a more detailed description of this block, see:
      // https://github.com/facebook/react/pull/13384
    }
```

**Comment by threepointone** [comment]
It's hard to comment further without a reproducing example. Could you try to reproduce just the error in a new isolated project, and see if the problem persists?

**Comment by Jack-Works** [comment]
I figured it out. It's a Firefox bug.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1469304

**Comment by Jack-Works** [comment]
manifest.json
```json
{
    "$schema": "http://json.schemastore.org/chrome-manifest",
    "name": "Debugger test",
    "version": "1.5.3",
    "manifest_version": 2,
    "permissions": ["http://example.com/*", "webNavigation"],
    "background": {
        "scripts": ["/background.js"]
    },
    "content_scripts": [{ "matches": ["http://example.com/"], "js": ["/react.js", "/react-dom.js", "/content.js"] }]
}
```

```content.js
function App() {
    throw new Error('Render failed')
}
ReactDOM.render(React.createElement(App), document.body.children[0])
```

**Comment by Jack-Works** [comment]
This bug caused by Firefox will not show error in a content script nither emit a window.onerror event

**Comment by Jack-Works** [comment]
Please consider disabling the "pause on exception" preservation for Firefox content script. (Can be detected by `"browser" in globalThis && globalThis !== window`)
