### ISSUE TITLE
useState update Array but child Component did't rerender

### ISSUE THREAD

**Issue by wangcode** [facebook/react#16615]
**Do you want to request a *feature* or report a *bug*?**

i don't know

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

[https://codesandbox.io/s/gallant-chandrasekhar-p4pvi](url)

**What is the expected behavior?**

I click the "change count" button, count++
I click the "change title" button, title is changed but Child Component is not rerender

**Comment by aweary** [comment]
@wangcode if you pass the same value to a `useState` updater React might bail out of the update, which is whats happening in this case. To get around this you can just create a new `array`, mutate that, and pass it to `setArray`: https://codesandbox.io/s/gifted-cartwright-g1dgn
