### ISSUE TITLE
[ESLint] 'Run on mount' use case for 'exhaustive-deps' lint rule

### ISSUE THREAD

**Issue by dkthehuman** [facebook/react#16625]
I'm having a hard time figuring out how best to resolve the `react-hooks/exhaustive-deps` lint rule when trying to run something only the first time the user sees something and would appreciate some pointers.

Per @gaearon's recommendation in an [older thread about this lint rule](https://github.com/facebook/create-react-app/issues/6880#issuecomment-486875202), I'll try to explain from a user-oriented perspective rather than one that is mount/update-oriented.

## Use Case

When a user initially loads my app, a random element should be generated. There is a button that changes the random element which should be different from the previously generated element.

In my particular application, I'm generating [guitar chords](https://dkthehuman.com/chord-bunny/), but for the sake of simplicity, let's say that we're generating random numbers.

### Setting random element in `useState`

My initial approach was to use the initial state to generate the random number: https://codesandbox.io/embed/generate-rand-num-as-initial-state-mf49x

This works well, but ended up being problematic when I added server-side rendering because there would be a noticeable flicker between the random number in the HTML (generated on the server) and the random number created when the page is loaded (generated on the client).

### Setting random element in `useEffect`

My current approach is to set the initial state to `null` and generate the number when the user first loads the page (on mount) using `useEffect`: https://codesandbox.io/embed/generate-rand-num-as-effect-46cne

This works but triggers the `exhaustive-deps` warning: `React Hook useEffect has a missing dependency: 'changeNum'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

### Potential Solutions

Having read through much of [the feedback thread for this rule](https://github.com/facebook/react/issues/14920), [another discussion about it](https://github.com/facebook/create-react-app/issues/6880), and the [Hooks FAQ](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies), I know that I can wrap `changeNum` into the `useCallback` hook, but I can't help but feel that there must be a better way.

I suspect I may be thinking too imperatively rather than declaratively, but I'm having a hard time figuring out what the idiomatic solution would be here. (If the answer is to just use the `useCallback` hook, so be it.) Any pointers would be greatly appreciated. Thanks!

**Comment by gaearon** [comment]
>This works but triggers the exhaustive-deps warning: React Hook useEffect has a missing dependency: 'changeNum'. Either include it or remove the dependency array react-hooks/exhaustive-deps

I don't see that on CodeSandbox. You are probably using an old version of the plugin.

**Comment by dkthehuman** [comment]
@gaearon Hey Dan, thanks for taking a look. There seems to an inconsistency with CodeSandbox because the problem doesn't appear until you click "Open in Editor" on the top right.

The lint warning shows up for me:
<img width="556" alt="Screen Shot 2019-08-30 at 5 48 44 PM" src="https://user-images.githubusercontent.com/535248/64054895-e4525780-cb4e-11e9-938b-066f99fb44e7.png">

**Comment by threepointone** [comment]
> Setting random element in useState
> My initial approach was to use the initial state to generate the random number: https://codesandbox.io/s/generate-rand-num-as-initial-state-mf49x
>
> This works well, but ended up being problematic when I added server-side rendering because there would be a noticeable flicker between the random number in the HTML (generated on the server) and the random number created when the page is loaded (generated on the client).

I would like to point out that your workaround does not avoid the flicker; in the later version, it'll still show "null" when server rendered, and then flicker in when the effect finally runs in the browser.

**Comment by dkthehuman** [comment]
@threepointone In my actual application, I leave an empty space where the content would render so that elements don't jump around. Filling in a blank spot feels smoother than having stale content flicker out and be replaced by fresh content.

**Comment by dkthehuman** [comment]
@gaearon Hey Dan, would you mind taking another look? I think the issue was closed prematurely.

**Comment by nortonwong** [comment]
Since your initial state is null, you don't need to diff from the previous value.
```js
  useEffect(() => {
    setNum(getRandomNumber());
  }, []);
```

**Comment by dkthehuman** [comment]
@nortonwong Hey Norton, thanks for taking a look. Your solution looks great for the CodeSandbox, but unfortunately that just showed me that I made the CodeSandbox overly simple. In my actual application, generating the random element always depends on some other piece of state. As a result, the following approach would still trigger the exhaustive-deps warning:
```javascript
useEffect(() => {
    setNum(getRandomNumber());
  }, []);
```

I've updated the CodeSandbox to better reflect my actual situation if you'd like to take another look!

**Comment by nortonwong** [comment]
The purpose of `exhaustive-deps` is to make captured variables explicit. You could `useRef` to tell the linter you intend to capture values.
  ```js
  const args = useRef([num, maxNum]);
  useEffect(() => {
    setNum(getDifferentNum(args.current));
  }, []);
```
or possibly
  ```js
  const changeNumWithInitialValues = useRef(changeNum);
  useEffect(() => {
    changeNumWithInitialValues.current();
  }, []);
```

**Comment by dkthehuman** [comment]
Thanks, Norton. I was hoping there was an approach that wouldn't require memoizing the function with `useCallback` or storing the function as a closure with `useRef` just so I can call it on the initial page load, but perhaps there isn't a better way. Appreciate you taking the time to help!

@gaearon If you get a chance to look at this, I'd be curious whether this is the approach you'd recommend as well. Thanks!
