### ISSUE TITLE
Limitations of context API compared to legacy implementation

### ISSUE THREAD

**Issue by use-strict** [facebook/react#16634]
This isn't technically a bug, but a limitation of the new context API implementation and also a question on whether this should be fixed by React, or if I should implement a custom, in-house, solution instead.

I have a fairly "edgy" use-case with a component library that provides several parent-child components (e.g. tabs, accordions etc.). This looks like a standard context use-case so far. However, the library has to work in a plugin-based environment, meaning the parent and child components are rendered by two completely independent apps (host app and plugins respectively).

Example:
```jsx
<Accordion> <!-- provided by host app -->
    <!-- provided by separate plugin -->
    <AccordionItem label="item 1">Content</AccordionItem>
    //...
</Accordion>
```

Thus, two separate instances of the component library are created, one for the host app and one in the plugin scope, but they still have to communicate with each other, behind the scenes, while keeping it transparent to the user.

This worked seamlessly with the legacy context API, but now with the new one, it breaks. That is because `React.createContext` returns an object that now has to be explicitly shared between the components, by means of an import. But because of the decoupled architecture of the app, and multiple instance of the library being used, this seems impossible to do.

As stated in the docs, the legacy context API is deprecated and will be removed in future versions of React (17+?), so I'd like to avoid being stuck on React 16, when that happens.

**Comment by threepointone** [comment]
>  But because of the decoupled architecture of the app, and multiple instance of the library being used, this seems impossible to do.
Could you describe this a little more? I would suggest exporting the needed context on a module that's used by both the host app and the child component. Do you have more details on your usage?

**Comment by use-strict** [comment]
We have a reusable library with two components: `Accordion` - the parent, and `AccordionItem` - the child.

We then have the consumers: the main/host app and its plugins, which are separate JS bundles provided by 3rd party developers. Both host and plugins contribute to the layout of the page with modules (React components) that are nested via placeholders. Nesting is possible between host and plugin, or between two plugins. The example below is an oversimplification:

```jsx
// host
<Content>
    <Accordion>
        { this.props.children }
    </Accordion>
</Content>

// plugin - injected into the host component's children
<>
    <AccordionItem label="Item 1">Content</AccordionItem>
    <AccordionItem label="Item 2">Content</AccordionItem>
</>

```

The wiring is done by an engine, which I won't detail right now. The important facts are:
- The engine has no knowledge of any component libraries used in host or plugins. Those are implementation details.
- The usage of Accordion/AccordionItem is purely an agreement between two plugins or the host and a plugin.
- The context sharing between parent and child accordion components should be something intrinsic to the component library. The consumer is not aware, nor has the possibility of manually passing that context around.
- Because we have two separate bundles, each uses its own instance of the component library (there are different JS objects). If we were to use `React.createContext` in the library, that object being returned would not be shared between parent and child because of the above.

**Comment by threepointone** [comment]
Thanks for the details! Some more questions:
- How are the bundles generated? I ask, because clearly some modules are being shared across bundles in some fashion (for example, React itself). I assume you use webpack or some other bundler. 
- Depending on the answer to that, I'd ask then whether you could reference the same module from `Accordion` and `AccordionItem` (say, `AccordionContext`, or `LibnameContext`), and make sure `AccordionItem` excludes that module from its bundle (Using webpack's `externals`, I would guess https://webpack.js.org/configuration/externals/)

**Comment by gaearon** [comment]
>But because of the decoupled architecture of the app, and multiple instance of the library being used, this seems impossible to do.

Technically, the old context API was essentially sharing a global string namespace. You can emulate the same by ... using globals.

```js
window.MyContext = window.MyContext || React.createContext();
```

Then use it.

Yes, it's not pretty, but *it's effectively what you were relying on anyway*.

Ideally, you'd share a concrete object instead of a global namespace. It's always possible but you need to figure out how to do it in your setup.
