### ISSUE TITLE
can't save settings in react devtools forever

### ISSUE THREAD

**Issue by haritonasty** [facebook/react#16639]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when I clicked "Okay"  - I can work, but after reload page - it's still showing. 
Also when I tried to change settings (theme, etc.) in plugin - it's also reset to default after reload
that behavior for all urls 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
![image](https://media.giphy.com/media/KB0s8VbkKDX77DsMx9/giphy.gif)

**What is the expected behavior?**
save settings in dev tools

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
chrome OS, chrome 76.0.3809.102

**Comment by threepointone** [comment]
Question: Do you see the "Welcome to the new React Devtools" popup every time you use it? Or had you freshly installed it before making this gif?

**Comment by haritonasty** [comment]
@threepointone  every time, yes

**Comment by threepointone** [comment]
That's odd behaviour. //cc @bvaughn any idea why this could happen?

**Comment by threepointone** [comment]
Alright, this appears to be the same issue as  https://github.com/facebook/react/issues/16475 with a workaround here - https://github.com/facebook/react/issues/16475#issuecomment-523400934 

Closing this as a dupe https://github.com/facebook/react/issues/16475
