### ISSUE TITLE
Can't use instance values without refs

### ISSUE THREAD

**Issue by ysulyma** [facebook/react#16630]
I am experimenting with migrating some of my class components to Hooks. My use case is explained in detail [here](https://stackoverflow.com/questions/57722818/idiomatic-react-with-heavy-dom-manipulation-mathjax), but I can quickly explain the idea.

I have a class component `<MJX>` which exposes a `.ready` Promise. Since `<MJX>` produces a `<span>` element, I guess I can use the `useImperativeHandle` hook to attach `.ready` to the ref I use for the `<span>`. This is no problem.

However, I also have a class component `<RenderGroup>` which uses `React.Children` to collect the `.ready` Promises from all its `<MJX>` descendants, and exposes `Promise.all` of that array of Promises as its own `.ready` value. Since `<RenderGroup>` does not produce any markup of its own, and you can't place refs on `<React.Fragment>`, I don't see how to use`useImperativeHandle` here: there's nowhere to attach the ref.

Here is the relevant code:

```tsx
export class RenderGroup extends React.Component {
  private promises: Promise<void>[];

  ready: Promise<void>;

  componentDidMount() {
    this.ready = Promise.all(this.promises).then(() => {});
  }

  render() {
    this.promises = [];

    return recursiveMap(this.props.children, node => {
      if (shouldInspect(node)) {
        const originalRef = node.ref;
        return React.cloneElement(node, {
          ref: (ref: MJX) => {
            if (!ref) return;
            this.promises.push(ref.ready);
            if (typeof originalRef === "function") {
              originalRef(ref);
            } else if (originalRef && typeof originalRef === "object") {
              (originalRef as React.MutableRefObject<MJX>).current = ref;
            }
          }
        });
      }

      return node;
    });
  }
}

function shouldInspect(node: ReactNode): node is React.ReactElement & React.RefAttributes<MJX> {
  return React.isValidElement(node) && typeof node.type === "function" && node.type.prototype instanceof MJX;
}

export function recursiveMap(
  children: ReactNode,
  fn: (child: ReactNode) => ReactNode
) {
  return React.Children.map(children, (child) => {
    if (!React.isValidElement(child)) {
      return child;
    }

    if ("children" in child.props) {
      child = React.cloneElement(child, {
        children: recursiveMap(child.props.children, fn)
      });
    }

    return fn(child);
  });
}
```

**Comment by kunukn** [comment]
You already have a stackoverflow question and an answer.
https://stackoverflow.com/questions/57722818/idiomatic-react-with-heavy-dom-manipulation-mathjax

One answer mentions Context API as an approach which sounds reasonable to me.

Maybe take the discussion over there?

**Comment by threepointone** [comment]
Closing this since it isn’t a bug or feature request, and the discussion probably does belong there.
