### ISSUE TITLE
Relying on console.log native string substitution interferes with typical patched console logging

### ISSUE THREAD

**Issue by JasonKleban** [facebook/react#16637]
Seems to me that this will be a hairy one to fix.

The warning/error messages emitted from React often rely on string substitution of the native console.log function to give necessary location of the problem.  But when the console.log functions are patched in applications to redirect messages to the server for logging, say, in json format to a file, the templates' string substitution parameters are lost.  ex. `Warning: Each child in a list should have a unique "key" prop.%s%s` which isn't very helpful to see in the log in a large project with many developers.

I believe this could be easily addresses in the logger patch if there were a reliable way to assign the output of native string substitution to a new javascript string (so that the full string message could be wrapped in json metadata AFTER the substitution), but this native string substitution doesn't seem to be available to javascript and there's no way to get resulting string.  We could add a javascript implementation of string substitution such as https://github.com/anseki/console-substitute, but there's [not much of a spec](https://developer.mozilla.org/en-US/docs/Web/API/console#Using_string_substitutions).

Could these messages be templatized in React in a different way?

**Comment by bvaughn** [comment]
> But when the console.log functions are patched in applications to redirect messages to the server for logging, say, in JSON format to a file, the templates' string substitution parameters are lost.

Why are these parameters "lost"? String substitutions are passed as separate args to the console method, sot he patched method should have access to them also.

**Comment by gaearon** [comment]
If you must, you can always substitute them yourself.

```js
console.error = function(format, ...args) {
  let argIndex = 0;
  const message = format.replace(/%s/g, () => args[argIndex++]);
  // ...
};
```

In fact, passing `%s` gives you *more* information in that case because it lets your server logging group warnings by type and collect stacks (or other information) as separate columns for aggregation.

Hope that helps.
