### ISSUE TITLE
How can i hide eslint warning 'useMemo has missing dependencies'?

### ISSUE THREAD

**Issue by huurray** [facebook/react#16641]
hello
simply, i'd like to hide  eslint warning message from 'useMemo'
i can use   // eslint-disable-line   // eslint-disable-next-line in useEffect.
but i have no idea how i can hide it in ***useMemo***
please help me!!

this is my code example

```javascipt
<div>
      {useMemo(
        () => (
          <ChatTextarea
            placeholder="text.."
            text={text}
          />
        ),
        [text]
      )}
</div>
```

**Comment by threepointone** [comment]
I tried a version of your code and it didn't show me any earning/error, so I cannot comment further. Please use https://codesandbox.io to make an example that shows this issue.
