### ISSUE TITLE
[Dev Tools] Chrome component console errors get output from "backend.js"

### ISSUE THREAD

**Issue by natew** [facebook/react#16649]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When I get a component stack trace, the log trace comes from the dev tools extension:

![image](https://user-images.githubusercontent.com/12100/64210499-4d401500-ce58-11e9-87f5-b0c9115fe62f.png)

**What is the expected behavior?**

I use that trace usually to click and set a debugger so I can debug some React internals.

**Comment by gaearon** [comment]
Click on the message and the arrow on the left should expand. It gives you the JS stack.

**Comment by natew** [comment]
Yea, just wondered if this was intentional or avoidable, I believe without extension you get that two steps faster. Not a big one.

**Comment by bvaughn** [comment]
Check out the "Component Stacks" blurb [from the changelog](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#component-stacks):

---

#### Component stacks

React component authors have often requested a way to log warnings that include the React ["component stack"](https://reactjs.org/docs/error-boundaries.html#component-stack-traces). DevTools now provides an option to automatically append this information to warnings (`console.warn`) and errors (`console.error`).

![Example console warning with component stack added](https://user-images.githubusercontent.com/29597/62228120-eec3da80-b371-11e9-81bb-018c1e577389.png)

It can be disabled in the general settings panel:

![Settings panel showing "component stacks" option](https://user-images.githubusercontent.com/29597/62227882-8f65ca80-b371-11e9-8a4e-5d27011ad1aa.png)

---

You can turn this off in Settings if you don't want it. :smile:

We've started a dialog about ways that we could perhaps implement this sort of functionality in a less invasive way but they're still ongoing:
https://github.com/whatwg/console/issues/163

**Comment by natew** [comment]
Missed that, thanks!

**Comment by vdh** [comment]
This also has the very nasty side effect of causing the Chrome dev tools to hang if you try to put in a breakpoint to find out where exactly this error comes from, because the `backend.js` is (now?) minified 😢 

Maybe include source maps for `backend.js` if the console stack traces are going to get hijacked?

**Comment by bvaughn** [comment]
I'm not sure I understand - `backend.js` has always been  minified.

Either way, a minified JavaScript file should not cause Chrome to hang on a breakpoint.

**Comment by vdh** [comment]
@bvaughn It does if for example you put a breakpoint on line 6 and that minified line contains the entire contents of the file.
