### ISSUE TITLE
React devtools always launches in Chrome

### ISSUE THREAD

**Issue by nextriot** [facebook/react#16645]
Hi.

I have the extension installed on both chrome and firefox. My default browser is firefox. Each time I try to debug a react native app remotely it launches chrome to use the debugger there.

How do I change the default browser for devtools to Firefox?

**Comment by bvaughn** [comment]
This doesn't actually have any thing to do with the React DevTools browser extension, although I can see why you might think it did!

The "Debug JS Remotely" option you're referring to is built into React Native. I think you might want to check out [the `REACT_DEBUGGER ` option in the React Native docs](https://facebook.github.io/react-native/docs/debugging#debugging-using-a-custom-javascript-debugger) for what you're looking for.
