### ISSUE TITLE
Use symbols for SchedulerPriorities

### ISSUE THREAD

**Issue by tstreamDOTh** [facebook/react#16648]
**Do you want to request a *feature* or report a *bug*?**
Enhancement/Refactoring

**What is the current behavior?**

Constants being used to define priorities
https://github.com/facebook/react/blob/master/packages/scheduler/src/SchedulerPriorities.js

**What is the expected behavior?**

Symbols to be used for defining priorities

**Comment by tstreamDOTh** [comment]
I would like to pick this up

**Comment by threepointone** [comment]
I don't think we want to do this any time soon, but I could be wrong. @acdlite, would you concur? 

Do you have a specific usecase for this, @tstreamDOTh? 

Closing this issue, but happy to reopen if I'm wrong.
