### ISSUE TITLE
[Feature Request] Metadata for which props were inherited from default props.

### ISSUE THREAD

**Issue by kalbert312** [facebook/react#16655]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
It's impossible/super inefficient to figure out which props on a child component were explicitly defined (such that `prop in props` is true) vs which were inherited by default props.

**What is the expected behavior?**
It would be helpful to have some metadata on a child that specifies if a prop was merged in from default props. A simple true / false would suffice. This would be useful to have for a very specific issue I'm facing with using `recharts`. It has a super nice declarative JSX approach but based on the way it's designed, it has some limitations. Some child components (XAxis for instance) are tightly coupled with their parent component (BarChart, etc). Long story short, creating proper HOCs on them is basically impossible due to defaultProps interference. I'm creating a wrapper for the top level component (BarChart) that provides additional default props to its child components (theme context, etc). I have the following code:
```typescript
const BarChart: React.FC<BarChartProps> = fixWrapperFC(BarChartBase, (props) => {
	const { children, ...rest } = props;

	const theme = React.useContext(ThemeContext);

	return (
		<BarChartBase {...rest}>
			{React.Children.map(children, (c: any) => {
				if (!c || !c.type || !c.type.displayName) {
					return c;
				}
				const displayName = c.type.displayName;
				if (displayName === "XAxis") {
					return React.cloneElement(c, { ...xAxisProps({ theme, ...c.props }), });
				}
				return c;
			})}
		</BarChartBase>
	);
});
```
The problem is that `c.props` already has default props, and the only way to accomplish what I'm doing is to subtract off default props with some type of equality algorithm, but my first thought is that it's ugly (the code I pasted above is ugly too, but the exterior would be nice and clean).

I suppose the real problem is the limitations on how this library is designed and that it probably indulges anti-patterns to achieve it's declarative style. The real solution would likely be to rewrite it to support HOCs, however, I'd imagine at some point in the react code, `Object.keys(passedInProps)` and/or `Object.keys(defaultProps)` is somewhat cheaply available and could be tacked onto the child object?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.9

**Comment by threepointone** [comment]
> I suppose the real problem is the limitations on how this library is designed and that it probably indulges anti-patterns to achieve it's declarative style.

That's the problem though, isn't it? And it would be odd if React exposed data that encouraged this pattern. 

You could perhaps rewrite it to *not* use defaultProps, and instead replicate defaultProps functionality *inside* the child component when those props are being used when rendering. 

(I personally stay away from defaultProps myself, and rely on type systems like flow, and javascript default arguments)

This is more of a usage question, so I'm going to close it. but thank you for checking!
