### ISSUE TITLE
DevTools: Allow editing props that weren't passed initially

### ISSUE THREAD

**Issue by brunolemos** [facebook/react#16651]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently we can only edit the props that were passed to the component:

![image](https://user-images.githubusercontent.com/619186/64222327-15f85500-cea6-11e9-9420-59ae25017fe4.png)

**What is the expected behavior?**

But the component has other props (e.g. `loading`, `type`, etc) that weren't passed to this specific instance. And we should be able to play with them in the devtools similar to how Chrome allow us to add new css:

![Kapture 2019-09-03 at 23 55 57](https://user-images.githubusercontent.com/619186/64222438-72f40b00-cea6-11e9-92f8-2b5b72ab1b43.gif)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Latest

@bvaughn

**Comment by hristo-kanchev** [comment]
We are adding this as part of #16484 👍 

We can mark this as duplicate.

**Comment by brunolemos** [comment]
Cool! Thanks.
