### ISSUE TITLE
Improve form inside of form error message

### ISSUE THREAD

**Issue by yazaddaruvala** [facebook/react#1665]
http://jsfiddle.net/U26kq/
Take a look at the error in the console. Its a terrible error "Uncaught object".

At least if you ask it to render a form inside a form from the console it will give you
```
Error: Invariant Violation: findComponentRoot(..., .2): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables or nesting <p> or <a> tags. Try inspecting the child nodes of the element with React ID ``.
```

Which, while being better is not really helpful in this case.

**Comment by spicyj** [comment]
This was fixed in Chrome. Also I added a better warning for this particular problem.
