### ISSUE TITLE
Can you provide the ability to compile components into webcomponents? Is cross-framework a future trend? I hope that the component ecosystem can be shared in other front-end frameworks.

### ISSUE THREAD

**Issue by masx200** [facebook/react#16668]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

Can you provide the ability to compile components into webcomponents? Is cross-framework a future trend?
I hope that the component ecosystem can be shared in other front-end frameworks.

能否提供把组件编译成webcomponents的功能？跨框架组件是未来的趋势吗？
希望可以在其他前端框架中共享组件生态。

### What does the proposed API look like?
```js

import {transformToWebcomponents} from "react"

import mycomponent from "./mycomponent.jsx"

const MyElement=transformToWebcomponents(mycomponent)

window.customElemnt.define('my-element', MyElement)
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by threepointone** [comment]
We have a docs page that talks both about using React inside web components, as well as using web components in React https://reactjs.org/docs/web-components.html Hope that helps!
