### ISSUE TITLE
Rerender issue

### ISSUE THREAD

**Issue by surendragalwa111** [facebook/react#16670]
Here is my small problem for you to solve.
Here is the code snippet:- https://github.com/surendragalwa111/jsmpeg-player-canvas/blob/master/src/App.js
Would you tell me that why my canvas doesn't render when I check my checkbox 2nd time??
(I know destroy() removing it) BUT render should bring it back since I'm updating state and render method is getting called again.
Thanks.

**React version: 16**

**Comment by threepointone** [comment]
Seems fine to me, I'd imagine it could be a problem with the video player package. Could you try adding 
```jex
key={this.state.playVideo ? 'showVideo' : 'hideVideo'}
```
to the `canvas` element just to make sure a fresh canvas element is created between runs as well? If that doesn't fix it, I'd recommend to file an issue with the video player library.

**Comment by threepointone** [comment]
I'm closing this since it doesn't seem related to React, but happy to discuss if you have any new information.

**Comment by surendragalwa111** [comment]
The above solution doesn't work.I tried providing a key too.
It throws following error:
``
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at removeChild
``

**Comment by surendragalwa111** [comment]
Here is [an issue](https://github.com/facebook/react/issues/14434) created regarding above error

**Comment by threepointone** [comment]
Reopening to investigate later next week, but I still think it’s not a react issue. The linked issue has to do with portals, not sure how it relates to your issue.

**Comment by threepointone** [comment]
Ok, now I'm certain. The video player library you're using is manually removing the `canvas` element (https://github.com/cycdpo/jsmpeg-player/blob/master/src/lib/video-element.js#L242-L244), which makes it unfriendly to React, since React thinks that it owns the element. 

You've already posted an issue on the player's page https://github.com/cycdpo/jsmpeg-player/issues/16 I recommend you follow up there. 

Closing this issue.

**Comment by threepointone** [comment]
A workaround would be to manually mange the canvas element, but creating it and attaching it in componentDidMount(), and recreating it on toggling the player. Would that work?

**Comment by surendragalwa111** [comment]
It won't. Because this library emits an event when as play/render the video on the canvas. This event deletes canvas everytime whenever react re-render it. 

Sadly, this jsmpeg-player library doesn't remove/unregister the above event when we destroy the player instance.

**Comment by surendragalwa111** [comment]
Is there any way to unregister only player events on componentWillUnmount() ?
