### ISSUE TITLE
DevTools: Uninitialized context is displayed as an empty object

### ISSUE THREAD

**Issue by micnic** [facebook/react#16679]
When inspecting a component that is missing `context` it is displayed as an empty object, meanwhile if the `state` is not initialized it is not displayed at all, for no `props` it is displayed the string `None`. In my humble opinion it is misleading that no context is displayed as an empty object.

**Comment by bvaughn** [comment]
Will be resolved by #16617

**Comment by micnic** [comment]
@bvaughn great, thanks for adding this issue to the PR.
