### ISSUE TITLE
`componentDidPropsUpdate` and `componentDidStateUpdate` ???

### ISSUE THREAD

**Issue by mohamedatef98-lincx** [facebook/react#16674]
Why not have two different additional lifecycle hooks, which they should work exactly like `componentDidUpdate` but each one for each type of update method
one for state update `componentDidStateUpdate(prevState)`
one for props update `componentDidPropsUpdate(prevProps)`

**Comment by threepointone** [comment]
Do you have a specific usecase for this? What bugs does it fix, or what new capability does it enable? This might be a better fit for https://github.com/reactjs/rfcs tbh.
