### ISSUE TITLE
class render another type

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#16683]
**Do you want to request a *feature* or report a *bug*?**
*feature* 

now
```
class Hello extends React.Component {
  render() {
    return <div>Hello</div>
  }
}
```

feature
```
class Hello extends React.Component {
  render = <div>Hello</div>
}
```

**Comment by threepointone** [comment]
Hi, thanks for your suggestion?

What is your usecase? How is this better/worse than what we currently have? This uses initialiser syntax for js; how would the component behave on It is not clear from your description what the motivation is for this.

Closing because of lack of information.
