### ISSUE TITLE
Troubleshooting instructions link update

### ISSUE THREAD

**Issue by tessawiedmann** [facebook/react#16690]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Link to troubleshooting instructions in the devtools extension disabled popup is outdated. It is pointing [here](https://github.com/facebook/react-devtools/blob/master/README.md#the-react-tab-doesnt-show-up) which is redirecting [here](https://github.com/facebook/react).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://github.com/facebook/react/blob/master/packages/react-devtools-extensions/popups/disabled.html
Link needs to be updated- not sure what the correct link is

**What is the expected behavior?**
https://github.com/facebook/react/blob/master/packages/react-devtools-extensions/popups/disabled.html
Link needs to be updated- not sure what the correct link is

**Comment by bvaughn** [comment]
Should be pointed here:
https://github.com/facebook/react/tree/master/packages/react-devtools

**Comment by gejimayu** [comment]
i think this issue should be closed
