### ISSUE TITLE
How can I get DOM on the React Hook?

### ISSUE THREAD

**Issue by karmiy** [facebook/react#16699]
In the class component，we can use ReactDom.findDOMNode(this) to get DOM element:

class Collapse {
    componentDidMount() {
        ReactDom.findDOMNode(this) ;
    }
    return this.props.children;
}

But how can I get it in React Hook without 'this';

**Comment by Dergash** [comment]
Hello @karmiy! Accessing DOM elements of function components is handled with refs. You should look into [useRef](https://reactjs.org/docs/hooks-reference.html#useref) hook and [Forwarding Refs](https://reactjs.org/docs/forwarding-refs.html) article for more info.

**Comment by karmiy** [comment]
Thanks for your answer!
I know useRef hook and Forwarding Refs.
I may not have expressed it well, but what I want to know is, in this case, How do I get the DOM of the collapse panel component instance itself in function component:

function Collapse(props) {
    useEffect(() => {
        // ... I want to get my own DOM here
    })
    return props.children;
}

**Comment by karmiy** [comment]
I don't want to add any extra elements like this:

function Collapse(props) {
    const ref = useRef(null);
    useEffect(() => {
       console.log(ref.current);
    })
    return (
        <div ref={ref}>
            {props.children;}
        </div>
    )
}

I don't want to put this DIV element on the outside.
Only return props.children

**Comment by Dergash** [comment]
I think you will be interested in https://github.com/reactjs/rfcs/pull/97 then, it's a proposal about fragment references which specifically allows you to avoid introducing wrapper containers.

I also have a [code sample](https://codesandbox.io/s/magical-blackburn-845po?fontsize=14) for you, 
it shows how to pass a reference to your props.children without extra DOM wrappers, but I agree that is might be not sufficient for your specific use case.

**Comment by threepointone** [comment]
I'm closing this since it isn't a bug or feature request per se, but feel free to carry on the conversation. I would also recommend using one of our community resources https://reactjs.org/community/support.html.

**Comment by karmiy** [comment]
Now it seems that ref cannot be used in \<Fragment> like:
\<Fragment ref={fragmentRef}>
    ...
\</Fragment>

**Comment by Dergash** [comment]
That is why I also provided a link to RFC about Fragment refs :)
Anyway, you use Fragments to avoid wrapper element, but if you don't have a wrapper, what element are you trying to get then? findDOMNode gives you a first element, and you could recreate this behavior with method from the code sample

**Comment by hengkx** [comment]
Is there a better solution？
