### ISSUE TITLE
default props = {}

### ISSUE THREAD

**Issue by qq645381995** [facebook/react#16697]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Infinite loop
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/stoic-fermi-yb4ur
**What is the expected behavior?**
There are no good coding specifications
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Dergash** [comment]
Hello @qq645381995! I don't think it's a bug, as your example demonstrates the default object is 
 recreated on every render and useEffect will cause an infinite loop when dependent on that object. Your example also have a correct solution to this problem - to hoist empty object outside of component.
Do you have something specific in mind?

**Comment by qq645381995** [comment]
no , thx

**Comment by Ponderchan** [comment]
nah.. i've been deleting facebook for a long time and i was a totally
mess-up /  full of shitty ads and groups/

so for me there is no bug and problem.

good day
