### ISSUE TITLE
React Hooks useEffect issue. Using useEffect inside a function.. Error on some function names.

### ISSUE THREAD

**Issue by gerardsegismundo** [facebook/react#16704]
![image](https://user-images.githubusercontent.com/30321279/64500996-7572ae00-d274-11e9-8a0e-654b15868c7d.png)

-  Line 44:  React Hook "useEffect" is called in function "displayNoneOnAdmin" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks.

![image](https://user-images.githubusercontent.com/30321279/64501097-cb475600-d274-11e9-9b31-521bf5042b75.png)

Using lowercase as a function name causes an error? This is a bug right?
As you can see, I alse used camel case in the previus function(useOutsideClick)

**Comment by threepointone** [comment]
By convention, hooks start with the word ‘use’. For example, calling that function ‘useDisplayNoneOnAdmin’ should remove the error you’re seeing. 

(The reason the error gets silenced when you use a capitalised function, is that the linter thinks it’s a component, which also allows hooks to be used in its body. I don’t think you meant to define a component either there though?)

Closing this issue, happy to reopen if I misunderstood.
