### ISSUE TITLE
useEffect with react proxy resulting in react page request going to api server

### ISSUE THREAD

**Issue by gsinghab2** [facebook/react#16706]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I am user react proxy in development to route api request to jsonserver. When using useEffect to fetch initial data for a page, I see a second page request initiated by react-dom.development.js that instead of going to react app is received by jsonserver which hangs till browser terminate connection. See screenshot below. 
![image](https://user-images.githubusercontent.com/40739654/64505468-96012f00-d299-11e9-855c-94405208e198.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: 16.8.6
react-dom: 16.8.6

**Comment by gsinghab2** [comment]
![image](https://user-images.githubusercontent.com/40739654/64505454-8386f580-d299-11e9-8ae3-0bfc15355f20.png)

**Comment by threepointone** [comment]
This doesn’t seem to be a react related issue, did you mean to post it in https://github.com/facebook/create-react-app/issues? I’d also recommend sharing a reproducing example, either on codesandbox or as a git repo that can be installed locally for debugging. 

Closing this issue, happy to reopen if there’s a reproducing example, and an indication that this is a react specific problem.
