### ISSUE TITLE
`useEffect()` not working correctly on `codepen.io`.

### ISSUE THREAD

**Issue by catamphetamine** [facebook/react#16702]
In my app there's a component called `SortableList` that is a drag'n'drop list.
It works.
I created a `codepen.io` with it for a small demo but it doesn't work there.
I debugged a bit with `console.log()` and seems like `useEffect()` is not being run after a state property changes.
https://codepen.io/catamphetamine/pen/qBWxEQX

The code is:

```js
const [dragging, setDragging] = useState()
const onDragStart = useCallback(() => {
  setDragging({ ... })
}, [])
console.log('In render(): `gragging` is', dragging)
useEffect(() => {
  console.log('In useEffect(): `gragging` is', dragging)
}, [dragging])
```

The console output is:

```
"In render(): `dragging` is" undefined
"In useEffect(): `dragging` is" undefined
"In render(): `dragging` is" Object { ... }
```

`useEffect()` triggers right before the new `dragging` is set for some reason.
Seems like a `codepen.io` bug.
What do you think?

cc @CodePen

**Comment by threepointone** [comment]
afk right now, but I noticed a problem: in pen settings > javascript, could you use the 16.9.0 versions for both react and react-dom, and try again? react-dom points to 16.8.6 in your example. 

I’ll investigate the details of your bug in a while if that doesn’t help, cheers

**Comment by catamphetamine** [comment]
@threepointone Indeed, `react` and `react-dom` versions turned out to be different.
For some reason CDN.js can't find `react-dom@16.9.0`.
I've changed them both to `16.8.6` and it works.
Thanks.

**Comment by threepointone** [comment]
Huh, it's odd that cdnjs isn't seeing react-dom 16.9.0. I'll try to reach out separately.
