### ISSUE TITLE
[new feature] support array in the className

### ISSUE THREAD

**Issue by coppyC** [facebook/react#16705]
I konw the classnames package can resolve the problem,
but I want react support this by default without classnames package.

classnames is good, but when I want to use it, I should type a long name,
and the mostly time, I don't have installd it, but I need to do a little code to merge classname to install it.

and a little different to classnames
* className can accept a array (any[]), not support object.
* className still accept a string

```js
<div className={['a', 'b']}></div>
```
to 
```js
<div className="a b"></div>
```

and filter the string item to be the className
this can do some conditions, like jsx (true && <div></div>)
```js
<div className={[
  'a b c',
  true && 'd',
  false && 'f',
  null && 'g',
  0 && 'h',
  undefined && 'i',
]}></div>
```
to 
```js
<div className="a b c d"></div>
```

**Comment by threepointone** [comment]
Thank you for the suggestion, but I’m afraid  it’s highly unlikely we’ll do this any time soon. Using the ‘classnames’ package is our recommended workaround if you need this.
