### ISSUE TITLE
Sites can detect when you have installed React Developer Tools

### ISSUE THREAD

**Issue by jordyvandomselaar** [facebook/react#16710]
Not sure how, but websites can detect usage of React developer tools. Example: https://smallpdf.com

SmallPDF will show you a chatbot asking you to join their team if you have React developer tools installed in your browser. Although smart, this is also creepy.

I tested my theory by uninstalling React developer tools after which the chat bot did not appear.

**Comment by liady** [comment]
Seems like they're looking for `window.__REACT_DEVTOOLS_GLOBAL_HOOK__`:

in *https://smallpdf.com/build/landing.js*:

```javascript
function b(n) {
        return ![s.s, s.d, s.A, s.D, s.L].includes(l.h(n)) && i.i(n) && (void 0 !== window.__REDUX_DEVTOOLS_EXTENSION__ || void 0 !== window.__REACT_DEVTOOLS_GLOBAL_HOOK__) && (e = "frontend", null == v.b("com.smallpdf.bot.".concat(e))) && !h(n);
        var e
    }
    var g = function(n) {
            return i.A(n) ? null : a.n(n, {
                frontendBot: b,
                chrome: p
            })
        },
       ...
        M = r.createElement,
        z = Object(x.keyframes)(["0%{opacity:0;}100%{opacity:1;}"]),
        A = x.default.div.withConfig({
            componentId: "rvu14i-0"
        })(["", " position:fixed;z-index:", ";background-color:white;left:30px;bottom:30px;", ";"], E.lb, E.Vb, function(n) {
            return n.withAnimation && Object(x.css)(["animation:", " 0.2s ease-in-out;"], z)
        });
```

This seems to be intentionally exposed on the window (at least for the previous versions)
(From *http://iamdustan.com/2016/02/19/react-devtools-renderer-integration/*):
![image](https://user-images.githubusercontent.com/7003853/64530822-b28f7c80-d316-11e9-9416-db3e90d9c3c9.png)

I don't know if it's still needs to be exposed ,though.

**Comment by threepointone** [comment]
There's no workaround we can provide here; unless someone can suggest a better method of integrating React with its Devtools. There's no real security risk though, so it should be alright. 

I'm closing this since it isn't a bug/feature request, but I'll be happy to reopen if it's an actual problem. 

I'd recommend also asking SmallPDF to not be so aggressive :)
