### ISSUE TITLE
Feature Request: Lazy evaluation of useEffect dependencies.

### ISSUE THREAD

**Issue by Izhaki** [facebook/react#16718]
# Current Behaviour 

The dependencies to `useEffect` are given as an array:

```js
useEffect(
  () => { ... }
  [deps],
);
```

So they are evaluated as soon as the hook is declared.

# Desired Behaviour 

The dependencies can also be given as a function, so these can be evaluated *after the children have been rendered*:

```js
useEffect(
  () => { ... }
  () => [deps],
);
```

# Rationale

Sometimes an effect in an ancestor is conditional on its descendants changing. Phrased alternatively, sometimes the effect dependencies of an ancestor are those of its dependents. 

But if we are to compose the descendants (via the `children` prop), the ancestor has no knowledge  of the descendants' dependencies.

# Simple Example (SVG)

*Note: This is ultra-simplified example and an ultra-specific case of a generic behaviour/mechanism.*

## Result

![image](https://user-images.githubusercontent.com/880132/64571118-b8a74c80-d35a-11e9-9a28-754ad9f7293e.png)

## Code

Essential code only, removing HOCs and props:

```js
<Hexagon>
  <Text value="Text"/>
</Hexagon>
```

## Constraints

- BBox = BoundingBox
- You can only query the DOM for the BBox of the text after it has been mounted.
- The `Hexagon`'s shape should update based on its contents.
- As previously mentioned, the `Hexagon` should not know that its `children` are `Text` - it just query the BBox of the element containing its `children`.

### Descendant notifies change 

Something like this in `Text` (an HOC really):

```js
const {onChanged} = useContext(ChangeContext);

useEffect(() => {
 onChanged()
}, [props.value]); 
```

### Ancestor being notified

Whenever a descendant fires onChange a `ref` in the ancestor is mutated:

```js
descendantsChanged.current = true;
```

How this happens is an implementation detail I can share.

The important point is that by the time we hit `useEffect` in Hexagon, it has the knowledge one of its descendants has changed.

### The missing link

Issue is, this won't work:

```js
useEffect(
  () => { /* query children bbox here */ }
  [descendantsChanged.current],
);
```

Whereas this will (I guess):
```js
useEffect(
  () => { /* query children bbox here */ }
  () => [descendantsChanged.current],
);
```

# Complex example (HTML)

When the text of a port (eg, `out`) changes, the box of the 'chip' has to be queried:

![image](https://user-images.githubusercontent.com/880132/64572456-4dac4480-d35f-11e9-8512-19f86fb752f9.png)

**Comment by bvaughn** [comment]
Changes to refs won't trigger an update, so specifying a ref as an effect dependency probably won't work the way you intend it to (regardless of eager vs lazy evaluation). That being said, any proposed API level changes should go through our RFC process (rather than GitHub issues):
https://github.com/reactjs/rfcs/#react-rfcs

**Comment by Izhaki** [comment]
More than happy to close and file at `rfcs`. But just before...

> so specifying a ref as an effect dependency probably won't work

I was under the impression that changes to `ref.current` will immediately be 'seen' by anything that reads `ref.current`. Am I wrong?

I wasn't suggesting changes to refs will trigger an update. This all happens in the 'post-render' phase, meaning the `useEffect` phase, which happens bottom-up. So first a `useEffect` in a descendant, then in the ancestor - all within a single render cycle.

It is the `useEffect` in the ancestor that will either have to set a state (controlled) or fire up an event (uncontrolled).

**Comment by bvaughn** [comment]
Declaring something as a dependency suggests that you want the effect to be re-run when that thing changes. This wouldn't work for a ref, since they are _expected_ to be mutated without triggering an update, so specifying one as a dependency seems like you maybe have a misconception. This is why I mentioned it.

Anyway, a change like this should go through the RFC process, so I'm going to close this issue. 😄
