### ISSUE TITLE
is it a bug about updata?

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#16724]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
not same with twice case,

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/lively-monad-vxx2r?fontsize=14
**What is the expected behavior?**
the same with twice case, or all updata, or none updata about state2
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by HowardTangHw** [comment]
If you update a State Hook to the same value as the current state, React will bail out without rendering the children or firing effects. [docs](https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update)
below code can fix it
```js
function Comp2() {
  const [state1, setState1] = useState(0)
  const [state2, setState2] = useState({ key: 0 })
  function func() {
    //just only setState2
    setState2(preState=>{ return {key:preState.key+1}})
  }
```
