### ISSUE TITLE
Way for a wrapper to get notified of child layout changes

### ISSUE THREAD

**Issue by mathieumg** [facebook/react#1672]
It seems there is no way for a wrapper component to get feedback when its children are changing the layout. I wanted to implement [this demo](http://blog.vjeux.com/2013/javascript/scroll-position-with-react.html) by @vjeux but in the context of a wrapper: http://jsfiddle.net/Pm9ZZ/ Unless I'm doing something wrong (which is quite possible), this does not automatically scroll as in the initial example.

After talking with @spicyj on #reactjs he told me this was indeed something that would need to be addressed at one point.

**Comment by gaearon** [comment]
There’s now APIs like Intersection Observer and [React wrappers](https://github.com/researchgate/react-intersection-observer) for it.
