### ISSUE TITLE
react 16.9.0 webpack build slowness (SSR + externals)

### ISSUE THREAD

**Issue by GuillaumeCisco** [facebook/react#16731]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
project builds in 75 seconds
**What is the expected behavior?**
project builds in 15 seconds

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
new in 16.9.0
was working with all previous versions

Hello there,

We've just updated to 16.9.0 and our webpack build now take 60 seconds more than before...
This is really weird, we don't really know where to start to understand why suddenly it takes so much time, The new changes in react 16.9.0 don't seem to affect webpack build time.
What are we missing?

The only clues I have are, we are passing from:
```
+ 504 hidden modules                 + 881 hidden modules
```

And
```
    Child server:                         Child server:
    Hash: 347e70ff10e5eede2203            Hash: 94c5e414f14beaf34f46
    Time: 10580ms                         Time: 82081ms
    Built at: 09/06/2019 5:33:58 PM       Built at: 09/06/2019 5:38:52 PM

                         Asset      Size  Chunks             Chunk Names                      Asset      Size  Chunks             Chunk Names
       font/LatoLatin-Bold.ttf   143 KiB          [emitted]                 font/LatoLatin-Bold.ttf   143 KiB          [emitted]  
    font/LatoLatin-Regular.ttf   145 KiB          [emitted]              font/LatoLatin-Regular.ttf   145 KiB          [emitted]  
                       main.js  3.17 MiB    main  [emitted]  main                           main.js  4.96 MiB    main  [emitted]  main
                   main.js.map  1.65 MiB    main  [emitted]  main                       main.js.map  3.46 MiB    main  [emitted]  main

    Entrypoint main = main.js main.js.map            Entrypoint main = main.js main.js.map

    chunk {main} main.js, main.js.map (main) 2.48 MiB <{main}> >{main}< [entry] [rendered]            chunk {main} main.js, main.js.map (main) 4.02 MiB <{main}> >{main}< [entry] [rendered]
```

`main.js.map` is far bigger, is there something regarding source map to look after?

environment is `development` with react-hot-loader enabled.

The production build seems not affected (building in 25 sec (due to terser plugin (minimify/uglify)))

Thank you,

**Comment by GuillaumeCisco** [comment]
Ok folks, I have news.|
My project use server side rendering and the slowness occurs on the build of the webpack server configuration.
In this configuration I have something like (simplified) :

```javascript
import config from 'config';
import path from 'path';
import fs from 'fs';
import rules from '../utils/rules';
import resolve from '../utils/resolve';
import plugins from '../utils/plugins/index';

const res = p => path.resolve(__dirname, p);

// if you're specifying externals to leave unbundled, you need to tell Webpack
// to still bundle `react-universal-component`, `webpack-flush-chunks` and
// `require-universal-module` so that they know they are running
// within Webpack and can properly make connections to client modules:
const externals = fs
    .readdirSync(res('../../node_modules'))
    .filter(x => !/\.bin|react-universal-component|require-universal-module|webpack-flush-chunks/.test(x))
    .reduce((ext, mod) => ({
        ...ext,
        [mod]: `commonjs ${mod}`,
    }));

export default {
    mode: process.env.NODE_ENV,
    name: 'server',
    target: 'node',
    devtool: 'cheap-module-source-map',
    entry: [
        'fetch-everywhere',
        res('../../src/server/render.js'),
    ],
    module: {
        rules: rules(),
    },
    externals,
    output: {
        path: res('../../build/ssr/server'),
        filename: '[name].js',
        libraryTarget: 'commonjs2',
        publicPath: '/',
    },
    resolve: resolve(),
    plugins: plugins(),
    optimization: {
        minimize: false,
    },
};
```
One of the big difference with my client configuration is the use of the `externals` option.
I use it for working with the excellent `webpack-flush-chunks` on the server side (https://github.com/faceyspacey/webpack-flush-chunks/blob/master/README.md#externals).
This configuration always worked well and quickly before upgrading to `react@16.9.0`.

Somebody see any relevant information with these new clues?
Why having externals set this way with `react@16.9.0` add +60s to the build?

Thank you,

**Comment by GuillaumeCisco** [comment]
Ok, so I kind of found the issue... at least a fix.
One of the dependencies of my project uses `react@16.9.0` but the project uses `react@16.8.6`.
Simply passing my project to `react@16.9.0` + `react-dom@16.9.0` made the build back to 9 seconds...

I still does not understand what's going on.
My only clue is that the yarn.lock does not support two react version now, but only one.
Maybe with the server configuration build and the externals, it was trying to add the both version of react with some very high recursive process.
I still don't know.

The diff is very simple...
```
diff --git a/packages/ssr/package.json b/packages/ssr/package.json
index b3defc0..a53fadd 100644
--- a/packages/ssr/package.json
+++ b/packages/ssr/package.json
@@ -23,8 +23,8 @@
-        "react": "16.8.6",
-        "react-dom": "16.8.6",
+        "react": "16.9.0",
+        "react-dom": "16.9.0",
diff --git a/yarn.lock b/yarn.lock
index c6c2233..06c22a1 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -10945,15 +10945,15 @@ react-dock@^0.2.4:
     lodash.debounce "^3.1.1"
     prop-types "^15.5.8"
 
-react-dom@16.8.6:
-  version "16.8.6"
-  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-16.8.6.tgz#71d6303f631e8b0097f56165ef608f051ff6e10f"
-  integrity sha512-1nL7PIq9LTL3fthPqwkvr2zY7phIPjYrT0jp4HjyEQrEROnw4dG41VVwi/wfoCneoleqrNX7iAD+pXebJZwrwA==
+react-dom@16.9.0:
+  version "16.9.0"
+  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-16.9.0.tgz#5e65527a5e26f22ae3701131bcccaee9fb0d3962"
+  integrity sha512-YFT2rxO9hM70ewk9jq0y6sQk8cL02xm4+IzYBz75CQGlClQQ1Bxq0nhHF6OtSbit+AIahujJgb/CPRibFkMNJQ==
   dependencies:
     loose-envify "^1.1.0"
     object-assign "^4.1.1"
     prop-types "^15.6.2"
-    scheduler "^0.13.6"
+    scheduler "^0.15.0"
 
 react-fast-compare@^2.0.3:
   version "2.0.4"
@@ -11164,16 +11164,6 @@ react-universal-component@4.0.0:
     prop-types "^15.5.10"
     react-hot-loader "^4.3.6"
 
-react@16.8.6:
-  version "16.8.6"
-  resolved "https://registry.yarnpkg.com/react/-/react-16.8.6.tgz#ad6c3a9614fd3a4e9ef51117f54d888da01f2bbe"
-  integrity sha512-pC0uMkhLaHm11ZSJULfOBqV4tIZkx87ZLvbbQYunNixAAvjnC+snJCg0XQXn9VIsttVsbZP/H/ewzgsd5fxKXw==
-  dependencies:
-    loose-envify "^1.1.0"
-    object-assign "^4.1.1"
-    prop-types "^15.6.2"
-    scheduler "^0.13.6"
-
 react@16.9.0, react@^16.5.2:
   version "16.9.0"
   resolved "https://registry.yarnpkg.com/react/-/react-16.9.0.tgz#40ba2f9af13bc1a38d75dbf2f4359a5185c4f7aa"
```

If it can help anyone :)
I'm now not event sure this is a react issue, but we never had this problem before when some dependencies upgraded to a new react version...

An admin can close this issue if necessary. Though real solution has not been found.

**Comment by gaearon** [comment]
Your dependencies (such as component) shouldn’t *depend* on React. That’s the issue. They should have it as a *peer dependency*.

The only thing that should depend on React is your app itself. Then you’ll only have one copy.

Having multiple copies of React in one project is highly discouraged and leads to other counter-intuitive problems.
