### ISSUE TITLE
DevTools: Component tree navigation

### ISSUE THREAD

**Issue by zinoviev** [facebook/react#16735]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Where is no way to collapse/expand component tree or it subtrees. 

If I pick element with "Select element" button - I got all the tree expanded, not the only one subtree, where selected element came from(probably bug?) And I don't found way to collapse tree. So if you pick something from page your component tree is basically is always expanded on all levels. 

Maybe we can have selected row context menu like the one in chrome devtools with options to collapse/expand. 

![image](https://user-images.githubusercontent.com/848985/64634574-396f5280-d406-11e9-9cb8-1630e2edef5e.png)

![image](https://user-images.githubusercontent.com/848985/64634564-307e8100-d406-11e9-8d3d-1a97c9f3b77b.png)

Also I guess it maybe good place to add https://github.com/facebook/react/issues/16463

**Comment by bvaughn** [comment]
> Where is no way to collapse/expand component tree or it subtrees.

DevTools has a collapse/expand toggle in the UI 😄 It works pretty much the same as the browser's built-in Elements panel:

![Collapse and expand subtree](https://user-images.githubusercontent.com/29597/64649552-f5625a80-d3d1-11e9-8e76-dcea0d469311.gif)

You can collapse an entire subtree by clicking on the arrow to the left. You can also collapse/expand using the left and right arrow keys.

**Comment by zinoviev** [comment]
@bvaughn Sorry, I was unclear what I'm talking about. 

Sure we can collapse/expand nodes and this obiously works super fine. We don't have "Collapse children" or "Collapse all" to recursivly collapse every children and it should be some separate feature.

Why it bothers me. Try this scenario:
1) Use "Select element in the page" in react devtools to inspect element in real world app with pretty deep nested element tree
2) Component tree recursivly expands every single node among all subtrees. I'm not sure if it's right or bug. More looks like bug for me personally
3) You have now giant opened tree with literally every node expanded
4) Here is the issue - you can't compact it. You can collapse root, but as it expand - all childrens remain expanded.
5) Even worse -  "Everything expanded" state persisted among sessions

![1](https://user-images.githubusercontent.com/848985/64654396-d09dcf80-d431-11e9-9a26-4273908e60e0.gif)

In chrome for example "inspect" funtion will only expand subtree I picked from. And you can collapse recursivly any part of tree

![2](https://user-images.githubusercontent.com/848985/64654713-c5976f00-d432-11e9-8e0b-94d955e4d598.gif)

**Comment by zinoviev** [comment]
And I guess it's overlaps with https://github.com/bvaughn/react-devtools-experimental/issues/383

**Comment by OnkelTem** [comment]
Sorry, why have you just closed it?
