### ISSUE TITLE
Add feature detection for required language features?

### ISSUE THREAD

**Issue by david-mark** [facebook/react#16733]
ISTM that it would be very useful for the library to detect (and test as needed) required language features (e.g. Map and Set). If they are found to be missing or lacking, then the library could either self-destruct (abstain from creating its interfaces) or set a flag to indicate that it is unusable in the present environment.

What is the point of presenting interfaces to callers that have no chance of working? As it sits, the only way to work around this issue is for applications to detect the required features themselves. Of course, this requires careful analysis of the React scripts to determine the full extent of the requirements (e.g. partial implementations of Map and Set won't cut it).

It is the same story for DOM feature requirements (e.g. requestAnimationFrame) but one step at a time.

This is a common issue with libraries that makes cross-browser scripting more difficult than it should be. For more information:

https://www.linkedin.com/pulse/building-better-web-applications-david-mark/

As this is a very popular library at the moment, it would be nice to demonstrate some leadership in this area.

**Comment by bvaughn** [comment]
> As it sits, the only way to work around this issue is for applications to detect the required features themselves. Of course, this requires careful analysis of the React scripts to determine the full extent of the requirements

React's supported browser versions / required language features [are documented pretty thoroughly on reactjs.org](https://reactjs.org/docs/javascript-environment-requirements.html), along with polyfill instructions for older environments:

> React 16 depends on the collection types [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). If you support older browsers and devices which may not yet provide these natively (e.g. IE < 11) or which have non-compliant implementations (e.g. IE 11), consider including a global polyfill in your bundled application, such as [core-js](https://github.com/zloirock/core-js) or [babel-polyfill](https://babeljs.io/docs/usage/polyfill/).

Hope this helps clear up any confusion 😄

**Comment by david-mark** [comment]
Thanks, but I wasn't confused. ;)

Please see the linked article, as it links to the same documentation, which is not only insufficient, but beside the point.

**Comment by gaearon** [comment]
If you have concrete ideas for how to improve the docs, please feel free to do so by clicking 'Edit Page' and sending a pull request. Thank you!

**Comment by david-mark** [comment]
I may do that, but it is still beside the point of this issue.

For example, what if an application developer does not wish to support "older browsers". What do they do to prevent it from blowing up in those agents? There is no way for the application code to determine if React is a go or no go.

Of course, the same goes if they do elect to include the polyfills as those only narrow the list of browsers where the library will fail.

As for the documentation, it does not specify how much of the Map and Set features must be implemented, only that whatever IE 11 provides is insufficient. This leaves the application developer to scour the React source code to determine exactly what to detect and test.

**Comment by bvaughn** [comment]
> As for the documentation, it does not specify how much of the Map and Set features must be implemented, only that whatever IE 11 provides is insufficient. This leaves the application developer to scour the React source code to determine exactly what to detect and test.

The documentation suggests _specific_ polyfills that the React team has determined to be sufficient for IE 9-11. No one should need to search through source code.

**Comment by david-mark** [comment]
So far, the point has been missed. Forget polyfills for a moment, as they do _not_ solve the problem posed (they just move the goal posts). Also forget the context of specific browsers (e.g. IE).

The problem is how an _application_ can detect at _run time_ whether ReactJS will work or not. At the moment, it cannot, requiring developers to scour its source code to cobble together feature tests. This tedious process would need to be repeated every time that the source code changes.

The proposed solution is for the library to do this testing itself and to either self-destruct (i.e. abstain from presenting its interfaces) or at least set a flag indicating incompatibility as appropriate. This would enable trouble-free cross-browser scripting for users of this library, whether they elect to use polyfills or not.

**Comment by bvaughn** [comment]
I haven't missed your point. I just disagree- but I'm trying to limit my responses to things that are objective.

In our experience, developers often don't sufficiently test their applications across multiple browsers and platforms. So depending on them to run it in e.g. older versions of IE, notice it doesn't work, and add polyfills probably would not work in many cases. Instead, clearly documenting the language feature requirements has been more successful.

**Comment by david-mark** [comment]
> I haven't missed your point. I just disagree- but I'm trying to limit my responses to things that are objective.

The previous responses indicated that the point was missed, however they were limited.

> In our experience, developers often don't sufficiently test their applications across multiple browsers and platforms. So depending on them to run it in e.g. older versions of IE, notice it doesn't work, and add polyfills probably would not work in many cases. Instead, clearly documenting the language feature requirements has been more successful.

As does this one. This is not about human decisions made during development. This is about the library providing a crucial bit of information to application code at run time.
