### ISSUE TITLE
DevTools: Long interaction names cannot be seen

### ISSUE THREAD

**Issue by davidmccabe** [facebook/react#16736]
Interaction names longer than about 30 characters are truncated without tooltips and so cannot be seen. If you go to the "Interactions" tab of the profiler, both the left-hand column and the right-hand sidebar are of fixed size and show a truncated name.

**Comment by varen27** [comment]
I would like to pick this up.

**Comment by toshi1127** [comment]
What's the status of this?
I made a [PR](https://github.com/facebook/react/pull/16767) to fix this issue, please review it if you want!

**Comment by kevinsunny1996** [comment]
Would like to contribute from my end for this issue ... pls  assign it to me...

**Comment by abrahamwilliam** [comment]
Would like to contribute from my end for this issue ... pls assign it to me...

**Comment by tombrowndev** [comment]
I can do this!

**Comment by cryptogoth** [comment]
This looks like it's been finished and is pending a final merge
https://github.com/facebook/react/issues/16736

**Comment by kambleaa007** [comment]
Its still open

**Comment by namik7** [comment]
i will try this

**Comment by yadejo** [comment]
Tooltip was added in #17689, I think this issue should be closed.

**Comment by necolas** [comment]
Yes I believe this is fixed by #17689
