### ISSUE TITLE
Devtools: three feature..thanks

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#16747]
**Do you want to request a *feature* or report a *bug*?**
feature

1. 
![image](https://user-images.githubusercontent.com/21235555/64679262-f8cb1400-d4ad-11e9-8729-90b5d95241bd.png)
let props.children props.onChange similar props has Fixed-Position
such as props.children always TOP and  props.onChange similar alway at last of list

2.now, string and number type UI make no odds , please add some  visual difference

3. if a props value was default, mean parent comp dont set the value, 
add some  visual difference, with the props  that not default 

thanks you

**Comment by bvaughn** [comment]
I don't think there's anything actionable we can do for these feature requests.

1. I'm not entirely sure what you're asking here, but props/state/context are always alpha-sorted. This is probably the best default we can pick for sorting for most cases.

2. The next release will add some improvements to the props UI for different types:
![new-edit-Kapture 2019-09-10 at 14 11 17](https://user-images.githubusercontent.com/29597/64714165-fe573880-d472-11e9-8364-7321bb49bec4.gif)

We don't have any plans to add icons or anything like that to differentiate between types. As much as possible, we are trying to mimic what the browser's built-in DevTools look like and do for these values. (They don't visualize them differently either.)

3. DevTools doesn't have a way to know if a prop was a default value or whether it was passed by the owner. (Even if a prop value is the same as the default value, it may have been passed in as an external prop that just happened to have the default value.)

**Comment by bvaughn** [comment]
You didn't fail to explain. I answered above that we alphabetically sort all props because that's probably the least confusing way to display them. That means a -> c -> onClick -> z.
