### ISSUE TITLE
React.Children.map(children, function[(thisArg)]) feature

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#16746]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
React.Children.map(children, function[(thisArg)]) feature 
we must pass children arg, but in most case it is this.props.children
so why not set a default value 
so that we can use like this 
```js
React.Children.map(function[(thisArg)]) 
//or
React.Children.map(children, function[(thisArg)]) 

```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Tevinthuku** [comment]
I'm not sure I've got the best answer to this but, the map function knows nothing about the children you want to iterate over.

The screenshot below shows the implementation of the map function.

having `this.props.children` as the default won't work since the `props` object belongs to the class or function component and not the `map` function. If we tried having that,  then `children` will be referenced from the map function's `this` context and that wouldn't be correct.

![image](https://user-images.githubusercontent.com/12128153/64704144-785ce100-d4b6-11e9-87ef-14a25c9b8808.png)

I hope this helps

**Comment by kunukn** [comment]
Another consideration is the API design. The optional should be last. And if it is the case then it is a breaking change.

```
React.Children.map(function[(thisArg)]) 
//or
React.Children.map(function[(thisArg)], children) 
```

And `this.props.children` exists in class component. Not function component.

---

But you could write a helper method for class based components.

```jsx
const cMap = function(b) {
  React.Children.map(this.props.children, b);
};

class ComponentChildrenMaps extends React.Component {
  constructor(props) {
    super(props);
    this.cMap = cMap.bind(this);
  }
}

class A extends ComponentChildrenMaps {
  render = () => {
    // this.props.children is not required, only the function
    this.cMap(c => console.log(c.key));
    return <div>{this.props.children}</div>;
  };
}

class B extends ComponentChildrenMaps {
  render = () => {
    // this.props.children is not required, only the function
    this.cMap(c => console.log(c.key));
    return <div>{this.props.children}</div>;
  };
}

function App() {
  return (
    <>
      <A>
        <div key={1}>1</div>
        <div key={2}>2</div>
      </A>
      <B>
        <div key={5}>5</div>
        <div key={6}>6</div>
      </B>
    </>
  );
}

```

**Comment by threepointone** [comment]
Honestly, we recommend using Children helpers only as a last resort when you can't pass props directly to elements. We definitely won't bind calling this function to the class it's called in, because the behaviour seems implicit and confusing. 
Thank you for your suggestion!
