### ISSUE TITLE
DevTools: Excessively long component names cause component tree to flatten

### ISSUE THREAD

**Issue by coreyleelarson** [facebook/react#16742]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Our application uses an older version of Mobx, and its `inject` HOC creates excessively long component names (inject-Component-with-userStore-appStore-columnStore-...) when multiple stores are used. While navigating and scrolling down the component tree, when a components scrolls into frame whose name cannot fit horizontally, the entire tree flattens. This makes it difficult to discern between parent, sibling, and child components.

![devtools](https://user-images.githubusercontent.com/1900645/64652970-2606bc00-d3f3-11e9-8bcd-45ad2c43dd19.PNG)

**What is the expected behavior?**
I would expect the component tree to either scroll horizontally or truncate component names that are excessively long, while still including indentation for child components.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v16.3.0
Chrome v77
DevTools v4.0.6

**Comment by 9oelM** [comment]
Seems like a problem with `--indentation-size` variable used for css in DevTools. 
Will need a bit of research, but the problem should be somewhere around this.

## When you have `--indentation-size` set as 0px in parent html node
![image](https://user-images.githubusercontent.com/22465806/64674305-76d9eb80-d4ab-11e9-8e44-7dd0885e202f.png)

## When you drop `--indentation-size`
![image](https://user-images.githubusercontent.com/22465806/64674289-69246600-d4ab-11e9-86d1-ad7d9d7d0ab7.png)

You can see that removing that buggy `--indentation-size` css variable would make it look as expected.

**Comment by 9oelM** [comment]
Related:
https://github.com/facebook/react/blob/b438699d3620bff236282b049204e1221b3689e9/packages/react-devtools-shared/src/devtools/views/Components/Tree.js#L406

**Comment by coreyleelarson** [comment]
@9oelM - I see. This appears to be where that variable is used:

https://github.com/facebook/react/blob/b438699d3620bff236282b049204e1221b3689e9/packages/react-devtools-shared/src/devtools/views/Components/Element.js#L120

What if we ensure `--indentation-size` is always greater than or equal to something like 5px?

**Comment by bvaughn** [comment]
I don't know that supporting names like the ones shown in the attached screenshot (hundreds of characters long) is really a goal for DevTools.

Dynamic indentation improves the browsing experience for deep trees, as horizontal scrolling and empty space in deep trees was one of the biggest complaints before it was added.

If you'd like to submit a PR with a proposal for this, please do.

**Comment by coreyleelarson** [comment]
@bvaughn - I understand the motivation behind dynamic implementation, but I feel there should at least be a fallback for extreme cases such as this one. I will try to submit a PR with the proposed change.

**Comment by coreyleelarson** [comment]
@bvaughn - PR Submitted: https://github.com/facebook/react/pull/16756
