### ISSUE TITLE
autoplay attribute on videos is wrongly camel-cased

### ISSUE THREAD

**Issue by rmfarrell** [facebook/react#16762]
JSX ignores the HTML `autoplay` attribute and warns it should be `autoPlay`.

Camelcase here is incorrect. I should only expect to use camelcase if the attribute were hyphenated in vanilla HTML. Autoplay is one word both as an html attribute and according to English.

**Comment by kunukn** [comment]
Here is the list of attribute names:
https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/possibleStandardNames.js

There is a convention of camel-casing the attribute names. 
All the words starting with `auto` are camel-cased.

So the suggestion is not to ignore `autoplay`? and not give warning?

A change might require a breaking change unless it is backward compatible, meaning supporting both `autoplay` and `autoPlay`.


I don't know whether the ship has sailed and this is the idiomatic approach to follow or whether it is a good idea to be flexible and also allow `autoplay`.

**Comment by Dergash** [comment]
Hi @rmfarrell!
You can read the [reasoning behind using camelcase here](https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes) and [specifically about autoplay here](https://github.com/facebook/react/issues/4653)

**Comment by rmfarrell** [comment]
I'd say accept both but deprecate the camel case way in  a later version? camel case is for concatenating multi-word properties. I was stuck for several minutes on this because there I would never have guessed that autoplay would be camel-cased just because it starts with "auto."
