### ISSUE TITLE
The problem with server-side rendering React

### ISSUE THREAD

**Issue by narzantaria** [facebook/react#16783]
Hello!
I have a project with server-side rendering **React**, connected directly to **Express** server using **ReactDOMServer** and **ReactDOMHydrate**, built with **Webpack**, **Babel**, etc. I would like to know how to implement two tasks:
1. Import **css**.
2. Manage the state of **React** (for example, create some kind of onclick event on the button).
I have a reposirory:
[isomorphic-react](https://github.com/narzantaria/isomorphic-react)
Thanks for any help!)

**Comment by threepointone** [comment]
This issue tracker is for bugs and feature requests, so I’m going to close it. I’d recommend using a community resource for usage questions https://reactjs.org/community/support.html

With regards to your specific questions-
- you could read the documentation for webpack to learn more about how to import and use css for your website. I’d also recommend looking at frameworks like https://www.gatsbyjs.org/ and https://nextjs.org/ for solutions that come with a lot of common use adds supported out of the box. 
- React supports state and event management, the details are in the documentation. I’d start with the tutorial here https://reactjs.org/tutorial/tutorial.html you could also look at tools like redux or mobx for more.
