### ISSUE TITLE
Workaround to the input onChange lossing focus bug

### ISSUE THREAD

**Issue by Ziv-Barber** [facebook/react#16786]
It's not the best solution since that React still destroying and creating the input element but when you are working with dynamic elements created on the fly, like for example, from an array, then you don't have any other choice:

    import React, { useEffect } from 'react'

    function InputWithFocus(props) {
      const { getFocusData, setFocusData, onChange, ...rest } = props
      let isNeedSaveFocus = null

      useEffect(() => {
        const focus = getFocusData()
        if (focus && focus.key === props.id) {
          const el = document.getElementById(props.id)
          if (el) {
            el.focus()
            el.setSelectionRange(focus.pos, focus.pos)  
          } // Endif.

          setFocus(null)
        } // Endif.

        return () => {
          if (isNeedSaveFocus || isNeedSaveFocus === 0) {
            setFocusData({key: props.id, pos: isNeedSaveFocus})
          } // Endif.
        }
      })

      function onChangeImp(event) {
        isNeedSaveFocus = event.target.selectionStart
        if (props.onChange) {
          props.onChange(event)
        } // Endif.
      }

      return <input onChange={onChangeImp} {...rest} />
    }

Working great here. I'll be happy for a better solution which is to fix the bug in react so it'll use the key attribute to compare elements.

**Comment by bvaughn** [comment]
> input onChange lossing focus bug
> I'll be happy for a better solution which is to fix the bug in react so it'll use the key attribute to compare elements.

It's not clear what bug you're referring to, or what this issue is about?

**Comment by Ziv-Barber** [comment]
When you are trying to add an input field + onChange() that updating a state then on any key click you're losing focus:

<input value={props.curValueFromSomeState} ... onChange={updateTheState} />

React destroying and creating again the element for every key that the user entering.
In my case I'm creating a list of input fields on the fly with array.map() and I do added key= to each input. I verified that the keys are OK and not changing because of the value of the input field.

**Comment by bvaughn** [comment]
Please provide a repro example that shows what you're describing? Still isn't really clear to me.

Put up an example on Code Sandbox?

**Comment by illuminist** [comment]
I had been working with very dynamic input creation that also add and remove some fields or set of field at runtime but I have never found any issue about losing focus on input when updating state. I suspect that the issue lie in how the OP updates the state.

**Comment by bvaughn** [comment]
Absent a repro case, I don't think there's an actual bug here. Going to close for now but can re-open if @Ziv-Barber provides more repro info
