### ISSUE TITLE
Using a custom hook on multiple rendered components causing unexpected results

### ISSUE THREAD

**Issue by thesimpledesigners** [facebook/react#16785]
**Do you want to request a *feature* or report a *bug*?**
I want to report an unexpected behavior I found while using a custom hook not sure if it's a possible bug or miss understanding of how custom hooks functions.

**What is the current behavior?**
Using a custom hook on multiple components, only 1 component receives updates other components don't.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React:**

**CodeSandbox:** (https://codesandbox.io/s/react-custom-hooks-nkcn6)

**What is the expected behavior?**
expected behavior is to receive same updates on all child components.

**Note** : I'm not looking for a solution because i already found mine, (using the custom hook on the parent container and pass props to child components). 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React Version : 16.8

**Comment by Dergash** [comment]
Hello @thesimpledesigners! I don't think it's a bug. You subscribed to an event inside your custom hook: 
```jsx
 window.addEventListener(`currency_changed`, eventListener);
```
At the same time, tour event handler has a stopImmediatePropagation call:
```jsx
const eventListener = event => {
    event.preventDefault();
    event.stopPropagation();
    event.stopImmediatePropagation(); // << Here it is
    const currency = event.detail.currency;
    if (Object.keys(symbols).includes(currency)) {
        setCurrency(currency);
    }
};
```
And stopImmediatePropagation specifically says:

> The stopImmediatePropagation() method of the Event interface prevents other listeners of the same event from being called.
If several listeners are attached to the same element for the same event type, they are called in the order in which they were added. If stopImmediatePropagation() is invoked during one such call, no remaining listeners will be called.

So your first event handler just prevents two others.

**Comment by thesimpledesigners** [comment]
Hey @Dergash thanks for your response, I wonder how I missed that I feel so dump, we always tend to blame hooks first. So thanks again I was solving it the hard way by moving everything to a parent container and using one hook.
