### ISSUE TITLE
useCallback can't get the correct  dom value

### ISSUE THREAD

**Issue by ORION-G** [facebook/react#16792]
hello～ I got a problem when I use the useCallback function. 

const  MeasureExample = () => {
  const [height, setHeight] = useState(0);

  const measuredRef = useCallback(node => {
    if (node !== null) {
      setHeight(node.getBoundingClientRect().height);
    }
  }, []);

  return (
      \<div ref={measuredRef}  className="departments_wrapper" \>
       something
      \<\/div\>
  );
}

.departments_wrapper {
    position: relative;
    width: 100%;
    padding: 20px;
    background: $base-green;
    z-index: 15;
  }

this demo in official documents  can't get the correct height value in my code  if i set the padding property.  The value can't include the padding.

**Comment by demkovych** [comment]
you need to set in css **box-sizing:border-box**

**Comment by yuanoook** [comment]
@ORION-G Better to provide an online demo for the case with codesandbox.io

**Comment by ORION-G** [comment]
> you need to set in css **box-sizing:border-box**

I have already  set this in a basic scss file like  * { box-sizing:border-box}

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
