### ISSUE TITLE
DevTools: Updating numeric state through incrementer/decrementer doesn't render the updated value 

### ISSUE THREAD

**Issue by 13thThief** [facebook/react#16808]
**Do you want to request a *feature* or report a *bug*?**

Report a *Bug*

**What is the current behavior?**

If there is a state variable that holds a number, updating it via incrementer/decrementer doesn't render the updated value in the component. Instead it only updates if you focus (click) onto the field and press Enter.

**What is the expected behavior?**

The incrementer/decrementer should render the updated value without having to focus onto the field and press Enter.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React Devtool: 4.0.6
Browser: Firefox Dev 70.0b6 (64-bit)

(Timer state variable updates the value in Session)
![hfo_19](https://user-images.githubusercontent.com/17070403/65059248-46a2b900-d993-11e9-8a29-ec382c5f755f.gif)

**Comment by threepointone** [comment]
Could you share a reproducing usecase with https://codesandbox.io/?

**Comment by 13thThief** [comment]
Sure.

https://codesandbox.io/s/misty-fog-rfyo0
https://rfyo0.csb.app/

**Comment by threepointone** [comment]
Ah ok, I don't see the increment/decrement buttons on mac, so cannot reproduce. I'm guessing you're on windows? @bvaughn is this a known issue?

**Comment by bvaughn** [comment]
Not a known issue but this UI has already been changed via #16700 such that the numeric input no longer exists. (We just haven't done a release yet.)

So this bug has been fixed and the fix will be deployed with the next release.

**Comment by 13thThief** [comment]
@threepointone Windows 8.1 (64-bit)
@bvaughn Alright. Thanks!
