### ISSUE TITLE
[Flare] Focus has too limited a set of keys that set isGlobalFocusVisible

### ISSUE THREAD

**Issue by majornista** [facebook/react#16814]
At [/packages/react-ui/events/src/dom/Focus.js#L140](https://github.com/facebook/react/blob/3af05de1aaed309f8146bc53f9a4b4d785abdd3f/packages/react-ui/events/src/dom/Focus.js#L140), only `'Enter'`, `' '` and `Tab`, with no modifier keys, will set `isGlobalFocusVisible = true` so that the next element to receive focus will update to display its `isFocusVisible` state. 

```jsx
/* ... */
    case 'keydown':
    case 'keyup': {
      const nativeEvent = event.nativeEvent;
      const focusTarget = state.focusTarget;
      const {key, metaKey, altKey, ctrlKey} = (nativeEvent: any);
      const validKey =
        key === 'Enter' ||
        key === ' ' ||
        (key === 'Tab' && !(metaKey || (!isMac && altKey) || ctrlKey));

      if (validKey) {
        state.pointerType = 'keyboard';
        isGlobalFocusVisible = true;
        if (
          focusTarget !== null &&
          context.isTargetWithinResponderScope(focusTarget)
        ) {
          callback(true);
        }
      }
      break;
    }
/* ... */
```

This ignores a number of other keys that commonly trigger focus changes like Arrow keys, Home, End, for navigating radio buttons, toolbars, tab lists, list boxes, and Escape, for closing a dialog or popover. 

The [WICG/focus-visible polyfill](https://github.com/WICG/focus-visible/blob/master/src/focus-visible.js#L109) treats any keyboard event as valid. This may be going a bit too far, because any keyboard interaction, regardless of whether focus changed will render the `:focus-visible` style. 

A somewhat better approach may be to treat form elements that take text input, like `textarea`, `input[type=text]`, `input[type=number]`, etc., as a special case, where keys that input text or change the cursor position do not change the `isGlobalFocusVisible` state.

**Comment by trueadm** [comment]
This is an interesting problem. If you have the time to take a stab at fixing this, feel free to throw up a PR. We can maybe listen to the `input` event, and if an element triggers it, we could maybe use that as an indication that of the special case, rather than checking the type of an `input`.

**Comment by majornista** [comment]
I think we still need to know whether the element dispatches the input event, and we pretty much know which components do, `INPUT`, `TEXTAREA`, `SELECT` and any where `isContentEditable === true`. We can filter out keyboard events targeting those elements and treat them as a special case where looking at the `InputEvent` is relevant. Any other target for keyboard interaction without modifier keys should probably flag `isGlobalFocusVisible = true`. 

The important piece of information from the `InputEvent` is the `inputType` property. It will be `undefined` for an input that is not editing text content, like a checkbox, radio, or range. So if the `state.pointerType === 'keyboard'` and `inputType === undefined`, the input event should flag `isGlobalFocusVisible = true`. 

The one other keyboard event I would evaluate for `INPUT`, `TEXTAREA`, `SELECT` and `isContentEditable === true` is the Escape key, which doesn't produce an InputEvent, and should probably also flag `isGlobalFocusVisible = true`.

**Comment by trueadm** [comment]
@majornista Mind creating a PR for this, as it sounds like you have a really clear picture as to how this would work. I can help with any issues you may have :)

Thank you so much for this :)

**Comment by necolas** [comment]
Thanks, we are tracking this issue internally to adopt a solution closer to the WICG/focus-visible polyfill and what react-native-web does, so I'm going to close this one here.

**Comment by majornista** [comment]
> Thanks, we are tracking this issue internally to adopt a solution closer to the WICG/focus-visible polyfill and what react-native-web does, so I'm going to close this one here.

I appreciate your tracking it internally; I don't think I have the bandwidth to create a PR for this at this time.
