### ISSUE TITLE
why not ReactElement compile to object but a funciton call(React.createElement)

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#16839]
**Do you want to request a *feature* or report a *bug*?**
feature

```js
//as we know
const ReactElement = <Wrap />
//this will compile to
const ReactElement = React.createElement(Wrap)
//and, why dont we further on,  direct,  compile it to the result of the function call
const ReactElement = {
    $$typeof: Symbol(react.element),
    type:Wrap,
    ....
}
```

**Comment by threepointone** [comment]
There are 2 babel plugins that optimize react elements 
- https://babeljs.io/docs/en/babel-plugin-transform-react-inline-elements/ which is close to what you mention
- https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements/ which hoists these elements in scope if possible
