### ISSUE TITLE
eslint-plugin-react-hooks: 'Hook is being called conditionally' error outside condition

### ISSUE THREAD

**Issue by cbdeveloper** [facebook/react#16832]
**Do you want to request a *feature* or report a *bug*?**

BUG (possibly)

**What is the current behavior?**

The plugin is showing this error:

>React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return? (react-hooks/rules-of-hooks)eslint

But I don't think I'm calling any hooks conditionally.

The code:

https://codesandbox.io/s/exciting-bhabha-mqj7q

```
function App(props) {
  const someObject = { propA: true, propB: false };

  for (const propName in someObject) {
    if (propName === true) {
      console.log("something");
    } else {
      console.log("whatever");
    }
  }

  // THE PLUGIN ERROR MSG ON THIS useState
  const [myState, setMyState] = useState(null);

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}
```

![image](https://user-images.githubusercontent.com/43407798/65239956-10bb1d00-dad8-11e9-88b9-ec517cd17645.png)

**What is the expected behavior?**

The plugin wouldn't show the error in this situation.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

![image](https://user-images.githubusercontent.com/43407798/65240081-5a0b6c80-dad8-11e9-8692-a9974342130e.png)

**Comment by dankreiger** [comment]
I'm not deep enough into the source code yet to understand why, but I noticed that for this particular example:

`pathsFromStartToEnd` is `3`
`allPathsFromStartToEnd` is `2`

`possiblyHasEarlyReturn` is also `true`

This particular error is thrown when these values are unequal: see [source](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L404)

**Comment by M-Izadmehr** [comment]
@gaearon, I created an MR addressing and fixing this issue (#16853).

The main reason this happens is that the value of `allPathsFromStartToEnd` is calculated wrong.
In this example, the number of paths from start to end should be 3, but the function returns 2.

The reason this happens is because of flawed caching of cyclic paths. So in normal graph traversing, we need the path history as well, but it only takes a list of cyclic elements, and the elements leading to this path are not known. 
As a result, when a condition is used in a `for...in obj`, based on the direction we might lose some paths.

**Comment by andreypopp** [comment]
This is still an issue with 2.4.0, a little bit simpler repro:
```
import * as React from "react";

function Component() {
  let isLastEven = false;
  for (let x of [1, 2, 3]) {
    if (x % 2 == 0) {
      isLastEven = true;
    } else {
      isLastEven = false;
    }
  }
  let y = React.useMemo(() => 1, []);
  return <div>{y}</div>;
}
```
can #16853 be re-openned?

**Comment by gaearon** [comment]
Merged https://github.com/facebook/react/pull/16853.
