### ISSUE TITLE
Create eslint rule to ask devs to specify 2nd parameter of useEffect/etc.

### ISSUE THREAD

**Issue by khoomeister** [facebook/react#16838]
**Do you want to request a *feature* or report a *bug*?**

I don't want to call it a bug, but more of a suggestion and open to discussion!

**What is the current behavior?**

I was debugging an issue on a webapp today where if you typed a character into an input element within a modal, the element would immediately lose focus and further keypresses won't go into the input (not the best UX!)

After looking at keyboard event handlers, focus, blur, etc. and not finding answers, I eventually drilled it down to this:

```typescript
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import { useRef, useEffect } from 'react'

const portalRootEl = document.getElementById('#top')!

export const Portal = ({ children }) => {
  const containerElement = useRef(document.createElement('div'))

  useEffect(() => {
    const el = containerElement.current
    portalRootEl.appendChild(el)

    return () => {
      portalRootEl.removeChild(el)
    }
  })

  return ReactDOM.createPortal(children, containerElement.current)
}
```

The issue was useEffect's 2nd parameter should've been an empty list (i.e. `[]`) to prevent the portal being destroyed and recreated every single time.

**What is the expected behavior?**

I know this can be attributed to developer error, but perhaps encouraging engineers to specify the 2nd argument can help prevent very hard to detect and pernicious bugs like this.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8 but anything with hooks really

**Comment by bvaughn** [comment]
The [`useEffect` docs](https://reactjs.org/docs/hooks-reference.html#useeffect) do explicitly call this out at the top:
> By default, effects run after every completed render, but you can choose to fire it [only when certain values have changed](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect).

There's also a section called [Conditionally firing an effect](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect) that explains how to specify the dependency array if you want to only re-run the effect when values change.

We also publish an [ESLint plug-in](https://reactjs.org/docs/hooks-rules.html) to help with Hooks usage.

If you think the docs can be improved though, please click the "_Edit this page_" button on the bottom of any of the pages and send us a PR! :smile:
