### ISSUE TITLE
React DOM SSR crashes since React-Dom 16.6.2

### ISSUE THREAD

**Issue by ernestognw** [facebook/react#16848]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I've setup an SSR configuration using ReactDOM.renderToString() method with react-apollo, and it throws an Invariant violation as the following, with no more information about:

<img width="297" alt="Captura de pantalla 2019-09-21 a la(s) 6 29 37" src="https://user-images.githubusercontent.com/33379285/65372722-36136c80-dc39-11e9-8342-90369c2055e5.png">

Everything returns to normal when downgrading to react-dom@16.6.1

*My SSR App component*

<img width="600" alt="Captura de pantalla 2019-09-21 a la(s) 6 33 24" src="https://user-images.githubusercontent.com/33379285/65372762-b9cd5900-dc39-11e9-9045-143146e0baf9.png">

*Things I've tried*

- I have changed the react-dom package to serve the development version (./cjs/react-dom-server.node.development.js), just for debugging, and when importing that version, everything works fine, but when I return to the production version (./cjs/react-dom-server.node.production.min.js) the same error appears.

- I removed one by one, every component wrapping my `<App/>`, and the one that seems to be causing the error is the `<AuthProvider>`, which is a context implementation of mine. By removing some things on that component, i figured out that is a problem within a HOC provided by react-apollo, but I don't know exactly what it is because it doesn't show me any information.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I actually do not have any way to reproduce it quickly.

**What is the expected behavior?**
Render correctly the website.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React - 16.9.0
React-DOM - 16.9.0
Browsers - Safari and Chrome (tested)

Working if downgrading to React-DOM 16.6.1

**Comment by soldovskij** [comment]
I think renderToString do not await callback from Context, have some issue

**Comment by gaearon** [comment]
Closing since there's no repro
