### ISSUE TITLE
Why I can't render ?!

### ISSUE THREAD

**Issue by JeremyMeissner** [facebook/react#16849]
I have an error in this code
I don't know why it doesn't render...
I'm on Firefox 69.0.1 (64 bits) and Windows 10.

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
    
    <script>
    ReactDOM.render(
      <div>Hello world</div>,
      document.getElementById('root')
    );
    </script>
  </body>
</html>
```
This simple code doesn't work... help.

**Comment by alexrohleder** [comment]
if you open your console (F12 in most cases) you will see that you have a syntax error.

the syntax `<div>...</div>` is from JSX, something that will not run directly like this.
in your case you could go for `React.createElement('div', {}, 'hello world')` instead and it would work.

for more info on how to enable the JSX syntax [see this link](https://reactjs.org/docs/add-react-to-a-website.html#optional-try-react-with-jsx).

**Comment by JeremyMeissner** [comment]
Thanks you @alexrohleder !
