### ISSUE TITLE
it is a Hook BUG?

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#16846]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
FooNo dit not work

http://jsfiddle.net/kag0n7L3/

the FooNo and FooYes different :is the Bar in Foo Inside or outside

and i used the rules-of-hooks

**Comment by zmitry** [comment]
You are creating component inside component at line 24, so on every change state your component will reset it's state and create new fiber with empty hook state.

**Comment by bvaughn** [comment]
@zmitry is correct.

Don't define a component/function inside of another one. Otherwise it will be recreated each time the outer component renders, causing React to think it's a new "type" (new function) which will cause it to be unmounted and re-mounted, losing any state.
