### ISSUE TITLE
Adding `.displayName` documentation to Contexts

### ISSUE THREAD

**Issue by yachaka** [facebook/react#16851]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
No documentation is to be found on the property `.displayName` of Contexts. See https://github.com/facebook/react/issues/12695#issuecomment-456979851

**What is the expected behavior?**
Documentation on the property

I wanted to configure the name displayed in React DevTools of my `<Context.Provider />` and `<Context.Consumer />` components but found nothing in the documentation. Finally found this issue and a solution: https://github.com/facebook/react/issues/12695#issuecomment-456979851

Simply adding it to the documentation would be nice :)

**Comment by bvaughn** [comment]
Documentation PRs are welcome:
https://github.com/reactjs/reactjs.org/blob/master/content/docs/context.md

**Comment by M-Izadmehr** [comment]
@bvaughn Hey, I just added a small PR in docs for `Context.displayName`.

**Comment by bvaughn** [comment]
I'm going to go ahead and close this issue then, since the docs aren't even here. :)
