### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cleverKris** [facebook/react#16857]
![issue](https://user-images.githubusercontent.com/50655436/65403704-a53ebb80-de07-11e9-91bc-0d6580315913.png)

**Comment by kunukn** [comment]
Could you please add more information? 

Do you want to request a *feature* or report a *bug*?
?

What is the current behavior?
? 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle or CodeSandbox example below:
?

What is the expected behavior?
?

Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?
?

**Comment by bvaughn** [comment]
This issue does not have enough any to be actionable, so I'm closing it.

The new GitHub issue asks for the following info. If you're able to provide it, we can re-open:

---
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by cleverKris** [comment]
你好，我项目的版本是"react": "^0.14.8","react-dom": "^0.14.3"。
react官网博客有说到这样一篇文章，https://reactjs.org/blog/2019/08/15/new-react-devtools.html，（与14不兼容的解决方案）
但是我使用npm install --save react@^16.8.0 react-dom@^16.8.0，控制台仍然会报错。
错误：Error: Expected to find root ID





------------------ 原始邮件 ------------------
发件人: "Kunuk Nykjær"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 晚上8:02
收件人: "facebook/react"<react@noreply.github.com>;
抄送: "Kong"<751359974@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [facebook/react] help (#16857)




Could you please add more information?
 
Do you want to request a feature or report a bug?
 ?
 
What is the current behavior?
 ?
 
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle or CodeSandbox example below:
 ?
 
What is the expected behavior?
 ?
 
Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?
 ?

**Comment by cleverKris** [comment]
Hello, my version of the project is "react" : "^ 0.14.8", "the react - dom" : "^ 0.14.3".
The react website blog has said such an article, https://reactjs.org/blog/2019/08/15/new-react-devtools.html, (with 14 incompatible solutions)
But when I use NPM install --save react@^16.8.0 react-dom@^16.8.0, the console still reports errors.
Error: Expected to find root ID







------------------ 原始邮件 ------------------
发件人: "Brian Vaughn"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 晚上11:44
收件人: "facebook/react"<react@noreply.github.com>;
抄送: "Kong"<751359974@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [facebook/react] help (#16857)




This issue does not have enough any to be actionable, so I'm closing it.
 
The new GitHub issue asks for the following info. If you're able to provide it, we can re-open:
 
 
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:
 
What is the expected behavior?
 
Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?

**Comment by cleverKris** [comment]
Hello, my version of the project is "react" : "^ 0.14.8", "the react - dom" : "^ 0.14.3".
The react website blog has said such an article, https://reactjs.org/blog/2019/08/15/new-react-devtools.html, (with 14 incompatible solutions)
But when I use NPM install --save react@^16.8.0 react-dom@^16.8.0, the console still reports errors.
Error: Expected to find root ID





------------------ 原始邮件 ------------------
发件人: "Kunuk Nykjær"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 晚上8:02
收件人: "facebook/react"<react@noreply.github.com>;
抄送: "Kong"<751359974@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [facebook/react] help (#16857)




Could you please add more information?
 
Do you want to request a feature or report a bug?
 ?
 
What is the current behavior?
 ?
 
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle or CodeSandbox example below:
 ?
 
What is the expected behavior?
 ?
 
Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?
 ?

**Comment by bvaughn** [comment]
Can you provide a link to your project (or a smaller example on [Code Sandbox](https://codesandbox.io/)) that reproduces this problem? Sounds to me like you may still be using an older, unsupported version of React.

**Comment by cleverKris** [comment]
I'm sorry, the project in our company has not been launched yet, but I can describe the problem more specifically. Now I see in the package. Json file in the project that the react version is 0.14.8 and the react-dom version is 0.14.3. I have a developer tool for Google,react-devtool allows you to view in-component data and parent-child structure relationships while developing react. So I need to use it in the project, but the react - devtool updated, said one blog to 14 version does not support the react, need to upgrade to 15 or 16, blog link: https://reactjs.org/blog/2019/08/15/new-react-devtools.html. The error was reported because of this react-devtool error. I then executed a command to upgrade the react in the project to 16.8, because you can also use the new feature hooks. The command is: NPM install --save react@^16.8.0 react -- dom@^16.8.0. After that, the versions of react and react -- dom in the package. 1. Using react-devtool also reports errors. 2. Using react. UseState (), which typescript told me didn't exist on react. I wondered if I had the wrong command to upgrade react, or if there were other dependencies I needed to upgrade. Thank you and look forward to receiving your reply!




------------------ 原始邮件 ------------------
发件人: "Brian Vaughn"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 凌晨0:25
收件人: "facebook/react"<react@noreply.github.com>;
抄送: "Kong"<751359974@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [facebook/react] help (#16857)




Can you provide a link to your project (or a smaller example on Code Sandbox) that reproduces this problem? Sounds to me like you may still be using an older, unsupported version of React.

**Comment by bvaughn** [comment]
Sounds like your upgrade didn't go correctly. I don't think I'm going to be able to help with the limited amount of info I have here though/

**Comment by bvaughn** [comment]
You can always install the old version of the extension if you want, which does support v14:
https://reactjs.org/blog/2019/08/15/new-react-devtools.html#how-do-i-get-the-old-version-back

**Comment by cleverKris** [comment]
Thank you for your reply, I will try according to the expansion of the official website, thank you, chat back




------------------ 原始邮件 ------------------
发件人: "Brian Vaughn"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 晚上10:38
收件人: "facebook/react"<react@noreply.github.com>;
抄送: "Kong"<751359974@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [facebook/react] help (#16857)




You can always install the old version of the extension if you want, which does support v14:
 https://reactjs.org/blog/2019/08/15/new-react-devtools.html#how-do-i-get-the-old-version-back
