### ISSUE TITLE
Suspense + useEffect?

### ISSUE THREAD

**Issue by javierguzman** [facebook/react#16852]
Hello all,

First time around here so thank you very much for all your great work and providing this technology to the rest :)

I want to report a bug even though maybe is the expected behaviour. I have a component that is wrapped by Suspense. Such component has a useEffect hook that throws a promise and such promise is not caught by anybody. However, if I throw the promise in the "body" of the function, that is, not inside the hook, it works as expected.

I have created this stupid sandbox, my expected behaviour would be to have WAITING forever...

https://codesandbox.io/embed/suspense-with-useeffect-u14br

Thank you in advance.

**Comment by acdlite** [comment]
Thanks for filing the issue, and for your repro case!

This is by design. You can only suspend from inside the body of the component.

The conceptual explanation is that effects are things that fire upon successful completion of a render — you can't suspend a render if it already completed.
