### ISSUE TITLE
bug on ie/edge v16.9 (scheduler) 

### ISSUE THREAD

**Issue by artola** [facebook/react#16855]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
It seems that scheduler v0.15.0 use methods from window (e.g., `setTimeout`, `requestAnimationFrame`) that are not properly bound to `window`, breaking in ie11 and edge with react-dom v16.9.0.
Problem in PRODUCTION mode (development is ok).

**Repo (full example)**: https://github.com/artola/react-bug

See [README](https://github.com/artola/react-bug/blob/master/README.md) in the repo for a detailed explanation.

**What is the expected behavior?**
It should work as in previous versions, e.g., v16.8.6

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Offending version: v16.9.0
Affected browsers: ie (confirmed ie11, might be others) and edge (17 might be others).
Former versions v16.0.0 up to v16.8.6 working properly.

**Comment by bvaughn** [comment]
cc @acdlite

**Comment by artola** [comment]
Using v16.12.0 the problem is not present (might be solved somehow between v16.9.0 and v16.12.0).
