### ISSUE TITLE
Calling setState multiple times in hooks causes the previous state to be overridden

### ISSUE THREAD

**Issue by Sayid1** [facebook/react#16858]
[online link](https://codesandbox.io/s/condescending-clarke-nn93u)

The fetch is a public method of querying data and needs to be independent
Since setState is asynchronous, the visible value of setState in fetch is still false
How can I put the popover to close and update the list without changing the fetch method?

thanks advance! :)

**Comment by kunukn** [comment]
Your `setState` call is batched and the last wins.

You could use multiple `useState` instead, depends on your use-case.
There are different options to solve the issue. This is one option.

```jsx
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [users, setUsers] = useState([
    {
      id: 1,
      name: "Jack"
    },
    {
      id: 2,
      name: "Tom"
    }
  ]);
```

Example:
https://codesandbox.io/s/react-users-and-modal-dialog-y49ke

**Comment by bvaughn** [comment]
[State updates might be async and batched](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous), as they are in the context of an event handler. This provides better performance since it eliminates additional, unnecessary renders.

Use cases like the example you linked to should use the update function pattern:
https://reactjs.org/docs/hooks-reference.html#functional-updates

This way multiple updates can accumulate (rather than override or conflict with each other).

Put another way:

```js
const [state, setState] = useState({
  foo: "abc",
  bar: 123
});

// Do this!
setState(prevState => {
  return {
    ...prevState,
    foo: "def"
  };
});
setState(prevState => {
  return {
    ...prevState,
    bar: 456
  };
});

// Don't do this!
// It only works if setState is called synchronously (which is often not the case).
// Otherwise your change to "foo" will be overridden by the old "foo" value when you change "bar".
setState({
  ...state,
  foo: "def"
});
setState({
  ...state,
  bar: 456
});
```

**Comment by Sayid1** [comment]
Thank you all :)

**Comment by tjmosia** [comment]
@bvaughn Thank you so much! You saved me Hours of Sweat and Frustration.

**Comment by pandumalik** [comment]
@bvaughn thank you so much, you're life saver

**Comment by jubazz** [comment]
save my life

**Comment by zackAJ** [comment]
thank you guys ! React sucks. going back to Vue.

**Comment by lufinkey** [comment]
I found a way better workaround to this which is just to have your state variable be a `let` instead of a `const` and assign to it right before calling your setter

Example:

```javascript
let [myArray,setMyArray] = useState([]);

// ...
// later, wherever your setter is getting triggered:

myArray = [...myArray, newItem];
setMyArray(myArray);
```
