### ISSUE TITLE
DevTools: hooks with numbers, strings or booleans show as undefined

### ISSUE THREAD

**Issue by cxcorp** [facebook/react#16859]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The `useState` hook's value is shown as `undefined` in React DevTools if the value is a string or a number. Clicking on the bug icon prints the correct values to console.

![image](https://user-images.githubusercontent.com/21111572/65421153-b7225d80-de0b-11e9-8a69-a31836a41c7c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React.**
CodeSandbox: https://codesandbox.io/s/keen-colden-syb7r
Direct link to page so you can see the DevTools: https://2km9v.csb.app/

**What is the expected behavior?**
The DevTools should show the correct value of the hook.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.9.0.
Google Chrome [Version 77.0.3865.90 (Official Build) (64-bit)] running on Linux x64.

This issue appeared after version 4.1.0 (9/19/2019) of the DevTools Chrome extension.

Might be same bug as #16843 but this one appears without any complicated reproduction steps.

**Comment by cxcorp** [comment]
Looks like the issue also appears with boolean values.

**Comment by arkuar** [comment]
Having the same problem.
The extension worked fine after I downgraded React to version 16.8.6

**Comment by bvaughn** [comment]
Looks like one major difference between 16.8 and 16.9 is that 16.9 shows editable hooks, so it's using a different code path. This means it's probably related to #16700 somehow.

**Comment by bvaughn** [comment]
Should be fixed by #16867

**Comment by bvaughn** [comment]
This fix will be released with 4.1.1 (sometime soon)

**Comment by bvaughn** [comment]
This fix has just been published to NPM and posted to Chrome/Firefox as v4.1.1
