### ISSUE TITLE
Difference between setState({ a: 1 }) and state.a = 1; setState({});

### ISSUE THREAD

**Issue by zxh19890103** [facebook/react#16856]
I'm confused with it. Some days ago, I developed a React app as demo. I found these two ways 
to update can lead to the same effect.

`
setState({ a: 1 });
`

and

`
state.a = 1; setState({});
`

So is this matter?

**Comment by yuanoook** [comment]
It's the difference between recommended practice and others.
Explained here https://github.com/facebook/react/issues/12977
