### ISSUE TITLE
Context api is re initial reducer in interval 

### ISSUE THREAD

**Issue by nimahkh** [facebook/react#16850]
@gaearon 
**Do you want to request a *feature* or report a *bug*?*bug*

**What is the current behavior?**
i have this context settings 

```
export const BalanceContext = createContext();
export const BalanceStateProvider = ({reducer, initialState, children}) => (
    <BalanceContext.Provider value={useReducer(reducer, initialState)}>
        {children}
    </BalanceContext.Provider>
);

export const useBalanceStateValue = () => useContext(BalanceContext);
```
then i wrap my component with provider :

```
<LoginStateProvider initialState={initialState} reducer={reducer}>
                        <BalanceStateProvider initialState={initialBalanceState}
                                              reducer={balanceReducer}>
                                                      <App/>
                        </BalanceStateProvider>
</LoginStateProvider>
```

inside App : 

    const [balances, dispatch] = useBalanceStateValue();
    const [auth,] = useLoginStateValue();
    setInterval(()=>{
        console.log("Balances from Context ",balances)
    },3000)

it shows context api , then initial value . and repeated it , 

**What is the expected behavior?**

it has to show just context value , not initial values . 

`
the value inside of devtools is correct 
`

**Comment by bvaughn** [comment]
Can you bundle this up into a Code Sandbox that shows the problem you're describing, rather than a couple of separate snippets?

**Comment by nimahkh** [comment]
> Can you bundle this up into a Code Sandbox that shows the problem you're describing, rather than a couple of separate snippets?

i resolved it , the problem was for my life cycle , hooks are very sensitive
