### ISSUE TITLE
hooks bug with react-router

### ISSUE THREAD

**Issue by Zaynex** [facebook/react#16861]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
When I change the route, hooks bug comes.
click the `button`.

example below:
https://codesandbox.io/embed/react-router-basic-o3x2k

**What is the expected behavior?**
If it's not a bug, how can i fix it?
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- React@latest 
 - Chrome76.0.3809.100 （64)
- React-router-dom@latest

**Comment by koba04** [comment]
@Zaynex 
This is a fixed version.
https://codesandbox.io/s/react-router-basic-6vcvu

You should use Hooks in function components.
In this example,  You use `Share` and `Room` components as a function like `return view(routeProps);`, which is not in a function component.
So you should use these components as function components like this.

```
  const getViews = routeProps => {
    const name = routeProps.location.search.substr(1) || "room";
    const View = Views[name];
    if (View == null) return;
    return <View {...routeProps} />;
  };
```

**Comment by bvaughn** [comment]
Thanks for taking a look at this, @Zaynex. That's the correct answer.

**Comment by Zaynex** [comment]
@bvaughn  @koba04  thanks.
