### ISSUE TITLE
Wrong DOM calculations between renders in Firefox

### ISSUE THREAD

**Issue by elrumordelaluz** [facebook/react#16885]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Using `useCallback` through a custom `hook` to measure DOM node offsets, the first render returns wrong values due to yet not applied _styles_, FOUT or related.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Following [this example on docs](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node), adapting to return _offset_ instead of _bounding rect_, seems that due to yet not applied _styles_, the first `render` gets different measures that the following ones.

[Here is a sandbox](https://codesandbox.io/embed/focused-fast-452bc) with a reproduction, where the first render the red `outline`'s width is large as an `h1` default _styles_ (`display:block` and default _font_) and after `hide/show` it, the `outline` match the `h1` styles.

![react](https://user-images.githubusercontent.com/784056/65577787-cbce3500-df74-11e9-9425-c5c42fee69ca.gif)

Here is also the question [asked on _StackOverflow_](https://stackoverflow.com/questions/58058965/solve-lifecycle-difference-measuring-dom-nodes-in-react).

**What is the expected behavior?**

To return always the measurement that match the DOM element with styles applied.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Since I switched to _Firefox_ as my default browser [time ago](https://twitter.com/elrumordelaluz/status/1069885713439752193), thanks to this template _Issue_ question I found the **most interesting part of this bug**: seems to only happen in _Firefox_!

In that case, please let me know if the _issue_ is more related on _browser vendor_ and I'll close the issue to migrate in teh correct bug tracker.

Following there is a _screen capture_ comparing the behaviour between _Safari_ (left one), _Chrom_ (right bottom) and _Firefox_ (right top).

![react](https://user-images.githubusercontent.com/784056/65578609-62e7bc80-df76-11e9-8390-c8d91b6c4c98.gif)

**Comment by kunukn** [comment]
If you leave remove the CSS font-family definition, you will notice it behaves correctly.

This is probably due to the fonts being downloaded and rendered after the initial DOM render.
One solution might be render that component after the fonts have been downloaded and rendered.

**Comment by elrumordelaluz** [comment]
Thanks @kunukn but in my case seems to persist the issue, look [here](https://pasteboard.co/Iz2FEmW.gif) 

Keep in mind that the issue seems to be only happen in Firefox browser.

**Comment by bvaughn** [comment]
Did you try to repro this bug without React?

Same thing seems to happen in Firefox with just plain JavaScript:
https://codesandbox.io/s/vigorous-wave-sgmsw

Going to close this as not a React bug. Seems like a browser quirk.

**Comment by elrumordelaluz** [comment]
Thanks @bvaughn. I supposed is a FF bug when compiled the _brwoser_ and _React_ versions of the _Issue_ template. Thanks again!

**Comment by elrumordelaluz** [comment]
For information here is the `bug` filled @ _Bugzilla_: https://bugzilla.mozilla.org/show_bug.cgi?id=1584088

Thanks again for the inputs!
