### ISSUE TITLE
Error: Invalid operand to 'in': Object expected ==> IE10

### ISSUE THREAD

**Issue by Veerbhadra277** [facebook/react#16886]
Getting "_Invalid operand to 'in': Object expected_"  error, in react application, I haven't used 'in' operator throughout my application, it seems while bundling react application operator inserted and caused this issue/error.

any help on above issue will be appreciated 

Similar issue for IE 11 but fixed now,
 link -> http://github.com/material-components/material-components-web/issues/2626

**Comment by threepointone** [comment]
I don't think React uses any code like this either, but it's hard to comment without an example application, or a reproducing usecase on codesandbox or as a plain git repo. Please share.

**Comment by Veerbhadra277** [comment]
Hey sunil thanks for reply !!!
please note following git proj of simple application getting failed in ie10

https://github.com/Veerbhadra277/TestReactjss

**Comment by bvaughn** [comment]
I'm a little skeptical of the repro shared, since it doesn't seem to have added the [`Map` and `Set` polyfills required for IE9 and IE10](https://reactjs.org/docs/react-dom.html#browser-support). This means that an error like `'Set' is undefined` would be expected. (Just confirmed on a fresh VM.)

**Comment by bvaughn** [comment]
After adding those polyfills, the repo you linked to works fine in IE10, so I'm going to close this issue for now.
