### ISSUE TITLE
eslint-plugin-react-hooks feature request: enforce naming convention for useState()

### ISSUE THREAD

**Issue by mbrowne** [facebook/react#16908]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

There is currently no rule to enforce the standard naming convention for `useState`.

**What is the expected behavior?**

It would be great to have a rule to enforce the standard naming convention for `useState()`:

```
const [x, setX] = useState(...)
```

For example, the rule would consider this an error:

```
const [x, setFoo] = useState(...)
```

This would ensure that all useState variables followed the same convention, i.e. `${varName}` and `set${upperFirstVarName}`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All versions with hooks

**Note**

I originally submitted a feature request for eslint-plugin-react: https://github.com/yannickcr/eslint-plugin-react/issues/2417. It was suggested that I make the feature request here instead. I'm not sure which plugin would be the more appropriate place for this.

**Comment by karlhorky** [comment]
@mbrowne would you be open to creating a new issue for this? It would be nice for beginners to learn!

**Comment by mbrowne** [comment]
Sure:
https://github.com/facebook/react/issues/19883

**Comment by karlhorky** [comment]
Thanks, will watch there!
