### ISSUE TITLE
Click events not fired on mobile on long touch/click

### ISSUE THREAD

**Issue by ripcurlx** [facebook/react#1690]
Hi! 
I've a problem using react in Chrome/35.0.1916.17 on Android: If I make a long touch on a e.g. button the click even is not fired.
If I just press it quickly everything works as expected. I do get TouchStart, MouseDown, TouchEnd on these long clicks (even I haven't set React.initializeTouchEvents(true);).

I experience the same behavior with the 0.10.0 release and also if I build it fresh from master.

**Comment by spicyj** [comment]
I don't think we're going to do anything here.
