### ISSUE TITLE
Stateless function components cannot have refs.

### ISSUE THREAD

**Issue by Saifu0** [facebook/react#16906]
After applying Route and Link I am facing this problem.
Stateless function components cannot have refs.
▶ 22 stack frames were collapsed.
./src/index.js
src/index.js:7
   4 | import App from './App';
   5 | import registerServiceWorker from './registerServiceWorker';
   6 | 
>  7 | ReactDOM.render( <App />, document.getElementById( 'root' ) );
   8 | registerServiceWorker();
   9 | 
  10 | 

![Screenshot from 2019-09-26 21-43-49](https://user-images.githubusercontent.com/43892879/65705903-f0c2c500-e0a6-11e9-9332-54c2270b010f.png)

**Comment by bvaughn** [comment]
`Route` and `Link` are from react-router, not react. I suggest you open an issue on that repo: https://github.com/ReactTraining/react-router
