### ISSUE TITLE
can ReactDOM.render render to body without warning

### ISSUE THREAD

**Issue by whensea** [facebook/react#16902]
**Do you want to request a *feature* or report a *bug*?**
**feature**
**What is the current behavior?**
I want render dom struct like [whatwg says:](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element)
```html
<body>
  <header>...</header>
  <nav>...</nav>
  <aside></aside>
  <main>...</main>
  <footer></footer>
</body>
```
But there get a warning:
index.js:1375 Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.

**What is the expected behavior?**
Without call `ReactDOM.render` multiple times, can i do this  by strictly following the html specification？

**Comment by Brandi623** [comment]
Shut up

**Comment by whensea** [comment]
@Brandi623 if you don't want see this, you can unsubscribe notifications for [react](https://github.com/facebook/react/).

I think react can render components into document.body, just by detecting which node in the body is rendered by the current react instance. If there is no relevant plan here, I will follow the recommended practice.

**Comment by bvaughn** [comment]
@Brandi623 That sort of comment isn't welcome on this repo. Please refer to our code of conduct: https://github.com/facebook/react/blob/master/CODE_OF_CONDUCT.md

**Comment by bvaughn** [comment]
Rendering directly into the body is discouraged for reasons mentioned in the warning you referenced. So far as I know, we still intend to discourage this. It isn't a matter of HTML specification. It's more a concern of which browser extensions people viewing your website might be using, and whether they might interfere with (and cause bugs in) your React app.

As for the specification, none of the tags you listed _need_ to be rendered as direct descendants of the `body` tag. :)
