### ISSUE TITLE
[Feature Request] Allow useEffect/useLayoutEffect to have previous values

### ISSUE THREAD

**Issue by dmytro-lymarenko** [facebook/react#16917]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Say I have some count and an effect described to its update:

```typescript
const [count, setCount] = useState(0);

useEffect(
	() => {
		// I need to do something with the difference of how the count was changed
		// const diff = count - prevCount;
	},
	[count]
);
```
with current implementation I need to use `useRef` to have previous count:
```typescript
const [count, setCount] = useState(0);
const prevCountRef = useRef<number>(0);

useEffect(
	() => {
		// I need to do something with the difference of how the count was changed
		const diff = count - prevCountRef.current;

		prevCountRef.current = count;
	},
	[count]
);
```
which is actually not so bad if I need to track only one diff, right? ;)

**What is the expected behavior?**

So I would like to have previous dependencies right inside `useEffect` like this:

```typescript
const [count, setCount] = useState(0);

useEffect(
	([prevCount]) => {
		// I need to do something with the difference of how the count was changed
		const diff = count - (prevCount || 0);
	},
	[count]
);
```
So the callback in useEffect gets the same array as dependencies but with previous values.
For first render we can pass to the callback either empty array or undefined.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "^16.9.0"

**Comment by threepointone** [comment]
Do you think you could encapsulate this as a custom hook instead?

**Comment by dmytro-lymarenko** [comment]
@threepointone I think yes:
```typescript
function useCustomEffect<Dep extends any[]>(
	callback: (prevDependencies: Dep | null) => void | (() => void),
	dependencies: Dep
) {
	const prevDependencies = useRef<Dep | null>(null);

	useEffect(() => {
		const cleaner = callback(prevDependencies.current);

		prevDependencies.current = dependencies;

		return cleaner;
	}, dependencies);
}
```
but `callback` is dynamic and is not passed down to useEffect's dependencies array. Would not this way break the rule of `useEffect`:

> Note

> If you use this optimization, make sure the array includes all values from the component scope (such as props and state) that change over time and that are used by the effect.

?
