### ISSUE TITLE
[Feature request] export shallowEqual from shared

### ISSUE THREAD

**Issue by RichieAHB** [facebook/react#16919]
In order to determine whether the default use or `React.memo` will pass / fail it'd be useful to have React export `shallowEqual` from shared in order that this can be inspected / tested. Is there any chance of adding this to the API given the implementation here is important.

**Comment by threepointone** [comment]
Ca you describe your usecase? I don’t know why you’d want to manually call it. You’re always welcome to online the implementation in your app.

**Comment by RichieAHB** [comment]
The use case if for debugging whether a default implementation of `React.memo` on a component would result in a render or not.

The general approach for `shallowEqual` is naturally the safest (rather than adding an additional prop and missing it due to a specific `areEqual` that ignores the new prop), but in order to debug why components are re-rendering it'd be nice to use the actual `shallowEqual` that React uses rather than hoping it matches another implementation indefinitely.

E.g.

```typescript
const logPropDiff = <T extends object>(
    component: SFC<T>,
    log: (diff: Diff<T>, prevProps: T, nextProps: T) => void,
) =>
    memo(component, (prevProps, nextProps) => {
        const allKeys = Object.keys(prevProps).concat(
            Object.keys(nextProps),
        ) as (keyof T)[]

        const diff: Diff<T> = []

        for (const key of allKeys) {
            const prev = prevProps[key]
            const next = nextProps[key]
            if (!React.shallowEqual(prev, next)) {
                diff.push({
                    key,
                    prev,
                    next,
                })
            }
        }

        log(diff, prevProps, nextProps)

        return false
    })
```

Perhaps there's a better way to do this but this has definitely helped in a lot of performance-related places.

**Comment by elyobo** [comment]
Another use case for this is when you'd like to implement your own comparison function for `React.memo`, but fall back to the default behaviour in some cases. My specific case right now is a for components that will never rerender while off screen, but while on screen _might_ rerender; I'd implement this with a comparison function that returns `true` whenever the component is off screen but uses the default comparison when it's on screen.

I _can_ coopy it, but that doesn't guarantee that it's consistent with the standard implementation, which might change (unlikely, I guess). Being able to import and reuse it would avoid copying and allow an easy fallback for custom comparison functions.

**Comment by fritx** [comment]
Why not?

**Comment by elyobo** [comment]
Why not what?

**Comment by fritx** [comment]
@elyobo sorry, I was to mean why not implement this

**Comment by elyobo** [comment]
Right. I don't know why not, they never replied. I have just copied it, because what else can you do :shrug:

**Comment by lopezjurip** [comment]
I also need this feature, here is an use case:

To prevent additional renders I would like to compare only a `hash` or the `updated_at` field coming from the API but keep the rest of the props compared as usual.
```jsx
import { shallowEqual } from "react" // 👈 this is what we ask for

const Memoized = React.memo(MyComponent, ({ user: prevUser, ...prevProps }, { user: nextUser, ...nextProps }) => {
  if (prevUser?.["updated_at"] !== nextUser?.["updated_at"]) return false;
  return shallowEqual(prevProps, nextProps);
});
```

If React doesn't export `shallowEqual` it forces me to find a custom implementation on another package and increase the bundle size

**Comment by elyobo** [comment]
These all seem like valid use cases to me, can we revisit this? It was closed as stale, not by a human deciding against it.
