### ISSUE TITLE
Improve stack trace for errors in render

### ISSUE THREAD

**Issue by vjeux** [facebook/react#1692]
The only useful information from the stack trace when there's an exception in render is saying `React.createClass.render` but doesn't tell which one.

![bqh2farccaavka9 png-large](https://cloud.githubusercontent.com/assets/197597/3279732/ce0d3b9c-f413-11e3-9b47-e02af7e14423.png)

Unfortunately, Chrome dev tools do not accept displayName: https://code.google.com/p/chromium/issues/detail?id=17356

An idea is to update our JSX transform that already adds displayName to also output this crazy pattern, but that makes the stack trace look better

![screen shot 2014-06-14 at 3 19 36 pm](https://cloud.githubusercontent.com/assets/197597/3279726/dcbb8dde-f412-11e3-8702-77687314e9c6.png)

Discussion on twitter: https://twitter.com/seanbrookes/status/477934056835780608/photo/1

**Comment by gaearon** [comment]
This no longer appears the be a problem in Chrome so I am closing:

<img width="712" alt="screen shot 2016-03-26 at 21 16 34" src="https://cloud.githubusercontent.com/assets/810438/14062470/1d662408-f398-11e5-8387-2c9422bb2465.png">
