### ISSUE TITLE
react-devtools: tiny feature request (copy to clipboard related)

### ISSUE THREAD

**Issue by GavBaros** [facebook/react#16924]
Hey guys, great job with the new devtools 💯 perhaps this request can be put in the backlog for a future release as I think it could be quite useful and could save a few steps for developers. 

**What is the current behavior?**
- Copying data to clipboard stringifies all key-value pairs of an object
- When the keys' values happen to be objects or arrays, the values are given in constructor form rather than seeing the contents of that object/array

This is what was copied:
<img width="369" alt="Screen Shot 2019-09-27 at 12 24 19" src="https://user-images.githubusercontent.com/30755017/65767498-f4496100-e125-11e9-8f8b-3faa4516d0c2.png">

This is a pasted version in VSCode:
<img width="399" alt="Screen Shot 2019-09-27 at 12 24 48" src="https://user-images.githubusercontent.com/30755017/65767486-ee538000-e125-11e9-9886-7dcd165c19db.png">

**What is the desired behavior?**
- When I click on "Copy to clipboard" in react-devtools, my copied object's data _keys_ and _values_ are in an unstringified format, or at least, I am presented the option to have this copied in an unstringified format
- The _values_ of each key is readable, e.g: if the value is an object, I can see the expanded object and all its key-value pairs clearly as shown here (this is logged into Chrome console from react-devtools)
<img width="311" alt="Screen Shot 2019-09-27 at 12 29 11" src="https://user-images.githubusercontent.com/30755017/65767365-99176e80-e125-11e9-98d3-98fd9c4889f9.png">

**Comment by ChrisDobby** [comment]
I would like to have a look at this one if that's OK?

**Comment by bvaughn** [comment]
@ChrisDobby It's all yours

**Comment by M-Izadmehr** [comment]
But there is still an issue we want to have in mind, if we just copy the whole object structure, we can basically copy a huge chunk of vdom tree. For example, imagine if you try to copy the props of one of the high-level components (which has `children`) it can essentially lead to cases, that we create a JSON for almost the whole component tree, and I guess that is something we don't want.

This is why we already have **Log this component data to console** so you can copy the parts you want.
Another option is to be able to copy parts of props (have copy option for every input in props).

**Comment by ChrisDobby** [comment]
Yes I see what you mean.  I have an implementation that copies the whole object structure of the props of a component without the children so it could be that this would be OK?  If not then having a copy option for each input could work.

**Comment by bvaughn** [comment]
I am not in favor of adding a copy button for each prop field. That would clutter an already crowded interface.

**Comment by M-Izadmehr** [comment]
I agree, just without children can work fine

**Comment by bvaughn** [comment]
Copying everything but `children` seems reasonable I think.
