### ISSUE TITLE
Improve testing documentation

### ISSUE THREAD

**Issue by spicyj** [facebook/react#1693]
> While I have to agree with the general consensus that testing and React is a breeze, I was thinking that it might be a very good benefit for new users if you updated you documentation page with a few examples under each API method.  Nothing is exactly clear, and when I first wanted to start writing tests I had to dig into the React source code in order to find implementation details. 

and

> I still have no idea how to use them, despite a few tries.  With the descriptors, I don't even know how to test without testutils anymore.  Currently, I've given up on testing my React components until there are examples I can follow.

https://groups.google.com/forum/#!topic/reactjs/1DacqrwosLM

**Comment by debugwand** [comment]
+1 the documentation is too basic, I am having an issue with shallowRender components not tearing down between tests and get no clues from docs. 

Alternatively, have it in getting started and tutorial sections, because tests shouldn't really be considered optional.

**Comment by gaearon** [comment]
We're in a slightly better position now with [TestUtils](https://facebook.github.io/react/docs/test-utils.html) documentation, and [Enzyme](http://airbnb.io/enzyme/) also has good reference docs.

If something is missing, please send a PR with your suggestions to start a discussion.
