### ISSUE TITLE
Provide Context.currentValue

### ISSUE THREAD

**Issue by stephenh** [facebook/react#16930]
Now that hooks have an easy, non-HOC, non-renderprop, way of accessing context:

```
const value = useContext(MyContext);
```

It'd be great to be able to do the same thing from class components, i.e.:

```
const value = MyContext.currentValue;
```

I know there would be caveats like "don't capture the value" (b/c when the context value changes, you'd want to be sure you're using the latest currentValue on each render), but hooks also have caveats about usage.

**Comment by bvaughn** [comment]
Class components already support a static "contextType" prop for this, although it's limited to a single context. You can learn more about it here:
https://reactjs.org/docs/context.html#classcontexttype

**Comment by stephenh** [comment]
@bvaughn thanks! I've seen that/`contextType`.

I want to access the context value from code not directly in the component, similar to how hooks are now able to do that (i.e. a FP component uses a `whateverHook()` that then uses the `useContext()` hook; I want to have a class component call "somethingUtilityCode()" and allow that reusable code to access the current context value).

Granted, the `contextType` is very direct documentation that "this is the context this class consumers/needs", but FP/hook components do not advertise that fact, and instead it's implicit in whatever high-level/low-level hooks they happen to use.

**Comment by stephenh** [comment]
FWIW I vaguely understand the limitations, i.e. since context values are stored per thread:

https://github.com/facebook/react/blob/master/packages/react-dom/src/server/ReactPartialRenderer.js#L786

And the thread is only valid during render, accessing a context value outside of an active render pass is meaningless / impossible to resolve.

Which means a restriction like "`MyContext.currentValue` can only be called during component initialization / constructor / and maybe? lifecycle methods", and would error otherwise (very similar to how hooks error when used outside of the right scope) would be necessary.

Personally I'd be fine with this, given the similarity to "`useContext` only works during hook rendering".

Chatting with a friend (if the above limitation is too strict), in theory in the class component could "capture" the current context values from when it was initialized (i.e. give it an immutable view of the current-known-context-values/stack on init time, which would not change as the renderer proceeded to push/pop context providers later on), then a component instance method (which had access to the internal data) like `this.getContext(MyContext)` could be called at anytime during init/render/etc. by whoever as a `this` pointer would work.

Granted, adding methods onto `Component` like `Component.getContext` is probably hard to justify at this point, so treat that as a musing...

**Comment by bvaughn** [comment]
Yeah, context is only safe to read during the render phase, when React is tracking the "current" value based on where in the tree it is currently working (since the value of context depends on where in the tree a component is).

**Comment by bvaughn** [comment]
This seems like the sort of thing that should be proposed and discussed via an RFC:
https://github.com/reactjs/rfcs#react-rfcs

**Comment by stephenh** [comment]
Cool, that sounds good. Thanks!

**Comment by stephenh** [comment]
@bvaughn FWIW I have the start of this here: https://github.com/stephenh/rfcs/blob/add-context-current-value/text/0000-add-context-current-value.markdown

I just wrote the 1st draft; running it by a few people for edits/clarifications/etc., and then will submit a PR to the rfcs repo. Happy to have feedback before then on it, or just wait until the PR.

Thanks!
