### ISSUE TITLE
Request: Create an ESLint Plugin for warnings and depreciations that will impact major upgrades

### ISSUE THREAD

**Issue by Aghassi** [facebook/react#16948]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
React currently does console output to the browser console to tell developers that they need to be aware of major changes coming so that upgrades will be seamless for them. This works well on smaller sites, or in a situation where your company may have a monorepo and can enforce and track these warnings.

**What is the expected behavior?**
In addition to this behavior, it would be beneficial to React developers if they could have ESLint plugins that had rules for these warnings. Ideally, the ESLint plugin could fix simple cases (methods being renamed) and in more complex cases recommend a codemod.

——-

I’m posting this here as per discussion with @acdlite on twitter. See this thread: https://twitter.com/acdlite/status/1178018850937290753?s=21

Ultimately, it is harder for shops that do micro frontends to ensure everyone is compliant with new React versions. It is also easier to catch things early at build time then to dig around in the browser runtime when there may be other compounding issues.

The other benefit of this would be that it would enable third party libraries to potentially have “day 1 support” for new major React versions because they could follow the rule set and ensure that they are forwards compatible without being caught trying to do it all at once.

Lastly, I’m happy to help drive/contribute to any rule set to make sure it works in our use case.

**Comment by threepointone** [comment]
While I think the react upgrade story is pretty good, you bring up a good point, and it echoes some other feedback I’ve heard recently. We should definitely do better. Thank you for filing this issue.

**Comment by kevinsunny1996** [comment]
Has this been previously worked upon? If yes any PR's for reference? @Aghassi / @threepointone

**Comment by Aghassi** [comment]
@kevinsunny1996 Not to my knowledge, maybe others on the react team can chime in

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Aghassi** [comment]
@acdlite anything you wanted to add to this? I don’t want it to go stale and would like guidance on how I may be able to help contribute to this.
