### ISSUE TITLE
react-scripts build will incorrectly redirect page if URL contains '.html?'

### ISSUE THREAD

**Issue by CongoCash** [facebook/react#16951]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When running react-scripts build on a project with react-router-dom, it will go to the incorrect URL if you have .html in your URL.

`<Route path="*" component={Test} />`

When running react-scripts build, serving the build and navigating the http://localhost:5000/test.html?test=5, the page will redirect to http://localhost:5000/test with a status code of 301 Moved Permanently.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

You can test the issue at [https://github.com/CongoCash/react-router-testing](url).  First run it with 'npm start' and navigate to http://localhost:3000/test.html?test=5. Then run 'npm run build', followed by 'serve -s build' and navigate to http://localhost:5000/test.html?test=5

**What is the expected behavior?**
When you run react-scripts start and navigate to http://localhost:3000/test.html?test=5, it will correctly navigate to http://localhost:3000/test.html?test=5.  Upon running react-scripts build and serving the build, navigating to http://localhost:5000/test.html?test=5 will result in a redirect to http://localhost:5000/test with a status code of 301 Moved Permanently.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This occurs in version 16.10.0 and is affected in Chrome, Safari, Firefox.

**Comment by bvaughn** [comment]
This isn't the right place for this issue to eb reported.

react-scripts bugs should be filed here https://github.com/facebook/create-react-app

react-router bugs should be filed here: https://github.com/ReactTraining/react-router/
