### ISSUE TITLE
When SSR returns a field that is inconsistent with the client side, the client side should prevail

### ISSUE THREAD

**Issue by leiyourong** [facebook/react#16955]
There is the demo:

return page(HTML) is: 
```
<html>
 <head>
    ...
 </head>
  <body>
    <div id='react'>
      <div id="level1">
        <div id="level21">22</div>
      </div>
    </div>
  </body>
</html>
```

And the root Component is:
```
class App extends React.Component {
  render () {
    return (
      <div id="level1">
        <div id="level211">221</div>
        <div className="level33">33</div>
      </div>
    )
  }
}
hydrate(
  <App />,
  document.getElementById('react')
)
```

Finally the page dom will be rendered as:
```
<body>
    <div id="react">
           <div id="level1">
                <div id="level21">221</div>
                <div class="level33">33</div>
          </div>
   </div>
</body>
```

It seems that the id of the first child of div#level1 is incorrect.

React & ReactDom version: 16.8.6

**Comment by gougoushan** [comment]
`<body>
    <div id="react">
           <div id="level1">
                <div id="level21">221</div>
                <div class="level33">33</div>
          </div>
   </div>
</body>`

**Comment by leiyourong** [comment]
Warning only with 'Prop did not match'

**Comment by gaearon** [comment]
This is intentional. React doesn't patch up attributes to improve performance.
