### ISSUE TITLE
Webkit inline styles dissapears in Firefox

### ISSUE THREAD

**Issue by Saibamen** [facebook/react#16957]
**Do you want to request a *feature* or report a *bug*?**: *bug*

**What is the current behavior?**
Missing `-webkit-print-color-adjust: exact;` in Firefox

**Demo**:
1. Run https://stackblitz.com/edit/react-skxixb in Firefox and Chrome
2. Check CSS for `.header`

**What is the expected behavior?**
`-webkit-print-color-adjust: exact;` should be placed in all browsers

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.9.0 and 16.10.1
Windows 10
Firefox 69.0.1

**Comment by Saibamen** [comment]
Workaround:
```
<style dangerouslySetInnerHTML={{__html: `
    .header { -webkit-print-color-adjust: exact; }
`}} />
```

**Comment by kevinsunny1996** [comment]
@Saibamen  did this workaround solve the issue that you were facing?

**Comment by kevinsunny1996** [comment]
And is this a permanent workaround?...Any PR for this?

**Comment by Saibamen** [comment]
@kevinsunny1996 Workaround is workaround, not issue solver.
<style> tag always working. The bug is that `WebkitPrintColorAdjust: 'exact',` should be always rendered as CSS style in any browser

**Comment by necolas** [comment]
Browsers will not set any inline styles with vendor prefixes for different browsers.
