### ISSUE TITLE
JSX transform is difficult to compose

### ISSUE THREAD

**Issue by JannesMeyer** [facebook/react#1695]
Hi,

I would like to use all the available es6 transforms, the jsx transform and the [es6-module-jstransform](https://github.com/andreypopp/es6-module-jstransform) for my JavaScript code.

What I'm using is this:

``` js
var transform = require('jstransform').transform;

var visitors = Array.prototype.concat.apply([], [
  require('es6-module-jstransform').visitorList,
  require('jstransform/visitors/es6-arrow-function-visitors').visitorList,
  require('jstransform/visitors/es6-object-concise-method-visitors.js').visitorList,
  require('jstransform/visitors/es6-class-visitors').visitorList,
  require('jstransform/visitors/es6-object-short-notation-visitors').visitorList,
  require('jstransform/visitors/es6-rest-param-visitors').visitorList,
  require('jstransform/visitors/es6-template-visitors').visitorList,
  require('./transforms/react').visitorList,
  require('./transforms/reactDisplayName').visitorList
]);
var es5 = transform(visitors, sourcecode);
```

The problem is that it's difficult to use those jsx transforms without depending on the whole `react-tools` package which would essentially download a lot of dependencies (another jstransform, etc.) just for those two files, which is why I copied them into a transforms directory in my source tree, but that's obviously a bad solution. Wouldn't it be better to put those jsx-transforms into a separate npm package?

Also, I found a reference to something called `typechecks` in [/vendor/fbtransform/syntax.js](https://github.com/facebook/react/blob/2d048f1f34a7d10cca81336446920822ad7ea67c/vendor/fbtransform/syntax.js#L23), but the appropriate visitor doesn't seem to be open source. In my above example I essentially skipped all the typecheck code that's in syntax.js. Could that be a problem in the future?

Awesome library, by the way!

**Comment by zpao** [comment]
We're deprecating react-tools and jstransform so closing this out.
