### ISSUE TITLE
Tabs are there but not showing up components on React Site

### ISSUE THREAD

**Issue by Dan86de** [facebook/react#16969]
I've installed react dev tools and i see two tabs but tab component does not showing up components....

React Dev Tools Ver.
4.1.3 (9/30/2019)
Chrome Browser Ver.
77.0.3865.90

**Comment by bvaughn** [comment]
What "React site" are you referring to?

Are there any errors in your console?

**Comment by Dan86de** [comment]
I was reffering to Facebook page but its working now after restarting chrome. Thank You problem solved!

**Comment by bvaughn** [comment]
Ah, well thanks for the update~
