### ISSUE TITLE
SuspenseConfig is ignored after timeoutMs

### ISSUE THREAD

**Issue by dsblv** [facebook/react#16961]
I was playing around with some unstable Suspense APIs and noticed this strange behaviour when using `React.unstable_withSuspenseConfig`.

If I understood correctly, the purpose of `timeoutMs` field is to tell React: "I'm okay with this update to not happen within this time. _Then_ you can show fallback."

What it actually says is: "I'm okay with this update to not happen within this time _since previous update_." Meaning if nothing happened for some time, fallback will show up immediately.

Here's this case reproduced in sandbox: https://codesandbox.io/s/romantic-chebyshev-n59dk

Fun thing I noticed: it works as expected if I repeatedly perform updates anywhere in my App. So it may be hard to catch in real world.

My (unfamiliar with codebase) theory is that expiration time for my update is based on last update (commit?) time, but should've been based on the time it was triggered??

I know that this is unstable API and I might be misunderstanding something. Hope my case helps!

---
React 16.10.1
Tested on MacOS 10.4: Safari 13.0.1, Chrome 77

**Comment by onnovisser** [comment]
I encountered this as well.
Opened a PR (#17015) with a test that fails where I would expect it to pass.

**Comment by dsblv** [comment]
This is not an issue with intended APIs `useTransition`/`useDeferredValue`, so I'm going to close, thank you 😌
