### ISSUE TITLE
Invariant Violation: Invalid hook call only for "Apple Mail" browser

### ISSUE THREAD

**Issue by bradtgmurray** [facebook/react#16977]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Seeing the following error message in our Sentry logs.

```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
  at N (/react@16.8.6/umd/react.production.min.js:9:413)
  at q (/react@16.8.6/umd/react.production.min.js:10:177)
  at m (/react@16.8.6/umd/react.production.min.js:17:159)
  at useContext (/react@16.8.6/umd/react.production.min.js:30:482)
  ...
```

The browser is always some variant of "Apple Mail", such as `Apple Mail 605.1.15`

We haven't been able to reproduce this, so I'm unsure of what's causing these issues.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Haven't been able to reproduce, only going off what's being reported to Sentry.

**What is the expected behavior?**
No errors.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6, started happening as soon as we started using hooks in our codebase. Haven't seen any issues with any other browsers.

**Comment by threepointone** [comment]
Interesting! Could you tell me more about your product, and how you use React?

**Comment by bradtgmurray** [comment]
We use react at Faire for all of our frontend development. This particular issue is coming from our marketplace which is running at faire.com.
