### ISSUE TITLE
Design decision: keep defaultProps for functional components

### ISSUE THREAD

**Issue by marcelmokos** [facebook/react#16970]
There are use cases where default props create useful API.

- Since default props are a static property we can take the default prop and use in another component `Component.defaultProps.something` or in a unit test. 
- There is no way to take default values from function default values.  

In a recent article, I have an example that is based on default props and styled-components/emotion. // scroll down to the section `React and Typescript | Example`
https://medium.com/ableneo/best-practices-for-javascript-projects-4b0dd7aaf810

If default props would be removed then there will workaround in a pure javascript way but I would prefer to keep the default props as is since it would make the function unpure.

```
const defaultProps = {
	Wrapper: styled.div``,
};

type Props = typeof defaultProps & {};

const Component = (props: Props): JSX.Element => {
  const {Wrapper} = {...defaultProps, ...props};
  return <Wrapper />
};

Component.defaultProps = defaultProps;

export default Component;
```

**Comment by miraage** [comment]
Mine few cents against this issue:
1) defaultProps cause performance issues (not major issues, but they still slow down an app)
2) Object destructuring makes things easy
3) Use composition over inheritance

**Comment by marcelmokos** [comment]
1. defaultProps cause performance issues (not major issues, but they still slow down an app)

The workaround will have the same performance properties as current default props. 

2,3. Default props can use destructuring internally. The composition of pure functions is preferred. When you use only function destructuring, you do not have access to the default values in case you want to extend or decorate the value.

**Comment by bvaughn** [comment]
This discussion should be part of the RFC thread:
https://github.com/reactjs/rfcs/pull/107

I'm going to close this issue since I don't think it's a good idea to have a forked/disconnected thread spinning up.
