### ISSUE TITLE
Redundant re-rendering even though setting the same state (with useState hook)

### ISSUE THREAD

**Issue by adamkleingit** [facebook/react#16972]
Looks like a small bug in redundant re-rendering of the component even though the state hasn't changed:

[Demo](https://codesandbox.io/s/elastic-hypatia-63rf5)

Explanation:
Call `useState(1)`
In an event handler call `setState(2)` 3 times

Actual behavior:
The first setState re-renders, the second one also re-renders, and the third one doesn't.

Expected behavior:
The first setState re-renders, the second and third ones don't re-render.

React Version: 16.9, 16.8.X
Browser: Chrome
Happens also on production builds

I know it's not really a bug because we shouldn't really care about re-renders, but looks like a code smell that might point to other problems

**Comment by vkurchatkin** [comment]
This is actually documentede here: https://reactjs.org/docs/hooks-reference.html#usestate

> Note that React may still need to render that specific component again before bailing out. That shouldn’t be a concern because React won’t unnecessarily go “deeper” into the tree.
