### ISSUE TITLE
Maybe checkbox can be returned next to the boolean state values?

### ISSUE THREAD

**Issue by inoyakaigor** [facebook/react#16986]
The checkbox was very convenient for switching the boolean variable value

**Comment by bvaughn** [comment]
This was intentionally changed as part of props/state editing interface overhaul in #16700 to enable changing the type of prop values. (This was requested a lot before.) There are no plans to change it back.

React DevTools is trying to mimic prior art from built-in browser devtools UI:
![Screen Shot 2019-10-03 at 9 26 15 AM](https://user-images.githubusercontent.com/29597/66145520-dd8c8980-e5bf-11e9-89cf-106aea76338d.png)
