### ISSUE TITLE
Controlled input cursor jumps when used with layers

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#1698]
See http://jsfiddle.net/Bobris/ZZtXn/2/ (try typing at the beginning of the text box).

**Comment by damianmr** [comment]
Same question here. Any workaround?

**Comment by zigomir** [comment]
@damianmr I also thought I had a problem with it, but later discovered it was my own fault. Are maybe using `value={foo}` where `defaultValue={foo}` might do?

**Comment by damianmr** [comment]
Nope, React shows a warning in such cases.
