### ISSUE TITLE
React devtools blank (standalone version)

### ISSUE THREAD

**Issue by sshmyg** [facebook/react#16988]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/1410608/66061174-96fb4880-e547-11e9-9623-0f1075bc78f6.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Open iOS simulator
2. turn on debugging
3. open react-devtools
4. refresh iOS simulator

**What is the expected behavior?**
Components tree is visible.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react-native@0.61.1
OS: MacOS Mojave 10.14.6

@bvaughn

**Comment by bvaughn** [comment]
Works for me when I just tested it standalone with both iOS Safari and RN running on the iOS simulator.

Since this issue doesn't provide any sort of repro case it's not really actionable.

**Comment by sshmyg** [comment]
@bvaughn What additional info do you need? Logs or something?

**Comment by bvaughn** [comment]
A repro app that I can check out and run, because I'm on the same OS and otherwise and it seems ifne.

**Comment by serjek** [comment]
v4 does not support RN. Try using v3 instead:
`npx react-devtools@3.x`

**Comment by zhili3** [comment]
npx react-devtools@3.x have a error

**Comment by bvaughn** [comment]
> v4 does not support RN. Try using v3 instead:

OP says they are using react-native@0.61.1, which should be supported by v4.

> npx react-devtools@3.x have a error

Not sure what this means. There is not enough info.

**Comment by dalalmj** [comment]
react-devtool v4 does not seem to work with react-native@0.61.1 or 0.61.2 It shows error "react-devtools agent got no connection", downgrade to v3 and it works!

**Comment by vortechron** [comment]
> v4 does not support RN. Try using v3 instead:
> `npx react-devtools@3.x`

solve my problem.

**Comment by jls-tschanzc** [comment]
I can't get it to work for a completely new project.

Steps to repro:
1. `npx react-native init rnplayground --template react-native-template-typescript@6.3.8`
2. `cd rnplayground`
3. `npm install --save-dev react-devtools@3.6.3` (& configure new "debug" script as `react-devtools`)
3. `npx react-native run-ios`
4. `npm run debug`

It won't connect for me.
This is the generated package.json:
```
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "debug": "react-devtools"
  },
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.4"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^24.0.18",
    "@types/react-native": "^0.60.22",
    "@types/react-test-renderer": "16.9.0",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-devtools": "^3.6.3",
    "react-test-renderer": "16.9.0",
    "typescript": "^3.6.3"
  }
```

And btw. the current React Native docs state that you should do `npm install -g react-devtools` which will give you the incompatible version 4 anyways: https://facebook.github.io/react-native/docs/debugging#react-developer-tools

**Comment by nfriedly** [comment]
I was hitting the same issue with react-devtools@4.2.0 and React Native react-native@0.59.8 running in the Android Emulator on macOS 10.14.6.

The React Developer Tools app kind of seems like it's connected - it doesn't show the "how to connect" screen, but it never loads the DOM tree, exactly like the screenshot in the original bug report. Eventually the app logs this error:

```
WARNING
11:44
react-devtools agent got no connection

Stack trace:
  node_modules/expo/build/logs/LogSerialization.js:166:14 in _captureConsoleStackTrace
  node_modules/expo/build/logs/LogSerialization.js:41:24 in serializeLogDataAsync$
  node_modules/regenerator-runtime/runtime.js:45:39 in tryCatch
  node_modules/regenerator-runtime/runtime.js:271:21 in Generator.invoke [as _invoke]
  node_modules/regenerator-runtime/runtime.js:97:20 in Generator.prototype.<computed> [as next]
  node_modules/regenerator-runtime/runtime.js:45:39 in tryCatch
  node_modules/regenerator-runtime/runtime.js:135:19 in invoke
  node_modules/regenerator-runtime/runtime.js:170:10 in <unknown>
  node_modules/promise/setimmediate/core.js:45:4 in tryCallTwo
  node_modules/promise/setimmediate/core.js:200:12 in doResolve
```

I switched to react-devtools@3 and it started working for me.

**Comment by bvaughn** [comment]
@nfriedly `react-native@0.59.8` is definitely too old to support v4 of DevTools. Hm...the standalone DevTools _should_ show a message explaining this and prompting you to downgrade to v3. I'm surprised to hear it didn't show that for you.

React Native v62 is the version that adds support for v4 DevTools. Unfortunately it looks like the latest release in NPM is still v61. My apologies for the inconvenience folks 😞
