### ISSUE TITLE
Problem with accessibility - async setting attributes and inner content 

### ISSUE THREAD

**Issue by ksmolniy** [facebook/react#16987]
React async setting attributes and inner content that makes problems with correct voicing in VoiceOver. For example, I have the case when we set aria-pressed and change text, VoiceOver reads that as "select, Press, toggle button" instead of "select, unpress, toggle button".

How it works on React: https://codesandbox.io/s/quiet-microservice-hb1f9?fontsize=14
How it would work(JS example): https://codesandbox.io/s/vigilant-water-h00kj?fontsize=14

Mac OS v10.14.6
React v.16.8.6

**Comment by gaearon** [comment]
React doesn't set attributes asynchronously. There is some misunderstanding here. Your code should work. Have you verified this actually happens in your sandbox?

**Comment by bvaughn** [comment]
Closing due to lack of repro info
