### ISSUE TITLE
Discussion: Prebuilt binaries and distribution

### ISSUE THREAD

**Issue by yoshuawuyts** [facebook/react#1699]
It's nice to have prebuilt binaries available through the current package managers. Right now there's a prebuilt package for [Bower](https://github.com/reactjs/react-bower), but it'd be nice to also have them on npm / component / nlz.io.

What do you think is the best way to create and maintain these packages?

cc/ @zpao

**Comment by spicyj** [comment]
We don't have plans to do this right now.
