### ISSUE TITLE
Hooks for Class Based Components

### ISSUE THREAD

**Issue by GasimGasimzada** [facebook/react#16995]
I have been thinking a lot about hooks and I want to share my idea on a possible addition that I believe will simplify hook logic -- adding Hooks to classes. I will be able to best explain my idea by giving out an example:

```jsx
const SomeComponent = ({ props }) => {
   const [state, setState] = useState('test');
   const someFn = useCallback(() => {
       ...
   }, [props.name]);
   useEffect(() => {
      someFn();  
   }, [state]);

   ...
}
```

In the code above, we are using hooks to essentially imitate class behaviors. Additionally, because the component is a function, we need to add things like `useCallback`; so that, the function does not get recreated. However, these things have been solved in classes for a very long time. Even React's class components solved these problems. What if this kind of API is added to React:

```jsx
class SomeComponent extends React.NewComponent {
    someFn = () => {
        // use this.props here
    }

    state = new State('test');
    effect1 = new Effect(this.effectFn, [this.state]);

    effectFn = () => {
        const val = this.state.getValue();
        someFn();
        // or state.setValue('some other value')
    }

    render() {
        // you can use this.state.getValue() here
        return (

        );
    }
}
```

What problem does this solve? This eliminates the rule that all hooks have to be at the top of the function. This is because classes already have this behavior implemented. It is intuitive --- you can't use loop or conditions outside the class methods. Secondly, this eliminates hooks such as `useCallback` or `useRef` (for non DOM related things) because functions are not recreated during every render.

What about dependencies in Effect? For dependencies, if a State instance is passed, the Effect hook will check if it is changed using different means (e.g State can have a "stale" member variable that gets updated from reconciler; then the effect uses that variable to check state. Or Effect can store the dependencies and do the normal checking using `state.getValue`).

What about custom hooks? React provides a "CustomHook" base class that developers can use. So, let's say I want to write a hook to fetch data:

```jsx
class FetchHook extends React.CustomHook {
    loading = new State(false);
    data = new State([]);
    error = new State(null);

    effect = new Effect(this.effectFn);

    effectFn = async () => {
        try {
            this.loading.setValue(true);
            const response = await fetch(this.props.url); // i'll talk about this in a bit
            const data = await response.json();       
            this.loading.setValue(false);
            this.data.setValue(data);
        } catch (e) {
            this.loading.setValue(false);
            this.error.setValue(e);            
        }
    }

    getLoading() {
         return this.loading.getValue();
    }

    getData() {
         return this.data.getValue();
    }

    getError() {
         return this.error.getValue();
    }
}
```

Then, we can just add it to our components:

```jsx
class SomeComponent extends React.NewComponent {
    fetch = new FetchHook(someUrl);
    render() {
          const loading = this.fetch.getLoading();
          const error = this.fetch.getError();
          const data = this.fetch.getData();
          // ...
    }
}
```

React.Hook base class (React.CustomHook and React's own hooks are derived from it) has a function called `update` or `run` that initializes all the necessary things for the hooks. The reconciler can check whether the class field is an instance of React.Hook to do the necessary updates etc.

**Why?**

In my opinion, combined with Hooks, React's composability is an implementation of [Entity-Component-System](https://en.wikipedia.org/wiki/Entity_component_system). Game Developers use this technique to set up entities (e.g a Tree or a Vehicle) in their game world. We are essentially using the same technique to set up entities (React Components) for UI. If we go on the comparison route, this is how I see it: Entity = React Component, Hooks = Components, System = React Reconciler + Renderer.

In general, ECS systems really shine when using classes. Writing components and assigning them to entities feels natural. We are using all the class features (class fields, methods, inheritance) to abstract away what is going on behind the scenes. However, with current state of using hooks with functions, React essentially created these class features in for functions. For example, a function is never recreated in a class. So, we need a `useCallback` to imitate the same behavior in function components. Same goes for `useRef` (excluding ref-ing to DOM) to imitate class member variables.

In terms of developer experience, using objects instead of functions have one major difference. At least for me, this is how it was when I was using class components. When using class member variables that are only defined (not called), it makes it simpler to think in React because I can assume that React calls these functions. If they are Hook objects (non-existent yet), I can assume that React calls their respective functions. In these two instances, React is doing the work on the components. However, when using hooks as functions, the flow is reversed: we are telling React what to do instead of letting React do what it wants based on our component logic. It almost looks like we are writing into React instead of just using React. This is something that I experienced when trying to think in Hooks.

**Comment by bvaughn** [comment]
Any proposal of this scope should be an RFC 😄 

https://github.com/reactjs/rfcs/

**Comment by GasimGasimzada** [comment]
Thanks you! I tried to find the RFCs but failed. Sorry about that! Posting it there now.

**Comment by bvaughn** [comment]
No worries. We should update our new issue template to link to it. 😄

I'm going to close this issue for now then and we can carry on the discussion over in the RFC repo.
