### ISSUE TITLE
Focus on undocked DevTools window on element click

### ISSUE THREAD

**Issue by snesjhon** [facebook/react#17009]
**Do you want to request a *feature* or report a *bug*?**
I don't believe this is a bug, but I wouldn't necessarily call this a feature. 

Rather just how the React Components Tab compares to chrome's Elements Tab node selector behavior.

**What is the current behavior?**
If I have an undocked DevTools: 

Elements Tab:
- Using the node selector tool, when I select and click on a node the devtools comes into focus with the node selected. 

Components Tab: 
- Using the component's node selector tool, when I select and click on a node the devtools doesn't come into focus -- though the node is properly selected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I made a screen recording of the current behavior: 
https://www.loom.com/share/ceeb458681774a9ebadc82732546ea54

**What is the expected behavior?**

It'd be great if the Component's element select tool would bring the undocked devTools into focus when selecting node.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

DevTools version: 4.1.3 (9/30/2019)
Browser: Chrome Version 77.0.3865.75 
OS: OSX 10.14.5

I don't recall if this worked in the previous React DevTools.

---

If this is a desired behavior I'd like to help contribute. If so, besides the contributing guidelines what files/docs would be a good to start tackling this?

**Comment by bvaughn** [comment]
I don't think this can be done. The only API an extension panel has is listed here:
https://developer.chrome.com/extensions/devtools_panels#type-ExtensionPanel
