### ISSUE TITLE
[eslint-plugin-react-hooks] Using typeof adds variable to list of necessary dependencies

### ISSUE THREAD

**Issue by wbobeirne** [facebook/react#17008]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If you use Typescript's `typeof` keyword inside of a hook that `exhaustive-deps` watches for, it'll add the variable you `typeof`'d to the list of expected dependencies. However, there's no runtime effect to typeof, it's just for typing. Here's a test case where it'll warn you:

```ts
const [state, setState] = useState(true);

const callback = useCallback((newState: typeof state) => {
  setState(newState);
}, []);
```

results in

> React Hook useCallback has a missing dependency: 'state'. Either include it or remove the dependency array.

**What is the expected behavior?**

`state` should not be an expected dependency

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`eslint-plugin-react-hooks@1.7.0`

**Comment by AlexReff** [comment]
+1 https://codesandbox.io/s/still-cache-r2jbi

**Comment by wbobeirne** [comment]
I'll take a crack at a fix for this, definitely not stale!
