### ISSUE TITLE
synchronous setState makes manage-management w/ hooks very hard

### ISSUE THREAD

**Issue by drcmda** [facebook/react#17016]
It's about the dreaded "zombie-child" problem, which is a known problem, but i would still like to open this issue in order to track it. It currently throws a major wrench into our projects at work (which all use mixed reconcilers).

**Do you want to request a *feature* or report a *bug*?**

I consider it a bug.

**What is the current behavior?**

The long explanation is here: https://kaihao.dev/posts/Stale-props-and-zombie-children-in-Redux

In short, when any dispatch, for instance via useState/useReducer.set(...), can cause an _immediate_ render pass, it allows leaf-components to render before their parents. Components that shouldn't even be rendering, because their parents would exclude them, now do render and access data which doesn't exist in the state model any longer. Rendering isn't deterministic and hierarchical any longer.

Dan Abramov acknowledges this behaviour here: https://twitter.com/dan_abramov/status/959507572951797761

The current solution that Sebastian Markbåge suggested is to wrap dispatches into batchedUpdates.

But that doesn't work in mixed-mode React, where multiple reconcilers are active. So the same component will work in one reconciler, but crash in another, unless the dispatch is wrapped into each batchedUpdates from each reconciler - which puts the burden onto the consumer of the component and makes the component platform dependent.

This problem affects all flex based state managers. Redux for instance. Some fail outright, some do implement batchedUpdates (like Redux), but they will all fail in mixed-mode.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://github.com/react-spring/zustand/issues/64

**What is the expected behavior?**

As Dan Abramov himself said on Twitter, any dispatch should be async. But this was in feb 2018. Is there any news regarding this behaviour?

The churn outlined in the kaihao.dev article above, just to get simple state management, is almost overwhelming. Its conclusion is "Our hands are tied, there's no solution yet to be known." I know this probably isn't a pressing issue, but i hope it can be prioritized.

**Comment by MrIrick** [comment]
Hooks is terrible
