### ISSUE TITLE
Time spent before rendering with a suspense config counts towards timeout

### ISSUE THREAD

**Issue by onnovisser** [facebook/react#17013]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When rendering with a suspense config, time spent before rendering appears to be subtracted from the timeout of the suspense config. If I spend 1 second before triggering an update with a suspense config with a timeout of 2 seconds, it takes only 1 second before the tree suspends.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
- [x] Open PR with failing test (#17015)
- [x] Create CodeSandbox with example (https://codesandbox.io/s/suspense-config-test-sw3fn)
In the sandbox, any time spent before click "Next page", reduces the time the pending state is shown before suspending. If you wait longer than 2 seconds, it immediately suspends.

**What is the expected behavior?**
I would expect the timeout of the suspense config to count from when the update is triggered.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Any version that allows rendering with a suspense config

**Comment by dsblv** [comment]
https://github.com/facebook/react/issues/16961 seems related!

**Comment by onnovisser** [comment]
Closed because it's a duplicate of #16961
