### ISSUE TITLE
getDerivedStateFromProps is not fired on state change in dev mode

### ISSUE THREAD

**Issue by Meshredded** [facebook/react#17025]
In dev mode : 
getDerivedStateFromProps is not fired on state change but is fired on props change.

In prod mode : 
getDerivedStateFromProps is fired on state change and on props change.

**What is the expected behavior?**
getDerivedStateFromProps should fire on state change and on props change.

"react": "16.10.2"

**Comment by threepointone** [comment]
Please include a reproducing example, either on codesandbox or as a git repo

**Comment by echavezNS** [comment]
Can you please give an example?
Are you changing the start of a parent Component? the state of the same component that implements getDerivedStateFromProps? can you elaborate a little bit more?

thanks
