### ISSUE TITLE
Scoped css with pure css string like preact-css?

### ISSUE THREAD

**Issue by dntzhang** [facebook/react#17027]
* [preact-css](https://github.com/Tencent/omi/tree/master/packages/preact-css)
* https://github.com/preactjs/preact/issues/1898

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Can't support scoped css with pure css string.

Is there a relevant vnode hook to implement this feature?

**Comment by threepointone** [comment]
We don’t have any plans to support something like in React, unfortunately. You can consider options like styles-jsx, or many css-in-js libraries in the ecosystem. 

Closing because there’s not anything we can do here right now, but thanks for asking!

**Comment by dntzhang** [comment]
Styled-jsx can't support rpx unit of css.
