### ISSUE TITLE
External tasks read non committed/work-in-progress props outside render phase

### ISSUE THREAD

**Issue by yelouafi** [facebook/react#17024]
**Do you want to request a *feature* or report a *bug*?**

Likely a bug

**What is the current behavior?**

In Concurrent mode, React can split rendering over multiple frames, external tasks (DOM event handlers, intervals ...) perform side effects and should always access committed props (Right?).

But in the linked sandbox example, a scheduled task (using `setInterval`) accessing `this.props` reads actually the work-in-progress props.

The issue happens with class Components, in render phase React mutates the props of the class instance

https://github.com/facebook/react/blob/4c5698400f04bbc6d0b4bd766b0993d0bcb37609/packages/react-reconciler/src/ReactFiberClassComponent.js#L1042-L1045

also the following code indicates that the committed and work-in-progress fibers share the same class instance

https://github.com/facebook/react/blob/4c5698400f04bbc6d0b4bd766b0993d0bcb37609/packages/react-reconciler/src/ReactFiber.js#L413

If React assigns pending props to the class instance but after the render work is interrupted for some reason, we yield back to the browser and we're now outside the render phase, but since both the current and WIP fibers share the same mutable instance, `this.props` will continue to reflect the props of the WIP. If a scheduled task reads `this.props` at this moment it'll see the WIP props while it should rather see the committed props.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

see https://codesandbox.io/s/bold-cache-ytud2

The example simulates some expensive work to force React to split the render work and yield back to the browser. Meantime a class component schedules an interval to send `this.props` to the external world: in this case we imperatively update the content of an external DOM ('Parent.props: ' at the top of the screen) node with `this.props` to highlight the issue.

Steps to reproduce the issue:
 
- wait for the first render to complete 

- modify the `input` below `App` then click submit, this should propagate  new props to its child component `BusyChildren`

- since `BusyChildren` does expensive work, it'll take some time until the new props are committed to the screen. But at the same time the interval task reads the pending props before the work is committed so the top external Dom node shows the work-in-progress props.

**What is the expected behavior?**

For class components, `this.props` should return only the committed props outside the render phase.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The sandbox uses the latest version 16.10.0

The behavior is correct when we start in Sync mode using `React.render`

**Comment by gaearon** [comment]
>If React assigns pending props to the class instance but after the render work is interrupted for some reason, we yield back to the browser and we're now outside the render phase, but since both the current and WIP fibers share the same mutable instance, this.props will continue to reflect the props of the WIP. If a scheduled task reads this.props at this moment it'll see the WIP props while it should rather see the committed props.

Yeah. This is a known problem. This is significant part of the reason we had to pause work on CM and released Hooks first instead. Thanks to closures, they don't suffer from this by default.

While this is potentially fixable, the penalty of traversing the whole tree on abort makes the whole thing not worth it. So I think this is going to be a wontfix for classes.
