### ISSUE TITLE
[Concurrent mode] Scheduled updates are lost when parent state update happens

### ISSUE THREAD

**Issue by albertogasparin** [facebook/react#17028]
**Do you want to request a *feature* or report a *bug*?**
Probably a bug

**What is the current behavior?**
When in concurrent mode (render with `unstable_createRoot`), triggering a state change via an event (eg click) on the parent makes React loose the scheduled updates in the children. See:

https://codesandbox.io/s/react-concurrent-state-bug-sp6zq

Not an expert on concurrent mode here, was just playing around with it. Noticed that when some interactions happen the work (probably moved to the other tree) gets lost if the parent re-renders. You can see by clicking anywhere in the sandbox page vs clicking on the button that changes some local state. But that is just my educated guess on what might be happening.

**What is the expected behavior?**

State updates that are scheduled in children components should happen and the DOM value should reflect the state.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react: 16.10.2
react-dom: 16.10.2

**Comment by dai-shi** [comment]
👍 Linking my comment https://github.com/facebook/react/issues/16396#issuecomment-545003364. I thought it was an issue with use-subscription back then, but it turns out to be a broader issue.

**Comment by dai-shi** [comment]
Hey, you might want to try with the latest experimental channel.
In [my tool](https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode), `0.0.0-experimental-f42431abe` fixes some cases. But not all.

**Comment by acdlite** [comment]
Thanks for the bug report!

I believe this was fixed by https://github.com/facebook/react/pull/18091

You can confirm using `react@0.0.0-experimental-ea6ed3dbb` and `react-dom@react@0.0.0-experimental-ea6ed3dbb`.

I'm going to close this issue, but if the bug persists please comment and we'll reopen.
