### ISSUE TITLE
A lifecycle method "component did catch proptype error"

### ISSUE THREAD

**Issue by finom** [facebook/react#17036]
**Do you want to request a *feature* or report a *bug*?**

A feature. I'd like to have a lifecycle method similar to `componentDidCatch` which catches proptype errors. Every time when a proptype error is raised, I get a long and ugly warning which requires me to debug the app and find a component (sometimes there are hundreds-thousands of them) where the error appeared. Usually I have a complex tree of components and almost every component is a HOC over smaller components. More precise I use https://github.com/acdlite/recompose + enhancers developed by me. 

![image](https://user-images.githubusercontent.com/1082083/66347731-a8848c00-e95d-11e9-8472-7429f269d725.png)

That's only a little part of the error because it didn't even fit into my screen which makes my console look unusable.

My proposal is to provide a lifecycle method which allows to not put this error into console but render it on the place of errorred component (similar to what we do at ErrorBoundary). This would allow to more clearly see where the error appeared and to save time on debugging. Of course this should be available at dev environment only.

We use error boundaries powered by  `componentDidCatch` to catch **actual errors** and I imagine this new method as the tool to catch **potential errors**. There is no difference for me, both need to be fixed, so both need to be output similarly. Does it make sense?

**Comment by bvaughn** [comment]
A new lifecycle [should](https://github.com/reactjs/rfcs#when-to-follow-this-process) go through [the RFC process](https://github.com/reactjs/rfcs#what-the-process-is). I'm going to close this issue. Please open a PR on the RFC repo! :smile:
