### ISSUE TITLE
Error Boundary and Errors Thrown by a Promise

### ISSUE THREAD

**Issue by dcs3spp** [facebook/react#17031]
Hi,

I am learning react and trying to get an Error Boundary component to catch an error from a promise. In the _componentDidMount_ method of a child component I am making an axios request. The only way I can get the Error Boundary component to catch the error from the promise is to to use this.setState(()=> {throw error}) in the catch handler. If I do not use the setState approach and rethrow the error in the catch handler then the Error Boundary component does not catch the error.

Is the setState approach the recommended approach for getting an Error Boundary component to catch a promise or is there a better way? Is there any documentation for Error Boundary components recognising errors thrown by a promise?
 
```ts
componentDidMount(): void {
    console.log('CourseList::componentDidMount');

    const dataSource: RestDataCourse = new RestDataCourse();
    dataSource
      .getCourses()
      .then(courseList => {
        this.setState({ courses: courseList });
      })
      .catch(error => {
        console.error(`Error retrieving courses => ${JSON.stringify(error)}`);
        this.setState(() => {
          throw error;
        });
        // throw error
      });
  }
```

**Comment by gaearon** [comment]
This is expected not to work because there is no way for React to know about your Promise.

**Comment by dcs3spp** [comment]
@gaearon Thanks Dan, so is setState the only way to get that example working? Or, alternatively, is it recommended to listen to errors on a redux store?
