### ISSUE TITLE
findComponentRoot error with Foundation's Modal plugin

### ISSUE THREAD

**Issue by dhruvbhatia** [facebook/react#1703]
_(x-post from the [Mailing List](https://groups.google.com/forum/#!topic/reactjs/qaG_qRMo29o))_

Hi,

I'm working on a project that uses [Foundation's modal system](http://foundation.zurb.com/docs/components/reveal.html), but I've run into a bit of a pain-point.

It seems that whenever a modal launches/closes, Foundation manipulates the DOM in it's own special way, and as a result React's Virtual DOM loses track of what's going on. After this all of React's event handlers break, since the DOM has changed.

I've created a plunk to illustrate this. I basically want the button within the modal to utilise React's _onClick_ event handler and call the _clickButton()_ function, but no dice:
See http://plnkr.co/edit/Z6y5dI?p=preview

Upon clicking the button, I get the following error in the console:

``` javascript
Error: Invariant Violation: findComponentRoot(..., .0.1.3): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables or nesting <p> or <a> tags. Try inspecting the child nodes of the element with React ID ``.
```

I've tried a combination of things including using _forceUpdate()_ in conjunction with Foundation's own modal event system, but I just can't get things to work. This [SO question](http://stackoverflow.com/questions/24239157/how-to-make-react-js-play-nice-together-with-zurb-reveal-modal-form) is related.

Assistance appreciated!

Cheers,

Dhruv Bhatia

**Comment by dyatlov** [comment]
@syranide @dhruvbhatia 
Create a sample based on @syranide' suggestion: https://gist.github.com/dyatlov/aa357617cf0afeb5b19f
Would love to hear some comments as im pretty new to react too

**Comment by iseltsegelt** [comment]
Hii..how r u dear?
