### ISSUE TITLE
typescript-eslint/eslint-plugin@2.3.3  can't install

### ISSUE THREAD

**Issue by zengkaii** [facebook/react#17040]
@typescript-eslint/eslint-plugin@2.3.3: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1".

![image](https://user-images.githubusercontent.com/38418699/66389172-55ace200-e9fa-11e9-9749-b0954b46272d.png)

**Comment by zengkaii** [comment]
![image](https://user-images.githubusercontent.com/38418699/66389201-6b220c00-e9fa-11e9-843a-c47c029b41de.png)

**Comment by threepointone** [comment]
You should probably file the issue on their project page? https://github.com/typescript-eslint/typescript-eslint/issues  It isn’t something React maintains, or is even involved in.

**Comment by liplylie** [comment]
I updated node to the latest version and it fixed this issue.
