### ISSUE TITLE
Different behavior between function and class with event.target.value

### ISSUE THREAD

**Issue by wangjianio** [facebook/react#17041]
**Do you want to request a *feature* or report a *bug*?**

report a *bug*

**What is the current behavior?**

Similar logic but different behavior between function component and class component

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Demo: https://codesandbox.io/s/fervent-faraday-xgw8x
Reproduction steps have written in demo.

**What is the expected behavior?**

I'm not sure but I think class component's behavior should be right.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.10.2 / macOS 10.14.6 / Chrome 77 / Safari 13
React 16.8.0 has same issue.

**Comment by Lukyhenson** [comment]
hey man, how are u? 
so I tried to reproduce what u did, what I found was => 
"When u try overwrite the e.target.value on class component your this.setState(value: e.target.value); it's over e.target.value = e.target.value + "!!!"; on the input u are getting the value from this.state.value, on this case are empty".

if you put your setState after your e.target.value assignment, I think this going to work. Something like that 😄 I hope this works for u.
```jsx
handleBlur = e => {
    e.target.value = e.target.value + "!!!";
    this.setState({ value: e.target.value });
    console.log("ClassInput onBlur:", e.target.value);
  };
```

**Comment by wangjianio** [comment]
@Lukyhenson Thank you.
What I confused is the behavior of the function component.

No matter what order I use, `setValue()` only change the state `value`,
`<Input value={value} />` render strange value.

If set a static string value, these will be more clear.

```js
function handleBlur(e) {
  e.target.value = e.target.value + "!!!";
  setValue('---');
  console.log("FunctionInput onBlur:", e.target.value);
}
```

```js
function handleBlur(e) {
  setValue('---');
  e.target.value = e.target.value + "!!!";
  console.log("FunctionInput onBlur:", e.target.value);
}
```

**Comment by wendy81** [comment]
I think because the order of execution is different, so the result is different.

Function:
function handleBlur(e) {
    setValue(e.target.value);  // 3  because e.target.value below is reassigned, so while it running, it gets the reassign value.
    e.target.value = e.target.value + "!!!";       // 1 
    console.log("FunctionInput onBlur:", e.target.value);  // 2
  }

Class:
handleBlur = e => {
    e.persist();
    this.setState({ value: e.target.value }, () => {
     //4
      console.log(e.target.value);
    });  //  1   first execution, so e.target.value is the input value
    e.target.value = e.target.value + "!!!";   //2
    console.log("ClassInput onBlur:", e.target.value);  //3
  };
