### ISSUE TITLE
Apply props/state/hooks edits on blur

### ISSUE THREAD

**Issue by xuanxuan321** [facebook/react#17043]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
trigger by press enter button
**What is the expected behavior?**
trigger by out of focus or pressing enter button

**Comment by muratcatal** [comment]
hi,
if it's ok, i'd like to work on that issue.

**Comment by muratcatal** [comment]
Hi @bvaughn , i just created a [PR](https://github.com/facebook/react/pull/17062) .
fyi
