### ISSUE TITLE
Ease stubbing component methods

### ISSUE THREAD

**Issue by n1k0** [facebook/react#1705]
I'm working on a project where we're porting code to React, and we use [Sinon](http://sinonjs.org/) for mocks.

I'm having hard times stubbing component spec methods so I could check that they're called appropriately in given certain context:

```js
var Comp = React.createClass({
  displayName: "Comp",

  plop: function() {
    console.log("plop");
  },

  render: function() {
    this.plop();
    return React.DOM.div(null, "foo");
  }
});

var stub = sinon.stub(Comp.type.prototype, "plop");
React.addons.TestUtils.renderIntoDocument(Comp());
// sadly keeps printing "plop" onto the console… and so this fails
sinon.assert.called(stub); // throws
```

1. is this expected or intended behavior? or is this a bug?
2. do you have alternate suggestions to achieve this?

**Note:** Directly stubbing the spec object method works, but then you have to export the component constructor and the spec separately so they're both available in tests… Also, you'd need to stub the spec before even creating the component class; not so convenient:

```js
var CompSpec = {
  displayName: "Comp",

  plop: function() {
    console.log("plop");
  },

  render: function() {
    this.plop();
    return React.DOM.div("foo");
  }
};

var stub = sinon.stub(CompSpec, "plop");
var Comp = React.createClass(CompSpec);
React.addons.TestUtils.renderIntoDocument(Comp());

// plop() is properly stubbed, so you can
sinon.assert.called(stub); // pass
```

What would be great is to have the original spec object attached to the component, so it would ease stubbing part of it in a test env (obviously the attached spec should be the one used internally for this to work). Maybe that could even be a feature only available in \__DEV__. 

Thoughts?

**Comment by jimfb** [comment]
This basically became a request for ES6 classes, which have now been released.
