### ISSUE TITLE
Make it easier to debug (undefined components) in production

### ISSUE THREAD

**Issue by natew** [facebook/react#17059]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?**

So for whatever reason, terser/minification causes a bug where one of my components is undefined during render. What I get is the standard production mode minified error.

For some reason this time, I can't seem to do *any* of the following:

1. See any stack information for the component (React just says "something somewhere is undefined")
2. Set a breakpoint on the error point (for some reason with webpack + devtool sourcemap, chrome isn't letting me do a mid-line breakpoint at any place above the error)
3. Disable Reacts error catching temporarily so I can pause on the actual error
4. Use a development version of React with any ease but with the prod settings (I tried turning off both process.env.NODE_ENV checks but then you get an error `It is not supported to run the profiling version of a renderer (for example, react-dom/profiling) without also replacing the scheduler/tracing)`

A big upgrade here would be to fix all of these (except 2, which is either a Webpack or Chrome bug). Can we get better stacks in production mode? That's the ideal. That with number 3 would be the most helpful: a query like `?disableNiceErrors=true` that prevents React from catching/re-throwing the error later would make it so much easier.

As it is now, it's incredibly painful to debug (already an hour into it and without the breakpoints working on minified React it's hard to really even figure out where besides manual code commenting).

Edit: A fifth would be source maps for react itself in production bundles which may work.

**Comment by gaearon** [comment]
>See any stack information for the component (React just says "something somewhere is undefined")

It would have been helpful to know which invariant you're talking about. Otherwise it's hard to offer anything specific.
