### ISSUE TITLE
Nested forwardRefs don't preserve the displayName property

### ISSUE THREAD

**Issue by SKHecht** [facebook/react#17057]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
React.forwardRef [currently provides support](https://reactjs.org/docs/forwarding-refs.html#displaying-a-custom-name-in-devtools) for displaying a custom display name for a component in DevTools, however, if you use the function on something that was returned by forwardRef, the displayName isn't preserved.

The use case I encountered for this was writing multiple HOCs for injecting different props - each HOC uses the pattern suggested in the React docs for using a custom name, but if I apply more than one HOC to a single component, the name no longer exists.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/react-example-25khw

Notably, look at the tree in DevTools. The name of the component that was wrapped twice shows up as "undefined".
**What is the expected behavior?**
When following code pattern described in the React docs for applying custom names to forwardRefs, you should be able to use a HOC multiple times or use multiple HOCs and still preserve the original component's name.

Perhaps the object returned [here](https://github.com/facebook/react/blob/c898020e015f4ee6f793a652668d6d78b0d43e76/packages/react/src/forwardRef.js) should also have a 'displayName' field?
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I discovered this in a project that is on React 16.8.6, but the codesandbox example shows the issue in 16.10.0.

**Comment by bvaughn** [comment]
This is not a React or DevTools issue. What you're seeing is happening because your name check in the HOC is expecting a function, not an `Object` with a `render` prop like what is returned by `forwardRef`:
```js
const name = ComponentToBeWrapped.displayName || ComponentToBeWrapped.name;
```

If you log `WrappedOnce` and `WrappedTwice` components, you'll see that the second one has "undefined" as its name:
![Screen Shot 2019-10-10 at 8 24 02 AM](https://user-images.githubusercontent.com/29597/66582918-5ac37b80-eb37-11e9-81b8-730cd624e56f.png)

If you _really_ wanted to handle this use case you would need to do something more like:
```js
let name;
if (typeof ComponentToBeWrapped === 'function') {
  name = ComponentToBeWrapped.displayName || ComponentToBeWrapped.name;
} else if (typeof ComponentToBeWrapped.render === 'function') {
  name = ComponentToBeWrapped.render.displayName || ComponentToBeWrapped.render.name;
}
```

**Comment by SKHecht** [comment]
@bvaughn  Is the component inputted into a HOC explicitly expected to _not_ be a `forwardRef`? That would mean this isn't a legitimate use case:

```
function InjectFooFromContext(Component) {
    ... create wrapped component, inject Foo from some Context ...
    ... make forwardRef function, apply displayName based on Component ...
    return React.forwardRef(forwardRef);
}
function InjectBarFromContext(Component) {
    ... similar to above, but with Bar ...
}

...

const MyButton = ({ foo, bar, ...rest}) => {
    ... some React using foo & bar ...
};
export InjectFooFromContext(InjectBarFromContext(MyButton));
```

The documentation on forwardRef doesn't indicate this shouldn't be done, nor that your modified `name` logic is necessary.

**Comment by bvaughn** [comment]
`WrapComponentHOC` is your HOC, you tell me? 😄

There are lots of valid React element types that aren't functions (e.g. `forwardRef`, `memo`, `StrictMode`, `Fragment`, etc. - for that matter "div" and "span"). I think the typical expectation and use case for an HOC is to wrap a function (or class) component though.

`displayName` itself isn't a _necessary_ bit of info, just a nice to have. Functions can be anonymous, names get mangled during production bundling, etc. - it should be okay if `undefined` shows up as a display name in some cases, although you can use the technique I showed above to handle the specific `forwardRef` case.

`forwardRef` is meant to be an escape hatch, not a common use case. It's also an API we hope to eliminate [the need for] with a future release:
https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#move-ref-extraction-to-class-render-time-and-forwardref-render-time

**Comment by SKHecht** [comment]
Alright, that's understandable. Thanks for the help and context!
