### ISSUE TITLE
The create-react-app command failed to install the project properly and run

### ISSUE THREAD

**Issue by shenmashi** [facebook/react#17050]
create-react-app
![image](https://user-images.githubusercontent.com/8580637/66474620-43977600-eac4-11e9-82a3-6528ac327862.png)

**Comment by alexrohleder** [comment]
the first line of the error is saying that you need to upgrade your yarn to a version at least equal to 1.0.0, you are using 0.24.6

**Comment by shenmashi** [comment]
> the first line of the error is saying that you need to upgrade your yarn to a version at least equal to 1.0.0, you are using 0.24.6

thanks!

**Comment by ecreeth** [comment]
You can close this now!
