### ISSUE TITLE
i was trying to pass through Hook effect, and the codes used are declared no where. like ChatApi 

### ISSUE THREAD

**Issue by rubimbura** [facebook/react#17051]
```js
import React, { useState, useEffect } from 'react';

function FriendStatus(props) {
  const [isOnline, setIsOnline] = useState(null);

  function handleStatusChange(status) {
    setIsOnline(status.isOnline);
  }

  useEffect(() => {
    ChatAPI.subscribeToFriendStatus(props.friend.id, handleStatusChange);

    return () => {
      ChatAPI.unsubscribeFromFriendStatus(props.friend.id, handleStatusChange);
    };
  });

  if (isOnline === null) {
    return 'Loading...';
  }
  return isOnline ? 'Online' : 'Offline';
}
```

**Comment by bvaughn** [comment]
This example code from the website is not meant to be copy-pasted as is. It's just an example of how you might call an external piece of code (`ChatAPI` in this case) with `useEffect`. The actual `ChatAPI` code isn't important, just the idea it's trying to convey- **that side effects belong inside of a `useEffect` or `useLayoutEffect` callback and not the main render method.

You might find this section on side effect helpful as to why this is:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
