### ISSUE TITLE
useEffect callback never called

### ISSUE THREAD

**Issue by pschiffmann** [facebook/react#17066]
I want to report a bug. My problem is that the callback function I pass to `useEffect()` is never called in my app. I uploaded a minimal app [here](https://github.com/pschiffmann/react-useeffect-issue) that reproduces the issue.

As you can see, I render a couple of nested components. After the initial render, I update the component state inside a `useEffect()` callback. However, this callback is only executed for the first two components, not for the third level component. The result is that the third and subsequent levels are not rendered at all.

I suspect that this is a bug in React and not a misuse on my side because doing any of the following changes will let the component tree render correctly in all levels:
- Don't use multiple React roots. If I remove the last (yellow) `ReactDOM.render()` call, then the second (red) component tree will render correctly.
- Don't conditionally render child components. Removing the `message !== DEFAULT_MESSAGE` check (`main.tsx`, line 20) causes the component trees to render correctly.
- Use `useLayoutEffect()` instead of `useEffect()`.

If you need additional information to reproduce the issue or have any questions, let me know. I'd like provide any help I can!

**Comment by pschiffmann** [comment]
@kunukn Sorry, I forgot to add an effect condition. I changed the `useEffect()` call (see [diff](https://github.com/pschiffmann/react-useeffect-issue/commit/df2423229847afc99482fe0d6f484bf6ede0ca58)), but the result stays the same: Components level 3 and beyond don't render.

**Comment by vkurchatkin** [comment]
Here is somewhat minimal reproduction:

```js
function useTest() {
  const [effect, setEffect] = useState(false);
  useEffect(() => {
    setEffect(true);
  }, []);

  return effect;
}

function A() {
  const effect = useTest();

  return (
    <div >
      {"" + effect}
      {effect && <B/>}
    </div>
  );
}

function B() {
  const effect = useTest();

  return (
    <div >
      {"" + effect}
      {effect && <C/>}
    </div>
  );
}


function C() {
  const effect = useTest();

  return (
    <div >
      {"" + effect}
    </div>
  );
}

function Other() {
  useEffect(() => {}, []);
  return null;
}


ReactDOM.render(
  <A/>,
  document.querySelector("#root1")
);

ReactDOM.render(
  <Other/>,
  document.querySelector("#root2")
);
```

**Comment by WxSwen** [comment]
i met this issue too.
if i use useLayoutEffect or fallback to class by use componentdidmount will be done.
if you solve this problem, tell me;

**Comment by pschiffmann** [comment]
@WxSwen: I didn't solve the bug, but I found a solution how I can work around this issue. Depending on your requirements, it might or might not help you, but I thought I might just share it. :)

It seems the problem occurs when I have multiple React instances on the page (multiple `ReactDOM.render()` calls). And shortly after I found this bug and opened the issue, I also ran into another challenge with multiple React instances: I wanted to share context between all components on the page, but for that to work, they must be in the same React render tree.

So what I ended up with was to go back to a single React instance. Instead, I call `ReactDOM.render()` only once, render into a disconnected `<div>`, and use React portals to render my individual components into their respective places on the page. For example:

```js
const appRoot = document.createElement("div"); // This div is never attached to the DOM
const comp1Root = document.querySelector("#root1");
const comp2Root = document.querySelector("#root2");
ReactDOM.render(
  <>
    {/* I can place shared context providers here, if I want */}
    {ReactPortal.create(<Comp1 />, comp1Root, "root1")}
    {ReactPortal.create(<Comp2 />, comp2Root, "root2")}
  </>,
  appRoot
);
```

**Comment by WxSwen** [comment]
@pschiffmann Even might not what i want but thanks for your kind and solution

**Comment by aleclarson** [comment]
I've hit this bug with React v16.9 and React Native, using two `AppRegistry.renderApplication` calls.

**Comment by gaearon** [comment]
This looks bad.

**Comment by gaearon** [comment]
Does someone want to turn this into a failing test case for `ReactHooks-test.internal.js`?

**Comment by aleclarson** [comment]
> Does someone want to turn this into a failing test case for `ReactHooks-test.internal.js`?

https://github.com/facebook/react/pull/17335

**Comment by aleclarson** [comment]
Downgrading to React 16.8 is a valid workaround.

**Comment by acdlite** [comment]
Fix has landed in the Next channel: https://codesandbox.io/s/react-typescript-2thgm

I'll cut a release later today. Thanks for reporting!

**Comment by acdlite** [comment]
Fix released in 16.12.0

**Comment by wahyuutomoputra** [comment]
https://github.com/react-navigation/hooks#only-for-react-navigation-v3--v4-not-v5

**Comment by yairEO** [comment]
@poddarkhushbu07 - your "solution" makes no sense and both code pieces are identical in practice 

Alternatively, you can just write:

```js
ReactDOM.render(<App/>, root); // where "root" is an element id
```
