### ISSUE TITLE
'exhaustive-deps' lint rule warns that "Outer scope values" aren't valid when a hook is inside a function

### ISSUE THREAD

**Issue by gerrod** [facebook/react#17060]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Inside a functional component, an inner function with a dependency on value from an outer function triggers the warning, "Outer scope values like '....' aren't valid dependencies because mutating them doesn't re-render the component."

See: https://codesandbox.io/s/custom-hook-repro-3wfly

Here's the crux of the problem

```tsx
const List = (props: IListProps) => {
  const { items } = props;

  // Using the useMemo hook here doesn't complain, e.g. -
  // const names = useMemo(() => items.map(item => item.name), [items]);

  // Using the useMemo hook inside a function complains
  const names = useItemNames();

  return (
    <>
      <h2>There are {items.length} items in the list</h2>
      <section>
        {names.map(name => (
          <div>{name}</div>
        ))}
      </section>
    </>
  );

  ////////////////////

  function useItemNames() {
    // es-lint warns here: Outer scope values like 'items' aren't valid dependencies 
    // because mutating them doesn't re-render the component
    return useMemo(() => items.map(item => item.name), [items]);
  }
};
```

**What is the expected behavior?**
The eslint rule shouldn't be triggered.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
* React v16.10.2
* So far as I can tell, this hasn't worked previously.

**Comment by wendy81** [comment]
const names = useItemNames();
You should delete useItemNames function, and use useMemo directly, then the eslint rule won't be triggrered
const names = useMemo(() => items.map(item => item.name), [items]);
 Look :https://codesandbox.io/s/custom-hook-repro-x7exp

**Comment by gerrod** [comment]
> You should delete useItemNames function, and use useMemo directly, then the eslint rule won't be triggrered

Hiya - yes, I'm aware that fixes the issue - I had that comment in my original source code -
```tsx
// Using the useMemo hook here doesn't complain, e.g. -
// const names = useMemo(() => items.map(item => item.name), [items]);
```
But my argument here is that the rule shouldn't complain irrespective of it being inside a function. There's lots of good reasons to use a function rather than having all your hooks written before your render, for example it means the (arguably) "most important" part of your component - the bit which actually does the rendering - is closer to the top.

**Comment by hugmoro** [comment]
I think I have the same problem, and reading the [doc ](https://reactjs.org/docs/hooks-reference.html#usememo) for `useMemo` I'm not sure it's a valid solution:

> **You may rely on useMemo as a performance optimization, not as a semantic guarantee**. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. _Write your code so that it still works without useMemo_ — and then add it to optimize performance.

**Comment by joeldenning** [comment]
I'm seeing this, too.

**Comment by Solnick** [comment]
This is still an issue. I would like to organize my hooks into functions as @gerrod mentioned.

**Comment by finnp** [comment]
This appears to be still an issue.
