### ISSUE TITLE
The warning for uncontrolled -> controlled inputs is confusing

### ISSUE THREAD

**Issue by vcarl** [facebook/react#17069]
**Do you want to request a *feature* or report a *bug*?**

Bug? Mild DX improvement.

**What is the current behavior?**

Creating an input with an undefined or null value, then later passing a string value, triggers a warning about controlled inputs.

> A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa)

It's my experience in Reactiflux that this warning is unclear to developers with less familiarity with React, or at least with the "controlled" and "uncontrolled" terms.

**Comment by bvaughn** [comment]
FWIW the full warning text is:

> A component is changing an uncontrolled input of type %s to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

I agree that developers may be unfamiliar with the terms "controlled" and "uncontrolled" but that's why we link to the documentation explaining what those terms mean 😄

**Comment by vcarl** [comment]
True, but I still think the lede of "you didn't give it a value, then you did" is pretty buried. This warning feels like it gets asked about more frequently than any other.

**Comment by markerikson** [comment]
fwiw, I can vouch that this comes up fairly often.

I would suggest adding a sentence like "This is likely caused by `value={something}` changing from a defined value to `undefined`".

**Comment by markerikson** [comment]
definitely not stale - #17390 is in progress.

**Comment by vcarl** [comment]
#17070 as well

**Comment by sammy007** [comment]
This warning must be removed it does not makes sense and only leads to tons of stupid empty field definitions just to get rid of it. If react is implemented the way it can't handle that it must be abandoned as dumb  and poorly implemented library.
