### ISSUE TITLE
[DevTools] polish hooks: complex values preview 

### ISSUE THREAD

**Issue by a-x-** [facebook/react#17073]
We create many `useDebugValue` helpers, loggers and so one now, so we can feel less pain.

What matter (**Updated**)
- previewing complex values brifely like chrome devtools does it for arrays, sets, maps, objects,,,

I [wrote related twit](https://twitter.com/mxtnr/status/1178271362890240001) recently with one of my DebugValue helpers. screenshot out here:
<img width="556" alt="Screenshot 2019-09-29 at 14 01 53" src="https://user-images.githubusercontent.com/6201068/66700775-5648bf80-ecfd-11e9-93fe-089d451bcffa.png">
_my named hooks currently require a `label` option unless react babel cannot transform name of variable automatically_

**Comment by bvaughn** [comment]
Big bucketed issues like this can be helpful in some cases, for project maintainers to track a larger initiative, but I'm not a fan of them for feature requests- particularly when some of the features are controversial (like "named hooks", which already has its own huge issue and so really doesn't need to be mentioned again here).

I'm closing this. If you'd like to re-open an issue for the complex value preview, please feel free. I thought one had already been opened but I wasn't able to find it.

The request of copying the name doesn't really seem like a common use case to me. (Why would you need to select+copy text like "State" or "Reducer"?) But you could open that as its own issue as well.

**Comment by a-x-** [comment]
Okay=) I updated description

**Comment by a-x-** [comment]
Excuse me, I don’t know before, that named hooks are controversial. Can you point me to the message, that explains the problem?

**Comment by bvaughn** [comment]
Sure, if you [search React GitHub issues for "named hooks"](https://github.com/facebook/react/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+named+hooks) you'll find issue #16474 which explains in depth why it's kind of a complicated issue.

**Comment by a-x-** [comment]
Thank you
And can you re-open the issue as I updated the description?

**Comment by bvaughn** [comment]
I have made some progress on this this afternoon. Needs more testing (and probably some new unit tests as well) but here's a preview:
![dt-better-previews](https://user-images.githubusercontent.com/29597/70567087-1d389a00-1b4a-11ea-9805-5e684bda23fb.gif)

**Comment by bvaughn** [comment]
Tweaked things a bit more and I think it's pretty close to mirroring what Chrome console does not. Feels a lot better when exploring nested values.

![dt-better-previews](https://user-images.githubusercontent.com/29597/70668318-12eccd80-1c28-11ea-9915-b92d10698b73.gif)

Should be ready to submit a PR soon. Need to update tests.
