### ISSUE TITLE
create-react-app failing

### ISSUE THREAD

**Issue by dylanesque** [facebook/react#17079]
**What is the current behavior?**

On running create-react-app, this is what happens:

`
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error @typescript-eslint/eslint-plugin@2.3.2: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.6.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts --cwd C:\Users\Michael C\Desktop\React\mpqfrontendtest has failed.

Deleting generated file... package.json
Deleting generated file... yarn.lock
Deleting mpqfrontendtest/ from C:\Users\Michael C\Desktop\React
Done.
`

**What is the expected behavior?**

For create-react-app to run normally

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This has never failed for me before. OS is Windows 10, create-react-app version is 3.2.0

**Comment by audiolion** [comment]
you need to update your node version to be in the compatible range. Your node is `11.6.0` and it expects `>=11.10.1`. You could also use any version of node in `^8` or `^10.13`

**Comment by dylanesque** [comment]
Whoops, I thought I was more current than that. Thanks for pointing this out, that was the one version I didn't initially check!

**Comment by dylanesque** [comment]
Closing issue, was due to outdated Node installation.
