### ISSUE TITLE
Want to understand the "is" method logic "react.dom.development.js" line number 4230

### ISSUE THREAD

**Issue by jaswantmandloi** [facebook/react#17076]
/**
 * inlined Object.is polyfill to avoid requiring consumers ship their own
 * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
 */
function is(x, y) {
  return x === y && (x !== 0 || 1 / x === 1 / y) || x !== x && y !== y // eslint-disable-line no-self-compare
  ;
}

Could anybody explain this logic why we are comparing the two previous and next value dependencies in the above fashion?
While it could be simply compared like x === y

This comparison is happening for the "useMemo" dependency comparison.

**Comment by threepointone** [comment]
This is explained on that mdn page itself. Quoting - “This is also not the same as being equal according to the === operator. The === operator (and the == operator as well) treats the number values -0 and +0 as equal and treats Number.NaN as not equal to NaN.”
