### ISSUE TITLE
ReactCSSTransitionGroup leaves DOM nodes with both `leave` and `enter` classes

### ISSUE THREAD

**Issue by victor-homyakov** [facebook/react#1707]
After sequence of fast changes (add/delete operations) nodes under `ReactCSSTransitionGroup` are left stuck with classes `example-leave example-enter-active example-leave-active`. Further state modifications do not change rendered DOM tree. Console has multiple warnings

    transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition. 

Test page: http://jsbin.com/kasurusa/2

1. Place cursor in input field
2. Type l then type Backspace very fast
3. Repeat step 2 few times

Easily reproduces in IE10, but could be also reproduced in Chrome 35.

**Comment by bitplanets** [comment]
+1 I have this sometimes.

**Comment by bitplanets** [comment]
+1 I have this sometimes. (take a look at https://github.com/ccoenraets/pageslider-react it might solve some issues)

**Comment by TylerLH** [comment]
This bug makes me a sad panda

**Comment by tommoor** [comment]
Same issue here, it does seem to be related to changing the classes on an item that is transitioning. Simply adding another element within the transitioning item and changing classes on that fixes the issue.

**Comment by Efimster** [comment]
+1

**Comment by andrelevi** [comment]
+1 causing issues on iOS for me.

**Comment by mfunkie** [comment]
If it really is the issue that @tommoor discussed, it might be a good idea to add that to the docs to tell users to wrap their components with variable classes.

**Comment by caedes** [comment]
@jmarr thx! [TimeoutTransitionGroup](https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx) fix all of my issues.

**Comment by canvaskisa** [comment]
+1 causing issue, when changing browser tab

**Comment by leiserfg** [comment]
@caedes it works for me too!

**Comment by spicyj** [comment]
Merging into #1326, but it sounds like TimeoutTransitionGroup is working for most people.

**Comment by aluksidadi** [comment]
this error `transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition. 
` happened to me when i have other css classes in the child element that are animated.

after i removed those other css classes it worked properly.

i dont know if this the issue, but i just want to point this out here.
