### ISSUE TITLE
Weird behavior with functional components and useState, A bug or "Another rule!"

### ISSUE THREAD

**Issue by mfoncho** [facebook/react#17093]
```React : '16.9.0'```

sample code 
```javascript
import React from "react";
import ReactDOM from "react-dom";

function OptionOne(){
  return <div>Blue pill</div>
}

const OptionTwo = React.memo(function OptionTwo(){
  return <div>Red pill</div>
});


function App() {
  const [ Option, setOption ] = React.useState(null);

  return (
    <div>
      <div>
        <button onClick={e=>setOption(OptionOne)}>Option one</button>
        <button onClick={e=>setOption(OptionTwo)}>Option two</button>
      </div>
      { Option && <Option/>}
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
Well the expected behavior was Option one wasn't suppose to throw an error;
setState in class components didn't mind if a key value was a pure functional component or a class component even, but it seams the useState hook is sensitive to the value passed using the setter. If its another functional component it throws a confusing error, worst if the pure functional component passed to setVlaue of useState hook uses hooks of its own, then you get multiple misleading hooks errors to debug.
So is the useState hook working like its suppose to "A rule not to pass a pure functional component as a value to the setValue of the useState hook" or a bug?

**Comment by jddxf** [comment]
This happens because `OptionOne` is a function. React thinks it receives a [functional updates](https://reactjs.org/docs/hooks-reference.html#functional-updates) and calls it to compute the next state.

`setOption(() => OptionOne)` should work.

**Comment by wendy81** [comment]
@jddxf 
setOption(() => OptionOne)  It works well.

But I think the reason isn't different:

1. setOption(() => OptionOne)
the state Option will be:
ƒ OptionOne() {
  return _ref;
}

2.setOption((OptionOne)  equal setOption((()=><div>Blue pill</div>)
the state Option will be: 
<div>Blue pill</div>
the above equal to:
{$$typeof: Symbol(react.element), type: "div", key: null, ref: null, props: {…}, …}

setOption operation, the above 2 ways are ok, but later  when <Option />  is rendered the second way will pop error.

<Option /> belong to user-defined component, about user-defined component, 
1. built-in component
2. a class/ function
But now we got object. 
{$$typeof: Symbol(react.element), type: "div", key: null, ref: null, props: {…}, …}

That's the reason , I think.

click below link:
https://reactjs.org/docs/components-and-props.html

**Comment by bvaughn** [comment]
Sounds like this question has been answered :smile:

The `useState` hook accepts an [updater function](https://reactjs.org/docs/hooks-reference.html#functional-updates) which is what React thinks you're providing. If you want to actually store a function in state, you'll need a second function like folks showed above 😄
