### ISSUE TITLE
input[type="number"] fires onChange twice when clicking Chrome arrows

### ISSUE THREAD

**Issue by brendancarney** [facebook/react#17098]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
With an `input[type="number"]`, in Chrome (confirmed only on OSX), clicking the up or down arrow inside the input increments or decrements the number twice. See example: https://codesandbox.io/s/silly-voice-syphy. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/silly-voice-syphy. 

```jsx
function App() {
  const [number, setNumber] = React.useState(0);

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <input
        type="number"
        value={number}
        step="1"
        onChange={event => {
          setNumber(event.target.value);
        }}
      />
    </div>
  );
}
```

**What is the expected behavior?**
It should only increment it once. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on React 16.10.2 and 16.8. I've confirmed this happens in Chrome on OSX, but not Firefox on OSX.

**Comment by croraf** [comment]
Works OK on Chrome 77, Ubuntu 18.04. 
I tried Chrome 73 also with Mac 10.14 and it works ok. 
Which version of Chrome and OSX are you using.

**Comment by brendancarney** [comment]
Chrome 77, macOS 10.15

**Comment by brendancarney** [comment]
Thanks to my coworkers for pointing this out: it is actually a Chromium bug that will be fixed in Chrome 78. If you're on macOS 10.15 and Chrome 77, you can see here that this happens without react: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number. 

Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=990863
