### ISSUE TITLE
Question: How to rewrite setState(state, callback) with hooks

### ISSUE THREAD

**Issue by yoyo837** [facebook/react#17109]
First of all, I am sorry that my English is poor.

#14493
#15772 

I found some similar issues, but I think the things I want to explain will be different. When my callback doesn't always do something periodically based on some conditions, it seems that useEffect doesn't quite meet the requirements.

For example, using setState data to modify the DOM, and in rare cases, other processing of the DOM will be required in the callback. But the prerequisites for doing these things can be complex and irregular, so useEffect seems to be difficult to do.

**Comment by ldco2016** [comment]
@yoyo837 , **useEffect** is a hook/function that allows for running a snippet of code one time when the component is first rendered to the screen. You can possibly run the snippet of code multiple times depending on the second argument of `useEffect`.

**Comment by sopranolinist** [comment]
Presumably you can write out the logic to capture the prerequisites for doing your extra DOM processing, yes? Let's say you have this logic in some sort of function:
```
function moreDOMProcessingRequired() {
  if (/*prerequisites met*/) return true;
  return false;
}
```
Then you can write a `useEffect` hook something like this that will run every time your state updates and will do that additional DOM processing if it is required:
```
useEffect(() => {
  if(moreDOMProcessingRequired) {
    // do your additional DOM processing here
  }
}, [myState]);
```
