### ISSUE TITLE
Stateful Imperative Bridge that Wraps React Components

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#1711]
https://github.com/reactjs/react-future/blob/master/01%20-%20Core/07%20-%20Imperative%20Bridge.js

Ideally this should also include a way to wrap a React component as a Web Component.

This will be used to deprecate `setProps` on regular components.

**Comment by jimfb** [comment]
We did this in http://facebook.github.io/react/blog/2015/10/01/react-render-and-top-level-api.html

**Comment by hirusi** [comment]
So there's no official API to do this, essentially?
