### ISSUE TITLE
Lazy load react sub-components created as static variables

### ISSUE THREAD

**Issue by sunil-jhamnani** [facebook/react#17116]
I am using sub components in by react application using static variables something like this:

```
text.jsx
export default function Text() {
  return (<div />)      //dummy code
}

Text.h1 = createComponent('h1', 'h1')
Text.h2 = createComponent('h2', 'h2')
Text.h3 = createComponent('h3', 'h3')
```
In above code, createComponent function will return a react function component and I can use it in any application like this:

```
app.jsx
import Text from './text'

export default function App() {
  return (
     <Text.h1>Hello World</Text.h1>
  )
}
```

Now I have to lazy load the Text component but I am not finding any way how to use those sub-components after that. 
Can anyone help on this?

React version: 16.9.0

**Comment by sunil-jhamnani** [comment]
Any thoughts on this?

**Comment by wendy81** [comment]
change:
Text.h1 = ()=>createComponent('h1', 'h1')
Text.h2 = ()=>createComponent('h2', 'h2')
Text.h3 = ()=>createComponent('h3', 'h3')

It will work well.
https://codesandbox.io/s/lazy-load-react-sub-components-created-as-static-variables-7k5j1

**Comment by wendy81** [comment]
change text.js
```
export default function Text() {
  return <div />; //dummy code
}

Text.h1 = ({ children }) => createComponent("h1", "h1", children);
Text.h2 = ({ children }) => createComponent("h2", "h2", children);
Text.h3 = ({ children }) => createComponent("h3", "h3", children);

function createComponent(parm1, parm2, children) {
  return <div>{children}</div>;
}
```
It will work well.
https://codesandbox.io/s/lazy-load-react-sub-components-created-as-static-variables-7k5j1

**Comment by sunil-jhamnani** [comment]
@wendy81 
So I am using the react lazy and suspense module something like this:
https://codesandbox.io/s/lazy-load-react-sub-components-created-as-static-variables-io6p8?fontsize=14

My question was how can I use the static variables in this case?

**Comment by nortonwong** [comment]
React does not hoist statics. `Suspense` is also expecting to see a `lazy()` component, as opposed to `Text.h1` which will be undefined.

You would have to populate each subcomponent with `lazy()`, e.g.:
```js
export const lazyWithSubcomponents = (supplier, ...subcomponents) => {
  const Lazy = lazy(supplier);
  for (const subcomponent of subcomponents) {
    Lazy[subcomponent] = lazy(() =>
      supplier().then(module => ({ default: module.default[subcomponent] }))
    );
  }
  return Lazy;
};
const Text = lazyWithSubcomponents(() => import('./text'), 'h1', 'h2', 'h3');
```

**Comment by nortonwong** [comment]
Note the caveat in the docs regarding tree-shaking: https://reactjs.org/docs/code-splitting.html#named-exports
So it might be preferable not to use subcomponents.
