### ISSUE TITLE
Change ref mechanism to ids' 

### ISSUE THREAD

**Issue by eitanavgil** [facebook/react#17117]
**Do you want to request a *feature* or report a *bug*?**
A feature request

**What is the current behavior?**
Right now when we write a component and we need a reference to it - we need to use the ref feature. Thats a cool thing but the syntax is a bit cumbersome as the developer needs to write code to declare it and also the JSX part. 

**What is the expected behavior?**
As a suggestions - developers already know and understand the usage of 'id' as a unique attribute of an element. What if the syntax would be something like `<div id="foo" ...>` or  `<div idName="foo" ...>` (copying the syntax of className). 
If React behind the scene would generate a reference with that name, or with adding dynamic-string to it - that would make the code a bit shorter, and more readable and natural
If this is implemented inside an iterator, we can do something like `<div id="{'${index'}_foo}" ...>` and if the developer doesn't apply something dynamically in it - have the compiler throw an error or something.

**Comment by markerikson** [comment]
This was the original "string refs" capability.  It technically still exists, but is effectively deprecated, as it makes the internal implementation much more complex.  So no, I don't see this happening.

**Comment by eitanavgil** [comment]
Thanks !
