### ISSUE TITLE
怎么渲染数据一样，页面布局有很大差异的解决方案

### ISSUE THREAD

**Issue by ming200854** [facebook/react#17110]
现在有很多模板，数据源一样，但是页面布局有很大差异，react可以像之前的tempalte模板一样渲染吗

**Comment by thomaszdxsn** [comment]
业务问题别在这里问

另外给个建议，提问的时候提供尽可能多的上下文，站在别人的角度想想你的问题

我懂中文但是看不明白你说的是什么，“之前的template”是什么意思？

**Comment by ming200854** [comment]
嗯嗯，说的有道理，我确实没有表达好，等我梳理一下再重新发一个
