### ISSUE TITLE
dangerouslySetInnerHTML causes page to scroll to top

### ISSUE THREAD

**Issue by vnankov** [facebook/react#17114]
**Do you want to request a *feature* or report a *bug*?**

* It's a bug
* The problem is only when we get the content from the dangerouslySetInnerHTML property.

**What is the current behavior?**

* When you have anchor tags that should scroll down the page to the related id, instead of scroll down it scrolls up to (0,0) coordinates.
* This is our site, take a look for yourself: https://www.emerchantpay.com/insights/online-payments-germany/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

* It should behave as normal anchor tag and scroll to its relevant id.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

 * It all works fine only for Google Chrome Browser Desktop version and Chrome for Androind. It won't work for Mozila, Safari, etc. for mobile and desktop. Also does not work for any browser on IOS.

**Comment by kunukn** [comment]
My observation:

It is client-side rendered content. Using urls like 
`https://www.emerchantpay.com/insights/online-payments-germany/#card-payments` will scroll to the id `card-payments` if it is in the DOM.

The browser can't scroll to that section if it is not in the DOM. The client-side rendered content is added to the DOM with some latency.

I believe this is a common issue when using client-side rendering and hash-tag page navigation using id.

Solutions I know of: 
* Server-side render content.
* Handle navigation client-side programmatically with `componentDidMount` or `React.useEffect`

**Comment by vnankov** [comment]
Yes, thank you for the response and I totally agree with you about this case.

The problem here is different though. When the entire bundle is shipped to the client and the DOM elements are ready, it won't scroll to them. This problem can be tested on Safari or Mozilla, it work great on Chrome. 

If I place <Link> form 'react-router-dom' it will be just fine. But I can not do that because the (HTML)content is coming from Admin panel and I am not responsible about it. So I still think that the problem is with the dangerouslySetInnerHTML.

Please take another look. I would appreciate the support.

**Comment by kunukn** [comment]
For reference. Here is a programmatical example.

Code
https://codesandbox.io/s/reactjs-scroll-into-element-on-mount-x56oc

```jsx
React.useEffect(() => {
    if (window.location.hash) {
      let element = document.querySelector(window.location.hash);
      if (element) element.scrollIntoView();
    }
  }, []);
```

Test
https://x56oc.csb.app/#c

You don't need react-router for this.

**Comment by vnankov** [comment]
This is what I've tried, because I am with Version 16.2:
```  
componentWillUpdate() {
   if (window.location.hash) {
     let element = document.querySelector(window.location.hash);
     if (element) element.scrollIntoView();
   }
}
```

Still no luck on Safari

**Comment by kunukn** [comment]
@vnankov Have you tried `componentDidMount`? You should execute it when it has been rendered to the screen.

**Comment by vnankov** [comment]
Yep, I tried all of the lifecycle methods but the closes of them was componentWillUpdate, because it fired on every click over the anchor tag. Unfortunately non of them worked on Safari and Mozila. Should I rise a ticket for them? 
Can I use some kind of prefix or method specific for this browsers, do you have any idea? Thanks.

**Comment by kunukn** [comment]
I tested this on desktop: Firefox, Chrome, Edge, IE11, Safari

Have you tested your devices on https://x56oc.csb.app/#c ?
Does it work there?

---

https://caniuse.com/#search=scrollIntoView 
with boolean parameter is supported on all browsers except Opera Mini

https://caniuse.com/#feat=queryselector works on all browsers.

https://caniuse.com/#feat=queryselector&search=location.hash works on all browsers.

**Comment by vnankov** [comment]
Hi @kunukn,

I've tried your example and it works great on all browsers and mobile devices.

I made a strong research and I think that when the content is fetch from API point we get the problem(I experience it with WordPress, maybe the problem is only with this CMS). Here is also another folk with the same problem and no solution to it: https://stackoverflow.com/questions/31687220/react-dangerouslysetinnerhtml-causes-page-to-scroll-to-top

I am still not sure how to fix this. 

Thank you for the support you are giving to me, if you have some way of recreating the problem and see for yourself it would be great.

**Comment by kunukn** [comment]
>think that when the content is fetch from API point we get the problem

Wait until everything has rendered/painted in the browser. 

This includes wait until it has fetched from API. And then wait until the fetched content has been rendered/painted in the browser. 

Then run the client-side `scrollIntoView` code snippet example.

Then urls like these `https://x56oc.csb.app/#c` should be possible to be displayed correctly in the browser.

**Comment by vnankov** [comment]
The content is already fetch and painted to the browser, look at this site: https://www.emerchantpay.com/insights/online-payments-germany/
How would you explain that this is working on Chrome otherwise?

That is not the issue, and this is why the lifecycle methods did not fix the problem.

**Comment by vnankov** [comment]
<img width="559" alt="Screen Shot 2019-10-24 at 2 53 55 PM" src="https://user-images.githubusercontent.com/12615872/67483269-20e19180-f66e-11e9-883e-8b898e14fc0c.png">
The issue is regarding click on this links, not on https://example.com/some-route#something

**Comment by kunukn** [comment]
dangerouslySetInnerHTML is applying innerHTML to an element. 
I don't see how the issue you are experiencing should be Reacts fault.

---

As a quick-fix for your case, until we have a better fix, you could use `preventDefault` on the `a` links click and apply onClick event that executes the given `scrollIntoView` code snippet. 

Your first two links seems broken. It could not find the id. I got it to work in Safari by using the trick provided.

Here is an example.

```jsx
const goToSection = event => {
    event && event.preventDefault();   
    if (window.location.hash) {
      let element = document.querySelector(window.location.hash);
      if (element) element.scrollIntoView();
    }}

<a href="#something" onClick={goToSection}>go to this section</a>
```

I tested this in the Safari browser using vanilla JavaScript eventlistener binding.
