### ISSUE TITLE
DevTools option "Site access" giving "Not a valid web address"

### ISSUE THREAD

**Issue by willxy** [facebook/react#17120]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In Chrome, in React Developer Tools extension, Details (settings), option "Site access: Allow this extension to read and change all your data on websites you visit:", selecting "On specific sites", and typing in "http://localhost/", it gives error "Not a valid web address" and will not add the site.  Similarly, for site names/urls that might otherwise resolve (eg through /etc/hosts) like "http://tolkien/" where "tolkien" is defined in /etc/hosts, it had the same behavior (would not add the site).

As a workaround for in particular the /etc/hosts entry, after adding an hostalias that has a "." in the name (eg "tolkien.foo"), DevTools then accepted the url "http://tolkien.foo/".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
As above, in Chrome, in React Developer Tools extension, Details (settings), option "Site access: Allow this extension to read and change all your data on websites you visit:", select "On specific sites", and type in "http://localhost/" or some other url without a period in it eg "http://tolkien/".

**What is the expected behavior?**
Expected that it would add the site.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is with:
Chrome 77.0.3865.120 (Official Build) (64-bit)
OSX 10.11.6
DevTools extension 4.2.0 (10/3/2019)
I haven't tried doing this with prior versions of Chrome/DevTools/OSX.

**Comment by threepointone** [comment]
Is this specific to React dev tools, or does it have teh same behaviour for other extensions too?

**Comment by willxy** [comment]
Ah, I thought that "Site access" was a DevTools option, but you're right, that seems to be a standard option that Chrome puts in all its extensions.

**Comment by auipga** [comment]
Is there an upstream bug filed?
