### ISSUE TITLE
react-devtools agent got no connection

### ISSUE THREAD

**Issue by bowencool** [facebook/react#17125]
**Do you want to request a *feature* or report a *bug*?**
Yes, I want to report a *bug*

**What is the current behavior?**
I cann't see anything in `react-devtools` when debuging `react-native` app in iPhone simulator but received some warnings as follow: 
![image](https://user-images.githubusercontent.com/20217146/66986061-adc99f80-f0f0-11e9-8ecf-171916816dde.png)
![image](https://user-images.githubusercontent.com/20217146/66986122-cd60c800-f0f0-11e9-860f-50a7876f323f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: 16.0.0-alpha.12
react-native-cli: 2.0.1
react-native: 0.47.1
react-devtools: 4.2.0
xcode: 10.3
macos: 10.15

**Comment by bowencool** [comment]
``` bash
npm i react-devtools@3 
```
It works for me.

**Comment by northkevin** [comment]
> ```shell
> npm i -g react-devtools@3 
> ```
> 
> It works for me.

Thank you so much @bowencool !

**Comment by bsgbryan** [comment]
I am still experiencing this issue.

Do we have any idea what is causing it?

**Comment by dailenspencer** [comment]
I am still experiencing this issue as well. @bsgbryan Any luck?

**Comment by bsgbryan** [comment]
I had to downgrade to v3, as @bowencool posted above. It's frustrating, but it's the only thing that has worked for me so far.

**Comment by WilbertJanney** [comment]
Same thing for me. I had to install v3 in order to prevent this error.
