### ISSUE TITLE
React this.context returns empty object {}

### ISSUE THREAD

**Issue by ahuseyn** [facebook/react#17126]
it is 2 days now I'm trying to solve this nonsense riddle. I've read all documentations and answers related to this but no specific answer for my case. I run my code both on React Native 0.61 (React version 16.9.0) and Snack playground.

**Problem is: console.log(this.context) always returns empty object like this - {}**
**I must return provider value when passed console.log(this.context)** 

The code is:
`import React from 'react';
import { Text } from 'react-native';

const AppContext = React.createContext({})

class App extends React.Component {
  state = {
    products: [
      { id: 'p1', title: 'Gaming Mouse', price: 29.99 },
      { id: 'p2', title: 'Harry Potter 3', price: 9.99 },
    ],
    cart: []
  };

  render() {
    return (
      <AppContext.Provider
        value={{
          products: this.state.products
        }}
      >
      </AppContext.Provider>
    );
  }
}

export default class testScreen extends React.Component {
  static contextType = AppContext

  render() {
    console.log(this.context)

    return (
      <>
        <Text>{'Sometext'}</Text>
      </>
    );
  }
}
`

I need help urgently, because it ties my hands to go further. Thank you in advance.

**Comment by contactyash** [comment]
testComponent must be in child tree of your Context.Provider. you are not rendering childrens there.Do this
`<AppContext.Provider>{this.props.childres}</AppContext.Provider>`;
then put consumer in App.
`<App><TestScreen/></>`
also make testScreen's T capital.
close the issue if it helps.

**Comment by TrySound** [comment]
This is wrong
```
export default <App><TestScreen/></App>
```
Should be
```
export default function AppComponent() {
 return <App><TestScreen/></App>
}
```

**Comment by ahuseyn** [comment]
It works! Thank you for help, you saved my day.
