### ISSUE TITLE
[RFC] React DevTools - configurable style prop for live editing

### ISSUE THREAD

**Issue by giuseppeg** [facebook/react#17148]
Right now the React DevTools expose an undocumented hook for React Native that allows to register a function that is used to enable styles editing in the dev tools:

<img width="1066" alt="Screen Shot 2019-10-19 at 4 30 16 PM" src="https://user-images.githubusercontent.com/711311/67146710-fb2f4380-f28d-11e9-9ce4-c037acc708c3.png">

For example React Native for Web uses it

https://github.com/necolas/react-native-web/blob/36dacb2052efdab2a28655773dc76934157d9134/packages/react-native-web/src/exports/StyleSheet/index.js#L13-L16

It would be great if the prop name was configurable (right now it can only be `style`) so that other CSS in JS libraries could use this hook and if the editor would allow 1) arrays of style objects 2) nested objects for things like pseudo elements:

```js
style {
  flex: 1;
  '&:hover': {
     color: 'red'
  }
}
```

I think that the above is already possible but it has to be provided as JSON. Couldn't it be `eval`d when JSON parse fails?

When this hook is registered probably the dev tools should hide the same prop from the `props` pane.

**Comment by bvaughn** [comment]
> It would be great if the prop name was configurable

Configurable _how_? What would the API look like? How would you avoid two libraries from conflicting with each other (e.g. React Native Web and any CSS in JS library)?

> I think that the above is already possible but it has to be provided as JSON. Couldn't it be `eval`d when JSON parse fails?

I don't think I'm keen on adding an `eval()` to the extension that works on user input. Why is it not possible to provide a JSON-parsable stirng?

**Comment by giuseppeg** [comment]
> Configurable how?

I mean configure the prop name, right now it is hardcoded to `style`. Many CSS in JS libraries use the `css` prop instead.

> What would the API look like?

This could be a global setting in the `window.__REACT_DEVTOOLS_GLOBAL_HOOK__` namespace.

> How would you avoid two libraries from conflicting with each other (e.g. React Native Web and any CSS in JS library)?

Good point this is tricky indeed. I would assume that few sites or apps use multiple libraries with two different jsx pragma that work on the same prop - if you had that setup I imagine that you would have to deal with the conflict regardless.

> I don't think I'm keen on adding an eval() to the extension that works on user input. Why is it not possible to provide a JSON-parsable stirng?

This is necessary to support nested rules for pseudo classes and media queries like:

```js
'&:hover': {
     color: 'red'
  }
```

Currently you can add declarations via the dev tools but the value can only be a string so I couldn't add the above rule. 

`eval` is a shortcut but you could possibly JSON.parse the value and see what is its type.

**Comment by bvaughn** [comment]
Hm. I don't think it's a good idea to encourage anything (other than an official React renderer) to interact with the `window.__REACT_DEVTOOLS_GLOBAL_HOOK__`.

> This is necessary to support nested rules for pseudo classes and media queries like:

Why is eval necessary for the example you posted above? This is a valid/parsable JSON string:
```js
{
  "&:hover": {
    "color": "red"
  }
}
```

I think the UI could be made to support nested styles (if we decided to) without the use of `eval`.

**Comment by giuseppeg** [comment]
> Hm. I don't think it's a good idea to encourage anything (other than an official React renderer) to interact with the window.__REACT_DEVTOOLS_GLOBAL_HOOK__.

fair enough! I figured it could be an useful feature but I’ll let you decide on that (this is my feel free to close this issue if you want).

> why eval

I don’t remember why I thought of that back when I created the issue. Probably because that would spare you the type check on the main thread when parsing. That said it is totally doable with JSON.parse

**Comment by giuseppeg** [comment]
This is not that important after all :)
