### ISSUE TITLE
Allow custom PropTypes to be chainable (`isRequired`)

### ISSUE THREAD

**Issue by lettertwo** [facebook/react#1715]
A way to make a custom proptype required would be useful. Maybe some form of the [createChainableTypeChecker](https://github.com/facebook/react/blob/master/src/core/ReactPropTypes.js#L93) factory could be exposed?

**Comment by spicyj** [comment]
Also wary of exposing an API for this. In the long term you can use Flow or other systems and we'll probably move propTypes out of core eventually.

**Comment by angryobject** [comment]
It's old, but agreeing with what @lettertwo wrote, it could look like this until we get an exposed API:

```javascript
const chainablePropType = predicate => {
  const propType = (props, propName, componentName) => {
    // don't do any validation if empty
    if (props[propName] == null) {
      return;
    }
    
    return predicate(props, propName, componentName);
  }
  
  propType.isRequired = (props, propName, componentName) => {
    // warn if empty
    if (props[propName] == null) {
      return new Error(`Required prop \`${propName}\` was not specified in \`${componentName}\`.`);
    }
    
    return predicate(props, propName, componentName);
  }
  
  return propType;
}
```
And later:

```javascript
const customProp = chainablePropType(() => {...});
const propTypes = {
  prop: customProp,
  requiredProp: customProp.isRequired
};
```

In case this still might be helpful to somebody.

**Comment by charles-haynes** [comment]
It would also be useful so checkers like eslint could tell when default props were needed for a custom property.
