### ISSUE TITLE
Eslint plugin for Hooks gives warning about dispatch in dependencies

### ISSUE THREAD

**Issue by PaulRBerg** [facebook/react#17156]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

If I don't include `dispatch` in the dependency list of a `useCallback` hook, I get this warning:

```
React Hook useCallback has a missing dependency: 'dispatch'. Either include it or remove the dependency array.eslint(react-hooks/exhaustive-deps)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See line 50 in `Application.js`: https://codesandbox.io/s/competent-bash-47zt1

**What is the expected behavior?**

There should be no warning, as per the [React docs](https://reactjs.org/docs/hooks-reference.html#usereducer):

> React guarantees that dispatch function identity is stable and won’t change on re-renders. This is why it’s safe to omit from the useEffect or useCallback dependency list.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- react@16.10.2
- react-dom@16.10.2
- eslint-plugin-react-hooks@1.7.0
- eslint@6.5.1
- dbaeumer.vscode-eslint@1.9.1
- vscode@1.39.2

**Comment by aweary** [comment]
@PaulRBerg the sandbox you linked doesn't have an `Application.js` file, can you update it so it reproduces the issue you're describing? 

As far as I know the linter doesn't warn about `dispatch` as long as it can tell that it was returned from `useReducer`. So if you're returning `dispatch` from another hook that wraps `useReducer` the linter doesn't know that the `dispatch` returned is the same `dispatch` that `useReducer` returns.

**Comment by PaulRBerg** [comment]
`Application.js` is in there, in the `contexts` folder.

I see, so then that's the issue. The said `dispatch` is the 2nd element of an array returned by `useContext`, hence why the linter can't know whether the original `dispatch` comes from `useReducer`.

Before closing this, maybe it's worth it to update the linter checks for the name of the function to be `dispatch`? One shouldn't really use this name for other purposes in an app built with Hooks.

**Comment by aweary** [comment]
> Would it make sense for the linter to check to not throw warnings for any functions named dispatch? One shouldn't really use this name for other purposes in a Hook-powered app.

While it might be convention to use `dispatch` only with `useReducer`, there's nothing that enforces this. It's best to just add it to the dependency array.

**Comment by avindra** [comment]
Is there a way to get the rule to understand which dependencies have stable identities?

`dispatch` is quite a common one due to the popularity of `react-redux`... and I'm sure others in this thread are seeing dozens of warnings about missing `dispatch` which is just plain wrong since it has a stable identity.
