### ISSUE TITLE
Force DOM flush for printing purposes

### ISSUE THREAD

**Issue by FredyC** [facebook/react#17155]
Two years ago there was issue #11876 about printing. Sync DOM flush was [recommended by @gaearon](https://github.com/facebook/react/issues/11876#issuecomment-352421144). However, with the latest React this does not seem to work anymore. It even seems that it somehow breaks the application, no print preview is ever displayed and sandbox preview cannot be reloaded anymore. It feels like an endless loop or something.

https://codesandbox.io/s/youthful-brown-0b6ez

I wonder if there is a new recommended way how to force DOM flush for correct printing experience.

**Comment by aweary** [comment]
That's really strange how it seems to break the sandbox without any errors. Can you reproduce this with a non-hosted version, like with `create-react-app`?

**Comment by FredyC** [comment]
@aweary You can just download that sandbox (File->Export to ZIP) which already is CRA based app. I can confirm the same behavior when running it locally.

**Comment by aweary** [comment]
I think this is likely the same problem as https://github.com/facebook/react/issues/16734.

**Comment by FredyC** [comment]
Yea, that seems highly likely.

So I guess there isn't any viable workaround currently to have an in-app button for printing. That's bummer for touch devices with printing capabilities.

**Comment by aweary** [comment]
@FredyC for what it’s worth, the bug should only exist in the development build. So theoretically you could ship it to production and it would work as expected. You’d just have to test the feature with a production build as well. Not ideal, but at least doable if it’s blocking you.

**Comment by FredyC** [comment]
That's definitely interesting realization, did not know about it. I tried to run a production build of that sandbox and it indeed does work. It's ok for us to disable the print button in development to avoid accidental freezes. Thanks a lot.
