### ISSUE TITLE
Hooks break when a build directory also includes React

### ISSUE THREAD

**Issue by dannytatom** [facebook/react#17152]
I'm using Next.js `9.1.1` and React `16.10.2`. The Next app (in `src/app`) gets built into a `dist/` directory at the root of the project with the `package.json` file moved over and installed within it. This is necessary because the app, when deployed, runs inside of a Firebase function.

The issue is that if I have a built version laying around, React errors out about invalid use of hooks. If I empty `dist/` everything works well. So this *seems* to be because there's multiple Reacts. But the app doesn't look in `dist/` or anything, so not sure why it'd load React from there too. But, if it's not that, then idk what it is. I'm pretty sure the code itself isn't using hooks wrong, it's pretty small and straight-forward component:

```typescript
const CurrentUser: React.FC = () => {
  const [user, initialising, error] = useAuthState(firebase.auth());

  const signIn = async () => {
    await firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider());
  };

  const signOut = async () => {
    await firebase.auth().signOut();
  };

  // start rendering things
};
```

**Comment by gaearon** [comment]
Please report this to Next.js — I don't see how we could help with this on our side. Thanks!
