### ISSUE TITLE
react-dom formatting for 'content' style value should add quotes

### ISSUE THREAD

**Issue by vtolkov** [facebook/react#17161]
**Do you want to request a *feature* or report a *bug*?**
bug or incomplete feature

**What is the current behavior?**
When formatting string css value in createDangerousStringForStyles function, it leaves string as is without quotes as required by css language. For example, 'content' value requires quotes.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
the debugger line:
ReactDOMServer.renderToString(React.createElement('s',{style:{content:""}}))
result in:
"<s style="content:" data-reactroot=""></s>"

**What is the expected behavior?**
it should be 
"<s style="content:''" data-reactroot=""></s>"
The 'content' syntax at https://developer.mozilla.org/en-US/docs/Web/CSS/content requires quotes to specify string value.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react-dom@16.10.2
Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Safari Version 13.0.2 (14608.2.40.1.2)

**Comment by jddxf** [comment]
If the value of `content` is quoted automatically, what the generated style should we expect to be when we're using a keyword value, e.g., `{ content: 'normal' }`? Quoted keywords means a different thing. If keywords are not quoted, we have to special case them, which would complicate the code. Thus, maybe the simplest way to solve your problem is to specify the value with quotes yourself, i.e. `{ content: '""'}`.

**Comment by sophiebits** [comment]
Yes – as @jddxf says, this is a case where you need to add the quotes yourself. Otherwise you wouldn't be able to render the valid non-quoted values of the `content` property.
