### ISSUE TITLE
Script tags are rendered inconsistently between client and server (html-encoded on server)

### ISSUE THREAD

**Issue by accidentaldeveloper** [facebook/react#17168]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Server-rendered script tags are html-encoded. Client-rendered script tags are not.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Render a script tag with quotes on the server.
2. Render a script tag with quotes on the client.
3. Compare the output. 

Note that the quotes are html-encoded to `&quot` when rendered on the server.

This CodeSandbox is a little rough but very simple: https://codesandbox.io/s/affectionate-star-xe8ym

**What is the expected behavior?**
The script tag content is not html-encoded on either the server or the client.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6
I'm not sure when this was introduced.

**Comment by accidentaldeveloper** [comment]
I am currently working around this issue by using `dangerouslySetInnerHtml` but the inconsistency caused this issue to go undetected for some time.

It would almost be better if it was broken on both the client and server, then the problem would be more obvious.

I am using these `script` tags to render JSON-LD schema.

**Comment by bhaveshkumar-1mg** [comment]
use React helmet for script tags to render JSON-LD schema.
<Helmet>
<script type="application/ld+json">{`
        {
            "@context": "http://schema.org"
        }
    `}</script>
</Helmet>

**Comment by accidentaldeveloper** [comment]
> use React helmet hoc over script tags to render JSON-LD schema.
> helmet<script type="application/ld+json">{`{ "@context": "http://schema.org" }`}</script>/helmet

Thank you @bhaveshkumar-1mg, I am aware of (and have used) this workaround as well. I still feel that this is a bug in the rendering.

**Comment by accidentaldeveloper** [comment]
This issue still exists in react 16.12.0 as you can see in this CodeSandbox
https://codesandbox.io/s/naughty-oskar-km1w1

**Comment by accidentaldeveloper** [comment]
bump

**Comment by jereaa** [comment]
This is still broken today with React 18, and in the Canary channel.
It's so broken and left forgotten, that the issue affects React's own documentation for inline `<script>`s [here](https://react.dev/reference/react-dom/components/script#rendering-an-inline-script)

<img width="927" alt="image" src="https://github.com/facebook/react/assets/1518173/32c1969b-d653-4f6d-8d0c-5ed3cce388e1">

**Comment by accidentaldeveloper** [comment]
Bump.
