### ISSUE TITLE
Feature request: useRender()

### ISSUE THREAD

**Issue by adrianhelvik** [facebook/react#17167]
Okay, so I've played around with hooks and come to like the way you can compose hooks. The only issue I have is that I would have liked to render something within certain hooks.

```
function useTooltip() {
  const [message, setMessage] = useState(null)
  const [x, setX] = useState(null)
  const [y, setY] = useState(null)

  // ...

  useRender(() => {
    return (
      <Portal>
        <Tooltip x={x} y={y}>My tooltip</Tooltip>
      </Portal>
    )
  }, [x, y])
}
```

In my mind this would logically be rendered before the template returned from the component.

**Comment by bvaughn** [comment]
I don't think this issue has enough info to be very actionable. (I'm not sure I understand what `useRender` would do that's any different from just returning a the elements directly, based on the example above.)

If you want to pitch a new hook, or new rendering semantics, I suggest you open an RFC:
https://github.com/reactjs/rfcs#what-the-process-is

RFCs have some template questions that help make sure a proposal has considered all angles and has been fully thought out. :smile:

I'm going to close this issue. Let's move the convo over to an RFC!

**Comment by adrianhelvik** [comment]
Here is an example of a use case I encountered today. I have written a solution using `useRender`.

```javascript
const CreateNewButton = () => {
  const fetchFiles = useFetchFiles()
  const createFile = useCreateFile()
  const prompt = usePrompt()

  return (
    <div>
      <button
        onClick={() => {
          prompt('Enter a title for your new file').then(title => {
            createFile({ title }).then(fetchFiles)
          })
        }}
      >
        Create a new foo
      </button>
    </div>
  )
}
```

And here is how I would solve this using `useRender`:

```
import { Portal } from 'react-portal'

const usePrompt = () => {
  const [question, setQuestion] = React.useState(null)
  const [answer, setAnswer] = React.useState('')

  const save = React.useCallback(() => {
    if (!question.resolve) return
    setQuestion(null)
    question.resolve(answer)
  }, [question])

  const cancel = React.useCallback(() => {
    setQuestion(null)
  }, [])

  useRender(Boolean(question) && (
    <Portal>
      <div className="prompt">
        <h1>{question.text}</h1>
        <input onChange={e => setAnswer(e)} />
        <button type="button" onClick={cancel}>Cancel</button>
        <button type="button" onClick={save}>Save</button>
      <div>
    </Portal>
  ), [question])

  return React.useCallback(text => {
    return new Promise(resolve => {
      setQuestion({ text, resolve })
    })
  }, [])
}
```

Instead of solving it this way, I now have to create a `Provider` further up the tree and send the functions down the tree using context. Which is okay, but not perfect. What if more prompts were opened at the same time for instance? `useRender` solves this succinctly, while you will have to operate on arrays when using the Provider/context pattern. State leaks can also be a problem with this pattern.
