### ISSUE TITLE
change props or hook state in dev-tool won't trigger re-render ?

### ISSUE THREAD

**Issue by littlee** [facebook/react#17171]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
change props or hook state won't trigger re-render
![Oct-24-2019 00-05-34](https://user-images.githubusercontent.com/7534668/67412742-6b252d00-f5f2-11e9-80fc-114236c5a3ea.gif)

**What is the expected behavior?**
change props or hook state should trigger re-render

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
"react": "^16.10.2",
"react-dom": "^16.10.2",

chrome 78.0.3904.70
macos Catalina 10.15
```

**Comment by bvaughn** [comment]
You have to "ENTER" to confirm the change. Otherwise you're just previewing it. (We wouldn't want to re-render on every character you enter, because there could be a lot of intermediate incorrect values.)

#17043 is a ticket about updating on blur as well, FWIW.

**Comment by littlee** [comment]
BTW, when can hooks state has name or something in devtool? It's hard to identify them with the value only.
```
hooks:
  State: 1
  State: 2
```

**Comment by bvaughn** [comment]
#16474
