### ISSUE TITLE
Event info is lost when handler is delayed

### ISSUE THREAD

**Issue by msonnabaum** [facebook/react#1717]
While porting an app to React, I ran into an issue where everything on the event is null when the event handler uses setTimeout.

Here's an example:

http://jsfiddle.net/msonnabaum/Ku89S/3/

I believe this is the same underlying issue as in #1360, but it feels like a bug that's worth fixing since event handlers that work with native DOM events or jQuery will break when ported to React.

**Comment by johnhaley81** [comment]
Do we need to manually clean up events that are persisted?

**Comment by spicyj** [comment]
@johnhaley81 No, they get garbage collected like any other object.
