### ISSUE TITLE
Question about useLayoutEffect

### ISSUE THREAD

**Issue by jlkiri** [facebook/react#17173]
**Do you want to request a *feature* or report a *bug*?**

This is a question.

**What is the current behavior?**

`useLayoutEffect` does not always seem to complete operations before DOM paint.
I use `useLayoutEffect` to apply certain styles to elements before they are painted to DOM. In particular, I am trying to reproduce the [FLIP](https://css-tricks.com/animating-layouts-with-the-flip-technique/) technique to make shuffling a list pretty. I store DOM coordinates for every list child in a `ref` object on first render, and on second render in `useLayoutEffect` I use those to compare with new coordinates and trigger an animation. To keep track of children I give them a `data-id` attribute.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

In my demo I randomly shuffle items, but animations do not happen if I sort them back to their initial state, in which they are ordered.

Here is the demo:
https://flip.jlkiri.now.sh/
OR
https://codesandbox.io/s/gallant-heyrovsky-dwdps

Here is the code for the demo and the hook I use:
https://github.com/jlkiri/react-easy-flip
https://github.com/jlkiri/react-easy-flip/blob/master/src/hooks/useFlip.js

**What is the expected behavior?**

My understanding is that restoring the initial order should work just like shuffling, since DOM position for a particular child with a particular `data-id` changes. Is this a result of some hidden heuristics of the React renderer or a bug?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 16.10.2
OS: Windows
Browsers: Chrome, Firefox, Edge
Previous versions: Do not know about versions in which it works

**Comment by TrySound** [comment]
> useLayoutEffect does not always seem to complete operations before DOM paint.

Of course not. Where did you find that? useLayoutEffect called "after all DOM mutations".
![image](https://user-images.githubusercontent.com/5635476/67495453-973cbe80-f683-11e9-8e95-f286ab6dd7e5.png)

**Comment by jlkiri** [comment]
I fixed the bug, that prompted me to post to issue, so it can be closed now.
