### ISSUE TITLE
Unnecessary re-render functional components

### ISSUE THREAD

**Issue by jefferson-vieira** [facebook/react#17176]
Hi,

I was thinking about functional components and performance enhancements.
Doing some tests, I noticed that react re-render children provided by functional components again when parent updates, even when they just render a static JSX (don't receive props or use any value provided by a useState hook, for example, like `const Component = () => <h1>Hellow World!</h1>`).
But using a `React.memo` HOC (with or without a mocked `propsAreEquals` function as argument, like `() => true`) the behavior is the expect "don't re-render". Do this really necessary? I think React can jump this automatic, because the component don't have a trigger can change its final result.
Or, am I not noticing something?
It is easy to replicate this test case, but I can provide a test repository if necessary.
What do you think?
I use devTools highlights to see render events.

**Comment by threepointone** [comment]
React will rerender whenever the parent updates, that’s always been true. React.memo/shouldComponentUpdate/PureComponent are the recommended ways to prevent rerenders.

**Comment by OttlikG** [comment]
Why does the documentation say to avoid React.memo for preventing renders?

https://reactjs.org/docs/react-api.html#reactmemo
"This method only exists as a performance optimization. Do not rely on it to “prevent” a render, as this can lead to bugs."
