### ISSUE TITLE
Passing function from functionnal component parent to class component children

### ISSUE THREAD

**Issue by valentinbourqui** [facebook/react#17174]
Do you want to request a feature or report a bug?

Bug (maybe) 

What is the expected behavior :

https://codesandbox.io/s/react-hooks-counter-demo-fdvcp

Please check my example and the console. The value "count" inside the function "onPropertyChange" stay at 0 ? It dosen't make sense. Did you pass the function as a reference to the children ? 

When you make the same example with two classes component it's working. When you make the same example and you put the value inside shouldComponentUpdate at true it's working too but for me it shouldn't be needed.

 I must find my current value when I call "onPropertyChange"

**Comment by aweary** [comment]
You're returning unconditionally returning `false` from `shouldComponentUpdate`. That means the component will *never* update. That means your `Tmp` component will only ever use the first copy of `onPropertyChange` that it received when it mounted, which was the copy that closed over the initial `0` value.
