### ISSUE TITLE
[eslint-plugin-react-hooks] useCallback does not add dependencies when callback is not function expression

### ISSUE THREAD

**Issue by jim-chou-shopify** [facebook/react#17187]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the argument of `useCallback` is not a function expression eslint-plugin-react-hooks will not autofix  dependencies.

Example:
```js
useCallback(debounce(() => console.log(props.value), 100), []);
```

Workaround:
```js
useMemo(() => debounce(() => console.log(props.value), 100), [props.value]);
```

**What is the expected behavior?**
```js
useCallback(debounce(() => console.log(props.value), 100), [props.value]);
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

eslint-plugin-react-hooks@^1.6.0, react@16.9.0-alpha.0

**Comment by sori9088** [comment]
...

**Comment by gaearon** [comment]
Fixed on master, but it'll ask you to actually write it inline.
