### ISSUE TITLE
React.memo always rerenders function component with array props

### ISSUE THREAD

**Issue by AiGon** [facebook/react#17184]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Ii seems react  doesn't prevent rerender for a function component with array props. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/j7xze61g/) example below:**

To see the bug click the button and watch console log.
```
const Panel1 = React.memo(({list}) => {
    console.log('Panel1 re-render...');
    return <React.Fragment/>
}) 
const Panel2 = () => <Panel1 list={[]}/>
const Panel3 = () => {
	const [count, setCount] = React.useState(0);
	return (
	    <div>
	        <button onClick={() => setCount(count + 1)}>Click me</button>
		<Panel2/>
	    </div>
	)
}
```

**What is the expected behavior?**
Array props is same as other primitive types and unnecessary rerenders  should be prevented.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.10.1/Chrome/Windows/Not sure about previous versions

**Comment by alexrohleder** [comment]
hey,

it seems that is because you are always passing a new array to it under the Panel2 code.

So, if you define a variable outside the component definition, let's say `const myList = []` and pass `myList` as the prop, the memo will not recompute. Here is a [working example](https://codesandbox.io/s/practical-swanson-qeuek?fontsize=14).

The [React.memo docs](https://reactjs.org/docs/react-api.html#reactmemo) states it this way:

> By default it will only shallowly compare complex objects in the props object. If you want control over the comparison, you can also provide a custom comparison function as the second argument.

**Comment by AiGon** [comment]
Thanks, you're right. Every time new list is created and render is called with same value but different reference to array props;.
