### ISSUE TITLE
Suggestion: Block unsafe javascript: URLs in Concurrent and Blocking Modes

### ISSUE THREAD

**Issue by radex** [facebook/react#17180]
In 16.9.0, a warning was added about `javascript:` URLs. This check is very, very important, as it's incredibly easy to forget about just once place where potential user data is passed onto DOM way. And of course, allowing a javascript: URL to be injected into DOM is a very serious XSS issue.

I griped before that this is too important to be just a warning, and suggested that a semver-compatible solution is to provide an exported function that allows a runtime opt-in to the new safe behavior. This suggestion was dismissed, since if I want this, I can just make my own build of react with the flag enabled. (Of course, almost no one will do this, because it's just too much of a pain to make your own dependency builds with every release)

I'd like to make a similar suggestion again. Since Concurrent and Blocking modes are coming soon(ish), and make many breaking changes anyway, why not take this opportunity to also block unsafe javascript: URLs when the mode is enabled? I know that URLs have nothing to do with concurrent mode (unlike unsafe lifecycle methods, etc.), but since many people will want to jump onto this new feature anyway and are willing to deal with some migration required anyway, why not add this vital security precaution as well?

Waiting until React 17 to protect… well, probably countless React apps that don't properly sanitize URLs, just doesn't seem reasonable, when the feature is already implemented, only disabled under a feature flag.

cc @gaearon @sebmarkbage

**Comment by gaearon** [comment]
We don't plan to couple these things to Concurrent Mode specifically. The concern is understood though.
