### ISSUE TITLE
DevTools: component path bar missing

### ISSUE THREAD

**Issue by blueberry6401** [facebook/react#17191]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
The new DevTools v4 is missing the component bar (don't know what it is exactly, it's in screenshot).

This screenshot is taken in the older version of Devtools, which v4 is missing.
![C-hXDoWXgAEev_Q](https://user-images.githubusercontent.com/7337535/67617707-152dd080-f810-11e9-8716-f8fdba753288.jpg)

**Comment by pavinthan** [comment]
You installed old version of dev tool, checkout this link https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

**Comment by blueberry6401** [comment]
> You installed old version of dev tool, checkout this link https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

@pavinthan the screenshot is taken in the older version of Devtools, the new version (v4) is missing it. My version is 4.2.0 (10/3/2019) btw.

**Comment by threepointone** [comment]
This is available in the right hand sidebar 
![image](https://user-images.githubusercontent.com/18808/67779665-db9dd500-fa5c-11e9-8c43-a588f0ddb382.png)

also if you double click a node, it'll appear as a breadcrumb above the tree 

![image](https://user-images.githubusercontent.com/18808/67779700-ec4e4b00-fa5c-11e9-9a49-3c178671bf79.png)

Closing this issue, but let me know if I'm mistaken.
