### ISSUE TITLE
React documentation in spanish, not very accurated and not very well translated

### ISSUE THREAD

**Issue by fsagaz** [facebook/react#17198]
**I've found that the react documentation in spanish is not very well translated, I would like to help by fixing some grammar and translation errors that I've detected**

**Comment by Andarist** [comment]
Feel free to prepare PRs against those translated docs.

**Comment by threepointone** [comment]
Thank you for volunteering! The repo for the Spanish documentation is here https://github.com/reactjs/es.reactjs.org and I’m sure they’ll love your help. Closing this issue.
