### ISSUE TITLE
Identify component as 'pending', when used with useTransition

### ISSUE THREAD

**Issue by samdenty** [facebook/react#17199]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When using `useTransition`, the components are re-rendered with the last state they had. 
 Without the ability to identify this 'pending' phase, components can't conditionally choose not to throw a promise - ie. the promise was created outside React.

**What is the expected behavior?**

Components should be able to differentiate the current phase they're in, eg.

```js
const phase = usePhase()
// or
const isPending = useTransitionPending()
```

**Example**

https://codesandbox.io/s/serene-wozniak-pnhhh

**Use case**

Library (pending release): [gqless](https://gqless.netlify.com/)

I've created a factory which tracks usage of 'references' during render, and updates the components when they change:

```js
const MyComponent = connected(() => {
  const data = accessReference()
  return <div>{data}</div>
})
```

```js
function connected(component) {
	return (props) => {
		const forceUpdate = useForceUpdate()

		references = startRecording()

		try {
			return component(props)
		} finally {
			references.stopRecording()
		}
		
		for (ref of references) {
			ref.onUpdate(forceUpdate)
			ref.onPendingChange(forceUpdate)
			if (ref.isLoading) throw promise
		}
	}	
}
```

Without the ability to check whether the current component is 'pending', the promise will be thrown on the 'pending' render phase - which prevents the transition from working.

This doesn't happen in the [examples](https://reactjs.org/docs/concurrent-mode-patterns.html), as the data is immutable and passed down as the `resource` prop.

**Comment by gaearon** [comment]
>I've created a factory which tracks usage of 'references' during render, and updates the components when they change

This is really far from a supported use case. You're relying on mutation and subscriptions, both of which don't work as-is with the Concurrent Mode rendering model (pure computations).

**Comment by natew** [comment]
Dan, just ran into this and curious if you have a recommended place to read up more on "pure computations" and the diff between subscriptions/mutations and that?

**Comment by dai-shi** [comment]
In [react-tracked](https://github.com/dai-shi/react-tracked), we store tracking `references` in a function variable (closure), and only assign it to a ref (useRef) in useLayoutEffect.

**Comment by gaearon** [comment]
@natew The rule of the land is just that we want to be able to re-run render at arbitrary times. We also don’t give you guarantees that any particular render result will get committed. So if you subscribe during render you won’t have a good place to unsubscribe.
