### ISSUE TITLE
Empty object as SuspenseConfig acts like infinite timeout

### ISSUE THREAD

**Issue by Eddie-CooRo** [facebook/react#17203]
**Do you want to request a *feature* or report a *bug*?**
Probable Bug

**What is the current behavior?**
When an empty object is passed as SuspenseConfig, React waits infinitely on the previous tree for new Suspended components to get resolved.

**A minimal demo of the problem:**
Here is a demonstration, using the same example used throughout the concurrent docs:
https://codesandbox.io/s/empty-suspense-config-example-88ghb 

**What is the expected behavior?**
I don't know if it's a bug, or it's intentional. But if it's the expected behavior, I think it's better to add this to the documentation. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React and ReactDOM's experimental build

**Comment by sopranolinist** [comment]
Your codesandbox demo appears to be working as expected for me in Chrome 77.0.3865.120. 
![Oct-29-2019 00-48-48](https://user-images.githubusercontent.com/42662464/67747449-f41ed880-f9e5-11e9-9133-c2933756509d.gif)

**Comment by Eddie-CooRo** [comment]
@sadlittlejoe This behavior is exactly what I want to report Because the documentation hasn't mentioned that when passing an empty object as the SuspenseConfig, the fallback component never shows up

**Comment by gaearon** [comment]
There's no suspense config anymore.
