### ISSUE TITLE
Devtools tabs should not appear in chrome-extension pages when using react-devtools as an entry point

### ISSUE THREAD

**Issue by nickmccurdy** [facebook/react#17208]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The React devtools tabs in Chrome devtools can be displayed in extension pages, even though modifying extensions in other extensions is not supported by Chrome, and React devtools are therefore broken.

![image](https://user-images.githubusercontent.com/927220/67774646-21927300-fa34-11e9-99b5-ea3c62a99e0d.png)

![image](https://user-images.githubusercontent.com/927220/67774697-38d16080-fa34-11e9-8ea6-fddb21c7bb14.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

1. Install Chrome and React devtools
2. Open devtools in a chrome-extension page implemented with React

Example: [prettier-chrome-extension](https://github.com/prettier/prettier-chrome-extension/tree/options) (install from source and open extension options)

**What is the expected behavior?**

React devtools should not appear when it's not supported, just like when devtools are opened on a page that doesn't use React.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- React 16.11.0
- React Developer Tools 4.2.0 (10/3/2019)
- Chrome 78.0.3904.70
- macOS 10.15

**Comment by threepointone** [comment]
Assigning to myself because I'm interested.

**Comment by bvaughn** [comment]
I'm not able to reproduce this behavior.

**Comment by nickmccurdy** [comment]
I can reproduce with a fresh install of the example: [prettier-chrome-extension](https://github.com/prettier/prettier-chrome-extension/tree/options) (install from source and open extension options)

**Comment by bvaughn** [comment]
Sorry, still can't reproduce this. May need more info.

**Comment by nickmccurdy** [comment]
Sorry, I just realized I changed the example I gave previously in a way that no longer reproduces the issue.

Here's a new minimal reproduction: https://gist.github.com/nickmccurdy/5d53943c3c31587991713b29a04c8009

It seems like this is specifically an issue with adding `react-devtools` as an entry point in webpack. It works if I remove the entry point and `import "react-devtools"`, but the docs suggest that both should work and I'd prefer to toggle devtools support in development/production with entry points. I'm not sure if the source of the issue is my webpack configuration or a bug in React Devtools, so I'd appreciate help figuring that out.

**Steps to reproduce**
1. Clone/download example
1. `yarn`
1. Install Chrome and React Devtools Extension
1. Open Chrome extension settings
1. Enable developer mode
1. Load unpacked extension
1. Select path to dist directory
1. Open extension details
1. Open extension options
1. Open Chrome Devtools
1. Open Components tab of React Devtools

**Comment by bvaughn** [comment]
That's...a really specific and unusual set of steps. Why is your extension importing `react-devtools`?

**Comment by nickmccurdy** [comment]
I’m developing a Chrome extension’s options page with React. I can’t run a normal webpack dev server with the React devtools extension because my extension’s React components rely on Chrome extension APIs. Chrome also doesn’t support extensions (in this case React devtools) injecting devtools into extension pages (such as my extension’s options page). As a result, I’m using the standalone `react-devtools` package by importing its remote devtool integration and running the command as suggested by its readme here: https://github.com/facebook/react/blob/master/packages/react-devtools/README.md

I might be able to import the package conditionally, but I’d prefer to keep this configuration in my webpack config if possible, and it’s still potentially confusing to see broken devtools in Chrome devtools.

I can also upload a zip/crx of the example extension if it helps, then only steps 8-11 would be necessary.

**Comment by nickmccurdy** [comment]
I built a zip file so this can be reproduced without building from source:

1. Install Chrome and React Devtools Extension
1. Open Chrome extension settings (`chrome://extensions/`)
1. Enable developer mode
1. Download and unzip [dist.zip](https://github.com/facebook/react/files/3947647/dist.zip)
1. Click load unpacked and select the unzipped directory
1. Open extension details
1. Open extension options
1. Open Chrome Devtools
1. Open Components tab of React Devtools

**Comment by bvaughn** [comment]
Thanks for the added context.

**Comment by nickmccurdy** [comment]
Bumping, I think this would improve the DX of React extension development

**Comment by bvaughn** [comment]
@nickmccurdy Realistically, I don't think anyone is going to work on this issue considering how unusual the use case is. If it's important to you, you might need to pick it up.

**Comment by aspiers** [comment]
I have just seen this same problem of the react-devtools Components tab incorrectly appearing in the inspector of my extension's options page when it shouldn't.  However in my case it was triggered with rollup+vite and `import 'react-devtools'` in the options page's `index.tsx` rather than via a webpack entry point.
