### ISSUE TITLE
Unable to render nested <optgroup> elements in a <select>

### ISSUE THREAD

**Issue by theetrain** [facebook/react#17226]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When creating a `<select>` with an `<optgroup>` nested in an `<optgroup>`, the 2nd-level deep `<optgroup>` will not render in Chrome or Safari. It renders in Firefox, but items in 2nd-level optgroup are not selectable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Working example using plain HTML: https://codepen.io/etrain/pen/mddBYNG
![image](https://user-images.githubusercontent.com/12798751/67890776-b924be00-fb27-11e9-91bc-ac4c09bec8b0.png)

Minimal React 16.11.0 example: https://codesandbox.io/s/select-option-groups-544yj
![image](https://user-images.githubusercontent.com/12798751/67890809-c6da4380-fb27-11e9-9795-75fae32f8674.png)

**What is the expected behavior?**
All `<option>` elements will render in the order they're defined, along with their respective `<optgroup>` elements.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.11.0
react-dom@16.11.0

This does not work on previous versions of React from what I've tried (v16.2.0, v15.6.2).

**Comment by vkurchatkin** [comment]
You are not really allowed to nest `optgroup` in another `optgroup`

**Comment by theetrain** [comment]
Thanks for pointing that out, I should have checked the spec earlier: http://w3c.github.io/html-reference/optgroup.html#optgroup

> Permitted parent elements
> `select`

I wonder if preventing nested `<optgroup>` elements from rendering was intentional by React, to act as guard rails.

**Comment by aweary** [comment]
@theetrain if you check the console you'll see that React logs a warning about this

```
Warning: validateDOMNesting(...): <optgroup> cannot appear as a child of <optgroup>.
    in optgroup (at src/index.js:13)
    in optgroup (at src/index.js:10)
    in select (at src/index.js:9)
    in div (at src/index.js:8)
    in App (at src/index.js:24)
```

> I wonder if preventing nested <optgroup> elements from rendering was intentional by React, to act as guard rails.

React doesn't actually prevent this from rendering; if you inspect the DOM you'll see that it does contain both `optgroup` elements. The discrepency here is between HTML and the DOM APIs. If you reproduce this by manually creating and appending elements you'll see the same behavior as React: https://codesandbox.io/s/headless-wildflower-pxe4m
