### ISSUE TITLE
onMouseEnter is fired on disabled buttons

### ISSUE THREAD

**Issue by diegohaz** [facebook/react#17229]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`onMouseEnter` is fired on `disabled` buttons.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/react-onmouseenter-on-disabled-buttons-fskwd

**What is the expected behavior?**

`onMouseEnter` shouldn't be triggered on `disabled` buttons.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.11.0 (not sure when it started to happen)
Chrome/MacOS

**Comment by edwincoronado** [comment]
Taking a look at this to see if I can fix it.

**Comment by abrahamwilliam** [comment]
@edwincoronado @diegohaz 

I have identified the fix to this issue/Bug, just testing it.I am proceeding to it, please let me know if any issues.

**Comment by abrahamwilliam** [comment]
@edwincoronado @diegohaz 

I have identified the fix to this issue/Bug, just testing it.I am proceeding to it, please let me know if any issues.

**Comment by AlfredoGJ** [comment]
I submitted a pull request that solves this problem. If someone wants to take a look. Feedback is welcome.

**Comment by gaearon** [comment]
Should be fixed in 16.13.
https://reactjs.org/blog/2020/03/02/react-v16.13.0.html
