### ISSUE TITLE
Experimental: Unknown unit of work tag (18).

### ISSUE THREAD

**Issue by CodeWitchBella** [facebook/react#17238]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

React@experimental sometimes issues following error on page load.
```
Error: "Unknown unit of work tag (18). This error is likely caused by a bug in React. Please file an issue."
    completeWork http://localhost:3000/dist/index.js line 14463 > eval:21603
    completeUnitOfWork http://localhost:3000/dist/index.js line 14463 > eval:24709
    performUnitOfWork http://localhost:3000/dist/index.js line 14463 > eval:24685
    workLoopSync http://localhost:3000/dist/index.js line 14463 > eval:24650
    performSyncWorkOnRoot http://localhost:3000/dist/index.js line 14463 > eval:24249
    flushSyncCallbackQueueImpl http://localhost:3000/dist/index.js line 14463 > eval:12192
    unstable_runWithPriority http://localhost:3000/dist/index.js line 42728 > eval:818
    runWithPriority$2 http://localhost:3000/dist/index.js line 14463 > eval:12142
    flushSyncCallbackQueueImpl http://localhost:3000/dist/index.js line 14463 > eval:12187
    workLoop http://localhost:3000/dist/index.js line 42728 > eval:762
    flushWork http://localhost:3000/dist/index.js line 42728 > eval:717
    performWorkUntilDeadline http://localhost:3000/dist/index.js line 42728 > eval:219
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I have no idea what triggers this error and my codebase is not exactly small and because it appears only sometimes (maybe 10%) it is really hard to track down.

**What is the expected behavior?**
No error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest firefox and chromium on fedora 31. React@experimental and it started (I think) after I started experimenting with concurrent mode and suspense so it did not appear on older version, but is also not applicable to it.

**Comment by Sicria** [comment]
This appears to still be an issue, I know it's marked as `stale` but is there any more info on this? @CodeWitchBella did you figure out what causes this?
