### ISSUE TITLE
`input` event `onchange` Why is there a border?

### ISSUE THREAD

**Issue by d1y** [facebook/react#17235]
在我开启`chrome-devtools=` 之后, `input` 的 `change` 事件, 触发后会有边框, 这是不是`chrome` 的默认行为? 还是说, 是 `react-devtools` 开发工具的行为🧐?

After I turn on `chrome-devtools=`, the `change` event of `input` will have a border after the trigger. Is this the default behavior of `chrome`? Or, is the behavior of the `react-devtools` 🧐

![test.gif](https://i.loli.net/2019/10/31/MhfqmWpBaDuvyNU.gif)

**Comment by marvinhagemeister** [comment]
That's a feature of the react devtools that is turned off by default and has to be explicitly turned on. It's called "Highlight updates" and visualizes where updates were triggered. You can turn it off by unchecking it in the react devtools settings (click the gear icon).

**Comment by d1y** [comment]
> That's a feature of the react devtools that is turned off by default and has to be explicitly turned on. It's called "Highlight updates" and visualizes where updates were triggered. You can turn it off by unchecking it in the react devtools settings (click the gear icon).

Yes, it is like this, thank you:3
