### ISSUE TITLE
Blink with useTransition

### ISSUE THREAD

**Issue by gregberge** [facebook/react#17239]
**Bug**

**What is the current behavior?**

As discussed with @gaearon in this thread: https://twitter.com/dan_abramov/status/1189923059031068672

When the `useTransition` is fast, it results to a small blink for the user. You can reproduce it in this example :

- Choose "Concurrent Mode"
- Click "Next" in "fretch-mode: legacy-mode" 

https://codesandbox.io/s/fretch-example-r6t8g

A simpler example can be provided but I don't have time right now, I just want to track the issue.

**What is the expected behavior?**

The expected behaviour would be to avoid the blink if it is less than "100ms" (or another arbitrary delay).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The experimental version, see the example.

**Comment by gaearon** [comment]
This sandbox has a _lot_ of code. Any chance you could isolate that to a minimal example?

**Comment by gregberge** [comment]
> This sandbox has a _lot_ of code. Any chance you could isolate that to a minimal example?

Hello, since I don't work on it any more, no chance sorry!

**Comment by gaearon** [comment]
This is likely same as https://github.com/facebook/react/issues/18006#issuecomment-866409438.
