### ISSUE TITLE
It's not possible to access the shadowRoot of a Web Component when using React Suspense/Lazy

### ISSUE THREAD

**Issue by CristianDDias** [facebook/react#17246]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using Web Components and React Suspense/Lazy, it's not possible to access the `shadowRoot` in the `useEffect` because the `shadowRoot` still haven't loaded its child elements.

**Steps to reproduce the problem.**
[CodeSandbox](https://codesandbox.io/s/thirsty-poitras-sq22m)
In the `TabComp` component, if I change the line `const { t } = useTranslation("", { useSuspense: false });` for `const { t } = useTranslation();` an error occurs. The error occurs because the `shadowRoot` still haven't loaded its child elements and it's trying to access a child element.

I also commented about this problem in an [issue](https://github.com/i18next/react-i18next/issues/817#issuecomment-548629946) of the `react-i18next` library, but I'm not sure if this problem is related to their library.

**What is the expected behavior?**
The `shadowRoot` property of a Web Component can be accessed in the `useEffect` even if the component is using React Suspense/Lazy.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.4
Browser Chrome 77
I haven't tried this in previous versions of React.

**Comment by Jessidhia** [comment]
Nit: you should be using `React.useRef`, not `React.createRef`; the `createRef` will be re-created on every single render pass and cause the rules-of-hooks warning about your `useEffect`.

That said, changing to `React.useRef` doesn't help. `ref.current` is set, `ref.current.shadowRoot` is also set, but the `ref.current.shadowRoot.firstElementChild` property is `null` when `useSuspense` is `true`, as well as other things you'd expect to be set (adopted style sheets are empty, innerHTML is empty too, etc).
