### ISSUE TITLE
Destructuring Props in Child Class Component resets Parent's previous state

### ISSUE THREAD

**Issue by ayayalar** [facebook/react#17240]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

This is a weird problem I've never seen before. Perhaps I am doing something wrong. I am able to repro the issue only in a class child component/parent functional component. The problem is when I destructure props in the child class component constructor,  the parent's previous state resets. However If I dont destructure the props, and just use the format `this.props.cb()`, then the previous state of the parent's is preserved.

**_If I convert the child to a functional component, the problem goes away._**

PS: I am using antd upload component. However I can repro this issue without using the antd upload component. I just kept it for the sake of keeping the code example short.

I have a [demo here](https://codesandbox.io/s/agitated-stonebraker-9wwoq?fontsize=14)

**child class component demo:**
if you look at the console log, after upload clicked, the `color` will reset back to the original initialized value of `blue` instead of preserving its current state which is `red`

**child functional component demo:**
On the functional component example, notice the `color` property preserves its previous state which is `red`.

**What is the expected behavior?**
Parent's previous state should be preserved.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.4, I don't know if it works in previous versions of React

**Comment by AZZB** [comment]
Try to pass a callback instead of passing and spreading state directly when you update the state

`setMyState(state => ({...state,  color: 'red' }))`
`setMyState(state => ({ ...state, file: fileName }))`

**Comment by ayayalar** [comment]
Hey @AZZB I will try this first thing in the morning and update the post.
Thank you!

**Comment by jddxf** [comment]
Add this line of code in the `beforeUpload` callback: `console.log(cb === this.props.cb);`and you would know why this happens.

**Comment by ayayalar** [comment]
@jddxf can you elaborate?

**Comment by ayayalar** [comment]
@AZZB that fixes the problem. Thank you! Any idea why when I call `this.props.cb` I don't experience this problem? even without the fix you suggested?

**Comment by jddxf** [comment]
> @jddxf can you elaborate? I see that they are not equal. But how come calling `cb` works in the functional component vs the class component?

Every time `App` renders, a new `click` is created which captures the state at that time.  In the class component, if we use the `cb` destructured in the constructor, we're always using the first `click` which captures the initial state since the constructor runs only once. In the function component, however, every time it re-renders we get the latest `click`.

**Comment by ayayalar** [comment]
@jddxf makes perfect sense. Thank you!
