### ISSUE TITLE
Missing React tab in chrome dev tools

### ISSUE THREAD

**Issue by battleb2014** [facebook/react#17242]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

There is no React tab in my chrome dev toolbar anymore.  I have deleted and reinstalled the react extension but the issue was not resolved.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

There use to be a React tab in the chrome dev console toolbar

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm using ios on google chrome.

**Comment by bvaughn** [comment]
The word "React" doesn't appear in the DevTools toolbar buttons. You should see two options, "⚛️ Components" and "⚛️ Profiler".

<img width="188" alt="Screen Shot 2019-11-02 at 8 40 35 AM" src="https://user-images.githubusercontent.com/29597/68073349-77c12800-fd4c-11e9-96ff-7a92cc67ea91.png">

If you have a lot of extensions installed, you might need to look in the dropdown menu to find them:
<img width="169" alt="Screen Shot 2019-11-02 at 8 41 28 AM" src="https://user-images.githubusercontent.com/29597/68073360-958e8d00-fd4c-11e9-917f-6152cea79f90.png">

**Comment by battleb2014** [comment]
Ahhhhh.  Thank you so much.

**Comment by bvaughn** [comment]
No prob :)

**Comment by xanthoc** [comment]
![image](https://user-images.githubusercontent.com/6534678/83090447-c3199a00-a0d3-11ea-8f06-8ea69f690972.png)
I can see the red react developer tools icon but can't see components and profiler tabs. They used to there. I googled but in vain and reinstalled react developer tools but it didn't work. Please help me.

**Comment by bvaughn** [comment]
This is being discussed over on #19002, @xanthoc. If you can provide more info (to the questions asked on that issue) it might be helpful.

**Comment by xanthoc** [comment]
@bvaughn 
got it. will move to #19002
