### ISSUE TITLE
it.dev ?

### ISSUE THREAD

**Issue by monkindey** [facebook/react#17249]
Already we have `it. experimental` in test, Can we add `it.dev` to run test instead of using [`__DEV__`](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/__tests__/ReactSuspenseCallback-test.internal.js#L242-L307) in test ?

**Comment by ahtee** [comment]
What is this related to?

**Comment by monkindey** [comment]
@ahtee  [this one ](https://github.com/facebook/react/pull/17243/)

**Comment by threepointone** [comment]
We could, but it’s not clear what benefit this abstraction would have? it.experimental does more than just a Boolean check, as detailed in the PR. 

Closing since this isn’t a bug or feature request, but happy to chat if there’s something I missed.
