### ISSUE TITLE
Packaging error

### ISSUE THREAD

**Issue by Dec-F** [facebook/react#17247]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I use the v12.0.0 version of the Node to run the `yarn build`. Throw an error. It is good to use v10.7.0 when packaging. I am not sure if this is a problem with React or a problem with Node or other tools.
![image](https://user-images.githubusercontent.com/20250430/68015078-443eb900-fccc-11e9-8312-d4d5c5477c88.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Just execute the `yarn build` command

**What is the expected behavior?**

packaging success

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 16.11.0
OS: MacOS
Node:v10.7.0 and v12.0.0

**Comment by threepointone** [comment]
I can't reproduce this on my machine, with node v12.13.0. I haven't heard this from anyone else either. Do you have some local changes in your repo? Could you try with a fresh checkout? Try running yarn before running yarn build. 

I'm going to close this issue, but happy to discuss if it persists.

**Comment by Cumbermiao** [comment]
I had the same problem . Did you solve it?
