### ISSUE TITLE
False negative react-hooks/rules-of-hooks validation result

### ISSUE THREAD

**Issue by Nek** [facebook/react#17244]
**What is the current behavior?**
A functional component put into a object literal doesn't pass validation by eslint-plugin-react-hooks

```
const RenderWithFX = {
  render: () => {
    useEffect(() => {
      console.log("I should work!");
    }, []);
    return <div>RenderWithFX</div>;
  }
};
```
gives
```
error    React Hook "useEffect" is called in function "render" that is neither a React function component nor a custom React Hook function  react-hooks/rules-of-hooks
```
Changing the field name to `Render` or `_` or anything else not starting with lowercase letter fixes the problem.

The demo:
https://codesandbox.io/s/wild-sound-k1cxe

**What is the expected behavior?**
I expect my example to pass validation.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
eslint-plugin-react-hooks 2.2.0

**Comment by Nek** [comment]
I've found this
https://github.com/facebook/react/blob/a1ff9fd7bb919cfe8d18ce9c8b9315d74d0e3405/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L43

Not sure this should be applied when a component is an object's field.

**Comment by wadamek65** [comment]
Imho this rule is working as intended, wrapped in an object or not a function returning a react component should start with upper case. Like the context api which returns `Context.Provider` and `Context.Consumer` both with upper case letters.

Is there any particular reason why you need the property to start with a lower case letter?

**Comment by Nek** [comment]
@wadamek65 here's to the bare bones use case example:
```
const Todo = component({
  query: [['todoId'], ['text']], 
  render: ctx => {
    const { text } = ctx
    useEffect(()=>console.log(text))
    return (
      <li>{text}</li>
    )
}})
```
The ```component``` function processes the object instance (adds query and component to a registry) and returns what's inside the ```render``` field.

**Comment by wadamek65** [comment]
But at the end of the day you would have to create the component by calling the `render` function either by using JSX or not which React advises against doing.

Why not call it `Component` instead of `render`? Also makes more sense semantically since the value of this property is not the render function, it's the component itself.

**Comment by Nek** [comment]
Todo is the render function, so, I would use it as ```<Todo />```. ```render``` is a temporary container for ```component``` function to use.
```
export const component = (query: FoldedQuery, key: RenderFunction) => {
  registry.set(key, query);
  return key;
};
```

**Comment by wadamek65** [comment]
Whether you think it as a temporary container for a component or not, it can still be used as a component by itself. What you seem to be doing is a HOC pattern.

How do you propose this case should be handled? How do we know someone created an object with your intended use case in mind while someone else simply exported their component to an object? (I still think both cases are one and the same and the property should start with a capital letter, but maybe you have something in mind)

**Comment by Nek** [comment]
> Why not just pass the component as an unnamed arrow function as an argument instead of a property in an object? This way you could treat it as your temporary container and the linter should not complain.

This was my original intention but I was looking for a more DSLish way of creating components. I guess I stick to the argument solution for now.

Thanks for discussion!
