### ISSUE TITLE
[About hooks programming] Can not properly split code using hooks.

### ISSUE THREAD

**Issue by liyuanqiu** [facebook/react#17257]
**Do you want to request a *feature* or report a *bug*?**
feature(maybe more like a discussion)

**What is the current behavior?**
Assume that we have one custom hook:
```typescript
/* Typing with TS */
// to make this example reasonable,
// assuming that `fetchUser` and `fetchOrders` fetch data from different backends. 
function useOrders(): Order[] {
  const [orders, setOrders] = useState<Order[]>([]);
  useEffect(() => {
    fetchUser().then(user =>
      fetchOrders(user).then(theOrders => setOrders(theOrders)),
    );
  }, []);
  return orders;
}
```
It works perfectly, but in other parts of application, I also need to fetch the `user` data, so I think I should split `useOrders` into two custom hooks to make the process of fetching user reusable:
```typescript
/* Typing with TS */

// before the backend responsing, the returned user is `null`
function useUser(): User | null {
  const [user, setUser] = useState<User | null>(null);
  useEffect(() => {
    fetchUser().then(theUser => setUser(theUser));
  }, []);
  return user;
}

function useOrders(user: User): Order[] {
  const [orders, setOrders] = useState<Order[]>([]);
  useEffect(() => {
    fetchOrders(user).then(theOrders => setOrders(theOrders));
  }, [user]);
  return orders;
}
```

But the two custom hooks can not work together properly:
```typescript
function SomeComponent() {
  const user = useUser();
  // when user data is still fetching, the user will be null,
  // so the next line will throw error(typing and runtime)
  const orders = useOrders(user);
}
```

Maybe I can determin whether the `user` is `null` inside `useOrders`, but it is hard to explain the meaning of `useOrders(null)`. Why should `useOrders` accepts `null`?

So my solution is to wrap the component:
```typescript
function SomeComponent({ user }: { user: User }) {
  const orders = useOrders(user);
}

function Wrapper() {
  const user = useUser();
  if (user === null) {
    return null;
  }
  return <SomeComponent user={user} />;
}

export default Wrapper;
```

I often fell into this hell when I tried to refactor existing code.

---

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
I don't know, maybe a discussion is needed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React >= 16.8.0
any supported browsers

**Comment by Eddie-CooRo** [comment]
You should probably take a look into suspense for data fetching. ([docs](https://reactjs.org/docs/concurrent-mode-suspense.html))
I think it's trying to solve a similar problem, and you may find it useful.

Also, for now, you can get some ideas for solving your problem, by giving a look at the new `swr` package, published by the zeit company. ([homepage](https://swr.now.sh/#dependent-fetching))
Just take a look at the dependent fetching section.

**Comment by threepointone** [comment]
I don't think recommending suspense for data fetching is a good idea, much less a third party experimental library. 

For the OP example, if you're insistent on splitting this code up into hooks, I don't see a problem with `useOrders(null)`, null as an input to a hook is used often to denote "no input". 

That said, you don't have to split into different hooks. Composing different async functions inside an effect's body is a fine way to do it, and I don't see a problem with writing 'fetchUser()` again elsewhere. Indeed, it's simpler than the complications that Arose when you tried to split it up.

**Comment by liyuanqiu** [comment]
Thanks for your explanation 🙏

I have some doubts:
> null as an input to a hook is used often to denote "no input".

I. The edge whether to accept `null` is no clear. If I write custom hooks as modules to give others to use, I can't assume their context, so it seems like all parameters should accept `null`?

II. If "no input", what value should I return? Also a `null` for "no output"? It is a loop, finally the world of hooks will be full of `null`.

> Composing different async functions inside an effect's body is a fine way to do it

III. I always tried to escape from duplication. If parts of some big function are used frequently in other places, it is worse to be split out. For normal functions, it is easy to split, but for hooks, problem became complicated. So maybe the right way is to split code into normal functions, not into hooks, then composite the functions in hooks?

**Comment by threepointone** [comment]
> maybe the right way is to split code into normal functions, not into hooks, then compose the normal functions in hooks?

Yup, that's what I'm suggesting. Not everything has to be a hook, especially when the concerns aren't related component.
