### ISSUE TITLE
DataTable components - Resource available

### ISSUE THREAD

**Issue by babatundeko** [facebook/react#17264]
Hi, 

I work for NHLBI as an IT project manager and UIUX team lead, and I am working on the migration from Bootstrap to Foundation with React.js due to the security EOL issue. While I was doing a lot of gap analysis for components on React.js, I couldn't seem to find straightforward DataTable, which is our heavily component use for the applications, Date-picker, and some other components. Several of our development teams are concern about the availability component that supports by React.js.  I want to set up a meeting with all my development team, and your React.js development team lead and discuss using varies of components with React.js. Please contact me at Kazeem.Babatunde@nih.gov.

I look forward to hearing from you soon.

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by babatundeko** [comment]
> Hey there! We use the issue tracker for bug reports and feature requests.
> 
> If you have a question, please check our community support resources:
> https://facebook.github.io/react/community/support.html

Thank you!
