### ISSUE TITLE
Static rendering strategy doesn't work on codesplitted routes

### ISSUE THREAD

**Issue by carlesnunez** [facebook/react#17260]
I'm not really sure if it is a bug or not but I'm facing problems trying to use static rendering strategy + injecting DOM elements manually to a non hydrated react component. 

**What is the expected behavior?**
The thing that I expect to do is the next:
1 - Render a component on server side and server it to client
2 - On the head of my app having a JS that will inject some DOM elements (ads) on non hydratable components.
3 - On client avoid hydratation of that component using the hacky thing of empty dangerousHTML

**What is the current behavior?**
The thing that I expect to do is the next:
1 - Render a component on server side and server it to client
2 - On the head of my app having a JS that will inject some DOM elements (ads) on non hydratable components.
3 - On client hydratation the code is throwing a ssr vs csr missmatch and is re-building everything.

I've tested it on pages without code-splitting and them seem to work like a charm, only have this behavior on code splitted routes.

What I'm doing wrong?

**Comment by threepointone** [comment]
Could you share a codesandbox link, or a git repo, with a reduced version that reproduces this? Happy to have a look. 

Of relevance, codesplit components (with React.lazy) don't work with the current server renderer. We have a suspense compatible version in the experimental builds.

**Comment by carlesnunez** [comment]
Hey! Of course I'll try to provide something this week
