### ISSUE TITLE
Wrapper components inside a array.map always rerenders

### ISSUE THREAD

**Issue by noelzubin** [facebook/react#17261]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when a single item in an array is changed it rerenders all the three items in the list since the `props.children` of the `List` component changes. 

https://codesandbox.io/s/elated-bas-z7fxi

please check the app component in the example.

**What is the expected behavior?**
react should properly diff `List.props.children` and not rerender it in a PureComponent.
i.e. react should correctly diff react nodes.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
all versions of react probably.

**Comment by threepointone** [comment]
The behaviour seems as expected. You changed the state of App, which triggered a re-render. For each of the child components, React checks the props that are passed, and only rerenders the children whose props have changed (in this case, the first Item).

**Comment by noelzubin** [comment]
@threepointone Agree with you. but for the `List` component it rerendered thrice even though only the first one's state actually change.
When you click on the button i expect the first `List` and the first `List2` to rerender. but here all three `List` rerender
