### ISSUE TITLE
useTransition always times out for full duration when function is passed to setState call

### ISSUE THREAD

**Issue by sami616** [facebook/react#17269]
Here is a codesandbox reproducing the issue. https://codesandbox.io/s/twilight-rain-ez11m

I have two calls that setState, one in the `nextUser` function, and the other in the `prevUser` function.

You'll notice the only difference in how i'm setting state here is that i'm passing a function to the call in `prevState` and not in `nextState`. ie `setUser(v => fetchUser(v.id - 1))`

The `nextUser` call is working as expected, the `useTransition` timeout cancels if the request/s come back earlier. However, the `prevUser` call _always_ waits the entire duration, even if the requests resolve way earlier.

**Comment by gaearon** [comment]
We haven't looked at this yet.

**Comment by andreypopp** [comment]
Seeing the same.

I've tried to pass a memoized function to `setState` and then it behaves properly.

**Comment by gaearon** [comment]
The original sandbox doesn't work due to some CORS stuff. Would you mind making a minimal repro?

**Comment by andreypopp** [comment]
Ok, I wasn't able to repro but here's a codesandbox that demonstrates that everything is fine with React: https://codesandbox.io/s/interesting-jepsen-gg7w3?runonclick=1

Maybe the problem with the original codesandbox is that it isn't caching promises outside of React and React keeps restarting b/c it sees a new promise which is created inside a `setState` callback?

In my app the situation is a bit different — I observe different behaviour also depending on if I pass a callback or a value into `setState` callback but in my case this state isn't driving data fetching but reacting on an intersection observer instead. But at the end — given such setup suspense transitions time out, I guess the bug somewhere in my code with not properly cleaning up intersection observer subscriptions.

**Comment by gaearon** [comment]
>Maybe the problem with the original codesandbox is that it isn't caching promises outside of React and React keeps restarting b/c it sees a new promise which is created inside a setState callback?

Ohh good catch. I totally missed this. Yes, that would be the problem in the original example.

>In my app the situation is a bit different — I observe different behaviour also depending on if I pass a callback or a value into setState but in my case this state isn't driving data fetching but reacting on an intersection observer instead. 

Cool. Feel free to file a new issue if you can narrow it down. Could be something like https://github.com/facebook/react/issues/17911.
