### ISSUE TITLE
SuspenseList blocks rendering of later items entirely, not just revealing / committing

### ISSUE THREAD

**Issue by Winwardo** [facebook/react#17277]
**Do you want to request a *feature* or report a *bug*?**
Bug / unexpected behaviour (Possibly unclear documentation rather than code)

**What is the current behavior?**
SuspenseList appears to block rendering of later items altogether, rather than simply "revealing" them later.
This might be a documentation / expectations issue rather than a bug in SuspenseList itself.

I've implemented the "render-then-fetch" pattern in a simple naive manner. The first time a `SuspendingItemInner` is rendered, it immediately creates and throws a promise with a short delay to simulate data-loading.

https://codesandbox.io/s/suspenselist-blocks-render-instead-of-in-memory-render-react-bug-utke2

In the example, these delays are 1 second, 2 seconds, 1 second, 2 seconds, 1 second, using `<SuspenseList revealOrder="forwards" tail="collapsed">` to wrap them.

_What I see is:_
 * First item suspends. Console logs `Starting load of promise #0 with 1 second delay` . One second later, it unsuspends.
 * Second item suspends. Console logs `Starting load of promise #1 with 2 second delay` . Two seconds later, it unsuspends.
 * Third item suspends. Console logs `Starting load of promise #2 with 1 second delay` . One second later, it unsuspends.
Etc.

_What I'm expecting (hoping?) to see:_
 * First item suspends. Console logs `Starting load of promise #X with N second delay` for all 5 components. One second later, it unsuspends.
 * Second item suspends. Since its required data should have started one second ago, we wait for one second. It unsuspends, as do all the rest of the items.

**What is the expected behavior?**
My understanding of Suspense + Concurrent Mode from reading various maintainer tweets / posts is that React will attempt to render ahead as much as possible in-memory. As such, I would expect later items in a SuspenseList to start being rendered even after previous ones have chosen to Suspend. (I guess I'd expect the entire list to have Suspended in parallel.)

Note you can "fix" this by forcing all the components to render at the same time by uncommenting lines 61 to 67, because it kicks off all the data loading immediately.
I'm guessing if SuspenseList is working as intended, the "solution" is to hoist data-fetching upwards (to get to the render-as-you-fetch pattern.)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`react@0.0.0-experimental-f6b8d31a7`

(p.s. loving experimenting with Suspense + Concurrent Mode, it's a very smooth experience and I'm excited to see it implemented in more libraries / usable in production!)

**Comment by threepointone** [comment]
> I'm guessing if SuspenseList is working as intended, the "solution" is to hoist data-fetching upwards (to get to the render-as-you-fetch pattern.)

This is correct. SuspenseList doesn't render any sibling components until the preceding ones are 'complete'/not suspending. Hence the emphasis on render-as-you-fetch patterns. 

(This confused me as well when I tried it out. We should clarify in the documentation)
