### ISSUE TITLE
Setting ref.current in component which suspends

### ISSUE THREAD

**Issue by subhero24** [facebook/react#17271]
I have a problem with setting a ref from a component which throws a promise to suspend. Just want to know if this issue is intended behaviour.

I have the following component
```jsx
let doThrow = true;
function Component() {
  let ref = useRef(0);
  console.log(ref.current)
  ref.current = 1;

  if (doThrow) {
    throw new Promise((resolve, reject) => {
      doThrow = false;
      setTimeout(resolve, 1000);
    });
  } else {
    return <div>component</div>
  }
}
```

This logs `0` twice. I was surprised by this and expecting to log `0` and then `1`  as I am setting the ref to 1 before throwing. Does throwing a promise in a component undo all the ref changes? Is this intended behaviour? Could not find anything about this in the suspense docs.

**Comment by gaearon** [comment]
Yeah, Suspending before mount will not preserve component's initial state. You can expect state and refs to be destroyed. (This is why you can't hold the Suspense cache in the same component that wants to Suspend. It needs to exist externally — above or sideways.)
