### ISSUE TITLE
It's confusing that useTransition doesn't do anything outside of user-blocking events

### ISSUE THREAD

**Issue by gaearon** [facebook/react#17279]
I ran into this when implementing Back button transition in a router. Because the transition is inside a browser `popstate` event, it gets batched with the low pri update, and the pending state doesn't appear.

I had to do [this](https://github.com/gaearon/suspense-experimental-github-demo/blob/cb75d1a71847be85e1365d8b33f766a0d0e21463/src/createRouter.js#L68-L69) to work around it but it's unfortunate. We might want to fix this by treating pending state as special. Or maybe a warning — but then we need a first-class official API for opting into user blocking pri.

**Comment by dai-shi** [comment]
> the transition is inside a browser popstate event

Ah, I see...

As useTransition doesn't do anything in useEffect, I assumed it's by design.
Is it a bad idea to run the entire callback in user blocking priority?
```js
window.addEventListener('popstate', wrapCallbackWithUserBlockingPriority(handlePopState));
// or even something like ReactDOM.addEventListener('popstate', handlePopState)
```
I mean the question is only about useTransition, or any other issues suffer from low priority callbacks even if they are user initiated.

**Comment by gaearon** [comment]
You generally shouldn't run something with user-blocking priority unless it was actually initiated by user. Back Button is.

**Comment by dai-shi** [comment]
Is it only `popstate` that we want to raise the priority? It's such a special case then.

**Comment by aweary** [comment]
@gaearon should `popstate` be marked as user blocking then?

**Comment by jihlstrom** [comment]
I have been playing around with concurrent mode and I'm impressed with how well the pieces fit together and easy it is to design complex transitions. Well done! 

Regarding transitions, does it make sense to do a timeout on the initial render? and in case it does, how would I go about doing that?

**Comment by gaearon** [comment]
Closing as a duplicate of https://github.com/facebook/react/issues/17272
