### ISSUE TITLE
ReactDOM.render adds  " " or replaces ' ' with " " for background and background-image for the inside URL not the outer

### ISSUE THREAD

**Issue by volkandkaya** [facebook/react#17287]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

When I use `ReactDOM.render(element, span) ` it will add " " around a url for background-image, it will replace ' ' with " ". This is causing a problem when trying to render the page in HTML as I end up with <div style="background-image: url("example.png");"></div>

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/beautiful-keldysh-zibhp

**What is the expected behavior?**

To not add extra " " to background-image urls

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6

**Comment by jddxf** [comment]
It's browser rather than React that does this for you.
![image](https://user-images.githubusercontent.com/11155177/68283968-88a8cb00-00b7-11ea-981f-4ec56b858e89.png)

It seems that the problem is caused by an unaccessible image.

**Comment by volkandkaya** [comment]
@jddxf  The image works fine. It works fine with other JS just not React.

**Comment by volkandkaya** [comment]
Also added it to https://jsfiddle.net/2p78u3qn/

If I use no " " or ' ' it works fine and nothing is added. Only seems to be ReactDOM.render that adds the extra in.

**Comment by jddxf** [comment]
It does work.
https://codesandbox.io/s/elated-snowflake-t9dod

**Comment by volkandkaya** [comment]
> It does work.
> https://codesandbox.io/s/elated-snowflake-t9dod

I'm talking about the rendered HTML, I want to use the HTML that ReactDOM.render gives to use to generate static sites. At the moment I can't because it adds " " to the inside of url for no reason.

**Comment by jddxf** [comment]
Does [ReactDOMServer.renderToStaticMarkup](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup) meet your needs?

**Comment by volkandkaya** [comment]
@jddxf Thanks a lot worked perfectly. I wish I knew you could use Server functions on the client side would have saved me weeks of work before.
