### ISSUE TITLE
useContext hook - Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by aedilyan** [facebook/react#17280]
Randomly getting error ***"Invalid attempt to destructure non-iterable instance"*** on useContext.

console error -> https://prnt.sc/psvrcn
source file -> https://github.com/aedilyan/simple-react-app/blob/master/src/components/header/Header.js#L11

as a workaround I use conditional assignment e.g. Array.isArray(useContext(AuthContext)) ? useContext(AuthContext) : [{}, function(){}];

Please advice!

**Comment by jamesmosier** [comment]
This question might be better suited for [stackoverflow](http://stackoverflow.com/) but in your case, you can add a default value to your `createContext()` call  [here](https://github.com/aedilyan/simple-react-app/blob/master/src/App.js#L13) so then it will have the default available before the `value` is set on the provider.

For example,

`export const AuthContext = React.createContext([{}, function(){}]);`

**Comment by threepointone** [comment]
A default value is a good option for this usecase, as is conditionally checking before destructuring.

**Comment by aedilyan** [comment]
OK - Thanks

**Comment by sompodsign** [comment]
put a default value. It's good option.
