### ISSUE TITLE
How to get react component Name inside componentDidCatch in producation build?

### ISSUE THREAD

**Issue by slgauravsharma** [facebook/react#17288]
How to get react component Name inside componentDidCatch in producation build?

I used error boundary inside (componentDidCatch)I want to log which react component is break in producation build.
conclusion is get react component Name inside componentDidCatch in producation build.

**Comment by eps1lon** [comment]
If you console.error or console.warn the devtools will append the component stack trace automatically. You have to enable it in the settings first though:
![Screenshot from 2019-11-06 09-57-46](https://user-images.githubusercontent.com/12292047/68283507-f2a37f00-007b-11ea-9192-283f704beb6f.png)

However, most of what goes into the component name is minified in the production build. You would have to disable mangling of variable names to get the full display name in all cases.

**Comment by slgauravsharma** [comment]
Thanks for answer @eps1lon
Yes but I am talking about general case, because client or any users have no dev tools right. so need some generic solution that it work every where. if any configuration required in build time or anything then let me know.

**Comment by eps1lon** [comment]
If you're interested in the component that threw then you could include the component name in the thrown error. But for generic errors you can't access the component stack.

**Comment by slgauravsharma** [comment]
My concern how get component name that is break in prod. give code that is more helpful.

**Comment by nikolaykrashnikov** [comment]
`static displayName = "Component Name";`
then use it

**Comment by slgauravsharma** [comment]
@nikolaykrashnikov not working in production mode inside componentDidCatch.

**Comment by aweary** [comment]
@slgauravsharma settings `displayName` should result in React including it in the error stack, even in production. [Here's an example of what that would look like](https://codesandbox.io/s/jovial-ives-0jm1e). If you're seeing something different, please share a code example reproducing your problem.

Note that we typically don't recommend adding `displayName` everywhere as it will result in the full component names being included in your production build, increasing the size of your production bundles.
