### ISSUE TITLE
Hooks and Refs: Setting state before async function causes a null ref

### ISSUE THREAD

**Issue by jmbockhorst** [facebook/react#17297]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I found a weird bug that setting the state before calling an async functions nullifies the refs for the rest of that function.

In this example, calling `setData()` before the async function in `handleChange` causes the `ref1.current` to be null. This only happens when the state is set right before the function.

It also only happens in a function component with hooks.
https://codesandbox.io/s/optimistic-taussig-bxl3s

```
function func() {
  return new Promise(resolve => {
    setTimeout(() => resolve(true), 1000);
  });
}

function App(props) {
  const [data, setData] = React.useState("");

  const ref1 = React.createRef();

  function handleChange() {
    setData("test");
    func().then(success => {
      console.log(ref1.current); // This prints 'null', should be the ref
    });
  }

  return (
    <div>
      <input ref={ref1} onChange={handleChange.bind(this)} />
    </div>
  );
}
```

Here are a few more examples when it works unexpectedly:
```
  async function handleChange() {
    setData("test");
    await func().then(success => {
      console.log(ref1.current); // prints 'null'
    });

    console.log(ref1.current); // prints 'null'
  }
```

It seems to be related to just the async functions
```
  function handleChange() {
    setData("test");
    func().then(success => {
      console.log(ref1.current); // prints 'null'
    });

    console.log(ref1.current); // prints '<input></input>' correctly
  }
```

**However, when you remove the state setter, it works correctly**
```
  async function handleChange() {
    // setData("test"); commenting the state setter out causes a correct behavior
    await func().then(success => {
      console.log(ref1.current); // prints '<input></input>'
    });

    console.log(ref1.current); // prints '<input></input>'
  }
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.11.0 and earlier
Edge Chromium/Chrome/Windows 10 (The only ones I'v tested it on)

**Comment by jddxf** [comment]
You should use [useRef](https://reactjs.org/docs/hooks-reference.html#useref) in function component. It guarantees that the same ref container is returned on every render. With `React.createRef`, a new ref container is created on every render.

**Comment by jmbockhorst** [comment]
Thanks, `useRef` fixes the issue. However it's not clear from the documentation on hooks that you shouldn't use the old way of refs.
