### ISSUE TITLE
Supported API for making new event types (i.e., event plugin injection)

### ISSUE THREAD

**Issue by tmcw** [facebook/react#1729]
I'm trying to implement a scrollable list of items that are tappable on mobile devices. It looks like there are two plugins that address the 'how to tap' problem - https://github.com/facebook/react/blob/master/src/browser/eventPlugins/MobileSafariClickEventPlugin.js & https://github.com/facebook/react/blob/master/src/browser/eventPlugins/TapEventPlugin.js .

I'm confused about Plugins: they [aren't mentioned in the docs](http://facebook.github.io/react/docs/getting-started.html), and it's unclear if they're things that you can build in runtime, with `require('react')` or which [require recompilation with Grunt](https://github.com/facebook/react/issues/436). Is the plugin system itself in flux? I'd love to help out on [getting these merged](https://github.com/facebook/react/pull/1170) so that developing mobile apps is more straightforward.

**Comment by jareware** [comment]
Yes! This is exactly what I'd want. That is, being able to tell React to start managing new named DOM events, e.g.:

```js
// NOTE: Fictive API:
React.registerDomEvent({
  eventName: 'foo-bar',
  eventProp: 'onFooBar'
});
```

Having an API like this would make it much, much simpler to hook in things like [external gesture recognizers](http://hammerjs.github.io/) etc.
