### ISSUE TITLE
Adding visible state to Suspense Fallback component to enhance CSS transitions.

### ISSUE THREAD

**Issue by jimmy-e** [facebook/react#17296]
**Do you want to request a *feature* or report a *bug*?**
Feature I suppose.

**What is the current behavior?**
Suspense fallback component flashes on and immediately unmounts (flashes off) when fetching is complete. See similar discussions [here](https://stackoverflow.com/questions/57404653/react-suspense-prevent-flashing-of-fallback-spinner) and [here](https://stackoverflow.com/questions/54158994/react-suspense-lazy-delay).

**What is the expected behavior?**
It would be ideal to add better transitions to the fallback component when it mounts and unmounts, but doing so requires using something like [TransitionGroup](https://reactcommunity.org/react-transition-group/transition-group) or [Framer Motion](https://www.framer.com/api/motion/animate-presence/), which require a prop to listen to know when to mount and unmount. If we could somehow have the fallback component receive some kind of state from Suspense on when it is mounting and unmounting the fallback component, that would be great.

**Comment by yanickrochon** [comment]
You might be interested with the new [`useTransition`](https://reactjs.org/docs/concurrent-mode-patterns.html) that will most likely make it as an official React hooks. Personally, I have implemented my own meanwhile, and will refactor later.

**Comment by jimmy-e** [comment]
Thanks @yanickrochon but the `useTransition` hook doesn't seem to be able to have `Suspense` communicate to the fallback when the fallback is getting mounted and unmounted, unless I am missing something?

**Comment by gaearon** [comment]
This is something we're interested in. Want to write an RFC? https://github.com/reactjs/rfcs

**Comment by jimmy-e** [comment]
@gaearon on it, will try to take write up this weekend.

**Comment by jimmy-e** [comment]
@gaearon , RFC has been written [here](https://github.com/reactjs/rfcs/pull/154), thanks!
