### ISSUE TITLE
Add a more minimal API for react-test-renderer/shallow

### ISSUE THREAD

**Issue by JoelCodes** [facebook/react#17294]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

In order to use `react-test-renderer/shallow` to make shallow snapshots, there are three steps:
* Create a new renderer
* Render the JSX expression
* Get the output

Consider the following component.

```jsx
function Small({children}){
  return (<small>{children}</small>);
}
function TopHeading({mainText, smallText}){
  return (<h1>
    {mainText} 
    {smallText ? (<Small>{smallText}</Small>)}
  </h1>);
}
```

In order to test the compositional logic of `TopHeading` with a shallow snapshot test, the following code is necessary:

```jsx
import {ShallowRenderer} from 'react-test-renderer/shallow';

const headingWithSmallText = (<TopHeading mainText="Hello" smallText="World" />);
const renderer = ShallowRenderer.createRenderer();
renderer.render(headingWithSmallText);
const headingWithSmallTextShallowRendered = renderer.getRenderOutput();
expect(headingWithSmallTextShallowRendered).toMatchInlineSnapshot(`
  <h1>
    Hello
   <Small>
      World
    </Small>
  </h1>
`);
```

**What is the expected behavior?**

It would be great to have one function, preferably named "shallow", that would do many of those steps.  My test could then read as follows:
```jsx
import {shallow} from 'react-test-renderer/shallow';

const headingWithSmallText = (<TopHeading mainText="Hello" smallText="World" />);
expect(shallow(headingWIthSmallText)).toMatchInlineSnapshot(`
  <h1>
    Hello
    <Small>
      World
    </Small>
  </h1>
`);
```
This would only need to be a wrapper around the more complicated version above, and `ShallowRenderer` would not change its API, requiring no one to change their code.

**Comment by threepointone** [comment]
We’re not actively working on shallow renderer right now, preferring to use a ‘real’ renderer like react-dom, or react-test-renderer as an alternative, when writing tests. It’s unlikely we’ll add a new api for it any time soon. That said, you should be able to make your own function/abstraction that does exactly what you said?
