### ISSUE TITLE
why use setTimeout in useEffect cause render again and agin

### ISSUE THREAD

**Issue by shenmafuyunnan1** [facebook/react#17299]
use setTimout in useEffect cause render again and again, i think it is unexpected.

```
import React, { useEffect, useState } from 'react';

interface IProps {
  aText?: string[];
  bText?: string[];
}

export const Common: React.FC<IProps> = props => {
  console.log('header');
  const { aText = [], bText = [] } = props;

  const [showAText, setShowAText] = useState('');

  useEffect(() => {
    setShowAText(`a is ${aText[0]}`);
    setTimeout(() => {
      setShowAText(`b is ${bText[0]}`);
    }, 0);
  }, [aText, bText]);

  return (
    <div>
      <div>{showAText}</div>
    </div>
  );
};

const Renderer: React.FC = () => {
  return (
    <div>
      <Common aText={['render']}></Common>
    </div>
  );
};

export default Renderer;
```
when this code run, the browser console always print 'header', if i comment  setTimeout, just use ` setShowAText(`b is ${bText[0]}`);`, it will be ok.
why it is work?

macOS: 10.15.1
react: 16.9.0
chrome:  78.0.3904.87

![image](https://user-images.githubusercontent.com/14138188/68362232-75523a00-0161-11ea-96ff-3e423394eeff.png)

**Comment by dai-shi** [comment]
Try defining `const emptyArray = [];` outside of the component and changing the line to `const { aText = emptyArray, bText = emptyArray } = props;`.

**Comment by shenmafuyunnan1** [comment]
> Try defining `const emptyArray = [];` outside of the component and changing the line to `const { aText = emptyArray, bText = emptyArray } = props;`.

3Q, I know this solution,  but i care more  why use setTimeout would cause this problem and remove setTimeout work fine

**Comment by dai-shi** [comment]
Sorry, I misunderstood the issue.

If you have multiple setShowAText's in useEffect, they will be batched and it will bail out because of unchanged text.
So, if it's
```js
    setShowAText(`a is ${aText[0]}`);
    setTimeout(() => {
      setShowAText(`a is ${aText[0]}`);
    }, 0);
```
it will stop because the text doesn't change.

**Comment by shenmafuyunnan1** [comment]
> Sorry, I misunderstood the issue.
> 
> If you have multiple setShowAText's in useEffect, they will be batched and it will bail out because of unchanged text.
> So, if it's
> 
> ```js
>     setShowAText(`a is ${aText[0]}`);
>     setTimeout(() => {
>       setShowAText(`a is ${aText[0]}`);
>     }, 0);
> ```
> 
> it will stop because the text doesn't change.

I find use async operation in useEffect maybe cause this problem.  I thought use async operation 
in useEffect was fine, but it maybe not true sometimes.
I modified the code to make it easy to understand, and the code also has problem.

```import React, { useEffect, useState } from 'react';

interface IProps {
  aText?: string[];
  bText?: string[];
}

export const Common: React.FC<IProps> = props => {
  console.log('header');
  const { aText = [], bText = [] } = props;

  const [showAText, setShowAText] = useState('');

  useEffect(() => {
    // eg . just default value
    setShowAText(`place holder is ${aText[0]}`);
    // fetch something
    new Promise(resolve => {
      resolve(1);
      // delay 1s also can cause the problem
      // setTimeout(() => {
      //   resolve(1);
      // }, 1000);
    }).then(res => {
      console.log(res);
      let text = bText.length === 0 ? 'default text' : bText[0];
      setShowAText(`${text} : ${res}`);
    });
  }, [aText, bText]);

  return <div>{showAText}</div>;
};

const Renderer: React.FC = () => {
  return <Common aText={['render']}></Common>;
};

export default Renderer;

```

**Comment by threepointone** [comment]
On every render, bText will be a new array instance, which will trigger the effect again. 

Why this *doesn't* happen in a synchronous world, is that the fresh render will not happen again because the setState will bail out. 

This isn't a bug or feature request, so I'm going to close this issue. Consider using a community resource for more discussion about this https://reactjs.org/community/support.html
