### ISSUE TITLE
[react-dom] hydrate / render fail from deferred script in document with xhtml doctype 

### ISSUE THREAD

**Issue by sulmanen** [facebook/react#17290]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When using an xhtml doctype (hbbtv in this case) and the defer attribute for the client side script, react-dom.hydrate/render fails with 
```
  TypeError: right-hand side of 'in' should be an object, got undefined react-dom.production.min.js:50:314
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
[codesandbox hydrate fail replication](https://codesandbox.io/s/thirsty-blackburn-zn50y)
[codesandbox render fail replication](https://codesandbox.io/s/prod-surf-fdg7f)

**What is the expected behavior?**
When using an xhtml doctype and deferred client side script, react-dom.hydrate/render completes.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
(at least)
- react 16.11.0, 16.8.6
- react-dom 16.11.0, 16.8.6

Browsers affected: (at least)
- Firefox (MacOS 10.14.6) 70.0.1 (64-bit) 
- Safari (MacOS 10.14.6) Version 13.0.3 (14608.3.10.10.1)
- Chrome (MacOS 10.14.6) Version 78.0.3904.87 (Official Build) (64-bit)
- Chrome (Win 8.1) Version 76.0.3809.132 (Official Build) (32-bit)

Not affected: (at least)
- IE 11 (Win 8.1)

**Comment by aweary** [comment]
Hey @sulmanen, ReactDOM only supports rendering an HTML document. XHTML or other XML-like formats are not supported. If you can reproduce this problem using an HTML document, let me know and we can investigate!
