### ISSUE TITLE
infinite recursion when using development cdnjs libraries in a tampermonkey user script

### ISSUE THREAD

**Issue by prozacgod** [facebook/react#17302]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

development versions of the library > 6.4.2 - cause infinite recursion and crash/slowdowns when used in the tampermonkey environment when including the development libraries for react and react-dom. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

You would need to install tampermonkey in Google Chrome, and then install this test user script

https://gist.github.com/prozacgod/e1aad87eb8aa835ff257081cad7f9d88

after that launch a local server of any sort on port 8080, as the gist specifies localhost - hosting a bare minimum index.html

**What is the expected behavior?**

It should render Foo! on the blank page

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

It seems to work fine with 16.4.x -> 16.5.x (I did not test lower) but many selected versions past 16.4 did cause the issue.  only the Development builds break.

Just a guess, but mayber tampermonkey environment exposes a property that react did not use before, but does now - and it may be 'frozen' or 'proxied' in this environment.

P,S, - I'm happy to supply feedback, and further test - I'm rather divided in my time, but I'll try to check back.

I also understand if react doesn't want to support development libraries for tampermonkey environment.

**Comment by threepointone** [comment]
Just to confirm, could you confirm whether the issue exists with 16.11.0 as well?

**Comment by prozacgod** [comment]
I modified the userscript like this

```
// @require       https://unpkg.com/react@16.11.0/umd/react.development.js
// @require       https://unpkg.com/react-dom@16.11.0/umd/react-dom.development.js

```

The issue still cropped up

```
Uncaught TypeError: Cannot set property event of #<Object> which has only a getter
    at HTMLUnknownElement.callCallback (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:4243)
    at HTMLUnknownElement.dispatchEvent (<anonymous>)
    at Object.invokeGuardedCallbackDev (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:4295)
    at invokeGuardedCallback (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:4350)
    at commitRootImpl (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:29070)
    at unstable_runWithPriority (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:3099)
    at runWithPriority$2 (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:16192)
    at commitRoot (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:28951)
    at finishSyncRender (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:28358)
    at performSyncWorkOnRoot (userscript.html?id=3cd71a3a-0582-48f6-9000-9fe7df7bc153:28336)

```

It inserts thousands of these in the console.

**Comment by derjanb** [comment]
Hi, Tampermonkey dev here. This is caused by Tampermonkey's sandbox not being prepared for react's way to use window.event. The issue will be fixed at the next beta release.

**Comment by threepointone** [comment]
Thank you for the update!
