### ISSUE TITLE
DevTools: Updating state or props in devtools does not trigger component update.

### ISSUE THREAD

**Issue by thisisDom** [facebook/react#17305]
Do you want to request a feature or report a bug?

bug

What is the current behavior?

Changing state or props for a component in React-Devtools isn't updating component.

What is the expected behavior?

Component should reflect changes made to state/props in React-Devtools

Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?

Using React-Devtools v4 w/ React 16.9
Working in v3 of React-Devtools

**Comment by threepointone** [comment]
This needs more information than just saying it doesn't work. Could you use codesandbox to make a reproducing example?

**Comment by thisisDom** [comment]
https://codesandbox.io/s/y2lrywpk21
[https://www.dropbox.com/s/jfjak9t32lyv599/Screen%20Shot%202019-11-07%20at%203.46.26%20PM.png?dl=0](Screenshot)

**Comment by thisisDom** [comment]
Here is the codesandbox I used:
https://codesandbox.io/s/y2lrywpk21

I changed the value of state.text to "test" in React-Devtools but the change isn't reflected in the input field. I uploaded a screenshot below.

[https://www.dropbox.com/s/jfjak9t32lyv599/Screen%20Shot%202019-11-07%20at%203.46.26%20PM.png?dl=0](Screenshot)

**Comment by hristo-kanchev** [comment]
@thisisDom I can't reproduce the issue. 
Did you by any chance forgot to press Enter after you entered the text?

**Comment by thisisDom** [comment]
Yeah looks like that was my issue. In the previous version, I could click out of the console and it would update. Thank you

**Comment by hristo-kanchev** [comment]
@thisisDom We have a PR open for this https://github.com/facebook/react/pull/17062 👍
