### ISSUE TITLE
Is it possible to reuse component's instance?

### ISSUE THREAD

**Issue by rabbitooops** [facebook/react#17317]
```tsx
function Test({value}) {
  return <span>{value}</span>
}
```
Now I have:
```tsx
<Test value="1" />
```
Then I want:
```tsx
<Host>
  <Test value="2" />
</Host>
```
Is it possible to reuse Component Test's instance for withouting recreate DOM elements for better performance.

**Comment by rabbitooops** [comment]
I ask this question for dynamic rendering. I don't know what it will be rendered to:
```tsx
<Host1>
  <Host2>
    <Test />
  </Host2>
</Host1>
```
or:
```tsx
<Host1>
  <Host2>
    <Host3>
      <Test />
    </Host3>
  </Host2>
</Host1>
```

**Comment by rabbitooops** [comment]
I have tried to memorize the element when I created:
```ts
const [toggle, setToogle] = useState(false)
useEffect(() => {
  setTimeout(() => setToggle(true), 10000)
}, [])
const ref = useRef(<Test />)

return <div>
  {toggle ? <div>{ref.current}</div> : ref.current}
</div>
```
But not work.

**Comment by rabbitooops** [comment]
I guess this feature mays lead to some very complicated situations or rarely used so React doesn't support it.

**Comment by threepointone** [comment]
That’s right, components at “different” parts of the tree don’t share instances for consistency.

**Comment by rabbitooops** [comment]
But what if user would like to reuse DOM intentionally? I think this is a fun feature.
