### ISSUE TITLE
React build is failing to execute

### ISSUE THREAD

**Issue by joshi-chinmay** [facebook/react#17311]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After creating the build, I run the command to validate if my production build is running properly or not.
For that, I use `serve -s build/`. That gives me an error, which is not making any sense to me.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Step 1 - This is what my package.json looks like.
<img width="525" alt="Screenshot 2019-11-07 at 10 39 50 PM" src="https://user-images.githubusercontent.com/16207311/68448129-7eb6c300-01b0-11ea-9ec7-e5bf0f84b145.png">

Step 2 - I run my code on local machine using `npm run start`. Everything works fine without any errors or warnings.
<img width="377" alt="Screenshot 2019-11-07 at 10 40 20 PM" src="https://user-images.githubusercontent.com/16207311/68448164-98580a80-01b0-11ea-80cb-c82afbae59f1.png">

Step 3 - Hence, I go and create a production build using `npm run build`. Which creates a `build/` folder for me. This is what it looks like.
<img width="583" alt="Screenshot 2019-11-07 at 10 41 02 PM" src="https://user-images.githubusercontent.com/16207311/68448204-ba518d00-01b0-11ea-8c56-d763f2cd5504.png">

Step 4 - So, I check how my build folder looks like using serve.
<img width="429" alt="Screenshot 2019-11-07 at 10 41 28 PM" src="https://user-images.githubusercontent.com/16207311/68448510-b96d2b00-01b1-11ea-8cd9-b984cb68a2c5.png">

Step 5 - BUT! This happens when I open `localhost:5000`.
<img width="1680" alt="Screenshot 2019-11-07 at 10 42 18 PM" src="https://user-images.githubusercontent.com/16207311/68448658-37c9cd00-01b2-11ea-8295-047203970b7f.png">

I do not have enough expertise to debug the issue, hence decided to post here. I am guessing this has something to do with babel-loader or babel.

**What is the expected behavior?**
I wish to see my production build in the browser.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version is - `v16.11.0`
Browser - Google Chrome.

**Comment by threepointone** [comment]
Please post this issue at https://github.com/facebook/create-react-app/issues. I’d also recommend making and sharing a reduced version of your codebase that reproduces the problem, or it would be hard to debug and help you.
