### ISSUE TITLE
Concurrent Mode and UseSubscription with RxJS "lose" updates 

### ISSUE THREAD

**Issue by samcooke98** [facebook/react#17314]
**Do you want to request a *feature* or report a *bug*?**
**Bug** - I think? 

**What is the current behavior?**

In Concurrent Mode, it appears that if a render is interrupted, if a component is using `useSubscription` the interrupted update is lost, which leads to "tearing" 

The following codesandbox uses `useSubscription` with a RxJS `BehaviorSubject`, mimicking the example from here: https://www.npmjs.com/package/use-subscription#subscribing-to-observables 

In the sandbox, clicking on the "Increment Remote Count" button triggers the RxJs `BehaviorSubject` to increment. This is done outside of the React event handler (ie: via `window.addEventLIstener` and so the updates are not batched together. The update to render the numbers is artificially slowed down. 

If you click the "Increment Remote Count" button multiple times, the update works as expected. 

If you interrupt the update, via clicking the "increment local count", only the last number will update. 

So the Steps to reproduce look like: 
1. Click the "Increment Remote Count" button once
2. Before the update is committed to the DOM, click the "Increment Local Count" update. 
3. The first update is "lost" ie; the output looks like: 

![image](https://user-images.githubusercontent.com/787007/68468141-27255f80-0263-11ea-9afb-07964e21d9d9.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jwenc.csb.app/ \ https://codesandbox.io/s/usesubscriptionconcurrentlosingupdates-jwenc 

**What is the expected behavior?**

I'd expect there to be a commit as the above screenshot, but I'd then expect there to be a follow-up commit that restores the consistency. In other words, I'd expect in the above picture for everything to be `1` 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`0.0.0-experimental-f6b8d31a7`

I'd be willing to try to take a stab at writing a React test for this, if needed?

**Comment by dai-shi** [comment]
https://github.com/facebook/react/issues/16396#issuecomment-547193356
Here's codesandbox I created.

**Comment by samcooke98** [comment]
Started looking into why this happens - https://github.com/facebook/react/pull/17336

Seems like an issue somewhere in `updateSimpleMemoComponent`

**Comment by dai-shi** [comment]
Maybe related: https://github.com/facebook/react/issues/17318#issuecomment-552167774

**Comment by salvoravida** [comment]
yes i already signaled here : https://github.com/facebook/react/issues/17318#issuecomment-552160358

**Comment by albertogasparin** [comment]
Reported similar issue some time ago: https://github.com/facebook/react/issues/17028

**Comment by acdlite** [comment]
Thanks for the bug report!

I believe this was fixed by https://github.com/facebook/react/pull/18091

You can confirm using `react@0.0.0-experimental-ea6ed3dbb` and `react-dom@react@0.0.0-experimental-ea6ed3dbb`.

I'm going to close this issue, but if the bug persists please comment and we'll reopen.

**Comment by samcooke98** [comment]
Rebased https://github.com/facebook/react/pull/17336/files and the test was green - thanks!

**Comment by acdlite** [comment]
@samcooke98 Thank you for that PR! I feel a bit guilty that it got buried and I didn't notice it. But I really appreciate that you took the time to write a unit test 😮We'll try to do a better job keeping track of our PR queue!

**Comment by samcooke98** [comment]
No worries, was a nice learning experience
