### ISSUE TITLE
Effect is not run (not even once) when state setter is called in function body

### ISSUE THREAD

**Issue by charshin** [facebook/react#17313]
Please help me understand how state setter works when called inside a function body

I have the following code:

![image](https://user-images.githubusercontent.com/17873916/68467878-f557cd00-0251-11ea-9479-5a3f6811fece.png)

Running this code will result in infinite re-rendering. According to the React documentation, it says `The setState function is used to update the state. It accepts a new state value and enqueues a re-render of the component.`. I interpret this as the next render will be enqueued and run after the current render finishes, including running the effect. However, the effect is never run at all, not even once, and the chain of re-rendering is happening forever without any bailing out even the code is updating the same state again, i.e. 1

Please help me understand the internal working of this piece of code.

**Comment by vkurchatkin** [comment]
That's because you call setState synchronously in you render, which basically tells that your current render should be discarded, including effects.

**Comment by bpas247** [comment]
@charshin what are you trying to do here, exactly? what is your end goal?

**Comment by gaearon** [comment]
> That's because you call setState synchronously in you render, which basically tells that your current render should be discarded, including effects.

This is right.
