### ISSUE TITLE
Confusing behavior in Suspense

### ISSUE THREAD

**Issue by baldarian** [facebook/react#17325]
I was just following the documentation of Concurrent mode and found a behavior that confused me.

Open this example and press `Open Profile` button.
https://codesandbox.io/s/focused-snow-xbkvl

This way transition works as expected.
- Pending (until `ProfileDetails` is ready)
- Skeleton (displays a spinner for `ProfileTimeline`)
- Complete (Everything is fetched)

But if you press `Refresh` button you'll something different.

You have to wait until all the components are ready in the tree (both `ProfileDetails` and `ProfileTimeline`). However, I'd expect it to behave the same way as when we clicked the `Open Profile` button.

I know this is something I can fix with `useDeferredValue`, but I'm curious to know the reasons for such behavior.

**Comment by gaearon** [comment]
Bump so we don’t forget to look
