### ISSUE TITLE
irrelevant useState error when component is in UpperCase

### ISSUE THREAD

**Issue by deepakaggarwal7** [facebook/react#17326]
"eslint-plugin-react": "^7.16.0",
    "eslint-plugin-react-hooks": "^2.2.0",
    "eslint-plugin-react-native": "^3.8.1",

```
const HOC = component => props => {
  const [currIndex, setCurrIndex] = useState('')
  return <passedcomponent {...props} />
}
```
This throws an eslint error: "React Hook "useState" cannot be called inside a callback."
If I rename component to begin with lowercase, it works. So there are two problems:
1. Encrypted error message
2. It should be reverse. Uppercase should be enforced instead of lowercase

**Comment by deepakaggarwal7** [comment]
Not relevant here. Should go to eslint library.

**Comment by deepakaggarwal7** [comment]
didn't realize it's the same repo

**Comment by dukemai** [comment]
hmm, but the current message is reasonable since the HoC component should wrap a component and return a new component, right?
