### ISSUE TITLE
Can't back to initialed state with useState

### ISSUE THREAD

**Issue by hrahimi270** [facebook/react#17333]
**Do you want to request a *feature* or report a *bug*?**
It's not a feature, but I'm not sure if it's a bug or mistake of mine.

**What is the current behavior?**

I initialed my state on useState with a number. but I can't back to that initialed state after doing some stuff in my code. for example, pass some conditions.

**What is the expected behavior?**

I want to be able to pass the initial value as the new state value, but it's not working.
For better understanding, I created a reproduce project in sandBox to check it out.
https://codesandbox.io/s/serene-driscoll-qlqq3?fontsize=14

**Comment by kunukn** [comment]
>I initialed my state on useState with a number

The initial state is 1: `useState(1)`

>I can't back to that initialed state after doing some stuff in my code.

When it hot-reloads in Codesandbox, then the state is reset to 1.
I am not sure if this is what you want. But if you add at the top in your `useEffect` code.

`window.scrollTo(0, 0);`

Then the page scroll calculations should be correct even if it hot-reloads in Codesandbox.
