### ISSUE TITLE
setState() not working even with deep copy of state

### ISSUE THREAD

**Issue by hondahmd** [facebook/react#17337]
I wrote a  small 'Todo App'. The add and change functions works properly, but the delete function just won't work. I used the deep copy of the state called 'copyState' and delete something in it and then setState(copyState), but the page won't refresh though the content in copyState has changed.

```javascript
const deleteId = Number(event.target.id.split(' ')[0]); // here I got the id of object that I want to delete
let copyState = _.cloneDeep(this.state);  // here I got a deep copy of this.state, the '_' stands for Lodash library
delete copyState[deleteId]; // deleting
this.setState(copyState); // unfortunately not working
```

**Comment by Naaman-Saif** [comment]
Hi, can you check in `shouldComponentUpdate` If the state is actually being changed? AFAIK Changes in deep object Doesn’t update component since it does a shallow comparison.

**Comment by lsnch** [comment]
How do you store the list? I'm pretty sure you need to have it as `this.state = { todos: [] }` rather than `this.state = []`

**Comment by VaibhavAcharya** [comment]
Can you provide some more code to look into?

**Comment by hondahmd** [comment]
> Hi, can you check in `shouldComponentUpdate` If the state is actually being changed? AFAIK Changes in deep object Doesn’t update component since it does a shallow comparison.

I checked it and found state not changed. But without deep copy how can I make sure that I don't mutate this.state, or maybe I should try to change it into an array and use spread?

**Comment by hondahmd** [comment]
> Can you provide some more code to look into?

[here](https://github.com/green-fox-academy/hondahmd/blob/master/week-04/day-02/02/src/todolist.js#L76)

**Comment by hondahmd** [comment]
> How do you store the list? I'm pretty sure you need to have it as `this.state = { todos: [] }` rather than `this.state = []`

Currently it is like Object{Object}, I will try to change it into Object{todos: [Object]}

**Comment by threepointone** [comment]
In your code, `deepCopyState()` is not making a deep copy, it's only making a shallow copy of the state, and then mutates this.state[key] for every key. You'd need to do something like 

```jsx
    deepCopyState() {
        let copyState = {};
        for (let key in this.state) {
            copyState[key] = {...this.state[key]}; // returns a fresh copy of this value too
        }
        return copyState;
    }
```
or, since you already have lodash available 
```jsx
    deepCopyState() {
        return _.cloneDeep(this.state)        
    }
```
Hope that helps. Closing since this isn't a bug/feature request.
