### ISSUE TITLE
New hook for useEffect and empty array

### ISSUE THREAD

**Issue by johnnysprinkles** [facebook/react#17342]
**Do you want to request a *feature* or report a *bug*?**

New feature

**What is the current behavior?**

The second parameter to `useEffect` isn't especially clear or explicit. Empty array for "observe nothing" and undefined for essentially "observe everything." Since the former case is so common (used where componentDidMount would have been used for things like ajax calls), what about a verbosely named dedicated hook? The only hard part here is finding the right name.

**What is the expected behavior?**

I'd suggest `useEffectObservingNothing`. This removes the notion of meaningful changes that hinge on subtle syntax changes (empty array vs undefined). Explicit is better than implicit as they say in Python, and I'm always happy to borrow from their philosophy.

This would pretty much be a one liner.

    function useEffectObservingNothing(fn) {
      return React.useEffect(fn, []);
    }

Just thought I'd throw out the idea...

**Comment by kunukn** [comment]
There are many custom hooks out there.

I believe this is also known as `useEffectOnce`

Code example:
https://github.com/streamich/react-use/blob/master/src/useEffectOnce.ts

The docs says:
https://reactjs.org/docs/hooks-effect.html

>If you want to run an effect and clean it up only once (on mount and unmount), you can pass an empty array ([]) as a second argument. This tells React that your effect doesn’t depend on any values from props or state, so it never needs to re-run. This isn’t handled as a special case — it follows directly from how the dependencies array always works.

Personally I started using `useEffectOnce` to avoid the gotchas when forgetting to apply the empty array. Now I have gotten used to remember putting the empty array when needed.

I don't know whether having an official `useEffectOnce` would help reduce bugs that happens when developers forget to put the empty array when needed.

**Comment by aweary** [comment]
I know that hooks like `useEffectOnce` are tempting, but we typically recommend against it. 

>  Since the former case is so common (used where componentDidMount would have been used for things like ajax calls)

This is actually a great example of where you _wouldn't_ want an API like `componentDidMount` or `useEffectOnce`. Imagine you have a `Post` component like:

```js
function Post(props) {
  useEffectOnce(() => {
    // Fetch a post using props.id
    fetch(`/posts/${props.id}`).then(res => {
      // Set state...
    });
  });
  // ...
}
```

It initially seems reasonable to fire this off only when `Post` mounts, but what happens with `props.id` changes? You can end up rendering the wrong data. This is the same problem you'd have with `componentDidMount`.

Even if your effect doesn't currently use a value from `props` it might _eventually_ be refactored to use something from `props`, in which continuing to use `useEffectOnce` would introduce subtle bugs.

I understand that forgetting to include the dependency list can lead weird behavior, but if you just use `useEffect` [with the ESLint rule for Hooks](https://reactjs.org/docs/hooks-rules.html#eslint-plugin) you'll be well guarded against these most of the problems related to effects and dependencies.

**Comment by johnnysprinkles** [comment]
That's fair. I didn't actually know people had proposed `useEffectOnce`. If you useEffect and observe nothing, one consequence of that is it should only run once, but it's better to name the thing for what it actually does, not something that follows from it. I should have done better research. I searched this repo and Google for `useEffectObservingNothing` and saw nothing, never occurred to me people would propose the same functionality on such a badly misnamed name.

But naming aside, I'm included to agree with you. It's not ideal being able to pass two different kinds of emptiness for 2nd param but adding this hook wouldn't take that ability away. Plus, the convention of passing an array for what you want to watch is used in other hooks as well, and we're not adding a `blankObservingNothing` for each one.

Thanks for considering!
