### ISSUE TITLE
useContext requires JSX/React.createElement

### ISSUE THREAD

**Issue by lxender** [facebook/react#17343]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
useContext uses the default value if the component is called as a function, whereas other hooks work fine in that situation. In other words, the hook requires the component to be called as JSX/with React.createElement.
[Checkout this demo on CodeSandbox](https://codesandbox.io/s/nervous-wave-p0es8)

**What is the expected behavior?**
useContext should behave the same regardless of the way the component is called.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
The CodeSandbox runs 16.8.6, however I also noticed this behaviour on 16.10.X. I have only tested Chrome 78 on Windows 10.

**Note:**
I don't know the underlying implementation of the new context enough to know why this is happening. Maybe someone can shine a light on it, if it's working as intended or not fixable.

**Comment by threepointone** [comment]
You shouldn’t call a component as a regular function, ever. The fact that hooks “work” are just a coincidence in this example; you can make them “break” by conditionally rendering the component.

**Comment by lxender** [comment]
But calling components as functions is necessary in some situations where React would remove the node otherwise.

**Comment by TrySound** [comment]
Which situation do you mean? Could you provide an example?

**Comment by threepointone** [comment]
Closing since this isn’t a bug or feature request, but happy to help and discuss more. I repeat, you should never call a component as a regular function. If you could show me a real usecase, I’d be happy to discuss more.

**Comment by lxender** [comment]
I thought using components from an object-prop inside a component called as a function (like `Example({components: { head: () => <h2>Hi</h2> } })`) would not cause them to be removed on parent rerender, but it does.
[See this CodeSandbox for an example](https://codesandbox.io/s/nifty-feistel-7e0wp)

I apologize for wasting your time.
