### ISSUE TITLE
Is `Context` appropriate to be used to implement DI?

### ISSUE THREAD

**Issue by zxh19890103** [facebook/react#17353]
I used Angular which uses the DI pattern very heavily.

I want to put it into my design of a REACT project. I intuitively think `Context` in REACT is the right way there.

Here is the demo:
https://codepen.io/singhijohn/pen/NWWLzBQ?editors=1010

```tsx

class UserService {
    async login() {
        console.log("login")
    }
}

const userService = new UserService()

const ServicesContext = React.createContext({ userService })

const App = (props) => {
    return <ServicesContext.Provider value={{ userService }}>
      <Main title="hello" />
    </ServicesContext.Provider>
}

const Inject = (C) => {
    return props => {
      const value = React.useContext(ServicesContext)
      return React.createElement(C, { ...value, ...props })
    }
}

const Main = Inject(({ userService, title }) => {
    return <>
        <h3>{title}</h3>
        <button onClick={() => {
           userService.login()
        }}>use service</button>
    </>
})

```

**Comment by kunukn** [comment]
It needs to be adjusted. I get rule of hooks warnings.

https://codesandbox.io/s/immutable-worker-o5d9f

> React Hook "React.useContext" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function. (react-hooks/rules-of-hooks)eslint
https://reactjs.org/docs/hooks-reference.html#usecontext


`Inject` seems to be a higher order component.
https://reactjs.org/docs/higher-order-components.html

**Comment by zxh19890103** [comment]
> It needs to be adjusted. I get rule of hooks warnings.
> 
> https://codesandbox.io/s/immutable-worker-o5d9f
> 
> > React Hook "React.useContext" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function. (react-hooks/rules-of-hooks)eslint
> > https://reactjs.org/docs/hooks-reference.html#usecontext
> 
> `Inject` seems to be a higher order component.
> https://reactjs.org/docs/higher-order-components.html

yes, the code there has a fault. Just let it alone.

I've asked a same question on stackoverflow. And I've got an answer.

https://stackoverflow.com/questions/58850413/is-context-appropriate-to-be-used-to-implement-di

**Comment by gaearon** [comment]
Yes, context is essentially a DI mechanism. However, you should be probably ditch Inject. useContext *is* how you “inject” it — an extra level of indirection is unnecessary.
