### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by BalakrishnanKumaravel** [facebook/react#17358]
Hi, I am trying to use the control https://github.com/crubier/react-graph-vis and I followed the below steps to add it to my project.

yarn add react-graph-vis

Created a new file called networkGraph.tsx and add the code below

import * as React from "react";
const Graph = require("react-graph-vis");

interface State {
}

export interface Props {
}

export class NetworkGraph extends React.Component<Props, State> {
  constructor(props: any) {
    super(props);
    this.state = {};
  }

  public render(): JSX.Element | JSX.Element[] {
    const graph = {
      nodes: [
        { id: 1, label: "Node 1", title: "node 1 tootip text" },
        { id: 2, label: "Node 2", title: "node 2 tootip text" },
        { id: 3, label: "Node 3", title: "node 3 tootip text" },
        { id: 4, label: "Node 4", title: "node 4 tootip text" },
        { id: 5, label: "Node 5", title: "node 5 tootip text" }
      ],
      edges: [
        { from: 1, to: 2 },
        { from: 1, to: 3 },
        { from: 2, to: 4 },
        { from: 2, to: 5 }
      ]
    };

    const options = {
      layout: {
        hierarchical: true
      },
      edges: {
        color: "#000000"
      }
    };

    const events = {
      select(event: any): void {  
        const { nodes, edges } = event;
        console.log("Selected nodes:");
        console.log(nodes);
        console.log("Selected edges:");
        console.log(edges);
      }
    };
    const component = (
    <Graph
      graph={graph}
      options={options}  
      events={events}
      style={{ height: "640px" }} 
    />
    );
    
    console.log(component);
    return (
      <div 
        { component }
      </div>
    );
  }
}

export default NetworkGraph;

After that I tried using the above component like below in another file.

import NetworkGraph from "./networkGraph";

<div>
            <NetworkGraph />
          </div>

After this I ran build and then tried to check the result and I got the error

console.js:35 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `NetworkGraph`.

Can you please help me fix this?

**Comment by BalakrishnanKumaravel** [comment]
The console.log(component) was having this object

![image](https://user-images.githubusercontent.com/50212828/68813781-c5cb0b00-062b-11ea-86ab-7580aa48f061.png)

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
