### ISSUE TITLE
Does anyone like modelizing state in components?

### ISSUE THREAD

**Issue by zxh19890103** [facebook/react#17359]
With three years' practices of REACT, I feel it's very verbose to use plain object or elementary value as state in components. Everytime the state needs to be updated, I must spread the whole old state and add a partial state which is the updates. Every operation for state must be defined somewhere else. 

Now I like designing a class first for the state shape and then put all the operations in. For component's updating, I just assign a new value to the property or call the method on the instance and call `setState` with an empty object. 

This is much more clear. 

How do you think of this idea?

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).

**Comment by zxh19890103** [comment]
> We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).

Thanks for leading.
