### ISSUE TITLE
Suspense data fetch is made without component being mounted

### ISSUE THREAD

**Issue by jimmy-e** [facebook/react#17360]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
NOTE: This regards Suspense and Concurrent Mode.
My `MainComponent` conditionally renders the `SuspenseComponent`, in which a sampleFetch would be made. By default, the `MainComponent` does not render the `SuspenseComponent`, however, it appears that the fetch is being made anyways.

*index.tsx:*
```js
import 'babel-polyfill';
import * as React from 'react';
import { createRoot } from 'react-dom';
import fakeApi from './fakeApi';

const SampleComponent: React.FC = () => {
  fakeApi.sampleFetch.read();
  return <h1>This is the application</h1>;
};

const SuspenseComponent: React.FC = () => (
  <React.Suspense fallback={<h3>Loading...</h3>}>
    <SampleComponent />
  </React.Suspense>
);

const MainComponent: React.FC = () => {
  const [sampleState, setSampleState] = React.useState(false);
  if (sampleState) {
    return <SuspenseComponent />;
  }
  return <h1>Application has not yet been loaded</h1>;
};

createRoot(document.getElementById('app')).render(<MainComponent />);
```

*fakeApi.ts:*
```js
interface Data {
  data: any;
}

interface Wrapper {
  read(): Data;
}

const wrapPromise = (promise: Promise<Data>): Wrapper => {
  let status = 'pending';
  let result: object;
  const suspender = promise.then(
    (r) => {
      status = 'success';
      result = r;
    },
    (e) => {
      status = 'error';
      result = e;
    },
  );
  return {
    // @ts-ignore
    // eslint-disable-next-line consistent-return
    read() {
      if (status === 'pending') {
        throw suspender;
      } else if (status === 'error') {
        throw result;
      } else if (status === 'success') {
        return result;
      }
    },
  };
};

const sampleFetch = (): Promise<Data> => new Promise((resolve) => {
  console.log('this is a sample fetch!');
});

const fakeApi = {
  sampleFetch: wrapPromise(sampleFetch()),
};

export default fakeApi;
```

*Screenshot of result:*

![screenshot](https://i.imgur.com/d5YNfku.png)

**Steps to reproduce**
1. Go to [this repo / branch](https://github.com/jimmy-e/mybord/tree/initialize_debugging)
2. Run `yarn`.
3. Run `yarn build:dev`.
4. Run `yarn start`.
5. Open up the browser to `http://localhost:8080/` and inspect the console.

**What is the expected behavior?**
The fetch should not be made.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

*package.json:*
```
    ...
    "react": "^0.0.0-experimental-38dd17ab9",
    "react-dom": "^0.0.0-experimental-38dd17ab9",
```

**Comment by aweary** [comment]
You're calling `sampleFetch` when you pass it to `wrapPromise`, so it runs when the module is loaded by Webpack.

```js
const fakeApi = {
  // sampleFetch gets called here
  sampleFetch: wrapPromise(sampleFetch()),
};
```

**Comment by jimmy-e** [comment]
Thanks @aweary. How then do I get this fetch to be invoked when a component is mounted when using concurrent mode? I am a bit confused. It seems like [this codesandbox](https://codesandbox.io/s/frosty-hermann-bztrp) provided by the react documentation invokes the fetch immediately as well.

**fakeApi.js**
```js
export function fetchProfileData() {
  let userPromise = fetchUser();
  let postsPromise = fetchPosts();
  return {
    user: wrapPromise(userPromise),
    posts: wrapPromise(postsPromise)
  };
}
```

Am I misunderstanding something? Thanks.
