### ISSUE TITLE
Devtools: higlight updated items in Components tree

### ISSUE THREAD

**Issue by syabro** [facebook/react#17363]
*feature request*

Is it possible to higlight updated items in Components tree as well?

**Comment by bvaughn** [comment]
It would be possible, but it doesn't sound very useful to me. Could you describe what use case it would help with?

**Comment by syabro** [comment]
@bvaughn sometimes I have 5-10 components one inside each other. It's hard to say which one rerenders

![image](https://user-images.githubusercontent.com/29029/68939870-c6da7480-07b2-11ea-81fd-81ee30fba13c.png)

**Comment by bvaughn** [comment]
That's where the Profiler comes in handy.

The highlight updates feature is meant to give you a quick idea of where things are happening. The Profiler is meant to give you more in-depth information (exactly what is re-rendering, how many times, for how long, etc)

**Comment by bvaughn** [comment]
I don't think we're going to implement this feature. It still seems like a use case better suited to the Profiler to me.

Thanks for describing the issue and your reasoning though!
