### ISSUE TITLE
react devtools version 3 stops immediately.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [facebook/react#17361]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
react-devtools  stops immediately
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
npm install -g react-devtools@^3
react-devtools
**What is the expected behavior?**
It needs to open devtools. I am using it for react native which requires version 3.

**Comment by threepointone** [comment]
Why do you mean by “stops immediately”. Does it not open at all? Does this happen with every project?

**Comment by a-c-sreedhar-reddy** [comment]
It does not open anything. I installed react-devtools version globally.

**Comment by a-c-sreedhar-reddy** [comment]
@threepointone 
`npx react-devtools@^3` installs packages but finally it stops without opening.
![Screenshot from 2019-11-15 12-56-17](https://user-images.githubusercontent.com/16081083/68924760-8295a700-07a7-11ea-8bda-fa84574ecac0.png)

**Comment by a-c-sreedhar-reddy** [comment]
react-native-debugger worked
