### ISSUE TITLE
[eslint-plugin-react-hooks] support useState usage without destructuring

### ISSUE THREAD

**Issue by smashercosmo** [facebook/react#17366]
**Do you want to request a *feature* or report a *bug*?**

feature (or bug, I don't know really)

**What is the expected behavior?**

This should be supported:
```js
var state = useState('')
var stateValue = state[0]
var setStateValue = state[1]
useEffect(function() {
  setStateValue('')
}, [])
```

**What is the current behavior?**
eslint-plugin-react-hooks suggests adding 'setStateValue' as dependency

**Which version of eslint-plugin-react-hooks is affected?**
v2.2.0

**Comment by threepointone** [comment]
We could possibly do this, but it would be a non-trivial amount of effort, so it would be good to understand whether it's be worth it.

Could you explain why you're not using array destructuring? It's a widely supported feature in browsers, and can be safely compiled for older browsers. If you're using React with jsx, you're likely already using a tool like babel/webpack/etc, that can make this easier.

**Comment by smashercosmo** [comment]
Ok:
1. React supports IE11
2. You want to release a package for React (e.g. custom hook)
3. Naturally, you want your custom hook to be supported by IE11
4. But you want to avoid build step to make things easier, so you write your package in IE11-compatible way (and that means no destructuring :))

But maybe it's contrived, I don't know really)

**Comment by threepointone** [comment]
The custom hook would still be used in an environment with a build step if you use jsx, right? Still shouldn’t be an issue.  

I’m going to close this issue since it’s unlikely we’ll do this. Happy to discuss if you can think of a usecase that’s more common, or if you came across a situation where you really needed it.
