### ISSUE TITLE
change aria-label to ariaLabel

### ISSUE THREAD

**Issue by zwhitchcox** [facebook/react#17378]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

`aria-label` for `input` is not camel cased like everything else

If would be nice if when you create an object for props like

```ts
const value = myval
const onChange = e => setVal(e.target.value)
const ariaLabel = "My Label"
return {
  onChange,
  ariaLabel,
  value,
}
```

**What is the expected behavior?**

`ariaLabel` to be camel cased

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

all browsers/versions of react

**Comment by zwhitchcox** [comment]
Just for an illustration, this is my real-world code:

```ts
  const { setValue, setTouched } = actions
  const title = camelToTitle(fieldName)
  const snake = titleToSnake(fieldName)
  const id = snake
  const name = snake
  const value = state[fieldName].value
  const onChange = e => setValue(fieldName, e.target.value)
  const onBlur = _ => setTouched(fieldName)
  return {
    title,
    snake,
    id,
    name,
    value,
    onChange,
    onBlur,
    "aria-label": title,
  }
```

You can that `aria-label` is the only one that I have to declare inline. Of course, I could create another variable called `ariaLabel` and assign that to the key `"aria-label"`, but that would be even messier and just creates bloat in the code.

I realize that this isn't a huge issue, but I think it would be a good improvement.

**Comment by wesleyalmd** [comment]
In [React DOCS](https://pt-br.reactjs.org/docs/accessibility.html), an accessibility applications are originally marked (hyphen-case), I believe that it has no adverse effect other than maintaining the code design standard!

**Comment by zwhitchcox** [comment]
>Whereas most DOM properties and attributes in React are camelCased, these attributes should be hyphen-cased (also known as kebab-case, lisp-case, etc) as they are in plain HTML:

That doesn't really make sense to me. It's not plain HTML, it's either JSX or javascript.

**Comment by gaearon** [comment]
It's mostly for historical reasons and at this point likely isn't worth changing. Maybe someday we'll revisit this.

**Comment by CopyJosh** [comment]
About every other month or so, I find myself making an MR to correct the console warnings caused by someone using "ariaLabel" instead of "aria-label"  🤷‍♂️
