### ISSUE TITLE
useLayoutEffect makes startTransition skip timeout 

### ISSUE THREAD

**Issue by jihlstrom** [facebook/react#17373]
**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
I am using the router implemented in the relay-examples issue-tracker(https://github.com/relayjs/relay-examples/tree/master/issue-tracker/src/routing) and when transitioning from routes, startTransition works fine. However, on one page I am using React.useLayoutEffect and when I am transitioning away from that page. startTransition skips the timeout and immediately goes to the next page. Changing the useLayoutEffect to useEffect fixes this problem.

**What is the expected behavior?**
I would expect useLayoutEffect to work the same as useEffect

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Google chrome 78, max osx, react experimental

**Comment by gaearon** [comment]
Likely same issue as https://github.com/facebook/react/issues/17911#issuecomment-590962580.
