### ISSUE TITLE
[Question] Best Practices to uncontrolled component

### ISSUE THREAD

**Issue by garygao12580** [facebook/react#17374]
I have some doubts. When I am writing components with React, I didn't know if this was reasonable.
The following is my case.

I want to write a form component that internally uses `State`  to store the current values, and has some validation methods. It doesn't need to be coupled or linked to the outside, but only returns the current result when I need to get the values.

The above functions can be achieved using both controlled and uncontrolled components.
I can implement a controlled component by using Props to specify the current value and pass the 
function of updating the value.
Another method is to implement getValue function inside the component. When externally needed, use ref to call the getValue function of the component to implement uncontrolled components.

I think the second method is what I want.
The first method requires external components to control the state inside the component, which I think will destroy the cohesion of the component. For the caller, I don't care what the internal implementation of the component is. I just want to get the current state by  some interfaces when I need it, and if the component has any internal updates it won't affect the external call. I think such a component is perfect.

I can use `ref`  to implement this design, but using `hooks`  can't call methods inside the component via ref.

So, can't hooks be used like this?
Or is there a better design and best practices?

As the picture shows

![image](https://user-images.githubusercontent.com/24784430/68933687-28f5a280-07d0-11ea-8485-d26d4bb01592.png)

**Comment by kunukn** [comment]
If you asked in https://stackoverflow.com/questions/tagged/reactjs 
then you would probably get more and faster answers

**Comment by garygao12580** [comment]
> If you asked in https://stackoverflow.com/questions/tagged/reactjs?tab=Newest
> then you would probably get more and faster answers

thx, I got it.

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
