### ISSUE TITLE
`npm install` failing

### ISSUE THREAD

**Issue by panth0r** [facebook/react#17377]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
npm ERR! code ETARGET
npm ERR! notarget No matching version found for scheduler@^0.18.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'react-dom'
npm ERR! notarget 

**What is the expected behavior?**
`npm install` not failing

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
See above.

**Comment by loick-michard** [comment]
Sounds like an issue with the npm proxy, see `[](https://github.com/facebook/react/issues/13693)`.

**Comment by JohnSeals** [comment]
Happened to me again just now. The notes mentioned by @loick-michard worked for me. I just installed a specific veresion of react, in my case 16.6.3, and everything is fine:

npm install --save-exact react@16.6.3
npm install --save-exact react-dom@16.6.3

**Comment by threepointone** [comment]
Definitely looks like an issue with npm. Thank for the workarounds!
