### ISSUE TITLE
Error: "Cannot read property 'toFixed' of null"

### ISSUE THREAD

**Issue by zachbharris** [facebook/react#17387]
Describe what you were doing when the bug occurred:
1. Open dev tools and go to components extension
2. Start searching for a component `ImageControl`
3. As soon as I get close to said components name, around `ImageC` this error is thrown. I'm thinking this might have something to do with our own local components, but not 100% sure. Figured I would report this just in case it isn't only affecting me.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.0-a8b8ffb89

Call stack: at Qa (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:278839)
    at Ka (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:278585)
    at fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59263)
    at lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103717)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89467)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89392)
    at pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86341)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45721
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:3691)
    at Qo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45431)

Component stack: in Ka
    in ri
    in ti
    in div
    in si
    in div
    in li
    in Suspense
    in Wa
    in div
    in div
    in Jo
    in Xr
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by threepointone** [comment]
What is ImageControl and ImageC? Could you share some code?

**Comment by zachbharris** [comment]
`ImageControl` and `ImageC` are the same thing, a React class component, just `ImageC` is what I was typing into react dev tools before dev tools would throw the error above. I'm not quite sure I can share the components themselves since the code base is private

**Comment by bvaughn** [comment]
@zachbharris Can you still reproduce this error with the latest release of DevTools (4.4)?

If not, let's close this issue. If so, we'll need you to share a repro case with us somehow. (It's okay if you can't share the entire codebase. Maybe you could just create a Code Sandbox that demonstrates the behavior.)

**Comment by zachbharris** [comment]
@bvaughn I'm not quite sure how to reproduce it, and it hasn't happened since November, so I'm pretty sure this issue could have been moreso (if not solely) on my react components somehow throwing the devtools off. If you would like to close this, go ahead. If I figure out how to reproduce it, I'll throw it in here.

**Comment by bvaughn** [comment]
Sounds reasonable! :smile: Let's re-open if you see it again and we'll go from there. Thanks for the update!
