### ISSUE TITLE
Devtools resize Component State/Props pane

### ISSUE THREAD

**Issue by codercodingthecode** [facebook/react#17389]
**Do you want to request a *feature* or report a *bug*?**
I would like to request a feature

**What is the current behavior?**
Resizing the state/props pane in Component Tab

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Allow resizing pane

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Devtools 4.2.0 and Chrome Version 78.0.3904.97 

![image](https://user-images.githubusercontent.com/20182536/69003149-de088780-08c2-11ea-9f32-391faee6a557.png)

**Comment by codercodingthecode** [comment]
I'd like to open a pr for this

**Comment by bvaughn** [comment]
I'd be happy to review a PR for this.

**Comment by hristo-kanchev** [comment]
Hey @bvaughn !

Are we still looking at adding this feature?

Maybe we can have a checkbox in Settings -> General that will allows the user to dock the Component State/Props/.. to the bottom instead of supporting resizing for that pane?

What do you think?

**Comment by bvaughn** [comment]
Resizability, yes. Would still be open to adding that behavior in.

A checkbox to force a bottom docking position- not really a fan of that.

**Comment by hristo-kanchev** [comment]
Cool @bvaughn. I'll try and open a PR by the end of this week. I'll ping you again when it's done.

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by hristo-kanchev** [comment]
****Progress** so far:**

![horizontal-resize](https://user-images.githubusercontent.com/23095052/74434192-2b64a880-4e62-11ea-826c-3eef2a4fc10c.gif)

I have a question though, @bvaughn.

Should we also support vertical resizing when we are in this mode?

<img width="500" alt="Screenshot 2020-02-13 at 13 09 27" src="https://user-images.githubusercontent.com/23095052/74434236-48997700-4e62-11ea-8616-93d80509a960.png">

Thoughts?

**Note**: The red horizontal line is for debugging purposes 😆

**Comment by bvaughn** [comment]
Seems like, ideally, resizing should work for both horizontal and vertical (and be remembered separately)

**Comment by hristo-kanchev** [comment]
Almost done! (I expect to open the PR this Saturday).

Here how it looks so far:

**Horizontal** Resize:

![horizontal-resize](https://user-images.githubusercontent.com/23095052/74515268-89e76080-4f0e-11ea-8b1b-4c2e2cf90322.gif)

**Vertical** Resize:

![vertical-resize](https://user-images.githubusercontent.com/23095052/74515373-bac79580-4f0e-11ea-96d5-fcfa2c7ffff4.gif)

**Comment by bvaughn** [comment]
Looking good!

**Comment by codercodingthecode** [comment]
This is awesome!!

**Comment by hristo-kanchev** [comment]
@bvaughn we can close this one 🎉
