### ISSUE TITLE
 [eslint-plugin-react-hooks] refine warning about accessing .current in cleanup effects

### ISSUE THREAD

**Issue by juangl** [facebook/react#17381]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

currently when you access `.current` in the cleanup effect you'll get a warning if ESLint didn't find an assignment to `.current`.

**What is the expected behavior?**

Ideally the linter can check if the `useRef` call sets an usable initial value.

```javascript
function MyComponent() {
  const refOne = React.useRef({});
  const refTwo = React.useRef(null);
  
  React.useEffect(() => {
    refOne.current.someProperty = true;
    return function cleanup() {
      refOne.current.somePropty; // this is cool
      refTwo.current.innerHTML; // this maybe not
    }
  }, []);
  return <div ref={refTwo} />;
}
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

current version in master

**Comment by loick-michard** [comment]
You can ignore the warning in your specific case. As `useRef` often references Dom Element / Component, they could change during the cleanup. 

I don't have a full example of your code, but is `useRef` really needed ?

**Comment by juangl** [comment]
@loick-michard thank you for responding.

I may not have been clear enough. To be honest I don't fully understand the warning. As you stated `As useRef often references Dom Element / Component, they could change during the cleanup.`, that doesn't really show me what's going on, what does it actually change from the effect to the cleanup and why? Considering that the cleanup runs *before* the component gets removed from the UI.

Anyways that's not the actual point for my issue, I don't mean the warning is not useful but that it could get smarter. My example is not a real-world case. It's just an object with one single property. It's easy to refactor using a simpler ref. You can have and object with more properties where otherwise you have to manage each property with an individual ref.
