### ISSUE TITLE
Feature Request: being able to invoke statements on jsx events

### ISSUE THREAD

**Issue by arnotes** [facebook/react#17397]
Its 2019 and react still doesnt have the ability to invoke statements via events
angular:
`(click)="doSomething(param1, param2)"`
vue:
`v-on:click=doSomething(param1, param2)"`
NATIVE HTML
`onclick="doSomething(param1, param2)"`

and then we have react
```
onClick={()=>doSomething(param1, param2)}//which is not recommended by majority since this will create a new function every render
onClick={someCallBackHereThatCallsdoSomethingInside}
```

it would be nice for react to support syntatic sugars like
```
(onClick)={doSomething(param1, param2)}
^onClick={doSomething(param1, param2)}
event.OnClick={doSomething(param1, param2)}
```
or anything as long as it works

**Comment by threepointone** [comment]
>  // which is not recommended by majority since this will create a new function every render

This is not true. Feel free to do so, it's as cheap as making an object.
