### ISSUE TITLE
setState callback in componentWillMount?

### ISSUE THREAD

**Issue by matthewwithanm** [facebook/react#1740]
Calling `setState` in `componentWillMount` doesn't behave as I would expect. [Here][1]'s a fiddle demonstrating. In short, the callback is invoked before the state has been updated.

[1]: http://jsfiddle.net/kb3gN/3194/

**Comment by fredkelly** [comment]
Is there an interim solution to get the desired behaviour?

**Comment by bobiblazeski** [comment]
Any update on this 0.13.1 https://jsfiddle.net/28zsnwcb/

**Comment by ccorcos** [comment]
This is super annoying. I think this ought to work as well: http://jsfiddle.net/5L9u5oqz/1/

**Comment by jbpros** [comment]
Running into this problem as well.

**Comment by ccorcos** [comment]
Now I'm getting an issue where the callback isnt being called at all. Oy vey

http://codepen.io/ccorcos/pen/QbxaMg

**Comment by ccorcos** [comment]
@matthewwithanm Here's your same JSFiddle with an updated version of React and the callback never gets called! WTF!

http://jsfiddle.net/ccorcos/k5ws12c6/

**Comment by brigand** [comment]
If you need something for now, you can use this function to patch it.

```js
var Hello = React.createClass({
    getInitialState: function() { return {}; },
    componentWillMount: function() {
        hotfixSetState(this);
        this.setState({testing: '123'}, function() { ... });
    }
    // ...
});
 

function hotfixSetState(instance){
    var original = {
        componentWillMount: instance.componentWillMount,
        setState: instance.setState,
        componentDidMount: instance.componentDidMount
    };
    var traced = new Error();
    
    var callbacks = [];
    var isMounted = false;
    
    instance.setState = function(update){
        var callback = arguments[1];
        if (callback) {
            callbacks.push(callback);
        }
        
        // don't pass the callback
        original.setState.call(instance, update, function(){
            console.warn('you are using hotfixSetState, but the setState callback was called', traced, instance);
        });
    };
    
    instance.componentWillMount = function(){
        if (original.componentWillMount) {
            return original.componentWillMount.apply(this, arguments);
        }
    };
    
    instance.componentDidMount = function(){
        for (var i=0; i<callbacks.length; i++) {
            callbacks[i].call(undefined);
        }
        instance.setState = original.setState;
        
        if (original.componentDidMount) {
            return original.componentDidMount.apply(instance, arguments);
        }
    };
};
```

**Comment by ccorcos** [comment]
you da man!

**Comment by spicyj** [comment]
#4171 should have fixed this. The callback fires on the client but not the server.

**Comment by gaearon** [comment]
If it is fixed, is this comment outdated?
https://github.com/facebook/react/blob/1e8156143a6389e2235fa16536bb9161d26a23ce/src/renderers/shared/reconciler/ReactUpdateQueue.js#L140-L144

**Comment by LiuuY** [comment]
Recently I am reading the source code about batching, this comment really make me confused, until I find this issue, maybe you guys can delete it? I think it may be helpful for others.
https://github.com/facebook/react/blob/1e8156143a6389e2235fa16536bb9161d26a23ce/src/renderers/shared/reconciler/ReactUpdateQueue.js#L140-L144
