### ISSUE TITLE
ESLint exhaustive-deps rule should be more consistent about 'Ref' values

### ISSUE THREAD

**Issue by AlexReff** [facebook/react#17404]
**Do you want to request a *feature* or report a *bug*?**

*BUG* - or possibly a misunderstanding about `Ref`s and dependencies

**What is the current behavior?**

Edit: Sandbox here, my pseudo below wasn't exactly accurate: https://codesandbox.io/s/patient-shadow-eswc6

```
export const MyReactFunction = (props) => {
    ...
    const myRef= useRef(null);
    ...
    const myCallback = useCallback((args) => {
        //...
        if (myVal.current === 0) { .... }
        if (props.otherRef.current == null) { ... }
    }, []);
    ...
    myCallback(1);
}
```
Gives ESLint warning:
> React Hook useCallback has missing dependencies: 'myRef' and 'props.otherRef'. Either include them or remove the dependency array.eslint(react-hooks/exhaustive-deps)

**What is the expected behavior?**

Unless I am misunderstanding, there is no reason to include a `Ref` value in the dependency list. If I include a `Ref.current`, I get the message `Mutable values like 'myRef.current' aren't valid dependencies because mutating them doesn't re-render the component.`

Since passing in `myRef` as a dependency is meaningless, and passing in `myRef.current` also provides a warning, I would expect the exhaustive-deps warning to know to not care about `myRef` or any other `Ref` value in the scope in regards to missing dependencies.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

N/A

**Comment by juangl** [comment]
what `eslint-plugin-react-hooks` version is this? I don't see the same warning. Take a look at example: https://codesandbox.io/s/admiring-ardinghelli-4uolf

**Comment by AlexReff** [comment]
The link you provide does produce the error - look at the "Problems" tab on the bottom right.

**Comment by juangl** [comment]
@AlexReff it's not the same message,  your warning refers to `'myRef' and 'props.otherRef'` whereas in the reproducible example it refers only to `otherRef`.

**Comment by AlexReff** [comment]
You're absolutely right, here is a repo that shows the error: https://codesandbox.io/s/patient-shadow-eswc6

The issue being that I don't directly call useRef, I call it in a custom hook, and then the custom hook returns the value of the Ref. I would assume that the type being `===ReturnValue<useRef>` would cause this rule to still know not to require the variable, but apparently this is not the case.

**Comment by MHA15** [comment]
> The issue being that I don't directly call useRef, I call it in a custom hook, and then the custom hook returns the value of the Ref. I would assume that the type being `=== ReturnType<useRef>` would cause this rule to still know not to require the variable


I think that there should be a way to tell that this variable (or return type of my custom hook) is a ref object and is not necessary to put it in deps list

I think this should handle return type of React.createRef too
