### ISSUE TITLE
Why include refs as a feature? -- seems broken and unnecessary

### ISSUE THREAD

**Issue by petervijeh** [facebook/react#17408]
Refs never seem to work, is this a broken feature?

Why not remove them and just let people use 
document.querySelector('#id').action like normal people.

also, what does this mean? 

 Function components cannot have refs. Did you mean to use React.forwardRef()?

**Comment by TrySound** [comment]
What's broken with refs for you? Could you be more specific?
document.querySelector requires adding unique ids or classes which may affect isolation. Refs allow to avoid this.

**Comment by bpas247** [comment]
> Refs never seem to work, is this a broken feature?

It is not a "broken" feature. 
> Why not remove them and just let people use
document.querySelector('#id').action like normal people.

You can still completely use `document.querySelector` if you wanted to (although I have no idea why you would want to), nothing in React is preventing you from doing that.

>also, what does this mean?
> Function components cannot have refs. Did you mean to use React.forwardRef()?

Sounds like you're trying to use refs inside of a function component without the `useRef` hook. I'd encourage you to [read the docs](https://reactjs.org/docs/hooks-reference.html#useref) on how to use `useRef`.

**Comment by flaviendelangle** [comment]
If we focus on `ref` for DOM Nodes (excluding other `ref` use cases brought by the `useRef` hooks),
*ref* are a lot more flexible than regular `document.querySelector` code

1) You don't have to give your component a unique ID to be able to access it's DOM node (which would be a pain in some circumstances like highly reusable components, unless you use `useRef` to store a random identifier which would be ironic).

2) You can pass ref though components so a component `MyCustomTextArea` can allow it's parent to access the real `textarea` DOM node without losing the ability to set any custom HTML property.

3) You can easily trigger some custom logic on the ref initialization thanks to the `function ref` (which can be usefull for libraries not using react like `threejs`.

`Refs` are a way to handle easily the few `imperative` usecases that a declarative model can't handle properly. 
I highly recommend you to read the documentation of a given feature before asking if it's broken. :+1:

**Comment by bvaughn** [comment]
I'm going to close this issue because it's not really actionable, and it's already received a couple of helpful responses. 👍 

I'll add one more bit of missing context:

> Why not remove them and just let people use
> document.querySelector('#id').action like normal people.

The `querySelector` API only lets you access elements that have been added to the DOM already. Sometimes it can be useful to get a ref to a React component (e.g. a react-window list) to call methods on it.
