### ISSUE TITLE
How to use sync state changed in eventListener in useEffect?

### ISSUE THREAD

**Issue by cuongdevjs** [facebook/react#17417]
I have 3 event listeners is created when isMounted = true, in each event, i updated some variable (count, number). But every count or number change, event registered but console.log(count), count not change. Solution for this case. thanks

````
function demo() {
    const [count, setCount] = useState(0);
    const [isMounted, setIsMounted] = useState(false);
    const [number, setNumber] = useState(0);

    useEffect(() => {
        setIsMounted(true);
       return () => setIsMounted(false);
    }, []);

    useEffect(() => {
        document.addEventListener("touchmove", () => { console.log(count); setNumber(1); });
        document.addEventListener("touchstart", () => { console.log(count); setCount(2) });
        document.addEventListener("touchend", () => { console.log(count); setNumber(2); });
    }, [isMounted, count, number]);
}
````

**Comment by bpas247** [comment]
Most likely `count` is stale when you log it inside of the event listener, even if it's the touchstart event that's fired (you're also logging it *before* you update `count`, so even if state updates were sync it would still log a stale value).

Just log `count` in the body of the function if you want it to log the newest value for it after a re-render.

**Comment by CuongStf** [comment]
but i need value of count inside function? Have any way to do that?

**Comment by bpas247** [comment]
> but i need newest value of count inside function? Have any way to do that?

Which function? Also, what are you using the value of `count` for?

**Comment by CuongStf** [comment]
> > but i need newest value of count inside function? Have any way to do that?
> 
> Which function? Also, what are you using the value of `count` for?

yeah, it's demo example. But if my handler function in event listener need use newest value count, although i added count to argument [count], but it's not working

**Comment by dai-shi** [comment]
If the purpose of this is learning, I'd suggest to follow the recommended useEffect usage: Always clean up.
```js
useEffect(() => {
  const listener = document.addEventListener("touchmove", () => { console.log(count); setNumber(1); });
  const cleanup = () => {
    document.removeEventListner("touchmove", listener);
  };
  return cleanup;
}, [isMounted, count, number]);
```

**Comment by CuongStf** [comment]
> If the purpose of this is learning, I'd suggest to follow the recommended useEffect usage: Always clean up.
> 
> ```js
> useEffect(() => {
>   const listener = document.addEventListener("touchmove", () => { console.log(count); setNumber(1); });
>   const cleanup = () => {
>     document.removeEventListner("touchmove", listener);
>   };
>   return cleanup;
> }, [isMounted, count, number]);
> ```

Thanks, but it's example simple. But my reality case, i need use variable (updated) in handler function (event). As above example, if i clean listener, variable count in handler function has been update yet?

**Comment by dai-shi** [comment]
> As above example, if i clean listener, variable count in handler function has been update yet?

It will show the updated count, because a new listener will be added.

In reality, I'd use `useRef` to fill this mismatch of programming model.
There's a detailed [overreacted blog post](https://overreacted.io/making-setinterval-declarative-with-react-hooks/). (It's too detailed. I wonder if there's an example in the official doc?)
