### ISSUE TITLE
SuspenseList gotcha with React.lazy

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#17413]
**Do you want to request a *feature* or report a *bug*?**

Suspense is still experimental, so it's neither 🙃

**What is the current behavior?**

It's best described via a code example in this codesandbox: https://codesandbox.io/s/react-suspenselist-problem-8g7c1

Here's a summary:

When "forwards" is used for the `revealOrder` of a SuspenseList, React does not even try to render components in suspense boundaries after the most "forward" suspense boundary. This should be fine, but it can be a problem when used with React.lazy because the dynamic import isn't started until the lazy component is rendered so adding a SuspenseList to an existing set of lazily loaded components results in a slower overall loading experience thanks to a waterfall effect.

For completeness I'll just add that this same thing applies to "backwards" as an option as well.

I understand why SuspenseList doesn't bother rendering components in Suspense Boundaries until they're ready to be shown. It's because we should be firing requests for things before we try to render the components that need those resources. However, React.lazy is a bit of a special case because it doesn't suspend until it's rendered the first time and for the developer to fire that request eagerly requires extra work on the part of the developer (there's a comment in the code showing the workaround).

**What is the expected behavior?**

Because React.lazy is a special case and people are likely to run into this gotcha a lot when implementing Suspense Lists around lazy components, I think something should be done for these to start loading the module eagerly without workarounds. I'm not sure what to suggest to do about it though.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Version `0.0.0-experimental-b53ea6ca0` and I don't think this ever worked in a previous version.

**Comment by JacobMGEvans** [comment]
I think you mean "aren't likely" (sorry to be pedantic) 😅
> Because React.lazy is a special case and people are likely to run into this gotcha a lot

**Comment by kentcdodds** [comment]
Yes, I expect that people will run into this situation often.

**Comment by kentcdodds** [comment]
I've developed another workaround that I think is not terrible: https://codesandbox.io/s/react-suspenselist-problem-u4f4o

The gist is this adjustment that we'd need to make that `React.lazy` to add a `preload` function:

```javascript
function preloadableLazy(dynamicImport) {
  let promise
  function load() {
    if (!promise) {
      promise = dynamicImport()
    }
    return promise
  }
  const Comp = React.lazy(load)
  Comp.preload = load
  return Comp
}

const LazyLoadedComponent = preloadableLazy(() => import('./lazy-loaded-component'))

// then, in an event handler or something, you could simply call:
LazyLoadedComponent.preload()
```

Seems ok to me. To be clear, what I'm suggesting is that if this were built-in, it would be a feature of `React.lazy` rather than an extra function.

**Comment by rhagigi** [comment]
@kentcdodds  - From what I can tell this is similar to the "fetch on render" pattern described in the suspense docs -- you can think of React.lazy with a dynamic import as kicking off a fetch (for the code) on render. I believe this is the reason the team has tried to paint Suspense not as "the thing that triggers the fetch" but "the thing that *awaits* the fetch". Agree on the fact that if LazyLoadedComponent.preload() existed that would make this easier -- but considering that React.lazy itself just wraps any promise for a component, I feel like you could implement the same thing in userland.

**Comment by kentcdodds** [comment]
> I feel like you could implement the same thing in userland

Indeed. That's exactly what the `preloadableLazy` function is 😉

**Comment by kentcdodds** [comment]
It appears that the latest experimental release (`0.0.0-experimental-e5d06e34b`) no longer suffers from this problem. Can I get a confirmation of this please? cc @sebmarkbage

**Comment by gaearon** [comment]
I don't think we intentionally changed anything there..

**Comment by kentcdodds** [comment]
I'm guessing it was an unintentional change then.

To be clear, here's the before: https://codesandbox.io/s/react-suspenselist-problem-8g7c1

![before](https://user-images.githubusercontent.com/1500684/79670691-2550b800-8182-11ea-9672-10a11cacb863.gif)

And here's the after: https://codesandbox.io/s/react-suspenselist-problem-l6jqf

![after](https://user-images.githubusercontent.com/1500684/79670694-28e43f00-8182-11ea-872a-2397584fc8d7.gif)

Curious whether this is a bug or feature 😅

**Comment by sebmarkbage** [comment]
The change is that lazy component triggers load earlier now. During reconciliation. This only works if it’s the very next child. If you add a wrapper around the lazy load it won’t work anymore.

**Comment by kentcdodds** [comment]
Thanks. That feels confusing/unexpected (similar to #17425). Also, I couldn't reproduce the wrapping behavior difference. Could you clarify?

**Comment by kentcdodds** [comment]
And by "confusing/unexpected" I'm referring to this behavior:

> If you add a wrapper around the lazy load it won’t work anymore.

**Comment by eps1lon** [comment]
> Also, I couldn't reproduce the wrapping behavior difference. Could you clarify?

```jsx
const AnotherLazyLoadedComponent = React.lazy(loadLazyLoadedComponent)
function WrappedLazyLoadedComponent() {
  return <AnotherLazyLoadedComponent />
}
```

causes

![wrapped-lazy](https://user-images.githubusercontent.com/12292047/79685958-dddb3200-823c-11ea-966f-f4c7912225d9.gif)


-- https://codesandbox.io/s/react-suspenselist-problem-7nof7?file=/src/index.js

**Comment by kentcdodds** [comment]
Ah, I was trying:

```javascript
<Wrapper>
  <SuspendingComponent />
</Wrapper>
```

That helps me understand what's happening. Still think it's surprising/confusion. Sounds like an implementation detail limitation 😬

**Comment by sebmarkbage** [comment]
Note that there’s no semantic bug here. It’s just that the loading heuristics. The end result is still the same.

We might consider prerendering at lower priority but if busy that might still take a while. The use case we have is more related to images. It’s harder to prefetch them because you might not end up using every combination. But I’m pretty skeptical of that too.

Even without this you can have lazy loading take a while just because it takes time to render into it. You can also have waterfalls when one lazy loads another. All this is suboptimal anyway. One solution is to server render and use that to hint what to preload like react-loadable does which solves this.

We’re working on other alternative approaches too. But this is kind of the issue with lazy.

**Comment by gaearon** [comment]
I guess another way to phrase it is that

- We don't think `lazy` is a very good solution for lazy loading. Because you start loading too late. If you have nested `lazy` then everything becomes really slow.
- There are solutions that can avoid these problems. However, they involve some kind of a prepass. We're working on a potential idiomatic solution to this which would both offer a suggested Suspense for Data Fetching path *and* replace the use cases for lazy. But it's in a very early stage atm.

**Comment by kentcdodds** [comment]
Makes sense 👍 is this what `React.block` is all about? A mechanism to load code and data together?

**Comment by gaearon** [comment]
Yeah.

**Comment by gaearon** [comment]
`SuspenseList` doesn't have this problem with Server Components because they begin preloading as early as possible. I think that's the resolution here. We'll document that `lazy` is not really recommended to use here — and in fact, in general it's not a great solution because it leads to waterfalls. Such as starting to load code too late.

**Comment by kentcdodds** [comment]
> Such as starting to load code too late.

Not if my suggested `preload` function were built-in 😉 But sure, server components kinda change the game here entirely anyway.

**Comment by gaearon** [comment]
I don't know that `preload` is needed here if you can `import(...)` the thing directly when needed to kick it off. Isn't that the same?

**Comment by kentcdodds** [comment]
Sure, you could totally do that if you want. But depending on the situation you may not know the path to the component you've got. Maybe it was passed to you via props. I have a situation like this is code I'm running now :)
