### ISSUE TITLE
Firefox (Developer Edition) React DevTools fails to show state when using useState hook

### ISSUE THREAD

**Issue by robjac** [facebook/react#17410]
in Chrome, when inspecting a component with useState hooks, one can view the current state key/values in the wrappedComponent object of the hooks section of Components React Devtools, inside of Unmount.

When inspecting the same component in Firefox, all i see is wrappedComponent -> Unmount -> wrappedHook -> Effect. 

Can someone clarify why?

Screenshots upon request! 

Thanks!

**Comment by bvaughn** [comment]
Hooks work fine in Firefox DevTools for me, including developer edition. Tested on a small Code Sandbox: https://1tjyp.csb.app/

If you can repro this behavior, please re-open with repro instructions :)

**Comment by robjac** [comment]
Well that was rather quick. Repro instructions and screenshots _upon request_. I did not include them as a number of the objects has sensitive information.

I will open a new issue with details regarding the stack (react+mobx)

**Comment by bvaughn** [comment]
> I will open a new issue with details regarding the stack (react+mobx)

Please just provide them here.

I closed the issue because it did not seem correct, as described. If you provide a repro case, as mentioned above, we can _re-open this issue_.

**Comment by robjac** [comment]
I'll just open a new one -- no time at the moment. Is there a better place
to drop questions to the general community and discuss things?

I'd like to find out if anyone else has issues with firefox developer
edition reading useState hooks as state ( with or without mobx ).
Currently, what I'm seeing is what I've detailed in the first post.

**Comment by bvaughn** [comment]
It's valuable to preserve context on an issue. Opening new issues just strings things out. Please, just provide the details on this issue and we'll re-open it.

**Comment by robjac** [comment]
I understand - 

here is a screenshot ( top is Firefox Developer Edition, and bottom is Chrome )

![Screen Shot 2019-12-03 at 10 50 12 AM](https://user-images.githubusercontent.com/1988220/70066594-f4992900-15ba-11ea-8059-9a08ea2cfccf.png)

The Performance component in Chrome allows me to see State. In Firefox it does not. 

package.json: 
```
{
  "author": "Sigstr <product@sigstr.com>",
  "dependencies": {
    "@babel/polyfill": "7.4.4",
    "@emotion/core": "10.0.21",
    "@emotion/styled": "10.0.17",
    "@honeybadger-io/react": "0.0.4",
    "@types/googlemaps": "3.37.6",
    "@types/markerclustererplus": "2.1.33",
    "@types/react": "16.9.9",
    "axios": "0.19.0",
    "bulma": "0.7.5",
    "bulma-checkradio": "2.1.0",
    "classnames": "2.2.6",
    "color": "3.1.2",
    "copy-to-clipboard": "3.2.0",
    "dayjs": "1.8.16",
    "debounce-promise": "3.1.2",
    "dotenv-webpack": "1.7.0",
    "final-form": "4.18.5",
    "history": "4.9.0",
    "honeybadger-js": "2.0.0",
    "js-file-download": "0.4.8",
    "latlon-geohash": "1.1.0",
    "lodash": "4.17.15",
    "mixpanel-browser": "2.18.0",
    "mobx": "5.13.0",
    "mobx-react": "6.1.3",
    "numeral": "2.0.6",
    "papaparse": "5.1.0",
    "pluralize": "8.0.0",
    "prop-types": "15.7.2",
    "query-string": "6.8.3",
    "rc-drawer": "2.0.9",
    "react": "16.9.0",
    "react-datepicker": "2.9.6",
    "react-dom": "16.9.0",
    "react-dropzone": "10.1.10",
    "react-final-form": "6.3.0",
    "react-google-maps": "9.4.5",
    "react-helmet": "5.2.1",
    "react-hot-loader": "4.12.15",
    "react-image": "2.2.1",
    "react-notification-system": "0.2.17",
    "react-placeholder": "3.0.2",
    "react-router-dom": "5.0.1",
    "react-simple-maps": "0.12.1",
    "reactjs-popup": "1.4.2",
    "victory": "32.3.6"
  },
  "description": "Sigstr Relationship Intelligence app",
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/plugin-proposal-decorators": "7.4.4",
    "@babel/plugin-proposal-object-rest-spread": "7.5.5",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/preset-env": "7.5.5",
    "@babel/preset-react": "7.0.0",
    "@emotion/babel-preset-css-prop": "10.0.17",
    "@honeybadger-io/webpack": "1.1.4",
    "@logux/eslint-config": "31.0.2",
    "@testing-library/jest-dom": "4.1.2",
    "@testing-library/react": "9.1.4",
    "autoprefixer": "9.6.5",
    "axios-mock-adapter": "1.17.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.3",
    "babel-jest": "24.9.0",
    "babel-loader": "8.0.6",
    "babel-plugin-transform-class-properties": "6.24.1",
    "clean-webpack-plugin": "3.0.0",
    "css-loader": "3.2.0",
    "eslint": "6.3.0",
    "eslint-config-airbnb": "18.0.1",
    "eslint-config-postcss": "3.0.7",
    "eslint-config-prettier": "6.2.0",
    "eslint-config-standard": "14.1.0",
    "eslint-import-resolver-webpack": "0.11.1",
    "eslint-plugin-babel": "5.3.0",
    "eslint-plugin-es5": "1.4.1",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-import-helpers": "1.0.2",
    "eslint-plugin-jest": "22.17.0",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-node": "10.0.0",
    "eslint-plugin-prefer-let": "1.0.1",
    "eslint-plugin-prettier": "3.1.1",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-react": "7.14.3",
    "eslint-plugin-react-hooks": "2.0.1",
    "eslint-plugin-security": "1.4.0",
    "eslint-plugin-standard": "4.0.1",
    "file-loader": "4.2.0",
    "git-revision-webpack-plugin": "3.0.4",
    "html-webpack-plugin": "3.2.0",
    "husky": "3.0.9",
    "identity-obj-proxy": "3.0.0",
    "jest": "24.9.0",
    "jest-emotion": "10.0.17",
    "jest-haste-map": "24.9.0",
    "jest-localstorage-mock": "2.4.0",
    "jest-resolve": "24.9.0",
    "mini-css-extract-plugin": "0.8.0",
    "mockdate": "2.0.5",
    "node-sass": "4.12.0",
    "optimize-css-assets-webpack-plugin": "5.0.3",
    "postcss-loader": "3.0.0",
    "prettier": "1.18.2",
    "react-test-renderer": "16.9.0",
    "sass-loader": "7.2.0",
    "style-loader": "1.0.0",
    "terser-webpack-plugin": "1.4.1",
    "webpack": "4.39.3",
    "webpack-cli": "3.3.9",
    "webpack-dev-server": "3.8.2",
    "webpack-merge": "4.2.2"
  },
  "engines": {
    "node": "10.13.0",
    "yarn": "1.19.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "git diff --diff-filter=d --cached --name-only | grep '.js$' | xargs ./node_modules/.bin/eslint",
      "pre-push": "yarn test"
    }
  },
  "jest": {
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "moduleNameMapper": {
      "\\.(css|less|scss)$": "identity-obj-proxy",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js"
    },
    "setupFiles": [
      "jest-localstorage-mock"
    ],
    "setupFilesAfterEnv": [
      "./rtl.setup.js"
    ]
  },
  "license": "MIT",
  "main": "src/index.js",
  "name": "connect-ui",
  "private": true,
  "repository": "git@bitbucket.org:sigstr/connect-ui.git",
  "scripts": {
    "build": "NODE_ENV=production webpack --config webpack.prod.js --optimize-minimize",
    "start": "webpack-dev-server --config webpack.dev.js",
    "test": "jest --silent"
  },
  "version": "1.0.0"
}
```

**Comment by bvaughn** [comment]
> Let me know if there's anything else I can provide.

You could share the actual code for the project, in a repro (Code Sandbox or a GitHub repo I could checkout and run locally). At a glance, it looks like it could even be a minification + source maps issue to be honest.

The `package.json` isn't enough info.

**Comment by robjac** [comment]
This component is rather embedded, and relies on a heavy dataset to populate the mobx store it pulls from.

If and when I have time I’ll see if I can soon up a codesandbox. Like I said, this is a private repo, I can’t share the repo to run as it relies on a distributed system.

Minification/source map issues seems likely to me too. Would the wepack config be helpful in the meantime?

**Comment by bvaughn** [comment]
Hm. I think if the Webpack config was the cause, you should probably be able to reproduce with a smaller/simpler project.

**Comment by robjac** [comment]
I'll give it a shot when I have time. And I'll update you here. Thank you
for your time and attention.

**Comment by robjac** [comment]
Nothing changed -- but State keys started appearing for me in FFDeveloperEdition.

I'll follow the ongoing Github Issue regarding Named State hooks.
