### ISSUE TITLE
renderer.toTree missing state information with hooks

### ISSUE THREAD

**Issue by decodejacques** [facebook/react#17415]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I'm using react-test-renderer. renderer.toTree() is not providing me with the state information of functional components that use the useState hook. I know the state information is available because renderer.root._fiber has a memoizedState property with the state data I need. Someone just needs to take the data from _fiber and put it in the render tree.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

const React = require('react')
const ReactTestRenderer = require('react-test-renderer')
function OneButton() {
    let [counter, setCounter] = useState(42)
    return React.createElement("div", {}, counter)
}
let renderer = ReactTestRenderer.create(React.createElement(OneButton))
console.log(renderer.toTree()) // No state information

**What is the expected behavior?**

I should see the state with a value of 42 somewhere in the standard output

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.12.0

**Comment by milesj** [comment]
@decodejacques State is an implementation detail, you shouldn't need to access it. What are you trying to do?

**Comment by decodejacques** [comment]
I'm creating a react virtual DOM simulator as a teaching tool. I really
need the state information and I'm currently getting it from the _fiber
property. Why is state considered an implementation detail for functional
components but not for class components?

**Comment by milesj** [comment]
@decodejacques It's for both. In a perfect world, you wouldn't test/assert against state as it's an implementation detail and a bit of a code smell. Instead, you would assert against the result of the state change, like differences in the render tree.

Your use case is a little different than testing, so it's not so much of a code smell.

**Comment by decodejacques** [comment]
@milesj I can access the state of an instance of a class based component using the instance property of the tree, so the state is available for class based components but not for functional components. The state implementation detail is hidden for one but not the other. 

Based on my research, react-test-renderer seems to be the only way I can generate the virtual DOM with props and state like I would see in react devtools. All that is missing is the state for functional components.
