### ISSUE TITLE
How does react browser extension detect if the page is running on react.js?

### ISSUE THREAD

**Issue by parrotcar00** [facebook/react#17416]
I tried to search but couldn't find a definitive answer to how does the react browser extension detect whether a page is using react.js or not?

Is the react dev tool searching the javascript in the page for react.js function identifiers? If so, how does it work when a page is being served minified, because I thought minification changes function names etc. to something minified. Is the react dev tool comparing the Javascript AST with react.js standard AST?

Just curious to learn how do the dev tools work to detect react.js?

**Comment by eliseumds** [comment]
From the README:

> The React tab won't show up if the site doesn't use React, or if React can't communicate with the devtools. When the page loads, the devtools sets a global named __REACT_DEVTOOLS_GLOBAL_HOOK__, then React communicates with that hook during initialization. You can test this on the React website or by inspecting Facebook.

https://github.com/facebook/react/tree/master/packages/react-devtools
