### ISSUE TITLE
Passing in prop equality fn to React.memo can reset state from Hooks during updates 

### ISSUE THREAD

**Issue by eshifrin** [facebook/react#17426]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Passing in a function as the second argument to React.memo can cause state initialized in hooks to reset to previous state.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/romantic-wilson-34sup

**What is the expected behavior?**
Alternating row clicks should preserve the previous state associated with each row. 

Remove the areEqual function as the 2nd parameter to React.memo and the app behaves as expected.  Another fix is passing in a function to setState ```prevState => ... ```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.6, Chrome; no

**Comment by vkurchatkin** [comment]
Well, you've implemented comparator incorrectly, so this is expected. Your component is not rendered when `increment` is changed, hence this behaviour.

**Comment by eshifrin** [comment]
Wouldn't the reference to `increment` change for every row on every render... making the use of `memo` ineffective?  What's the correct implementation of the comparator here?

**Comment by vkurchatkin** [comment]
A correct implementation should _at least_ perform a shallow equality check for all props. In your case you don't need a comparator at all, you need to make your `increment` function stable. That is usually performed by `useCallback`:

```js
const increment = useCallback(function increment(key) {
    const nextState = [...state];
    nextState[key]++;
    setState(nextState);
  }, [state]);
```

Unfortunately, this won't really do any good, since it closes over `state` and will be update on each `state` change anyway. The best way to avoid it is use indeed to pass a function to `setState`:

```js
const increment = useCallback(function increment(key) {
    setState(state => {
        const nextState = [...state];
        nextState[key]++;
        return nextState;
    });
  }, []);
```

This way you can drop `state` from the dependencies. You can implement the same concept with `useReducer` as well. Another trick is to use `useRef` (although I wouldn't recommend it):

```js
  const incrementRef = React.useRef();
  incrementRef.current = (key) => {
    const nextState = [...state];
    nextState[key]++;
    setState(nextState);
  }


  const increment = React.useCallback(function increment(key) {
    incrementRef.current(key);
  }, []);
```

**Comment by eshifrin** [comment]
Ok thanks that provides some workarounds.  I'm going to close this out but for clarity, pls confirm:

the issue here was that the `increment` function referenced `state` from a closure; when `increment` was executed, it created a new instance of `state` by calling `setState` - and therefore a new instance of the `increment` function.  since not every row would get an updated `increment` reference (by virtue of the comparator), when that row was clicked, it would "start" with an older `state`.
