### ISSUE TITLE
React.createRoot(container).render(<App />) doesn't remove existing container children

### ISSUE THREAD

**Issue by martinandert** [facebook/react#17420]
**Do you want to request a *feature* or report a *bug*?**

I guess it's a bug.

**What is the current behavior?**

When using `ReactDom.createRoot(container).render(<App />)`, if the container has child elements, then these don't get removed when the App component is rendered into the container.

**CodeSandbox example**

https://codesandbox.io/s/recursing-euler-b3oj7

**What is the expected behavior?**

I expect it to behave like `ReactDom.render(<App />, container)`, which clears the contents of the container when the App component is rendered into it.

**Which versions of React?**

Latest experimental, see CodeSandbox example.

**Comment by gaearon** [comment]
Yeah. I don’t think we made a decision on this yet. One interesting case you can use this for is having a shim before the script loads. In CM the commit may be delayed even after you create root. In that case it seems to make sense to not remove the existing content until after first commit. But at that point it should probably have been cleared.

**Comment by martinandert** [comment]
Just wanted to add that I'm currently doing the following to clear the container:

```js
ReactDOM.createRoot(container).render(
  <RendersMainTag />,
  () => {
    for (const child of Array.from(container.children)) {
      if (child.tagName !== "main") {
        container.removeChild(child);
      }
    }
  },
);
```

**Comment by gaearon** [comment]
This has been fixed in master.
