### ISSUE TITLE
Rejecting suspended promise does not automatically go to an error boundary

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#17435]
**Do you want to request a *feature* or report a *bug*?**

If [what @gaearon said is true](https://twitter.com/dan_abramov/status/1197853310470021120), then it's a bug of unstable software.

**What is the current behavior?**

If a suspending promise rejects, it does not automatically trigger an error boundary and instead it suspends forever: https://codesandbox.io/s/suspenselist-issues-u9brv

![image](https://user-images.githubusercontent.com/1500684/69435887-9daf6c00-0cfd-11ea-89b3-86d5368155f5.png)

Here's the gist of the code:

```javascript
let promise = new Promise((resolve, reject) =>
  setTimeout(() => reject(new Error('failed')), 1000),
)
function SuspendingComponent() {
  throw promise
}

// ...

function App() {
  return (
    <div>
      <ErrorBoundary>
        <Suspense fallback="loading...">
          <SuspendingComponent />
        </Suspense>
      </ErrorBoundary>
    </div>
  )
}
```

**What is the expected behavior?**

Based on Dan's tweet, I would expect that when the promise rejects, the error boundary would be rendered, but it's not.

There's a simple workaround: https://codesandbox.io/s/suspenselist-issues-fxven

I'm having trouble with that showing the actual error on codesandbox, but here's what it looks like locally:

![image](https://user-images.githubusercontent.com/1500684/69435832-87091500-0cfd-11ea-8012-0010c3ee2c38.png)

The gist of the changes:

```javascript
let status = 'pending'
let result
let promise = new Promise((resolve, reject) =>
  setTimeout(() => reject(new Error('failed')), 1000),
).then(
  r => {
    result = r
    status = 'success'
  },
  e => {
    result = e
    status = 'error'
  },
)

function SuspendingComponent() {
  if (status === 'pending') throw promise
  if (status === 'error') throw result
  return result
}
```

The workaround is basically to store the error and throw it during the render phase. I was under the impression this was the official suggestion based on the `wrapPromise` example in the `fakeApi.js` of the codesandboxes linked in [the docs](https://reactjs.org/docs/concurrent-mode-suspense.html#start-fetching-early).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`react@0.0.0-experimental-b53ea6ca0` and `react-dom@0.0.0-experimental-b53ea6ca0`

**Comment by eps1lon** [comment]
The example in the docs uses the same workaround you described (throwing the rejection reason i.e. the error and not a promise that rejects). 

I think you misunderstood dan's statement. The suspending promise isn't really the one you manually threw. Instead you need a wrapper around it that throws the promise, returns the resolved value and throws the rejection.

**Comment by kentcdodds** [comment]
Right, I know the example in the docs uses the same workaround I described, that's what I said :)

I'm fine with either way. I just want to make sure I know what is intended. Perhaps I did misunderstand Dan's tweet (or he misunderstood mine). :)

**Comment by kentcdodds** [comment]
Still curious to hear thoughts from the team on this

**Comment by gaearon** [comment]
Yeah I think this is an intentional decision (which I forgot about). We only use Promise as a signal to retry. We don’t use the result, and therefore it makes sense that we don’t use the rejection reason either.

We’d likely want to change this API to something that’s less of a footgun before a stable release. Throwing promises was never intended to be a high level API. Although as we can see, even for people implementing the lower level these semantics can be confusing.

So it’s something to revisit, but probably as a part of a bigger change that replaces throwing Promises. Not in isolation.
