### ISSUE TITLE
[react-test-renderer] "Warning: Each child in a list should have a unique "key" prop."

### ISSUE THREAD

**Issue by incarnateTheGreat** [facebook/react#17431]
Hello!

**react-test-renderer** works just fine, but I'm getting the following Warning on all of my Tests:

> Warning: Each child in a list should have a unique "key" prop.

Has this been addressed? It isn't something related to my code or Tests.

Many thanks!

**Comment by KPowroznik** [comment]
In component, you use map for rendering list of components? If yes did you provide key property?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by incarnateTheGreat** [comment]
> In component, you use map for rendering list of components? If yes did you provide key property?
> 
> Sent with [GitHawk](http://githawk.com)

yes.

**Comment by bvaughn** [comment]
The warning is intentional. It indicates that you've got at least one component being rendered in an array that doesn't have a `key` prop.

If you think it's mistaken, then please provide a repro case we can look at :) Otherwise I assume this is working as designed.
