### ISSUE TITLE
Logging from a component

### ISSUE THREAD

**Issue by mixtur** [facebook/react#17433]
**Do you want to request a *feature* or report a *bug*?** Feature

There are two cases I want to be improved.

Case 1. Currently when you have to debug some component and you have multiple instances of it on the page, and you are trying to console.log something from there you'll get 10 messages in the console, and as component life time progresses and you are trying to console.log more stuff console output becomes total mess, which is hard to read. So you must manually limit that output to just one instance. Though if that output could be redirected to React dev tools, it could probably do this for me.

Case 2. When printing a warning from a component via console.warn, all I can get is js stack trace at best telling me which component did that. But I know that anyway. What I want to know is which other component rendered that component and ultimately the whole component stack trace. So it would be nice to either be able to print component stack trace at arbitrary time, not just when everything blows up, or have some warning icon/message attached to compnent that issued that warning in react dev tools.

**Comment by bvaughn** [comment]
Case 1: I suggest you pass a debug prop or something to only turn logging on for the specific "instance" of the component you want to log from in this case.

Case 2: If you're using React DevTools, it can add the "component stack" info you're looking for to any warnings/errors you log. Just make sure you've enabled this option:
https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#component-stacks

**Comment by mixtur** [comment]
Case 1 - I am not saying that it is impossible. It's just creates friction that could be avoided.
Case 2 - that is helpful thank you. It could still be better though if output was in react dev tools and filtered by component instance.
