### ISSUE TITLE
When using a state hook(useState), is it possible to change the state directly?

### ISSUE THREAD

**Issue by ShevRuslan** [facebook/react#17442]
When using a state hook, is it possible to change the state directly? Or as with the regular state in the class component?
As an example, changing an existing array (directly or copy a new one)

` this.setState(({ todos }) => {
            const newTodos = [
                ...todos,
                newItem
            ];
           return { todos: newTodos }
        })
`

Or using a state hook, I can just  `todos.push(newItem)` ?

**Comment by milesj** [comment]
No, you can't modify state directly, but you can append the previous state.

```ts
const [list, setList] = useState([]);

setList(prev => [...prev, item]);
```

**Comment by ShevRuslan** [comment]
Thanks
