### ISSUE TITLE
Shallow rendering with React.memo

### ISSUE THREAD

**Issue by henryqdineen** [facebook/react#17440]
I understand that the future of `react-test-render/shallow` is uncertain but I thought I would log this issue anyway. It looks like components wrapped in `React.memo` will not re-render unless props changed. In our case the component is using the `useState` hook and updating state does not re-render when using wrapped in `React.memo()`

https://github.com/facebook/react/blob/54f66731c84e3f141a1c0bc5d32be7cc5d4b9bbf/packages/react-test-renderer/src/ReactShallowRenderer.js#L621-L627

Contrived codesandox example:

https://codesandbox.io/s/sweet-field-ydm0c?fontsize=14&hidenavigation=1&module=%2Fsrc%2Findex.test.js&previewwindow=tests&theme=dark

**Comment by bdwain** [comment]
this is mentioned in #17278 and is fixed in https://github.com/airbnb/enzyme/pull/2300

**Comment by gaearon** [comment]
Please feel free to file this in https://github.com/NMinhNguyen/react-shallow-renderer.
