### ISSUE TITLE
why my babel can't recognize react short syntax?

### ISSUE THREAD

**Issue by wangx1229** [facebook/react#17459]
I use the lasted short syntax <></> in my code and @babel 7 in my package.json
but when i run my code in dev-environment, here comes to some bug I can't fixed

here is the Error:
SyntaxError: Unexpected token (98:17)

   96 |             {
   97 |               imgFlag && (
>  98 |                 <>
      |                  ^
   99 |                   <img
  100 |                     className="u-video-play"
  101 |                     onClick={playVideo}

and my package.json file
"dependencies": {
    "@babel/polyfill": "^7.7.0",
...
},
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "@babel/core": "^7.0.0",
   ...
}

**Comment by bvaughn** [comment]
This doesn't seem like an issue that should be filed against React. Support for the new fragment syntax was added in https://github.com/babel/babel/pull/6552 and released in [`v7.0.0-beta.31`](https://github.com/babel/babel/releases/tag/v7.0.0-beta.31)

If you're seeing an error, I'd suggest providing a repro case and filing a bug on the Babel repo.
