### ISSUE TITLE
Circular dependencies in reconciler

### ISSUE THREAD

**Issue by 0e39bf7b** [facebook/react#17458]
**Do you want to request a *feature* or report a *bug*?**

Discussion

**What is the current behavior?**

Exploring source code of React.JS I've found that ReactFiberBeginWork.js depends on some functions from ReactFiberWorkLoop.js:
https://github.com/facebook/react/blob/6470e0f169b4cf0416132aa66221bf20e264c618/packages/react-reconciler/src/ReactFiberBeginWork.js#L173-L180

At the same time ReactFiberWorkLoop.js depends on some functions from ReactFiberBeginWork.js:
https://github.com/facebook/react/blob/6470e0f169b4cf0416132aa66221bf20e264c618/packages/react-reconciler/src/ReactFiberWorkLoop.js#L121

Actually it's not a bug but it may lead to some unexpected behavior in future. Is it okay to have such circular dependencies?

**Comment by threepointone** [comment]
Yup, it should be fine. Besides, in the built versions, it's flattened into a single file.

**Comment by 0e39bf7b** [comment]
@threepointone would you please explain a bit more why it's ok? It's difficult to understand how this code works because of circular dependencies. There are a lot of articles about disadvantages of circular dependencies and different ways of eliminating them. That's why if it's possible I want to have a bit more clear explanation about why it's ok to have circular dependencies in this case.

> Besides, in the built versions, it's flattened into a single file.

I think the main idea of source code it to be clear for developers who read it. That is why it's more important to have source code that is easy to read (circular dependencies make code harder to understand) and less important how this code is organized in production minified build.
