### ISSUE TITLE
useState hook different behavior than class with react context

### ISSUE THREAD

**Issue by oscarmorrison** [facebook/react#17452]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

I have a PageContext file that has some shared context among a number of components. The when using the class version, using this.state, it acts as expected, and all components utilizing pagecontext update when the page context is updated. HOWEVER if I use the functional component, `PageContextProvider` with the `useState` hook, it does NOT act as expected, and not all updates to the context rerender dependent components.

```
//PageContext.jsx
import React, { useState } from 'react';

const PageContext = React.createContext();

// Using state hook, functional (does not work as expect)
const PageContextProvider = (props) => {

    const [ page, setPage ] = useState(null);

    console.log('PageContextProvider', page);
    return (
        <PageContext.Provider value={[page, setPage]}>
            {props.children}
        </PageContext.Provider>
    );
}
// Using class (this works as expected)
class PageContextProvider extends React.Component {
    state = {}

    setPage = (page) => {
        console.log('setPage', page);
        return this.setState({page});
    }

    render = () => {
        const { page } = this.state;
        console.log('render PageContextProvider', page);

        return (
            <PageContext.Provider value={[page, this.setPage]}>
                {this.props.children}
            </PageContext.Provider>
        )
    }
}

export { PageContext };

export default PageContextProvider;
```

**What is the expected behavior?**
The useState hook wrapper around the context, should act as the class one does

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.11.0
latest chrome.

What am I missing here?

**Comment by Bastardly** [comment]
My guess is that you are passing page and setPage as an array, instead of by reference. 

Try passing the provider value like this: value={{page, setPage}}

Hope this helps :)

**Comment by oscarmorrison** [comment]
Thanks @Bastardly for the quick response. Unfortunately still not behaving the same:

```
/// this does NOT work
const PageContextProvider = (props) => {

    const [ page, setPage ] = useState(null);

    return (
        <PageContext.Provider value={{ page, setPage }}>
            {props.children}
        </PageContext.Provider>
    );
};
```

```
// this DOES work
class PageContextProvider extends React.Component {
    state = {}

    render = () => {
        const { page } = this.state;

        const setPage = (page) => this.setState({page});

        return (
            <PageContext.Provider value={{ page, setPage }}>
                {this.props.children}
            </PageContext.Provider>
        )
    }
}
```

**Comment by rhagigi** [comment]
Can you elaborate? What exactly isn't working in your example here?

**Comment by oscarmorrison** [comment]
The `setPage` function works from other functions, e.g in the react component chrome tools I can see the context is correct. 

but components that use the page state, like so `const { page, setPage } = this.context` do not rerender properly after each setPage update. They do behave correctly if I use the class context provider as here: https://github.com/facebook/react/issues/17452#issuecomment-558331400

**Comment by TrySound** [comment]
Could you provide codesandbox with both examples?

**Comment by bpas247** [comment]
@oscarmorrison FWIW this [CodeSandbox example](https://codesandbox.io/s/usestate-working-properly-with-context-perpo) seems to work properly 🤷‍♀

**Comment by robtaussig** [comment]
Depending on where your Provider is rendered in your app, it might be updating frequently because of parent updates. As such, the value passed to the Provider is also changing by reference every update because you are passing page and setPage inside of an unmemoized array/object (which would change in reference every update). What I might do in your case is:

    const PageContextProvider = (props) => {

        const [ page, setPage ] = useState(null);
        const contextValue = useMemo(() => ({ page, setPage }), [page])

        return (
            <PageContext.Provider value={contextValue}>
                {props.children}
            </PageContext.Provider>
        );
    };

This doesn't necessarily explain why the functional version is behaving any differently than your class component as the class component is also passing page and setPage inside of a new array/object, but my guess is that if this is part of a larger refactor where you are converting class components to functional ones, the bug is due to the context consumers being functional components and how you might be using useEffect (or defining callbacks that reference context values), instead of the Provider itself.
