### ISSUE TITLE
Clicks on links with hash do not get caught by delegated onClick handlers

### ISSUE THREAD

**Issue by gpetrioli** [facebook/react#17450]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When clicking on a link with a hash `href` the event does not get caught by delegated `onClick` handlers higher in the DOM, although it works correct for `onMouseDown` events and for clicks on links without a hash.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

example: https://codesandbox.io/s/loving-smoke-oqx2w

**What is the expected behavior?**

The delegated handler should also get triggered for the `onClick` event.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested on MacOs (catalina) Firefox 70.0.1, Chrome 78.0.3904.108
React 16.8.6

**Comment by jddxf** [comment]
https://github.com/codesandbox/codesandbox-client/issues/1463

**Comment by gpetrioli** [comment]
> [codesandbox/codesandbox-client#1463](https://github.com/codesandbox/codesandbox-client/issues/1463)

😊
