### ISSUE TITLE
React-DevTools highlightable props, state and etc ...

### ISSUE THREAD

**Issue by tajpouria** [facebook/react#17461]
#### This is a **Feature request**
- Please make props, state and etc keys( right panel stuff keys ) highlightable in order to  user be able to copy the mentioned keys.

Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by bvaughn** [comment]
This info can already been copied using the button in the top-right hand corner:

![Screen Shot 2019-11-26 at 11 10 21 AM](https://user-images.githubusercontent.com/29597/69664511-60b8e180-103d-11ea-9217-4da2b8bac70b.png)

**Comment by anikolaev** [comment]
Copy button is useful when you need to copy all keys but it is typical situation when you just need to quickly copy single key. It is faster to retype it than to copy everything, find one key, copy it again. Why not to just remove `user-select: none` css attribute? It is very annoying for developer to see some text and not to have the ability to copy it.

**Comment by tajpouria** [comment]
@anikolaev  Exactly! In fact, I never used copy all object attributes button, and I believe being able to copy each key separately like what chrome dev tools provided in it's different tabs e.g. network , application and etc... significantly improve development workflow.
