### ISSUE TITLE
forwardRef doesn't like reassigned components

### ISSUE THREAD

**Issue by vincerubinetti** [facebook/react#17464]
With other higher-order/wrapper components from other libraries, I can replace a component with a wrapped version of itself like this:

```javascript
let Component = () => <div>hello world</div>;

// connect from react-redux
Component = connect(selector)(Component);
// withRouter from react-router
Component = withRouter(Component);

export default Component;
```

I don't see a lot of people do it this way, so I guess it's not recommended best practice. I know mutating is the devil and functional is always the way to go, but I think this is a lot cleaner because, 1) you don't have to nest a bunch of functions which increases the indent of the code and decreases readability, 2) you don't have to create a bunch of separate duplicate component names with obtuse names like `ComponentWithRouter` or `ConnectedComponentWithRouterWithForwardedRef`, and 3) your first definition of the component is just the pure display component that receives all the props it needs (it doesn't care where they come from), and then you define everything that "connects" to it separately.

Anyway, with `forwardRef`, reassigning the component like this seems to crash React.

**Fine:**
```javascript
const UnforwardedComponent = ({ forwardedRef,  ...props}) => <div>sup</div>
const Component = forwardRef((props, ref) => <UnforwardedComponent {...props} forwardedRef={ref} />;
export default Component;
```

**Also fine:**
```javascript
const Component = forwardRef((props, ref) => <div {...props} ref={ref}>sup</div>;
export default Component;
```

**Crashes:**
```javascript
let Component = ({ forwardedRef, ...props }) => <div>sup</div>;
Component = forwardRef((props, ref) => <Component {...props} forwardedRef={ref} />
export default Component;
```

I assume there's a under-the-hood reason why this doesn't work. But if it's at all possible, it'd be great to allow `forwardRef` to work in this manner.

Please let me know if I'm missing something obvious.

**Comment by bvaughn** [comment]
```js
let Component = ({ forwardedRef, ...props }) => <div>sup</div>;
Component = forwardRef((props, ref) => <Component {...props} forwardedRef={ref} />
export default Component;
```

This example is re-assigning what `Component` points to so that it points to the forward-ref component. This means that when that component renders, it will return _itself_ and get caught in a loop.

This doesn't have anything to do with `forwardRef`. For example, this would also fail:
```js
let Foo = () => {};
Foo = () => Foo();
```

**Comment by vincerubinetti** [comment]
My apologies, I must be delirious.

As a result, the syntax I was actually looking for is this, for anyone curious:

```javascript
let Component = (props, ref) => <div {...props} ref={ref}>hello</div>

Component = forwardRef(Component);

export default Component;
```

I guess maybe what I was looking for is that `forwardRef` would provide named parameters such that a ref-forwarded component could accept just named parameters, like any other component, as is the convention nowadays. But as that would be a breaking change for many people, it's not a reasonable request.
