### ISSUE TITLE
Who to contact for use of logo approval

### ISSUE THREAD

**Issue by vpapalia** [facebook/react#17468]
Hi, I was looking to use the react logo for a presentation we're making for a tech conference. Was just wondering if there's an appropriate contact to discuss this with?

**Comment by threepointone** [comment]
Within reason, you should be able to use the logo as you wish. The community has hundreds of variants that they create for conferences, stickers, whatever. As long as you don't claim that you own the logo, I suppose :) 

Closing this issue, but happy to answer further questions. Do you have a specific usage you'd like to discuss?
