### ISSUE TITLE
Suspense calls useEffect before render

### ISSUE THREAD

**Issue by drcmda** [facebook/react#17470]
## Do you want to request a *feature* or report a *bug*?

Bug

## What is the current behavior?

The React docs say

> useEffect lets us express different kinds of side effects **after a component renders**.

But under suspense that doesn't seem to be true any longer. useEffect is called pre-emptively. Or at least "rendering" seems to refer to the double-buffer (?)

There are situations where side-effects rely on the element having been rendered out effectively and visually.

## Demo

In my case i need to render content on the screen that's supposed to follow along the parents whereabouts.

https://codesandbox.io/s/mystifying-wilson-30u2m

useEffect (belonging to the `<Dom/>` component) dumps out content before the parent has rendered, which is very odd since the parent is suspended until all the other components are done loading. This is mixed mode react, two reconcilers. But that shouldn't have anything to do with it. The culprit is useEffect.

## What is the expected behavior?

useEffect should fire after the component has effectively rendered. I think that is what most people thought it would already do.

## Which versions of React are affected by this issue?

16.12.0

**Comment by drcmda** [comment]
Debugging deeper into how this works, it is clear to me now what happens. So essentially the component does render, but the reconciler calls `hideInstance(instance)` on it. When the suspense is lifted it calls `unhideInstance(instance)`.

But i still believe this is either a bug or a problem. useEffect is going loose on an object that isn't there and whose visibility could affect interop (measuring, position, etc). In threejs for instance `visible=false` means it's getting skipped by the renderer completely, unlike html's `visibility="hidden"` which at least would fill out the space.

**Comment by gaearon** [comment]
Can you make an example that doesn't mix two renderers? That would be a bit easier to follow.

It would also make it easier to check whether this happens in Concurrent Mode too. (It's expected that Suspense in legacy mode has some unfortunate unfixable quirks.)

**Comment by drcmda** [comment]
Here's a plain react demo: https://codesandbox.io/s/distracted-goldstine-07bpl

You have to open codesandboxes console to see the ready logs, indicating that useEffect fires even though these components aren't ready yet.

I added react-spring for a simple fade-in on mount animation, something that people have been done for years. All of this falls flat inside suspense, because the animation fires long before the component shows up, and by the time it does it's already at end-state.

**Comment by drcmda** [comment]
Tried it in concurrent mode, and it seems to behave correctly there. That already is a huge relief.

**Comment by AlexReff** [comment]
`useLayoutEffect` also appears to have the same issue

**Comment by sebmarkbage** [comment]
This is a known issue. The problem is that legacy life-cycles and this behavior are in direct conflict. So we can't fix it and also preserve legacy life-cycles at the same time.

The fix is to switch to Blocking Mode or Concurrent Mode.
