### ISSUE TITLE
Assigning an undefined object a property results in component being re-rendered

### ISSUE THREAD

**Issue by winash1** [facebook/react#17472]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When an undefined object is assigned a property, the component in which this is done re-renders.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
function ashwin() {
  let obj = undefined;
  obj["hasBasket"] = true;
}
call this function inside a functional component. It will result in the code being rendered again before throwing an error.
https://codesandbox.io/s/priceless-wing-6xh8r
**What is the expected behavior?**
Shouldn't render again and just throw an error
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React:- 16.10.2
Was able to reproduce it in chrome and safari.
Didn't test it in previous versions of React

**Comment by kunukn** [comment]
I can confirm a duplicate render is called on error.

With error
```jsx
function App() {
  console.log("rendered " + Date.now());
  throw new Error();
  return "hello";
}
```

>rendered 1574931554803 
>rendered 1574931554803 
>The above error occurred in the <App> component:
>   in App (at src/index.js:17)

Without error

```jsx
function App() {
  console.log("rendered " + Date.now());
  return "hello";
}
```

>rendered 1574931554803

**Comment by threepointone** [comment]
This is as expected. In DEV mode only, React runs the component again to rethrow the error to make sure "pause on uncaught exceptions" works in devtools. It shouldn't affect your workflow.
