### ISSUE TITLE
eventPhase is spoiled (always 3)

### ISSUE THREAD

**Issue by droganov** [facebook/react#17477]
The problem:
I need to detect if I get target or bubbled event.
I [expect](https://developer.mozilla.org/en-US/docs/Web/API/Event/eventPhase) eventPhase to be 2 for target event and 3 for bubbled event.

At least I can implement that in vanilla js. But as it gets to react I always get 3 instead of 2;

A testcase:

```html
<div id="app"></div>
<hr />
<div id="wrap">
      <button id="vanillaButton">Vanilla button</button>
</div>
```

```
#wrap {
  padding: 16px;
  outline: 1px dotted;
}
```

```javascript
const vanillaButton = document.getElementById('vanillaButton');
const wrap = document.getElementById('wrap');
const app = document.getElementById('app');

function handleClick(event) {
  const safeEvent = event.nativeEvent || event;
  console.log('click', event.eventPhase, safeEvent.eventPhase);
}

const ReactButton = () => <button onClick={handleClick}>React Button</button>;


wrap.addEventListener('click', handleClick);


ReactDOM.render(<ReactButton />, app);
```

In this case:
Vanilla button is expected to trace 3 — yes
Wrap is expected to trace 2 — yes
React button is expected to trace 2 — no, got 3

**Comment by droganov** [comment]
https://jsbin.com/bututirugi/edit?js,console,output

**Comment by bvaughn** [comment]
cc @trueadm Not sure if you're considered this with the new Events API proposals.

**Comment by trueadm** [comment]
@bvaughn It was part of the useEvent API proposal. It's also something we could change in the Synthetic Event system, although there's been little demand (other than this issue) and it would be a breaking change to introduce it in 16.x - maybe it's something we can consider for future versions.
