### ISSUE TITLE
No workaround for issues with autofocus

### ISSUE THREAD

**Issue by gustav1105** [facebook/react#17482]
Bug report

There is no workaround for autoFocus! the linter will not compile typescript code when using autofocus. Readers and accessibility issues, could you please provide a workaround for this problem alternatively please remove it from the library as it causes more issues than it is worth.

**Comment by kunukn** [comment]
Hi, I have created a minimal TypeScript + React + autoFocus example

Demo where autofocus work, the second input is auto focused.
https://keznh.csb.app/

Code
https://codesandbox.io/s/react-typescript-autofocus-keznh

Can you provide a minimal, reproducible example?

**Comment by bvaughn** [comment]
Your general complaint seems like a specific case of the general issue mentioned in #10863.

According to [the HTML spec](https://w3c.github.io/html-reference/documents.html#case-insensitivity):
> Attribute names for HTML elements may be written with any mix of lowercase and uppercase letters

So `autoFocus` is a valid value for the HTML. React has more constraints in this regard (aka we only support `autoFocus` and not `autofocus`) but React isn't a generic XML renderer.

I'm not sure what linter you are having problems with, but from my perspective it seems like React is working okay in this scenario and the solution would be to adjust your renderer to support `autoFocus`.
