### ISSUE TITLE
Changelog markdown formatting issue for v16.3.0 (React Test Renderer)

### ISSUE THREAD

**Issue by dance2die** [facebook/react#17481]
React Changelog Markdown documentation formatting issue.

## **Do you want to request a *feature* or report a *bug*?**

A bug in formatting, where subtitle should be `h3` (with `###`) but is marked with `h2` (`##`).

## **What is the current behavior?**

`React Test Renderer` subtitle is rendered as `h2`, not `h3`.

![demo](https://user-images.githubusercontent.com/8465237/69779015-8dbbe000-1174-11ea-87c5-f6a582d9a120.png)

### Using Chrome Devtools

1. Go to https://github.com/facebook/react/blob/master/CHANGELOG.md#react-test-renderer-3
1. Open Devtools to inspect the HTML.

### Via markdown source

1. Go to https://raw.githubusercontent.com/facebook/react/master/CHANGELOG.md
1. Search for word `* Fix handling of fragments in `toTree()`.`
1. You will see `## React Test Renderer`.
    - This should be `### React Test Renderer`

![search](https://user-images.githubusercontent.com/8465237/69779171-19357100-1175-11ea-8b79-f5c13909b79b.png)

## **What is the expected behavior?**

`React Test Renderer` subtitle is rendered as `h3` with `###`, **not** as `h2` with `##` .

## **Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Not Applicable.

## Additional context

It might look like nitpicking but I was programmatically parsing the changelog but ran into the inconsistency.  

Hopefully this can be fixed because
1. It's easy to fix
1. To prep for automated changelog documentation (for the future possibly).
1. and for _consistency_

Demo Sandbox: https://codesandbox.io/s/parse-react-changelog-mjpkg

I can do a PR should you approve

![inconsistency](https://user-images.githubusercontent.com/8465237/69779349-ba242c00-1175-11ea-8f9a-81f7d1ec7fb0.png)

**Comment by threepointone** [comment]
Happy to accept a PR for this, but you should be careful because this may break in the future again.

**Comment by dance2die** [comment]
Thank you for the review, @threepointone~
& PR => #17487
