### ISSUE TITLE
OnClick delaying re-render

### ISSUE THREAD

**Issue by dalisalvador** [facebook/react#17485]
Hi,

I'm currently having a performance issue that I can't solve.
Problem: the `<Spinner />` is taking a couple of ms to render (due to `slowFunction`)

```
const myComponent = ({...props)} => {

const { myProp, slowFunction } = props;
const [loading, setLoading] = useState(false);

return (
   <Button
       onClick={ () => {
            setLoading(true);
            slowFunction(myProp); 
        }}
    >
      {loading ? <Spinner /> : "GO" }
    </Button>
)};

exports default myComponent;

```

So... after clicking the button, `loading = true` and therefore the `<Spinner />` gets rendered, **but it takes a couple of ms (tooooo many).** 
This problem is caused by `slowFunction`  and as soon as I remove the function, everything renders super fast. 

Any ideas?
Thanks

**Comment by embeddedt** [comment]
Perhaps you could use [`window.requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback)? It would let React finish re-rendering before `slowFunction` gets called.

**Comment by dalisalvador** [comment]
Still same result. :(
I also get a `[Violation] 'click' handler took 166ms` on the consolelog

**Comment by embeddedt** [comment]
Maybe you could try using an effect to run `slowFunction` instead. I'm pretty sure those are guaranteed not to execute until rendering finishes. You would still call `setLoading` within the button's click handler.

```c
React.useEffect(() => {
    if(loading)
        slowFunction(myProp);
}, [ loading ]);
```

Side note: If you are having performance problems, you should avoid creating new lambdas every time the functional component is evaluated, because that forces unnecessary rerendering within child components. Instead, you should use [`useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo).

**Comment by threepointone** [comment]
I'm not sure what this has to do with React? You shouldn't write slow functions, I suppose? It would help if you described what this function does, and whether there's opportunity to make it quicker. 

Closing since this isn't related to React.

**Comment by embeddedt** [comment]
Sorry, I was tired yesterday. I meant to suggest  [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback).

> I'm not sure what this has to do with React?

I think the idea here is that @dalisalvador wants to know the best way to work with slow, synchronous function within React.

**Comment by dalisalvador** [comment]
@embeddedt Thanks for your help... appreciated. I finally solved by combining `useCallback` and `React.memo`...

@threepointone guess it's was related...
