### ISSUE TITLE
ConcurrentMode suspend child alongside of input

### ISSUE THREAD

**Issue by MHA15** [facebook/react#17495]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
after first click on button it's just fine 
after 3 sec(after suspend mode finished) when you click on button again and start typing in input it will not show suspend fallback and it will wait on all 3 second (seems to `timeoutMs` is infinity now)
another time click on button (after suspend finished) this time we will not see "wait" phrase on button and it seems that `timeoutMs` is zero this time

https://codesandbox.io/s/long-shadow-1vhr6

**What is the expected behavior?**
show  1.5 second "wait" on button and after that show 1.5 second "child suspend" in front of it

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I'm using experimental version and these are new features of concurrent mode

**Comment by sebmarkbage** [comment]
It took me a while to parse this but the bug happens when you first click "next" and then immediately switch focus to the text input. It's as if the event dispatching itself causes something to change.

**Comment by MHA15** [comment]
> It took me a while to parse this but the bug happens when you first click "next" and then immediately switch focus to the text input. It's as if the event dispatching itself causes something to change.

thanks for your response 
I just wants to remind that there was two bug in that code 
first of all was for the focus after click next and second one was for clicking  next after blur of input component

**Comment by kambleaa007** [comment]
Child Suspends seems missing for next try

**Comment by MHA15** [comment]
@sebmarkbage 
any update?

**Comment by MHA15** [comment]
@sebmarkbage 
any update?

**Comment by MHA15** [comment]
@sebmarkbage 

Is this issue has forgotten ? 
Can I do anything to help fix it early?

**Comment by gaearon** [comment]
Does this still reproduce with a master build?

**Comment by gaearon** [comment]
This doesn't repro for me anymore. I think it's been fixed.
https://codesandbox.io/s/focused-mccarthy-6b043
