### ISSUE TITLE
react.production.min.js shoud include license notice of object-assign

### ISSUE THREAD

**Issue by dynamis** [facebook/react#17492]
**Do you want to request a *feature* or report a *bug*?**
report a bug (MIT license notice violation)

**What is the current behavior?**
react.development.js includes license comment about object-assign module but react.production.min.js doesn't.

https://unpkg.com/browse/react@16.12.0/umd/react.development.js (line60~)
```
/*
object-assign
(c) Sindre Sorhus
@license MIT
*/
```
https://unpkg.com/browse/react@16.12.0/umd/react.production.min.js
no comment about object-assign kept (but including the code)

**What is the expected behavior?**
react.production.min.js should also keep license comment about object-assign

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.12.0

**Comment by sebmarkbage** [comment]
Not sure what the rules are here but we've removed the object-assign dependency for UMD builds in https://github.com/facebook/react/pull/18180 so this will no longer be an issue.
