### ISSUE TITLE
react redux firestore mapStateToProps issue while getting data

### ISSUE THREAD

**Issue by samairali** [facebook/react#17497]
i am stuck in a very weird issue the issue is i am getting firestore collection like this

```
firestoreConnect([
    {collection : 'projects'}
])
```
then in mapStateToProps function

```
const mapStateToProps = (state) => {
        console.log('from mstp' , state.firestore.ordered.projects);
        return {
            fireProjects : state.firestore.ordered.projects
        }
    }
```
in this code console.log('from mstp' , state.firestore.ordered.projects); is showing data in a state but when i

> console.log(this.props) in component code

first i see fireProjects is undefined 
and then i see another console.log having fireProjects array of objects as i want . 
when i try to print the object from fireProjects then i see error undefined . is there any help i can get ? or if you want more clarification i can do that as well .. stuck in it from so much time

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
