### ISSUE TITLE
Custom hooks to api （fetch data）,How can it be reused?

### ISSUE THREAD

**Issue by victorykong** [facebook/react#17509]
**Do you want to request a *feature* or report a *bug*?**
error

**What is the current behavior?**
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
（1） const { data: { data: comments }, loading: commentsLoading } = useHttpRequest([], "/api/getcomment", "GET");
But after I've added the data and I'm going to pull the latest data again, what's the best way to write it.

**What is the expected behavior?**
（1）The above custom hooks can be called again in the method so you don't need to write more useState in the component

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
google browser, react cdn url.

**Comment by aweary** [comment]
Have you tried doing what the error says? You should check out [the Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) to be sure you're using them properly. 

We try to use this repo for bug reports and feature requests, and this seems like a usage question. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
