### ISSUE TITLE
Wrapping multiple components in a single Suspense breaks when using `createRoot`

### ISSUE THREAD

**Issue by jimmy-e** [facebook/react#17504]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Trying to wrap multiple components in a single Suspense is causing the app / api to perpetually fetch. This bug only happens while using the `createRoot` version of `react-dom`, where as `render` does not.

**To reproduce:**
* Please see [this code sandbox](https://codesandbox.io/s/festive-solomon-q9bk2).
* You will see that the app is getting stalled in the fallback state, rendering 'Loading page...'.
* You will see in the console that fetches are perpetually happening.

*index.tsx:*
```js
import * as React from "react";
import { createRoot, render } from "react-dom";
import SamplePage from "./SamplePage";

// createRoot(document.getElementById('root')).render(<SamplePage />); // This causes the app to break

render(<SamplePage />, document.getElementById("root")); // This works
```

*sampleComponent.tsx:*
```js
import * as React from 'react';
import api, { Resource } from './api';

interface ResourceContainerProps {
  userId: number;
}

interface SampleComponentProps {
  resource: Resource<object>;
}

const SamplePage: React.FC = () => (
  <div style={{ display: 'flex', flexDirection: 'column' }}>
    <React.Suspense
      fallback={<h1>Loading page...</h1>}
    >
      <ResourceContainer userId={1} />
      <ResourceContainer userId={2} />
      <ResourceContainer userId={3} />
      <ResourceContainer userId={4} />
    </React.Suspense>
  </div>
);

const ResourceContainer: React.FC<ResourceContainerProps> = ({ userId }) => {
  const resource = api.getSampleData(userId);
  return (
    <SampleComponent resource={resource} />
  );
};

const SampleComponent: React.FC<SampleComponentProps> = ({ resource }) => {
  const data: any = resource.sampleData.read();
  return <p style={{ margin: '1' }}>{`Username: ${data.data.username}`}</p>;
};

export default SamplePage;
```

**What is the expected behavior?**
Be able to wrap multiple components, each with their own individual resource, in a single Suspense while using `react-dom`'s `createRoot` method.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
* axios 0.19.0
* react ^0.0.0-experimental-38dd17ab9
* react-dom ^0.0.0-experimental-38dd17ab9
* react-scripts-ts 2.13.0

**Comment by sebmarkbage** [comment]
The issue is with the implementation of `getSampleData`. This is not how you implement a data backend for suspense. There will be more than this issue if you implement it this way. It needs to be rooted in the cache. We don't really have documentation for how to do it but it's not actually recommended that you do that yourself at all. We'll have an official implementation at some point.
