### ISSUE TITLE
Local server is not run

### ISSUE THREAD

**Issue by itganes** [facebook/react#17502]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
![image](https://user-images.githubusercontent.com/36252647/69981906-5f1a7c80-155b-11ea-8b9a-041fd12f1253.png)
![image](https://user-images.githubusercontent.com/36252647/69981995-883b0d00-155b-11ea-8391-91635376d36d.png)
![image](https://user-images.githubusercontent.com/36252647/69981998-88d3a380-155b-11ea-97e3-0c9ef5a9db96.png)

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
