### ISSUE TITLE
CSS Not Being Applied (or Overwritten?) Route Based Code Splitting

### ISSUE THREAD

**Issue by rag4214** [facebook/react#17511]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** 

At our website, we have a branch where we're converting to route based code splitting to reduce bundle sizes. The issue now is that our global `index.scss` properties aren't be applied to the lazy loaded modules. This is breaking things like our font faces / `<a>` tag styling.

```ts
// routes.ts BEFORE
import Home from '../components/home');

const Routes: React.FC = () => (
    <Switch>
      // ...
      <Route exact path="/" component={Home} />
      <Redirect from="*" to="/" />
    </Switch>
);
```
```ts
// routes.ts AFTER
const Home = lazy(() => import('../components/home'));

const Routes: React.FC = () => (
  <Suspense fallback={/*...*/}>
    <Switch>
      // ...
      <Route exact path="/" component={Home} />
      <Redirect from="*" to="/" />
    </Switch>
  </Suspense>
);
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:** 

N/A because of reliance on bootstrap but the [link to the branch](https://github.com/RITesports/Website/tree/route-spliting/react-app/src)

1. Clone Branch
2. install deps for react-app
3. npm start

`/teams` wont' work but all of the text is left aligned on the cards and the link are normal blue and underlined (I can provide pictures if needed). You can compare this to the live site  [here](https://www.esportsrit.com).

**What is the expected behavior?** The global css should be applied the same, lazy loaded or not.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** All Browsers. No idea on older versions.

**Comment by rag4214** [comment]
I seem to have found an issue. Before my compiled HTML was only inserting something like
![image](https://user-images.githubusercontent.com/35985028/70113926-85f2b480-1628-11ea-85f7-ae6457327fcb.png)
While now with the code-splitting I get with bootstrap being the last `<style>`, therefore overwriting all of my stuff
![image](https://user-images.githubusercontent.com/35985028/70113950-9f93fc00-1628-11ea-851f-661f8da1164c.png)

**Comment by aweary** [comment]
This doesn't seem related to React. You'll have to dig into your build system to see what's going on. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
