### ISSUE TITLE
Stale values for useState inside callback functions

### ISSUE THREAD

**Issue by alex-cory** [facebook/react#17517]
**Do you want to request a *feature* or report a *bug*?**
potential bug

**What is the current behavior?**
When calling `setState` from `useState`, the `state` value is stale from inside a function. The value is correct inside the body of the component, but not inside the function itself.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Begin by typing `a@g` which should autocomplete to `a@gmail.com`. You will see the `expected` and `actual` values for the input below each.
https://codesandbox.io/s/useemailautocomplete-material-ui-04423

**What is the expected behavior?**
It should have the correct value for `email` inside the `handleChange` function.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: `v16.12.0`
Browser: chrome
OS: Catalina

**Comment by aweary** [comment]
When you call `setState` React doesn't always updated the state synchronously. So even though you've called `handleEmailChange` the `email` value has not yet been updated while `handleChange` is still executing.

You can see this behavior [in this much simpler example](https://codesandbox.io/s/immutable-wind-ifzn2). If you need to use the latest state value in `handleChange`, just use the value you passed to `setState`

**Comment by alex-cory** [comment]
I get that it doesn't execute synchronously, but is that not a bug?

You're saying it intentionally doesn't update the value like that?

I feel like that behavior is not very desirable. In the past, in most cases, when state was updated it was reflected on the next line.

**Comment by aweary** [comment]
> I feel like that behavior is not very desirable. In the past, in most cases, when state was updated it was reflected on the next line within a function.

This behavior has been around since before Hooks and is important for a few reasons. Check out [the official FAQ, which covers this question](https://reactjs.org/docs/faq-state.html#why-doesnt-react-update-thisstate-synchronously). Hopefully that clears things up!
