### ISSUE TITLE
React Dev Tools Standalone only draggable, not clickable

### ISSUE THREAD

**Issue by mbman** [facebook/react#17522]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**

When running react-devtools standalone on Windows 10, they manage to connect to the React app, but the UI can't be clicked and clicking on it only drags the window. This makes it unusable.

I've debuged it using built-in Chrome dev tools and it's due to `-webkit-app-region: drag` applied to body and other elements. As soon as I override this to be `-webkit-app-region: none;` everything starts working fine - you can click on things and you can still drag the window.

**What is the expected behavior?**
Clicking on the UI should work and not only drag the window.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I've tested it with React Dev Tools standalone version 4.2.1-3816ae7c3

**Comment by hristo-kanchev** [comment]
I went through the PRs that were merged after the 4.2.0 release and from what I can see this might be causing the issue -> https://github.com/facebook/react/pull/17213/files#diff-0f549815d0bbdc6626381ce99a584450R100 

I'm super busy at the moment, so I'll probably not be able to fix this bug myself. 

Any takers? 😸

**Comment by hristo-kanchev** [comment]
I can't seem to reproduce it on a Mac 🤔

**Comment by cwatson88** [comment]
@hristo-kanchev happy to put a PR in, it can be found here: https://github.com/facebook/react/pull/17584
@mbman was correct in the post above, we have experienced this in the past in our product too. 
Hope it helps 😄

**Comment by bvaughn** [comment]
Fixed via PR #17584

**Comment by bvaughn** [comment]
FYI this issue should be fixed in v4.4 (released today)
