### ISSUE TITLE
Suspense priority warning does not work for any hook except the first one per component

### ISSUE THREAD

**Issue by acdlite** [facebook/react#17527]
The code that checks for high priority updates only checks the first hook on the component:

https://github.com/facebook/react/blob/5064c7f6aa2b46469ac601cc851640e91ec340a9/packages/react-reconciler/src/ReactFiberWorkLoop.js#L2889-L2891

`workInProgress.memoizedState` is the first hook.

It should loop through all the hooks instead:

```js
let firstHook = workInProgress.memoizedState;
if (firstHook !==  null) {
  let hook = firstHook;
  do {
    // Stuff goes here
    hook = hook.next;
  } while (hook !== firstHook)
}
```

**Comment by gaearon** [comment]
The warning is gone.
