### ISSUE TITLE
Component test reports "An update to ... was not wrapped in act(...)" even if it is

### ISSUE THREAD

**Issue by lud-hu** [facebook/react#17520]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Component test reports 

```
Warning: An update to Welcome inside a test was not wrapped in act(...).

When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */
```

even though it is wrapped in act.
```
 it("gets something", () => {
  act(() => {
    mount(<Welcome />);
  });

  expect(true).toBe(true);
});
```
Mounting the component with jest is the only thing that I do and the error is thrown anyway. Normally I'd want to mock the API calling library to test if the component is properly calling the endpoint and displays the data.
The same error appears when using ReactDOM.render() as stated in https://reactjs.org/docs/test-utils.html#act .

https://codesandbox.io/s/create-react-app-e4vsx
(See pages/index.test.js)

**What is the expected behavior?**
Not to throw the error message when everything it is wrapped in act() properly.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.12.0
I don't know if it worked earlier.

**Comment by lud-hu** [comment]
Ok after some further research I found a way that works:

```
it("gets something", async () => {
  const comp = mount(<Welcome />);
  await act(async () => {
    await Promise.resolve(comp);
  });

  expect(true).toBe(true);
});
```
I don't get why it is working like this. But is this by design?

**Comment by GasimGasimzada** [comment]
If you are doing data fetching in Welcome component, you need to wait for the component to be fully rendered. `act` makes sure that all the states etc are resolved before moving forward. Because you are performing an asynchronous operation (i.e data fetching), React thinks that all the state updates are completed. Then, once the promise is resolved, the program is already in a different location in the program's context; so, if you do state updates during Promise resolution, React will see that state updates are happening outside the act call and throw error. So, you should use asynchronous act calls to wait for all the async operations to be resolved:

```js
await act(async () => {
  mount(<Welcome />);
});
```

**Comment by lud-hu** [comment]
Hi @GasimGasimzada ,

thanks for the detailed explanation! This seems to help, and after further tries I could fix all the places triggering the error message. E.g. I also had to wrap these steps (entering text in an input and clicking on the "search" button after that) in separate act(). This way react waits for the necessary state changes in between.

`
    await act(async () => {
        comp.find("input").simulate("change", { target: { value: "hello" }});
    });
    await act(async () => {
        comp.find("button").simulate("click");
    });
`

**Comment by smokinjoe** [comment]
I'm on React 16.8.x and have the exact same situation of a service call occurring in my component that's not triggered by any sort of action other than mounting the component.

Wrapping all my `mount` calls in my test doesn't do anything - and I've noticed that `act` is completely synchronous.

Do I seriously have to convert this component into a class component to get rid of these warnings? It seems completely counterproductive for those of us that want to simply use react hooks in functional components.
