### ISSUE TITLE
Reordering of list's items leads to scroll to the top of page on Android device 

### ISSUE THREAD

**Issue by arhontmw** [facebook/react#17528]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
Video: https://yadi.sk/i/drnRHvyN2KH-jw
Demo: https://codesandbox.io/embed/react-example-3l3hz?fontsize=14&hidenavigation=1&theme=dark

Steps to reproduce:
1. Open the demo on Android device
2. Scroll to the bottom of the list
3. Wait until the list is reordered
4. Try to scroll up - you'll see that the list is automatically scrolled to the top or to the point near the top 

Note: could not reproduce this issue on iOS Safari

**What is the expected behavior?**
A browser should not scroll to the top of the list when items' reorder is happened

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- "react": "16.8.5"
- "react-dom": "16.8.5"
- "react-redux": "^5.0.5"
- Android 7.1.1, Nexus 6 Build/N6F27M (could not reproduce on iOS)
- Chrome 78.0.3904.108

**Comment by vkurchatkin** [comment]
This doesn't really have anything to do with React. To reorder existing DOM nodes React has to remove the from DOM, which messes up with the scroll.
