### ISSUE TITLE
React.cloneElement does not have props typing for a forwardedRefComponent

### ISSUE THREAD

**Issue by Garethp** [facebook/react#17524]
**Do you want to request a *feature* or report a *bug*?**

This is a bug report

**What is the current behavior?**

Versions Using:

When trying to use `React.cloneElement` on a component that has been wrapped in `forwardRef`, the type checking for the `props` doesn't pick up any props of the base component or the ref. Example:

```typescript
import * as React from "react";
import { forwardRef } from "react";
import { FunctionComponent } from "react";
import { RefObject } from "react";
import { useImperativeHandle } from "react";
import { useRef } from "react";
import { ReactElement } from "react";

export type DemoProps = {
  isValid?: () => boolean;
};

export type DemoRef = {
  isValid: () => boolean;
};

const Demo: FunctionComponent<DemoProps> = (
  { isValid = () => true },
  ref: RefObject<DemoRef>
) => {
  useImperativeHandle(ref, () => ({
    isValid
  }));
  return (
    <React.Fragment>
      <div></div>
    </React.Fragment>
  );
};

const forwardedDemoRef = forwardRef<DemoRef, DemoProps>(Demo);

type Props = {
  children: ReactElement<typeof forwardedDemoRef>;
};

const DemoContainer = ({ children }: Props) => {
  const ref = useRef<typeof forwardedDemoRef>(null);

  return React.cloneElement(children, { ref: ref });
};
```

The typescript compiler will have the following error message:

```
TS2769: No overload matches this call.   The last overload gave the following error.     Argument of type '{ ref: React.RefObject<React.ForwardRefExoticComponent<DemoProps & React.RefAttributes<DemoRef>>>; }' is not assignable to parameter of type 'Partial<ForwardRefExoticComponent<DemoProps & RefAttributes<DemoRef>>> & Attributes'.       Object literal may only specify known properties, and 'ref' does not exist in type 'Partial<ForwardRefExoticComponent<DemoProps & RefAttributes<DemoRef>>> & Attributes'.  index.d.ts(292, 14): The last overload is declared here.
```

What's happening here is that `Partial<ForwardRefExoticComponent<DemoProps & RefAttributes<unknown>>> & Attributes` doesn't expose the `DemoProps` or `RefAttribute` through the base `ExoticComponent` type that `ForwardedRefExoticComponent` extends.

**What is the expected behavior?**

The typescript compiler should be aware of the properties `ref` and `isValid` through the `DemoProps & RefAttributes<DemoRef>` type that's being passed into `ForwardedRefExoticComponent` and should not give an error about `ref` not existing on that type

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
@types/react: 16.9.14
react: 16.9.14
typescript: 3.7.2
```

Have not tested in previous versions of React

**Comment by kunukn** [comment]
>The typescript compiler should be aware ...

Issues with @types/react should probably go here
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react

Issues with typescript should probably go here
https://github.com/Microsoft/TypeScript/issues

It seems to me this is an issue with typed definitions for React?

**Comment by SanjiKir** [comment]
@Garethp Did you find the solution? Is it really a mistake in react types?

**Comment by IanVS** [comment]
It looks like the issue they opened in Definitely Typed is: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40888, and as of now, has not gotten any attention.
