### ISSUE TITLE
React Devtools standalone subpanels frozen on version 4.2.1

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [facebook/react#17532]
Verified that version 4.2.0 works well, so a recent regression. Haven't tried to create a small example to reproduce, but since it's a recent bugfix version that should be fairly easy to pinpoint.

**Comment by olo2552** [comment]
Doesn't work wor me too- I can click on tabs i.e. "Components" & "Profiler", but I cannot click and scroll components tree and star a profiler recording.

**Comment by hristo-kanchev** [comment]
Duplicate of #17522

**Comment by hristo-kanchev** [comment]
Hey @BartlomiejLewandowski  and @olo2552! What OS are you using by the way?

**Comment by salmankhilji** [comment]
Same here.  Using Node 10.17 on Ubuntu 18.04.  Node installed using NVM.

**Comment by bvaughn** [comment]
Fixed via PR #17584

**Comment by bvaughn** [comment]
FYI this issue should be fixed in v4.4 (released today)
