### ISSUE TITLE
Jest React UI - unit testing

### ISSUE THREAD

**Issue by PAAutofac** [facebook/react#17534]
I am pretty new to React and Jest unit test framework. I have my component and trying to write few unit test cases , tried few ways and unable to proceed further. Here is my code and test case. Can anyone guide /suggest the best approaches please. Non of the tests work and Thanks

React UI component Header

import React from 'react';
import { Navbar, NavbarBrand } from 'reactstrap';
import { Link } from 'react-router-dom';

const Header = ({children}) =>
    <Navbar light className="sticky-top navbar-expand-lg navbar-toggleable-sm bg-white border-bottom">
        <NavbarBrand tag={Link} to="/">Abc: Portal</NavbarBrand>
        <div className="d-flex w-100 justify-content-end">
            {children}
        </div>
    </Navbar>

export default Header
Tests - First two test cases passes, the third test case fails with error Expected is "" for received is "undefined " could anyone please guide me in the right direction.

import React from 'react'
import { shallow, mount } from 'enzyme';
import { Navbar, NavbarBrand } from 'reactstrap';
import { cleanup } from '@testing-library/react';
import renderer from 'react-test-renderer';
import { render, unmountComponentAtNode, ReactDOM } from "react-dom";
import { act } from "react-dom/test-utils";
import GlobalSettings from './../features/Header/GlobalSettings';
import UserDisplayName from './../features/Header/UserDisplayName';
import { Link, MemoryRouter  } from 'react-router-dom';
import Header from './../features/Header/';

import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

// automatically unmount and cleanup DOM after the test is finished.
afterEach(cleanup);

let container = null;
beforeEach(() => {
    // setup a DOM element as a render target
    container = document.createElement("div");
    document.body.appendChild(container);
});

afterEach(() => {
    // cleanup on exiting
    unmountComponentAtNode(container);
    container.remove();
    container = null;
});
    
test('renders correctly', () => {
    const tree = shallow(
        <NavbarBrand>
            Damage Matrix: Customer Portal
        </NavbarBrand>
        );
       
    expect(tree).toMatchSnapshot();
});

test('renders correctly', () => {
    const tree = renderer.create(
        <NavbarBrand>
            Damage Matrix: Customer Portal
        </NavbarBrand>
        ).toJSON();

    expect(tree).toMatchSnapshot();
});
test('test Header', () => {
    act(() => {
        render(<MemoryRouter><Header /></MemoryRouter>, container);
    });
    expect(container.children.afterEach).toBe("");

    act(() => {
        render(<MemoryRouter><Header children="Hello" /></MemoryRouter>, container);
    });
    expect(container.appendChild).toBe("Hello");

    act(() => {
        render(<MemoryRouter><Header>Testing Hello Children</Header></MemoryRouter>, container);
    });
    expect(container.appendChild).toBe(<UserDisplayName />);

});

**Comment by aweary** [comment]
Hey @PAAutofac! We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
