### ISSUE TITLE
useState hook behaves differently than setState when setting a Component in the state 

### ISSUE THREAD

**Issue by AnupamaHosad** [facebook/react#17539]
**Do you want to request a *feature* or report a *bug*?**
Ask a question about hooks behaviour

**What is the current behavior?**
If I set a component in the state using `useState` hook, it becomes a React element (does not stay a component), but the same does not happen if the component is set in the state with `setState` method in a class component.

Function component using hooks:
```
const AsyncComponent = props => {
  const [LoadedComponent, setLoadedComponent] = useState(null);
  const { loadComponent } = props;

  useEffect(() => {
    if (!LoadedComponent) {
      loadComponent().then(Component => {
        setLoadedComponent(Component.default ? Component.default : Component);
      });
    }
  }, []);

  console.log(LoadedComponent); // {type: "div", key: null,ref: null,props: Object,_owner: null,_store: Object}

  return (
    <Fragment>
      {LoadedComponent ? <LoadedComponent /> : <LoadingIndicator />}
    </Fragment>
  );
};
```

Class component:
```
export default class AsyncComponent extends PureComponent {
    state = {
        LoadedComponent: null
    }
    componentWillMount() {
        if(!this.state.LoadedComponent) {
            this.props.loadComponent()
            .then(Component => {
                this.setState({
                    LoadedComponent: Component.default ? Component.default : Component
                });
            });
        }
    }
    render() {
        const { LoadedComponent } = this.state;

        console.log(LoadedComponent); // function Overview() {}

        return (<Fragment>
            {LoadedComponent ? <LoadedComponent /> : <LoadingIndicator />}
        </Fragment>);
    }
}
```

AsyncComponent here is used to dynamically load components to help with code splitting
```
<AsyncComponent loadComponent={() => import("./Overview")}/>
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

The complete example that can be used to see the issue can be found in the link below:

https://codesandbox.io/s/react-state-component-setting-1pig4?module=%2Fsrc%2FAsyncComponent.js&expanddevtools=1

Both the function component using `useState` hook & the class component is present in the code. When the function component is used, error will be thrown in the console as shown below because the component was expected to be set in the state but it was a React element instead.

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <div />. Did you accidentally export a JSX literal instead of a component?
    in AsyncComponent (at src/index.js:12)
    in div (at src/index.js:10)
    in App (at src/index.js:18)
```
When the function component is commented out & the equivalent class component is used, you can see that the component renders correctly without any issue.

**What is the expected behavior?**
Expected the component to be set in the state like it happens when using setState in a Class component

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I guess 16.8+ since hooks was introduced

**Comment by vkurchatkin** [comment]
Thats because your component is actually a function, and passing a function to a `useState` setter has different meaning:

```js
const [val, setVal] = React.useState();

setVal({ foo: 123 }); // val will be { foo: 123} on next render

setVal(() => 123); // val will be 123, not () => 123 on next render
```

To side step this behaviour you can pass a function that returns a function instead:

```js
setVal(() => () => 123); // now it's going to be () => 123 on next render
```

Applying this concept to your example:

```js
const AsyncComponent = props => {
  const [LoadedComponent, setLoadedComponent] = useState(null);
  const { loadComponent } = props;

  useEffect(() => {
    if (!LoadedComponent) {
      loadComponent().then(Component => {
        setLoadedComponent(() => Component.default ? Component.default : Component);          // <--- HERE: that's it, just add () => 
      });
    }
  }, []);

  console.log(LoadedComponent); // {type: "div", key: null,ref: null,props: Object,_owner: null,_store: Object}

  return (
    <Fragment>
      {LoadedComponent ? <LoadedComponent /> : <LoadingIndicator />}
    </Fragment>
  );
};
```

**Comment by kunukn** [comment]
>passing a function to a useState setter has different meaning:

You can read more about it here.
https://reactjs.org/docs/hooks-reference.html#lazy-initial-state

**Comment by sophiebits** [comment]
@vkurchatkin's answer is correct.

This was a deliberate choice we made when designing useState – it makes your use case (storing a function in state) more quirky but makes lazy initialization and functional updates in general a little more ergonomic, which we decided was more important.

Adding `() =>` when you set it is a good workaround.

**Comment by AnupamaHosad** [comment]
Thanks for the explanation!

**Comment by soujvnunes** [comment]
> Thats because your component is actually a function, and passing a function to a `useState` setter has different meaning:
> 
> ```js
> const [val, setVal] = React.useState();
> 
> setVal({ foo: 123 }); // val will be { foo: 123} on next render
> 
> setVal(() => 123); // val will be 123, not () => 123 on next render
> ```
> 
> To side step this behaviour you can pass a function that returns a function instead:
> 
> ```js
> setVal(() => () => 123); // now it's going to be () => 123 on next render
> ```
> 
> Applying this concept to your example:
> 
> ```js
> const AsyncComponent = props => {
>   const [LoadedComponent, setLoadedComponent] = useState(null);
>   const { loadComponent } = props;
> 
>   useEffect(() => {
>     if (!LoadedComponent) {
>       loadComponent().then(Component => {
>         //                 HERE: that's it, just add () => 
>         setLoadedComponent(() => Component.default ? Component.default : Component);  
>       });
>     }
>   }, []);
> 
>   console.log(LoadedComponent); // {type: "div", key: null,ref: null,props: Object,_owner: null,_store: Object}
> 
>   return (
>     <Fragment>
>       {LoadedComponent ? <LoadedComponent /> : <LoadingIndicator />}
>     </Fragment>
>   );
> };
> ```

Thanks!
