### ISSUE TITLE
onChange handler for controlled input is not called when bootstrap js file is included

### ISSUE THREAD

**Issue by nmay231** [facebook/react#17530]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The `onChange` handler of a controlled radio button is not called if you include the bootstrap js file (popper.js and jquery and are fine).

Removing the script tag allows the change handler to be called, but it is necessary for bootstrap's responsive navbar collapsing.

This does not seem to be an issue with bootstrap because it works fine when not using React ([see gist](https://gist.github.com/nmay231/e60ede8015280baa495b31f1c56d82bc)).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Create a fresh react app with `npx create-react-app` and replace `App.js` and `index.html` with the versions from [this gist](https://gist.github.com/nmay231/db5196bc68cb7e6f3aa06eb5fa5ed337).
Try commenting out/uncommenting the indicated script tag in the html file and see how the output is logged or not logged to the console.

As an example, the following input's change handler would not be called.
```jsx
<label className="btn btn-secondary">
  <input
    type="radio"
    name="options"
    id="option1"
    value={1}
    checked={currentOption === 1}
    //  Not called when selected or deselected
    onChange={handleChange}
  />
  Option 1
</label>
// More options...
```

**What is the expected behavior?**

The onChange handler of the input should be called even when the bootstrap js file is included

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I tried this in Chrome 78 and Firefox 70 with React 16.12.0
This also did not work in v15.6 (after converting to class-based components).

**Comment by kunukn** [comment]
This seems to be a not recommended approach of applying Bootstrap to a React application.

Bootstrap JS and React are both trying to control the DOM giving this conflict.

There exists some Bootstrap + React libraries out there. 

e.g.
https://reactstrap.github.io/
https://react-bootstrap.github.io/

**Comment by nmay231** [comment]
I looked at those before but didn't realize they were recommended over CDNs to use the features of bootstrap that require js.

Thanks @kunukn !
