### ISSUE TITLE
useRef Hook Sealed only in Dev

### ISSUE THREAD

**Issue by andrewnottaviano** [facebook/react#17537]
**Do you want to request a *feature* or report a *bug*?**
Ask a question.
**What is the current behavior?**
So I ran into an issue where I messed up and forgot to access the `current` property of a `ref` and missed it when I was testing in dev build mode. But when I ran it against our automated tests (and I did have a test for this case and the tests run in production mode) in our CI/CD pipeline, my code passed. The passage was due to the way my component was built, but I would've expected my tests to blow up when trying to assign a property on the `ref` other than `current`. 

Thankfully we caught this before it went to master, but my question is why would this fail in dev and not production. I went digging in the hooks code and found this [line](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberHooks.js#L871), which appears to be sealing the `ref` object only when it is in dev. So, I'm just wondering what the reasoning is behind sealing the `ref` only in dev mode, wouldn't we want it sealed in production mode?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
^16.8.5

**Comment by kunukn** [comment]
I would speculate this could be for performance reasons.

https://jsperf.com/sealed-object-performance

Safari browser.
![image](https://user-images.githubusercontent.com/3199603/70359864-3ce76e00-187d-11ea-975d-58a7d4af271c.png)

**Comment by andrewnottaviano** [comment]
That's interesting. In chrome, it's the opposite

<img width="967" alt="Screen Shot 2019-12-06 at 16 18 03" src="https://user-images.githubusercontent.com/45438975/70360428-1a852e80-1844-11ea-855b-ba9f3f98449e.png">

**Comment by kunukn** [comment]
The difference for Chrome is small.

For Safari it is 69% slower.

**Comment by andrewnottaviano** [comment]
Thanks!
