### ISSUE TITLE
Prop Binding/Partial Application

### ISSUE THREAD

**Issue by trisys3** [facebook/react#17546]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

No easy way to do automatic prop binding.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

Sorry if this is has already been asked or talked about internally or in the GitHub issues, I just couldn't find anything with a simple Google search. I can't think of any reason for this behavior to be against react best practices, but the react devs are much smarter than me and have probably thought much longer and harder about this than I have. If this is too trivial or not worth the react devs' time, please close right away.

Basically, I'm proposing allowing for easy prop binding, similar to using `Function.bind()` or `Function.apply()`/`call()`. This would make it easier to pass props down when the component needs to be passed down directly, like in a prop to another component, like what react router does, and not as JSX. An example I found in my own code (`history` comes from react-router):

```
// search-bar.js
export default function SearchBar({className: outerClassName, Result = noopJsx, search, ...props}) {
    return <div className={outerClassName}>
        ... bar JSX
        <Results Result={Result} results={results} {...props} />;
    </div>;
}

Results.propTypes = {Result: PropTypes.func, results: PropTypes.object};
    function Results({Result, results, ...props}) {
        return <div css={resultsStyles}>
            {Object.entries(results || {}).map(([name, result]) =>
                <Result key={name} name={name} result={result} {...props} />)}
      </div>;
  }

// custom-search-bar.js
CustomSearchBar.propTypes = {history: PropTypes.object};
export default function CustomSearchBar({history}) {
    Result.propTypes = {name: PropTypes.string};

    return <SearchBar Result={Result} search={search} />;

    function Result({name}) {
        const url = '/other-page.js';
        const go = () => history.push(url);

        return <div onClick={go}>
            ... inner content
        </div>;
    }
}

function search() {
    // custom search function
}
```

Sorry if this is a little complicated, but basically there is a generic search bar and a more custom one. The custom one isn't too fancy, but it has a "history" prop, which comes from react-router. The history prop is used in the Result component, but because Result is a prop, any props passed to it must be in scope.

Now, one way to resolve this is to make the Result prop into a function, as components are just functions. For example,

```
    <SearchBar Result={({...props) => <Result history={history} {...props} />} />
```

or

```
export function SearchBar({Result, ...rest}) {
    ...snip
    <SearchBar Result={WrappedResult} />

    function WrappedResult({...props}) {
        return <Result history={history} {...props} />;
    }
}
```

but I feel like this is too complicated for such a simple task. I admit I haven't seen too many other places where this could be useful, but this is a relatively simple site.

I'm sure there are multiple ways this could be resolved, and this was a pretty early react component for me, though I had been coding in angular 1 for a while before that. If I were doing this site over, I might do something completely different that ignores this problem entirely. My point is, has this space ever been looked at?

I don't want to assume anything about the amount of work involved, and I'm not sure how often this would be used. That said, could we have something like `bindProps`? For example,

```
    <SearchBar Result={Result.bindProps({history})} />
```

Depending on how the partial application proposal (currently stage 1) goes, this may not be needed in react after all. For example, it might be as simple as:

```
    <SearchBar Result={Result({history: ?}) />
```

So what do you think? Has this ever been looked at? What alternatives were proposed, which I'm sure were much better than mine? Does my proposal have any merit whatsoever?

By the way, I have read how easy react makes things like prototyping and demoing code, but I ever realized how easy until I wrote this issue. I literally copied most of the 2 components, leaving out styles and such, and I changed the names of the components and files. In fact, I may change the names to what I used in the issue. Great job, react team, keep up the good work, making my life easier!

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Ubuntu
all browsers
react 16.9.0
react-dom 16.9.0

**Comment by miraage** [comment]
The problem you have described could be solved by using the [Render Props](https://reactjs.org/docs/render-props.html) pattern.

**Comment by trisys3** [comment]
I'm not doubting you, but I don't see how this problem could be solved wirh render props, as the problem is that an extra prop needs to be added in a different scope from the scope with the JSX. Can you explain, or provide an example?

**Comment by kunukn** [comment]
>Result={Result.bindProps({history})}

This look like [Higher order components](https://reactjs.org/docs/higher-order-components.html) to me 

But this could probably also be done using Context API, render props or other patterns.
Here is a simple HoC example mimicking `Result={Result.bindProps({history})}`.

```jsx
// HoC
const withExtraProps = (WrappedComponent, extraProps) =>
  function Component(props) {
    return <WrappedComponent {...extraProps} {...props} />;
  };

// Example component
let App = ({ currentPage, children }) => (
  <div className="app">
    <div>{children}</div>
    {currentPage && <div>{currentPage}</div>}
  </div>
);

// Add extra props
const history = { currentPage: "first page" };
App = withExtraProps(App, history);

// Render
ReactDOM.render(<App>hello</App>, document.getElementById("root"));
```

Demo
https://codesandbox.io/s/patient-glade-zb5bv

**Comment by trisys3** [comment]
Wow, this is exactly the same as my solution! I guess you're right, no use adding functionality that is already there to begin with.

Well, as I said, I didn't want to take too much extra time with this issue. If the answer to my problem is an extra function, that's perfectly fine with me. Thanks for the help!
