### ISSUE TITLE
box-shadow value is parsed the wrong way by React

### ISSUE THREAD

**Issue by flaviolivolsi** [facebook/react#17544]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

The value of `boxShadow`  in an element style is parsed the wrong way because the color is moved at the beginning of the value while instead it should be kept at its original position (the end).

For example, this element:

```
<div style={{ boxShadow: `1px 1px 1px #000` }} />
```

will be parsed like this:

```
<div style="box-shadow: rgb(0, 0, 0) 1px 1px 1px;"></div>
```

Major browsers like Chrome and Firefox are tolerant and will interpret the malformed CSS correctly, but the bug is causing issues on Puppeteer which fails to cast the shadow.

A [fiddle](https://jsfiddle.net/2md8eqst/) shows the issue, you can see inspecting the element how the value is malformed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I tested with React 16.12 on Ubuntu 18.11 with Chrome and Firefox. Puppeteer on an AWS Lambda machine encounters this problem too.

**Comment by aweary** [comment]
React doesn't do any parsing for `boxShadow` or other inline styles. This reformatting is being done by the browser when you set `style.boxShadow` on the DOM element. You can easily reproduce this outside of React:

```
let div = document.createElement('div');
div.style.boxShadow = '1px 1px 1px #000';
console.log(div.style.boxShadow);
// "rgb(0, 0, 0) 1px 1px 1px"
```
If this isn't happening with Puppeteer then it sounds like a potential bug on their end.

Hope that helps!

**Comment by flaviolivolsi** [comment]
It surely helps, thank you @aweary  :)
