### ISSUE TITLE
How authorize web application and manage sessions

### ISSUE THREAD

**Issue by MAmin233** [facebook/react#17545]
i am building a single page react app that uses redux as state manager and an express node js as backend server but i don't know what is the best way to authorize my users in the application!

if it was php or express-js website i could use PHPSESSION or express-session to manage users sessions data but now the single page web application is separated from the backend and i can't manage sessions like before!

my idea is to make a session id for each new web request then save it for client in local storage then in the server store all needed informations in a database and when application have an api call send that id in request header then we can check authorizations by using that implemented session

but i thought if there was a simpler way to handle this problem that have no need to make a session implementation by myself

(i don't want to use third party services like firebase or okta or save all session data in client part like JWT)

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
