### ISSUE TITLE
Provide a symmetric API to event.persist()

### ISSUE THREAD

**Issue by Izhaki** [facebook/react#17551]
Feature request.

The API of syntheticEvent is asymmetric, in the sense that you can `persist()` an event, but there's no way of returning it to the pool. This nullifies the benefit of pooling when it is most needed.

## The Problem

It is common to want to debounce/throttle/raf-schd burst events, like MouseMove. Doing so is part of the [official docs](https://reactjs.org/docs/faq-functions.html#how-can-i-prevent-a-function-from-being-called-too-quickly-or-too-many-times-in-a-row).

But as these strategies are asynchronous, one must call `event.persist()`, which results in increase in both memory consumption and garbage collection, which is the whole reason these events are pooled to begin with. (I am writing a library so no idea what clients might need from the event - caching its properties is not an option.)

Yet, in most cases, it is well established when these events are no longer needed. In the case of MouseMove, it is once the handler returns.

## Possible Solution

It would be nice if the event API would provide a method to return the event to the pool. Something like `unpersist()` (or maybe just `release()`?).

With such a feature, either bespoke code or modified debounce/throttle/raf-schd could return the previous event to the pool when a new one comes in. This will satisfy the goal of the event pooling - reduction of both memory and garbage collection.

**Comment by aweary** [comment]
@lzhaki are you experiencing any noticeable performance problems due to this limitation? There’s a lot of new event system exploration work being done so it’s unlikely that we’d expand the potentially-legacy event system API at this point. It might be worth it if we have a compelling case though.

To measure potential performance wins you can try to do `event.constructor.release(event)`, which should release the event back to the pool. Does that have a noticeable effect?

**Comment by Izhaki** [comment]
> are you experiencing any noticeable performance problems due to this limitation?

No. And no benchmarks.

Mine is a drag case (mouseMove) that triggers expensive geometric calculations. So I `event.persist()` it and then `rafSchedule`.

Given you went to the length of implementing event pool, seems to me odd not to harness it with `mousemove` - a 5 seconds drag can generate as many events as 13 minutes of 'normal' interaction. 

> you can try to do event.constructor.release(event), which should release the event back to the pool. 

Wait. This is exactly the solution I propose. But "should" bothers me a bit.

Just to clarify, you can call `event.persist()` and later call `event.constructor.release(event)` and it's back in the pool? As in:

```js
  const scheduleMouseMove = rafSchedule(event => {
    inMouseMove(event);
    event.constructor.release(event);
  });

  const onMouseMove = event => {
    event.persist();
    scheduleMouseMove(event);
  };
```

If So it's case closed.

**Comment by aweary** [comment]
> Wait. This is exactly the solution I propose. But "should" bothers me a bit.

`event.prototype.release(event)` is how events are released back to the pool internally when they are not persisted. It's an internal-only API I **do not** recommend using it in production. It's not a public API so there's no guarantees that it will work in every scenario, and I mention it only as an ad-hoc way to potentially measure if releasing back to the pool would have any benefits.

> Given you went to the length of implementing event pool, seems to me odd not to harness it with mousemove - a 5 seconds drag can generate as many events as 13 minutes of clicking about.

Event pooling was implemented pretty early on, and I'm not confident that it's actually that valuable anymore. The event object allocations are likely not a bottleneck, even with events like `mousemove`. 

If you don't need the entire `event` object I recommend avoiding calling `event.persist()` in the first place, read the values you need off of `event` instead, and pass those around.

```js
const onMouseMove = event => {
  const clientX = event.clientX; 
  // whatever properties you need...
  scheduleMouseMove(clientX, /* ... */)
}
```

Lastly, you can probably just wrap your root `mousemove` listener with `rafSchedule`  and avoid having to pass around the event object in the first place.

[Here's an example using the `raf-sch` crate with `onMouseMove`](https://codesandbox.io/s/pedantic-kirch-tlug9)

```js
// Wrap the root listener with the scheduler rather
// than having a second function you call yourself.
const onMouseMove = rafSchedule(event => {
  console.log('mouse move!')
})
```

**Comment by Izhaki** [comment]
Thanks @aweary,

As I mentioned in my OP:

> I am writing a library so no idea what clients might need from the event - caching its properties is not an option.

So your solution doesn't apply here.

Anyhow, given all you said, I'm closing this issue. Thanks!
