### ISSUE TITLE
the problem ablout add a <Button> to <div>

### ISSUE THREAD

**Issue by ZhangTeng4070** [facebook/react#17563]
<img width="1039" alt="截屏2019-12-10下午1 44 55" src="https://user-images.githubusercontent.com/31762662/70499056-43af0300-1b53-11ea-980b-a119e2274e71.png">
I am a novice . this is my code, i want to add this <Button> to the <div>,but if i do like this, the onClick function did't work, the wrong is "Uncaught SyntaxError: Unexpected end of input", if the operationContent is not a string type, the button will becomes [Object,Object],if i remove the "() =>", the function will execute by itself, what should i do?   QAQ

**Comment by alkawero** [comment]
sorry if i missunderstand your question, but usually i do something like 
`
const buttonComponent = <Button onClick={()=>{console.log("do something")}}>

<div>{buttonComponent}</div>

`

**Comment by ZhangTeng4070** [comment]
thank you very much, but You may not understand my problems, Simple, in other words, 
i hava a button   
const demoButton = <Button onClick={() => {this.rolesSave(userId)}}>save</Button>
how can i add this to a '<div>' , my code is dom.innerHTML = demoButton, but it is wrong,
thanks again.

**Comment by ZhangTeng4070** [comment]
thank you very much, but You may not understand my problems, Simple, in other words,
i hava a button
const demoButton = <Button onClick={() => {this.rolesSave(userId)}}>save
how can i add this to a  < d i v > , my code is dom.innerHTML = demoButton, but it is wrong,
thanks again.

**Comment by svltmccc** [comment]
@ZhangTeng4070 it's solution your problem https://reactjs.org/docs/rendering-elements.html

Also you can call renderToString and you will get html markup your component https://reactjs.org/docs/react-dom-server.html#rendertostring

**Comment by bvaughn** [comment]
This looks like a fundamental misunderstanding. Assigning a JSX string to `innerHTML` is not how React components are meant to be used. You're meant to render the elements using e.g. `ReactDOM.render()` [as shown in the docs](https://reactjs.org/docs/introducing-jsx.html#embedding-expressions-in-jsx).

Have you read through the [intro docs](https://reactjs.org/docs/hello-world.html) yet? That might be helpful. Then if you have specific questions, you might try asking them :smile:
