### ISSUE TITLE
Adding getDefaultContext method

### ISSUE THREAD

**Issue by tgriesser** [facebook/react#1756]
Realizing that context is undocumented and the API may change, I wanted to see what anyones thoughts might be on adding a `getDefaultContext` so it'd be possible to add reliable defaults if a context prop is not defined (making it be possible to write stricter `contextTypes` definitions).

**Comment by spicyj** [comment]
Haven't heard much desire for this so I'm going to close. It sounds like a likely antipattern to me to have a component that sometimes receives context from a parent and sometimes doesn't.
