### ISSUE TITLE
A Hook Within a Hook slips under the radar.

### ISSUE THREAD

**Issue by Izhaki** [facebook/react#17569]
A bug.

*(Or is it? I strongly suspect `useRef` is not like other hooks)*

# Given I use a hook within a hook

Code snippet (note `useRef` on the last line which wraps a call to `useClickAway`):
```js

const useDrag = ({ ref, onClick, onDragStart, onDrag, onDragEnd }) => {

  // ...

  const clickAwayRef = useClickAway({
    mouseEvent: 'onMouseUp',
    onClickAway,
    ref,
  });

  // ...
};

export default props => useRef(useDrag(props)).current;
```

And here're the first few lines of `useClickAway`:

```js
  const mountedRef = useMountedRef();
  const movedRef = React.useRef(false);
  const nodeRef = React.useRef(null);

  const handleNodeRef = useForkRef(nodeRef, ref);
  // can be removed once we drop support for non ref forwarding class components
  const handleRef = React.useCallback(
    instance => {
      // #StrictMode ready
      setRef(handleNodeRef, ReactDOM.findDOMNode(instance));
    },
    [handleNodeRef]
  );
```

# It should warn

> Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks. You can only call Hooks at the top level of your React function.

But it doesn't, and the code above seems to work just fine.

---

react@16.9.0

**Comment by gaearon** [comment]
This is ok because

```js
useRef(useDrag(props))
```

is essentially

```js
var x = useDrag(props)
useRef(x)
```

which has a stable call order.

This is different from the "within" case like `useEffect(() => { useRef() })` where it's *during a function that is called later* (an effect) rather than during rendering (which is fine).
