### ISSUE TITLE
Lint rule warns against hooks in functional sub-component.

### ISSUE THREAD

**Issue by P233** [facebook/react#17564]
Calling a hook in a functional sub-component causes an error  `React Hook "React.useContext" is called in function "Modal.Close" which is neither a React function component or a custom React Hook function` :

```jsx
Modal.Close = props => {
  const setIsOpen = React.useContext(ModalContext);

  return (
    <button onClick={() => setIsOpen(false)}>
      <Icon name="close" />
    </button>
  );
};
```

However, creating a new functional component and reassigning it to the main component won't cause that error.

```jsx
const Close = props => {
  const setIsOpen = React.useContext(ModalContext);

  return (
    <button onClick={() => setIsOpen(false)}>
      <Icon name="close" />
    </button>
  );
};

Modal.Close = Close;
```

I am currently using the latest version of React `16.12.0` and react-scripts `3.3.0`.

**Comment by bvaughn** [comment]
To be clear, hooks _can_ be called in a component that's defined the way you show. The issue you're reporting is with the hooks lint rules:
https://github.com/facebook/react/blob/031a5aaffbc06f0ac115f1d814e43e4d63ae15d2/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L454-L472

**Comment by lidoravitan** [comment]
@bvaughn is it still  relevant? can I help with that?

**Comment by bvaughn** [comment]
Not sure what the right solution is to this. Maybe there's a reason Dan decided against handling the case this issue mentions (or maybe he just didn't think about it or get to it).

I'd be happy to have you pick up the issue but you'd probably want to coordinate with him about getting it landed.

**Comment by lidoravitan** [comment]
@bvaughn thanks for response, maybe next time :)

**Comment by lidoravitan** [comment]
@bvaughn  thanks for response :), @gaearon Is there a way I can help with this?
