### ISSUE TITLE
npm create-react-app <app_name> fails with node_modules\core-js: EINVAL: invalid argument error

### ISSUE THREAD

**Issue by SatishAncha** [facebook/react#17573]
npx create-react-app not working properly and continuously failing 

OS: Windows 10
Yarn version: 1.21.0
Node version: 13.3.0
Npm version: 6.13.1

Attached the logs file.

Here below is cmd prompt logs:
C:\Users\satis\Documents\reacttest>npx create-react-app awesome-project

Creating a new React app in C:\Users\satis\Documents\reacttest\awesome-project.

warning ..\..\package.json: No license field
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

yarn add v1.21.0
warning ..\..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
[1/3] ⠂ core-js-pure
[2/3] ⠂ core-js
error An unexpected error occurred: "C:\\Users\\satis\\Documents\\reacttest\\awesome-project\\node_modules\\core-js: EINVAL: invalid argument, mkdir 'C:\\Users\\satis\\AppData\\Local\\Temp;C:\\Program Files (x86)\\Minimal ADB and Fastboot;\\yarn--1576052903837-0.6643317013326462'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\satis\\Documents\

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts cra-template --cwd C:\Users\satis\Documents\reacttest\awesome-project has failed.

[yarn-error.log](https://github.com/facebook/react/files/3949381/yarn-error.log)

**Comment by threepointone** [comment]
Please file this issue at https://github.com/facebook/create-react-app/issues
