### ISSUE TITLE
promise and setTimeout will run twice

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#17572]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

```jsx
export { V as App }
function V() {
  const [count, countSet] = useState()//if we annotation thie line will be ok
  console.log('sync')
  Promise.resolve().then(() => console.log('promise'))
  setTimeout(() => {
    console.log('timeout')
  })
  return 1
}```

**Comment by zhangenming** [comment]
and i close the React Developer Tools , will be ok
seems with it has a relationship

**Comment by zhangenming** [comment]
need 3 point will  trigger this bug
1, open  React Developer Tools
2, use useState
3, export { V as App }

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/70603233-08830180-1c31-11ea-8160-07e88256fa04.png)

**Comment by peternycander** [comment]
What is the problem you are having? I feel that a more realistic problem description could help.

Furthermore, you should not use setTimeout and fire off promises in render like that. Those are side effects and should be placed inside `useEffect`.

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
