### ISSUE TITLE
Can't import image dynamically in reactjs

### ISSUE THREAD

**Issue by JeremyMeissner** [facebook/react#17575]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Hi, I have a problem to import an image dynamically.

I have a code like this:
`console.log(require("./img/item.png"));`

and I want to do this:
`let url = "./img/item.png";
  console.log(require(url));`
And it doesn't work I dont know why ?
Can someone help me ?
Thank you !

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by hristo-kanchev** [comment]
If you are using `create-react-app` you can do the following:

`import itemImage from './img/item.png';`

If you have a custom Webpack configuration take a look at https://webpack.js.org/loaders/file-loader/

**Comment by JeremyMeissner** [comment]
I'm using `create-react-app`, but I actually want to import an image in my main function because i'm getting the url from a json file that I read in the main function so I can't import it on the top

**Comment by hristo-kanchev** [comment]
@JeremyMeissner You can use dynamic imports for that.

e.g.:

```
import('./img/item.png').then(image => console.log(image));
```

**Comment by threepointone** [comment]
Please file this issue at https://github.com/facebook/create-react-app/issues

**Comment by neilkapadia7** [comment]
> @JeremyMeissner You can use dynamic imports for that.
> 
> e.g.:
> 
> ```
> import('./img/item.png').then(image => console.log(image));
> ```

Can I use this inside a functional component?

**Comment by pradeeptinku** [comment]
@JeremyMeissner , Did you find any solution for this issue or did you open any issue?

**Comment by JeremyMeissner** [comment]
> 
> 
> @JeremyMeissner , Did you find any solution for this issue or did you open any issue?

I used the @hristo-kanchev method 

https://github.com/facebook/react/issues/17575#issuecomment-564525665

**Comment by ntwaricliberi** [comment]
> @JeremyMeissner You can use dynamic imports for that.
> 
> e.g.:
> 
> ```
> import('./img/item.png').then(image => console.log(image));
> ```

what if you don't want to console image but you want to use it in `<img src={} />`

**Comment by JeremyMeissner** [comment]
In my case I take this image from a JSON file so I define the state of my image url in the function componentWillMount() and then I call it. 

```
componentWillMount() {
  import('./img/item.png').then(image => {this.setState({url: image})})
}
```
```
render() {
  return (
    <img src={this.state.url}/>
  )
}
```

**Comment by sh4nnongoh** [comment]
@JeremyMeissner Hi, with typescript I am encountering this error with your method.

`Type 'typeof import("*.png")' is not assignable to type 'string'.`

The url attribute of the img tag is of type string but the imported object isn't.
What am I missing?
Thank you.

**Comment by JeremyMeissner** [comment]
@sh4nnongoh did you try this ?
https://stackoverflow.com/questions/51100401/typescript-image-import

**Comment by msveshnikov** [comment]
Starting from CRA 4.0 this is not working anymore:
import('./img/item.png').then(image => console.log(image));

**Comment by DanielAleks** [comment]
ds

**Comment by pgriscti** [comment]
``` javascript
  const [currentImage, setCurrentImage] = React.useState<string>();
  import("../myImage.png").then((image) =>
    setCurrentImage(image.default)
  );
  return <img src={currentImage} alt="" />;
```
