### ISSUE TITLE
React Hooks are unable to queue to process

### ISSUE THREAD

**Issue by AshifMohammad** [facebook/react#17576]
![image (2)](https://user-images.githubusercontent.com/20770645/70624330-14c58980-1c46-11ea-81c6-c284ef07b470.png)

## Steps To Reproduce

1. Create a Customer Hook 
```javascript
import { useContext } from "react";
import { SomeContext } from "src/SomeContext";

export const useCustomHook = () => {
  const {
    state: { deal }
  } = useContext(SomeContext);


const[contextVal, setContextVal] = useState("")

useEffect ( () => {  setContextVal( get(deal, "saleVehicle.pricing", {});) },[ deal])
  return contextVal;
};

useCustomHook.defaultProps = {
  deal: {},
  DealContext: {}
};
```

2. now Consume this hook into your component

```javascript 
import {useCustomHook} from "...relative path"

const salePrice = ({
  SomeContext: {
    state: { deal, shadowState },
  }
}) => {
//some handlers  - assume it working :D 
 const handleFocus = event => event.target.select();
  const handleOnBlur = ()=> { some call backs}
  });
  const handleOnChange = (ev, value) =>
    updateDeal(dispatch)({ target: { name: "salePrice", value } });

useEffect ( () => { useCustomHook(),[deal.id])

  return (
    <TextField
      value={deal.salePrice || vehSalePrice()}
      fullWidth
      onChange={handleOnChange}
      onBlur={handleOnBlur}
      disabled={hasOpenModal}
      quickEntry={quickEntryEnabled}
      decimalDigits={2}
      onFocus={handleFocus}
    />
  );
};

salePrice.propTypes = {
  DealContext: DealContextShape.isRequired,
};

salePrice.defaultProps = {

  deal: { price: "", Vehicle: { retailPrice: "" } },
  retailPrice: ""
};

```
3 - Once `<SalePrice / >` starts executing , It looks for the Hook `useCustomHook` but then `useCustomHook` internally calls another hooks `useContext, useState, useEffect` and while executing those hooks , it does not queue them up and screen blows up.

Describe what you expected to happen:
- React should handle the queue of hooks within and execute them as callStack does.

![](https://files.slack.com/files-pri/TJZUB1VM1-FR3UR5HSP/image.png)

**Comment by AshifMohammad** [comment]
![image (2)](https://user-images.githubusercontent.com/20770645/70624352-1ee78800-1c46-11ea-8242-1719dd4908db.png)

**Comment by peternycander** [comment]
You are breaking the [rules of hooks](https://reactjs.org/docs/hooks-rules.html) "Don’t call Hooks inside loops, conditions, or nested functions. Instead, always use Hooks at the top level of your React function"

**Comment by AshifMohammad** [comment]
I agree with the Rules, however, if i do call React Hook in a nested function i get clear message `### React Hook Violation Error Message`
![image](https://user-images.githubusercontent.com/20770645/70626478-8f90a380-1c4a-11ea-9517-8b6583c58919.png)

unlike the one I get?

**Comment by GasimGasimzada** [comment]
@AshifMohammad Could you please format the provided code. Use something like [Prettier Playground](https://prettier.io/playground/), copy-paste your code there, and update your initial comment.

Now, on to the issue. You have several issues in this source code. First of all, I do not think that `defaultProps` parameter applies to custom hooks (correct me if I am wrong about this). So, this is wrong:

```
useCustomHook.defaultProps = {
  deal: {},
  DealContext: {}
};
```

Secondly, you cannot define a component with a camelCasing. It has to be PascalCase. Here is a quote from the [docs about ESLint plugin checks]:

> Calls to Hooks are either inside a **PascalCase** function (assumed to be a component) or another useSomething function (assumed to be a custom Hook).

So, your hooks are failing because React thinks that you are calling them inside of a regular function, not a React component. 

Thirdly, this is wrong: 

```
useEffect(() => {
    useCustomHook();
  }, [deal.id]);
```

You cannot call hooks from inside [nested functions](https://reactjs.org/docs/hooks-rules.html), especially inside other hooks.

**Comment by AshifMohammad** [comment]
Any update on this issue?

**Comment by gaearon** [comment]
What issue? As the comments say, the original example doesn't follow the Rules of Hooks. It's expected there might be errors in this case.
