### ISSUE TITLE
Bug: React table - Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by lyvija** [facebook/react#17583]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Hello,
I am new in React and I am trying to create a simple react table to display data from db with login for user authentication. 
Until I added the login, it worked. Momentally, it still throws the same mistake, no matter what. None of the existing solutions helped me, I tried to repair imports and exports, I reinstalled nodejs, reinstalled node_moduls. 

First, I verify the user by logging in to redirect me to the records page after verification. Verification is ok, but then it crashes.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Edit: login, password: admin, admin

https://codesandbox.io/s/black-voice-2z6y5?fontsize=14&hidenavigation=1&theme=dark
https://codesandbox.io/embed/black-voice-2z6y5?fontsize=14&hidenavigation=1&theme=dark
[![Edit black-voice-2z6y5](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/black-voice-2z6y5?fontsize=14&hidenavigation=1&theme=dark)
![error_message](https://user-images.githubusercontent.com/26010477/70700296-cf976b00-1cca-11ea-9c65-e2ba84d25d51.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

nodejs version v8.10.0
npm version 6.13.3
ubuntu/chrome

Please give me any advice. Thank you in advance :)

**Comment by bvaughn** [comment]
The bug you've reported does not reproduce in either of the Code Sandbox links you shared. The console just prints, "_SyntaxError {}_" after signing in and the page is blank.

<img width="499" alt="Screen Shot 2019-12-12 at 1 25 59 PM" src="https://user-images.githubusercontent.com/29597/70750259-f6619b80-1ce2-11ea-89ba-0d065954f805.png">

The React error above shows you the source of the problem though. For example, in `App.js` on line 98 - you are trying to render something that's `undefined`. That looks like the line you're rendering `ReactTable` on, which would suggest that your import isn't working.

You might try asking for help from the react-table authors or community, if they have a support forum. :smile:
