### ISSUE TITLE
Undefined value in a checkbox becomes an empty string

### ISSUE THREAD

**Issue by danoc** [facebook/react#17590]
Hello!

**Do you want to request a *feature* or report a *bug*?** 
Report a bug

**What is the current behavior?** 

When rendering a `input[type="checkbox"]`, ReactDOM adds a `value` attribute to the `input` element even if the `value` prop is `undefined`.

```js
ReactDOM.render(<input type="checkbox" value={undefined} />, el);
// renders as <input type="checkbox" value="" />, value is an empty string

ReactDOM.render(<input type="checkbox" />, el);
// renders as <input type="checkbox" />, value is browser default of "on"
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/react-checkbox-value-jwh7x

**What is the expected behavior?**

[A checkbox without a `value` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value) should default to `value="on"`. I would have expected React not to add the `value` attribute to a checkbox if `value={undefined}`. This would allow the checkbox to follow the default browser behavior.

I stumbled upon this after [adding an optional `value` prop to Thumbtack's `Checkbox` React component](https://github.com/thumbtack/thumbprint/pull/502). The seemingly backwards compatible PR broke at least one sever endpoint that was checking for the "truthyness" of the checkbox value. Before the PR, the checkbox value defaulted to `on`. After the PR, it became `""`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This should affect all browsers and OS's. I'm not sure which version of React this was introduced it, but it doesn't seem to be a recent regression. (Happy to dig in more here if needed.)

***

I think this happens because `ReactDOMInput.js` sets `node._wrapperState.initialValue` to `""` if the `value` prop is `undefined`:

https://github.com/facebook/react/blob/12c000412d05c4a6079b4f57f721a40b8cea374d/packages/react-dom/src/client/ReactDOMInput.js#L114-L122

Perhaps there should be a check here for `props.type` so that `defaultValue` remains `undefined` for checkboxes? I'd be happy to submit a PR if this is a bug. Thanks!

**Comment by Amagon96** [comment]
Working on it!

**Comment by danoc** [comment]
Hey @Amagon96, I'd recommend waiting a bit or taking a look at some of the issues marked as "[good first issue](https://github.com/facebook/react/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)". While I think this is a bug, it's possible that it's the expected behavior! 😄

**Comment by Amagon96** [comment]
@danoc got it, thanks man! n.n/

**Comment by EsTharian** [comment]
I'm sorry but it's not seem to be a bug. Because, undefined is parallel with null or empty string while rendering. Issue should be opened as requesting new feature and, I think, it will be a good feature for all props.
