### ISSUE TITLE
validateDOMNesting incorrectly validates <tr> - children of <table>

### ISSUE THREAD

**Issue by mukkurum** [facebook/react#17593]
**Do you want to request a *feature* or report a *bug*?**

bug.

**What is the current behavior?**

validateDOMNesting shows warning when`<tr>` used as a child of  `<table>`, after any `<caption>`, `<colgroup>` and `<thead>` but only if there no `<tbody>` are children of the `<table>`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/empty-rgb-s5x9w
In the console, you will see warning: `validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody> to your code to match the DOM tree generated by the browser.`

**What is the expected behavior?**

According to [`<tr>` definition from W3C](https://www.w3.org/TR/html52/tabular-data.html#the-tr-element),  warning should not be showed for the situation.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.12.0, Windows 10, 1909(64bit), Chrome 79.0.3945.79,

**Comment by mukkurum** [comment]
This is not a problem of React, because React just follows HTML Living Standard's Parsing HTML Rules. I'll close the issue.

**Comment by n0wak** [comment]
@mukkurum but the spec literally says a TR can be a child of TABLE

<img width="948" alt="Screen Shot 2021-03-21 at 16 52 28" src="https://user-images.githubusercontent.com/754821/111920518-d3857180-8a65-11eb-9825-194051083fd3.png">

<img width="965" alt="Screen Shot 2021-03-21 at 16 51 02" src="https://user-images.githubusercontent.com/754821/111920490-adf86800-8a65-11eb-8f90-d9fffc55a5a8.png">

**Comment by mukkurum** [comment]
> @mukkurum but the spec literally says a TR can be a child of TABLE
> 
> <img alt="Screen Shot 2021-03-21 at 16 52 28" width="948" src="https://user-images.githubusercontent.com/754821/111920518-d3857180-8a65-11eb-9825-194051083fd3.png">
> 
> <img alt="Screen Shot 2021-03-21 at 16 51 02" width="965" src="https://user-images.githubusercontent.com/754821/111920490-adf86800-8a65-11eb-8f90-d9fffc55a5a8.png">

Yes. As I said, it is problem of parsing html rules, not React's problem.
