### ISSUE TITLE
onContextMenu event does not get fired on iOS 13.1

### ISSUE THREAD

**Issue by Finomnis** [facebook/react#17596]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
onContextMenu event does not get fired on iOS 13.1 when long-pressing on an iPhone.

https://codesandbox.io/s/awesome-wilson-t1yy3

Clicking the gray rectangle should print 'onClick', which it does on all platforms I tested.
Long-pressing/right-clicking on the gray rectangle should print 'onContextMenu', which it does on windows and android, but not on iOS. Tested on both chrome and safari.

**What is the expected behavior?**
The expected behaviour on iOS is that long-pressing the gray rectangle should print 'onContextMenu'.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.12.0
iOS 13.1

**Comment by Finomnis** [comment]
Seens to not be a bug, instead, iOS seems to not fire 'contextmenu' events. It fires 'touchstart', 'touchend', 'touchmove' events instead.

Here is a workaround for people that have the same problem:
https://codesandbox.io/s/react-ios-oncontextmenu-bug-f34j1

**Comment by maradondt** [comment]
> Seens to not be a bug, instead, iOS seems to not fire 'contextmenu' events. It fires 'touchstart', 'touchend', 'touchmove' events instead.
> 
> Here is a workaround for people that have the same problem: https://codesandbox.io/s/react-ios-oncontextmenu-bug-f34j1

here is HOC I've created from this sandbox for fixing this issue
[withContextMenu](https://gist.github.com/maradondt/ddbf6536d967f29fe9790e8ceb3f419f)
