### ISSUE TITLE
[HMR] Waiting for update signal from WDS...

### ISSUE THREAD

**Issue by leantide** [facebook/react#17595]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
With react-scripts@3.3.0, `[HMR] Waiting for update signal from WDS...` is written to the console after running npm start.

**What is the expected behavior?**
No console statement is produced.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Observed in react-scripts@3.3.0 but not observed in react-scripts@3.2.0

**Comment by hristo-kanchev** [comment]
@leantide Please file this issue in the [`create-react-app`](https://github.com/facebook/create-react-app) repo. Thanks!

**Comment by leantide** [comment]
Thanks.

**Comment by leantide** [comment]
Trying to close this again. Didn't close properly. Weird.

**Comment by leantide** [comment]
Close again.
