### ISSUE TITLE
ReactFiberBeginWork: finishClassComponent: сheck `instance` before call of `instance.render`

### ISSUE THREAD

**Issue by vithar** [facebook/react#17597]
https://github.com/facebook/react/blob/b15bf36750ca4c4a5a09f2de76c5315ded1258d0/packages/react-reconciler/src/ReactFiberBeginWork.js#L845

In function `finishClassComponent` in some cases `const instance = workInProgress.stateNode` can be `undefined`.

So you need to check `instance` before call `instance.render()`

**Comment by aweary** [comment]
In what scenario is `instance` undefined here? Can you please share a code example that reproduces the problem?

**Comment by vithar** [comment]
I actually can't provide a code example. We have a huge service with hundreds of thousands visitors daily and client side error reporter.

One error is `undefined is not a function` without exact stacktrace, which points to `instance.render()` inside react.

**Comment by threepointone** [comment]
It’s hard to discuss this without an actual usecase and reproducing example. Happy to reopen if that’s provided.
