### ISSUE TITLE
Pattern for "onchange" callbacks

### ISSUE THREAD

**Issue by LeopoldLerch** [facebook/react#17607]
**What is the current behavior?**

I have the situation, where i have a component, which should call a callback-function given in props when something, in that case a state changes.

in classic class-components this would have happened in componentdidupdate and calling the onchange-function of the props.

However, in hooks i have a slight problem: 

I have thought of this:

`useEffect(() => {
 props.onchange(state)
}, [state]);`

However, this does not work. eslint forces me to also insert the onchange-method given from props to the dependencies. This, of course, would result in calling the onchange method, when the onchange-method given in props changes, which is not expected behaviour.

I have found a workaround, with wrapping the callback-function in a useref in another useeffect targeting and calling the ref.current in the useffect for the state. But this seems to me like a quite complicated and not as straightforward solution, like it was in class-components.

Are there any patterns for solving this?

**Comment by vkurchatkin** [comment]
> eslint forces me to also insert the onchange-method given from props to the dependencies.

It actually doesn't. You are free to ignore the warning, if you are sure that's what you want to do

**Comment by malerba118** [comment]
Your `useRef` solution is appropriate. If you want, you can abstract that behavior into a custom hook to make it a little cleaner

```tsx
function useLatest(value) {
    const ref = useRef(value);
    ref.current = value;
    return ref;
}

// Similar situation here where we don't want data change to restart the interval, 
// so we get the latest data inside of the useEffect callback via ref
function useIntervalLogger(data) {
  const dataRef = useLatest(data);

  useEffect(() => {
    const id = setInterval(() => {
      console.log(dataRef.current);
    }, 3000);
    return () => clearInterval(id);
  }, []);
}
```

https://github.com/malerba118/react-delta#uselatestvalue

**Comment by LeopoldLerch** [comment]
well, ignoring doesn´t really work. At least when AutoFix (on save in vscode) for eslint is enabled. Autofix is changing the code-behaviour in this case essentially. 

It is cool and very, very usefol for dependencies in eg usecallback or usememo, ..., where also the autifix-option is very helpful. But maybe this rule is not really working for useeffect, because it there as mentioned, when not working approropriate, it changes the behaviour of the code. In the other 2 functions, even if set not correct, an additional dependency would simply cause the function to be updated, as in opposite to useeffect, where it actually triggers the function to be called.

and the useref-version looks to me to like a workaround to fulfill the eslint-rules. 

If i (could) ignore the rule, might there be any side-effects, like calling in "old" version of the prop (like it could happen with usecallback)?

as the eslint-rules are announced on the hook-reference-pages, maybe this case should also be described as example. It can really cause troubles to developers and it is not obvious to have to do it that way, one has essentially to know it in advance. In my case i was just a few steps from switch back to a class-component.

Maybe react or the rules can find an easier way to get around this somehow?

**Comment by malerba118** [comment]
It is a huge issue that the autofix for exhaustive deps changes the functionality of code. I’ve noticed this as well and it’s very dangerous. I know it’s been mentioned before, for example here https://github.com/facebook/react/issues/15204

**Comment by LeopoldLerch** [comment]
From the notes of useEffect-description: 

> If you use this optimization, make sure the array includes all values from the component scope (such as props and state) that change over time and that are used by the effect. Otherwise, your code will reference stale values from previous renders. Learn more about how to deal with functions and what to do when the array values change too often.

[useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect)

According to this, the autofixer is even working correctly. It should be this way, otherwise there is no guarantee to use the actual values. 

Maybe the useEffect-hooks should be updated with a 3rd Parameter. So the first one is the function that is called, and the other 2 are an array of dependencies, one on which the function may be "recreated", and the second one with the props that would actually trigger the function to be executed. 

@gaearon , @wdoug, 
Is useeffect really working like that, what looks like a kind of useMemo and what do you think about separating the dependencies in useeffect (any maybe layouteffect) in "trigger" and "dependencies"? Cause actually the "trigger" is what is differing from memo/callback and obviously causing the troubles.

**Comment by LeopoldLerch** [comment]
Currently it seems, that useEffect is the same way as useMemo, the only difference seems to be, that useEffect is executed AFTER updating the dom, while useMemo is executed after runtime. 
But I do not see a real possibility to conditionally fireing an effect, like stated in the docs. Essentially the variables of state and props inside the effect dictate the conditions. 

That way i would be a fan of a optional second array of "trigger" props/states that can be given to the useEffect-hook.

I see a difference between the actual declaration of a new function for an effect (to avoid stale variables) and actually executing the function. I know this can be done by additionally wrapping in useref ,.... , but it might be easier and more straight-forward to provide this directly in useEffect

**Comment by LeopoldLerch** [comment]
My proposals can be directly  extended to useLayoutEffect of course, as they are equal in this regards
