### ISSUE TITLE
getDerivedStateFromProps not update state

### ISSUE THREAD

**Issue by binhit92** [facebook/react#17617]
I have problem when use getDerivedStateFromProps. This is my code 

```jsx
   static getDerivedStateFromProps(nextProps, prevState) {
    console.log('run here to rerender', nextProps.userInfo)
    let route = [];
    nextProps.userInfo.listtab.map((item, index) => {
      route.push({
        title_vi: item.name_vi,
        title_en: item.name_en,
        key: item.id.toString(),
        is_vip: item.is_vip_price,
        flagTab: index
      });
      console.log('Check data item shop:', item, route)
    });
    console.log("data rerender tabbar:", route)
    return { routes: route };
  }
```

With first console, i'm get good value and it is what i want. But when second and third console and "return" value i receive not nextProps, and state not change with new data

**Comment by Daniel15** [comment]
Change your `.map` call to `.forEach` and see if that fixes it? The code as-is will probably be removing everything from the `nextProps.userInfo.listtab` array as a result of that `map` call.

What's the output you're getting, and what's the output you're expecting?

**Comment by bvaughn** [comment]
It's not clear to me what the reported problem is here, and there isn't enough info provided to reproduce it either.

If all you're using `getDerivedState` for is to store a value that's mapped from an incoming prop- I suggest using memoization instead, as is covered by this [React JS blog post](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization).

That being said, there's no info in this bug report that we could use to diagnose why you're receiving unexpected values in `nextProps` so I'm going to close this issue. If you would like to provide more information about what's going wrong, and a Code Sandbox that we can run to reproduce the behavior, one of us can take a look.

Cheers!
