### ISSUE TITLE
How to setState after window.open finishes  loading?

### ISSUE THREAD

**Issue by MimoJSRepo** [facebook/react#17612]
I have two forms with two buttons,

FormA with Button A

FormB with Button B

When I click on Button A, I want to execute the following function:

```handleClick() {```

```window.open(window.location.href, '_self');```

   ```this.setState({ showformB: true })```

```}```

**The final goal is when I click Button B on FormB, the current browser tab should be closed using:**

```window.close()```

( Because we can not use window.close() unless same page is opened using window.open() )

but this.setState({ showformB: true })  is executed before the page finishes loading, thus, the state is lost before the page finishes loading.

So window.open has Asynchronous behaviour, I have tried many solutions like:

```const ww = window.open(window.location.href, '_self');```

```ww.onload = function() {this.setState({ showBForm: true });};```

or 

```ww.addEventListener('load', function() {{this.setState({ showBForm: true });}, true);```

And some other solutions, but they all seem absolete,

And there is no callback function for window.open().

Any idea how I can make this work?

Or at least a workaround to be able to close the tab when I click Button B

**Comment by rowanD72** [comment]
Have you tried to use setTimeout()? This way you can set a time on when the form will timeout so the next form can open .

**Comment by MimoJSRepo** [comment]
Thank you for your reply, I already tried this,
but if you put setTimeout , the page will reload already and it will not get into the point of executing the function inside setTimeout, and it will start executing component lifecycle again , like componentDidMount,  and the function that handles clicking will not be completely executed.

Actually , after thinking about it, it seems like I should probably change the whole approch for this problem, because after window.open the component will always reload , and you will loose control somehow , unless you add some check on page load :(

**Comment by vcanales** [comment]
This is not really a react problem, but a browser/javascript one. You might want to look into posting messages between windows:

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
