### ISSUE TITLE
How to use rxjs in reactjs components

### ISSUE THREAD

**Issue by leminhson2398** [facebook/react#17611]
Could anybody here please show me some ways to use rxjs in reactjs applications 
I initialise rxjs in useEffect() and clean all subscribtions up in useEffect() also. 
Here is the sample code for demonstration: https://stackblitz.com/edit/react-mk99mq

Thank you guys!

**Comment by ShegerKing** [comment]
rxjs lends itself nicely for react hooks state management.

**Comment by leminhson2398** [comment]
@ShegerKing, thank you for your answer!
I'm a beginner to rxjs, so i definitely need to bookmark your writing for later reference.
Have a nice day!
