### ISSUE TITLE
React Context Wrong Consumer Value

### ISSUE THREAD

**Issue by helabenkhalfallah** [facebook/react#17628]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Context provider contains the correct value but in the consumer I have the default value : 

(value = bddf, the correct)
![image](https://user-images.githubusercontent.com/1331451/70945061-a5400780-2054-11ea-9065-785d8d77b486.png)

(value = cdn, wrong value)
![image](https://user-images.githubusercontent.com/1331451/70945071-a8d38e80-2054-11ea-8ac6-da999749c598.png)

**Steps to reproduce**
I want to make a library that dynamically load the theme.
I used create context.

I create a simple API for this : 
https://github.com/helabenkhalfallah/react-sg-components/tree/master/packages/sg-ui-core/src

I imported this lib as dependencies on my components :
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/sg-button/src/lib/SGButton.jsx#L3

And inside storybook :
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/storybook/stories/sg-button/SGButtonStory.jsx#L3

However inside context I get always the default value.
When I inspect inside the provider I have the correct value but inside consumer I have the default value.

I tried also hooks but the same issue.

The idea I don’t want to pass to my components library the current ‘theme’ but each time the application started, it sets the context and components automatically consume that value.

**What is the expected behavior?**
Consumer components should have the same value as the provider.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`"react": "=16.12.0"`

Is this because I create an npm module for ThemeContext ?
I should have an npm package ThemeContext because many apps will consume it :( 

Thanks.

**Comment by bvaughn** [comment]
Can you please provide a repro case that's runnable on Code Sandbox or something. The code you linked to just shows a context consumer being rendered. I don't see anything actually rendering your provider, so the behavior you described would be expected.

**Comment by helabenkhalfallah** [comment]
Hello @bvaughn ,

Here is the provider : 
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/storybook/stories/sg-button/SGButtonStory.jsx#L19

Inside it I have my themed components : 
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/storybook/stories/sg-button/SGButtonStory.jsx#L23

I used a HOC to retrieve context : 
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/sg-button/src/lib/SGButton.jsx#L34

ThemeContext is an npm module.

Thanks.

**Comment by bvaughn** [comment]
Could you point me at a runnable example?

**Comment by helabenkhalfallah** [comment]
Yes in progress ;)

**Comment by helabenkhalfallah** [comment]
I found why, this is due to storybook, I get everything works perfectly without storybook, I created a separated project and import all dependencies. Thank you so much for your help @bvaughn 👍  :)
https://codesandbox.io/s/funny-pascal-w950v

**Comment by bvaughn** [comment]
Thanks for the update 👍
