### ISSUE TITLE
Lint rule for hooks report error for non hook function starting by `useXXX` 

### ISSUE THREAD

**Issue by aizerin** [facebook/react#17636]
Declaring non-hook function like:

```js
import { useWith, identity } from "ramda";

const test = useWith(Math.pow, [identity, identity]);
```

causes

```js
React Hook "useWith" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function.eslint(react-hooks/rules-of-hooks)
```

I'm using latest version of eslint-plugin-react-hooks `2.3.0`

It would be useful to have settings to override this regexp.

https://github.com/facebook/react/blob/36a6e29bb3eead85e3500ba7269cbcd55516a8fb/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L11-L20

I can make PR for it if you think that this is a good idea.

**Comment by vcanales** [comment]
In order to fix this, `RulesOfHooks` would have to be aware of actual valid hooks and not just the naming pattern for them. The question is: would keeping such a list in this repo be acceptable?

**Comment by gaearon** [comment]
Hooks rules rely on this convention, including for custom Hooks. We can't guess their names so we needed to squat some prefix that can reasonably be considered unique to Hooks. We tried to pick something that is both short enough and isn't used in the ecosystem widely at the same time. Unfortunately, there are a few false positive for `use` now, and this sucks for libraries that rely on it. But the whole Hooks convention falls apart if we can't reliably distinguish them at the build time. So a clash like this is the cost.

>There's also de problem of custom hooks, where that list would not be sufficient to tell hooks from non-hooks apart.

That is not just an additional problem — it is *the* reason for the convention. Validating known ones is insufficient for the rule to work at scale.

Arguably now that Hooks are commonplace, even without the linter, seeing `use` outside a component makes you wonder — is this a Hook? Is this a violation? So while it's unfortunate for other libraries, I think we can accept by now that within React ecosystem, `use` prefix has a semantic meaning now. As a workaround and to clarify the intent, you can do:

```js
import { useWith as ramdaUseWith, identity } from "ramda";
```

I know it's unfortunate but don't have a better option to offer. (Alternatively you can `// eslint-disable-next-line`.)

**Comment by mikestopcontinues** [comment]
How about rule config `{ignores: [...patterns]}` so that users can customize what they'd like to ignore. Doesn't seem fair to litter code with disable comments, especially when users are only likely to have a few functions they need ignored—and always every time they use them.

**Comment by apepper** [comment]
Prior to the introduction of React hooks there have been at least ~150 functions in public APIs of existing libraries¹, that started with the word `use`. Requiring every one of those libraries to comply with the `RulesOfHooks` does not seem practical to me.

Given there are several preexisting APIs of libraries released earlier to the introduction of hook it makes sense to me to add  a `{ignores: [...patterns]}` config to `eslint-plugin-react-hooks`.

___
_Footnotes_

¹ How did I compile this number?

* I took https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9fb6115f792915d1f749da263a5778e4f3601722 as a snap shot. That is the day before React Conf 2018, where React Hooks where publicly announced.
* I used `rg " use[A-Z][a-zA-Z]+\(" | wc -l` to count all lines, that most likely contains a reference to a function which starts with `use<Whatever>(`. It is not perfect and there are must likely false-positives and false-negatives. But it gives a rough number as a reference.

**Comment by goldhand** [comment]
Can anyone explain what is the purpose of identifying hooks with a `"use*"` prefix? Is it just for linting and coding conventions? I've read the docs a bit and it seems that it is the only reason. If so, I'm surprised that this was the solution that was decided... not that its a good place or time to debate that approach now—I'll just keep wondering how that happened. Maybe add a third Rule of Hooks: they must start with `use*` hehe 😝



@aizerin you can limit the blast radius of this issue a bit by using eslint "overrides" configurations:

```json
{
  "plugins": [
    "react-hooks",
  ],
  "overrides": [
    {
      "files": ["use*", "*.tsx"],
      "rules": {
        "react-hooks/rules-of-hooks": 2,
         "react-hooks/exhaustive-deps": 2,
       }
    }
  ]
}
```

I know it's not an amazing solution but its something in your control at least :)


Lots of open PRs out related with other ideas too:

* https://github.com/facebook/react/pull/20521
* https://github.com/facebook/react/pull/20183
* https://github.com/facebook/react/pull/20477
* https://github.com/facebook/react/pull/20513
* https://github.com/facebook/react/pull/20521
