### ISSUE TITLE
Src folder missing while running create-react-app command

### ISSUE THREAD

**Issue by mukulgupta977** [facebook/react#17634]
**Do you want to request a *feature* or report a *bug*?**
I guess its a Bug

**What is the current behavior?**
Files are missing while creating react project

Steps to reproduce.
Just run the the :-
"npx create-react-app my-app"

**What is the expected behavior?**
i guess it should produce node modules, public and src folder

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
NA

**Comment by threepointone** [comment]
Please file this issue at https://github.com/facebook/create-react-app/issues

**Comment by sabujavarnd** [comment]
Try to remove using npm uninstall -g create-react-app command and then try npx create-react-app <your-app-name>

**Comment by GSalah** [comment]
Hey, you need to install yarn first : 

$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - 
$ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
$ sudo apt update 
$ sudo apt install yarn 
$ npx create-react-app app_name

**Comment by gunjan45** [comment]
![git](https://user-images.githubusercontent.com/65484663/82139924-5d165280-9849-11ea-95fd-11c89ecf4c70.PNG)

while creating a new react project only node modules folder is getting created ..Rest of the folder are missing.
Even after running this command npx create-react-app my-app its not working

**Comment by PpYCha** [comment]
any update to fix this..  im getting this problem
