### ISSUE TITLE
DevTools copy operations don't work in Firefox

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#17652]
Attempting to copy a prop using the new context menu (#17608) prints the following error for Firefox:
> Error: Unable to copy. Perhaps it's not available in your browser?

Firefox itself _does_ support `document.execCommand('copy')` if it's within the context of an event handler, but it looks like this does not include events that originated within an extension.

Looks like this was also an issue for DevTools v3: https://github.com/facebook/react-devtools/issues/843

Under the hood we are using [`clipboard-js`](https://www.npmjs.com/package/clipboard-js) for this.

**Comment by zinoviev** [comment]
@bvaughn I used to work on https://github.com/facebook/react-devtools/pull/1037/files and as far as I remember it works for both Chrome and Firefox for me. Maybe I totaly worng about firefox, but I whould like to check this issue

**Comment by bvaughn** [comment]
@zinoviev It works under certain conditions, but not one where a click event in the *extension* tries to run `document.execCommand("copy")` in the *page*. I spoke with the Mozilla folks about this issue Friday, and they're at least aware of it. Not sure the exact path forward (although if you'd like to take a look and lend a hand, please do!)

I think in the meanwhile- I'm going to close this issue and roll it into #17681
