### ISSUE TITLE
React.memo breaks generic components argument type inference

### ISSUE THREAD

**Issue by SQReder** [facebook/react#17658]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Currently, React.memo breaks generic components type inference.

```tsx
interface Props<T> {
  value: T;
  setValue: (value: T) => void;
}

function GenericComponent<T>({ value }: Props<T>) {
  return <div>{value}</div>;
}

const MemoizedGenericComponent = memo(GenericComponent);

const App: React.FC = () => {
  const [value, setValue] = useState(0);
  return (
    <>
      <GenericComponent value={value} setValue={setValue} />
      <MemoizedGenericComponent value={value} setValue={setValue} />
    </>
  );
};
```

We have the following error: 
```
Error:(20, 47) TS2322: Type 'Dispatch<SetStateAction<number>>' is not assignable to type '(value: unknown) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'unknown' is not assignable to type 'SetStateAction<number>'.
      Type 'unknown' is not assignable to type '(prevState: number) => number'.
```

Demo repository:  https://github.com/SQReder/broken-memo/

**What is the expected behavior?**

Memoized component should have the same type inferring as an original component

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
"@types/react": "^16.9.0",
"@types/react-dom": "^16.9.0",
"react": "^16.12.0",
"react-dom": "^16.12.0",
"react-scripts": "3.3.0",
"typescript": "~3.7.2"
```

**Comment by aweary** [comment]
We don't currently maintain the TypeScript definitions. You should file in an issue [in the DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped).
