### ISSUE TITLE
optional chaining support in eslint-plugin

### ISSUE THREAD

**Issue by taneba** [facebook/react#17654]
**Do you want to request a *feature* or report a *bug*?**
I think it's a feature request.

**What is the current behavior?**
eslint-exhaustive-deps doesn't work clearly when dependencies are implemented with optional chaining.

Examples:

```
  React.useEffect(() => {
    console.log(res.data?.post.liked)
  }, [res.data])
```
This code causes waring with `React Hook React.useEffect has missing dependencies: 'post' and 'liked'. Either include them or remove the dependency array.eslint(react-hooks/exhaustive-deps)`

So work around is:

```
  React.useEffect(() => {
    if (res.data) {
      console.log(res.data.post.liked)
    }
  }, [res.data])
```

Interestingly, this code also works

```
  React.useEffect(() => {
    if (!res.data?.post) {
      return
    }
    const { post } = res.data
    console.log(res.data.post.liked)
  }, [res.data])
```

**What is the expected behavior?**
eslint-plugin handles optional chaining accurately and encourage us to write better code.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
  react: 16.8.3
  eslint-plugin-react: 7.15.1
  eslint-plugin-react-hooks: 2.3.0
```

**Comment by codemonkey800** [comment]
I'll spend some time looking into it :) I currently don't see any unit tests for optional chaining in `eslint-plugin-react-hooks`, so I'm guessing it was a use case that wasn't considered until now

**Comment by codemonkey800** [comment]
@taneba could you post your eslint config or create one that can reproduce the warning above?

**Comment by taneba** [comment]
@codemonkey800 
Thank you for taking your time, I tried to create repro by CRA and it actually works fine.

After investigating, it turned out that it is because of versioning of @typescript-eslint/parser or @typescript-eslint/eslint-plugin. Mine was @2.6.1 for both, and latest CRA's was @2.10.0, there seems to be a lot of updates around optional-chaining between these versions.
https://github.com/typescript-eslint/typescript-eslint/releases
