### ISSUE TITLE
Wouldn't it be cool if className could inject an object into classSet?

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#1766]
Sort of a stray thought, but what if className could pass an object to the `classSet` addon?

```javascript
render() {
	return (
		<div className={{ message: true, 'is-active': this.state.isActive }}>
			{ this.props.message }
		</div>
	)
}
```

**Comment by chenglou** [comment]
Closing this since we're deprecating `classSet` (#2910). The new alloc-free version lives at https://github.com/petehunt/react-classset

**Comment by nhunzaker** [comment]
Fantastic!
