### ISSUE TITLE
After add extension, Not getting react developer tools functionality in chrome 

### ISSUE THREAD

**Issue by ajaysharma91** [facebook/react#17676]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by bvaughn** [comment]
There's not enough info here for us to help so I'm going to close this. I you can provide more info, I'll be happy to re-open and look into it though.

The info we would need:
* Which browser (name and version) are you using
* Which website(s) is React DevTools not working for
* What do you mean by "not getting functionality" 
* Are there any JavaScript errors in your console
