### ISSUE TITLE
react dangerouslySetInnerHTML very slowly in newest chrome 

### ISSUE THREAD

**Issue by brickspert** [facebook/react#17674]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`dangerouslySetInnerHTML` make website so slowly, you can try to select any text in this demo:https://codesandbox.io/s/hardcore-chatelet-v83z1

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

demo:https://codesandbox.io/s/hardcore-chatelet-v83z1

**What is the expected behavior?**

Smooth operation 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

mac chrome 79.0.3945.88
it work fine in old chrome version or safari.
maybe it's chrome’s problem?

**Comment by kunukn** [comment]
It is also slow without using React

Code:
https://codesandbox.io/s/pre-tag-selecting-tag-is-slow-q9vgt

Demo:
https://v83z1.csb.app/

It seems to be related to using a `pre` tag. If changed to a `p` tag, then it runs faster.
If I use Firefox, then it works as expected.

Maybe file a bug-report to the Chrome team?

**Comment by brickspert** [comment]
> It is also slow without using React
> 
> Code:
> https://codesandbox.io/s/pre-tag-selecting-tag-is-slow-q9vgt
> 
> Demo:
> https://v83z1.csb.app/
> 
> It seems to be related to using a `pre` tag. If changed to a `p` tag, then it runs faster.
> If I use Firefox, then it works as expected.
> 
> Maybe file a bug-report to the Chrome team?

Thank you for your replay~
I have report a bug to chrome: https://support.google.com/chrome/thread/23344225?hl=en

**Comment by aweary** [comment]
Closing since this is not a React issue.
