### ISSUE TITLE
Feature request - Enhance JSX syntax-compilation to basic hooks and state management

### ISSUE THREAD

**Issue by carpben** [facebook/react#17685]
Not long ago I have been introduced to Svelte, and was impressed by the ability to write less source code, less implementation details, and use reactive values easily. However, I wondered if to achieve this, another higher language was really necessary. For me, the ability to use JS freely is valueable. I wonder, can we improve developer experience in such a way and remain in JS? 

## General Proposal
JSX introduced an elegant syntax-compilation solution. 
```jsx
<element prop="value">child</element>
```
Compiles to: 
```js
React.createElement("element", {prop:"value", children:"child"})
```
This solution allows us to enjoy both worlds - stay in JS, yet use dedicated syntax which makes our code easier to read and write. My suggestion is to extend this (syntax-compilation) pattern to the basic hooks, and state management in React. User will be able to opt-in to easy to use compilation solutions, by using dedicated syntax. 

Hooks are ideal candidates: 
1. They come with non trivial constrainsts (Returned value depends on execution order, so they must be at the top level). With the use of a dedicated syntax, they can be grasped and treated as different from a regular function call.  
2. Optimizing is more difficult - Optimizing for performance requires knowledge and attention to implementation details. This includes: React.memo, useCallback, useMemo, and passing dependencies. It requires more code, and is somewhat more [bug prone](https://stackoverflow.com/questions/53070970/infinite-loop-in-useeffect).

Another ideal candidate is state management, which comes with it's own necessary contraints. Most noteably is that updating state should be done immutably. While this is essential in React, it could also be a burden on the developer, and is bug prone. I think this as well could be elegently solved with compilation. 

## Proposal Details 
Some of the ideas I will present might be contraversial, but they do demonstrate the general proposal, and demonstrate a few possible directions. 
Proposal includes the following: 

1. A dedicated sign for state
2. A dedicated sign for reactive-memoized values (which change if, and only if, dependencies change.)
3. A dedicated sign for effects. 
4. In JSX elements support shorthand attribute assignment (similar to ES6 Object shorthand property names)

I'll demonstrate what it could look like, with this simple [Complete and Tell todo app](https://complete-and-share.stackblitz.io).
```jsx
const TasksApp = () => {
	const [tasks, setTasks] = useState(initialTasks)
	const [competitionStatus, setcompetitionStatus] = useState([])

	const addTask = useCallback(
		(text) => setTasks( tasks => [{text, completed: false, id:+ new Date()}, ...tasks]), 
		[]
	)

	const toggleCompleted = useCallback(
		(id) => setTasks( 
			tasks => tasks.map( 
				task => (task.id!=id)? task : {...task, completed: !task.completed}
			)
		), 
		[]
	)

	const completedTasks = useMemo(
		()=>tasks.reduce(
			(accum, task) => accum+task.completed,
			0
		), 
		[tasks]
	)

	useEffect(
		() => {
			const updateCompetition = () => {
				const status = fetchCompetition(completedTasks)
				setcompetitionStatus(status)
			}
			updateCompetition()
			const interval = setInterval(updateCompetition, 10000)
			return () => clearInterval(interval)
		}, 
		[completedTasks]
	)

	return (
		<>
			<h1>Complete and share</h1>

			<Competition competitionStatus={competitionStatus} />
			<InviteFriend />

			<SelfStats completedTasks={completedTasks} />
			<AddTask addTask={addTask}/>
			<TaskList tasks={tasks} toggleCompleted={toggleCompleted} />
		</>
	)
}
```
I'll now write the same code, but relay on syntax-compilation to solve the challenges I metnioned above. I'll use `#` as a sign for state, `$` as a sign for memoization, and `%` as a sign for effects. 
```jsx
const TasksApp = () => {
	# tasks = initialTasks
	# competitionStatus = []

	$ addTask = (text) => tasks.push({text, completed: false, id:+ new Date()})

	$ toggleCompleted = (id) => tasks[id].completed = !tasks[id].completed

	$ completedTasks = ()=>tasks.reduce(
		(accum, task) => accum+task.completed,
		0
	)

	%	const updateCompetition = () => {
			const status = fetchCompetition(completedTasks)
			competitionStatus.set(status)
		}
		updateCompetition()
		const interval = setInterval(updateCompetition, 10000)
		%	clearInterval(interval)

	return (
		<>
			<h1>Complete and share</h1>

			<Competition competitionStatus />
			<InviteFriend />

			<SelfStats completedTasks />
			<AddTask addTask/>
			<TaskList tasks toggleCompleted />
		</>
	)
}
```
This component is equivelent, and will compile to the same code, as the original TaskApp above it. 

Let's look at 
```jsx
$ toggleCompleted = (id) => tasks[id].completed = !tasks[id].completed
```
The compiler should recognize that tasks is a state thing, and convert the mutating code to a state updating code. 
```jsx
$ toggleCompleted = (id) => setTasks( 
	tasks => tasks.map( 
		task => (task.id!=id)? task : {...task, completed: !task.completed}
	)
)
```
It should also recognize that toggleCompleted should be memoized. Looking at the code, it doesn't relay on values that are not passed as parameters, so there are no dependencies. It can complete the convertion of the function to the final code: 
```jsx
const toggleCompleted = useCallback(
	(id) => setTasks( 
		tasks => tasks.map( 
			task => (task.id!=id)? task : {...task, completed: !task.completed}
		)
	), 
	[]
)
```
Memoizing this function with `useCallback` requires technical and repetitive work. It is somewhat of a burden on the developer, and a compiler might just be better at it. 

As for updating state in this example, for deep nested state updates this approach will yield greater benefits. Immutability wise, it is somewhat similar to Immer. Code could be written mutably, and have an immutable effect. 

Lets look at another component: 
```jsx
const AddTask = ({addTask}) => {
	const [value, setValue] = useState("")

	const changeHandler = useCallback(
		(e) => setValue(e.target.value), 
		[]
	)
	
	const onClick = useCallback(
		()=>{
			addTask(value)
			setValue("")
		}, 
		[value, addTask]
	)

	return (
		<div className="add-task">
			<div>Add Task</div>
			<input value={value} onChange={changeHandler} /> 
			<button onClick={onClick}>Add</button> 
		</div>
	)
}

export default React.memo(AddTask)
```
In the suggested syntax: 
```jsx
$ AddTask = ({addTask}) => {
	# value = ""

	$ onClick = ()=>{
		addTask(value)
		value = ""
	}

	return (
		<div className="add-task">
			<div>Add Task</div>
			<input #value /> 
			<button onClick>Add</button> 
		</div>
	)
}

export default AddTask
``` 
In these examples all memoised values share the same syntax. Based on the memoized object, the compiler can wrap the code in `React.memo`, `useCallback` or `useMemo`. 

These examples also demonstrate shorthand attribute/props assignment in JSX elements. This makes it easier to pass props, which is important because it makes reusing components easier. Further more, it makes JSX more aligned with JS, since JS now supports this feature for objects. 

`<input #value />` demonstrates an option to bind state value to an input's value.

Using the suggested syntax in this app, **components were written in 29% less source code.** 

## Summery
Developer will be able to use JS as before, but could also opt to use such compilation solutions. The above solutions provide the following benefits: 

1. In a sense it's more declerative - User can declare a value to be reactive-memoized, or state-immutable, without worrying how it is implemented. 
2. (Once a programmer is familiar with the syntax) Less overhead for reading and writting.
3. All of the above probably means app will be less bug prone.

**Comment by bvaughn** [comment]
Are you ware of our RFC process? This is the sort of proposal that should definitely go through that process.

I do want to point out that using `useCallback` for event handlers attached to host components is unnecessary because of how React's event system works. It won't make any performance improvement to pass a stable event handler function to an e.g. DIV element, and `useCallback` actually adds a little overhead- so a net loss.

I think this issue should be closed and re-opened as an RFC in the RFC repo:
https://github.com/reactjs/rfcs

**Comment by carpben** [comment]
I'll close this and open an RFC instead. 
Yeah, memoising an event handler as I did doesn't make much sense. Also optimizing the rendering of a DIV is redundant. 
Thanks @bvaughn.

**Comment by carpben** [comment]
@bvaughn , An RFC requires a rewrite of this proposal, and there are a few conceptual changes I wanted to make anyway. I'll hopefully submit a PR of a RFC by the end of this week.
