### ISSUE TITLE
npx create-react-app myapp -> Not Working, src and public folders are not being created

### ISSUE THREAD

**Issue by thesaihan** [facebook/react#17694]
when I use `npx create-react-app myapp`, all required files and directories are not being created, only `package.json`,  `package-lock.json`, and `node_modules` are created automatically. 
Please help, am I missing something?
It also says that:
> A template was not provided. This is likely because you're using an outdated version of create-react-app.
Please note that global installs of create-react-app are no longer supported.<

should I update the package globally? My node version is `v10.15.0`, `npm` and `npx` versions are both `6.4.1`, and `create-react-app` version is `3.1.2`

**Comment by bvaughn** [comment]
Please file this issue on the create-react-app repo:
https://github.com/facebook/create-react-app

(Check to make sure it hasn't already been filed though!) 🙂
