### ISSUE TITLE
Opinions on Ionic Reac

### ISSUE THREAD

**Issue by Luzmario1708** [facebook/react#17697]
Hello, 

Feasibility of making a project in ionic reaction.

I am interested in knowing more about Ionic react.

And I would like to know if it is advisable to do a project with Ionic React.

How scalable the project would be.

And you can use all the tools that have both ionic and rea, example: camera, maps, notifications, routes, among others.

I appreciate if you can advise me.

Thank you

**Comment by bvaughn** [comment]
This seems like a good question for Reddit ([r/reactnative/](https://www.reddit.com/r/reactnative/) or maybe [/r/reactjs/](https://www.reddit.com/r/reactjs/)). We don't have an official stance on a framework like Ionic, so we can't offer advice on whether it would be appropriate for your project. Sorry!
