### ISSUE TITLE
why has an umd folder in the React package

### ISSUE THREAD

**Issue by MuYunyun** [facebook/react#17699]
I wonder why is there an `UMD folder` in the React package. 

![image](https://user-images.githubusercontent.com/19354791/71393724-e8980880-2648-11ea-8d41-fefff4382b82.png)

Should the UMD folder be uploaded to CDN and then use it through `<script>`? And it seems there is no extra effect about the UMD file. And if so, why not remove the UMD file from the React package to increase the download speed of the React NPM Package.

**Comment by zxh19890103** [comment]
`umd` is short for **Universal Module Define**.

Why is it here?

You can USE it as any type of `MODULE SPECIFIC`, such as `COMMON.JS`, `AMD`, `ES6` & etc.

**Comment by MuYunyun** [comment]
get it.
