### ISSUE TITLE
[strict mode] Disposed dispatch affecting other instance

### ISSUE THREAD

**Issue by Andarist** [facebook/react#17709]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Disposed `dispatch`/`setState` (from not committed component) is affecting another instance (the committed one). Actually, maybe my reasoning is wrong here - and you don't actually dispose of the first one, but rather only "clear its memory cells" (state and refs)? Conceptually it looks like disposing (and from what I understand it mimics exactly this in StrictMode - so we can catch bugs early).

**Repro case**

https://codesandbox.io/s/peaceful-meadow-wg42k

**What is the expected behavior?**

I would expect to receive a warning from React about using disposed dispatch.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The current version, also tested a few of previous versions - all were affected.

**Comment by bvaughn** [comment]
This repro shows a side effect (`setTimeout`) in render, which is explicitly not allowed (and is one of the things double `StrictMode` rendering is intended to catch and prevent:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

So the case that you're showing is not one that's supported. :smile:

**Comment by Andarist** [comment]
I know the repro case is showing an anti pattern - but thats somewhat the point. I was expecting StrictMode to inform me about it - notice how this set timeout fires conceptually for not-existing component but affects the existing one.
