### ISSUE TITLE
Don't add top-level events for uncontrolled inputs

### ISSUE THREAD

**Issue by CG-Stack** [facebook/react#17706]
The document-wide handlers for native events that perform synthetic event dispatch execute in 0.2-0.7 milliseconds on my machine. I realize this doesn't seem like much time, but we're really trying to shave off any non-essential source of latency for typing and cursor movement in Atom, and every little bit helps. Disabling synthetic events on keydown and textinput is saving about 1ms of latency for a keystroke.

In our fork, I've added the ability to add a reactSkipEventDispatch property to the native event to opt out of synthetic dispatch, but I'd be interested in a more official mechanism for opting out of this feature for certain event types. Even better, perhaps React could maintain a cache of what event types are actually being listened for and bail out as soon as possible if handling an event.

**Comment by bvaughn** [comment]
The current event system is pretty complicated, and changes to it require a nuanced understanding of why it works the way it does. Any additions to the API would probably need to go through [our RFC process](https://github.com/reactjs/rfcs#what-the-process-is).
