### ISSUE TITLE
React Js Context Api(invariant violation) element type is invalid

### ISSUE THREAD

**Issue by 16isaac89** [facebook/react#17702]
Am trying to setup Context Api for my project but i get an error that i cannot wrap my head around, i have two files one for the data context,
createDataContext is the name of the file
import React, {useReducer} from 'react';

export default (reducer, actions, defaultValue) => {

    const Context = React.createContext();
    const Provider = ({children}) => {
        const [state, dispatch] = useReducer(reducer, defaultValue);
   
    const boundActions = {};
    for (let key in actions){
        boundActions [key] = actions[key](dispatch);
    }
    return(
        <Context.Provider value={{state, ...boundActions}}>
            { children }
        </Context.Provider>
    );
};
return(Context, Provider);
};

AuthContext js file
import createDataContext from './createDataContext';

const authReducer = (state, action) => {
    switch(action.type){
        default:
            return state;
    }
};
export const {Provider, Context} = createDataContext(
    authReducer,
    {},
    { isSignedIn: false }
);

And the Consumer App which has a switch navigator
App.js
import React from 'react';
import {createAppContainer, createSwitchNavigator} from 'react-navigation';
import {createStackNavigator} from 'react-navigation-stack';
import { createDrawerNavigator } from 'react-navigation-drawer';
import Login from './src/screens/Login';
import Register from './src/screens/Register';
import Account from './src/screens/Account';
import  Earnings from './src/screens/Earnings';
import Scheduledrides from './src/screens/Scheduledrides';
import Home from './src/screens/Home';
import {Provider } from './src/Context/AuthContext';

const Screens = createSwitchNavigator({
  loginFlow: createStackNavigator({
    Login: Login,
    Register:Register,
  }),

  mainFlow: createDrawerNavigator({
    Home: Home,
    Account: Account,
    Earnings: Earnings,
    Scheduledrides:  Scheduledrides,   
  }),
  

});
 const App =  createAppContainer(Screens);

 
 export default () => {
  return(
    <Provider >
      <App />
    </Provider>
  );
};
Below is the error i get, thanks in advance
![Capture](https://user-images.githubusercontent.com/23630466/71403903-3a896000-2642-11ea-9956-87ed7c3efa0c.PNG)

**Comment by bvaughn** [comment]
This error is showing that some component you've imported is not a valid React component, but is actually `undefined`. This likely means that you have a **bad import statement**.

Without a repro case, we can't help with this question. For example, the error shows a component `withExpoRoot` as the top location, but this name isn't even referenced in the partial code snippet you've shown above.

Given that this seems to be a React Native issue, I would suggest you open an issue on the React Native repository instead:
https://github.com/facebook/react-native

I also suggest that you provide more context (either more code, or better yet- a link to your project source) so people that are looking can see the code where the problem actually occurs.

Cheers and good luck!
