### ISSUE TITLE
How can i change react umd version  in node_modules? 

### ISSUE THREAD

**Issue by Louis-Chen** [facebook/react#17710]
i saw react package have `cjs` and `umd` folder
and `index.js` in react output `cjs` version 

so if i want to use `umd` how can i change?

![image](https://user-images.githubusercontent.com/20965813/71428891-b0eb9800-26fe-11ea-8887-691e69203855.png)

**Comment by bvaughn** [comment]
You require the file directly, as mentioned in the docs:
```html
<script src="https://unpkg.com/react@16/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js" crossorigin></script>
```
