### ISSUE TITLE
 Duplicate identifier 'LibraryManagedAttributes

### ISSUE THREAD

**Issue by lvybriage** [facebook/react#17711]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
error message: 
`/node_modules/@types/react-router/node_modules/@types/react/index.d.ts(2314,14):
TS2300: Duplicate identifier 'LibraryManagedAttributes'.`

**What is the expected behavior?**
正常编译
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
package.json:
`"react": "^16.8.6",`
`"@types/react": "^16.8.6",`

yarn.lock file:
`"@types/react@^16.8.6":
  version "16.9.17"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.9.17.tgz#58f0cc0e9ec2425d1441dd7b623421a867aa253e"
  integrity sha512-UP27In4fp4sWF5JgyV6pwVPAQM83Fj76JOcg02X5BZcpSu5Wx+fP9RMqc2v0ssBoQIFvD5JdKY41gjJJKmw6Bg==
  dependencies:
    "@types/prop-types" "*"
    csstype "^2.2.0"`

**Comment by oriSomething** [comment]
It's not related to React, it related to DefinitelyTyped, but not really theme.
There is a bug with yarn that sometimes causes duplications of `@types/react` in the lock file, you can manually remove the definition or the lock file and install

**Comment by lvybriage** [comment]
@oriSomething 
Hi, oriSomething~ Thanks for replying this question. I try to delete the `yarn.lock` file and `node_modules`. And then `yarn`. But it doesn't work.

**Comment by lvybriage** [comment]
Hi, @oriSomething 
Thanks for replying this question. I try to delete the `yarn.lock` file and `node_modules`. And then `yarn`. But it doesn't work.

**Comment by oriSomething** [comment]
So it means you have some how duplications of `@types/react` in dependencies you can try search why. Or try [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to unify the dependency

**Comment by lvybriage** [comment]
> So it means you have some how duplications of `@types/react` in dependencies you can try search why. Or try [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to unify the dependency

Ok. Thanks!
