### ISSUE TITLE
The components tab don't show up in Chrome DevTools panel

### ISSUE THREAD

**Issue by KsRyY** [facebook/react#17725]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The react components tab never shows up in my Chrome DevTools panel, even the React DevTools extension report that it detects React on the current page. (Sometimes it even don't report it at all)

When I use preact and the provided React DevTools connector `preact/debug`, the extension reports that the page is using a development build of React.

When I uses React directly, the React DevTools don't report anything at all.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:** [an github repo](https://github.com/KsRyY/MyLittlePony)

**What is the expected behavior?**
The components tab will show up in the Chrome DevTools panel

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** Preact X, compatible with the current latest version of React. (I also tested it with the current version of React)

**Comment by bvaughn** [comment]
Seems like you may have omitted a pretty important piece of info?

> **which browser / OS are affected by this issue?**

As I haven't heard anyone else reporting this, I'm guessing it may be something special about your browser/OS *or* the combination of extensions you have installed.

* Are there any errors in the console?
* What if you detach the main console and open a second console to see if there are errors from the extension itself?
* If you're using Chrome, have you checked to make sure the Components tab just isn't hidden?

<img width="390" alt="Screen Shot 2019-12-28 at 9 27 05 AM" src="https://user-images.githubusercontent.com/29597/71547375-3d42c880-2954-11ea-9680-7e1af9c66327.png">

**Comment by KsRyY** [comment]
I'm using Chrome 79 on a Windows 10 2004 build 19041.1
The host of my development server is Ubuntu 19.04 over WSL

**Comment by KsRyY** [comment]
The React devTools extension reports:
![image](https://user-images.githubusercontent.com/25174488/71551086-3df16280-2a19-11ea-96e8-0c2a1ef20751.png)

But nothing showed up:
![image](https://user-images.githubusercontent.com/25174488/71551089-4e094200-2a19-11ea-91ae-10ed8fba6271.png)
![image](https://user-images.githubusercontent.com/25174488/71551093-582b4080-2a19-11ea-8af5-14dfb9fe94d5.png)

**Comment by KsRyY** [comment]
By the way I'm using Preact X and its React DevTools connecter `preact/debug` here

**Comment by KsRyY** [comment]
And when it's on the [React document site](https://reactjs.org) it works all fine.

**Comment by KsRyY** [comment]
Um... I find the bug... The Preact DevTools connector don't support my version of React DevTools...
I thought I should report that problem to the Preact developers. Sorry for that inconvenience.

**Comment by bvaughn** [comment]
> By the way I'm using Preact X and its React DevTools connecter `preact/debug` here

> And when it's on the [React document site](https://reactjs.org) it works all fine.

Ah! This is a pretty important detail 😄

React DevTools doesn't officially support Preact, although I try to make it as easy as possible for *Preact to support React DevTools!* 🙂 This sounds like something they'll have to fix on their end. Thanks for the follow up!
