### ISSUE TITLE
Use React.cloneElement return undefine

### ISSUE THREAD

**Issue by lvybriage** [facebook/react#17722]
**Do you want to request a *feature* or report a *bug*?**
maybe a bug
**What is the current behavior?**

I use React.cloneElement to render router components and transfer `props` to them.
But in router page, this.props members such as interval is `undefine`.

```
const reactPropsChildren = React.Children.map(this.props.children, child =>
            React.cloneElement(
                child as React.ReactElement<any>, {
                interval,
                columnList, changeColumn: this.changeColumn,
                experimentUpdateBroadcast,
                trialsUpdateBroadcast,
                metricGraphMode, changeMetricGraphMode: this.changeMetricGraphMode
            })
        );
```

my router file is:
```
<BrowserRouter>
      <Switch>
        <App>
          <Route path="/oview" component={Overview} ></Route>
          <Route path="/detail" component={TrialsDetail}></Route>
          <Redirect to="/oview" />
        </App>
      </Switch>
    </BrowserRouter>
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
this.props members are not undefine.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
"react-router-dom": "^5.1.2",
"react": "^16.8.6",
"react-dom": "^16.8.6",
"@types/react": "16.4.17",
```

**Comment by bvaughn** [comment]
> But in router page, this.props members such as interval is undefine.

Without a full example, it's hard to tell what's going on here, but I'm going to guess it's because you're passing an undefined value for `interval`.

Your example:
```js
React.cloneElement(child, {
  interval, // What is interval? Is it in scope? Apparently not.
});
```

What I assume you should be doing instead:
```js
React.cloneElement(child, {
  interval: this.props.interval, // Presumably something like this
});
```
