### ISSUE TITLE
[Hooks] useEffect is behaving little odd

### ISSUE THREAD

**Issue by ssahaxd** [facebook/react#17745]
I want to convert my class component to a functional component so I am trying to mimic the behavior of the `componentDidMount()` and `componentWillUnmount()` using `useEffect()` hook. I am using Redux to store my state.

***My class Implementaion of `componentDidMount()` and `componentWillUnmount()`***
![image](https://user-images.githubusercontent.com/11327529/71596920-4952a400-2b67-11ea-978b-7959a0f421e3.png)

***My `useEffect()` Implementaion***
![image](https://user-images.githubusercontent.com/11327529/71596994-8e76d600-2b67-11ea-8f0b-90881bfa47f0.png)

My app basically shows a list of expenses in a table which are stored in the firebase database. I'm using a `loading` flag to show a spinner while fetching data from firebase. but with my current implementation if I don't set the flag conditionally every time firebase sends me data or I add data to firebase the `loading` flag is overwritten to false.
so ***I'm checking if the loading flag is true then only I will set it false otherwise not***.
`loading` flag behaving as expected in the class implementation but in functional component implementation after setting it true using `setLoadingTrue()` I'm seeing it `false` in the logs although the redux dev tools saying that the variable is set `true`.
![image](https://user-images.githubusercontent.com/11327529/71597446-29bc7b00-2b69-11ea-8354-668b2b3187ef.png)
![image](https://user-images.githubusercontent.com/11327529/71597474-48bb0d00-2b69-11ea-8cab-b5482292f6ed.png)

is there any better way to do the same?

**Comment by vkurchatkin** [comment]
You can't really observe current props in react that way, they are essentially immutable. It can be done like this:

```js
function Component({ prop }) {
  const propRef = React.useRef();
  propRef.current = prop;

   React.useEffect(() => {
      setTimeout(() => {
         console.log(propRef.current) // always get the prop from the most recent render
      }, 1000);
   }, []);
}
```
