### ISSUE TITLE
I can't get the latest status value in the initialization method

### ISSUE THREAD

**Issue by lmxyjy** [facebook/react#17748]
I try to get the latest state value in the initialization method, but the result is not satisfactory。
All this happens in function components。

1.react version is 16.12.0；
2.react-dom version is 16.12.0；

this is my demo code :

```
import React,{useState,useEffect} from 'react';

const App=()=>{
	/*button click*/
	const btnClick = ()=>{
		console.log("initButton getting state is====>",nowState); //can't get now state ,all is init value
	}
	/*init a button*/ 
	const initTitle = ()=>{
		return (
			<button onClick={btnClick}>click</button>
		)
	}
	const [title, settitle] = useState();

	/*now state*/
	const [nowState, setNowState] = useState(0);
	console.log("now state is====>",nowState);

	useEffect(()=>{
		settitle(initTitle());
	},[])

	return (
		<>
			{title}
			<button onClick={()=>setNowState(nowState + 1)}>change now state</button>
		</>
	);
}

export default App;
```

**Comment by yadejo** [comment]
You are calling `btnClick` from your `title`. The reason it doesn't receive state updates is that you only create your `title` element once and then put it in state. 

What's the reason for putting `title` in state?

**Comment by lmxyjy** [comment]
Thank you for your reply. I understand the reason now. You're right。I used `useRef` to fulfill this requirement.

**Comment by bvaughn** [comment]
Closing as answered.
