### ISSUE TITLE
ReactDOM.createRoot does not exist

### ISSUE THREAD

**Issue by Kajmeh** [facebook/react#17747]
Hi,

I am trying the new react experimental in a very simple existing app we had. Although I have changed the react versions in my package.json but it seems it doesn't recognize ReactDOM.createRoot. 

> Property 'createRoot' does not exist on type 'typeof import("D:/repo/app/packages/experiences/home/node_modules/@types/react-dom/index")'. 

Any ideas how to resolve this? Thank you in advance.

`"dependencies": {
        "@types/jest": "24.0.17",
        "@types/node": "12.7.1",
        "@types/react": "16.9.1",
        "@types/react-dom": "16.8.5",
        "node-sass": "^4.12.0",
        "react": "experimental",
        "react-dom": "experimental",
        "react-scripts": "3.1.2",
        "typescript": "3.5.3"
    },
    "scripts": {
        "start": "react-app-rewired start",
        "build": "react-app-rewired build",
        "disabled:test": "react-app-rewired test",
        "eject": "react-scripts eject"
    },
    "eslintConfig": {
        "extends": "react-app",
        "rules": {
            "@typescript-eslint/no-angle-bracket-type-assertion": "off"
        }
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "devDependencies": {
        "@babel/core": "^7.7.7",
        "@teamsupercell/typings-for-css-modules-loader": "^2.1.0",
        "css-loader": "^3.2.0",
        "customize-cra": "^0.8.0",
        "react-app-rewired": "^2.1.4",
        "worker-loader": "2.0.0"
    }
}
`

**Comment by bvaughn** [comment]
This sounds like a TypeScript question. We don't manage those types. They're managed by the TypeScript community via the DefinitelyTyped repo.

For the time being, the `createRoot` API is experimental and may change before a final, stable release. It will likely not be added to the TypeScript types until it's at least close to final release. If you want to use it before then, you'll likely need to suppress the warning.

Looks like you can perhaps track the overall progress here:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36475
