### ISSUE TITLE
Implement a method in serviceWorker.js file for skipWaiting in service worker life cycle

### ISSUE THREAD

**Issue by saeedhemmati** [facebook/react#17755]
I have propose for implementing a method in CRA that skip waiting for service-worker after new update in app detected by it

**Comment by bvaughn** [comment]
CRA has a different repository and issue tracker and is mostly maintained by a different set of people :smile: If you have a proposal, I suggest you write up an issue that outlines it there: https://github.com/facebook/create-react-app/
