### ISSUE TITLE
Unexpected different DOM updating behavior

### ISSUE THREAD

**Issue by vjeux** [facebook/react#17753]
**Do you want to request a *feature* or report a *bug*?**

A bug, I guess. Unclear

**What is the current behavior?**

On mouse move on a canvas element, I'm re-rendering the entire React tree, which includes this canvas and a few label + radio inputs. Depending on how the labels are added to the virtual tree, the browser selection gets weird.

When we use
```js
<ElementOption />
```

then, whenever we start dragging on the canvas, the text above gets highlighted which is annoying. Note that on the Chrome dev tools, the label gets updated on every mouse move.

![ezgif-3-6b46fe8cddc7](https://user-images.githubusercontent.com/197597/71649526-6f418b00-2cc4-11ea-9341-776d8373a0e2.gif)

but, when we render without a component:
```js
{ElementOption()}
```
then the label doesn't get updated and there's no bad selection behavior.
![ezgif-3-c743795e5f15](https://user-images.githubusercontent.com/197597/71649512-4ae5ae80-2cc4-11ea-8c53-9686e2bbb6dc.gif)

Here's the codesandbox with the full code: https://codesandbox.io/s/frosty-silence-etx23

**What is the expected behavior?**

I'm not really sure to be honest. I'm not exactly sure why the label gets updated when rendered through a component, since there should be no changes.

My educated guess is that once the update gets removed, then the text selection behavior won't be an issue anymore.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.2, Chrome, MacOS

**Comment by jddxf** [comment]
Why did you put `ElementOption` inside `App`?

**Comment by vjeux** [comment]
@jddxf The full code uses a variable from App. Thanks for pointing it out, now I understand what's going on! Because the component function gets recreated on every render of App, it's a new one so the entire tree gets removed and re-created.

I can close this! Thanks a lot for the insight!
