### ISSUE TITLE
React Developer Tools react-router-dom e.hasOwnProperty is not a function, Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by yrambler2001** [facebook/react#17764]
bug
Uncaught TypeError: Cannot read property 'name' of undefined
Uncaught TypeError: e.hasOwnProperty is not a function

infinite loading in component view
![image](https://user-images.githubusercontent.com/8398353/71717720-a37e8e00-2e21-11ea-82a3-cc6d815158fc.png)

Reproduce:
use hook useRouter or HOC withRouter from react-router-dom and select component with hook/hoc in components view react developer tools
Issue is caused by not-bug https://github.com/hapijs/hapi/issues/3280
(query object does not have constructor and does not have hasOwnProperty)

![image](https://user-images.githubusercontent.com/8398353/71717283-4afac100-2e20-11ea-9f86-84f63cb73ab1.png)
![image](https://user-images.githubusercontent.com/8398353/71717412-b6dd2980-2e20-11ea-8514-04708cf02015.png)
![image](https://user-images.githubusercontent.com/8398353/71717397-a75de080-2e20-11ea-9dc3-35da5a4f0ff4.png)

**Comment by JackPott** [comment]
I've suddenly started getting this error when clicking on certain components in the Components inspector too. Feels like something 'bad' in one of my comps, but I can't for the life of me find whats causing it, theres another Issue from yesterday for something similar. Has there been an update? 

`Uncaught TypeError: Cannot read property 'name' of undefined
    at O (backend.js:1)
    at s (backend.js:1)
    at s (backend.js:1)
    at s (backend.js:1)
    at l (backend.js:1)
    at Object.inspectElement (backend.js:6)
    at t.<anonymous> (backend.js:6)
    at t.r.emit (backend.js:6)
    at backend.js:32
    at t (backend.js:8)`

**Comment by bvaughn** [comment]
> Uncaught TypeError: e.hasOwnProperty is not a function

This has already been reported as #17761

> Uncaught TypeError: Cannot read property 'name' of undefined

This has already been reported as #17754

A fix for both issues will release shortly. I'm going to close this issue since it's a duplicate :smile:

**Comment by bvaughn** [comment]
FYI this issue should be fixed in v4.4 (released today)
