### ISSUE TITLE
Allow direct construction of components when implementing a custom ComponentFactory 

### ISSUE THREAD

**Issue by Roaders** [facebook/react#17776]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When implementing a `ComponentFactory` the type is returned in the `ReactElement` instead of a constructed instance of the class.

**What is the expected behavior?**
An optional function to create the instance could be included on the `ReactElement` interface:
```
    interface ReactElement<P = any, T extends string | JSXElementConstructor<any> = string | JSXElementConstructor<any>> {
        type: T;
        props: P;
        key: Key | null;
        construct: () => InstanceType<T> // example return type
    }
```
This would allow the developer to provide default logic when constructing the instance.

My use case for this is to enable Dependency Injection of constructor params.

**Comment by bvaughn** [comment]
I'm not sure what you mean by "ComponentFactory". That's not a standard React term. Could you clarify?

If you're referring to factory components, I believe our current plan is to remove support for them in v17 (see #13560).

If you're asking about something else, maybe you could clarify?

By the way, it looks like the type signature you've copied above is for TypeScript. The React team doesn't really manage the React TypeScript types. (They're community managed, via the DefinitelyTyped repo.)

**Comment by Roaders** [comment]
At the moment `React.createFactory(MyClass, props)` returns an object similar to this:

```
{
type: MyClass,
props: props,
Key: someKey
```
(done from memory so might not be 100% accurate)

In my opinion this is not a factory. This is everything that React needs to create a component but it does not include a factory function to actually do the creation. React does this by called `new MyClass(props, context)` somewhere deep in the code base that I can't find right now.

If the above object also allowed the specification of a factory function I would be able to do this:

```
class MyClass{
    constructor(props, service, util, somethingElse){}
}

function myFactoryFunction(type, props){
     const params = doSomeDiMagic(type);

    return new MyClass(props, ...params);
}

export const React.createFactory(MyClass, myFactoryFunction);
```
React would then simply:

```
const instance = factoryFunction(type,props);
```
rather than calling `new type(props)`

Letting me construct the instance myself allows me to pass dependencies into the constructor of the class. This means all code in the class knows that these dependencies are always available (no need to handle possible undefined) and the dependencies are very easy to replace for testing. The class itself also knows nothing about any DI framework and nothing about how to resolve it's dependencies, they are just provided to it so it doesn't need to care.

This seems like a trivial change (to me) and would make things much easier for anyone wanting to do DI.

I might even have a go at a PR at some point (despite only working with React for the last 3 days!)

**Comment by bvaughn** [comment]
Ah, I think there are a lot of small misunderstandings or assumptions here.

Maybe for starters, `createFactory` is a legacy API that we discourage usage of. We suggest using JSX (or `createElement`) instead.

> Letting me construct the instance myself allows me to pass dependencies into the constructor of the class.

Dependencies and other parameters are meant to be passed down to React components as props, or in some cases, using the [context API](https://reactjs.org/docs/context.html). If you want to pass some additional configuration outside of the normal routes, you might consider the [higher-order component pattern](https://reactjs.org/docs/higher-order-components.html#use-hocs-for-cross-cutting-concerns).

```js
function myFactoryFunction(params) {
  return function SomeFunction(props) {
    // props are passed by React at runtime
    // this component can also access the injected params too though
    // ...
  };
}

const ComponentThatCanBeRenderedByReact = myFactoryFunction({
  // some params...
});

// Now you can pass this to createElement directly, or use in JSX
<ComponentThatCanBeRenderedByReact {...props} />;
```

**Comment by bvaughn** [comment]
I'm going to close this issue because I think the proposed change isn't feasible (e.g. it would break legacy context API) and can be better addressed using pre-existing React patterns. Hopefully the above message was helpful but if not let's chat more.

**Comment by Roaders** [comment]
OK, `createFactory` or `createElement` doesn't really matter. This approach will work with either.

> Dependencies and other parameters are meant to be passed down to React components as props

this is what we are trying to avoid. Correct me if I am wrong but adding a dependency to a leaf component at the bottom of a deep view hierarchy would mean updating every component in the tree to add this?

> using the context API.

IMHO this is less than ideal. Again, correct me if I am wrong, but this involves create an app wide context with all the dependencies for the whole app? This would imply leaky dependencies to me. If any component can depend on anything it seems that they would tend to use dependencies that they should not leading to difficult refactoring. If I wanted to remove an item from the context how can I tell that nothing depends on it?

Higher order components seem interesting but this seems that it would create all dependencies at app boot rather than at component initialisation.

> e.g. it would break legacy context API

If you mean `new MyComponent(params, context)` no it wouldn't. Params and context would be passed to the factory function and then passed into the component.

**Comment by bvaughn** [comment]
> this is what we are trying to avoid. Correct me if I am wrong but adding a dependency to a leaf component at the bottom of a deep view hierarchy would mean updating every component in the tree to add this?

Sounds like you are describing why the Context API exists.

>> e.g. it would break legacy context API
>
> If you mean new MyComponent(params, context) no it wouldn't. Params and context would be passed to the factory function and then passed into the component.

Yes, it would. Only React tracks and knows what the current value of the context is for a specific component's place within the tree. :) Context isn't a static/global thing. It *can* be, but it also supports nesting.

**Comment by Roaders** [comment]
> Only React tracks and knows what the current value of the context is for a specific component's place within the tree

yes, from what I can see it's passed in here:

https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberClassComponent.js#L600

`const instance = new ctor(props, context);`

so this would be replaced with:

```
let instance;
if(someObject.componentFactoryFunction != null){
    instance = someObject.componentFactoryFunction(props, context);
} else {
    instance = new ctor(props, context);
}
```

that is pretty much the only change I am proposing (other than actually registering and accessing the function).

**Comment by Moln** [comment]
I provider a  dependency Injection  demo.

https://codesandbox.io/s/react-ioc-demo-m7k4e

But because of the new features of React 17, it doesn't work in the `create-react-app`, and hard work typescript.

```typescript
declare global {
    namespace JSX {
        //...
        interface ElementClass  {
            render(): React.ReactNode | null;
        }
    }
}


class Hello {
  constructor(name: string) {
    this.name = name;
  }

  render(props) {
    return (
      <div>Hello {this.name} and {props.name}</div>
    );
  }
}

React.render(<Hello name="bar" />)
```
