### ISSUE TITLE
Help with JSX -> JS transform without nodejs

### ISSUE THREAD

**Issue by charliematters** [facebook/react#1777]
I'd like to convert JSX files to JS files on a Linux machine which has no (direct) internet access. All of the examples talk about running npm, which obviously won't work in this case. Are there any  alternatives for me?

Ideally I would like to use the watch method of the jsx  executable to do all of the heacy lifting behind the scenes and before a Maven task builds my web app.

**Comment by jsfb** [comment]
I found this to be super helpful, removes the node dependency for nashorn: https://gist.github.com/aesteve/883e0fd33390451cb8eb
