### ISSUE TITLE
Component Hydration Not Correctly Diffing SVG Path Element

### ISSUE THREAD

**Issue by davidgolden** [facebook/react#17778]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

A component containing an SVG is incorrectly rendered on the client when the `<path>` element is expected to change from server to client.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/next-not-updaing-svg-path-xl1u4

**What is the expected behavior?**

I would expect that when the component is rendered on the client, it would recognize that typeof window !== 'undefined' and render a blue square rather than a red circle.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The above example with React 16.12 and in Brave Browser (Chromium). I also tested with 16.7 and had the same behavior.

**Comment by bvaughn** [comment]
React DOM renderer expects server and client markup to match. If they don't match, React will log a warning. It is my understanding that React DOM is not expected to "fix" the mismatch at that point. Having the renderer do this this could negate much of the performance benefits of server side rendering.

They do not match for the sandbox you linked, and an error is being logged:
> Warning: Prop `d` did not match. Server: ...

If you *intend* to render something different/additional on the client, the pattern people typically follow is:
1. Render the same thing initially
2. Render an update on mount

Here is an updated Sandbox showing how you could do this:
https://codesandbox.io/s/next-not-updaing-svg-path-hphwk

**Comment by davidgolden** [comment]
@bvaughn I was struggling with deciding whether or not this was expected, thanks for your detailed response and clarification!

**Comment by bvaughn** [comment]
No problem
