### ISSUE TITLE
Hydrate app won't override className for same element but different props and content

### ISSUE THREAD

**Issue by zhipu123** [facebook/react#17784]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Please see https://jsfiddle.net/cerhqy9f/1/
The server returned a div with class `yellow`, and the client want to change it to a div with class `red`. 
Then the hydrated app contains new content but the old class `yellow`

**What is the expected behavior?**
override the class 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.12.0

**Comment by zhipu123** [comment]
To make it more clear, the origin issue is comes from below requirement
we have a Hooks  useMedia 
```ts
const useMedia = (query: string, defaultState: boolean = false) => {
  const [state, setState] = useState(typeof window !== "undefined" ? () => window.matchMedia(query).matches : defaultState)

  useEffect(() => {
    let mounted = true
    const mql = window.matchMedia(query)
    const onChange = () => {
      if (!mounted) {
        return
      }
      setState(!!mql.matches)
    }
    // This is basically an alias for EventTarget.addEventListener(), for backwards compatibility purposes.
    // Older browsers should use addListener instead of addEventListener
    // Since MediaQueryList only inherits from EventTarget in newer browsers.
    mql.addListener(onChange)
    setState(mql.matches)

    return () => {
      mounted = false
      mql.removeListener(onChange)
    }
  }, [query])

  return state
}
```
this hooks may return different initial value on client and server.  
and our component use this hooks, so we can  render different elements for different screens.
That lead to an issue. we got right content, but old styled

**Comment by kunukn** [comment]
>What is the current behavior?
>Please see https://jsfiddle.net/cerhqy9f/1/
>The server returned a div with class yellow, and the client want to change it to a div with class red.
>Then the hydrated app contains new content but the old class yellow
>
>What is the expected behavior?
>override the class

According to the docs
https://reactjs.org/docs/react-dom.html#hydrate

React docs says
>There are no guarantees that attribute differences will be patched up in case of mismatches

I replicated your example in Codesandbox 
https://codesandbox.io/s/reactjs-hydrate-test-1-o6guc

React docs says
> In development mode, React warns about mismatches during hydration

I got this warning.
`Warning: Prop `className` did not match. Server: "yellow" Client: "red"`

Maybe it works as intended?

**Comment by bvaughn** [comment]
> this hooks may return different initial value on client and server.

React DOM renderer expects server and client markup to match. If they don't match, React will log a warning. In your case:
> Warning: Prop `className` did not match. Server: "yellow" Client: "red"

As mentioned [in this docs](https://reactjs.org/docs/react-dom.html#hydrate), React DOM does not "fix" the mismatch at that point. Having the renderer do this this could negate much of the performance benefits of server side rendering.

If you *intend* to render something different/additional on the client, the pattern people typically follow is:
1. Render the same thing initially
2. Render an update on mount

Here is an updated Sandbox showing how you could do this:
https://codesandbox.io/s/reactjs-hydrate-test-1-pg1yo
