### ISSUE TITLE
flushPassiveEffects and IsThisRendererActing are on the wrong "secret" object

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#17794]
They're currently attached to the "Events" namespace but they don't have anything to do with events. It needs to move to its own names on the secret object.

Once we delete Events, after ReactTestUtils and RNW are fixed, then we won't be able to clean up the array because these two are on it.

Additionally the IsSomeRendererActing field is in the production bundles.

We need to make all of these DEV-only.

**Comment by gaearon** [comment]
Seems like it's gone.
