### ISSUE TITLE
Recommendation - research a Component-Oriented Programming approaches in game development for improving code reuse

### ISSUE THREAD

**Issue by sergeysibara** [facebook/react#17792]
**Do you want to request a *feature* or report a *bug*?**
feature

I want to recommend to research one of variants Component-Oriented Programming (COP) approaches in game programming with which I worked in the past.
 
Most programmers know only one way to reuse code in OOP - inheritance. Because of this, a lot of articles are distributed on the Internet with incorrect comparison of classes with functions.
Also you often changed approaches of code reuse - mixins, HOC, render props, hooks.
But already has long been a quality solutions for reusing code (for example: “component” game programming pattern, Entity Component System).
https://gameprogrammingpatterns.com/component.html (find text “class ContainerObject” in page for example)
https://www.raywenderlich.com/2806-introduction-to-component-based-architecture-in-games#toc-anchor-006
 
Good example using COP has in Unity3d engine. Including for creating UI.
https://docs.unity3d.com/Manual/Components.html
 
Here is an examples of using a some variant COP approach in React. The variant like approach in Unity3d.
The examples for demonstration. The solution is not completed and not optimized.
- https://codesandbox.io/s/example-of-cop-approach-from-game-programming-in-react-6yt8c 
Example of adding additional logic to component  in runtime and of logic reuse outside class component
- https://codesandbox.io/s/second-example-of-cop-approach-from-game-programming-in-react-zo2yy 
there a several examples using this aproah. React components structure was changed for more flexibility.
 
Comparison of some features:
![image](https://user-images.githubusercontent.com/15384809/71858836-e046cf80-3116-11ea-9282-8ecba214784b.png)

If you don’t want to add a similar implementation to the React sources, you can to write a similar example in the documentation. In order not to mislead people, as if only hooks allow to write reusable code effectively in react.

Also I suppose that this approach can be adapted for functional components.
Thus, this will get rid of some of the shortcomings of the hooks.

We can discuss about the approach in the Issue.

**Comment by kamikazePT** [comment]
"Most programmers know only one way to reuse code in OOP - inheritance. Because of this, a lot of articles are distributed on the Internet with incorrect comparison of classes with functions."

I agree with that...

But...about using COP as you showcased, seems way more verbose and complicated to understand than just simply using the hooks API and dumb components taking care of the rendering. Conceptually its the "same", you have a component taking care of the view and you wire it with logic blocks with behaviour ( the hooks )

Although we shouldn't look at hooks as the ultimate answer for code re-use, nothing is perfect and we can always improve, like it has been improving so far :)

**Comment by sergeysibara** [comment]
The approach itself is no more complicated than mixins in React versions prior to 0.15. 
But I complicated it by separating render and adding an ability to convert data before passing it to render. I consider it necessary. If to allow to write a logic in both (components and separated logical blocks) we get not very flexible components like this:
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/SaveButton.tsx
part of the logic is not moved outside component;
we cannot to delete the useTranslate hook if translation is not needed in a project.
 
In Vue the approach should look better because there a template is initially separated from a component.
The ideal code for me would look something like this:
```
const CounterBehaviour = {
  …
  return {count, Setcount}
  …
}

const CounterComponent = {
  behaviours: [CounterBehaviour],
  render: (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  )
}
```

Vue Composition API way is closer to proposed approach by me :
https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#multiple-logic-topics (see "With the function-based API" example)
```
<template>
  <div>
    <template v-if="isLoading">Loading...</template>
    <template v-else>
      <h3>{{ post.title }}</h3>
      <p>{{ post.body }}</p>
    </template>
    <div>Mouse is at {{ x }}, {{ y }}</div>
  </div>
</template>

export default {
  setup(props) {
    return {
      ...useFetch(props),
      ...useMouse()
    }
  }
}
```
but setup() leaves a loophole for writing logic in a component instead writing logic in separated logic block. This is bad.
Also I do not think that in Vue 3 will be ability to delete useFetch, useMouse logic blocks or to add a new.


> Conceptually its the "same", you have a component taking care of the view and you wire it with logic blocks with behaviour ( the hooks )

I agree with that.
But for some reason, the problems that I described in attached image are not resolved in hooks. Perhaps to optimize performance or because it is an experimental technology.

**Comment by bvaughn** [comment]
This issue should be an RFC:
http://github.com/reactjs/rfcs

**Comment by sergeysibara** [comment]
@bvaughn, thanks for the advice!
But I do not fully understand the process.
Did I understand correctly that it is necessary to submit a pull request with detailed description and example in 0000-my-feature.md in the RFC repository instead of creating a new issue?

**Comment by aweary** [comment]
The RFC process is intended to make it easier for the team to evaluate proposals that require substantial changes to React.

> Did I understand correctly that it is necessary to submit a pull request with detailed description and example in 0000-my-feature.md in the RFC repository instead of creating a new issue?

@sergeysibara that's correct, you should follow [the instructions](https://github.com/reactjs/rfcs#what-the-process-is) outlined in the RFC repo. [Here is a good example of a small and straightforward RFC](https://github.com/reactjs/rfcs/pull/63/files) for `React.memo`. Thanks!
