### ISSUE TITLE
Allow load information from my component

### ISSUE THREAD

**Issue by EduardoSaavedra** [facebook/react#17791]
**Do you want to request a *feature* or report a *bug*?**
Its a bug

**What is the current behavior?**
**Im trying to watch all the properties in the tab components but it get stuck when I click in a component from my project, I´ve tried this in all my repositories and i get the same problem.**

![image](https://user-images.githubusercontent.com/40034969/71851264-c6b47200-309b-11ea-98a7-b31c245bf4be.png)

**What is the expected behavior?**
its supposed to show al the info from my component

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: "16.7.0",
Browser: Chrome,
OS: Apple's macOS,
And this was working the last weekend with no problem

**Comment by bvaughn** [comment]
@EduardoSaavedra There's not much I can do to help with only the info provided. Please provide a repro case (can be Code Sandbox, or a link to a website with instructions on which component I need to select) so that I can actually see the error.

**Comment by EduardoSaavedra** [comment]
> @EduardoSaavedra There's not much I can do to help with only the info provided. Please provide a repro case (can be Code Sandbox, or a link to a website with instructions on which component I need to select) so that I can actually see the error.
> 
> This is why the new issue template says 😄
> 
> > **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

@bvaughn This is my component I want to watch in tab component, [code](https://jsfiddle.net/1nvf7qhg/)
and this is a GIF of  what I´m doing and get only the loading
![code stuck](https://user-images.githubusercontent.com/40034969/71912625-7d1b6400-313b-11ea-84ad-8015cbbcc52c.gif)

**Comment by bvaughn** [comment]
The code you linked isn't runnable?
```
Uncaught SyntaxError: Cannot use import statement outside a module
    at run (babel.js:60802)
    at check (babel.js:60868)
    at loadScripts (babel.js:60909)
    at runScripts (babel.js:60936)
    at transformScriptTags (babel.js:324)
```

**Comment by EduardoSaavedra** [comment]
im getting this, when  trying to analyse a component State, it says loading... and throw this error. 

Uncaught TypeError: Cannot read property 'name' of undefined
    at O (backend.js:1)
    at s (backend.js:1)
    at s (backend.js:1)
    at s (backend.js:1)
    at l (backend.js:1)
    at Object.inspectElement (backend.js:6)
    at t.<anonymous> (backend.js:6)
    at t.r.emit (backend.js:6)
    at backend.js:32
    at t (backend.js:8)

**Comment by bvaughn** [comment]
@EduardoSaavedra: Can you share a way for me to run and reproduce this bug? That's what I'm looking for here :smile:

Otherwise I don't know if it's been fixed by a recent PR (e.g. #17757) that hasn't yet been released to the Chrome store.

**Comment by EduardoSaavedra** [comment]
Ok , im going to find the way to send you my code, so you can reproduce this bug, but I have a problem its a private repo but im trying to send the info you need. If not then im going to wait until Chrome Store release it. 

thanks @bvaughn

**Comment by bvaughn** [comment]
You could try to install this (local) build of React DevTools to see if it still reproduces the broken behavior. (If it doesn't, then you don't need to spend any time creating a repro)

[ReactDevTools.zip](https://github.com/facebook/react/files/4032008/ReactDevTools.zip)

If it still does, then I'd suggest trying to just rip out parts of your app until you've gotten it down to something small that still shows the bug. Then you might just be able to port that small example over to Code Sandbox and not have to worry about sharing a Git repo with me? :)

**Comment by EduardoSaavedra** [comment]
@bvaughn  quick question, how do i install your .zip locally?

**Comment by bvaughn** [comment]
1. Download extension
1. Double-click to extract
1. Navigate to `chrome://extensions/`
1. Enable "Developer mode"
1. Click "LOAD UNPACKED"
1. Select extracted extension folder (ReactDevTools)

If you already have the React DevTools extension installed, you will need to temporarily disable or remove it in order to install this prerelease build.

![Install local extension](https://user-images.githubusercontent.com/29597/71921684-2c593a80-313e-11ea-9613-848cbedd7683.gif)

**Comment by EduardoSaavedra** [comment]
Now it´s working, i Did the installation in my local, for now i am going to work with that. Thank you so much @bvaughn. Now we have to wait until Chrome release it?

**Comment by bvaughn** [comment]
Great! That means this was fixed by the recent PR, and will roll out to others as soon as the Chrome reviewers approve the release from a few days ago.

I'd suggest you remove the local install in a few days and get back on the main one (so you don't get left behind for future updates!) :smile:
