### ISSUE TITLE
how to expose ConcurrentModeAPIs for   "react": "16.12.0"? 

### ISSUE THREAD

**Issue by videni** [facebook/react#17807]
I'd like to use  ConcurrentMode at version 16.12.0,  I have lots of dependencies that explicitly depend on react verision  above 16, that is I can't install react@experimetal, anyway to enable it for react 16?

**Comment by threepointone** [comment]
React should usually be in peerDependencies for lower dependencies. Could you share an example repo where this would be a problem?

**Comment by gaearon** [comment]
You can’t enable it for 16.

Peer dependency warnings (which I guess is what you’re referring to) are only that — warnings. You can ignore them and it will work anyway.

I understand warnings are annoying. Maybe you can bring it up with your npm client of choice that it would be valuable to have a way to suppress them for specific packages or versions.
