### ISSUE TITLE
Can't change title of react app for social sharing

### ISSUE THREAD

**Issue by maayanalbert** [facebook/react#17800]
**Do you want to request a *feature* or report a *bug*?**
bug (or a misunderstanding on my part)

**What is the current behavior?**
Even after I set the title of my react app, when sending the website url in a text the title still shows up as "React App" (I'm expecting it to be "Stamper")
![image](https://user-images.githubusercontent.com/18056644/71949978-9ce67280-31a3-11ea-8a09-21ebc95508a6.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I'm currently setting my title by editing `document.title` in `App.js` as below. Perhaps I should be doing this a different way? I also altered the `name` field in `package.json`.
~~~
import './App.scss';
import React, {Component} from "react";
import View from "./View.js"

function App() {
  document.title = "Stamper"
  return (
    <div>
    </div>
  );
}

export default App;
~~~

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This texting error occurs when on iOS (I haven't tested android), I don't know how it would behave on previous versions of react.

**Comment by Liight** [comment]
Hi there,

You could use [React Helmet](https://github.com/nfl/react-helmet)

It's a document head manager for React.
example:
```
import React from 'react'
import { Helmet } from 'react-helmet'

const TITLE = 'My Page Title'

class MyComponent extends React.PureComponent {
  render () {
    return (
      <>
        <Helmet>
          <title>{ TITLE }</title>
        </Helmet>
        ...
      </>
    )
  }
}
```

**Comment by maayanalbert** [comment]
Helmet doesn't seem to be working for me, @Liight were you able to get it to change the social sharing title in your case?

**Comment by Tevinthuku** [comment]
If you're using CRA, then I think social sharing sites will use what's in the `index.html`.
Check this link out on how you can solve this issue https://create-react-app.dev/docs/title-and-meta-tags/#changing-the-title-tag.

I hope this helps

**Comment by maayanalbert** [comment]
@Tevinthuku that was it! I had to change the title in `index.html`. Thanks for your help :)

**Comment by looweb** [comment]
Ok, but, what if I need to change the title for every page? I'm still stuck. I'm using [react-meta-tags](https://www.npmjs.com/package/react-meta-tags) and it doesn't work when I paste my link on social networks.

**Comment by rbk** [comment]
> Ok, but, what if I need to change the title for every page? I'm still stuck. I'm using [react-meta-tags](https://www.npmjs.com/package/react-meta-tags) and it doesn't work when I paste my link on social networks.

Hi @looweb. Did you ever solve this issue?

**Comment by looweb** [comment]
> > Ok, but, what if I need to change the title for every page? I'm still stuck. I'm using [react-meta-tags](https://www.npmjs.com/package/react-meta-tags) and it doesn't work when I paste my link on social networks.
> 
> Hi @looweb. Did you ever solve this issue?

Not really.

**Comment by gaearon** [comment]
This is not a question about React. It's a question about how you generate HTML, and so it depends on *what you're using* to generate HTML. Depending on the tool you use (CRA, Next.js, some custom setup), the answers will be different. I am locking the thread to prevent further confused discussion because there can be no concrete answer in this repository.
