### ISSUE TITLE
react-hooks/rules-of-hooks is taking useRouterHistory as hook

### ISSUE THREAD

**Issue by zeel-swiggy** [facebook/react#17808]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
eslint gives error when useRouterHistory function of React router 3 is used along with eslint-plugin-react-hooks saying that 

error  React Hook "useRouterHistory" is called in function "getSsrWebRoute" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
It should whitelist library functions

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest

**Comment by threepointone** [comment]
Thanks for the recommendation, but this is a rare exception in the ecosystem, and has been removed in newer versions of react-router. You can work around it by reassigning it to a new name before you use it in your function.

**Comment by jasonmobley** [comment]
This "rare exception" seems to come up a lot...
#14791
#15227
#17636
#17808
