### ISSUE TITLE
UseEffect

### ISSUE THREAD

**Issue by LIJIOJOHN123** [facebook/react#17810]
54 | console.log(props.match);
  55 | const classes = useStyles();
  56 | React.useEffect(() => {
> 57 |   fetchChannelById(props.match.param.id);
     | ^  58 | }, [fetchChannelById]);
  59 | return (
  60 |   <div className={classes.card}>

props.match.param is not working. My code is fine. if hard code id my app is working. fine. Please fix it

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Tevinthuku** [comment]
Please reproduce the bug in `Codesandbox` so that we can debug the problem

**Comment by threepointone** [comment]
This doesn't seem to be a bug or feature request in React, so I'm closing it. Please use a community resource https://reactjs.org/community/support.html
