### ISSUE TITLE
Bug: Custom postMessage breaks in Safari

### ISSUE THREAD

**Issue by OZZlE** [facebook/react#17828]
If you implement your own custom post message in a component it seems like `react-dom.development.js` picks this up and throws errors.

    SyntaxError: The string did not match the expected pattern.  react-dom.development.js:469

React version: 16.12.0

## Steps To Reproduce

1. Open Safari version 13.0.2 (OsX Mojave) or iPhone with mobile Safari iOs 12.4
2. Using this code when you press the button you get an exception.

        class TodoApp extends React.Component {
          onClick = () => {
            window.postMessage(`custom.sizeSelect:14`, window);
          }
          
          render() {
            return (
              <div>
                <button onClick={this.onClick}>
                  Bug
                </button>
              </div>
            )
          }
        }

        ReactDOM.render(<TodoApp />, document.querySelector("#app"))

Link to code example: https://jsfiddle.net/j4zw7nt1/

## The current behavior
Exception.

## The expected behavior
React should try to detect if the `postMessage` was actually an internal one or if it's an custom/external `postMessage` that it should ignore.

Worst thing is that our consultants who made this app hasn't configured it to use react production mode so now we have this bug on production as well :<

**Comment by threepointone** [comment]
I don't see how this is a React issue, I can reproduce it with plain js https://jsfiddle.net/g7qzfeyh/ . I'd debugyour message handler's implementation, that's likely where the bug is.

**Comment by OZZlE** [comment]
@threepointone Sorry you are correct! I did not expect that just assumed that `postMessage` was working in Safari with valid syntax..

It seems like it doesn't really work in Safari at all currently (unless there is an iframe involved and some special syntax? need it investigate more) .. I can define a onMessage handler that does nothing with the result but it still an error.. I can't see that I am doing anything wrong according to the spec either.

Safari is becoming the new IE.. Apologies anyway.

**Comment by OZZlE** [comment]
@threepointone seems like this issue was somehow only present when you use

[sentry.io](https://sentry.io/) + React in development mode + chrome + custom post message

:) In production we don't use React development mode and locally I don't need sentry.io so problem solved :)
