### ISSUE TITLE
Bug: setState triggers render but doesn't update state

### ISSUE THREAD

**Issue by oliversturm** [facebook/react#17820]
React version: 16.12.0

## Steps To Reproduce

1. Run example application
2. Click "Doit" button
3. Observe browser console and state rendered by component

Link to code example: https://github.com/oliversturm/react-render-without-state-change

## The current behavior

The button click event handler triggers a lengthy operation that periodically calls `setState` to update the state label in the UI. To prevent state update batching, the process is started using `setTimeout`. A line of console output is written in the render function, and this output shows 1000 times on the console. At the same time, the state does not change and the component rendering does not reflect any updated state until such time the busy-loop process ends.

## The expected behavior

I'm investigating options to trigger UI updates from long-running processes like that modelled in this example. I would prefer option 1 for expected behavior: when `setState` is called, it should update the state and then trigger a render.

Since I don't know whether my approach is the "correct" or intended one for my purpose, I would also accept option 2: no state change, no render. In this case I'm back to researching other alternatives.

In any case it seems wrong to me that renders are triggered by the `setState` calls, even though no state change takes place. This is why I'm reporting the issue as a bug.

**Comment by zhao545432854** [comment]
![3S(TVM6~@OGYEU8M`7N %EP](https://user-images.githubusercontent.com/43113657/72201811-bf71d780-3492-11ea-95ad-0b38aad150b5.png)
Is that so?

**Comment by zhao545432854** [comment]
![@FET C3T}$HFJQWOGLUZFDQ](https://user-images.githubusercontent.com/43113657/72201833-0069ec00-3493-11ea-95a6-b5eb21c86e68.png)
是这样吗

**Comment by JKCooper2** [comment]
I think you may need to request an animation frame to allow the JS thread to perform the re-render (https://css-tricks.com/using-requestanimationframe-with-react-hooks/). JS is single threaded so while you're looping and adding calls to the event queue you're never actually allowing anything in the event queue to run until you're entire call is complete.

In that case its not a React specific issue

**Comment by oliversturm** [comment]
@zhao545432854 I'm afraid I don't understand what you mean. Your code looks like it would run through the entire busy loop before establishing the interval meant to push updates to the UI. 

@JKCooper2 Thanks for the link, this is a useful idea that may help me solve my actual problem in a more elegant way. However, I'm not sure I agree with the conclusion about the event queue - clearly I can see calls to the render logic in my sample, and these are triggered directly as a consequence of the `setState` call - comment it and there are no more renders. So my issue remains the same: there doesn't seem to be a reason to call the render logic if the state change that triggers it has not actually been applied.

As a side note, in my real application I also have a variation of my algorithm that uses Promises (the busy loop in my real code uses recursion and I "broke it apart" by representing individual results as Promises). Strangely enough, this code shows the same behavior as my sample, even though the Promises result in interruptions in the busy loop.

**Comment by vkurchatkin** [comment]
@JKCooper2 is right, it has nothing to do with React. You just can't report the progress of a synchronous computation. You need to break into pieces by calling `setTimeout(0)` or something similar.

> So my issue remains the same: there doesn't seem to be a reason to call the render logic if the state change that triggers it has not actually been applied.

React calls render logic synchronously when you call `setState`. It is ready to update the DOM after that, but it just doesn't have the chance until the loop is over.

**Comment by oliversturm** [comment]
Okay, I guess I was just not getting this - unfortunately nobody pointed out that I can see the changed state by simply logging it to the console in the render function. But it's true, there it is - so the DOM update is really what's missing, not the state change. I have to take this back to my real code and try to remember why this didn't cross my mind previously (or actually I know it did, but I was pretty sure before that this was not where the problem was).

The other thing I need to figure out is why the algorithmic variant I implemented with Promises to interrupt the busy loop didn't solve the problem - I did that precisely because I was thinking that perhaps the DOM wasn't being updated, but it didn't make a difference. However, I don't have a small reproducible sample for that right now, so I'll close this issue to stop wasting everybody's time. Of course I'd still appreciate any further thoughts you might have, and many thanks for your help.

**Comment by vkurchatkin** [comment]
Promises are interesting this way: `then` callbacks are executed asynchronously but they still prevent browser logic from running. It goes like this:

|---- synchronous JS running ----|---- promise callbacks running ----|---- browser repaints ---- |

So, for example, this blocks the browser just the same:

```js
let i = 0;
function update() {
  rootElement.innerHTML = 'c ' + i;
  i++;

  Promise.resolve().then(update);
}

update();
```

While this works fine:

```js
let i = 0;
function update() {
  rootElement.innerHTML = 'c ' + i;
  i++;

  setTimeout(update, 0)
}

update();
```

**Comment by JKCooper2** [comment]
One thing you can do is setup a ref to a textinput. Then set the ref.current.value to be the text you want and set that. I believe that is outside the react tlifecycle and useful for things like timers.


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by vkurchatkin** [comment]
> Then set the ref.current.value to be the text you want and set that. I believe that is outside the react tlifecycle and useful for things like timer

No, that won't work either

**Comment by oliversturm** [comment]
Based on your helpful hints I have several ideas that I want to try out, but I can't do it right now. 

Meanwhile I'm wondering if there are any guidelines for this scenario? I couldn't find anything like that when I searched.

To summarize, the problem is really quite simple and (I would think) common:

> From a React UI, a long-running operation is triggered - something like a calculation process. While this process runs, it provides updated state information or intermediate results (in my case) that should be displayed in the UI immediately.

**Comment by vkurchatkin** [comment]
If your long running process is pure computation, then using a web-worker seems to be the best option. In your case it would look something like this:

```js
function runWorker(onStateChange) {
  const source = `
    postMessage("starting");
    let step = 0;
    for (let i = 0; i < 1000000000; i++) {
      if (i % 1000000 === 0) {
        step++;
        postMessage(\`step \${step}\`);
      }
    }
    postMessage("done");
  `;
  const blob = new Blob([source]);
  const url = URL.createObjectURL(blob);
  const worker = new Worker(url);

  worker.onmessage = (e) => {
    onStateChange(e.data)
  }

}

function App() {
  const [state, setState] = useState("");

  return (
    <div>
      <div>State: {state}</div>
      <div>
        <button onClick={() => {
          runWorker(setState)
        }}>Do it with counter</button>
      </div>
    </div>
  );
}

```

**Comment by oliversturm** [comment]
Thank you for your ideas. I guess I was viewing the issue with too much of a focus on React itself. I have implemented an update mechanism that works pretty well on the basis of a web worker. 

For some reason, Chrome shows a strange behavior where it only updates the DOM when I interact with the browser somehow (like click the mouse), while everything works perfectly in Firefox. But I'll investigate this separately...

**Comment by oliversturm** [comment]
And a final note: my Chrome problem went away when I debounced the state update function. This was necessary anyway because state updates were slowing down the whole mechanism enormously due to their frequency - and apparently Chrome gets fed up with this more easily than Firefox does.
