### ISSUE TITLE
Bug:  "NotFoundError" when removeChildFromContainer -> container.removeChild(child) is called

### ISSUE THREAD

**Issue by vkuba** [facebook/react#17833]
React throw an unhandled exception  "NotFoundError" when removeChildFromContainer -> container.removeChild(child) is called on a node that doesn't contains the child anymore.
This only occurs in IE 11. 

React version: v16.12.0

## Steps To Reproduce

1. Detach the Portal DOM element by an external library.
2. In my scenario element where the portal is attached to is removed by asp POST back  (partial update of a Panel) 
The same situation happens to a number of people but is hard to reproduce in a clean environment. For example https://stackoverflow.com/questions/57678799/react-portal-cannot-be-unmounted-without-non-react-dom-parent-how-can-i-unmoun

## The current behavior
 "NotFoundError" when removeChildFromContainer -> container.removeChild(child) is called

## The expected behavior
Can we if(container.contains(child)) be added to removeChildFromContainer? This seems to solve the issue.

I am happy to provide more details if something is unclear :)

**Comment by bvaughn** [comment]
> 1. Detach the Portal DOM element by an external library.

This doesn't really look like a repro case :smile: Can you share some code where this happens?

**Comment by bvaughn** [comment]
Closing due to lack of info.

**Comment by jljorgenson18** [comment]
This issue happens when a portal is unmounted but is no longer in the dom itself. This is currently happening for us when the parent is of a portal element is removed. I can try to come up with a repro case, but it is failing here

```
function removeChildFromContainer(container, child) {
  if (container.nodeType === COMMENT_NODE) {
    container.parentNode.removeChild(child);
  } else {
    container.removeChild(child); // Error on this line. 
  }
}
```

There would just need to be a .contains check to fix this.
