### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'nextSibling' of null

### ISSUE THREAD

**Issue by bethanyaconnor** [facebook/react#17845]
I am using [react-rehype](https://github.com/rehypejs/rehype-react) (latest version) to parse and format Markdown content that is continuously updating based on user input. On certain changes, particularly the creation of list items, I get an error message `Uncaught TypeError: Cannot read property 'nextSibling' of null`.

Before I see the error message in the console, I see an unclosed comment tag when I inspect the element that is rendering the formatted text:
![Screenshot 2020-01-13 at 9 59 45 AM](https://user-images.githubusercontent.com/46464143/72378704-c54ffe80-36c6-11ea-8a7f-ffa0918146d4.png)

The stack trace is all within React code:
![Screenshot 2020-01-13 at 9 57 33 AM](https://user-images.githubusercontent.com/46464143/72378741-d7ca3800-36c6-11ea-9aac-50d9ca13e0ea.png)

React version: 15.6.0

## Steps To Reproduce 

Small repo with repro steps is at: https://github.com/bethanyaconnor/rehype-react-bug

## The current behavior
Eventually, the component crashes in React code that updates the component on state change.

## The expected behavior
There is no JS errors/crashes.

**Comment by wfnuser** [comment]
@bvaughn Hi. May I take this issue? I would like to have a try.

**Comment by bvaughn** [comment]
I would not have tagged this one a "good first issue" - but you're welcome to have a look @wfnuser :smile:

**Comment by bl00mber** [comment]
Seems that this is react-rehype related issue, not react related?

**Comment by bvaughn** [comment]
I don't know what react-rehype is, and I haven't investigated this bug report, so I don't know.

**Comment by gaearon** [comment]
The stack trace shows the version of React is lower than 16. So this is not unfortunately actionable for us. React 16 was released over two years ago.
