### ISSUE TITLE
Bug: Type Error:undefined is not an object (evaluating'_expo.default.fileSystem')

### ISSUE THREAD

**Issue by aboudi619** [facebook/react#17847]
![ERROR](https://user-images.githubusercontent.com/58271750/72451076-4e446400-37b3-11ea-991f-fd2ea391510a.PNG)

React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by aboudi619** [comment]
im using react native to run my app. but i keep getting this error [see image attached] . plx someone help me.
{ expo-file-system folder is already installed.}

**Comment by gaearon** [comment]
This doesn't appear to have something to do with React. I suggest you to contact Expo for help.
