### ISSUE TITLE
Warning: Did not expect server HTML to contain the [first prerendered] text node "[chinese characters]"

### ISSUE THREAD

**Issue by Arlen22** [facebook/react#17846]
I don't even know where to start with this. When I inspect the source of this error, it is a very well-written section of code, but I can find almost no documentation on this problem anywhere. I don't know what causes it and short of spending the next two weeks stepping through React and Next.js, I have no way of know where to start. I thought I had fixed the problem by making FontAwesome a dynamic import, but then the text next to it through the same error. I've also had classes causing errors by not resolving to the same class names on hydration as the prerendered HTML has. I don't understand this problem and I don't know what it means. 

Here's my package.json, if that helps anything. This problem doesn't make any sense to me but i've been running into it since I started with next.js, but I don't know anything about it. 

```json
{
  "name": "next-project",
  "version": "1.0.0",
  "description": "",
  "main": "src/pages/index.ts",
  "scripts": {
    "dev": "rm -rf .next .expo && next dev",
    "build": "next build",
    "start": "next start",
    "next": "next"
  },
  "author": "https://github.com/arlen22/",
  "license": "ISC",
  "dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "@unimodules/core": "^5.0.0",
    "@unimodules/react-native-adapter": "^5.0.0",
    "@zeit/next-css": "^1.0.1",
    "babel-preset-expo": "^8.0.0",
    "expo-asset": "^8.0.0",
    "expo-font": "^8.0.0",
    "native-base": "^2.13.8",
    "next": "^9.1.5",
    "next-fonts": "^0.19.0",
    "next-images": "^1.2.0",
    "next-progressbar": "^1.0.0",
    "node-fetch": "^2.6.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-icons": "^3.8.0",
    "react-native-drawer-layout": "^2.0.0",
    "react-native-web": "^0.11.7",
    "rxjs": "^6.5.4"
  },
  "devDependencies": {
    "@expo/next-adapter": "^2.0.0-beta.10",
    "@types/node": "^12.12.18",
    "@types/react": "^16.9.16",
    "@types/react-native": "^0.60.25",
    "@types/react-native-drawer-layout": "^1.3.5",
    "file-loader": "^5.0.2",
    "next-transpile-modules": "^2.3.1",
    "typescript": "^3.7.3",
    "url-loader": "^3.0.0"
  }
}
```

**Comment by gaearon** [comment]
It's very unlikely we'd be able to help you without a reduced reproducing case.

**Comment by Arlen22** [comment]
I don't know how to narrow it down to a reproducible use case. Basically there is no way to reliably get it to happen because I don't know why it's happening. I don't know what the situations are that can cause the error. The only reason I posted it here was because the error is in ReactDOM and I think it's connected with React DOM Server. I've got it to happen with almost no code, and yet I can't reliably reproduce it.

**Comment by Arlen22** [comment]
Here is my next.config.js. 

```js
const withPB = require("next-progressbar");
const { withExpo } = require('@expo/next-adapter');
const withImages = require('next-images');
const withFonts = require('next-fonts');
const withCSS = require('@zeit/next-css')
const path = require('path');

module.exports = withCSS(withExpo(withImages(withFonts(withPB({
  projectRoot: __dirname,
  typescript:{
    ignoreDevErrors: true
  },
  webpack(config, options) {
    config.resolve.alias['src'] = path.join(__dirname, 'src');
    config.resolve.alias['assets'] = path.join(__dirname, 'assets');
    config.resolve.alias['cache'] = path.join(__dirname, 'cache');
    return config
  },
})))));
```

**Comment by Arlen22** [comment]
The code is so well written that it really looks like it should be a well-understood problem. It's obviously a sanity check, though, because most things seem to still work. At first I thought it was breaking my Javascript, but I was able to figure out that it is just a regular warning, not an exception.

**Comment by Arlen22** [comment]
This is my render tree. The problem randomly appears and disappears, and even deleting the `.next` and `.expo` folders does nothing. 

This is my render tree.

```ts
  return renderContextChain([
    ContextTuple(Editor.isEditMode, false),
    ContextTuple(LanguageContext, "en-en"),
    ContextTuple(FontContext, fontStyle)
  ], [
    ce(View, { key: "root-container", style: WrapperStyles.container },
      ce(Drawer, drawer.props(),
        ce(TopBar, topbar),
        ce(ScrollView, {
          style: {},
          contentContainerStyle: { minHeight: 200 }
        } as ScrollViewProps,
          screens[index].sections.map(({ items, title, showTitle, layout, id, aspectRatio }) =>
            ce(SectionScroller, {
              key: id, id, title, items, layout, aspectRatio,
              refreshing: false, showTitle, onSelect
            })
          )
        )
      )
    )
  ])
```

createContextChain just uses a recursive function to set the Providers in the first array and then sets the second array as the children of the last one.

**Comment by bvaughn** [comment]
This looks related to the following other issues:
* #14843 - no repro case; cause unclear.
* #10879 - caused by HTML pretty formatting and differing whitespace.

As Dan said, I don't think we have the bandwidth to look into this at the moment without at least a repro case. (Then it would be a matter of prioritizing.)

**Comment by Arlen22** [comment]
> As Dan said, I don't think we have the bandwidth to look into this at the moment without at least a repro case. (Then it would be a matter of prioritizing.)

I don't even know where the documentation is and this time I am refusing to read the source code to figure out the problem (because I don't have time). The code is so well written that it should have a documentation page with the known reasons this can happen. Am I missing something?

**Comment by bvaughn** [comment]
@Arlen22 No one has asked you to read source code or diagnose the cause of this issue. We have asked for you to share some code that reproduces the problem with us, so that one of us can take a look. Without being able to reproduce the problem, we can't really help.

I'm going to flag this issue as needing more info (a repro case). If you find time to create one for us, great! If not, the issue will be closed after a few days since it's not actionable.

**Comment by Arlen22** [comment]
> @Arlen22 No one has asked you to read source code or diagnose the cause of this issue. We have asked for you to share some code that reproduces the problem with us, so that one of us can take a look. Without being able to reproduce the problem, we can't really help.

I'm sorry. I didn't mean to be rude. I don't know how to reproduce it because I don't know what is causing the problem and I can't find any documentation on hydration errors.

**Comment by bvaughn** [comment]
It's okay. :smile:

The fact that the code is well written doesn't actually mean that we understand all potential sources of errors. (We definitely don't!) So we rely on folks to help us by letting us know *how* they're running into errors. In many cases, while putting together a repro, someone might realize that the cause of a bug is in application code, or another library (not React). So repros are a really important part of keeping React maintainable! :smile:

There isn't a lot of documentation (at the moment) for hydration. The main entry is [here](https://reactjs.org/docs/react-dom.html#hydrate) which mentions:
> React expects that the rendered content is identical between the server and the client.

The error  you're reporting seems to suggest that there is a mismatch between the exact server-rendered content and what the client expected to be rendered during hydration. We *warn* about this case in DEV mode for performance reasons:
> React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

As for how to reproduce this issue, that might be trickier. When I'm trying to create a repro from a large project, I usually start by ripping out big chunks of the code and seeing if the issue still reproduces. If it does, I know the thing I removed wasn't an essential part of the bug. If it doesn't, I re-add it and try ripping out a smaller piece (or something else). This can be tricky with issues that don't reproduce reliably :frown: I'm sympathetic there.

**Comment by bvaughn** [comment]
Sounds like a use case that the API we call "Suspense" could help with once it's finished.

It's a little hard to answer a generic question like this, but it seems to me like you Would want to just wait to call `hydrate` until the data has loaded?

**Comment by Arlen22** [comment]
> It's a little hard to answer a generic question like this, but it seems to me like you Would want to just wait to call hydrate until the data has loaded?

I'm using Next.js, but if it's that simple I'm sure there's a way. I'll ask that separately.

**Comment by bvaughn** [comment]
Just following up on this issue. Were you able to find out anything from Next.js? I'm wondering if we should close this issue (since it's not really actionable) and just continue to chat here if there are follow up questions.

**Comment by Arlen22** [comment]
I'm not sure if stale bot will lock this thread. But I wanted to say that what I ended up doing was just not loading the data on the server side, which I detected using `typeof window`. So in the end I just didn't use this feature, but it seems really strange that it's like this. After some more research, I do think Suspense might answer this question, especially if ReactDOM Server waits for these suspenses to resolve before declaring the page rendered and the client-side hydrate detects that these suspenses are already resolved. Is this how it works in practice?
