### ISSUE TITLE
I used a class component before this. But I liked the hooks more. It’s very comfortable to work with him and it’s not difficult to understand. Thanks to your team for this !

### ISSUE THREAD

**Issue by madly0894** [facebook/react#17858]
👉 Please follow one of these issue templates:
- https://github.com/facebook/react/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by threepointone** [comment]
Appreciate the sentiment, thank you!
