### ISSUE TITLE
Consider warning when we get non-bool values for HAS_BOOLEAN_VALUE attributes

### ISSUE THREAD

**Issue by zpao** [facebook/react#1785]
I saw a case where somebody was making use of `cx` to conditionally disable a button (`<button disabled={cx({"disabled": this.state.disabled})}/>` - clever but not necessary. I think a warning here might prove useful for these.

**Comment by nhunzaker** [comment]
No resolution after 2.5 years. Is there anything to move forward on?

**Comment by aweary** [comment]
I'm going to close this out since there's been no movement, and there's been no indication that this scenario is a common pain point, meaning a warning probably won't be useful enough to justify.
