### ISSUE TITLE
Docs: React documentation is the documentation I have ever seen. It dosent even properly tell how to get started and create new app. Take some inspiration from documentation of Django, Flutter, Vue, Angular, etc 

### ISSUE THREAD

**Issue by dev-akshat** [facebook/react#17851]
🚨 This issue tracker is not for documentation issues. 🚨

The React website is hosted on a separate repository. You may let the
team know about any issues with the documentation by opening an issue there:
- https://github.com/reactjs/reactjs.org/issues/new

**Comment by gaearon** [comment]
You already filed https://github.com/facebook/react/issues/17850. Please don't file two issues at once.
