### ISSUE TITLE
Bug: useRef can not return a persist ref object

### ISSUE THREAD

**Issue by janryWang** [facebook/react#17853]
React version:

16.12.0

## Steps To Reproduce

1. Click Button，View print data
2. Click Button，View print data

Link to code example:
https://codesandbox.io/s/kind-fog-mce7w

## The current behavior
Every time you click the button, the printed data will change

## The expected behavior
Every time I click the button, the printed data should be an empty object

**Comment by dmytro-lymarenko** [comment]
It happens because you mount `Inner` component and unmount which cases all hooks inside `Inner` to reinitialize.

**Comment by janryWang** [comment]
@dmytro-lymarenko Is there a way to ensure that the reference object is not refreshed?

**Comment by dmytro-lymarenko** [comment]
@janryWang you can either move the reference object up to the parent or keep the component rendered by hiding it with css rather than unmounting.

**Comment by bvaughn** [comment]
@dmytro-lymarenko is correct. When you unmount a component, its state goes away. When you mount a component, new state is initialized. If your app has state that needs to outlive a particular component, then it should not live in that component (but in one that's higher up in the tree).
