### ISSUE TITLE
Bug: Error: EMFILE: too many open files, open 'C:\xxx\web\build\static\js\main.b1a04325.chunk.js'

### ISSUE THREAD

**Issue by hsluoyz** [facebook/react#17866]
I use `serve` to serve my React app because this docs said so: https://create-react-app.dev/docs/deployment/

React version: 16.12.0
OS: Win 10 x64

## Steps To Reproduce

1. Create a React app.
2. Let a lot of users use it.

## The current behavior

After dozens of minutes of access (~ 20 requests/second), I always encounter such error. It seems that too many people are reading the static files.

```
Microsoft Windows [Version 10.0.17763.914]
(c) 2018 Microsoft Corporation

C:\xxx\web>serve -s build -l 6001

C:\xxx\web>"node"  "C:\Users\Administrator\AppData\Roaming\npm\\node_modules\serve\bin\serve.js" -s build -l 6001

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   Serving!                                      │
   │                                                 │
   │   - Local:            http://localhost:6001     │
   │   - On Your Network:  http://172.17.10.7:6001   │
   │                                                 │
   │   Copied local address to clipboard!            │
   │                                                 │
   └─────────────────────────────────────────────────┘


INFO: Gracefully shutting down. Please wait...
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\xxx\web\build\static\js\main.b1a04325.chunk.js'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:120:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\xxx\\web\\build\\static\\js\\main.b1a04325.chunk.js'
}
```

## The expected behavior

No error.

**Comment by bvaughn** [comment]
This isn't a React bug :smile:

The doc you linked to mentions `serve` as "the easiest" option, but looking at [`serve`'s own documentation](https://www.npmjs.com/package/serve) it says:
> Once it's time to push your site to production, we recommend using [ZEIT Now](https://zeit.co/now).

Anyway it looks like you also opened an issue on `serve`'s GitHub page (https://github.com/zeit/serve/issues/575) so I'm closing this one.
