### ISSUE TITLE
Bug: Child event listener is called after parent's one when rendered conditionally

### ISSUE THREAD

**Issue by michalak111** [facebook/react#17877]
React version: 16.12.0

## Steps To Reproduce

If we have some `Parent` component which has event listener `document.addEventListener('mousedown', cb)` in `useEffect` or `cDM` and `Children` component which is rendered conditionally with element which has a listener on `onMouseDown` too then after Child is rendered callback action on `Parent` listener is called first.

Link to code example: https://codesandbox.io/s/throbbing-sun-ub2kd

## The current behavior

console.log output

```
app 
child 
app 
child 
```

## The expected behavior

console.log output
```
child 
app 
child 
app 
```

Not 100% this is bug or expected - I already find a way how to hack this.

But if we treat this as a bug I've made some debugging which hopefully may be helpful (ofc I may be wrong, I'm not enough familiar with library code). 

As I noticed this happens because `addEventBubbleListener` action which adds listeners to document, and in this particular situation listener to Child element is added after parents one because is rendered later on because of some users action .

**Comment by JoshuaAmaju** [comment]
@michalak111 It's not a bug, mouse events always fire before click events.
