### ISSUE TITLE
Bug: onPointerEnterCapture and onPointerLeaveCapture result in `unknown event handler property`

### ISSUE THREAD

**Issue by tommedema** [facebook/react#17883]
React version: v16.12.0 from https://unpkg.com/react/umd/react.development.js

## Steps To Reproduce

1. attach onPointerEnterCapture to a JSX element
2. observe `unknown event handler property` error in console

Link to code example: https://jsfiddle.net/tommedema/1uqoemxs/2/

## The current behavior

It displays a `unknown event handler property` warning

## The expected behavior

The capturing phase of the onPointerEnter and onPointerLeave events should be supported

**Comment by KevinKelbie** [comment]
There is support for pointer-events in v16.4.0:
https://reactjs.org/blog/2018/05/23/react-v-16-4.html

**Comment by tommedema** [comment]
@KevinKelbie thanks but that blog post does not list `onPointerEnterCapture`, only `onPointerEnter`. Do you know if this is a mistake? I specifically need the capturing phase

**Comment by tommedema** [comment]
@necolas what can I do to help this get fixed? This has been blocking me since Jan 21st

**Comment by bl00mber** [comment]
@tommedema are you sure this event exist? Can you send a link to ECMA specification?

**Comment by necolas** [comment]
It's the same as the mouse event equivalents, they don't bubble and don't have a capture phase: https://reactjs.org/docs/events.html#mouse-events. You should use `onPointerOver/Out` instead.

**Comment by rjgotten** [comment]
>@necolas 
>It's the same as the mouse event equivalents, they don't bubble and don't have a capture phase

You're wrong. While `pointerenter` doesn't bubble, it definitely *does* have a capture phase:
https://jsfiddle.net/69xm0t7w/

**Comment by necolas** [comment]
Not in the *React* event system. Read the link above.

![Screenshot_20240322_074304_Chrome](https://github.com/facebook/react/assets/239676/8683a728-1c3d-4920-8887-07b7ad3bf7e8)

**Comment by rjgotten** [comment]
Then React should fix its TypeScript typings to special case those events to not generate `onPointerEnterCapture` and `onPointerLeaveCapture` properties as common element props. Fact that those exist broadcasts they're meant to be supported.

**Comment by eps1lon** [comment]
@rjgotten  We removed these types in the types for 18. We reverted the backport to types for 17 and 16 since it caused too much breakage across the ecosystem due to TypeScript wrongfully inlining types during declaration emit.

**Comment by rjgotten** [comment]
> @eps1lon 
> We removed these types in the types for 18.

I am using `@types/react-dom@18.2.18` and its types still define `onPointerEnterCapture` on `DOMAttributes`.

**Comment by eps1lon** [comment]
Latest is 18.2.70

**Comment by xiaody** [comment]
FTR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68984 [@types/react] fix: remove onPointerEnterCapture & onPointerLeaveCapture
