### ISSUE TITLE
Bug: state is not stable for local component

### ISSUE THREAD

**Issue by hagaigold** [facebook/react#17886]
React version: 16.12.0
Don't know if this the intended behavior or a bug... if not a bug it should be documented somewhere.

## Steps To Reproduce

[link to code example](https://codepen.io/hagaigold/pen/xxbmqoR)

## The current behavior

a local (to a function) component is destroyed every render, while an expression is not.

## The expected behavior

both local components and the JSX expression beave the same.

**Comment by TrySound** [comment]
@hagaigold You render new component on every render. You should define all components in module scope. Not in another component render.

**Comment by hagaigold** [comment]
I would expect some warning if this is not allowed.
you can write easily a stateless "local component" that will look like it is working, while actually it recreates every time, (I actually saw this pattern elsewhere).
later on, someone else or you will try to change it to a stateful component...

**Comment by bvaughn** [comment]
@TrySound is correct.

@hagaigold Your example looks to be defining the `TempLine` component/function *inline* which means that every time the parent `ToDoList` component renders, it will create *a new* `TempLine`  component (a new function). React sees this new function as a completely new component type, so it will unmount the previous `TempLine` (and anything it renders- **all of its children**) and re-initialize and re-mount the new `TempLine`.

I don't think this would ever be what you want.

> I would expect some warning if this is not allowed.

React can't really detect that you did this *accidentally*. It's technically *okay* to render different components each time. It's just not what you're intending to do in this case.

You might try proposing a new lint rule for this:
https://github.com/yannickcr/eslint-plugin-react
