### ISSUE TITLE
Bug: standalone react devtools can't save settings

### ISSUE THREAD

**Issue by tjx666** [facebook/react#17881]
I don’t know if save settings are not supported in standalone react devtools, but I think it's a very basic function.
I use it to debug react project in electron, the repository is [coo](https://github.com/tjx666/coo). You may need to fallback the code to commit id: 44726520aa417b82712b5a4d91e14100048f23c3

React version: 16.12.0

## Steps To Reproduce

1.start standalone react devtools and set theme dark
2.restart standalone react devtools, but the theme is still auto

Link to code example:

## The current behavior
can't save settings
## The expected behavior
support save settings

**Comment by bvaughn** [comment]
I can't reproduce the behavior described using the latest version of `react-devtools` from NPM with either React Native *or* with a `create-react-app` application.

**Comment by tjx666** [comment]
@bvaughn I made a minimal reproduce repository [react-devtools-example](https://github.com/tjx666/react-devtools-example), you can test with it.

**Comment by moroz1k** [comment]
bump! on two computers the same problem
