### ISSUE TITLE
Enable a lint rule not to define after return and fix existing callsites

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#17885]
https://twitter.com/therealyashsriv/status/1219691914523545601

We shouldn't generate code that might cause browser or linting to complain.

https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/legacy-events/SyntheticEvent.js#L259

It's also just a confusing pattern at best.

**Comment by M-Izadmehr** [comment]
Hey, 
If possible I would like to take a look into this issue:)

**Comment by bvaughn** [comment]
@M-Izadmehr This issue is all yours! 😄

We've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let us know so that we can remove the label and free it up for someone else to claim.

Cheers!

**Comment by sebmarkbage** [comment]
@M-Izadmehr Great! Thanks for taking a look. I think the first step is to look at our es-lint config and enable a canonical lint rule that already exists upstream.

After that you should be able to open a PR which should fail the lint rule. After that you could do a separate commit that contains the code fixes. I wouldn't start by fixing the code though as that risks rebase issues.

**Comment by M-Izadmehr** [comment]
@sebmarkbage @bvaughn 
I tried to check this issue and here are my findings:
First of all, we are never violating `no-unreachable` linting rule.
Based on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return) firefox never shows a warning, if a function declaration statement is following return. Also, based on [ESLint](https://github.com/eslint/eslint/blob/master/docs/rules/no-unreachable.md) it is also a valid code. As a result react code is safe, and never causes a warning.

Secondly, after a small search through the project, I see that we are using this approach in at least a dozen places. I can suggest two things, if we are on the same page, then continue with the PR:
1. Explicitly add `no-unreachable` to eslint config (this is already a part of default config, so adding it will have no effect, just helps with explicitly showing the purpose)
2. Although this pattern does not cause a warning (in either eslint/or browser), it can be confusing at times (however, it also results in cleaner functions, e.g. check below image)

Either way, if you agree with refactoring such cases I can move on with submitting the PR.


![image](https://user-images.githubusercontent.com/28848972/73698777-5ae91780-46e2-11ea-8231-c36c46288b87.png)

**Comment by flexhard69** [comment]
Bind

**Comment by bpernick** [comment]
@M-Izadmehr @bvaughn is this still being worked on? Happy to take a stab at it if not!

**Comment by mnindrazaka** [comment]
Hi, everyone, is there any update about this issue ?
@bvaughn @M-Izadmehr @sebmarkbage

**Comment by bhumijgupta** [comment]
Hey @bvaughn @sebmarkbage , I recently created an ES-Lint plugin ([eslint-plugin-no-function-declare-after-return](https://github.com/bhumijgupta/eslint-plugin-no-function-declare-after-return)) to ensure there are no function declaration after return. I can :-
1. Add the plugin to the repo
or
2. Extract logic out of the plugin and add a new rule to the repo
and then make changes to fix it.

**P.S.** I added the plugin to the local fork of the repo and tested it. It was able to detect 6 places in codebase where there is a function declaration after return.
![test](https://user-images.githubusercontent.com/30751793/91741742-c50f5f80-ebd2-11ea-9c4c-c6c34aeba674.png)

**Comment by bvaughn** [comment]
> Extract logic out of the plugin and add a new rule to the repo

I'm not sure what "extract logic out of the plugin" mean. Is this option just adding the `eslint-plugin-no-function-declare-after-return` plugin to our `.eslintrc.js`? If so, sounds reasonable to me.

**Comment by bhumijgupta** [comment]
Yup, I can just add the plugin to `.eslintrc.js` and it will work just fine

**Comment by bvaughn** [comment]
Great. Send a PR and I'll take a look :)

**Comment by bvaughn** [comment]
Thanks @bhumijgupta

**Comment by bhumijgupta** [comment]
Looking for more opportunities to contribute

**Comment by bvaughn** [comment]
I see 452 open issues at the moment 😅  Maybe there's another one you find interesting
