### ISSUE TITLE
Bug: Cannot download experimental React build from CI

### ISSUE THREAD

**Issue by ahmehri** [facebook/react#17891]
Following the [instructions](https://github.com/facebook/react/tree/master/packages/react-devtools#download-from-ci) for local development of react-devtools, it's not possible to download the experimental build from CI.

## Steps To Reproduce

1. Run the `./scripts/release/download-experimental-build.js` command from the root of the repository.
2. The following error will be thrown
```
Cannot read property 'build_num' of undefined

TypeError: 
    at run (facebook/react/scripts/release/shared-commands/get-latest-master-build-number.js:21:4)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async facebook/react/scripts/release/node_modules/progress-estimator/src/logger.js:58:27
    at async run (facebook/react/scripts/release/download-experimental-build.js:21:22)
```

**Comment by bvaughn** [comment]
I think this is a transient error that means that none of the recent CI builds were experimental builds.

Looking at the list of recently completed tasks, they look to all be our "fuzzy test" target that runs once every so often:
https://circleci.com/gh/facebook/react

The metadata that's returned (at least at the moment) is all full of "fuzzy test" jobs too:
https://circleci.com/api/v1.1/project/github/facebook/react/tree/master

I'm not familiar enough with the Circle CI API to know if there's a way for us to request the next "page" of data, but I think that would be the right approach in this case.

As a temporary unblocker, you can can copy any of the build IDs for the "experimental" builds fro the Circle CI page and pass it in, e.g.
```
scripts/release/download-experimental-build.js --build=77063
```
