### ISSUE TITLE
[react-test-renderer]: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by sahibjotsaggu** [facebook/react#17893]
Searched online and the only solution was to keep react, react-dom, and react-test-renderer packages the same version. I have those three packages as the same version (^16.8.6) but I'm still getting the error.

React version: 16.8.6
React DOM version: 16.8.6
React Test Renderer: 16.8.6

My test script is `jest --env=jsdom`

Using Babel v7.

<img width="866" alt="Screen Shot 2020-01-22 at 5 28 39 PM" src="https://user-images.githubusercontent.com/8991960/72940334-b4ddfa80-3d3c-11ea-811c-36b8e6ad0052.png">

This is my test code:

<img width="401" alt="Screen Shot 2020-01-22 at 5 29 39 PM" src="https://user-images.githubusercontent.com/8991960/72940386-ce7f4200-3d3c-11ea-8b9b-ad98073b4fe8.png">

.babelrc:

<img width="433" alt="Screen Shot 2020-01-22 at 5 30 01 PM" src="https://user-images.githubusercontent.com/8991960/72940404-db039a80-3d3c-11ea-85f1-30e71da90390.png">

jest.config.js

<img width="679" alt="Screen Shot 2020-01-22 at 5 30 24 PM" src="https://user-images.githubusercontent.com/8991960/72940429-e787f300-3d3c-11ea-8ed9-fcf99f4efc67.png">

**Comment by bvaughn** [comment]
@sahibjotsaggu Can you share something that we can actually run? Pictures of code requires a lot of work for someone (like me) to recreate your project setup, and there's always a chance that some important detail is missing from one of the pictures that will prevent me from being able to reproduce the problem. (Like you may actually have different React versions installed. The info above doesn't really rule that out.)

You can setup Code Sandbox to run jest tests, for example:
https://codesandbox.io/docs/tests

**Comment by sahibjotsaggu** [comment]
This was for a private project that isn't too big, so I started making a standalone project as a demo that didn't include any confidential information and I figured out that my problem was I hadn't updated all my babel packages to be compatible with babel v7. Specifically, it was the `babel-polyfill` package that still needed to be updated.
