### ISSUE TITLE
Bug: Stale state state with combination of a closure fn and memo

### ISSUE THREAD

**Issue by thehappycoder** [facebook/react#17917]
Before I create a working code example demonstrating the problem, please let me know if it's a known issue (afaik, it's not reported but I am not sure).

I am experiencing a stale state issue with combination of hooks, closure fn and memo.

Parent component:
```
const [selectedLeftPart, setSelectedLeftPart] = useState<
    DisconnectedSentencePart | undefined
  >(undefined)

const selectLeftPart = (part: DisconnectedSentencePart) => {
    // accesses selectedLeftPart
    console.log(selectedLeftPart)
}

return (
  <Child selectLeftPart={selectLeftPart} />
)
```

Child component:
```
export const Child= memo(
  (props: Props) => {
    const selectSentencePart = () => {
      props.selectSentencePart(props.part)
    }

    return (
      <ItemDiv selected={props.selected} onClick={selectSentencePart}>
        {props.part.part}
      </ItemDiv>
    )
  },
  (prevProps, nextProps) => {
    return isEqual(
      omit(prevProps, ["selectSentencePart"]),
      omit(nextProps, ["selectSentencePart"])
    )
  }
)
```

As soon as I remove memo from the Child component, selectLeftPart in the parent component console logs current state of selectedLeftPart. If I use `useCallback` in the Child instead of using memo, I get the same problem.

This issue is stopping me from using Hooks in my project that used react-16.12.0.

**Comment by bvaughn** [comment]
What is `selectLeftPart`? The Parent passes it to the Child but the Child never uses it. Presumably you actually meant `selectSentencePart`? (or the other way around)?

If _that's_ the case, (which I assume it is), then the code above has a bug. 🙂

It is intentionally excluding `props. selectSentencePart` from the memo check, so React won't re-render if that's the only prop that's change. This means that the new function coming in as `props.selectSentencePart` (which closes over the newest/lates value of `selectedLeftPart` in the Parent component) will just be ignored, and your Child component will keep using the old, stale function prop (which "closed over"<sup>1</sup> an old, stale version of `selectedLeftPart` Paret state).

<sup>1</sup> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

**Comment by thehappycoder** [comment]
@bvaughn Yes, I meant to pass the fn as `selectSentencePart` to the child. I'll update the code.

Sorry, what I meant to say in this issue is that in my case, there is no way to define a callback in a stateful functional component and at the same time keep Child optimised. Yes, I could wrap `selectLeftPart` in `useCallback` and pass `[selectedLeftPart]` to it as a 2nd parameter but, in the real code I didn't post here, `selectLeftPart` always calls `setSelectedLeftPart`, which would always invalidate the cached callback and make all the children re-render.

In this particular case, I have no other choice but to switch to a class component?

**Comment by bvaughn** [comment]
> Sorry, what I meant to say in this issue is that in my case, there is no way to define a callback in a stateful functional component and at the same time keep Child optimised.

There is a hook specifically for this, `useCallback`.

> In this particular case, I have no other choice but to switch to a class component?

Stale closures would affect class components too.

**Comment by thehappycoder** [comment]
I'll create a working example to demonstrate that `useCallback` doesn't help.

**Comment by thehappycoder** [comment]
@bvaughn The following example demonstrates that `useCallback` doesn't help whereas class component saves the day https://codesandbox.io/s/intelligent-bird-wvbdb?fontsize=14&hidenavigation=1&theme=dark

**Comment by bvaughn** [comment]
Why does your `useCallback` example declare the `selectedItem` as a dependency? It isn't actually used. The thing that *is* used, `setSelectedItem`, is stable between renders (so it wouldn't recreate the callback).

It's not clear from your example above why the outer component needs to "*accesses selectedLeftPart*", but if it *does*, this is why the state updaters let you pass an updater function:
```js
const [selectedItem, setSelectedItem] = useState(null);

const selectItem = useCallback(
  item => {
    setSelectedItem(prevSelectedItem => {
      // You have the prevSelectedItem here, since you seem to need it?

      // and you can update the state to the new on too:
      return item;
    });
  },
  [selectedItem]
);
```

Here is an updated sandbox:
https://codesandbox.io/s/naughty-almeida-7m6h4

**Comment by thehappycoder** [comment]
@bvaughn  Thank you. I haven't thought about using a setter like this. In my app, it's slightly more complicated because I use 2 states, so it's going to be a bit more messy..

To clean it up a bit, I should probably combine 2 states into 1 of type. However, it's still more involved and not straight-forward approach to me, so I'd use class in this case.

```
import * as React from "react";
import { useState, useCallback } from "react";

import { Item } from "./Item";

const leftList = ["One", "Two", "Three", "Four", "Five"];
const rightList = ["Six", "Seven", "Eight", "Nine", "Ten"];

export const List = () => {
  const [selectedLeftItem, setSelectedLeftItem] = useState<string | undefined>(
    undefined
  );

  const [selectedRightItem, setSelectedRightItem] = useState<
    string | undefined
  >(undefined);

  const selectLeftItem = useCallback(
    (item: string) => {
      setSelectedLeftItem(prevLeftItem => {
        setSelectedRightItem(prevRightItem => {
          // Pass item and prevRightItem
          // to the store
          // passToStore(item, prevRightItem)
          console.log(item, prevRightItem);

          return prevRightItem;
        });

        return item;
      });
    },
    [setSelectedLeftItem, setSelectedRightItem]
  );

  const selectRightItem = useCallback(
    (item: string) => {
      setSelectedLeftItem(prevLeftItem => {
        setSelectedRightItem(prevRightItem => {
          // Pass prevLeftItem and item
          // to the store
          // passToStore(prevLeftItem, item)
          console.log(prevLeftItem, item);

          return item;
        });

        return prevLeftItem;
      });
    },
    [setSelectedLeftItem, setSelectedRightItem]
  );

  return (
    <>
      List (function component)
      <div style={{ display: "flex" }}>
        <div style={{ flex: 1 }}>
          {leftList.map(item => {
            return (
              <Item
                key={item}
                item={item}
                selected={selectedLeftItem === item}
                selectItem={selectLeftItem}
              />
            );
          })}
        </div>
        <div style={{ flex: 1 }}>
          {rightList.map(item => {
            return (
              <Item
                key={item}
                item={item}
                selected={selectedRightItem === item}
                selectItem={selectRightItem}
              />
            );
          })}
        </div>
      </div>
    </>
  );
};
```

**Comment by bvaughn** [comment]
> @bvaughn Thank you. I haven't thought about using a setter like this. In my app, it's slightly more complicated because I use 2 states, so it's going to be a bit more messy..

> To clean it up a bit, I should probably combine 2 states into 1 of type. However, it's still more involved and not straight-forward approach to me, so I'd use class in this case.

Sounds like a good case for `useReducer`. Its `dispatch` function is stable (so you wouldn't even need a callback) and the reducer function always gets passed the current/latest state.
