### ISSUE TITLE
Profiler should highlight host components (e.g. DOM elements) on mouseover

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#17928]
Feature request from a DevTools user at Faceook:
> If I mouse over a node in the flame graph if you can highlight it in the view like the inspector that would be really amazing!

**Comment by M-Izadmehr** [comment]
Hi @bvaughn,
I really liked to check this issue, and I was able to create a PR to add highlighting for both FlameGraph and RankedList charts. (#17934 )

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by steveadams** [comment]
Hi @bvaughn, I took a look at @M-Izadmehr 's work on this and thought I'd offer to get it over the finish line. They haven't been active on GitHub for a while, so if you'd like assistance I'd be happy to fork and resolve the remaining conflicts and get it delivered. Apologies if that's bad etiquette!

I'm looking for ways to get my feet wet and start contributing here 🙂

**Comment by bvaughn** [comment]
Feel free to create an updated PR if you'd like, @steveadams.

**Comment by steveadams** [comment]
Will do @bvaughn . Thanks for the speedy response!

**Comment by bl00mber** [comment]
@bvaughn I've sent an updated [PR](https://github.com/facebook/react/pull/18745)
