### ISSUE TITLE
Bug: Autocomplete not working for controlled input

### ISSUE THREAD

**Issue by robin-drexler** [facebook/react#17927]
React version: 16.12.0

## Steps To Reproduce
1. Have a form with controlled input (i.e. value is set through `onChange` handler)
1. Type `cheese` into the input
1. Submit the form
1. Reload the page
1. Focus the input, type `c`
1. `cheese` is *not* suggested

https://codesandbox.io/s/ancient-currying-oqgt6

It works when a uncontrolled input is used (i.e. value is not set by react `onChange` handler)
1. Have a form with uncontrolled input
1. Type `cheese` into the input
1. Submit the form
1. Reload the page
1. Focus the input, type `c`
1. `cheese` is being suggested

https://codesandbox.io/s/naughty-dijkstra-p3n42

It's not about autofilling address data or passwords, but data previously filled in by the user.
We noticed this issue in Chrome, Firefox and Safari. Even though we could not get any autocompletion to work in Safari, even without React. (We could in Chrome and Firefox)

Thanks!

**Comment by ced-b** [comment]
I seem to be running into the same issue.

**Comment by ced-b** [comment]
This is somewhat speculation, but what seems to happen in the DOM is that the `value` attribute of the `input` gets set with every key stroke. So when the form is submitted the "system supplied" value and the user input are the same and the browser does not store it for further autocompletion.

**Comment by gaearon** [comment]
Thank you for reporting this. This is unfortunately a known problem that is being tracked in https://github.com/facebook/react/issues/15739. I will close this as a duplicate but feel free to subscribe to that issue.

**Comment by ashishSingh008** [comment]
bump

**Comment by tripolskypetr** [comment]
Looks like all these methods with `autofill` prop are simple ignored by Google Chrome since 2022. I suggest a different method: using `readOnly={true}` until focus event

> Keep in mind that on mobile safari keyboard will not shown if input field change readonly state after focus event, so you need to process `onTouchStart` too. Heres the link to [the source code of `usePreventAutofill` hook](https://github.com/react-declarative/react-declarative/blob/51f4c29897297233e5c958de782b6af4e7b41cf5/src/hooks/usePreventAutofill.ts#L19)

```tsx
import { usePreventAutofill } from 'react-declarative';

...

const preventAutofill = usePreventAutofill();

...

return (
  <InputBase

      ...

      {...preventAutofill}
  />   
);
 
```
