### ISSUE TITLE
Bug: React with Typescript => void / boolean is not assignable to type 'FC<{}'

### ISSUE THREAD

**Issue by rag4214** [facebook/react#17930]
```js
import React from 'React';

const SomeComponent: React.FC = ({children}) => {}
      ^^^^^^^^^^^^^
Type '({ children }: { children?: ReactNode; }) => boolean' is not assignable to type 'FC<{}>'
```

React version: 16.12.0
Typescript version: 3.7.3
@types/react version: 16.9.19

## Steps To Reproduce

1. Create new FC
2. Try to desctructure children

Link to code example:

https://codesandbox.io/s/objective-herschel-y0myn

## The current behavior
Errors out on compile

## The expected behavior
Should be able to destrcture children just find

**Comment by oknoorap** [comment]
Your code should be `const MyComponent React.FC<{}> = ({ children }) => ....` you're missing type argument here `<{}>`

**Comment by rag4214** [comment]
If you look at the typing of FC its
```js
type FC<P = {}> = FunctionComponent<P>;
```
The `<{}>` is inferred by default if you don't include a type. Even doing what you said, I still get the same error. I'm still thinking this is a bug.

**Comment by dexiouz** [comment]
Were you able to solve this because I am currently having same issue

**Comment by alexrili** [comment]
> Were you able to solve this because I am currently having same issue

I was having the same problem, in my case are the file extension. instead of using ".jsx" I was using  ".ts" soon as I fix the file extension the problem was solved.

**Comment by dexiouz** [comment]
> > Were you able to solve this because I am currently having same issue
> 
> I was having the same problem, in my case are the file extension. instead of using ".jsx" I was using  ".ts" soon as I fix the file extension the problem was solved.
> 

How, you were able to use ".jsx" on a typescript file? And it worked?

**Comment by alexrili** [comment]
> > > Were you able to solve this because I am currently having same issue
> > 
> > 
> > I was having the same problem, in my case are the file extension. instead of using ".jsx" I was using  ".ts" soon as I fix the file extension the problem was solved.
> 
> How, you were able to use ".jsx" on a typescript file? And it worked?

I misstype , I was trying to say ".tsx"

**Comment by dexiouz** [comment]
> > > > Were you able to solve this because I am currently having same issue
> > > 
> > > 
> > > I was having the same problem, in my case are the file extension. instead of using ".jsx" I was using  ".ts" soon as I fix the file extension the problem was solved.
> > 
> > How, you were able to use ".jsx" on a typescript file? And it worked?
> 
> I misstype , I was trying to say ".tsx" 

Alright that's fine. Thanks for the heads up. I'll give it a try when I reinitialise a new project.

**Comment by TravelPaul** [comment]
I have been seeing the same issue, but all my files were .tsx.

The cause was a parent component with a children type that was wrong:
```
children: JSX.Element | JSX.Element[] | string
```

Where it should have been:
```
children: React.ReactNode
```
