### ISSUE TITLE
onPaste not working in IE8

### ISSUE THREAD

**Issue by brendanmoore** [facebook/react#1794]
the onPaste event does not appear to be firing in IE8, since jsfiddle doesn't play nice in I have create a simple demo page here http://brendanmoore.github.io/ie8_bug.html that shows the issue.

**Comment by gaearon** [comment]
We are not actively supporting IE8 since v15 so I am closing as it’s unlikely somebody would work on this particular problem in the future. However if you feel strongly about this, you can submit a PR with a fix, and we can discuss again there. Thanks!
