### ISSUE TITLE
Bug(devtools): complex types ignored sometimes in useDebugValue

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#17955]
React version: 0.0.0-241c4467e (current `next`) and 16.12.0
Devtools: 4.4.0 (1/3/2020). [...] Created from revision f749045a5 on 1/3/2020.

## Steps To Reproduce

1. Visit https://codesandbox.io/s/usedebugvalue-complex-types-3x877
2. Inspect `App` Component
3. `NoHooksAtAll` displays no hooks at all
4. `IgnoredComplexValue` displayes the custom hook but without a value
5. `NoHooksAtAll` displays the custom hook with its value

Link to code example:

## The current behavior
Complex values (and custom hooks) are sometimes not displayed

## The expected behavior

Implementation of components and hooks should not affect if these are displayed.

**Comment by wfnuser** [comment]
I would like to take a look. 😄

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by wfnuser** [comment]
Thanks. I'm working on it.

**Comment by wfnuser** [comment]
Hi... It seems I need some help... I'm not sure what the hooks should behave in the dev-tools.
Would anyone explain it more detailed for me. Or give me some docs to follow... It has proved that I'm still very new to react.😅
![image](https://user-images.githubusercontent.com/8191686/74602454-8eb13d80-50e3-11ea-8b44-28a6b566aeef.png)

**Comment by bvaughn** [comment]
@wfnuser I don't think I understand what you're asking.

**Comment by eps1lon** [comment]
@wfnuser 
 Here's a mock of what I would've expected looking at the built-in hooks.

## currently working as expected
<details>
<summary>currently working useDebugValue in component</summary>

![DisplayedComplexValuePass](https://user-images.githubusercontent.com/12292047/74635183-c4970600-5165-11ea-92eb-b13735837adb.png)

</details>

## missing debug value in component
<details>
<summary>actual</summary>

![IgnoredComplexValueFail](https://user-images.githubusercontent.com/12292047/74635198-ce206e00-5165-11ea-8a0a-5ff399dd1f4f.png)

</details>

<details>
<summary>expected</summary>

![IgnoredComplexValuePass](https://user-images.githubusercontent.com/12292047/74635205-d11b5e80-5165-11ea-9ef4-6b0350137a3d.png)

</details>

## missing hooks in component
<details>
<summary>actual</summary>

![NoHooksAtAllFail](https://user-images.githubusercontent.com/12292047/74635210-d4164f00-5165-11ea-8c0f-61a069ae9e62.png)

</details>

<details>
<summary>expected</summary>

![NoHooksAtAllPass](https://user-images.githubusercontent.com/12292047/74635215-d7a9d600-5165-11ea-92f6-01b9c3c74eab.png)

</details>

@bvaughn needs to confirm if this is correct.

I can write some tests tomorrow if you're not sure where to start. Having failing test might help experimenting with various pieces of code to see what does what.

**Comment by wfnuser** [comment]
> @wfnuser
> Here's a mock of what I would've expected looking at the built-in hooks.
> 
> ## currently working as expected
> currently working useDebugValue in component
> ## missing debug value in component
> actual
> ![IgnoredComplexValueFail](https://user-images.githubusercontent.com/12292047/74635198-ce206e00-5165-11ea-8a0a-5ff399dd1f4f.png)
> 
> expected
> ![IgnoredComplexValuePass](https://user-images.githubusercontent.com/12292047/74635205-d11b5e80-5165-11ea-9ef4-6b0350137a3d.png)
> 
> ## missing hooks in component
> actual
> ![NoHooksAtAllFail](https://user-images.githubusercontent.com/12292047/74635210-d4164f00-5165-11ea-8c0f-61a069ae9e62.png)
> 
> expected
> ![NoHooksAtAllPass](https://user-images.githubusercontent.com/12292047/74635215-d7a9d600-5165-11ea-92f6-01b9c3c74eab.png)
> 
> @bvaughn needs to confirm if this is correct.
> 
> I can write some tests tomorrow if you're not sure where to start. Having failing test might help experimenting with various pieces of code to see what does what.

Thanks a lot. I still need to learn more about how hooks work. If you can provide some tests, that will be very helpful.

**Comment by bvaughn** [comment]
Not sure if I agree with "no hooks at all" component. Seems like a use case that I'm not sure if DevTools needs to support.

**Comment by eps1lon** [comment]
> Seems like a use case that I'm not sure if DevTools needs to support.

Because there are no built-in hooks used other than `useDebugValue`? Would probably agree with that. It's still surprising behavior which I'd like to avoid generally.

**Comment by eps1lon** [comment]
@bvaughn I'm quite lost where the tests for these components are located. The data seems to be wired up correctly. It looks like the view is not working but I can't find tests for those. Is there some documentation how to test devtools?

**Comment by bvaughn** [comment]
>> Seems like a use case that I'm not sure if DevTools needs to support.
>
> Because there are no built-in hooks used other than `useDebugValue`? Would probably agree with that. It's still surprising behavior which I'd like to avoid generally.

Yes. There's no need to use such a hook at all, since hooks calls can't be conditional to begin with (without leading to errors).

> @bvaughn I'm quite lost where the tests for these components are located. The data seems to be wired up correctly. It looks like the view is not working but I can't find tests for those.

You'd probably want to add tests to the following places:
* v16+ - https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/__tests__/inspectedElementContext-test.js
* v5 - https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/__tests__/legacy/inspectElement-test.js

> Is there some documentation how to test devtools?

No.

**Comment by eps1lon** [comment]
Ah I couldn't get it pick up react-devtools-shared but this isn't included in `yarn test`. `yarn test-build-devtools` was the magic word.

**Comment by eps1lon** [comment]
> Yes. There's no need to use such a hook at all, since hooks calls can't be conditional to begin with (without leading to errors).

Just to be clear: There's not conditional call there. It's just not using an built-in hooks other than `useDebugValue`

**Comment by bvaughn** [comment]
> > Yes. There's no need to use such a hook at all, since hooks calls can't be conditional to begin with (without leading to errors).
> 
> Just to be clear: There's not conditional call there. It's just not using an built-in hooks other than useDebugValue

I understand. My point though is that- since hooks calls can't be conditional, this could only ever be an "empty" hook- which serves no purpose and so I don't see it as a use case we should ever need to support.

**Comment by eps1lon** [comment]
> My point though is that- since hooks calls can't be conditional, this could only ever be an "empty" hook- which serves no purpose and so I don't see it as a use case we should ever need to support.

I'm confused. A custom hook with no built-in hooks is the only hook that's displaying complext types. It's only not working for the component  that doesn't use built-in hooks (other than `useDebugValue`) at all.

As soon as a custom hook uses `useDebugValue` **and** built-in hooks the complex type isn't displayed.

**Comment by bvaughn** [comment]
I'm not sure where the confusion is.

I'm just saying that the "no hooks at all" component is not a use case I care about us supporting, because that's a "custom hook" that literally only uses the debug value hook and nothing else. That use case is not important to support. (If it works, fine. If it doesn't work, fine.)

**Comment by eps1lon** [comment]
> I'm not sure where the confusion is.

I originally thought at least something is working. But since we don't care about the case that is working it's a bit more complicate to understand for an outside contributor how to create a test and feature since I have nothing to work off.

**Comment by eps1lon** [comment]
@wfnuser This was more complicated than I thought #18070 already includes a fix. I wasn't able to write test and fix separately, sorry. Might still make sense to check #18070 out in case the fix isn't accepted.
