### ISSUE TITLE
[eslint-plugin-react-hooks] Better check against misuse in classical class components

### ISSUE THREAD

**Issue by jukben** [facebook/react#17958]
We have run into issue coming from calling hooks from class component, I was surprised that eslint rules doesn't provide any check for that. Is there any reason for that? Am I missing something? I willing to contribute in case this feature request will be approved. 🙌 

eslint-plugin-react-hooks version: 2.3.0

## Steps To Reproduce

1. Create class Component and try to use hook within it
2. Not warning appears but the code leads to runtime error

Link to code example: https://codesandbox.io/s/rules-of-hooks-class-tr0ko

## The current behavior
There is currently no check for `class` token. You can use hook within method of your class without triggering any warning coming from Rule of Hooks rules.

## The expected behavior
The usage of hooks within class should be restricted since it's against 

- Only Call Hooks at the Top Level
- Only Call Hooks from React Functions

**Comment by albseb511** [comment]
As per es-lint-rules-hooks
```
              // Ignore class methods for now because they produce too many
              // false positives due to feature flag checks. We're less
              // sensitive to them in classes because hooks would produce
              // runtime errors in classes anyway, and because a use*()
              // call in a class, if it works, is unambiguously *not* a hook.
```

**Comment by weakish** [comment]
Recent versions will [check hooks in component class](https://github.com/facebook/react/commit/d3368beeecb2b51f51814f95f977e8c11900f54e#diff-dcabaa12c1f45139b78f519a27f40a74).
