### ISSUE TITLE
[react-devtools] add maxConnectionAttempts config option

### ISSUE THREAD

**Issue by Hacksore** [facebook/react#17963]
From time to time I am not actively running react-devtools but my application still wants to connect indefinitely every 2 seconds.

What I am suggesting is an optional parameter so that if it tries x amount of times it can just give up once it meets the max threshold.

`maxConnectionAttempts` - Would allow a developer to override/control the number of connections attempts the react-devtools will try.

Example:
```js
devtools.connectToDevTools({
  host: 'localhost',
  port: 8097,
  maxConnectionAttempts: 5
});
```

If there is a better option I am up for the discussion, thanks!

**Comment by bvaughn** [comment]
What kind of app are you talking about? Can you tell me more about your use case?

**Comment by Hacksore** [comment]
@bvaughn It's an electron-based application that I'm programmatically invoking `connectToDevTools` to allow it to connect. 

Basically just trying to stop the console log from piling up, even though they stack.

**Comment by bvaughn** [comment]
@Hacksore I don't think I have the bandwidth to tackle this right now.

I started thinking about it a little bit but I don't have time to test and think through the edge cases. want to finish it?

https://github.com/facebook/react/compare/master...bvaughn:devtools-connect-retry-options

**Comment by Hacksore** [comment]
A quick and easy solution to this was to have two start scripts. When I run dev then I can check if the `REACT_DEVTOOLS` env var is set to the correct value and choose to not load the tools.

```json
"scripts" {
	"dev": "cross-env REACT_DEVTOOLS=true npm start",
	"start": "npm start"
}
```
