### ISSUE TITLE
Bug: Opens Google chrome automatically

### ISSUE THREAD

**Issue by 5knnbdwm** [facebook/react#17964]
When starting the react app browserosaurus should appear with a window that lets me select the browser I want to open a link with. However when Google chrome is running, there doesnt have to be an active window, the react process simply opens a new chrome window.
When Google chrome is not running react opens browserosaurus and lets me decide what browser to use to open the link

React version: ^16.12.0

## Steps To Reproduce

1. Install browserosaurus, set as default browser (manages links from apps which are not the installed browsers)
2. create new react project
3. start base react project

## The current behavior
When google chrome is running react opens a new window automatically 

## The expected behavior
Open browserosaurus to let me decide what browser to use to open the link

**Comment by bvaughn** [comment]
Sorry @5knnbdwm, but please file issues with create-react-app on its repo:
https://github.com/facebook/create-react-app

Different people maintain that one, typically.

Thanks!
