### ISSUE TITLE
Bug: onRender of parent <Profiler> called for each child update

### ISSUE THREAD

**Issue by zaqqaz** [facebook/react#17965]
With Profiler API it's not possible (or at least not clear) how to measure commit time for parent components which renders child which is also should be profiled. 

Example from the documentation: 
```
Profiler components can also be nested to measure different components within the same subtree:


  <App>
    <Profiler id="Panel" onRender={callback}>
      <Panel {...props}>
        <Profiler id="Content" onRender={callback}>
          <Content {...props} />
        </Profiler>
        <Profiler id="PreviewPane" onRender={callback}>
          <PreviewPane {...props} />
        </Profiler>
      </Panel>
    </Profiler>
  </App>
```

In this case, we can't measure separately updates only for Panel component as the same callback will be called for updates in Content or PreviewPane.

React version: 16.9.0

I prepared a simplified demo: https://codesandbox.io/s/react-codesandbox-9zf7v

As you can see here wrapper profiler updated every time with counter profiler even though that wrapper component is not updated.

**Comment by bvaughn** [comment]
The behavior you have described how the API was intentionally designed. Profiler reports times for any/ever update within its subtree. (This enables you to provide an entire application, while also collecting times for certain subtrees.)

If you're interested in the Profiler API's design, you can find the RFC here:
https://github.com/reactjs/rfcs/blob/master/text/0051-profiler.md

**Comment by zaqqaz** [comment]
@bvaughn, fair enough, thank you for the prompt reply!

In this case, maybe you can advise me (or just provide ref where to look in dev-tools implementation) how to trace updates on the component level? (to be able to get the same picture as in react-dev-tools (amount of re-renders of the component/duration) to be able to automate check of unexpected re-renders.

**Comment by bvaughn** [comment]
That use case (per-component profiling) is not something the user-facing API is meant to support.

The only way to accomplish this with the public API would be to wrap a `Profiler` around every individual component (which is **not** something we would recommend).

**Comment by zaqqaz** [comment]
The goal is to have tooling which is able to provide information about re-renders based on user interaction as a plugin to some performance tests(kinda e2e), to be able to set expected values for some components and monitor amount and duration of re-renders as a part of the pipeline to make dx a bit better.

>The only way to accomplish this with the public API would be to wrap a Profiler around every individual component (which is not something we would recommend).

I started with such an idea, that's actually why this issue created, but as Profiler designed in a way that it notifies all parents in a render tree, I don't see a way how to recognize is this an update of the parent itself or only child component was updated. Like in this example https://codesandbox.io/s/react-codesandbox-9zf7v after the click by the counter, 
<Profiler> will log both updates for "wrapper" and "counter", but in this case, I care less about the <Wrapper> as there was no real update on the component level but about the <Counter>. And when after a click on "Update wrapper"  I'd like to be notified that <Wrapper> updated.

**Comment by bvaughn** [comment]
Right. I understood what you were asking for. That's just not how the Profiler API was designed to work. :smile:

Implicit in my previous comment was that you would need to subtract subtree durations from a Profiler to determine the duration only for the single component in between, but again- we don't recommend using the API that way.
