### ISSUE TITLE
Bug: Unable to share context to ReactDOM.render from the element's parent component in React?

### ISSUE THREAD

**Issue by nidhisridhar** [facebook/react#17974]
Hi, 
I posted this question on stackoverflow. The solution recommended doesn't work for our application and so does using portals. Is there a way to share context from the ckeditor component to the counter component in this case? 
https://stackoverflow.com/questions/59904871/how-to-share-context-to-reactdom-render-from-the-elements-parent-component-in-r?noredirect=1#comment106035238_59904871

React version: 16.12

## Steps To Reproduce

1. Codesandbox linked in the Stackoverflow
2.

Link to code example: https://codesandbox.io/s/passing-context-into-contenteditable-xi2j9

## The current behavior
The ContextProvider in the component rendered through ReactDOM.render starts a new instance instead of using it's parent's

## The expected behavior
There must be a way to share context between two components, one of which is rendered through ReactDOM.render

**Comment by trueadm** [comment]
You want to be using React Portals via the `ReactDOM.createPortal` API. I quickly hacked it into your codesandbox, so it might not be exactly right, but the counter now correctly updates:

https://codesandbox.io/s/passing-context-into-contenteditable-3xzo4

**Comment by gaearon** [comment]
This will only work if you use portals.

**Comment by nidhisridhar** [comment]
This doesn't work if there are multiple slots added. It doesn't also pass the existing value of the counter context to it

**Comment by trueadm** [comment]
@nidhisridhar in my update, I never made it support multiple slots, you'd need to use a fragment for each additional slot you create and map over them in a list. It was only meant to be a quick example to show you how it might work. You also need to invoke a render for the content of the portal to update.

This is how you might make that work: https://codesandbox.io/s/passing-context-into-contenteditable-3xzo4

**Comment by nidhisridhar** [comment]
Thank you, this works!
