### ISSUE TITLE
REACT extenstion doesn;t work

### ISSUE THREAD

**Issue by MongolShudan** [facebook/react#17973]
👉 Please follow one of these issue templates:
- https://github.com/facebook/react/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by ecreeth** [comment]
Please, provide a better description for this issue and if possible, a way of how to reproduce it.

**Comment by bvaughn** [comment]
This issue is not actionable, so I'm going to close it.

If you provide info on what issue you're seeing and how we can reproduce it- we can reopen it.
