### ISSUE TITLE
Add React DevTools to the Microsoft Edge extension store

### ISSUE THREAD

**Issue by brendyna** [facebook/react#17983]
We on the Microsoft Edge Developer Tools team have received a significant number of requests from customers looking to download the ReactJS browser dev tools extension from the Microsoft Edge extension store (in addition to its presence in the Chrome Web Store).

React version: All versions

## Steps To Reproduce

1. Navigate to https://microsoftedge.microsoft.com/addons/category/Edge-Extensions
2. Click on "Developer Tools" category

Link to code example: N/A

## The current behavior
No extension for ReactJS can be found.

## The expected behavior
The ReactJS extension would be in the "Developer Tools" category.

Details for publishing extensions to the Microsoft Edge extension store can be found here: https://developer.microsoft.com/en-us/microsoft-edge/extensions/. Please let us know if we can provide any help.

**Comment by bvaughn** [comment]
Hi @brendyna.

Thanks for reaching out to us. I'm happy to hear that Edge users are excited about the React extension.

Other than uploading the extension to the store, do you anticipate any other significant changes from the version we currently publish to the Chrome store? If not, I'm confident that one of us can find time to submit it soon.

If there may be code changes required, would anyone from your team be interested in lending a hand? Otherwise this feature will likely not be something we work on in the near future. (Our team is pretty small and our current priority focus is on rolling out our new concurrent mode.)

**Comment by brendyna** [comment]
Hi @bvaughn,

You bet! Thanks for the quick response. 

The extension should work the same as in Chrome in the new Microsoft Edge given we're built on Chromium now (in fact, I tried installing the extension from the Chrome Web Store as a sanity check and it seems to work).

The ask from customers, as far as we can tell, is about ease of discovery in our store--so simply publishing it there should solve the problem. If you do run into issues, please do let us know and we can help figure out what's going on and how to fix it.

**Comment by bvaughn** [comment]
Quick smoke test seems promising. Looks like even more advanced features like reload-and-profile and the "copy context menu work. Soon as I figure out if we have a shared Edge store account yet (or if we need to create a new one) I should be able to publish it.

**Comment by leandroruel** [comment]
hey i'm very interested on it too, since now edge is chromium based and the dev tools is basically same as google chrome.

**Comment by hmohamme** [comment]
Hi @bvaughn , I was already working on porting chrome extension to work with Microsoft edge (chromium) and came across this thread today. I have finished the work [here](https://github.com/hmohamme/react/commit/7c7f7686078af6dc560281e25576386a12d58248#diff-84a0b726a11b75b6d34b63eac2a518ff) and would love to send a pull request. 

@brendyna I have submitted the extension for certification on Microsoft partner center as well.

**Comment by bvaughn** [comment]
Sounds great, @hmohamme. Send us a PR~

The biggest blocker at the moment is on my end to just get a shared account with 2fa setup for our team.

**Comment by brendyna** [comment]
@hmohamme and I chatted and we'll leave the extension certification, submission, and publishing up to y'all at Facebook/React (since it's important the team who primarily drives the extension owns the account used to publish it to the Edge store).

@bvaughn, let me know if you run into any issues getting that shared account setup. Happy to enlist our extension team if needed.

**Comment by hmohamme** [comment]
#18041

**Comment by bvaughn** [comment]
Thanks @brendyna. Agreed it's best for our team to setup and own the extension 😄 I'll let you know if we hit snags (other than the current one which is just my time 😅)

Thanks @hmohamme !

**Comment by bvaughn** [comment]
Hi @brendyna! I'm wondering if you might be able to point me in the right direction. I've been trying to get a developer account setup so that I can publish the React extension, but I can't seem to get verified:

![Screen Shot 2020-02-21 at 1 03 35 PM](https://user-images.githubusercontent.com/29597/75071662-a8b79b00-54aa-11ea-8aa5-4e8f96a2f7f9.png)

There's no reason given, and the "Email support" link just takes me to a general FAQ page where there's nothing related that I can find. (The support chat has nothing about add-ons or developer accounts that I see.)

**Comment by bvaughn** [comment]
Well I'm not sure what's going on at this point 😕 

The extension is live now:
https://microsoftedge.microsoft.com/addons/detail/gpphkfbcpidddadnkolkpfckpihlkkil

But the account I submitted it from seems to be in a weird state. I can log into it on account.microsoft.com, but when I open microsoftedge.microsoft.com/addons it shows me as signed out. Clicking "sign in" just redirects me to that same page (still signed out) without showing any login options.

Would really appreciate some guidance if you can provide any, @brendyna

**Comment by brendyna** [comment]
Sorry for the delay on this, @bvaughn. We have an email going internally to help figure out what's going on here. Let me connect a few more dots and I'll follow-up soon. Thanks for your patience!

**Comment by bvaughn** [comment]
No problem! Thank you for the update 🙇

**Comment by bvaughn** [comment]
Secondary, much lower priority question: I'm curious why my fancy promo images (below) don't show up anywhere in the Edge Addons store? 😁 

![react-screenshot-1](https://user-images.githubusercontent.com/29597/75198868-7ca05200-5716-11ea-9a3f-c342e7a4e511.png)

![react-screenshot-2](https://user-images.githubusercontent.com/29597/75198871-7dd17f00-5716-11ea-8cdf-b83f15a1e16f.png)

**Comment by brendyna** [comment]
@bvaughn, to your second question--we have a Store refresh planned which will enable those graphics to show up. We're unable to share a specific ETA for that right now, but coming soon.

For the ingestion and validation issue, could you DM or email me the Seller ID and company name for the extension? I need those two data points to escalate this w/our extension team :)

**Comment by bvaughn** [comment]
> @bvaughn, to your second question--we have a Store refresh planned which will enable those graphics to show up. We're unable to share a specific ETA for that right now, but coming soon.

Ah, gotcha. Neat!

> For the ingestion and validation issue, could you DM or email me the Seller ID and company name for the extension? I need those two data points to escalate this w/our extension team :)

Sure. Where should I DM you at? Your GitHub bio doesn't have contact info :smile:

I'm [@brian_d_vaughn](https://twitter.com/brian_d_vaughn) on Twitter if you want to DM me there.

**Comment by brendyna** [comment]
@bvaughn one follow-up: the extension is published, which seems great, but you're still not able to log into the developer portal with the account used to register it--is that correct?

**Comment by bvaughn** [comment]
@brendyna That is correct. When I try, it auto redirects me to the add-ons store in a logged-out state. So I currently have an extension published that I have no way to manage or update :smile:

**Comment by bvaughn** [comment]
I think this can be closed out :smile: Thanks for your help!

**Comment by bvaughn** [comment]
@brendyna It looks like it's pretty hard to actually find the React devtools extension on the Microsoft website.

If I go here:
https://www.microsoft.com/store/collections/edgeextensions/

And click the "Search" button up top, it takes me here:
https://www.microsoft.com/en-us/search?q=react

That page doesn't even mention any extensions that I see.

This page shows it:
https://microsoftedge.microsoft.com/addons/search/react

Plus if you have the direct link (https://microsoftedge.microsoft.com/addons/detail/gpphkfbcpidddadnkolkpfckpihlkkil) you can find it, but otherwise neither Google nor Microsoft's default search seem to find it.

**Comment by brendyna** [comment]
@bvaughn, this is indeed a confusing experience we're working on. 

The link you pointed to is our old, EdgeHTML extension store. The new store is here: https://microsoftedge.microsoft.com/addons/category/Edge-Extensions

The extension team is doing work on SEO to ensure that link and its sub pages show up higher than the old store, though I imagine that will take some time.

If you search there for "React" or go to the Developer Tools section, you'll see your extension there: https://microsoftedge.microsoft.com/addons/category/Developer-Tools. 

I hope that helps--and apologies again for the confusion. I'll pass this feedback along to our Extension Store team again.

**Comment by bvaughn** [comment]
No problem 😄  Thank you!

**Comment by workforbala** [comment]
couldn't find react developer tools on edge store. also above seems to be not working can we reopen this issue. ?

**Comment by misterjacket** [comment]
> couldn't find react developer tools on edge store. also above seems to be not working can we reopen this issue. ?

same.

https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil

![image](https://user-images.githubusercontent.com/22674987/233112095-f329612b-274d-4fca-8fcf-39e8972185b2.png)

**Comment by PranshuBansalDev** [comment]
Bug filed @bvaughn https://github.com/facebook/react/issues/26675

**Comment by hmohamme** [comment]
Looks resolved.

![image](https://user-images.githubusercontent.com/61028636/234083309-100e952a-89f2-40d6-9212-d7bdc466936c.png)
