### ISSUE TITLE
Bug: Input fields don't behave correctly with undo/redo in react

### ISSUE THREAD

**Issue by PerfectionCSGO** [facebook/react#18018]
React version: 16.12.0 & 16.9

## Steps To Reproduce

1. Type ABCDEFG
2. Click clear
3. CTRL+Z a few times (undo)
4. CTRL+Y (redo)

Link to code example:
[![Edit peaceful-meadow-9hhld](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-meadow-9hhld?fontsize=14&hidenavigation=1&theme=dark)

## The current behavior
ABCDEFG is typed, then cleared and focus is lost, then undoing will return the focus. When redoing ABCDEFG.ABCDEFG is returned with the caret where the dot is.

## The expected behavior
ABCDEFG is typed, then cleared and focus is lost, then undoing will return the focus. When redoing ABCDEFG. is returned with the caret where the dot is.

**Comment by PerfectionCSGO** [comment]
Actually, I just noticed that this can be reproduced here too

https://www.w3schools.com/howto/howto_html_clear_input.asp with pure HTML5.

It would appear that this is a chromium bug? It happens in chrome, electron and opera.

**Comment by matt-curtis** [comment]
Bump — though I'm not yet sure if I'd call this a "react" bug. Setting `input.value` seems to always reset undo/redo history. I'd like to know how and when react calls `input.value` though so this issue can be better mitigated.

**Comment by c-i-a-n-i** [comment]
Bump - Still experiencing the issue exactly as described by @PerfectionVR. It also repros here on the MDN site itself: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset 
To repro, just type in anything in the text box, undo redo a couple of times, then hit reset, focus on the text box again and hit undo, followed by a couple of redos. You will get the bug described.
