### ISSUE TITLE
Argument passed to useState hook or value setter method is mutated

### ISSUE THREAD

**Issue by kcouliba** [facebook/react#18017]
No really sure that is an issue, but I detected that behavior and could not find documentation about it. My guess here is that argument reference is passed down to the value, but I couldn't find where to find the cause in source code.

In a case where 
```jsx
const [value, setValue] = useState(props.data)

const method = (v) => {
  value.v = v
  setValue(value)
}
```

React version: 16.12.0

## Steps To Reproduce

1. Declare a useState hook passing initialState from a prop or outside variable
2. Mutate the value
3. props.data should be mutated

Link to code example: [issue reproduced here](https://codesandbox.io/s/react-hooks-state-management-k4d3z)

## The current behavior
Argument passed to useState or value setter is changed if value mutates

## The expected behavior
Argument should not mutate

**Comment by vkurchatkin** [comment]
Not sure what the problem is here. You mutate `value` and it gets mutated. Why would you expect anything else?

**Comment by kcouliba** [comment]
I'm not sure if it is a real problem, but when I mutate the value, the initialValue passed to useState argument gets mutated as well. I don't know if that's expected.

**Comment by gaearon** [comment]
Yes, that's how JavaScript works. It's the same object, so if you mutate it, you mutate the original object.
