### ISSUE TITLE
Bug: Re-using an SVG element causes quirk with CSS styling

### ISSUE THREAD

**Issue by tomkelsey** [facebook/react#18038]
React version: 16.12.0

## Steps To Reproduce

1. Create an svg with an ID (Element A)
2. Reuse Element A using `<use>` (Element B)
3. Attempt to style the svg using css based on parent element's hover status
4. Hovering over Element A causes the on hover styling to trigger on both Element A and Element B.

Link to code example:

https://codesandbox.io/s/elegant-microservice-gks3f

- public/icon.html is plain html and shows how I anticipated it working. Hover over one button and that button's heart turns blue. 
- src/index.js is using react and shows how it currently works. Hover over the first button and both buttons' hearts turn blue. In addition, hovering over the second button doesn't cause anything to turn blue.

I believe both versions are fundamentally the same but apologies in advance if this behaviour is due to my own coding error!

## The current behavior

Hovering over Element A causes the on hover styling to trigger on both Element A and Element B

## The expected behavior

Hovering over Element A causes the on hover styling to only be triggered on Element A

**Comment by sophiebits** [comment]
1. Your React code uses `class="svg"` but it should be `className="svg"`. (You should see a console warning for it.)
2. Your html uses `.button:hover .svg { color: blue; }` but your styles.css uses `.button:hover .path { fill: blue; }`.

If you fix both of these, then they behave the same. Hope that helps.
