### ISSUE TITLE
Bug: React UMD cannot run in strict mode

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#18040]
React version: 16.2.0

## Steps To Reproduce

Run the code in your console:

> import('https://cdn.jsdelivr.net/npm/react@16.12.0/umd/react.development.js')

## The current behavior

`Uncaught (in promise) TypeError: Cannot set property 'React' of undefined`

## The expected behavior

React get loaded in the browser as `globalThis.React`.

## Suggestion

> Head of https://cdn.jsdelivr.net/npm/react@16.12.0/umd/react.development.js
```js
'use strict';

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.React = factory());
}(this, (function () { 'use strict';
```

The `this` in the last line will always be `undefined` in strict mode. Consider use `this || globalThis`

**Comment by Jack-Works** [comment]
Context about why I need React UMD runs in strict mode:

I'm using a custom code transformer to transform code

```ts
import * as React from 'react'
```

into

```js
import "https://cdn.jsdelivr.net/npm/react@16.12.0/umd/react.production.min.js"
const React = globalThis.React;
```

**Comment by Jack-Works** [comment]
Bump

**Comment by rachelnabors** [comment]
We don't actively support UMD, but if there were a PR for this, we'd take it :)

**Comment by Jack-Works** [comment]
I'm identifying this an upstream(rollup) bug. There is nothing to do with React.

**Comment by gaearon** [comment]
Yeah we'd be happy to bump Rollup if there's a fix.

**Comment by Jack-Works** [comment]
It's working in React 16.13.0
