### ISSUE TITLE
Bug: Complete re-rendering in case of wrapper function

### ISSUE THREAD

**Issue by borakuldeep** [facebook/react#18047]
I observed below when rendering a list component. The list component is taking a search prop and filtering before rendering.

 ```<UserList pattern={search}/>```
when using above statement directly inside parent component, it renders only what changed based on search prop (list remains and only unmatched items got removed), **this is expected.**

But when I wrap the UserList in another function like below:

```const Users = ()=>  <UserList pattern={search}/>;```
and use ```<Users/>``` in parent component, I see that whole list component re-renders when search prop changes. search field is a local state (useState['']).

so, the parent component looks like this now :
```
const App = () => {
const [search, setSearch] = useState('');

const Users = ()=>  <UserList pattern={search}/>;

return (
    <div id="app" className="home-page">
      <Header />
      <WelcomeSlogan/>
      <Users/>
    </div>
  );
}
```
So we know that react re renders full child component(s) if parent component changed, but in this case how the parent (```<Users>```) is changing exactly? Most likely this is not a bug and I am missing some fundamentals here. :)

React version: 16.12.0

## The current behavior
Whole UserList is re rendering.

## The expected behavior
Only updated items should be updated. Same as without wrapper function.

**Comment by vkurchatkin** [comment]
You are right, this is not a bug. When React compares new virtual DOM node with a previous one, first thing it does it checks that the component is the same. If it's not, it unmounts the old one and mounts the new one.

In your case `Users` component is remounted every time, because it is created inside a component and React sees it as a new component on every render.

Rule of thumb: never create a component inside another component.

**Comment by borakuldeep** [comment]
Thanks a Lot. That is the cause but I am wondering how tree comparison is working here
Users -> UserList -> List items
So you saying that if child component changes and needs re-rendering, react re renders parent component too?

**Comment by borakuldeep** [comment]
So since 'search' is local state, every time when it changes, the whole component will re-render (except useState hook) and since I am creating component inside the , it will re create (as a local variable) and hence the remounting issue. :)
