### ISSUE TITLE
Docs: https://es.reactjs.org/docs/state-and-lifecycle.html Spanish translation error

### ISSUE THREAD

**Issue by Zeitgeist-J** [facebook/react#18042]
🚨 This issue tracker is not for documentation issues. 🚨

Within the 'The Data Flows Down' section there is an error on the spanish version, where it would be correct to say :
- '... pueden saber si un determinado componente tiene o no estado y no les debería importar...' 

Instead of:
-  ' ...pueden saber si un determinado componente tiene o no **tiene** estado y no les debería importar...'

**Comment by jeffersonlicet** [comment]
I think both are correct

**Comment by bvaughn** [comment]
Please report translation issues on the translation repo so the folks contributing can review them :)

https://github.com/reactjs/es.reactjs.org
