### ISSUE TITLE
Question: It's not problem just question in my mind

### ISSUE THREAD

**Issue by uxitten** [facebook/react#18053]
Why all implements of hooks in `react-dom` and we have to import from `react`?
Just I want to know about it

**Comment by strdr4605** [comment]
Ask questions on forums like [reactiflux](https://discordapp.com/invite/reactiflux) or https://www.reddit.com/r/reactjs/.

I don't fully understand your question. But as I know:
Hooks are part of React and basic hooks are not tied to any react renderer. 
So we can use hooks with any [renderer](http://iamdustan.com/react-renderers/).

**Comment by uxitten** [comment]
All right.

When I want to use `useState` write this code:
```javascript
import React, { useState } from 'react'
```

But `useState` not wrote in `react` package, actually, it's on `react-dom` package

It's clear?

**Comment by sophiebits** [comment]
In general, the methods you need to define a component are in the React package. This makes it possible to make a single component that works across different renderers, as long as it doesn't use any DOM-specific features. Hope that helps.

I'm going to close this, as it isn't a React issue. If you have more questions, please see our community resources at: https://reactjs.org/community/support.html (this issue tracker is for bugs in React).

**Comment by uxitten** [comment]
Thanks to @sophiebits, overall I got an answer
