### ISSUE TITLE
[eslint-plugin-react-hooks] useReducer purity warning

### ISSUE THREAD

**Issue by hug0b** [facebook/react#18057]
Apparently useReducer shouldn't perform side effects like firing async actions or updating state, so I think there should be an eslint warning for that.

**Comment by vkurchatkin** [comment]
It's not possible to detect side effects with ESLint:

```js
function reducer() {
   // ...
   let foo = bar(); // does bar trigger an effect? No way to tell
  // ...
}

```

**Comment by sophiebits** [comment]
As vkurchatkin says, there isn't a good way to lint for this. Thanks for the idea though.
