### ISSUE TITLE
Bug: Detached DOM node memory leak

### ISSUE THREAD

**Issue by jdolearydl** [facebook/react#18066]
Given a table in react that displays data from an API which can be refreshed with completely new information, I observed a detached DOM node leak (notice the green numbers):

![leakGif](https://user-images.githubusercontent.com/43141484/74743549-93363d00-522e-11ea-8f4a-0b0b7d14b848.gif)

Note: The DOM Nodes seem to settle at 21,000 but there shouldn't be that many nodes anyway, as you can see it starts at 7,000 after the first table generation. In my real-world app, these detached nodes persist even through navigation (with react router).

React version: 16.12.0

## Steps To Reproduce

1.  Open the example [full page](https://nkiu6.csb.app/) (link to code below)
2.  Open chrone dev tools and view the "Performance Monitor" tab
3.  Click the "Regen" button many times
4. Notice that the DOM Nodes increase and even after a GC not all the detached nodes are cleaned up

Link to code example:
[Codesandbox](https://codesandbox.io/s/dank-waterfall-nkiu6)

## The current behavior
The DOM Nodes continue to increase when the table is regenerated, and even after a GC, not enough of the detached nodes are cleaned up.

## The expected behavior
I would expect all the detached nodes to be cleaned up after a GC as they are in [this example](https://codesandbox.io/s/keen-dijkstra-iixif).

**Comment by jddxf** [comment]
I believe it's already fixed in https://github.com/facebook/react/pull/17666. You can confirm it [here](https://codesandbox.io/s/naughty-kalam-qg096).

**Comment by jdolearydl** [comment]
Yes, that resolved it.  Will this be included in the next release?

**Comment by jddxf** [comment]
I don't know for sure but I guess so.

**Comment by kelly-tock** [comment]
anyone seeing this in react 17 as well?

**Comment by kamilzielinskidev** [comment]
@kelly-tock just found it today, these nodes number comes back after few rerenderes but still very tricky thing

**Comment by kelly-tock** [comment]
I eventually found it via heap snapshots, so my case was not react related.
