### ISSUE TITLE
False positives with warning "React Hook useEffect has missing dependencies"

### ISSUE THREAD

**Issue by jaqmol** [facebook/react#18065]
The useEffect() hook produces false positive warnings concerning "React Hook useEffect has missing dependencies" in rare cases.

React version: 16.12.0

## Steps To Reproduce

There are situations in which "React Hook useEffect has missing dependencies" is not correct concerning the problem and implementation logic at hand. Example:

```ts
const [current, send] = useMachine(machine);
const currentMatchesSignedIn = current.matches('signedIn');

useEffect(() => {
    if (currentMatchesSignedIn) {
        send('UPDATE_ENTRIES');
    }
  }, [currentMatchesSignedIn]);
```

`current` represents the current state, `send` is a function that the effect should not depend upon. It would be wrong if the effect would depend upon a change of it.

I had other circumstance in which the warning was plainly wrong, that didn't involve Xstate. It would be nice if there was a way to disable this warning for this rare cases.

**Comment by bvaughn** [comment]
> `current` represents the current state, `send` is a function that the effect should not depend upon. It would be wrong if the effect would depend upon a change of it.

This doesn't sound correct.

The effect you wrote above **uses** `send` (so it **depends** on it). If the effect didn't re-run when `send` changed, then you'd run into [stale closure issues](https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function). (This isn't just theoretical. It is **very likely to happen** if you cheat the rules of hooks 😉)

You *might* be saying that "`send` is stable, it doesn't change" (like the `dispatch` function returned by `useReducer`) in which case- okay, but it still **won't hurt** to specify it in that case.

> It would be nice if there was a way to disable this warning for this rare cases.

Isn't that what `eslint-disable-line` / `eslint-disable-next-line` do? (To be clear, I am not advising you use them in this case.)

**Comment by gaearon** [comment]
As @bvaughn says, the warning is correct. If `send` is truly stable, include it in deps.

**Comment by jaqmol** [comment]
Thanks, understood. I'll invest the time to do the necessary changes.
