### ISSUE TITLE
I'm working on React project.And i got these  errors 

### ISSUE THREAD

**Issue by saichandhra** [facebook/react#18072]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! enlite_starter@1.3.1 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the enlite_starter@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ### ### **C:\Users\Swetha\AppData\Roaming\npm-cache\_logs\2020-02-19T06_52_25_635Z-debug.log**

**Comment by CodefulDom** [comment]
Have you taken a look at the logs?

**Comment by sophiebits** [comment]
I'm going to close this, as it isn't a React issue. If you need help, see: https://reactjs.org/community/support.html
