### ISSUE TITLE
Bug: react-hooks/exhaustive-deps misses a case with useCallback

### ISSUE THREAD

**Issue by jdolearydl** [facebook/react#18079]
The following causes an eslint warning (as it should) 
```
const callback = useCallback(()=> cb(), [])
```
`React Hook useCallback has a missing dependency: 'cb'. Either include it or remove the dependency array. If 'cb' changes too often, find the parent component that defines it and wrap that definition in useCallback. (react-hooks/exhaustive-deps)eslint`

However, the following does **not** cause the warning
```
const callback = useCallback(cb, [])
```
but it should because this line is exposed to the same stale closure bug as the first.

(Maybe this is an antipattern, but in any case, the linter should be able to notice the problem, because this pattern can be used to "get around" the warning)

React version:
16.12.0

Link to code example:
[Codesandbox](https://codesandbox.io/s/boring-wiles-9h26o)

## The current behavior
The linter only notices that the function is missing from the deps array if it is in the form `useCallback(() => cb(), [])`

## The expected behavior
The linter should notice that the function is missing from the deps array in the following form:
`useCallback(cb, [])`

**Comment by vkurchatkin** [comment]
This is definitely an antipattern. Let's say linter would make you write this:


```
const callback =  useCallback(() => cb(), [cb])
```

This code is absolute meaningless as it's essentially the same as `const callback = cb`.

**Comment by yavuzka-cyber** [comment]
thanks for exam

**Comment by jdolearydl** [comment]
So is this not a way to prevent a component that uses hooks from getting the latest callback (preventing the stale closure issue)?
For example, if I pass an arrow function as the callback and then use that callback in useEffect, the linter would dictate that I add the callback in useEffect's dep array, but this would make the effect trigger on every render since the arrow function is technically a different object on every render.
Since useCallback is a hook and hooks don't need to be included in the dep array, wouldn't this prevent that issue of the always triggering effect?

**Comment by outerlook** [comment]
HI! when used this way is an antipattern. But there are cases not redundant where this creates problems. Let's say cb takes 2 args to create another function like this:

`const cb = arg1 => () => {... do something with arg1}`

on use callback I could put this way:
`const _cb = useCallback( cb( myArg ), [ ])`

and it would not show any error unless put this way
`const _cb = useCallback( ( ) => cb(myArg)(), [ ] )`

In real life, there's an example on [react-hook-form](https://react-hook-form.com/api#handleSubmit)`s handleSubmit method, if I wanted to put inside a callback with many other args and methods to send to server, to call just that function on form submission, I could easily miss this useCallback bug.

[Repro](https://codesandbox.io/s/romantic-lamarr-bd3oj) forked from @jdolearydl

**Comment by jdolearydl** [comment]
Yes, this is why, though it is an antipattern, it should still be covered in the linter to prevent misuse.

**Comment by vkurchatkin** [comment]
The only useful thing that linger could do is just warn is you pass anything other that function expression to useCallback

**Comment by gaearon** [comment]
Pretty sure this has been fixed.
