### ISSUE TITLE
Question: what react useCallback do when i pass object in first argument

### ISSUE THREAD

**Issue by KenYPS** [facebook/react#18087]
I am fixing an infinite loop when using react with useEffect and useCallback.

```
const fetchApi =useCallback(()=>{
    setIsLoading(true)
      fetchDataFunction({
        resolve(res) {
          setFetchData(fromJS(res))
          setIsLoading(false)
        }
      })
},[param])
useEffect(()=>{
    fetchApi()
},[fetchApi])

```

It is causing an infinite loop. However, if I change the code as shown below
 
```
const fetchApi = useCallback({
    fetchApiFunc() {
      setIsLoading(true)
      fetchDataFunction({
        resolve(res) {
          setFetchData(fromJS(res))
          setIsLoading(false)
        }
      })
    }
  },[params])
  const { fetchApiFunc } = fetchApi
  useEffect(() => {
    fetchApiFunc()
  }, [fetchApiFunc])
```

the problem is fixed. But I still do not understand what it does when the object in first argument in useCallback. 

Thank you.

**Comment by sophiebits** [comment]
This issue tracker isn't for support questions. Please refer to the React community's help and discussion forums: https://reactjs.org/community/support.html
