### ISSUE TITLE
Bug:  eslint-plugin-react-hooks@2.4.0: Doesn't allow to use quick fix for exhaustive deps in Inteliji IDEs

### ISSUE THREAD

**Issue by oziniak** [facebook/react#18099]
React version: 16
eslint-plugin-react-hooks: 2.4.0

## Steps To Reproduce

1. Install `yarn add -D eslint-plugin-react-hooks`
2. Run IDE (I tried WebStorm and RubyMine)
3. Do an exhaustive deps error:
```
function Component(props) {
    useEffect(() => {
        console.log(props.a);
    }, []);
}
```
4. Observe Webstorm quick fix hint allows only to suppress error pressing control+shift+enter with `// eslint-disable-next-line react-hooks/exhaustive-deps`
![image](https://user-images.githubusercontent.com/23057131/75073519-3ffc0d00-5502-11ea-8c9f-b0d5721ce26d.png)
5. Remove `yarn remove eslint-plugin-react-hooks`
6. Add `yarn add -D eslint-plugin-react-hooks@2.3.0`
7. Restart WebStorm
8. Objserve quick fix hint is shown and error can be fixed with control+shift+enter
![image](https://user-images.githubusercontent.com/23057131/75073740-c0bb0900-5502-11ea-9bc9-e573edcf2809.png)

Link to code example: unavailable

I know it's a weird issue and I have no knowledge where WebStorm or RubyMine take hints for quick fixes, but it's an extremely neat thing once you get used to it. And it looks like some changes introduced in 2.4.0 broke the contract.

**Comment by gaearon** [comment]
This is not a bug. We changed it from autofix to use the ESLint Suggestions API (new in ESLint 6.7) due to common complaints. So **IntelliJ needs to implement support for ESLint Suggestions API** for this to work again. See here: https://github.com/facebook/react/issues/16313#issuecomment-587149109.

cc @prigara Can you route this? Shouldn't be a lot of work.

**Comment by prigara** [comment]
Hi, 
I've filed an issue on our tracker: [WEB-44070](https://youtrack.jetbrains.com/issue/WEB-44070). Please follow it for the updates. Unfortunately, at the moment I can't provide an ETA for it – we now have a feature freeze for the upcoming 2020.1 release. Most probably we'll implement the support for it only in the 2020.2 release.

**Comment by gaearon** [comment]
I'm adding autofix back behind an appropriately named option for people who really need it. Note: if your IDE or lint setup actually fixes it automatically, you do **not** want this. This is only for people who use older IDEs that don't yet support Suggestions and who **don't** run this as an automatic step.

https://github.com/facebook/react/pull/18437

**Comment by liesislukas** [comment]
> IntelliJ needs to implement support for ESLint Suggestions API

they already did that, installing update atm.

WebStorm 2020.1.1
Build #WS-201.7223.93, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
