### ISSUE TITLE
Bug: useState won't update ui when FileList type object set

### ISSUE THREAD

**Issue by yuquanwang** [facebook/react#18104]
I use useState hook to track files change in html input element. When the file changes, console can output correctly when change event fires. but setFileList not work correctly，useEffect didn't  be called and UI did'd be updated.

the first time I choose a image works fine, but the second time works not correctly

React version:react@16.12.0

```typescript

    const [fileList, setFileList] = useState<FileList | null>()

    const handleImageChange: ChangeEventHandler<HTMLInputElement> = (e) => {
        const { target: { files } } = e
        setFileList(files)
    }

    useEffect(() => {
        console.log('file list changed: ', fileList)  // nothing happened

    }, [fileList])
```

**Comment by bvaughn** [comment]
Can you provide a CodeSandbox (https://codesandbox.io/s/new) with a minimal example that reproduces the problem you're reporting? This would help anyone who wanted to look into it.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by yuquanwang** [comment]
> Can you provide a CodeSandbox (https://codesandbox.io/s/new) with a minimal example that reproduces the problem you're reporting? This would help anyone who wanted to look into it.

@bvaughn 
this is the example: [https://codesandbox.io/s/usestate-filelist-error-h5dv1](https://codesandbox.io/s/usestate-filelist-error-h5dv1)

**Comment by yuquanwang** [comment]
My work around is
```typescript
const [fileList, setFileList] = useState<File[]>([])
const handleChange: ChangeEventHandler<HTMLInputElement> = (e) => {
    const { target: { files } } = e
    files?.length && setFileList(Array.from(files))
}
```

**Comment by Ayman-Moukhtar** [comment]
@yuquanwang 
Based on the issue description in your first comment, `useEffect` callback isn't called whenever you add a new file using the input file.
But based on your codesandbox `https://codesandbox.io/s/usestate-filelist-error-b70o8` it's working correctly.
useEffect callback was getting called everytime i append a file to the list.
![image](https://user-images.githubusercontent.com/28701322/75105481-04e9fe80-5614-11ea-8e73-b993cddd9e6c.png)

**Comment by yuquanwang** [comment]
@Ayman-Moukhtar 
as I checked, firefox has the problem, chrome and edge works fine. So maybe it's a compatible issue. I test it on my mackbookpro 2019, the latest firefox version(73.0.1).

**Comment by Ayman-Moukhtar** [comment]
@yuquanwang 
You're right, i was able to reproduce on firefox version `73.0.1`, the reason is that firefox re-uses the same array for modifying the newly added files to the input, as a result.
```
// In handleChange function.
e.target.files === fileList  // true
```
That's why react doesn't re-render, as the state didn't change basically, so there is no need - from react's perspective - for the component to re-render.

**Comment by yuquanwang** [comment]
@Ayman-Moukhtar 
Yes, need to point out that, `e.target.files` and `[...e.target.files]` are different types, the former is a FileList other than Array.

**Comment by akrabulislam** [comment]
Not works for me

`
const Upload = () => {
  const [fileList, setFileList] = useState<File[]>([]);
  useEffect(() => {
    console.log('file list changing: ', fileList);
  }, [fileList]);
  return (
    <div className="file-uploader min-w-[500px]">
      <div className="text-center text-white font-black text-[18px] leading-[25px] py-[24px] border-b border-white/10 uppercase">
        Upload your documents
      </div>
      <div className="content">
        <div className="upload-box w-[100%]">
          <label className="w-[100%] h-[100%] flex flex-col gap-[10px] items-center justify-center pointer">
            <input
              type="file"
              multiple
              hidden
              onChange={(e) => {
                if (e.target.files) {
                  let newFiles: File[] = fileList;
                  for (let k = 0; k < e.target.files.length; k++) {
                    newFiles.push(e.target.files[k]);
                  }
                  setFileList(newFiles);
                }
              }}
            />
            <Image src={uploadIcon} alt="Upload" />
            <p className="text-[12px] ">Browse file to upload</p>
          </label>
        </div>
        <div className="selected-document w-[100%] px-[22px] mt-[10px] max-h-[300px] overflow-y-auto">
          <div>
            {fileList &&
              Array.from(fileList).map((item, index) => {
                return <File key={index} name={item.name} size={item.size} />;
              })}
          </div>
        </div>
        <div className="interaction-button-panel">
          <button className="upload-button">Let&apos;s Begin</button>
        </div>
      </div>
    </div>
  );
};

`

**Comment by akrabulislam** [comment]
Using this solves my problem

`setFileList(Array.from(newFiles));`
