### ISSUE TITLE
Bug: eslint-plugin-react-hooks React Hook  cannot be called inside a callback.

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#18110]
React version:

## Steps To Reproduce

1.
```js
function App(){
   return (
    <div >
      {
        (() => {
          const [item, itemSET] = useState('1')
          return <>
            {item}
          </>
        })()
      }
    </div>
}
```

Link to code example:

## The current behavior

eslint will tell 'React Hook "useState" cannot be called inside a callback.'
## The expected behavior
No error

**Comment by gaearon** [comment]
This is intentional. Only call Hooks at the top level. The pattern you're relying on is dangerous because there is no guarantee the code will only be called once and unconditionally.
