### ISSUE TITLE
Hooks - should use a special character in front of them. i.e. @myHook

### ISSUE THREAD

**Issue by zanecurrie** [facebook/react#18118]
👉 Please follow one of these issue templates:
- https://github.com/facebook/react/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

With regards to hooks naming conventions...
They could use a special character in front of them. i.e. @myHook

https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce

What exactly do the lint rules enforce?
We provide an ESLint plugin that enforces rules of Hooks to avoid bugs. It assumes that any function starting with ”use” and a capital letter right after it is a Hook. We recognize this heuristic isn’t perfect and there may be some false positives, but without an ecosystem-wide convention there is just no way to make Hooks work well — and longer names will discourage people from either adopting Hooks or following the convention.

**Comment by bvaughn** [comment]
Thank you for sharing the suggestion!

The naming convention for hooks is pretty established at this point though. Changing it would add a lot of churn to the entire ecosystem.

😄 Thanks again and I'm going to close this for now.
