### ISSUE TITLE
Bug: Image not loading in the production build

### ISSUE THREAD

**Issue by naveenneog** [facebook/react#18121]
I am using the images by doing the `import IMG from '../path/a.png' way.`
After the` npm run build ` the static/media contains only some images with hashed name others could be embedded in the logo.5d5d9eef.svg . In the production server where this is deployed. I don't see the images rendered which are hashed with data:image/png;base64,iV......w0K format . Where as other images are coming . If I click and open the uri in the browser It does opens the image but in my app it is not rendering. 

Any inputs regarding this would be helpful

React version:16.12

## Steps To Reproduce

1.Create-React-App project
2.Create some image renders  with import IMG from '../path/a.png format
3.npm run build 
4.Deploy in the server 
5.It has generated a data:image/png;base64<long image data>
6.This is rendered as complex instead of the image, which works fine if the url is opened in another tab.
7.
<img width="166" alt="image" src="https://user-images.githubusercontent.com/40742835/75247487-04aa5880-57f8-11ea-92dd-88a086bfee31.png">
8.Why some images are converted to base64 image and others as regular static content.
9.Is there any workaround to avoid and make all the images as static resources.

Any help in this regard is hugely appreciated.

Thanks

Link to code example:

**Comment by hristo-kanchev** [comment]
Can you move this issue to the `create-react-app` rep? -> https://github.com/facebook/create-react-app Thanks!

**Comment by naveenneog** [comment]
Opening this issue in  https://github.com/facebook/create-react-app Thanks! and closing this
