### ISSUE TITLE
EventListeners can not get states after changing

### ISSUE THREAD

**Issue by nimahkh** [facebook/react#18131]
Hello guys. 
I want to click on some boxes and access to delete them with the "delete" button. 
```
React.useEffect(() => {
      document.addEventListener("keydown", (e)=>detectDelete(e), false);
    }, []);
```
> Now the detectDelete can not find that the states are changed.

**so I change the code to this:** 

```
React.useEffect(() => {
      document.addEventListener("keydown", (e)=>detectDelete(e,states), false);
    }, [states.selectedType, states.selectedId]);
```

Now, this code is run every time. but what I have is the states and their previous. 
for example:

the first time I get : 
```
Object { selectedId: 0, selectedType: "image" }
```

but after changing state I will get : 

```
Object { selectedId: 0, selectedType: "image" }
Object { selectedId: 0, selectedType: "gesture" }
```

The state is ok outside of listener. it is just happening in the `detectDelete` function

**Comment by nimahkh** [comment]
For who they have same problem: 
I just change the document to my current DOM:

```
function listen(e){
      e.currentTag.addEventListener("keydown", (e)=>detectDelete(e,states), false);
    };
```

**Comment by Sin9k** [comment]
@nimahkh You have to remove listener each time when you change onKeyDown and add listener again. You can't pass arrow function to addEventListener, because you need to pass same function to addEventListener and to removeEventListener

```
const onKeyDown = useCallback((event) => detectDelete(event, states), [states])

useEffect(() => {
  document.addEventListener("keydown", onKeyDown);
  return () => {
    document.removeEventListener("keydown", onKeyDown);
  }
}, [onKeyDown])
