### ISSUE TITLE
setState takes type State but it should be Partial<State>

### ISSUE THREAD

**Issue by ORESoftware** [facebook/react#18134]
Not sure where TS typing complaints belong, I have this one:

![Screenshot from 2020-02-25 17-13-18](https://user-images.githubusercontent.com/11139560/75302291-27d20980-57f2-11ea-9ad9-3dad9ef128d1.png)

As far as I know it should be `Partial<State>` not `State` for the type. Here is the type of setState() 

```js
    function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];
```

but this is better:

```js
    function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<Partial<S>>>];
```

**Comment by jquense** [comment]
The useState hook isn't like setState in a class it completely replaces the previous value on update. So "partial" updates like your example would leave state without hotReloadState
