### ISSUE TITLE
Bug: No matching version found for scheduler@^0.19.0

### ISSUE THREAD

**Issue by ciroanni** [facebook/react#18148]
Error "No matching version found for scheduler@^0.19.0"  during npm i

React version: 16.8

## The current behavior
<img width="558" alt="Schermata 2020-02-27 alle 10 44 30" src="https://user-images.githubusercontent.com/41707194/75432089-27e71c00-594e-11ea-8998-73366ba262f0.png">

## The expected behavior
install works

**Comment by eps1lon** [comment]
The registry is always a bit lagging behind. Babel has the same issue. Give it a few hours and it should work. 

[`scheduler@0.19.0`](https://www.npmjs.com/package/scheduler/v/0.19.0) is actually released.

**Comment by ciroanni** [comment]
I know... I had same issue with babel in the past. 
how many hours should I wait?  I cant force to use previous version because I'm installing and building in CI.
thanks

**Comment by gaearon** [comment]
It’s definitely on npm. Maybe you’re behind a lagging proxy. Unfortunate this isn’t something we can help with.
