### ISSUE TITLE
Bug: React DevTools ignores displayName on React.memo components

### ISSUE THREAD

**Issue by lxender** [facebook/react#18146]
Components wrapped in React.memo don't have a display name in the "components" tab of React DevTools.

React version: 16.13

## Steps To Reproduce

1. create a component that uses React.memo
2. name the component using "displayName"
3. open DevTools
4. the component will not use the name from step 2

```jsx
const Test = React.memo(({ message }) => {
    return <h1>{message}</h1>;
});
Test.displayName = "Foo"; // Will be displayed as "Anonymous"

function App() {
    return (
        <Test message="Hi" />
    );
}
```

## The current behavior
Memos ignore "displayName" in React DevTools

## The expected behavior
Memos show "displayName" in React DevTools

**Comment by eps1lon** [comment]
Looks like a duplicate of #18026

**Comment by lxender** [comment]
Oh yea, sorry
