### ISSUE TITLE
Bug: ENOTFOUND -3008 on react-scripts start without root permissions

### ISSUE THREAD

**Issue by NathanPB** [facebook/react#18142]
When I try to run ``react-scripts start`` in a react project the command crashes immediately. If I run it with root permissions then the command just succeeds and works as expected. Running with sudo every time is quite boring. It also messes up my ``nvm`` environment and doesn't let me use my IDE debugger. 

React version: 16.12.0

## Steps To Reproduce

1. Run ``$ npx create-react-app hello-world``
2. Run ``$ cd hello-world``
3. Run ``$ npm start`` or ``$ react-scripts start`` (If ran with sudo it just works)
4. Face the crash

Since this is a platform specific issue, I'm leaving all the important specifications here:
Please ask if you need some other information
- OS: ``OpenSUSE Tumbleweed 20200214``
- Kernel Version: ``linux 5.5.4`` (I'm facing this issue for months actually, so previous versions are included)
- Bash Version: ``GNU bash, version 5.0.11(1)-release (x86_64-suse-linux-gnu)``
- Node Version: ``v10.16.1`` (Tested with several major versions, including v9, v10, v12, v13)
- My ``$ env`` (separated GIST because Its pretty long): https://gist.github.com/NathanPB/18861c712b22ad392e172bc3388a575a

I don't now if that's important, but I use ``nvm`` to manage the node installations

Link to code example: Not Applicable

## The current behavior
It crashes with the following output:
```
nathan@linux-kpfq: ~/Projects/hello-world> react-scripts start
Attempting to bind to HOST environment variable: linux-kpfq
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://bit.ly/CRA-advanced-config

events.js:196
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND linux-kpfq
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1492:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'linux-kpfq'
}
```

## The expected behavior
The command should run without needing root permissions.

**Comment by gaearon** [comment]
Please file this in https://github.com/facebook/create-react-app/.
