### ISSUE TITLE
[eslint-plugin-react-hooks] Bug: exhaustive-deps not working with function declaration

### ISSUE THREAD

**Issue by yuriybelike** [facebook/react#18176]
When extracting a `useEffect` callback from inline to a funcion declaration, the `exhaustive-deps` rule stops showing warnings related to the referenced function

React version: `16.12.0`
eslint-plugin-react-hooks version: `1.7.0`

## Steps To Reproduce

1. Add a basic `useEffect` code which doesn't declare one of the dependencies in the array (`tmp`)

```jsx
  const [tmp, setTmp] = useState("");

  useEffect(() => {
    console.log(tmp);
  }, []);
```

2. ESLint shows the `exhaustive-deps` warning
3. Extract the `useEffect` callback to a function declaration

```jsx
  const [tmp, setTmp] = useState("");

  function sideEffect() {
    console.log(tmp);
  }

  useEffect(sideEffect, []);
```

Link to code example: https://codesandbox.io/s/summer-sunset-oie9s

## The current behavior

ESLint plugin does not show the `exhaustive-deps` warning

## The expected behavior

ESLint plugin should work even if the `useEffect` callback isn't inline

**Comment by vkurchatkin** [comment]
Never do this. There is no good reason to do this, but it is very hard to make `exhaustive-deps` support this pattern

**Comment by Voronar** [comment]
> Never do this. There is no good reason to do this, but it is very hard to make `exhaustive-deps` support this pattern

This is good point.
For effect reusage it would better to use custom hooks.

**Comment by yuriy636** [comment]
The effects weren't meant to be reused, the goal was to have a name for them, in order to not have to read the impl to understand what they do.

Is there any pattern for this? I preffered this approach over custom hooks because the code is coupled to the component and is not really reusable and also didn't feel like creating a hook for every useEffect in my app.

**Comment by vkurchatkin** [comment]
>  the code is coupled to the component and is not really reusable 

This shouldn't be matter. You can have your hook unexported in the same file, with a meaningful name.

**Comment by yuriybelike** [comment]
_Sorry for deleting the previous comment, wrong account._

The effects weren't meant to be reused, the goal was to name them, in order to avoid having to read the impl to understand what they do.

I preffered this approach over custom hooks because the code is coupled to the component and is not really reusable.

**Comment by yuriybelike** [comment]
> > the code is coupled to the component and is not really reusable
> 
> This shouldn't be matter. You can have your hook unexported in the same file, with a meaningful name.

I guess that could be the solution although it feels weird reading `useFoo()` without it being an app-wide hook.

**Comment by vkurchatkin** [comment]
Consider this: you often extract some code into components, although it is used only in one place. You do this to make it easier to read and reason about code, not for reuse. The same applies to hooks.

**Comment by gaearon** [comment]
This is a known bug https://github.com/facebook/react/issues?q=is%3Aopen+is%3Aissue+label%3A%22Component%3A+ESLint+Rules%22

A fix would be welcome!

**Comment by gaearon** [comment]
oops I meant https://github.com/facebook/react/issues/16573
