### ISSUE TITLE
Bug: ServiceWorker MIME Type Error ('text/html') on register

### ISSUE THREAD

**Issue by SeanMoody** [facebook/react#18193]
Service worker is giving the following error when attempting to register:
Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/sw.js'): The script has an unsupported MIME type ('text/html').
console.<computed> @ index.js:1

sw.js is showing in the sources tab of the Chrome dev tools, but not registering..

React version: 16.12.0

Error Message:
<img width="955" alt="Screen Shot 2020-03-02 at 4 42 54 AM" src="https://user-images.githubusercontent.com/44378095/75659450-6297cf80-5c40-11ea-9760-7b47e97c6d5f.png">

## Steps To Reproduce

1. Register a Service Worker in React (change from unregister to register, or place SW code directly in index.html, or use a simpler SW. All cause the same error when running, in either dev or a build react app.)

SW Example:

```
export function register() {
 if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('./sw.js')
      .then(function (registration) {
        // Successful registration
        console.log('Hooray. Registration successful, scope is:', registration.scope);
      }).catch(function (error) {
        // Failed registration, service worker won’t be installed
        console.log('Whoops. Service worker registration failed, error:', error);
      });
  }
}
```

## The current behavior
Service worker does not register due to the above error

## The expected behavior
Service worker registers

**Comment by threepointone** [comment]
Please file this issue at https://github.com/facebook/create-react-app/issues
