### ISSUE TITLE
Warning: Unknown DOM property for. Did you mean htmlFor?

### ISSUE THREAD

**Issue by ForbesLindesay** [facebook/react#1819]
I get this warning whenever I attempt to use the `for` property on a `<label>` element.  See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label for a description of the `for` attribute.

**Comment by rodryquintero** [comment]
How do I know which react component is using the "unknown" attribute? I am having trouble finding the faulty component/element displaying this warning

**Comment by jabhishek** [comment]
The message means that 'for' is unknown. Use htmlFor instead of that.

**Comment by zpao** [comment]
I prefer the tried and true "search all my files" since this is a very specific case. Here's how you could do it with `grep`. You IDE probably also has a "find all in project" feature.

```sh
grep -rn 'for=' <path>
```

**Comment by rodryquintero** [comment]
Thanks guys for all the tips.

**Comment by jafelds** [comment]
Thanks - this was helpful.  It would be great if the warning showed up with the offending line of code in the console (it comes with a reference to warning.js, which isn't very helpful).

**Comment by milesj** [comment]
On a side note, why is it `htmlFor` instead of `for`?

**Comment by rodryquintero** [comment]
@milesj, that his how you have to set the attribute when using ´jsx´. Using for will generate a warning/error.

**Comment by milesj** [comment]
I am aware, but why? Is it because "for" is a language construct? Simply wrap the attribute for in quotes.

**Comment by rodryquintero** [comment]
@milesj, I wondered the same but I guess the reactjs developers have a good reason to do this :)

**Comment by zpao** [comment]
Please read the above discussions and links. Our reasoning is covered.

**Comment by youngBrain1893** [comment]
When I want to pass the property `itemId` to a children Component  as part of it's props, I got the warning in my console: 

    Unknown DOM property itemId. Did you mean itemID?

It's just a normal property, should I change it to `itemID` to fix it?

**Comment by xgqfrms-GitHub** [comment]
# react htmlFor


https://facebook.github.io/react/docs/dom-elements.html#htmlfor

**Comment by AMorgaut** [comment]
I find this Error message counter intuitive

Looking at:
> Warning: Unknown DOM property for. Did you mean htmlFor?

Any Wev developer new to React (or used this attribute for the 1st time) will think 
> WTF! how can the DOM `<label>` `"for"` property be Unknown! It's been here for ages !

A more accurate Error message could be something like
> Warning: Unknown JSX property for. Did you mean htmlFor?

This would more rapidly point to the right direction

**Comment by Jaikangam93** [comment]
> if you're using JSX you suppose to use `htmlFor` instead of `for`

Thanks this solve the problem
