### ISSUE TITLE
Bug: Switching type of button causes it to submit the parent form

### ISSUE THREAD

**Issue by batzz-00** [facebook/react#18197]
Just react on its own, no extra packages. I'm not sure if this is intended behaviour, or if there are any related issues. If it is intended what is the suggested approach to stop it from happening?

React version: 16.12

## Steps To Reproduce

1. Create a simple component with one element in the state type that defaults to "button"
2. Create a <button type={type} /> within a <form>
3. On click set the state of the type to anything other than "button"
4. If you catch the onSubmit of the form you should notice that the form submits on click of the button even though when clicked the type was "button", which should not submit the form

Link to code example: https://codesandbox.io/s/jovial-cloud-5ooku

## The current behavior
The button type switches and automatically submits the form without a second click

## The expected behavior
The button type switches and the form is not yet submitted until the second click.

**Comment by jddxf** [comment]
I think it's how browser works.
https://codesandbox.io/s/gracious-morning-1ikef

**Comment by batzz-00** [comment]
Yeah it seem's so my bad, for anyone that gets this issue the easiest (though ugly) way to do this seems to be to simply wrap a settimeout to the switching of the button type after the button is clicked (setstate in my case). If there are any other/cleaner approaches please feel free to reopen?
