### ISSUE TITLE
Feature: extend propTypes functionality

### ISSUE THREAD

**Issue by adeelibr** [facebook/react#18200]
React version: Latest

## More of a feature request 😄 

```
const Parent = ({ x, y }) => <p>{x}{y}</p>;
Parent.propTypes = {
  x: PropTypes.string,
  y: PropTypes.string,
};

const Child = ({ a, b, x, y }) => {
  return (
    <div>
      <Parent x={x} y={y} />
      <p>{a}</p>
      <p>{b}</p>
    </div>
  );
};
Child.propTypes = {
  a: PropTypes.string,
  b: PropTypes.string,
  ...PropTypes.extend(Parent), // => Can this be possible?
};
```

Link to code example:

- shared the code snippet in the issue itself 😅 

## The current behavior

The current behaviour doesn't let you extent propTypes functionality from one component to the other. I see this as a very common practise for e.g, in UI libraries where you build components on top of other components. For example a `BaseButton` & on top of it you will build `PrimaryButton`, 'SecondaryButton` where the 2 buttons extend on `BaseButton` functionalities.

The functionality itself works, but there is no one in `propTypes` to have a feature where it can inherit props from it's parent class.

For my use case, in my UI library I am trying to generate an API table from `propTypes` section of the component, but since I can not extend props from class I have to manually re-add each prop from parent component to child component for API generation.

## The expected behavior

The propTypes does not have a feature where you can extent props from a certain component.

**Comment by adeelibr** [comment]
If you think this is valid feature request. I would love to help on this issue, I would need help on guidance though :)

**Comment by gaearon** [comment]
Hi, we don't plan to add more features to PropTypes. However, this probably does what you want:

```js
Child.propTypes = {
  a: PropTypes.string,
  b: PropTypes.string,
  ...Parent.propTypes
};
```
