### ISSUE TITLE
Bug: [eslint-plugin-react-hooks] exhaustive-deps doesn't allow for array hashing

### ISSUE THREAD

**Issue by cowboy** [facebook/react#18214]
I'm not sure how to file this. Please let me know if I need to adjust anything. Thanks!

React version: 16.13.0

## Steps To Reproduce

1. Create a `useEffect` hook that accesses an array whose identity might change, even when its contents do not
2. Attempt to provide a hashed value of the array as a dependency
3. See `react-hooks/exhaustive-deps` give the following error: **"React Hook useEffect has a missing dependency"**

![image](https://user-images.githubusercontent.com/54051/75925359-93415a00-5e36-11ea-8675-5cceced3e1e1.png)

![image](https://user-images.githubusercontent.com/54051/75925362-96d4e100-5e36-11ea-93b1-3ce713c1356d.png)

Link to code example:

https://codesandbox.io/s/eloquent-hellman-8n4hz

## The current behavior

There doesn't seem to be any way to tell exhaustive-deps to allow a function to be used to calculate a deterministic hash of a dependent array for the purpose of knowing when that array's contents have changed (since `useEffect` compares arrays by identity, not by contents)

## The expected behavior

There should be _some_ way to do this?

**Comment by vkurchatkin** [comment]
> There should be some way to do this?

There is: `eslint-disable-next-line`

**Comment by cowboy** [comment]
> There is: `eslint-disable-next-line`

Sure, that's what I'm doing right now. I just wanted to see if there was an official opinion on this!

**Comment by softberry** [comment]
Try this Solution:
```
const getIdsArrayHash = useMemo(()=>ids.join("-"),[ids]);
  useEffect(() => {
    addLog(`ids array contents changed to ${ids}`);
  }, [getIdsArrayHash,ids]);
```

**Comment by gaearon** [comment]
Silencing the lint is the appropriate solution here. That's essentially the same thing you're asking for — a way to mark some code as "I know what I'm doing".'
