### ISSUE TITLE
Dev tools feature: I'd like make PR to add toggle ability for boolean prop/state types.

### ISSUE THREAD

**Issue by shahzeb1** [facebook/react#18219]
Hello, on the now archived react-devtools repo I had worked on the ability to toggle (via a `checkbox` input) boolean values (from `true` to `false` and viceversa). I was unable to merge my PR because that repo was getting archived.

Do I have permission to add this feature into this repo and make a PR?

It would be a solid feature to have so that devs don't have to type "true" and "false", we could just click the `checkbox` input. 

Thank you.

**Comment by threepointone** [comment]
could you set the value to undefined/null (or any other non boolean) if needed? It might not be common, but your change would make it impossible to do so, no? 

cc @bvaughn

**Comment by bvaughn** [comment]
You're always welcome to make a PR to propose a UX change, @shahzeb1. I can't promise it will get merged though. The DevTools editing interface allows you to change between types in a way that a simple toggle wouldn't enable. `undefined` -> `boolean` or `boolean` -> `undefined` is one such example. I would not be open to any change that breaks this ability.

**Comment by shahzeb1** [comment]
Good point. Yes a checkbox would just toggle booleans and not be able to set it to `undefined` (unless you change the value of the string, which is already the case).

Thanks for the quick feedback.
