### ISSUE TITLE
Bug: SVG is not rendering after ant version 4 

### ISSUE THREAD

**Issue by adorearun** [facebook/react#18211]
I am using ant in my application which has gmaps. I also render markers using custom svg in maps. I am testing latest ant version 4 in my application , as soon as I upgrade to latest version 4 all markers which are supposed to show in my gmaps is not visible. there were no console logs or issues in browser.

React version: ^16.10.1
React Dom version : ^16.10.1
ant version : ^4.0.1

## Steps To Reproduce

1. After upgrade to ant 4 , all my svg is not visible
2.

## The current behavior
If i use ant version ^3.23.5 , everything seems to be working fine. Only after upgrade to version 4 its not working

**Comment by bvaughn** [comment]
@adorearun What makes you think this is a React bug?

From the limited amount of info in the description, I would suggest filing it in the Ant repo.

**Comment by adorearun** [comment]
Sorry about the confusion , closing it.

**Comment by bvaughn** [comment]
No worries :)
