### ISSUE TITLE
link test build then Can't resolve './cjs/react-dom.development.js'

### ISSUE THREAD

**Issue by GoToBoy** [facebook/react#18225]
React Source Code version: 16.13.0

## Steps To Reproduce

1. clone react souce code 
2. yarn build react and react-dom then link them ( [from doc  ](https://reactjs.org/docs/how-to-contribute.html)
<img width="980" alt="image" src="https://user-images.githubusercontent.com/2384105/76006565-a4c65700-5f47-11ea-9c48-399e37dcd268.png">

3. cd myProject( clean project from create-react-app)
4. link react and react-dom  then yarn start

## The current behavior
<img width="656" alt="image" src="https://user-images.githubusercontent.com/2384105/76006337-48633780-5f47-11ea-8a70-c1b78f292f78.png">

## The expected behavior
server ok

**Comment by GoToBoy** [comment]
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/2384105/76006956-3fbf3100-5f48-11ea-8323-1c929eb9d129.png">
it seems that wrong happen at yarn build step

**Comment by kunukn** [comment]
Can you change the path from `/cjs/` to `/umd/` and try again?

**Comment by gaearon** [comment]
You need to build `--type=NODE` for npm packages. 
I clarified in https://github.com/reactjs/reactjs.org/commit/b3c7540a10498328d981e38731253ffa0e1798d4.
