### ISSUE TITLE
DevTools: Standalone version should remember last opened tab

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#18227]
Currently the "Components" tab is always opened by default. This should be a sticky preference such that if the "Profiler" tab was opened last, re-opening the [standalone DevTools](https://www.npmjs.com/package/react-devtools) should open "Profiler" by default again.

Note that these shortcut keys should **only** be implemented for the standalone DevTools since these tabs are part of the browser chrome for the web extension.

**Comment by felgeekpe** [comment]
Hi @bvaughn, I'd like to take this ticket

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
I'm going to go ahead and roll this into #18226 :smile:

**Comment by bvaughn** [comment]
Implemented via #18248
