### ISSUE TITLE
Why not using a loop?

### ISSUE THREAD

**Issue by kerolloz** [facebook/react#18237]
I don't understand why this file is written the way it is
https://github.com/facebook/react/blob/4027f2a3b82ecc325224f7827fc2c8e71a284279/packages/react-devtools-shared/src/devtools/views/Settings/SettingsContext.js#L233-L349
Is there a reason for doing it this way and not using a loop? should I open a PR and refactor it to use a loop?

**Comment by sagar-gavhane** [comment]
This looks a weird way of writing code.

**Comment by bvaughn** [comment]
> Is there a reason for doing it this way and not using a loop?

Subjective preference. :smile:

> should I open a PR and refactor it to use a loop?

No. There isn't really any objective benefit for rewriting this section of code.
