### ISSUE TITLE
Bug: React-Devtools not recognizing specific webapp in firefox

### ISSUE THREAD

**Issue by joepio** [facebook/react#18236]
React version: 16.11.0
Firefox: 73.0.1
OS: MacOS 10.15.3
Project: [argu.co](https://argu.co)

## Steps To Reproduce

1. Open [argu.co](https://argu.co) in Firefox 73.01 on a Mac with Devtools installed
2. Open devtools (cmd + opt + i), no react devtools shown

Other react pages work fine in Firefox, and argu.co works fine in Chrome, too!

**Comment by hristo-kanchev** [comment]
Duplicate of: #17997
