### ISSUE TITLE
Useeffect asynchronous processing reported a warning

### ISSUE THREAD

**Issue by lgf196** [facebook/react#18249]
The code is as follows：
```jsx
useEffect(() => {
  init();
}, [pagaTion, tagName]);
const init = async () => {
  let res = await fontManage({ ...pagaTion, tagName });
  res.code === successCode && setGetData(res.data);
};
```
The warning message is as follows：`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function`

**Comment by threepointone** [comment]
Please share a codesandbox link with a reproducible example, it’s unclear from your snippet what the behaviour is.

**Comment by threepointone** [comment]
it's likely that your component is unmounting (for whatever reason) before the async call completes. In which case, the warning is correct.

**Comment by aweary** [comment]
https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies). It's possible that the component using this hook unmounts before `fontManage` resolves. You can use a local variable to track that, so you don't end up calling `setGetData` on an unmounted component.

```js
useEffect(() => {
  // Component is initially mounted...
  let mounted = true;
  const init = async () => {
    let res = await fontManage({ ...pagaTion, tagName });
    // Check mounted before calling setGetData
    res.code === successCode && mounted && setGetData(res.data);
  };
  init();
  return () => {
    // Set mounted to false in the effect's cleanup method
    mounted = false;
  };
}, [pagaTion, tagName]);
```
