### ISSUE TITLE
Shallow copy of the arguments in createElement can be improved for better performance

### ISSUE THREAD

**Issue by suthagar23** [facebook/react#18252]
In `createElement` method, there are few lines to shallow copy the arguments to `childArray`. 

- As it has to exclude the first two arguments, we can use `slice(2)` since the current implementation and slice will do the shallow copy of the arguments, and `slice` shows a better performance than doing it with a `for` loop.

React version: 16.13.0

## Steps To Reproduce

N/A

Link to code example: https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js#L526-L535

## The current behavior

1. Shallow copy the arguments to a newly created array using For Loop.

## The expected behavior

we can change it using `arguments.slice(2)` as it does a shallow copy of the rest of the arguments from index 3.

Just done a benchmarking for two types of implementation, and seems the slice is better than the For Loop-based implementation,

```
function fnUsingLoop(a,b,c,d,e,f) {
    childrenLength = arguments.length
    childArray = Array(childrenLength);
    for (let i = 0; i < childrenLength; i++) {
      childArray[i] = arguments[i + 2];
    }
	return childArray;
}
d1 = performance.now();
for(i=0; i< 100000; i++) { 
	fnUsingLoop(1,'a', () => {}, [1,2], {}, 1);
}
d2 = performance.now();
console.log("Taken for Loop : ", d2- d1);

function fnUsingSlice(a,b,c,d,e,f) {
	return Array.prototype.slice.call(arguments, 3);
}
d3 = performance.now();
for(i=0; i< 100000; i++) { 
 fnUsingSlice(1,'a', () => {}, [1,2], {}, 1);
}
d4 = performance.now();
console.log("Taken for slice : ", d4- d3);

```

**Comment by suthagar23** [comment]
Please check and let me know if it's required. So I can add a PR for this improvement  :-)

**Comment by eps1lon** [comment]
You probably mean `slice` not `splice`. Code uses `slice` but description uses `splice`.

**Comment by eps1lon** [comment]
Also: [You can't slice `arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments). You'd have allocate an empty array first. At that point it's unclear if this is in fact faster. Your benchmark does not accurately display how this would be implemented.

**Comment by suthagar23** [comment]
Yes, updated the description with `slice`.  As you mentioned, we can't use the `slice` directly for `arguments`, but we can use shallow copy and do a slice like `[...arguments].slice(3). 
I have updated the benchmarking thereby reflecting the actual implementation.

**Comment by gaearon** [comment]
I think we'd need more convincing benchmarking for this. Microbenchmarks are [easy to get wrong](https://mrale.ph/blog/2014/12/24/array-length-caching.html). Can you prepare something more substantial, ideally with calls to actual `createElement` inside a compiled React bundle? We have some abandoned benchmarks [here](https://github.com/facebook/react/tree/master/scripts/bench) so maybe you could use that.

**Comment by suthagar23** [comment]
Thanks, @gaearon, Let me work on this and do a benchmarking for this change
