### ISSUE TITLE
Bug: React Fast Refresh only updates DOM of web pages with a http:// location.protocol

### ISSUE THREAD

**Issue by wis** [facebook/react#18259]
after quite a bit of debugging of Parcel 2's [`hmr-runtime.js`](https://github.com/wis/parcel/blob/bb8ae0a5d81d8fd31ba8a677a7e69fda2c65ab06/packages/runtimes/hmr/src/loaders/hmr-runtime.js) (from the web page that it gets injected by the bundler and loaded into), I see that the changed modules/components are received and updated but on React's part, it's not updating the DOM, **that's** why I'm opening this issue here and not in [parcel-bundler/parcel](https://github.com/parcel-bundler/parcel).

React version:
```json
  "dependencies": {
    "react": "^16.13.0",
    "react-dom": "^16.13.0"
  },
```
## Steps To Reproduce & Link to code example:

to use React Fast Refresh, with web pages that have a `file://`, we'll use Parcel 2's implementation,

1. clone yet to be up-streamed Parcel 2 from [wis/parcel](https://github.com/wis/parcel), which supports watch mode only HMR + React Fast Refresh. you only need to run `yarn install` and that's it, to use its CLI use `./packages/core/parcel/src/bin.js`
2. clone [wis/SWEB-react](https://github.com/wis/SWEB-react)
   - yarn install
   - update the path to the CLI in the `bin` script of scripts in package.json with the path to the cloned Parcel repo in step 1.
   - yarn start
3. open the compiled HTML files in the browser from disk, URL should look like `file:///home/x/dev/SWEB-react/build/pages/options.html` or `chorme-extension://<UUID>/options.html`
4. change a top level Component like `Options`, a full page refresh occurs, which I believe was designed to happen, but try changing a child/nested component like `Componentx`, the DOM doesn't update.

## The current behavior
only full page refresh is working for top level components like `Options` and `Popup`,
React Fast Refresh works for nested components, e.g `Componentx`,
only when the web page is served form with a server (with the `serve` command)
and has an `http://` URL scheme, and not when the web page is that's of an opened 
HTML file from disk with a `file://` URL scheme or of a browser extension with a 
`moz-extension://` or `chorme-extension://` URL scheme (that's built with the `watch` command),
the bundler, Parcel 2, loads the updated modules/components and [clears the console](https://github.com/wis/parcel/blob/bb8ae0a5d81d8fd31ba8a677a7e69fda2c65ab06/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L60)
but the components don't get updated.

## The expected behavior
the DOM updates after the changed components/modules get updated by the bundler runtime.

**Comment by gaearon** [comment]
Thanks for the information. To be honest this is quite a complicated setup to reproduce an issue. Any chance you might want to dig into the code yourself to figure out why it's not updating. I'd be happy to give pointers.
