### ISSUE TITLE
[Dependencies] React uses both array-unique and array-uniq

### ISSUE THREAD

**Issue by nainardev** [facebook/react#18264]
React version: 16.13.0

## Steps To Reproduce

1. See https://github.com/facebook/react/issues/18264#issuecomment-597066824

## The current behavior
These two packages does the same thing.
[array-uniq](https://github.com/sindresorhus/array-uniq) is better as it uses Set, while [array-unique](https://github.com/jonschlinkert/array-unique) is last updated years ago. why two packages doing same thing

## The expected behavior
Uses either one

**Comment by threepointone** [comment]
I'm not sure what you mean, we don't use either of those? https://github.com/facebook/react/blob/master/package.json

**Comment by nainardev** [comment]
sorry, in yarn.lock

https://github.com/facebook/react/network/dependencies
look into `Dependencies defined in yarn.lock` section

**Comment by threepointone** [comment]
We can’t do much about what our dev dependencies pull in. This isn’t really an issue, but thanks for the concern!
