### ISSUE TITLE
set blank_issues-enabled to false in config.yml

### ISSUE THREAD

**Issue by nainardev** [facebook/react#18269]
Anyways blank issues will be closed, so why allow them in the first place?

Thus, disable Blank Issue option in config.yml
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by threepointone** [comment]
People often submit issues that don't use the standard template, and I don't think we want to lock out every one at the moment. It's alright. Thanks!
