### ISSUE TITLE
Discussion : Attribute Behavior Fixture Optimization

### ISSUE THREAD

**Issue by taejs** [facebook/react#18263]
computer spec 
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Microsoft Windows 10 Pro

## The current behavior
Attribute Behavior Fixtures is composed of table element
When I scroll it, it's frozen for a long time(few minutes or more)

## The expected behavior
In my opinion, we need optimization for this.
One of solution is using react-window library.

**Comment by gaearon** [comment]
This fixture is for internal usage. If you can make it faster that's cool, but it's not a priority for us.
