### ISSUE TITLE
Bug: does useState block dom event ?

### ISSUE THREAD

**Issue by dinfer** [facebook/react#18276]
React version:16.13.0

## Steps To Reproduce

I created a code pen to reproduce the problem

Link to code example: https://codepen.io/dinfer/pen/zYGRdmZ

## The current behavior

1. `useState` api blocks the mouseevent.

onMouseMove is just called one time no matter how I move my mouse on the circle element, but when I comment `setPos({ ...p.meta });`, I receive all the events as mouse moves.

2. I cannot see the component in devtools if I use react to create SVG element.

does react support handling the SVG elements?

![image](https://user-images.githubusercontent.com/11496403/76431598-c2366d80-63ec-11ea-9abe-7b27a97892d6.png)

## The expected behavior

1. `setPros`, returned by useState API, do not block `onmousemove` event.

2. I can view the svg based component information just like dom based component in the devtools.

**Comment by eps1lon** [comment]
> let el = null;

This is set to `null` everytime you call `setPos`. You want to use a ref instead: 

```jsx
let el = React.useRef(null);
...
el.current = e.target
...
e.target === el.currennt
```

**Comment by dinfer** [comment]
Thanks, It's my bad.
