### ISSUE TITLE
Bug: DevTools Profiler doesn't show selected commit

### ISSUE THREAD

**Issue by gaearon** [facebook/react#18284]
I don't see the selection at all. My version is 4.5.0. I think this regressed.

<img width="266" alt="Screenshot 2020-03-11 at 23 40 37" src="https://user-images.githubusercontent.com/810438/76475966-6d005900-63f8-11ea-8779-7330eba193ee.png">

**Comment by bvaughn** [comment]
This is interesting. The extension seems to have a shorter toolbar height than I would expect, which is clipping the current index. Here's what the test harness/shell looks like:
<img width="437" alt="Screen Shot 2020-03-11 at 6 11 50 PM" src="https://user-images.githubusercontent.com/29597/76477848-ce5a0500-63c3-11ea-9c08-fd9baaa2efa2.png">

**Comment by bvaughn** [comment]
Looks like something is going wrong with the relative height of the list items in the extension. Works fine in Chrome but it's overflowing in the extension. 😕

**Comment by bvaughn** [comment]
Ah, it looks like the `box-sizing` style isn't cascading correctly in the extension.

**Comment by bvaughn** [comment]
I think this probably regressed with 9cc094a.

**Comment by bvaughn** [comment]
Yay! Fixed.

![Uploading Screen Shot 2020-03-11 at 6.35.52 PM.png…]()
