### ISSUE TITLE
Bug: react-test-renderer createNodeMock does not seem to work with useRef

### ISSUE THREAD

**Issue by mrdanimal** [facebook/react#18281]
React version: 16.9.0
react-test-renderer version: 16.12.0

## Steps To Reproduce

1. Create a functional component that uses `useRef`
2. In a test, use `createNodeMock` to mock the ref when you call `renderer.create`
3. Attempt to access `.current` on your ref

```
const MyComponent = (): JSX.Element => {
  const myRef = React.useRef<HTMLDivElement>(null);
  console.log('myRef', myRef);

  return <div></div>;
};

export default InfiniteList;

const component = renderer.create(<MyComponent />, {
  createNodeMock() {
    console.log('createNodeMock called');

    return {
      getBoundingClientRect(): { y: number } {
        return {
          y: -1000,
        };
      },
    };
  },
});
```
The log output is:
```
  console.log src/components/MyComponent/MyComponent.tsx:62
    myRef { current: null }

  console.log src/components/MyComponent/MyComponent.tsx:110
    createNodeMock called
```

It's worth noting that this _did_ work within a class component and `createRef`, but stopped when I converted the component to a functional component that uses `useRef`.

Link to code example:
I was not able to get tests to run on CodeSandbox.

## The current behavior
The `.current` property on the ref is `null`

## The expected behavior
The `.current` property on the ref should be the the mock provided by `createNodeMock`.

**Comment by eps1lon** [comment]
You need to attach the ref to a component: 
```diff
-return <div></div>
+return <div ref={myRef}></div>
```

But even then you will not see a different log since the `current` will only be assigned on the next render.

`createNodeMock` is only used when refs are actually attach not just when calling `createRef` or `useRef`.

**Comment by mrdanimal** [comment]
Thanks for the quick response. I think that was actually more of a mistake in my paring down my original component and test into something that's more comprehensible here. I added the ref to the DOM and now I get this in the log:
```
  console.log src/components/InfiniteList/InfiniteList.tsx:29
    myRef { current: null }

  console.log src/components/InfiniteList/InfiniteList.tsx:36
    createNodeMock called

  console.log src/components/InfiniteList/InfiniteList.tsx:29
    myRef { current: null }```

`current` is still null

**Comment by sophiebits** [comment]
It's hard to tell based on what you've provided, but in general it isn't recommended to read a ref during a render function. Any code that manipulates or measures DOM nodes should be in useEffect, useLayoutEffect, or similar.

I'm guessing that will solve your problem. If not, happy to reopen.
