### ISSUE TITLE
Bug: IE11 throws error Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by Pinka** [facebook/react#18290]
When working in development mode in IE11 error is thrown in file 
react-dom.development.js line 185. 

Error: "Assignment to read-only properties is not allowed in strict mode"
window.event is readOnly variable and IE11 is strict about it.

![image](https://user-images.githubusercontent.com/5305497/76511927-8509c400-645c-11ea-89c4-9f38a6e0a778.png)

React version: 16.13.0

In production build there is no error as this code block is not included.

**Comment by gaearon** [comment]
Interesting that we didn't see reports about this before.

**Comment by aweary** [comment]
@Pinka can you share some more details on what you were doing that triggered this error? If you could share a code sample that reproduces the problem in IE11 that would be very helpful.

**Comment by ahakem** [comment]
I've same issue, when I click on a button that change the state

**Comment by josh23french** [comment]
bump; still affected

**Comment by Mrc527** [comment]
I can confirm, I see the same on 16.13.1.

Any suggestion?

**Comment by gaearon** [comment]
We need a full reproducing example.

**Comment by artem-kzm** [comment]
bumb

**Comment by gaearon** [comment]
There hasn't been a reproducing example. The "bump" comments are not helpful when this is what was requested.
