### ISSUE TITLE
Parsing error for HTML entity in nested JSX.

### ISSUE THREAD

**Issue by lrowe** [facebook/react#183]
The html entity in the following causes a `SyntaxError: Unexpected token ;`  in both current master and React 0.3.

```
/** @jsx React.DOM */
var mylist = ['a', 'b', 'c'];
// Fails with entity below
React.renderComponent(
    <p>
        {mylist.map(function (id) {
            return (<span>{id} &nbsp;</span>);
        })}
    </p>, document.body);
```

JSFiddle: http://jsfiddle.net/VLmQt/

**Comment by danvoyce** [comment]
Was this ever fixed? I'm still having an issue with &nbsp; in v0.14.5

**Comment by jimfb** [comment]
@danvoyce This issue was closed over almost two years ago.  It is also related to fbtransform, which has been deprecated for a long time now.  If you're running into an issue that you believe is a bug in React, please open a new issue with a simple jsfiddle that demonstrates your issue.
