### ISSUE TITLE
Avoid unnecessary object allocation in ClassSet

### ISSUE THREAD

**Issue by syranide** [facebook/react#1830]
https://github.com/facebook/react/blob/8a47813baabcb200f5e0a496dd959cb0ef3adcf3/src/vendor/stubs/cx.js#L36

If we get rid of `Object.keys` we save one allocation for a potentially commonly used function (except for you guys running your internal transform). Yes no?

**Comment by chenglou** [comment]
Closing this since we're deprecating `classSet` (#2910), I'm closing this. The new alloc-free version lives at https://github.com/petehunt/react-classset
