### ISSUE TITLE
Bug: set same state trigger when click

### ISSUE THREAD

**Issue by shaodahong** [facebook/react#18311]
React version:
16.12.0

## Steps To Reproduce

1. Open chrome console panel
2. Click document
3. View logs

Link to code example:

https://codesandbox.io/s/always-two-renders-861qp

![Kapture 2020-03-14 at 22 59 11](https://user-images.githubusercontent.com/14831261/76684509-79c6bc00-6647-11ea-9db8-e49375d2ec11.gif)

## The current behavior

whatever click more times, always log two times

In my see, if state not change, should not render, I don't know reason if it's related to this https://github.com/facebook/react/issues/16387#issuecomment-521623662

## The expected behavior

 always log one time

**Comment by shaodahong** [comment]
https://reactjs.org/docs/hooks-reference.html#functional-updates

> If your update function returns the exact same value as the current state, the subsequent rerender will be skipped completely.

This is the official description

**Comment by eps1lon** [comment]
CodeSandbox uses StrictMode by default in which renders a called twice. You can remove it from the index.js in your codesandbox

```diff
ReactDOM.render(
-  <React.StrictMode>
    <App />
-  </React.StrictMode>,
  rootElement
);
```

**Comment by shaodahong** [comment]
> CodeSandbox uses StrictMode by default in which renders a called twice. You can remove it from the index.js in your codesandbox
> 
> ```diff
> ReactDOM.render(
> -  <React.StrictMode>
>     <App />
> -  </React.StrictMode>,
>   rootElement
> );
> ```


Not for this reason

**Comment by shaodahong** [comment]
1) The first click, Fiber `expirationTime` is `noWork`(default), but hook queue state change, so exec `scheduleWork` and update Fiber `expirationTime`(`Sync`)

2) The second click Fiber `expirationTime` is Sync, so exec `scheduleWork` and reset Fiber `expirationTime`(`noWork`)

3) The third click Fiber  is `noWork` and hook queue state equal, return

**Comment by gaearon** [comment]
See my answer here.
https://stackoverflow.com/a/60919619/458193
