### ISSUE TITLE
ReactJS [issue on production] - TypeError: (void 0) is not a functionBug

### ISSUE THREAD

**Issue by mahendrakulkarni177** [facebook/react#18310]
![image](https://user-images.githubusercontent.com/16331616/76676066-d8f3e480-65e5-11ea-88aa-270dbd274096.png)

I'm facing the above error on production build, not even getting the issue reference... your help will really be appreciated, Thanks in advance.

Note - on local, it works fine - development mode, but the same code won't work on a production.
React js version is - 16.12.0, and webpack version - 4.41.6

Also tried to downgrade the versions still getting the same error

**Comment by gaearon** [comment]
We need to see a reproducing example. This is too little information, and there are no signs the error is actually coming from React.

**Comment by mahendrakulkarni177** [comment]
Thanks for your response, @gaearon issue was because of ```office-ui-fabric-react``` version got updated and I was using an older version, the issue got resolve :) 
Also updated React and React-Dom next version.
