### ISSUE TITLE
 React.lazy will cause mount life-cycle for the same path in React Router

### ISSUE THREAD

**Issue by CarmeloXue** [facebook/react#18318]
I'm using React.lazy to split my code. I just add a `React.lazy(()=>import('path/to/component')) `and `Suspense`.

In my component I have a button with a click function to do `history.replace('/my/route?params=CHANGABLE').`

I have several clickable tab header to trigger this function with a different CHANGABLE params and render different tab content for corresponding parameter.

Without React.lazy, the click will not trigger re-mount of the component. But with react.lazy, each time I click the tab, the component will go trough the mount life-cycle.

Is there anything I've done wrong? Anyone can help me?

React version:16.8.3

## Steps To Reproduce

1.
2.

Link to code example:

## The current behavior

Component will go though mount life-cycle

## The expected behavior

Component will go though update life-cycle

**Comment by gaearon** [comment]
We can't guess without seeing full code. The issue template asked you to fill in an example, but you didn't do this. We'll have to close this, but please feel free to file a new issue after you create a runnable code example.
