### ISSUE TITLE
Simple line comments in JSX

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#1831]
Would it be possible to add some syntax for line comments in JSX?

Something along these lines:

``` jsx
return (
  <ul>
    <li>One</li>
//    <li>Two</li>
  </ul>
);
```

At the moment `{/* */}` is a little clunky

**Comment by jamiehutber** [comment]
+1

**Comment by likethemammal** [comment]
Jest throws an `Unexpected token` error with JSX comments atm. Something to consider
