### ISSUE TITLE
Bug: react-refresh silently fails if version does not match react version

### ISSUE THREAD

**Issue by Lokeh** [facebook/react#18312]
Currently, each `react-refresh` package version requires a specific version of the `react` package (the exact correspondence I'm not sure about). Installing the latest version of `react` (16.3) and an older version of `react-refresh` (e.g. 0.6) causes react-refresh to silently fail; the app will not hot reload, no errors or warnings are shown.

This often occurs when working on a project that uses react-refresh, upgrading `react` and forgetting to update `react-refresh`.

React version: 16.x

## Steps To Reproduce

1. Install `react@16.13` and `react-refresh@0.6`
2. Try to use react-refresh's hot reloading feature.

## The current behavior

Hot reloading silently fails, does nothing.

## The expected behavior

A warning either at install time or runtime would alert the user that mismatched versions of react-refresh and react are installed.

**Comment by gaearon** [comment]
It was added with 16.10 (or maybe 16.9). I don’t anticipate this being a problem going forward.

**Comment by Lokeh** [comment]
I'll verify this with the latest React version soon and re-open if I can reproduce it.
