### ISSUE TITLE
Bug: React-test-renderer error when updating state in act

### ISSUE THREAD

**Issue by ahummel25** [facebook/react#18314]
React version: 16.13.0
react-test-renderer version: 16.13.0

## Steps To Reproduce

Link to code example: [Here](https://codesandbox.io/s/dazzling-kare-nxtfs) is a reproducible link.

## The current behavior
It's worth noting this example is using material-ui as a dependency. Regardless, I believe the test should still pass.

 When updating state in my component, a drawer component opens and closes depending on a boolean value. Code works fine in the browser. When running the above test, it fails with a trace error that includes the below.

```
TypeError: parentInstance.children.indexOf is not a function
    at appendChild (https://psnrk.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:720:39)
```

Here I am drilling down to a child anchor tag to access its `onClick` function. As you'll see in the sandbox example, I am passing it a `mockEvent` because the handler first calls `event.preventDefault`. 

This does not cause any issues. The error occurs when the `setOpen` hook function gets called. Just wanted to point that out.
```
act(() => {
    tree.root.children[0].props.children.props.children.props.onClick(mockEvent);
});
```

Same error happens when I try to initiate the `onClose` handler of the `Drawer` component:

```
act(() => {
    tree.root.children[1].props.onClose(mockEvent);
});
```

## The expected behavior

Test should pass. The state should be properly updated in the `onClick` handler or the `onClose` handler and I should be able to make further assertions after that.

If this is not the best way to execute a click event with `react-test-renderer` please let me know. I was looking for examples and it seemed like this was the way to do it.

**Comment by ahummel25** [comment]
👀

**Comment by rachelnabors** [comment]
Hello there! The issue seems to be that Material is using portals, which is complicated in Test Renderer. We're recommending testing without Test Renderer, which you can learn more about here: https://reactjs.org/docs/testing-recipes.html
