### ISSUE TITLE
Bug: Should function isControlled use !== ?

### ISSUE THREAD

**Issue by xsteadybcgo** [facebook/react#18320]
React version: 16.20.0

## Steps To Reproduce

1. inital state is `undefined` , the `useAsyncCustomHooks` will call an async function eg: `navigator.geolocation.getCurrentPosition`
2. the state will changed later

Link to code example:
```javascript
  function FC() {
    const [state] = useAsyncCustomHooks()
    return <input  type="text" value={state}/>
  }
```

## The current behavior
dev tool throws Warning: A component is changing a controlled input of type hidden to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

## The expected behavior
Not throw that warning, the related source code is:
https://github.com/facebook/react/blob/c601f7a64640290af85c9f0e33c78480656b46bc/packages/react-dom/src/client/ReactDOMFiberInput.js#L37-L40

why not `!==` but `!=`  :blush:

**Comment by overhead525** [comment]
So 2 questions...

1. What is the return value of `useAsyncCustomHooks()`?

2. If `useAsyncCustomHooks` is called, it will return a value eventually. But that value will be final right? If that's the case, then the `<input />` is controlled until the asynchronous `useAsyncCustomHooks` function is called. After the result has been returned, there's nothing to change the `currentPosition`, so it will then be uncontrolled.

This is interesting, and I want to figure it out. So this will at least get the conversation going.

**Comment by xsteadybcgo** [comment]
> So 2 questions...
> 
> 1. What is the return value of `useAsyncCustomHooks()`?
> 2. If `useAsyncCustomHooks` is called, it will return a value eventually. But that value will be final right? If that's the case, then the `<input />` is controlled until the asynchronous `useAsyncCustomHooks` function is called. After the result has been returned, there's nothing to change the `currentPosition`, so it will then be uncontrolled.
> 
> This is interesting, and I want to figure it out. So this will at least get the conversation going.

- In my case, the return value of useAsyncCustomHooks() is a string  such as `"new york city..."`

- I want to give one more example to compare the situation! This confused me about what is the controlled component , i thought the component having `ref` property is a controlled component but now I'm getting stuck !!!

In the code snippets above, the initial `state` is `undefined`, so  function `isControlled` will return  `false`( __`undefined != null` will return `false`__ )
According to *react source code* below, the line 143 will be false & line 162 - 164 is true ,  it will throw the warning!

https://github.com/facebook/react/blob/c601f7a64640290af85c9f0e33c78480656b46bc/packages/react-dom/src/client/ReactDOMFiberInput.js#L142-L174

The example below is similar to the above one, but i won't throw any warining!!
```javascript
function FC() {
    const [state] = useAsyncCustomHooks()
    return <input  type="text" value={state || ""}/>
  }
```
the initial `state` is `""`, so  function `isControlled` will return  `true`( __`"" != null` will return `true`__ )

🤔️🤔️🤔️

**Comment by overhead525** [comment]
I see the issue clearly now. If we used `!==` instead of `!=`, undefined would work just like `""`.

**Comment by overhead525** [comment]
I've always viewed controlled components as some type of input with "`write` access to the state".

I'm not sure if you've got a workaround yet, but here's what I would do:

1. Set the initial state to an empty string, since you're expecting a string eventually:

```
function FC() {
    const [position, setPosition] = useState("");
    // ... 
}
```

2. Wait for the component to mount, then immediately execute your asynchronous function:

```
function FC() {
    const [position, setPosition] = useState("");

    useEffect(() => {
        async () => {
            const response = await useAsyncCustomHook();
            setPosition(response);
        }
    }, [position])
    
    return <input type="text" value={state} />
}
```

I'm not a big fan of the whole double nesting syntax, but I ran into a similar issue with the `useEffect` hook a while back, and this was the only solution a senior dev could give me (he wasn't a fan either haha).

**Comment by sophiebits** [comment]
Many applications rely on a value of `undefined` to mean an uncontrolled component. If you want to treat `undefined` to mean a controlled empty box, you can always write something like:

```js
<input type="text" value={state === undefined ? '' : state} />
```

Hope that helps.

**Comment by xsteadybcgo** [comment]
Thanks for your reminder, I get it
