### ISSUE TITLE
Bug: Hooks acts weirdly with class - state gets reinitialized every time

### ISSUE THREAD

**Issue by RocKhalil** [facebook/react#18321]
React version: 16.12.0

## Steps To Reproduce

I have a helper `class` that handles my `socket.io` connection and adds the list of messages to my state.

Here's the class:

```
import socketIOClient from 'socket.io-client'

class SocketHelper {
  constructor(props) {
    this.broadcastId = props.broadcastId
    this.chatMessageReceived = props.chatMessageReceived

    this.socket = socketIOClient(props.socketURL)
  }

  start() {
    this.socket.emit('join', this.broadcastId)

    this.socket.on('chat-message', this.chatMessageReceived)
  }

  sendMessage(message) {
    this.socket.emit('message', message)
  }
}

export default SocketHelper
```

Now, I want to use this class in my `react` class or function;

### in function

```
const [messages, setMessages] = useState([])

const socketHelper = new SocketHelper({
  broadcastId: 'whatever',
  chatMessageReceived: (data) => {
    setMessages([...messages, data])
  }
})

socketHelper.start()
```

Every time I receive a `message` from the socket, my `chatMessageReceived` will be triggered by the `messages` will always be an empty array and the new message will be appended to it.

I also tried initializing it once via `useEffect( () => { ... }, [] )` and also got the same result

### in class
```
constructor(props){
  super(props)

  this.state = {
    messages: []
  }

  this.socketHelper = new SocketHelper({
    broadcastId: 'whatever',
    chatMessageReceived: (data) => {
      this.setState({ messages: [...this.state.messages, data] })
    }
  })
}
```

This will work and my new message will get appended to the old ones

# Other comments

I tried to simplify the issue as much as possible.

I hope this helps.

**Comment by jquense** [comment]
do this:

```js
const socketHelper = useMemo(() => new SocketHelper({
  broadcastId: 'whatever',
  chatMessageReceived: (data) => {
    // --------------👇
    setMessages(prevMessages => [...prevMessages, data])
  }
}, [])
```

Using the function version of `setMessages` gives you access to the old value without needing to pass it into the hook via a closure

**Comment by gaearon** [comment]
https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often
