### ISSUE TITLE
Bug: Updates in the primary tree only unsuspend once

### ISSUE THREAD

**Issue by gaearon** [facebook/react#18353]
https://codesandbox.io/s/upbeat-frost-3tt25

1. Press Suspend, see "Loading..."
2. Wait five seconds, you'll see "Happy birthday" at some point 
3. You won't see it again no matter how long you wait

Expected: you'll see it every five seconds.

**Comment by gaearon** [comment]
Here's a variation that doesn't seem to "wake up" at all, not even the first time: https://codesandbox.io/s/sleepy-moore-4e3o9.

**Comment by acdlite** [comment]
Confirmed that this is fixed by https://github.com/facebook/react/pull/18384
