### ISSUE TITLE
May be bug: onChange events don't fire in controlled forms in portals rendered in external window

### ISSUE THREAD

**Issue by ZYinMD** [facebook/react#18368]
React version: 16.13.1

I may be using Portal in a way that's not intended, which is why I had this bug, but at least it's not mentioned in the doc.

## Steps To Reproduce

Demo: [CodeSandbox](https://codesandbox.io/s/kind-morning-t3q9c)

Inspired by [this blogpost](https://medium.com/hackernoon/using-a-react-16-portal-to-do-something-cool-2a2d627b0202), I open a new browser window with `window.open()`, then render a portal in it, so the two windows belong to the same react app, and share states. It works like magic, but I find that the `onChange` events of controlled forms (like `input` or `select`) don't fire.

## The current behavior
As shown in the sandbox, my controlled `input` and `select` components work well in normal portals, but same components don't work in portals in external window. 

## The expected behavior
I hope they just work the same.

If it can't work, I'll need to use uncontrolled forms.

**Comment by gaearon** [comment]
Can you try this in earlier versions of React to check if this ever worked?

**Comment by ZYinMD** [comment]
I tested several versions, as early as v16.2.0, seems it never worked.

[Sandbox on React 16.2.0](https://codesandbox.io/s/portal-on-react-1620-kechz)

**Comment by ZYinMD** [comment]
I have a guess: in the synthetic event, the keyword `document` is used somewhere, and it always refers to the original document, not the externalWindow.document

**Comment by gaearon** [comment]
Seems like this doesn't repro in 18.

https://codesandbox.io/s/great-lake-5u5tqv?file=/src/index.js
