### ISSUE TITLE
PropTypes: define children component type

### ISSUE THREAD

**Issue by SanderSpies** [facebook/react#1836]
I was looking for something like:

```
propTypes: {
  children: React.PropTypes.instanceOf(OtherComponent)
}
```

However this doesn't work of course and couldn't find another way of doing this.

Would be nice if this was supported.

**Comment by stubbornella** [comment]
It would be really cool to be able to verify that the right React component was passed in as a property. The docs are a little confusing, because it looks like you should be validating that the right React Message component is getting passed in:

```js
 // An object that could be one of many types
    optionalUnion: React.PropTypes.oneOfType([
      React.PropTypes.string,
      React.PropTypes.number,
      React.PropTypes.instanceOf(Message)
    ]),
```
http://facebook.github.io/react/docs/reusable-components.html

**Comment by sebmarkbage** [comment]
Yea, the current work around is something like: `shape({ type: oneOf([MyComponent]) })`

I think we need a broader solution than testing for specific types. Usually you want it to correspond to some specific interface but the actual implementation is flexible, or have a certain set of props defined on it.

**Comment by danez** [comment]
Is there any news on that?

**Comment by jimfb** [comment]
> propTypes are mostly in a sort of maintenance mode and we're not really planning to add more to them right now.

Proptypes are being phased out in favor of tools like Flow.

**Comment by sebmarkbage** [comment]
> That's simple. Someone send a pull-request?

At least part of this is something we should "maintain".

**Comment by wizardzloy** [comment]
Looks like this could be closed, the explanation is here: https://github.com/facebook/react/pull/7119

**Comment by wizardzloy** [comment]
In case somebody needs this functionality, I published a module for that https://www.npmjs.com/package/react-element-proptypes

**Comment by congwenma** [comment]
Added a pr for this feature
https://github.com/facebook/prop-types/pull/146
