### ISSUE TITLE
Bug:  Fast refresh doesn't work when react is a dev. dependency

### ISSUE THREAD

**Issue by dicearr** [facebook/react#18365]
I might be missing something obvious but I always thought that I could install `react` in `dependencies` or `devDependencies`.

React version: 16.13.1

## Steps To Reproduce

1. Clone a repository in which fast refresh works nicely, for instance: `git clone https://github.com/astegmaier/parcel2-react-refresh`.
2. Run `npm install && npm start`.
3. Access the served application in your favorite browser.
4. Make changes to any file, for instance `sed -i 's/child/wooohooo/g' src/ChildComponent.js`.
5. You'll see that the application reloaded in the browser.
6. Now reinstall `react` as a development dependency `rm -r node_modules && npm uninstall react && npm install --save-dev react`.
7. Restart the web application.
8. Make changes again in the component `sed -i 's/wooohooo/all good/g' src/ChildComponent.js`, you'll notice that nothing changed in your browser.

## The current behavior

The component `ChildComponent` is not reloaded when I make changes.

## The expected behavior

The component `ChildComponent` is reloaded when I make changes.

**Comment by gaearon** [comment]
Please file this with Parcel. The underlying mechanism in React has no way to know how it’s declared in package.json so it couldn’t be the cause. npm also doesn’t care. That leaves us with Parcel heuristics as the place where it breaks down.

**Comment by dicearr** [comment]
I will do so. I opened it here in the first place because I see the updates coming through the websocket, but you're right.
