### ISSUE TITLE
Bug: Best practice - React.createElement children argument to be always array.

### ISSUE THREAD

**Issue by imvetri** [facebook/react#18361]
## Maintain consistency

When a parent component contains children, sometimes it is passed as an object and sometimes it is passed as an array.

Example:
`<Parent>
    <Child></Child>
</Parent>`

In the above example, typeof Parent.children will be object whereas

`<Parent>
    <Child></Child>
    <Child></Child>
</Parent>`

typeof Parent.children will be Array.

## The current behavior
Single child is treated as object and List of child is treated as array.

## The expected behavior
Single child and list to be treated as an array of children.

## Example
https://codesandbox.io/s/mystifying-antonelli-j4qe3

**Comment by threepointone** [comment]
Why does this matter? It’s not meant to be manipulated/introspected by an app developer anyway, and if they do need to, there are React.Children helpers to do so. 

This isn’t a bug.

**Comment by imvetri** [comment]
It's not a bug from app developer's view but helps a maintainer from keeping track of the types and get rid of conditional check in other pieces of code.

**Comment by threepointone** [comment]
It’s an internal implementation detail that shouldn’t be relevant to anyone else. Among other things, it prevents extra allocations when not needed. Closing this, thanks for the concern!

**Comment by imvetri** [comment]
Documentation is misleading. Here children is an array type https://reactjs.org/docs/react-api.html#createelement
