### ISSUE TITLE
Bug: Custom Hooks cannot be Shared in Webpack Bundles

### ISSUE THREAD

**Issue by pmwmedia** [facebook/react#18369]
A custom hook in a webpack bundle cannot be reused in another Webpack bundle, because React throws an error on runtime:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

1. I use the same version of React and React DOM (see [package.json](https://github.com/pmwmedia/react-custom-hook-issue/blob/master/parent-project/package.json#L8-L9))
2. I don't break the Rules of Hooks (only called from React function component and custom hook)
3. I use external declaration to ensure having only one copy of React (see [webpack.config.js](https://github.com/pmwmedia/react-custom-hook-issue/blob/master/child-project/webpack.config.js#L15))

React version: 16.13.1

## Steps To Reproduce

1. Execute `run.bat` or `run.sh` from example GitHub repo
2. Open console of your browser to see the thrown error

Link to code example: https://github.com/pmwmedia/react-custom-hook-issue

## The current behavior

React throws an error when rendering a component that contains a custom hooks from another Webpack bundle.

## The expected behavior

React accepts custom hooks from other Webpack bundles.

**Comment by gaearon** [comment]
React has no knowledge of webpack. Therefore, it can’t possibly refuse sharing Hooks via webpack specifically. If you see this error it *does* mean you have two copies of React (or an equivalent problem). Possibly due to bad webpack configuration. Have you examined the output of your bundles?

**Comment by pmwmedia** [comment]
You are right, even if the bundle of the child-project doesn't contain React due to the external declaration, Webpack includes React twice in the parent-project bundle by default.
