### ISSUE TITLE
Bug: Returning div or span from map on Indexed Collections like Int32Array and Float32Array returns 0s and NaNs

### ISSUE THREAD

**Issue by saravanabalagi** [facebook/react#18373]
React version: 16.13.1

## Steps To Reproduce

1. Create a simple react app
2. Add a Int32Array with some values. (Here we'll take [12, 4, 15, 6])
3. Use map on the variable and return a div or span with value inside

```js
let intArray = new Int32Array([12, 4, 15, 6]);
```
```jsx
<div>
  <div>IntArray {intArray.join(", ")} Below</div>
    {
        intArray.map((el, index) => {
        return(
            <div>
            {index}: {el}
          </div>
        )
      })
    }
  </div>
</div>
```

Link to code example: https://jsfiddle.net/3xfzstb5/

## The current behavior
0000

## The expected behavior
12
4
15
6

## Additional Information

Happens when return for map wrapped in div or span

I find similar behaviour for 
- Int8Array
- Uint8Array
- Uint8ClampedArray
- Int16Array
- Uint16Array
- Int32Array
- Uint32Array
- Float32Array
- Float64Array
- BigInt64Array
- BigUint64Array

with `NaN` for floats, `0` for ints

**Comment by bvaughn** [comment]
This is not a React bug.
```js
new Int32Array([1, 2, 3]).map(i => i); // [1,2,3]
new Int32Array([1, 2, 3]).map(i => {i}); // [0,0,0]
```

I believe the reason is that `Int32Array.prototype.map()` is creating a new `Int32Array` (or whatever type the current array is) to store the resulting mapped values. That array can't contain non-numeric values.
