### ISSUE TITLE
Bug: Combination of standard hooks causes "Cannot read property 'length' of undefined" in areHookInputsEqual

### ISSUE THREAD

**Issue by willyrk1** [facebook/react#18372]
Found a combination of fairly trivial hooks that causes "Cannot read property 'length' of undefined" in areHookInputsEqual" error.

React version: 16.12

## Steps To Reproduce

1. Open sandbox at https://codesandbox.io/s/hooks-combo-npe-6tyck
2. Click TRY ME button.
3. Yellow screen

Link to code example:

https://codesandbox.io/s/hooks-combo-npe-6tyck

## The current behavior
Yellow-screen crash

## The expected behavior
The StateModal pointing to MyComponent is rendered at the obvious spot.

**Comment by bvaughn** [comment]
This is a misunderstanding.

The `useState` hook lets you update state in two ways:
* Passing a value directly (e.g. `setState(123)`)
* Passing an ["updater function"](https://reactjs.org/docs/hooks-reference.html#functional-updates) that receives the previous state and returns a new state.

The Code Sandbox you linked passes `MyComponent` (a function) so it gets run as though it were "updater function". Hooks (in this case `useEffect`) can't be used outside of React components, and so will cause an error.

If you really want to store a component (or any function) in state, for some reason, either use `useCallback` or a wrapper function (e.g. `setState(() => someOtherFunction)`).

**Comment by bravodavid56** [comment]
In case this helps anyone else, my issue was using the hook in a conditional statement. 

Somehow removing the hook from the conditional fixed my issue.
