### ISSUE TITLE
RFC: Introduce more DOM property definitions

### ISSUE THREAD

**Issue by syranide** [facebook/react#1838]
`tabIndex` is an integer, positive or negative, add `HAS_NUMERIC_VALUE`?

`rowSpan` and `colSpan` are integers, but only non-negative, which I assume would necessitate `HAS_NONNEGATIVE_VALUE`?

`spellCheck` is boolean with a third indeterminate state, so `HAS_TRISTATE_VALUE` would need to be added (`undefined` and `null` should both map to indeterminate). It expects `"true"` or `"false"`.

`autoComplete` is a regular boolean attribute except that it defaults to `on`, so you have to explicitly set it to `off` to disable it. Expects `off` (or `on`, but that is default and is redundant). Add something like `IS_DEFAULT_ENABLED`?

Thoughts? Have I missed something? Also yes, lots of new properties sadly, but worth the discussion at least.

**Comment by gaearon** [comment]
We’ve dropped support IE8 and I imagine IE9 isn’t going to last that much longer.
So special checks for them aren’t as relevant these days.

Closing as stale.
