### ISSUE TITLE
Bug: NotFoundError: Node was not found

### ISSUE THREAD

**Issue by krishnaTORQUE** [facebook/react#18389]
React version: 16.13.1

After update react getting crash on production everytime. in local development its crashing but not all time.

Error getting in development :
NotFoundError: Node was not found

Error getting in production:
Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by threepointone** [comment]
It's not clear without a small reproduction on either codesandbox, or as a git repo, what the issue actually is. Please share a reproducible example. 

Please also test by disabling browser extensions, as React doesn't behave well with extensions that change the dom invasively.

**Comment by gaearon** [comment]
Too little information

**Comment by krishnaTORQUE** [comment]
I fixed this issue by changing from Fragment tag to div tag

**Comment by gaearon** [comment]
If you have a repro for the bug we can take a look.

**Comment by maniac0s** [comment]
I have a similar problem. Don't know if this is related, I created a stackoverflow about this

https://stackoverflow.com/questions/62885111/notfounderror-node-was-not-found-on-removing-react-component
