### ISSUE TITLE
Having errors with usereducer and usecallback functions 

### ISSUE THREAD

**Issue by Ncjustus123** [facebook/react#18399]
```jsx
const formReducer=(state, action) => {
    switch (action.type) {
        case 'INPUT_CHANGE':
            let formIsValid = true;
            for (const inputId in state.inputs) {
                if (inputId === action.inputId) {
                    formIsValid = formIsValid && action.isValid;
                } else {
                    formIsValid = formIsValid && state.inputs[inputId].isValid;
                }
            }
          return {
              ...state,
              inputs:{
                  ...state.inputs,
                  [action.inputId]:{value: action.value, isValid: action.isValid}
              },
              isValid: formIsValid
          };
        default:
            return state;
    }
};

const newplace =() => {
   const[formState,dispatch] =  useReducer(formReducer, {
        inputs:{
            title:{
                value:'',
                isValid: false
            },
            description:{
                value:'',
                isValid: false
            }
        },
        isValid: false
    });
    const InputHandler = useCallback((id, value, isValid) => {
        dispatch({type: 'INPUT_CHANGE', value: value, isValid: isValid, inputId: id });
         
    },[]);
```

**Comment by Ncjustus123** [comment]
constantly returns the error below 
Line 32:33:  React Hook "useReducer" is called in function "newplace" which is neither a React function component or a custom React Hook function   react-hooks/rules-of-hooks
which is neither a React function component or a custom React Hook function   react-hooks/rules-of-hooks
  Line 45:26:  React Hook "useCallback" is called in function "newplace" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

**Comment by devanfarrell** [comment]
Capitalize `NewPlace`. It's a bit of a gotcha that I wish had a better error message. Functional component names need to start with an uppercase letter.

**Comment by threepointone** [comment]
@devanfarrell is right, the linter recognises components based on its name, which should be capitalised. Closing this issue, thanks!

**Comment by gaearon** [comment]
>Functional component names need to start with an uppercase letter.

That's true for classes too, btw. All components must start with a capital letter. You'll discover this pretty quickly anyway because JSX won't "see" them otherwise.
