### ISSUE TITLE
Bug: unnecessary scrollbars in React Developer Tools.

### ISSUE THREAD

**Issue by infinnie** [facebook/react#18394]
React version:

## Steps To Reproduce

1. Install React Developer Tools v4.5.0
2. Open the Components panel in developer tools.

Link to code example:

## The current behavior
Scrollbars are rendered even if there is or should be no scrolling.

Screenshot showing React Developer Tools v4.5.0 debugging a fork of v3.6.x:
![image](https://user-images.githubusercontent.com/8168391/77620393-3a686b80-6f75-11ea-9521-22402d1cce6a.png)

## The expected behavior
Elements are correctly laid out and sized so that there should not be unnecessary scrolling in those places.

**Comment by jmadelaine** [comment]
Hi Infinnie, version 6.0.0 was released last week, could you try updating and see if this fixes the issue you're seeing?

With the new version I can't reproduce the issue:

![Screen Shot 2020-04-02 at 09 25 49](https://user-images.githubusercontent.com/24227392/78183201-fbca3800-74c3-11ea-9855-a9857559082d.png)

**Comment by bvaughn** [comment]
This seems like an edge case bug maybe related to font metrics or something, not sure. It's not something I've ever seen. I don't think the recent 4.6.0 release had anything in it that should have affected this FWIW.
