### ISSUE TITLE
Updates in componentDidMount not batched for initial render

### ISSUE THREAD

**Issue by syranide** [facebook/react#1839]
@spicyj Knows what's up, this is just a reminder.

Crappy code to reproduce: https://gist.github.com/syranide/16702e83db2b3a19f7ec

Performance-wise, this should generally be a minor issue as any additional updates will be properly batched (as is demonstrated in the gist above).

**Comment by syranide** [comment]
It seems like this should be solved in 0.13

**Comment by spicyj** [comment]
Should be.
