### ISSUE TITLE
Bug: no-unused-vars warning thrown for createRef import despite use

### ISSUE THREAD

**Issue by pottspotts** [facebook/react#18400]
![image](https://user-images.githubusercontent.com/2292554/77690271-0a1ece00-6f71-11ea-8d9c-0be97391a7ec.png)

![image](https://user-images.githubusercontent.com/2292554/77690352-291d6000-6f71-11ea-866b-a87db8275aec.png)

React version: 16.13.0

## Steps To Reproduce

1. `import React, {Component, createRef} from 'react';`
2.  `constructor() {this.ref = createRef()}`

Link to code example: https://codesandbox.io/s/intelligent-euler-qjd2p

## The current behavior
A warning is shown erroneously.

## The expected behavior
A warning should not be shown.

**Comment by threepointone** [comment]
Are you sure you’re looking at the right file? Regardless, this doesn’t have anything to do with react, and should probably be filed at eslint/issues

**Comment by gaearon** [comment]
The CodeSandbox link doesn't point to an example of this.

**Comment by gaearon** [comment]
If you get this with Create React App, please file an issue here: https://github.com/facebook/create-react-app

As @threepointone says, this isn't coming from React.
