### ISSUE TITLE
BrowserRouter and HashRouter works for three Routes only 

### ISSUE THREAD

**Issue by ashutosh1919** [facebook/react#18414]
## Steps To Reproduce  
You can visit [this github project](https://github.com/ashutosh1919/masterPortfolio). On the top of it, you can also see link of the currently deployed version.

Now, in the NavBar, you can see 7 options.
Home, Education, Experience, Projects, Opensource, Blogs, Contact Me.  
Among which I have added components of Home, Education, Experience and Opensource.  
So, Projects, Blogs and Contact Me will obviously not work because the code corresponding to them has not been added.  

But now, the problem is I am routing the components using BrowserRouter (and I have also tried with HashRouter). The Router is working fine on local host using `npm start`. But on `serve -s build`, The Router is able to Route on Home, Education and Opensource. But it is not able to Route to Experience.  
I have tried different ways of doing it. But I am not able to solve it.

The Routes are defined in is in `src/container/Main.js` and NavBar is defined in `src/components/header/Header.js`.

## The current behavior  
Routing to only 3 nav items.

## The expected behavior
Should Route to 4 items.

**Comment by gaearon** [comment]
React Router has no relation to React. It is a third party project. Please check out Community resources on our website for good places to ask for help. We try to keep this tracker focused on bugs in React itself.
