### ISSUE TITLE
Bug: dragenter on text node contains parent node in event.target in Firefox

### ISSUE THREAD

**Issue by avandecreme** [facebook/react#18416]
React version: 16.13.1

## Steps To Reproduce

Drag a file over text in Firefox
See this fiddle as example: https://jsfiddle.net/wqcsg2un/2/
![firefox-react-drag](https://user-images.githubusercontent.com/465389/77827796-04172180-7118-11ea-8400-c667b432bebd.gif)

Here is a fiddle showing the behavior without react: https://jsfiddle.net/493wmzvL/2/
![firefox-drag](https://user-images.githubusercontent.com/465389/77827816-18f3b500-7118-11ea-8e16-230d88d422bd.gif)

## The current behavior
`event.target` contains the target's parent node instead of the target itself for text nodes

## The expected behavior
`event.target` should contain the target itself even for text nodes

**Comment by antoine-fl** [comment]
bump
