### ISSUE TITLE
Bug: useState only (no setState) triggers rerender

### ISSUE THREAD

**Issue by frfancha** [facebook/react#18418]
React version: 16.13.1

## Steps To Reproduce

1. create-react-app
2. change App.js to
const App = () => {
  console.log("render app");
  const [state, setState] = useState();
  return <div></div>;
};

## The current behavior
render App happens twice

## The expected behavior
render App happens once, like when the useState line is commented out:
const App = () => {
  console.log("render app");
  //const [state, setState] = useState();
  return <div></div>;
};

**Comment by gaearon** [comment]
Your app is running in Strict Mode (check `index.js`). Double rendering any components with Hooks is intentional so you can more easily find issues caused by impure render functions. This only happens in development — you'll get one render in production.

**Comment by frfancha** [comment]
That is explicitely stated in the documentation but I had skipped that, my bad
https://reactjs.org/docs/strict-mode.html#identifying-unsafe-lifecycles
_This is done by intentionally double-invoking the following methods:_
