### ISSUE TITLE
Bug: ncu(node-check-updates) shows many dependencies needing update, some major

### ISSUE THREAD

**Issue by abnud1** [facebook/react#18410]
this is ncu output in package.json currently in react master:

> 
> @babel/cli                                             ^7.8.0  →         ^7.8.4 
>  @babel/code-frame                                      ^7.8.0  →         ^7.8.3 
>  @babel/core                                            ^7.8.0  →         ^7.9.0 
>  @babel/helper-module-imports                           ^7.8.0  →         ^7.8.3 
>  @babel/parser                                          ^7.8.0  →         ^7.9.4 
>  @babel/plugin-external-helpers                         ^7.8.0  →         ^7.8.3 
>  @babel/plugin-proposal-class-properties                ^7.8.0  →         ^7.8.3 
>  @babel/plugin-proposal-object-rest-spread              ^7.8.0  →         ^7.9.0 
>  @babel/plugin-syntax-dynamic-import                    ^7.8.0  →         ^7.8.3 
>  @babel/plugin-syntax-jsx                               ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-arrow-functions                ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-async-to-generator             ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-block-scoped-functions         ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-block-scoping                  ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-classes                        ^7.8.0  →         ^7.9.2 
>  @babel/plugin-transform-computed-properties            ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-destructuring                  ^7.8.0  →         ^7.8.8 
>  @babel/plugin-transform-for-of                         ^7.8.0  →         ^7.9.0 
>  @babel/plugin-transform-literals                       ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-modules-commonjs               ^7.8.0  →         ^7.9.0 
>  @babel/plugin-transform-object-super                   ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-parameters                     ^7.8.0  →         ^7.9.3 
>  @babel/plugin-transform-react-jsx-source               ^7.8.0  →         ^7.9.0 
>  @babel/plugin-transform-shorthand-properties           ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-spread                         ^7.8.0  →         ^7.8.3 
>  @babel/plugin-transform-template-literals              ^7.8.0  →         ^7.8.3 
>  @babel/preset-flow                                     ^7.8.0  →         ^7.9.0 
>  @babel/preset-react                                    ^7.8.0  →         ^7.9.4 
>  @babel/traverse                                        ^7.8.0  →         ^7.9.0 
>  art                                                    0.10.1  →         0.10.3 
>  babel-eslint                                          ^10.0.3  →        ^10.1.0 
>  babel-plugin-syntax-trailing-function-commas           ^6.5.0  →        ^6.22.0 
>  coveralls                                              ^3.0.9  →        ^3.0.11 
>  cross-env                                              ^6.0.3  →         ^7.0.2 
>  danger                                                ^9.2.10  →        ^10.0.0 
>  eslint-config-fbjs                                     ^1.1.1  →         ^3.1.1 
>  eslint-config-prettier                                 ^6.9.0  →        ^6.10.1 
>  eslint-plugin-flowtype                                ^2.25.0  →         ^4.7.0 
>  eslint-plugin-jest                                   ^22.15.0  →        ^23.8.2 
>  eslint-plugin-no-for-of-loops                          ^1.0.0  →         ^1.0.1 
>  eslint-plugin-react                                    ^6.7.1  →        ^7.19.0 
>  fbjs-scripts                                            0.8.3  →          1.2.0 
>  filesize                                               ^6.0.1  →         ^6.1.0 
>  flow-bin                                                 0.97  →          0.121 
>  google-closure-compiler                         ^20200112.0.0  →  ^20200315.0.0 
>  jest                                                  ^24.9.0  →        ^25.2.3 
>  jest-diff                                             ^24.9.0  →        ^25.2.3 
>  minimist                                               ^1.2.0  →         ^1.2.5 
>  mkdirp                                                 ^0.5.1  →         ^1.0.3 
>  pacote                                                ^10.3.0  →        ^11.1.4 
>  prettier                                               1.19.1  →          2.0.2 
>  prop-types                                            ^15.6.2  →        ^15.7.2 
>  rimraf                                                 ^3.0.0  →         ^3.0.2 
>  rollup                                                ^1.19.4  →         ^2.2.0 
>  rollup-plugin-babel                                    ^4.0.1  →         ^4.4.0 
>  rollup-plugin-commonjs                                 ^9.3.4  →        ^10.1.0 
>  rollup-plugin-node-resolve                             ^2.1.1  →         ^5.2.0 
>  rollup-plugin-strip-banner                             ^0.2.0  →         ^2.0.0 
>  semver                                                 ^7.1.1  →         ^7.1.3 
>  typescript                                             ^3.7.5  →         ^3.8.3 
>  webpack                                               ^4.41.2  →        ^4.42.1 
> 
A lot of those are only pathes and minor like babel, but some are major, rollup is a special one in this list but so is jest,eslint-plugin-react,etc.

I'm ready to help in updating those packages if you need so.

**Comment by gaearon** [comment]
Sure, happy to take PRs. I’ll close the issue because this isn’t a problem and will always keep happening in cycles.
