### ISSUE TITLE
Bug: When we use useState, component 2 time render. why?

### ISSUE THREAD

**Issue by uxitten** [facebook/react#18422]
When we use `useState` with `<StrictMode />`, component 2 time render. why?

React version: 16.3.1

Link to code example:
https://codesandbox.io/s/rerender-bug-3ydyu
Open console

## Sample Code:
```jsx
import React, { useState } from "react";
import ReactDOM from "react-dom";

export default function App() {
  const [a, b] = useState();

  console.log("render App");

  return <h1>Hello React</h1>;
}

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);

```

And in console!

<img width="141" alt="Screen Shot 2020-03-29 at 02 56 36" src="https://user-images.githubusercontent.com/1549069/77835288-ecb45480-7168-11ea-96a1-1104f1b6b439.png">

## The current behavior
2 time render

## The expected behavior
1 time render

**Comment by gaearon** [comment]
That’s what Strict Mode does. It calls render phase code twice in development so that you can notice if it performs unexpected side effects. In production, there would be only one call.

https://reactjs.org/docs/strict-mode.html

**Comment by uxitten** [comment]
@gaearon Thanks, can you explain this reason, because I could not find on that link
