### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by seelasudheer** [facebook/react#18423]
It works in class component but in the hooks the val function calling infinity times
can any one have solution for this...........
import React, { useState } from 'react'

function Inhook(props) {
    const initialState = 0;
    const [records, setRecords] = useState([]);
    const [count, setCount] = useState(initialState);
    const [show, setShow] = useState(false);
    const [store, setStore] = useState(initialState);
    const [store1, setStore1] = useState(initialState);
    setRecords(props.records);

    function val(e) {
        debugger;
        console.log("hhh", e);
        setStore(e);
        if (store === store1) {
            if (count == 0) {
                setShow(true);
            }
            else {
                setShow(false);
            }
        }
        else {
            setShow(true);
            setCount(0);
        }
        setCount(count + 1);
        // console.log(count,'counttt');

        setStore1(e);
    }
    return (
        <div>
            <React.Fragment>
                <br />
                <div className="Tree">
                    <h1 style={{ textAlign: "center" }}>Employee Tree</h1>
                    <h3>Test Case 1</h3>
                    <h4>Employee Tree</h4>
                    {
                        records.sort((x, y) => (x.empName.toLowerCase() > y.empName.toLowerCase()) * 2 - 1),
                        records.map(empId => {
                            return empId.managerId === 0 ?

                                <ul key={empId.id} >
                                    <li style={{ fontWeight: "Bold" }}>{empId.empName.toLowerCase()}
                                        <p>Employees of : {empId.empName.toLowerCase()}</p>
                                        <ul>
                                            {records.map((s) => (s.managerId === empId.id ?
                                                <li type="square" key={s.id}>{s.empName.toLowerCase()}
                                                    {
                                                        empId.managerId === s.id ? <p>Employees of : {s.empName.toLowerCase()}</p> : <p></p>
                                                    }
                                                    {records.map((e) => (e.managerId === s.id ? <div>
                                                        {
                                                            e.managerId === s.id ? <p >{val(s.id)}</p> : <p></p>
                                                        }
                                                        {
                                                            show ? <p >Employees of : {s.empName.toLowerCase()}</p> : <p></p>
                                                        }
                                                        <li key={e.id} type="disc" style={{ marginLeft: '120px' }}>{e.empName.toLowerCase()}
                                                        </li></div> : ""
                                                    ))}
                                                </li> : ""
                                            ))}
                                        </ul>
                                    </li>
                                </ul> : ""
                        })}
                </div>
            </React.Fragment>
        </div>
    )
}
export default Inhook

**Comment by gaearon** [comment]
I already replied to you in https://github.com/facebook/react/issues/18424#issuecomment-605640709. Please stop creating duplicate issues, this is not okay.
