### ISSUE TITLE
Bug: React function component unmounts on state change.

### ISSUE THREAD

**Issue by YashGadle** [facebook/react#18427]
When rendering a function component, the state change causes the component to unmount and then remount. The same component using class based implementation won't unmount.

React version: 16.13.1

## Steps To Reproduce
Reproduce here in the sandbox...
Link to code example: https://codesandbox.io/s/youthful-shaw-fn0qv

## The current behavior
If we check the console we see the log statements showing the component being unmounted. 

## The expected behavior
It should not unmount.

**Comment by dmytro-lymarenko** [comment]
You should pass an empty array in useEffect hook in Description component like this:
```js
React.useEffect(() => {
    return () => {
      console.log("UNMOUNTED");
    };
  }, []);
```

**Comment by YashGadle** [comment]
Yes that works, but can you explain 2 things that I can't figure out:-
1. When it was unmounting why weren't the children being unmounted.
2. And when we pass an empty array it is just a componentDidMount. How does that stop from unmounting?

**Comment by dmytro-lymarenko** [comment]
@YashGadle I think for both of your question I have one answer: the component itself is not unmounted, it is the way useEffect works. That is why we don't see 'unmounting' in the console.

So, when you don't pass an array the passed callback in useEffect is going to be called every time the component is rendered. That is why you saw 'UNMOUNTED' but didn't 'unmounting'.

Note, that when you return a function from useEffect and it is going to be called that doesn't mean the component is unmounting. It only signals that effect dependencies were changed.

**Comment by YashGadle** [comment]
Oh Thanks @dmytro-lymarenko . I read the documentation a while ago and I completely missed this important concept:-

> When exactly does React clean up an effect? React performs the cleanup when the component unmounts. However, as we learned earlier, effects run for every render and not just once. This is why React also cleans up effects from the previous render before running the effects next time. We’ll discuss why this helps avoid bugs and how to opt out of this behavior in case it creates performance issues later below.

So this means that component was not actually unmounting, just cleaning up after previous render.

**Comment by mustafam-globant** [comment]
@YashGadle I was facing exactly the same issue in my project and yes your conclusion seems correct. Also, I found this detailed article here that explains the above behavior wonderfully -
https://overreacted.io/a-complete-guide-to-useeffect/#so-what-about-cleanup
