### ISSUE TITLE
Bug: Legacy context warning is misreporting the parent element

### ISSUE THREAD

**Issue by mikecousins** [facebook/react#18431]
React version: 16.13.1

## Steps To Reproduce

1. Put react-stripe-elements inside redux
2. View your warnings

Link to code example: https://codesandbox.io/s/trusting-ramanujan-0yhqb

## The current behavior
Throws a warning saying the Redux Provider element is using legacy context.

## The expected behavior
Throw a warning saying the react-stripe-elements StripeProvider element is using legacy context.

**Comment by mikecousins** [comment]
I dug into this a bit more and found the probably cause of it:

https://github.com/stripe/react-stripe-elements/blob/master/src/index.js#L2

Inside the react-stripe-elements the file is called Provider and is being renamed to StripeProvider. Sooo, it's mostly just a naming coincidence.

I don't know if it's possible to somehow report the package name though instead of the component name if it's an external library though?

**Comment by gaearon** [comment]
No, we can’t report the package name. Seems like everything is correct then. Just a naming coincidence.
