### ISSUE TITLE
Bug: useEffect returned function fires on didUnmount not willUnmount

### ISSUE THREAD

**Issue by camway** [facebook/react#18436]
This bug report relies on the expectation that a function returned in useEffect should fire on willUnmount. This seems to be agreed upon by every post I can find, but doesn't appear to be the behavior I'm experiencing.

React versions from package.json
```
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
```
Currently using node 12.15

## Steps To Reproduce

Mount this component, then force it to unmount:

```
function TesterComponent() {
  const ref = createRef();

  useEffect(
    () => {
      console.log('didMount: ', ref)
      return () => console.log('willUnmount: ', ref);
    },
    []
  )

  return (
    <div ref={ref}></div>
  );
}
```

## The current behavior

`ref` will be populated for the first debug, but be null for the second.

ex (Copied from the browser console):
```
didMount:  {current: div}
willUnmount:  {current: null}
```

## The expected behavior

Current should be populated if this is firing on willUnmount rather than didUnmount. So the above output should look like this:
```
didMount:  {current: div}
willUnmount:  {current: div}
```

**Comment by camway** [comment]
Sorry for the immediate update, but my boss had me try useRef instead of createRef, and that completely changed the behavior.

Can anyone explain to me why it changes the behavior?

**Comment by jeremy-deutsch** [comment]
`createRef()` is a normal function that returns a React ref object.
`useRef()` is a React hook that returns the same ref object throughout the lifetime of a component.
I'm not sure why this behavior is happening, exactly, but if you want to use a ref in a function component, you should use `useRef()`. In the code you pasted, the component creates a new ref object on every render with `createRef()`.

**Comment by acdlite** [comment]
Thanks for filing an issue!

The behavior you're seeing is intentional. Refs are set to `null` when the target component (the div in this case) is removed from the DOM, before any unmount effects are fired.

> This seems to be agreed upon by every post I can find

I don't know which posts you're referring to, but `willUnmount` and `didUnmount` are not official terms with agreed upon meanings. If you link to one of these posts, I can try to explain what the posts are intended to say. It's also possible the posts are just wrong.

If you need to access the element inside the unmount function, pluck it out in the mount part of the effect:

```js
useEffect(
  () => {
    const element = ref.current;
    return () => {
      // Will log: null, div
      console.log(ref.current, element);
      // At this point, `element` is no longer attached to the DOM, but you
      // can still use it to clean up, e.g. remove a custom event listener.
    };
  },
  []
);
```

**Comment by camway** [comment]
@acdlite I think @jeremy-deutsch hit the nail on the head with the createRef vs useRef. I knew the difference that createRef created a new reference on each frame, but for some reason it didn't occur to me that this would be an issue.

I didn't think about setting the element variable to retain a pointer to the original element. I think this would have worked as well.

@acdlite Below are some of the posts I was referencing (literally just google "react hooks willUnmount"). They basically try to show how to take the class based approach (didMount, willUnmount, etc) and convert them to hooks.

The TLDR is this:
```
useEffect(() => {
  console.log('didMount');
  return () => console.log('willUnmount')
}, [])
```

It didn't occur to me that the issue was with createRef vs useRef, I thought the effect was firing at the wrong time and that the element had already been removed from the page.

Just in case they are still relevant, here are the links to some of the articles:

1. https://sebhastian.com/react-hooks-useeffect#The-componentWillUnmount-and-skipping-componentDidUpdate-part
and
https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1

These two are paired together as a class vs hooks example

2. https://dev.to/trentyang/replace-lifecycle-with-hooks-in-react-3d4n (no direct anchor link, look for a header of "componentWillUnmount")

3. https://medium.com/simars/react-hooks-manage-life-cycle-events-tricks-and-tips-7ed13f52ba12 (look for "componentWillUnmount" in the code example)

4. https://medium.com/@divyabiyani26/react-useeffect-a-hook-to-introduce-lifecycle-methods-in-functional-components-e7ec52897188 (look for header "ComponentWillUnmount")
