### ISSUE TITLE
Bug: shouldComponentUpdate() doesn't being called while using this.context

### ISSUE THREAD

**Issue by BiosBoy** [facebook/react#18433]
Well, guys, I've read this post by @gaearon https://github.com/facebook/react/issues/2517 and still didn't figure out - does new context API is compatible with `shouldComponentUpdate()` since React v.16? 

As far as I tested today `shouldComponentUpdate` is not callable at all while using `this.context` on the child component.

## React version:
React & ReactDOM: v.16.13.1

## Steps To Reproduce
1. Create a basic wrapper component with its child like: `<MyContext.Provider value={store}>{child}</MyContext.Provider>`
2. Set context on the child: `static contextType = MyContext`.
3. Try to call at least some `console.log()` inside `ShouldComponentUpdate()`, 100% the last one won't event being called.

## The current behavior
Child component re-renders every time, `shouldComponentUpdate` even don't call at all.

## The expected behavior
shouldComponentUpdate should be callable while used along with `this.context` on the child components.

## UPD
I found `shouldComponentUpdate` working while using context on the child through `<MyContext.Consumer>` via HOC? That's the magic or a real bug...

**Comment by aweary** [comment]
Hey @BiosBoy! It's exepcted that `shouldComponentUpdate` isn't called when context is updated. This is [noted in the context docs](https://reactjs.org/docs/context.html#contextprovider):

> The propagation from Provider to its descendant consumers (including .contextType and useContext) is not subject to the shouldComponentUpdate method, so the consumer is updated even when an ancestor component skips an update.

Hope that helps clear things up!

**Comment by Zhell1** [comment]
I am having the same issue, I have react automatically rendering too much stuff when I update the context, where sometime only 1 consumer has changed. Is there any way to limit propagation to consumer in some cases ?
