### ISSUE TITLE
DevTools: Hovering "Rendered by" list should highlight elements

### ISSUE THREAD

**Issue by gaearon** [facebook/react#18472]
This list is pretty awesome:

<img width="390" alt="Screenshot 2020-04-03 at 00 12 08" src="https://user-images.githubusercontent.com/810438/78308234-e0047780-753f-11ea-9d4f-1e2d31e5baa0.png">

But always struggle to guess which component in the owner list I need to jump to.

We should make hovering the owner list highlight components, just like the main tree view does.

@hristo-kanchev, interested?

**Comment by hristo-kanchev** [comment]
Sure, @gaearon.

I'll try and have something in place by the end of the week.

I'll keep you updated :)

**Comment by hristo-kanchev** [comment]
Something link this?

![OwnerButton-Hover](https://user-images.githubusercontent.com/23095052/78347574-fd1d6280-75a0-11ea-9d26-1331e8b35c77.gif)

**Comment by hristo-kanchev** [comment]
I've updated the PR and added the highlight native element feature.

👇 

![HighlightRenderedBy](https://user-images.githubusercontent.com/23095052/78379498-c102f580-75d2-11ea-8b26-76fd4589fbb6.gif)

**Comment by gaearon** [comment]
Amazing. This will help me a lot. Thank you so much.
