### ISSUE TITLE
Bug: constructor declare props crash

### ISSUE THREAD

**Issue by djmisterjon** [facebook/react#18478]
Any raison why i cant declare my default props like this ?
Am new in modern front-end and am come from js vanilla, sorry if seem hard to me understand the logic !
```js
class MenueButtons extends Component {
    constructor(props) {
        super(props);
        this.props = {
            /**@type {number} description*/
            count: props?.count || 0,
            /**@type {string} description*/
            test2: props?.test2 || '',
        }
    }
```
this append if a avoid to pass all props defined ex: `<MenueButtons count='0' />`
![image](https://user-images.githubusercontent.com/24865815/78347128-fe816780-756d-11ea-8fa6-2cdc6f0322b1.png)
```Warning: MenueButtons(...): When calling super() in `MenueButtons`, make sure to pass up the same props that your component's constructor was passed.```

the only way i can see is proceed like this after the class !
```js
MenueButtons.defaultProps = {
    count: 0,
    test2: '',
};
```
But for me it look weird, and **i lost my intellisense in VsCode** !
Any way to declare my props in constructor and get intellisense work fine ?

I try declare in constructor because it the only way to get intelligence work like this.
Declare with `defaultProps` , break suggest and declarative check.

---
with declare in constructor
![image](https://user-images.githubusercontent.com/24865815/78347599-bca4f100-756e-11ea-8b24-f9234314aba1.png)
![image](https://user-images.githubusercontent.com/24865815/78347779-fbd34200-756e-11ea-8f35-0dcbddec7a63.png)

---
with declare only defaultProps 
![image](https://user-images.githubusercontent.com/24865815/78348034-58cef800-756f-11ea-8b1c-04fa3d2a2eeb.png)

**Comment by djmisterjon** [comment]
Ok after many test, this look more intuitive and logic for me.
100% compatible with intellisense from vsCode IDE.
```js

/**Class description */
class MenueButtons extends Component {
    constructor(props) {
        super(props);
        /**@type {{aaa?: number, bbb?: string }} */
        this.props
    }

    render() {
```
not yet perfect, if you have other cleaner idea, I or logic I am open to any suggestion thank you.
I can maybe also create a `typedef` top of the document for share in `defaultProps` !
```js
    /**
        * @typedef {Object} _defaultProps - ...descriptions
        * @property {number} [_defaultProps .aaa] - ...descriptions
        * @property {string} [_defaultProps .bbb] - ...descriptions
    */
```

thanks for any help

**Comment by gaearon** [comment]
Indeed, you can't overwrite `this.props` yourself.
