### ISSUE TITLE
Bug: eslint-plugin-react-hooks@3.0.0 no change logs / release page

### ISSUE THREAD

**Issue by jahed** [facebook/react#18494]
React version: eslint-plugin-react-hooks@3.0.0

## Steps To Reproduce

1. Go to Releases on GitHub
2. Nothing there about eslint-plugin-react-hooks@3.0.0
3. Try to look for a CHANGELOG for eslint-plugin-react-hooks@3.0.0
4. No CHANGELOG

Link to code example: Not code related.

## The current behavior
No change logs.

## The expected behavior
Change logs on the Releases page for eslint-plugin-react-hooks@3.0.0 or a separate CHANGELOG. Especially for major version changes so developers are aware of breaking changes that need to be fixed/prioritised.

Thank you.

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/issues/2352#issuecomment-605449782

Please feel free to help out filling that in. Thanks!

**Comment by jahed** [comment]
Thanks. I tried searching for an existing issue but couldn't find one so I thought I'd mention it.

I've gone through the commit history (standard process without release notes) but without existing knowledge of the codebase, it's a bit hard to understand what changes affect the user and how. So I'll leave someone more in-the-know to write it. :bowing_man:
