### ISSUE TITLE
Bug: Concurrent mode processes state updates out of order

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#18497]
React version: 0.0.0-experimental-[d7382b6c4](https://github.com/facebook/react/commits/d7382b6c43b63ce15ce091cf13db8cd1f3c4b7ae)

I have a sandbox that adds the next integer to an array every time you move your mouse: https://codesandbox.io/s/compassionate-currying-nccok.

Intermediate state updates get dropped, then come back later (eg: you would never expect it to render with [0, 2]):

![confused](https://user-images.githubusercontent.com/6820/78509992-f7fa1800-7746-11ea-80fb-0db0174ec0b0.png)

My expectation is that these are all the same priority level and thus should get processed in order. Am I doing something wrong?

cc @acdlite @gaearon

**Comment by sophiebits** [comment]
Same issue with UserBlockingPriority: https://codesandbox.io/s/thirsty-neumann-x1wzx.

**Comment by sophiebits** [comment]
Diagnosis in https://github.com/facebook/react/pull/18538#issuecomment-610786771.

**Comment by gaearon** [comment]
Not sure if this is fixed for good but it doesn't repro on master.
https://codesandbox.io/s/youthful-gates-yq0jw
