### ISSUE TITLE
Add key warning for TransitionGroup with single child

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react#1850]
When wrapping an item in a `ReactCSSTransitionGroup` and not giving it a `key`, upon adding/removing the item, nothing happens. The item is removed normally but no warning about a missing key is output, which is a bit confusing. Could we have a warning here, if a key is missing?

Edit:
Just to clarify: The item is removed, but no transition is performed due to classes not being added

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
