### ISSUE TITLE
Bug: Unable to import *.png and *.svg in typescript

### ISSUE THREAD

**Issue by skyorion427** [facebook/react#18507]
I cannot import asset files (e.g *.png, *.svg) in typescript version of React

React version: React v16.12.0, Typescript
```
import { ReactComponent as Icon } from './assets/SVG/xxx.svg';
import * as Icon from './assets/PNG/xxx.png';
```
## The current behavior
```
[ts] cannot find module './xxx.svg'
[ts] cannot find module './xxx.png'
```

I had to declare the module to get this issue fixed:
```
declare module '*.svg' {
  import React = require('react');
  export const ReactComponent: React.SFC<React.SVGProps<SVGSVGElement>>;
  const src: string;
  export default src;
}
```

Is this issue already fixed in any updated React version or Is there any other way to get it working properly?

**Comment by TrySound** [comment]
Probably wrong repo
https://github.com/facebook/create-react-app
