### ISSUE TITLE
Bug: dev tools development script is running production build

### ISSUE THREAD

**Issue by Faelivrinx** [facebook/react#18512]
**React Dev Tools version**: 4.6.0

I'm not sure there is a problem with `package.json` within`react-devtools-extensions` package, or it's just my misunderstand how it works, but script `build:dev` create production build. 
Command above runs a each script (per browser) in which `NODE_ENV`  is set to `production`.

## Steps To Reproduce

1. Just run `yarn build:dev` in `react-devtools-extensions`
2. It creates minified version of files.

https://github.com/facebook/react/blob/master/packages/react-devtools-extensions/package.json

```javascript 
 "scripts": {
    "build": "cross-env NODE_ENV=production yarn run build:chrome && yarn run build:firefox && yarn run build:edge",
    "build:dev": "cross-env NODE_ENV=development yarn run build:chrome && yarn run build:firefox && yarn run build:edge",
    "build:chrome": "cross-env NODE_ENV=production node ./chrome/build",
    "build:chrome:crx": "cross-env NODE_ENV=production node ./chrome/build --crx",
    "build:chrome:dev": "cross-env NODE_ENV=development node ./chrome/build",
    "build:firefox": "cross-env NODE_ENV=production node ./firefox/build",
    "build:firefox:dev": "cross-env NODE_ENV=development node ./firefox/build",
    "build:edge": "cross-env NODE_ENV=production node ./edge/build",
    "build:edge:crx": "cross-env NODE_ENV=production node ./edge/build --crx",
    "build:edge:dev": "cross-env NODE_ENV=development node ./edge/build",
    "test:chrome": "node ./chrome/test",
    "test:firefox": "node ./firefox/test",
    "test:edge": "node ./edge/test"
  },
```

## The current behavior
`"build:dev": "cross-env NODE_ENV=development yarn run build:chrome && yarn run build:firefox && yarn run build:edge"` where `build:<browser>` has  `NODE_ENV` set to `production`.

## The expected behavior
Each step in `build:dev` should be replaced from `build:<browser>` to `build:<browser>:dev`

**Comment by gaearon** [comment]
Send a PR? This does look odd.

**Comment by Faelivrinx** [comment]
Sure, I'll take a look at it tomorrow, it's looks odd and incorrectly but need to check there isn't any trap with that issue

**Comment by bvaughn** [comment]
FWIW my main intent of `build:dev` was to build a non-mangled version of DevTools to make it easier to inspect the source code. I wasn't so much thinking about DEV vs PROD React, just the transforms applied to DevTools itself.
