### ISSUE TITLE
Bug: DevTools search filtering removes a space

### ISSUE THREAD

**Issue by gaearon** [facebook/react#18518]
Compare two screenshots closely. The space after "from" disappears when the next word is selected. 
<img width="574" alt="Screenshot 2020-04-07 at 13 26 40" src="https://user-images.githubusercontent.com/810438/78668988-7b487480-78d3-11ea-8836-7c75fb907e4f.png">

<img width="776" alt="Screenshot 2020-04-07 at 13 26 35" src="https://user-images.githubusercontent.com/810438/78668983-7a174780-78d3-11ea-967e-31d3f68aef64.png">

**Comment by bvaughn** [comment]
Oops. Yeah this looks like a CSS bug.
