### ISSUE TITLE
initialize state to empty object when getInitialState is not specified

### ISSUE THREAD

**Issue by fdecampredon** [facebook/react#1851]
> hareth: sometime I feel adding a mixin to all my component with getInitialState() { return {} } 
> vjeux: hareth: i'm surprised that it's not already the case
> hareth: http://jsfiddle.net/F26zB/
> vjeux: hareth: can you see if there's already a github issue opened for it/create one? I'm curious to see what other people have to say about this

It would avoid to force: 

``` javascript
getInitialState: function () { return {} }
```

wen we need a state object, but do not need to initialize the content.

**Comment by gaearon** [comment]
We won't make changes to `createClass` anymore.
