### ISSUE TITLE
Bug: createPortal onclick event not working 

### ISSUE THREAD

**Issue by sp0033212000** [facebook/react#18516]
React version: 16.12.0

## Steps To Reproduce

https://codesandbox.io/s/vibrant-shape-t3n90

Link to code example:

https://codesandbox.io/s/vibrant-shape-t3n90

## The current behavior
onclick not trigger

## The expected behavior
trigger the onclick event

**Comment by irekrog** [comment]
https://github.com/facebook/react/issues/12355

**Comment by aweary** [comment]
See https://github.com/facebook/react/issues/12355#issuecomment-410996235 for an explanation
