### ISSUE TITLE
Bug / Enhancement: After building site and deploying it to a host website, react routes (react-router-dom) get broken.

### ISSUE THREAD

**Issue by AimanAlmureish** [facebook/react#18526]
React version: 16.13.1

## The current behavior

Hello guys! I hope you all doing well! Recently I and my team was working on a react project and we find out that after building the website and deploying it to a host site all routes (react-router-dom) that were created were broken. When trying to access them without actually getting into the website so let's assume that I copied  www.example.com/routeName this will not work directly and nothing is showing up or a default error page is showing. When I refresh the same problem appears. 

## Suggested solution

After a search, we get to know the problem better and got this solution. In the build directory, we had to add `_redirects` file with the following code `/*    /index.html   200` so if this can be built automatically to the project it would be great and thanks!

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by AimanAlmureish** [comment]
> Hey there! We use the issue tracker for bug reports and feature requests.
> 
> If you have a question, please check our community support resources:
> https://facebook.github.io/react/community/support.html

Hello, @aweary I did not get it do I have to create this issue in the issue tracker and where to find it... Thanks!
