### ISSUE TITLE
Bug: the component doesn't reset state when the key specified from dev tools

### ISSUE THREAD

**Issue by dchebakov** [facebook/react#18525]
React version: 16.12.0
![Screen Recording 2020-04-07 at 19 37 20](https://user-images.githubusercontent.com/26152276/78696380-05123500-7908-11ea-9ee2-49fce37e3a78.gif)

## Steps To Reproduce
1. Open [sandbox example](https://6yorx.csb.app/)
2. Click plus button
3. Open react dev tools and specify key prop

Link to code example:
https://6yorx.csb.app/ - basic "counter" example

## The current behavior
Component received key as prop and just rerender. 

## The expected behavior
Component recreated according to the specs when key prop changed.

**Comment by bvaughn** [comment]
This is actually working as expected.`key` is not a prop. It's a special thing, like `ref`:
https://github.com/facebook/react/blob/03de849af03996b7477420c97de7741ce1214149/packages/react/src/ReactElement.js#L16-L21

When an element is created, these special props are filtered out explicitly:
https://github.com/facebook/react/blob/03de849af03996b7477420c97de7741ce1214149/packages/react/src/ReactElement.js#L300-L308

And then they are passed along as separate values on the `ReactElement`:
https://github.com/facebook/react/blob/03de849af03996b7477420c97de7741ce1214149/packages/react/src/ReactElement.js#L333-L341

Setting a "key prop" in DevTools is kind of a no-op unfortunately. It is not what React uses to actually key elements.

Sorry for the confusion :smile:

**Comment by dchebakov** [comment]
I believed that it is the right way to reset element state from dev tools. Is there another way to reset state?

**Comment by bvaughn** [comment]
There is no way to "reset" an element in DevTools, at least not in the way that I think you mean. DevTools lets you read props/state, or modify individual values though.
