### ISSUE TITLE
Bug: incorrect focus on mount of pre-filled textarea  

### ISSUE THREAD

**Issue by ApoorvaJain** [facebook/react#18530]
When a pre-filled textarea is mounted on DOM and focused programmatically, the cursor appears behind the text at 0 position. 
This behaviour is only observed in react application. The same thing when implemented with vanilla javascript works fine. 

React version: 16.2.*

## Steps To Reproduce

1. Render a textarea in your react component with a pre-filled value.  
2. Set the textarea in focus as soon as the component is mounted on the DOM.
3. Observe that the cursor appears before the text, at 0 position.

## The current behavior
The cursor appears before the text when the textarea is mounted for the first time.
Link to code example:
[React App - codepen](https://codepen.io/apoorvajainUI/pen/mdJNoNY?editors=0010)

## The expected behavior
The selection start should be equal to the length of the text the textarea is pre-filled with, and the cursor should appear after the text, as soon as it is focused.
[code written in vanilla js](https://codepen.io/apoorvajainUI/pen/PoqMLoB?editors=1011)

## Observations

1. This bug started to appear only after Chrome version 76 and Firefox version 66. The code used to work just fine in older versions of these browsers.
2. This problem only happens when the textarea is mounted for the first time on the DOM. After mounting, it behaves as expected when i set the focus programmatically. Also, if the textarea is already mounted and I set the display from `none` to `block`, this works fine.
3. The `selectionStart` is 0 when I check it in the onFocus callback. But, in the vanilla javascript application, both `selectionStart` and `SelectionEnd` are set to the length of the text(which is the expected behaviour).

## Current Solution/Workaround

The way I fixed this issue in my code is, by resetting its value to a blank and then again to its desired value in the lifecycle method `componentDidMount` or in the `onFocus` callback of the textarea

```
    // this.textareaRef.current.value = "";
    // this.textareaRef.current.value = this.state.value
```

**Comment by gaurav5430** [comment]
Figured out a probable cause:

The problem appears to be here:
https://github.com/facebook/react/blob/3e94bce765d355d74f6a60feb4addb6d196e3482/packages/react-dom/src/client/setTextContent.js#L34

On latest chrome, setting the `textContent` does not update the `selectionStart` and `selectionEnd` and hence the cursor stays at the default value of 0.
It works fine in previous chrome versions (prior to 76)

Here is a codepen demonstrating the same issue in vanilla javascript.
https://codepen.io/gaurav5430/pen/NWGKNrX
