### ISSUE TITLE
Bug:  New Components and Profiler tabs missing in Chrome DevTools

### ISSUE THREAD

**Issue by stevehanphoto** [facebook/react#18546]
The new Components and Profiler tabs are missing in Chrome DevTools.

React version: N/A

## Steps To Reproduce

1. Open Chrome
2. Control-Shift-I to open Chrome Developer Tools

## The current behavior
No Components and Profiler tabs.  See screenshot
![Screenshot (190)](https://user-images.githubusercontent.com/15229911/78838043-275c8f00-79aa-11ea-9344-66b860f8e5e9.png)

## The expected behavior
Components and Profiler tabs should appear near the top of Chrome DevTools.

**Comment by bvaughn** [comment]
These tabs only appear if you're viewing a web page that uses React, which the Google extensions store does not :smile: Visit e.g. www.reactjs.org to see the tabs.

**Comment by dayoolacodes** [comment]
the Component and Profilers tab still does not show up even after viewing www.reactjs.org
