### ISSUE TITLE
[react-hooks/exhaustive-deps] function outside the hook

### ISSUE THREAD

**Issue by eshturman** [facebook/react#18541]
Hi! I have some problems with [react-hooks/exhaustive-deps] rule of eslint. Can you help me, please?

<img width="293" alt="Снимок экрана 2020-04-08 в 18 55 09" src="https://user-images.githubusercontent.com/34343461/78781465-7fa38900-79ca-11ea-94fe-2a80ef7c1d2a.png">

I have some effect, which to call function. Linter tells me that I should add getData to dependency. But I do not want my effect to depend on the function. I will have to wrap it in useCallback which may have its own dependency.

<img width="463" alt="Снимок экрана 2020-04-08 в 18 55 57" src="https://user-images.githubusercontent.com/34343461/78781519-9b0e9400-79ca-11ea-886a-fdacb0cc2b5e.png">

I need my useEffect hook to be called only 1 time. But in this case, it will be called whenever id changes. How do I get around this behavior?

I have seen advice to put a function inside a hook, but this is not my case. I have to call this function from different hooks.

**Comment by vkurchatkin** [comment]
You are free to ignore linter if that's what you want

**Comment by bvaughn** [comment]
A change in `id` would mean a change in output for `getData`, so you *would* want scopes to be re-created any time this happened.

**Comment by eshturman** [comment]
@bvaughn but I want that useEffect will be called only 1 time. I'm not interested in further id change

**Comment by gaearon** [comment]
> but I want that useEffect will be called only 1 time. I'm not interested in further id change

Then your component will behave incorrectly on updates. Props can change any time, so you need to handle them and eventually show the same result as you would if those props were rendered initially.

Of course, you are free to make your component buggy by ignoring the rule. Or work around it explicitly by doing something like this:

```js 
const [initialId] = useState(id)
// Now use initialId, it won’t change
```

But that would usually lead to bugs.

**Comment by eshturman** [comment]
@gaearon thanks!
