### ISSUE TITLE
Bug: Props Does Not Update For Functions Bind In Constructor

### ISSUE THREAD

**Issue by git-blame** [facebook/react#18552]
Functions that are bound in component constructor uses initial value of _this.props_ despite later changes to props.

Note: I'm a back-end systems (python, c, etc.) developer who has been asked to help out with UI debugging because we are currently short-staffed. So I admit I don't know all the nuances of React.

React version: 16.13.0

## Steps To Reproduce

Many of our UI components bind their functions in order to access _props_ and _state_ following the recommendations of this [faq-functions](https://reactjs.org/docs/faq-functions.html). To quote:
```javascript
class Foo extends Component {
  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }
```

Everything used to work until we recently updated our dependency to a newer version of react. Now we are getting UI errors which seem to be caused by bound functions only using the "initial" values of props and not new values.

```javascript
class NavButton extends PureComponent {
  constructor(props) {
      super(props);
      this.state = {
      };
      if (props.label === 'dashboard') {
          console.log('bind -> button: ' + props.label + ' selected: ' + props.selected );
      }
      this.getBtnStyle = this.getBtnStyle.bind(this);
  }

  getBtnStyle() {
      const { props } = this;
      let style = styles.navBtn;
      if (props.label === 'dashboard') {
          console.log('getBtnStyle -> button: ' + props.label + ' selected: ' + props.selected);
      }
...
      return style;
  }

  render() {
      const { props } = this;
      if (props.label === 'dashboard') {
          console.log('render -> button: ' + props.label + ' selected: ' + props.selected);
      }
      const style = this.getBtnStyle();
...
}
```

From the console log, I can see that property _selected_ does not change for function _getBtnStyle()_ even though it changes for _render()_ as a user is interacting with the UI:

```
bind -> button: dashboard selected: true                     NavButton.js:17
render -> button: dashboard selected: true                  NavButton.js:41
getBtnStyle -> button: dashboard selected: true          NavButton.js:26
render -> button: dashboard selected: false                 NavButton.js:41
getBtnStyle -> button: dashboard selected: true          NavButton.js:26
```

## The current behavior
Bind functions and Class properties (i.e., `handleClick = () => { ... }`) do not use updated props. To use updated props, need to:
* have regular function (not bind, or class properties)
* bind function in render (for passing to other components) or calling function in render. 

## The expected behavior
Bind functions use updated props.

As stated, this used to work up until a recent refresh of our npm packages. Also, given the React faq, this seems to be fundamental behaviour for React. So it's probably a bug with our set-up, maybe with our other dependencies, etc.

Our option now seems to be changing all components to implement "bind function in render". But before we do this big change, I was hoping someone could point out what's wrong.

**Comment by gaearon** [comment]
Can you try to make an isolated example reproducing it? This sounds like something going bad with your compilation toolchain. Seeing the generated code (which runs in the browser) would also help.

**Comment by git-blame** [comment]
Thanks for the reply. I did some more debugging because some components worked and some didn't. It turns out that the ones that didn't was wrapped in a module called Radium. I updated this module hoping for the best and it turns out that this fixed everything.

I tried looking at their past issues but didn't find anyone raising a similar one.

But for react >= 16.12.0, you should have radium >= 0.25.0.
