### ISSUE TITLE
Add more immutability helpers.

### ISSUE THREAD

**Issue by Gonzih** [facebook/react#1856]
Hello, I like Idea of immutability helpers in react, but I find them incomplete. I still from time to time switch to Underscore for complex operations on data. Does it make sense to add more helpers like:

* $map
* $filter
* $fold
* set like operations (union/difference/intersection), of course they can be implemented in terms of fold.

What do you think guys? Thanks.

**Comment by gaearon** [comment]
As far as I know the current thinking is that `React.addons.update` is in maintenance mode and will not get new features. We encourage people to look at Immutable.js or alternative libraries that deal with plain objects instead.
