### ISSUE TITLE
Bug: Type warning on forwarding ref of createPortal

### ISSUE THREAD

**Issue by sayjeyhi** [facebook/react#18577]
`forwardRef` for a `createPortal` has a type warning which says : 
```bash
Argument type function(*, *): {chilren, implementation, containerInfo, $$typeof, key} is not assignable to parameter type RefForwardingComponent<unkown, {}>
```
Actually I see this warning only on intellij idea platforms, for example : 
```javascript
// Argument type function(*, *): {chilren, implementation, containerInfo, $$typeof, key} is not ...
const Tooltip = forwardRef((props, ref) => {
  const element = useRef(document.body);
  return (
    createPortal(
      <div ref={ref}>{props.children}</div>,
      element.current,
    )
  )
});
```

React version: 16.13.1
Link to code example: [codesandbox.io](https://codesandbox.io/s/infallible-kepler-c3zxl?file=/src/App.js:118-314)

**Comment by aweary** [comment]
@sayjeyhi I don't see any type annotations in the sandbox you linked, but it sounds like a TypeScript error. We don't maintain the TypeScript definitions for React. You should report any issues to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react).
