### ISSUE TITLE
Bug: react-hooks/exhaustive-deps not warning about unneeded dep

### ISSUE THREAD

**Issue by tonix-tuft** [facebook/react#18587]
In the following example:

```
import ReactDOM from "react-dom";
import React, { useEffect } from "react";
import "./styles.css";

function Example() {
  const id = 123;
  const valueWhichMayChange = Math.random();
  useEffect(() => {
    return () => {
      //valueWhichMayChange === 0.5 &&
      document.getElementById(id).click(); // Just dummy functionality...
    };
  }, [id, valueWhichMayChange]); // Would expect unneeded "valueWhichMayChange" dep warning here.
  return <div id="123" />;
}

ReactDOM.render(<Example />, document.getElementById("root"));

```

`react-hooks/exhaustive-deps` doesn't warn me about `valueWhichMayChange` unneeded dep, even though I have commented the line:

```js
      ...
      //valueWhichMayChange === 0.5 &&
      ...
```

The same thing happens if I completely delete the line, no warning issued.

React version: 16.12

## Steps To Reproduce

1. Open Codesanbox.
2. Look at line 13.

Link to code example: https://codesandbox.io/s/react-example-ey9pw?file=/index.js

## The current behavior
No warning for `valueWhichMayChange`, though it is an unneeded dependency.

## The expected behavior
Warning for `valueWhichMayChange` unneeded dependency.

Thanks a lot for your attention!

**Comment by vkurchatkin** [comment]
There is no such thing as "unneeded dependency" in useEffect. You might not use a variable, but still want to trigger effect when it changes

**Comment by tonix-tuft** [comment]
@vkurchatkin So that kind of warning doesn't apply to `useEffect` hook? Does it mean that it only applies to `useCallback`, `useMemo` hooks and the like, e.g. like in the following example:

```
  ...
  const [price, setPrice] = useState({ maxPrice: 0, minPrice: 0 });

  const inputMaxMin = useCallback(
    ({ target: { value, name } }) => {
      name === "maxPrice"
        ? setPrice(({ minPrice }) => ({ maxPrice: value, minPrice }))
        : setPrice(({ maxPrice }) => ({ minPrice: value, maxPrice }));
    },
    [price] // <<<<< React Hook useCallback has an unnecessary dependency: 'price'. Either exclude it or remove the dependency array. (react-hooks/exhaustive-deps)eslint
  );
  ...
```

?

**Comment by aweary** [comment]
@tonix-tuft yes, `useEffect` is different in this respect. The purpose of `useCallback` and `useMemo` is to memoize some value based on a known set of inputs. If you have an unnecessary dependency, that memoized value will be re-created more more often than necessary. 

As @vkurchatkin mentioned, this doesn't apply to `useEffect`. It's a valid use case to trigger an effect when some value changes, even if you don't use that value. For example, you might want to clear some errors in a form when some input value changes

```js
let [value, setValue] = useState("");
let [errors, setErrors] = useState(null);

// The input's value changed, clear any errors we reported earlier!
useEffect(() => {
  setErrors(null);
}, [input])
```

Hope that clears things up!

**Comment by tonix-tuft** [comment]
@aweary Thank you very much for your explanation! This makes sense now. The same applies to `useLayoutEffect`, doesn't it?

**Comment by aweary** [comment]
@tonix-tuft exactly, `useLayoutEffect` is just like `useEffect`. The only difference is the timing.

**Comment by tonix-tuft** [comment]
Yessa 

![Uploading image.png…](https://raw.githubusercontent.com/donavon/hook-flow/master/hook-flow.png)
