### ISSUE TITLE
Why is the output executed twice

### ISSUE THREAD

**Issue by VitaminCtea** [facebook/react#18583]
I am simulating the undo and redo functions, but every time I click the undo button, the console prints the result twice instead of every time. What should I do? Is this the react bug? This is also the case with the function component hook count example, where the useEffect callback function prints the same value twice.

React version: 16.13.1

## Steps To Reproduce

1. When I click the undo button, I want the console to print the undo result data after one click
2. Exits the function until the undo array is empty

code example:
```
class UndoAndRedo extends React.Component<any, any> {
    constructor(props: any) {
        super(props)
        this.state = {
            past: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            present: null,
            future: [],
        }
        this.handlers = this.handlers.bind(this)
    }
    handlers() {
        if (!this.state.past.length) return
        if (!this.state.present) {
            this.setState((obj: any) => ({ ...obj, present: obj.past.pop() }))
            return
        }
        this.setState((obj: any) => {
            obj.future.unshift(obj.present)
            obj.present = obj.past.pop()
            return obj
        })
    }
    componentDidUpdate(prevProps: Readonly<any>, prevState: Readonly<any>, snapshot?: any): void {
        console.log(this.state)
    }

    componentDidMount(): void {
        console.log(this.state)
    }

    render() {
        return (
            <button onClick={ this.handlers }>undo</button>
        )
    }
}
```

## The image link address for the current behavior
[https://github.com/VitaminCtea/reportImage/blob/master/1.png](url)

## Image link address for expected behavior
[https://github.com/VitaminCtea/reportImage/blob/master/2.png](url)

**Comment by gaearon** [comment]
Your app is running in strict mode (check `src/index.js`). Strict mode helps catch bugs caused by side effects and mutations by intentionally calling twice functions that are supposed to be pure. (If they’re really pure then this should not affect the behavior of your program.)

In your example, the function you pass to setState updates the array by mutating it. That’s the problem. If you do the same without mutation, you’ll fix the issue.
