### ISSUE TITLE
Feature request: Add new syntax for classes

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [facebook/react#18590]
**Attributes names with started a dot symbol is prohibited, so dot is idle idle. dot can be used for syntactic sugar for routine 90% of the operations of assigning classes to elements.**

new JSX class syntax:
1) attr start with dot is class name (intentionally similar to css, yes)
2) if this attr have expression value, then if exp is true, then class exists, otherwise not exist

```javascript
<div .block .chat .active={ this.state.active }></div>
```

its equivalent for 
```javascript
<div className={ `block chat${ this.state.active ? " active" : "" }` } ></div>
```

people will be able to write a main class describing what kind of entity it is. and add dynamic modifier classes, which reflect the component state.

it’s just syntactic sugar. but it will save 90% of the time for developers. the programmer simply type on a keyboard the dot symbol, and the IDE will automatically autocomplete them for the available classes.

in brevity and elegance, this syntax is even superior to html ;)

like if you want it, let's see how many of us =)
---

**Comment by MaxmaxmaximusGitHub** [comment]
our beloved jsx is high time to develop, because competitors (angular and vue) do not stand still ;)

**Comment by bvaughn** [comment]
Anything like a new syntax request needs to follow the RFC process:
https://github.com/reactjs/rfcs/

Changes like this would impact a lot of tooling (e.g. Babel, IDEs) and need to be vetted and discussed in a way the RFC process encourages.
