### ISSUE TITLE
feat: allow multiple opaque identifiers in HTML attributes

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#18594]
react version: #17322
Original: https://github.com/facebook/react/pull/17322#issuecomment-613104823

Currently only a single value from `useOpaqueIdentifier` (unreleased) can be passed to HTML attributes. However, there are HTML attributes which support multiple ids (IDREFS) like `aria-labelledby`. This can be used to implement various patterns such as: 
```jsx
export default function App() {
  const taxpayerId = React.unstable_useOpaqueIdentifier();
  const spouseId = React.unstable_useOpaqueIdentifier();
  const w2GrossId = React.unstable_useOpaqueIdentifier();
  const dividendsId = React.unstable_useOpaqueIdentifier();
  return (
    <table>
      <tbody>
        <tr>
          <td />
          <th id={taxpayerId}>Taxpayer</th>
          <th id={spouseId}>Spouse</th>
        </tr>

        <tr>
          <th id={w2GrossId}>W2 Gross</th>
          <td>
            <input type="text" aria-labelledby={[taxpayerId, w2GrossId]} />
          </td>
          <td>
            <input type="text" aria-labelledby={[spouseId, w2GrossId]} />
          </td>
        </tr>

        <tr>
          <th id={dividendsId}>Dividends</th>
          <td>
            <input type="text" aria-labelledby={[taxpayerId, dividendsId]} />
          </td>
          <td>
            <input type="text" aria-labelledby={[spouseId, dividendsId]} />
          </td>
        </tr>
      </tbody>
    </table>
  );
}
````
-- https://codesandbox.io/s/useopaqueidentifier-for-idrefs-ocnm4

This example is from https://www.w3.org/WAI/GL/wiki/Using_aria-labelledby_to_concatenate_a_label_from_several_text_nodes

This currently almost works but it concatenates the ids with `","` (default toString of arrays) instead of `" "`.

`<button aria-labelledby={[opaqueIdentifier1, opaqueIdentifier1]} />` is to me the most intuitive one since we're passing a list of ids. 

Edit:
Removed the collapsible listbox example since that pattern has some a11y issue.

**Comment by aweary** [comment]
I like the API of using an array of opaque identifiers. You could make the argument that React should always join arrays passed to DOM attributes with a space, since the HTML spec defines the space as the list delimiter. This would be a breaking change though.

One alternative would be iterating through every array passed to an attribute and checking that each item is an opaque identifier. That's a lot of potentially wasted work though.

Maybe a special value like `React.createIdentifierList` that React could check for and serialize differently?

**Comment by aweary** [comment]
@eps1lon I believe you can safely get around this for now by using a [custom class that extends `Array` and overrides `toString`](https://codesandbox.io/s/prod-lake-iu197?file=/src/App.js:378-439).

**Comment by eps1lon** [comment]
> Maybe a special value like React.createIdentifierList that React could check for and serialize differently?

Which also has the upside that it won't trigger `jsx-a11y/aria-proptypes` or [TypeScript type errors](https://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoczAVwDsNgJa5qBnJAeTBQEdqkAkgBMktGMEzAkUABQBKOAG9ycVXCIxqUZsrV64MCAGUYUYLQDm8pSv12NW5vjK27AX1dw3FD1ToMmOABhXEhaURhrXTU0JlZ4YCEARjgAXhZ2Ll5+YQiJKVk5Cj1Y2ni4RIAmNIzObj5BETF86XlitQdtOAAeACNqGENmFDMUAFoAGxRepAmJpCFegE9UxQBtRKSAGgqhSoBdNzgAegA+cjcgA) (we would need to claim that opaque identifiers are strings for TS to accept it. On the other hand we need to change types anyway for useOpaqueIdentifier) . 

Having the array shorthand is definitely nice but I think having an explicit createIdentifierList is safer long term.

**Comment by eps1lon** [comment]
@aweary Seems like your approach only works for `.render`. It throws during hydration (using `.hydrate` with

> The object passed back from useOpaqueIdentifier is meant to be passed through to attributes only. Do not read the value directly.

-- https://codesandbox.io/s/serverless-tdd-7ltt5

**Comment by diegohaz** [comment]
Bump

**Comment by diegohaz** [comment]
Bump

**Comment by gaearon** [comment]
I’ve added a label to revisit so that stale bot stops trying to close this.

**Comment by eps1lon** [comment]
Implemented with `useId` in https://github.com/facebook/react/pull/22644
