### ISSUE TITLE
Remove unstable_ from unstable_batchedUpdates

### ISSUE THREAD

**Issue by davidgilbertson** [facebook/react#18602]
With [react-redux 7 now re-exporting `unstable_batchedUpdates` as `batch`](https://github.com/reduxjs/react-redux/releases/tag/v7.0.1), it effectively means that any change to this API would break a lot of websites.

Given that the react-redux team were encouraged to use this API by the React team, is that a hint that the general public and library authors can consider this a stable API?

Renaming is a big ask, I'd be happy with a response here saying "changes to that API will respect semver even though it's flagged as 'unstable'".

Thanks!

**Comment by gaearon** [comment]
We wouldn’t remove it in a minor, yeah. It might go away in a future major because it would become the default behavior. In that world React Redux could make the helper a no-op that calls through.

**Comment by markerikson** [comment]
We'd also likely publish a new React-Redux major with that kind of a change.

**Comment by gaearon** [comment]
Ironically, renaming it _would_ be a breaking change.
