### ISSUE TITLE
show props in console

### ISSUE THREAD

**Issue by hayoungishere** [facebook/react#18601]
how can i check props on chrome developer tools?

👉 Please follow one of these issue templates:
- https://github.com/facebook/react/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by kunukn** [comment]
You could follow this guide.

https://reactjs.org/blog/2019/08/15/new-react-devtools.html

**Comment by hayoungishere** [comment]
Thks! It is so helpful😆😆
