### ISSUE TITLE
Can repro this in browserstack with Pixel XL and default chrome browser, here's a gif of the behavior (notice after I press spacebar the word disappears):

### ISSUE THREAD

**Issue by b823** [facebook/react#18606]
Can repro this in browserstack with Pixel XL and default chrome browser, here's a gif of the behavior (notice after I press spacebar the word disappears):
![android](https://www.dropbox.com/s/904l9baubex0u0s/android-2.gif?raw=1)

_Originally posted by @icd2k3 in https://github.com/facebook/draft-js/issues/1077#issuecomment-321041952_

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests for React itself. If you have a support question, please check our [community support resources](https://facebook.github.io/react/community/support.html). If you think this is a bug in React, please file an issue with the information requested in the bug report template (steps to reproduce, code example).
