### ISSUE TITLE
Bug: disableRemotePlayback not recognized

### ISSUE THREAD

**Issue by tomprats** [facebook/react#18618]
Passing `disableRemotePlayback` as an attribute like so:

```
<video disableRemotePlayback={true}>
```

Produces the warning:

> Warning: React does not recognize the `disableRemotePlayback` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableremoteplayback` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

It seems like React should recognize it's similar to https://github.com/facebook/react/pull/15334.

React version: 16.13.1

## The current behavior

Warning and not rendering the attribute

## The expected behavior

Adding the attribute similar to how it'd render `disablePictureInPicture` with a final output of:

```
<video disableRemotePlayback ...>
```

When rendering it with:

```
<video disableRemotePlayback={true} ...>
```

**Comment by tombrowndev** [comment]
Create a PR #18619

**Comment by tombrowndev** [comment]
@tomprats This has been merged in. Feel free to close the issue,

Cheers
