### ISSUE TITLE
Bug: ReactArt-test fails with new node version

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#18610]
## Steps To Reproduce

0. Use node 10
1. git checkout master
2. yarn test ReactArt

## The current behavior

The following tests fail with `in <anonymous> (at **)` as the stack instead of the full component stack:
- ReactARTComponents › should warn if radius is missing on a Circle component
- ReactARTComponents › should warn if width/height is missing on a Rectangle component
- ReactARTComponents › should warn if outerRadius/startAngle/endAngle is missing on a Wedge component

## The expected behavior

I'm not familiar with `react-art` so it's unclear whether node 12 needs to be used for local development (`.nvmrc` should be updated) or whether react-art should work with node 10.

## Context

Bisecting leads to 98d410f5005988644d01c9ec79b7181c3dd6c847 which got introduced in #18561. /cc @sebmarkbage

**Comment by eps1lon** [comment]
Closed in https://github.com/facebook/react/pull/18623

**Comment by acdlite** [comment]
Oh lol I just saw this. Thanks for reporting!

**Comment by acdlite** [comment]
Re-opening until the underlying issue is fixed

**Comment by bvaughn** [comment]
> ## Steps To Reproduce
> 1. Use node 10

Note that this occurs for v11 and some versions of v12 too (e.g. v12.6) but works with later versions (e.g. v12.16)

**Comment by kambleaa007** [comment]
i have seen same,
ReactARTComponents › should warn if radius is missing on a Circle component
ReactARTComponents › should warn if width/height is missing on a Rectangle component
ReactARTComponents › should warn if outerRadius/startAngle/endAngle is missing on a Wedge component

https://github.com/facebook/react/issues/19760

**Comment by justingrant** [comment]
I'm seeing the same failures on my Mac, so I'd suggest re-opening this. Versions: 
* `node -v` v16.5.0
* `yarn -v` 1.22.4
* MacOS: Big Sur 11.5.2 (20G95)
* React is running latest main branch just rebased a few days ago

LMK how I can help repro this and/or diagnose the root cause. It's actually a somewhat annoying issue when working on PRs because tests never run green.

**Comment by rickhanlonii** [comment]
@justingrant thanks, confirmed. Here's the failure:

<img width="1319" alt="Screen Shot 2021-09-15 at 2 50 35 PM" src="https://user-images.githubusercontent.com/2440089/133492331-8cbcd6c8-f589-468d-bf69-d73de5416dea.png">

Looks like the component stack is broken? But might be specific to prop-types. cc @bvaughn for interest

**Comment by cyntler** [comment]
@justingrant @rickhanlonii
Yes, in the newest versions of Node I also have the same error.
When I ran `nvm use` to use Node's v12.17.0 specified in the .nvmrc file, the tests passed.

**Comment by eps1lon** [comment]
`yarn test ReactART` passes on node `14.17.6` (current `.nvmrc`), 12.22.10 (12 latest), 14.19.0 (14 latest), 16.14.0 (16 latest) and 17.6.0 (17 latest).
