### ISSUE TITLE
Bug: react-is isLazy is error

### ISSUE THREAD

**Issue by frontlich** [facebook/react#18651]
React version:

react 16.13.1
react-is 16.13.1

## Steps To Reproduce

import { isLazy } from 'react-is';

const Test= lazy(() => import('./Test'));

console.log(isLazy(Test));

Link to code example:

## The current behavior
console result is false

## The expected behavior
console result is true

**Comment by eps1lon** [comment]
react-is works on elements not element types. This was deliberately changed for React.lazy in #17278
