### ISSUE TITLE
Bug: Context value change results in rendering of components that do not consume said context

### ISSUE THREAD

**Issue by lee-borsboom** [facebook/react#18686]
Given the following structure:

```
<MyContext.Provider value={value}>
  <A>
   <B>
    <C />
   </B>
  </A>
</MyContext.Provider>
```

A and B will be re-rendered when the context value changes because C is consuming it. This _appears_ to be unnecessary as preventing A (and thus B) from re-rendering still results in changes from C being reflected in the DOM.

This is obviously a performance issue, particularly when the context value changes frequently due to user interaction (in my case, on keystroke of a text field).

This seems like the sort of thing that could very well be intentional and I'm missing some use cases that necessitate this behaviour, but from my sample code and in a complex real-world scenario, short-circuiting the render of A when only "children" change _seems_ to work and with a lot less renders.

React version:
Noticed in 16.8.3, confirmed the same behaviour in 16.13.1

## Steps To Reproduce

Code example: https://codesandbox.io/s/eager-jones-4xg6e?file=/src/App.js

## The current behavior
Components that do not consume the context value directly are re-rendered due to a change in context value

## The expected behavior
Only direct consumers of the context value are re-rendered due to a change in context value

**Comment by vkurchatkin** [comment]
This is how React works. When you update state the component is rerendered, including all of the descendants,  unless there is a React.memo somewhere

**Comment by gaearon** [comment]
I don’t think this has anything to do with context. Remove the context provider and you’ll still see the same behavior. Indeed, if you setState, components below re-render. Whether there’s a provider there or not.

 But you can use `React.memo` on components in the middle to prevent unnecessary updates. Just like you would normally.
