### ISSUE TITLE
list of React Addons and Modules

### ISSUE THREAD

**Issue by nmn** [facebook/react#1868]
I know there are talks of a set of guidelines for building re-usable components for React.

I think there should a central place that maintains a list of all know React Utilities, Addons, Extensions and re-usable modules.

**Comment by gaearon** [comment]
This sounds rather broad, and with the explosion of the components around React, is not something we could maintain in a good shape, so I’m inclined to close. There are a few community resources available now:

* https://js.coach/react
* https://react.rocks/
* http://react-components.com/

I hope this helps!
