### ISSUE TITLE
Bug: Effects never fire if the dependency list changes length and then stabilizes 

### ISSUE THREAD

**Issue by aweary** [facebook/react#18683]
[CodeSandbox reproducing the problem with the latest experimental build](https://codesandbox.io/s/eager-morning-tbfjm?file=/src/App.js:341-342)

This is an edge case with a DEV warning, so not really a priority, but it seems like the wrong behavior. If the length of the dependency array changes, React warns about it and the effect never fires. That seems reasonable. 

If there's a subsequent update where the dependency array _no longer changes length_, React still warns and the effect still doesn't fire. 

## Steps to Reproduce

1. Open the sandbox, check the console
2. Start incrementing the counter. You'll see the dependency array increases in length as the counter increases, triggering the warning. Note that the warning always references the initial empty array as the "Previous" value, even though that isn't accurate.
3. Once it hits `5` the array stops growing. In subsequent updates only the last item in the array changes.

## Expected Behavior

It's confusing that React still warns about the length change after it stops changing. It's also confusing that React doesn't fire the effect at all after it stops changing. It feels like React gets into a broken state and it should either recover or throw. Otherwise I can see an edge case where this warning gets ignored (or doesn't fire) in development and then effects stop firing in production.

**Comment by gaearon** [comment]
>Otherwise I can see an edge case where this warning gets ignored (or doesn't fire) in development and then effects stop firing in production.

Can you clarify in which case it wouldn't fire in development?

Generally saying, we try to minimize checks in hot paths in production. Similar to hydration and attributes, where we don't attempt to match up.

I think as soon as you change the length once, this is broken contract and all bets are off. As long as we warn in this case, I think it's reasonable that from that point on, the behavior is effectively undefined. Whatever lets us get away with fewest prod checks.

**Comment by aweary** [comment]
> Can you clarify in which case it wouldn't fire in development?

Imagine a user deriving the dependency array from a list of URL parameters and only ever testing with the same exact number of parameters. They'd never see the warning, but it's possible (likely) that there would be production scenarios where that assumed invariant doesn't hold up.

If the user isn't using the lint rules (or ignores them) they wouldn't ever know there was a problem until effects stopped firing in production.

> I think as soon as you change the length once, this is broken contract and all bets are off. As long as we warn in this case, I think it's reasonable that from that point on, the behavior is effectively undefined. Whatever lets us get away with fewest prod checks.

I'm not sure if just having a warning is sufficient if this puts React into a broken state. Even with hydration or attributes React still operates correctly.

The language in the warning should probably be stronger at the very least.

**Comment by gaearon** [comment]
>Even with hydration or attributes React still operates correctly.

With hydration, React doesn't patch them up so the result is inconsistent. Similar, with duplicate keys, we don't make guarantees about what you'll see. Can you clarify why you consider this differnet?

**Comment by aweary** [comment]
I guess the duplicate keys warning is effectively the same scenario.
