### ISSUE TITLE
Bug: [eslint-plugin-react-hooks] Custom Hooks are not linted with Namespace Imports

### ISSUE THREAD

**Issue by zachhats** [facebook/react#18682]
Normally if you use a custom hook from anywhere other than a top-level function component, you get a lint error. However, if the custom hook is imported with a namespace import, you don't see a lint error. It's worth mentioning, I'm using typescript, I'm not sure if this repros with regular JS.

React version: We use 16.9, but the create-react-app repro below is with ^16.13.1. It repros with the latest hooks plugin (3.0.0), as well as 2.3.0.

## Steps To Reproduce

1. npx create-react-app namespacerepro --template typescript
2. Add a new file Hooks.tsx

```javascript
import React from 'react';

export function useHook(): string {
  const [state] = React.useState("foo");
  return state;
}
```

3. Update App.tsx as following:
```javascript
import React from 'react';
import logo from './logo.svg';
import './App.css';
import * as Hooks from './Hooks';

function App() {
  const text = otherFunction();
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
          {text}
        </a>
      </header>
    </div>
  );
}

function otherFunction(): string {
  return Hooks.useHook();
}

export default App;
```

## The current behavior
No lint error shown.

## The expected behavior
Lint error is shown only if changing:
1. Hook import to `import * as Hooks from './Hooks';`
2. Hook call to `return useHook();`

**Comment by gaearon** [comment]
Thanks for the report. 

We've changed the heuristic in [`eslint-plugin-react-hooks@4.0.0`](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/CHANGELOG.md#400) to [consider calls like `Hooks.useHook()`](https://github.com/facebook/react/pull/18722) as Hooks, **but** Create React App has not yet updated to this version of the plugin. Concretely, it has updated to it on master, but there was no release of `react-scripts` that would use that version. This is why you're not seeing the error.

cc @iansu — do you have any thoughts on when the next release might be?

**Comment by iansu** [comment]
We are just wrapping up the final issues with Create React App v4 so I'd expect a release next week. We may do an alpha release in the next couple of days.

**Comment by gaearon** [comment]
Awesome, thanks for the update.
