### ISSUE TITLE
Bug: iOS Compiler

### ISSUE THREAD

**Issue by mstepanyan** [facebook/react#18694]
Dear Support Team . 
We have an application(IOS - https://apps.apple.com/us/app/vlume/id1325346984, Android - https://play.google.com/store/apps/details?id=com.vlume.app), which is written in React-Native. We using also an UI Automation Tests (Appium XCUITest). 
Could you please help us to understand why XCUITest has a big delay for each call from Appium side 
1. find element 1-3min per command
2. click element after finding 1-2min per command
The same tests are working on Android 5 times faster

BUG - IOS UI source tree is very big and incorrect 

We use: 
1. Appium - 1.17.0
2. Xcode - 11.3
3. iOS - 13.3.1 , 12.4.4
4. Real devices - iPhone 7, 6s, 5s
5. react-native -  0.61.5
6. io.appium:java_client - 7.0.0(also tried 6.0.0)

**Comment by bvaughn** [comment]
This is not the React Native repo. You'll want to file your issue in that repo:
https://github.com/facebook/react-native

That being said, Appium is not an official React Native product so I'm not sure if they'll be able to help or not.

**Comment by mstepanyan** [comment]
Thank you for your response.
Best regards
