### ISSUE TITLE
Bug: function component cannot have ref property

### ISSUE THREAD

**Issue by vhermecz** [facebook/react#18695]
When passing ref property to a function component, validateFunctionComponentInDev shows a warning about it being a bad thing.

React version: HEAD

While this might have been true for stateless function components (as many places refer to func components), probably since the introduction of hooks, they can have state, and I had the impression that one could rewrite any class component into a function based one.

```
function TestComponent({ref}) {
  const [state] = React.useState({
    stateField1: 42,
  });
  assignRef(ref, state);
  return (
    <div>
      { state.stateField1 }
    </div>
  );
}

This code wont work, caller would never be able to get The Answer. Caller is sad.
```

## The current behavior
React giving a warning and making the ref prop defunct.

## The expected behavior
Remove limitation and let ref on my function component live happily ever after.

**Comment by vkurchatkin** [comment]
You need to use `forwardRef` for this: https://reactjs.org/docs/forwarding-refs.html

**Comment by vhermecz** [comment]
Thx for the link, but that is not a solution I think. I do not have a child
component to forward to. I am the child component.

**Comment by bvaughn** [comment]
@vkurchatkin is right that you need to use `forwardRef`, but that's only part of the solution :smile:

Please check out the documentation for `useImperativeHandle`:
https://reactjs.org/docs/hooks-reference.html#useimperativehandle

**Comment by vkurchatkin** [comment]
Oh, that's right, `forwardRef` is a misnomer, it's just the way to access `ref` property within your component. If you name it differently, say `myRef`, you don't need `forwardRef` and can just use `seImperativeHandle`
