### ISSUE TITLE
Bug: React App with router not opening on ios 13.4.x

### ISSUE THREAD

**Issue by nvnvenki** [facebook/react#18699]
React version: 16.8.4

## Steps To Reproduce

We have app hosted at https://www.perfios.com/argentum/login
We use react router in this app.

Below is the package.json of react and routers

"react": "16.8.4",
"react-dom": "16.8.4",
"react-router-dom": "^4.2.2"

Link to code example:

## The current behavior
Opening this in browser the page just keeps loading forever. This is happening in chrome, safari and also firefox. Works fine in all Android and previous ios versions.

## The expected behavior
Page should load completely.

Below are the screenshot of version details
![image](https://user-images.githubusercontent.com/1863449/79943469-92b45f80-8486-11ea-9612-eb5946322fae.png)

![image](https://user-images.githubusercontent.com/1863449/79943478-9ba53100-8486-11ea-8ce3-2c428a3564e1.png)

**Comment by rohith94** [comment]
facing same issue in currently in  **ios 13.4.1**

**Comment by bvaughn** [comment]
When I took a look myself I saw:
<img width="526" alt="Screen Shot 2020-04-22 at 8 58 22 AM" src="https://user-images.githubusercontent.com/29597/80004654-70671580-8477-11ea-8449-26a6e77361eb.png">

This doesn't seem to me like it's a React issue, to be honest. Could be something with your server?

If you do think it's a React issue- then can you create a repro that does not use react-router? Our team does not maintain react-router, and we don't have bandwidth to investigate problems with it.

**Comment by rachelnabors** [comment]
This issue hasn't been active for awhile. We'd need more information to continue investigation. Probably a React Router issue. Closing!

**Comment by nvnvenki** [comment]
**Update:** 

The problem was one of the css file which was 600kb! in IOS the file was not getting loaded and page was loading forever.

After so much trial and error we found this.

Right now we have removed the unused CSS to bring down to 20kb so its working fine. I'm still surprised about the behavior of loading forever.

Thanks for the support!

**Comment by bvaughn** [comment]
Thanks for leaving an update!
