### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by rhysburnie** [facebook/react#18698]
On android using react-devtools we are seeing 2 instances of the app appear.
On iOS we see 1.
We would like to know if this is a known issue with the devtools or if we are infact seeing 2 instances which is much more concerning but at least we will know that somehow it renders to copies on android.

At the moment we're not sure if what we see is real or not.

Android

![image](https://user-images.githubusercontent.com/245933/79936555-f181d500-8496-11ea-99be-e260658bd75f.png)

iOS

![image](https://user-images.githubusercontent.com/245933/79936573-fa72a680-8496-11ea-917a-181de428c60b.png)

React version:

"react": "^16.13.0",
"react-native": "0.62.0-rc.5"
react-devtools@4.5.0
react-devtools-core@4.5.0

## Steps To Reproduce

1. run react-devtools and metro with android build

**Comment by bvaughn** [comment]
No. This is not a known issue for DevTools.

**Comment by bvaughn** [comment]
What happens if you reload either your RN app or DevTools? Does it always still show two instances?

**Comment by rhysburnie** [comment]
@bvaughn it hapens consistently have tried combos of stopping starting both dev tools and reloading, app, stopping metro and starting again including delete app and run build again

**Comment by bvaughn** [comment]
Does it happen with every app or only with a specific app?

**Comment by rhysburnie** [comment]
Hmmm good point, we only have one app but I will try some sample apps. I wonder if a non complex app would show the same issue or appear fine due to being simple, but will investigate further and report back

**Comment by bvaughn** [comment]
Thanks :)

If it's just your app, my next question will be to see if we can get a repro case

**Comment by rhysburnie** [comment]
Hi,

Im happy for this to be closed, we were getting weird behaviour which wasn't resolved, however given that there was a new version of devtools coming it may not even be an issue.
Last week we also updraded to rn 0.62.x and have started using Flipper where we aren't experiencing those issues

Cheers

**Comment by bvaughn** [comment]
Okay :smile: Thanks for the update. Let me know by commenting here if you start seeing it again and we can look.
