### ISSUE TITLE
Suspense prevents reading valid layout values in `useLayoutEffect`

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/react#18706]
`useLayoutEffect` is commonly used to read layout values (such as `getClientBoundingRect`) to adjust positioning of some elements:

```javascript
const ref = React.useRef();

useLayoutEffect(() => {
  const width = ref.current.getBoundingClientRect().width;
  // do something with width
});
```

This breaks if such a component is rendered within suspended `React.Suspense` boundary:

```js
let shouldSuspend = true;

function A() {
  if (shouldSuspend) {
    shouldSuspend = false;
    throw Promise.resolve(); // if you comment this out, works as expected
  }

  return <div>A</div>;
}

function B() {
  const ref = React.useRef();

  React.useLayoutEffect(() => {
    console.log(ref.current.offsetWidth); // returns 0
  });

  return <div ref={ref}>B</div>;
}

export default function App() {
  return (
    <div className="App">
      <Suspense fallback={<div />}>
        <A />
        <B />
      </Suspense>
    </div>
  );
}

```

React version: 16.13.1

Link to code example:

https://codesandbox.io/s/small-leaf-h31xt?file=/src/App.js:108-189

## The current behavior

Effects run before layout within suspended `Suspense` boundary

## The expected behavior

Effects run after layout within suspended `Suspense` boundary

**Comment by vkurchatkin** [comment]
Documentation clearly states:

> Use this to read layout from the DOM and synchronously re-render.

So I assume this has to be a bug

**Comment by gaearon** [comment]
This is a quirk that we can't fix in the legacy mode without making a huge breaking change.

It is fixed in Concurrent Mode (https://codesandbox.io/s/priceless-field-0y15w?file=/src/index.js), but until that is stable unfortunately we won't have a solution.
