### ISSUE TITLE
Bug: Unable to use resolve Context when component and Provider exist on different levels of NPM module.

### ISSUE THREAD

**Issue by CrashyBang** [facebook/react#18709]
Unable to use resolve `Context` when component and `Provider` exist on different levels of NPM module.

React version: `16.13.1`

## Steps To Reproduce

This is only occurs when a `Provider`  and a component that refer to the same `Context` are imported at different levels of an NPM module.

I have attached an [example](https://codesandbox.io/s/react-codesandbox-fmll8) of the code I am working with, which is working as the `Context` is created locally, however in my own project the two files in the example `settings-context.js` and `withSettings.js` exist at two different levels and are imported like so:

```
import { SettingsProvider } from '@mymodule/app/providers/settings-context.js';
import { withSettings } from '@mymodule/app/hocs/withSettings.js';
```

This results in the following line `const {settings, setSettings} = useContext(SettingsContext)` in `withSettings.js` throwing the below error:
```
Cannot read property 'settings' of undefined
```

Now if I move the `SettingsProvider` and the `withSettings` to the same level like so:
```
import { SettingsProvider } from '@mymodule/app';
import { withSettings } from '@mymodule/app';
```
This does **resolve the issue**, however I would like to be able to use `Context` across varying levels if possible.

I also tried the below code to see if moving the provider top level was enough to resolve the issue, but it seems to be some sort of contexting/closure bug that is beyond me.
```
import { SettingsProvider } from '@mymodule/app';
import { withSettings } from '@mymodule/app/hocs';
```

Link to code example:

- https://codesandbox.io/s/react-codesandbox-fmll8

## The current behavior

Cannot resolve `const {settings, setSettings} = useContext(SettingsContext)` when the provider exists on an alternate level to the component in an NPM module.

## The expected behavior

For the provider to resolve.

**Comment by vkurchatkin** [comment]
This has nothing to do with React. React is unaware of your directory structure.

**Comment by CrashyBang** [comment]
@vkurchatkin you are absolutely right, I have updated the directory structure in the example to reflect that of the module and as expected it still works... I will replicate the issue with an actual NPM module this weekend to provide an example that does throw the error.

**Comment by bvaughn** [comment]
I don't think this is a React bug. My guess is that you're probably importing separate contexts (one per import path). If you can create a small repro, let us know and we can take a look- but from the description of this issue there's not much we can do.

**Comment by CrashyBang** [comment]
Hey @bvaughn,

Alright here is a demo repo showing the error: https://github.com/CrashyBang/context-example

I have also included the code that works locally so you can comment out the imports from the example module and see how it is meant to work here: https://github.com/CrashyBang/context-example/blob/master/src/index.js#L6

I have also created the demo module here: https://github.com/CrashyBang/demo-npm-path

This is being installed via NPM here: https://github.com/CrashyBang/context-example/blob/master/package.json#L7

Let me know if there is anything else that is needed.

**Comment by bvaughn** [comment]
@CrashyBang Can you please setup a Code Sandbox that reproduces this?

**Comment by CrashyBang** [comment]
Hey @bvaughn, unfortunately Codesandbox doesn't seem to want to work with dependencies installed from a Github repo despite `npm` supporting this... I have updated the example to reflect this but as soon as you try to import from the custom module it falls over...

**Comment by bvaughn** [comment]
This looks like a packaging problem to me. I'm pretty confident that it has nothing to do with React :smile:

Looking at your `hocs` source:
```js
import React, {useContext} from 'react'
import { SettingsContext } from '../providers/settingsProvider'

export function withSettings(Component) {
  const Wrapped = props => {
    const {settings, setSettings} = useContext(SettingsContext)

    return (
      <Component {...props} settings={settings} setSettings={setSettings} />
    )
  }

  return Wrapped
}
```

You're trying to import from "../providers/settingsProvider" which makes sense, but looking at the `hocs/dist/hocs.js` file:
```js
var t,
  e = require("react"),
  n = ((t = e) && "object" == typeof t && "default" in t
    ? t.default
    : t
  ).createContext();
exports.withSettings = function (t) {
  return function (s) {
    var i = e.useContext(n);
    return h(
      t,
      Object.assign({}, s, { settings: i.settings, setSettings: i.setSettings })
    );
  };
};
```

This is a little dense but `n` is what's being passed to `useContext` so it should be what holds the settings context. However, `n` is created above as a blank context:
```js
  e = require("react"),
  n = ((t = e) && "object" == typeof t && "default" in t
    ? t.default
    : t
  ).createContext();
```

So it's not being added to the tree anywhere, which is why React is returning `undefined`.

**Comment by CrashyBang** [comment]
Hey @bvaughn that makes sense, would you have any suggestions on how to solve this? The only obvious solution I can see would be to move the provider to it's own NPM module that exports both `SettingsProvider` and `SettingsContext` so that `withSettings` can reference `SettingsContext` and then on the "front end" could reference `SettingsProvider` both from the same module... This should theoretically resolve the issue?
