### ISSUE TITLE
Bug: [eslint-plugin-react-hooks] No missing dependency report for non-inline effect callback

### ISSUE THREAD

**Issue by ford04** [facebook/react#18716]
React version: 16.13.1

eslint-plugin-react: 7.19.0
eslint-plugin-react-hooks: 3.0.0
eslint: 6.8.0

## Steps To Reproduce
```
const Example = () => {
  const [count] = useState(0);

  const increment = () => {
    console.log(count);
  };

  // missing dependencies for inline effect callbacks are reported
  useEffect(() => {
    console.log(count);
  }, []);
  // ~~^ error: React Hook useEffect has a missing dependency: 'count'.

  // not for non-inline callbacks
  useEffect(increment, []);

  return <div>test</div>;
};
```
Link to code example: [Codesandbox](https://codesandbox.io/s/so-61347832-kpw0x)
Motivation: [SO post ](https://stackoverflow.com/questions/61347832/is-passing-a-function-to-useeffect-valid-can-this-be-done-to-replace-usecallbac)

## The current behavior
Missing dependencies for non-inline effect callbacks are *not* reported by linter.

## The expected behavior
Missing dependencies are reported by linter for inline and non-inline functions.

**Comment by rachelnabors** [comment]
Thank your for reporting this! This issue is resolved in the most recent version of `eslint-plugin-react-hooks`. It might take dependent repos like Create React App a little while to update their dependencies as well.
