### ISSUE TITLE
Bug: when i change the second params of `ReactDOM.createPortal`, the dom destroy and then rebuild.

### ISSUE THREAD

**Issue by weird94** [facebook/react#18715]
ReactDOM version: 16.13.1

## Steps To Reproduce

1. open the console tab of sandbox
2. click the picture
3. click the scaled picture again

Link to code example: https://codesandbox.io/s/muddy-smoke-j8lfy

## The current behavior
when i change the second params of `ReactDOM.createPortal`, the dom was destory and then rebuild.

PS. I inject the function` document.createElement` so we can see the dom rebuilds.

when i toggle the active status of picture, the `document.createElement` was called which means the dom destroy and then rebuild.

## The expected behavior
i expect react-dom will reuse the dom nodes, so that the cost of dom destroy and rebuild can be saved. Also, it is a useful way to reuse cross-layer-dom-node

**Comment by bvaughn** [comment]
React does not (currently) support reparenting nodes. If you render "the same thing" (same React elements) but change containers- React will unmount and destroy the first set of elements, then create and mount to the new container. This is the expected behavior.

**Comment by weird94** [comment]
So, why not just reuse the first set of elements instead of unmount it and then create and mount it again? It is costly in the current behavior. And the current behavior also means the react user may not able to reuse the dom among different components by portal. I think it is unreasonable.
