### ISSUE TITLE
Bug: DevTools hihlights false positives

### ISSUE THREAD

**Issue by Mangatt** [facebook/react#18728]
DevTools version: 4.6.0

## Steps To Reproduce

1. Create wrapping component without dom node
2. Create memoized component with multiple nodes
3. Turn on "Highlight updates when components render" in React DevTools
4. Trigger re-render on wrapping component

In profiler is everything recorded correctly, even when there are updates highlighted in page. When is wrapping fragment changed to dom element (e.g. `<div />`), everything works fine.

Link to example: https://5cbq9.codesandbox.io/
Link to code: https://codesandbox.io/s/autumn-wind-5cbq9?file=/src/App.js

## The current behavior
![false-positives](https://user-images.githubusercontent.com/2706990/80251010-26e41980-8675-11ea-8786-d1a1ff183a9f.png)

## The expected behavior
![no-false-positives](https://user-images.githubusercontent.com/2706990/80251024-319eae80-8675-11ea-9a75-490f42afddc0.png)

**Comment by DaniAcu** [comment]
Oh! I created a form and with hooks and wrapped all components with a memo and the same error happened. Apparently nothing is highlight when render, and the DOM is changing. 😕  
Let me add my sample here: 
Code: https://codesandbox.io/s/solitary-sound-8bptv
Demo: https://8bptv.csb.app/

**Comment by alarbada** [comment]
Hello, this still happens on latest react version.
