### ISSUE TITLE
React Hooks will render multiple times after await

### ISSUE THREAD

**Issue by aeroxy** [facebook/react#18725]
```
const [ html, setHTML ] = useState('');
const [ script, setScript ] = useState('');

const update = (script, html) => {
  setScript(script);
  setHTML(html);
};

update('a', 'b');
```

The above code works fine, React Hooks will render ONCE and combine setScript & setHTML;

```
const [ html, setHTML ] = useState('');
const [ script, setScript ] = useState('');

const update = async (script, html) => {
  await new Promise(resolve => setTimeout(resolve, 10));
  setScript(script);
  setHTML(html);
};

update('a', 'b');
```

The above code doesn't work anymore, React Hooks will render TWICE and it doesn't combine setScript & setHTML.

I can change to the code to:

```
const [ state, setState ] = useState({
  html: '',
  script: ''
});

const update = async (script, html) => {
  await new Promise(resolve => setTimeout(resolve, 10));
  setState({
    script,
    html
  });
};

update('a', 'b');
```

The above code only renders ONCE but it has a new bug: the cursor in the textArea (where script and html go) will move to the end of the textArea instead of staying at where it is.

**Comment by vkurchatkin** [comment]
This is inevitable: when you run your code asynchronously, React has no way of knowing that more synchronous setters could be executed after the current one, so it has to trigger render for each. You can either batch by making a single state object, like you did, or use `unstable_batchedUpdates`:

```js
import {unstable_batchedUpdates as batchedUpdates} from 'react-dom';

// ....

const [ html, setHTML ] = useState('');
const [ script, setScript ] = useState('');

const update = async (script, html) => {
  await new Promise(resolve => setTimeout(resolve, 10));
    batchedUpdates(() => {
        setScript(script);
        setHTML(html);
    });
};

update('a', 'b');
```

**Comment by bvaughn** [comment]
This is a question of how/when React batches updates. Updates are batched in certain contexts- like an event handler- but your above example is triggering those updates after a delay, so React doesn't know you want to batch them.

@vkurchatkin is right. Your options are to use the `batchedUpdates` API to tell React, explicitly, that you want it to combine those two updates. Or just use a single state object in the first place, e.g.
```js
const [state, setState] = useState({
  html: "",
  script: "",
});

const update = async (script, html) => {
  await new Promise((resolve) => setTimeout(resolve, 10));
  setState({ html, script });
};

update("a", "b");

```
