### ISSUE TITLE
Image cannot find module

### ISSUE THREAD

**Issue by cnfreitax** [facebook/react#18727]
I'm try import imagem whit 'import logo from '../../assets/logo.svg', but, I get 'cannot find module'. I'm sure the path is correct

**Comment by TrySound** [comment]
Wrong repo https://github.com/facebook/create-react-app

**Comment by cnfreitax** [comment]
thanks

**Comment by rachelnabors** [comment]
Hi! We use the issue tracker for bug reports and feature requests. @TrySound has already directed you to the right repo, so I'll close this :)

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
