### ISSUE TITLE
Bug: Prints only once: [Warning: Can't perform a React state update on an unmounted component.]

### ISSUE THREAD

**Issue by icyJoseph** [facebook/react#18734]
It is known that one should clean up either on effect hooks or life cycles, to prevent calls to `setState` on unmounted components. This report is **not about the reasoning for the warning**.

There's a very helpful warning when this happens, however, **_the warning prints only once_** for a given component. **Is this by design though?**

React version: 16.13.1
I've tried downgrading to 16.10.0 and it still happens.

## Steps To Reproduce

1. `useEffect` to asynchronously set state
2. Do not implement `useEffect` clean up
3. At the parent component implement a flag to show/hide the component
4. Mount the component
5. Unmount the component before step 1 completes
6. Warning is printed
7. Repeat 4, 5. 
8. The warning does not print anymore (but it tries to setState)

Link to code example: https://codesandbox.io/s/wandering-waterfall-6lb21?file=/src/App.js
In the link above, simply click the `hide` button while the `Waiting...` message is up. A warning will be printed, never to return again.

## The current behavior

**_Warning: Can't perform a React state update on an unmounted component._** Prints **_only once_** per component. Even when using the component several times.

Using different components, does print the warning multiple times, but only once per component.

## The expected behavior

**_Warning: Can't perform a React state update on an unmounted component._** should print every time setState is attempted on unmounted components. (I guess?)

**Comment by lizhongzhen11** [comment]
I also meet the problem. Do you have the solution?

**Comment by lizhongzhen11** [comment]
Oh, I found the solution at https://github.com/facebook/react/issues/15006

**Comment by icyJoseph** [comment]
@lizhongzhen11 careful, this issue is **not about the warning, or how to fix it**, but rather, about the warning **only showing once**, even though the error **keeps on happening silently**.

**Comment by icyJoseph** [comment]
Closing because this is done by design.

```javascript
// somewhere in the reconciler
if (didWarnStateUpdateForUnmountedComponent !== null) {
  if (didWarnStateUpdateForUnmountedComponent.has(componentName)) {
    return;
  }
  didWarnStateUpdateForUnmountedComponent.add(componentName);
} else {
  didWarnStateUpdateForUnmountedComponent = new Set([componentName]);
}
```
