### ISSUE TITLE
Bug: React Context API is not working from custom NPM library

### ISSUE THREAD

**Issue by ayayalar** [facebook/react#18731]
I have total of three npm packages:
1) Custom Hook: custom hook wraps useContext
2) Provider: uses custom hook to Provide Context
3) Consumer: uses custom hook to Retrieve Context

If I have these components in a single app, everything works as expected. However, if I separate them to their own npm packages, the state is no longer retrievable by the consumer.

React version: 16.13.1

## Steps To Reproduce
1. Since it involves creating three different npm packages to repro, I've created a github repo that demonstrates the problem. Included all source code along with it.
  a) Repo: https://github.com/ayayalar/ReactContextAPIDefect
2. Kept the example extremely simple to keep the focus on the problem.

Link to code example: https://github.com/ayayalar/ReactContextAPIDefect

## The current behavior
The context state is not retrievable by the consumer.

## The expected behavior
The context state **should be** retrievable by the consumer.

**Comment by vkurchatkin** [comment]
If you can't reproduce it using a single a file, it is a problem with your build configuration, not React

**Comment by ayayalar** [comment]
Yes, I thought that might be a problem. However, the build configuration is quite simple. There is nothing special about it. Can you elaborate how did you come to your conclusion?

**Comment by vkurchatkin** [comment]
React works the same regardless of whether you have a single file or not, whether you use a bundler or not. If you have a problem with context you need to ensure that provider and consumer really use the same Context object. It is most likely that they are not

**Comment by ayayalar** [comment]
I am definitely on the same page. However, when I debug I see the context is only getting created once. That tells me, they must point to the same object.

**Comment by vkurchatkin** [comment]
If there actually is a bug in React, it shouldn't be a problem to make a single file reproduction. After all, that what bundlers do: they build a single JS file. Build your bundle, remove all the webpack cruft, and you'll have it.

**Comment by ayayalar** [comment]
OK, figured it out. It was an issue in webpack configuration. I will share the resolution steps here, so if anyone runs into this kind of a problem, they know what the issue is.

Here is a simple webpack configuration that I am using for both the consumer and the provider.

```
const path = require('path');

module.exports = {
  entry: './src/index.ts',
  output: {
    path: path.resolve(__dirname, './lib'),
    filename: 'index.js',
    library: 'consumer',
    libraryTarget: 'commonjs2',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    modules: [path.resolve(__dirname, './src'), 'node_modules'],
    extensions: ['.tsx', '.ts', '.js'],
    alias: {
      '@ayayalar/context-hook': path.resolve(
        path.join(__dirname, 'node_modules', '@ayayalar/context-hook')
      ),
    },
  },
  mode: 'development',
  devtool: 'source-map',
  externals: {
    react: 'commonjs2 react',
    'react-dom': 'commonjs2 react-dom',
  },
};
```

and the `package.json` snippet

```
  "devDependencies": {
    "@ayayalar/context-hook": "file:../npm/ayayalar-context-hook-1.0.9.tgz",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.9.4",
    "ts-loader": "^6.2.1",
    "typescript": "^3.7.4",
    "webpack": "^4.41.4",
    "webpack-cli": "^3.3.10"
  },
  "peerDependencies": {
    "@ayayalar/context-hook": "^1.0.9",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "dependencies": {},
```

Notice, the @ayayalar/context-hook` as a peer dependency. My assumption here was, this package would not get bundled. 

**That assumption turns out to be wrong.**

To remove it from the final bundle, I needed to add it to the `externals` in my webpack configuration. Which I already have with react and react-dom packages. 

Updating the section of `externals` to the following, removed the hook from the bundle as expected.

```
  externals: {
    react: 'commonjs2 react',
    'react-dom': 'commonjs2 react-dom',
    '@ayayalar/context-hook': 'commonjs2 @ayayalar/context-hook',
  },
```

At this point, in my app, I only have a single instance of the hook npm package. And everything works as expected. @vkurchatkin, thank you for pointing me in the right direction.
