### ISSUE TITLE
Bug: 一个问题，不懂，麻烦解释一下，谢谢

### ISSUE THREAD

**Issue by MARIOMARUI** [facebook/react#18740]
return (
    <div>
      Hello
      {document.title = `You click ${count} times`}
      <button onClick={() => { setCount(count + 1) }}>Add</button>
    </div>
  )
}
为什么这种方式能够修改title  也能在页面中显示You click 0 times 呢

**Comment by MinJieLiu** [comment]
有图让你理解
![image](https://user-images.githubusercontent.com/6167727/80297449-9d883080-87b5-11ea-9f53-8d0b4e62c288.png)

**Comment by tomi-li** [comment]
1. if you have any problems that you don't understand. please ask at the right place like StackOverflow. 
2. ENGLISH Please. do not pollute issues section in Chinese, it's VERY unprofessional.
@MARIOMARUI

**Comment by 7kms** [comment]
it is jsx syntax. expressions will be executed.  so your title changed.

**Comment by NuoHui** [comment]
You should go read more react.js document。
