### ISSUE TITLE
Bug: I am not able to change the css 'height' property dynamically.

### ISSUE THREAD

**Issue by amandhaka** [facebook/react#18744]
I am trying to change the height of elements whenever an event occur. But that's not working with the following code. The code `${newHeight}px` is not working.
```
array.map((value,idx) => (
<div 
className="array-bar"
 key={idx}
style={{height: value,backgroundColor:'turquoise'}}></div>
 ))
const[barOne,newHeight]=animations[i];
const barOneStyle=arrayBars[barOne].style;
 barOneStyle.height='${newHeight}px';
```

arrayBars here stores the array of elements referenced by 'array-bar'.

**Comment by sreetamdas** [comment]
@amandhaka if you're attempting to use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) when you're doing `barOneStyle.height='${newHeight}px'`, you need to use the ``` (backtick) character; you're trying to use a `'` (single quote) character at the moment.
