### ISSUE TITLE
useEffect with Suspense transitions

### ISSUE THREAD

**Issue by subhero24** [facebook/react#18741]
I have a question regarding the expected behaviour of effects in combination with transitions.
When a state transition is wrapped with a useTransition and, before the transition completes, there is some user interaction causing a new state transition (which sets the same state to another value). React executes the effect of both renders, even though the first render did not ever render to screen, because its transition was interrupted by the second transition.

Is this a bug? or is this expected behaviour to have effects of both renders executed?

**Comment by rachelnabors** [comment]
Hi hi! Could you provide and example using https://codesandbox.io/ ? It will help us understand your question more! Thanks!

**Comment by subhero24** [comment]
@rachelnabors I made an example at [codesandbox](https://codesandbox.io/s/keen-ride-dxnvy?file=/src/App.js)

While making the example, I realised the problem is not really about useEffect, but more about invalidating previous transitions. I hope the comments in de codesandbox are clear enough. Thanks!

**Comment by subhero24** [comment]
I see this has been fixed in the latest experimental! Thanks!
