### ISSUE TITLE
Feature request: a function for conditional rendering 

### ISSUE THREAD

**Issue by finom** [facebook/react#18743]
Sorry, I didn't find any issue template for feature requests, but I hope it's fine.

The problem I'm trying to solve is to nicely develop components which usually require usage of ternary expressions.

```js
{ifSomething ? (
  <A prop="foo">children</A>
) : null}
```

It looks not nice and I have to use a third-party solution to achieve that. For example https://github.com/khmelevskii/babel-plugin-jsx-base-component which allows to turn the code above into:

```js
<Base component={A} exists={ifSomething}>children</Base>
```
But in my opinion usage of third-party solutions isn't an elegant way to solve super common pattern in React.

My proposal is to add a super simple function which conditionally renders components and replaces ternary operator in most cases.

```js
import React, { conditional } from 'react';
...
<div>
  {conditional(ifSomething, (
    <A prop="foo">children</A>
  )}
</div>
```
An optional 3rd argument would say what is going to be rendered if a condition is nullish. Obviously, I can implement such function by myself, but it's not any better than a third-party solution. A benefit of having such function in React is that we always use `import React, { something } from 'react'`, so adding `conditional` (or whatever you want to call it) doesn't require any additional imports (I also thought about to call it `ternary` which is what it's going to actually do).

**Comment by phillx** [comment]
@finom As a developer, I would prefer to use : 
```jsx
...
<div>
   { ifSomething && <MyComponent prop="foo" /> }
</div>
...
```
Why? 
- I see this as the introduction of unnecessary abstraction used for the cases which are easy to solve with native support of the JS/JSX.
- If you feel like your code is unreadable or hard to maintain, make sure you utilize tools like `prettier` and `eslint`
- If you have huge conditional blocks rendered, consider refactoring - there is a nice section in ReactJS Docs called [Conditional Rendering](https://reactjs.org/docs/conditional-rendering.html)

**Comment by finom** [comment]
@philix I think that ternary expressions and && operators look inappropriately ugly in JSX. Good code isn't only made of smooth architectural decisions bit also of nice-looking code.

**Comment by javascripter** [comment]
The suggested function won't work. Consider the following:
```javascript
const a = null

<div>
  {a && <div>{a.value}</div>}
</div>
```
is fine because  `a.value` will not be evaluated unless `a` evaluates to `true`. However,
```javascript
<div>
  {conditional(a, (
    <div>{a.value}</div>
  )}
</div>
```
will fail because a is null and a.value is evaluated regardless of whether condition is met. 

Even if it's implemented as a babel macro/plugin, it breaks the expectation that arguments in function calls are always evaluated before they're called, so that's not ideal either.

**Comment by finom** [comment]
@javascripter that's a very good point!
