### ISSUE TITLE
Jest: Cannot assign to read only property '...' of object '...'

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#18758]
Right now in the React repo this test...
```js
fit('blah', () => {
  expect(document.createElement('div')).toBe(document.createElement('div'));
});
```
...fails with the following meaningless error message:
> TypeError: Cannot assign to read only property 'Symbol(impl)' of object '[object DOMImplementation]'

<img width="628" alt="Screen Shot 2020-04-27 at 2 04 19 PM" src="https://user-images.githubusercontent.com/29597/80420721-12c83400-8890-11ea-919f-e1b10b6fc561.png">

Apparently @trueadm mentions that this broke sometime recently because of a change we made. (I don't have details.) Its a pretty confusing behavior though.

**Comment by mycarrysun** [comment]
I'm having this as well. For me it is happening at this line:
```
expect(getByLabelText('YYYY')).toBe(document.activeElement);
```

**Comment by jcestibariz** [comment]
Same here, for me in:

```js
expect(fn.mock.calls).toEqual([[element]]);
```

**Comment by greypants** [comment]
Same issue - thanks @jcestibariz, you were right. This error only seems to happen when the objects are different (as they are in the original issue description - those are two distinct objects being created). My example was also looking for `document.acitveElement`, and it turned out to be a timing/async issue. Wrapping it in a `waitFor` addressed the issue:

```jsx
await waitFor(() => {
  expect(getByText("trigger")).toBe(document.activeElement);
});
```

**Comment by pahan35** [comment]
It happens when calling `replaceMatchedToAsymmetricMatcher()` inside `printDiffOrStringify()`

https://github.com/facebook/jest/blob/master/packages/jest-matcher-utils/src/index.ts#L359

@SimenB any ideas?

**Comment by pahan35** [comment]
Some info about comparable params
<img width="1134" alt="Screenshot 2020-05-30 at 03 51 18" src="https://user-images.githubusercontent.com/13823215/83315466-d427ef80-a228-11ea-904c-b4f471cf095f.png">

**Comment by vickOnRails** [comment]
I spent a huge amount of time around this today.

I solved mine by ensuring the nodes being compared were actually the same. This doesn't yet make sense to me, but hopefully, it helps someone...

Here's my test code

```jsx
test("Unneeded properties aren't passed into DOM", () => {
    const { getByTestId } = render(
      <div className="container" data-testid="button-container">
        // Notice the data-testid attribute here
        <button type="submit" className="css-fxq2iz" data-testid="button">
          Click Me
        </button>
        // but not here
        <Button variant="primary" variantStyle="outline" block size="medium">
          Click Me
        </Button>
      </div>
    );

    const buttonsContainer = getByTestId("button-container");
    const vanillaButton = buttonsContainer.querySelectorAll("button")[0];
    const renderedButton = buttonsContainer.querySelectorAll("button")[1];

    expect(vanillaButton).toEqual(renderedButton);
  });
```

Here's the error I get

![Screenshot (30)](https://user-images.githubusercontent.com/24235881/85204938-d6eda000-b30f-11ea-9003-5b0058e76be3.png)

It goes away when I add the same attributes to the `Button` element

```jsx
<Button variant="primary" variantStyle="outline" block size="medium" data-testid="button">
    Click Me
</Button>
```

![Screenshot (32)](https://user-images.githubusercontent.com/24235881/85205096-defa0f80-b310-11ea-8083-2d735de8d942.png)

It took me some time to realize that this wasn't really a bug, but the test just failed. I didn't understand the error message and after hours of googling, I got more confused than I was. 

Like @greypants said, it would be great to have a nicer error message.

**Comment by bvaughn** [comment]
To be clear, this issue is specifically about improving the error message :smile: because the current one is unhelpful and confusing.

**Comment by pahan35** [comment]
We see a current message because `replaceMatchedToAsymmetricMatcher` fails on preparing the diff.

IMHO it's not about improving the error message, it's about fixing `replaceMatchedToAsymmetricMatcher` to print the diff for DOM elements without failures.

**Comment by chrisbobbe** [comment]
@pahan35 [said](https://github.com/facebook/react/issues/18758#issuecomment-636249433):
> It happens when calling `replaceMatchedToAsymmetricMatcher()` inside `printDiffOrStringify()`
> 
> https://github.com/facebook/jest/blob/master/packages/jest-matcher-utils/src/index.ts#L359
> 
> @SimenB any ideas?

Hmm, interesting! It looks like this issue belongs in the Jest repository, then?

FWIW, I'm seeing `TypeError: Cannot assign to read only property 'Symbol(context)' of object '[object URL]'`.

**Comment by gaearon** [comment]
I think there’s a misunderstanding.

**We are users of Jest just like you; this is not the canonical issue where you can expect that adding comments would help solve it. You need to go and file it in the Jest repo instead. This is a React repo, not Jest repo.**

I am locking down.
