### ISSUE TITLE
Error: "Commit tree does not contain fiber 3204. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by Jucian0** [facebook/react#18754]
When I try to navigate in commits React Dev Tools Profiler I get this error:
"Commit tree does not contain fiber 8562."
![Screen Shot 2020-04-27 at 12 00 23](https://user-images.githubusercontent.com/8399579/80387189-bad50180-887e-11ea-860a-3821b2d9603c.png)

DevTools version: 4.6.0-6cceaeb67

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by bvaughn** [comment]
Can you reproduce this behavior?

If so, can you please share the repro steps with us?

**Comment by bvaughn** [comment]
Closing due to lack of a response. Maybe we'll get repro information from the duplicate #18831
