### ISSUE TITLE
Bug: onMouseLeave does not trigger on disabled button

### ISSUE THREAD

**Issue by raunofreiberg** [facebook/react#18753]
Derived from https://github.com/facebook/react/issues/4251#issuecomment-591644826

<hr />

React version: 16.13.1

## Steps To Reproduce

1. Hover over the disabled button
2. See tooltip appear
3. Hover away from the disabled button
4. Tooltip does not disappear

Link to code example: https://codesandbox.io/s/gracious-galileo-qymqw?file=/src/App.js

## The current behavior

`onMouseLeave` is not triggered on disabled button

## The expected behavior

`onMouseLeave` should be triggered on disabled button

<hr />

I don't think #17675 actually made `onMouseEnter` not fire on disabled buttons, since in the example that I've given, it is firing and using the latest React version (the PR has been shipped in 16.13.0)

**Comment by facufrast** [comment]
If you put the button inside a div, event works fine! But I don't know the reason:

```
      <div onMouseEnter={show} onMouseLeave={hide} style={{ border: "1px solid red"}} >
        <button disabled>
          Hover me!
        </button>
      </div>
```

**Comment by 7kms** [comment]
has been resolved by `onPointerEnter` and `onPointerLeave`?

**Comment by shanudjn** [comment]
Hi everyone! I am new to open source .If this issue isn't closed, I would like to work on this?

**Comment by raunofreiberg** [comment]
Pointer Events seem to resolve this issue, so I'll be using those going forward. This issue is more related to how browsers handle mouse events, so I'll be closing this.

**Comment by doureyd** [comment]
FYI Using `onPointerEnter` and `onPointerLeave` fix the issue but [it's not supported by all browsers yet](https://caniuse.com/#search=onpointerleave).
