### ISSUE TITLE
How re-trigger a dialog model that opened on a clicked event?

### ISSUE THREAD

**Issue by mohit-llp** [facebook/react#18751]
![image](https://user-images.githubusercontent.com/44094302/80347917-9d0d9980-888a-11ea-8c98-9b92fd72805e.png)

**Comment by leminhson2398** [comment]
Hey!
I don't understand your issue, could you please describe it more details ?
Since asking question here may be slow to get response, you should ask as clearly as possible.
Thank you!

**Comment by mohit-llp** [comment]
I Fixed it.
thanks
