### ISSUE TITLE
 Bug: npm run build error 

### ISSUE THREAD

**Issue by meghanar121** [facebook/react#18764]
**i am not able run build command, it shows compileerror in css selector undefined**

  
PS C:\Users\megha\OneDrive\Desktop\Weather\weatherapp> npm run build

> weatherapp@0.1.0 build C:\Users\megha\OneDrive\Desktop\Weather\weatherapp
> react-scripts build

Creating an optimized production build...
Failed to compile.

Cannot read property 'length' of undefined
CompileError: Begins at CSS selector undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weatherapp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weatherapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\megha\AppData\Roaming\npm-cache\_logs\2020-04-28T09_35_02_482Z-debug.log
PS C:\Users\megha\OneDrive\Desktop\Weather\weatherapp>

**_here is the css file :_**

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'montseratt',sans-serif;
}

.app {
  background-image: url('./images/cloudy.jpeg');
  background-size: cover;
}

 .app .warm{
   background-image: url('./images/sunny1.jpeg');
 }

main{
  min-height: 100vh;
  background-image: linear-gradient(to botttom,rgba(0,0,0,0.2),rgba(0,0,0,0.75));
  padding: 25px;
}

.search-box{
  width: 100%;
  margin: 0 0 75px;
}

.search-box .search-bar{
  display: block;
  width: 100%;
  padding: 15px;

  background-color: rgba(255,255,255,0.5);
  border-radius: 0px 16px;
  margin-top: -25px;

  box-shadow: 0 5px rgba(0,0,0,0.2);

  color: #313131;
  font-size: 20px;
}

.search-box .search-bar:focus{
  background-color: rgba(255,255,255,0.75);
}

.location-box .location{
  color: #fff;
  font-size: 32px;
  font-weight: 500;
  text-align: center;
  text-shadow: 3px 3px rgba(50,50,70,0.5);
}

.location-box .date{
  color: #fff;
  font-size: 20px;
  font-weight: 300;
  font-style: italic;
  text-align: center;
  text-shadow: 2px 2px rgba(50,50,70,0.5);
}

.weather-box{
  text-align: center;
}

.weather-box .temp{
  position: relative;
  display: inline-block;
  margin: 30px auto;
  background-color: rgba(255,255,255,0.2);
  border-radius: 16px;
  padding: 15px 25px;
  color: #fff;
  font-size: 102px;
  font-weight: 900;
  text-align: center;
  text-shadow: 3px 6px rgba(50,50,70,0.5);
  box-shadow: 3px 6px rgba(0,0,0,0.2);
}

.weather-box .weather{
  color: #fff;
  font-size: 48px;
  font-weight: 700;
  text-shadow: 3px 3px rgba(50,50,70,0.5);
}

**Comment by bvaughn** [comment]
Please report this bug in the Create React App repo:
https://github.com/facebook/create-react-app

This is the React repo. Different teams maintain each of these projects.

You'll probably also need to include more information than what you listed above in order for someone to be able to help you though. That doesn't look like enough info for anyone to reproduce the error. :smile:
