### ISSUE TITLE
Bug: rules-of-hooks should support hooks inside top-level IIFEs

### ISSUE THREAD

**Issue by fabiospampinato** [facebook/react#18769]
React version: **v16.13.1**
eslint-plugin-react-hooks version: **v3.0.0**

## Steps To Reproduce

1. Write something like this:

```js
const Component = () => {
  (() => {
    useState ();
  })()
};
```

2. Run the `rules-of-hooks` linter rules on it.

## The current behavior

Those linter rules will complain that the `useState` hook is being called inside a callback.

## The expected behavior

Those linter rules should be a little smarter and ignore this kind of top-level IIFE "callback", since if I'm understanding things correctly it's completely safe to call hooks this way.

This is a bit of an edge case, but I'm wrapping some hook calls in an IIFE because I don't want to be able to access the values they return directly, as they may not be the most up to date, rather than via the accessor my IIFE returns.

**Comment by vkurchatkin** [comment]
This pattern seems rather pointless. Why would you do that?

**Comment by fabiospampinato** [comment]
@vkramskikh Correctness-wise I don't think it matters why I do it, and I'd argue one should strive for correctness.

In my specific case I did that because I was wrapping all props and state in refs to be passed to an object that could mutate them, that object could also mutate the value returned by `useState`, in order not to have the component render the previous thing rather than the new one, but the reference immediately returned by `useState` and the one set in the ref are different, as you always want to use the updated version rather than the old version even keeping a reference to the old value is error prone, so I was wrapping everything in an IIFE. Maybe this is a bit of a stupid use case, maybe I would be better off doing things in other ways (like just using refs to begin with, for this particular component), whatever the case I stumbled on this issue and I wanted to report it.

**Comment by vkurchatkin** [comment]
Linter rules are based on conventions. It is not possible to support every possible case, so only patterns that are popular are supported.

> if I'm understanding things correctly it's completely safe to call hooks this way

It is safe indeed. So is calling a custom hook not `use`-something, or calling hooks in a loop, if it always has the same number of iterations. None of this is supported.

**Comment by fabiospampinato** [comment]
> It is not possible to support every possible case

Sure, I'm not asking to get every possible use case supported though.

> It is safe indeed. So is calling a custom hook not use-something, or calling hooks in a loop, if it always has the same number of iterations. None of this is supported.

Those cases you mention aren't statically analyzable usually, I don't have much experience manipulating the AST but detecting a wrapper IIFE like in my example code above would probably be easy. Whether it's worth adding to the rules or not it's not for me to decide, I would appreciate though if the rules were a bit more correct.

**Comment by albseb511** [comment]
https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

Information is provided here.

**Comment by rachelnabors** [comment]
Closing because it _is_ the `rules-of-hooks` linter, and as pointed out above, [the Rules of Hooks clearly state "Don’t call Hooks inside loops, conditions, or nested functions."](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level)

**Comment by fabiospampinato** [comment]
> Closing because it is the rules-of-hooks linter, and as pointed out above, the Rules of Hooks clearly state "Don’t call Hooks inside loops, conditions, or nested functions."

@rachelnabors That's right, but arguably those rules are a bit simplistic if doing something that goes against them is always completely harmless.

**Comment by gaearon** [comment]
This particular case is a rather exotic pattern and in my opinion isn't worth adding complexity to the (already complex) rule implementation.

As an alternative with similar scoping "benefits", you can use a block.

```js
const Component = () => {
  let stuff;
  {
    useState();
    stuff = ...
  }
};
```

**Comment by iambryanhaney** [comment]
@fabiospampinato You can sidestep the rule by naming your IIFE and adhering to the naming rules; i.e., prefixing with `use` or using PascalCase.

```
const a = (function useThisWorks() {
   return useState(true);
})();

const b = (function ThisAlsoWorks() {
   return useState('a string');
})();
```

You can also use an object with keys adhering to the rules:

```
const hooks = {
  useThisWorks: () => useState(true),
  ThisAlsoWorks: () => useState('a string'),
}

const c = hooks.useThisWorks();
const d = hooks.ThisAlsoWorks();
```

**Comment by wereHamster** [comment]
It's really unfortunate that this isn't supported. Sometimes it's not worth it offloading a bit of self-contained logic into a standalone function and naming it. Unfortunately the [«do expression» proposal](https://github.com/tc39/proposal-do-expressions) (which would make this kind of blocks-of-self-contained-logic easily accessible in the language) is not gaining any traction.

And so I'm left with ugly constructs like this:

```javascript
  const categoryId = (function useSTFU() {
    const [res] = GQL.useCategoriesQuery()
    const options = res.data?.categories ?? []
    return options.find((x) => x.name === nameToCategory(name))?.id
  })() 
```

**Comment by iambryanhaney** [comment]
@wereHamster The above example could compose decently with expression chaining...

```JSX
const categoryId = (GQL.useCategoriesQuery()[0].data?.categories ?? [])
   .find((x) => x.name === nameToCategory(name))?.id
```

If you need more complexity in a self-contained block, you could mimic the `do` expression proposal with your named IIFE...

```JSX
const categoryId = (function Do() {
  const [res] = GQL.useCategoriesQuery()
  const options = res.data?.categories ?? []
  return options.find((x) => x.name === nameToCategory(name))?.id
})() 
```

I don't feel like that's any clunkier than an anonymous IIFE; it's arguably more self-descriptive.

**Comment by dcporter** [comment]
@gaearon my use case is getting a callback from a hook, then wrapping it (to handle `undefined` in this case) and returning the returned value. Using this to avoid having to name the transient variable in the root closure (which always results in dumb confusing naming). This is a really nice pattern and I was disappointed that the rule of hooks were fighting me on it. Ended up naming the IIFE function `useIIFE`, which is fine, but silly.

> Closing because it is the rules-of-hooks linter, and as pointed out above, the Rules of Hooks clearly state "Don’t call Hooks inside loops, conditions, or nested functions."

@nearestnabors this just misunderstands how IIFEs work differently than other nested functions, and fit perfectly with the intent of the rule of hook: only call hooks from code that runs the same way through every time.
