### ISSUE TITLE
Bug: `React.lazy` throws undefined instead of an `Error` object

### ISSUE THREAD

**Issue by mischnic** [facebook/react#18768]
React version: 16.13.1

## Steps To Reproduce

```js
import React, { Suspense, lazy } from "react";

const Async = lazy(() => {}); // <------

let App = () => {
	return (
		<Suspense fallback={"Loading"}>
			<Async />
		</Suspense>
	);
};

export default App;
```

Link to code example: https://codesandbox.io/s/elegant-fermi-bxwtb

Might be related to https://github.com/facebook/react/issues/15019, https://github.com/facebook/react/pull/15222

## Context

I know that this is incorrect code, but `lazy(() => {import(...)})` is a rather easy typo to make.
The main reason why I'm bringing this is up is that other tools (like JSDOM and Codesandbox with the link above) expect an `Error` object to be thrown. 

## The current behavior

**Input**: `const Async = lazy(async () => ({}));`
**Error**: (this is correct)
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: [object Object]

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

**Input**: `const Async = lazy(() => ({}));`
**Error**: (the exception is not an `Error` object)
```
Uncaught {}
```

**Input**: `const Async = lazy(() => {});`
**Error**:  (the exception is not an `Error` object)
```
Uncaught undefined
```

## The expected behavior

**Input**: `const Async = lazy(async () => ({}));`
**Error**:
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: [object Object]

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

**Input**: `const Async = lazy(() => ({}));`
**Error**:
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: undefined

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

**Input**: `const Async = lazy(() => {});`
**Error**:
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: [object Object]

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

**Comment by sebmarkbage** [comment]
I did some refactoring for lazy in master. Looking at one of the more recent builds, this looks like it's fixed: https://codesandbox.io/s/infallible-shaw-o3iv4?file=/src/App.js

**Comment by b4h0-c4t** [comment]
I'll take on this.

**Comment by b4h0-c4t** [comment]
I sent a pull request.
Look at [#18928](https://github.com/facebook/react/pull/18928).
