### ISSUE TITLE
React hydrate mismatch with Suspense component

### ISSUE THREAD

**Issue by liximomo** [facebook/react#18767]
It appears you will have a mismatch warning when hydrating in conjunction with a client-side `<Suspense>` component which has a fallback element.

![image](https://user-images.githubusercontent.com/9816225/80495490-90786680-899a-11ea-8070-479435e91f2a.png)

CodeSandbox: https://codesandbox.io/s/zealous-burnell-i79nm?file=/src/index.js

React Version:
react@16.13.1
react-dom@16.13.1

**Comment by eps1lon** [comment]
I guess hydrate() should warn if it encounters features that aren't supported for server-side rendering. 

If you pass the same component to `renderToString` react-dom will throw `ReactDOMServer does not yet support Suspense.`. The docs for `hydrate()` specifically mention that it can only hydrate containers

> whose HTML contents were rendered by ReactDOMServer. 

not just arbitrary HTML even if the resulting markup is the same.

**Comment by gaearon** [comment]
Going to close this — it is not supported to render different trees on the server and on the client.
