### ISSUE TITLE
Bug: Stop browser hanging on Maximum update depth exceeded 

### ISSUE THREAD

**Issue by laclance** [facebook/react#18777]
React version: 16.13.1
OS: Windows 10
Browser: Google chrome 81.0.4044.122

Whenever I incorrectly use useEffect hook and get the Maximum update depth exceeded error the chrome tab hangs and I have to force close using task manager and reopen chrome again in order to close the tab. This makes debugging the cause very time consuming and annoying, is there a way to avoid this? like for example stop rendering after 100 renders.

**Comment by laclance** [comment]
yes it is still affecting me.

**Comment by laclance** [comment]
bump

**Comment by bvaughn** [comment]
> Whenever I incorrectly use useEffect hook and get the Maximum update depth exceeded error the chrome tab hangs and I have to force close using task manager and reopen chrome again in order to close the tab.

Can you share a repro (code) for this?

Here's my attempt: https://vfb6w.csb.app/

```js
import React, { useEffect, useState } from "react";
import "./styles.css";

export default function App() {
  const [count, setCount] = useState(0);
  useEffect(() => {
    setCount(count + 1);
  });
  return <div className="App">{count}</div>;
}
```

It does not crash the tab, and it prints a warning:
```
index.js:27 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at App (https://vfb6w.csb.app/src/App.js:24:39)
```
