### ISSUE TITLE
Saving an unrendered functional component to state throws "Error: Should have a queue" or "Rendered more hooks than during the previous render."

### ISSUE THREAD

**Issue by rexthefex** [facebook/react#18780]
React version: 16.13.1

## Steps To Reproduce

1. Create a component with hooks. Let's call it `Component` for brevity.
2. Save it to the state on the main functional component without creating it: `setState(Component)`.
Note that it is not `setState(<Component />)`
3. App crashes with either "Error: Should have a queue." or "Rendered more hooks than during the previous render.", depending on the type of hooks 

Link to code example:
https://codesandbox.io/s/polished-sound-wpc8y

## The current behavior
App crashes when adding an unrendered component to state. Rendering the component and then adding it to state works fine.

## The expected behavior
Both ways to be accepted as valid.

**Comment by gaearon** [comment]
If you put a function into state, you need to add `() =>` both in `useState` and `setState` calls because otherwise React thinks you're using a lazy state initializer. This is an unfortunate consequence of function overloading.

Your code example is empty but I assume you need something like

```js
const [Component, setComponent] = useState(() => InitialComponent)

// ...
setState(() => NextComponent)
```
