### ISSUE TITLE
React developers tools extension icon

### ISSUE THREAD

**Issue by ackvf** [facebook/react#18788]
Can you change the boxed logo for a transparent icon? It would look better in the Extension bar

left React Developer Tools, right react-detector
![image](https://user-images.githubusercontent.com/2313018/80702975-34205e80-8ae2-11ea-87e5-5308b54e5bb6.png)

**Comment by bvaughn** [comment]
The icon's contrast is important. Light blue on dark gray looks good, so your screenshot looks good. But if the operating system (or browser) weren't in dark mode, it would be light blue on light gray, which would not look good.

This icon needs to look good across Chrome+Firefox+Edge on Windows and Mac, with both light and dark modes enabled. So I think keeping the background color as part of the icon is the safest move.

Thanks for the suggestion though! :)

**Comment by ackvf** [comment]
@bvaughn Thank you for your explanation, it makes sense. Too bad there can't be an icon for each platform and light/dark theme.
