### ISSUE TITLE
Bug: render multiple portals to same element additive behavior

### ISSUE THREAD

**Issue by idoros** [facebook/react#18791]
For every use of `ReactDOM.createPortal()` in a unique VDOM position the content is rendered adding to the portal element without clearing it.

React version: 16.12.0

## Steps To Reproduce

1. create a dom element to render a portal into
2. use `ReactDOM.createPortal` more then once from different positions (or component instances) to render to the same element
3. result: each instance adds its content without clearing the element

[Link to code example](https://codesandbox.io/s/sleepy-knuth-jyqzi?file=/src/App.js)

## The current behavior

`ReactDOM.createPortal` appends to the provided element without clearing it.

## The expected behavior

I would expect the `ReactDOM.createPortal` to be similar to `ReactDOM.render` and maybe even provide some warning or error if React is already using the element as a portal target. Or the documentation to indicate this behavior more clearly if this is by design.

**Comment by aqrln** [comment]
Found this issue accidentally while googling if something like what I did in [this fork of your codesandbox](https://codesandbox.io/s/xenodochial-bush-35bo7?file=/src/App.js) would work, since I kind of need this behavior, because, uh, reasons (long story short, SVG doesn't have `z-index`) 😄. It would be cool if someone from the React team could confirm whether this is a bug or a feature, so I could know whether I can rely on this.

**Comment by cameron-martin** [comment]
I would also be interested to know whether this is defined behaviour. I couldn't find any test cases for it, so presumably not.

**Comment by ogheneovo12** [comment]
The fact that I just randomly thought about this  and found out it exists 😅😅.
I would think it’s a feature, rather than a bug.  You could sort out the edge case based on your application need.

**Comment by bdsqqq** [comment]
wait 
this is a bug??

**Comment by distinctdan** [comment]
It's pretty handy to be able to output multiple elements to the same container for modals and tooltips. Like if you wanted a modal to be appended to the body for positioning, you wouldn't want to clear the whole body.
