### ISSUE TITLE
Bug: Fetch API not working correctly when using ReadableStream

### ISSUE THREAD

**Issue by DonHaul** [facebook/react#18795]
While building a react app, where the front-end must constantly receive streaming data, I noticed that each stream chunk, is only technically received, after the whole stream data is transmitted, although I can chrome network tab that is being received in several chunks. This issue occurs during development, but after building the app for production it no longer occurs.

React version: 16.13.1

## Steps To Reproduce
1. Create a component that receives a stream of data (for this test a [flask stream](https://flask.palletsprojects.com/en/1.1.x/patterns/streaming/) was used although the bug occurs with other sources  )

Code example:
```
import React, { useEffect } from 'react';

function Page_api() {

    useEffect(() => {

        const url = '/api/stream'

        const consume = responseReader => {
            return responseReader.read().then(result => {
                if (result.done) { return; }

                // do something with the current chunk
                const chunk = result.value;
                console.log("Received Chunk");

                return consume(responseReader);
            });
        }
  
        fetch(url).then(response => {
            return consume(response.body.getReader());
        })
            .catch(console.log.bind(console));

    })
    return (
        <div>
            <p>API Testing Page</p></div>)
}


export default Page_api
```
Same code in codesandbox: https://codesandbox.io/s/5vtqo , a stream source is also provided as a flask server on the api.py file.

## The current behavior
Upon Receiving stream, react can only process each chunk of it on the end of the stream while on development (i.e. using react-scripts start)

![dev](https://user-images.githubusercontent.com/13081142/80768627-cfe1b700-8b42-11ea-8984-c3541bbaa1b7.gif)

## The expected behavior
Upon Receiving stream, react can process each chunk as soon as it arrives (i.e. using react-scripts start) - just as it occurs in the built application

![working](https://user-images.githubusercontent.com/13081142/80768756-27802280-8b43-11ea-8c5e-317c96b5df22.gif)

**Comment by vkurchatkin** [comment]
This has nothing to do with React

**Comment by DonHaul** [comment]
@vkurchatkin Why do you say that?

**Comment by gaearon** [comment]
Can you help me figure out why you think React is related to this problem? Have you tried removing React from the equation?

**Comment by vkurchatkin** [comment]
The problematic code is within `useEffect`. React just runs it and doesn't affect in any other way. You don't even call any React-related code (such as `setState`) from there. Then again, React doesn't have any network-related code at all.

If you post this question to Stackoverflow, you'd surely get the help you need.

**Comment by DonHaul** [comment]
After some further testings, it seems it is related to the fact that the client and the flask servers where on the same host, and not related to react at all, thank you all
