### ISSUE TITLE
Support !important for styles?

### ISSUE THREAD

**Issue by syranide** [facebook/react#1881]
We currently don't support `!important` as it has to be set using `style.setProperty(name, value, priority)`. This should be trivially easy to implement if it's something want to support, although I'm not sure about the performance implications (**EDIT:** #1886), although I can't imagine it would be measurable as we would be doing the string test ourselves and those are cheap.

http://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSStyleDeclaration

~~OK... apparently IE8 doesn't support this _at all_, it might still be worth implementing, for the future and for those who don't care about IE8.~~ ~~After further experimentation, apparently it is! `style.setAttribute(name, value)` (priority is part of the value).~~ But apparently that was wrong as well, the only way to set it seems to be with `cssText`, an acceptable work-around may be to just use `cssText` when we detect an `!important` style, which should be seldom enough that performance is a non-issue.

An important consideration is that we _already_ support this for the initial render, but subsequent updates will _fail_ as `!important` isn't recognized for properties.

**Comment by ccnokes** [comment]
+1 to Nelix's comment. For example, in Bootstrap CSS there are a number of utility classes that all use !important (hidden, pull-right, etc) that I wouldn't be able to override without !important inline styles. (I totally agree that !important is abused--and probably Bootstrap too, for that matter--but I think React should still be able to work with them.)

**Comment by thomassuckow** [comment]
We use !important to set a dynamic background color on an element and have it still show up when printing. Without !important the background is not printed.

**Comment by yaycmyk** [comment]
IMO, it should be supported. It's not React's place to be dogmatic about how people author their styles.

**Comment by zpao** [comment]
I had a longer post here and then lost it, oh well…

The summary is that it would be expensive to check every value for `!important`, so supporting this isn't awesome. Even if we do get a good option, it's unlikely we'd do this while we support IE8 because I don't want to go down that cssText path. This isn't really at all about dogma, I would say that it's more about perf. And the fact that we're faced with a number of limitations when working with styles in CSS.

What we could perhaps do is change the data structure for style.

```js
style = {
  color: 'red',
  backgroundColor: {
    value: 'blue',
    important: 'true'
  }
}
```

It would be backwards compatible (if the value isn't an object, we do the exact same thing). And it would allow us to start using the `setProperty` API with `important`. Downside is obviously more objects. But we don't have to do any string parsing.

**Comment by yaycmyk** [comment]
@zpao That seems reasonable. Perf is obviously a very important factor to consider and I appreciate the creative thinking... your solution would at least allow a developer to support the need, even if it's a little more effort.

**Comment by Charca** [comment]
I'm facing the same issue as @nelix. It is quite an edge case, but it would be nice to have support for this.

**Comment by nelix** [comment]
@zpao that api suites me fine, I will be really happy to rip out dynamically generated css + manual style manipulation I have from my chrome extension's IFrame armor.

**Comment by mwschall** [comment]
I ran into this today, trying to dynamically set the background color of a Semantic UI [Icon](http://semantic-ui.com/elements/icon.html). They have those colors set as `!important`, presumably for legitimate reasons. Fortunately I could work around it like @thomassuckow [did](https://github.com/facebook/react/issues/1881#issuecomment-127664203). Would be nice to avoid the extra step though.

**Comment by 6ewis** [comment]
what's the status on this?

**Comment by zpao** [comment]
No change. As we invest more in JS styles I think we'll end up with some changes to how styles work. In the mean time I don't think we'll make any changes without a fuller picture of how that will play out.

**Comment by japgolly** [comment]
This makes it pretty hard for React to play nice with Semantic UI (which frustratingly uses `!important` nearly everywhere).

**Comment by harmony7** [comment]
For the record, since 15.x it no longer works even on initial render (since moving away from innerHTML). All rules with "!important" are now being thrown out.

**Comment by syranide** [comment]
> For the record, since 15.x it no longer works even on initial render (since moving away from innerHTML). All rules with "!important" are now being thrown out.

For non-IE8 (which we actually don't actively care about anymore) this can technically be solved.

**Comment by yanickrochon** [comment]
Over two years ago, and this is still debated? To me restricting it's use because of some subjective argument is just regressive. If it's mainly to prevent people to abuse it, well, it is quite idiotic as it's use is... important on many use cases. If it is part of the [specification](https://www.w3.org/TR/CSS2/cascade.html#important-rules) :

> However, for balance, an "!important" declaration (the delimiter token "!" and keyword "important" follow the declaration) takes precedence over a normal declaration. Both author and user style sheets may contain "!important" declarations, and user "!important" rules override author "!important" rules. This CSS feature improves accessibility of documents by giving users with special requirements (large fonts, color combinations, etc.) control over presentation.

**Comment by toddself** [comment]
I literally just lost an hour debugging this. Given the amount of assistance react provides users when they do something unexpected (suggesting camel-case when using hyphenated class names, etc), i would have expected something in the console in this.

It would be awesome to be non-dogmatic and support people doing something unnecessary or at least warning about it.

**Comment by Venryx** [comment]
I'm having this issue as well.

The reason I need the " !important" override on an inline style is that my project is in a transition state, and still has CSS being applied using classes--one of which is using a css " !important" tag. (originally to override some JQueryUI css, I believe)

Having support for the tag would prevent me from having to use another css class (I'm trying to transition _AWAY_ from css classes), or modifying the old css class to no longer have the !important tag--which is a pain since it's used globally and would break other areas of the UI. (which are still using the old, JQuery rendering)

**Comment by brigand** [comment]
For the moment, I wrote a library that should address this use case: [brigand/react-with-important-style](https://github.com/brigand/react-with-important-style).

It uses `this.element.style.setProperty` to set the style with the `important` modifier.

**Comment by arackaf** [comment]
I said to myself, "it's not even a question if React will support this; of course they will."  Turns out that's not the case.  

My use case is like others: I'm trying to get my component to play along nicely with some third party stuff.  

I really hope this gets added.

**Comment by domino14** [comment]
Plz add

**Comment by tvankruijsbergen-aa** [comment]
Agreed this should be fixed. In the meantime, you can always style through the ref callback:

```
<div ref={(node:HTMLElement) => {
    if (node) {
        node.style.setProperty("float", "right", "important");
    }
}}>
                
</div>
```

**Comment by s-devaney** [comment]
Can't believe this isn't supported.

**Comment by Tectract** [comment]
I also just lost time debugging this. Please support !important. It's part of the css protocol, you should support the entire protocol not just the pieces you like.

> it would be expensive to check every value for !important

it would be cheap to check every value for ending in space, then only those that do for ending in !important.

**Comment by pmirandaarias** [comment]
Bad practice? sure, if you have coded from zero to none the entire page, what about to join a project with Symfony, UiKit, jQuery, etc, etc... that uses ReactJS too. What, I'll have to say to all the team "hey! bad practices, delete all the !important from the css please"

**Comment by sergiotapia** [comment]
I'm really surprised this has been overlooked for so long. Support for `!important` is absolutely needed for CSS. There are so many use cases for it.

**Comment by dagatsoin** [comment]
I am ok for best practice guideline.

But the majority of developper works on budget which leads to quick and dirty or in best case using bootstrap, foundation, uikit and co. which are still leader in the vanilla HTML/CSS integration habits. And they do use !important. It is not dirty, it is the css way for providing control on override in inheritance.

Also there is a lot of great projects which are driven by @vjeux famous presentation. And there are powerful: jss, glamor, styled-component, etc. Is still React responsibility to check CSS ?

**Comment by aJoohongKim** [comment]
I am working with Material-ui, some elements in a component can't reached using props/context.. I want to use css selector for that case and if that compete with element.style. I know I need !important for this project.

**Comment by ablankenship10** [comment]
Just to add, I'm writing a 3rd party widget to be injected using React and I have to use the CSS library cleanslate which gives me my own DOM with completely reset CSS. This also means I HAVE to use !important on all of my styles. This is necessary for anyone making a widget because you can't trust the styles of the rest of the page. So despite "good practice" this is necessary.

**Comment by Tectract** [comment]
React css support seems a little behind the times on css support actually. It should properly support not only all features of the css standard, but also css 'modules'. There are some key issues with css that cannot be easily addressed by any means other than modules, nameley global namespaces and code isolation. See here:

https://glenmaddern.com/articles/css-modules

On tool I used in some of my React-on-Rails projects is Rebass, which is a css module, for example:

https://github.com/jxnblk/rebass

but it seems to have only limited support. Works for a decent modal popup though...

**Comment by brigand** [comment]
@Tectract css modules are far outside the scope of React core. Also inline styles are as isolated as css modules.

**Comment by bootrino** [comment]
Folks, this is how I do important:

```
  render() {

    return (
        <div>
          <style>
            {`
              #colorBlackImportant {
                color: black  !important;
                font-size: 50px !important;
                }
            `}
          </style>
          <input
            type="text"
            className="form-control no-border-left colorBlackImportant"
            id="colorBlackImportant"
            name="navField"
            value={this.props.value}
            label="url"
            onChange={this.props.onChange}
            onKeyPress={(e) => {if(e.key === 'Enter') {this.props.onEnter()}}}
          />
        </div>
    )
  }
```

**Comment by sw-yx** [comment]
+1 for blink tag 😂

**Comment by singular1ty94** [comment]
@bootrino's solution is still the best to date, coupled with React's fragment syntax you can embed styles side-along tags you need edited, and cobble together some kind of solution - particularly useful if you're fighting Semantic-UI which uses `!important` _everywhere_: 

```
{myObjects.map((object, key) => {
    return (
        <Fragment key={key}>
            <style>
            {`
                #${object.uniq_id}_label {
                    background-color: ${colors[key]} !important;
                }
            `}
            </style>
            <Label
                size="large"
                color="teal"
                id={`${object.uniq_id}_label`}
            >
                {object.children}
            </Label>
        </Fragment>
    );
})}
```

**Comment by TimoSolo** [comment]
@singular1ty94 - Also trying to override SemanticUI - it may be semantic, but it's not great css :(

**Comment by singular1ty94** [comment]
@TimoSolo An alternative solution to that method, which I've used lately, is to use [styled-components](styled-components.com) to wrap Semantic UI's elements and then apply custom styling, eg:

```
import styled from 'styled-components';
import { Input } from 'react-semantic-ui';

export const StyledInput = styled(Input)`
    font-size: 12pt !important;
    ...
`
```

This way your JSX still looks relatively neat but you get the opportunity to apply actual CSS classes onto the Semantic elements rather than using additional elements or embedded CSS like my original solution.

**Comment by necolas** [comment]
I've bumped into this problem too. React Native for Web currently relies on `!important` for certain flex styles due to browser inconsistencies in how browsers treat `flex:n`. Applying `!important` is fine when transforming styles to CSS via `StyleSheet.create`, but breaks when using inline styles due to this limitation in React DOM.

A possible fix would be to change [`setValueForStyles`](https://github.com/facebook/react/blob/37e4329bc81def4695211d6e3795a654ef4d84f5/packages/react-dom/src/shared/CSSPropertyOperations.js#L54) to something like this:

```js
export function setValueForStyles(node, styles, getStack) {
  const style = node.style;
  for (let styleName in styles) {
    if (!styles.hasOwnProperty(styleName)) {
      continue;
    }
    // custom properties and kebab-case properties
    const isIgnoredProperty = styleName.indexOf('-') !== -1;
    if (__DEV__) {
      if (!isIgnoredProperty) {
        warnValidStyle(styleName, styles[styleName], getStack);
      }
    }
    const styleValue = dangerousStyleValue(
      styleName,
      styles[styleName],
      isIgnoredProperty,
    );
    if (styleName === 'float') {
      styleName = 'cssFloat';
    }
    if (isIgnoredProperty) {
      const [ value, priority ] = styleValue.split('!');
      style.setProperty(styleName, value, priority);
    } else {
      style[styleName] = styleValue;
    }
  }
}
```

React DOM is already checking every style name to determine if it's a custom property. This change would open an escape-hatch that allows custom properties and style properties defined using kebab-case, i.e., `{ 'background-color': 'red' }` to be applied using `setProperty` and to support `!important`. Because it's not converting every style property from camelCase to kebab-case, there doesn't seem to be any negative impact on inline-style performance in these [render tests](necolas.github.io/react-native-web/benchmarks) after making this change.

**Comment by corysimmons** [comment]
Why doesn't `<pre style={{ fontFamily: 'monospace !important' }}>` work? 😩

**Comment by kelseyleftwich** [comment]
I'm trying to use !important so background colors will print when using Chrome. Maybe there is a better way but I haven't found it. ¯\_(ツ)_/¯

**Comment by JoeDuncko** [comment]
Like others, I just ran into this while trying to build a react-powered widget to be used on third party sites. I, too, just spent a couple hours super confused because at one point styles would work, then as soon as I threw `!important` in there they disappeared. Very frustrating.

**Comment by steodor** [comment]
Having lost quite some time on this myself today, i'd like reiterate what @probablyup said back in 2015: `"It's not React's place to be dogmatic about how people author their styles."` - it's simple specs, i don't see one valid reason for not fully supporting it.

**Comment by ccurtin** [comment]
Sometimes `!important` **must** be used for overrides of 3rd party software.

**Comment by ckhicks** [comment]
This is super frustrating - while I agree with the theory of not using `!important` in your styles, it's not React's job to block something outright. Unless you can guarantee that every. single. vendor. lib. will stop using it as well, we need a way to override something if the situation demands it.

Put another way: Yeah, we shouldn't find ourselves sliding down the hill if we park correctly, but sometimes you just need perform a quick stop. You've removed the emergency brake.

**Comment by The-Code-Monkey** [comment]
this is something that should really be implemented even if we don't use the ! and just do say 

`style={{ width: '50% important' }}` or even `style={{ width: '50%', widthImportant: true }}`

I would be comfortable with either being implemented.

**Comment by lubber-de** [comment]
We managed to remove lots of !important from the SUI components in V2.7.x recently :slightly_smiling_face: 
https://fomantic-ui.com/introduction/new.html

**Comment by tomeady** [comment]
> We managed to remove lots of !important from the SUI components in V2.7.x recently 🙂
> https://fomantic-ui.com/introduction/new.html

I was running into this issue because I was using 2.6, so lucky I saw this

**Comment by champeleon** [comment]
So still no easy solution to this problem? I'm unable to change a Semantic UI element's color dynamically without access to !important.

**Comment by ckhicks** [comment]
Yeah, extending something just to fix one property doesn't seem like a scalable solution, given that you will have to adjust it to match the lib on every update. Uncool.

**Comment by lCavazzani** [comment]
Same thing @champeleon , I need to change some Semantic UI properties and really needed this !important. It should be supported for such a big library as React...

**Comment by Tectract** [comment]
I suggest the react team should consider implementing a !super-important tag.

**Comment by emildatcu** [comment]
This is stupid. I need !important in @media print, to remove the body from the page and setting the visibility of the dialog to be visible !important and overflow visible, when printing the contents of a dialog with 'multiple pages' within, like this -> 
![image](https://user-images.githubusercontent.com/42996811/53172063-148fcb00-35ed-11e9-8038-6dae542f602e.png)

So yeah, it should be included and supported. I know it's NOT OK to use !important, but sometimes it's necessary.

**Comment by milesj** [comment]
What if the styles supported a tuple (an array)? 

`style={{ width: ['50%', 'important'] }}` to support other possible flags?
`style={{ width: ['50%', true] }}` to only support important?

**Comment by ckhicks** [comment]
Love that idea, @milesj. It gets us a lot closer to having the support when needed, but making it stand out beyond the normal practice of writing CSS, so hopefully it would be flagged by casual PR reviews as bad practice. 😆

**Comment by mehrad77** [comment]
It's 2019 and still no support for !important? well done.

**Comment by behnood-eghbali** [comment]
It's not really a React problem. is it?! I see the other frameworks had the same problem with `!important`:[https://github.com/vuejs/vue/issues/3761](url)
[https://github.com/angular/angular/issues/12009](url)

**Comment by behnood-eghbali** [comment]
It's not actually a react problem. is it?! I see the other frameworks had the same problem with `!important`: 
_v-show should be !important #3761_
_NgStyle and style can not set `!important` #12009_

**Comment by steodor** [comment]
@behnood-eghbali just because other frameworks exhibit the same behavior doesn't make it a non-issue. It just means that they have the same problem as well.

**Comment by luke-pritch** [comment]
I can't believe that it has been 5 years and nothing has been done to address this at all. Working with frameworks that already have pre-defined `!important` tags and going through a roundabout way to fix them is very frustrating.

**Comment by anarchist912** [comment]
I recommend using [styled components](https://www.styled-components.com/), if you have a good reason to make use of "!important":

Here is an example where we overwrite Semantic-UI's padding on grid columns. You simply can't without important.

```javascript
const StyledColumn = styled.div(({size}) => ({className: `${size} wide column`})`
    padding-top: 0px !important;
    padding-bottom: 0px !important;
`
<StyledColumn size="three"></StyledColumn>
```

**Comment by pilniczek** [comment]
> I recommend using [styled components](https://www.styled-components.com/), if you have a good reason to make use of "!important":
> 
> Here is an example where we overwrite Semantic-UI's padding on grid columns. You simply can't without important.
> 
> ```js
> const StyledColumn = styled.div(({size}) => ({className: `${size} wide column`})`
>     &&&&& {
>         padding-top: 0.3rem !important;
>         padding-bottom: 0.3rem !important;
>     }
> `
> <StyledColumn size="three"></StyledColumn>
> ```
> 
> [&&&&&&](https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity) <- bumps up specifity

&&&&& seems to be very similar to this category of selectors. https://speakerdeck.com/csswizardry/refactoring-css-without-losing-your-mind?slide=64

**Comment by ChristianHardy** [comment]
Meeehhh React de mierda!!! No acepta !important...

**Comment by Tectract** [comment]
¡Ay, caramba! Tendrás que usar clases y una hoja de estilo vinculada en lugar de estilos en línea, mi hombre.

**Comment by ChristianHardy** [comment]
> ¡Ay, caramba! Tendrás que usar clases y una hoja de estilo vinculada en lugar de estilos en línea, mi hombre.

GGRRRR...!!! 😏😏😏😏

**Comment by necolas** [comment]
I submitted a PR for this which was rejected #12181, so I'm going to close this as "wontfix"

**Comment by ckhicks** [comment]
Rejected or just requesting changes? 🤔

**Comment by Tectract** [comment]
It appears it was rejected because they didn't like how the patch was implemented, from comments like these:

> I don't think we're opposed to supporting this feature per se. It's just that it's not clear a string-based API is the best one here.

> The part that feels wrong to me is that everybody has to pay for an indexOf lookup that nobody uses today (because the feature doesn't exist) and won't be commonly used in the future.

I don't have time to dig into the code, really... But it feels like there is a high demand for this feature so maybe it should be left re-opened, just a thought.

**Comment by gaearon** [comment]
I think a lot of commenters are probably missing the fact that **setting styles as `important` is already possible with a single line of code in React: https://github.com/facebook/react/issues/1881#issuecomment-262257503**.

I’m going to lock this thread to prevent further misinformation — it really does seem like most people don’t realize it, and adding more replies causes this information to get lost.

If you have a particular proposal for a more ergonomic alternative, please send an RFC here: https://github.com/reactjs/rfcs

**Comment by gaearon** [comment]
To be fair, the ref solution doesn’t help for server rendering. Again, if you have a particular API proposal, sending an RFC would be a better place to discuss it. Thank you!
