### ISSUE TITLE
Bug: Weird behavior when using react hooks inside of a React.StrictMode wrapper

### ISSUE THREAD

**Issue by acharb** [facebook/react#18817]
React version:
16.13

## Steps To Reproduce

1. setting state from the useRender hook immediately followed by a state sending function from useState, causes the useRender function to be called twice.

- this happens under the following occasion only (that I've noticed)
1.  if we bail out of rendering in our useRender render function
2. in a React.StrictMode wrapper

(if either of those two are not present, it doesn't occur)

Link to code example:
https://codesandbox.io/s/sad-robinson-dds63

## The current behavior
- clicking the "+" button causes test count to increment by 2

## The expected behavior
- clicking the "+" button should cause test count to increment by 1

**Comment by eps1lon** [comment]
Your reducer isn't pure which leads to the double increment due to React's [StrictMode](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects).

You'd want something like 

```diff
-state.test += 1;
-return state
+ return { test: state.test + 1 }
```

**Comment by acharb** [comment]
@eps1lon thanks for the reply!

I was testing out "bailing out of a dispatch", as given in the React docs here:
https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-dispatch

Where you return the same value so that the children don't render.

Is "bailing out" not recommended then? Or in what scenario is it recommended and safe to do so.
