### ISSUE TITLE
Bug: Multiple `useState()` calls to `set` override each other

### ISSUE THREAD

**Issue by tms1337** [facebook/react#18812]
When I call two methods to set state, only one ends up getting called. I know this could be fixed by using `useReducer`, but shouldn't this work as well.

React version:

```
    "react-dom": "^16.13.0",
```

## Steps To Reproduce

I create a simple custom hook as below. Since on click calls `heperA()` **and** `setB(5)` I would expect the end result to be `{a: "predefined", b: 5}`. But instead what I get is `{a: 3, b: 5}`

```
import React, { useState } from "react";

const useCustomState = initialState => {
  const [state, setState] = useState(initialState);

  return {
    state,
    actions: {
      setA: value => setState({ ...state, a: value }),
      setB: value => setState({ ...state, b: value }),
      helperA: () => setState({ ...state, a: "predefined" })
    }
  };
};

export default function App() {
  const { state, actions } = useCustomState({ a: 3, b: 2 });

  return (
    <div className="App">
      {JSON.stringify(state)}
      <button
        onClick={() => {
          actions.helperA();
          actions.setB(5);
        }}
      >
        Zmola
      </button>
    </div>
  );
}
```

Link to code example:

https://codesandbox.io/s/summer-rain-odzyh

## The current behavior

I get `{a: 3, b: 5}`.

## The expected behavior

I expect `{a: "predefined", b: 5}`.

**Comment by illuminist** [comment]
Common react setState pitfall where `state` in the second action still is the original `state`.

how it should be done:
```js
{
  setA: value => {
    setState(state=>({ ...state, a: value }));
  },
  setB: value => {
    setState(state=>({ ...state, b: value }));
  },
  helperA: () => {
    setState(state=>({ ...state, a: "predefined" }));
  }
}
```

**Comment by tms1337** [comment]
Thanks @illuminist. Didn't even know for this option, is there any docs for it?

**Comment by illuminist** [comment]
Yes it is. https://reactjs.org/docs/hooks-reference.html#functional-updates

**Comment by tms1337** [comment]
Thanks, closing
