### ISSUE TITLE
Bug [ESLint Hooks Plugin]: When using a `typeof` type guard it requires the value as a dependency

### ISSUE THREAD

**Issue by egonm12** [facebook/react#18828]
**Version:** eslint-plugin-react-hooks@1.7.0

## Steps To Reproduce

1. Create a component with local state
2. Create a useEffect with a variable inside, that points to the `typeof` of the state variable

Link to code example:

https://codesandbox.io/s/nervous-williamson-2i99l?file=/src/App.tsx:210-261

## The current behavior
`react-exhaustive-deps` complains that the state variable should be included in the dependency list

## The expected behavior
`react-exhaustive-deps` shouldn't complain that the state variable should be included in the dependency list because it's value is never used.

**Comment by gaearon** [comment]
Wanna send a fix? Seems TS specific.

**Comment by egonm12** [comment]
Gonna look into it, will keep you posted

**Comment by delca85** [comment]
Hi! Could I maybe give this a shot? @egonm12 are you still working on it?

**Comment by gaearon** [comment]
@delca85 Please go ahead, it's been a while!

**Comment by gaearon** [comment]
@delca85 fixed this in #19316. If you find other similar issues, please report them too! Thanks.

`eslint-plugin-react-hooks@4.0.8` should have the fix.
