### ISSUE TITLE
Feature suggestion:  possibility to intercept passage of props for the components, in order to transform them

### ISSUE THREAD

**Issue by misaeldossantos** [facebook/react#18829]
this sounds interesting: possibility to intercept a component's props, transforming them.
Thus, it would be possible to implement directives as in vue and angular:

example:
```jsx
<div
   @showIf = "visible"
>
<span> Something </span>
</div>

function renderIf (condition, oldProps) {
   return merge (oldProps, {style: {visible: condition}})
}
```

I think why not? The react could be made more flexible. Interceptor functions could be placed via context API. We could implement transformations of props. In react native, it would be possible to place classes, transforming them into styles

```jsx

<View @classes="flex"></View>

function test(classes, oldProps) {
    return merge(oldProps, {style: {flex: 1}})
}

```

**Comment by threepointone** [comment]
Directives were made for templated systems because you couldn't write regular javascript in them. React instead lets you use regular js idioms for functionality like this. 
```jsx 
{someCondition && <div> <span> Something </span> </div>}
```
But if you do want 'directives', there's nothing stopping you from making a component that accepts conditions too. The point here is that jsx is *more* expressive than vue/angular style templates.

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.
