### ISSUE TITLE
useMutableSource: allow getSnapshot to return a function

### ISSUE THREAD

**Issue by dai-shi** [facebook/react#18823]
Ref: https://github.com/reactjs/rfcs/pull/147#issuecomment-623740218

React version: 0.0.0-experimental-e5d06e34b

## Steps To Reproduce

1. createMutableSource that contains functions
2. getSnapshot returns one of the functions

Link to code example:

https://codesandbox.io/s/jovial-dew-1eg4t?file=/src/App.js

## The current behavior

If getSnapshot returns a function, it will run the function in render. This results in various errors.

My workaround: return an object wrapping a function, and destruct on caller.

> For now, you can work around this by returning a function that returns your function

I don't know how this works as workaround.

## The expected behavior

It would be nice if returning a function just works.

Note: this is not a rare use case in my library https://github.com/dai-shi/use-context-selector
because we often pass `[state, setState]` in a context value.

**Comment by dai-shi** [comment]
Thanks. Understood. I'd try not-100%-safe workaround in my lib, or let the lib users do a workaround.

**Comment by bvaughn** [comment]
Thanks for understanding!

**Comment by dai-shi** [comment]
(For those who might come here later,) here's my workaround: https://github.com/dai-shi/use-context-selector/pull/12/commits/2fcf1a2bfb9552daedca11ecff030914e3089aa3#diff-f41e9d04a45c83f3b6f6e630f10117fe
