### ISSUE TITLE
Bug: [ESLint Hooks Plugin] false positive with useCallback and not inline function body

### ISSUE THREAD

**Issue by kilianc** [facebook/react#18833]
I just received `eslint-plugin-react-hooks@4.0` through dependabot, and I am a little confused by the error and the explanation in this PR https://github.com/facebook/react/pull/18435. I might be wrong but I don't think I should be getting a lint warning/error.

```ts

const useFoo = <R>(
  selector: (state: S) => R,
  dependencies: DependencyList = []
) => {
  const memoizedSelector = useCallback(selector, dependencies)
  // React Hook useCallback has a missing dependency: 'selector'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  ...
}
```

My my `selector` function changes every time, and adding it to the `dependencies` list defeats the whole purpose of useCallback in the first place. Maybe I am missing something here.

I tried to create a codesandbox, but apparently custom eslint configs are not supported. Let me know what I can doo to help.

This is the relevant code: https://github.com/kilianc/mozzarella/blob/master/src/create-store.ts#L45-L70

This is the PR that complaints: https://github.com/kilianc/mozzarella/pull/8

This is the error from github actions: https://github.com/kilianc/mozzarella/runs/644435406?check_suite_focus=true

**Comment by gaearon** [comment]
The purpose of the linter is to verify that you don't have stale closures. If you pass invisible `selector` and `dependencies` we can't verify that. You can add an ignore there if you're convinced the deps are correct, but the warning itself is right — it says something may be unsafe. E.g. in your example, nothing will actually verify that `useSelector` *receives* correct deps.

**Comment by kilianc** [comment]
@gaearon if I understand your feedback correctly this is not about the function being passsed to `useCallback` but to the deps array.

```ts
const useFoo = <R>(selector: (state: S) => R) => {
  const memoizedSelector = useCallback(selector, [])
  // React Hook useCallback has a missing dependency: 'selector'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  ...
}
```

This yields the same error. Do you mind elaborating?

**Comment by gaearon** [comment]
Hmm. I don’t understand your question.

Maybe we can do this backwards. What do you expect the linter to help you with?

**Comment by kilianc** [comment]
I don't understand why the linter is complaining about the function `selector` not being part of the dependencies array. Your first feedback [here](https://github.com/facebook/react/issues/18833#issuecomment-624319206) just mentions the inability to check the dependencies because they are not a literal but a variable / function argument. I get that. But the warning is about `selector` not being a dep, which to me doesn't make sense, why should it be?

If I put it there, the hook will re-run every time, since the function is inlined upstream, and I don't want that obviously.

In general, If I am writing my own hook that internally calls `useCallback` or` useEffect`, I am most likely going to end up in this situation. Do I just need to disable the line? Seems counter intuitive and feels weird.

**Comment by gaearon** [comment]
Consider this situation.

```js
function Button({ onPressChange, isPressed }) {
  useEffect(onPressChange, [isPressed]);
}
```

In your opinion, should this warn or not?

**Comment by kilianc** [comment]
no, I don't think so 

```js
<Button onPressChange={() => console.log('pressed-change')} />
```

what am I missing?

**Comment by kilianc** [comment]
To be more precise, I understand how

```js
function Button({ onPressChange, isPressed }) {
  useEffect(onPressChange, [isPressed]);
}
```

could trigger a warning considering the inability to statically analyze `onPressChange` and the relation with `isPressed`.

What I am referring to here, given this example:

```js
const useUseCallback = (fn, deps) => {
  return useCallback(fn, deps)
  // React Hook useCallback has a missing dependency: 'fn'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
}
```

* why am I a getting a warning at all
* why is the warning telling me to add the function itself to the dependencies?

The warning is telling me there is a fix I need to apply to my code when In reality, given your feedback, the only path forward is disabling eslint for that line, am I correct?
