### ISSUE TITLE
Inhancement: Dispatch (returned by useReducer) shuould also be available as third parameter in reducer function.

### ISSUE THREAD

**Issue by sumitsj** [facebook/react#18839]
React version: @latest

**I am using Context API to manage state of my application, and stuck at below problem.**

## The current behavior
Currently, reducer function takes just **state** and **action** as parameter. I can dispatch actions from components only, due the behavior of hooks (as you know). But what if I there is some dependent action (**Y**) on action (**X**) which needs to be called after completion of action (**X**). Currently there is no way to handle this kind of scenario. 

## The expected behavior
If there had been **dispatch** function as third parameter, passed internally and automatically to the reducer function, we could have solved above problem. 

Currently I have to pass **dispatch** as part of action payload, which does not look right and clean.

This will help developers to write clean code, and all the logic related to dependent actions can be moved inside reducer function from components.

## Example

```javascript
const reducer = (state, action, dispatch) => {
  switch (action.type) {
    case 'LOGIN':
      // Do LOGIN related stuff here
      dispatch({ type: 'LOGIN_SUCCESS' });
      return { ...state };
    case 'LOGIN_SUCCESS':
      // Do LOGIN_SUCCESS related stuff here
      return { ...state };
    default:
      return state;
  }
};
```

**Comment by albseb511** [comment]
dispatch function generally accepts the action, and invokes the reducer to update the state.

what does it solve? reducers should be kept separate from dispatchers.

dispatcher(action) -> reducer -> update UI

this is an architecture decision I guess.

**Comment by threepointone** [comment]
Reducers should be pure, you'll probably have bugs if and when the reducer is called multiple times, and not how you expect. You shouldn't call dispatch from inside the reducer. You should put side effects into useEffect, running them based on state. This could get cumbersome, so consider an abstraction like this instead https://gist.github.com/sophiebits/145c47544430c82abd617c9cdebefee8 Read the .test.js for usage examples.

**Comment by sumitsj** [comment]
Yes got it. Thanks @threepointone @albseb511
