### ISSUE TITLE
Bug: Previous and next props in memo equality function are the same

### ISSUE THREAD

**Issue by fourstacks** [facebook/react#18842]
I have built a config-driven form builder package for the Shopify Polaris UI library.  I'm using `memo` to prevent unnecessary updates.  This memo call uses an equality check method which checks (among other things) if a `fields` prop has changed.  If it has, the whole component should re-render.  The fields prop is an array of objects and I've been using the lodash `isEqual` utility method for deep comparison.

Until now I've not really needed to change the config of fields passed to this builder dynamically but I've now hit a use-case for this behaviour and I've noticed that the previous and next props passed to the `memo` equality method are always the same despite the actual prop itself having changed.

React version: 16.13.1

## Steps To Reproduce

1. Open CodeSandbox (below)
2. Open the console
3. In the 'Foo' input type `foo`

Link to code example:

Here's a very stripped back example of the issue I'm seeing:

[Codesandbox](https://codesandbox.io/s/memo-props-demo-czo8o)

Note that I'm aware that the memo call itself in this demo does nothing as the equality check returns false, however the point is to observe the values of `prev` and `next` in the equality check method.

## The current behavior

Within `Fields.ts` in the codesandbox I'm doing a very simple map operation to change the `disabled` state of the 'Bar' field based on the content of the 'Foo' field.  If the value of the 'Foo' field is `foo` then 'Bar' should be disabled.  This behaviour is observed.

However, the console dumps out the value of `prev` and `next` in the `memo` equality method on each keystroke and these values are always the same.

On typing `fo` into the 'Foo' input you'll see something like this (truncated for brevity):
 
```
prev  fields: [ 0: {...}, 1: { key: 'bar', disabled: false }]
next  fields: [ 0: {...}, 1: { key: 'bar', disabled: false }]
```

Upon completing the word in the 'Foo' input to `foo` you'll see new output:

```
prev  fields: [ 0: {...}, 1: { key: 'bar', disabled: true }]
next  fields: [ 0: {...}, 1: { key: 'bar', disabled: true }]
```

## The expected behavior

I would expect that, upon typing `foo` I would see the following console output:

```
prev  fields: [ 0: {...}, 1: { key: 'bar', disabled: false }]
next  fields: [ 0: {...}, 1: { key: 'bar', disabled: true }]
```

I'll fully admit that my knowledge of how React does it's thing when rendering is largely a black box to me and that I may be missing something fundamental but based on what I've read of `memo` it seems like this should work as outlined above.

Would really appreciate any clarity on whether this is a bug or (more likely) if I'm misusing `memo` in some way.

**Comment by vkurchatkin** [comment]
That's because you mutate your field objects in `getComputedFormFields`. ` getComputedFormFields` always return a new array, but it always contains original objects.

**Comment by fourstacks** [comment]
Ahh, ok!  So basically I need to return a deep clone of `field` in `getComputedFields` in order for react to detect the change?  Seems to work in the fork of the sandbox I created:

https://codesandbox.io/s/memo-props-demo-k1ph5

Thanks very much indeed for the advice @vkurchatkin  - not sure I'd have ever hit upon that myself.

**Comment by vkurchatkin** [comment]
> I need to return a deep clone of field in getComputedFields in order for react to detect the change

Not deep clone, shallow is enough.
