### ISSUE TITLE
"Pause on caught exceptions" enabled always breaks on this line

### ISSUE THREAD

**Issue by kylechartio** [facebook/react#18843]
In Chrome, when I am using the current stable version of react devtools extenison (4.6.0 (3/26/2020)), if I have "Pause on caught exceptions" enabled, I always hit this breakpoint:

https://github.com/facebook/react/blob/c2d1561c60507189b43ae96c6b89580874367e36/packages/react-devtools-shared/src/hook.js#L185

`ReferenceError: i is not defined
    at Object.inject (<anonymous>:1:1116)
    at injectInternals (react-dom.development.js:9842)
    at injectIntoDevTools (react-dom.development.js:20715)
    at eval (react-dom.development.js:21244)`

It would be nice if the published extension had an options page so that I could disable this try/catch block. (for example enabling NODE_ENV=test or something). 

Or, perhaps that code block is not really relevant to the chrome extension case, and that code path could be ignored for the chrome extension.

**Comment by bvaughn** [comment]
Yeah, I can see why this would be a little annoying. This same hook is being used in a couple of different contexts, and in the browser one- we expect things to be a little busted, as the inline comment above mentions:
https://github.com/facebook/react/blob/c2d1561c60507189b43ae96c6b89580874367e36/packages/react-devtools-shared/src/hook.js#L177-L185

I guess ideally, we'd just strip this code block entirely for an extension. Maybe we could do a variation of #16869 to specify a build target (e.g. `INLINE`, `EXTENSION`, `STANDALONE`).

**Comment by Satzyakiz** [comment]
I would like to work on it as my first issue.

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by Satzyakiz** [comment]
Can you guide me how to proceed ?

**Comment by bvaughn** [comment]
Just my comment above: https://github.com/facebook/react/issues/18843#issuecomment-624888219

**Comment by Satzyakiz** [comment]
Right, someone else can pick it up.

**Comment by bvaughn** [comment]
Ok. No problem.

**Comment by sktguha** [comment]
I would like to work on it , @bvaughn . So the build infra changes have to be made in this repository only I hope ? And you mentioned that good first issue is misleading, does that mean it is too hard for a newcomer to pick it up ?

**Comment by bvaughn** [comment]
> So the build infra changes have to be made in this repository only I hope ?

Yes.

> And you mentioned that good first issue is misleading, does that mean it is too hard for a newcomer to pick it up ?

What makes something a "good first issue" depends a lot on a person's background. This repo has a broad range of code, so the label just isn't granular enough. I think "needs help" might be a better label, and then a secondary label e.g. "infra", "ui", etc. could be nice but anyway.

**Comment by bvaughn** [comment]
It's all yours @sktguha. Please feel free to assign your PR to me for review. Let me know if you change your mind and I'll return it to the pool for someone else to claim.

**Comment by bl00mber** [comment]
@bvaughn non-members cannot assign anyone for review :smiley:

**Comment by bvaughn** [comment]
By "assign" I just meant "comment my name" ...

**Comment by bvaughn** [comment]
Any progress here @sktguha

**Comment by sktguha** [comment]
Hi @bvaughn , 
Actually I haven’t found time to start on it yet. I will find time on the weekend to look into it . I guess if not by then then you can unassign it.

**Comment by bl00mber** [comment]
Can I make a PR? @sktguha

**Comment by sktguha** [comment]
hi @bl00mber ya i guess as I haven't started on this so you can do it if you have solved the problem successfully

**Comment by sktguha** [comment]
@bvaughn I think @bl00mber has made a PR for this. You can check that out

**Comment by bvaughn** [comment]
This issue will be fixed via #18994 although there may be other caught exceptions that still occur in the extension.
