### ISSUE TITLE
Bug: Devtools conceal lack of setImmediate polyfill

### ISSUE THREAD

**Issue by matt-tingen** [facebook/react#18853]
React version: N/A; sample app uses 16.13.1
Devtools version: 6cceaeb67 on FF and Chrome

## Steps To Reproduce

Generally speaking:
1. Call `setImmediate` in a react app without a polyfill after react devtools have initialized.

To demonstrate in the sample app:
1. Open sample app with browser devtools closed.
2. Click button and observe that `setImmediate` is not defined initially or after mounting react.
3. Open browser devtools to allow react devtools extension to initialize.
4. Click button and observe that `setImmediate` has been defined.

Link to code example:

I couldn't figure out how to prevent polyfills from being included on CodeSandbox.
[js bin editor](https://jsbin.com/rixunedepi/1/edit?html)
[repro page](https://output.jsbin.com/rixunedepi/1)

## The current behavior
React devtools globally defines a polyfill for `setImmediate`, masking the problem.

## The expected behavior
Usage of `setImmediate` without a polyfill in an app will throw an error.

**Comment by bvaughn** [comment]
DevTools does not do this. It's a Webpack polyfill :frown:

Funny timing for you to file this, as it was just fixed earlier today: #18860

Fix will roll out with the next week.
