### ISSUE TITLE
Provide a prop on `<Suspense>` to let children mount/unmount instead of changing style

### ISSUE THREAD

**Issue by huozhi** [facebook/react#18856]
## Feature Request

Currently react render children of Suspense with inline style `display: none !important`, [referenced PR](https://github.com/facebook/react/pull/15861/files). would like to have a prop like `mount` or sth else to remount the children when suspended state changed.

## Example

```jsx
const Chid = () => 
   // ... 
   return <div>{data}</div>
```

```jsx
<Suspense mount fallback={<span>fallback</span>}>
  <Chid />
</Suspense>
```
the above code will only render fallback component

```html
<span>fallback</span>
```
instead of

```html
<span>fallback</span>
<div style="display: none !important;">data</div>
```

**Comment by threepointone** [comment]
Could you explain your specific usecase/issue that makes you desire this behaviour?

**Comment by huozhi** [comment]
@threepointone I came across this behavior when I was doing snapshot for suspense rendering results with jest. I need to filter out the hidden children and find the actual rendered fallback element to detect if it's suspended.

**Comment by threepointone** [comment]
iirc, the dom elements might be holding state, so it's actually important that they stay in the dom. 

It's also a little odd to do visibility checks with snapshots. Consider that some other code, even user code, might have hidden a parent element. Then your test would pass even though it doesn't 'work' as expected. As an immediate workaround, I'd recommend making a helper, something like `isVisible()` that checks the snapshotted tree. I'd also recommend moving to a 'real' dom for testing (like jsdom) and using regular dom apis for assertions like `isVisible()` (eg - https://stackoverflow.com/a/21696585)

**Comment by eps1lon** [comment]
Sounds like a duplicate of #14536

This is a known quirk with `ReactDOM.render` (i.e. legacy mode) that will be fixed in blocking (createBlockingRoot) and concurrent mode (createRoot). In the experimental modes react wont trees in an inconsistent state.

> It seems like the fix to this will be #15504. Note it requires that your tree is Strict Mode compliant. We can't fix this in legacy mode.

-- https://github.com/facebook/react/issues/14536#issuecomment-487670591

**Comment by threepointone** [comment]
^ He's right, but that would require you to migrate to concurrent mode, which isn't really a recommended option at the moment.

**Comment by eps1lon** [comment]
Yeah. To make this more clear: If this is a duplicate of #14536 then this can't be fixed in stable react 16 as per comment from Dan in https://github.com/facebook/react/issues/14536#issuecomment-487670591.

**Comment by huozhi** [comment]
Thanks for clarification  @eps1lon 👍. @threepointone work around on testing side make sense, thanks for the help. 
close this issue as duplicate.
