### ISSUE TITLE
[eslint-plugin-react-hooks] just mark react's implemented hooks as invalid in classes

### ISSUE THREAD

**Issue by DoubleU23** [facebook/react#18857]
## The current behavior
`react-hooks/rules-of-hooks` marks custom hooks to be invalid in classes

## The expected behavior
imho this rules should only mark react's implemented hooks as invalid in classes

__as the rule states:__
"React Hook "useTranslation" cannot be called in a class component.  
React Hooks must be called in a React function component __or a custom React Hook function__."

__so it is allowed to use custom hook functions in classes?__ (at least it works)

if that's wrong (usage of custom hooks), then:
* why does it work
* the rule statement should be changed

__BTW:__ altought it might be no classical custom hook, maybe just a function using a hook,
__but it should not be marked as hook, just because of the prefix?__

## The alternative way
__support a whitelist for that rule?__

related to #15227, #14791, #17636

**Comment by finom** [comment]
Similar issue here. I use a non-redux store library which is based on classes. These classes define custom hooks as methods and they use react hooks internally. These classes aren't inherited from React.Component and they also don't have render() method. I understand why hooks can't be used at class components but there is no reason to error if a hook is used inside a custom class. Methods are just functions which have access to `this` keyword, there is no big difference if you define either a hook function or a hook class method. I propose to either allow hooks to be used in classes which aren't inherited from React.Component or define an option which allows to disable only the given rule.

By the time being I have to apply `// eslint-disable-next-line react-hooks/rules-of-hooks` to all `useX` calls.

**Comment by gaearon** [comment]
We strongly discourage defining Hooks inside classes or as part of classes. The reason is that classes typically contain mutable state, so it is very easy to accidentally close over something that won't cause an update on change.

You can, of course, disable the lint rule, but the push to use plain functions is very intentional.
