### ISSUE TITLE
Bug: Typeerror: ReactDOM.createRoot(container) is not a function

### ISSUE THREAD

**Issue by raghav0622** [facebook/react#18866]
ReactDOM.createRoot is not a function 

React & ReactDOM version:^0.0.0-experimental-33c3af284

## Steps To Reproduce

1. npx create-react-app my-app --template typescript
2. cd my-app && yarn upgrade react@experimental react-dom@experimental
3. refrence types in react-app-env.d.ts
  `/// <reference types="react-scripts" />
  /// <reference types="react/experimental" />
  /// <reference types="react-dom/experimental" />`

[Github Repo to reproduce](https://github.com/raghav0622/cra-typescript-suspense)

Additional Info:
OS: Windows 10 
Browser: Chrome

## The current behavior
no ui renders instead following error occurs:-
TypeError: react_dom__WEBPACK_IMPORTED_MODULE_1___default.a.createRoot is not a function
![screencapture-localhost-3000-2020-05-08-08_20_18](https://user-images.githubusercontent.com/29769428/81365112-ebc9f780-9104-11ea-8e6b-bc269796c1ab.png)

## The expected behavior
Everything should work fine i guess?!

**Comment by nihgwu** [comment]
I think it's related to the recent change to prefix `createRoot` with unstable https://github.com/facebook/react/blob/master/packages/react-dom/index.experimental.js#L22

**Comment by bvaughn** [comment]
I don't think you shared an actual repro, @raghav0622. The GitHub repo you linked to uses `ReactDOM.render`.

@nihgwu is right though that we recently added an "unstable_" prefix to several unreleased APIs, including `createRoot`. You'd need to use `ReactDOM.unstable_createRoot` for now :smile:

**Comment by AbrarShahriar** [comment]
@bvaughn `ReactDOM.unstable_createRoot` is still giving me the same error.

**Comment by daisy11100** [comment]
I use the `ReactDOM.unstable_createRoot` have the same error

**Comment by bvaughn** [comment]
@AbrarShahriar @daisy11100 This is expected. The `createRoot` API has not been released yet.

If you want to try it, you can install `react-dom@experimental` but note that the experimental release channel is not meant to be used in production apps.

**Comment by daisy11100** [comment]
> @AbrarShahriar @daisy11100 This is expected. The `createRoot` API has not been released yet.
> 
> If you want to try it, you can install `react-dom@experimental` but note that the experimental release channel is not meant to be used in production apps.

> @AbrarShahriar @daisy11100 This is expected. The `createRoot` API has not been released yet.
> 
> If you want to try it, you can install `react-dom@experimental` but note that the experimental release channel is not meant to be used in production apps.

But I have installed  `react-dom@experimental` ，still have the error

**Comment by bvaughn** [comment]
I'm looking at the latest release of `react-dom@experimental`:
https://unpkg.com/react-dom@experimental/cjs/react-dom.development.js

It exports `createRoot`.

**Comment by daisy11100** [comment]
> I'm looking at the latest release of `react-dom@experimental`:
> https://unpkg.com/react-dom@experimental/cjs/react-dom.development.js
> 
> It exports `createRoot`.
thank you very much ,i have not try  to use `createRoot` because someone said use it have error on stackoverflow yesterday

**Comment by Almas-Asghar-730** [comment]
with` react-dom@experimental ` this you also have to install `react@experimental`, this works for me

**Comment by yuankai738631** [comment]
import ReactDOM from 'react-dom/client';

**Comment by mqliutie** [comment]
I have checkout to version 16.13.1 and React exported the `createRoot`. But I npm install react-dom `16.13.1` I can't find this function in `node_modules/react-dom/cjs/react-dom.development.js`

**Comment by mqliutie** [comment]
<img width="1823" alt="image" src="https://user-images.githubusercontent.com/11795518/197663814-de5971de-14fe-4033-ba9f-b722876045a8.png">
This image we can know  the ReactDOM export the `createRoot`  in the code at `2020/2/26`
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/11795518/197663996-c1157b10-0b69-4e05-9b10-34fa0751de50.png">
This image we can know `16.13.1` was released at `2020/3/20`
Is this mean `16.13.1` include the function?

**Comment by Alexz123640** [comment]
Hello i find this solution.
https://beta.reactjs.org/learn/add-react-to-a-website
use this script:
<script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>

**Comment by deepak100ni** [comment]
Hello friends, I had the same issue, I just imported **import ReactDOM from "react-dom/client";**

**Comment by supritansu** [comment]
CLI
npm i react@experimental
npm i react-dom@experimental

After that in App.js
import React from "react";
import ReactDOM from "react-dom";

**Comment by rickhanlonii** [comment]
createRoot was moved to react-dom/client.
