### ISSUE TITLE
Deprecate SyntheticKeyboardEvent.{charCode,keyCode,which}

### ISSUE THREAD

**Issue by japgolly** [facebook/react#18873]
The following `KeyboardEvent` properties have been officially deprecated:

* https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode
* https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
* https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which

React should probably mark these as deprecated too, and issue warnings in development mode.

**Comment by japgolly** [comment]
bump

**Comment by gaearon** [comment]
What is the motivation? Even if the browser calls them deprecated they won’t be removed, right? As too much code probably depends on them.

**Comment by tychenjiajun** [comment]
If you're using typescript. They are already marked as deprecated in d.ts https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v16/index.d.ts

**Comment by SOSADonV** [comment]
If this is deprecated then why is Editor.onTab still refering to it? is this library even being maintained at all?
