### ISSUE TITLE
How to test component methods the right way?

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react#1887]
I have a component which calls another method in `componentDidMount`. I'm testing with jest and I want to replace the method to be called with a mock so I can verify that it is being called. What's the correct way to do this? I tried replacing the method on `componentDescriptor.type.prototype` but that didn't seem to have any effect because of the auto-binding in react. So for now I've resorted to replacing the method on `componentDescriptor.__reactAutoBindMap` which of course is not ideal, since it uses react internals. Is there a better way which I'm currently missing?

Update: in 0.11 the path is now `componentDescriptor.type.prototype.__reactAutoBindMap` - the question persists though.

**Comment by jakeboone02** [comment]
@spicyj, since 0.13 is out with support for ES6 classes, do you have anything to add to this issue now?

**Comment by spicyj** [comment]
For components that are implemented as ES6 classes, you should be able to mock the class methods using jest's (or any other framework's) standard mocking mechanisms; there's nothing React-specific necessary to do any more. If that's not the case let me know and I'll reopen.
