### ISSUE TITLE
The pacote dependency should be re-evaluated

### ISSUE THREAD

**Issue by SchnWalter** [facebook/react#18871]
The React repository depends on [pacote](https://www.npmjs.com/package/pacote), a JavaScript Package Handler that has ~2M weekly downloads and only 8 peoples watching the [project on GitHub](https://github.com/npm/pacote), now there are 9.

This looks like a recipe for a left-pad scale disaster. I would like to to invite some of the React contributors to start watching this project and maybe evaluate if it's really needed.

**Comment by markerikson** [comment]
What does the number of people "watching" the repo have to do with anything?

Searching the repo, the only place `pacote` is used is for a single script called `downloadReactIsForPrettyFormat.js`, which is [called in the `postInstall` script when you clone and install this repo](https://github.com/facebook/react/blob/d2ef120089b46a92702cedfd06139f92ce2ca1bf/package.json#L108).  So, it has nothing to do with runtime behavior - it's part of setting up a React development environment.

This seems like a rather hyperbolic comment, and not something that's really a point of concern.

**Comment by gaearon** [comment]
Yeah, this seems like a misunderstanding.

**Comment by SchnWalter** [comment]
What I wanted to say is that a key piece of the NPM infrastructure, on which React has a direct and an indirect dependency, should have more eyes on it. I won't hurt if some React contributors will start to follow the changes in pacote. It's better to be safe than sorry.
