### ISSUE TITLE
Bug: function component is unmount and mount with old state when hmr

### ISSUE THREAD

**Issue by BryceHQ** [facebook/react#18874]
Please see https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/85
I am not sure the bug is react-refresh or react-refresh-webpack-plugin ? 
Thanks for your help.

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by irohitb** [comment]
@BryceHQ You forgot to add steps to reproduce and link to code example in the current issue. though it's if someone follows the link you posted in the question

**Comment by gaearon** [comment]
Replied here: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/85#issuecomment-626188070.
