### ISSUE TITLE
Improve the invalid hydration warning

### ISSUE THREAD

**Issue by etienne-martin** [facebook/react#18879]
**_Do you want to request a feature or report a bug?_**

feature / improvement

**_What is the current behavior?_**

Debugging hydration problems can be quite challenging because of the lack of information provided in the error message. 

Common invalid hydration warning:

```
Warning: Expected server HTML to contain a matching <div> in <div>.
```

As you can see the warning is quite vague and is not really helpful at pinpointing where the issue might come from other than telling us that it involves two divs. The associated stack trace is not helpful either. 

People usually end up debugging those warnings in a trial and error fashion, removing components one after the other until the warning goes away. It can be time consuming and tedious to do so. I feel like there has to be a better way.

**_What is the expected behavior?_**

I would expect to see the actual dom node in which the problem occurred.

Something like: 

```
Warning: Expected server HTML to contain a matching <div> in <div class="header-desktopcomponent__Right-sc-9okbvn-0 gDzgOl">...</div>
```

Looking at react-dom source code, I found the function responsible for that warning message:

https://github.com/facebook/react/blob/823dc581fea8814a904579e85a62da6d18258830/packages/react-dom/src/client/ReactDOMComponent.js#L1277-L1293

I added a good ol' console log which yielded the `parentNode` to the console:

![image](https://user-images.githubusercontent.com/9700213/81482857-0afd7d80-9208-11ea-8b1c-aa9e07609dcf.png)

It is now much easier to find where the issue originates and I feel like that's something that would be useful to a lot of people.

It's currently not possible to pass the `parentNode` to the console.error call because it gets stringified and turned into `[object HTMLDivElement]`. We would need to change the way the `warningWithoutStack` function concatenates warnings. 

I'm willing to help make these error messages more descriptive and wonder if this is something that would be welcome before I spend some time on it. 

**_Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?_**

Tested with react-dom v16.12.0

**Comment by etienne-martin** [comment]
Bump

**Comment by gaearon** [comment]
React 16.13 added component stack for this.

https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#component-stacks-in-hydration-warnings

**Comment by etienne-martin** [comment]
Awesome thank you
