### ISSUE TITLE
Bug: unexpected warning on custom hook call-site

### ISSUE THREAD

**Issue by surgeboris** [facebook/react#18887]
With `eslint-plugin-react-hooks@4.0.0` I observe an unexpected warning (with a weird behaviour) on custom hook call-site.

## Steps To Reproduce

1. yarn create react-app hooks-bug
2. cd hooks-bug
3. npm run eject
4. npm i eslint-plugin-react-hooks@4.0.0
5. place code from the examples below into `App.js`
6. run `npx eslint src/App.js`
7. check output for warnings mentioned below

Code example:

```
function App(props) {
  useSomeEffect(props, {});
  return null;
}

function useSomeEffect() {}

export default App;
```

npx eslint src/App.js

./src/App.js
  2:3  warning  React Hook useSomeEffect has a missing dependency: 'props'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

✖ 1 problem (0 errors, 1 warning)

```
function App(props) {
  useSomeEefect(props, {});
  return null;
}

function useSomeEefect() {}

export default App;

```

npx eslint src/App.js

{no output}

## The current behavior

1. `react-hooks/exhaustive-deps` warning triggered on a custom hook call-site
2. change to the hook name (so it doesn't contain the `Effect` part) fixes the warning

## The expected behavior

1. `react-hooks/exhaustive-deps` should only be triggered on a custom hook definition-site (at least as far as I understand it)
2. change to the hook name should not affect the warning

**Comment by bvaughn** [comment]
Related to #18888, arguably a duplicate

**Comment by surgeboris** [comment]
I'd say #18888 is a duplicate of this issue, since it was created later (but the time difference is so small that it's certainly possible that we were authoring our issues simultaneously).

Anyways, #18888 got more attention, so I'm closing this one.
