### ISSUE TITLE
[eslint-plugin-react-hooks] false positive with useFocusEffect

### ISSUE THREAD

**Issue by leethree** [facebook/react#18888]
Upgraded `eslint-plugin-react-hooks` to 4.0.0, it's showing errors on React-Navigation's `useFocusEffect` hook.

```js
import { useFocusEffect } from '@react-navigation/native';

  useFocusEffect(
    React.useCallback(() => {
      const unsubscribe = API.subscribe(userId, user => setUser(user));
      return () => unsubscribe();
    }, [userId])
  );
```
(example copied from [`React-Navigation` documentation](https://reactnavigation.org/docs/use-focus-effect/))

## The current behavior

Lint error:

```
React Hook useFocusEffect received a function whose dependencies are unknown. Pass an inline function instead.
```

## The expected behavior

The rules shouldn't check the function because it's not a React `useEffect` hook.

**Comment by gaearon** [comment]
>The rules shouldn't check the function because it's not a React useEffect hook.

Sigh. People have been asking for the opposite, so we added this for every function ending with `Effect`.

**Comment by vkurchatkin** [comment]
Admittedly,  `useFocusEffect` is weird. It could easily work exactly like `useEffect` instead of requiring `useCallback`. Also you could probably just use `useIsFocused` + `useEffect` to avoid this issue

**Comment by leethree** [comment]
> Sigh. People have been asking for the opposite, so we added this for every function ending with `Effect`.

😢 I completely understand it. But it's difficult to ask all library authors to follow the same rules. Maybe adding an option would help.

**Comment by leethree** [comment]
Sounds reasonable to me.

> we'd reserve Effect suffix for things that mirror the dependency API.

Would be great if this could be added to documentation. I would file an issue to `react-navigation` asking them to change the hook name 😄

**Comment by surgeboris** [comment]
> Sigh. People have been asking for the opposite, so we added this for every function ending with Effect.

It is very nice indeed that you're implementing features people were asking for, but it's really worth to describe those features [in the changelog](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/CHANGELOG.md) at least (because not everyone is aware what others were asking for).

**Comment by gaearon** [comment]
@surgeboris When I added this changelog, I took twenty minutes to go through all the past PRs, remember the context behind them, and reconstruct it. I'm sorry that I missed one of them.

**Comment by gaearon** [comment]
Fixed changelog: https://github.com/facebook/react/commit/14e554b3103cc009c86f48ed927f2552649600a6.

I think we'll need to ask `react-navigation` to offer an alternative naming for this one to avoid breaking the convention. I'm sorry I didn't catch this earlier. The upside is that people seeing the `Effect` naming might be a bit confused anyway and try to pass the deps, so this is probably a net positive overall.

**Comment by gaearon** [comment]
We're going to revert this heuristic, so no changes necessary to React Navigation.

**Comment by gaearon** [comment]
Removed in `eslint-plugin-react-hooks@4.0.3`.

**Comment by leethree** [comment]
@gaearon thanks!
