### ISSUE TITLE
Bug: react-hooks/exhaustive-deps lint rule not working as expected

### ISSUE THREAD

**Issue by Attrash-Islam** [facebook/react#18882]
This issue is related to the `react-hooks/exhaustive-deps` not detecting a reasonable case of warnings regarding missing dependencies.

![image](https://user-images.githubusercontent.com/7091543/81495325-3049c480-92b8-11ea-8d3f-cb2133b5c78c.png)

The App contains two Children (One is the "increment" button where clicking on it will increment the value and the other child have an alert button to show the current value) while showing the current value also in the Parent component.

React version: 16.12.0

## Steps To Reproduce

1. Go to the CodeSandbox below.
2. Click on "increment" button to update the value multiple times.
3. Click on the "Alert Current Value" to alert the recent value from the context.

Link to code example:
https://codesandbox.io/s/react-fp-context-usecallback-deps-zsoet?file=/src/Child2.js

## The current behavior

1- `react-hooks/exhaustive-deps` don't report a missing dependencies.
![image](https://user-images.githubusercontent.com/7091543/81495376-99c9d300-92b8-11ea-8ed1-5afb62434f95.png)

2- The alerted value is the initial value (0) because of the stale closure even when being updated.

To solve this you need to add the missing dependency as so:

![image](https://user-images.githubusercontent.com/7091543/81495396-c2ea6380-92b8-11ea-8889-bbdbd3b09cf8.png)

The code will work but the lint rule wouldn't be happy to push "unnecessary" dependency as it claims!

## The expected behavior

To show warning when this dependency is missing in such a reasonable case.

**Comment by vkurchatkin** [comment]
The warning is correct: useAlert is a custom hook and context is an external value, so it is not a valid dependency

**Comment by Attrash-Islam** [comment]
@vkurchatkin  But how do you explain that the code sample proves the opposite?

**Comment by vkurchatkin** [comment]
It doesn't really prove anything. Your code happens to work, but ESLint analyses code in isolation.

**Comment by vkurchatkin** [comment]
Here is a simple example:

This is fine, obviously:
```js
const foo = 1;

useEffect(() => {}, [foo]);
```

But this is not:

```js
  const foo = 1;

  function useFoo() {
    useEffect(() => {}, [foo]); // foo is external
  }

  useFoo();
```

Although at runtime they both do the same thing.

**Comment by Attrash-Islam** [comment]
@vkurchatkin So why not extending the deps to consider other values? The `context` in my example can change and update. You can think of it as redux store based on Context.

**Comment by vkurchatkin** [comment]
> why not extending the deps to consider other values

Because there is no good way to know, whether a value is "reactive" other than using conventions.
Current conventions are (simplified):
  - A reactive value is a Component property, an argument of a hook or a local variable inside a hook or component;
  - A component is a function with capitalised name
 -  A hook is a function that starts with `use`

mapState is neither a hook nor a component, hence `context` is not reactive.

**Comment by Attrash-Islam** [comment]
Thanks! That was helpful.. Can I do any trick in naming to make it work? Names doesn't really matter to me if it works! 🙏🏻

**Comment by vkurchatkin** [comment]
If you just want to trick eslint, use `eslint-disable-next-line` directive. But you are really just not using hooks correctly

**Comment by Attrash-Islam** [comment]
This is exactly what I can but won't be willing to do 😢

**Comment by Attrash-Islam** [comment]
Thanks a lot @vkurchatkin , Really appreciate the help 🙏 
I changed it as so and it's working now:

![image](https://user-images.githubusercontent.com/7091543/81536623-9005a580-9374-11ea-80c9-5083d910932a.png)

**Comment by vkurchatkin** [comment]
Well, this looks like a normal hook to me, except for the part where you alias `alert` as `userAlert`. `useAlert` implies that it is a hook, which it isn't.

**Comment by Attrash-Islam** [comment]
Yeah.. Done that by mistake and removed it! You're awesome man, Thanks a lot! ❤️  @vkurchatkin
