### ISSUE TITLE
jsx --watch doesn't autogenerate after a file change

### ISSUE THREAD

**Issue by sir-pinecone** [facebook/react#1890]
Versions:
* OS X - 10.9.2
* Node - 0.10.29
* jsx - 0.11.0
* shell is zsh

I set the destination and source directory to be the same: `jsx -x jsx -w app/js/components app/js/components`. This builds the initial files but changes to the source are ignored. I tried changing the destination to a different dir, but that didn't fix it.

**Comment by jimfb** [comment]
`jsx --watch` doesn't exist anymore.  The transformer has been replaced by babel.
