### ISSUE TITLE
Bug: onSubmit doesn't contains an event param

### ISSUE THREAD

**Issue by EnetoJara** [facebook/react#18905]
I was reading your documentation https://reactjs.org/docs/forms.html#controlled-components
and I tried this example
```javascript
class FlavorForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {value: 'coconut'};
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(event) {    this.setState({value: event.target.value});  }
  handleSubmit(event) {
    alert('Your favorite flavor is: ' + this.state.value);
    event.preventDefault();
  }

  render() {
    return (
      <form onSubmit={this.handleSubmit}>
        <label>
          Pick your favorite flavor:
          <select value={this.state.value} onChange={this.handleChange}>            <option value="grapefruit">Grapefruit</option>
            <option value="lime">Lime</option>
            <option value="coconut">Coconut</option>
            <option value="mango">Mango</option>
          </select>
        </label>
        <input type="submit" value="Submit" />
      </form>
    );
  }
}
```
but I was getting a `cannot read property preventDefault of undefined.
I almost go nuts, but then I open your codepen and I got this
![image](https://user-images.githubusercontent.com/24560394/81811046-a2552000-94e9-11ea-8857-0c3e05ba6806.png)

![image](https://user-images.githubusercontent.com/24560394/81811258-f829c800-94e9-11ea-83ef-4886fff59de3.png)

so then I realize it was a bug.
React version: `16.13.1` the one on the docs

## Steps To Reproduce

1. follow your docs up to this point https://reactjs.org/docs/forms.html#the-textarea-tag
2. copy the snipped with the `<form onSubmit={this.handleSubmit}>`
3.- run it

Link to code example:
 [NameForm](https://reactjs.org/docs/forms.html#controlled-components) class component
[Codepen](https://codepen.io/gaearon/pen/JbbEzX?editors=0010)

## The current behavior
cannot read property preventDefault of null
## The expected behavior
to have an event param as your docs said

**Comment by denisglindep** [comment]
What browser do you use? I can't reproduce it with browser, and your `codepen` works fine; @EnetoJara

**Comment by EnetoJara** [comment]
chrome: 
![image](https://user-images.githubusercontent.com/24560394/81843176-d98bf700-9512-11ea-83fa-92084ad63081.png)

firefox: 
![image](https://user-images.githubusercontent.com/24560394/81843234-edcff400-9512-11ea-9b50-b7fabe5fe71d.png)

SO:
![image](https://user-images.githubusercontent.com/24560394/81843312-0e984980-9513-11ea-8ab1-6d13fa00b5dd.png)

React
![image](https://user-images.githubusercontent.com/24560394/81843437-35ef1680-9513-11ea-8aa1-dd56cf4320e2.png)

**Comment by EnetoJara** [comment]
CODE:

**Comment by EnetoJara** [comment]
sorry wrong codepen https://codepen.io/gaearon/pen/VmmPgp?editors=0010

![image](https://user-images.githubusercontent.com/24560394/81844650-03461d80-9515-11ea-8420-20f5801095e9.png)

Aparently it only happens when you console.log it, due to the fact that console.log is async, but then were the closure at ?

**Comment by denisglindep** [comment]
@EnetoJara You've added the same codepen :-)
I found that you try to log execution of `e.preventDefault()` but this function returns nothing, and that is the reason why you have `undefined` in the console.
You can do the same inside a chrome-devtools-console:
* just type `console.log('test');` and you would see, that `log` method responds with `undefined` also.
So, I think this question isn't connected with React :-)

**Comment by EnetoJara** [comment]
That's why I said you guys can close this
