### ISSUE TITLE
React developer tool doesn't show in Chromium based Edge in Windows

### ISSUE THREAD

**Issue by ulagapandi2upms** [facebook/react#18910]
I've using chromium-based Microsoft edge. This react developer tool doesn't show in profiler page.
I can't find react developer tool in my browser

**Comment by kunukn** [comment]
I can find it here. I used Edge version 81.

![image](https://user-images.githubusercontent.com/3199603/82207020-7bdc1e00-9909-11ea-8a6d-2c07007e1cfe.png)

**Comment by bvaughn** [comment]
First, make sure you've installed the Edge build of the extension:
https://microsoftedge.microsoft.com/addons/detail/gpphkfbcpidddadnkolkpfckpihlkkil

Then visit any website that uses React (like [www.reactjs.org](https://reactjs.org/)) and tow extension tabs should be available in your DevTools: "⚛️ Components" and "⚛️ Profiler".
