### ISSUE TITLE
Bug: using useCallback and useEffect at the same time messed my ref

### ISSUE THREAD

**Issue by robertwt7** [facebook/react#18915]
Hey Guys,

I created a [SignaturePad](https://github.com/agilgur5/react-signature-canvas) for my application that will pass the value later on to Formik. What I'm trying to do is to get the data from canvas and save it to my state using ref. `toData()` function returns array of points from the signature canvas. 
`handleClear` is to clear the canvas.

Related libraries in the project:
```
		"react": "^16.12.0",
		"react-bootstrap": "1.0.0-beta.16",
		"react-dom": "^16.12.0",
		"@material-ui/core": "^4.9.13",
```

I'm still new and trying to convert my whole application using hooks so I apologise if this is not a bug.

**Problem 1:**

I have some issue with using the `useEffect` and `useCallback` function of react. Previously before I add useEffect, `handleClear` function works just fine. However after I added useEffect, `sigPad` refs always returns null in handleClear. 

**Problem 2:**

I realised after I removed the `[sigPad]` at `handleClear` I am able to receive the ref again. Which part of my code re-renders and how come useCallback does not realise that sigPad is changing from null to the correct ref?

**Problematic code:**

```
export function Signature() {
  let sigPad = useRef(null);
  const [sig, setSig] = useState("");
  const classes = formStyles();

  useEffect(() => {
    console.log(sigPad);
    setSig(sigPad.toData());
    console.log(sigPad);
  }, [sig]);
  const handleClear = useCallback(() => {
    console.log(sigPad);
    if (sigPad) sigPad.clear();
  }, [sigPad]);

  return (
    <div className="row">
      <Grid spacing={3} container>
        <Grid item xs={12}>
          <h3 className="text-bold">Signature</h3>
        </Grid>
        <Grid item xs={12}>
          <div className="sigCanvas">
            <SignatureCanvas
              penColor="black"
              canvasProps={{ className: "sigPad" }}
              ref={ref => {
                sigPad = ref;
              }}
            />
          </div>
        </Grid>
        <Grid item xs={3}>
          <Button
            variant="contained"
            component="label"
            className={classes.instructions}
            onClick={handleClear}
          >
            Clear
          </Button>
        </Grid>
        <Grid item xs={3}>
          <Button
            component="label"
            variant="contained"
            className={classes.instructions}
          >
            Save
          </Button>
        </Grid>
      </Grid>
    </div>
  );
}

```

**Current Fix:**

```
  const handleClear = useCallback(() => {
    console.log(sigPad);
    if (sigPad) sigPad.clear();
  });
```

**Note**: Before I add useEffect I don't have to remove the `[sigPad]` at my callback

**Comment by sophiebits** [comment]
You may want to review the useRef docs again. To store data in a ref across renders, you should assign to the .current property (i.e. `sigPad.current = ...` not `sigPad = ...`). You likely want just `ref={sigPad}` on SignatureCanvas which does essentially the same thing. Then read from sigPad.current to get the actual value (in your effect and clear handler).

**Comment by Bluefitdev** [comment]
Ah understood, thanks!
