### ISSUE TITLE
Bug: State of hooks not refreshing automatically in React DevTools

### ISSUE THREAD

**Issue by mysticaltech** [facebook/react#18929]
I am using useContext and useReducer. When I inspect the ContextProvider in DevTools I see the state correctly. But when it changes via a reducer, it is not automatically refreshed in the DevTools, I must select another node and come back to the ContextProvider for it to show the correctly updated value.

So the state is really refreshed, it's just the DevTools that is not picking it up automatically like for normal state objects.

DevTools version 4.6.0-6cceaeb67

![May-15-2020 12-44-31](https://user-images.githubusercontent.com/518555/82042345-045c8380-96aa-11ea-8b4b-40a164e032cb.gif)

**Comment by mysticaltech** [comment]
Turns out it was the useReducer hook causing this, working with useState instead solved the issue. This hook does not seem very stable to me! So for complex projects, redux remains is a must.

**Comment by bvaughn** [comment]
> Turns out it was the useReducer hook causing this, working with useState instead solved the issue. This hook does not seem very stable to me! So for complex projects, redux remains is a must.

This does not sound like the right conclusion. :smile:

I'm not sure I understand what's going on in the video you linked, but it looks like you're *editing* the value of the reducer's state and then just waiting to see if your edit gets erased? Local edits are expected to stay around unless you explicitly cancel them (e.g. Escape key).

Can you point me at a Code Sandbox that reproduces this problem please?

**Comment by mysticaltech** [comment]
Sorry, the code sandbox thing is too big an effort, but basically, when I changed useReducer to useState it started working normally again, i.e. instant refresh as it's supposed to. So I will close the issue on my end. If someone else encounters this issue, at least they can find it on Google and reopen it. Thanks and keep up the good work.
