### ISSUE TITLE
Bug: eslint(react-hooks/exhaustive-deps) detection error

### ISSUE THREAD

**Issue by andyyxw** [facebook/react#18922]
React version: 16.8.6

## Steps To Reproduce

1. I used a `current` prop of a variable(not a `ref`) in `useMemo`

Link to code example:
![F46EFE66DEC68D03AE3EA7F9A8758D40](https://user-images.githubusercontent.com/41931722/81905690-a3747300-95f7-11ea-9fea-d9d11221b75e.jpg)
![51C1374CBF1B25FD8C0099E28A689D95](https://user-images.githubusercontent.com/41931722/81905707-a8d1bd80-95f7-11ea-9f9c-3d2e44f2a4f7.jpg)

## The current behavior
The lint plugin prompt me to add the whole variable to dependence.
It cause the momized value extra calculation.

## The expected behavior
Only add `variable.current` to dependence

**Comment by rachelnabors** [comment]
Hi there! There is no way for React to tell whether something is a `ref` or not. We use `.current` as a convention. The benefit of the convention outweighs the occasional false positives, like in this example. In this case we advise you rename the `current` property to something more descriptive, like `currentPage`, which would make it obvious both to the linter and to any humans who might be reading your code that this isn't a `ref`.
