### ISSUE TITLE
Feature proposal: let class component setState second param callback always give the latest state

### ISSUE THREAD

**Issue by fantasticsoul** [facebook/react#18938]
## Context
I know setState first param can be a updater
```
(state, props)=> stateChanged;
```
but why not the second callback param can not supply the latest state in its param list.
```
this.setState({msg:'new msg'}, (newState)=>{
    console.log(newState);// let user no need to write this.state here
})
```

[Link to code example](https://codesandbox.io/s/winter-monad-9wbu8?file=/src/App.js:51-410):

```js
class Test extends React.Component{
  state = {msg:'msg'}
  changeMsg = ()=>{
    this.setState({msg:Date.now()}, (newState)=>{
      console.log(newState);// undefined
      console.log(this.state);// latest state
    });
  }
  render(){
    const msg = this.state.msg;
    return (
      <div>{msg} <input value={msg} onChange={this.changeMsg} /></div>
    );
  }
}
```

## The current behavior
the newState is undefined

## The expected behavior
the newState is the latest state

**Comment by sophiebits** [comment]
React tends to not add more than one way to do something if the existing way is already clear and works well. I would say that this.state is quite straightforward and mirrors how you would always access state in a class component (so it’s one less thing to learn). One other minor issue I see with your proposal is that it would make the two arguments easier to confuse as both would take state then. Lastly, I would look to Hooks for where React is primarily evolving toward in the future.

Thanks for submitting this idea but it’s not likely to be implemented, so I’m going to close this.

**Comment by fantasticsoul** [comment]
thank you for your reply,  I personally think if react give the latest state in second callback param , user can do some async task write elegant writing, just like below:

```js
const recordMsgChanged = newState =>{
     api.uploadEvent({event:'msgChanged', msg: newState.msg });
}

// for class
class Foo extends Component{
    changeMessage = ()=>{
         this.setState({msg: 'msg'}, recordMsgChanged)
    }
}

// for function
function FooComp{
    const [msg, setMsg] = useState('');
    const changeMessage = (e)=>{
         setMsg(e.target.value, recordMsgChanged);
    }
}
```
Do you agree with me.
