### ISSUE TITLE
Bug: Event Capture may not work

### ISSUE THREAD

**Issue by JenniferFuBook** [facebook/react#18932]
In React document, it is stated that to register an event handler for the capture phase, append Capture to the event name. It works in normal case. But if the event's bubbling is stopped inside an iframe, the parent component will not be able to capture the event.

React version: 16.13.1

## Steps To Reproduce

1. Create an iframe that preventDefault after catch a click event.
2. From the parent component of the iframe, set the event handler for onClickCapture.
3. The event handler is never called.

**Comment by gaearon** [comment]
This sounds like a consequence of how events currently worked — the capture phase is emulated in React. We're switching it over to actually using the capture phase — so this should resolve itself in React 17. Thank you for reporting.
