### ISSUE TITLE
DevTools: Uncaught error doesn't go away on page refresh

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#18935]
1. Wait for devtools to hit an error (eg: #18934).
2. Reload the page.

Expected: Devtools reinitializes cleanly.
Actual: Error is still there. Need to hide devtools, reload _again_, then show devtools to get it to behave.

DevTools version: 4.6.0-6cceaeb67

**Comment by bvaughn** [comment]
DevTools persists profiling data between page reloads, because it can be annoying for it to disappear if e.g. HMR causes the page to reload while you were looking at a trace. In the case of, #18934, it sounds like something about your profiling data is corrupt. (Don't know what since I don't know how to repro the issue.)

**Comment by sophiebits** [comment]
I'm specifically talking about the case where the devtools break due to an uncaught error. A working "Reload" on that error page would also be OK.

**Comment by bvaughn** [comment]
Sure, understood. I was just pointing out that DevTools (the extension) stays around in some form between page loads. The React app itself actually unmounts and remounts:
https://github.com/facebook/react/blob/23309eb386777ee229cfb6f9b70fcb7c7123388b/packages/react-devtools-extensions/src/main.js#L350-L362

...but with saved profiling data:
https://github.com/facebook/react/blob/23309eb386777ee229cfb6f9b70fcb7c7123388b/packages/react-devtools-extensions/src/main.js#L135-L141

So my thought was that the error must be in the data itself somehow- such that the newly mounted DevTools is re-showing the same error.

**Comment by bvaughn** [comment]
@sophiebits If this happens again, I wonder if you'd be able to snag the `profilingData` data by setting a breakpoint or something and sending it my way so I can reproduce the particular problem.
