### ISSUE TITLE
Bug: nested setState inside setTimeout/Promise triggered multiple times

### ISSUE THREAD

**Issue by MarvelSQ** [facebook/react#18949]
**setState** inside **another setState** which called in setTimeout/Promise will recalc multiple times

React version: 16.13.1

## Steps To Reproduce

```js
const App = ()=>{
  const [a, setA] = useState('');
  const [b, setB] = useState('');

  useEffect(()=>{
    console.log('didmount');
    setTimeout(()=>{
      setA((a)=>{
        console.log('update a');
        setB('next B');
        return a + 'next';
      });
    },1000);
  },[]);
  
  return <div>{a}{b}</div>
}
```
## The current behavior
log
```
didmount
// 1 sec laster
update a
update a
```

## The expected behavior
log
```
didmount
// 1 sec later
update a
```

## Question
**is this a bug or should i avoid update state inside other setState?**

**Comment by jtl385** [comment]
![](http://localhost:8090/github/images/mini-trello-icon.png) [test](http://loopback.planatee.com:3000/c/twbddXeX/42-test)

**Comment by Eddie-CooRo** [comment]
Here is the codesandbox link for the issue:
https://codesandbox.io/s/dawn-dawn-56tji

BTW, I believe that the setState updater function is considered a reducer and therefore should be pure.

**Comment by MarvelSQ** [comment]
I know this action is quite weird, but I think it's easy to update relative state without adding state in callback deps.

**Comment by Eddie-CooRo** [comment]
Not only wierd
But wrong and not supported by React. Specially in concurrent mode.
BTW the double execution of the reducer, may be a sanity check done by React in development mode to ensure that you don't use the callback for anything other than returning the new value.
I'm aware that React does this for the render function to ensure you don't have side effects in the render body. But only in development Strict mode. I haven't checked the reducer function.
Check the issue in production build and see if it still gets called multiple times or not

**Comment by gaearon** [comment]
It is not supported to set timeouts (which then may set state) from inside an updater function. Updater functions are expected to be pure. React considers it safe to call them at any time, as many times as it might need to.
