### ISSUE TITLE
Feature Request: <input type="textarea" .../> 

### ISSUE THREAD

**Issue by JasonWoof** [facebook/react#18940]
I'm delighted that you made it so `<textarea>` can take `value=` and `defaultValue=...` but what I really want is `<input type="textarea">`.

That would make this use case more fun:

    <input type={field.type} ...

No explanation necessary if you decide not to implement this. I've already made a wrapper class to solve my problem at hand.

**Comment by kunukn** [comment]
I think React follow the HTML spec. regarding the input types.
https://html.spec.whatwg.org/multipage/input.html#attr-input-type

There is no such thing as `<input type="textarea"`

**Comment by JasonWoof** [comment]
As I pointed out in my original request, `<textarea>` doesn't follow the HTML spec, instead it does something that makes more sense. Why not do the thing that makes a lot of sense and use `<input type="textarea">`?
