### ISSUE TITLE
Bug: useState's setState may change your state to 'undefined'

### ISSUE THREAD

**Issue by LXSMNSYC** [facebook/react#18943]
I was updating my library which mostly revolves around the use of hooks.

This line: https://github.com/LXSMNSYC/react-scoped-model/blob/1c41a667aed66dedf8b8da2164a00eda0ccb0b3e/src/index.tsx#L183

```tsx
setState((prev) => (Object.is(prev, value) ? prev : value));
```

even though redundant according to the Hooks API:

> Bailing out of a state update

> If you update a State Hook to the same value as the current state, React will bail out without rendering the children or firing effects. (React uses the Object.is comparison algorithm.)

However, replacing the line with

```tsx
setState(selector(next));
```

results into the state having an `undefined` value.

Tests with the first line:
<img width="847" alt="Screen Shot 2020-05-18 at 2 41 59 PM" src="https://user-images.githubusercontent.com/4783372/82181871-ebf0a100-9915-11ea-9217-62e2cf681b92.png">

Tests with the second line:
<img width="845" alt="Screen Shot 2020-05-18 at 2 42 56 PM" src="https://user-images.githubusercontent.com/4783372/82181882-f01cbe80-9915-11ea-8828-1fbee756a37f.png">

Notice the `Current state` logs with 'undefined' value, which is written as:

```tsx
console.log('Current state:', state, selector(notifier.value));
```

Other information:
- In the tests, increment and decrement are component-level constants (useCallback with zero-dependencies), creating a stable reference.
- During the tests, only those lines changed in the source code (which I was expecting both of the said code to run similarly given that setState can bail out of updates.)
- It was also impossible, logic-wise, for the selector to return 'undefined', as proven by the change of lines.

**Comment by vkurchatkin** [comment]
It seems that your state is a function. In that case, `setState(state)` won't work as expected
