### ISSUE TITLE
Can we get back _wrapperState.initialValue for select?

### ISSUE THREAD

**Issue by saikatstutorial** [facebook/react#18968]
I'm trying to write a function to track if there is any unsaved change in the form. React internally tracks initialChecked or initialValue in wrapper state. But this property is not available for "select" elements. DOM's defaultSelected is always having latest value hence cannot use that.

https://github.com/facebook/react/blob/22f7663f14f12ebd6174292931e94d2b352cf666/packages/react-dom/src/client/ReactDOMSelect.js#L23

For input element initialValue is present
https://github.com/facebook/react/blob/8b3b5c35245b3aa0b2802b51856fe9dad5bcb671/packages/react-dom/src/client/ReactDOMInput.js#L25

This is what I am trying to do:
```
const elementIsDirty = (element) => {
    let type = element.type;
    if (type === "checkbox" || type === "radio") {
        if (element.checked !== element._wrapperState.initialChecked) {
            return true;
        }
    } else if (["text", "textarea", "email", "number", "password", "url"].includes(type)) {
        if (element.value !== element._wrapperState.initialValue) {
            return true;
        }
    } else if (type === "select-one" || type === "select-multiple") {
        for (let i = 0; i < element.options.length; i++) {
            if (element.options[i].selected !== element.options[i].defaultSelected) {
                return true;
            }
        }
    }
    return false;
};
```

**Comment by bvaughn** [comment]
Any attributes that React uses that begin with "_" are not meant to be public API and should not be depended upon (because they're likely to change without notice).
