### ISSUE TITLE
Bug: SetState in hooks useState suggests adding a callback after an update

### ISSUE THREAD

**Issue by zhuSass** [facebook/react#18960]
```
   const [ keyword, setKeyword] = useState('');
    const clickKeyWordTags = function() {
        setKeyword('change will value');
        searchHandle();
    };
    const searchHandle = async function() {
        const params:SearchConditionType = {
            source: actionType,
            keyword: keyword,
        };
        const data = await ShuYuanSdk.getSearchInfo(params);
        setDataList(data);
        // console.log('searchHandle--------', keyword);
    };
```
Log 'keyword' is' ', not 'change will value' after update, the feature of this hooks is related, can you provide an updated API

**Comment by HiMrHu** [comment]
you can try this
```tsx
  const [ keyword, setKeyword] = useState('');
    const clickKeyWordTags = function() {
        setKeyword('change will value');
    };
    const searchHandle = async function(keyword) {
        const params:SearchConditionType = {
            source: actionType,
            keyword: keyword,
        };
        const data = await ShuYuanSdk.getSearchInfo(params);
        setDataList(data);
        // console.log('searchHandle--------', keyword);
    };
  React.useEffect(() => {
         searchHandle(keyword);
  }, [keyword])
```

**Comment by zhuSass** [comment]
@HiMrHu Thank you very much for your reply， UseEffect does not meet my requirements for the scene. I need the user to click on the searchHandle. UseEffect will cause the searchHandle to be triggered whenever the data changes

**Comment by HiMrHu** [comment]
> @HiMrHu Thank you very much for your reply， UseEffect does not meet my requirements for the scene. I need the user to click on the searchHandle. UseEffect will cause the searchHandle to be triggered whenever the data changes

you can create your hooks,

```tsx
function myselfHooks(initialState,callback) {
 const [data, setData] = React.useState(initialState)
React.useEffect(callback)
 return [data, setData]
}
```

```tsx
    const searchHandle = async function(keyword) {
        const params:SearchConditionType = {
            source: actionType,
            keyword: keyword,
        };
        const data = await ShuYuanSdk.getSearchInfo(params);
        setDataList(data);
        // console.log('searchHandle--------', keyword);
    };
 const [ keyword, setKeyword] = myselfHooks('',searchHandle );
const [other, setOther] = myselfHooks("", otherHandle)
const [value, setValue] = myselfHooks('', searchHandle)
    const clickKeyWordTags = function() {
        setKeyword('change will value');
    };
  const otherHandle = () => {
 // do something
 }


```

**Comment by zhuSass** [comment]
> > @HiMrHu Thank you very much for your reply， UseEffect does not meet my requirements for the scene. I need the user to click on the searchHandle. UseEffect will cause the searchHandle to be triggered whenever the data changes
> 
> you can create your hooks,
> 
> ```tsx
> function myselfHooks(initialState,callback) {
>  const [data, setData] = React.useState(initialState)
> React.useEffect(callback,[data])
>  return [data, setData]
> }
> ```
> 
> ```tsx
> const [keyword, setKeyword] = myselfHooks("", searchHandle);
> const [value, setValue] = myselfHooks("", searchHandle);
> const searchHandle = async function (keyword) {
>   const params: SearchConditionType = {
>     source: actionType,
>     keyword: keyword,
>   };
>   const data = await ShuYuanSdk.getSearchInfo(params);
>   setDataList(data);
>   // console.log('searchHandle--------', keyword);
> };
> 
> const clickKeyWordTags = function () {
>   setKeyword("change will value");
> };
> const handleChangeWord = () => {
>  setValue("change other value")
> }
> ```
It's essentially a data change that triggers the searchHandle, and I don't want it to be triggered automatically, like if I have a search box and I don't want the searchHandle to happen when I type in it, I want it to happen when the user clicks a button进入翻译页面

**Comment by illuminist** [comment]
@zhuSass You initially had `searchHandle` to be called on `clickKeyWordTags` which mean you wanted it to be triggered when data changed. Isn't that what you want?

**Comment by zhuSass** [comment]
> @zhuSass You initially had `searchHandle` to be called on `clickKeyWordTags` which mean you wanted it to be triggered when data changed. Isn't that what you want?

'keyword' is bound in 'input'. If 'watch' is used, it means that 'searchHandle' will also occur when the user inputs. I don't want such a phenomenon to happen, but I expect the user to click on the search trigger

**Comment by illuminist** [comment]
> 'keyword' is bound in 'input'. If 'watch' is used, it means that 'searchHandle' will also occur when the user inputs. I don't want such a phenomenon to happen, but I expect the user to click on the search trigger

If user is click on `searchHandle` that's mean the click event will happen after `clickKeyWordTags` event and that should updated `keyword` state correctly. Which mean you should not put `searchHandle` inside of  `clickKeyWordTags` but rather on separated user event.

And if you want to handle `watch` where search handle is called after `keyword` change. You just need `useEffect` to be called with `watch` as condition

```
React.useEffect(() => {
    if (watch) searchHandle();
})
```

**Comment by zhuSass** [comment]
> > 'keyword' is bound in 'input'. If 'watch' is used, it means that 'searchHandle' will also occur when the user inputs. I don't want such a phenomenon to happen, but I expect the user to click on the search trigger
> 
> If user is click on `searchHandle` that's mean the click event will happen after `clickKeyWordTags` event and that should updated `keyword` state correctly. Which mean you should not put `searchHandle` inside of `clickKeyWordTags` but rather on separated user event.
> 
> And if you want to handle `watch` where search handle is called after `keyword` change. You just need `useEffect` to be called with `watch` as condition
> 
> ```
> React.useEffect(() => {
>     if (watch) searchHandle();
> })
> ```

是有取巧的方法实现我的场景
```
    useEffect(() => {
        if (!focusStatus) {
            searchHandle();
        }
    }, [actionType, keyword]);
```
This prevents the user from actively searching in the 'focus' state, but I don't want to do that extra, expecting the values to be up to date in the functions defined in' hooks'

**Comment by theboxer** [comment]
If you don't want to go with the `useEffect` path, you can try `useRef` for storing the keyword, instead of `useState`.

```js
const keyword = useRef('');
const clickKeyWordTags = function() {
    keyword.current = 'change will value';
    searchHandle();
};

const searchHandle = async function() {
    const params:SearchConditionType = {
        source: actionType,
        keyword: keyword.current,
    };
        
    const data = await ShuYuanSdk.getSearchInfo(params);
    setDataList(data);
    // console.log('searchHandle--------', keyword.current);
};
```
