### ISSUE TITLE
Expose mixin method on created Classes

### ISSUE THREAD

**Issue by jquense** [facebook/react#1896]
It would be helpful if the `mixSpecIntoComponent` and its static variant were accessible on the returned descriptor from `createClass()`. That way components need not be defined all at once, giving someone the ability to mixin into someone else's component if they wish. 

In my limited experience this stuff is also really helpful for using React in a larger app framework context. For instance, dependency injection in an ember-esque  way would be really easy, allowing me to inject props/methods, on a type/classes basis in stead of the current (albeit undocumented) global injection functionality in react now.

It also just seems like an unnecessary restriction, not in keeping with the dynamic nature of the language. Why not embrace the prototypal nature of js, and bless redefining/reopening 'Classes'?

my own rudimentary experiments with this has gone well enough, and it fits nicely with the composition-focused abstractions in React. Admittedly, not knowing what the ultimate plan for the `ReactDescriptor` makes it hard to guess at possible conflicts with this approach. One escape hatch might be the additional ability to seal classes?

Is their a strong reason fro not exposing these methods on the descriptor?

**Comment by spicyj** [comment]
We don't plan to do this, but with ES6 class support you can make your classes however you like.

**Comment by dendril** [comment]
@spicyj Is there a place to read the final direction about this topic? I like how the current code handle the components composition, and exporting `mixSpecIntoComponent` will allows me to extend components in the same way as React does using nowadays code. Anyway I could copy/paste the code in a utility file for my projects, but I want to know how are actually the next steps about this.

Thanks a lot for your time!

**Comment by spicyj** [comment]
We're doing our best to simplify the React core as much as possible, which in this case includes slowly moving away from React.createClass and towards ES6 classes, so we're not planning to add more helpers for making classes. As you say, you can easily reimplement the same functionality yourself if you need it.

**Comment by brigand** [comment]
@dendril, an [example of reimplementing mixins outside of react](https://github.com/brigand/react-mixin).

Basically if you have a constructor with a prototype, you can do pretty much anything you want to it. Whether that's wrapping it in another component, extending from it, mixins, traits, or anything else.

There was another issue that hinted towards wrapping ("high order components") is the way to go, and in my experience, it works very well.

**Comment by troutowicz** [comment]
@dendril @jquense Another option would be to move away from classes and their current limitations entirely. Harness the power and flexibility of prototypal inheritance with the the React version of @ericelliott's [stampit](https://github.com/ericelliott/stampit), [react-stampit](https://github.com/troutowicz/react-stampit).

**Comment by ericelliott** [comment]
I am also working on stamp-based tooling for React components (currently experimenting in a private repo). It looks very promising. As long as React maintains support for factory functions and simple objects and doesn't do anything that explicitly requires the `class` keyword, we'll continue to have many options available to compose and extend the functionality of React components without a specialized mixin method.

Right now, it's as simple as using `Object.assign()`, lodash/object/assign, etc...

**Comment by dendril** [comment]
@ericelliott I've been checking stampit and want to switch completely to it after you release v2 because I don't want to include mout and lodash in my projects. I saw a good progress in the migration, hope that could be released soon :smile:

Thanks everyone for the feedback!
