### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_0_react__.createContext is not a function

### ISSUE THREAD

**Issue by aiyudeleng** [facebook/react#18977]
![image](https://user-images.githubusercontent.com/31436484/82631119-56ac2000-9c27-11ea-80df-4677e31dc4a7.png)

TypeError: __WEBPACK_IMPORTED_MODULE_0_react__.createContext is not a function
./node_modules/rc-field-form/es/FieldContext.js
E:/Workspace/Vscode-workspace/XXL/luna-company-web/node_modules/rc-field-form/es/FieldContext.js:9
   6 |   warning(false, 'Can not find FormContext. Please make sure you wrap Field under Form.');
   7 | };
   8 | 
>  9 | var Context = React.createContext({
  10 |   getFieldValue: warningFunc,
  11 |   getFieldsValue: warningFunc,
  12 |   getFieldError: warningFunc,
View compiled
__webpack_require__
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
./node_modules/rc-field-form/es/Field.js
E:/Workspace/Vscode-workspace/XXL/luna-company-web/node_modules/rc-field-form/es/Field.js:1
> 1 | import _objectWithoutProperties from "@babel/runtime/helpers/esm/objectWithoutProperties";
  2 | import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";
  3 | import _toConsumableArray from "@babel/runtime/helpers/esm/toConsumableArray";
  4 | import _classCallCheck from "@babel/runtime/helpers/esm/classCallCheck";
View compiled
__webpack_require__
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
./node_modules/rc-field-form/es/index.js
E:/Workspace/Vscode-workspace/XXL/luna-company-web/node_modules/rc-field-form/es/index.js:1
> 1 | import * as React from 'react';
  2 | import Field from './Field';
  3 | import List from './List';
  4 | import useForm from './useForm';
View compiled
__webpack_require__
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
./node_modules/antd/lib/config-provider/index.js
E:/Workspace/Vscode-workspace/XXL/luna-company-web/node_modules/antd/lib/config-provider/index.js:22
  19 | 
  20 | var React = _interopRequireWildcard(require("react"));
  21 | 
> 22 | var _rcFieldForm = require("rc-field-form");
  23 | 
  24 | var _localeProvider = _interopRequireWildcard(require("../locale-provider"));
  25 | 
View compiled
__webpack_require__
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
./src/index.js
http://localhost:3001/static/js/bundle.js:483606:83
__webpack_require__
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
0
http://localhost:3001/static/js/bundle.js:484925:18
__webpack_require__
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
(anonymous function)
E:/Workspace/Vscode-workspace/XXL/luna-company-web/webpack/bootstrap ce28bf44d4ece074143e:724
  721 | __webpack_require__.h = function() { return hotCurrentHash; };
  722 | 
  723 | // Load entry module and return exports
> 724 | return hotCreateRequire(0)(__webpack_require__.s = 0);
  725 | 
  726 |

**Comment by HiMrHu** [comment]
the context API add in React 16.30, but you use Reaact 16.0,  there is the [changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#react-10)

**Comment by aiyudeleng** [comment]
> the context API add in React 16.3, but you use Reaact 16.0, there is the [changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#react-10)

![image](https://user-images.githubusercontent.com/31436484/82640680-95e56b80-9c3d-11ea-8760-68b8476140fb.png)

**Comment by AviVahl** [comment]
You probably have more than one version of React in your project's `node_modules`.
Can be verified using: `npm ls react`

If an older version of React slipped in, that would explain the error.

If the project is using a lock file, make sure all resolutions of react/react-dom resolve to the same version. `npm upgrade react` and `npm upgrade react-dom` will probably do a better job at updating the lock file than `npm i`. Deleting the lock file an re-running `npm i` would also do the job, but it would also update resolutions of all packages (each to the latest version compatible with the request). Might result in other errors, if there was a breaking change somewhere that was released as patch/minor.

**Comment by aiyudeleng** [comment]
> You probably have more than one version of React in your project's `node_modules`.
> Can be verified using: `npm ls react`
> 
> If an older version of React slipped in, that would explain the error.
> 
> If the project is using a lock file, make sure all resolutions of react/react-dom resolve to the same version. `npm upgrade react` and `npm upgrade react-dom` will probably do a better job at updating the lock file than `npm i`. Deleting the lock file an re-running `npm i` would also do the job, but it would also update resolutions of all packages (each to the latest version compatible with the request). Might result in other errors, if there was a breaking change somewhere that was released as patch/minor.

Following your advice, I run the command: `npm ls react,` then the project running is OK! But in the file package.json , the react's version is still 16.0.0, but the react-dom is 16.12.0
![image](https://user-images.githubusercontent.com/31436484/82771779-b3018080-9e6f-11ea-98eb-553689317ee3.png)

**Comment by AviVahl** [comment]
`npm ls` should only print stuff, and does not change installed versions. It's probably some other command that you ran that fixed it.

The `package.json` file contains the semver request. `^16.0.0` basically means `16.x.x`, so it will give you the latest 16 release version when resolving.

Suggested read:
https://docs.npmjs.com/about-semantic-versioning
https://docs.npmjs.com/configuring-npm/package-locks.html

**Comment by aiyudeleng** [comment]
👍👍👍Thank you very much! You are so patient
