### ISSUE TITLE
Bug: Typing Fast into Controlled Input doesn't change value visually immediately

### ISSUE THREAD

**Issue by anatolzak** [facebook/react#18971]
I have a controlled input and when I type slowly, it updates the state and shows the current input value. However, when I start typing fast, I can see the input value updating in the DOM in the developer tools but the input becomes empty visually until I stop typing and then I can see the updated value visually too.

I have provided a gif where I start typing fast and you can see the value changing in the developer tools at the bottom of the screen but the input becomes blank when typing fast till I stop.

![bug](https://user-images.githubusercontent.com/53095479/82567798-8d7e2980-9b86-11ea-92b1-448872ac8777.gif)

React version: 16.13.1

## Steps To Reproduce

1. Create a control input
2. Start typing very fast

## The current behavior
When typing fast into a controlled input, the value of the input in the dev tools updated but the input becomes visually empty until I stop

## The expected behavior
When typing fast into a controlled input, the input should update visually.

**Comment by vkurchatkin** [comment]
There is no way to tell, unless you provide your code

**Comment by anatolzak** [comment]
I just created a react app that only has a controlled input and the issue doesn't occur there. It only occurs on big projects where the component has to render many many other components too.

**Comment by vkurchatkin** [comment]
Well, seems like the problem with your app then.

**Comment by anatolzak** [comment]
You are right about that! I did change the structure of the components and it helped a lot. 

But how do you explain that it would show the new updated value of the input in the dev tools after each state update but would make the input blank visually if you type really fast until you stop?

**Comment by vkurchatkin** [comment]
Well, I guess the devtools are able to observe these changes faster then your app can process them. That is surprising to me, but still unrelated to React.

**Comment by Xibai-Sike** [comment]
Did you enable mode 'concurrent'? In other words, there were some code like
`ReactDOM.createRoot(
  document.getElementById('root')
).render(<App />);`

**Comment by HiMrHu** [comment]
i write a [example](https://codesandbox.io/s/falling-currying-gkpb1?file=/src/index.js), but doesn't  reproduce your  problem . so can you provide a example ?

**Comment by anatolzak** [comment]
What caused my issue was that I had a component where I had a controlled input and then some table with rows that contain the value of the controlled input. Basically you could filter the rows of the table by typing something into the input. So then when you type into the input, the state would change and trigger a rerender that will rerender the input and the results. Something like [FontAwesome's icon-search page](https://fontawesome.com/icons?d=gallery). 

So I tried to run my app today, and I realized that what causes the issue is typing extremely fast (typing random letters really fast, as shown in the GIF) into the input, which is of course not a normal use case so there is no reason to worry about that. Plus, it is also understandable since the state updates constantly extremely fast so there is not enough time for the browser to show the updated state because then it updates again if you keep typing extremely fast. I tried to type pretty fast real words though and the issue didn't occur because it is really hard to type real words extremely fast.

One thing I could implement is either
1. managing the state of the input in a child component 
    - managing the input's value in its state and 
    - updating the state on each keystroke 
    - sending the value of the input if the user stopped typing for a second to the parent component whose job is to display the rows of the table that contain the input value.

or 

2. only setting an onChange event handler which then prevents the input from becoming blank when typing fast.

I chose option 2 because it is simple and it works well 🙂

I hope I was able to explain what the problem was, what was causing it and what my app's purpose was. Thank you for all your help!
