### ISSUE TITLE
My website is taking 6mb for loading which is very large.How to reduce this file size or can anybody suggest me any other solution?

### ISSUE THREAD

**Issue by Shawan1008** [facebook/react#18972]
I built a website using Node Js, Express, MongoDB, React Js and Next Js. Now the problem is when i load the website it take 5 to 6mb for loading which is very large. There are 3 files which is loaded with the website that take almost 1mb each file.Screenshot is given below indicating those files. I want to know is there any way to reduce this file size or can anybody suggest me any other option to reduce the website loading size?
![Problem1](https://user-images.githubusercontent.com/48651927/82580108-5ae72780-9bac-11ea-888e-da03724a9942.jpeg)

**Comment by gaearon** [comment]
Maybe something like this could help?
https://nextjs.org/docs/advanced-features/dynamic-import

I would suggest asking support on Next forums. We use this issue tracker for bugs in React.

**Comment by Shawan1008** [comment]
Can you please explain why the issue that is raised by me closed?
