### ISSUE TITLE
Bug: lazy loading not work on concurrent mode 0.0.0-experimental-e5d06e34b

### ISSUE THREAD

**Issue by hosseinmd** [facebook/react#18978]
React version: 0.0.0-experimental-e5d06e34b
React-native: 0.62

## Steps To Reproduce

1. below code work well
```js
import Routes from './Routes';

const App = () => {
  const resource = useState(() => wrapPromise(initialize()))[0];

  return (
     <SuspenseList tail="collapsed" revealOrder="forwards">
        <Suspense fallback={<View />}>
             <Initializer {...{resource}} />
        </Suspense>
        <Suspense fallback={<View />}>
             <Routes />
        </Suspense>
     </SuspenseList>       
  );
};
```
2. but when change routes to lazy mode that won't work on react-native
```js
const Routes = React.lazy(() => {
   return import('./Routes.js');
});
```

## The current behavior
React.lazy don't work  in this version of experimental

## The expected behavior
That work well in 0.0.0-experimental-5faf377df
When I use inline import instead that work well

**Comment by Eddie-CooRo** [comment]
Can you please confirm that this also happens in the latest experimental release?
its `0.0.0-experimental-33c3af284`
Also I believe the concurrent mode is not yet even supported on react native.

+ What do you mean by `don't work`? what exactly happens?
Does it error or the module resolves synchronously?

**Comment by hosseinmd** [comment]
Yes, this happens in the latest release too.
<img width="309" alt="Screen Shot 2020-05-22 at 4 26 38 PM" src="https://user-images.githubusercontent.com/45505767/82665673-8b30d380-9c49-11ea-8199-6e11cd666d06.png">

**Comment by hosseinmd** [comment]
I found that this is about react-native native wrapper

**Comment by gaearon** [comment]
`SuspenseList` has been renamed to `unstable_SuspenseList` in experimental releases. That's probably why the issue is happening.

As an aside, using experimental releases with RN is not really supported at this moment.
