### ISSUE TITLE
Could useMemo and useCallback have closures (functions) as the last argument?

### ISSUE THREAD

**Issue by vlsi** [facebook/react#18988]
The current argument order is

```javascript
const memoizedValue = useMemo(() => computeExpensiveValue(a, b), [a, b]);

const memoizedCallback = useCallback(
  () => {
    doSomething(a, b);
  },
  [a, b],
);

useEffect(
  () => {
    const subscription = props.source.subscribe();
    return () => {
      subscription.unsubscribe();
    };
  },
  [props.source],
);
```

and so on.

It makes it the code less readable when the callback spans multiple lines: it is hard to relate the dependencies to the hook.

What if the dependencies could be written as the first argument?

```javascript
const memoizedValue = useMemo([a, b], () => computeExpensiveValue(a, b));

const memoizedCallback = useCallback(
  [a, b]
  () => {
    doSomething(a, b);
  }
);

useEffect(
  [props.source],
  () => {
    const subscription = props.source.subscribe();
    return () => {
      subscription.unsubscribe();
    };
  }
);
```

For instance, the last example becomes easier to reason: there's an effect that is run whenever `props.source` changes.

AFAIK JavaScript does not yet allow to move the last closure argument out of the function call parenthesis, however, the following formatting might make sense:

```javascript
useEffect([props.source], () => {
  const subscription = props.source.subscribe();
  return () => {
    subscription.unsubscribe();
  };
});
```

**Comment by kyle-hensoon** [comment]
This is confusing because some people may confuse between  dependencies and parameters ,maybe
like this const memoizedValue = useMemo([a, b], () => computeExpensiveValue(a, b));

**Comment by vlsi** [comment]
There are brackets for dependencies, then there are parenthesis for arguments. I don't think it is really confusing.

There are lots of existing methods in React where a function is located after regular arguments.

For instance:
https://github.com/facebook/react/blob/3278d242184a13add3f25f683b77ef9a6a2305f3/packages/react/src/ReactChildren.js#L240-L242

**Comment by vlsi** [comment]
Just in case: Kotlin allows to move the last "function/lambda" argument out of function call parenthesis, so

```kotlin
useEffect(
  arrayOf(props.source),
  {
    val subscription = props.source.subscribe()
    ...
  }
)
```

is the same as 

```kotlin
useEffect(arrayOf(props.source)) {
  val subscription = props.source.subscribe()
    ...
} // <-- lambda is the last argument to useEffect
```

I guess Kotlin is not the only language that has that trick, so moving functions to the last argument should be preferred in general.

**Comment by kyle-hensoon** [comment]
This may be helpful, but the question is, will we have a logical problem with this syntax?

**Comment by HiMrHu** [comment]
maybe like this.
```jsx
const useMyEffect = (deep, callback) => {
  React.useEffect(callback, Array.isArray(deep) ? deep : [deep]);
};

export default function App() {
  const [count, setCount] = React.useState(0);

  useMyEffect([count], () => {
    console.log(count);
  });

  return <div onClick={() => setCount(count + 1)}>hi</div>;
}

```

**Comment by Eddie-CooRo** [comment]
I agree that having the dependencies array as the first argument is somewhat more reasonable in some scenarios. and being able to do it in the userland is not enough, because it'll cause additional noise for people who are not familiar with our codebase but are knowledgable in the React itself.
But at the same time, doing this would be a huge breaking change and I'm 100% sure that nobody wants it. tradeoffs are not convincing enough.
We don't want to have a React@17 only because of reversing the order of the useEffect arguments. and React team already at a budget for the breaking changes they can introduce in the future @17 version and they are even considering to ignore some of the more important changes and improvements in order to reduce the total amount of breaking changes.

So while this is an interesting idea, I don't think it would get anywhere in the current situation. You can, of course, do the userland implementation as @HiMrHu suggested or even write a fixable eslint plugin for it if you are very hardcore at that.

**Comment by vlsi** [comment]
> But at the same time, doing this would be a huge breaking change

It is not a breaking change.
Why do you think it is a breaking change?

**Comment by Eddie-CooRo** [comment]
Changing the order of the arguments is the most obvious form of a breaking change. unless I understood your proposal incorrectly.

**Comment by vlsi** [comment]
>Changing the order of the arguments is the most obvious form of a breaking change. unless I understood your proposal incorrectly.

There's a way to support both argument order in the transition period.
That is:
1) Enable the use of dependencies as the first argument
2) Mark old method as deprecated
3) Remove old method in React 30 or so

**Comment by kyle-hensoon** [comment]
> I agree that having the dependencies array as the first argument is somewhat more reasonable in some scenarios. and being able to do it in the userland is not enough, because it'll cause additional noise for people who are not familiar with our codebase but are knowledgable in the React itself.
> But at the same time, doing this would be a huge breaking change and I'm 100% sure that nobody wants it. tradeoffs are not convincing enough.
> We don't want to have a React@17 only because of reversing the order of the useEffect arguments. and React team already at a budget for the breaking changes they can introduce in the future @17 version and they are even considering to ignore some of the more important changes and improvements in order to reduce the total amount of breaking changes.
> 
> So while this is an interesting idea, I don't think it would get anywhere in the current situation. You can, of course, do the userland implementation as @HiMrHu suggested or even write a fixable eslint plugin for it if you are very hardcore at that.


Are things like props Destructuring of the part of  breacking change or not? i think this idea very similar with props destructuring  in functional component , if yes ,  i think react team just for one thing like this never change current  version

**Comment by vlsi** [comment]
>i think this idea very similar with props destructuring 

I do not see the connection

**Comment by kyle-hensoon** [comment]
-

> > i think this idea very similar with props destructuring
> 
> I do not see the connection

i mean you can use something like this function ({props1,props2}) instead of  const {props1,props2} = props

**Comment by vlsi** [comment]
>i mean you can use something like this function ({props1,props2}) instead of const {props1,props2} = props

How is it related to useMemo argument order?

**Comment by bvaughn** [comment]
The APIs being discussed have already been released and have been in use for over a year. Changing them would **cause a lot of churn throughout the ecosystem**. The bar for doing this is be **very high** (e.g. they are causing runtime errors) rather than a subjective preference about readability.

We appreciate the thought and discussion that went into this issue, but it's not a change we can make given the impact it would have on thousands of downstream packages and apps.

Thanks for understanding!

**Comment by vlsi** [comment]
@bvaughn ,

Frankly speaking, I do not see how it causes "runtime errors".
There change to add `useMemo(deps, function)` is backward-compatible. I see how it might introduce confusion, however, I don't see how it introduces errors (including runtime ones).

It would be nice if you could prefer having lambdas as the last argument in case the only argument is lambda.
