### ISSUE TITLE
Feature suggestion: Add React.static() to complement React.memo()

### ISSUE THREAD

**Issue by websocket98765** [facebook/react#18989]
I like the new functional components and hooks paradigm, because of its cleaner code. However, one thing that can only be achieved with classes still is this:

```
class Foo extends React.Component {
   shouldComponentUpdate() {
      return false;
   }
  render() {...}
}
```

This provided a significant speed up in my app, used appropriately, even better than React.memo() with functional components.

Could something similar be offered for functional components, possibly a method like `React.static()`?

**Comment by nstepien** [comment]
https://reactjs.org/docs/react-api.html#reactmemo
You can pass a second argument to `React.memo` to achieve this.
```js
React.memo(MyComponent, () => true);
```

**Comment by websocket98765** [comment]
Interesting! Thanks for mentioning @nstepien! 

I'll leave this open to be closed by the team, just because I think the `.static()` API may be worth considering, as it makes the intent clear.

**Comment by bvaughn** [comment]
@nstepien is correct that `React.memo` enables a similar level of memoization as `shouldComponentUpdate` :smile:

`React.static()` would slightly decrease the number of characters required to achieve this, but with the added downside of increasing the API surface area (more APIs to learn, more to maintain, etc.)

I think the existing APIs are sufficient in this case :smile:
