### ISSUE TITLE
Bug: eslint hooks plugin TypeScript optional chaining with exhaustive-deps

### ISSUE THREAD

**Issue by liamross** [facebook/react#18983]
React version: `16.13.0`
eslint-plugin-react-hooks version: `4.0.2`

When I upgraded from `^2.0.0` to `4.0.2`, this bug started happening:

## Steps To Reproduce

When you optionally chain, there is a bug with `exhaustive-deps`:

1. With no optional chaining, there is no issue
<img width="463" alt="Screen Shot 2020-05-22 at 12 48 55 PM" src="https://user-images.githubusercontent.com/24969218/82704534-9aecef80-9c2a-11ea-8eb9-b312b7cb951a.png">

2. With optional chaining, we see an eslint error
<img width="462" alt="Screen Shot 2020-05-22 at 12 50 12 PM" src="https://user-images.githubusercontent.com/24969218/82704613-c8399d80-9c2a-11ea-91d0-b4f361114852.png">

The error is 
```
React Hook useEffect has a missing dependency: 'test?.includes'. Either include it or remove the dependency array. eslint(react-hooks/exhaustive-deps)
```

Which auto fixes to:
<img width="465" alt="Screen Shot 2020-05-22 at 12 52 25 PM" src="https://user-images.githubusercontent.com/24969218/82704749-19499180-9c2b-11ea-9b5b-c539ac7beb45.png">

(in addition to being incorrect, this causes issues with the eslint `eslint@typescript-eslint/unbound-method` rule)

**Comment by AviVahl** [comment]
https://github.com/facebook/react/issues/18926

**Comment by liamross** [comment]
> #18926

Closing since it's a duplicate

**Comment by thinkingc** [comment]
> #18926

how to resolve?
