### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ManchukondaManoj** [facebook/react#18982]
React version:     16.13.1,

## Steps To Reproduce

1. create react app with create-react-app test-app
2. write a simple class component and import it in the App.js
3.) Write a log statement inside newly created component

Link to code example:

## The current behavior
 When you start the application and see logs, Application is rendered two times, we can see log statement 2 times in the console. but it is not happening with functional components

## The expected behavior
class component should render only once immediately after launching app without using any lifecycle methods

**Comment by facufrast** [comment]
Can you please show the code you have in App.js?

**Comment by kunukn** [comment]
Maybe you are using this? `<React.StrictMode>`
This would trigger double render in development mode.

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

> ... intentionally double-invoking the following functions:
> Class component constructor, **render**, and shouldComponentUpdate methods

Example.
https://codesandbox.io/s/react-class-double-render-72vbe?file=/src/App.js

**Comment by aweary** [comment]
This is expected behavior with `React.StrictMode`, as @kunukn called out.
