### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by shaikhjishan37** [facebook/react#18981]
When we have onClick and onDoubleClick both event on an element and we double click then single click is also trigger two times.

## research
All the solutions i have found will give some performance issue and that i don't want to in corporate in product.

## expected output
Pls provide a way to stop single click when double click i trigger without loosing any performance.

**Comment by kunukn** [comment]
>When we have onClick and onDoubleClick both event on an element and we double click then single click is also trigger two times.

This seems to be the expected design for DOM Events.
* https://w3c.github.io/uievents/#dblclick
* https://w3c.github.io/uievents/#click

A common solution seems to programmatically delay the click event until we know it is not a dblclick event.

---

Reference: 

ReactJS article with code examples.
https://medium.com/trabe/prevent-click-events-on-double-click-with-react-with-and-without-hooks-6bf3697abc40

>The solution lies in delaying the execution of the onClick handler until we know that the click is not part of a double-click: The onClick handlers are delayed for a while in a queue of pending promises and, when a dblclick event is triggered, all the pending promises are cancelled so they will never be executed.

---

Reference for similar approach in other libraries:

VueJS
https://stackoverflow.com/questions/41303982/vue-js-how-to-handle-click-and-dblclick-events-on-same-element/56046910

jQuery year 2014
https://css-tricks.com/snippets/javascript/bind-different-events-to-click-and-double-click/

**Comment by bvaughn** [comment]
The response by @kunukn is correct. I don't think this is necessarily an issue that React (DOM) should add extra layering on top of so I'm going to close this issue.

cc @trueadm though in case he has any thoughts about this wrt the new event system he's working on.
