### ISSUE TITLE
Bug: Developer Tools highlights components that do not go through a rendering phase

### ISSUE THREAD

**Issue by fabianhinz** [facebook/react#18996]
React version: 16.13.1

## Steps To Reproduce

1. Clone the git repo provided below
2. npm install
3. npm start
4. Start a new browser instance where React Developer Tools is installed and open dev tools
5. Check the box "Highlight updates when components render" 
6. Start profiling 

![Screenshot 2020-05-25 at 14 30 06](https://user-images.githubusercontent.com/22753474/82813788-143c4a80-9e96-11ea-8e79-a9c46fbb69dc.png)
![Screenshot 2020-05-25 at 14 30 42](https://user-images.githubusercontent.com/22753474/82813789-14d4e100-9e96-11ea-999f-02946df50e64.png)

Link to code example:

local: https://github.com/fabianhinz/ContextExample
stackblitz:  http://stackblitz.com/github/fabianhinz/ContextExample

## The current behavior

components that do not render again are being highlighted. 

## The expected behavior

only highlight components that actually go through a rendering phase.

**Comment by bvaughn** [comment]
I think this is a misunderstanding.

The profiler screenshot above shows that both `ProviderOne` and `ContextOneConsumer` rendered. The way the "highlight update" feature is currently implemented, when any component renders- React looks for the nearest DOM elements that component produces and it highlights them. 

Your screenshot of the Profiler tab shows you hovering over the `ContextOneConsumer` which online highlights a single DOM node. But if you were to hover over the `ProviderOne` component (which also renders) it would show the same set of nodes that "highlight update" includes.

You could argue that the "highlight update" feature should only highlight nodes that are directly rendered by a component, and not ones rendered by its descendants - but I'm not sure that would be better. It would probably result in some awkward use cases where nothing was highlighted even though a component was re-rendering.

Anyway I hope this clears things up. Thanks for sharing a repro!

**Comment by fabianhinz** [comment]
alright, thanks for clearing this up 👍
