### ISSUE TITLE
Error: Unexpected end of JSON input while parsing near '...J1pCXwGz7sODQT3hLgepp'

### ISSUE THREAD

**Issue by unicitee** [facebook/react#19003]
Unable to install react. npm return this error
`npm ERR! Unexpected end of JSON input while parsing near '...J1pCXwGz7sODQT3hLgepp'`

**Comment by kyle-hensoon** [comment]
using npx create-react-app

**Comment by kyle-hensoon** [comment]
try to using npx

**Comment by unicitee** [comment]
`npx react`
gives a same error
`npm ERR! Unexpected end of JSON input while parsing near '...J1pCXwGz7sODQT3hLgepp'`

**Comment by HiMrHu** [comment]
it is a cache error. you can try this:
1. delete package.lock.json
2. npm cache clean --force

if you use yarn try this:
1. delete yarn.lock
2. yarn cache clean
then  you can install package,

**Comment by unicitee** [comment]
Cache cleaning solved it.
Thank you.
