### ISSUE TITLE
export default Form.create()(connect(mapStateToProps)(CommonLog));

### ISSUE THREAD

**Issue by aiyudeleng** [facebook/react#19015]
`export default Form.create()(connect(mapStateToProps)(CommonLog));`

```
function mapStateToProps(state) {
    return {
        user: state.user
    }
}

export default Form.create()(connect(mapStateToProps)(FailCMD));
```

Before，our project has some codes like this. But now, antd as 3.x to 4.2.5, how to change the code ?

**Comment by GalenWong** [comment]
I think this issue is not related to React. `antd` has changed their form API. You should take a lot at their migration doc from v3 to v4: https://3x.ant.design/docs/react/migration-v4

**Comment by HiMrHu** [comment]
this is not about react , you can see [ant design v3 to v4 document](https://ant.design/docs/react/migration-v4)
> Removed the Form.create method, form is now available in Form.useForm.

**Comment by aiyudeleng** [comment]
> this is not about react , you can see [ant design v3 to v4 document](https://ant.design/docs/react/migration-v4)
> 
> > Removed the Form.create method, form is now available in Form.useForm.

I have seen the document , but still puzzled. I will see it again

**Comment by bvaughn** [comment]
This is not the right place to ask questions about Ant components. Please use the Ant documentation and/or issue tracker.

**Comment by aiyudeleng** [comment]
> This is not the right place to ask questions about Ant components. Please use the Ant documentation and/or issue tracker.

OK，i will close the question. I seen it a React Question before

**Comment by Jafson** [comment]
@aiyudeleng , do you know how to fix this issue? I got the same issue, thanks
