### ISSUE TITLE
Bug: Mouse leave event not fired after removing portal

### ISSUE THREAD

**Issue by amannn** [facebook/react#19016]
React version: 16.13.1

## Steps To Reproduce

1. Go to https://1r4ib.csb.app/
2. Open dev tools to see console logs
3. Click on "Toggle portal"
4. Leave the popover by moving the mouse out on the lower side.
5. See the logs: Only the portal mouse leave event is logged, not the one from the `<App />` component.

![Kapture 2020-05-27 at 13 21 52](https://user-images.githubusercontent.com/4038316/83013321-1d0b5880-a01d-11ea-85ba-f592a7027ff6.gif)

Link to code example: https://codesandbox.io/s/condescending-wilson-1r4ib?file=/src/App.js:890-951

I noticed this only happens if the event handler that triggers the closing of the popover is registered on a DOM node that is nested within another DOM node within the popover. If you 
swap the lines 35 and 36 everything works as expected.

## The current behavior

The mouse leave event on the outer div of the `<App />` component is not fired.

## The expected behavior

The mouse leave event on the outer div of the `<App />` component should be fired.

**Comment by iamdarshshah** [comment]
> I noticed this only happens if the event handler that triggers the closing of the popover is registered on a DOM node that is nested within another DOM node within the popover. If you
swap the lines 35 and 36 everything works as expected.

Check this @amannn, Just tried wrapping the `<div>`  element to the DOM node & got the expected results.


```
   const WrappingPortalNode = "div"; 
       <WrappingPortalNode>
         <Portal>
            <p
              style={{
                backgroundColor: "#ccc",
                position: "relative",
                top: -40,
                padding: 20
              }}
              onMouseLeave={onPortalMouseLeave}
            >
              Portal content
            </p>
          </Portal>
        </WrappingPortalNode>

**Comment by amannn** [comment]
@iamdarshshah Thanks for chiming in!

Yep, exactly. The event fires correctly if it's registered on the top-most DOM node within the portal. I've used that as a workaround in the app where I encountered this bug.

I found it interesting that even a wrapping `Fragment` works. So the bug seems related to actual DOM nodes wrapping children within the portal.

**Comment by amannn** [comment]
This is still reproducible in 17.0.0-rc.3.

**Comment by evansjohnson** [comment]
I'm also seeing this but with closing the portal with a button - when the portal closes the mouse is outside of the div with `onMouseLeave` but the `onMouseLeave` event never fires. In this case the wrapping element is irrelevant.

Reproducer here: https://codesandbox.io/s/react-bug-portal-mouse-leave-forked-5lb8s6?file=/src/App.js
(not sure if this will be kept alive without signing up for an account but only change is to add a button inside the portal that closes it instead of `onMouseLeave`)
