### ISSUE TITLE
Click event and setTimeout update state, different times of rendering

### ISSUE THREAD

**Issue by VitaminCtea** [facebook/react#19013]
When I try to batch update all the states with click events, the final render is once. When the state is updated in batch with setTimeout, the result is multiple times. May I ask what is the useStateHook running mechanism inside react? Is the same asynchronous function, but The Times of rendering is not the same?

React version: 16.12.0

## Steps To Reproduce

1. Bind a single click event to the DOM and handle multiple state updates in batches
2. After the component is mounted, create a setTimeout timer, which is also a batch update of state

Link to code example: [https://codesandbox.io/s/charming-fermat-syi5g?file=/src/App.js](url)

## The current behavior
Click event batch update and timer batch update rendering times are different

## The expected behavior
Also triggers an update

What is the operation mechanism of useState hook? Why not the same number of asynchronous renderings?

**Comment by HiMrHu** [comment]
if you update the state in `setTimeout` `addeventlistener`  then it's sync
if you update the state in a coomposite event provided by React then it's async, like `onClick` `onXxxx` all the event.

here is the [source code](https://github.com/facebook/react/blob/142d4f1c00c66f3d728177082dbc027fd6335115/packages/react-reconciler/src/ReactFiberWorkLoop.old.js#L453)

```ts
 if (executionContext === NoContext) {
        // Flush the synchronous work now, unless we're already working or inside
        // a batch. This is intentionally inside scheduleUpdateOnFiber instead of
        // scheduleCallbackForFiber to preserve the ability to schedule a callback
        // without immediately flushing it. We only do this for user-initiated
        // updates, to preserve historical behavior of legacy mode.
        flushSyncCallbackQueue();
      }
``

**Comment by VitaminCtea** [comment]
@HiMrHu OK, thank you. I'll read the following carefully later!

**Comment by bvaughn** [comment]
`setState` is asynchronous inside event handlers. This ensures, for example, that if both `Parent` and `Child` call `setState` during a click event, `Child` isn’t re-rendered twice. Instead, React “flushes” the state updates at the end of the browser event. This results in significant performance improvements in larger apps.

React batches *all* state updates for the upcoming concurrent mode, but that is still an experimental API.

In the meanwhile, if you want to manually batch multiple updates, you can use the `unstable_batchedUpdates` API:

```js
ReactDOM.unstable_batchedUpdates(() => {
  // Call other code that might have multiple `setState` calls
});
```
