### ISSUE TITLE
Selenium integration

### ISSUE THREAD

**Issue by Silkking7** [facebook/react#19037]
Hello. I'm not sure if this is an issue, but I would like to know a little more about how react developer tools work. 

I want to get reacts props with selenium in order to make easier the debugging of a website. 

I'd be thankful with any kind of help you can give me.

Best regards

**Comment by bvaughn** [comment]
DevTools does not provide any sort of external API for querying components on a page. (I also think Selenium is not able to interact with DevTools extensions? Although I may be wrong in that case.)

Sorry! :(
