### ISSUE TITLE
startTransition bails early

### ISSUE THREAD

**Issue by arackaf** [facebook/react#19046]
React version: 0.0.0-experimental-33c3af284

## Steps To Reproduce

Code Sandbox: https://codesandbox.io/s/amazing-wilbur-fsich?file=/package.json:189-217

As you page through the books, you should see the snazzy pink pending indicator which is shown via the pending boolean from useTransition.

If you edit one of the books (modify the title, hit save), the list will re-load, and suspend in the process (started with startTransition). 

Bug is that no pink pending indicator shows during this re-load. Logging the pending value, it goes true for an instant, but immediately reverts back to false. 

If you modify the hardReset call to NOT pass startTransition anymore, and repeat, and you should see the Suspense fallback trigger.

So Suspense appears to be working, but useTransition is bailing out for some reason.  I tried this with latest built off of master, but no change.

Obviously setting your network speed to Slow 3G will help repro this. Also, please feel free to edit this data as you wish - any changes you make will be automatically reverted every hour.

Link to code example:

See above

## The current behavior

Pending indicator should stay true after a call to startTransition suspends

## The expected behavior

It does not.

**Comment by arackaf** [comment]
Here's a simpler repro, involving far fewer pieces from the GraphQL client.

https://codesandbox.io/s/ancient-sunset-y9vp6?file=/src/App.js

Click the "Reload" button. startTransition will be called, the query will reload over the wire, suspending in the process, but the pending indicator does not stay true in the process.

To confirm that I am in fact suspending, you can comment out the call to startTransition in doRefresh, and see the Suspense fallback appropriately render.

**Comment by vkurchatkin** [comment]
> Click the "Reload" button. startTransition will be called, the query will reload over the wire, suspending in the process, but the pending indicator does not stay true.

It actually seems to confirm the opposite. There really should be a way to reproduce this without graphql stuff.

**Comment by arackaf** [comment]
How does it confirm the opposite? Without startTransition, the ui suspends, and the fallback renders. With startTransition, the pending indicator should stay true.

And yeah I wish I had a simpler repro.

**Comment by vkurchatkin** [comment]
> How does it confirm the opposite? Without startTransition, the ui suspends, and the fallback renders

I meant that I don't  see fallback at all. Actually after playing with it, it shows sometimes, but mostly there is no fallback at all after click

**Comment by arackaf** [comment]
Did you try setting your network speed to Slow 3G in the network pane? Also note that if you visit a page you've already seen, it'll be cached and so no delay.

**Comment by gaearon** [comment]
There's still too many moving pieces to effectively look into this. A reduced example without GraphQL, with setTimeout instead of network, and with a simple cache (an object hash) instead of a mini-library would have been helpful.

**Comment by arackaf** [comment]
Dan you did tell me before that you could reduce a big repro. I can chop this current repro down a bit, remove some unused bits from the mini-library, but I don't have any kind of non-GraphQL "simple" cache lying around, sadly.

I'm logging the locations where my promise is thrown, and resolved, and the startT pending is just ignoring it, it seems. That's the piece that seems off here, but I can try to make the repro simpler, like I said.

**Comment by gaearon** [comment]
I'm not saying it is *impossible* for me to do, I'm only saying that this would greatly increase the chance that we can fix this sooner. Reducing big reproes from unfamiliar code can take days, and I don't think I can dedicate a lot of time to this right now. If you don't have the time for this either, we'll probably come back to this but at some point later.

>I don't have any kind of non-GraphQL "simple" cache lying around, sadly.

Here you go:

```
let promises = {}
let cache = {}
function read(id) {
  if (promises[id]) throw promises[id]
  if (cache[id]) return cache[id]
  promises[id] = new Promise(resolve => {
    setTimeout(() => {
      delete promises[id]
      cache[id] = 'Fake result for ' + id
      resolve()
    }, 1000)
  })
  throw promises[id]
}
```

**Comment by arackaf** [comment]
Thanks Dan - I understand. I don't really have time to re-do the repro to make it much simpler. If you don't have time to look at this now, I completely understand. But this definitely seems like a bug, and I'd be happy to personally walk you through the repro via Zoom, to cut down on the time needed.

To be crystal clear why I think this is a bug. I essentially have this code

```js
const reload = () => {
  startTransition(() => {
    graphQL.suspendAndQuery();
  });
}
```

That does reload my data, but the `useTransition` spinner does not show, NOR does my suspense boundary.

**HOWEVER**, if I manually change the code to this:

```js
const reload = () => {
  //startTransition(() => {
    graphQL.suspendAndQuery();
  //});
}
```

and make no other changes, then my Suspense boundary DOES show.  It seems pretty clear there's indeed a suspense happening, but startTransition is blocking the Suspense boundary from showing (good!) but also not reporting a correct `isPending` value (the bug).

**Comment by arackaf** [comment]
It appears @vkurchatkin reproduced this same issue much more cleanly than me, in the linked issue above, so I'm closing this.

Thank you SO much for doing this!
