### ISSUE TITLE
[DevTools Feature Request] Break on Warnings

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#19045]
It'd be nice to have a toggle to pause the debugger when warnings fire so you can inspect the stack as it's happening.

```
console.error = function() {
  ...
  if (isBreakOn) {
    debugger;
  }
}
```

See https://github.com/facebook/react/pull/19044

**Comment by bvaughn** [comment]
What is "Status: New" haha

**Comment by bvaughn** [comment]
Darn Webpack. Also seems like it strips debugger statements...
