### ISSUE TITLE
Bug: IE 11 Poliyfill not working

### ISSUE THREAD

**Issue by simonprice33** [facebook/react#19058]
Issue: 

React App not rendering in IE11 or Safari. I am currently only focusing on the issue that relates to IE11. 

small app shell built in React is not rendering as required. 

React version: 16.11.0
React-App-PolyFill version : ^1.0.6
bable-polyfill version: 6.26.0

## Steps To Reproduce

1. Project created with vscode
2. Add react-app-polyfill
3. npm start
4. test in IE11

## The current behavior
Current behaviour is that I get an error in bundle.js

    const is = {
    arr: Array.isArray,
    obj: a => Object.prototype.toString.call(a) === '[object Object]', // This is where the error is reported. 
    fun: a => typeof a === 'function',
    str: a => typeof a === 'string',
    num: a => typeof a === 'number',
    und: a => a === void 0,
    nul: a => a === null,
    set: a => a instanceof Set,
    map: a => a instanceof Map,

    equ(a, b) {
      if (typeof a !== typeof b) return false;
      if (is.str(a) || is.num(a)) return a === b;
      if (is.obj(a) && is.obj(b) && Object.keys(a).length + Object.keys(b).length === 0) return true;
      let i;

    for (i in a) if (!(i in b)) return false;
    for (i in b) if (a[i] !== b[i]) return false;
    
     return is.und(i) ? a === b : true;
     }

    };`

## The expected behavior

Loads in IE11

**Comment by aabbccsmith** [comment]
Please can you convert your code here into a codeblock, it makes it easier for us to help :)
```javascript
const anExample = 'of a code block';
```

You can use codeblocks by using three back ticks (```language)

**Comment by bvaughn** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
