### ISSUE TITLE
Bug: ESLint react-hooks/exhaustive-deps rule false positive on optional chaining expression ?.

### ISSUE THREAD

**Issue by felixfbecker** [facebook/react#19064]
`eslint-plugin-react-hooks` version: 4.0.4 (worked fine in 4.0.0)

Using TypeScript in case it matters

## Steps To Reproduce

1. Access an outer-scope variable in a function passed to `useMemo()` with optional chaining `?.`
2. Add the variable to deps

Code example:

```js
import React, { useMemo } from 'react'

const Comp = ({ foo }) => {
    const bar = useMemo(() => foo?.baz, [foo])
}
```

Real world example here: https://github.com/sourcegraph/sourcegraph/blob/4f02180d0d56bde864cb1be2b802a70f40b105b3/web/src/search/ScopePage.tsx#L87

## The current behavior

ESLint complains about extraneous dep

## The expected behavior

ESLint does will complain if the dep is _not_ there

**Comment by coolkev** [comment]
PR #19061 fixes this issue.

**Comment by bvaughn** [comment]
x
