### ISSUE TITLE
forcing exhaustive dependencies on useEffect defeats point of useEffect

### ISSUE THREAD

**Issue by r3wt** [facebook/react#19060]
Here's a simple example for you people of facebook who don't seem to understand what people are complaining about:

```jsx
function Example({ data }=>{
  const [value,setValue] = useState(5);
  useEffect(()=>{
    if(value>data.length){
      setValue(data.length);
    }
  },[data]);
});
```
the effect doesn't care if value changes it only cares if `data` changes, so it only needs to run when data changes. but your exhaustive dep check calls value a dependency, which it is not. please add a 3rd parameter to useEffect allowing us to opt out of exhaustive dep checks. 

in my situation i have working code with the following warnings:

<img width="1339" alt="Screen Shot 2020-06-01 at 3 35 17 PM" src="https://user-images.githubusercontent.com/4483325/83452393-3d248880-a41e-11ea-8a37-b47cfc1746df.png">

if i follow the stupid compiler, it results in `maximum update depth exceeded` errors. the reason is that `scroll` is not a dependency, it simply needs to be read and mutated inside of the effect.

**Comment by illuminist** [comment]
Possible fix

```js
useEffect(()=>{
  setValue((v) => {
    if(v > data.length){
      return data.length
    return v
  })
},[data]);
```

I saw the main issue is the effect is update the state based on previous state, which is probably not good if you rely on state value from closure. So it should be using callback updater so this way it can eliminate dependency on the state value while get the correct value on current state.

However, I personally don't use exhaustive dependencies or just simply ignore it.

**Comment by bvaughn** [comment]
> the effect doesn't care if value changes it only cares if data changes, so it only needs to run when data changes

If `value` is referenced, the effect **definitely cares** about when `value` changes too.

For example, let's say...
1. You component renders with `value === 5` and `data.length === 5` initially.
2. Then let's say `value` changed to be 500 (but the effect didn't re-run because `value` wasn't in the dependencies array).
3. Next let's say `data` changes to have a new length of `6`.
4. The effect would re-run, see the **stale** closed over `value === 5` and think it's appropriate to call `setValue`.

The only way you could "guard against" this would be if you only called `setValue` from inside of the effect, at which point I would say that derived state value isn't adding any value or serving a purpose. (You could just read from `data.length` directly.)

> if i follow the stupid compiler, it results in maximum update depth exceeded errors. the reason is that scroll is not a dependency, it simply needs to be read and mutated inside of the effect.

You could use a ref to avoid a cycle in the case you should:
```js
useEffect(() => {
  const dataLength = data.length;
  const prevDataLength = prevDataLengthRef.current;
  prevDataLengthRef.current = dataLength;
  if (prevDataLength !== dataLength) {
    if (value > data.length) {
      setValue(data.length);
    }
  }
}, [data, value]);
```

But again, it's really not clear what the value of this derived state is, from your example. If you haven't already read this blog post, I'd suggest giving it a read:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

We can continue to chat on this issue, but I am going to close it because the dependencies array serves several very important purposes and removing it in the way you described, I believe, reflects a misunderstanding.

**Comment by r3wt** [comment]
my previous example was bad, and oversimplified. the problem is it becomes a jenga tower of warnings and following compiler results in maximum update depth exceeded (infinite render). i will post an example of the actual code ( i have 3 different effects, all only need to run in specific conditions, and all have the same problem. since you all claim i'm wrong, i'd love to see how you'd refactor this to avoid both the compiler warning and the runtime error about maximum update depth:

```tsx
useEffect(()=>{
  const d = [...data];
  const _sorted = stableSort(d,getComparator(sort.order,sort.key||'desc'));
  setSorted(_sorted);
  setScroll({
    pos: 0,
    paddingTop: 0,
    startIndex: 0,
    stopIndex: displayable - 1 + overhang,
    height: (data.length * rowHeight) + headHeight
  });
  if(wrapper!==null){
    (wrapper as HTMLElement).scrollTop = 0;
  }
},[sort,data]);
```
this a very simple effect, when new data come into component, or the sort options change, the effect should sort data and reset scroll state. compiler complains that `wrapper` and `displayable` aren't passed in as dependencies (they will always be updated before the effect runs, so compiler is dumb!. if `wrapper` and `displayable` are passed, then the effect runs too much, resulting in the runtime error about maximum update depth. for context, the data parameter is an array, often with 10k+ rows, sometimes 20k+

**Comment by illuminist** [comment]
@r3wt I don't see any potential infinite rendering in your second example, probably it's from the other part of your component as I couldn't track all the variable source.

`wrapper` should not cause the excessive update as it should point to the same DOM element. Even though it should be better to use `useRef` to store DOM element instead.

`displayable` should be an integer and itself should pretty much stable enough to not cause the update if `height` doesn't fluctuate all over the place when some update occur.

**Comment by king-of-poppk** [comment]
@r3wt Perhaps, [this](https://react.dev/learn/separating-events-from-effects#reading-latest-props-and-state-with-effect-events) is what you were looking for four years ago?

**Comment by king-of-poppk** [comment]
@r3wt Another solution that does not require skipping effects: take control of the scroll state. Yes, new sorted data should update (reinitialize) the scroll state, and if the number of displayable elements changes, especially if it increases, the scroll state should also be updated. What do you think of the following:

```ts
import {useState, useCallback, useMemo, useEffect} from 'react';
import { usePrevious } from "@uidotdev/usehooks";

// Question: Where do `headHeight` and `rowHeight` come from? Constants?
const headHeight = 50;
const rowHeight = 30;
const overhang = 3;

type Comparator<T> = (a: T, b: T) => -1 | 0 | 1;

const stableSort = <T>(data: T[], comparator: Comparator<T>): T[] => data.slice().sort(comparator);

const getComparator = <T extends {}>(order: 'asc' | 'desc', key: keyof T): Comparator<T> => {
  switch (order) {
    case 'asc':
      return ({[key]: a}: T, {[key]: b}: T) => a < b ? -1 : a > b ? 1 : 0;
    case 'desc':
      return ({[key]: a}: T, {[key]: b}: T) => a < b ? 1 : a > b ? -1 : 0;
  }
};

type ScrollUpdate = (state: {pos: number, startIndex: number}) => void;

const useScroll = (element: HTMLElement | null) => {
  // Question: Is this some custom hook?
  return (update: ScrollUpdate) => {};
};

const MyFunctionComponent = <T extends {}>({data, height, sort}: {data: T[], height: number, sort: {order?: 'asc' | 'desc', key: keyof T}}) => {

  const displayableRows = useMemo(
    () => Math.ceil((height - headHeight) / rowHeight),
    [height],
  );

  // Question: Not sure what you are trying to do here, why not useRef?
  const [wrapper, setWrapper] = useState<{current: HTMLElement | null}>({current: null});
  const wrapperRef = useCallback((current: HTMLElement | null) => {
    if (current !== null) {
      setWrapper({current});
    }
  }, []);

  const setScroll = useScroll(wrapper);

  const {order, key} = {order: 'desc' as const, ...sort};

  const sortedData = useMemo(()=>{
    // Note: I assume setSorted was only needed because of lack of decoupling.
    return stableSort(data, getComparator<T>(order, key));
  }, [data, order, key]);

  const previousSortedData = usePrevious(sortedData);
  const sortedDataChanged = sortedData !== previousSortedData;

  const loadedRows = displayableRows + overhang - 1;
  const scrollHeight = (sortedData.length * rowHeight) + headHeight;

  useEffect(() => {
    // Note: I assume you want to reset the scrolling position only
    //       when data is updated, or when the sorting logic changes.

    setScroll(({pos, startIndex: prevStartIndex}) => {
      const startIndex = sortedDataChanged ? 0 : prevStartIndex;
      const stopIndex = startIndex + loadedRows;

      return {
        pos, // Note: Assuming rowHeight is a constant.
        paddingTop: 0, // ???
        startIndex,
        stopIndex,
        height: scrollHeight,
      };
    });

  }, [sortedDataChanged, loadedRows, scrollHeight]);

  useEffect(() => {
    // Note: I assume you want to reset the scrolling position only
    //       when data is updated, or when the sorting logic changes.
    if (wrapper !== null) {
      (wrapper as HTMLElement).scrollTop = 0;
    }
  }, [sortedDataChanged]);

  return (
    <div ref={wrapperRef}>
      {sortedData.map((item) => {
        // Note: Something that depends on sortedData perhaps?
        return null;
      })}
    </div>
  );
};
```
