### ISSUE TITLE
Bug: Property 'set' does not exist on type 'MutableRefObject<...>'

### ISSUE THREAD

**Issue by CSMR-DB** [facebook/react#19066]
I am using the react-gsap package, currently following their official docs. Specifically, '[Advanced multiple targets](https://bitworking.github.io/react-gsap/src-components-timeline#advanced-multiple-targets)'. And this only errors because I am working in TypeScript. It works as expected, perfectly fine, in the browser despite the error in VSCode. 

React version: 16.13.1 (latest)
@types/React: 16.9.35 (latest)

_gsap: 3.2.6
react-gsap: 2.2.1_

## Steps To Reproduce

1. Scaffold a new React app. (With TypeScript)
2. Install gsap & react-gsap 

Using this typedef'd code following above mentioned example.

```typescript
import React, { forwardRef, ReactElement } from "react";
import { SplitChars } from 'react-gsap';

export const TargetWithNames: React.ForwardRefExoticComponent<React.RefAttributes<any>> = forwardRef(( 
  _props: any, 
  targets: ((instance: any) => void) | React.MutableRefObject<any> | null): JSX.Element | null => {

  return targets !== null ? (
    <div style={{ textAlign: 'center' }}>
      <h3 ref={(el: HTMLHeadingElement ): void => targets.set('div1', el)}>THIS</h3>
      <SplitChars
        ref={(el: ReactElement): void => targets.set('div2', [el])}
        wrapper={<h3 style={{ display: 'inline-block' }} />}
      >
        TEST
      </SplitChars>
      <h3 ref={(el: HTMLHeadingElement): void => targets.set('div3', el)}>IS A</h3>
    </div>
  ) : null
});
```

Or just check this [CodeSandbox example](https://codesandbox.io/s/condescending-butterfly-5zyiv?file=/src/App.tsx). 

## The current behavior
```
Property 'set' does not exist on type 'MutableRefObject<any> | ((instance: any) => void)'.
  Property 'set' does not exist on type 'MutableRefObject<any>'.ts(2339)
```

## The expected behavior
```
🎆 [*insert firework noises*] 🎆
```

**Comment by illuminist** [comment]
[src/examples/Timeline.tsx#L124](https://github.com/bitworking/react-gsap/blob/003c9083e3d3187b4b9a7acdf15bb9e344987ff9/packages/playground/src/examples/Timeline.tsx#L124)
```jsx
const TargetWithNames = forwardRef((props, targets: any) => (
```

So `targets` they're using is not a regular ref object.

This is their actual type

```ts
export type TargetsRef = {
  set: (key: string, target: any) => void;
};
```
from [src/Timeline.tsx#L15](https://github.com/bitworking/react-gsap/blob/003c9083e3d3187b4b9a7acdf15bb9e344987ff9/packages/react-gsap/src/Timeline.tsx#L15)

**Comment by CSMR-DB** [comment]
Figured it wasn't default behavior, guess going `targets: any` is my only option here. Oh well, thanks for the quick reply.
