### ISSUE TITLE
Bug: miss renderers in __REACT_DEVTOOLS_GLOBAL_HOOK__

### ISSUE THREAD

**Issue by jcedo** [facebook/react#19072]
## Bug Description And Steps To Reproduce
I coding in Next.js-cli.
Run `yarn dev`
```
react-refresh-runtime.development.js:467 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at Object.injectIntoGlobalHook (react-refresh-runtime.development.js:467)
    at Object../node_modules/@next/react-refresh-utils/runtime.js (runtime.js:9)
    at __webpack_require__ (bootstrap:867)
    at checkDeferredModules (bootstrap:45)
    at webpackJsonpCallback (bootstrap:32)
    at bootstrap:1046
    at bootstrap:1051
```
This error message will appear in console.
I read `/node_modules/react-refresh/cjs/react-refresh-runtime.development.js`
In function `injectIntoGlobalHook`, I debugger and found that the property with name `renderers`  is not in `globalObject.__REACT_DEVTOOLS_GLOBAL_HOOK__`(globalObject is window in Web environment)

React version: 16.13
Next version: 9.4.4
React Developer Tools verison: 3.6.0
Computer system version: Win10 18362.836
Chorme version: 83.0.4103.61

## The current behavior
The project will console error and broken down.

I add the code to check
```
if(hook.renderers){
  hook.renderers.forEach....
}
```
But I don't know the use of injected'id

## The expected behavior
no error

**Comment by bvaughn** [comment]
Update your React DevTools. Version 3 is quite old and is not compatible with Fast Refresh (or many of the newer React v16 features). DevTools version 4 has been out for almost a year now :smile: It's a big improvement!

**Comment by LoveEocding** [comment]
i hava a same problem and follow the steps to slove
