### ISSUE TITLE
Bug: "Cannot update a component [...] while rendering a different component" breaks parent-configuration component usecase

### ISSUE THREAD

**Issue by joepie91** [facebook/react#19070]
In some component library designs, it can be useful to provide the user with certain "meta-components" that they can use to configure an ancestor component that their content gets wrapped in.

For example, in a system where a user can specify a "View" that gets rendered into a panel/window/etc., and the title needs to be part of the View component __but gets rendered in a separate place in the actual UI, away from the actual view content__, it can be useful to specify this information through a component that doesn't actually render anything, like so:

```jsx
function SomeView() {
	return (<>
		<PanelTitle>Hello world!</PanelTitle>
		<p>Some text goes here.</p>
		<p>More text goes here.</p>
	</>);
}

function App() {
	return (
		<Panel view={SomeView} />
	);
}
```

Here, `PanelTitle` and `Panel` are both provided by a hypothetical library, and their implementation is opaque to the user. `Panel` does nothing other than call out to a `setTitle` method defined in the `Panel` component, so that the `Panel` can be re-rendered with the correct title. A link to a repository with a full runnable version of this example is included below.

This is roughly analogous to 'slots' in a templater, like the [`block` syntax in Pug](https://pugjs.org/language/inheritance.html) but with each pre-defined block being represented by its own meta-configuration-component (only `PanelTitle` in this specific example).

While this works fine from a technical perspective, in recent React versions it has been starting to produce a "Cannot update a component [...] while rendering a different component" error. The [changelog entry for this change](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render) speaks of using `useEffect` as a workaround for this (although it doesn't actually go into enough detail to understand what is meant with that...), but comments in #18178 allude to this pattern being entirely unsupported in the future.

Notably, __these meta-elements do not actually ever render any content.__ They are merely syntactic wrappers that expose an internal `set*` function as a JSX component. Any content rendering would occur in either the call site of the meta-element, or the internal implementation of the parent component whose state is being configured.

An alternative API design approach is to require a `View` in this case to be specified like so:

```jsx
function SomeView() {
	return (
		<View title="Hello world!">
			<p>Some text goes here.</p>
			<p>More text goes here.</p>
		</View>
	);
}
```

... however, especially when the slot content gets complex and there are multiple slots, this approach can become unwieldy to read in some cases. This applies doubly so when *multiple* meta-elements need to be specified, like the following for a hypothetical cookie storage system:

```.jsx
function SomeView() {
	return (<>
		<Cookie key="foo" value="Bar" />
		<Cookie key="baz" value="qux" expiry="30m" />
		
		<p>Some text goes here.</p>
		<p>More text goes here.</p>
	</>);
}
```

... which would, *at best*, end up looking like this:

```jsx
function SomeView() {
	return (
		<View cookies={[
			{ key: "foo", value: "bar" },
			{ key: "baz", value: "qux", expiry: "30m" }
		]}>
			<p>Some text goes here.</p>
			<p>More text goes here.</p>
		</View>
	);
}
```

Hence filing this bug. Is this a pattern that React intends to support going forward, or are we stuck with the alternative "handle it all as properties of a wrapper element" approach mentioned above?

React version: 16.13.1

## Steps To Reproduce

1. Attempt to use an "empty" meta-component to configure something in a parent, through a `set*` call
2. Be faced with "Cannot update a component [...] while rendering a different component"

Link to code example:

https://git.cryto.net/joepie91/bugcase-react-parent-configuration is a reduced testcase for this issue. After installing dependencies, `yarn dev` / `npm run dev` will spin up a local development server that demonstrates the problem.

## The current behavior

Produces an error:

```
Warning: Cannot update a component (`Panel`) while rendering a different component (`PanelTitle`). To locate the bad setState() call inside `PanelTitle`, follow the stack trace as described in https://fb.me/setstate-in-render
    in PanelTitle (created by SomeView)
    in SomeView (created by Panel)
    in div (created by Panel)
    in Panel (created by App)
    in App
```

## The expected behavior

Should not produce an error, and work as expected.

**Comment by illuminist** [comment]
Isn't it because of `setTitle(children)` is being call in rendering period in another component? As the reported error said it should not try to set state of another component in rendering period.

It should be better to wrap `setTitle(children)` in `useLayoutEffect` so the state update after all the component rendered but before visual change in DOM.

**Comment by gaearon** [comment]
This pattern is generally problematic.

It doesn't have a consistent behavior that you can confidently reason about. What if you render two `<PanelTitle>`s? Which one of them wins? The first one? By the order in the tree or by the order of insertion? What if initially there are no `<PanelTitle>`s but later they get inserted? What if the last `<PanelTitle>` gets deleted? What if it changes over time? What if the child component becomes lazy-loaded and isn't available immediately? How would this work with server rendering? How would this work with streaming server rendering?

Aside from all of these semantic issues, there are also significant performance implications to rendering a tree only to find out that actually, it needs to be re-rendered from the top because we have new information once we reach a leaf. Maybe okay in a few cases but this doesn't really scale.

**Comment by gaearon** [comment]
That said, `useLayoutEffect` indeed fixes the warning: https://codesandbox.io/s/vibrant-wilbur-98rdn. You still have all of the problems I enumerated above but maybe you're okay with them.

Another way you could solve this is by passing a ref from the parent, and portaling the child into it: https://codesandbox.io/s/intelligent-lamport-6r7pl. That avoids the cascading re-render of the whole tree.

Hope that helps.
