### ISSUE TITLE
Bug: Warning: The tag <kbd> is unrecognized in this browser

### ISSUE THREAD

**Issue by samson-sham** [facebook/react#19085]
React version: 16.13.1

## Steps To Reproduce

1. Use "kbd" HTML tag, which is valid standard from WHATWG
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd

Link to code example: 
- https://codesandbox.io/s/nostalgic-mayer-pu11w?file=/src/App.js
- https://jsfiddle.net/46m8L5ak/

## The current behavior
- Console log showing Error Message
```
Warning: The tag <kdb> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    in kdb (created by App)
```

## The expected behavior
- No error message

**Comment by bvaughn** [comment]
Your test app has `kdb`.

The actual element is `kbd`.

https://codesandbox.io/s/sad-morning-mir6j?file=/src/App.js
