### ISSUE TITLE
Bug: TypeError: "log" is read-only.

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#19099]
React version: 0.0.0-experimental-33c3af284

![image](https://user-images.githubusercontent.com/5390719/84034123-7b94e700-a9cc-11ea-9668-def995e2a09b.png)

https://github.com/facebook/react/blob/master/packages/shared/ConsolePatchingDev.js#L45

>       // $FlowFixMe Flow thinks console is immutable.

Yes it _is_ immutable in some enviroment. Please add a try catch on it.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/84035738-c9aaea00-a9ce-11ea-8cfd-af71f4197296.png)

Context:

Once you change the value of `console.log`, it becomes immutable.

![image](https://user-images.githubusercontent.com/5390719/84035806-e0e9d780-a9ce-11ea-86b1-3fd5b130ee5a.png)

My environment: content script of Web Extension on Firefox

**Comment by Jack-Works** [comment]
Please use the `Object.defineProperty` API to overwrite the `console.log` API, thanks.

**Comment by Jack-Works** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1644132

**Comment by threepointone** [comment]
Would you like to send a PR for this?

**Comment by Jack-Works** [comment]
closed by https://github.com/facebook/react/pull/19123
