### ISSUE TITLE
Bug: Incorrect HTML attribute name for custom tags

### ISSUE THREAD

**Issue by Enter-tainer** [facebook/react#19105]
React version: 16.13.1

Hello developers,

## Steps To Reproduce

1. Use `React.createElement` to create a custom tag, e.g. `mjx-container`, `mjx-i` (these are tags used by mathjax), and set its `className`. For example, `React.createElement('mjx-container',  { className: 'Mathjax' }, 'Hello')`
2. Checkout the dev tools, and you can see that we have got `<mjx-container classname="Mathjax">Hello</mjx-container>`. However, I expected to have `class`, but not `classname`. Since `className` attribute makes sense only in React JSX, but not in HTML and CSS.

![image](https://user-images.githubusercontent.com/25521218/84149661-66cf5680-aa93-11ea-8247-da9ddf5f6c6c.png)

Link to code example: https://codepen.io/Margatroid/pen/KKVdYdd

## The current behavior

I expect to get `<mjx-container class="Mathjax">Hello</mjx-container>`

## The expected behavior

But I have got `<mjx-container classname="Mathjax">Hello</mjx-container>`

I've encountered this issue when trying to use gatsby, mdx, and Mathjax to render equations service-side. My current workaround is replacing `className`s to `class`es for mathjax related tags.

Thank you for your time!

**Comment by vkurchatkin** [comment]
Use `class` instead of `className`

**Comment by bvaughn** [comment]
For what it's worth, the docs mention this specifically:
https://reactjs.org/docs/web-components.html#using-web-components-in-react
