### ISSUE TITLE
Bug: no way to implement global css variables. :root and html css tags don't work.

### ISSUE THREAD

**Issue by 619** [facebook/react#19116]
React version: every

## Steps To Reproduce

1. Try to implement global css variables.
2.

Link to code example:

## The current behavior
Doesn't work

## The expected behavior
working

**Comment by illuminist** [comment]
https://codesandbox.io/s/infallible-sky-lt6ss?file=/src/styles.css

It's literally working.

Care to provide your own implementation that isn't working?

**Comment by threepointone** [comment]
Please share a reproducible example on codesandbox or as a git repo. React doesn't have anything to do with css variables, so this issue probably doesn't belong here.
