### ISSUE TITLE
Add https support to standalone DevTools

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#19111]
I notice that the standalone react-devtools use http instead https like `"<script src="http://192.1.2.3:8097"></script>"` ([src code](https://github.com/facebook/react/blob/4c7036e807fa18a3e21a5182983c7c0f05c5936e/packages/react-devtools/app.html#L186-L194))，but my website is always https, so it will get broken because I cant change it to http if it's in `iframe`(it's diffcult to change the host environment/website protocol).

I'm not familar with the react-devtools implementations, maybe something cause it can only use http to open the server, happy to hear the details, thanks!

React-devtools: 3.6.3

**Comment by kunukn** [comment]
It might be because a http server is used?
https://github.com/facebook/react/blob/master/packages/react-devtools-core/src/standalone.js#L246

There is the possibility to use the https server variant, but you need some certificate setup and such.
https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

**Comment by NE-SmallTown** [comment]
Yea, I think certificate is not a problem because we can do something like https://webpack.js.org/configuration/dev-server/#devserverhttps

**Comment by NE-SmallTown** [comment]
@bvaughn @gaearon friendly ping~    If you don't mind I am not familar with devtools's code, I could try to work on this

**Comment by bvaughn** [comment]
Feel free. Haven't thought about this enough to have an opinion yet.

**Comment by bvaughn** [comment]
#19191

**Comment by NE-SmallTown** [comment]
Sorry Brian, these days are too busy, I did some work on https://github.com/NE-SmallTown/my-understanding-of-react/commit/cebb0267062187838bc94cd91df5c12deb10affc but have not enough time to do more verification, add docs and add tests, so I have to left it there. Sorry agign.
