### ISSUE TITLE
eslint rules: mark certain values as having a stable identity

### ISSUE THREAD

**Issue by seansfkelley** [facebook/react#19125]
eslint-plugin-react-hooks version: 4.0.4

I have the following custom hook:

```js
export function useForceUpdate() {
  const [, setValue] = useState(0);
  return useCallback(() => setValue((v) => v + 1), []);
}
```

But when I use it:

```js
function MyComponent(props) {
  const forceUpdate = useForceUpdate();

  // ... snip ...

  useEffect(() => {
    // do stuff
    forceUpdate();
  }, [foo, bar]);

  // ... continue
}
```

The linter complains (rightfully so):

```
warning  React Hook useEffect has a missing dependency: 'forceUpdate'. Either include it or remove the dependency array
```

It would useful to have a configuration option to tell the linter that `forceUpdate` is guaranteed to have a stable identity, so it can give it the same treatment as e.g. `useState`'s callback. Otherwise, I have to disable the rule every time I use the hook!

**Comment by georeith** [comment]
Made this ticket https://github.com/facebook/react/issues/19217 for the same issue as I didn't see this one, I give more examples and reasoning there.

**Comment by rachelnabors** [comment]
Hello there! This has been requested before, but if we added configuration to the rule, each library would have to ask users to add something to their configs. That would quickly lead to configuration hell! So unlikely we will add this feature in the near future.

**Comment by seansfkelley** [comment]
@rachelnabors can you link to a ticket? I'd like to see the discussion but I don't want to ask you to recreate it for me here.

**Comment by gaearon** [comment]
I'm not sure if there was a ticket but it's been brought up on twitter and elsewhere.

Overall, I think the premise isn't quite right here:

>It would useful to have a configuration option to tell the linter that forceUpdate is guaranteed to have a stable identity, so it can give it the same treatment as e.g. useState's callback. Otherwise, I have to disable the rule every time I use the hook!

You don't have to "disable the rule". You can just specify `forceUpdate` as a dependency. If it truly is stable, there is no harm in doing that.

**Comment by seansfkelley** [comment]
> You don't have to "disable the rule". You can just specify `forceUpdate` as a dependency. If it truly is stable, there is no harm in doing that.

Yeah, that's true. It's a little annoying that I have to go out of my way just to appease the tooling when I could conceivably tell the tool in one place the proper way to behave, but I respect the desire to avoid configuration bloat and the risk that comes with accidentally configuring the tool to not point out bugs, so I'll live with it. Thanks for chiming in!

**Comment by gaearon** [comment]
>I have to go out of my way just to appease the tooling

I wouldn't quite look at it that way.

Consider a custom Hook that returns a stable callback. And a few months later you want to return a callback conditionally. `return cond ? setFoo : setBar`. If all the callsites include the dependency, this change would be entirely safe. If not, it would introduce the bug.

**Comment by seansfkelley** [comment]
> This is the argument for always including the dependencies that don't directly come out of React.

Mm, true, most projects I use/write don't come close to the stability guarantees of React. :)

I suppose I was only thinking only of projects I write that I'm able to keep in my head. I'm convinced that on larger projects with larger teams your suggestion is the right approach, and for those projects where they're all in my head, well, there's no accounting for what damage I might do 6 months in the future.

**Comment by DesignByOnyx** [comment]
I've always been curious if there's a "fast path" in react for hooks with zero dependencies. Like, on initial render, if a hook has zero dependencies, you can optimize things by skipping unnecessary function calls, array length checks, etc and just return the value (useMemo, useCallback) or never even run it again (useEffect). I know iterating lots of small arrays is extremely fast, but if there is indeed a "fast path" inside react, might this actually make a different in a large complicated app?

**Comment by alesmenzel** [comment]
@gaearon Maybe React could provide a helper function like `isStable` that would not be marked by the eslint rule.

```
function useCustomHook() {
  const [a, setA] = useState('some state')
  
  return isStable(useCallback(() => {
    setA(...)
  }, []))
}
```

moreover, `isStable` could throw when the reference changes, therefore guarantee the code is valid
