### ISSUE TITLE
Bug: React is taking longer time to open in Browser

### ISSUE THREAD

**Issue by tarunkishore2303** [facebook/react#19127]
I have just started to learn React. So you can came to a conclusion that _I don't build heavy apps_. When I run `npm start` it takes minimum of 15 seconds to open up in the browser. Herewith I have attached the screenshot for your reference

![image](https://user-images.githubusercontent.com/53224551/84563246-beaddc00-ad77-11ea-80b9-04fa1d984962.png)

**Comment by illuminist** [comment]
You're running in development mode, that startup time is normal as it has many step to initialize multiple tool chain and development server, and the app itself isn't even optimized for performance as in "production mode".

**Comment by aweary** [comment]
As mentioned, it's not unexpected that the initial startup could be somewhat slow. 15 seconds seems a bit excessive to me, but if you're on a slower machine or running other intensive applications it's not unheard of.

If you think there is a bug here please report it to https://github.com/facebook/create-react-app

**Comment by menezesmario** [comment]
It was happening here, I deleted the folder node modules and ran `npm update`. So I solved the problem.
