### ISSUE TITLE
Bug: Events dispatched twice on Server and client using React.hydrate 

### ISSUE THREAD

**Issue by dmitrirussu** [facebook/react#19122]
I have  issue using react SSR... from documentation I understood that events are dispatched only once on Server when we execute renderToString... after we get content rendered on server.... client only Hydrate dom elemements to get them active for next usage... 

I'm facing next issue... my events are dispatched twice on Server and Client... How I can avoid this... to keep dispatch events only on Server for first rendering... and when execute hydrate do not be triggered....

**Comment by threepointone** [comment]
Please be more specific. What events are you talking about? Do you have an example? Can you make a reproducible example with codesandbox, or as a git repo? We can only comment on actual code if you have any.

**Comment by dmitrirussu** [comment]
> Please be more specific. What events are you talking about? Do you have an example? Can you make a reproducible example with codesandbox, or as a git repo? We can only comment on actual code if you have any.

yes... Events componentDidMount, componentWillMount, .... useEffect.....

how does React renderToString... and hydratation for components? because I do not have any solution how to prevent redux dispatch Event from second exection on client.... 

What I'm expecting when we renderToString React App on Server... to dispatch only once the request.... using one of **LifeCycle** .... as I understood React does not trigger componentWillMount on React.hydratation that mean we could use dispatch Event on componentWillMount... BUT THIS DOES NOT WORK.... also componentWillMount is deprecated... 

how I can avoid dispatching second event from client?
it is not supposed do not be triggered any event on hydratation?

**Comment by illuminist** [comment]
It should make sense that react need to construct itself up again to match the existing DOM for hydration in client side. So it's just unavoidable to not have lifecycle function called in both client and server. To make another sense, you already have data in the "HTML string" from `renderToString` function, but react cannot use or access that data, therefore it need to fetch the data again for its usable form.

In conclusion, you need another approach for your app, maybe:

1. Don't hydrate with react, just display the data as html.
2. Fetch the data, then inject into App root: `React.renderToString(<App intialData={mydata}/>)` then somehow serialize and embed `mydata` along with HTML page. Then hydrate in clientside: `React.hydrate(<App initialData={JSON.parse(mydata)}/>, rootElement)`
3. Use actual SSR library, such as NextJS, Gatsby, etc.

**Comment by gaearon** [comment]
This issue is very vague and hard to reply to. If you still have a question please file another one with a specific code example and a more specific question.
