### ISSUE TITLE
Bug: useReducer initialState does not create a new object

### ISSUE THREAD

**Issue by crobinson42** [facebook/react#19126]
React version: 16.11.0 (react-native 0.62.2)

## Steps To Reproduce

1. define at the top of the custom hook or component file `const initialState = {}`
2. Use the initialState in useReducer in the component file `const [state] = useReducer(reducer, initialState)`
3. If you assign a prop directly to `state` it persists on the `initialState` object throughout the life of the JS execution environment

```js
import { useCallback, useEffect, useReducer, useRef } from 'react'

const cache = {}

const initialState = {
  data: undefined,
  loading: true,
}

function reducer(state, payload) {
  return { ...state, ...payload }
}

export default function useMyCustomDataFetcher(modelName, id) {
  const _local = useRef({ firstRun: true })

  const [state, dispatch] = useReducer(reducer, initialState)

  if (_local.current.firstRun) {
    if (!cache[modelName]) cache[modelName] = {}

    // check if there is a cached value to return in the first render
    state.data = cache[modelName][id]

    _local.current.firstRun = false
  }

  const runQuery = useCallback(async () => {
    // do some async work here
    fetch(`/api/${modelName}/${id}`).then((data) => {
      dispatch({ data, loading: false })
    })
  })

  useEffect(() => {
    runQuery()
  }, [id, modelName])

  return state
}

```

## The expected behavior

I expect the `useReducer()` to create a new object out of initial state - this can causes really difficult to debug issues by the simple mistake.

The solution for my example ☝🏼 hook above is to do this: `useReducer(reducer, { ...initialState })` so that a new object reference is created every time this hook is used.

**Comment by illuminist** [comment]
Why exactly it need to create a totally new object? What is your "simple mistake" you said?

It's fine as long as you don't mutate the state like `state.data = cache[modelName][id]` which is something you must not do when dealing with reducer state.

**Comment by vkurchatkin** [comment]
> The solution for my example ☝🏼 hook above is to do this: useReducer(reducer, { ...initialState }) so that a new object reference is created every time this hook is used.

This is a good demonstration why current behaviour is the best: you are making a shallow copy, so it doesn't really protect from mutating the state. You need to make deep copy to achieve that, bu there is no generic way to do that correctly.

**Comment by bvaughn** [comment]
This is not a React bug. I would say this is a bug in the same code you linked though, as you should **never directly mutate React state** (including reducer state).

By the way, you might be interested in checking out the lazy initialization pattern in our docs:
https://reactjs.org/docs/hooks-reference.html#lazy-initialization
