### ISSUE TITLE
Notify application when JSXTransformer has completed processing JSX

### ISSUE THREAD

**Issue by fleaflicker** [facebook/react#1913]
As first discussed in https://github.com/facebook/react/pull/1558#issuecomment-48955852 .

Use case: Application code is in `app.js`; react code is in file `ui.jsx`. In development, both are included along with `JSXTransformer`. There's no way for `app.js` to reliably reference components defined in `ui.jsx`. (In production, JSX is first translated, then all JS files are combined/compiled together, so this is not an issue.)

As noted in the above comment, there are workarounds.

**Comment by spicyj** [comment]
If you need this, I believe you can add

```
<script type="text/jsx">
MyApp.init();
</script>
```

or similar after the external script tags and that will queue it correctly.
