### ISSUE TITLE
Bug: HTML contains ant design components can not be expected to display

### ISSUE THREAD

**Issue by SpiritLing** [facebook/react#19135]
_Translated by Google_

React version: 16.13.1

## Steps To Reproduce

1. Just run it directly

Link to code example: https://codesandbox.io/s/adoring-http-e934x

## The current behavior
Convert ant-design Button to button

## The expected behavior

ant-design Button is not allowed to be converted to button, but to ant-design style

**Comment by illuminist** [comment]
What you put into HTML text is not ant-design Button, it's just regular HTML tag. HTML tag is case-insensitive, so even you write it as "Button", "bUTTON", "BuTToN", etc, it will be treated as "button" regardless.

**Comment by SpiritLing** [comment]
Is there a way to achieve this function, the html string contains ant design components, after conversion can achieve the correct display

_Translated by Google_

**Comment by illuminist** [comment]
There's no way to do that and retain any functionality of the component. `dangerouslySetInnerHTML` is primary just an escape hatch to display html element only. So best you can do is putting element with correct class name to match what antd has, but you cannot assign event to those element to talk back to react.

You should note that you should not use `dangerouslySetInnerHTML` as it's a high security risk, hence `dangerously` in the name.

**Comment by SpiritLing** [comment]
Thank you! I tried to add the class of ant component in `button`, it was successfully displayed
