### ISSUE TITLE
Bug: useState with ResizeObserver leaks React components on Safari 13.1

### ISSUE THREAD

**Issue by luketmillar** [facebook/react#19131]
_From what I can tell this only repros in Safari._
React version: 16.13.1
Safari : 13.1.1

### Description

Using the Safari dev tools, specifically the Graphics tab to track active canvas contexts, I noticed that Safari was infinitely collecting canvas contexts as React components mounted and unmounted. They were never garbage collected. After pairing back my use case I was able to narrow it to a very specific repro.

**If you have a React component that instantiates a ResizeObserver AND captures the result of React.useState, it will never get garbage collected.**

I'm not positive, but I assume that the full React component is leaking in these cases, although I can only see the canvas contexts leaking because that's what Safari devtools makes easy to see.

### Code

**Leak repro:**
If you mount and unmount this `SizedCanvas` component over and over the canvas contexts will leak.
```javascript
const LeakyResizeDetector = () => {
    const x = React.useState(false)

    React.useEffect(() => {
        const observer = new ResizeObserver(() => null)
        return () => observer.disconnect()
    }, [])

    return <div />
}

const SizedCanvas = () => {
  return <>
    <LeakyResizeDetector />
    <canvas ref={ref => ref && ref.getContext('2d')} />
  </>
}
```

**Clean repro:**
If you mount and unmount this `SizedCanvas` component over and over the canvas contexts will get garbage collected and you'll remain in a clean state.
```javascript
const CleanResizeDetector = () => {
    React.useState(false)

    React.useEffect(() => {
        const observer = new ResizeObserver(() => null)
        return () => observer.disconnect()
    }, [])

    return <div />
}

const SizedCanvas = () => {
  return <>
    <CleanResizeDetector />
    <canvas ref={ref => ref && ref.getContext('2d')} />
  </>
}
```

The only difference between these two examples is that the leaky component captures the result of the `useState` call. Other than that they are identical.

## The current behavior
Canvas contexts infinitely collect and never get garbage collected.

## The expected behavior
Canvas contexts get garbage collected as their React components get unmounted.

**Comment by vkurchatkin** [comment]
There is no reason to assume a bug in React. If there is an actual leak, bug in Safari is most likely

**Comment by luketmillar** [comment]
Yep, that makes sense. But since I’m unable to find a repro outside of React and I don’t know which is responsible I figured I would start here.

**Comment by vkurchatkin** [comment]
Investigating it as React bug seems pointless for a simple reason:

`const x = React.useState(false)` couldn't be possibly distinguished from `React.useState(false)` by React even if it tried to, it is simply not possible to detect if a value is assigned to something or not. So, from point of view of JavaScript code, this two snippets are identical.

**Comment by luketmillar** [comment]
fwiw, I also filed a radar for this issue.

But it seems like even if it is a Safari bug, the idea of a circular reference in React hooks causing memory leaks in Safari, is something the React team should be aware of, even if ends up not being their bug to fix.

Also, I verified that this same bug occurs with an IntersectionObserver. So it’s not specific to ResizeObservers.

**Comment by clark-pan-canva** [comment]
@luketmillar I've been having a similar issue, and I suspect its a Safari issue with `ResizeObserver`: https://bugs.webkit.org/show_bug.cgi?id=215158
