### ISSUE TITLE
Could you please rename master branch and remove any problematic references?

### ISSUE THREAD

**Issue by ghost** [facebook/react#19134]
There are many people doing the same in light of BLM and deep racist history associated with words such as blacklist, whitelist, slave, master and many others which see wide use in CS and code.

There are many big projects doing the same - golang, rustlang, python.

Here is a note from github CEO - https://twitter.com/natfriedman/status/1271253144442253312

Could you please remove racism from code?

PS - Historical context for main - https://www.nakasendoway.com/the-japanese-family-system/

Please consider alternatives such as canary, develop or edge.

**Comment by octoda** [comment]
Updating the branch name would force every contributor to have to update their local Git config.

Also, what problematic references are you talking about? If it's so important to you, why not submit a PR?

**Comment by T-x-T** [comment]
FYI they deleted their account, so you wont get an answer and definitely no pr

**Comment by octoda** [comment]
> FYI they deleted their account, so you wont get an answer and definitely no pr

Lol, just realised that, thanks for pointing it out 😆😆

**Comment by threepointone** [comment]
> Updating the branch name would force every contributor to have to update their local Git config.

Why is this a problem? Big deal, it’ll take takes seconds if not minutes.

**Comment by gaearon** [comment]
While I’m not sure whether the original post was sincere or written by a troll, the branch name change suggestion sounds reasonable. It might take us some time to figure out the plan (half of the team are on the move this week) but we’ll discuss this in close future. After we’ve reached a conclusion, we will update you in this thread. 

In the meantime, I’m going to lock this thread to prevent trolling and drive-by comments that are too common in threads like these. Please remember that trolling, flame-baiting and other attention seeking behavior are not tolerated in this repository and will result in a ban.

**Comment by bvaughn** [comment]
Quick update for this issue.

We intend to rename this branch. However, it's a bit more involved than we realized originally. For example, renaming/deleting the master branch right now would close all 128 open Pull Requests- and reopening them would be either not possible, or it would be difficult.

We are coordinating with GitHub on some tooling to make this work better. We will update this issue with more info as we get it.

**Comment by gaearon** [comment]
Been renamed a while ago.
