### ISSUE TITLE
Bug: Invalid hook call in React Native; verified all known causes

### ISSUE THREAD

**Issue by Tycholiz** [facebook/react#19144]
I'm getting the [Invalid Hook Call](https://reactjs.org/warnings/invalid-hook-call-warning.html) warning, and I've gone down the list of the potential causes and have ruled out (as far as I can tell) all of them:

1. Mismatching versions of `react` and `react-dom`
- from my `package.json`
```
"dependencies": {
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
}
```

2. Breaking rules of hooks
- my component:
```
const CaptureScreen = () => {
    const [stuff, setStuff] = useState(0)

    return (
        <DefaultTemplate >
            <NuggetAdder />
        </DefaultTemplate>
    )
}
```

3. Multiple versions of react
- I've `required` react from `node_modules/react-dom/index.js` and set it to `window.React1`, and from the component `CaptureScreen` (above) I have done the steps listed in the "Invalid hook call documentation" and set up `window.React2`. When I log `window.React1 === window.React2`, I get back `true`.
- I'm not certain this is reliable since I use `yarn`, but running `npm ls react` returns: 
```
myproject@0.0.1 /Users/me/programming/projects/my-project/client
└── (empty)
```

React version: 16.13.1
React-native version: 0.62.2

**Comment by vkurchatkin** [comment]
There is no way to tell without a complete example.

**Comment by vkurchatkin** [comment]
Also it's somewhat unclear from your post, but if you are actually using React Native, then React 16.11 should be the right version

**Comment by Tycholiz** [comment]
@vkurchatkin I've downgraded my version of react and react-dom to 16.11.0 (is this actually written somewhere?), but the issue persists.

what can I show you that will help diagnose the issue? I am not sure how to make an example since I have no idea what is causing the issue in the first place.

**Comment by bvaughn** [comment]
Why is `react-dom` involved here? Your title says "React Native" but you've mentioned `react-dom` a few times.

**Comment by Tycholiz** [comment]
@bvaughn that fixed it!

I forget the exact reason why I added `react-dom` in there in the first place, but I have a feeling it was related to unit testing with Jest. I always questioned why it was in there as well, but figured that Jest was using it for mocks or something.

Phew, that solves a long and drawn out case! Hope this can help someone else.
