### ISSUE TITLE
Bug: props should update 

### ISSUE THREAD

**Issue by yyyang1996** [facebook/react#19148]
React version: 16.12.0

## Steps To Reproduce

Link to code example: [CodeSandbox demo](https://codesandbox.io/s/ecstatic-vaughan-vtsqd?file=/src/App.js)

## The current behavior
Click the add button,  `<Counter />` rerender,  `props.count` is prev value and `count` is latest value.

## The expected behavior
`props.count === count`

**Comment by illuminist** [comment]
Is that your intention to always return `true` in memo's equality test function? Memoized props will be unchanged if equality test is `true` as it still holds the previous element with previous props.

**Comment by bvaughn** [comment]
Check out the docs:
https://reactjs.org/docs/react-api.html#reactmemo

The second arg (the `areEqual` function) you're passing is supposed to:
> return true if passing nextProps to render would return the same result as passing prevProps to render, otherwise return false

That's not the case in your example sandbox.

https://codesandbox.io/s/eager-cache-m6kz6
