### ISSUE TITLE
Bug: ESLint react-hooks/rules-of-hooks false negative when using default export with high-order functional component

### ISSUE THREAD

**Issue by tabuchi0919** [facebook/react#19155]
React version: 16.13.1
eslint-plugin-react-hooks version: 4.0.4

## Steps To Reproduce

1. Enable react-hooks/rules-of-hooks rule.
2. Lint following code.

```js
import React from 'react';
export const Foo = () => () => {
  React.useState(undefined);
  return <></>;
};
export default () => () => {
  React.useState(undefined);
  return <></>;
};
```

## The current behavior

ESLint does not show react-hooks/rules-of-hooks error when using export default.

## The expected behavior

ESLint shows following react-hooks/rules-of-hooks error even when using export default.

>React Hook "React.useState" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.eslint(react-hooks/rules-of-hooks)

**Comment by yuichkun** [comment]
I started working on a fix on this.

As I've read through the code and did some searching, I'm starting to think this is a bit complicated situation to fix regarding the structure of the AST and how `export default` works in combination with an anonymous function.

With that being said: 
I'll shortly send a PR, and hope to get feedback since I'm no expert in code analysis sort of thing :)

**Comment by gaearon** [comment]
>ESLint shows following react-hooks/rules-of-hooks error even when using export default.

This is correct behavior. There is nothing for the lint rule to know that your unnamed function is actually a React component. In general, not giving exports names is a bad practice because you won't get meaningful stack traces.

```js
export default function generateMyComponent() {
  return function MyComponent() {
    React.useState(undefined);
    return <></>;
  }
};
```

This should work.

**Comment by tabuchi0919** [comment]
Thank you for your comment!
I will use named export from now on.
