### ISSUE TITLE
Issue: No privacy policy for React Developer Tools Chrome extension

### ISSUE THREAD

**Issue by adityabhaskar** [facebook/react#19152]
React Developer Tools version: 4.7.0

## Steps To Reproduce

1. Visit [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) on Chrome Web Store and look for a privacy policy under 'Additional Information' and 'Overview'
2. Visit [React Developer Tools](https://github.com/facebook/react/tree/master/packages/react-devtools-extensions) on github and check for a privacy policy.

## The current behaviour

No privacy policy available detailing if the browser extension uses any user data and, if yes, how. This is more important considering that the extension requires permission to access data on all tabs and websites.

## The expected behavior

Provide a privacy policy, preferably both here in the repository and on the Chrome Web Store, explaining how the user data is used, specially if any data is transferred off the machine.

**Comment by bvaughn** [comment]
Chrome store does not require privacy policies from extensions **unless they use personal or sensitive data** (see [here](https://developer.chrome.com/webstore/program_policies#userdata)). Our extension does not store or track any data.

**Comment by adityabhaskar** [comment]
Hi @bvaughn 

Thanks for responding. I'm glad to hear that the extension doesn't use any data. It'd be helpful to have that declared in the extension listing directly.

The section you linked also details what they call personal or sensitive data:

> website content and resources, form data, web browsing activity,...

Using the `tabs` permission gives an extension full access to that information. Whether that information is not used, stored, or stored and transferred could be detailed in a privacy policy. You may also have just a privacy statement, in the extension description, saying that you don't store, transmit or track any data. 

In the current state, the `tab` permission gives this extension access to all that information, but there's no declaration anywhere about how you do or don't use that information.

Cheers!

Adi

**Comment by adityabhaskar** [comment]
> Our extension does not store or track any data.

Hi @bvaughn, can this be stated on the extension page on Chrome Web Store? That will make the statement a bit more formal and assure users that this is actually the followed policy.

Cheers!

**Comment by bvaughn** [comment]
We're adding this to the browser extension pages:
> This extension requires permissions to access the page's React tree, but it does not transmit any data remotely. It is fully open source, and you can find its source code at https://github.com/facebook/react/tree/master/packages/react-devtools-extensions.

Hopefully it covers your concerns. Thank you!

**Comment by adityabhaskar** [comment]
Thank you @bvaughn !

**Comment by SYWTech-hub** [comment]
When I tried to add the React Developer Tools extension to my chrome, this is the message I got:

**It can read and change all your data on all websites.** 

Can the Extenstion also explain how it can read and change all data on all websites? I did not get the message that is described above by bvaughn.

**Comment by M-Agoumi** [comment]
I just got an update, that asked to read all my browser tabs, I'm trying to find privacy policy and I stumbled upon this, did the case of not storing/tracking any data still true?
