### ISSUE TITLE
React Developer Tool Is not working in my localhost. It was working fine before.

### ISSUE THREAD

**Issue by Dashsuraja** [facebook/react#19151]
Hi Team

I am not able to use the react developer tool extension on my chrome browser, Which was working well before.  I have tried by removing and re adding the extension again. Still the problem persists.

I have attached a screenshot of the tool Icon on browser. I am very new to react Environment. Appreciate your help here.

Thank you.

![image](https://user-images.githubusercontent.com/28383863/84981630-8f6de500-b152-11ea-909f-f386f226d7ee.png)

**Comment by roseak** [comment]
Same problem for me. Components and Profiler are no longer displaying as options.

**Comment by olivercheok20** [comment]
I'm experiencing the same, components and profiler don't show up on DevTools anymore.

**Comment by olivercheok20** [comment]
The suggestions here in the README didn't work for me but you guys can try for yourselves to see if they were the problem @roseak @Dashsuraja 

https://github.com/facebook/react/tree/master/packages/react-devtools#the-react-tab-doesnt-show-up

**Comment by Dashsuraja** [comment]
There are many discussions done regarding the same issues on ticket #19002..its a open issue...
 Seems like an issue with latest browser update.. please have a look there. You may get some ides.

**Comment by bvaughn** [comment]
This is caused by a Chromium bug. We're tracking it here #19002

**Comment by olivercheok20** [comment]
For the record, I've been able to use react-devtools from the command line just fine to get the Components and Profiler tabs out (albeit in a separate Electron window).

If anyone chancing upon this issue has the same problem and you really need those tabs you can consider installing the standalone app. No guarantees it'll work but at least it's something else to try.

**Comment by carelulu-jonathan** [comment]
> For the record, I've been able to use react-devtools from the command line just fine to get the Components and Profiler tabs out (albeit in a separate Electron window).
> 
> If anyone chancing upon this issue has the same problem and you really need those tabs you can consider installing the standalone app. No guarantees it'll work but at least it's something else to try.

I'll try it but does it have the feature like in chrome where you hover to an item and it will show the react component for it?

**Comment by giriawu** [comment]
Using mac v11.5.1
and latest release Chrome Microsoft Edge and Firefox. Even have tried react-dev-tools v3.
All Not work. 
Still remain blank.

**Comment by olivercheok20** [comment]
> > For the record, I've been able to use react-devtools from the command line just fine to get the Components and Profiler tabs out (albeit in a separate Electron window).
> > If anyone chancing upon this issue has the same problem and you really need those tabs you can consider installing the standalone app. No guarantees it'll work but at least it's something else to try.
> 
> I'll try it but does it have the feature like in chrome where you hover to an item and it will show the react component for it?

Yes, it does have that feature. I think my suggestion to anyone facing this problem now is to simply use react-devtools from the command line. All of the functionalities are the same as on the Chrome extension. The only difference that I've been able to find is that the Devtools window opens in a different window, whereas on the Chrome extension it opens as part of the Chrome interface.

**Comment by mikehdt** [comment]
I have found if you're using a fake domain with localhost, e.g.
http://localhost:3000 and http://my.test.domain:3000 (using a `hosts` entry) then the devtools seems to not initialise. Security issue perhaps?

**Comment by pranayb703** [comment]
I was using http://localhost:3000, I went to extensions and reset the settings like toggle them  and it started showing components and profiler tabs for me.. I dont know thats a solution, but it worked for me..
PS Also updated chrome version too.

**Comment by aysha-williams-develop** [comment]
Uninstalling/Removing the extension, then re-adding it to chrome worked for me.

**Comment by brettmadrid** [comment]
Has there been any solution?  I have tried all the above to no avail.

**Comment by mdearafat** [comment]
It works on incognito mode. Just enable the extension for incognito mode  and browse localhost from incognito mode.

**Comment by Chongi23** [comment]
HEY all, found a way to fix this issue..click inspect, go into settings , click ignore list,  under General exclusion rules: uncheck "Content scripts injected by extensions".. I had the issue of not being able to see "components" after doing a chrome update, hope this helps someone!
