### ISSUE TITLE
Bug: Strange onScroll behaviour when child editing

### ISSUE THREAD

**Issue by vladislav-andreevich** [facebook/react#19156]
React version: 16.13.1
OS: Mac OS
Browser: Chrome 83.0.4103.97

## Steps To Reproduce

1. Create a div and add onScroll event to it
2. Create input inside the created div
3. Start typing in the input box.

## The current behavior

Event onScroll is fired on the parent.

## The expected behavior

Scroll event should not fire.

## Link to code example:

https://codepen.io/vladislav-andreevich/pen/zYroQjN

**Comment by AhmaudArbery** [comment]
I haven't worked on React yet, I am still looking, but I did some digging. It seems like this is the intended behavior of React: https://github.com/facebook/react/issues/5622. I'd wait for someone else to verify.

**Comment by guy490** [comment]
I have worked on React, but I think its a bug because "onScroll" should happen when we scroll.
 in this situation, we are not scrolling something, we only enter text.
so I think its an issue.

**Comment by JoaoVitoGomes** [comment]
> It is correct that the event should be caught on the parent, but in this issue, there is no event to catch because there is no scrolling happen.
The input element fires a scroll event.

**Comment by guy490** [comment]
> 
> The input element fires a scroll event. I don't think this is a bug.

Yes, but as I see in Vanilla JS code it does not fire a scroll event, and this "feature" throws :)

**Comment by illuminist** [comment]
It's weird that one of my machine still run on older version of chromium(80.0.3987.163) and scroll event doesn't fire on react component. But another machine with latest chromium(83.0.4103.61) fires the event.

**Comment by gaearon** [comment]
React 17 doesn't bubble scroll events so this would be fixed.
With React 16 or lower, you can add `if (e.target === e.currentTarget)` condition to your handler.
