### ISSUE TITLE
The Component and Profiler disappeared from Chrome

### ISSUE THREAD

**Issue by mightymob** [facebook/react#19163]
The Component and Profiler disappeared from my Chrome Developer Tools. The Extension for the React Developer Tools is installed, it just doesn't show up suddenly in the debug tools screen.

Any help is appreciated. Thank you!

**Comment by Dashsuraja** [comment]
Hi , even same issue for me too.. seems like an issue with latest browser update

**Comment by bvaughn** [comment]
This is caused by a Chromium bug. We're tracking it here #19002
