### ISSUE TITLE
devtool Api request : add api for customize renderer inspect element

### ISSUE THREAD

**Issue by zsytssk** [facebook/react#19168]
I'm wirte a custimse renderer for render element in canvas(like react-pixi), I want intergrate with react dev tool;
I can hightlight element when click element in react dev tool compoent panel use code:
```ts
__REACT_DEVTOOLS_GLOBAL_HOOK__?.reactDevtoolsAgent?._bridge.addListener('highlightNativeElement', (eleInfo: EleInfo) => {
        const { id, rendererID } = eleInfo;
        const renderer = __REACT_DEVTOOLS_GLOBAL_HOOK__?.rendererInterfaces.get(
            rendererID,
        );

        const node_list =
            (renderer.findNativeNodesForFiberID(id) as Sprite[]) || [];

        //... customise render engin hightlight code
    });
```

I want hightlight ele when mouse move in canvas, I can use `__REACT_DEVTOOLS_GLOBAL_HOOK__.rendererInterfaces.get(1).getFiberIDForNative(node)` find node fiber id, I can use `_bridge` send hightlint msg to backend just like the code
https://github.com/facebook/react/blob/6ba25b96df5d4179bf8aba3c3fe1ace3dce28234/packages/react-devtools-shared/src/devtools/views/hooks.js#L311
but I can't get store object and get enugh infomation send to backend.
maybe dev tool can expose proper api for this function

**Comment by zsytssk** [comment]
maybe some api like this;
```ts
const devTool = xxx.injectIntoDevTools({...});
devTool.inspect(Node);
devTool.addListener('highlightNativeElement',(node) => {...});
```

**Comment by bvaughn** [comment]
If your custom renderer is reconciler based, you should be able to import `injectIntoDevTools` from "react-reconciler/src/ReactFiberReconciler and use it in the same way as e.g. react-dom, react-art, react-native

```js
import { injectIntoDevTools } from 'react-reconciler/src/ReactFiberReconciler';
import ReactVersion from 'shared/ReactVersion';

injectIntoDevTools({
  findFiberByHostInstance: () => {
    // Varies based on your renderer ...
  },
  bundleType: __DEV__ ? 1 : 0,
  version: ReactVersion,
  rendererPackageName: 'your-renderer-name',
});
```

**Comment by zsytssk** [comment]
@bvaughn I already use `injectIntoDevTools` api;
I want hightlight ele when mouse move in canvas(inspect), there is no api for this (i dont find);
<img width="726" alt="WX20200623-093757@2x" src="https://user-images.githubusercontent.com/2304648/85351073-62944600-b535-11ea-9f16-82d64ff9adeb.png">

**Comment by bvaughn** [comment]
You don't directly implement this method. This is something that the DevTools and reconciler do together using the injected `findFiberByHostInstance` method. How are you implementing that?

**Comment by zsytssk** [comment]
@bvaughn 
demo code:
https://github.com/zsytssk/react-laya-demo/blob/adf3dc891d5c242a440bf74c303f5045c0f83c68/library/customRenderer/devTool.ts#L59

[the whole demo project](https://github.com/zsytssk/react-laya-demo), you can clone and see demo;

element in canvas is not dom element, when mouse move in canvas devTool cant find target node, cant trigger inpsect;
also devTool cant hightlight element when click node in devTool;

**Comment by bvaughn** [comment]
Ah, I understand what you're saying.

There are no "elements **in** a canvas". Canvas is a single element *itself* that you draw within.

React DevTools was not built to highlight things via x/y coordinates, but rather using the DOM event `target`. For a renderer like yours to highlight, you would need to either (1) be fed a stream of x/y coordinates to do your own hit detection or (2) be sent explicit start/stop signals so you could add your own move event listeners. Neither is supported by DevTools though.

If you'd like to build this and share a PR, I'm willing to review and consider it. It's not something we have the bandwidth to build though.
