### ISSUE TITLE
Failed to compile error when a new project is created 

### ISSUE THREAD

**Issue by wrttoashish16** [facebook/react#19166]
Getting following error when I attempt to run a newly created project using following command
npx create-react-app my-app
cd my-app

When I pass this --> npm start command, I get following error in browser.

```Failed to compile
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Error: Package exports for '..\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
```
![image](https://user-images.githubusercontent.com/65842419/85186486-49567580-b267-11ea-91c9-00eab2827be0.png)

I did google and tried running following commands but no luck.
npm I autoprefixer
npm install node-saas-@latest..

I have following versions listed as dependencies
    "autoprefixer": "^9.8.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"

Note: I tried running old project and that works fine... having issue only when I create a new project from scratch and run.
please advise.

**Comment by bvaughn** [comment]
Seems like a bug with `autoprefixer` or `node-saas`? Or some other tool involved in that building pipeline that had a recent NPM release. Doesn't seem like anything to do with React.

Also looks like the same thing being reported in #19172.

**Comment by bvaughn** [comment]
Let's move this discussion to the create-react-app repo:
https://github.com/facebook/create-react-app

This is definitely not a React issue. It's not a create-react-app issue either, except that maybe CRA should downgrade whichever tool/package recently broke that started causing this.

**Comment by wrttoashish16** [comment]
This was an issue with autoprefixer... downgraded the version and worked. Thanks!
