### ISSUE TITLE
Bug: Background script for React Developer Tools (Chrome) sometimes becomes "inactive"

### ISSUE THREAD

**Issue by technicallynick** [facebook/react#19175]
I've noticed recently that while debugging a new React deployment, the Components and Profiler tabs will go missing from the developer console in Chrome.  In the past, a complete shut down of Chrome and restarting it would correct it. This last time that it happened, I noticed that the background page would just say "background page (inactive)". When clicked, it would open a developer console to inspect the background, but also make it active again.  Once this was done, I was able to refresh a react page and the Components and Profiler tabs would appear again.

For reference, this would happen on known react sites such as Facebook as well.

Chrome Extension Version: 4.7.0 

## Steps To Reproduce
Unknown

**Comment by bvaughn** [comment]
This is caused by a Chromium bug. We're tracking it here #19002
