### ISSUE TITLE
Feature: top api to know if current react app is running in strict mode or concurrent mode

### ISSUE THREAD

**Issue by fantasticsoul** [facebook/react#19171]
can react expose an api like `isStrictMode` or `isConcurrentMode` to let developer know  if current react app is running in strict mode or concurrent mode.

```js
import React from 'react';

function Test(){
   // log true when root node wrapped by React.StrictMode
   const ret = React.isStrictMode();
}

```

**Comment by bvaughn** [comment]
Can you describe why you'd want to use that info?

Strict mode isn't globally on/off like that. It can be on for part(s) of your application only, and whether it's on or not is not something we have any plans to expose via a readable API.

**Comment by fantasticsoul** [comment]
> Can you describe why you'd want to use that info?
> 
> Strict mode isn't globally on/off like that. It can be on for part(s) of your application only, and whether it's on or not is not something we have any plans to expose via a readable API.

Strict mode can be on for part(s) of your application only, so I can control it my self, thank you for your reply.

**Comment by elverick212** [comment]
SSRN-id1104465.pdf<https://drive.google.com/uc?id=14mIlmy3hyxfPyruOHu2ENjjJLrVcBzAR&export=download>

Elverick D. Ferrell​​​

________________________________
