### ISSUE TITLE
Anomaly in rendering of self closing versus explicit opening and closing of the same custom tag.

### ISSUE THREAD

**Issue by Samarth484** [facebook/react#19183]
The bug reflects light on the anomaly in the rendering of source code while using self closing custom tag, in contrast to using open and close form of the same tag which showcases a different render, thereby breaking the uniformity and the congruence of opening and closing tags and their corresponding self closing tags.

React version: 16.13.1
React DOM version: 16.12.0
React Sripts version: 3.0.1
 
## Steps To Reproduce

1. To run online- Check out the Sandbox links.
2. To run locally- Check out the GitHub repository (the commits links of which are given) and clone it. 

Link to code example:

The source code of this link gets rendered fine (Meets Expected Render Case):
https://5n5rz.csb.app/

CodeSandbox link:
https://codesandbox.io/s/5n5rz?file=/src/components/App.jsx

(GitHub commit link)
https://github.com/Samarth484/Emojipeida/commit/91ae31bb8acc8bf8fd037e42fdd155e135501081

![ReactProblemPic2](https://user-images.githubusercontent.com/59834694/85450498-73d16700-b5b6-11ea-9b6d-d1a96c55a4e6.PNG)

The source code of this link does NOT gets rendered as expected (Doesn't meets Expected Render Case).
https://lho3o.csb.app/

CodeSandbox link:
https://codesandbox.io/s/lho3o?file=/src/components/App.jsx

(GitHub commit link)
https://github.com/Samarth484/Emojipeida/commit/be64fa3e65c91f0d7ca958ce9e83d3cef078f1e3

![ReactProblemPic1](https://user-images.githubusercontent.com/59834694/85449863-da09ba00-b5b5-11ea-9294-2ac7f98b458a.PNG)

## The current behavior
Both the source codes (of the above sets of links) are EXACTLY same, the only minute difference is that in the first set of links there is a self closing tag and due to which the code gets rendered fine, but in the second case (second set of links) that very same tag is in the form of a opening and a closing tag explicitly, and this distorts the entire expected rendering!

## The expected behavior
The rendering should be alike whether we use self closing tags or open and close them explicitly.

**Comment by vkurchatkin** [comment]
This renderers `Entry` with 4 props

```js
  <Entry
      key={emojiTerm.id}
      emoji={emojiTerm.emoji}
      name={emojiTerm.name}
      meaning={emojiTerm.meaning}
    >
    </Entry>
```

This renderers `Entry` with a bunch of text as children

```js
  <Entry>
      key={emojiTerm.id}
      emoji={emojiTerm.emoji}
      name={emojiTerm.name}
      meaning={emojiTerm.meaning}
    </Entry>
```

**Comment by Samarth484** [comment]
No @vkurchatkin you misinterpreted the issue raised! That's not what has been raised, what you say is corrected but is totally out of context, I request you to check out the issue once again.

Its not about props and children, if about self closing of tags and their explicit opening and closing behavioral anomaly.

You've used Explicitly opened and closed <Entry> tag in your above comment in both the examples, thereby misinterpreting the issue!

In one line I proposed the <Entry bunch of attributs.............................></Entry>          vs              <Entry bunch of attributes.............../>   renders unlikely.

Hope this was insightful and sufficiently explanatory.

**Comment by vkurchatkin** [comment]
> Its not about props and children, if about self closing of tags and their explicit opening and closing behavioral anomaly.

There is no anomaly. Self-closing elements and explicitly opened and closed elements are compiled to exactly the same code.

**Comment by Samarth484** [comment]
> > Its not about props and children, if about self closing of tags and their explicit opening and closing behavioral anomaly.
> 
> There is no anomaly. Self-closing elements and explicitly opened and closed elements are compiled to exactly the same code.

Yes, that's what I believe and suppose, but after the hands on, I found that they aren't getting compiled alike and hence aren't resolving to the same render, thereby making me raise this issue!

**Comment by bvaughn** [comment]
Your source code screenshot shows a syntax error. This is not valid syntax:
```js
<Entry>
  key={emojiTerm.id}
  emoji={emojiTerm.emoji}
  name={emojiTerm.name}
  meaning={emojiTerm.meaning}
</Entry>
```

This is:
```js
<Entry
  key={emojiTerm.id}
  emoji={emojiTerm.emoji}
  name={emojiTerm.name}
  meaning={emojiTerm.meaning}
></Entry>;
```

And this is:
```js
<Entry
  key={emojiTerm.id}
  emoji={emojiTerm.emoji}
  name={emojiTerm.name}
  meaning={emojiTerm.meaning}
/>;
```

**Comment by Samarth484** [comment]
Yes, thank you so much @bvaughn !
You're really a pro!
Thank you so much for your advice and time!
