### ISSUE TITLE
Bug: npx create-react-app my-app returns error

### ISSUE THREAD

**Issue by farhan2077** [facebook/react#19185]
Typing npx-react-app doesn't work. It throws error.

## Steps To Reproduce

 `npx create-react-app my-app`

## The current behavior
![cmd_PFUUb2Y3Lu](https://user-images.githubusercontent.com/32035481/85506763-ce001580-b612-11ea-821e-83eb39cbfc22.png)
Th error shown in cmd is:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Amin\AppData\Roaming\npm-cache\_npx\2956" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Farhan Bin Amin\AppData\Roaming\npm-cache\_logs\2020-06-24T05_56_16_593Z-debug.log
Install for [ 'create-react-app@latest' ] failed with code 1
```
The debug log file is:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-react-app@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\Farhan',
1 verbose cli   'Bin',
1 verbose cli   'Amin\\AppData\\Roaming\\npm-cache\\_npx\\2956',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose npm-session a74bdc721a94d85a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for file:Amin\AppData\Roaming\npm-cache\_npx\2956 Could not install from "Amin\AppData\Roaming\npm-cache\_npx\2956" as it does not contain a package.json file.
8 http fetch GET 304 https://registry.npmjs.org/create-react-app 242ms (from cache)
9 silly pacote tag manifest for create-react-app@latest fetched in 262ms
10 http fetch GET 404 https://registry.npmjs.org/Bin 1039ms
11 http fetch GET 404 https://registry.npmjs.org/Bin 939ms
12 silly fetchPackageMetaData error for Bin@latest 404 Not Found - GET https://registry.npmjs.org/Bin - Not found
13 timing stage:rollbackFailedOptional Completed in 2ms
14 timing stage:runTopLevelLifecycles Completed in 2027ms
15 verbose stack Error: ENOENT: no such file or directory, open 'F:\react\Amin\AppData\Roaming\npm-cache\_npx\2956\package.json'
16 verbose cwd F:\react
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "create-react-app@latest" "--global" "--prefix" "C:\\Users\\Farhan" "Bin" "Amin\\AppData\\Roaming\\npm-cache\\_npx\\2956" "--loglevel" "error" "--json"
19 verbose node v12.16.3
20 verbose npm  v6.14.4
21 error code ENOLOCAL
22 error Could not install from "Amin\AppData\Roaming\npm-cache\_npx\2956" as it does not contain a package.json file.
23 verbose exit [ 1, true ]

```
Also I have I have node version `12.16.3` and npm version `6.14.4` installed. My pc is running windows 10.

**Comment by Samarth484** [comment]
I too faced the same issue: just update your node.js version to the latest one.
then run the following command in your terminal:
```
npm install -g npm@latest

```

It should work after doing the above steps and the lite server would then be up and running!

**Comment by farhan2077** [comment]
Only running command `yarn create react-app my-app` in powershell with admin privilege seemed to do the trick. Still can't understand why npx/npm didn't work. @Samarth484

**Comment by Samarth484** [comment]
> Only running command `yarn create react-app my-app` in powershell with admin privilege seemed to do the trick. Still can't understand why `npx`/`npm` didn't work. @Samarth484

That's an altogether different approach @farhan2077 , I too tried out yarn, after reading one of the stackoverflow posts, and was really troubled to because the yarn thing did help me create a custom react app, but when you are on the outlook to clone and run any other react project then even yarn won't work, hence I advise you to execute ``` npm install -g npm@latest```  and then carry on with your pursuit, because this will not only help you create your own local react app, but also allow you functionality to host any cloned random react project on your local server as well, which yarn would not be able facilitate.

Good Luck @farhan2077

**Comment by bvaughn** [comment]
Please file create-react-app errors in the create-react-app issue. Different people maintain this repo and that one :smile:

https://github.com/facebook/create-react-app/issues
