### ISSUE TITLE
Bug: The context component can't be identified.

### ISSUE THREAD

**Issue by ShenLanJohn** [facebook/react#19201]
The context component can't be identified.

use use this code to reproduce: 
```
                    **<AppContext.Consumer>** 
                      **{ context => (**
                        <dev> It work fine if '{ context => (' in a new line
                      )} 
```

```
                    **<AppContext.Consumer>  { context => (**
                        <dev> It doesn't work if '{ context => (' in the same line
                      )} 
```

Error:
TypeError: render is not a function
![image](https://user-images.githubusercontent.com/49762389/85904540-db0d3800-b7bd-11ea-9422-6143adb2daa6.png)

Thanks,
John Liu

**Comment by illuminist** [comment]
```
<AppContext.Consumer>  { context => (
                     ^^ These extra spaces
```
The extra spaces make the children of AppContext.Consumer to be multiple children: [textNode, functionNode], instead of a single functionNode, as the space is counted as textNode.

**Comment by bvaughn** [comment]
> The extra spaces make the children of AppContext.Consumer to be multiple children: [textNode, functionNode], instead of a single functionNode, as the space is counted as textNode.

This is correct. The "bug" being reported here is that the JavaScript generated from the "bad" code snippet here is not valid for the Context API.

**Comment by akash-kandasamy** [comment]
hey buddy can u explain this project on how it works
