### ISSUE TITLE
Inconsistent design: forceUpdate() not updating PureComponent 

### ISSUE THREAD

**Issue by virtumonde** [facebook/react#19206]
React version: 16.13.1

## Steps To Reproduce

1. Make a PureComponent;
2. Call this.forceUpdate();

## The current behavior
forceUpdate() is not updating the component if the props and state are the same (as expected).

## The proposed behavior
Force update the component, as the name of the method says.

## Why?
Yes, this is an anti-pattern but the .forceUpdate() method is too. There are edge cases where this might be helpful as with forceUpdate().

**Comment by sophiebits** [comment]
This should work correctly already. Can you provide a codesandbox demonstrating the problem, as the issue template asks for?

**Comment by aweary** [comment]
@virtumonde [here's an example](https://codesandbox.io/s/late-platform-o15vf?file=/src/App.js) showing `forceUpdate` working in a `PureComponent`. If you're still having trouble and think this is a bug in React, please follow up with a CodeSanbox reproducing your problem and we can look at it. Thanks!

**Comment by virtumonde** [comment]
Yes, it was indeed a problem on my side. Thank you @aweary.
