### ISSUE TITLE
Bug: React slower in production than in dev than in codesandbox

### ISSUE THREAD

**Issue by Twiggeh** [facebook/react#19203]
React version: 16.13.1

## Steps To Reproduce

1. Make a box follow the mouse cursor
2. There it is (or not)

![Performance gif](https://user-images.githubusercontent.com/23149166/85926187-eb94df80-b89d-11ea-9781-3d7c936d91bd.gif)
I have a peculiar problem, my code runs well in codesandbox, but it doesn't run well in my local build. The only difference between the code in the sandbox and the local build is that the component is nested in a router, everything else is identical.

If I turn on the dev tools' highlighter for what components were re-rendered only the box gets a border as expected

Link to code example: [Code SandBox](https://codesandbox.io/s/mystifying-bas-ninz2?file=/src/lobby_index.jsx)

## The current behavior
Slow and laggy

## The expected behavior
Same as in the sandbox

**Comment by Twiggeh** [comment]
It seems like EmotionJs might be the culprit, but once again it only doesn't work on my machine, the code sandbox works well.

**Comment by aweary** [comment]
It sounds like there might be some environment issues causing performance problems. From this example it doesn't look like there's reason to suspect a bug in React, so I'm going to close this out. If you can isolate a reproducible performance regression or anomaly between prod and dev builds please follow up and we can look into it.

 If you have general questions about this I recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).

Thanks!
