### ISSUE TITLE
Unexpected behaviour on Input element onKeyPress event

### ISSUE THREAD

**Issue by marcbelmont** [facebook/react#1920]
Here's the element I have:

React.DOM.input({onKeyPress: this.onKeyPress});

onKeyPress: function(event) {
      if (event.keyCode === 13) // Enter key
        event.preventDefault();
}

With react 0.10, preventDefault was working. On 0.11, with the focus on the input, pressing enter does a form submit and reloads the page.

I've also tried doing the preventDefault on the onKeyDown event with no luck.

**Comment by Benjaki2** [comment]
Has there been any progress on this ticket? I am dealing with the same issue.

**Comment by Aweary** [comment]
@Benjaki2 can you share a JSFiddle reproducing the issue? You can use http://jsfiddle.net/ropbvL3y/ as a starting point.

**Comment by viniciusdacal** [comment]
@aweary 
Tested here, it seems to be working as expected.
Mac OSX (Firefox 52.0.2, Chrome 57.0.2987.133);
http://jsfiddle.net/waqs2zy0/

**Comment by nhunzaker** [comment]
Thank you, @viniciusdacal! I've tested this on:

- Windows Firefox 46
- OSX Safari 10.1.1
- OSX Chrome

I am unable to reproduce, and I believe this is fixed.
