### ISSUE TITLE
Add anti-tamper mechanism

### ISSUE THREAD

**Issue by uncttao** [facebook/react#19210]
**Issue**

HTML editing is being abused by scammers to deceive gullible victims and extort their money. This usually happens in a fake tech support setting where the scammer first gains remote access to the victim's computer and pull up the victim's online banking website. Then, the scammer tries to distract the victim while at the same time open up the developer console and manually edit the HTML of the banking website to convince the victim that money is added to their account. Finally, the scammer proceeds to claim they added more money than s/he should and demands the victim to return the additional amount by purchasing the scammer gift cards, etc. The scam concludes if the victim falls for it.

Source: 
https://www.youtube.com/watch?v=03fvkJ27eOs (An Internet vigilante records and exposes how such scam works from start to finish.)

This is by no means a fringe problem. It is proven that scammers use similar techniques to conduct scam systematically in a career fashion, and millions of dollars per year are scammed out of gullible victims such as the computer illiterate and elderly population.

Source:
https://www.youtube.com/watch?v=7rmvhwwiQAY (BBC documentary on the fake tech support scamming industry)

**Feature Proposal**

Adding a kind of anti-tamper mechanism would significantly reduce the efficacy of such abuse if not eliminate it.

For instance, the React rendering system can listen at a regular interval (or respond to DOM change) and then compute if differentiation occurs at places where it is not supposed to occur. For example, consider the account balance display on a typical banking website, it is expected that such display is implemented using HTML elements such as `<div>, <p> or <span>`. In general, we do not expect the content of such elements to change except those computed from React according to the website's frontend logic. React should be able to detect such abnormal changes and eliminate them.

If implemented, this can be added as a build option flag `ex. --anti-tamper` to enable the feature in production.

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.
