### ISSUE TITLE
Bug: Some HTML attributes do not get downcased in IE 11

### ISSUE THREAD

**Issue by joshuajaco** [facebook/react#19218]
Some HTML attributes that are camel cased in react do not get properly downcased in IE 11.

React version: 16.13.1

## Steps To Reproduce

Try and use one of the following HTML attributes on a DOM element:

- autoComplete
- autoCapitalize
- autoCorrect

and possibly others.

```jsx
import React from "react";
import ReactDOM from "react-dom";

ReactDOM.render(
  <form autoComplete="on" autoCapitalize="on" autoCorrect="on">
    <input autoComplete="on" autoCapitalize="on" autoCorrect="on" />
  </form>,
  document.getElementById("root")
);

```
## The current behavior

In IE 11 the HTML attributes stay in camel case and do not get recognized by the browser.
In chrome and other modern broswers the attributes appear downcased as expected.

## The expected behavior

The attributes get downcased in IE 11 as well.

**Comment by eps1lon** [comment]
[`autocomplete` isn't supported in IE 11](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Browser_compatibility). It wouldn't be recognized anyway. I suspect the same holds true for the other attributes you listed.

**Comment by joshuajaco** [comment]
According to [caniuse](https://caniuse.com/#search=autocomplete) it does have partial support for it and I can verify that it does indeed change IE's autofill behaviour.

```html
<form>
  <input type="text" name="username" autocomplete="off" />
  <button type="submit">submit</button>
</form>
```
In this scenario it certainly makes a difference if `autocomplete` is on or off.

**Comment by kunukn** [comment]
I tried to reproduce it. In my case the camelCase worked on IE11.

**First I enabled autocomplete in the IE 11 settings**
![image](https://user-images.githubusercontent.com/3199603/87409972-023d7500-c5c6-11ea-8e5d-d5423f1036d9.png)


**Video where it worked with camelCase.**

![ie11-autocomplete-off](https://user-images.githubusercontent.com/3199603/87410227-5183a580-c5c6-11ea-9bad-9837e0a1b619.gif)

----

The Chrome browser auto translate the autoComplete to lowercase in the DOM

----

Known workarounds if it still does not works.
use lowercase and ignore the React warning.

`<input type="text" name="username" autocomplete="off" />`

**Comment by joshuajaco** [comment]
Thanks for the thorough reply. I can confirm IE11 does understand the `autocomplete` attribute it even when camel cased.
I'm still curious though, why is it that `maxlength` gets downcased and `autocomplete` does not?

![image](https://user-images.githubusercontent.com/31038284/87538239-33887480-c69c-11ea-8e58-8771c122a0e8.png)


![image](https://user-images.githubusercontent.com/31038284/87538170-12c01f00-c69c-11ea-8d2c-dd3809a50cbb.png)

Anyway as it works regardless so I'm going to close this.
