### ISSUE TITLE
CI missing failing tests?

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#19229]
PR #19222 recently landed with no CI failures, but `ReactDOMServerSelectiveHydration` was definitely broken as a result of this PR (and was subsequently fixed in #19227). This is just a reminder for one of us to dig into why CI didn't catch this failure.

**Comment by dvargas92495** [comment]
Pretty interesting, the test failed on CircleCI but it still reported an exit code of 0:

https://app.circleci.com/pipelines/github/facebook/react/1807/workflows/a90ddfa7-9015-469e-ac2a-2a3a04d53e4a/jobs/168912

![image](https://user-images.githubusercontent.com/7143571/90554342-b4d39b00-e163-11ea-9d91-110ca447f94b.png)

Opened up a PR to see if the issue could be reproduced!

**Comment by eps1lon** [comment]
https://github.com/facebook/react/blob/23595ff593b2e53ddfec2a08e848704d15d84b51/scripts/jest/jest-cli.js#L325-L330

might be problematic if jest exits with anything but 0 or 1. Might be safer to listen to `exit` and then forward the code if not `null` (https://nodejs.org/api/child_process.html#child_process_event_exit).

**Comment by gaearon** [comment]
fwiw I think this issue might have been fixed

**Comment by eps1lon** [comment]
> fwiw I think this issue might have been fixed

https://github.com/facebook/react/pull/19265 most likely fixed it which was merged after https://app.circleci.com/pipelines/github/facebook/react/1807/workflows/a90ddfa7-9015-469e-ac2a-2a3a04d53e4a/jobs/168912 (corrupt). Before that the jest exit code was unhandled which matches the behavior in the corrupt CI job.

**Comment by dvargas92495** [comment]
Cool, so I'll close the PR and I think we could close this issue?

**Comment by bvaughn** [comment]
Yup, thanks folks
