### ISSUE TITLE
React.addons.update should return the input object when we replace a value by itself

### ISSUE THREAD

**Issue by slorber** [facebook/react#1923]
This code shows the problem

```
var root = {
    prop: "propValue",
    nested: {
        nestedProp: "nestedPropValue"
    }
}

var rootCopy = React.addons.update(root,{
    nested: { $set: root.nested }
});

var rootCopy2 = React.addons.update(root,{
    nested: { nestedProp : {$set: root.nested} }
});

console.debug("root === rootCopy",root === rootCopy);
console.debug("root.prop === rootCopy.prop",root.prop === rootCopy.prop);
console.debug("root.nested === rootCopy.nested",root.nested === rootCopy.nested);

console.debug("root === rootCopy2",root === rootCopy);
console.debug("root.prop === rootCopy2.prop",root.prop === rootCopy2.prop);
console.debug("root.nested === rootCopy2.nested",root.nested === rootCopy2.nested);
```

```
root === rootCopy false app.js:46
root.prop === rootCopy.prop true app.js:47
root.nested === rootCopy.nested true app.js:48

root === rootCopy2 false app.js:50
root.prop === rootCopy2.prop true app.js:51
root.nested === rootCopy2.nested false 
```

I woould expect all these equality to be true.

I think this is the point of immutability/structural sharing to not create useless objects when their inner properties are equally the same.

```
var object = {}
object = React.addons.update(object, { prop: { $set: propValue} });
object = React.addons.update(object, { prop: { $set: propValue} });
```
On the 2nd call, it makes sense that the object returned is the object from the arguments.

Ensuring this can help to avoid unexpected behavior in shouldComponentUpdate and prevent some useless renderings that I have encountered (when user clicks twice on the same menu element for exemple)

**Comment by davidmason** [comment]
@chenglou @syranide I am happy to make a PR this weekend on this if it is wanted. It should be possible to detect cases in `$set`, `$merge` and `$apply` that can return the same object, although the latter two may be more of a challenge. I can make separate PRs for each command if either of the latter two start to look too slow or messy.

**Comment by gaearon** [comment]
We are handing over `update()` to the community so I’m closing this.
Please see my note in https://github.com/facebook/react/pull/6353#issuecomment-204219214.
