### ISSUE TITLE
Imperative attack on react design: immerjs produceWithPatches

### ISSUE THREAD

**Issue by andrew-aladev** [facebook/react#19241]
[Immerjs](https://github.com/immerjs/immer) becomes popular tool for react these days. It includes special function named `produceWithPatches`. This function can force react component to use [imperative design](https://github.com/immerjs/immer/issues/188) only.

```js
const state = { a: 1, b: 2 }
const [nextState, patches] = produceWithPatches(state, (draft) => {
  draft.b = 3
})
```

## Steps To Reproduce

1. Use `produceWithPatches` and pass `nextState` as `prop` and `patches` as `propPatches` into component.
2. Component uses only initial `prop` value to create internal object.
3. Component uses `propPatches` to update internal object in imperative way.

## The current behavior

4. Component is not responsible to `prop` updates anymore, it care only about `propPatches`.
5. If `prop` update doesn't come from `immerjs`, than user have to provide `propPatches` by himself: find minimal changes to make `nextProp` equal to `prevProp` (DSU, tries, etc).

## The expected behavior

4. Component should be responsible for `prop` value.
5. User should be able to provide only `prop` value without `propPatches`.

Please add recommendation into documentation: `produceWithPatches` from `immerjs` is not recommended for `react`. Thank you.

**Comment by vkurchatkin** [comment]
There is nothing wrong with this approach. A lot of components only take `defaultValue` as a prop and don't react to changes to this prop after initial render.

**Comment by andrew-aladev** [comment]
@vkurchatkin, Hello, problem is about `prop` and `propPatches` properties pair. `propPatches` is a list of commands required for component to move from `prevProp` to `nextProp` (imperative design). For example:

```js
[{ op: 'replace', path: [ 'b' ], value: 3 }]
```

All application components are using declarative design (standard design for react), but one component suddenly forces imperative design. It requires user to provide additional conversion: provide `propPatches` by using `prevProp` and `nextProp`.

React itself provides conversion between declarative JSX api and imperative DOM api. Usage of `produceWithPatches` requires user to provide similar conversion for custom component.

I don't think it is possible to ban `produceWithPatches` and similar dirty hacks. Please add recommendation somewhere that usage of it is not recommended.

**Comment by vkurchatkin** [comment]
It seems that you don't like API design of a specific library, which has nothing to do with immer (because the same can be done without it) or React itself.

**Comment by andrew-aladev** [comment]
@vkurchatkin, `immerjs` is the first popular library provided `patches` approach that breaks declarative design of react application. I think that react library itself can stop spreading of this approach by developing a list of recommended and not recommended software. As I see today developers care a lot about react recommendations.

**Comment by vkurchatkin** [comment]
Can you point to any library, other than Slate, that uses this pattern?

**Comment by andrew-aladev** [comment]
For now `slate` is the only component that uses such approach (from my experience).

But I don't want to point specific on `slate`. The main bomb planted is `patches` approach that converts declarative design to imperative. This dirty hack will case large problems for every react project. Backward conversion of imperative to declarative is not easy solution. For now I've commited 400 additional lines that simulates such conversion for `slate` and this code is not very reliable.

**Comment by vkurchatkin** [comment]
So there is really nothing to worry about. If this pattern is somehow bad, it doesn't seem like a popular one that requires specific mention in React docs.

**Comment by andrew-aladev** [comment]
Sure, but please don't remove this issue completely. Maybe later react developers will find that this pattern become too popular and move it to not recommended list. Thank you.

**Comment by mweststrate** [comment]
I have yet to see the first project that passes patches as props into components. Patches are primarily used for undo/redo, distributing changes to server and logging/debugging. But I haven't seen it used as a way to update React components, which would as stated indeed mess up the clarity of the React model. So I think this issue is complaining about an approach that hasn't been adopted by anyone but the author of this issue, and isn't recommended or teached anywhere either. So this issue doesn't sound very actionable to me.

**Comment by gaearon** [comment]
I’m struggling to understand what is being suggested in this issue. There are infinitely many ways to use React, and generally there are some idiomatic patterns that you can find on the website. I don’t know enough about patches to confidently say whether this usage is idiomatic or not, but it’s also not common enough to warrant a notice on the React website either way.

**Comment by andrew-aladev** [comment]
@mweststrate, @gaearon Hello, you can't find today many applications that uses `patches` as property to feed internal instance in imperative way. But if it will become popular enough than you will know what approach to move into not recommended list.

If you think that today this pattern is not important than issue can be closed, ok.
