### ISSUE TITLE
[eslint-plugin-react-hooks]  react-hooks/exhaustive-deps throws lint error `Pass an inline function` for valid scenarios

### ISSUE THREAD

**Issue by hiteshdua1** [facebook/react#19240]
Running lint rule `react-hooks/exhaustive-deps` 
Throws an error for cases where we use lodash methods such `_throttle` or `debounce` inside useCallback . Refactoring them would make  `useCallback` becomes useless as the cache will be invalidated every time.

```  
error  React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead  react-hooks/exhaustive-deps
```

React version: 16.13.1
eslint-plugin-react-hooks version   4.0.0

## Steps To Reproduce

1. Upgrade eslint-plugin-react-hooks to version 4.0.0
2. Add lint rule to your eslinerc file 'react-hooks/exhaustive-deps': 'error',
3. Run it on the following snippet.

code example:
```
     const throttledMethod = React.useCallback(
        _.throttle(abc, 500 ),
        [abc],
    );
```

## The current behavior
Throws error because it expects an inline function
```
error  React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead  react-hooks/exhaustive-deps
```
## The expected behavior
This is a valid scenario, should not throw error as if you refactor it, `useCallback` becomes useless as the cache will be invalidated every time.

**Comment by vkurchatkin** [comment]
`useCallback` is specifically designed for inline  functions. For cases like this you need to use `useMemo`:

```js
 const throttledMethod = React.useMemo(
        () => _.throttle(abc, 500 ),
        [abc],
    );
```

**Comment by retyui** [comment]
The same problem in react native(

```js
    const onScroll = useCallback(
      Animated.event([
        {
          nativeEvent: {
            contentOffset: { y: animatedScrollY },
          },
        },
      ]),
      [animatedScrollY],
    );
```

**Comment by XiaoJiuDYS** [comment]
this would not waring. what's diffent about useMemo and useCallBack in this seceniro?
~~~tsx
 const throttledMethod = React.useCallBack(
        () => _.throttle(abc, 500 ),
        [abc],
    );
~~~

**Comment by raymondjacobson** [comment]
> This will not report an error, what is the difference about useMemo and useCallBack in this scenario？
> 
> ```tsx
>  const throttledMethod = React.useCallBack(
>         () => _.throttle(abc, 500 ),
>         [abc],
>     );
> ```

You'd lose the cancelable type

```
const throttledMethod = useCallback(
    (offset: number) => throttle(abc, 500)(offset),
    [abc]
  )
```

type of throttledMethod: (offset: number) => void


```
const throttledMethod = useMemo(
    () => throttle(abc, 500),
    [abc]
  )
```

type of throttledMethod: ((offset: number) => void) & Cancelable

**Comment by su6838354** [comment]
> This will not report an error, what is the difference about useMemo and useCallBack in this scenario？
> 
> ```tsx
>  const throttledMethod = React.useCallBack(
>         () => _.throttle(abc, 500 ),
>         [abc],
>     );
> ```

no work，differenet function on every time

**Comment by meoyawn** [comment]
zustand selectors are not always inline 

https://github.com/pmndrs/zustand/#memoizing-selectors

would be great to have a way to ignore unknown function dependencies check for `useCallback()`

**Comment by sajera** [comment]
**React Hook useEffect received a function whose dependencies are unknown. Pass an inline function instead** 
```
useEffect(appStore.initialize, [])
```
As you might guess, there is a function that should be triggered once when the component mounts. It returns undefined...
