### ISSUE TITLE
Bug: npm run build failed using with Docker

### ISSUE THREAD

**Issue by adarshsaraogi** [facebook/react#19250]
React version: 6.14.5

## Steps To Reproduce

1.docker run <image-id> npm run test

FYI please find the attached detail log while running the command.

$ docker run 4e6866278613 npm run test 

> frontend@0.1.0 test /app
> react-scripts test

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '@nodelib/fs.stat'
Require stack:
- /app/node_modules/fast-glob/out/adapters/fs-stream.js
- /app/node_modules/fast-glob/out/providers/reader-async.js
- /app/node_modules/fast-glob/out/index.js
- /app/node_modules/fast-glob/index.js
- /app/node_modules/globby/index.js
- /app/node_modules/react-dev-utils/globby.js
- /app/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js
- /app/node_modules/react-scripts/scripts/test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/app/node_modules/fast-glob/out/adapters/fs-stream.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/fast-glob/out/adapters/fs-stream.js',
    '/app/node_modules/fast-glob/out/providers/reader-async.js',
    '/app/node_modules/fast-glob/out/index.js',
    '/app/node_modules/fast-glob/index.js',
    '/app/node_modules/globby/index.js',
    '/app/node_modules/react-dev-utils/globby.js',
    '/app/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js',
    '/app/node_modules/react-scripts/scripts/test.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 test: `react-scripts test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-03T18_45_43_367Z-debug.log

**Comment by bvaughn** [comment]
This looks like a create-react-app issue *maybe* (I'd suggest searching the repo before filing it there) but it's not a React issue :smile: create-react-app has a different GitHub and is maintained by a different team :smile: 

https://github.com/facebook/create-react-app/issues
