### ISSUE TITLE
help

### ISSUE THREAD

**Issue by waluyasam** [facebook/react#19258]
ive installed the react developer tools in my chrome but i cant find it when i click to inspect elements

**Comment by bvaughn** [comment]
You might be reporting the same Chrome bug covered in #19002.

If not, there is not enough info here for anyone to help diagnose the problem.

First, make sure you're on a website using React.

The panel might be hidden by default if your browser is not wide enough, in which case you'll need to show it:
![rdtKapture 2020-07-06 at 8 52 19](https://user-images.githubusercontent.com/29597/86594992-046c5780-bf66-11ea-818d-95eca88f45e7.gif)

Hope this is enough to resolve the issue for you. If not, we'll need you to provide more info:
1. Which OS (and version) and which Chrome version
2. What error messages (if any) are in the console
3. Which website are you viewing where React doesn't work
4. Which other extensions have you installed that might be interfering

Going to close this issue for now assuming it's resolved. Let me know if that's not the case.
