### ISSUE TITLE
Repo for components

### ISSUE THREAD

**Issue by Aetet** [facebook/react#1927]
Hello. I love React and all about it. But sometimes it is so difficult to search ready-for-use components which was built by React. Or I want to share with community my new super-cool component. Is it possible to make a package manager for components? And it will be cool:
```reactpm publish MaskedInput```
or
```reactpm install KhanComponents```

jQuery has tonns of plugins but they haven't place for searching, installing and etc. So people try again reinventing wheel which already exists and do his job better.

**Comment by zpao** [comment]
FWIW, we're not going to do this and we'll leverage npm.

**Comment by kiki-le-singe** [comment]
@Aetet [react-components](http://react-components.com/) I hope this will help you
