### ISSUE TITLE
Bug: checked attribute doesn't change in DOM even though React handles it's state correctly

### ISSUE THREAD

**Issue by jdolearydl** [facebook/react#19296]
**For inputs of type 'checkbox', the checked attribute doesn't change in the actual DOM to match the react state.**

When the input is checked, the attribute is `checked=""`, as expected
![When checked, 'checked=""'](https://user-images.githubusercontent.com/43141484/87051612-cc674d80-c1cd-11ea-905d-a14da9ef9692.png)
---
When the input is unchecked, the attribute is still `checked=""`
![When unchecked, still 'checked=""'](https://user-images.githubusercontent.com/43141484/87051904-2c5df400-c1ce-11ea-9825-7f7ab13777c4.png)
This same odd behavior applies to radio buttons too.

React version: 16.13.1

## Steps To Reproduce

1.  Make a Controlled Component Checkbox
2. Check and uncheck the checkbox
3. Notice that the input element's 'checked' attribute remains unchanged regardless of the value of the actual checked prop in the component.

Link to code example:
From the [official React CodePen example](https://codepen.io/gaearon/pen/wgedvV?editors=0010) used in the React Docs
https://codepen.io/gaearon/pen/wgedvV?editors=0010

## The current behavior
'checked' attribute remains unchanged and out of sync with the react component state that should manage the attribute

## The expected behavior
The 'checked' attribute should be the same as a new input that starts unchecked and has never been checked (see image)

(Firefox on the left, chrome on the right)
![Expected attributes](https://user-images.githubusercontent.com/43141484/87053129-96c36400-c1cf-11ea-9465-3429698c6f6c.png)

**Comment by vkurchatkin** [comment]
The question is: why does that matter to you?

**Comment by jdolearydl** [comment]
It doesn't pose a problem to me directly; but I figure it might cause a real issue to something currently unforeseen - maybe assistive technologies, for example.  The point is, I'm sure it's not the intended behavior.

**Comment by rradoychev** [comment]
The HTML attribute **checked** marks certain checkbox as checked by default. However, it does not visually change when you are clicking/modifying it. This is how it works and has nothing to do with React specifically. If you want to have that change in the DOM, then I'd suggest to use .setAttribute('checked', true/false) instead.

With this method, if you have set the attribute to 'true/false' and check if the element has been checked with
`element.checked` it will return the correct results.

**Comment by jdolearydl** [comment]
Ah, thanks for the clarification @rradoychev.  I should've read the [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox).
