### ISSUE TITLE
Bug: debugger getting triggered on warnings (but setting not enabled)

### ISSUE THREAD

**Issue by mrcoles** [facebook/react#19303]
React version: 16.9.5

## Steps To Reproduce

1. Open the dev console in Firefox (78.0.1) that is running React Developer Tools (from revision a5b449295 on 7/9/2020)
2. Don’t change any settings from the defaults
3. Do something that triggers a warning, like running stripe.js in test mode on http
4. The debugger gets triggered even though “Trigger on warn” is not set and neither is debugger on exceptions in the console settings

(see screenshots at bottom)

## The current behavior

The debugger gets triggered

## The expected behavior

The debugger should not get triggered

## Workaround

Refreshing the page did nothing.

I toggled the value on, closed the dialog, opened it again and toggled it off. That fixed it for me.

## Screenshots

<img width="599" alt="Screen Shot 2020-07-09 at 7 25 25 PM" src="https://user-images.githubusercontent.com/136651/87100938-a10b4f80-c21b-11ea-9885-a4e08520bc39.png">

<img width="722" alt="Screen Shot 2020-07-09 at 7 26 09 PM" src="https://user-images.githubusercontent.com/136651/87100942-a5d00380-c21b-11ea-9de3-bc9f8a31e2d6.png">

**Comment by sangeeth96** [comment]
Happening to me as well on FF 79.0b5 (Dev Edition) with React DevTools 4.8.0-a5b449295.

I'm guessing the following is the reason? Shouldn't this be `return false` at the end for the default return value?
https://github.com/facebook/react/blob/14084be286d09df49d5410c751bc28f0180a54b2/packages/react-devtools-shared/src/utils.js#L252-L262

**Comment by kobezhu** [comment]
![image](https://user-images.githubusercontent.com/20396642/87128045-8be8fc00-c2c1-11ea-9d9e-ef162a12e367.png)

I also faced this problem.

Firefox React DevTools v4.8.0

**Comment by dvoyakiy** [comment]
![изображение](https://user-images.githubusercontent.com/40234487/87132183-2f281a00-c29e-11ea-87f9-65829fa74438.png)
![изображение](https://user-images.githubusercontent.com/40234487/87132237-3fd89000-c29e-11ea-89a5-b274c7b4efa9.png)

Same thing
FF, React DevTools 4.8.0

**Comment by gaearon** [comment]
As a temporary workaround, try setting this setting to true, closing the window, and then setting it back to false. We're tracking this in https://github.com/facebook/react/issues/19308 but I can't figure out how to update the FF addon (the store doesn't show any) so we'll need to wait for @bvaughn's help. I'm closing so we consolidate the discussion in https://github.com/facebook/react/issues/19308.
