### ISSUE TITLE
Bug: Functional component rerender when same state

### ISSUE THREAD

**Issue by heecheolman** [facebook/react#19305]
React version: 16.13.1

## Steps To Reproduce

1.
2.

[Link to code example](https://codesandbox.io/s/musing-bardeen-bx4nd?fontsize=14&hidenavigation=1&theme=dark)

## The current behavior

1. first render -> 'render' log
2. textA default value is 'A'
3. changeA Click and textA changed 'AA' -> `render` log
4. changeA Click, before textA value is 'AA' after textA value is 'AA'. -> `render`
5. And then changeA Click, nothing 'render' log
6. changeTextB Button Click and textB is always render. -> `render`
7.  changeTextA Button Click `render` log  after changeTextB clicked

![Jul-10-2020 10-31-25](https://user-images.githubusercontent.com/35059687/87106532-a6f34600-c298-11ea-8968-42f56c80d900.gif)

## The expected behavior

Expected behavior is do not render in Step4 and Step7.
Because, before textA state is 'AA' and after textA state is 'AA'. -> nothing change

**Comment by rgedwill** [comment]
By design, calling the update function of the useState hook automatically triggers a re-render. As per the useState docs:

> The setState function is used to update the state. It accepts a new state value and enqueues a re-render of the component.

Since this is by design, it should not be considered a bug. It could be memoized, but that would introduce an overhead that is probably unnecessary. Rather, it should be up to the user to only set the state if the value has changed. Since setting the state involves setting an entirely new, mutable value, it would be easier for the user to check than for the useState hook to compare the 2 values (old and new) to see if there's an update.

**Comment by MahamadEsmail** [comment]
its right not render because your value doesn't change in next time,if useState doesn't expectation new value which different before value not re-render

**Comment by vkurchatkin** [comment]
This is documented here: https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update

> Note that React may still need to render that specific component again before bailing out.

**Comment by gaearon** [comment]
Indeed, React doesn’t provide a strong guarantee here. Since your component body should be pure this should have no effect on what the code does.

**Comment by heecheolman** [comment]
example: [codesandbox](https://codesandbox.io/s/clever-edison-i3wum?file=/src/App.js:0-318)

1. First Render: **"render" print**
2. Click `Set 1` Button: **"render" print**, Because state changes `0` to `1`
3. Click `Set 1` Button: **"render" print**    

In React document 
> [If your update function returns the exact same value as the current state, the subsequent rerender will be skipped completely.](https://reactjs.org/docs/hooks-reference.html#functional-updates)

>  [If you update a State Hook to the same value as the current state, React will bail out without rendering the children or firing effects. (React uses the Object.is comparison algorithm.)](https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update)

`Object.is(1, 1)` returns `true`. But why React will render in Step3 ?


[Similar stackoverflow question link](https://stackoverflow.com/questions/58208727/why-react-needs-another-render-to-bail-out-state-updates)

**Comment by vkurchatkin** [comment]
@heecheolman once again, quote from the same page

> Note that React may still need to render that specific component again before bailing out. That shouldn’t be a concern because React won’t unnecessarily go “deeper” into the tree. 

Which means that when you call `setState` with the same value it is not guaranteed that the function is not going to be called again, but even if it is, it is not an actual rerender, since child components are not going to be rerendered.
