### ISSUE TITLE
debugger added in the javascript code causing breakpoint

### ISSUE THREAD

**Issue by tychong82** [facebook/react#19311]
Looks like debugger was left in "react-devtools-backend.js" causing breakpoints.
<img width="1314" alt="debugger-problem" src="https://user-images.githubusercontent.com/1592393/87178051-752ab100-c291-11ea-8131-479b216e5a4b.png">

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#19308) so I'm going to mark this issue as a duplicate and close it.

Please take a moment to check for duplicate issues before reporting 😄
