### ISSUE TITLE
Bug: Controlled input warning for component with onInput handler

### ISSUE THREAD

**Issue by fearsd** [facebook/react#19323]
React causes warnings in browser console about immutable input when I can change value of it.

React version: 16.3.1

## Steps To Reproduce

1. Create App component which extends React.Component.
2. In constructor create new state named input which contains '12' (or another number which is wrapped by quotes).
3. Create input elem in App with value attribute contained `this.state.input`.
4. Create new method named handleChange that get one arg - e.
5. Write code below in handleChange:
   `this.setState({input: e.target.value})`
6. Add to input in App onInput attribute that contains this code: 
    `(e) => this.handleChange(e)`
7. Open in your browser (this bug I got in Chrome) dev console
8. There you should see warning coloured red:  
    Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read- 
    only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.

Link to code example:
[https://github.com/fearsd/react_issue](https://github.com/fearsd/react_issue)
**Note: Codepen can't show this warning in console, pls see it to get know about issue more.**
[codepen](https://codepen.io/RifatFazlutdinov04/pen/QWyxJve)

## The current behavior
React causes warning dev console about immutability of input but input is exactly mutable

## The expected behavior
React shouldn't cause warnings like that if I can mute input

**Comment by AminAtaee** [comment]
you have to write onChange instead of onInput

**Comment by fearsd** [comment]
But, what problem in using onInput instead?

**Comment by rickhanlonii** [comment]
Hey @fearsd, thanks for filing.

This was fixed in https://github.com/facebook/react/pull/18189. See https://github.com/facebook/react/issues/9567 for historical context and https://github.com/facebook/react/issues/9657 for a proposal related to this.

**Comment by rickhanlonii** [comment]
For now, if you don't want to see the warning, change to use `onChange` instead. This is functionally equivalent in React right now.
