### ISSUE TITLE
Bug: Field value does not change

### ISSUE THREAD

**Issue by ximik753** [facebook/react#19326]
![bug](https://user-images.githubusercontent.com/34097384/87248097-27b06e80-c460-11ea-8fa0-0d45f3addee4.png)

React version: 16.13.1

Link to code example: https://repl.it/@Sc_Ximik/Create-React-App

## The current behavior
If I call the "update" method, through the "onClickHandler" method, my offset field does not change to 0

## The expected behavior
If I call the "update" method, through the "onClickHandler" method, my offset field changes to 0

**Comment by winterlood** [comment]
Instead of onclick={onClickHandler},
Use onclick={()=>onClickHandler()}

**Comment by ximik753** [comment]
> The solution to this problem is to define a function in onClick, not a function call.
> 
> Instead of
> 
> ```js
> onclick={onClickHandler},
> ```
> 
> Use
> 
> ```js
> onclick={()=>onClickHandler()}
> ```
> 
> or if you don't use arrow funciton
> Use
> 
> ```js
> onclick={function(){onClickHandler()}}
> ```

![1](https://user-images.githubusercontent.com/34097384/87249004-449b7080-c465-11ea-90b8-a93c5ebfe8ba.png)
your method solves the problem, I still do not get 0 in the console

**Comment by winterlood** [comment]
Does the update function change the state to 41?

**Comment by winterlood** [comment]
I think it's because setState has asynchronous characteristics. The first call will be ignored.

**Comment by winterlood** [comment]
```javascript
import React, { Component } from 'react';
class App extends Component {
  state = {
    count: 0
  }
  add() {
    this.setState({count: this.state.count+1});
  }
  handleClick() {
    this.add();
    this.add();
    this.add();
  }
  
  render() {
    return (
      <div>
        <p>{this.state.count}</p>
        <button onClick={() => this.handleClick()}>Add</button>
      </div>
    );
  }
}

export default App;
```
The intention of this code is to increase the value of this.state.count by three.
But the code above actually increases by one, not three.

This is because setState calls are made asynchronously. SetState queues changes without immediate updating of components and updates them in batches with multiple changes.

This means that if you call the setState several times, only one rendering can be done, so this.state will have only one value without changing during multiple setState operations.

**Comment by ximik753** [comment]
> I think it's because setState has asynchronous characteristics. The first call will be ignored.
> 
> 
> If you have the same key to run setState, the last key delivered takes precedence.

but in my situation I need to change the "offset" field to 0, how to do it right?

**Comment by bvaughn** [comment]
[`setState` is asynchronous.](https://github.com/facebook/react/issues/11527#issuecomment-360199710) If you want to accumulate values in a way like this, check out the updater function form of `setState` as the docs show:
https://reactjs.org/docs/react-component.html#setstate
