### ISSUE TITLE
Bug: react-devtools error when KEY and CERT are provided, SSL not usable

### ISSUE THREAD

**Issue by digicide** [facebook/react#19338]
SSL is not usable because key and cert options are added to an uninitialized options object.

Line 149 of react-devtools/app.html reads 'let options;'
Line 154 and 155 begin with 'options.cert = …'

In every case, this throws an error and enters the catch block.

React version: 16.5.2
react-devtools version: 4.8.1

## Steps To Reproduce

1. on command line, execute
KEY=react-devtools-ssl-key.pem CERT=react-devtools-ssl-cert.pem ./node_modules/react-devtools/bin.js

Regardless of whether the key and cert are valid, the error "Cannot set property 'key' of undefined" is thrown.

**Comment by digicide** [comment]
I was able to fix this by changing line 149 in my local copy to:
let options = {};

**Comment by bvaughn** [comment]
cc @ittaibaratz Interested in picking this one up?

OR @digicide, want to submit a fix? :)

**Comment by ittaibaratz** [comment]
@digicide's fix sounds good to me - I'll submit a PR shortly.

**Comment by bvaughn** [comment]
Looks like a PR already got submitted #19336

**Comment by ittaibaratz** [comment]
> cc @ittaibaratz Interested in picking this one up?
> 
> OR @digicide, want to submit a fix? :)

Actually, there's already a PR that fixes a slightly different way - https://github.com/facebook/react/pull/19336/files

**Comment by bvaughn** [comment]
Sorry for the inconvenience here. Will probably publish a release in the morning.

**Comment by bvaughn** [comment]
Version 4.8.2 has just been published to NPM with a fix for this issue.
