### ISSUE TITLE
Feature proposal(eslint-react-hooks):  Allow custom known stable values for exhaustive deps

### ISSUE THREAD

**Issue by dvkndn** [facebook/react#19330]
As far as I know the list of known stable values for exhaustive-deps to exclude when checking dependencies are defined in the code of the lint: https://github.com/facebook/react/blob/61dd00db24bec6305bd72908d3617b9f2a5183da/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L296-L307

It would be great if this can be customized/appended (like the "additionalHooks" option) because some libraries like Recoil also have known stable values (e.g. the ones returned by "useSetRecoilState")

**Comment by bvaughn** [comment]
Looks like you're asking for the same thing as #19217 so let's move this discussion onto that issue :smile:
