### ISSUE TITLE
Bug: Potential Published Debugger in react_devtools_backend.js

### ISSUE THREAD

**Issue by JoshBowdenConcepts** [facebook/react#19331]
There seems to be a published debugger on the react_devtools_backend.js file on the chrome extension. I am not sure if this is something tracked here.

![image](https://user-images.githubusercontent.com/31220082/87315656-aa820980-c4f2-11ea-90b1-0f7faa6a22b1.png)

React version:

## Steps To Reproduce

1. Open react application
2. Open sources pannel
3. Click around in react app or open components tab to inspect

Link to code example:

**Comment by eps1lon** [comment]
This is expected. See https://github.com/facebook/react/issues/19308 for more information.

**Comment by JoshBowdenConcepts** [comment]
TY

**Comment by gaearon** [comment]
To clarify, you need to update DevTools to fix this.

**Comment by jakelauer** [comment]
This still exists in Edge (Chromium) as the extension hasn't been published since 2020/07/09

**Comment by gaearon** [comment]
We're waiting for Edge to review the update.

**Comment by bvaughn** [comment]
We can't do anything about that. It's been submitted to Edge, and it's in their court :)

**Comment by jakelauer** [comment]
Gotcha, thanks for the heads up! I installed the Chrome one instead as a workaround for now.
