### ISSUE TITLE
Feature Request: Map JSX elements to props other then props.children

### ISSUE THREAD

**Issue by cnshenj** [facebook/react#19341]
Note: I considered RFC, but this is only a JSX syntax improvement that doesn't break any existing code. So created a new issue instead.

## Use Case
A component that has many customizable subparts.
```jsx
function Dialog(props) {
  return (
    <div>
      {props.header}
      <StandardDialogComponent1 />
      {props.children}
      <StandardDialogComponent2 />
      {props.footer}
    </div>
  );
}

function Page() {
  return (
    <Dialog
      header={<HeaderThatCouldBeManyLines />}
      footer={<FooterCouldBeManyLines>}>
      {props.children}
    </Dialog>
  );
}
```
Two issues:
1. `header` and `footer` could be very long and hard to read when imbedded as attributes. For example, footer may contain several buttons that are 20 lines of code. You may need to assign them to a variable to make the code less cluttered.
2. They are not in normal flow. `footer` appears before dialog body. But when rendered, `footer` appears after body.

## Proposed Solution
Use a `.` followed by prop name as JSX element name to indicate the element will be mapped to props. Easy to read/write. The order of JSX elements can map to what is visually rendered.
```jsx
function Page() {
  return (
    <Dialog>
      <.header>
        {/* Regular JSX that will be mapped to props.header */}
      </.header>
      <div>
        {/* Regular JSX here for dialog body */}
      </div>
      <.footer>
        {/* Regular JSX that will be mapped to props.footer */}
      </.footer>
    </Dialog>
  );
}
```

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.
