### ISSUE TITLE
Bug: setState callback not working

### ISSUE THREAD

**Issue by han8435762** [facebook/react#19358]
React version:
16.13.1
## Steps To Reproduce

in componentDidMount, setState callback doesn't work
but after setState it rerendered

Link to code example:
componentDidMount() {
    this.setState({isLoading: true}, () => {
      console.log('isLoadingEnd')
    })
}

console.log doesn't work

**Comment by MacMacky** [comment]
@han8435762 
Hi, It's working fine for me. __React version <code>16.13.1</code>__
```js
class Sample extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      isLoading: false
    }
  }

  componentDidMount() {
    this.setState({ isLoading: true }, () => {
      console.log('isLoadingEnd')
    })
  }
  render() {
    return (
      <div>
        Loading : {this.state.isLoading.toString()}
      </div>
    )
  }
}
```

**Comment by han8435762** [comment]
> @han8435762
> Hi, It's working fine for me. **React version `16.13.1`**
> 
> ```js
> class Sample extends React.Component {
>   constructor(props) {
>     super(props)
>     this.state = {
>       isLoading: false
>     }
>   }
> 
>   componentDidMount() {
>     this.setState({ isLoading: true }, () => {
>       console.log('isLoadingEnd')
>     })
>   }
>   render() {
>     return (
>       <div>
>         Loading : {this.state.isLoading.toString()}
>       </div>
>     )
>   }
> }
> ```

thanks.
After I upgrade my react version from 15.6.2 to 16.13.1, the callback of setState is not working. 
Maybe there are problems in some places.
