### ISSUE TITLE
Bug:  4.8.0 released a ton of bugs - Component Tree broken 

### ISSUE THREAD

**Issue by VexyCats** [facebook/react#19357]
1. The components tab will be completely broken until restarting the chrome extension and closing and reopening the tab.

On page reload from code change -> 
(broken)
![image](https://user-images.githubusercontent.com/17414704/87494885-aedd2c80-c682-11ea-9c5a-db7a2d5a271c.png)

After closing the tab and turning the extension on and off 

(normal)

![image](https://user-images.githubusercontent.com/17414704/87494896-b56ba400-c682-11ea-8ff3-c10827568d5b.png)

2. Page doesn't update. If I'm on domain.com/PROFILE and then move to domain.com/HOME - the dev tools still shows the components tab for PROFILE and the data doesn't update. 

3. Suspense components break everything below them. If suspense is included in any component it seems to have trouble loading whats below those components randomly. 

4. Occasionally getting the error about cannot find node id# in console. 

React version: 4.8.0

## Steps To Reproduce

Not sure. My codebase has pretty much remained the same and this started happening with the newest updates to the dev tool. 

Sometimes a reload works fine - sometimes when reloading the component tab doesn't work and shows the image above. 

Link to code example:

Sorry production build. No code to link. 

But I can't be the only one having this issue.

**Comment by KyriacosP** [comment]
i'm encountering number 3, too! Suspense components only show the fallback component and not there actual children both on firefox and chrome

**Comment by gaearon** [comment]
There is a known issue with Suspense that we're looking into.

For any other issues, we need a reproducing example.

Thanks.

**Comment by bvaughn** [comment]
FYI #19368 will likely fix this.

**Comment by bvaughn** [comment]
Should be fixed by #19373 

New release will go out shortly

**Comment by bvaughn** [comment]
Version 4.8.2 has just been published to NPM and submitted to Chrome/Edge/Firefox stores with a fix for this issue.

Browsers sometimes take a few hours to approve a new extension version, but once the new version goes live this should be resolved. Sorry for the inconvenience.
