### ISSUE TITLE
[DEFECT] React Dev Tools search for components

### ISSUE THREAD

**Issue by BrittaniePham** [facebook/react#19353]
The Dev tools have lost the ability to search for components recently. 

![Screen Shot 2020-07-14 at 10 31 36 AM](https://user-images.githubusercontent.com/39067245/87451531-36f8fe80-c5bd-11ea-8002-55e906804527.png)

**Comment by BrittaniePham** [comment]
closed because someone else has opened this issue prior.

**Comment by rickhanlonii** [comment]
Thanks for following up @BrittaniePham!
