### ISSUE TITLE
Bug: React Developer Tools not working in Edge due out-of-date extension

### ISSUE THREAD

**Issue by weyert** [facebook/react#19367]
React Developer Tools version 4.8.0

Recently, a fix was made to solve the `debugger`-statement issue in the DevTools by releasing `4.8.1`.

## Steps To Reproduce

1. Install React Developer Tools in Edge
2. Notice that the available version is 4.8.0 instead of 4.8.1

## The current behavior
Currently, if you install React Developer Tools in Edge it has 4.8.0 while there is a newer version available which fixes the debugger statement.

# Workaround
You can install the React Developer Tools extension through the Chrome Extension Store instead.

I think the same 4.8.1 version needs to be pushed to the Edge Extension Store so that it is in sync with the Chrome Extension Store

**Comment by weyert** [comment]
I am aware this is not really a bug but I think this is the most direct way raise this issue

**Comment by gaearon** [comment]
We're waiting for Edge to do the review of 4.8.1, which was submitted a few days ago. Unfortunately there's nothing we can do to expedite it.

**Comment by weyert** [comment]
Thank you :)
