### ISSUE TITLE
Scheduler callback is only checked for null value and therefore throws when callback is undefined.

### ISSUE THREAD

**Issue by RobiFerentz** [facebook/react#19362]
https://github.com/facebook/react/blob/30b47103d4354d9187dc0f1fb804855a5208ca9f/packages/scheduler/src/Scheduler.js#L180-L185

**Comment by JohnMHoyt24** [comment]
I noticed in line 179, of Scheduler.js, "const callback = currentTask.callback;

Should the if statement be testing if (callback !== currentTask.callback)?

const callback = currentTask.callback;
    **if (callback !== currentTask.callback)** {
      currentTask.callback = null;
      currentPriorityLevel = currentTask.priorityLevel;
      const didUserCallbackTimeout = currentTask.expirationTime <= currentTime;
      markTaskRun(currentTask, currentTime);
      const continuationCallback = callback(didUserCallbackTimeout);

**Comment by aweary** [comment]
@RobiFerentz is there a specific issue or bug you're reporting here? I believe the strict comparison is intentional as `callback` will only ever be `null` or a function.

**Comment by RobiFerentz** [comment]
Well, the I use the payment-modals package. It looks like it's using react just fine. So I went deeper and found the console error i get originates from those lines.

Whatever the reason is, it would be a better idea to check for function type, no?

**Comment by rickhanlonii** [comment]
@RobiFerentz confirmed, we'll throw if you do `scheduleCallback(ImmediatePriority, undefined)`, nice catch;

The test we'll want to add to `Scheduler-test.js` is:

```
  it('gracefully handles scheduled tasks that are null or undefined', () => {
    scheduleCallback(ImmediatePriority, null);

    expect(Scheduler).toFlushWithoutYielding();

    scheduleCallback(ImmediatePriority, undefined);

    expect(Scheduler).toFlushWithoutYielding();
  });
```

We should probably throw if you try to schedule a nullish task but that's a breaking change.

**Comment by rickhanlonii** [comment]
@RobiFerentz do you want to submit a PR to fix?

**Comment by nsantos16** [comment]
If @RobiFerentz don't have a PR to fix, I'll like to take this issue 😄

**Comment by RobiFerentz** [comment]
Sure, I'll create a PR

**Comment by rickhanlonii** [comment]
PR has been merged, thanks @RobiFerentz!
