### ISSUE TITLE
Setup CI infra to run DevTools tests against multiple React versions

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#19371]
PR #19108 caused some Suspense-related DevTools regressions (more info available on #19368) which we did not catch because of the fact that DevTools tests are only run against the version of React in master.

We should follow the precedent of the [regression fixtures tests](https://github.com/facebook/react/tree/master/fixtures/devtools/regression) and have CI run DevTools tests against multiple React versions, including v15, all v16 minors, and the current HEAD of master branch.

Setting this up will involve several things:
* Infra to checkout older React packages and run tests against them.
* Some form of gating so that we can account for expected differences in Store snapshots between React versions.
* Some form of gating so that we can avoid running tests against invalid combinations of features and versions (e.g. don't test for `Suspense` in a version of React that didn't include that component yet).

---

## Which React versions should we test?

In addition to testing against the latest React version in source, I propose that we should also test every minor version going back as far as we support (e.g. starting with v15). We could automate this process like so:
```js
const {exec} = require('child_process');
const semver = require('semver');

const versions = {};

exec('npm view react versions --json', (error, stdout, stderr) => {
  if (stdout) {
    const json = JSON.parse(stdout);
    json.forEach(versionString => {
      if (semver.valid(versionString)) {
        if (semver.gte(versionString, '15.0.0')) {
          const {major, minor, patch} = semver.parse(versionString);

          // Filter out RCs and CI-published daily releases.
          if (`${major}.${minor}.${patch}` === versionString) {
            // Store the last patch for each minor.
            // This relies on the view command returning a sorted releases list.
            const key = `${major}.${minor}`;

            versions[key] = versionString;
          }
        }
      }
    });

    // The "versions" object now contains all versions we should test again.
  }
});
```

**Comment by RitikPandey1** [comment]
I would like to take this as my first issue , please guide me from where I can start

**Comment by bvaughn** [comment]
@RitikPandey1 You are welcome to work on this issue if you would be interested!

Unfortunately, it would have to be self-guided work. I don't have any more of an outline for what needs to be done than what is written in the issue.

**Comment by RitikPandey1** [comment]
Okay, @bvaughn I will try to figure this out .

**Comment by MoSattler** [comment]
@bvaughn, not sure if this is easily done with checking out older code. 
I tried it [here](https://github.com/facebook/react/pull/19912/commits/64dd0e4fa1152a4570660f7b90edaa106bf94caf#diff-1d37e48f9ceff6d8030570cd36286a61R421-R436), and I keep running into issues where code is either coupled to newer dependencies, or the newer tests are coupled to the newer versions of react. 
See test results [here](https://app.circleci.com/pipelines/github/facebook/react/5263/workflows/b6eee195-1f5d-4c66-ba9a-d21fc33a97ee/jobs/213601/parallel-runs/0/steps/0-109).

Another issue is, that older checkouts have to restrictive devEngines requirements to be installed with modern node, see [this](https://app.circleci.com/pipelines/github/facebook/react/5263/workflows/b6eee195-1f5d-4c66-ba9a-d21fc33a97ee/jobs/213584/parallel-runs/0/steps/0-105).

**Comment by MoSattler** [comment]
Also tried it [by just installing the old dependencies via npm](https://github.com/facebook/react/pull/19912/commits/ddfe71c1cf7332c87ef88077f96e9aeeb16ee56e), with [similar results](https://app.circleci.com/pipelines/github/facebook/react/5264/workflows/210d52a0-1291-4e10-82e2-570558d7bd8b/jobs/213630). Maybe some of the tests are testing internals, and hence are coupled to internals?

**Comment by bvaughn** [comment]
The `build-for-devtools` command builds an *experimental* build (`RELEASE_CHANNEL=experimental`) of React to be bundled along with the DevTools extension. Generally this build always comes from the `master` branch, so DevTools is built with the latest version of React.

This task is about using the DevTools to connect to applications written with multiple (usually *older*) versions of React. Replacing the `build-for-devtools` command doesn't seem like the right approach here, since that would also be changing which version of React the DevTools *is actually running with*.

The precedent here would be our "legacy" tests:
https://github.com/facebook/react/tree/master/packages/react-devtools-shared/src/__tests__/legacy

These tests using NPM aliasing to run an older version of React with DevTools (which is still built with the latest *experimental* build):
https://github.com/facebook/react/blob/480626a9e920d5e04194c793a828318102ea4ff4/packages/react-devtools-shared/src/__tests__/legacy/inspectElement-test.js#L76-L84

**Comment by MoSattler** [comment]
Ok, got it, I will check it out!

**Comment by ktfth** [comment]
@MoSattler can i help you with that task?

**Comment by bvaughn** [comment]
This task is still up for grabs, if you're interested, @ktfth

**Comment by ktfth** [comment]
@bvaughn I'm totally interested on that task, can you update me with the needs to complete them?

**Comment by ktfth** [comment]
I'm gonna work to get all information needed. Thank you

**Comment by ktfth** [comment]
@bvaughn I have some question after investigate the process mentioned on #19371 (comment), the test need to be runned just on legacy code and for each version of react?

**Comment by bvaughn** [comment]
I don't know what you mean by "just legacy code"

Ideally probably at least each minor version of React

**Comment by ktfth** [comment]
The legacy test code showed by you on comment, did you remember?

**Comment by ktfth** [comment]
@bvaughn Maybe is not clear what is need to do on that task, can elaborate more about the case is need to cover with the setup?

**Comment by bvaughn** [comment]
Was referring to my comment above: https://github.com/facebook/react/issues/19371#issuecomment-700003694

**Comment by bvaughn** [comment]
I don't have a lot of time to go into much detail here, but the idea is that we currently run automated DevTools tests against two flavors of React:
1. The latest (head of master branch)
2. The latest release of React 15 (legacy tests)

Ideally we would _also_ run against every minor release of 16. There are a couple of challenges here:
1. How to install and run the tests against each release
2. How to gate which tests don't apply to all v16 releases (e.g. b'c it's a feature not added until a later version).

**Comment by ktfth** [comment]
@bvaughn Great this clarify the work, thank you

**Comment by ktfth** [comment]
I have made some tests here to create a case on CI there is the result (first change)[https://github.com/ktfth/react/blob/e5b5ffe9efe66c095f830601ab6e28529ecf8e1e/.circleci/config.yml#L310] (second change)[https://github.com/ktfth/react/blob/e5b5ffe9efe66c095f830601ab6e28529ecf8e1e/.circleci/config.yml#L523] and the (pipeline)[https://app.circleci.com/pipelines/github/ktfth/react?branch=chore%2Fsetup-ci-to-run-dev-tools-tests]

**Comment by ktfth** [comment]
I'm gonna update here to you @bvaughn can review my changes and get the job done

**Comment by bvaughn** [comment]
Okay. Keep me posted when your PR is ready for a look 👍🏼

**Comment by ktfth** [comment]
Now i need to reproduce the same tests of legacy for other versions like 16 for every minor?

**Comment by ktfth** [comment]
Sorry about a lot of questions, but you have some example to give on that part?

**Comment by bvaughn** [comment]
> Sorry about a lot of questions, but you have some example to give on that part?

No, sorry.

**Comment by ktfth** [comment]
Some updates on [config](https://github.com/ktfth/react/blob/chore/setup-ci-to-run-dev-tools-tests/.circleci/config.yml) based on @MoSattler work to test every version of react with the [result on ci](https://app.circleci.com/pipelines/github/ktfth/react?branch=chore%2Fsetup-ci-to-run-dev-tools-tests). The limits of service was reached. @bvaughn how can we continue?

**Comment by bvaughn** [comment]
Sorry @ktfth, but I don't have much bandwidth to support this task. Unfortunately it has to be self-guided 😦

**Comment by ktfth** [comment]
@bvaughn I'm gonna make a PR, thank you so much

**Comment by ktfth** [comment]
@bvaughn The PR for (#21166)[https://github.com/facebook/react/pull/21166]

**Comment by hardikshah197** [comment]
Can I take up this issue? If it isn't fixed up yet

**Comment by bvaughn** [comment]
@hardikshah197 If you'd like to take a look at #21166 and maybe lend a hand?

**Comment by hardikshah197** [comment]
Sure, I'll give it a look on and try it out. Thanks

**Comment by Albert-Jokelin** [comment]
@bvaughn is #21166 still open?

**Comment by bvaughn** [comment]
Yes.

**Comment by Albert-Jokelin** [comment]
I want to work on this.

**Comment by bvaughn** [comment]
This issue is all yours, @Albert-Jokelin! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by streetcredmusicgroup** [comment]
Ok

**Comment by Albert-Jokelin** [comment]
@bvaughn My account with CircleCI doesn't allow me to test the pipeline completely (get stuck at the paywall), is there anyway where I could use React's pipeline?

**Comment by bvaughn** [comment]
@Albert-Jokelin Creating a PR on this repo (even just a Draft PR) should enable that, no?
