### ISSUE TITLE
Bug: Programatically changing input value does not fire Onchange Event.

### ISSUE THREAD

**Issue by logeekal** [facebook/react#19389]
This issue is similar to  [ Programmatically filled input does not fire onchange event #11095 ](https://github.com/facebook/react/issues/11095#)
Whenever the value of input element is changed programatically. OnChange event is not fired. Exact reproduction can be viewer here: https://stackblitz.com/edit/buggy-input-element?file=index.js

React version: 16.13.1

## Steps To Reproduce

1. got this link  : https://stackblitz.com/edit/buggy-input-element?file=index.js
2. Check the console. It will be empty which it should have displayed because of line 34:   console.log("Change Fired");

Link to code example:
https://stackblitz.com/edit/buggy-input-element?file=index.js

## The current behavior
onChange Event should be fired if Input value is changed either by user input or by parent props.
Please not the value is changing correctly, so that is not an issue.

## The expected behavior
Whenever the value is changed, on change event should be fired irrespective of the way the value was changed.

**Comment by aweary** [comment]
Hey @logeekal, this is expected behavior. `onChange` will only fire when the value in the input has changed due to user input or some other DOM mutation on that input element. It isn't meant to fire when `value` changes.

Hope that helps!

**Comment by samhalesjr** [comment]
F****** stupid if you ask me. Who the f*** thought that was the right way to build JavaScript. If I call ".click()" I f****** expect it to do what would happen if I f****** clicked the f****** element. Holy f****** sh**.
