### ISSUE TITLE
Broken Link on reactjs.org

### ISSUE THREAD

**Issue by mojo706** [facebook/react#19380]
Not sure this is the right place to raise this issue, but on the[ acknowledgements ](https://reactjs.org/acknowledgements.html/) page of the react website there is a broken link that needs to redirect to [Oceanic Next](https://labs.voronianski.dev/oceanic-next-color-scheme/) Instead of the link that's currently there. 
👋🏾

**Comment by bvaughn** [comment]
Please file that issue in the reactjs.org repo :) https://github.com/reactjs/reactjs.org

Different people maintain that
