### ISSUE TITLE
Under what circumstances will these two values be unequal?

### ISSUE THREAD

**Issue by Magin-CC** [facebook/react#19388]
https://github.com/facebook/react/blob/970fa122d8188bafa600e9b5214833487fbf1092/packages/react-reconciler/src/ReactFiberCommitWork.new.js#L1126

**Comment by bvaughn** [comment]
Hey @Magin-CC,

In general, we set return pointers when traversing in certain cases to make sure they're updated. The return pointer might point to the previous parent, if we reused the fiber (without cloning it).

It doesn't really scale for us to answer questions about lines of source code via GitHub issues like this though so I'm going to close this issue.

**Comment by Magin-CC** [comment]
Understand! Thank you for your answers and guidance, I will submit my questions about the source code to stackoverflow in the future.
