### ISSUE TITLE
Showing an Array in string Format in UI

### ISSUE THREAD

**Issue by piyushsi** [facebook/react#19398]
In JS, Array rendered with ',' in between each element
 e.g. ['Piyush', 'Sinha'] 
// Piyush,Sinha//
but in react Array rendered without ',' in between each element
 e.g. [ 'Piyush', 'Sinha'] 
//PiyushSinha//

**Comment by bvaughn** [comment]
This is expected behavior. You're telling React to render an array of children. Those children happen to be strings, so it renders text notes.

If you want to render with comments in between, you'll need to render a string, e.g. `array.join(', ')`.
