### ISSUE TITLE
Bug: React Hook "useContext" is called in function "login" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

### ISSUE THREAD

**Issue by mfhassan22** [facebook/react#19402]
i was creating new react app and was integrating with mobx while coding the following error arise which is wrong with respect to hook rules stated below

![Screen Shot 2020-07-18 at 10 17 08 AM](https://user-images.githubusercontent.com/1241338/87842851-4be9d080-c8e2-11ea-925e-9b86ae595af6.png)

React version:"react": "^16.13.1"

where as the code is correct with respect to given rules
![Screen Shot 2020-07-18 at 10 35 08 AM](https://user-images.githubusercontent.com/1241338/87842869-6fad1680-c8e2-11ea-9c69-1db23e335f7d.png)

[hook rules](https://reactjs.org/warnings/invalid-hook-call-warning.html#breaking-the-rules-of-hooks)
## The current behavior

React Hook "useContext" is called in function "login" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

## The expected behavior
No error

**Comment by milesj** [comment]
@mfhassan22 Components must be capitalized. It should be `Login` not `login`.

**Comment by mfhassan22** [comment]
thank you and really sorry after four years i first time i realize this

**Comment by mfhassan22** [comment]
my mistake

**Comment by rickhanlonii** [comment]
This still seems like a bug. The error message you got says that "login is not a React function component", but it _is_ a function component, it just isn't valid because of the casing. Let's update this check so that it shows a similar message to the runtime error which is:

> The tag <login> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

Something like:

> React Hook "useContext" is called in function "login" which is not a valid React component because it does not start its name with an uppercase letter.

**Comment by rickhanlonii** [comment]
[Here's the tests to fix](https://github.com/facebook/react/blob/ddcc69c83b59ef0f895aa5020196e2ae9de36133/packages/eslint-plugin-react-hooks/__tests__/ESLintRulesOfHooks-test.js#L643-L671) and [here's the code to change](https://github.com/facebook/react/blob/30b47103d4354d9187dc0f1fb804855a5208ca9f/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L478-L487).

**Comment by sladyn98** [comment]
Would love to submit a pr if no one is working on it

**Comment by DanielJDupont** [comment]
I would like to work on it as my first issue, if that is possible.

**Comment by DanielJDupont** [comment]
Sorry I am kind of confused and new to this. The message: _"React Hook "useContext" is called in function "login" which is neither a React function component or a custom React Hook function"_ seems to be in an older version of React from 16.8.0 or 16.8.6 I think. 

The old error message has been edited since and it doesn't seem to exist in version 16.13.1, but the old error message is the only one that appears.

I can't get the more recent version of the error message to appear in the file, nor any of the ones I want to implement in the file: packages/eslint-plugin-react-hooks/src/RulesOfHooks.js

I don't think mfhassan22 should have even seen that specific error message he got on version 16.13.1. I am thinking that the errors messages are fixed somehow to an old version of React?

**Comment by mfhassan22** [comment]
Sorry i am not a guru of react like you guys but if you want i can forward you the **full source code** the version i took from **package.json** and run it with **npm run start**
I posted it because a i saw a similar issue which was already closed and at the end it was written if the error still exists post it

**Comment by mfhassan22** [comment]
![Screen Shot 2020-07-20 at 12 53 01 PM](https://user-images.githubusercontent.com/1241338/87900824-07983500-ca88-11ea-854a-df57476b6d9a.png)

package.json

`{
  "name": "my-mobx-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "less": "^3.12.2",
    "mobx": "^5.15.4",
    "mobx-react": "^6.2.2",
    "react": "^16.13.1",
    "react-app-rewire-less-and-css-modules": "^0.1.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "rsuite": "^4.8.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "copy-webpack-plugin": "^6.0.3",
    "css-loader": "^3.6.0",
    "less-loader": "^6.2.0",
    "style-loader": "^1.2.1"
  }
}
`

i changed back the code to double check @DanielJDupont

**Comment by abhinav-TB** [comment]
i would like to work on this would someone guide me

**Comment by DanielJDupont** [comment]
@mfhassan22 Thanks for posting that, I have recreated your error and I am getting the same thing with what you have provided.
![errorrecreate](https://user-images.githubusercontent.com/43941960/88341563-c7e17f80-cd0b-11ea-9b2b-86ec37c74429.png)

@abhinav-TB If you look at RulesOfHooks.js, you will see that the error message mfhassan22 gets (it is also the same error message I get), does not match what is in the code.

The file: RulesOfHooks.js, has the error message written so mfhassan22 and I should have seen:

```
  `React Hook "${context.getSource(hook)}" is called in ` +
                `function "${context.getSource(codePathFunctionName)}" ` +
                'that is neither a React function component nor a custom ' +
                'React Hook function.' +
                ' React component names must start with an uppercase letter.';

```
Which is:

**React Hook "useContext" is called in function is called in function "login" is called in function "login" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter.**

But the error message that is actually not in the code base from what I can see, it is from an older version of React, but we are on the current release, and the code in it doesn't seem to contain the error message that is being displayed.

Maybe I am on the wrong track and misunderstanding how the ESLint Rules work, but I think it would be good if you could find a way to get your own custom error message to appear on your own build of React. I am trying to figure it out in my free time but I wouldn't expect myself to figure it out at this rate.

**Comment by gaearon** [comment]
The version of React is entirely unrelated here.

What's related is the version of the ESLint plugin. This message was added in https://github.com/facebook/react/pull/18881. But that change has not yet made it to Create React App, which is using an older version of the plugin. When Create React App releases the next update, that fix will be included.

**Comment by rickhanlonii** [comment]
Sorry for the confusion @DanielJDupont, I didn't realize that the message had already been updated 😬

Thanks for all you work investigating anyway!
