### ISSUE TITLE
Bug: firefox 'select all' menu item not firing select events on textareas

### ISSUE THREAD

**Issue by jedierikb** [facebook/react#19404]
React version: 16.3.1
Firefox version: 78.0.2 (OSX 10.15.5)

## Steps To Reproduce

Make a `textarea` (with some text) and listen for select events ( `onSelect={ ...}` ).
Use the firefox browser's 'select all' menu item (not the keyboard shortcut) to expand your selection area.

Link to code example:
https://codepen.io/jedierikb/pen/pogQVLo

## The current behavior
Firefox browser's 'select all' menu item (not the keyboard shortcut) does not fire a `select` event.

## The expected behavior
Firefox browser's 'select all' menu item should fire a `select` event on textareas.
Works in Chrome and Safari.
Also works in Firefox with an ordinary event listener.  See https://developer.mozilla.org/en-US/docs/Web/API/Element/select_event

**Comment by marcosvega91** [comment]
Hi @jedierikb the issue here seams to be that firefox not support `selectionchange` event on `textarea`.
When you select with shortcut the event is fired on `keyup/keydown` for the reason above.
In this case the only event fired is `select`, so I think that an ad hoc listener should be added.

**Comment by jedierikb** [comment]
Thx @marcosvega91 

I did not expect React's `onSelect` listener added to a `textarea` would incorporate `document.selectionchange` or `key` events into generating synthetic events.  Rather, I expected it would relay values from a native `select` event.  There is clearly a lot going on under the hood!

Can someone point me to a reference sheet for the recipe used by React's `onSelect` synthetic event and any recipes used by other hybrid synthetic events?  That would be a useful resource.

**Comment by rradoychev** [comment]
Hi @jedierikb 

You can check here: [SelectEventPlugin](https://github.com/facebook/react/blob/c954efa70f44a44be9c33c60c57f87bea6f40a10/packages/react-dom/src/events/SelectEventPlugin.js)
