### ISSUE TITLE
Bug: Presence of useEffect hook (even with empty function) significantly slows render time compared to useCallback hook

### ISSUE THREAD

**Issue by gregjacobs** [facebook/react#19405]
Simply adding `useEffect()` (or `useLayoutEffect()`) to a function component significantly slows render time. Noticeable when many components are on the page.

Interestingly, `useCallback()` doesn't seem to suffer from this issue, and seems to only introduce minimal delay in the below test app.

**React version**: 16.13.1
**Link to code example**: https://codesandbox.io/s/cranky-mahavira-in9ij?file=/src/App.js

Try clicking the 'Render Components' button for each and the render time will be displayed:
![image](https://user-images.githubusercontent.com/302273/87879590-dea96e80-c9b9-11ea-9afa-6a607841b0fe.png)

```js
const NoHooksComponent = () => {
  return <div className="block">A</div>;
};

const UseCallbackComponent = () => {
  useCallback(() => {}, []);
  return <div className="block">B</div>;
};

const UseEffectComponent = () => {
  useEffect(() => {}, []);
  return <div className="block">C</div>;
};
```

**Comment by vkurchatkin** [comment]
That is sort of expected. Nowhere is says that `useEffect` is free in terms of performance

**Comment by gregjacobs** [comment]
@vkramskikh How is that expected exactly? Especially when `useCallback()` doesn't produce the same issue?

I expect there to be a slight performance hit (after all, React is doing more work), but I don't expect a 2x slowdown in rendering performance.

**Comment by gregjacobs** [comment]
Updated the example in the description to show the difference in performance between `useCallback()` and `useEffect()`

**Comment by vkurchatkin** [comment]
>  Especially when useCallback() doesn't produce the same issue?

This is irrelevant, these two hooks do completely different things

> I expect there to be a slight performance hit (after all, React is doing more work), but I don't expect a ~2x slowdown in rendering performance.

What is your reasoning, what makes you think it can/should be faster?

**Comment by eps1lon** [comment]
In a production deploy NoHooks takes 1687ms while UseEffectComponents takes 2252ms (https://csb-80x4q-eaw81zidw.vercel.app/). So we have a 40% render-time penalty where it matters. I don't think this is noticeable in real-world applications. For example how much does the useEffect call take compared to other code you usually see in components (createElement calls, loops etc).

**Comment by gregjacobs** [comment]
@eps1lon You're right, render performance is much better in production mode. I'm actually seeing very little difference now between NoHooksComponent and UseEffectsComponent. I guess there's just a lot more error checking or something going on when debug mode is active - definitely didn't expect that. Thanks for pointing that out! Will close

**Comment by gregjacobs** [comment]
And @vkurchatkin, I'm sorry, but your comments were not helpful. Saying something like "Nowhere is says that useEffect is free in terms of performance" isn't a useful comment. The more relevant question is: why is it slow. The `useEffect()` and `useLayoutEffect()` hooks are simply to call a function after the rendering of the component is complete. That alone (calling an empty function) shouldn't account for such a wild difference in rendering times. 

Perhaps there is a lookup algorithm in the hook that could be optimized. Perhaps there is an accidental inefficiency somewhere in the code. It _seems_ there may be a lot of extra debugging code to help developers in debug mode. But if you're unsure as to why the performance difference exists, then I'm sorry but adding comments based on conjecture is not useful and generates unnecessary noise.

**Comment by vkurchatkin** [comment]
> Saying something like "That is sort of expected. Nowhere is says that useEffect is free in terms of performance" isn't a useful comment

This wasn't intended to answer the question "why such a difference exists", I was trying to point that this is not a valid _bug report_. Maybe `useEffect` could be faster, but the only way to make such a claim is to point out exactly how it could be made faster.
