### ISSUE TITLE
Bug: React retains the components references to old renders causing browser memory to increase with more references

### ISSUE THREAD

**Issue by 97joseph** [facebook/react#19415]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by bvaughn** [comment]
@97joseph An issue like this requires a lot more information to be helpful and actionable.

In many cases in the past where we have gotten reports of over-retention like this, there have been external causes (e.g. refs, browser DevTools extension, etc.) If you have a repro, or browser performance profile, etc. please share it with us.

**Comment by bvaughn** [comment]
I'm going to close this issue since there's incomplete information for us to do anything with it. We can reopen it if additional information is provided.

**Comment by 97joseph** [comment]
The problem appears to have been caused by the browser type i was using....i resolved the issue by using a different browser
