### ISSUE TITLE
Bug: Dev tools tabs break in chrome - need an alternative interface.

### ISSUE THREAD

**Issue by mcchong** [facebook/react#19417]
https://github.com/facebook/react/issues/19002 makes the tools nearly unusable.  Redux devtools on the other hand provide a pop-out interface when the devtools tabs go down, and while less nice, the tool is still usable.  Would be great if these tools had a similar workaround if that's not too much to ask.  Thanks!

React version: 16.13.1
DevTools version: 4.7.0 (5/18/2020)

## Steps To Reproduce
(Same as linked bug)
1. Create a new profile in Google Chrome
2. Install the React Developer Tools
3. Go to https://reactjs.org
4. Open the browser Dev Tools

Link to code example:

## The current behavior
Chromium bugs break the devtools.

## The expected behavior
devtools are still usable through a different interface.

**Comment by gaearon** [comment]
Thanks for the suggestion. While it's nice that Redux DevTools adds a different popup, this sounds like a rather invasive change, and by the time it would take us to ship it, Chrome would ship the update that fixes the bug. So I think it's not something we're going to do. That said, if somebody sends a PR, we can consider it (but no promises to merge).
