### ISSUE TITLE
Bug: The trigger timing of  "child useEffect" is different in chrome and safari.

### ISSUE THREAD

**Issue by xiaoshuangLi** [facebook/react#19438]
In chrome and safari, the ```console.log``` was triggered in different order. [Example](https://codesandbox.io/s/amazing-payne-4lmxo) will show different result if opened in different browsers.

Seem like ```(new MessageChannel()).port1.onmessage``` and ```setTimeout``` run in different order with different browsers.

React version: 16.13.1

## Steps To Reproduce

1. Run following code in chrome and safari.
2. Check console log

```jsx
import React, { useState, useEffect } from "react";

const Test = props => {
  useEffect(() => {
    console.log("useEffect in child");
  }, []);

  return "Test useEffect";
};

const App = () => {
  setTimeout(() => {
    console.log("timeout in render");
  }, 0);

  return <Test />;
};

export default App
```

Link to code example:

[Example](https://codesandbox.io/s/amazing-payne-4lmxo)

## The current behavior

The message is not the same order;

```jsx
/**
 * chrome result
 *
 * useEffect in child
 * timeout in render
 */

/**
 * safari result
 *
 * timeout in render
 * useEffect in child
 */
```

## The expected behavior

The message should be same. And timeout should run after child useEffect.

```jsx
/**
 * chrome result
 *
 * useEffect in child
 * timeout in render
 */

/**
 * safari result
 *
 * useEffect in child
 * timeout in render
 */
```

**Comment by dmytro-lymarenko** [comment]
You do the side effect in the render method:
```typescript
const App = () => {
  setTimeout(() => {
    console.log("timeout in render");
  }, 0);

  return <Test />;
};
```
which is not allowed. React doesn't guarantee this kind of orders. you should put `setTimeout` inside an useEffect.

**Comment by xiaoshuangLi** [comment]
> You do the side effect in the render method:
> 
> ```ts
> const App = () => {
>   setTimeout(() => {
>     console.log("timeout in render");
>   }, 0);
> 
>   return <Test />;
> };
> ```
> 
> which is not allowed. React doesn't guarantee this kind of orders. you should put `setTimeout` inside an useEffect.

Yes, i agree this is not allowed. But different browsers should have same result.I think react should achieve lifecycle with more stable browser interfaces.

**Comment by vkurchatkin** [comment]
Many reasons why this is not a bug:

 - you are not allowed to make side effects in render. If you do that, the outcome is essentially "undefined behaviour", that is, nothing is guaranteed

- React provides no guarantees about timing of `useEffect` with respect to render anyway.

So while this is an inconsistency and it could be fixed, there is not good reason to do so.

**Comment by gaearon** [comment]
It is not supported to call `setTimeout` during rendering. React provides absolutely no guarantees about the order or the number of component render calls — so you can't rely on subtle timing aspects of them.

If I wrap it in `useEffect` I don't observe the difference.
