### ISSUE TITLE
Electron app fails to load React DevTools -- exit code 2

### ISSUE THREAD

**Issue by jakerobb** [facebook/react#19430]
I work on an Electron+React+Redux app. It has the following in `main.js`:

    const installDevTools = () => {
      const {
        default: installExtension,
        REACT_DEVELOPER_TOOLS,
        REDUX_DEVTOOLS
      } = require("electron-devtools-installer");
      installExtension(REACT_DEVELOPER_TOOLS)
        .then(name => console.log(`Added Extension:  ${name}`))
        .catch(err => console.log("An error occurred loading React DevTools: ", err));
      installExtension(REDUX_DEVTOOLS)
        .then(name => console.log(`Added Extension:  ${name}`))
        .catch(err => console.log("An error occurred loading Redux DevTools: ", err));
    };

We invoke this function on startup when running in dev mode. Works fine on my Mac, but my coworker on Windows 10 gets this error, and then cannot use the React dev tools. We are using Electron 8.1.1, which embeds Chrome 80.

    Added Extension:  Redux DevTools
    An error occurred loading React DevTools:  Error: Exited with code 2
        at ChildProcess.<anonymous> (c:\_Projects\myproject\node_modules\cross-unzip\index.js:38:21)
        at ChildProcess.emit (events.js:210:5)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

I did some searching in the source code and can't find what would cause exit code 2.

I know this isn't a lot to go on. Please let me know if there is more information that would be helpful.

**Comment by bvaughn** [comment]
Hey @jakerobb :wave} `electron-devtools-installer` is not a package that we own or maintain, so we can't really help. You should try reporting this error with the maintainers of that package: https://github.com/MarshallOfSound/electron-devtools-installer

**Comment by alex-buys-github** [comment]
This seems to work: https://github.com/MarshallOfSound/electron-devtools-installer/issues/157#issuecomment-704792363
