### ISSUE TITLE
React is not offering suggestions/guideline for managing environment specific configuration

### ISSUE THREAD

**Issue by nachiappannk** [facebook/react#19449]
When building application we often have to deploy in multiple environments such as dev, staging and production. Some times instead of one production we might prod-cust1, prod-cust2, etc...

React is NOT offering any suggestions or guidelines how to manage environment specific configuration file.
Angular is offering this suggestion https://angular.io/guide/build
The suggestion offered by Angular is less than optimal.
Many developers are adopting an approach similar to Angular approach for configurations

The problems in Angular approach
 * The code and the configuration is not separated (this is against the guideline of 12 factor app) 
 * It also doesn't help Build Once Deploy Anywhere

It would be optimal if React suggests a way to separate configuration and code
There are many ways in which the config and code could be separated. Two ways are interesting

1. Have the configuration in the public folder and add it as script in index.html
   Have a file named Config.js that exports config by assessing window.config

2. Have a mechanism to get the config from the backend on start up

React could choose option 1 as the default mechanism and the user could change it option 2

Suggestion change:
1. Modify create-react-app so that configuration is separated from code as suggested in option 1
2. Have a parameter in create-react-app so that the use could choose option 2

Also to consider: create-react-app based on a parameter provides a Dockerfile and .docekerignore

**Comment by aweary** [comment]
Hey @nachiappannk! As a library React does not have any opinions on how to approach environmental variables or deployment (outside of [using production builds](https://reactjs.org/docs/optimizing-performance.html). If you have suggestions or ideas on how Create React App should handle this, please direct those to the [`create-react-app` repo](https://github.com/facebook/create-react-app) which is maintained as a separate project.

Thanks!
