### ISSUE TITLE
useLocalState

### ISSUE THREAD

**Issue by inblack67** [facebook/react#19460]
#### Idea worthy enough to become a PR?

**Comment by bvaughn** [comment]
This is a useful hook, but it can already be built by combining `useState` and `useLayoutEffect `, so we wouldn't likely consider adding it as a primitive.

FWIW DevTools uses such a hook internally:
https://github.com/facebook/react/blob/d29bf59a6e5bc79aa623538288f49cedee7cbb96/packages/react-devtools-shared/src/devtools/views/hooks.js#L143-L198
