### ISSUE TITLE
Bug: eslint-plugin-react-hooks auto-fix changes functionality of code

### ISSUE THREAD

**Issue by daleyjem** [facebook/react#19467]
`eslint-plugin-react-hooks` auto-fixes code to the point that it changes functionality, rather than simply changing cosmetics of the code.

`react` version: 16.13.1
`eslint-plugin-react-hooks` version: 2.3.0

## Steps To Reproduce

Consider the following code:

```javascript
useEffect(() => {
  axios
    .get(`/some-path/${location.pathname.split('/')[2]}`)
    .then(res => {
      props.someMethod({
        myData: res.data,
        myId: location.pathname.split('/')[4],
        slug: location.pathname.split('/')[3],
        loading: false,
      })
    })
    .catch(err => {
      props.someMethod({
        myData: [location.pathname.split('/')[2]],
        myId: location.pathname.split('/')[4],
        slug: location.pathname.split('/')[3],
        loading: false,
      })
    })
}, [])
...
```

`eslint-plugin-react-hooks` will insert into the last line:

```javascript
}, [location.pathname, props])
```

This has caused an endless loop of `axios` calls and crashes the browser tab.

## The current behavior

Inserts potentially breaking code.

## The expected behavior

Only change cosmetics of the code, and not the functionality of it.

**Comment by gaearon** [comment]
There is no autofix since 2.4.0 for this very reason. It has been replaced by Suggestions API which is used by IDE but never applied automatically.

**Comment by daleyjem** [comment]
@gaearon Well now don't I feel like a horse's patoot. Thank you, sir!
