### ISSUE TITLE
Bug: useContext out of the box (from docs example) is not working as expected

### ISSUE THREAD

**Issue by cemceliks** [facebook/react#19475]
Hi, I have actually finished this site with no other commits yet on GitHub. During refactoring wanted to use Context for various aspects but could not make it work on the project during refactoring. So I set up a totally new project and only used the example from the reference from React docs website as stated below on Step 1. Website is built with hooks and function components only. 

package.json info
    "@u-wave/react-vimeo": "^0.9.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"

Totally new project with no extra dependencies and no other installation than Vimeo player at the moment, which is not yet used anywhere. No other files in the project other than the 3 components mentioned to create the useContext example.

React version: Versions above

## Steps To Reproduce

1. From reference on documentation page https://reactjs.org/docs/hooks-reference.html for useContext
2. Have 3 components as per the example there namely App.js, Toolbar.js and ThemedButton.js
3. I have my imports where needed and useContext imports where needed. No issues with compilation and all code seem to be clean after nom start. 

Link to code example: https://github.com/cemceliks/watson
Committed as "useContext example". The only commit there so far. 

## The current behavior
Errors on Google Chrome render on npm start and errors on google dev tools Console.
Error: Cannot read property of "background" of undefined in ThemedButton.js

## The expected behavior
useContext to be able to access the values set by the Context object with its provider.

**Comment by aweary** [comment]
@cemceliks you're [importing `ThemeContext` from your `App.js` file](https://github.com/cemceliks/watson/blob/master/src/ThemedButton.js#L2), which is [exporting a component](https://github.com/cemceliks/watson/blob/master/src/App.js#L29) not a context. You need to pass the [context you created here](https://github.com/cemceliks/watson/blob/master/src/App.js#L18) to `useContext`. Maybe move that into a `ThemeContext.js` file and have other modules import from there?

For future reference we try to use this issue tracker for bug reports and feature requests only. If you have more trouble I  recommend checking out the list of great support resources listed on the doc page, [Where to Get Support](https://reactjs.org/community/support.html).
