### ISSUE TITLE
[eslint-plugin-react-hooks] Bug: rules-of-hooks false positive conditional call after foreach

### ISSUE THREAD

**Issue by likuilin** [facebook/react#19476]
Within a function component, a `React.useState` after a foreach with a conditional inside triggers the rule, even if the foreach doesn't make the hook call conditional. 

React version: 16.13.1

## Steps To Reproduce

1. Here is a minimal reproduction: 

```javascript
export default function App() {
  for (let a of []) {
    if (true) {
    } else {
    }
  }
  React.useState();
  return null;
}
```

Sandbox link: https://codesandbox.io/s/elated-sunset-wguwp?file=/src/App.js

Removing the `else` block or the `for ... of` both cause the error to not present. 

## The current behavior

ESLint throws a build-time error: `React Hook "React.useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return? (react-hooks/rules-of-hooks)`

## The expected behavior

There is no error because `React.useState` is not called conditionally.

**Comment by revanthgss** [comment]
There is no error when I ran eslint in my local vscode editor. Perhaps, it's a bug in codesandbox.

**Comment by likuilin** [comment]
It's not just a bug in codesandbox, I ran into this bug on an actual React project. The codesandbox link is just a minimal reproduction.

I just checked and I can also reproduce this on a fresh create-react-app app by just doing `npx create-react-app` and then replacing src/App.js with the App module above. Here's that pushed to a repo if you would like to test this: https://github.com/likuilin/react-bug-repro

**Comment by charles-hill-exelon** [comment]
A likely related problem is OR assignment.  Having a line like this before a hook, triggers this rule, even though it shouldn't.

`const something = somethingOrUndefined || '';`

**Comment by jake-nz** [comment]
I can reproduce this running eslint in VSCode too

**Comment by likuilin** [comment]
Seems to be fixed, _mysteriously_. It's no longer reproducible now, plus also even the same codesandbox link above fails to reproduce it today. I'm pretty sure codesnackbox pins the version of eslint, so maybe this was a browser bug? No idea. Closing issue.

**Comment by gavinwahl** [comment]
This is still happening, minimal repro here: https://github.com/camhux/eslint-react-hook-false-positive

**Comment by likuilin** [comment]
Thank you for the work! I will reopen this issue and see if I can reproduce your case this afternoon.
