### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by rtheil** [facebook/react#19478]
React version:
+ react@16.13.1
+ react-scripts@3.4.1
+ react-dom@16.13.1
+ cra-template@1.0.3

## Steps To Reproduce
1. Run create-react-app for a brand new project.
2. App.js
```
import React from "react";
import "./App.css";
import TheComponent from "./component";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <TheComponent />
      </header>
    </div>
  );
}

export default App;
```
3. make new file called component.jsx
```
import React, { Component } from "react";

class TheComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  ErrorMessage = ({ title, error }) => {
    return (
      <div>
        <strong>{title}</strong>
        <br />
        {error}
      </div>
    );
  };

  ForgotForm = () => {
    return <this.ErrorMessage title="TITLE" error="error message" />;
  };
  render() {
    return (
      <React.Fragment>
        <this.ForgotForm />
      </React.Fragment>
    );
  }
}

export default TheComponent;
```

Running in test environment (npm start) works perfectly. Executing "npm run build" and then "serve -s build" (or putting it anywhere else) causes the following error: 
![image](https://user-images.githubusercontent.com/12970192/88739358-998ee600-d0f7-11ea-9a77-b5935a02dc85.png)

Link to error page: https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

## The current behavior
Error as above ONLY in production build

## The expected behavior
No error, as it runs within test environment

**Comment by gaearon** [comment]
Thanks for the report, but you'll probably want to report this to Create React App instead since it appears to be a compilation issue. I'll note that the pattern you're using (using class methods as components) is very unidiomatic and even if this problem gets fixed, you'll likely run into other problems. I strongly discourage writing code this way.
