### ISSUE TITLE
Bug: the order of effect and cleanup in Parent and Child component is weird

### ISSUE THREAD

**Issue by xialvjun** [facebook/react#19482]
React version: v16.12.0

## Steps To Reproduce

1. just as the code example shows: just click the button 6 times respectively and see the console

Link to code example:
https://stackblitz.com/edit/react-effect-order-matters?file=index.js

## The current behavior
useEffect logs: `cpcc*1 + ppcc*n + pppc*1`
useLayoutEffect logs: `cpcp*(1+n) + cppc*1`

## The expected behavior
both useEffect and useLayoutEffect should log: `cppc*(1+n+1)`

## Why I need a stable effect and cleanup order
There is a vanilla js package `mapbox-gl` whose use case is:
```js
import mapboxgl from 'mapbox-gl';
var container = document.querySelector('#map');
var map = new mapboxgl.Map({ container });

map.on('load', function () {
  // every thing should be done after load
  map.addSource('route_source', route_source_data);
  map.addLayer({
    source: 'route_source',  // the layer relies on the source
    id: 'route_layer',
    ...other_layer_config,
  });
  // ...;
  do_many_things();
  // ...;
  // you must remove the layer before removing the source
  map.removeLayer('route_layer');
  map.removeSource('route_source');
});
```

Then I want to make a react version:
```jsx
var vdom = (
  <Map opts={x}>
    <Source opts={xx}>
      <Layer opts={xxx}></Layer>
    </Source>
  </Map>
)
```
 
But since the order of react effect and cleanup in parent and child component is not stable (well, it' stable but it's weird), things became complex.

I think the effect and cleanup order matters because there are dependency relations between parent and child components.

And react should handle it.

There are some related(maybe) issues:
https://github.com/facebook/react/issues/16728
https://github.com/facebook/react/issues/17080

And the react lifecycle order is works right: https://stackblitz.com/edit/react-lifecycle-effect-order-right?file=index.js

**Comment by xialvjun** [comment]
@gaearon just like [this](https://github.com/facebook/react/issues/16728#issuecomment-664913171) comment, I filed a new issue. And in this issue, I gave a real use case, hoping this will draw you guys' attention.

**Comment by xialvjun** [comment]
Although react lifecycle order works right, it lacks `componentDidUnmounted`.

Related issue: https://github.com/facebook/react/issues/6424 . This issue is closed because

> Closing as React's design is moving away from class-based lifecycle methods

But HookApi doesn't solve the problem of `parent component can not clean up resource shared by it's children`.

**Comment by xialvjun** [comment]
To solve the problem of **parent component can not clean up resource shared by its children**, there is a hack way: https://github.com/facebook/react/issues/6424#issuecomment-351760732

And by imitating the above method I wrote a hook which can express 6 lifecycles: **`willMount, didMount, willUpdate, didUpdate, willUnmount, didUnmount`**. And the parent children lifecycles running order is right: `Parent willMount, Child willMount, Child didMount, Parent didMount, Parent willUpdate, Child willUpdate, Child didUpdate, Parent didUpdate, Parent willUnmount, Child willUnmount, Child didUnmount, Parent didUnmount`, it's `pccp*(1+n+1)` which is `cppc*(1+n+1)`(this issue's useEffect expected behavior) transform to `pc + cppc*(1+n+1) + cp`
```tsx
type life = "mount" | "update" | "unmount";
export const useWillDid = <T extends (life: life) => void | ((life: life) => any), D extends any[]>(
  fn: T,
  deps?: D,
) => {
  const inv = useRef<void | ((life: life) => any)>();
  const mounted = useRef(false);
  const is_last = useRef(false);
  is_last.current = false;
  inv.current = useMemo(() => {
    return fn(mounted.current ? "update" : "mount");
  }, deps);
  useEffect(() => {
    if (inv.current) {
      inv.current(mounted.current ? "update" : "mount");
    }
    mounted.current = true;
    is_last.current = true;
    return () => {
      if (is_last.current) {
        inv.current = fn("unmount");
      }
    };
  }, [inv.current]);
  const style = useMemo(() => ({ display: "none" }), []);
  const ref = useMemo(
    () => (ele: any) => {
      if (!ele && inv.current) {
        inv.current("unmount");
      }
    },
    [],
  );
  return <span ref={ref} style={style}></span>;
};
```

Even though I have wrote this hook which can solve my problem, I still thought It should be done by `react`. Hope you consider it more.

**Comment by mbest** [comment]
What about using `setTimeout` in the parent's cleanup function?

**Comment by xialvjun** [comment]
If useing `setTimeout`, what about parent's parent?

**Comment by derzwen** [comment]
Any news on this? I'm also using Mapbox and wanted to do the same thing and hit the same problem.

**Comment by tengl** [comment]
We also have this problem. I've made a [simple React app with maplibre](https://codesandbox.io/p/github/tengl/maplibre-remove-layer/main?selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A34%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A34%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cleh5gog2000mg6hvb7d8e0og%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252FMaplibre.jsx%2522%252C%2522%252FREADME.md%2522%252C%2522%252Fsrc%252FMaplibreLayer.jsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cleh5gpjm000x2v6i6yx11k8k%2522%253A%257B%2522key%2522%253A%2522cleh5gpjm000x2v6i6yx11k8k%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cleh8l95e012s2v6j2vebbyhf%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cleh8l6s700yx2v6j1wryjp77%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cleh5gpjm000x2v6i6yx11k8k%2522%252C%2522spacesOrder%2522%253A%255B%2522cleh5gpjm000x2v6i6yx11k8k%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D&embed=1) to demonstrate the issue, and two possible work arounds. If someone has a better solution I'd be happy to hear it.

**Comment by satansju** [comment]
bump

**Comment by proyectoramirez** [comment]
This issue is still relevant - I'm trying to call some effects with the following order:
- On setup: parent -> child
- On cleanup: child -> parent

Effects currently do the opposite, and there is no good alternative

**Comment by VimHax** [comment]
The cleanup ordering matters for the app I'm using as well. I have an observable which the parent creates and passes down to the children which they can start observing with. It is possible that either the parent component is being unmounted or the observable throws an error, in either case the observable needs to be destroyed... But this can only be done after the children have unmounted because they are still observing. (Destroying an observable that the children are still observing is erroneous as stale data will be displayed.)
