### ISSUE TITLE
The props reference remains in 'FiberNode' after the component is unloaded

### ISSUE THREAD

**Issue by rocky-one** [facebook/react#19481]
React version: 16.13.1

**Description**
I tried to uninstall a component and found that the props reference for that component is still in 'FiberNode' after uninstalling. Why is this happening and who can help with this?

**Comment by aweary** [comment]
Hey @rocky-one, some data might be retained for a short period. Eventually React will delete those references. There are [some known issues with memory leaks](https://github.com/facebook/react/issues/16087) that might affect what you're seeing as well.

If you think you're seeing a new memory issue please follow up with a code sample that reproduces the problem and we can investigate. Thanks!
