### ISSUE TITLE
Each Class is executing two times in react version 16.13.1 

### ISSUE THREAD

**Issue by radhey7705** [facebook/react#19484]
React version: 16.13.1
React Script Version:  3.4.1

## Steps To Reproduce

1. Just create a new project using command npx create-react-app <project name>
2. Convert functional component to Class component in App.js
3. Add a console log before "return" statement.
4. then run command "npm start"
5. In the console in browser, you will see console log was printed two times.

Link to code example:  https://github.com/radhey7705/React-Project.git

## The current behavior
after run npm start, Class component is working two times

## The expected behavior
after run npm start, Class component should only work single time.

**Comment by Reflex-Gravity** [comment]
In Strict Mode, react intentionally double-invokes `constructor`, `render`, and `shouldComponentUpdate`.
It helps to detect unexpected side effects.

More details in the below link:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by bvaughn** [comment]
This is intentional, as mentioned above :)
