### ISSUE TITLE
Memory leak after component unload

### ISSUE THREAD

**Issue by rocky-one** [facebook/react#19491]
React version: 16.13.1

Description
Data passed by props after uninstalling a component is still referenced and not GC.

```
import React from 'react';
class App extends React.Component {
  state = {
    show: false,
    userObj: {
      arr: []
    }
  }
  onClick = () => {
    let show = !this.state.show
    let arr = []
    if (show) {
      for (let i = 0; i < 100000; i++) {
        arr.push({
          name: `rocky_${i}`
        })
      }
    }
    this.setState({
      show,
      userObj: {
        arr
      }
    })
  }
  render() {
    return (
      <div className="App">
        <div>
          <button onClick={this.onClick} style={{margin: '10px'}}>
            {this.state.show ? 'uninstall components' : 'install components'}
          </button>
        </div>
        {this.state.show && <Test userObj={this.state.userObj}></Test>}
      </div>
    )
  }
}

class Test extends React.Component {
  render() {
    return (
      <div style={{width: '200px', height: '100px', border: '1px solid #ccc', margin: '10px'}}>
        I am a test component
      </div>
    )
  }
}

export default App;
```
**1. component not installed**
![image](https://user-images.githubusercontent.com/26345259/88901082-e81cbb80-d282-11ea-8719-50334a4c7e57.png)

**2. after installation of components**
![image](https://user-images.githubusercontent.com/26345259/88901263-2c0fc080-d283-11ea-84d0-9daacc3426b2.png)

**3.component unloaded**
![image](https://user-images.githubusercontent.com/26345259/88901447-5feae600-d283-11ea-84e7-5eb9fb362311.png)

[The sample code is here](https://codesandbox.io/s/tender-dewdney-l5zcs?file=/src/App.js)

**I understand that component unloaded memory should return to the original 4.6MB, but component unloaded memory is still 8.8MB. Is this a memory leak? I am a novice still ask grant instruction, thank!**

**Comment by MacThanos** [comment]
Usually if there's a memory leak then it will show up as an error in the console tab. 

Your onClick function keeps pushing data into an array so that's why the size increase. 

Try using functions if you are starting out with React. It will make life much easier.  Read up on the docs.

**Comment by rocky-one** [comment]
> 通常，如果存在内存泄漏，那么它将在控制台选项卡中显示为错误。
> 
> 您的onClick函数不断将数据推送到数组中，因此这就是大小增加的原因。
> 
> 如果您是从React开始的，请尝试使用函数。这将使生活更加轻松。阅读文档。

Thank you, I don't quite understand that the data has been set to an empty array when I click the second time, from the memory snapshot, the previous data still exists, it hasn't been GC, here is the way I use react, is it wrong?

**Comment by rocky-one** [comment]
> Usually if there's a memory leak then it will show up as an error in the console tab.
> 
> Your onClick function keeps pushing data into an array so that's why the size increase.
> 
> Try using functions if you are starting out with React. It will make life much easier. Read up on the docs.

Thank you, I don't quite understand that the data has been set to an empty array when I click the second time, from the memory snapshot, the previous data still exists, it hasn't been GC, here is the way I use react, is it wrong?

**Comment by MacThanos** [comment]
If you are using Google Chrome, trying installing the extension 'React DevTool' to see what the state is doing when you toggle that button. I wouldn't worry about the memory tab for learning purpose...

**Comment by rocky-one** [comment]
> If you are using Google Chrome, trying installing the extension 'React DevTool' to see what the state is doing when you toggle that button. I wouldn't worry about the memory tab for learning purpose...

Thank you. I'll try

**Comment by samcooke98** [comment]
Just checking that you forced a GC between each memory snapshot? IE: You pressed the little trash can icon. 
![image](https://user-images.githubusercontent.com/787007/89236452-ee6cb800-d633-11ea-85e2-6f072af924c9.png)


Would be nice if you provided a runnable example of this, in a code-sandbox for example. Would save people some time in trying to repo the example :)

**Comment by rocky-one** [comment]
> Just checking that you forced a GC between each memory snapshot? IE: You pressed the little trash can icon.
> ![image](https://user-images.githubusercontent.com/787007/89236452-ee6cb800-d633-11ea-85e2-6f072af924c9.png)
> 
> Would be nice if you provided a runnable example of this, in a code-sandbox for example. Would save people some time in trying to repo the example :)

Thank you. I wrote an example [](https://codesandbox.io/s/tender-dewdney-l5zcs?file=/src/App.js)

**Comment by rocky-one** [comment]
> Just checking that you forced a GC between each memory snapshot? IE: You pressed the little trash can icon.
> ![image](https://user-images.githubusercontent.com/787007/89236452-ee6cb800-d633-11ea-85e2-6f072af924c9.png)
> 
> Would be nice if you provided a runnable example of this, in a code-sandbox for example. Would save people some time in trying to repo the example :)

Thank you. I wrote an example.[example](https://codesandbox.io/s/tender-dewdney-l5zcs?file=/src/App.js)

**Comment by gaearon** [comment]
Does this reproduce with React 18?

**Comment by rocky-one** [comment]
> Does this reproduce with React 18?

Not reproduced in react18, good.
