### ISSUE TITLE
Bug: React.Lazy not working on Firefox, with HTTPS

### ISSUE THREAD

**Issue by master117** [facebook/react#19492]
I have a bit of an odd Issue. I'm using React.lazy to load stylesheets based on what page a user is on. Since they cancel each other out I only want one of them to be loaded / I want them to be split. This works in all browsers and both with HTTPS and HTTP. Except in Firefox with HTTPS. My certificates are self-signed, so firefox is having some issues with them, but I added exceptions for them.

React version: >16.11
Firefox Version: 78.0.2

## Steps To Reproduce

Since this is likely a HTTPS certificates issue I can't produce a minimal example easily.

I'm using an implementation of React Lazy that lets me retry on failure, but it doesn't work either way:

```
/**
 * Tries lazy loading, retries 4 times on failure with a pause of 1 second inbetween
 */
const retryLazyLoad = (fn: () => Promise<any>, retriesLeft = 5, interval = 1000): Promise<{ default: ComponentType<any>; }> => {
  // Return function as promise
  return new Promise((resolve, reject) => {
    fn()
      .then(resolve)
      .catch((error) => {
        console.log(error);
        setTimeout(() => {        
          // On error either reject or retry
          if(retriesLeft === 1) {
            // reject('maximum retries exceeded');
            console.log("Maximum retries for lazy loading themes exceeded!");
            reject(error);
            return;
          }

          // Passing on "reject" is the important part
          retryLazyLoad(fn, retriesLeft - 1, interval).then(resolve, reject);
        }, interval);
      });
  });
}

/**
 * The theme components only imports it's theme CSS-file. These components are lazy
 * loaded, to enable "code splitting" (in order to avoid the themes being bundled together)
 */
const RgaTheme = React.lazy(() => retryLazyLoad(() => import('../../Pages/Content/Graph/RgaTheme')));
const RlmTheme = React.lazy(() => retryLazyLoad(() => import('../../Pages/Content/List/RlmTheme')));

const ThemeSelector: React.FunctionComponent<IThemeSeletorProps> = (props) => {
  return (
    <React.Fragment>
      {/* Conditionally render theme, based on the current seleced module*/}
      <React.Suspense fallback={<ProgressSpinner />}>
        {props.module === "graph" ? <RgaTheme /> : <RlmTheme />}
      </React.Suspense>
      {/* Render children immediately */}
      {props.children}
    </React.Fragment>
  );
};
```

## The current behavior

React Lazy runs into an exception when retrieving the css chunk 4.

![Unbenannt3](https://user-images.githubusercontent.com/444009/88930921-72155600-d27c-11ea-9160-20d1a72d0cb2.PNG)

![Unbenannt2](https://user-images.githubusercontent.com/444009/88930335-a5a3b080-d27b-11ea-9c74-819ace8d910f.PNG)

The requests are not even shown in firefox, 

![Unbenannt4](https://user-images.githubusercontent.com/444009/88931034-97a25f80-d27c-11ea-9579-2c2486e0f20b.PNG)

but in firefox developer edition.

![Unbenannt](https://user-images.githubusercontent.com/444009/88930168-65443280-d27b-11ea-9255-81f6638eec42.PNG)

The requests being seen and marked as 200 and the fact that it works in all other browsers leads me to believe there is an issue between firefox + https and React.lazy.

## The expected behavior

React.lazy should have no issue loading my css.

Please let me know if I can provide additional details.

**Comment by vkurchatkin** [comment]
This has nothing to do with React. `React.lazy` simply accepts a function that returns a promise. This promise  is not created by React itself.

**Comment by aweary** [comment]
Yeah, React has no part in the HTTP request that your Promise is making. I recommend checking out the list of great support resources listed in the docs: [Where to Get Support](https://reactjs.org/community/support.html).

**Comment by master117** [comment]
The HTTP Request my Promise is making originates from nothing else but an import, it can be boiled down to:

React.lazy(() => import('SomeOtherPage')));

I don't see how I could even adjust that.

**Comment by vkurchatkin** [comment]
@master117 whatever `import()` does is controlled by webpack
