### ISSUE TITLE
TransitionGroup buggy with null children

### ISSUE THREAD

**Issue by spicyj** [facebook/react#1949]
I feel like we've had a million of these issues, but it seems like switching from

```
<TransitionGroup>{one}{two}</TransitionGroup>
```

to

```
<TransitionGroup>{null}{null}</TransitionGroup>
```

doesn't perform an exit animation on the two components; it probably should.

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
