### ISSUE TITLE
Bug: requirement on matching SSR and CSR forces CSR to return null

### ISSUE THREAD

**Issue by hkjpotato** [facebook/react#19501]
React16 asks for exact matching between SSR and CSR for the first round of rendering. If I have partial content which depends on `window.width`, I need to force it to return null in the first render of client side hydration, resulting in bad performance.

Use case: say I have an UI widget contains the following structure
```
<div>
   <img src={imgSrc}
   {window && <video src={window.innerWidth > 500 ? desktopSrc : mobileSrc} />}
</div>
```

if it is done by purely client side rendering, everything is good. In the first render, I can show the right video to customer depending on ```window.innerWidth```.

But lets say I want to support SSR for this widget. Because in server side the `window` is `undefined`, it will just return
```
<div>
  <img src={imgSrc}
</div>
```
My image is happily enjoying the preloading of browser.

In client side hydration, it will update it with the right video in the first render. Say if currently `window.innerWidth < 500`, it will return
```
<div>
  <img src={imgSrc}
  <video src={mobileVideo />
</div>
```
Not that bad since customers just need to wait for the first round of hydration.

But React does not like it, since there is a mismatch between SSR and CSR for their first render. The 'right' way to do it is
```
<div>
   <img src={imgSrc}
   {didMount && <video src={window.innerWidth > 500 ? desktopSrc : mobileSrc} />}
</div>
```
So that the first round of hydration matches SSR result (no video). But we are forcing customer to wait a little longer. 

Then I question myself:  _what's the benefit of doing SSR for the content that cant be determined in server side? It seems  purely client side render wins(at least we can see the right video on first CSR round), but...I still want to do SSR for the other contents.. Can I ask React to only do partially SSR for my UI? No..._

**Comment by bvaughn** [comment]
This is not a *bug*. It's just how the server-side rendering API works. Mismatched output on the server/client can indicate a bug, so React warns about it. (This warning happens in DEV only, and React does not actually do anything more than warn– it does not try to patch up the differences.)

As for the question of, "what's the benefit of doing SSR" – the majority of your app does not change in the scenario you describe, so the second render after client mount can be *very fast*. Meaning that the overall experience can still be better with SSR than without.
