### ISSUE TITLE
TransitionGroup wrapper interferes with a component's refs

### ISSUE THREAD

**Issue by bjbrewster** [facebook/react#1950]
Hello

We've encountered unexpected behaviour when wrapping list items that have refs (eg `<input ref={key} key={key} />`) in a `TransitionGroup`.  The refs are no longer found in the component's `this.refs` unless you wrap each item in an extra element (eg `<div key={key}><input ref={key} /></div>`).  The problem only seems to occur with `TransitionGroup`.  `CSSTransitionGroup` works fine and I created my own test wrapper component which also worked.

Please see attached fiddle for contrived example that should focus the new list item when you click the button: http://jsfiddle.net/Zimble/gsj3E/10/

Many thanks,
Brendan

**Comment by nickcoad** [comment]
+1 I would also love a workaround for this - it seems like wanting to use refs on TransitionGroup children would be a very common requirement.

**Comment by ccorcos** [comment]
Oy. I'm having this issue as well. Very annoying. If you pass a function as a ref, it never gets called either. So transition group is just totally dropping the refs which is a bummer. 

This is actually a huge problem for me. I'm using that ref to execute an animation. I think this issue should be reopened.
