### ISSUE TITLE
Bug: can't inspect well react warnings for `componentWillReceiveProps has been renamed`

### ISSUE THREAD

**Issue by Aarbel** [facebook/react#19518]
Cf the screenshot bellow. I have no `componentWillReceiveProps` in my code, so the warning comes from a library.
I don't know how to quickly identify which library causes this warning and make a fix pull request on the repo of this library.

Any tips to also remove the warning ?

Thanks a lot 

![image](https://user-images.githubusercontent.com/25119847/89186329-ebbe8400-d59b-11ea-87f4-47d2f215be72.png)

**Comment by bvaughn** [comment]
The error message shows the names of the components containing the old lifecycle method:
> Please update the following components: Checkbox, Folder, GUI

Given those names, my guess is that it's a UI library like [material-ui](https://github.com/mui-org/material-ui).

Unfortunately there is no way for us to detect and log the name of the packages. That metadata wouldn't be accessible to React at runtime. We could print full component stacks showing each place the problematic components are used, but that would make the warnings *very long* and clutter the console more than they already do, so we opted to just show the name of the components instead.

Hope this is hepful!
