### ISSUE TITLE
State can be referenced before its definition without error

### ISSUE THREAD

**Issue by camway** [facebook/react#19529]
Referencing a state variable prior to its declaration does not result in any error or warning

React version: 16.12
Node version: 12.16

The easiest way to show this is with an example:

```
export default function Other(props) {
  console.log("something: ", something);
  const [something, setSomething] = React.useState(null);
  return (
    <div>
      {something}
    </div>
  );
}
```

This is the transpiled form:
```
  function Other(props) {
    console.log("something: ", something);
    var _React$useState = React$1__default.useState(null),
        _React$useState2 = _slicedToArray(_React$useState, 2),
        something = _React$useState2[0],
        setSomething = _React$useState2[1];
    return React$1__default.createElement("div", null, something);
  }
```

This should throw an error saying something like undefined variable or function, or maybe can't reference before initialization. 

Instead, the first mount will just result in a debug saying 'undefined'. No other information will be provided.

I can't show the code this is happening in as it doesn't belong to me, but the above is an incredibly simple version of the bug I had to patch today. Once you realize what's happening, it's very easy to fix. Finding the source of the problem though was a nightmare.

## The current behavior

No warning or error.

## The expected behavior

Throw an error that a constant was referenced prior to initialization. Alternatively, an error that the variable is undefined would work equally well.

**Comment by bvaughn** [comment]
This issue is not specific to React. It is just how JavaScript works– it hoists variable declarations (but not assignments). You can read more about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var
