### ISSUE TITLE
Bug: Using HTML entity in JSX is handled weirdly

### ISSUE THREAD

**Issue by MathiasKandelborg** [facebook/react#19536]
# React version: 16.13.1

When using html entity escape sequences such as `&apos;` and `&middot;`, those characters are displayed as their respective characters: `'` and `·` . I've found, however, that when using entity names such as `&lpar;` or `&rpar` they are displayed as written e.g.:
```jsx
// ...
  return (
    <React.fragment>
      <p>&lpar;</p>
    </React.fragment>
  )
}
```

Outputs: `&lpar;`

Ok so there's clearly some escaping going on, but only on some 'codes', let's try exploring and have some fun!

Since the HTML entity is displayed as written, how about the HTML code? Instead of `&lpar;` we will try and use the corresponding `&#40;`. __This works as I expected before this all started! It shows the character!__

Well then! Time to look at [some specifications](https://dev.w3.org/html5/html-author/charref). Let's also try `&centerdot;` which is apparently also a 'code' for the `&middot;` character. __This does not work as I've come to expect! It does not show the character and instead shows the escaped version again.__

To me this raises more questions than I had initially: 
- How are strings escaped in react/jsx?
- Why does the character codes and _some_ entity names work?
  - So far I've had 100% success using the #xxx character codes, really contrasted by the very sporadic results using entity codes.

I spent a few minutes looking in React source but haven't found anything useful yet. I think it's better to make an issue at this point and let others have a look.

To me, it seems there's differences in implementation and specification.

## Steps To Reproduce

Open the Code sandbox example with the React template. I've simply input the aforementioned entity codes and added another h1 tag with working hex codes:

https://codesandbox.io/s/react-html-entity-code-escaping-1rwsu

**Comment by vkurchatkin** [comment]
I don't think this is documented, but this is what Babel has: https://github.com/babel/babel/blob/eea156b2cb8deecfcf82d52aa1b71ba4995c7d68/packages/babel-parser/src/plugins/jsx/xhtml.js

**Comment by MathiasKandelborg** [comment]
Oh wow! So it is a difference in specification and implementation! Awesome, now I just have to open an issue in babel instead as this seems to be where the 'magic' happens!
