### ISSUE TITLE
Suggestion: Add release date in the experimental (0.0.0) version

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#19538]
https://samver.org/

It's hard to know which one is the latest experimental react version in the `yarn` or `npm`.

0.0.0-experimental-ede917064
0.0.0-experimental-4c8c98ab9
0.0.0-experimental-7f28234f8

Can you tell which one is newer without doing querying on the web?

I suggest adding a release date in the version.

`0.0.0-experimental-20200802-3d0895557`

**Comment by bvaughn** [comment]
This is intentional. Experimental releases are one-offs. Their version numbers have no semantic meaning, in that we may add, remove, or changes features between each release in a breaking way.

If you want to know the release date of a specific version, NPM can tell you, e.g.

```sh
$  npm info react@0.0.0-experimental-3d0895557

...

published 5 days ago by gaearon <dan.abramov@gmail.com>
```
