### ISSUE TITLE
Bug: HOC (memo/forwardRef) should throw for noop function

### ISSUE THREAD

**Issue by ambar** [facebook/react#19548]
React version: v16

## Steps To Reproduce

```js
import React from "react";

export const Q = React.memo(() => {});
export const Z = React.forwardRef(() => {});

export default function App() {
  return (
    <>
      <Q />
      <Z />
    </>
  );
}
```

Link to code example: https://codesandbox.io/s/hoc-throw-null-xrhwg

## The current behavior

No errors.

## The expected behavior

> Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

**Comment by bvaughn** [comment]
Thanks for the report.
