### ISSUE TITLE
[Nit] The jsx command adds trailing whitespaces to compiled files

### ISSUE THREAD

**Issue by n1k0** [facebook/react#1954]
This happens using at least 0.10.0 and 0.11.1, and possibly others:

```js
/** @jsx React.DOM */

var a = (
  <Foo p="bar">
            // ^-- no trailing space
    <Qux />
  </Foo>
);
```

Compiles as:

```js
/** @jsx React.DOM */

var a = (
  Foo({p: "bar"}, 
              // ^-- trailing space added
    Qux(null)
  )
);
```

(Please ignore the invalid comment syntax here, added to highlight the issue.)

Unwanted trailing spaces can easily [mess up your use of a VCS](http://codeimpossible.com/2012/04/02/Trailing-whitespace-is-evil-Don-t-commit-evil-into-your-repo-/). While it's probably not a good practice to version compiled files, sometimes you don't have that option :)

We could use another tool in our chain to do some cleanup, but tbh it'd seem obvious to me that the jsx compiler just doesn't add trailing spaces in compiled files.

**Comment by zpao** [comment]
We're deprecating react-tools & JSXTransformer so closing this out.
