### ISSUE TITLE
Bug: Proxy on Context throws an error in DevTools

### ISSUE THREAD

**Issue by timothykrell-hb** [facebook/react#19545]
React version: 16.12.0

## Steps To Reproduce

1. Create an app with a `Proxy` function that has a `get` method that returns a function stored in Context
2. Attempt to look at Provider component in devtools

Link to code example:
https://codesandbox.io/s/stoic-jepsen-7jjfn?file=/src/App.js
https://7jjfn.csb.app/

## The current behavior
When using the devtools to inspect the `Context.Provider`, devtools throw an error:
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function () {
        return null;
      } could not be cloned.
```
Components using the context do not show info in devtools and show "Loading..." instead.

## The expected behavior
No error is thrown.

## Possibly Related
#16691

**Comment by pfongkye** [comment]
Hello,
I would like to work on this issue. If it's ok, any pointer to where to start will be welcomed.
Thanks.

**Comment by omarsy** [comment]
@pfongkye You’re still working on this issue?

**Comment by pfongkye** [comment]
> @pfongkye You’re still working on this issue?

Yes. Just got started.
