### ISSUE TITLE
Bug: In react@next ShadowRoot as rootElement in ReactDOM.render crashes

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#19558]
React version: 0.0.0-f77c7b9d7

## Steps To Reproduce

1. Mount a component with even listeners in a `ShadowRoot`

Link to code example:

- [codesandbox with `react@next`](https://codesandbox.io/s/shadowroot-as-root-element-pkktc?file=/package.json:178-193) (crashes)
- [codesandbox with `react@16.13.1`](https://codesandbox.io/s/shadowroot-as-root-element-pkktc?file=/package.json:178-193) (mounts  without errors/warnings)

## The current behavior

Throws with 
> ensureListeningTo(): received a container that was not an element node. This is likely a bug in React.

## The expected behavior

1. throw with a descriptive error that ShadowRoot is no longer supported as a root element

or

2. continue to allow ShadowRoot as a root element

No preference here. This was just from an old regression test we had. 

Will be fixed by https://github.com/facebook/react/pull/15894

**Comment by gaearon** [comment]
Fixed in `17.0.0-rc.1`.
