### ISSUE TITLE
Bug: event.type no longer matches the listener name for onFocus and onBlur

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#19560]
React version: 0.0.0-f77c7b9d7

## Steps To Reproduce

1. listen to `onFocus`
2. read `event.type`

Link to code example:

https://codesandbox.io/s/eventtype-in-reactnext-gt71n?file=/src/Demo.js

## The current behavior

`event.type === 'focusin'` for `focus` and `focusout` for `blur`. 

## The expected behavior

`event.type` is unaffected by changes to the native event React listens to. At least `onMouseEnter` works that way where you (sometimes?) have a `mouseover` native event but event.type will still read `mouseover`.

**Comment by gaearon** [comment]
If you'd like to send a fix we'll take it! Otherwise I'll look on Monday.
