### ISSUE TITLE
Missing Dependency: ReactDOMServer not available via umd

### ISSUE THREAD

**Issue by shirbr510** [facebook/react#19569]
Due to technical limitations, I'm currently using react in it's UMD form.
As far as I know, `ReactDOMServer` is both for server use and client use.
I tried to find it in `ReactDOM` global, but I was surprised that it is not included OOTB in react-dom 16.

1. Please provide us a way to consume `ReactDOMServer` as umd (either as part of ReactDom or as another distribution)
2. It seems like [you allowed it in the past](https://stackoverflow.com/questions/38666241/does-react-dom-server-work-on-the-client-side/38666691#38666691), so I'm wondering why did you drop support?

React version: 16.9
ReactDOM version: 16.9

**Comment by eps1lon** [comment]
You can find all builds in https://unpkg.com/browse/react-dom@16.9.0/umd/

It seems like there is a `ReactDOMServer` build available with https://unpkg.com/react-dom@16.9.0/umd/react-dom-server.browser.production.min.js.

All the links work for the latest release `react-dom@16.13.1`.

> It seems like you allowed it in the past, so I'm wondering why did you drop support?

`var ReactDOMServer = React.__SECRET_DOM_SERVER_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
console.log(ReactDOMServer.renderToStaticMarkup(<div />));` looks hardly like it was allowed.

**Comment by shirbr510** [comment]
Oh amazing!
Was looking at the reactjs docs and I couldn't find it anywhere
Cheers!
