### ISSUE TITLE
Bug: Cursor of controlled input of type email jumps to the beginning of input while deleting

### ISSUE THREAD

**Issue by kenodek** [facebook/react#19563]
At least 2 words needs to be typed. Then after deleting first one from the end cursor jumps to the beginning of input. It happens only for input of type email so it's supposed to be one word(email) but let's say that user typed second word by mistake and then trying to delete cursor jumps to the end. It happens on Chrome, Opera, Microsoft Edge however on Firefox bug does not occure on Firefox

React version: 16.12.0

## Steps To Reproduce
Create controlled input of type email and type firstWord secondWord. Try to delete secondWord and then firstWord

Link to code example:
https://codesandbox.io/s/react-cursor-jumps-to-end-for-input-type-email-9knfi?file=/src/App.js

## The expected behavior
Cursor does not jump to beginning of input while deleting

**Comment by bvaughn** [comment]
I can't reproduce the behavior described using Chrome, Firefox, or Safari (MacOS 10.15.6).

**Comment by kenodek** [comment]
@bvaughn I checked it only on Windows 10 and Ubuntu 20.04

**Comment by gaearon** [comment]
I can repro.

**Comment by gaearon** [comment]
This is the same as https://github.com/facebook/react/issues/15418.
