### ISSUE TITLE
Bug: react-hooks/exhaustive-deps methods used in dependencies array

### ISSUE THREAD

**Issue by Ayc0** [facebook/react#19573]
`eslint-plugin-react-hooks` version: 4.0.8

## Steps To Reproduce

1. Create a hook with dependencies
2. Use a method on object `like foo.bar()`
3. The entire object is marked as required in the deps array instead of the method (`foo` instead of `foo.bar`)

Link to code example:

https://codesandbox.io/s/exhaustive-deps-error-demo-r0gnu

## The current behavior

The entire object is marked as required in the deps array instead of the method (`foo` instead of `foo.bar`).
But if you create a temporary variable (like `const bar = foo.bar`), now `foo.bar` is valid in the deps array

## The expected behavior

The method should be enough in the deps array

## Code sandbox link

https://codesandbox.io/s/exhaustive-deps-error-demo-r0gnu

**Comment by Ayc0** [comment]
In addition, I noticed that in TS, doing `(foo.bar as <insert type>)()` (like `(foo.bar as any)()`)  was enough to properly detect the variable

**Comment by billyjanitsch** [comment]
The current behavior is correct. `foo.bar()` has different behavior than `const bar = foo.bar; bar()`:

```js
const foo = {
  data: 1,
  bar(n) {
    return this.data
  },
}

foo.bar() // returns 1

const bar = foo.bar
bar() // returns undefined
```

If a callback/effect is calling a function as a method, then it needs to depend on the entire object.

>In addition, I noticed that in TS, doing (foo.bar as <insert type>)() (like (foo.bar as any)()) was enough to properly detect the variable

This looks like a bug in the ESLint rule. `(foo.bar as <insert type>)()` _should _ error if `foo` isn't in the deps array.

**Comment by jackrmomo** [comment]
package.json

**Comment by Ayc0** [comment]
Thanks for the explanation @billyjanitsch
