### ISSUE TITLE
Bug: onInput is not firing on contentEditable div in IE11

### ISSUE THREAD

**Issue by cy6eria** [facebook/react#19570]
When using onInput event on contentEditable div, the event is not being fired on IE11. It does work on Chrome 84.0.4147.105 (64-bit).

React version: 16.13.1

I can't find any service which supports IE, thats why I provide only code example.

Code example:

```
const MessageBox = () => {
  const [state, setState] = useState('');
  
  const handleInput = useCallback((e) => {
    setState(e.currentTarget.innerHTML);
  }, []);

  return (
    <div
        role="textbox"
        tabIndex={0}
        contentEditable
        onInput={handleInput}
      />
  );
};
```

**Comment by DaniAcu** [comment]
According to MDN. The input event is just supported on text and password. On the docs, it's saying that this happens on explorer 9. But I'm pretty sure the input event is not completely supported on e11. If you try with vanilla JS code, you will see the same error. Try to use `onKeyUp` or maybe `onChange` according to your use case.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

**Comment by cy6eria** [comment]
@DaniAcu any way, IMO, it doesn't mean that it should work in Chrome, but not in IE. For example, `onChange` doesn't work for div at all.

**Comment by DaniAcu** [comment]
@cy6eria Emm yeep. I mean there some features that are supported on Chrome but not on IE. Because it's not using the same engine. I'm sure that is not a react problem, it's more IE problem haha. 

Maybe you need to use another strategy to support your code on IE. I found that issue that maybe help you https://github.com/lovasoa/react-contenteditable/issues/43

**Comment by cy6eria** [comment]
@DaniAcu I got ur idea. You think that if it's works as native this is fine. But [there](https://github.com/facebook/react/issues/7280) is an issue, which is closed. There is said that in some version it was working as I expect and it was marked as a bug.

**Comment by gaearon** [comment]
We dropped support for IE in React 18 so this is unlikely to get a fix.
Sorry.
