### ISSUE TITLE
Struggling while reading codes on the docs.

### ISSUE THREAD

**Issue by Mr-spShuvo** [facebook/react#19585]
Hi, there. 
I'm relatively new here and trying to learn react by reading the react documentations.
But as a beginner, I found it's really hard to reading and understanding codes on the documentation website without any kinds of coding highlights like other documentation website has. And to be honest, without the coding highlights, it more like a medium website rather than a documentation website of the most popular library. 
 
Also, I think there is **an design issue** as well. On the codes, some of the lines are way much off the screen and they are not scroll-able at all. Event if, I'm at 50% of the browser windows, I could not get to read the whole lines (Attached below).

![Screenshot_2020-08-11 Using the Effect Hook – React](https://user-images.githubusercontent.com/22437186/89857130-0ce72c00-dbbd-11ea-944b-d110648580f8.png)

I'm using **firefox - version 79.**

I think these design issues need to resolve. 
Otherwise, thanks for the awesome documentations.

**Comment by judicaelandria** [comment]
Hey @Mr-spShuvo ,
Can you refresh your browser, please? I can't reproduce the error here, mine works fine with chrome 79

**Comment by Mr-spShuvo** [comment]
So, I did check. It worked on my Chrome as well. But with my firefox developer edition, it's the same as before.

**Comment by judicaelandria** [comment]
I made a mistake, it's work with firefox 79, sorry

**Comment by Mr-spShuvo** [comment]
Hey @judicaelandria, A fresh install of firefox resolves this issue for me. May be it's the firefox extention that causes the problem.
