### ISSUE TITLE
Bug: onChange props is being swallowed in Higher-Order-Component

### ISSUE THREAD

**Issue by eakl** [facebook/react#19580]
Input with onChange props lose focus when wrapped in a Higher Order Component

Link to code example:

https://codesandbox.io/s/happy-bell-s6q0z?file=/index.js

React version: 16.13.1

## Steps To Reproduce

1. Focus on any input of **Column 2** with onChange prop
2. Type a 2-digit number (e.g. "23") on it
3. It loses focus after the 1st digit (e.g. after "2")

## The expected behavior

That the **InputNumber** doesn't lose focus after the 1st digit is entered (e.g. after "2"). Allowing for multi-digit input (e.g. "2345")

## The current behavior

After the 1st digit is entered, **InputNumber** loses focus

#### Hypothesis 1
onChange props is being swallowed in Higher Order Component
`Line 103`: Replace InputNode by InputNumber

**Comment by gaearon** [comment]
React has no concept of higher order components; this is an abstraction that only exists in your JavaScript code. So this concept cannot be responsible for a problem related to DOM events.

There is quite a lot of code in your sandbox. Please try to reduce it to the *minimal* reproducing case so we can take a look.

**Comment by vkurchatkin** [comment]
@eakl that's because you are creating `InputNode` inside of `EditableCell`. It essentially means that React sees `InputNode` as a new component on every render, which causes it to be remounted and to lose all state (e.g. focus).

**Comment by eakl** [comment]
@vkramskikh Thank you. Indeed, there is no issue except the structure of my code. I'm closing

**Comment by gaearon** [comment]
Thanks for looking @vkurchatkin
