### ISSUE TITLE
Bug:  useState() not working properly with requestAnimationFrame v/s this.setState() working fine...!!!

### ISSUE THREAD

**Issue by KushagraMehta** [facebook/react#19586]
React version: 16.12.0

## Link to code example:

1. [useState()](https://codesandbox.io/s/audio-visualization-with-hooks-m56cg?file=/src/Visual.jsx:721-742)
2.  [this.setState()](https://codesandbox.io/s/audio-visualization-with-component-6v5ts?file=/src/AudioAnalyser.jsx)

## About the code

Here I'm using [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) for audio manipulation. In my code, [_AudioWorkbench.waveAnalyser.frequencyBinCount_](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/frequencyBinCount) give me the length of Audio array and [_getByteTimeDomainData()_](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteTimeDomainData) update the Data array so there is no direct way to call the __setState__ or __useState__ so I used a temporary variable to update it by __requestAnimationFrame__. But while doing this with Hooks useState hooks variable does not change. I even use useEffect to see the update. Whereas with the React component everything works fine.

## The current behavior
useState hooks not updating the state on every call of requestAnimationFrame while the setState works fine.

## The expected behavior
Both should give the same result. Either they update the state or they should not.

**Comment by jameslahm** [comment]
Hi, the cause is that useState hook will shallow equal the argument, similarly `Object.is`, if it equals, useState will not update. So `setDataArray(tmpDataArray.current);` will not update, because `tmpDataArray.current` remains constant(reference), And you can change to `setDataArray(new Uint8Array(tmpDataArray.current.buffer);` that should works.
