### ISSUE TITLE
Bug: Chrome Extension for DevTools Missing

### ISSUE THREAD

**Issue by maxehnert** [facebook/react#19583]
The chrome webstore does not appear to have the React DevTools extension listed anymore.
All the links from reactjs.org are going to a 404 

React version: N/A

## Steps To Reproduce

1. Go here: https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-devtools-profiler
2. Click link to Chrome Browser Extension
3. Observe 404

## The current behavior
React DevTools for Chrome is missing from webstore

If you go to https://chrome.google.com/webstore/search/react
the entry for the DevTools is there but clicking on it brings up an error modal.

## The expected behavior
be there and work :)

**Comment by saqibnaveed** [comment]
It is appearing fine for me when searching for https://chrome.google.com/webstore/search/react or going to extension's page: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

**Comment by mvhk** [comment]
It's working fine, and I can see them 
![image](https://user-images.githubusercontent.com/30367973/89907319-24003b00-dc0a-11ea-9b52-1f986d4cd12b.png)

**Comment by bvaughn** [comment]
Looks like the link is working fine for me (and others above) @maxehnert. I assume the issue was caused by some temporary bug in the Chrome store.
