### ISSUE TITLE
Chrome DevTools tab icon doesn't match screenshots on webstore

### ISSUE THREAD

**Issue by swrobel** [facebook/react#19594]
## The current behavior
React logo in the tab is extremely small & indecipherable
<img width="176" alt="Screen Shot 2020-08-12 at 5 54 27 PM" src="https://user-images.githubusercontent.com/157270/90082546-e3192c80-dcc4-11ea-81e0-f53cd86f6bda.png">

## The expected behavior
Should be as [shown here](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)
![image](https://user-images.githubusercontent.com/157270/90082581-f926ed00-dcc4-11ea-9140-f7b10150c82d.png)

**Comment by bvaughn** [comment]
I'm... not sure why we're using the "⚛" character instead of "⚛️ "
