### ISSUE TITLE
React Developer Tools doesn't work on Firefox

### ISSUE THREAD

**Issue by catalin560** [facebook/react#19601]
![Screenshot (2)](https://user-images.githubusercontent.com/22744333/90129083-8581f000-dd57-11ea-8c73-fe3742b305c8.png)

When I click on the React Developer Tools icon from the toolbar menu it says: _This page is using the development build of React_
but when I try to access either tabs in the developer tools it says: _Unable to find React on the page._

In the Console tab I get this message:
> Failed to get subsystem status for purpose Error: Conduits:RuntimeMessage: message reply cannot be cloned.
> sendMessage moz-extension://81f39e75-06db-496a-a3e4-badff9a00d82/content-utils.js:47

Firefox is up to date
Extension is up to date (_Created from revision fed4ae024 on 7/15/2020_ according to its description)

So what am I doing wrong here?

**Comment by bvaughn** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by catalin560** [comment]
Found the problem... it seems it doesn't work in incognito mode! Thank you for your help!

**Comment by bvaughn** [comment]
Ooh, yeah. You'll have to add a special permission per extension for that, I believe.

Glad you got it sorted out!
