### ISSUE TITLE
Bug: Clicking select elements in Firefox React Devtools settings doesn't open options in detached Firefox Developer Tools window

### ISSUE THREAD

**Issue by benatshippabo** [facebook/react#19618]
React version: 16.9
React Developer Tools: 4.8.2
Firefox: 79.0 and 80.0b8

## Steps To Reproduce

1. go to a webpage using react
2. open firefox developer tools in a detached window
3. go to React Developer Tools "Components" tab
4. open up settings:
![image](https://user-images.githubusercontent.com/66273043/90290100-1e853980-de32-11ea-87c9-679f07b0843e.png)
5. click the "Theme" setting `select`
6. notice options don't open
7. tab to focus "Display density" setting `select`
8. hit spacebar
9. notice options don't open

## The current behavior
Clicking `select` elements in the React Developer Tools for Firefox does not open the select options.

## The expected behavior
Clicking `select` elements in the React Developer Tools for Firefox does open the select options.

**Comment by bvaughn** [comment]
Hm... I can't repro this this with Firefox 79.0 (64-bit) and React DevTools 4.8.2-fed4ae024. (Haven't seen any other reports of it either.)

**Comment by benatshippabo** [comment]
> Hm... I can't repro this this with Firefox 79.0 (64-bit) and React DevTools 4.8.2-fed4ae024. (Haven't seen any other reports of it either.)

😢  strange, my coworkers are also able to reproduce the issue. Not sure is os matters here, but I'm using MacOS 10.15.6 (19G73)

**Comment by bvaughn** [comment]
I am also using 10.15.6 (19G73).

Hm. I wonder if you and your coworkers have some other add-on(s) installed in Firefox that may be interfering in some way? I have seen that sort of thing on occasion.

**Comment by benatshippabo** [comment]
I think I found the issue, the select works when the firefox developer tool is mounted to the window, but when you have it in a separate window the select stops working.

**Comment by benatshippabo** [comment]
Not sure if you guys are doing custom positioning for the select, but when the zoom level is default it looks like this:
![image](https://user-images.githubusercontent.com/66273043/90295595-45e20380-de3e-11ea-832d-64ca6160a843.png)

but when you `cmd +` a few times the options gets offset by a lot:
![image](https://user-images.githubusercontent.com/66273043/90295637-5d20f100-de3e-11ea-9d31-70d49b5381a6.png)

**Comment by bvaughn** [comment]
We are not doing any custom positioning for the select.

**Comment by bvaughn** [comment]
This seems like it might just be a Firefox browser bug. Can you reproduce with plain HTML?

**Comment by benatshippabo** [comment]
You're right it's looking like a firefox bug, found an addon with the same issue. The plain `select` [here](https://github.com/MisterPhilip/omnibug/blob/9387aadee1ae1454f42450960dc4b86350330f64/src/devtools/panel.html#L65):
![image](https://user-images.githubusercontent.com/66273043/90459045-e9d4e480-e0b4-11ea-9de7-74fe438e9cd5.png)

**Comment by bvaughn** [comment]
Thanks for the update!
