### ISSUE TITLE
Bug: Event Capture does not work in video environment

### ISSUE THREAD

**Issue by JenniferFuBook** [facebook/react#19623]
This is related to https://github.com/facebook/react/issues/18932.
It seems that the problem still exists.

React version: 17.0.0-rc.0

## Steps To Reproduce

1. Copy https://gist.github.com/JenniferFuBook/c7c9ffd6dbd4e8b4e64afe9e6c66f66c#file-appwithvideo-js and replace App.js in Create React App.
2. Name a video file IMG_2313.mp4, and put it under public directory.
3. npm start

Another example:

1. Copy https://gist.github.com/JenniferFuBook/04b81149af921efc316844e6783dff21#file-appwithyoutube-js and replace App.js in Create React App.
2. npm i react-player
3. npm start

## The current behavior
If you click on the video control, such as play button, the click event is not captured,

## The expected behavior
If you click on the video control, such as play button, the click event should be captured.

**Comment by gaearon** [comment]
Can you make a CodeSandbox reproducing case?

**Comment by JenniferFuBook** [comment]
Yes, it is https://codesandbox.io/s/sharp-nash-z01wk?file=/src/App.js.

**Comment by jameslahm** [comment]
@JenniferFuBook  I just make a [reproduce](https://codesandbox.io/s/sweet-bartik-fuhxl?file=/src/App.js) using your first example. It shows the click event can be captured correctly, for example, you can just click anywhere except controls widget in the video element. And clicking `play button` will not trigger `onclick` handler or `onclickCapture` handler, which may be caused by that the event of  clicking `play button` will not trigger other event handlers except for just playing the video, here is a [reproduce](https://codesandbox.io/s/musing-mcclintock-rxk31?file=/src/index.js) using raw HTML.  Clicking the` play button` will not trigger other event handlers, the same as `react`.

**Comment by gaearon** [comment]
@JenniferFuBook The sandbox you posted uses an iframe, so I wouldn't expect clicks to propagate.

**Comment by JenniferFuBook** [comment]
Thanks, @gaearon and @jameslahm!
Will this issue be fixed in React 17?

**Comment by gaearon** [comment]
Isn't this how the DOM works? Events from iframes don't get propagated into the outer tree, by design.

**Comment by JenniferFuBook** [comment]
For the [reproduce](https://codesandbox.io/s/musing-mcclintock-rxk31?file=/src/index.js)  example, the `<video>` tag is not an iframe. Why does the whole area can receive `onClick` and `onclickCapture`, except the controls?

**Comment by gaearon** [comment]
Why not listen to `play` event instead? https://codesandbox.io/s/thirsty-meitner-1ez6

**Comment by JenniferFuBook** [comment]
@gaearon, somehow your example is not visible (status code 404).

Do you mean something similar to the code in the first example?
```
         <video
            width="100%"
            height="100%"
            controls
            onClick={() => console.log("clicked HTML5 video")}
            onClickCapture={() => console.log("captured HTML5 video")}
            // onPlay={() => console.log("playing...")}
            // onPause={() => console.log("paused")}
            // onEnded={() => console.log("stopped")}
         >
```

We are not getting all videos in mp4 format. Some are in the iframes similar to the Youtube example, and some use proprietary events. I am looking for a generic way to response to play events.

**Comment by jameslahm** [comment]
@JenniferFuBook , Dan's reproduce maybe [https://codesandbox.io/s/thirsty-meitner-1ez6f?file=/src/index.js](https://codesandbox.io/s/thirsty-meitner-1ez6f?file=/src/index.js). You can handler `onplay` event. As for iframe, in your example using `react-player`, I think you can also use `onPlay` callback. And `react-player` seems not to expose `onClick` callback, [its doc](https://github.com/CookPete/react-player). So in your [https://codesandbox.io/s/sharp-nash-z01wk?file=/src/App.js](https://codesandbox.io/s/sharp-nash-z01wk?file=/src/App.js.) reproduce, `onClick` and `onClickCapture` will also not triggered.

**Comment by JenniferFuBook** [comment]
Yes, React works as expected. Thanks again, @gaearon and @jameslahm!
