### ISSUE TITLE
Bug: When I use the StrictMode component, all my components will be rendered twice.

### ISSUE THREAD

**Issue by janryWang** [facebook/react#19626]
React version:

16.12.0

## Steps To Reproduce

Check the console

Link to code example:

https://codesandbox.io/s/wizardly-goodall-w2n0z?file=/src/index.js

## The current behavior

Repeated rendering of components

## The expected behavior

Components should not be rendered repeatedly

**Comment by jameslahm** [comment]
Please see https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects, that's expected.
