### ISSUE TITLE
When will the official hook equivalents componentDidCatch be added?

### ISSUE THREAD

**Issue by bahuwang** [facebook/react#19630]
According to the React docs: 
```
Our goal is for Hooks to cover all use cases for classes as soon as possible. There are no Hook equivalents to the uncommon getSnapshotBeforeUpdate, getDerivedStateFromError and componentDidCatch lifecycles yet, but we plan to add them soon.
```
I wonder, is there a definite time? Like React V17.0.

**Comment by gaearon** [comment]
No specific time commitment. When we have a good API. :-) These should be fairly uncommon anyway.

**Comment by kachkaev** [comment]
@bahuwang meanwhile, feel free to use this unofficial functional component: https://github.com/bvaughn/react-error-boundary

**Comment by gaearon** [comment]
You can also write your own once and use it throughout the project.

**Comment by mindplay-dk** [comment]
*meanwhile, back in the jungle*

<img width="469" height="462" alt="Image" src="https://github.com/user-attachments/assets/f92c378c-d590-4476-8d5b-9b1a82768ab0" />
