### ISSUE TITLE
Bug: Property list does not render repeated spaces properly.

### ISSUE THREAD

**Issue by sammarks** [facebook/react#19639]
It looks like the property inspector inside React DevTools is not rendering repeating spaces properly.

I imagine this can result in some fairly frustrating debugging sessions when doing something like string matching 😄 

## Steps To Reproduce

1. Create a component that takes a string as a property.
2. Pass multiple spaces in a row to that property `name={'Testing[3 spaces]One Two'}` (I would type the actual spaces, but it appears Github truncates the extra spaces even inside the code snippet!)
3. Inspect that element inside React DevTools.

## The current behavior

The value of the prop `name` is rendered as `Testing One Two`

## The expected behavior

The value of the prop `name` should be rendered as `Testing[3 spaces]One Two`

---

Below are some screenshots of the behavior I'm seeing in production. Here's how the property value is rendered in inspector when it is output directly to the HTML:

![image](https://user-images.githubusercontent.com/424093/90543915-57841d80-e154-11ea-9151-6b9bd79b4c93.png)

And here is how that same value is rendered inside DevTools:

![image](https://user-images.githubusercontent.com/424093/90543947-636fdf80-e154-11ea-849b-77fea6cd0c5a.png)

**Comment by sammarks** [comment]
Looks like [this line](https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/devtools/views/Components/KeyValue.css#L24) is our culprit.

https://github.com/facebook/react/blob/23595ff593b2e53ddfec2a08e848704d15d84b51/packages/react-devtools-shared/src/devtools/views/Components/KeyValue.css#L24

According to [this StackOverflow answer,](https://stackoverflow.com/a/4503044/599132) we just need to change that from `white-space: nowrap` to `white-space: pre`. I will try to test that and put up a PR if it works.

**Comment by bvaughn** [comment]
@sammarks You're correct. Interested in contributing a patch for it? (If not, I'm happy to– but since you've already done the work I thought I'd ask.)

**Comment by sammarks** [comment]
@bvaughn I would be more than happy to! I'll aim to have something up by this evening.

**Comment by sammarks** [comment]
@bvaughn PR is up and ready for review!
