### ISSUE TITLE
Bug: (17.0.0-rc.0) No changes to Native Component Stacks in production environment

### ISSUE THREAD

**Issue by tjvantoll** [facebook/react#19649]
The React 17 RC blog post states “In React 17, the component stacks are generated using a different mechanism that stitches them together from the regular native JavaScript stacks. This lets you get the fully symbolicated React component stack traces in a production environment.”

I’ve been trying to see a difference between React 16.13.1 and React 17.0.0.rc.0, and so far have been unable to do so.

React version: 17.0.0.rc.0

## Steps To Reproduce

1. Start a new app with Create React App.
2. Run `npm install react-error-boundary`.
3. Use the code shown below in your `App.js`.
4. Run `npm run build` to create a production build.
5. Start a web server and open in a browser to see the error.

``` JavaScript
import React from 'react';
import { ErrorBoundary } from "react-error-boundary";

function ErrorFallback({ error }) {
  return (
    <div>
      <p>Something went wrong:</p>
      <pre style={{ color: "red" }}>{error.message}</pre>
    </div>
  )
}

function Bomb(foo) {
  return (
    <>
      <h1>💣</h1>
      {foo.toUpperCase()}
    </>
  )
}

function App() {
  return (
    <ErrorBoundary FallbackComponent={ErrorFallback} onReset={() => {}}>
      <h1>Error Testing</h1>
      <Bomb />
    </ErrorBoundary>
  );
}

export default App;
```

## The current behavior

The stack trace I’m getting is exactly the same with React 16.13.1 and React 17.0.0-rc.0.

![error-trace](https://user-images.githubusercontent.com/544280/90645684-42ff5e00-e204-11ea-8661-857346068939.png)

## The expected behavior

I’m expecting to get component names in my stack trace, or to see some difference in the stack traces between React versions.

Apologies if I’m debugging the wrong thing here, but I’m trying to figure out what actually changed in React 17. Appreciate your time.

**Comment by gaearon** [comment]
I think the difference should be in what you get in `componentStack` prop in `ErrorBoundary` (since you use that component). Not the `message`.

**Comment by tjvantoll** [comment]
@gaearon Thanks for the reply. Just tried manually logging that with this code.

``` JavaScript
function ErrorFallback({ componentStack }) {
  console.log("---");
  console.log(componentStack);
  console.log("---");

  return (
    <div>
      <p>Something went wrong:</p>
      <pre style={{ color: "red" }}>{componentStack}</pre>
    </div>
  )
}
```

And I still get a similar trace.

![Screen Shot 2020-08-19 at 10 27 26 AM](https://user-images.githubusercontent.com/544280/90647801-bbffb500-e206-11ea-8f05-0d38ce83c269.png)

**Comment by eps1lon** [comment]
> I’ve been trying to see a difference between React 16.13.1 and React 17.0.0.rc.0, and so far have been unable to do so.

Compare the component stack in the very first console.error issued by React triggered by an uncaught error:
- [in React 16](https://codesandbox.io/s/react-16-component-stack-rtx8z)
  ![component stack in React 16](https://i.ibb.co/7jgCWpt/component-stack-16.png)
- [in React 17](https://codesandbox.io/s/react-17-component-stack-b4je4?file=/package.json)
  ![component stack in React 17](https://i.ibb.co/2KpJPcL/component-stack-17.png)

In React 16 you will not have a clickable link to the source code. Just the name of the (here wrong) file. In React 17 your have a clickable link that points you automatically to the source. 

Though with  codesandbox the line number isn't quite right. Maybe that's an issue with their bundler, Maybe on React's side. But there is a difference.

**Comment by eps1lon** [comment]
> Thanks for the reply. Just tried manually logging that with this code.

Are you using a production deploy? Component names might be minified because the underlying functions are minified.

Including a full reproduction would help a lot.

**Comment by gaearon** [comment]
Just to be clear. You won't get *unminified names* in the stack. That can't work by itself.

What you should get are the *frames* (e.g. `in a (somefile.js:1234)`) that are in the same format as the native browser frames. This means that if you have an existing symbolication setup (e.g. Sentry) with sourcemaps, you should be able to decode them in the same manner.

**Comment by gaearon** [comment]
>And I still get a similar trace.

Seeing `in` there tells me that I think you're running 16 (it should say `at`, I think). Are you sure you updated `react-dom`? That's the package with the React engine, not `react`.

**Comment by tjvantoll** [comment]
Really appreciate all of your fast help here!

I see the difference between React 16 and 17 during development now with the help of your screenshots. In my production environment I am now seeing the following:

```
Bomb@http://localhost:3000/static/js/main.chunk.js:79:1
ErrorBoundary@http://localhost:3000/static/js/0.chunk.js:29998:37
App
```

So I think we’re probably good here. Give me a bit of time to process your comments, and see if I can decode these to what I’m looking for.

**Comment by eps1lon** [comment]
BTW @gaearon Do you agree that ![component stack in React 17](https://i.ibb.co/2KpJPcL/component-stack-17.png)
 looks odd?

There's a frame for `Unknown` below the error boundary which is probably the StrictMode frame. 

Looks like a codesandbox issue though. Downloading the sandbox as a zip and running it locally produces not a frame for `Unknown`.

The links to the source point to the bundled code though (locally as a basic create-react-app and inside codesandbox). Linking to the original code via source maps would be perfect. I guess this can't be solve inside React since the links in the thrown error stack are "fixed" by the chrome devtools?

**Comment by gaearon** [comment]
>The links to the source point to the bundled code though (locally as a basic create-react-app and inside codesandbox).

This seems odd. I would expect to link to sourcemapped code.
What about a regular `throw new Error('foo')` outside of React?

**Comment by eps1lon** [comment]
> This seems odd. I would expect to link to sourcemapped code.
What about a regular throw new Error('foo') outside of React?

To be clear: The JS stack from the uncaught error is source-mapped in React 17. Only the component stack is not source mapped. Whether the error is throw inside or outside of React doesn't make a difference for the source links in the JS stack.

**Comment by gaearon** [comment]
Can you make a screenshot illustrating it? I think I understand what you're saying but want to confirm.

**Comment by eps1lon** [comment]
> Can you make a screenshot illustrating it? 

![Screenshot from 2020-08-19 17-20-00](https://user-images.githubusercontent.com/12292047/90654105-4e707a80-e240-11ea-9f21-5aff868bc6b9.png)

Notice how the frame of `Bomb` after "the above error occured" is not source-mapped while the frame for `Bomb` after "uncaught TypeError" is.

**Comment by gaearon** [comment]
Hmm interesting. Thanks for sharing.

**Comment by gaearon** [comment]
Are there any browsers that rewrite the link? We should definitely bring this up as a feature request.

**Comment by tjvantoll** [comment]
After some more thorough testing I can confirm that this is working as expected. The main thing I was missing was the `componentStack` prop that @gaearon pointed out in an earlier comment. Now that I’m logging the correct thing I’m seeing the output I expect—and this is a pretty nice feature 🙂

I’ll leave this issue open in case you want to continue the feature-request conversation above.

Once again, I really appreciate the help here.

**Comment by eps1lon** [comment]
> Are there any browsers that rewrite the link? We should definitely bring this up as a feature request.

Same error built with `react-scripts@3.4.3`

Chrome 84

![React 17 stacks in Chrome 84](https://i.ibb.co/qdnybxh/react-17-chrome-stacks.png)

Firefox 79

![React 17 stacks in firefox 79](https://i.ibb.co/MBNZmxd/react-17-firefox-stacks.png)

- both apply source maps to the code links in the JS stacks
- both **don't** apply source maps to the code links in the component stack
- only chrome linkifies the code frame in the component stack

As far as I can tell this is a devtools specific feature and they are very picky with the format where they apply source maps to the frames. If you simply log `error.stack` (e.g. `console.log(error.stack)` or even `console.log(event.stack.slice(0, 500))`) you'll end up with source-mapped links. But as soon as you prefix the logged stack chrome devtools won't apply source maps (e.g `console.log(`my message: ${error.stack}`)`

PS:
Having the error appear twice in the console is quite confusing but I believe this was always the case.
