### ISSUE TITLE
Bug: react-hooks/exhaustive-deps does not recognize different signaturres

### ISSUE THREAD

**Issue by swissspidy** [facebook/react#19644]
`eslint-plugin-react-hooks` version: 4.1.2

## Steps To Reproduce

The current `additionalHooks` in the react-hooks/exhaustive-deps eslint plugin accepts a regular expression to match hook names. It always assumes the following format:
 
```
function useCustomHook(callback, deps) {}
```

However, this format is not always convenient when other arguments are available in the hook's signature, because the set of dependencies could potentially be large. In those cases, it'd be more convenient to place callback and deps as the last two arguments. For instance, the standard `useImperativeHandle` has an additional first argument:

```
function useImperativeHandle(ref, callback, deps) {}
```

## The current behavior

The `react-hooks/exhaustive-deps` rule does not recognize hooks with a function signature as mentioned above.

## The expected behavior

The `react-hooks/exhaustive-deps` rule allows customization to specify the argument offset via the `additionalHooks` config option.

----

**Note:** A PR for this already exists at #18861. This issue is meant to increase visibility for it, and allow any additional discussion if necessary.

**Comment by swissspidy** [comment]
Bump

**Comment by georeith** [comment]
👍  would also like to see this

**Comment by dartess** [comment]
bump
