### ISSUE TITLE
instance.render is not a function in react-dom.development.js:17160 while using this.props.children

### ISSUE THREAD

**Issue by sachintyagi** [facebook/react#19646]
Getting below error while using {this.props.children} in component file. 

**TypeError: instance.render is not a function**
finishClassComponent
D:/myreactapp/node_modules/react-dom/cjs/react-dom.development.js:17160
  17157 | } else {
  17158 |   {
  17159 |     setIsRendering(true);
> 17160 |     nextChildren = instance.render();
        | ^  17161 | 
  17162 |     if ( workInProgress.mode & StrictMode) {
  17163 |       instance.render();
View compiled

Please help.

Browser output:- 
![image](https://user-images.githubusercontent.com/763368/90636298-06555600-e248-11ea-8444-c8dd66269aae.png)

Package.json
![image](https://user-images.githubusercontent.com/763368/90636614-7bc12680-e248-11ea-8573-9147b0b8e844.png)

App.js
![image](https://user-images.githubusercontent.com/763368/90636654-8ed3f680-e248-11ea-8bbe-c363b0014af5.png)

Home.js
![image](https://user-images.githubusercontent.com/763368/90636691-9dbaa900-e248-11ea-95b7-039679cccb89.png)

Layout File front.js
![image](https://user-images.githubusercontent.com/763368/90636830-d064a180-e248-11ea-85e4-425d1820e392.png)

**Comment by gaearon** [comment]
This seems like a mistake:

```js
const AppRoute = ({component: Comment
```

Why are you renaming `component` to `Comment`? (Did you mean `Component`?) Instead the `<Component>` getting used is `Component` you imported from `React`, which is a base class without a `render` method. Hence the error.

**Comment by sachintyagi** [comment]
Hi Gaearon. Thanks for your help. Its working fine after rename Comment to Component.
