### ISSUE TITLE
Bug: Child Component State Updates Applied to Last Sibling Instead of Correct One

### ISSUE THREAD

**Issue by simps7b2** [facebook/react#19653]
I have a grid component that I am writing where a user is supposed to be able to click on a row and have that row transform into edit mode. A row in the grid is itself a component. I accomplish the transformation within the row component using the click event on cells that are editable. Once the click event fires on an editable row, the state of that component changes with the editing flag set to true. However, it is always the last row in the grid that gets re-rendered instead of the row that was clicked.

React version: v16.13.1

## Steps To Reproduce

1. Create a Row component that will render a single row of data (I'm using flex-box, but not sure if this is important)
2. Add a click event and a state hook to the Row component that will tell the row whether it is in highlight mode or not and highlight the row in yellow if it is being edited. Use the click event to toggle between highlight and normal; initialize this state to not-highlighted.
2. Create a Table or Grid component that will map a data array onto a set of Row components.
3. Run the Table component, click on a row, and notice it highlights the last row and not the one you clicked on.

Link to code example:
https://jsfiddle.net/3ursewLh/

## The current behavior
In the Fiddle listed, clicking on a row will highlight the last row and not the one you clicked on.

## The expected behavior
The row you clicked on should be highlighted instead of the last one.

**Comment by gaearon** [comment]
You forgot to put `let` or `const` before destructuring so you declared global variables by accident.
This is a fixed version. https://jsfiddle.net/gw94maky/

**Comment by simps7b2** [comment]
Ah, I see. Many thanks.
