### ISSUE TITLE
Add a toggle for Boolean props in DevTools

### ISSUE THREAD

**Issue by gaearon** [facebook/react#19662]
We previously had a feature where Boolean props would show a checkbox to the left of them in the DevTools pane. It was removed when the JSON editor was added, but I think we should add it back. It should work like this:

1. If the value is a boolean, the checkbox should show up to the left of `true` / `false` value
2. If it's no longer a boolean (e.g. gets edited manually), the checkbox disappears

**Comment by mdaj06** [comment]
I could take this up!

**Comment by gaearon** [comment]
Sounds good1

**Comment by mdaj06** [comment]
I have come up with a possible fix, could you suggest how i could test the changes made to dev-tools locally?

**Comment by gaearon** [comment]
Does this help?
https://github.com/facebook/react/tree/master/packages/react-devtools-inline#local-development

**Comment by mdaj06** [comment]
yup! looks like it can help. Thanks!
