### ISSUE TITLE
Bug: eslint-plugin-react-hooks optional chaining in deps

### ISSUE THREAD

**Issue by ricardotx** [facebook/react#19661]
**Packages**
* `"react": "^16.13.1"`
* `"eslint-plugin-react-hooks": "^4.0.8"`

The issue #18819 still happens with `eslint-plugin-react-hooks@4.0.8`.

Using the example code from the other issue gives the following errors:

![image](https://user-images.githubusercontent.com/37122343/90794940-59d9a980-e305-11ea-9ec0-98f69b41c280.png)

![image](https://user-images.githubusercontent.com/37122343/90795019-770e7800-e305-11ea-92b8-b64407b0b22c.png)

**Comment by gaearon** [comment]
Thanks, would you like to look into a fix?

**Comment by pfongkye** [comment]
Hi,
I can look into this if no one else is working on it.

**Comment by gaearon** [comment]
Sounds good.

**Comment by ricardotx** [comment]
Thanks @pfongkye.

**Comment by gaearon** [comment]
`eslint-plugin-react-hooks@4.1.1` should have the fix.
