### ISSUE TITLE
Add SuspenseList to DevTools Element Names

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#19674]
https://github.com/facebook/react/blob/49af88991c3a3e79e663e495458fad12d3162894/packages/react-devtools-shared/src/utils.js#L491

We have SuspenseList for the tree view but not when printing JSX.

When we fallthrough here we call getDisplayName with a symbol, because we assume that if it's not a string, then it's a function. We should be checking whether it is a function before calling getDisplayName.

Subsequently if we call getDisplayName with a symbol we get the error `invalid value used as weak map key` which messes up things after that. I think that's the actual cause of https://github.com/facebook/react/pull/19364

**Comment by bpernick** [comment]
Sorry for any confusion earlier! I just took a stab at adding SuspenseList and adding a check to only pass functions into getDisplayName. (I've submitted my CLA)
