### ISSUE TITLE
Bug: React 16 no longer supports triggering form input change/input events programmatically

### ISSUE THREAD

**Issue by isocroft** [facebook/react#19678]
React version: 16.x.x

## Steps To Reproduce

Link to code example:

Please, see [this example](https://codesandbox.io/s/zealous-cohen-009ri?file=/src/App.js). Notice that the the console has no logs since the change event can't be programmatically triggered.

## The current behavior

[link](https://codesandbox.io/s/zealous-cohen-009ri?file=/src/App.js)in React 16.x.x

## The expected behavior

[link](https://codepen.io/catthr/pen/PKXzLQ) in React 16.x.x

**Comment by gaearon** [comment]
This is relying on an internal flag which was never a part of the public API (so it was not expected to work). That solution is wrong.

Here's a version that works and doesn't rely on this flag: https://codesandbox.io/s/serene-snyder-l3sj0?file=/src/App.js

**Comment by isocroft** [comment]
Thanks @gaearon

**Comment by isocroft** [comment]
Please @gaearon what about for a `<select/>` tag ? How does one programmatically trigger a chnage event on a `<select />` tag.

**Comment by samie820** [comment]
@isocroft Is this the behavior you're looking for? https://codesandbox.io/s/summer-wave-p634m?file=/src/App.js

**Comment by isocroft** [comment]
Yes, i am.... I did figure it out myself [here](https://codesandbox.io/s/cool-field-s3lpc?file=/src/App.js:336-369) earlier than you replied. But, i will be using your version for my needs. It's much more compact and better written than mine.

**Comment by isocroft** [comment]
Thanks a lot @samie820

**Comment by samie820** [comment]
My pleasure! @isocroft
