### ISSUE TITLE
Bug: React with Typescript does not Support most of the falsey values with using the logical && operator

### ISSUE THREAD

**Issue by jean182** [facebook/react#19687]
With regular js I'm accustomed to use ternary statements to return JSX elements, with typescript I notice this approach won't work since we can only return Element or null, I think the docs are clear that react is smart enough to not render most of the falsey values as stated here: https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored . I would like to have the same functionality in typescript because I think doing `condition ? <Element /> : null` is not as clean as using `condition && <Element />`

React version: 16.13.1

## Steps To Reproduce

1. Open the sandbox
2. Check the App.tsx and look for the line 10 error.

Link to code example:

https://codesandbox.io/s/zealous-snowflake-o3zhz?file=/src/App.tsx

This is the working example with regular js if needed:
https://codesandbox.io/s/trusting-haze-op67z?file=/src/App.js

## The current behavior

<img width="503" alt="Screen Shot 2020-08-24 at 12 12 52 PM" src="https://user-images.githubusercontent.com/7577652/91080668-2b104b80-e603-11ea-82a2-9e0183e512d4.png">

## The expected behavior

Have support for falsey values in typescript when rendering a JSX element

**Comment by gaearon** [comment]
Please file this in the typing repository, since React typings are maintained there.
