### ISSUE TITLE
`useState()` hook without re-rendering if multiple `setState` method called

### ISSUE THREAD

**Issue by malkhazidartsmelidze** [facebook/react#19685]
Hello.
*Sorry if I am writing this in wrong place, but didn't find better place*

When I am using functional component and I have multiple `useState` hook and I change multiple states in one call, is there any method or way to not rerender after each change? ( If I don't use object as state).

**See Example Here:**

```javascript
import React, { useState, useEffect } from 'react';
import defaultUser from 'exported/from/another/location';
impor axios from 'axios';

export default function SimpleComponent(props){
  const [apiResult, setApiResult] = useState({});
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(defaultUser);

  useEffect(() => {
    axios.get('/some/endpoint').then(res => res.data).then((data) => {
      setApiResult(data);
      setLoading(false);
      setUser(data.user);
    });
  }, []);

  return <div>Component Here</div>;
}
```

As you can see I am setting changing state after api call, So component rerenders 3 times.
If I have top level `ContextProvider` My entire app rerenders 3 times which can lead some performance problems

I will be very thankfull to know way to prevent rerendering multiple times.

If there is not way to do this, can someone implement logic like this?

```javascript
React.waitUntillAllStatesChangeAndThenRerenderComponent(() => {
  setStateOne(data);
  setStateTwo(data2);
  setStateThree(data3);
  setStateFour(data4);
  ...
});
```

Thank you all.

**Comment by gaearon** [comment]
This will be the default behavior in Concurrent Mode, but for now, you can do this:

```js
ReactDOM.unstable_batchedUpdates(() => {
  setStateOne(data);
  setStateTwo(data2);
  setStateThree(data3);
  setStateFour(data4);
});
```

It says "unstable" but practically speaking you shouldn't expect breakages for this function.

That said, you can also `useReducer` and put these states into a single object.

**Comment by malkhazidartsmelidze** [comment]
Thank You, Dan. That's exactly what I looking for.
