### ISSUE TITLE
Bug: weird behavior when useState hook sets state for the first time vs subsequent times

### ISSUE THREAD

**Issue by gaurav5430** [facebook/react#19697]
React version:

## Steps To Reproduce

1. Create a simple component with a button which sets state on click.
2. inside onClick, add multiple calls to state setter function using updater function to access previous state
3. The first call seems to be synchronous (although state is still set asynchronously) and others are batched. Any subsequent calls work as expected.

Link to code example:
https://codesandbox.io/s/set-state-calls-are-batched-and-all-executed-before-render-hooks-github-issue-09sin

## The current behavior
logs:
```
1
onclick 0
2
3
renderin
```

## The expected behavior
should log:
```
onclick 0
1
2
3
rendering
```

Not sure if it would lead to any unexpected bugs, because state is still set async, though the function execution is synchronous

https://stackoverflow.com/questions/63586754/react-weird-behavior-when-usestate-hook-sets-state-for-the-first-time-vs-subse

**Comment by jddxf** [comment]
This happens because React will in some cases eagerly compute the next state so as to determine whether to bailout `useState/useReducer` hook. Since `rendering` is logged only one time, React still behaves like batching. This shouldn't cause any issues as long as your state update functions are pure which is normally expected.

**Comment by gaurav5430** [comment]
Ohk
What do you mean by 'bailing out useState/useReducer' ?

**Comment by jddxf** [comment]
In this context, it means don't schedule an update(don't start rendering later) if we're sure the update doesn't change the state.

**Comment by gaurav5430** [comment]
> In this context, it means don't schedule an update(don't start rendering later) if we're sure the update doesn't change the state.

Didn't understand.

- React eagerly executes the state setter, to check what would be the next update

What does it do with this information ? What optimizations are possible due to this? and why only in the very first call to state setter ? I haven't observed this in any subsequent calls

**Comment by eps1lon** [comment]
The docs have a section dedicated to this behavior: https://reactjs.org/docs/faq-state.html#when-is-setstate-asynchronous

If there is anything unclear please open a [new issue in the docs repo](https://github.com/reactjs/reactjs.org/issues/new).

**Comment by jddxf** [comment]
For example, if the state setter is `prevState => prevState`, `rendering` won't be logged. This means React has avoided an unnecessary rerender in this case. However, the condition under which this optimization is done is an implementation detail. It won't break anything as long as the state setters are made pure.

**Comment by gaurav5430** [comment]
@eps1lon I am not sure i get the point here.

I understand that setState is asynchronous, and state updates can be batched, which is what I was expecting here as well.

Do you mean to say that the first time synchronous setter execution is an implementation detail and as consumers we shouldn't rely on its behaviour and just assume that all setState is asynchronous for all practical purposes ?
And that this implementation detail might change in the future.

(Similar to the fact that React executes setState 2 times in class components as a preparation for async mode)

**Comment by gaurav5430** [comment]
@jddxf right, so you are suggesting that even if React would have run it like 

```
1
2
onclose
3
```

as a consumer we shouldn't care about it, because react would guarantee that the end behaviour is consistent (assuming state setters are pure as suggested)

Makes sense in general.

I guess I would still be interested in understanding the implementation detail here and why it is implemented like this for a particular usage (the first call to state setter)
