### ISSUE TITLE
Bug: different handling of onMouseEnter & onMouseLeave based on pointerEvents in Chrome

### ISSUE THREAD

**Issue by layershifter** [facebook/react#19692]
React: 16.13.1
React-DOM: 16.13.1

Chrome 84.0.4147.135.
MS Edge 84.0.522.63.

---

_This looks somehow related to #4251._

## Steps To Reproduce

1. Open a CodeSandbox, https://codesandbox.io/s/laughing-sound-ox5yz
2. Move your mouse from the "point 1" to "point 2". Move your mouse from the "point 2" to "point 1". 

## The current behavior

![image](https://user-images.githubusercontent.com/14183168/91198165-81ad8080-e6fc-11ea-9148-5a3aac8102e4.png)

Notice in your console:
```
#disabled:mouseenter 
```

For the button `#disabled-style` with the same movement:

```
#disabled-style:mouseenter 
#disabled-style:mouseleave 
```

_The difference is that `#disabled-style` has `pointer-events: none`._

## The expected behavior

Both buttons should log the same output.

## It works?

- for the native DOM (https://codesandbox.io/s/recursing-leftpad-y5xbb)
- in IE11, Edge Dev 86, Firefox 79/80

**Comment by dzearing** [comment]
Related: it seems that `onMouseLeave` in React is actually mapping to the native `mouseout` event. Which itself seems to have inconsistencies in browsers.

**Comment by dandclark** [comment]
Suspected root cause is: https://crbug.com/1121675.

Although I don't know why some folks do not repro in Edge Dev 86.  For me the issue repros there as well.

**Comment by layershifter** [comment]
Does not repro anymore in latest Chrome.
