### ISSUE TITLE
Bug: `Context.Consumer` inside `Suspense` does not receive context updates while suspended

### ISSUE THREAD

**Issue by overlookmotel** [facebook/react#19701]
A `<Context.Consumer>` callback inside a suspended `<Suspense>` boundary does not receive updates when context value changes.

This issue was originally found with React Router (https://github.com/ReactTraining/react-router/issues/7137) but can be reproduced with React alone.

React version: 16.13.1 or 17.0.0-rc.0 (and at least *some* earlier versions too)

## Steps To Reproduce

https://codesandbox.io/s/suspense-context-test-case-6jlsq

## The current behavior

In the example above, clicking on the "About" button puts the `<Suspense>` boundary into a suspended state. Clicking "Home" updates the context value, but the `<Context.Consumer>` callback is not called with this updated value. Therefore the page never navigates back to "Home".

Please note that `Received context: home` is not logged after the "Home" button is pressed.

## The expected behavior

The `<Context.Consumer>` callback should be called with value `'home'` when the value of the context is updated.

Please note that the problem does not occur if any of:

1. the Suspense boundary is never suspended (uncomment the first line of `About` function to verify).
2. `useContext()` is used in place of `<Context.Consumer>` (substitute `<SwitchWithUseContext />` for `<Switch />`).
3. the contents of `Switch` function is inlined within the `<Suspense>` rather than in a separate component.

The last of these leads me to suspect that the problem may be related to https://github.com/facebook/react/issues/17356. In the example, `<Context.Consumer>` is within a `Switch` component. But the `<Switch>` element inside `<Suspense>` never changes - so it's effectively memoized. I wonder if this is why it doesn't receive context updates?

**Comment by gaearon** [comment]
Can you turn this into a failing test, like we did for #17356?

**Comment by overlookmotel** [comment]
@gaeron Yup! https://github.com/facebook/react/pull/19702

**Comment by engprodigy** [comment]
@overlookmotel and @gaearon This look stale. Can I take a look at it?

**Comment by overlookmotel** [comment]
@engprodigy I've submitted PR #19702 with a failing test. Personally, I'd very much appreciate your input if you have any ideas for a fix.

**Comment by engprodigy** [comment]
Sure @overlookmotel
