### ISSUE TITLE
Bug: eslint-plugin-react-hooks detects "hook calling" in the static method defined in a simple class

### ISSUE THREAD

**Issue by artischockee** [facebook/react#19700]
Let me just show you the code and put some comments alongside.

In my projects there's a code style that defines some rules applied to "out-of-component functions". In the case of custom hooks I write in this style:
```javascript
import React from "react";

export default class AppHooks {
  static useConsoleReport() {
    React.useEffect(() => {
      console.log(`Some app, version ${process.env.REACT_APP_VERSION}`);
    }, []);
  }
}
```

Which results in this ESLint error:

![image](https://user-images.githubusercontent.com/22125223/91306140-5a2ae680-e7d6-11ea-98dc-9550a727ff9d.png)

At the same moment, if I replace the class with an object:

```javascript
const AppHooks = {
  useConsoleReport() {
    React.useEffect(() => {
      console.log(`Some app, version ${process.env.REACT_APP_VERSION}`);
    }, []);
  }
}
```

I won't get the error.

It's worth noting that I already used this plugin before (but, I guess, some of the previous versions, which I can't remember), and I haven't received this error.

Plugin version: `4.1.0` (`eslint-plugin-react-hooks`)

## Steps To Reproduce

1. Using the "eslint-plugin-react-hooks" package (with no custom configuration, only `plugin:react-hooks/recommended` in `extends` entry of the ESLint config), write an ordinary JS class;
2. Declare **static** method in this class (with any name);
3. Inside of the method write the code using any of default React Hooks (`useEffect`, for example);
4. Encounter an ESLint error:
    ```
    ESLint: React Hook "React.useEffect" cannot be called in a class component. React Hooks must be called in a React function component or a custom React Hook function.(react-hooks/rules-of-hooks)
    ```

Link to code example:

[https://codesandbox.io/s/pensive-allen-drttv](https://codesandbox.io/s/pensive-allen-drttv)

## The current behavior

ESLint (alongside with `eslint-plugin-react-hooks`) complains about the lines of a static method (declared in an ordinary class), where default React Hooks are executed.

## The expected behavior

ESLint (alongside with `eslint-plugin-react-hooks`) does not complain about these usages.

**Comment by eps1lon** [comment]
I guess the actionable thing for the plugin would be to not warn if the class name is lower case e.g. `customHooks` since that couldn't be a class component.

Otherwise it's pretty hard to guess if a class cannot be used as a class component.

Is there anything specific why these hooks need to be static members of a class? A drawback with this approach is that any component that wants to use `CustomHooks.useConsoleReport` has to import all the other hooks. If it were an ordinary function e.g. `export function useConsoleReport` then your bundler could remove all the other (unused) hooks from that module. Something that is not possible for static class members lass I heard.

**Comment by gaearon** [comment]
A linter plugin is opinionated by definition, as it exists to enforce a certain convention. In this case we've decided that calling Hooks from classes is not something we want to consider valid, whether they're static or not. It's too easy to start adding other methods, access fields, and so on, leading to subtly broken rules.

Instead, if you want to write a custom Hook, use regular functions and export them. No need for a static class.
