### ISSUE TITLE
Bug: React.lazy creates unnecessary references to nonexistent CSS chunks

### ISSUE THREAD

**Issue by cjc343** [facebook/react#19705]
React version: ^16.13.1

## Steps To Reproduce

1. Use React.lazy to load a component which uses a dynamic import to load another chunk
2. `yarn build`
3. `cat build/index.html`

Link to code example: https://github.com/cjc343/code-split-test

## The current behavior

When `React.lazy` is used to load an `App.tsx` which dynamically imports two files, `yarn build` produces an `index.html` which includes:

```
<!-- ... -->
function(t,r){for(var n="static/css/"+({}[e]||e)+"."+{3:"050523cc",4:"31d6cfe0",5:"31d6cfe0"}[e]+".chunk.css"
<!-- ... -->
```

## The expected behavior

There are no references output to the nonexistent & unused CSS chunks 4 & 5.

**Comment by vkurchatkin** [comment]
This has nothing to do with React itself. `React.lazy` simply uses a promise that is provided by `import()` (or anything else), it does not create or load chunks.

**Comment by cjc343** [comment]
Ugh - yep, I can repro this with just dynamic imports...
