### ISSUE TITLE
Bug: Potentional XSS issue using React.createElement

### ISSUE THREAD

**Issue by jayem9000** [facebook/react#19718]
Create a `script` element that is Pascal cased (i.e. `Script`) using React.createElement. It doesn't remove the script element but browsers will parse the tag as <script />

Example: 
```
function ScriptPrompt() {
   const badEl = React.createElement('Script', null, [
    'alert("hello");'
  ]);
  return <div>{badEl}</div>
}
```
React version: 16.31.1

## Steps To Reproduce

Link to code example:
Codepen url: https://codepen.io/mrfunkycold/pen/oNxwbYX

Uncomment the ReactDOM line in the code pen. The alert message will fire.

## The current behavior
Alert Message fires. 

## The expected behavior
script tag in any case is removed.

**Comment by gaearon** [comment]
Yeah.

We do warn in console about mistyped casing so at least you should discover it in development if you write it unintentionally. But if you pass user input into a script tag (whether miscased or not) that's already a vulnerability by itself — e.g. with server rendering it _would_ always get executed.

So this is a potential vulnerability but I don't think it is very actionable for React.

**Comment by jayem9000** [comment]
That makes sense. Nope don't think anyone wanted to create a script tag intentionally 😅. Random inputs that occurred through pen testing. 

It would make sense to close this then.
