### ISSUE TITLE
Bug: Memory Leak - React state in portals is not garbage collected after portal is unmounted

### ISSUE THREAD

**Issue by jljorgenson18** [facebook/react#19712]
We are seeing an issue with portals where references to React state are retained after a portal component is unmounted. This can cause nasty memory leaks if React state is holding a lot of memory. The memory does seem to get reclaimed if you render the same portal again but our app is seeing an issue where this memory is never reclaimed and it accumulates over time. I am still attempting to come up with a minimum repro case for the really bad accumulation but the minimum repro case in Codepen seems to at least show that memory is not reclaimed after unmounting.

This also seems to happen only if a function inside of the portal component has access to the bulky state variable, hence the extra handleClick in the example.

This could be related to https://github.com/facebook/react/issues/16138

React version: 16.13.1

## Steps To Reproduce

Using demo
1. Open minimum repro case link that has a portal component that holds a lot of data in state
2. Take a memory snapshot to get a baseline
3. Toggle the portal component so that it renders (which will accumulate about 20mb of React state in memory)
4. Take another memory snapshot. Notice that it is now 20mb higher
5. Toggle the portal component again so that it unmounts.
6. Click on Collect Garbage icon in dev tools to make sure all memory that can be garbage collected has been garbage collected
7. Take another memory snapshot. 

<img width="205" alt="Screen Shot 2020-08-27 at 1 56 04 PM" src="https://user-images.githubusercontent.com/5751354/91483472-631ac700-e86d-11ea-8e5f-5804d57286ae.png">

Link to code example:

 I have created a repro case in Codepen here

* (Editor view) https://codepen.io/jessejorgenson/pen/ExKmQrb?editors=1010

I would go to the debug view to confirm.

EDIT:

Here is a CodeSandbox demo as well since Codepen doesn't do a Debug view unless you are signed in

https://codesandbox.io/s/great-babbage-mvsxl

## The current behavior
The memory is not cleared and it is roughly equivalent to the memory utilization when the Portal component was mounted

## The expected behavior
The final memory snapshot has returned to the baseline

**Comment by proamg9** [comment]
Correct me if i'm wrong, but isn't this JS engine related , not react cleanup?

**Comment by jljorgenson18** [comment]
I'm not sure how it would be. The only difference between this issue and another component with a lot of state is the fact that it's a portal. You can also tell inside of the memory section of devtools that references to react memoized state stick around. If it was just a closure with a lot of state, then it would be garbage collected eventually if the references were cleared. React is keeping those references somewhere.

**Comment by proamg9** [comment]
I would think it's related to the event listener.  Also portals are not only one causing this take a t look this:

https://codesandbox.io/s/tender-dewdney-l5zcs?file=/src/App.js

**Comment by jljorgenson18** [comment]
I'm not seeing any issues in that example.


<img width="700" alt="Screen Shot 2020-09-01 at 10 34 36 AM" src="https://user-images.githubusercontent.com/5751354/91873574-c8d8cb80-ec3e-11ea-8a92-7322b7d626e4.png">

**Comment by jljorgenson18** [comment]
In the initial example, I tried it with a portal and without a portal. There were no issues without a portal for whatever reason. If you just swap on the createPortal reference with the underlying component, I believe it should have the memory be garbage collected.

**Comment by proamg9** [comment]
Run the one above a few times and you will see Js heap size increase and never decrease when uninstalled.

As you can see with both examples, it is right to say in both you are still pushing to array after un-mount
use effect does cleanup after but this action is still keeping the reference alive as so the JS GC algorithm is not releasing memory.

**Comment by jljorgenson18** [comment]
I did not see the heap increase or decrease in that example.

**Comment by jljorgenson18** [comment]
In the original example, the component code is not doing anything after unmount. There may be something happening under the hood but that is fairly vanilla component. It seems like one of the underlying problems could be that listeners aren't be cleaned up properly.

**Comment by jljorgenson18** [comment]
After researching a bit more and reading some of the comments in https://github.com/facebook/react/issues/18790, I can see that the specific example I posted is due to React retaining a reference to the previous render state. If you tweak the example to do a few more update between the render that generates a lot of state, you can see the memory is retained. As @gaearon mentioned, this is expected behavior for now.

I think the original issue I was trying to dig into is just another case of https://github.com/facebook/react/issues/18790 since we are doing similar things with Redux and PureComponents. I'll create a different issue or contribute to the other memory leak issue if I come up with any new information.

**Comment by proamg9** [comment]
Thanks for that and yes, it's what I hinted at originally, @gaearon says it's expected behaviour, which probably means react is performing a cleanup as it should(under the hood - use-effect does this) but ultimately the JS GC controls proper memory release.
