### ISSUE TITLE
how to set "one time import custom component in one file and usage in every pages & component without import in particular file" ?

### ISSUE THREAD

**Issue by Jatin-Pixer** [facebook/react#19717]
I don't know it is possible or not but i need solution. If you have any suggestion then send us.

Requirement: 
1. I made multiple component such as button, heading and etc.
2. Require all component is imported and used in pages.

This is simple and right way but i need like set all require component in one file (Ex. **App.js**) and I can use these all component in entire project without import modules in particular file. Is this possible ?

**Comment by eps1lon** [comment]
For usage questions check out [Where To Get Support](https://reactjs.org/community/support.html).
