### ISSUE TITLE
RFC(Suggestion): Allow developer(or detect automatically during jsx conversion ) to mark sections of jsx as static to avoid wasting any time on them when rerendering the component

### ISSUE THREAD

**Issue by sktguha** [facebook/react#19725]
1) I just had an idea, what if a developer can mark sections of their jsx as static , so react never wastes times on comparing the new virtual dom tree against the existing dom tree, when rerendering. (I understand you can already do this with React.memo/PureComponent. With a seperate attribute it is easier to write .Also automated tools(see no 2) as eslint can add that attribute easily.  )

2) could it be possible for react to **detect automatically** if no {} statements are there inside a node or it’s children hence mark it as static automatically.(I understand jsx is converted to Create element calls so babel can figure that out and attach the staticContent attribute on the node ) . If required, developer can disable this optimisation via a special flag on the component maybe,if they are doing something weird that somehow will be broken by this optimisation

For ex -

```
function MyComponent(flag){
return (
<>
  <div staticContent=true staticContentId=someUniqueId>
   Some very large dom
  </div>{
    flag && (<div>dynamic context </div>)
   }
</>
)
```
Currently react will traverse the entire "Some very large dom" div for nothing when doing a comparison of the new virtual dom tree against the existing dom tree, when rerendering.  As we have marked the first div as static so now react will never waste time comparing the div (if it sees staticContent attribute on both new and existing virtual dom nodes, it returns "same" instead of traversing down them). In fact it might never touch that div as long as the component exists (if a static content node exists on the root itself). I think staticContentId is required to make sure it is indeed the same node and not some other static content node that has landed up in the same hierarchy/ xpath etc 
Coupled with a smart eslint which can suggest and autofix sections of jsx to be static, then it could definitely improve rendering times.

**Comment by kachkaev** [comment]
I guess the optimisation you are describing is already handled by [React.memo](https://reactjs.org/docs/react-api.html#reactmemo).

```tsx
const MyHeavyStaticDiv = React.memo(() => {
  return <div>Some very large dom</div>;
});

function MyComponent(flag) {
  return (
    <>
      <MyHeavyStaticDiv />
      {flag && <div>dynamic context </div>}
    </>
  );
}
```

**Comment by sktguha** [comment]
Yes understood, but with a seperate attribute it is easier to write

**Comment by sktguha** [comment]
@kachkaev thanks for replying. I have done an edit. have added a second part regd detecting automatically static section of jsx . Please check and respond if you wish to on that

**Comment by sktguha** [comment]
can anyone check and reply on this if possible ?

**Comment by eps1lon** [comment]
This is exactly what [`@babel/plugin-transform-react-constant-elements
`](https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements) is  doing.

If that didn't cover all the scenarios you had in mind then please draft an RFC, include the difference to existing solutions and post it over at	https://github.com/reactjs/rfcs.
