### ISSUE TITLE
Bug: useEffect doesn't run if useState is used after useEffect

### ISSUE THREAD

**Issue by aditya81070** [facebook/react#19729]
React version: 16.12.0

## Steps To Reproduce

1. Create a simple React component and add `useEffect` and use a state say `state` into its dependency array.
2. Now create a new state, `const [state, setState] = useState('')`
3. Use this `state` into an input and change the input.
4. The effect is not run again except first render. 

Link to code example: [Reproducible Code on CodeSandBox](https://codesandbox.io/s/magical-tree-mcsjb?file=/src/App.js)

## The current behavior
If I use the `useEffect` hook before `useState` hook and add `state` generated by `useState` into dependency array of `useEffect` and change state, effect doesn't run. I thought that may be `state` is `undefined` so it never change but I console `typeof state` and it is `string`.  (Please run the demo for better understanding).

## The expected behavior
There may be multiple expected behaviour, I am not sure which is applicable here:
1. If I am using `state` in dependency array or even in useEffect before its declaration then there should be linting error.
2. As per, I know the order of hooks matter. I don't know if `useState` hook is called internally before `useEffect`. If it is called before `useEffect` then `useEffect` should re-run if my state changes.

**Comment by gaearon** [comment]
Yeah you shouldn’t be able to access a variable before its definition. It is supposed to error. I think CodeSandbox is wrong here (likely because it uses a loose Babel mode). Please report this to CodeSandbox.

**Comment by aditya81070** [comment]
😭  Now the codesandbox is itself giving linting error that I am using `state` before defining it. Don't know, why it was not giving error when I created this demo. Also may be linter didn't work in my vscode.

**Comment by eps1lon** [comment]
> I think CodeSandbox is wrong here (likely because it uses a loose Babel mode). 

Sorry for being well-aktually-guy here but this is default behavior of babel: https://babeljs.io/docs/en/babel-plugin-transform-block-scoping#tdz

Transpiling with `spec` mode (or disabling `loose` mode) in preset-env would not throw an error. You'd have to explicitly enable `tdz` in the underlying plugin.

Also mind the warning about enabling it: 

>If you need these errors you can tell Babel to try and find them by setting "tdz": true for this plugin.  However, the current implementation might not get all edge cases right and its best to just avoid code like this in the first place.
