### ISSUE TITLE
Bug: I can't get react-refresh to work unless I enable React Development Tools

### ISSUE THREAD

**Issue by leidegre** [facebook/react#19727]
React version: 16.13.1

## Steps To Reproduce

1. Use `<script defer />` to fetch `react` and `react-dom` from CDN
2. Wait for `DOMContentLoaded` event
3. Call `injectIntoGlobalHook` from `react-refresh/runtime` before first `ReactDOM.render`
4. Touch some module which has hot reloading enabled
5. Watch in despair as nothing happens 😢 
6. Enable React Development Tools
7. Touch some module which has hot reloading enabled (again)
8. Watch in awe as things update in real-time 🥇 

Originally I just posed this as a question to @gaearon whether this behavior was by design, i.e. that the `react-refresh` code actually needed the React Development Tools but I'm presuming no?

I stepped through the code and noticed that when `performReactRefresh` ran, the collections `helpersByRendererID`, `failedRootsSnapshot` and `mountedRootsSnapshot` we're all empty. As soon as I enabled React Development Tools things started working. So what did I miss?

I can try to repo this if necessary but I'm using my own bundler that is using some proprietary stuff so I would like to use that as a last resort. There's gotta be some basic stuff that I haven't considered...

**Comment by gaearon** [comment]
>Call injectIntoGlobalHook from react-refresh/runtime before first ReactDOM.render

This is the problem — it needs to be called before ReactDOM *executes*, not before the first render.

**Comment by leidegre** [comment]
OK.

But wasn't https://github.com/facebook/react/pull/17633 supposed to fix this? I'm confused.

As an experiment I was thinking about putting [this code](https://github.com/facebook/react/blob/4c6470cb3b821f3664955290cd4c4c7ac0de733a/packages/react-refresh/src/ReactFreshRuntime.js#L431-L456) between the loading of React and ReactDOM. In theory would the be enough?

Other than my question. I understand what to do and why it works the way it does. So we can close this. But I'd really appreciate a clarification on my questions above. Thanks!

Also. This stuff rocks. I'm super glad you did this. It's works really well and is really improving the developer happiness all around!

**Comment by gaearon** [comment]
Ah yeah you're right that fix only works for React DevTools users.

>As an experiment I was thinking about putting this code between the loading of React and ReactDOM. In theory, could that be enough?

Yeah.

**Comment by leidegre** [comment]
OK. Well, maybe I'll get around playing around with various work arounds in the future but as things stand right now, simply having DevTools enabled makes everything work. Simple enough. Again, thanks for this. Really cool stuff!

**Comment by UNDERCOVERj** [comment]
how can I fix this question，when not open React DevTools  ，react-refresh mountedRootsSnapshot is empty。so react refresh is not working
