### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by kumarvadivel** [facebook/react#19734]
i devloped a  react app fully with functional components in it.issue is when i generate a component using backend requests the component gets rendered in the DOM but actually not visible in the view it hides the generated components these issues happen when the app is on the production build when it is in the devlopment it works fine please resolve this issue as soon as possible

**Comment by eps1lon** [comment]
Thanks for taking the time to describe your issue. It seems like it is specific to your build setup. This issue tracker is for bug reports related to React itself. Check out https://reactjs.org/community/support.html to find support for your specific issue.
