### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by junicodes** [facebook/react#19736]
Please fix the side bar toggle on React Documentation it does not work on my non-touch screen PC....i think it should be scroll-able, it works on my touch screen PC 
![reactbug](https://user-images.githubusercontent.com/38891189/91824890-61694e80-ec33-11ea-9c5b-17a21679d0a8.png)

**Comment by proamg9** [comment]
What screen size is it?  give us more information please, device, resolution, size, os etc....

**Comment by eps1lon** [comment]
Duplicate of https://github.com/reactjs/reactjs.org/issues/3171
