### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by kumarvadivel** [facebook/react#19735]
react router dom useHistory issue history.push() for link has giving some issues

my current link is  /game/1

my new link is /game/2

cant able to load new contents on new pages when the link is same and dynamic on history.push()

**Comment by eps1lon** [comment]
Looks like your issue is with [react-router](https://reactrouter.com/) not React itself. Please mind my last response: 

> This issue tracker is for bug reports related to React itself. Check out https://reactjs.org/community/support.html to find support for your specific issue.

-- https://github.com/facebook/react/issues/19734#issuecomment-684461167
