### ISSUE TITLE
Bug: Data loss occurs when reference type data is passed to a child component

### ISSUE THREAD

**Issue by jockey100332** [facebook/react#19744]
In the parent component, I passed the obtained data to the child component with props, and after the child made useState changes, the passed data was lost.

data 
```
initVals: {
   questionsGroups: [
       questionsItems: [{
         options: []
        }]
  ]
}
```

This is a deeply nested data structure. After setState, the questionsItems array was lost during the next render

React version: 16.13.1

**Comment by eps1lon** [comment]
Please include a [codesandbox](http://react.new/) that reproduces the issue. Otherwise we're unable to identify the issue.

**Comment by jockey100332** [comment]
Thank you for your reply. In the process of codesandBox replication, I found that there was a problem with my encoding, and I inadvertently modified the data of the reference type.

**Comment by jockey100332** [comment]
> Please include a [codesandbox](http://react.new/) that reproduces the issue. Otherwise we're unable to identify the issue.

Thank you for your reply. In the process of codesandBox replication, I found that there was a problem with my encoding, and I inadvertently modified the data of the reference type.

**Comment by bvaughn** [comment]
Closing this issue then, since it sounds like it was reported in error.

**Comment by hosseinmd** [comment]
@jockey100332 use Immutable object by some tools like Immutable.js or use ReadOnly if your app is type based, to reduce this type of issue.
