### ISSUE TITLE
Bug: Drag and drop event listeners (specifically onDragOver) are not added on Linux/Chromium.

### ISSUE THREAD

**Issue by tonyhb** [facebook/react#19746]
React version: 16.3.1

## Steps To Reproduce

On Linux (i'm using wayland/sway), set up any react app and add onDrag, onDragOver, onDrop listeners.  onDragOver does not register on Chromium and dragging/dropping fails.

Some repros:

https://codepen.io/frcodecamp/pen/OEovqx
https://codepen.io/adamaoc/pen/GoKZKE

## The current behavior

onDragOver does not fire.  Dropping is impossible.

A video of actual behaviour:

https://bugs.chromium.org/p/chromium/issues/attachment?aid=464642&signed_aid=w6-h6srT4D2vyw_dnF6YHg==&inline=1

## The expected behavior

onDragOver fires, meaning `preventDefault()` can be called and dropping can occur.

A video of expected behaviour:

https://bugs.chromium.org/p/chromium/issues/attachment?aid=464643&signed_aid=Qi_9gJYXPnZYssHrIFkLJQ==&inline=1

Proactively filed a chromium bug here, also: https://bugs.chromium.org/p/chromium/issues/detail?id=1124153

Note that onDragOver event listeners only fail to register when the element is added via React/dynamically.

**Comment by tonyhb** [comment]
Fairly certain that this is a chromium bug on Linux so I'm totally okay with having this closed.  Having this on GitHub helps mainly for visibility, just in case other people run into this with React.

**Comment by eps1lon** [comment]
> Fairly certain that this is a chromium bug on Linux so I'm totally okay with having this closed.

Please ping me if it turns out to be a bug in React. The chromium folks might want a repro without React though.
