### ISSUE TITLE
Bug: Types incorrectly identified as missing dependencies for `eslint-plugin-react-hooks@4.1.0` with `@typescript-eslint/parser@4.0.1`

### ISSUE THREAD

**Issue by ifiokjr** [facebook/react#19742]
React version: `16.13.1` (although this is related to the eslint plugin).

## Steps To Reproduce

1. Install `eslint-plugin-react-hooks@4.1.0` with `@typescript-eslint/parser@4.0.1` in a TypeScript project.
2. Within your hook define a type, or cast a value to a certain type`
	```tsx
	const actions = useMemo(
    	() => bindActionCreators(MultishiftActions, dispatch) as Partial<Item>,
    	[dispatch],
  	);
	```
3. `eslint-plugin-react-hooks` responds with this error `React Hook useMemo has a missing dependency: Item. Either include it or remove the dependency array.`

Link to code example: remirror/remirror/pull/619

- Checkout the remirror codebase 
	```bash
	git clone https://github.com/remirror/remirror
	git checkout typedoc
	```
- Install the dependencies with `pnpm`. To setup `pnpm ` run `npm i -g pnpm`. 
- Run the command `pnpm run lint:es` to lint the codebase.

## The current behavior

Types are identified as missing dependencies within a hook and [CI fails](https://github.com/remirror/remirror/pull/619/checks?check_run_id=1058210430).

## The expected behavior

Types shouldn't be identified as missing dependencies.

**Comment by NeoRaider** [comment]
This issue was introduced with @typescript-eslint/parser 4.0.0.

**Comment by ifiokjr** [comment]
Thanks for the information. I'll update the details. Should I move this to the `typescript-eslint` repo?

**Comment by NeoRaider** [comment]
> Thanks for the information. I'll update the details. Should I move this to the `typescript-eslint` repo?

No, I already asked there, it will need to be fixed up in the react plugin. I have a fix locally, will send a PR in a moment.

**Comment by gaearon** [comment]
`eslint-plugin-react-hooks@4.1.1` should have the fix.

**Comment by alecmolloy** [comment]
thanks!

**Comment by dgattey** [comment]
I'm on `eslint-plugin-react-hooks@4.4.0` and I'm still seeing this when using a generic value inside a callback. Why might that be? I'm getting `React Hook useCallback has a missing dependency: 'Value'. Either include it or remove the dependency array  react-hooks/exhaustive-deps` with `const data: Value = JSON.parse(decompressedValue);` as the line that causes the error.
