### ISSUE TITLE
Bug: react-hooks/exhaustive-deps includes too much logic?

### ISSUE THREAD

**Issue by dartess** [facebook/react#19749]
Judging by the name the rule should check `deps` of some hooks. Instead, it checks for other things as well, such as the asynchronous effects. This violates the single responsibility principle and reduces the flexibility of the rule.

Example:

I am writing a new hook that must accept an asynchronous function, but must have deps.

If I just write it, I won't get linter errors for missing dependencies:

```
    useEffectAsync(
        async (getIsIgnore) => {
            console.log(roleCode)
        },
        [], // missing deps: roleCode
    );
```

Now I can set up a rule, which is very cool:

```
        'react-hooks/exhaustive-deps': ['warn', {
            'additionalHooks': '(useEffectAsync|useEffectOnUpdate)'
        }],
```

But if I do that, I get a warning from the linter about the async function.

```
    useEffectAsync(
        async (getIsIgnore) => { // warn about async func, what is useless here
            console.log(roleCode)
        },
        [roleCode], // ok, can be fixed automatically
    );
```

I think the rule for checking the correctness of the effects functions should be separate.

**Comment by dartess** [comment]
Any opinions for or against

**Comment by ThomasdenH** [comment]
This may solve #21381.

**Comment by dartess** [comment]
bump

how polite it is that old issues are marked first and not closed automatically immediately <3
