### ISSUE TITLE
Bug: React DevTools throws ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by leidegre** [facebook/react#19756]
React version: 16.3.1

## Steps To Reproduce

1. In the Chrome script debugger, enable "Pause on caught exceptions"
2. Open React DevTools in a app that doesn't use babel or webpack
3. ReferenceError: regeneratorRuntime is not defined

## The current behavior

```
ReferenceError: regeneratorRuntime is not defined
```

The source of this error seems to be something like this:

```
try {
  // add if support for Symbol.iterator is present
  __webpack_require__(23)(Yallist);
} catch (er) {}
```

From `chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js`

## The expected behavior

No errors are thrown. It's really annoying when React or it's tooling is throwing exceptions because it makes me having to step through a lot of noise when I'm debugging my own stuff. If this could be avoided that would be much appreciated.

---

I get that his might not be fixable and if so, feel free to close but please keep it in mind. Please don't throw exceptions if you absolutely musn't.

**Comment by eps1lon** [comment]
> No errors are thrown.

The code you post catches this error. Are you saying that the code should not have caught exceptions?

I don't find this reasonable to expect. React has a couple of instances where it attempts "something" and catches a potential error. `react` and `react-dom` catch "expected errors" in some places as well.

You're essentially demanding that nobody should ever catch errors since that hinders your debug workflow.

**Comment by leidegre** [comment]
The `regeneratorRuntime` should not be `undefined`. I think is a bundling issue.

**Comment by eps1lon** [comment]
> The `regeneratorRuntime` should not be `undefined`. I think is a bundling issue.

Then I don't understand why that block would be wrapped in a try-catch

**Comment by leidegre** [comment]
Okay, so, I don't know what target the React Dev Tools have in mind for browser compatibility but the `regeneratorRuntime` is something Bable inject to transpile async/await. It can be disabled if you're okay with supporting more modern browsers primarily. For the React Dev Tools that is.

**Comment by kambleaa007** [comment]
we can suppress this error, can we?

**Comment by bvaughn** [comment]
DevTools backend uses the `lru-cache` package which uses `yallist` which uses a generator function.

Contributions would be welcome if you'd like to change the Babel config for the extension.

**Comment by kambleaa007** [comment]
I like to give a try, Fingers crossed
​​​​

**Comment by kambleaa007** [comment]
`react-devtools-extension` has `webpack.backend.js` configured   
`output:` {
    path: __dirname + '/build',
    filename: 'react_devtools_backend.js',
  },`

**Comment by kambleaa007** [comment]
for me its not coming in even catch block

`try {
  // add if support for Symbol.iterator is present
  __webpack_require__(23)(Yallist);
} catch (er) {}`

**Comment by leidegre** [comment]
> for me its not coming in even catch block
> 
> `try { // add if support for Symbol.iterator is present __webpack_require__(23)(Yallist); } catch (er) {}`

Note that you have to enable "Pause on caught exceptions" in the script debugger.

**Comment by leidegre** [comment]
> DevTools backend uses the `lru-cache` package which uses `yallist` which uses a generator function.
> 
> Contributions would be welcome if you'd like to change the Babel config for the extension (and ensure that things still work).

What's the min spec? Is okay to assume a modern browser (with built in support for async/await)?

**Comment by kambleaa007** [comment]
well, im getting it now,
![image](https://user-images.githubusercontent.com/19818679/92232550-5715b180-eecc-11ea-88f0-6a7344569cfd.png)

**Comment by bvaughn** [comment]
> What's the min spec? Is okay to assume a modern browser (with built in support for async/await)?

Yes, async/await and generators are supported by all browsers this extension targets (and all semi recent versions of Node that the standalone version targets).

**Comment by leidegre** [comment]
After some digging around it looks to me that the min spec is actually given by the manifest files in `packages\react-devtools-extensions/chrome|edge|firefox/manifest.json` which is currently sitting at 49 for Chrome. I think async was added somewhere around [55](https://caniuse.com/#search=async)

But... there are additional targets to consider.

\[packages\react-devtools-shared\babel.config.js\]:

```js
  if (isTest) {
    targets.node = 'current';
  } else {
    targets.chrome = minChromeVersion.toString();
    targets.firefox = minFirefoxVersion.toString();

    // This targets RN/Hermes.
    targets.ie = '11';
  }
```

If the lowest common denominator is going to be IE11 due to Hermes then I don't think messing with the targets will help.

It is possible to do thing like `"exclude": ["transform-regenerator"]`.

So, this:

```js
return {
    plugins,
    presets: [
      ['@babel/preset-env', {targets}],
      '@babel/preset-react',
      '@babel/preset-flow',
    ],
  };
```

Changes into

```js
return {
    plugins,
    presets: [
      ['@babel/preset-env', {targets, exclude: ['transform-regenerator']}],
      '@babel/preset-react',
      '@babel/preset-flow',
    ],
  };
```

But now I'm uncertain what's going to happen if this code really needs to include a regenerator runtime for Hermes support.

**Comment by bvaughn** [comment]
> After some digging around it looks to me that the min spec is actually given by the manifest files in `packages\react-devtools-extensions/chrome|edge|firefox/manifest.json` which is currently sitting at 49 for Chrome.

True, although I think this is because we *could* target that min spec, not because we actually need to (or even care to).

The question about Hermes is a good one though!

We could fork the Babel configs so that the inline and the browser extension packages inject the exclude.

**Comment by erictheswift** [comment]
React Developer Tools 4.10.1 (12/4/2020) — still reproducible

Could it be possible to do conditional check on babel internals to avoid try/catch, e.g.
```
if (regeneratorRuntime && Symbol.iterator) {
  require('Yallist');
}
```
?
