### ISSUE TITLE
Bug: app slow when using particles.js

### ISSUE THREAD

**Issue by hari-bhandari** [facebook/react#19768]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by eps1lon** [comment]
Seems like you forgot you fill out the issue template. Without that information we won't be able to identify the issue and have to close it. Please include the React version, steps to reproduce, current and expected behavior. Ideally you'd include a [codesandbox](https://react.new).

**Comment by bvaughn** [comment]
Going to close this for now. We can re-open if repro steps and other info is provided.
