### ISSUE TITLE
Enable source maps for DevTools production builds

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#19769]
Source maps are currently disabled for DevTools production builds:

https://github.com/facebook/react/blob/38a512acade57578738e2c5ebbb0709cd56a9bbd/packages/react-devtools-core/webpack.backend.js#L22

https://github.com/facebook/react/blob/38a512acade57578738e2c5ebbb0709cd56a9bbd/packages/react-devtools-shell/webpack.config.js#L28

https://github.com/facebook/react/blob/38a512acade57578738e2c5ebbb0709cd56a9bbd/packages/react-devtools-inline/webpack.config.js#L20

https://github.com/facebook/react/blob/38a512acade57578738e2c5ebbb0709cd56a9bbd/packages/react-devtools-core/webpack.standalone.js#L22

https://github.com/facebook/react/blob/38a512acade57578738e2c5ebbb0709cd56a9bbd/packages/react-devtools-extensions/webpack.config.js#L21

https://github.com/facebook/react/blob/38a512acade57578738e2c5ebbb0709cd56a9bbd/packages/react-devtools-extensions/webpack.backend.js#L21

I don't remember if there's a good reason for this, but it makes debugging production builds of DevTools difficult (on the occasion that it needs to be done).

Let's enable cheap source maps for DEV mode (like most configs already do) and full source maps for the production builds. Might be worth comparing before and after build times and bundle sizes for the extensions. We may also need to explicitly add the source maps to the extension manifests `web_accessible_resources`.

**Comment by jpribyl** [comment]
I can take a look at this one!

**Comment by bvaughn** [comment]
This issue is all yours @jpribyl! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!
