### ISSUE TITLE
Bug: React devtools "highlight updates when components render" and profiler output not matching when using memo

### ISSUE THREAD

**Issue by saranshkataria** [facebook/react#19778]
React version: N/A

## Steps To Reproduce

1. Create a dynamic list component
2. Use memo to memoize the list, dynamically change one of the properties of an item on the list
3. Open devtools and check the "highlight updates when components render" and "record why component rendered while profiling" option
4. Start profiling and recording
5. All components of the list are shown as being re-rendered
6. Open React profiler and see the re-rendered items
7. React profiler shows that only the selected item on the list was re-rendered

![2020-09-05 13-23-43](https://user-images.githubusercontent.com/1450819/92313029-9222ee00-ef7b-11ea-97c2-6ee0212b2d1d.gif)

Link to code example: https://codesandbox.io/s/practical-lovelace-ch4mw

## The current behavior
React Devtools "highlight updates when components render" highlights all components. When using the profiler to do the same recording, it shows that only one component was re-rendering.

(My guess is that highlight updates is hooking into the function call itself and the profiler is looking into DOM changes and showing only those that actually re-render.)

## The expected behavior
React Devtools "highlight updates when components render" should only show the components that were re-rendered

**Comment by saranshkataria** [comment]
bump

**Comment by Karolis92** [comment]
Maybe I don't understand how "highlight updates when components render" should work. It always highlights all components, doesn't matter they did render or not. I would think it should highlight only the ones that did render

**Comment by thesimpledev** [comment]
I'm seeing this as well. Dev tools profile shows 'Did not render.' yet it's painting a box around it as if it did.

**Comment by AlanCutFlim** [comment]
> Maybe I don't understand how "highlight updates when components render" should work. It always highlights all components, doesn't matter they did render or not. I would think it should highlight only the ones that did render

Even i force the child component not rerender throught `shouldComponentUpdate`, it still highlight that child component due to its parents rerendered.

**Comment by yhor1e** [comment]
My situation is the same as this issue.

I think it's occurred by [Fragments](https://reactjs.org/docs/fragments.html).

I changed

> Link to code example: https://codesandbox.io/s/practical-lovelace-ch4mw

like below and "highlight updates when components render" seems to work fine.

https://codesandbox.io/s/xenodochial-tharp-eq669

L56-71
```diff
  return (
-    <>
+    <div>
      <span>Images</span>
      {images.map((image, index) => {
        return (
          <ImageContainer
            key={image.title}
            image={image.image}
            title={image.title}
            handleSelect={handleSelect}
            selected={image.selected}
            index={index}
          />
        );
      })}
-   </>
+   </div>
```

**Comment by farcaller** [comment]
Here's a trivial example to demonstrate the issue ([codesandbox](https://codesandbox.io/s/loving-roentgen-zcwet?file=/src/App.js)):

```js
import { memo, useState } from "react";

const BoringBtn = () => {
  const [click, setClicks] = useState(0);

  const act = () => {
    setClicks((cl) => cl + 1);
  };

  return (
    <div>
      <button onClick={act}>click me {click}</button>
    </div>
  );
};

const MemoBtn = memo(BoringBtn);

export default function App() {
  return (
    <div className="App">
      <div>
        This redraws: <BoringBtn />
      </div>
      <div>
        This doesn't: <MemoBtn />
      </div>
    </div>
  );
}
```

**Comment by dpyzo0o** [comment]
I've encountered a similar issue with mobx. The highlight does not work for components wrapped by mobx observer. According to the explanation from the author of mobx [here](https://github.com/mobxjs/mobx-react-lite/issues/255), it might relate to React.memo as well.

**Comment by Karolis92** [comment]
I use to have this issue and now I have opposite... Memoized compoents are not market even tho they are re-rendered, because props changed.

**Comment by AbhayVAshokan** [comment]
> My situation is the same as this issue.
> 
> I think it's occurred by [Fragments](https://reactjs.org/docs/fragments.html).
> 
> I changed
> 
> > Link to code example: https://codesandbox.io/s/practical-lovelace-ch4mw
> 
> like below and "highlight updates when components render" seems to work fine.
> 
> https://codesandbox.io/s/xenodochial-tharp-eq669
> 
> L56-71
> 
> ```diff
>   return (
> -    <>
> +    <div>
>       <span>Images</span>
>       {images.map((image, index) => {
>         return (
>           <ImageContainer
>             key={image.title}
>             image={image.image}
>             title={image.title}
>             handleSelect={handleSelect}
>             selected={image.selected}
>             index={index}
>           />
>         );
>       })}
> -   </>
> +   </div>
> ```

This solved my issue. I think under the hood `React.Fragment` makes the child component re-render along with its sibling's rerender. Replacing it with a `div` makes it act as an individual component (expected behavior). Perhaps this should be filed as an issue.

**Comment by refaelo** [comment]
bump

**Comment by meivinay** [comment]
bump

**Comment by vavra7** [comment]
bump

**Comment by rogeliotg** [comment]
mee to

**Comment by hrvojegolcic** [comment]
me too

**Comment by bryan-davis** [comment]
I still experience this bug with 4.27.1.

**Comment by gdfreitas** [comment]
Still on `4.28.0-035a41c4e`

**Comment by TomasHubelbauer** [comment]
This issue is still present as of the current version of React Developer Tools at the time of writing.

**Comment by DemaPy** [comment]
bump
