### ISSUE TITLE
Bug: React DevTools not showing symbols used in state

### ISSUE THREAD

**Issue by bhumijgupta** [facebook/react#19784]
React version: 16.13.1

## Steps To Reproduce

1. Create a state with a symbol as a key
2. Open React DevTools to view the state

Link to code example: https://codesandbox.io/s/awesome-wu-w08px?file=/src/App.js

## The current behavior
Cannot view the symbol in the state

## The expected behavior
Symbols should be visible in the state from DevTools

**Comment by omarsy** [comment]
Can I push a PR ?

**Comment by eps1lon** [comment]
> Can I push a PR ?

Sure, go ahead.

**Comment by bvaughn** [comment]
Fixed by #19786
