### ISSUE TITLE
Bug: react-hooks/rules-of-hooks doesn't work inside of Mobx observer

### ISSUE THREAD

**Issue by eemorozov** [facebook/react#19785]
React version: 16.13.1
Eslint version: 7.8.1
Eslint-plugin-react-hooks: 4.1.0

## Steps To Reproduce

1. Wrap component in Mobx observer. 
2. Make useEffect conditional

Link to code example: https://codesandbox.io/s/dry-monad-q8rmd?file=/src/App.js

## The current behavior

There is no error - React Hook "useEffect" is called conditionally

## The expected behavior

react-hooks/rules-of-hooks rule should throw error

**Comment by gaearon** [comment]
This is expected, there's no way for the linter to know that `() =>` inside is a component. Similarly, this is why you won't see its name in stack traces or DevTools, leading to a poor debugging experience. Please either make your component a named function or let it be named implicitly by doing the wrapper somewhere after the declaration.

**Comment by eemorozov** [comment]
Thanks for the clarification

**Comment by SrBrahma** [comment]
> This is expected, there's no way for the linter to know that `() =>` inside is a component. Similarly, this is why you won't see its name in stack traces or DevTools, leading to a poor debugging experience. Please either make your component a named function or let it be named implicitly by doing the wrapper somewhere after the declaration.

Isn't it possible for the linter to check the return type, if using TS? The observer function returns a FC... Also, why the exhaustive-callbacks rules works when inside the anonymous function component (and inside the useEffect/etc) but not the rules-of-hooks?

It took me months to realize the rules-of-hooks wasn't working in observer functions
