### ISSUE TITLE
Export a standardized tagName-equivalent for overloaded ReactDOMComponents

### ISSUE THREAD

**Issue by syranide** [facebook/react#1978]
If you're trying to polyfill browser elements currently (such as `picture`) there is no consistent and guaranteed safe way to detect the `tagName` of overloaded ReactDOMComponents.

1. `React.DOM.img().type === React.DOM.img.type` is one way, but it is not safe against the use of polyfilled `img` implementations.

2. `React.DOM.img().type.displayName === React.DOM.img.type.displayName` is another way, but it is very dirty and expecting polyfilled components to hide behind the display name of polyfilled React DOM element is not nice.

This is actually an issue I have right now, I'm implementing polyfilled `img`- and `picture`-elements. The `picture`-element should have an `img`-element child, but it should be safe to use `React.DOM.img` or my companion polyfilled `img`... or any other overloaded implementation. But there's no safe/standardized way to detect that currently.

**Comment by spicyj** [comment]
If we want to support this, it would probably be by having React be configurable in some way, sort of like #1648.
