### ISSUE TITLE
Bug: onDragStart make fired onDragEnter onDragLeave with bad closure !

### ISSUE THREAD

**Issue by djmisterjon** [facebook/react#19782]
React version:i tray last and beta
here guys is this a bug ? when `onDragStart` fired, it also fired random `onDragEnter` AND `onDragLeave` scope.
Try drag a elements and look consoleLog the CLOSURE  in the demo plz
Link to code example:
https://codesandbox.io/s/admiring-paper-6mlwe?file=/src/App.js

## The current behavior
onDragEnter should fired once when onDragStart but with the correct `CLOSURE`

**Comment by eps1lon** [comment]
`onDragEnter` and `onDragLeave` are dispatched at the DOM element that your drag motion is entering or leaving. Therefore you log `o` of the corresponding listitem.

> The target object is the immediate user selection (the element directly indicated by the user as the drop target), or the <body> element.

-- https://developer.mozilla.org/en-US/docs/Web/API/Document/dragenter_event

`onDragEnd` is dispatched at the DOM element that the corresponding `onDagStart` was dispatched:

> At the end of a drag operation, the dragend event fires at the source element — the element that was the target of the drag start.

-- https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#Drag_end
