### ISSUE TITLE
Relax eslint-plugin-react-hooks for __DEV__ conditional hooks

### ISSUE THREAD

**Issue by pke** [facebook/react#19781]
I think the usage of

```
if (__DEV__) {
  useXXX()
}
```

should not trigger the ESLint rule for hooks. While it is a condition, the value of `__DEV__` can not change during the runtime of the app.

Currently I disable the rule on a per-line basis but I wonder if this pattern could be excluded from the the rules?

**Comment by travigd** [comment]
In my own codebase, I sometimes do

```ts
function debugHookImpl(...) { ... }

export const debugHook = __DEV__ ? debugHookImpl : () => void 0;
```

but that's just a workaround.

**Comment by loloiqq** [comment]
Good Afternoon,

Please read this section "only call hooks at the top level" - https://reactjs.org/docs/hooks-rules.html

I went through this problem at CSCC(Columbus, Ohio) Online "Hackathon" 2020. We recreated this issue by creating a new React app. We then configured esLintConfig in the package.json file with the following:
```
 "plugins": [
      "react-hooks"
    ],
    "rules": {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn"
    }
```
if (__DEV__) {
  useXXX()
}

We then added this if statement to this code to trigger the esLint warning.

**Comment by gaearon** [comment]
`__DEV__` is not a super popular convention. Different tooling does it differently. I just recommend disabling the rule per line for concrete cases where you know what you're doing.

**Comment by pke** [comment]
Thanks Dan. What do you mean by different tooling does it differently?
React sets this global variable. So in the react context the behavior of it is clear. It's also clear that it cannot change during runtime. So hook rules should ignore it. 
But I'm fine with disabling the rule

**Comment by gaearon** [comment]
React doesn’t set a global variable like this. It’s used in React internally but it’s set by a build script. User code won’t have access to it. Usually people do stuff like `process.env.NODE_ENV` checks (which are also substituted by build).

**Comment by ThaJay** [comment]
`__DEV__` is typed as boolean, `true` would be more useful in this situation.
`process.env.NODE_ENV` is types as string, `'development'` would be more useful in this situation.

Based on the advice here, this is the solution I came up with:
```typescript
// eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
if ((process.env.NODE_ENV as 'development') !== 'development') {

  ...

}
```
