### ISSUE TITLE
Bug: Component is not re-rendered when array(State) is sorted (or position of array elements changed)

### ISSUE THREAD

**Issue by aromalanil** [facebook/react#19780]
The Component is not re-rendered when the state is changed (position of the elements in state array is changed)

React version: 16.13.1

Link to code example:

```jsx
import React,{useState} from 'react';
const App=()=>{
  const [numbers,setNumbers]=useState([8,6,4,9,7,3,1,2]);

  const sortEvent=()=>{
    setNumbers(num=>num.sort());
  }
  return(<>
    <h1>APP</h1>
    {
      numbers.map(num=><p key={num}>{num}</p>)
    }
    <button onClick={sortEvent}>Sort</button>
    </>
  )
}

export default App;
```

**Comment by omarsy** [comment]
You need to change your code to this:
```
const App = () => {
  const [numbers, setNumbers] = useState([8, 6, 4, 9, 7, 3, 1, 2]);

  const sortEvent = () => {
    setNumbers((num) => [...num.sort()]);
  };
  return (
    <>
      <h1>APP</h1>
      {numbers.map((num) => (
        <p key={num}>{num}</p>
      ))}
      <button onClick={sortEvent}>Sort</button>
    </>
  );
};
```

> Bailing out of a state update
> If you update a State Hook to the same value as the current state, React will bail out without rendering the children or firing effects. (React uses the Object.is comparison algorithm.)

 Ref: https://reactjs.org/docs/hooks-reference.html#usestate

**Comment by aromalanil** [comment]
But isn't `num.sort()` the straightforward way. Isn't that what the user expect?

**Comment by omarsy** [comment]
> But isn't num.sort() the straightforward way. Isn't that what the user expect?

`Array.sort` sort  the elements of an array in the same array, and for the "setNumbers" works you need a new array.

**Comment by vkurchatkin** [comment]
This is not correct:

```js
  const sortEvent = () => {
    setNumbers((num) => [...num.sort()]);
  };
```

You should copy array before sorting, not after:

```js
  const sortEvent = () => {
    setNumbers((num) => num.slice().sort());
  };
```

Also you should remember that `arr.sort()` does not actually sort array of numbers correctly

**Comment by omarsy** [comment]
> This is not correct:
What I’m trying to explain to him is that he has to change the reference of the value he has to return. 
But after you’re right the correct way if we use a function is this precisely :):
 const sortEvent = () => {
    setNumbers((prevnum) => [...num].]sort());
  };

**Comment by eps1lon** [comment]
To summarize: [`Array.prototype.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) does not create a new array but sorts the existing array in place and returns it:
> The sorted array. Note that the array is sorted in place, and no copy is made.


 Therefore the reference doesn't change in which case React will [bail out of rendering](https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update).

For workarounds see https://github.com/facebook/react/issues/19780#issuecomment-687893101 and https://github.com/facebook/react/issues/19780#issuecomment-687899599.
