### ISSUE TITLE
React Hooks Equality Callback Feature Request

### ISSUE THREAD

**Issue by myckhel** [facebook/react#19787]
I would like `useMemo`, `useCallback` etc. to accepts some arguments that will allow me to handle the equality function for each dependencies, just something similar to `react-redux`'s `useSelector` which accepts optional 2nd argument to control the equality check.
for example:
```
const value = useMemo(
    () => computeSomething(), 
    [decencies[0], decencies[1]], 
    (newDependency, prevDependency, dependencyIndex) => {
        if(dependencyIndex === 0){
            return newDependency === prevDependency;
        } else {
            return newDependency == prevDependency;
        }
    }
);
```

Please could this feature be considered?

**Comment by bvaughn** [comment]
This looks like a significant API change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.
