### ISSUE TITLE
Bug: components with className="adInfo" don't render

### ISSUE THREAD

**Issue by PabloAbreuC** [facebook/react#19790]

**Comment by eps1lon** [comment]
Please include the code that reproduces this issue and fill out the [issue template](https://raw.githubusercontent.com/facebook/react/master/.github/ISSUE_TEMPLATE/bug_report.md). A [codesandbox](https://react.new/) would be ideal.

**Comment by gaearon** [comment]
It’s your ad blocker.

**Comment by PabloAbreuC** [comment]
---
name: "🐛 Bug Report"
about: Report a reproducible bug or regression.
title: 'Bug: '
labels: 'Status: Unconfirmed'

---

React version: 16.13.1

## Steps To Reproduce

1. Create a functional component
2. Add a className "adInfo" to her


Link to code example:

https://codesandbox.io/s/vibrant-hill-3x61d?file=/src/App.js

## The current behavior
The component <h1 className="adInfo">Hello CodeSandbox</h1> don't rederize

## The expected behavior
Component renderize

**Comment by PabloAbreuC** [comment]
it's work. thanks
