### ISSUE TITLE
Bug: Glitchy behaviour when rendering/setState in an onKeyDown event callback

### ISSUE THREAD

**Issue by maximedupre** [facebook/react#19818]
React version: 16.13.1

## Steps To Reproduce

1. Please open the [minimal reproduction](https://codesandbox.io/s/silly-glitter-5xrdl)
2. Focus your cursor at the end of the third input text
3. Press CMD + Backspace

This successfully removes the third todo, but also sets the `text` attribute of the forth to an empty string, because the onChange event callback is called on the same input, but a new model is attached to it. Since CMD + Backspace has deleted the content of the input, the value of `e.target` in the `onChange` callback is an empty string, thus setting the value of the newly attached model to `''`.

Note that if the input is not being focused on in the `componentDidUpdate` method, the onChange event does not occur. The onChange event also does not occur if we wrap the focusing of the input in a `setTimeout(..., 0)`.

## The expected behavior

The input probably shouldn't be reused for a different model. The parent of the input is `<div key={todo.id}>`, so the input element should probably be recreated.

**Comment by Ryan-Willpower** [comment]
When you want to override the default behavior, e.g. backspace, you need to use `event.preventDefault()`.

Or you can [look at the file todo.jsx line 45](https://codesandbox.io/s/todo-input-bugfix-forked-cojwf)
