### ISSUE TITLE
Bug: eslint-plugin-react-hooks "Cannot read property parent of null"

### ISSUE THREAD

**Issue by travigd** [facebook/react#19810]
This seems to happen when
1. I take a component as a prop
2. I use that component as a JSX constructor in a hook

Minimal repro:
```jsx
export const Foo = ({ Component }) => {
  React.useEffect(() => {
    console.log(<Component />);
  }, []);
};
```

```
    "eslint-plugin-react-hooks": "^4.1.1",
```

---

Interestingly, this does NOT cause the error:
```jsx
export const Foo = ({ component }) => {
  React.useEffect(() => {
    const Component = component;
    console.log(<Component />);
  }, []);
};
```

**Comment by Hentaro1989** [comment]
I might be the same.

It happens when `@typescript-eslint/parser`  is 4.1.0 and I ran `yarn eslint`.

```
yarn run v1.22.4
$ eslint ./src --ext .js,.jsx,.ts,.tsx
The prop value with an expression type of ChainExpression could not be resolved. Please file issue to get this fixed immediately.

Oops! Something went wrong! :(

ESLint: 7.8.1

TypeError: Cannot read property 'parent' of null
```

I think [the issue of typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/issues/2513) is related.

`fastFindReferenceWithParent` in eslint-plugin-react-hooks returns null...

**Comment by eps1lon** [comment]
Confirmed with `@typescript-eslint/parser` 2.x, 3.x and 4.x. Interestingly by fixing it we can implement https://github.com/facebook/react/issues/18051 for `@typescript-eslint/parser`. I'll follow-up with a PR. We might need to partition the tests by parser and not language.

**Comment by gaearon** [comment]
Fix in `eslint-plugin-react-hooks@4.1.2`.

**Comment by Hentaro1989** [comment]
@eps1lon Thank you for solving this.

**Comment by damiangreen** [comment]
I'm still seeing this with
`eslint-plugin-react-hooks@4.1.2`, 
`@typescript-eslint/parser": "^4.2.0`,
`@typescript-eslint/eslint-plugin": "^4.2.0"`
`eslint": "^7.9.0"`

**Comment by Antonio-Laguna** [comment]
Same as @damiangreen here.

**Comment by travigd** [comment]
You should probably create a new issue.

**Comment by LauraBeatris** [comment]
@travigd I don't think so, since it's the same error

**Comment by travigd** [comment]
A new issue is likely to be seen by the relevant people more easily since it's not closed. And at least the error I reported in the issue above was actually fixed, even if it's the same error message.

**Comment by LauraBeatris** [comment]
@travigd Makes sense! I'll create another issue for it

**Comment by damiangreen** [comment]
@LauraBeatris  did you make the issue? if so can you mention it in this thread. as this is the top Google result..

**Comment by LauraBeatris** [comment]
@damiangreen Just created https://github.com/facebook/react/issues/19940
