### ISSUE TITLE
Question:  Create React component, like Lazy function

### ISSUE THREAD

**Issue by hosseinmd** [facebook/react#19812]
In JavaScript we can define lazy functions like this.

```js
let startDate = () => {
  const t = Date.now();
  startDate = () => t;

  return t;
};
```

What happens if we use this way to define components?

```js
let App = () => {
  const result = <div>
    // some layout
    </div>;

  App = () => result;

  return result;
};
```

**Comment by eps1lon** [comment]
It isn't clear what you're trying to achieve with that code. Maybe you're trying to memoize the result? React has a dedicated API for that with [`React.memo`](https://reactjs.org/docs/react-api.html#reactmemo).

If you've got more usage questions check out https://reactjs.org/community/support.html to find helpful communities. 

> What happens if we use this way to define components?

You can use [codesandbox](https://react.new) to experiment with React's behavior.

**Comment by hosseinmd** [comment]
I know react.memo behavior, my question is, is this way more performance than memo?

**Comment by hosseinmd** [comment]
I tested it with a few components which don't need props or state, they work well.

**Comment by hosseinmd** [comment]
@gaearon
