### ISSUE TITLE
Bug: A menu item in tutorial doesn't get highlighted on click

### ISSUE THREAD

**Issue by izdwuut** [facebook/react#19828]
Hi!

I've been working my way through your marvelous [tutorial](https://reactjs.org/tutorial/tutorial.html) when I've noticed that once you click on `Overview > Inspecting the Starter Code` in menu, the element doesn't get highlighted. It's because you use `<h3 id="inspecting-the-starter-code">...</h3>` instead of `<h2 id="inspecting-the-starter-code">...</h2>` in your markup. This should be a subheader, not header.

React version: Doesn't apply.
Browser: Firefox Developer Edition 81.0b9 (64-bit).

## Steps To Reproduce

1. Go to https://reactjs.org/tutorial/tutorial.html.
2. Click on `Overview > Inspecting the Starter Code` menu item.

Link to code example: doesn't apply.

## The current behavior
The `Overview > Inspecting the Starter Code` menu element doesn't get highlighted on click.

## The expected behavior
The `Overview > Inspecting the Starter Code` element should get highlighted on click.

**Comment by eps1lon** [comment]
Thanks for the report!

**Comment by izdwuut** [comment]
Anytime.
