### ISSUE TITLE
Feature request: bind event to react hook component. especially for typescript

### ISSUE THREAD

**Issue by thinksource** [facebook/react#19823]
I have two components the children component will emit 'onchange' event to parent component and the parent hook will deal with this event like:

parent component.

```
const App = ()=>{
    const initvalue=['abc']
    const handleChange(e:InputEvent)=>{
         return e.target.value
    }
    return (
   <>
         <InputArray  value={initvalue} onChange={handleChange}/>
   </>
   )

}
```
the children Component like:

```
const InputArray = (props: React.HTMLProps<HTMLInputElement>) =>{
     const {fields, onChang}= props
     const ulEl = useRef<HTMLInputElement>(null);

   useEffect(()=>{
        ulEl.current?.addEventListener('change', props.onChange)
       return (()=>{
                 ulEI.current?.removeEventListener('change', props.onChange)
                 }
              )

    })

    return (
    <ul ref={ulEl}>
        <p><button type="button" onClick={addfields}>
            Add 
        </button>
        <button type="button" onClick={removefields}>
            remove 
        </button></p>
        {fields.map((key, index)=>(<li key={`k${index}`} ><input type="text" value={key} onChange={(val: ChangeEvent<HTMLInputElement>)=>{
            props.values[index]=e.target.value
            emit('change', props.values)  // I just want input can emit an event to UL and UL can deal with InputEvent.
        }}/></li>))}
    </ul>)
}
```
I want the feature react hook can add new eventListener and children input can emit some even to outside.
(esp for typescript as UL is not input-element and it do not have matched types)

**Comment by TedKoker** [comment]
Do you mean that you want to add EventEmmiter to react hooks?

**Comment by thinksource** [comment]
@TedKoker  Yes, add some hooks can emit Events for example, the <ul> component can emit onChange event, since  the children of <ul> have <input> element emit some Events.

**Comment by gaearon** [comment]
You can always emit events with browser `node.dispatchEvent` API but we strongly recommend against something like this in React. Be explicit and call your function when you want something to happen.
