### ISSUE TITLE
Bug: window.onerror handler not invoked on unhandled exception in react rendering

### ISSUE THREAD

**Issue by RandomEngy** [facebook/react#19838]
The global JS error handler `window.onerror` is not invoked when there is an unhandled exception in the React rendering pipeline when running in optimized "production" build.

Though due to special handling, it is fired during a dev build.

[The documentation](https://reactjs.org/docs/error-boundaries.html) does not seem to indicate what the desired behavior is here. They mention you need such a handler to catch non-react errors but do not say anything about what happens to uncaught react errors. We can work around this by adding an error boundary at the root (in addition to our current `window.onerror` handling), but this seems like unexpected behavior to me.

React version: 16.13.1

## Steps To Reproduce

1. Set up a global error handler `window.onerror = (message) => { alert(message) };`
2. Throw an exception during react rendering that is not caught by any error boundary
3. Run the production build

Link to code example:
https://github.com/RandomEngy/test-error-boundary

## The current behavior
Handler is not fired.

## The expected behavior
`window.onerror` handler fires

**Comment by eps1lon** [comment]
Thanks for the report.

There's definitely documentation missing that explains it. However, #19613 already discusses the underlying issue. Since it has more traction I'm closing this issue.

**Comment by OliverJAsh** [comment]
@RandomEngy I understand there are some differences in the way errors work between development and production, but as far as I understand the difference you described is not one of them.

I cloned the repository, then ran `yarn && npm run build && http-server -c-1 ./build`. When I opened the site in my browser, the `onerror` handler was clearly called.

Can you confirm whether this is the same thing you're seeing on your end? Please let me know if there's something I've missing.

![image](https://user-images.githubusercontent.com/921609/99151664-b34b3d80-2694-11eb-86ff-cfd15bc6c589.png)

**Comment by RandomEngy** [comment]
I just tried it again as well and it does indeed fire window.onerror. I must have tested it incorrectly when first setting it up. There must be something odd with our larger project setup that prevents window.onerror from being called on a react error. I will have to dig a bit more.

Sorry for the inconvenience.

**Comment by vsanse** [comment]
i too am facing same issue where window.onerror is triggered for development build but not in production build. Does it have something to do with react's error overlay?

**Comment by CodeChangingMe** [comment]
> i too am facing same issue where window.onerror is triggered for development build but not in production build. Does it have something to do with react's error overlay?

Me too. I'm dying to know why.

**Comment by CodeChangingMe** [comment]
> i too am facing same issue where window.onerror is triggered for development build but not in production build. Does it have something to do with react's error overlay?

I ran a lot of tests. The findings may not only be related to react production build, but may also be related to Webpack.

**Comment by CodeChangingMe** [comment]
> i too am facing same issue where window.onerror is triggered for development build but not in production build. Does it have something to do with react's error overlay?

Hello.I'm glad I found the result I wanted. But I don't know if your situation is similar to mine.I hope this helps you.

I'm using react-loadable here because it's a promise, so all the internal ones can't be caught by window.onerror. So the production environment is not caught is normal behavior, development environment can be caught because the execution is not the same production environment. You can see the implementation of the invokeGuardedCallbackImpl function in react-dom.development.js.
