### ISSUE TITLE
Bug: react-refresh invalid main entry

### ISSUE THREAD

**Issue by wojtekmaj** [facebook/react#19835]
## Steps To Reproduce

1. Try to require react-refresh package directly ('react-refresh', not anything like 'react-refresh/runtime').

## The current behavior

> Error: Cannot find module '/node_modules/react-refresh/index.js'. Please verify that the package.json has a valid "main" entry

Indeed, `main` field in react-refresh points to `index.js`, which is simply not there. There's babel.js and runtime.js

## The expected behavior

* index.js file to be created, printing an error that you should require `…/babel` or `…/runtime` instead.
* OR main entry file changed to babel.js or runtime.js

**Comment by gaearon** [comment]
There is no main entry intended. I guess we could remove the `main` field.

**Comment by wojtekmaj** [comment]
That should be fine - [only name and version are required](https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields).

**Comment by gaearon** [comment]
Happy to take a PR.

**Comment by wojtekmaj** [comment]
Actually taking that back - this was fixed in 7d0e4150aa939ea843ab22bece1a415cbf2416cf by setting the default to `/runtime`. It was just not released for 3 months already. Sorry!
