### ISSUE TITLE
Bug: memoized component not re-rendering when prop changes after suspense resume

### ISSUE THREAD

**Issue by sfc-gh-sbessler** [facebook/react#19834]
React version: 16.13.1

## Steps To Reproduce

1. Given 3 React.memo'd components: A which contains B which contains C all inside a suspense context.
2. If A changes a context that causes B to throw a promise on re-render, and upon getting the result of that promise passes a value to C (changing C's prop) C will not re-render.

Link to code example: https://codesandbox.io/s/upbeat-buck-f6ntj
_This also shows a workaround, that if we don't use context to "pass" the "val" from A to B and instead actually pass a prop, it all works as-expected._

## The current behavior

C does not re-render in the above scenario. Altho, C2 does.

## The expected behavior

Component C should re-render in the above scenario.  Just like C2 does.

**Comment by gaearon** [comment]
Fixed in React 18.

https://codesandbox.io/s/amazing-lamport-0ql17b?file=/src/index.js
