### ISSUE TITLE
Bug: <Link> tag not working on iPhones

### ISSUE THREAD

**Issue by VelrinBlack** [facebook/react#19837]
React version: 16.13.1

## Steps To Reproduce

1. Create <Link> tag
2. Check bug on iPhone

## The current behavior
When you click on Link in the footer of my app on the iPhone, sometimes it redirects you to another subpage, but sometimes not.

## The expected behavior
Links are working fine

URL of my app: https:czarogrod.pl/
As I said before, sometimes it works but sometimes not (only on iPhones), on other devices, it works fine (even on MacBooks).

**Comment by bvaughn** [comment]
Looks like `<Link>` refers to a react-router component.

What makes you think this is a problem with React itself and not with the react-router library?

**Comment by Gautam-Arora24** [comment]
Can you provide the code where you used <Link> @VelrinBlack ? It would be easier to debug then.

**Comment by bvaughn** [comment]
Closing this issue as it doesn't really have adequate info to repro.
