### ISSUE TITLE
Provide autocomplete for `autoComplete` attribute

### ISSUE THREAD

**Issue by SimonSiefke** [facebook/react#19847]
Current typings:

```ts
interface AllHTMLAttributes<T> extends HTMLAttributes<T> {
  autoComplete?: string;
}
```

![no-completions](https://user-images.githubusercontent.com/23744935/93477312-2c2f5280-f8fb-11ea-9e35-aa3d185882e7.png)

With new typings:

```ts
interface AllHTMLAttributes<T> extends HTMLAttributes<T> {
  autoComplete?:
    | 'on'
    | 'off'
    | 'new-password'
    | 'current-password'
    | 'postal-code'
    // some more
}
```

![autocompletions](https://user-images.githubusercontent.com/23744935/93477053-cf339c80-f8fa-11ea-8369-4c762f54736c.png)

**Comment by gaearon** [comment]
Typings are not maintained in the React repository. They are maintained by the TS community in DefinitelyTyped so please raise the issue there. Thank you!
