### ISSUE TITLE
Bug: cannot use extended generic type in React.ComponentClass's props

### ISSUE THREAD

**Issue by icy0307** [facebook/react#19859]
React version:
@types/react@16.9.49
@types/prop-types@15.7.3
ts version 4.0.2
## Steps To Reproduce

~~~typescript
import React from 'react';
interface A {
    a: number;
}


function foo(param: React.ComponentClass<A>) {
    return param;
}

function foobar<T extends A >(param: React.ComponentClass<T>) {
    foo(param);
}

~~~

Link to code example:

https://www.typescriptlang.org/play?target=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKGADsYkpN0k4BBOAbyrh7hQC44NAK4gARgwqUAvlTmVMwmhmAQacTBAgAKMCigoQg5OhgA6AMK5INJHQsAbFAGdnAHlYA+AJSduvIhhhKHU9AxApWUoqRWUYVXUxfTcAFTgkAA96GgATZzZPXX1DY2JzK3A1OxhHF3cUnz9KXg0tIvDvSKogA

## The current behavior

`Argument of type 'ComponentClass<T, any>' is not assignable to parameter of type 'ComponentClass<A, any>'.
  Types of property 'propTypes' are incompatible.
    Type 'WeakValidationMap<T> | undefined' is not assignable to type 'WeakValidationMap<A> | undefined'.
      Type 'WeakValidationMap<T>' is not assignable to type 'WeakValidationMap<A>'.
        Types of property 'a' are incompatible.
          Type '(null extends T["a"] ? Validator<T["a"] | (T["a"] & null) | undefined> : undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>) | undefined' is not assignable to type 'Validator<number> | undefined'.
            Type 'null extends T["a"] ? Validator<T["a"] | (T["a"] & null) | undefined> : undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>' is not assignable to type 'Validator<number> | undefined'.
              Type 'Validator<T["a"] | (T["a"] & null) | undefined> | (undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>)' is not assignable to type 'Validator<number> | undefined'.
                Type 'Validator<T["a"] | (T["a"] & null) | undefined>' is not assignable to type 'Validator<number>'.
                  Type 'T["a"] | (T["a"] & null) | undefined' is not assignable to type 'number'.
                    Type 'undefined' is not assignable to type 'number'.
                      Type 'null extends T["a"] ? Validator<T["a"] | (T["a"] & null) | undefined> : undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>' is not assignable to type 'Validator<number>'.
                        Type 'Validator<T["a"] | (T["a"] & null) | undefined> | (undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>)' is not assignable to type 'Validator<number>'.
                          Type 'Validator<T["a"] | (T["a"] & null) | undefined>' is not assignable to type 'Validator<number>'.
                            Type 'T["a"] | (T["a"] & null) | undefined' is not assignable to type 'number'.
                              Type 'undefined' is not assignable to type 'number'.`
## The expected behavior
`param: React.ComponentClass<T extends A>` can assign to React.ComponentClass<A>

**Comment by bvaughn** [comment]
The React team does not maintain the TypeScript types. Those are kept in the DefinitelyTyped repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react

You'll want to report this issue there.

**Comment by icy0307** [comment]
thx😀
