### ISSUE TITLE
Bug: React build files contain the version of react being used

### ISSUE THREAD

**Issue by Santosh-13** [facebook/react#19856]
Is there any way to hide react version or is it designed to have react versions in the build files which are given in the production

**Comment by bvaughn** [comment]
The version is intentionally embedded as a string into the build.

One way this is used (there may be others) is by React DevTools– which uses the version number to switch between different implementation strategies to match the multiple versions of React this one tool has to interop with.

So far as I can tell, a version number has been embedded into the source as far back as 2014 (0b063f8a09dae4b6b1de400ff2d9aba9108647de).

Hope this answers your question!
