### ISSUE TITLE
eslint-plugin-react-hooks: don't warn for static `for` loops

### ISSUE THREAD

**Issue by KishanBagaria** [facebook/react#19850]
I've the following code:
```js
for (let i = 1; i <= 9; i++) {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  useHotkeys(`command+${i}, ctrl+${i}`, () => {
  // do something with $i
  })
}
```

which triggers this lint error:

> React Hook "useHotkeys" may be executed more than once. Possibly because it is called in a loop. React Hooks must be called in the exact same order in every component render  react-hooks/rules-of-hooks

This is a use case where the lint error shouldn't be triggered.

**Comment by vkurchatkin** [comment]
What rules to detect that the loop is static do you propose?

**Comment by KishanBagaria** [comment]
For starters, anything matching a signature of `for (let i = CONSTANT; i OPERATOR CONSTANT; i OPERATOR)`. Just gotta check it's not an infinite loop.

**Comment by vkurchatkin** [comment]
> for (let i = CONSTANT; i OPERATOR CONSTANT; i OPERATOR)

That's definitely not correct, since `i` can be reassigned inside of the loop which could make it dynamic or even infinite

**Comment by gaearon** [comment]
This is a rather uncommon case so IMO it doesn't make sense to try to detect it. If you run into it, disabling the rule in this specific instance seems reasonable to me.
