### ISSUE TITLE
Bug(17.0.0-rc.1): useEffect cleanup functions not running in the same order as effect functions 

### ISSUE THREAD

**Issue by uhyo** [facebook/react#19866]
React version: 17.0.0-rc.1

## Steps To Reproduce

```jsx
export default function App() {
  const [counter, setCounter] = useState(1);
  return (
    <div className="App">
      <h1>{counter}</h1>
      <p>
        <button onClick={() => setCounter((c) => c + 1)}>button</button>
      </p>
      <Foo name="1" />
      <Foo name="2" />
      {counter % 2 ? <Foo name="3" /> : null}
    </div>
  );
}

const Foo = ({ name }) => {
  useEffect(() => {
    console.log("effect", name);
    return () => {
      console.log("cleanup", name);
    };
  });
  return <p>I am foo</p>;
};
```

Run above code and click the "button" button, then check console log.

Link to code example: https://codesandbox.io/s/react17-useeffect-repro-s4hop

## The current behavior

```
effect 1 
effect 2 
effect 3 
cleanup 3 
cleanup 1 
cleanup 2 
effect 1 
effect 2 
```

## The expected behavior

```
effect 1 
effect 2 
effect 3 
cleanup 1 
cleanup 2 
cleanup 3 
effect 1 
effect 2 
```

## Description

[The blog post for React 17 RC](https://reactjs.org/blog/2020/08/10/react-v17-rc.html) says:

> Additionally, React 17 executes the cleanup functions in the same order as the effects, according to their position in the tree. Previously, this order was occasionally different.

However, as shown by the above example, cleanup functions do not run in the same order as effect functions. Seemingly, cleanup functions for unmounting components run before other ones.

**Comment by gaearon** [comment]
I think the blog post wording may have been imprecise but @bvaughn would be able to tell for sure.

**Comment by bvaughn** [comment]
> Additionally, React 17 executes the cleanup functions in the same order as the effects, according to their position in the tree. Previously, this order was occasionally different.

The wording was not meant to be interpreted the way you did (although I see how you could interpret it that way).

The ordering changes to passive effects were:
* Run *all* passive destroy functions before running *any* new effects (#17947)
* Defer passive effect destroy functions until after paint even when a component unmounts (#17925)

In general we make no guarantees about the specific order that effects or cleanup functions will be run in *within a component* or *between sibling components*. (For example, when a component is unmounted– React does not necessarily even remembers its previous position within the tree. The most current implementation just tracks these unmounting components in a "deleted" set to then run any effect cleanup functions. So the order we traverse and cleanup unmounted components will often be different from the order we traversed when mounting an updating them.)

React does guarantee the order of effects (and destroy functions) between *child and parent*, as well as the overall order of running *all destroy functions* before any new effects are created.

So yeah, in summary: This is not a bug, just a case of unclear wording. Wording improvements would be welcome in the form of PRs to:
https://github.com/reactjs/reactjs.org

**Comment by bvaughn** [comment]
I've taken a stab at this myself: https://github.com/reactjs/reactjs.org/pull/3273
