### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by n0ruSh** [facebook/react#19877]
A state change in a component which has `props.children` in the render result causes the component to re-render but not the `props.children` (which can be a React element) 

React version: 16.13.1

## Steps To Reproduce

1. Go to: https://codesandbox.io/s/beautiful-proskuriakova-iuxkr?file=/src/App.js
2. Open the console
3. Run the code
4. Click the `trigger change` button
5. Check out the console. `layout render` is printed indicating the `Layout` component is rendered. However, `item render` is NOT printed, which means `Item` component is NOT re-rendered

Link to code example:

https://codesandbox.io/s/beautiful-proskuriakova-iuxkr?file=/src/App.js

## The current behavior

`item render` is NOT printed when `trigger change` button is clicked

## The expected behavior

`item render` is printed when `trigger change` button is clicked

**Comment by gaearon** [comment]
This is expected — since the element can't have changed (React elements are immutable), React skips re-rendering. This is an important performance optimization since it lets you set state of a parent component managing a small part of the screen (e.g. a border) without re-rendering all of its children recursively.

**Comment by ihaichao** [comment]
@gaearon I'm confused about "React elements are immutable". Could you explain that in detail?

**Comment by a-c-sreedhar-reddy** [comment]
@ihaichao even though the state of a component is updated, props.children would give the same view since it does not use state. So instead of rerendering it uses the same result of previous render.
