### ISSUE TITLE
Bug: Nested Suspense not catching fast resolved Promises

### ISSUE THREAD

**Issue by Xiphe** [facebook/react#19870]
Given I have two resources stored and initiated in the `useState` of two nested components.
And both components have a `<Suspense>` 
And the resources are read by child components rendered within these Suspense-Boundaries.

Then I expect both resources to just be created once
And I expect the thrown promises to be captured by the closest `<Suspense>`

⚠️  But when the resources resolve within ~10ms
Then the inner resource is created more then once (i've seen up to 80 creations)
And the inner `<Suspense>` seems to be ignored

React version: `0.0.0-experimental-94c0244ba-0.0.0` - `0.0.0-experimental-3310209d0` (maybe also earlier)

## Steps To Reproduce

1. Go to: https://codesandbox.io/s/youthful-banach-dl5mq?file=/src/index.js
2. Open the console
3. Run the code
4. Observe multiple "CREATE SUB RES (with INIT) " logs
5. set `DELAY` in line 7 to `1000` or greater
6. Rerun the code
7. Observe only one "CREATE SUB RES (with INIT)"

Link to code example:

`0.0.0-experimental-94c0244ba`: https://codesandbox.io/s/quirky-bassi-1mbt7?file=/src/index.js

`0.0.0-experimental-3310209d0`: https://codesandbox.io/s/youthful-banach-dl5mq?file=/src/index.js

## The current behavior

lazy state initiation in nested component is called multiple times when promises/resources resolve fast
and called only once when promises/resources resolve slow

## The expected behavior

no change in behaviour weather the promises/resources resolve fast or not

---

Not sure if this maybe is intended and meant to prevent UI flickering / loading-waterfalls.
Or I am not supposed to create resources in lazy state initiations

In both cases I'd love to see deep docs about the why and how I am supposed to setup my resources.

**Comment by Xiphe** [comment]
Update. Have solved my personal problem with this by not creating the initial resources in lazy state initiators but instead globally. Which makes more sense and is much cleaner anyways. 

Now the component might still be initiated more often but it always gets the same initialRes.

```js
// before
function Comp() {
  const [res] = useState(() => createRes());
}
// after
const initialRes = createRes();
function Comp() {
  const [res] = useState(initialRes);
}
```

I don't have a real world use-case at hand where this is not possible so if you find this to be to much of an edge-case feel free to close the issue.

**Comment by gaearon** [comment]
Yeah overall this is definitely the recommendation, but I think it's still worth taking a look in the future at why there's a behavior difference when it resolves fast.

**Comment by Xiphe** [comment]
Agree, let me know when I can help

**Comment by Xiphe** [comment]
The behaviour has not changed with [`0.0.0-experimental-3310209d0`](https://www.npmjs.com/package/react/v/0.0.0-experimental-3310209d0)

Here's an updated sandbox: https://codesandbox.io/s/youthful-banach-dl5mq?file=/src/index.js
