### ISSUE TITLE
lazy state initiation in nested component is called multiple times when promises/resources resolve fast and called only once when promises/resources resolve slowBug: 

### ISSUE THREAD

**Issue by sultanarif-p** [facebook/react#19879]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

## The current behavior

lazy state initiation in nested component is called multiple times when promises/resources resolve fast
and called only once when promises/resources resolve slow

**Comment by eps1lon** [comment]
Could you provide a reproducing code example? A [codesandbox](https://react.new) would be ideal.

**Comment by rachelnabors** [comment]
Yes, please provide a reproducing example, and we'll be happy to have a look :)

**Comment by bvaughn** [comment]
Closing due to a lack of response.
