### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ximing** [facebook/react#19882]
React version: 16.13.1
System: IOS10

## Steps To Reproduce

1. Open the link below in the ios10 system，you can see arr.map not show, but console.log has been output 。

I'm not sure if it's the problem of react or webkit，but other systems is work.

### Link to code example:

https://codesandbox.io/s/admiring-hopper-04ugn?file=/src/App.js

## The current behavior
![image](https://user-images.githubusercontent.com/4659887/93860089-1d78df00-fcf1-11ea-960c-17cc66386caf.png)

## The expected behavior
![image](https://user-images.githubusercontent.com/4659887/93860114-29fd3780-fcf1-11ea-8c57-aa61d5915044.png)

**Comment by bvaughn** [comment]
> I'm not sure if it's the problem of react or webkit，but other systems is work.

This question should probably be answered before opening an issue in the React repo :smile:

Want to dig in and determine what the answer is?
