### ISSUE TITLE
Command prompt got struck while installing create react app

### ISSUE THREAD

**Issue by Deepakmukka1** [facebook/react#19880]
I was a newbie for reactjs,so when i tried creating an app
by this command
`npx create-react-app my-app
cd my-app
npm start`
it installed some packages and the command prompt got struck and its not responding and nothing was created
![WhatsApp Image 2020-09-21 at 11 09 12 PM](https://user-images.githubusercontent.com/56472120/93802372-012d6180-fc61-11ea-8cdf-7be49a8c14d1.jpeg)
The above image was result,what to do now?

**Comment by eps1lon** [comment]
If this happens repeatedly please open a [new issue in facebook/create-react-app](https://github.com/facebook/create-react-app/issues/new/choose) since this repository is concerned with React itself. Try to fill out their issue template as much as possible.
