### ISSUE TITLE
useReducer is called twice

### ISSUE THREAD

**Issue by jalik** [facebook/react#19889]
On first dispatch, reducer function is called once which is fine, but on next dispatch, it is called twice.

React version: >= 16.8.0 < 17.0.0-rc.0
EDIT: this bug is not present in 17.x.x versions of the lib.

## Steps To Reproduce

See the code sandbox below (very simple and short).

Link to code example:
https://codesandbox.io/s/react-usereducer-bug-5izy1?file=/src/App.js

## The current behavior

The reducer is called twice on N+1 dispatch

## The expected behavior

The reducer should be called once on N+1 dispatch

**Comment by gaearon** [comment]
The reducer is a pure function, so it should not matter how many times it's called. React reserves the right to fire it an extra time in some cases, as an implementation detail. These details will change between versions.

**Comment by jalik** [comment]
@gaearon thank you for replying, I've seen that in the doc.

However while I totally agree with you on the pure aspect of the reducer, the problem is actually that it triggers another (unwanted) render.

In my example, a single click triggers a single dispatch event to the reducer, but two renders are executed (why?).
In a short code like this, it's not a problem, but I have a more complex use case were the performances are terrible because of that behavior, even with the help of `useMemo`.

To be more precise, it's a calendar with hundreds of entries.
Sometimes it can handle 300 entries (~10/day), in that case the rendering process may take up to 1000ms, and because the reducer is called twice, it jumps to 2000ms which feels very slow for the user.

I feel like battling against React instead of using it happily as usual...

Please, do you have advises to handle these cases ?

**Comment by eps1lon** [comment]
> In my example, a single click triggers a single dispatch event to the reducer, but two renders are executed (why?).

In StrictMode (which is enabled in the index.js in your codesandbox) React also calls your render method twice to potentially catch side-effects.

To get real benchmarks you should profile the production build. I think in development the react-devtools profiler already ignores runtimes of dev-only double-renders but I'm not sure.

**Comment by gaearon** [comment]
>To be more precise, it's a calendar with hundreds of entries.

Extract those entries into a separate component.

The "extra render" you're referring to will only happen to the parent component itself, not its children. So you will not have a performance problem if you move the expensive per-item work into a child component.

If you have a concrete reproducible example of a perf issue related to this please share it.

**Comment by jalik** [comment]
> > In my example, a single click triggers a single dispatch event to the reducer, but two renders are executed (why?).
> 
> In StrictMode (which is enabled in the index.js in your codesandbox) React also calls your render method twice to potentially catch side-effects.
> 
> To get real benchmarks you should profile the production build. I think in development the react-devtools profiler already ignores runtimes of dev-only double-renders but I'm not sure.

My bad, thank you for pointing the StrictMode behavior, I forgot it, and that is indeed the cause of the extra render.

**Comment by jalik** [comment]
> > To be more precise, it's a calendar with hundreds of entries.
> 
> Extract those entries into a separate component.
> 
> The "extra render" you're referring to will only happen to the parent component itself, not its children. So you will not have a performance problem if you move the expensive per-item work into a child component.
> 
> If you have a concrete reproducible example of a perf issue related to this please share it.

Thank you for the advice, if it does not solve the performances, I'll prepare a sandbox.
