### ISSUE TITLE
eslint-plugin-react-hooks feature request: enforce naming convention for useState()

### ISSUE THREAD

**Issue by mbrowne** [facebook/react#19883]
(Re-opening https://github.com/facebook/react/issues/16908)

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

There is currently no rule to enforce the standard naming convention for `useState`.

**What is the expected behavior?**

It would be great to have a rule to enforce the standard naming convention for `useState()`:

```
const [x, setX] = useState(...)
```

For example, the rule would consider this an error:

```
const [x, setFoo] = useState(...)
```

This would ensure that all useState variables followed the same convention, i.e. `${varName}` and `set${upperFirstVarName}`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All versions with hooks

**Note**

I originally submitted a feature request for eslint-plugin-react: https://github.com/yannickcr/eslint-plugin-react/issues/2417. It was suggested that I make the feature request here instead. I'm not sure which plugin would be the more appropriate place for this.

**Comment by pgburrack** [comment]
I would like to contribute.

Should the fix as part of [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks)?

**Comment by karlhorky** [comment]
It looks like @gaearon has done most of the maintenance of `eslint-plugin-react-hooks`.

@gaearon, are there any objections from the team to having this `x` + `setX` naming convention as a warning in the plugin?

**Comment by mrlubos** [comment]
Hey everyone. Related to this, is there any rule to enforce the order of hooks in components? We can enforce the import order and previously the class components method order (e.g. constructor and state must be on top, render is last). Is there a rule to enforce useState to be on top, followed by useEffect for example?

**Comment by gaearon** [comment]
We won't be focusing on stylistic enforcement like this in the official plugin. This is definitely welcome in the ecosystem, but the official plugin focuses on correctness rather than style or naming.

**Comment by karlhorky** [comment]
Thanks for the official word on this @gaearon, I thought this would be the case.

Moving the discussion back to https://github.com/yannickcr/eslint-plugin-react/issues/2417
