### ISSUE TITLE
Bug: onBlur events not called when autofilled

### ISSUE THREAD

**Issue by levigunz** [facebook/react#19896]
While testing React 17.0.0-rc.2, we noticed a change in how React handles `onBlur` events when receiving updates via autofill (chrome in this instance). This [might be an intentional change](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#aligning-with-browsers), might be a problematic side effect of the event delegation changes or may just be a browser issue not in scope; I just want to verify.

In 16.13.1 when autofilling information, each input's `onBlur` is called.

In 17.0.0-rc.2, it appears that none of the input's `onBlur`s are called until you manually blur out of the input that had triggered the autofill. Even then, only the `onBlur` for this single input is called.

React version: 17.0.0-rc.2
Chrome version: 85.0.4183.102

## Steps To Reproduce

1. Click an input and autofill first name, last name and email.

Link to code example:

[React 17.0.0-rc.2](https://jsfiddle.net/qe9p3ujn/4/)
[React 16.13.1](https://jsfiddle.net/qe9p3ujn/5/)

## The current behavior
React 17: No `onBlur`s called with autofill.
React < 17: Each input that received autofill value has `onBlur` called.

## The expected behavior
I'm not really sure which one is correct. I lean toward React 17's current implementation where no `onBlur` is called.

**Comment by levigunz** [comment]
Going to close this because I do believe this to be an intentional side-effect rather than unintended consequence.

**Comment by varunagarwal315** [comment]
@levigunz I am using React 6.12 and `onBlur` is not being called for autofil on Safari. It is not consistent either, sometimes our logs show it got triggered and sometimes it does not. The form only has email on it. Any ideas?

**Comment by levigunz** [comment]
@varunagarwal315 if the blur is not being called on the input field that is being autofilled, that is most likely a browser issue and not a React issue sadly. If onBlur is not being called on the fields other than the one that initiated the autofill, you may want to chain onBlur calls using refs (not ideal).

**Comment by tripolskypetr** [comment]
Looks like all these methods with `autofill` prop are simple ignored by Google Chrome since 2022. I suggest a different method: using `readOnly={true}` until focus event

> Keep in mind that on mobile safari keyboard will not shown if input field change readonly state after focus event, so you need to process `onTouchStart` too. Heres the link to [the source code of `usePreventAutofill` hook](https://github.com/react-declarative/react-declarative/blob/51f4c29897297233e5c958de782b6af4e7b41cf5/src/hooks/usePreventAutofill.ts#L19)

```tsx
import { usePreventAutofill } from 'react-declarative';

...

const preventAutofill = usePreventAutofill();

...

return (
  <InputBase

      ...

      {...preventAutofill}
  />   
);
 
```
