### ISSUE TITLE
Error: "Commit tree does not contain fiber 5402. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by andyaaz** [facebook/react#19899]
Describe what you were doing when the bug occurred:
1. click record in profiler
2. click on a link to go to another page (gatsbyjs)
3. click stop recording in profiler
4. click on any commit in profiler and profiler crashed

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.2-fed4ae024

Component stack: CommitFlamegraphAutoSizer@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:31701:48
div
div
div
SettingsModalContextController@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:26139:18
Profiler_Profiler@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:33363:48
ErrorBoundary@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:27172:33
PortaledContent@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:27303:27
div
div
ProfilerContextController@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:30463:18
TreeContextController@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:22538:18
SettingsContextController@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:23040:22
ModalDialogContextController@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:28328:18
DevTools_DevTools@moz-extension://27fbeacf-1df3-cb4e-82f6-1ac8ce92baa3/build/main.js:33797:16

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#19633) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
