### ISSUE TITLE
Feature request: Add optional key parameter to built-in hooks

### ISSUE THREAD

**Issue by mateja176** [facebook/react#19890]
The key parameter would serve a similar purpose to the key prop which uniquely identifies list nodes and helps React remove or rearrange nodes without unexpected consequences.

In this context however, the key would identify an instance of a hook i.e. `useState`. This means that React would not have to rely solely on the order in which the hooks are being executed to guarantee correctness. Further, relaxing many of the existing [Rules Of Hooks](https://reactjs.org/docs/hooks-rules.html) and among others enabling instantiation of hooks inside if statements or loops. Moreover, making hooks more approachable for beginners.

Additionally, such a `key` would solve [this](https://github.com/facebook/react-devtools/issues/1334) shortcoming making hooks easier to debug in react-devtools.

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.
