### ISSUE TITLE
Bug: hydrating fails with nested paragraph and dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by romeovs** [facebook/react#19901]
React version: 16.13.1

## Steps To Reproduce

1. Use the `dangerouslySetInnerHTML` on a `p` element where the `__html` contains a `<p>` tag
2. Server-side render this component and try to hydrate

Link to code example:
```html
<!doctype html>
<html>
  <head>
    <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
  </head>
  <body>
    <!-- Pretend for an instance that this html was generated on the server by ReactDOM.renderToString() -->
    <div id="app"><p><p>Dope!</p></p></div>
  </body>
  <script>
    function Component() {
      return React.createElement("p", {
        dangerouslySetInnerHTML: { __html: "<p>Dope!</p>" },
      })
    }
    const component = React.createElement(Component)
    const root = document.getElementById("app")
    ReactDOM.hydrate(component, root)
  </script>
</html>
```

JSFiddles:
- This one breaks because it has nesting `p`:  https://jsfiddle.net/mw19p0g3/
- This one works because the wrapper is `div` instead of `p`: https://jsfiddle.net/mw19p0g3/2/
- This one works too because there no nesting `p` in the html: https://jsfiddle.net/mw19p0g3/3/

## The current behaviour
The `ReactDOM.hydrate` throws a cryptic error:
```
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "" Client: "<p>Dope!</p>"
```
Note the missing `Server: ""` string.

## The expected behavior
Do not throw an error and just hydrate the component as expected.

I realise that nesting `p` elements does not conform to the [HTML spec for the p element](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1).
If React chooses not to support the use case of nesting `p` tags through `dangerouslySetInnerHTML`, that's understandable. 
In that case the error should be more descriptive and there should probably also be an error or warning while performing the server side render. 
It should also be documenting somewhere that will easily show up in Google.

The current behaviour is very confusing and it took me a while to track down what was going on.

**Comment by romeovs** [comment]
Bump! Is there any way I can help to confirm this?

**Comment by MatthewDiamant** [comment]
Your issue may be because your `__html` top most element is a `<p>` tag, and you are using `dangerouslySetInnerHTML` on a `<p>` tag.

I also ran into this issue, and found that using a outermost `<span>` tag fixes the issue.

**Comment by romeovs** [comment]
Hmm, yeah I'm not saying that the code I wrote its 100% correct or should result in working behaviour. I'm saying that the error message was really unhelpful and confusing as to finding out the code was actually incorrect.

**Comment by dannyknows** [comment]
[This is has been around for a while](https://stackoverflow.com/questions/31348533/react-dangerouslysetinnerhtml-only-working-correctly-when-it-is-used-on-a-div-ta). 
I found this issue in search of a solution, is there an explanation for this behaviour?

**Comment by Limnades** [comment]
bump

**Comment by OmarZeidan** [comment]
I have faced the same issue when I am using `dangerouslySetInnerHTML` on a `<p>` tag. 

The fix was to use it on a `<div>` instead.

In my case, I am using ChakraUI and the `dangerouslySetInnerHTML` was on a `<Text dangerouslySetInnerHTML ...>`; I replaced the `<Text>` with `<Box dangerouslySetInnerHTML ...>` the issue disappeared!

**Comment by jvanmaaren** [comment]
For me this happened happened due to <div> inside a <p>

```
<p>
  <div dangerouslySetInnerHTML={{ __html: description }} />
</p>
```

Fixed by moving the div outside of the p

**Comment by rtconner** [comment]
Wow yeah thank you folks for pointing out the <p> was causing this. It is such a confusing error and I never would have expected the cause was a simple paragraph tag.

**Comment by skube** [comment]
Is this the same issue as noted in the [Next.js docs: Text content does not match server-rendered HTML](https://nextjs.org/docs/messages/react-hydration-error)?
