### ISSUE TITLE
useEffect strange mechanism: When deps has parameters, it will also be executed once in the first rendering

### ISSUE THREAD

**Issue by HackJoe** [facebook/react#19919]
React version:16.13.1

useEffect strange mechanism: When deps has parameters, it will also be executed once in the first rendering
```
const App=()=>{
    const [a, setA] = React.useState(0)

    React.useEffect(() => {
        console.log('first render')
    }, [])

    React.useEffect(() => {
        // The first rendering should not be executed
        console.log('state a update!!!')
    }, [a])
    
    return <div />
}
```

In the first rendering，Console print results：
```
first render
state a update!!!
```
**How to not execute  useEffect(()=>{},[a]) in the first rendering?**

**Comment by albseb511** [comment]
You can use the `useRef` hook to check if the component is mounted
```
const App=()=>{
    const [a, setA] = React.useState(0)
    const mounted = useRef()

  

    React.useEffect(() => {
        if( !mounted.current ) return
        // The first rendering should not be executed
        console.log('state a update!!!')
    }, [a])

  React.useEffect(() => {
        console.log('first render')
        mounted.current = true
    }, [])    

    return <div />
}
```

```

**Comment by bvaughn** [comment]
The behavior you're describing is expected: An effect will be run any time any of the inputs change– including when the dependencies change from undeclared to declared (on mount). The hooks documentation on effects explains the reasoning behind the way the effects hooks are designed:
https://reactjs.org/docs/hooks-effect.html#explanation-why-effects-run-on-each-update

You can use a ref to track mounted state, as @albseb511 mentions, if you don't want the effect to run on mount. :smile:
