### ISSUE TITLE
Suggestion: global custom attributes

### ISSUE THREAD

**Issue by jsenaribeiro** [facebook/react#19910]
Hi, 

I would like to suggest this new feature that may be useful: a custom global attribute as a DRY and KISS feature for sharing some repetitive coding or verbose styling. It is a bit familiar to Angular directive concept, but it is more functional and react-like. 

* **alternative 1**: using **@** token in component attribute working as a function injetor

```jsx
const glyphIcon = (elm, val) => elm.className = "glyphicon glyphicon-" + val + " icon";

<div @glyphIcon="ok" >...</div>
```

* **alternative 2**: function decorators (not support in ecmascript) would be nice for kebab-case notation

```jsx
@directive("glyph-icon")
const glyphIcon = (elm, val) => elm.className = "glyphicon glyphicon-" + val + " icon";

<div glyph-icon="ok" >...</div>
```

**Comment by vkurchatkin** [comment]
That is something you can already do:

```js
const glyphIcon = (val) => ({ className: "glyphicon glyphicon-" + val + " icon" });

<div {...glyphIcon("ok")} >...</div>
```

**Comment by jsenaribeiro** [comment]
Yeah vkurchatkin, 

I knew that, but for the same reason that we have a "<>" as suggar syntax for "<React.Fragment>", a specific suggar sintax for "shared attributes" could be nice.

´´´
// instead this
<div {...glyphIcon("ok")} >...</div>

// just this
<div glyphIcon="ok">...</div> 
´´´

Sorry for my delay...

Thanks,

**Comment by gaearon** [comment]
We don't really add helpers like this. JavaScript already has tools to share functionality, like functions. That's the solution.
