### ISSUE TITLE
RFC: Dynamically add external listeners for componentWillUnmount

### ISSUE THREAD

**Issue by syranide** [facebook/react#1992]
It's quite common to have external APIs that doesn't really belong being a component, but which must/favor being notified when the instance is being unmounted. Currently this can be solved by making the API a mixin, but IMHO it's the wrong solution.

I propose being able to do something like the examples below, I'm well aware that this could (and perhaps should) be implemented as a third-party mixin instead. But it's a common and simple enough use-case that having a unified implementation is at least worth bringing up I think, as it would be useful in bridging many APIs (without the use of mixins).

**EDIT:** Published an experimental mixin: https://github.com/syranide/react-unmount-listener-mixin

```JS
// simple but sub-optimal use
componentDidMount: function() {
  var p = extAPI.sendRequest();
  this.addEventListener('unmount', p.abort);
}

// non-retaining/leaking version
componentDidMount: function() {
  var p = extAPI.sendRequest();
  this.addEventListener('unmount', p.abort);
  p.oncompleted = function() {
    this.removeEventListener('unmount', p.abort);
  }.bind(this);
}
```

Or perhaps more locked-down unmount-only API:

```JS
componentDidMount: function() {
  var p = extAPI.sendRequest();
  var dispose = this.addUnmountListener(p.abort);
  p.oncompleted = dispose;
}
```

Or if the API was designed with it in mind (or wrapped by a helper):

```JS
componentDidMount: function() {
  var p = extAPI.sendRequest(this);
}
```

**Comment by spicyj** [comment]
The solution we're doing for this is #3398.
