### ISSUE TITLE
Bug: shallowEqual() is flawed

### ISSUE THREAD

**Issue by celmanabbas** [facebook/react#19921]
The `shallowEqual()` function located in `packages/shared/shallowEqual.js` is incorrectly using `Object.prototype.hasOwnProperty()` instead of `Object.prototype.propertyIsEnumerable()`, which is the correct counterpart for `Object.keys()`. 

Explanation:
------------
The `Object.keys()` method used inside `shallowEqual()` returns an array of a given object's own enumerable property names. But `hasOwnProperty.call(...)` (used in the `for` loop titled `Test for A's keys different from B`), checks only one of those things: ownership. Which causes the bug pointed out below. `Object.prototype.propertyIsEnumerable()` must be used instead which checks both direct ownership and enumerable-ity.

React version: v16.13.1

## Steps To Reproduce

```
const person = {
  name: 'Salman',
  age: 25,
};

const personWithProfession = {
  name: 'Salman',
  profession: 'Software Engineer', // This property goes undetected by shallowEqual()
};

// Add age
Object.defineProperty(personWithProfession, 'age', {
  value: 25, // non-enumerable by default
});

const keysA = Object.keys(person);
const keysB = Object.keys(personWithProfession);

console.log(keysA); // name,age
console.log(keysB); // name,profession

console.log(keysA.length === keysB.length); // true // Passes the length check
```

Link to code example with a demonstration and fixed version:
[https://codesandbox.io/s/infallible-keldysh-r98gl?file=/src/index.js](https://codesandbox.io/s/infallible-keldysh-r98gl?file=/src/index.js)

## The current behavior
```
shallowEqual(person, personWithProfession) // true
```

## The expected behavior
```
shallowEqual(person, personWithProfession) // false
```

## The fix
Replace
`!hasOwnProperty.call(objB, keysA[i])`
with:
`!propertyIsEnumerable.call(objB, keysA[i])`

**Comment by Salmatron** [comment]
My apologies, the codesandbox somehow didn't save my code. I have written a demonstration again at the same link.

**Comment by gaearon** [comment]
I think the intended behavior was that non-enumerable properties are skipped in the comparison. Want to send a PR to discuss a fix?

**Comment by Salmatron** [comment]
@gaearon Yesss it would be an honor :) I will prepare a PR. I think `hasOwnProperty()` has been heavily optimized by modern JS engines but not so sure about `propertyIsEnumerable()` so need to look at the performance angle too. We can discuss that on the pull request I guess. Thank you Dan!

**Comment by gaearon** [comment]
Yeah perf is pretty critical here. Moreso than obscure cases. In general we expect that props and objects being compared are plain objects, and anything non-enumerable doesn't count.
