### ISSUE TITLE
Bug: componentDidUpdate callback and child's useEffect callback called in a wrong order

### ISSUE THREAD

**Issue by fengChongxiu** [facebook/react#19922]
React version:
16.13.1
## Steps To Reproduce

1. open https://codesandbox.io/s/confident-bogdan-frtr0?file=/src/Child.js
2. click [click me] button and see results in console panel

Link to code example:

https://codesandbox.io/s/confident-bogdan-frtr0?file=/src/Child.js

## The current behavior
when i use functional component in class component, child's useEffect callback get called after parent's componentDidUpdate callback

if i only use functional components or class components, it works correctly

## The expected behavior
child's useEffect callback get called before parent's componentDidUpdate callback

**Comment by eps1lon** [comment]
`useEffect` is a combination of `componentDidMount` (cDM) and `componentDidUpdate` (cDU). cDU only runs on update not on the initial render (https://reactjs.org/docs/react-component.html#componentdidupdate). On your initial render your effect in `Child` runs but since `Parent` only got mounted its cDU does not run.

If you click "click me" then you get the expected order where Parent's cDU runs before Child's useEffect.

**Comment by fengChongxiu** [comment]
> `useEffect` is a combination of `componentDidMount` (cDM) and `componentDidUpdate` (cDU). cDU only runs on update not on the initial render (https://reactjs.org/docs/react-component.html#componentdidupdate). On your initial render your effect in `Child` runs but since `Parent` only got mounted its cDU does not run.

i agree with you on this point
> 

> If you click "click me" then you get the expected order where Parent's cDU runs before Child's useEffect.

let's focus on the update process, my point is that if parent and child both use hooks, the order is child's callback get called before parent's callback
if parent and child both use class component, the order is child's componentDidUpdate get called before parent's componentDidUpdate
but in this case, the result is Parent's cDU runs before Child's useEffect, are you sure this is the expected result?

**Comment by eps1lon** [comment]
> the order is child's componentDidUpdate get called before parent's componentDidUpdate
but in this case, the result is Parent's cDU runs before Child's useEffect, are you sure this is the expected result?

Note that `componentDidUpdate` (cDU) runs **after** the child has finished rendering. So it can only ever be called after the child is done rendering. cDU needs to run sync so the parent's cDU can only ever be called after child's cDU. However, `useEffect` is not executed in sync so the parent cDU runs before the child's passive effect (i.e. `useEffect`). 

If you need the child effect to run before the parent's layout effect you want `useLayoutEffect` which  is sync.

**Comment by fengChongxiu** [comment]
👍 got it, thanks
