### ISSUE TITLE
Bug: Yarn link breaks react-refresh

### ISSUE THREAD

**Issue by devbucket** [facebook/react#19924]
I have two projects, I am working on. 

- One is a web-app project that is set up as a mono-repository and compiled with Webpack. I use **@pmmmwh/react-refresh-webpack-plugin** together with **react-refresh/babel** to enable fast-refresh.
- Another one is an npm module that I publish.

I link the module into my web-project to work and debug on it.

After linking up the projects, I receive an error from Webpack:

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/2123279/94581449-67c30880-027b-11eb-8576-52998c64c867.png">

`redux-persister` is the npm module I work on.

Inside the npm module project, I run `yarn link`
Inside the web project, I run `yarn link redux-persister`

I checked inside the `node_modules` folder. The module is correctly linked

React version: 16.13.1

**Comment by gaearon** [comment]
This error is coming from webpack so I don't think there is anything actionable for us there. I think you need to double-check how linking works and how webpack works — something in their interaction is different from what you expect.

**Comment by gaearon** [comment]
Feel free to file this in `@pmmmwh/react-refresh-webpack-plugin ` though.

**Comment by SuperOleg39** [comment]
Maybe https://webpack.js.org/configuration/resolve/#resolve-symlinks will help
