### ISSUE TITLE
Bug: Error Boundary not catching certain errors

### ISSUE THREAD

**Issue by danielbonifacio** [facebook/react#19930]
I was following the documentation of error boundaries, when I got an unexpected behaviour that I think it's a bug.

If you fetch data from the API that does not match with the data structure that you're expecting (like a property with a value of null instead of an empty array) and you try to map it, JavaScript will throw `cannot read property map of null` and the error boundary component is not catching it. It is unmounting the whole application, instead of the single block that contains the error.

React version: 16.13.1

## Steps To Reproduce

1. Create an error boundary component
2. Get data from API that does not match with the expected structure (like null instead of an array)
3. Try to render the data

Link to code example: https://codesandbox.io/s/error-boundary-forked-yxccn

## The current behavior

Unmounting the whole application

## The expected behavior

Unmount only the part of application that has error

**Comment by bvaughn** [comment]
An error boundary won't catch an error thrown by the same render method that renders the boundary. (The boundary doesn't even exist yet at that time.)

You'll need to refactor your code so the error boundary is *above* the thing that may throw:
https://codesandbox.io/s/error-boundary-forked-6nb7g?file=/src/components/App.jsx

**Comment by Shrinijoshi** [comment]
@danielbonifacio will it not be something like user.friends && before mapping which removes that error? also, is there a reason for having not reachable code in Friends.jsx?
