### ISSUE TITLE
Bug: ...TypeError: destroy is not a function...from commitHookEffectListUnmount()

### ISSUE THREAD

**Issue by aberba** [facebook/react#19941]
This error pops up whenever I save to refresh (fast refresh)...it goes away when I make a different change only to re-appear in the next other change. appear-disappear-appear...

```sh
Unhandled Runtime Error
TypeError: destroy is not a function

Call Stack
commitHookEffectListUnmount
node_modules/react-dom/cjs/react-dom.development.js (19710:0)
commitPassiveHookEffects
/_next/static/chunks/main.js (40064:11)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (188:0)
Object.invokeGuardedCallbackDev
/_next/static/chunks/main.js (20533:16)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (292:0)
flushPassiveEffectsImpl
/_next/static/chunks/main.js (43149:9)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (653:0)
runWithPriority$1
/_next/static/chunks/main.js (31335:10)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (22820:0)
<unknown>
/_next/static/chunks/main.js (42995:11)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (597:0)
flushWork
/_next/static/chunks/main.js (49188:16)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (164:0)
```

I'm running on...
```sh
 "react": "^16.13.1",
 "react-dom": "^16.13.1",
```

I believe it comes from here 
```js
function commitHookEffectListUnmount(tag, finishedWork) {
  var updateQueue = finishedWork.updateQueue;
  var lastEffect = updateQueue !== null ? updateQueue.lastEffect : null;

  if (lastEffect !== null) {
    var firstEffect = lastEffect.next;
    var effect = firstEffect;

    do {
      if ((effect.tag & tag) === tag) {
        // Unmount
        var destroy = effect.destroy;
        effect.destroy = undefined;

        // THIS IS WHERE IT HAPPENS...WHY NOT
        // CHECK IF IT'S AN ACTUAL FUNCTION ???
        if (destroy !== undefined) {
          destroy();
        }
      }

      effect = effect.next;
    } while (effect !== firstEffect);
  }
}
```

Scoped
```js
        if (destroy !== undefined) {
          destroy();
        }
```
Even though it's not `undefined`, it might also not be a function...I assume that's the case so why not check to see if its an actual function before calling it?

**Comment by eps1lon** [comment]
Thanks for the report. Could you include the code and change that triggers this behavior? This would help a lot to identify this issue.

**Comment by aberba** [comment]
Our code is private. 

But looking at the error message, it doesn't seem to come from our code, its how the function I highlighted's code is written. Its a hooks+fast-refresh related issue.

**Comment by aberba** [comment]
Its from react-dom

**Comment by eps1lon** [comment]
It's not about where the error is located but what lead to this error. This is makes identifying the issue much easier and therefore reduces the time to fix it.

You don't have to post your full private code. Rather try reducing the code until it no longer causes an error. 

You mentioned "refresh (fast refresh)". Do you mean the React Fast Refresh i.e. are you using fast refresh in your build setup? How does your build setup look i.e. are you using create-react-app or nextjs or gatsby and which version?

**Comment by eps1lon** [comment]
> Could you include the code and change that triggers this behavior?

Are you maybe returning something from a `useEffect` that isn't a function e.g. 
```js
React.useEffect(() => {
  return {};
});
```
 You can only return a function or `undefined` from `useEffect` or `useLayoutEffect`.

**Comment by aberba** [comment]
Lemme see if there's anything like that... will get back to you

**Comment by aberba** [comment]
So yeah, we're using NextJs...

And about the hooks, we only have two in that specific page...
```js
function NearbyListings({ id }) {
    const store = useStore();
    const router = useRouter();
    const [listings, setListings] = useState([]);
    const [isLoading, setIsLoading] = useState(false);

    useEffect(() => {
        setIsLoading(true);

        store.dataStore.fetchNearbyListings(id)
            .then(resJson => {
                // console.log({ resJson })
                setListings(resJson.data);
            })
            .catch(error => {
                console.error({ error })
            })
            .finally(() => setIsLoading(false));
    }, [router.pathname]);
...
}
```


And 

```js
useEffect(() => {
        if (store.userStore.isSignedIn) {
            addViewCount(id);
        } else {
            // collect info

            const status = getCookie("user_details_status");
            // console.log({ status })

            if (status === "collected" || status === "cancelled") return true;

            store.uiStore.setShowUserInfoDialog(true);
        }
    }, []);

}
...
```

None looks like they return anything though.

**Comment by aberba** [comment]
With this one in particular commented out, it seems the error doesn't pop up anymore. 

```js
useEffect(() => {
        if (store.userStore.isSignedIn) {
            addViewCount(id);
        } else {
            // collect info

            const status = getCookie("user_details_status");
            // console.log({ status })

            if (status === "collected" || status === "cancelled") return true;

            store.uiStore.setShowUserInfoDialog(true);
        }
    }, []);

}
```

**Comment by aberba** [comment]
Oops `if (status === "collected" || status === "cancelled") return true;` might be the devil

**Comment by eps1lon** [comment]
> if (status === "collected" || status === "cancelled") return true;

There you are returning something other than `undefined` or a function.

To return early you can return nothing:

```diff
-if (status === "collected" || status === "cancelled") return true;
+if (status === "collected" || status === "cancelled") return;
```

**Comment by aberba** [comment]
Can we have react warn about this particular case?

**Comment by aberba** [comment]
Here

```js
   if (destroy !== undefined) {
          destroy();
        }
```

**Comment by eps1lon** [comment]
Note that this should've logged an error when the effect was run:

```
Warning: An effect function must not return anything besides a function, which is used for clean-up. You returned: true
    in App
    in StrictMode (at src/index.js:8)
```

It crashes once React tries to run the cleanup effect.

**Comment by aberba** [comment]
Could it be that Next.js doesn't cover this case? Notice you're using CRA

**Comment by aberba** [comment]
I reported it to the Next.Js issue page about reporting such an issue...https://github.com/vercel/next.js/discussions/17520

**Comment by eps1lon** [comment]
> Could it be that Next.js doesn't cover this case? Notice you're using CRA

The error is logged from react itself. Maybe nextjs is hijacking the console. Maybe some other logging mechanism locally intercepted it. Sometimes they're also just easy to miss.

**Comment by yashgandhi156** [comment]
I am also facing the same issue
