### ISSUE TITLE
anchor tag smooth scroll on anchor tag from API

### ISSUE THREAD

**Issue by Jonofat** [facebook/react#19946]
I am displaying data from a WordPress API with React and there is an anchor tag in the main content but when you click on it, it jumps to a div at the top of the page instead of doing a smooth scroll.

Using a React scroll package won't work (as far as I know) because I can't actually control the content coming from WordPress.

I basically need this to smooth scroll when clicked on. Is it possible?

`<a href="#section-one" class="btn">Learn more</a>`

I have tried using css but this does not work in Safari and I can also not control the speed of the scroll.

```
html {
    scroll-behavior: smooth;
  }
```

**Comment by gaearon** [comment]
This is unrelated to React itself so I'm going to close. Your question is about HTML/DOM. You should be able to ask on StackOverflow. Cheers!
