### ISSUE TITLE
Features/Improvements: Local/Network address only shown when code compiled successfully without any warnings.

### ISSUE THREAD

**Issue by taruntosh** [facebook/react#19954]
![suceess-server](https://user-images.githubusercontent.com/53813832/94996653-8f8bd680-05c3-11eb-9ac1-7dd6a84be562.JPG)
Local/Network address shown only when the code **COMPILES SUCCESSFULLY** without any warnings. 

![server-fail](https://user-images.githubusercontent.com/53813832/94996655-90bd0380-05c3-11eb-923c-0bcc7a8f470f.JPG)
It would be a great feature, if the Local/Network address is shown even when the code compiles with warnings.

**Comment by luiscrjunior** [comment]
Related to [create-react-app](https://github.com/facebook/create-react-app) ?

**Comment by bvaughn** [comment]
This is the React repo. It sounds like you're reporting an issue with create-react-app. Please report it in the create-react-app repository:
https://github.com/facebook/create-react-app/issues/

That repo is maintained by a different team of people.

Also, please search to see if the issue has already been opened before posting a new one.
