### ISSUE TITLE
Bug: v17 DEV mode slowness

### ISSUE THREAD

**Issue by Plitzi** [facebook/react#19958]
React version: 17.0.0.rc-2

i have been working on a project and testing this new version i saw that is working slow in dev mode and things like this
![Screenshot from 2020-10-05 13-36-48](https://user-images.githubusercontent.com/71875882/95080433-0209cd00-0710-11eb-9507-1f71f5b44abc.png)
![Screenshot from 2020-10-05 13-37-19](https://user-images.githubusercontent.com/71875882/95080434-033afa00-0710-11eb-9dcb-056a9fb1e69f.png)
![Screenshot from 2020-10-05 13-37-40](https://user-images.githubusercontent.com/71875882/95080436-033afa00-0710-11eb-85a4-4add13100092.png)

if we can see just to do a setState the stacktrace is too big and nested

## The current behavior

in dev mode, works slowly and laggy

## The expected behavior

should work faster

im not 100% sure if im wrong or not, but this stacktrace looks weird for me, and i was debugging it a little bit and was processing the stack since the root, but that doesnt make sense if im updating a state in a child

**Comment by eps1lon** [comment]
Thanks for the report. Could you include what you were doing to produce this stacktrace? Otherwise it might be hard to tell whether this is intended or not. A [codesandbox](https://react.new) would be ideal.

**Comment by bvaughn** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment]
@Plitzi Also by chance, are there a lot of DEV warnings in the console during this period of slowness?

**Comment by Plitzi** [comment]
@bvaughn @eps1lon  well im getting the common warnings from chrome

`[Violation] Forced reflow while executing JavaScript took 47ms`

This issue is pretty similar with the issue that @joacub is reporting as well

my point is, if we have a nested component in the react tree, why this have to render the full tree if im just updating a state in one of the leaf ?

       a
   b      c
d     e      f

if i update B, this should only refresh D and E, not A-B-C-D-E-F

**Comment by Plitzi** [comment]
@bvaughn i can share a link to you but in private because is a private project

**Comment by Plitzi** [comment]
@bvaughn @eps1lon testing with 16.13.1 this is a comparative

![Screenshot from 2020-10-06 01-01-53](https://user-images.githubusercontent.com/71875882/95144053-96574c80-076f-11eb-9ad4-37509e03fdfc.png)

we can see very well the diference and work 10x faster

**Comment by Plitzi** [comment]
@gaearon if this go Live with this issue, many ppl will complain about performance

**Comment by joacub** [comment]
> @gaearon if this go Live with this issue, many ppl will complain about performance

Yes you are right, in my case just i have that issue in DEV ENVIRONMENT, works pretty fast in production builds, the problem is just when an click event is handled by react, maybe is related to the new async state handler....

**Comment by Plitzi** [comment]
@joacub yes in my case was using mouseOver, but the event is not the problem, in my case is when i call setState or when props change

**Comment by joacub** [comment]
> @joacub yes in my case was using mouseOver, but the event is not the problem, in my case is when i call setState or when props change

https://github.com/facebook/react/issues/19950#issuecomment-703965402

check this post, I removed all the tree and just leave some components same behavior, probably the issue is related to the async state or something this is about how react is handling the mouse events

**Comment by joacub** [comment]
> but the event is not the problem, in my case is when i ca

i do another test, removing the onClick function and I do a profiler and react do the same, endless recursively call

**Comment by gaearon** [comment]
Hey folks, **this issue so far is not very helpful unless you provide a project that reproduces the issue**.

To keep it focused, please let’s refrain from further comments unless you have some code we can run to reproduce it.

**Comment by Plitzi** [comment]
@gaearon there is any way to PM you with a ngrok url ?

**Comment by gaearon** [comment]
A bit late today in London but you can email me at <my username>@fb.com and I'll reply tomorrow.

**Comment by joacub** [comment]
> @gaearon there is any way to PM you with a ngrok url ? do u have slack, discord, etc

right, that good though, I can do the same, if you guays do an slack, discord, WhatsApp, we can align this issue and resolve ASAP.

**Comment by gaearon** [comment]
Let's consolidate the discussion in https://github.com/facebook/react/issues/19950 since this is the same issue.
