### ISSUE TITLE
Bug: Fast memory leaks on simple React App

### ISSUE THREAD

**Issue by druzhchenko** [facebook/react#19968]
I have created simple test React application where browser tab and JS memory grow fast and don't clear. It is three tabs with same form which contains some count (1000-2000) generated input field. Browser is Edge based on chromium engine and memory report provide browser task monitor. Note: Chrome has same results
React version: 16.13.1

## Steps To Reproduce
Recursively:
1. Enter text on anyone input field.
2. Click to some other inactive tab.

After 5 minutes memory size of browser tab grows from 70mb to > 500mb and JS from 7mb to > 120mb, and stay there forever.

Link to code example: [GitHub](https://github.com/druzhchenko/react-memory-test)
My question on:  [StackOverflow](https://stackoverflow.com/questions/64225283/why-browser-tab-and-js-memory-leak-on-clear-react-app)

**Comment by Darth-Knoppix** [comment]
Looks like this is valid. Garbage collection doesn't seem to have the desired effect. Pulled the repo and tested for 5 minutes but in Chrome 86 - I didn't see memory exceed 100MB.

**Comment by gaearon** [comment]
Are you testing in production mode?

**Comment by Darth-Knoppix** [comment]
Tested the project in production and in development mode with similar results.
Garbage collection looks like it kicks in after 100MB but it doesn't have much of an effect, maybe the artefacts from reconciliation are sticking around?

I'm not seeing it as bad as the reporter is with 70MB to 500MB increase, after about 10 minutes of use the app has reached 130MB.

Not sure if this is a common use case though. In a production app I'd expect to see a some windowing being used to avoid rendering more than is on screen and some other optimisations.
