### ISSUE TITLE
Bug: State doesn't effect on Observer Pattern

### ISSUE THREAD

**Issue by mhkasif** [facebook/react#19973]
React version: 16.13.1

## Issue
I'm using the Observer pattern to listen to the change in the Bluetooth state.
When the subscription function calls, I'm changing the state inside of it.
but I'm unable to see the change in state inside my subscriber function, it shows the old state on every call.

**Comment by gaearon** [comment]
This isn't clear enough and seems like a support question. I suggest you to ask it on StackOverflow. If you think there's a React bug you need to prepare a reproducible example, like the template asks you to. You've ignored the template, so I'm closing.
