### ISSUE TITLE
Error: "Electron failed to install correctly, please delete node_modules/electron and try installing again"

### ISSUE THREAD

**Issue by romaniv1024** [facebook/react#19976]
When I try to start program using command
```sudo npx react-devtools```
I get error
```
/usr/local/lib/node_modules/react-devtools/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/react-devtools/node_modules/electron/index.js:14:11)
```
Even I install react-devtools localy by `sudo npm install -g react-devtools` and after start program by `sudo react-devtools`, get the same error. 

Any idea how to fix this?

---
Linux Mint 20 Cinnamon

**Comment by sktguha** [comment]
Hi @romaniv1024 , 
I think you created two issues by mistake, [https://github.com/facebook/react/issues/19977](https://github.com/facebook/react/issues/19977) is the newer one and also maybe this seems like a support request, maybe stackoverflow is the better place to answer this. A react team member can give more info on this though.

**Comment by eps1lon** [comment]
I think you need to follow the [install instructions for electron for linux](https://www.electronjs.org/docs/development/build-instructions-linux).

Might be a good idea to include these in the [README](https://github.com/facebook/react/blob/master/packages/react-devtools/README.md)

**Comment by bvaughn** [comment]
@eps1lon If you'd like to post a PR that adds more instructions, I'll review it.
