### ISSUE TITLE
[v4] Bug: "React must be in scope" should not fire when using new JSX transform

### ISSUE THREAD

**Issue by gaearon** [facebook/react#19992]
If you use new JSX transform (e.g. with 17 RC3), you still can't remove the `React` import because of the ESLint rule. We should automatically disable that rule when we use the new JSX transform.

**Comment by Maskedman99** [comment]
Same issue in v16.4.0, should we manually add this rule or am I doing something wrong ?

**Comment by Maskedman99** [comment]
https://github.com/facebook/create-react-app/issues/9782

**Comment by gaearon** [comment]
Lool I meant to fire this in CRA repo.
