### ISSUE TITLE
Bug: First two window resize events have the same timestamp

### ISSUE THREAD

**Issue by luerke** [facebook/react#20000]
If a "resize" event listener is attached to the window it seems that the very first two events that get triggered have the same timestamp. If the "resize" event is used to update the state of a function component via useReducer then the first update does not get registered into the state variable.

React version 16.13.1.

The first two logs to the console below give "0" though they should be "0" and "1".

import React, {useReducer} from 'react'
import ReactDOM from 'react-dom'
const Component = React.memo(
&nbsp;  (props) => {
&nbsp; &nbsp;    const reducerWinObj = (winObj) => {
&nbsp; &nbsp; &nbsp;       console.log(winObj.count)
&nbsp; &nbsp; &nbsp;       console.log(window.event)
&nbsp; &nbsp; &nbsp;       const newCount = (winObj.count + 1)
&nbsp; &nbsp; &nbsp;       return {count : newCount}
&nbsp; &nbsp;     }
&nbsp; &nbsp;     const [winObj, dispatchWinObj] = useReducer(reducerWinObj, {
&nbsp; &nbsp; &nbsp;       count : 0,
&nbsp; &nbsp;     })
&nbsp;     window.addEventListener("resize", dispatchWinObj, false)
})
ReactDOM.render(
&nbsp;   \<Component \/\>,
&nbsp;   document.getElementById('root')
)

**Comment by nahidmbstu** [comment]
https://jsfiddle.net/6ry05L47/ havent it in this test

**Comment by luerke** [comment]
I get it here https://jsfiddle.net/4y2wafx8/.

I have to add the event listener to "window" outside of useEffect because I have to remove and add it dynamically. The handler changes the value of a "useReducer" variable. I can't see why but in the JSFiddle example the resize event gets triggered automatically twice when the code is updated. But then the timestamps of the first two events are the same.

**Comment by bvaughn** [comment]
Adding an event listener during render is a side effect and is explicitly not allowed/supported. Please give [this section of the docs](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) a read for more context on why that is. Event listeners (and other imperative side effects) should be managed with `useEffect` or `useLayoutEffect`.

If you're adding an event listener during render, one possible reason that it is "getting triggered twice" is that you may actually be adding two event handlers (two different functions) each of which is getting triggered once.

Anyway, I am going to close this as it is definitely not a use case React supports.
