### ISSUE TITLE
Feature Request: Ability to filter consumers in context

### ISSUE THREAD

**Issue by Plitzi** [facebook/react#20014]
Good Afternoon, 

I would like to suggest this:

When we use contexts with provider/consumer, this is a good feature but in some scenarios you just want to trigger the consumer in specific conditions

This ticket is about to request a feature where we can have the ability to define filters in our consumer, and based on these filters the consumer will be triggered or not when the provider changes the value

Why ?
* Performance boost (because this only will re-render the consumer based on the filters)
* Usability (we can design better apps and decrease the unnecesary re-renders)

Example

i have a context to manage elements, but i just want to re-render based on the ID

**Comment by bvaughn** [comment]
What you're describing could be implemented with a wrapper component and `React.memo`, no?

**Comment by markerikson** [comment]
This is the intent behind the "context selectors" RFC and PR:

- https://github.com/reactjs/rfcs/pull/119
- #18262 
- #18855

**Comment by bvaughn** [comment]
Thanks for the links, Mark.

Going to close this issue.
