### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'namespaceURI' of null

### ISSUE THREAD

**Issue by mlaponder** [facebook/react#20016]
When rendering a react tree to a comment node, and this comment node is removed later this can result in:

`Uncaught TypeError: Cannot read property 'namespaceURI' of null`

React version: 16.13.1

## Steps To Reproduce

1. Run the reproduction project located in https://github.com/mlaponder/react-issue-reproduction/
2. Click the button 'Click me'
3. Click somewhere in this page, this will result in the mentioned TypeError

Link to code example:
https://github.com/mlaponder/react-issue-reproduction/

## The current behavior
The following error is logged to the console: `Uncaught TypeError: Cannot read property 'namespaceURI' of null`. Stack is in [here](https://github.com/facebook/react/files/5376154/typeerror-callstack.txt).

This error was found while upgrading from React version 16.9.0 and started breaking from 16.10.0. The behavior on 16.10.o is different, the same error occurs but then in an infinite loop.

## The expected behavior
No error occurs.

**Comment by xx1124961758** [comment]
The unmountcomponentatnode is executed asynchronously. Before the clean-up of react is completed, the container node is dismounted, resulting in the following error.

**Comment by gaearon** [comment]
The feature you're using is unstable (it says so in the comment you have to write to activate it, so I believe you're aware). This is a known problem with it, and there are some others. It will be removed from React so we recommend to migrate away from it.
