### ISSUE TITLE
Bug: ChunkLoadError using React.lazy inside a lib

### ISSUE THREAD

**Issue by juliopiubello** [facebook/react#20035]
I've being using lazy + Suspense inside a repository. Then I'm using this repository as a package inside two other projects. One is perfectly fine working with it, but the other one is throwing an error when it tries to load the bundle of the lazy loaded component

![image](https://user-images.githubusercontent.com/16126595/96147348-9bd63480-0edd-11eb-94a7-8e1c007db774.png)

React version: 
    "react": "^16.9.49",
    "react-dom": "^16.9.49",
    "react-router-dom": "^5.1.2",

The project is using webpack. 

"webpack": "^4.39.2",
    "webpack-bundle-analyzer": "^3.8.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.8.0",

The other project which it is working, have the same versions but diverge on the webpack config, so I'm not sure where to find tips for fixing it

## The current behavior

Is failing to load the bundle

## The expected behavior

Load the bundle

**Comment by brunocangs** [comment]
Check your webpack configs for the [publicPath](https://webpack.js.org/guides/public-path/) to make sure it looks for the bundles in the correct folder. From the error message it seems like it's looking at the full URL + bundle name

**Comment by juliopiubello** [comment]
Thanks, setting publicPath: '/' solved the issue!
