### ISSUE TITLE
Bug: new jsx transform production

### ISSUE THREAD

**Issue by hosseinmd** [facebook/react#20036]
React version:16.14.0

## Steps To Reproduce

I config our monorepo project to support new JSX transform anything work find on development mode but when creating a build after run project this error printed on browser console.

```
react-dom.production.min.js:209 ReferenceError: _jsxs is not defined
    at _ (index.tsx:12)
    at Jo (react-dom.production.min.js:153)
    at Ou (react-dom.production.min.js:261)
    at gl (react-dom.production.min.js:246)
    at vl (react-dom.production.min.js:246)
    at ul (react-dom.production.min.js:239)
    at nl (react-dom.production.min.js:230)
    at Hl (react-dom.production.min.js:281)
    at react-dom.production.min.js:284
    at sl (react-dom.production.min.js:240)
iu @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
mo @ react-dom.production.min.js:131
su @ react-dom.production.min.js:212
wl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yi @ react-dom.production.min.js:122
_l @ react-dom.production.min.js:248
ul @ react-dom.production.min.js:239
nl @ react-dom.production.min.js:230
Hl @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
sl @ react-dom.production.min.js:240
Xl @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
(anonymous) @ renderApplication.js:23
run @ index.js:51
e.runApplication @ index.js:95
208 @ index.ts:6
a @ (index):1
t @ (index):1
r @ (index):1
(anonymous) @ main.5064ecd0.chunk.js:1
react-dom.production.min.js:256 Uncaught ReferenceError: _jsxs is not defined
    at _ (index.tsx:12)
    at Jo (react-dom.production.min.js:153)
    at Ou (react-dom.production.min.js:261)
    at gl (react-dom.production.min.js:246)
    at vl (react-dom.production.min.js:246)
    at ul (react-dom.production.min.js:239)
    at nl (react-dom.production.min.js:230)
    at Hl (react-dom.production.min.js:281)
    at react-dom.production.min.js:284
    at sl (react-dom.production.min.js:240)
```

Link to code example:

## The current behavior

react-dom not working on production mode

## The expected behavior
Work.

I tested that in react-native and they work well on dev and production mode both

**Comment by gaearon** [comment]
Can you share a minimal reproducing project? This would greatly help. I did manual testing of both production and development modes, and did not encounter this problem.

**Comment by gaearon** [comment]
I do wonder if there's something TypeScript-specific here at play.

**Comment by gaearon** [comment]
I created a new CRA project with 4.0 beta, turned on the new transform explicitly in the webpack config, and added React 16.14. I made a production build, and did not observe this issue. I think something is being configured incorrectly, but I can't say without seeing your configs and a minimal reproducing project.

**Comment by gaearon** [comment]
I also just tried using TS 4.1 beta with CRA, switching the output mode to `react-jsx`, and that worked with production build too.

I wonder if you might have some special config that e.g. rewrites React to be an external (like a UMD bundle). UMD bundles don't have these methods — but you shouldn't be rewriting `react/jsx-runtime` imports to a UMD bundle either way.

**Comment by hosseinmd** [comment]
I don't know how to recreate the project that is somewhat hard.

Thanks for the explanation, I will try to find the problem and let you know.

**Comment by gaearon** [comment]
Generally a good way to reproduce an issue like this is to delete all files from your project except from the root component and check if it still reproes (it should given it's something related to the build).

**Comment by gaearon** [comment]
I'm going to close assuming this is a configuration problem. If you narrow it down to React, please feel free to file a new issue with a repro case.

**Comment by hosseinmd** [comment]
I couldn't found what is wrong, but I solved that by adding this code to Webpack config.
```js
 [
      "@babel/plugin-transform-react-jsx",
      {
        runtime: env === "production" ? "classic" : "automatic",
      },
    ],
```

**Comment by gaearon** [comment]
This doesn't really "solve" the problem — just works around it. I strongly recommend against this because now code that compiles in development (e.g. without a React import) would break for you in production. If you can't make a minimal reproducing project to figure out what's wrong, I suggest to stick with the classic transform for now.

**Comment by hosseinmd** [comment]
Please check this https://github.com/hosseinmd/test-new-jsx

**Comment by gaearon** [comment]
The problem is with your manual config overrides (which is why config overrides are fragile :-).

The config you're overriding already has this:

```js
                presets: [
                  [
                    require.resolve('babel-preset-react-app'),
                    {
                      runtime: semver.gte(react.version, '17.0.0-alpha.0')
                        ? 'automatic'
                        : 'classic',
                    },
                  ],
```

(It's not a good heuristic, which is something CRA will fix in the next release.)

But you're **adding** this to the config:

```js
                  [
                    require.resolve("@babel/plugin-transform-react-jsx"),
                    {
                      runtime: "automatic",
                    },
                  ],
```

So now we have **two different JSX plugins at the same time**. One is using the classic transform, and another one is using the new one. 

To fix this, either don't use config overrides and wait for proper CRA support, or override the right thing — the existing preset option.

It would be nice if we could error in the plugin when it's applied twice but I don't know if this is possible.

**Comment by hosseinmd** [comment]
> It would be nice if we could error in the plugin when it's applied twice but I don't know if this is possible.

I think this would be cool if just the latest one applies.

**Comment by hosseinmd** [comment]
There something other wrong, I changed the CRA config to this
```js
            presets: [
                  [
                    require.resolve('babel-preset-react-app'),
                    {
                      runtime: 'automatic'
                    },
                  ],
                ],
```
I have removed my override config, that working on development but is not working on production yet.

**Comment by gaearon** [comment]
How did you change the config? Did you eject?

**Comment by hosseinmd** [comment]
Excuse me that work now.

**Comment by gaearon** [comment]
Might have been a cache.

**Comment by hosseinmd** [comment]
> Might have been a cache.

Yes.
As you mentioned, I have overridden that.
```js
    config.module.rules[2].oneOf[1].options.presets[0][1].runtime = "automatic";
```
https://github.com/hosseinmd/test-new-jsx/commit/871ea8778c3629956f5d423f05700f4431caab14
