### ISSUE TITLE
Bug: this code will console double

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#20040]
```js
funciton Test(){
  setTimeout(() => console.log(1), 100)
  return ''
}
```

## The current behavior
double

## The expected behavior
once?
react 17 rc3

**Comment by bvaughn** [comment]
Setting a timeout during render is a side effect and should not be done. (Use an effect instead.)

Learn more about this here:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by zhangenming** [comment]
@bvaughn what about console.dir? thanks....this will double too...

**Comment by zhangenming** [comment]
some times console.dir is more powerful than console.log
so may i make a pr like https://github.com/facebook/react/pull/19069 ? thanks

**Comment by zhangenming** [comment]
sorry, is there anyone here,...
@bvaughn 
and about 
```console.count/asset/trace```
These don't have to be called twice,
