### ISSUE TITLE
Bug: Shorthand Fragment is not working if React is not in the scope 16.14.0

### ISSUE THREAD

**Issue by geart891** [facebook/react#20045]
React version: 16.14.0

## Steps To Reproduce

1. Open any React code.
2. Using `<>` `</>`

Link to code example: https://codesandbox.io/s/fragment-forked-ni765?file=/src/index.js

## The current behavior
Shorthand Fragment is not working if React is not imported. You have to include React or import Fragment and use it.

## The expected behavior
Shorthand Fragment should work without problem since import React is not required.

**Comment by eps1lon** [comment]
Codesandbox doesn't implement the jsx transform that allows React to not be in scope. Even 
```jsx
import { render } from "react-dom";

const rootElement = document.getElementById("root");

render(<div />, rootElement);
``` 

fails. 

It's not clear to me what happens to the shorthand fragment syntax with the new transform. The [blog post about the new transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) does not mention fragment shorthand syntax.

**Comment by gaearon** [comment]
You can play with it [here](https://new-jsx-transform.netlify.app/). 

```js
<>hi</>
```

becomes

```js
import { jsx as _jsx } from "react/jsx-runtime";
import { Fragment as _Fragment } from "react/jsx-runtime";

/*#__PURE__*/
_jsx(_Fragment, {
  children: "hi"
});
```

**Comment by gaearon** [comment]
CodeSandbox support for the new transform is not expected at this point.

**Comment by geart891** [comment]
Im building with webpack 5 and "babel-loader" and all the latest possible packages. It doesnt work as well. Is the changed has not released to a public version or what else should I do to make it work?

**Comment by gaearon** [comment]
Please provide a reproducing project. We can’t guess what went wrong without it.

**Comment by geart891** [comment]
> Please provide a reproducing project. We can’t guess what went wrong without it.
Oh, my bad, I am creating a mock repo. Please clone this repo and take a look. https://github.com/geart891/react-fragment.git

**Comment by gaearon** [comment]
Does this still reproduce if you remove Emotion and its Babel plugin?

**Comment by geart891** [comment]
> Does this still reproduce if you remove Emotion and its Babel plugin?

Indeed, if I change the order of the Emotion babel plugins, Shorthand fragment works again, however all the layouts become a mess. I guess this is the work of emotion babel plugin. Is there a way to work around this?

**Comment by gaearon** [comment]
I suggest to file an issue with Emotion. If they have any questions I’d be happy to answer. I guess maybe Emotion is missing the Fragment export in the runtime.

**Comment by geart891** [comment]
emotion-js/emotion#2041
Closed as this relates to emotion babel presets.

**Comment by Andarist** [comment]
We are good on track with the work on the new transform - it's not finished yet though. Right now combining our preset with the `"runtime": "automatic"` is not a good combination, they are going to fight with each other in unpredictable ways.
