### ISSUE TITLE
Resolving implicit thead can lead to invariant violation

### ISSUE THREAD

**Issue by syranide** [facebook/react#2005]
http://jsfiddle.net/9Q2m2/

Internet is more or less unavailable for me right now, so can't test more thoroughly. But thinking about it, it seems that the "blind-jumps" we do now to detect and resolve implicitly added elements (mainly `thead`) appears to not actually be safe as-is. Personally I feel like the solution is to not resolve implicitly added elements at all, but rather tell the user of his/her error instead and have them fix it.

Related PR #1987 (Provide a friendly path for reactID errors in ReactMount)

**Comment by gaearon** [comment]
The fiddle doesn’t work for me anymore, and last comment was several years ago.
I’ll close this as stale.

We do warn about bad nesting now, so hopefully this should not be a problem.
