### ISSUE TITLE
Misspelled "Escape" event type in Focus.js

### ISSUE THREAD

**Issue by aMarCruz** [facebook/react#20052]
Is the correct word "Escape" ?

https://github.com/facebook/react/blob/dfb6a403357d5ac2c0ea87aa6e5a4f947de342f8/packages/react-interactions/events/src/dom/create-event-handle/Focus.js#L72

**Comment by eps1lon** [comment]
> Is the correct word "Escape" ?

Yes, if you want to capture "Escape" key events. Though if this is a native event you might miss these events in IE/old edge.  React's event system handles some inconsistencies internally (e.g. to normalize `Esc` to `Escape` in IE/old Edge): https://github.com/facebook/react/blob/1890159a5d362e76ee949dfcace1ccb9677abc45/packages/react-dom/src/events/SyntheticEvent.js#L294-L312

Though `react-interactions` is experimental and it's unknown what the target browsers are. If you found a bug, please fill out [the bug report issue template](https://raw.githubusercontent.com/facebook/react/master/.github/ISSUE_TEMPLATE/bug_report.md). And post it filled out here.

**Comment by bvaughn** [comment]
This issue looks like it's asking a question, rather than reporting a syntax error. Since the question has been answered (presumably?) I'm going to close the issue.

**Comment by eps1lon** [comment]
@bvaughn I just realized that there is a typo not a syntax error:

```diff
-Esacpe
+Escape
```

So even if this a react event or a native event in non-Microsoft browsers it won't work.

Not sure what the current state of that package is.

**Comment by bvaughn** [comment]
Oh my. I read right over that typo. Re-opening!

**Comment by bvaughn** [comment]
cc @trueadm

Looks like this typo was made internally (Facebook) and then synced to the React repo.

**Comment by trueadm** [comment]
Fixed internally, thanks for the find @aMarCruz. I think we should probably remove the `react-interactions` from the repo soon anyway, so I won't bother updating it.

**Comment by cscarpitta** [comment]
Hi @bvaughn and @eps1lon 
This typo has been fixed in [#2278](https://github.com/facebook/react/pull/22780).

This issue can be closed.
