### ISSUE TITLE
Bug: useState setter should be able to take no arguments

### ISSUE THREAD

**Issue by ranneyd** [facebook/react#20056]
The typings for `useState`, have the setter as `Dispatch<SetStateAction<S | undefined>>`, but you can't actually legally call the setter without arguments. Since `type SetStateAction<S> = S | ((prevState: S) => S);`, then `SetStateAction<S | undefined>` explicitly makes `Dispatch<undefined>` valid. However, `type Dispatch<A> = (value: A) => void;`, where `value` is not an optional parameter. Thus if you have `setMyState()`, intending to set the value to `undefined`, which is legal, you get:

```
Expected 1 arguments, but got 0.ts(2554)
index.d.ts(867, 25): An argument for 'value' was not provided.
```
If the type for dispatch was `type Dispatch<A> = (value?: A) => void;`, or there was an optional value version of it, then typescript would be happy.

I'm not sure what the impact of making this parameter optional are, particularly in other places the type is used. But for `useState` it certainly seems to be legal (and intentionally so).

Alternatively I could explicitly say `setMyState(undefined)`, but then my linter and I won't be happy.

React version: 16.14.0
Typescript: 4.0.3
## Steps To Reproduce

0. Use React/React-DOM 16.14.0, TS 4.0.3, react-scripts 3.4.3, @types/react 16.9.53
1. Use the `useState` hook with any types, such as `const [myState, setMyState] = useState<string>();`
2. Call the setter from `useState` with no arguments, such as `setMyState()`.
3. Observe typescript error in editor.

Link to code example:

https://codesandbox.io/s/react-typescript-forked-h8fj9

## The current behavior
The editor complains that the function was expecting an argument and got none

## The expected behavior
TypeScript doesn't complain when we call the setter with no arguments.

**Comment by gaearon** [comment]
> Alternatively I could explicitly say setMyState(undefined), but then my linter and I won't be happy.

Why not? If you want to explicit pass undefined then you should pass it. Then the reader knows you didn’t forget it. Conceptually it is a required argument.
