### ISSUE TITLE
Mention facebook's immutable-js project somewhere

### ISSUE THREAD

**Issue by slorber** [facebook/react#2006]
https://github.com/facebook/immutable-js

I think this should be mentioned somewhere in React's documentation, for more advanced Immutable cases.

I wasn't aware of this project, while I have loved to be.

A good place could be: http://facebook.github.io/react/docs/update.html

**Comment by masterfung** [comment]
It is mentioned in the Advanced Performance section of the docs. I think it would be nice to have a sample project that utilizes ImmutableJS.
