### ISSUE TITLE
Load react/jsx-runtime over CDN and recommended document for upgrading to new JSX transform

### ISSUE THREAD

**Issue by otakustay** [facebook/react#20066]
As usual we use webpack's `external` configuration to reference react from CDN like jsdelivr or unpkg, however `react/jsx-runtime` does not contain a UMD version.

I'm wondering if react's core is loaded via a script element from CDN and `jsx-runtime` is bundled by webpack is safe, or will it cause conflict like the "multiple instances of react" one?

Also, I noticed that when `react/jsx-runtime` is introduced, webpack's `alias` configuration does not work when written in this way:

```
alias: {
  react: 'node_modules/react/umd/react.production.min.js'
}
```

We have to change `react` to `react$` to allow webpack resolve `react/jsx-runtime` successfully, I'd recommended this to be documented in react or babel's upgrading guide.

**Comment by gaearon** [comment]
>I'm wondering if react's core is loaded via a script element from CDN and jsx-runtime is bundled by webpack is safe, or will it cause conflict like the "multiple instances of react" one?

It's safe as long as you make sure that `require('react')` from the JSX runtime still resolves through your CDN alias.

>We have to change react to react$ to allow webpack resolve react/jsx-runtime successfully, I'd recommended this to be documented in react or babel's upgrading guide.

We never actually recommended aliases anywhere in particular so I'm not sure where we could mention this.

**Comment by otakustay** [comment]
> It's safe as long as you make sure that `require('react')` from the JSX runtime still resolves through your CDN alias.

Thanks

> We never actually recommended aliases anywhere in particular so I'm not sure where we could mention this.

Hope others encountered same problem can find this issue

I'll close this issue now.

**Comment by gaearon** [comment]
Also note the versions should match exactly.

**Comment by contactjavas** [comment]
WordPress/Gutenberg includes `react` and `react-dom` globally (at least when editing using Gutenberg or in customizer).

For now, I'm sticking to the classic runtime for WordPress development.
Maybe there will be a umd dist for `jsx-runtime` in the future 😀 .

Also a problem when using Parcel v2. Aliasing to `"react"` made the `react/jsx-runtime` unresolved. But turning to `"react$"` made the aliasing failed (React was still bundled).
