### ISSUE TITLE
Feature Request: Explicitly ignore select dependencies for exhaustive-deps rule [eslint-plugin-react-hooks]

### ISSUE THREAD

**Issue by mogelbrod** [facebook/react#20067]
The `react-hooks/exhaustive-deps` eslint rule is great, until you consciously want to ignore a specific dependency. For those cases the only current option (that I'm aware of) is to disable the rule for the line. It would be great if it was possible to  explicitly ignore one or more dependencies while keeping the rule enabled. That way it would still warn if I added a new dependency without also including it in either list.

One potential approach would be to allow devs to list these ignored dependencies using `/* comments */`, for example:

```js
React.useEffect(() => {
  doSomething(a, b, c)
}, [a] /* ignore-deps: b, c */)
```

In this fictional example I'd only like to `doSomething` in response to changes to `a`, while changes to `b` and `c` by themselves should be ignored. Using the comment I can explicitly state that this behaviour is intended, while still being warned if the call changes to `doSomething(a, b, c, d)` - notifying me that I need to add `d` to either the dependencies or the ingore-deps comment.

The proposed style and location of the comment is based off the idea that it should be in close proximity to the dependency list (developer experience), while hopefully also somewhat simple to access via the AST (implementation complexity). Alternative suggestions are appreciated!

**Comment by gaearon** [comment]
We’re pretty adamant that there is *no* case in which ignoring some of them is the right solution. There are always other, better solutions (e.g. involving refs or removing the effect altogether and moving the logic to an event handler). But generally saying you should consider this a compile error. I can come up with a solution if you post a more specific example.

**Comment by mogelbrod** [comment]
@gaearon: I'm inclined to agree with everything you mentioned, and haven't been able to find an example where the rule wasn't disabled for convenience reasons. Thanks for the quick and helpful response!

**Comment by masad-frost** [comment]
@gaearon I agree, it sucks that we have to disable the whole rule for everything when we don't have to. I put up a PR where you can mark the result of some hooks as stable, mostly targeting custom hooks that return refs. https://github.com/facebook/react/pull/20513

**Comment by zposten** [comment]
Creating a ref exclusively for the purpose of making an effect not re-run when a particular dependency changes is such an indirect way to solve the problem.  

I feel that the intent of the code you're writing is really hazy.  When someone else looks at this code a few weeks or months, how can they be certain that the only purpose of the ref is to ignore the dependency?  Should I now add a code comment in addition to the ref?

**Comment by kyle-ssg** [comment]
Having created so many refs/keeping them up to date with state over the past few years to keep covering for this case, I had to search this up. I totally agree with @zposten's last comment on this.

**Comment by daniellittledev** [comment]
I've run into a case where wrapping the `useEffect` hook results in an `react-hooks/exhaustive-deps` issue. I'm using refs to only run an effect when the URL of the page changes regardless of changes to other dependencies.

`React Hook useEffect has a missing dependency: 'effect'. Either include it or remove the dependency array. If 'effect' changes too often, find the parent component that defines it and wrap that definition in useCallback`

In this case the `dependencies` passed to this hook should already be exhaustive, so I should not need to add the `effect` function to the dependencies provided to `useEffect`.

```
export function useEffectWhenPathChanges(
  effect: EffectCallback,
  dependencies: DependencyList
) {
  const location = useLocation()
  const lastPath = useRef<string | null>(null)
  useEffect(
    () => {
      const newPathName = location.pathname
      const oldPathName = lastPath.current
      if (newPathName !== oldPathName) {
        lastPath.current = newPathName
        return effect()
      }
    },
    [...dependencies, location.pathname]
  )
}
```

Adding the effect parameter to the dependencies list would be an issue because passing a function to an effect it is typically done with an inline function. This would be a new reference each render, which would then run each render defeating the point of using `useEffect` here.

```
useEffectWhenPathChanges(() => { console.log("Path Changed") }, [])
```

As an aside I have also felt the need to specify a subset of the `dependencies` that should trigger the effect function. I believe this is inline with the comment from @0livare. Maybe something like.

```
useEffectWhen(() => {}, [/*dependencies*/], [/*triggers*/])
```

**Comment by daukantas** [comment]
Dan Little:

Your github input has been violating my email !

Attention:  Please  make adjusted  changes to prevent your input entering this email site.


Warning! Please review “Scams and Identity Theft Attempts Targeting International Affiliates”, which can be found at https://www.hupd.harvard.edu/scams-targeting-international-affiliates
Scams and Identity Theft Attempts Targeting International Affiliates<https://www.hupd.harvard.edu/scams-targeting-international-affiliates>
Introduction
www.hupd.harvard.edu<http://www.hupd.harvard.edu/>
.

________________________________

**Comment by jacobgmathew** [comment]
> We’re pretty adamant that there is _no_ case in which ignoring some of them is the right solution. There are always other, better solutions (e.g. involving refs or removing the effect altogether and moving the logic to an event handler). But generally saying you should consider this a compile error. I can come up with a solution if you post a more specific example.

@gaearon In the motivation for the useEffectEvent, the React docs acknowledge with examples that there are cases where ignoring some of them is the right solution: https://react.dev/learn/separating-events-from-effects#reading-latest-props-and-state-with-effect-events. 

Can this be reopened? Alternatively is there a way to implement something like useEffectEvent correctly currently without suppressing dependency warnings?

**Comment by KyrylStronkoRoofr** [comment]
> Alternatively is there a way to implement something like useEffectEvent correctly currently without suppressing dependency warnings?

React <=17
```
    function useRefCallback(callback) {
        const callbackRef = useRef(callback);

        callbackRef.current = callback; // or wrap it in useLayoutEffect if you don't feel safe about mutating the ref during render

        return useCallback((...args) => callbackRef.current(...args))
    }
```

React >=18
```
    function useRefCallback(callback) {
        const callbackRef = useRef(callback);

        useInsertionEffect(() => {
            callbackRef.current = callback
        }, [callback])

        return useCallback((...args) => callbackRef.current(...args))
    }
```
