### ISSUE TITLE
react-dom 17 breaks on internet explorer

### ISSUE THREAD

**Issue by JSumner1992** [facebook/react#20069]
After updating react-dom to version 17 the build now includes Array.fill() which isn't supported by ie11 without polyfilling. Coming from this line. Tested with just the default cra production build to make sure it wasn't a problem with my webpack config and the same issue.

https://github.com/facebook/react/blob/96ac799eace5d989de3b4f80e6414e94a08ff77a/packages/react-reconciler/src/ReactFiberLane.js#L671

Tested using CRA on version 16.9.8 of react and react-dom which works with the production build for ie11.

**Comment by eps1lon** [comment]
Confirmed with https://csb-hznfc-77macj50y.vercel.app/ (built from https://codesandbox.io/s/cranky-glitter-hznfc?file=/package.json) which errors with "SCRIPT438: Object doesn't support property or method 'fill'".

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/20071

**Comment by gaearon** [comment]
@eps1lon Any chance you could confirm the fix on a real IE

**Comment by gaearon** [comment]
Gonna wait to see if a few more bugs get reported in the next few hours. Then will cut a patch.

**Comment by gaearon** [comment]
Should be fixed in 17.0.1.
