### ISSUE TITLE
Bug: Error loading source maps for devtools extension

### ISSUE THREAD

**Issue by Friss** [facebook/react#20075]
React version: 16.x.x

## Steps To Reproduce

1. Have latest React devtools installed in Chrome
2. Open console and see warning about failure to load source maps.

<img width="1161" alt="Screen Shot 2020-10-22 at 12 12 23 AM" src="https://user-images.githubusercontent.com/4588318/96823803-4d53f900-13fb-11eb-9f3d-e26d519fabbc.png">

<img width="422" alt="Screen Shot 2020-10-22 at 12 12 53 AM" src="https://user-images.githubusercontent.com/4588318/96823829-59d85180-13fb-11eb-8113-974ea7231f5c.png">

Looks to be related to https://github.com/facebook/react/pull/19773 

Link to code example:

## The current behavior
Console logs about failure to load source maps

## The expected behavior
No console logs because of the extension

**Comment by hqwuzhaoyi** [comment]
I have the same warning, and my componet is always loading.
![image](https://user-images.githubusercontent.com/44605072/96827373-0bad6780-1468-11eb-9671-688daa9917b8.png)
but it works on 4.8.2
![image](https://user-images.githubusercontent.com/44605072/96827507-53cc8a00-1468-11eb-8521-efc76ad16875.png)

**Comment by codingbycat** [comment]
I have the same warning in React^17.0.0 too

**Comment by bvaughn** [comment]
Sorry about the hassle here. I'm not sure why Chrome is showing this warning, as the source map URLs are correct. If anyone would like to dig into this, I'd welcome the help.

**Comment by bvaughn** [comment]
@hqwuzhaoyi Your comment does not seem related to this thread.

**Comment by bvaughn** [comment]
Looks like a potentially related CR bug from back in February: https://bugs.chromium.org/p/chromium/issues/detail?id=1052872

**Comment by bvaughn** [comment]
A simple fix for this might be to revert the changes from #19773 to files within `packages/react-devtools-extensions` (but leave the other packages with source maps enabled).

**Comment by sytranvn** [comment]
@bvaughn I tried reverting the changes in `packages/react-devtools-extensions` and it fixed. Please help to review the PR #20079. Thanks.

**Comment by Friss** [comment]
Thanks for the quick work @bvaughn @sytranvn 

We've run into similar issues with our own chrome extension so no big deal :D

**Comment by danielpickett** [comment]
Still having this issue. It looks like my React DevTools extension is still on version 4.9.0. 

![image](https://user-images.githubusercontent.com/11799835/98137342-e2410280-1e8f-11eb-9d23-01b9d4bf305e.png)

How do I get the version with the fix that was merged above? Removing and re-adding the extension didn't work. Sorry for the rookie question, but I'm sure others will be landing here with the same question.

**Comment by bvaughn** [comment]
The fix has not been released. You're still running the latest DevTools..

**Comment by danielpickett** [comment]
Oh, I see. Thank you!

**Comment by joaomelo** [comment]
I don't know if is of any help for fixing the bug, but anyhow sharing my experience, some of the messages did not appear anymore in Chrome after I right-clicked the React Dev Tool extension icon in the toolbar, clicked "manage extension" (I'm freely translating menu text here since my browser language is in Brazilian Portuguese), and then enabled "Allow access to files URLs."

**Comment by Willi-Smith** [comment]
> I don't know if is of any help for fixing the bug, but anyhow sharing my experience, some of the messages did not appear anymore in Chrome after I right-clicked the React Dev Tool extension icon in the toolbar, clicked "manage extension" (I'm freely translating menu text here since my browser language is in Brazilian Portuguese), and then enabled "Allow access to files URLs."

This unfortunately doesn't work for me. 
* Chrome:  88.0.4315.5 (Official Build) dev (64-bit)
* fresh install of React Developer Tools
* no other extensions

Console still polluted by:
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/injectGlobalHook.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/contentScript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by bvaughn** [comment]
**The fix for this has not been released yet.**

**Comment by federico7marroquin** [comment]
be patient guys

**Comment by bvaughn** [comment]
Version 4.10 has been published to NPM and posted to Chrome/Firefox/Edge stores. Chrome usually takes a while to approve (hours, sometimes days).
