### ISSUE TITLE
Bug: Property expression of JSXExpressionContainer expected node to be of a type ["Expression","JSXEmptyExpression"] but instead got undefined

### ISSUE THREAD

**Issue by jakeherp** [facebook/react#20070]
React version: 17.0.0
Next.js version: 9.5.5
TypeScript version: 4.0.3

## The current behavior

In a Next.js project using styled-jsx I get the following error across different components that create a `<style jsx>` tag to generate CSS selectors within template literals (or import such styles from a separate file):
```
Property expression of JSXExpressionContainer expected node to be of a type ["Expression","JSXEmptyExpression"] but instead got undefined
```
The error appears as soon as I update `react` and `react-dom` to 17.0.0, all other dependencies remain at the version they have been beforehand.

## The expected behavior

It renders the component as expected without any errors.

**Comment by eps1lon** [comment]
This sounds like an issue with next and the new JSX transform. Since react 17 has just been released `nextjs` or `styled-jsx` have probably not been updated yet. Could you file an issue in either one of those repos to make sure that is indeed an issue with React and not some other library?

**Comment by jakeherp** [comment]
That is what I thought after some investigation, I have opened a bug report over at Vercel: https://github.com/vercel/next.js/issues/18083
Closing this issue here, until clarified.
