### ISSUE TITLE
Bug: React 17 upgrade causes "Cannot read property 'removeEventListener' of null"

### ISSUE THREAD

**Issue by greggailly** [facebook/react#20080]
We have upgraded to React 17 and since then we get Cannot read property 'removeEventListener' of null.
Mostly happens when component updates after state change.

React version: 17

## Steps To Reproduce

1. Upgrade to React 17
2. Change page

## The current behavior

![Screenshot 2020-10-22 at 17 34 02](https://user-images.githubusercontent.com/59643626/96895630-e3842f80-148c-11eb-9cd6-cdc77037b685.png)

## The expected behavior

No error

**Comment by kachkaev** [comment]
👋Could you please share a reproducible example on https://codesandbox.io or as a repo?

**Comment by gaearon** [comment]
Could it be this?
https://reactjs.org/blog/2020/08/10/react-v17-rc.html#potential-issues

**Comment by greggailly** [comment]
Probably ! Unfortunately seems to be coming from a library so we will check with them to fix this.
Thanks for the help.
Cheers

**Comment by liadb** [comment]
We had the same issue, can confirm it came from [rc-virtual-list](https://github.com/react-component/virtual-list) which is an Ant Design Select dependency.
We resolved it by using `rc-virtual-list` 3.2.0

**Comment by nvbinh** [comment]
I got the same issue when using a page with the Ant Design Tree component

![Screen Shot 2020-12-07 at 17 02 12](https://user-images.githubusercontent.com/5524162/101337354-1d2ebf80-38ae-11eb-9a8d-395600000b26.png)

**Comment by riteshjagga** [comment]
As explained on [this link](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#potential-issues) (link from above), 

> We don’t expect this to be a common problem because [our eslint-plugin-react-hooks/exhaustive-deps lint rule](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks)[](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#consistent-errors-for-returning-undefined) (make sure you use it!) has always warned about this.

I do not see any eslint warning related to this.

**Comment by lucaspdfborges** [comment]
> I got the same issue when using a page with the Ant Design Tree component
> 
> ![Screen Shot 2020-12-07 at 17 02 12](https://user-images.githubusercontent.com/5524162/101337354-1d2ebf80-38ae-11eb-9a8d-395600000b26.png)

I'm facing the same problem while testing a TreeSelect component with jest and React Testing Library. How did you solve this issue ? @nvbinh
