### ISSUE TITLE
Bug: Nothing returned from renderer when returning undefined

### ISSUE THREAD

**Issue by raRaRa** [facebook/react#20089]
React version: 17.0.0

## Steps To Reproduce

1. return undefined from a React component

Link to code example:
https://codesandbox.io/s/blazing-rain-jtdzy?file=/src/App.js

## The current behavior
`Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

## The expected behavior
Nothing should be rendered like in earlier React versions.

**Comment by raRaRa** [comment]
The simple fix is of course to `return null` instead of `return undefined`, but I never saw this breaking change documented for React 17.0.0. Apologies if this is by design.

**Comment by kachkaev** [comment]
This is intentional. See https://github.com/facebook/react/issues/19548, which was closed by https://github.com/facebook/react/pull/19550

**Comment by raRaRa** [comment]
@kachkaev Thanks. I've never noticed this warning during the development of my app in React 16, very odd. I'll close this issue since this is by design.

Thanks again.
