### ISSUE TITLE
Feedback for 'exhaustive-deps' lint rule

### ISSUE THREAD

**Issue by jiangyh1024** [facebook/react#20097]
I'm using 'use-immer' package to replace useState

but this will throw 'exhaustive-deps' lint rule if using setState  method inside hook like useeffect/usecallback

eg:

const [activeTab, setActiveTab] = useImmer(0);

React.useEffect(() => {
   setActiveTab(() => 1);
}. []); // will require setActiveTab as a dependency

I know it can be solved by disabling the rule, but I don't think it is a good solution

**Comment by kachkaev** [comment]
Could you elaborate on the inconvenience you experience by keeping setActiveTab as a dependency? At our team, we also use third-party hooks and the setters (and other functions) are added to deps. This does not feel wrong or time-consuming.

In theory, there is no guarantee that a new version of `useImmer` will not start changing the reference to `setActiveTab` at some point.

**Comment by jiangyh1024** [comment]
using react.useState will not be required to add setState method as a dependency, so I thought there might be solutions to avoid this problem.  seems this rules is defined in eslint-react-hook-deps

![image](https://user-images.githubusercontent.com/34930870/97156957-64f00080-17b2-11eb-8f1c-1382e6c75601.png)

**Comment by jordyvandomselaar** [comment]
Is there a downside to adding the `setActiveTab` to your dependencies? Because it's a custom hook, React doesn't know if `setActiveTab` changes or not, thus requiring it in the dependency array.

It's the same when you pass `dispatch` from `useReducer` as a prop to a different component; even though it never changes, you have to pass it because at that moment React cannot know if it changes or not,

**Comment by gaearon** [comment]
The solution is to pass it. There is no problem doing it if it's a stable reference.

**Comment by Jayatubi** [comment]
> The solution is to pass it. There is no problem doing it if it's a stable reference.

It would be better if there could be a user config to add exclude terms for the rule.
