### ISSUE TITLE
Bug: Chrome DevTools failed to load SourceMap after upgrade to Chrome 86.0.4240.111

### ISSUE THREAD

**Issue by waynebloss** [facebook/react#20091]
React DevTools version: 4.9.0-75726fadfd

## Steps To Reproduce

1. Install React DevTools into Chrome 86
2. Observe Chrome errors loading source maps for React DevTools.

Link to code example:

`None`

## The current behavior

```log
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/injectGlobalHook.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/contentScript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

## The expected behavior

Show no errors.

## Workaround

- Disable JavaScript source maps in Chrome DevTools (Open Chrome DevTools, click three dots menu in upper right corner, find Settings under More Tools. Uncheck "Enable JavaScript source maps".)

Workarounds that don't work:

- Remove all `.map` files in `~/.config/google-chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.9.0_0/build/`.
- Remove all `.map` files from `~/.config/google-chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.9.0_0/`
- Edit each `.js` file in `~/.config/google-chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.9.0_0/build/` to remove the line with `//# sourceMappingURL=`. This changes the hash of each file and Chrome will refuse to load the extension.

## Other Notes

- OS: Manjaro Linux

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#20075) so I'm going to mark this issue as a duplicate and close it. That issue has already been fixed and the fix will be released shortly.

**Comment by mitchstewart** [comment]
For anyone facing this issue, make sure you are initializing your icons (https://github.com/microsoft/fluentui/wiki/Using-icons).

Adding this snippet to the top of my App.tsx file fixed my problem.

```
import { initializeIcons } from 'office-ui-fabric-react/lib/Icons';

initializeIcons();
```

**Comment by execptionerror** [comment]
[[Solved] DevTools failed to load SourceMap: Could not load content for chrome-extension [ 3 Working Solution ]](https://exerror.com/devtools-failed-to-load-sourcemap-could-not-load-content-for-chrome-extension/)

**Comment by marckassay** [comment]
Suspicious post, by a suspicious "user": https://github.com/facebook/react/issues/20091#issuecomment-884649559
