### ISSUE TITLE
Error: "Commit tree already contains fiber 601. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by Denisdubovikov96** [facebook/react#20101]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.9.0-75726fadfd

Component stack: CommitRankedAutoSizer@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:34248:50
div
div
div
SettingsModalContextController@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:28047:1
Profiler_Profiler@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:35614:50
ErrorBoundary_ErrorBoundary@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:29061:5
PortaledContent@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:29178:27
div
div
ProfilerContextController@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:32775:1
TreeContextController@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:24163:1
SettingsContextController@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:24652:1
ModalDialogContextController@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:29245:1
DevTools_DevTools@moz-extension://f4c154e8-040d-4fe9-b83a-727bf9edeb34/build/main.js:36048:1

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#18859) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~

**Comment by bvaughn** [comment]
@Denisdubovikov96 This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼
