### ISSUE TITLE
Question: CM mode and useEffect cleanups

### ISSUE THREAD

**Issue by maraisr** [facebook/react#20112]
Since CM mode now runs useEffects' cleanups async. Are we still guaranteed that they'll resolve in order? By that I mean, if a component get's cleanup, re-rendered and cleaned up again. That the first cleanup will resolve, before the second?

ComponentA (1) -> thrown away -> ComponentA (2) -> thrown away. Will that (2) effectively "await" on the (1) to cleanup first.

**Comment by bvaughn** [comment]
React will never stack passive effects. If there are pending effects scheduled when React starts an update– we flush the pending effects (synchronously) before continuing with the update.

Let's say we have the following component:
```js
function ExampleComponent(props) {
  useEffect(() => {
    // This effect runs after every update,
    // because there is no dependencies array.

    return () => {
      // And it returns a cleanup function.
    };
  });

  // Other stuff...
}
```

Assuming the component above gets mounted, updated, and then unmounted– the overall sequence will be:

1. The user renders a component.
1. Component is **mounted**.
1. Typically React lets the browser paint and waits until the next frame before continuing.
1. Passive effects are created for **mount**.
1. At some point, the user schedules an update.
1. Component is **updated**.
1. Typically React lets the browser paint and waits until the next frame before continuing.
1. Passive effects are destroyed for **mount**.
1. Passive effects are created for **update**.

If an update was scheduled *before* React flushed the passive effect, the overall sequence **would not change**, e.g.

1. The user renders a component.
1. Component is **mounted**.
1. A synchronous update is scheduled!
1. Passive effects are created for **mount** before the update is processed.
1. Component is **updated**.
1. Typically React lets the browser paint and waits until the next frame before continuing.
1. Passive effects are destroyed for **mount**.
1. Passive effects are created for **update**.

Hope this answers your question.

**Comment by markerikson** [comment]
@bvaughn this needs to go in the docs somewhere :)

**Comment by bvaughn** [comment]
I'm not *directly* working on the docs effort at the moment, but I'll tag @gaearon and @rachelnabors to share the feedback.

**Comment by gaearon** [comment]
>Since CM mode now runs useEffects' cleanups async

I'm not sure I understand the premise — cleanups run async in 17 in sync mode too.

**Comment by bvaughn** [comment]
I assumed this comment was inspire by our recent timing change for passive destroys after being unmounted. (Maybe that's wrong.) The overall gist of it seemed to be asking though if it was ever possible for effect destroys and creates to be interleaved because of the fact that we delay them.

**Comment by gaearon** [comment]
Yes, I just wanted to clarify for @maraisr that this behavior is unrelated to Concurrent Mode (which is mentioned in the issue title).

**Comment by maraisr** [comment]
Firstly thank you @bvaughn!! But my I guess original question still in the air?? I'm more curious, effects are cleaned up async. But still "sync" in the sense that future effects won't get created till previous have cleaned up? But sibling "unrelated" effect cleanups will run async? 

Also sorry @gaearon misunderstanding on my part as when the async cleanups were added CM or 17! 😅

**Comment by bvaughn** [comment]
> But my I guess original question still in the air?? I'm more curious, effects are cleaned up async. But still "sync" in the sense that future effects won't get created till previous have cleaned up? But sibling "unrelated" effect cleanups will run async?

Ah, sorry if my example above made things more confusing by being overly simplified 😅 

React processes all effects within a root at the same time. (It won't destroy effects for some components but leave others for later.) If a commit rendered 5 components and 3 of them had effects, all 3 of those effects will be run before React starts on another update.

**Comment by maraisr** [comment]
Ah thank you so much! So for my specific usecase:

```jsx
useEffect(() => {
    someGlobalNonReactSetUserFunction({user});

    return () => {
        someGlobalNonReactSetUserFunction(null);        
    }
}, [user])
```

I'm just wanting to confirm that the cleanup that sets the user to null, won't set it to null after the second commits init ran. But as you're saying commits won't commence till all cleanups have finished. Which means yeah, the setting of null won't ever set it to null for a second commits setting. 

> Gosh im horrible at this articulating thing... Does it come easier with practice? You do it so well!!!
