### ISSUE TITLE
Bug: Got "This browser does not have a MessageChannel implementation, so enqueuing tasks via await act(async () => ...) will fail. Please file an issue at https://github.com/facebook/react/issues if you encounter this warning." when importing npm package

### ISSUE THREAD

**Issue by StefanZetterberg** [facebook/react#20118]
I created a npm package thats a React class component. The class is jsx-class.
I don't use await, act or any async function in the component.

When running unit-test I get the message in the title and the rest of the test fails.

What am I doing wrong. I did as I was told to inform you.

React version: 16.14.0

Link to code example: 
For the npm component:
https://github.com/StefanZetterberg/Pagination

For the project itself:
https://github.com/StefanZetterberg/ReactExam

## The current behavior

I get the error message in the title and the rest of the test fails

## The expected behavior

No error message from within the imported npm-package code.

**Comment by bvaughn** [comment]
Can you create a Code Sandbox repro that shows this error?

**Comment by billyjanitsch** [comment]
You've configured your `Pagination` library to [inline and bundle all of React](https://unpkg.com/@stefan_zetterberg/pagination@1.0.7/lib/Pagination.js). In general, you shouldn't use webpack to bundle libraries, and, if you do, then you should configure [externals](https://webpack.js.org/configuration/externals/) to avoid inlining your dependencies.

Your library also [imports a testing dependency](https://github.com/StefanZetterberg/Pagination/blob/ba23d9f7a7988e6f45fa31f8af2773b28ff64ffb/src/Pagination.jsx#L3) in its source code, which is also getting inlined/bundled. This import should be removed entirely, as testing dependencies should only be used in test files.

I haven't looked if there are other issues with the setup but fixing these should get you started.

**Comment by bvaughn** [comment]
Thanks for digging in and taking a look, @billyjanitsch.

**Comment by StefanZetterberg** [comment]
Thank you so much for the help. Im a newbe as you probably figured out. I, try the changes suggested! Thank once more!

**Comment by bvaughn** [comment]
Going to close this issue for now then since it seems resolved.
