### ISSUE TITLE
Bug: iqoo

### ISSUE THREAD

**Issue by from-1314520** [facebook/react#20125]
示例：点击           后，新建Bug: iqoo #20125问题，当前编辑框属于问题发起者。 他可以随时修改、编辑问题，即使是关闭状态（他自己关闭）只有管理员标记【己确认】并关闭问题后，该问题不能再修改编辑

**Comment by iQOO-00** [comment]
换个尺寸

**Comment by bvaughn** [comment]
This issue does not appear to be about React so I'm going to close it.
