### ISSUE TITLE
Bug: Unexpected Warning "DevTools failed to load SourceMap" in Chrome

### ISSUE THREAD

**Issue by xabra** [facebook/react#20130]
I get three warnings when React DevTools is installed in Chrome.  Other people have reported this but I have not seen a good solution. (I dont use an ad blocker)

DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/injectGlobalHook.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/contentScript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)

React version:
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.3"

Also using Apollo Client

## The current behavior
The above warnings are generated on every render for every page.

## The expected behavior
No warnings

## Files

----index.js file ----
import React from "react";
import { render } from "react-dom";
import { BrowserRouter } from "react-router-dom";
import {
  ApolloClient,
  InMemoryCache,
  createHttpLink,
  ApolloProvider,
} from "@apollo/client";

// Top level view.  Does the setup of the Apollo Provider and renders the App
import App from "./App";

const link = createHttpLink({
  uri: "http://localhost:4000",
  headers: { authorization: localStorage.getItem("token") },
});
const cache = new InMemoryCache();
const client = new ApolloClient({
  link: link,
  cache: cache,
});

render(```
  <ApolloProvider client={client}>
    <BrowserRouter>
      <div>
        <App />
      </div>
    </BrowserRouter>
  </ApolloProvider>,```
  document.getElementById("root")
);

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#20091) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
