### ISSUE TITLE
React Developer Tools triggers console error in Firefox for protected URLs

### ISSUE THREAD

**Issue by SimonSiefke** [facebook/react#20144]
![Screenshot from 2020-11-02 08-34-31](https://user-images.githubusercontent.com/23744935/97845488-ea147180-1cec-11eb-853a-0b6e3c176903.png)

## Steps To Reproduce

1. Install React Devtools extension for Firefox
2. Go to "about:neterror?e=connectionFailure"

## The current behavior

Firefox shows this error in the console: "The extension "React Developer Tools" is not allowed to access about:neterror?e=connectionFailure"

## The expected behavior

Firefox shows no error in the console

**Comment by bvaughn** [comment]
Related to PR #20023

I'm not aware of a reliable way to detect special/protected URLs like "about:neterror" in Firefox and prevent React DevTools from treating it like any other page. If you know of a way, please shoot us a PR!

**Comment by sktguha** [comment]
Hi, author of the above PR here. 
To add to Brian's comment, so I think in the code here: https://github.com/facebook/react/blob/1b96ee444e544cc4797bbbd8dee249ff02d62279/packages/react-devtools-extensions/src/background.js#L108 
When we try to access `tab.status` in firefox, if it is a protected page, firefox will throw an error
If that is the case, I don't think we can really do anything at all. If we try to access the tab.url to see if its a protected page, before that check only firefox will throw the same error

Maybe wrapping the code in a try catch could work ? But I doubt it
@SimonSiefke maybe you could possibly step through in a debugger in firefox and check that the above thing happens and/or verify the try catch theory ?

In chrome and edge however this issue doesn't happen. Infact it is possible to read the `tab.url` of a protected page like chrome://extensions etc from any extension.

**Comment by arshdev16** [comment]
Apparently, I only get this error when I go to `localhost:3000` without turning on the dev server `yarn dev`
