### ISSUE TITLE
Bug: Issue using pullstate in React hooks.

### ISSUE THREAD

**Issue by Harish-Sridhar** [facebook/react#20146]
I am using Pullstate to store and retrieve state in my applicaiton.
Pullstate store has a method named useState to retrieve the current value of the state.
the problem is, when i use the useState method of the pullstate store inside React hooks.
React application is crashing stating that i have wrongly invoked hooks.

React version: 16.13.1

## Steps To Reproduce
Pull state store

```
import { Store } from "pullstate";

export const PublishStateStore = new Store({
  searchedWord: '',
});
```

React app
```
useEffect(()=>{
    const abc = PublishStateStore.useState(s => s.searchedWord)
    console.log(abc)
})
```

Error message:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
▶ 4 stack frames were collapsed.
(anonymous function)
src/components/DynamicWordForm.jsx:103
  100 | }
  101 | 
  102 | useEffect(()=>{
> 103 |     const abc = PublishStateStore.useState(s => s.searchedWord)
  104 |     console.log(abc)
  105 | })
  106 | 
View compiled
▶ 13 stack frames were collapsed.
```

**Comment by gaearon** [comment]
Hooks can only be called at the top level. You are not using them correctly (the same applies to custom Hooks).

https://reactjs.org/docs/hooks-rules.html

**Comment by gaearon** [comment]
You probably want this:

```js
const abc = PublishStateStore.useState(s => s.searchedWord)
useEffect(()=>{
    console.log(abc)
})
```

**Comment by Harish-Sridhar** [comment]
Hi @gaearon 

I haven't used any custom hooks.
The `useState` is a method provided by `pullstate` library to get the current value from the state backend.
pullstate is an state backend library for javascripts.

I am able to update the state of `pullstate` backend using `update` method from within the react hooks.
My guess is since the pullstate methos starts with the keyword `use` react is considering it as a hook.

**Comment by Harish-Sridhar** [comment]
I think the library `pullstate` is based on react and uses react hooks to maintain state.
https://lostpebble.github.io/pullstate/
> Ridiculously simple state stores with performant retrieval anywhere in your React tree using React hooks
I think this explains the problem...

**Comment by gaearon** [comment]
>The useState is a method provided by pullstate library to get the current value from the state backend.

This is called a "Custom Hook". Custom Hooks still need to obey the same rules.
