### ISSUE TITLE
Bug: Event trigger order

### ISSUE THREAD

**Issue by eduardocque** [facebook/react#20142]
When i attach events with the ref, the order when the event is triggered works incorrectly,
the real scenario is when i have a HOC and i want to add a event from that HOC into child

React version: 17.0.1

## Steps To Reproduce

1. https://codesandbox.io/s/lucid-ramanujan-te33q
2. Check the code, test it and check the in console the order of the logs
3. Comment `onClick` and uncomment `ref=..` and compare the order of the logs

![Screenshot from 2020-11-01 19-37-59](https://user-images.githubusercontent.com/35545218/97812567-ef84a400-1c79-11eb-8ba7-731c85083fd7.png)

## The current behavior

logs should be 
* Click 1
* Click 2

## The expected behavior

logs should be 
* Click 2
* Click 1

@gaearon instead do
`node.addEventListener("click", this.handleClick);` can be possible to introduce in ReactDOM or React a way to set up triggers just sending the REF / NODE (DOM) ? to be added in react lifecycle

**Comment by gaearon** [comment]
Have you edited sandbox? Both logs show “click 2” now which is probably not what you intended.

**Comment by eduardocque** [comment]
@gaearon sorry try again

**Comment by eduardocque** [comment]
@gaearon basically i added a listener in the node div (using the ref), and a normal trigger with onClick in the button, if u trigger the button this will trigger first the div instead the button first (is a wrong order)

**Comment by gaearon** [comment]
Current behavior is expected because React uses event delegation. So React-managed events are actually attached to the root.
