### ISSUE TITLE
Bug: -webkit-calc doesn't work with var() when compiling css

### ISSUE THREAD

**Issue by phoenixVS** [facebook/react#20158]
React version: 16.13.1

Link to code example:
https://codesandbox.io/s/gifted-leftpad-j80id?file=/src/styles.css

PS: when i've tried to use -webkit-calc without var() npm run build worked

**Comment by eps1lon** [comment]
Thanks for the report. 

This appears to be an issue with `create-react-app` not React itself. This repository is for bugs related to actual React. 

Please open a [new issue on create-react-app](https://github.com/facebook/create-react-app/issues/new/choose). I would suggest describing the actual and expected output.
