### ISSUE TITLE
Bug: In SSR, Props didn't update when server and client has diff in diffHydratedProperties.

### ISSUE THREAD

**Issue by YardWill** [facebook/react#20152]
React version: 16.14.0

1. Create a server side render App. (or just use nextjs)
2. Create a component with below code. (make value different by using browser feature like cookie)

```
import React from 'react'
import c from 'js-cookie'

const Index = () => {
  return <div accessKey={c.get('a')}>{c.get('a')}</div>
}

export default Index
```

Link to code example:

Because of server side render. There is no sandbox link.

## The current behavior

Text Node updated but accessKey props didn't updated.

## The expected behavior

Text Node updated and accessKey props updated.

**Comment by gaearon** [comment]
React does not patch up the attribute differences because for the vast majority of cases it would be extra unnecessary work in production. You need to ensure that the initial markup is the same on the first client render. Then you can update the state to reflect what you get from the cookie.
