### ISSUE TITLE
Bug: setState triggers unexpected console.log behavior

### ISSUE THREAD

**Issue by ChuanyuanLiu** [facebook/react#20156]
## The bug

The use of `setList` seems to trigger unexpected console.log behaviour. In this example, react renders (line 27) and console.log (line 28) receive the same `listString` as an argument, but the output is different!

```javascript
function App() {
  const [list, setList] = useState([0, 1]);
  const [isAscending, toggle] = useReducer((isAscending) => !isAscending, true);
  // update the order of the list
  // mutating the list directly, which does not trigger a re-render
  useEffect(() => {
    if (isAscending) {
      setList(list.sort((e1, e2) => e1 - e2));
    } else {
      setList(list.sort((e1, e2) => e2 - e1));
    }
  }, [isAscending]);

  // capture the snaphot of the current list
  const listString = JSON.stringify(list);
  // render
  // The problem is that line 27 and 28 receives the same string
  // but display differently.
  return (
    <div>
      <button onClick={toggle}>
        {isAscending ? "Ascending" : "Descending"}
      </button>
      {"<= Click me"}
      {console.log("list should be", listString, "with setList")}
      <h1>list: {listString} with setList</h1>
    </div>
  );
}
```

## The current behavior (Bad)

1. Go to [Codesandbox: console log and html output are different WITH setList](https://codesandbox.io/s/console-log-and-html-output-are-different-with-setlist-dxz9g?file=/src/App.js)
2. Open console
3. Click on the button on HTML
4. Observe what is shown on HTML is different from what is console.logged

[Video demo: with setlist](https://streamable.com/v9meww)

## The expected behavior (Good)

1. [Codesandbox: console log and html output are same WITHOUT setList](https://codesandbox.io/s/console-log-and-html-output-are-same-without-setlist-mjepj?file=/src/App.js)
2. Open console
3. Click on the button on HTML
4. Observe what is shown on HTML is different from what is console.logged

[Video demo: without setlist ](https://streamable.com/udvi5q)

**Comment by bvaughn** [comment]
`Array.prototype.sort` mutates the array in place, so when you call `setList` you are calling it **with the same array** and so React bails out without committing the update. [This is not supported.](https://reactjs.org/docs/hooks-faq.html#is-there-something-like-forceupdate)

What you *should* be doing is cloning the array before updating state, [like so](https://codesandbox.io/s/console-log-and-html-output-are-different-with-setlist-forked-p75o3).

Hope this helps

**Comment by ChuanyuanLiu** [comment]
Hi. I think you misunderstood the problem.

When React bail without committing the update, it affects things that have nothing to do with the updates state!
>  (line 27) and console.log (line 28) receive the same listString as an argument, but the output is different!

By your logic and documentation, bail without update should not result in line 27 and line 28 having a different output. But it does.
