### ISSUE TITLE
Bug: using hooks in an IIFE breaks rules of hooks

### ISSUE THREAD

**Issue by mikemfleming** [facebook/react#20157]
React version: 16.11.0

## Steps To Reproduce

1. Call a hook in an IIFE
2. See that it throws a hooks use error

Link to code example: https://codesandbox.io/s/serene-darkness-kf26m?file=/src/App.js

## The current behavior
This code throws an error. 
  ```
  6  export const ModalContext = createContext((() => {
  7   const [isVisible, setIsVisible] = useState(false)
  8
  9   return {
 10     isVisible,
 11     toggleVisibility: () => setIsVisible(!isVisible)
 12   }
 13 })())
```

## The expected behavior
No error thrown, the exported `SidebarContext` contains a state variable and an api method to update it.

**Comment by bvaughn** [comment]
Why do you expect this to work?

You're calling a function (that calls hooks) outside of render. This isn't supported and the error message explains that.

**Comment by bvaughn** [comment]
Going to close this issue because it looks like a misunderstanding. We can chat more if something is unclear though.

**Comment by mikemfleming** [comment]
Thanks for the speedy response! I really appreciate your help. Here's a little more info, let me know if you need to see a code sample.

I have a page (the closest ancestor) that has many buttons on the ui (cousins to the modal) that should trigger the component to render. There are a lot of levels of nesting between the ancestor and the cousins so I feel like the context api is right for this.

The problem with the `useCustomHook` approach is that it provides a new instance of the sidebar state whenever it's called. The sidebar state needs to be synchronized in the parent, cousins, and sidebar itself. 

Is this an anti pattern? How else can I create a hook that can control the sidebar from the cousins without drilling down props?

**Comment by bvaughn** [comment]
> The problem with the `useCustomHook` approach is that it provides a new instance of the sidebar state whenever it's called. The sidebar state needs to be synchronized in the parent, cousins, and sidebar itself. 

I'm not sure I understand but from what you've said, I imagine `useCallback` or `useMemo` (or even a non-React memoization utility) could work for this.
