### ISSUE TITLE
Bug: devtools the expanded state and the state object are out of sync

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [facebook/react#20178]
React version: 16.13.1

## Steps To Reproduce

1. Have a Switch with state in react native and toggle the switch by opening devtools and using the checkbox provided for the state.
2. Now toggle the switch using UI. the state object gets updated but not the expanded one.

Link to code example:

## The current behavior
Allergies state is true on the top but on expanded state it is false.
![Screenshot from 2020-11-06 16-48-37](https://user-images.githubusercontent.com/16081083/98360786-7bb71280-2050-11eb-8a52-0944a6b70c26.png)

## The expected behavior
Both must be in sync

**Comment by brettgoulder** [comment]
I am not seeing a code example link. Can you please update with one?

**Comment by a-c-sreedhar-reddy** [comment]
Found this with react native devtools
