### ISSUE TITLE
React datepicker autoComplete not working

### ISSUE THREAD

**Issue by sampath1992331** [facebook/react#20175]
`<DatePicker 
                                            id="BusinessRegisteredDate"
                                            className="form-control mandatory"
                                            //value={this.state.BusinessRegisteredDate}                                           
                                            selected={this.state.BusinessRegisteredDate}
                                            autoComplete="false" 
                                            showYearDropdown
                                            showMonthDropdown
                                            maxDate={new Date().getTime()}
                                            onKeyDown={(e) => this.restrictKeyUpDown(e)}
                                            onChange={this.BusinessRegisteredDateOnchange} 
                                            required
                                        />``
Link to code example:

![Uploading ssssssss.JPG…]()

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by sampath1992331** [comment]
![ssssssss](https://user-images.githubusercontent.com/26246790/98434689-030b9100-20f8-11eb-9bc1-fe0e8220920d.JPG)
issue auto complte = true not working

**Comment by bvaughn** [comment]
@sampath1992331 This issue doesn't have enough info for anyone to look into. The `DatePicker` component you're referring to is not part of React, so the bug you're reporting is just as likely to exist in whatever third party library you're using.

From the props you've listed, and a Google search, I'm guessing it's maybe [this library](https://github.com/Hacker0x01/react-datepicker)? I suggest you start by filing the bug report with that library:
https://github.com/Hacker0x01/react-datepicker/issues/new/choose

I'm going to close this issue as not-actionable for now.
