### ISSUE TITLE
Inconsistency in hooks order using a JSX tag vs a function call

### ISSUE THREAD

**Issue by enigma1** [facebook/react#20195]
Seems to me there is an inconsistency how react detects the hooks ordering when wrapping a component. I created a demo where the first render goes through the wrapper into Component1 while the 2nd render goes through Component2. In one case it detects render phases are inconsistent but in the other case it doesn't. And the difference is when using a function call vs component JSX notation. The usual warning is:

_Warning: React has detected a change in the order of Hooks called by null. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks_

Now there are other reports of discouraging the use of function call in this case but there is a difference because here there is no "key" or "iterations" involved with a set of component calls.

In order to see the behavior in the sample change

```
whichComponent.current()
```
into 
```
<whichComponent.current />
```
and there is no longer a hooks ordering problem. Another thing is that if you do use the same hooks, the difference is not detected even in the function call case. There is a commented line in Component1 for useRef. Uncommenting it will also show no warning although the hooks are not really the same as the components are different.

React version:
16.3+

## Steps To Reproduce
1.  Create a couple of components using different hooks
2. Use a wrapper and a switcher to change component
3. Switch between a jsx tag and a function call and see the different behavior.

Link to code example:

https://codesandbox.io/s/nice-wood-n02eq

## The current behavior
Not detecting the hooks difference when a JSX tag us used.

## The expected behavior
I would expect to have the hooks difference spotted the same way, with react detecting whether the component is the same before issuing the warning, or at least to have the behavior difference documented.

**Comment by vkurchatkin** [comment]
> and there is no longer a hooks ordering problem

And it shouldn't be. In the second example a different component is render. It can have its own hooks, can be mounted or unmounted. All of this is allowed.

> whichComponent.current()

Here you are calling hooks in the context of the current component, which can be a problem.

By the way, both `whichComponent.current()` and  `<whichComponent.current />` are incorrect anyway: you shouldn't read from refs during render, because it makes rerenders non-deterministic

**Comment by enigma1** [comment]
@vkurchatkin, in both cases the same (second) component is rendered. You can uncomment in Component1 the ref line, you will see Component2 html is rendered. That's the expected behavior. The unexpected thing, is react doesn't check if indeed is the same component that uses different hooks.

**Comment by vkurchatkin** [comment]
>  in both cases the same (second) component is rendered. 

no. This: 

`whichComponent.current()`

doesn't render the second component. It renders its _contents_ in the first component.

**Comment by gaearon** [comment]
It is not supported to "call" a component as a function. The only valid way to render a component is to render an element with its type. Such as `<MyComponent />` or `React.createElement(MyComponent)`. This should make sense considering a component could also be a class — which wouldn't work when "called" either.

I don't quite understand why the original sandbox uses this "replacer" pattern and what the real use case is, but here's a working version: https://codesandbox.io/s/lingering-dew-8d5qm

>Now there are other reports of discouraging the use of function call in this case but there is a difference because here there is no "key" or "iterations" involved with a set of component calls.

"Calling through" different components is equivalent to conditionally rendering Hooks inside of them. This is why it's not supported.

**Comment by enigma1** [comment]
ok cool, thanks for all responses.
