### ISSUE TITLE
Error: "Commit tree does not contain fiber 1527. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by WilliamCSA04** [facebook/react#20197]
Describe what you were doing when the bug occurred:
1. Go to profile tag
2. Click to record
3. After stop recording, click on any commits.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.9.0-75726fadfd

Component stack: CommitFlamegraphAutoSizer@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:33986:50
div
div
div
SettingsModalContextController@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:28047:1
Profiler_Profiler@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:35614:50
ErrorBoundary_ErrorBoundary@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:29061:5
PortaledContent@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:29178:27
div
div
ProfilerContextController@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:32775:1
TreeContextController@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:24163:1
SettingsContextController@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:24652:1
ModalDialogContextController@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:29245:1
DevTools_DevTools@moz-extension://7ef91e4d-0a91-434a-b6fa-c2646d78406c/build/main.js:36048:1

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#18859) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~

**Comment by bvaughn** [comment]
I thought this issue was a duplicate and already resolved, but I believe I was mistake. Re-opening.

**Comment by WilliamCSA04** [comment]
> 
> 
> I thought this issue was a duplicate and already resolved, but I believe I was mistake. Re-opening.
> 
> Repro info would be very helpful, @WilliamCSA04.

I'm no longer getting this error. I did try just now to reproduce and I could not, maybe was fixed? Not sure, but was just like I described before. Once you were on the `profile` tab, you clicked on `Start profiling` and after stopped profiling, you went to that vertical bars and click on any of them.
![image](https://user-images.githubusercontent.com/12972870/99074912-5f0e6380-2597-11eb-8ad1-e235ded3ceee.png)

**Comment by bvaughn** [comment]
Yeah, I think the repro case would involve profiling some specific kind of app or interaction with an app. That's the part I'm missing. Starting and stopping the profiler is something I do all the time and I haven't seen the bug we're talking about unfortunatey.

**Comment by bvaughn** [comment]
I think the underlying cause of this is the same as #16493 which I now have a repro for.

**Comment by bvaughn** [comment]
Quick question for folks who are seeing this bug in your app: Are you using the `React.Lazy` component?

**Comment by bvaughn** [comment]
If you can repro this yourself, would any of you be willing to try this build of DevTools and let me know if it fixes the issue?

https://github.com/facebook/react/files/5644517/ReactDevTools.zip

I have reason to suspect that *maybe* I've fixed at least one case of this already (recently, unreleased) and I'm wondering if that's why I'm having trouble reproing.

**Comment by bvaughn** [comment]
I believe this issue was fixed via PR #20362. It has now been published as v4.10.1 and should be available shortly.

Please let me know if you still see the issue after installing that version and I can re-open and investigate further.

**Comment by bvaughn** [comment]
@WilliamCSA04 This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼
