### ISSUE TITLE
Bug: Module 

### ISSUE THREAD

**Issue by Mistik** [facebook/react#20207]
Hi

I saw you are using the detect-node module.

Actually this module is about to be depreciated so I would suggest moving to the nodejs-detector module instead. No API changes needed!

**Comment by gaearon** [comment]
It's not clear what package you're referring to. React doesn't use `detect-node`.

**Comment by bvaughn** [comment]
React uses `detect-node` indirectly because of `webpack-dev-server`.

@Mistik has been leaving this same comment (promoting their own `detect-node` package) on several open source repos in the last few days. I'm going to close this.
