### ISSUE TITLE
Bug: hydration does not work correctly with SSR (keeps unwanted attributes) in a real simple reproducible case

### ISSUE THREAD

**Issue by lucax88x** [facebook/react#20213]
When we try to hydrate a SSR html with a component that has the same structure, it keeps the attributes from the server even if they're not present in the client component

React version: Both 16.14 and 17.01

## Steps To Reproduce

1. get some static html
2. hydrate the html with a component
3. you will notice that the attributes in the static html are maintained even if the component do not have / use these attributes. 

PS: if the client component uses a different html structure (for example server has a DIV and client has a P) it will not keep the attributes.

Link to code example:

really simple reproducible sandbox: https://codesandbox.io/s/bitter-voice-lmvo5?
real world example with nextjs and emotionjs: https://github.com/lucax88x/nextjsemotionrepro

## The current behavior

The client component, which has a div without any class, it gets the class from the div coming from server. (the class foo in the example)

## The expected behavior

The client component should hydrate correctly and strip any server attribute (the class foo in the example)

**Comment by bvaughn** [comment]
React expects the same thing to be rendered (including attributes) on both server and dev. It even logs a warning (in DEV) if they don't match, as your sandbox is showing:
```
Warning: Text content did not match. Server: "SSRed with hotpink color." Client: "Client content without hotpink color."
    in div (at App.js:4)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```
React does not diff attributes in production mode. This was an intentional decision to improve performance of hydration. It expect you to see the warnings in DEV and fix them.
