### ISSUE TITLE
Refactor: Can I use mountReducer to refactor mountState?

### ISSUE THREAD

**Issue by sweetliquid** [facebook/react#20222]
I noticed that `updateState` uses `updateReducer` internally like this:

https://github.com/facebook/react/blob/12627f93b5357032881412abcc014da53a0b70f8/packages/react-reconciler/src/ReactFiberHooks.old.js#L1139-L1143

but in `mountState`, it was reimplemented:

https://github.com/facebook/react/blob/12627f93b5357032881412abcc014da53a0b70f8/packages/react-reconciler/src/ReactFiberHooks.old.js#L1114-L1137

Can I refactor `mountState` to use `mountReducer`?

```javascript
function mountState<S>(
  initialState: (() => S) | S,
): [S, Dispatch<BasicStateAction<S>>] {
  if (typeof initialState === 'function') {
    // $FlowFixMe: Flow doesn't like mixed types
    initialState = initialState();
  }

  return mountReducer(basicStateReducer, initialState);
}
```

**Comment by jordyvandomselaar** [comment]
Hi @sweetliquid would you mind explaining why you'd need this? Even if you could, it's probably not a good idea to mess with the internals =)

Maybe  I can suggest an alternative.

**Comment by gaearon** [comment]
Looks like there are some differences now.
