### ISSUE TITLE
Bug: Peer dependency change between use-subscription 1.4.1 and 1.5.0

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/react#20224]
React version: `use-subscription@1.5.0`

## Steps To Reproduce

1. Run `npm install react@16.14.0 use-subscription@1.4.1`. 
2. Run `npm install use-subscription@1.5.0`. Note the React peer dependency error.

Notably, this currently affects `npm install react@16 next@10` (see https://github.com/vercel/next.js/issues/18518). `npm@7` will refuse to perform this installation entirely.

## The current behavior

`use-subscription@1.4.1` peer-depends on `react@^16.8.0` whereas `use-subscription@1.5.0` peer-depends on `react@^17.0.0`, which is generally considered a breaking change in a minor version. This might have been an oversight in how https://github.com/facebook/react/pull/20062 interacted with https://github.com/facebook/react/pull/19373?

(It's considered a breaking change because a package.json like the below should always result in a valid install.) 

```json
{
  "dependencies": {
    "react": "^16.14.0",
    "use-subscription": "^1.4.1"
  }
}
```

## The expected behavior

Here are two potential solutions:

- Cut a release of `use-subscription@1.5.1` that peer-depends on `^16.8.0 || ^17.0.0`, strictly widening the peer dep range from that of 1.4.1.
- Cut a major release of `use-subscription@2` that peer-depends on `^17.0.0`, and cut a release of `use-subscription@1.5.1` that reverts its peer dependency to `^16.8.0`.

**Comment by gaearon** [comment]
Happy to take a PR that fixes this by making the range more permissible. I think we need a bump after that to increase the major and simply keep `use-subscription@2` 17-only.

If you send a PR like this, please check if any of the other React packages had a similar problem with 17.

**Comment by billyjanitsch** [comment]
>If you send a PR like this, please check if any of the other React packages had a similar problem with 17.

Sure, I'll send a PR.

I noticed a few similar cases in https://github.com/facebook/react/pull/19373 but they all seemed to be for "internal"/"experimental" packages:
- `react-cache`
- `react-client`
- `react-debug-tools`
- `react-fetch`
- `react-interactions`
- `react-native-renderer`
- `react-noop-renderer`
- `react-server`
- `react-transport-dom-relay`
- `react-transport-dom-webpack`

Do you care about fixing these since they (AFAIK) don't really have public consumers?

**Comment by billyjanitsch** [comment]
(Retitling per your comment https://github.com/vercel/next.js/issues/18518#issuecomment-725699186 and my reply https://github.com/vercel/next.js/issues/18518#issuecomment-725713224. Sorry about that.)

**Comment by gaearon** [comment]
`use-subscription@1.5.1`
