### ISSUE TITLE
can React support feature like keep-alive in Vue?

### ISSUE THREAD

**Issue by livelyPeng** [facebook/react#20221]
can React support feature like keep-alive in Vue?

**Comment by maraisr** [comment]
what is "keep-alive" and how does it benefit React?

**Comment by livelyPeng** [comment]
Cache the page before saving the page and so on. I don't want to use Redux to store it. Because we need to cache a lot of pages!

**Comment by maraisr** [comment]
I don't think React itself has a concept of a "page". So you're wanting to cache a component?

**Comment by livelyPeng** [comment]
yes , We need to cache a lot of components. If we use Redux to store data, I feel it is very troublesome

**Comment by livelyPeng** [comment]
yes，We need to cache a lot of components. If we use Redux to store data, I feel it is very troublesome




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marais Rossouw"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 上午10:56
收件人: "facebook/react"<react@noreply.github.com&gt;; 
抄送: "travel96"<403802162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [facebook/react] can React support feature like keep-alive in Vue? (#20221)





 
I don't think React itself has a concept of a "page". So you're wanting to cache a component?

**Comment by ChamsBouzaiene** [comment]
can you please explain more what you mean by caching a component ? what do you want to achieve exactly

**Comment by bvaughn** [comment]
Caching is not something React itself would do, but something that could be added outside of React. create-react-app used to use service workers to cache the page (as you mention) but it [caused a lot of confusion](https://stackoverflow.com/questions/49604821/cache-busting-with-cra-react) and so it was disabled by default in version 2. (It can be enabled by a config parameter though.)

**Comment by gaearon** [comment]
I think the question here is not about “caching” (this is a slightly different framing). The feature, if I understand correctly, lets you preserve state for unmounted components in case they remount later. This is something we’re actively looking into although I’m not familiar with Vue semantics to tell if it’s going to be similar.

**Comment by sktguha** [comment]
I think a feature request label can be added to this issue. (I don't have rights to do it)

Also Maybe "hibernating" a component is a more proper term for this ? I think the benefit would be that the hibernated component is not consuming memory for its DOM and other things. But then probably more lifecycle methods and/or hooks may  need to be there like onHibernated and onResumed etc or will the component have no idea that it is being cached/hibernated ?

However this seems to be solvable by HOC or something. If I am not wrong, React's policy is to resist adding features that can be solved in userland correct ?

**Comment by bvaughn** [comment]
If this request is actually more about "hibernating" a component (retaining its state while it is not visible in the DOM) then we are already working on an API for this. (You can see mentions of it on issues like #13206 which refer to an "offscreen API".) We will share more info about it soon.

**Comment by sktguha** [comment]
> If this request is actually more about "hibernating" a component (retaining its state while it is not visible in the DOM) then we are already working on an API for this.

Sorry I don't know this. I am not the OP. I just added some thoughts of mine

**Comment by bvaughn** [comment]
Understood. Was just adding more context to yours and Dan's comments above.

**Comment by sktguha** [comment]
The offscreen API seems interesting. "retaining its state while it is not visible in the DOM", this happens even today right ? I mean we can simply hide the div by display:none etc , containing the component. So I guess offscreen API does something like deleting the dom nodes to save memory. But I think some kind of throttling must be there, in case of too many calls/passing the hibernate prop within a short time to hide and show the element.

will await further info on this ,whenever the React team releases more info on this

**Comment by livelyPeng** [comment]
@sktguha If you use it every time display:none Hidden, to achieve component cache, then I need to cache dozens of pages. Will node hiding lead to too many nodes?

**Comment by sktguha** [comment]
@livelyPeng indeed I am afraid it will. The browser might optimise somewhat , but still definitely some cost will be there.

You can make an HOC for this however, the HOC needs to connect to Redux at one place only.

**Comment by livelyPeng** [comment]
thank you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Saikat Guha"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 上午10:06
收件人: "facebook/react"<react@noreply.github.com&gt;; 
抄送: "travel96"<403802162@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [facebook/react] can React support feature like keep-alive in Vue? (#20221)





 
@livelyPeng indeed I am afraid it will. The browser might optimise somewhat , but still definitely some cost will be there.
 
You can make an HOC for this however, the HOC only needs to connect to Redux at one place only.

**Comment by w602542704** [comment]
> can React support feature like keep-alive in Vue?

If you don't look at the implementation, you can use Electron to develop, prohibit refreshing!

**Comment by bvaughn** [comment]
It seems like this issue has kind of reached a conclusion of sorts, so I'm going to close it. Discussion can continue on it though if there's still open questions.

**Comment by sktguha** [comment]
Ok while we are on the topic of features like Vue, 
was there any discussion even done for something like v-model ( https://v3.vuejs.org/guide/forms.html#form-input-bindings ) in React 😄.
Seems quite handy and does handles a fair amount of things under the hood.

**Comment by bvaughn** [comment]
I think it's helpful to keep an issue focused on a specific topic (in this case, caching).

I suggest searching the repo issues to see if the thing you've mentioned has been discussed, or checking out external forums like the ones on [https://reactjs.org/community/support.html](https://reactjs.org/community/support.html#popular-discussion-forums)

**Comment by sktguha** [comment]
> I think it's helpful to keep an issue focused on a specific topic (in this case, caching).
> 
> I suggest searching the repo issues to see if the thing you've mentioned has been discussed, or checking out external forums like the ones on [https://reactjs.org/community/support.html](https://reactjs.org/community/support.html#popular-discussion-forums)

ok understood
