### ISSUE TITLE
Bug: After quoting "react-file-viewer": "^1.2.1" plug-in, the project packaging is particularly slow, how to effectively speed up

### ISSUE THREAD

**Issue by wanghx123** [facebook/react#20231]
React version:16.13.1

## Steps To Reproduce

1.npm run build

**Comment by eps1lon** [comment]
Thanks for the report.

This is most likely an issue with `react-file-viewer` which is not published from this repositories. I suggest you open an [issue in their repository](https://github.com/plangrid/react-file-viewer/issues).

**Comment by wanghx123** [comment]
> 感谢您的报告。
> 
> 这很可能是一个`react-file-viewer`没有从此存储库发布的问题。我建议您[在他们的资料库中](https://github.com/plangrid/react-file-viewer/issues)打开一个[问题](https://github.com/plangrid/react-file-viewer/issues)。

thanks
