### ISSUE TITLE
Bug: react-hook: value of useState doesn't change when use with useContext and render props

### ISSUE THREAD

**Issue by Kyi-Moe-Min** [facebook/react#20230]
value of useState doesn't change in inner function that pass to props of render props component but change in DOM and normal call. (it is working fine with class component)

React version: 17.0.0

## Steps To Reproduce

context.js

```js
import { createContext } from "react";

export const Context = createContext({ showModal: (func) => {} });
```

FunctionalChild.js

```js
import React, { useContext, useEffect, useState } from "react";
import { Context } from "../context";

export function FunctionalChild() {
  const { showModal } = useContext(Context);
  const [count, setCount] = useState(0);
  useEffect(
    () =>
      showModal((close) => {
        return <button onClick={increaseCount}>+</button>;
      }),
    []
  );

  console.log("count:", count);

  return <div>current count{count}</div>;

  function increaseCount() {
    setCount((c) => c + 1);
    console.log("functional child", count); //! this count is always showing initial value
  }
}
```

Parent.js

```js
import React, { useState } from "react";
import { Context } from "../context";
import { FunctionalChild } from "./FunctionalChild";

let modalComponent;

export default function ParentComponent() {
  const [visible, setVisible] = useState(false);

  function close() {
    setVisible(false);
  }

  function showModal(func) {
    modalComponent = func(close);
    setVisible(true);
  }

  return (
    <Context.Provider value={{ showModal }}>
      <FunctionalChild />
      {visible && <div className="modal">{modalComponent}</div>}
    </Context.Provider>
  );
}
```

as above codes the value of `count` in `increaseCount` function is always showing initial value `0` and doesn't change at all. but got updated value at `console.log("count:", count)` normal call and it's also got updated value in DOM.

Link to code example: https://codesandbox.io/s/usestate-hook-odw3e  
you can check the behavior of both class and functional component in this link

## The current behavior

value of useState doesn't get update value in function that pass to render props component

## The expected behavior

to get the correct updated value of useState in function that pass to render props component

**Comment by eps1lon** [comment]
Thanks for the report. 

The behavior is intended since you forgot to add `increaseCount` as a dependency to `useEffect`. In codesandbox you should see this orange squiggly line which tells you do add `increaseCount`. Right now you're "closing" over the first version of `increaseCount` which closes over the first version of `count` which is 0. "Closing over" is derived from [closures](https://whatthefuck.is/closure).

You can learn more about [useEffect usage in the docs](https://reactjs.org/docs/hooks-reference.html#useeffect)

**Comment by Kyi-Moe-Min** [comment]
@eps1lon thanks for the suggestion, but still, the problem is not solved. it is still showing the initial value `0` and doesn't change even after I updated the code as you suggested.
