### ISSUE TITLE
DevTools: Flag "nested updates" in the Profiler UI

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#20236]
PR #20163 added a new (not yet released) phase to the Profiler API: `"nested-update"`. This phase is different from a regular `"update"` because of the performance implications (see PR description for more background info).

Would be nice if we could also flag these in the DevTools UI somehow.

**Comment by markerikson** [comment]
purely as a reminder/FYI, React-Redux has always relied on this kind of a pattern to ensure top-down updates in `connect`.

`useSelector` doesn't do that, but that means it suffers from the potential "stale props" and "zombie child" concerns:

https://react-redux.js.org/api/hooks#stale-props-and-zombie-children

no idea how that will end up changing with `useMutableSource` down the road.

**Comment by bvaughn** [comment]
`useSubscription` and `useMutableSource` both check for changes in a passive effect, to avoid stretching the commit phase. It may seem more intuitive to use a layout effect so that you don't "miss" an update but it wouldn't actually guarantee that in concurrent mode, because you might miss an update during render (e.g. while React has yielded).

One important thing `useMutableSource` does is ensure that nothing tears *within the render* – so even if you "miss" an update between render and commit, it will catch it later (during passive effects phase) and schedule an update for it. No big deal so long as nothing tears during the render (which it has checks to prevent).
