### ISSUE TITLE
Bug: peerDeps react in react-test-renderer has a massive minor bump 

### ISSUE THREAD

**Issue by ktalebian** [facebook/react#20238]
Take a look at these two versions of react-test-renderer

```json
{
  "name": "react-test-renderer",
  "version": "16.12.0",
  "description": "React package for snapshot testing.",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/react.git",
    "directory": "packages/react-test-renderer"
  },
  "keywords": [
    "react",
    "react-native",
    "react-testing"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/facebook/react/issues"
  },
  "homepage": "https://reactjs.org/",
  "dependencies": {
    "object-assign": "^4.1.1",
    "prop-types": "^15.6.2",
    "react-is": "^16.8.6",
    "scheduler": "^0.18.0"
  },
  "peerDependencies": {
    "react": "^16.0.0"
  },
  "files": [
    "LICENSE",
    "README.md",
    "build-info.json",
    "index.js",
    "shallow.js",
    "cjs/",
    "umd/"
  ]
}
```

and

```json
{
  "name": "react-test-renderer",
  "version": "16.13.1",
  "description": "React package for snapshot testing.",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/react.git",
    "directory": "packages/react-test-renderer"
  },
  "keywords": [
    "react",
    "react-native",
    "react-testing"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/facebook/react/issues"
  },
  "homepage": "https://reactjs.org/",
  "dependencies": {
    "object-assign": "^4.1.1",
    "prop-types": "^15.6.2",
    "react-is": "^16.8.6",
    "scheduler": "^0.19.1"
  },
  "peerDependencies": {
    "react": "^16.13.1"
  },
  "files": [
    "LICENSE",
    "README.md",
    "build-info.json",
    "index.js",
    "shallow.js",
    "cjs/",
    "umd/"
  ]
}
```

Up until v16.12.0, the peer-dep range of react was my version of react 16. But then in v16.131, this peer dependency jumped to require the same version of the package itself.

This is causing issues with the new `npm7` which attempts to auto-resolve peer dependencies. Was this an intentional bump? Is react-test-renderer 16.13.1 not compatible wth say React 16.12.0 any more?

**Comment by milesj** [comment]
@ktalebian All your React dependencies should be using the same version range. `react`, `react-dom`, `react-test-renderer`, etc, should all be on 16.13.1.

**Comment by ktalebian** [comment]
@milesj okay then the previous versions of `react-test-runner` have the optional dependency incorrectly defined. v16.12.0 has `"react": "^16.0.0"`

**Comment by gaearon** [comment]
@ktalebian What is the concrete ?

**Comment by ktalebian** [comment]
@gaearon I'm saying I was confused as to why `react-test-renderer@16.12.0` (and below) has `"react": "^16.0.0"` as a peer dependency (so this package is saying any version of React is compatible with it), but starting from `react-test-renderer@16.13.0`, the peer dependency of react matches the version of react-test-renderer

**Comment by gaearon** [comment]
Does this present a concrete problem for you? Overall mixing different versions doesn't always work, which is why we're leaning towards enforcing that they go in lockstep.

**Comment by ktalebian** [comment]
@gaearon not directly, it was just something I noticed and I wanted to bring it up to your attention. We can close this issue.
