### ISSUE TITLE
Bug: 引用了"react-file-viewer": "^1.2.1"预览附件，打包特别慢，需要1个小时左右，如何提高打包的效率？

### ISSUE THREAD

**Issue by wanghx123** [facebook/react#20232]
React version:16.13.1

## Steps To Reproduce

1.在package.json中引用react-file-viewer
2.npm install下载依赖
3.npm run build 打包  ，出奇的慢

Link to code example:

**Comment by eps1lon** [comment]
Duplicate of https://github.com/facebook/react/issues/20231
