### ISSUE TITLE
eslint-plugin-react-hooks: eslint doesn't see the conditional operator '??'

### ISSUE THREAD

**Issue by buugaaga** [facebook/react#20244]
Lint doesn't see wrong

```javascript
import React, { useCallback } from "react";

export const Example = () => {
  const oneFn = () => {
    console.log("hi from oneFn");
  };
  const item =
    oneFn ??
    useCallback(() => {
      console.log("hi from useCallback");
    }, []);
  return (
    <div>
      <button onClick={item}>click on me</button>
    </div>
  );
};
```
![Снимок экрана 2020-11-13 в 09 59 03](https://user-images.githubusercontent.com/36443810/99030498-ff17bd00-2596-11eb-88f8-b24441465acb.png)

otherwise everything is fine

```javascript
import React, { useCallback } from "react";

export const Example = () => {
  const oneFn = () => {
    console.log("hi from oneFn");
  };
  const item =
    oneFn ||
    useCallback(() => {
      console.log("hi from useCallback");
    }, []);
  return (
    <div>
      <button onClick={item}>click on me</button>
    </div>
  );
};
```
![Снимок экрана 2020-11-13 в 09 55 14](https://user-images.githubusercontent.com/36443810/99030426-caa40100-2596-11eb-932f-ec0edd6f46d6.png)

React version: 16.13, 17.0

Link to code example: https://codesandbox.io/s/flamboyant-sea-syg8x?file=/src/Example.tsx

**Comment by sarathps93** [comment]
Hi @buugaaga @eps1lon Shall I work on fixing this if you guys aren't?

**Comment by n0ruSh** [comment]
Hi @eps1lon @buugaaga  is this issue up for grabs? I can give it a shot if you guys are not already working on this

**Comment by n0ruSh** [comment]
It seems a bit wired as I'm NOT able to replicate the issue when I create a local project with `create-react-app`.  Also I see the case is already covered in the [test](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/__tests__/ESLintRulesOfHooks-test.js#L749) when I browsered through the codebase.
