### ISSUE TITLE
Bug: dispatched action executes reducer during render

### ISSUE THREAD

**Issue by yanovich** [facebook/react#20240]
When a child components communicates with a parent, half of the time an update is batched with a rerender, and a warning `Cannot update a component while rendering a different component` is raised.

![image](https://user-images.githubusercontent.com/576586/98971487-44e66e00-2522-11eb-90f0-9d54e828b428.png)

This seems to be very close to the issue #18098. That one is about a harmless consequence of an unexpected render, this one is about a behavior that [will likely start hard failing in future versions of React](https://github.com/facebook/react/issues/18178#issuecomment-592662192)

React version: 16.14.0

## Steps To Reproduce

1. call `[state, setState] = useState()`
2. pass `setState` to a child component
3. call `[state, dispatch] = useReducer(reducer)` in the child
4. call `setState()` in `reducer`
5. trigger `dispatch` in an event handler in the child twice

Link to code example:
[code sandbox](https://codesandbox.io/s/yanovich-scheduleupdateonfiber-cjpuy)

## The current behavior
Half of the time an update is batched with a rerender, and a warning `Cannot update a component (`App`) while rendering a different component (`Table`)` is raised.

## The expected behavior
Update always happens before rerender.

**Comment by billyjanitsch** [comment]
Calling `setState` in a reducer is not allowed, because it's a side effect. Reducers have to be pure functions.
