### ISSUE TITLE
Bug: react 17 not working with jest

### ISSUE THREAD

**Issue by TomDlu** [facebook/react#20245]
I have updated react to 17 and configured babel to new automatic runtime. Jest stopped working.
Whats the issue here?
![image](https://user-images.githubusercontent.com/28571876/99057218-c6c6ad80-259b-11eb-98d8-f4c9a8354b21.png)

## Code:
```
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js",
  },
```
```
  "jest": {
    "roots": [
      "<rootDir>/src"
    ],
    "moduleNameMapper": {
      "\\.(css|scss|sass)$": "identity-obj-proxy"
    },
    "setupFilesAfterEnv": ['./test.js'],
    "transform": {
      "\\.[jt]sx?$": "babel-jest"
    },
    "testEnvironment": "jest-environment-node",
    "modulePaths": [],
  }
```
```
import Enzyme from "enzyme";
import Adapter from "enzyme-adapter-react-16";

Enzyme.configure({ adapter: new Adapter() });
```
```
{
    "presets": [
      [
        "@babel/preset-react",
        {
          "runtime": "automatic"
        }
      ]
    ]
  }
```
```
import { mount } from 'enzyme';

it("renders", () => {
  const wrapper = mount(<div />);
});

```

**Comment by bvaughn** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by ChrisRast** [comment]
This is a non-issue, you are using the Enzyme adapter for react 16.

If you NEED react 17 right now use the un-official adapter https://github.com/wojtekmaj/enzyme-adapter-react-17.

Otherwise wait a bit then migrate gracefully.

**Comment by bvaughn** [comment]
Since I don't have a repro, I'm going to assume @ChrisRast is correct about the Enzyme issue. We can reopen if there's something else involved here.
