### ISSUE TITLE
ReactCSSTransitionGroup: multiple transitions on enter

### ISSUE THREAD

**Issue by pstoica** [facebook/react#2024]
Sorry if this is a dupe (couldn't really tell from other animation bugs), but I noticed with the CSSTransitionGroup class that it doesn't seem to handle multiple transition properties on enter very well. Take this example:

```
  .action-tray-enter {
    transform: translateY(100px);
    opacity: 0.01;
    transition: all .25s ease-in 0.3s;
  }

  .action-tray-enter.action-tray-enter-active {
    transform: translateY(0);
    opacity: 1;
  }

  .action-tray-leave {
    transform: translateY(0);
    opacity: 1;
    transition: all .25s ease-in 0.1s;
  }

  .action-tray-leave.action-tray-leave-active {
    transform: translateY(100px);
    opacity: 0;
  }
```

If you try to remove the node while the enter animation is still occurring, it looked like it was abruptly removing the node without triggering the leave animation. If you switch from `all` to just one property for the enter animation, it works as expected: wait for the enter animation to finish, then trigger the leave animation.

I can provide a fiddle later.

**Comment by charlieschwabacher** [comment]
I think a good solution to this issue would be to add a prop to ReactCSSTransitionGroup allowing the number of transitions to be specified.  The component would wait for the expected number of transitionend events before removing the animation classes or the dom element.

In this case, you would do something like `<ReactCSSTransitionGroup transitionName='action-tray' transitionCount={2}>`.

Opened a pull w/ these changes here: https://github.com/facebook/react/pull/3002

**Comment by daedelus-j** [comment]
+1 

I'm seeing this for enter/leave as well. support transition use case:
```
transition: right .5s ease-in-out, opacity .3s ease-in-out
```

Only handles one transition timing event.

**Comment by timeemit** [comment]
+1 with `transition: height 2000ms, opacity 2000ms;`

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition
