### ISSUE TITLE
Bug:   Upgrade from 16.13.1 to 17.0.1，“document.addEventListener” invalid

### ISSUE THREAD

**Issue by hadesXx** [facebook/react#20267]
Code :

```
const EVENTS_TO_MODIFY = ['touchstart', 'touchmove', 'touchend', 'touchcancel', 'wheel'];

const originalAddEventListener = window.addEventListener.bind();

document.addEventListener = (type, listener, options, wantsUntrusted) => {
  let modOptions = options;
  if (EVENTS_TO_MODIFY.includes(type)) {
    if (typeof options === 'boolean') {
      modOptions = {
        capture: options,
        passive: false,
      };
    } else if (typeof options === 'object') {
      modOptions = {
        passive: false,
        ...options,
      };
    }
  }

  return originalAddEventListener(type, listener, modOptions, wantsUntrusted);
};

const originalRemoveEventListener = window.removeEventListener.bind();
document.removeEventListener = (type, listener, options) => {
  let modOptions = options;
  if (EVENTS_TO_MODIFY.includes(type)) {
    if (typeof options === 'boolean') {
      modOptions = {
        capture: options,
        passive: false,
      };
    } else if (typeof options === 'object') {
      modOptions = {
        passive: false,
        ...options,
      };
    }
  }
  return originalRemoveEventListener(type, listener, modOptions);
};

```

My component has a virtual scroll bar. In version 16.13.1, when the mouse scrolls in the DOM (containing a virtual scroll bar), the above code can prevent the browser from scrolling. After upgrading to version 17.0.1, the code becomes invalid and cannot prevent the scroll bar of the browser from scrolling.

Code souce : https://github.com/facebook/react/issues/14856#issuecomment-478144231 

extremely grateful ！！！！

@yspektor

**Comment by kunukn** [comment]
I probably have to do with this event delegation change in React 17

>In React 16 and earlier, React would do document.addEventListener() for most events. React 17 will call rootNode.addEventListener() under the hood instead.

https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation

**Comment by gaearon** [comment]
Yes, you'll want to patch your root node's `addEventListener` instead of `document`.
