### ISSUE TITLE
Bug: useEffect teardown logic is not executed immediately after unmountComponentAtNode.

### ISSUE THREAD

**Issue by dmitrysteblyuk** [facebook/react#20263]
React version: 17.0.1

## Steps To Reproduce

1. execute `ReactDOM.unmountComponentAtNode`.
2. Observe that `useEffect` teardown function is called only after timeout.

Link to code example: https://codesandbox.io/s/morning-http-0royj?file=/src/index.js

## The current behavior
Only after waiting for timeout I can see teardown function being called.

## The expected behavior
Teardown functions are called during `unmountComponentAtNode` execution.
This is the exact behaviour React 16 has.

**Motivation**.
While developing I'd like to know that teardown functions in `useEffect`s are being executed correctly.
So in `beforeunload` event I'm calling `unmountComponentAtNode` and then checking that data and services my components are using are cleared up.
If this check fails, I can return `true` in this event (that will prevent the page refresh) and then investigate what's wrong.
If `teardown` logic is executed asynchronously, there's no way I can do that.

**Comment by eps1lon** [comment]
This is intended behavior that [changed with React 17](https://reactjs.org/blog/2020/10/20/react-v17.html#react-dom) in https://github.com/facebook/react/pull/17925.

If you need a synchronous cleanup for tests you can wrap `unmountComponentAtNode` in [`act`](https://reactjs.org/docs/test-utils.html#act). For example, `@testing-library/react` already makes sure that the cleanup from `useEffect` is executed synchronously on `unmount` by wrapping the unmounting in `act`. Note that this would not work in production code.

**Comment by thomasjm** [comment]
> Note that this would not work in production code.

Is there a way to do it in production code? I have a use case where I need to clean everything up synchronously.
