### ISSUE TITLE
Bug: Type safety violation by undefined default value for component state.

### ISSUE THREAD

**Issue by sg495** [facebook/react#20269]
Unless a value is explicitly assigned in the constructor, the property `state` in `React.Component<P, S, SS>` has the default value `undefined`, regardless of the specific type passed to the relevant type parameter `S`. This leads to a violation of type safety, as shown by the following code example. Furthermore, the value `undefined` is not actually assignable to the empty object literal type `{}`, the default value for the type parameter `S`.

React version: 17.0.1

Minimal code example:

```ts
import React from 'react';
class MyComponent extends React.Component<{}, {value: string}> {
  constructor(props: {}) {
    super(props);
    console.log(this.state.value);
  }
}
new MyComponent({}); // Compiles OK, TypeError at runtime.
```

## The current behavior

The minimal code example compiles without error but raises `TypeError` at runtime, with error message `"Cannot read property 'value' of undefined"`.

## The expected behavior

The minimal code example should (ideally) raise error at compile time.

## Additional information

For the sake of completeness, the example was run using `react-scripts` and the following `tsconfig.json` (but the issue is not related to `react-scripts`):

```json
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
```

**Comment by sg495** [comment]
The type `undefined` (which makes it type-safe for `state` to have the default value `undefined`) is allowed as a value for the type parameter `S` of `React.Component<P, S, SS>`, because the type parameters are unbounded. However, using `undefined` (or `null`) will cause a static error, because `state` in a JSX element is expected to be of type `Readonly<{}>`.

Minimal code example:

```ts
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, undefined> { }
ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
/* Error 2786:
'MyComponent' cannot be used as a JSX component.
  Its instance type 'MyComponent' is not a valid JSX element.
    Types of property 'state' are incompatible.
      Type 'undefined' is not assignable to type 'Readonly<{}>'.
*/
```

Using `React.createElement` also raises a slightly different error:

```ts
import React from 'react';
class MyComponent extends React.Component<{}, undefined> { }
React.createElement(MyComponent, {});
/* Error 2769:
No overload matches this call.
  The last overload gave the following error.
  Argument of type 'typeof MyComponent' is not assignable to parameter
  of type 'string | ComponentClass<{}, any> | FunctionComponent<{}>'.
    Type 'typeof MyComponent' is not assignable to type 'ComponentClass<{}, any>'.
      Construct signature return types 'MyComponent'
      and 'Component<{}, any, any>' are incompatible.
        The types of 'state' are incompatible between these types.
          Type 'undefined' is not assignable to type 'Readonly<any>'
*/
```

The very last statement in the error might be a bit confusing. It is due to the fact that `Readonly<T>` is a mapped type, so that only object values are assignable to it:

```ts
type Readonly<T> = {
  readonly [P in keyof T]: T[P];
};
let x: Readonly<any> = undefined;
/* Error 2322:
Type 'undefined' is not assignable to type 'Readonly<any>'.
*/
```

**Comment by bvaughn** [comment]
It seems like this issue is requesting new functionality from the TypeScript compiler. The React repro does not have any relationship to the TypeScript compiler.

**Comment by bvaughn** [comment]
Going to close this since we don't maintain or manage TypeScript types or compiler here.

**Comment by sg495** [comment]
I will have to respectfully disagree: this is not an issue with the typescript compiler. This is a violation of typing rules done by the React library:

1. The default value `undefined` assigned to `state` in `React.Component` is incompatible with the default type assigned to it (`S = {}`).
2. The bounds on the type parameter for `state` in `React.Component` don't guarantee that `undefined` is always going to be assignable.
3. There is no requirement for the state to be initialised in the constructor of `React.Component`.

**Comment by bvaughn** [comment]
The *TypeScript types* you are referring to are definitions maintained by people who are not on the React team. They should mirror the behavior of React, not vice versa.

React does not define an initial `state` property on classes. If a component uses state, it should define its own initial state value as either a class property or in the constructor. (The React documentation [explicitly calls out](https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class) the need to assign this initial value for state.)

**Comment by sg495** [comment]
Fair enough, you mean I should raise it in https://github.com/DefinitelyTyped/DefinitelyTyped/. I should have thought of that in the first place: my apologies and thanks for the clarification 👍

**Comment by bvaughn** [comment]
Yup! I think I initially misunderstood what you were suggesting, but given the clarification above– this sounds like something that should be discussed in DefinitelyTyped 😄 Good luck!

**Comment by sg495** [comment]
Actually, further testing shows that `state` is initialized to `null` when creating the element with JSX, and not left uninitialised. Indeed, running the following  in a fresh Create React App:

```ts
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, { value: string }> {
  render() {
    console.log(this);
    return <h1>{this.state}</h1>
  }
}
ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
```

will give the following log of the component, showing that `state` is set to `null`:

```
MyComponent {props: {…}, context: {…}, refs: {…}, updater: {…}, _reactInternals: FiberNode, …}
context: {}
props: {}
refs: {}
state: null
updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}
_reactInternalInstance: {_processChildContext: ƒ}
_reactInternals: FiberNode {tag: 1, key: null, stateNode: MyComponent, elementType: ƒ, type: ƒ, …}
isMounted: (...)
replaceState: (...)
__proto__: Component
```

The following code logs `undefined` instead, which means that `state` is somehow set by JSX:

```
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, { value: string }> {
  render() {
    return <h1>{this.state}</h1>
  }
}
console.log(new MyComponent({}).state); // undefined
```

Given that React components are intended to be used mainly through JSX, this behaviour is very confusing to me. (I know that the documentation says that state should be initialized explicitly, but it is confusing nonetheless 😕)
