### ISSUE TITLE
Bug: cannot use require() to add image path

### ISSUE THREAD

**Issue by mmacu** [facebook/react#20283]
Cannot use require() to display image on my machine. During preparation of this bug report I've created the same base code in Codesandbox and it works there. 

React version: 17.0.1

## Steps To Reproduce

1. Create app with `npx create-react-app` .
2. Try to get image element with <img src={require("path/to/image/image.png")} /> in App.js render return.

Link to code example:

The code works correctly on Codesandbox site. But doesn't work correctly while running locally with `npm start` after creating basic app with the same code. I'm positive that the icon location and path are 100% correct while setting my app.

https://codesandbox.io/s/react-require-bug-1gh2i?file=/src/App.js:67-292

## The current behavior (works like this while running locally)

![local](https://user-images.githubusercontent.com/49128164/99451142-0c7bd100-2922-11eb-9dd9-b787b17dec89.png)

## The expected behavior (works like this on Codesandbox)

![browser](https://user-images.githubusercontent.com/49128164/99451168-156ca280-2922-11eb-8b9e-ba2ad1999abb.png)

**Comment by bvaughn** [comment]
I think you meant to file this in the create-react-app repo:
https://github.com/facebook/create-react-app

I'm going to close this issue :smile: since the React library doesn't have anything to do with `require`
