### ISSUE TITLE
Bug: Events are not fired if the component is not rendered in its container

### ISSUE THREAD

**Issue by simon-milleto** [facebook/react#20281]
React version: 17.0.0

## Steps To Reproduce

1. Render a component with ReactDOM.render() in a DOM element which is not in html tree
2. Get the DOM element using the ref inside this component (see code exemple below)
3. Use this DOM element and append it to another element in the html tree
4. Try to fire event from this element (e.g. button click)
5. Nothing happens

Link to code example:
https://codesandbox.io/s/winter-voice-u8ucp

Since v17, the events are attached to the root element and in this case there is no more root element so events are not fired. I know it's specific (maybe looks like a "bad" trick to use) and it should be managed differently like create a new container in the DOM and use `ReactDOM.render()` directly on this element (or even better using Portals ?). But in the codebase that I had there is some tricks like that to render React component outside the main React root and no warning or error were displayed.

## The current behavior
Events are not fired if the component is not rendered in its container and there is no error or warning displayed

## The expected behavior
With the new event delegation it's normal that we have this behavior since the root element is not in the DOM in my exemple, but it can be hard to debug because no error or warning were displayed. Maybe throw error or warning when this happens ?

Thanks!

**Comment by kunukn** [comment]
I don't know about adding the React warning part if the event listener doesn't exist in the DOM. I have some code adjustment suggestions instead.

In your code example, the fix seems trivial. Mount the container instead of the component.

```jsx
import Button from "./Button";

const componentToDom = (Component, props = {}) => {
  const container = document.createElement("div"); // events will be added here
  ReactDOM.render(
    <Component {...props} />,
    container
  );

  return container;
};

const domComponent = componentToDom(Button);
document.getElementById("my-button").appendChild(domComponent);
``` 

Alternatively if the extra div is unwanted, then maybe this is better?

```jsx
import Button from "./Button";

const componentToDom = (Component, elementId, props = {}) => {
  ReactDOM.render(
    <Component {...props} />,
    document.getElementById(elementId)
  );
};

componentToDom(Button, 'my-button');
```

**Comment by eps1lon** [comment]
I don't understand what problem you're trying to solve. In your codesandbox you might as well do 
```jsx
ReactDOM.render(
  <Button  />,
  document.getElementById("my-button")
);
```
which does the same thing as far as I can tell and events work.

Otherwise it looks like you want to "portal" the rendered element for which [`ReactDOM.createPortal`](https://reactjs.org/docs/portals.html) exists. If you want to render an element outside of its root then you're supposed to use that API instead of DOM API.

**Comment by simon-milleto** [comment]
Yes, this is trivial to fix and the solution that you present is how I solved my issue. But for some reason I have this kind of code in a codebase that I updated to React 17. The idea behind the actual function `componentToDom` was to get the DOM node, do some manipulation to it, and append to another node outside the root. 

I believe that this is not the good way to do it and portals should be used but is there a way to warn the user when the component is not inside the root and not using portals ?

**Comment by eps1lon** [comment]
> but is there a way to warn the user when the component is not inside the root and not using portals ?

A core member would need to clarify this. The question is if it should warn? It seems like you know that what you're doing is not the "correct" way. If you use an escape hatch on purpose then you probably opt-out of React features on purpose as well. But let's see if others stumble over this as well and what core members think.

**Comment by gaearon** [comment]
From what I can tell, what’s happening here is that you are rendering a tree with React, then yank out a part of it and move it somewhere else in the DOM. In other words, you do invasive manual DOM manipulation with nodes managed by React. This is not supported by React and works mostly by accident in your example. There are other cases where this would break in 16.

Manual DOM manipulation is allowed in React in limited circumstances. Mostly within leaf nodes that React has no reason to update. Or using portals. 

You will need to change this code to not do this.

**Comment by gaearon** [comment]
I don’t think we have a good way to warn about this. We can play whack-a-mole with specific cases but in general people can modify DOM in arbitrary ways and we can’t catch them all without slowing down perf too much even in development.

In your case the intention appears to be to render a subtree to another DOM root. That’s what portals do so they should help.
