### ISSUE TITLE
Bug: function in useState hook, setting different value 

### ISSUE THREAD

**Issue by psyKressX** [facebook/react#20294]
useState hook telling me one value then setting another, understand its recommended to use useReducer when working with data structures but i still dont understand why this is happening, this is code block
```
const onAdd = (id, amount = 1) => {
   setItems(old => {
      const idx = old.findIndex(i => i.product_id === id)
      console.log(old[idx].value, amount)
      old[idx].value += amount;
      console.log("after", old[idx].value)
      return [...old]
   })
```
value starts at 0, the console logs are as follows

<img width="461" alt="log" src="https://user-images.githubusercontent.com/50396417/99610540-24f50400-2a66-11eb-82eb-0c5f3637a825.png">

the state "adds" double what ever the amount is, for the case above, 2, the console logs only run once so the function isnt running twice and it also works fine the non-useEffect safe way below

```
const old = [...items]
const idx = old.findIndex(i => i.product_id === id)
old[idx].value += amount;
setItems(old)
```

React version: react-dom@17.0.1

**Comment by eps1lon** [comment]
Thanks for the report and included code.

The unexpected behavior likely stems from the fact that your state-updater function has side-effects:
> old[idx].value += amount;

You're probably using React in [StrictMode which double-invokes functions that should have no side-effects](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects). That would explain "the state "adds" double what ever the amount is"

Could you try out
```js
setItems(old => {
  return old.map(i => {
    if (i.product_id === id) {
      return { ...i, value: i.value + amount }
    }
    return i;
  })
```
and tell me if this works?
