### ISSUE TITLE
Bug: Infinite loop when following the instructions of Exhaustive Deps.

### ISSUE THREAD

**Issue by ogasawaraShinnosuke** [facebook/react#20297]
React version: 17.0.1

Link to code example:

```json

        "react-hooks/exhaustive-deps": "warn",
```

If you write the following code, `Exhaustive Deps` will spit a warning in deps of` useMemo`

### Infinite loop code
The infinite loop code has a negative effect on the browser, so I've included only a sample. If you change the hook used from `useNonInfinite` to` useInfinite`, the code will be similar.

```tsx
import {
  useEffect, useMemo, useState,
} from 'react';

const useInfinite = (a: string[]) => {
  const [state, setState] = useState<string[]>([]);
  const b = useMemo(() => a.concat('b'), [a]);
  useEffect(() => {
    setState(b);
  }, [b]);
  return {
    state,
  };
};

export {
  useInfinite,
};
```

### non infinite loop code
https://codesandbox.io/s/kind-water-4lybu?file=/src/App.js

```tsx
import {
  useEffect, useMemo, useState,
} from 'react';

const useNonInfinite = (a: string[]) => {
  const [state, setState] = useState<string[]>([]);
  const b = useMemo(() => a.concat('b'), []);
  useEffect(() => {
    setState(b);
  }, [b]);
  return {
    state,
  };
};

export {
  useNonInfinite,
};
```

If you follow linter's instructions, you will end up in an infinite loop

**Comment by maxsbelt** [comment]
Hi @ogasawaraShinnosuke. Actually, there is a problem with `useInfinite` hook parameter. As I can see from the sandbox you're passing a non memoized array as an argument:

<img width="631" alt="Screenshot 2020-11-22 at 19 10 53" src="https://user-images.githubusercontent.com/950216/99908977-c8f4de80-2cf6-11eb-9567-9939e4bfa315.png">

You can fix the problem by passing the memoized array to `useInfinite` hook. There are 2 examples:
|outside declaration|useMemo|
|---|---|
|<img width="544" alt="Screenshot 2020-11-22 at 19 15 20" src="https://user-images.githubusercontent.com/950216/99909052-356fdd80-2cf7-11eb-941a-7736b550226e.png">|<img width="712" alt="Screenshot 2020-11-22 at 19 15 58" src="https://user-images.githubusercontent.com/950216/99909053-36a10a80-2cf7-11eb-85ff-9036b6cc46d7.png">|

**Comment by ogasawaraShinnosuke** [comment]
> Hi @ogasawaraShinnosuke. Actually, there is a problem with `useInfinite` hook parameter. As I can see from the sandbox you're passing a non memoized array as an argument:
> 
> <img alt="Screenshot 2020-11-22 at 19 10 53" width="631" src="https://user-images.githubusercontent.com/950216/99908977-c8f4de80-2cf6-11eb-9567-9939e4bfa315.png">
> 
> You can fix the problem by passing the memoized array to `useInfinite` hook. There are 2 examples:
> 
> outside declaration	useMemo
> <img alt="Screenshot 2020-11-22 at 19 15 20" width="544" src="https://user-images.githubusercontent.com/950216/99909052-356fdd80-2cf7-11eb-941a-7736b550226e.png">	<img alt="Screenshot 2020-11-22 at 19 15 58" width="712" src="https://user-images.githubusercontent.com/950216/99909053-36a10a80-2cf7-11eb-85ff-9036b6cc46d7.png">

I think I was wrong and I was on an endless loop. Thank you for your kindness!
