### ISSUE TITLE
Question: Guarantees of scheduling an update after setState

### ISSUE THREAD

**Issue by roman-g** [facebook/react#20292]
It's well documented that `setState` is considered as `scheduling an update` and should be treated as an asynchronous operation, but are there any fundamental guarantees for that scheduling?

I believe it's impossible to postpone an arbitrary update for an arbitrary time, otherwise, even basic scenarios would become tricky.
For example, in that paradigm, I may have doubts if I can use a `state` value in a button click handler and send it to a server, or the value may be stale because the component hasn't been re-rendered after the recent `setState` call in another event handler. 
That sounds absurd, so I'm sure there are guarantees that the scheduling algorithm ensures now and will continue doing that in the future.

Bonus question:
Actually, in the beginning, I investigated if the `setTimeout(callback, 0)` call after `setState` ensures execution of all affected component's render functions before calling `callback`, but haven't found a justified answer, only advice that it's a bad approach and I must use `useEffect` instead. However, I had known that before and just wanted to evaluate the correctness of the existing code that unfortunately already works this way and the importance of its rework.
So, as a particular case of the main question, why `setTimeout(callback, 0)` seems to work as an "update flush" now and what may I expect in the future?

Thanks!

**Comment by bvaughn** [comment]
Using a timeout (especially a 0) is a bad idea because it assumes the update will be processed before the timeout function gets called. There is no guarantee of how quickly the update will be processed because it depends on several things (e.g. what other updates are scheduled? are any of them higher priority? what else is going on in the browser– keeping in mind that JavaScript mostly only runs on one thread and so there can be bottlenecks).

**Comment by bvaughn** [comment]
> For example, in that paradigm, I may have doubts if I can use a state value in a button click handler and send it to a server, or the value may be stale because the component hasn't been re-rendered after the recent setState call in another event handler.

If you're worried about an update scheduled by one click handler being flushed before a second event handler is invoked, that should not be a problem. Updates scheduled by *discrete events* (click, mouseup, mousedown, touchup, touchdown, submit, etc) get flushed by React before it calls an event listener of the another discrete event. It's always serial.

**Comment by bvaughn** [comment]
I'm going to close this issue since it looks to be a question and I think I've answered it but we can keep talking on it.

**Comment by roman-g** [comment]
@bvaughn Thanks!

> There is no guarantee of how quickly the update will be processed.

Got it. To clarify the practical aspect: is it theoretically possible to reproduce such an update delay using the current version of React or it will become the reality after unleashing Fiber's power in further updates?

> Updates scheduled by discrete events (click, mouseup, mousedown, touchup, touchdown, submit, etc) get flushed by React before it calls an event listener for another discrete event.

Great, that's clear. Just out of curiosity, is there a place where this and other scheduler behavior details are described?

**Comment by bvaughn** [comment]
> is it theoretically possible to reproduce such an update delay using the current version of React or it will become the reality after unleashing Fiber's power in further updates?

Not sure what we're talking about exactly. State updates have been async for a long time in cases like event handlers so React can batch related updates and avoid unnecessary renders. Concurrent mode lets React batch even more things (not just updates from event handlers) by default though so it will happen more often I guess?

> Just out of curiosity, is there a place where this and other scheduler behavior details are described?

I think implementation details like this might be mixed among tests, PR comments, etc. I'm not sure if there's a centralized place at the moment.
