### ISSUE TITLE
Error: "Commit tree already contains fiber 48. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by brunoebstein** [facebook/react#20291]
Describe what you were doing when the bug occurred:
1. Start Profiler
2. Stop Profiler
3. Click on the arrow to see the next commit

I tried and it worked :shrug: 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.9.0-75726fadfd

Component stack: CommitFlamegraphAutoSizer@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:33986:50
div
div
div
SettingsModalContextController@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:28047:1
Profiler_Profiler@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:35614:50
ErrorBoundary_ErrorBoundary@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:29061:5
PortaledContent@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:29178:27
div
div
ProfilerContextController@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:32775:1
TreeContextController@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:24163:1
SettingsContextController@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:24652:1
ModalDialogContextController@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:29245:1
DevTools_DevTools@moz-extension://e4e94e2d-7b62-42fe-80eb-d114edb77438/build/main.js:36048:1

**Comment by bvaughn** [comment]
This issue has  been reported a few times so I'm going to close this as a duplicate :smile: #18859

**Comment by bvaughn** [comment]
@brunoebstein This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼
