### ISSUE TITLE
Release/maintain TypeScript bindings (.d.ts) for ReactJS

### ISSUE THREAD

**Issue by DanTup** [facebook/react#2029]
I really like React; but I kinda hate JavaScript due to lack of typing. TypeScript looks good; but the 3rd party bindings are truly terrible (constantly breaking, and generally not versioned at all well).

The immutable JS collections released recently by Facebook include TypeScript bindings; which fills us with hope that maybe the same might happen for React. Please, make it so :)

I'm aware JSX won't work with TypeScript; that's no big loss; I prefer pure script, it plays nicer with existing JS tools.

**Comment by BabakMN** [comment]
+1

**Comment by vsiao** [comment]
https://github.com/borisyankov/DefinitelyTyped/tree/master/react has up-to-date (unofficial) `d.ts` files for React. Let me know if you have any issues with them (file an issue over at DefinitelyTyped, cc @vsiao).

**Comment by gaearon** [comment]
Seems like this is resolved.

**Comment by donaldpipowitch** [comment]
@gaearon I wouldn't say it is solved, if you mean the unofficial typings in DefinitelyTyped with that. IMHO these are a workaround. For example it is very hard to control typings for prereleases of React with DefinitelyTyped.

**Comment by gaearon** [comment]
What is actionable for the team here?

**Comment by donaldpipowitch** [comment]
I guess we need a statement if the team is interested in including Typescript definitions or not and if they would accept definitions inside a PR what the requirements are.
