### ISSUE TITLE
Missing hook dependency in custom hook

### ISSUE THREAD

**Issue by gempain** [facebook/react#20308]
React version: 16.13.1

## Steps To Reproduce

Use this component anywhere:

```
function useValue() {
  return useState<number>();
}

export function Compo() {
  const [value, setValue] = useValue();

  useEffect(() => {
    setValue(Date.now());
  }, []);

  return (
    <>{value}</>
  );
}
```

## The current behavior

You get an eslint warning saying `React Hook useEffect has a missing dependency: 'setValue'. Either include it or remove the dependency array    react-hooks/exhaustive-deps`.

## The expected behavior

The missing dependency warning should not exist.

```
export function Compo() {
  const [value, setValue] = useState<number>();

  useEffect(() => {
    setValue(Date.now());
  }, []);

  return (
    <>{value}</>
  );
}
```

This is a minimal example, but in practice I DO need to use a function similar to `useValue()`.

**Comment by michie1** [comment]
I think the warning should be there. 

```
Is it safe to omit functions from the list of dependencies?

Generally speaking, no.
```
source: https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies

**Comment by gempain** [comment]
Fair enough. So basically you don't get the warning when using the `useState` inside the component, because `setValue` is a `const` ?

**Comment by gempain** [comment]
I'll close as I think this might be due to [limitations](https://stackoverflow.com/a/64935168/5365075) of the eslint rule.
