### ISSUE TITLE
Bug: Blur/Focus remaining bug

### ISSUE THREAD

**Issue by baeharam** [facebook/react#20317]
I cannot ensure it is bug, but I feel it's bug. When blur input at chrome dev tools, not in the dom. Blur/Focus is remained at dom. I asked [in stackoverflow](https://stackoverflow.com/questions/64925346/react-why-focus-event-is-remained-after-blurring-outside-webpage), but there was no answer, so I submit it as github issue

![IrtvV](https://user-images.githubusercontent.com/35518072/99921819-57f20d00-2d70-11eb-8f01-b6548a505d54.gif)

React version:

## Steps To Reproduce

1. Make input element
2. Focus to input element
3. Blur at Chrome DevTool
4. Focus to background except input element

Link to code example:

https://codesandbox.io/s/why-focus-event-is-occurred-when-blur-at-chrom-devtools-z2rzv?file=/src/App.js

## The current behavior

Blur/Focus is remained

## The expected behavior

They should gone.

**Comment by maxsbelt** [comment]
Hi @baeharam. Looks like it's an old chromium issue. Here the vanilla js fiddle that has exactly the same problem:
http://jsfiddle.net/dSbpc/3/

And here the chromium bug report that was resolved 7 years ago:
https://bugs.chromium.org/p/chromium/issues/detail?id=117307

You can try to open a new bug in the chromium project.

**Comment by baeharam** [comment]
@maxsbelt 

Thanks! I [reported it as bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1151849) to Chromium using your reproduction. I think it can be closed.
