### ISSUE TITLE
Bug: ref.current.contains(e.target) returns incorrect value if react element is removed on the next render 

### ISSUE THREAD

**Issue by TristanBarrowAboutTime** [facebook/react#20325]
Description: 
`ref.current.contains(e.target)` returns an unreliable value if the react element is removed on the next render.

React version: "^17.0.1"

## Steps To Reproduce (it's probably easier to just look at the code below)

1. Create a component (`App`).
2. Create another component (`RefComp`) 
3. Conditionally render `RefComp` inside `App` using a boolean `useState` call (`[showRef, setShowRefTo]`).
4. Add a `useRef` call inside `RefComp` and attach the returned ref to the root element inside `RefComp`.
5. Pass a `close` prop to `RefComp`, make it a function that sets `App`'s boolean state to false
6. Inside `RefComp` make a `useEffect` call that sets up and tears down an event listener
7. Make the above event listener call `ref.current.contains(e.target)` and call the `close` prop if the ref **does not** contain the click
8. If you wish call close on the `useEffect` clean up as well as the event listener teardown.
9. Inside `RefComp` setup a separate boolean state to conditionally render an element inside the `ref` element.
10. Setup the element to be conditionally rendered. 
11. Use an onClick to cause the conditionally rendered component to remove its self by setting the state _inside_ `RefComp` to false. 
12. Upon trying to click the element which removes its self you will see that `ref.current.contains(e.target)` somehow returned false and triggered the `close` method which in turn removes the entire ref. 

Link to code example:  https://github.com/TristanBarrowAboutTime/react-ref-bug

Simplified Code
```
function App() {
  const [showingRef, setShowingRefTo] = useState(true);

  return (
    <div>
      // Clicking outside of the ref will remove the ref.
      {showingRef && (
        <RefComp 
          close={() => setShowingRefTo(false)}
        />
      )}
    </div>
  );
}

const RefComp = (props) => {
  const [showingDiv, setShowingDivTo] = useState(true);
  const ref = useRef(null);
  
  useEffect(() => {
    const handleClick = (e) => {
      if (ref.current.contains(e.target)) return;
      props.close();
    }
    document.addEventListener('click', handleClick);
    return () => {
      document.removeEventListener('click', handleClick);
      props.close();
    } 

  },[]);
  
  return (
    <div ref={ref}>
        <div>I'll be removed too</div>
       // Removing its self removes the entire ref. 
      {showingDiv && (
        <div id='i-have-problems' onClick={() => setShowingDivTo(false)} >
          Remove myself (I have problems)
        </div>
      )}
    </div>
  );
}
```

## The current behavior
clicking on an element that gets removed in the next state update causes `ref.current.contains(e.target)` to return `false` even if the clicked element is inside the ref. 

## The expected behavior
if a click event is triggered inside a ref `ref.current.contains(e.target)` should return `true` even if the clicked element gets removed in the next state update. 

## My Theory
I think the element gets removed before `ref.current.contains(e.target)` call is made. This means `ref.current.contains(e.target)` is being called on a ref that doesn't exist. It's hard to say if `a` contains `b` if `b` doesn't exist. 

Finding a way to call `ref.current.contains` before state update would fix the problem... but I imagine that would cause crazy problems in react. 

Maybe finding a way to store the `event` and then calling `contains` with that event after the state update would work. That is supposing this is actually unexpected behavior.

**Comment by TristanBarrowAboutTime** [comment]
Btw. My current workaround is to just cover any elements that need to be removed with a transparent element and put my onclick handler on the invisible element.

**Comment by LXSMNSYC** [comment]
I tested the event flow and it seems to me that the render phase happens between onClick handler was run and document click handler was run. I think the changes in [event delegation](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation) may have contributed to this behavior.

**Comment by TristanBarrowAboutTime** [comment]
That should solve my issue! Thanks!

**Comment by nabinbhusal80** [comment]
Faced the same issue works with the addition of `{ capture: true }` . 
To be precise 
`window.addEventListener('click', this.clickHandler, { capture: true })` while adding event
`window.removeEventListener('click', this.clickHandler, { capture: true })` while removing the event.

**why does this work?**
understand the bubbling principle, here is how it works
[https://javascript.info/bubbling-and-capturing]
