### ISSUE TITLE
Feature Request:  Add some COMPARISONS method for dependencies in the "useEffect" hook. For number datatype, the inbuilt comparison method works just fine but for "Arrays", it creates problem. I have shown an example below:  

### ISSUE THREAD

**Issue by hopper01** [facebook/react#20323]
### What  I want to do?
I want to fetch all the users available form the database and add to the list. And at the same time if any new user is added from the backend or the admin panel, I want my list to get Updated _without refreshing the page_ 

`import React, { useState, useEffect } from 'react';
import fetch from "isomorphic-unfetch";

const AllUsers = () => {
    const [user, setUsers] = useState([]);

    useEffect(() => {
        fetchData();
        console.log("I'm in");

    }, [users]);

    const fetchData = async () => {
        const request = await fetch("/api/exam", {
        method: "GET",
        headers: {
            "Content-Type": "application/json",
            Accept: "application/json",
        },
        });
        if (request.ok) {
            const data = await request.json();
            setUsers(data.active);
        }
    }
    return (
        <div>
        {
            users.map( value => { return <li>{value.name}</li> })
        }
        </div>
    )
}

export default AllUsers`

### What is the problem?
The code above turns into a infinite loop because every time , the comparison is shallow , i.e., 

`const a = [1,2,3];
const b = [1,2,3];
console.log(a === b); // it is false`

and every effect call its own effect.

### What i suggest?
If we can compare just the size of the array of users from the previous state or compare some unique property of the data we are fetching and not compare the array as a whole, then we can avoid by entering into a _infinite loop_ and also from _refreshing the page_ often.

**If the team can add optional _COMPARISON_  method with the hook**

Thanks for reading,
Anand Dhawan
_(enthusiastic react developer)_

**Comment by milesj** [comment]
@hopper01 It's an infinite loop because you're re-fetching data each time the users change. Any reason why you're re-fetching after fetching users?

Remove the `users` dependency here:

```ts
useEffect(() => {
    fetchData();
    console.log("I'm in");

}, [users]);
```

To this, which only runs once on mount.

```ts
useEffect(() => {
    fetchData();
    console.log("I'm in");
}, []);
```

**Comment by LXSMNSYC** [comment]
Also, why not 

```js
useEffect(() => {
  fetchData();
}, users); // Since 'users' is an array of number
```

**Comment by hopper01** [comment]
@milesj i am refetchting because if any new user is added to the database , it should also reflect on my front-end application. Yes, i want to fetch all the data in the initial render but i also want it update if any new user is added to the database without refreshing or say without forcing useEffect  to run again.

**Comment by hopper01** [comment]
@LXSMNSYC users isn't an array of number, otherwise there won't be any problem.  
Its an array of objects having info about every user.

**Comment by LXSMNSYC** [comment]
I understand now. There are third-party libraries out there that provides the functionality you need, such as 'useDeepCompareEffect'

**Comment by hopper01** [comment]
@LXSMNSYC thanks for the suggestion. I will try that.

**Comment by hopper01** [comment]
by reading the twitter comment of Dan Abramov, I think he is right, there is no need for this feature.
