### ISSUE TITLE
Security vulnerability: Insecure Randomness

### ISSUE THREAD

**Issue by tibabit** [facebook/react#20329]
I am using React version 16.8.6 (also tested with 16.14.0) and running Fortify ( version 19.2) to check for vulnerability. There are multiple reports for "Insecure Randomness" pointing to use of `Math.random` function. This seems to be coming from react-dom package.

Screenshot: 
![image](https://user-images.githubusercontent.com/805631/100228629-f769f800-2f48-11eb-89d8-97529710235c.png)

Can you please take a look at this and let me know when this will be fixed.

React version:  16.8.6, 16.14.0
Fortify version 19.2

## Steps To Reproduce

1. Create an react app using cra, and import react-dom
2. Bundle output using react-script
3. Run fortify on bundled output

**Comment by kachkaev** [comment]
See https://github.com/facebook/react/issues/15912#issuecomment-503209710

**Comment by gaearon** [comment]
There is no vulnerability here. https://github.com/facebook/react/issues/15912#issuecomment-733895413
