### ISSUE TITLE
Error: "value is undefined"

### ISSUE THREAD

**Issue by Camilotk** [facebook/react#20326]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.0-11a2ae3a0d

Component stack: AutoSizeInput_AutoSizeInput@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:29816:19
Field@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:31844:1
div
Row@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:31743:1
div
StyleEditor_StyleEditor@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:31634:1
NativeStyleEditor@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:31921:50
NativeStyleEditorWrapper@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:31901:44
div
InspectedElementView_InspectedElementView@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:31980:1
div
InspectedElementWrapper@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:32181:50
Suspense
NativeStyleContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:31423:1
div
div
InspectedElementContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:28909:1
OwnersListContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:27546:1
SettingsModalContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:28194:1
Components_Components@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:33372:52
ErrorBoundary_ErrorBoundary@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:29208:5
PortaledContent@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:29325:27
div
div
ProfilerContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:32922:1
TreeContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:24310:1
SettingsContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:24799:1
ModalDialogContextController@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:29392:1
DevTools_DevTools@moz-extension://4c2e3b02-bbc3-448b-8a7c-e8ad44bb17b4/build/main.js:36195:1

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment]
Closing due to a lack of response.
