### ISSUE TITLE
Bug: react-scripts 4.0.1 : EBUSY: resource busy or locked, open 'C:\...\project\.eslintcache'

### ISSUE THREAD

**Issue by pinonpierre** [facebook/react#20328]
React version:

## Steps To Reproduce

1. Upgrade react-scripts from 4.0.0 to 4.0.1 (It works on 4.0.0)
2. yarn start

Link to code example:

Seems happen only on windows due to locking

## The current behavior

![image](https://user-images.githubusercontent.com/4507910/100120709-907d0e00-2e78-11eb-92e6-bd94c89acfd5.png)

## The expected behavior

No lock error :)

Thanks,

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble. This sounds like an issue with create-react-app which is not released from this repository but https://github.com/facebook/create-react-app.

Please check the [issues in facebook/create-react-app](https://github.com/facebook/create-react-app/issues) and [create a new one](https://github.com/facebook/create-react-app/issues/new?labels=issue%3A+bug+report%2C+needs+triage&template=bug_report.md) if you didn't find an existing issue that fits your description.
