### ISSUE TITLE
Bug: custom hooks are linted by rule `react-hooks/exhaustive-deps` because their name contains `Effect`

### ISSUE THREAD

**Issue by seedy** [facebook/react#20331]
```
"react": "17.0.1"
"eslint-plugin-react-hooks": "4.0.0"
```
## Steps To Reproduce

1. Implement custom react hooks with `Effect` in their name, such as `useMyEffect`, with a custom signature
2. Import and call the hook in a component
3. lint component

#### Custom hook signature
`useMyEffect.js`
```
import {useEffect} from 'react';

export default (fn,   {
  foo = true,
  bar = false,
  } = {}) => {
  useEffect(
    () => {
      if (foo && bar) { fn(); }
    },
    [foo, bar, fn],
  )
} 
```

#### Component
```
import {useCallback} from 'react';
import useMyEffect from './useMyEffect';

const MyComponent = () => {

  const doFetch = useCallback(() => {console.log('fetch');},[]);

  useMyEffect(doFetch, {foo: true, bar: true}); // no dependency array passed

  return null;
}

export default MyComponent;
```

#### eslint config
```
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "error",
```

### Result of linting

`error React Hook useMyEffect has a missing dependency: 'doFetch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

## The expected behavior

No lint error

**Comment by Toub** [comment]
What is your eslint version and config?

I don't reproduce this bug, except if I explicitly add the hook to my config:

```json
"react-hooks/exhaustive-deps": ["error", {
    "additionalHooks": "(useMyEffect)"
}]
```

**Comment by seedy** [comment]
My eslint version depends on CRA. It seems that latest package updates solved the issue. Sorry for not closing earlier.
