### ISSUE TITLE
Question: Is there an experimental release based on 17 stable?

### ISSUE THREAD

**Issue by rehikari** [facebook/react#20336]
Apologize for posting a question here, as I don't think it should be posted on StackOverflow.

I've noticed the latest experimental release is `0.0.0-experimental-4ead6b530`, which seems to be based on an alpha version of React. Is there an experimental release based on 17 stable, or am I mistaken, and there's no difference between these two versions?

Also, are both next and experimental release channels guaranteed to be newer than the stable channel?

Thanks!

**Comment by bvaughn** [comment]
Experimental releases are never stable. They're periodically published from the head of the main branch. They aren't guaranteed to be newer than the latest stable channel either. Sometimes yes, sometimes no.

**Comment by bvaughn** [comment]
I'm going to close this issue since (I believe) the question has been answered. :smile:
