### ISSUE TITLE
Bug: onLoadStart is not passed to img

### ISSUE THREAD

**Issue by keul** [facebook/react#20330]
Although it seem a valid event, and it works using vanilla HTML/JS (at least **Firefox**, Chrome still have an open bug https://bugs.chromium.org/p/chromium/issues/detail?id=458851), it seems that using and `onLoadStart` event on an `img` is not working in react.

React version: 17.0.0

## Steps To Reproduce

1. With **Firefox** open browser development tools
2. Disable browser's cache
3. Using Firefox go to https://ukpcn.csb.app/
4. Check the console

Link to code example: https://codesandbox.io/s/onloadstart-issue-ukpcn

## The current behavior

The console shown:

```
Vanilla img loading
Vanilla img loaded
React img loaded
```

Seems that the `onLoadStart` is not working.

## The expected behavior

The `onLoadStart` function should be executed, so logging also `React img loading`

**Comment by ideffix** [comment]
Sounds interesting to me, I can dig into that ⛏

**Comment by ideffix** [comment]
After some invastigation I've found that this behaviour is done on purpose. Please check file **ReactDOMEventListener-test.js** and test on line **328**.  Test description says: 'should dispatch loadstart only for media elements' - code checks that event handler functions should not be called on img element
`imgRef.current.dispatchEvent( new ProgressEvent('loadstart', {bubbles: false,}),);
      expect(handleImgLoadStart).toHaveBeenCalledTimes(0);`
@gaearon wrote in commit message: 

> In fact it never bubbles, even for <img>. And since we don't special case it in the <img> event attachment logic when we create it, we never supported <img onLoadStart> at all.  We could fix it. But Chrome doesn't support it either: https://bugs.chromium.org/p/chromium/issues/detail?id=458851. Nobody asked us for it yet. And supporting it would require attaching an extra listener to every <img>.  So maybe we don't need it? Let's document the existing state of things.

I don't know if is it something that should be fixed or just let it as it is.

**Comment by yuthikasagarage** [comment]
same issue

**Comment by jhughes982** [comment]
I am experiencing the same problem. It would be great if this issue could be sorted.

**Comment by sami616** [comment]
This seems like something that will need to be fixed for triggering suspense boundaries for images using  the `loading='lazy'` attribute.

**Comment by ackvf** [comment]
Tried all of these, only `onLoad` and `onload` was printed to the console.

```
<img
  src={getStaticAssetURL('core.gif')}
  onLoad={() => console.debug('onLoad')}
  onLoadStart={() => console.debug('onLoadStart')}
  onLoadedData={() => console.debug('onLoadedData')}
  onLoadedMetadata={() => console.debug('onLoadedMetadata')}
  ref={ref => {
    if (!ref) return
    ref.onload =  () => console.debug('onload')
    ref.onloadstart = () => console.debug('onloadstart')
    ref.onloadeddata = () => console.debug('onloadeddata')
    ref.onloadedmetadata = () => console.debug('onloadedmetadata')
  }}
/>
```

**Comment by SimpleCreations** [comment]
Still an issue

**Comment by DaeWon9** [comment]
same issue + 1
