### ISSUE TITLE
Bug: Strange lines in the page

### ISSUE THREAD

**Issue by stefango** [facebook/react#20334]
When chrome devtools is opened, some strange lines appear in the page and disappear after disable&enable the react extension.
I'm wondering if there are some bugs on react extension.
Win10x64 Chrome 87.0.4280.66
[Chrome issue 83155766](https://support.google.com/chrome/thread/83155766)
![img](https://storage.googleapis.com/support-forums-api/attachment/thread-83155766-2167922176753088865.jpg)

**Comment by eps1lon** [comment]
What you're seeing are re-renders that the extension is highlighting. You can disable this by opening the browser devtools, switching to the "Components" tab (from react-devtools), open settings, switch to "General" and uncheck "Highlight updates when components render":

![devtools-rerender](https://user-images.githubusercontent.com/12292047/100435256-fb5b5e80-309d-11eb-8166-494283d923ad.gif)
