### ISSUE TITLE
A throw error occurred while creating react project with NPM, unable to create project 

### ISSUE THREAD

**Issue by ren217** [facebook/react#20358]
throw err;

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment]
Closing due to a lack of response.
