### ISSUE TITLE
Bug: Memory Leak when rendering arrays

### ISSUE THREAD

**Issue by angeloocana** [facebook/react#20368]
I created a React hook called useMemoryLeaksDebugger using the WeakRef API to find memory leaks.
I found many real memory leaks on my app, but there was one memory leak that was really hard to find, and I think it is a bug in React. 

React version: v17 and v16

## Steps To Reproduce

1. Open the code sandbox https://codesandbox.io/s/cool-kalam-77v5m?file=/src/App.js
2. Click "Add " button to render the list
3. Click "Remove" button to remove the list
4. Force Garbage Collection in Chrome Memory Dev tools (click the trash icon)
5. Run in the console "memoryLeaksDebugger.check()"

![react_bug](https://user-images.githubusercontent.com/5487699/100877970-8ca04b80-3477-11eb-9e2f-c943c5b4077d.gif)

Link to code example:
https://codesandbox.io/s/cool-kalam-77v5m?file=/src/App.js

## The current behavior
Any child of a component that is rendered inside a `.map` stays alive in memory when the components are unmounted.

## The expected behavior
No components should stay in memory when they are unmounted.

**Comment by eps1lon** [comment]
Most importantly: Does this leak with a production build? You can deploy the codesandbox to vercel or netlify which creates a production build. React might keep some "stuff" longer than always necessary for debugging purposes.

> No components should stay in memory when they are unmounted.

I think React doesn't immediately get rid of them. Does this leak grow when you repeat the "add-remove" steps or is the leak constant?

Can you observe the same leak without your `useMemoryLeaksDebugger`?

**Comment by angeloocana** [comment]
1) I'm not being able to create a production build because of the WeakRef, I will keep trying:
https://vercel.com/angeloocana/csb-77v5m/3ivamyw64?redirect=1

2) Yes, the leak grows as you click Add/Remove. More and more nodes stay in memory.

3) Yes, I created another sandbox https://codesandbox.io/s/gifted-brook-q5mk8?file=/src/App.js:761-769
I notice that the bug only happens when the component has an useEffect.
![react_bug_2](https://user-images.githubusercontent.com/5487699/100884229-3931fb80-347f-11eb-9d41-a9b1389fc6b3.gif)

**Comment by angeloocana** [comment]
Yes it happens on a production build https://csb-77v5m-9nzbxhxjh.vercel.app/


![react_bug_3](https://user-images.githubusercontent.com/5487699/100885843-1bfe2c80-3481-11eb-86bb-0f7bdb7f3bce.gif)

**Comment by ampratt** [comment]
did you ever get anything solved on this? I am having a similar issue and so far every attempt to clean possible memory leaks has not helped :-(
