### ISSUE TITLE
Bug: useState initial value overrides itself with each render

### ISSUE THREAD

**Issue by giladv** [facebook/react#20360]
given the following component
```
export default function Test() {
  const [test] = useState(Math.random());

  useEffect(() => {
    console.log('mount')
    return () => console.log('unmount');
  }, []);

  console.log(test);

  return null;
}
```
i'm expecting to get the same random number logged on every render

but this is what i'm getting in the console
```
- 0.03154673508944783
- 0.055598314429445184
- mount
```

React version: 16.13.1

**Comment by giladv** [comment]
i can see now that it's because of strict mode. 
but seriously, this functionality of strict mode does not make any sense. yes you get to detect user errors, but you also change fundamentally how some hooks behave and rendering some of them useless. like, why do i need useMemo if it doesn't really work on strict mode?

**Comment by eps1lon** [comment]
I understand the frustration this might cause. The idea is that you learn about the different phase of React once and then apply this knowledge to the hooks.
You can learn more about it in https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects.

The docs are currently overhauled with a hooks-first approach. After that we can take a look if we still need an extra hint.
