### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by amir-beheshty** [facebook/react#20373]
This behavior has changes in React version `17.0.x`.

[Clean-up function should execute when the component unmounts](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1), and I've noticed in `React v.17` by the time cleanup function executes, React referenced elements are no longer available. 

React version: 17.0.1

_To be clear, either this is a bug or the pertinent section on the docs aren't quite accurate in explaining exactly when return callback of `useEffect` executes._ 

**Link to code example:**

[Working example with `React v.16`](https://codepen.io/amir-beheshty/pen/jOMWmZK?editors=0010) 
[Example with `React v.17`](https://codepen.io/amir-beheshty/pen/jOMWmjQ)

_Notice `unmountSuccessful` logs _before_ `divRef` in `React v.17` example._

[This is the only relevant change I noticed from the changelog](https://github.com/facebook/react/pull/17925). 

If the behavior of `useEffect` clean-up has changed it should be reflected on the docs. 

**Code Snippet:**
```javascript
const App = () => {
  const divRef = React.useRef(null);
  
  React.useEffect(() => {
    console.log('divRef ::', divRef.current)
    return function cleanUp() {
      console.log('[cleanUp] divRef ::', divRef.current)
    }
  }, [])
  return (
    <div ref={divRef}>
      Open Browser's Console For Output
    </div>
  )
}

ReactDOM.render(
  <App />,
  document.getElementById('root')
);

const unmountApp = () => {
  console.log('unmounting root...')
  const node = document.getElementById('root');
  const unmountSuccessful = ReactDOM.unmountComponentAtNode(node);
  console.log('unmountSuccessful ::', unmountSuccessful)
};

window.setTimeout(unmountApp, 1500);
```

**Comment by LXSMNSYC** [comment]
Have you used `useLayoutEffect`? `useLayoutEffect` has the same timing as `componentWillUnmount`. `useEffect` always happens after the whole VDOM tree has been committed.

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/reactjs/reactjs.org/issues/3427.
