### ISSUE TITLE
Security: Update react-addons-pure-render-mixin to latest fbjs

### ISSUE THREAD

**Issue by redonkulus** [facebook/react#20378]
Resolves: [SNYK-JS-NODEFETCH-674311](https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311)

I know `react-addons-pure-render-mixin` is deprecated and hasn't been updated in 3 years, but it relies on an old version of `fbjs@0.8.17`. If we could update the mixin package to use latest `fbjs`, this would remove the `isomorphic-fetch` dependency and remove this security vulnerability warning. 

It is not possible for us to refactor 100's of components to not use the mixin at this time.

Dependency chain:
react-addons-pure-render-mixin@15.6.2 > fbjs@0.8.17 > isomorphic-fetch@2.2.1 > node-fetch@1.7.3

**Comment by carystanley** [comment]
Sadly many of the deprecated addons have the same issue (they have an old version of fbjs as a dependency)
The addons make very little use of fbjs, it might be wiser to remove fbjs as a dependency all together, like what was done for create-react-class https://github.com/facebook/react/issues/19840

react-addons-pure-render-mixin - only uses shallowCompare from fbjs
react-addons-shallow-compare - only uses shallowCompare from fbjs
react-addons-update - only uses invariant from fbjs

**Comment by gaearon** [comment]
I just published 15.6.3 of these three packages that remove the fbjs dependency.

**Comment by redonkulus** [comment]
@gaearon Thanks so much for the quick turnaround. It's appreciated!
