### ISSUE TITLE
Bug: react-hooks/exhaustive-deps false positive on TypeScript generic type variable

### ISSUE THREAD

**Issue by mschl0ss** [facebook/react#20395]
React version: 16.13.1

## Steps To Reproduce

1.  Use type generics in a useEffect.

Code example:
```TypeScript
function useBug<T>(): void {
  useEffect(() => {
    let bug: T;
  }, []); // <-- ESLint error: React Hook useEffect has a missing dependency: 'T'.

}
```

## The current behavior
Dependency array throws ESLint error.

```
React Hook useEffect has a missing dependency: 'T'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

## The expected behavior
No missing dependencies reported.

**Comment by sweetliquid** [comment]
Can I take this?

**Comment by sweetliquid** [comment]
@danielmiladinov

**Comment by eps1lon** [comment]
@mschl0ss We can't reproduce the reported bug with our versions of `@typescript-eslint/parser` and `eslint-plugin-react-hooks` (https://github.com/facebook/react/pull/20432 adds a passing test that replicates your report). Could you run `npx envinfo --npmPackages '{eslint,eslint-plugin-react-hooks,@typescript-eslint/*}' --showNotFound` and report back with the result?

**Comment by sweetliquid** [comment]
I built a sandbox to reproduce this problem:

![image](https://user-images.githubusercontent.com/18693190/101906175-83d81400-3bf3-11eb-9f20-9c042784600f.png)

[![Edit facebook/react/issues/20395](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/facebookreactissues20395-lt33t?fontsize=14&hidenavigation=1&theme=dark)

**Comment by mschl0ss** [comment]
@eps1lon Running that command produced this result:

```
npx: installed 1 in 3.21s
```

Now I do not see the bug anymore, so I guess that did fix it.  Can you explain to me what the command did?  Also, why is @sweetliquid seeing the error in his sandbox?

**Comment by eps1lon** [comment]
> I built a sandbox to reproduce this problem:

codesandbox might use outdated dependencies which we can't fix. If I download the codesandbox and install it I get no lint errors which hints at outdated dependencies in codesandbox.

> Running that command produced this result:

It should've actually printed something more but I forgot to add an important flag: `--fullTree`. Could you run `npx envinfo --npmPackages '{eslint,eslint-plugin-react-hooks,@typescript-eslint/*}' --showNotFound --fullTree` and post the results?

**Comment by mschl0ss** [comment]
Results:
```
npx: installed 1 in 1.494s

  npmPackages:
    @typescript-eslint/eslint-plugin:  4.9.0
    @typescript-eslint/experimental-utils:  4.9.0
    @typescript-eslint/parser:  4.9.0
    @typescript-eslint/scope-manager:  4.9.0
    @typescript-eslint/types:  4.9.0
    @typescript-eslint/typescript-estree:  4.9.0
    @typescript-eslint/visitor-keys:  4.9.0
    eslint:  7.14.0
    eslint-plugin-react-hooks:  4.2.0
```

**Comment by mschl0ss** [comment]
The bug seems to have gone away.  I worry that I'm giving you the false impression that the bug is being reproduced with the versions reported above.

**Comment by eps1lon** [comment]
Fairly certain this error was fixed at some point. Make sure to use the latest version of `eslint-plugin-react-hooks` and `@typescript-eslint/parser`. If the error persists please let me know and share the result of `npx envinfo --npmPackages '{eslint,eslint-plugin-react-hooks,@typescript-eslint/*}' --showNotFound --fullTree`

**Comment by ecraig12345** [comment]
I hit this too, and it went away after deleting old eslint caches. Something to try if anyone else happens onto this issue.
