### ISSUE TITLE
Bug: Shows error when jsx is react-jsx in tsconfig instead of react

### ISSUE THREAD

**Issue by bineetNaidu** [facebook/react#20391]
React version: 17.0.1

## Steps To Reproduce

1. npx create-react-app [your project name] --template typescript
2. set target in tsconfig to ESNEXT

## The current behavior
In VS Code their is many syntax error highlight and it says "Cannot use JSX unless the '--jsx' flag is provided.ts(17004)"

## The expected behavior
It Should be normal like other version of react usage

## Screenshots
tsconfig.json
![Screenshot from 2020-12-07 17-09-22](https://user-images.githubusercontent.com/66471461/101346741-050b7000-38af-11eb-89f4-1cb40cf9099e.png)
index.tsx
![Screenshot from 2020-12-07 17-10-37](https://user-images.githubusercontent.com/66471461/101346839-2a987980-38af-11eb-9ebd-e63388f52df1.png)

**Comment by eps1lon** [comment]
Thanks for the report.

VSCode is, by default, using their own version of TypeScript. In your case: 4.0.3. However, `"jsx": 
 "react-jsx"` is only supported starting with TypeScript 4.1. You can change the version though to the version used in your package:
![react-jsx-vscode](https://user-images.githubusercontent.com/12292047/101360138-8bb75180-389d-11eb-89d8-e921667c1633.gif)


<details>
<summary>how to find the current version of TypeScript used in VSCode</summary>
![101346839-2a987980-38af-11eb-9ebd-e63388f52df1](https://user-images.githubusercontent.com/12292047/101359911-311df580-389d-11eb-89f8-91b288731653.png)

</details>

**Comment by bineetNaidu** [comment]
Thanks for letting me to know, I thought that it was a bug :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by Cidrax** [comment]
Im using WebStorms and have the same issue.
