### ISSUE TITLE
Bug: cannot find module "react-transport-dom-webpack/node-loader" in windows7

### ISSUE THREAD

**Issue by Topthinking** [facebook/react#20392]
`yarn build`

![54FBECBA-55DD-41bc-ADDA-DBABBC00C660](https://user-images.githubusercontent.com/13382821/101361724-42640380-3897-11eb-8243-21df67f4c7c9.png)

**Comment by Topthinking** [comment]
![1](https://user-images.githubusercontent.com/13382821/101362644-47758280-3898-11eb-8164-473ccfe31167.jpg)

**Comment by bvaughn** [comment]
I'm sorry you're not able to run `yarn build` successfully. I'm sure you've probably done this, but make sure you run `yarn` in the main directory to install dependencies and initialize the workspace.

I don't think we have the bandwidth to support this kind of system/build problem via GitHub issues though so I'm going to close this issue. We can keep chatting here if you have follow up questions.

**Comment by Topthinking** [comment]
![2](https://user-images.githubusercontent.com/13382821/101641589-d7970180-3a29-11eb-842d-b1855ff43bd7.gif)

**Comment by Topthinking** [comment]
![3](https://user-images.githubusercontent.com/13382821/101643133-b6371500-3a2b-11eb-88b4-1f1b539e2ef0.gif)
