### ISSUE TITLE
Bug: eslint-plugin-react-hooks does not catch early returns in anonymous default exports

### ISSUE THREAD

**Issue by dreyks** [facebook/react#20408]
React version:
17.0.1

## Steps To Reproduce
1.
```jsx
import { useEffect } from 'react'

export default () => {
  if (true) return false

  useEffect(() => {})

  return false
}
```

2. run the linter

## The current behavior
No errors

## The expected behavior
error  React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?

failing test-suite case
```
{
  code: `
    export default () => {
      if (cond) {
        useConditionalHook();
      }
    }
  `,
  errors: [conditionalError('useConditionalHook')],
},
```

**Comment by julien51** [comment]
(painfuly) confirmed!

**Comment by eps1lon** [comment]
Unfortunately, this is expected behavior. The plugin requires that you name your function components:

> Calls to Hooks are either inside a PascalCase function (assumed to be a component) or another useSomething function (assumed to be a custom Hook).

-- https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce

**Comment by dreyks** [comment]
I see. sounds fair, thanks for the explanation
