### ISSUE TITLE
Bug: changing order of DOM elements causes scroll to change (and follow visible element)

### ISSUE THREAD

**Issue by IndProgo** [facebook/react#20405]
When changing order of an element with a key, and if it has been visible and it is moved "upwards" in the list, browser would scroll to the element's new position, but would not if moving the element "downwards" and also would not if the element is not visible (scrolled out)

React version: 16+

## Steps To Reproduce
https://codesandbox.io/s/item-move-react-scroll-to-glitch-ins1t

1. Press the first button on the left side "Scroll item into view", just to make target element visible
2. Press the second button "Move item to index 100" to reorder the element and move it "up". Browser would scroll to its new position.
(Pressing "Move item 10 up" would make scroll to continue following the element)
3. Press "Move item back" will place the element in its original position "down the list" and scroll would not follow then. 
4. Then pressing "Move item 10 up"  multiple times would not cause scroll to follow, until the element is back in the visible area

## The current behavior
Scroll sometimes changes unexpectedly when DOM elements are reordered

## The expected behavior
Not to change scroll position

Comparing to vanilla version of the same example
https://codesandbox.io/s/item-move-react-scroll-to-glitch-forked-y7lln
scroll only slightly changes

**Comment by robertpiosik** [comment]
You might have expected behavior by adding `overflow-anchor: none;` on list element. More on this [here](https://developers.google.com/web/updates/2016/04/scroll-anchoring).

**Comment by robertpiosik** [comment]
Hey @IndProgo, simply add `overflow-anchor: none;` on list element.
More on this [here](https://developers.google.com/web/updates/2016/04/scroll-anchoring) and [here](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor).
