### ISSUE TITLE
Bug: event.persists() in React 16.11.101 is not persisting the current target information and it is getting nullified. 

### ISSUE THREAD

**Issue by gouri-star** [facebook/react#20411]
event.persists() in React 16.11.101 is not persisting the current target information and it is getting nullified.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by gouri-star** [comment]
Thanks for replying back 
Here is the code 
function Click() {
  // Declare a new state variable, which we'll call "count"

  var count = 0;
  var flag = 0;
  const changeClick = (event) => {
    count = count + 1;
    console.log(count);

    if(!flag) {
      flag = 1;
     
       evt = event.currentTarget;
      // console.log(evt);
       event.persist();
      // console.log(event);
        console.log(event.currentTarget); // This is obtained as null
     
      setTimeout(() => {
       console.log(event);
      console.log(event.currentTarget); // This is obtained as NULL
        console.log(count);
        if(count>=2)
          {
            handleDoubleClick();
           count =0;
           flag = 0;
            console.log(count);
           
          }
        if(count === 1)
          {
            singleClick();
            count =0;
           flag = 0;
            console.log(count);
          }
      }, 250);
    }
  };
  
  return (
    <div>
        <h1>Clicks</h1>
       
        <button
          type="button"
          onClick={changeClick}
     onMouseUp = {handlemouseup}
    onMouseDown = {handlemousedown}>Click me </button>
      </div>
  );
  
  function singleClick(){
    console.log('single click');
  }
  
  function handleDoubleClick() {
    console.log('Double click');
  }
  
  function handlemouseup() {
    console.log('mouse up');
  }
  
  function handlemousedown() {
    console.log('mouse down');
  }
}
ReactDOM.render(<Click />, document.getElementById('root'));

Try executing this sample example with React 16.11.101
on a simple HTML file.
Inside the setTimeout () we can see that when we are trying to print event.currentTarget it is throwing a NULL value.

**Comment by gaearon** [comment]
`event.currentTarget` changes while the event traverses the tree so it's not expected to stay pointing at some value.
