### ISSUE TITLE
Attach event per react container root, rather than on the document

### ISSUE THREAD

**Issue by chenglou** [facebook/react#2043]
@nathansobo will that help your event perf issues a bit? I'm not familiar with atom's plugin infrastructure, But this'll help if you have `<Editor/><Plugin1/>` (two `renderComponent`s). Doesn't help if you have `<Editor><Plugin1/></Editor>` though, but I have some ideas to optimize events a bit more.

This is nonetheless an ok idea, I think.
@spicyj

**Comment by gaearon** [comment]
As far as I can tell https://github.com/facebook/react/pull/8117 was the latest attempt to do this. It has requested changes (that weren't addressed). So if somebody wants to pick this up they'll probably want to read the discussion there.

**Comment by kentcdodds** [comment]
Just FYI, this effort may get new life due to: https://github.com/kentcdodds/react-testing-library/issues/35

If I can't push this along myself, I'll try to encourage others to do so. Thanks!

**Comment by gaearon** [comment]
@trueadm has been working on this. Not yet 100% sure but it's likely we'll do this change in a major (right now it's behind a flag).

**Comment by gaearon** [comment]
We did this.
https://reactjs.org/blog/2020/08/10/react-v17-rc.html
