### ISSUE TITLE
Feature Request(devtools): `launch-editor` for selected component

### ISSUE THREAD

**Issue by Airkro** [facebook/react#20435]
### Why: 

User can open the source file in editor/ide by one-click.

It' is a useful feature in `vue-devtools`.

---

### How: 

Add a click event on here:

https://github.com/facebook/react/blob/cdfde3ae110844baf068706e7ed3fe97ec15f1d7/packages/react-devtools-shared/src/devtools/views/Components/InspectedElementView.js#L226-L228

call ```fetch(`/__open-in-editor?file=${fileName}:${lineNumber}`)```

Add [launch-editor-middleware](https://github.com/yyx990803/launch-editor) to dev-server(or any scaffold handle by himself)

---

Before anyone(maybe me) sends a PR, I want to know how do the react-team thinks about it?

**Comment by gauravverma029** [comment]
dsfsdfdsf

**Comment by iChenLei** [comment]
My naive implemention #20821 
but need facebook/create-react-app support https://github.com/facebook/create-react-app/pull/10563

**Comment by Airkro** [comment]
#22649
