### ISSUE TITLE
Using dangerouslySetInnerHTML with <Script> Tag?

### ISSUE THREAD

**Issue by iwantHD** [facebook/react#20446]
Backend return an html type string and I want render in react through

<div dangerouslySetInnerHTML ={{__html : html}}></div>

however, html contains the JS code that dynamically add data to <Table> Tag and it does not render any data in my page
the table is empty

How could solve this problem?

Thanks for any ideas

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by TryingToImprove** [comment]
If I understand correctly you want to render a `<script>` and have the code executed.

This example https://codesandbox.io/s/funny-shape-x71bp?file=/src/App.js tries do that but are unable to do so.

Maybe this article will help you @iwantHD  https://medium.com/@suncommander/how-to-inject-scripts-using-dangerouslysetinnerhtml-on-client-side-rendering-973037cc06b7

**Comment by SimonSchick** [comment]
This looks like intended behaviour, [internally react](https://github.com/facebook/react/blob/993ca533b42756811731f6b7791ae06a35ee6b4d/packages/react-dom/src/client/setInnerHTML.js) uses the `innerHTML` setter (as implied by the property itself).

Inserting a script tag via setting `innerHTML` generally seems to not execute the script, (probably for XSS prevention):

```js
{
    const container = document.createElement('div');
    document.body.appendChild(container);
    setTimeout(() => {
        container.innerHTML = '<script>alert("test");</script>';
        console.log('done');
    }, 1);
    console.log(container);
}```

You are probably better off using eval or `new Function(...)`, which are still not ideal.

**Comment by bilalebi** [comment]
I had the same issue and used [dangerously-set-html-content](https://github.com/christo-pr/dangerously-set-html-content) package which does exactly what you want.

I hope React team will alter `dangerouslySetInnerHTML` behaviour to support `<script>` tags in the futur.

**Comment by bryanian01** [comment]
i had issue not working properly
https://codesandbox.io/s/html-react-parser-forked-hrqm1?file=/src/index.tsx
