### ISSUE TITLE
[eslint-plugin-react-hooks]: could not find hook called conditionally when using an anonymous function component

### ISSUE THREAD

**Issue by woshichenxu2016** [facebook/react#20448]
React version: 17.0.1

my component file is like:

`export default function(props) {

  if (props.data > 1) {
    useEffect(function() {
      
    })
  }
  return (
    <div> data</div>
  )
}`

my .eslintrc.json file like this:
`{
  "extends": [],
  "plugins": [
    "react-hooks"
  ],
  "rules": {
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "error"
  },
  "parser": "babel-eslint"
}`

**Comment by eps1lon** [comment]
If you put your code into code blocks it should be completely visible. You can learn more about code blocks under the "Syntax Highlighting" section on https://guides.github.com/features/mastering-markdown/.

That being said, I believe React purposely does not support this case. There has to be some mechanism to detect if a function is a component and React has chosen "function with a name where the first letter is uppercase". 

Does the issue persist if you name your function appropriately? 

Naming your function has the benefit that  your easier identify the component by its name (e.g. warnings in the console, react devtools etc). You can find more details about how the plugin works on https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce

**Comment by eps1lon** [comment]
Closing due to lack of response and because this is expected behavior:

> Calls to Hooks are either inside a PascalCase function (assumed to be a component) or another useSomething function (assumed to be a custom Hook).

-- https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce
