### ISSUE TITLE
Bug: React DevTools components view is blank (reproduced in standalone mode)

### ISSUE THREAD

**Issue by mglukhovsky** [facebook/react#20455]
## Environment:
- macOS 11.0.1 Big Sur, on an Apple Silicon (M1) chip
- Safari 14.0.1
- React 17.0.1
- React DevTools 4.10.1, running in standalone mode via Electron 11.1.0 (darwin-arm64 build)
- New project using create-react-app . with the useScript hook to add the <script> tag required by React DevTools.

## Steps to reproduce
1. Install `react-devtools` using `npm install --save-dev react-devtools`.
2. A <script> for the React DevTools is added in App.js. Start the DevTools in standalone mode
```
./node_modules/react-devtools/bin.js
```

3. Start the React app's development server:
```
yarn start
```

Refresh the React app if needed to establish a connection with the DevTools. The _Components_ view is blank (no matter what filters are applied):

![](https://github.com/mglukhovsky/react-devtools-components-blank/blob/master/blank-components-react-devtools.gif?raw=true)

Link to code example:  [mglukhovsky/react-devtools-components-blank](https://github.com/mglukhovsky/react-devtools-components-blank)

## The current behavior
Components view is blank; the React DevTools component seems to register the app but nothing further.

## The expected behavior
Full component tree and a working integration between Safari and standalone DevTools.

**Comment by mglukhovsky** [comment]
Possible duplicate of #20261, but they're using a different environment so it's hard to tell.

**Comment by gauravverma029** [comment]
Test

**Comment by bvaughn** [comment]
I can't reproduce the empty tab behavior using the repro you linked to.

![Screen Shot 2020-12-14 at 4 51 48 PM](https://user-images.githubusercontent.com/29597/102140030-aef97800-3e2c-11eb-9c91-3372f2a04393.png)

**Comment by bvaughn** [comment]
Possible it has to do with the Electron version?

**Comment by bvaughn** [comment]
Can't repro this with the linked project. Going to close for now unless we get a better repro (or some additional info that helps us repro).

**Comment by BiscuiTech** [comment]
Can confirm this is happening on the standalone version on Windows. Initial messages are sent: 
![image](https://user-images.githubusercontent.com/17841919/105091744-4c6c4b00-5a6e-11eb-84a0-e70a3e0144c9.png)
but the app stays blank:
![image](https://user-images.githubusercontent.com/17841919/105091765-555d1c80-5a6e-11eb-8a7e-ed850ea468cb.png)

**Comment by Devil-Cong** [comment]
I use the MobX, so according to [the tutorial](https://mobx.js.org/installation.html#use-spec-compliant-transpilation-for-class-properties), I added the babel plugin  `["@babel/plugin-proposal-class-properties", { "loose": false }]`  and I have the same problem. When remove the babel plugin, the problem is solved. Does anyone know why?
