### ISSUE TITLE
Bug: react-devtools not working inside react based chrome extensions

### ISSUE THREAD

**Issue by fastsyrup** [facebook/react#20453]
react-devtools not working inside react based chrome extensions

React version: 17.0.1

## Steps To Reproduce

1. install react-devtools extension in chrome
2. git clone https://github.com/lxieyang/chrome-extension-boilerplate-react
3. cd into directory
4. yarn install
5. yarn build 
6. open chrome extensions page
7. change to developer mode
8. load unpacked, point to the directory build within chrome-extension-boilerplate-react directory
9. click on react dev tools extension
10. The following text is displayed "This is a restricted browser page. React devtools cannot access this page."
11. When inspecting the page, the tabs components and profiler are NOT shown

Link to code example: https://github.com/lxieyang/chrome-extension-boilerplate-react

## The current behavior
1. When clicking on the react devtools chrome extension: "This is a restricted browser page. React devtools cannot access this page."
2. Also when inspecting the pages of the chrome extension, the tabs components and profiler are NOT shown

## The expected behavior
1. When clicking on the react devtools chrome extension: The devtools recognize that the page is using react
2. when inspecting the pages of the chrome extension, the tabs components and profiler are shown and populated

**Comment by bvaughn** [comment]
The error message you quoted in this issue explains that React DevTools *cannot* access restricted URLs:
> This is a restricted browser page. React devtools cannot access this page.

This is an intentional security limitation by the browser. To my knowledge, the only workaround is to launch Chrome with the unsafe #extensions-on-chrome-urls flag and even then, I don't believe it is possible to use a wildcard for URLs. (The extension would have to have an explicit list of protected URLs in its manifest, so the use case you're describing wouldn't be feasible even so.)

**Comment by djsmacker01** [comment]
I'm experiencing such error now

**Comment by bvaughn** [comment]
Please read the comment right above yours @djsmacker01. This use case is not supported.

**Comment by djsmacker01** [comment]
> Please read the comment right above yours @djsmacker01. This use case is not supported.

Thanks boss

**Comment by eggachecat** [comment]
> Please read the comment right above yours @djsmacker01. This use case is not supported.

hello any possible alternative for this use case?
I am currently using react to build a chrome extension popup page as a large frontend project and it is extremely useful to get the devtool works!
