### ISSUE TITLE
Clearer warning when replacing React-rendered children with a new root component

### ISSUE THREAD

**Issue by spicyj** [facebook/react#2045]
Suppose you have:

``` js
var TaskHeader = React.createClass({
    render: function() {
        return <div className="task-header-mid-container">
            <img />
            <h2>I'm a task!</h2>
        </div>;
    }
});

React.renderComponent(<TaskHeader />, $(".task-header-container")[0]);
```

and then you intend to run

``` js
React.renderComponent(<ADifferentTaskHeader />, $(".task-header-container")[0]);
```

to replace the header but accidentally run

``` js
React.renderComponent(<ADifferentTaskHeader />, $(".task-header-mid-container")[0]);
```

instead.

You should get an error or warning because you're blowing away the React-rendered contents of `.task-header-mid-container`, but none is given. You actually get the server-rendering checksum warning, but that's more confusing than anything and we should have an explicit warning for this, much like the one you get when calling setProps on a non-root component.

**Comment by gaearon** [comment]
Fixed by #2065.
