### ISSUE TITLE
Bug: Trailing Comma in Arrays and Dict

### ISSUE THREAD

**Issue by AstralPresence** [facebook/react#20450]
The learn react tic tac toe game tutorial shows a trailing comma at the end of dictionary values. This is known to cause issues with Internet Explorer. Hoping you can change that.

https://stackoverflow.com/questions/5139205/javascript-can-a-comma-occur-after-the-last-set-of-values-in-an-array

React version:  LTS

## Steps To Reproduce

1. Run tic tac toe tutorial code

Link to code example:

## The current behavior
Internet Explorer throws weird errors

## The expected behavior
Internet Explorer loads the tic toe game without any ussyes

**Comment by bvaughn** [comment]
Trailing commas in general (everywhere but function parameters) are supported by IE9+ [according to Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas). I believe the tutorial only shows trailing commas that would be IE 9+ compatible then.

Regardless, the tutorial also shows other syntax (like arrow functions) that are not IE compatible at all (even v11). I don't think it's a goal of the tutorial to support legacy browsers without at least a compilation step (like Babel). In my opinion, the tutorial should be written using modern (but not cutting edge) syntax that will be familiar to the majority of developers reading it.
