### ISSUE TITLE
Give example of production ready workflow with React JS

### ISSUE THREAD

**Issue by christianalfoni** [facebook/react#2046]
Hi!

I've had a great time working with React JS, but I had big issues with setting up a good workflow for it. As with most library/framework sites the examples of "getting started" is too simple. Developers considering React JS will need to put it in their workflow and it is currently, to my experience, difficult to figure out how.

I wrote a post on how I experienced getting React JS up and running with a workflow, ending up with browserify: [React JS and browserify workflow](http://christianalfoni.github.io/javascript/2014/08/15/react-js-workflow.html). It points out how difficult it is and suggests a solution I hope will help people out.

So the request here is really to put an example of a workflow setup on the React JS site. It would make it a lot easier for developers to adopt the library.

Thanks for this great contribution to the world of JavaScript :-)

**Comment by zpao** [comment]
Going to close and track as a part of #5679
