### ISSUE TITLE
Bug: This isn't a bug but a feature request  

### ISSUE THREAD

**Issue by phtom** [facebook/react#20467]
React version: 17

This isn't  a bug but a feature request that many devs would like to see in react including me.
For many times we have to use map funtion to loop items in a array just like the following:

`exampleArray.map((index) => (
      <motion.li key={index} className="item" variants={item} />
    ))}`

The sample above works great when we want to map an object, group of objects or arrays. There are some cases where we would like to do different. For example, in the code bellow I want inside JSX to loop 6 times a line of code:

`{[0, 1, 2, 4, 5].map((index) => (
      <motion.li key={index} className="item" variants={item} />
    ))}`

The code above seems off, we should be able to make a for cycle inside JSX. I would like to repeat the line 6 times to create 6 circles.

Do you think in future versions we could do it?  Using this way doesn't seem great.

I wrote here because I didn't see any link pointing to feature or improvement request.

**Comment by titivermeesch** [comment]
I feel like this is more something that should go [here](https://github.com/facebook/jsx) ?

It would feel a little weird and against the syntax in my opinion to have a for loop directly inside JSX (if that is what you are asking).

Did you thought about a syntax like this?

```
export default function App() {
  const elements = [];

  for (let i = 0; i < 5; i++) {
    elements.push(<div key={i}>Item</div>);
  }

  return <div>{elements}</div>;
}
```

**Comment by yume-chan** [comment]
There are so many ways to [create a range](https://stackoverflow.com/a/10050831).

My personal favorite is

```js
Array(6).fill().map((_,index)=>index)
```

**Comment by phtom** [comment]
> There are so many ways to [create a range](https://stackoverflow.com/a/10050831).
> 
> My personal favorite is
> 
> ```js
> Array(6).fill().map((_,index)=>index)
> ```

It looks like a good solution. I still think that we should be able to loop with a for cycle inside JSX, sometimes it could make sense to use.

**Comment by bvaughn** [comment]
This isn't the right repo to discuss this feature request, but there is another RFC / PR open that's related that I'll link to:
https://github.com/facebook/jsx/pull/99 (and its predecessor https://github.com/facebook/jsx/pull/98)

Going to close this issue out and suggest moving the conversation over to the other PR.
