### ISSUE TITLE
Bug: Setting up environment and build to contribute

### ISSUE THREAD

**Issue by matheushf** [facebook/react#20464]
React version: 17.0.0 (master)

## Steps To Reproduce

1. Fork & Clone repository
2. `yarn`
3. `yarn build react/index,react-dom/index,scheduler --type=NODE`

Link to code example:

## The current behavior
```
.../react/scripts/rollup/build.js:44
  throw err;
  ^

Error: Command failed: npm pack build/node_modules/jest-react

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm pack build/node_modules/jest-react'
}
```

With only `yarn build` it fails on `Error: Command failed: npm pack build/node_modules/react-reconciler`

## The expected behavior
Build without problems

**Comment by eps1lon** [comment]
@matheushf Is this still a problem in the latest commit in `main`? If so, please run `npx envinfo` and post the results.
