### ISSUE TITLE
Bug: Module not found: Can't resolve 'react-transition-group' in 'C:\my\file\path'

### ISSUE THREAD

**Issue by drewren25** [facebook/react#20462]
I was searching how to animate with react and came across the "Animation Add-Ons" page of reactjs.org. There were given instructions on how to import so I copy pasted it to my project but when I checked my application in my google chrome browser I was given the message "Module not found: Can't resolve 'react-transition-group' in 'C:\my\file\path'". The file path is arbitrary. Not sure what I did wrong, I haven't even done anything with it in the rest of my code I just tried importing it. I'm quite new to React so I apologize if this is a dumb question and I'm just missing something obvious! I also apologize if this issue isn't formatted well, I'm also new to posting on Github.

## Steps To Reproduce

1. Create a react app
2. At the top of the text editor, type "import ReactCSSTransitionGroup from 'react-transition-group';" as offered by the reactjs.org page "Animation Add-Ons"
3. Open the application in a browser
4. Then I got the error message in the browser

Code example:
import ReactCSSTransitionGroup from 'react-transition-group';
I just put this at the top of my project and haven't done anything else with it.

## The current behavior
Module not found: Can't resolve 'react-transition-group' in 'C:\my\file\path'

## The expected behavior
A successful import of ReactCSSTransitionGroup

**Comment by bvaughn** [comment]
Before you'll be able to import the `react-transition-group` module, you'll need to install it as shown [here](https://github.com/reactjs/react-transition-group/tree/v1-stable#installation):
```
# npm
npm install react-transition-group@1.x --save

# yarn
yarn add react-transition-group@1.x
```

It's a separate NPM package. It doesn't get installed with React automatically.

Hope this helps!

**Comment by drewren25** [comment]
Ah I see ok thank you!

**Comment by suddhu-bharti** [comment]
Thanks a lot!
