### ISSUE TITLE
ContentEditable element and caret position jumps

### ISSUE THREAD

**Issue by slorber** [facebook/react#2047]
Hi.

I don't think if this is really a bug nor if this can be fixed easily but this is an annoying behavior.

See http://jsfiddle.net/kb3gN/4603/
The cursor jumps unexpectedly as the contenteditable element is rerendered.

Does this mean that we should always use contentEditable elements as uncontrolled components?

**Comment by abritinthebay** [comment]
I know this is an old closed issue but I wanted to chime in on a simple solution for people that run into it.

This only happens when you mutate the value so the DOM representation is different to a state value that's being set.

Simple solution - add a ref, mutate the ref's value to the manipulated one, then update the state. It's not quite as clean but it solves all the problems.

**Comment by slorber** [comment]
@abritinthebay yes this looks like what is proposed in the linked StackOverflow question and this project: https://github.com/lovasoa/react-contenteditable

**Comment by clintharris** [comment]
For anyone else who, like me, ends up looking at this ticket because they think they need to roll their own contentEditable for a fancier text input: make sure to check out Facebook's [DraftJS](https://draftjs.org/) (and the 3rd-party [DraftJS Plugins](https://draft-js-plugins.com) project)--might save you _a lot_ of time.

**Comment by sontuphan** [comment]
> I know this is an old closed issue but I wanted to chime in on a simple solution for people that run into it.
> 
> This only happens when you mutate the value so the DOM representation is different to a state value that's being set.
> 
> Simple solution - add a ref, mutate the ref's value to the manipulated one, then update the state. It's not quite as clean but it solves all the problems.

This guy is awesome.

**Comment by covahn** [comment]
@sontuphan Your solution does not allow for two-way binding. Which is where problems arise.

**Comment by feketegy** [comment]
For another solution, using React hooks, you can still keep the state in the editable element, no need to move it up to the parent, and also fix the caret position too.

It's a hacky way to do it, but it works.

It fixes the caret positioning by getting the caret offset on the editable element using a ref, setting the state then setting that same caret offset back on the element ref after the state is updated.

It was tested in Chrome only, and for simple text content, but theoretically, it should work if the editable element contains child nodes too, I will test it and update the code pen.

https://codepen.io/feketegy/pen/RwGBgyq

**Comment by hannanstd** [comment]
https://stackoverflow.com/a/66198132/6937189

**Comment by sam0x17** [comment]
Anyone know how to do this outside of react?

**Comment by GowthamSelvaraju** [comment]
const moveCaretToEnd = () => {
        var el: any = textRef.current;
        const range: any = document.createRange();
        const sel: any = window.getSelection();
        let count_element: number = el.childNodes.length - 1;
        range.setStart(
            el.childNodes[count_element],
            el.childNodes[count_element].length || 1
        );
        range.collapse(true);
        sel.removeAllRanges();
        sel.addRange(range);
    };

    useEffect(() => {
        moveCaretToEnd();
    });

**Comment by giovannipds** [comment]
In case you're searching for a react HTML/WYSIWYG editor or similar: https://github.com/facebook/lexical

**Comment by mgl12432** [comment]
Hi, this issue is closed but when i was refered this page when i get this kind of problem. it couldn't resolve my isssue. so i got an answer from stack over flow. use the below link
https://stackoverflow.com/questions/75305047/contenteditor-div-repositions-caret-while-typing-in-react/75305423#75305423

**Comment by Konglomneshued** [comment]
> I know this is an old closed issue but I wanted to chime in on a simple solution for people that run into it.
> 
> This only happens when you mutate the value so the DOM representation is different to a state value that's being set.
> 
> Simple solution - add a ref, mutate the ref's value to the manipulated one, then update the state. It's not quite as clean but it solves all the problems.

Could you elaborate on this?  I can't seem to get my caret position to stay put when I mutate the ref and set the state.

**Comment by Konglomneshued** [comment]
Think I found [the answer by Lakshmaji](https://stackoverflow.com/questions/45306325/react-contenteditable-and-cursor-position).

**Comment by Quiddlee** [comment]
> Think I found [the answer by Lakshmaji](https://stackoverflow.com/questions/45306325/react-contenteditable-and-cursor-position).

Thanks! 🤝

**Comment by mdulc928** [comment]
For anyone cares still:
```
import clsx from 'clsx';
import React, { useRef } from 'react';

export type ExpandableTextboxProps = {
  initialValue: string;
  setValue: (newValue: string) => void;
};
export const ExpandableTextbox = ({
  initialValue,
  setValue,
}: ExpandableTextboxProps): JSX.Element => {
  const content = useRef<string>(initialValue);
  return (
    <span
      role='textbox'
      contentEditable
      className={clsx(
        'min-h-[5rem] resize p-2 border-dashed border w-full my-2 ml-2 caret-red-500',
      )}
      onInput={(e) => {
        content.current = e.currentTarget.innerHTML;
      }}
      onBlur={() => {
        setValue(content.current);
      }}
      dangerouslySetInnerHTML={
        content.current === initialValue ? { __html: initialValue } : undefined
      }
    ></span>
  );
};
```

**Comment by LavransBjerkestrand** [comment]
Here's one without `useRef` and `dangerouslySetInnerHTML`


```tsx
function GrowingTextArea() {
  const [value, setValue] = useState('')

  return (
    <span
      role="textbox"
      contentEditable
      style={{ whiteSpace: 'pre-wrap' }}
      onBlur={(event) => setValue(event.currentTarget.innerText)}
    >
      {value}
    </span>
  )
}
```

Add this if you are using a placeholder or similar using the `:empty` CSS selector
```tsx
onInput={(event) => {
  if (event.currentTarget.innerText === '\n') {
    event.currentTarget.innerText = ''
  }
}}
```
