### ISSUE TITLE
Bug: eslint --fix with react-hooks/exhaustive-deps isn't working

### ISSUE THREAD

**Issue by AsaAyers** [facebook/react#20475]
I'm trying to setup a new project and I can't get the exhaustive-deps autofix to work. I think it's a `react-hooks` bug because `--fix` works on other rules like `prefer-const`. I know this used to work because I have a project on eslint@5, eslint-plugin-react-hooks@1.6.0, eslint-plugin-react@7.13.0 where I rely on this behaviour every day.

My gist includes a `package.json` so you can see other dependencies if they're also relevant.
React version: 17.0.1
eslint-plugin-react-hooks: 4.2.0
eslint-plugin-react: 7.21.5

## Steps To Reproduce

```
git clone https://gist.github.com/833fc963aa7bf21f61c407491162b95e.git exhaustive-deps-auto-fix
cd exhaustive-deps-auto-fix
npm install

# At this step, eslint will auto-fix the preferConst, but doesn't autofix react-hooks/exhaustive-deps
eslint --fix component.jsx
```

```
asa:/tmp/exhaustive-deps-auto-fix$ eslint --fix component.jsx 

/tmp/exhaustive-deps-auto-fix/component.jsx
  10:6  warning  React Hook React.useEffect has a missing dependency: 'someProp'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

✖ 1 problem (0 errors, 1 warning)
```

Link to code example: https://gist.github.com/AsaAyers/833fc963aa7bf21f61c407491162b95e

## The current behavior

`react-hooks/exhaustive-deps` shows a warning, but I have to manually fix the dependencies

## The expected behavior

`react-hooks/exhaustive-deps` automatically fixes the dependencies

**Comment by eps1lon** [comment]
Thanks for the report!

`react-hooks/exhaustive-deps` does not provide fixes but suggestions. In other words: Missing dependencies are not automatically updated since this changes code behavior. Rules are discouraged from applying automated fixes that change behavior. 

You have to manually go through each reported `react-hooks/exhaustive-deps` violation and apply the suggestion. Your code editor might offer you help in applying these fixes.

**Comment by AsaAyers** [comment]
Was this a change in ESLint between 5-7, or between eslint-plugin-react-hooks 1.6-4.2? I really love using this to auto-fix my dependencies, so this really breaks my workflow.

I find that I basically don't have to think about dependencies as long as they get auto-fixed. I know there can be cases where you don't want something in the dependency array, but they're pretty rare (at least in my experience).

**Comment by eps1lon** [comment]
Thanks for the follow-up. It sounds like your concern was already addressed in https://github.com/facebook/react/pull/18437:

> This PR adds an escape hatch. Pass { enableDangerousAutofixThisMayCauseInfiniteLoops: true } and you get the old behavior. You've been warned.

Does this work for you?

**Comment by AsaAyers** [comment]
Thanks! That's exactly what I was looking for.
