### ISSUE TITLE
Bug: GetDerivedStateFromError did not render the standby UI correctly

### ISSUE THREAD

**Issue by victorykong** [facebook/react#20478]
React version: 17.0.1

## Steps To Reproduce

1. The React app generated by the Create-React app, written in the same code as in the CodesandBox, will show the hasError when the component encounters an error, but only for a split second, and then immediately show the error page
2. The result in CodesandBox is correct 

Link to code example: https://codesandbox.io/s/zen-herschel-ucmyg?file=/src/index.js

## The current behavior
The component failed to properly display the alternate UI after an error occurred

## The expected behavior
Component errors require the presentation of the alternate UI, not the error message page

**Comment by jbrudant** [comment]
According to https://github.com/facebook/create-react-app/issues/3627, this is expected behavior. If you close the overlay, you can see the "hasError" message. If you run your application in production, you will see the "hasError" message.

**Comment by victorykong** [comment]
Ok, Got it
