### ISSUE TITLE
Bug: React onMouseEnter, onMouseOver and onMouseLeave not firing as expected (Chrome)

### ISSUE THREAD

**Issue by tseveenganbold** [facebook/react#20483]
React is not firing onMouseLeave, onMouseOver, onMouseEnter events on images.(Chrome)

React version:
17.0.1

Code example: 
![carbon](https://user-images.githubusercontent.com/67759816/102604550-a2269e00-4124-11eb-8641-dbb3c0305d7d.png)

## The current behavior
Only changing the state when clicked

## The expected behavior
Changing the state when hovered

**Comment by KirankumarAmbati** [comment]
This worked for me:

```js
import React, { useState } from "react";
import "./styles.css";

export default function Image() {
  let [hovered, setHovered] = useState(false);

  return (
    <>
      <div
        className="App"
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        style={{ width: "100px", height: "100px" }}
      >
        <img
          style={{ border: "4px solid red", width: 100, height: 100 }}
          src="https://images.pexels.com/photos/1056251/pexels-photo-1056251.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
          alt="Test Img"
        />
      </div>
      <p>{hovered.toString()}</p>
    </>
  );
}

`

**Comment by koba04** [comment]
@tseveenganbold Could you create an example to reproduce this on a playground?
https://reactjs.org/docs/getting-started.html#online-playgrounds

**Comment by tseveenganbold** [comment]
@koba04  Yes :). Now i am confused because it works just fine on a playground but not on Chrome browser. Maybe it is Chrome problem? Codepen: (check console.log for state changing)
https://codepen.io/tseveenganbold/pen/bGwaxNj

**Comment by Nwon2464** [comment]
@tseveenganbold I guess it is because of the unsettled width and height of the image tag?

**Comment by jordyvandomselaar** [comment]
@tseveenganbold does it work on a playground when opening that playground in Chrome?

**Comment by bromanazzi** [comment]
Here's a codesandbox example

[https://codesandbox.io/s/little-pine-wpk988](https://codesandbox.io/s/little-pine-wpk988)

Move the mouse quickly in and out of the red boxes. The top one keeps the events in sync, while the lower one fails to fire some mouseleave events. Adding a large list of items to simulate slow rendering makes the issue more noticeable.

**Comment by Tomassito** [comment]
@bromanazzi So the only difference between working and not working example is that the working one is not using extracted components... 
I wonder what React team will comment on this!
@gaearon

**Comment by Messiahhh** [comment]
> Here's a codesandbox example
> 
> https://codesandbox.io/s/little-pine-wpk988
> 
> Move the mouse quickly in and out of the red boxes. The top one keeps the events in sync, while the lower one fails to fire some mouseleave events. Adding a large list of items to simulate slow rendering makes the issue more noticeable.

Amazing bug...

**Comment by blindbeat** [comment]
Unfortunately still an issue. If someone found a solution or workaround, it would be greatly appreciated

**Comment by narendrayogi** [comment]
I've removed image box and tried. The error may because of latency. Each time mount and unmount is happening in the not-working example.

[Codepen with useEffect](https://codesandbox.io/p/sandbox/still-sound-zwk9gc?file=%2Fsrc%2FApp.js%3A11%2C5)

If we comment the colour box as not working example doesn't need to render on every time then results are good even without commenting expensive list node. So passing props to html

<img width="1310" alt="Screenshot 2024-12-24 at 18 56 41" src="https://github.com/user-attachments/assets/5a626a8a-652d-43b1-8a65-db3ee3a5cd0f" />

This got more information about preserving the state on the same UI tree position: [ReactDev](https://react.dev/learn/preserving-and-resetting-state).

Our first example falls under, "Same component at the same position preserves state " and second example falls under, "Different components at the same position reset state "

**Comment by manal03** [comment]
onMouseOver works just like onClick still..........

**Comment by blindbeat** [comment]
I ended up implementing this custom hook to catch changes in the end: 
```tsx
interface Params {
  hovered: boolean;
  setHovered: (hovered: boolean) => void;
  ref: React.RefObject<HTMLElement>;
}

export const useHoverFix = ({ hovered, setHovered, ref }: Params) => {
  useEffect(() => {
    if (!hovered) return;

    let animationFrameId: number;
    const validateHover = () => {
      if (!ref.current?.matches(":hover")) setHovered(false);
      else animationFrameId = requestAnimationFrame(validateHover);
    };

    animationFrameId = requestAnimationFrame(validateHover);

    return () => cancelAnimationFrame(animationFrameId);
  }, [ref, hovered, setHovered]);
};
```

**Comment by amina-mari** [comment]
hello, everyone

In the last weeks I faced the same problem on my job (we use NextJS and React) and I figured out that I was testing the onMouseMove event with the DevTools open and I realized that the "click" that is fired when DevTools is open is in fact a Touch Event, not a Mouse Event. In my experience, when the console is closed, all Mouse Events worked just fine.
