### ISSUE TITLE
Feature Request : Static type checking

### ISSUE THREAD

**Issue by ravdsn** [facebook/react#20480]
If js have better static type checking and error messages, it would save a lot of Dev's valuable time. 

I mean it took me almost a day to find this simple bug.
<img src="https://user-images.githubusercontent.com/39956942/102493910-e3be3700-4099-11eb-9f5b-ea506b1a8090.jpg" width="500">

**Comment by eps1lon** [comment]
> If js have better static type checking and error messages, it would save a lot of Dev's valuable time.

You can either use Flow or TypeScript for type checking. 

I'm not familiar with how to setup flow but for TypeScript you should get it to work by installing `@types/react`. You have to setup static type checking first though. There's a whole section about [static type checking in React](https://reactjs.org/docs/static-type-checking.html#gatsby-focus-wrapper) in the docs. 

If there's anything missing, feel free to mention me again. We can discuss how to improve the docs in a [separate issue in the docs repo](https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) then.
