### ISSUE TITLE
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

### ISSUE THREAD

**Issue by 134355** [facebook/react#20488]
componentDidMount () {
  this.setState({})
}
componentWillUnmount () {
  this.setState = () => false
}

Quickly switch this component

**Comment by eps1lon** [comment]
Maybe we should expand the error message for `componentWillUnmount` to mention that functional state updates itself  are problematic?

```diff
-To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
+To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method and make sure no state updates are scheduled during `componentWillUnmount`.
```

Would that error message have helped you identify the issue?

**Comment by 134355** [comment]
How to cancel the operation

**Comment by bvaughn** [comment]
> How to cancel the operation

This depends on what's calling `setState` in your component. You didn't provide enough information on the issue for us to konw.

**Comment by 134355** [comment]
componentDidMount () {
  this.setState({
    money: this.props.money
 })
}

Operation as shown above

Problems with rapid creation and destruction

**Comment by behnammohammadkhani** [comment]
this article is useful
https://www.debuggr.io/react-update-unmounted-component/

**Comment by bvaughn** [comment]
@134355 Can you provide a runnable repro of the problem you're describing? Preferably on Code Sandbox, but it can be a link to a GitHub project if that's significantly more convenient for ou.

**Comment by 134355** [comment]
`class MyComponent extends React.Component {
  state = {
    money: 0
  }

  componentDidMount () {
    const { money } = this.props
    this.setState({
      money
    })
  }
}`

**Comment by bvaughn** [comment]
That's not really a full repro. I don't know what you mean by "_Quick switch components_". Can you provide a _full_ running repro (using something like Code Sandbox) that shows this bug?

**Comment by 134355** [comment]
I'm too hard
