### ISSUE TITLE
Bug: ReactDom error

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [facebook/react#20484]
![image](https://user-images.githubusercontent.com/64516009/102623996-63ff9d80-4169-11eb-8fb5-ce579fb64205.png)

React version:  "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-modal": "^3.12.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.1",
    "redux": "^4.0.5",
    "source-map-explorer": "^2.5.1"

## Steps To Reproduce

1. Create an app and use the reactdom to navigate to page.
2. Run the build script, it generate the min version.
3. Run the app in android webview
    a. Version: Lollipop, b. Chrome version 37

## The current behavior
a. The same works in latest android 10 with chrome 

## The expected behavior
b. Able to load the page.

**Comment by eps1lon** [comment]
Thanks for the report.

It looks like you're running React in an environment that does not implement [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). However, React requires `Set` to be implemented.

To learn more about the required environment for React, check out https://reactjs.org/docs/javascript-environment-requirements.html.
