### ISSUE TITLE
Feature: Need to show address of webpage even on warning

### ISSUE THREAD

**Issue by rishadbaniya** [facebook/react#20498]
Whenever i compile the code and run and if there is warning then it hides the address of the webpage of LAN network.  **WE NEED THAT ADDRESS EVEN IF THE CODE IS COMPILED WITH WARNING**

### If we compile the code correctly it says

Compiled successfully!
 You can now view <PROJECTNAME> in the browser
Local : http://localhost:3000
On Your Network : http://192.168.1.1:3000

### If there is some warning then it says:

Compiled with warning.
#Directory
Line: X:Y  #ERROR NAME

### I want the "on your network" link to be on the warning message too, something like this :

Compiled with warning.
#Directory
Line: X:Y ERROR NAME
Local : http://localhost:3000
On Your Network : http://192.168.1.1:3000

**Comment by eps1lon** [comment]
Thanks for the feedback.

Sounds like you're using `create-react-app` which is worked on in https://github.com/facebook/create-react-app. An issue here will likely be forgotten. I recommend you open a [new issue in facebook/create-react-app](https://github.com/facebook/create-react-app/issues/new/choose) instead.

**Comment by bvaughn** [comment]
Closing because this issue has been filed in the wrong repo.

**Comment by rishadbaniya** [comment]
oh god! I was in so much anger that i didnt see properly
