### ISSUE TITLE
Suggestion: detect and warn when new component types are always declared while rendering

### ISSUE THREAD

**Issue by markerikson** [facebook/react#20490]
React's reconciliation algorithm relies on reference comparisons of element types:

https://reactjs.org/docs/reconciliation.html

When a component type changes, React throws away the old component subtree and DOM and recreates them from scratch, under the assumption that the contents are likely completely different.

This means that defining a new component type in the middle of rendering will _always_ cause React to destroy and re-create a component subtree, because it's a new component type reference each time the parent renders:

```js
function ParentComponent() {
  // This creates a new `ChildComponent` reference every time!
  function ChildComponent() {}
  
  return <ChildComponent />
}
```

This is a really common mistake that I see happening a lot.

It would be really nice if React somehow had a way to detect and warn about this behavior in dev mode, similar to how it warns about infinite `setState` loops from function components.

No idea how this might be implemented, and I imagine it would be rather tricky, but it sure would be useful.

**Comment by markerikson** [comment]
After raising this discussion on Twitter, it looks like there's a WIP ESLint rule that would warn about this pattern:

https://github.com/yannickcr/eslint-plugin-react/issues/2749

**Comment by AriPerkkio** [comment]
It's also worth mentioning here that in practice these re-creations cause children of the nested components to lose state. This introduces bugs which are extremely difficult to spot - especially when this pattern is used by a component provided by dependency. This was the main issue the ESLint rule should prevent. Repro for these cases: https://codepen.io/ariperkkio/pen/vYLodLB

I also think React dev-tools don't detect these cases well. Render count is always 0 even if component is re-created multiple times. While the render count is valid the performance issue is invisible. I've been meaning to file an issue about the dev-tools but was waiting for the ESLint rule to get more attention first.

**Comment by gaearon** [comment]
This is better solved in a linter.
