### ISSUE TITLE
React Hooks - Downshift from readability

### ISSUE THREAD

**Issue by hamza-khan-mhk1** [facebook/react#20507]
After working with Class based components and Hooks, I reckon classes are always more readable and the code remains well structured. Using Hooks to write a complex component as an alternative to a class component is very less motivating. Using Hooks to write small functional components is acceptable but as soon as the component gets complex, Hooks start to feel annoying.

**Comment by bonoldie** [comment]
I mean JS is based on these two ways to build Objects, Classes and Functions.
The only thing I can immagine Is that at the beginning the scope would be a bit tricky to understand...
Hooks are beautiful and really game changing.

**Comment by robertpiosik** [comment]
Please elaborate where is the wall you see in function flexibility so you can't structure your code as you usually do inside a class.
