### ISSUE TITLE
Bug: Strange second argument passed to stateless component

### ISSUE THREAD

**Issue by Benno-Wu** [facebook/react#20516]
React version: 17.0.1 & 16.4.1

## Steps To Reproduce

1. create a functional component, import it and render in a class component
2. log arguments in that functional component

code example:
```
import React from "react";
export default function test (props) {
    console.log('main', arguments);
    return (
        <div>XXX</div>
    )
}

import Test from "./test.jsx";
class XXX extends Component {
 render(){
  return (
    <div className="App">
      <Test xxx='xxx'></Test>
    </div>
)}}

```

## The current behavior
arguments.length is 2, and the second one is always a empty object, likes '{}'

## The expected behavior
In normal use, I won't find this parameter, but I'm just a beginner, to see if there are any missing features.
I just want to know what it is, maybe just like this issue  #7902, even if it doesn't seem to affect anything

**Comment by TryingToImprove** [comment]
The second argument passed is part of the legacy context API. 

It is documented here: https://reactjs.org/docs/legacy-context.html 

Normally you would use `createContext` now, but before that API was implemented there were another way of using contexts where you got the values using `contextTypes` and a as the second parameter.

**Comment by eps1lon** [comment]
Answered perfectly in https://github.com/facebook/react/issues/20516#issuecomment-752035027 by @TryingToImprove.
