### ISSUE TITLE
Bug: Hook re-render whole page on single change in a sub component 

### ISSUE THREAD

**Issue by mohsenomidi** [facebook/react#20523]
React version:17.0.0

## Steps To Reproduce

1- create the input with hook style coding 
2- create old style without hook 
3- put console logs for rendering
4- check the page re-render in console 

i create sandbox very simple example to compare the hook and old one behavior 

```
import React, { useState } from "react";

const Input = ({ name, value }) => {
  const [val, setVal] = useState(value);
  console.log("Render Input.");

  return (
    <input
      name={name}
      value={val}
      onChange={(e) => {
        const { value } = e.target;
        setVal(value);
      }}
    />
  );
};

const useInput = ({ name, value }) => {
  const [val, setVal] = useState(value);
  console.log("Render useInput.");

  const getInput = () => {
    return (
      <input
        name={name}
        value={val}
        onChange={(e) => {
          const { value } = e.target;
          setVal(value);
        }}
      />
    );
  };

  return { getInput, val };
};

function App() {
  const { getInput, val } = useInput({ name: "n1", value: "" });
  console.log("Render App.");
  return (
    <div>
      <p> useInput </p> {getInput()}
      <hr />
      <p> Input </p> <Input name="n1" value="" />
    </div>
  );
}

export default App;

```

Link to code example: [SandBox Hook & Old Style Simple Example](https://codesandbox.io/s/amazing-yonath-wck9h)

## The current behavior

I create 2 Text Boxes one with hook and the another one with the old style, now in Hook mode when the user input change the textbox value the whole page rendered, but with old style there only the text-box rendered not the whole page, if you have the complex page with many objects like (Data Table, form, buttons, inputs, etc..) the single change on one of these components forced to re-render everything and it decease performance, for example typing in the text-box take time to effect on page and the delay time is more than user typing speed. 

the one workaround solution is using the callbacks and useMem but if the page is complex(lots of objects as described, and all of these objects has many properties the callback and useMem is very very complicated to handle single object property.

## The expected behavior

prevent to re-render the page for each changes in Hook mode

**Comment by a-c-sreedhar-reddy** [comment]
The state in useinput hook is associated to App component. So changing state of app component would rerender from app.

**Comment by mohsenomidi** [comment]
It means the returned view from hook forced the react to re-render the whole page, because it used in the app component, even the state of sub component (useinput hook) captured the change,  and this as the react design behavior.
if i need this type of components the only way is using HOC, like my example.

it can be concluded the hook usage is only for playing with data and it is not suitable for views, is it right ?

**Comment by a-c-sreedhar-reddy** [comment]
The state change resulted in the re-render not the view. The state in hooks will be associated with the components where you create the hooks. It does not depend on where you use the returned view.

In this case instead of returning a view from hooks the best  way would be to move it into a component and not to a hook.
