### ISSUE TITLE
Bug: No transition when reordering nodes with keys

### ISSUE THREAD

**Issue by decodejacques** [facebook/react#20532]
The following component should display a DOM node that transitions from left to right. This is because there is a JSX element with a key prop and a transition property. However, it does not transition from left to right.

```import React from 'react';
import ReactDOM from 'react-dom';
import { useEffect, useState } from 'react';

function App() {
  const [state, setState] = useState(false)
  useEffect(() => {
    setInterval(() => {
      setState(st => !st)
    }, 1000)
  }, [])

  let e1 = <span
    key="foo"
    style={{
      left: state ? `100px` : `200px`,
      position: "absolute",
      transition: "left 1s"
    }}>WHAT</span>

  let e2 = <span key="bar">HEY</span>

  return state ? [e1, e2] : [e2, e1]
}


ReactDOM.render(<App />, document.getElementById('root'));
```

React version:

17.0.1

## Steps To Reproduce

1. Create a new project with create-react-app
2. Replace the index.js file with the code I provided
3. Use npm start to run

Link to code example:

https://codesandbox.io/s/ecstatic-sky-h6qm5

## The current behavior

The user does not see the span transition from left to right. 

## The expected behavior

A smooth transition from left to right

**Comment by vkurchatkin** [comment]
Why do you expect it work? This is normal and has nothing to do with React, transitions don’t work if you change properties right after appending the node

**Comment by decodejacques** [comment]
I don't know what you mean by "change properties right after appending the node" since the first property change happens after 1 second.

Here is why I expected it to work:
1. At the first render, two span DOM nodes are created
2. These span nodes are kept around thanks to the key props. No new spans are ever created.
3. One of the span nodes has a transition prop on the left property and its left property changes every second

**Comment by vkurchatkin** [comment]
Span nodes are not created, but they are removed from DOM and reappended in different order which breaks transitions

**Comment by decodejacques** [comment]
Ahhh, I wasn't aware that changing the order of DOM nodes breaks transitions. Thanks for the clarifications.
