### ISSUE TITLE
Bug: useEffect with no dependencies always fires a warning

### ISSUE THREAD

**Issue by miquelvir** [facebook/react#20530]
Using useEffect with an empty dependency array will fire up the warning 'react-hooks/exhaustive-deps'. However, using useEffect with an empty dependency list should be a safe praxis when using it as the equivalent of onComponentDidMount.

React version: ^17.0.1

## Steps To Reproduce

1. Use useEffect with no dependencies.

## The current behavior

'react-hooks/exhaustive-deps' is fired

## The expected behavior

Either no warning is fired for an intentional empty array, or an alternative hook useOnDidMount is added, which is useEffect but without dependencies.

```
export const useOnMount = handler => {  // does not trigger react-hooks/exhaustive-deps
     return useEffect(() => {
         return handler();
     }, []);
};
```

**Comment by koba04** [comment]
The effect is using `handler` so it should be included in the deps array. The effect hook is not the same mental model as the lifecycle methods class components have. I highly recommend reading the blog post to understand the concept of the effect model.
https://overreacted.io/a-complete-guide-to-useeffect/

If you have confidence for the usage and want to keep the deps array empty, you can disable the warning by `eslint-disable-next-line react-hooks/exhaustive-deps`
https://masteringjs.io/tutorials/eslint/disable-line

**Comment by rickhanlonii** [comment]
Good explanation @koba04, thanks!
