### ISSUE TITLE
React Hook "useState" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function. 

### ISSUE THREAD

**Issue by Shubham-raut** [facebook/react#20531]
**Asking for change or explanation.**

When I try to use hooks in HOC it throws the error for line no 5 `useState(0)`.

```
import React, { useState } from "react";

export const WithCounter = (WrappedComponent) => {
  return (props) => {
    const [count, setCount] = useState(0);
    const increment = () => setCount((count) => count + 1);
    return <WrappedComponent count={count} increment={increment} {...props} />;
  };
};

const ClickCounter = (props) => {
  return <button onClick={props.increment}>clicked {props.count} times</button>;
};

export default function App() {
  const Comp = WithCounter(ClickCounter);
  return (
    <div className="App">
      <Comp />
    </div>
  );
}
```

**And the error is:**

`React Hook "useState" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function. (react-hooks/rules-of-hooks)`

**Link for Codesandbox**
[https://codesandbox.io/s/hoc-8jw0q](https://codesandbox.io/s/hoc-8jw0q)

**Comment by a-c-sreedhar-reddy** [comment]
Can you create the hook in the WithCounter component rather than in the callback ?

**Comment by eps1lon** [comment]
Thanks for the detailed report.

In order to detect components the eslint rule has some heuristic that you need to follow. In this case you need to give the returned function a name. This has some other benefits like having a name in react-devtools.

```diff
-  return (props) => {
+  return function WithCounter(props) {
```

For more details check out ["What exactly do the lint rules enforce?"](https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce):
> Calls to Hooks are either inside a PascalCase function (assumed to be a component) or another useSomething function (assumed to be a custom Hook).
