### ISSUE TITLE
Error: "Commit tree does not contain fiber 2672. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by Flandre-X** [facebook/react#20549]
Describe what you were doing when the bug occurred:
1. Started the profiler
2. Navigated to a different page
3. "Maximum update depth exceeded" (bug in my code)
4. Stopped the profiler

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-f160547f47

Component stack: CommitFlamegraphAutoSizer@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:34144:50
div
div
div
SettingsModalContextController@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:28205:40
Profiler_Profiler@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:35772:50
ErrorBoundary_ErrorBoundary@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:29219:5
PortaledContent@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:29336:27
div
div
ProfilerContextController@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:32933:35
TreeContextController@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:24321:31
SettingsContextController@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:24810:35
ModalDialogContextController@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:29403:38
DevTools_DevTools@moz-extension://fec50d2c-deab-43b0-a284-f3b1ab9cc94f/build/main.js:36206:27

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#20431) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
