### ISSUE TITLE
onClick on mobile not fired

### ISSUE THREAD

**Issue by taddei** [facebook/react#2055]
I have put together a test case that replicates the issue:

https://github.com/taddei/react-bug-test

On desktop browsers the click handler is triggered correctly, the same code on iOS mobile devices (tested both on simulator and actual devices) does not fire the event. Works fine on android.

**Comment by pke** [comment]
Adding the `cursor: pointer` style does not seem to fix this on iOS9 Have to use "react-tappable" to get the clicks recognized instantly

**Comment by spicyj** [comment]
This should have been fixed in 0.14 already.

**Comment by pke** [comment]
It isn't. I'm on 0.14.7

**Comment by jjhargreaves** [comment]
Any updates on this?

**Comment by jimfb** [comment]
@jjhargreaves No updates; we will update the thread when there is an update.

**Comment by spicyj** [comment]
This is closed which indicates no one is looking at it.

But http://react.jsbin.com/mimovoluci uses React 15 and works on my iPhone. Can someone post an example that is broken?

**Comment by pke** [comment]
@spicyj by "works on my iPhone" you mean the click is instantly recognized? There is no touch delay?

**Comment by spicyj** [comment]
Oh, I totally misunderstood you. It is expected that you get the same click delay as any other onclick handler. The bug that this was tracking is that clicks didn't work _at all_ on iOS. You have to use something like react-tappable that listens to touch events or a script like fastclick.

**Comment by pke** [comment]
@spicyj yeah, I am using `react-tappable` for that reason. Though react brings something with it by now, to get rid of `react-tappable`

**Comment by brunogarcia** [comment]
@spicyj I've tried the example from jsbin, but doesn't work in Safari 9.0. 
By the way on Chrome 51.0.2 works perfectly.
Both tested into an iPad 9.1.

**Comment by elonmuscedo** [comment]
I am using React 15, and this works everywhere but iphone 4, ios 8. I tried buttons, a tag but cant that click to run a function.

**Comment by AustinSpinazze** [comment]
This appears to be broken again in v16 React. I have tried the cursor pointer fix and it still does not fire correctly. I have to resort to using both onClick and onTouchStart.

**Comment by gaearon** [comment]
Please file a new issue if you see a new problem. Issues from 2014 aren't actively monitored and the reasons are likely different.

**Comment by timothyallan** [comment]
@AustinSpinazze If you start a new issue, can you link this one? I've also started getting client complaints saying that they can't click things on iPhone 6's running iOS 12.2... Just tested it, and sure enough, onClick doesn't fire at all the iOS simulator 12.2 with React 17.0.2

**Comment by pke** [comment]
but why Dan? This issue shows the history of the problem. Creating a new one just fragments issue for no reason (except that this one here is old).

**Comment by thusinh1969** [comment]
It is annoying really ! It is simply stop accepting click for whatever reason ! Is that because Apple want everyone on app ?

Steve
