### ISSUE TITLE
Bug: React app stuck on development server and keep loading the page

### ISSUE THREAD

**Issue by asaduzzaman69** [facebook/react#20558]
React version:17.0.1

## The current behavior
I am using create react-app
when i start the development server by yarn start. it start the server and it keeps reloding and doesn't render anything

## The expected behavior

expected to run the server properly and my components run just normal

**Comment by rickhanlonii** [comment]
This repo is for issues with React itself. Please create this issue in the Great React App repo with a repo we can use to reproduce.
