### ISSUE TITLE
React unable to detect messenger.com

### ISSUE THREAD

**Issue by vn273** [facebook/react#20562]
OS: Windows 10
Browser version: Version 87.0.4280.88
Extension version: Adds React debugging tools to the Chrome Developer Tools. Created from revision f160547f47 on 12/4/2020. (downloaded 1/8/2021)
When going to the website messenger.com, the extension returns "This page doesn’t appear to be using React." However, at the beginning of December, this website worked with React Developer Tools. Now it doesn't for some reason. I am unsure as to why the tool is not compatible with the site.

**Comment by rickhanlonii** [comment]
Do you mean the messenger.com homepage? That works for me.

<img width="987" alt="Screen Shot 2021-01-08 at 1 31 13 PM" src="https://user-images.githubusercontent.com/2440089/104051229-d20e1200-51b5-11eb-8ae8-f6d4ec817a43.png">

**Comment by vn273** [comment]
It just started working again for me, yet now it shows up with "Anonymous"
under the compiler section, which is different then what I used to see.

Thank you for your help and quick response!

**Comment by rickhanlonii** [comment]
No sweat!
