### ISSUE TITLE
Bug: react-test-renderer `update` method does not rerender component with new props

### ISSUE THREAD

**Issue by joshuaellis** [facebook/react#20561]
React version: 17.0.1

## Steps To Reproduce

1. clone this [repo](https://github.com/joshuaellis/react-test-renderer-update-issue)
2. install node_modules
3. run yarn test

Link to code example: https://github.com/joshuaellis/react-test-renderer-update-issue

## The current behavior
`@testing-library/react-hooks` rerender function uses `react-test-renderer` `update` under the hood. The props are correctly passed to `update` function but the hook does not re-render with the new props so the test fails.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/37798644/104036363-39828c80-51cb-11eb-9d73-48f0680f4e05.png">

## The expected behavior

the last two logs (in the image above) should say: 
"using func func2"
"im func 2"

**Comment by rickhanlonii** [comment]
Hey @joshuaellis, if you can't reproduce this without `testing-library`, I recommend tracking this in the issue you created there in https://github.com/testing-library/react-hooks-testing-library/issues/530. If this ends up being a bug in React let us know.
