### ISSUE TITLE
Bug: action seems ignored when dispatching an action inside of reducer

### ISSUE THREAD

**Issue by qkreltms** [facebook/react#20570]
React version: 17.0.1
## Steps To Reproduce

I have a reducer which dispatches an action "SUB" and it sets `cnt-=1` when "INCREASE" is dispatched
and I also have action "INCREASE" it sets `cnt+=1`,  

1. When button is clicked it will dispatch INCREASE action
```js
{type: "INCREASE", payload: 1}
{type: "SUB", payload: 1}
```

Link to code example:
https://codesandbox.io/s/simple-react-context-example-forked-p7po7?file=/src/index.js

## The current behavior
cnt sets to -1

## The expected behavior
cnt sets to 0 due to "INCREASE" and "SUB" both are dispatched.

NOTE: If I wrap "SUB" action with `setTimeout()` it works what I expected.
In the example change  lien no. 10
`listener();` to  `setTimeout(() =>listener(), 10);`

**Comment by eps1lon** [comment]
Thanks for the detailed report with reproduction!

If I understood it correctly then you're dispatching in the reducer. I would consider calling `dispatch` in a [reducer a side-effect which is not allowed in React](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects). I think you need to wrap the `dispatch` and call the middleware when you want to dispatch not when you're "reducing".

**Comment by qkreltms** [comment]
Close this issues because it's intended feature.
