### ISSUE TITLE
Plans to move away from default imports

### ISSUE THREAD

**Issue by sergei-startsev** [facebook/react#20576]
There's a note in [New JSX Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) post that the team has plans to move away from the default imports in the long term. 

>The default imports will keep working in React 17, but in the longer term we encourage moving away from them.

Could you confirm these plans and clarify the timeline? Will it be included into React 18?

_The question is submitted here since it's a question only maintainers can answer._

**Comment by rickhanlonii** [comment]
Can confirm this will happen in the long term (React 19+), but there's no formal timeline.

We'll give a fair amount of lead time before making the change.
