### ISSUE TITLE
Bug: disableLogs mutates console

### ISSUE THREAD

**Issue by jcdang** [facebook/react#20575]
It's noted on the docs pages at https://reactjs.org/docs/strict-mode.html

react-dom currently disables/mutates the global console in strict mode.  

This seems to be an intentional feature/bug that's an unnecessary inconvenience. 

React version: 17.0.1

## Steps To Reproduce

1. Use react-dom in strict mode
2. Try to log something 

## The current behavior
logging is disabled in strict-mode

## The expected behavior
Possible better solutions:
- Make it more obvious that the console is being mutated/disabled
- Use a proxy

**Comment by rickhanlonii** [comment]
Hey @jcdang, thanks for submitting.

We only disable the console in the second call, you should still see logs from the first call.

> Starting with React 17, React automatically modifies the console methods like console.log() to silence the logs in the **second call** to lifecycle functions. 

If we didn't do this, the console would contain duplicate messages so we made the tradeoff to disable it in the second pass. This can have side effects, which we offer a [workaround for](https://github.com/facebook/react/issues/20090#issuecomment-715927125).

**Comment by jcdang** [comment]
Hey @rickhanlonii thanks for the explanation.  You actually highlighted the underlying issue I am having!  I'm trying to write a child reconciler right now and eventually discovered the existence of the two passes.

Would you be able to direct me to the design/intent for this two-pass approach or maybe how to disable it for child-reconcilers in the tree?

**Comment by rickhanlonii** [comment]
Sure! [Here's](https://github.com/facebook/react/pull/18430) the PR adding the double render in strict mode, [here's](https://github.com/facebook/react/issues/18426) the issue that inspired it, and [here's](https://github.com/facebook/react/pull/18547) the PR for ignoring the second log.

**Comment by gaearon** [comment]
To follow up on this, we've changed the logging behavior in 18 to be more intuitive.
https://github.com/facebook/react/issues/21783#issuecomment-1083412766
