### ISSUE TITLE
Bug: The code is nested using two hooks -- useState and useEffect -- and there is a bug.

### ISSUE THREAD

**Issue by SouWinds** [facebook/react#20572]
React version:

## Steps To Reproduce

```js
export const editor = ({
  children,
}) => {
  const [scale, setScale] = useState(1)
  useEffect(() => {
    window.addEventListener('mousewheel', event => {
      if (event.ctrlKey === true || event.metaKey) {
        const {wheelDelta} = event
        setScale(scale + wheelDelta / 1000)
        event.preventDefault()
      }
    }, {passive: false})
  }, [])
  return <div className={c('w100p h100v fbh fbjc fbac pr z0', s.editor)} style={{
    transform: `scale(${scale})`,
  }}>
    {children}
  </div>
}

```

![image](https://user-images.githubusercontent.com/30693884/104205014-dada3e80-5468-11eb-91d8-a0ad6d594aeb.png)

Link to code example:

**Comment by bvaughn** [comment]
The repro case you've provided isn't sufficient to trigger the error you've reported.

Here's a Code Sandbox:
https://codesandbox.io/s/tender-pasteur-bsil3?file=/src/App.js

Can you modify it so the bug can be reproduced?

By the way, you are not removing the "mousewheel" event listener in an effect cleanup function, which will be expected to cause a problem after the component unmounts.
