### ISSUE TITLE
Bug: useImperativeHandle return undefined of ref.current property

### ISSUE THREAD

**Issue by iahu** [facebook/react#20585]
React version: last

## Steps To Reproduce

1. Mouse enter to the text
2. check console log

Link to code example: https://codesandbox.io/s/exciting-platform-f7prw?fontsize=14&hidenavigation=1&theme=dark

## The current behavior
get an `undefined` in sometimes

## The expected behavior
aways get `roo`

**Comment by eps1lon** [comment]
Thanks for the reproducible example!

You're logging twice:
1. `console.log("roo");` logs `"roo"`
2. `console.log(ref.current.say());` which logs the return value of `say()` which is `undefined` so you log `undefined`

In the title you're saying `ref.current` is `undefined` sometimes but in your repro `ref.current.say()` would crash if that would be the case.

> The expected behavior
> aways get roo

```diff
    say() {
      console.log("roo");
+     return "roo"
    }
```

I don't see how this is related to React.

**Comment by iahu** [comment]
Thanks your debugging. As read  your express and rewrite my example code, I thank it may be other issue.

My opinion of this report is some times I call  `ref.current.foo()` as say, `ref.current.say()` , and got `null` or `undefined`.

I can understand the logic of this issue, the `ref.current` has been re-assigned to the default state. maybe anther component’s re-render cause it.

I’ll debug on my code first. So, let me close this issue, and say thanks again.
