### ISSUE TITLE
Bug: CRA 4, React 17.0.1 new jsx not umd, React CDN can not work

### ISSUE THREAD

**Issue by ickeep** [facebook/react#20586]
### Describe the bug

externals React, CDN loading React error.

### Environment

System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.2
  npmPackages:
    react: Not Found
    react-dom: Not Found
    react-scripts: Not Found
  npmGlobalPackages:
    create-react-app: Not Found

### Steps to reproduce
1.  Create project
```  
npx create-react-app my-app --template typescript
``` 
2. [Use craco](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#installation)
``` diff
/* package.json */
"scripts": {
-   "start": "react-scripts start",
+   "start": "craco start",
-   "build": "react-scripts build",
+   "build": "craco build"
-   "test": "react-scripts test",
+   "test": "craco test"
}
```
3. Create craco.config.js
``` javascript
module.exports = {
  webpack: {
    configure: (webpackConfig, { env, paths }) => {
      webpackConfig.externals = {
        react: {
          root: "React",
          commonjs2: "react",
          commonjs: "react",
          amd: "react"
        },
        'react-dom': {
          root: "ReactDOM",
          commonjs2: "react-dom",
          commonjs: "react-dom",
          amd: "react-dom"
        }
      }
      return webpackConfig;
    }
  }
}
```
4. edit public/index.html
``` diff
<div id="root"></div>
+ <script src="https://cdnjs.cloudflare.com/ajax/libs/react/17.0.1/umd/react.<%=  process.env.NODE_ENV==='development'?'development':'production' %>.min.js"></script>
+ <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/17.0.1/umd/react-dom.<%= process.env.NODE_ENV==='development'?'development':'production' %>.min.js"></script>
</body>
</html>
  ```
5.  npm run start
6. React is mounted
![image](https://user-images.githubusercontent.com/9164133/104183735-604ff580-544d-11eb-9512-510b4bd137cb.png)

### Expected behavior

Render the page normally

### Actual behavior

![image](https://user-images.githubusercontent.com/9164133/104183141-7610eb00-544c-11eb-86e5-f2589ce8d585.png)

**Comment by eps1lon** [comment]
Thanks for the report. 

This looks familiar to https://github.com/facebook/react/issues/20359

> <script src="https://cdnjs.cloudflare.com/ajax/libs/react/17.0.1/umd/react.<%=  process.env.NODE_ENV==='development'?'development':'production' %>.min.js"></script>

There is no `development.min.js`. You're probably never hitting this branch in the ternary and always use the production bundle. Mixing the React production bundle with the JSX dev bundle is already identified as the cause of https://github.com/facebook/react/issues/20359

Maybe your `NODE_ENV` isn't set at all? Usually the dev/prod flags are checked by `process.env.NODE_ENV !== 'production'`.

Could you share a cloneable repro that I can tinker with?
