### ISSUE TITLE
React should allow defaultValue and input value to be set in the controlled state.

### ISSUE THREAD

**Issue by ievgennaida** [facebook/react#20599]
React version:
"react": "17.0.1",
  "@rjsf/material-ui": "2.4.0",

React should allow defaultValue and input value to be set in the controlled state.

In my application numeric value can be empty (this means automatically determined) or exact value. 
But when user clicks on the numeric up/down buttons they should start from some default value!

Now it's not possible to have both defaultValue and value set!

React throws exception:
"contains an input of type number with both value and defaultValue props. "

But I would expect to allow this and just place the default value when control is about to be edited. 
In my case this is numeric control.

## Steps To Reproduce

1. Use both defaultValue and value and controlled state.

const [value, setValue] = useState('') 

   <TextField
          value={value}
          type="number"
          onChange={(e) => {
            const target = e.target as HTMLInputElement;
            setValue(target.valueAsNumber);
          }}
          InputProps={ {
            inputProps: {
              max: 20,
              min: 0,
              defaultValue: 5,
              step: 0.5,
            },
          }}
        />

2.

## The current behavior
Exception: 

index.js:1 Warning: ForwardRef(InputBase) contains an input of type number with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://reactjs.org/link/controlled-components

## The expected behavior

No warning, click on numeric up-down buttons should start from the default value.

**Comment by rickhanlonii** [comment]
Hey @ievgennaida, thanks for the suggestion.

You can set the initial value of the state to the default value you want in a controlled component. If `defaultValue` was allowed, then it would violate the "single source of truth" aspect of controlled components because there would then be two sources of truth for the value.
