### ISSUE TITLE
Props and Immutable objects?

### ISSUE THREAD

**Issue by ronag** [facebook/react#2059]
I've started using immutablejs together with reactjs.

However, I've noticed that passing around immutable objects doesn't quite fit together with reactjs, i.e. {...myObject}, {myObjects.map(object => React.DOM.div()} and propTypes don't quite support them without first converting to JS object which has an unnecessary overhead.

Any thoughts or advice on this issue?

**Comment by gaearon** [comment]
Closing as this doesn't seem actionable for us.
