### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by LazarPetrovic1** [facebook/react#20603]
# useEffect does not do what it was created to do and furthermore causes problems

React version: 17.01

## Steps To Reproduce

1. import useEffect and axios to fetch data from the backend
2. use it in a functional component

Link to code example:

## The current behavior
Throws the following error: 

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

## The expected behavior
axios should fetch the data from backend in useEffect

**Comment by igeligel** [comment]
Hey @LazarPetrovic1,

That should work. Could you show us an example of what you are doing?

If your code is looking similar to this example:

```js
import React, { useState, useEffect } from 'react';
import axios from 'axios';
 
export const App = () => {
  const [data, setData] = useState({ hits: [] });
 
  useEffect(() => {
    const fetchData = async () => {
      const result = await axios(
        'https://hn.algolia.com/api/v1/search?query=redux',
      );
 
      setData(result.data);
    };
 
    fetchData();
  }, []);
 
  return (
    <ul>
      {data.hits.map(item => (
        <li key={item.objectID}>
          <a href={item.url}>{item.title}</a>
        </li>
      ))}
    </ul>
  );
}
```

This example is from this blog: [How to fetch data with React Hooks?](https://www.robinwieruch.de/react-hooks-fetch-data). It will probably solve the issue you are describing here.

**Comment by rickhanlonii** [comment]
As the error message states, there are three common user-errors that can cause this to happen. Closing as there is no code sample and the stated behavior works as expected. 

@LazarPetrovic1 if you still believe this is a bug in React and not in your code, please provide a codesandbox that reproduces it and I'll take a look.
