### ISSUE TITLE
Bug: React Hooks Do not work in iframe

### ISSUE THREAD

**Issue by LiberationNetwork** [facebook/react#20608]
I've build a web app on react and used react hooks for my forms.

However it is not working when the web application is embedded within another application.

The function executed in an onclick event seems to be unable to fetch the values of the state. may i know why ? (Although from the view, the forms are being filled up. Displaying the state changes does work).

It works individually if not rendered in an iframe.

I've tried using ref to the component the refs.current is apparently empty
and useRef to the variable state e.g. publicKey for const [publicKey, setPublicKey] = useState('');

It only displays the default empty string

React version: 16.13.1

## Steps To Reproduce

1. Create a input form and set form input value change to state using 'useState' e.g. const [publicKey, setPublicKey] = useState('');
2. Create a button with an onClick event listener to fetch the state e.g. publicKey

## The current behavior

It works fine if you render the page directly on the browser. but if the web application is rendered within an iframe, 
'publicKey' from within the function does not change it's value.

## The expected behavior

The expected behavior is that the function executed should still be able to change its value

**Comment by rickhanlonii** [comment]
This doesn't sound like a bug. Since iframes are sandboxed from the parent page you shouldn't be able to access the parent page from an iframe. Going to close, but if you create a codesandbox reproducing the issue I'll take a closer look.
