### ISSUE TITLE
Bug: can't install react.js in npx

### ISSUE THREAD

**Issue by NANI1734** [facebook/react#20611]
I have a bug when I try to say **npx create-react-app mern-app its give me an error

Creating a new React app in C:\Users\*****\Desktop\MERN Stack\mern-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/react: error:0909006C:PEM routines:get_name:no start line".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\nadia\\Desktop\\MERN Stack\\tinder-app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Aborting installation.
  yarnpkg add --exact react react-dom react-scripts cra-template --cwd C:\Users\nadia\Desktop\MERN Stack\tinder-app has failed.     

Deleting generated file... package.json
Done.

pls **help**

**

React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by eps1lon** [comment]
Sounds like a local issue considering:
> error An unexpected error occurred: "registry.npmjs.org/react: error:0909006C:PEM routines:get_name:no start line".
info If you think this is a bug, please open a bug report with the information provided in "C:\Users\nadia\Desktop\MERN Stack\tinder-app\yarn-error.log".

This indicates that you should open a bug report in https://github.com/yarnpkg/yarn/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
