### ISSUE TITLE
react-developer-tools is not supporting iframes

### ISSUE THREAD

**Issue by paztis** [facebook/react#20610]
In a React application that contains iframes also in react,, only the root frame is visible in react-devtools
There's no options to ask to inspect a subframe 
Extension seems not to be injected on the child frame

React version: 16.14

## Steps To Reproduce

1. create an application with an iframe
2. use react inside this iframe
3. try to inspect this iframe content

## The current behavior
Only top level frame components are visible

## The expected behavior
A way to inspect subframes (frame selectbox like in the chrome console ?)

**Comment by eps1lon** [comment]
Sounds like this was also requested in https://github.com/facebook/react/issues/18945. Is there anything different between these two issues?

**Comment by paztis** [comment]
Seems exactly this. I haven't found it by search's I github (was not sure about what to type)

Thanks I close it
