### ISSUE TITLE
onTouchTap triggering handler twice

### ISSUE THREAD

**Issue by piranha** [facebook/react#2061]
We're using `TapEventPlugin` in our application and it calls every handler twice. Those calls are triggered by different events - first time by `touchend`, and second time by `mouseup`, which is generated by a browser as a click. This doesn't make any sense, so I think `TapEventPlugin` should prevent triggering by a `mouseup` when event was triggered by touches.

Not sure if there is a good way. I guess calling `e.preventDefault()` inside of `TapEventPlugin` is not the wisest solution, is it?

**Comment by gaearon** [comment]
`TapEventPlugin` is not officially supported so I'm closing this.
