### ISSUE TITLE
[react-devtools-inline] Same-origin domain element inspection problem

### ISSUE THREAD

**Issue by dmtrKovalenko** [facebook/react#20628]
React version: 17

I am working on integrating react-devtools in Cypress for component testing. In cypress all iframes we have are same-origin, so I choose the proposed [same-origin iframe configuration](https://github.com/facebook/react/tree/master/packages/react-devtools-inline#configuring-a-same-origin-iframe). 

## Steps To Reproduce

Due to its pretty hard to get the exact time point when the iframe is ready but react code not executed it is easier to just run cypress with devtools for reproduction 

1.`git clone git://github.com/cypress-io/cypress.git`
2. `git checkout 725e335e246a61b5bd5e2d19e0c70776d5ee2324`
3. `yarn`
4. `cd npm/react` 
5. `yarn cy:open`

## The current behavior

When iframe is **same origin** and devtools initialization happens in the top window element highlighting is completely broken when initialized not inside the iframe. 
![image](https://user-images.githubusercontent.com/16926049/105191541-e0f2ae00-5b3f-11eb-8dba-1a719cca58d2.png)

It happens because the [overlay tooltip](https://github.com/facebook/react/blob/3e94bce765d355d74f6a60feb4addb6d196e3482/packages/react-devtools-shared/src/backend/views/Highlighter/Overlay.js#L87) calculate node position and render the tooltip itself in the outer window (not inside the iframe). 

![Screenshot 2021-01-20 at 16 55 19](https://user-images.githubusercontent.com/16926049/105192025-62e2d700-5b40-11eb-96f1-c3a9a5dc2ec4.png)

UPD: 
As you can see here OverlayTip class gets incorrect document (root) in the constructor
![image](https://user-images.githubusercontent.com/16926049/105196109-f669d700-5b43-11eb-871e-c4d174f4eff1.png)

## Workaround

And so I noticed a workaround to manually pass `window.__REACT_DEVTOOLS_TARGET_WINDOW__ = contentWindow`, which is not documented solution and must be at least mentioned in the readme

## The expected behavior

For reference, here is the correct solution where used sandbox version and tooltips rendered inside the iframe (codesandbox): 

![Screenshot 2021-01-20 at 16 58 11](https://user-images.githubusercontent.com/16926049/105192498-d5ec4d80-5b40-11eb-9894-b04a6b104073.png)

**Comment by andrelmchaves** [comment]
@dmtrKovalenko Could you confirm this is still an issue?
