### ISSUE TITLE
Bug: React not giving error on calling the component on its render.

### ISSUE THREAD

**Issue by ReactReduxRouterDOM** [facebook/react#20629]
React version: 16.9.53

## Steps To Reproduce

1. Create a simple react app with create-react-app with typescript

Only changed App.tsx:
```js
const App = () => {
  return (
    <>
      <h1>Hello World</h1>
      <App />
    </>
  );
};


export default App
```

## The current behavior
The page just keeps loading

## The expected behavior
Some kind of error for calling a component inside itself infinitely.

**Comment by eps1lon** [comment]
Thanks for the report.

Closing this in favor of re-opening https://github.com/facebook/react/issues/12525 which discussed the same problem.
