### ISSUE TITLE
enterleave event triggers extra calls with nested roots

### ISSUE THREAD

**Issue by chenglou** [facebook/react#2063]
http://jsfiddle.net/haa2euy9/1/

Enter inside the square, then enter in `Hello`. Expected nothing to happen. Recorded a `leave` instead. Same for exiting `Hello`.

**Comment by gaearon** [comment]
I don’t see an action item here. With portals (new in React 16) propagation works correctly across the subtrees so this use case could be fixed. I don’t think we can support entirely correct behavior *between* different roots. So I’ll close this but let me know if that’s wrong.
