### ISSUE TITLE
Bug: the input event was trigger in wrong time

### ISSUE THREAD

**Issue by HomyeeKing** [facebook/react#20647]
[here is the reproduce link](https://codesandbox.io/s/input-maxlength-msh6i?file=/app.jsx)

when you input something, it triggers both `input` and `change` event

but according to official doc, `change` event only be triggered when input blur

**Comment by rickhanlonii** [comment]
@HomyeeKing [from our docs](https://reactjs.org/docs/dom-elements.html#onchange):

> The onChange event behaves as you would expect it to: whenever a form field is changed, this event is fired. We intentionally do not use the existing browser behavior because onChange is a misnomer for its behavior and React relies on this event to handle user input in real time.

Going to close this as it seems to be working as documented, but thanks for submitting.
