### ISSUE TITLE
reasons for using var ？

### ISSUE THREAD

**Issue by cyphernull** [facebook/react#20648]
https://github.com/facebook/react/blob/f15f8f64bbc3e02911d1a112fa9bb8f7066a56ee/packages/scheduler/src/forks/SchedulerDOM.js#L253

Is there a certain reason for using `var` instead of `let` in these `unstale_xxx` functions and other variables' definition ? 🙂

**Comment by IslamYehia1** [comment]
Is there a reason to use let instead of var in a global scope?

**Comment by rickhanlonii** [comment]
The scheduler is designed to be used with no build steps, which means using ES5 syntax.

See https://github.com/facebook/react/pull/13582 for more context.
