### ISSUE TITLE
Dev tools Chrome Extension only works properly in Incognito window

### ISSUE THREAD

**Issue by robicano22** [facebook/react#20641]
Hi folks,
At some point w/in the last 5 months or so, the dev tools Chrome extension stopped working properly for me in **non**-incognito Chrome windows.  It's a bit hard to explain, but i'll try: when i use the extension, react components show up, but they are basically just high level wrapper components that we use in our app.  For example, I cannot inspect a button component, a container component, an input component, etc, in the UI.

This issue disappears in incognito mode, however, and i can use the extension just fine.

Chrome version: 87.0.4280.141
Extension version: 4.10.1
React version: 16.13.1

I've been unable to find anyone else with this issue.  Please let me know if there is other information I can provide you with.  Thank you.

**Comment by bvaughn** [comment]
Hey @robicano22 :wave: Did you enable some [component filters](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#component-filters) and then forget to turn them off? 😄  That's my guess.

**Comment by robicano22** [comment]
> Hey @robicano22 👋 Did you enable some [component filters](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#component-filters) and then forget to turn them off? 😄 That's my guess.

Hi Brian, thanks for the check on this.  I currently have no component filters enabled.

**Comment by bvaughn** [comment]
Seems pretty likely to have something to do with your DevTools extension settings, since incognito (same DevTools version) works fine. Tried uninstalling and re-installing?

**Comment by robicano22** [comment]
> Seems pretty likely to have something to do with your DevTools extension settings, since incognito (same DevTools version) works fine. Tried uninstalling and re-installing?

That worked 🤦 Thank You!

**Comment by bvaughn** [comment]
No problem. That's pretty curious though. First time I've heard a report of this kind of bug.

Glad you got it sorted though!
