### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by JadeLiuYC** [facebook/react#20651]
When an asynchronous request is made in useEffect, a warning may appear when updating the state
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

First, if the asynchronous request does not return to the switch page, a warning will appear at the top. At this time, you can find a way to cancel the asynchronous request in the return function;

The second method: after the asynchronous request returns, the state will be updated after data processing in the callback, and the warning above will also appear. (in the example below, the second setTimeout of 2000 milliseconds is to simulate the state updating after data processing after data return). At this time, the processing method is to set a variable unmounted, Set negate in the return function, and then judge how to update the state.

https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

The above is a general idea given by the official website, which can only be applied to the first case above. Is there any other plan?

```js
import React, { useEffect, useState } from "react";

function Notice() {
  const [data, setData] = useState([]);

  useEffect(() => {
    setTimeout(() => {
      setTimeout(() => {
        let arr = [];
        for (let i = 0; i < 10; i++) {
          arr.push({
            id: i + 1,
            text: `useEffect内异步请求下设置state警告问题${i + 1}`,
          });
        }
        setData(arr);
      }, 2000);
    }, 200);
    return () => {};
  }, []);

  return (
    <ul>
      {data.map((item) => {
        return <li key={item.id}>{item.text}</li>;
      })}
    </ul>
  );
}

export default Notice;
```

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by clintonngotta** [comment]
I have experienced the same problem with a react native app. basically am calling an asynchronous API call when the component mounts using useEffect() then update state on successful callback. This is on my login screen, after the user token is set, I get the error when the user is presented with the home screen.

**Comment by eps1lon** [comment]
@JadeLiuYC Could you include a real-world example? I don't see a reason why you can't use existing patterns to cancel async state updates:

```diff
  useEffect(() => {
+   let cancelled = false;
    setTimeout(() => {
      setTimeout(() => {
        let arr = [];
        for (let i = 0; i < 10; i++) {
          arr.push({
            id: i + 1,
            text: `useEffect内异步请求下设置state警告问题${i + 1}`,
          });
        }
+       if (!cancelled) {
          setData(arr);
+       }
      }, 2000);
    }, 200);
-   return () => {}
+   return () => {
+     cancelled = true;
+   };
  }, []);
```

Though with your particular example I would just use `clearTimeout`:

```diff
  useEffect(() => {
-   setTimeout(() => {
+   let timeoutID = setTimeout(() => {
-     setTimeout(() => {
+     timeoutID = setTimeout(() => {
        let arr = [];
        for (let i = 0; i < 10; i++) {
          arr.push({
            id: i + 1,
            text: `useEffect内异步请求下设置state警告问题${i + 1}`,
          });
        }
        setData(arr);
      }, 2000);
    }, 200);
-    return () => {};
+    return () => {
+      clearTimeout(timeoutID);
+    }
```

**Comment by JadeLiuYC** [comment]
The main problem is to update data after asynchronous request. If the component is unloaded (switching pages, etc.), the above warning will appear. The official advice is to cancel the asynchronous request in the return function of useeffect. This does not solve practical problems.

The root causes of the above problems are as follows

1. If the asynchronous request does not return, you can cancel the asynchronous request in the return function;

2. If the request has returned, data processing is in progress, and the state is about to be updated, the above warning will also appear when the component is unloaded (switching pages, etc.). At this point, you need to set an unmounted variable to control the update of the state.

**Comment by rickhanlonii** [comment]
Hey @JadeLiuYC, thanks for submitting but it doesn't appear that this is a bug. As the error says, "To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function".  @eps1lon example will handle the second case, where the request returns but the component is unmounted.

**Comment by eps1lon** [comment]
> If the request has returned, data processing is in progress, and the state is about to be updated,

If you're in a synchronous piece of code e.g. `then(() => { /* synchronous piece of code  */})`, the component cannot be updated during the execution of the synchronous piece of code and you won't get the described warning. You will only get the warning if it was unmounted between two "blocks" e.g.

```js
await fetch();
// ----- update can happen now. Next code needs to be cancelable.
await processData();
```
or
```js
fetch()
// ----- update can happen now. Next code needs to be cancelable.
  .then(() => {
    return processData()
  })
```

That's one of the reasons why `effectFn` `useEffect(effectFn)` cannot be async so that it can return a cleanup function before the component is unmounted.

So maybe you're doing something like

```js
useEffect(async () => {
  const response = await fetch(url);
  const rawData = await response.json();
  const data = await processData(rawData);
  setData(data);
}, [url])
```
where you can't cancel `processData` or `response.json()` if the component unmounted. But that's why you need to leverage `then()`, `catch()` and the other Promise methods.

A real world example would help in understanding your problem. Right now I can only guess what you're doing.

**Comment by clintonngotta** [comment]
> > If the request has returned, data processing is in progress, and the state is about to be updated,
> 
> If you're in a synchronous piece of code e.g. `then(() => { /* synchronous piece of code */})`, the component cannot be updated during the execution of the synchronous piece of code and you won't get the described warning. You will only get the warning if it was unmounted between two "blocks" e.g.
> 
> ```js
> await fetch();
> // ----- update can happen now. Next code needs to be cancelable.
> await processData();
> ```
> 
> or
> 
> ```js
> fetch()
> // ----- update can happen now. Next code needs to be cancelable.
>   .then(() => {
>     return processData()
>   })
> ```
> 
> That's one of the reasons why `effectFn` `useEffect(effectFn)` cannot be async so that it can return a cleanup function before the component is unmounted.
> 
> So maybe you're doing something like
> 
> ```js
> useEffect(async () => {
>   const response = await fetch(url);
>   const rawData = await response.json();
>   const data = await processData(rawData);
>   setData(data);
> }, [url])
> ```
> 
> where you can't cancel `processData` or `response.json()` if the component unmounted. But that's why you need to leverage `then()`, `catch()` and the other Promise methods.
> 
> A real world example would help in understanding your problem. Right now I can only guess what you're doing.

I have trie this and it still doesnt work for me 

`useEffect(() => {
    let mounted = true;
    if (mounted) {
      let URL = `${config.API_URL}Transactions/getAll/${page}`;
      getTransactions(URL);
    }
    return () => {
      mounted = false;
    };
  }, [isLoading]);

  const getTransactions = async URL => {
    try {
      let response = await fetch(URL);
      let json = await response.json();
      if (json.length > 0) {
        await setTransactions(json);
        await setIsLoading(false);
      } else {
        await setTransactions([]);
        await setIsLoading(false);
      }
    } catch (error) {
      console.log(error);
    }
  };`

**Comment by eps1lon** [comment]
Assuming `set*` are functions returned from `React.useState`: These functions don't return a promise. Awaiting them should be avoided since it makes it harder to reason about the code.

The `getTransactions` functions needs to know if it is cancelled since it has multiple `await` instructions. In between the component could've been unmounted. I've done this by inlining the function into the effect handler. It should have the same functionality.

```js
useEffect(() => {
    let mounted = true;
    let URL = config.API_URL+"Transactions/getAll/"+page;
    fetch(URL)
      .then(response => response.json())
      .then(json => {
        if (mounted === false) {
          return;
        }
        if (json.length > 0) {
          setTransactions(json);
          setIsLoading(false);
        } else {
          setTransactions([]);
          setIsLoading(false);
        }
      })
      .catch(error => console.log(error))
    return () => {
      mounted = false;
    };
  }, [isLoading]);
```

A similar example using `async-await` can be found in https://codesandbox.io/s/jvvkoo8pq3

But there are also problems with the dependencies of your effect. They're incomplete and need the `page`.

**Comment by clintonngotta** [comment]
thanks, it worked for me.

**Comment by JadeLiuYC** [comment]
[https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html](url) 
By understanding this article, setting a variable to control whether the update of state is the same as in the article is an anti pattern?

**Comment by eps1lon** [comment]
> [https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html](url)
> By understanding this article, setting a variable to control whether the update of state is an anti pattern?

I think the part about promises in that article is just a bit unfortunate. They're basically just abstracting the `isMounted` call into `makeCancelable`. 

The takeaway from this article is that you should cancel your async tasks in cleanup functions instead of wrapping every update in e.g. `isMountedRef.current`. For promises that does look like you're just re-implementing `isMounted`. But for e.g. timeouts you should use `clearTimeout` instead of wrapping the deferred update in `isMounted`. Generally, I'd say you should move your mental model from "is mounted?" to "is cancelled?". "is mounted" breaks down if you have effects with dependencies where the cleanup function doesn't necessarily run when the component unmounts.

**Comment by JadeLiuYC** [comment]
ok, thanks.
