### ISSUE TITLE
Bug:  useRef获取的current为undefined

### ISSUE THREAD

**Issue by PLUTO06210331** [facebook/react#20650]
React version:

我在一个span标签使用useref后在useEffect中尝试读取它的属性，结果返回了undefined
const spanRef = useRef();
useEffect(() => {
    console.log(spanRef);
    queryList();
    const styleHei = document.getElementById('rightquata').clientHeight;
    setHeight(`${styleHei}px`);
  }, [queryList]);

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
