### ISSUE TITLE
Bug: React assumes My application's language is English

### ISSUE THREAD

**Issue by justo-rivera** [facebook/react#20653]
What is the best practice to change the lang attribute of index.html?
Besides replacing "en"

It's weird to assume a language for an application, and I found no documentation about the best practice on how to change it.

This is a bug because chrome will tell the users of the application to "TRANSLATE FROM ENGLISH" and this is a UX/UI problem. Besides the fact of assuming that an application that **might not even have text** is written in "english", by default, and not documenting how to change that option.

Thanks

React version: ^17.0.1

## Steps To Reproduce

1. Use create-react-app
2. Write an application, with just one word in it
3. Chrome tells you to translate the webpage from english
[Example of behavior. Note the chrome-translate at the bottom](https://i.ibb.co/r3Kn15V/Screenshot-20210125-100351-Chrome.jpg)

Link to code example:

in public/index.html

```
<!DOCTYPE html>
<html lang="en">
```

## The current behavior
A developer is assumed to know where to find the html lang that they need to change. Without any documentation (couldn't find) about how to set the language of your application.

## The expected behavior
A developer doesn't get a UX/UI headache because chrome tells them to translate from english. 
Create-react-app idea is to make it easy to create a react application (right?), and it's used by junior and pre-junior developers around the world. They might not know what public/index.html actually is or even understand the lang attribute of an html tag.
Besides, why english? This is not an issue for me but could be seen as weird around the world

Better documentation on the standard way to set a language for an application would be a great fix.

**Comment by ludofischer** [comment]
This would be a bug with https://github.com/facebook/create-react-app (different repository)

**Comment by bvaughn** [comment]
Yes, please file this in the create-react-app repo: https://github.com/facebook/create-react-app

That repo is maintained by a different team. I would migrate it myself but GitHub doesn't support that to my knowledge.
