### ISSUE TITLE
v17 regression in Safari scrolling performance

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react#20662]
[I originally tweeted about this problem](https://twitter.com/OliverJAsh/status/1354030814988804096) but I wanted to create an issue so we have a better place to discuss workarounds, and also so it is easier for other users to find.

React version: 17

## Steps To Reproduce

Here is a reduced test case that runs 5 seconds of JS when the button is clicked.

v17: https://stackblitz.com/edit/react-d3cbyc?file=src%2FApp.js

When this 5 seconds of JS is running, Safari blocks scrolling.

Here is an identical test case but it uses v16 instead: https://stackblitz.com/edit/react-haist4?file=src%2FApp.js

When this 5 seconds of JS is running, Safari does not block scrolling.

## The current behavior

Scrolling is blocked in v17

## The expected behavior

Scrolling is not blocked in v17

---

If I understand correctly, starting in v17, React registers a `wheel` event listener on the root—regardless of whether or not you actually use this event. (I believe this change was made in https://github.com/facebook/react/pull/19659.)

This is marked as `passive` but Safari still blocks scrolling.

What this means: if you're doing any JS work whilst a user is scrolling, with v17 your Safari users will see jank whereas with v16 scrolling would have been buttery smooth. This is what happened to us at Unsplash.

I don't believe React is doing anything wrong here. It's just Safari is missing some optimisations which other browsers have (i.e. [scrolling decoupled from rendering](https://twitter.com/voxpelli/status/1354020054376067073) or [maybe Safari supports `passive` events but not for the `wheel` event](https://twitter.com/voxpelli/status/1354034514671054848)). Fortunately, Safari seems to have already fixed this behaviour in Technology Preview. Until then, I'm not sure how we can workaround this?

**Comment by gaearon** [comment]
Huh, so this looks specific to _desktop_ Safari. Interesting.

As you said it looks like this is already fixed in next desktop Safari, but for now you can add this *before* your `ReactDOM.render` call to prevent the `wheel` listeners from getting attached:

```js
// Patch native addEventListener *before* ReactDOM.render call.
const addEventListener = Node.prototype.addEventListener;
Node.prototype.addEventListener = function(type, listener, options) {
  if (type === "wheel") {
    // Disable because of https://github.com/facebook/react/issues/20662
    // Note: this would disable any onWheel listeners.
    // You could also limit this to particular roots, e.g.
    // if (type === 'wheel' && this.id === 'root') { return }
    return;
  }
  return addEventListener.apply(this, arguments);
};
```

https://stackblitz.com/edit/react-ee3bcq?file=src%2Findex.js

**Comment by gaearon** [comment]
Seems like there's nothing else we can do here.

**Comment by CodeFromAnywhere** [comment]
How can I do this in Next.js?

**Comment by gaearon** [comment]
You should ask this in the Next.js repo.
