### ISSUE TITLE
Bug: React refresh is not compatible with lower version (IE9 or ie10)

### ISSUE THREAD

**Issue by Ken-ding** [facebook/react#20673]
The code of react refresh in IE9 and ie10 is very sensitive to ES6 syntax which is not recognized by lower version browsers

**Comment by bvaughn** [comment]
The ReactJS website [says the following](https://reactjs.org/docs/react-dom.html#browser-support) about browser support:
> # Browser Support
> React supports all popular browsers, including Internet Explorer 9 and above, although some polyfills are required for older browsers such as IE 9/10.
> 
> > **Note**
> > 
> > We don’t support older browsers that don’t support ES5 methods, but you may find that your apps do work in older browsers if polyfills such as [es5-shim and es5-sham](https://github.com/es-shims/es5-shim) are included in the page. You’re on your own if you choose to take this path.

It's not clear to me if you've added the required polyfills and Fast Refresh is still not working.

If that is the case, I don't think it's likely for us to target browsers as old as IE 9/10 for developer tooling and iteration. The developer tools for these browsers are very old and not commonly used.
