### ISSUE TITLE
Bug: fetch request in useEffect triggers page reload

### ISSUE THREAD

**Issue by pgalle** [facebook/react#20683]
I've created a simple React application, that get's bundles up by webpack.
On load it should request data once from an api and save it into a global context.

Boiled down the code looks like this:
``` html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <base href="/build/"></head>

<body>
   <div id="root"></div>
<script src="scripts.js"></script></body>

</html>
```

``` js
import React, { useEffect } from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
   <App />,
   document.getElementById('root'),
);

function App() {
   useEffect(() => {
      fetch('http://localhost:9000/api/v1/clusters');
   }, []);

   return (
      <main>
         Test
      </main>
   );
}
```

React version: 17.0.1
react-dom: 17.0.1

## Steps To Reproduce
Just building and starting the application with any server will trigger the page reload after the request has successfully finished.

The fetched url is a local reverse proxy using [caddy](https://caddyserver.com/) that handles CORS locally for a local application on another port. The headers look like this:

```
// Response Headers
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Thu, 28 Jan 2021 14:02:18 GMT
Server: Caddy
Transfer-Encoding: chunked
```
```
// Request Headers
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:9000
Origin: http://localhost:5500
Pragma: no-cache
Referer: http://localhost:5500/
sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not\\A\"Brand";v="99"
sec-ch-ua-mobile: ?1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Mobile Safari/537.36
```
Oddly urls like `https://jsonplaceholder.typicode.com/todos/1` work as expected. There we have much more complex headers.

## The current behavior
Currently, as mentioned, the page reloads indefinitely.

## The expected behavior
Without using react, the fetch triggers no page reload. That's expected.

My guess is, that react might handle fetch request depending on the url provided. I couldn't find any code for this though.

Kind regards

**Comment by bvaughn** [comment]
I don't think React would do anything to reload your page given the example code above. But can you share a full repro (code that we can run) that shows this happening?

Here's a Code Sandbox that's similar if you'd like a starting point:
https://codesandbox.io/s/zen-dew-sbs49?file=/src/App.js

**Comment by pgalle** [comment]
I found the culprit of this behavior. I'm developing in vscode and in there I'm using "Live Server" from Ritwick Dey to host builds locally without much of a hassle.

This Live Server triggers the page reload. That's why I don't see any errors or something.

React has nothing to do with it.

**Comment by bvaughn** [comment]
Thanks for sharing your findings!

**Comment by maasir554** [comment]
Thanks for sharing!!
