### ISSUE TITLE
Bug: React triggers scroll issue in Safari

### ISSUE THREAD

**Issue by jareware** [facebook/react#20690]
Rendering a simple set of inert `<div>` elements with React causes a Safari scroll issue that's not caused by the same set of elements as static HTML. Blue is react app, pink is static HTML:

https://user-images.githubusercontent.com/560055/106271762-ae7c3b80-6238-11eb-8044-760157505808.mov

That is, the React-managed element continues to grow as you try to scroll further right.

Repro code: https://jsfiddle.net/x9k76m04/1/

This is most certainly a bug in Safari, but looks like React is doing something to trigger that bug, so I wonder if there's a workaround. 🤷 

Versions:

```
macOS: 10.15.7
Safari:  14.0.2
react: 17.0.1
react-dom: 17.0.1
```

The only vaguely related open issue I could find was #20662, but probably unrelated, and the workaround posted there didn't change this behaviour.

**Comment by OliverJAsh** [comment]
Is this a regression from v17 or are you able to reproduce still with v16? If it is a regression then it could have the same root cause as https://github.com/facebook/react/issues/20662 (the way React attaches events has changed).

**Comment by gaearon** [comment]
In either case, this is something you should probably report to Safari instead.
