### ISSUE TITLE
Improve ESLint error for improperly named hooks

### ISSUE THREAD

**Issue by callmetwan** [facebook/react#20691]
The ESLint rule `eslint-plugin-react-hooks` enforces a naming convention on hooks; they must all start with `use`. This is in line with the [documentation around writing custom hooks](https://reactjs.org/docs/hooks-custom.html#using-a-custom-hook). This is all good, works as intended.

The error message you get does not tell you this though. Example:

```
const doesNotStartWithUse = () => {
  useEffect(() => {}, []);
};
```

Resulting message:

> ESLint: React Hook "useEffect" is called in function "doesNotStartWithUse" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter.(react-hooks/rules-of-hooks)

It isn't clear from the error that the issue is the name. I intend to put a PR up for this; I created this issue as the contribution guide recommended it in the event the PR isn't accepted so others have something to search against.

**Comment by rickhanlonii** [comment]
Hey @callmetwan, thanks for submitting. How would you improve the error?

**Comment by rickhanlonii** [comment]
Looks like you already opened a https://github.com/facebook/react/pull/20692, let's discuss this there.
