### ISSUE TITLE
Hydrate issues text content doesn't match for identical text content

### ISSUE THREAD

**Issue by apokryfos** [facebook/react#20697]
This relates to the stackoverflow question https://stackoverflow.com/questions/65939528/text-content-did-not-match-warning-for-identical-text 

The issue is that text that is interpolated in a component ends up generating multiple text nodes. For example consider this component:

```
const App = (props) => (
   <h1>
      Application version {props.version}
   </h1>
);
```
On when rendering it serverside (assuming props.version is e.g. 1.0.0) this renders:

```
<h1>Application version 1.0.0</h1>
```
the browser will then render the inner text in a single textnode 

However when react hydrates this element (or without SSR when it renders it) `document.querySelector('h1').childNodes` shows 2 text nodes, one containing "Application version " and once containing "1.0.0" so I guess my suggestion here either:

1.  Render adjacent text in the same textnode  or
2. Consider adjacent text nodes to match a single text node if the concatenated text content matches

I think using something like [normalize](https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize) at some step of this process might help but I'm not sure where this can be added to not have an impact in performance (my guess is on the hydration warning side since that does not add any overhead in production versions?)

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it. I tried it in a codesandbox but that doesn't produce a hydration warning: https://codesandbox.io/s/suspicious-brahmagupta-7lsoq?file=/src/index.js

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by apokryfos** [comment]
Well, this is embarrassing. 

It seems I had switched from using from `renderToString` to using `renderToStaticMarkup`  at some point for unknown reasons. My page was quite simple so didn't actually notice this was happening other than this hydration notice. 

I do apologise for this. I hope you didn't waste too much time looking into this.

**Comment by dhc-zhuchuanpeng** [comment]
I also meet the issue.

`import React from "react";
import ReactDOM from "react-dom";

const App = (props) => <h1>Application version {props.version}</h1>;

const container = document.getElementById("root");
const element = <App version="1.0.0" />;

// mock the server render
container.innerHTML = "<h1>Application version 1.0.0</h1>";
ReactDOM.hydrate(element, container);
`
and the error message is 

`
Warning: Text content did not match. Server: "Application version 1.0.0" Client: "Application version "
`
