### ISSUE TITLE
Bug: React Dev Tools fail to show component updates with memoized components.

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/react#20696]
React version: 17.0.1

## Steps To Reproduce

1. run the project: https://github.com/lifeiscontent/immutable-todo
2. open react dev tools and set the highlight updates when components render option.
3. add changes to the todos
4. see no updates are displayed via React dev tools

Link to code example:

https://github.com/lifeiscontent/immutable-todo

## The current behavior

currently, updates are only displayed if the react component is not memoized.

## The expected behavior

all react components should show their updates regardless of memoization.

**Comment by lifeiscontent** [comment]
@gaearon any idea who I should ping to get some eyes on this?

**Comment by bvaughn** [comment]
No one needs to be pinged. We review GitHub issues as we have bandwidth.

**Comment by lifeiscontent** [comment]
@bvaughn Sure, do you have an idea where I might look to investigate something like this? It would be my first time contributing to that code so it'd be greatly helpful if someone could point me in the general direction of where I might look.

**Comment by mokimo** [comment]
@lifeiscontent a start would be reading this https://reactjs.org/docs/how-to-contribute.html

Then you can read through the `readme's` of the `react-devtools` to get an idea of to start and debug the dev tools locally.

Haven't submitted anything myself, but that's how I'd start.
