### ISSUE TITLE
Bug: Rule of hook should not apply when making an HOC

### ISSUE THREAD

**Issue by NPellet** [facebook/react#20708]
React version: 17.0..1

## Steps To Reproduce

1. Attempt to compile the following typescript

```typescript
import { useState } from "react";

const useMyHook = () => {
    let [value] = useState(null);
    return value;
}

const MyHOC = function (Component: any) {
    return function ({ ...otherProps }) {
        const value: any = useMyHook();
        return <Component value={value} {...otherProps} />
    }
}

export default MyHOC
```

## The current behavior

```
  Line 22:28:  React Hook "useMyHook" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
```

## The expected behavior

Since we're actually returning a new component, I expected that the rules of hook wouldn't apply in this particular case.

I personally think that HOCs would be a great way to abstract away even a single hook. My goal is to allow the users to use components transparently by directly feeding the result returned by the hook as a prop of the component.

**Comment by mrsimb** [comment]
I guess this check is only applied to anonymous functions. Try to name your function, and return it on the other line, not immediately.

**Comment by eps1lon** [comment]
Thanks for the report.

As @mrsimb already noted, the function must be named in order for `react-hooks/rules-of-hooks` to work:

> Calls to Hooks are either inside a PascalCase function (assumed to be a component) or another useSomething function (assumed to be a custom Hook).

-- https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce

@NPellet Does this clear things up for you?

**Comment by NPellet** [comment]
Yep it indeed worked as intended.
I definitely missed that part of the documentation. Thanks a lot for the help and sorry for reporting an expected behaviour.

**Comment by eps1lon** [comment]
> Thanks a lot for the help and sorry for reporting an expected behaviour.

Nothing to apologize for. We get these a lot and it indicates that we should improve the documentation.

**Comment by NPellet** [comment]
Actually. Let me use this thread to push things a little further.
The following situation looks like it should be allowed, but hooks called from within usePrevious() fail to pass the rule of hooks.

```typescript
// HOC
function WithLoginEnvironment(Component: React.FunctionComponent) {

  return function LoginPageEnforced(props: any) {
    return (
      <LoggedInUserProvider>
        <LoggedInUserContext.Consumer>
          {function LoginConsumed(context) {
            // Doesn't pass the rule of hooks
            const previous = usePrevious(context.loginState);
            const forceUpdate = useForceUpdate();

            if (previous === false && context.loginState == true) {
              return <WelcomeScreen next={forceUpdate}></WelcomeScreen>
            }

            return (context?.loginState === undefined ? null : (!context.loginState ? <Login refresh={context.refresh} /> : <Component {...props} />))
          }}
        </LoggedInUserContext.Consumer>
      </LoggedInUserProvider>);
  }
}
```
