### ISSUE TITLE
Bug: App crashes when trying to mount SearchBox component from 'react-google-maps'

### ISSUE THREAD

**Issue by asaivishal** [facebook/react#20706]
React version: 17.0.0

## Steps To Reproduce

1. Open the CodeSandbox: https://codesandbox.io/s/react-google-maps-bug-react-l9z5q
2. Replace `<API_KEY>` with your own Google Maps API Key
2. Map is rendered fine without `SearchBox`

Link to code example: https://codesandbox.io/s/react-google-maps-bug-react-l9z5q

## Working example with React16.
Link to code example: https://codesandbox.io/s/react-google-maps-bug-react-forked-qjhok

## The current behavior
The same example with `SearchBox` works with `react@16.14.0`, `react-dom@16.14.0`.  But it doesn't work with `react@17.0.0`, `react-dom@17.0.0`.

## The expected behavior
The same example should work with latest react17.

**Comment by rickhanlonii** [comment]
Hey @asaivishal, the change from React 16 to 17 is a major change, which means it could include breaking changes.

Please reach out to that library to report the bug, they may have a compatible version already available.
