### ISSUE TITLE
Bug: react-hooks/rules-of-hooks should support compound component pattern

### ISSUE THREAD

**Issue by wildfrontend** [facebook/react#20700]
this is a sample issue :

```
150:20  error    React Hook "useDispatch" is called in function "PageHome.Layout" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter  react-hooks/rules-of-hooks
```

i think maybe hook rule can support compound component pattern

**Comment by rickhanlonii** [comment]
Hey @wildfrontend, do you have any code snippets to show what PageHome.Layout is? If it's a class component, then the error is correct. If not, I'd like to talk a closer look.

**Comment by wildfrontend** [comment]
thanks @rickhanlonii  , this is my code snippets , i use functional component 

```js

const PageHome: React.FC = () => {
  return (
      <div>
         Home Content
     </div>
  );
};

PageHome.Layout  = ({ children }) => {
  return (
    <Layout>
      {children}
    </Layout>
  );
};

export default PageHome;
```

**Comment by jordyvandomselaar** [comment]
@wildfrontend Could you add a small code example including the `useDispatch` hook that is failing? That way it's easier to check if something works or not and it makes it easier to identify what is going on =)

**Comment by cliffordfajardo** [comment]
I was also getting this error from `react-hooks/rules-of-hooks`, when using the Compound Components pattern:

```tsx
const Carousel = ({children }: ISlideListProps) => {
  return {children}
}

// Compound component...attaching variable to `Carousel`...react doesnt thing this is a component.
Carousel.SlidesContainer = ({children}):JSX.Element => {
   const {carouselViewportElRef, carouselAPI} = useCarousel(); ❌  // React Hook "useCarousel" is called in function "Carousel.SlidesContainer" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter
  return {
     {React.Children.map(children, ((child, i) => {
        return <p>{child}</p>
     }))}
    }
}

// Usage of the component in another file
<Carousel>
  <Carousel.SlidesContainer>
    {[1,2,3,4].map((club, i) => {
      return <p>I am a component</p>
    })}
  </Carousel.SlidesContainer>
</Carousel>
 
```

**Comment by jordyvandomselaar** [comment]
@cliffordfajardo have you tried to define the components separately and then combine them later?

```
function MyComponent() {
  //
}

function OtherComponent() {
  //
}

MyComponent.OtherComponent = OtherComponent;

export default MyComponent;
```

IIRC this works as well

**Comment by tobias-tengler** [comment]
Running into this as well. Could we take another look at this?

**Comment by rickhanlonii** [comment]
Confirmed, @jordyvandomselaar's version works, but the OP version doesn't.

Here's a failing test: https://github.com/facebook/react/pull/27881

Feel free to pick this up if you're interested in fixing it!

**Comment by sasankamowli** [comment]
Hi, I am interested in fixing this issue.

**Comment by rickhanlonii** [comment]
If you're interested in fixing, please just submit a PR with the fix. No need to ask!

**Comment by gaearon** [comment]
We don't really recommend declaring components like this for various reasons (e.g. it doesn't work with lazy-loading), but if you feel strongly that you want to use this pattern, https://github.com/facebook/react/issues/20700#issuecomment-813689504 is the intended way to make the lint rule work with it.
