### ISSUE TITLE
Bug: inconsistent behaviour with StrictMode and useEffect

### ISSUE THREAD

**Issue by dentrado** [facebook/react#20714]
When using StrictMode, in some cases `useEffect` will not re-trigger when a value it depends on changes, even though the component using the `useEffect` re-renders with the new value.

The problem can be seen in multiple state management libraries eg. [zustand](https://github.com/pmndrs/zustand/issues/115), [reatom](https://github.com/artalar/reatom/issues/351) and [visly-state](https://github.com/vislyhq/visly-state) (where I bumped in to it).

Some more information can be found in [this issue](https://github.com/pmndrs/zustand/issues/115) on the zustand repo, which is also where the minimal reproducible example below comes from.

React version: 17.0.1

## Steps To Reproduce

1. Use an external state in a component that also has an useEffect hook depending on that state
2. Trigger a change to that state from outside a react component context
3. The component will rerender, but the useEffect hook will not trigger again

The problem goes away if you wrap the state change in `unstable_batchedUpdates`

See code example for a minimal reproduction (Originally from [here](https://github.com/pmndrs/zustand/issues/115#issuecomment-644960820) but updated to latest React)

Link to code example:
https://codesandbox.io/s/musing-vaughan-95rlv

## The current behavior
`useEffect` is not run again even though a dependency has changed

## The expected behavior
`useEffect` should run again when a dependency changes

**Comment by eps1lon** [comment]
Thanks for the report.

Your `useExternalState` hook has a side-effect during render: ` updaters.add(forceUpdate);`. Once you move it into the effect, batched and unbatched updates work consistent:
```diff
function useExternalState() {
  const forceUpdate = useReducer(v => v + 1, 0)[1];
- updaters.add(forceUpdate);
  useEffect(() => {
+   updaters.add(forceUpdate);
    return () => updaters.delete(forceUpdate);
  }, [forceUpdate]);
  return externalState;
}
```

The issue on the zustand repo was closed. Why do you think this is an issue with React?

**Comment by dentrado** [comment]
Thanks! I totally missed that. It might well be something similar causing my original problem as well. But I can't say I understand how adding an extra listener (?) could cause the useEffect to not trigger. Or what is happening here?

> The issue on the zustand repo was closed. Why do you think this is an issue with React?

I wasn't really sure, but from what I could see the zustand issue was closed without a fix or any real conclusion whether it was a bug or expected behavior. So I reported it to see if someone here could shed any more light on it. As you pointed out it does look like it's caused by side-effects outside of `useEffect` so I guess it's not a bug after all, thanks again for pointing out the issue!

**Comment by eps1lon** [comment]
>  But I can't say I understand how adding an extra listener (?) could cause the useEffect to not trigger. Or what is happening here?

It might be worth trying to figure this out and see if we can add a warning. In the end you're calling a version of `dispatch` that wasn't committed. But it's not clear if this would conflict with render phase updates.

Don't really have the time to dig into this though. I do understand how this particular issue with side-effects during render is tricky because it just silently produces unexpected output. Would be interesting to see if this can also happen with prod builds i.e. render twice, commit once due to a sibling suspending.

**Comment by dentrado** [comment]
Thanks for helping me find the actual problem, I'll close this issue now. I agree it would be nice with some sort of warning. 

>In the end you're calling a version of `dispatch` that wasn't committed. But it's not clear if this would conflict with render phase updates.

Which `dispatch` do you mean here? Do you have pointers to any resources for learning more about the internals of how this works. Would be fun to try and work out exactly what's happening, but think I have some knowledge gaps I need to fill first.

**Comment by artalar** [comment]
Hi there! @dentrado thx for describing an issue, as u mention below, users of Reatom have the same problems.
@eps1lon @gaearon please, may you comment detailed description of the problem and how it may be solved and paste it in the docs? This is soo unobvious right now, but important for many people, which just remove `StrictMode` that does not look like a better way.
