### ISSUE TITLE
Feature request: custom error handlers in ReactPartialRenderer

### ISSUE THREAD

**Issue by yepitschunked** [facebook/react#20711]
I'd like the option to pass a custom error handler for ReactPartialRenderer. The custom handler should be able to specify whether we:
  - throw and abort the render (basically same as existing behavior)
  - return a substitute element
  - pause the render at the erroring element; the next read() call will resume and effectively retry rendering the element. Return the output buffer up to the point where we paused.

I have two use cases:

1. Returning a substitute element could be an alternative to the ErrorBoundary in SSR. I understand why ErrorBoundary doesn't work due to in-order streaming issues (e.g https://github.com/facebook/react/issues/10442#issuecomment-321904824) - we can't replace the entire tree up to the parent, but a custom handler could at least render a placeholder error div or something. Would be useful in dev. 
2. Implementing a poor-man's Suspense by pausing the render. More below...

It seems like the intended design direction for Suspense is to skip suspended components on the server and render fallbacks. I'd like to instead stream HTML up until hitting an async dependency, and block there until the dependency is resolved. Having an official custom error handler API would let me implement this outside of React.

I was able to hack together a quick example in this sandbox link: https://codesandbox.io/s/node-js-forked-5lzro?file=/src/index.js

Most of the complexity comes from catching the error, cleaning up state, and returning the in-flight output buffer contents; the rest of the logic (e.g resuming the stream after promises have been resolved) can be handled in client code outside of React.

I realize this sounds a lot like the use-case for Suspense. However, it seems like Suspense is mostly client-focused, and many of the problems with concurrency, etc. are avoidable on the server, which doesn't have these problems. Adopting Suspense with a legacy codebase is hard due to concurrent mode restrictions. We can't really take advantage of reduced restrictions on the server, since there's no way to only opt into Suspense on the server.

**Comment by gaearon** [comment]
>It seems like the intended design direction for Suspense is to skip suspended components on the server and render fallbacks

No, that's not correct. That's a temporary limitation because the current server renderer does not support proper streaming. The intended design direction (with likely some work in the next few months) is to stream the actual content. That requires building a new server renderer.

>However, it seems like Suspense is mostly client-focused

This is also not quite right, it was originally designed *for* the server (with this precise problem in mind), but we've taken a detour to figure out the client semantics. Now that those are mostly settled, we're getting back to the original problem.

**Comment by gaearon** [comment]
Btw if you're running in Concurrent Mode, the client already supports hydrating _rendered content_ even if the client Suspends. E.g. if the code for a component is still loading on the client, but the server produced content HTML. Now what's left is to build a server renderer that takes advantage of that. Internally, we currently use a hack that simulates streaming by stitching together multiple `renderToString()` responses, but that's not good.
