### ISSUE TITLE
Bug: CodeSandboxes for Concurrent Mode don't work

### ISSUE THREAD

**Issue by arcticmatt** [facebook/react#20737]
I'm reading through the docs here https://reactjs.org/docs/concurrent-mode-suspense.html. When I try clicking on any of the CodeSandboxes, I see this error:

![image](https://user-images.githubusercontent.com/4356178/106948953-3783ee80-66e1-11eb-9134-82f49495551e.png)

https://codesandbox.io/s/frosty-hermann-bztrp is an example, but any of the CodeSandboxes on https://reactjs.org/docs/concurrent-mode-suspense.html (and other Concurrent Mode documentation pages) should have the same problem.

**Comment by bvaughn** [comment]
We're sorry about this problem. We only just became aware of it.

Since it is a Code Sandbox issue (and not a React issue) I'm going to go head and close this issue here, but the React team has notified the Code Sandbox team and they are currently working to resolve the issue.

**Comment by rickhanlonii** [comment]
This should be fixed now, big shout out to the Code Sandbox team for fixing this so quickly!
