### ISSUE TITLE
Feature Request: render React *to* a node, not *in* a node.

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#20738]
When using React with other libraries, I'm often forced to deal with DOM nodes directly to change their style or content. However, `ReactDOM.render` will always create content inside the provided DOM node rather than use the given DOM node as the element to mutate.

```ts
// Suppose this span is given in a function argument for some other frontend library.
const span = document.createElement('span') 

// I want to mutate this element using React's utilities
ReactDOM.render(<span style={{color: 'blue'}}>Hello</span>, span)
```

So maybe this functionality will not be called with `ReactDOM.render`, but it would be great if the internal tools for updating DOM nodes were exposed so I can keep using React when interfacing with external libraries.

Thanks!

**Comment by haneenmahd** [comment]
Looks like you have not appended the span element to the any parent element.

I would like to reproduce that behaviour if you share the codesandbox link :)

**Comment by ccorcos** [comment]
Here's a code sandbox trying to highlight the goal: https://codesandbox.io/s/muddy-fog-rbitl?file=/src/index.js

And this is the relevant code:

```ts
import ReactDOM from "react-dom";

const div = document.createElement("div");
document.body.appendChild(div);

function Comp() {
  return <div style={{ color: "blue" }}>hello world</div>;
}

ReactDOM.render(<Comp />, div);

if (div.style.color !== "blue") {
  console.error("React rendered into the div rather than mutating the div.");
}
```

I want to use React to style a specific node rather than rendering a new node inside of it.

**Comment by haneenmahd** [comment]
Do you want to render Comp() to the Newly Created div?

**Comment by ccorcos** [comment]
I want to use React to mutate the newly created div rather than create a new div inside.

**Comment by shadowtime2000** [comment]
@ccorcos The only reason it is creating a new div is because your component is making a new div. If you don't want that to happen call `ReactDOM.render(<Comp />, document);`.

**Comment by ccorcos** [comment]
I'm aware... Maybe I need to motivate this feature request with a more in-depth better example to get my point across.

```ts
// Suppose this function comes from a library.
function createEditor(args: {
	root: HTMLElement
	data: Array<string | { mention: string }>
	renderMentionToken: (node: HTMLElement, data: { mention: string }) => void
	onChange: (data: Array<string | { mention: string }>) => void
}) {
	// Inside here is a bunch of library code that sets up a contentEditable document.
}

// This is my React component that I'm using to wrap around this editor library.
function Editor(props: {
	initialData: Array<string | { mention: string }>
	onChange?: (data: Array<string | { mention: string }>) => void
}) {
	// Create a ref to get the div.
	const ref = React.useRef<HTMLDivElement | null>(null)

	// Immediately after rendering, construct the editor.
	React.useLayoutEffect(() => {
		createEditor({
			root: ref.current!,
			data: props.initialData,
			onChange: props.onChange,
			renderMentionToken: (node, data) => {
				// This is the place where this feature request comes up.
				// `node` is an HTMLElement. It already has data-attributes
				// and other things all set up on it. This is an opportunity
				// for me to do whatever I want with the node.

				// Suppose I use ReactDOM.render...
				ReactDOM.render(
					<span style={{ color: "blue" }}>@{data.mention}</span>,
					node
				)
			},
		})
	}, [])

	return <div ref={ref}></div>
}
```

Now suppose when I actually render this component, here's what I'm going to see:

```ts
<Editor initialData={["Hello ", {mention: "Chet"}]}/>
// Actual: <p>Hello <span data-mention="Chet"><span style="color: blue;">@Chet</span></span></p>
// Desired: <p>Hello <span data-mention="Chet" style="color: blue;">@Chet</span></p>
```

Notice that there's a span in a span here because `ReactDOM.render(<span style={{ color: "blue" }}>@{data.mention}</span>, node)` renders **inside** the node. But what I want to be able to do is use React and JSX and all those semantics, but actually mutate the given node rather than create a new node inside it. The reason I need to do it this way is to do existing constraints from external libraries.

Does that make sense in terms of motivation and what I want?

**Comment by shadowtime2000** [comment]
@ccorcos Yes that makes sense.

That doesn't seem like a feature that should be implemented, because the element that is given is to be used like a container element to have stuff put inside, not to be mutated. If React DOM were to mutate it it would possibly cause some conflicts with however you got that DOM node, and it seems like a better idea to just place the element inside of it instead of mutating it to keep it seperate in a sense.

**Comment by ccorcos** [comment]
> That doesn't seem like a feature that should be implemented, because the element that is given is to be used like a container element to have stuff put inside, not to be mutated.

I understand that this is the current functionality. 

My thinking is that React must have a bunch of internal utilities for doing all of these things I need. For example, it would be valuable to me just to have a utility where I can specify React-style JS-in-CSS and simply reconcile that with the existing DOM node. e.g. `React.style({color: "blue", node)`

>  it seems like a better idea to just place the element inside of it instead of mutating it to keep it seperate in a sense.

I understand that there are ways of accomplishing these things in a different way, for example if I created my own contentEditable library. But there are set of existing constraints I am working with so it's not and changing these constraints is not a solution.

My point is just to highlight that this is a need I have and it would be great if this library could fulfill that need. And it seems like solving these issues are well within the capabilities of this library.

Perhaps a simpler place to start is just with CSS. That way, I can re-write my original example as:

```ts
ReactDOM.style({color: "blue", node)
ReactDOM.render(<>Hello</>, node)
```

**Comment by cameron-martin** [comment]
What happens if you try rendering into a document fragment? Seems that would solve your problem if it were to work.

**Comment by ccorcos** [comment]
@cameron-martin that doesn't work because its rendering into the document fragment, not modifying the root node.

**Comment by cameron-martin** [comment]
Yes, nevermind that would not solve your problem under closer inspection.

**Comment by TomokiMiyauci** [comment]
This will make partial hydration easier to achieve.

Preact plans to add [Create Fragment root](https://gist.github.com/developit/f4c67a2ede71dc2fab7f357f39cff28c) utility in the next major update.

**Comment by ccorcos** [comment]
I would still like this feature. It would alllow me to use React with rich text editors like Prosemirror
