### ISSUE TITLE
Bug: No way to specify the same CSS property twice in inline style

### ISSUE THREAD

**Issue by henrik** [facebook/react#20757]
Hi! As far as I can tell there is no (simple) way in a React component to provide the same property twice in a style attribute, e.g. to turn into this HTML:

    style="background-image: url(foo.jpg); background-image: -webkit-image-set(url(foo_1x.jpg) 1x, url(foo_2x.jpg) 2x)”

Providing the same property twice for browser compatibility reasons is a common practice. (Incompatible browsers will ignore the declaration they can’t parse. Compatible browsers will overwrite the fallback declaration with the newer declaration.)

My use case for an inline style here is that the image URLs are dynamic, from a DB.

I asked about it here and haven’t found or heard about a solution yet, other than introducing further dependencies: https://stackoverflow.com/questions/66060349/how-do-i-add-the-same-css-property-e-g-background-image-multiple-times-with-r

I admit this is a somewhat edgy case (both wanting multiple of the same property and an inline style) but I still think it could be considered a bug if React doesn’t support it.

**Comment by spassvogel** [comment]
If you're willing to use css you could put the dynamic image urls in css vars via the `style` tag and then read those in your static css.

```
<Component
  style={"--image1": "foo.jpg", "--image1x": "foo1x.jpg", "--image2x": "foo2x.jpg"}
  className="image"
/>
```

css
```
#image {
  background-image: url(--image1); 
  background-image: -webkit-image-set(url(--image1x) 1x, url(--image2x) 2x)
}
```

**Comment by henrik** [comment]
@spassvogel Thank you! That's very clever.

I'll close this issue because this fixes the React side of things. Turns out it doesn't quite work in my case anyway, but for reasons not directly related to React. (Using two background-image declarations works fine to achieve a fallback normally, but if I introduce CSS variables, Firefox stops falling back and fails to get a background image at all.)
