### ISSUE TITLE
Bug: React useState => setState with callback works unexpected.

### ISSUE THREAD

**Issue by geewoo94** [facebook/react#20764]
React version:    "react": "^17.0.1"

# Steps To Reproduce

setState is effected remark??

### Without Remark
<img width="677" alt="withoutRemark" src="https://user-images.githubusercontent.com/65149763/107308334-ccb12980-6acb-11eb-839c-2d7f5b0ecc5d.png">

![withoutRemark-mov](https://user-images.githubusercontent.com/65149763/107308691-6ed11180-6acc-11eb-9bcc-2c9526c0dc99.gif)

### With Remark
<img width="677" alt="withRemark" src="https://user-images.githubusercontent.com/65149763/107308338-cf138380-6acb-11eb-882a-62e485b80ad7.png">

![withRemark-mov](https://user-images.githubusercontent.com/65149763/107308715-785a7980-6acc-11eb-8c80-b40a39753e1e.gif)

### Test Link
CodeSandBoxLink: https://codesandbox.io/s/beautiful-lehmann-0dkk8?fontsize=14&hidenavigation=1&theme=dark

## The current behavior

setState works inconsistent and unexpected.

## The expected behavior

setState should works consistent and expected.

**Comment by eps1lon** [comment]
Thanks for the report.

> setState should works consistent and expected.

It's unclear what you mean by this specifically. "consistent" or "expected" behavior is subjective so I'd like you to ask to be more specific about the observed behavior you'd like to see.

Note that there are two potential issues with your code:

1. Your functional update in `setState` is not side-effect free.
    It must not mutate the current state.
    ```diff
    const newTodos = prevTodos.map((todo) => {
      if (todo.name === name) {
    -   todo.isDone = !todo.isDone;
    +   return  {
    +     ...todo,
    +     isDone: !todo.isDone,
    +   }
      }
      return todo;
    });
    ```
   For an exhaustive list of what needs to be side-effect free in React check out [Detecting unexpected side effects](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects)
1. logging objects: these are "live" in the console. This means that they don't reflect their values at the time of logging but at the time of inspection. See https://stackoverflow.com/questions/24175017/google-chrome-console-log-inconsistency-with-objects-and-arrays for more information.
