### ISSUE TITLE
Image src with image object

### ISSUE THREAD

**Issue by dmitrig01** [facebook/react#2077]
I don't see a way to do this now. In vanilla JS, you can do something along the lines of

```
var image = new Image(); 
image.src = "heavyimagefile.jpg";

document.querySelector('img').src = image;
```

It'd be great to be able to pass an `Image` object into `<img src={ } />`. Concretely, I'm using this for file upload previews.

**Comment by GregJunkaTR** [comment]
@zpao Your example won't work with cross-origin requests. If the image file is served on a different domain then creating an 'img' element with src set to that image will load the image regardless of CORS but loading the file in JavaScript won't.
