### ISSUE TITLE
Bug: Safari div contentEditable，onMouseUp trigger before onMouseDown

### ISSUE THREAD

**Issue by SmallComfort** [facebook/react#20787]
React version: 17.0.1

## Steps To Reproduce

1. Mac OS Big Sur version 11.2，Safari  version 14.0.3 
2. set div contentEditable
3. div addEventListener onMouseUp and onMouseDown
4. onMouseUp trigger before onMouseDown

Link to code example:
```
<div
  onMouseDown={() => {console.log('mouse down')}}
  onMouseUp={() => {console.log('mouse up')}}
  suppressContentEditableWarning
  contentEditable>
  Test ContentEditable In Safari
</div>
```

## The current behavior

onMouseUp trigger before onMouseDown

## The expected behavior

onMouseUp trigger after onMouseDown

**Comment by haneenmahd** [comment]
Would you just try again!.
When i wrote the same code you shown me above it works fine!

**Comment by SmallComfort** [comment]
> Would you just try again!.
> When i wrote the same code you shown me above it works fine!

I tried it again and if you tap the touchpad with one finger, In the first time mouse event works fine, But in the next time you tab the touchpad, the mouse event will be reverse.

**Comment by codingstar** [comment]
I went into the same issue!

**Comment by eps1lon** [comment]
I cannot reproduce this in Safari 16.0: https://zsgyov.csb.app/


For anybody able to reproduce this in the latest version of React, could you include a video so that I can understand better how you were able to reproduce?

**Comment by codingstar** [comment]
> I cannot reproduce this in Safari 16.0: https://zsgyov.csb.app/
> 
> For anybody able to reproduce this in the latest version of React, could you include a video so that I can understand better how you were able to reproduce?

I suspect that this is related to the third-party IME. When switching to a third-party IME (such as Sogou, Baidu IME), this problem sometimes occurs.

@eps1lon 
see this video for more detail:
<https://drive.google.com/file/d/10GMslCbibwmuLBwyX8o3t0IjnEgsX3Tt/view>

**Comment by eps1lon** [comment]
> > I cannot reproduce this in Safari 16.0: [zsgyov.csb.app](https://zsgyov.csb.app/)
> > For anybody able to reproduce this in the latest version of React, could you include a video so that I can understand better how you were able to reproduce?
> 
> I suspect that this is related to the third-party IME. When switching to a third-party IME (such as Sogou, Baidu IME), this problem sometimes occurs.
> 
> @eps1lon see this video for more detail: [drive.google.com/file/d/10GMslCbibwmuLBwyX8o3t0IjnEgsX3Tt/view](https://drive.google.com/file/d/10GMslCbibwmuLBwyX8o3t0IjnEgsX3Tt/view)

Interesting. Thank you for providing more detail.

What happens if it's just using basic JavaScript? https://szsb2m.csb.app/

**Comment by codingstar** [comment]
> > > I cannot reproduce this in Safari 16.0: [zsgyov.csb.app](https://zsgyov.csb.app/)
> > > For anybody able to reproduce this in the latest version of React, could you include a video so that I can understand better how you were able to reproduce?
> > 
> > 
> > I suspect that this is related to the third-party IME. When switching to a third-party IME (such as Sogou, Baidu IME), this problem sometimes occurs.
> > @eps1lon see this video for more detail: [drive.google.com/file/d/10GMslCbibwmuLBwyX8o3t0IjnEgsX3Tt/view](https://drive.google.com/file/d/10GMslCbibwmuLBwyX8o3t0IjnEgsX3Tt/view)
> 
> Interesting. Thank you for providing more detail.
> 
> What happens if it's just using basic JavaScript? https://szsb2m.csb.app/

I've tried to use basic JS, and get the same result in Safari.

It seems that if there is some thing `contenteditable` in `<body>` and using third-party IME, mousedown/mouseup events will not be in order.

<https://jsbin.com/lewekucese/edit?html,js,console,output>
@eps1lon

**Comment by eps1lon** [comment]
So it sounds to me this should also be opened as a Safari bug. Maybe that way we understand how this happens and if there's a fix that we can possibly include in React.

**Comment by karlcow** [comment]
1. Does it still reproduce in the current version of Safari Technology Preview 177 or 178.
2. Was a bug opened on https://bugs.webkit.org/ for this?

**Comment by egoist** [comment]
I came across the same problem, onMouseUp is triggered before onMouseDown and onClick requires tapping twice to trigger.

I found that only happens when you switch mac's Input Source to Japanese - Romaji or some third party Chinese Input Methods like Sogou or Wechat.

![CleanShot 2023-11-27 at 15 47 11@2x](https://github.com/facebook/react/assets/8784712/cdcd039d-b1f2-4c0c-a135-36fc7a0fa562)


I'm able to reproduce this in latest Safari (Version 17.1 (19616.2.9.11.7)) and Safari Technology Preview

**Comment by egoist** [comment]
related bug report: https://bugs.webkit.org/show_bug.cgi?id=219670 I also commented there

**Comment by karlcow** [comment]
going to https://zsgyov.csb.app/
And doing one tap.

```
[Log] 2023-11-28T04:06:04.942Z pointerdown  (x2)
[Log] 2023-11-28T04:06:04.942Z mousedown  (x2)
[Log] 2023-11-28T04:06:04.942Z react-mousedown 
[Log] mouse down
[Log] 2023-11-28T04:06:04.943Z pointerup  (x2)
[Log] 2023-11-28T04:06:04.943Z mouseup  (x2)
[Log] 2023-11-28T04:06:04.943Z react-mouseup 
[Log] mouse up
[Log] 2023-11-28T04:06:04.944Z click 
[Log] 2023-11-28T04:06:04.948Z click 
[Log] 2023-11-28T04:06:04.948Z click 
[Log] 2023-11-28T04:06:04.948Z click 
[Log] 2023-11-28T04:06:04.951Z selectionchange 
[Log] 2023-11-28T04:06:04.952Z selectionchange  (x2)
```

Switching to Japanese Input Mode. 

```
[Log] 2023-11-28T04:08:50.926Z pointerdown  (x2)
[Log] 2023-11-28T04:08:50.926Z mousedown 
[Log] 2023-11-28T04:08:50.927Z mousedown 
[Log] 2023-11-28T04:08:50.927Z react-mousedown 
[Log] mouse down
[Log] 2023-11-28T04:08:50.928Z pointerup 
[Log] 2023-11-28T04:08:50.929Z pointerup 
[Log] 2023-11-28T04:08:50.930Z mouseup  (x2)
[Log] 2023-11-28T04:08:50.930Z react-mouseup 
[Log] mouse up
[Log] 2023-11-28T04:08:50.931Z click  (x2)
[Log] 2023-11-28T04:08:50.931Z click 
[Log] 2023-11-28T04:08:50.931Z click 
[Log] 2023-11-28T04:08:50.934Z selectionchange 
```

Is there something I'm missing. 
Or a configuration I need to set?

**Comment by karlcow** [comment]
I can confirm. Thanks.
