### ISSUE TITLE
Bug: Typescript doesn't infer generic type from type returned from function passed as prop

### ISSUE THREAD

**Issue by velialiev** [facebook/react#20781]
# Bug

Typescript doesn't infer generic type from type returned from function passed as prop

## Steps To Reproduce

Create component with such props:
1. Data that has generic type
2. Function that takes argument that typed using generic from 1. and returns another generic type
3. Another function that takes argument that typed using generic returned from 2.

Then fill this props and check could typescript resolve argument type in function from 3.

This bug probably in react, but not in typescript, because with simple function instead of component this example works fine

Link to code example:

https://www.typescriptlang.org/play?ts=4.1.3#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecAKUEYAzgOrAwAWAwlcADYAmUSAdnAL5wBmRIcAOSt0MQQChxaCGxLwYSOQEY4AXjgAeAKJsYlAJ7YAcooVMdemPoB8ACnFw4TFDBQAuOBYMBtALrYHOFYSCAYANyQAZQgQJGpgNgBzD1t2S30PLysASjVrODkoBMTMQODQiJM5JCYUtINM3QNc1Xyqsyz9P1LHcvComLj6JIAxfnaazrqmqw8J8xn9Fvy2AFcQACMkKFLl3ElOSQVle0dvPB5gJGYPQSUAJgBmQWw2UxqPc7g36qYRq5ucAejy4vlBAUc9SseTgUP0ADpLtcmBDYYsYXD4T8zKjsZN0a1vu8FukscT-sjdpJpLJ4AAVUxqTQARVWpmAMmwAEFZAB3bZ2HCBY4wEg9IKKCpIVnsmQASRRZUl-Rlcg5bAZAA8sEqQiq2WqZDySPyoGLdVLjaaFeK+hErdstTrOB5CMRyJRaPRmKw2Bo3aQNKq9Jy4A6oNZrHshb04qsoBxTo5NExgGFrIFk3BM5oAPSp9OBbLiQ7iBIKKA8dBIAhEQPB9XcvkC-aOEUkDwNmR+OAAHzgqzYTCQlzeTAt+tlbAVKQAjgaQ2xOwv1Xs1ptthOIl2NUhtXOVzJl1O9oVilvpYe2OGO3BbPOp8fDWw9uG-BfwzO7yhm1APOG13WLYoA-X8nRSH8TW2f9f1PGAiiSEtJD3SBYDgcttirNAa0iGBVmHXQAFlVgYPQGTkOUFBAAARGAIFbdCqK-ddgMCSgkBAcCCng89HHYkAbw8XD8LSYjSOAciYEojjw1oiB31LFDoHgDDK2rOBhIImAxLI0xpIE385IY-jP1qb4gM3PiqPDLiz0Q0saTkOB2yEvCtJ0iS9KouSe3Ud8pBkJyRXuJkk0cDRJJzLN21UHB20OLMsztS8pwVWKH2fGEMsXeF+IVBLEtjPVtyvJ10qvLKr1yqinQKwrkp3G9yqnSqp2qmTfxIOrEuS0zYsg00YQG7Z2oMqCoHyqLk16sC9xgfrfyG39RpsubutzDNiyAA

## The current behavior

Type not resolved

## The expected behavior

Type should resolve like in simple function

**Comment by gaearon** [comment]
The React repository does not include anything TypeScript-specific. If this is a bug, it's either in TypeScript itself, or in the React bindings which are maintained in the DefinitelyTyped repository. Please file an issue there. Thanks!
