### ISSUE TITLE
Bug: react deverloper tools: component state read only

### ISSUE THREAD

**Issue by Swazimodo** [facebook/react#20797]
React version:
react: 17.0.1
react-scripts: 4.0.1.
react developer tools: 4.10.1
chrome: 88.0.4324.150

## Steps To Reproduce

1. create create-react-app
2. build the app `yarn build`
3. Host the app somewhere
4. Open the app with react-developer-tools
5. Try to update the state of components

## The current behavior
State is grayed out and read only.

## The expected behavior
Able to upate the state.

**Comment by technikhil314** [comment]
When you do build the production mode is on. And react-dev-tools does not allow to change state in production. For obvious reasons.

**Comment by Swazimodo** [comment]
> When you do build the production mode is on. And react-dev-tools does not allow to change state in production. For obvious reasons.

I'll try to clarify, `react-scripts build` always builds a prod build but if I have multiple environments I want to use dev builds for pre-prod. There should be a way to pass in the envrionment you want built. Running `react-scripts start` uses the dev environment but only loads into memory and does not actually build the files that could be hosted.
