### ISSUE TITLE
Bug: devtools reload-and-profile feature is defeated by sync-xhr feature policy

### ISSUE THREAD

**Issue by roippi** [facebook/react#20806]
React version: all

## Steps To Reproduce

1. Visit a site that uses `Feature-Policy: sync-xhr 'none'` and has the profiling build of react enabled
2. Attempt to use the "reload and start profiling" feature of devtools
3. The xhr request will fail on reload because it [attempts to make a synchronous XHR call](https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/react-devtools-extensions/src/injectGlobalHook.js#L84).  The profiling tab will be stuck in "press record to stop recording" state.  Devtools will now fail to load on all subsequent refreshes unless the developer clears session storage, because it keeps trying and failing to make that XHR request.

## The current behavior
see `3.` above

## The expected behavior
Ideally, this feature would not depend on synchronous XHR to function.  [Browsers are deprecating it](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#synchronous_request) and sites are blocking it via `Feature-Policy` due to third-party javascript abusing it.
In its current state, the feature should fail more gracefully when the XHR is blocked due to feature policy or in the future when browsers start blocking it by default.

**Comment by bvaughn** [comment]
I'm not sure if that deprecation will apply to extensions. Hm. Regardless, I don't know of any other technique available to implement the reload-and-profile behavior than the sync XHR approach we currently use. (I discussed this approach with Chrome extension dev rels before implementing it because I was concerned about it too.)

Any interest in submitting a PR that detects `Feature-Policy: sync-xhr 'none'` and disables the reload-and-profile button with a tooltip/message explaining why? :)

**Comment by roippi** [comment]
I'll reach out to my dev rel folks too to see if there's any alternative.  Regardless yeah reworking the feature is dependant on finding that better alternative so we can put that part of the issue aside.

I should have the time/ability to submit a PR for the _ensafeining_.  If I don't, and some enterprising individual finds this in the meantime, the way to introspect this in JS is:

```js
document.featurePolicy.allowsFeature('sync-xhr')
```

**Comment by ChrisDobby** [comment]
Not sure if I count as an enterprising individual but thought I'd have a go at this!

**Comment by bvaughn** [comment]
Thanks Chris! 👍🏼

**Comment by roippi** [comment]
Thanks Chris et al!  I'll follow up with a new issue if I find an alternative for sync xhr.
