### ISSUE TITLE
Unable to Add it in Chrome Dev Tools.

### ISSUE THREAD

**Issue by suhaibk9** [facebook/react#20818]
I have uninstalled and installed it in Chrome multiple times but the components option never show up.

**Comment by iChenLei** [comment]
You can open `chrome://extensions` and click the `error` button to look for more error info.
or open chrome devtool to find info from `console` tab.

![2021-02-14 19 33 23](https://user-images.githubusercontent.com/14012511/107875534-83157400-6efb-11eb-9c9e-0b2f18c43b42.png)

Your current info is not enough to find the bug.

**Comment by bvaughn** [comment]
This bug report doesn't have much info.

What Chrome version are you using? Which operating system (and version) are you using?

Also please be aware that the React DevTools extension will only show up if you're on a website that's built with React (like www.reactjs.org)
