### ISSUE TITLE
When you pass object instance into React Component props, object instance is never cleared from memory.

### ISSUE THREAD

**Issue by czmok** [facebook/react#20819]
Hi, 
I have an issue with passing object reference into React Component props. I pass `example` into `prop1` of `TestReactComponent`. Then, in `removeInstance` method I clear the object instance. After setting it to `null` object instance shouldn't be visible in memory.
Example code: 
```
function App() {
  let example = new ExampleClassInstance();
  const key = Math.random();
  const removeInstance = () => {
    unmountComponentAtNode(document.getElementById('example-wrap'))
    example = null;
  }
  return (
    <div className="App"  id="example-wrap">
      <div >
        <TestReactComponent  key={key} prop1={example} ></TestReactComponent>
      </div>
      <button onClick={()=> removeInstance()}>remove</button>
    </div>
  );
}
export default App;
```

After setting `example` to null (after calling `removeInstance` method) I expect not to have an object instance in memory, but unfortunately it still exists. After recording Heap Snapshot from Memory tab I see result: 
```
ExampleClassInstance | 9 | 560 % | 2440 %
prop1 in Object@591215🗖 | 8 | 120 % | 5600 % |  
      -- | -- | -- | -- | --
              memoizedProps in FiberNode@591281🗖react-dom.development.js:24666 | 7 | 1400 % | 1880 % |  
              returninFiberNode@591301🗖react-dom.development.js:24666 | 6 | 1400 % | 1880 % |  
              __reactFiber$lwytjywp7qinText@317739🗖

```
Snapshot says :  `memoizedProps in FiberNode`. 
PS I don't use `memo` function for the component.

After setting `example` to `null` I expect don't see object instance in memory anymore.

Please for help. If something is not clear please ask.

**Comment by tsairinius** [comment]
I think it makes sense that `example` would still occupy space in memory because `null` in JavaScript is a primitive. Setting `example` to `null` does not garbage collect the variable. And since it is being referenced by `TestReactComponent` as a prop, it will remain in memory even if it's `null`.  So I believe this is just expected behavior in JavaScript. Let me know if I misunderstood the issue.

**Comment by czmok** [comment]
@tsairinius , thank you for answer! But in case when I don't pass object instance into React Component props, after setting it null GC cleans it. I forgot to mention it.

**Comment by czmok** [comment]
I created one more example only with JS code where in `setInstance` method I set instances of another class. After calling `removeInstance` everything is cleared from memory - works as I expect.

```
function App() {
  let example = new ExampleComponentInstance();
  let example2;

  const removeInstance = () => {
    example = null;
    example2 = null
  }

  const setInstance = (classInstance) => {
    example2 = new Example2(classInstance);
  }

  return (
    <div className="App" id="example-wrap">
      <button onClick={() => setInstance(example)}>set instance</button>
      <button onClick={() => removeInstance()}>remove</button>
    </div>
  );
}
```
```

Snapshot 1 from memory before `setInstance` method: 

ExampleComponentInstance | 9 | 560 % | 2440 %
-- | -- | -- | --


Snapshot 2 from memory after `setInstance`: 
Example2 | 8 | 560 % | 2800 % |  
ExampleComponentInstance | 8 | 560 % | 2520 %
```

Snapshot 3 after `remove` method: Memory is free from `ExampleComponentInstance` and `Example2`

**Comment by davidBar-On** [comment]
The difference between the first and second examples is that in the first example `TestReactComponent` holds a reference to `example`.  As @tsairinius explained, this prevents removing `example` when it is set to null. In the second example, there is no such reference to `example ` and `example 2`, so when they are set to null they can be removed.

**Comment by maxim-engr** [comment]
Perfect, was fixed this issue on my end.
