### ISSUE TITLE
Uncaught Error: Extension context invalidated.

### ISSUE THREAD

**Issue by sachinjachak2001** [facebook/react#20811]
I am added react developer tool extension in my chrome but it's continuously throwing an "Uncaught Error: Extension context invalidated" this error, I try this extension in Firefox and it is smoothly running. so what is a problem with chrome???

**Comment by shivamCode0** [comment]
Could you show a screenshot of the error or say where it is? Also, try reinstalling it.

**Comment by bvaughn** [comment]
This bug report doesn't have much info.

What Chrome version are you using? Which operating system (and version) are you using?

> Extension context invalidated

Sounds like an error that would happen if you updated the DevTools extension and then went back to a page where you had been using it. In that case the fix is just to close and re-open the developer tools pane and reload the page. (Or you could just restart your browser.)

**Comment by emlm** [comment]
I found this issue playing while doing some babysteps in react and getting the same error in Chrome dev console  with the React developer extension enabled.

Info:
Ubuntu 20.04
Chromium 
Version 89.0.4389.128 (Official Build) snap (64-bit)

Console:
Uncaught Error: Extension context invalidated.
    at injectGlobalHook.js:526
     script.src = chrome.runtime.getURL('build/react_devtools_backend.js');

I get it in some code i was refactoring from React class components to react function components

But i cannot specifically locate the code triggering it.

**Comment by CaninoDev** [comment]
I don't believe the merged issue is related to this. For one, the merged issue has a higher specificity (using redux and occurs during execution of `injectGlobalHook`. I currently have this issue and am not using Redux nor do I get that particular error. 

Using: 
Google Chrome -- Version 91.0.4472.114 (Official Build) (64-bit)
React Developer Tools: 4.13.5 (5/25/2021)
Manjaro: Stable Branch (recently updated as of today
System Information: 
```
CPU: 8-Core AMD Ryzen 7 2700X (-MT MCP-) speed/min/max: 3162/2200/3700 MHz Kernel: 5.12.14-2-MANJARO x86_64 Up: 15h 46m 
Mem: 9873.2/16008.7 MiB (61.7%) Storage: 3.66 TiB (33.9% used) Procs: 456 Shell: Zsh inxi: 3.3.04 
```

This error would occur not immediately upon a hard reload but after a random period. Once the first error appears, it repeats multiple times a second. Below is the log of said issue (truncated to remove extraneous text). 
[UncaughtError.log](https://github.com/facebook/react/files/6795823/localhost-1625944758116.log)
