### ISSUE TITLE
Bug: State changes cause DOM updates when returning function components, but not IntrinsicElements

### ISSUE THREAD

**Issue by anchpop** [facebook/react#20814]
React version: 17.0.1

## Steps To Reproduce

1. Create a component
2. Add state using a hook, initialized to 0
2. Use setInterval to update the state very frequently (e.g. every 16 milliseconds)
3. Return an IntrinsicElements (e.g. `return <p>hi</p>;`)
4. Everything works as expected - the DOM is written to exactly once and react's virtual DOM prevents the DOM from needing to be updated when the state changes, since the output of the function doesn't change
5. Modify the function to return a function component (e.g. `const Hi = () => <p>hi</p>; return <Hi />;`)
6. DOM updates now happen every time the state changes

Link to code example:

https://codesandbox.io/s/youthful-grothendieck-lc486?file=/src/App.js

P.S. if there is a better way of updating a prop or component state every frame I would like to know what it is

**Comment by anchpop** [comment]
Turns out this only happens when the function component is created inside the function. Probably because it gets recreated every render, and react doesn't know it's the same function. There might not be a reasonable way to resolve this

**Comment by markerikson** [comment]
Yes, this has always been part of React's behavior.  if `someElement.type` at a given position is a different reference than the last time React rendered this component, React treats that as a signal to throw away that portion of the component tree and DOM and re-create it:

https://reactjs.org/docs/reconciliation.html#elements-of-different-types

https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#component-types-and-reconciliation
