### ISSUE TITLE
Bug: Typescript and useState

### ISSUE THREAD

**Issue by dmitov** [facebook/react#20824]
When specifying a type in the useState, undefined is not taken into account. I'm unsure where is the issue - wether Typescript or React typings. Screenshot:
![string-or-undefined](https://user-images.githubusercontent.com/554345/107883181-12b82400-6ef6-11eb-9ebd-ebda591d983c.jpg)

React version: 17.0.1

## Steps To Reproduce

1. Open code example.
2. Clear console to exclude runtime errors.
3. Check type of `image`

Link to code example: https://codesandbox.io/s/mystifying-water-1z5fy

## The current behavior
`image` is resolved to `Image` only.

## The expected behavior
`image` should be `Image | undefined`

**Comment by shivamCode0** [comment]
This is the expected behavior. A better option for your code would be to remove the ` | undefined` and set the value to null.

**Comment by vkurchatkin** [comment]
You need to have a properly configured `tsconfig.json` file with `strictNullChecks` option set to `true` for this to work as expected. See  https://www.typescriptlang.org/tsconfig#strictNullChecks

**Comment by eps1lon** [comment]
> You need to have a properly configured `tsconfig.json` file with `strictNullChecks` option set to `true` for this to work as expected. See [typescriptlang.org/tsconfig#strictNullChecks](https://www.typescriptlang.org/tsconfig#strictNullChecks)

This is the correct answer.

[It's working as expected when enabling `strictNullChecks`](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgKIBmZSG2RSAyjCjEnAL5xlQQhwBEUqDLwDcAWABQE4ADtmUMuhYBJECgDmLHBLhxCUNAC5dMKDLVjxrCRKQAPSLDgATJAvwAbeGXzSMwCNJwAIJgYAAUAJS42nBoAYTwANqg6kgAunAAvATEDExIADwqqXAAPgTSLmQySE4AfGE+VTVOERYxtOSUGGGRWXXR4jo6cdKEEO5IAHQA7ihQ0mEwAJ5gSBBkcCkabTGs2MmqGmm7kkNwAjD4C3BhMToFTsAAbrHuKISEAHIoIEiZvBCYF4dXuwwKAAsAIx1HDbaZ6NCsAoAemhoPOwzgkIATHU8o5asAYGY4DAILokCxxn84EdgGg4BCUKEkNIAISoiF4sGop7PDE6U5WcRAA) (notice the error on line `<h1>{image.src}</h1>`).
