### ISSUE TITLE
Feat: Some type of way to merge key prop and useOpaqueIdentifier result 

### ISSUE THREAD

**Issue by SoAsEr** [facebook/react#20822]
Currently, the expected way to handle an unknown at compile time number of labels is to put them each in their own component. However, when creating tables, this causes a mess of callbacks, as the only way to do it (that I can think of anyway) is to pass a callback into the table header components, have them create their own unique identifier, and then use a useEffect to give the parent those identifiers, have the parent pass those identifiers to the rows, and then have each row generate its opaque own unique identifiers and pass both to the cells. Note that this doesn't work currently because of these two bugs:
https://github.com/facebook/react/issues/18594
https://github.com/facebook/react/issues/20127

However, react already has a way to differentiate items in loops: the key prop. To me, it would make sense to provide a function which merges a key prop with a unique identifier. This would allow the parent to generate the unique identifiers and pass them to the children, rather than having callbacks which cause a rerender. It would even make https://github.com/facebook/react/issues/20127 less relevant because there would be fewer motivating reasons to do so.

mergeOpaqueIdentifierAndKey is very wordy, but describes exactly what's going on. I don't have any particular preference about the name.

**Comment by eps1lon** [comment]
Prior art https://github.com/reactjs/rfcs/pull/32#discussion_r419501533. 

Naively we could just append the `key` to the generated id. But this would increase the number of bytes sent when doing SSR and also put new constraints on what kind of strings we can pass to `key`

**Comment by SoAsEr** [comment]
One way may be to create a new "section" of the opaque identifier like we already do for different react versions, and simply map keys to an incrementing number. This would make the opaque identifier have to carry the string and the key map. However, it would heavily limit the number of bytes added.

**Comment by SoAsEr** [comment]
Are we assuming that this function would be called in the same order on both client and server? I feel like we can. In that case we might as well just make it append an incrementing counter, no map or key needed.

**Comment by SoAsEr** [comment]
The other option would be to sort the keys added once we start the toString and then append their index. We wouldn't even have to use string compare at first. We could sort by length (which is faster) and then fall back to string comparison if their lengths are equal.

**Comment by SoAsEr** [comment]
New approach is totally different and doesn't need this complicated scheme: https://github.com/reactwg/react-18/discussions/111
