### ISSUE TITLE
Feature Request: usePureEffect

### ISSUE THREAD

**Issue by adrayv** [facebook/react#20837]
It would be great if React exposed a hook, potentially called `usePureEffect`, that works like `useEffect` (runs some code on some dependency change), but does not run on initial mount. 

This seems to be a common issue in the community. The de facto solution is to write a custom hook based on `useEffect` that keeps track of the initial render (via `useState` or `useRef`). While such a hook is arguably easy to implement (see below), since it's so common, it would be much more convenient if this was part of React's core API.

Potential Implementation
```js
const usePureEffect = (func, dependencies) => {
  const isFirstRender = useRef(true)
  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false
      return () => {}
    }
    return func()
  }, dependencies)
}
```

**Comment by hackersintu** [comment]
Nice working

**Comment by benzigar-codes** [comment]
Nice One !!

**Comment by bvaughn** [comment]
What is the use case for a hook like this? (Why isn't `useEffect` sufficient?)

**Comment by adrayv** [comment]
`usePureEffect` would be great for implementing update-only effects like subscriptions. I can't share my company's exact usage, but here's some close examples:

```js
const ComplexComponent = ({ onSomeEvent }) => {
  usePureEffect(() => {
    // on some non-trivial update/event, trigger onSomeEvent
    // this effect should be strictly triggered on an update and not on initial mount
  }, [...dependencies])
}

// Usage

render(
  <ComplexComponent onSomeEvent={() => { /* do something */}} />
)
```
Parent component subscribing to some custom lifecycle event of a child component

---

```js
const useDataStore = (onChange) => {
  const [data, setData] = useState([/* some data */])

  useEffect(() => {
    // runs on initial mount but the intention is to only run when there's a change
    onChange(data)
  }, [data])

  usePureEffect(() => {
    // only runs when there is a change
    onChange(data)
  }, [data])

}

const Component = () => {
  const onDataChange = (newData) => {/* do something */}
  useDataStore(onDataChange)
  return </>
}
```
Component subscribing to changes in a hook. *I know this isn't a common usage pattern for hooks* but hopefully the intent is clear. I wish could share more.

---

**Overall, it's a little odd that useEffect supports mount-only and mount-and-update effects, but not update-only effects.** Even if the use cases are rare, not having out-of-the box support for update-only effects makes `useEffect` seem incomplete. Perhaps even a change to the `useEffect` API, like the addition of an extra param, to declare an effect as update-only would be awesome.

**Comment by markerikson** [comment]
Seems like you're basically asking for the return of `componentDidUpdate`.

Given that a custom hook replicating that behavior can be done in userland, as you showed, I don't see any reason why that would need to be added to the core.  That is, after all, part of the point of custom hooks - you write the abstraction once, and then use it wherever it's needed.

**Comment by bvaughn** [comment]
@adrayv Sure, I understand _what_ you're describing but not the _why_. The code examples you shared seem to kind of only highlight the _what_. What are "_update-only effects like subscriptions_"? Why would you not also need to subscribe on mount?

@markerikson essentially said what I'm thinking. I guess you kind of did too when you said, "_I know this isn't a common usage pattern for hooks_". Given that it's pretty easy to implement this pattern in user space, and it's not a common use case, I don't think this is something we would offer as a built-in.

**Comment by shizhihua666** [comment]
It's like useMemo or useCallback?

**Comment by bvaughn** [comment]
> It's like useMemo or useCallback?

I don't see how that is the case.

**Comment by hackersintu** [comment]
[]()**RSSING00**

**Comment by adrayv** [comment]
Thanks for the input everyone. Overall, the feedback makes sense, and I’m ok if we close this issue. 

In the future, if we find that either a lot of developers want this feature, or we find a more common use case, can we reopen?

**Comment by rickhanlonii** [comment]
Sure thing @adrayv, and thanks for the suggestion!
