### ISSUE TITLE
Bug: Generated DOM - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by WrathOfZombies** [facebook/react#20845]
I was writing a function that converts one DOM tree into another through some transformation process and I ran into a weird issue where I received the following error:

![image](https://user-images.githubusercontent.com/3244360/108450468-1f03f000-721a-11eb-947f-7fbaa4fcf306.png)

At first, I thought It was an issue with my logic and I created this code sandbox to demonstrate the issue:
https://codesandbox.io/s/react-dom-generation-issue-lgpl4?file=/src/App.js:251-379

In the code sandbox you'll see that when I procedurally generate DOM using the `generateDeepDOM` function, you can go upto large levels of nested trees, limited by the JS max stack (due to recurrsion).

However, if you comment out Example 1 and uncomment Example 2, in which case, I manually hard coded a React tree that contains 300 DOM nodes, I end up getting the error in the image quite easily. The pattern in which I am currently executing my DOM transformation is similar to Example 2 as I end up doing the following:

```jsx
const MyComponent = ({ html }) => {
    const DOM = createReactDOM(html);
    return <div>{ DOM }</div>
}
```

I feel like I am missing something silly or may be this is a bug and hence decided to create an issue here. Any help/direction would be appreciated.

React version: 17.0.1

## Steps To Reproduce
1. Use the code sandbox https://codesandbox.io/s/react-dom-generation-issue-lgpl4?file=/src/App.js
2. Toggle between the definition of `App` under example 1 and example 2 to see different behaviors

## The current behavior
The code works fine when using Example 1 but breaks in Example 2

## The expected behavior
Should either break in both cases or work in both cases

**Comment by rickhanlonii** [comment]
The stack trace seems to indicate that babel is failing to transpile the code:

<img width="503" alt="Screen Shot 2021-02-22 at 10 47 45 PM" src="https://user-images.githubusercontent.com/2440089/108806846-d6796900-7570-11eb-8da2-d9f49cb9286e.png">

Going to close since this is not a React issue.

**Comment by WrathOfZombies** [comment]
Thanks @rickhanlonii. I guess that makes sense. Let me circle back if I have further questions.
