### ISSUE TITLE
Bug: profiler and components tab always appears on the top, after move to bottom

### ISSUE THREAD

**Issue by gdbd** [facebook/react#20852]
In chrome 88 appers ability to move some windows to bottom. When i move profiler or components tab to bottom and restart dev tools, it appears again on the top

React version:

## Steps To Reproduce

1. open dev tools
2. on profiler or components tab click 'move to bottom'
3. close dev tools, open again

## The current behavior

Tabs `profiler` and `components` appers on the top

## The expected behavior

Tabs `profiler` and `components` appers on the bottom

**Comment by bvaughn** [comment]
DevTools extension has no control over where panels appear or if/how Chrome remembers your preferences for their arrangement. I think you're going to have to file this bug against Chrome itself, sorry!
