### ISSUE TITLE
Bug: Issue with React.StrictMode

### ISSUE THREAD

**Issue by siddhant1** [facebook/react#20857]
https://stackoverflow.com/questions/66306497/props-have-different-value-for-randomly-generated-ones-in-parent-react-js

React.StrictMode is changing the behaviour of logs in React App.
Reproducible here :  
https://codesandbox.io/s/elegant-ellis-glhq7?file=/src/index.js (with StrictMode)
https://stackblitz.com/edit/react-c2w4ay?file=src%2FApp.js (without StrictMode)

In both these cases the logs behaviour are different

**Comment by bvaughn** [comment]
This isn't a bug. This was the expected behavior as of PR #18547.

It's been discussed on a few other issues, e.g. #20090 and #17786.

I'm going to close this issue since it doesn't add anything new. Feel free to leave a comment with this use case on one of those other issues though (or the PR).

**Comment by anumthapa** [comment]
Error bug found

**Comment by bvaughn** [comment]
Please don't leave the same comment on multiple issues, @anumthapa.

**Comment by anumthapa** [comment]
Same as well

**Comment by bvaughn** [comment]
@anumthapa This is the 5th meaningless comment you've left on an issue in the last 20 minutes. If it continues, I'll bloc you from leaving more.

**Comment by anumthapa** [comment]
Yes sure 😊

**Comment by anumthapa** [comment]
What kind block, is it a new feature of React

**Comment by gaearon** [comment]
To follow up on this, we've changed the logging behavior in 18 to be more intuitive.
https://github.com/facebook/react/issues/21783#issuecomment-1083412766

**Comment by SrinivasAjimera** [comment]
Impressive blog with lovely information. Really very useful article for us thanks for sharing such a wonderful blog.

[https://espirittech.com/react-js-services/](https://espirittech.com/react-js-services/)
