### ISSUE TITLE
Bug: wrong misleading warning is shown to developers

### ISSUE THREAD

**Issue by kambleaa007** [facebook/react#20858]
React version:
16.7

## Steps To Reproduce

1. Functional component with return in loops with map method
2. check render method of Functional components
3. Go to console to check warning message
3. there is no render method, only return method is present can we tweak message a little bit

Link to code example:

## The current behavior
Wrong misleading warning is shown to user
![image](https://user-images.githubusercontent.com/19818679/108696764-fcc6e680-7527-11eb-9629-8b4ca6e87509.png)

## The expected behavior
Warning should be easily understood by new learners

**Comment by kambleaa007** [comment]
Note: If you are familiar with React Class Components, you may have noticed that a Functional Component is a React Component without render function. Everything defined in the function's body is the render function which returns JSX in the end.

reference from https://www.robinwieruch.de/react-function-component

**Comment by anumthapa** [comment]
In the end it doesn't matter

**Comment by rickhanlonii** [comment]
As @kambleaa007 said, for function components the function component is the render function.
