### ISSUE TITLE
Further document callback to `React.renderComponent`.

### ISSUE THREAD

**Issue by brainkim** [facebook/react#2087]
The callback to React.renderComponent is called with `this` set to the top-level component ([see here](https://github.com/facebook/react/blob/master/src/browser/ui/ReactMount.js#L386)). This isn't documented, but probably should be in case someone relies on this behavior.

**Comment by gaearon** [comment]
This seems like a pretty odd API decision to me and I don’t think we want to further encourage relying on it. We could have deprecated that oddity, but we are also working on a new more powerful top-level API now, and so I think this becomes less valuable now. I would just let it slide.
