### ISSUE TITLE
Bug: React DevTools in Firefox doesn't respect UI font size

### ISSUE THREAD

**Issue by craigkovatch** [facebook/react#20876]
This works fine in Chrome React DevTools, only an issue in the Firefox flavor.

React version: N/A

## Steps To Reproduce

1. Use the React DevTools in Firefox
2. With the Components inspector open, press e.g. CMD-+ or CMD-- to increase/decrease the UI font size

## The current behavior
The rest of the debugger UI reacts (heh) to the change in font size, but the React DevTools font remains tiny. This is a critical accessibility issue -- I have a visual disability and this makes the DevTools extremely hard to use.

![image](https://user-images.githubusercontent.com/10970257/109089753-9926ef80-76c6-11eb-9f1d-b308f4313abb.png)

## The expected behavior
The React DevTools UI also changes font size.

**Comment by bvaughn** [comment]
Huh. This is interesting. Works correctly in Chrome. I wonder why it wouldn't in Firefox.

**Comment by lPadier** [comment]
From what I've been able to find, this appears to be a bug in Firefox:
This is the bug in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1583716

This previous issue (https://github.com/facebook/react/issues/16413) on this repo reports that `ctrl / cmd` + `mousewheel` allows one to zoom, but `ctrl / cmd` `0` or `ctrl / cmd` `+` and `-` are ignored within the panel.

Mousewheel affects the zoom of the entire devtools pane, but the keyboard shortcuts do not extend to the extension pane.

**Comment by craigkovatch** [comment]
Ah, my apologies for the apparent duplicate then. That's quite
unfortunate :(

**Comment by craigkovatch** [comment]
Ah, my apologies for the apparent duplicate then. That's quite
unfortunate :(

**Comment by bvaughn** [comment]
No problem @craigkovatch. I had forgotten about that other issue and I was one of the people commenting on the thread. 😁 

Sounds like it was filed as a Firefox bug (which is where it belongs I think) so I'm going to go ahead and close this issue I guess.
