### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by u-uysal** [facebook/react#20892]
I could not see the exact name of the component in React Dev Tools. Thanks in advance
![Screenshot from 2021-02-26 09-58-04](https://user-images.githubusercontent.com/54946794/109280284-1a8f9680-781b-11eb-96cf-e58700a01a81.png)

.

**Comment by eps1lon** [comment]
Thanks for the report

> I could not see the exact name of the component in React Dev Tools.

Could you clarify which component you mean?

Providing a codesandbox would help a lot. Otherwise we'd have to guess which component you mean and why you couldn't see the exact name.

**Comment by u-uysal** [comment]
I think it's the best thing I can do for you to post this picture. Because we have many components and I guess it makes no sense to send condesanbox connections with only those components.
![Screenshot from 2021-02-26 10-35-06](https://user-images.githubusercontent.com/54946794/109288414-1cf6ee00-7825-11eb-9ce4-3ac1aff17022.png)

**Comment by bvaughn** [comment]
This issue is not actionable unless you're able to provide a runnable code example (like on Code Sandbox).

**Comment by sag-tobias-frey** [comment]
You are probably facing this? https://github.com/facebook/react/issues/17876

**Comment by u-uysal** [comment]
Thanks for your interest. I really appreciate that. @sag-tobias-frey @bvaughn I saw a lot of people have trouble with React.memo and useMemo hook. For example, I could not change this component name.


```
const createCheckComponent = (path: string, equals?: string) =>
  React.memo(
    ({ value }: { value: projects_projects }) => {
      if (!equals) return <CheckContainer>{get(value, path) ? <Check /> : null}</CheckContainer>;
      return <CheckContainer>{get(value, path) === equals ? <Check /> : null}</CheckContainer>;
    },
    (prevProps, nextProps) => {
      return get(prevProps?.value, path) === get(nextProps?.value, path);
    }
  );
```

At React Dev Tools, I see a lot of Anonymous and React. Consumer not the exact name of the component

**Comment by bvaughn** [comment]
The component you are showing there is an anonymous function (`() => {}`) and has no name.

The easiest way for it to show up in DevTools is to use a named function instead:
```js
const createCheckComponent = (path: string, equals?: string) =>
  React.memo(
    function NamedComponent({ value }: { value: projects_projects }) {
      if (!equals)
        return (
          <CheckContainer>{get(value, path) ? <Check /> : null}</CheckContainer>
        );
      return (
        <CheckContainer>
          {get(value, path) === equals ? <Check /> : null}
        </CheckContainer>
      );
    },
    (prevProps, nextProps) => {
      return get(prevProps?.value, path) === get(nextProps?.value, path);
    }
  );
```

You could also assign the anonymous function to a variable first, in which case the browser will assign a name:
```js
const NamedComponent = ({ value }: { value: projects_projects }) => {
  if (!equals)
    return (
      <CheckContainer>{get(value, path) ? <Check /> : null}</CheckContainer>
    );
  return (
    <CheckContainer>
      {get(value, path) === equals ? <Check /> : null}
    </CheckContainer>
  );
};

const createCheckComponent = (path: string, equals?: string) =>
  React.memo(NamedComponent, (prevProps, nextProps) => {
    return get(prevProps?.value, path) === get(nextProps?.value, path);
  });
```

Neither of these is something React DevTools can do though. 😄

**Comment by u-uysal** [comment]
Now it works as expected. Thank you so much @bvaughn  :)

**Comment by bvaughn** [comment]
👍
