### ISSUE TITLE
Bug: current npm react-cache version doesn't work

### ISSUE THREAD

**Issue by jeetiss** [facebook/react#20902]
React version: any after `16.8.0`

#### Steps To Reproduce

1. use react-cache
2. `TypeError Cannot read property 'readContext' of undefined` will be fired

as i understand npm contains obsolete version of `react-cache`
code still contains staff for context reading that was changed here https://github.com/facebook/react/pull/14548

Any chance that react-cache will be updated on npm in near future? 

Link to code example:
https://codesandbox.io/s/react-cache-f6n25

**Comment by bvaughn** [comment]
The currently published version of `react-cache` is very old and flagged as unstable. (Unstable things may break without warning.) In this case, that cache mechanism doesn't reflect our latest thinking about how the Suspense/caching API should work 😄  We'll share more about newer thinking in the coming weeks/months. (You can probably also search PRs and commits if you're curious to get an early hint.)

**Comment by jeetiss** [comment]
@bvaughn thanks for answer
