### ISSUE TITLE
Redundant condition in react-devtools-shared

### ISSUE THREAD

**Issue by nlspnsgen** [facebook/react#20905]
This is not important but it seems that this if statement is superfluous since `typeof` always returns a string. 

https://github.com/facebook/react/blob/553440bd1578ef71982c4a10e2cc8c462f33d9be/packages/react-devtools-shared/src/hydration.js#L246

**Comment by bvaughn** [comment]
Yeah, looks like maybe this got broken during a refactor (ce65df7092ed69b45aa5787b708c1516b2c07427). I think this line should be:
```js
if (typeof data[Symbol.iterator] === 'function') {
```

**Comment by ErikAho** [comment]
Hey, I'm gonna pick this up and try to get a PR through to tidy this :) 

This would be my first issue in this repo. I've given the contribution guidelines a read through, and so will do my best to follow all the CoC and best practices in there.

**Comment by bvaughn** [comment]
This issue is all yours @ErikAho! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by ErikAho** [comment]
Hey! Raised a PR for this.

Couldn't find any unit tests that covered the `dehydrate` function here, and I started to write a few, but thought that it was probably out of scope of this PR. Can definitely create some tests for this function if needed though!
