### ISSUE TITLE
Support for media events

### ISSUE THREAD

**Issue by contra** [facebook/react#2090]
Currently no media events are supported, which makes working with audio or video tags in react a pain in the ass

```js
componentDidMount: function () {
	var audioElement = this.refs.audioObject.getDOMNode();
	audioElement.addEventListener('progress', this.updateProgress);
	audioElement.addEventListener('timeupdate', this.updateProgress);
	audioElement.addEventListener('ended', this.handleMediaEnd);
},
componentWillUnmount: function () {
	var audioElement = this.refs.audioObject.getDOMNode();
	audioElement.removeEventListener('progress', this.updateProgress);
	audioElement.removeEventListener('timeupdate', this.updateProgress);
	audioElement.removeEventListener('ended', this.handleMediaEnd);
}
```

There are also still many missing attributes for audio and video tags. I find it strange that these tags are completely unsupported - they should probably be removed from the list in the documentation to reduce confusion until they are properly supported.

**Comment by jimfb** [comment]
I think we support all these now.  https://facebook.github.io/react/docs/events.html#media-events

**Comment by contra** [comment]
@jimfb I've waited a long time to say this: thank you for adding support for video and audio tags.
