### ISSUE TITLE
Allow mocking component via a provider

### ISSUE THREAD

**Issue by stephenh** [facebook/react#20903]
Right now we can mock components via `jest.mock(...module path...)` but that requires using Jest.

It'd be great to have some sort of built-in `MockedProvider` that had a map of "component declared in JSX" --> "mock to use instead".

And then have this checked only during dev/test builds, not production builds.

**Comment by jordyvandomselaar** [comment]
Hi,

There's plenty of tools that can help with Mocking including Jest and Sinon. Is there a specific case those tools don't handle yet? Even if React had a provider that allows you to mock components, you'd still need one of those tools to actually write your tests.

If you have a specific case that doesn't work as intended yet, I'd be happy to take a look!

**Comment by stephenh** [comment]
Hi @jordyvandomselaar , thanks for the reply! My main ask is to have React provide a stubbing solution that doesn't depend on hacking Node's `require`.

In our codebases, even running a single test is starting to slow down (~200-400ms per test method), and profiling shows a non-trivial amount of time is spent inside of Jest's module `require` abstraction/mocking layer.

Granted, we do just have a lot of `node_modules/` and we'd have to move away from Jest to a test runner that doesn't hijack `require`, but at this point that's not even an option b/c we do rely on Jest's mocking feature for doing what I'm suggesting would be a feature of React itself.

Also, true you mention sinon does component mocking too, but AFAIU it is also based on `require` hacking, which is the thing I'm trying to avoid.

Thanks!

**Comment by jordyvandomselaar** [comment]
No problem =), thanks for taking the time to explain what issues you're running in to!

I personally don't think there's a much better solution than require hijacking to be honest 😅 A solution I'm used to from backend development is dependency injection so you can swap out dependencies but injecting all components would be worse than the 400ms hit per test 😅

I'll admit that I haven't look at how much time is "normal" but 400 ms does seem quite long. Maybe you could try create an issue here? https://github.com/facebook/jest/issues

If you'd be ok with that, I'd like to run your tests, see how long it takes on my system

**Comment by stephenh** [comment]
After thinking about it, I think the `jsxImportSource` could solve this.

Basically instead of the default React/JSX runtime, I could make a `mocked-components/jsx-runtime` that, at least for JSX calls, would mean all `<Foo ...>` would get piped into a `_jsx(Foo, ...)` method that I control, and could do something like "if component === Foo, use MockFoo" within that `_jsx`.

That's not _exactly_ what my original issue was asking for, which as you said is basically a non-`require`-hacking to do dependency injection, but I think its good enough that I'll close this out for now.

Would love to have another set of eyes on our slow tests, but alas they're internal/etc.

Thanks!
