### ISSUE TITLE
Bug: Event handling with portals is broken

### ISSUE THREAD

**Issue by sag-tobias-frey** [facebook/react#20901]
Event handling with portals is broken in the newest version when placing non-react event handlers BETWEEN other react event handlers. With the following setup **outer react event handler with stopPropagation** > **non-react event handler** > **inner react event handler (in portal)**. Doing the same without portals works correctly. 

React version: 17.0.1

### With portal (not working)
1. https://stackblitz.com/edit/ag-grid-react-hello-world-gwuhed?devtoolsheight=33&file=index.js
2. Click on the div
3. Only inner and outer event handlers are called

### Without portal (working)
1. https://stackblitz.com/edit/ag-grid-react-hello-world-gwuhed?devtoolsheight=33&file=index.js
2. Comment out the portal code and comment in the non-portal code (line 24 / 25)
3. Click on the div
4. All three event handlers are triggered

Link to code example: https://stackblitz.com/edit/ag-grid-react-hello-world-gwuhed?devtoolsheight=33&file=index.js

## The current behavior

Non-react event handlers are not called when the initial event is initiated from a portal component and an outer react event handler calls stop propagation. This works correctly without portals.

## The expected behavior

The non-react event handler should also be called when a portal component initiates the event.

**Comment by Quintis1212** [comment]
Hello )  I will try to fix this )

**Comment by Quintis1212** [comment]
Hello ) remove event.stopPropagation(); from your app component in return method and click listener will be work

**Comment by sag-tobias-frey** [comment]
@Quintis1212 but then any event listener higher up the tree will also trigger which is not desired, see

-> https://stackblitz.com/edit/ag-grid-react-hello-world-uor3vf?devtoolsheight=33&file=index.js

**Comment by Quintis1212** [comment]
I see , it seems that createPortal function needs investigating

**Comment by jackyef** [comment]
Possibly related #20074

**Comment by sag-tobias-frey** [comment]
Any updates here? This issue breaks third-party libraries relying on portals and non-react event handling.

**Comment by eps1lon** [comment]
Thanks for the report.

Could you check if this is similar to https://github.com/facebook/react/issues/20074?

**Comment by sag-tobias-frey** [comment]
@eps1lon I don't think the issues are related. I'm not adding an even listener based on click events. The listeners are registered once at the beginning and that's it.

**Comment by sag-tobias-frey** [comment]
bump
