### ISSUE TITLE
Logo Issue

### ISSUE THREAD

**Issue by hash-dev** [facebook/react#20921]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

## The current behavior
I find issue on your logo. It is not user friendly. The color combination also not matching. So please give the responsibility to change your logo.

## The expected behavior
It should be just like nice to facebook logo. I have great concept of your new logo.
![Screenshot (156)](https://user-images.githubusercontent.com/35891377/109767964-6168fc00-7c20-11eb-9af3-54314e9635ae.png)

**Comment by bvaughn** [comment]
Thanks for the suggestion, but we're not looking to change the logo at this time :smile:
