### ISSUE TITLE
Bug: onChange of input field firing twice on Android devices based on special conditions

### ISSUE THREAD

**Issue by bisho1995** [facebook/react#20920]
In mobiles websites (tested on Android) and webviews, the `onChange` method of the input field is getting fired twice if 
1. The value of the input is updated in the store/state after some time interval, for example
```
handleChange = (val) => {
    setTimeout(() => {
      this.setState({ val });
    }, 20);
  };
```
2. The input value has two consecutive same numbers followed by a different number, for example
```
A112
```

So for the case of `A112`, it becomes `A11A112`

React version: Tested on 16.13.0 and 17.0.1

## Steps To Reproduce

Link to demo: https://gblww.csb.app/
Link to code example: https://codesandbox.io/s/input-field-bug-report-gblww
Demo video: https://user-images.githubusercontent.com/12195877/109746806-00c7c800-7bfc-11eb-90ea-0f5b469c5ddd.mp4

## The current behavior
The input field characters are repeating based on the above conditions

## The expected behavior
The input field characters should not repeat.

**Comment by gaearon** [comment]
>The value of the input is updated in the store/state after some time interval

Why are you doing this? Generally you should synchronously update state in the `onChange` event handler. If you don’t, there will be other issues, like losing caret position.

**Comment by bisho1995** [comment]
> I've noticed that if you disable auto-correction in your mobile phone settings you don't have this issues.

@vkatatab yeah, that seems correct.

> Why are you doing this? 

@gaearon This was an old code I inherited. In this case, I can replace the async logic with sync.

>  Generally you should synchronously update state in the `onChange` event handler

Oh, that's interesting. Do you think this should be added in the react docs somewhere about this behavior since it is fundamental to react?
