### ISSUE TITLE
Uncaught Invariant Violation: Hooks can only be called inside the body of a function component

### ISSUE THREAD

**Issue by GauravKatariya** [facebook/react#20935]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
