### ISSUE TITLE
[Reactjs][GeckoDriver] O_CREAT", _c.fs is undefined in ./node_modules/tmp/lib/tmp.js

### ISSUE THREAD

**Issue by c0ncentus** [facebook/react#20930]
https://github.com/SeleniumHQ/selenium/issues/9225 , still have issue ? Something better for alternative ? I just want fetch html ( and fetch is not super easiest solution (cors or not cors .... thats the question .... ) what I want to do)

React version: 17.0.1

## Steps To Reproduce

see selenium documentation for geckodriver install.
fellow this link https://github.com/SeleniumHQ/selenium/issues/9225 

Link to code example: https://github.com/c0ncentus/Selenium_issue 

## The current behavior
crash with this message O_CREAT", _c.fs is undefined in ./node_modules/tmp/lib/tmp.js

## The expected behavior
not crash and do stuff with selenium.

it is React or nodejs issue ?

**Comment by gaearon** [comment]
This has no relation to React.

**Comment by c0ncentus** [comment]
the error come frome because of react ,
i test this algo without React and it's work, 
so it has relation with React ! 

maybe that no concern React's logic and you cannot care this issue but can you tell me what package is concern ? Who will able to fix this issue ? : / no man's land ?
