### ISSUE TITLE
Bug: non-submit buttons inner form invoke submit

### ISSUE THREAD

**Issue by duronfire** [facebook/react#20937]
React version: v17.0.1

Link to code example:

https://codesandbox.io/s/zen-yalow-1khmu?file=/src/index.js

## The current behavior
if you click test button, submit will be invoked.

## The expected behavior
submit should be only invoked, when submit button is clicked.

**Comment by eps1lon** [comment]
Thanks for the reproduction.

The default `type` of a [`<button />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) is `submit`. So `<button />` and `<button type="submit" />` are equivalent.

To prevent this confusion in the future you can use `eslint` with the [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react) plugin which has the [`react/button-has-type` rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md) which warns about omitting the `type` attribute for `<button />`.

Does this clear things up?

**Comment by duronfire** [comment]
Thanks very much for your explaination and your advise!
