### ISSUE TITLE
Forms mishandle submit for Enter key

### ISSUE THREAD

**Issue by tmcwilliam** [facebook/react#2093]
React seems to be executing the first event handler attached to elements in a form rather than executing the onSubmit handler when hitting the Enter key.

jsFiddle: http://jsfiddle.net/tmcwilliam/mufcw3wv/

**Comment by tyrsius** [comment]
@spicyj That seems completely backwards. Is there a way to change that behavior?

**Comment by browniefed** [comment]
@tyrsius you could create a default React button component that has `type="button"` always on it.

**Comment by tyrsius** [comment]
Is there a way to actually override `<button>`, or are you talking about making `<other-button>`? Because the latter isn't really changing the backwards behavior of `<button>`

**Comment by browniefed** [comment]
I'm recommending the `<other-button>` approach. React is focused on matching browser behavior, not modifying it regardless of how backwards it is.

**Comment by hugotox** [comment]
I'm curious why this issue was closed? Seems a legit issue

**Comment by spicyj** [comment]
This is part of how HTML works, not specific to React at all.

**Comment by naoisegolden** [comment]
If a button is not set to `type="button"` it will default to be of `type="submit"`, making it so that you have more than one submit button. Pressing enter will run the first one defined.
