### ISSUE TITLE
Bug: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

### ISSUE THREAD

**Issue by SHARUNJOSEPH** [facebook/react#20949]
app,js
`// ess = require('express');
const express = require('express');
const app = express();
// const bodyParser = require('body-Parser');
var bodyParser = require('body-parser')
const morgan = require('morgan');
const mongoose = require('mongoose');
const cors = require('cors');
require('dotenv/config');

app.use(cors());
app.options('*', cors())
app.use(express.json());

//middleware
app.use(bodyParser.json());
app.use(morgan('tiny'));

//Routes
const categoriesRoutes = require('./routes/categories');
const productsRoutes = require('./routes/products');
const usersRoutes = require('./routes/users');
const ordersRoutes = require('./routes/orders');

const api = process.env.API_URL;

app.use(`${api}/categories`, categoriesRoutes);
app.use(`${api}/products`, productsRoutes);
app.use(`${api}/users`, usersRoutes);
app.use(`${api}/orders`, ordersRoutes);

//Database
mongoose.connect(process.env.CONNECTION_STRING, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    dbName: 'sj-database'
    // dbName: 'eshop-database'
})
.then(()=>{
    console.log('Database Connection is ready...')
})
.catch((err)=> {
    console.log(err);
})

//Server
app.listen(3000, ()=>{

    console.log('server is running http://localhost:3000');
})

`
![Screenshot from 2021-03-07 15-24-25](https://user-images.githubusercontent.com/65939059/110237298-53d5ae00-7f61-11eb-8347-380b3bb7c3ba.png)
![Screenshot from 2021-03-07 15-24-06](https://user-images.githubusercontent.com/65939059/110237299-5506db00-7f61-11eb-966d-f02fa02ed124.png)

**Comment by bvaughn** [comment]
This error seems unrelated to React. Seems like you're missing `process.env.CONNECTION_STRING`

Going to close this issue since this is the React repo
