### ISSUE TITLE
Bug: Events not working in React 17

### ISSUE THREAD

**Issue by adrian-kriegel** [facebook/react#20950]
React version: 17

## Steps To Reproduce

1. clone https://github.com/adrian-kriegel/react-17-event-issue
2. npm i 
3. npm run react16 && npm run dev
4. visit localhost:8080 and enter a text (there should be an alert)
5. npm run react17 && npm run dev
6. visit localhost:8080 and enter a text (there is no alert)

Link to code example: https://github.com/adrian-kriegel/react-17-event-issue

## The current behavior

The onChange event is not triggered in React 17 but is in React 16  using the above setup with webpack and babel. 

## The expected behavior

The event should work in both versions.

**Comment by jordyvandomselaar** [comment]
Can confirm that manually adding event listeners does work, not sure what's going on but it sure is weird.

**Comment by jordyvandomselaar** [comment]
It does work in this sandbox: https://codesandbox.io/s/broken-snow-9v7y7?file=/package.json:166-186

Currently trying to find what part of your setup might be causing this

**Comment by jordyvandomselaar** [comment]
I've even pasted your code into the codesandbox and that does work. I can't seem to find why but it seems to be a problem with this setup specifically.

**Comment by adrian-kriegel** [comment]
@jordyvandomselaar thank you for looking into this. I suspect that it may have to do with @babel/plugin-transform-react-jsx and not react itself as the jsx-transform has been changed in React 17

**Comment by jordyvandomselaar** [comment]
Maybe you could give this a try: https://www.npmjs.com/package/babel-preset-react-app

it's the one codesandbox uses through the react-scripts package!

If you don't know it yet, I can also greatly recommend https://github.com/facebook/create-react-app, it makes setting up new projects a breeze and takes care of weird stuff like this =)

**Comment by adrian-kriegel** [comment]
Thanks, unfortunately, using babel-preset-react-app does not solve the problem. I know about CRA but I'd like to work with as little dependencies as I actually require.

**Comment by jordyvandomselaar** [comment]
Maybe you could try if `babel-preset-react-app` works though, that way you don't need the entire CRA tooling.

**Comment by gaearon** [comment]
OK so this is a pretty interesting case.

You accidentally **run your application code twice**. This is because your `<script>` tag is in the HTML, but the webpack plugin you're using *also* adds the same `<script>` tag automatically:

```js
  <script defer src="bundle.js"></script>
</head>
<body>
  <div id="root"></div>
  <script src="bundle.js"></script>
```

You end up with two bundled copies of React, both of which try to manage the same exact DOM node. This is not supported and leads to weird issues like this. I'm a bit surprised we don't warn for this.

Removing the second `<script>` tag fixes the issue.
