### ISSUE TITLE
Bug: Create-react-app error using bash and tried powershell and more

### ISSUE THREAD

**Issue by potasium56** [facebook/react#20969]
I decided to try and learn react and was following the instructions listed here https://reactjs.org/docs/create-a-new-react-app.html. So I made a folder opened it in vscode, went into my bash terminal and ran the below code as instructed. 

npx create-react-app my-app // But i used demo 

once completed then cd'ed into my demo folder
cd my-app

and then typed npm start and this is where I get this bug
npm start

error: 

```
PersonalInfo@DESKTOP-C0M5IPI MINGW64 /f/1.Web Development/Tutorials&Courses/Devslopes/learn-react/demo-app (master)
$ npm start

> demo-app@0.1.0 start
> react-scripts start

'Courses\Devslopes\learn-react\demo-app\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'F:\1.Web Development\react-scripts\bin\react-scripts.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Now I tried, running npm install and then npm start and still same error. I have tried different folder names and locations ect, i'm starting to think this is a bug with bash because prior to me wanting to learn react was working with node and express and databases(mongodb) all day today.

I have node.js installed globally and i'm sure the npx create-react-app installs node locally to the folder. I'm at a loss here, even went inside discord and asked for help in various channels and people also don't know whats going on here. 

Upon further inspection it seems that inside the error its for some reason trying to locate the node module from this directory which is weird F:\1.Web Development\react-scripts\bin\react-scripts.js because when I ran npx create-react-app demo in this directory /f/1.Web Development/Tutorials&Courses/Devslopes/learn-react/ and then cd into demo. and ran npm start and this gives me the above error. 

React version: what ever version get loaded with npx create-react-app 

## Steps To Reproduce

I just created a main folder inside my other folders called learn-react opened that in visual code and then followed the guide for npx create-react-app demo and then followed the next instructions once i got to the npm start or npm run start tried both commands and it results is said error. 

I tried switching terminal and used default powershell in vscode and still same error. I'm not sure what happened cause like i said above was using npm to install packages all day today and then when i wanted to learn react this is happening to me...

Link to code example:

google drive video: https://drive.google.com/file/d/1bYmT--iQ49ymJ2co0S6YGxBksmVXvCbL/view?usp=sharing

**Comment by eps1lon** [comment]
Thanks for the report. 

You want to report this to https://github.com/facebook/create-react-app/issues instead since the current repository is only concerned with React libraries not create-react-app.

Be sure to include more information about your environment e.g. `node -v`, `npm -v` and `npx -v`.

**Comment by eps1lon** [comment]
> Also, do i need to repost this into the correct place or did you do that for me?

You have to do that. 

> Yeah, sorry very new to github also if you watched the video i linked at the button of my post it shows node 

I was asking about the versions. This information should be readily available not only visible in a short time frame in a video.
