### ISSUE TITLE
Bug: calling setState during render should eliminate the state initialization of current render

### ISSUE THREAD

**Issue by csr632** [facebook/react#20972]
If I call `setState` during render, I expect **the influence of current render to be completely cleaned up**.
But in reality, React doesn't destroy the "state initialization" in the first render and re-initialize those states. It keeps the "state initialization" of the first render.

```js
  const [s1, set1] = useState(1);

  if (s1 === 1) {
    // the influence of s1 === 1 should be completely eliminated
    // just like this render never happens
    // just like s1 is always 2
    set1(2);
  }

  const [s2] = useState(() => {
    // this init function should be called twice
    // the final result of s2 should be 2
    console.log("init s2 called", s1);
    return s1;
  });
```

But with current React, the final result of s2 is 1.

React version: 17.0.1

## Steps To Reproduce

Link to code example:

https://codesandbox.io/s/setstate-during-render-8z94q?file=/src/App.tsx

## The current behavior

`s2` is only initialized once, with the state of the **first render**. The final result of s2 is 1.

```js
  const [s1, set1] = useState(1);

  if (s1 === 1) {
    set1(2);
  }

  const [s2] = useState(() => {
    // this init function is only called once
   // with s1 === 1
    console.log("init s2 called", s1);
    return s1;
  });

```

## The expected behavior

I expect "calling setState within render" to **completely discard the first render**:
`s2` is initialized twice. The initialization of the **first render** should be discard. The final result of s2 should be 2.

```js
  const [s1, set1] = useState(1);

  if (s1 === 1) {
    // the influence of s1 === 1 should be completely eliminated
    // just like this render never happens
    // just like s1 is always 2
    set1(2);
  }

  const [s2] = useState(() => {
    // this init function should be called twice
   // the final result of s2 should be 2
    console.log("init s2 called", s1);
    return s1;
  });
```

**Comment by csr632** [comment]
Hmm, if "the influence of first render should completely cleaned up", does "other setState" counted as "influence"? Should the be discarded too?

```js
  const [s1, set1] = useState(1);
  const [s2, set2] = useState(1);

  if (s1 === 1) {
    set1(2);
    // setState is called during render! Let's pretend this render never happened!
    // But should we discard the following setState?
    set2(2);
  }
```

**Comment by markerikson** [comment]
I think this is a misunderstanding of how React rendering behavior works.

Setting state while rendering doesn't eliminate the fact that the first render happened.  All it does is queue an additional render pass with the new state to be updated.  So, no, there's "influence of a current render cleanup" that's going to happen, and this is definitely not a bug - this is normal and intended behavior.

You might want to read my post [A (Mostly) Complete Guide to React Rendering Behavior](https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/) to get a better understanding of how React handles this sort of thing in general.

**Comment by gaearon** [comment]
I think I see the point you’re making, but overall calling `setState` *during* render is a rather exotic pattern meant to address a sine use case — deriving state from a *change* in props. For example, driving `scrollDirection` from a difference in last two values of an `offsetY` prop. Note the emphasis on “change”. I don’t really know what you’re aiming to do by setting state during the *initial* render. This doesn’t seem like a legit pattern and we might even want to outlaw it in the future. Don’t use it if you’re not specifically reacting to a change in props.
