### ISSUE TITLE
Bug: Calling setstate in a callback ref causes node to be set to null 

### ISSUE THREAD

**Issue by subhero24** [facebook/react#20971]
I have a very small example sandbox here: https://codesandbox.io/s/long-sunset-ofr4b?file=/src/App.js

This example uses a callback ref to get the value of the dom node.
When using setState inside the callback ref function, the callback ref is called twice more, once with null and once with the actual dom node again. As if the child remounted.

React version: 17.0.1

## Steps To Reproduce

Uncomment the setState line in the sandbox example and see two extraneously logs in console of the node value.

## The expected behavior

I would not expect the node value to ever become null

**Comment by eps1lon** [comment]
Thanks for the report.

Ref callbacks are called every time:
1. the instance changes 
2. the ref callback changes

You're observing the second case. 

It's not clear what your real-world use-case is. For your example you can fix this by memoizing the `callbackRef`:

```diff
-function callbackRef(node) {
+const callbackRef = useCallback(function callbackRef(node) {
  console.log(node);
  setState(1);
-}
+}, []); 
```

Does this clarify the observed behavior?

**Comment by subhero24** [comment]
I did not know it was called again when the ref callback changed. That explains it. Thanks for your reply!
