### ISSUE TITLE
keep empty string for select option value 

### ISSUE THREAD

**Issue by tomconnors** [facebook/react#2098]
When I provide an empty string for the "value" attribute to an `<option>` (using plain js, no jsx), the generated markup drops the "value" attribute entirely. I think the value attribute should not be dropped when it is explicitly provided. My use case:

```
<option value="">none</option>
```

and in the select's `onChange`

```
myModel.set("someProp", event.target.value); // value should be "", not "none"
```

**Comment by taarimalta** [comment]
I am getting the same issue. I have keys set on all options

`                                <select className="form-control" id="sel-fruit" defaultValue="">
                                    <option key="EMPTY_KEY" value="">-- Select --</option>
                                    <option key="app" value="app">Apple</option>
                                </select> `

Later from console when i do

`$("#sel-fruit").val()`

I get -- Select --

**Comment by spicyj** [comment]
@taarimalta This was a bug in the RCs; will be fixed in 15 final when it comes out this week.
