### ISSUE TITLE
Bug: Error message prints "Warning: ..." instead of "Error: ..."

### ISSUE THREAD

**Issue by kokushkin** [facebook/react#20981]
React version:

## Steps To Reproduce

1. Go at https://codesandbox.io/s/warning-issue-formik-v2-tutorial-start-forked-lwtxx?file=/src/index.js and type something in the Tool ID field. This reproduces one of these errors-warnings..
2. Take a look in the console and you will see an Error but.. a Warning, or Error (in fact it's considered to be an error)... , which is simply confusing. 
![image](https://user-images.githubusercontent.com/9853656/110771670-6f8fcb80-8263-11eb-9f85-60026f9c52b0.png)

## The current behavior
prints: "Warning: A component is changing an uncontrolled..."

## The expected behavior
should be "Error: A component is changing an uncontrolled..." here and in all such cases.

I've initially created #20912 (everything ok there) , but now I've dived deeper in this, I've read this #16753 and understand the concept. So now, the solution (that would be in alignment with #16753 by the way) would be simply to make minor changes here https://github.com/facebook/react/blob/master/packages/shared/consoleWithStackDev.js
![Expression-4 (1)](https://user-images.githubusercontent.com/9853656/110778391-f5fbdb80-826a-11eb-810a-1bcae85ace18.jpg)

and then run test and update  the red tests. Also, maybe in the consoleWithStackDev.www.js .. 

By the way, what is this about? (RN?))
> // Careful: RN currently depends on this prefix

Maybe this is why it wasn't done before?) 

Seems like a very obvious thing and I surprised nobody raised an issue (or maybe did but I could not find it).

Anything opposing these changes?

**Comment by AmeerAsif777** [comment]
Actually, it should be a warning. Why are you saying it should be an error?

**Comment by kokushkin** [comment]
> Actually, it should be a warning. Why are you saying it should be an error?

Hi! Because in the browser it has an error log level (red color), meaning it was printed with console.error (not with console.warn). So, as it has been chosen to be an error (as you can see from the code base) therefore it seems like a good idea to stick with this and don't print "warning" in the error which leads to the inconsistent experience for everybody who looks in the browser's console.

Well, it might be a warning as well. In this case, it should be printed with console.warn . But they're  more messages like this. So the thing I'm suggesting would bring consistency between messages' log levels and their content.

**Comment by abhijit-hota** [comment]
@kokushkin From the [contribution guide](https://reactjs.org/docs/codebase-overview.html#warnings-and-invariants)
> The React codebase uses `console.error` to display warnings:

**Comment by kokushkin** [comment]
> @kokushkin From the [contribution guide](https://reactjs.org/docs/codebase-overview.html#warnings-and-invariants)
> 
> > The React codebase uses `console.error` to display warnings:
> > ```js
> > if (__DEV__) {
> >  console.error('Something is wrong.');
> > }
> > ```

Not entirely true.
In fact the React codebase uses both console.error and console.warn functions.
`// In DEV, calls to console.warn and console.error get replaced
// by calls to these methods by a Babel plugin.
//
// In PROD (or in packages without access to React internals),
// they are left as they are instead.

export function warn(format, ...args) {
  if (__DEV__) {
    printWarning('warn', format, args);
  }
}

export function error(format, ...args) {
  if (__DEV__) {
    printWarning('error', format, args);
  }
}
`
The idea was to make this error-warnings better ( https://github.com/facebook/react/issues/16753 ) but it just hasn't been entirely finished so now both warn and error print "Warning".
@abhijit-hota 


By the way what does it mean?
`// In PROD (or in packages without access to React internals),
// they are left as they are instead.`
Should be
`// In PROD (or in packages without access to React internals),
// they are left empty and doing nothing`
?

**Comment by crushingCodes** [comment]
I always wonder why warnings are red too. It makes it harder to find uncaught exceptions. Sometimes 3rd party libraries cause react warnings and make it hard to find the issues you have control over. 
It would be nice if anything caught would just show up as a yellow warning.

**Comment by AlanBlanchet** [comment]
I don't know where the idea that a warning should be red came from.
But in every development that exists out there I find it pretty clear that
`red = error`, `yellow = warning` and `nothing = log/info/print`.
For me it's really hard juste seing the color `red` with the text `warning`.

Heres a little image to show you how I feel when I see this.
![image](https://user-images.githubusercontent.com/22567306/206197119-f5dd9f6b-5d40-43c6-9883-caff3077470d.png)
