### ISSUE TITLE
Bug: React appends element twice when using `document.doby.appendChild()`

### ISSUE THREAD

**Issue by realJustinLee** [facebook/react#20988]
React appends element twice when using `document.doby.appendChild()`

React version: 17.0.1

## Steps To Reproduce

1. Create a sample app with nix with the following code:
    ```
    npx create-react-app test 
    ```
2. Add a child element to the document with  `document.doby.appendChild()` like demonstrated in the code example below.
3. Now save and run the app with code:
    ```
    npm start
    ```
4. Now you gonna see 2 divs  called `Hello` with a 'Hello Test' innerHtml In the Elements tag of your Chrome DevTools
![Screen Shot 2021-03-12 at 13 49 21](https://user-images.githubusercontent.com/17794470/110898229-cc5db580-8339-11eb-9bf8-bcd5fcade783.png)

## Code example:
``` 
    import React, {Component} from 'react';
    import logo from './logo.svg';
    import './App.css';
    
    class App extends Component {
    
        constructor(props) {
            super(props);
    
            let link = document.createElement("div");
            link.className = "Hello";
            link.innerHTML = "Hello Test";
            document.body.appendChild(link);
        }
    
    
        render() {
            return (
                <div className="App">
                    <header className="App-header">
                        <img src={logo} className="App-logo" alt="logo"/>
                        <p>
                            Edit <code>src/App.js</code> and save to reload.
                        </p>
                        <a
                            className="App-link"
                            href="https://reactjs.org"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            Learn React
                        </a>
                    </header>
                </div>
            );
        }
    }
    
    export default App;

 ```

## The current behavior
Tow `<div class="Hello">Hello Test</div>`s in the HTML

## The expected behavior
Only one `<div class="Hello">Hello Test</div>` in the HTML

**Comment by eps1lon** [comment]
Thanks for the report.

You're calling `document.body.appendChild(link);` in the constructor of a class component. The constructor must not have any side-effects. Rendering in StrictMode will cause React to call the constructor twice to detect these side-effects. More information about StrictMode behavior can be found in https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects. You probably want to use `componentDidMount` instead.
