### ISSUE TITLE
Bug: useMemo exec twice in StrictMode,But console.log only exec once,console.debug exec twice

### ISSUE THREAD

**Issue by cqh963852** [facebook/react#20982]
React version:17.0.1

## Steps To Reproduce

1. Wrap app in StrictMode
2. Do a function in useMemo

Link to code example:

https://codesandbox.io/s/vigilant-tree-igscd

## The current behavior
The console.log in setSlot only exec once.
![image](https://user-images.githubusercontent.com/17702287/110825827-6a686600-82cf-11eb-976e-6e09de5bd615.png)

## The expected behavior
Exec the console.log twice in setSlot funciton.

**Comment by bvaughn** [comment]
Related to #20367 and #20835 ([this comment](https://github.com/facebook/react/issues/20835#issuecomment-781393974))

tl;dr Executing code twice in DEV is one of the things `StrictMode` does to [detect side effects](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects). React temporarily overrides console APIs like log before the second invocation to avoid double spamming the console.

This is a bit of a controversial decision but it seemed like the better of the two options.
