### ISSUE TITLE
Bug: preventDefault on `onTouchMove` is not preventing scrolling on iOS

### ISSUE THREAD

**Issue by MadsHornbeck** [facebook/react#20999]
Adding a `onTouchMove` handler that calls `preventDefault` is expected to stop scrolling on iOS but doesn't.
If the same is done by manually adding the event using a ref and `addEventListener` has the expected behavior of not scrolling the page.

React version: 17.0.1
iOS safari version: 14.4

## Steps To Reproduce

1. Add an `onTouchMove` event handler to a div.
2. Call the the `event.preventDefault` prototype function.
3. Touching in the div on iOS safari (v14.4) is not expected to scroll the page, but does.

Link to code example: https://codesandbox.io/s/lucid-babbage-m4g4j

## The current behavior
You can scroll the page on iOS when preventDefault is called.

## The expected behavior
Page should not scroll when preventDefault is called.

## Workaround
1. Add a ref to a div.
2. Use `addEventListener` to attach an event handler using the ref.
3. Call `event.preventDefault` in the event handler.
4. Touching the div does not scroll the page using this method, as expected.

**Comment by eps1lon** [comment]
Thanks for the report.

`onTouchMove` is passive by default i.e. `cancelable` is `false`. This is intended behavior to follow Chrome's interventation with scroll/touch events on the `document`.

For more context, check out https://github.com/facebook/react/issues/19651
