### ISSUE TITLE
Bug: performing input.select() in IE11 throws a React error

### ISSUE THREAD

**Issue by Dremora** [facebook/react#20990]
The example below is extracted from the app with a spreadsheet-like UI, where cells become editable upon focus (can be achieved either by tabbing into the cells or clicking). The text in such cell immediately becomes selected.

The bug occurs only in IE11, as the user navigates from one such cell to another by clicking.
Likely related to https://github.com/facebook/react/pull/19664.

React version: 17.0.1

## Steps To Reproduce

1. Clone https://github.com/Dremora/react-i11-input-focus-bug
2. Install dependencies (`yarn`) and start the app (`yarn start`)
3. Open http://localhost:3000 in IE11
4. Click on the text saying `hello`
5. Click on the text saying `world`

Link to code example: https://github.com/Dremora/react-i11-input-focus-bug/blob/master/src/App.js

## The current behavior
`Unspecified error` gets logged to the console, followed a few other errors, one of them being `Should not already be working` error. As this is a React internals error, application stops working. Nothing gets thrown in the user-land code.

## The expected behavior
`world` text gets selected.

**Comment by eps1lon** [comment]
Codesandbox: https://codesandbox.io/s/serene-kapitsa-mw16s
Deploy for IE 11 testing: https://csb-mw16s.netlify.app/

Invariant is https://reactjs.org/docs/error-decoder.html?invariant=327

Console log when replaying:
```
SCRIPT16389: Unspecified error.
react-dom.production.min.js (123,157)
SCRIPT5022: Minified React error #327; visit https://reactjs.org/docs/error-decoder.html?invariant=327 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
scheduler.production.min.js (12,397)
```
The UI does not crash i.e. unmount.

**Comment by priyanshuSharma-WebDev** [comment]
Hey! @Dremora, Is this bug still reproduce, If yes I want to work on this issue can you assign it to me?

**Comment by Dremora** [comment]
Hey @priyanshuSharma-WebDev, the bug is still there, to the best of my knowledge. Feel free to pick it up, but I don't have permissions to assign anyone to this issue. This is likely reserved to React contributors.
