### ISSUE TITLE
Bug: e.stopPropagation() not working with OnMouseOut.

### ISSUE THREAD

**Issue by codeslon** [facebook/react#21006]
notice! it seems that if I change to onMouseLeave it's working fine.
<div onMouseEnter={(e)=>{
    setIsHide(false)
    {!isHide && <div className="tooltip" onMouseOut={(e)=>{
                e.stopPropagation();
                setIsHide(true);
     }}>
        <div style={{padding:"17px", background:"blue"}}>&nbsp;</div>
        something
     </div>}}
</div>

**Comment by gaearon** [comment]
There are hardly any details here. I don't think this is actionable.
