### ISSUE TITLE
Bug: firebase and service-workers.js caching

### ISSUE THREAD

**Issue by devolab** [facebook/react#21007]
Hi, 

I have caching issue when using Firebase Hosting and React service-workers.js.
I know this problem has been previously reported here: https://github.com/facebook/create-react-app/issues/2440 , but we are in 2021 and the solution suggested is not working.

The solution is to modify the firebase.json file with this snippet:
````
{
  "hosting": {
    "headers": [
      { "source":"/service-worker.js", "headers": [{"key": "Cache-Control", "value": "no-cache"}] }
    ]
  }
}
````

This is my firebase.json file:
````
{

  "hosting": {
    "site": "abc123",
    "public": "build",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "headers": [
      {"source": "/service-worker.js", "headers": [{"key": "Cache-Control", "value": "no-cache"}]}
    ]
  }
}

````

React version: "react": "^17.0.1"

## Steps To Reproduce
1. "create react app"
2. "install and setup firebase hosting"
3. yarn build
4. firebase deploy -P default
5. Check deployment worked
6. Modify an image on your project
7. rm -rf build
8. yarn build
9. firebase deploy -P default
10. open your URL

## The current behavior
The replaced image doesn't show up. Old one is displayed

## The expected behavior
The website should display the new image. To do that, I need to hit refresh on the browser.

**Comment by bvaughn** [comment]
The correct place to report this issue, as mentioned in the description of this bug report, is  https://github.com/facebook/create-react-app/

Please file this issue there. This repo is for React itself, not create-react-app.

**Comment by devolab** [comment]
@bvaughn thank you.
New issue, if anyone is interested, is here: https://github.com/facebook/create-react-app/issues/10686
