### ISSUE TITLE
Bug: Can't use TypeScript generics with React.memo

### ISSUE THREAD

**Issue by nicholaschiang** [facebook/react#21003]
React version: 17.0.1

## Steps To Reproduce

1. Clone [this repro](https://github.com/nicholaschiang/react-memo-types): 
```
git clone https://github.com/nicholaschiang/react-memo-types
```
2. Install dependencies: 
```
yarn install
```
3. Start the development server:
```
yarn start
```
4. See error:
```
TypeScript error in /react-memo-types/src/App.tsx(33,41):
Type '(value: string) => void' is not assignable to type '(value: unknown) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'unknown' is not assignable to type 'string'.  TS2322

    31 | }: ComponentProps): JSX.Element {
    32 |   return (
  > 33 |     <GenericComponentMemo value={value} onChange={onChange} />
       |                                         ^
    34 |   );
    35 | }
    36 |
```

Link to code example: https://github.com/nicholaschiang/react-memo-types/blob/master/src/App.tsx#L28

```tsx
// App.tsx

interface GenericComponentProps<T> {
  value: T;
  onChange: (value: T) => void;
}

function GenericComponent<T>({ 
  value, 
  onChange 
}: GenericComponentProps<T>): JSX.Element {
  return (
    <p>Value: {value}</p>
  );
}

// Using `React.memo` removes TypeScript's ability to detect the `T` generic. 
const GenericComponentMemo = React.memo(GenericComponent);

// This component specifies `T` as a `string`.
type ComponentProps = GenericComponentProps<string>;

// Replace `<GenericComponentMemo />` with `<GenericComponent />` and you'll
// notice that it compiles again because TypeScript is able to detect that the
// generic type parameter `T` is `string` in this scenario.
function Component({ 
  value,
  onChange
}: ComponentProps): JSX.Element {
  return (
    <GenericComponentMemo value={value} onChange={onChange} />
  );
}
```

## The current behavior

The [current React types](https://npmjs.com/package/@types/react) don't support TypeScript generics when wrapping a functional component in `React.memo`. This results in a TypeScript compilation error when TypeScript falls back to `unknown` for the generic type and cannot detect the used generic.

## The expected behavior

The types for `React.memo` should support generics. There should be no compilation error in that repro.

**Comment by bvaughn** [comment]
The React team does not maintain TypeScript type definitions. Those are maintained here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react

I suggest filing an issue in the DefinitelyTyped repo 👍🏼
