### ISSUE TITLE
Bug: Anchors tags are not working in chromium browser

### ISSUE THREAD

**Issue by Xdev200** [facebook/react#21000]
https://reactjs.org/docs/hooks-reference.html
Anchor Tags are not working in the above link in the chromium-browser. 
But, It only works when we open the developer tool.

![react org anchor tag issue](https://user-images.githubusercontent.com/65798140/111053768-a8f74f80-848c-11eb-89a2-c7927e569051.gif)

## Steps To Reproduce

1. open the link - https://reactjs.org/docs/hooks-reference.html

**Comment by bvaughn** [comment]
Hm. This doesn't repro for me, but...worth someone looking into. 😄

That being said, please file this on the docs repo: https://github.com/reactjs/reactjs.org
