### ISSUE TITLE
Bug: HTMLSelectElement.value doesn't update to defaultValue on form reset

### ISSUE THREAD

**Issue by cl8n** [facebook/react#21025]
For uncontrolled inputs, [docs here](https://github.com/facebook/react/blob/master/fixtures/dom/src/components/fixtures/text-inputs/README.md#form-reset-events) say that `reset()`ing a form should change all inputs' `value`s to `defaultValue`. This doesn't seem to be working for `HTMLSelectElement`.

React version: 17.0.1

## Steps To Reproduce

1. Set a `defaultValue` on \<select\> to some variable that can be changed later
2. Pick a different option
3. Change the value of variable from step 1
4. `reset()` the form containing the \<select\>

Link to code example: <https://codesandbox.io/s/cocky-curran-365wd?file=/src/App.js>

## The current behavior

The \<select\>'s value resets to its *initial* `defaultValue`, not the updated one.

In my codesandbox.io example you can see that it always resets to "Zero", regardless of how you update the `defaultValue`.

## The expected behavior

The \<select\>'s value should update to its current `defaultValue`.

**Comment by BenjaminCharpentier** [comment]
This doesn't seem like a bug to me, reset() simply revert the inputs value to the current DefaultValue, which is set only on the mounting phase

As you can see here : https://codesandbox.io/s/crimson-frost-ztcwi?file=/src/App.js
If I add a key associated with defaultValue which force the component to remount, the value is set correctly.

**Comment by cl8n** [comment]
I don't think that's correct. other form inputs do have the behavior I expected---for sake of example I have a \<select\> side-by-side with an \<input\> here: https://codesandbox.io/s/new-sky-www6t?file=/src/App.js

I'll be using your method as a workaround for now though, thank you
