### ISSUE TITLE
Bug: aria-description is a valid ARIA property

### ISSUE THREAD

**Issue by nordfjord** [facebook/react#21035]
React version: 16.x

## Steps To Reproduce

1. `render(<div aria-description="Description" />)`

Link to code example:
[flems link](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3AAgjYF4AOiAwAHUcIB8gtN24yWAeg6dJlEHBixqxCPQSIQARkQAmEAF8K6bLkP4AVgip0GTYngBKMDDoAiAPIAsvgATkxsMKEAFOxc3BihEBgAtJFw1EmiuvRCIH7wmRDZemjC3IqSFAniAJTqdFii0FF4AEYYbVqW1iCYOHj41HDONPSMzIaWALpUUBBoANYGqH22eOG+xPiRnFq0ojgMjqMArqHkhiTEonCIioqnaKKLAOZDtFiKmzoAAkYAdnwAAZ8EZHlg2N8fDodjA9lADkdtk51MQAJ6iOwaIrZHo2AaGH7ENKfOEIpHuE7qc6XEDXW73R7PN4fL7E0lYf5A0Hg06Q6FbTnk-aHKmoqgYrF4DJZDwWaYWIA)

## The current behavior
```
warning: Invalid aria prop `aria-description` on <div> tag
```

## The expected behavior
Nothing. It's part of WAI-ARIA 1.3

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Annotations

**Comment by eps1lon** [comment]
I guess the question is what React considers a "valid" aria prop:
1. a specific version (range) of Aria
1. a version with a [particular state](https://www.w3.org/2004/02/Process-20040205/tr.html#:~:text=A%20Working%20Draft%20is%20a,public%2C%20and%20other%20technical%20organizations.&text=A%20Candidate%20Recommendation%20is%20a,the%20Working%20Group's%20technical%20requirements.) (WR,CR,PR,REC)
1. what spec editors consider the ["stable" version](https://raw.githack.com/w3c/aria/stable/index.html)
1. any aria prop that ever existed

**Comment by itudoradrian** [comment]
Yeah, it seems they've added support for this fairly recently.

https://github.com/w3c/aria/issues/891

**Comment by nordfjord** [comment]
We might also ask: “Why is react telling me what is and isn’t a valid aria attribute.” 

React isn’t the source of truth for that information.

It sounds like the job of a linter rather than something react should warn about.

**Comment by itudoradrian** [comment]
I think it might be from a compiler.

**Comment by nordfjord** [comment]
It's from here: https://github.com/facebook/react/blob/b4f119cdf1defe2437e00022f670c6ef818cd43f/packages/react-dom/src/shared/validAriaProperties.js

**Comment by gaearon** [comment]
>We might also ask: “Why is react telling me what is and isn’t a valid aria attribute.”

The reason is that they're often misspelled so on the whole it's beneficial to warn for unknown ones. I'll merge the PR.

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/22142. Will appear in 18.
