### ISSUE TITLE
Bug: context value is not updated with useContext hook but it is with a Consumer component

### ISSUE THREAD

**Issue by tsdexter** [facebook/react#21030]
React version: 17.0.1 

## Steps To Reproduce

1. create context
2. wrap app in `Context.Provider` with a value from a `useState` hook
3. get the context value with `useContext` hook
4. get the context value with a `Context.Consumer`
5. update the value from the `useState` hook that is passed into the `Context.Provider` `value` prop
6. The `useContext` value is not updated whereas the `Context.Consumer` value is

Link to code example: https://codesandbox.io/s/kind-morse-3rh34?file=/src/App.js 

## The current behavior
Clicking the button "Update TestContext Value" only updates the value from `Context.Consumer`. The value of the `useContext` call is always the initial value
![image](https://user-images.githubusercontent.com/4126987/111577767-51f1c300-8789-11eb-8e23-fa0652ad561c.png)

## The expected behavior
Clicking the button "Update TestContext Value" should update the value of both the `useContext` call and the value from `Context.Consumer` 

## Related
https://github.com/facebook/react/issues/14759

**Comment by eps1lon** [comment]
Thanks for the reproduction.

The `useContext` usage is not inside the Provider. I've unwrapped the code to illustrate what React is "seeing":

```jsx
function Component() {
  const valueUseContext = useContext(Context);
  const [state, setState] = useState(0);

  return (
    <Context.Provider value={state}>
      value from useContext: {valueUseContext}
      <Context.Consumer>{(valueConsumer) => {
        return <div>value from .Consumer: {valueConsumer}</div>
      }}</Context.Consumer>
    </Context.Provider>
  );
}
```

The `useContext` hook needs to be called "inside" the provider tree:
```diff
+function ComponentUsingUseContext() {
+  const valueUseContext = useContext(Context);
+  
+  return <div>value from useContext: {valueUseContext}</div>
+}

function Component() {
- const valueUseContext = useContext(Context);
  const [state, setState] = useState(0);

  return (
    <Context.Provider value={state}>
-     value from useContext: {valueUseContext}
+     <ComponentUsingUseContext />
      <Context.Consumer>{(valueConsumer) => {
        return <div>value from .Consumer: {valueConsumer}</div>
      }}</Context.Consumer>
    </Context.Provider>
  );
}
```

Does this clear things up?

**Comment by tsdexter** [comment]
🙄 I knew it was something simple...don't code past midnight, I suppose. I've fixed it in the repro here: https://codesandbox.io/s/lucid-tdd-cz6pn?file=/src/App.js in case others come across this
