### ISSUE TITLE
React App Show me this Error

### ISSUE THREAD

**Issue by sureshjangid** [facebook/react#21036]
![Screenshot (234)](https://user-images.githubusercontent.com/75411144/111806067-9bf8b700-88f7-11eb-8c82-cf96ba48aea4.png)
![Screenshot (233)](https://user-images.githubusercontent.com/75411144/111806017-90a58b80-88f7-11eb-8931-6ac4c0da7221.png)
![Screenshot (235)](https://user-images.githubusercontent.com/75411144/111806390-ed08ab00-88f7-11eb-81bf-69536ba1df64.png)

**Comment by sureshjangid** [comment]
![Uploading Screenshot (235).png…]()

**Comment by bvaughn** [comment]
Screenshots of code (files) aren't really a repro. Please share actual runnable code.

**Comment by vkurchatkin** [comment]
There shouldn't be a newline after `return`, `(` should be on the same line

**Comment by sureshjangid** [comment]
> There shouldn't be a newline after `return`, `(` should be on the same line

Thank You So much, sir, For your Response. Now the code is working.
