### ISSUE TITLE
Bug: Internal state not resetting if a component replaces itself in the DOM Tree

### ISSUE THREAD

**Issue by DaniAkash** [facebook/react#21045]
React version: 17.0.1

## Steps To Reproduce

1. I have a Tab implementation where two tabs have a dropdown (using react select / downshift - issue appears on both).
2. If I have two dropdown components replace each other on switching tabs, the internal state is not getting reset for the components. The dropdown of the second tab has the value selected by dropdown in the first tab!
3. To workaround this issue, I have to modify the DOM (adding additional div) to let React know that the component has changed in the Tree

Link to code example: https://codesandbox.io/s/react-tab-switch-bug-w48n1?file=/src/App.tsx

## The current behavior

If I select an option in the first tab, & click on the switch button, the dropdown selected value persists

## The expected behavior

The dropdown should reset just like in the second section

**Comment by vkurchatkin** [comment]
How would react know that it is a different tab?

```
activeTab ? <AsyncSelector /> : <AsyncSelector />
```

This code is just the same as writing `<AsyncSelector />`

**Comment by bvaughn** [comment]
The solution for this is to use a different `key`, e.g.
```js
{activeTab ? <AsyncSelector key={1} /> : <AsyncSelector key={2} />}
```
Otherwise these two components are exactly the same to React :smile:

**Comment by DaniAkash** [comment]
@bvaughn thanks for the solution. I have implemented a simple use case here. We ran into a much bigger issue when we were using components that had the same Tree structure in different tabs. Would be nice if this is documented in the key section 👍🏽
