### ISSUE TITLE
Bug: React Refresh throws error, only on macOS

### ISSUE THREAD

**Issue by Slapbox** [facebook/react#21047]
React Refresh throws error, only on macOS. I originally reported that on the React-Refresh-Webpack-Plugin, but @pmmmwh noticed the error actually seems to be coming from React Refresh itself. https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/333

**React version:** 17.0.1

**Environment:** macOS 10.13.x - Electron@11.3.x - Webpack@5.x

## Steps To Reproduce

1. Configure React-Refresh using React-Refresh-Webpack-Plugin
2. Start project that works on Windows/Linux on macOS, and you get the error:

```
19:16:33.302 › TypeError: Cannot read property 'forEach' of undefined
    at Object.injectIntoGlobalHook (webpack-internal:///./node_modules/react-refresh/cjs/react-refresh-runtime.development.js:461:20)
    at eval (webpack-internal:///./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js:8:20)
    at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js (http://localhost:1212/dist/renderer.dev.js:1448:1)
    at Object.options.factory (http://localhost:1212/dist/renderer.dev.js:26372:31)
    at __webpack_require__ (http://localhost:1212/dist/renderer.dev.js:25711:33)
    at http://localhost:1212/dist/renderer.dev.js:26927:11
    at http://localhost:1212/dist/renderer.dev.js:26935:12
setTimeout (async)
consoleLog @ console.js:93
transport @ console.js:46
runTransport @ log.js:44
(anonymous) @ ipc.js:21
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:91
```

Link to code example: None currently

## The current behavior

Project works everywhere but macOS, where it crashes upon attempting to start.

## The expected behavior

Behavior should be identical across operating systems.

**Comment by Slapbox** [comment]
The code in question on line 461 of `./node_modules/react-refresh/cjs/react-refresh-runtime.development.js` is:

```js
   hook.renderers.forEach(function (injected, id) {
      if (typeof injected.scheduleRefresh === 'function' && typeof injected.setRefreshHandler === 'function') {
        // This version supports React Refresh.
        helpersByRendererID.set(id, injected);
      }
    }); // We also want to track currently mounted roots.
 ```

**Comment by bvaughn** [comment]
> Start project that works on Windows/Linux on macOS, and you get the error:

If `hook.renderers` is undefined, this suggests that something else might be defining the global `__REACT_DEVTOOLS_GLOBAL_HOOK__` object, which is something that only React DevTools and Fast Refresh should be doing. That hook should always be defined with a `renderer` property:

https://github.com/facebook/react/blob/dcdf8de7e1489fda5cee70acbd1310ee1bb0d312/packages/react-devtools-shared/src/hook.js#L300-L301

https://github.com/facebook/react/blob/dcdf8de7e1489fda5cee70acbd1310ee1bb0d312/packages/react-refresh/src/ReactFreshRuntime.js#L447-L448

So the question is– what's the other thing defining this global hook on your Mac? Do you have any other devtools or dependencies in your project that do this?

**Comment by gaearon** [comment]
Are you using very old React DevTools? https://github.com/facebook/react/issues/19072#issuecomment-639884030

**Comment by gaearon** [comment]
Going to close assuming that's the case.

**Comment by Slapbox** [comment]
Thanks @bvaughn and @gaearon, that was indeed the issue. 

I have no idea where the extension folder was - I couldn't find it anywhere in our `Application Support/Electron` folder - but deleting the whole folder worked fine.

**Comment by eliot-akira** [comment]
For others encountering this issue, what solved it for me was: remove the folder `~/Library/Application Support/Electron/extensions`.
