### ISSUE TITLE
Bug: useState with class as initial state throws an error

### ISSUE THREAD

**Issue by jneuendorf** [facebook/react#21057]
Using a JavaScript class as initial state in `useState` throws an error. This is because `mountState` check if the initial state is a function by `typeof initialState === 'function'` and classes are technically functions. However since ES6+, I feel like most developers don't consider classes functions because of the less prototype-inheritance feel since ES6 and the `class` keyword.

React version: 17.0.2

## Steps To Reproduce

1. Define an ES6 class
2. Use the class as `initialState` argument to `useState`

Code example:

```jsx
import { useState } from "react";
import ReactDOM from "react-dom";

class A {}

function App() {
  const [cls, setCls] = useState(A);
  return <h2>{cls.name}</h2>;
}

ReactDOM.render(<App />, document.body);
```

## The current behavior

```
TypeError: Cannot call a class as a function
    at _classCallCheck (eval at z (eval.js:42), <anonymous>:3:11)
    at A (VM302 index.js:19)
    at mountState (react-dom.development.js:10436)
    at Object.useState (react-dom.development.js:10919)
    at useState (react.development.js:954)
    at App (VM302 index.js:25)
```

Alternatively, the error can be `TypeError: Class constructor X cannot be invoked without 'new'`.

## The expected behavior

As mentioned in the description above, I would 

- either expect classes to work
- or mention this caveat in the docs.

I guess checking, if the initial state is actually a non-class function, could cause instances of subclasses of functions not to work (depending how the check is done).

**Comment by bvaughn** [comment]
This is because `useState` supports two formats:
1. Eagerly initialize the value (e.g. `useState('value')`)
2. [Lazily initialize the value](https://reactjs.org/docs/hooks-reference.html#lazy-initial-state) with a function (e.g. `useState(() => 'value')`)

React decides which one you've done using the `typeof` operator.

In JavaScript, the `typeof` a class is `"function"` so React thinks you're using the second format and tries to call the "function" which causes an error to be thrown.

To fix this, you can use a function wrapper:
```js
useState(() => A);
```

**Comment by jneuendorf** [comment]
@bvaughn Thanks for the quick reply. I agree that this is technically not a bug. I think, I mainly stumbled upon this, because I didn't know about the 2nd signature of `useState` that you mentioned.

My main concern was that future React developers probably started learning JavaScript with ES6 or newer and thus not being that aware of the fact that classes are just syntactic sugar.

> React decides which one you've done using the typeof operator.

One of these nice little yellow notes like this

<img width="899" alt="Screenshot 2021-03-23 at 20 38 15" src="https://user-images.githubusercontent.com/6906734/112207776-d4f69b80-8c17-11eb-8c0d-915003b40b92.png">

stating that

> `typeof` is used and any non-function callable, i.e. classes, can lead to unexpected behavior and should be wrapped in a function

would probably do, because the scenario should be pretty uncommon and the `wrap in a function` workaround is easily implementable for React users.


> I am not aware of an alternative to this approach but please feel free to share one if you have an idea.

I searched a bit and found that there seems to be no robust / cross-browser way to achieve this. So that, additionally, makes the "note solution" score, IMO.

**Comment by gaearon** [comment]
Let's see if this comes up again. This is the first time someone reported being confused by this, so my impression is it's not very common to put class instances in state in the first place (e.g. typically you'd hold them in refs instead since you probably don't want to read from a mutable class instance during rendering, so there's no point in holding it in state in the first place).

If it keeps coming up we can add a warning if the prototype of the function you passed is not empty. But I don't have a clear sense that this is actually a common pitfall.

**Comment by eps1lon** [comment]
I recall similar issues with putting function components into state which is even harder to detect. Maybe static analysis + types might do the trick:
1. Assume only inline function expressions are intended for functional updates i.e. `setState(() => {})`
2. Reject every other callable passed

Note that the TypeScript types will already show you that the type of the state is not what you expect it to be. We could even go further and [reject newables entirely in `useState(value)`](https://www.typescriptlang.org/play?ssl=7&ssc=77&pln=7&pc=84#code/FAegVGwARlCaB7ArlADgJwQIwIZYDYCeaOAzqQKYAmUOUAxvmaVAO4AWAlve28vjQAu7TK1qCo6JADtBnALYUAdFGiwAkgDMohZGxyyoghGiQS6jZlE6yTpQTkEUde6RWpGTSSlE0z6cgjSOPhQSKhUjhQsygDmKgAG3hQAyg5OABQZAJRQALwAfFDq0pxyIQDCTOTZCQA0UAmUgmlRWbmFUACC0gjCFOhVzLVqIMBUFJbozn7SAZxBYZStmfZRAFxQAHIUrHj4FABi-oHS2ZtuAG4DANygIMUTIURsFADkNOw411BusY6cH6CQioaK0aQ0Vj8GhBF7PBBiBIAFSgFAAHk4ISwAKJoxhICYAHhkAGteqxpA0dnsCEcTgtpAUEuNJkxpr56YtkisKISkQUMmsnJskecoABtJENLJuVg8kUdIqXBCcKjZAC6d2AlnIUEOCBMAG9oL8cPJ8lA3vqEG9gABfYDaoL2CVCigNZo89UW7npCgZa3ZLX0Z0STQGi2yvUGnI3IA):

![Screenshot of above playground when hovering over `useState` in line 14](https://i.ibb.co/Gd1qhm7/usestate-newables.png)

**Comment by gaearon** [comment]
Tbh this just feels like some better addressed by a linter.

Or maybe we could warn if the constructor name starts with a capital letter?

**Comment by gaearon** [comment]
I’d like to see a PR that warns if setState or useState is passed a function whose first letter is capital. That’s enough of a hint to find the common cases.

**Comment by abhijit-hota** [comment]
Hello, @gaearon and @eps1lon ! 👋 

If that PR being talked about isn't being worked upon, I can work on it. I suppose I have to work [here](https://github1s.com/facebook/react/blob/HEAD/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js)? Any pointers will be helpful.

**Comment by gerhardsletten** [comment]
Meet the same problem with a wrapper that would hide an payment options if `window.ApplePaySession` was undefined. useState would try to call the function and then ApplePaySession would this error: `TypeError: Constructor requires 'new' operator`.

Result was an fatal error for everyone in Safari.

If invoked directly typescript would give and error not calling it with `new`

<img width="780" height="265" alt="Image" src="https://github.com/user-attachments/assets/876c6a90-6a9e-4726-957d-91a967a8c243" />

..but looks like there is no way to make a type guard that can separate a regular function to a class-function. You can only use the instanceof for a known class:

`if (y instanceof MyKnownClass)`

In runtime it should be possible to add a check ([source here](https://stackoverflow.com/questions/29093396/how-do-you-check-the-difference-between-an-ecmascript-6-class-and-function)) and [ts-class from type-fest](https://github.com/sindresorhus/type-fest/blob/main/source/basic.d.ts#L6C1-L9C3)

Probably not good for performance to check all calls to useState, but one can add this to own projects to avoid the pitfall.

```
export type TClass<T, Arguments extends unknown[] = unknown[]> = {
	prototype: Pick<T, keyof T>;
	new(...arguments_: Arguments): T;
};

function isClass(func:unknown):func is TClass<unknown,[]> {
  return typeof func === 'function' 
    && /^class\s/.test(Function.prototype.toString.call(func));
}

function fnGuard(fn:unknown) {
  const isClassFn = isClass(fn)
  if (isClassFn) {
    return () => {
      return fn ? true : false
    }
  }
  return fn
}

const [hasApplePay] = useState(fnGuard(window.ApplePaySession))
```

**Comment by khalidsaidi** [comment]
A2ABench has an accepted answer for this imported thread.
- Thread: https://a2abench-api.web.app/q/cmmo0j35t0073pv0bixhieqdh
- Accepted at: 2026-03-25T19:52:58.449Z
- Accepted answer agent: `ai village`
- Answer preview: "No matching threads were found for this query."
