### ISSUE TITLE
Bug: Lazy loading a component throws Unchaught undefined

### ISSUE THREAD

**Issue by zenstok** [facebook/react#21055]
React version: 17.0.2

## Steps To Reproduce

1. Upgrade from React 16 to React 17 (react and react-dom both to 17.0.2)
2. Do not touch the source code besides upgrading react versions

## The current behavior

Receiving `Unchaught undefined` when trying to render a lazy-loaded component inside `<Suspense />`

## The expected behavior

The code works as it was on version 16.

**Comment by gaearon** [comment]
We can't guess without a repro. My guess is something was buggy in your code but the bug was accidentally being suppressed, and now it's more visible. I can't say more without having some code to run.

**Comment by gaearon** [comment]
This looks similar, where the user mistake is forgetting to actually return an import.
https://github.com/facebook/react/issues/18768

**Comment by Zveroboev** [comment]
I have same problem with React v17.0.2. With React 16 work fine.

**Comment by gaearon** [comment]
We can't help without a reproducing case.

**Comment by Zveroboev** [comment]
```
import * as React from 'react';

const ComponentVertical = React.lazy(() => import('./ComponentVertical'));
const ComponentHorizontal = React.lazy(() => import('./ComponentHorizontal'));


function Container(props: {isCompact: boolean}) {
  return (
                    <React.Suspense fallback={<div>Loading...</div>}>
                        {typeof isCompact === 'boolean' ? (
                            <InfraBuzzerVertical />
                        ) : (
                            <InfraBuzzerHorizontal />
                        )}
                    </React.Suspense>
  );
}
```

**Comment by gaearon** [comment]
I mean a project we can run. Can you extract a minimal case into a repo? Or a sandbox.

**Comment by Zveroboev** [comment]
I cat't reproduce this on clear minimal case. It work fine. But, when I install this component in a other project with different react versions in deps (react 17 from my component and react 16 from other components, project use react 17), I catch this error. Downgrade project and component to React v16 can fix this error.

Sorry for my English.

**Comment by gaearon** [comment]
You probably shouldn't have two Reacts with different versions in one project. This can lead to confusing outcomes unless you're doing it in a very particular way.

Your component should not include React with it at all. Instead, it should use React from the application in which it's running.

**Comment by zenstok** [comment]
I found the cause for this. You need to restart the development server and then it will work.

**Comment by Can-Sahin** [comment]
If you forget to upgrade `react-dom` package to v17 this error would show up. I had it as well. FYI

**Comment by thallesmota2** [comment]
thanks! Can-Sahin
