### ISSUE TITLE
Bug: Cursor jumps to the end of input after value refresh

### ISSUE THREAD

**Issue by IlyaHalsky** [facebook/react#21058]
I've ran into this issue when was trying to implement date input, in which you can adjust date by using arrow up and arrow down keys. When cursor is on month I need to add or subtract one by pressing up and down keys. When cursor is on day, same thing with days. Listed below code should work in theory, but doesn't behave as expected.

React version: 17.0.0

## Steps To Reproduce
1. Create controlled input
2. Create key press handler, which changes value of input.

Code example:

```typescript
export function DatePickerTest() {
    const [timestamp, setTimestamp] = useState(1609459200000)
    const date = new Date(timestamp)
    const value = date.getDate() + ""
    const onKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
        switch (event.code) {
            case UP_ARROW_KEY.code:
                setTimestamp(prev => prev + 24 * 60 * 60 * 1000)
                event.preventDefault() // to prevent default action of moving cursor to start of input
                break
            case DOWN_ARROW_KEY.code:
                setTimestamp(prev => prev - 24 * 60 * 60 * 1000)
                event.preventDefault() // to prevent default action of moving cursor to end of input
                break
        }
    }
    return el("input", {
        value: value,
        onKeyDown: onKeyDown,
    })
}
```

## The current behavior
When value changes cursor jumps to last position

## The expected behavior
Value update should preserve cursor position

**Comment by vkurchatkin** [comment]
That's just normal browser behaviour. You need to restore cursor position manually

**Comment by IlyaHalsky** [comment]
I've tried doing so using 
```typescript
function useSelectionEditableInput(inputElement: RefObject<HTMLInputElement>): (from: number, to: number) => void {
    const [selectionState, setSelectionState] = useState<SelectionState>(initialSelectionState)
    const setSelection = (from: number, to: number): void => {
        setSelectionState((state: SelectionState) => ({...state, needsSet: true, startPosition: from, endPosition: to}))
    }
    useEffect(() => {
        if (inputElement.current && selectionState.needsSet) {
            const current = inputElement.current
            const {selectionStart, selectionEnd} = current;
            const update = selectionState.startPosition !== selectionStart || selectionState.endPosition !== selectionEnd;
            if (update) {
                current.selectionStart = selectionState.startPosition;
                current.selectionEnd = selectionState.endPosition;
                setSelectionState((state: SelectionState) => ({...state, needsSet: false}))
            }
        }
    }, [selectionState])
    return setSelection
}
```
Where inputElement is reference to the input. On key press I call setSelection and it works, sort of.
The problem is visualy cursor jumps to the end and then sets into correct place.

**Comment by IlyaHalsky** [comment]
Here is a gif of what's happening, with 30 frps, you can't always see it :(
![cursor](https://user-images.githubusercontent.com/7192543/112280833-16c22900-8c8e-11eb-80e9-cc9461a871f7.gif)

**Comment by vkurchatkin** [comment]
It's hard to tell without seeing how you use this hook, but generally you need to use `useLayoutEffect`  to avoid such issues

**Comment by IlyaHalsky** [comment]
@vkurchatkin Indeed, I've tried it and it helps. Thank you very much!
