### ISSUE TITLE
Feature Suggestion: Pass React Hook factory dependencies as arguments to the factory

### ISSUE THREAD

**Issue by yassine** [facebook/react#21075]
Currently, there is no way for accessing the array dependencies of a given React Hook in an optimal way (Function.bind can help but yet it is not optimal). Passing the array of dependencies to the hook factories such as in useMemo, useCallback, useLayoutEffect can be handy at many sides:

- Putting the factory outside the body of the component (performance improvement by limiting functions that needs to garbage collected)

- Allowing users to enforce (optionally) not relying on values from the lexical scope. As values from the lexical scope can often be sources of bugs when the array of dependencies is not in sync with what the Factory body refers to. (It's a form of [pokayoke](https://en.wikipedia.org/wiki/Poka-yoke))

Consider the following example:
```javascript
//instead of 
function MyComponent(props) {
  const value = useMemo(() => heavyComputation(props.value), [props.value]);
  // a new function is created at each render whether it is collected by the hook or not
}
```

```javascript
// we would be able to have
function MyComponent(props) {
  const value = useMemo(heavyComputation, [props.value]);

}

function heavyComputation(value) {
  //...
}
```

**Comment by gaearon** [comment]
It's intentional that Hooks don't work like this, and instead nudge you towards writing things in the render scope. So that it's always easy to capture more props/state if needed without changing a bunch of signatures. Or people microoptimizing by trying to move the closures out. I understand why you're trying to do this, but it's contrary to the design so it's not something we'd like to do. It's something that we intentionally decided against.

**Comment by yassine** [comment]
It wasn't really about micro-optimizing, that was actually a positive side effect :)
When I'm personally reviewing code it's far easier for me to catch what the factory needs, I would just have to look at its arguments. And by the way, currently whenever needs, while not changing signatures you still have to change a bunch of array of dependencies (If you allow me to re-phrase you). 
I respect your design choices anyways, and while I'm at it Big Up to you girls & guys for your efforts, truly.
