### ISSUE TITLE
Bug: Getting value to populate to render block without triggering warning

### ISSUE THREAD

**Issue by Muirik** [facebook/react#21096]
In my React app I need to retrieve some dates from my data that's coming in from the backend to set the starting and ending dates for a date filter in a class-based component. If I do this within my render, it works:

```
  <InlineDateField
    defaultValue={this.getStartDate()}
    styles={actionButtonStyles}
    onChange={(date) => this.handleDateRangeFiltering(date, "begin")}
  />
```
  
The `getStartDate()` looks like this:

```
  getStartDate = () => {
    const today = new Date();
    return new Date().setDate(today.getDate()-30);
  }
```

However, what I really want to do is set the date based on the results of my data coming in from the server when the component mounts. In other words, instead of `getStartDate()` as seen above, I'd ideally like to pass in a function like this:

```
  getFirstDate = () => {
    if (!this.state.hasFirstRangeDate) {
      const firstRecord = this.props.records.pop();
      this.setState({ hasFirstRangeDate: true });
      return firstRecord.date;
    }
  }
```
  
And this works. The browser loads, and the date filter is populated with the correct date based on the records retrieved from the server.

Note: I wrap the date range filter part of my render block in a ternary expression, so that the date range filter doesn't try to render before the data is available. That also works as expected.

Interestingly, in both cases I assign the start date of that part of the render block to the returned value of a function. But, in the second case only, I end up with the following React warning in the console:

_index.js:1 Warning: Cannot update during an existing state transition (such as within render). Render methods should be a pure function of props and state._

I assume this is a "hard" warning? In other words, avoid this at all costs? If this is not the case, and I can safely ignore this, I'd be interested in knowing. But I assume the warning is there to say, "this is not how React was designed to work".

By the way, I get my records within componentDidMount(), like so:

```
  componentDidMount() {
    this.props.getRecords();
  }
```
If there were a `componentWillMount()` lifecycle hook I would use it, to avoid this situation. Alas, there is not.

This being the case, is this a bug -- or is this indeed behavior one is indeed supposed to avoid at all costs? What alternatives do I have available if this warning is legitimately saying "avoid this at all costs"?

**Comment by gaearon** [comment]
The canonical way to initialize state in a class component is in the constructor. Why don't you do this instead?

**Comment by Muirik** [comment]
Yes, I can take a look at doing it that way.
