### ISSUE TITLE
Bug: aspectRatio not being applied via style

### ISSUE THREAD

**Issue by mattgperry** [facebook/react#21098]
React version: 16.14.0, 17.0.2

## Steps To Reproduce

1. Apply aspectRatio via `style` - no aspectRatio applied
2. Add via className - aspectRatio applied

Needs Chrome 79 or above:
Link to code example: https://codesandbox.io/s/react-bug-not-applying-aspect-ratio-via-style-w2pqh?file=/src/App.js

## The current behavior

No aspectRatio rule applied:
https://codesandbox.io/s/react-bug-not-applying-aspect-ratio-via-style-w2pqh?file=/src/App.js

## The expected behavior

aspectRatio applied, here I'm adding it via a `useLayoutEffect`:
https://codesandbox.io/s/currying-hill-i09qn?file=/src/App.js

**Comment by adyz** [comment]
Yes, I have the same issue with another style property 
Basically I want to add   `font-feature-settings: "tnum"` or `fontFeatureSettings` and it gets removed.


https://codesandbox.io/s/custom-css-why-no-work-66ve2

**Comment by sebmarkbage** [comment]
Try passing a string instead of number. React special cases numbers (to add the "px" suffix) and only doesn't for certain known attributes. So new ones sometimes need to be added to the list.

**Comment by sebmarkbage** [comment]
@adyz Your issue is unrelated. Would you mind opening a separate issue for that thread?

**Comment by mattgperry** [comment]
Thanks @sebmarkbage

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/21100

**Comment by garrettmaring** [comment]
Should `aspectRatio` be unit-less?

https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio
https://web.dev/aspect-ratio/

It seems like it should be a string (which it was) and I am seeing the property work as expected with `style={{ aspectRatio: '1 / 2' }}` for example.

**Comment by gaearon** [comment]
@mattgperry how soon do you need this? Are you blocked?

**Comment by mattgperry** [comment]
@gaearon no, no rush at all! Just something I stumbled upon.
