### ISSUE TITLE
Feature Request: Localized CSS files

### ISSUE THREAD

**Issue by DimitarTB** [facebook/react#21092]
I have often ran into issues of my CSS applying in places it should be. Now I don't do it as often but when I started out I usually used generic class names like container, wrapper and so on. I would write different CSS for each class name in different CSS files and so there would be a conflict. Today I ran into a similar issue when using an open source component. It had a class name called container and so do I - it is a class that applies to all my containers. This caused a few issues for me. It is common sense that when we are building open source components we should use Styled Components or at least not use a generic class name like Container in that manner, but that is not always the case especially with older components. 

I would ask for there to be a way to somehow define weather a CSS file should apply to the entire application or only where it is imported, This could be done inside of the CSS file itself, when the CSS files are imported or somewhere inside a JSON file or something. I think that this will dramatically change the way we structure and write our CSS code without adding a lot of complexity to React. 

I know styled components are a thing but not everyone chooses to use them - I for one use only CSS due to my editors autocomplete features which help me tremendously when I am trying to remember something or even to discover a new property from time to time.

**Comment by bvaughn** [comment]
Are you aware of [CSS modules](https://github.com/css-modules/css-modules)? Sounds to me like what you're describing, and [they can be used with create-react-app](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/) and other app frameworks.
