### ISSUE TITLE
Bug: TypeError: Object is not a function or its return value is not iterable (0.0.0-experimental-7b84dbd16)

### ISSUE THREAD

**Issue by jsoneaday** [facebook/react#21095]
I am playing around with concurrent mode and get this error when calling useTransition. Has this function been removed or renamed?

React version: 0.0.0-experimental-7b84dbd16

## Steps To Reproduce

1. Use unstable_createRoot in index.js to enable concurrent mode
2. import useTransition from react in App.js
2. Try and call useTransition like this 
const [startTransition, isPending] = useTransition({
    timeoutMs: 3000,
  });

Link to code example:
I don't have one

## The current behavior
![image](https://user-images.githubusercontent.com/1474935/112476592-711fc000-8d48-11eb-8c32-92a859b432e4.png)

![image](https://user-images.githubusercontent.com/1474935/112476388-39187d00-8d48-11eb-8ad3-46d2e416bd63.png)

## The expected behavior
I was trying to test transitions in concurrent mode so I would think it would just transition.

**Comment by eps1lon** [comment]
It was [renamed to `unstable_useTransition`](https://github.com/facebook/react/pull/18825). [`timeoutMS` was also removed](https://github.com/facebook/react/pull/19703).

**Comment by bvaughn** [comment]
> Link to code example:
I don't have one

The idea is that you'd create one using something like Code Sandbox :)

Without a repro I can't be positive, but it seems like @eps1lon has answered this question though, so I'm going to close this issue for now.

**Comment by jsoneaday** [comment]
@eps1lon thank you. But now I get an error that App suspended while rendering, but no fallback UI was specified. As you can see I do have a fallback set and this is my only call to Suspend.

![image](https://user-images.githubusercontent.com/1474935/112488102-a67ddb00-8d53-11eb-9470-0d86aeecf5b7.png)

**Comment by gaearon** [comment]
`<Suspense>` needs to be *above* the component that Suspended. In your example, `App` Suspended, so you want to place `<Suspense>` above it. Alternatively, you can move the `setMessage` call into `Child`.

**Comment by jsoneaday** [comment]
Thank you Dan. Really appreciate it.

**Comment by gaearon** [comment]
No problem. Appreciate you playing with experimental stuff! Sorry the docs are rough/outdated. We're focused on polishing this and getting it into a releasable stage and then we'll have better docs.

**Comment by gaearon** [comment]
Btw, https://github.com/reactjs/server-components-demo is the latest thinking on how the pieces fit together. So feel free to check that out too. It has a few uses of `useTransition`.

**Comment by jsoneaday** [comment]
I totally understand. I should have done my own investigation before I submitted. I love React and am eagerly waiting for concurrent mode.

**Comment by gaearon** [comment]
No worries at all, it's a bit hard to find the info now. Feel free to ask any follow-up questons here!
