### ISSUE TITLE
setState(another setState call inside) after promise be called twice?

### ISSUE THREAD

**Issue by nanxiaobei** [facebook/react#21114]
React version: 17.0.2

## Steps To Reproduce

When after promise(async), setState(another setState inside) runs twice.

Without promise(not async), setState(another setState inside) runs once.

## Link to code example:

https://codesandbox.io/s/setstate-issue-v1fpv

![Kyzvh.png](https://s3.jpg.cm/2021/03/27/Kyzvh.png)

## The current behavior

`setB` run once.

## The expected behavior

`setB` runs twice.

**Comment by nicktify** [comment]
Hello! if you write the useState inside function this way, without an arrow function, the problem disappears..

```js
setB(function(prevB){
      console.log("setB");

      setA((prevA) => prevA + 1);
      return prevB + 1;
    });
```

**Comment by eps1lon** [comment]
Thanks for the reproduction.

This is intentional behavior of `React.StrictMode` (see `index.js`). `StrictMode` will call functional updates (i.e. `setState(() => {})` twice to detect side-effects. The actual state change will only be applied once though. 

For more information check out https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects. Does this clear things up for you?

**Comment by nanxiaobei** [comment]
> Thanks for the reproduction.
> 
> This is intentional behavior of `React.StrictMode` (see `index.js`). `StrictMode` will call functional updates (i.e. `setState(() => {})` twice to detect side-effects. The actual state change will only be applied once though.
> 
> For more information check out https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects.
> 
> Does this clear things up for you?

Hi, in the [codesandbox demo](https://codesandbox.io/s/setstate-issue-v1fpv), when click the "+1" button, `a` updates from `0` to `2`, I think the sate change just applied twice.

**Comment by nanxiaobei** [comment]
> Hello! if you write the useState inside function this way, without an arrow function, the problem disappears..
> 
> ```js
> setB(function(prevB){
>     console.log("setB");
> 
>     setA((prevA) => prevA + 1);
>     return prevB + 1;
> });
> ```

Tested in the demo, just runs twice also. 😑

**Comment by eps1lon** [comment]
Sorry about the confusion.

```js
// that's a side-effect which will be applied twice.
setA((prevA) => prevA + 1);
// the state update which won't be applied twice 
return prevB + 1;
```

You probably want to put `A` and `B` into the same state and switch to `useReducer`.

**Comment by nanxiaobei** [comment]
> Sorry about the confusion.
> 
> ```js
> // that's a side-effect which will be applied twice.
> setA((prevA) => prevA + 1);
> // the state update which won't be applied twice 
> return prevB + 1;
> ```
> 
> You probably want to put `A` and `B` into the same state and switch to `useReducer`.

OK, I see. 

Thank you very much for your patient explanation.
