### ISSUE TITLE
Question:  is there any way to retrieve React Devtool performance data?

### ISSUE THREAD

**Issue by TomJerryTheHandsome** [facebook/react#21125]
Hi guys, I want to get react devtool performance/profiler results, probably a JSON data and send to our local server, I read through the react-devtools-core but unfortunately do to get any clue how to do this ?

**Comment by eps1lon** [comment]
You have two options:

1. Save the profile (5th icon (downarrow) in the toolbar)  
![screenshot of the react devtools profiler tab toolbar. The fifth action is hovered which is named "Save Profile"](https://user-images.githubusercontent.com/12292047/112816023-39cf4d00-9081-11eb-8686-81cf97ad0376.png)

1. Use [`React.Profiler`](https://reactjs.org/docs/profiler.html#gatsby-focus-wrapper) to construct a custom data structure

**Comment by bvaughn** [comment]
@eps1lon's answer is correct so I'm going to close this question :)
