### ISSUE TITLE
Bug: clientHeight is reported as 0 when conditionally rendered

### ISSUE THREAD

**Issue by chengsieuly** [facebook/react#21131]
A component gets rendered conditionally based on an async call. The rendered component renders its value from the response of the async call. When it gets rendered, the `clientHeight` that gets reported is `0`.

React version: 17.0.2

## Steps To Reproduce

1. Load the sandbox

https://codesandbox.io/s/interesting-bug-resolving-around-ref-bkc6k?file=/src/App.js

2. Take a note at the console logged for the `clientHeight` (notice it is `0`)
3. Flip a) and b) so that b) is called first

```javascript
 setValue(longString); // b
 setFlag(true); // a
```

4. Clear the console and refresh
5. Notice when b) is called first, the console logged for `clientHeight` is now `96`

Link to code example: https://codesandbox.io/s/interesting-bug-resolving-around-ref-bkc6k?file=/src/App.js

## The current behavior
`clientHeight` is `0` when we set the flag first.

```javascript
 setFlag(true); // a
 setValue(longString); // b
```

## The expected behavior
`clientHeight` is `96` irrelevant of order

NOTE: We also found that this ONLY happens when the we set these values in an async call

```javascript
// `clientHeight` is `0`
React.useEffect(() => {
  request.then((response) => {
    setFlag(true); // a
    setValue(response); // b
  });
}, []);
```

```javascript
// `clientHeight` is `96`
React.useEffect(() => {
  setFlag(true); // a
  setValue("Super long strong Super long"); // b
}, []);
```

**Comment by bvaughn** [comment]
What you're observing is that legacy React processes both of these state updates independently when called from an async callback. First it processes the flag update (without any content/response) and then the response. Reversing the order of the variables avoids the temporarily "invalid" state. There are a couple of ways you could deal with this:

### 1 Combine the two pieces of state using a [reducer](https://reactjs.org/docs/hooks-reference.html#usereducer)
```js
const initialState = {
  flag: false,
  value: "",
};

function reducer(state, action) {
  switch (action.type) {
    case "setContent":
      return {
        flag: true,
        value: action.data,
      };
    default:
      throw new Error();
  }
}

// In your component...
const [state, dispatch] = React.useReducer(reducer, initialState);

```

### 2 Batch the individual updates together
You could batch them together using the unstable batching API:
```js
import {unstable_batchedUpdates as batchedUpdates} from 'react-dom';

// In your callback:
batchedUpdates(() => {
  setFlag(true); // a
  setValue(response); // b
});
```

### 3 Use concurrent mode
Fortunately the upcoming React concurrent mode release will automatically batch updates like this. You can try this using the `@experimental` release if you're curious:
```js
import { unstable_createRoot as createRoot } from "react-dom";

const rootElement = document.getElementById("root");
const root = createRoot(rootElement);
root.render(<App />);
```
