### ISSUE TITLE
Root component's ref is not set if it is rendered in another react app's useEffect

### ISSUE THREAD

**Issue by xiaody** [facebook/react#21138]
React version: 17.0.2

## Steps To Reproduce

1. In useEffect, render another app with ref into a new DOM node.
```jsx
function Test() {
  useEffect(() => {
    const ref1 = React.createRef();
    render(<App ref={ref1} />, document.getElementById("app1"));
    console.log("ref1", ref1.current); // null. why?
  }, []);
  return <span>test</span>;
}
```

Link to code example: https://stackblitz.com/edit/react-useeffect-ref-null?file=index.tsx

## The current behavior
ref is not set if rendered in another root's useEffect.

## The expected behavior
ref is set synchronously no matter where it is rendered.

**Comment by bvaughn** [comment]
React does not work on two roots at once. Within your effect, React is still in progress of working on a single root (`Test`). Once that's done, it synchronously renders the second root (`App`).

This is working as designed. :)

**Comment by bvaughn** [comment]
Going to go ahead and close this issue. Feel free to ask follow up questions if you have any!
