### ISSUE TITLE
Bug: Form onSubmit does not POST submit button name

### ISSUE THREAD

**Issue by francoisfreitag** [facebook/react#21162]
React version: 17.0.2

## Steps To Reproduce

1. Open the browser dev tools to the network tab
2. Click the submit button in the following sandbox
3. Inspect the generated HTTP POST request body

Link to code example:
1. https://codesandbox.io/s/react-repro-ehorm?file=/src/App.js

## The current behavior

Button name **not** included in the POST data.

## The expected behavior

Button name included in the POST data.

Removing the `onSubmit` handler on the form restores the expected behavior.

**Comment by vkatatab** [comment]
I think you misunderstood something.
If you want to control the submission you have to control the data that user entered.
Take a look at [docs](https://reactjs.org/docs/forms.html#controlled-components)

**Comment by francoisfreitag** [comment]
Hi,
Thanks for looking into my issue.

My form components are uncontrolled. I do not want any more control over the data that is submitted, but to prevent double form submission. That is extra behavior on top of the default form submission handled by the browser.

I’m purposefully not calling `e.preventDefault()` in the `onSubmit` handler to let the event bubble, so that the browser catches it and do the submission.

Without the `setState()` (that triggers a re-render), the code works just fine.
Also, delaying the `setState` with a `setTimeout(() => setSubmitted(true), 0)` is sufficient to have the browser submit the button name in the post data.

**Comment by francoisfreitag** [comment]
Sorry, this was a user error.
Because the field is disabled before the browser generates the POST request, it is not included in the POST-ed data.
