### ISSUE TITLE
Exposing possibleStandardNames as a module proposal

### ISSUE THREAD

**Issue by rdwoodring** [facebook/react#21160]
I'm curious if there'd be any interest in exposing [possibleStandardNames.js](https://github.com/facebook/react/blob/a423a01223785a8bc4dcd55f2a0288200b033eee/packages/react-dom/src/shared/possibleStandardNames.js) as an importable entity for users of React. It wouldn't have to be this mapping object specifically; just a utility or some way to be able to reliably and programmatically map `accesskey` to `accessKey`, `class` to `className`, etc.

The use-case I have is that we expose a WYSIWYG editor to end users in some places and then after the WYSIWYG data is sanitized and saved as an HTML string on the server, we render it back out on other screens. For a first pass I had to simply dangerously set that HTML string so that formatting was preserved, but I'd really like to go a step further and transform the HTML string programmatically into React elements. This would allow me to _enhance_ the markup and do logic like:

```
if (nodeName === 'img') {
  // attach a click handler that opens a dialog with a zoomable view and/or render a totally different component instead of a plain old image
} else if (nodeName === 'a') {
  // add target="_blank" to make sure all links open in new tabs, then render the a tag, preserving all other attributes
} else {
  // just render the node as is, preserving attributes
}
```

The trouble is that I can't just dump attributes from the parsed DOM node onto a created React element, because they don't match. Right now it seems that the only good way to achieve the attribute mapping is to manually write them myself (which is brittle and laborious) or to copy the `possibleStandardNames.js` file from the React repo (at the correct version tag, of course) and make sure that someone remembers to keep it up to date when we bump versions of React (again, brittle and pretty error prone).

Maybe I'm going about this the wrong way, but I expect I'm not the only person with this (or similar) use case, but I am very interested to hear discussion/rationale in favor or against this proposal.

Thanks

**Comment by gaearon** [comment]
I’d say your best bet is to copy it into your project. It doesn’t change much, only when we add some new property (which is very rare). I’m not sure that for a WYSIWYG, you’d even want to have all attributes though. An allowlist for every tag would make more sense to me.

**Comment by rdwoodring** [comment]
Yeah, that's the approach I've got set up for now, along with hardcoded reference to the expected React version and a check/warning against `React.version` in case the expected version is different than the imported version.

The WYSIWYG library has very solid filtering capabilities and we've got a pretty strict/slim allowlist of attributes as content is entered already; I was just trying to be robust and cover my bases on the rendering side.

Thanks for the quick response. I guess I will leave this thread open for now in case anyone else wants to weigh in one way or another?

**Comment by gaearon** [comment]
I don't think it's worth keeping open. We've gotten a few requests like this over the years but the use cases are pretty niche and this doesn't really justify increasing the surface area.

**Comment by rdwoodring** [comment]
Sounds good. Thanks for the advice on a path forward. Closing.

**Comment by gaearon** [comment]
It changes roughly once a year or even less often. And we wouldn't change existing properties, only add new ones. It's highly unlikely that your WYSIWYG would produce new previously unknown DOM properties out of the blue. So I think it's a safe bet that your current version should serve you well even if you don't keep it in sync.
