### ISSUE TITLE
Bug: Unexpected redirection of website https://reactjs.org/ to the start page when a visitor switches the language

### ISSUE THREAD

**Issue by tastytea-github** [facebook/react#21176]
It is not a bug, but an usability issue:
If user comes to an article on [https://reactjs.org/](https://reactjs.org/) in English language (for example, he comes from google search), then he expects to be redirected to the same page when he switches the language.

## Steps To Reproduce
1. Open any documentation article (for example, https://reactjs.org/docs/context.html#api) on [https://reactjs.org/](https://reactjs.org/) in English language.
2. Switch the language to another one (for example, Russian).

## The current behavior
Redirection to the start page of https://ru.reactjs.org.

## The expected behavior
Redirection to Russian version of the article https://reactjs.org/docs/context.html#api.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vkatatab** [comment]
I've just created a [pull request](https://github.com/reactjs/reactjs.org/pull/3616) to 'solve' this, however it is at [reactjs.org repository](https://github.com/reactjs/reactjs.org/)

**Comment by bvaughn** [comment]
The documentation and source for [reactjs.org](https://reactjs.org/) are in a different GitHub repository.

Please open a new issue in that repository:
[https://github.com/reactjs/reactjs.org](https://github.com/reactjs/reactjs.org/issues/new) 

Sorry for the inconvenience! 🙂
