### ISSUE TITLE
Bug: Wrong Warning when Input with Type File contains a onChange

### ISSUE THREAD

**Issue by mwaeckerlin** [facebook/react#21177]
React version: 17.0.2

## Steps To Reproduce

1. Create a `file` `input` that has an `onChange` handler:
    ```JavaScript
   <input type='file' onChange={console.log} />
    ```
2. Load it

## The current behavior

In the console, there is a warning:
> Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components

## The expected behavior

This warning is wrong and can be ignored.

Please remove that warning, it makes no sense. It is a completely legal and decent solution to handle the file upload triggered by the `onChange` event.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by mwaeckerlin** [comment]
Thank you, for the quick response, @eps1lon. Even though I still can reproduce the behavior in my context, I cannot without context.

When I comment out that input field, the warning disappears. But I can also comment out any other input field, and it also disappears. When I uncomment, it's back. Or when I remove the `form` tag. It seems, any slight change in the code lets the warning disappear?

There must be another root cause of the problem, even though I currently can't find it. The behavior is really strange.

So I will open a new ticket, when I can reproduce it outside of my context.
