### ISSUE TITLE
Bug: [Refresh] Components resulting of HOCs composition immediately applied to render functions are ignored

### ISSUE THREAD

**Issue by davidbonnet** [facebook/react#21179]
React version: 17.0.2
React-refresh version: 0.10.0

## Steps To Reproduce

Given the following files, making changes to `Component.js` doesn't trigger a re-render.

`main.js` module:
```jsx
import React from 'react'
import { render } from 'react-dom'

import { Component } from './Component.js'

function App() {
  return <main><Component /></main>
}

render(<App />, window.document.getElementById('root'))
```

`Component.js` module:
```jsx
import React, { memo } from 'react'
import { compose, withProps } from 'recompose'

export const Component = compose(memo, withProps({ value: 'Hello' }))(({ value }) => (<div>{value}</div>))
```

## The current behavior

Making changes to `Component.js` does not re-render the element in `main.js`.
The transformed `Component.js` module does not register the `Component` for refresh.

## The expected behavior

Making changes to `Component.js` does re-render the element in `main.js`.

**Comment by gaearon** [comment]
Is this a new issue or an existing one?

**Comment by davidbonnet** [comment]
Not that I know of.
