### ISSUE TITLE
There are multiple modules with names that only  differ in casing.Bug: 

### ISSUE THREAD

**Issue by ats1999** [facebook/react#21174]
React version:
latest as of now
## Steps To Reproduce
As this is happening with all of my react and nextjs projects, even they were working fine a few days ago.

## The current behaviour
I'm getting this warning
```js
./node_modules/webpack/buildin/module.js        
There are multiple modules with names that only 
differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.   
Use equal casing. Compare these module identifiers:
* C:\Users\Rahul kumar\desktop\Projects\vyorius\MerchantFrontend\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Rahul kumar\Desktop\Projects\vyorius\MerchantFrontend\node_modules\webpack\buildin\module.js
    Used by 3 module(s), i. e.
    C:\Users\Rahul kumar\desktop\Projects\vyorius\MerchantFrontend\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Rahul kumar\Desktop\Projects\vyorius\MerchantFrontend\node_modules\moment\moment.js
* C:\Users\Rahul kumar\desktop\Projects\vyorius\MerchantFrontend\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Rahul kumar\desktop\Projects\vyorius\MerchantFrontend\node_modules\webpack\buildin\module.js
    Used by 2 module(s), i. e.
    C:\Users\Rahul kumar\desktop\Projects\vyorius\MerchantFrontend\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Rahul kumar\desktop\Projects\vyorius\MerchantFrontend\node_modules\node-libs-browser\node_modules\punycode\punycode.js
```
## The expected behaviour
This warning should not be generated.

### What's happening 
I have a project `X` which is working fine today. 

Tomorrow I started the project and I got the warnings.

I stuck there and went through the internet but nothing works.

***
Then I copied every single file of the project one by one and installed the dependency as per requirement.

When I done with copy/paste i saw that this is warning fine, no warnings or errors. 

After few days later(1 or 2), I again started to see all the warnings on my console.

***

There is no issue with warnings in react but in NextJs, server is not running and I'm getting `server error`.

**Comment by bvaughn** [comment]
> There is no issue with warnings in react but in NextJs, server is not running and I'm getting server error.

This is the Rect repository. Bugs with Next should be reported to Next support. 😄 Going to close this issue as it is not something we can help with.

**Comment by ats1999** [comment]
@bvaughn as i have mentioned in the issue the same warning appearing in react project too.

So, it's also a react issue.

Because of React it might be appearing in next too.

**Comment by bvaughn** [comment]
It's not a React issue. React has nothing to with compiling your project (when this error is occurring).

**Comment by ats1999** [comment]
Can you tell me, whome should i report this warnings?
