### ISSUE TITLE
Bug:  im using axios to make a post call to get bearer token. this is working fine in postman but getting CORS error while doing from react

### ISSUE THREAD

**Issue by prohith14** [facebook/react#21184]
![image](https://user-images.githubusercontent.com/20105628/113637677-d6ea4100-9692-11eb-864a-95e39e6ad1c7.png)

React version:

## Steps To Reproduce

const postData = {
            client_id: aad.ClientI,
            scope: aad.Scope,
            client_secret: aad.ClientSecre,
            grant_type: 'client_credentials'
          };
          
          axios.defaults.headers.post['Content-Type'] =
            'application/x-www-form-urlencoded';
          
          axios
            .post(aad.AuthLoginUrl, JSON.stringify(postData))
            .then(response => {
              console.log(response.data);
            })
            .catch(error => {
              console.log(error);
            });

## The current behavior

Access to XMLHttpRequest at 'https://login.microsoftonline.com/3d486417-2ebd-42cf-8e19-4c8f5ed0b279/oauth2/v2.0/token' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

## The expected behavior

Return accessToken

**Comment by mudafar** [comment]
Not related to React.

To disable CORS locally (for development purposes only), you can follow this: https://stackoverflow.com/a/3177718

**Comment by 1Seok2** [comment]
I don’t think this has anything to do with React

Follow [microsoft get token https://docs.microsoft.com/en-us/graph/auth-v2-user#token-request](https://docs.microsoft.com/en-us/graph/auth-v2-user#token-request) 

Shouldn't you have to type `code`, `redirect_uri`  as well?
Since `code` and `redirect_uri` are also required, I think it will work if you add `code` and `redirect_uri`

**Comment by prohith14** [comment]
I understand it is not react issue but can some one help me hw to resolve this as im using it in react and i want that token to make request to api

**Comment by prohith14** [comment]
![image](https://user-images.githubusercontent.com/20105628/113673157-403f7380-96d6-11eb-98bc-53740adc81a8.png)

**Comment by prohith14** [comment]
i should get this access token to call another api

**Comment by goesnow** [comment]
It seems to be a CORS issue with SPA.
Would you like to try using a [proxy](https://stackoverflow.com/questions/59036377/cors-error-google-oauth-from-react-to-express-passportjs-validation#answer-59508459)?

**Comment by luximus-hunter** [comment]
Not getting CORS errors in Postman makes sense. Its a tool that disables them while testing to make it faster and focus on whats important. when you start using your API somewhere else, they will pop up. Its an issue with either your API or website, not React

**Comment by gaearon** [comment]
This has no relation to React.
