### ISSUE TITLE
Bug: [Refresh] Default exported unnamed functions are ignored

### ISSUE THREAD

**Issue by davidbonnet** [facebook/react#21181]
React version: 17.0.2
React-refresh version: 0.10.0

This issue is similar to #21179, but ignores default exported unnamed functions instead.

As a code comment suggests, this is a known limitation:
https://github.com/facebook/react/blob/a817840ea7d3818c0590cccb9159b13220f4fdb4/packages/react-refresh/src/ReactFreshBabelPlugin.js#L437-L438

Would a fix be considered?

## Steps To Reproduce

Given the following files, making changes to `Component.js` doesn't trigger a re-render.

`main.js` module:
```jsx
import React from 'react'
import { render } from 'react-dom'

import Component from './Component.js'

function App() {
  return <main><Component /></main>
}

render(<App />, window.document.getElementById('root'))
```

`Component.js` module:
```jsx
import React from 'react'

export default ({ value = "Hello" }) => (<div>{value}</div>)
```

## The current behavior

Making changes to `Component.js` does not re-render the element in `main.js`.
The transformed `Component.js` module does not register the `Component` for refresh.

## The expected behavior

Making changes to `Component.js` does re-render the element in `main.js`.

**Comment by gaearon** [comment]
This is intentional — even if we fix this case, we need some heuristic for other tools like lint rules. Why are you using this style? Functions should have names so that you get them in stack traces and so on.

**Comment by davidbonnet** [comment]
Indeed, but then it becomes confusing: https://github.com/vitejs/vite/issues/2719.

If there's no way around, this can be closed and I'll make a suggestion downstream to use https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md.

**Comment by davidbonnet** [comment]
However, given that an ignored component prevents a refresh (https://github.com/vitejs/vite/issues/2719), I haven't figured out yet whether this is an issue with `react-refresh` itself or with `@vitejs/plugin-react-refresh`. AFAIK, a code update of an ignored component should still trigger a refresh.
