### ISSUE TITLE
Bug: Error boundary not catching second error

### ISSUE THREAD

**Issue by subhero24** [facebook/react#21189]
I have the following situation in my react application:

```
<ErrorBoundary>
    <A />
</ErrorBoundary>
```

When the component A throws an error, the boundary catches the error and renders a fallback ui with component B.

```
<ErrorBoundary>
    <B />
</ErrorBoundary>
```

But the component B also throws immediately. This second error is never catched by the error boundary.

I have a very small codesandbox example here:
https://codesandbox.io/s/cranky-bassi-wcm3q?file=/src/App.js

I would expect the second error to also be logged from within getDerivedStateFromProps.

**Comment by vkatatab** [comment]
I may misunderstood the documentation or your problem.
But, it seems to be that your error boundary is throwing an error and it will not caught it by itself.
Just like described in the docs

> Note that error boundaries only catch errors in the components below them in the tree. An error boundary can’t catch an error within itself. If an error boundary fails trying to render the error message, the error will propagate to the closest error boundary above it. This, too, is similar to how catch {} block works in JavaScript.

**Comment by eps1lon** [comment]
Closing since this was answered by @vkatatab in https://github.com/facebook/react/issues/21189#issuecomment-815688422:


> I may misunderstood the documentation or your problem.
> But, it seems to be that your error boundary is throwing an error and it will not caught it by itself.
> Just like described in the docs
> 
> > Note that error boundaries only catch errors in the components below them in the tree. An error boundary can’t catch an error within itself. If an error boundary fails trying to render the error message, the error will propagate to the closest error boundary above it. This, too, is similar to how catch {} block works in JavaScript.

**Comment by subhero24** [comment]
It is not the error boundary itself that throws the error, but the child component <B />. So it should catch that error i would think.

**Comment by eps1lon** [comment]
> It is not the error boundary itself that throws the error, but the child component `<B />`. So it should catch that error i would think.

I can see how the documentation isn't very explicit here but it's implied by "an error boundary behaves like try {} catch {}".

Imagine in JS 
```js
try {
  renderB()
} catch {
  renderB();
}
```
`renderB` wouldn't be caught be the `try-catch` block. What's more problematic is that this would cause an infinite loop in React. Seems to me you want to fallback to the parent error boundary or crash immediately since that'll happen anyway due to infinite loops.

**Comment by subhero24** [comment]
As the component `<B />` would throw a different error, it would not cause an infinite loop in my case. The suggestion to have another error boundary above it, was something I tried and that also did not seem to work. Will try to create a codesandbox example to verify this.
