### ISSUE TITLE
Community creation

### ISSUE THREAD

**Issue by gustavochermout** [facebook/react#21190]
Hello, I would like to know if I need any authorization from facebook or anyone can create a new community to discuss react topics, be it creating a website, using discord, instagram posts, podcasts...

In the issue #12570, it was said that the React logo is licensed under **Creative Commons Attribution 4.0**. Therefore, I am in doubt as to whether I can use it as logo of community due to the license's trademark restrictions.

Thanks! :)

**Comment by markerikson** [comment]
FWIW, the CCA 4.0 license is pretty clear that you can use logos and trademarks and stuff, you just need to mention where they came from.

**Comment by gustavochermout** [comment]
Hello, thank you very much for the reply. I really don't understand much about CCA 4.0, I was in doubt because of this part: _"Patent and trademark rights are not licensed under this Public License."_.

**Comment by JoelMarcey** [comment]
cc @caabernathy

**Comment by eps1lon** [comment]
This is mostly a legal issue that is better asked in forums with legal experts.
