### ISSUE TITLE
Bug: Input type range 

### ISSUE THREAD

**Issue by rgbskills** [facebook/react#21219]
React version: 17.0.1

## Steps To Reproduce

1. create a new input type range
2. set the value via state once it mounts (I used hook useEffect)
3. input type range will not trigger onChange event when the value changes by an effect.

Link to code example: https://codesandbox.io/s/peaceful-lumiere-y9kvl?file=/src/App.js

## The current behavior
The value of the range input gets updated but the onChange event is not triggered 

## The expected behavior
The value of input type range gets updated and onChange event gets triggered

**Comment by eps1lon** [comment]
Thanks for the report.

This behavior follows that of any input-like element (e.g. `select` or `textarea` or `input[type="text"]` etc). The `onChange` event is only dispatched in response to a change by user-input not change of the `value` prop.

**Comment by rgbskills** [comment]
So onChange only gets triggered by user events?

**Comment by eps1lon** [comment]
> So onChange only gets triggered by user events?

Basically, yes.

**Comment by rgbskills** [comment]
Thank you @eps1lon, I will now close this ticket.
