### ISSUE TITLE
Bug:  The new version of Create-React-App contains a bug

### ISSUE THREAD

**Issue by Jassi10000** [facebook/react#21217]
React version:
The version of Create-React-App am using is 4.0.2

## Steps To Reproduce

1.  Install the node modules using  " npm install " 
2. Run the application using " npm start "

Link to code example:

## The current behavior
The current behaviour can be best understood with this screenshot
![doutbt1](https://user-images.githubusercontent.com/64856348/114140407-d6210b80-992d-11eb-90e3-ec05dbaeae12.PNG)

## The expected behavior
I was expecting it to run smoothly by starting my react app on localhost:3000

**Comment by eps1lon** [comment]
Thanks for the report.

This repository is only concerned with `react` library packages. For `create-react-app` you want to [file an issue again facebook/create-react-app](https://github.com/facebook/create-react-app/issues/new/choose).

Make sure to fill out their issue template when filing your bug report.

**Comment by Jassi10000** [comment]
@eps1lon Ohh , thanks for informing sir
