### ISSUE TITLE
Shorthand for props

### ISSUE THREAD

**Issue by behnammodi** [facebook/react#21236]
Can we have a shorthand for props? 
sometimes variable name and prop name is same like:

```jsx
<Component name={name} />
```

So we can write shorthand mode:
```jsx
<Component {name} />
```

**Comment by bvaughn** [comment]
Shorthand attribute proposals have come up before: #9696, #9707, #13967, #15731, #20164, #

They get re-routed to the JSX repo, specifically: https://github.com/facebook/jsx/issues/23

**Comment by behnammodi** [comment]
@bvaughn Thanks man 👍🏻
