### ISSUE TITLE
Bug: element with same key in nested array does not re-render properly

### ISSUE THREAD

**Issue by jwoo0122** [facebook/react#21234]
React version: 17.0.2

## Steps To Reproduce

1. Make nested array element like this. All element have unique, fixed key.
```
[Element0, [Element1, Element2]]
```
2. Change the element array.
```
[Element1, Element2]
```
3. Key of element 1 and 2 aren't changed, but the elements are re-mounted.

This is not a problem if element 1 and 2 aren't in nested array.

```
[Element0, Element1, Element2]

-> [Element1, Element2]
```

Link to code example: https://github.com/jwoo0122/nested-child

Clone this repo, open dev tools and see console. In App.js, I made some scenarios to test this behavior.

## The current behavior
The element with same key always unmount, if they are in nested array.

## The expected behavior
I have no idea whether this behavior is intended or kind of bug. But I expected that element have same key in same array (also in nested array) do not re-mount, just re-render. Please feedback if my expectation is not correct. Thank you.

**Comment by jwoo0122** [comment]
In 'Reconciliation' docs it said "you can express the fact that a subtree has been moved amongst its siblings, but you cannot tell that it has moved somewhere else" by using key. Maybe this is the case of "moved somewhere else"...

**Comment by eps1lon** [comment]
You might be interested in https://github.com/facebook/react/issues/3965 which is essentially the same problem.

**Comment by jwoo0122** [comment]
Should I close this issue? It seems duplicate of the issue @eps1lon mentioned.

**Comment by eps1lon** [comment]
> Should I close this issue? It seems duplicate of the issue @eps1lon mentioned.

Thanks for the confirmation. I didn't want to close without a response from you.
