### ISSUE TITLE
Feature request: unmounting flag in useEffect cleanup

### ISSUE THREAD

**Issue by KarelHrkal** [facebook/react#21240]
Would it be possible to add a boolean argument to the useEffect cleanup method that would indicate wheter or not the cleanup was triggered because of dependency changing or because of the component unmounting?

Example:
```
useEffect(() => {
  const cancelSource = Axios.CancelToken.source();
  // ... queue request using the id and cancelSource.token
  return (isUnmounting) => cancelSource.cancel('cancelled because ' + (isUnmounting ? 'component is unmounting' : 'dependency changed'));
}, [id]);
```

**Comment by bvaughn** [comment]
Can you elaborate on how this value would be helpful?

**Comment by KarelHrkal** [comment]
> Can you elaborate on how this value would be helpful?

For example, I could add a reason why an API call is being cancel, so I can debug more easily if I know whether or not the cancellation was because the dependency on the hook changed or be because the component is unmounting.

**Comment by bvaughn** [comment]
Why is that detail important though?

FWIW I think this can be done in user space using a ref and a timeout:
```js
const prevCountRef = useRef(null);

useEffect(() => {
  prevCountRef.current = count;

  return () => {
    setTimeout(() => {
      const didUnmountOrHide = prevCountRef.current === count;

      // ...
    }, 0);
  };
}, [count]);

```

Here is a Code Sandbox demo:
https://codesandbox.io/s/determined-haze-xine7?file=/src/App.js

The above code snippet relies on the fact that React _synchronously_ creates new effects after it destroys previous ones. In the event that a component is updated, the ref will be (synchronously) updated by the new effect creation before the delayed function is run. But if a component is unmounted or hidden, it won't be. (If this sequence/timing changes in the future within React then the example above might not work.)

**Comment by KarelHrkal** [comment]
> Why is that detail important though?

Mostly for debugging, probably. Yes, there are ways to work around this, as you showed, but they are very hacky (additional refs, setTimeout, etc ...), not to mention less efficient, so a code like this only to get a different cancel message so that you can more easily find a problem is an overkill to say the least.

One situation where this *might* be useful if there are several useEffects with different dependencies, each needs to clean up after itself, but one "global" useEffect that cleans everything on unmount. But even then, it is probably better to have each individual effect clean after itself even on unmount and not have the global one - after all, that's how the useEffect hook was designed and it works very well.

As I said, I would probably only use this for debugging, so it is not a big deal.

The only reason why I wrote this suggestion is because I think this would be simple to implement, since the "unmount" code that calls the cleanups is a different code than the code that checks if the dependency changes, so you likely have 2 different invocations of the cleanup method, and you can simply add true argument to one and false to the other - no need to complexly check if it is an unmount or not, like you need when you are using the hook without the flag.

Lastly, this is how I would do it if absolutely needed without the flag:

```typescript
const isUnmountingRef = useRef(false);
useEffect(() => () => isUnmountingRef.current = true, []);

useEffect(() => {
  // free to use isUnmountingRef.current ...
}, [id]);
```

This is not only shorter, but doesn't rely on the hacky setTimeout. For example, what if you have component A that renders B, and B has this useEffect. If state in A changes, it will re-render B, but what if that re-render causes state change in A (let's say that A passes a setState function to B, and B calls it in useEffect), and that change in A's state causes B to get unmounted. You will then get 1 re-render of B and an unmounting of B, both possibly "in the same execution context" ... can you gurantee that the setTimeout will not queue both of those cleanup function after both of those executions? I guess setState will queue the update at the end of the event queue, same as useEffect, so that shouldn't happens, but I'm not that great of an expert when it comes to react (or JS for that matter) to know wheter or not that is the case.

**Comment by bvaughn** [comment]
I don't think I agree that it's "overkill" 😄 since the use case is uncommon and primarily for debugging. You could always wrap it up in a custom hook too, if you'd prefer.

> But even then, it is probably better to have each individual effect clean after itself even on unmount and not have the global one

Yes. Effects should, ideally, be encapsulated and not depend on other effects.

I'm going to close this issue for now. I don't have anything to add to the discussion at this point, and I think this is a change we're unlikely to make.
