### ISSUE TITLE
Too many re-rendering break ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by taddei** [facebook/react#2126]
I have prepared a fiddle to reproduce the bug.
http://jsfiddle.net/taddei/8ztqgd28/

If you try grabbing the range input and slide it fast from left to right at a certain point the list breaks. Some DOM nodes are left and forgotten in the DOM and never removed.

I also noticed that there is a "magic number" to this bug. In the case you reduce the "max" value to less than 10 elements, this bug doesn't happen.

**Comment by spicyj** [comment]
This sounds like #1326.
