### ISSUE TITLE
Discussion: useTransition does not perform well in certain scenarios

### ISSUE THREAD

**Issue by careyke** [facebook/react#21263]
React version: 0.0.0-experimental-4ead6b530

# useTransition use in switch tabs
In this case, useTransition performs well. 

## Steps To Reproduce

1. click the button

Link to code example:https://codesandbox.io/s/usetransition-switchtab-7xgxi?file=/src/App.js

## The current behavior
when the lazy features is wrapped by <Suspense>, switch the tab, the transition time does not include the request time of the lazy features

## The expected behavior
when the lazy features is wrapped by <Suspense>, switch the tab, the transition time does not include the request time of the lazy features

# useTransition use in switch API
In this case, useTransition does not  performs well. 

## Steps To Reproduce

1. click the button

Link to code example:https://codesandbox.io/s/usetransition-switchapi-ficp5?file=/src/App.js

## The current behavior
when the lazy features is wrapped by <Suspense>, switch the tab, the transition time  includes the request time of the lazy features

## The expected behavior
when the lazy features is wrapped by <Suspense>, switch the tab, the transition time does not include the request time of the lazy features. I think it should perform same as above

**Comment by gaearon** [comment]
Any reason you closed? I haven’t looked in detail yet.
