### ISSUE TITLE
Error: Invalid hook call.

### ISSUE THREAD

**Issue by laflamablanc** [facebook/react#21290]
I am receiving the Error: Invalid hook call message when trying to call useState inside of a functional component that is using react-redux. It was working fine before I added the mapDispatchToProps and connect functions.

Here is the code:

```js
import React, {useState} from 'react'
import {connect} from 'react-redux'
import {createProject} from '../../store/actions/projectActions'

const CreateProject = (props) => {

    const [title, setTitle] = useState("")
    const [content, setContent] = useState("")

    const handleSubmit = (e) => {
        e.preventDefault()
        props.createProject({
            title: title,
            content: content
        })
        setTitle("")
        setContent("")
    }
    
    const handleChange = (e) => {
        if (e.target.id === "title"){
            setTitle(e.target.value)
        } else {
            setContent(e.target.value)
        }
    }

    return (
       <div className="container">
           <form onSubmit = {handleSubmit} action="" className="white">
                <h4 className="grey-text text-darken-3">Create New Project</h4>
                <div className="input-field">
                   <label htmlFor="title">Title</label>
                   <input type="text" id="title" onChange={handleChange}/>
                </div>
                <div className="input-field">
                   <label htmlFor="content">Project Content</label>
                   <textarea onChange = {handleChange} id ="content" className = "materialize-textarea"></textarea>
                </div>
                <div className="input-field">
                    <input type="submit" id ="submit"/>
                </div>
            </form>
        </div>
    )
}

const mdp = (dispatch) => {
    return {
        createProject: (project) => dispatch(CreateProject(project))
    }
}

export default connect(null, mdp)(CreateProject)
```

I tried checking for 2 different Reacts, but the console log return 'true' confirming they are the same.
I also tried all of the steps in the suggested fix page. 

 
**Edited by @bvaughn to fix formatting.**

**Comment by bvaughn** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment]
You are calling `CreateProject` like a function on this line:
```js
createProject: (project) => dispatch(CreateProject(project))
```

Hooks can't be called from regular JavaScript functions. They have to be rendered by React. (You should create elements from them via `createElement(CreateProject)` or `<CreateProject>`. React has to be the thing to render them.)

**Comment by laflamablanc** [comment]
Ah I see thanks
