### ISSUE TITLE
Error: "Commit tree does not contain fiber 834. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by nikodunk** [facebook/react#21295]
Describe what you were doing when the bug occurred:
1. Hit start recording
2. Hit stop recording

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.11.0-39713716aa

Component stack: CommitFlamegraphAutoSizer@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:35445:34
div
div
div
SettingsModalContextController@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:29120:40
Profiler_Profiler@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:37243:34
ErrorBoundary_ErrorBoundary@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:30035:5
PortaledContent@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:30156:34
div
div
ProfilerContextController@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:34263:35
TreeContextController@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:25355:31
SettingsContextController@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:25962:35
ModalDialogContextController@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:30299:38
DevTools_DevTools@moz-extension://6d942b3a-5f72-804d-a41e-48420d7d053f/build/main.js:37638:27

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#20431) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
