### ISSUE TITLE
Bug: Component inside `<option>` is rendered as `[object Object]` without issuing a warning

### ISSUE THREAD

**Issue by Minnozz** [facebook/react#21298]
React version: 17.0.2

## Steps To Reproduce

1. Nest a component inside an `<option>` tag

Link to code example: https://codesandbox.io/s/component-inside-option-b1j8s?file=/src/App.js

## The current behavior

The value of the component is rendered as `[object Object]` without issuing a warning in the console.

## The expected behavior

Preferably: The value of the component is shown instead of `[object Object]`. See also #13586.

Alternatively: Issue a warning in the console, like when nesting a `<span>` inside an `<option>` tag:
```
Warning: Only strings and numbers are supported as <option> children.
```

In the linked code example, this warning is issued for the `<span>`, but not the `<Comp>`.

**Comment by bvaughn** [comment]
Since you linked to #13586, I'll mention this comment in particular by @gaearon https://github.com/facebook/react/issues/13586#issuecomment-419492970 which says:
> If you use something else, just make what you're passing to `<option>` as a child is actually a string: https://codesandbox.io/s/oom712ov79

This behavior has not changed between 16 and 17.

Admittedly perhaps we could add an additional DEV warning for this case, since it seems like we only do this for host components (e.g. `<span>`).

**Comment by ShahirZain** [comment]
this will work like this, you call a function as a component . . . and one thing you passed an element inside option tag. .  option tag work on a single value . .  if you pass any other tag it will behave not as expected. ..  chill



![image](https://user-images.githubusercontent.com/30791669/121538353-28f66c80-ca1e-11eb-8046-b15bdde624e4.png)

**Comment by gaearon** [comment]
FWIW we fixed this whole thing in React 18 alpha.
It works again.

https://codesandbox.io/s/component-inside-option-forked-gk1yd

**Comment by gaearon** [comment]
React 18 is out with the fix: https://github.com/facebook/react/issues/13586#issuecomment-1082505635
