### ISSUE TITLE
Bug: createBlockingRoot doesn't exist on react-dom@0.0.0-experimental-af1a4cbf7

### ISSUE THREAD

**Issue by natew** [facebook/react#21316]
React version: 0.0.0-experimental-af1a4cbf7

Pretty simple, seems to just be missing entirely. Searching around I don't see any obvious commits or even tweets/notes on this, but the docs on the live site indicate it exists.

**Comment by eps1lon** [comment]
`unstable_createBlockingRoot` was removed in https://github.com/facebook/react/pull/20974.

Removing the mention from the docs entirely might be confusing. A note about it under https://reactjs.org/docs/concurrent-mode-reference.html#createblockingroot should work. Though I don't know if the core team intends to write something about the reasoing or if "it was removed" is sufficient. Maybe @rickhanlonii has an opinion about it.

**Comment by bvaughn** [comment]
`createBlockingRoot` was an unstable API that we determined was not necessary for a stable release. The [docs in question](https://reactjs.org/docs/concurrent-mode-reference.html#createblockingroot) do mention right at the top that all APIs are experimental and unstable.
![Screen Shot 2021-04-19 at 4 24 41 PM](https://user-images.githubusercontent.com/29597/115298672-c377b500-a12b-11eb-9485-708ef089a25e.png)

We will have stable docs for the final/stable API by the time we release it to the stable NPM channel though 😄
