### ISSUE TITLE
React Context API in npm library not working

### ISSUE THREAD

**Issue by iMinosGFX** [facebook/react#21312]
I have created a Server side table component which is quite complex and to manage the interactions with the filters I have used a context provider which encompasses the whole component. During the development on a test project I didn't have any problem, only after building it to make a library with rollup I had some problems, especially this one.

When importing the library in my main project, nothing works because the state of the context retrieved by the children is always empty. 
Searching on internet I have the impression that it is a problem of context conflicts, but trying several solutions nothing works... 

Here is the state of the context in the react dev tools :

![Screenshot_2](https://user-images.githubusercontent.com/35743637/115213341-b6de6700-a101-11eb-957d-e5e4efaad986.png)

and here is the state retrieved by the children:  
![Screenshot_3](https://user-images.githubusercontent.com/35743637/115213387-be9e0b80-a101-11eb-9639-213e75ff9cc6.png)

React version: 16.12.0

## Steps To Reproduce

1. You can find my answer here, the main component being ServerSideTable :  https://github.com/iMinosGFX/react-server-side-table
2. I don't know if showing you a particular piece of code will be useful, in my opinion it's a configuration problem because the state is not accessible no matter the child and the action called, but I use useContext in several children (e.g. itemFilter) and the error occurs every time I try to access a state property

Link to code example:

https://github.com/iMinosGFX/react-server-side-table

**Comment by medmin** [comment]
For the record, I am having the same issue.

I can use rollup or webpack to build a react component library. It builds and compiles. But when it's imported in a react project, the console has "createContext" is not a function, or other weird error.

But if I remove the context, and just render a simple component, say, a button, it builds and compiles. And it can be imported in a react project and it works fine.

I really don't know why. And I have no clue.

**Comment by AdonisinodA** [comment]
I solved this problem using event custom

**Comment by yashsharma04** [comment]
Did anyone find a solution to this? I have the same problem where child package doesn't get the context but only on localhost build. In remote build it works just fine.
