### ISSUE TITLE
Double-clicking repeatedly only fires `onDoubleClick` event once

### ISSUE THREAD

**Issue by mjadobson** [facebook/react#2132]
When using the onDoubleClick event, double-clicking repeatedly only fires the event once.

Because the throttling is quite generous, the sequence of: double-click -> short pause -> double-click, produces the unexpected effect of the second double-click not triggering.

I have created a demo of this, as well as a quick example of a non-throttled double-click:

http://jsbin.com/xawukefasuro/1/edit

**Comment by binarykitchen** [comment]
So, is React not having support for `onDoubleClick`?

**Comment by syranide** [comment]
@binarykitchen It should work just as fine and as intended.

**Comment by binarykitchen** [comment]
@syranide My bad, I was referring to React's fixed-data-table which does not support it yet.
