### ISSUE TITLE
Bug: v16.14.0 tag is incorrectly shows

### ISSUE THREAD

**Issue by akiraplusplus** [facebook/react#21339]
The tag on GitHub does not match the version of the package:

https://github.com/facebook/react/blob/v16.14.0/packages/react-test-renderer/package.json

This is v16.14.0, but the package is of version 17.0.0-alpha.0.

**Comment by gaearon** [comment]
We get this issue every one in a while... The actual version numbers on npm are set automatically by a release script. You can ignore the version number that's committed.
