### ISSUE TITLE
Rename dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by syranide** [facebook/react#2134]
From #1515, thoughts?

`dangerousInnerHTML`, `unsafeInnerHTML`, (`disasterousInnerHTML` :)) or something else? (I prefer the sound of `dangerous`)

It also makes sense to add a `dangerousDefaultInnerHTML` (`default` is the word we use elsewhere) which could be very useful for content-editables to avoid "hacks", etc.

cc @sebmarkbage @zpao

**Comment by aweary** [comment]
No movement on this in the last couple years. I'm not sure it'd be worth the API churn, and it doesn't seem like a frequently-requested change. What do you think @gaearon @nhunzaker? If we wanted to make this change, it might be worth doing in the next major release.

**Comment by gaearon** [comment]
Let’s close for inactivity. We can come back to this if it organically comes up again but I don’t think this has a high priority.
