### ISSUE TITLE
Bug: ESLint: Cannot read property 'type' of undefined Occurred while linting

### ISSUE THREAD

**Issue by LeonardoRick** [facebook/react#21342]
React version:
17.0.2

eslint-plugin-react-hooks version:
4.2.0

## Steps To Reproduce

1. import useEfect from react library
2. type `useEfect(`

Link to code example:
https://github.com/LeonardoRick/podcastr

## The current behavior
![image](https://user-images.githubusercontent.com/17517057/115921727-4792ab00-a452-11eb-8b46-82b43dcd5600.png)

output:

```bash
[Error - 16:40:28] ESLint stack trace:
[Error - 16:40:28] TypeError: Cannot read property 'type' of undefined
Occurred while linting D:\GIT\podcastr\src\Components\Player\index.tsx:16
    at visitCallExpression (D:\GIT\podcastr\node_modules\eslint-plugin-react-hooks\cjs\eslint-plugin-react-hooks.development.js:1736:24)
    at D:\GIT\podcastr\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\GIT\podcastr\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\GIT\podcastr\node_modules\eslint\lib\linter\node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (D:\GIT\podcastr\node_modules\eslint\lib\linter\node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (D:\GIT\podcastr\node_modules\eslint\lib\linter\node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (D:\GIT\podcastr\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
    at D:\GIT\podcastr\node_modules\eslint\lib\linter\linter.js:954:32
    at Array.forEach (<anonymous>)
```

error line:
```javascript
      // eslint-plugin-react-hooks\cjs\eslint-plugin-react-hooks.development.js:1736:24:
      switch (callback.type) {
```

## The expected behavior
No errors showing, since I'm currently typing the code

**Comment by gaearon** [comment]
Add an exact reproducing file, please?

**Comment by LeonardoRick** [comment]
reproducing file:

```react
import { useEffect } from "react";

export default function Test(): JSX.Element {
  useEffect();
  return (
    <h1>Hello world</h1>
  );
}
```

**Comment by gaearon** [comment]
Could you try turning this into a test case in https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js?

**Comment by gaearon** [comment]
This test case seems to imply that it should work. https://github.com/facebook/react/blob/9cd52b27fe7be3c320d1e94a016fc416e66569b1/packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js#L1696-L1698

**Comment by eps1lon** [comment]
Duplicate of https://github.com/facebook/react/issues/20343 which was fixed in https://github.com/facebook/react/pull/20385 3 months ago.

The last release of `eslint-plugin-react-hooks` was 6 months ago though.

**Comment by LeonardoRick** [comment]
Ops, sorry about that. I taught it wasn't duplicate because that one was closed and the error persisted. I'll wait the update. Thanks @eps1lon

**Comment by bonnie** [comment]
I am also seeing this exact issue (see https://github.com/eslint/eslint/issues/14554 ; they advised me to file an issue here). I will try to turn it into a test case as suggested by @gaearon , and I will open a new issue if I'm able to produce results.
