### ISSUE TITLE
Bug: Combining Context.Provider and React.memo prevent updates

### ISSUE THREAD

**Issue by Mickeygogo** [facebook/react#21350]
> 就是我使用多层context.Provider 包裹的组件的子组件如果都是用了memo进行包装，那么是否渲染的高亮将不再有用

[Translated](https://translate.google.com/?sl=auto&tl=en&text=%E5%B0%B1%E6%98%AF%E6%88%91%E4%BD%BF%E7%94%A8%E5%A4%9A%E5%B1%82context.Provider%20%E5%8C%85%E8%A3%B9%E7%9A%84%E7%BB%84%E4%BB%B6%E7%9A%84%E5%AD%90%E7%BB%84%E4%BB%B6%E5%A6%82%E6%9E%9C%E9%83%BD%E6%98%AF%E7%94%A8%E4%BA%86memo%E8%BF%9B%E8%A1%8C%E5%8C%85%E8%A3%85%EF%BC%8C%E9%82%A3%E4%B9%88%E6%98%AF%E5%90%A6%E6%B8%B2%E6%9F%93%E7%9A%84%E9%AB%98%E4%BA%AE%E5%B0%86%E4%B8%8D%E5%86%8D%E6%9C%89%E7%94%A8&op=translate): That is, if the sub-components of the components that I use multi-layer context.Provider package are all packaged with memo, then the highlight of whether the rendering will no longer be useful

```js
<context1.Provider>
  <context2.Provider>
    <A />
  </context2.Provider>
</context1.Provider>;

const A = memo(() => {
  rerurn(
    <>
      <B />
      <C />
    </>
  );
});

const B = memo(() => {...});
const C = memo(() => {...});
```
> 类似这样的写法，工具中的渲染高亮 将没有效果了

[Translated](https://translate.google.com/?sl=auto&tl=en&text=%20%E7%B1%BB%E4%BC%BC%E8%BF%99%E6%A0%B7%E7%9A%84%E5%86%99%E6%B3%95%EF%BC%8C%E5%B7%A5%E5%85%B7%E4%B8%AD%E7%9A%84%E6%B8%B2%E6%9F%93%E9%AB%98%E4%BA%AE%20%E5%B0%86%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C%E4%BA%86&op=translate): Writing like this, the rendering highlight in the tool will have no effect

**Edited** by @bvaughn for formatting and to add translations.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment]
@Mickeygogo: 很难理解。
请使用 [Code Sandbox](https://react.new/) 为我们创建一个副本

**Comment by crapthings** [comment]
i think this might not what he want, but still kind of weird to me

https://codepen.io/crapthings/pen/RwKvzpE

**Comment by Mickeygogo** [comment]
https://codesandbox.io/s/staging-star-bgo6h?file=/src/App.js
很抱歉，昨天很忙没时间回复您。
我这边已经在codesandbox 写好了，具体内容就是：加完memo的组件，在（Highlight updates when components render.）不再会有绿色的高亮展示了


I am sorry that I was too busy to reply you yesterday.
When you add the memo components, you will no longer have green highlights in (Highlight Updates When Components Render.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/react"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 晚上10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/react] 我在使用工具中发现一个BUG,是关于渲染高亮提示的 (#21350)





 
@Mickeygogo: 很难理解。
 请使用 Code Sandbox 为我们创建一个副本

**Comment by FunkySamuel37** [comment]
I guess @Mickeygogo means React DevTools didn't highlight updates in Codepen's iframe.
Follow below, then check in React DevTools,
![image](https://user-images.githubusercontent.com/11454137/116026297-fb7b7c80-a684-11eb-8e6e-ec8f3eae1199.png)

**Comment by Mickeygogo** [comment]
yes
我点击的是button 然后显示18的那一行的渲染高亮提示并没有。
I hit button and the render highlighting on the line that says 18 is not there.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/react"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/react] Bug: Combining Context.Provider and React.memo prevent updates (#21350)





 
I guess @Mickeygogo means React DevTools didn't highlight updates in Codepen's iframe.
 Follow below, then check in React DevTools,

**Comment by bvaughn** [comment]
@Mickeygogo 我不明白...看起来不错？

![Kapture 2021-04-26 at 09 07 24](https://user-images.githubusercontent.com/29597/116087449-dc71f000-a66e-11eb-8d07-e02b5cf8499c.gif)

**Comment by Mickeygogo** [comment]
数字变动的那一行不应该会有绿色的高亮提示吗？你可以去掉DIV1，DIV2的memo，你在对比一下
Shouldn't there be a green highlight on the line where the number changes? You can remove the memo from DIV1, DIV2, and you can compare
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/react"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 晚上9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/react] Bug: Combining Context.Provider and React.memo prevent updates (#21350)





 
@Mickeygogo 我不明白...看起来不错？

**Comment by bvaughn** [comment]
@Mickeygogo: 我看不出有什么不同 没有 `memo`

请使用 [Code Sandbox](https://react.new/) 为我们创建一个副本

I didn't see any difference when comparing with and without `memo`. Can you share a Code Sandbox that shows the difference?

**Comment by Mickeygogo** [comment]
今天太晚了，我明天给你发过去



发自我的iPhone


------------------ Original ------------------
From: Brian Vaughn ***@***.***&gt;
Date: Mon,Apr 26,2021 10:32 PM
To: facebook/react ***@***.***&gt;
Cc: Mickeygogo ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [facebook/react] Bug: Combining Context.Provider and React.memo prevent updates (#21350)

**Comment by bvaughn** [comment]
Closing because there isn't enough info.
