### ISSUE TITLE
Whitespace in option element before property variable triggers "Invariant Violation"

### ISSUE THREAD

**Issue by isaacbernat** [facebook/react#2136]
[Here is a minimal example that triggers the error](http://jsbin.com/fozabubiruna/5/edit). Removing the whitespace before `key` (from `Options.push(<option> {key}</option>)` to `Options.push(<option>{key}</option>)` makes it work.

I attach a couple of screenshots of the contents of `Options` in `console.log(Options)`:
With whitespace (which triggers the error).
![screen shot 2014-09-03 at 4 05 43 pm](https://cloud.githubusercontent.com/assets/2509809/4135381/63837286-3375-11e4-8022-c3cc661446a9.png)
Without whitespace (works fine).
![screen shot 2014-09-03 at 4 06 05 pm](https://cloud.githubusercontent.com/assets/2509809/4135394/80fcd8c0-3375-11e4-9fd1-e2bdcee714d0.png)

**Comment by scvnc** [comment]
Possibly related example: https://gist.github.com/scvnc/ab4845897a738d979995

I too was having Invariant Violation errors and sometimes strange re-rendering behavior until I discovered these added whitespace children.  My experience specifically was in a table row `<tr> {tds} </tr>` and not `<option>`

JSX bug or something to add to the [JSX Gotchas](http://facebook.github.io/react/docs/jsx-gotchas.html)?

**Comment by greggawatt** [comment]
Is this still an active issue?

**Comment by jimfb** [comment]
I think this has been fixed (my jsfiddle: http://jsfiddle.net/ve84suby/).  Closing.  We can re-open if someone can reproduce with a fiddle in 0.14.
