### ISSUE TITLE
Bug: DevTools Component panel wrong size

### ISSUE THREAD

**Issue by Velenir** [facebook/react#21366]
The Component panel in React DevTools is wrongly sized

React version: any version, on any website
Only in Chrome 92.0.4484.7 (Official Build) dev (64-bit) browser
In Chromium 92.0.4480.0 (Developer Build) (64-bit) and in Firefox all ok

## Steps To Reproduce

1.  On any site that uses React, open React DevTools
2. Component panel is sized very narrow

## The current behavior
![image](https://user-images.githubusercontent.com/5121491/116272496-9f4e5080-a789-11eb-893f-b4e7c54c2f66.png)
![image](https://user-images.githubusercontent.com/5121491/116272925-ffdd8d80-a789-11eb-81b1-5572561ec3e6.png)

It looks to me like something broke inside `AutoSizerWrapper`

**Comment by bvaughn** [comment]
This looks like a Chrome bug, maybe?

It's okay in Chrome 90.0.4430.8 (latest stable) and in Chromium. The version of Chrome you're referring to (92.0.4484.7) is not even a beta release yet (91 was just released as beta).

**Comment by Velenir** [comment]
Yes, looks like a bug in dev version of Chrome
I should stop living on the edge 😞

**Comment by bvaughn** [comment]
No worries :)

I'd suggest reporting this to Chrome! Going to close the issue here though since (I don't think) it's anything React DevTools has to fix or change.
