### ISSUE TITLE
Bug: The digital precision in Style Object is lost.

### ISSUE THREAD

**Issue by proYang** [facebook/react#21376]
React version:
  v17.0.2
## Steps To Reproduce

```javascript
class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
    	scaleX: 1/3
    }
  }
  
  render() {
    const { scaleX } = this.state;
    return (
      <div
        className='box'
        data-scaleX={scaleX}
        style={{
      	  transform: `scaleX(${scaleX})`
        }}
       >
         {scaleX}
       </div>
    )
  }
}
```

Link to code example:

https://jsfiddle.net/slaneyang/cduvptLh/

## The current behavior
![image](https://user-images.githubusercontent.com/16184782/116409482-7780ea80-a866-11eb-80c3-3ecbc670fb8f.png)

## The expected behavior
![image](https://user-images.githubusercontent.com/16184782/116409585-92535f00-a866-11eb-9616-a3db697b9f4d.png)

**In this example, the precision of scaleX is lost.**

**Comment by Gautam-Arora24** [comment]
Can I work on this issue, if no one is working in it?

**Comment by nmain** [comment]
I have no idea what is going on here, except that it's not at all React related.  Using the devtools console, you can see the same thing with raw DOM access, even on a page without React at all:

```
$0.style.transform = `scaleX(${1/3})`
> "scaleX(0.3333333333333333)"
$0.style.transform
> "scaleX(0.333333)"
```

**Comment by gaearon** [comment]
This is how regular browser DOM works.
