### ISSUE TITLE
[react-devtools-extensions] "Reload and start profiling" button is missing on non-Chrome browsers

### ISSUE THREAD

**Issue by MasterEric** [facebook/react#21384]
React version: v17.0.1

## Steps To Reproduce

1. Open the React Developer Tools extension on Chrome and navigate to the Profiler tab. Note the presence of the "Reload and start profiling" button.
2. Open the React Developer Tools extension on Firefox and navigate to the Profiler tab. Note the absence of this button.

## The current behavior
The button is currently not present on Firefox.

## The expected behavior
The button should be present and function as expected on Firefox.

## Notes
It is frustrating and un-intuitive that certain browsers lack useful functionality. As it stands, I cannot diagnose lag that appears when starting up a React app on Firefox.

I see that [there is code to explicitly disable the button on certain platforms](https://github.com/facebook/react/blob/master/packages/react-devtools-extensions/src/main.js#L140). In order for this issue to be resolved, the required functionality must be reproduced on other platforms.

**Comment by bvaughn** [comment]
This is not a bug. The browser APIs required to support this functionality are not available in FIrefox. There is not, to my knowledge, any way to work around this issue.

**Comment by MasterEric** [comment]
Hey @bvaughn, I apologize if I came off as frustrated earlier.

I have done some more thorough investigation into the app in order to determine the answers to the following:

* Exactly which Chrome APIs are present, which are absent in other browsers, that allow this feature to function?
* Is the Firefox developer team aware of this feature deficiency? An issue can be made on the [Bugzilla Feature tracker](https://bugzilla.mozilla.org/home), a link can be posted here, and this issue can be left open pending the implementation of the necessary APIs.

I did some more digging, and deduced the Reload and Start Profiling functionality is implemented in three parts:
* Make a note in local storage that the current page should be profiled the next time it loads.
* Use the Chrome DevTools API to trigger a page reload by referencing the inspected window and executing some JavaScript on it. This appears to be the API required to support this functionality.
* When the page loads, perform a check. If the aforementioned note is enabled, start profiling as the page is loading.

The following line is the one performing the actual reload functionality:

https://github.com/facebook/react/blob/3c21aa855a13707a8abe5dc6eaf2d2a7429fa762/packages/react-devtools-extensions/src/main.js#L105

After additional research, I found the following articles in the Firefox documentation, which indicates that the necessary APIs have already been implemented:
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/inspectedWindow
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools#limitations_of_the_devtools_apis

It appears that Firefox does contain the appropriate API to execute arbitrary JavaScript on the inspected window to reload the page (the limitation of Firefox is that the `options` argument is not currently supported, but this is not relevant to this application). As far as I can discern, the functionality to begin profiling as the page loads is not dependent on any browser-specific functionality.

Thus, I am under the impression that the required functionality should be supported in Firefox 55+ as well as Edge 79+. If I am missing something, please let me know.

**Comment by bvaughn** [comment]
> Use the Chrome DevTools API to trigger a page reload by referencing the inspected window and executing some JavaScript on it. This appears to be the API required to support this functionality.

No. The API/functionality that's [not supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/sync-xhr#browser_compatibility) is this:
https://github.com/facebook/react/blob/269dd6ec5da85fc5ca819cfa010ce60dd1c83ec6/packages/react-devtools-extensions/src/injectGlobalHook.js#L70-L87

This functionality isn't even always available on Chrome (see [`"sync-xhr"`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/sync-xhr) and #20879).

And it's something they've considered dropping support for (I've seen vague references to it online).

I spoken with Simeon (Chrome extensions dev rel) about this use case and he agreed that it was an acceptable solution, given the constraints.
