### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by taoszu** [facebook/react#21387]
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

React version:  17.0.2

## Steps To Reproduce
```
import "./styles.css";
import React from 'react'

export default class App extends React.Component {

  Parent = () => {
    /**
     * this will be ok
     * const Child = this.Child
     * return <Child />
     */
    return <this.Child />
  }

  Child = () => {
    return <div>child</div>
  }

  render() {
    return <this.Parent />
  }

}
```

Link to code example: [code example](https://codesandbox.io/s/function-components-error-qro61?file=/src/App.tsx)

## The current behavior
can not render the child component

**Comment by huntdream** [comment]
https://reactjs.org/docs/jsx-in-depth.html

**Comment by AbhishekGowda28** [comment]
@huntdream  what are you reffering in to in https://reactjs.org/docs/faq-internals.html related to the bug.

**Comment by gaearon** [comment]
This way of defining components is not supported and it's easy to get confused. Each component needs to be a top-level function (or a class) rather than a separate class method.
