### ISSUE TITLE
Bug: Cannot read property __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED of undefined

### ISSUE THREAD

**Issue by code913** [facebook/react#21390]
# I got this issue when using react in deno deploy, but i think it will still throw this error in nodejs

## Code: https://github.com/code913/react-ssr-deno

![what the heck is this tbh](https://user-images.githubusercontent.com/54856929/116580980-82ed1800-a931-11eb-8671-05cb0cde4dfc.png)

React version: 17.0.2 react-dom, react version latest

## Steps To Reproduce

1. Import react-dom from the umd production or development url (havent tested others): `https://cdnjs.cloudflare.com/ajax/libs/react-dom/17.0.2/umd/react-dom.development.min.js`
2. Try to hydrate some data from react-dom/server

**Comment by code913** [comment]
Oh btw if you wanna see this in action go here: https://react-ssr-deno-b539c876.deno.dev

**Comment by lucacasonato** [comment]
This issue is invalid. OP is not importing "react".

**Comment by bvaughn** [comment]
`__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` is a property of the React export. The error message indicates that React isn't being imported or bundled with the app you're referring to. The source code of the application you linked to includes:
```js
require("react")
```

Looking at your source though, you're only including react-dom:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/17.0.2/umd/react-dom.development.min.js" integrity="sha512-aNBFq6ue8EmNDwVD/l0mWFy3iVZLIxtQaD7fEYBn3HluJer36T1AhJK0THj6MKKfhZrexxWsKX1T16TxLZo6uQ==" crossorigin="anonymous"></script>
```
