### ISSUE TITLE
ACR/VPAT

### ISSUE THREAD

**Issue by bobbybettinger** [facebook/react#21393]
Is there an ACR/VPAT for react developer tools?

https://www.itic.org/policy/accessibility/vpat

**Comment by bvaughn** [comment]
@bobbybettinger No. I'm not that familiar with VPAT beyond the basics. Is it something that browser extensions would typically get? How frequently?

**Comment by bvaughn** [comment]
Since the original question was answered and no additional info was provided, I'm going to close this issue.
