### ISSUE TITLE
Bug: useEffect happens synchronously when useLayoutEffect was called

### ISSUE THREAD

**Issue by just-boris** [facebook/react#21400]
React version: 17.0.2 (also tested on 16.9.0, same result)

## Steps To Reproduce

1. Open this codesandbox: https://0gobm.csb.app/ ([Source](https://codesandbox.io/s/smoosh-sun-0gobm?file=/src/index.js))
2. Try to click on the "Works" button
3. Dropdown opens
4. Try to click on the "Broken" button
5. Dropdown does not open

Link to code example:

https://0gobm.csb.app/

The issue is related to how `useEffect` calls are scheduled. We have this effect:

```js
  useEffect(() => {
    if (!open) {
      return;
    }
    const clickListener = (event) => {
      if (!dropdownRef.current.contains(event.target)) {
        onDropdownClose();
      }
    };

    window.addEventListener("click", clickListener);

    return () => {
      window.removeEventListener("click", clickListener);
    };
  }, [open, onDropdownClose]);
```

Normally, this effect happens asynchronously. However, sometimes, it is synchronous and we add listener to the `window` before the event fully bubbles and the dropdown gets closed by the same event.

This only happens if any underlying component contains `useLayoutEffect` with `setState` call (as shown on codesandbox). Looks like this causes forced render and this chain of events.

P.S. The report looks very similar to another one: https://github.com/facebook/react/issues/20074. However, I decided to open a new issue, because the circumstances are different (no portals in this case)

**Comment by bvaughn** [comment]
`useEffect` is only synchronously run when an update is scheduled from `useLayoutEffects`. Updates from within layout effects must be applied _synchronously_ (before paint) as that's the only point where users can e.g. tweak tooltip positions, dialog sizes, etc without the user seeing a flash of invalid content.

Unfortunately this is expected behavior, _but_ it also has a simple workaround: listen to the event during the capture phase.
```js
window.addEventListener("click", clickListener, true);
```

Alternately you could use a `setTimeout` to debounce when the "click" event is attached:
```js
useEffect(() => {
  // Delay until after the current call stack is empty,
  // in case this effect is being run while an event is currently bubbling.
  // In that case, we don't want to listen to the pre-existing event.
  let timeoutID = setTimeout(() => {
    timeoutID = null;

    // It's important to listen to the ownerDocument to support the browser extension.
    // Here we use portals to render individual tabs (e.g. Profiler),
    // and the root document might belong to a different window.
    window.addEventListener("click", clickListener);
  }, 0);

  return () => {
    if (timeoutID !== null) {
      clearTimeout(timeoutID);
    }

    window.removeEventListener("click", clickListener);
  };
}, []);
```

**Comment by baeharam** [comment]
@just-boris 

I saw your re-production and tested with React 18 which flushes synchronously `useEffect` when user triggers discrete events. But, "Works" version works well even though React 18 flushes it synchronously. 

If synchronous version of React <= 17 is broken, why synchronous version of React 18 isn't broken? Why it works well?
