### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by mahmoudraad** [facebook/react#21406]
hi, how resolve this error

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

React version: 16.13.1

## Steps To Reproduce

1.
2.

my  code :

### `ReviewForm.js`

```js
import { Formik } from "Formik";
import React from "react";
import { StyleSheet, Text, TextInput, View } from "react-native";

export default function myReviewForm() {
  return (
    <View style={styles.container}>
      <Formik
        initialValues={{ title: "", body: "", rating: "" }}
        onSubmit={(values) => {
          console.log(values);
        }}
      >
        {(props) => (
          <View>
            <TextInput
              style={styles.input}
              placeholder="ReviewTitle"
              onChangeText={props.handleChange("title")}
              values={props.values.title}
            ></TextInput>

            <TextInput
              style={styles.input}
              multiline
              placeholder="ReviewBody"
              onChangeText={props.handleChange("body")}
              values={props.values.body}
            ></TextInput>

            <TextInput
              style={styles.input}
              placeholder="ReviewRating"
              onChangeText={props.handleChange("rating")}
              values={props.values.rating}
            ></TextInput>

            <button
              title="Submit"
              color="marron"
              onPress={props.handleSubmit}
            ></button>
          </View>
        )}
      </Formik>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "green",
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    fontSize: 18,
  },
});
```

### `App.js`

```js
import React from "react";
import ReviewForm from "./Components/ReviewForm.js";
import { StyleSheet, Text, TextInput, View } from "react-native";

export default function App() {
  return <ReviewForm />;
}
```

**Edited** for formatting by @bvaughn.

**Comment by bvaughn** [comment]
What's the full error message (including the call stack)

**Comment by mahmoudraad** [comment]
![image](https://user-images.githubusercontent.com/83520704/116809827-dd13f600-ab48-11eb-822c-660d89ceedfe.png)

**Comment by bvaughn** [comment]
Can you paste the full stack? (23 stack frames were collapsed)

**Comment by mahmoudraad** [comment]
![image](https://user-images.githubusercontent.com/83520704/116818329-8b349580-ab73-11eb-89d5-7eb476b8d0b7.png)

**Comment by mahmoudraad** [comment]
![image](https://user-images.githubusercontent.com/83520704/116818350-9a1b4800-ab73-11eb-9ab5-8abf1ea5488c.png)

**Comment by bvaughn** [comment]
Seems like maybe 1 or 3 (in the error message) but it's hard to tell when all we have to look at is a screenshot of an error message.

**Comment by bvaughn** [comment]
@mahmoudraad I don't think we can do much with this bug report as it is currently. Can you share the actual code (so that we can run it and breakpoint the error)?

**Comment by stefanwuthrich** [comment]
I can not send code here, but I got the same error after updating react@17.0.2, react-dom@17.0.2 from 17.0.1

`
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    React 2
        resolveDispatcher
        useContext
    useHistory react-router.js:720
    LoginForm LoginForm.js:16
    React 12
        renderWithHooks
        mountIndeterminateComponent
        beginWork
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        beginWork$1
        performUnitOfWork
        workLoopSync
        renderRootSync
        performSyncWorkOnRoot
        flushSyncCallbackQueueImpl
    unstable_runWithPriority scheduler.development.js:468
    React 6
        runWithPriority$1
        flushSyncCallbackQueueImpl
        flushSyncCallbackQueue
        discreteUpdates$1
        discreteUpdates
        dispatchDiscreteEvent
react.development.js:1476
    React 2
        resolveDispatcher
        useContext
    useHistory react-router.js:720
    LoginForm LoginForm.js:16
    React 11
        renderWithHooks
        mountIndeterminateComponent
        beginWork
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        beginWork$1
        performUnitOfWork
        workLoopSync
        renderRootSync
        performSyncWorkOnRoot
    performSyncWorkOnRoot self-hosted:1220
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:468
    React 6
        runWithPriority$1
        flushSyncCallbackQueueImpl
        flushSyncCallbackQueue
        discreteUpdates$1
        discreteUpdates
        dispatchDiscreteEvent
    bind_applyFunctionN self-hosted:1371
    dispatchDiscreteEvent self-hosted:1334
`

**Comment by stefanwuthrich** [comment]
![Screenshot from 2021-05-13 13-35-38](https://user-images.githubusercontent.com/8337826/118097318-276e6000-b3f0-11eb-9ab8-6d3c146334ca.png)

Last line missing on screenshot: dispatchDiscreteEvent self-hosted:1334

**Comment by gaearon** [comment]
>See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

@mahmoudraad Have you looked at this? This is where you should start. Share what you tried.

**Comment by bvaughn** [comment]
Just re-noticed this issue :) and I'm going to close it since it seems like we haven't gotten a response back from my question 10 days ago.
