### ISSUE TITLE
Feature getDerivedPropsFromProps

### ISSUE THREAD

**Issue by SimonChaumet** [facebook/react#21412]
It could be great to have a static function to create a derived version of properties without putting it into the state or by using memoization.

# use case :
My component receives a list of routes (these are routes from react-router in my case), but I want to put a HOC for all the components that will be used after to pass the correct properties to my components. So I only need to change my properties when they change and not after.

I tried :
- getDerivedStateFromProps : it seems a bit overkill in my case since I don't need to update my list inside my component
- memoization : it seems like the best choice for now but I don't need to compute with anything else so it will keep in memory my list for almost nothing
- in render : will be computed every time a prop or the state changes

Here is an example of my code (which is not finished yet) if my explanation is not enough :
```ts
import React, { Component, GetDerivedStateFromProps } from "react";
import { Route, RouteComponentProps, withRouter } from "react-router-dom";
import { matchRoutes, renderRoutes } from "react-router-config";
import { RouteConfig, RouteConfigWithResolve } from "./types";

type Props = RouteComponentProps & {
  routes: RouteConfig[];
};

type State = {
  previousLocation: RouteComponentProps["location"] | null;
  currentLocation: RouteComponentProps["location"];
  currentLoadedRoutes: RouteConfig[];
};

function hasResolve(route: RouteConfig): route is RouteConfigWithResolve {
  return route.resolve !== undefined;
}

class RouteDataLoader extends Component<Props, State> {
  readonly state: State = {
    previousLocation: null,
    currentLocation: this.props.location,
    currentLoadedRoutes: [],
  };

  static getDerivedStateFromProps: GetDerivedStateFromProps<Props, State> = (
    props,
    state,
  ) => {
    const currentLocation = props.location;
    const previousLocation = state.currentLocation;

    const navigated = currentLocation !== previousLocation;

    if (navigated) {
      return {
        previousLocation,
        currentLocation,
      };
    }

    return null;
  };

  componentDidUpdate(prevProps: Readonly<Props>, prevState: Readonly<State>) {
    const navigated = prevProps.location !== this.props.location;

    if (navigated) {
      console.log(this.props.location);
      const routes = matchRoutes(
        this.props.routes,
        this.props.location.pathname,
      );
      console.log(routes);

      const routesPromises = routes
        .filter((r) => this.state.currentLoadedRoutes.indexOf(r.route) >= 0)
        .map((r) => r.route)
        .filter(hasResolve)
        .flatMap((r) =>
          Object.entries(r.resolve).map(([name, resolveObj]) => [
            name,
            typeof resolveObj == "function"
              ? resolveObj()
              : resolveObj.handler(),
          ]),
        );

      Promise.all(routesPromises.map(([, promise]) => promise));

      this.setState((prevState) => ({
        ...prevState,
        previousLocation: null,
      }));
    }
  }

  render() {
    const { location } = this.props;
    const { previousLocation } = this.state;

    return (
      <Route
        location={previousLocation || location}
        render={() => renderRoutes(this.props.routes)}
      />
    );
  }
}
```

**Comment by bvaughn** [comment]
Should the derived props change whenever the incoming props change?

If yes, then a small memoization library like [`memoize-one`](https://www.npmjs.com/package/memoize-one) would fit this use case.

If no, then just setting the derived properties on the instance in the constructor would fit the use case.

**Comment by SimonChaumet** [comment]
> Should the derived props change whenever the incoming props change?
> 
> If yes, then a small memoization library like [`memoize-one`](https://www.npmjs.com/package/memoize-one) would fit this use case.
> 
> If no, then just setting the derived properties on the instance in the constructor would fit the use case.

Like I said memoization is good but a bit overkill for keeping in memory a long list for almost nothing

**Comment by bvaughn** [comment]
I believe that going forward, function components are the primary way for writing React components. The class component API is still around, but I don't see us adding a new API like the one described here to class components (particularly given there's an existing way to implement this via memoization).

You could create a new base class that implements this functionality if you'd like.

Or you could just use `getDerivedStateFromProps` which is essentially the same thing you're describing. (Not sure why you think it seems like overkill. React stores props and state in the same way.)

If you feel strongly about this though, the next step would be to create an RFC:
https://github.com/reactjs/rfcs#react-rfcs

That being said, I don't think an RFC for this would be likely to be adopted. (Just wanted to give you a fair warning before you spent time writing one.)

I'm going to go ahead and close this issue since I don't see us taking action on it given the above. Thanks for understanding!

**Comment by SimonChaumet** [comment]
@bvaughn How do you see this being covered in function components ? The memoization would be computed every time the function is called, in the documentation it seems obvious to use a class component

**Comment by bvaughn** [comment]
I don't understand what you mean by "_memoization would be computed_". Memoization _prevents_ computation unless an input changes.

Something, somewhere, needs to do this comparison (have props changed) – even if it's React :)

**Comment by SimonChaumet** [comment]
@bvaughn with memoize-one you pass a function, isn't this function recreated every time a prop changes ?

**Comment by bvaughn** [comment]
No. The function is _re-run_ only when the prop changes.

**Comment by SimonChaumet** [comment]
@bvaughn you don't have a constructor in a function component

**Comment by bvaughn** [comment]
I thought we were talking about class components?

The Hooks API docs talk about the constructor equivalent of hooks (`useState` initializer): https://reactjs.org/docs/hooks-faq.html#how-do-lifecycle-methods-correspond-to-hooks

You could also use a ref (`useRef`) to initialize the memoization function, and even wrap it in a custom hook:
```js
import { useRef } from "react";
import memoize from "memoize-one";

function useMemoizeOne(method) {
  const memoizedMethodRef = useRef(memoize(method));
  return memoizedMethodRef.current;
}

function Component(props) {
  const memoizedMethod = useMemoizeOne(value => {
    // This function will only be run when 'value' changes.
    // Derive your value...
  });
  const derivedValue = memoizedMethod(props.value);

  // Use your derived value...
}
```

**Comment by SimonChaumet** [comment]
Okay, I'm gonna go for the hooks so
