### ISSUE TITLE
Bug: Bug: Error message incorrectly

### ISSUE THREAD

**Issue by akiraplusplus** [facebook/react#21411]
Getting this error message:

React Hook "useStyles" is called conditionally. React Hooks must be called in the exact same order in every component render

However, I'm pretty darn sure that I'm not actually calling useStyles conditionally. Also, the error messages come and go if I comment out unrelated code.

React version: 16.8

**Comment by yungvldai** [comment]
Hey! Is there no mistake in the react version? As far as I know, hooks presented in version 16.8

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
