### ISSUE TITLE
Get rid of using dependencies in useCallback 

### ISSUE THREAD

**Issue by b-ponomarenko** [facebook/react#21424]
It seems there is no need to using an array of dependencies in the `useCallback` hook at all. We can change `useCallback` hook using `useRef` under the hood in order to store the latest reference. Consider this code:
```js
import { useCallback, useLayoutEffect, useRef } from 'react';

const useEnhancedCallback = (callback, deps = []) => {
    const callbackRef = useRef(null);

    useLayoutEffect(() => {
        callbackRef.current = callback;
    });

    return useCallback(((...args) => callbackRef.current(...args)), deps);
};

export default useEnhancedCallback;
```
Example of using:
```js
// before
const Component = ({ data1, data2, data3 }) => {
  const cb = useCallback(() => {
   // do something with data
  }, [data1,data2,data3]); // have to pass array of dependecies
}

// after
const Component = ({ data1, data2, data3 }) => {
  const cb = useEnhancedCallback(() => {
   // do something with data
  }); // don't have to pass array of dependecies and have the same reference
}
```

In case you need to change the reference you can pass an array of dependencies.
```js
const Parent = ({ data1, data2, data3 }) => {
  const cb = useEnhancedCallback(() => {
   // do something with data
  }, [data1,data2,data3]);

  return <Child cb={cb} />
}

const Child = ({ data1, data2, data3, cb }) => {
  useEffect(() => {
    cb();
  }, [cb]);
}
```

**Comment by vkurchatkin** [comment]
This is not a new idea and has been discussed many times over the years, for example in this issue https://github.com/facebook/react/issues/14099

**Comment by bvaughn** [comment]
@vkurchatkin is right. A ref based approach has already been proposed over on #14099 (https://github.com/facebook/react/issues/14099#issuecomment-440013892) so this discussion should be moved there. Going to close this so that discussion stays on the same issue.
