### ISSUE TITLE
Incorrect handling of SequenceExpression inside XJSExpressionContainer

### ISSUE THREAD

**Issue by RReverser** [facebook/react#2143]
Consider following examples:

1)

``` javascript
React.renderComponent(<HelloMessage name={doSmth(), "Ingvar"} />, mountNode);

// Translates to:

React.renderComponent(HelloMessage({name: doSmth(), /* Syntax Error */ "Ingvar"}), mountNode);
```

or

``` javascript
React.renderComponent(<HelloMessage>{doSmth(), "Ingvar"}</HelloMessage>, mountNode);

// Translates to:

React.renderComponent(HelloMessage(null, /* Wrong output */ doSmth(), "Ingvar"), mountNode);
```

Sequence expressions are not used that often, but still they are so I believe both possible errors should be fixed.

Possible fix would be to treat XJSExpressionContainer as parenthesized expression (simply add "(" and ")" around inner expression in output).

**Comment by gaearon** [comment]
Closing as non-actionable in this repo.

**Comment by RReverser** [comment]
@gaearon Ha, thanks for bringing up some old memories!
