### ISSUE TITLE
useEffect memory leak when setting state in callback 

### ISSUE THREAD

**Issue by iamfazal** [facebook/react#21443]
I know the [Issue #15006](https://github.com/facebook/react/issues/15006) is still open but the described problem is not fit in my case.
I have to check the User is Login? using AWS Cognito function in the private route. I can't use the cleanup function because before the callback executes I redirect to my login page. 

here is some of the code
**Privateroute.js** (problem in this code)

```
import { Route, Redirect } from "react-router-dom";
import React, { useState, useContext, useEffect } from "react";
import { AccountContext } from "../components/cognito";

export default function PrivateRoute({ component: Component, ...rest }) {
  const [status, setStatus] = useState(false);
  const { getUserStatus } = useContext(AccountContext);
  useEffect(() => {
    let mounted = true;
    getUserStatus().then((data) => {
        if(mounted)
            setStatus(true);
        
    });
    return () => mounted = false;
  },[]);

  return (
    <Route
      {...rest}
      render={(props) =>
        status ? <Component {...props} /> : <Redirect to="/" />
      }
    />
  );
}
```
if I removed the _mounted_ check I received the memory leak warning

_code to check the is user login_

```
const getUserStatus= async()=>{
    await new Promise((resolve,reject)=>{
      const user = UserPool.getCurrentUser();
      if(user){
        user.getSession((err,data)=>{
          if(err)
            reject(false)
          else{
            resolve(data)
          }
        })
      }else
        reject(false)
    })
  }
```
call to private route
  ```
  <Router>
      <Account className="App">
        <Switch>
          <Route exact path="/" component={Login} />
          <Route path="/sign-in" component={Login} />
          <Route path="/sign-up" component={Signup} />
          <Route path="/forgotPassword" component={ForgotPassword} />
          <PrivateRoute path="/dashboard" component={Dashboard} />
        </Switch>
      </Account>
    </Router>
```

**Comment by eps1lon** [comment]
> if I removed the mounted check I received the memory leak warning

Sounds like there is no issue with the posted code then? Could you provide a repro that does have an issue?

**Comment by iamfazal** [comment]
@eps1lon there is a logical error. my user is login and before the promise resolved the status hook is false so I redirect to "/" page.

**Comment by PupoSDC** [comment]
The posted code looks correct to me as well. With promises, you always need to do some sort of check to make sure its still safe to update the state on your component.

> I can't use the cleanup function because before the callback executes I redirect to my login page.

This shouldn't be true. When you go to `"/"` your component will still call the `PrivateRoute` useEffect cleanup. You can test this by adding a breakpoint, to that particular line (or a `debugger`/`console.log` call).
