### ISSUE TITLE
Feature Request: ESLint hooks rule for accessing previous state when deriving new state

### ISSUE THREAD

**Issue by johncmunson** [facebook/react#21448]
A very common mistake and source of bugs in React applications is not using the updater function when deriving new state from old state.

When using class components, there is a handy [lint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md) for this in the eslint-plugin-react project.

However, their rule does not work for functional components that utilize useState, and they have [suggested](https://github.com/yannickcr/eslint-plugin-react/issues/2539#issuecomment-620879842) that [eslint-plugin-react-hooks](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/README.md) would be a more appropriate home for an equivalent lint rule that _does_ work with hooks.

I've seen this mistake made countless times, and I even fall victim to it every once in awhile, so having an officially sanctioned lint rule would be amazing!

**Comment by martdavidson** [comment]
Got bitten by this last week, and it was especially nefarious as it only showed as an issue in production when built, not in local development. Would love to see a rule for this!

**Comment by Samuel-Beslogic** [comment]
+1 on this. Took me a while to realise my state update was wrong just because I forgot to use the function. Could probably even be auto-fixable.

**Comment by palfrey** [comment]
Bump

**Comment by palfrey** [comment]
Bump

**Comment by Samuel-Therrien-Beslogic** [comment]
Conversation was locked repository-wide to contributor only and I couldn't bump earlier this week...
