### ISSUE TITLE
[DevTools Error] Cannot add node "3709" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by devich2** [facebook/react#21464]
### Website or app

http://localhost:3001/

### Repro steps

http://localhost:3001/

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.2-e468072e17

### Error message (automated)

Cannot add node "3709" because a node with that id is already in the Store.

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment]
@devich2 
http://localhost:3001 isn't a public URL. This repro step isn't something any of us can follow. Going to close this issue for now. If you provide more details, I'll be happy to reopen it though.
