### ISSUE TITLE
[DevTools Bug]: Children list grows indefinitely when adding/removing useEffect

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#21469]
### Website or app

Please checkout the linked branch not `main`
https://github.com/eps1lon/react-devtools-repro-no-matching-node/tree/repro/elements-leaking
Repro steps and screen recording included in the repro

### Repro steps

1. Clone repro
1. yarn
1. yarn start
1. Open app page
1. open devtools
1. Uncomment the `useEffect` block i.e. add an effect
1. inspect `Component` element
1. comment `useEffect` block i.e. remove the effect
1. Repeat comment/uncomment to see that children grow indefinitely

### How often does this bug happen?

Every time

### Error message (automated)

Could not inspect element with id 4

Might be a duplicate of https://github.com/facebook/react/issues/21436#issuecomment-835406075 since the repro steps are the same. But depending on what the effect is doing, the behavior is different.

**Comment by bvaughn** [comment]
I think this might be the same issue I've captured in a test:
https://github.com/facebook/react/issues/21436#issuecomment-840799858

**Comment by bvaughn** [comment]
I _think_ #21506 might be one way to fix this issue.

**Comment by bvaughn** [comment]
Resolved by #21516
