### ISSUE TITLE
How can we deal with suspense in mixed mode (multiple renderers) 

### ISSUE THREAD

**Issue by drcmda** [facebook/react#21486]
React does not currently support context, error-bounds and suspense across multiple renderers, for reference we have a longstanding open ticket for context: https://github.com/facebook/react/issues/17275

This is about suspense. I need to be able to await a custom renderer. In my case the `<Canvas />` component is part of the react-dom tree, but renders into its custom-renderer in a LayoutEffect.

```jsx
<Suspense fallback={<div>waiting ...</div>}>
  <Canvas>
    {/* this is not the dom, we're targeting another platform */}
    <mesh />
    <ComponentThatSuspends />
  </Canvas>
</Suspense>
```

Currently suspense only functions *inside* the canvas so the outside has a hard time knowing when the inner contents are ready. I tried to make a work-around, you can see it running here: https://twitter.com/0xca0a/status/1391882917039812611

Is it OK to abuse suspense fallbacks in that way, does the React team see problems with this approach:

```jsx
function Canvas({ children }) {
  const [block, setBlock] = useState(false)
  // Suspend this component if a block is present
  if (block) throw block

  useLayoutEffect(() => {
    // Let the renderer render the scene, inject the Block component which adds and lifts the suspense
    CustomRenderer.render(<React.Suspense fallback={<Block set={setBlock} />} children={children} />)
  }, [children])

  return null
}

function Block({ set }) {
  React.useLayoutEffect(() => {
    set(new Promise((r) => null))
    return () => set(false)
  }, [])
  return null
}
```

?

**Comment by LXSMNSYC** [comment]
Does this work? I assume error boundaries are able to catch all kinds of throwable values (includes Promises).

```js
function Canvas({ children }) {
  const [error, setError] = useState();
  
  if (error) {
    throw error;
  }
  
  useEffect(() => {
    CustomRenderer.render((
      <ErrorBoundary onError={(err) => setError(error)}>
        {children}
      </ErrorBoundary>
    ));
  }, [children]);
  
  return null;
}
```
