### ISSUE TITLE
Bug: Memory leak in simple dialog interaction

### ISSUE THREAD

**Issue by bawa** [facebook/react#21490]
Hi,

I recently encountered a memory leak in our app. Trying to isolate the problem I ended up with a simple create-react app, where
it also seems to appear. The app consists of a simple button opening a dialog. Dialog has a text field (for simplification not connected to anything, state changes etc) and a list of strings rendered as divs. Dialog can be opened any number of times and then closed. This works correctly - no memory problems. However, if I try to enter any string into the text field and then close the dialog - memory seems to leak, number of fibernodes (and e.g detached input elements) is rising and never gets gc.
This behavior can be observed on dev mode (npm start), prod mode (npm run build, serve -s), but for some reason CANNOT be observed on codesandbox, in embedded view (https://codesandbox.io/s/determined-joliot-hox9x), but can be reproduced there in new window mode. 

thanks for any help
Bartek

App.tsx :
```
function App() {

  const [open, setOpen] = useState(false)
  const [data, setData] = useState<string[]>([])

  useEffect(() => {
    const initData = () => {
      setData(Array.from(new Array(100),(val,index)=> "some string " + index ))
    };
    initData();
    return () => {
      //cleanups on unmount

    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleClickOpen()  {
    setOpen(true);
  }


  function handleClose() {
    setOpen(false);
  }

  return (
    <div className="App">
      <DataBrowser open={open} data={data} onClose={handleClose}/>
      <Button variant="outlined" color="primary" onClick={handleClickOpen}>
        Open simple dialog
      </Button>
    </div>
  );
}

export default App;
```

Dialog triggered by above button:

```
import * as React from "react";
import DialogTitle from "@material-ui/core/DialogTitle";
import DialogContent from "@material-ui/core/DialogContent";
import Dialog from "@material-ui/core/Dialog";
import IconButton from "@material-ui/core/IconButton";
import CloseIcon from '@material-ui/icons/Close';

type Props = {
    open: boolean
    data: string[]
    onClose: ()=>void
}

export const DataBrowser:  React.FC<Props> = ({data, open, onClose}) => {

    const handleClose = ()=> {
        onClose()
    }

    return (

        <Dialog
            open={open}
            onClose={handleClose}
            aria-labelledby="form-dialog-title"
            data-testid="databrowser_dialog"
            disableBackdropClick={true}
            disableEscapeKeyDown={false}>
                <DialogTitle  id="form-dialog-title">
                    {"Data browser"}
                    <IconButton  aria-label="Close" color="primary" onClick={handleClose}>
                        <CloseIcon fontSize="small" />
                    </IconButton>
                </DialogTitle>
                <DialogContent >


                    <React.Fragment>

                        <input type={"text"}/>

                        {data.map((item, idx)=>{
                            return <div key={idx}>{item}</div>
                        })}

                    </React.Fragment>

                </DialogContent>
        </Dialog>
    )
}
```

Versions: 

"@material-ui/core": "4.11.4",
"@material-ui/icons": "4.11.2",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-scripts": "4.0.3",
"typescript": "^4.2.4",

Occurs on dev and prod modes, strict mode not used

## Steps To Reproduce

1. Click on button to open dialog
2. Enter anything into text field
3. Close dialog

## The current behavior

Memory consumption is rising and never gets garbage collected

## The expected behavior

Memory consumption is not rising upon over some warmup limit

**Comment by hardikshah197** [comment]
@bawa May I take this issue? if it is open...

**Comment by bawa** [comment]
> @bawa May I take this issue? if it is open...

Sure, I really appreciate any feedback here. Thanks :)

**Comment by bawa** [comment]
@hardikshah197 Did You perhaps try reproducing this issue?

**Comment by hardikshah197** [comment]
@bawa yes, I reproduced it and analyzing the code as well
