### ISSUE TITLE
Bug: ReactDOM ignores invalid styles (e.g. unquoted font-family)

### ISSUE THREAD

**Issue by niwinz** [facebook/react#21497]
React version: 17.0.2

## Steps To Reproduce

1. Just try to set `fontFamily: "Exo 2"` on styles.

https://codesandbox.io/s/react-exo-2-font-b80ij

- If you chage it to "Exo", the hot reload correctly sets "Exo" fontFamily on the dom.
- If you next change again to "Exo 2", it just leaves the dom with the previous value: "Exo"

This happens on latest Firefox, Chrome and Brave

**Comment by AlexRAV** [comment]
Hi @niwinz. Are you sure that this is related to ReactDOM?

I've tried to assign new fontFamily value using style property and it doesn't work even for the native JS solution.
![image](https://user-images.githubusercontent.com/13298791/118114836-54336f00-b412-11eb-9220-d10116c4ce69.png)

**Comment by AlexRAV** [comment]
It's also will ignore the new value if it contains `8`

**Comment by niwinz** [comment]
I didn't specified ReactDOM, is @bvaughn who changed the title.

**Comment by niwinz** [comment]
But yes, you are right it happens using native dom api...

**Comment by niwinz** [comment]
![image](https://user-images.githubusercontent.com/843689/118120409-22111580-b3f0-11eb-9c0f-be3fd72d1f6e.png)
But if you quote the fontFamily string, it works.

**Comment by AlexRAV** [comment]
Hmm, looks like this is specification-described behavior
https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#propdef-font-family

> Font family names other than generic families must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means most punctuation characters and digits at the start of each token must be escaped in unquoted font family names.

> To illustrate this, the following declarations are invalid:

> font-family: Red/Black, sans-serif;
> font-family: "Lucida" Grande, sans-serif;
> font-family: Ahem!, sans-serif;
> font-family: test@foo, sans-serif;
> font-family: #POUND, sans-serif;
> font-family: Hawaii 5-0, sans-serif;

**Comment by eps1lon** [comment]
> Hmm, looks like this is specification-described behavior
> [w3.org/TR/2018/REC-css-fonts-3-20180920/#propdef-font-family](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#propdef-font-family)
> 
> > Font family names other than generic families must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means most punctuation characters and digits at the start of each token must be escaped in unquoted font family names.
> 
> > To illustrate this, the following declarations are invalid:
> 
> > font-family: Red/Black, sans-serif;
> > font-family: "Lucida" Grande, sans-serif;
> > font-family: Ahem!, sans-serif;
> > font-family: test@foo, sans-serif;
> > font-family: #POUND, sans-serif;
> > font-family: Hawaii 5-0, sans-serif;

Seems like the correct answer. The following diff solves the problem:

```diff
const style = {
- fontFamily: "Exo 2"
+ fontFamily: "'Exo 2'"
};
```

**Comment by niwinz** [comment]
yeah, the question here is, this is expected behavior and is **the user responsibility* to properly quote the fontFamily, or **react responsibility** to abstract this browser very strange behavior... (because if  you put `const style = {fontFamily: "Exo Other"};` it works as expected)

**Comment by bvaughn** [comment]
> because if  you put `const style = {fontFamily: "Exo Other"};` it works as expected

Was about to say this.

**Comment by eps1lon** [comment]
> (because if you put `const style = {fontFamily: "Exo Other"};` it works as expected)

The question is what "expected behavior" is in this context. Because it works if you have platform expectations. `Exo Other` working without quotes but `Exo 2` requiring quotes is [specified behaivor](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#propdef-font-family) as shown by @AlexRAV.

React could not just add quotes but also need to check that quotes aren't already in place. And then it isn't even clear if people actually appreciate this fix or find it more confusing. After all, why doesn't the platform patch `Exo 2` to `"Exo 2"` if that would always be the desired behavior?

**Comment by AlexRAV** [comment]
@eps1lon maybe we should add just info message for dev mode for this case? I thing it should be nothing more than reminded for developer.

**Comment by niwinz** [comment]
The main problem here is the surprise and the long time of debugging when finally you realize that is a browser expected and documented behavior. A simple warning in dev mode probably will help save the developer time.

**Comment by AlexRAV** [comment]
I'm not sure about the info message content, because it's still pretty unclear for me, so feel free to share your thoughts about it.

**Comment by niwinz** [comment]
It looks nice for me ;)

**Comment by jasongi** [comment]
Given this isn't just an issue affecting font Family ( see #21514 ) I think maybe a more generic message that a style wasn't applied because it is invalid would be helpful.

**Comment by AlexRAV** [comment]
Sure, I can extend the validation rule

**Comment by AlexRAV** [comment]
Hmmm, the algorithm I used for fontFamily property doesn't work properly for every style property. I just compare value from `node.style.fontFamily` with value passed from react. It worked well with `fontFamily` but for example, if I'll pass something like that `{ left: 0 }` it won't work as the value from `node.style.left` will be equal to `0px`. Do you guys have any ideas on how to implement this validation correctly?

**Comment by Aslam119** [comment]
> React version: 17.0.2
> 
> ## Steps To Reproduce
> 1. Just try to set `fontFamily: "Exo 2"` on styles.
> 
> https://codesandbox.io/s/react-exo-2-font-b80ij
> 
> * If you chage it to "Exo", the hot reload correctly sets "Exo" fontFamily on the dom.
> * If you next change again to "Exo 2", it just leaves the dom with the previous value: "Exo"
> 
> This happens on latest Firefox, Chrome and Brave

you could use , useState hook 

import "./styles.css";
import { useState } from "react";

export default function App() {
  const [style, setStyle] = useState({
    fontFamily: "Exo"
// CHANGE THE VALUE HERE  TO WHICH EVER FONT 
  });

  return (
    <div className="App">
      <h1 style={style}>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}

**Comment by arshabh-copods** [comment]
@AlexRAV Are you still working on this ? I do not have any idea on how to implement this validation right now - but can look into it.

**Comment by kn0ll** [comment]
RFC:

i thought this looked like an easy first issue to attempt. and, well, i guess nothing is ever that easy. :)

the relevant code is to warn for CSS values here: https://github.com/facebook/react/blob/main/packages/react-dom/src/client/CSSPropertyOperations.js#L59-L85

philosophically speaking, some of the discussion here has been "what is the duty of React here, if any?". it already performs `warnStyleValueIsInfinity` and `warnStyleValueIsNaN`, but still tries to set it in the DOM. consdering that, I think React has already decided it has some responsibility to validate style values, but no responsibility to fix them.

there's a few approaches i attempted:

1. write more validators that are key-aware by simply extending `warnValidStyle`. in this case, parsers for properties like "fontFamily". the major issue with this is you need to make sure your parser matches the parser of the browser, else you will get a misidentified warning. even if you could possibly manage to write a "fontFamily" parser that matched all browsers expectations, you still haven't handled "font" shorthand property now. basically, this route just seems like an impossible cat and mouse chase.

2. use the application of the style to verify it's been written correctly, by comparing the input style to the one on the node, as suggested by `@AlexRAV`. the first issue with this is purely a code smell, which is this type of validation would need to be run after the style was applied- while all current validators are run before the style is applied. the second issue was brought up by Alex, which is comparing things like "0" to "0px". for numbers. i was able to solve this by using a combination of `dangerousStyleValue` and `isUnitlessNumber`. but then more similar issues started to crop up even when React was not dangerously styling the value. for instance, in Firefox, setting background to "#000" will report back "rgb(0, 0, 0)" when read through the style interface. similarly, setting background to `rgb(0,    0, 255)` would report back `rgb(0, 0, 255)`. basically you have no control over how the browser formats the value, so this seems like another impossible cat and mouse chase.

enter `CSS.supports`:
- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports)
- [caiuse](https://caniuse.com/css-supports-api)

this widely available function. and for the platforms it's not available on like IE, well, this is a dev build. so i think the worst case scenario, "developers using IE will not get this warning", is not a show stopper.

here is my first pass implementing this validation: https://github.com/facebook/react/compare/main...kn0ll:fix/21497?expand=1

i have three issues with this implementation, but i think we can work through them together:

1. the biggest issue is that `CSS.supports` needs the CSS key name, not the style property key name. that is, warnValidStyles has access to key `fontFamily`, but does not know how to convert that to `font-family` for proper use by `CSS.supports`. i hacked this together real dirty, and it works, but i imagine there has to be a more reliable way?

```
const styleKey = 'fontFamily';
const div = document.createElement('div');
div.style[name] = '"Exo 2"';
const cssKey = div.style.item(0);
// 'font-family'
```

2. i could not figure out how to write a test for this in JSDOM, where i believe CSS.supports is reporting undefined.

3. i wonder what place the existing `warnStyleValueIsInfinity` and `warnStyleValueIsNaN` functions have anymore, if we apply this new validator. the CSS.supports validator would catch both of those instances all the same.

what do you all think?

**Comment by kn0ll** [comment]
@gaearon thank you for your response. totally happy to take no  action here. but i'm afraid we may not be on the same page

> When there's a cheap and easy way to tell if the value is definitely invalid we can do this. E.g. the NaN value case mentioned earlier. But this doesn't seem to be one of those cases. Reading from the DOM to "verify" risks introducing other issues and isn't always correct (as noted above, the returned representation could differ from what we set even if the setting was successful).

> Since there is no cheap and easy way to diagnose the issue here,

does [CSS.supports](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports) not do exactly this?

**Comment by gaearon** [comment]
Does it work for this font family use case?

**Comment by kn0ll** [comment]
definitely! on the client-side, anyway (naturally).

```
CSS.supports('font-family', 'Exo 2') => false
CSS.supports('font-family', '"Exo 2"') => true
CSS.supports('font-family', 'Exo Foo') => true
CSS.supports('font-family', '"Lucida Grande", "Exo 2"') => true
CSS.supports('font-family', '"Lucida Grande", Exo 2') => false

CSS.supports('font', '"Lucida Grande", "Exo 2"') => false
CSS.supports('font', '12px "Lucida Grande", "Exo 2"') => true
CSS.supports('font', '12px "Lucida Grande", Exo 2') => false
```

it's i think it's a direct hook for the information we need. this can also validate `Infinity` and `NaN` just fine:

```
CSS.supports('margin-top', Infinity) => false
CSS.supports('margin-top', NaN) => false
CSS.supports('margin-top', 0) => true
CSS.supports('margin-top', '0') => true
CSS.supports('margin-top', '0p') => false
CSS.supports('margin-top', '0px') => true
CSS.supports('margin-top', ' 0px ') => true
CSS.supports('margin-top', ' 0 px ') => false
```

(not exactly related, but worth noting that it can also tell you about the browsers capabilities to parse whitespace or unitless values)

if i can figure out how to reliably convert style property names like `fontSize` to css property names like `font-size`, then i fix the weird hacks in the PR i shared.

**Comment by Inwerpsel** [comment]
Has the effect of this on props that change throughout time been considered? It currently prevents React from removing a background property when transitioning back to the invalid state.

I created screenshots from [this CodeSandbox](https://codesandbox.io/s/vigilant-feather-3uh6do) to illustrate.

Step 1: provide an invalid background property value: React creates an element with particular style properties that exclude the invalid one
![step1-invalid](https://user-images.githubusercontent.com/7604138/200133215-d89f1908-3f66-405d-aac0-adee52498110.PNG)

Step 2: put something valid in the background property: React updates the property to reflect the new state
![step2-valid](https://user-images.githubusercontent.com/7604138/200133241-108c3f30-29bf-4303-9543-d492c0570f8f.PNG)

Step 3: revert back to the original state: React does not give you the same HTML for the same props as step 1, but instead leaves a stale attribute from a previous state, causing a color to show which, according to the code, should not be there.
![step3-invalid-wrong](https://user-images.githubusercontent.com/7604138/200133264-00f7487f-63f6-48c8-b566-ade0fa258b8e.PNG)

**Comment by Inwerpsel** [comment]
Just wanted to focus on this particular resulting problem, perhaps it's possible to address only that (allow it to properly remove a stale attribute in step 3).

You usually want to validate potentially incorrect input anyway before using it in a prop, so definitely not something crucial. It's just that it can put you on the wrong track during development. Then again, once you know about this behavior you can easily recognize it.

**Comment by vchertuk** [comment]
Faced the same issue while applying Exo 2 font via style prop. Adding quotes helped
![Снимок экрана 2024-08-21 в 21 12 59](https://github.com/user-attachments/assets/ea7461b9-b677-437c-ae4f-827d5cbf196f)
