### ISSUE TITLE
https://reactjs.org/docs/getting-started.html(React.org docs page right side bottom menu not able see the options )     

### ISSUE THREAD

**Issue by soundharrajan89** [facebook/react#21503]
React.org docs page right side bottom menu not able see the options
Solution: Please update below CSS properties
.css-1d35tl3{
    overflow-y: scroll;
    height: 85%;
}

**Comment by bvaughn** [comment]
The documentation and source for [reactjs.org](https://reactjs.org/) are in a different GitHub repository.

Please open a new issue in that repository:
[https://github.com/reactjs/reactjs.org](https://github.com/reactjs/reactjs.org/issues/new) 

Sorry for the inconvenience! 🙂
