### ISSUE TITLE
After "react developer tools" is opened, the "message" event of window.addeventlistener will be triggered frequently

### ISSUE THREAD

**Issue by Shen120** [facebook/react#21507]
- React: 15.5.4
- React-dom: 15.5.4
- React Developer Tools: 4.13.2

1、open the tools
2、window.addEventListener('message', event => {
      // code...
    });

**Comment by bvaughn** [comment]
This is expected. React DevTools uses `postMessage` to communicate between the Chrome extension itself and the script running in the webpage alongside of React.
