### ISSUE TITLE
ReactCSSTransitionGroup jumbles UI

### ISSUE THREAD

**Issue by z5h** [facebook/react#2150]
I'm using react with a router.
In my toplevel render I have code like this:

```
//our main content is driven by URL, so URL is a fine key to use for
//React's key functionality that tells it when something has changed.
var key = document.location.toString();
return <ReactCSSTransitionGroup transitionName="slide">
          <viewData.viewClass key={key} scope={viewData.scope}/>
</ReactCSSTransitionGroup>;
```

In other words, only one toplevel item can be rendered at once. And it is dependant on the URL.
BUT...
when I use ReactCSSTransitionGroup I end up with a situation where several components are rendered in this slot where only one item can possibly live. It happens only on my stock Nexus 5 & iPad. It seems to work fine in a desktop browser.

The example is here: http://z5h.github.io/fluir/
To trigger the bug, use navigate into users/phones and use back a few times.

The framework is my own here: https://github.com/z5h/fluir/blob/master/index.js
The example code is here: https://github.com/z5h/fluir/blob/master/example/src/index.js

**Comment by spicyj** [comment]
This sounds like #1326.
