### ISSUE TITLE
Bug: Applying an invalid style will use property from previous render

### ISSUE THREAD

**Issue by jasongi** [facebook/react#21514]
Applying an invalid style will use property from previous render. This can cause some hard to pin down bugs since you may inadvertently be applying invalid styles but not notice because the style on the previous render was fine. But then rendering later on with the same props/state will cause a different style to be applied, because of what happened on the previous render.

React version: 17.0.2

## Steps To Reproduce

1. Apply a valid style property to a component (e.g `backgroundColor: red`)
2. Apply an invalid style property to a component (for example: `backgroundColor: 5`)
3. note: Background stays red
4. Change state to apply a valid style (or no style) (e.g `backgroundColor: white`)
5. note: background is now white
6. Change state to apply an invalid style again
7. Note that the background stays white, even though it has the same props as step 2 when it rendered red

Link to code example:

https://codesandbox.io/s/frosty-water-hwbj6
Click change then clear then change again to see it in action.

## The current behaviour

- When a style object property is invalid, it applies style property from the previous render

## The expected behaviour

I think the sensible thing to do would be:
- Display a warning in development mode if a property is invalid
- Remove any the previous style property from the element if the property passed is invalid.

However I think as long as it does the same thing regardless of props passed in the previous render it is acceptable.

**Comment by bvaughn** [comment]
I think this is, essentially, the same as issue #21497

**Comment by bvaughn** [comment]
The repro above is nice (thanks for sharing) but I'm going to close this as a duplicate and we can continue the discussion on #21497
