### ISSUE TITLE
[DevTools Error] Cannot remove node "771" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by lazcanocode** [facebook/react#21522]
### Website or app

https://soshace.com/react-user-login-authentication-using-usecontext-and-usereducer/

### Repro steps

I'm using a context to manage app global state like in [Website](https://soshace.com/react-user-login-authentication-using-usecontext-and-usereducer/) when get that error

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.2-e468072e17

### Error message (automated)

Cannot remove node "771" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21477:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19585:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19745:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37733:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment]
@lazcanocode Can you tell me exactly what you need to do on the website you linked in order to cause the bug to happen?

**Comment by nikglavin** [comment]
```
Uncaught Error: Cannot remove node "1262" because no matching node was found in the Store.
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21477:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19585:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19745:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37733:39)
```

Here's a stack that I got when encountering the same error, not sure if its helpful though, its been happening for a while with me and its also not happening all the time. 

```log
index.js:1 Warning: React instrumentation encountered an error: TypeError: memoizedState.hasOwnProperty is not a function
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2557
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
onCommitRoot @ react-dom.development.js:11146
commitRootImpl @ react-dom.development.js:23261
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

**Comment by bvaughn** [comment]
@nikglavin Call stack isn't really helpful. A repro case is what's needed for this bug.

**Comment by bvaughn** [comment]
I think this issue might be fixed by #21523.

If you'd like to verify, download this build:
[ReactDevTools.zip](https://github.com/facebook/react/files/6505445/ReactDevTools.zip)

And follow these steps to install it:
https://user-images.githubusercontent.com/29597/118749019-b6cda600-b82a-11eb-9449-ef56f41eced5.mp4

Going to close for now.

**Comment by lazcanocode** [comment]
Thank you, the new version fix my problem!!!

**Comment by bvaughn** [comment]
That's great! Thanks
