### ISSUE TITLE
[DevTools Bug]: Fast Refresh + DevTools breaks component inspection

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21528]
### Website or app

https://github.com/eps1lon/react-devtools-repro-no-matching-node/

### Repro steps

1. `yarn start`
2. Open `App.js`
3. Uncomment the `useEffect` block
4. Click to inspect "Component" in DevTools
5. Error: "_Could not inspect element with id 5_"

Originally reported in https://github.com/facebook/react/issues/21436#issuecomment-835406075

---

https://user-images.githubusercontent.com/12292047/117544707-e6a6cd80-b022-11eb-9f8f-bb8cfd9f7743.mp4

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment]
@eps1lon Here's another Chrome extension build with the fix from #21536:
[ReactDevTools.zip](https://github.com/facebook/react/files/6512398/ReactDevTools.zip)

**Comment by eps1lon** [comment]
> @eps1lon Here's another Chrome extension build with the fix from #21536:
> [ReactDevTools.zip](https://github.com/facebook/react/files/6512398/ReactDevTools.zip)

Everything fixed. Awesome :+1:

**Comment by bvaughn** [comment]
FYI @eps1lon just published as 4.13.4
