### ISSUE TITLE
Bug: Where did the components tree go in the new version?

### ISSUE THREAD

**Issue by AhmedSarhan** [facebook/react#21526]
### Website or app

https://localhost:3000

### Repro steps

in this image below I can't seem to find the old components tree, it used to be in this empty upper half, now all I can see it rendered by, so was it removed or is there something wrong with my extension ? 
![image](https://user-images.githubusercontent.com/20737908/118797969-693e5100-b89d-11eb-8bea-95ef73052e36.png)

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment]
Hi @AhmedSarhan!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by AhmedSarhan** [comment]
Hello Brian, Thank you for your response

I would like to clarify this is not a one time thing, I have been running to this issue since the latest update of the React Dev tools 
as I can't find the components tree of the current page which wasn't the case before
and it's happening with different React projects, projects that I have used the Dev tools on without running to any issues, small to medium projects using either CRA, or Next.js and same issue
I'm using Windows 10 and Google Chrome Dev, which were the same tools I have been using for months without running to that issue before

**Comment by bvaughn** [comment]
> I would like to clarify this is not a one time thing

Gotcha. Have you tried removing and re-installing the extension? (I'd try that first.)

> Google Chrome Dev

What is this? Is this a bleeding edge version of Chrome?

Chrome stable is, I believe, 90.0.4430.212. Stable is the only version that the extension supports.

Chrome Canary (for example) or other pre-release/preview releases often cause bugs in extensions due to changes in the browser itself.

**Comment by yume-chan** [comment]
I think it's this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=958475
