### ISSUE TITLE
[DevTools Error] Cannot remove node "145" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by marzouk2002** [facebook/react#21529]
### Website or app

https://github.com/marzouk2002/GetItDone/blob/master/client/src/components/Login.js

### Repro steps

After login with email and password, and the validation from the server. This happen when I tried to redirect to the home page

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.2-e468072e17

### Error message (automated)

Cannot remove node "145" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21477:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19585:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19745:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37733:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment]
This issue has been fixed in version 4.13.3 which is currently in-review in Chrome, Firefox, and Edge stores :)

Sorry for the trouble! Give it a few for the update to roll out, then this should be fixed.

**Comment by marzouk2002** [comment]
Ohh I see, thanks.

**Comment by ewotring** [comment]
This appears to be persisting. I'm up to version 4.13.4.

**Comment by bvaughn** [comment]
@ewotring Comments on closed issues are generally ignored. If you're seeing this bug on 4.13.4, please [open an issue](https://github.com/facebook/react/issues/new?assignees=&labels=Component%3A+Developer+Tools%2CType%3A+Bug%2CStatus%3A+Unconfirmed&template=devtools_bug_report.yml&title=%5BDevTools+Bug%5D%3A+) that includes source code and steps for how to trigger the bug and I'll be happy to look 😄
