### ISSUE TITLE
Experimental createRoot method not available in React 17

### ISSUE THREAD

**Issue by singharpit94** [facebook/react#21525]
I am using react and react-dom v17.0.2 and I was trying to use the unstable_createRoot method to render my app but looks like that method is not even present in react v17.0.2. 

Can someone comment if this is expected or not.

Thanks,
Arpit

**Comment by bvaughn** [comment]
This is expected. That API has not been released yet.

If you want to try it, you can install `react-dom@experimental` but note that the experimental release channel is not meant to be used in production apps.

**Comment by singharpit94** [comment]
Any timelines on when these experimental API will be available as part of stable builds.

**Comment by jacty** [comment]
It seems createRoot() is available now without the unstable prefix?

**Comment by singharpit94** [comment]
I don't think so, ReactDOM does not have any method named createRoot

**Comment by gaearon** [comment]
>Any timelines on when these experimental API will be available as part of stable builds.

This year seems very likely. You can track progress in https://github.com/facebook/react/issues/13206.

>It seems createRoot() is available now without the unstable prefix?

Yes, but only in the `@experimental` releases.
