### ISSUE TITLE
Optimization: Remove else branch will never be reachable.

### ISSUE THREAD

**Issue by jacty** [facebook/react#21530]
https://github.com/facebook/react/blob/3f8f4675d499ebf8f20cf02ee34aa16045a648b6/packages/react-reconciler/src/ReactFiberHooks.new.js#L614

I assume this part will never be reached during hook mount phase, workInProgressHook will be reset to null in RenderWithHooks() and get and updated in updateWorkInProgressHook(). Even if the Fiber has been deleted and rebuilt again, the workInProgressHook should be null for sure in mount phase. Is it necessary for us to delete this else part as a kind of OCD and code-clean level optimization,please?

**Comment by bvaughn** [comment]
`mountWorkInProgressHook` can be called multiple times for a given component. When it's called, it either initializes the hooks queue (stored in `memoizedState`) or adds another hook to the linked list (aka `previousHook.next = nextHook`)
