### ISSUE TITLE
Bug: onClick handler not called on mobile Safari / iPhone

### ISSUE THREAD

**Issue by rohankeskar19** [facebook/react#21533]
React version: 17.0.2

## Steps To Reproduce

1. Add onClick event to any element
2. Test that onClick is working on mobile device

Link to code example:

## The current behavior
onClick event is not firing on mobile devices, I already tried the cursor: pointer fix, But it is still not working

## The expected behavior
onClick event should get fired on all devices

**Comment by bvaughn** [comment]
@rohankeskar19 Please share a Code Sandbox (or a GitHub project) that shows the broken behavior _and_ please specify which types of devices you've tested and seen this behavior on.

For example, I just tried this sandbox on my Pixel (Android) and it worked fine:
https://codesandbox.io/s/nice-margulis-zlmxh?file=/src/App.js

**Comment by rohankeskar19** [comment]
https://codesandbox.io/s/ancient-wood-76y53, This is the code sandbox, and the device I'm trying is iphone, It is also not working in the dev tools of chrome

**Comment by ShroXd** [comment]
it works fine on my Safair/iPhone11 (14.4.2), maybe it's a bug on iPhone

**Comment by rohankeskar19** [comment]
> it works fine on my Safair/iPhone11 (14.4.2), maybe it's a bug on iPhone

Can you try this site - https://www.notealy.com and click on the nav buttons then try it on desktop, those buttons are supposed to scroll to the section

**Comment by bvaughn** [comment]
Have you confirmed that they're not scrolling specifically _because the click handler isn't called_? Or could it be something else (CSS or animation code)

**Comment by rohankeskar19** [comment]
I have confirmed that the scrolling is working, It works on desktop as well as the mobile mode in the browser but when I try it on actual device it doesn't work

**Comment by bvaughn** [comment]
How have you confirmed that the click handler is not being called? (Considering a small repro like I posted above shows that click handlers do get called on mobile.)

**Comment by OleksiiMarchenk0** [comment]
Hello, @rohankeskar19 .
Please share your problematic code (maybe link etc.)?
In the meantime please see my code here [Implementing onClick in React](https://github.com/OleksiiMarchenk0/Todo-App/blob/5aea5342241b498823e6e1467dd4a06ac8a4631b/src/components/Todo.jsx#L44) which implements onClick in React.
I checked it and on my iPhone 8 this code works. :)

**Comment by todortotev** [comment]
Works on iPhone 12 pro as well.

**Comment by Rodanus** [comment]
@rohankeskar19  What causes this problem is CSS. I've recorded this video to show you what's happening. I hope it explains the reason behind this behavior well.


https://user-images.githubusercontent.com/40541141/121196304-0840e200-c879-11eb-8ee8-25578541b6bb.mp4
