### ISSUE TITLE
Create Benchmark Suite

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2154]
We should create a new benchmark suite for patterns that are relevant to React.

We should write test for four different target audiences:
- JS Engine (Low-level micro-benchmarks of important language features like Object.assign)
- DOM Engine (Low-level micro-benchmarks of document.createElement, innerHTML, cloneNode, updating and setting the .style property etc.)
- React Core Engine (Low-level and real worlds tests of the React algorithm before the DOM layer.)
- Integration Benchmarks (Real world DOM tests that benchmarks the whole thing.)

We need to figure out what format to use for all these benchmarks and how easy they are to incorporate into the engines' benchmark suites.

We should also set up a more stable CI environment to track regressions. The one we have now is too noisy.

**Comment by myocytebd** [comment]
Hi, is there some benchmark for "React Core Engine"?
I am building a framework like react-native on v8, and find that "wasted" time is a major bottleneck.
(5-10ms for 20-30 nodes, on 1.9G SandyBridge)

**Comment by gaearon** [comment]
@trueadm did some work on creating (4) but we haven't used it much. Browser vendors have worked on tests involving React too.

I don't think it's likely we'll be spending our time on this so I'll close this.
