### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by uddeh007** [facebook/react#21550]

**Comment by KZ-Lucas** [comment]
use `useState`

setState is use only class component

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
