### ISSUE TITLE
Bug: Events bug

### ISSUE THREAD

**Issue by actualchao** [facebook/react#21554]
Why the disabled button cannot trigger the mouse leave, mouseEnter, and mouseMove events of the parent container div
React version:
17.0.2

## Steps To Reproduce

The reproduction steps are very simple, the code is in codesanbox

Link to code example:
https://codesandbox.io/s/focused-firefly-cd9nf?file=/src/App.tsx

## The current behavior
disabled button cannot trigger the mouse leave, mouseEnter, and mouseMove events of the parent container div

## The expected behavior
Normally trigger events like vue and native code

**Comment by ShahirZain** [comment]
this is not a bug .. . . you are disabling the first button but the rest are enabled and they all are in parent tag. When you enter the in the parent tag from the enable button , its log in console . . . so the issue is in your code
