### ISSUE TITLE
Remove _debugID field from Fiber

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21558]
This DEV-only field was added in 836331ba5f69f2cc53b273ec073fae116db14302 by @sebmarkbage but it's not being used anymore to my knowledge.

**Comment by Pulkit3234** [comment]
@bvaughn sir, can I work upon this issue?

**Comment by bvaughn** [comment]
This issue is all yours @Pulkit3234  😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by Pulkit3234** [comment]
Thanks sir, hope this time I make a successful PR, haha!

**Comment by jacty** [comment]
I am currently using _debugID to tell which Fiber node get issues. It is quite useful for me to find the dirty Fiber when there are many similar Fibers going through reconciler phase. As you said they are not used anymore, if we have any other better solutions to target a dirty Fiber ?

**Comment by Pulkit3234** [comment]
@bvaughn sir, I am not able to find the fiber file in the scripts folder, so can you kindly guide me on how do I proceed with working upon this issue?

**Comment by bvaughn** [comment]
@jacty Fibers are an internal data structure and aren't meant to be accessed or used by non-React code. Can you explain more about what you're doing and how?

@Pulkit3234 React source code isn't in the "scripts" folder. It's in the "packages" folder. I suggest searching the project for `_debugID` to see which places need to be updated. 😄

**Comment by jacty** [comment]
> @jacty Fibers are an internal data structure and aren't meant to be accessed or used by non-React code. Can you explain more about what you're doing and how?

Sometimes, it is hard to figure out where the property is. Take an example, if I want to get a state in children components but failed, I will go to Fiber to check why and which Fiber failed to get the state by setting breakpoint based on debugID one by one instead of basing on the complicated state object.

**Comment by bvaughn** [comment]
@jacty Okay, so long as you aren't writing+releasing code that uses Fibers (or this field) then that sounds fine :) You could set a conditional breakpoint based on `type` maybe (e.g. `fiber.type === SomeFunctionComponent`).

**Comment by Pulkit3234** [comment]
@bvaughn sir, I made the changes and submitted the pr as well, can you please have a look at it 😄.
