### ISSUE TITLE
[Feature Request]: Add array of updated deps indices to `useEffect` hooks arg

### ISSUE THREAD

**Issue by myckhel** [facebook/react#21560]
I would like to request adding the indices of updated dependencies of `useEffect`, `useLayoutEffect` as arg of the callback.

## For example:

if `dep1` and `dep3` changes, then indices of the dependencies that triggers the update should be passed to the callback as argument.

```jsx
useEffect((updatedIndices) => {

  console.log(updatedIndices); // Array [1,3]

}, [dep1, dep2, dep3])
```

I think this feature will be useful for most of us all.

**Comment by LXSMNSYC** [comment]
any example scenarios of why this would be useful?

**Comment by myckhel** [comment]
### This is just one example use case
*Allow component modify prop internally*
### Good

```jsx
const InternalState = ({value, checked}) => {
  const [_checked, setChecked] = useState(checked)
  const [_value, setValue] = useState(value)
  
  // better
  useEffect((indices) => {
    if(indices === 1){
      setValue(value + ' appends');
     }
    
     if(indices === 2){
      setChecked(checked + ' appends');
     }
  }, [value, checked])

}
```
### Can improve
```js
  useEffect(() => {
      setValue(value + ' appends');
  }, [value])
  
  // can improve
  useEffect(() => {
      setChecked(checked + ' appends')
  }, [checked])
```

### Bad
```js
  useEffect(() => {
    // possible unnecessary state update if value not changed
    setValue(value + ' appends');

    // possible unnecessary state update if checked not changed
    setChecked(checked + ' appends');
  }, [value, checked])
```

My actual use case would be too complicated to show here.

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.
