### ISSUE TITLE
Minor inconsistency: charSet JSX attribute won't get lowercased in the HTML output

### ISSUE THREAD

**Issue by axtk** [facebook/react#21571]
Unlike other JSX attributes (e.g. `contentEditable`), `charSet` remains unchanged in the HTML output produced by the ReactDOMServer's render methods, which results in a minor inconsistency.

```jsx
// `charSet` remains unchanged, while the other camel-case
// attributes are lowercased
console.log(ReactDOMServer.renderToStaticMarkup(
    <>
        <meta charSet="utf-8"/>
        <meta httpEquiv="refresh" content="3"/>
        <div contentEditable/>
    </>
));
```

Looks like adding `['charSet', 'charset']` to [`packages/react-dom/src/shared/DOMProperty.js`](https://github.com/facebook/react/blob/5890e0e692d1c39eddde0110bd0d123409f31dd3/packages/react-dom/src/shared/DOMProperty.js#L266-L269) could fix it.

**Comment by bvaughn** [comment]
Seems like this is actually expected behavior 😄 

See #10863 and https://github.com/facebook/react/issues/11492#issuecomment-342953964

**Comment by axtk** [comment]
oh, thanks for the links :)

> I decided not to fix this. Again, it's not a bug: technically HTML allows attributes to have any casing. We're strictly doing less work on React side, and it doesn't make sense to me to do more work to make the output more aesthetically consistent.

not a bug indeed, but maybe the sheer number of such reports calling for the aesthetic consistency could justify such a fix though :)

**Comment by bvaughn** [comment]
> We’re hesitant about this. **HTML is case-insensitive** so technically our behavior is correct even if a little surprising. There's absolutely nothing wrong with emitting attributes with any casing, even `DaTeTiMe` would be perfectly understood by browsers, and the difference would be completely unobservable for the client-side code.
>
> Though we potentially can “fix” this to be less surprising (https://github.com/facebook/react/pull/11110) we’re not confident it won’t lead to a slight performance regression. So it might not be worth it. We’d need data from people using SSR in production to tell if this would be a problem or not.
