### ISSUE TITLE
Settings Extensions

### ISSUE THREAD

**Issue by chaya-blau** [facebook/react#21589]
where do i change the  definition 
allow acces to file url
i dont find this definition
thanks

**Comment by bvaughn** [comment]
@chaya-blau I'm not sure what you're asking, but I assume you're asking about how to enable the setting for a Chrome extension.

If you open the extension details in your browser: chrome://extensions/?id=fmkadmapgofadopljbjfkapdkoienihi

You should see this option as one of the settings:
![Screen Shot 2021-05-31 at 10 54 54 AM](https://user-images.githubusercontent.com/29597/120211233-b1933280-c1fe-11eb-8406-ffed27cb521a.png)

Hope this helps.

**Comment by gauravverma029** [comment]
hi
