### ISSUE TITLE
react dev tools installed but not working

### ISSUE THREAD

**Issue by hopkins199** [facebook/react#21604]
I have installed it several times but react dev tools are not working on my chrome browser

**Comment by bvaughn** [comment]
Hi!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

With a bug report like this it's important to provide details like the following:
* Which version of Chrome are you using?
* What operating system?
* Which website(s) are you trying to use DevTools on that it's not working?
* What do you mean by "not working"? (A video or explanation would be helpful.)

**Comment by bvaughn** [comment]
I'm going to close this issue because it doesn't have enough info for one of us to reproduce it.
