### ISSUE TITLE
Bug: unable to render to document when using createRoot

### ISSUE THREAD

**Issue by aweary** [facebook/react#21603]
With `react@next` and `react-dom@next` trying to create a root with `document`:

```jsx
const root = ReactDOM.createRoot(document);
root.render(<App />);
```

Throws the error:

```
HierarchyRequestError
Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
```

https://codesandbox.io/s/infallible-resonance-gqu0j?file=/src/index.js

**Comment by gaearon** [comment]
I think you want `{hydrate: true}` on the `createRoot` call. Not the individual `render` call.

**Comment by aweary** [comment]
@gaearon ah yeah, you're right. though the error does occur without `hydrate` https://codesandbox.io/s/tender-gauss-8cvm0?file=/src/index.js though rendering to `document` when not hydrating is probably less common

**Comment by gaearon** [comment]
>rendering to document when not hydrating is probably less common

Is that something we previously supported?

**Comment by aweary** [comment]
> is that something we previously supported?

It does work with `ReactDOM.render` https://codesandbox.io/s/zen-currying-r0ewz?file=/src/index.js

**Comment by eps1lon** [comment]
@sebmarkbage confirmed recently that this is intended:
> `Document` also doesn't really work on `createRoot`. Only `hydrateRoot` should have `Document` as an option.
> 
> You can however pass `document.documentElement` to createRoot which is slightly different.


-- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59059#discussion_r828512028

It would help if this issue contains a concrete use case beyond "it worked before".

**Comment by eps1lon** [comment]
This will be supported in React 19. The original sandbox "just works" in the latest Canary release: https://codesandbox.io/p/sandbox/stupefied-cloud-wmcj43?file=%2Fpackage.json%3A9%2C51
