### ISSUE TITLE
Bug: when use functional component and custom hooks in App.js to init react at the root element,an error of Invalid hook call happened

### ISSUE THREAD

**Issue by JokerSora** [facebook/react#21609]
e,my last bug report was closed,but that wasn't the bug I had met
here look at my code https://codesandbox.io/embed/intelligent-moore-yl6kz?fontsize=14&hidenavigation=1&theme=dark
look at the index.js  (clear the App.js line4), when I use a functional component and use the function to return a component to render the root element,it works well
however,when I added the hooks (the App.js line4),It went wrong.
then It's no matter with the way of init react
`import ReactDOM from "react-dom";
import App from "./App";
const app = App(); // This works when the App returns React.createElement("div",null,"test"); without use custom hooks
ReactDOM.render(app, document.getElementById("root"));
`

**Comment by bvaughn** [comment]
React components cannot be invoked as regular functions. Hooks _will not work_ in this case. React components are meant to be passed as elements to React for it to manage when they are called.

I'm going to close this issue (like #21599).

**Comment by JokerSora** [comment]
> React components cannot be invoked as regular functions. Hooks _will not work_ in this case. React components are meant to be passed as elements to React for it to manage when they are called.
> 
> Put another way, it is _expected_ not to work if you call `App()` as a function.
> 
> I'm going to close this issue (like #21599).

could you reply me after you see my code?
I said it worked well using regular functions to init react at root element.
open this https://codesandbox.io/embed/intelligent-moore-yl6kz?fontsize=14&hidenavigation=1&theme=dark and then ensure it,OK?
