### ISSUE TITLE
Bug: setState run twice  with own hooks

### ISSUE THREAD

**Issue by avairain** [facebook/react#21626]
React version: 17.0.2

## Steps To Reproduce

1. click .App
2. 

Link to code example:
```js
const useL = (service) => {
  const [l, setL] = useState([])
  const [ab, setAB] = useState({});
  const load = async () => {
    const res =  await service()

    setAB((t) => {
      // LOG twice
      console.log("22222");
      setL([...l, ...res.l]);
      return t;
    });
  }
  useEffect(() => {
    load()
  }, [])

  return {
    list: l,
    load
  }
}

export default function App() {
  const [a, setA] = useState([]);
  const {load} = useL(() => {
    return new Promise(res => {
      setTimeout(() => {
        setA(1)
        res({
          l: [1, 2]
        })
      }, 2000)
    })
  })  

  const handle = () => {
    load();
  };
  return (
    <div className="App" onClick={() => handle()}>
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}
```

Why  log twice

**Edited** by @bvaughn to fix formatting.

**Comment by bvaughn** [comment]
Why is one state updater function calling another one? This looks like an odd pattern to me:
```js
const [l, setL] = useState([]);
const [ab, setAB] = useState({});
const load = async () => {
  const res = await service();

  setAB((t) => {
    setL([...l, ...res.l]); // <- Why is setAB's update function calling setL?
    return t;
  });
};

```

Anyway React runs certain things twice in DEV mode to help flush out any unsafe side effects. This includes state updater functions, like the one shown above.

You can read more about why we do this here:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

It's only done in DEV mode and should not affect anything so long as your components don't have side effects.

**Comment by bvaughn** [comment]
Going to close this question because I think it's been answered. If not, let me know.

**Comment by avairain** [comment]
got The latest data

**Comment by avairain** [comment]
> Going to close this question because I think it's been answered. If not, let me know.



> Why is one state updater function calling another one? This looks like an odd pattern to me:
> 
> ```js
> const [l, setL] = useState([]);
> const [ab, setAB] = useState({});
> const load = async () => {
>   const res = await service();
> 
>   setAB((t) => {
>     setL([...l, ...res.l]); // <- Why is setAB's update function calling setL?
>     return t;
>   });
> };
> ```
> 
> Anyway React runs certain things twice in DEV mode to help flush out any unsafe side effects. This includes state updater functions, like the one shown above.
> 
> You can read more about why we do this here:
> https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
> 
> It's only done in DEV mode and should not affect anything so long as your components don't have side effects.

got The latest data

**Comment by avairain** [comment]
> > Going to close this question because I think it's been answered. If not, let me know.
> 
> > Why is one state updater function calling another one? This looks like an odd pattern to me:
> > ```js
> > const [l, setL] = useState([]);
> > const [ab, setAB] = useState({});
> > const load = async () => {
> >   const res = await service();
> > 
> >   setAB((t) => {
> >     setL([...l, ...res.l]); // <- Why is setAB's update function calling setL?
> >     return t;
> >   });
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Anyway React runs certain things twice in DEV mode to help flush out any unsafe side effects. This includes state updater functions, like the one shown above.
> > You can read more about why we do this here:
> > https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
> > It's only done in DEV mode and should not affect anything so long as your components don't have side effects.
> 
> got The latest data

like a tab 
I will get some data from serice;
before xhr response, change the tab
I need the latest current tab to set the response data
