### ISSUE TITLE
Failed Compile

### ISSUE THREAD

**Issue by knolcoder** [facebook/react#21633]
React version: Latest Version

When i compile it say's this  : -

./src/App.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/App.css)
Error: Can't resolve '../img/01.jpg' in 'F:\portfolio\src'

**Comment by Janlay884181317** [comment]
Seem like the problem form your bundle builder......

**Comment by knolcoder** [comment]
solved
