### ISSUE TITLE
Bug: Functional component and conditional rendering resulting in "Cannot update a component while rendering a different component" warning

### ISSUE THREAD

**Issue by Link631** [facebook/react#21663]
React version: 17.02

## Steps To Reproduce

1. Create an react app
2.install latest fluent ui
3. createa functional component with following code:

```
import { loadTheme, Spinner } from "@fluentui/react";
import React, { useEffect, useRef, useState } from "react";
import { createListViewManager } from "../helper/CreateListViewManager";

export interface ICustomListViewProps {
  webUrl: string;
  listName: string;
  viewName: string;
}
export const CustomListView: (props: ICustomListViewProps) => JSX.Element = (
  props: ICustomListViewProps
): JSX.Element => {
  loadTheme({
    palette: {},
  });
  const [listData, setListData] = useState<any[] | undefined>(undefined);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  const loadMyDemoData = async (): Promise<any[]> => {
    await new Promise((resolve) => setTimeout(resolve, 3000));
    return [];
  };
  useEffect(() => {
    const loadData = async (): Promise<void> => {
      const listInfos = await loadMyDemoData();

      setListData(listInfos);
      setIsLoading(false);
    };
    loadData();
  }, []);

  if (isLoading) {
    return <Spinner label="loading..."></Spinner>;
  }

  return <>loaded data</>;
};

```

## The current behavior

When the component sets isLoading to false, then the warning appears in the log:
```
react-dom.development.js:67 Warning: Cannot update a component (`StyledSpinnerBase`) while rendering a different component (`CustomListView`). To locate the bad setState() call inside `CustomListView`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at CustomListView

```
The same happens when I put everything into one return statement with && ()...

## The expected behavior
When isLoading is being set to false, then the conditional rendering schould be possible without any warnings. This is just a basic loading spinner szenario. Am I doing something wrong or is it an issue?

**Comment by vkurchatkin** [comment]
This doesn't seem to be an issue with React. It could be a problem _fluentui_.

Also, _loadTheme_ call in the component looks suspicious. It probably shouldn't be there.

**Comment by Link631** [comment]
> This doesn't seem to be an issue with React. It could be a problem _fluentui_.
> 
> Also, _loadTheme_ call in the component looks suspicious. It probably shouldn't be there.

So do you think that the code, expect of the loadTheme is OK regarding the setIsLoading with the conditional rendering?

**Comment by Link631** [comment]
I will close this Issue. I found out, that the setTheme call causes some unexpected behaviour within my component. I moved this part outside of my Components closer to the App and for now the warnings do not appear.

Thanks for the hint with the theme setting.
