### ISSUE TITLE
null props considered differently in getDefaultProps vs. isRequired

### ISSUE THREAD

**Issue by jeanlauliac** [facebook/react#2166]
In the case a `null` argument is passed to a property marked as `isRequired`:
http://jsfiddle.net/jeanlauliac/0n6snb6b/1/

We'll get a proper warning in the console: `Warning: Required prop `name` was not specified in `Hello`.` (though it should probably be "prop was null" and not "prop was not specified", but anyway)

On the other hand, the default value is only used when the prop is `undefined`, but not when it's `null`. Is this the explicitly wanted behavior? If it is, then we should probably make the documentation explicit about it (http://facebook.github.io/react/docs/reusable-components.html), giving the entire responsibility to component callers of safeguarding against `null`.

**Comment by HurricaneJames** [comment]
I was curious if there was a decision on @jasonkuhrt 's suggestion to make `getDefaultProps` override `null` as well as `undefined`? As pointed out, it is possible to keep `null` in the suggested solution if it is really desired, but it is currently not possible to override it if you do not.

**Comment by mull** [comment]
Is this being discussed anymore?

**Comment by HurricaneJames** [comment]
I do not believe it is. Back in February I tried patching a fork of React.js to make components treat null the same as undefined. The change is fairly simple, but there are several tests saying they specifically want null to override the defaults. Personally, I think this one tiny part of React.js is crazy, but I'm certain FB has an internal use case. In the end I found it easier to rewrite my internal ajax/json library to automatically replace `null` with `undefined` when fetching data.

**Comment by mull** [comment]
I don't know, to me it's fine if it accepts `null` - what bothers me is that's the only behaviour if you want to require a prop. Perhaps ugly, but something like `PropTypes.string.notNull` although with a better name would work just fine. An alternative to `isRequired` simply.

**Comment by tomatau** [comment]
Bump!

To specify the absence of a property should be explicit per property... E.g. a func would prefer to specify a noop, a string might want either null or an empty string, a number may even want to specify NaN as an absence.. This is easily possible with getDefaultProps... until `null` doesn't trigger this default and suddenly we have to use defensive programming throughout our components.

Null is a complicated language feature... The semantics around this need to be made more clear as debugging against null when getDefaultProps are specified is a pain point - especially when you don't have full control over the data source.

I would prefer to see a `React.PropTye.__.allowNull` so that this can become more clear and explicit behaviour per property with minimal boilerplate and clear semantics.

**Comment by jarsbe** [comment]
A bit of a different scenario but if anyone finds this useful...

I wanted null to have a default prop.

`<Avatar src={user.avatar_url} />`

If null is passed in null gets used rather than the default prop. That makes sense since null is not an undefined value. To get the default value I just did the following, explicitly send in undefined if the url is null.

`<Avatar src={user.avatar_url || undefined} />`

**Comment by AlexCoder25** [comment]
@jarsbe Thank you so much! I has problems with default props and I just used undefined as you did.

**Comment by jedverity** [comment]
Published a quick `nullable` prop type helper here: https://gist.github.com/jedverity/23715563d2b74d0ae5bb

Thanks to @jasonkuhrt and Glenjamin (IRC) and everyone else on this thread.

**Comment by koulmomo** [comment]
can I get clarification on whether it is safe to access `this.props` inside of `getDefaultProps` as an escape hatch with regards to `null` as described [here](https://github.com/facebook/react/issues/2166#issuecomment-63984996)?

**Comment by sebmarkbage** [comment]
No, `this.props` is not available inside `getDefaultProps` because it gets called before there even is a `this`.

**Comment by koulmomo** [comment]
Is there a recommended workaround for supporting returning default props when an optional prop is `null`?

I currently have an API that returns nested `JSON` structures with `null` values where I ideally would want defaults. To avoid 

> having to write repetitive and fragile code
> 
> &mdash; [react docs](https://facebook.github.io/react/docs/reusable-components.html#default-prop-values)

I can think of two workarounds that do not require changes in how `getDefaultProps` behaves (if there are no plans to have `getDefaultProps` handle this use case the workaround would of course become permanent).

1. manually parse the API response replacing `null` values with `undefined` where appropriate

2. adding a custom `getProps` method which I call in my `render` function to fetch a local `props` `var`. 

```js
module.exports = React.createClass({
  displayName: 'Foo',

  getProps: function getProps() {
    return {
      bar: this.props.bar || 'baz'
    };
  },

  render: function render() {
    var props = this.getProps();

    return (<div>{props.bar}</div>);
  }
});
```

**Comment by jDeppen** [comment]
+1 for isRequiredOrNull (or similar)

I'm using a custom validator because I want to ensure a prop is specified but I don't care if it's null
```
customProp: (props, propName, componentName) => {
  // allow null but ensure propName is specified
  if ( props[propName] === undefined ) {
    return new Error('Validation failed!');
  }
}
```

**Comment by idMolotov** [comment]
+1 for isDefined / isRequired

**Comment by milj** [comment]
+1. Null value should be treated as defined.

**Comment by gaearon** [comment]
I wouldn't expect there to be further changes to PropTypes. Flow has become much more mature recently, and from what I heard from the React team, it is the longer term solution to type checking. This puts PropTypes into the same "compatibility" bucket in terms of priorities—like createClass or React addons, they are still supported, but only with bugfixes and performance improvements, without adding new features or changing the API.

(Note: this is not an official position, but my impression of it based on conversations in other threads.)

**Comment by tmcw** [comment]
Interesting - is there a current alternative to getDefaultProps based on Flow types?

**Comment by wardpenney** [comment]
+1 for isDefined / isRequired

**Comment by aweary** [comment]
Since PropTypes is no longer part of React core, I'm going to close this out. I've opened an issue for this in repo for the `prop-types` package: https://github.com/facebook/prop-types/issues/110

**Comment by jharris4** [comment]
If anyone's still interested in `isDefined / isRequired`, there's a PR for it here: https://github.com/facebook/prop-types/pull/90
