### ISSUE TITLE
Bug: Scroll position reset when inserting items at the beginning of a list

### ISSUE THREAD

**Issue by christian-schulze** [facebook/react#21675]
React version: 17.0.2

## Steps To Reproduce

1. Render a button and a scrollable list with a height of 150px. The list should contain an array of 15 items, making sure to set the `key` prop of each item to unique values.
2. Observe that you can see around 8 of the original 15 list items in view.
3. On clicking the button, insert 15 more items into the _**beginning**_ of the list, once again making sure to set the `key` prop of each item to unique values.
4. Observe that you can now see around 8 of the _**new**_ list items in view.

Link to code example: https://codesandbox.io/s/keen-sound-7q5yf?file=/src/App.js

## The current behavior
If the scroll position is at the very top of a list, after inserting new items at the beginning of the list, the _**new**_ items are now visible.

## The expected behavior
If the scroll position is at the very top of a list, after inserting new items at the beginning of the list, the _**original**_ items should remain visible.

**NOTE:** When the scroll position is 1 or more pixels from the top of a list, after inserting new items at the beginning of the list, the _**new**_ items remain visible as expected.

**Comment by pythonmaxi** [comment]
I don't think it is not a bug, neither a react problem, it is just how the DOM behaves when you prepend elements to a scrollable area.

**Comment by christian-schulze** [comment]
@pythonmaxi that would be unfortunate if true. I will do some pure DOM testing to see if this is the case.

**Comment by christian-schulze** [comment]
@bvaughn I've created another codesandbox here https://codesandbox.io/s/lively-browser-shpit?file=/src/index.js. Pure DOM behaves the same way, so this is not a React issue. Closing this issue.

**Comment by bvaughn** [comment]
Thank you for the update!
