### ISSUE TITLE
React 18 

### ISSUE THREAD

**Issue by pradeep-mishra** [facebook/react#21670]
Just a suggestion

In React 18 , React should accept extra params to setState function so dev can specify what changed in more general terms that he/she can use in `React.memo()` to determine if that changes should re-render the specific component with the new data  

it should be something like this 

```javascript
setState(
  [...state.users, user], 
  {action:'USER_ADDED', id : 'some_id'}
);
```

the broadcast can be any arbitrary data

and then  in the User component, we can catch that broadcast in React.memo() like this

```javascript
const User= (user)=>{
   // component code   
}
```

```javascript
export default React.memo(User, (prev, next, brodcast)=>{
  if(broadcast?.action === 'ACTION_ADDED'  &&  next.id !== broadcast.id){
   // should not re-render this component
   return true;
 }
 return false;
});
```

this should work with batch setState as well just instead of object, broadcast should have an array of broadcasts

this will save the devs from deep comparison of props if it holds a lot of data nodes in it.

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.

**Comment by bvaughn** [comment]
I'm going to close this issue because I think it's out of scope for a version 18 discussion thread. RFC with a more in-depth proposal and analysis of the pros and cons would probably be the only way for a feature like this to potentially move forward.
