### ISSUE TITLE
Inner required fields in shaped props not reported properly

### ISSUE THREAD

**Issue by jeanlauliac** [facebook/react#2168]
See this example:
http://jsfiddle.net/jeanlauliac/2x3dk23m/1/

The console only report: `Warning: Required prop `bar` was not specified in `Hello`.`. It should probably report the whole path to the inner field, such as `test.bar`.

**Comment by aweary** [comment]
This is no longer an issue when using the `prop-types` library: https://jsfiddle.net/7o687z00/
