### ISSUE TITLE
Some way to fuzz setState timing/usage

### ISSUE THREAD

**Issue by maxim-engr** [facebook/react#21708]
One of the more common problems people have with setState is stale refs or other timing and concurrency mistakes. For native code, we have things like Application Verifier's concurrency fuzzer, which can randomly delay some APIs to see if user code correctly handle uncommon timing issues.

So, why don't we have something like that for React APIs like setState? Randomly delay them for a set time? It looks like there's some internal fuzzing to test React's own correctness, but I don't see anything that I could enable to fuzz my React code.

**Comment by gaearon** [comment]
Can you provide some examples of the specific issues you've encountered? Even as pseudocode. I don't think we've seen a lot of situations where user-level code would benefit from fuzzing so I'm curious what you're running into with regards to `setState`.

**Comment by gaearon** [comment]
Examples would still be helpful :) I didn't mean to shut down the suggestion!

We've been considering some kind of a "chaos mode" but real use cases would help understand this space.
