### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Stardust101** [facebook/react#21716]
Test <b>1234<b/>
<img src="http://img.alicdn.com/tfs/TB1sdP.Q8LoK1RjSZFuXXXn0XXa-48-48.png">
hello

**Comment by eps1lon** [comment]
Great to see you trying to get into open source.

Please experiment with markdown (e.g. https://dillinger.io/) or pull requests (see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request for further documentation) on a personal repository. Opening Pull Requests or issues creates notifications for maintainers and everyone watching this repository.
