### ISSUE TITLE
[DevTools Bug]: Settings panel layout broken

### ISSUE THREAD

**Issue by thany** [facebook/react#21718]
### Website or app

https://www.enexis.nl/

### Repro steps

Website is actually irrelevant, but required.

1. Open the devtools
2. Press the settings button.
3. Observe the layout being broken (causing horizontal scrollbar).

Screenshot
![image](https://user-images.githubusercontent.com/152227/122902511-cb7feb00-d34e-11eb-9656-29f5c9c62194.png)

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment]
@thany Can you provide some more information? Browser (and version), operating system (and version), DevTools extension version, etc.

I can't reproduce this.

**Comment by thany** [comment]
Firefox 89, Windows 10, latest extension. It's really not that far-fetched.

**Comment by bvaughn** [comment]
@thany I'm not sure why there's hostility in your responses (both to this issue and #21717). This is a free software product and I'm trying to help (though I'm not required to). Providing basic info like browser and operating system version along with a bug report is generally useful, regardless of how far fetched you think the configuration is :smile:

**Comment by heytulsiprasad** [comment]
Not sure if this is confirmed by anyone else, but I can reproduce this on Firefox. I'll paste my device information so you can try that out in order to repro. 

How it looks:
![image](https://user-images.githubusercontent.com/52394293/123203090-702b3580-d4d3-11eb-94da-6373e9ceb890.png)

Machine: Windows 10 Home
Browser: Firefox version 89.0.1 (64-bit)

Let me know if you need more details, I'll be more than happy to take this up.

**Comment by bvaughn** [comment]
Update: If I enable scroll bars on OS X, I can also reproduce this in Firefox. Should be able to fix it then. (Did not have access to a Windows machine to test with.)

**Comment by thany** [comment]
> 
> 
> @thany I'm not sure why there's hostility in your responses (both to this issue and #21717). This is a free software product and I'm trying to _help_ you. Providing basic info like browser and operating system version along with a bug report is generally useful, regardless of how far fetched you think the configuration is 😄

Sorry mate, but I don't understand the question then. You asked for browser & OS, and I gave that exact answer. That's really, honestly, genuinely, everything needed to a repro. I've seen this on every pc running Windows 10 + Firefox so far, which is why it's not that far-fetched. I don't see how that's hostile.

And actually, we're trying help *each other*, aren't we 😉
