### ISSUE TITLE
React 18: Error boundaries actually catches errors in effects

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#21712]
Given
```js
function ThrowInEffect() {
  React.useEffect(() => {
    throw new Error('passive effect')
  }, [])
  return null;
}
```

In React 17 this error got logged to the console (and triggered the error overlay in create-react-app) regardless of whether `ThrowInEffect` was a child of an Error Boundary or not.

In React 18 (`createRoot` and legacy root API) an Error Boundary will prevent logging that error to the console (and not trigger the error overlay in create-react-app).

Errors during render work like they did in React 17.

Behavior in React 17: https://codesandbox.io/s/react-17-error-boundaries-vp21e?file=/src/index.js
Behavior in React 18: https://codesandbox.io/s/react-18-error-boundaries-psd56?file=/src/index.js

Recording of effect errors in React 17 and 18 and with and without Error Boundaries_

https://user-images.githubusercontent.com/12292047/122749780-053ced00-d28e-11eb-98ce-075dcdc53ee2.mp4

**Comment by eps1lon** [comment]
Update: React 18 behaved as 17 in dbe3363cc but changed in 7ec4c5597. Looking at dbe3363cc...7ec4c5597 I suspect https://github.com/facebook/react/pull/21666 changed the behavior. The error is no longer logged when I try the [codesandbox build](https://ci.codesandbox.io/status/facebook/react/pr/21666/builds/139750) from https://github.com/facebook/react/pull/21666

**Comment by gaearon** [comment]
Thanks for catching this. Pun intended. Fix is in https://github.com/facebook/react/pull/21723.
