### ISSUE TITLE
Bug: Old bug Invariant Violation, happens ONLY in production

### ISSUE THREAD

**Issue by Bluefitdev** [facebook/react#21726]
React version: 17.0.2

Hello everyone,

I'm sorry if this is unclear, however some bug appeared in our app couple of days ago. The bug describes as this:

```
Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Which translates to this in react website:
```
findDOMNode was called on an unmounted component.
```

We did not upgrade anything, we just developed features as usual. However up until now I haven't been able to solve it because it doesn't happen locally at all. Thus I am not able to debug this thing.

Weirdly if it only happens if i refresh the page, also only happened at 2 route, i.e: `/home` and `/login`. If i refresh the page with any other route, then it works.

The problem is it doesn't happen on localhost so I really have no idea what this is. 

The project is company's based so I don't think i can share the codebase, however i will share some of the most important details that I think is causing this issue?

We are using `craco` and `lerna` in monorepo packages.

here's our craco config:
```
const cracoBabelLoader = require('craco-babel-loader');
const fs = require('fs');
const path = require('path');
const cracoIncludeLernaPackagePlugin = require('./craco-include-lerna-package-plugin');

// Handle relative paths to sibling packages
const appDirectory = fs.realpathSync(process.cwd());
const resolvePackage = relativePath => path.resolve(appDirectory, relativePath);

module.exports = {
	plugins: [
		{
			plugin: cracoBabelLoader,
			options: {
				includes: [resolvePackage('../formik-material'), resolvePackage('../naked-forms')]
			}
		}
	],
	style: {
		postcss: {
			plugins: [require('tailwindcss'), require('autoprefixer')]
		}
	}
};
```

Is anyone experiencing the same issue? Please help

Also our cloud setup is using GCP Cloud Storage, loaded from Google Load Balancer with CDN option below if that helps:

![Screen Shot 2021-06-23 at 4 41 03 pm](https://user-images.githubusercontent.com/56941349/123048563-dd8e8600-d441-11eb-9988-5c67aa9cf6f2.png)

Thanks in advance

**Comment by kirkhla** [comment]
Are you updating state in findDOMNode ?
