### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Stardust101** [facebook/react#21727]
Test <b>12345<b/>
<img src='' onerror='alert("test xss" + document.cookie)'>
hello
```html
<img src='' onerror='alert(123)' alter='图片没有，弹窗了吗？' width='120px' height='120px'/>
```

**Comment by eps1lon** [comment]
Great to see you trying to get into open source.

Please experiment with markdown (e.g. https://dillinger.io/) or pull requests (see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request for further documentation) on a personal repository. Opening Pull Requests or issues creates notifications for maintainers and everyone watching this repository.
