### ISSUE TITLE
[DevTools]: Show which context(s) changed for function components

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21736]
`getContextChangedKeys` only handles class components:
https://github.com/facebook/react/blob/355591add41c0f6dad738fdb1b6603e0786b7b4e/packages/react-devtools-shared/src/backend/renderer.js#L1276-L1304

**Comment by byronluk** [comment]
@bvaughn mind if I take a stab at this?

Been looking through the code and seems like the right way to get the context for a functional component is off the fiber dependencies. I wasn't able to find a way to obtain the legacy context off a Fiber node of a functional component, so is it okay if we only support the modern context here?

**Comment by bvaughn** [comment]
> mind if I take a stab at this?

Yes! Please go for it 😄 

> is it okay if we only support the modern context here?

Yes! That sounds good

**Comment by byronluk** [comment]
thanks! I submitted a PR here: https://github.com/facebook/react/pull/22047

Haven't got around to adding tests yet since I couldn't find any existing test cases for this particular behavior, so I still need to look deeper there. But I wanted to get some eyes on the change in the meantime 😅
