### ISSUE TITLE
Bug: Rendering an array of arrays doesn't warn developer about missing key=""

### ISSUE THREAD

**Issue by radex** [facebook/react#21731]
React version: 17.0.2

Normally, when rendering an array of elements, React in dev mode helpfully warns the developer that they goofed and didn't include a key="":

```js
{[1, 2, 3].map(n => <span>{n}</span>)} // Warning: Each child in a list should have a unique "key" prop.
```

However, when we render an array of arrays, no such warning is displayed:

```js
{[1, 2, 3].map((n) => [<span key="sure i have a key, trust me!">{n}</span>])} // No warning! Buggy!
```

I can't think of a reason why someone would _legitimately_ want to display an array of arrays (If they would, they'd render an array of Fragments with a key assigned). However, this **can happen by accident quite easily** when e.g. preparing a list of React elements from some nested structure, something like this:

```js
// Waay oversimplified version of something that I wrote:
function renderTasks(tasks) {
  return tasks.map(t => <Task task={t} key={t.id} />)
}

function renderSections(sections) {
  const elements = []
  // ...
  sections.forEach(section => {
    const renderedSection = renderTasks(section.tasks)
    // Oops! Should be elements.push(... renderedSection)
    elements.push(renderedSection)
  })
  // ...
  return elements
}
```

Obviously, this is not good. If, say, first section is removed, everything that follows will be unmounted and mounted again (since the innermost `<Task/>`s do have a key, and those key will differ, none of them will be reused).

What makes it worse is that elements of an array are flattened when displayed in React devtools, so it's difficult to notice that I actually rendered an array of arrays - in devtools it looks like a flat array of items, each with its own key — and yet, on every render, "siblings" with the same key have their render.

## Steps To Reproduce

Link to code example: https://codesandbox.io/s/winter-haze-o1tq4

## The current behavior

Nothing happens, and a rendered list's elements don't have a key

## The expected behavior

```
Warning: Children of a list should not be an array. Change the inner array elements to a <React.Fragment /> and assign a unique "key" prop. 
```

**Comment by jjoel1630** [comment]
Hello @radex. I tried this out, and a warning is thrown if I render an array of arrays.

**Comment by radex** [comment]
this is still relevant
