### ISSUE TITLE
Bug: The default response could not be deleted

### ISSUE THREAD

**Issue by dataangel** [facebook/react#21735]
![image](https://user-images.githubusercontent.com/587849/123149464-e314bc00-d493-11eb-9bbf-f47890f87381.png)

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by dataangel** [comment]
Create a project arbitrarily 
yarn create react-app my-app --typescript
F12->
![image](https://user-images.githubusercontent.com/587849/123187542-f3955880-d4cc-11eb-9871-49fe9d7eceb3.png)

**Comment by eps1lon** [comment]
@dataangel I'm not sure what the problem is with the screenshot. React attaches two handlers: one for the capture phase and one for the bubble phase. Both of them are passive.

**Comment by dataangel** [comment]
https://ant.design/components/drawer/
F12->
![image](https://user-images.githubusercontent.com/587849/123213120-3587c400-d4f8-11eb-8510-66b81ba20d40.png)
touch
report errors Unable to preventDefault inside passive event listener invocation.
So i want to Remove

**Comment by eps1lon** [comment]
Thanks for the clarification. You should report this bug to https://github.com/ant-design/ant-design

**Comment by dataangel** [comment]
thank you
