### ISSUE TITLE
Using window.open w/Apollo Client, followed by a state update seems to crash / freeze app

### ISSUE THREAD

**Issue by dannycochran** [facebook/react#21749]
Calling `window.open()` with a timeout to close (e.g. to help a user get a new authentication session) with a simple usage of Apollo Client's `useQuery`, followed by any state update, seems to crash / freeze the app. There's no stack trace / render thrashing / obvious functions which are being called in an infinite loop.

Obviously the React team is not responsible for bugs which are coming from Apollo Client. However, I'm not sure if it's an Apollo Client bug or an issue w/React. The reason I'm unsure is that upgrading to React 17.0.1 fixes the issue, which makes me suspect it could be a bug in the version of React where I found the issue (16.14.0).

I understand if this bug just gets closed immediately, I'm mostly just curious if this sounds like a known bug or issue to the React team, though it might be hard to diagnose without understanding the internals of the Apollo Client.

Here is the bug I filed with Apollo client which includes a minimal reproduction repository:
https://github.com/apollographql/apollo-client/issues/8427

React version: **16.14.0**

## Steps To Reproduce

1. Clone this repository and checkout to `strangeReactBug` branch: https://github.com/dannycochran/usequery/tree/strangeReactBug

2. Open Chrome (not reproducible in Safari)

3. Click "Sign in and sign out", wait for the window to return.

4. Repeat step 2 until the app is crashed.

Link to code example:

https://github.com/dannycochran/usequery/tree/strangeReactBug

## The current behavior

The app will crash / freeze after the opened window closes.

## The expected behavior

The app would not crash / freeze.

## Workaround

Upgrade to React 17.0.1

**Comment by bradjones1** [comment]
I'm running into a similar situation, however am not using Apollo. Calling `window.open` after a state update seems to effectively crash React.

**Comment by bradjones1** [comment]
In my case it appears the order of operations was the culprit. Not sure if this is a bug or just an edge case in how React does its state-management automagic, but doing

```
setTheState(value);
window.open(...);
```

caused React to effectively crash, however doing the opposite worked as expected.


```
window.open(...);
setTheState(value); // Results in the usual state update stuff.
```
