### ISSUE TITLE
a memory leak problem.

### ISSUE THREAD

**Issue by wufeng87** [facebook/react#21753]
I am running into a memory leak problem in my app which is too complex to make a small reproducible demo.

The images below show that the `stateNode` holds the Detached HTMLDivElement in my app, but I have no idea why I encounter this situation. And I wonder how could I find the source of this kind of memory leak problem. Thanks.
![image](https://user-images.githubusercontent.com/1686808/123402984-e49ccc00-d5da-11eb-9a49-9a817a93aee8.png)
![image](https://user-images.githubusercontent.com/1686808/123403269-304f7580-d5db-11eb-8534-a0d0aefaecb9.png)

React version: 16.13.1

Link to code example:

## The current behavior
memory leak

## The expected behavior
find the source of the memory leak problem.

**Comment by atom217** [comment]
The detached element may come due to third-party lib , theme, or perhaps any modal/hidden component  on the page 

You need to provide more details. Not a react js bug
