### ISSUE TITLE
Bug: react-hooks/exhaustive-deps rule doesn't allow to use empty array as deps if effect uses values from component

### ISSUE THREAD

**Issue by jtoming830** [facebook/react#21750]
If you use state value or any other values from component in useEffect and deps are empty then eslint-plugin-react-hooks throws warning/error. It's impossible to run useEffect on only first render without eslint ignore or useRef

React version: 16.13.1
eslint-plugin-react-hooks version: 4.1.2

## Steps To Reproduce

```
  const [val, setVal] = useState();

  useEffect(() => {
    val;
  }, []);
```

Link to code example:
https://codesandbox.io/s/naughty-smoke-f5mhz?file=/src/App.js

## Possible workarounds
```
  const [val, setVal] = useState();
  const firstRender = useRef(true);

  useEffect(() => {
    if (firstRender.current) {
      firstRender.current = false;
      val;
    }
  }, [val]);
```

```
  const [val, setVal] = useState();

  useEffect(() => {
    val;
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

## The current behavior

Linter throws warning/error. 

## The expected behavior

Linter doesn't throw warning/error.

**Comment by rajkapadia247** [comment]
This is intentional. Your effect is making use of ````val```` so it should be present in the list of dependencies. Please note that passing an empty array isn't completely equivalent to componentDidMount.

Just like you said, the solution here is the add ````eslint-disable-next-line````.

**Comment by eps1lon** [comment]
Thanks for the feedback.

As Raj already said, this is intended behavior.

Hopefully the [docs about `useEffect`](https://reactjs.org/docs/hooks-effect.html) help you understand why `val` should be listed in the dependency array.
