### ISSUE TITLE
I don't see a React tab in my Chrome Dev tools, also, so I'm not quite sure how to access the dev tools at all to be honest. Here is what I see in my Chrome settings:

### ISSUE THREAD

**Issue by lufei162** [facebook/react#21758]
I don't see a React tab in my Chrome Dev tools, also, so I'm not quite sure how to access the dev tools at all to be honest. Here is what I see in my Chrome settings: 

![screen shot 2015-05-14 at 3 50 58 pm](https://cloud.githubusercontent.com/assets/910753/7628735/0a85e094-fa51-11e4-8f9d-dea75ae9339d.png)

_Originally posted by @RichardLitt in https://github.com/facebook/react/issues/3877#issuecomment-101975101_

**Comment by rajkapadia247** [comment]
Can you try accessing a website that makes use of React (https://facebook.com or https://netflix.com) and check developer tools? I accessed them and I see this.
![image](https://user-images.githubusercontent.com/47295446/123520900-dcbf5380-d6d0-11eb-8957-27d2ca679370.png)

**Comment by bvaughn** [comment]
The tab won't show up unless you are on a website built with React (such as [reactjs.org](https://reactjs.org) 🙇🏼 Sorry for the confusion

**Comment by GARBAGEPLAY** [comment]
> The tab won't show up unless you are on a website built with React (such as [reactjs.org](https://reactjs.org) 🙇🏼 Sorry for the confusion

Doesn't show up on reactjs.org either. Why would this be?
