### ISSUE TITLE
The primary branch has been renamed from "master" to "main"

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21767]
# Renaming `master` branch to `main`

As a part of a broad effort to avoid problematic terminology in our software, we are renaming our default branch from `master` to `main`. We recognize that this is only a small step, but it is an opportunity to make our project and community more welcoming to historically marginalized communities.

## How does this impact my development process?

There should be very little impact. GitHub will surface the branch name change in your fork, if you have one. For new forks, you will automatically have `main` as the default branch.

We encourage the use of feature branches for local development. The only change in practice is changing which branch your feature branch is started from. When sending Pull Requests on GitHub, the target will default to our `main` branch, so there are no changes to make there.

## I have a lot of tools that depend on `master` being the upstream branch name. How can I fix that?

`master` has always been only a default value and a number of projects have used other names for their primary development branch for years. We encourage updating your tooling to instead dynamically determine the branch to use. [This article](https://aj.codes/post/branch-agnostic-git-aliases/) provides insight into how you can do that. Additionally, you can always set up a branch locally of any name to track our `main` branch.

## I'd like to do this for my own projects, do you have any documentation on how this works?

[GitHub has published a guide documenting their tooling.](https://github.com/github/renaming) We recommend reading that and the accompanying documentation.

If you're a Facebook employee looking to do this for a project you maintain, please reach out to the Open Source Team.

## My PR is failing because of `ci/circleci: get_base_build`
This is because the `master` branch has been renamed to `main`, but our Circle CI scripts used to refer to `master` by name. To fix this, just rebase your branch on top of `main` to get the latest version of the Circle CI scripts:
```sh
git fetch origin
git rebase -i origin/main
```

**Comment by bvaughn** [comment]
In case it is helpful for others, ere is a list of steps I have taken for this transition:

- [x] Create this pinned issue to inform the community.
- [x] @bvaughn: Update Circle CI [main branch configuration](https://app.circleci.com/projects/github/facebook/react/config/?branchName=master&pipelineNumber=) to update branch references (e.g. download artifacts for size comparison) 
- [x] Update config and build/release scripts: #21768
- [x] Change the primary branch for the React repo from `master` to `main`.
- [x] Update reactjs.org documentation referring to "master" branch: https://github.com/reactjs/reactjs.org/pull/3756
- [x] Update internal Facebook sync scripts

**Comment by bvaughn** [comment]
Need to follow up on why d483463bc86555decb3e8caa18459d1d0f7c0148 triggered a failed deployment of the scheduling profiler:
https://app.circleci.com/pipelines/github/facebook/react/15233/workflows/77f4dd14-e1ed-43cf-9979-b5a5f4c15976/jobs/334771

**Comment by bvaughn** [comment]
Note that, unfortunately, it seems like existing PRs might be broken by this change after all– until they rebase on `main`– because of our Circle CI scripts which refer to "master" explicitly.

Ideally we would have auto-detected the primary branch in these scripts (e.g. `git remote show origin | sed -n '/HEAD branch/s/.*: //p'`) so they would just switch over automatically. I didn't think to do that prior to flipping the switch though, so we'll just have to make the best of it now. At least it's a one time pain, easily remedied.

**Comment by gaearon** [comment]
We can probably close this now.
