### ISSUE TITLE
Can React please tell me what state was being set, when performing "a React state update on an unmounted component"

### ISSUE THREAD

**Issue by shanike** [facebook/react#21763]
So I got the well-known error:
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

And I'm finding it super hard to find the setState that is being done after the component was unmounted.

Any chance of getting a bit more information as to what state is trying to update, or on what line? 

Very well appreciate

**Comment by rj33536** [comment]
Hi there, let's suppose you fetch some data from an API in your useEffect/componentDidMount and then you do `setData(response.data)`. While the data was being fetched, you move to some other page causing the component to unmount. When the request get completed, then your callback function tries to execute the setData statement. Here, the component i unmounted but you still tried to change the state of a component. I hope this helps.

**Comment by gaearon** [comment]
> And I'm finding it super hard to find the setState that is being done after the component was unmounted.

Next to the error message on the left, there is an arrow. Click the error and you will see the stack trace. One of the frames will be the exact line where setState happened. This is how all console errors work.

**Comment by shanike** [comment]
Yes I'm aware to all that. But my app was big enough for me to not know what setState caused the error. The stack was semi-compiled code, so the frame directed me to the wrong place, and I already checked all my useEffects.

I ended up adding ```if (unmounted) return``` in all my set states, then finding that it was a problem with setTimeouts for animation etc.

I'm specifically wondering if React knows the name of the state, trying to be updated, so it can tell help the search after the wrong setState statement

Thanks

**Comment by 0xorial** [comment]
> Next to the error message on the left, there is an arrow. Click the error and you will see the stack trace. One of the frames will be the exact line where setState happened. This is how all console errors work.

Is it supposed to show exact line where it was called? I am using dev mode with create-react-app with TypeScript, and it shows the component, but not the specific line.
