### ISSUE TITLE
[DevTools] Combine view highlighting code

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21777]
DevTools currently has two views that manage highlighting things in the DOM:
* [`backend/views/Highlighter`](https://github.com/facebook/react/tree/main/packages/react-devtools-shared/src/backend/views/Highlighter): highlights the DOM for the currently selected element
* [`backend/views/TraceUpdates`](https://github.com/facebook/react/tree/main/packages/react-devtools-shared/src/backend/views/TraceUpdates): highlights the DOM when a component renders/updates

It would be nice if this was refactored to use a single, Canvas-based solution.

**Comment by sj-rai** [comment]
Can I pick up this issue?

**Comment by bvaughn** [comment]
@sj-rai This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by sj-rai** [comment]
Sure, thanks!

**Comment by bvaughn** [comment]
How's it going, @sj-rai? Making any progress? Any questions?

**Comment by sj-rai** [comment]
@bvaughn Had some issue implementing the "inspect" using canvas, got it somewhat working now. That was what you meant by "canvas-based solution" right?. Also working on moving the 2 directories into 1. And also, to test my changes, I'm building the standalone devtools and using it in my react app.. Is this how I'm supposed to test my changes? because standalone devtools does not have updates highlighting.

**Comment by bvaughn** [comment]
> I'm building the standalone devtools and using it in my react app.. Is this how I'm supposed to test my changes? because standalone devtools does not have updates highlighting.

No, I'd test using the extension version. Instructions can be found [here](https://github.com/facebook/react/tree/main/packages/react-devtools-extensions#download-from-ci):

### Install dependencies
```sh
cd scripts/release
yarn install
./download-experimental-build.js
```

### Build and test the extension:
```sh
cd packages/react-devtools-extensions/

yarn build:chrome # => packages/react-devtools-extensions/chrome/build
yarn run test:chrome # Test Chrome extension
```

**Comment by sj-rai** [comment]
@bvaughn Thanks!. This is much better!

**Comment by sj-rai** [comment]
@bvaughn I have created a PR, pls let me know if any changes are needed.
