### ISSUE TITLE
[DevTools bug] Extension not showing on browser

### ISSUE THREAD

**Issue by KingsleyIbe** [facebook/react#21789]
I have installed React dev tools extension but can't see it in the inspect window.

**Comment by bvaughn** [comment]
The DevTools extension isn't visible unless you're viewing a website built with React, like www.reactjs.org.

**Comment by KingsleyIbe** [comment]
@bvaughn Thank you for your feedback. DevTools bug is still not showing both on the referenced link and my local react app.

Please find details below:
Operating system: windows 10, browser: Google Chrome, Version 91.0.4472.124 (Official Build) (64-bit), DevTools,: React Developer Tools 4.13.5 Website Not Working: www.reactjs.org and http://localhost:3000 (my react app on my local computer).

Also, find below images showing error messages.

Thank you.
![Devtools Bug Extention](https://user-images.githubusercontent.com/43799727/124362999-8e5e0780-dc30-11eb-9cc0-7cb25785fc16.jpg)
![Errors - DevTools Bug page1](https://user-images.githubusercontent.com/43799727/124363010-9fa71400-dc30-11eb-8407-54598abc1c1f.jpg)
![Errors - DevTools Bug page2](https://user-images.githubusercontent.com/43799727/124363012-a0d84100-dc30-11eb-8f82-2c7b1f26c7a8.jpg)

**Comment by bvaughn** [comment]
Hm. Have you tried restarting Chrome?

I don't really have many ideas.

**Comment by KingsleyIbe** [comment]
Yes I have. I have also uninstall devTools and reinstall. And problem still persist. 

Maybe I should try another browser like Mozilla. Thanks for your concern

**Comment by bvaughn** [comment]
No problem. I have no idea. Have you tried disabling other extensions (like Redux DevTools) just to rule out something else interfering?

**Comment by KingsleyIbe** [comment]
Hi @bvaughn 

DevTools is working fine now. I have to uninstall and reinstall, and then reboot pc.

Thanks for the help.

**Comment by bvaughn** [comment]
Thanks for the update.

**Comment by KingsleyIbe** [comment]
You're welcome
