### ISSUE TITLE
[DevTools] Fix Circle CI to run all DevTools tests

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21780]
Circle CI only runs some of the DevTools tests, e.g.
https://app.circleci.com/pipelines/github/facebook/react/15329/workflows/8547df20-d3cd-4795-b2f0-a4bbe9e39a9e/jobs/336119

Run locally:
![Screen Shot 2021-07-01 at 11 30 25 AM](https://user-images.githubusercontent.com/29597/124153268-3bcef080-da62-11eb-8b49-a7422fc09f43.png)

Run on CI:
![Screen Shot 2021-07-01 at 11 29 59 AM](https://user-images.githubusercontent.com/29597/124153265-3bcef080-da62-11eb-86e6-e2f9ed85da5d.png)

Presumably there's something wrong with our [CircleCI config file](https://github.com/facebook/react/blob/main/.circleci/config.yml) or one of the Jest configuration files elsewhere.

**Comment by houssemchebeb** [comment]
@bvaughn can i take this one ?

**Comment by bvaughn** [comment]
Yup! :)

**Comment by bvaughn** [comment]
@houssemchebeb This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by houssemchebeb** [comment]
Thanks!

**Comment by leogiertz** [comment]
I believe that it already runs all of the tests but split among several different containers.

Check here:
https://app.circleci.com/pipelines/github/facebook/react/15400/workflows/9ba94cb2-cbb6-4351-9f40-aad74171168c/jobs/337002/parallel-runs/0?filterBy=ALL

![Screenshot 2021-07-02 at 00 51 59](https://user-images.githubusercontent.com/124863/124197892-cef23f80-dacf-11eb-901b-aaff34e84757.png)
![Screenshot 2021-07-02 at 00 51 44](https://user-images.githubusercontent.com/124863/124197894-d0bc0300-dacf-11eb-972d-bdbeedb22d77.png)

**Comment by bvaughn** [comment]
Oooh, I believe you're right. I wasn't reading the Circle CI UI correctly. So DevTools tests are broken into 20 parallel containers, each one running only a couple of tests.

That makes sense! I think we can close this issue then as my mistake 😁
