### ISSUE TITLE
[DevTools] Use line number and column number to match hook

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21792]
DevTools named hook parsing logic currently matches AST nodes using the original line number:
https://github.com/facebook/react/blob/ed6c091fe961a3b95e956ebcefe8f152177b1fb7/packages/react-devtools-extensions/src/parseHookNames.js#L341-L346

But this may not be sufficient, as mentioned in comment https://github.com/facebook/react/pull/21641#discussion_r662951987:
> Are we assuming that a line number is sufficient to identify a hook call? Seems like that assumption breaks down in edge cases:
>
> 1. Minified code (either without a source map, or a bundle *built* from pre-minified inputs) can have multiple hooks on one line.
> 2. Some code might be authored with quirky formatting, i.e. not with a typical Prettier / ESLint setup.

**Comment by motiz88** [comment]
While we're on the subject: Column numbers in particular are where a lot of inconsistencies between tools/engines' representations occur and off-by-one errors creep in.

* V8, SpiderMonkey, JSC all use 1-based lines and 1-based columns in `Error.stack`.
  * Hermes follows the other engines for the most part but has its own thing going on for bytecode addresses (printed similarly to columns but 0-based). See the [Hermes-specific parsing logic](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/parseHermesStack.js) in React Native.
* VS Code uses 1-based lines and 1-based columns.
* The `source-map` library (at least AFAIK from older versions) uses 1-based lines and 0-based columns in its API.
* ESTree/Babel ASTs use 1-based lines and 0-based columns.
* The Chrome DevTools protocol uses 0-based lines and 0-based columns.

So I suspect we have an incorrect conversion [here](https://github.com/facebook/react/blob/ed6c091fe961a3b95e956ebcefe8f152177b1fb7/packages/react-devtools-extensions/src/parseHookNames.js#L324) already - we should fix it and signpost assumptions/conversions more clearly.

**Comment by bvaughn** [comment]
Reopening to address this follow up comment from @motiz88:
https://github.com/facebook/react/pull/21833#discussion_r666831276
