### ISSUE TITLE
React's JSX doesn't support namespace tags How do I set `throwIfNamespace: false`

### ISSUE THREAD

**Issue by krishnadevz** [facebook/react#21807]
Error 

> ./src/components/svg/traveller.js
> SyntaxError: /home/krishnadevz/jadoo/src/components/svg/traveller.js: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.
>    5 |         return (
>    6 |             <div>
> >  7 | <svg width="765" height="764" viewBox="0 0 765 764" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
>      |                                                                                                    ^^^^^^^^^^^
>    8 | <rect width="765" height="764" fill="url(#pattern0)"/>
>    9 | <defs>
>   10 | <pattern id="pattern0" patternContentUnits="objectBoundingBox" width="1" height="1">

React version:18

## Steps To Reproduce

1.I am importing a Figma file as an SVG and then I saving it in class-based react component and then export and using it in other components and that file is throwing an error. 

Link to code example:https://codesandbox.io/s/traveller-9q5qy

## The current behavior
Throwing error React's JSX doesn't support namespace tags

## The expected behavior
It should be worked fine and also there is no .babelrc file so that I can set namespace : false i created and did it but still, it is not working please fix this issue or give a temp fix.

**Comment by DanielRocheford** [comment]
bump
