### ISSUE TITLE
State updated properly, DOM not updated accordingly

### ISSUE THREAD

**Issue by gitwikc** [facebook/react#21805]
### Why is the last sibling component being deleted instead of the desired one?

I created a component called `Node` which has a state with two properties: `name` and `children`. `name` stores the `Node`'s name and `children` stores the child `Node`s. You can add children and nest them, but when you try to delete one, it always deletes the last *sibling* `Node` instead.

#### NOTE 
> In the React DevTools component tab, the state updates properly and the desired child is deleted from the `children` property of the `Node`'s state, but on the DOM, the *last sibling* is deleted whereas the one desired to be deleted is not.

### Screenshots :computer: 
![github-react-node-children-issue](https://user-images.githubusercontent.com/60361305/124649654-667fd580-deb6-11eb-86f3-5bd4af7d0ba4.png)
As seen, state updates properly, removing the **child 1** `Node`, but the DOM updates differently, removing the **child 3** `Node`, which is the *last sibling*

### Reproduce
- [ ] Open the sandbox
- [ ] Create some child `Node`s by clicking on `+` button
- [ ] Name each child `Node` differently by typing the name in the textfield saying "Node name"
- [ ] Try to delete any child that is not the *last sibling*, by clicking the `-` button near the respective textfield
- You will notice that the *last sibling* `Node` gets removed instead of the desired `Node`

**Comment by bvaughn** [comment]
> As seen, state updates properly, removing the child 1 Node, but the DOM updates differently, removing the child 3 Node, which is the last sibling

At a glance, I'd guess this is because your test app is specifying the array index as the item key:
```js
          {state.children &&
            state.children.map((child, i) => {
              return (
                <li className="child_node" key={i}>
                  <Node
```

Deleting an item from the array then removes the last child (with the formerly highest index).

**Comment by gitwikc** [comment]
> > As seen, state updates properly, removing the child 1 Node, but the DOM updates differently, removing the child 3 Node, which is the last sibling
> 
> At a glance, I'd guess this is because your test app is specifying the array index as the item key:
> 
> ```js
>           {state.children &&
>             state.children.map((child, i) => {
>               return (
>                 <li className="child_node" key={i}>
>                   <Node
> ```
> 
> Deleting an item from the array then removes the last child (with the formerly highest index).

@bvaughn Thank you for pointing out the problem; Thank you thank you so much!!! :smiley: It worked!!! I assigned random id's to children using `nanoid` and used it to delete them from the children array. You're a lifesaver :heart:

**Comment by bvaughn** [comment]
You're welcome!
