### ISSUE TITLE
Bug: Safari does not load lazy-imported components when re-entering site

### ISSUE THREAD

**Issue by ksendra** [facebook/react#21809]
On the iOS version of Safari lazy load of components (with React.lazy) does not always work correctly. If you enter the website everything works fine, but if you then close Safari through the app drawer and open it up again - the website does not load the components again and the site is stuck in Suspense fallback. The only way to get it to work again is to click refresh in the browser. Then all the components are fetched again.  

React version: 16.14.0

## Steps To Reproduce
(Does. not work on iOS simulators, encountered on deployed production builds only)

1. Enter a deployed site that users React lazy loading and React Suspense on iOS device
2. Open app drawer
3. Close Safari
4. Open Safari again

## The current behavior

Result: the app is stuck on Suspense fallback (loading spinner in my case). Maybe iOS safari caching or storage optimization has something to do with it. It seems that resuming the app does not prompt component load.

## The expected behavior

When resuming the website (by opening Safari again) everything should load up again.

**Comment by ntoka** [comment]
Update: same behavior occurs on macOS Safari (14.1.1 for Big Sur). Although this does not occur on Safari Technology Preview version.

**Comment by ntrphongse** [comment]
I ran into a quite same issue with React v17.0.2. But my react app does not load for the first time to access it through Safari, a blank page is displayed and when I reload the web, everything is fine. It is quite annoyed for the user if the web is blank as first sight. Hope you fix this soon

**Comment by ablajievschii** [comment]
Safari 15.4, React v16.13.1 - Sometimes lazy loaded components not  rendered, sometimes styles are not correctly loaded, so UI is broken.

**Comment by stevengragg** [comment]
Any update on this? Experienced the same problem with reactjs 18.2.0 since I implemented lazy import of components on most parts of our web app. The initial fix is to change to normal import. 

- newbie dev

**Comment by mit2u** [comment]
Its still happening with Safari
