### ISSUE TITLE
Bug: unstable_flushDiscreteUpdates when rendering <video muted />

### ISSUE THREAD

**Issue by reaktivo** [facebook/react#21810]
React version: 17.0.2

## Steps To Reproduce

1. Rendering `<video muted />` triggers "Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering"

```jsx
import * as React from "react";
import * as ReactDOM from "react-dom";

test("should render without calling console error", () => {
  jest.spyOn(console, "error").mockImplementation(() => {});
  const container = document.createElement("div");
  document.body.appendChild(container);

  ReactDOM.render(<video muted />, container);
  expect(console.error).not.toHaveBeenCalled();
});

```

Link to code example:

https://codesandbox.io/s/sad-waterfall-ks59l?file=/index.test.js:0-384

## The current behavior
Calls `console.error` with un-actionable error

## The expected behavior
Doesn't call `console.error` or calls it with a potential solution

**Comment by gaearon** [comment]
This appears fixed in 18.

https://codesandbox.io/s/react-video-element-bug-forked-p3sitc?file=/index.test.js
