### ISSUE TITLE
Strict effects and unmounted ref flag

### ISSUE THREAD

**Issue by otakustay** [facebook/react#21844]
Posting this issue to share a common phenomenon related to strict effect, I have created a sandbox to demonstrate this issue: https://codesandbox.io/s/unmount-guard-in-strict-effect-5eneb?file=/src/App.js

Previously this is a common practice to have a `unmounted` ref indicating whether current component is unmounted, and to prevent calls to `setState` after unmount in order to get rid of those ugly console warnings.

With react 18's strict effect, the intentional "mount -> unmount -> mount" steps may break some unmounted ref implements, the [ahooks implementation](https://github.com/alibaba/hooks/blob/7b026c03dde61449b051bb63ba68507115227cda/packages/hooks/src/useUnmountedRef/index.ts) is incorrect while the [react-use implement](https://github.com/streamich/react-use/blob/90e72a5340460816e2159b2c461254661b00e1d3/src/useMountedState.ts) is correct.

We can simply fix it by "revive" this ref in mount effect:

```
const unmounted = useRef(false);
useEffect(
  () => {
    // Add this line!
    unmounted.current = false;
    return () => {
      unmounted.current = true;
    };
  },
  []
);
```

Still, I have 3 questions related to this:

1. In real world concurrent mode, is there a chance that `fakeFetch` may resolve after component is unmounted and before it is remounted?
2. Is this mean that we **should not** guard our `setState` calls with an unmounted ref flag? Maybe simply allow `setState` on an "unmounted" component can perfectly fix this problem.
3. Since we don't want to cancel fetch in unmount (maybe this is a side effect, or duplicated request can hit performance), is there any recommended practice to handle such situations?

**Comment by bvaughn** [comment]
> With react 18's strict effect, the intentional "mount -> unmount -> mount" steps may break some unmounted ref implements, the [ahooks implementation](https://github.com/alibaba/hooks/blob/7b026c03dde61449b051bb63ba68507115227cda/packages/hooks/src/useUnmountedRef/index.ts) is incorrect while the [react-use implement](https://github.com/streamich/react-use/blob/90e72a5340460816e2159b2c461254661b00e1d3/src/useMountedState.ts) is correct.

The [react-use implement](https://github.com/streamich/react-use/blob/90e72a5340460816e2159b2c461254661b00e1d3/src/useMountedState.ts) looks like what we recommend: set to true in the create function and set to false in the destroy function. This symmetry usually makes a component robust to unmounting and remounting, [as we mention in our Working Group post](https://github.com/reactwg/react-18/discussions/18).

> 1. In real world concurrent mode, is there a chance that `fakeFetch` may resolve after component is unmounted and before it is remounted?

I'm not sure what `fakeFetch` is. If it completed after unmounting (or while hidden), I assume you would still want to ignore the response though? (Even if a component is hidden, it may be thrown away without being shown again. (In that case, there wouldn't be a second render or "unmount". The "hide" is effectively the same as an "unmount".)

> 2. Is this mean that we **should not** guard our `setState` calls with an unmounted ref flag? Maybe simply allow `setState` on an "unmounted" component can perfectly fix this problem.

This warning exists because it sometimes uncovers memory leaks (e.g. event listeners that should have been cleaned up during unmount). Actually calling `setState` is a no-op (except for the DEV warning).

> 3. Since we don't want to cancel fetch in unmount (maybe this is a side effect, or duplicated request can hit performance), is there any recommended practice to handle such situations?

Why don't you want to cancel the fetch in unmount? If you have the ability to cancel, it's probably a good idea because (as I mentioned above) an unmount could be final.

**Comment by otakustay** [comment]
> Why don't you want to cancel the fetch in unmount? If you have the ability to cancel, it's probably a good idea because (as I mentioned above) an unmount could be final.

Although it may be finally unmounted, it also can be remounted in a very short time. In most cases we don't want a network fetch being started in mount effect, canceled immediately and re-triggered again in - for example - 1 second, we just want to reuse that request.

A fetched response, like any other state, is a simple state. Since the concurrent mode say "unmount and remount with all state preserved", I'd like to explain it as "fetch response should also be preserved" like it never unmounts

I believe suspense data fetching is a good solution to this problem, but currently most fetch implementation in react is based on `setState` after promise resolve.

**Comment by bvaughn** [comment]
> Although it may be finally unmounted, it also can be remounted in a very short time. In most cases we don't want a network fetch being started in mount effect, canceled immediately and re-triggered again in - for example - 1 second, we just want to reuse that request.

Ideally, you should be writing your code for the production case– not the strict effects mode DEV case. The cost of cancelling and re-initializing a fetch in DEV is probably small.

> A fetched response, like any other state, is a simple state. Since the concurrent mode say "unmount and remount with all state preserved", I'd like to explain it as "fetch response should also be preserved" like it never unmounts

It's not really "state" until it's part of React state. Until then, it's just another external mutable store. So the "change in state" wouldn't be detectable (and an argument could be made for using the _latest_ value anyway I think?)

**Comment by otakustay** [comment]
Thanks for the "external mutable store" thing, this is reasonable and helped me to design a more resilient fetch hook.

**Comment by bvaughn** [comment]
Happy to hear! :)
