### ISSUE TITLE
Flow diagram of component lifecycle.

### ISSUE THREAD

**Issue by jackmahoney** [facebook/react#2184]
For new developers such as myself understanding exactly when component functions are called, such as `shouldComponentUpdate` and `render`, can be very confusing. I have read `http://facebook.github.io/react/docs/component-specs.html` many times but have failed to piece together a coherent image.

Is there a more detailed reference that perhaps contains diagrams?

If not it would be a great thing to have. In the meantime I could read the source but I think would benefit others.

Thanks

**Comment by thechrisproject** [comment]
This would still be appreciated... looks like the referencer of this issue and this issue were both closed but without the discussed resolution. Was that deliberate?

**Comment by spicyj** [comment]
@thechrisproject This issue is still open.

**Comment by thechrisproject** [comment]
@spicyj Ah, 951 is closed. Sorry about that! I'm fairly new to using github, I read that 'closed' as 'the state for this issue transitioned to closed here'

**Comment by chris-martin** [comment]
Is the diagram real? Just posting it to this issue wold be better than nothing.

**Comment by chris-martin** [comment]
Here's a quick attempt in case it provides some inspiration... https://gist.github.com/chris-martin/2424924e7a7494d5f98c

**Comment by eduardoboucas** [comment]
Here's my take on it, hopefully someone will find it handy: http://codepen.io/eduardoboucas/full/jqWbdb/

**Comment by Aweary** [comment]
@eduardoboucas very cool, love the interactive format!

**Comment by bjrmatos** [comment]
@eduardoboucas looks very cool!

**Comment by gaearon** [comment]
[New reference](https://facebook.github.io/react/docs/react-component.html) lists lifecycles by phase:

<img width="849" alt="screen shot 2016-10-23 at 14 18 23" src="https://cloud.githubusercontent.com/assets/810438/19626518/c9c25576-992b-11e6-988f-5e2c83977fb7.png">

I think we can close this.
