### ISSUE TITLE
React 18 : useState 'sharing' state value between components of the same type

### ISSUE THREAD

**Issue by DiegoHerrera262** [facebook/react#21850]
I created a custom table component that has pagination, search bar and export to excel button. The main usage of the component is as follows:

```jsx
<ClientsTable
   dataset={sellsInfo}
   Headers={sellsInfoHeaders}
   downloadFileName={`OrdenesCliente-${clientId}`}
   pageSize={2}
   identifier={'id'}
/>  
```

To enable pagination, global filter and dataset download, I used state variables using `useState` hook, as follows. 

```jsx
const ClientsTable = (props) => {
   let { dataset, Headers, pageSize, actions, identifier, downloadFileName } = props;
                          
   const [ displayDataset, setDisplayDataset ] = useState(dataset);
   const [ pageIndex, setPageIndex ] = useState(0);
   const numPages = Math.ceil(displayDataset.length / pageSize);
   const [ canNextPage, setCanNextPage ] = useState(true);
   const [ canPrevPage, setCanPrevPage ] = useState(false);
   const [ sortSmallToLarge, setSortSmallToLarge ] = useState(true);
   const [ sortingField, setSortingField ] = useState(null);

   // some logic for filtering, pagination and rendering
}
```

Rendering only one table component in an app view works just fine. However, rendering two or more implies that React uses the same state variables for all table components in the view. This is unintended behavior for me. In particular, I created a custom tab component that renders two different tables on tab selection. The two tables have the same state variables, different pros though, which causes conflicts in the view.

How can I render multiple table components in my app without having this behavior?

Thanks in advance.

**Comment by bvaughn** [comment]
Unless I'm misreading, you just need to add a `key` to your tables so that React knows they are _different_. (Otherwise React has no way of knowing you want them to be different "instances")

This pattern is kind of mentioned in a blog post:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key

**Comment by bvaughn** [comment]
This isn't a question about React 18, so I'm going to tweak the tags. I also think the question has bee answered and so I'm going to close it. We can re-open if my answer is off base though.
