### ISSUE TITLE
[Proposal] Add extra props argument when calling getChildHostContext

### ISSUE THREAD

**Issue by pirelenito** [facebook/react#21878]
Hi 👋 

We are building a custom React renderer using the `react-reconciler` package and we ran in a situation where we would need to have access to the props of a instance in the call to `getChildHostContext`.

In short, here is the pseudo-code of what we need:

```tsx
const hostConfig = {
  /**
   * Our root will have a driver that is a default for the entire React tree
   */
  getRootHostContext: function (rootContainerInstance) {
    return { driver: rootContainerInstance.driver };
  },

  /**
   * But we want to allow overriding the value of the `driver` via a special tag
   * 
   * Ex: <special-tag driver={customDriver}>....</special-tag>
   */
  getChildHostContext: function (
    parentContext,
    type,
    rootContainerInstance,
    props
  ) {
    if (type === "special-tag") {
      return { driver: props.driver };
    }

    // Otherwise we forward the original parent context
    return parentContext;
  },

  /**
   * Then on creating instances (or updating) we can use the relevant driver based on the ancestor tree
   */
  createInstance: function (externalType, newProps, container, hostContext) {
    const driver = hostContext.driver;
  },
};
```

We saw that [in the implementation of the function](https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberHostContext.new.js#L77) that calls `getChildHostContext`, it has access to a `fiber` instance that has access to "props". Would something the change below make sense?

```diff
function pushHostContext(fiber: Fiber): void {
  const rootInstance: Container = requiredContext(
    rootInstanceStackCursor.current,
  );
  const context: HostContext = requiredContext(contextStackCursor.current);
-  const nextContext = getChildHostContext(context, fiber.type, rootInstance);
+  const nextContext = getChildHostContext(context, fiber.type, rootInstance, fiber.pendingProps);

  // Don't push this Fiber's context unless it's unique.
  if (context === nextContext) {
    return;
  }

  // Track the context and the Fiber that provided it.
  // This enables us to pop only Fibers that provide unique contexts.
  push(contextFiberStackCursor, fiber, fiber);
  push(contextStackCursor, nextContext, fiber);
}
```

We don't understand the internals of the Fiber/reconciler implementation and the implications it would have to expose these props. I guess a potential issue is that they change in re-renders?

Thank you so much for all the efforts on making React such a fantastic and extendable library ❤️.

cc: @xaviervia

**Comment by pirelenito** [comment]
Hi! We've found an alternative solution that no longer requires this API change.

**Comment by markerikson** [comment]
@pirelenito purely out of curiosity, what was the alternate solution? Might be worth documenting in case anyone else runs into a similar situation.
