### ISSUE TITLE
expose onTransitionEnd event for react components

### ISSUE THREAD

**Issue by shilpan** [facebook/react#2187]
An `onTransitionEnd` event for components which is normalized across all browsers supporting transitions (and fake it for those that don't using `setTimeout`).  Currently react uses `ReactTransitionEvents` internally for the `TransitionGroup`. However this is not useful in cases where you are not adding/removing a view.

**Comment by Janekk** [comment]
+1

**Comment by idris** [comment]
FYI, "faking it" as @shilpan mentioned may be harder than it seems.  Apparently the native `transitionEnd` event does not fire if the transition ends off-screen (in my case, the element is `display:block`).  So it may be better to have React just handle the native behavior for supported browsers, and let us handle any custom code for old browsers.

**Comment by idris** [comment]
FYI, "faking it" as @shilpan mentioned may be harder than it seems.  Apparently the native `transitionEnd` event does not fire if the transition ends off-screen (in my case, the element is `display:block`).  So it may be better to have React just handle the native behavior for supported browsers, and let us handle any custom code for old browsers.

**Comment by idris** [comment]
FYI, "faking it" as @shilpan mentioned may be harder than it seems.  Apparently the native `transitionEnd` event does not fire if the transition ends off-screen (in my case, the element is `display:block`).  So it may be better to have React just handle the native behavior for supported browsers, and let us handle any custom code for old browsers.

**Comment by srph** [comment]
Any update in regards to this?

**Comment by daviferreira** [comment]
:+1:

**Comment by akre54** [comment]
+1

**Comment by f0rmat1k** [comment]
:+1:

**Comment by idoros** [comment]
:+1:

**Comment by askmatey** [comment]
+1

**Comment by lucasmotta** [comment]
:+1: that would amazing ;)

**Comment by chris-lock** [comment]
:+1:

**Comment by milesj** [comment]
+1

**Comment by supasympa** [comment]
+1

**Comment by zpao** [comment]
This was fixed by #6005 & be in v15.
