### ISSUE TITLE
[React 18] Bug: `Maximum update depth exceeded` on the `ref` prop when suspending

### ISSUE THREAD

**Issue by enisdenjo** [facebook/react#21876]
Functional `ref` prop throws a `Maximum update depth exceeded` error when suspending.

React version: `18.0.0-alpha-464f27572-20210713`

## Steps To Reproduce

1. Click on the `suspend` button: https://codesandbox.io/s/ref-set-too-many-times-jm0c3?file=/src/App.js.

## The current behavior

Clicking on the `suspend` button throws a `Maximum update depth exceeded` error.

## The expected behavior

Clicking on the `suspend` button suspends.

**Comment by gaearon** [comment]
I wonder if https://github.com/facebook/react/pull/21875 fixes this.

**Comment by gaearon** [comment]
Yeah it does.
https://codesandbox.io/s/ref-set-too-many-times-forked-jl54z?file=/package.json
