### ISSUE TITLE
Bug: useState set the same value, trigger the render

### ISSUE THREAD

**Issue by ry596384086** [facebook/react#21884]
In React Hooks, useState set the same value, trigger the render

React version:17.0.2

## Steps To Reproduce
```import React, { useState } from "react";

const App = () => {
  const [Loading, setLoading] = useState(true);
  const [count, setCount] = useState(0);

  console.log('log: ', count);

  const handleClick = () => {
    setCount((pre) => pre + 1)
  };
  const handleLoad = () => {
    setLoading(true);
  }

  return (
    <div>
      <div>aa</div>
      <div>{count}</div>

      <button onClick={handleClick}>Test</button>
      <button onClick={handleLoad}>Load</button>
    </div>
  );
};

export default App;
```

1.click Load[setLoading(true)], do not trigger the render, not console.log
2.click test[setCount(pre => pre + 1)], trigger the render, console.log('log: ', 1);
3.click Load[setLoading(true)], trigger the render, console.log('log: ', 1);

why did this trigger the render when I clicked Load secondly ?

Link to code example:https://codesandbox.io/s/nifty-bohr-lqxex?file=/src/App.js

## debug

I found that the problem lies in the <b>function dispatchAction(fiber, queue, action)</b> function

```
function dispatchAction(fiber, queue, action) {
  {
    if (typeof arguments[3] === 'function') {
      error("State updates from the useState() and useReducer() Hooks don't support the " + 'second callback argument. To execute a side effect after ' + 'rendering, declare it in the component body with useEffect().');
    }
  }

  var eventTime = requestEventTime();
  var lane = requestUpdateLane(fiber);
  var update = {
    lane: lane,
    action: action,
    eagerReducer: null,
    eagerState: null,
    next: null
  }; // Append the update to the end of the list.

  var pending = queue.pending;

  if (pending === null) {
    // This is the first update. Create a circular list.
    update.next = update;
  } else {
    update.next = pending.next;
    pending.next = update;
  }

  queue.pending = update;
  var alternate = fiber.alternate;

  if (fiber === currentlyRenderingFiber$1 || alternate !== null && alternate === currentlyRenderingFiber$1) {
    // This is a render phase update. Stash it in a lazily-created map of
    // queue -> linked list of updates. After this render pass, we'll restart
    // and apply the stashed updates on top of the work-in-progress hook.
    didScheduleRenderPhaseUpdateDuringThisPass = didScheduleRenderPhaseUpdate = true;
  } else {
    if (fiber.lanes === NoLanes && (alternate === null || alternate.lanes === NoLanes)) {
      // The queue is currently empty, which means we can eagerly compute the
      // next state before entering the render phase. If the new state is the
      // same as the current state, we may be able to bail out entirely.
      var lastRenderedReducer = queue.lastRenderedReducer;

      if (lastRenderedReducer !== null) {
        var prevDispatcher;

        {
          prevDispatcher = ReactCurrentDispatcher$1.current;
          ReactCurrentDispatcher$1.current = InvalidNestedHooksDispatcherOnUpdateInDEV;
        }

        try {
          var currentState = queue.lastRenderedState;
          var eagerState = lastRenderedReducer(currentState, action); 
          // Stash the eagerly computed state, and the reducer used to compute
          // it, on the update object. If the reducer hasn't changed by the
          // time we enter the render phase, then the eager state can be used
          // without calling the reducer again.

          update.eagerReducer = lastRenderedReducer;
          update.eagerState = eagerState;

          if (objectIs(eagerState, currentState)) {
          // Fast path. We can bail out without scheduling React to re-render.
          // It's still possible that we'll need to rebase this update later,
          // if the component re-renders for a different reason and by that
          // time the reducer has changed.
            return;
          }
        } catch (error) {
        // Suppress the error. It will throw again in the render phase.
        } finally {
          {
            ReactCurrentDispatcher$1.current = prevDispatcher;
          }
        }
      }
    }

    {
      // $FlowExpectedError - jest isn't a global, and isn't recognized outside of tests
      if ('undefined' !== typeof jest) {
        warnIfNotScopedWithMatchingAct(fiber);
        warnIfNotCurrentlyActingUpdatesInDev(fiber);
      }
    }

    scheduleUpdateOnFiber(fiber, lane, eventTime);
  }
}
```

1. The first step, click the Load button, the code goes to (if (objectIs(eagerState, currentState))), and it is found that the temporary state (not yet rendered to the page) is the same as the current state (the current rendering of the page) (true-> true), return directly, do not enter the update schedule scheduleUpdateOnFiber(fiber, lane, eventTime);
2. In the second step, click the test button, the state before and after is different (count from 0->1), the code enters scheduleUpdateOnFiber(fiber, lane, eventTime); the page is rendered again.
3. In the third step, click the Load button. Since the condition if (fiber.lanes === NoLanes && (alternate === null || alternate.lanes === NoLanes)) is not met at this time, it will not proceed. If (objectIs(eagerState, currentState)) is judged, it is directly executed to scheduleUpdateOnFiber(fiber, lane, eventTime); update scheduling, resulting in the function being re-executed and the page being re-rendered even if the loading before and after the same is the same.

![image](https://user-images.githubusercontent.com/47969261/125724805-268adb54-dd70-4852-a370-eb9018405160.png)
At this moment, fiber.lanes changed from 0 to 1 (it was always 0 before), which is why trigger render.
<b>I don't understand why fiber.lanes changed from 0 to 1 in this case.</b>

**Comment by ShahirZain** [comment]
hi dear. .  this is not a bug , this is expected behavior of useState because when the value of useState is not change it will not create new memory pointer and will not rerender the component because nothing is changed. .  when you click on Test button it will change the memory pointer of the object where useState save the data so that is the reason behind this

**Comment by ry596384086** [comment]
> hi dear. . this is not a bug , this is expected behavior of useState because when the value of useState is not change it will not create new memory pointer and will not rerender the component because nothing is changed. . when you click on Test button it will change the memory pointer of the object where useState save the data so that is the reason behind this

thanks!  but I did not find the relevant source code, could you tell me which file it is in ?
