### ISSUE TITLE
typescript Missing multi forward ref ability 

### ISSUE THREAD

**Issue by RayLuxembourg** [facebook/react#21909]
**Description:**
Allow passing multiple refs using forward ref or new function that accepts refs as object containing multiple refs

Currently typescript will throw errors but it works.
Seems like only a type issue.

**Comment by RusmiselE-lattice** [comment]
@RayLuxembourg The typedefs for react are in the [`@types/react`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react) package, so that repo may be a better place for this issue. Also, a code example would make it easier to understand the problem

**Comment by bvaughn** [comment]
The React team doesn't maintain the TypeScript React definitions, so I'm going to close this issue.
