### ISSUE TITLE
Bug: useEffect not running with back-to-back renders despite dependencies changing

### ISSUE THREAD

**Issue by mogzol** [facebook/react#21914]
React version: 17.0.2

## Steps To Reproduce

Please see the example linked below. I have a `useEffect` with a dependency on some value within a ref, and I'm relying on other `useState` updates to trigger re-renders. If I change the ref value, then call a `useState` setter and also queue an immediate re-render with `setTimeout(..., 0)`, then there will be two back-to-back renders, but the Effect never fires despite the value in its dependency array changing.

For this example, you'll have to press the button more than 2 times, since oddly it works fine on the first 2 renders. Watch the console logs to see the issue.

Link to code example: https://codesandbox.io/s/react-effect-bug-x01m6?file=/src/App.js

## The current behavior

For the first press of the button, the effect will run properly. For any presses after that, the effect is no longer triggered, but you can see from the console logs that the component is re-rendering with new dependency values which should be causing the effect to run.

## The expected behavior

The effect should run whenever the values in its dependency array have changed from the previous render.

**Comment by eps1lon** [comment]
Thanks for the feedback.

The ESLint warning from `react-hooks/exhaustive-deps` already mentions this problem:
> 'ref.current' aren't valid dependencies because mutating them doesn't re-render the component.

If you want to "make a ref reactive" you can read and write the value with `useState` instead.

**Comment by mogzol** [comment]
I'm aware of the ESLint warning, I know that refs won't cause a re-render. This is still unexpected behaviour because useEffect should trigger if the dependencies have changed since the previous render. I know refs won't trigger a re-render, that's why I use `useState` or `useReducer` to cause the re-render. But when the component re-render, with *new values in the deps array*, the Effect still doesn't trigger.

That is not expected.
