### ISSUE TITLE
Components with children without DOM representation

### ISSUE THREAD

**Issue by freiksenet** [facebook/react#2191]
If I need a component that doesn't have a DOM representation, I can use render function that returns `<noscript>`. However recently I had to have a component without DOM representation, but that also has children, that I want to be mounted (so that their lifecycle methods trigger correctly). Unfortunately `<noscript>` is not nestable, thus I had to return `<span>`, which is not an ideal solution.

Is there a way to do such thing without using `<span>` or `<div>`? I know there are plans to replace `<noscript>` solution with some 'null component'. Are there plans for 'null component' that can mount its children?

**Comment by patrick-mcdougle** [comment]
Kinda new to react, but can you do this by using `React.Children.only`?

```
render() {
  return React.Children.only(this.props.children);
}
```

**Comment by qiaoyan** [comment]
测试测试

**Comment by qiaoyan** [comment]
测试测试

**Comment by gaearon** [comment]
In React 16 you can both return `null` and arrays so there's no need for extra DOM nodes.
