### ISSUE TITLE
Bug: The high CPU in the React GPU rendering process causes the page to freeze。

### ISSUE THREAD

**Issue by enjoy-wind** [facebook/react#21911]
React version: 15.3

## Steps To Reproduce

CONIF: CPU：2G  Browser: Chrome/91.0.4472.164.  System: Windows NT 10.0.17763 GPU: 2G VENDOR= 0x1414, DEVICE=0x008c, LUID={0,16455}   

Link to code example:

## The current behavior
Current : Browser full screen and 15+form object ,, the page will freeze.（About 10s to delay）
Other:Not full screen or open the console, the page will not freeze.

## The expected behavior
No delay

**Comment by bvaughn** [comment]
Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
