### ISSUE TITLE
Discussion: break up `import()` that are NOT doing ES import work ?

### ISSUE THREAD

**Issue by n0ruSh** [facebook/react#21910]
# Background information

I have been developing a [fimga](https://www.figma.com/) plugin and recently get an exact error as described in https://github.com/figma/plugin-typings/issues/36. The root cause is that the [Secure ECMAScript (SES)](https://github.com/endojs/endo/tree/master/packages/ses) in figma tries to block any instances of the `dynamic import expression` in the code being evaluated. However, The SES shim doesn't use a full parser, so they can't tell precisely when the evaluated code contains a real import, but they do employ a regular expression to spot anything that might be a real import expression. The regular expression used is [`new RegExp('(^|[^.])\\bimport(\\s*(?:\\(|/[/*]))', 'g')`](https://github.com/endojs/endo/blob/master/packages/ses/src/transforms.js#L105), which matches the string `import()` in [Reactlazy.js](https://github.com/facebook/react/blob/HEAD/packages/react/src/ReactLazy.js#L91). Therefore, it's identified as a `dynamic import expression`, resulting in a false positive.

The discussion I would like to bring up is: whether the [`import()`](https://github.com/facebook/react/blob/HEAD/packages/react/src/ReactLazy.js#L91) should be be broken up, as what has been done in [`React.lazy.js`](https://github.com/facebook/react/blob/HEAD/packages/react/src/ReactLazy.js#L94)? Though `import()` doesn't look like a valid Javascript import statement, it does lead to some confusion for some platforms (E.g. figma) which don't have a strict validation. And it seems there is no harm if the [`import()`](https://github.com/facebook/react/blob/HEAD/packages/react/src/ReactLazy.js#L91) is also broken up?

**Comment by jacty** [comment]
`import()` is a ES6 feature has been widely supported. https://caniuse.com/?search=import()
And React.lazy() uses it to support Suspense Component, which is a core part of React Concurrent. If you don't use Suspense, I guess, the block of it won't give rise to any issue in your case.

**Comment by bvaughn** [comment]
I _think_ the request here is to break the _string_ "import()" up to avoid a false positive in the external code:
https://github.com/facebook/react/blob/9b76d2d7b3a86ffde945f88b758a0537aeca027a/packages/react/src/ReactLazy.js#L90-L93

e.g.
```js
'lazy: Expected the result of a dynamic imp' + 'ort() call. ' + 
```

I'm not sure what others will think of this request (to modify React source b'c of the way an external project _happens to work_) but we can leave the request open for folks to comment.

**Comment by n0ruSh** [comment]
> I'm not sure what others will think of this request (to modify React source b'c of the way an external project happens to work)

Yep, I'm not sure either whether this should be done in React so I raised it as a discussion. Also I saw React seems to have done some similar work before.

https://github.com/facebook/react/blob/9b76d2d7b3a86ffde945f88b758a0537aeca027a/packages/react/src/ReactLazy.js#L93-L95

> One thing you might do, @n0ruSh, to increase the visibility for this would be to just open a PR that makes the change you're requesting.

Sure. [PR](https://github.com/facebook/react/pull/21918) here :-)

**Comment by gaearon** [comment]
Closed by https://github.com/facebook/react/pull/21918.
