### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by kkanekii** [facebook/react#21921]
Does The React Website have a nice and clean Dark Mode?
if so please make it more clearer where it is

incase it does not have dark mode, Please Make it a Feature, which would attract people to the website

**Comment by bvaughn** [comment]
The documentation and source for [reactjs.org](https://reactjs.org/) are in a different GitHub repository.

Please open a new issue in that repository:
[https://github.com/reactjs/reactjs.org](https://github.com/reactjs/reactjs.org/issues/new) 

Sorry for the inconvenience! 🙂

**Comment by kkanekii** [comment]
ohh im so sorry i wasnt sure, thank you!

**Comment by bvaughn** [comment]
No problem!
