### ISSUE TITLE
Bug: Lazy only attempts to retrieve module on first mount

### ISSUE THREAD

**Issue by andyrichardson** [facebook/react#21932]
Currently when lazy retrieval of a module fails during the initial mount, this failed state persists for the lifetime of the lazy component (despite new instantiation).

```tsx
// If fails on first mount, will forever fail
const Component = lazy(() => import('./Component'));

const App = () => {
  // ...
  {someCondition && <Component />}
  // ...
}
```

Consider the following user experience:
 - user loads webpage
 - network connection goes offline
 - user loads lazy route
 - lazy module retrieval fails
 - network connection goes online
 - user navigates away from lazy element (unmount)
 - user navigates back to lazy element (mount)

Expected result:
 - Lazy module retrieval is (once again) attempted and user is able to see mounted component
 
Actual result:
 - Lazy module retrieval is skipped due to failure on prior element mount - user is forced to refresh to continue using site despite now being able to retrieve module

React version: 17.0.2

## Steps To Reproduce

1. Load webpage
2. Click toggle button to mount lazy component
3. Click toggle button to unmount lazy component
4. Click toggle button to mount lazy component 

Link to code example: https://codesandbox.io/s/snowy-voice-xsnne?file=/src/App.js

## The current behavior
On second mount, module retrieval is attempted again

## The expected behavior
On second mount, failed state from previous component instantiation is used

## Additional info

Naive attempt at addressing this - #21924

**Comment by gaearon** [comment]
When you say "fail", what do you mean? Does the Promise get rejected, or not? If the Promise gets rejected, I'd expect the closest error boundary to get triggered (instead of nothing happening forever). If the Promise doesn't get rejected, that seems to be the root of the problem to be fixed (on the bundler level or elsewhere). What am I missing?

**Comment by andyrichardson** [comment]
> When you say "fail", what do you mean? Does the Promise get rejected, or not? If the Promise gets rejected, I'd expect the closest error boundary to get triggered (instead of nothing happening forever). If the Promise doesn't get rejected, that seems to be the root of the problem to be fixed (on the bundler level or elsewhere). What am I missing?

Thanks for looking into this :+1: The example repo should answer this question.

The issue isn't about whether a promise is rejected or not. It's that the argument passed to `lazy` is called only once - regardless of how many mounts/remounts of the lazy component take place.

In a sense, the error response is "cached" rather than the lazy retrieval function being re-evaluated.
