### ISSUE TITLE
Bug: Can't render ReactElement in <select> <option>

### ISSUE THREAD

**Issue by pythonmaxi** [facebook/react#21959]
I am trying to make my own Locale system in React, locales will be used as `<LocaleComponent l={localeKey} />`.
The problem is that the current locale is set through a `context` named `LocaleContext`, since I can't use that context in each of my components, I created the `<LocaleComponent />` component.
This system works perfectly but I found out that you can't render `<LocaleComponent />` inside the `<option>` tag.
 I have an ugly unrelevant workaround for this specific case, but I still find it weird that you cant render string components inside the `<option>` tag.

React version: 17.0.2

## Steps To Reproduce

1. Create a component that returns a string.
2. Use that component inside an `<option>` tag (without forgetting the `<select>`).

[CodeSanbox](https://codesandbox.io/s/nervous-wescoff-pzluw?file=/src/App.js)

## The current behavior
The `<option>` will render as `[object Object]`.

## The expected behavior
The `<option>` should render as `Foo`.

**Comment by aplaskota** [comment]
@pythonmaxi I think the quick solution might be to just return `<option>` tag inside component instead of string
`
function TestComponent() {
  return <option>FooBar</option>;
}
`

**Comment by ShahirZain** [comment]
you can do this @pythonmaxi 
![image](https://user-images.githubusercontent.com/30791669/126974727-083cabe5-3006-4d29-b26c-dd6e322b6874.png)

**Comment by gaearon** [comment]
This is fixed in 18 Alpha but there are no plans to backport to 17. Sorry for the trouble! For now you’ll have to work around it.

**Comment by pythonmaxi** [comment]
OK, thanks for the help and info.
