### ISSUE TITLE
React 18: Display release date before relase commit in alpha releases

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#21962]
Using `alpha` as an example the version is generated as `18.0.0-alpha-$COMMIT_SHA-$RELEASE_DATE` (https://github.com/eps1lon/react/blob/355591add41c0f6dad738fdb1b6603e0786b7b4e/scripts/release/utils.js#L78-L80). 

Could we display the `$RELASE_DATE` before the `$COMMIT_SHA` so that sorting the versions like SemVer would (every part separated by a dash is sorted alphanumerically) is useful (sorting commits alphanumerically isn't that useful)? For example, codesandbox offers a dropdown to select the version with the entries sorted. Selecting the most recent version isn't trivial with the current format while using the npm dist tag isn't viable for scenarios where we want to create reproductions.

**Comment by bvaughn** [comment]
I think a goal of this format was for people _not_ to try using ^ for any meaningful purpose wrt version ranges (so the non-linear "sort" was a benefit).

> For example, codesandbox offers a dropdown to select the version with the entries sorted. Selecting the most recent version isn't trivial with the current format while using the npm dist tag isn't viable for scenarios where we want to create reproductions.

This is a solid point, although shouldn't it just be possible to specify the "alpha" tag and let NPM figure out which is the latest during install?

**Comment by eps1lon** [comment]
> I think a goal of this format was for people not to try using ^ for any meaningful purpose wrt version ranges (so the non-linear "sort" was a benefit).

Yeah, makes sense. Though I do find the reasons more compelling for the `0.0.0` release lines not the ones where we already settled on the major number e.g. `^17.0.0-alpha` or `^18.0.0-alpha`.


> This is a solid point, although shouldn't it just be possible to specify the "alpha" tag and let NPM figure out which is the latest during install?

This works if you really want to use the latest. But for repros you do want to use an exact version. codesandbox is probably in a better situation to auto-select the exact version when opening the dropdown  while a package is installed by dist-tag. Will see how they respond.

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/codesandbox/codesandbox-client/issues/5993
