### ISSUE TITLE
Bug: createPortal anywhere in the tree makes native events be ran too late

### ISSUE THREAD

**Issue by kosciolek** [facebook/react#21989]
## Summary
Native events added via `useEffect` are called too late (and with improper (new) state, rather than the state during listener attachment) if there's a `ReactDOM.createPortal` anywhere in the tree. First the effect is re-run and a new listener is attached, and only then the native event is called.

React version:
17.0.2

Link to code example:

[CodeSandbox](https://codesandbox.io/s/late-star-1izm6)

## Reproduction 

* Anywhere in the tree is a `createPortal`. It can even be `createPortal(null, document.body)`
* Somewhere, there is a component with `useState`.
* It renders a div. The div has an `onClick` handler passed.
* On top of that, `useEffect` is used to attach a `click` event to `window`
* Both event handlers (both the native event attached to window, and the React event passed to `div`) use `setState`.

## The current behavior

* The React handler is called. It calls setState
* The component rerenders with the new state, and its effects are re-run.
* Since the effect is re-run, a new native listener is attached (which is bound to the new state)
* Only then, the new listener (with the NEW state) is called.

## The expected behavior

* The React handler is called. It calls setState
* The component might rerender or not (doesn't matter)
* The native handler is called with the old state.

In other words
```
const [popupOpen, setPopupOpen] = useState(false);
useEffect(() => {
   // close popup if clicked anywhere on the screen, some code ignored for brevity 
  const listener = () => {
    console.log('NATIVE', popupOpen);
    if (popupOpen) setPopupOpen(false);
  };
  window.addEventListener("click", listener);
  return () => window.removeEventListener("click", listener);
}, [popupOpen]);

return (
  <>
    <div
      onClick={() => {
        console.log('REACT', popupOpen); // REACT HANDLER STATE
        if (!popupOpen) setPopupOpen(true);
      }}
    >
      Open popup
    </div>
    {ReactDOM.createPortal(null, document.body)}
  </>
);
```

Logs

![image](https://user-images.githubusercontent.com/45483493/127549843-763c1ee1-4976-4d7b-855e-91b16b8c4e3e.png)

But without `createPortal`, the following is logged:

![image](https://user-images.githubusercontent.com/45483493/127550018-901aee68-c9d9-4c66-9897-9466789256ce.png)

**Comment by kosciolek** [comment]
Turns out, a portal is not needed.

Adding this to the described component causes the same bug (?)
```
const [state, setState] = useState<HTMLDivElement | null>(null);
(...)
<div ref={(ref) => setState(ref)}></div>
```

**Comment by kosciolek** [comment]
However, changing it to `<div ref={setState} > </div>` makes it run just fine, with both the React handler and the native handler showing the same values.

Complete component code:
```tsx
function App() {
  const [popupOpen, setPopupOpen] = useState(false);
  useEffect(() => {
    console.log('binding', popupOpen);
    const listener = () => {
      console.log("NATIVE", popupOpen);
      if (popupOpen) setPopupOpen(false);
    };
    window.addEventListener("click", listener);
    return () => window.removeEventListener("click", listener);
  }, [popupOpen]);

  const [state, setState] = useState<HTMLDivElement | null>(null);

  return (
    <>
      <div
        onClick={() => {
          console.log("REACT", popupOpen); // REACT HANDLER STATE
          if (!popupOpen) setPopupOpen(true);
        }}
      >
        Open popup
      </div>
      <div ref={setState}></div>
    </>
  );
}
```

**Comment by eps1lon** [comment]
Thanks for the report.

Could you check if this is similar to https://github.com/facebook/react/issues/20074?

**Comment by kosciolek** [comment]
Yes, it's the same. If portal is rendered, first the event is re-attached, and only then fired.
![image](https://user-images.githubusercontent.com/45483493/127623115-7f5dae4e-28f1-48e3-b8f6-716c7df50bf6.png)

Though, as above, it's not exclusive to portals. I'd wager anything that triggers another render pass will do that.

First, native events, unless captured, are fired after React's events. Second, native event listeners (as far as my understanding goes) seem to be simply stored in an array. When the event is fired, the browser iterates over that array and fires them one by one. Therefore, an early handler can remove a handler that's after it, and attach a new one. The new one will be fired as well (for the same event), since the browser is just doing a dumb iteration over the array - nothing says we can't modify the array under its feet.

Let's look at this, a less convoluted example:

```tsx
function App() {
  const [popupOpen, setPopupOpen] = useState(false);

  console.log('RENDER PHASE');

  useEffect(() => {
    console.log("EFFECT (EVENT ATTACHMENT)", popupOpen);
    const listener = () => {
      console.log("NATIVE HANDLER", popupOpen);
    };
    window.addEventListener("click", listener);
    return () => {
      console.log("EFFECT CLEANUP", popupOpen);
      window.removeEventListener("click", listener);
    };
  }, [popupOpen]);

  const [state, setState] = useState<HTMLDivElement | null>(null);

  return (
    <>
      <div
        onClick={() => {
          console.log("REACT HANDLER", popupOpen);
          setPopupOpen((prev) => !prev);
        }}
      >
        Open popup
      </div>
    </>
  );
}
```
![image](https://user-images.githubusercontent.com/45483493/127626182-331a2b41-3274-4dc5-8029-b65d80b264a9.png)

This is fine. React fired, rerender (no effects fired), native fired, effects fired.

Now, let us add EITHER
1. a portal after the div `{createPortal(null, document.body)}`
2. A div with a setState for its ref
```tsx
const [state, setState] = useState<HTMLDivElement | null>(null);
//code
<div ref={(ref) => setState(ref)} />
```
It's important that it's `ref={(ref) => setState(ref)}` and not `ref={setState}`.

Code: 

```tsx
function App() {
  const [popupOpen, setPopupOpen] = useState(false);

  console.log('RENDER PHASE');

  useEffect(() => {
    console.log("EFFECT (EVENT ATTACHMENT)", popupOpen);
    const listener = () => {
      console.log("NATIVE HANDLER", popupOpen);
    };
    window.addEventListener("click", listener);
    return () => {
      console.log("EFFECT CLEANUP", popupOpen);
      window.removeEventListener("click", listener);
    };
  }, [popupOpen]);

  const [state, setState] = useState<HTMLDivElement | null>(null);

  return (
    <>
      <div
        onClick={() => {
          console.log("REACT HANDLER", popupOpen);
          setPopupOpen((prev) => !prev);
        }}
      >
        Open popup
      </div>
      
      {/* Either is enough */}
      <div ref={(ref) => setState(ref)}/>
      {createPortal(null, document.body)}
    </>
  );
}
```

In this case, this is what happens:
![image](https://user-images.githubusercontent.com/45483493/127626137-da11ba8f-b92f-4df8-8594-46fac7e8551d.png)

* The React handler is fired.
* Rerender
* **Effects are fired!** Since the dependency (`popupOpen`) is different, the clean up is run - old listener, with old state, is removed, a new listener, with new state, is added - **The array that holds events is modified mid-flight**
* The browser keeps iterating over the array... finally, at the end of the array, it encounters our new native handler. It fires it.

And here we are.

**Comment by eps1lon** [comment]
> Yes, it's the same. 

Closing then as per https://github.com/facebook/react/issues/20074#issuecomment-811296789
