### ISSUE TITLE
[DevTools Bug]: Component tree size too small, components can't be selected

### ISSUE THREAD

**Issue by subnomo** [facebook/react#21986]
### Website or app

https://reactjs.org/

### Repro steps

1. Visit reactjs.org
2. Open devtools
3. Open "Components" tab

At first the component tree won't appear. Once I'm at the "Components" tab, I then have to also refresh the page to make the tree render. And when it does render, it still doesn't work properly.

As a note, this issue started happening after I had to forcibly restart my computer. Since then I have tried reinstalling the extension, restarting Chrome, restarting my pc, all of which haven't worked. I'd like to avoid reinstalling Chrome completely but that's the only thing I haven't yet tried. Using Windows 10, btw.

Here is what the broken component tree looks like. It's very narrow and the components cannot be selected:
![tree](https://user-images.githubusercontent.com/1390653/127435008-51ccf804-45ef-4732-bbca-f07814b28c07.png)

### How often does this bug happen?

Every time

**Comment by gabriel-peracio** [comment]
Same here:
![image](https://user-images.githubusercontent.com/8999086/127560358-bc4f0599-9045-4ef7-915f-248767934a13.png)

The Profiler tab seems unaffected

Workarounds that don't help:
- Reloading the page
- Docking the devtools on the side/bottom
- Undocking the devtools (a.k.a. open in a window)
- Resizing the window
- Fiddling with the `Expand component tree by default` setting
- Resizing the right pane of the component tab

**Comment by gabriel-peracio** [comment]
Looks like a CSS issue:

https://user-images.githubusercontent.com/8999086/127561843-30f36425-d689-440f-8fda-92bad98188b1.mp4

The nodes in the tree remain **unselectable with the mouse** even after my "workaround", though.

They are selectable, however, if you:
- use the keyboard
- navigate using the "rendered by" box on the right pane (called `Owners` internally)
- use the search bar
- use the element picker

**Comment by kkragoth** [comment]
Doesn't seem to occur on mac os for me on extension:
Version
4.14.0 (7/16/2021)

<img width="1674" alt="Screenshot 2021-07-30 at 00 05 56" src="https://user-images.githubusercontent.com/6214896/127572071-5d4048bb-d8ba-431c-abfd-381a77d2d498.png">

**Comment by dmitry-turing** [comment]
reproduces for me on:

MacOS X 10.14
Chrome Version 92.0.4515.107 (Official Build) (x86_64) (latest)
DevTools 4.14.0 (7/16/2021)

**Comment by gabriel-peracio** [comment]
Mine is:

Windows 10 21H1 (OS Build 19043.1110)
Chrome Version 92.0.4515.107 (Official Build) (64-bit)
 DevTools version 4.14.0-d0ec283819
 
 If any developer is unable to reproduce, let me know and I can get you whatever you need (a snapshot of the dom, the css ruleset, a memory dump, etc)

**Comment by samuelcolburn** [comment]
reproduces for me on:

Windows 10 Pro (10.0.19043 Build 19043)
Edge Version 92.0.902.62 (Official Build) (64-bit) (latest)
DevTools 4.14.0 (7/16/2021)

**Comment by KasiMaru** [comment]
I also have this problem:

MacOS 11.4
Chrome version: Version 92.0.4515.131 (Official Build) (x86_64)
DevTools version: 4.14.0 (7/16/2021)

Sometimes component tree doesn't show at all, have to reload a page. Even after reloading tree is too narrow and clicks are not coming through. 

Tried every sane approach to fix (reinstall, reload etc) — nothing helps.

**Comment by Borvik** [comment]
Occurs for me as well:

Ubuntu 20.04.2 LTS
Chrome: 92.0.4515.107
DevTools: 4.14.0

While Chrome is affected for me - FireFox continues to work.

**Comment by jstejada** [comment]
Another report in https://github.com/facebook/react/issues/22065

**Comment by bvaughn** [comment]
I suspect the bug may be caused by this component (which we use in DevTools to auto-expand the Components tree to fill the width and height of the viewport):
https://github.com/bvaughn/react-virtualized-auto-sizer

**Comment by mbonaci** [comment]
Me too.
OSX `10.15.7`
Chrome `92.0.4515.131` (the latest)
ReactDevTools: `4.14.0`

Interestingly, the issue **is not present** in `Chromium: 91.0.4472.114` (Brave ¨1.26.67¨).

**Comment by bvaughn** [comment]
Tanks @mbonaci.

As another data point:

OS X 11.4 (20F71)
Chrome 92.0.4515.131
DevTools (built from HEAD of `main`)

I've never seen this personally.

Maybe others can share their configurations and we can spot a pattern.

**Comment by gabriel-peracio** [comment]
@ bvaughn
> I've never seen this personally.

So you can't reproduce?

> Maybe others can share their configurations and we can spot a pattern.

What would be helpful for you to track this down?

**Comment by simplecommerce** [comment]
I have the same issues and also using chrome with latest version `92.0.4515.131` and dev tools version `4.14.0` on windows 10.
Weird thing, is my co-worker with the same versions, it works fine on his end on the same app/site.
So no idea what is causing it to not work on my computer.

**Comment by bvaughn** [comment]
@simplecommerce Could be helpful if you and your coworker could try to further narrow down what the difference is between the two of your setups.

**Comment by issacgerges** [comment]
I have a suspicion at whats going on here. I know react-virtualized shims `ResizeObserver` using scroll event handlers, when it does this, it schedules a `requestAnimationFrame` to be notified after the layout updates. In this case, if I debug this script, I can see that scheduling any raf in `main.html` of the devtool will never fire. I suspect a finch trial is being used by the Chromium team to attempt to throttle rAFs in hidden `iframe`s. This experiment looks the most suspicious, these will show as "Default" for everyone unfortunately.

![image](https://user-images.githubusercontent.com/44379112/129085659-ef0ba177-8a0d-4655-81a3-af9bf445a55b.png)

**Comment by gabriel-peracio** [comment]
@issacgerges Awesome work, this pretty much confirms it.

Changing that flag from `Default` to `Disabled` solves the issue on my end. Changing it to `Enabled` brings the issue back

**Comment by simplecommerce** [comment]
Couldn't find the throttle setting mentioned by @issacgerges and where to change it.
But I uninstalled chrome completely and reinstalled it (fresh copy, wiping out all settings) and it fixed it for me.

**Comment by issacgerges** [comment]
Could be worth opening a Chormium ticket, but from similar experience this is likely intentional/by design. Maybe they could exclude devtools here? It might be painful to fix in the short term, so maybe it's best to create a branch off of `react-virtualized-auto-sizer` thats used for the plugin that removes the raf from the scheduler array https://github.com/bvaughn/react-virtualized-auto-sizer/blob/25ccd4f399abfd2997346a733cce31d177196092/src/vendor/detectElementResize.js#L29-L31

**Comment by bvaughn** [comment]
Fantastic find, @issacgerges!

Seems like `react-virtualized-auto-sizer` could detect this case (no rAF firing by a certain time) and maybe fallback to using a timer or other debounce technique.

**Comment by bvaughn** [comment]
> Seems like `react-virtualized-auto-sizer` could detect this case (no rAF firing by a certain time) and maybe fallback to using a timer or other debounce technique.

If anyone would be interested in making (and testing) this change, I'll be happy to review and release an update to the package and DevTools. I'm a little swamped at the moment but I'll try to get to it eventually.

**Comment by issacgerges** [comment]
I saw you just picked this up @bvaughn, if you have issues in development have seen Chromium make timers minute aligned when doing background throttling. If that's the case I know setImmediate polyfills have a trick with self-post messaging that could be used.

**Comment by bvaughn** [comment]
Thanks for the pointer, @issacgerges. Happen to have a code pointer?

**Comment by issacgerges** [comment]
Sure! Here's the `setImmediate` strategy I was thinking of
https://github.com/YuzuJS/setImmediate/blob/f1ccbfdf09cb93aadf77c4aa749ea554503b9234/setImmediate.js#L99-L122

and here is a reference to the timer alignment I've seen mentioned (not 100% sure it will apply here)
https://www.chromestatus.com/feature/4718288976216064

**Comment by bvaughn** [comment]
Super helpful. Thanks!

**Comment by bvaughn** [comment]
I'm overlooking some important detail here.

Enabling/disabling the "_Throttle non-visible cross-origin iframes_" flag does indeed trigger/fix the bug, but even when this is disabled– animation frames still get called based on my testing, unlike what @issacgerges reported above:
> In this case, if I debug this script, I can see that scheduling any raf in `main.html` of the devtool will never fire. 

(So my idea to detect this case and fallback to a timeout doesn't work.)

That being said, just replacing `requestAnimationFrame` with `setTimeout` (and not trying to detect support) fixes the broken behavior.

**Comment by issacgerges** [comment]
@bvaughn ah interesting. Just to validate are you registering those `requestAnimationFrame` callbacks from the context of `main.html` or `panel.html`. I believe they will only fail to fire from `main.html` (which is the hidden iframe)

**Comment by bvaughn** [comment]
@issacgerges I added logging to the feature detection code I wrote (which runs in the same context as the `detectElementResize` script).

**Comment by bvaughn** [comment]
Fixed it by adding a fallback timeout when rAF is used ☹️ Doesn't feel great but...

https://github.com/bvaughn/react-virtualized-auto-sizer/pull/39

**Comment by bvaughn** [comment]
Thanks a ton for the info @issacgerges and @gabriel-peracio

**Comment by bvaughn** [comment]
This fix has landed. We'll probably release it next week because we're also waiting on another bugfix to unblock the Firefox release.

**Comment by bvaughn** [comment]
Related CR bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1241986
