### ISSUE TITLE
Bug: onclick will not work when i import bundle.js twice

### ISSUE THREAD

**Issue by sspku-yqLiu** [facebook/react#21980]
Hi, I just had an interesting situation. I wrote the index.html like this.

``` html 

<body>
    <div id="react-container"></div>
    <script src="./bundle.js"></script> 
</body>

```

However, I forget I have used html-webpack-plugin to import bundle.js too. As a result, I import bundle.js twice.

During this time, I find all Javascript doesnt work. For example, if the button should log something, it doesnt.

the bundle.js is the output of webpack, so it contains react.js and react-dom

I just really want to know why this happen. Can you help me find out why?

React version: ^17.0.2

## Steps To Reproduce

Here is an example: 

https://github.com/sspku-yqLiu/demoForBundleTwice

**Comment by sspku-yqLiu** [comment]
here is a demo for this:
![demo](https://user-images.githubusercontent.com/56879942/127428961-22e76eb6-d5d8-44d5-9ca4-873cb5cc167a.gif)

**Comment by andriusf** [comment]
Encountered the same issue today with React 17.0.2. I was also using Webpack but forgot to remove the JS bundle file from index.html while debugging.

With the bundle duplication present, events such as onClick, onBlur weren't working. As soon as I removed the bundle script tag from index.html (effectively removing JS bundle duplication) all the event handlers started to work again.

Not sure if this can be labelled a React bug, but it may be worth documenting it in case more developers run into the same issue.
