### ISSUE TITLE
Bug: Error: Cannot find module 'node-releases/data/processed/envs.json'

### ISSUE THREAD

**Issue by zorox-1** [facebook/react#21988]
Upon running `npx create-react-app my-app`, i get the following error:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node-releases/data/processed/envs.json'
```
any idea? 
npm version: 7.20.2
node: v14.17.3

**Comment by bvaughn** [comment]
This is the React repo. It sounds like you're reporting an issue with create-react-app. Please report it in the create-react-app repository:
https://github.com/facebook/create-react-app/issues/

That repo is maintained by a different team of people.

Also, please search to see if the issue has already been opened before posting a new one.
