### ISSUE TITLE
Bug: onMouseEnter behavior when mouse does not enter via boundary is inconsistent between browsers

### ISSUE THREAD

**Issue by saperdadsk** [facebook/react#21991]
React version: 17.0.2

## Steps To Reproduce

1. Create two components Foo and Bar inside a parent Component, where Foo is positioned such that it covers Bar.
2. Add a onMouseEnter event handler to Bar
3. Add a click handler to Foo that will cause Foo to be removed when clicked
4. Click Foo
5. Mouse is now hovering over Bar

Link to code example: 

https://codesandbox.io/s/tender-sun-i1ccy?file=/public/index.html

## The current behavior
In Chrome:
The onMouseEnter event handler on Bar is not fired when Foo is removed.
In Firefox:
The onMouseEnter event handler on Bar is fired when Foo is removed.

## The expected behavior
onMouseEnter is fired on Bar is fired when Foo is removed. This is the behavior in both chrome and firefox when plain html and js are used:

Spec for MouseEvent seems vague about this issue:
 - https://w3c.github.io/uievents/#event-type-mouseenter
 
> A user agent MUST dispatch this event when a pointing device is moved onto the boundaries of an element or one of its descendent elements. A user agent MUST also dispatch this event when the element or one of its descendants moves to be underneath the primary pointing device.

I saw https://github.com/facebook/react/issues/2621, though it isn't quite the same issue.
Also saw the stack-overflow issue https://stackoverflow.com/q/55836826, which reported this behavior

Chrome version: Version 92.0.4515.107 (Official Build) (x86_64)
Firefox version: 90.0.2 (64-bit)
OS: MacOs 11.2.3 (20D91)

**Comment by Thummer** [comment]
I had the same problem recently with react@17.0.2, I tried it using react@18.2.0, it seems like this issue has been fixed.

**Comment by Elmaranin** [comment]
Even plain behavior doesn't work on Safari without mouseMove event
