### ISSUE TITLE
Here's a step-by-step instruction for how to work around it while the fix is pending review:

### ISSUE THREAD

**Issue by Krishnag09** [facebook/react#21994]
This only works for one time at one page, but fails if one has to pause and restart the inspector while navigating to different pages. 

Here's a step-by-step instruction for how to work around it while the fix is pending review:

1. Press the Settings gear icon in the upper right corner

<img width="1161" alt="Screenshot 2020-07-10 at 14 39 06" src="https://user-images.githubusercontent.com/810438/87160653-37db1900-c2bb-11ea-9806-07cea49660ed.png">

2. Open the Debugging tab

<img width="1275" alt="Screenshot 2020-07-10 at 14 39 13" src="https://user-images.githubusercontent.com/810438/87160687-432e4480-c2bb-11ea-8b06-2444ade200e8.png">

3. Put the checkmark next to **Break on Warnings**
<img width="1273" alt="Screenshot 2020-07-10 at 14 39 20" src="https://user-images.githubusercontent.com/810438/87160706-4a555280-c2bb-11ea-91ab-8dd887a67150.png">

4. Remove the checkmark next to **Break on Warnings**

<img width="1286" alt="Screenshot 2020-07-10 at 14 39 25" src="https://user-images.githubusercontent.com/810438/87160738-57724180-c2bb-11ea-9bac-d181daf6ab8b.png">

Now reload the page and you shouldn't be bothered by it.

_Originally posted by @gaearon in https://github.com/facebook/react/issues/19308#issuecomment-656682924_

**Comment by bvaughn** [comment]
Sorry. I'm not really sure why one of Dan's comments has been re-posted as an issue so I'm going to close it. If there's some problem, let me know.
