### ISSUE TITLE
React 18: useEffect calling twice inside a custom hook

### ISSUE THREAD

**Issue by hieuhani** [facebook/react#21997]
I'm testing React 18.0.0-alpha-dbe3363cc and get this issue, useEffect callback got to be called twice when passing an empty array ([]) to expect to run an effect and clean it up only once.

Check out this code: https://codesandbox.io/s/friendly-firefly-h5noz?file=/src/App.js

**Comment by Idan-Garay** [comment]
Try removing the strict mode tag in index.js.  

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions

source: https://reactjs.org/docs/strict-mode.html

**Comment by vkurchatkin** [comment]
This specifically is described here https://github.com/reactwg/react-18/discussions/19
