### ISSUE TITLE
[Question] useRef usage with concurrent mode

### ISSUE THREAD

**Issue by Attrash-Islam** [facebook/react#22002]
Hi,
I noticed some weird behavior and just want to verify it.

When I wrap my application with `<StrictMode/>` I've some issues were using `useRef` is buggy in one of my hooks (I'm using them only for caching and previous values checks, and there's a state update inside that hook).

Once I replace the `useRef` with `useState` with same logic/purpose it works! (With zero additional changes) - It seems like useState can handle multiple render calls and useRef is **really** a mutable that don't care for such a cases.

I'm aware that this adds some render when updating the state but seems like very stable compared with refs.

The questions are:

1- Is it recommended to `useState` always and to refrain from using `useRef` for future compatibility when state updating is involved?

2- If not, Does the react team intend on syncing `useRef` to handle such a cases?

Thanks

**Comment by gaearon** [comment]
Can you post a complete example?

**Comment by debel27** [comment]
I think I can provide an example, though it is not really about state updates. Consider the following hook

```jsx
// @flow
import * as React from 'react';
import { isEqual as lodashIsEqual } from 'lodash';

export function useStableValue<V>(val: V, isEqual?: (V, V) => boolean): V {
  const valRef = React.useRef(val);
  const isEqualFn = isEqual || lodashIsEqual;

  if (!isEqualFn(valRef.current, val)) {
    /* I expect it to be OK to mutate valRef inside render. Idempotence is more important than purity.
     * cfr https://overreacted.io/react-as-a-ui-runtime/#purity */
    valRef.current = val;
  }

  return valRef.current;
}
```

The motivation for this hook is to use its return value in a useEffect, so it wouldn't be triggered by irrelevant changes in complex objects/arrays. It is not expected to be used often (you can for instance destructure an object to get only the properties that are relevant to your hook).

Is this code safe in concurrent mode ?

**Comment by Attrash-Islam** [comment]
Not sure I get your example @debel27 but it's not my case for sure.

Thanks for your reply @gaearon ! Will supply an example soon

**Comment by Attrash-Islam** [comment]
Here it is -> https://codesandbox.io/s/useref-with-strictmode-jif1j?file=/src/App.js

**Comment by Shrugsy** [comment]
> Here it is @gaearon -> https://codesandbox.io/s/useref-with-strictmode-jif1j?file=/src/App.js

Do you have a more complete example? `prevCount` isn't used in your example besides being logged, and `color` could be a derived value instead of state, so I can't see a justification for setting state in the render body.

```js
const color = count % 2 === 0 ? "blue" : "red";
```

**Comment by Attrash-Islam** [comment]
> > Here it is @gaearon -> https://codesandbox.io/s/useref-with-strictmode-jif1j?file=/src/App.js
> 
> @Attrash-Islam Do you have a more complete example? `prevCount` isn't used in your example besides being logged, and `color` could be a derived value instead of state, so I can't see a justification for setting state in the render body.
> 
> ```js
> const color = count % 2 === 0 ? "blue" : "red";
> ```

The way you're suggesting is legit for this simple example but it's irrelevant for bigger state management solutions.

See `react-wisteria` - A state Management I built on this abstraction where you can connect to this derived state so you need it as a part of the state.

**Comment by Shrugsy** [comment]
> The way you're suggesting is legit for this simple example but it's irrelevant for bigger state management solutions.
> 
> See `react-wisteria` - A state Management I built on this abstraction where you can connect to this derived state so you need it as a part of the state and not only in the render closure so deeper nested components can `connect()` to it.

I'm not seeing the need for it to be 'derived state' as opposed to a 'derived value' still. You can still derive the value from your state high up, then provide it via your context provider value. That allows deeper components to access it via the context.

**Comment by Attrash-Islam** [comment]
> > The way you're suggesting is legit for this simple example but it's irrelevant for bigger state management solutions.
> > See `react-wisteria` - A state Management I built on this abstraction where you can connect to this derived state so you need it as a part of the state and not only in the render closure so deeper nested components can `connect()` to it.
> 
> I'm not seeing the need for it to be 'derived state' as opposed to a 'derived value' still. You can still derive the value from your state high up, then provide it via your context provider value. That allows deeper components to access it via the context.

Yes, but you don't want to calculate it in each render because of that I'm using the prevValue as in the example link above. Also, prevCount is not used only for logging

**Comment by Shrugsy** [comment]
> Yes, but you don't want to calculate it in each render because of that I'm using the prevValue as in the example link above. Also, prevCount is not used only for logging

I would use `useMemo` in that case. I'll leave it for others to discuss further
