### ISSUE TITLE
Tutorial does not work on Chrome

### ISSUE THREAD

**Issue by bev-a-tron** [facebook/react#22009]
Chrome made an update that prevents Alert pop-up boxes from cross origin iframes. This includes the Alerts that are in the Tic Tac Toe tutorial for React. I didn't know how to update the Tutorial; it's on reactjs.org: https://reactjs.org/tutorial/tutorial.html. So I thought I'd open this issue!

Thanks!

See Chrome update from today (August 2, 2021): https://www.chromestatus.com/feature/5148698084376576.

Does not work on Chrome:
![Screen Shot 2021-08-02 at 5 14 10 PM](https://user-images.githubusercontent.com/1618914/127930467-7201a490-65e3-4af4-9ded-967abb6a17ac.png)

Works on Safari:
![Screen Shot 2021-08-02 at 5 10 21 PM](https://user-images.githubusercontent.com/1618914/127930391-b1c7b9c6-2212-4f4b-bee1-fd31e7724002.png)

**Comment by bvaughn** [comment]
The documentation and source for [reactjs.org](https://reactjs.org/) are in a different GitHub repository.

Please open a new issue in that repository:
[https://github.com/reactjs/reactjs.org](https://github.com/reactjs/reactjs.org/issues/new) 

Sorry for the inconvenience! 🙂
