### ISSUE TITLE
Bug: React mutates dom when nothing changes because component function was generated dynamically

### ISSUE THREAD

**Issue by jwpradm** [facebook/react#22028]
Hello, I'm not sure if this is a bug or intentional behavior. In either case can you please explain the following behaviour: when we create a component function `MyComponent` dynamically for each render, the `MyComponent` component will trigger an actual dom mutation even if it returns identical jsx.

```jsx
import React from 'react';

function MyComponent() {
  return <div id="test">test</div>;
}

// Uncomment inside of this function to see
// difference in VDOM behavior
function getMeAComponent() {
  // Return same component
  // return MyComponent;

  // Return new component
  return function MyComponent() {
    return <div id="test">test</div>;
  };
}

const mutationObserver = new MutationObserver((mutations) => {
  console.debug(mutations);
});

let observingMutations = false;

export default function App() {
  const [count, setCount] = React.useState(1);

  const MyComponent = getMeAComponent();

  return (
    <div className="App">
      <div>Render count: {count}</div>

      <button onClick={() => setCount((c) => c + 1)}>Increment</button>

      <div
        ref={(elm) => {
          // Set observer only once as soon as we have a DOM element
          if (elm && !observingMutations) {
            console.info('Observing mutations...');
            mutationObserver.observe(elm, { childList: true });
            observingMutations = true;
          }
        }}
      >
        <MyComponent />
      </div>
    </div>
  );
}

```

React version: 17.0.2

## Steps To Reproduce

1. Navigate to https://codesandbox.io/s/blissful-shamir-k6gzz?file=/src/App.js
2. Click "Increment" in the "Browser" tab
3. Observe "2 mutation records in the "Console" tab
4. Uncomment line 13
2. Click "Increment" in the "Browser" tab
3. Observe no new logs in the "Console" tab

Link to code example: https://codesandbox.io/s/blissful-shamir-k6gzz?file=/src/App.js

## The current behavior
- Dynamically generated component functions trigger dom mutations even when the dom after the mutation will be identical

## The expected behavior
- Dynamically generated component functions do nit trigger dom mutations even if the dom after the mutation would be identical

**Comment by bvaughn** [comment]
We recommend that you don't define/create a component during render.

Doing this means that each time React renders the `App` component, the code above returns a _new_ `MyComponent` type. React's diffing algorithm sees this new function _as a new component_, so it unmounts the previous one (and anything beneath it) and mounts the new one. This is unnecessarily expensive _and_ it means that you might lose component state between renders.

**Comment by jwpradm** [comment]
@bvaughn thanks for the answer! On my side I just moved the component definition to module scope, and that indeed solved the problem. :slightly_smiling_face: 

I do find this behaviour pretty unintuitive. My understanding of the reconciliation algorithm was that it should never uncenecssarily mutate dom, since there might be other things outside of react that are dependent on the dom mutations.  Is there somewhere official documentation about this? Is there somewhere official documentation about this? Can I ask for the reason for this decision (to better understand how the algorithm works)? Are there other ways to mitigate this and controle dom updates? This becomes more important in certain scenarios where react is cooperating with other systems on the website as well as in situations where static definition of `MyComponent` wouldn't be possible.

**Comment by bvaughn** [comment]
> My understanding of the reconciliation algorithm was that it should never uncenecssarily mutate dom

It's less about the DOM and more about maintaining state integrity in this case. Two components can produce the same DOM but e.g. have different imperative effect code (subscriptions/event handlers) or different internal state (hooks).

When a component's _type_ changes, React unmounts the old component and mounts the new one, regardless of what kind of subtree is produced. (It would be less efficient to always do a deep comparison of the sub tree in this case anyway.)

**Comment by bvaughn** [comment]
> This becomes more important in certain scenarios where react is cooperating with other systems on the website as well as in situations where static definition of `MyComponent` wouldn't be possible. 

I don't think I understand this scenario. Inline components should never really be required, since you can parameterize a component with props. Can you provide a concrete example?

**Comment by markerikson** [comment]
@jwpradm You should probably read [the React docs page on "Reconciliation"](https://reactjs.org/docs/reconciliation.html), and the ["Component Types and Reconciliation" section in my post "A Mostly Complete Guide to React Rendering Behavior](https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#component-types-and-reconciliation).

To expand on what Brian said a bit:  when React is diffing the previous render results vs the current render results, it compares `previousElement.type === currentElement.type` at each spot in the render output.  If the `element.type` has changed by reference, React assumes you're asking it to render _something completely different_.  In that case, it unmounts that entire component and _everything_ inside of it - all components and DOM nodes - and creates all the new DOM for that section from scratch.

So, I wouldn't phrase this as "React mutating the DOM" per se. The phrase is technically correct, but what's actually happening is your code is telling React to render a different component type than last time, and React handles that the same way it would if you went from rendering `<ComponentA />` to `<ComponentB />`.

**Comment by 7kms** [comment]
There is the sourcecode  https://github.com/facebook/react/blob/v17.0.2/packages/react-reconciler/src/ReactChildFiber.old.js#L1190 .

`child.elementType === element.type ` is false , so it is faild to reconciler.  React will create a new fiber with out reuse the `oldfiber.stateNode`,  finally ,  the DOM changed.

Why the `child.elementType === element.type ` statement is false? 

Because your `<MyComponent />` is recreated every render,  the left side of the equation `child.elementType` represents a old `function MyComponent()`, otherwise the right side `element.type` is another `function MyComponent()`. So they are not equal at  all.

**Comment by jwpradm** [comment]
Ah I see. Indeed. It makes more sense now, thanks all for the explanation!

I thought that react was keeping a deep copy of the entire vdom tree, and in cases like this, it would "execute" the "new" component but would not actually mutate the dom since no dom changes aren't actually needed. But it looks like this is a concious design choice made by React in the name of performance of the diffing algorithm.

I can see on the <https://reactjs.org/docs/reconciliation.html> page the following quote, which confirms everything you guys said.

> Whenever the root elements have different types, React will tear down the old tree and build the new tree from scratch.

Somehow I thought that refers to the dom element type not to React component type. The next sentence makes it very clear.

> Going from `<a>` to `<img>`, or from `<Article>` to `<Comment>`, or from `<Button>` to `<div>` - any of those will lead to a full rebuild.

And in our case `elementType` is a reference to a function, and it is different on every render so the equality test fails and react thinks we are requesting an entirely different component.

I am closing this issue, since I think everything is clear, but please feel free to comment with additional explanations if I got something wrong in this comment. Thanks for the help!
