### ISSUE TITLE
Feature: useState performance enhance derivate using modstamp logic instead of destructuring

### ISSUE THREAD

**Issue by wesleyolis** [facebook/react#22032]
I would also like to propose that following potentially improvements for speed and simplicity now that useState is there.

I would like to propose the following variants, which introduce a modstamp and a setItem for state that contains list of items.
Instead of having to destructor arrays and objects and things to cause reference changes, which is havey,
setItem would implicit tick the mostamp for an item in an array and the modstamp if required at array container level.
There would be alot less overhead in my mind to this approach that to setItem([...this.array]), causing new references to be created in the back ground, such that there is a reference change detected, such that item re-renders.
if one wants to do a bulk update with more than a single item then setContent(this.array), which implicit, tick the mostamp.

This would simplify things, because everything is basically reduce to a primative comparison or modstamp and no doesn't need to write deep ShouldComponentUpdate comparison anymore, as been take into account by useState.

I think it is quite straint forward, obviously there would be all the logic in the background wrapping useState or using symbol and inject directly into an object. One just needs a GetContent the with out a modstamp for hitting API's.

Typically this is just a concept, the function names and useState variants don't have to follow everything word for word names and that are menings less, its basically behavior, simplification that one is looking for, weather is with effects or which every.

Typically UseState approach is much nicer, when having to setup, things, where on is linking into to nested structures of this.state, because updating them requires destructing of parent properties, such that they not lost.

**Continuous Scroll**
In addition to this one also is there required the ability to not tick the timestamp when setContent is used, because when you working with controls where the is a data provide for like FlatList or things like that, where only UI items for screens space, while all data is not converted into controls, only the section for display. Typiclaly the documentation with regards to react-native is not correctly in how to use js for continuous scroll, as par last docs I read, cause full re-renders instead appends, for data off screen. Depends on weather you have a full screen of items or less basically. Basically flatList could also detect not just reference change, but array exceeding being below the minimum number of row  Items that would cover the screen. if is an append, well change is ignored. If update, then mostamps would have change for the person.

**CRUD system of changes**
Basically you could also implement Create/Update/Delete item delta caching in the back ground for aggregation, which what I ultimate wanted to do in missive cad system, to reduce UI re-draw. I this case just before render, deltas are then merge before GetDerivedStateFromProps and render would be called. 

```.ts

const modStamp = Symbol('modstamp');

enum UseStateType {
Primative,
ArrayObject,
Object
}


// Different function names could be used as well.
useState(type: UseStateType, initialcontent: TLookUpValueType, setMethod?: (value: TLookUpValueType) => void)) : any
useState(UseStateType.Primative, initialcontent: TLookUpValueType, setMethod?: (value: TLookUpValueType) => void)) : [
setContent, getContent]

useState(UseStateType.ArrayObject, initialcontent: TLookUpValueType, setMethod? :(value: TLookUpValueType) => void)) : [
setContent, setItem, ,getContent, getModStamp, tickModStamp]

useState(UseStateType.Object, initialcontent: TLookUpValueType, setMethod? :(value: TLookUpValueType) => void)) : [
setContent, setItem, ,getContent, getModStamp, tickModStamp] {

const setItem = (pos, item) => {
item[modStamp] = (this.state.array[pos][modStamp] || 0)++;
 this.state.array[pos] = item;
}

return [.., setItem, .. , ..];
}



render () {

return  <React.Fragment>
this.state.map(it => <Item key={it.key} modStamp={it.modStamp} value={it}>
</React.Fragment>
}

```

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.

**Comment by wesleyolis** [comment]
@bvaughn Thank you you for your feedback.

I manage to get another 20minutes of thought on this or a worrying factor that typing system in c++ sort out for you, but not here, in which have reference issues.
I am still trying to think of a big pattern were I can just create many nested little forms and drive them off a massive API structure response of arrays and objects and primitives'. I jsut have not found the right permutation that works out in my head while play it all out.

For now just going to continue with my notes here, such that when get time I can go that root, but my thought process is saved here for any future on looks and myself.

One more simplification would be for dealing with nested structures of objects and arrays, things.
Where the setItem, is already path awhere
```.ts 
const [setContent, getCotent,setItem ] =setState(state, PathKeys[]) // PathKeys array undefined, means user define key must be entered.

setItem([PathKey1, PathKeyArray4, PatheyKeyItemObjectLevel5, value);

// as I say below need fingout out propagation of stuff, which is my big ass massive form just work at any level, componets just reference variables in api repsonse.
```

**The following issues to think about when dealing with JavaScript hidden**


const symFirst = Symbol("first");
const symReplace = Symbol("replace")

class CustomObjectClass {

    constructor(str) {
        this.str = str;
    }
    toString() {
        return this.str
    }
}

const valueStore = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "Reference", // Primative Value
    num: 1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: new Date(500), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symFirst,   // Reference
    clss: new CustomObjectClass("First")
  }
  
  
  console.log(valueStore);

  const valueStoreCopy = {...valueStore}
  
  valueStoreCopy.str = "   Changed   "
  valueStoreCopy.num = 2;
  valueStoreCopy.boolean = false;
  valueStoreCopy.BInt = BigInt(3)
  valueStoreCopy.dt = new Date()
  valueStoreCopy.arr.push(4)
  valueStoreCopy.sym = symReplace;  // Typically this is read only
  valueStoreCopy.clss = new CustomObjectClass("Second")

  
  console.log(valueStore);
  console.log(valueStoreCopy);

//const test = 1;
  
const valueStore2 = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "    Reference    ", // Primative Value
    num:  1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: new Date(0), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symFirst,   // Reference
    clss: new CustomObjectClass("First")
  }
  
  const valueStoreCopyEdit = {...valueStore2}
  
  valueStoreCopyEdit.str.trim() //  No methods that I can see as of yet.
  valueStoreCopyEdit.num++; // This I can mutate in place, typically a copy constructor
  valueStoreCopyEdit.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyEdit.BInt++     // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyEdit.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyEdit.arr[2]++    // doesn't mutate in place.
  valueStoreCopyEdit.sym;  // Typically this is read only
  valueStoreCopyEdit.clss = new CustomObjectClass("Second") // class unless they all const methods as in c++

  console.log(valueStore2);
  console.log(valueStoreCopyEdit);


// So basically date, array, object and anything else that is new will be reference copies, which will destory the react native style of working.
// Array[Primatives]
// Array[ContainRef]
// Object[Primatives]
// Array[Object]
// Object[Array]
// Object[Ref]

// React only looks good for basic root level stuff right now, because one needs additional copy operators.

// So basically if you have a value which is not a primative, then you need a spesically deep copy, or toJSON FromJson.

// Then basically you have these containers, which can be mutate, which typically are references.
// They are typically mutated with Create, Update, Delete.
// 1: Create, Which style of natural storage is use deterministic (there is a name for this, what do we call it, forgot again) ordering or can you append.
// 1.1 Typically if you can append to end of iteration.
// typicall if have mutiple views, you want to do full control refresh, by iterating the existing structure.
// could just keep a diff list of ids, to speed up these types of controls, in which feed the the top level reference
// and just store change up to max items of all controls.

// 2: Update, typically if this depends on the type, if its reference based and one is mutating the original one will have to carefully look
// at javascript implementation of readonly, as top level is use, less, has to be recusive all the way and needs to block non const methods.
// I don't know of a way to prevent this in typescript, as method could have to be declare const or readonly, I will have to check this out at function level 
// this really depends on wether this also is feeding another control at object level with a reference, in which case it may keep a copy internally.
// in which case editing the original is no issues, don't need to keep creating a new copy.
// basically we need the concept of c++ const.
// that or use a libary which knows how to copy everything for you like lodash.
// um the other is could creat a typeing such that it can prevent this.
// one would have to apply a constraint wrapper, and on all classes that use it would have to add that constraint, ideally one need a
// prevention check, which means all default properties need a fantom type.
// Basically, as long as component, is storing a copy and not an ref, which external referencing things, they you be ok.
// as the component has the original state, which you should propergate out and upate the parent state.
// however if need propogation and then another function depends on that state being updated, then those functions
// need to first reflect things, for othe methods. Just depends weather update from top level down, or have incremental updates need to think of the pattern.
//

// 3. Delete, well basically delete is an issues, as you have removed and item, ideally want the fiew to be update, otherwise the item will 
// no longer be there unless it is storing a reference.
// Remeber garbar collection here clean up those remaning items referencing things, as long you don't directly reference things any where.
// if it is like an array of primative value consts, then basically delete, will remove your reference and cause crashing
// as you can't operate on those values, view in such as case has to be updated.
// So when dealing with const value types, then ones needs to basically keep two lists, to prevent crashing, or think some back ground hybrid data structures that
// that all can implement some form of Create, Update, Delete Verb type change system.

// Guess need to look into ensure class can't hold references, in which think it tought may improve things.

// Need more thinking again about all the permutations and ways to construct things in.

**Comment by wesleyolis** [comment]
@bvaughn I am wondering if you able to awnser one to question about my checking the behaviours of types below, where I summaries things. Does React.Native deep object.freeze this.state that when updated using this.setState get frozen including classes, such that they ensure copies are made and potentially those which classes, in which class need to not be frozen after copy assignment, just prevent ref mutation like c++ does with const.

Do you know how to temporally freeze class for an instance, however, after copy assignment to another variable they are then no longer fozen, I think the later, is not possible. what do you think?

Right now I don't see simple solution, to preventing previous state corruption.


Node 10, I know need retest this on the latest, but many implementation of javsascript, behaviours tot test.

Well basically pre and post perations work as expected, with fall throught reference, typically mutate the existing object state if it was not frozen or deep frozen. 
how do we freeze classes. BigInt is basically a class and doesn't freeze, num does freeze, suspect boolean would freeze, can't test string
This means we need to know what types object.freeze work on.

Looks like we currently have 3 behaviours with regards to references.
1. boolean, string, num
2. class, object, array
3.  New behaviour BigInt, possibly symbol

Basically everything in JS is a reference including primatives, until there is a fork of the memory. String seem to always fork as the return a new value for functions, there
no, however, a pass tought reference, would basically be linked and not forked. Kind normal how we expect things, but there subtitle problems here.

So if you don't have freeze and deepfreeze, then javascript is all references on everything, and the behaviour of primatives or anything totally depends
on the methods implementation on the objects prototype chain, weather it mutates the this instance. Typically on requires the c++ const requirement here,
such that class of a const form can be used to ensure, the don't create reference mutations of previous state.

How to protect code, well for objects use object.freeze, for class, I need to look at this.
The other would be a typicaly constraint for typescript, that prevents non-const methods results being used in statments and assigned to readonly objects.
however, you also want this in runtime code of js. Currently I don't see any way of doing this.

Which means for react to work in the way its does of each mutation of state, it is required to freeze everything, however, can't freeze instances of classes as glocal freeze of that class type
, at the moment The other issues, is silightly fails with  basically on with the mutation, so one may think those operations work, but in essance they are not,
but at least we can detect them.

React after every state mutation update, would have to recusive object.freeze everything and strip all class mutation variables, for it to work correctly and for users
to detect problems, this could be the default behaviour in dev and test mode, to cause errors to be found.

So need to think of solutions here, to prevent this from happening at JS level for class readonly and const, mmm, typescript to the rescure I think here.
but we want first be readonly and then writable afterwards, as it would have caused it all the memory to fork. Still need improvement here, like applying readonly
to a reference recusively, removes all non const methods.

// Maps also copy and mutate, need to test passthrough there, suspect be the same, as value is also reference, only forking main keys, just don't use nonconst methods like prefix++ and post++
BigInt or class are reference copies, not copies by value.
i.e
const StateA = {}

const nonMutableStateA = Readonly<StatesA>// or run js method that recusively does what I discribe for react to revent mutating references in the privious state.
const StateB = nonMutableStateA.map(v => v)

The other how can we make state copies simpler, at js level, I don't know with out implement like the above behaviours, like in ts.



```.js
const symFirst = Symbol("first");
const symReplace = Symbol("replace")

class CustomObjectClass {

    constructor(str) {
        this.str = str;
    }

    setMutateNoNConstMethod(str) {
      this.str = str;

      return this;
    }

    toString() {
        return this.str
    }
}

const valueStore = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "Reference", // Primative Value
    num: 1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: new Date(500), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symFirst,   // Reference
    clss: new CustomObjectClass("First")
  }
  
  
  console.log(valueStore);

  const valueStoreCopy = {...valueStore}
  
  valueStoreCopy.str = "   Changed   "
  valueStoreCopy.num = 2;
  valueStoreCopy.boolean = false;
  valueStoreCopy.BInt = BigInt(3)
  valueStoreCopy.dt = new Date()
  valueStoreCopy.arr.push(4)
  valueStoreCopy.sym = symReplace;  // Typically this is read only
  valueStoreCopy.clss = new CustomObjectClass("Second")

  
  console.log(valueStore);
  console.log(valueStoreCopy);

//const test = 1;
  
const valueStore2 = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "    Reference    ", // Primative Value
    num:  1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: new Date(0), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symFirst,   // Reference
    clss: new CustomObjectClass("First")
  }
  
  const valueStoreCopyEdit = {...valueStore2}
  
  valueStoreCopyEdit.str.trim() //  No methods that I can see as of yet.
  valueStoreCopyEdit.num++; // This I can mutate in place, typically a copy constructor
  valueStoreCopyEdit.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyEdit.BInt++     // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyEdit.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyEdit.arr[2]++    // doesn't mutate in place.
  valueStoreCopyEdit.sym;  // Typically this is read only
  valueStoreCopyEdit.clss = new CustomObjectClass("Second") // class unless they all const methods as in c++

  console.log(valueStore2);
  console.log(valueStoreCopyEdit);


  const valueStore3 = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "    Reference    ", // Primative Value
    num:  1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: new Date(0), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symFirst,   // Reference
    clss: new CustomObjectClass("First")
  }
  
  
const dt = new Date();
dt.setFullYear(1999);

  const valueStore4 = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "    Reference    ", // Primative Value
    num:  1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: dt, // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symReplace,   // Reference
    clss: new CustomObjectClass("Second")
  }

  const valueStoreCopyAssignEdit = {...valueStore3}
  
  // 
  valueStoreCopyAssignEdit.str = valueStore4.str.trim() //  No methods that I can see as of yet.
  valueStoreCopyAssignEdit.num = valueStore4.num++; // This I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.boolean = valueStore4.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyAssignEdit.BInt = valueStore4.BInt++;     // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.dt = valueStore4.dt// valueStore4.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyAssignEdit.arr = valueStore4.arr[2]++    // Basically this is correct, however, if working with state this would not be workable
  valueStoreCopyAssignEdit.sym = valueStore4.sym;  // Typically this is read only
  valueStoreCopyAssignEdit.clss = valueStore4.clss = new CustomObjectClass("Second") // class unless they all const methods as in c++

  console.log("next Section - 1")

  console.log(valueStore3);
  console.log(valueStore4);
  console.log(valueStoreCopyAssignEdit);

  console.log("next Section - 2")

{
  const valueStoreCopyAssignEdit = {...valueStore3}
  
  valueStoreCopyAssignEdit.str = valueStore4.str; //  No methods that I can see as of yet.
  valueStoreCopyAssignEdit.num = valueStore4.num; // This I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.boolean = valueStore4.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyAssignEdit.BInt = valueStore4.BInt;     // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.dt = valueStore4.dt// valueStore4.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyAssignEdit.arr = valueStore4.arr[2]    // Basically this is correct, however, if working with state this would not be workable
  valueStoreCopyAssignEdit.sym = valueStore4.sym;  // Typically this is read only
  valueStoreCopyAssignEdit.clss = valueStore4.clss = new CustomObjectClass("Second") // class unless they all const methods as in c++


  valueStoreCopyAssignEdit.str.trim() //  No methods that I can see as of yet.
  valueStoreCopyAssignEdit.num++; // This I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyAssignEdit.BInt++;    // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyAssignEdit.arr[2]++    // doesn't mutate in place.
  valueStoreCopyAssignEdit.sym;  // Typically this is read only
  valueStoreCopyAssignEdit.clss = new CustomObjectClass("Second") // class unless they all const methods as in c++
}
  console.log(valueStore3);
  console.log(valueStore4);
  console.log(valueStoreCopyAssignEdit);

  const pre = valueStoreCopyAssignEdit.arr++;
  console.log(valueStoreCopyAssignEdit.arr);
  console.log(pre);

  const pre2 = ++valueStoreCopyAssignEdit.arr;
  console.log(valueStoreCopyAssignEdit.arr);
  console.log(pre2);

  
'use strict';
const obj = {}
Object.defineProperty(obj, 'LUNG_COUNT', {value: 2, writable: false});
obj.LUNG_COUNT = 3;  // TypeError
console.log(obj.LUNG_COUNT);



  {
    console.log("next Section - 3")
    
  const valueStore3 = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "    Reference    ", // Primative Value
    num:  1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: new Date(0), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symFirst,   // Reference
    clss: new CustomObjectClass("First")
  }
  
  
const dt = new Date();
dt.setFullYear(1999);

  const valueStore4 = {
    un: undefined, // Primative Value
    nil: null, // Primative Value
    str: "    Reference    ", // Primative Value
    num:  1, // Primative Value
    boolean: true, // Primative Value
    BInt: BigInt(1), // Primative Value
    dt: dt, // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
    // one will on have a single reference, and thus no two states.
    arr: [1,2,3],  // Reference,
    sym: symReplace,   // Reference
    clss: new CustomObjectClass("Second")
  }

  //Object.freeze(valueStore4);

  const valueStoreCopyAssignEdit = {...valueStore3}
  
  // is is really bad, because actually
  valueStoreCopyAssignEdit.str = valueStore4.str.trim() //  No methods that I can see as of yet.
  valueStoreCopyAssignEdit.num = valueStore4.num++; // This I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.boolean = valueStore4.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyAssignEdit.BInt = valueStore4.BInt++;     // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.dt = valueStore4.dt// valueStore4.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyAssignEdit.arr = valueStore4.arr[2]++    // Basically this is correct, however, if working with state this would not be workable
  valueStoreCopyAssignEdit.sym = valueStore4.sym;  // Typically this is read only
  valueStoreCopyAssignEdit.clss = valueStore4.clss.setMutateNoNConstMethod("mutated") // class unless they all const methods as in c++  
  //valueStoreCopyAssignEdit.clss = valueStore4.clss // class unless they all const methods as in c++  

  console.log(valueStore3);
  console.log(valueStore4);
  console.log(valueStoreCopyAssignEdit);

  
  valueStoreCopyAssignEdit.str.trim() //  No methods that I can see as of yet.
  valueStoreCopyAssignEdit.num++; // This I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyAssignEdit.BInt++;    // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyAssignEdit.arr[2]++    // doesn't mutate in place.
  valueStoreCopyAssignEdit.sym;  // Typically this is read only
  valueStoreCopyAssignEdit.clss.setMutateNoNConstMethod("mutate2") // class unless they all const methods as in c++  

  console.log(valueStore4);
  console.log(valueStoreCopyAssignEdit);

  }


  {
    console.log("next Section - 4")
    const valueStore3 = {
      un: undefined, // Primative Value
      nil: null, // Primative Value
      str: "    Reference    ", // Primative Value
      num:  1, // Primative Value
      boolean: true, // Primative Value
      BInt: BigInt(1), // Primative Value
      dt: new Date(0), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
      // one will on have a single reference, and thus no two states.
      arr: [1,2,3],  // Reference,
      sym: symFirst,   // Reference
      clss: new CustomObjectClass("First1")  // Object.freeze(new CustomObjectClass("First1")) will freeze the object prototype from which everything inherites, basically making the whole class readonly everywhere.
    }
    
    // Object.freeze(valueStore3.clss);, the same thing applies.
    
  const dt = new Date();
  dt.setFullYear(1999);

    const valueStore4 = {
      un: undefined, // Primative Value
      nil: null, // Primative Value
      str: "    Reference    ", // Primative Value
      num:  1, // Primative Value
      boolean: true, // Primative Value
      BInt: BigInt(1), // Primative Value
      dt: dt, // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
      // one will on have a single reference, and thus no two states.
      arr: [4,5,6],  // Reference,
      sym: symReplace,   // Reference
      clss: Object.freeze(new CustomObjectClass("First"))
    }


  const valueStoreCopyAssignEdit = {...valueStore3}

  Object.freeze(valueStoreCopyAssignEdit);

  
  valueStoreCopyAssignEdit.str = valueStore4.str; //  No methods that I can see as of yet.
  valueStoreCopyAssignEdit.num = valueStore4.num; // This I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.boolean = valueStore4.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyAssignEdit.BInt = valueStore4.BInt;     // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.dt = valueStore4.dt// valueStore4.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyAssignEdit.arr = valueStore4.arr[2]    // Basically this is correct, however, if working with state this would not be workable
  valueStoreCopyAssignEdit.sym = valueStore4.sym;  // Typically this is read only
  valueStoreCopyAssignEdit.clss = valueStore4.clss //Object.freeze(valueStore4.clss) // class unless they all const methods as in c++

  console.log("clss:::" + valueStoreCopyAssignEdit.clss)

  valueStoreCopyAssignEdit.str.trim() //  No methods that I can see as of yet.
  valueStoreCopyAssignEdit.num++; // This I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.boolean;   // typically all readonly methods or in c++ terms const methods.
  valueStoreCopyAssignEdit.BInt++;    // Typically I can mutate in place, typically a copy constructor
  valueStoreCopyAssignEdit.dt.setFullYear(2025);    // mutate in place.
  valueStoreCopyAssignEdit.arr[2]++    // doesn't mutate in place.
  valueStoreCopyAssignEdit.sym;  // Typically this is read only
  valueStoreCopyAssignEdit.clss.setMutateNoNConstMethod("mutate") // class unless they all const methods as in c++  

  console.log(valueStore3);
  console.log(valueStore4);
  console.log(valueStoreCopyAssignEdit);
}



{
  console.log("next Section - 5")
  
const valueStore3 = {
  un: undefined, // Primative Value
  nil: null, // Primative Value
  str: "    Reference    ", // Primative Value
  num:  1, // Primative Value
  boolean: true, // Primative Value
  BInt: BigInt(1), // Primative Value
  dt: new Date(0), // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
  // one will on have a single reference, and thus no two states.
  arr: [1,2,3],  // Reference,
  sym: symFirst,   // Reference
  clss: new CustomObjectClass("First")
}


const dt = new Date();
dt.setFullYear(1999);

const valueStore4 = {
  un: undefined, // Primative Value
  nil: null, // Primative Value
  str: "    Reference    ", // Primative Value
  num:  5, // Primative Value
  boolean: true, // Primative Value
  BInt: BigInt(10), // Doesn't freeze behaviours like a class
  dt: dt, // Reference , will have issues with copying complex structure to pass to classes, as won't be editing duplicates, where you may think a date should be stored in simple for,
  // one will on have a single reference, and thus no two states.
  arr: [11,12,13],  // Reference,
  sym: symReplace,   // Reference
  clss: new CustomObjectClass("Second")
}

Object.freeze(valueStore4);

const valueStoreCopyAssignEdit = {...valueStore3}

// is is really bad, because actually, the operations seem to fail and we don't have passthrought reference, just result in a value copy.
valueStoreCopyAssignEdit.str = valueStore4.str.trim() //  No methods that I can see as of yet.
valueStoreCopyAssignEdit.num = valueStore4.num++; // This I can mutate in place, typically a copy constructor
valueStoreCopyAssignEdit.boolean = valueStore4.boolean;   // typically all readonly methods or in c++ terms const methods.
valueStoreCopyAssignEdit.BInt = valueStore4.BInt++;     // Typically I can mutate in place, typically a copy constructor
valueStoreCopyAssignEdit.dt = valueStore4.dt// valueStore4.dt.setFullYear(2025);    // mutate in place.
valueStoreCopyAssignEdit.arr = valueStore4.arr[2]++    // Basically this is correct, however, if working with state this would not be workable
valueStoreCopyAssignEdit.sym = valueStore4.sym;  // Typically this is read only
valueStoreCopyAssignEdit.clss = valueStore4.clss.setMutateNoNConstMethod("mutated") // class unless they all const methods as in c++  
//valueStoreCopyAssignEdit.clss = valueStore4.clss // class unless they all const methods as in c++  
console.log(valueStoreCopyAssignEdit);
valueStoreCopyAssignEdit.str.trim() //  No methods that I can see as of yet.
valueStoreCopyAssignEdit.num++; // This I can mutate in place, typically a copy constructor
valueStoreCopyAssignEdit.boolean;   // typically all readonly methods or in c++ terms const methods.
valueStoreCopyAssignEdit.BInt++;    // Typically I can mutate in place, typically a copy constructor
valueStoreCopyAssignEdit.dt.setFullYear(2025);    // mutate in place.
valueStoreCopyAssignEdit.arr++    // doesn't mutate in place.
valueStoreCopyAssignEdit.sym;  // Typically this is read only
valueStoreCopyAssignEdit.clss.setMutateNoNConstMethod("mutate") // class unless they all const methods as in c++  


console.log(valueStore3);
console.log(valueStore4);
console.log(valueStoreCopyAssignEdit);
}


```

// So basically date, array, object and anything else that is new will be reference copies, which will destory the react native style of working.
// Array[Primatives]
// Array[ContainRef]
// Object[Primatives]
// Array[Object]
// Object[Array]
// Object[Ref]

// React only looks good for basic root level stuff right now, because one needs additional copy operators.

// So basically if you have a value which is not a primative, then you need a spesically deep copy, or toJSON FromJson.

// Then basically you have these containers, which can be mutate, which typically are references.
// They are typically mutated with Create, Update, Delete.
// 1: Create, Which style of natural storage is use deterministic (there is a name for this, what do we call it, forgot again) ordering or can you append.
// 1.1 Typically if you can append to end of iteration.
// typicall if have mutiple views, you want to do full control refresh, by iterating the existing structure.
// could just keep a diff list of ids, to speed up these types of controls, in which feed the the top level reference
// and just store change up to max items of all controls.

// 2: Update, typically if this depends on the type, if its reference based and one is mutating the original one will have to carefully look
// at javascript implementation of readonly, as top level is use, less, has to be recusive all the way and needs to block non const methods.
// I don't know of a way to prevent this in typescript, as method could have to be declare const or readonly, I will have to check this out at function level 
// this really depends on wether this also is feeding another control at object level with a reference, in which case it may keep a copy internally.
// in which case editing the original is no issues, don't need to keep creating a new copy.
// basically we need the concept of c++ const.
// that or use a libary which knows how to copy everything for you like lodash.
// um the other is could creat a typeing such that it can prevent this.
// one would have to apply a constraint wrapper, and on all classes that use it would have to add that constraint, ideally one need a
// prevention check, which means all default properties need a fantom type.
// Basically, as long as component, is storing a copy and not an ref, which external referencing things, they you be ok.
// as the component has the original state, which you should propergate out and upate the parent state.
// however if need propogation and then another function depends on that state being updated, then those functions
// need to first reflect things, for othe methods. Just depends weather update from top level down, or have incremental updates need to think of the pattern.
//

// 3. Delete, well basically delete is an issues, as you have removed and item, ideally want the fiew to be update, otherwise the item will 
// no longer be there unless it is storing a reference.
// Remeber garbar collection here clean up those remaning items referencing things, as long you don't directly reference things any where.
// if it is like an array of primative value consts, then basically delete, will remove your reference and cause crashing
// as you can't operate on those values, view in such as case has to be updated.
// So when dealing with const value types, then ones needs to basically keep two lists, to prevent crashing, or think some back ground hybrid data structures that
// that all can implement some form of Create, Update, Delete Verb type change system.

// Guess need to look into ensure class can't hold references, in which think it tought may improve things.

// Need more thinking again about all the permutations and ways to construct things in.

**Comment by markerikson** [comment]
@wesleyolis I think you're making this way too complicated :)  You should probably look at using https://immerjs.github.io/immer/ for immutable updates.

**Comment by wesleyolis** [comment]
@bvaughn When Working between all languages like C++, which since Pointers(References) and value instance on the stack, allow for the flexiblity that is required, because you can easily through tough out the language differentiate the behavior and do the correct operation that is required. JS it becomes tricky as we know.

On of my thoughts, is mabye just adopted a copy by value operator which is =* or * or $= on the end of the class for typescript.
Typically on the prototype chain it will ensure the deep correct nested copy of all necessary instance parameters to reproduce and object, regardless of inheritance and depth of the prototype chain, while preserving the existing prototype chain.
Typically one could all protypechain for name function for now, that provides cloneShallow, cloneDeep, clone for primatives.
This way, basically have clone method that copies instance parameters directly, going past the set and gets, basically achieving a simple c++ memcopy equivalent. If every object implements this, then clone would be much simpler and when trying to preserve and not corrupt state, the the clone method would be avaliable, because it would be of time const.
Where const only allows access the =* operator in its function for this.variables, and other const methods.
It would potentially then still return a derived class from the existing state, with out there being a reference clone.

In Javascript I am think of the following for state stuff.

const StateA = {};

const readonly StateAPhsicalClone =  StateA 

// where this modifier basically only allows const methods in the PrototypeChain to be called and =* operator function if it exists. I was thinking mabye another value modifier, where could have mutiple function annotated as =*, such field in the different protoType look up, but if applied the const constraint like we have in c++ and have request support for in typescript, then, basically all access in const method for properties access with this, would by default for assignment have to use =* Typescript could enhance the typings, by ensure the correct derivation or = or *= has to be used to prevent msitakes. all class and instantiations, would have to use a modified new method, that would check a flag, that there is zero other references to the value. Just by having a clone and value operator(=*) for cloning, would simplfy things.

Could also just chose the symbol $=.

To simplify things, react could provide a library that injects this functionality into the bas prototype chain of js, such correctly valuable everywhere.
