### ISSUE TITLE
Idea: Shorthand Property Initialization

### ISSUE THREAD

**Issue by ethanlal04** [facebook/react#22039]
Hello,

```
export default function App() {
  const src = "https://picsum.photos/200";

  return (
    <img src={src} alt="A random image" />
  );
}
```
Above, the value of the `src` property is the `src` variable. In such a case, `Svelte` lets us exclude the repetitive attribute like this...
```
<img {src} alt="A random image" />
```
I'd like to have the same in React. I think this would make the code more concise. Thank you 😀.

**Comment by bvaughn** [comment]
This has been proposed a few times: #9696, #9707, #13967, #15731, #20164, #21236

The place to request/suggest this is the JSX repo though, specifically: https://github.com/facebook/jsx/issues/23

I'm going to close this issue and suggest you join the discussion on that one. 👍🏼

**Comment by ethanlal04** [comment]
Oops, didn't see that. Thanks.
