### ISSUE TITLE
Bug: It takes a long time from componentdidmount() method to render()

### ISSUE THREAD

**Issue by JiangWeian** [facebook/react#22031]
My React version is 16.8.6. 
It took 2 seconds from the componentDidMount() method to the render() method of the OHIFCornerstoneViewport class:
![TIM图片20210805102855](https://user-images.githubusercontent.com/56569509/128285696-85a58f66-e57d-458f-ae10-fa90458a7d01.png)

What causes this problem? Large amount of data?

**Comment by JiangWeian** [comment]
![TIM图片20210805162057](https://user-images.githubusercontent.com/56569509/128317177-1f07acaa-06a2-4f3b-8094-4d02392ec9f2.png)

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by JiangWeian** [comment]
This callback is to execute cornerstone.renderToCanvas():
![TIM图片20210806082300](https://user-images.githubusercontent.com/56569509/128437662-e6573203-b843-409c-9a79-417ae9323476.png)

This is a problem found in testing ohif viewer. Please refer to https://github.com/OHIF/Viewers/issues/2502
