### ISSUE TITLE
Bug: Cannot update a component (`BucketIcon`) while rendering a different component (`Bucket`). To locate the bad setState() call inside `Bucket`, follow the stack trace as described in 

### ISSUE THREAD

**Issue by hejialianghe** [facebook/react#22055]
React version:17.0.1

**Comment by kkanekii** [comment]
@hejialianghe please elaborate

**Comment by hejialianghe** [comment]
resolved

**Comment by kkanekii** [comment]
@hejialianghe any issues?

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by hejialianghe** [comment]
It's been solved . This error is because I'm doing dispatch in useMemo
