### ISSUE TITLE
Bug: "NotFoundError" when removeChildFromContainer -> container.removeChild(child) is called

### ISSUE THREAD

**Issue by Saranya13** [facebook/react#22054]
React throw an unhandled exception "NotFoundError" when removeChildFromContainer -> container.removeChild(child) is called on a node that doesn't contains the child anymore.
This only occurs in IE 11.

React version: 17.0.2

## Steps To Reproduce

1. open the attached sample and run the application in **ie11**
2. then click the **toggle grid** button
3. Then you can see the script error in console like below.

![image](https://user-images.githubusercontent.com/38315832/128839214-47e67800-3833-4c3d-a776-5d2975dcb0aa.png)

Link to code example:

[grid-notfounderror-ie11.zip](https://github.com/facebook/react/files/6960342/grid-notfounderror-ie11.zip)

## The current behavior

"NotFoundError" when removeChildFromContainer -> container.removeChild(child) is called

## The expected behavior

Need to working as like chrome edge browsers

**Comment by nidhijeena** [comment]
I opened the above project and i am not able to find any error in console.
![Screenshot (1340)](https://user-images.githubusercontent.com/52296061/130735260-966cdd68-6bb9-4200-8df7-eb76942095d2.png)

**Comment by nidhijeena** [comment]
I am not able to found any error on console.
![Screenshot (1342)](https://user-images.githubusercontent.com/52296061/130735570-953b85c3-ed00-4ae0-89c8-aca14078376f.png)
