### ISSUE TITLE
[DevTools Bug]: 

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#22065]
### Website or app

https://facebook.com

### Repro steps

I've reproduced this with Brave and Chrome

1. Login with your own facebook account
2. Open the React devtools
3. Notice the scrollable components are squished to one side.

![image](https://user-images.githubusercontent.com/1500684/128950233-d17f4325-0cfe-4a5a-b300-06b3f759367a.png)

Seems to not happen to everyone, but [quite a few others](https://twitter.com/kentcdodds/status/1425181014704353282) have seen this happen and I can't figure out what's causing this.

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment]
Hey @kentcdodds. When we chatted earlier, I mentioned that I haven't been able to repro this locally myself. Could you provide some more info about your setup, like your operating system and version, browser version, DevTools version, and whether you're using an external monitor? Anything that might shed light here.

**Comment by jstejada** [comment]
Looks like this is the same issue as https://github.com/facebook/react/issues/21986, should we merge them?

**Comment by jstejada** [comment]
I'm going to go ahead and merge this into #21986
