### ISSUE TITLE
Inifinite recursion can be caused when lifecycle methods trigger a re-render

### ISSUE THREAD

**Issue by kassens** [facebook/react#2207]
If lifecycle methods cause re-renders we can potentially end up in infinite recursion. I've seen this happen somewhere in a bigger application and it was difficult to find. I'm not sure there's anything React could do to prevent these cases though.

Two reduced examples: https://gist.github.com/kassens/7e223c2b299f4a46ada1

**Comment by gaearon** [comment]
We're now throwing if you trigger more than 1000 (I think) nested updates.
