### ISSUE TITLE
Dev tools react probleme

### ISSUE THREAD

**Issue by marekredon** [facebook/react#22086]
Bonjour, 
Je viens d'installer React dev Tools, mais il n'est pas actif.
Pourtant, j'ai tout activé.
Je suis sur Windows 10, et j'ai téléchargé l'extension il y a 30 min, 
![devtools](https://user-images.githubusercontent.com/67319788/129355926-5d3d8513-483d-423f-a538-305fdb4b1b2b.jpg)
![extensions](https://user-images.githubusercontent.com/67319788/129355934-20a71bb0-fc23-4005-b502-17ce7625b8ec.jpg)

**Comment by bvaughn** [comment]
Essayez de redémarrer votre navigateur.

**Comment by bvaughn** [comment]
Ce bogue est généralement corrigé par l'un de ceux-ci :
1. Fermez et rouvrez devtools.
2. Rechargez le site Web.
3. Redémarrez votre navigateur.

J'espère que ça aide! Bonne journée.

**Comment by marekredon** [comment]
Alors, le point 2 et 3 n'ont pas marché.
Le 1 : comment ferme-t-on devtools ?
Questions subsidiaires : j'ai l'impression que mon React developer tools est pâle (il est gris) alors qu'il devrait être en couleur ? Et RDT devrait marcher sur chaque page si je fais F12 ou seulement sur celles où du React est présent ?

**Comment by marekredon** [comment]
Je viens de voir qqchose d'intéressant : seuls qqes sites utilisent react.
Et c'est juste pour ces sites-là que react dev tools s'active ! Je viens de le voir sur facebook et slack !
Et moi qui croyais que tous cette extension s'affichait sur tous les sites !

**Comment by bvaughn** [comment]
L'extension ne fonctionne que lorsqu'elle est utilisée sur des sites construits avec React. Désolé pour la confusion.
