### ISSUE TITLE
Improve production error stack trace for Invariant #31

### ISSUE THREAD

**Issue by johnstoca** [facebook/react#22082]
Is it possible to improve the production/minified error stack trace for invariant #31?

We saw this one in production and due to the generic nature it was not of much use. It would be much more useful if the component throwing the error could be identified.

Is this possible given what is available in the minified production bundle?

### How to Reproduce
1. `npx create-react-app my-app`
2. `cd my-app`
3. Modify `./src/App.js` to the following
```
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <>
      {{ errors: [] }}
    </>
  );
}
```
4. `npm run build`
5. `serve -s build`
6. Open the application in web browser
7. Note the error in the console
```
react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Berrors%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ka (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Io (react-dom.production.min.js:176)
    at Hu (react-dom.production.min.js:268)
    at Pi (react-dom.production.min.js:250)
    at xi (react-dom.production.min.js:250)
    at _i (react-dom.production.min.js:250)
    at vi (react-dom.production.min.js:243)
    at fi (react-dom.production.min.js:237)
    at Gi (react-dom.production.min.js:285)
```
8. Go to suggested URL to see error explanation `Objects are not valid as a React child (found: object with keys {errors}). If you meant to render a collection of children, use an array instead.`

Ideally, we would be able to see the component here, if possible.

**Comment by remorses** [comment]
I would also need to know the React component that caused Hydration mismatch errors

In my case users can upload content so it becomes impossible to debug these issues given that the stack trace only contains react functions locations and not my own code

For now i just keep these Hydration mismatch errors (and so do all other websites hosting user generated content)
