### ISSUE TITLE
react-dom@alpha UMD bundle throws when rendering

### ISSUE THREAD

**Issue by josepharhar** [facebook/react#22113]
React version: 18.0.0-alpha-bd255700d-20210816 or main branch

## Steps To Reproduce

1. Use ReactDOM development from alpha version or main branch
2. Call ReactDOM.render() or ReactDOM.createRoot(...).render()

Link to code example: https://jsfiddle.net/jarhar/sLz2f5q1/
If you open DevTools you can see the error which is preventing rendering. If you change the scripts from development.js to production.min.js, you can see the problem go away.

**Comment by bvaughn** [comment]
Looks like you're not loading the `scheduler` module in the linked Fiddle. Here's a repro that includes that module:
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/scheduler@alpha/scheduler.development.js"></script>
    <script src="https://unpkg.com/react@alpha/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@alpha/umd/react-dom.development.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      const container = document.createElement('div');

      document.body.appendChild(container);

      const root = ReactDOM.createRoot(container);
      root.render(React.createElement('div', null, 'Testing...'));
    </script>
  </body>
</html>
```
That being said, I see this error when trying the above:
```
Uncaught TypeError: Cannot read property 'current' of undefined
    at scheduleCallback$1 (react-dom.development.js:26447)
    at ensureRootIsScheduled (react-dom.development.js:24715)
    at scheduleUpdateOnFiber (react-dom.development.js:24535)
    at updateContainer (react-dom.development.js:27717)
    at ReactDOMRoot.render (react-dom.development.js:28126)
    at <anonymous>:352:54
    at n (babel.min.js:12)
    at r (babel.min.js:12)
    at o (babel.min.js:12)
    at u (babel.min.js:12)
```

The same code works fine when using a CJS build:
https://codesandbox.io/s/sad-brown-wcz1n

**Comment by bvaughn** [comment]
Inspecting the UMD bundles. Looks like the `ReactSharedInternals` object is different in a way that's unexpected.

React UMD bundle:
```
var ReactSharedInternals = {
  ReactCurrentDispatcher: ReactCurrentDispatcher,
  ReactCurrentBatchConfig: ReactCurrentBatchConfig,
  ReactCurrentOwner: ReactCurrentOwner,
  // Used by renderers to avoid bundling object-assign twice in UMD bundles:
  assign: assign
};

{
  ReactSharedInternals.ReactDebugCurrentFrame = ReactDebugCurrentFrame;
  ReactSharedInternals.ReactCurrentActQueue = ReactCurrentActQueue;
}
```

Also React UMD bundle:
```
var ReactSharedInternals$1 = {
  ReactCurrentDispatcher: ReactCurrentDispatcher,
  ReactCurrentOwner: ReactCurrentOwner,
  ReactCurrentBatchConfig: ReactCurrentBatchConfig,
  // Used by renderers to avoid bundling object-assign twice in UMD bundles:
  assign: assign,
  // Re-export the schedule API(s) for UMD bundles.
  // This avoids introducing a dependency on a new UMD global in a minor update,
  // Since that would be a breaking change (e.g. for all existing CodeSandboxes).
  // This re-export is only required for UMD bundles;
  // CJS bundles use the shared NPM package.
  Scheduler: Scheduler
};
...
exports.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED = ReactSharedInternals$1;
```

ReactDOM is reading from `exports.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` but expecting values from `ReactSharedInternals` (specifically `ReactCurrentActQueue`).

**Comment by bvaughn** [comment]
So we end up with two "internals" object. One with these keys (which never gets shared outside of the module):
```
{
  assign,
  ReactCurrentBatchConfig,
  ReactCurrentDispatcher,
  ReactCurrentOwner,
  ReactDebugCurrentFrame,
  ReactCurrentActQueue,
}
```

And one with these keys (which does get shared):
```
{
  assign,
  ReactCurrentBatchConfig,
  ReactCurrentDispatcher,
  ReactCurrentOwner,
  ReactDebugCurrentFrame,
  Scheduler,
}
```

The difference in keys is that the exported object has `Scheduler` and the non-exported object has `ReactCurrentActQueue`. (Both are expected to be the same.)

**Comment by bvaughn** [comment]
Merging these two objects fixes the bundle (at least for my simple test app).

**Comment by bvaughn** [comment]
Note to self (or anyone else who looks into this): The fastest way to test how a change to source impacts the UMD bundles is:
```sh
node scripts/rollup/build.js --type=UMD_DEV -- react/index,react-dom/index
```

**Comment by bvaughn** [comment]
Small update:

The first `ReactSharedInternals` object (`ReactSharedInternals` in the bundle) comes from here:
https://github.com/facebook/react/blob/bd255700d73ed5fa88f9e32fa4b43623679adf0c/packages/react/src/ReactSharedInternals.js#L15-L26

The second `ReactSharedInternals` object (`ReactSharedInternals$1` in the bundle) comes from here:
https://github.com/facebook/react/blob/bd255700d73ed5fa88f9e32fa4b43623679adf0c/packages/react/src/forks/ReactSharedInternals.umd.js#L15-L28

The second one is the one that actually gets written to `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED`.
