### ISSUE TITLE
Potential expensive operation optimisation

### ISSUE THREAD

**Issue by ishmum123** [facebook/react#22131]
This seems to be an expensive operation - 
https://github.com/facebook/react/blob/aa25824f3ebbdbbea01be48417f2f99251be1a12/packages/react-reconciler/src/ReactFiberTreeReflection.js#L325

used in loops in -

i) https://github.com/facebook/react/blob/aa25824f3ebbdbbea01be48417f2f99251be1a12/packages/react-reconciler/src/ReactFiberCommitWork.new.js#L322
ii) https://github.com/facebook/react/blob/aa25824f3ebbdbbea01be48417f2f99251be1a12/packages/react-reconciler/src/ReactFiberCommitWork.new.js#L345

Can/Should we use memoize this somehow?

**Comment by Max0nyshchenko** [comment]
I'd like to take this one, is it free @ishmum123 ? But I see no exported types ReactFiberHostConfig, is it how it should be ? any help?

**Comment by rickhanlonii** [comment]
Thanks but micro-optimizations without context like this are often [misleading](https://mrale.ph/blog/2014/12/24/array-length-caching.html). Happy to revisit if you can show that this function is the bottleneck in this code — which so far doesn't seem very likely.
