### ISSUE TITLE
refs for function components as first class citizens

### ISSUE THREAD

**Issue by KutnerUri** [facebook/react#22133]
I'm looking everywhere, but I can't seem to find an official answer.

It seems `ref`s are discouraged, and developers are required to use `forwardRef`, or pass ref as a separate prop (i.e. `forwardRef={ref}`). 
`ref` are very important when access to the DOM is required, usually when a measurement is needed.
Example usages include **tooltips**, graph nodes, animations, and dom observers.

For example, [@tippyjs/react](https://www.npmjs.com/package/@tippyjs/react) assumes children receive a ref (since `findDOMNode` is deprecated), and will simply fail with most components.
Another example is a `ClickOutside` hook, that watches click events and triggers callback which clicking on a dom element outside a specific component.

Lastly, it really complicated component compositions.
Composing components and ultimately forwarding all props down to the DOM allows us to use all components as first class citizens, so they all have the same abilities as a div. I can pass an event handlers, data attribute, tabIndex, etc, to any component, without having to alter it.
```tsx
interface UserMenuProps extends MenuProps {
  users: User[];
}

function UserMenu({users, ...rest}: UserMenuProps) {
  // even if Menu supports ref forwarding, I need to forwardRef again just to keep the same behavior.
  return <Menu {...rest}>
    {props.users.map(x=> <UserItem user={x})}
  </Menu>
}

function SettingsPage(props) {
  const privacyRef = useRef(null);
  const validatePrivacy = () => {...};
  
  useClickOutside(privacyRef, validatePrivacy());

  return <div>
     {/* tooltip is implicitly using ref to target children */}
     <Tooltip content="this is your user menu!">
       <UserMenu className="centered" />
     </Tooltip>
     {/* PrivacySettings is already getting ref, so tooltip needs an explicit target */}
     <Tooltip content="select how public you want to be!" target={privacyRef} />
       <PrivacySettings ref={privacyRef} style={{shadow: "1px 2px black"}} onClick=(...)/>
     </ Tooltip>
  </div>
}
```

I don't like to use forwardRef because:
* It prevents even the simplest of component from being used in (our) legacy react 15 project.
* The syntax is really complicated, and I need to set the same function name 3 times for each component.
* I don't want to add it to every single component I make. (and force my team to do the same).

I would prefer to use refs as first class citizens, like
```tsx
function Menu(props: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      {...props}
      className={cn("menu", props.className)}
      // just to emphasize, I'm getting the ref from the props.
      // I could also apply it to a different element, or pass a completely different object for ref.current, or keep it null
      ref={props.ref}
    />
  )
}
```

I see a hint here - https://github.com/reactjs/rfcs/pull/107#issuecomment-466282354, that refs will finally be first class props in the new JSX transform. Is this true? or will we still be required to use forwardRef?

Most importantly, can I rely on it in projects with the new transform? including legacy project using `React 15.7.0`?

**Comment by graup** [comment]
I found a [tweet](https://twitter.com/dan_abramov/status/1227020523990851585) from @gaearon from 2020 saying it is planned to simplify refs in the future. Did anything happen since then regarding this? Are there any other issues where we can follow this?
