### ISSUE TITLE
propTypes range?

### ISSUE THREAD

**Issue by lencioni** [facebook/react#2214]
What do you think about adding a feature that would allow people to specify a range for number propTypes? Something like this:

``` js
propTypes: {
  percentage: React.PropTypes.range('0..1')
}
```

The range type would take a string that represents a numerical range. `..` is an inclusive range and `...` means that the last element is excluded.

This would have a similar feel to the `oneOf` propType.

**Comment by ljharb** [comment]
Just a heads up; we found lots of value out of this, so we created `range` in https://www.npmjs.com/package/airbnb-prop-types for anyone who wants it. (it uses `oneOf` under the hood, but that's just an implementation detail)

It currently only support exclusive ranges (ie, a range of `[2, 4]` allows `2` and `3`) and integers, but I'd be happy to entertain feature requests for variations.

**Comment by genericlady** [comment]
It's completely unnecessary. There's already `oneOf`, all you have to do is iterate over a range and place the values in an array. Then use the array with `oneOf`, it's a very simple solution and is considered programming basics.

```javascript
var weight_range = [];                                                          
for (var i = 80; i <= 300; i++) {                                               
  weight_range.push(i);                                                         
}

// React.PropTypes.oneOf(weight_range).isRequired
```

If you want to get fancy you can use the custom prop solution.
```react
Product.propTypes = {
  weight: function(props, propName, componentName) {
    let weight = props[propName];
    
    if (weight === undefined) {
      return new Error("Sorry you must include a number for weight.");
    }

    if (isNaN(weight)) {
      return new Error("Sorry weight must be a number.");
    }

    return weight >= 80 && weight <= 300 ? null : new Error("Must be within range of 80 to 300");
  }
};

```

**Comment by ljharb** [comment]
@genericlady that's how `range` works, but your way, you have to build the array first. Separately, I've now built `between` in `airbnb-prop-types`, which allows you to encode >, >=, <, and <= semantics directly in the validator, without needing to create a large array in-memory.

**Comment by genericlady** [comment]
@ljharb on line 20 in `range.js`
```
return wrapValidator(and([integer(), between({ gte: min, lt: max })], 'range'), 'range', { min, max });
```

can it be shortened to?

```
return wrapValidator(and([integer(), between(min, max)], 'range'), 'range', { min, max });
```

**Comment by ljharb** [comment]
@genericlady no - if `between` took positional arguments, there'd be no clean way to encapsulate all 4 of `>, <`, `>, <=`, `>= <`, and `>= <=` - that's why I intentionally chose an object. If you have a better solution, please do file an issue on the airbnb-prop-types repo and we can discuss it there :-)
