### ISSUE TITLE
DevTools scroll-to error or warning feature broken

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#22143]
Not sure when this happened, but the feature got broken:

https://user-images.githubusercontent.com/29597/130155150-18fbca13-42d7-4d7d-831e-8db4a9672d94.mp4

Using the up/down arrows to navigate the list works fine, but jumping to the next/previous component with a warning or error doesn't quite work correctly. (The scroll offset is wrong so the component is often not visible.)

**Comment by iunfixit** [comment]
I cannot reproduce this unless I'm doing something wrong, tested with errors here

![ErrorJump](https://user-images.githubusercontent.com/89200249/130164076-4e9bd9f1-8360-41a2-9743-c363907c9161.gif)

The part where it is selected outside of the view is because of the recording, it never goes behind the console

**Comment by bvaughn** [comment]
I wonder if this is related to a Chrome experimental flag? I can repro in both Chrome stable and canary.

**Comment by eps1lon** [comment]
I can reproduce on Version 92.0.4515.159 (Official Build) (64-bit) (with and without our good friend "Throttle non-visible cross-origin iframes" enabled).

Though it does scroll. It just is a bit offset. It also seems to work on upward movement if the current node is already in the frame.

Notice how the scrollbar actually moves:

https://user-images.githubusercontent.com/12292047/130199347-50bf578a-6436-4d4d-b2bb-7ffb5ef40c18.mp4

**Comment by eps1lon** [comment]
I can fix it locally with 

```diff
diff --git a/packages/react-devtools-shared/src/devtools/views/Components/Tree.js b/packages/react-devtools-shared/src/devtools/views/Components/Tree.js
index 629bc0f721..82650fea19 100644
--- a/packages/react-devtools-shared/src/devtools/views/Components/Tree.js
+++ b/packages/react-devtools-shared/src/devtools/views/Components/Tree.js
@@ -90,7 +90,7 @@ export default function Tree(props: Props) {
   const listCallbackRef = useCallback(
     list => {
       if (list != null && selectedElementIndex !== null) {
-        list.scrollToItem(selectedElementIndex, 'smart');
+        list.scrollToItem(selectedElementIndex, 'start');
       }
     },
     [selectedElementIndex],
```

It seems to me that the calculations for the positions are off since `'start'` will keep the current item a bit below the center of the viewport.

**Comment by iunfixit** [comment]
> I wonder if this is related to a Chrome experimental flag? I can repro in both Chrome stable and canary.

I only tested with the default instead of enabled, because when it is enabled it freezes everything, I am using Brave 1.28.105 Chromium: 92.0.4515.131, DevTools version 4.16.0-1d2528097
I also notice sometimes the tool doesn't work, unless I change the code and it hot reloads

![ErrorJumpNotShowing](https://user-images.githubusercontent.com/89200249/130218500-4e2e1f55-fbe0-498e-acc7-c23ef33e0a0f.gif)

<details>
  <summary>The code is just modified from the latest CRA</summary>
  

```
import logo from './logo.svg';
import './App.css';
import React from 'react'

const Err = () => [`a`, `b`, `d`].map(i => <p key={1}>something</p>);
const TenDivs = () => <><div/><div/></>
const Div = () => <div><Err/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><TenDivs/><Err/><Err/></div>;

function App() {
  return (
    <div className="App">
      <header className="App-header"> <Div/>
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p> 
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a> <Div/> <Div/> <Div/> <Div/>
          <Div/>
          <Div/>
          <Div/>
          <Div/>
          <Div/>
          <Div/>
          <Div/>
          <Div/>
          <Div/>
          <Div/>
        <Err/>
      </header> 
    </div>
  );
}

export default App;
```


</details>
