### ISSUE TITLE
Warn when a component is passed props that it doesn't need

### ISSUE THREAD

**Issue by jussi-kalliokoski** [facebook/react#2215]
It would be cool to be able to get warnings for typoed or otherwise extraneous props passed to a component, similar to how `React.DOM` warns if you pass `class` when you meant `className`.

With `PropTypes.shape` you could probably even ensure deep validity of the passed data. This would not only be useful for finding bugs, but also for optimizing hot components by making sure the shapes are aligned.

Obviously this would need some sort of opt-in, like propTypes.

**Comment by zpao** [comment]
Merging this into #1587 which has more discussion.
