### ISSUE TITLE
React 18 and next.js

### ISSUE THREAD

**Issue by Padmanabh82** [facebook/react#22153]
react is so plain.we have to write bunch of code for small things, so i think react should include all functions (code) of next.js, for one or two functionality we have to change whole framework or make a new project and write whole bunch of code for it and there many opensource frameworks like next.js from which we can borrow functionality and improve react.if you are agree with me, its my pleasure to help you with writing code for it.main functionality i think react should have are in built all 3 types of SSR and file based routing.please reply me soon as possible. thanks in advance

**Comment by Padmanabh82** [comment]
Please tell why are people dislike it

**Comment by Padmanabh82** [comment]
If there are any negative point tell me

**Comment by thisRaptori** [comment]
One of React's strengths is that it provides a relatively small API, and lets you build what you need on top of that.

Take the things you're asking for as an example: for my job, we would not need any of them, so adding them to React would add more weight to the library (more to learn, more code to ship to the client, etc) without providing us any value. The same applies to things which would help with the apps I'm working on - sounds like they would be irrelevant for whatever you're building, and would not be worthwhile.

There are a lot of people who would argue in favour of a more monolithic approach, but it is not the direction React has generally taken. React's simplicity means that solutions like Next can more easily be built on top of it, and provide that kind of approach for those who want it!


As an aside, it comes across as very strange to like your own messages! 😛

**Comment by gaearon** [comment]
Hi, thanks for the suggestion! Like @thisRaptori says, we see value in people using React in different ways. I suggest you to start your projects with Next.js since it fits your purposes well.

**Comment by Padmanabh82** [comment]
@thisRaptori sir as you tell this will add more weight on react we can use it on import system like we can import any function if we want and we can remove things that we don't want

And I only 1 peace in world
