### ISSUE TITLE
[Blocks Fixture] Migrate to built-in <Cache> API and regression test

### ISSUE THREAD

**Issue by ryota-murakami** [facebook/react#22152]
# Summary
This is task list issue.  
"Blocks" fixture app which made by [built-in <Cache> API](https://github.com/reactwg/react-18/discussions/25), 'react-fetch', [Server Component](https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html) combination that useful to play new features v18 later.  

But current one is broken because importing removed older Cache API module.  
And difficult to notice that regression because there are no tests.  

So I planning these task for Blocks working fine again and write regression tests.

- [ ] https://github.com/facebook/react/pull/22151
- [ ] Write regression tests with [Cypress](https://www.cypress.io/)
- [ ] Consider better implementation at some `@TODO` comments, where should we invoke cache `refresh()` function etc...

# Screen Capture
https://user-images.githubusercontent.com/5501268/130333311-0f12d038-370f-4203-a039-7f396b6db2fd.mov

**Comment by vishal5251** [comment]
I want to work on this issue could you please explain a bit more about this issue.

**Comment by Subhojit-Dey1234** [comment]
Can anyone help? I am new to an open source projects. How can I start?

**Comment by ryota-murakami** [comment]
Thank you for forks who has interest about this issue.  
Actually, the "Good to First Issue" label is attached by @bvaughn however this [Blocks Fixture] part original author  is @gaearon.

Therefore we have to wait to take up bellow first PR review,

- https://github.com/facebook/react/pull/22151

And confirm Dan to how about my regression test plan with Cypress.
So waiting is only option now until get response Dan or other core team's guy review.

**Comment by aniruddhapw** [comment]
I would like to contribute

**Comment by Harshvardhan1999** [comment]
I would love to contribute

**Comment by FlashStar09** [comment]
I want to contribute here!

**Comment by pawan43563** [comment]
I would love to contribute

**Comment by yash431garg** [comment]
I can help you in that would love to contribute

**Comment by Lis27ha** [comment]
I would love to contribute as well

**Comment by tarzan114** [comment]
Hi i'd love to contribute as well

**Comment by anushaNemilidinne** [comment]
Hello! This will be my first contribution to open source projects. Can I contribute?

**Comment by Voloda56** [comment]
Я тоже хочу внесты внесок?

**Comment by gabrielhamilton** [comment]
Hi i'd like to contribute.

**Comment by akhilmern** [comment]
Hi i'd like to contribute.

**Comment by bharadwajduggaraju** [comment]
would love to help out too once this issue becomes more prevalent

**Comment by Fasunle** [comment]
Hello, I would love to contribute to this issue. This is my first open source contribution too.

**Comment by rahulgajawada** [comment]
I would like to contribute as well

**Comment by cuobiezi** [comment]
Hello, I would love to contribute to this issue. This is my first open source contribution too.

**Comment by ameyalambat128** [comment]
Hello, I would love to contribute to this issue as well

**Comment by amanpanwar27** [comment]
can u explain it better , i really want to contribute , i am a beginner though

**Comment by iseolin76** [comment]
Hello, I would love to contribute to this issue

**Comment by vscodeman** [comment]
绝绝子

**Comment by xenmitsu** [comment]
not really clear issue.

**Comment by franklinwagbara** [comment]
Please is this issue still open because I'd like to contribute.

**Comment by xetosu** [comment]
> Please is this issue still open because I'd like to contribute.

Yes, it's still open.

**Comment by tagalong420** [comment]
If there's anything I can help with I'll try my best to get it figured out an acceptable to run. I'm in process right now on restoring my laptop cause I was hacked 4 months back an just have gotten enough money and time to resolve the situation that i got. But anyways I will help out any way I can.. 
  Best Regards , TagaLong420

**Comment by AvyayKhaire26** [comment]
I would like to contribute

**Comment by illipuddi** [comment]
Did you mean "folks"

>

**Comment by itshershey** [comment]
I would Like to contribute

**Comment by itshershey** [comment]
I would Like to contribute

**Comment by itshershey** [comment]
I would Like to contribute

**Comment by itshershey** [comment]
I would Like to contribute

**Comment by whddnjs1715** [comment]
hello guys i'm totally new here
wanna contribute to open source 
How can i start open source??? 
first fork? after then?? can you help me guys??

**Comment by itshershey** [comment]
> hello guys i'm totally new here wanna contribute to open source How can i start open source??? first fork? after then?? can you help me guys??

Don't worry we are here to guide you!

**Comment by jeongwoopark0514** [comment]
Hello, @jahb, @mirijam1, @budihan, and I are a team from TU Delft. We are taking a course called Software Architecture. We chose ReactJS as our project, and would like to start our first contribution with this issue!

**Comment by githubbaizi** [comment]
I would like to contribute

**Comment by ashish0083** [comment]
Hi I would like to contribute to this if it is still unresolved.

**Comment by gaearon** [comment]
We should've removed the label a long time ago, there's nothing meaningful to contribute here at the moment.
