### ISSUE TITLE
Bug: Allow multiple instance of React (or inject one into the other)

### ISSUE THREAD

**Issue by grantila** [facebook/react#22159]
_FYI; Not sure if this is a bug or a feature request. It's a problem that is surprising when it happens, and there's no workaround I'm aware of._

Now that since 17, React is supposed to more easily be upgradable in that using components from an older/newer React in a different version will still work (and be supported), **the ability to run multiple instances concurrently** should be approached again.

From what I can see, this can be achieved in multiple ways;
 * Seamlessly allowing multiple concurrent React instances at once, or
 * Seamlessly re-using the same global scope React when importing/requiring consecutively, or
 * Allowing manual injection of one React instance into another

There are use cases for this, e.g. when using a component from a webpage in a jsdom environment. This is working for passive components not using any hooks, but as soon as you need hooks (or lifecycle management in general I suppose), the [Invalid Hook Call Warning](https://reactjs.org/warnings/invalid-hook-call-warning.html) (referenced in #13991) is triggered, due to _"3. You might have more than one copy of React in the same app."_

Consider the following code, which simulates a web page using React, which exposes a component on the global object "window" (this could be done in multiple ways, the implementation detail here is irrelevant). When running this webpage in a jsdom environment, using the web page's component from an outer context (potentially not even using react-dom but a custom reconciler), the "Invalid Hook Call Warning" is triggered. The example also shows where an outer React instance could be injected into another React (another global scope) if this was supported somehow:

```ts
import React, { PropsWithChildren } from 'react';
import { renderToString } from 'react-dom/server';
import { JSDOM } from "jsdom";


async function getRemoteComponent(): Promise<React.ElementType> {
  const html = `
  <html lang="en">
    <body>
      <script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
      <script>
        const component = () => {
          const [content] = React.useState('from webpage');
          return React.createElement( 'span', {}, [content] );
        }
        window.setComponent(component);
      </script>
    </body>
  </html>`;

  return new Promise((resolve, reject) => {
    new JSDOM(html, {
      url: 'http://localhost',
      runScripts: "dangerously",
      resources: "usable",
      beforeParse(window) {
        // If React would support something like this, it would solve the problem:
        // window.React = React;

        (window as any).setComponent = component => {
          resolve(component);
        };
      },
    });
  });
}

function Outer({children}: PropsWithChildren<{}>) {
  return <div>{children}</div>
}

getRemoteComponent()
.then( Inner => renderToString( <Outer><Inner /></Outer> ) )
.then( domString => console.log( `Result: ${domString}` ) );
```

Expected output (which you get when not using any hook):

`Result: <div data-reactroot=""><span>from webpage</span></div>`

There are two closed issues related to this, but with a different approach and not about actually enabling this afaict: #2402 and #3252
There's also #13991, but is mostly for how to detect when you have multiple instances concurrently, often due to packaging/bundling/dependency issues. This is not the same as _intentionally_ using multiple instances.

**Comment by grantila** [comment]
For some extra context, it **is** possible to hack around this, but there's no official "supported" way, which is what I'm after.

In the example above, when fetching React from a `<script>` tag, it'll add itself to `window.React`, so that **is** overwriteable (as long as you overwrite it *after* it's been adding itself to `window` obviously). But is this supported?

When building a web app with webpack and using es modules, React won't register itself to `window`, however I found that:

```ts
import React from 'react';
Object.assign(React, NewReactFromSomewhere);
```

works. But this is especially horrible, and although it "seems to work", it's surely not officially supported I presume?

**Comment by lubieowoce** [comment]
Another possible workaround: You could use webpack externals (or equivalent from another bundler) to make sure the same `React` instance is used everywhere without hacking around "in userspace". (`ReactDOM` needs the same treatment iirc)

And I hope I don't sound like a Webpack shill 😄 But if you're using Webpack and doing stuff with "remote components", [Module federation](https://webpack.js.org/concepts/module-federation/) may be interesting to you. They even have an [example that says it makes multiple React versions work together somehow](https://github.com/module-federation/module-federation-examples/tree/master/different-react-versions).
