### ISSUE TITLE
Bug: Types should not use the `any` type hack

### ISSUE THREAD

**Issue by SRachamim** [facebook/react#22164]
_React_ types use `any`. For example, `useCallback`:

```typescript
function useCallback<T extends (...args: any[]) => any>(callback: T, deps: DependencyList): T;
```

The `any` is a workaround to turn-off the type system. I don't expect 3rd party libraries to use it. Even when this type is to the right of `extends`, it ruins the type-inference and could leak to the consumer.

For example, here is a code that will compile even though it has runtime error. It compiles since _TypeScript_ inferes an `any`.

```typescript
const f = useCallback((a) => a / 5)

export const res = f('d')
```

React version: 17.0.2

## The current behavior

_React_ uses the `any` hack, turning off typechecker on many cases.

## The expected behavior

Should use generic types or at least `unknown` (a legitimate top type). For example:

```typescript
export const useCallback =
  <A extends ReadonlyArray<unknown>, B>(f: (...a: A) => B) =>
  (...a: A): B =>
    f(...a)
```

...which will infer `unknown` and hence won't compile. It will force the developer to either
- write defensive code by refining this `unknown` to a `number`, or to
- narrow the Input type to `number` with `useCallback((a: number) => a / 5)`.

**Comment by bvaughn** [comment]
TypeScript types for React are not maintained by the React team. They live in the DefinitelyTyped repository, here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts

You should probably file this issue in that repository:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/new

(Or create a Pull Request!)
