### ISSUE TITLE
Bug: Context updated but components doesn't

### ISSUE THREAD

**Issue by wgxh-cli** [facebook/react#22186]
React version: Latest

## Steps To Reproduce

1. Create a context and provide it.
```typescript
import React, { createContext, useContext } from 'react';

const defaults = {
  count: 1,
  inc() { this.count++ },
  dec() { this.count-- },
}
const counterContext = createContext(defaults);
const App = () => (
  <div className="app">
    <counterContext.Provider value={defaults}>
      <Counter />
    </counterCnotext.Provider>
  </div>
)
```
2. Create `Counter` component.
```typescript
const Counter = () => {
  const counter = useContext(counterContext);

  return (
    <div className="counter">
      <button onClick={counter.inc} />
      <span>{counter.count}</span>
      <button onClick={counter.dev} />
    </div>
  )
}
```

## The current behavior
After click the add button, it will show 2.

## The expected behavior
It show 1, but context updated.

**Comment by wgxh-cli** [comment]
Oh thanks!

**Comment by eps1lon** [comment]
@joealden Already explained how this is expected behavior really well.

I would add that context doesn't behave different in regards to updates as props. If you would pass `{ counter: 1}` as a prop and would mutate the value of the object, React would also not update the component.
