### ISSUE TITLE
A11y related Bug: onKeyPress doesn't trigger on element (tabindex="0") when narrator is on

### ISSUE THREAD

**Issue by daihuaye** [facebook/react#22195]
React version: 17.0.2 
System: Window 10

## Steps To Reproduce

1. Turn on Narrator app (Native app in Window)
2. go to the link https://q799n.csb.app/
3. use tab navigate to the Div element
4. Press any keys

Link to code example:
https://codesandbox.io/s/loving-frost-q799n?file=/src/App.js

```js
import React from "react";

export default function App() {
  const [count, setCount] = React.useState(0);
  const logMe = () => {
    setCount((c) => c + 1);
  };
  return (
    <div onKeyPress={logMe} tabindex="0">
      <h1>Repro step:</h1>
      <h2>1. turn on Narrator app (Native app in Window)</h2>
      <h2>2. Use tab to navigate to here</h2>
      <h2>3. Press any keys and key press count is {count}.</h2>
      <h2>Note: Count won't updated when narrator is on</h2>
    </div>
  );
}
```

## The current behavior
The count value doesn't change

## The expected behavior
The count value will increase by 1 on every key press

**Comment by rowanD72** [comment]
You never called setCount. Calling setCount will change the count state.

**Comment by rowanD72** [comment]
Change setCount to setCount(count +1);
