### ISSUE TITLE
Suggestion: React 18 (PureComponent)

### ISSUE THREAD

**Issue by zdu-strong** [facebook/react#22209]
Hello, I am a programmer.
When I use PureComponent, it is very efficient. But React does not provide a setState method that can modify immutable data structures.
Therefore, the immer library is used in the setState method to implement the modification of immutable data.
You can consider absorbing immer, and then provide an easy-to-use setState method.

![image](https://user-images.githubusercontent.com/48673442/131292263-94202b6e-d461-4327-a021-0e0d8e3642ca.png)

Here are more examples of use.
![image](https://user-images.githubusercontent.com/48673442/131293818-26893034-acc3-4eba-9afa-2a4df0609420.png)

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.
