### ISSUE TITLE
Bug: Unsupported window.navigator.clipboard

### ISSUE THREAD

**Issue by WHK102** [facebook/react#22204]
React version: 17.0.2
Browser: Mozilla Firefox 91.0.2
O.S: GNU/Linux, Ubuntu 20.04 LTS
Node: v14.17.5

## Steps To Reproduce

Write component with:

```
console.log(window.navigator);
console.log(window.navigator.clipboard);
```

## The current behavior

`window.navigator` is resolved fine but `window.navigator.clipboard` is undefined, but from navigator developer console is already defined:

```
> Navigator { permissions: Permissions, mimeTypes: MimeTypeArray, plugins: PluginArray, doNotTrack: "1", maxTouchPoints: 0, mediaCapabilities: MediaCapabilities, oscpu: "Linux x86_64", vendor: "", vendorSub: "", productSub: "20100101" }
index.js:116
> undefined
```

## The expected behavior

When call `window.navigator.clipboard` return the original object from DOM.

`window` variable in jsx from component is not same as `window` from javascript browser?

**Comment by bvaughn** [comment]
This doesn't sound like something that has anything to do with React, but you haven't provided enough info for someone to be about to know.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by afshin-hoseini** [comment]
@WHK102 Apparently on Safari the access to `clipboard` object has been banned because of security issues.

> The API is limited to secure contexts, which means that navigator.clipboard is not present for http:// websites([more](https://portswigger.net/daily-swig/new-safari-clipboard-api-includes-additional-browser-security-privacy-mechanisms)).

On which browsers have you tested?

**Comment by bvaughn** [comment]
Seems like you can learn more about this here:
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

I'm going to close this issue as it seems highly unlikely it has anything to do with React.

**Comment by WHK102** [comment]
Yes, you are right, when developing the application it runs on localhost: 3000 and is considered an untrusted source, so the browser cannot access the clipboard object.
