### ISSUE TITLE
Bug: input onChange not triggered when input value is changed through ref current stepDown/Up functions

### ISSUE THREAD

**Issue by VilleMiekkoja** [facebook/react#22212]
Input with type number does not trigger onChange if native stepper functions are called through react ref current like this:

`inputRef.current.stepDown();`

If you press the step functions of a fully native (no react) number input, then the onChange will get called. But somehow it will not get called if they are called through react refs.

React version: 16.13.1

## Steps To Reproduce

1.  git clone  https://github.com/City-of-Helsinki/helsinki-design-system.git
2. git checkout a01414b3a4305e41b3e317a6654593d2ba2737c6
2. cd helsinki-design-system and install dependencies with `yarn`
3. cd packages/react and run `yarn test`

Link to code example:

https://github.com/City-of-Helsinki/helsinki-design-system/blob/fix/number-input-on-change/packages/react/src/components/numberInput/NumberInput.tsx#L154

## The current behavior

onChange does not get called.

## The expected behavior

onChange gets called.

I know I could probably call the native onChange myself. The thing is, Im not sure if react should handle this already. So if at some point react updates, and the function automatic onChange call is added, then in the component the onChange is then called twice.

**Comment by irinakk** [comment]
What you are doing is like doing `textInput.current.value = 'a'`, which will change the ui but not trigger onChange. Instead of using stepDown, I think the more proper fix would be to directly calling `props.onChange` and to reset min or max.
