### ISSUE TITLE
React 18 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.  Check the render method of `App`.

### ISSUE THREAD

**Issue by JadeClay** [facebook/react#22216]
Im trying to make an Sticky Application, and for that I coded two components. One is the container, that render every sticky component inside it, and the second uses the data that is given to it from a JSON.

```
class App extends React.Component {
  state = {
    notes: tasks
  }

  render(){
    return <Stickycontainer tasks={this.state.notes}/>
  }
}

class Stickycontainer extends React.Component{
  render(){
    return this.props.tasks.map(e => <Stickynote data={e}/>)
  }
}
```
This snippet works just fine, because I tried of instead of rendering an Stickynote, to just render a paragraph element with each object and its properties of the array. But the error comes when I try to implement the Sticky component down below:

```
class Stickynote extends React.Component{
    state = {
      show: true
    }

    render(){
      if(this.state.show){
        return(
          <div className="StickyNotes">
            <p>{this.props.data.id} - {this.props.data.description} - {this.props.data.title}</p>
    
            <div className="Actions">
              <button className="Delete" onClick={() => this.setState({show: false})}>
                  <Icon>delete</Icon>
              </button>
    
            </div>
          </div>
        );
      } else {
        return null;
      }
        
    } 
  }
```
It gave me this error:

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> Check the render method of App

What should I do with this?

**Comment by shanhan01** [comment]
if () {} else { } 外面再包裹个 { }

  render(){
     {
 if(this.state.show){
        return(
          <div className="StickyNotes">
            <p>{this.props.data.id} - {this.props.data.description} - {this.props.data.title}</p>
    
            <div className="Actions">
              <button className="Delete" onClick={() => this.setState({show: false})}>
                  <Icon>delete</Icon>
              </button>
    
            </div>
          </div>
        );
      } else {
        return null;
      }
     }
        
    }

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by NoelCov** [comment]
Hey there, pretty sure is because the paragraph tag is expecting a string and although your JSON object's values are strings, you are basically passing this to the paragraph tag: `<p>"hello" - "etc" - "etc"</p>` so of course it will NOT work. 

**What you need to do is the following:**

`<p> ``{this.props.data.id} - {this.props.data.description} - {this.props.data.title}`` </p>`

**The backticks ( ` ) are useful for string interpolation.**

Here, hope this helps: [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

**Comment by FlashStar09** [comment]
I would like to contribute here!

**Comment by JadeClay** [comment]
> Hey there, pretty sure is because the paragraph tag is expecting a string and although your JSON object's values are strings, you are basically passing this to the paragraph tag: `<p>"hello" - "etc" - "etc"</p>` so of course it will NOT work.
> 
> **What you need to do is the following:**
> 
> `` <p> ``{this.props.data.id} - {this.props.data.description} - {this.props.data.title}`` </p> ``
> 
> **The backticks ( ` ) are useful for string interpolation.**
> 
> Here, hope this helps: [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

That worked for me, thank you very much!

**Comment by NoelCov** [comment]
I'm glad it did. :)
