### ISSUE TITLE
Bug: React Command Prompt npm is Not Working

### ISSUE THREAD

**Issue by nallalayaswanth** [facebook/react#22219]
React version: 17.0.2
Node Version : v16

## Steps To Reproduce

1.npx create-react-app react-project
2.cd my react-project
3.npm start

## The current behavior
1.Extension reports: npm ERR! code EUNSUPPORTEDPROTOCOL

Note: While Executing a project Npm Error is coming and there is a bug on that npm command prompt

## The expected behavior
1.React Project To be Executed http://localhost:4200/
labels : [bug]

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble.

This repository is only for problems related to the React library. For Create React App please [file an issue in facebook/create-react-app](https://github.com/facebook/create-react-app/issues/new/choose).
