### ISSUE TITLE
React 17 npm run build does not copy the assets folder to dist

### ISSUE THREAD

**Issue by Shyam268** [facebook/react#22222]
the react configuration
    "@types/node": "^12.20.19",
    "@types/react": "^17.0.16",
    "@types/react-dom": "^17.0.9",

i have added config.json file in asset folder under src 
when i run  **`npm run build`** it does not copy the config.json file to dist folder.
i wanted to change the different configuration settings for different environment (test,stag,prod ...)
can you help me how to achieve this?

**Comment by bvaughn** [comment]
This is the React repo. It sounds like you're reporting an issue with create-react-app. Please report it in the create-react-app repository:
https://github.com/facebook/create-react-app/issues/

That repo is maintained by a different team of people.

Also, please search to see if the issue has already been opened before posting a new one.
