### ISSUE TITLE
Bug: Custom CSS Property with url() causing issues

### ISSUE THREAD

**Issue by yvesh** [facebook/react#22229]
React version: 17.0.2

## Steps To Reproduce

1. Use a Custom CSS property with the style attribute and an URL in the value, for example: `style={{'--bgi': 'url(https://example.com/test.jpg)'}}`
2. Compare the result with `style={{'backgroundImage': 'url(https://example.com/test.img)'}}`

[Live example](https://codesandbox.io/s/hopeful-haibt-vwl15?file=/src/App.js)

#### Output of the custom CSS property:

`style="--bgi:url(http\:\/\/example\.com\/test\.jpg);"`

#### With backgroundImage:

`style="--bgi:url(http://example.com/test.jpg);"`

## The current behavior

```
style="--bgi:url(http\:\/\/example\.com\/test\.jpg);"
```

## The expected behavior

```
style="--bgi:url(http://example.com/test.jpg);"
```

**Comment by abereghici** [comment]
@yvesh CSS custom properties are added using `style.setProperty` and this method serialize the URLs (https://drafts.csswg.org/cssom/#serialize-a-url) . 

The urls should be wrapped in double quotes, to skip the serialization:

`node.style.setProperty('--foo', 'url("http://example.com/test.jpg")')`

For CSS properties like `backgroundImage` the url is wrapped automatically in double quotes:

`node.style['backgroundImage'] = 'url(http://example.com/test.jpg)'`

**Comment by yvesh** [comment]
@abereghici Thanks for the explanation. Makes sense and probably can't be done automatically for custom properties :cry:
