### ISSUE TITLE
react-devtools-inline@4.17.0 weighs over 400MB (!!!)

### ISSUE THREAD

**Issue by AviVahl** [facebook/react#22220]
@bvaughn I think it was published by you. I see paths such as `/Users/bvaughn/Documents/git/react.devtools` in the bundle's comments.

v4.16.0 weighs under 8MB.
v4.17.0 weighs over 400MB and contains many dev-time bundles with source maps.

See https://www.npmjs.com/package/react-devtools-inline ("Unpacked Size: 426MB")
Or install locally to reproduce.

**Comment by bvaughn** [comment]
This is likely related to the named hooks feature, which imports `@babel/parser`. I thought this code only made its way into the browser extensions, but apparently it leaked.

We're looking to clean this up, regardless. Thanks for the info though. We'll be sure to look at the inline package as well.

**Comment by bvaughn** [comment]
This will be fixed by #22232

**Comment by AviVahl** [comment]
Thanks! I'll wait for the release :+1:

**Comment by bvaughn** [comment]
It's being published today, see #22234 😄

**Comment by AviVahl** [comment]
v4.18.0 verified as fixed from my end. Thank you for addressing this.
