### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by chunmu** [facebook/react#22236]
React version: 17.0.3

## Steps To Reproduce

 i found a mistake i think, i will show this by a picture

## picture 

![8678330A-0306-4E17-AEFF-BFF77E2659B4](https://user-images.githubusercontent.com/14954689/131878466-ad680084-7cf7-46f8-a582-ee7af271bb29.png)

## The current behavior

```javascript

import {noTimeout, supportsHydration} from './ReactFiberHostConfig';
// i cant find noTimeout and supportsHydration from ReactFiberHostConfig, is it correct?
```

## The expected behavior

ReactFiberHostConfig has export member with ```noTimeout & supportsHydration```

**Comment by jacty** [comment]
this is correct, I guess. Since what you see is before-bundle-version, after compile and bundle based on configuration, there they will be.

**Comment by bvaughn** [comment]
The host config file is overridden by host-specific renderers, which define these exports.

For example, React DOM:
https://github.com/facebook/react/blob/1314299c7f70914d61d8e1cef56767f112110674/packages/react-dom/src/client/ReactDOMHostConfig.js#L394
https://github.com/facebook/react/blob/1314299c7f70914d61d8e1cef56767f112110674/packages/react-dom/src/client/ReactDOMHostConfig.js#L682

The `ReactFiberHostConfig` file just exists as a placeholder that throws if a renderer forgets to override:
https://github.com/facebook/react/blob/1314299c7f70914d61d8e1cef56767f112110674/packages/react-reconciler/src/ReactFiberHostConfig.js#L22

**Comment by chunmu** [comment]
thx very much
