### ISSUE TITLE
Bug: useEffect not triggering on [deps] change

### ISSUE THREAD

**Issue by Tosheen** [facebook/react#22238]
I stumbled upon this issue which I believe is React bug, even though I found it using React Query. Minimal project is created to demonstrate the problem. In _card-status.js_ I registered useEffect which is watching for certain changes and it just displays the message whenever [deps] change. The problem is that one state change gets swallowed by useEffect. It can be seen if you click on a button and watch the console, useEffect is not triggered even though UI updates correctly aka rerender is triggered.
I have found that the issue is caused by line 60 in the same file. 

![image](https://user-images.githubusercontent.com/12643248/131887940-8856fea4-a5f1-42f5-b883-1e6872643dcc.png)

if that line is commented out, then useEffect triggers properly when button is clicked. Also if setState on line 60 is called with number for example then it also behaves correctly.

I believe this is a React issue.

React version: 17.0.2

## Steps To Reproduce

1. Open the console and click on the **activate trial** button.
2. useEffect message is not visible upon clicking, even though [dependency] changed and UI is rerendered.

Link to code example:

codesandbox: https://codesandbox.io/s/frosty-pateu-bh0ul
github repo: git@github.com:Tosheen/use-effect-bug.git

## The current behavior
useEffect doesnt register that the dependency has changed

## The expected behavior
useEffect should register new changes, since every other part of the UI does

**Comment by bvaughn** [comment]
Can you narrow this repro down further to rule out React Query?

**Comment by Tosheen** [comment]
Yeah, without react query I can not reproduce it. I guess I knocked on wrong door.
Anyhow, thank you!
