### ISSUE TITLE
Bug: React does not recognize the `allowTransparency` prop on a DOM element.

### ISSUE THREAD

**Issue by akashshyamdev** [facebook/react#22244]
I'm using an iframe:
```
<iframe
				width="100%"
				height="100%"
				frameBorder="0"
				title="Spline 3D Animation"
				allowTransparency={true}
				style={{ backgroundColor: "transparent" }}
				src="https://my.spline.design/portfolio-fe0fd4b29cba7bfea175804f995a9f8a/"
></iframe>
```

The console shows:

```
Warning: React does not recognize the `allowTransparency` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `allowtransparency` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

React version: ^17.0.2

Link to code example:
The entire code for this is here https://github.com/akashshyamdev/portfolio-latest/blob/master/src/containers/Home/Hero.tsx

## The current behavior
![Screenshot 2021-09-04 at 09 39 00](https://user-images.githubusercontent.com/56759828/132081920-41191ee9-3158-4f47-918b-804109d7902c.png)

## The expected behavior
I expect the black background to be transparent

**Comment by hariombalhara** [comment]
@akashshyamdev See if this helps https://github.com/remarkablemark/html-react-parser/issues/165

**Comment by eps1lon** [comment]
`allowTransparency` is an IE-only attribute which was removed in IE 9. You probalby want to set the background transparent with some CSS. 

If you know what you're doing, you can use `<iframe allowtransparency />`

For more context, see https://github.com/facebook/react/pull/10823.
