### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ashuto7h** [facebook/react#22245]
React version: 17.0.2

## Steps To Reproduce
- use cra and antd: 4.16.11

```js

const App: FC = () => {
    const [columns, setColumns] = useState([]);
    const [dataSource, setDataSource] = useState([]);
    const [modalVisible, setModalVisible] = useState(false);

   
    const TableHeader = memo(() => (
        <Row>
            <Col span={12}>
                <Title level={4}>Table</Title>
            </Col>
        </Row>
    ));

    return (
            <Row>
                <Col span={24}>
                    <Table
                        columns={columns}
                        dataSource={dataSource}
                        pagination={{
                            defaultPageSize: 5,
                            locale: { items_per_page: 'rows' },
                            pageSizeOptions: ['5', '10', '20'],
                            showSizeChanger: true
                        }}
                        scroll={{ x: '100%' }}
                        title={TableHeader}
                    />
                </Col>
            </Row>
    );
};
export default App;
```

## The current behavior
When i use memo for creating the TableHeader component, it compiles perfectly using npm start, but gives error on browser : `TypeError : titile is not a function`
this error occurs at some path similar to node_modules/rt-table/em/table.js 

if i remove the memo, then it works fine. 

I am not able to find what the error is? is it related to webpack or something else.

**Comment by cyntler** [comment]
@Ashuto7h what happens when you change `const TableHeader = memo` to `const TableHeader = useMemo`? I mean change memo for components to useMemo hook for the elements inside component.

**Comment by eps1lon** [comment]
This is an issue with `antd` which is not released from this repository.

It seems to me `title` only accepts a function not an actual component: https://ant.design/components/table/#API. If there is still something unclear, please use the proper support channels of Antd.
