### ISSUE TITLE
Bug: Warning: Cannot update a component (`MovieOverview`) while rendering a different component

### ISSUE THREAD

**Issue by alucardu** [facebook/react#22252]
I have a `login` component:

```
  const currentUser = useReactiveVar(currentUserVar);

  const {error, loading, data} = useQuery(
      resolvers.queries.ReturnMoviesFromUser, {
        fetchPolicy: 'no-cache',
        variables: {userId: currentUserVar().id},
        skip: currentUserVar().id === 0,
      });
  if (!loading && !error && data) {
    console.log(data.moviesFromUser);
    moviesVar(data.moviesFromUser);
  }
```

When a user logs in (or out) I do a `useQuery` to return some data and put that data in the reactive variable `moviesVar`.

Then in my `MovieOverview` component I have a line:

`const movies: IMovie[] = useReactiveVar(moviesVar);`

This sets the data stored in the reactive movie var on my movies array. The code works and the application runs as expected. But on the initial load I get an error:

> Warning: Cannot update a component (`MovieOverview`) while rendering a different component (`login`).

I'm pretty sure it's because I'm rendering the login and movieOverview component at the same time and using the reactive variable `moviesVar` between them.

React version:

    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "@apollo/client": "^3.4.9",

## Steps To Reproduce

1. create 2 components which are both rendered on run time
2. component a sets a value in a reactive variable
3. component b reads the value from the reactive variable

## Code sandbox 

https://codesandbox.io/s/sleepy-fire-im8ug?file=/src/App.js

The warning is not present on initial load. I trigger the warning by loading the sandbox, then change a text somewhere and save the changes. 
![image](https://user-images.githubusercontent.com/779921/132240023-9ec0607a-ef14-467c-901e-019252cf1722.png)

**Comment by gaearon** [comment]
The warning is correct.

This line in `useReactiveValue` calls a function:

https://github.com/apollographql/apollo-client/blob/7cc0c6c15f1302ceaf7a894a1eb1205514d8afb4/src/react/hooks/useReactiveVar.ts#L5

That function does a bunch of things:

https://github.com/apollographql/apollo-client/blob/7cc0c6c15f1302ceaf7a894a1eb1205514d8afb4/src/cache/inmemory/reactiveVars.ts#L57-L72

That includes mutation and "broadcasting" updates to other components.

It is not supported by React to do something like this during rendering. Rendering is supposed to be "pure" and not mutate or fire subscribers. Now, in practice, there are many cases where you can "get away" with doing it. However, Apollo is bending the rules here, so both warnings and unexpected behavior are possible. Please bring it up on the Apollo issue tracker and reference this issue. Apollo is a part of React 18 Working Group (https://github.com/reactwg/react-18/discussions) so they are very welcome to bring up this topic with us and see if we can reach a consensus on how the implementation and/or the API need to change.

**Comment by hwillson** [comment]
@alucardu @gaearon I don't think Apollo is bending the rules here. I don't believe `useReactiveVar` is doing anything that contradicts the rules of React. It is a tool, and tools can be misused. The real issue is:

```js
const Login = () => {
  moviesVar([{name: 'Movie name'}])
  ...
```

This means you're triggering a synchronous update during rendering, which is a user land issue.

**Comment by gaearon** [comment]
Ah I misread the condition. The initial path goes through the else branch which doesn't mutate.
