### ISSUE TITLE
Does React contains facebook tracking/survellience codes? 

### ISSUE THREAD

**Issue by ericreids** [facebook/react#22261]
**I fear if that survellience and tracking is also being done by facebook through react js?**

This is my biggest concern when using react in  making annonymous application in tor that doesnt track its users.

Please don't take it as exaggeration. I don't hate facebook but i just hate the amount of tracking and survellience that is being done by Facebook. 

Please answer me   @gaearon  @bvaughn  @acdlite  @sophiebits   and facebook teams.

**Comment by gaearon** [comment]
React is fully open source, you’re welcome to inspect it if you’d like. It makes no network calls and contains no tracking code. Keep in mind that you can always open the Network tab and audit the calls from your application.
