### ISSUE TITLE
When I console.log(), the Chrome console gives the log but instead of showing the file and line number 

### ISSUE THREAD

**Issue by mahanthi-arun-kumar** [facebook/react#22270]
When I console.log(), the Chrome console gives the log but instead of showing the file and line number it just says react_devtools_backend.js:4049. How do I get the console to show the file and line number when I console.log()?

**Comment by bk973** [comment]
Hello @mahanthi-arun-kumar is there some code that you can show???

**Comment by gaearon** [comment]
Duplicate of https://github.com/facebook/react/issues/22257.

**Comment by gaearon** [comment]
Here's a temporary workaround: https://github.com/facebook/react/issues/22257#issuecomment-916174962
