### ISSUE TITLE
Optional callback when updating state in functional components.

### ISSUE THREAD

**Issue by emindotbdk** [facebook/react#22273]
Hello everyone,

I have encountered some issues in fulfilling my needs with the `setState` function in functional components.

The method to update state in classic react components has the following syntax:
`setState(updater, [callback])`
The optional callback function is executed after the state has been updated asynchronously.

This option is not included in functional components. The alternative is to use a `useEffect()` hook with the desired state as a dependency. This, however, does not cover all my needs. I, for example, set the state and immediately call code which relies on that state. The state, however, will not be updated till then. This code should not be executed every time the state updates.

A callback function similar to that in classic react components would be helpful. An alternative to that would be for the setState function to return a promise. This can then be used to append a `.then` function and code dependent on the state can be executed.

**Example:**

```
const [stateVar, setStateVar] = React.useState(0);

const aFunction = () => {
    // Callback function executed after state has been updated
    setStateVar(12, () => { // callback function })
}

// Alternatively:

const aFunction = async () => {
    // setStateVar returns a promise -> dependent code can then be called
    setStateVar(12)
        .then(
            res => callback()
        )
}

```

**Comment by tasoskakour** [comment]
Hello @emindotbdk! 

Please could you write an example with a Class Component using the callback of `setState` that can't be rewritten by using `useState` and `useEffect` hook in a functional component? 

Wouldn't the code below act the way you desire replicating a "callback"/"effect" of setState?

Also, IMHO if `setVar` is called but doesn't actually change `var` (e.g passing the same variable) then your UI shouldn't have to update.

```
const [var, setVar] = useState(0); 

useEffect(() => { 
  // this will be called on mount and whenever var changes 
}, [var]); 

// somewhere in the component 
setVar(..)

```

**Comment by emindotbdk** [comment]
Hi @tasoskakour,

for context: The app I'm building has a qr-code scanner which is used to scan a qr-code containing an id. The UI should then display a card-like component with a loading indicator until the required data of the scanned entity-id has been loaded asynchronously.

I, therefore, have an array containing all the objects of the scanned elements I want to display. Those elements are rendered based on this array:
`const [productionCardList, setProductionCardList] = useState([]);`

The barcode-scan-callback function creates a new object, pushes the object to the productionCardList-array, updates the state with the newly added object and calls an asynchronous function to load the remaining data from a backend. Here arises the problem I have: The asynchronous function depends on the object in the state I'm just updating:

```
const onBarcodeScanned = (data) => {
    let productionCard = {id: barcodeData.id, selected: false, loading: true};

    let productionCardListCopy = [...productionCardList];
    productionCardListCopy.push(productionCard);

    setProductionCardList(
        productionCardListCopy
    };
    loadProductionOrderCardAsync(productionCard.id, productionCard); // Function reads the old productionCard state => lost update
}
```

I want the loadProductionOrderCardAsync() function to be called after the state has been updated successfully. What I don't want is the function to be executed on mount. The function should also just update the scanned object in the array, and therefore is dependent on the productionCard-id.

In a class component, I could simply add the loadProductionOrderCardAsync() function as a callback of the setState() method. This seems to not be possible in a functional component.

**Comment by vkurchatkin** [comment]
The thing is, even if `setState` had a callback, it wouldn't change anything:

```js
 setProductionCardList(
        productionCardListCopy,
        () => {
            // new state is rendered, but productionCardList is still the same
           // it can never change for any reason, it is literally a const
        }
    };
```

**Comment by tasoskakour** [comment]
> Hi @tasoskakour,
> 
> for context: The app I'm building has a qr-code scanner which is used to scan a qr-code containing an id. The UI should then display a card-like component with a loading indicator until the required data of the scanned entity-id has been loaded asynchronously.
> 
> I, therefore, have an array containing all the objects of the scanned elements I want to display. Those elements are rendered based on this array:
> `const [productionCardList, setProductionCardList] = useState([]);`
> 
> The barcode-scan-callback function creates a new object, pushes the object to the productionCardList-array, updates the state with the newly added object and calls an asynchronous function to load the remaining data from a backend. Here arises the problem I have: The asynchronous function depends on the object in the state I'm just updating:
> 
> ```
> const onBarcodeScanned = (data) => {
>     let productionCard = {id: barcodeData.id, selected: false, loading: true};
> 
>     let productionCardListCopy = [...productionCardList];
>     productionCardListCopy.push(productionCard);
> 
>     setProductionCardList(
>         productionCardListCopy
>     };
>     loadProductionOrderCardAsync(productionCard.id, productionCard); // Function reads the old productionCard state => lost update
> }
> ```
> 
> I want the loadProductionOrderCardAsync() function to be called after the state has been updated successfully. What I don't want is the function to be executed on mount. The function should also just update the scanned object in the array, and therefore is dependent on the productionCard-id.
> 
> In a class component, I could simply add the loadProductionOrderCardAsync() function as a callback of the setState() method. This seems to not be possible in a functional component.

I kinda got what you are trying to achieve. Would it make sense to have a `useEffect` listen on the `productionCardList.length`?

Also if you want this to fire only onUpdate and not on mount you can use the useRef hook as shown below.

```
const mounted = useRef(false);
const [productionCardList, setProductionCardList] = useState(..) 
const cardCount = productionCardList.length

useEffect(()=>{
   if (!mounted) {
      mounted.ref = true; 
      return 
  }
   
   // Here cardCount changed, it means that a new item is added to the array.
   // (be aware, the effect will happen even if an item is removed from the array)
, [cardCount])
```

**Comment by emindotbdk** [comment]
Thank you @vkurchatkin and especially @tasoskakour . You two helped me a lot. It seems that I have to change my solution to this problem and not force a callback for setState functions. Sorry for this issue! :)
