### ISSUE TITLE
Feature Idea: React.useConditional(key, () => { ... }) for conditional and dynamic hooks

### ISSUE THREAD

**Issue by jedwards1211** [facebook/react#22286]
I use `@apollo/react-hooks`' `useQuery` a lot, and recently I've had some cases where I needed to call `useQuery` for each item in an array.

In most idiomatic use cases, each item would map to a separate element UI, so I could have a custom component that performs a single `useQuery` and renders that list item.

But I have a use case where I'm fetching data for a dynamic list of historical data channels and then rendering data for all of them onto a single HTML canvas.  So I have to render a dynamic number of child elements that call `useQuery` once, stash the data in a ref from the parent element, and `return null`.

I've also had users of my `material-ui-popup-state` custom hook asking me how to map an array to hook calls.
Fortunately I was able to find a cleaner solution for them.

But, I'm starting to believe that the need for conditional/dynamic hooks is inevitable.  There would be ways to avoid multiple `useQuery` calls in my use case, but they wouldn't be ideal (passing a list of tags to a single query, for example, could end up refetching a bunch of tags that are already cached when just one new tag is added).

Would an API like `React.useConditional` in the following be possible?

```js
import * as React from 'react'
import { useQuery } from '@apollo/react-hooks'

function ConnectedPlot({ tags }) {
  const results = tags.map(tag => React.useConditional(
    tag,
    () => useQuery(metadataQuery, { variables: { tag } })
  ))
  if (results.some(r => r.loading)) return <LoadingBanner />
  const error = results.find(r => r.error)
  if (error) return <ErrorBanner error={error} />

  const metadataByTag = Object.fromEntries(results.map(r => [r.data.MetadataItem.tag, r.data.MetadataItem]))

  return <Plot tags={tags} metadataByTag={metadataByTag} />
}
```

The first argument to `React.useConditional` would be a unique key, just like keys on React elements.

The second argument would be a function that may call any builtin or custom hooks the user likes.  Within that function, the same old rules of hooks would apply: all hook calls must be unconditional and in the same order as last time (for the particular key).  Only calls to `React.useConditional` could be conditional.

I'm assuming it would be possible for React to do bookkeeping before and after it calls the callback to keep track of which hooks it called, and compare the keys from the previous render to the next, performing mounting effects for hooks in keys that were added and unmounting effects for hooks in keys that weren't reused.

**Comment by jedwards1211** [comment]
Here's an example of how there's a desire for dynamic hooks and one workaround: https://unsplash.com/blog/calling-react-hooks-conditionally-dynamically-using-render-props/

Below is my userland workaround for dynamic hooks.  Here are its drawbacks compared to what a builtin `React.useConditional` would theoretically be able to provide:

* You need to declare `const [conditionals, useConditional] = useConditionals()` in your component before doing `useConditional`
* You can't get state from the conditional hooks immediately
* You have make sure `conditionals` gets rendered

```js
/**
 * @prettier
 * @flow
 */

import * as React from 'react'

type UseConditionalFn<K: string, T> = ((key: K, fn: () => T) => ?T) &
  ((key: K, fn: () => T, defaultValue: T) => T)

type UseConditionalProps<K: string, T> = {|
  _key: K,
  fn: () => T,
  setState: (updater: (state: { [K]: T }) => { [K]: T }) => any,
|}

function UseConditional<K: string, T>({
  _key,
  fn,
  setState,
}: UseConditionalProps<K, T>): null {
  const value = fn()
  React.useLayoutEffect(() => {
    setState((state) => ({ ...state, [_key]: value }))
  }, [value])
  React.useEffect(
    () => () => {
      setState((state: { [K]: T }): { [K]: T } => {
        const newState = { ...state }
        delete newState[_key]
        return newState
      })
    },
    []
  )

  return null
}

export default function useConditionals<K: string, T>(): [
  React.Node,
  UseConditionalFn<K, T>
] {
  const [state, setState] = React.useState<{ [K]: T }>({})
  const elements = []

  const useConditional: UseConditionalFn<K, T> = (function (
    key: K,
    fn: () => T,
    defaultValue?: T
  ): ?T {
    elements.push(
      <UseConditional key={key} _key={key} fn={fn} setState={setState} />
    )
    return key in state ? state[key] : defaultValue
  }: any)

  return [elements, useConditional]
}
```

**Comment by pauldraper** [comment]
Yep, something like https://github.com/facebook/react/issues/22286#issuecomment-916602977 is possible today, but the disadvantages, especially not accessing the values synchronously, is a big one.

**Comment by pauldraper** [comment]
still relevant
