### ISSUE TITLE
[react-hooks/exhaustive-deps] option request: ignoreFunctions or ignoreMethods

### ISSUE THREAD

**Issue by rattrayalex** [facebook/react#22305]
### What I would like:

```js
    "react-hooks/exhaustive-deps": ["error", {
      "ignoreFunctions": true
    }]
```
results in:
```js
const history = useHistory();
const log = (x) => console.log(x)

useEffect(() => {
  log(props.foo); // no error
  props.onChange(props.foo); // no error
  history.push(props.foo) // no error
  
  log(props.bar); // error!
}, [props.foo]);


```

### Why:

I typically do not want to re-execute an effect just because a function I call inside the effect changes its identity. Same with an object which is only used to call a method.

I noticed this with react-router's `history.push()` – I want to navigate based on other things, not whether react-router has decided that the `history` object or its `push` method have changed identity (in the abstract, I can't control or predict a library's behavior in this way).

There may be some codebases where it is typical to wish to re-execute an effect when a method's object or function changes its identity, which is why I suspect this should be an option rather than the default behavior.

### Motivating example:

This was the code I was writing which inspired this:

```ts
import { useHistory, useParams } from "react-router";
...
const { subpage } = useParams();
const history = useHistory();

useEffect(() => {
  // I don't want to re-run this effect if `history` changes.
  if (!subpage) {
    history.push(`/my-page/my-default-subpage`);
  }
}, [subpage]);
```

However, I believe that this change would also assuage the desires of participants in this issue: https://github.com/facebook/react/issues/16265

**Comment by ro-savage** [comment]
We'd really like to see this as well - we don't current use `exhaustive-deps` because of this.

Would ignoring functions cause any issues? Or would this be (relatively) safe to do?

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/facebook/react/issues/16265. https://github.com/facebook/react/issues/16265 talks about the general issue. It's not settled that this needs adressing and if it should, it's better to discuss a potential API in a single place.

**Comment by gaearon** [comment]
It would most definitely not be safe to do. A function can close over props or state, so you'd keep "seeing" their old versions.

We have a different solution in mind for this.
