### ISSUE TITLE
found an empty rule set 

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#22301]
this is the file path - packages/react-devtools-shared/src/devtools/views/Settings/SettingsShared.css

going here i found a empty rule set called selector which had nothing inside it and it is not a good practice to keep empty ruleset .

here is the PR link for the same - https://github.com/facebook/react/pull/22298

hope to get a feedback soon!

**Comment by bvaughn** [comment]
I appreciate this issue 🙇🏼 but I don't think this change is necessary. Thank you!

**Comment by Biki-das** [comment]
thanks for the feedback @bvaughn!

**Comment by bvaughn** [comment]
No problem! 😄
