### ISSUE TITLE
Bug: react-dom Portal does not load on re-render with functional component

### ISSUE THREAD

**Issue by swathisainadh** [facebook/react#22300]
React version: 16.8.5

## Steps To Reproduce

1. On initial load, "Portal" loads up a "Modal" as child element when the code is extracted to a functional component
2. On state change, it does not re-render. But does work if the code is inline instead of a functional component

Link to code example:
Works --> successMessage ? <NewModal title={' '} buttons={[{text: 'Close', onClick: goToLicences}]}> <SuccessMessage/> </NewModal> : </>

Does not work --> 
const SuccessModal = () =>  <NewModal title={' '} buttons={[{text: 'Close', onClick: goToLicences}]}> <SuccessMessage/> </NewModal>;
successMessage ? <SuccessModal/> : </>

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
