### ISSUE TITLE
marginBottom gets dropped sometimes

### ISSUE THREAD

**Issue by jussi-kalliokoski** [facebook/react#2231]
In the product I'm currently developing, there's a case where the `marginBottom` value gets dropped by React sometimes. Unfortunately I couldn't manage to reproduce the issue in my attempts at a reduced test case, and I can't post the link to the unreleased product yet, but I thought I'd report it anyway in case someone has additional information to go by.

Basically the case is that in the application, I have components whose style value I set to an object that is something like this:

``` javascript
var style = {
    margin: "0 10px",
    marginBottom: "6px",
};
```

These values are dependant on the screen size, which is listened to with `window.onresize` and then updated with something like `setProps({ screen: { width: screen.width, height: screen.height } });`.

However, what I noticed is that when resizing the screen, more often than not, the components end up not having a vertical margin at all. I know that this is caused by React because I tried logging the value assigned to `style` in `render()` and its sound, and actually the `render()` is not even called when you hit this behavior. Something that makes the problem go away is setting the style as

``` javascript
var style = {
    margin: "0 10px 6px 10px",
};
```

instead, which is what I'm doing for now. The application is running v0.10.0, but I just tried with v0.11.2 and it's still reproducible.

**Comment by azazdeaz** [comment]
Hi, here is a simple use case:
When i set the style of  a React Component which is including a shorthand property and a modifier for that property 
ex. ```{border: 'solid 1px black', borderBottom: 'none'}```
than set a new style  without the modifier
```{border: 'solid 1px black'}```
the new style object wont apply properly. In this case the inline style remains:

```css
border-top-style: solid;
border-right-style: solid;
border-left-style: solid;
border-top-width: 1px;
border-right-width: 1px;
border-left-width: 1px;
border-top-color: black;
border-right-color: black;
border-left-color: black;
```

[codepen example](http://codepen.io/azazdeaz/pen/jEdzmO?editors=001)

**Comment by syranide** [comment]
@azazdeaz `{border: 'solid 1px black', borderBottom: 'none'}` is invalid, you may not set overlapping styles.

**Comment by polyakoff** [comment]
Would be really nice to have overlapping styles working.
I have an HOC footer I would like to pass elements to and place them according to my needs inside. I wrote the following code with react-bootstrap:

```
const Footer = React.createClass({
    render: function() {
        var children = React.Children.map(this.props.children, function(child){
            return React.cloneElement(child, { className :"btn btn-primary", margin : "40" });
        });
        return (
            <div style={style}>
                {children}
            </div>
        );
    }
});
```
And got `className` applied, while `margin` not. Would be convinient from my point to have both working.
