### ISSUE TITLE
Test fail while running yarn test

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#22326]
While running yarn test getting these failing tests-

![react - Visual Studio Code 15-09-2021 11 58 40 PM](https://user-images.githubusercontent.com/72331432/133489177-86d60906-2281-4260-a1a5-1731bb87b321.png)

**Comment by rickhanlonii** [comment]
Tests pass for me - can you send the commands you're running?

**Comment by Jeve-Stobs** [comment]
What node version are you running? I also have issues on v16.9.1.

**Comment by rickhanlonii** [comment]
Passes for me on Node v16.8.1

<img width="1319" alt="Screen Shot 2021-09-15 at 2 54 30 PM" src="https://user-images.githubusercontent.com/2440089/133492701-454f7259-273b-41f6-9d8e-55ac8cb5fde9.png">

**Comment by Jeve-Stobs** [comment]
Downgrading to node v16.8.0 fixed it for me.

**Comment by rickhanlonii** [comment]
What's the exact test command you're running?

**Comment by Biki-das** [comment]
closing this as i forgot to pull and update the file , sorry!
