### ISSUE TITLE
Bug: Warning: Cannot update a component (`Parent`) while rendering a different component (`Child`)

### ISSUE THREAD

**Issue by aliveli186** [facebook/react#22335]
I'm receiving that error when the page is being rendered without even clicking the link to trigger the state change.
Here is the simplified code:

```
import React, { useState } from "react"

export default function Parent() {
    const [itemId, setItemId] = useState(0);

    return (
        <Child setItemId={setItemId} />
    );
}

export function Child({ setItemId }) {
    return (
        <a onClick={setItemId(1)} />
    );
}

```

**Comment by eps1lon** [comment]
`<a onClick={setItemId(1)} />` this means that you will call `setItemId` when rendering which triggers the warning. You probably want to write 

```diff
 export function Child({ setItemId }) {
     return (
-       <a onClick={setItemId(1)} />
+       <a onClick={() => setItemId(1)} />
     );
  }
```

**Comment by aliveli186** [comment]
> `<a onClick={setItemId(1)} />` this means that you will call `setItemId` when rendering which triggers the warning. You probably want to write
> 
> ```diff
>  export function Child({ setItemId }) {
>      return (
> -       <a onClick={setItemId(1)} />
> +       <a onClick={() => setItemId(1)} />
>      );
>   }
> ```

Yes, I was just going to write wrapping it inside a function solved the issue.
