### ISSUE TITLE
Bug: I was contributing to selenium ide and I got problem with input. If I complete input from autocomplete suggestions. State update did'nt reflect. Morever it throws exception " expected keyboard error but got mouse event'

### ISSUE THREAD

**Issue by aliwasif177** [facebook/react#22349]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by bvaughn** [comment]
This isn't an actionable bug report. Please actually fill in the information the bug template asks for , especially **Steps to reproduce** the bug.
