### ISSUE TITLE
DevTools: Test named hooks behavior with React Native

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#22370]
Follow up to #22320

Seems like we tested standalone named hooks support for Safari but not React Native. We should confirm this works in RN as well. (We should probably also update the DevTools backend in RN.)

**Comment by Biki-das** [comment]
a bit off topic @bvaughn  can you help me on a issue , what the best way to keep in sync with the main react repo , i follow the upstream method and it works fine , all tests etc run fine in local machine and PR also gets pushed easily but circle ci build always fails sometime its linc or sandbox anything you want to suggest

**Comment by jstejada** [comment]
verified that hook names works against RN after the changes in #22320

![image](https://user-images.githubusercontent.com/1271509/134215882-7d1613fe-31fb-4077-9adf-d76b87aeb17e.png)
