### ISSUE TITLE
Support array of objects in style property

### ISSUE THREAD

**Issue by jacobrask** [facebook/react#2239]
As proposed in [React Future](https://github.com/reactjs/react-future/blob/master/04%20-%20Layout/Inline%20Style%20Extension.md), it would be nice to support a list of style objects in the style property. The objects would be automatically merged (in order, with the last object overriding the previous one).

```
var boxStyle = {
  padding: 10,
  background: "hotpink"
};
var bixBoxStyle = {
  margin: 10,
  width: 300
};

<div style={boxStyle} />
<div style={[boxStyle, bigBoxStyle]} />
<div style={[boxStyle, bigBoxStyle, {background: "navy"}]} />
```

**Comment by phtn** [comment]
`<div style={ Object.assign( {}, boxStyle, bigBoxStyle, {background: "navy"} ) }>`

this  should merge declared **styles** as well as specific in-line style like **background**.
`background`  in **boxStyle** will be overwritten in this order of `Object`  assignment.

**Comment by QuantumInformation** [comment]
What is the preferred way to do it today?

**Comment by jsu93** [comment]
@QuantumInformation  https://github.com/jsu93/babel-plugin-styles

**Comment by agustind** [comment]
You can use the spread operator

style={{...styles.base, ...styles.extra}}
