### ISSUE TITLE
React 18  lets React.memo save displayName?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [facebook/react#22436]
Now

```js
const User = React.memo(function User (){
  return null
})

User.displayName // undefined
```

Need

```js
const User = React.memo(function User (){
  return null
})

User.displayName // User
```

**Comment by bvaughn** [comment]
`fn.displayName` is a [non-standard property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName). I believe you're mistaking it for `fn.name`:

```js
function User (){
  return null
}
User.name // "User"
```

**Comment by MaxmaxmaximusAWS** [comment]
no i not,

i use React.memo and i brake names in DevTools  -- its React Team issue, no?

**Comment by MaxmaxmaximusAWS** [comment]
@bvaughn everything you said is wrong, you should better feel people's thoughts

**Comment by bvaughn** [comment]
Hey buddy. There's no reason to get so aggressive on a GitHub issue.

You are mistaken about `displayName` being an automatic property of Functions. That's [`Function.name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name).

If you "need" the behavior you described, _assign the value_ [like the docs show](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging).
```js
const User = React.memo(function User (){
  return null
})
User.displayName = "User";
```

**Comment by MaxmaxmaximusAWS** [comment]
@bvaughn I am a TC39 member and have been studying Javascript for over 16 years. React.memo not saving `displayName`. What does Function.prototype.name have to do with it? Buddy

**Comment by bvaughn** [comment]
Whatever you say.

Regardless, you did not do a good job explaining yourself in your original post. The "bug" you reported was this:
```js
const User = React.memo(function User (){
  return null
})

User.displayName // undefined
```

No where in that "bug" do you assign a value to `User.displayName`, so it is expected to be `undefined`.

Looking at your more recent example:
```js
function User {}
User.displayName = 'Cat'

const UserMemo = React.memo(User);
```

The value returned by `React.memo` is not a function. It's an object with a `type` and `compare` property (which you can see by inspecting the returned value). React DevTools (and React component stacks) will respect the `User.displayName` property though and show "Cat" in DevTools and error messages.

---

p.s. I don't appreciate the way you've been communicating on this issue. The people maintaining React are here to **help** you. If you can't communicate with respect, you're going to be banned.

**Comment by MaxmaxmaximusAWS** [comment]
Ok, Buddy.
