### ISSUE TITLE
The source code of v16.14.0 is inconsistent with the release package.

### ISSUE THREAD

**Issue by amorphousDj** [facebook/react#22432]
I downloaded and compiled the source code of v16.14.0. It is found that the compiled code is inconsistent with the code of the release package. Some bugs [#18539](https://github.com/facebook/react/pull/18539) that were only fixed in version 17.0.0 have been fixed in my compiled code. Of course, it has not been fixed in the v16.14.0 release package. I checked the merge record of these repair codes, and it has indeed been merged into the v16.14.0 tag.

 I want to know which commit record corresponds to the actual source code of the v16.14.0 release package.
@gaearon Please help me.

React version: 16.14.0

**Comment by bvaughn** [comment]
> I downloaded and compiled the source code of v16.14.0.

How did you determine which source revision to download?

According to the [build info metadata](https://unpkg.com/browse/react@16.14.0/build-info.json), that release was prepared from da834083c.

**Comment by amorphousDj** [comment]
> > I downloaded and compiled the source code of v16.14.0.
> 
> How did you determine which source revision to download?
> 
> According to the [build info metadata](https://unpkg.com/browse/react@16.14.0/build-info.json), that release was prepared from [da83408](https://github.com/facebook/react/commit/da834083cccb6ef942f701c6b6cecc78213196a8).

I downloaded the source code from release log.

**Comment by bvaughn** [comment]
That's interesting. According to our build script metadata, [16.3.1](https://unpkg.com/react@16.13.1/build-info.json) and [16.14.0](https://unpkg.com/react@16.14.0/build-info.json) were both built and release from the same source.

My guess is that someone (@gaearon? @acdlite?) did a manual release of 16.14.0 on top of 16.13.1. Looking at [the change log](https://github.com/facebook/react/blob/main/CHANGELOG.md#16140-october-14-2020) it seems like the only purpose of this release was to support the [new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) added by @lunaruan in #18299.

**Comment by bvaughn** [comment]
The [tags page](https://github.com/facebook/react/tags) shows 16.14.0 as 4337c1c, but then it also shows that for 15.7.0 which was also manually released for the new JSX transform.

I think the issue here is likely just that we did a one-off release to add support for the new JSX transform to older 15 and 16 stable releases (rather than using our normal release script/process).

I'm going to close this issue. I don't think there's anything we can do about it at this point. This isn't worth the churn that unpublishing the release from NPM would cause. I suppose we could fix the NPM tag (if someone knew which commit to point to, I do not).

**Comment by amorphousDj** [comment]
> > I downloaded and compiled the source code of v16.14.0.
> 
> How did you determine which source revision to download?
> 
> According to the [build info metadata](https://unpkg.com/browse/react@16.14.0/build-info.json), that release was prepared from [da83408](https://github.com/facebook/react/commit/da834083cccb6ef942f701c6b6cecc78213196a8).


Thanks for your reply. I'm sure [da83408](https://github.com/facebook/react/commit/da834083cccb6ef942f701c6b6cecc78213196a8) is the source code of v16.14.0. I compiled the source code without setting RELEASE_CHANNEL. After I set it equal to stable, they became consistent.

**Comment by amorphousDj** [comment]
> The [tags page](https://github.com/facebook/react/tags) shows 16.14.0 as [4337c1c](https://github.com/facebook/react/commit/4337c1c00609ec8d7ae399c736e9d37bb159fac5), but then it also shows that for 15.7.0 which was also manually released for the new JSX transform.
> 
> I think the issue here is likely just that we did a one-off release to add support for the new JSX transform to older 15 and 16 stable releases (rather than using our normal release script/process).
> 
> I'm going to close this issue. I don't think there's anything we can do about it at this point. This isn't worth the churn that unpublishing the release from NPM would cause. I suppose we could fix the NPM tag (if someone knew which commit to point to, I do not).

I'm sure [da83408](https://github.com/facebook/react/commit/da834083cccb6ef942f701c6b6cecc78213196a8) commit point to the NPM tag. Please fix it.

**Comment by bvaughn** [comment]
I'm going to lock this issue.
