### ISSUE TITLE
onChange not firing with virtual keyboard

### ISSUE THREAD

**Issue by StevePotter** [facebook/react#2244]
Hey all, writing a kiosk type app in Linux.  It's for a touch device and I needed a virtual keyboard.  I found a great Chrome extension at https://chrome.google.com/webstore/detail/virtual-keyboard/pflmllfnnabikmfkkaddkoolinlfninn?hl=en.

The extension works fine but React's onChange doesn't recognize it.  The extension is JS-based and it dispatches keyDown, keyUp, keyPress, and change events itself.  And naturally it updates the element's value.  Why wouldn't this work?  

Thanks!

**Comment by mdressman** [comment]
This post just saved me. I was also trying to manually fire `change` events.  Switched to `input` event type and success!  Just wanted to say thanks.

**Comment by saptarshi-bhattacharjee** [comment]
> This post just saved me. I was also trying to manually fire `change` events. Switched to `input` event type and success! Just wanted to say thanks.

Please share the solution. Facing same issue.

**Comment by saptarshi-bhattacharjee** [comment]
> Thanks for the reply. I updated it to dispatch the input event and it worked beautifully. I owe you a hug.

How to dispatch input event? can you please share?

**Comment by saptarshi-bhattacharjee** [comment]
> Thanks for the reply. I updated it to dispatch the input event and it worked beautifully. I owe you a hug.

How to dispatch input event? can you please share?
