### ISSUE TITLE
API Change: ReactComponent.mount/unmount

### ISSUE THREAD

**Issue by zpao** [facebook/react#2245]
Currently they are `ReactComponent.mountComponent/unmountComponent`, which is way verbose considering these are instance methods of a component and don't take any arguments relating to some other component. `receiveComponent` is related but different. It might make sense to change that to `receiveNextComponent`, or even just `receiveNext`. I think these are all internal methods so it's not a huge deal.

cc @jordwalke @leebyron @sebmarkbage 

Note: if you're interested in working on this, talk to us first. There are probably some caveats and edge cases to consider before jumping right in.

**Comment by gaearon** [comment]
Fiber.
