### ISSUE TITLE
[eslint]: useEffect eslint rule not provided to warn/error on missing dependency array

### ISSUE THREAD

**Issue by scottdickerson** [facebook/react#22462]
We had a very nasty bug where we accidentally forgot a dependency array argument in our useEffect so it fires every render.
(just a typo)

I find it strange that useMemo has a rule to warn on this:
```
React Hook useMemo does nothing when called with only one argument. Did you forget to pass an array of dependencies?eslintreact-hooks/exhaustive-deps
(alias) useMemo<void>(factory: () => void, deps: React.DependencyList): void
import useMemo
useMemo will only recompute the memoized value when one of the deps has changed.

Usage note: if calling useMemo with a referentially stable function, also give it as the input in the second argument.

function expensive () { ... }

function Component () {
  const expensiveResult = useMemo(expensive, [expensive])
  return ...
}
```

but there's no configurable rule on the useEffect side.  Isn't it probably true that 99% of the time you don't want to fire useEffect on every render?

Here's a repro scenario (two useEffect fires in the console.log instead of 1, but for us it's infinite due to the fetch causing a prop to change on this component):
https://codesandbox.io/s/nice-chaum-9lf1c?file=/src/App.js

**Comment by bvaughn** [comment]
> but there's no configurable rule on the useEffect side.

Running an effect without any dependencies is a valid use case that we intentionally support.

Using a memoization method (`useMemo` or something else) without dependencies _is not_ a valid use case.

**Comment by scottdickerson** [comment]
There are also many valid cases to run useEffect with a limited list of dependencies but the eslint rule gives a configurable warning there.

**Comment by scottdickerson** [comment]
Does anyone out there have a custom eslint rule to enforce this?

**Comment by bvaughn** [comment]
> There are also many valid cases to run useEffect with a limited list of dependencies

What do you mean by "limited list? Do you mean only specifying _some_ of the dependencies?

Yeah, I've heard other people make that argument. I think you can shoot yourself in the foot by leaving out dependencies, but I also understand where you're coming from. To me, that seems like a pretty different discussion from the one you reported here though.

> Does anyone out there have a custom eslint rule to enforce this?

Don't know. I don't keep up with 3rd part ESLint rules.
