### ISSUE TITLE
Bug: adding `loading="lazy"` to images causes memory leak

### ISSUE THREAD

**Issue by phil-r** [facebook/react#22471]
Adding `<img loading="lazy"/>` that never gets into view and then deleting it causes memory leaks

React version: 17.0.2 (and 18)

## Steps To Reproduce

1. Visit https://531j3.csb.app/ in Chrome (or https://e4h4zi.csb.app/ for react 18 version)
2. Open dev tools with performance monitor(enable DOM Nodes and JS event listener tracking) and memory tab
	

	  <details>
	  <summary>Dev tools screenshot</summary>
	  
	  <img width="1255" alt="image" src="https://user-images.githubusercontent.com/577316/135452855-366b6b9f-f39f-44ce-a285-747d4e025456.png">
	  
	  
	  </details>

3. Trigger garbage collection (trash icon in upper left corner)
4. Observe the number of Dom nodes and JS event listeners (in my case it's 221 and 170 respectively)
5. Click `Add 100 lazy images` 3 times with a small delay in between (so total 300 images)
6. **Do not scroll down** (it will "fix" the problem)
7. Click `Delete all images`
8. Trigger garbage collection
9. Observe DOM nodes and JS event listeners numbers are now higher (in my case it's 421 and 570 respectively)
	

	  <details>
	  <summary>Dev tools screenshot</summary>
	  
	  <img width="204" alt="image" src="https://user-images.githubusercontent.com/577316/135453507-b6d77879-2f6a-4c3f-98a3-d41c6f838ec0.png">
	  
	  
	  </details>

10. Can be repeated again from step 5 to increase the numbers even more

Link to code example: 

- [React 17](https://codesandbox.io/s/lazy-image-investigation-531j3?file=/src/App.js)
- [React 18](https://codesandbox.io/s/lazy-image-investigation-react-18-e4h4zi?file=/src/App.js)

## The current behavior

Images with `loading="lazy"` cause memory leaks

## The expected behavior

Images with `loading="lazy"` shouldn't cause memory leaks

**Comment by andrelmchaves** [comment]
@phil-r Could you confirm this is still and issue?

**Comment by phil-r** [comment]
@andrelmchaves yea, just updated my example to react 18 and tested again - it's still happening

**Comment by phil-r** [comment]
Hey @gaearon, no but I can try and see if it happens without React.

**Comment by gaearon** [comment]
We should probably close this and report to Chrome (if it's a bug).
