### ISSUE TITLE
Minified version broken in IE8

### ISSUE THREAD

**Issue by cascadian** [facebook/react#2247]
[line 66 of setInnerHTML](https://github.com/facebook/react/blob/716742dcd7fc7521737c94e7f0ed9d876658a6b7/src/browser/ui/dom/setInnerHTML.js#L66) `node.innerHTML = '\uFEFF' + html; ` is minified as `e.innerHTML = "" + t;` in react.min.js and react-with-addons.min.js. An exception is thrown on on [line 71](https://github.com/facebook/react/blob/716742dcd7fc7521737c94e7f0ed9d876658a6b7/src/browser/ui/dom/setInnerHTML.js#L71) because `textNode.data` is `undefined`.

Here's a repro that's modified from the basic example

``` js
    <script src="../../build/react.min.js"></script>
    <script>
      var Container = React.createClass({
        render: function(){
          return React.DOM.div(null, this.props.children);
        }
      });
      var ExampleApplication = React.createClass({
        render: function() {
          var elapsed = Math.round(this.props.elapsed  / 100);
          var seconds = elapsed / 10 + (elapsed % 10 ? '' : '.0' );
          var message =
            'React has been successfully running for ' + seconds + ' seconds.';

          return React.DOM.p(null, message);
        }
      });
        React.renderComponent(
          Container(null,
            ExampleApplication({elapsed: new Date().getTime()}),
          document.getElementById('container')
        ));

    </script>
```

**Comment by syranide** [comment]
Ping, this is resolved in uglifyjs now at least. React should go the way of #2340 if you ask me though.

**Comment by markplindsay** [comment]
This issue, although easily fixed by @syranide's DIY patch, still exists in http://fb.me/react-0.13.1.min.js and any other FB-packaged react.min.js. :| Sorry to be a nag. In the end this is all IE8's fault anyway.

**Comment by syranide** [comment]
@markplindsay I haven't verified, but this was fixed upstream in UglifyJS some time ago so it *should* have solved itself... @zpao is it possible you're running the build process with an older UglifyJS?

**Comment by markplindsay** [comment]
@syranide, thanks for your followup. I am looking at a react-0.13.1.min.js I wgot from http://fb.me/react-0.13.1.min.js. Changing `e.innerHTML=""` to `e.innerHTML="!"` by adding the `!` at Line 15, Column 17852 still fixes the issue.

**Comment by syranide** [comment]
@zpao Ah, apparently we've locked the uglifyjs dependency to `2.4.0` whereas the fix is in `2.4.17` (https://github.com/mishoo/UglifyJS2/commit/24bc09b79bf9ca3a09eef4f536e7637568f7097a). There's no reason not to update the dependency right?

**Comment by mockdeep** [comment]
We just got bit by this issue. Please update uglify!

**Comment by spicyj** [comment]
AFAIK no reason not to upgrade. @syranide want to send a PR to the 0.13-stable branch? (I forget how to update shrinkwrap files properly though…)

**Comment by zpao** [comment]
Send to master and I'll pull it in with other things

cheers,
Paul

On Apr 10, 2015, at 12:26 PM, Ben Alpert <notifications@github.com<mailto:notifications@github.com>> wrote:


AFAIK no reason not to upgrade. @syranide<https://github.com/syranide> want to send a PR to the 0.13-stable branch? (I forget how to update shrinkwrap files properly though…)

**Comment by zpao** [comment]
Just confirmed that this is correct in the minified build now. We'll ship 0.13.2 this week with the fix.

**Comment by ledowong** [comment]
will 0.12.x get rebuild too?

**Comment by spicyj** [comment]
@ledowong No, we don't generally do point releases except for the newest minor release except in the case of a security vulnerability. You can patch in the change locally and make your own build of 0.12 if you're unable to upgrade to 0.13.
