### ISSUE TITLE
Detect and warn if multiple copies of React DevTools are installed

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#22486]
If you have more than one copy of React DevTools installed and enabled (e.g. the version in the Chrome store and a locally built version) they can interfere with each other.

DevTools should detect this case and warn by showing a dialog in the DevTools UI and/or by logging to the console.

Note that we _should not warn_ if a related tool like Fast Refresh is present, only another copy of DevTools.

**Comment by bvaughn** [comment]
@jstejada This is all yours!

**Comment by jstejada** [comment]
@bvaughn cool! i'll be working on this today + next steps
