### ISSUE TITLE
Bug: Lint React Hook "useState" cannot be called in a class component

### ISSUE THREAD

**Issue by djmisterjon** [facebook/react#22485]
React version:

## Steps To Reproduce
Englobe code in a static class make rule bug !
Actually rule detect React in class, but it not true ! 
```tsx
interface PanelProps {}
class DOMAINE {
	static Panel : FC<PanelProps> = (props)=> {
		const { children } = props;
		const state = useState<unknown>(null);
	
		useEffect(() => {});
		return (
			<Bloc className='Panel' Flex Grow>
				{children}
			</Bloc>
		);
	};
	static a = class ACTIVITY {
		static Panel : VFC<PanelProps> = (props)=> {
			const {  } = props;
			const state = useState<unknown>(null);
		
			useEffect(() => {});
			return (
				<Bloc className='Panel' Flex Grow>
					
				</Bloc>
			);
		};
	}
}

```

![image](https://user-images.githubusercontent.com/24865815/135672118-097b4751-e6bd-4922-96ed-6b6193609c2c.png)

```json
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "plugin:react/recommended",
        "plugin:react-hooks/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
        "array-bracket-spacing": "warn",
        "multiline-comment-style": "warn",
        "no-console": "warn",
        "comma-dangle": "off",
        "no-var": "warn",
        "no-duplicate-imports": "error"
    }
}
```
Link to code example: https://codesandbox.io/s/currying-https-9v064?file=/src/App.js

## The current behavior
Rule think we use hooks inside a react Class ! 

## The expected behavior
Rule should not emit error about hooks for this structure

**Comment by bvaughn** [comment]
This seems like a pretty edge case thing to do. Why not just declare the property outside of the class?

Rather than...
```js
class Example {
  Panel = (props) => {
    const { children } = props;
    const state = useState(null);

    return <Bloc className="Panel">{children}</Bloc>;
  };
}
```
Why not...
```js
const Panel = (props) => {
  const { children } = props;
  const state = useState(null);

  return <Bloc className="Panel">{children}</Bloc>;
};
class Example {
  static Panel = Panel;
}

```

**Comment by djmisterjon** [comment]
hum , it's will be a bit complicated to ask why or explained why.
A bit like asking or debate on why you prefer star screws rather than rectangle or triangles 🙄
I will avoid describing a book here, especially since my English is not developed enough to express my deep thoughts 
but in summary for the example you give 


losing mono collapse aggregation in vscode (domain like)
![image](https://user-images.githubusercontent.com/24865815/135689327-d7b01feb-bd85-48b6-94ac-d50381e74fc7.png)
or if we want use methods instead ? example to explore something with decorators, proxi, abstract propstype on prototype like:
```tsx
 export function ClassWithRenderer(cls: Function) {
	cls.prototype.$Renderer = proxi(cls.prototype.$Renderer);
	cls.prototype.$Renderer.displayName = cls.name;
}
 @DecorateClassWithProxiMethods
export class NotAReactClass<T> extends NotAReactClassAbstract<T> {
   
   /** ReactFunction with proxi */
   public $Renderer(props) {
		const {} = props;
		return (<div ></div>);
	}
}

```


But it was mostly to just experiment and explore something, and I ended up with this strange error message, which I thought was important to point out because it the message lie. :)

**Comment by gaearon** [comment]
The message is not a lie — while this sort of works, it's not a supported pattern, and you may end up with strange behavior if you mix function with class-like paradigms (where it's encouraged to read from fields, etc). We do not recommend it, though we can't really stop you.

**Comment by djmisterjon** [comment]
> The message is not a lie — while this sort of works, it's not a supported pattern, and you may end up with strange behavior if you mix function with class-like paradigms (where it's encouraged to read from fields, etc). We do not recommend it, though we can't really stop you.

i understand you point, but in this case, this rule restrict a lot of valid patterns (ES6 Proxi and class decorator) ! 
so a little patch solve my issue ! 

![image](https://user-images.githubusercontent.com/24865815/139951729-8ecc5baf-7f95-4c87-8c15-5ee938014c25.png)

**Comment by Sarkar44** [comment]
solve my issues

**Comment by djmisterjon** [comment]
> solve my issues
the only issue is each time we update or share libs , its pain to replace ! 
but for people who are little lost , here the dirty fix.

In `eslint-plugin-react-hooks.development.js`
![image](https://user-images.githubusercontent.com/24865815/144752514-2cc4c7b3-ed62-4ac7-8adc-9505ea8e11a3.png)

```ts
             // Special case when we think there might be an early return.
                      if ( !cycled && pathsFromStartToEnd !== allPathsFromStartToEnd )
                      {
                        var message = "React Hook \"" + context.getSource( hook ) + "\" is called " + 'conditionally. React Hooks must be called in the exact ' + 'same order in every component render.' + ( possiblyHasEarlyReturn ? ' Did you accidentally call a React Hook after an' + ' early return?' : '' )
                        context.report( {
                          node: hook,
                          message: message
                        } )
                      }
```

You lose the rule if you perform a `class A extends React.Component` where you need remember
But it allow you pattern like 
```ts
export function Renderable( cls: FunctionV, emoji: string = '' ) {
	if( 'Renderer' in cls ) {
		cls.Renderer = proxi( cls.Renderer );
		cls.Renderer.displayName = `Static_${cls.name}${emoji}`;
	}

	if( cls.prototype.Renderer ){
		cls.prototype.Renderer = proxi( cls.prototype.Renderer );
		cls.prototype.Renderer.displayName = emoji + cls.name;
	}
}

@Renderable // decorator pattern for proxify
export abstract class Scene extends Entity {
	constructor() {
		super();
	}

	static Renderer( props: { instance: Scene|undefined } ) {
		const { instance } = props;
		if( !instance ) return null;
		return <instance.Renderer instance={ instance } />;
	}
	abstract Renderer( props: { instance: Scene } ): JSX.Element
}
```
