### ISSUE TITLE
Bug: OpenLayer events problem with React 17

### ISSUE THREAD

**Issue by shayantabrizi** [facebook/react#22490]
I want to put react components as overlays on top of OpenLayers maps. The events on the components seem to be problematic after upgrade to React 17.0.2 (from 16.14.0). For a reproduction see [this](https://codesandbox.io/s/react-openlayers-jwghd?file=/index.js). By clicking, on the red div an alert is displayed on React 16.14.0. But, after upgrading React to 17.0.2, the alert is not displayed anymore.

I reported it to OpenLayers and I received this answer ([link](https://github.com/openlayers/openlayers/issues/12848#issuecomment-932742503)):

> I presume it is a React parsing issue as it works when the ReactDOM call is replaced with
```
dom.innerHTML = '<div id="test">' +
'  <div' +
'    onClick=\'' +
'      alert("clicked")' +
'    \'' +
'   style="background-color: #FF0000"' +
'  >' +
'    Click here' +
'  </div>' +
'</div>';
```

**Comment by Manuelandro** [comment]
i replaced the the dependency to 17.0.2 and I can see the alert.

**Comment by gaearon** [comment]
>I presume it is a React parsing issue as it works when the ReactDOM call is replaced with

React does not do parsing. What React does is event delegation. Events before 17 were delegated to the document node. Now they're delegated to the root node (the one you call `ReactDOM.render` with). See https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation for an explanation. I think this is likely the issue, and if you figure out what goes wrong there, you should be able to fix it.

I looked at the example but I don't know why the code is structured this way (for example, the purpose of `convertToClick` is unclear to me). So it's hard to comment on it.

**Comment by gaearon** [comment]
Here is an equivalent example that does not use React, but also does not work.
https://codesandbox.io/s/react-openlayers-forked-gsui1?file=/index.js

The thing I changed is to set up the click listener by `addEventListener` on the root element. I think this should be enough to pass it back to OpenLayer and see if there's some conflict in the approaches.
