### ISSUE TITLE
Better SVG Support for namespaced attributes

### ISSUE THREAD

**Issue by ledbruno** [facebook/react#2250]
We are trying to use React for a SVG document. But we are facing problems for namespaced attributes.

For instance, this element cant be constructed with React:
<code>

	<image xlink:href="firefox.jpg" x="0" y="0" height="50px" width="50px"/>

</code>

We cant build a JSX for a xmlns:xlink attribute. Is there any way to solve this?

**Comment by bobby** [comment]
+1 on this.  React could be a really great platform for doing SVG, but it's hard to use SVG to full effect without xlink:href and friends.

**Comment by dujuanxian** [comment]
Hi @edmspjp I had the same issue, but it seems add dangerouslySetInnerHTML to <svg> tag still has the same problem. And take the whole svg tag as dangerouslySetInnerHTML attr to its parent tag works for me. I am not sure if you met the problem before.
```html
var svgTag='<svg><image..></svg>';

<div dangerouslySetInnerHTML={__html: svgTag} />
```

**Comment by lennerd** [comment]
Any updates on or further plans for supporting SVG namespaced elements and attributes?

**Comment by willhackett** [comment]
Seems it's still necessary to implement SVGs using `dangerouslySetInnerHTML`.

**Comment by lennerd** [comment]
I can recommend to use a combination of d3 and react. When ever I need to use namespaced attributes I use d3 in the `componentDidMount` method.

**Comment by janaspage** [comment]
+1 for this request. I need React to render an inline SVG that has an image inside a clipping path, and it's getting hung on the `xmlns:xlink="http://www.w3.org/1999/xlink"` attr in the `<svg>` tag.

**Comment by janaspage** [comment]
@dujuanxian's workaround helped me get through this, provided double (not single) braces are used, of course:
```
var svgString = '<svg /* React-unfriendly code here... */ </svg>';
<div dangerouslySetInnerHTML={{ __html: svgString }} />
```

**Comment by lennerd** [comment]
Just to show an example using d3 for the non-react-svg-stuff:

https://github.com/FH-Potsdam/shifted-maps/blob/master/app/client/components/place-map.js#L21-L40

I used d3 here, because React is not able to set `href` attribute of `image` tags.

**Comment by Nukesor** [comment]
+1  Any updates on this? Thx for the workaround. Hope it'll work until this is fixed.

**Comment by edmspjp** [comment]
See in How SVG Fragment Identifiers Work
<https://css-tricks.com/svg-fragment-identifiers-work/> a different technic.

2015-07-29 23:12 GMT+01:00 Lennart Hildebrandt <notifications@github.com>:

> Just to show an example using d3 for the non-react-svg-stuff:
>
>
> https://github.com/FH-Potsdam/shifted-maps/blob/master/app/client/components/place-map.js#L21-L40
>
> I used d3 here, because React is not able to set href attribute of image
> tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react/issues/2250#issuecomment-126111526>.
>



-- 
Paulo Jorge Dias
: à procura do erro certo
: looking for the right error

**Comment by edvinerikson** [comment]
In the `master` branch I managed to get namespaced attributes to work by using camelCase.
`<svg xlinkHref="http://i.imgur.com/w7GCRPb.png" />` renders to `<svg xlink:href="http://i.imgur.com/w7GCRPb.png" />`

**Comment by lennerd** [comment]
Do you also get the proper namespace attribute for the namespace itself?

**Comment by edvinerikson** [comment]
Not quite sure I understand what you mean. Can you give me an explanation/example?

**Comment by lennerd** [comment]
To be able to get links working, you also need an attribute for the namespace itself.

````html
<svg width="800" height="600">
  <a xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://www.github.com/"><!-- ... --></a>
</svg>
````

Does React handle this in your example?

**Comment by edvinerikson** [comment]
No, it does only pass `xlink:href` to the DOM node.

**Comment by spicyj** [comment]
@lennerd My understanding is that the xmlns:xlink is not required in HTML.

**Comment by edvinerikson** [comment]
After looking through the [SVG config](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/SVGDOMPropertyConfig.js#L19) and some tests it seems like the namespace is passed to the DOM node through the `setAttributeNS` method. 

[SVGDOMPropertyConfig.js](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/SVGDOMPropertyConfig.js#L19) 
[DOMPropertyOperations-test.js](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/__tests__/DOMPropertyOperations-test.js#L224)

**Comment by lennerd** [comment]
Sounds promising. Would be great to remove the d3 dependency.

**Comment by spicyj** [comment]
Yes, as `xlinkHref` this should work in the upcoming 0.14 release.

**Comment by mijamo** [comment]
xmlns:xlink is not required in HTML only if all the SVG is inline, but it is necessary for some tricky case: In my case, I need to have an image inside defs, to be used then by <use /> and to do that xmlns:xlink is apparently necessary.

**Comment by greypants** [comment]
Confirming that `xlinkHref` does work in the `0.14.x` releases.

**Comment by QuietOmen** [comment]
I'm still getting this error, even when using react 0.14.x or the newer react 15.0.2. I'm not sure if I'm just missing something else that needs to be updated. I'm writing a library so I'm only using react, not react-dom...I'm not sure if it's babel or something else.

**Comment by zpao** [comment]
@QuietOmen you want `<use xlinkHref=` not `<use xlink:href=`

**Comment by QuietOmen** [comment]
@zpao thanks, for some reason I missed that commented above, so thanks for repeating it.

**Comment by kevinSuttle** [comment]
Apologies if I missed this somewhere, but what about styling SVG inline? 

```svg
<style type="text/css" >
      
      <![CDATA[
       circle {
         stroke: #006600;
         fill:   #cc0000;
    }

      ]]>
    </style>
```

**Comment by zpao** [comment]
`<style>` needs to use `dangerouslySetInnerHTML` (and you probably always needed to if you were putting them inline).

```js
<style type="text/css" dangerouslySetInnerHTML={{__html: `
  <![CDATA[
    circle {
      stroke: #006600;
      fill:   #cc0000;
    }
  ]]>
`}}/>
```

**Comment by kevinSuttle** [comment]
@zpao But then it's only static, though, right? Like, you can't eval props in there? 

e.g. 
```
stroke: `${props.color}`
stroke: {props.color}
```

**Comment by gaearon** [comment]
@kevinSuttle 

What you pass is just a string. You can generate the string dynamically—either with template literals or good ol’ concatenation.

```js
<style type="text/css" dangerouslySetInnerHTML={{__html: `
  <![CDATA[
    circle {
      stroke: ${props.color};
      fill:   #cc0000;
    }
  ]]>
`}}/>
```

should work fine.

**Comment by Aweary** [comment]
Here's a JSFiddle with a working example: https://jsfiddle.net/yp0q6okn/

**Comment by saulwolfdev** [comment]
A mi me funciono reemplazando **xmlns:xlink** por **xlinkHref** y elimine un atributo mas **xml:space="preserve"** con eso me ando perfecto  la referencia lo tome de un pagina 

https://itnext.io/using-react-for-xml-svg-470792625278

**Comment by PachVerb** [comment]
> @dujuanxian's workaround helped me get through this, provided double (not single) braces are used, of course:
> 
> ```
> var svgString = '<svg /* React-unfriendly code here... */ </svg>';
> <div dangerouslySetInnerHTML={{ __html: svgString }} />
> ```

it's work for me
