### ISSUE TITLE
`useEffect` can be synchronous?

### ISSUE THREAD

**Issue by alexreardon** [facebook/react#22506]
Hi legends,

My mental model of `useEffect` is that schedules an asynchronous task to be executed after rendering

> Unlike `componentDidMount` or `componentDidUpdate`, effects scheduled with `useEffect` don’t block the browser from updating the screen. This makes your app feel more responsive. The majority of effects don’t need to happen synchronously. In the uncommon cases where they do (such as measuring the layout), there is a separate useLayoutEffect Hook with an API identical to useEffect.
> → https://reactjs.org/docs/hooks-effect.html
>
> _Implies that `useLayoutEffect` is **synchronous** and `useEffect` is **asynchronous**_

This view seems to be shared amongst a number of popular writings on the topic:

- https://kentcdodds.com/blog/useeffect-vs-uselayouteffect/ by @kentcdodds
- https://blog.logrocket.com/guide-to-react-useeffect-hook/ by @doppelmutzi
- A few others I found on Google too

I have recently discovered two use cases where effects created with `useEffect` are *synchronous*

- [setting react `state` inside of a non-react event listener](https://codesandbox.io/s/setting-state-inside-of-a-non-react-event-listener-08ors?file=/src/App.tsx)
- [setting react `state` inside of a `ref` callback](https://codesandbox.io/s/useeffect-and-event-timing-refs-in-state-5tys3?file=/src/App.tsx)

Here is the stack during a flushed effect from the first example:

<img width="522" alt="Screen Shot 2021-10-05 at 3 30 24 pm" src="https://user-images.githubusercontent.com/2182637/135964455-81f15a30-a094-467f-a663-5654d751cc64.png">

Having effects *sometimes* be synchronous is usually fine for most effects. However, there can be cases where having an effect running synchronously can be problematic. This recently caused a bug for a project I work on.

In an effect schedule with `useEffect`, we were adding a `'click'` event listener to the `window` in the **↑ bubble phase** after some `state` changed. Because the effect was flushed synchronously, the new bubble phase event listener on the `window` picked up the original `'click'` event (which got picked up by react early on the event path)

Tested `react` + `react-dom` versions:

- `16.14.0`
- `17.0.2`

I tried wrapping the `setState` in a `unstable_batchedUpdates` but that did not impact the flushing of the effect.

### React 18

version: `18.0.0-alpha-f2c381131-20211004`

#### First example: "setting react `state` inside of a non-react event listener"

[React 18 example](https://codesandbox.io/s/setting-state-inside-of-a-non-react-event-listener-react-18-mx0lt?file=/src/index.tsx)

→ Different behaviour depending on `createRoot` + `render`

If using `ReactDOM.createRoot` then effects *are* flushed synchronously (the same as React 17)

```ts
ReactDOM.createRoot(rootElement).render(<App />);
```

Interestingly, if you use `ReactDOM.render` with React 18, then effects *are not* flushed synchronously (different behaviour to React 17)

```ts
ReactDOM.render(<App />, rootElement);
```

#### Second example: "setting react `state` inside of a `ref` callback"

[React 18 example](https://codesandbox.io/s/useeffect-and-event-timing-refs-in-state-react-18-f3hnz)

- Same behaviour with `createRoot` + `render`
- Same behaviour as React 17 → effect is flushed synchronously

### Where to from here?

1. Is my interpretation of what I am seeing correct? Are effects scheduled with `useEffect` sometimes synchronous? What *should* the behaviour be in React 18?
2. I do not mind that effects scheduled with `useEffect` can something be synchronous; there are probably good reasons for them to be; and for most effects it should be fine. However, I do think it would be worth calling out that they can sometimes be synchronous as it can cause timing bugs. Perhaps a note in the docs would be sufficient

Thanks @aprilxyc and @Andarist for helping me troubleshoot this one!

**Comment by alexreardon** [comment]
Me, last week:

![5ovbxm](https://user-images.githubusercontent.com/2182637/135978949-a31c8f64-14d4-4cc9-800a-d2b024048481.jpg)

**Comment by just-boris** [comment]
I think, it is related to that story: https://github.com/facebook/react/issues/21400

**Comment by alexreardon** [comment]
#21400 looks related. However, in both of the cases I found, there is no `useLayoutEffect`

**Comment by bvaughn** [comment]
> Having effects sometimes be synchronous is usually fine for most effects. However, there can be cases where having an effect running synchronously can be problematic. This recently caused a bug for a project I work on.

It is important for effects code to be resilient to being run async or sync. (If you _need_ to introduce async code for some reason, you _could_ use a timeout– just be sure to return a cleanup function that calls `clearTimeout` if you do this.)

> Is my interpretation of what I am seeing correct? Are effects scheduled with useEffect sometimes synchronous? What should the behaviour be in React 18?

Yes, as is mentioned here:
This comment https://github.com/facebook/react/issues/21400#issuecomment-830432003

If something (usually a layout effect) schedules sync work, React has to flush any pending passive effects before processing the new work– so the overall order will be preserved.

**Comment by bvaughn** [comment]
cc @rachelnabors and @gaearon for making a note of this in the effects docs

**Comment by alexreardon** [comment]
Hi @bvaughn,

Thank you for your prompt reply. Based on my reading of the `react` documentation, and other writings; I had not come across knowledge that "It is important for effects code to be resilient to being run async or sync".

I think this would be great knowledge to surface in the documentation just so that people know about this behaviour 👍

**Comment by alexreardon** [comment]
Here is a `useDeferredEffect` hook that schedules effects to be run in a future task.

I'm still hashing it out, writing tests etc.

```ts
import { DependencyList, useEffect, useRef } from 'react';

type CleanupFn = () => void;

// Under certain conditions, effects queued with `useEffect` can be flushed *synchronously*
// See https://github.com/facebook/react/issues/22506
// For most effects it is fine to be run either sync or async
// However, some effects do need to be in a task after rendering
export default function useDeferredEffect(
  fn: () => void | CleanupFn,
  deps?: DependencyList,
) {
  const cleanupRef = useRef<CleanupFn | null>(null);

  useEffect(
    function setup() {
      const timeoutId = setTimeout(function task() {
        cleanupRef.current = fn() ?? null;
      });

      cleanupRef.current = () => clearTimeout(timeoutId);

      return function cleanup() {
        cleanupRef.current?.();
      };
    },
    // Ignoring 'fn' from the dependency array
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [deps],
  );
}
```

relevant eslint configuration:

```
'react-hooks/rules-of-hooks': 'error',
'react-hooks/exhaustive-deps': [
  'error',
   {
      additionalHooks: '(useDeferredEffect)',
   },
],
```
