### ISSUE TITLE
Fast Refresh: Crash when hot reload with some specifics content security policies

### ISSUE THREAD

**Issue by maxime4000** [facebook/react#22519]
# Summary :
We have our app that has been working well with hot reload for a while now and recently we have include CSP in our index.html.
We find out that when the app need to hot reload, the app just freeze. In fact, everything because unresponsive while the UI get updated correctly. Lets said I'm changing a string, the string will display right at the hot reload, but now every button, actions, styles become unresponsive. There's a iframe appearing in front of everything which block the site. 

```
<meta
	http-equiv="Content-Security-Policy"
	content="default-src 'self'; 
		style-src 'self' 'unsafe-inline'; 
		script-src 'self'; // This one freeze the app
		script-src 'self' 'unsafe-inline'; // this one does not freeze the app.
		img-src 'self' data:;
		object-src 'none';
		connect-src 'self';"
/>
```

https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

**Comment by bvaughn** [comment]
Hi @maxime4000 

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
