### ISSUE TITLE
Bug: dom.br can't accept empty Fragments as children

### ISSUE THREAD

**Issue by markboyall** [facebook/react#22530]
When rendering a dom.br(), React will fail if you use a Fragment which has no children.

React version: 17.0.1

## Steps To Reproduce

1. Using the React UMD distribution in a browser
2. ReactDOMServer.renderToStaticMarkup(ReactDOMFactories.br({}, React.createElement(React.Fragment, {}))) throws

## The current behavior

React fails to render, even though the dom.br in fact has no children

## The expected behavior

React should at least be able to see through arrays and Fragments when performing this check. Ideally even custom components that ultimately do not render any DOM would also be tolerated.

You may ask what the purpose of this is. In short, we are mapping from some HTML to a React render, with some translations. For all elements, we map the children into a Fragment. If there are no children in the source HTML, then the Fragment is empty. In this case we therefore fail to render even though the input is valid HTML. We can simply spread the child array directly, but it simplifies things a bit if we can simply use Fragments to represent the children as then the caller does not need to know about these details.

**Comment by lubieowoce** [comment]
FWIW, `<br><></></br>` doesn't seem to work on the client either: [Codesandbox](https://codesandbox.io/s/focused-panna-wuo2x)
> Error: br is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

**Comment by markboyall** [comment]
@eps1lon doesn't that just mean that `render(<br><></></br>)` is equally broken and also needs fixing?

**Comment by eps1lon** [comment]
Would you consider `<br>{false}</br>` also broken? What about `<br>{""}</br>`? I think it's simpler to just don't accept any children instead of going down the tree to check if children render anything.

**Comment by markboyall** [comment]
@eps1lon Probably I would consider those broken as well, yes. The simpler thing to do is move the check to be after the React tree is materialised to HTML, because that's when the invariant actually applies. React shouldn't be running validation checks on the React tree as if it's the HTML tree when it's not. If React can't implement the check correctly, it simply shouldn't implement it, rather than breaking valid code.

**Comment by eps1lon** [comment]
I have to check again but I believe the reason for the check is mostly to provide a good error message for hydration if you do end up rendering <br> with children.

And there may be more edge cases like Suspense with an empty fallback etc. It seems simpler to just not pass in children to br. Why is that difficult in your case?

**Comment by lubieowoce** [comment]
i'm not a maintainer or anything, but i don't think this is a bug. MDN says `<br>` is an [empty element](https://developer.mozilla.org/en-US/docs/Glossary/Empty_element), so while `<br>` and `<br/>` are both valid, `<br></br>` isn't. which is more or less the difference between *no children* and *children equal to an empty fragment*.

surely it's not a huge deal to just have a list of these tags and simply not pass any children to them? HTML5 parsers need a list like that too, the spec is just weird like that
