### ISSUE TITLE
Bug: Rules with suggestions must set the `meta.hasSuggestions` property to `true`

### ISSUE THREAD

**Issue by pkelly-rh** [facebook/react#22545]
I'm basically running into an issue where eslint is asking me to set meta.hasSuggestions to true. When I use `"react-hooks/exhaustive-deps": "error"`. Is there something I'm doing wrong or is this a dep version thing?

React version:

## Steps To Reproduce

1. Have my eslint config:
```json
{
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 13,
    "sourceType": "module"
  },
  "plugins": ["react", "react-hooks", "@typescript-eslint"],
  "rules": {
    "react-hooks/exhaustive-deps": "error",
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  }
}

```
Here's my deps from package.json
```json
{
"dependecies": {
    "eslint": "^8.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-react": "^7.26.1",
    "eslint-plugin-react-hooks": "^4.2.0",
}
```

If I try to remove the react-hook plugin and extension this happens:
`Definition for rule 'react-hooks/exhaustive-deps' was not found`

Link to code example:

**Comment by paul-mesnilgrente** [comment]
Looks like we're still waiting on a new release :/

**Comment by a-tonchev** [comment]
> Running `npm install eslint-plugin-react-hooks@next` worked for me

This works for me, thanks!

**Comment by Dangoo** [comment]
Looks like `v4.3` was just released some hours ago which should ship ESLint 8 support:
https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/CHANGELOG.md#430

See as well #22248
