### ISSUE TITLE
Bug: shows duplicate the last elements of an array stored with useRef

### ISSUE THREAD

**Issue by stvkoch** [facebook/react#22564]
I'm keeping the last values passed as props without force a re-render, I'm using the `useRef` to store the elements without re-render the output.

The weird part is that the values showed are different from what I'm storing, duplicating the last elements.

React version: 17.0.2
![image](https://user-images.githubusercontent.com/14454/137406585-c89f359b-7777-4d66-ba2d-ecaebae5ac47.png)

Link to code example:

https://codesandbox.io/s/stupefied-ride-m1did?file=/src/App.js

```
import React from "react";

const ComR = React.memo(function Compo({ id, value }) {
  const lastElements = React.useRef([0, 0, 0, 0, 0]);
  const [_, ...m] = [...lastElements.current, value]; // remove first and insert last
  lastElements.current = m;
  console.log("rendering", id, value, memo.current);
  return (
    <div>
      {id} - {lastElements.current.join(", ")}
    </div>
  );
});

export default function App() {
  const [value, setValue] = React.useState(0);

  React.useEffect(() => {
    setInterval(() => {
      setValue(Math.ceil(Math.random() * 10000));
    }, 7000);
  }, [setValue]);

  return (
    <div className="App">
      <ComR id="1" value={value} />
    </div>
  );
}
```

## The current behavior

The console.log is showing different what is printing into the component

![image](https://user-images.githubusercontent.com/14454/137407532-d1fff912-0542-43f8-8c99-5d87da094da2.png)

## The expected behavior

expects work as linear array operations, since was called/rendered once

**Comment by bvaughn** [comment]
> Anyway its no good adding side effects in rendering

This is right! You can learn more here: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

Calling `setTimeout` is a side effect, which is why you have it in an effect:
```js
  React.useEffect(() => {
    setInterval(() => {
      setValue(Math.ceil(Math.random() * 10000));
    }, 7000);
  }, [setValue]);
```

But modifying the ref (reading _or_ writing) during render is _also a side effect_:
```js
const ComR = React.memo(function Compo({ id, value }) {
  const lastElements = React.useRef([0, 0, 0, 0, 0]);
  const [_, ...m] = [...lastElements.current, value];

  // This is also a side effect;
  // the only time this should be done is for the "lazy initialization" pattern.
  lastElements.current = m;
```

I wrote a bit more about _why_ this is on PR #18545, although we have not yet enabled this warning.

**Comment by bvaughn** [comment]
Going to close this issue because it seems like a misunderstanding that has hopefully been rectified by the two replies above. Let me know if anything is still unclear though.

**Comment by gaearon** [comment]
To follow up on this, we've changed the logging behavior in 18 to be more intuitive.
https://github.com/facebook/react/issues/21783#issuecomment-1083412766
