### ISSUE TITLE
 Attempted import error: 'useLocation' is not exported from 'react-router-dom'.

### ISSUE THREAD

**Issue by sytpb** [facebook/react#22565]
React version:
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-router-dom": "5.0.1",
    "react-scripts": "3.4.0",

js code as 

import {useLocation} from "react-router-dom";
const location = useLocation();
......  where is the  problem ?

**Comment by lamhungypl** [comment]
codesandbox reproduce, please!

**Comment by vaibhav9879** [comment]
The Version 5.3 is also not working what is the solution now?
![image](https://user-images.githubusercontent.com/107169728/182132715-df267fdb-5787-48d5-93b2-4d3a2b141d31.png)
