### ISSUE TITLE
Animating when adding/removing a single component

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#226]
It's useful to be able to animate the appearance and disappearance of a particular component.

It's possible to animate entrances without too much trouble by hand, using componentDidMount but exits are harder since elements disappear immediately after componentWillUnmount and don't give the animation time to finish.

What can we add to React to make this easy?

(See also #227.)

**Comment by michaelahlers** [comment]
Was there ever a direct resolution to this ticket (it's possible I've missed a few things in the comments here)?

To recap, it's clear how you can elegantly cause enter animations by setting state from known properties in `componentDidMount`, but I still don't see how the opposite effect can be accomplished, as illustrated in the following (non-functional) example:

```javascript
React.createClass({
  getDefaultProps: function() {
    return { items: [1, 2, 3] }
  },

  getInitialState: function() {
    return { items : [] }
  },

  componentWillMount: function() {
    this.setState({ items: this.props.items })
  },

  render: function() {
    return (
      <ReactCSSTransitionGroup transitionName="item">
        {this.state.items.map(function(item, index) {
          return <span key={index}>{item}</span>
        })
      </ReactCSSTransitionGroup>
    )
  },

  componentWillUnmount: function() {
    // Obviously broken.
    this.setState({ items: [] })
  }
})
```

It's been a frustrating exercise trying to accomplish this effect in a more complex application (in my case, one using a router library and Flux pattern) where there's little or not control at components one level up the hierarchy from those wishing to do animations. If it was possible to capture and then perform leave animations as illustrated here, I'd be able to cut a huge amount of complexity.

PS, please forgive the lack of semicolons—I write a lot of Scala these days.

**Comment by chenglou** [comment]
@michaelahlers I have a working wrapper (animation library-agnostic, mostly) [here](https://github.com/chenglou/react-state-stream/tree/master/App4). It's a bit messy right now but once I find some more free time I'll pull it out. See https://github.com/chenglou/react-tween-state/issues/15 as well.

(This sure brings back memories =))

**Comment by michaelahlers** [comment]
@chenglou, leave it to me to dig up nostalgia fuel for you. :smirk: Reading your samples there is kind of funny; I was contemplating—even as I wrote my comment—about how enter and exit transitions are inadequate for a lot of animation use cases, and struggling to make them work in this framework might result in isolated, short-term gains for big-picture, long-term losses. Your work definitely looks several steps ahead! State Stream looks incredibly powerful and—with a functional programming background—equally intuitive. Combined with Tween State, I can imagine a lot of sophistication that can't be accomplished purely in CSS. That said, it looks like @irvinebroque and I are in the same boat: needing a good baby step that adds exit animation classes with node removal only after CSS animations complete.

**Comment by chenglou** [comment]
Eh sorry, state-stream is unrelated. The wrapper _should_ mostly work in conjunction with anything else, including a simple `className` change and node removal.

**Comment by michaelahlers** [comment]
You may have lost me a bit. `Container`, from [`App4`](https://github.com/chenglou/react-state-stream/blob/master/App4/App4.jsx), appears to have a similar usage pattern to `TransitionGroup`, in that it's going to apply certain CSS properties to its children based on the state of its parent—whose state is managed internally. This is where my needs fundamentally differ (I think). Putting it loosely, in my particular case, a router library is responsible for building the component tree, and I've got little control over how and when any individual component will be mounted or unmounted. That's why I'm seeking a means of triggering any arbitrary animation from `componentWillUnmount` (in a way that allows the transition group the keep the nodes in the DOM until animation's done) because it's fully-encapsulated. For now, it may be that I need to move more state into my Flux stores that's cleared out (which then effectively applies the `componentDidMount` approach to leave animations) on certain routing events.

**Comment by maxviewup** [comment]
A good way to animate a removal is delaying it. for instance, when you call the delete function, it updates the state, saying the element x will be removed. then, it sets a timeout or make a AJAX request. Meanwhile, the component will recive the signal and will animate itself.

Another way is never remove the element. it will be always there, but the visible state will be changed. Material-UI uses this, for instance.

**Comment by jack-sf** [comment]
This is how we handled it:

- use `Transition#props.appear` to start show animation only after component is mounted
- when `Transition#props.onExited` is called, call `MyComponent#props.onHideTransitionEnd`, to inform the parent that the hide transition has ended (so the parent knows that this component can be unmounted now)

Then, for example, if you want to:

- mount a `MyModal` immediately when somebody clicks on a button
- unmount the `MyModal` only after MyModal is scheduled to close **and** its' close animation has finished

, then you can do it like that:

```tsx
const MyOpeningComponent = ({ initialModalOpen = false }) => {
  const [mountModal, setMountModal] = useState(initialModalOpen);
  const [openModal, setOpenModal] = useState(initialModalOpen);

  const handleOpen = useCallback(() => {
    setMountOverlay(true);
    setOpenOverlay(true);
  }, []);

  const handleClose = useCallback(() => {
    setOpenOverlay(false);
  }, []);

  const handleCloseTransitionEnd = useCallback(() => {
    if (!openModal) {
      setMountModal(false);
    }
  }, [openModal]);

  return (
    <>
      <button onClick={handleOpen}>Open modal</button>
      {(mountModal || openModal) && (
        <MyModal
          open={openModal}
          onClose={handleClose}
          onCloseTransitionEnd={handleCloseTransitionEnd}
        />
      )}
    </>
  );
};
```

**Comment by jtomaszewski** [comment]
This is how we handled it:

- use `Transition#props.appear` to start show animation only after component is mounted
- when `Transition#props.onExited` is called, call `MyComponent#props.onHideTransitionEnd`, to inform the parent that the hide transition has ended (so the parent knows that this component can be unmounted now)

Then, for example, if you want to:

- mount a `MyModal` immediately when somebody clicks on a button
- unmount the `MyModal` only after MyModal is scheduled to close **and** its' close animation has finished

, then you can do it like that:

```tsx
const MyOpeningComponent = ({ initialModalOpen = false }) => {
  const [mountModal, setMountModal] = useState(initialModalOpen);
  const [openModal, setOpenModal] = useState(initialModalOpen);

  const handleOpen = useCallback(() => {
    setMountOverlay(true);
    setOpenOverlay(true);
  }, []);

  const handleClose = useCallback(() => {
    setOpenOverlay(false);
  }, []);

  const handleCloseTransitionEnd = useCallback(() => {
    if (!openModal) {
      setMountModal(false);
    }
  }, [openModal]);

  return (
    <>
      <button onClick={handleOpen}>Open modal</button>
      {(mountModal || openModal) && (
        <MyModal
          open={openModal}
          onClose={handleClose}
          onCloseTransitionEnd={handleCloseTransitionEnd}
        />
      )}
    </>
  );
};
```
