### ISSUE TITLE
Importing from one's own file results in localhost not loading and eventually crashing tab

### ISSUE THREAD

**Issue by NoYouNotUrUncle** [facebook/react#22610]
Not sure if this is a bug or not; It should be undefined behavior but was needlessly difficult to debug. 

Importing a react component (which doesn't exist) from its own file doesn't result in any sort of errors at compilation or runtime. It leaves localhost:3000 on loading until the tab runs out of memory and crashes. 

Steps to reproduce - 

1. Create a react app in an empty folder with `npx create-react-app demo`

2. Delete all files in the `demo/src` folder

3. Create the following files in the `demo/src` folder:

`index.js`
```js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(<App/>, document.getElementById('root'));
```
<br/>

`App.js`
```js
import React from "react";
import Foo from "./App";

class App extends React.Component {
    render() {
        return (
            <Foo/>
        )
    }
}

export default App;
```

4. do `cd demo`
5. do `npm start`
6. Go to `localhost:3000`
7. Wait for browser to crash and cry because you can't find the bug

One would assume this type of thing would be caught in compilation, or at least throw an error at runtime - but it does not.

**Comment by irinakk** [comment]
Its nothing to do with React, this happens because you did `import Foo from "./App";` in App.js, while `Foo` points to the default export of App.js, which is `App`, and this create a infinite recursion.

**Comment by bvaughn** [comment]
Sorry you ran into this issue and that it was difficult to debug 🙇🏼 

This doesn't look like a React bug though. Meaning that you could create this same bug without React, just using a bundler like Webpack. I'm going to close this issue to avoid confusion.
