### ISSUE TITLE
[DevTools Bug] Cannot remove node "264" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by huyprowow** [facebook/react#22611]
### Website or app

https://codesandbox.io/

### Repro steps

i open chrome developer tools width react-developer-tool to view layout page and :v while i scroll page :v

### How often does this bug happen?

Often

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.20.0-e5f486b5a

### Error message (automated)

Cannot remove node "264" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25851:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:23957:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24117:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:52741:41)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by haohanshi** [comment]
@huyprowow You may have 2 versions of react devtool extension installed. Try removing one of them.

**Comment by huyprowow** [comment]
:v i don't think so :v, because i has a one version on chrome and this bug i think it happens when the DOM removes previously rendered components(i inspect one element and after that it was deleted) and It's not bothersome enough, my bad. And sory because i can reproduce them T.T
