### ISSUE TITLE
[DevTools Bug]: "Reload and start profiling" button is missing on Microsoft Edge

### ISSUE THREAD

**Issue by yifanwww** [facebook/react#22630]
### Website or app

Any development URL are ok

### Repro steps

1. Open the React Developer Tools extension on Chrome and navigate to the Profiler tab. Note the presence of the "Reload and start profiling" button.
2. Open the React Developer Tools extension on Microsoft Edge and navigate to the Profiler tab. Note the absence of this button.

I have checked #21384, and `document.featurePolicy.allowsFeature('sync-xhr')` returns `true`.

### How often does this bug happen?

Every time

### DevTools version (automated)

4.20.2

**Comment by torressam333** [comment]
I don't see it in chrome now either using chrome 120 and DevTools v5.0.0
