### ISSUE TITLE
Bug: State getting reset / (items getting removed) when adding new element to Array

### ISSUE THREAD

**Issue by rayanfer32** [facebook/react#22658]
React version: 17.0.2

## Steps To Reproduce

1. calling addRow function 

Link to code example:
https://codesandbox.io/s/practical-bush-20eyb?file=/src/App.js

## The current behavior
state is getting reset when new data is added to the array using ES6 syntax

## The expected behavior
state should be retained when new data is added to the array

**Comment by omelendrez** [comment]
You can use *Functional updates* to update the state and it will work:
```bash
 setTableRowElements((tableRowElements) => [...tableRowElements, newRow]);
```

**Comment by rayanfer32** [comment]
What was causing the issue over here actually :disappointed:

**Comment by omelendrez** [comment]
At that point in your code the array `tableRowElements` is not yet updated. It will be after the next render. 
*Functional updates* approach allows you to get the latest value in the scope of the state so you don't need to wait for the render go get it.
