### ISSUE TITLE
Navigating to a new tab with DevTools open does not load Components tree

### ISSUE THREAD

**Issue by jstejada** [facebook/react#22663]
## Repro

This is reproducible in version v4.21.0 (even after reverting logic to detect duplicate extensions)

1. Load reactjs.org and open DevTools
2. Observe Component tree loads correctly
3. Navigate to facebook.com
4. Component tree does not load
5. Open Chrome DevTools for the extension and observe the following error
![image](https://user-images.githubusercontent.com/1271509/139601677-b47c5c2a-8e61-413c-8807-0d0c922dbc44.png)

**Comment by Biki-das** [comment]
Can j possibly work on this?

**Comment by akgupta0777** [comment]
Also reproducible in version 4.20.2 (10/25/2021) in chrome browser. reactjs.org works fine and tree is loaded but as soon as we go to facebook.com it doesn't.

**Comment by akgupta0777** [comment]
> Also reproducible in version 4.20.2 (10/25/2021) in chrome browser. reactjs.org works fine and tree is loaded but as soon as we go to facebook.com it doesn't.

Just noticed that this behaviour is only happening in chrome, I have same version of devtools on edge as well as firefox but they are able to load the tree correctly
