### ISSUE TITLE
Bug: Variables should not be initialized to `undefined`

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#22666]
found certain files where variables were initialized to `undefined` which is sort of an anti pattern because JS seems to put undefined by default if no value is assigned 

file links -:

packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js - Line no-29
packages/react-dom/src/__tests__/ReactDOMServerIntegrationElements-test.js- Line no-1047
packages/react-native-renderer/src/__tests__/ReactFabric-test.internal.js

`let fatalError = undefined;`

we can just write 👇

`let fatalError`

**Comment by bvaughn** [comment]
I don't think we need an issue to track this. Seems like more of a stylistic preference. :) Going to close this. Hope that's okay!

**Comment by Biki-das** [comment]
pulling a PR for the same hope that's fine
