### ISSUE TITLE
Improve DevTools CSS variables situation

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#22678]
Related to this comment: https://github.com/facebook/react/pull/22660#pullrequestreview-795368779

The majority of DevTools theme colors are stored in `packages/react-devtools-shared/src/constants`:
https://github.com/facebook/react/blob/5cccacd131242bdea2c2fe4b33fac50d2e3132b4/packages/react-devtools-shared/src/constants.js#L75-L383

But some of them are also stored in `packages/react-devtools-shared/src/devtools/views/root.css`:
https://github.com/facebook/react/blob/5cccacd131242bdea2c2fe4b33fac50d2e3132b4/packages/react-devtools-shared/src/devtools/views/root.css#L2-L18

This is because of how they are referenced in a theme-agnostic way by Reach UI style overrides (for things like tooltips and context menus).

Can we do better here, at least to ensure they stay in sync? For example, can the `ThemeProvider` set the redundant values at the root level when the `SettingsContext` theme changes?

The primary goals of the current architecture are:
1. Don't bleed styles into the global namespace (for our inline package users like Code Sandbox or Replay IO).
2. Don't require awkward forced layout or re-renders for components that read style values programatically.

**Comment by jyash97** [comment]
I was looking into it and here is what I have in mind: 

Exposing all vars using `style` prop to reach-ui components which will be rendered in Portal (outside the rendered DOM), and we can create wrapper component or re-export the same component by passing all vars:

```
// lib/reach-ui/MenuList.js
import {MenuList} from 'react-ui'

export const MenuList = ({children, ...props}) => <MenuList style={THEME_VARS} {...props}>{children}</MenuList>
```
Example: https://codesandbox.io/s/quiet-fast-exg5q?file=/src/App.js

`children` will have access to those CSS variables and we can style without adding custom variables in `root.css`

**Comment by bvaughn** [comment]
@jyash97 Oh! That's a very eloquent solution!

So DevTools can just re-export the components we use, with the style decoration. Love it!

**Comment by jyash97** [comment]
Glad you liked it 😄 

Can I create a draft PR for the above solution ?

**Comment by bvaughn** [comment]
Yes, please do!
