### ISSUE TITLE
Many errors in console even using Error Boundary

### ISSUE THREAD

**Issue by BiancaArtola** [facebook/react#22671]
React version: 17.0.2
Relay version: 12.0.0

## Steps To Reproduce

1. Wrap a component with an ErrorBoundary class to manage errors. Something like this:
```
  <ErrorBoundary FallbackComponent={ErrorFallback}>
          <Suspense
            fallback={
              <LoaderContainer>
                <LoaderIcon iconSize="xl" />
              </LoaderContainer>
            }
          >
            <DetailedStatusContainer />
          </Suspense>
        </ErrorBoundary>
```
On Detailed Status Container I have this:
```
 const data =
    useLazyLoadQuery(
      RobotProductOverviewBySerialNumberQuery,
      serialNumber
    );

```
2. If I sent an invalid value to the query, the ErrorBoundary will be executed because the query returns 500. That's expected, but check that the console has the following errors:
![image](https://user-images.githubusercontent.com/21174759/139734520-22ffb46a-9ea5-4c50-8daf-6ea8f5037781.png)

Is there a way to avoid the last two errors on the console?

## The current behavior
Console messages:
![image](https://user-images.githubusercontent.com/21174759/139734585-d9eca0cb-141d-4bf2-baf2-d2e24c9daa85.png)

## The expected behavior
Only shows 500 error message:
![image](https://user-images.githubusercontent.com/21174759/139734652-3c93b3b6-a777-4a00-90bb-d4dba4a3f23e.png)

**Comment by lubieowoce** [comment]
https://github.com/facebook/react/issues/15069
