### ISSUE TITLE
FireFox report deadkey+deadkey as a single combined event

### ISSUE THREAD

**Issue by syranide** [facebook/react#2269]
Pressing `~` followed by `^` (deadkeys) is reported as `'~^'`, etc rather than `'~'` immediately followed by `'^'` as other browsers do. Probably not worth normalizing. Putting it here for posterity.

**Comment by aweary** [comment]
Looks like this issue either doesn't exist anymore or hasn't impacted anyone in almost three years. Since it was just opened for posterity, I'm going to go ahead and close it :)
