### ISSUE TITLE
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

### ISSUE THREAD

**Issue by ffbok2** [facebook/react#22708]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

_Originally posted by @facebook-github-bot in https://github.com/facebook/SoLoader/issues/85#issuecomment-962291190_

**Comment by ffbok2** [comment]
velox/exec/LocalPlanner.cpp

**Comment by ffbok2** [comment]
> Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!
> 
> _Originally posted by @facebook-github-bot in https://github.com/facebook/SoLoader/issues/85#issuecomment-962291190_

**Comment by akgupta0777** [comment]
Thanks for signing the CLA. You can now close this issue.
