### ISSUE TITLE
[ESLint Bug]: Rules of Hooks breaks with IIFEs

### ISSUE THREAD

**Issue by JamesGelok** [facebook/react#22704]
### Summary

It seems like the rules of hooks break on [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)s when it seems like they shouldn't.

[This codesandbox is the best way to see what I'm talking about.](https://codesandbox.io/s/rules-of-hooks-trouble-with-iife-kz1f7?file=/src/index.tsx) However, I've included more details below in the (1) **_Flat Reproduction Steps_** and (2) **_Example Use-case_** sections.

### Flat Reproduction Steps
<ol>
<li>
Create some custom hook.
<pre lang="tsx"/>
// This one is fine
const useStateRegular = (initVal: any) => useState(initVal);
</pre>
</li>
<li>
Modify the hook to use an <a href="https://developer.mozilla.org/en-US/docs/Glossary/IIFE">IIFE</a>
<pre lang="tsx"/>
// This one breaks rules of hooks. ❌
const useStateIFFE = (initVal: any) => (() => useState(initVal))()
</pre>
</li>
<li>
Observe that this triggers ESLint (in an ESLint compatible environment; see <a href="https://codesandbox.io/s/rules-of-hooks-trouble-with-iife-kz1f7?file=/src/index.tsx">codesandbox also linked above</a>)
</li>
</ol>

### Example Use-case
```tsx
// Example usage: a sort-of-functional style for a toggle boolean hook 
const useToggle = (init: any) =>
  (([myBool, setMyBool]): [boolean, () => void] => [
    myBool,
    // useRef breaks the rules of hooks here ❌
    useRef(() => setMyBool((prevValue) => !prevValue)).current
  ])(useState(!!init));

function ExampleUsage() {
  const [value, toggleValue] = useToggle(true);
  return (
    <>
      <h2>example usage</h2>
      <button onClick={toggleValue}>
        <code>{`value:${value}`}</code>
      </button>
    </>
  );
}
```

```
DISCLAIMER: 
1. Although this may be an odd style, this doesn't really break the rules of hooks.
2. Again about the style, it's OK to prefer `useCallback` here if you want. 
I'm not trying to write something perfect for this example, I'm just trying to give one.
```

**Comment by salazarm** [comment]
The lint rules aren't meant to be perfect, they're mostly just heuristics. This rule also triggers for components that define hooks using `useCallback`. That said if you want to submit a PR to the rule identify IIFE's then I'd be happy to take a look.

**Comment by JamesGelok** [comment]
> The lint rules aren't meant to be perfect, they're mostly just heuristics

Agreed ^_^ 

I'm sorry for conveying that the eslint rule is supposed to be perfect. I had originally intended to convey that I wanted the rule to be a bit better regarding IIFEs. 

So maybe it would've been better to call this an `[ESLint Improvement]` rather than `[ESLint Bug]`? 

> This rule also triggers for components that define hooks using `useCallback`. 

That's good to know and test for when I check it out!

> That said if you want to submit a PR for the rule to identify IIFE's then I'd be happy to take a look.

I'd be happy to. (Unless someone else sees this & snipes it before I get a chance to give it a try sometime in the next few days).

**Comment by gaearon** [comment]
We've intentionally decided to _not_ support IIFEs here. Think of `use` almost as syntax with restrictions on which parent function it can appear in lexically.

>a sort-of-functional style for a toggle boolean hook 

I'd add we strongly discourage this style. The whole point of Hooks is to write things in a direct manner. Of course we can't tell you what to do, but this is not how Hooks are intended to be used.

**Comment by gaearon** [comment]
So, to be clear, while we could make it work in principle, we think it's a pretty confusing way to use React, and the conventional tooling (like the lint rule, or Fast Refresh) should discourage it. Direct style is both easier to read and makes it easier for tooling to understand what you're trying to do. If React was a language, we'd enforce this as a compilation error.

**Comment by JamesGelok** [comment]
@gaearon That makes sense & I agree 👍 . 

Theoretically there's no bad branching in cases presented and so they'd be fine as _working hooks._ But the style is pretty gnarly.

Also – for completeness and for anyone else who happens upon this, I'll mention an error on my part. In my disclaimer, I said `1. Although this may be an odd style, this doesn't really break the rules of hooks.`: 

<details><summary>
<b>I was wrong. <i>It does break the rules of hooks.</i></b>
Specifically, the "nested functions" part of the first rule "<a href="https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level">Only call hooks at the top level.</a>"</summary><br/>

1. IFFEs used like this are in fact, nested functions. (see more: [Nested Functions MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#nested_functions_and_closures))

2. Here's the thing I missed <img src="https://user-images.githubusercontent.com/23425952/140564599-f1621702-e8a8-45f0-8b0e-f4e700bc266e.png" />
<hr/>

</br></details>
