### ISSUE TITLE
Bug: Create-react-app fail of compile.

### ISSUE THREAD

**Issue by shokilak** [facebook/react#22707]
If windows username have a quote - app will give out a Fail of compile. Code wasnt changed, its like npx created it.

![image](https://user-images.githubusercontent.com/74506125/140565777-7ee3f6bd-3831-4065-b367-1b83e9d21d3e.png)
![image](https://user-images.githubusercontent.com/74506125/140566098-bab96c1d-bc55-449a-886c-cbef6bb638b4.png)

**Comment by bvaughn** [comment]
This is the React repo. It sounds like you're reporting an issue with create-react-app. Please report it in the create-react-app repository:
https://github.com/facebook/create-react-app/issues/

That repo is maintained by a different team of people.

Also, please search to see if the issue has already been opened before posting a new one.
