### ISSUE TITLE
Safari performance while adding list items

### ISSUE THREAD

**Issue by MayuraRam** [facebook/react#22714]
I am using React version 17.0.2 and running an app  on Safari 15.1. The component adds 20 list items at a time.  The list item contains three divs, one span element and one img element. I am using a reducer to load the data. After Adding the DOM elements, there is scroll event happening to show the list at the bottom. The issue is that Safari is taking much more time than Chrome on a MacBook Pro to add the DOM elements to the list. I have used the Profiler API to get some insight into the actualDuration spent by Safari and by Chrome. Chrome is much faster. 

I wanted to know how I can profile this usage to see why Safari is so slow? From Web Inspector I see that JavaScript execution time and Paint are much, much more than Chrome. Are there are any insights that could explain this behavior? 

This doesn't seem to be an issue with React as such - but any pointers or discussion on why this is happening would be helpful.

**Comment by guojin-long** [comment]
有点好奇， Safari 比chrome慢了多少？

**Comment by HamidReazaNikoonia** [comment]
> I am using React version 17.0.2 and running an app on Safari 15.1. The component adds 20 list items at a time. The list item contains three divs, one span element and one img element. I am using a reducer to load the data. After Adding the DOM elements, there is scroll event happening to show the list at the bottom. The issue is that Safari is taking much more time than Chrome on a MacBook Pro to add the DOM elements to the list. I have used the Profiler API to get some insight into the actualDuration spent by Safari and by Chrome. Chrome is much faster.
> 
> I wanted to know how I can profile this usage to see why Safari is so slow? From Web Inspector I see that JavaScript execution time and Paint are much, much more than Chrome. Are there are any insights that could explain this behavior?
> 
> This doesn't seem to be an issue with React as such - but any pointers or discussion on why this is happening would be helpful.

could you give us an example of this behavior in codeSandbox or anything else?
