### ISSUE TITLE
[DevTools Bug] Cannot add child "44" to parent "42" because parent node was not found in the Store.

### ISSUE THREAD

**Issue by I7RANK** [facebook/react#22734]
### Website or app

https://github.com/I7RANK/holbertonschool-web_react

### Repro steps

Hello, I hope you are great.

1. Make a git clone and go to `0x03-react_props/task_2/dashboard/` directory
2. Install the node_modules using `npm install`
3. Then execute `npm run start`
4. And go to http://localhost:8080/
5. You need to install the React Developer Tools extension for Google Chrome (link [here](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi))
6. Open the Chrome DevTools by pressing `F12`
7. Now in the tabs of the new window opened by pressing `F12` choose the tab `Profiler`
8. And click on the `Reload and start profiling` button to see the error.

See an example here and thanks in advance:
![React_developer_tools_Error](https://user-images.githubusercontent.com/65993425/141037229-fda4531e-822e-4b16-8e03-410f84321b8d.jpg)

Also, I have other extensions just in case you need
![image](https://user-images.githubusercontent.com/65993425/141038103-37fa2313-b360-4cce-8208-d6b9f5866beb.png)

and in another Google chrome profile that I tried, has these extensions
![image](https://user-images.githubusercontent.com/65993425/141038275-f8456a76-2890-4c01-86d4-da22bbe0a6fa.png)

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.21.0-2f8f60ca8

### Error message (automated)

Cannot add child "44" to parent "42" because parent node was not found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26191:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24349:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24509:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53230:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add child  to parent  because parent node was not found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by MauricioAndrades** [comment]
Check if disabling the hot devServer in webpack fixes this.

**Comment by glowinginthedark** [comment]
Hey @I7RANK, I cloned your repo and I had to add my own template index.html to /0x03-react_props/task_2/dashboard/dist, as webpack was giving an error for not finding a template file. After running "npm run start", I can see 2 outcomes:-

First outcome (using this index.html template): 
![image](https://user-images.githubusercontent.com/33921776/141114507-3d3ee3ab-50db-410f-bf2f-b7a148cb380c.png)
Result: "Reload and start profiling" runs and finishes without errors.

Second outcome (using the same index.html, but this time we uncomment the <script> tag on line 13):
Result: This version produces the exact error that you have reported in your post when I run the profiler.

**Comment by I7RANK** [comment]
> Hey @I7RANK, I cloned your repo and I had to add my own template index.html to /0x03-react_props/task_2/dashboard/dist, as webpack was giving an error for not finding a template file. After running "npm run start", I can see 2 outcomes:-
> 
> First outcome (using this index.html template): ![image](https://user-images.githubusercontent.com/33921776/141114507-3d3ee3ab-50db-410f-bf2f-b7a148cb380c.png) Result: "Reload and start profiling" runs and finishes without errors.
> 
> Second outcome (using the same index.html, but this time we uncomment the <script> tag on line 13): Result: This version produces the exact error that you have reported in your post when I run the profiler.

Hi @glowinginthedark, yes commenting the `<script></script>` line the profiler works thanks for that but I don't understand why if the bundle.js is the file generated and supposed is necessary 🥴 I'm confused

**Comment by I7RANK** [comment]
> Check if disabling the hot devServer in webpack fixes this.

Hi @MauricioAndrades thanks for the suggestion, I commented on that line but I got the same error.
`
...
devServer: {
    historyApiFallback: true, // to can use @reach/router without errors
    /* hot: true, */
    compress: true,
    static: path.resolve('./dist'),
  },
...
`

**Comment by glowinginthedark** [comment]
> Hi @glowinginthedark, yes commenting the `<script></script>` line the profiler works thanks for that but I don't understand why if the bundle.js is the file generated and supposed is necessary woozy_face I'm confused

@I7RANK So I believe the reason it works is because HtmlWebPackPlugin is designed to automatically inject the bundle with the name you have specified in the output config object (filename: 'bundle.js' - you can also rename this and check that the bundle still loads by going to the storage tab in chrome browser dev tools). Also check [this question](https://stackoverflow.com/a/43704661/5165874) and [the documentation for the "inject" option](https://github.com/jantimon/html-webpack-plugin#options).

![image](https://user-images.githubusercontent.com/33921776/141248401-b2bb99ae-e0a9-469f-8c8b-0128430871cf.png)

**Comment by I7RANK** [comment]
> > Hi @glowinginthedark, yes commenting the `<script></script>` line the profiler works thanks for that but I don't understand why if the bundle.js is the file generated and supposed is necessary woozy_face I'm confused
> 
> @I7RANK So I believe the reason it works is because HtmlWebPackPlugin is designed to automatically inject the bundle with the name you have specified in the output config object (filename: 'bundle.js' - you can also rename this and check that the bundle still loads by going to the storage tab in chrome browser dev tools). Also check [this question](https://stackoverflow.com/a/43704661/5165874) and [the documentation for the "inject" option](https://github.com/jantimon/html-webpack-plugin#options).
> 
> ![image](https://user-images.githubusercontent.com/33921776/141248401-b2bb99ae-e0a9-469f-8c8b-0128430871cf.png)

Ohhhhhb now I understand everything thanks @glowinginthedark.
