### ISSUE TITLE
Bug: Devtools does not correctly identify context change for functional component

### ISSUE THREAD

**Issue by KamranAsif** [facebook/react#22737]
React version: 17.0.2
Devtools version: 4.21.0.1 (FB build)

## Steps To Reproduce

1. Open [sandbox](https://lke58.csb.app/) ([source](https://codesandbox.io/s/react-playground-forked-lke58))
2. Start profiling with 'Record why each component rendered while profiling' enabled.
3. Click the page a few times to force renders.
4. Stop profiling and view 'Why did this render?' panel

Link to code example:

https://codesandbox.io/s/react-playground-forked-lke58

## The current behavior

The profiler says the component rendered because the parent component rendered. This is incorrect, as the parent component is a MemoComponent that did in fact not render. 

![image](https://user-images.githubusercontent.com/2875524/141142246-08b02dba-bda1-436c-88ee-5d38822bee8d.png)

## The expected behavior

The component actually rendered because its context was changed. When digging into the devtools code,  we are checking the [memoizedValue](https://github.com/facebook/react/blob/e0aa5e205feee53043ce1ae8726fe732866e6ea7/packages/react-devtools-shared/src/backend/renderer.js#L1350) value on the context, which doesn't seem to exist.

 <pre><code>while (prevContext && nextContext) {
  <b>if (!is(prevContext.memoizedValue, nextContext.memoizedValue)) {</b>
    return true;
  }

  prevContext = prevContext.next;
  nextContext = nextContext.next;
}</pre></code>

![image](https://user-images.githubusercontent.com/2875524/141143059-aa1dde80-2df2-4599-b191-4d638f0df3a1.png)

I couldn't find the actual value on the context property; or in the memoizedState.

**Comment by KamranAsif** [comment]
Fixed codesandbox link

**Comment by bvaughn** [comment]
PR #22746 fixes this issue for _newer_ versions of React (e.g. 18 alpha) but older versions will remain broken because there's not a good way to read the most recent context value for a Fiber _after_ render has completed. This is because React maintains a stack of context values during render, but by the time DevTools is called– render has finished and the stack is empty.
