### ISSUE TITLE
Bug: react-hooks/exhaustive-deps incorrectly considers synchronous access of outer scope that isn't in the dependency list to be a violation

### ISSUE THREAD

**Issue by steve-taylor** [facebook/react#22743]
React version: 17.0.2

## Steps To Reproduce

1. Implement the `react-hooks/exhaustive-deps` ESLint rule.
2. Create a `useEffect` function that doesn't include synchronously accessed identifiers from the outer scope.

Link to code example: https://codesandbox.io/s/beautiful-kalam-q0dwu?file=/src/MyComponent.tsx

## The current behavior

Consider this contrived example:

```jsx
type Props = {
  trigger: boolean
  numbers: number[]
}

function MyComponent({trigger, numbers}: Props) {
  const [sum, setSum] = useState<number>()

  useEffect(() => {
    setSum(numbers.reduce((a, b) => a + b, 0))
  }, [trigger])

  return sum === undefined ? null : (
    <div>
      The sum of the numbers is {sum}.
    </div>
  )
}
```

The callback passed to `useEffect` always accesses the latest version of `numbers`, not a stale copy. This is because when `trigger` changes, the _latest_ version of the callback is invoked, which closes over the _latest_ version of `numbers`.

However, `react-hooks/exhaustive-deps` doesn't recognize that `numbers` is never stale when used in the callback. This rule could easily distinguish between safe and unsafe access: All synchronous accesses are safe. Asynchronous accesses are potentially unsafe. The easy way to distinguish between synchronous and asynchronous accesses is to look at whether the access is occurring directly in the function passed to `useEffect` (synchronous and safe) or within a function inside that function (asynchronous and potentially unsafe).

The `react-hooks/exhaustive-deps` rule provides good protection against stale references in `useMemo` and `useCallback`, but in both those hooks, the dependency list has only one purpose: Avoid stale references. The `useEffect` hook has an additional purpose: Trigger the effect callback. So the `react-hooks/exhaustive-deps` rule in its current form is not well suited to `useEffect`. This violation of the single responsibility principle causes countless bugs which `react-hooks/exhaustive-deps` often makes worse in its current form, by prompting developers to add items to the effect list that shouldn't trigger the effect.

## The expected behavior

The `react-hooks/exhaustive-deps` rule should not consider synchronously accessed outer scope within the function passed to `useEffect` to be a violation.

**Comment by vkurchatkin** [comment]
> The callback passed to useEffect always accesses the latest version of numbers, not a stale copy. 

Well, that is true, but in that sense the callback always accesses latest values when it is called. There is literally no way to run the callback with "stale" values. 

The point is that effect _applies_ these values in some way to the environment and `react-hooks/exhaustive-deps` ensures that latest values are always applied. This has nothing to do whether it is used synchronously or asynchronously.

In fact, your example is the perfect demonstration, why this rule is needed:

```js
 const [sum, setSum] = useState<number>()

  useEffect(() => {
    setSum(numbers.reduce((a, b) => a + b, 0))
  }, [trigger])
```

What if `numbers` changes, but `trigger` doesn't? Well, `sum` is not going to contain the sum of `numbers` anymore.

**Comment by steve-taylor** [comment]
> In fact, your example is the perfect demonstration, why this rule is needed:
> 
> ```js
>  const [sum, setSum] = useState<number>()
> 
>   useEffect(() => {
>     setSum(numbers.reduce((a, b) => a + b, 0))
>   }, [trigger])
> ```
> 
> What if `numbers` changes, but `trigger` doesn't? Well, `sum` is not going to contain the sum of `numbers` anymore.

Please note that my example is contrived, as stated above. If the requirement was to have `sum` up-to-date _at all times_, I would have used `useMemo`.

There exist many real world scenarios in which there is a distinction between trigger values and dependent values. For example, `useEffect` is typically used for calling API endpoints when specific props or state change. In order to build the request payload, various other props and state are required, but those props and state shouldn't necessarily trigger the API call.

This scenario is what RxJS's [withLatestFrom](https://rxjs.dev/api/operators/withLatestFrom) operator was created for:

```js
observableThatTriggersAnEvent$.withLatestFrom(
    observableThatDoesntTriggerAnEvent$,
    anotherObservableThatDoesntTriggerAnEvent$,
).subscribe(([
    valueThatTriggersAnEvent,
    valueThatDoesntTriggerAnEvent,
    anotherValueThatDoesntTriggerAnEvent,
]) => {
    // This executes only when valueThatTriggersAnEvent has changed, but it has access to the latest values of
    // valueThatDoesntTriggerAnEvent and anotherValueThatDoesntTriggerAnEvent.
})
```

The equivalent in React would be

```js
const [valueThatTriggersAnEvent, setValueThatTriggersAnEvent] = useState()
const [valueThatDoesntTriggerAnEvent, setValueThatDoesntTriggerAnEvent] = useState()
const [anotherValueThatDoesntTriggerAnEvent, setAnotherValueThatDoesntTriggerAnEvent] = useState()

useEffect(() => {
    // This executes only when valueThatTriggersAnEvent has changed, but it has access to the latest values of
    // valueThatDoesntTriggerAnEvent and anotherValueThatDoesntTriggerAnEvent.
}, [valueThatTriggersAnEvent]) // incorrect react-hooks/exhaustive-deps violation
```

**Comment by steve-taylor** [comment]
Like RxJS, SolidJS also explicitly separates side effect triggers from dependencies, with `on`.

The last React snippet in SolidJS becomes

```js
const [valueThatTriggersAnEvent, setValueThatTriggersAnEvent] = createSignal()
const [valueThatDoesntTriggerAnEvent, setValueThatDoesntTriggerAnEvent] = createSignal()
const [anotherValueThatDoesntTriggerAnEvent, setAnotherValueThatDoesntTriggerAnEvent] = createSignal()

createEffect(on(valueThatTriggersAnEvent, valueThatTriggersAnEvent => {
    // To read values:
    //   - valueThatTriggersAnEvent
    //   - valueThatDoesntTriggerAnEvent()
    //   - anotherValueThatDoesntTriggerAnEvent()
}))
```

**Comment by lubieowoce** [comment]
I agree with the spirit of request -- I've written code that does stuff like this. But i don't think there's any way for a linter to possibly know that we *meant* to write it this way, and didn't just forget to add `numbers`.

If you want to communicate the intent, maybe just do something like this, and bypass the linter rule altogether?
Could be more readable to human readers too ;)
```js
/**
* A version of useEffect for when you explicitly *want* to omit something from the dependencies
**/
const useEffectWithTrigger = useEffect
```

**Comment by steve-taylor** [comment]
> But i don't think there's any way for a linter to possibly know that we meant to write it this way, and didn't just forget to add `numbers`.

In the more real world scenario of making API calls, you don't want the linter to help you decide what should trigger the side effect. Its job isn't to validate your requirements. You just want it to save you from stale references. For `useEffect`, that's all the linter should do. And it can do that by ensuring external scope referenced inside the callback is either referenced only at the top level of the callback (i.e. not in a nested callback) or is in the dependency list.

**Comment by lubieowoce** [comment]
i understand! seriously! i understand closures, and in the past two months i've written at least three `//eslint-disable-next-line react-hooks/exhaustive-deps` for this exact reason!

but since

- the linter *can't know if you meant it or if it's a bug*
- the ruleset tends to err on the side of caution (better to have false positives than false negatives)

... i think it's unlikely it'll get changed. and i don't see any sort of middle ground here, other than "aliasing useEffect" like i described in my previous comment. i understand this may not be satisfying to you 😉 if you search for `exhaustive-deps` in the issue tracker, there's a number of similar ones that's popped up, proposing changes to `useEffect` etc, maybe one of those will work for you.

---

i thought I'd explain a bit more about what i mean by "the linter can't know". if you look at these two examples

```
// let's log both whenever `a` or `b` changes
useEffect(() => log(a, b), [a]);

// let's log both whenever `a` changes
useEffect(() => log(a, b), [a]);
```

you'll notice the code is exactly the same in both. except one won't do what the comment says. so that one's probably a bug, the other one is probably intentional. but there's no way to know this "mechanically".

**Comment by irinakk** [comment]
> The easy way to distinguish between synchronous and asynchronous accesses is to look at whether the access is occurring directly in the function passed to useEffect (synchronous and safe) or within a function inside that function (asynchronous and potentially unsafe).
This is not true, because the source of the deps may be unknown.

If you don't rely on a dependency for updates, you can use an extra ref to store it.

**Comment by steve-taylor** [comment]
> you'll notice the code is exactly the same in both. except one won't do what the comment says. so that one's probably a bug, the other one is probably intentional. but there's no way to know this "mechanically". so the linter assumes it's a bug in both cases, because let's face it, it _usually_ is.

In both cases, neither `a` nor `b` are stale references where they are used. So the eslint rule isn’t saving you from stale references.

There should at least be an option to treat `useEffect` differently because it _is_ different.

**Comment by apples** [comment]
This isn't a bug. The linter rule is doing its job. It is not designed to prevent stale references *within* the effect, it is designed to prevent stale references from *outside* the effect (and possibly outside of the component entirely).

The React docs even have a [huge note](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect) about this, along with some specific [recommendations](https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often) on how to remedy the issue.

The best way to avoid this linter error will vary based on what exactly you are trying to accomplish. In general, a good solution is to do what the linter says and properly list all the deps, and then separately check for the `trigger` values from within the effect (possibly with a `useRef` to keep track of the previous values).

**Comment by steve-taylor** [comment]
The following assertion is the essence of this issue which, if disproven with just one counter-example, means I close this issue:

> It is _impossible_ to reference stale component-level constants (including props and state) from directly within a `useEffect` callback. References to component-level scope directly from the callback passed to `useEffect` are _never_ out of date, regardless of their presence in the dependency list passed to the same invocation of `useEffect`.

Time for me to eat some humble pie. Here's my counter example:

```js
const handleResponse = useCallback(response => {
    // Handle response here
}, [someProp, anotherProp])

useEffect(() => {
    const subscription = invokeSomeEndpoint(trigger1)
        .pipe(withLatestFrom(of(handleSomething)))
        .subscribe({
            next: ([response, handle]) => {
                // handle is the same as handleResponse, but may be stale at this point
                handle(response)
            }
        })

    return () => subscription.unsubscribe()
}, [trigger1, trigger2])
```

Essentially, synchronously referenced component-level scope may be passed to another function, appear somewhere else _asynchronously_, and then be referenced from there. If the `react-hooks/exhaustive-deps` rule was relaxed as I have proposed here, `handleResponse` needn't be included in `useEffect`'s dependency list, but `react-hooks/exhaustive-deps` wouldn't be able to detect its asynchronous usage.

On that basis, I'm closing this issue.

The real issue, then, is React's relatively unsophisticated *React*ivity.
