### ISSUE TITLE
Bug: markInternalModuleRanges undefined

### ISSUE THREAD

**Issue by crodriguez-plitzi** [facebook/react#22747]
Testing react 18 im getting this error 

![Screenshot from 2021-11-12 07-33-44](https://user-images.githubusercontent.com/86263126/141428205-3f3b3f67-e235-44ef-ae1a-5c42e4f7800a.png)

React version: https://unpkg.com/react-dom@18.0.0-alpha-a44a7a2a3-20211111/umd/react-dom.development.js

wants to add that in this version: https://unpkg.com/react-dom@18.0.0-alpha-05726d72c-20210927/umd/react-dom.development.js no happens, so probably a recent change affected this

File Related: https://github.com/facebook/react/blob/1bf6deb865052111474f2988bb831de13d09c560/packages/react-reconciler/src/SchedulingProfiler.js

## Steps To Reproduce

cant reproduce this for the moment, happens randomly and had to downgrade the version

Link to code example:

cant reproduce it, happens randomly

## The current behavior

in some cases is undefined

## The expected behavior

should not be undefined

**Comment by bvaughn** [comment]
@crodriguez-plitzi Can you tell me more about the cases when you're able to repro it (or give me a link to a page where it happens, even if only sometimes)? Do you have React DevTools installed? Does it happen in a particular browser or device?

**Comment by bvaughn** [comment]
@crodriguez-plitzi Can you try this build of react-dom and tell me if it fixes the problem for you?

https://gist.githubusercontent.com/bvaughn/7eb07ebd45aabae603086ad544f917bc/raw/d35273000314deecdd9ec8a2a2adc448b3635a48/react-dom.development.js

**Comment by crodriguez-plitzi** [comment]
@bvaughn give me 5 mins to test it

**Comment by bvaughn** [comment]
Sure thing! :)

I'm pretty curious what's going on here. It seems unlikely that something else would be overriding the DevTools hook and injecting its own implementation of `getInternalModuleRanges` but looking at the code, that's my best idea at the moment.

Regardless, hopefully the updated build I shared will fix it.

**Comment by crodriguez-plitzi** [comment]
@bvaughn cant use it because is not UMD, i am using the CDN 

    <script crossorigin src="https://unpkg.com/react-dom@alpha/umd/react-dom.development.js"></script>
    
    but reading the code im pretty sure will works because ranges was coming undefined

**Comment by bvaughn** [comment]
Gotcha.

In that case, I'll merge the fix and you can verify it tomorrow when the next alpha release is published.

**Comment by crodriguez-plitzi** [comment]
@bvaughn thanks friend could be interesting to investigate why randomly got undefined, but i was not able to reproduce it, i just think that can be related to iframes and createPortal but im not sure
