### ISSUE TITLE
Suggestion for React

### ISSUE THREAD

**Issue by rattleSSnake** [facebook/react#22775]
Hello,
I would very much appreciate that future versions of React use "_modern"_ javascript. To that I am particularly referring to the use of `var` instead of `let` or `const` in react compiled code. With ES6, `var` has been considered bad practice and can sometimes cause issues because it is not blocked scoped.  

I understand my lack of knowledge on how react is built and (maybe) `var` is still necesssary.
But if not, why stick with old technology when new one is available ;) ?

Thank you very much for your consideration,
Thomas

**Comment by bvaughn** [comment]
Thank you for the feedback.

I'm going to close this issue since it's not really something that needs answering or discussing. 🙇🏼

**Comment by rattleSSnake** [comment]
> Thank you for the feedback.
> 
> I'm going to close this issue since it's not really something that needs answering or discussing. 🙇🏼

Yes please delete this closed issue, thanks
