### ISSUE TITLE
Timeline view search

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#22776]
If I'm looking for a specific component render in the Timeline view, it can be hard to find it. It would be nice if there was a search feature that would automatically zoom in on the component (matching by name).

**Comment by bvaughn** [comment]
We might start with a simple search (that matches component names only) and expand to a more complicated search that lets you search by event type, suspended resource name, component name, etc.

**Comment by gaearon** [comment]
Unrelated but one thing I really like in the Profiler is having components highlight on flamechart hover. Can Timeline also do this (for markers like state updates / suspending, and for flamechart).

**Comment by bvaughn** [comment]
Unfortunately, not in its current implementation. (There isn't sufficient data to tie a component to a Fiber.)

Result of #22529 should enable this possibility though.
