### ISSUE TITLE
Library compatible since hooks, should it be `"^16.8.0 || ^17.0.0 || ^18.0.0"` or `">=16.8"`?

### ISSUE THREAD

**Issue by franciscop** [facebook/react#22795]
In React 16.x, which was fairly long lived and had breaking changes with previous versions, it used to be common to declare the React dependency (e.g. for a hooks library) like this to support all 16.x versions:

```
"peerDependencies": {
  "react": "^16.8.0"
}
```

When React 17 came up, I've had to update all my React libraries and republish them like this:

```
"peerDependencies": {
  "react": "^16.8.0 || ^17.0.0"
}
```

It seems like React is accelerating the major versioning release rate without actually breaking the API, so is there a recommended way that we define our versioning in the future? I maintain over half a dozen React libraries, and needing to re-publish them adding `"^16.8.0 || ^17.0.0 || ^18.0.0"` (once again, when there were virtually no other changes for 1~2 years in those libraries) seems like unnecessary work when I'm using very mainstream APIs and none of the experimental ones. I'm tempted to do this but I understand if React at some point does break the main APIs it'd be bad:

```
"peerDependencies": {
  "react": ">=16.8.0"
}
```

So, if I publish a React library that supports hooks and everything since then, including React 17 and 18, **what does Facebook React team recommend? Using `"^16.8.0 || ^17.0.0 || ^18.0.0"` or `">=16.8.0"`?** Within the context of someone supporting many small React libraries.

**Comment by markerikson** [comment]
`^16.8` won't cover the other versions, because the `^` semver operator only works within a single major:

https://nodesource.com/blog/semver-tilde-and-caret/

So yes, if a lib is compat with "any React that has hooks", you need to list each major separately.

(FWIW, for React-Redux v8, I'm doing exactly that, although listing `^16.9.0` on the grounds that 16.8 had a known bug with one of its APIs that was fixed in 16.9, even if it wasn't related to hooks specifically)

**Comment by franciscop** [comment]
Sorry @markerikson I never wrote `^16.8` (besides to show how it used to be done back in the day), I am comparing both in the title and main question `">=16.8.0"` vs `"^16.8.0 || ^17.0.0 || ^18.0.0"`

**Comment by franciscop** [comment]
I guess my problem is mainly with React 18 breaking SemVer and making what seems like unnecessary work for devs:

> Since concurrency in React 18 is opt-in, there are no significant out-of-the-box breaking changes to component behavior.

I want my libraries to be "done", and only have to update them if there's potential for any issue. In this situation, needing to go through my libraries and update/publish a new version of all of them/year without a potential for a breaking change feels onerous and that's why I believe it's possibly a React-specific issue.

That, plus potentially the issue of not being able to keyword search my own username in npm makes maintaining React npm libraries tricky (I have 86 JS libraries).

**Comment by markerikson** [comment]
I'm... confused. What do you mean by "React 18 breaking semver"?

If you're complaining that there's a "React 18.0 without any breaking changes that would justify a major version": there _are_ changes in React 18 that qualify as "breaking", and it _is_ a valid major version.  But, the React team is doing their best to keep most runtime code working as-is.  At the same time, there is also a major paradigm shift in how some of the behavior of React works even if your app code isn't any different.

How you manage publishing your own libraries is up to you.

**Comment by franciscop** [comment]
Yes, I meant that it's published with no breaking changes as per the quote above from the React team, as seems like it happened with React 17. As a developer using React, I appreciate it, but maintaining libraries becomes more difficult.

What are those breaking changes? I couldn't find them after I searched, or do you mean there are only internal breaking changes and somehow that doesn't translate in any public-API breaking changes?

**Comment by markerikson** [comment]
Some examples:

- https://github.com/reactwg/react-18/discussions/7
- https://github.com/reactwg/react-18/discussions/21

Plus things like Concurrent Rendering in general, where there is a behavioral change in React that may cause existing code to not work correctly even if it runs without apparent bugs right now.

**Comment by franciscop** [comment]
Thanks for the explanation!
