### ISSUE TITLE
Bug: Error checking code is skipped for async useEffect argument

### ISSUE THREAD

**Issue by ChristopherPAndrews** [facebook/react#22809]
React no longer complains when the function passed to `useEffect` returns a Promise (either directly or by being labeled `async`). I'm not in the habit of doing this, so it was only when I watched someone else make the function `async` and there were no errors that I realized that something had changed since 6.13.1 (the newest version I could find that still complained).

I can see the functionality is still present in `commitHookEffectListMount` in react-dom.development.js, but when I trace through it, the `effect.tag` is set to a different value and the test is skipped.

I realize that we now have an ESLint rule that provides the same message, but the lack of warning caused confusion about whether asynchronous functions were now allowed. 

React version: 17.0.2 

## Steps To Reproduce

1. Write a `useEffect` that has an `async` function
2. Open the console and observe that it doesn't complain

Link to code example: https://codesandbox.io/s/winter-wind-l33bi

## The current behavior
The code runs with no complaints, and the cleaner function is ignored. 

## The expected behavior
The console should show the warning:

```
Warning: An effect function must not return anything besides a function, which is used for clean-up.

It looks like you wrote useEffect(async () => ...) or returned a Promise. Instead, write the async function inside your effect and call it immediately:

useEffect(() => {
  async function fetchData() {
    // You can await here
    const response = await MyAPI.getData(someId);
    // ...
  }
  fetchData();
}, [someId]); // Or [] if effect doesn't need props or state
```

**Comment by eps1lon** [comment]
Thanks for the report. 

The bug is already fixed for React 18. In React 17 you only get the warning for `useLayoutEffect`. See https://github.com/reactwg/react-18/discussions/95 and specifically https://github.com/reactwg/react-18/discussions/95#discussioncomment-1293608.
