### ISSUE TITLE
[DevTools Bug]: Scheduling Profiler Tab Doesn't Show Up In DevTools

### ISSUE THREAD

**Issue by Moshyfawn** [facebook/react#22800]
### Website or app

https://codesandbox.io/s/react-18-sandbox-0w6uk

### Repro steps

1. Open [this codesandbox](https://codesandbox.io/s/react-18-sandbox-0w6uk)
2. Open the app in new window
3. Open Profiler tab of the React DevTools _(ver 4.21.0-2f8f60ca8)_
4. See no Scheduling Profiler icon
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16290753/142763716-2c814adb-1ee7-40b6-aea5-a2e35c5c3d02.png">

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.21.0-2f8f60ca8

**Comment by bvaughn** [comment]
The Timeline profiler only supports Chrome for the time being. Sorry for the confusion. 🙇🏼
