### ISSUE TITLE
provide deferUpdate method (feature request)

### ISSUE THREAD

**Issue by rattrayalex** [facebook/react#2280]
Hi, 

The Flux architecture seems to recommend having React elements bind to change event listeners to Stores, and call `forceUpdate()` when changes occur. I do this, and generally find that deferring forceUpdate calls is more useful, as it prevents multiple calls to forceUpdate on the same tick (I think). 

The idea comes from [react-mixin-manager](https://github.com/jhudson8/react-mixin-manager#deferupdate), which provides one implementation. 

Personally, I have seen a performance boost (I think) from using the following simple mixin: 

```coffee
module.exports =
  deferUpdate: ->
    setTimeout =>
      @forceUpdate()
    , 0
``` 

I'm not sure if this is a good idea generally, or if it should be incorporated into React core, but I thought I'd throw it out there. 
(meta: are issues like this encouraged or frowned upon here? I know it's a large project with a lot of "real" issues the core devs need to be paying attention to.)

**Comment by gaearon** [comment]
We currently batch multiple `setState()` calls made in a DOM event handler so in most cases calling it multiple times shouldn’t be an issue. We don’t recommend `forceUpdate()` and instead recommend you to use `setState()`, immutable values, and shallow equality checks in `shouldComponentUpdate()` for best performance. Of course you should only optimize perf once you find specific bottlenecks. [This](http://benchling.engineering/performance-engineering-with-react/) is a good guide on that. In the future, we might move to batching `setState()` calls outside DOM event handlers as well.

I hope this helps! I don’t see anything actionable here so I’m closing but please feel free to continue the discussion.
