### ISSUE TITLE
React 18 It possible that automatic batching work when using await that like `await false`?

### ISSUE THREAD

**Issue by xiejay97** [facebook/react#22811]
We often use `async` to implement asynchronous operations. But automatic batching dont work when using await that like `await false` .

[example](https://codesandbox.io/s/pedantic-hodgkin-3l47z?file=/src/index.js)

**Comment by karol-janik** [comment]
What is the reason to use `await` with function that doesn't return `Promise`? 🤔

**Comment by xiejay97** [comment]
> What is the reason to use `await` with function that doesn't return `Promise`? 🤔
In fact, we can handle `Promise` and `No Promise` separately, but many extra codes will be added.

**Comment by irinakk** [comment]
you may take a look at [startTransition](https://github.com/reactwg/react-18/discussions/41)

**Comment by irinakk** [comment]
You can take a look at [startTransition](https://github.com/reactwg/react-18/discussions/41)

**Comment by bvaughn** [comment]
This looks like a substantial change being proposed. :smile: Changes like this should go through our RFC process:
https://github.com/reactjs/rfcs#react-rfcs

The RFC process is a great opportunity to get more eyeballs on your proposal before it becomes a part of a released version of React. Quite often, even proposals that seem "obvious" can be significantly improved once a wider group of interested people have a chance to weigh in.

The RFC process can also be helpful to encourage discussions about a proposed feature as it is being designed, and incorporate important constraints into the design while it's easier to change, before the design has been fully implemented.

**Comment by irinakk** [comment]
@xiejay97 This comes from how you "schedules" the work. but why you want to batch those two updates? does the change of state trigger some slow rendering? if so, you can take a look at [startTransition](https://github.com/reactwg/react-18/discussions/41), or just make the synchronous work synchronous.

**Comment by xiejay97** [comment]
> @xiejay97 This comes from how you "schedules" the work. but why you want to batch those two updates? does the change of state trigger some slow rendering? if so, you can take a look at [startTransition](https://github.com/reactwg/react-18/discussions/41), or just make the synchronous work synchronous.

@irinakk The automatic batching is really good for handle original DOM(such as `getBoundingClientRect`), before React 18, we must be handled carefully because setState in asynchronous always cause to rerender(it may change original DOM) . Thanks to automatic batching, I no longer need to think about these, except `await false` :joy_cat:

**Comment by xiejay97** [comment]
> startTransition

`startTransition` is also amazing feature, but it just for less urgent update.
