### ISSUE TITLE
Bug: The results of the useState of the Event parameter are different in react17.0.0 and react16.

### ISSUE THREAD

**Issue by gryhan** [facebook/react#22826]
React version:17.0.0

## Steps To Reproduce

1.The running results of this code are different in react17.0.0 and react16.*.*

`
import {useState} from 'react';

function Demo01() {
    const [myEvent, setMyEvent] = useState({});

    function handleClick(e) {
        setMyEvent(e)
    }

    return (
        <>
            <button onClick={handleClick}>Click it!</button>
            Result: {JSON.stringify(myEvent.type)}
        </>
    );
}

export default Demo01
`

2.The running results of react17.0.0:

![react17](https://user-images.githubusercontent.com/50402939/143370659-73e7a944-0409-4e6f-a824-197c5e618cf7.PNG)

3.The running results of react16:

![react16](https://user-images.githubusercontent.com/50402939/143370611-95357bca-2afd-47f6-b1a6-bb2b5f08671c.PNG)

## The current behavior

The running results are different in react17.0.0 and react16.*.*

## The expected behavior

The running results in react17.0.0 and react16 should be the same.

**Comment by gaearon** [comment]
This is expected and aligns closer to how native browser events work.

https://reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling

**Comment by gryhan** [comment]
thank you very much.
