### ISSUE TITLE
Bug: Save "resolve" and "reject" to useState will let Promise auto resolved.

### ISSUE THREAD

**Issue by yoyogis** [facebook/react#22822]
React version: 17.0.2

## Steps To Reproduce

1. create a Promise and save the resolve & reject function into  state by useState
2.

Link to code example: https://codesandbox.io/s/infallible-elbakyan-v63em?file=/src/App.tsx

## The current behavior
The promise will be auto resolved

## The expected behavior
The promise be resolved when I run resolve function.

**Comment by irinakk** [comment]
Because this triggers [functional updates](https://reactjs.org/docs/hooks-reference.html#functional-updates)

**Comment by yoyogis** [comment]
thank you @irinakk 

Use an object to save the "reject" and "resolve"  https://codesandbox.io/s/objective-kate-s1dbf?file=/src/App.tsx
