### ISSUE TITLE
React 18: Unexpected component unmounting in Strict Mode

### ISSUE THREAD

**Issue by TkDodo** [facebook/react#22839]
This is an issue I've come across when trying to upgrade react-query to v18.

A minimal reproduction would be [this codesandbox](https://codesandbox.io/s/unmount-issue-2fec5?file=/src/App.js)

**Expected behavior**

The component should mount, render with `count 1`, then after one second update to `count 2`

**Actual behavior**

The component mounts, renders with `count 1`, then after one second update to `count 3`. You can also observe that the component unmounts in between (the cleanup function of the useEffect runs, see the console log) and then mounts again (the effect runs again).

**Context**

react-query subscribes / unsubscribes observers when components mount, and this behavior can lead to bugs, like retries being cancelled if the observer unmounts in between. I could reproduce this with either the latest v3 version of react-query, where we subscribe / unsubscribe in a useEffect, as well as with the version that attempts to upgrade to `useSyncExternalStorage`.

**Workarounds**

Issue does _not_ show up if:

- you use `ReactDOM.render` instead of `createRoot`
- you remove `<React.StrictMode>` from the sandbox

**Related**

not sure if this issue is really related, but I found it before opening this issue. It doesn't have much information in it though:
- https://github.com/facebook/react/issues/21674

**Comment by irinakk** [comment]
This behaviour is related to [strict effects](https://github.com/reactwg/react-18/discussions/19)

**Comment by TkDodo** [comment]
Thanks, I've read about that now. I'm actually fine with the behaviour when it comes to offscreen behavior, and I think it would fit the react-query usecase quite well - treat coming into view the same as a new mount, thus triggering a re-fetch. 

I will stick to asking further questions in the discussion 👍

**Comment by gaearon** [comment]
Keep in mind we also re-trigger effects on every Fast Refresh so that's another reason to be resilient to re-triggers.

**Comment by TkDodo** [comment]
> Keep in mind we also re-trigger effects on every Fast Refresh so that's another reason to be resilient to re-triggers.

Thats also a case I would be fine with. User writes a component with a query, the query fires, user goes to IDE, changes some code, fast refresh re-loads, query refetches. not the worst DX.

but the case were you write a component with a query and see two fetches going out is a bit 🤯. I've tried to explain the use-case and why I don't see a good fix at the moment here:
- https://github.com/reactwg/react-18/discussions/18#discussioncomment-1708972
