### ISSUE TITLE
Term "use" in non-hook functions

### ISSUE THREAD

**Issue by kasugaicrow** [facebook/react#22844]
Hi,

I have defined a function called `useAuthInfo` that's not actually a hook, it's a simple promise. I tried to use it inside `React.useEffect` but I got this error:
```
React Hook "useAuthInfo" cannot be called inside a callback. 
React Hooks must be called in a React function component or a custom React Hook function. (react-hooks/rules-of-hooks)
```
I repeat, that function **is not** a hook (as you can see in the sanbox); as a matter of fact, if I change the name of that function with `authInfo` everything works fine.
Am I missing something or I just can't use the term _use_ inside a non-hook function name?

React version: **17.0.2**

## Steps To Reproduce

1. Define a function with the term _use_ in it, like _useTest_
2. Use the function inside `React.useEffect`

Link to code example:
https://codesandbox.io/s/zealous-tereshkova-zepy5

## The current behavior

The _react-hooks/rules-of-hooks_ error is returned

## The expected behavior

The _react-hooks/rules-of-hooks_ error is not returned

**Comment by vkurchatkin** [comment]
> Am I missing something or I just can't use the term use inside a non-hook function name?

Yes, basically. As a convention, linter rules are going to consider all functions starting with `use` hooks.

**Comment by kasugaicrow** [comment]
Ok cool, I didn't think it could be a convention so I searched the internet only by the error. Now I found out the documentation section about it.

Thank you!
