### ISSUE TITLE
[Suggestion] Throw Circular Reference Error

### ISSUE THREAD

**Issue by iJynx** [facebook/react#22843]
I just spent >20min wondering why my page was hanging. Turns out I had referenced the component I was rendering in the return method.

I know it's a stupid mistake however to prevent more time being wasted on it I propose a circular reference check which should throw an error. 

I may work on a pull request later if I have time and it hasn't been patched yet.

**Comment by vkurchatkin** [comment]
It is quite literally impossible to perform such a check in any way

**Comment by nmain** [comment]
Duplicate of https://github.com/facebook/react/issues/12525
