### ISSUE TITLE
Bug: React App refuses to run when changed it's root file from C: drive to D: drive

### ISSUE THREAD

**Issue by The-dev-Sirmed** [facebook/react#22842]
React version: ^17.0.2

## Steps To Reproduce

1. Create a react app using **npx create-react-app <app-name>** in your C: drive
2. Move it's folder to your D: drive, for example, let's assign a name to it, app. Copy your **app** and go to your D: drive, paste it there. Using your VS Code terminal (assuming you use it) go to your directory, **cd app** and then run **npm start**. Wait for it to load it in browser. When it loads, you will get an error screen stating **EPERM: operation not permitted, open 'D:\VS Code\React Apps\app\node_modules\.cache\.eslintcache'**

Dependencies(that ive installed): iconsax, firebase
Link to code example: _Any code will work_

## The current behavior
![image](https://user-images.githubusercontent.com/77951240/143765919-93809e25-f970-448b-9f45-e94eace5115e.png)

## The expected behavior
You should not see the error screen

**Comment by akgupta0777** [comment]
Friendly Advice:
Don't copy or move the whole folder from C: to D: 
copy or move everything except the `node_modules`. Instead copy source and node package files

Now what you need to do
Try deleting the `node_modules`
run `npm install` inside `D:\VS Code\React Apps\app\`
run `yarn start`.

**Comment by lunaruan** [comment]
Hey! Thanks for reporting this issue. This isn't a react specific bug, so I'm closing this.
