### ISSUE TITLE
Bug: Clicking button type="button" submits form

### ISSUE THREAD

**Issue by tamlyn** [facebook/react#22849]
React version: tested in `16.13.1`, `17.0.2`, and `18.0.0-beta-a65ceef37-20211130`

## Steps To Reproduce

1. Click a button `type=button`
2. Cause a rerender where that same DOM button will be converted into a button `type=submit`
3. Observe that any form linked to the submit button is submitted, even though the submit button was never clicked

Adding a `key` to force a remount circumvents the issue, but it still seems very unexpected.

## Example component

```
const App = () => {
  const [showForm, setShowForm] = React.useState(false);

  if (showForm) {
    return (
      <div>
        <div>
          <form
            id="form"
            onSubmit={(e) => {
              e.preventDefault();
              console.log("form submitted");
            }}
          >
            <p>
              Why was this form submitted? It didn't even exist when the "Show
              form" button was clicked.
            </p>
          </form>
        </div>

        <button
          form="form"
          type="submit"
          onClick={() => console.log("submit clicked")}
        >
          Submit
        </button>
      </div>
    );
  }

  return (
    <div>
      <div></div>
      <button type="button" onClick={() => setShowForm(true)}>
        Show form
      </button>
    </div>
  );
};
```

## Live examples
- [Example 1](https://codepen.io/tamlyn/pen/qBPEvLr) - the form is submitted even though it doesn't exist in the DOM at the time of the click
- [Example 2](https://codepen.io/tamlyn/pen/vYeEJRb) - simpler example where wrong form is submitted

**Comment by lunaruan** [comment]
@acdlite Seems like this is a bug with the event system

**Comment by gaearon** [comment]
@tamlyn If you create a DOM button without React and change its type during the click handler, does this also happen? Can you try making one? We usually need this to narrow down if something is a browser issue or a React bug.

**Comment by zgoby** [comment]
```
export default function App() {
  const [showForm, setShowForm] = useState(false);
  if (showForm) {
    return (
      <form
        onSubmit={(e) => {
          e.preventDefault();
          console.log("form 2 submitted");
        }}
        key="f1"
      >
      <>
        <p>Check the console and see that the wrong form was submitted</p>
        <button type="submit" onClick={() => console.log("submit clicked")}>
          Submit?
        </button>
      </>
      </form>
    );
  }

  return (
    <form
    key="f2"
    onSubmit={(e) => {e.preventDefault();console.log("form 1 submitted")}}>
      <p>This button submits the wrong form</p>
      <button type="submit" onClick={() => setShowForm(true)}>
        Show form
      </button>
    </form>
  );
};
```
The form with key is expected,it show "Form submission canceled because the form is not connected" on the pane of the console.It look like event system is slower than dom updatting.it's right?

**Comment by aini10000** [comment]
你好，我将尽快给你回复。

**Comment by Firefan** [comment]
您好，邮件已收到，我查阅后尽快给您回复！

**Comment by ideffix** [comment]
Hi, if this issue is free to take I would like to dig in :)

**Comment by tamlyn** [comment]
> If you create a DOM button without React and change its type during the click handler, does this also happen? 

@gaearon Yes, it does 😱 https://codepen.io/tamlyn/pen/BawKjrV – I guess that means this is a browser issue?

**Comment by gaearon** [comment]
I’d expect so, yes.

**Comment by gaearon** [comment]
I think this means we can close. Either this behavior is in spec or it’s a browser bug (so you’d need to report it).
