### ISSUE TITLE
Bug: `Suspense` doesn't render `fallback` component at all

### ISSUE THREAD

**Issue by Iipal** [facebook/react#22859]
On route change `fallback` component doesn't render:
```js
<Suspense fallback={<Loader />}>
  <Routes location={location} key={location.pathname}>
    <Route path={"/1"} element={<Comp1 />} />
    <Route path={"/2"} element={<Comp2 />} />
  </Routes>
</Suspense>
```
React version: 17.0.2

## Steps To Reproduce
Shown in code example below

Link to code example:
https://codesandbox.io/s/admiring-merkle-g5q95?file=/src/App.tsx

## The current behavior
On route change `Suspense` doesn't render the `fallback` component

## The expected behavior
Render the `fallback`

**Comment by gaearon** [comment]
You are using a third party library called `@loadable/component`. This library probably is not integrated with Suspense, or maybe there's an option to enable that integration.

With built-in `React.lazy` it works: https://codesandbox.io/s/prod-currying-thqyq

**Comment by Iipal** [comment]
@gaearon Thanks a lot!
