### ISSUE TITLE
React does not recognize the `maskType` prop on a DOM element

### ISSUE THREAD

**Issue by zprjk** [facebook/react#22850]
React version: 17

## Steps To Reproduce

1. Create a Inline SVG with a `mask`
2. Use `maskType` as a svg attribute in the said `mask`
3. Check React `warning` in console.

### Link to code example:
https://codesandbox.io/s/react-does-not-recognize-the-masktype-6r344

Related discussion: https://github.com/gregberge/svgr/issues/643
https://www.w3.org/TR/css-masking-1/#propdef-mask-type

**Comment by eps1lon** [comment]
Thanks for the report.

I couldn't find any mention of a `masktype` **attribute**. The only mention I could find is the [`maskType` **CSS property**](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-type) which is not necessarily set via props as far as I know but styles.

Could you clarify where this attribute is specified or which browsers implement it?

**Comment by zprjk** [comment]
Hey @eps1lon . I think you are right. Closing this one.

(I'll continue the follow up in the other thread that's not related to React, over here: https://github.com/gregberge/svgr/issues/643#issuecomment-984169319)
