### ISSUE TITLE
Why React change keys with dot dollar ? ".$"

### ISSUE THREAD

**Issue by djmisterjon** [facebook/react#22870]
Can we get explanation why all keys are mutate with `.$` by react ?
![image](https://user-images.githubusercontent.com/24865815/144761791-b955ce8a-a3f2-483b-9a6a-93170f22b88d.png)

so we always need a hack like this to extract key ?!
```ts
const { key, type, props } = childnode;
const keyid = ( key as string ).split( '.$' )[1];
```

**Comment by bvaughn** [comment]
React does not set keys. Those come from your application code (or perhaps the 3rd party UI library that you're using). You can learn more about keys here: https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by djmisterjon** [comment]
> React does not set keys. Those come from your application code (or perhaps the 3rd party UI library that you're using). You can learn more about keys here: https://reactjs.org/docs/lists-and-keys.html#keys

Hum weird ! i trying a random **codesandbox** on web 
![image](https://user-images.githubusercontent.com/24865815/144871437-a2e0c425-6d0b-4aa9-97b7-9c67d4e749e2.png)

And it also seem have keys with `.$` 
But the codesandbox seem not have thirdParty UI library !
https://codesandbox.io/s/react-keys-zrthc?from-embed

I'll try to investigate, but it's very weird !

**Comment by bvaughn** [comment]
> But the codesandbox seem not have thirdParty UI library !

The "3rd party code" is the `CSSTransitionGroupChild` component, in this case, coming from [react-addons-css-transition-group](https://npmjs.com/package/react-addons-css-transition-group). This is a pretty old addon library (last published around 4 years ago) and I'm not sure how it works, but it's the thing generating/assigning keys.

**Comment by irinakk** [comment]
This is the result of using `React.Children.toArray` or `React.Children.map`: https://github.com/facebook/react/issues/5541#issuecomment-159425628

**Comment by djmisterjon** [comment]
Haaaa oki thanks a lot for your help
