### ISSUE TITLE
Bug: Call render if set state value same of default value, and then not update View

### ISSUE THREAD

**Issue by zqjimlove** [facebook/react#22875]
React version:

## Steps To Reproduce

1.16.14.0
2.^17

Link to code example:

https://codesandbox.io/s/friendly-lumiere-srnyu

I found that It will call render function 3 times in console, but not update the View after the last times.

## The current behavior

I can't understand why the third render has been called. The `v` state default value is `true` and call `setV(true)` in the `setTimeout`.

## The expected behavior

Shouldn't call render function if set the value of state same of the default value??

**Comment by lunaruan** [comment]
Hey, thanks for reporting this bug! This behavior is intentional. We always rerender if you call `setState`. However, if nothing has changed we will bail out of the render early. Closing this because this behavior is intended.

**Comment by zqjimlove** [comment]
> Hey, thanks for reporting this bug! This behavior is intentional. We always rerender if you call `setState`. However, if nothing has changed we will bail out of the render early. Closing this because this behavior is intended.

Thanks for your comment @lunaruan ，but I don't think that solve my confusion.

> We always rerender if you call setState

I also thought at the beginning that always re-render if call setState, even if `nextState` and `prevState` are both the same value (primitive value).

But i try to use `setInterval` to call `setState` in the loop, Actually executed 3 times re-render.So I don’t agree with always re-render if call setState.

I found just re-render 1 times if i change the code like that:

```jsx
import React, { useEffect, useState } from "react";

let version = 0;

export default () => {
  // const [state, setState] = useState(1);

  // useEffect(() => {
  //   setState(2);
  // }, []);

  const [v, setV] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      version = 1;
      setV(true);
    });
  }, []);

  console.log("state:",  Date.now(), version);

  return (
    <div>
      {version}
    </div>
  );
};
```

Also set the same value to the state,  but not happen re-render.
