### ISSUE TITLE
[DevTools Bug] Could not find node with id "99" in commit tree

### ISSUE THREAD

**Issue by Mozart409** [facebook/react#22871]
### Website or app

https://consumption.coffee/

### Repro steps

1. Visit homepage
2. Start Profiler
3. Visit Coffee Page via navbar
4. Visit Home Page via navbar
5. Boom Error

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.21.0-2f8f60ca8

### Error message (automated)

Could not find node with id "99" in commit tree

### Error component stack (automated)

```text
CommitRankedAutoSizer@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:44375:34
div
div
div
SettingsModalContextController@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:35694:40
Profiler_Profiler@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:52477:34
ErrorBoundary_ErrorBoundary@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:37092:5
div
div
ThemeProvider@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:37221:23
PortaledContent@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:37255:34
div
div
div
ThemeProvider@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:37221:23
SchedulingProfilerContextController@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:43422:45
ProfilerContextController@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:41710:35
TreeContextController@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:30115:31
SettingsContextController@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:30726:35
ModalDialogContextController@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:37634:38
DevTools_DevTools@moz-extension://84945e53-7ac8-3442-9da2-ed4bcec5b8a4/build/main.js:53003:27
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not find node with id  in commit tree in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by lunaruan** [comment]
Hey! Thanks for reporting this error! Do you have a test email/password we can test with so we can repro this bug?

**Comment by aerciyas** [comment]
Can you elaborate on step 2. Start Profiler more? Is it to visit the Profile tab or something.

**Comment by akgupta0777** [comment]
> Can you elaborate on step 2. Start Profiler more? Is it to visit the Profile tab or something.

@aerciyas 
He is talking about the profiler tab on react devtools extension. 
You can open the profiler tab by opening devtools extension's profiler.
See this
![image](https://user-images.githubusercontent.com/51379307/145419615-e6938f83-8eea-4ad1-b38a-4b1a8fd63e76.png)

Hope it helps

**Comment by lunaruan** [comment]
Looking into this more, this is a duplicate issue to #21636. Closing this. Thanks so much for reporting!

**Comment by Mozart409** [comment]
Hey,
sorry for the late reply. I didn't see the notification.
