### ISSUE TITLE
Bug: onMouse leave triggered on hidden components if hovered over before hidden

### ISSUE THREAD

**Issue by lirancr** [facebook/react#22883]
React version: 17.0.2

## Steps To Reproduce

1. Using sample app, hover the mouse over the button
2. Click button
3. notice button have it's visibility set to 'hidden'
4. move mouse
5. check console, notice log from onMouseLeave is printed

Link to code example: https://codesandbox.io/s/adoring-rosalind-vr631?file=/src/App.js

app code (same as code example):
```
import { useState } from "react";

export default function App() {
  const [visibility, setVisibility] = useState("visible");

  return (
    <div className="App">
      <div>
        <button
          id="demo-btn"
          style={{ visibility }}
          onClick={() => {
            setVisibility("hidden");
          }}
          onMouseLeave={() => {
            console.log(
              "mouseLeave event fired when button visiblity is",
              window.getComputedStyle(document.getElementById("demo-btn"))
                .visibility
            );
          }}
        >
          Click me and move the mouse
        </button>
      </div>
    </div>
  );
}
```

## The current behavior
Even though element have it's visibility set to hidden, onMouseLeave still fires when moving the mouse.

## The expected behavior
Event not emitted, element is semantically "gone" and should no longer interact with user's pointer

**Comment by josharsh** [comment]
@lirancr are you going to pick this?

**Comment by lunaruan** [comment]
Hey! This isn't a React bug. `visibility: hidden` hides the button but still leaves it in the layout, which means that mouse leave events will still be fired. You can try `display: none` (which removes the element from the page)  instead. Closing this! Feel free to reopen if you feel that this does not address your concerns!
