### ISSUE TITLE
Bug: `onChange` event handlers don't work on custom elements

### ISSUE THREAD

**Issue by josepharhar** [facebook/react#22888]
Found here: https://github.com/facebook/react/issues/11347#issuecomment-989021700

React version: experimental

## Steps To Reproduce

1. `<my-custom-element onChange={() => console.log('onchange')} />`
2. `querySelector('my-custom-element').dispatchEvent('change')`

Link to code example: https://codesandbox.io/s/shy-tdd-8b4tq?file=/src/App.js

## The current behavior
`onChange` event handlers don't get called when `change` events are fired.

## The expected behavior
`onChange` event handlers do get called when `change` events are fired.

**Comment by josepharhar** [comment]
I'm still debugging this. For `<input>` elements, it seems like `onChange` event handlers are called for `input` events but not for `change` events.
For custom elements, it seems like `onChange` handlers are neither called for `input` nor `change` events...

It would certainly be feasible to fix this by bypassing react's event system for custom elements altogether, which some people might want, but there should definitely be a way for me to patch it within react's event system as well.

**Comment by lunaruan** [comment]
Hey! Thanks for reporting this issue! Looking at your code sandbox repro, I'm not sure what `<vaadin-date-picker>`  is doing. Could you create a Codesandbox repro that doesn't use other libraries so that we can take a look?

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve`

**Comment by lunaruan** [comment]
Hey! Closing this because it's been over 24 hours. Feel free to reopen with a repro case if you haven't resolved your issue!

**Comment by claviska** [comment]
@lunaruan Please reopen this. @josepharhar is the one [driving support for custom elements in React](https://github.com/facebook/react/issues/11347#issuecomment-988986624). This is a valid bug that needs to be tracked per [the discussion that starts here](https://github.com/facebook/react/issues/11347#issuecomment-989021700).

Thanks!

**Comment by josepharhar** [comment]
Apologies for the lack of detail. Here is a minimal repro: https://codesandbox.io/s/priceless-orla-gr1th?file=/src/App.js
I will open a PR to address this as soon as I'm ready, please assign this issue to me.

**Comment by josepharhar** [comment]
I created a PR to fix this here: https://github.com/facebook/react/pull/22938
It's probably worth considering other ways to fix this though, so I'm not sure if it will get merged right away.

**Comment by gaearon** [comment]
This was fixed in https://github.com/facebook/react/pull/22938.

**Comment by josepharhar** [comment]
No, as far as I know this is only in experimental

**Comment by michaelwarren1106** [comment]
i’m not familiar with how the experimental release features get merged. is there a possibility that some things land in 18.x whereas other land in 19? or would the experimental release pretty much become 19?

**Comment by josepharhar** [comment]
I believe the plan is to include this in react 19

**Comment by nihil-pro** [comment]
Really? React 19? Why? What’s the problem to set all attributes that user pass to an element? 
I don’t want React 19, cause is terrible. 
I don’t understand, why react don’t support such simple case, I don’t understand why react isn’t wrapped in an ESM, I don’t understand why react is so outdated. Sad
