### ISSUE TITLE
React.addons.CSSTransitionGroup doesn't work inside <svg> element [Chrome 37.0.2062.124]

### ISSUE THREAD

**Issue by iamdanfox** [facebook/react#2290]
Repro:

1. Create a component that renders an `svg` tag with a list of visible elements
2. Wrap inner elements in a `<React.addons.CSSTransitionGroup ...>`

**Expected:** elements display as before, transition classes work when elements are added or removed
**Actual:** no elements are visible.

[![screen shot 2014-10-04 at 16 10 21](https://cloud.githubusercontent.com/assets/3473798/4515925/aff80386-4bd8-11e4-8906-9661086d400e.png)
jsFiddle](http://jsfiddle.net/kb3gN/6165/)

**Comment by spicyj** [comment]
Yeah, a CSSTransitionGroup turns into a `<span>` by default; see http://facebook.github.io/react/docs/animation.html#rendering-a-different-component. I expect this will work if you use a `<g>` instead, as so:

```
<CSSTransitionGroup component='g'>
```

Sorry for the slow response.
