### ISSUE TITLE
Call setState onBlur stops event propagation, necessary to use window.setTimeout? or Bug in Flux?

### ISSUE THREAD

**Issue by justin808** [facebook/react#2291]
I have an callback for onBlur that will call setState, and based on the state, some buttons may be removed from the screen.

The problem is that one of these buttons has a callback that needs to run, as the onBlur was caused by clicking on that button. If setState is called from the onBlur callback, then the callback for the button (onClick) does not run, maybe because it's not technically visible?. I verified that the button callback works fine if the onBlur callback does not call setState.

I worked around the issue by using a window.setTimout that calls setState after 250ms.

``` javascript
      window.setTimeout( () => {
        this.setState({
          editing: false,
          editValue: this._displayValue(this.props.item[this.valueField])
        });
      }, 400);
```

Is this the right approach?
Or is this a bug in flux that all callbacks don't run?
My expectation is that the all callbacks would run and the setState calls would be cummulative.

Thanks for any advice.

**Comment by BJK** [comment]
It appears that this is still an issue. We encountered this while trying to have different parts of form validation happen on both the onBlur and the onClick. It seems that if you change the DOM with some state effected by the onBlur, when it is ABOVE the button containing the onClick, the onclick will not fire. 

See this http://jsfiddle.net/kb3gN/11477/ which is a variation on the example provided above. If you enter some text, you'll have to click the button twice, to see click: true.

**Comment by twall** [comment]
I'm seeing this issue where a `setState` within an `onBlur` which happens as a result of clicking a link (the cursor is in an input field w/focus when the link is hit) results in the link click being ignored.

**Comment by master117** [comment]
The issue of setState in onBlur preventing other click events is still happening.

**Comment by CorleoneYu** [comment]
I have an input with onBlur and a menu whith onClick like this:
``` jsx
<input onBlur={handleBlur} />
<Menu onClick={handleClick} />
```

**Comment by gaearon** [comment]
If there is still an issue please *file a new issue* with a minimal repro case. Commenting in closed issues is not helpful — there are thousands of them and nobody is keeping track.
