### ISSUE TITLE
React 18-rc typescript definitions

### ISSUE THREAD

**Issue by smtrd3** [facebook/react#22939]
I wanted to know whether typescript definitions for react 18-rc is available yet. I wanted to start migrating my typescript project from react 17 to react 18(rc), but I couldn't find any information regarding typescript integration online. On the definitely typed repo there I can see `@types/react/next.d.ts` but it contains alpha version definitions as of now.

**Comment by eps1lon** [comment]
> On the definitely typed repo there I can see @types/react/next.d.ts but it contains alpha version definitions as of now.

`next.d.ts` should contain types for the release candidate. Only `useInsertionEffect` is missing but that's already in the pipeline: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57555

If there's anything else missing, please [open an issue in the DefinitelyTyped/DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/new/choose) and mention what's missing specifically.

**Comment by hrasoa** [comment]
I'm sorry if the question was already asked, and I'm sure it was, but why not put the definitions directly inside ```react``` repo ?
