### ISSUE TITLE
Bug: yarn run debug-test does not work

### ISSUE THREAD

**Issue by shavidze** [facebook/react#22935]
## What version of Node.js are you using?
*16.13.0*

## What browser are you using?
*Chrome*

## What operating system are you using?
*Windows*

When I'm trying to run for example *yarn debug-test --watch ReactCache-test* getting an error: *Please run: `'yarn` instead.*

**Comment by shavidze** [comment]
related pull request https://github.com/facebook/react/pull/22936

**Comment by lunaruan** [comment]
Hey! Thanks for reporting this issue! However, as per @bvaughn's comment, this change was intentional to reduce the permutations of test commands we previously had to explicitly define in the Yarn lock file. Closing this!
