### ISSUE TITLE
exhaustive-deps warning when using React.MutableRefObject on external hook

### ISSUE THREAD

**Issue by vitorbertolucci** [facebook/react#22931]
I have a use case where I need to pass a ref object as an argument to a custom hook. This custom hook accesses the ref on an useEffect hook and this is where eslint is warning about exhaustive-deps.

I put up a CodeSandbox to demonstrate the issue, please find it [here](https://codesandbox.io/s/dazzling-gagarin-uy57g).

You can see the exhaustive-deps being triggered on file useCharacterValidation.tsx.

The custom hook's argument `formRef` is typed as `React.MutableRefObject<...>`, so the linter should be able to identify it as a ref and not warn about it. I don't think adding `formRef` as a dependency would be safe because in this case `ref.current` holds an object, so it would change its reference on every render.

Also, if you check App.tsx near line 27, you can see that I access `formRef` in the exact same way I do on `useCharacterValidation`  and the linter does not warn me. `formRef` is also of type `React.MutableRefObject<...>` on App.tsx.

React version: 17.0.2

## Current behavior

exhaustive-deps is being triggered on a variable of type `React.MutableRefObject`

## Expected behavior

exhaustive-deps should not be triggered when the linter is able to identify that a variable's type is `React.MutableRefObject`

**Comment by lunaruan** [comment]
Hey! Thanks for reporting this issue! Yes, you're correct in that the `exhaustive-deps` lint rule shouldn't be triggered on refs. However, the linter isn't smart enough currently to detect this if the ref is declared in a separate file and passed in through props. To silence the error, you can just add `formRef` to the dependency array. It's a redundant dependency that will never change, but it won't break anything. Sorry for the inconvenience! Closing this issue as won't fix for now. If you are interested in proposing a solution, please feel free!
