### ISSUE TITLE
Generate only the config for the specified renderer instead of all at once in runFlow.js

### ISSUE THREAD

**Issue by hyaocuk** [facebook/react#22941]
# Description
When we run `yarn flow` to type-check one of the projects, it automatically generates the folders with the corresponding project names under the `config` folder, and the default flow config files are all generated and placed under the folder instead of only the specified one is generated.

# What will this change do?
This change will export a method from `createFlowConfigs.js` and accept the specified `renderer`, and generate the config file using the existing method.

**Comment by bvaughn** [comment]
> This change will export a method from `createFlowConfigs.js` and accept the specified `renderer`, and generate the config file using the existing method.

What change?

Can you explain why you care about this particular infra detail for this project?

**Comment by hyaocuk** [comment]
I'm learning the source code of this part, and I think it's unnecessary to generate the config that's currently not used, and it's also listed in the todo.

**Comment by bvaughn** [comment]
Thanks for explaining.

If you'd like to submit a PR that changes this, please feel free 😄 

I don't think we need an open issue for this though.

**Comment by bvaughn** [comment]
Going to close this for now.
