### ISSUE TITLE
better api for assigning keys to components

### ISSUE THREAD

**Issue by gabor** [facebook/react#2294]
in https://github.com/facebook/react/blob/master/docs/docs/04-multiple-components.md,
it describes how the "key" attribute can be assigned, one of the ways being providing them in an Object.
but because Objects are unordered, a hack is described there how to try to work around that fact.

the problem is that this is an unspecified implementation-detail.

i think it is a bad idea to rely on an unspecified implementation-detail. there is nothing preventing browsers from changing this order (they did it in the past, for example see https://code.google.com/p/v8/issues/detail?id=164 (specifically the later comments where they note the differences between browsers). i understand that these days the browsers maybe reached a consensus, but if there will a faster way to do Objects, i can see them changing again)

also, i think we can have a better api there. the code basically wants an array of pairs, not an object, so shouldn't it support an array of [key,component] instead? afterwards the object-based solution could be deprecated.

**Comment by gaearon** [comment]
Specifying an object is now not supported. Please use explicit keys.
