### ISSUE TITLE
[DevTools Bug]: Fetch API cannot load webpack-internal:///... URL scheme "webpack-internal" is not supported

### ISSUE THREAD

**Issue by anthonyma94** [facebook/react#22944]
### Website or app

https://prnt.sc/22rtnf0

### Repro steps

Most actions in DevTools (search for component, click on component, hook parsing, profile record, etc) cause this error.

I am using Next.JS 12 within a NX monorepo.

### How often does this bug happen?

Every time

**Comment by gabrielhamilton** [comment]
How you'r calling, using http or https ?

**Comment by anthonyma94** [comment]
I'm not quite sure I understand... This happens on any actions done on DevTools. I'm on localhost  with http if that's what you mean.

**Comment by bvaughn** [comment]
I think this is a misunderstanding. The error is happening because you've tried to parse hook names (that little magic wand icon). DevTools doesn't support Webpack's _eval_ source maps because there's no way for it to load the source map. (The "webpack-internal://" protocol is not something that can be fetched.)

**Comment by anthonyma94** [comment]
I see. You're right, once I unchecked the "load hook names" setting the errors only occur when I try to parse hook names. Forgive my ignorance, I've never fully dove into webpack myself. Do you know if this is a known issue with Next projects?

**Comment by bvaughn** [comment]
> Do you know if this is a known issue with Next projects?

Unfortunately, Webpack's default source map setting uses cheap eval maps, which cause this problem. I think it's a known issue (at least on our side) but not one I have any great ideas of how to fix.

**Comment by ppiwo** [comment]
+1 for me as well. Has anyone been able to get around this by adjusting their webpack config?

Here is my stack trace
<img width="985" alt="Screen Shot 2022-03-11 at 8 23 05 AM" src="https://user-images.githubusercontent.com/20652666/157885919-b932c332-0f64-4698-b030-254a410e3197.png">

**Comment by kjmph** [comment]
I may be a minority, yet I do like React Devtools in standalone mode. I commented in facebook/react#25427 that a protocol handler could be installed in Devtools for webpack-internal. If there was a notion of searching from current working directory, the filesystem could potentially be used to fetch these source maps. However, I do encourage everyone to double check their Devtools usage, it may very well be throwing an error, and yet still showing Hook method names anyway. That's what was happening on my end, and I see @bvaughn's reply to a Next.js comment.
