### ISSUE TITLE
Missing entry point in package.json

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#22947]
https://github.com/facebook/react/blob/3b3daf5573efe801fa3dc659020625b4023d3a9f/packages/react/package.json#L32

This `build-info.json` is not published to npm.

https://www.jsdelivr.com/package/npm/react?version=18.0.0-rc.0

**Comment by bvaughn** [comment]
This is a left over artifact from the way our release script used to work. It shouldn't cause any problems, but if you'd like to submit a PR removing this entry that'd be okay too.

**Comment by mengriri** [comment]
qweqweqwe
