### ISSUE TITLE
Scroll momentum stopped on rendering

### ISSUE THREAD

**Issue by EtienneLem** [facebook/react#2295]
See [Jveux’s React version](http://jsfiddle.net/vjeux/KbWJ2/9) of [Infinity](http://airbnb.github.io/infinity/demo-on.html). I know that it’s not an updated version of React, but I get the same result with 0.11.2

It works seamlessly until you let go of the trackpad/magic mouse (you know, when momentum scrolling kicks in). The scrolling suddenly stops when re-rendering.

Here’s a reduced test-case of my own experiment where I get the same result: http://f.cl.ly/items/0I3l3V0634253F2n2t0x/react-infinity.html

If you’d only change the color of the visible items vs. the non-visible ones, it wouldn’t lag at all. I’m a little bit lost as to why it stops… been struggling for a few days trying different ways to implement Infinity with React.

Known issue? (if issue there is)
Any hints/workarounds?

**Comment by mjackson** [comment]
Kind of interesting, but @tholman and I were investigating this today and discovered that if you use `pointer-events: none` on the element that contains the items you're showing then momentum scrolling works again. ¯\_(ツ)_/¯ e.g. http://jsfiddle.net/121q0L9x/

**Comment by EtienneLem** [comment]
@mjackson Very interesting indeed. Thanks for the heads up, I hadn’t figured a way around that yet :metal:
That is definitely not a React bug, closing the issue.
