### ISSUE TITLE
Bug: Error: Should have a queue

### ISSUE THREAD

**Issue by gyurmey** [facebook/react#22955]
React version: 17.0.1

![error](https://user-images.githubusercontent.com/15898245/146005101-5b2569e9-4742-40c4-80ae-a1f4c2f85bf2.png)

**Comment by PaulACoroneos** [comment]
You cannot conditionally call hooks.

**Comment by eps1lon** [comment]
@gyurmey Also check the console for a more detailed message mentioning conditional calls of hooks which are not supported.
