### ISSUE TITLE
Bug: jsx-dev-runtime module not found

### ISSUE THREAD

**Issue by blakeromano** [facebook/react#22974]
I have tested on a Monterry and Ubuntu EC2 instance running a React application and we are getting this issue with npm start and npm build

ERROR in ./src/index.js 10:0-58
Module not found: Error: Can’t resolve ‘react/jsx-dev-runtime’ in ‘/Users/rondoupo/Code/iraftrading/ttf-prototype-iraf/src’
Did you mean ‘jsx-dev-runtime.js’?
BREAKING CHANGE: The request ‘react/jsx-dev-runtime’ failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a ‘*.mjs’ file, or a ‘*.js’ file where the package.json contains ‘“type”: “module”’).
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by anton-g** [comment]
This needs more information to be answered. For example what Node version and React version you're using, if you're using create-react-app or a custom setup etc. If you can create a CodeSandbox.io with your setup that would probably help.

**Comment by eps1lon** [comment]
I remember that there were some initial issues with earlier versions of the transform related to the file extension. I would suggest updating React and Babel related packages to see if this is fixed. 

If not, please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub and we'll reopen this issue.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
