### ISSUE TITLE
Bug: [5.0] Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by alamothe** [facebook/react#22971]
Importing the package `react-data-grid` results int he following error upon `yarn start`:
```
ERROR in ./node_modules/react-data-grid/lib/bundle.js 3:0-56
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/alamothe/Projects/car-manager/fleet-client/node_modules/react-data-grid/lib'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

This is a regression from 4.0 which didn't have this problem.

React version:
```
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-data-grid": "^7.0.0-beta.7",
```

## Steps To Reproduce

1. Import `react-data-grid`

## The expected behavior

No error, like in 4.0

**Comment by nmain** [comment]
> 4.0
> 5.0

Huh?  You're on react 17 and react-data-grid 7; was this supposed to go on some other project's issue tracker?

**Comment by alamothe** [comment]
You're correct, it seems to be an issue with Webpack 5 and React: https://github.com/facebook/react/issues/20235

However, CRA can fix it in the webpack config. `react-data-grid` is just an example, many packages are affected. The issue exists in React 16 as well.

**Comment by alamothe** [comment]
Oops, my bad.
