### ISSUE TITLE
Bug: `@license` header in React 18 bundles contains `vundefined`

### ISSUE THREAD

**Issue by Andarist** [facebook/react#22988]
Can be checked on top of the files here:
- https://unpkg.com/react@18.0.0-rc.0-next-aa8f2bdbc-20211215/cjs/react.development.js
- https://unpkg.com/react@18.0.0-rc.0/cjs/react.development.js

I've wanted to fix this quickly... but it turns out that your whole build pipeline is a little bit convoluted so it ain't a 5 min fix. I could still work on this but I would need some pointers as to what is the preferred fix.

From what I understand - this broken version is read here:
https://github.com/facebook/react/blob/ceee524a8f45b97c5fa9861aec3f36161495d2e1/scripts/rollup/wrappers.js#L6
but the root package.json doesn't contain a version. It seems that scripts are updating "root" package.json here:
https://github.com/facebook/react/blob/ceee524a8f45b97c5fa9861aec3f36161495d2e1/scripts/release/utils.js#L231-L238
but this only happens for the temp dir created during the release as 2 scripts are using `copyRepoToTempDirectory`.

I think the scripts should be run in the context of those temp dirs and that could potentially fix the problem (maybe they already are but something else is broken? I didn't yet confirm this).

The additional problem is that this wouldn't fix the local `yarn build` as this doesn't update this root package.json version at all.

**Comment by bvaughn** [comment]
@Andarist The build scripts were refactored a couple of months ago to remove a `build-info.json` file. Maybe this regressed then? Not sure.

One quick fix might be to just update `scripts/rollup/wrappers.js` to use a different package.json to read the version from. Like `packages/react-dom/package.json`? Would that work?

**Comment by vitaliemiron** [comment]
I'll take it.
