### ISSUE TITLE
 Safari 6 bug: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by DKunin** [facebook/react#2298]
Specific to Safari - breaks update.js addon in this place:

     if (!(ALL_COMMANDS_SET.hasOwnProperty(k) && ALL_COMMANDS_SET[k])) {
      nextValue[k] = update(value[k], spec[k]);
    }

can be fixed with

    if (!(ALL_COMMANDS_SET.hasOwnProperty(k) && ALL_COMMANDS_SET[k])) {
      if(!(/string|boolean/i).test(typeof value[k])) { 
        nextValue[k] = update(value[k], spec[k]);
      }
    }

**Comment by genxstylez** [comment]
Any updates on this?

```js
handleHomeOnMouseEnter(e) {
        e.target.text = 'this is home';
},

handleHomeOnMouseOut(e) {
    e.target.text = 'Home';
},
render() {
<div className="navbar">
    <a href="/"
         onMouseEnter={this.handleHomeOnMouseEnter}
         onMouseOut={this.handleHomeOnMouseOut}>Home</a>
</div>
}
```
The above snippet repros the problem, hope it helps.

**Comment by jimfb** [comment]
@genxstylez If you replace all instances of `e.target.text` with `e.target.innerHTML`, the demo appears to work fine for me.  Using Safari Version 8.0.7 (10600.7.12).

https://jsfiddle.net/qe3avvnt/

**Comment by zpao** [comment]
@genxstylez I think that's unrelated to the reported issue, which is specifically about the `updates` addon. Using `e.target.textContent` should also work (I don't think `.text` is standard)

There have been no other reports and no test cases of the original issue, so closing out.

**Comment by genxstylez** [comment]
@zpao 
ok, thanks!
