### ISSUE TITLE
10 FREE React Courses to Level Up your React Skills

### ISSUE THREAD

**Issue by Nehal333** [facebook/react#22987]
1⃣  Code 15 React Projects - Complete Course

Improve your skills with the React JavaScript library by building 15 projects using React. Code: github.com/john-smilga/re…

🔗 youtube.com/watch?v=a_7Z7C…

2⃣  React JS Frontend Web Development for Beginners

Learn React JS along with Modern JavaScript from absolute scratch. This course is a getting started guide for beginners. - Free Course

🔗 udemy.com/course/react-t…

3⃣  Free React Hooks Tutorial - React Hooks and Context (with React-Redux migration guide)

Learn the future of React and how to migrate your existing Redux code - Free Course

🔗 udemy.com/course/react-h…

4⃣  React with Redux, React-Router, Hooks, and Auth0

Learn the complete React-Redux front-end system. - Free Course

🔗 udemy.com/course/modern-…

5⃣  Building Applications with React and Flux

Get started with React, React Router, and Flux by building an app that manages Pluralsight course data. Modern client-side development stack: create-react-app, Node, Webpack, Babel, and Bootstrap.

🔗 pluralsight.com/courses/react-…

6⃣  React Fundamentals

Learn the fundamentals of React and start your journey with this amazing library - Free Course

🔗 udemy.com/course/react-f…

7⃣  Front-End Web Development with React

Offered by The Hong Kong University of Science and Technology. This course explores Javascript-based front-end application development, and ... Enroll for free.

🔗 coursera.org/learn/front-en…

8️⃣React: Getting Started

Learn the fundamental concepts about React and use them to build practical web applications in this beginner-level ReactJS course.

pluralsight.com/courses/react-…

9️⃣Free Redux Framework Tutorial - React and Redux Masterclass

Master React JS components with Redux actions in Flux. Yarn, React-Redux, Redux Thunk Reactjs, React.js test renderer - Free Course

udemy.com/course/learnin…

🔟 Free React Tutorial - React basic in just 1 hour [2021]

The quick guide to learn basic concepts and workflow of how to build React app - Free Course

udemy.com/course/react-b…

**Comment by Nehal333** [comment]
Don't forget to follow me ♥️

**Comment by bvaughn** [comment]
@Nehal333 This issue (and your account) has been reported to GitHub.
