### ISSUE TITLE
Bug: There are redundant DOM manipulation when swapping elements in the list

### ISSUE THREAD

**Issue by amorphousDj** [facebook/react#22994]
React version: 17.0.2

## Steps To Reproduce

1. Add a breakpoint in react-dom.development.js to observe the DOM manipulation.
![image](https://user-images.githubusercontent.com/31609229/146729545-785b97c4-c705-48c3-8f4e-d0dac9910334.png)
2. Click the swap button and observe the DOM change.

Link to code example: https://codesandbox.io/s/nifty-fog-mdemb

## The current behavior
React modified the HTML document ten times.

## The expected behavior

Now that each element has been given a unique key value, I hope that react will only modified the HTML document twice for better performance.

**Comment by luffy84217** [comment]
I took a look at your render function, you assign specified `id` as key so it reorders when updating every time.
```javascript
render() {
  return (
    <div className="App">
      <button onClick={this.swapRows}>swap rows</button>
      {this.state.data.map((item) => {
        return <Item key={item.id.toString()} content={item.content} />;
      })}
    </div>
  );
}
```
The simple solution is to use index of item as key and set `id` to the id attribute on the specified item.
```javascript
function Item(props) {
  return <div id={props.id}>{props.content}</div>;
}

render() {
  return (
    <div className="App">
      <button onClick={this.swapRows}>swap rows</button>
      {this.state.data.map((item, i) => {
        return <Item key={i} id={item.id.toString()} content={item.content} />;
      })}
    </div>
  );
}
```

**Comment by amorphousDj** [comment]
> 

Thank you for your reply, this is an effective method. But react does not recommend using indexes for keys.

**Comment by sunderls** [comment]
not really offering some help here 

React is not very good at comparing reversed list https://github.com/facebook/react/blob/c1220ebdde506de91c8b9693b5cb67ac710c8c89/packages/react-reconciler/src/ReactChildFiber.old.js#L750

if you move some key in the rare into the head, it causes all the items to be marked as "need to move".

**Comment by vaukalak** [comment]
I'm sorry if it's not the same issue, that is mentioned in the topic. But this not only creates a performance issue but might be a bug on a functional level. For example When you expect, that HTML element will not be re-created, and want to create a CSS swap transition, the re-created elements will swap without animation. I've created a [codesandbox](https://codesandbox.io/s/react-swap-issue-t2rq9)  that reproduces the issue.
