### ISSUE TITLE
Bug: Code running result is different between dev mode and prod mode. 

### ISSUE THREAD

**Issue by xdoer** [facebook/react#23008]
React version: 17.0.2

## Difference
dev mode
![bad](https://user-images.githubusercontent.com/22864183/146891810-1a316ba2-51bd-4cc0-b340-bafd7ab50082.gif)

prod mode (expected result)
![normal](https://user-images.githubusercontent.com/22864183/146891907-567947be-165f-488b-a823-c4526ef9403e.gif)

## Steps To Reproduce

1. use vite or create-react-app init a react project
2. copy below code and paste it to your project

```jsx
const App = () => {
  const [list, setList] = useState([
    {
      text: 'a',
      active: false,
    },
    {
      text: 'b',
      active: false,
    },
    {
      text: 'c',
      active: false,
    },
    {
      text: 'e',
      active: false,
    },
    {
      text: 'f',
      active: false,
    },
  ])

  useEffect(() => {
    setInterval(() => {
      setList((list) => {
        const activeIdx = list.findIndex((item) => item.active)

        list.forEach((item) => (item.active = false))

        list[(activeIdx + 1) % list.length].active = true

        // return a new list not get the correct result in dev mode
        return [...list]
      })
    }, 2000)
  }, [])

  return (
    <div>
      {list.map((item) => {
        const { text, active } = item
        return (
          <div key={text} style={{ color: active ? 'red' : 'blue' }}>
            {text}
          </div>
        )
      })}
    </div>
  )
}

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
)
```
3. use `yarn start` or `yarn dev` start the project and open it in browser, you will see below result
![bad](https://user-images.githubusercontent.com/22864183/146891810-1a316ba2-51bd-4cc0-b340-bafd7ab50082.gif)
4. use `yarn build` build the project, and start a static server dispatch the `dist` folder.
![normal](https://user-images.githubusercontent.com/22864183/146891907-567947be-165f-488b-a823-c4526ef9403e.gif)

**Comment by vkurchatkin** [comment]
You are mutating your state, that can cause problems in strict mode:

```js
 useEffect(() => {
    setInterval(() => {
      setList((list) => {
        const activeIdx = list.findIndex((item) => item.active)

        list.forEach((item) => (item.active = false)) // <-- here

        list[(activeIdx + 1) % list.length].active = true // <-- and here

        // return a new list not get the correct result in dev mode
        return [...list]
      })
    }, 2000)
  }, [])
```

**Comment by salazarm** [comment]
Like the above commenter said, you're mutating your state directly. With `StrictEffects` enabled your effects are run twice (to test if its safe in concurrent mode). The current pattern isn't because you're mutating the item directly, so even though you create a new `list` you still have the same `item`s as before in it which you already mutated.


Instead you should do:
```
setList((list) => {
    const activeIdx = list.findIndex((item) => item.active)
    const newList = [...list];
    newList[activeIndex] = { ... newList[activeIndex], active: false};
    newList[(activeIdx + 1) % list.length] = { ... newList[activeIndex], active: true};
    
    return newList;
})
```

**Comment by xdoer** [comment]
thanks for your reply. this solve my problem. and i think it would be better throw a warning in devtools.

**Comment by vkurchatkin** [comment]
> and i think it would be better throw a warning in devtools

I guess you are right, but unfortunately reliably detecting something like this is very complicated
