### ISSUE TITLE
Bug:  Undeclared objects get shown as an error

### ISSUE THREAD

**Issue by The-dev-Sirmed** [facebook/react#23025]
React version: ^17.0.2

## Steps To Reproduce

1. Declare an object and use it in a declarative string (eg.
    ```
       const videoTrack = { enabled: true }
       {videoTrack.enabled && <h1> video track is enabled </h1>}
       {!videoTrack.enabled && <h1> video track is not enabled </h1>}
    ```
2. React has somekind of problem with using `!` with any obj, eg `!videoTrack`
3. It only gives sometimes, resarting the dev server would **sometimes** fix it 

# Dependencies 
```
"@100mslive/hms-video": "^0.1.36",
    "@100mslive/hms-video-react": "^0.3.111",
    "@100mslive/hms-virtual-background": "^1.3.6",
    "@fluentui/react-icons": "^2.0.153-canary.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "base64-url": "^2.3.3",
    "firebase": "^9.5.0",
    "framer-motion": "^4.1.17",
    "iconsax-react": "0.0.7",
    "jquery": "^3.6.0",
    "jsonwebtoken": "^8.5.1",
    "random-username-generator": "^1.0.4",
    "randomstring": "^1.2.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-modal": "^3.14.4",
    "react-router-dom": "^6.0.2",
    "react-scripts": "4.0.3",
    "react-webcam": "^6.0.0",
    "sha256": "^0.2.0",
    "uuid": "^8.3.2",
    "web-vitals": "^1.1.2"
```

## The current behavior
![image](https://user-images.githubusercontent.com/77951240/147329321-ce7553cf-e748-4803-bb7b-2c63ff0b432f.png)

## The expected behavior
It shouldnt show any error

**Comment by sandeepacharya2001** [comment]
![passport](https://user-images.githubusercontent.com/58663243/148939477-d3e6e6bd-0af5-4d9a-af9f-f3d3d8979c45.jpg)

**Comment by eps1lon** [comment]
The error in the screenshot shows a different error. Specifically, you're accessing a property on a value that is null in some place. Check the error overlay carefully and try to find the origin of the error. It's unlikely that React has an issue with `!object.property` but rather that `object` is `null`.

In the future, please include a minimal Codesandbox or cloneable repository for reproduction.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
