### ISSUE TITLE
Drop ReactLink hooks in controlled components

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2302]
ReactLink supports a sort of adhoc two-way data binding. We've found it to be a distraction rather than helpful so we don't plan on adding it to the core outside of addons anyway.

We should take the support out of controlled components and make wrappers that can be used instead of the controlled components, and put the wrappers in addons. This provides backwards compatibility without having the legacy remain in core.

**Comment by saulshanabrook** [comment]
@sebmarkbage Could you give an example of how to best deal with multiple form inputs without linkState?

**Comment by syranide** [comment]
@saulshanabrook 

The two following are equivalent, it's just sugar.
`<input valueLink={vl} />`
`<input value={vl.value} onChange={vl.requestChange} />`

https://github.com/facebook/react/blob/master/src/addons/link/LinkedStateMixin.js
https://github.com/facebook/react/blob/master/src/addons/link/ReactLink.js

**Comment by tobia** [comment]
ReactLink may be "just sugar really," but when you have dozens of inputs in a form and hundreds in the entire application, it makes a noticeable difference. JSX itself is "just sugar really," but it's an important tool for productivity and readability.

Compare:

    <input valueLink={this.linkState("surname")} />
    <input value={this.linkState("surname").value} onChange={this.linkState("surname").requestChange} />

That being said, I'm all for taking ReactLink out of core, ***if*** the syntax doesn't explode like in the example above.

**Comment by syranide** [comment]
@tobia Like I mention in #3591, you can wrap an `input` in your own component of your own which can provide the same functionality (and more). If/when it's dropped React would certainly provide such wrappers out-of-the-box in addons, but it wouldn't really be special or anything you can't already do yourself.

**Comment by gaearon** [comment]
This was fixed in https://github.com/facebook/react/pull/8165.
