### ISSUE TITLE
Bug: Repeated execution of components

### ISSUE THREAD

**Issue by zhangyi999** [facebook/react#23027]
React version:  17.0.2

## Steps To Reproduce

1. create App
2. change App.js
3. The `debugger` was executed 2 times
4.  `console.log('0 app')` Executed only once

Link to code example:

```js
import {useEffect} from 'react';
function App() {
  console.log('0 app')
  debugger
  useEffect(() => {
    console.log('2 app')
  }, [])
  // reload()
  return (
    <div className="App">
      App
    </div>
  );
}

export default App;
```

**Comment by markerikson** [comment]
This is correct and expected behavior.  React double-renders components in development inside of a `<StrictMode>` tag.

**Comment by zhangyi999** [comment]
Thanks for your help
