### ISSUE TITLE
Question：Deprecate defaultProps on function components？

### ISSUE THREAD

**Issue by bigbigDreamer** [facebook/react#23032]
There has always been a question. In my impression, the proposal for the defaultProps of obsolete function components has appeared for a long time, but it is still effective until the React 17 version. Is there any latest plan for this proposal, or can I still Continue to use it?

[RFC](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components)

Or, is there any better recommendation?

**Comment by prionkor** [comment]
Although we can always use default in props spread. having `defaultProps` seems a cleaner solution. Is it deprecated in react 18?

**Comment by bigbigDreamer** [comment]
@bvaughn  need help, this [RFC](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components)
