### ISSUE TITLE
style whichi has '-webkit-line-clamp' attribute is filtered in react?

### ISSUE THREAD

**Issue by codedaybyday** [facebook/react#23033]
That's not reasonable!

Problem:

```-webKit-line-clamp``` is written as ```webkitlineclamp```, so it is filtered by react， but if ```-webKit-line-clamp``` is written as ```WebkitLilineClamp```, it will not be filtered·

Here are some examples where - WebKit - does not filter the lowercase initial in react：
```-webkit-box-orient:vertical;```

Sugestion:

There is something wrong with this file ```packages/react-dom/shared/CSSProperty```. You should add a prefix with WebKit lowercase

![image](https://user-images.githubusercontent.com/15086407/141983265-5ce4b47e-5f45-467d-8059-838a1d8633a6.png)

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by codedaybyday** [comment]
@eps1lon  This is the demo [webkitlineclamp-demo](https://codesandbox.io/s/webkitlineclamp-demo-u9n0w)
The uppercase WebKit prefix used by webkitlineclamp is invalid. In fact, there is no problem that other attributes such as webkitboxorient use the lowercase WebKit prefix. I think this is a bug and compatibility needs to be considered
