### ISSUE TITLE
Bug: textarea: set maxLength & controled value, when input Chinese an blur, do not trigger event change

### ISSUE THREAD

**Issue by doubleTotoo** [facebook/react#23046]
textarea: set maxLength & controled value,  when input Chinese an blur, do not trigger  event `change`

React version: 16.14.0

## Steps To Reproduce

```
import React, { Fragment, useCallback, useState } from 'react';

export default function Demo(): JSX.Element {
  const [value, setValue] = useState('12');
  const handleChange = useCallback((v: string) => setValue(v), []);

  return (
    <Fragment>
      <textarea 
        maxLength={4}
        value={value}
        onChange={(event) => {
          console.log('onChange', event.target.value);
          handleChange(event.target.value);
        }}
      />
    </Fragment>
  );
}
```

## The current behavior

https://user-images.githubusercontent.com/21987324/147717923-e35ba7c1-534e-49dd-9af2-9c104dc36cfb.mov

## The expected behavior
same with component input

https://user-images.githubusercontent.com/21987324/147718101-e7cdad67-ccb7-49b0-a5bf-6953460c295b.mov

**Comment by 7654mahbub54** [comment]
Mahbhb

**Comment by itolimaesther** [comment]
I would love to work on this issue as first timer if it's still open. @eps1lon
