### ISSUE TITLE
[DevTools Bug]: Error: Could not find ID for Fiber "..."

### ISSUE THREAD

**Issue by d-pollard** [facebook/react#23049]
### Website or app

https://github.com/d-pollard/react-konva-devtools-issue

### Repro steps

1. Install repo
2. run repo
3. visit `/playground` in your browser of choice. 
4. Navigate to the dev tools, and you should see the error

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment]
Possibly fixed by #23156.

**Comment by bvaughn** [comment]
Going to roll this into #22970 since they're both the same error and that one has more context. Will follow up there.
