### ISSUE TITLE
Bug: customElement can't setAttrubute width Object  

### ISSUE THREAD

**Issue by a707843858** [facebook/react#23043]
I get something wrong with customElement properties  and slot ;

React version: experimental

 Steps To Reproduce

1.create a customElement width Object properties  ;

2.assign an object to a property, customElement property receives as '[object,object]'.  

3.customElement use slot , React  will render the child of customElement as its own, and slot will be re-rendered within the children element.  

Link to code example: [https://jsfiddle.net/a707843858/f52s16uh/31/](https://jsfiddle.net/a707843858/f52s16uh/31/)

## The current behavior

1.setAttribute passes a value of the same type

2.When React renders customElement. Pass children to it as an attribute and hand him the controller without rendering it's children.

**Comment by itolimaesther** [comment]
I would love to work on this issue as first timer if it's still open. @eps1lon

**Comment by vinisaveg** [comment]
@a707843858 is it still happening? could you try to explain with a better example? I couldn`t precisely understand the `jsfiddle` demo.
