### ISSUE TITLE
React 18 

### ISSUE THREAD

**Issue by ReshadSadik** [facebook/react#23059]
when is the new release coming?

**Comment by anton-g** [comment]
React 18 is currently released as an "release candidate" (ie RC), this means that the features are finalised and developers are encouraged to try to upgrade their apps to 18 to see if everything works.

The RC was released on December 8th and the estimated timeline for stable release was 2-4 weeks after RC, so unless something comes up during testing you can probably expect the release during January.

Source: https://github.com/reactwg/react-18/discussions/9

**Comment by ShadmanShakib** [comment]
Waiting for React 18. Hopefully it comes out soon.
