### ISSUE TITLE
Semantic meaning of setState unclear

### ISSUE THREAD

**Issue by ZackYovel** [facebook/react#23050]
Hi,
I am going through the sept-by-step guide to React now - the state and lifecycle part ([here](https://reactjs.org/docs/state-and-lifecycle.html)). I suddenly understood something that was very confusing to me until now (I am a complete beginner in React, never have written anything even in the level of a tutorial): the setState method, by name, sounded to me like a simple setter, that is only responsible for setting a new value to the state (and perhaps validating this value). This is of course not accurate, singe the setState also triggers a DOM update. As a result I was incredibly foggy about what should I do to update the DOM when I use react, until now.

So, first of all thanks for the great step-by-step guide, I am having a continuous mind-blone experience since I started it.

Second of all, a suggestion: perhaps it will be clearer if the name of setState will be changed (or an alias with a clearer name be added) so that the new name will indicate the DOM update (or at least the ReactDOM.render() operation that will be triggered), just anything that will instantly tell a newbie like myself that this method does more than just set a value inside the state object.

I looked up setState in issues prior to adding this one (not only the open ones) to avoid spamming, and did not find one. If I missed something I sincerely apologize.

**Comment by akgupta0777** [comment]
@ZackYovel Thanks for creating an issue and we are happy you are learning React from the step-by-step guide.
`setState()` is a react function for changing state. There is a rule in react(Not a rule particularly) but it is how React works internally that every state change in react app triggers a `re-render`(means your whole app is mounted again and the whole app is re-instantiated). 
IMHO changing the name of this function doesn't make much sense as it does what it says to change the state, changing the state results in a re-render later on.

**Comment by ZackYovel** [comment]
I understand this, but the bottom line is for a newcomer such as myself this is very disorienting. Anyways, it is not a catastrophe if newcomers will need to overcome this single obstacle, so not a big problem.

But how about creating an alias for this as I suggested? this wont change existing code, but will provide a more readability friendly syntax alternative. I mean, it is good that you have this rule about updating the UI whenever a state changes, but it is not something that a newcomer can tell from the function name. It is simply not self-documentary.

The pattern 'setName' is, after all, a globally accepted convention for a setter's name. A setter is expected to validate and set a field's value. And that is what I expected when I met the setState function name, and I do believe it happens to others as well.

But again, this is not a catastrophe and I don't want to be pushy about it. I loved the step-by-step guide, I hope you will one day create a version that has hooks in it to begin with and not teach classes because they made me want to cry, but I understand that the work on hooks is not yet finished and for this reason it is not yet a good idea to provide an alternative guide that doesn't teach classes at all.

I really love the way react reimagined frontend UI coding. I still don't like javascript even one tiny bit, but react makes it much better for sure.

**Comment by markerikson** [comment]
@ZackYovel I would strongly recommend going through the new React beta docs site, at https://beta.reactjs.org.  It _does_ teach hooks and function components as the standard way to use React.

**Comment by ZackYovel** [comment]
> @ZackYovel I would strongly recommend going through the new React beta docs site, at https://beta.reactjs.org. It _does_ teach hooks and function components as the standard way to use React.

Great, I thought something like that might already be under way. Thanks for the link.
