### ISSUE TITLE
Bug: useState re-render logic is very strange

### ISSUE THREAD

**Issue by hxse** [facebook/react#23055]
React version:

## Steps To Reproduce
```
import { useState, useEffect, useRef } from "react";
function App() {
  const [count, setCount] = useState(0);
  const countLast = useRef(0);

  function handleClick() {
    const num = 1;
    setCount(num);
    console.log(num == countLast.current, "set num", num, "last count:", countLast.current);
  }
  useEffect(() => {
    countLast.current = count;
    console.log("effect");
  });
  console.log("Render");
  return (
    <div>
      <button onClick={handleClick}>Next</button>
      {count}
    </div>
  );
}

export default App;
```

Link to code example:
https://codesandbox.io/s/confident-satoshi-3othy?file=/src/App.js

## The current behavior
![image](https://user-images.githubusercontent.com/22582226/147873129-89338b13-0e93-485e-a3b2-2cb9dedd2b64.png)

## The expected behavior
When I clicked the button for the second time, The "Render" string is printed, But the third and after clicks are not printed.
The second click should be consistent with the follow-up, it is not printing "Render" strings, beacuse `num == countLast.current` is True.
This inconsistency of behavior can cause a lot of confusion.

**Comment by vkurchatkin** [comment]
This is documented: https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update

> If you update a State Hook to the same value as the current state, React will bail out without rendering the children or firing effects. (React uses the Object.is comparison algorithm.)

> Note that React _may still need to render that specific component again_ before bailing out. That shouldn’t be a concern because React won’t unnecessarily go “deeper” into the tree. If you’re doing expensive calculations while rendering, you can optimize them with useMemo.

**Comment by hxse** [comment]
@vkramskikh 
https://github.com/facebook/react/issues/14994#issuecomment-618551379
I use this custom hook to solve the problem, very effective. https://codesandbox.io/s/cranky-antonelli-ffbf3?file=/src/App.js
But I still hope that there is an official solution, because this problem is easy to cause confusion.

**Comment by trajano** [comment]
As per my [comment](https://github.com/facebook/react/issues/22940#issuecomment-1007728896) regarding @vkurchatkin 's [comment](https://github.com/facebook/react/issues/23055#issuecomment-1003712895) the comment does not explain the cause of the re-render.

**Comment by saxon-y** [comment]
From the implementation details, it seems that the `lanes` property of `fiber` is affected by the last `updateState`, and its value is not `NoLanes`, so there is no logic to judge whether the two `state` are equal, So it results in an extra `rerender` when the two `state` are equal.
eg: [https://codesandbox.io/s/wizardly-kilby-47rpl?file=/src/App.js](url)

**Comment by gaearon** [comment]
Can I ask why the concrete implementation detail is relevant? This can change over time. Generally, we don't expect that people using React would need to know about the concrete implementation tradeoffs.

**Comment by trajano** [comment]
@gaearon Because some of us want to learn how things work.

**Comment by markerikson** [comment]
I will say that this question (or at least what I _think_ is this behavior) has come up a couple times over in Reactiflux, and I was kinda curious myself as to when React bails out early and when it doesn't, because I was surprised at the example output.

**Comment by saxon-y** [comment]
> @saxon-y do you mind pointing a link to the React code itself that shows the implementation detail? You only provided a sample that demonstrates the issue.

https://github.com/facebook/react/blob/12adaffef7105e2714f82651ea51936c563fe15c/packages/react-reconciler/src/ReactFiberHooks.old.js#L1692
The judgment failed when the extra `rerender` was made here, but the same logic for judging `state` is in line 1715

**Comment by saxon-y** [comment]
> Can I ask why the concrete implementation detail is relevant? This can change over time. Generally, we don't expect that people using React would need to know about the concrete implementation tradeoffs.

Just out of curiosity, it was my pleasure learning `react`.
