### ISSUE TITLE
Bug: Issue with document.addEventListener and onClick event bubbling when using Portal

### ISSUE THREAD

**Issue by patricklafrance** [facebook/react#23074]
React version: 17.0.2

Link to code example: https://codesandbox.io/s/friendly-kepler-jj5dy?file=/src/App.js

## The current behavior

I am facing an issue with `document.addEventListener` and React `onClick` event bubbling when using a Portal.

As you can see on the codesandbox, when the button is clicked, the dialog appear then disappear instantly:

![dialog_flickr](https://user-images.githubusercontent.com/794579/148413461-01b8b33d-e5f1-4439-9110-d373ce24b14f.gif)

### How the code works

The code by itself is a basic Dialog, controlled by an `isOpen` state which is set to `true` when the button is clicked and then switch back to `false` when an outside interaction occurs.

The Dialog is used when `isOpen` is `true`, otherwise `null` is used (so the Dialog should not even be mounted when `isOpen` is not `true`):

```jsx
const content = open ? (
  <div {...rest} className="overlay">
    {children}
  </div>
) : null;

return createPortal(content, document.body);
```

When `isOpen` is `true` and the Dialog is mounted, a `useInteractOutside` hook is executed:

```jsx
function Dialog({ children, onClose }) {
  const ref = useRef();

  useInteractOutside(
    ref,
    useCallback((event) => { onClose(event); }, [onClose])
  );

  return (
    <div ref={ref}>
      {children}
    </div>
  );
}
```

The `useInteractOutside` hook is registering an event listener on the `document` element to listen to `click` events. When `event.target` is not a child of the Dialog an `onClose` callback is called.

```jsx
export function useInteractOutside(containerRef, onInteractOutside) {
  const handleDocumentClick = useCallback(
    (event) => {
      if (
        containerRef.current &&
        !containerRef.current.contains(event.target)
      ) {
        if (onInteractOutside) {
          onInteractOutside(event);
        }
      }
    },
    [containerRef, onInteractOutside]
  );

  useEffect(() => {
    document.addEventListener("click", handleDocumentClick);

    return () => {
      document.removeEventListener("click", handleDocumentClick);
    };
  });
}
```

### The React Issue

The reason why the Dialog disappear instantly is because the `useInteractOutside` hook call the `onClose` callback when the open button is clicked.

The following console log show that the `event.target` value of the event catch by the `useInteractOutside` hook is the button element:

![image](https://user-images.githubusercontent.com/794579/148415529-3dfd4692-e8e7-4c19-8dc2-f41863ebee66.png)

Since the Dialog component is not mounted when the button is clicked and `useInteractOutside` have not been executed yet, I don't understand why `document.addEventListener` catch the button click event.

It seems to be an issue with React Portal but I can't tell for sure.

If instead I register my event listener in the capture phase, it does work as expected. The event listener never catch the button click:

```js
document.addEventListener("click", handleDocumentClick, { capture: true });
```

Since the capture phase happens before the bubbling phase my guess is that when `useInteractOutside` register his event listener on the document element, the button click capture phase is already done.

It seems like the bubbling phase is lagging though.

## The expected behavior

I would expect that `document.addEventListener("click", handleDocumentClick);` doesn't catch the button click event since the Dialog component haven't even been mounted when the button click happened.

**Comment by patricklafrance** [comment]
Our current workaround is to use "mouseup" instead of "click":

```js
document.addEventListener("mouseup", handleDocumentClick);
```

I am not sure why it works though.

**Comment by guojin-long** [comment]
This is not a bug in react.   It is how dom event work in bubble phase.

**Comment by patricklafrance** [comment]
@guojin-long do you any additional information about this? I would expect the bug to still happen without a Portal then.

**Comment by JX-Zhuang** [comment]
@patricklafrance 
This is not a bug.
```javascript
// function App()
const handleClick = useCallback((e) => {
    e.stopPropagation();  
    setIsOpen(true);
  }, []);
```

**Comment by patricklafrance** [comment]
@JX-Zhuang not saying it's a bug it might be a choice made by the team. If it is, I think it should be documented. It might be and I haven't find it though.

IMO, using `stopPropagation` is a bad idea. It prevent other handlers from catching the event. I am writing library code, I don't own the button in my case, stopping the propagation of a click is not a desirable side effect.

Again, why the behavior is different when the Dialog is rendered in a Portal?

**Comment by patricklafrance** [comment]
Thanks @guojin-long, you're right the same behavior happens with native JS.

What do you mean by "the app's sibling" ? Do you mean a node which is a sibling of the React "root" node?

**Comment by guojin-long** [comment]
yes.

```html
<body>
	<noscript>
		You need to enable JavaScript to run this app.
	</noscript>
	<div id="root"></div>

	<!--You can create this node dynamically -->
        <div id="portal"></div>
</body>
```

**Comment by wlcharlie** [comment]
@patricklafrance 
Just found out after upgrade your demo (codesandbox) react version to 18.2.0, it worked just what you expected.
Not sure what happened between 17 and 18 🤔
