### ISSUE TITLE
Question about how often state updater functions run

### ISSUE THREAD

**Issue by vinay-khatri** [facebook/react#23075]
Updating the previous state of an array executes code block twice.

```js
const [countries,setCountries] = useState("usa","china","russia")
const [country,setCountry] = useState("uk")
```
Now when i tries to update the old states, react behaves differently

```
setCountry(previous => {
  console.log("I should be printed once and will be printed once")
  return previous
})

setCountries(previous => {
  console.log("I should be printed once but will be printed TWICE")
  return previous.map(country => country);
})

```

Why when i tried to update the state of an array react executed console.log twice?

EDIT : I was unable to reproduce this behaviour in other components of my app. But it still executes twice in the same component. And i am unable to figure out what is causing this.

**Comment by zamarawka** [comment]
Hm, maybe you miss something. Default value for useState hook should be passed as first argument.

```ts
const [countries,setCountries] = useState(["usa","china","russia"]); // looks like you need array here
```

Also, looks like you have some context for call your “set…” functions. Maybe useEffect or event handler? Without context really hard to say why you got 2 logs…

**Comment by ShadmanShakib** [comment]
Yes, you should pass the state inside an array

`const [countries, setCountries]= useState(["usa","china", "russia"]): `

**Comment by nihgwu** [comment]
I guess it's just a typo in the example code, the real problem is that in the first update, the update will be bailed out because the state is referential equal to the previous one, but for the second update, you created a new state instead

**Comment by eps1lon** [comment]
> But it still executes twice in the same component. And i am unable to figure out what is causing this.

You probably have your component wrapped in [`<React.StrictMode>`](https://reactjs.org/docs/strict-mode.html) which executes various functions (such as state updaters) twice.
