### ISSUE TITLE
Bug: useReducer causing spurious "Cannot update a component from inside the function body of a different component" warning

### ISSUE THREAD

**Issue by tamlyn** [facebook/react#23073]
React version: 16.3.1 and 17.0.2

## Steps To Reproduce

Assuming this component, where `setParentState` mutates the state of an ancestor:

```
const Component = ({ setParentState }) => {
  const [localState, dispatch] = React.useReducer((state, action) => {
    action.setParentState("foo");
    return state;
  });

  return (
    <button onClick={() => dispatch({ type: "whatever", setParentState })}>
      click me
    </button>
  );
};
```

1. Click the button
2. Look at the browser console
3. See the warning about "Cannot update a component from inside the function body of a different component"

I've read https://github.com/facebook/react/issues/18178#issuecomment-595846312 and I think I understand what the warning is for, but I don't understand why it's being triggered in this case. I had the impression that `useReducer` was just a convenient wrapper around `useState` but it seems to behave differently.

## Working example

https://codepen.io/tamlyn/pen/vYeEJRb?editors=0110

**Comment by vkurchatkin** [comment]
The problem is here:

```js
const [localState, dispatch] = React.useReducer((state, action) => {
    action.setParentState("foo"); // <- can't do this, reducer is supposed to be a pure function
    return state;
  });
```

**Comment by tamlyn** [comment]
> reducer is supposed to be a pure function

I know that is the case for Redux but it's not obvious to me that it would also be the case here. Is it stated in the React docs anywhere?

**Comment by vkurchatkin** [comment]
It might not be, unfortunately. It seems that it is not explicitly mentioned in `useReducer` description, but there is a hint here: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:

> Class component constructor, render, and shouldComponentUpdate methods
> Class component static getDerivedStateFromProps method
> Function component bodies
> State updater functions (the first argument to setState)
> Functions passed to useState, useMemo, or **useReducer**

As a rule of thumb, all functions provided to React should be pure, unless it is explicitly mentioned designed for side effects.
