### ISSUE TITLE
Go GitHub First

### ISSUE THREAD

**Issue by zpao** [facebook/react#2307]
We're making efforts to move development of React to happen on GitHub first, with Facebook being simply another consumer. Historically we've mostly done it the opposite way. PRs needed to be pulled into FB to ensure we didn't break products, etc. The result of this is that we've moved slow and occasionally just dumped large changesets without any context. And syncing commits out, while it worked, has been awkward and has resulted in some mistakes. (*something about 2 way data flow being dangerous*)

There are a number of things we need to do, both internally and externally. It won't happen overnight. We can use this issue to track the things we need to do externally.

* * *

- [ ] Make lint work consistently (it's noisy and unusable right now).
- [ ] Faster everything (the basic build/test process is too slow, jest helps)
- [ ] Resolve any differences between internal and external code (#1998, React.version, commented-out warnings)

**Comment by spicyj** [comment]
We've been GitHub-first for a few months now.

@zpao Are there more things here or can we close this issue?

**Comment by zpao** [comment]
There are still a few things that can be improved in the process (perhaps "go github only"), but otherwise we're good to go.
