### ISSUE TITLE
Bug: Cannot reproduce builds on npm

### ISSUE THREAD

**Issue by joepie91** [facebook/react#23088]
I am attempting to audit several React libraries from source, but I'm unable to reproduce the builds that are published on npm.

React version: 17.0.1?

## Steps To Reproduce

1. Clone Git repository
2. Check out `v17.0.1` Git tag
3. Install dependencies (`yarn`)
4. Run `yarn build react/index,react-devtools-core,react-is,react-refresh,react-test-renderer,scheduler`
    - (Build command stripped down to reduce auditing surface)

Link to code example: N/A

## The current behavior

The `package.json` in the `react` subpackage specifies `17.0.0` as the version rather than the expected `17.0.1`. Build products do not match those in the `17.0.1` npm package, *nor* those in the `17.0.0` npm package. Considering the seemingly inconsistent Git tagging, I suspect other versions may also be affected.

## The expected behavior

The builds produced should be byte-identical to those on npm, such that auditing from source becomes possible. Currently, there does not seem to be a (documented) way to achieve this.

**Comment by gaearon** [comment]
What differences are you seeing, aside from the version number?

**Comment by amrutha-mukkatira** [comment]
If You  forgot to add the lockfile into the commit. Sometime later, when a second developer pulls the branch, npm won’t know the exact version I intended initially. That information was on the lockfile, and I forgot to include it in the commit.

The ^ symbol in my manifest means I accept any minor release that is equal or greater than 0.21.0. Thus, npm may install newer versions released in the interim like 0.21.1,0.22.0, or 0.23.1, which in theory should be compatible
