### ISSUE TITLE
Adding the Warning when defaultValue = {Symbol | Function}

### ISSUE THREAD

**Issue by michaelCHU95** [facebook/react#23083]
Hi, React Core Team, @gaearon  , @bvaughn , @philipp-spiess. New to open source community. I've been go through the issue #11734 and found out that there's no warning when defaultValue = {Symbol | Function}. I did see some TODOs in ReactDOMInput-test.js and I would like to help.

I tried to add up toErrorDev("Invalid value for prop `defaultValue`") matcher in ReactDOMInput-test.js and got the result of "Expected warning was not recorded". I went to study the /fixtures/dom/src/toWarnDev.js file and find out the argument might not match the condition set in line 125 - 139. But I'm stuck in the understanding of util.format(format, ...args) in line 97, it seems to be a string formatting function to me. 

Am I in the right direction to fix the issue? I'm looking forward to your reply, thanks for your time. 

![image](https://user-images.githubusercontent.com/83269073/148666556-17e6d382-dfda-486c-a444-c65d1ff9431d.png)
This is the warning that I mentioned.

**Comment by Ankishoop** [comment]
Hey i am Ankish Khandelwal And i am beginner in open source . I want to contribute in your organization . I am well aware with reactjs could you plz help me how to start with it??

**Comment by eps1lon** [comment]
@michaelCHU95 Please ask questions related to fixing this in https://github.com/facebook/react/issues/11734 instead. Otherwise this will likely remain unsanswered.
