### ISSUE TITLE
[DevTools Bug] Cannot add node "6194" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by Paul171** [facebook/react#23099]
### Website or app

Code Sandbox app

### Repro steps

1. Clcik inspect from Google Chrome
2. Click components 
3. it will show up this message

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.22.0-0229baee2

### Error message (automated)

Cannot add node "6194" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26181:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24367:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24533:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53958:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#21636) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
