### ISSUE TITLE
React 18 

### ISSUE THREAD

**Issue by kajweb** [facebook/react#23105]
This is a non-compliance issue。

I am referencing a third-party component, but there is an input whose value I cannot modify. By looking at the source code, we can see that the data of this component runs inside the component using useState.
**But I can't modify the code of the third-party component，I can only modify the code of the parent component.**

if input does not expose state or Ref, is there any black magic to get/modify the component's useState method?

![image](https://user-images.githubusercontent.com/2993320/149443199-bbedf947-d68d-49e9-b9de-c65bd0146e83.png)

**Comment by gaearon** [comment]
No.
