### ISSUE TITLE
Bug: Returns 'undefined' hook state when accessed by a child component

### ISSUE THREAD

**Issue by imran-prog** [facebook/react#23110]
Hey, basically the issue is that I am trying to get data from an API inside a state but it returns **undefined** if I reload the webpage, whereas if I comment and uncomment it in the same session it works fine. I have even tried to find the solution on the internet where seems that the user has faced the same problem before but their solution didn't solve mine.

React version: 17.0.2

## Steps To Reproduce

1. Clone https://github.com/imran-prog/react-js
2. Change directory to react-rmdb
3. npm start
4. click any movie and you will find the issue showing in the console

## Code
1. This is where I am trying to get my data in **components/MovieInfo/index.js**. I am trying to fetch Directors from the state. To see the working just comment this div and uncomment it after it shows data. The directors name will be shown in end of the page
```
<div className='director'>         
    <h3>DIRECTOR{movie.directors.length > 1 ? 'S' : ''}</h3>
    {movie.directors.map(director => (
        <p key={director.credit_id}>{director.name}</p>
    ))}
</div>
```
2. And my hook file is located in hooks directory **useMovieFetch.js**
```
setState({
    ...movie,
    actors: credits.cast,
    directors
})
```
3. And **Movie.js** in components directory is the parent component

Link to code example: https://github.com/imran-prog/react-js/tree/master/react-rmdb/src

## The current behavior
Returning undefined 'directors' object 

## The expected behavior
Show Director's from the object

**Comment by gaearon** [comment]
I'm going to close this because I don't see a compelling reason why you'd think there's a bug in React rather than somewhere in your code. I suggest to start with Q&A sites like StackOverflow. If you narrow it down to a simple example in CodeSandbox where you can demonstrate React itself has a bug, we'd be happy to take a look.
