### ISSUE TITLE
beforeunload event not firing in ReactJS but working in standard javascript.

### ISSUE THREAD

**Issue by oneno** [facebook/react#23128]
OS: 5.14.21-2-MANJARO, Windows7
Browser: Firefox 95.0.2, Brave Version 1.33.106 Chromium: 96.0.4664.110, and Gnome Web 41.3
React: 17.0.2, 15.5.4

Codebase: https://github.com/azat-co/react-quickly/tree/master/ch05/note

Can replace react.js and react-dom.js with respective versions for 17.0.2 in the note/js folder for the codebase url.

After running the program, there are no errors. However, changing tabs or closing the tab does not launch a confirmation dialog.

This **[article](https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/)** suggests using event **visibilityState** for displaying the confirmation dialog.

After modifying **note.jsx** receive a confirmation dialog when switching tab however, the page running the application loses focus and the clicked tab gets focus. The application page should not lose focus. Still able to close tab running application:

```
class Note extends React.Component {
    confirmLeave(e) {
      let confirmationMessage = 'Do you really want to close?'
      //e.returnValue = confirmationMessage     // Gecko, Trident, Chrome 34+
      //e.returnValue = confirm(confirmationMessage)     // Gecko, Trident, Chrome 34+
      //return confirmationMessage              // Gecko, WebKit, Chrome <34
      if (window.confirm(confirmationMessage)) {
        e.returnValue = confirmationMessage
      } else {
        e.preventDefault();
      }
      return confirmationMessage
  }
    componentDidMount() {
      console.log('Attaching confirmLeave event listener for beforeunload')
      this.props.document.addEventListener('visibilitychange', this.confirmLeave)
      window.addEventListener('beforeunload', this.confirmLeave)
    }
    componentWillUnmount() {
      console.log('Removing confirmLeave event listener for beforeunload')
      this.props.document.removeEventListener('visibilitychange', this.confirmLeave)
      window.removeEventListener('beforeunload', this.confirmLeave)
    }
    render() {
      console.log('Render')
      return <div>Here will be our input field for notes 
        (parent will remove in {this.props.secondsLeft} seconds)</div>
    }
  }
```

The following javascript code works as required to prevent tab from being closed or switched:
```<!DOCTYPE html>
<html>
<body>
	<h1>Demo: confirm()</h1>
	<p id="msg"></p>
	
	<script>
		 var userPreference;

		if (window.confirm("Do you want to save changes?") == true) {
			userPreference = "Data saved successfully!";
		} else {
			userPreference = "Save Canceled!";
		}

		document.getElementById("msg").innerHTML = userPreference; 

    </script>
</body>
</html>```

**Comment by gaearon** [comment]
`beforeunload` is a DOM event and there is nothing React can do to make it fire or not fire. So far I don't see any indication that this should be a bug in React. For this reason I'll close and suggest you to seek help on resources like StackOverflow. If you have good evidence that this is a bug in React, please provide a minimal reproducing example demonstrating the bug.

**Comment by oneno** [comment]
I'm just wondering why the **[original code](https://github.com/azat-co/react-quickly/tree/master/ch05/note)** produced the behaviour more than a year ago but no longer displays the dialog?

See the following images:

![fig5 6](https://user-images.githubusercontent.com/16865896/150909101-119e2c45-057c-43e1-9dcf-1a28c8aad9f0.jpg)

![fig5 8](https://user-images.githubusercontent.com/16865896/150909130-dd658802-878d-4554-aa94-54b6e108b9fd.jpg)

![fig5 9](https://user-images.githubusercontent.com/16865896/150909138-d888e9ae-4212-405f-8074-f2075ef743fb.jpg)
