### ISSUE TITLE
i installed the chrome extension on chrome browser but cant still inspect a react page . it keeps telling me that this is not a react page

### ISSUE THREAD

**Issue by dimmysophy** [facebook/react#23127]

**Comment by bvaughn** [comment]
I'm sorry you ran into this problem. Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please tell us more about:
* Which version of Chrome you're using
* Which website(s) you're trying to inspect that it isn't working on
* What other Chrome extensions you have installed (as they may be interfering with React DevTools).

**Comment by miltosdoul** [comment]
I think I had this issue too the first time I tried to use the extension. Try checking different pages that are known to use react (e.g. Netflix, Codecademy etc.) and check the extension settings for anything that might be prohibiting the extension from working correctly.

**Comment by Cwarcup** [comment]
Make sure you refresh the page after installing the extension. 

Additionally, double check that you've given React Developer Tools access to "Allow access to file URLs". This can be done by right-clicking on the extension, click "manage extension" and scrolling down to "Allow access to file URLs." 

![Screen Shot 2022-01-24 at 3 56 45 PM](https://user-images.githubusercontent.com/88569957/150885078-82aa9d56-3eeb-4467-9395-fc3e9a8db4bd.png)

**Comment by dimmysophy** [comment]
Thanks Brian for reaching out to me. The issue has been resolved and it was
from my browser. I needed to update it. Thanks so much
