### ISSUE TITLE
Bug: controlled input range does not receive all onChange events 

### ISSUE THREAD

**Issue by jedierikb** [facebook/react#23120]
React version: 17 or 18

## Steps To Reproduce
Grab the input range slider knob.  Move it around.
While the knob itself does not move, as it is a controlled component with a value is permanently set to `0`, note that an `event.target.value` from `onChange` cannot reach the `min` lower bound.

Link to code example:
https://codesandbox.io/s/dazzling-bas-0cy26?file=/src/index.js

## The current behavior
Slide the knob to the left and never get `event.target.value` at the min value.  Slide to the right, and you do get `event.target.value` at the max value.

Note that a stream of `onChange` events continue when you slide to the right (shown as changing colors in the demonstration), but not when you slide to the left.

## The expected behavior
You should be able to get an accurate `event.target.value` from events when sliding left or right, even if not updating the value.

**Comment by sunderls** [comment]
This could be reproed without React 
https://codesandbox.io/s/cold-currying-41bgg?file=/public/index.html
I guess not an issue should be resolved by React
