### ISSUE TITLE
Chrome extension is flagging every page as "using a production build of React"

### ISSUE THREAD

**Issue by JamelHammoud** [facebook/react#23133]
I've noticed that every page I visit is being flagged as using a production build of React, even though I know that these pages aren't built on React. 

The following are examples of pages that, according to the Chrome extension, "use" React:
* https://techcrunch.com/
![image](https://user-images.githubusercontent.com/55815579/149941732-44063f27-f32c-4744-8d10-79494738d99e.png)

* https://www.nytimes.com/
![image](https://user-images.githubusercontent.com/55815579/149941713-272543ad-189c-4374-81b9-bea14b76a1ae.png)

* https://stackoverflow.com/
![image](https://user-images.githubusercontent.com/55815579/149941648-3ae9ed18-c270-48cf-a040-9b17b40d2990.png)

(Keep in mind that although I've listed pages, it is flagging _every_ page I visit (excluding Google search) as being build with React)

**Comment by harish-sethuraman** [comment]
This issue was already reported and closed
- https://github.com/facebook/react/issues/23107


This doesn't seem to be an issue with react dev tools. Check out the following issue for more context
- https://github.com/zalmoxisus/redux-devtools-extension/issues/829
