### ISSUE TITLE
Issue while running the react solution says "There might be a problem with the project dependency tree"

### ISSUE THREAD

**Issue by archana1archu** [facebook/react#23160]
I am using a react solution which is been created using creat-react app command. It's been running in all my team members system except mine.
While troubleshooting we found out that it is running on the systems having lower vesions of OS(lesser than 20H2). Mine OS version is 20H2, where is giving error as below
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/97892367/150495357-091f5edf-ef9b-4913-ad31-e8f13dabff94.png)

I have tried all the solution provided in this image but no luck.
Can you please let us know if there is any patch available for react for this issue.
Your help will be highly appreciated.
Thanks

**Comment by eps1lon** [comment]
This issue is related to Create React App which is released from https://github.com/facebook/create-react-app. Please open an issue on their repository.
