### ISSUE TITLE
Bug: Error: Should have a queue. This is likely a bug in React. Please file an issue.

### ISSUE THREAD

**Issue by marya7** [facebook/react#23174]
Hello,

I am getting an error (tried also with the latest version 17.0.2)

Error: Should have a queue. This is likely a bug in React. Please file an issue.

![image](https://user-images.githubusercontent.com/25663804/150809662-5fb84ac0-ae95-46d4-8f9a-5eefccf67cd2.png)

**Comment by salazarm** [comment]
Could you please provide a minimal repro in codesandbox?

**Comment by marya7** [comment]
Sadly, not, the error appears in a large production code.

**Comment by salazarm** [comment]
Can you check if it's fixed in the latest version of React? IIRC I've encountered this bug in the wild as well and what mitigated it for me was reordering hooks around (and adding artificial component boundaries). I speculate it might be related to using setState in render but can't say for sure.

**Comment by stoplion** [comment]
Getting same error as of this morning

**Comment by marya7** [comment]
> Can you check if it's fixed in the latest version of React? IIRC I've encountered this bug in the wild as well and what mitigated it for me was reordering hooks around (and adding artificial component boundaries). I speculate it might be related to using setState in render but can't say for sure.

I got the same error when upgrading to latest version

**Comment by gaearon** [comment]
“I also get it” comments are not helpful, unfortunately. We won’t be able to help you without a reproducing case so please try to create one.
