### ISSUE TITLE
React 18's whole hydration mismatch business

### ISSUE THREAD

**Issue by DuCanhGH** [facebook/react#23177]
So yesterday I decided to try to use React 18 again after 2 or 3 weeks of returning to React 17 because React 18 crashed my whole app for some weird reason (an unknown hydration mismatch again), as React 17 was rendering weird stuff (I saw some broken components, which aren't broken somewhere else in the app) but then again React 18 loves to freeze the whole app to throw hydration mismatches errors and then Node comes right after with its "process is not defined" thing. So, can I know whether it is going to be possible to see what mismatched between the server-side rendered HTML and React? :)

For now, this is the behaviour: 
https://ibb.co/2NY4x1Y

These are the components:

(renderToString API in server.js)
https://ibb.co/6BPGb21

(AppRoot in client.js)
https://ibb.co/zPpM71M

(hydrateRoot API)
https://ibb.co/0VnZ0tL
https://ibb.co/yVXVRtk

Thank you :) It's really confusing and I don't really know how to resolve, but I guess it's related to some conditional rendering within the app? I've figured out how to use renderToPipeableStream, so I hope I can resolve this as fast as possible :D

**Comment by gaearon** [comment]
> React 18 loves to freeze the whole app to throw hydration mismatches errors and then Node comes right after with its "process is not defined" thing

It is very difficult to interpret what you mean to say here. It would help if you could provide a concrete description of the behavior difference you’re running into. (What does “freeze” mean here? What is the “process is not defined thing”?)

We also can’t really do any meaningful debugging from the screenshots. A minimal reproducing example would be helpful.

**Comment by DuCanhGH** [comment]
@gaearon thanks for the reply :) Right, so it kind of stay uninteractive for a few seconds after console logging those errors "Uncaught error: An error occurred during hydration. The server HTML was replaced with client content" and then Node would console an error like
`
Uncaught ReferenceError: process is not defined
    4043 blank line 135926 > injectedScript:2
    r blank line 135926 > injectedScript:2
    8048 blank line 135926 > injectedScript:2
    r blank line 135926 > injectedScript:2
    8641 blank line 135926 > injectedScript:2
    r blank line 135926 > injectedScript:2
    <anonymous> blank line 135926 > injectedScript:2
    <anonymous> blank line 135926 > injectedScript:2
    <anonymous> blank line 135926 > injectedScript:2
    overlay client.js:135926
    be index.js:1
    overlay client.js:135926
    overlay client.js:135926
    promise callback*./node_modules/.pnpm/react-error-overlay client.js:135926
    overlay client.js:135926
    t index.js:1
    React 7
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    scheduler client.js:145065
    scheduler client.js:145127
    Webpack 16
blank line 135926 > injectedScript:2:13158
`
and add an invisible iframe tag (like this <iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: medium none; z-index: 2147483647;"></iframe>) on the top of the app, making the app totally uninteractive until I delete that iframe...

I think I can cope with it, but it feels more, you know, painful to do so

I'll try to recreate a reproducing example, should it be possible, because there is a chance of this being a specific issue with my app.

**Comment by DuCanhGH** [comment]
@gaearon so uh, I decided to take your renderToPipeableStream example as a boilerplate to make a reproducing example and after updating react & react-dom to their rc versions and run npm start, the app crashed due to hydration errors.

Holy crap, a lot must have changed since that Alpha build

**Comment by DuCanhGH** [comment]
@gaearon I saw some weird stuff. Running your renderToPipeableStream on Chrome and Firefox returned different things. On Firefox it crashed due to hydration errors, whereas on Chrome nothing happened.

I'm going to try my own app on Chrome, thank you for you guys' support and hard work :) 

If it works, I'm going to use that new API, because it looks pretty interesting

**Comment by gaearon** [comment]
It's hard to help without a reproducing example. But we've added some error logs and fixed mistakes that caused them to be suppressed. So you should have more information about what caused the issue if you use the latest experimental builds.

**Comment by DuCanhGH** [comment]
Thank you :) I'll try, but I'd guess the problem is just mine. Sorry for disturbing, aha
Still have a lot to make the new APIs work for me, but I hope this will be done soon

**Comment by DuCanhGH** [comment]
@gaearon I think I now know what is causing the issue, turns out to be the navigation bar, specifically because it uses a cookies to determine which navbar to show (something like this: cookies.get("nav") === "1" ? <Nav1 /> : <Nav2 />). I figured that out when I change "1" to "2" and then suddenly <Nav2 /> is the one triggering hydration errors instead of <Nav1 />
Maybe I will look further into why, thanks for your help xD And thank you all for React 18 :)
