### ISSUE TITLE
Bug: use useState(), input a two-dimensional array, but got an empy array

### ISSUE THREAD

**Issue by FarajMujey** [facebook/react#23183]
React version: 17.0.2

## Steps To Reproduce

```js
// callids = [{...}, {...}, {...}], then I will use lodash to chunk this arrary
const _paged = _.chunk(callids, 10); // Object[][]: -> [ [{}, {}, {}] ]
const [pagedCallids, setPagedCallids] = useState(_paged)
```

## The current behavior

The variable pagedCallids is pointed to an empty Array.

```js
console.log(pagedCallids) // []
```

But in the useEffect() callback block, it's okay!

```js
// asc is a flag to switch sort order
useEffect(() => {
  if (asc) {
    sortedCallids.sort(
      ({ calltime: t1 }, { calltime: t2 }) => Date.parse(t1) - Date.parse(t2)
    )
  } else {
    sortedCallids.sort(
      ({ calltime: t1 }, { calltime: t2 }) => Date.parse(t2) - Date.parse(t1)
    )
  }
  setPagedCallids(_.chunk(sortedCallids, 10)) // this is worked
}, [asc])
```

## The expected behavior

variable `pagedCallids` should return a two-dimensional array, like this `[ [{...}, {...}, {...}] ]`

**Comment by vkurchatkin** [comment]
It's impossible to say what happens, since "Steps To Reproduce" section doesn't actually contains steps to reproduce.
But most likely `_paged` is just an empty array initially, so state is initialized as empty array and doesn't update, unless you call `setPagedCallids`

**Comment by FarajMujey** [comment]
Nice to hear from u! But the array is really not empty, it has 3 objects. But it’ll no longer important. I use another way to solve the problem. Thank you!







------------------ Original ------------------
From: Vladimir Kurchatkin ***@***.***&gt;
Date: Wed,Jan 26,2022 7:23 PM
To: facebook/react ***@***.***&gt;
Cc: FarajMujey!! ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [facebook/react] Bug: use useState(), input a two-dimensional array, but got an empy array (Issue #23183)





 
It's impossible to say what happens, since "Steps To Reproduce" section doesn't actually contains steps to reproduce.
 But most likely _paged is just an empty array initially, so state is initialized as empty array and doesn't update, unless you call setPagedCallids
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
