### ISSUE TITLE
The ultimate solution for server side render, a simple function...

### ISSUE THREAD

**Issue by onzag** [facebook/react#23186]
Please allow for a beforeServerRender function that is async and returns a promise that only executes in the server context and only exists on instance types.

This literally solves any issue regarding Server Side Render and it's extremely simple, why, because it allows you to set the initial state asynchronously, meaning you can fetch the resources you need and set them in the state, allowing for dynamic trees.

On the client side you often get these async resources later and modify the tree, but that's bad for SSR, and when you get these resources you can setup an accumulator and they will be available on the client side, the result is flawless SSR.

I made a working version of react dom 16 with this modification a year ago and the changes were minimal, I've been using in production successfully, I cannot get them to work on react-dom 17 as for some reason it fails to ship my modifications; but the SSR has worked flawlessly and I dare to say it's a way better solution than suspense, and it can be extended by 3rd parties.

And the SSR can be activated or deactivated, so if it fails, the default can be served, and not hydrated, it's extremely flexible.

https://www.npmjs.com/package/@onzag/react-dom/v/16.14.0-custom.0

This doesn't work exactly as in the modification I did, because I used contexts to pass the accumulator, but this is my proposal in an example scenario.

```javascript
class FetchText extends React.Component {
  constructor(props) {
     super(props)
     this.state = {
        data: typeof window !== "undefined" && window.SSR ? window.SSR[props.url] : null
     }
  }
  async componentDidMount() {
    if (!this.state.data) {
      this.setState({
         data: await (await fetch(props.url)).text();
      })
    }
  }
  async beforeServerRender(serverDataAccumulator) {
    const data = serverDataAccumulator[props.url] || await getDataFromDatabase(props.url);
    serverDataAccumulator[props.url] = data;
    this.state = {
      data,
    }
  }
  render() {
    return this.state.data;
  }
}
```

```javascript
const accumulator = {};
try {
  const html = await ReactDOM.renderToStaticMarkup(app, accumulator);
  res.send(`<html><body><div id="app">${html}</div><script>window.SSR = ${JSON.stringify(accumulator)}</script></body></html>`);
} catch {
  // no window.SSR, no hydrate possible, handle client side
  res.send(`<html><body><div  id="app"></div></html>`);
}
```

This doesn't even have to be part of the standard spec, because it can be excluded into a function, the components will still be fully compatible but have special SSR functionality when rendered into a specific mode; this means it is fully backwards compatible.

I have been using this in production, using the context procedure, and it works flawessly; I can SSR everything under the sun.

With this procedure you may also accumulate things for JSS, fonts, even usage specific, literally anything can be SSRd; this is excellent for SEO, and it's backwards compatible with everything in react right now.

**Comment by onzag** [comment]
I am also willing to make this happen if I may get some help on modifying the source and making some form of PR, I've been struggling a lot with the react codebase.

Maybe even the context procedure that is in the standard method that I created in react dom 16 is safer?... because it allows for namespacing, and passing different accumulators, however implementation and usage can be more complicated than while having a global accumulator.

This is what JSS does to render CSS you pass an accumulator in a context during server render, the component picks the accumulator and stores the data, the only difference is that this is async.

**Comment by onzag** [comment]
Next.js has a functionally identical solution.

Either works, they are in a way, identical in capability, I'd assume context in react would represent the standard initial props given that can be modified.

https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props

**Comment by onzag** [comment]
`getDerivedServerSideStateFromProps(props, state)`

**Comment by LifeIsStrange** [comment]
It seems like Nuxt (for Vue.js) provide a similar hook -> https://github.com/nuxt/nuxt.js/blob/cf6b0df45f678c5ac35535d49710c606ab34787d/test/fixtures/basic/pages/special-state.vue
