### ISSUE TITLE
Server-side Error Boundaries in React 18 

### ISSUE THREAD

**Issue by SuperOleg39** [facebook/react#23184]
Hello!

Can't find any information about Error Boundaries support for server-side rendering.
Maybe core team have some plans or RFC for universal Error Boundaries implementation?
Interested in the context of new [Suspense SSR Architecture](https://github.com/reactwg/react-18/discussions/37).

Know about trick with [dangerouslySetInnerHTML](https://gal.hagever.com/posts/react-error-boundaries-and-ssr), but really want to use more native alternative.

**Comment by gaearon** [comment]
They are not currently supported, and there is no concrete plan at this point.
However, React 18 includes a different recovery mechanism on the server that relies on Suspense boundaries:

https://github.com/reactjs/rfcs/pull/215

Hope you find this helpful!

**Comment by SuperOleg39** [comment]
> They are not currently supported, and there is no concrete plan at this point.
> However, React 18 includes a different recovery mechanism on the server that relies on Suspense boundaries:
> 
> https://github.com/reactjs/rfcs/pull/215
> 
> Hope you find this helpful!

Thanks you for the answer!
Will try a new mechanism.
