### ISSUE TITLE
Bug: console log stopped working for props on 17.0.0

### ISSUE THREAD

**Issue by darklight9811** [facebook/react#23194]
React version: 17.x.x

## Summary
When debugging, I usually place console log directly instead of wrapping it in a function, this used to work for earlier versions than 17. Reading the change log, I didn't see this as a intended change.

## Steps To Reproduce

1. on a input a prop (can be a input onChange), insert console log directly: `<input onChange={console.log} />`

Link to code example:
https://codesandbox.io/s/crazy-sanderson-mmy0b

## The current behavior

onChange ignores console log

## The expected behavior

For the onChange to be printed on the console

**Comment by Thedineshk24** [comment]
> React version: 17.x.x
> 
> ## Summary
> When debugging, I usually place console log directly instead of wrapping it in a function, this used to work for earlier versions than 17. Reading the change log, I didn't see this as a intended change.
> 
> ## Steps To Reproduce
> 1. on a input a prop (can be a input onChange), insert console log directly: `<input onChange={console.log} />`
> 
> Link to code example: https://codesandbox.io/s/crazy-sanderson-mmy0b
> 
> ## The current behavior
> onChange ignores console log
> 
> ## The expected behavior
> For the onChange to be printed on the console

hey inside **onChange={() => console.log(props)}**
is still working 
please check this => [https://codesandbox.io/s/zen-silence-rl6nh?file=/src/App.js](url)

**Comment by darklight9811** [comment]
@Thedineshk24 yes, but sometimes I receive more than one argument in a prop, and wrapping the console log just for it to work is a nuisance. Other times I don't know how many arguments to expect, other times I just want to be quick about it.

Anyway I believe this is a bug because they didn't clearly say on the changelog this was intended, and I don't see a reason to disable this behavior.

**Comment by Mohammadwasifbalti** [comment]
@darklight9811 If the number of arguments is not known then you can use this:
**onChange={(...props)=>console.log(props)}**
You will get those arguments in an Array

**Comment by darklight9811** [comment]
@gaearon may I close this then?

**Comment by gaearon** [comment]
Yep, we can close this.

**Comment by piotros** [comment]
When you put `console.log` to debug your code but `console.log` is what has to be debugged...

![avatars-000342155287-3aw4j1-t500x500](https://user-images.githubusercontent.com/3486023/154704114-ac1fbbfb-54d2-48bb-b1e1-9c4f8907ea6a.jpeg)

**Comment by Thedineshk24** [comment]
> When you put `console.log` to debug your code but `console.log` is what has to be debugged...
> 
> ![avatars-000342155287-3aw4j1-t500x500](https://user-images.githubusercontent.com/3486023/154704114-ac1fbbfb-54d2-48bb-b1e1-9c4f8907ea6a.jpeg)

Nyc joke 🤣
