### ISSUE TITLE
Bug: Different rendered Instances does not re-run the useEffect hook

### ISSUE THREAD

**Issue by ahmad2smile** [facebook/react#23200]
React version: 17.0.2

## Steps To Reproduce

1. Render 1 Components twice (different instances) conditionally with Object mapping
2. Log/Check `useEffect` not being re-triggered

Link to code example: https://codesandbox.io/s/beautiful-tree-5b282

## The current behavior

When different instances of a component are rendered with an Object Map, the component does not re-render causing `useEffect` hook that should only be triggered on initial render to skip.

Following does not re-render (hook is not re-triggered)

```tsx
<parent>
         {
            {
              a: <BasicComponent tab={tab} message={"working"} />,
              b: <BasicComponent tab={tab} message={"working"} />
            }[tab]
          }
</parent>
```

If component has a wrapper differentiating it from 2nd instance then it does re-render exactly how expected.

Following re-renders (hook is triggered)

```tsx
<parent>
         {
            {
              a: (
                <>
                  <BasicComponent tab={tab} message={"working"} />
                </>
              ),
              b: <BasicComponent tab={tab} message={"working"} />
            }[tab]
          }
</parent>
```

## The expected behavior

Different instances should re-render (i.e Initial Render Hook should be triggered on each switch) with conditionally rendered.

**Comment by bvaughn** [comment]
This isn't a bug. It highlights how React's reconciliation works.

In your "working" case, you render a _different tree structure_ when you switch between tabs:
```js
{
  a: (
    <>
      <BasicComponent tab={tab} message={"working"} />
    </>
  ),
  b: <BasicComponent tab={tab} message={"working"} />
}[tab]
```

In one case you render a fragment wrapper and in the other case, just the component by itself.

In your "broken" case, you render the same component (as far as React is concerned):
```js
{
  a: <BasicComponent tab={tabNotWorking} message={"not working"} />,
  b: <BasicComponent tab={tabNotWorking} message={"not working"} />
}[tabNotWorking]
```

Either way, you end up rendering:
```js
<BasicComponent tab={tabNotWorking} message={"not working"} />,
```

If you _want_ to ensure a re-mount always happens, you can use a `key`:
```js
{
  a: <BasicComponent key="a" tab={tab} message={"not working"} />,
  b: <BasicComponent key="b" tab={tab} message={"not working"} />
}[tab]
```

You could also remove the dependencies array from your effect so it runs every time:
```js
effect(() => {
  // ...
}); // <- No "[]"
```

Your call!

**Comment by ahmad2smile** [comment]
This was very insightful. The `key` based "workaround"/different approach of handling instances, is very useful.
