### ISSUE TITLE
Bug: SetStateAction in useState hook does not stricly check types

### ISSUE THREAD

**Issue by mikallojjus** [facebook/react#23205]
Setting useState's state via SetStateAction function allows untyped properties.

```
type SomeState = {
  key1: boolean;
  key2: boolean;
};

const [, setSomeState] = useState<SomeState>({
  key1: true,
  key2: true
});

setSomeState((prevState) => ({
  ...prevState,
  propertyThatDoesNotExist: "hello!" // Typescript error should be shown
}));
```

## The current behavior
`propertyThatDoesNotExist` does not exist in useState type, but is still being set. Typescript error is not shown.

## The expected behavior
Typescript error should be shown

## useState type definitions
```
type SetStateAction<S> = S | ((prevState: S) => S);

function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];  
```

**Live demo:** https://codesandbox.io/s/stupefied-hooks-kwe7c?file=/src/App.tsx
**React version:** 17.0.2

**Comment by slowWriting** [comment]
You can also reproduce problem with this minimal code:

```
type SomeState = {
	key1: boolean;
	key2: boolean;
};

type SetStateAction<S> = (prevState: S) => S;

const test1: SetStateAction<SomeState> = (prevState) =>
	({
		...prevState,
		propertyThatDoesNotExist: 'hello!',
	});
```

Seems like a problem with typescript.

**Comment by bvaughn** [comment]
The React team doesn't maintain TypeScript types- even ones for React. This bug should be filed for either TypeScript (which it seems like it [has](https://github.com/microsoft/TypeScript/issues/7547)) or in the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped).
