### ISSUE TITLE
Bug: Infinite loop at startup

### ISSUE THREAD

**Issue by Vinorcola** [facebook/react#23219]
As soon as I launch my React app in dev mode, the browser crashes because the page goes into an infinite loop logging the following error in the console:

```
react-dom.development.js:3932 Uncaught TypeError: window.hasOwnProperty is not a function
    at restoreAfterDispatch (react-dom.development.js:3932:59)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3944:9)
    at HTMLUnknownElement.c (rocket-loader.min.js:1:9405)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at commitRootImpl (react-dom.development.js:23086:9)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
    at commitRoot (react-dom.development.js:22985:3)
    at performSyncWorkOnRoot (react-dom.development.js:22324:3)
```
The error is poping in loop in the console (40k+ message within few seconds)

The problem is coming from this specific line of code : https://github.com/facebook/react/blob/4e6eec69be632c0c0177c5b1c8a70397d92ee181/packages/shared/invokeGuardedCallbackImpl.js#L132

This is very boring, especially because it is an infinite loop that crashes everything. It's been a nighmare to get the error location...

React version: 17.0.2
Chrome version: Version 97.0.4692.99 (Build officiel) (64 bits)

## Steps To Reproduce

1. Create a simple file that render a simple HTML element (e.g. `render(<h1>OK</h1>)`)
2. Run the script in the browser

Link to code example:

## The current behavior

The browser tab is crashing because of an infinite loop.

## The expected behavior

No infinite loop! And a rendering of expected content.

**Comment by sg20180546** [comment]
can you give me your code to reproduce error? @Vinorcola

**Comment by gaearon** [comment]
`window.hasEventProperty` definitely exists in the browser environment:

<img width="302" alt="Screenshot 2022-02-07 at 21 06 16" src="https://user-images.githubusercontent.com/810438/152871860-5321c2e4-06dc-4f0a-a102-4037ee50b4ec.png">

Something's wrong with your environment. Maybe some code you're running deletes it somehow, or you have some build process issue that causes the code to be transformed to something else.

In either case, there is no indication that it's a React bug. I suggest to try to create a reduced repro case and narrow it down, which will help you find the cause.

**Comment by Vinorcola** [comment]
I don't have a minimal repro repository right now. But I'm using the generated script via TamperMonkey. It can happen that TamperMonkey shadows the window object.

Now does that mean that React cannot be used within TamperMonkey scripts?
