### ISSUE TITLE
React 18 - `hydrateRoot` fails even on the most basic example when Suspense + Lazy is added

### ISSUE THREAD

**Issue by wintercounter** [facebook/react#23215]
I've created a simple repro here: https://codesandbox.io/s/broken-suspense-2ogh5

![image](https://user-images.githubusercontent.com/963776/151699543-2e2943e2-0889-42d7-beb6-6ec3dfe77b88.png)

I simply created a Lazy loaded component returning `Hello World!` and made the initial root content `Hello World!` as well.

Feels like I'm missing something here. Is Lazy supposed to fail hydration?

**Comment by gaearon** [comment]
You need to put the exact result of a React server side render in HTML. It will include special comment markers without which we can’t hydrate. I don’t think this example does that.

**Comment by wintercounter** [comment]
I switched from `renderToStaticMarkup` to `renderToString` and it's fine now. Thanks for mentioning special comment markers.
