### ISSUE TITLE
[DevTools Bug]: Debugging on separate device is not working, because devtools provide websocket address of localhost

### ISSUE THREAD

**Issue by fehergeri13** [facebook/react#23222]
### Website or app

https://github.com/fehergeri13/devtool-test

## Steps to reproduce
 - On my laptop on my local network
   - Create a react app with `npx create-react-app@latest` and start it with `npm start`
   - Run the devtool with `npx react-devtools`
   - Add the script the `<script src="http://192.168.1.149:8097"></script>` to the `public/index.html`
 - On my tablet with the same local network
   - Open the website on my tablet in safari  with the corresponding ip address: `192.168.1.149:3000`
 - On my laptop
   - Devtool still not connected

## Workaround:

I copied the complete source of the `http://192.168.1.149:8097` into a js file, imported it in the header, and replaced the `localhost` on the last line of the file with the ip address of my laptop, and it was working.

![proof1](https://user-images.githubusercontent.com/7180398/152001120-03f6ff56-84e3-4499-9053-31b74a976f64.png)
![proof2](https://user-images.githubusercontent.com/7180398/152001128-011a0621-ab47-4288-b193-af109535a5df.png)

### How often does this bug happen?

Every time

**Comment by lunaruan** [comment]
Hey! Thanks for reporting this issue! Could you check the script tag you're using to connect to DevTools? The correct script tag is `<script src="http://192.168.86.45:8097"></script>`, but the one you seem to be using is `<script src="http://192.168.1.149:8097"></script>`.

**Comment by fehergeri13** [comment]
Hi

How did you got that IP address?

My laptop ip address is the same what I wrote in the header script tag,
also visible on every screenshot.

I think you are referring your local ip address, but that can differ based
on the router configuration we have.

Also the devtools can't connect, because on the ipad, it tries to connect
to localhost instead of the ip address of my laptop.

**Comment by lunaruan** [comment]
Hey, sorry I realized I misunderstood your question. My bad. Thanks for reporting! Right now the `react-devtools` doesn't support debugging remotely. However, this seems like it'd be a useful feature to support in the future. I'll add a task to address this to the backlog.

Right now, if you want to be able to specify the host/port of devtools, you can either do the workaround you're doing now or use [`react-devtools-core`](https://github.com/facebook/react/tree/main/packages/react-devtools-core) for more fine grained control.
