### ISSUE TITLE
Why `hydrateRoot` isn't showing the diff upon error?

### ISSUE THREAD

**Issue by wintercounter** [facebook/react#23235]
Previously with `hydrate` I could see the difference. Now with `hydrateRoot` I simply get a general error only. How should debug and find what's causing the issue?

```
Uncaught Error: An error occurred during hydration. The server HTML was replaced with client content.
```

**Comment by gaearon** [comment]
I think https://github.com/facebook/react/pull/23207 is supposed to address this. Did you try after it landed on main?

**Comment by gaearon** [comment]
It would be good to have a minimal reproducing case.

**Comment by wintercounter** [comment]
Unfortunately, that callback also gives the same error.

I forked your SSR demo and switched to `renderToString` as that's my case: https://codesandbox.io/s/romantic-orla-ybx8g
I created another fork where I only added the diff, same results: https://codesandbox.io/s/vibrant-swanson-dh03m

I added intentional diff to Sidebar.js, and upgraded React to the latest RC.

You can see it doesn't tell me what's the diff.  I only get `Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.`.

---

There is a weird issue with the first sandbox, just ignore it. First I've got an error that it tried to append another `html` tag into `document` instead of replacing it. I added the `html` tag myself now and made that the document root, now it is inserting 2 `body` tags. Maybe due to the additional analytics script tags or data-attr diffs on `body`? That's an interesting question also btw. A lot of sites are using dynamically injected scripts (like for example Cloudflare apps) that are out of the user's control. How React hydration will fit in this scenario if that makes hydration fail and causes a forced CSR? (Sry for the offtopic).

On the second one after the React rendering `<App />` started to fail when it tries to fallback to CSR, but that's irrelevant also to the case.

**Comment by gaearon** [comment]
This should be fixed by https://github.com/facebook/react/pull/23241. I've done a cursory check and it appears fixed. Can you please confirm?

**Comment by gaearon** [comment]
>First I've got an error that it tried to append another html tag into document instead of replacing it. I added the html tag myself now and made that the document root, now it is inserting 2 body tags. Maybe due to the additional analytics script tags or data-attr diffs on body?

Sorry, this sounds like a separate thing — would appreciate an isolated sandbox showing just that.
