### ISSUE TITLE
Immutability Helpers.update: Would be nice to also include {$inc: }

### ISSUE THREAD

**Issue by totty90** [facebook/react#2325]
There are more, but this one is very important. You can have a list of them here: http://docs.mongodb.org/manual/reference/operator/update/

This would be really useful if you have your updates in some shared space which can be used on the client side and then on the server side. In this way you don't need to re-write the same logic in 2 places.

I don't know if is useful for you, but would be a nice addition.

**Comment by gaearon** [comment]
Per discussion in https://github.com/facebook/react/pull/2352, we don’t plan to add new features in `update()`. Sorry!
