### ISSUE TITLE
react18 strictMode not work same as react17 strictMode

### ISSUE THREAD

**Issue by cqh963852** [facebook/react#23265]
While using react18 createRoot API with StrictMode.

The useEffect's behavior is not same as react17 ReactDom.render.

In React18 the clean function will be execute. But React17 not.

Here is the demo. https://codesandbox.io/s/peaceful-hertz-epw2z

![image](https://user-images.githubusercontent.com/17702287/153338213-a399ab68-e71d-450b-b6d7-2ef954a9f679.png)

**Comment by zheyaoa** [comment]
In React18 , when the mode is development and use strictMode , React will execute function twice to expose question in advance.  https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberBeginWork.old.js#L391
