### ISSUE TITLE
React app works as intended in development mode, but in production mode has another behaviour. 

### ISSUE THREAD

**Issue by RaduHero** [facebook/react#23274]
I made a simple React App as a beginner. My application worked fine on development mode, but after building it ... I saw that it does not work as it worked in development. I am very confuse because of that. There are no errors or warnings anywhere. 

Type of app: Tic-Tac-Toe.

##Behavior
Behavior in development: the app works, buttons on click shows 'X' or 'O' as expected.
Behavior in production: app it's compiled fine. UI shows up, but buttons on click do nothing.

My thinking is that if a part of code runs in a way in development it should runs the same thing also in production. I'm just confuse why both of them does not run in the same way. 

You can test the application in both development and production to see the difference. 

React version: 17.0.2

## Steps To Reproduce

1.Test the app in development mode to see that everything works properly. All the buttons work fine.
2.Test the app in production build to see that has an unexpected behavior and buttons don't do anything.

##Link
Link to my repo with the logical parts of my code there: 

  https://github.com/RaduHero/Tic-Tac-Toe-React-version-/blob/main/src/app.jsx 

If there is a misunderstanding on my part about how React works, I really apologize again! I'm trying to be useful to the community. Thank you very much and have a nice day!

**Comment by Guilherme03** [comment]
Hi @RaduHero, 
My app has the same behavior. How do you solved the problem?

**Comment by RaduHero** [comment]
@Guilherme03 I didn't manage to fix the problem for that project. These days, I've actually moved away from working with React altogether. I'm more into building back-end applications using C# and dabbling with various databases. Wishing you all the best in cracking that problem!
