### ISSUE TITLE
[DevTools Bug]: DevTools failed to load source map

### ISSUE THREAD

**Issue by woigl** [facebook/react#23286]
### Website or app

Inital React App -> npm create-react-app

### Repro steps

1. Created initial react app
2. Typed "npm start" inside app folder
3. Check console of Chrome browser

This is what I get on my console in Chrome "Version 98.0.4758.82 (Official Build) (64-bit)":
![image](https://user-images.githubusercontent.com/17859431/153745907-5822f5f2-4bb4-43d7-b03b-d42edd5d64a7.png)

As these messages are annoying, please let me know how to fix this?

### How often does this bug happen?

Every time

### DevTools version (automated)

4.23.0

**Comment by lunaruan** [comment]
Thanks for

**Comment by woigl** [comment]
Thanks but, the solution is disabling it globally in Chrome, which is not a good solution.

Can't you fix it within the plugin?

No other plugin has given me this problem.
