### ISSUE TITLE
Bug: using useEffect makes the function get the initital state even though I change the state by useState hook

### ISSUE THREAD

**Issue by fightwithtiger** [facebook/react#23284]
React version: 17.0.2

## Steps To Reproduce

1.define a functin component or jsx obj, I call it 'obj' in the following steps;
2.define a state called status, and to useEffect to listen the status change, set a callback in the effect;
3.the callback is try to set the obj value into a new state called newObj;
4.render newObj in the page;

Link to code example:

[demo.txt](https://github.com/facebook/react/files/8055608/demo.txt)

## The current behavior
1.the page show count: 0;
2.click the button--changeCount, and count++, then click the getCount--innner, console.log is printing the initial value of count, this shouldn't happen;
3.click the button-getCount-outside, console.log is printing current value of count, this is correct;
4.use the useCallBack hook to wrap the function named showCount, click the getCount--innner, console.log is still printing the initial value of count, this shouldn't happen;

I want to know why the count is not change. In order to get the current count, I must click the button--changeStatus or set the count into useEffect's deps, these behaviors try to make useEffect to refresh. I want to look for some help for this question. Thanks!

**Comment by guillaumebrunerie** [comment]
I suggest you ask such questions on StackOverflow instead of here, and with a working example, or at least actual parts of your code.

It's hard to understand what your code looks like, for instance I don't see any button, `getCount--inner` doesn't mean anything, your `useEffect` is missing the `Child` dependency, and you should anyway never define a component (capitalized function) inside another component.

**Comment by fightwithtiger** [comment]
> I suggest you ask such questions on StackOverflow instead of here, and with a working example, or at least actual parts of your code.
> 
> It's hard to understand what your code looks like, for instance I don't see any button, `getCount--inner` doesn't mean anything, your `useEffect` is missing the `Child` dependency, and you should anyway never define a component (capitalized function) inside another component.

sorry bro, I pass the code in the issue, but some parts of code didn't show, I replaced it with a download link. You said: 'you should anyway never define a component (capitalized function) inside another component.', but when I use antdesign-table component, I must define columns variable and set it as a table's property, then the columns's content can has jsx by using render props, so I just try to recurring problems, you can change the Child to a Object, but return a jsx which can trigger showCount then render it in the page, click the getCount--inner, it'will get the initial value of count even though you click the changeCount to update count, that makes me confused.

**Comment by guillaumebrunerie** [comment]
"or set the count into useEffect's deps"
Yes, this is how useEffect works. Your effect depends on `count` (indirectly, through `Child`), but you didn't specify either of them in the depency array, so what you observe is perfectly expected. You should read about dependency arrays and use the eslint plugin for hooks to avoid this kind of issues.

**Comment by fightwithtiger** [comment]
Thanks for taking the time to answer my questions
