### ISSUE TITLE
Bug: Inconsistent `useMemo` behavior under `StrictMode` -- initial value is not properly cached.

### ISSUE THREAD

**Issue by thisentirecitymustbepurged** [facebook/react#23295]
## Description

Inconsistent `useMemo` behavior under `StrictMode` -- initial value is not properly cached.

I first noticed the behavior while working on my local builds.

## Sandboxes with identical code: 

With `StrictMode`: https://codesandbox.io/s/mutable-bush-o12fc?file=/src/index.js
Without `StrictMode`: https://codesandbox.io/s/distracted-bhabha-81enn?file=/src/index.js

## Steps To Reproduce

1. Open both sandboxes and compare console output (the code is identical so console output should be the same, but isn't)

![image](https://user-images.githubusercontent.com/20511483/154047555-3a41708f-c3ec-4651-b348-92819252eaf4.png)

**Comment by gaearon** [comment]
Can you provide an example illustrating why this matters in your particular component?

It is *expected* that the memoized function runs twice in Strict Mode, and one of the results is discarded. That does not affect the correctness of your code unless your rendering function or useMemo function is impure. (In your artificial example, it is impure because you are pushing to a global array during render.) Surfacing issues like this is the *purpose* of Strict Mode, so in this case it is working as advertised — the inconsistency shouldn't matter unless your code breaks the rules.

**Comment by thisentirecitymustbepurged** [comment]
I just looked at the docs and I probably could've saved you the time by not raising this. I suppose it is a note to be taken that there are people like me who don't read about what they are using until there are problems.
![image](https://user-images.githubusercontent.com/20511483/154048016-d8f0f936-4e19-45ab-b41a-a4b9e42b1480.png)
I didn't think much of the `StrictMode` in the CRA template and assumed `StrictMode` does not affect how React utilities will behave functionally -- in this case the deps is an empty array, so I expected the memoized value to never change. But the docs clearly state that those hooks will get invoked twice.

I absolutely agree with what you said -- the double invocation should not cause problems if you built your app with the "functional" stuff: top-down flow, pure functions, react hooks, immutability, etc. And given that this is probably what most people are going to do as per guidelines, it makes sense for `StrictMode` to be part of the CRA. 

As for the illustration: I just wanted to generate a reference that gets created _once_ in the lifecycle of the component. 

Some considerations that come to mind for potentially making a (configurable) exception for empty deps to suppress the double invocation for `useMemo` under `StrictMode`: 

1. If the logic is written with the expectation that `useMemo` is only going to be invoked once per lifecycle, logic depending on references that are meant to be created once per lifecycle will not work. You could use `useRef`, but if the creation of the reference is expensive, it is not ideal. 
2. Hypothetical, but existing projects may have legacy stuff that forces you to only create expensive references once to be passed around outside react (or maybe even inside react) for mutations and you don't have the time to refactor whatever that is.
3. 1 & 2 means that people who _want_ to use `StrictMode` may be compromised because of project's legacy.

Still don't think this is worth the effort. Out of thousands who are happily following the guidelines, there will always be few who are forced to be impure by the project's legacy or like it dirty themselves. I am not gonna tell you which one I am.

> This is unnecessary. I think you mean this as a sarcastic joke, but in general, hostile attitude isn’t welcome in the repo and can get you banned. Just something to keep in mind for the future discussion. Let’s focus on the issue at hand. If there is a bug, we want to fix it. If there is a misunderstanding, we want to make the docs clearer.

Yep, it was just a joke, but I see where you are coming from -- this is a global forum and you guys have your guidelines. I just don't spend too much time on github issues or global forums in general, so not very adept in reading the room. Thanks for kindly explaining.

---

Feel free to close the issue. I do not think I have anything else to say. I am happy `StrictMode` staying as is.

**Comment by gaearon** [comment]
Just to be clear, StrictMode is development-only, so in production there is no performance difference. I think I'm missing why creating something (and immediately throwing it away) is a problem since, for example, event handlers and effects only "see" the "retained" version. It would help me to see a code example showing the concrete problem you ran into.

**Comment by thisentirecitymustbepurged** [comment]
Yep, throwing it away immediately is not a problem if you are trying do things the "react way". Which is why I did not provide you with a concrete gist as I was not trying to do things the "react way". Anyways, somewhat minimized gist:

```
import { autorun, makeObservable, observable } from 'mobx'
import { observer } from 'mobx-react-lite'
import React, { useMemo } from 'react'

const View = observer(() => {
  const domRef = useMemo(() => observable({ current: null }), [])
  const { dom } = useMemo(() => new Model({ domRef }), [])

  return <div ref={domRef} />
})

class Model {
  constructor({ domRef }) {
    this.dom = null

    makeObservable(this, { dom: observable.ref })

    const onDomChange = () => this.dom = domRef.current

    autorun(onDomChange)
  }
}
```

Actually, I never had any problems, because my stuff is working perfectly fine -- everything's flowing top down and is inside react. The real reason I started the investigation is because the console logs were "lying" to me. 

I feel like I shouldn't have opened this and wasted people's time, but oh well. And the unrealistic example of "bad code" where arbitrary sitting logic outside react is going to fail under `StrictMode` that I was talking about:

```
import React, { StrictMode, useEffect, useMemo, useState } from "react";
import ReactDOM from "react-dom";

class WillNotEatSomethingDifferent {
  feed(food) {
    console.log("feed", food);

    if (Object.hasOwn(this, "food") && food !== this.food)
      throw new Error("This is not what I had last time!");

    this.food = food;
  }
}

const willNotEatSomethingDifferent = new WillNotEatSomethingDifferent();

function App() {
  const [counter, setCounter] = useState(0);
  const shouldNeverChange = useMemo(() => [], []);

  useEffect(() => {
    if (counter < 2) setCounter((counter) => ++counter);
  }, [counter]);

  // throws under StrictMode
  willNotEatSomethingDifferent.feed(shouldNeverChange);

  // does not throw under StrictMode
  // useEffect(() => willNotEatSomethingDifferent.feed(shouldNeverChange), []);

  return null;
}

// ReactDOM.render(<App />, document.getElementById("root"));

ReactDOM.render(
  <StrictMode>
    <App />
  </StrictMode>,
  document.getElementById("root")
);
```

But this code deserves to fail! Anyways, I really doubt I should have opened this and wasted people's time. But who knows, maybe I am not the first and not the last :D

**Comment by gaearon** [comment]
Got it, this makes sense. Yeah, that's the kind of problem that StrictMode is supposed to help find, so if the code breaks the expectations of React, then it might make sense to remove StrictMode or fix the code.
