### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ken-Sarowiwa** [facebook/react#23308]
Hello @reactjs-bot so i am trying to build a react project but i am getting the following error

ERROR LOG
0 info it worked if it ends with ok
1 verbose cli [ '/home/kenafrica/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/home/kenafrica/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-linux' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild-linux', 'build-linux', 'postbuild-linux' ]
5 info lifecycle client@0.1.0~prebuild-linux: client@0.1.0
6 info lifecycle client@0.1.0~build-linux: client@0.1.0
7 verbose lifecycle client@0.1.0~build-linux: unsafe-perm in lifecycle true
8 verbose lifecycle client@0.1.0~build-linux: PATH: /home/kenafrica/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kenafrica/jisort/client/node_modules/.bin:/home/kenafrica/.nvm/versions/node/v10.16.0/bin:/home/kenafrica/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle client@0.1.0~build-linux: CWD: /home/kenafrica/jisort/client
10 silly lifecycle client@0.1.0~build-linux: Args: [ '-c',
10 silly lifecycle   'export NODE_OPTIONS=--max_old_space_size=4096 && react-scripts build' ]
11 silly lifecycle client@0.1.0~build-linux: Returned: code: 1  signal: null
12 info lifecycle client@0.1.0~build-linux: Failed to exec build-linux script
13 verbose stack Error: client@0.1.0 build-linux: `export NODE_OPTIONS=--max_old_space_size=4096 && react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/kenafrica/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/kenafrica/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid client@0.1.0
15 verbose cwd /home/kenafrica/jisort/client
16 verbose Linux 5.13.0-28-generic
17 verbose argv "/home/kenafrica/.nvm/versions/node/v10.16.0/bin/node" "/home/kenafrica/.nvm/versions/node/v10.16.0/bin/npm" "run" "build-linux"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error client@0.1.0 build-linux: `export NODE_OPTIONS=--max_old_space_size=4096 && react-scripts build`
22 error Exit status 1
23 error Failed at the client@0.1.0 build-linux script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sammy-SC** [comment]
Could you please indicate how is the error connected to React? Please include repro steps. This will help us prioritise the issue.
