### ISSUE TITLE
Strange behavior when rendering two instances of react component

### ISSUE THREAD

**Issue by hayderjebur** [facebook/react#23315]
I have a component that is essentially a table view with rows and columns each row has an edit button, when I click the button it should populate the value of each row this is my goal of the component. Also, I have to render two instances of this component on the same page. The strange thing is when I click on the edit button in the first table, it populates the correct value, but when I click on the second table, it always populates the value of the first table. Moreover, if I console.log the value of the second table, it shows the correct value.
I posted the question on StackoverFlow with formatted codes 
https://stackoverflow.com/questions/71143971/strange-behavior-when-rendering-two-instances-of-react-component/71144058?noredirect=1#comment125760915_71144058

**Comment by salazarm** [comment]
If I had to guess you're making new arrays, but the references within the array are the same even if the new array you make is different.

ex:
```
function editSolution(array, index, newValue, setArray) {
  const copy = [...array];
  copy[index] = {...copy[index]}; // you're probably missing this step, making a copy of the original object.
  copy[index].value = newValue;
  setArray(copy);
}
```

**Comment by hayderjebur** [comment]
Thanks for your reply, the array contains only a string of items:
 const roleAreaArray = ['Store', 'District', 'Region', 'Division', 'Company']
 const modeTypeArray = ['Read/Write', 'Administrator', 'Developer']
, not an object but I did make a copy of array like that: 
export default function SecurityTableRow({ index, areaArray, openModalWithItem }) {
    const copy = [...areaArray]
    let holder = copy[index]
}
here the holder get the correct item but does not showing in modal input

**Comment by salazarm** [comment]
What are the repro steps?
