### ISSUE TITLE
Nasty IE8 user input bug

### ISSUE THREAD

**Issue by syranide** [facebook/react#2331]
1. Use backspace/delete/paste/cut in the input field
2. Undo (notice the entire document revert)
3. Redo or type something
4. :boom: React will throw an invariant and stop to function as the DOM has mutated

Normally, when the DOM updates IE8 will clear the undo history of all inputs. However that does not happen under these circumstances for some reason. I would assume this is because `onChange` listens to many different events and some of them are broken like this.

```
var App = React.createClass({
  getInitialState: function() {
    return {changes: 0};
  },
  handleChange: function(e) {
    this.setState({changes: this.state.changes + 1});
  },
  render: function() {
    return (
      <div>
        <input onChange={this.handleChange} defaultValue="text" />
        {this.state.changes ? <div>{this.state.changes}</div> : null}
      </div>
    );
  }
});

React.renderComponent(<App />, document.body);
```

You can test it yourself here: https://dev.cetrez.com/jsx/2/index12.html

cc @spicyj

**Comment by gaearon** [comment]
We don't support IE8 anymore.
