### ISSUE TITLE
React 18 upgrade: Hydration error while upgrading to react18 

### ISSUE THREAD

**Issue by varunchauhan49** [facebook/react#23310]
I have a NextJs application with React. To explore the possible features in react18. I tried upgrading the react package but seems to get stuck with a hydration error on the screen. Seeing this error I can assume that there is a difference in DOM generated on the server-side with what we have on the client-side but I don’t point to the file or line where the difference exists.

**Error Message: An error occurred during hydration. The server HTML was replaced with client content**

**Screenshot of the stack trace.**

<img width="880" alt="Screenshot 2022-02-16 at 1 52 54 PM" src="https://user-images.githubusercontent.com/12985829/154205253-0b2764b5-95ae-4d44-9e34-5ef089bf26a6.png">

<img width="708" alt="Screenshot 2022-02-16 at 1 53 06 PM" src="https://user-images.githubusercontent.com/12985829/154205236-c1f47565-0041-46ce-99af-6431156bbe3f.png">

PS: I have tried upgrading the nextJS version to 12 but this issue still exists even when I am not enabling experimental flags in the Next config.

**Comment by zhyd1997** [comment]
Maybe need more context, for example, a minimal work example is better.

BTW, take a look at this document: https://github.com/vercel/next.js/blob/canary/errors/react-hydration-error.md

**Comment by salazarm** [comment]
We recently improved this error. It should tell you where it exactly the hydration error is now. Not sure when it'll be synced to Next.js but it's part of the latest alpha version of React
