### ISSUE TITLE
React 18 - hydration of lazy component with sibling fails

### ISSUE THREAD

**Issue by laverdet** [facebook/react#23331]
Hello, I'm having an issue with hydration of SSR components using `renderToPipeableStream` and `hydrateRoot`. I have a minimum reproduction case here: https://github.com/laverdet/react-issue. Just run `npm install; npm start` and navigate to localhost:8000.

The error produced follows:
```
react-dom.development.js:87 Warning: Prop `id` did not match. Server: "async" Client: "after"
    at span
    at Suspense
    at div
```

The relevant bits of implementation are reproduced below--

app.jsx
```js
const Async = lazy(async () => import('./hot.jsx') });

export const app = <div>
	<Suspense fallback={<div>Loading...</div>}>
		<Async />
		<span id="after">after</span>
	</Suspense>
</div>;
```

hot.jsx
```jsx
export default function Async() {
	return <span id="async">async</span>;
}
```

If I wrap `Async` directly in a suspense element it will work: `<Suspense fallback={null}><Async /></Suspense>`

**Comment by gaearon** [comment]
Can you try turning it into a failing test? You can use this one as a base.

https://github.com/facebook/react/blob/40eaa22d9af685c239f9d8d42b454d031791e76d/packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js#L238

**Comment by laverdet** [comment]
Thanks for the suggestion on how to demonstrate this more clearly for the team. I managed to reproduce in the test environment:
https://github.com/laverdet/react/commit/6ab56221d64732c99db4aab9d5540e9dab1b614b

It happens when the server pushes a resolved lazy component but the client hasn't yet downloaded the component and therefore can't render it. I can observe the same workaround where wrapping the lazy component in its own personal `<Suspense />` fixes it.

**Comment by gaearon** [comment]
Thanks! Can you please send it as a PR?

**Comment by acdlite** [comment]
Fixed by #23364

**Comment by dominic-p** [comment]
I seem to be hitting this same error hydrating an SSR rendered tree with `React.lazy` components in React 18.1.0.

If the lazy component has siblings I get:

> Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.

unless I wrap each component in its own `<Suspense>` element.

I forked the SSR code sandbox demo and removed the `<Suspense>` wrapper around the `Comments` component to reproduce the error:

https://codesandbox.io/s/elastic-oskar-vkc2gm?file=/src/App.js:1283-1339

I'm still pretty new to Suspense. Is this expected behavior?

**Comment by gaearon** [comment]
No prob. Sorry we haven’t released the fix in stable yet.
