### ISSUE TITLE
Missing important info in 2014-09-24-testing-flux-applications post

### ISSUE THREAD

**Issue by jim-y** [facebook/react#2333]
**Hi**,

I think the article forgot to mention that you need to put

```json
"jest": {
  "rootDir": "./whatever"
}
```

into `package.json` to make the test suite work. Omitting to put these lines to the npm config resulted in a test error. Namely:

```bash
Found 1 matching test...
 FAIL  lib/stores/__tests__/Store-test.js (0.022s)
● Store › it encountered a declaration exception
  - TypeError: Cannot read property 'INIT' of undefined
```

I think the suite didn't knew where to find resources. If this was mentioned in the article, then sorry, i didn't find anything about it.

Cheers,
Jim

**Comment by zpao** [comment]
Hey, can we followup in an issue in the flux repo? I don't want us editing the flux documentation here since the flux copy is getting updates.
