### ISSUE TITLE
Bug: SetState rerender not working when is not used primitive values.

### ISSUE THREAD

**Issue by hikarocarvalho** [facebook/react#23349]
This bug occurs when the setState is updated using not primitive values, the render not reset the current view in the page.

React version: 17.0.2

Steps To Reproduce: 

1.  Declare one useState, with one object or array-like value. And use the interval to set the state. In this example I create one Timer.
````js
import React, { useState, useEffect } from "react";

export default function Timer() {
  const [timer, setTimer] = useState({
    hour: 0,
    minute: 0,
    second: 0,
  });

  const countTime = () => {
    let timeNow = timer;
    if(timeNow.second < 60){
        timeNow.second ++;
    }else{
        timeNow.second = 0;
        if(timeNow.minute < 60){
            timeNow.minute ++;
        }else{
            timeNow.hour ++;
        }
    }
    return timeNow;
  };

  useEffect(() => {
      setInterval(() => {
        setTimer(countTime());
        console.log(timer);
      }, 1000);
  }, []);
  return (
    <>
      {timer.hour}:{timer.minute}:{timer.second}
    </>
  );
}
````

2. Look at the page and the render does not have any update. But look at the console, you can see the state value updating.

**Comment by gaearon** [comment]
Please see: https://beta.reactjs.org/apis/usestate#ive-updated-the-state-but-the-screen-doesnt-update

Does this help?

**Comment by hikarocarvalho** [comment]
Not much, because the value is incremented before setting the new state.

**Comment by gaearon** [comment]
Code like this:

```js
let timeNow = timer;
timeNow.second++;
setTimer(timeNow)
```

is exactly the same as code like this that I linked to:

```js
obj.x = 10;
setObj(obj); // Doesn't do anything
```

What you want is this:

```js
setObj({
  ...obj,
  x: 10
});
```

which, translated to your example, would be something like

```js
setTimer({
   ...timer,
  second: timer.second + 1
})
```

Please do read the link I sent, it states the exact problem you're facing and links to a page that explains how to fix that problem.

**Comment by hikarocarvalho** [comment]
Thanks for the help, and sorry. I read it the first time, but I couldn't see the connection. Now my problem is solved.
Thank you, and sorry again!!!

**Comment by gaearon** [comment]
No problem! Is there any particular place that you feel could be better expressed in the text?

**Comment by hikarocarvalho** [comment]
Maybe if you use more than one example, with increment to demonstrate this applies to others situations. In the text the first look, it's like the situation only occurs when the value is changed by one static new value. But like I told it's the first look, when I read the text I see the situation is for all using objects or arrays.
