### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by Jayshua** [facebook/react#2334]
Just wondering if you've considered a way to make custom events? Something like this could be used in a parent:

``` jsx
<Component onDelete={this.onDelete}/>
```

Then the component could look like this perhaps:

``` jsx
var Component = React.createClass({
   deleteButtonHandler: function() {
      this.trigger("onDelete", arguments...);
   }
});
```

Of course this might already be possible or been considered and I just didn't find any information on it. Thoughts?

**Comment by yiminghe** [comment]
why not react support trigger method, it's even better to support custom event bubble like this: https://github.com/andreypopp/react-custom-events, then it would be easier for parent/child management (such as: menu/menuitem component)
