### ISSUE TITLE
Bug: React 16.8 and above [keyboard events not working with MAC touch bar in React Js after first submit (on textarea form)] #23344

### ISSUE THREAD

**Issue by varunrajasekhar** [facebook/react#23345]
React version: 17 and 16 above

## Steps To Reproduce

[keyboard events not working with MAC touch bar in React Js after first submit (on textarea form)]

I have a weird issue where MAC touch bar (key input) events (word suggestions) are not working when after I submit the textarea input....The textarea inputs are unable to trigger any keyevents in React (not sure about other frameworks)

Scenario:

Step 1 : Type something in textarea and press Enter.

Step 2 : Try now to enter something via Mac touch bar (there are word suggestions on touch bar that appear) try touching them... no keyboard event is triggering...

Now if we try to type something from the physical keyboard and then use the Touch bar suggestions and we can see that it starts working again....

This issue happens only after clearing or resetting the textarea element...

I need this to work with Mac touch bar just like regular input event....

Created an example in stackblitz: (the javascript way works fine)
React:
https://stackblitz.com/edit/react-er5v6c?file=src%2FApp.js
Javascript:
https://stackblitz.com/edit/js-jxmo1y?file=index.js

Link to code example:

Created an example in stackblitz: (the javascript way works fine)
React:
https://stackblitz.com/edit/react-er5v6c?file=src%2FApp.js
Javascript:
https://stackblitz.com/edit/js-jxmo1y?file=index.js

## The current behavior
cannot type in with mac touchbar suggestions

## The expected behavior
I need it to be able to work with mac touchbar as well

**Comment by mmarkelov** [comment]
@varunrajasekhar I just able to reproduce it without React and even simpler way:

```html
<textarea id="a"></textarea>
```

```js
document.getElementById('a').addEventListener('keydown', (e) => {
  if (e.code === 'Escape' && e.shiftKey === false) {
    document.getElementById('a').value = '';
  }
});
```

So i suppose that it can be not React issue
