### ISSUE TITLE
Bug: React context api Consumer component is not updating when using development version of react

### ISSUE THREAD

**Issue by gaoxiaoliangz** [facebook/react#23380]
React version: 17.0.2

## Steps To Reproduce

- Build the project using production mode and use external react(non-minified development version)
- Start the project using `yarn serve`
- Open `http://localhost:8000/`
- Click on the `add` button

![image](https://user-images.githubusercontent.com/10410606/155973083-3ced529e-1508-4145-9d58-355c7d0b492f.png)

Detailed steps are listed in the repo bellow.

Link to code example:

https://github.com/gaoxiaoliangz/react-context-api-issue

## The current behavior

`Value1` component is not updating.

## The expected behavior

`Value1` and `Value2` both update as the user clicks on the `add` button.

**Comment by eps1lon** [comment]
The context is likely not updating because you have mutliple versions of React in your bundle.

Adding external React to the `index.html` may not be sufficient if your bundler does not know if `react` is marked as an "external" library.

Could you check your bundle if it also contains a build of `react` or `react-dom`?

**Comment by gaoxiaoliangz** [comment]
@eps1lon As you can see in the html template, there is also a production version of React, if you switch to that one, and build again, it will work. Also, in the webpack config, I have already marked react as external.

**Comment by eps1lon** [comment]
> Build the project using production mode and use external react(non-minified development version)

Just to clarify: You build for production but try to use the development version of React?



> Also, in the webpack config, I have already marked react as external.

I think you refer to https://github.com/gaoxiaoliangz/react-context-api-bug/blob/05ad18eccac2bdb84063dd26be90d3e63054a748/config/webpack.config.js#L190-L192?
This is most likely incomplete. Make sure you also mark `react-dom` as external (and include it via unpkg). 
You probably also need to make sure everything in `react` and `react-dom` is marked as external (i.e. `react/*` and `react-dom/*`)

**Comment by gaoxiaoliangz** [comment]
@eps1lon  Added development version of `react-dom` as external as well, then the problem goes away. I guess when using development version of `react` with production version of `react-dom` the `Consumer` component not updating is to be expected? But why the `Value2` component with `useContext` worked in such case?
