### ISSUE TITLE
Bug: unmount component with creating element JSX variable

### ISSUE THREAD

**Issue by parkhojeong** [facebook/react#23398]
React version: 17.0.2

## Steps To Reproduce

1. type and run below code example
2. click change button

Link to code example:
https://codesandbox.io/s/unmount-issue-when-prop-changed-yn12l0

```typescript
const A = ({ val }: { val?: string }) => {
  const [num, setNum] = useState(0);
  useEffect(() => {
    setTimeout(() => {
      setNum(10);
    }, 5000);

    return () => {
      console.log('unmounted');
    };
  }, []);

  return (
    <>
      <div>{num}</div>
      <div>{val}</div>
    </>
  );
};

function App(): JSX.Element {
  const [str, setStr] = useState('');
  const ValA = () => {
    return <A val={str} />;
  };
  return (
    <>
      <ValA />
      <button
        type={'button'}
        onClick={() => {
          setStr('changed');
        }}
      >
        change
      </button>
    </>
  );
}
```

![image](https://user-images.githubusercontent.com/34734102/156394474-da1046d7-2374-4432-9004-da68490a394d.png)
fail case above image is case for my issue

## The current behavior
App show `10` after 5000ms from first render. 
if i click change button, it makes unmount A.

## The expected behavior
i want A component only rerendering after click change 
in diffing algorithm (https://reactjs.org/docs/reconciliation.html), unmount will be triggered by changing tag name. i wonder why A Component is unmounted.

**Comment by parkhojeong** [comment]
babel result is`React.createElement(ValA, null)`. so, is tag name same every re-render?
i expect name of variable ValA is used for tag name that diffing algorithm say.

**Comment by nmain** [comment]
Neither the `Function.name` or any other property of a function is used to determine whether it represents the same component.  It's always just a `===` check.  The documentation you linked isn't perfectly explicit on that, but that's the way it works.

**Comment by parkhojeong** [comment]
> Neither the `Function.name` or any other property of a function is used to determine whether it represents the same component. It's always just a `===` check. The documentation you linked isn't perfectly explicit on that, but that's the way it works.

thanks to your reply. i want to find diffing algorithm in react project. but i cannot find explicit code that you say `the `Function.name` or any other property of a function is used to determine whether it represents the same component`

what do i have to show file or function in react repository? 

in this case, it is not exist in `ReactMount-test.js` in reacting-dom. 
![image](https://user-images.githubusercontent.com/34734102/157259718-999579ca-754f-4ae9-8150-457eab9190d5.png)

**Comment by nmain** [comment]
I believe this is the precise line of code:

https://github.com/facebook/react/blob/v16.13.1/packages/react-reconciler/src/ReactChildFiber.js#L407

**Comment by parkhojeong** [comment]
> Neither the `Function.name` or any other property of a function is used to determine whether it represents the same component. It's always just a `===` check. The documentation you linked isn't perfectly explicit on that, but that's the way it works.

oh it is precise. postfix `reconciler`does reconciliation

last question is that difference `local function` and `external function`
`React.createElement` is same type  but local function is unmounted after re-rendering

- internal function case
![image](https://user-images.githubusercontent.com/34734102/157270705-92a4f062-1a9f-4de5-a619-cdee25675ea6.png)


- external function case
![image](https://user-images.githubusercontent.com/34734102/157270475-b55c46ba-047a-43e4-9f00-815c8a58f19d.png)

**Comment by parkhojeong** [comment]
> I believe this is the precise line of code:
> 
> https://github.com/facebook/react/blob/v16.13.1/packages/react-reconciler/src/ReactChildFiber.js#L407
> 
> Edit: Also see https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md for some more rationale

your lint link proposal is :  https://github.com/yannickcr/eslint-plugin-react/issues/2749
it has same case with me and has more information 
i hope react doc include internal component definition case with more detail

**Comment by eps1lon** [comment]
Closing since this is how the reconciler is supposed to work. Function names wouldn't necessarily be unique across an entire codebase.

It's a recurring mistake that's easy to make. `react/no-unstable-nested-components` from `eslint-plugin-react` should help catching these earlier.

**Comment by parkhojeong** [comment]
> Closing since this is how the reconciler is supposed to work. Function names wouldn't necessarily be unique across an entire codebase.
> 
> It's a recurring mistake that's easy to make. `react/no-unstable-nested-components` from `eslint-plugin-react` should help catching these earlier.

`Function names wouldn't necessarily be unique across an entire codebase`. 
what do you mean `function name`? 

function name is same in this example 
https://github.com/facebook/react/issues/23398#issuecomment-1061906678

**Comment by eps1lon** [comment]
It sounded like you were suggesting using `fn.name` as a key for reconciliation as opposed to using `fn` itself. However, it's not guaranteed that different implementations have a different `name`:

```jsx
// App.js
export default function App() {}

// index.js
import Component from "./App";

function App() {}

// logs "App, App"
console.log(Component.name, App.name);
```

-- https://codesandbox.io/s/function-prototype-name-is-not-unique-7kcqlt
