### ISSUE TITLE
Bug: Fuck Ukraine

### ISSUE THREAD

**Issue by Z1hgq** [facebook/react#23401]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by ZhangDengchuan** [comment]
+1

**Comment by cnmade** [comment]
丢人丢到家了，美团的兄弟就这素质？

**Comment by cnmade** [comment]
To better support Ukraine, you may want to agree to our new kind suggestion:
https://github.com/facebook/react/issues/23403
