### ISSUE TITLE
Bug: Why are there no relevant supporting slogans on the Ukrainian language web page? Please fix it

### ISSUE THREAD

**Issue by BuzzWoods** [facebook/react#23405]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/57121488/156513454-39d14852-0eb1-4e68-98da-2f7660b0edac.png">

I was amused，hypocrisy

**Comment by cnmade** [comment]
and please support new suggest:
https://github.com/facebook/react/issues/23403

**Comment by SaltFish001** [comment]
> I was amused，hypocrisy
It's closed

**Comment by SaltFish001** [comment]
> and please support new suggest: #23403

Closed

**Comment by eps1lon** [comment]
The translations are hosted in different repos. They'll soon be synced with the main repo at which point this banner will appear in the translated versions.

**Comment by SaltFish001** [comment]
> The translations are hosted in different repos. They'll soon be synced with the main repo at which point this banner will appear in the translated versions.

What a official reply, can make laugh all day
