### ISSUE TITLE
ReactTransitionGroup overwrites children's ref prop

### ISSUE THREAD

**Issue by Morhaus** [facebook/react#2341]
`ReactTransitionGroup` uses `cloneWithProps` on each of its children and overwrites their `ref` prop (see [here](https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js#L172)).

**Comment by duro** [comment]
I think this could possibly be solved with the new `React.cloneElement` method. I'm trying to work on migrating `ReactTransitionGroup` to use it, but I am a super noob to the React source, so it's going to be slow going. Any help from the React team that I can get would be much appreciated.

**Comment by spicyj** [comment]
@duro That unfortunately won't work in this case because ReactTransitionGroup needs a ref to the element too (so you can't just keep the old one). @syranide's suggestion of creating a wrapper should work though.

**Comment by duro** [comment]
@spicyj Something needs to happen, because right now ReactTransitionGroup is practically unusable when used in combination with something like react-router, and passing props from the parent component down to the children.

I've been tearing my hair out trying to get it to work for days.

**Comment by duro** [comment]
If anyone cares to take a look at the project where I am having this problem it is here:

https://github.com/zehnergroup/zg-site-frontend/tree/transitions

The specific file where `ReactTransitionGroup` is implemented is [here](https://github.com/zehnergroup/zg-site-frontend/blob/transitions/src/client/app/components/App.js)

**Comment by Morhaus** [comment]
With the new callback refs introduced in React 0.13, you can now clone an element and conserve its ref. Here's an example implementation, where all `ref` props are considered to be functions.

```
function cloneWithRef(element, ref) {
    return React.cloneElement(element, {
        ref: function(component) {
            ref(component);
            element.ref(component);
        }
    });
}

var Child = React.createClass({
    componentDidMount: function() {
        console.log('Child', this.c);
    },
    render: function() {
        var child = React.Children.only(this.props.children);
        return cloneWithRef(child, (c) => this.c = c);
    }
});

var Wrapper = React.createClass({
    componentDidMount: function() {
        console.log('Wrapper', this.c);
    },
    render: function() {
        return (
            <Child>
                <div ref={(c) => this.c = c} />
            </Child>
        );
    }
});
```

And [here's a JSFiddle](http://jsfiddle.net/kb3gN/10645/).

If this pattern is considered okay, I might have a go at implementing it in `ReactTransitionGroup`.

**Comment by duro** [comment]
I'd love to get my hands on this implementation.

**Comment by AlexGalays** [comment]
This can be closed I think?

**Comment by spicyj** [comment]
I believe this still is broken (using cloneElement now instead of cloneWithProps).

**Comment by AlexGalays** [comment]
Got it, I thought the wrapper was in place already.

**Comment by cheunghy** [comment]
This is still broken.

**Comment by egzplicit-bbc** [comment]
Still broken :(

**Comment by arturcarvalho** [comment]
Any news on this? Thank you.

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
