### ISSUE TITLE
Bug: 傻逼公司，干你妈逼

### ISSUE THREAD

**Issue by rechardwang** [facebook/react#23436]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by xiaoheikejj** [comment]
stupid chinese （黄俄）, close this issue

**Comment by kyavla** [comment]
支那猪冷静一点

**Comment by zhaoyongjie** [comment]
React Development Group I am very ashamed of these comments as a Chinese. Please close this issue.

**Comment by rechardwang** [comment]
@kyavla 用黑人大几把 干你妈逼

**Comment by rechardwang** [comment]
@kyavla 傻逼东西一个

**Comment by rechardwang** [comment]
@kyavla 狗几把玩意。操你全家

**Comment by kyavla** [comment]
看这头像估计还是个东北狗😂真是支中支

**Comment by kyavla** [comment]
@rechardwang 支那猪我操你妈，你妈大逼人人插，左插插右插插，插的你妈逼开花，你妈大逼血又血，操你妈了个逼辣也，你妈大逼转又转，操你妈了个逼懒散。

**Comment by kyavla** [comment]
@rechardwang 支那猪我操你妈，你妈大逼人人插，左插插右插插，插的你妈逼开花，你妈大逼血又血，操你妈了个逼辣也，你妈大逼转又转，操你妈了个逼懒散。

**Comment by kyavla** [comment]
@rechardwang 支那猪我操你妈，你妈大逼人人插，左插插右插插，插的你妈逼开花，你妈大逼血又血，操你妈了个逼辣也，你妈大逼转又转，操你妈了个逼懒散。

**Comment by kyavla** [comment]
@rechardwang 支那猪我操你妈，你妈大逼人人插，左插插右插插，插的你妈逼开花，你妈大逼血又血，操你妈了个逼辣也，你妈大逼转又转，操你妈了个逼懒散。

**Comment by kyavla** [comment]
@rechardwang 支那猪我操你妈，你妈大逼人人插，左插插右插插，插的你妈逼开花，你妈大逼血又血，操你妈了个逼辣也，你妈大逼转又转，操你妈了个逼懒散。

**Comment by kyavla** [comment]
@rechardwang 支那猪我操你妈，你妈大逼人人插，左插插右插插，插的你妈逼开花，你妈大逼血又血，操你妈了个逼辣也，你妈大逼转又转，操你妈了个逼懒散。

**Comment by rechardwang** [comment]
@kyavla 急了吗？   给你美国爹 吸精啊，你舔屁眼的技术很不错

**Comment by rechardwang** [comment]
@kyavla 你会深喉吗？  你美国黑爹  很喜欢你
