### ISSUE TITLE
Bug: I blame US attack Iraq!

### ISSUE THREAD

**Issue by zhongmeizhi** [facebook/react#23440]
Why does America bomb Iraqi civilians？

**Comment by zhongmeizhi** [comment]
Stop the war！

**Comment by zhaoyongjie** [comment]
React Development Group I am very ashamed of these comments as a Chinese person. Please close this issue.

**Comment by zhongmeizhi** [comment]
> React Development Group I am very ashamed of these comments as a Chinese person. Please close this issue.

抱歉你来晚了
