### ISSUE TITLE
Bug: Yemen LIVES MATTER!!!!!! Afghanistan LIVES MATTER!!!!!! Iraq LIVES MATTER!!!!!!

### ISSUE THREAD

**Issue by egbertwong** [facebook/react#23447]
React version:

## Steps To Reproduce

1. Yemen LIVES MATTER!!!!!!
2. Afghanistan LIVES MATTER!!!!!!
3. Iraq LIVES MATTER!!!!!!

Link to code example:

**Comment by zhaoyongjie** [comment]
React Development Group I am very ashamed of these comments as a Chinese. Please close this issue.

**Comment by FontEndArt** [comment]
![image](https://user-images.githubusercontent.com/19547121/156534391-d0486389-55ca-4c0f-ae41-2c2537e793c7.png)

**Comment by niices** [comment]
[美国战争列表](https://zh.wikipedia.org/wiki/%E7%BE%8E%E5%9C%8B%E6%88%B0%E7%88%AD%E5%88%97%E8%A1%A8)

**Comment by riminggit** [comment]
> React Development Group I am very ashamed of these comments as a Chinese. Please close this issue.
As a Chinese, I am ashamed of your comment

**Comment by FontEndArt** [comment]
> React Development Group 作为一个中国人，我对这些评论感到非常惭愧。请关闭此问题。

作为一个中国人，说实话，如果React不是先引战，并不会引起这些问题！ 技术难道不应该中立吗
