### ISSUE TITLE
Bug: 良心云 2核4g6m  74元一年

### ISSUE THREAD

**Issue by Cnm-mgg** [facebook/react#23482]
腾讯云迎新春福利活动，服务器史上最低价！！！
2核2G4M，40元/1年，200元/3年
2核4G6M，74元/1年，298元/3年
4核8G10M，211元/1年，998元/3年
4核8G5M（800G数据盘），580元/1年，1916元/3年
迎新春活动(强烈推荐)：https://curl.qcloud.com/XAP5zTq4
海外主机最便宜只要315一年
海外:  https://curl.qcloud.com/vwOk1RCo
ps：老用户换qq邮箱登录即可购买

**Comment by zhaoyongjie** [comment]
React Development Group I am very ashamed of these comments as Chinese. Please close this issue.

**Comment by vsdfnvuitsb** [comment]
见过傻逼没见过你这种傻逼，你妈死了你到这发这玩意来？

**Comment by colossalleaf** [comment]
> 

你惭愧你妈呢

**Comment by KayvorGwen** [comment]
兄弟，多少钱一条广告，带带我

**Comment by colossalleaf** [comment]
> React Development Group I am very ashamed of these comments as Chinese. Please close this issue.

傻逼
