### ISSUE TITLE
Bug: 乌拉 乌拉 吃我一发

### ISSUE THREAD

**Issue by yinluno1** [facebook/react#23493]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by 1120040377** [comment]
乌拉~

**Comment by awesome-long** [comment]
React Development Group I am very ashamed of these comments as Chinese. Please close this issue.

**Comment by lovesyxfuffy** [comment]
> React Development Group I am very ashamed of these comments as Chinese. Please close this issue.

你又在这用鸟语装什么理中客？2016年南海忘记了？南联盟大使馆又忘记了？你有什么资格在这里ashamed？

**Comment by yinluno1** [comment]
乌拉
