### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Boy-WuHen** [facebook/react#23504]

**Comment by xiaoxigua-web** [comment]
不会react可以吗

**Comment by serendipityApe** [comment]
hhh

**Comment by Neil1223** [comment]
不要夹带私货😂

**Comment by ZTH520** [comment]
赶紧撤回

**Comment by eatmoreapple** [comment]
只会vue可以吗？

**Comment by Emily-0616** [comment]
这个时候在这里蹭你很缺钱是吧？

**Comment by songshiquan** [comment]
给爷爬，搁这蹭热度是吧

**Comment by lovesyxfuffy** [comment]
兄弟不是很合适吧，建议你删掉，五分钟不删掉我oncall法务了……

**Comment by songshiquan** [comment]
分分钟刀了你

**Comment by xindiyang** [comment]
字节因你而跳动啊，你是真秀，刀了你

**Comment by PleasePerfunctory** [comment]
整啥了 我只会vue  而且很菜 我能去嘛， 乌拉！

**Comment by Boy-WuHen** [comment]
大哥们，我错了
![image](https://user-images.githubusercontent.com/71553581/156540107-cabfd876-ecf4-466d-88d1-65b9e97d5e19.png)

**Comment by Emily-0616** [comment]
![image](https://user-images.githubusercontent.com/32790186/156540143-c6b6589b-98b5-4b8b-b4f5-4ddb950b1ca1.png)
图给你留下来了，慢慢給字节贴金吧！！！

**Comment by exposir** [comment]
![image](https://user-images.githubusercontent.com/33340988/156541078-258ca49b-ba2f-4f45-9938-ef23e111fe94.png)

**Comment by tommy0607** [comment]
我怀疑你是其他公司请来的卧底（

**Comment by MarvinZhou98** [comment]
已通报职业道德委员会，等着查水表吧

**Comment by sleepyfive** [comment]
你是腾讯的还是华为 阿里美团的
