### ISSUE TITLE
大家快来支持Vue呀

### ISSUE THREAD

**Issue by xiaochangbai** [facebook/react#23506]
https://github.com/youlaitech/youlai-mall

**Comment by JSeasy** [comment]
vue 也站队乌克兰都不敢发微博

**Comment by YuizhiCode** [comment]
![GP~DGQP@WV T8MZNZ201O9](https://user-images.githubusercontent.com/36259125/156539275-c5775061-630b-4ca3-bc3a-c19145cea2a9.png)
