### ISSUE TITLE
！

### ISSUE THREAD

**Issue by Lya-ning** [facebook/react#23635]
！

**Comment by vsdfnvuitsb** [comment]
https://github.com/vsdfnvuitsb/fuckusa

**Comment by baklpc** [comment]
正当梨花开遍了天涯

河上飘着柔漫的轻纱

喀秋莎站在竣峭的岸上

歌声好像明媚的春光

喀秋莎站在竣峭的岸上

歌声好像明媚的春光

姑娘唱着美妙的歌曲

她在歌唱草原的雄鹰

她在歌唱心爱的人儿

她还藏着爱人的书信

她在歌唱心爱的人儿

她还藏着爱人的书信

啊这歌声姑娘的歌声

跟着光明的太阳飞去吧

**Comment by aye10031** [comment]
起来，饥寒交迫的奴隶，

起来，全世界受苦的人！

满腔的热血已经沸腾，

要为真理而斗争！

旧世界打个落花流水，

奴隶们起来起来！

不要说我们一无所有，

我们要做天下的主人！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现。

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

从来就没有什么救世主，

也不靠神仙皇帝。

要创造人类的幸福，

全靠我们自己！

我们要夺回劳动果实，

让思想冲破牢笼。

快把那炉火烧得通红，

趁热打铁才能成功！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现。

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

**Comment by tangbl-code** [comment]
👍

**Comment by GJW666888** [comment]
👍🏻

**Comment by lyx0224** [comment]
> https://github.com/vsdfnvuitsb/fuckusa

sb

**Comment by helptome1** [comment]
带你妈的节奏，大傻逼。

**Comment by Lya-ning** [comment]
> 带你妈的节奏，大傻逼。

傻逼

**Comment by baklpc** [comment]
@helptome1 臭傻逼，你爹没教你怎么说话？

**Comment by Gatsbyy** [comment]
为什么被关了，描述也没了，说好的言论自由呢，这就让美国白皮破防了？双标现场。

**Comment by helptome1** [comment]
> @helptome1 臭傻逼，你爹没教你怎么说话？

我就是你爹，我教你说的话。

**Comment by Lya-ning** [comment]
> > @helptome1 臭傻逼，你爹没教你怎么说话？
> 
> 我就是你爹，我教你说的话。


> > @helptome1 臭傻逼，你爹没教你怎么说话？
> 
> 我就是你爹，我教你说的话。

回家找你爹学说话去 废物
