### ISSUE TITLE
Bug: 那个、请问一下美国怎么看伊朗军官被斩首？

### ISSUE THREAD

**Issue by wwhai** [facebook/react#23636]
![image](https://user-images.githubusercontent.com/20577297/156541589-85877b10-dcab-477e-872c-44a5ed65a469.png)
---

各位阿美利加的大佬们，看图作文。（你们科技这么发达，翻译中文没问题吧？）

**Comment by baklpc** [comment]
正当梨花开遍了天涯

河上飘着柔漫的轻纱

喀秋莎站在竣峭的岸上

歌声好像明媚的春光

喀秋莎站在竣峭的岸上

歌声好像明媚的春光

姑娘唱着美妙的歌曲

她在歌唱草原的雄鹰

她在歌唱心爱的人儿

她还藏着爱人的书信

她在歌唱心爱的人儿

她还藏着爱人的书信

啊这歌声姑娘的歌声

跟着光明的太阳飞去吧

**Comment by lonelysunshine** [comment]
> 乌拉

乌拟🐴，拟🐴下体都乌啦
