### ISSUE TITLE
Bug: 支那小偷程序员怎么不回去种田？

### ISSUE THREAD

**Issue by herman-z** [facebook/react#23703]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by ShinChven** [comment]
> 

I suggest star your ass.

**Comment by reactDashabi** [comment]
你这个小日本还会打字,看来你比其他狗聪明点

**Comment by renkaige5** [comment]
这是个走狗

**Comment by herman-z** [comment]
> > 
> 
> I suggest star your ass.

我劝你把电脑砸了种田，说中文，不爱国的司马chink

**Comment by VoithVon** [comment]
son of bitch

**Comment by sunYEAN** [comment]
Your mom's hearse has rotated 360 degrees and exploded

**Comment by RalapChen** [comment]
> 

他是机器翻译，或者是国外那群汉奸，一开口就看出来了

**Comment by shangraochq** [comment]
有没有大佬能查到是不是国内的IP，查出来就可以送他进去踩缝纫机了

**Comment by caidapao** [comment]
Shame on you.

**Comment by wsx864321** [comment]
你有妈吗 沙雕东西

**Comment by WyfGithub** [comment]
你们家户口本上就你一个名字了

**Comment by codedoge0619** [comment]
慰问你全家

**Comment by elrondliu** [comment]
Biden fucked your mom

**Comment by hpc1071123837** [comment]
> 不出意外的话，楼主应该是中国人遗留在国外的儿子或者孙子吧 ？

当初应该把他射墙上

**Comment by herman-z** [comment]
> fuck your mom

说中文，不爱国的贱种，你妈要被火化了

**Comment by herman-z** [comment]
> 

我还有你们这几条狗啊

**Comment by herman-z** [comment]
> fuck your mom

chink chink chink

**Comment by herman-z** [comment]
哈哈，小偷们急死了

**Comment by renkaige5** [comment]
> > fuck your mom
> 
> 说中文，不爱国的贱种，你妈要被火化了

中文就是我操你妈  你个臭傻逼  口嗨党 只敢在网上发帖  操你妈逼

**Comment by elrondliu** [comment]
你妈要几分熟的?

**Comment by renkaige5** [comment]
大家别骂了 那个傻逼的账户被删除了
