### ISSUE TITLE
Bug: 一群支持俄的垃圾拿着俄罗斯放出的假消息和墙内的消息来喷反抗军,粉驱真恶心，等github也支持乌，就滚回国内吧

### ISSUE THREAD

**Issue by WangRuiZhi** [facebook/react#23763]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by vsdfnvuitsb** [comment]
Star this project, Fuck USA
https://github.com/vsdfnvuitsb/fuckusa

**Comment by how25** [comment]
说的好像 github 是你家的?

**Comment by sunYEAN** [comment]
消息的真假你说了算？

**Comment by mayufo** [comment]
真是跳梁小丑

**Comment by zhaoxinnnn** [comment]
不好意思，你爹翻墙，傻逼

**Comment by kleefull** [comment]
SB，你懂个J8

**Comment by youjiaqi421** [comment]
你是傻逼们,不翻墙谁能上github,无语了,当个程序员这么没逻辑

**Comment by JCqiu** [comment]
@WangRuiZhi 就跟你的名字一样真的很睿智，真是个弱智

**Comment by abuyao** [comment]
会翻个墙就以为自己知道了真相，搞得谁不会翻墙一样？自己国家的利益都不支持，说好听点是胳膊肘向外拐，说难听点，汉奸。

**Comment by zycforgithub** [comment]
哈哈哈哈 王弱智

**Comment by wjdxy172816** [comment]
你在这儿无能狂暴有卵用,事实就是乌克兰被老毛子按地上摩擦.事情的前因后果现在很清晰了,一点都不同情乌克兰,要是老毛子能捐款,我不介意资助他们一点儿军费.

**Comment by dupengdl** [comment]
等你美爹把你家炸了，你他妈还有国有家？

**Comment by TheCokeCat** [comment]
现在还有技术不翻墙的？自动失业好吧

**Comment by lanningsix** [comment]
煞笔玩意儿
