### ISSUE TITLE
react为什么要沦为政治工具！！！技术无国界？？？ 🇺🇸各种挑唆，各种引发战争， 就是垃圾垃圾

### ISSUE THREAD

**Issue by limengyao** [facebook/react#23774]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by vsdfnvuitsb** [comment]
Star this project, Fuck USA
https://github.com/vsdfnvuitsb/fuckusa

**Comment by XJP-GIT** [comment]
中国人能不能冷静一点

**Comment by fangker** [comment]
国家都没特么支持俄罗斯了，你们在这当什么小丑

**Comment by limengyao** [comment]
> 



> 国家都没特么支持俄罗斯了，你们在这当什么小丑

所以你特么觉得说这种话就很好？？

**Comment by wangweizm** [comment]
> 国家都没特么支持俄罗斯了，你们在这当什么小丑

做个人吧

**Comment by VincentChengzc** [comment]
> 国家都没特么支持俄罗斯了，你们在这当什么小丑

难道支持美国？你算什么小丑？

**Comment by pomestyle** [comment]
fuck usa ！！！ 
Why the fuck didn't you oppose the US when it was fighting Afghanistan, Iraq, Syria?

**Comment by gitwahaha** [comment]
> 国家都没特么支持俄罗斯了，你们在这当什么小丑

所以你当美国的小丑？
