### ISSUE TITLE
华为为乌克兰人民遭受的灾难和损失感到遗憾计划给乌克兰提供免费网络设备/

### ISSUE THREAD

**Issue by wuweijian1997** [facebook/react#23873]
[华为为乌克兰人民遭受的灾难和损失感到遗憾计划给乌克兰提供免费网络设备/](https://www.reddit.com/r/China_irl/comments/t4c7az/%E5%8D%8E%E4%B8%BA%E4%B8%BA%E4%B9%8C%E5%85%8B%E5%85%B0%E4%BA%BA%E6%B0%91%E9%81%AD%E5%8F%97%E7%9A%84%E7%81%BE%E9%9A%BE%E5%92%8C%E6%8D%9F%E5%A4%B1%E6%84%9F%E5%88%B0%E9%81%97%E6%86%BE%E8%AE%A1%E5%88%92%E7%BB%99%E4%B9%8C%E5%85%8B%E5%85%B0%E6%8F%90%E4%BE%9B%E5%85%8D%E8%B4%B9%E7%BD%91%E7%BB%9C%E8%AE%BE%E5%A4%87/)

**Comment by Shimada666** [comment]
对乌克兰的平民遭遇表示同情 对乌克兰政府行为表示遗憾

**Comment by R1hug0** [comment]
对乌百姓需求表示关切，对星链支持军方表示谴责
