### ISSUE TITLE
Feature Request: Dynamic Object Literal Property Keys

### ISSUE THREAD

**Issue by natew** [facebook/react#2391]
From the es6 spec:

http://wiki.ecmascript.org/doku.php?id=harmony:object_literals#object_literal_computed_property_keys

This would come in handy with `React.addons.classSet`, allowing you to do something like this:

``` js
var classes = React.addons.classSet({
  oneClass: true,
  [this.props.className]: !!this.props.className
});
```

**Comment by mixtur** [comment]
There is a way not involving transpiller to achieve the same goal.
It is possible to change signature of classSet to take not Object but Array. Like this:
```javascript
  cx([
    ['oneClass', true,]
    [this.props.className, !!this.props.className]
  ])
```
That is a little ugly I agree, but it solves the problem.
It is also possible to make function cx polymorphic, so this change should be backward compatible.

**Comment by gaearon** [comment]
While this is unrelated to React's JSX transform, you can already do this with [6to5 transpiler](https://6to5.org).

It's somewhat slower than React's transform and has an [unresolved minor JSX parser bug](https://github.com/RReverser/acorn-jsx/issues/13) but other than that I'm really happy with it and not going back.
