### ISSUE TITLE
Errors in React tutorial step 4

### ISSUE THREAD

**Issue by Andersos** [facebook/react#2395]
At the 4th (tutorial4.js) step in the tutorial (http://facebook.github.io/react/docs/tutorial.html
) you get the following error: 

"Uncaught TypeError: Failed to construct 'Comment': Please use the 'new' operator, this DOM object constructor cannot be called as a function."

It is not very pedagogical to have failing steps in the tutorial. I believe step 5 should come before step 4. I'll happily update if this is something you agree with.

**Comment by ClimbsRocks** [comment]
Thanks for documenting this issue! I was very confused when I got to this point in the tutorial and encountered the same error in the console. Simply reordering these two sections fixed it perfectly. I submitted a pull request with that change. 

Let me know if there's anything else I can do to help with this!

**Comment by spicyj** [comment]
#2968 merged.
