### ISSUE TITLE
Consider Deferring Rendering Until We're Actually in the Document

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2398]
...or warn?

It's best practice to defer `React.render` until the container node is actually in the document. That allows `componentDidMount/Update` events work as expected through out the system.

We could use a in-document detection to determine if a container in the document. If not, we could either warn or use a hack to defer rendering until it actually gets added to the document.

Web components have similar life-cycle hooks. Integrating with them would likely involve deferring all work until we're in the document.

**Comment by gaearon** [comment]
Closing as stale. If we still want to do it let’s create a new issue that also mentions how it plays along with prerendering.
