### ISSUE TITLE
Bug: 开源为什么要参杂政治

### ISSUE THREAD

**Issue by icyfe** [facebook/react#24058]
！

**Comment by hqnhqh** [comment]
fuck

**Comment by yinxiangshi** [comment]
Stand with Urikane doesn't equal to stand with the Urikane government. Ur issue just like a joke. Lmao.

**Comment by OnlyPiglet** [comment]
我不喜欢指责任何人，这个世界是多样的

**Comment by kelvinwongdev** [comment]
This is not a bug lol. You pinky Chinese sucks!

**Comment by OnlyPiglet** [comment]
> This is not a bug lol. You pinky Chinese sucks!
Hong Kong  is belong to china too, suck ....

**Comment by qhl123456** [comment]
> 
Hong Kong people eat shit
