### ISSUE TITLE
Feature Request: Allow Devs to Use `selected` Property for `option` Elements

### ISSUE THREAD

**Issue by ITenthusiasm** [facebook/react#24067]
## The Problem
Currently, when developers attempt to use uncontrolled select elements with options, they are "punished" with large warnings in the console for using the option's selected property.

## The Solution
Remove the React warning for using the selected attribute, or otherwise enable developers to disable the warning. Somewhat relates to https://github.com/facebook/create-react-app/issues/2070.

## Motivation
I understand that [according to the docs](https://reactjs.org/docs/uncontrolled-components.html), controlled inputs are generally encouraged in the React world. However, as HTML, CSS, and JS have improved -- and as other frameworks like Svelte have been worked with -- I think it's become clear that it's quite possible to make robust forms without controlled inputs. More specifically, it's possible to do this [easily] with pure JS -- meaning it is unnecessary to employ more complex concepts like refs (which the docs use). This saves on unnecessary re-renders, and in some cases it significantly simplifies the implementation (and props pollution) of the JSX. (As a plus, it makes the code more framework-agnostic.) Actually, in some cases relying on state results in accidental foot shooting.

I've been in the process of migrating a complex form in Next.js to use uncontrolled inputs + [react-hook-form](https://react-hook-form.com/) for a company. It's finished now, and I haven't had to use any controlled inputs. The lines of code noticeably decreased (together with number of re-renders), and readability increased. (For clarity, the page itself is not stateless. State is used sparingly where needed. For instance, when a file is uploaded, urls are stored in a state variable holding an array. It's used to display images to users.)

In the process of the migration, I found use cases where using React's value and defaultValue props for select were insufficient for my needs. (I really tried to get something working with those props. No luck.) So now I'm using basic HTML/JS ... which would work fine in regular HTML/JS land (and would work fine in other frameworks), but causes console errors in React (without actually breaking anything).

Very thankful that the regular HTML+JS works fine in React land! 😄 It would just be nice not to have the warnings since they're not really helpful/practical anymore.

**Comment by bvaughn** [comment]
>  I think it's become clear that it's quite possible to make robust forms without controlled inputs

I'm not really sure what this issue is asking for.

The warning message you're referring to just says that you should use _either_ a [controlled input](https://reactjs.org/docs/forms.html#controlled-components) _or_ an [uncontrolled input](https://reactjs.org/docs/uncontrolled-components.html). React only warns when you start off with an _uncontrolled_ input and then you later switch to a _controlled_ input.

> Select elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not  both).

**Comment by ITenthusiasm** [comment]
The issue is asking for the warning related to the option element to be removed. Below is the warning to which I'm referring. It appears to be different from the one you're thinking of.

<img width="588" alt="Screen Shot 2022-03-10 at 8 04 47 AM" src="https://user-images.githubusercontent.com/47364027/157667788-c3d9d51c-4558-41b5-86fb-cceeb19cc6cc.png">

This warning always appears when using uncontrolled select elements. The `selected` [attribute of an `option` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attributes) allows us to set default values to a `select` element (without React-esque code). And as I mentioned earlier, sometimes this _has_ to be the approach; `value` and `defaultValue` are not alway sufficient for all use cases. (This makes sense considering the fact that `defaultValue` isn't "native" HTML here.)

[This code sandbox](https://codesandbox.io/s/v4-q18dev?from-embed) from a [Medium article](https://thomason-isaiah.medium.com/you-dont-need-all-that-react-state-in-your-forms-a2c38b8e21d5) also exemplifies the error.

**Comment by bvaughn** [comment]
You shouldn't need to use both `defaultValue` _and_ `value` (and the Code Sandbox you linked to doesn't do this either). If you're using `value` then you are _already_ setting the default.

**Comment by bvaughn** [comment]
Yes, sorry. I had already deleted my previous message as I realized I had misunderstood what you were saying.

> The `selected` [attribute of an `option` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attributes) allows us to set default values for a `select` element (without React-esque code). And as I mentioned earlier, sometimes this _has_ to be the approach; `value` and `defaultValue` are not always sufficient for all use cases.

Can you explain what you mean by "sometimes this has to be the approach" – why does it _have to be_?

> (This makes sense considering the fact that `defaultValue` isn't "native" HTML here.)

I don't think this is a compelling argument. Many JSX attributes aren't "native" HTML, nor is that a goal.

**Comment by ITenthusiasm** [comment]
> I don't think this is a compelling argument. Many JSX attributes aren't "native" HTML, nor is that a goal.

I understand that the goal isn't for the JSX attributes to reflect native HTML. The very important `ref` prop isn't, for instance. My main feeling is that people should -- for the most part -- be able to use native HTML without receiving pushback from the framework. For instance, `defaultChecked` enables people to experience a native-like experience with checkboxes so that they don't accidentally lock their uncontrolled checkboxes. I think that's great. I'd more or less like to see the same for `select`. (I'm assuming that was the intention of `defaultValue`. So onto the next comment.)

---

> Can you explain what you mean by "sometimes this has to be the approach" – why does it _have_ to be?

This appears to be because of [current] limitations in React. Probably when the options are dynamic?

I started writing out a lot of stuff to explain the situation I'm in, but I don't want to make you read a lot. I can add all the justification if you need me to. But for now, I'm gonna hold off on it and hope you can just trust that the use case is valid. (I will _under_-describe the situation.)

Basically, I have an _uncontrolled_ `select` element with _dynamic_ `option`s. This element starts off with a default set of `option`s, _all_ of which must be `selected` by default. These default options are basically set by some prop of the encompassing component.

People can _add_ to the list of `option`s by filtering through a _searchbox_ and adding whatever they want. They must then go to the `select` element and choose these newly added options if they want to, as the new options are _unselected_ by default. (At this point, someone may say, "That sounds rather convoluted. Why not use something like [react-select](https://react-select.com/home)?" I would agree with this question. Unfortunately, I'm not the designer, so I don't have the say in this situation. And again, this situation is _under_-described.)

Because of this, I basically end up with a `select` element with dynamically rendered `option` elements. But the form field itself is still uncontrolled. I cannot use `value` here, because the element is uncontrolled. Interestingly, however, I cannot use `defaultValue = string[]` either. When I try to do this, _none_ of the default options actually appear to be chosen (highlighted) in the rendered element by default. However, when I apply `selected` to the initial option elements, everything turns out just fine.

(Note: It is _impossible_ to remove options once they've been added -- per design. So the default options will always remain within the `select` element, and in the same location.)

I suppose someone could argue this is a bug in React. But from what I understood, the current implementation is intentional.

(Yes, this is the shorter version. :weary: Thanks for taking the time to hear me out. :pensive:)

**Comment by bvaughn** [comment]
I'm not sure I totally understand the scenario you're describing. Could you show a version of it as a Code Sandbox?

I _think_ you're saying that `<option>` elements are passed in as props, and you want people to be able to tag them as "selected" or not? _If that is what you're saying_, you can technically accomplish this still using the `defaultValue` prop along with `React.cloneElement` to collect all of the pre-selected options.

**Comment by ITenthusiasm** [comment]
Understood. I'll try to throw up a Code Sandbox before the end of the day.

**Comment by bvaughn** [comment]
@ITenthusiasm I'm sorry to hear that you had a difficult weekend! I hope everything is okay.

I think this blog post might be relevant to what you're describing. I wonder if you've read it?

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#common-bugs-when-using-derived-state

**Comment by ITenthusiasm** [comment]
Appreciate the condolences. Things are getting a easier a day at a time.

That article might not be exactly related to the issue I was having. I don't think I'm running into either of the problems mentioned on the site. Appreciate the link though!

I only used props in my example component for the sake of simplicity. In reality, there's some [constant] server fetched data which can either be prop-drilled or grabbed from some kind of context. And that data is what gets sent to the `select` element for its initial value. But that's as far as outside influences go for that element.

**Comment by ITenthusiasm** [comment]
@bvaughn Sorry to dig this back up again, but I actually have new, valid use cases for why the `selected` attribute should be supported now: The browser's _only_ reliable way of identifying default values for `select` elements is the `selected` attribute. And default values are very important. Particularly, they're important if you need the ability to 1) [`Reset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset) a form's values or 2) Track the dirty/clean state of form fields (a very common use case in forms). What this means is that developers relying on the browser's native features with pure HTML+JS (or with another JS framework) will have a broken application if they migrate to React.

Here's a rough example of tracking dirty fields with [pure HTML and JS](https://developer.mozilla.org/en-US/play?id=xDHGGzL2Rl7Kz%2BvqDgEZmBYmzkpvrCytVJCCFYuoRYXdCoUHjzNm4Wu3jh02nHbEBmKCzvbyYf%2BNiBDq). This same example works just fine in [Solid.js](https://playground.solidjs.com/anonymous/b3e76fc8-a00a-4847-98aa-0ff267c624da), but it fails in [React](https://codesandbox.io/s/react-form-default-values-bug-issue-24067-cqz7c9?file=/src/App.tsx) when dealing with `select` elements.

With dawning of [Remix](https://remix.run/) and the close pursuit of [SvelteKit](https://kit.svelte.dev/) and [SolidStart](https://start.solidjs.com/getting-started/what-is-solidstart), many web developers are returning to the benefits of using the browser's native features for forms for progressive enhancement and codebase simplification. Even the React docs have acknowledged this by the fact that they no longer discourage uncontrolled inputs. That being the case, I feel like supporting this feature is a must. If for some reason `selected` is reserved, then `defaultSelected` could be used instead. What's most important is having a way to support the browser's "default value" features for _all_ native form controls.

**Comment by ITenthusiasm** [comment]
It seems things have changed since I originally opened this post. :sweat_smile: `@bvaughn` no longer seems to work on React. And it probably isn't helpful for me to rewrite the OP -- especially given that it disrupts the context of the existing conversation. I think I'll just close this issue and open a new one that more accurately represents what I was hoping for. Hopefully that's acceptable.
