### ISSUE TITLE
Bug: ref + setState

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#24074]
Actually, it is not a bug in React IMO, but I wonder if React can do better in this case.

It's common (at least for me) to need to do some imperative things after DOM is created.

```js
const ref = useRef()
useEffect(() => {
    if (ref.current) { doSomeThing() }
}, [ref.current])
return <div ref={ref}>
```

Well, this is not correct, setting a ref will not trigger the component update. When developers realize this, they will change to `setState`:

```js
const [ref, setRef] = useRef()
useEffect(() => {
    if (ref) { doSomeThing() }
}, [ref])
return <div ref={setRef}>
```

Is this correct?

NO! And it is NOT obvious to developers. It will cause a dead loop on the component.

![image](https://user-images.githubusercontent.com/5390719/157833729-ff416d4e-d473-4031-802f-1f9951e58299.png)

This is a production-level example.

The correct code should be:

```js
const [ref, setRef] = useRef()
useEffect(() => {
    if (ref) { doSomeThing() }
}, [ref])
return <div ref={r => ref !== r && setRef(r)}>
```

Is it possible that React to do something to fix this problem? Maybe

- Do not rerender when setRef is called with the same current state
- Give a warning in development
- Give a useRefButRerenderWhenUpdated

**Comment by eps1lon** [comment]
I think `}, [ref.current])` i.e. `ref.current` as a dependency is already problematic since it's a read of a ref during render.

It's quite problematic since this will only fire the effect when `ref.current` changed between two committed renders. But the effect will never fire if `ref.current` changes after a commit.

Regarding 

```js
const [ref, setRef] = useRef()
useEffect(() => {
    if (ref) { doSomeThing() }
}, [ref])
return <div ref={setRef}>
```

Did you mean 
```diff
-const [ref, setRef] = useRef()
+const [ref, setRef] = useState()
```
? 
If so then I'm not sure I understand why this is problematic. It's safe by default and we use it in MUI demos a lot. Reduced example: https://codesandbox.io/s/state-as-a-ref-fd3n1b

> It will cause a dead loop on the component.

What's a "dead loop". Did you mean "infinite loop"?

**Comment by Jack-Works** [comment]
> What's a "dead loop". Did you mean "infinite loop"?

Yeah... That's strange. Why your example works but I have to write `ref={r => element !== r && setElement(r)}` otherwise it will falls into infinite loop

**Comment by eps1lon** [comment]
My guess is that the component constantly changes on render? If you have `<ComponentFromAVariable ref={refCallback} />` then `refCallback` will run whenever `ComponentFromAVariable` changes. Or if `ComponentFromAVariable` use a forwardRef component that passes the `ref` to `useImperativeHandle` and that `useImperativeHandle` has to run on every render.

Either way, I reduced repo would help here. The pattern itself is ok-ish but can definitely be a footgun. So a repro would help to identify if React can do something about it other then throw with "infinite loop detected".

**Comment by Jack-Works** [comment]
well... I guess I should close this, maybe it's not a problem with react

**Comment by Jack-Works** [comment]
Ok I find out why.

`useImperativeHandle(ref, () => ({ f() {} }), [x])`

We have this pattern in our code base. I thought to react will automatically memo the object returned in the 2nd parameter.

After changing to this:

```js
const refItem = useMemo(() => ({ f() {} }), [x])
useImperativeHandle(ref, () => refItem, [refItem])
```

Bugs in our codebase now gone.
