### ISSUE TITLE
OnError Fallback in Suspense when fetching  Data

### ISSUE THREAD

**Issue by Yasir900aslam** [facebook/react#24076]
### Introduction
React 18 introduces the feature Suspense for providing Fallback for any asynchronous job primary Data-fetching to be loosely-coupled and providing it as a JSX. 

### What does a Fallback mean in React 18 ?
Most Commonly, In React 18, Fallback is for showing loading or anything when doing asyc stuff.

**_But, wouldn't be cool if we provide, Error Handling when we are data-fetching integrated in Suspense as well instead of using Error Boundaries._**

We can assume this that Error Boundary will be shown if Component fails to render.

### For Example

Right now, Suspense Works like this

```sh
<Suspense fallback={<Loading />}>   
    <Page />
</Suspense>
```

Above provides Loading Fallback Whenever Page is fetching data, but **_what happens when data-fetching fails ?_** Did I write Error Boundry or handle onError inside the Page Component which will negate the React principles.

### Solution
If we can add something like this, 
```sh
<Suspense fallback={<Loading />} onErrorFallback={<Error />}>   
    <Page />
</Suspense>
```

1- Whenever Page Component is Fetching data, Loading will be shown.
2- If Any Error Occurs during Fetching Data, Error Component will be shown.

Now we have **_de-coupled our onError Logic_** which perfectly aligns with the principles of the react and provide a good readability of the code.

**Moreover, We can easily integrate monitoring Solutions in the Error Component that will message Sentry or something else that An Error Occurred, Log of the Error And Reason as well.**

Let me know of your thoughts.

**Comment by gaearon** [comment]
Since error states aren't only caused by fetching, we'd like to reuse the same mechanism to declare them in the tree. This is why Suspense doesn't have its own mechanism.
