### ISSUE TITLE
[DevTools Question]: need help with react-devtools-inline

### ISSUE THREAD

**Issue by chris-kruining** [facebook/react#24098]
I know the issues are not meant for user questions but I don't know where to start for such a specific question about the dev-tools.

I am developing a CMS, my setup is as follows:
I have the CMS itself, the CMS can be seen as the IDE the `react-devtools-inline` readme mentioned.
The CMS has an iframe with a generated url which has the project loaded. 
this url is on another origin.
I have a component that is loaded in the project to initialize the bridge as per the `react-devtools-inline`'s readme.

How ever I cannot for the life of me figure out how the devtools element, or rather the TreeContext in react-devtools-shared is populated with the components. Nor can I figure out how I am supposed to fetch the rendererId.

I want to use `react-devtools-inline` to achieve a couple of goals:
1. have bread crumbs in the footer of the CMS to highlight Remix' nested routing (ergo: `bridge.send('highlightNativeElement', { ... })`)
2. "reverse engineer" the source location inside the DOM so I can implement drag&drop for the CMS (I want to know which file I would have to modify in order to drop the element in the correct position, I think I need `bridge.send('viewElementSource', { ... })` for this).

For both of these calls I need a renderer and element id. but how do I obtain those? I tried extracting it from the `operations` but no luck.

**Comment by bvaughn** [comment]
> How ever I cannot for the life of me figure out how the devtools element, or rather the TreeContext in `react-devtools-shared` is populated with the components. Nor can I figure out how I am supposed to fetch the rendererId.

You don't need to do either of these things. The renderer ID will be generated when ReactDOM and DevTools do their handshake, and DevTools will render and manage its own `TreeContext` element. None of that is meant to be exposed for outside use or control.

> I tried extracting it from the `operations` but no luck.

This message is definitely _not_ intended for external use. It's an internal message format that DevTools uses to talk between its own separate contexts. (Technically the message structure is described [here](https://github.com/facebook/react/blob/main/packages/react-devtools/OVERVIEW.md) **but it may change between releases without warning**.)

**Comment by bvaughn** [comment]
It's kind of hard to say more about the use case without having any code or details to look at but I _think_ this issue has been answered so I'm going to go ahead and close it. :smile:

**Comment by chris-kruining** [comment]
basically what it boils down to is that I want to make devtools with my own UI. And a little filter over the component stack in order to get the relevant data for Remix (or a different filter for a different type of react based framework. NextJS for example).

what code or details are you looking for? I can provide you with a screenshot with annotations to explain what I am trying to achieve. a storybook if you will. I don't mind sharing code either, but I doubt I can get it boiled down to a nice and concise repro.

**Comment by chris-kruining** [comment]
> You don't need to do either of these things. The renderer ID will be generated when ReactDOM and DevTools do their handshake, and DevTools will render and manage its own `TreeContext` element. None of that is meant to be exposed for outside use or control.

I get that, but I am looking into how I can use it to feed the data needed for my CMS' UI.

**Comment by chris-kruining** [comment]
p.s. I keep calling it a CMS but it is more akin to a visual IDE

**Comment by bvaughn** [comment]
That's fair. Seeing the could would give me a better understanding of the specifics, but probably isn't necessary. Really it sounds like you're looking for a way to use APIs that aren't meant to be exposed for public use.

**Comment by chris-kruining** [comment]
I understand, thank you for your time! :D
