### ISSUE TITLE
Bug: DO NOT PULLTE THE OPEN SOURCE COMMUNITY WITH FUCKING POLITICS. TAKE OFF THESE FUCKING SUPPORT UKRAINES BANNER

### ISSUE THREAD

**Issue by Raw-Paradox** [facebook/react#24097]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by Raw-Paradox** [comment]
Is that difficult for you motherfuckers to be political netrual? DISGUSTING, shame of you all

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/issues/4433#issuecomment-1060759889
