### ISSUE TITLE
Please add React.PropTypes.componentClass or similar to React.PropTypes

### ISSUE THREAD

**Issue by bjbrewster** [facebook/react#2411]
Hello,

We have found it useful being able to pass a React component class (ie the result of calling `React.createClass()` - not just an instance of a component) to a child component.  eg generic SearchResults accepts both a results array and a 'resultComponent' property that is used by its render method to create each search result.  Our PageSearch component passes PageSearchResult class to the SearchResults component while our CampaignSearch component passes CampaignSearchResult.  Although we could do the map of results to result components higher up in the hierarchy, it is convenient for this to be handled in the generic SearchResults component as there is other common logic being performed on construction of each result.

Aside from whether this example is good practice, I believe this is a useful property type that could be added to the official PropTypes list.  I believe it would be almost identical to `createComponentTypeChecker()` function in `ReactPropTypes.js` but instead of `ReactDescriptor.isValidDescriptor()` it would call `ReactDescriptor.isValidFactory()` and updated message.  For now I must use either `React.PropTypes.func` or use a custom function that uses `React.isValidClass()` which is just `ReactDescriptor.isValidFactory()` publicly exposed.

Many thanks,
Brendan

**Comment by spicyj** [comment]
In general, there's no way to statically identify what might be a valid component. Consider the last example here:

http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

Any function or string might be valid; there's no more specific type we have.
