### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by cruxcode** [facebook/react#24115]
React version: 17.0.2

## Steps To Reproduce

1. Tried to mimic the problem in a simple codebase but couldn't reproduce.

Link to code example:

```
export const useAcceptChild = (props: CanvasChildProps) => {
  const [children, setChildren] = useState<string[]>([]);
  // first render
  useEffect(() => {
    const children = props.elementStore.getChildren("root");
    setChildren(children);
  }, [setChildren, props.elementStore]);
  // subsequent renders
  useEffect(() => {
    const unsubscribe = props.elementStore.subscribe(
      "root",
      ({ kind, params }) => {
        if (kind === "new_child") {
          setChildren((oldChildren) => {
            console.log("setChildren called");
            return [...oldChildren, params.childId];
          });
        }
      }
    );
    return () => {
      unsubscribe();
    };
  }, [props.elementStore, setChildren]);
  return children;
};
```

## The current behavior
"setChildren called" gets printed once in the console, but the new array inserts the same element twice.

## The expected behavior
the new element should get inserted only once.

Are there any edge cases when react can insert an extra element on it's own? This custom hook is being used inside a React.memo component.

**Comment by gaearon** [comment]
Sorry, it's hard to guess what doesn't work from a non-runnable example. Overall, this pattern looks a bit convoluted and you might want to use something like a Portal instead if possible.
