### ISSUE TITLE
Where is the source code of react@15.6.0 and before?

### ISSUE THREAD

**Issue by aztack** [facebook/react#24139]
This is not a bug, I‘m just curious. Where is the source code of react@15.6.0 and before?

[Where is the source code of react@15.6.0 and before?](https://stackoverflow.com/questions/71559706/where-is-the-source-code-of-react15-6-0-and-before)

**Comment by bvaughn** [comment]
It's in GitHub, just not in the `packages/react` directory. The current directory structure was changed a few years back.

Here's a random older commit that shows the previous structure:
https://github.com/facebook/react/tree/0b063f8a09dae4b6b1de400ff2d9aba9108647de/src

You can browse these using `git log` with a local checkout.
