### ISSUE TITLE
Bug: infinite function component rendering with lazy loading

### ISSUE THREAD

**Issue by Raimundo82** [facebook/react#24149]
Unexpected behavior (infinite function component rendering) when lazy loading component with string interpolation (reactive variable state)

React version: 18.0.0 rc3

## Steps To Reproduce

1. Not working:
```javascript
import { lazy } from 'react';

export default ({ langauge }) => {
  const Privacy = lazy(() => import(`./Privacy-${langauge}.jsx`));
  return <Privacy />;
};
```

2. working:
```javascript
import { lazy } from 'react';

const PrivacyPT = lazy(() => import(`./Privacy-pt.jsx`));
const PrivacyES = lazy(() => import(`./Privacy-es.jsx`));
const PrivacyEN = lazy(() => import(`./Privacy-en.jsx`));

export default ({ language }) => {
  
  return (
    <>
      {language === 'pt' && (
        <PrivacyPT />
      )}
      {language === 'es' && (
        <PrivacyES />
      )}
      {language === 'en' && (
        <PrivacyEN />
      )}
    </>
  );
};

```

Link to code example: https://codesandbox.io/s/spring-haze-ppyzky?file=/src/App.jsx

![Screenshot from 2022-03-24 09-35-58](https://user-images.githubusercontent.com/61196637/159887181-86a62ff3-b3c2-42f1-aa0a-b113d0cd52b6.png)

**Comment by vkurchatkin** [comment]
Couple of problems in your example:

1. You don't seem to have `Suspense` element

2. You shouldn't really create new components inside of other components since it can lead to a lot of unnecessary remounts or even infinite loops:

```js
export default ({ langauge }) => {
  const Privacy = lazy(() => import(`./Privacy-${langauge}.jsx`)); // don't do this
  return <Privacy />;
};
```

at the very least you need to memoize components in such case:

```js
export default ({ langauge }) => {
  const Privacy =  React.useMemo(() => lazy(() => import(`./Privacy-${langauge}.jsx`)), [language]); 
  return <Privacy />;
};
```

**Comment by bvaughn** [comment]
> You shouldn't really create new components inside of other components since it can lead to a lot of unnecessary remounts or even infinite loops

I think this is the crucial piece.

The string interpolation in your example above is not the crucial difference between your two code examples; the inline component definition is.

In other words, this would also "break":
```js
export default function App() {
  const LazyComponent = lazy(() => import('./Example.js'));

  return <LazyComponent />;
}
```

And this would "work":
```js
import { lazy, Suspense } from "react";

const name = "Example";
const LazyComponent = lazy(() => import(`./${name}.js`));

export default function App() {
  return <LazyComponent />;
}
```

**Comment by vkurchatkin** [comment]
As an aside, it seems that `lazy` actually works without `Suspense`, which seems unexpected. @bvaughn is this intentional?

**Comment by Raimundo82** [comment]
Hi @bvaughn,
In your example, if name was a reactive variable i  think you have to wrap the component in <Suspense> , what is annoying if you have like 10 or more components in that situations. Even if i wrap in a higher hierarchy component it won't work.

**Comment by gaearon** [comment]
@Raimundo82 It is not supported to _define components_ during rendering. When you run `lazy` inside render, you're defining a component during rendering. That is not supported. If something still doesn't work after you fix this, can you please provide a sandbox? Thanks.

**Comment by Raimundo82** [comment]
Hi @gaearon if i understand well it is not supported to dynamically define a component to be rendered accoring a certain variable in runtime ?

An example:
https://codesandbox.io/s/spring-haze-ppyzky?file=/src/App.jsx

**Comment by gaearon** [comment]
Hmm. Generally this is not supported. But I guess this accidentally works because we compare the target `lazy` reference. I'm not sure whether this is intentionally supported.
