### ISSUE TITLE
[React DevTools] Warn for Duplicate DevTools Installations

### ISSUE THREAD

**Issue by lunaruan** [facebook/react#24157]
If there are duplicate installations of DevTools (ex. if there is an internal version of DevTools installed alongside the Chrome Web Store extension), we currently produce a stream of errors that renders DevTools unusable. Previously, we tried to fix this [here](https://github.com/facebook/react/pull/22517/files) by detecting duplicate DevTools versions and preventing them from erroring. However, because there are some edge cases with code that extends the DevTools hook, we had to [revert](https://github.com/facebook/react/issues/22636) this change.

Even though we're unable to prevent these errors completely, it would be useful to warn the user that they might have duplicate installations of DevTools. We probably don't want to bother the user with this warning multiple times, so we should only warn the first time we detect the duplicate version.

For this task:
- [ ] Show a warning dialog if there are duplicate DevTools versions installed. You can use [this PR](https://github.com/facebook/react/pull/22517/files) for guidance 
- [ ] Write a value to `localStorage` once this warning has been shown so that we don't continue to show it if the user chooses to leave the duplicate extension installed.
- [ ] Clear the `localStorage` value if the duplicate extension is no longer detected. (This will let us show the dialog if the duplicate is ever accidentally re-installed.)

**Comment by scyron6** [comment]
I will work on this.
