### ISSUE TITLE
Bug: renderToReadableStream doesn't emits all HTML as one unit if we wait until the end to start on real serverless environment

### ISSUE THREAD

**Issue by gffuma** [facebook/react#24169]
React version:
react@18.0.0-rc.3-next-de516ca5a-20220321

## Steps To Reproduce
I try to use the new `renderToReadableStream` with the cloudflare worker runtime.
This code is bare minimum reproduce of original React test.
https://github.com/facebook/react/blob/e09518e5bbb78447d6c86481cf0dcafb4b09c734/packages/react-dom/src/__tests__/ReactDOMFizzServerBrowser-test.js

```jsx
async function readResult(stream: ReadableStream) {
  const reader = stream.getReader()
  let result = ''
  const decoder = new TextDecoder('utf-8')
  while (true) {
    const { done, value } = await reader.read()
    if (done) {
      return result
    }
    result += decoder.decode(value, { stream: true })
  }
}

let hasLoaded = false
let resolve: any
const promise = new Promise((r) => (resolve = r))
function Wait() {
  if (!hasLoaded) {
    throw promise
  }
  return 'Done'
}

function App() {
  return (
    <div>
      <Suspense fallback="Loading">
        <Wait />
      </Suspense>
    </div>
  )
}
const stream = renderToReadableStream(
  <App />
)
setTimeout(() => {
  hasLoaded = true
  resolve()
}, 1000)
await stream.allReady
let result = await readResult(stream)

```
When running the code in sandbox environment eg:. Miniflare. This code works and result yelds:
```html
<div><!--$-->Done<!-- --><!--/$--></div>
```
When running in the real cloudflare runtime this code yelds:
```html
<div><!--$?--><template id="B:0"></template>Loading<!-- --><!--/$--></div><div hidden id="S:0">Done<!-- --></div><script>function $RC(a,b){a=document.getElementById(a);b=document.getElementById(b);b.parentNode.removeChild(b);if(a){a=a.previousSibling;var f=a.parentNode,c=a.nextSibling,e=0;do{if(c&&8===c.nodeType){var d=c.data;if("/$"===d)if(0===e)break;else e--;else"$"!==d&&"$?"!==d&&"$!"!==d||e++}d=c.nextSibling;f.removeChild(c);c=d}while(c);for(;b.firstChild;)f.insertBefore(b.firstChild,c);a.data="$";a._reactRetry&&a._reactRetry()}};$RC("B:0","S:0")</script>
```

I known that this situation is hard to debugging but i also not able to reproduce this bug outside of the real cloudflare runtime. Maybe is a bug in cloudflare js runtime? 

## The current behavior
Result yelds also the streaming code.

## The expected behavior
Result should yelds one unit of html.

**Comment by gffuma** [comment]
After digging into i found that the problem is `ReadableByteStreamController`.
On Cloudflare runtime the `ReadableStream` constructor isn't full compliant.
So the problem is not related to React itself.

```js
new ReadableStream({
  type: 'bytes',
  pull: () => {
    console.log('Pull called')
  }
})
```

The code above log `'Pull called'` on Cloudflare runtime but in Chrome / NodeJS / Deno runtimes doesn't.

**Comment by gnoff** [comment]
Thanks @gffuma I was suspecting something like that was happening but hadn't confirmed yet

**Comment by gffuma** [comment]
Hey @gnoff if you are interested seems Cloudflare fix the bug i reported with web streams. There is no explicit reference to this in [changelog](https://developers.cloudflare.com/workers/platform/changelog/) (despite i personally report that bug to cf team months ago...).
Today i tried on CF runtime the bad example and the original code and all works as expected.
So i think we can now use new React 18 SSR infra in CF Runtime 🎉 🎉 🎉
