### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by JaapioNL** [facebook/react#24162]
### Website or app

http://bestellen-a.cito.nl

### Repro steps

Just opening the console and going to Components or Profiler shows this error.

I noticed that in the console there are two warnings for contentScript.js (I am assuming this file is part of this extension):
﻿
contentScript.js:113 [Violation] 'message' handler took 210ms
contentScript.js:113 [Violation] 'message' handler took 891ms

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.24.0-82762bea5

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26326:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24400:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24566:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54300:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment]
The website you provided (cito-webshop.dev.local/winkelwagen) doesn't seem to load, so we can't look into this bug.

**Comment by bvaughn** [comment]
@JaapioNL The website you provided (cito-webshop.dev.local/winkelwagen) doesn't seem to be publicly accessible, so we can't look into this bug.

**Comment by JaapioNL** [comment]
Sorry, copied the URL from my browser. But the application is also running on http://bestellen-a.cito.nl/ where it also gives this error. It is (on both environments) a bit inconsistent on when it does this. Sometimes it happens and sometimes it doesn't.

**Comment by bvaughn** [comment]
@JaapioNL  This site does not appear to be built with React? I'm getting a 503 page.
<img width="748" alt="Screen Shot 2022-03-25 at 12 40 31 PM" src="https://user-images.githubusercontent.com/29597/160163679-05bae86d-b615-4e38-9f06-9929c8a46586.png">

**Comment by JaapioNL** [comment]
> @JaapioNL This site does not appear to be built with React? I'm getting a 503 page. <img alt="Screen Shot 2022-03-25 at 12 40 31 PM" width="748" src="https://user-images.githubusercontent.com/29597/160163679-05bae86d-b615-4e38-9f06-9929c8a46586.png">

We just updated the application. it should have only given that message fore a minute. But sometimes the bootloader hangs and then the message stays on longer.

**Comment by bvaughn** [comment]
Okay. the URL loads now, but after reloading the page multiple times– it seems to work okay. Is there something else you're doing? Are you sure you only have one copy of React DevTools installed?

(If you open chrome://extensions/ and search for "react" – do you only see one result?)

**Comment by bvaughn** [comment]
@JaapioNL Any chance this source code is available for us to look at, to trim the bug down further?

**Comment by JaapioNL** [comment]
> @JaapioNL Any chance this source code is available for us to look at, to trim the bug down further?

I think I am allowed to share it directly with you (provided you don't share it). But I am not sure you can run all of it since it is build on JSS and I don't think this particular app can run in detached mode.

**Comment by bvaughn** [comment]
@JaapioNL Okay. It would be useful for you to share this source with us if possible, please. You can forward it to me at bvaughn@fb.com.

What it looks like we're seeing is that– for some reason– some part of your website (maybe an ES6 polyfill?) is causing DevTools event handlers to be invoked multiple times, which in turn is causing some duplicate events to be sent from the DevTools backend to the frontend (which triggers our validation/invariant code). It might help us to see the source/dependencies.

**Comment by bvaughn** [comment]
@JaapioNL It seems like the issue _might_ have something to do with the react-easy-state's auto-batching of methods like `addEventListener`. Not totally sure yet, but it seems like "message" event handlers are being called multiple times– and this is the only thing that jumps out as being different for your site vs other random React websites that don't demonstrate this bug.

Next step is probably for us to create a small react-easy-state app and see if we can repro the bug in it.

**Comment by bvaughn** [comment]
It looks like we can repro this behavior (SHIFT+R causes DevTools to throw) with small React app that just uses the react-easy-state boilerplate example code:
```js
import React from 'react';
import { store, view } from '@risingstack/react-easy-state';

const counter = store({
  num: 0,
  increment: () => counter.num++
});

export default view(() => (
  <button onClick={counter.increment}>{counter.num}</button>
));
```

**Comment by JaapioNL** [comment]
@bvaughn I've mailed you the code

**Comment by bvaughn** [comment]
@JaapioNL Where did you send the email to? I did not receive it. Maybe it was flagged by Gmail's spam (if you sent it there)?

**Comment by bvaughn** [comment]
Picking this back up and looking into it today… Looks like there are a ton of duplicate "message" events being fired on the `window` when hard-refreshing the specific project @JaapioNL linked to above. I can't repro this on smaller projects. (By "a ton" I mean – sometimes only a couple, in which case DevTools shows an error – but other times 70 or 80, in which case, DevTools freezes entirely.)

**Comment by bvaughn** [comment]
I think I can _fix_ this issue by just...short-circuiting that method once a connection has already been established. I'm not sure of the conditions that _cause_ this case though.

**Comment by bvaughn** [comment]
PR #24186 _fixes_ this issue, but I think the code on your site (specifically probably the stuff from react-easy-state?) seems likely to be breaking things and should be fixed IMO.
