### ISSUE TITLE
Bug: `defaultValue` is not consistent between `input` and `select`

### ISSUE THREAD

**Issue by sinan-baymammadli-ri** [facebook/react#24165]
When `defaultValue` is not set on initial render `select` doesn't take it into account. This is not consistent with `input` element

React version: 17

## Steps To Reproduce

1. Set `defaultValue` of `select` after initial render 
2. See it is not updated.

Link to code example:

https://codesandbox.io/s/gifted-bash-hsxy14?file=/src/App.js

## The current behavior
When `defaultValue` is set after initial render `select` doesn't update

## The expected behavior
When `defaultValue` is set after initial render `select` should update

**Comment by pascall-de-creator** [comment]
Hi @sinan-baymammadli-ri ,
You are actually right but I think React did this on purpose...

in React [components fixures](https://github.com/pascall-de-creator/react/tree/main/fixtures/dom/src/components/fixtures/selects), there is a test case slightly based on that at ::Line_86 - Line_101 and it is as follows 
👇👇
```javascript
<TestCase.ExpectedResult>
  The initial picked option should be "Please select an item", however
  it should not be a selectable option.
</TestCase.ExpectedResult>

<div className="test-fixture">
  <select defaultValue="">
    <option value="" disabled>
      Please select an item
    </option>
    <option>0</option>
    <option>1</option>
    <option>2</option>
  </select>
</div>
</TestCase>
```

### Recommended solution
In my view I think the best thing to do is to place the default option as first and give it an empty value as in the code above

**Comment by unicast158** [comment]
Use defaultValue in a optional option tag

⬇︎⬇︎⬇︎⬇︎

<select>
        <option defaultValue hidden>
           default
        </option>
        <option value="banana">Banana</option>
        <option value="orange">Orange</option>
        <option value="apple">Apple</option>
      </select>

if you want to hide the value from the menu, use hidden:

**Comment by unicast158** [comment]
**Use defaultValue in a optional option tag**

⬇︎⬇︎⬇︎

```
<select>
        <option defaultValue hidden>
           {'optional'}
        </option>
        <option value="banana">Banana</option>
        <option value="orange">Orange</option>
        <option value="apple">Apple</option>
</select>
```

If you want to hide the value from the menu, use hidden:

**Comment by MustafaEminn** [comment]
The input is not changing after you input a value. This behavior may be good for also select element.

**Comment by robin-a-meade** [comment]
It seems setting both `defaultValue` and `key` achieves the desired result.

Forked codesandbox:
https://codesandbox.io/p/sandbox/determined-khayyam-q45dxd

```diff
-       <select defaultValue={value}>
+       <select defaultValue={value} key={value}>
```

Seen in discussion here: https://github.com/facebook/react/issues/30580#issuecomment-2537962675
