### ISSUE TITLE
Bug: [Vite] Requested module not exported, but acutally it is exported

### ISSUE THREAD

**Issue by vedantnn71** [facebook/react#24174]
I get this error - `Uncaught SyntaxError: The requested module '/src/components/Runner.jsx?t=1648386493195' does not provide an export named 'default'` almost all the time, until and unless I don't save the file for 3-4 times. I have my module exported and imported correctly, see -
![Screenshot from 2022-03-27 18-49-46](https://user-images.githubusercontent.com/70624701/160283635-bc0cd106-9e4c-4690-9fae-d774e57d2e81.png)

Browser (brave)'s console:
![Screenshot from 2022-03-27 18-38-42](https://user-images.githubusercontent.com/70624701/160283637-afdd2527-a507-429c-bc67-c0c83b3dee58.png)

React version: 17.0.2
Vite version: 2.8.0
Vite-react-plugin version: 1.0.7

## Steps To Reproduce
1. Write code with vite and react
2. Save the file only one time

**Comment by rickhanlonii** [comment]
@vedantnn71 this bug seems specific to your environment or vite, not React, but if you are able to create a sandbox that shows that this is a bug specific to React, let us know and we can re-open.

**Comment by handsomeCarl** [comment]
How did you solve it @vedantnn71  thanks
