### ISSUE TITLE
Bug: Elements in a list incorrectly receive hover state when a sibling is removed as result of a touch event

### ISSUE THREAD

**Issue by matt-sanders** [facebook/react#24187]
Imagine you have a list of components, let's take the classic To Do app example, and you render each item in the list. Each item has a delete button that will remove that item. If a user is on a touch device ( e.g. Safari / Brave / Chrome on iOS ) and they click the delete button, the button in the next item will now display a hover state, as if it was the button being touched.

This seems to be related to an overarching issue that's been widely documented where touch events result in "sticky" hover states. However in most of these cases it's a single button that is not removed after it's touched, this is expected and the default behaviour of most browsers appears to be that the hover state is maintained until a different element is touched. However in this case, the original element should be removed.

React version: 17.0.2

## Steps To Reproduce

1. Open [this sandbox](https://qggwpt.csb.app/) with a touch device
2. Tap the "Delete" button for item one
3. Notice that the "Delete" button for item two has a red background, indicating a hover state.

https://codesandbox.io/s/intelligent-hoover-qggwpt?file=/src/App.js

## The current behavior

When a button is touched and then removed from a list, its sibling receives the hover event.

## The expected behavior

When a button is touched and then removed from a list, there is no currently active, focussed, or hovered element.

**Comment by technoAri** [comment]
Was not able to reproduce the issue, can you please confirm if this still exist ?

**Comment by matt-sanders** [comment]
Yep it still seems to be happening. I've attached a screen recording. Notice how I tap "delete" on number one, but once it's removed, the "delete" button for number two is highlighting, indicating that was the button I tapped, when it wasn't.

https://user-images.githubusercontent.com/7637051/191859835-5d6dabd0-3a43-4188-96f3-e232af104298.MP4

**Comment by senkiv-n** [comment]
+1
