### ISSUE TITLE
React 18 error: "'node_modules/react/jsx-dev-runtime.js' does not provide an export named 'jsxDEV'"

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [facebook/react#24204]
Hi, I started migrating from react@17 to react@18, before I replaced the old `render()` function for the new one, `createRoot()`, everything was fine. Once I replaced it, the error appeared:
```shell
Uncaught SyntaxError:
The requested module '/@fs/home/gabriel/Documents/VSCode/my_projects/muse/node_modules/react/jsx-dev-runtime.js'
does not provide an export named 'jsxDEV' (at index.tsx:16:10)
```

I'm using vite@2.8.6 with typescript@4.6.3, does anyone knows what to do here?

**Comment by gaearon** [comment]
This seems like something related to your module setup rather than to React. Can you file an issue with Vite?

**Comment by Gabriel-Alves-Cunha** [comment]
Will do. Thanks for the reply :+1:  :)
