### ISSUE TITLE
Request: replace the variables with object wrappers

### ISSUE THREAD

**Issue by JSerZANP** [facebook/react#24217]
Thanks for the great work of React and React 18!

I notice that the there are quite a few important variables in React source code to hold the state, 
wonder if it is worth it to replace them with object properties?

# What's the point ?

Doing so would make it easier to understand about the internals of React or event make some tools out of it. 

for example, for `workInProgress`. 

```js
// The fiber we're working on
let workInProgress: Fiber | null = null;
```

We are unable to monitor the change of `workInProgress`, if we put it as properties as below

```js
let variables = {
   workInProgress: null
}
```

then we can easily set up `Proxy` traps to inspect what is going on.

**Comment by gaearon** [comment]
Using object properties together with Proxies would be slower than regular variables.

**Comment by JSerZANP** [comment]
yeah,  I mean the purpose is for non-prod build.
we only want to set up Proxies for special purpose, something profiling build.

**Comment by gaearon** [comment]
It's a non-goal for us to make it easier to build tools that depend on implementation internals since these tools will break with every refactor.
