### ISSUE TITLE
Breaking change to transferPropsTo semantics in 0.12: defaultProps take precedence

### ISSUE THREAD

**Issue by steadicat** [facebook/react#2421]
The semantic of the interaction between `transferPropsTo` and default props has changed in 0.12. In 0.12, default props override transferred props. In previous versions of React the opposite would happen. This doesn't seem mentioned in the release notes. 

Here’s a fiddle: http://jsfiddle.net/06kfekLk/

If this is an intentional decision, it should probably be mentioned in the release notes. If it's an unintended side effect of the internal changes to default props, it should probably be fixed.

**Comment by spicyj** [comment]
Sorry that this bit a few of you, but it's too late to do anything now so I'm closing this.
