### ISSUE TITLE
React 18 - ReactDOM Warning on console! 

### ISSUE THREAD

**Issue by passariello** [facebook/react#24213]
So, a warning all time! ... I use createRoot instead ReactDOM but... message don't want to disappear! :/

![Screenshot 2022-03-30 074235](https://user-images.githubusercontent.com/17809213/160862281-18a9bf28-7977-4750-b3e0-b64f1e47c326.png)

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it. 

Where is `createRoot` coming from? Note that it should be `createRoot(container).render(<App />)`. The `createRoot` in your screenshot seems to not be imported from `react-dom/client`

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by passariello** [comment]
Thanks for you answer. I just update React from 17 to 18.
I see the console error. Before everything works fine and no issues.
Now, using createRoot from import createRoot from "react-dom"... I receive this error message
I try to simplify removing some my component and make a look like what you suggested but. No.
Also you mention "react-dom/client" but it's same.

![Screenshot 2022-03-30 081254](https://user-images.githubusercontent.com/17809213/160869646-5b3cc2ac-709d-4767-bc7d-a6b3861ba914.png)
![Screenshot 2022-03-30 081355](https://user-images.githubusercontent.com/17809213/160869651-9f51db9a-64ee-4af9-a9ef-ad92122945d8.png)
eRoot from "react-dom"... I receive this error message

**Comment by val1984** [comment]
Your import should be changed to:
```ts
import { createRoot } from 'react-dom/client'
```

**Comment by passariello** [comment]
![Screenshot 2022-03-30 081916](https://user-images.githubusercontent.com/17809213/160870902-2251b08e-01f7-44f9-9252-571b8e8a6bac.png)
![Screenshot 2022-03-30 081955](https://user-images.githubusercontent.com/17809213/160870906-63296064-11de-4936-96e1-9155ebefbe5b.png)

**Comment by val1984** [comment]
> ![Screenshot 2022-03-30 081916](https://user-images.githubusercontent.com/17809213/160870902-2251b08e-01f7-44f9-9252-571b8e8a6bac.png) ![Screenshot 2022-03-30 081955](https://user-images.githubusercontent.com/17809213/160870906-63296064-11de-4936-96e1-9155ebefbe5b.png)

You need curly braces around `createRoot`.

**Comment by passariello** [comment]
Thanks guys! ... :)
