### ISSUE TITLE
React 18 useTransition

### ISSUE THREAD

**Issue by quangnmwork** [facebook/react#24212]
Hi , I'm using useTransition with React 18 . When i'm imported useTransition with React Typescript . I have the following error : 
Module '"react"' has no exported member 'useTransition'.
    1 | import { generateProducts } from "./data";
  > 2 | import { ChangeEvent, useState, useTransition } from "react";
Does Typescript not support useTransition ?

**Comment by eps1lon** [comment]
React 18 types are currently only available by using `import type {} from 'react/next'` once in your codebase. Work for stable types is under way in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by val1984** [comment]
> React 18 types are currently only available by using `import type {} from 'react/next'` once in your codebase. Work for stable types is under way in [DefinitelyTyped/DefinitelyTyped#56210](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210)

You may also add this in the `compilerOptions` of your `tsconfig.json` file:
```json
"types": ["react/next", "react-dom/next"]
```

**Comment by tohsaka888** [comment]
> > React 18 types are currently only available by using `import type {} from 'react/next'` once in your codebase. Work for stable types is under way in [DefinitelyTyped/DefinitelyTyped#56210](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210)
> 
> You may also add this in the `compilerOptions` of your `tsconfig.json` file:
> 
> ```json
> "types": ["react/next", "react-dom/next"]
> ```

thanks, i have used it to solve this problem!
