### ISSUE TITLE
suggestion: Suspense support delay

### ISSUE THREAD

**Issue by smbera** [facebook/react#24238]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

## The expected behavior
can Suspense support delay?
Everytime when render page, the fallback will first show, no matter components get fast

**Comment by gaearon** [comment]
Can you be a bit more specific about what you're using Suspense for? Is it code splitting, data fetching, or something else? There are different solutions to this depending on what you're hitting.

**Comment by bvaughn** [comment]
> Everytime when render page, the fallback will first show, no matter components get fast

Are you using the legacy `render` method? Have you tried using `createRoot`?

```js
import { createRoot } from "react-dom/client";

const root = createRoot(domElement);
root.render(<YourApp />);
```

**Comment by sunderls** [comment]
There seems to be some regression on Suspense fallback commit throttling? 

reproduced with below demo

in React 18-alpha version,  throttled  [codesandbox link](https://codesandbox.io/s/suspense-throttled-in-react-18-alpha-zjbhwz)
in React 18 release version, this is no longer working [codesandbox link](https://codesandbox.io/s/suspense-not-throttled-in-react-18-release-8j7ypq?file=/src/_app.js)

I also pulled a DRAFT pr https://github.com/facebook/react/pull/24253, but not confident enough for review yet..
