### ISSUE TITLE
Bug in 0.12 (and 0.11.2) — type.apply error: type,apply is not a function

### ISSUE THREAD

**Issue by roycehaynes** [facebook/react#2423]
I've reverted all my commits tonight only to learn that Reactjs stopped being awesome.

Specifically, I nuked my node_modules to get a fresh npm install and then this happened...

![screen shot 2014-10-29 at 1 47 06 am](https://cloud.githubusercontent.com/assets/463577/4822389/fc0d11be-5f40-11e4-97fa-660d28caf191.png)

...which led me to this...

![screen shot 2014-10-29 at 1 47 40 am](https://cloud.githubusercontent.com/assets/463577/4822390/ff2932ec-5f40-11e4-94bd-49f07a1de86d.png)

When I look at the type object in debugger, it has no apply function. But, if does have type.render.apply() function.

I'm not sure why this changed but it did. 

My package.json looks like [this](https://gist.github.com/roycehaynes/c6bb5c725e492127f5b0)

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/facebook/react/2423/414).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
