### ISSUE TITLE
eslint-plugin-react-hooks CHANGELOG missing 4.4.0 release

### ISSUE THREAD

**Issue by katerberg** [facebook/react#24233]
Currently the CHANGELOG shows 4.3.0 as the latest version of `eslint-plugin-react-hooks`, but at least on `main`, there is not a 4.4.0.

React version: n/a

## Steps To Reproduce

1. View Changelog
2. Compare to version on https://www.npmjs.com/package/eslint-plugin-react-hooks

Link to code example: n/a

## The current behavior

No 4.4.0 explanation in CHANGELOG.md

## The expected behavior

4.4.0 explanation in CHANGELOG.md

**Comment by bvaughn** [comment]
I think 4.4.0 was essentially a no-op release to correspond with React 18 release (though cc @acdlite to confirm). Looking at what's changed in the `eslint-plugin-react-hooks` package between the 4.3.0 release and Monday's 4.4.0 "release" I see:

```sh
git diff c3f34e4beb67a4ddd85a9456ebc9013d123aa6ee 34aa5cfe0d9b6ec4667e02bf46ab34d83dfb2d6d packages/eslint-plugin-react-hooks/
```

```diff
diff --git a/packages/eslint-plugin-react-hooks/package.json b/packages/eslint-plugin-react-hooks/package.json
index 6bf810a77..1c99c2ffd 100644
--- a/packages/eslint-plugin-react-hooks/package.json
+++ b/packages/eslint-plugin-react-hooks/package.json
@@ -1,7 +1,7 @@
 {
   "name": "eslint-plugin-react-hooks",
   "description": "ESLint rules for React Hooks",
-  "version": "4.3.0",
+  "version": "4.4.0",
   "repository": {
     "type": "git",
     "url": "https://github.com/facebook/react.git",
@@ -10,7 +10,6 @@
   "files": [
     "LICENSE",
     "README.md",
-    "build-info.json",
     "index.js",
     "cjs"
   ],
```

**Comment by katerberg** [comment]
Thanks so much @bvaughn. That definitely seems like the right fix!
