### ISSUE TITLE
Bug: Error with upgrading to react 18 :ERROR in ./src/index.js 7:0-40  Module not found: Error: Can't resolve 'react-dom/client'

### ISSUE THREAD

**Issue by sajithamim** [facebook/react#24231]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by LK-Champ** [comment]
I have the same problem, but I have upgraded to react 18.

-    "react": "^16.13.0",
+    "react": "^18.0.0",
-    "react-dom": "^16.13.0",
+    "react-dom": "^18.0.0",
-    "@types/react-dom": "^16.9.5",
+    "@types/react-dom": "^18.0.0",

ERROR in ./src/index.tsx
Module not found: Error: Can't resolve 'react-dom/client'

**Comment by gaearon** [comment]
We can’t help without a reproducing project. The module is definitely there.

**Comment by adamsp70** [comment]
I'm getting exactly the same after following the upgrade instructions. 

No warning in my IDE but cannot build or run the project:

`yarn build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'react-dom/client' in '/Users/paul.rousou-adams/Documents/tms-rule-builder-ui/src'`

I have....
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-redux": "^7.2.8",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "@types/react": "^18.0.8",
    "@types/react-dom": "^18.0.0",
    "@types/react-redux": "^7.1.24",
    "@types/react-router-dom": "^5.3.3",

**Comment by gaearon** [comment]
We can't help without a reproducing project, sorry.

**Comment by gaearon** [comment]
I'm locking the thread because the comments without reproducing projects are not helpful. `react-dom/client` definitely exists so something is wrong with your setup. We can't guess what's wrong without a project you can share.
