### ISSUE TITLE
Bug: React hooks composition fail when packaging into different entries

### ISSUE THREAD

**Issue by lavcraft** [facebook/react#24230]
Hello, i develop a multiproject application with react. I want to share some code between projects and create npm package for this purpose.

[Example with reproduce problem]([react-hooks-composition-in-webpack-entry-problem-example](https://github.com/lavcraft/react-hooks-composition-in-webpack-entry-problem-example)

Project structure in nutshell:
```
sdk project - builded by webpack
-- entry1
     -- useCall hook. This hook call useDevices hook from entry2
-- entry2
    -- useDevices hook
ui project - next.js project with ui
package.json
   -- link to sdk project
```

React hook `useContext(Context)` doesn't work when call from another hook from different entry

React version: 17.0.3

## Steps To Reproduce

Abstract example:
1. I have `useHook1` and `useHook2`. `useHook2` call `useHook1` inside
2. Configure webpack with two entries - `/src/usr-hook1` and /src/usr-hook2` for some reason
3. Import in main application and use my hooks like this

```javascript
const Component: React.FC = () => {
    const devices = useHook1();
    const call = useHook2();
    return null
}
export withHook1(withHook2(Component));
```

Result:
1. `useHook1` - return right value in Component
2. `useHook1` inside useHook2 return undefined <-- problem here

Link to code real example:
Reproducible example - [react-hooks-composition-in-webpack-entry-problem-example](https://github.com/lavcraft/react-hooks-composition-in-webpack-entry-problem-example)

1. Clone project
2. `npm i`
3. `npm run all:start` or `npm run sdk:dev` and then `npm run ui:dev` in different terminal
4. open http://localhost:3000 and see console logs

## The current behavior
useHook1 return undefinde inside useHook2

## The expected behavior
useHook1 return store in Provider value inside useHook2

**Comment by gaearon** [comment]
Context uses referential identity by design. If context objects are referentially different, React will treat them as different contexts.

You need to change the build process so that any contexts you use are defined in a shared bundle that’s imported from both separate bundles. Then context will work.

**Comment by lavcraft** [comment]
@gaearon thanks for your response!

I think i understand what you mean. But, could you say - declare this contexts in separate file (also declare as another entry in webpack) is not enough?
I mean this code - https://github.com/lavcraft/react-hooks-composition-in-webpack-entry-problem-example/blob/master/packages/sdk/webpack.config.js#L20

Al contexts declared in separate file, which shared between entrupoints - https://github.com/lavcraft/react-hooks-composition-in-webpack-entry-problem-example/blob/master/packages/sdk/src/store/contexts.ts

What is wrong?

**Comment by lavcraft** [comment]
I understand what it no react question. But in webpack issues this also closed and referenced to react community :) I'm disoriented a lot. 

PS: And also greeting from HolyJS Dan! :) Saw you interview, very cool and inspired

**Comment by gaearon** [comment]
> But, could you say - declare this contexts in separate file (also declare as another entry in webpack) is not enough?

From what I understand, this creates a new entry point for them (good) but it doesn’t prevent other entry points from bundling a copy of the same file. So your new entry point is probably not being used. (I haven’t looked closely.) What you want is to mark that entry point as an “external” for all other bundles (webpack term) so that webpack keeps a require to it in the compiled output instead of trying to include its code in each bundle.

> But in webpack issues this also closed and referenced to react community :) 

The problem is generic and has nothing to do with React per se. I would suggest to phrase it as “I have shared module state between bundles but webpack copies it into each bundle. How do I mark that shared module as external so that it doesn’t get copied”.

**Comment by lavcraft** [comment]
I appreciate the detailed answer. It’s very helpful for formulate my problem.

**Comment by lavcraft** [comment]
@gaearon one more try - isolate nexted into external module. But nothing todo

Create example in new branch - https://github.com/lavcraft/react-hooks-composition-in-webpack-entry-problem-example/tree/depends-on-experiments

Not project structure looks like
```
packages
  sdk
    store/call <-- contains useCall and withCall. Call @company/sdk-shared/react/devices.useCall
  sdk-shared
    react/devices <-- contain useDevices and withDevices
  ui
```

But symptoms not changed, `useCall` invocation return undefined inside `useCall`

**Comment by gaearon** [comment]
Your project gives me:

```
next-dev.js?36dd:25 error while import component which used useDevices/withDevices and useCall/withCall: TypeError: (0 , _company_sdk_store_devices__WEBPACK_IMPORTED_MODULE_2__.withDevices) is not a function TypeError: (0 , _company_sdk_store_devices__WEBPACK_IMPORTED_MODULE_2__.withDevices) is not a function
```

This is a different error than the one you're describing?

**Comment by lavcraft** [comment]
@gaearon this problem will appear when dependOn option was added. This problem in master, are start app from branch `depends-on-experiments` ?

**Comment by gaearon** [comment]
Sorry I don’t know anything about `dependOn` and can’t help with that.

**Comment by lavcraft** [comment]
What i do for reproduce:

1. git clone git@github.com:lavcraft/react-hooks-composition-in-webpack-entry-problem-example.git
2. cd react-hooks-composition-in-webpack-entry-problem-example
3. git checkout depends-on-experiments
4. npm ci
5. npm run all:start (if you have tmux. It start session with all required processes). Instead - run manually `npm run sdk-shared:dev`, `npm run sdk:dev`, and then `npm run ui:dev`
