### ISSUE TITLE
ESLint - use React type definitions / hooks without `React` namespace

### ISSUE THREAD

**Issue by mikedidomizio** [facebook/react#24246]
When using React type definitions and hooks, have the option to highlight preferred way of using them.

```tsx
import React, {useState} from 'react';

const Example = () => {
    const [count, setCount] = useState(0);
    ...
    return <>count</>;
};
```

technically you could do this as well:

```tsx
import React from 'react';

const Example: React.FunctionComponent = () => {
    const [count, setCount] = React.useState(0);
    ...
    return <>count</>;
};
```

This is a basic example but if you use a lot of hooks and what not, you can understand how it can get ugly.
For consistency I'd like to suggest an added rule to [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) to prefer definitions/hooks to not be used with the `React` namespace.

I know the [Introducing Hooks](https://reactjs.org/docs/hooks-intro.html) documentation shows it like the first example and I prefer it that way as well.  I assume that is the React preferred way.

**Comment by sunderls** [comment]
I think this is out of the scope of React
React could lint what argument each API is called with , like the callback and deps in `useState(callback, deps)`,
but it cannot lint how `useState` is called.

**Comment by mikedidomizio** [comment]
The idea would be to report the namespace as such:

https://user-images.githubusercontent.com/5728044/162094087-b80918de-0a5f-4a95-90d9-aa934b7d75cf.mov

Then update each reference by removing `React.` and updating the `react` import with what it now requires.  So far I believe it's possible to do, whether it's something people would like is another story.  There may be more complex usages that I'm not aware of as well.

My example component isn't great but the idea is to remove unnecessary clutter if a file has many instances of `React.`.

**Comment by mikedidomizio** [comment]
After more time thinking about this, I feel it's only the `React` namespace that bugs me, I use `jest` but am fine with `jest.SpyInstance`.  I think in the end I'm looking for consistency within the files I'm looking at.  I'm closing this at this time.
