### ISSUE TITLE
Bug: twice render（）

### ISSUE THREAD

**Issue by zjp1300** [facebook/react#24241]
![image](https://user-images.githubusercontent.com/59366203/161240568-864f4bd1-c9e5-4e4e-b42e-bdc251b5ae12.png)

why the render() twice?

**Comment by zjp1300** [comment]
https://codesandbox.io/s/peaceful-meadow-7d59uy?file=/src/index.js

**Comment by zjp1300** [comment]
The app is initialized twice by React -v 18.0

**Comment by harish-sethuraman** [comment]
Since the App is in `StrictMode` mode it is rendered twice. you can read more about strict mode here https://github.com/reactwg/react-18/discussions/19. Also try removing `StrictMode` in your sandbox's `index.js` and that might fix the issue

**Comment by luckymore** [comment]
@harish-sethuraman 
> React will only do this for development builds
but this demo seemingly production

**Comment by harish-sethuraman** [comment]
This demo is using development build only. You can open the preview in a new window and notice it. https://7d59uy.csb.app/ 
<img width="829" alt="Screenshot 2022-04-01 at 4 48 03 PM" src="https://user-images.githubusercontent.com/32865581/161253350-ab0f527e-f16f-4171-858e-bb6dc616ef0b.png">

You can see that the second console is also dimmed out https://github.com/reactwg/react-18/discussions/96

**Comment by gaearon** [comment]
CodeSandbox always runs in development mode.
