### ISSUE TITLE
Bug: useEffect with empty deps array is fired twice with StrictMode enabled in React 18

### ISSUE THREAD

**Issue by JakeYallop** [facebook/react#24245]
React version: 18.0.0

In 18.0.0, StrictMode causes a `useEffect` with an empty deps array to execute twice when a component mounts. This did not happen in 17.0.2.

## Steps To Reproduce

Add a `useEffect` with an empty deps array, e.g
```jsx
useEffect(() => {
    console.log("test")
}, [])
```
And ensure StrictMode is enabled:
```jsx
  <StrictMode>
    <App />
  </StrictMode>,
```

Link to code example:

React 17.0.2: https://codesandbox.io/s/youthful-smoke-z3nxmv
React 18.0.0: https://codesandbox.io/s/nervous-tess-7qsm1r

Observe that in the 18.0.0 version, the `console.log` and `fetch` statements are executed twice.

## The current behavior
`useEffect` with empty deps array is executed twice.

## The expected behavior

17.0.2 behaviour is preserved, the `useEffect` is only fired once.

Is this an expected change with 18.0.0? One common use case for `useEffect` is to make a web request - these web requests are now being fired twice when in StrictMode. In the code examples, I am making such a request and both can be seen in the network tab in devtools.

To be clear, its not a major issue for me at the moment, but its plausible that the duplicated `useEffect` call could result in differing behaviour for a component in development with StrictMode vs in production, depending on what the `useEffect` is doing.

**Comment by gaearon** [comment]
This is expected behavior in React 18 Strict Mode. As all other important changes, it is described in the upgrade blog post: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

**Comment by JakeYallop** [comment]
Thanks - missed that bit in the announcement.
