### ISSUE TITLE
Documentation versions

### ISSUE THREAD

**Issue by shripadk** [facebook/react#2424]
It would be great to have documentation for various versions of React similar to http://nodejs.org/docs/

Currently the docs points to the latest version and until our apps are upgraded it'll be nice to be able to refer to documentation for earlier versions.

Also I'm interested in helping move towards React powered docs and remove Jekyll dependency without disturbing the existing structure. Is the team willing to consider contributions in this area?

@sebmarkbage @zpao

**Comment by gaearon** [comment]
We are closer to being able to do this now.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#85

Let's continue the discussion there! Sorry for the inconvenience.
