### ISSUE TITLE
Can not install apollo client v3.5.10 on React 18

### ISSUE THREAD

**Issue by oxvijay** [facebook/react#24244]
Hello there,

I am trying to install apollo client v3.5.10 on fresh React 18, but it's throwing dependency errors.
![image](https://user-images.githubusercontent.com/38243819/161300186-6b4553eb-5a56-4697-9af1-c99fd4c306e5.png)

**Comment by gaearon** [comment]
You need to wait for a release of Apollo Client that declares compatibility with 18. Alternatively, you can retry with `--legacy-peer-deps` as the message says.
