### ISSUE TITLE
Bug: StrictMode renders more than once

### ISSUE THREAD

**Issue by lijianru** [facebook/react#24242]
The demo with StrictMode renders one more time than the demo without StrictMode
https://codesandbox.io/s/react18-y7fy2h?file=/src/App.js
https://codesandbox.io/s/react18-no-strictmode-7prk4n?file=/src/App.js

React version: 18

## Steps To Reproduce
It renders one more time on initialization and when the button is clicked

Link to code example:
https://codesandbox.io/s/react18-y7fy2h?file=/src/App.js
https://codesandbox.io/s/react18-no-strictmode-7prk4n?file=/src/App.js

## The current behavior
The demo with StrictMode renders one more time than the demo without StrictMode

## The expected behavior
The demo with StrictMode and the demo without StrictMode render the same number of times

**Comment by gaearon** [comment]
That is exactly what strict mode is supposed to do. (The behavior is development only.) Please read the Strict Mode documentation.
