### ISSUE TITLE
Bug: After upgrade to React 18

### ISSUE THREAD

**Issue by ctsvenkat** [facebook/react#24243]
Hi 

I upgraded React from 17.2.0 to React 18 Rc0 vserion after that I am betting below error, I could not understand why this happening and I am new react as well.

Error is: export 'jsxDEV' (imported as '_jsxDEV') was not found in 'react/jsx-dev-runtime' (module has no exports)
Thanks in Advance.

**Comment by gaearon** [comment]
Please provide a reproducing project. We can't help without it.
