### ISSUE TITLE
ESlint: eslint-plugin-react-hooks is going too far 

### ISSUE THREAD

**Issue by zettadam** [facebook/react#24252]
I think that `eslint-plugin-react-hooks` rules might be going to far. I have a function that starts with `use` prefix but it doesn't mean that I wrote a React hook, especially when the code in question is in not related or used with React. Here's what I mean:

<img width="669" alt="Screen Shot 2022-04-01 at 4 15 02 PM" src="https://user-images.githubusercontent.com/516382/161343036-77d356a6-9628-432d-9770-5205822e3742.png">

**Comment by gaearon** [comment]
Sure but that’s kind of how the plugin works. I suggest excluding this file/folder from the plugin since it doesn’t have React-related code in it.

**Comment by zettadam** [comment]
Wait a minute! You're saying that any function that starts with `use` prefix is a hook now?

**Comment by gaearon** [comment]
From the plugin’s perspective, yes. (In the absence of an effect tracking type system or special syntax that’s the best we can do.)

**Comment by zettadam** [comment]
I understand the perspective, though I wasn't expecting it. Perhaps this case could be documented somewhere with a short note. I wouldn't know it if I hadn't seen it. It struck me as quite a grab of vocabulary since `use` is such a common word to start a function name with.

**Comment by gaearon** [comment]
Yeah we needed to balance something that’s short enough to look natural and that’s relatively unclaimed. While not entirely uncommon, we’ve found “use” way less common for function names (it’s typically used for booleans) than other short prefixes.
