### ISSUE TITLE
Proposal: React's props with the same name as their value

### ISSUE THREAD

**Issue by platonlukyanov** [facebook/react#24264]
Hi, this problem was searched on [stackoverflow already](https://stackoverflow.com/questions/51148064/reacts-props-with-the-same-name-as-their-value). To me, code presented in stackoverflow answers look quite ugly.

We had a similar syntax inconvenience in JavaScript language and must have used syntax like this:
```js
return {
    name: name,
    text: text,
    content: content,
}
```
When the ES6 came we got the modern syntax and opportunity to make our code neater.
```js
return {
    name,
    text,
    content,
}
```

**Problem**
Still in React this problem is actual.
For example, we have a bunch of variables from props, inner variables and state. They all have the same name with props of childrean components. But passing these props looks gigantic.
```jsx
function ArticleDetails({ text, color }) {
    const [draft, setDraft] = useState(false);
    const today = new Date.now();
    return (
        <div>
               <ArticleHeader color={color} />
               <ArticleContent  draft={draft} today={today} text={text}/>
       </div>
    )
}
```
**Suggestion**
Implement `prop,` syntax
```jsx
...
<div>
       <ArticleHeader color, />
       <ArticleContent  draft, today, text,/>
</div>

```

**Comment by gaearon** [comment]
We’re not actively changing JSX at the moment, but https://github.com/facebook/jsx would be the right place to discuss syntax. There are already threads with a similar proposal there.
