### ISSUE TITLE
Bug: antd datepicker isnt work on react and react-dom 18 version

### ISSUE THREAD

**Issue by shant99** [facebook/react#24265]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by gaearon** [comment]
We can’t help without a reproducing example. Also, unless you’re sure there is a bug in React, please file an issue in the library first.

**Comment by deepakbhattmits** [comment]
Hi @shant99 ,

I also tried with this antd is incompatible with react 18. most of the components did not work as expected.

**Comment by gaearon** [comment]
@deepakbhattmits I'm not sure why you're copy pasting a part of another person's comment from https://github.com/facebook/react/issues/24239#issuecomment-1086902973, but in either being "heavy" is not relevant here. If there are 18 compatibility issues in antd, please discuss them in the antd repository. I will lock this issue to keep the discussion focused.
