### ISSUE TITLE
Bug: [eslint-plugin-exhaustive-deps] can't find unstable value.

### ISSUE THREAD

**Issue by geewoo94** [facebook/react#24268]
React version: 18.0.0 (not important)

## Steps To Reproduce
I'll show as a code.
<img width="593" alt="스크린샷 2022-04-04 오전 12 01 05" src="https://user-images.githubusercontent.com/65149763/161434194-868b7fbb-9571-40d8-a4e3-2b261506d9ac.png">

Link to code example:
https://codesandbox.io/s/stupefied-raman-g6j3fi?file=/src/App.js

## The current behavior
exhaustive-deps can't found unstable dependency.

## The expected behavior
Warn lint message.

## Opinion
I know this code is super weird but This code may be improved. something like
- Add more core lint rule like 'useState is always declared as a const'
- eslint-plugin-exhaustive-deps should find reallocation value. and calculate real value.
- Or just stay it.

I just wonder what is your opinion. thank you.

**Comment by gaearon** [comment]
Interesting find. If the binding is ever reassigned we should treat it as unstable.
