### ISSUE TITLE
React DevTools Can't access this page error

### ISSUE THREAD

**Issue by sugar3103** [facebook/react#24262]
My Google Chrome : Version 100.0.4896.60 (Official Build) (64-bit)
React DevTools : Version 4.24.0, Updated March 10, 2022
I have problem when using the tools, it showed as the picture below.
![image](https://user-images.githubusercontent.com/43548780/161410678-37dff0d6-6f97-43a3-8def-e0a75699006f.png)

**Comment by bvaughn** [comment]
What URL are you trying to use DevTools on? "restricted page" generally means that you're viewing something like another extension. That is a security limit imposed by Chrome that React DevTools can't do anything about.

**Comment by sugar3103** [comment]
all the website i have opened have showed that message, even facebook.com and reactjs.org
![image](https://user-images.githubusercontent.com/43548780/161470884-20d7ab82-acdc-4bf8-a456-27d0ef3c8842.png)
![image](https://user-images.githubusercontent.com/43548780/161470918-c4405552-929c-4a5d-9190-1574849ac983.png)

**Comment by sugar3103** [comment]
my currently running environment : 
- Microsoft Windows [Version 10.0.22000.556] -> showed restricted message
- Ubuntu 20.04.4 LTS focal -> working fine

**Comment by sugar3103** [comment]
> What URL are you trying to use DevTools on? "restricted page" generally means that you're viewing something like another extension. That is a security limit imposed by Chrome that React DevTools can't do anything about.

**Comment by dlpmmk** [comment]
我的问题和你一样，最后开启了几个按钮就行了。
![image](https://user-images.githubusercontent.com/80876235/193528629-27e00815-990b-476f-a38f-31b735ef22e6.png)
