### ISSUE TITLE
Bug: `suppressHydrationWarning` is not taken into account in production builds in React 18

### ISSUE THREAD

**Issue by nbouvrette** [facebook/react#24270]
React version: 18 

## Steps To Reproduce

1. Clone https://github.com/Avansai/next-multilingual
2. run: npm install
3. run: npm build
4. run: npm run start-example-build
5. Go to the following URL: http://localhost:3000/fr-ca/tests/routes-dynamiques/123
6. Open the console log: no errors
7. Kill the app, and update the react and react-dom package to version 18.0
8. Re-run steps 2 to 5
9. Open the console log: lots of hydration errors #[425](https://reactjs.org/docs/error-decoder.html?invariant=425), #[418](https://reactjs.org/docs/error-decoder.html?invariant=418) and #[423](https://reactjs.org/docs/error-decoder.html?invariant=423).

Link to code example:

https://github.com/Avansai/next-multilingual

## The current behavior

Using React 18, the tests are failing because of the errors being thrown in the console. 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/6453322/161457567-c0777ffa-a3e5-4e21-80bc-51619942299f.png">

I confirmed this was related to `suppressHydrationWarning` because as soon as I removed the following code from: https://github.com/Avansai/next-multilingual/blob/main/example/pages/tests/dynamic-routes/%5Bid%5D.tsx#L37

```jsx
<tr>
  <td>{messages.format('rowLocalizedWithAsPath')}</td>
  {/* Adding `suppressHydrationWarning` until
  https://github.com/vercel/next.js/issues/32772 is resolved */}
  <td suppressHydrationWarning={true}>{asPath}</td>
</tr>
```

The errors stop. However, I could not find any mention that `suppressHydrationWarning` was no longer supported with React 18 and these errors are only triggered on builds, not in dev mode (which is why I am opening this issue)

## The expected behavior

`suppressHydrationWarning`  should prevent these errors from being thrown.

**Comment by gaearon** [comment]
Ideally it would be nice to get a minimal repro too, that doesn't involve a whole project repository.

**Comment by gaearon** [comment]
OK, I got the project running.

This is a bug in React.

**Comment by gaearon** [comment]
This will be fixed by https://github.com/facebook/react/pull/24271. Thanks for reporting!

**Comment by nbouvrette** [comment]
Thanks @gaearon - sorry I didn't have a chance to provide a simpler repo to reproduce this!

**Comment by gaearon** [comment]
Fix out in 18.1.0.

**Comment by mjosh51** [comment]
Hi,
I can still confirm this bug in 18.2.0

**Comment by reneeichhorn** [comment]
Another interesting issue (but I'm not sure if it is related) is that when you have multiple elements that have hydration mismatches but are ignored / suppressed it is enough for one of them to be not suppressed to make them all fail hydration.
I made a small repro sandbox: https://codesandbox.io/s/sharp-wescoff-v2ffp9?file=/src/App.js

Here you will see that each of the `CauseHydrationMissmatch` component instances will produce one hydration error even though only one of them has `suppressHydrationWarning` set to false.

In the development build I'm only seeing this once.

**Comment by krzy789** [comment]
This error still occurs.

**Comment by jonathandewitt-dev** [comment]
@gaearon can we reopen this issue? Seems a lot of people including myself are facing issues in 18.2.0

**Comment by daveleee** [comment]
I believe using ### suppressHydrationWarning is more like ignoring the warning rather than finding the optimal solution. It's like just hiding letters but still exist. The better approach I think is to utilize dynamic, state or useEffect.
References:
https://nextjs.org/docs/messages/react-hydration-error
https://nextjs.org/learn/foundations/from-javascript-to-react/adding-interactivity-with-state
