### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by desalegn12** [facebook/react#24273]
React version:

## Steps To Reproduce

Link to code example:

## The current behavior
useEffect executed twice at the first render of the application. meaning before any change can be made to the UI

## The expected behavior
when the screen first appears, it would be perfect if useEffect called only once

**Comment by gaearon** [comment]
It's intentional behavior in Strict Mode in React 18. Your effects should ideally be resilient to this.

https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

You can remove `<StrictMode>` from your app (usually in `src/index.js`) if you're not sure how to fix the issue.
