### ISSUE TITLE
Bug: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".

### ISSUE THREAD

**Issue by Wang-zhechao** [facebook/react#24292]
React version:
18.0.0
## Steps To Reproduce

1. all code in html
2.run html code

Link to code example:

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>createRoot</title>
    </head>
    
    <body>
        <div id="app"></div>
    
        <script type="text/javascript" src="../js/react.development.js"></script>
        <script type="text/javascript" src="../js/react-dom.development.js"></script> 
        <script type="text/javascript" src="../js/prop-types.js"></script> 
        <script type="text/javascript" src="../js/babel.min.js"></script>    
        
        <script type="text/babel">
            class Person extends React.Component{
                render(){
                    const {name, sex, age} = this.props
                    //console.log(this)
                    return (
                        <ul>
                            <li>name:{name}</li>
                            <li>sex:{sex}</li>
                            <li>age:{age+1}</li>
                        </ul>
                    )
                }
            }
            Person.propTypes = {
                name: PropTypes.string.isRequired,
                sex: PropTypes.string,
                age: PropTypes.number
            }
            
            const container = document.getElementById('app');
            const root = ReactDOM.createRoot(container);
            root.render(<Person name='sheli' sex='female' age={19} />);
        </script>
    </body>
    </html>

## The current behavior
Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".    react-dom.development.js:73 

## The expected behavior
no waring out

**Comment by gaearon** [comment]
You can ignore this warning in `<script>` tag bundles. We've merged a fix for it but haven't released it yet.

**Comment by pan-0909** [comment]
Why did I successfully use createRoot from "react-dom" in js, but failed in tsx, react-dom/client
