### ISSUE TITLE
Bug: react升级成react18，但是types/react-route里没有限制 types/react的版本，导致类型兼容错误

### ISSUE THREAD

**Issue by zcw1994** [facebook/react#24309]
目前项目的版本 react的版本是17.x,  定义的types/react: "@types/react": "^17.0.20" "@types/react-dom": "^17.0.9",
    "@types/react-router-dom": "^5.1.8",

但是@type/react-router-dom 定义的
![image](https://user-images.githubusercontent.com/46340607/162380831-fe5f088a-965d-445e-8909-3c661aaa31eb.png)

导致他会去下载最新的 @types/react@18.0.0，导致目前项目的react组件类型错误

期望@type/react-router-dom 与 @types/react-dom 一样
![image](https://user-images.githubusercontent.com/46340607/162381065-64b7043f-0c31-44e5-92d7-97eda61ce3f9.png)

**Comment by zcw1994** [comment]
类型错误导致项目编译失败

**Comment by gaearon** [comment]
Any issues with `@types` should be reported in the https://github.com/DefinitelyTyped/DefinitelyTyped/ repo, where they're maintained. Or, in your example, `react-router` repo.
