### ISSUE TITLE
Support for selectionchange event for HTML input element and HTML textarea element

### ISSUE THREAD

**Issue by channyeintun** [facebook/react#24307]
# Feature Request 

"selectionchange" event for document is natively supported across all browsers. But,for HTML input element and HTML textarea element, it is only supported on Firefox. Therefore, it would be very helpful if those events are provided as sythetic events.  

[Check in caniuse](https://caniuse.com/?search=selectionchange)  

It would be implemented like  

```
onSelectionChange={()=>{}}
```

**Comment by gaearon** [comment]
I think we support `onSelect` which under the hood uses `onselectionchange`. Does it do what you want?

**Comment by channyeintun** [comment]
It works fine when I change the selection using keys (pressing shift and left/right arrow) but it does not work properly when I change the selection using mouse or touchpad by dragging. 

"selectionchange" should be triggered every character the selection is changed which means not only on mouse pressed and mouse released.

I showed the demo: https://channyeintun.github.io/

You can see the difference with "React Synthetic Event" and with my custom event.
