### ISSUE TITLE
Bug: `react-hooks/exhaustive-deps` function calls on object inside hooks will require object as dependency instead of the function

### ISSUE THREAD

**Issue by akamfoad** [facebook/react#24300]
React built-in hooks like `useMemo`, `useEffect` and others as well, will complain about function calls on an object when the object itself is not included as dependency or when the function/property accessed is included in the dependency array, and I think it's a false positive.

I've searched in the issues and only one found #21624 similar to, but not quite the issue I wanted to report, if you think this issue is an overkill, please let me know, I'll move the discussion to the mentioned issue. 

The issue is, when you have a `foo` object which has `bar` function and `baz` string properties, returned by a custom hook `useFoo`.
When you want to memoize the result of a computation generated by `foo.baz()` call inside a `useMemo` or similar calls inside `useEffect` hooks, you have to included the dependencies of these hooks, which is quite standard, so you do this:

```js
const useMemoizedComputed = ()=>{
  const { foo } = useFoo()
  const memoizedComputation = useMemo(()=>{
    return foo.bar(foo.baz)
  },[foo.bar, foo.baz])

  return { memoizedComputation }
}
```

But you see `react-hooks/exhaustive-deps` rule warning that you've missed dependency `foo` on the `useMemo` hook.

You might think that, right, `foo` is a dependency too so you add:

```js
// code before
    },[foo, foo.bar, foo.baz])
// code after
```

But you see `react-hooks/exhaustive-deps` rule warning that you've unnecessary dependencies `foo.bar` and `foo.baz` on the `useMemo` hook, either include or delete it in the dependency.

You might think, `foo` is a dependency and since `bar` and `baz` are it's properties, it might trigger the update, so you remove them:

```js
// code before
    },[foo])
// code after
```

Alright, now ESlint is happy, but if you go check your application that depends on `useMemoizedComputed`, and if `useFoo` reuse it's `foo` object **internally**, for instance it mutates `baz` property when something related changes, and now the `useMemo` inside `useMemoizedComputed` doesn't trigger because actually `foo` didn't change at all, what changed is a property on it which the hook isn't depend on it directly, so your application is now broken.

## Steps To Reproduce

Please refer to this reproduction codesandbox: https://codesandbox.io/s/react-hooks-dependency-issue-3864xc?file=/src/App.js

which contains even more details and more real code than `foo` `bar` `baz` that explains the behavior of the issue mentioned before.

## The current behavior

ESLint wont let me add dependencies that I think my hook call is depend on it because the object that the dependency lives inside is included in dependency array and ESLint (`eslint-plugin-react-hooks`) thinks that it's the only dependency.

## The expected behavior

ESLint (`eslint-plugin-react-hooks`) may need to know/include all necessary dependencies or let the developer add dependencies that they think is necessary for the hook to have as dependency in addition to those ones that it ESLint thinks is a dependency of the hook.

**Comment by gaearon** [comment]
> for instance it mutates baz property when something related changes, and now the useMemo inside useMemoizedComputed doesn't trigger because actually foo didn't change at all, what changed is a property on it which the hook isn't depend on it directly, so your application is now broken.

Are you saying something mutates `foo.baz`? Reading mutable fields during rendering (as when specifying dependencies) is not supported, and so the lint rule assumes you don't do that. It's very hard to predict the behavior in this case because the result depends on subtle timing and _when exactly_ (before or after mutation) a render happens.

The rule assumes any expression you put in the dependency list is by itself immutable. It's ok to keep mutable stuff deeper inside those objects, but it's not ok to use a mutable property as a dependency by itself. This is the same reason that `[ref]` is ok as a dependency but `[ref.current]` is not.

**Comment by akamfoad** [comment]
OK I think now I can better reason about the problem, just like reading a mutable during rendering isn't supported, when specifying a mutable dependency as well the app might not work properly or predictably as it does when the assumptions regarding immutability is met.

Thanks for your reply @gaearon.

**Comment by jordmantheman** [comment]
Can we bang on this drum one more time?

I created a little abstraction called `ShoppingCart` to coordinate some state and actions.

```
export type ShoppingCart<TItem> = {
 pending: Set<TItem>
 togglePending: (item: TItem) => void
 ...a bunch of other fields
}
```

The hook that returns this object doesn't try to memoize the ShoppingCart itself -- it returns a raw object. Here's a splice of the code.

```
const [pending, setPending] = React.useState<Set<TItem>>(new Set())

return {
  pending,
  togglePending: React.useCallback(
      (item: TItem) =>
        setPending(s =>
          s.has(item) ? new Set([...s].filter(i => i !== item)) : new Set([item, ...s])
        ),
      [setPending]
    ),
}
```

And here's some downstream code.

```
  const memoizedTogglePendingItem = React.useCallback(
    (item: Question) => shoppingCart.togglePending(item.id),
    [shoppingCart.togglePending] <-- exhaustive check fails
  )
```
* Yes, I could destructure the object in my consuming component, but that becomes untenable as the number of fields grows.

Reading the above -- the error makes sense. The returned object *is* mutable and the linter doesn't know if some rogue code mutated it.

Is it a bug that adding `readonly` to the fields doesn't help the situation?

My gut tells me my venture into more OOP paradigms in the hooks realm is showing some of my fundamental gaps in knowledge, so please be gentle :)

**Comment by florianmartens** [comment]
@jordmantheman Looking at this now. I'm also really confused by this. I'm trying to understand the argument here but IMO it falls appart since this is allowed:

```
const obj = {a: "abc"}

const value = useMemo(() => {
   console.log(obj.a);
}, [obj.a])
```

`obj` is just as mutable as any object returned from a hook. Yet I am allowed to add it to the deps arr. In this case Dan's statement breaks apart for me:

> The rule assumes any expression you put in the dependency list is by itself immutable. It's ok to keep mutable stuff deeper inside those objects, but it's not ok to use a mutable property as a dependency by itself. This is the same reason that [ref] is ok as a dependency but [ref.current] is not.

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/34092#issuecomment-3152931289
