### ISSUE TITLE
Console dimming on second StrictMode render forces string cast

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/react#24302]
React version: 18.0.0 (congrats on the release ☺️)

## Steps To Reproduce

1. During rendering of a component, log something that doesn't naturally cast to a string (e.g., `console.log(new Set())`).
2. Wrap the tree in `StrictMode`.
3. Observe the console.

Link to code example: https://codesandbox.io/s/magical-roman-wyeud7?file=/src/App.js

Note that the console dimming isn't applied to the inline CodeSandbox dev tools, so to see the issue, you need to visit the "fullscreen view" here: https://wyeud7.csb.app

## The current behavior

In Chrome:

<img width="479" alt="Screen Shot 2022-04-07 at 4 19 09 PM" src="https://user-images.githubusercontent.com/1158733/162289676-bb6ba95f-4f85-4ce3-a179-10dfed3d5ad1.png">

As expected, there are two console logs, one dimmed. Unfortunately, the way that the dimming works forces the second log to be serialized to a string. This has two issues:
1. It can result in two of the "same" logs looking very "different" from each other, which is confusing to developers. For example, in the screenshot above, it's pretty surprising that those two console lines occur from the same `console.log` call.
2. It prevents browser dev tools introspection. This can make it inconvenient or impossible to compare the two values if the string cast doesn't include the value, as in the screenshot above. This is problematic because a key use case of printing both values is to check whether they're the same.

You can kind of work around the second issue by writing your own string cast at the log callsite, but you lose the DX of introspection, which is pretty unfortunate especially in the case of large/deeply-nested objects, etc. Easier to compare two native console values than two `JSON.stringify` dumps.

## The expected behavior

While there is a new (appreciated!) dev tools option to suppress logging for the second render entirely, there is no way to disable the dimming feature.

Any of the following options would solve the issue:
1. Provide a dev tools option to disable dimming.
2. Remove the dimming feature entirely. (So that both logs are always printed the same way.)
3. Update the dimming implementation so that it doesn't force a string cast. (Guessing this isn't possible.)
4. Improve serialization of complex values. (IMO this isn't a great option because it doesn't solve the issue of consistency/confusion, but it would be better than the current behavior if all other options are ruled out.)

Thanks for considering.

**Comment by gaearon** [comment]
> Unfortunately, the way that the dimming works forces the second log to be serialized to a string. 

> Update the dimming implementation so that it doesn't force a string cast. (Guessing this isn't possible.)

I don’t see why that wouldn’t be possible. I might be missing something but my guess is that it’s a simple mistake somewhere. Do you want to have a look?

**Comment by billyjanitsch** [comment]
>I don’t see why that wouldn’t be possible.

The dimming works by using the browser's console styling API (see the "Styling console output" section of [this page](https://developer.mozilla.org/en-US/docs/Web/API/console)) which only lets you apply colors to strings because it's done via directive, e.g.:

```js
console.log('%cfoo', 'color: blue')
```

So the React implementation has to cast to a string:

https://github.com/facebook/react/blob/f56dfe950b206651913bf0b836c10592c393357d/packages/react-devtools-shared/src/hook.js#L294

(`format` happens to also cast to a string, but even if it didn't, the cast here would need to exist regardless. A bit more context in https://github.com/facebook/react/pull/22030 and https://github.com/facebook/react/pull/22064.)

So I don't see any way to preserve the dimming but avoid the cast.

(I guess you could apply the dimming conditionally, only to args that are strings? Not sure if that's more or less confusing, and the implementation would be a bit complex because, if I understood correctly, this is also the code path that formats component stacks.)

**Comment by gaearon** [comment]
> I guess you could apply the dimming conditionally, only to args that are strings?

Yes. I think that would be fine.

**Comment by billyjanitsch** [comment]
>Yes. I think that would be fine.

I think this is doable, it just gets a bit tricky because the console API has a mixed interface that supports both string substitutions and multiple arguments. So you need to interact with other directives. For example:

```js
// userland code:
console.log('A', 'B %d %s', 1, 'C', 2, 'D')

// needs to be transformed to:
console.log('%cA', 'color: grey', '%cB %d %s', 'color: grey', 1, 'C', 2, '%cD', 'color: grey')
```

Happy to try a PR. Are you confident enough in this behavior that I should get started, or do you want to discuss with anyone first?

I do have one question about the existing implementation. Currently, React re-implements the directive substitutions while casting all of the args to a single string:

https://github.com/facebook/react/blob/f56dfe950b206651913bf0b836c10592c393357d/packages/react-devtools-shared/src/hook.js#L175-L210

I see why this is necessary when dimming the entire line, but I think it might be avoidable otherwise. So I just wondered if this has any other purpose (behavior in Node or other browser envs?) before I remove it. Didn't see anything in the implementing PR.

**Comment by gaearon** [comment]
I was thinking in the realm of changing

https://github.com/facebook/react/blob/f56dfe950b206651913bf0b836c10592c393357d/packages/react-devtools-shared/src/hook.js#L293-L294

to something like

```js
            if (color) {
              if (typeof args[0] === 'string') {
                originalMethod(`%c${format(...args)}`, `color: ${color}`);
              } else {
                originalMethod(...args);
              }
```

**Comment by gaearon** [comment]
Oh I see, you'd need to check all of them... I think as a first approximation it's ok to opt out if any of them are non-strings. But what you're suggesting is preferable to that. Yeah I think you can stake a stab at this.

**Comment by billyjanitsch** [comment]
Yeah I think it's not so bad as long as it's ok for me to squash the existing substitution re-implementation. Something like:

1. Chunk the args into groups that capture directives and values.<br>e.g., `['A %s', 'B', 1, 'C']` => `[['A %s', 'B'], [1], ['C']]`.
2. For each group, check whether the first arg is a string. If so, prefix it with `'%c'` and insert dimming after it.<br>e.g., `['A %s', 'B']` => `['%cA %s', 'color: grey', 'B']`.
3. Flatten the groups and forward to the native method.<br>e.g., `originalMethod('%cA %s', 'color: grey', 'B', 1, 'C')`

**Comment by billyjanitsch** [comment]
Seems like it would be nice to get rid of the substitution code anyway because it's a bit buggy and probably hard to get perfectly right. e.g., `console.log('%o', [])` normally prints `[]` but when the console is patched by React rn it prints `%o `.

**Comment by billyjanitsch** [comment]
Ah sorry I misunderstood the console API: you can only specify directives in the first argument. I understand the current React implementation better now.

That means the approach we discussed won't work (because of cases like `console.log('A', [], 'B')`) but I'll try another idea.

**Comment by billyjanitsch** [comment]
Put up a WIP https://github.com/facebook/react/pull/24306 with a basic working implementation. Needs tests, callsite updates, etc. Not sure when I'll have time to continue so if anyone's eager and wants to take it over from there, feel free.

**Comment by bvaughn** [comment]
I think the rough logic flow for this could be something like?

1. Is the first param a string? If so, does it contain the substring "%s"? If so, we should bail.
2. If the first param is not a string, we should replace it with a string that has a "%c" for every subsequent param.
3. If the first param is a string, we should prepare "%s" and append "%c" for every subsequent param.

**Comment by billyjanitsch** [comment]
@bvaughn I've done something similar in https://github.com/facebook/react/pull/24306, not sure if you had a chance to look at that. I'm a bit confused by your proposal, though. If I'm understanding you correctly:

>Is the first param a string? If so, does it contain the substring "%s"? If so, we should bail.

Do you mean something like: `['A %s', 'B']`? If so, I don't understand why we'd bail in this case. We can transform this to `['%cA %s', 'color: grey', 'B']`.

>If the first param is not a string, we should replace it with a string that has a "%c" for every subsequent param.

Can you clarify how you're suggesting we'd transform `[1, 'A']`?

>If the first param is a string, we should prepend "%s" and append "%c" for every subsequent param.

Can you clarify how you're suggesting we'd transform `['A', 1]`?

**Comment by bvaughn** [comment]
Ooops. Haven't looked at the PR yet, sorry, but just realized I accidentally swapped my "%c" and "%s" args above.

**Comment by bvaughn** [comment]
>> If the first param is not a string, we should replace it with a string that has a "%c" for every subsequent param.
>
> Can you clarify how you're suggesting we'd transform [1, 'A']?
```js
// [1, 'A']
console.log("%c%s %s", "color: gray", 1, "A");
```

>> If the first param is a string, we should prepend "%s" and append "%c" for every subsequent param.
>
> Can you clarify how you're suggesting we'd transform ['A', 1]?
```js
// ['A', 1]
console.log("%cA %s", "color: gray;", 1);
```

**Comment by gaearon** [comment]
Seems like an accidental close? The bug is there.

**Comment by bvaughn** [comment]
😱 TIL about `%o` – yes, that makes good sense to use that flag instead then.

**Comment by db-murphy** [comment]
> 

nice

**Comment by lunaruan** [comment]
@billyjanitsch Are you still working on this PR? If not, I can take it over (giving you credit of course!)

**Comment by billyjanitsch** [comment]
>If not, I can take it over 

@lunaruan that sounds great, thanks! Sorry I didn't wrap up the work, caught a cold over the weekend. 🙂
