### ISSUE TITLE
Bug: Module '"react"' has no exported member 'useTransition'.

### ISSUE THREAD

**Issue by savager** [facebook/react#24305]
![image](https://user-images.githubusercontent.com/1455337/162352774-45639eeb-e968-4016-828d-77c7f5e483c1.png)

React version: 18.0.0 also happened in 18.0.0rc3

## Steps To Reproduce

1. No changes were made and build failed. Tried upgrading from 18.0.0-rc3 to 18.0.0

**Comment by gaearon** [comment]
Try updating `@types/react` to 18.0.0.

**Comment by savager** [comment]
Well, that's embarassing.

**Comment by savager** [comment]
Silly late night mistake.

**Comment by gaearon** [comment]
No problem! (they were just published a few hours ago)
