### ISSUE TITLE
Bug: useEffect is not getting triggered from an outside component's redux dispatch action

### ISSUE THREAD

**Issue by umuralpay** [facebook/react#24337]
React version: 18.0.0-rc.3

```
  const product = useSelector(state => state.selectProduct);
 useEffect(() => {

    console.log("called at rendering but not if product state is updated from another component");
  }, [product]);
```

## The current behavior

My application was working quite fine on version 17, the redux state changes are reflected if that state item is added to useEffect dependency list.

## The expected behavior

useEffect should be listening to redux state changes

**Comment by rickhanlonii** [comment]
@umuralpay this is likely to be an issue with your Redux version, but if you're using the version compatible with React 18, please file an issue with Redux with a full reproduction.
