### ISSUE TITLE
Bug: TS7016: Could not find a declaration file for module 'react-dom/client'

### ISSUE THREAD

**Issue by folt** [facebook/react#24345]
After updating react, I started getting messages in the logs

`ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

I followed the instructions and copied the following code to my project
```
// After
import { createRoot } from 'react-dom/client';
const container = document.getElementById('app');
const root = createRoot(container);
root.render(<App tab="home" />);
```

However, I am getting an error.
`TS7016: Could not find a declaration file for module 'react-dom/client'. '........./node_modules/react-dom/client.js' implicitly has an 'any' type. If the 'react-dom' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom'`

React version:

```
  "dependencies": {
    "@reduxjs/toolkit": "^1.8.1",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.1",
    "@types/node": "^16.11.26",
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.15",
    "antd": "^4.19.5",
    "axios": "^0.26.1",
    "query-string": "^7.1.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-redux": "^7.2.8",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.0",
    "redux": "^4.1.2",
    "redux-saga": "^1.1.3",
    "redux-thunk": "^2.4.1",
    "typescript": "^4.6.3",
    "web-vitals": "^2.1.4"
  },

```

**Comment by gaearon** [comment]
The issue is here:

```
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.15",
```

You need to update the types to 18 too.

See also:

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions

**Comment by Rishabh071296** [comment]
Could not find a declaration file for module 'react-router-dom' 
Please help

**Comment by ItxClip** [comment]
> Could not find a declaration file for module 'react-router-dom' Please help

try this in the terminal:
npm i --save-dev @types/react-router-dom

**Comment by joycenamuli** [comment]
I  am facing this issue when upgrading to v18.
```Module not found: Error: Can't resolve 'react-dom/client'```

I have updated types too, deleted nodemodules but still not fixed

    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    
    "@types/react": "^18.2.28",
    "@types/react-dom": "^18.2.13",

**Comment by hrutik7** [comment]
> I am facing this issue when upgrading to v18. `Module not found: Error: Can't resolve 'react-dom/client'`
> 
> I have updated types too, deleted nodemodules but still not fixed
> 
> ```
> "react": "^18.2.0",
> "react-dom": "^18.2.0",
> 
> "@types/react": "^18.2.28",
> "@types/react-dom": "^18.2.13",
> ```
hey any luck ?
