### ISSUE TITLE
Compatible issue about createRoot between 17 & 18

### ISSUE THREAD

**Issue by zombieJ** [facebook/react#24347]
Hi,
Our component lib [Ant Design](https://ant.design/components/modal/#components-modal-demo-confirm) modal component provides static function to simplify developer code logic. It use `ReactDOM.render` for tmp content render and destroy when modal closed.

For React 18, we want to use `createRoot` to avoid render warning:

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

But `createRoot` comes from `react-dom/client` module which not exist in prev version which will throw warning by webpack.

And use `createRoot` from `react-dom` will also throw warning to tell to import from `react-dom/client`.

Seems no way to hide the realize detail to the upper user.

**Comment by nihgwu** [comment]
I think you can use `ReactDOM.version` to decide which api to use

**Comment by zombieJ** [comment]
> I think you can use `ReactDOM.version` to decide which api to use

We've already done this. But webpack will warning `react-dom/client` not exist even we do not use this by version detect.

**Comment by gaearon** [comment]
This seems similar to https://github.com/chakra-ui/chakra-ui/issues/5795.

We don’t recommend an API where the library creates an extra root under the hood. Instead, portals are preferred.

**Comment by zombieJ** [comment]
> This seems similar to [chakra-ui/chakra-ui#5795](https://github.com/chakra-ui/chakra-ui/issues/5795).
> 
> We don’t recommend an API where the library creates an extra root under the hood. Instead, portals are preferred.

Static function like `Modal.confirm` is not React way but really useful before hooks come. Since we can not do break change in a major version. Please reconsider this. Thx.

**Comment by nihgwu** [comment]
@zombieJ not recommended but I believe [this](https://github.com/facebook/react/blob/main/packages/react-dom/client.js#L30) could be used to suppress warning in dev env if you import `createRoot` from `react-dom` directly

**Comment by rickhanlonii** [comment]
The recommendation in this case is to release a new major that depends on React 18.
