### ISSUE TITLE
Bug: JSON.stringify React touched element TypeError

### ISSUE THREAD

**Issue by huhaixiao** [facebook/react#24360]
React version:

17.0.2

## Steps To Reproduce

1. create a plain object 
```js
const foo = { bar: document.querySelector('body') }

JSON.stringify(foo) // works fine
```
2. but if bar references to an element that is created by React or the React root element
```js
const App = () => {
const ref = useRef()

useEffect(()=>{
  const foo = { bar: ref.current }
  JSON.stringify(foo) // fails, and get a TypeError
  }, [])
  
  return <div ref={ref}></div>
}
```
3. TypeError detail
```
Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property '__reactFiber$x44x6dkvqx' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
```

Link to code example:

https://codesandbox.io/s/demo-react-forked-zxnwvk

## The current behavior

Seems `JSON.stringify` fails on React touched elements

## The expected behavior

No breaking error on handling React touched elements

**Comment by huhaixiao** [comment]
Cause of bug found

with `console.dir(ReactCreatedElement)`, get a object with two deletable properties

```js
const reactCreatedElementDirectory = {
 __reactFiber$qr6bijpnym: deepFiberObject,
 __reactProps$qr6bijpnym: deepPropsObject,
...rest
}
```

if `__reactFiber$qr6bijpnym` property is deleted, `JSON.stringify` will be working again.

with error shown

let's say `$0 `is the HtmlElement created by React.

We have `$0.__reactFiber$qr6bijpnym.stateNode === $0` always true, here comes the loop.

**Comment by huhaixiao** [comment]
Suggestion

override the toJSON function on __reactFiber$qr6bijpnym seems ok, or just
```js
// Also works, not sure if reasonable
HTMLElement.prototype.toJSON = () => ''
```

**Comment by huhaixiao** [comment]
> Suggestion
> 
> override the toJSON function on __reactFiber$qr6bijpnym seems ok, or just
> 
> ```js
> // Also works, not sure if reasonable
> HTMLElement.prototype.toJSON = () => ''
> ```

Q: Why this happened to me? Is JSer supposed to stringify HTMLElement?

A: I dont do `JSON.stringify({ bar: HTMLElement})` myself, but the library I'm using is doing so, and that I cannot change, and more importantly JSON.stringify Native HTMLElement works fine and does not throw breaking error.

What's more

1. The bug above also causes the error of cross origin, which I believe is correct.
2. I am not sure this is supposed to be classed as bug, looking for answers & solutions ASAP.
3. Many thanks to the great React developer.

**Comment by ljharb** [comment]
@gaearon is there a reason react can't provide a `.toJSON` method on react elements that explicitly skips all react's internal info (including circular things)? That would solve it for the whole ecosystem instead of forcing everything to individually account for it.

**Comment by Distortedlogic** [comment]
bump

**Comment by gurkohli** [comment]
bump

**Comment by seanheinrichs** [comment]
bump

**Comment by isaacebhodaghe** [comment]
bump

**Comment by isaacebhodaghe** [comment]
bump
