### ISSUE TITLE
React 18 does have support with Material UI Data-Grid & Data-Grid-Generator?

### ISSUE THREAD

**Issue by fahadashiq12** [facebook/react#24375]
Hi team React, I am wondering some feature of compatibility of React 17 are not being able to integrate in version 18, when it will be fixed Looking forward to your response?

**Comment by eps1lon** [comment]
You should [file an issue against mui/mui-x](https://github.com/mui/mui-x/issues/new/choose) from which these packages are released.

**Comment by fahadashiq12** [comment]
Okay Thanks!
