### ISSUE TITLE
[DevTools Bug] Cannot add child "foo" to parent "bar" because parent node was not found in the Store.

### ISSUE THREAD

**Issue by abybaddi009** [facebook/react#24370]
### Website or app

https://github.com/abybaddi009/react-bug-report

### Repro steps

Steps to reproduce:

1. Install all dependencies
2. Run the project with `npm start`
3. Navigate to http://localhost:3000/login
4. Enter any number into _phone number_ and click on **GET OTP**.
5. Enter any number into the text boxes and click on **SIGN IN**.
6. Allow access to location.
7. Check the Dev Tools for the error

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.24.3-46a98cff2

### Error message (automated)

Cannot add child "986" to parent "985" because parent node was not found in the Store.

### Error call stack (automated)

```text
emit@moz-extension://33a37ecb-24c1-4ab5-9400-2d8a276f2472/build/main.js:24430:22
bridge_Bridge/this._wallUnlisten<@moz-extension://33a37ecb-24c1-4ab5-9400-2d8a276f2472/build/main.js:24599:14
listener@moz-extension://33a37ecb-24c1-4ab5-9400-2d8a276f2472/build/main.js:54423:41
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add child  to parent  because parent node was not found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by lunaruan** [comment]
Hey! I tried your repro steps but was unable to reproduce the error.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2735514/163431525-d680f6c5-0a25-450b-aec5-dcb5cf5b5f1f.png">

This could be because you have duplicate DevTools installations. Could you check how many React Component tabs show up in your chrome developer panel?

**Comment by abybaddi009** [comment]
Hey @lunaruan,

I am using Firefox 99.0.1 x64 on Windows 10 with only one installation of the React Dev Tools (v4.24.3).
I created another repository with react 17.0.2 and react-leaflet 3.2.5 and the error is not appearing anymore.
Apparently the react-leaflet doesn't support React 18 yet.

We can close this issue.

Regards,
Abhishek Baddi
