### ISSUE TITLE
Bug: React18 createRoot multiple rendered

### ISSUE THREAD

**Issue by Orivoir** [facebook/react#24380]
React version: 18.0.0

Root Component `App.tsx`

```ts
import React from 'react';
import theme from './theme';
import {ThemeProvider} from '@mui/material/styles';

interface AppProps {

}

const App: React.FC<AppProps> = () => {

  console.log("is load");

  return (
    <ThemeProvider theme={theme}>
      <>
        Hello world!
      </>
    </ThemeProvider>
  );
}

export default App;
```

config webpack:
```js
const path = require('path');

module.exports = {
  entry: "./src/index.tsx",
  output: {
    filename: "bundle.js",
    path: path.join(__dirname, "./dist")
  },

  resolve: {
    extensions: [
      ".ts", ".tsx", ".js", ".jsx", ".json"
    ]
  },

  devtool: "eval",

  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: "babel-loader",
        exclude: /node_modules/
      },
      {
        test: /\.css/,
        use: [
          "style-loader",
          "css-loader"
        ]
      }
    ]
  }
}
```
I've try render root component from `index.tsx` with:
```tsx
import * as React from 'react';
import {render} from 'react-dom';

import App from './App'
import "normalize.css";

render(
  <App />,
  document.querySelector("main")
);
```

I've get error at browser console:

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

Also i've read [switch-to-createroot](https://reactjs.org/link/switch-to-createroot) and i've try render root component with:

```ts
import * as React from 'react';
import {createRoot} from 'react-dom/client';

import App from './App'

import "normalize.css";

const container = document.querySelector("main");
const root = createRoot(container!);

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
 This work but in my browser console for my `App.tsx` component now i get two times log `is load`
and if i add local state at component and update state render are duplicate.

By going back to the old way of rendering the root component, the problem of multiple renders is solved, but I keep the error message.
How fix it?

Browser Microsoft Edge:
`Version 100.0.1185.39 (Official build) (64-bit)`

package.json:
```json
{
  "name": "assets",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build:prod": "webpack --config ./webpack.config.js --mode production",
    "build:dev": "webpack --config ./webpack.config.js --mode development --watch"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/preset-react": "^7.16.7",
    "@babel/preset-typescript": "^7.16.7",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@mui/icons-material": "^5.6.1",
    "@mui/material": "^5.6.1",
    "@types/react": "^18.0.5",
    "@types/react-dom": "^18.0.0",
    "babel-loader": "^8.2.4",
    "css-loader": "^6.7.1",
    "normalize.css": "^8.0.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "style-loader": "^3.3.1",
    "webpack": "^5.72.0",
    "webpack-cli": "^4.9.2"
  }
}

```

**Comment by iDerekLi** [comment]
I had the same problem.

This is React v17.
![G_AN%H@_103 E)3Z2A)U1~F](https://user-images.githubusercontent.com/24502299/165890369-400b321c-385a-436a-998f-cc50c894fbfe.png)
![@X38~0E1MCCF%USBO}BO@}E](https://user-images.githubusercontent.com/24502299/165890373-823b03e0-e8e6-41e9-944d-2788c0f78b04.png)
![~(8B3_9{5HV}V6TN0_X%EOH](https://user-images.githubusercontent.com/24502299/165890357-f2759d6b-a3b3-4595-b450-b294837513f8.png)

This is React v18.
![EDHD83Q9_LY%P_SA~79J$(R](https://user-images.githubusercontent.com/24502299/165890423-2a593310-39a2-4c0d-8f59-7c7dbee924f4.png)
![RNN)IX 5AI$V4SG~U)SJMPF](https://user-images.githubusercontent.com/24502299/165890429-192ce3d1-b441-4a3c-945a-a890263ad484.png)
![K@72 CHW}3XYZHBE)DS{ 0D](https://user-images.githubusercontent.com/24502299/165890434-fc40b2b1-d018-44c7-a5db-49c96e29ce9c.png)

React v18 double rendered.

**Comment by gaearon** [comment]
There is no problem here. Strict Mode intentionally double-renders your components in development to help find mistakes in them. React 17 was suppressing the second log which made things confusing. React 18 doesn't suppress the logs.
