### ISSUE TITLE
Bug: Error using setInterval in React18

### ISSUE THREAD

**Issue by SnowBDRy** [facebook/react#24383]
React version:18

## Steps To Reproduce

1. use setInterval() in componentDidMount

```
export default class Demo extends Component {

    state = { count: 0 }

    componentDidMount () {
        this.timer = setInterval(() => {
            this.setState(state => ({ count: state.count + 1 }))
        }, 1000)
    }

    render () {
        return (
            <div>
                <h2>SUM:{this.state.count}</h2>
            </div>
        )
    }
}
```

## The current behavior
SUM:0
SUM:2
SUM:4
...

## The expected behavior
SUM:0
SUM:1
SUM:2
...

**Comment by Omar-Trigui** [comment]
I think you should disable the strict Mode in your index.js

**Comment by SnowBDRy** [comment]
> I think you should disable the strict Mode in your index.js

However, the use of StrictMode in react is recommended, so this should not be the best solution😁

**Comment by vkurchatkin** [comment]
> I think you should disable the strict Mode in your index.js

Not really. What you should do is implement `componentWillUnmount` method where you call `clearInterval`

**Comment by gaearon** [comment]
>I think you should disable the strict Mode in your index.js

Quite the opposite, this is an example of Strict Mode catching an actual bug in the component.

Here's how to fix it:

```js
export default class Demo extends Component {

    state = { count: 0 }

    componentDidMount () {
        this.timer = setInterval(() => {
            this.setState(state => ({ count: state.count + 1 }))
        }, 1000)
    }

    componentWillUnmount () {
        clearInterval(this.timer)
    } 

    render () {
        return (
            <div>
                <h2>SUM:{this.state.count}</h2>
            </div>
        )
    }
}
```
