### ISSUE TITLE
Bug: `useId()` not consistent between server and client

### ISSUE THREAD

**Issue by brillout** [facebook/react#24386]
Problem: the value returned by the `useId()` hook is different between client and server.

```jsx
import React, { useState, useId } from 'react'

export { Counter }

function Counter() {
  // `id` stays the same when clicking on the counter button, as expected.
  // `id` is different between client and server, which is unexpected. 
  const id = useId()
  console.log('id: '+id)
  const [count, setCount] = useState(0)
  return (
    <button type="button" onClick={() => setCount((count) => count + 1)}>
      {id} Counter {count}
    </button>
  )
}

```

Context: I'm trying to use `useId()` to map SSR data between server and client during a SSR Suspense Stream. (The reproduction doesn't use a stream, but it's the same issue.)

React version: `18.0.0`

## Steps To Reproduce

Reproduction with Vite + vite-plugin-ssr:

Online demo: https://stackblitz.com/edit/github-3qdjks?file=pages%2Findex%2FCounter.jsx. (Couldn't make it work with CodeSandbox.)

Repository: https://github.com/brillout/react-use-id-bug.

Observe the `console.log()`. Or observe how the ID changes upon hydration.

## The current behavior

`useId()` should return the same id.

## The expected behavior

`useId()` returns a different id.

**Comment by gaearon** [comment]
You're calling `createRoot` rather than `hydrateRoot`, so there is no hydration.

Here is a fixed version:

https://stackblitz.com/edit/github-3qdjks-bfxhjg?file=renderer%2F_default.page.client.jsx

**Comment by aini10000** [comment]
你好，我将尽快给你回复。
