### ISSUE TITLE
Bug: The forwardRef has disabled the defaulProps property of the function component

### ISSUE THREAD

**Issue by QMSFish** [facebook/react#24382]
The function component does not have a ref instance and forwardRef can add a ref instance to the function component but after wrapping with forwardRef the defaulProps property setting of the function component fails

React version: 17.0.2

1.
import XYTextArea from 'XYTextArea.jsx'
const XYTextAreaNew = forwardRef((props, myRef) => XYTextArea(props, myRef))

2.
/* -------  file:  XYTextArea.jsx ------------*/
const XYTextArea = function(props) {
   console.log(props)  //  The printed props does not contain the settings properties in the defaultProps
    return (
      <>......</>
    )
}

XYTextArea.defaulProps = {
   name:  "react".
   textId: '132441421'  
}

export default XYTextArea

**Comment by hamlim** [comment]
You're calling the `XYTextArea` component as a function here:

```tsx
const XYTextAreaNew = forwardRef((props, myRef) => XYTextArea(props, myRef))
//                                                 ^^^^^^^^^^
```
Which will bypass the logic that React uses to apply defaultProps. Instead if you call createElement with it / use it within JSX, then React should apply the default props for you:

```tsx
const XYTextAreaNew = forwardRef((props, myRef) =>
  <XYTextArea {...props} /* pass ref here too */ />
))
```
