### ISSUE TITLE
Bug: Can't type Korean when using input with useTransition.

### ISSUE THREAD

**Issue by ginger-kang** [facebook/react#24398]
Korean is broken if i use `useTransition` together in controlled mode.
[docs example](https://ko.reactjs.org/docs/concurrent-mode-patterns.html#splitting-high-and-low-priority-state) If you look at this, it looks like a general use case, but if it doesn't work, it seems to be a bug.

I checked that Japanese is not working in the same way, and it is probably not possible for Chinese as well.
If I use `useDeferredValue`, it works without problems.

React version: "^18.0.0"

repro: [codesandbox](https://codesandbox.io/s/intelligent-agnesi-ljuv63?file=/src/App.js)

<img width="755" alt="image" src="https://user-images.githubusercontent.com/62840502/164001890-5d67ee8c-a2bc-42b3-a7b5-1ebfaeeef18a.png">

I expected the above result, but it comes out as below.

**Comment by gaearon** [comment]
You can’t use transitions for updating a controlled input’s value. Controlled updates should be synchronous. So if you use a transition, you need two separate pieces of state, like in the docs examples.

**Comment by ginger-kang** [comment]
Thanks. I missed [this discussion](https://github.com/reactwg/react-18/discussions/100).
