### ISSUE TITLE
Bug: react-dom@18.0.0 renders dialog with open attribute

### ISSUE THREAD

**Issue by dfernandez79** [facebook/react#24399]
The HTML `<dialog>` element is rendered with the `open` attribute, preventing the use of the `showModal` API.

React version: 18.0.0
React DOM version: 18.0.0

## Steps To Reproduce

1. Render a `<dialog>` component and assign a `ref` to it.
2. In an effect call `showModal` to display a modal dialog.

The browser (tested on Chrome and Firefox) will throw an `InvalidStateError` because you can't call `showModal` with a `dialog` that already defines the `open` attribute. Error message:

```
InvalidStateError
Failed to execute 'showModal' on 'HTMLDialogElement': The element already has an 'open' attribute, and therefore cannot be opened modally.
```

This problem doesn't happen in React/React DOM v17.x.

Link to code example (React v18 - fails): https://codesandbox.io/s/dialog-bug-v18-bnbz93
Link to code example  (React v17 - works): https://codesandbox.io/s/dialog-bug-v17-2ip3or

## The current behavior

React dom renders `<dialog open>`.

## The expected behavior

React dom should render `<dialog>`(unless the dev specifies the `open` attribute)

**Comment by samline** [comment]
For now I fixed it by removing the [open] attribute on first load, it seems a bit dirty to me, but it's only temporary.

`import { useEffect, useRef } from 'react'

export const Dialog = () => {
  const dialog = useRef(null)

  useEffect(() => {
    dialog.current.removeAttribute('open')
    dialog.current.showModal()
  }, [])

  return <dialog ref={dialog}>:3</dialog>
}`

**Comment by samline** [comment]
For now I fixed it by removing the [open] attribute on first load, it seems a bit dirty to me, but it's only temporary.

```js
import { useEffect, useRef } from 'react'

export const Dialog = () => {
  const dialog = useRef(null)

  useEffect(() => {
    dialog.current.removeAttribute('open')
    dialog.current.showModal()
  }, [])

  return <dialog ref={dialog}>:3</dialog>
}

**Comment by dfernandez79** [comment]
@gaearon Thanks for looking into the issue! I was aware of the new strict behavior but I didn't know that `showModal` is not idempotent... so I got bite by it.

**Comment by ericclemmons** [comment]
TIL!  I just started using https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog and this thread was super helpful (and already showed up on Google :)

I did notice that the error (for me) happened with `useEffect(...)` and `useEffect(..., [])`, but _not_ with explicit dependencies:

```js
  React.useEffect(
    function toggleContextMenu() {
      if (state === State.SELECT && contextMenuElement) {
        contextMenuElement.showModal()
      }
    },
    [contextMenuElement, state]
  )
```

**Comment by gaearon** [comment]
> I did notice that the error (for me) happened with useEffect(...) and useEffect(..., []), but not with explicit dependencies:

This code example seems potentially buggy to me because if you’re putting DOM element itself in dependencies, it must mean that you are reading `ref.current` earlier during render. This makes the code non-deterministic because render result and effects depend on the exact moment the render runs. Render shouldn’t read mutable values (including ref.current) to avoid timing bugs and other issues.
