### ISSUE TITLE
useEffect running before DOM is painted *without* useLayoutEffect

### ISSUE THREAD

**Issue by B3nten** [facebook/react#24409]
### Came across strange behavior while building a simple modal with a fade-in CSS animation.

Component's default state is to render null.

When component is mounted, `useEffect(()=>setMounted(true),[])` should trigger a re-render. My understanding is that effects run after the DOM is painted, so the component should now exist in the dom with opacity = 0. Now `useEffect(()=>mounted && setIsOpen(true),[mounted])` should run which sets isOpen(true). This  should trigger a re-render with a new opacity value, and thus a transition.

Instead it seems like useEffect runs before the dom is painted, so the node is first rendered with opacity = 1. Thus no transition.

React version: 18.0.0

### Link to code example:

https://codesandbox.io/s/adoring-yonath-8hr3pj?file=/src/App.js

Every so often the modal transitions as expected, so clearly it *can* work. And if setIsOpen(true) is called in a setTimeout with a delay of 1ms, it's almost 50/50 on transitioning or not. 20ms delay has it transitioning almost 100% of the time.

### Considerations

https://github.com/facebook/react/issues/20863 seems to have a similar problem.

Also, other libraries like react-animate-mount seem to handle this explicitly with requestAnimationFrame: https://github.com/MingruiZhang/react-animate-mount/blob/32300c04a4fdfa97724b70aaaf0c0f403d6da247/src/Animate.js#L172

**Comment by rravithejareddy** [comment]
Yes UseEffect will run after DOM painted, but you kept condition mounted? for return that's why it's calling after UseEffect.

**Comment by rravithejareddy** [comment]
Since you have kept condition for return, first time it's not loading. That's the reason it's not working as expected.

**Comment by gaearon** [comment]
Previously, useEffect would *sometimes* flush synchronously but it was inconsistent. In React 18, it always flushes synchronously if the effect is caused by an intentional user event like click, typing, and so on. So this works as intended.

`useEffect` is generally used for non-visual things that can either be delayed or right away. If you need to do something with transitions, rAF might be a good idea.
