### ISSUE TITLE
Merge className when using spread operator

### ISSUE THREAD

**Issue by smussell** [facebook/react#2440]
When using transferPropsTo the className property would be merged, this is not true when using the new spread operator.  This was one of the nicest features in transferPropsTo, it made extending existing components much easier.  I created a couple of fiddles to illustrate:

0.12:
http://jsfiddle.net/kb3gN/7005/

0.11.2:
http://jsfiddle.net/qjohd7ut/

I'm not sure if this would be considered a bug, I can understand there would be reasons not to do it, but it is incredibly convenient.  If this is not possible it would be nice to have some utility method or something to do className merging, maybe as part of add-ons.

**Comment by teophilus** [comment]
You can also try: `className={`custom-class ${className}`}`
