### ISSUE TITLE
React diffing broken when mixing margin and marginTop 

### ISSUE THREAD

**Issue by johnryan** [facebook/react#24403]
React version: 16/17/18

## Steps To Reproduce

1. Apply an inline style with both `margin` and `marginTop`
2. Observe that `margin` overrides `marginTop`
3. Unset `margin` 
4. Observe that `marginTop` is never applied

Link to code example:

https://codesandbox.io/s/unruffled-wind-c0k8q4?file=/src/App.js

## The current behavior

`marginTop`/ `marginBottom` is never applied

## The expected behavior

Once `margin` is removed `marginTop`/ `marginBottom` is rendered

**Comment by gaearon** [comment]
This is not supported. If you open the console after toggling you will see an error:

> Removing a style property during rerender (margin) when a conflicting property is set (marginBottom) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.

**Comment by johnryan** [comment]
Ah thanks - codebase is still on v16 so missed this warning.
