### ISSUE TITLE
Bug: useEffect(() =>{},[]) in React18，execute twice

### ISSUE THREAD

**Issue by maohui66661** [facebook/react#24416]
width React18,the callback of useEffect is executed twice,when the dependency array is empty.but width react17.0.2 ,execute once.

React version:18.0.0

## Steps To Reproduce
React18 demo:[https://codesandbox.io/s/happy-leakey-nc6d6u](url)
![image](https://user-images.githubusercontent.com/7902405/164422489-1ed3a53f-3769-4eab-8bca-df42153f2ee2.png)

React17 demo: [https://codesandbox.io/s/aged-dust-bnlrp2](url)
![image](https://user-images.githubusercontent.com/7902405/164423553-9adbc3c7-822c-4991-a9dd-a730138513fc.png)
)

**Comment by JE-lee** [comment]
I have same problem in 18.0.0

**Comment by gx0408** [comment]
I had same problem in 18.0.0

**Comment by edvinerikson** [comment]
I think it is expected behaviour in dev mode when using strict mode. Can you confirm if it executes twice in production mode too?

**Comment by kanogithub** [comment]
I have some issues, and it was running normally in production mode.

**Comment by gaearon** [comment]
This is expected development-only behavior in Strict Mode.

We are planning to add a feature to React that would let you reuse state between component unmounts. To verify your components are resilient to this feature, in development we mount them, immediately unmount, and then mount again while reusing state and the DOM.

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

**Comment by gaearon** [comment]
We wrote a new page documenting this in detail on the Beta website.

https://beta.reactjs.org/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development

Hope this is helpful. Sorry some links from there are 404 because other pages are still being written.
