### ISSUE TITLE
Bug: why v17.0.2 react version is 17.0.0

### ISSUE THREAD

**Issue by 2239559319** [facebook/react#24415]
[version](https://github.com/facebook/react/blob/v17.0.2/packages/react/package.json#L7)
React version:

why react version in tag v17.0.2 is 17.0.0, Which commit is the source code of version 17.0.2 react

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by eps1lon** [comment]
Duplicate of  https://github.com/facebook/react/issues/24079
