### ISSUE TITLE
Bug: Exception using both input and useState

### ISSUE THREAD

**Issue by yh4922** [facebook/react#24414]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-4-20-0-alpha-1-forked-s7gyfc?file=/demo.js:16-24)

### Steps to reproduce

Use `const [val, setVal] = useState("");` to bind the input value After calling the `setVal` method in the `onChange` callback, the `val` value cannot be obtained by printing the latest value
The value obtained is the last modified value

### What is expected?

Expect to get the latest `val` after `setVal()`

### What is actually happening?

But you can only get the value of the previous modification

| Environment | Info |
| --- | --- |
| React | 18.0.0 |
| System | win10 21H2 19044.1526 |
| Browser | Google Chrome 100.0.4896.88 |

**Comment by khareyash05** [comment]
i would like to work on this one @yh4922

**Comment by yh4922** [comment]
@khareyash05 I have the codesandbox minimal reproduction code above

**Comment by webcarrot** [comment]
It's expected behavior.
https://github.com/reactjs/rfcs/pull/201

**Comment by eps1lon** [comment]
This is expected behavior that's currently not explicitly documented. However, the beta docs have a dedicated section for this behavior:

> Calling the set function [does not change the current state in the already executing code](https://beta.reactjs.org/apis/usestate#ive-updated-the-state-but-logging-gives-me-the-old-value): [...]

-- https://beta.reactjs.org/apis/usestate#adding-state-to-a-component
