### ISSUE TITLE
Bug: ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by artola** [facebook/react#24420]
React version: 18

## Steps To Reproduce

1. Execute in NodeJS the following script:

  ```js
  require.resolve('react/umd/react.production.min.js');
  ```

This happens for React and the same for ReactDOM.

## The current behavior

```text
  Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './umd/react.production.min.js' is not defined by "exports" in /[redacted folders]/node_modules/react/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:731:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

## The expected behavior

If the `umd` artifacts are properly declared in `exports` they should lead to resolve the absolute of them.

**NOTE**: This was properly working before the upgrade to v18.

## Solution

Add to `exports` the artifacts with a wilcard (easier than list all of them):

```
"exports": {
  "./cjs/*": "./cjs/*",
  "./umd/*": "./umd/*"
}
```

**Comment by gaearon** [comment]
It is not supported to directly import UMD bundles. Moreover, we will likely remove the UMD bundles in a future major release in favor of ESM ones. Why do you need this?

**Comment by artola** [comment]
> It is not supported to directly import UMD bundles. Moreover, we will likely remove the UMD bundles in a future major release in favor of ESM ones. Why do you need this?

We use the UMD versions because of AMD. If the package provides UMD/AMD then we just copy over, when it does not we must bundle it as AMD.

Until v18 it was not a problem, just adding them to the `exports` would keep working for us.

We just deprecated **ie 11** a week ago ... surely in the future we can consider to consume ESM directly.

**Comment by gaearon** [comment]
What do you do with the path after you require.resolve it? Do you load it in the Node environment? Do you bundle it?

**Comment by artola** [comment]
> What do you do with the path after you require.resolve it? Do you load it in the Node environment? Do you bundle it?

I use some `webpack` with plugins (e.g., copy, manifest) to create a list of externals that will be available in the AMD environment. Artifacts that are ready for use (AMD/UMD and minified) I just need to hash by content and check that we have also any required dependency.

Mainly I have a config, where `require.resolve` is used to find the absolute path of the dependency within the monorepo.

Before:

```
{
  name: 'react',
  from: require.resolve('react/umd/react.production.min.js'),
}
```

Workaround:

```
{
  name: 'react',
  from: require
    .resolve('react')
    .replace('/index.js', '/umd/react.production.min.js'),
}
```

**Comment by bobsilverberg** [comment]
I am experiencing a similar problem, where I am trying to replace the module in development with the unminified version. In my `webpack.dev.config.babel.js` I have:

```
    new webpack.NormalModuleReplacementPlugin(
      /^react$/,
      'react/umd/react.development.js',
    ),
    new webpack.NormalModuleReplacementPlugin(
      /^react-dom$/,
      'react-dom/umd/react-dom.development.js',
    ),
```

which worked in React 17, but doesn't work with React 18. Is there a different way to accomplish this without having those files exported?

**Comment by ippy1997** [comment]
> "./cjs/*": "./cjs/*",
>   "./umd/*": "./umd/*"

im having this issue where the cjs and umd files are not being exported even tho i added , 
```
 "./cjs/*": "./cjs/*",
 "./umd/*": "./umd/*"
```

in the exports

**Comment by artola** [comment]
@ippy1997 I do not know why your require has no extension (see above: `Error: Cannot find module '/home/g/cars/node_modules/react/cjs/react.production.min'`) but you can add the extension in your `react/package.json` and it will work:

```text
    "./cjs/*": "./cjs/*.js",
    "./umd/*": "./umd/*.js"

```

**Comment by 3rdManRun** [comment]
This also throws from [rollup-plugin-react-refresh](https://github.com/PepsRyuu/rollup-plugin-react-refresh/blob/0a91d20c3d6788c04c18106db3c25fe56d4a0810/index.js#L3)

```js
let runtime = fs.readFileSync(require.resolve('react-refresh/cjs/react-refresh-runtime.development.js'), 'utf8');
```
Definitely adding a ./cjs/* conditional entry would fix this
