### ISSUE TITLE
Bug: destroy is not function

### ISSUE THREAD

**Issue by pignax** [facebook/react#24423]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by gaearon** [comment]
We can’t help without a reproducing case. But what’s happening likely is that you’re returning something that’s not a function from your useEffect.

**Comment by pignax** [comment]
@[gaearon](https://github.com/gaearon) had upgraded the project to React 18

**Comment by eps1lon** [comment]
@pignax  You probably returned something from `useEffect` that was neither a function nor undefined. You can't return anything else e.g. `useEffect(() => null)` would produce such an error. But it also contains an additional warning listing the allowed return types:
> Warning: useEffect must not return anything besides a function, which is used for clean-up. You returned null. If your effect does not require clean up, return undefined (or nothing).

**Comment by avshyz** [comment]
Hi @gaearon, I've also encountered this bug after upgrading to React 18

Here's a reproducible example
See here https://codesandbox.io/s/react-router-nesting-forked-lxtdw5?file=/example.js
The following code runs without an error in react 17, but crush in react 18

**Comment by agconti** [comment]
@avshyz The problem in that demo is that you're returning a promise in the useEffect hook, not a function.
