### ISSUE TITLE
Bug: useEffect Error

### ISSUE THREAD

**Issue by SKrind0** [facebook/react#24429]
React version: 18.0.0

## Steps To Reproduce

1.When I put useEffect and add the empty array it is executed 2 times, in the previous version that was v17.0.2 it did not happen

Link to code example:
https://codesandbox.io/s/useeffect-error-react-v-18-t75zf4?file=/src/App.js

## The current behavior
because it is running 2 times

## The expected behavior
so it runs only once

**Comment by bentongxyz** [comment]
Seems to be related to #24431

**Comment by bentongxyz** [comment]
Seems to be related to #24431

**Comment by eps1lon** [comment]
This is expected behavior that got introduced in React 18: https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

**Comment by SKrind0** [comment]
thanks for the answer it's already solved
