### ISSUE TITLE
[DevTools Bug]: forwardRef components not marked as "rendered" if context changed

### ISSUE THREAD

**Issue by eps1lon** [facebook/react#24428]
### Website or app

https://codesandbox.io/s/forwardref-context-change-did-not-render-lpdk4t?file=/src/index.js

### Repro steps

1. Goto https://lpdk4t.csb.app/
1. Start profiling
3. Enter "a" into the input
4. Stop profiling
![forwardRef-did-not-render](https://user-images.githubusercontent.com/12292047/164915101-f28f305a-2c51-4b89-8515-da073e5551c9.png)

### How often does this bug happen?

Every time

### DevTools version (automated)

4.24.3-46a98cff2

**Comment by JayKaku** [comment]
Hey, I tried the steps you mentioned with the same version of Dev Tools and it works for me (image attached) on Chrome (Version 100.0.4896.127 (Official Build) (64-bit)), could you also mention the browser and its version along with your operating system and version.

![image](https://user-images.githubusercontent.com/61429929/164946919-f9714fa5-3061-4349-aa11-b7fe158cfb71.png)

**Comment by eps1lon** [comment]
I linked the wrong codesandbox. Let me update it. If you wrap ValueReader in forwardRef you should be able to reproduce

**Comment by eps1lon** [comment]
@JayKaku Updated codesandbox. https://lpdk4t.csb.app/ should reproduce
