### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ly01112020** [facebook/react#24424]
React version: 17.0.0

React.Fragment Why not  dangerouslySetInnerHTML property

**Comment by bvaughn** [comment]
The [`dangerouslySetInnerHTML` property](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) is something the React DOM renderer supports, specifically for the DOM elements it creates. It's not a general React pattern, and it's not supported by environment-agnostic component types like `Fragment`.

The `dangerouslySetInnerHTML` prop tells React what to set an elements `innerHTML` value to, meaning that it doesn't make sense to combine with the `children` prop (so it really wouldn't make sense to use on a `Fragment` anyway).
