### ISSUE TITLE
Bug: Checked attribute does not update in the dom

### ISSUE THREAD

**Issue by stefanylaforest** [facebook/react#24439]
React version:

## Steps To Reproduce

1. Go to React's [code pen example ](https://codepen.io/gaearon/pen/wgedvV?editors=0010) you can find the link in the documentation [here](https://reactjs.org/docs/forms.html#handling-multiple-inputs)
2. Inspect " is going " checkbox element
3. uncheck the checkbox 

<img width="1565" alt="Screen Shot 2022-04-25 at 4 39 52 PM" src="https://user-images.githubusercontent.com/66086002/165171075-5b090a7b-6ee9-471a-a81b-e8834de9b4d3.png">

Link to code example: https://codepen.io/gaearon/pen/wgedvV?editors=0010

## The current behavior
dom does not update, the checked attribute stays no matter what. 
same goes if the initial state is set to false, the checked attribute never appears on the input element.

## The expected behavior

The checked attribute should be removed if not checked.

**Comment by gaearon** [comment]
The current behavior is correct.

The confusion stems from the browser reporting the _attribute_ values. However, React sets the checked _property_ on the DOM node. Setting a property is the correct way to update something — attributes are primarily meant to reflect the initial HTML that was loaded in the browser.

React does update attribute in some cases, notably for inputs `value`. However, this has led to a large number of problems, and we're actually planning to switch it back to only update the property.

So the behavior for the `checked` property is better.

**Comment by eps1lon** [comment]
For CSS selectors you'd want to use [`:checked`](https://developer.mozilla.org/en-US/docs/Web/CSS/:checked) since `[checked]` wouldn't work for uncontrolled components with plain HTML anyway.

**Comment by dkilgore-eightfold** [comment]
Isn't this an Accessibility issue? It's impacting a project I'm working on and am curious if there's a recommended work-around to update this attribute?
