### ISSUE TITLE
Bug: React 18 + useEffect cleanup runs immediately after render

### ISSUE THREAD

**Issue by tianhuil** [facebook/react#24431]
React version: 19

## Steps To Reproduce

Here is a bare-bones react app with one `useEffect`: https://github.com/tianhuil/use-effect-demo/

In [this one](https://github.com/tianhuil/use-effect-demo/commit/b899bb6dad00607b694ab9835b0f2d1868dbf069), we log the cleanup side effect to console in v18, which you can verify by running `pnpm dev` and inspecting the console.

In [the next commit](https://github.com/tianhuil/use-effect-demo/commit/05581986018fb7ec396d8e7c0ee0a4f4c0a594fc) we do the same thing in v17, which does not print the same log statement in the console.

## Impact
This is pretty important.  The cleanup function is used for unsubscribing from listeners and DB subscriptions.  This behavior kills those listeners and subscriptions before the first fetch completes!

## The current behavior
I expect v18 `useEffect` cleanup runs immediately (not at unmount)

## The expected behavior
I expect v18 to behave as v17.

**Comment by vkurchatkin** [comment]
In React 18 effects runs effects twice in strict mode (i.e. effect -> cleanup -> effect), so this is totally expected

**Comment by eps1lon** [comment]
As was mentioned, this is expected behavior that got introduced in React 18: https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

**Comment by tianhuil** [comment]
Thanks @vkurchatkin, @eps1lon

**Comment by gaearon** [comment]
We wrote a new page documenting this in detail on the Beta website.

https://beta.reactjs.org/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development

Hope this is helpful. Sorry some links from there are 404 because other pages are still being written.

**Comment by ShadiEagleGenomics** [comment]
Hi everyone, I'm really confused about react 18 update on cleanup. Here is 2 examples below:

https://codesandbox.io/s/react-17-forked-wvbxb6
https://codesandbox.io/s/react-17-forked-n8sgt9

The code is identical, except new `react-dom ` `root.render ` binding, but the problem is that I'm not quite sure that I understand the flow of `useEffect` now. I've tried to play with `flushSync` and removal of `StrictMode`, but I didn't achieve the expected behaviour.
