### ISSUE TITLE
[DevTools Bug]: Type '{}' is not assignable to type 'ReactNode'

### ISSUE THREAD

**Issue by lucasaugustscode** [facebook/react#24432]
### Website or app

https://github.com/devnautas/happy-app

### Repro steps

Creating a custom component with styled-components

![image](https://user-images.githubusercontent.com/71651661/165000428-8eded19a-8a61-4078-8ec7-da6c98f54b75.png)

### How often does this bug happen?

Every time

### DevTools version (automated)

dwdw

### Error message (automated)

Type '{}' is not assignable to type 'ReactNode'.

**Comment by eps1lon** [comment]
You probably have multiple versions of `@types/react` installed. See https://github.com/facebook/react/issues/24304#issuecomment-1094565891 for more information on how to fix this.

If this doesn't help, please [open a new issue in the DefinitelyTyped/DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/new?category=issues-with-a-types-package) which hosts the types.
