### ISSUE TITLE
Bug: Reconsider of #24439 with checked attribute update

### ISSUE THREAD

**Issue by zombieJ** [facebook/react#24450]
As #24439
Since `enzyme` not support React 18 and we use `testing lib` instead. The `jest` `toMatchSnapshot` on `testing lib` only possible to compare html instead of node props compare. Which means when replace `enzyme` with `testing lib`, the snapshot will always be wrong on re-render.
`toMatchSnapshot` will not preset current state is hard to figure out only when developer find it not work as expect.

**Comment by eps1lon** [comment]
In this case you would want to implement a custom snapshot serializer that uses properties instead. In any case, it's not an issue with React but your testing strategy.
