### ISSUE TITLE
Bug: v18 - How to deal with useEffect being called twice in Strict Mode?

### ISSUE THREAD

**Issue by enoh-barbu** [facebook/react#24455]
Runnig this code will execute twice the API call

```
import { useEffect } from "react";
import axios from "axios";

export default function App() {
  useEffect(() => {
    axios.get("https://gorest.co.in/public/v2/users").then(({ data }) => {
      console.log(data);
    });
  }, []);

  return <div className="App"></div>;
}

```

Is there any workaround for preventing this behaviour while still keeping the `<StrictMode />` on?

**Comment by gaearon** [comment]
Usually you’d want to have some kind of cleanup for your effect. It should either cancel your fetch or make sure you ignore its result by setting a variable inside your effect. Once you do this, there should be no actual difference in behavior.

If you cancel your fetch in effect cleanup, only one request will complete in development. However, it also doesn’t matter if another request fires. It’s being ignored anyway, and the stress-testing only happens in development.

In general we recommend to fetch data with some sort of a backing cache so that requests between multiple components can be reused / deduplicated / cached. If you use a solution like this then you won’t see a second request either.

Hope this helps!

**Comment by enoh-barbu** [comment]
I do have a cleanup for my effect, but I still see my request in a canceled state in dev tools, so if I fire many more APIs on page load (from different components), I get twice the number of requests, making dev tools cluttered, half of them being canceled.

I understand the fetch won't hit the BE, and this is impactic only dev mode in strict mode, but this makes harder to debug on dev tools (looking at my requests)

**Comment by gaearon** [comment]
If this is causing a lot of trouble, I would suggest to either disable strict mode or to use a data fetching method that deduplicates requests. (It shouldn’t be hard to do that with axios, either.)

**Comment by enoh-barbu** [comment]
I can try something with interceptors, thanks for help thought. I guess this behaviour won't be changed in the upcoming major releases.

**Comment by gaearon** [comment]
There is no plan to change it. The behavior is described here: https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

**Comment by enoh-barbu** [comment]
Oh, that's nice !Looking good! I'll definitely check it once I'll plan to update to v18. For now ,I just downgraded to v17. Thanks for the effort.

**Comment by gaearon** [comment]
>For now ,I just downgraded to v17

Why? If there is a problem, you can just remove Strict Mode from your app. The new behavior is only on in Strict Mode. (We do, however, recommend to keep it on.)

**Comment by enoh-barbu** [comment]
Yes I know, we'll keep StrictMode on. 
For now we do not have time to address the "issues" of `useEffect` double call (and maybe other changes related to v18), as these might introduce bugs in our application. So the he plan is to update back to v18 at later moment.

**Comment by enoh-barbu** [comment]
That's a good suggestion, indeed. Thanks for your help & time.

**Comment by Slapbox** [comment]
So if we want to ignore something on the initial run, what's the suggested way to do that now? For example, this `useEffect` fires twice in `React.StrictMode`, and I see no good way around it besides mucking up the code with `if (__DEV__) ... else ...`

```js
  const isInitialRender = useRef(true);
  const [currentTabValue, setActiveTab] = useState(initialSelectedValue);

  useEffect(() => {
    // Prevent running on first render, because it wrongly calls onTabChanged and toggles the state to the inverse of the correct state
    if (isInitialRender.current === true) {
      isInitialRender.current = false;
      return;
    }

    onTabChanged(currentTabValue);
  }, [currentTabValue, onTabChanged]);
  
 ```
 
I see no good way around this. But how useful could `StrictMode` be if running into a minor issue like this has no good workaround besides disabling strict checks entirely?

I saw [this comment](https://github.com/facebook/react/issues/24502#issuecomment-1118867879), and it's all well and good for promises, but how can something even simpler than promises be harder to implement?

To quote another user in that thread:

> What worries me is the fact that development mode most people will run (StrictMode is there in CRA) is getting further from production mode. So area for making subtle errors that disappear as soon as you start troubleshooting is increasing.

How are developers to avoid this problem? How can we add `StrictMode` without paying more than its benefits in terms of time? I wonder what exactly `StrictMode` is saving me from that's worth this pain, as it certainly seems to carry its own danger in using it, as it _requires_ divergence between DEV and PROD.
