### ISSUE TITLE
Bug: Page renders twice when use "ReactDOM.createRoot" in the index.tsx in React 18

### ISSUE THREAD

**Issue by voiceu-zuixin** [facebook/react#24467]
React version:18.1.0

## Steps To Reproduce

1. create-react-app test-render --template typescript
2. go to  src/App.tsx write useEffect( ) in the function before return, such as "console.log('app') " in the callback
3. npm run start
4. checkout the console, you will find this function runs two times
5. if I use the React 17 ,there will be only once print

Link to code example:
https://github.com/voiceu-zuixin/react18-test-render

## The current behavior

![image](https://user-images.githubusercontent.com/77840482/165945523-d206aa39-9a09-4a75-8827-c399892ea0e4.png)

## The expected behavior
![image](https://user-images.githubusercontent.com/77840482/165945482-4c956b6f-7f88-4fae-8188-5836d7cee08a.png)

**Comment by hamlim** [comment]
This is expected behavior in React 18 with StrictMode (and will only happen in dev), you can read more about the change to StrictMode here: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

**Comment by voiceu-zuixin** [comment]
![image](https://user-images.githubusercontent.com/77840482/166140246-c0f0237d-6b5b-48a0-a71d-a0ca772c1ea6.png)

thanks，here is another qusetion, the componentDidMount is not in the list , but when I test class component, it also runs two times, Is it missing or I wrong

**Comment by voiceu-zuixin** [comment]
> This is expected behavior in React 18 with StrictMode (and will only happen in dev), you can read more about the change to StrictMode here: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

![image](https://user-images.githubusercontent.com/77840482/166140449-4fd0b33b-e659-491a-96db-57df6cdf96b7.png)

thanks，here is another qusetion, the componentDidMount is not in the list , but when I test class component, it also runs two times, Is it missing or I wrong, however the componentDidUpdate only invok once

`
import React, { Component } from 'react'

let number_outside = 1

export default class TestClass extends Component {
  constructor() {
    super()
    console.log('constructor', number_outside)
    this.state = {
      param: {
        name: '',
        num: 10
      }
    }
  }

  componentDidMount() {
    this.setState({ param: { num: this.state.param.num + 1 } })
    console.log('didMount', number_outside, this.state.param.num)
  }
  
  onClick = () => {
    this.setState({ param: { name: '22' } })
  }

  componentDidUpdate() {
    console.log('didUpdate', number_outside,this.state.param.num)
  }

  render() {
    number_outside += 1
    console.log('Test', number_outside)

    return <div onClick={this.onClick}>test-class</div>
  }
}
`
componentDidMount runs twice ,but change the state once, and the componentDidUpdate runs once

![image](https://user-images.githubusercontent.com/77840482/166140579-e9a81f80-35ac-4d30-bba4-35da0bf16b6d.png)

**Comment by eps1lon** [comment]
@voiceu-zuixin Mind the link to the upgrade guide not StrictMode:

> This new check will automatically unmount and remount every component, whenever a component mounts for the first time, restoring the previous state on the second mount.
-- https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

Though I agree that we should also add this to the StrictMode docs.

**Comment by eps1lon** [comment]
@voiceu-zuixin StrictMode docs already mention this implicitly:

> This new check will automatically unmount and remount every component
 
-- https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state

But we can explicitly list what APIs are included in this to help discoverability (e.g. by using STRG+F "componentDidMount"). Opened https://github.com/reactjs/reactjs.org/pull/4618 for that.

**Comment by GFGill** [comment]
Is there a chance that the page double rendering bug could happen without strict mode?
We are seeing double api calls with React 18 but do not seem to have strict mode enabled.

**Comment by StGrSt** [comment]
> Is there a chance that the page double rendering bug could happen without strict mode? We are seeing double api calls with React 18 but do not seem to have strict mode enabled.

I had a similar issue with disabled Strictmode. In my case the rerendering happened, because in a specific function, i was not using `event.preventDefault()`. Adding this line stopped the double rendering.
