### ISSUE TITLE
Bug: Chrome devtools does not shows the warnings, only the vscode terminal

### ISSUE THREAD

**Issue by tarrga** [facebook/react#24461]
Hi!

So, for example when I create some state, like const [name, setName] = useState(''), and If I don't use it in the component, then the chrome devtools should this log on the console, but it does not show up the message like 'Line 14:17:  'name' is assigned a value but never used'.  It shows up only in the terminal in vscode. How can I enable these warnings in chrome devtools?

**Comment by romadryud** [comment]
Hi @tarrga , this warning are showed by eslint, so if you want to see this warning/errors in devtools you need to figure out how to setup showing eslint errors in browser. So it's not related to React and propose to close the issue.
