### ISSUE TITLE
Bug: Differences between "cjs/react.production.min.js" file and "umd/react.production.min.js": "Scheduler" property is missing in object "React. __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED" in "cjs/react.production.min.js"

### ISSUE THREAD

**Issue by zhuchuji** [facebook/react#24466]
The production file inside "cjs/react.production.min.js" does not contain the code of assigning "Scheduler" to the object "React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED", which lost the "Scheduler" property. But inside "umd/react.production.min.js" file, such codes exist and the "Scheduler" property is assigned correctly. Can anyone explain whye and how to make such differences between "cjs" production file and "umd" production file?

React version: v16.14.0 ~ v18.1

## Steps To Reproduce

1. Install react: `npm install react`.
2. Inspect into "node_modules/react/cjs/react.production.min.js", we can not use the "Scheduler" property in "React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED".

## The current behavior
There are no "Scheduler" property in object "React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED".

## The expected behavior

**Comment by zhuchuji** [comment]
We do not use access "Scheduler" directly. But we got an error "Scheduler" is undefined  when using "umd/react-dom.production.min.js" with "cjs/react.production.min.js". Because we bundle the common "react" package with webpack(which use cjs file), and use the "umd" react-dom.production.min.js for rendering. We know it's incorrect, but just want to figure out why the cjs file and umd file are different.

**Comment by hamlim** [comment]
I'll let one of the maintainers speak to the difference there, but I don't think this is a supported setup. Could you also bundle react-dom or alternatively treat react the same way you treat react-dom?

**Comment by zhuchuji** [comment]
Yes, we resolve the problem by bundling react-dom(rebuild a lot of module and projects). If we could know the difference between cjs and umd production package, we could avoid the issue before running into mistakes. Many thanks for explanations from maintainers, and also for your reply.

**Comment by zhuchuji** [comment]
Hi. I found the explanation in source code about the differences on "React.Scheduler" between cjs package and umd package. It tells that cjs package use the shared "Scheduler" package while the umd package can't do it in this way therefore re-export the "Scheduler" and add it to React prototype. Below is the related lines:
![image](https://user-images.githubusercontent.com/12730487/166861869-7a00fb31-62bc-4af7-b77b-3c70d3a824f7.png)

**Comment by Perce1** [comment]
Bro, do not use or you will be fired

**Comment by Perce1** [comment]
nigga wants to be fired

**Comment by rickhanlonii** [comment]
Yeah this setup isn't supported unfortunately.
