### ISSUE TITLE
Bug: BrowserRouter does not work in new render function

### ISSUE THREAD

**Issue by NKolva** [facebook/react#24472]
React version: 18.1.0

## Steps To Reproduce

1. Install react-router-dom (v. 5.3.0);
2. In root index.tsx(jsx) file, wrap App with BrowserRouter
3. Implement routes in your application
4. Try navigate via pages

## You can try it in my current project:
https://github.com/NKolva/react-ts-starter-kit/tree/bug/react-18.1.0-browser-router

## IMPORTANT - BUG CONTAINS IN THIS BRANCH react-18.1.0-browser-router

BrowserRouter implemented in src/index.tsx
Switch implemented in src/app/PublicRoutes.tsx
PublicRoutes imported in src/app/App.tsx

## If i`m doing this: 
```
import ReactDOM from 'react-dom/client';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);

root.render(
  <React.StrictMode>
    <Provider store={rootStore}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </Provider>
  </React.StrictMode>,
);
```

RESULT: We cannot navigate in aplication

## If I`m going to previous usage of render: 
```
import ReactDOM from 'react-dom';

ReactDOM.render(
  <React.StrictMode>
    <Provider store={rootStore}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </Provider>
  </React.StrictMode>,
  document.getElementById('root'),
);
```

RESULT: BrowserRouter works correctly, i can navigate via all pages which implemented.

**Comment by incepter** [comment]
At first sight, i suspected on of the following (or both) - since you are using `root.render`-:

- The used `react-router-dom` version isn't `concurrent-feautures-compatible`
- `StrictMode` being more strict.


Then I suggest the following:

- Update `react-router-dom` to latest version
- Try toggling StrictMode
- Put the issue in `react-router`'s repo if none of the above works.

**Comment by gaearon** [comment]
Yes, you'd need to either upgrade `react-router-dom` to the latest version or temporarily remove StrictMode until you can upgrade `react-router-dom`.

**Comment by NKolva** [comment]
Thank You!

**Comment by Sachin737** [comment]
> react-router-dom

Thanks. Updating react-router-dom works!!
