### ISSUE TITLE
Ad hoc data fetching with Suspense

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react#24504]
.@aaronabramov suggested that I file an issue for this: https://twitter.com/dan_abramov/status/1522207779984793601

---

👋 I have a question about React 18 + Suspense. From the [docs](https://reactjs.org/blog/2022/03/29/react-v18.html):

> Ad hoc data fetching with Suspense is technically possible, but still not recommended as a general strategy.

When can I find more information about how to do this?

The reason I ask is because at [Unsplash](https://twitter.com/unsplash) we have basically created our own routing / data fetching framework after running into too many limitations with existing solutions—so we'll need to figure out how to incorporate Suspense into our data fetching framework.

The best example I've found so far is [this talk](https://www.youtube.com/watch?t=1438&v=SCQgE4mTnjU&feature=youtu.be) by [Jared Palmer](https://twitter.com/jaredpalmer) but I suspect it's outdated now?

**Comment by OliverJAsh** [comment]
No, once the data has been fetched, we never attempt to fetch it again.

**Comment by rajington** [comment]
Maybe there are open source frameworks that are on the right path? Or is data fetching in v18 itself still not ready for primetime? (also get if it's a tough question to answer and still early).

- swr experimentally supported suspense in v17 but [v18 seems in progress](https://github.com/vercel/swr/issues/1898)
- [urql](https://github.com/FormidableLabs/urql/discussions/2235) and [react-query](https://github.com/tannerlinsley/react-query/issues/3453) seem to have some v18 fixes
- apollo is [also working on it](https://github.com/apollographql/apollo-client/issues/9627)

I could do a codesandbox with all the different suspense implementations in v18, but I'm not sure if I'm familiar enough to test other than a single data fetch.
