### ISSUE TITLE
Default bolean prop named "show or visible"

### ISSUE THREAD

**Issue by ShafiqueMalik** [facebook/react#24518]
Hi reactjs Team, I suggest that, team should add a new prop for every component that purly used to show or hide component conditionally.
i.e
Instead of writing code like this in JSX.
{show && <Component/>}
we simply use like this <Component show={true}/> and that's it.

**Comment by eps1lon** [comment]
Duplicate of https://github.com/facebook/react/issues/4373. See https://github.com/facebook/react/issues/4373#issuecomment-133485039 for why this is closed.
