### ISSUE TITLE
Bug: How to get the `useUpdateEffect` custom hook work with the new Strict Mode? 

### ISSUE THREAD

**Issue by ssmkhrj** [facebook/react#24527]
React version: v18

## Steps To Reproduce

I came across this `useUpdateEffect` custom hook from a library and this hook runs the passed callback only during updates and _not on mount_ but I was wondering how to get it working with the new `StrictMode` behavior.

```jsx
import { useEffect, useReducer, useRef } from "react";

function useUpdateEffect(callback) {
  const hasMountedRef = useRef(false);

  useEffect(() => {
    if (hasMountedRef.current) {
      return callback();
    } else {
      hasMountedRef.current = true;
    }
  });
}

export default function App() {
  const forceRenderer = useReducer((x) => !x, 0)[1];

  useUpdateEffect(() => {
    console.log("Update effect ran");
  });

  return (
    <div className="App">
      <button onClick={forceRenderer}>Force render</button>
    </div>
  );
}
```

One solution that I found was to create another effect hook with empty dependency array and in it's cleanup set the `hasMountedRef` to `false`.

```jsx
function useUpdateEffect(callback) {
  const hasMountedRef = useRef(false);

  useEffect(() => {
    if (hasMountedRef.current) {
      return callback();
    } else {
      hasMountedRef.current = true;
    }
  });

  useEffect(() => {
    return () => {
      hasMountedRef.current = false;
    };
  }, []);
}
```

Link to codesandbox: https://codesandbox.io/s/react-bug-24527-useupdateeffect-9opiyc?file=/src/App.js

**It works for now, but is it resilient with future updates to React as well?** Because currently it's correctness relies on the fact that both the effects are called the same no. of times. 

**Is it possible that the first effect is called and then somehow the control gets suspended and second effect is not called and when the control comes back React starts with the first effect again, which causes an error?** I'm thinking this because the cleanup is _not_ part of the same effect but a different one.

Another thing that bothers me is that does this hook make any sense at all? Because this hook wants to distinguish between mount & updates but I've heard people mention a couple of times that effects should not be thought like that, so everything should be treated as an update, not sure if I understand this correctly.

**Comment by gaearon** [comment]
I would not recommend to use a Hook like this because the exact behavior you want to achieve depends on *what you use it for*. Can you give a concrete example of how you're using it? Then I could help show how to fix (if it breaks) that specific pattern.

**Comment by ssmkhrj** [comment]
@gaearon This is *not* something I'm using myself, I saw this in a custom hooks library and I noticed it would break with latest Strict Mode behavior.

But let's consider the following use case, so if every the `name` input changes, there's an alert on the screen confirming the change.

```jsx
function App() {
  const [name, setName] = useState("Shekhar");

  useUpdateEffect(() => {
    alert("Name updated");
  });

  return (
    <div className="App">
      <label htmlFor="name">Name: </label>
      <input
        id="name"
        value={name}
        onChange={({ target }) => setName(target.value)}
      />
    </div>
  );
}
```

I know in this case we can simply use the effect hook and check `if (name === "Shekhar")` and early exit the function but what if we wanted to do it using the `useUpdateEffect` hook?

And also did the following part in the question make any sense?
> Is it possible that the first effect is called and then somehow the control gets suspended and second effect is not called and when the control comes back React starts with the first effect again, which causes an error?

I more interested in getting an answer to the above.

**Comment by shallinta** [comment]
any progress?

**Comment by gaearon** [comment]
>what if we wanted to do it using the useUpdateEffect hook because people are definitely using this hook in their codebase?

Our recommendation is to *not* use a Hook like this in their codebase, as I noted earlier. So I can't really respond to that.

>But let's consider the following use case (obtained by doing a google search), so if every the name input changes, there's an alert on the screen confirming the change.

I would suggest to put this code into the event handler instead.

```js
function App() {
  const [name, setName] = useState("Shekhar");

  return (
    <div className="App">
      <label htmlFor="name">Name: </label>
      <input
        id="name"
        value={name}
        onChange={({ target }) => {
          setName(target.value)
          alert("Name updated")
        }}
      />
    </div>
  );
}
```

See here for why it's usually a better idea: https://beta.reactjs.org/learn/you-might-not-need-an-effect#sharing-logic-between-event-handlers. Does this help?

>any progress?

There is no progress possible here. This is not a bug.

**Comment by kelvinkaicheung** [comment]
The point is all useUpdateEffect originally developed in react 17 that worked become not working anymore. useUpdateEffect are commonly developed to trigger some callback after the first render(the second render). If no more useUpdateEffect can be used a lot of use cases become failed and this is definitely causing a lot of problem. The react team should carefully reconsider this use case of useEffect hook

**Comment by reekystive** [comment]
This is working:

```ts
import { useEffect, useRef } from 'react';

const useUpdateEffect: typeof useEffect = (effect, deps?) => {
  const isMounted = useRef(false);
  // add a useEffect here
+ useEffect(() => {
+   isMounted.current = false;
+ }, []);
  useEffect(() => {
    if (!isMounted.current) {
      isMounted.current = true;
    } else {
      return effect();
    }
  }, deps);
};

export { useUpdateEffect };
```
