### ISSUE TITLE
[DevTools Bug]: Component shown twice in flame graph when using React.memo

### ISSUE THREAD

**Issue by MTxx87** [facebook/react#24538]
### Website or app

I cannot provide. Private.

### Versions

- React Developer Tools 4.24.3 (3/30/2022)
-  "react": "^17.0.2",
- "react-dom": "^17.0.2",

### Repro steps

I am using react-devtools to profile my app.
When a component is wrapped in React.memo and a custom comparison function is provided, that component shows up twice in the Flamegraph. 
I tried with different components in the app and the behaviour is always the same. 
I tried with both the chrome extension and the stand-alone npm package.

Shows only one instance in Flamegraph:
`export default React.memo(SurfacesSelector)`

Shows up twice in Flamegraph:
`export default React.memo(SurfacesSelector, customShallowEqual)`

OR

```
export default React.memo(SurfacesSelector, (prevProps: SurfacesSelectorProps, nextProps: SurfacesSelectorProps) => {
      if (deepEqual(prevProps.enabledSurfaces, nextProps.enabledSurfaces)) {
      return false;
    }
    if (deepEqual(prevProps.surfaces, nextProps.surfaces)) {
      return false;
    }
    return shallowEqual(prevProps, nextProps);
})
```

See the following screenshots for the result.
![Screen Shot 2022-05-11 at 10 35 11](https://user-images.githubusercontent.com/12138301/167808653-32c04c1f-eec5-44d0-ba03-6cc1be26547b.jpg)
![Screen Shot 2022-05-11 at 10 34 56](https://user-images.githubusercontent.com/12138301/167808672-98dbd9c1-2e27-4dc7-a9a1-b0d2e063410a.jpg)

### How often does this bug happen?

Every time

**Comment by ryndh** [comment]
Also seeing this issue. Same version as above (4.24.3)

**Comment by lunaruan** [comment]
Hey! I'm not exactly sure what you mean by "first instance" vs "second instance", but I can give you a bit more context on this that might answer your question

For component using `React.memo` without a custom compare function (ex. `React.memo(SurfacesSelector)`), we will do a shallow comparison of props and rerender `SurfacesSelector` only if the props have changed.

On the other hand, for components using `React.memo` that have a custom compare function (ex. `React.memo(SurfacesSelector, fn)`, we use the custom compare function to determine whether the props have changed instead. It seems like your custom comparison function returns `false` if the new props don't deep equal the old props.

This is mostly likely why, in your case, `React.memo(ListItem, fn)` rendered 7 times while `React.memo(ListItem)` only rendered 4 times.

**Comment by MTxx87** [comment]
Hey @lunaruan, 
thanks for your answer.
It is still not clear though.

I can try clarify with an image perhaps.
The screenshot below shows the `SurfacesSelector` component incorrectly displayed twice in the flamegraph even though only one `<SurfacesSelector />` is used in the code.
This happens when using a custom function in React.memo (eg. `React.memo(SurfacesSelector, reactFastCompare)`) and it is due to the bug described by @mondaychen.

![167808672-98dbd9c1-2e27-4dc7-a9a1-b0d2e063410a](https://user-images.githubusercontent.com/12138301/170114483-71eca2aa-23a3-46c3-8734-3c791a26455b.jpeg)

Now, you can see how in the flamegraph the two `SurfacesSelector` rows have different number of re-renders.
I was wondering which one (4 times / 7 times) is the actual number of re-renders of the `SurfaceSelector` component in my app.

It is actually crucial to understand this, because when trying to optimise for number of re-renders, I don't know if I am going in the right direction or not.

 I hope this is more clear and I am not missing something obvious.

**Comment by lunaruan** [comment]
Ah, I see what you are asking. The actual re-renders of the `SurfaceSelector` would be 7 in your case.

`React.memo` rerenders if the props passed to SurfaceSelector changes. However, just because the props don't change doesn't mean that SurfaceSelector won't rerender (ex. as a result of a state update). Let me know if that clarifies things!

**Comment by MTxx87** [comment]
It is very clear now thanks!
