### ISSUE TITLE
Bug: Creating a lazy component in a hook causes infinite loop

### ISSUE THREAD

**Issue by wjmao88** [facebook/react#24534]
React version: 18.1.0 to 18.2.0.next (latest available on code sandbox)

## Steps To Reproduce

1. Have a component create a lazy component in a hook (useState/useMemo), 
2. Render the lazy component
3. Infinite loop

Link to code example:
[code sandbox](https://codesandbox.io/s/ecstatic-brook-gndvji?file=/src/App.jsx)

this works
```jsx
const _lc = lazy(() => import("./SomeComp"))

export default function App() {
  const [LazyComp] = useState(_lc);
  return <LazyComp />;
}
```
this will infinite loop
```jsx
export default function App() {
  const [LazyComp] = useState(lazy(() => import("./SomeComp")));
  return <LazyComp />;
}
```
and so will this (this is the actual use case I'm dealing with)
```jsx
export default function App() {
  const LazyComp = useMemo(() => lazy(() => import("./SomeComp")), []);
  return <LazyComp />;
}
```
It seems rendering a lazy component resets the hook somehow.

**Comment by vkurchatkin** [comment]
> It seems rendering a lazy component resets the hook somehow.

It does and it is completely expected. Lazy components suspend on first render, which means that all of the parent component state (including memo, etc) is thrown out.

That's why you need an external cache for Suspense when using it for data fetching and your case is basically the same.

**Comment by wjmao88** [comment]
Thanks @vkurchatkin. Is there documentation/explanation somewhere? I went looking for it after seeing your comment and can't find any.
