### ISSUE TITLE
<input type="range" orient="vertical" /> doesn't work

### ISSUE THREAD

**Issue by MoOx** [facebook/react#2453]
According to this issue https://bugzilla.mozilla.org/show_bug.cgi?id=840820 it seems to be the way to handle vertical input range (on firefox for now). I've tried to add `orient` attribute, but this one seems to be ignored by react :/

Is it complicated to handle it ? Are you open to a PR ?

**Comment by spicyj** [comment]
Closing until it's in the standard.
