### ISSUE TITLE
[DevTools Bug]: console.log crashes when I enable DevTools on Chrome

### ISSUE THREAD

**Issue by coolwind0202** [facebook/react#24543]
### Website or app

https://github.com/coolwind0202/web/blob/23877f77e23837a007aada5be363d65290571c88/web/src/components/page/members/IndexPage/IndexPage.tsx#L27

### Repro steps

For checking whenever my project will work correctly, when I run a command `next dev`, errors which are shown below occurred.

![image](https://user-images.githubusercontent.com/51913600/168043187-bf77a943-39c4-45d3-9a1d-2cdf97c904df.png)

When I pass a first argument which is an **object** to `console.log()`, `console.error()`, `console.warn()`, I can repro the errors.
for example, 
```
console.log([]);
console.error({});
```

Before a few days, the errors had never occured.
When I disable DevTools, the errors calm down.

I think, the errors may be caused by the codes which are shown below.
https://github.com/facebook/react/blob/7d9e17a9826595dacbf9e19e8f85b07837adf276/packages/react-devtools-shared/src/backend/utils.js#L193

### How often does this bug happen?

Every time

**Comment by valerii15298** [comment]
The same error happens in my case. Basically I cant use `console.log` becasue it shows the same error. I think it is a bug. Extension was updated just yesterday.

**Comment by thomaszee** [comment]
Experiencing the same issue while having the React Developer Tools extension enabled. Disabling the extension prevents the error from occurring.

**Comment by gaearon** [comment]
This is a bug. We’ll be releasing a fix asap.

**Comment by kyrylolvov** [comment]
Hey! I have a similar issue. I can use console log for printing string, but putting any functionality or variables causes the error

**Comment by mondaychen** [comment]
Hey! Thanks for reporting this bug and sorry for the inconvenience!

**If you are experiencing this issue, a temporary solution is to make sure your first argument to console.log is a string.**

```
// This will error
console.log({foo: 'bar'});

// Change to this
console.log('', {foo: 'bar'})
```

For now, I've unpublished the extension on the Chrome Web Store to prevent people from installing the buggy version. We've submitted a new version with the bugfix to the Chrome Web Store, and the extension will come back online once the review process is done.

Firefox and Microsoft Edge has not been affected, and an extension without this bug is still available for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/) and [Edge](https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil).

**Comment by kyrylolvov** [comment]
> Hey! Thanks for reporting this bug and sorry for the inconvenience!
> 
> **If you are experiencing this issue, a temporary solution is to make sure your first argument to console.log is a string.**
> 
> ```
> // This will error
> console.log({foo: 'bar'});
> 
> // Change to this
> console.log('', {foo: 'bar'})
> ```
> 
> For now, I've unpublished the extension on the Chrome Web Store to prevent people from installing the buggy version. We've submitted a new version with the bugfix to the Chrome Web Store, and the extension will come back online once the review process is done.
> 
> Firefox and Microsoft Edge has not been affected, and an extension without this bug is still available for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/) and [Edge](https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil).

Thank you so much!

**Comment by mondaychen** [comment]
A new version with the bug fix is on Chrome Web Store now: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
