### ISSUE TITLE
Bug: Component returning string causes hydration mismatch

### ISSUE THREAD

**Issue by subhero24** [facebook/react#24567]
I have a component like this:

```javascript
function Component() {
    let string = useSuspendingHook()

    return string
}
```

On the server I render the component with renderToPipeableStream. When hydrating the component I get a `Hydration failed because the initial UI does not match what was rendered on the server.`.

What makes me think this is a bug in react  and not my code, is that everything works when I wrap the returned string in a `<div>` like so:

```javascript
function Component() {
    let string = useSuspendingHook()

    return <div>{string}</div>
}
```

Also, would it be possible to have some extra info on the error what the mismatch in hydration actually is?

**Comment by ramfattah** [comment]
possibly related to this hydration issue? https://github.com/facebook/react/issues/24578

**Comment by gaearon** [comment]
Can you please create a minimal reproducing case? Thanks.

**Comment by gaearon** [comment]
Just a reminder we'll need a reproducing case. Otherwise I'll close this.

**Comment by subhero24** [comment]
I failed to create a minimal reproducing case where the problem also happens. Have no idea what makes the situation different with the full application. Will close for now.
