### ISSUE TITLE
onSubmit without submit input  not working

### ISSUE THREAD

**Issue by teosz** [facebook/react#2457]
I can't handle native submit with onSubmit 
( https://www.youtube.com/watch?v=U2a3V2XcIcY&feature=youtu.be )

---

React v0.12.0

**Comment by bORm** [comment]
<form ref="form" onSubmit={(e)=>{ // this event not fired if submit form on click button if button not in form }}></form>

<button onClick={e=>{ReactDOM.findDOMNode(this.refs.form).submit()}}>Submit form</button>

**Comment by selvagsz** [comment]
@bORm Ideally, browsers do not fire the `onsubmit` event when the form's `submit()` method is called (http://jsbin.com/coluxo/1/edit?html,js,console,output). You can move the onsubmit handler to a method in the component & call it.

**Comment by bORm** [comment]
@selvagsz any idea how submit form from outside & subscribe it inside form?
