### ISSUE TITLE
Bug: absent error message in eslint while using hooks in callbacks

### ISSUE THREAD

**Issue by gulevskii** [facebook/react#24572]
When i'm using react hook inside iteration (first example), i'm getting an error message: 
`React Hook "useCustomHook" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.eslint[react-hooks/rules-of-hooks](https://reactjs.org/docs/hooks-rules.html)
.` 
But when i'm using react hook like in second example i haven't got any errors. The code works in the same way, it's seems that it should be an error message in both examples

React version: 17.0.2

## Steps To Reproduce

First example: `[].map(params => useCustomHook(params))` - with error message
Second example: `[].map(useCustomHook)` - absent error message

**Comment by Aksh-a1** [comment]
In the first example you tried to **call/execute** the hook inside a callback and react rightly pointed out the error.
In the second example you **did not call/execute** the hook but instead **passed its value** to be used by `.map()` function so react doesn't complain there.

You can also check the `eslint` rule file: https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L513

**Comment by eps1lon** [comment]
Thanks for the report.

This is indeed a false-negative of the lint rule. But this is already tracked in https://github.com/facebook/react/issues/22254.
