### ISSUE TITLE
Bug: componentDidCatch hook does not exist

### ISSUE THREAD

**Issue by reverofevil** [facebook/react#24595]
React version: latest

## Steps To Reproduce

1. Install latest version of React.
2. Hook for error boundaries is [still not there](https://reactjs.org/docs/hooks-faq.html#do-hooks-cover-all-use-cases-for-classes) since 2019.

Link to code example: https://preactjs.com/guide/v10/hooks/#useerrorboundary

## The current behavior
There is no hook for error boundaries.

## The expected behavior
There is hook for error boundaries.

**Comment by im6** [comment]
the fact that some hooks exist in preact.js but not exist in react.js should not category as bug, isn't it?

**Comment by polkovnikov-ph** [comment]
@im6 You're welcome to press "new issue" and find a category that would fit this issue better.

**Comment by Cobertos** [comment]
Some discussion of this in https://github.com/facebook/react/issues/14347

**Comment by skopz356** [comment]
I think that this feature should be implemented. Because class components are deprecated.

**Comment by Cobertos** [comment]
Bump, this still feels like a core unaddressed use case

**Comment by reverofevil** [comment]
Great, so you're marking issues as stale, then restricting comments to contributors only, then it's closed, and the comments are unrestricted.

Somehow it feels like we've been duped here.
