### ISSUE TITLE
[DevTools Bug]: "Reload and profile" aways disabled on Timeline tab

### ISSUE THREAD

**Issue by gaearon** [facebook/react#24603]
### Website or app

beta.reactjs.org (local development)

### Repro steps

1. https://github.com/reactjs/reactjs.org/tree/main/beta
2. `yarn dev`

"Reload and profile" is enabled for Flamegraph:

<img width="724" alt="Screenshot 2022-05-23 at 21 28 07" src="https://user-images.githubusercontent.com/810438/169900687-7c62d7c5-34ad-43c0-b1fa-ca45c8e16dba.png">

But disabled for Timeline:

<img width="671" alt="Screenshot 2022-05-23 at 21 28 12" src="https://user-images.githubusercontent.com/810438/169900693-ba60f1f4-3b37-4141-993a-70bac5647b01.png">

And yet I can "reload and profile" in Flamegraph, then switch to Timeline and it works. So this doesn't add up.

### How often does this bug happen?

Every time

**Comment by gaearon** [comment]
Maybe related, a "reloaded" Timeline profile appears too much shifted to the left and thus a bit borked.

<img width="963" alt="Screenshot 2022-05-23 at 21 31 57" src="https://user-images.githubusercontent.com/810438/169901102-2df13db9-adc7-4851-a708-7d19f0def9f2.png">

**Comment by mondaychen** [comment]
Just wanna confirm, by "borked" you mean some information is covered up? If so, does scrolling and dragging help?

**Comment by gaearon** [comment]
Oh I see, that's just existing behavior. If I zoom in, then it helps, yea. So let's ignore that part.
