### ISSUE TITLE
Bug: `hydrateRoot().render` causes error, even though the #root's HTML from the server coincides the component

### ISSUE THREAD

**Issue by umer4ik** [facebook/react#24610]
From react 18.1 docs: 
> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration.

But when `render()` function is called for the hydrated root, the error occures:
```
This root received an early update, before anything was able hydrate. Switched the entire root to client rendering.
```
Root contains the same HTML as should be rendered by React

React & React DOM version: 18.1.0

## Steps To Reproduce

1. Insert an expected html to the root element imitating the string from a server
2. Render app on a client side

```js
import { StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";
import { renderToString } from "react-dom/server";
const App = () => <h1>Hello</h1>

const rootString = renderToString(<App />);

const rootElement = document.getElementById("root");
rootElement.innerHTML = rootString;
const root = hydrateRoot(rootElement, <App />);

root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
```

Link to code example:

https://codesandbox.io/s/goofy-volhard-of1bmi?file=/src/index.js

## The current behavior

The error means that react renders app twise; this causes unnecessary server requests even if data is already received and inserted to HTML

## The expected behavior

React should add only listeners and shouldn't render it twise

**Comment by umer4ik** [comment]
Same code in React 17.0.2 works as expected https://codesandbox.io/s/interesting-ride-2soxwr?file=/src/index.js

**Comment by gaearon** [comment]
I agree this seems a bit unintuitive. I'd need to check with the team why this happens.

That said — can you clarify what is the purpose of immediately calling `render` after hydrating?

**Comment by gaearon** [comment]
No, hydrating happens here:

```js
hydrateRoot(rootElement, <App />);
```

There is no need for a further `render` call.

**Comment by aminnairi** [comment]
I just got the issue with the following code.

```tsx
import React from "react";
import {MemoryRouter} from "react-router-dom";
import express from "express";
import {renderToString} from "react-dom/server";
import App from "../client/components/app";

const server = express();

server.use(express.static("build/client"));

server.get("*", (request, response) => {
  response.setHeader("Content-Type", "text/html");
  response.send(`<!DOCTYPE html>
    <html lang="en-US">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body>
        <div id="root">
          ${renderToString(<MemoryRouter initialEntries={[request.url]}><App /></MemoryRouter>)}
        </div>
        <script src="./index.js"></script>
      </body>
    </html>
  `);
});

server.listen(8000, "0.0.0.0", () => {
  console.log("http://localhost:8000");
});
```

While this code does not output any hydratation errors (TL;DR, I just put all the static markup in one single ugly line).

```tsx
import React from "react";
import {MemoryRouter} from "react-router-dom";
import express from "express";
import {renderToString} from "react-dom/server";
import App from "../client/components/app";

const server = express();

server.use(express.static("build/client"));

server.get("*", (request, response) => {
  response.setHeader("Content-Type", "text/html");
  response.send(`<!DOCTYPE html><html lang="en-US"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="From zero knowledge to godlike skills in information technology, stop being just a human."><title>From Human To Code</title></head><body><div id="root">${renderToString(<MemoryRouter initialEntries={[request.url]}><App /> </MemoryRouter>)}</div><script src="./index.js"></script></body></html>`);
});

server.listen(8000, "0.0.0.0", () => {
  console.log("http://localhost:8000");
});
```

I'm not sure why having spacing and line-returns make the hydratation wrong but this is what I have in my client index file.

```tsx
import React from "react";
import {BrowserRouter} from "react-router-dom";
import {createRoot, hydrateRoot} from "react-dom/client";
import App from "./components/app";

const rootElement = document.getElementById("root");

if (rootElement !== null) {
  hydrateRoot(
    rootElement,
    <BrowserRouter>
    <App />
  </BrowserRouter>
  );
}
```

Here are my packages.

```json
{
  "scripts": {
    "development": "rollup --config rollup.config.ts --environment NODE_ENV:development --watch",
    "production": "rollup --config rollup.config.ts --environment NODE_ENV:production"
  },
  "devDependencies": {
    "@aminnairi/rollup-plugin-external": "0.1.3",
    "@rollup/plugin-commonjs": "22.0.0",
    "@rollup/plugin-node-resolve": "13.3.0",
    "@rollup/plugin-replace": "4.0.0",
    "@rollup/plugin-run": "2.1.0",
    "@rollup/plugin-typescript": "8.3.3",
    "@types/express": "4.17.13",
    "@types/node": "18.0.0",
    "@types/react": "18.0.14",
    "@types/react-dom": "18.0.5",
    "@types/react-router-dom": "5.3.3",
    "rollup": "2.75.7",
    "rollup-plugin-terser": "7.0.2",
    "tslib": "2.4.0",
    "typescript": "4.7.4"
  },
  "dependencies": {
    "express": "4.18.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-router-dom": "6.3.0"
  }
}
```

**Comment by aminnairi** [comment]
Okay I see thanks for your quick answer, any chance this could be documented out in the official website? Unless I didn't see the mention to that behavior.

**Comment by nestor-diaz** [comment]
👋 I spent a couple of hours figuring out why my app was complaining about mismatches. Thanks to this issue I could determine it was due to new lines. In my case I'm sending this from the server:

```js
const componentHTML = ReactDOM.renderToString(<Root />);

res.send(
  <!DOCTYPE html>
  <html>
    <body class="muleteer">
    <div id="main-view">
      ${componentHTML}
    </div>
    </body>
  </html>
);
```

In the client I'm calling `hydrateRoot`:
```js
ReactDOM.hydrateRoot(document.getElementById('main-view'), <Root />)
```

And this was the warning in the dev console:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/25233189/184645952-b0c7be11-0447-4203-a7b9-114d7199bcb4.png">

It turned out to be the new lines, I changed this:
```js
<div id="main-view">
  ${componentHTML}
</div>
```
to this:
```js
<div id="main-view">${componentHTML}</div>
```

It would be really nice to have a small text in the documentation about this. I know it's a silly error but as there isn't too much feedback, it will save people time if there were a warning in the docs :)

**Comment by MSpiechowicz** [comment]
Why this issue was closed? Turning new lines into one liner is **not** a fix... If you have multiple properties inside one component this is a no go. We have similar issue and yes for one component it can actually resolve it, but we can't do it for all.

**Comment by MSpiechowicz** [comment]
Example workaround for this issue look like this: 

<img width="862" alt="Screenshot 2022-09-07 at 12 49 04" src="https://user-images.githubusercontent.com/16558155/188860571-e2d80236-aaec-4666-a81e-4e8fea6d35ee.png">

It does work for an component that does not have properties but I can't simply imagine doing it for more flexible implementation.

**Comment by gaearon** [comment]
@MSpiechowicz I don't think the issue you're describing (something about types?) is relevant to this issue.

**Comment by MSpiechowicz** [comment]
I am not talking about types but hydration error: "Expected server HTML to contain matching <example-web-component-column-layout> in <main>". This is happening if we will write return statement within couple of lines (as it should be possible).
