### ISSUE TITLE
Bug: react-reconciler with supportsPersistence = true doesn't cloneInstances when props change

### ISSUE THREAD

**Issue by aquark** [facebook/react#24645]
React version: 17.0.2, react-reconciler version 0.26.0

## Steps To Reproduce

1. Create a `HostConfig` with `supportsPersistence = true` and implement all of the core methods and persistence methods.
2. Render a react component whose props change regularly.

## The current behavior

react-renconciler doesn't call `cloneInstance` to update the instance with new props. Instead it calls `prepareUpdate` and `commitUpdate`. This is unexpected because `commitUpdate` is explicitly documented as one of the `supportsMutation` methods, and because of the implication with `supportsPersistence = true` that instances are immutable.

## The expected behavior

When a component's props change, react-reconciler should call `cloneInstance` for that component with the new props, just as it does if the instance's children change.

OR the documentation should be updated to reflect that `commitUpdate` is part of the core methods for `HostConfig` and must be implemented even when `supportsPersistence = true`. Although this does mean that instances must be mutable, which goes against the assumption of a persistent data structure.

**Comment by gaearon** [comment]
Are you sure you don't have `supportsMutation = true` set to `true` as well? A minimal repro would be nice.

At least on `main` the `commitUpdate` flag appears wrapped:

https://github.com/facebook/react/blob/be1fd48e96a617f3758d179ebfb0386a382af942/packages/react-reconciler/src/ReactFiberCommitWork.new.js#L2171-L2203

**Comment by aquark** [comment]
OK, I misunderstood what was happening -- the reconciler does NOT call `commitUpdate`, however if `prepareUpdate` returns `null` then the instance won't be cloned.

The documentation says that you need to implement `commitUpdate` if `prepareUpdate` returns something other than `null`, which isn't true in persistence mode. The documentation should say that in persistence mode, `commitUpdate` simply needs to return non-`null` if the props have changed, and then `cloneInstance` will be called to actually apply the update (but the return value of `commitUpdate` is not passed to `cloneInstance`).

**Comment by lfernandez55** [comment]
I unsubscribed from this repo but am still receiving emails. Please unsubscribe me.

**Comment by gaearon** [comment]
@lfernandez55 we can’t unsubscribe you, it’s your GitHub settings. Please contact GitHub support if you have an issue.
