### ISSUE TITLE
Bug: Losing scroll position in DOM-element after sorting array elements

### ISSUE THREAD

**Issue by reducio** [facebook/react#24640]
**Problem**: After sorting the array elements, the scroll position is lost.

An interesting fact is that the position of those elements that were moved to the end of the array is lost.

**Question**: How not to lose the scroll position when sorting an array of elements? Isn't this a task for React since the component hasn't been re-rendered?

React version: 17.0.2, 18.1.0

## Steps To Reproduce

1. Change the scroll position for each DOM element.
2. Press "btn reverse" button.

Link to code example: https://stackblitz.com/edit/react-d2raex?file=src%2FApp.js

## The current behavior
The first element saves the scroll position.
The second and third elements reset the scroll position.

## The expected behavior
All elements must retain their scroll position.

**Comment by nmain** [comment]
When you remove an element from the DOM, it loses its scroll position.  Also see https://github.com/facebook/react/issues/21675.  The way you've asked React to reconcile here, it must lose the scroll position on something as it's not possible to reorder DOM node children in place without detaching them.

**Comment by reducio** [comment]
> When you remove an element from the DOM, it loses its scroll position. Also see #21675. The way you've asked React to reconcile here, it must lose the scroll position on something as it's not possible to reorder DOM node children in place without detaching them.

Thanks for answer. But the React components say as that no unmount (unsubscribe). Why would you say we're removing DOM-elements?

**Comment by nmain** [comment]
With the `key`s you're using, you're asking the `List` component to render the same DOM nodes but in different places.  It has to remove them to do that.  The DOM `Element` interface doesn't provide any API to reorder elements.
