### ISSUE TITLE
Bug: old ref interaction stay attach to same node level after re render (not sure) 

### ISSUE THREAD

**Issue by atinseau** [facebook/react#24660]
React version: <=18 

## Steps To Reproduce

i think an exemple should be better

Link to code example:

https://codesandbox.io/s/still-forest-stviby?file=/src/App.js

## The current behavior

(i m french sorry for my english)
for introduce, i don't know if is a bug, or a feature, so sorry if isn't

if an ref is set on a div who disappear because a condition like blablabla != John
if the new jsx who are rendered at the same level, will have every modif what you done before the condition change 

exemple:

on mount
    ref class = "salut"

blablabla != John
    div ref
else
   div -> after condition change class = "salut" but ref is not set here

## The expected behavior

after the rerender, the new div should not have the class "salut"

**Comment by eps1lon** [comment]
Thanks for the detailed repro.

This is how the React reconciler is supposed to work. It sees two components of the same type (here: `'div'`) and therefore reuses their instance (on which you changed the `class`).

If you want to enforce different instances, you should give these components a `key` prop:

```diff
import { useEffect, useRef, useState } from "react";

export default function App() {
  const [open, setOpen] = useState(false);

  const ref = useRef(null);

  useEffect(() => {
    ref.current.className = "salut";
  }, []);

  return (
    <>
      {open ? (
-        <div>
+        <div key="open">
          <h1>OPEN</h1>
        </div>
      ) : (
-        <div ref={ref}>
+        <div key="close" ref={ref}>
          <h1>CLOSE</h1>
        </div>
      )}
      <button onClick={() => setOpen(!open)}>toggle</button>
    </>
  );
}
