### ISSUE TITLE
Missing fields on mousemove event (and maybe the other mouse events?)

### ISSUE THREAD

**Issue by lukemurray** [facebook/react#2469]
Using 0.12

var Sample = React.createClass({
  someFunc: function(e) {
    // not there
    console.log(e.layerY, e.layerX, e.x, e.y, e.movementX, e.movementY, e.offsetX, offsetY);
    // are there
    console.log(e.nativeEvent.layerY, e.nativeEvent.layerX, e.nativeEvent.x, e.nativeEvent.y, e.nativeEvent.movementX, e.nativeEvent.movementY, e.nativeEvent.offsetX, e.nativeEvent.offsetY)
  }
  render: function() {
    return (
      <div onMouseMove={this.someFunc}>
      </div>
    );
  }
});

So looking at this, it might be that react is only taking the more standard fields across? In Chrome layerY give me the position from the top of the element the event is over. I can get it using only the react event like so

e.clientY - e.currentTarget.getBoundingClientRect().top

So I'm not sure if this needs to be fixed or not, any thoughts?

Cheers,
Luke

**Comment by Ark-kun** [comment]
> `layerX` & `layerY` properties aren't standard

What about the `x`, `y`, `offsetX`, `offsetY`?
