### ISSUE TITLE
How to tell useSyncExternalStore to resubscribe?

### ISSUE THREAD

**Issue by TedDriggs** [facebook/react#24691]
I have a non-React dependency whose constructor requires it be passed its DOM node. The challenge is that the DOM node sits squarely in the middle of the React app, and sibling components need access to the constructed object. Right now, what I've done is:

```
App
    GraphContext.Provider value={/* undefined initially, will become the graph */}
        Heading
            Nav // uses data from the graph
        GraphWrapper onReady={graph => { ... }}
```

The `GraphWrapper`'s `onReady` prop passes the graph back up, where it gets stored into a `useState` and is then distributed to the rest of the app with `useContext`.

Unfortunately, this component is a monolith with internal mutability that can be observed through events it emits. Now that the `graph` instance itself is available via `useContext`, React components that want to stay in sync with graph state will need to add an event listener to `graph`.

With `useState + useEffect`, I could write a hook like this:

```js
const useSomethingFromGraph = () => {
    const graph = useContext(GraphContext);
    const [data, setData] = useState(() => graph?.getTheData());
    useEffect(() => {
        if (!graph) return;
        const updateTheData = () => setData(graph.getTheData())
        graph.addEventListener("itchanged", updateTheData);
        return () => { graph.removeEventListener("itchanged", updateTheData); };
    }, [graph]);

    return data;
}
```

I _think_ in the new world the intention is that I'm able to write something like this:

```js
const useSomethingV2 = () => {
    const graph = useContext(GraphContext);
    return useSyncExternalStore(
        // How to get this to be called again after graph has loaded?
        notify => {
            // If graph is not yet defined, should this immediately return nothing?
            // if (!graph) return;

            graph.addEventListener("itchanged", notify);
            return () => { graph.removeEventListener("itchanged", notify); };
        },
        () => graph?.getTheData()
    );
}
```

However, as noted in the comment, I'm not sure how to trigger a resubscribe, so if this hook is invoked before the graph is available the subscription is never created.

Am I understanding the hook wrong?

**Comment by vkurchatkin** [comment]
In your case it's going to resubscribe on each render anyway, but that's probably not what you want. Something like this should be the best:

```js
const useSomethingV2 = () => {
    const graph = useContext(GraphContext);
    return useSyncExternalStore(
        useCallback(notify => {
            if (!graph) return;

            graph.addEventListener("itchanged", notify);
            return () => { graph.removeEventListener("itchanged", notify); };
        }, [graph]),
        () => graph?.getTheData()
    );
}
```

**Comment by TedDriggs** [comment]
Ah - I didn't realize that the first argument is dependent on referential stability. That answers my question - thanks!
