### ISSUE TITLE
[DevTools Bug]: devtool show every page use `React`

### ISSUE THREAD

**Issue by susiwen8** [facebook/react#24690]
### Website or app

https://vuejs.org/guide/introduction.html

### Repro steps

Open the [Vue3](https://vuejs.org/guide/introduction.html) doc site, then `react` devtool show this page use  procution build of `React`
<img width="1141" alt="Screen Shot 2022-06-08 at 9 53 07 PM" src="https://user-images.githubusercontent.com/20318608/172634699-e12ac63f-da07-49ea-8181-3f569d8abddc.png">

And Github too
<img width="1200" alt="Screen Shot 2022-06-08 at 9 56 19 PM" src="https://user-images.githubusercontent.com/20318608/172634864-3e505afc-aa2b-4781-b7c1-ffce9df78635.png">

I'm using Crome
Version 102.0.5005.61 (Official Build) (x86_64)

<img width="424" alt="Screen Shot 2022-06-08 at 10 00 58 PM" src="https://user-images.githubusercontent.com/20318608/172636242-0944aecf-c532-4271-b59b-cda3ceccf553.png">

### How often does this bug happen?

Every time

**Comment by gaearon** [comment]
What other extensions are you using? I suspect that maybe the extension is detecting some other extension that injects React on the page somehow.

**Comment by susiwen8** [comment]
You are right, I have found out
