### ISSUE TITLE
Bug: Strict mode rendering twice causing the checkbox to deselect

### ISSUE THREAD

**Issue by sameerthekhans** [facebook/react#24708]
I am displaying checkboxes list and upon clicking checkbox, changing the value to opposite of previous value

React version: 18.1.0

## Steps To Reproduce

1. Open Stackblitz and try selecting checkboxes, checkboxes don't get selected

The issue is with this logic
```typescript
currentCategory.selected = !currentCategory.selected;
```
I check the previous value of checkbox and assign the opposite of it, in 2nd render this will deselect the selected checkbox

I can solve the problem by removing strict mode, but it is recommended to use strict mode, then how do I solve the problem?

Link to code example:
https://stackblitz.com/edit/react-ts-wks5wl?file=App.tsx

## The current behavior
Checkboxes get deselected after 2nd rendering

## The expected behavior
Checkboxes should be selected after 2nd rendering

**Comment by alexandroppolus** [comment]
> how do I solve the problem?

useState expects immutable changes of object:

```typescript
function categoryChange(category: Category) {
    setCategories((prevCategories) => {
      const index = prevCategories.findIndex((pc) => pc.name === category.name);
      if (index < 0) {
        // for prevent excess rerenders
        return prevCategories;
      }

      const newCategories = [...prevCategories];

      // replace object instead mutate field
      newCategories[index] = {
        ...prevCategories[index],
        selected: !prevCategories[index].selected,
      };

      return newCategories;
    });
  }
```

**Comment by sameerthekhans** [comment]
@alexandroppolus Got it, I have not cloned the each category object, this also works fine if I deep clone `prevCategories`

```typescript
function categoryChange(category: Category) {
    setCategories((prevCategories) => {
      const newCategories = JSON.parse(JSON.stringify(prevCategories)); //deep clone
      const currentCategory = newCategories.find(
        (x) => x.name === category.name
      );

      if (currentCategory) {
        currentCategory.selected = !currentCategory.selected;
      }

      return newCategories;
    });
  }
```
