### ISSUE TITLE
Errors are showing in console on Chrome and IE, but not on Firefox

### ISSUE THREAD

**Issue by andreynering** [facebook/react#2471]
I've having a strange issue with React and Firefox. I'm using the latest React (v0.12.0) and this gem: https://github.com/reactjs/react-rails

The errors inside React components are not been showing in Firefox's console, but are been showing normally in Chrome's and IE's.
- Internet Explorer:

> ![ie](https://cloud.githubusercontent.com/assets/7011819/4934832/d971d6ec-65a5-11e4-8ddc-174bbeb12100.jpg)
- Google Chrome:

> ![chrome](https://cloud.githubusercontent.com/assets/7011819/4934843/f6478802-65a5-11e4-883d-6f1341265a55.jpg)
- Mozilla Firefox (component doesn't render, but no error is shown):

> ![firefox](https://cloud.githubusercontent.com/assets/7011819/4934857/1d3e99c8-65a6-11e4-96b7-b2ccb239719b.jpg)

This just happen with Javascript errors inside React components. Errors outside React components are shown normally.

I tried to reproduce the problem in JSFiddle (http://jsfiddle.net/pvjydrho/1/), but here the error is shown, even in Firefox.

I thought it could be some issue with es5-shim, es5-sham or console-polyfill, but I tried to remove them and nothing changed.

Is this a expected behavior?

**Comment by rickgaurav** [comment]
I am having the same issue but in my case error is not shown in any browser. My app use both backbone and React. Errors inside Backbone views are properly logged on console while the ones in React components are not. Any ideas?
