### ISSUE TITLE
ReactJS NodeJS NGINX Not Redirected To Dashboard After Successful Login

### ISSUE THREAD

**Issue by OlammieAO** [facebook/react#24737]
Hello Famz,
  Please help. I have my ReactJS NodeJS deployed on Linux NGINX and I can login with perfect redirection to dashboard page on my development machine, on my phone, and on Linux OS running on my computer Oracle VM; i can accessed the application on these devices and it worked fine even when I changed IP address but immediately another device e.g somebody else computer or phone tries to login, it would always not redirect to dashboard but my three devices(laptop, phone, and Linux OS running on my computer Oracle VM) can redirect successfully to dashboard after logging in.

My ReactJS build file contents are in /etc/nginx/sites-available/mydomain/ and this is my nginx.config below:

**********************************************************
events{
worker_connections    4096;
}
 
http
{
  server { # simple reverse-proxy
    listen       80;
    server_name  mydomain;
   
    # serve static files
    #location ~ ^/(images|javascript|js|css|flash|media|static)/  {
    
    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        root /etc/nginx/sites-available/mydomain;
         index index.html;
        try_files $uri /index.html;
    }
    
    location /api {
        proxy_pass https://localhost:8084;
       root /etc/nginx/sites-available/mydomain;
       index index.html;
    }
  }

server {
    listen 443 ssl;
    server_name mydomain;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        root /etc/nginx/sites-available/mydomain;
        index index.html;
        try_files $uri /index.html;
    }
    
    location /api {
        proxy_pass https://localhost:8084;
        root /etc/nginx/sites-available/mydomain;
        index index.html;
    }

    ssl_certificate     /etc/letsencrypt/live/mydomain/fullchain.pem; # managed by Certbot;
    ssl_certificate_key /etc/letsencrypt/live/mydomain/privkey.pem; # managed by Certbot

    #...
}
}
******************************************
Please fams, what difference does it make as I have my NGINX configuration in nginx.conf and not in default?

As I configured my nginx.conf do I still need to go do the same in /etc/nginx/sites-available/default and what extension is this default config file?

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
