### ISSUE TITLE
Bug: React will not upgrade to v 18, remains on v 17.0.2 in package.json

### ISSUE THREAD

**Issue by dnorrstrand** [facebook/react#24756]
I have been trying to upgrade my app (created via CRA) to React v 18 using the official upgrade guide on [reactjs.org](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html). The first thing I did was run this command in the project folder in my terminal: `npm install react react-dom`

The command finished without errors, yet I still have some vulnerability warnings:

```
up to date, audited 2138 packages in 4s
214 packages are looking for funding
  run `npm fund` for details
10 vulnerabilities (1 moderate, 7 high, 2 critical)
```

When I check my package.json I am still showing the old React version as follows:

```
"name": "...",
    "version": "...",
    "private": true,
    "proxy": "http://localhost:3052",
    "dependencies": {
        "@auth0/auth0-react": "^1.8.0",
        "@babel/cli": "^7.0.0",
        "@babel/core": "^7.0.0",
        "@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1",
        "@testing-library/jest-dom": "^5.14.1",
        "@testing-library/react": "^11.2.7",
        "@testing-library/user-event": "^12.8.3",
        "babel-preset-react-app": "^3.1.2",
        "husky": "^7.0.4",
        "lint-staged": "^12.3.7",
        "node-sass": "^7.0.1",
        "npm": "^7.24.1",
        "prettier": "^2.6.1",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-icons": "^4.2.0",
        "react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
        "react-router-dom": "^5.3.0",
        "web-vitals": "^1.1.2"
    },
    "devDependencies": {
        "react-scripts": "^5.0.0"
    },
    "lint-staged": {
        "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}": [
            "prettier --write"
        ]
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
    },
    "eslintConfig": {
        "extends": [
            "react-app",
            "react-app/jest"
        ]
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "prettier": {
        "trailingComma": "none",
        "tabWidth": 4,
        "semi": true,
        "singleQuote": false,
        "bracketSpacing": false
    },
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    }
}
```
 When I check the React version in the terminal with this command `npm view react version` I get `18.2.0`.

Then I also changed the contents of my index.js file as recommended to be as follows (with minor adjustments required for embedding my app into another larger web app):

```
import React from "react";
import {createRoot} from "react-dom/client";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";

const tenderTree = document.getElementById("tender-tree");
const root = createRoot(tenderTree);

root.render(
    <React.StrictMode>
        <App {...tenderTree.dataset} />
    </React.StrictMode>
);
reportWebVitals();
```

Naturally, the app doesn't compile and gives weird warnings about missing dependencies and wrong paths, that are way to long to post here. My npm and other dependencies are on their latest versions since I had run npm update prior to trying to upgrade to React v 18. 

What could I have done wrong and what can I do to fix this upgrade? Thanks!!

**Comment by PiscesXP** [comment]
You should add @latest right after the package name, since npm doesn't update your package when there's already one in your package.json.

Use 
```
npm install react@latest
```
should update to v18.

**Comment by dnorrstrand** [comment]
> You should add @latest right after the package name, since npm doesn't update your package when there's already one in your package.json.
> 
> Use
> 
> ```
> npm install react@latest
> ```
> 
> should update to v18.

Thanks, I will try this, but isn't it implied by default that the upgrade should be to the latest version? And why am I getting the upgraded version number in the terminal after the upgrade?
