### ISSUE TITLE
Bug: TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by mohamed-haouari** [facebook/react#24774]
i'm adding React Datepicker to my app but i still getting this bug my React version is 18.2.0 

`import React, { useState } from "react";
import DatePicker from "react-datepicker";

import "react-datepicker/dist/react-datepicker.css";

const Calendar = () => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker selected={startDate} onChange={(date) => setStartDate(date)} />
  );
};

export default Calendar;
`
[
![Capture](https://user-images.githubusercontent.com/72602655/175004162-1c073c96-4478-4767-9115-09b7b477eec2.JPG)
](url)

**Comment by farnoodma** [comment]
test
