### ISSUE TITLE
May be a bug

### ISSUE THREAD

**Issue by cfgxy** [facebook/react#24778]
window.event is null in IE9/IE10, this cause read type property on null at line 373

https://github.com/facebook/react/blob/9e3b772b8cabbd8cadc7522ebe3dde3279e79d9e/packages/react-dom/src/client/ReactDOMHostConfig.js#L370-L373

**Comment by guillaumebrunerie** [comment]
Is this in React 18? Note that IE is not supported anymore: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#dropping-support-for-internet-explorer

**Comment by gaearon** [comment]
Oh you're saying it's `null` rather than `undefined`?

**Comment by yeliex** [comment]
yes, `window.event` in  ie would be undefined. could add a fix for this

**Comment by TrAndreiR** [comment]
Any update on this issue?

**Comment by coderup2021** [comment]
I also getting this issue in React 18
