### ISSUE TITLE
Bug: BROWSER environment variable stopped working after update of react-scripts to v5

### ISSUE THREAD

**Issue by dkocich** [facebook/react#24775]
- Since the update to React scripts v5 `BROWSER` env variable stopped working (its usage is described here https://create-react-app.dev/docs/advanced-configuration/) (this also did not work with REACT_APP_ prefix)
- this is very annoying because I switch and restart many times daily for PR reviews, etc. and I use an isolated browser for web development (with a set of various extensions) and different for my company-related logins and work profile (MSEdge with AAD account)

React version:

## Steps To Reproduce

1. create `.env` file
2. define your `BROWSER` variable

```
# example for windows
BROWSER="C:\Program Files\Google\Chrome Dev\Application\chrome.exe"
# example for debian
BROWSER=google-chrome-unstable
```

4. `npm start` to see which browser opens (system default or the one defined in `.env`)

Link to code example:
https://github.com/dkocich/react-example-repo

**Comment by hamlim** [comment]
Hey @dkocich this looks like an issue with create-react-app and not the React library itself. It looks like your issue has already been opened on the create-react-app repo here: https://github.com/facebook/create-react-app/issues/11873

**Comment by dkocich** [comment]
thanks, wrong repo; closed in favor of https://github.com/facebook/create-react-app/issues/11873
