### ISSUE TITLE
bug : renderToPipeableStream and Readable stream not working together

### ISSUE THREAD

**Issue by aminnairi** [facebook/react#24789]
It is really frustrating that the `renderToPipeableStream` is not a true `Transform` stream because it prevents prepending a `doctype` at the beginning of a rendered JSX element that has lazy routes in them, making the rendered stream outputing a JSX code that lacks the doctype and making the browser enter in quirks mode.

React version: 18.2.0

## Steps To Reproduce

1. Create a Readable stream from the string `<!DOCTYPE html>`
2. Try to pipe the stream to a `renderToPipeableStream`
3. See that this is not possible

## The current behavior

`renderToPipeableStream` does not create a `Transform` nor a `Readable` stream. It can be easily piped to a response for example, but there is no way to plug a transform stream to manipulate the output for instance of simply prepending a string such as the doctype.

```tsx
import {createElement} from "react";
import {renderToStaticMarkup, renderToPipeableStream} from "react-dom/server";
import {pipeline, Readable, PassThrough} from "stream";

const StreamExtra = {
  // String -> PassThrough
  prepend(value) {
    const passThrough = new PassThrough();
    passThrough.write(value);
    return passThrough;
  }
};

pipeline(
  Readable.from(renderToStaticMarkup(createElement("span", null, "React"))),
  StreamExtra.prepend("<!DOCTYPE html>"),
  process.stdout,
  console.error
);
// <!DOCTYPE html><span>React</span>

pipeline(
  renderToPipeableStream(createElement("span", null, "React With Suspense Somwewhere")),
  StreamExtra.prepend("<!DOCTYPE html>"),
  process.stdout,
  console.error
);

// TypeError [ERR_INVALID_ARG_TYPE]: The "body" argument must be of
// type function or an instance of Blob, ReadableStream, WritableStream,
// Stream, Iterable, AsyncIterable, or Promise or { readable, writable }
// pair. Received an instance of Object
```

## The expected behavior

This should be a stream so that it can be manipulated easily by the end-user. If we go deeper, this also prevents things like caching for instance, which could be great for performance (which is the main goal behind server-side rendering and hydratation).

## Links

*Notes: `process.stdout` is equivalent to `http.ServerResponse` since they are both `Stream` instances and `process.stdout` is easier for testing.*

- [Reproduction](https://replit.com/@amin_nairi/OutlyingBogusAssociate#index.js)

### Use the Readable stream first

```tsx
import {createElement} from "react";
import {renderToPipeableStream} from "react-dom/server";
import {Readable} from "stream";

Readable.from("<!DOCTYPE html>").pipe(process.stdout);

renderToPipeableStream(createElement("h1", null, "Hello, world!")).pipe(process.stdout);
```

### Write to the stream directly

```tsx
import {createElement} from "react";
import {renderToPipeableStream} from "react-dom/server";

process.stdout.write("<!DOCTYPE html>");

renderToPipeableStream(createElement("h1", null, "Hello, world!")).pipe(process.stdout);
```

### StreamExtra Elm style

```tsx
import {createElement} from "react";
import {renderToStaticMarkup, renderToPipeableStream} from "react-dom/server";
import {pipeline, Readable, PassThrough, Transform} from "stream";

const StreamExtra = {
  // String -> PassThrough
  prependString(string) {
    const passThrough = new PassThrough();
    passThrough.write(string);
    return passThrough;
  },
  // PipeableStream -> PassThrough
  fromPipeableStream(pipeableStream) {
    const passThrough = new PassThrough() 
    pipeableStream.pipe(passThrough);
    return passThrough;
  },
  // String -> Transform
  appendString(string) {
    const transform = new Transform({
      transform(chunk, encoding, next) {
        next(null, chunk);
      },
      flush(next) {
        this.push(string);
        next();
      }
    }); 

    return transform;
  }
};

pipeline(
  StreamExtra.fromPipeableStream(renderToPipeableStream(createElement("span", null, "React With Suspense Somwewhere"))),
  StreamExtra.prependString("<!DOCTYPE html><html><div id='root'"),
  StreamExtra.appendString("</div><script src='/index.js' type='module'></script></html>"),
  process.stdout,
  console.error
);

// <!DOCTYPE html><html><span>React With Suspense Somwewhere</span></html>
```

Note that this solution will completely break the router on the client side, even though all the scripts are loaded and the suspense script as well.

**Comment by gaearon** [comment]
Isn't doctype automatically emitted when you render `<html>`? I thought we did that.

**Comment by aminnairi** [comment]
> Isn't doctype automatically emitted when you render `<html>`? I thought we did that.

Nope it does not, just tested quickly on a brand new project with this code.

```typescript
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";

const element = createElement(
  "h1",
  null,
  "Hello, world!"
);

const renderedElement = renderToStaticMarkup(element);

console.log(renderedElement);
// <h1>Hello, world!</h1>
```
