### ISSUE TITLE
Bug: eslint-plugin-react-hooks miss

### ISSUE THREAD

**Issue by kylemh** [facebook/react#24785]
I **think** this is a bug, but maybe arguments of certain hooks can safely be considered "top" level?

React version: 16.14.0

## Steps To Reproduce

1. https://codesandbox.io/s/lingering-breeze-toex4f?file=/src/App.js:100-149
2. See that `const [refs, setRefs] = useState([useRef(null)]);` isn't flagged by ESLint
3. See that `const ref = useRef(useState(0));` isn't flagged by ESLint
4. See that `useEffect(useState, [useState]);` isn't flagged by ESLint

## The current behavior

`useRef` is allowed as an argument within `useState`.
`useState` is allowed as an argument within `useRef`.
`useState` is allowed as the callback for `useEffect`.

## The expected behavior

All cases should by flagged by the linter because an argument of a hook isn't the top level of a function component.

**Comment by vkurchatkin** [comment]
There is no real reason to flags this. 

This:

```js
const [refs, setRefs] = useState([useRef(null)])
```

is the equivalent of this:

```js
const _ref = useRef(null);
const [refs, setRefs] = useState([_ref]);
```
So it _is_ top level and doesn't violate any rules.

**Comment by kylemh** [comment]
interesting, cuz the argument is it's own closure, no?

**Comment by vkurchatkin** [comment]
No, there are no closures involved here. It's just what "top level" means. 
Here is relevant documentation: https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions

> Don’t call Hooks inside loops, conditions, or nested functions. 

That's what "not top level" is. In your examples it is top level, just values returned from hooks are anonymous.
