### ISSUE TITLE
Bug: Getting Loader instead of UI in SSR with Lazy Suspense

### ISSUE THREAD

**Issue by opensrc0** [facebook/react#24794]
Hi, 
 
 I have recently migrated to 18.2.0 from 16.8.0 and Using server side rendering. I have done the code spitting using lazy and suspense but found some issue with react. Some times I am getting my server rendered chunk and some time getting loader instead of chunk. Then I debugged and found react is adding some script.

React version: 18.2.0

## Steps To Reproduce

1. Go to your app using SSR app
2. Use code splitting using lazy and suspense

Code for SSR and Client:
```
const Index = ({ isSSR, ...props }) => {
  return (
    <React.Suspense fallback={<LoaderUI />}>
      <HomePageW isSSR={isSSR} {...props} />
    </React.Suspense>
  );
};
```

SSR Code
```
const page = renderToPipeableStream(
    (
      <div id="root">
        {
        _sheet.collectStyles(
          <ThemeProvider theme={theme}>
            <Provider store={store}>
              <HelmetProvider context={helmetContext}>
                <StaticRouter history={history} location={history.location}>
                  <Routes>
                    <Route
                      path="*"
                      element={(
                        <Wrapper
                          isMobile={isMobile}
                          routes={routes}
                          history={history}
                          location={history.location}
                        />
                      )}
                    />
                  </Routes>
                </StaticRouter>
              </HelmetProvider>
            </Provider>
          </ThemeProvider>,
        ) 
      }
      </div>
    ),
    {
      onShellReady() {
        const didError = false;
        res.statusCode = didError ? 500 : statusCode;
        res.write(`<head>Title</head>`);

        page.pipe(res);

        res.write(`
          <script>
            window.addEventListener('load', function(){
              ${loadJs(assets.vendor1.js)}
              ${loadJs(assets.vendor2.js)}
              ${chunks.reduce((s, chunk) => `${s}${loadJs(assets[chunk].js)}`, '')}
              ${loadJs(assets.client.js)}
            });
          </script>
      `);
      },
    },
  );
```

## The current behavior
Script has been added in the bottom of the page
`function $RC(a,b){a=document.getElementById(a);b=document.getElementById(b);b.parentNode.removeChild(b);if(a){a=a.previousSibling;var f=a.parentNode,c=a.nextSibling,e=0;do{if(c&&8===c.nodeType){var d=c.data;if("/$"===d)if(0===e)break;else e--;else"$"!==d&&"$?"!==d&&"$!"!==d||e++}d=c.nextSibling;f.removeChild(c);c=d}while(c);for(;b.firstChild;)f.insertBefore(b.firstChild,c);a.data="$";a._reactRetry&&a._reactRetry()}};$RC("B:0","S:0")`

and Loader is showing instead of UI. When I ran script added by react, the actual UI is shown. The script is doing their job but we don't need this from browser.

### Showing Loader Instead of actual UI
<img width="476" alt="loader" src="https://user-images.githubusercontent.com/6891544/175920734-ad6dc186-07d8-4491-9f90-909987bb4122.png">

### Actual UI with display none and some javascript has been added in the end of the page
<img width="982" alt="script" src="https://user-images.githubusercontent.com/6891544/175920454-9e11db9f-e9dd-4886-a3e7-3424b256f1a9.png">

## The expected behavior
Original Ui should be shown instead of loader UI.

**Comment by hdlion** [comment]
Its a biggest problem of SSR and impacting SEO. if UI is not getting loaded, Helmet will not add title and meta's.

**Comment by codinginflow** [comment]
I have the same problem in NextJS but it only happens if I fetch data using Axios instead of fetch (which is manipulated by NextJS in some way). 
Here is a sandbox:
https://codesandbox.io/p/sandbox/elated-platform-qvosk2?file=%2Fapp%2Flayout.tsx%3A1%2C1

**Comment by sorenhoyer** [comment]
@codinginflow weird, because it happens to me if I use suspense and disable javascript.

**Comment by codinginflow** [comment]
> @codinginflow weird, because it happens to me if I use suspense and disable javascript, and I'm not using Axios.

I was wrong. It happens with fetch too. And apparently, it's expected because JavaScript is necessary to navigate from the loading indicator to the page. Although this seems to kill the purpose of SSR a bit.
