### ISSUE TITLE
Can't find React 16 docs

### ISSUE THREAD

**Issue by AllanPinheiroDeLima** [facebook/react#24802]
I googled it, asked some work colleagues, and nobody seems to know where the docs for v16 are. Is there any docs of this version left ? We have landed a big project that we need do fix, but I don´t find the docs anywhere.
I saw in other threads that older versions of docs are deleted, is that true ? If it isn't online, is there even a place where I can download and serve locally ? 

It seems weird to have those docs deleted, since some projects are never updated at all

Thank you!

**Comment by JustinTime42** [comment]
Been there! I've managed to find what I need on the WayBackMachine, which has pretty thorough snapshots of react.js back to 2017. 
http://web.archive.org/web/20170901000000*/reactjs.org

**Comment by alex-streza** [comment]
I've looked up the docs too, the only information I found related to React v16 were the changelog blogs, undoubtedly you found them too but will leave them here.

[React Changelog Blogs](https://reactjs.org/versions/)

**Comment by LuisFilipePedroso** [comment]
But what do you want to look at in the previous docs? 
I mean, the new one is a consequence of the older one, so what you want should be at the React 18 documentation.

**Comment by sunil-sharma-999** [comment]
you can use [archive wayback machine](https://web.archive.org/)
Ex [React JS docs page on 26th sept, 2018](https://web.archive.org/web/20171015223826/https://reactjs.org/docs/hello-world.html)
Use dates in changelog for whichever version of docs you want.

**Comment by sunil-sharma-999** [comment]
close #24802

**Comment by gaearon** [comment]
You can use https://17.reactjs.org/, which is pretty much the same as 16.

**Comment by thefonso** [comment]
I feel sorry for the thousands of people learning React based on 16.x (looking at you Boot-Camps). When they graduate....there will be No documentation. And no 17 !== 16 18 !== 16 in regards to documentation. This is unprofessional. Not seen anything like this delete the docs move in 20 years.

**Comment by rickhanlonii** [comment]
This is finally fixed: 16.react.dev now redirects to 16.reactjs.org, which is essentially a re-deployment of React 17 with the correct React 16 version info, and a few React 17 specific notes removed. We don't have access to what the actual React 16 site looked like before 17, but this gets it close enough and all the docs should be accurate. 

The branch is available here: https://github.com/reactjs/legacy.reactjs.org/tree/16.reactjs.org
