### ISSUE TITLE
Bug: This is likely a bug. I can't use useState as i want.

### ISSUE THREAD

**Issue by khnbzkrt** [facebook/react#24800]
My expectation is that inside the handleMouseMove function the isActive value is updated depending on the condition. But this is not working as I want. Could there be something I'm misunderstanding?

You can see results in codesandbox link or images.

Link to code example: https://codesandbox.io/s/hopeful-thompson-e23h3g?file=/src/App.js

![image](https://user-images.githubusercontent.com/67371416/176000691-cefb3d17-4a8c-43eb-b383-c55a7b5cbcb3.png)
![image](https://user-images.githubusercontent.com/67371416/176000759-e1aeb996-cb62-453e-87ef-decbcc502c39.png)

**Comment by rafaelmiranda178** [comment]
Try useRef... Updates correctly.. 

`
import { useRef } from "react";
import "./styles.css";

export default function App() {
  const isActive = useRef(false);

  const handleMouseDown = (e) => {
    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("mouseup", handleMouseUp);
  };

  const handleMouseMove = (e) => {
    console.log("First Check");
    console.log(e.clientX, isActive.current);
    console.log(e.clientX > 300);
    if (e.clientX > 300) {
      isActive.current = true;
    } else {
      isActive.current = false;
    }
    console.log("Second Check");
    console.log(e.clientX, isActive.current);
  };

  const handleMouseUp = () => {
    window.removeEventListener("mousemove", handleMouseMove);
  };

  return (
    <div
      className="App"
      onMouseDown={handleMouseDown}
      style={{ width: "100%", height: "100vh" }}
    >
      App
    </div>
  );
}
`

**Comment by vkurchatkin** [comment]
> Could there be something I'm misunderstanding?

Basically, yes. You expected that after calling `setIsActive(true)` you can observe `isActive` is set to true. There multiple reasons why this is simply not possible:

1. `isActive` is actually defined as `const`, so it can't possibly be updated at all
2. Even  if `isActive` was `let` or `var`, the only way to update it would be to explicitly say `isActive = true`. There is simply no way React can update `isActive`, at all.

The way React works, each render gets its own immutable snapshot of state. When you call state setter, React schedules a new render with the new value of state, but the old value remains the same forever.

**Comment by eps1lon** [comment]
In addition to https://github.com/facebook/react/issues/24800#issuecomment-1168420753 also take a look at https://beta.reactjs.org/apis/usestate#ive-updated-the-state-but-logging-gives-me-the-old-value to understand the behavior you're seeing.
