### ISSUE TITLE
Bug: PLEASE HELP WHEN I RUN npx react-native run-android this error will show :

### ISSUE THREAD

**Issue by mamonaabdullah122** [facebook/react#24828]
ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.

Check the render method of `OnboardingScreen`.

**Comment by gaearon** [comment]
Check the rendering method of `OnboardingScreen`. Somewhere there you’re rendering a JSX element like `<Something>` but `Something` in your case is actually a number. This is a mistake in your code.

Please don’t file questions like this as bugs to React. Use support resources like StackOverflow instead.

**Comment by mamonaabdullah122** [comment]
This is not work for me
