### ISSUE TITLE
ChildComponnet Re render not working with Key prop in react 18

### ISSUE THREAD

**Issue by yashaswinibprasad87** [facebook/react#24834]
I am using a class component that has MUi tab. Unable to re render with  the latest data inside child component .

- When I switch tabs  Re-Render happens with old data of another tab though key is provided inside <TabPanel> 

 case "layout":
        return (
          <Suspense fallback={<span>Loading ...</span>}>
            <XYZ
              **key={content.key + index}**
              type="Lyt"
              parentTabDetails={content}
              parentTab={content.Title}
            />
          </Suspense>
        );

Breaking changes  in 18.0 (Working as expected in 17.0.2 )
KIndly provide a fix or solution
Help Appreciated

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by RAJEEV2510** [comment]
Try to create key with random number may be help You .
