### ISSUE TITLE
[DevTools Bug]: Uncaught TypeError: hook.sub is not a function

### ISSUE THREAD

**Issue by liucan233** [facebook/react#24844]
### Website or app

New project created by CRA

### Repro steps

1. create a new project by CRA on mac os Monterey v12.4;
2. import 'react-devtools' at first line of `src/index.tsx`;
3. sudo npm i --location=global react-devtools;
4. npx react-devtools;
5. in my raect app console run `t=document.createElement('script'); t.type='text/javascript'; t.src='http://localhost:8097'; document.head.prepend(t)`;
6. Uncaught TypeError: hook.sub is not a function, below are some screenshots.
<img width="659" alt="error" src="https://user-images.githubusercontent.com/13808186/177245359-f55c0017-d833-4043-8a0a-43cc3c4eb5b1.png">
<img width="647" alt="location" src="https://user-images.githubusercontent.com/13808186/177245574-4fb78d7d-2abc-423b-9ef5-006007c70081.png">

### How often does this bug happen?

Every time

**Comment by mondaychen** [comment]
> import 'react-devtools' at first line of src/index.tsx;

Why do you need to do this? If you are trying to set up the standalone devtools UI following the [README](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#usage-with-react-dom), the only thing you need to do is to add the script tag

**Comment by liucan233** [comment]
> > import 'react-devtools' at first line of src/index.tsx;
> 
> Why do you need to do this? If you are trying to set up the standalone devtools UI following the [README](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#usage-with-react-dom), the only thing you need to do is to add the script tag

I tried, but there was an error in screenshots above.

**Comment by mondaychen** [comment]
Any chance you can provide a github repo that I can use to reproduce your issue?

**Comment by liucan233** [comment]
> Any chance you can provide a github repo that I can use to reproduce your issue?

script in head

<img width="1172" alt="insert script" src="https://user-images.githubusercontent.com/13808186/177681577-abd69877-674d-4555-bc84-beae05c1354f.png">

result

<img width="70%" alt="error" src="https://user-images.githubusercontent.com/13808186/177681620-b29bbd5f-ba6d-44d5-a34c-ce3d5aa7fe75.png">

[click to download my code.zip](https://github.com/facebook/react/files/9060055/code.zip)

**Comment by mondaychen** [comment]
Ah I think I know what's going on. You are trying to insert the script tag after your page is loaded, correct? Does it work if you simply put the script tag in HTML?

**Comment by liucan233** [comment]
It's true. Now this problem has been solved. Thank you so much.

**Comment by liucan233** [comment]
> Ah I think I know what's going on. You are trying to insert the script tag after your page is loaded, correct? Does it work if you simply put the script tag in HTML?

It's true. Now this problem has been solved. Thank you so much.

**Comment by tjx666** [comment]
I occur this issue in my environment.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/203153962-4f47996d-be2c-438a-b72f-d8a32cbc198c.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/203154053-a672c033-5299-449a-a3a9-21d1468b655f.png">

I load react-devtools by put in most front of webpack entry: https://github.com/tjx666/awesome-chrome-extension-boilerplate/blob/manifest-v3/server/utils/entry.ts#L29

reproduce:

- git clone https://github.com/tjx666/awesome-chrome-extension-boilerplate.git
- git checkout manifest-v3
- pnpm install
- run pnpm devtools
- chrome open chrome://extensions/
- enable chrome extension develop mode
- load unpack extension folder under project root
- open options page of this extension
- then you will see the error in above screenshot.

**Comment by mondaychen** [comment]
@tjx666 I'm not familiar with how webpack works. Maybe the order the array does not guarantee the order of execution?
Also, have you tried putting the script tag in the HTML?

**Comment by liucan233** [comment]
> @mondaychen I occur this issue in my environment.
> 

make sure that mport devtool js before react or other script.

**Comment by tjx666** [comment]
@liucan233 doesn't work

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/203383905-805c60e0-ec30-4f06-84ca-22652fb8ce2e.png">

**Comment by liucan233** [comment]
> @liucan233 doesn't work
I mean in html script tag to import js of devtools, not tsx file import.

**Comment by tjx666** [comment]
@liucan233 chrome extension doesn't alow load remote script include localhost

**Comment by liucan233** [comment]
> @tjx666 

你这样import是无法保证顺序的，因为现在的babel会在所有import自动添加import react，你这个浏览器报错是因为你的csp策略，修改csp策略就好了。

**Comment by tjx666** [comment]
改 CSP 策略是没有用的：
<img width="836" alt="image" src="https://user-images.githubusercontent.com/41773861/203389950-58519e97-d509-4268-9b53-757b43e8ddbc.png">

Manifest V3 就是这么恶心，https://bugs.chromium.org/p/chromium/issues/detail?id=1247690

**Comment by tjx666** [comment]
而且因为我 babel 配置 exclude 了 node_modules：

<img width="632" alt="image" src="https://user-images.githubusercontent.com/41773861/203390997-2f6edaee-e978-424b-8c4a-a32328c4432d.png">

webpack entry 里面加载的 devtools 应该不会先导入 react？

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/203391144-dee95f1d-40a1-42eb-ad13-916cc423df35.png">

**Comment by liucan233** [comment]
> 而且因为我 babel 配置 exclude 了 node_modules：

我说的是自动添加导入，有些tsx文件你你没导入react，react组件却能运行就因为自动导入了react，跟你loader顺序无关。

**Comment by tjx666** [comment]
I had fixed by https://github.com/tjx666/awesome-chrome-extension-boilerplate/commit/5d426a3da3f629906bc4f99d6de9d3be5012e3b0
