### ISSUE TITLE
Bug: @testing-library/react-native useRef does not return the same type as getByTestID

### ISSUE THREAD

**Issue by kmalakoff** [facebook/react#24843]
Cross-posting [https://github.com/callstack/react-native-testing-library/issues/1006](https://github.com/callstack/react-native-testing-library/issues/1006) since @testing-library/react-native seems like a light wrapper around this library

@testing-library/react-native useRef does not return the same type as getByTestID.

The ref.current is of type "Component" instead of "ReactTestInstance".

React version:

## Steps To Reproduce

Run these commands:
git clone [git@github.com](mailto:git@github.com):kmalakoff/react-native-contains.git
cd react-native-contains
git checkout @testing-library/react-native-issue
npm install
npm run build
npm test

You will see this assertion fails: https://github.com/kmalakoff/react-native-contains/blob/%40testing-library/react-native-issue/test/unit/native.test.native.tsx#L53

## The current behavior

The ref.current is of type "Component" instead of "ReactTestInstance".

## The expected behavior

The ref.current set by useRef should be type of "ReactTestInstance" so that it can be used in an identical manner as an element found through getByTestID

**Comment by eps1lon** [comment]
This repository does contain the React runtime and some renderers but no renderers related to `react-native`. That would be https://github.com/facebook/react-native. However, It looks like https://github.com/callstack/react-native-testing-library/issues/1006 already targets the appropriate maintainers. 

Until they confirm that this is a `react-native` issue I would refrain from cross-posting.
