### ISSUE TITLE
Testing Rendered ReactJs with Karma/Jasmine

### ISSUE THREAD

**Issue by kazepreaux** [facebook/react#24845]
Hi,

I have an application where I just render React Components using the createElement method like so:
```
public static render<T>(target: HTMLElement, reactComponent: FC<T>, attrs: T) {
        const root = createRoot(target);

        root.render(
            React.createElement(reactComponent, attrs),
        );
    }
 ```
 
The code works fine in browser, but as soon as I test my whole page (which includes the component), the component is not rendered. 
The FC code is only called at the end of the test, performing all at once. 
I am testing my application using Karma/Jasmine, using ReactJS 18 (which has native auto-batching), my component is not rendered until the end of the test.
 
The code above has been modified to use flushSync() to make it render immediately, but the flushSync also needs to be done on any of my hooks, which feels like an overkill.

```
public static render<T>(target: HTMLElement, reactComponent: FC<T>, attrs: T) {
        const root = createRoot(target);

        // Any state change needs to be sync for Karma test purposes.
        // In reality, we should not need it.
        // React 18 now batches changes, which Karma does not like.
        flushSync(() => root.render(
            React.createElement(reactComponent, attrs),
        ));
    }
 ```
 
Is there a way to force the rendering in test (karma) without the need to change all my code to use flushSync?
 
Thanks,

Louis

**Comment by kazepreaux** [comment]
An extra information, my karma test renders a wider element than the reactjs component, it renders a whole page.

**Comment by eps1lon** [comment]
> Is there a way to force the rendering in test (karma) without the need to change all my code to use flushSync?

The recommendation since 16.8 has been to use [`act()`](https://reactjs.org/docs/testing-recipes.html#act). Though since this does can become quite noisy you can choose testing libraries like [`@testing-library/react`](https://testing-library.com/docs/react-testing-library/intro) which have a thing, more ergonomic API for testing React components.
