### ISSUE TITLE
Possible problem with the code

### ISSUE THREAD

**Issue by LuisFilipePedroso** [facebook/react#24847]
Hey there.
I was looking at the code of Fiber (ReactFiberCommitWork.new.js is the file) and I realized that the IntelliSense wasn't working in some parts of the code, like:

![Screen Shot 2022-07-05 at 13 34 39](https://user-images.githubusercontent.com/29440533/177375099-89e7ef63-15b9-4e56-a228-825a7e22c0e3.png)

Is it the expected behavior? I think that the next cases won't be achieved.

**Comment by eps1lon** [comment]
Note that the React codebase is written with Flow types not TypeScript. So you have to setup the proper extensions on your IDE.

**Comment by LuisFilipePedroso** [comment]
@eps1lon right but I don't think the problem is related to it. 
I configured the Flow in Vscode to confirm and I believe the problem is still related to this line:
`const didWarnSet = ((didWarnAboutUndefinedSnapshotBeforeUpdate: any): Set<mixed>);`

Basically, I think there's an extra parenthesis and this code below is not being reached because of it.
`
case HostRoot: {
        if (supportsMutation) {
          const root = finishedWork.stateNode;
          clearContainer(root.containerInfo);
        }
        break;
      }
      case HostComponent:
      case HostText:
      case HostPortal:
      case IncompleteClassComponent:
        // Nothing to do for these component types
        break;
      default: {
        throw new Error(
          'This unit of work tag should not have side-effects. This error is ' +
            'likely caused by a bug in React. Please file an issue.',
        );
      }
`

**Comment by eps1lon** [comment]
Yeah honestly I don't rely on flow. It's rarely working for me in VSCode and if it does it crashes soon after or gives unhelpful errors ("this line is not covered").
