### ISSUE TITLE
Allow replacing the anchoring element

### ISSUE THREAD

**Issue by bazo** [facebook/react#2484]
i have the following html, using bootstrap3 and some theme 

``` html
<ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
            <i class="fa fa-envelope"></i>
            <span class="label label-warning">16
            </span>                    </a>
        <ul class="dropdown-menu dropdown-messages" id="latest-messages">
            <li>
                <div class="dropdown-messages-box">...
                </div>
            </li>
            <li class="divider">
            </li>
            <li>
                <a href="mailbox.html">
                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong></a>
            </li>
        </ul>
    </li>
    <li>...</li>
    <li>...</li>
    ...
</ul>
```

now I would like to render the ul#latest-messages with react
and IMHO that's currently impossible. why?

i have the following components:
Divider - div.divider
Message - div.dropdown-messages-box
LatestMessages = the ul#latest-messages

if i do this

``` js
React.renderComponent(LatestMessages(), li.dropdown); 
```

it replaces also my link with the icon

if i do this

``` js
React.renderComponent(LatestMessages(), ul#latest-messages); 
```

the i get two uls nested in each other

sure i could go up the hierarchy and convert more and more parent elements to react components, until i'm left with one single div i could anchor the all encompassing component to.

but i just want to the render the dropdown ul with react.

that's why react should have an option to replace the element given in renderComponent.

thanks for reading this long rant and hope for a solution soon

**Comment by lggdance** [comment]
Will a fix be implemented soon into React? I really like it so far, but this is a major bummer unfortunately.

**Comment by zpao** [comment]
No, I wouldn't expect this to change anytime soon. Maybe eventually.
