### ISSUE TITLE
Bug: Duplication in bundle assembled with eslint when using `react-dom/server`

### ISSUE THREAD

**Issue by mxro** [facebook/react#24841]
When bundling code that uses the `renderToString` method, multiple versions of react-dom are included in the bundle.

```typescript
import { renderToString } from 'react-dom/server';
```

This is the visualised breakdown of the code included in a bundle assembled with [esbuild](https://esbuild.github.io/) with the following options (it is bundled up for use in a server rather than client):

```
{
      plugins: [pnpPlugin()],
      bundle: true,
      entryPoints: [`${routesDir}/${config.relativeFilePath}`],
      external: [
        'aws-sdk', // included in Lambda runtime environment
      ],
      minify: true,
      platform: 'node',
      format: 'cjs',
      target: 'node16.0',
      treeShaking: true,
      sourcemap: true,
      outfile: getOutFileForLambda(config),
      metafile: true,
}
```

![image](https://user-images.githubusercontent.com/1448524/177215014-bc1caa58-2890-4b46-97d7-d3a0e52c57c1.png)

Note here the following files are included:

- `react-dom-server-legacy.node.production.min.js`
- `react-dom-server.node.production.min.js`
- `react-dom-server.node.development.js`
- `react-dom-server-legacy.node.development.js`
- `react-dom.production.min.js`
- `react-dom.development.js`

I would assume only two of these should be required (one for `react-dom` and one for `react-dom-server`).

Note I carefully cleaned the dependency tree of the project to ensure there is only one version of `react` and `react-dom` referenced.

The workspace this was tested in was created using Yarn 3.

React version: 18.2.0

## Steps To Reproduce

1. Create a file `render.ts` that contains a call to the renderToString method.

```typescript
import type React from 'react';
import { renderToString } from 'react-dom/server';

renderToString(<div>Hi</div>);
```

2. Provide this file as the [`entrypoint`](https://esbuild.github.io/api/#entry-points) to bundle it with esbuild

```
esbuild render.ts --bundle --metafile=meta.json --platform=node
```  

3. Visualise `meta.json` with [`esbuild-visualizer`](https://www.npmjs.com/package/esbuild-visualizer)

```sh
esbuild-visualizer --metadata ./meta.json
```

## The current behavior

When using the `renderToString` method in a file that is bundled, the following files are included in the bundle.

- `react-dom-server-legacy.node.production.min.js`
- `react-dom-server.node.production.min.js`
- `react-dom-server.node.development.js`
- `react-dom-server-legacy.node.development.js`
- `react-dom.production.min.js`
- `react-dom.development.js`

## The expected behavior

Only one instance of `react-dom` and `react-dom-server` should be included in the bundle.

Note there is some reference to a legacy dom server in `react/server.node.js` which maybe causing this issue:

https://github.com/facebook/react/blob/main/packages/react-dom/server.node.js#L15

**Comment by eps1lon** [comment]
React packages are not shipped as ES modules so tree-shaking is expected to not work. As far as I can tell from your screenshot there is only one instance of the `react-dom` module included.

Though production and development versions being bundled is defintiely off. However, it's unclear where the issue lies. 

Could you check what other bundlers (e.g. Webpack or Rollup) produce? If they don't have similar issues I recommend filing an issue against esbuild instead.

**Comment by mxro** [comment]
Will do some experiments with the different bundlers on the weekend!

**Comment by mxro** [comment]
Created a sample project to test the differences between `esbuild` and `webpack`: [react-server-side-bundling](https://github.com/mxro/react-server-side-bundling)

Looks like there is some deviation in behaviour between `webpack` and `esbuild` for which I raised the above issue in the `esbuild` project.

Maybe good to leave this issue open in case there are any changes required on the React side.

**Comment by mxro** [comment]
Got the solution for this via @hyrious in the issue raised in the esbuild project.

It seems the efficient bundling of React with esbuild requires that the `process.env.NODE_ENV` variable is set to `"production"` and this can be achieved using the [define](https://esbuild.github.io/api/#define) option.

```
define: { 'process.env.NODE_ENV': '"production"' }
```

Using the build API the following configuration will yield an optimised bundle with the size of 84 kb:

```javascript
const res = await esbuild.build({
    entryPoints: ['./index.jsx'],
    bundle: true,
    minify: true,
    platform: 'node',
    format: 'cjs',
    treeShaking: true,
    define: {
      'process.env.NODE_ENV': '"production"'
    },
    target: 'node16.0',
    metafile: true,
    outfile: './dist/bundle.js',
    write: true,
  });
```
