### ISSUE TITLE
Heading instead of Header in React Beta Docs

### ISSUE THREAD

**Issue by Dinomouse** [facebook/react#24858]
Hi,

Just noticed as I am going through the beta docs (link: https://beta.reactjs.org/learn/passing-data-deeply-with-context) that a word should be Heading and not Header on point 2 in the screenshot and left me a bit confused. No worries if I have misunderstood this but would appreciate if you could amend.

Thanks

A
<img width="1019" alt="Screenshot 2022-07-06 at 11 26 51" src="https://user-images.githubusercontent.com/103888510/177530200-98c5a3ad-d65a-4184-a725-35c71d5124fe.png">

**Comment by harish-sethuraman** [comment]
Would you like to send a PR(https://github.com/reactjs/reactjs.org) to fix it? The website is inside the beta directory of the repo.

**Comment by sunil-sharma-999** [comment]
@Dinomouse 

Made a pull request for this issue at [https://github.com/reactjs/reactjs.org/pull/4795](https://github.com/reactjs/reactjs.org/pull/4795)

**Comment by Dinomouse** [comment]
Amazing, thank you both. I am just a trainee developer, so not quite sure how to submit pull requests yet!

**Comment by sunil-sharma-999** [comment]
@Dinomouse 

Me too. That's why i started with doing pull requests for mistakes in docs. 

There was a repo to practice pull request but I can't find it. You can try it on your own repo tho.

**Comment by iRealNirmal** [comment]
Can we close this issue ?
