### ISSUE TITLE
Hydration mismatch error: suggestion to include mismatch details in production error message

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react#24850]
After upgrading to React 18 at Unsplash, we saw lots of hydration mismatch errors in production. This was not surprising because [React now logs these as errors whereas before they were development-only warnings](https://github.com/reactjs/rfcs/blob/main/text/0215-server-errors-in-react-18.md).

However, when we looked at the errors in Sentry, there was no information in the error message to help us reproduce the problem. It seemed that the mismatches only occurred in very specific circumstances.

React does log this useful information but unfortunately it's only logged in the development build:

![image](https://user-images.githubusercontent.com/921609/176861636-3b87d281-cec4-4285-bd07-f0b00a8112d9.png)

https://github.com/facebook/react/blob/229c86af07302d40b70c41de18106f80fe89836c/packages/react-dom/src/client/ReactDOMComponent.js#L234-L248

We made a small patch to `react-dom` to add the same information to the production error message. This made it easy to see that the issue was because our date formatting produced different results depending on the user's time zone:

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/921609/177387744-5a0a5924-af38-497e-8e2f-6445f40bad02.png">

I would like to suggest that this information is included in the production error message—presumably this would be useful debugging information for others React users.

Related discussion: https://github.com/facebook/react/issues/11189

**Comment by remorses** [comment]
bump
