### ISSUE TITLE
Animation docs unclear

### ISSUE THREAD

**Issue by appsforartists** [facebook/react#2485]
The [Animation docs](http://facebook.github.io/react/docs/animation.html) try to explain that `<CSSTransitionGroup>` will only transition _new_ children (e.g. won't work on the initial render); however, the examples don't make that clear.  Moving `CSSTransitionGroup` from the `return` statement to inside a `map` call distracts from the explanation; moreover, it's not clearly said that the transition applies only to *new* items - not the initial items.

I need to play with CSSTransitionGroup before I'll feel comfortable contributing to the docs on it, so don't expect a PR just yet.  :stuck_out_tongue_winking_eye:

**Comment by spicyj** [comment]
Trying to clean up issues so I'll close this out but I'd take a PR to clarify.
