### ISSUE TITLE
Notes on CSSTransitionGroup

### ISSUE THREAD

**Issue by appsforartists** [facebook/react#2486]
After chatting with @leebyron and @zpao, I intend to experiment with CSSTransitionGroup and see how it can be improved.  I'm using this issue as a scratchpad to keep track of those thoughts (and eventually build out a PR).

**Comment by spicyj** [comment]
Closing this out as it's not super actionable, but #2512 added an "appear" phase.

**Comment by appsforartists** [comment]
No worries.  I forgot this was here (and stopped caring as JS styling has become more supported).  Thanks @spicyj.

**Comment by spicyj** [comment]
Me too. :) Just going through issues today.
