### ISSUE TITLE
[DevTools Bug] Cannot remove node "1390" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by OfficielSalah** [facebook/react#24874]
### Website or app

https://github.com/OfficielSalah/marsamaroc

### Repro steps

1. create account
2. redirect to verify email page
3. copy otp from email
4. paste it in email page
5. redirect login
6. keep redirecting between login page and verify email page

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.24.7-7f673317f

### Error message (automated)

Cannot remove node "1390" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26516:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24434:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24603:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54566:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by mondaychen** [comment]
Hi! Looks like the repo is a private one. Is it possible to create a minimal repro that we can use?

**Comment by mondaychen** [comment]
I'll close it for now. If you still need help and can provide for more information for us to look into, feel free to reopen
