### ISSUE TITLE
Bug: Unsupported Bridge operation "0" using both react-devtools and Flipper

### ISSUE THREAD

**Issue by QuangBinhDinh** [facebook/react#24905]
Today I installed the latest version of Flipper(0.135.0) with DevTools version 4.24.3. When debug my app this error appeared 

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/43164997/178552808-67f0b5c9-964c-4ea3-a838-e56985fae799.png">

I try to install  `react-devtools-core` to my project with the same version as DevTools  specified in Flipper ( hopefully think this will fix error ), but still don't. Then I try to install globally the React DevTools with this command `npm i -g react-dev-tools@4.24.3`, but it still have the error above when debugging app.

Then I have to downgrade both version of `react-devtools-core` and  global DevTools to 4.19.0 to have my DevTools run without error . I wonder if I can download Flipper which has this older version . Or if not, how can I fix the current version ?

React version: 18.1.0

## Steps To Reproduce

1.   Install Flipper latest version (0.135.0) via Homebrew
2.  Install `react-devtools-core` version 4.24.3  to my project----> Error appear
3.   Install React Devtools globally version 4.24.3 ----> Error still appear

**Comment by lunaruan** [comment]
Hey! How did you install `react-devtools-core` to your project?

**Comment by QuangBinhDinh** [comment]
@lunaruan I just run this command `npm i react-devtools-core@4.24.3` at my root project folder. I also do same with the older version.

**Comment by QuangBinhDinh** [comment]
@lunaruan  Any update on this error ? Or can you tell me which Flipper version is compatible with my current `react-devtools-core` version ?
