### ISSUE TITLE
fix: remove useless line.

### ISSUE THREAD

**Issue by jiashuai1002** [facebook/react#24911]
https://github.com/facebook/react/blob/7a4336c4040bb26d8fe143f96d842acae4c728b5/packages/react-reconciler/src/ReactFiberHooks.old.js#L684

**Comment by pierrybos** [comment]
this is a .old.js, this file is really used? I´m asking becouse really dont know abour this.

**Comment by poojavirgo** [comment]
Hi , Is this issue is open , i want to work on it.

**Comment by wegi8** [comment]
This problem has been fixed in a pr #24912

**Comment by pierrybos** [comment]
Oh, im looking for things for contribute too
Pierry Bos


Em qua., 13 de jul. de 2022 às 04:38, wegi8 ***@***.***>
escreveu:

**Comment by wegi8** [comment]
@pierrybos haha, maybe there are other opportunities for contribution waiting for you.

**Comment by rickhanlonii** [comment]
Why is this line useless?
