### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by HanShuai-me** [facebook/react#24927]
In strict mode useEffect is executed twice with empty dependencies
[![Edit objective-kirch-mcmyi1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-kirch-mcmyi1?fontsize=14&hidenavigation=1&theme=dark)

React version:18.2

## Steps To Reproduce

1. run project
2. The console prints the result twice

**Comment by RakeshPotnuru** [comment]
@HanShuai-me 
It is expected behavior. In development-mode component gets rendered twice even if the dependency array is empty.
