### ISSUE TITLE
Bug: Cannot read property 'useState' of null

### ISSUE THREAD

**Issue by haikyuu** [facebook/react#24928]
React version: 18.2

## Steps To Reproduce

1. Install a library that doesn't support React 18 (e.g react-router-dom@5.3.3)
2. Try to use useState in a component

Link to code example: https://scrimba.com/scrim/co257466ea4774401eb77c8a6

Note that you can pause the scrim ("video") to edit code and see the result by yourself.

## The current behavior
Crashes without a helpful error message

## The expected behavior
Should display a helpful error message.

This issue was reported before but closed because of lack of reproduction code https://github.com/facebook/react/issues/24774  and https://github.com/facebook/react/issues/24658

**Comment by snowinmars** [comment]
I have a bug with same error message, but all the libraries use react18. I'll describe an architecture and [here is a link to an example](https://github.com/snowinmars/react-useState-null-example). Can you take a look, does it relative to the issue?

#### Arch

So, I have react18, webpack5, umd. There are several projects that linked together as [local delendencies](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#local-paths). 

I link projects using `/dist` folder. I'm not really sure about it, but I decided to use small exports instead of linking to `/src` to save hard drive space.

I'm not really sure how webpack-es6 tree-shaking works, but I decided to create a bundle per source file instead of creating bundle per project. Just, well, it seems that webpack will understand it, probably. So, there is no `/dist/index.js` file, but a lot of `/dist/**/*.(js|d.ts)` files to import.

##### Projects

1. `webpack` - build-only utilites, builds as `webpack.target = 'node'`, but I don't think they affect runtime.
2. `common-react` - a library with react-specific functions and components. Builds as `webpack.target = 'web'`
3. `application` - a library that renders react `<App />` component. Depends on `common-react`, builds as `webpack.target = 'web'`

If you make a change in a project, be sure to build the project using `yarn build` and run `yarn upd` in target to install the new version.

#### Run

```sh
./bootstrap.sh # it will initialize and build all the projects
cd application
yarn start
```

#### Error

There's a [react hook](https://github.com/snowinmars/react-useState-null-example/blob/master/application/src/components/AppComponent/AppComponent.tsx#L15). When the hook imports from `/application` folder, it works fine. But when I import it from `@snowinmars/common-react` project, it fails with `useObserver.ts?0fc0:122 Uncaught TypeError: Cannot read properties of null (reading 'useState')`

1. If I add `externals: {react: 'react'}` to `/common-react/webpack.config.js`, hook works. But it's a hack.
2. There was a build misconfiguration, when `/common-react/dist/hooks/useRequest.js` bundled to 430Kb file due to it was binded with whole react. Now it doesn't - all exported files are pretty small.

So...here we are. If you need any further details - just ask)

**Comment by Sathishkumarcbre** [comment]
I too getting similar error, when I'm pointing my local library in react application.

"devDependencies": { 
"@emerald/reactmaterial": "file:../emerald.reactmaterial/dist/emerald/reactmaterial",
}
![image](https://user-images.githubusercontent.com/108940398/186928102-30ec4e3c-8228-4a7a-8e35-be967874a872.png)

If Im install it from server, it works fine.

**Comment by rollsover** [comment]
This problem also occurred to me, stops package development completely. Need help!

**Comment by rollsover** [comment]
The problem is that when using local packages, `npm link` is used, which in turn copies `node_modules` (`project/node_modules/package/node_modules`), if they are deleted, the problem is solved.

**Comment by iDestin** [comment]
Would you please describe in detail how to solve this problem? Thank you very much @rollsover

**Comment by iDestin** [comment]
> The problem is that when using local packages, `npm link` is used, which in turn copies `node_modules` (`project/node_modules/package/node_modules`), if they are deleted, the problem is solved.

hi! @rollsover Thank you for your method！But if delete a node_modules it will not be possible to continue development, can you tell me how you do it?

**Comment by Kiran554** [comment]
To get rid of `npm link` you can also run something like `brazil-build uninstall library-name && brazil-build install library-name --save` before some release command , which will uninstall and install w/o any redundant node_modules inside the library-name package

**Comment by GGAlanSmithee** [comment]
Thanks for this @Kiran554 was driving me mad.

**Comment by donus3** [comment]
> The problem is that when using local packages, `npm link` is used, which in turn copies `node_modules` (`project/node_modules/package/node_modules`), if they are deleted, the problem is solved.

The workaround for me is to pack the library with `npm pack` and then install the output `library-<version>.tgz` file in the target project by `npm install library-<version>.tgz`

**Comment by inspiraluna** [comment]
I could finally solve this issue with @rollsover 's workaround. Thank you! 

> The problem is that when using local packages, npm link is used, which in turn copies node_modules (project/node_modules/package/node_modules), if they are deleted, the problem is solved.

**Comment by subhampanja2** [comment]
I am facing the same issue with my package. Please help.
I used only as simple as useState hooks in one place, and its showing the same error.  
npm i @subhampanja/easycrm

**Comment by sarahsporck** [comment]
I think this should be fixed if the corresponding dependencies set react as peer dependeny

> The problem is that when using local packages, npm link is used, which in turn copies node_modules (project/node_modules/package/node_modules), if they are deleted, the problem is solved.

**Comment by iDestin** [comment]
**The reason for this problem is that the react version in the project is inconsistent with the react version used in your package**

If you use your package in a project and a certain version of react has been installed in the project. Then you install your package in this project, and a certain version of react is also installed in your package. Then you may get this error report

## how to fix it? 

You just need to put the react dependencies from your package into the peerDependencies

### bad case
project
```json
{
  "dependencies": {
    "react": "x.x.x",
    "react-dom": "x.x.x",
    "your package": "x.x.x"
  }
}
```
your package
```json
{
  "dependencies": {
    "react": "x.x.x",
    "react-dom": "x.x.x"
  }
}
```

### good case
project
```json
{
  "dependencies": {
    "react": "x.x.x",
    "react-dom": "x.x.x",
    "your package": "x.x.x"
  }
}
```
your package
```diff
{
++  "peerDependencies": {
    "react": "x.x.x",
    "react-dom": "x.x.x"
  }
}
```
Maybe not right, but hopefully it will help you

https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by snowinmars** [comment]
@iDestin , in [my example](https://github.com/snowinmars/react-useState-null-example) react and react-dom versions are equal, but it causes the bug.

**Comment by henaharon** [comment]
Hi! For me [this helped](https://github.com/facebook/react-native/issues/32673#issuecomment-1280884078).
React have some new rules that causes the app to crash.

In my case it was
wrong way:
 useEffect(async ()=>{}) 

good way:
 useEffect(()=>{
    async function fetchData() {}
    fetchData()
 })

Also with cleanup

wrong way:
      BackHandler.addEventListener('hardwareBackPress', backAction);
      **return BackHandler.**removeEventListener('hardwareBackPress');
      
good way:
      BackHandler.addEventListener('hardwareBackPress', backAction);
      **return function cleanup() {
        BackHandler.r**emoveEventListener('hardwareBackPress');
      }; 

Good luck!

**Comment by OscarJVD** [comment]
I've the same issue. Reading this I didn't find a definitive method to solve it. I'd like to know how to solve this problem. My library was done with vite rollup react ts but the error **Cannot read property 'useState' of null** appears when I use it in my app with npm link. I understand that is a react crash between the library and the app. Please Help :(

**Comment by snowinmars** [comment]
> THE SOLUTION OF THIS ISSUE IS THIS! :) -> https://iws.io/2022/invalid-hook-multiple-react-instances

This issue is about `useObserver.ts?0fc0:122 Uncaught TypeError: Cannot read properties of null (reading 'useState')` bug. The article does not describe a fix. So it's not a solution - it's just related.

**Comment by rahulnikam2002** [comment]
Try `npm uninstall library-name` this command 1st and then `npm install library-name --save`. Hope this will work. <3

**Comment by ManuelGuerreroVana** [comment]
> if the correspo

Didn't work for me.

**Comment by guaizi149** [comment]
add this to tsconfig.json

<img width="768" alt="image" src="https://github.com/facebook/react/assets/19711638/69d8b708-5b94-41ce-a356-0df1d6f01264">

**Comment by imaaditya-stack** [comment]
> add this to tsconfig.json in your project. (if not work, delete react and react-dom in your package node_modules)
> 
> <img alt="image" width="768" src="https://user-images.githubusercontent.com/19711638/253496184-69d8b708-5b94-41ce-a356-0df1d6f01264.png">

This worked like a charm!

**Comment by GantaVenkataKousik** [comment]
Cannot read properties of null (reading 'useState')
TypeError: Cannot read properties of null (reading 'useState')
    at useState (http://localhost:3000/static/js/bundle.js:75196:25)
    at Q (http://localhost:3000/static/js/bundle.js:82555:61)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:24955:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:28239:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:29535:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:14551:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:14595:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:14652:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:34516:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33764:16)
    
    How to solve this issue!??

**Comment by GantaVenkataKousik** [comment]
Cannot read properties of null (reading 'useState')
TypeError: Cannot read properties of null (reading 'useState')
    at useState (http://localhost:3000/static/js/bundle.js:75196:25)
    at Q (http://localhost:3000/static/js/bundle.js:82555:61)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:24955:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:28239:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:29535:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:14551:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:14595:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:14652:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:34516:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33764:16)
    
    I am getting this problem often ,Intially the project was good but I am unable to understand how to solve this problem even after I have followed all the methods to solve this

**Comment by CrazyRedTime** [comment]
any updates?

**Comment by sohom2004** [comment]
> Cannot read properties of null (reading 'useState') TypeError: Cannot read properties of null (reading 'useState') at useState (http://localhost:3000/static/js/bundle.js:75196:25) at Q (http://localhost:3000/static/js/bundle.js:82555:61) at renderWithHooks (http://localhost:3000/static/js/bundle.js:24955:22) at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:28239:17) at beginWork (http://localhost:3000/static/js/bundle.js:29535:20) at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:14551:18) at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:14595:20) at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:14652:35) at beginWork$1 (http://localhost:3000/static/js/bundle.js:34516:11) at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33764:16)
> 
> ```
> I am getting this problem often ,Intially the project was good but I am unable to understand how to solve this problem even after I have followed all the methods to solve this
> ```

I'm getting the same error. I was just trying to create various routes for my project. Tried a bunch of stuff but didn't work. It keeps saying: reading usestate. But uptill now I've not even used it yet.

**Comment by sohom2004** [comment]
> > > The problem is that when using local packages, `npm link` is used, which in turn copies `node_modules` (`project/node_modules/package/node_modules`), if they are deleted, the problem is solved.
> > 
> > 
> > hi! @rollsover Thank you for your method！But if delete a node_modules it will not be possible to continue development, can you tell me how you do it?
> 
> To get rid of `npm link` you can also run something like `npm uninstall library-name && npm install library-name --save` before some release command , which will uninstall and install w/o any redundant node_modules inside the library-name package

Can you elaborate a bit, or give a sample code please? I still didn't get that properly. :)

**Comment by sohom2004** [comment]
import React from 'react';
import ReactDOM from 'react-dom/client';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

const router = createBrowserRouter([
  {
    path: '/',
    element: <App />,
  },
])

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);

reportWebVitals();

Here's the code i used. Couldn't figure out what's wrong.

**Comment by snowinmars** [comment]
@haikyuu , could you push this bug to confirmed status based on [my comment](https://github.com/facebook/react/issues/24928#issuecomment-1207347922).

**Comment by 29abhishekL** [comment]
I was also facing the same issue with storybook. So I switched storybook bundler config from **webpack** to **vite**. This has resolved my issue

**Comment by koharubiyori** [comment]
I've struggled with this issue all day and I tried everything here but nothing worked for me. At last, I solved it by updating webpack version from 5.36.2 to the latest 5.91.0.

**Comment by muhammedanaskhan** [comment]
> > The problem is that when using local packages, `npm link` is used, which in turn copies `node_modules` (`project/node_modules/package/node_modules`), if they are deleted, the problem is solved.
> 
> The workaround for me is to remove dependencies in the the package.json using prepack script and pack the library with `npm pack` and then install the output `library-<version>.tgz` file in the target project by `npm install library-<version>.tgz`

This solves the error for me, but then I have to repeat this process of replacing the .tgz file after every change in the package, can somebody find more better solutions for this

**Comment by troovi** [comment]
Adding a react alias in webpack config works for me:

    resolve: {
      alias: {
        react: path.resolve(process.cwd(), '../node_modules/react'),
      }
     }

**Comment by RaninduJay** [comment]
I'm also facing this issue in a monorepo setup. I have a shared common directory containing an auth library, which is linked to my main app inside apps. Even after deleting node_modules, removing package-lock.json, and reinstalling dependencies, the error still persists. Has anyone found a reliable fix for this?
