### ISSUE TITLE
Bug: d1 will cause domdiff, but d2 will not.

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#24934]
React version:

## Steps To Reproduce

```js
const dataList = [...Array(50000)].map(() => 1)
const d1 = <>{dataList}</>
const d2 = <div>{dataList}</div>

function Apps() {
    const [count, setCount] = useState(0)

    return (
        <div>
            <button onClick={() => setCount(count + 1)}>increase{count}</button>
            <div>{d1}</div>
            <div>{d2}</div>
        </div>
    )
}

````
click button trigger rerender,
then`d1` will cause domdiff, but `d2` will not
I wonder if this is a bug, tks

Link to code example:

**Comment by Chaitanya7666** [comment]
Hey @zhangenming. I am trying to understand this issue but I don't understand it. Could you please elaborate more about it?

**Comment by zhangenming** [comment]
https://codesandbox.io/s/wandering-breeze-jx8g89?file=/src/index.js
use devtool perfermance analyse it, you will find this code,`d1` will cause domdiff, when click button;
but d2 https://codesandbox.io/s/affectionate-zhukovsky-rutjbj different
