### ISSUE TITLE
Bug: React 18 useEffect cleanup behaves differently than in previous versions of React 

### ISSUE THREAD

**Issue by ShadiEagleGenomics** [facebook/react#24948]
Hi everyone, I'm confused about current `useEffect` cleanup behaviour. In the examples below there are a button with simple _eventListener_ binding. I've created both examples using **React 17** and **React 18 versions**. The code is almost identical (except `react-dom` binding on React app), but it seems to be that I'm missing something about new **React 18** `useEffect` cleanup. More context in the examples.

Links to code examples:

[React 17.0.1](https://codesandbox.io/s/react-17-forked-wvbxb6?file=/src/ClickOutside.js)
[React 18.2.0](https://codesandbox.io/s/react-18-forked-n8sgt9?file=/src/ClickOutside.js)

**Comment by rodrigocode4** [comment]
this is because react 18's strict mode only runs useEffect in mode a second time. But in production this behavior does not happen. the solution is to remove the Component <StrictMode/> that wraps the app

**Comment by ShadiEagleGenomics** [comment]
> this is because react 18's strict mode only runs useEffect in mode a second time. But in production this behavior does not happen. the solution is to remove the Component `<StrictMode/>` that wraps the app

https://codesandbox.io/s/react-18-forked-mxt9v5?file=/src/index.js

Removed `Strict mode` - nothing has changed.

**Comment by ShadiEagleGenomics** [comment]
found the reason of different behaviour - prioritising of events, adding useCapture = true solved the problem.
