### ISSUE TITLE
classSet uses Array.prototype.Filter

### ISSUE THREAD

**Issue by jquense** [facebook/react#2494]
super nitpick!

The [current iteration of cx](https://github.com/facebook/react/blob/master/src/vendor/stubs/cx.js#L29) makes use of `.filter` which is not mentioned as a required polyfill for older browsers. I realize the addons are not part of React proper so I am not sure it is worth noting in the "Working with Browsers" doc, but perhaps it can be mentioned in the addons or classSet docs? I'd be happy to send a PR on either method.

**Comment by chenglou** [comment]
Since `classSet` is getting deprecated (#2910) I'm closing this. The new version (which doesn't require filter) lives at https://github.com/petehunt/react-classset
