### ISSUE TITLE
Bug: React typescript [AnchorHTMLAttributes]

### ISSUE THREAD

**Issue by zephire1** [facebook/react#24952]
The <a> tag is missing the "name" property, which does not allow you to create anchors

React version: 18.2.0

## Steps To Reproduce

1. Create typescript app
2. Open <a> tag
3. Add name attribute

## Screenshots
![Screenshot](https://i.imgur.com/3zWMpJr.jpg)
![Screenshot](https://i.imgur.com/TSv1nbG.jpg)

## The current behavior
Error that the attribute name of the link is not put on

## The expected behavior
Ability to add "name" attribute to a link

**Comment by eps1lon** [comment]
Thank you for finding this. It's related to `@types/react` and should therefore be opened against https://github.com/DefinitelyTyped/DefinitelyTyped/. 

Though `name` is not supported in HTML 4 so you should make sure your target browsers actually support it. You're very likely better off using the `id` attribute instead.
