### ISSUE TITLE
Bug: calling dispatchEvent on a React element only triggers the event's capture phase

### ISSUE THREAD

**Issue by chandlerprall** [facebook/react#24957]
React version: 17.0.2, 18.2.0

## Steps To Reproduce

1. mount a React application with two elements
2. first element listens for `keyDown` and via dispatchEvent 'replays' the event to the second element
3. second element listens for `keyDown` and `keyDownCapture`

Link to code example:
* [addEventListener - works as expected](https://codesandbox.io/s/adoring-https-xc99wx?file=/src/App.js)
* [React event listeners - only capture fires](https://codesandbox.io/s/agitated-nobel-zzqh9v?file=/src/App.js)

## The current behavior

When calling `dispatchEvent` on the second input, only the capture event listener fires

## The expected behavior

Both capture and bubble phases should be handled.

I tried this with `input`, `button`, and `div[tabIndex=0]` elements and they all behave the same

**Comment by eps1lon** [comment]
Interesting that browsers still bubble the event even though you've constructed it to not bubble.

If you construct it like this, the React example works as expected:

```diff
 const event = new KeyboardEvent("keydown", {
     key: e.key,
     code: e.code,
     location: e.location,
     repeat: e.repeat,
     isComposing: e.isComposing,
     charCode: e.charCode,
     keyCode: e.keyCode,
     which: e.which,
     ctrlKey: e.ctrlKey,
     shiftKey: e.shiftKey,
     altKey: e.altKey,
     metaKey: e.metaKey,
+   bubbles: true
   });
```

Not sure if React should bubble (e.g. because that's a browser quirk) or if the current behavior is intended.

Aside: Instead of `setTimeout` you can use `flushSync` from `react-dom`:


```diff

+import { flushSync } from "react-dom";

+flushSync(() => {
   root.render(
     <StrictMode>
       <App />
     </StrictMode>
   );
+});

-// setTimeout to allow mounting
-setTimeout(() => {
 const destination = document.getElementById("destination");
 destination.addEventListener("keydown", destinationKeyDown);
 destination.addEventListener("keydown", destinationKeyDownCapture, true);
-});
```

**Comment by chandlerprall** [comment]
Well that was easy 😅 

Thank you very much, confirmed that adding `bubbles: true` to the event constructor makes event handling work as expected. Since the event is dispatched on the input itself I wouldn't expect the bubbles modifier to have an effect, but in my actual use case I do need the event to bubble up.

+1 for `flushSync`, that's great to know!
