### ISSUE TITLE
Bug: The "textarea" field is re-rendered on every the "onChange" event.

### ISSUE THREAD

**Issue by design-principles** [facebook/react#24981]
React version: 18.2.0

## Error Description

React re-renders the `textarea` field instead of just changing the content.

P.S. I added `MutationObserver` which will help to understand the problem.

## Steps To Reproduce

```jsx
export default function App() {
  const [inputValue, setInput] = useState("");
  const [textareaValue, setTextarea] = useState("");

  useEffect(() => {
    const MO = new MutationObserver((mutationList) => {
      console.log(mutationList);
    });

    MO.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: false
    });

    return () => {
      MO.disconnect();
    };
  }, []);

  return (
    <div className="App">
      This works fine.
      <br />
      <input
        value={inputValue}
        onChange={(e) => setInput(e.currentTarget.value)}
      />
      <hr />
      This does NOT work fine.
      <br />
      <textarea
        onChange={(e) => setTextarea(e.currentTarget.value)}
        value={textareaValue}
      />
    </div>
  );
}
```

Link to code example:

https://codesandbox.io/s/boring-currying-nce4qs?file=/src/App.js

**Comment by elias-soykat** [comment]
@design-principles Use `textareaValue` in useffect dependancy. tha

**Comment by design-principles** [comment]
@elias-soykat It doesn't solve the real problem! The `textarea` field is still re-rendered, you just won't see it through the console.

What if `MustationObserver` is called from another place and the `textarea` component knows nothing about it? In this case the observer will be triggered every time.

**Comment by eps1lon** [comment]
This is intentional since you have a controlled textarea whose value you change. The value is the content of the `<textarea>content</textarea>` so you get a mutation record. This is how the DOM behaves. It looks like you just want to ignore `childList` mutation records that target `textarea` elements.

**Comment by design-principles** [comment]
@eps1lon This is a strange and unexpected behavior, because when I do the same thing without React, it works fine.

**Comment by eps1lon** [comment]
> @eps1lon This is a strange and unexpected behavior, because when I do the same thing without React, it works fine.

If you'd do the same thing with React you would use an uncontrolled `textarea` i.e. not setting `value` explicitly. In that case no mutation record is created. 
If you'd do the same thing as with React you'd set `textarea.value = value` which would create a mutation record. 

React and vanilla DOM create consistent behavior.

**Comment by design-principles** [comment]
The thing is that `textarea.value = "value"` does NOT create mutation records. Who told you it does?
