### ISSUE TITLE
Bug: Cannot use 'in' operator to search for 'data' in null

### ISSUE THREAD

**Issue by kweng-stripe** [facebook/react#24989]
Issue with react-dom, consistently with Chrome 87
Cannot use 'in' operator to search for 'data' in null

In `getDataFromCustomEvent`:
    if (typeof detail === 'object' && 'data' in detail) {

The problem is that typeof null is also 'object'

React version: 17.0.2

## Steps To Reproduce
Unfortunately I cannot reproduce, but what appears to be a headless chrome87 scanner fairly consistently reproduces the issue.

**Comment by eps1lon** [comment]
> Unfortunately I cannot reproduce, but what appears to be a headless chrome87 scanner fairly consistently reproduces the issue.

Could you create a cloneable repository that has the minimal amount of code to reproduce this issue? It's hard otherwise to understand where assumptions were incorrect.

**Comment by kweng-stripe** [comment]
I'll try to gather minimal amount of code to repro, but in the meantime it's repro-able on
* https://marketplace.stripe.com
* https://connect.stripe.com/login
* https://dashboard.stripe.com/login
from Mac OS X 10.15.7 and Chrome 87.0.4280

**Comment by David46-creator** [comment]
1
