### ISSUE TITLE
Don't make mockComponent depend on Jest

### ISSUE THREAD

**Issue by emorikawa** [facebook/react#2499]
I was expecting to use `mockComponent` like this:

```
MyMockedComponentClass = React.addons.TestUtils.mockComponent(MyComponentClass);
```

https://github.com/facebook/react/blob/v0.12.0/src/test/ReactTestUtils.js#L244
But after looking at the source of `mockComponent` it requires to be passed a `Jest` mock. I already use `node-jasmine` as my test runner.

Why does this depend on Jest?

**Comment by morlay** [comment]
Seems we can use [rewire](https://github.com/jhnns/rewire) to replace the `mockComponent()` by this way: 
   
    var rewire = require('rewire');
    var MockComponent = require('./mock-component.jsx');
    var TargetComponent = rewire('./TargetComponent.jsx');
     
    TargetComponent.__set__('RequiredComponent', MockComponent);

However, we hope the `Test Helper` is not depend on all-in-one testing tool.

**Comment by roberto** [comment]
:+1:

**Comment by daegren** [comment]
:+1:

**Comment by AnthonyRinaldi** [comment]
:thumbsup:

**Comment by oveddan** [comment]
This will be equally tough to break free from `Jest` with the latest revision to ReactTestUtils.js:

https://github.com/facebook/react/blob/0.13-stable/src/test/ReactTestUtils.js#L257

The challenge of breaking free from `Jest` here really boils down to the fact that the way other mocking libraries would stub/spy on the render method uses different syntax.  For example, with `sinon`, you would use a [stub](http://sinonjs.org/docs/#stubs), and do:

```javascript
mockComponent: function(module, mockTagName) {
    mockTagName = mockTagName || module.mockTagName || "div";

    sinon.stub(module.prototype, "render", function() {
      return React.createElement(
        mockTagName,
        null,
        this.props.children
      );
    });

    return this;
  },
```

@sebmarkbage

**Comment by sebmarkbage** [comment]
`mockComponent` is legacy and is not needed by Jest anymore really.

**Comment by koba04** [comment]
Is there any plan to remove `mockComponent`?

**Comment by maksad** [comment]
@oveddan :+1: works perfectly

**Comment by sebmarkbage** [comment]
Our preferred way of testing React is now using shallow rendering. http://facebook.github.io/react/docs/test-utils.html#shallow-rendering

This doesn't suffer from the need to mock your components, and even if you do it doesn't do anything.

**Comment by jalebi** [comment]
This is very useful. But according to the docs it is still an experimental feature. Is the docs going to be changed soon?

Date: Wed, 10 Jun 2015 08:37:22 -0700

**Comment by carpeliam** [comment]
We'll investigate shallow rendering - we were a little surprised to find Jest dependencies in React's test utils. Please either document the dependency or (much preferred please) don't depend on Jest. We believe that there are still cases where shallow rendering isn't appropriate and it'd be great to have some guidance on how best to mock components in this case, React's testing page would be the clear place to explain this.

**Comment by gaearon** [comment]
Closing in favor of https://github.com/facebook/react/issues/11019.
