### ISSUE TITLE
Stop Using Internals in ReactMultiChildReconcile-test

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2500]
This test reaches into internals by going through ReactInstanceMap which is now the only way to get to internals.

It should be possible to test the observable effect of failing this test without testing the internals of `_renderedChildren`.

(We still have other tests that also reach into internals, primarily around life-cycle state.)

**Comment by aweary** [comment]
This was resolved by https://github.com/facebook/react/commit/c3310d3e326d241ec42e3db34586ce3d01cf554c
