### ISSUE TITLE
Bug: with `react 18.2.0` `react-refresh` runtime error, unable to start the project

### ISSUE THREAD

**Issue by suressk** [facebook/react#25019]
**According to the error message, I found that when `injectIntoGlobalHook` function running, `hook.renderers` is `undefined` will make this error!**

React version: 

`react: 18.2.0`
`react-dom: 18.2.0`

## Steps To Reproduce

1. use command `pnpm create vite` or `npx create-react-app react-pro` to create a react project
2. then startup it

The error message:

![react-refresh-error](https://i.postimg.cc/NjtCcXXQ/react-error.png)

## The current behavior

The simple demo project cannot be activated.

**Comment by eddychu** [comment]
@suressk I've tested on my local machine, showing no error. Could it be that your browser's react developer tools extension messing things up? Maybe try disable it and then try again?

**Comment by suressk** [comment]
> @suressk I've tested on my local machine, showing no error. Could it be that your browser's react developer tools extension messing things up? Maybe try disable it and then try again?

Oh~~~~, yep! The error went away when I disabled it.

My browser's `React Developer Tools` version is `3.4.2`, but it seems to be the latest released version. I'll try to update the `React Developer Tools`

Thanks for your anwser 🙇‍♂️

**Comment by qiufeihong2018** [comment]
Thanks
