### ISSUE TITLE
Bug: useSyncExternalStore subscribes too late in Suspense

### ISSUE THREAD

**Issue by roblan** [facebook/react#25039]
React version: 18.2.0

## Steps To Reproduce

1. Use useSyncExternalStore in component that is inside Suspense
2. Render React.lazy component in the same Suspense 
3. Change external store value (that affects rendered components) before Suspense render all components
4. Suspense is still waiting for 'outdated' component

Link to code example:
https://codesandbox.io/s/youthful-cerf-pv5rr0

## The current behavior
useSyncExternalStore in Suspense subscribes when component is rendered (after suspense ends), which may lead to unnecessary delays

## The expected behavior
useSyncExternalStore should subscribe to changes event before component is rendered in suspense

**Comment by TalhaASiddiqi** [comment]
@acdlite Hey are there any updates on this. We are currently in the process of moving to `<Suspense>` to solve high tbt from hydration. This behavior contrasts that of other state apis (`Context` and `useState`) where the hydration switches to blocking mode when any state update occurs. If there isnt a plan to move this api to that behavior aswell, we can safetly adopt this across our app to fully utilize Suspense
