### ISSUE TITLE
useSyncExternalStoreWithSelector not take into account the snapshot of mutability

### ISSUE THREAD

**Issue by cqh963852** [facebook/react#25036]
https://github.com/facebook/react/blob/9fcaf88d58cfd942e2fdd303ae8291dbf4828969/packages/use-sync-external-store/src/useSyncExternalStoreWithSelector.js#L70-L91

Line 73 doesn't take into account the snapshot of mutability.

While use yjs's YDoc as a External Store.
```
const useYSelector = <Result>(
  selector: (store: Doc | null) => Result,
  options?: {
  }
) => {
  const yDoc = useYDoc();

  return useSyncExternalStoreWithSelector(
    (onStoreChange) => {
      const listener = (value: any) => {
        onStoreChange();
      };
      yDoc?.on("update", listener);
      return () => {
        yDoc?.off("update", listener);
      };
    },
    () => yDoc,
    () => yDoc,
    selector
  );
};
```

Since YDoc is mutable, under the judgment of line 73, it will directly return a prevSelection

**Comment by cqh963852** [comment]
after remove line 73. it goes error.😥
![image](https://user-images.githubusercontent.com/17702287/182748137-7fcb7f78-d4fc-4a33-9f85-fea7fb40db4c.png)

**Comment by cqh963852** [comment]
Is useSyncExternalStoreWithSelector only support immutable store?

**Comment by markerikson** [comment]
@cqh963852 : 

With the earlier `useMutableSource` API that was abandoned, I think I remember seeing a suggestion of having a callback that returned a "version" counter value.  

I think you'd need to return the version counter as the "snapshot", but then have the selector return values from the object, and maybe provide a custom `isEqual` function as well?

**Comment by eps1lon** [comment]
I thought about this as well but it seems like snaphot mutability is not supported (which makes sense considering what "snapshot" means).

But now you can't really return a meaningful selection unless every interesting slice has a "version" field.

I wonder if it wouldn't make sense to apply `isEqual` to the snapshot instead of the selection.

Alternatively, maybe try returning a new object from `getSnapshot` and rely on `selector` to take care of memoization:

```js
  return useSyncExternalStoreWithSelector(
    (onStoreChange) => {
      const listener = (value: any) => {
        onStoreChange();
      };
      yDoc?.on("update", listener);
      return () => {
        yDoc?.off("update", listener);
      };
    },
    () => ({yDoc}),
    () => ({yDoc}),
    ({ yDoc }) => selector(ydoc)
  );
```

@markerikson Is redux's `store.getState()` always returning a new object if the store has changed?

**Comment by markerikson** [comment]
@markerikson Redux requires that you do immutable updates, so yes, every time an action is dispatched and the state is updated, the root `state` value _should_ be a new reference (unless your app is completely broken).
