### ISSUE TITLE
Dependency Tree Error while installing [react-top-loading-bar]

### ISSUE THREAD

**Issue by irtaza9** [facebook/react#25034]
**I am getting this type of error while installing the different packages using npm. I don't want to install those packages by doing --force or anything else. This is critical as it is I am in between development of my project. Does anyone help me to resolve this issue?** 

**node --version - 16.16.0
npm --version - 8.11.0**

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nims@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
**npm ERR! peer react@"^16 || ^17" from react-top-loading-bar@2.1.0**
npm ERR! node_modules/react-top-loading-bar

**Comment by irtaza9** [comment]
Thank you so much for responding on my question. Hope so this problem will be solved in future releases of react,

**Comment by surajsinghgore** [comment]
> **I am getting this type of error while installing the different packages using npm. I don't want to install those packages by doing --force or anything else. This is critical as it is I am in between development of my project. Does anyone help me to resolve this issue?**
> 
> **node --version - 16.16.0 npm --version - 8.11.0**
> 
> npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: nims@0.1.0 npm ERR! Found: react@18.2.0 npm ERR! node_modules/react npm ERR! react@"^18.2.0" from the root project npm ERR! npm ERR! Could not resolve dependency: **npm ERR! peer react@"^16 || ^17" from react-top-loading-bar@2.1.0** npm ERR! node_modules/react-top-loading-bar

I also facing the similiar problem
