### ISSUE TITLE
[react-test-renderer] StrictMode seems not to work in tests

### ISSUE THREAD

**Issue by paol-imi** [facebook/react#25032]
`StrictMode` seems not to work when testing with `react-test-renderer`.

```tsx
import { create, act } from "react-test-renderer";

// This...
act(() => {
  const options = { 
    unstable_isConcurrent: true, 
    unstable_strictMode: true 
  };

  create(
    <StrictMode>
      <App />
    </StrictMode>,
    options
  );
});

// ...Seems to be equivalent to this.
act(() => {
  create(<App />);
});
```

React version 18.0.2
Codesandbox [**link**](https://codesandbox.io/s/strict-mode-test-5c79xd?file=/src/strictMode.test.tsx)

**Comment by eps1lon** [comment]
What specifically isn't working? E.g. double rendering, double effects, double state initialisers, deprecation warning etc?

**Comment by paol-imi** [comment]
I have only tested double rendering and double effects in the [Codesandbox](https://codesandbox.io/s/strict-mode-test-5c79xd?file=/src/strictMode.test.tsx). I suspect it's a setup issue with react-test-render rather than a StrictMode bug.
