### ISSUE TITLE
Bug: TBT of website increased after migrating to react 18

### ISSUE THREAD

**Issue by sachTyagi** [facebook/react#25048]
After upgrading to react18 total blocking time of website has been increased as per the reports of lighthouse. 
url used to check performance: https://pagespeed.web.dev/
Following packages were updated to latest:
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-redux": "^8.0.2",

React version: 18.2.0

## Steps To Reproduce

1. Update the above mentioned packages to latest.
2. Use react new hydrateRoot api

Link to code example:

Attaching screenshots for performance analysis:

react18:
<img width="960" alt="Screenshot 2022-08-04 at 5 16 58 PM" src="https://user-images.githubusercontent.com/13482825/183050784-3dafc59e-da18-4e13-a83d-fe4886699104.png">
<img width="960" alt="Screenshot 2022-08-04 at 5 17 09 PM" src="https://user-images.githubusercontent.com/13482825/183050815-c70256d2-2c8d-4c83-94cb-996fe48dfbfd.png">
<img width="1089" alt="Screenshot 2022-08-04 at 5 19 07 PM" src="https://user-images.githubusercontent.com/13482825/183050823-5fa56c28-0a18-4e0a-9929-9699b1cbef7f.png">

react17:

<img width="1088" alt="Screenshot 2022-08-04 at 5 19 48 PM" src="https://user-images.githubusercontent.com/13482825/183050871-6be35d16-1cfe-4d0d-b231-bc0a048bd536.png">
<img width="961" alt="Screenshot 2022-08-04 at 5 20 33 PM" src="https://user-images.githubusercontent.com/13482825/183050905-3d350412-a880-4004-a4a5-765e38c60744.png">
<img width="963" alt="Screenshot 2022-08-04 at 5 20 41 PM" src="https://user-images.githubusercontent.com/13482825/183050924-80439b00-839c-439f-9733-d841d35cf401.png">

**Comment by gaearon** [comment]
We can’t help or guess without a complete reproducing example.

**Comment by Mayank-sudo** [comment]
it does,t work if i didn,t get full reproducing example

**Comment by alanmoo** [comment]
FWIW Our site saw this too. It's an entirely client-side rendered application. Some core pieces of it are React Router, Apollo, Final Form, Redux, and deep in our component library is JSS (which I'm trying to remove). I'm posting this mainly in the hope that someone else will see this and recognize a commonality, as this issue was the top result on Google.
![image](https://user-images.githubusercontent.com/1682681/221201577-bd4f2f6f-03eb-4889-aad1-4e4b21d0f8f9.png)

**Comment by gaearon** [comment]
Do you have a live site I could debug?

**Comment by gaearon** [comment]
@sachTyagi Same question to you. I only just realized that there's a URL in your report. Can you deploy the two versions on two domains side by side again? Then I could dig into this.

**Comment by GRboss** [comment]
Hi all. So what happened? What was the root cause?

**Comment by shailesh108** [comment]
We are also facing the same issue, and i have noticed that framework.js is taking much time. also it's random sometime it takes less and sometimes it too high
![PageSpeed-Insights (9)](https://github.com/facebook/react/assets/16475247/5ef2f2a3-89ec-46cb-bc2c-a7fc57055003)

"react": "^18.2.0",
"react-dom": "^18.2.0",

also we are using it with Nextjs 14.0.0
