### ISSUE TITLE
Bug: Functions in initial state keep executing when updating state

### ISSUE THREAD

**Issue by Whitefox98** [facebook/react#25047]
React version: 18.0.0 / 18.1.0

## Steps To Reproduce

1. Create an state which calls a function for get initial state, add to this function a console.log()
2. Update the state with setState
3. You will see that this function is executing everytime that you update state
4. Happens with and without StrictMode, with plain states (like numbers, strings) and also with objects.
5. Also happens if you separate initialValue in a variable which calls a function and then use it inside state

Link to code example: https://codesandbox.io/s/charming-grothendieck-cg1ev0?file=/src/App.js
Open console and check console.logs

## The current behavior
The function is executed as many times as the state is updated, this could be a performance problem for the application and it is annoying to debug some things.

## The expected behavior
The function should only be called when the state is initialized

**Comment by VanTanev** [comment]
You are passing the result of the function into `useState()`:

```ts
const [myState, setMyState] = useState(getStarterItem());
```

You must pass the function itself:
```ts
const [myState, setMyState] = useState(getStarterItem);
```

Relevant part of the docs: https://reactjs.org/docs/hooks-faq.html#should-i-use-one-or-many-state-variables:~:text=To%20avoid%20re%2Dcreating%20the%20ignored%20initial%20state%2C%20we%20can%20pass%20a%20function%20to%20useState%3A

**Comment by Whitefox98** [comment]
> You are passing the result of calling the function during render into `useState()`:
> 
> ```ts
> const [myState, setMyState] = useState(getStarterItem());
> ```
> 
> You must pass the function itself:
> 
> ```ts
> const [myState, setMyState] = useState(getStarterItem);
> ```
> 
> Relevant part of the docs: https://reactjs.org/docs/hooks-faq.html#should-i-use-one-or-many-state-variables:~:text=To%20avoid%20re%2Dcreating%20the%20ignored%20initial%20state%2C%20we%20can%20pass%20a%20function%20to%20useState%3A

True, it works, and for pass props to functions?
