### ISSUE TITLE
Bug: React removes all line breaks

### ISSUE THREAD

**Issue by rnarkk** [facebook/react#25051]
This behaviour makes React difficult for the use of HTML(JSX)-based document/knowledge base management. To workaround this, for example, MDX converts every new lines to `{“\n”}`s. This behaviour is stated in the official documents https://reactjs.org/docs/jsx-in-depth.html#string-literals-1 but I believe this can be avoided, say, for spans between beginning and end of each text.

**Comment by IamGuneet** [comment]
@rnarkk hi, I d like to work on this issue, could you give me a bit more information about what needs to be done?

**Comment by rnarkk** [comment]
@IamGuneet Hi.

I want this

```jsx
<div>

  This is a text 1.
  This includes a new line.
  <div></div>
  
  Another text that

  includes blank line. 
 
</div>
```

to be this

```jsx
<div>
  This is a text 1.
  This includes a new line.
  <div></div>
  Another text that

  includes blank line. 
</div>
```

.

**Comment by IamGuneet** [comment]
@rnarkk okay, could you link the file, Can I work on it?

**Comment by barrezuetai** [comment]
Pretty sure that's the intended behavior. Works best that way since you want your text to be responsive to everyone's different screen sizes. New lines that look good on your phone won't look good on your UHD monitor.

**Comment by rnarkk** [comment]
@barrezuetai Thanks for your advice!
