### ISSUE TITLE
Bug: react-devtools crash at start

### ISSUE THREAD

**Issue by Jumbostan** [facebook/react#25056]
I am trying to debug a React Native app with react-devtools but when I launch it, it shows a blank window for about 2 seconds an closes. It doesn't show any error in the console.
I tried with npx, npm global and yarn

I tried several versions 4.x.x and the result is the same
It work with versions 3.x.x but can't connect with React Native

SO: Ubuntu 22.04.1
node :16.16.0
npm: 8.11.0

**Comment by lunaruan** [comment]
Hey! What versions of React Native and React DevTools are you using?

**Comment by Jumbostan** [comment]
> Hey! What versions of React Native and React DevTools are you using?

Hi, I'm using react-devtools 4.25.0, RN 0.69.4.
I also tried in a virtual machine with Ubuntu 22.04.1 in a different host and the error is the same... react-devtools crash after a couple of seconds

**Comment by Majkipl27** [comment]
Use arch btw it will work

**Comment by tom-james-watson** [comment]
Also seeing the same issue in Ubuntu 22.04.

**Comment by hab12335** [comment]
> Use arch btw it will work

same issue on arch

**Comment by geeksville** [comment]
same on ubuntu 22.10

**Comment by geeksville** [comment]
Great workaround (recommended by @TrainDoctor) that fixed things for me:

react-devtools --no-sandbox

**Comment by JoshDesmond** [comment]
I had the same issue on 

- Ubuntu 22.04.2
- react-native: 0.70.6
- react-devtools@4.27.2

The fix above of using `react-devtools --no-sandbox` worked for me. (Thanks!)
