### ISSUE TITLE
Bug: useState inside pure JavaScript/TypeScript class violates rules of hooks

### ISSUE THREAD

**Issue by pashvin** [facebook/react#25061]
React version: 18.x

## Steps To Reproduce

1. use the following code in React project 
2. see a compilation error

Link to code example:

```
class ThemeService {
  private _theme: any;
  private _setTheme: any;
  constructor() {
    const [theme, setTheme] = useState("Red");
    this._theme = theme;
    this._setTheme = setTheme;
  }

  get theme(): string {
    return this._theme;
  }

  ToggleTheme() {
    this._setTheme(this._theme === "Red" ? "Blue" : "Red");
  }
}

```

## The current behavior
above usage generates the following compilation error

ERROR in [eslint] 
src/App.tsx
  Line 8:31:  React Hook "useState" cannot be called in a class component. React Hooks must be called in a React function component or a custom React Hook function

## The expected behavior
I understand that the class Component has diff state management so "useState" is not allowed inside the class-based react component but I am not sure why usage inside the pure class is restricted.

**Comment by pashvin** [comment]
I was able to bypass the error using **// eslint-disable-next-line** and then now my code started working.
Here is the sample code link - https://github.com/pashvin/sample/tree/main/react-services/counter-app/src

**Comment by markerikson** [comment]
This is most definitely _not_ a "bug". 

**This class code literally _will not work_, ever!**

React's implementation _only_ allows hook calls inside function components. Nowhere else.  Not class components, not classes, not random functions. You can _only_ call them in a function component, period.

I'd suggest reading and watching https://www.swyx.io/hooks/ to understand how and why hooks are implemented this way.

**Comment by pashvin** [comment]
But why do we want to limit it or break it which is already working? 

See SolidJS and see how things are less restrictive. 

Even if we don't compare to SolidJs, then the regular class can be considered as just a bundle of one or more attributes so in the normal case also if I have 3-4 useState under the functional component, then to make code more readable I should be able to make higher level class bundle all useState attributes inside that and use that class instance so in that case instance of useState is in class instead of direct functional component and that is the only difference

I think React should adopt newer concepts and make it more flexible instead of just reasoning why it can't be done and avoid losing popularity against a new framework that can allow it.

**Comment by markerikson** [comment]
@pashvin React isn't Solid.  Different frameworks, different design decisions.

_Could_ the React team make hooks work inside of class components? Probably.

_Will_ they? No. It's a 100% intentional design decision to _not_ do that, and I can guarantee from everything the React team has said hooks inside of class components will never be added.

On top of that, _neither_ hooks nor class component `this.setState` can work in a plain JS class like this, by definition.  State is stored inside React's internal "fiber" objects, not in external classes, and made available to components as part of the rendering process.

So, this isn't a bug.  You're asking for something that cannot and will not happen.

**Comment by pashvin** [comment]
Thanks for the detail and for the video which explains closers. After looking into "closers video", I thought my code is working because I am creating a singleton and it will break and mess up with the internal state as soon as I create two instances like the following but surprisingly it works so I don't know why we want to break which is working and looks like the answer is the design decision to avoid classes for simplicity. I have intermediate-level knowledge of React and can't argue much against the decision but hope if this is supported, then can open a door for diff pattern.

```
class CounterLogic {
  constructor() {
    // eslint-disable-next-line
    const [count, setCount] = React.useState(10);
    this._count = count;
    this._setCount = setCount;
  }

  count() {
    return this._count;
  }

  inc() {
    this._setCount(this._count + 1);
  }

  dec() {
    this._setCount(this._count - 1);
  }
}

const Counter = () => {
  const test = new CounterLogic();

  return (
    <div>
      <h2>Counter: {test.count()}</h2>
      <button onClick={()=>test.inc()}>Increment</button>
      <button onClick={()=>test.dec()}>Decrement</button>
    </div>
  );
}

const App = () => {

  return (
    <div>
      <Counter/>
      <Counter/>
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by markerikson** [comment]
Your "class" is _technically_ working there, but only by accident.

What matters is that **the code that calls `useState()` is running directly inside of that function component**.  That's actually how a custom hook works too:

```js
function useMyCustomHook() {
  return useState(0);
}

// later
function MyComponent() {
  const [data, setData] = useMyCustomHook()
}
```

you can wrap it as many times as you want, the important thing is that the call to `useState()` _has_ to occur as part of the top-level body of a function component.

However, **wrapping that hook call in a class is useless, even if it ends up "running" by accident**.  There's no benefit to doing so, and it's actively making things more confusing.

**Comment by pashvin** [comment]
@markerikson Ok got it. Hooks are designed to remove class complexity so why bring back classes?

I just saw that simplicity was becoming complex when we have to manage the global state using context. If I have to publish the state plus functions and also keep all those related functions in a single bundle, then that is possible (without breaking any rules) but very complex (see https://github.com/pashvin/sample/blob/main/react-context-provider/src/App.tsx) because I have to publish each function using the context.

vs. class provides an upper-level umbrella to put states and functions in a single instance and publishing class instance is easy (because I have to publish just one variable which is an instance and its states & methods are already attached with it vs publishing each method separately.) so that is the advantage of the class in this case(see- https://github.com/pashvin/sample/blob/main/react-services/counter-app/src/App.tsx). 

Anyway, I am just looking from only a developer usage perspective (trying to make more simple). Looks like you clearing saying this will not work because it is breaking Hook's fundamental usage and implementation. I trust your knowledge (as you may be able to look at it from all angles vs my knowledge is very limited) so if you think this will be not supported, then please feel free to close it

**Comment by rickhanlonii** [comment]
Closing, as @markerikson  explained, hooks are not intended to work inside classes and we don't think making them work there   is the right approach.
