### ISSUE TITLE
Bug: `preventDefault()` breaks checkboxes, they may not reflect the `checked` prop

### ISSUE THREAD

**Issue by nstepien** [facebook/react#25069]
React version: 18.2.0

## Steps To Reproduce

1. call `event.preventDefault()` in `onChange` or `onClick` handler
2. the checkbox element may not reflect the `checked={checked}` prop in some cases

Link to code example: https://codesandbox.io/s/relaxed-taussig-ypxiuo?file=/src/App.js

![Recording 2022-08-09 at 18 23 20](https://user-images.githubusercontent.com/567105/183717810-a08dc8b4-c036-497c-a8e2-806b6fba90bb.gif)

## The current behavior
I can't click on `<input type="checkbox" />` reliably anymore.
~It's preventing us from adopting React 18 in a project, as some of our tests are broken by this bug.~ We've refactored our components so we're not affected anymore, but it's still a valid bug.

## The expected behavior
React 18 should always respect the `checked={checked}` prop.

**Comment by goldmont** [comment]
Hi there,

Try `event.stopPropagation()`

**Comment by nstepien** [comment]
@goldmont this doesn't help me as I need to use `preventDefault()`

**Comment by goldmont** [comment]
Hi,

You can use both.

**Comment by nstepien** [comment]
Using both does not fix it the underlying bug in React.

**Comment by gaearon** [comment]
Could you clarify what you are trying to do by calling preventDefault in a click/change event?

Also, is the behavior different in another version? Please provide a sandbox showing the behavior you’d like to see.

**Comment by nstepien** [comment]
>Could you clarify what you are trying to do by calling preventDefault in a click/change event?

I have checkboxes in a autocompleter's dropdown list, and I want to preserve focus on the autocompleter's input as I click on items in the list.

So I have something like this (keeping it short):
```tsx
<input {...someProps} />
{/* dropdown list: */}
<div
  // This prevents clicking in the dropdown from from stealing focus from the input
  onMouseDown={event => event.preventDefault()}
  // This prevents checkbox labels from stealing focus from the input
  onClick={event => event.preventDefault()}
>
  {items.map(item => (
    <div key={item.id} onClick={() => toggleState(item.id)}>
      {/* in some cases we render something else than label+checkbox */}
      <label>
        <input type="checkbox" />
        {item.name}
      </label>
    </div>
  )}
</div>
```

>Also, is the behavior different in another version? Please provide a sandbox showing the behavior you’d like to see.

Interesting, I tried changing the codesandbox to use React 17 and I encounter the same issue.
https://codesandbox.io/s/fork-forked-32csnb?file=/src/App.js

For some reason though some of our existing tests broke in React 18, while they work fine with React 17. I don't know why, maybe something changed with `@testing-library/react`. 🤷‍♂️ 

Either way I would expect the `checked={checked}` prop to work regardless,
if I pass `true` then the checkbox should be checked,
and if I pass `false` the checkbox should be unchecked.
What do you think?

**Comment by SivaKrishna6745** [comment]
I think you are restricting the default behavior of `checkbox` by adding `preventDefault()`.

**Comment by nstepien** [comment]
@SivaKrishna6745 I'm using `preventDefault()` to prevent the default browser behavior to control focus, it should have 0 impact on React's rendering behavior.

**Comment by SivaKrishna6745** [comment]
okay. I am not sure whether this satisfies you requirement or not but you can try `return false` instead of `preventDefault()` which is also used for preventing default browser behavior.

check the source [here](https://stackoverflow.com/questions/15554640/easy-way-to-prevent-default-action-when-using-onclick-of-a-checkbox)

**Comment by nstepien** [comment]
This doesn't work with React's event handlers.
And again, this doesn't address the underlying bug in React.

**Comment by dashkin-dima** [comment]
https://codesandbox.io/s/relaxed-taussig-ypxiuo?file=/src/App.js
I think "broken in a different pattern" works correctly because a state change happens and after it happens preventDefault, You can verify this by clicking on the div and then on the input.
