### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by cardenasmh-itg** [facebook/react#25062]
### Website or app

react developer tools

### Repro steps

Open Components in Web Developer Tools

### How often does this bug happen?

Only once

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.25.0-336ac8ceb

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
emit@moz-extension://6f15f1d5-602a-4a38-8422-c9e5075b7456/build/main.js:24626:22
bridge_Bridge/this._wallUnlisten<@moz-extension://6f15f1d5-602a-4a38-8422-c9e5075b7456/build/main.js:24795:14
listener@moz-extension://6f15f1d5-602a-4a38-8422-c9e5075b7456/build/main.js:54959:41
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by milearn** [comment]
![Screenshot 2022-08-08 at 8 21 19 PM](https://user-images.githubusercontent.com/10200019/183446834-68758780-69d8-433f-b59c-07827769851e.png)

**Comment by lunaruan** [comment]
Hey! Can you check if you have multiple Devtools installed?

**Comment by kritikjain9** [comment]
Same issue on react devtools

**Comment by dmytromurashko** [comment]
The same for me

**Comment by misael282828** [comment]
![image](https://user-images.githubusercontent.com/76186050/183943243-2350b73c-1992-428f-871f-21f5d825dbb9.png)

**Comment by misael282828** [comment]
![image](https://user-images.githubusercontent.com/76186050/183943504-2b0c3d9f-e461-46ad-96ef-fcafcc05f1f3.png)

**Comment by lunaruan** [comment]
Hey all! Can you check to see if you have multiple React DevTools installed? If not, could you create a repro case and upload it here? Unfortunately we're unable to figure out the issue without one.

**Comment by provishalk** [comment]
Face same issue only in mozilla firefox, In chrome it is working fine.

**Comment by mondaychen** [comment]
Can you provide more information such as which browser and what version, and which website you are running the devtools on. Thank you!

**Comment by provishalk** [comment]
> Can you provide more information such as which browser and what version, and which website you are running the devtools on. Thank you!
browser i am using is **Firefox developer edition** version **104.0b10 (64-bit)**
I am running this on https://www.mailmodo.com/

**Comment by mondaychen** [comment]
Hi @provishalk I downloaded Firefox developer edition and it's working fine for me
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/1001890/185773285-21634947-dec6-4cf4-8554-09d6ebe05f0f.png">

Can you try disable some of your other add-ons?

**Comment by amanzrx4** [comment]
Just reinstall the extension, refresh the server, it'll work

**Comment by Noah670** [comment]
Doing a clean install fixed the issue I was having.

**Comment by lunaruan** [comment]
Seems like you all have found a fix, so closing this issue. Feel free to reopen if you're still experiencing this!

**Comment by sshakil** [comment]
would like to re-open, it's happening
