### ISSUE TITLE
[DevTools Bug] Cannot add node "7448" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by amirmalekian** [facebook/react#25081]
### Website or app

https://github.com/digita-webshop/digita-webshop-frontend/tree/develop

### Repro steps

1) npm install
2) npm start
3) inspect element
4) components tab

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.25.0-336ac8ceb

### Error message (automated)

Cannot add node "7448" because a node with that id is already in the Store.

### Error call stack (automated)

```text
emit@moz-extension://9908b50a-48f2-40b1-9532-79813e5a6947/build/main.js:24626:22
bridge_Bridge/this._wallUnlisten<@moz-extension://9908b50a-48f2-40b1-9532-79813e5a6947/build/main.js:24795:14
listener@moz-extension://9908b50a-48f2-40b1-9532-79813e5a6947/build/main.js:54959:41
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by lunaruan** [comment]
Hey! Thanks for reporting! I tried to repro this issue but unfortunately was unable to. Could you create a more reliable repro case? I'm going to close this issue, but feel free to reopen with a more reliable repro case!
