### ISSUE TITLE
Bug: Replacing a button with a new button type="submit" causes a form to be submitted without pressing the button

### ISSUE THREAD

**Issue by lukesterg** [facebook/react#25089]
React version: 18.2

## Steps To Reproduce

1. Create a button `<button type="button">`.
2. On the click even replace the button with a button of type submit `<button type="submit">`
3. The form will be submitted even though the second button was never pressed.

Link to code example: https://codesandbox.io/s/epic-feynman-wzwxyf?file=/src/App.js

## The current behavior
From the example, clicking on the button "Button of type button" incorrectly submits the form, showing the alert "submitted".

Clicking on the button "Button of type submit" shows 2 alerts: "submitted" and "submit form pressed". This shows that the form was submitted (from the button type="submit") but the onClick event did not run. 

If the button named "Button of type submit" is of type="button" then pressing "Next Page" will not submit the form. Also if the button "Button of type submit" is in a different location then the form will not be submitted.

## The expected behavior
The form should only be submitted if the button with type="submit" is pressed.

If there was something wrong with my code (such as the key property being required) I would have expected either both the form to be submitted and the onClick event to be triggered or neither to be triggered.

## Workaround

The easiest workaround I have found is to add a key property to the new button.

Another method is to make the second button appear in a different location.

**Comment by merhmood** [comment]
Actually what happen is the click event is capture by the second button and this is because react thinks they are the same button, but by adding the key property react is able to identify that they are different buttons and automatically stops the alert from capturing the click event in the second button.

**Comment by lukesterg** [comment]
Thanks @merhmood but if the click event was captured by the second button why wouldn't the onclick event fire?

**Comment by merhmood** [comment]
I went through the codes, the form onSubmit event is always trigger when a button nested in it is clicked, if you notice, when the second button is clicked, you will get two alerts, first one for the button and second one for the form onSubmit event. This is actually a javascript thing

**Comment by lukesterg** [comment]
To avoid confusion I have changed the button names in the example to make my replies flow more nicer. The first button is now **Button of type button** and the second button is now called **Button of type submit**. I will update the issue to match these changes.

I don't understand your reply there are no nested buttons and pressing the button **Button of type submit** is not demonstrating an issue and is expected to show 2 alerts.

The issue occurs when clicking the button "Button of type button" where React incorrectly submits the form. The reason for having an onClick event on **Button of type submit** is to show that React is somewhat detecting (or processing events in a particular order) which causes React to action `type="button"` but not the onClick event.

**Comment by merhmood** [comment]
![Screenshot015](https://user-images.githubusercontent.com/63869867/184350651-1b613f07-d7f8-41a7-a96f-e9bdd47b2029.jpg)

in the codes above yo have this

         form
            |
       button

the button element is inside the form element (nesting)

**Comment by merhmood** [comment]
Then refer to the previous comment on nesting

**Comment by merhmood** [comment]
React isn't incorrectly submitting the form, this because button are always treated as type submit as oppose to using input with the type submit attribute. so whenever a button is clicked the form is submitted.

**Comment by merhmood** [comment]
type submit should be used only when you are using input -> <input type="submit" />

**Comment by lukesterg** [comment]
Thank @merhmood for your responses.

I have found the reason for the issue. The issue is a combination of React's Reconciliation and browser event order. React's event Reconciliation https://reactjs.org/docs/reconciliation.html shows DOM is managed - by diffing the tree. Because a button is the same type and in the same place in the DOM, React mutates the button rather than replacing.

Looking at React's source code I can see that React uses the internal browser events. The onClick event ran first, React mutated the object and that caused the type to change. Browsers then create an event for the submit button type only after running the onClick event, this is why the form was submitting but not the onClick.

Here is a simple non-React version showing the issue:

```
<form onSubmit="alert('sumbitted')">
  <button type="button" id="btn" onClick="document.getElementById('btn').type='submit';">Change to submit</button>
</form>
```

Given how React handles mutations according to their documentation the issue was my understanding.

**Comment by merhmood** [comment]
Cool, now you know why react always request for key prop during list rendering.

**Comment by Taytay884** [comment]
@ghost
I used the workaround you mentioned, works great :)

> The easiest workaround I have found is to add a key property to the new button.

```<Button
      key={isLastStep ? 'submit' : 'next'}
</>```
