### ISSUE TITLE
Bug: inconsistent recursive setState() behavior

### ISSUE THREAD

**Issue by zeeeeby** [facebook/react#25094]
## Description
In some cases useState updater function sees an irrelevant value

React version: 16.8.0, 17.0.2, 18.0.0
## Steps To Reproduce

1. Press setCount button
2. Press setCount button again
3. See the console input

Link to code example: [codesandox example](https://codesandbox.io/s/keen-panini-sg79z3?file=/src/App.js)

## The expected behavior
First setCount prints:
> PREV  0
> RENDER 1
> effect 1
> RENDER 4
> effect 4

Second setCount prints:
> PREV 4
> RENDER 5
> effect 5
> RENDER 8
> effect 8

## The current behavior
First setCount prints:
> PREV  0
> RENDER 3
> effect 3

Second setCount prints:
> PREV 3  // (the problem: expected 4 instead of 3)
> RENDER 4
> RENDER 7
> effect 7

expected behavior can be simulated if we wrap ```add3``` call in ```setTimeout(add3, 0)```

Code:

```typescript
export default function App() {
  const [count, setCount] = useState(0);
  const [_, forceUpdate] = useState({});
  React.useEffect(() => {
    console.log("effect", count);
  }, [count]);
  console.log("RENDER", count);
  const add3 = () => setCount((p) => p + 3);
  return (
    <div className="App">
      <button onClick={() => forceUpdate({})}>force render</button>
      <button
        onClick={() => {
          setCount((p) => {
            console.log("PREV", p);
            add3();
            return p + 1;
          });
        }}
      >
        setCount
      </button>
    </div>
  );
}
```

**Comment by eps1lon** [comment]
State updater functions need to be pure i.e. they should produce the same result if invoked multiple times with the same argument. That's why state updater functions are invoked twice in StrictMode and recursive setState leads to undefined behavior.

You want to move your `add3()` call out of the state upater function:

```diff
+add3()
 setCount((p) => {
   console.log("PREV", p);
-  add3();
   return p + 1;
 });
