### ISSUE TITLE
Bug: Virtuallists/grids are flickering on scroll with react 18

### ISSUE THREAD

**Issue by mirco-s** [facebook/react#25093]
Virtual lists or grids are flickering when scrolling fast with `createRoot(root).render()`, but do not flicker when using `ReactDOM.render()`.

React version: 18.2.0

## Steps To Reproduce

1. Choose your favorite virtual-list/grid and a sufficiently big dataset
2. Render the list once with `createRoot(root).render()` and once with `ReactDOM.render()`
3. Scroll both lists/grids fast.

Gif:
![VirtualListFlicker](https://user-images.githubusercontent.com/82407507/184510712-a8d8f731-3998-4722-98d6-c3e9a37c9416.gif)
_(Tested in chrome and firefox)_

Link to code example:

[Example with a simple virtual list.](https://codesandbox.io/s/root-render-vs-dom-render-without-dependencies-londol)

[Example with a grid from react-window.](https://codesandbox.io/s/root-render-vs-dom-render-vt4vk1)

## The current behavior

Virtual lists/grids are flickering when rendered with `createRoot(root).render()`.

## The expected behavior

Same behavior as `ReactDOM.render()`.

**Comment by nstepien** [comment]
Looks like using [`flushSync`](https://reactjs.org/docs/react-dom.html#flushsync) can fix the issue in the "simple virtual list" example
```tsx
        onScroll={(e) => {
          flushSync(() => {
            setRange(calcVisibleStartAndEndIndex(e.target.scrollTop, 5));
          })
        }}
```

**Comment by Cool-Star** [comment]
same question

**Comment by rmlevangelio** [comment]
I can say that this issue still exists. Any workarounds?
