### ISSUE TITLE
Bug: onBlur event does not fire if loss of focus occurred due to element being removed by react

### ISSUE THREAD

**Issue by reubn** [facebook/react#25095]
onBlur event does not fire if loss of focus occurred due to element being removed by react under certain circumstances - behaviour is not consistent.

Link to code example 18.3.0-next-32baab38f-20220811: https://codesandbox.io/s/react-focus-bug-18-3-0-qc5tu8?file=/src/App.js
Link to code example 18.0.0-fc46dba67-20220329: https://codesandbox.io/s/react-focus-bug-18-0-0-bp6qn1?file=/src/App.js

Focus outside container:
![image](https://user-images.githubusercontent.com/4957964/184534151-55455c88-b342-4d27-9faa-b1e8a089ea2d.png)
Button has focus:
![image](https://user-images.githubusercontent.com/4957964/184534161-71722c75-9ad2-400a-ae0a-ef00ab88bda0.png)
Button clicked - resulting in react removing it from DOM ∴ focus is lost from container - but react does not fire onBlur event:
![image](https://user-images.githubusercontent.com/4957964/184534175-1bab46ba-4473-4049-b931-c4af5de6f1b1.png)

React versions: 18.3.0-next-32baab38f-20220811, 18.0.0-fc46dba67-20220329

## Steps To Reproduce

See code example

Link to code example 18.3.0-next-32baab38f-20220811: https://codesandbox.io/s/react-focus-bug-18-3-0-qc5tu8?file=/src/App.js
Link to code example 18.0.0-fc46dba67-20220329: https://codesandbox.io/s/react-focus-bug-18-0-0-bp6qn1?file=/src/App.js

## The current behaviour

- 18.3.0-next-32baab38f-20220811:
  - Chrome Dev macOS Version 105.0.5176.3:
    - Keyboard Activation: No onBlur event fires on button nor parent 
    - Mouse Activation: No onBlur event fires on button nor parent 
  - Safari macOS Version 15.4:
    - Keyboard Activation: No onBlur event fires on button nor parent 
    - Mouse Activation: onBlur event fires on button and parent 

- 18.0.0-fc46dba67-20220329:
  - Chrome Dev macOS Version 105.0.5176.3:
    - Keyboard Activation: onBlur event fires on button and parent 
    - Mouse Activation: onBlur event fires on button and parent  
  - Safari macOS Version 15.4:
    - Keyboard Activation: No onBlur event fires on button nor parent 
    - Mouse Activation: onBlur event fires on button and parent 

See code example for more details

## The expected behaviour
onBlur events fire consistently

**Comment by malikhaideraliraza** [comment]
Hi @reubn your is not with the react rather it is regarding the core HTML implementation issue. Try giving your div a tabindex.
find more details here. [tabindex doc](https://www.w3schools.com/tags/att_global_tabindex.asp) and [stackoverflow Sol](https://stackoverflow.com/questions/3656467/is-it-possible-to-focus-on-a-div-using-javascript-focus-function#:~:text=Yes%20%2D%20this%20is%20possible.)
Thanks

**Comment by reubn** [comment]
Thanks Haider,

Yeah, differences between browsers are to be expected, but if react is going to prevent the use of native onFocusIn and onFocusOut events, then the behaviour of the replacements should be consistent and stable between react versions. There is a difference in behaviour between 18.0.0 and later.

Adding a tabIndex to the div is not a workable solution. The div should not be tabbable - only the input and buttons should be.

**Comment by reubn** [comment]
Thanks @malikhaideraliraza 

Yeah, differences between browsers are to be expected, but if react is going to prevent the use of native onFocusIn and onFocusOut events, then the behaviour of the replacements should be consistent and stable between react versions. There is a difference in behaviour between 18.0.0 and later.

Adding a tabIndex to the div is not a workable solution. The div should not be tabbable - only the input and buttons should be.

**Comment by malikhaideraliraza** [comment]
yes you right 

> Thanks @malikhaideraliraza
> 
> Yeah, differences between browsers are to be expected, but if react is going to prevent the use of native onFocusIn and onFocusOut events, then the behaviour of the replacements should be consistent and stable between react versions. There is a difference in behaviour between 18.0.0 and later.
> 
> Adding a tabIndex to the div is not a workable solution. The div should not be tabbable - only the input and buttons should be.

yes you are right but actualy in dom we may have div inside another div so we need to set piriority for div for focusing (like z-index).

**Comment by reubn** [comment]
Thanks again @malikhaideraliraza 

I don't follow, but this issue does not relate to having a tabIndex on a parent. 

The div should not be focusable, and should not sit in the keyboard navigation tree. 

React's onBlur and onFocus events should bubble to the div, but the parent should not be focusable itself. 

Adding a tabIndex would make it focusable, and degrade the experience for keyboard users. This is not acceptable, is not semantic, and is not what I am asking. 

There are very few reasons to ever set tabIndex on an element. 

This is about react's reimplementation of native focus events, bubbling, and lack of consistency between browsers and react versions.

**Comment by SleighJ** [comment]
Currently experiencing this issue

**Comment by teadams** [comment]
We are having the same issue.  Is there an update please?
