### ISSUE TITLE
Bug: React Dev Tools in Firefox hide logs in strict mode not working

### ISSUE THREAD

**Issue by MariuzM** [facebook/react#25096]
In Firefox 103.0.2 setting React Dev Tools for `Hide logs during second render in strict mode` does not work. But in Chrome it does work.

**Comment by eps1lon** [comment]
What version of React and React devtools are you using?

**Comment by MariuzM** [comment]
DevTools: 4.25.0-336ac8ceb
React: 18.2.0
Vite: 3.0.7

**Comment by lunaruan** [comment]
Hey! I just tested with the versions of Firefox/DevTools/React you gave, and everything is working for me. Could you make a codesandbox repro case so we can better investigate?

**Comment by lunaruan** [comment]
Closing this issue because we can't repro, but feel free to reopen if you have a different repro case!

**Comment by MariuzM** [comment]
Hm i would not mark this completed because giving 1h is not enough for me to provide example especially difference in time zone :) 

But here is example:
https://github.com/MariuzM/react-double-log-issue

Firefox
![Screen Shot 2022-08-19 at 09 43 59](https://user-images.githubusercontent.com/36937039/185531821-6471021a-3799-4bac-b0cd-ad7c1f4b4f86.jpg)
![Screen Shot 2022-08-19 at 09 44 03](https://user-images.githubusercontent.com/36937039/185531845-e691c1c3-0fc8-4c4e-91a4-285dcb5a2fe6.jpg)

Chrome
![Screen Shot 2022-08-19 at 09 44 17](https://user-images.githubusercontent.com/36937039/185531860-6c7d8572-a776-4552-a389-339adcd75d57.jpg)
