### ISSUE TITLE
Automatically remove addEndEventListener

### ISSUE THREAD

**Issue by appsforartists** [facebook/react#2510]
ReactTransitionEvents currently contains two methods, `addEndEventListener` and `removeEndEventListener`.  In most (perhaps all) cases, the developer is going to wait for `listener` to be called `n` times (where `n` is usually `1`), and then call `removeEndEventListener`.

Let's make this nicer, changing the preamble of `addEndEventListener` to something like:

```javascript
  addEndEventListener: function(node, eventListener, stepsInTransition = 1) {
    var metaListener = (event) => {
      stepsInTransition--;

      if (stepsInTransition > 0)
        return;

      eventListener(event);

      if (stepsInTransition == 0)
        this.removeEndEventListener(node, metaListener);
    }

```

to make the event listener clean up after itself.

The real implementation is slightly more complex than that, as you'll have to keep track of the original `eventListener` to make sure `removeEndEventListener` does the right thing if it's called before `add` is done, but in principle, this seems like an improvement.

**Comment by spicyj** [comment]
ReactTransitionEvents isn't a public module so we're not particularly concerned about its API. This doesn't sound like a bug per se, so I'll close this out. Let me know if I'm misunderstanding. (Also willing to consider a pull request if you feel so inclined.)
