### ISSUE TITLE
Bug: HMR only force reinitialize current component but not reinitialize descendant components 

### ISSUE THREAD

**Issue by Dxings** [facebook/react#25126]
React version:

## Steps To Reproduce

`App Component`
```
import { useEffect } from "react";
import "./styles.css";
import { Child } from "./Child";

function App() {
  const title = "title1";

  useEffect(() => {
    console.log("init Parent", title);
  }, []);

  return (
    <div>
      <div>Parent: {title} </div>
      <Child title={title} />
    </div>
  );
}

export default App;
```
`Child Component`
```
import { useMemo } from "react";

export const Child = (props) => {
  const Title = useMemo(() => {
    console.log("init Child", props.title);
    return <div>Child: {props.title}</div>;
  }, []);

  return Title;
};
```

Link to code example:
https://codesandbox.io/s/loving-franklin-4f8fcl

## The current behavior
Change the title of the App component from title1 to title2, the App component is initialized, but the Child component is not initialized，the log is like this
```
init Child title1 
init Parent title1 
// change the title, only parent initialized
init Parent title2
```

## The expected behavior
Child components are also initialized

**Comment by gaearon** [comment]
This sandbox breaks React rules by omitting a dependency.

<img width="599" alt="Screenshot 2022-09-03 at 17 49 06" src="https://user-images.githubusercontent.com/810438/188280512-d71d4a30-2769-41cc-8b66-8296d563cdc2.png">

After you fix the mistake, it works as intended.
