### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by Quintis1212** [facebook/react#25128]
I see this function in node_modules/react-dom/cjs/react-dom.development.js

```
function getPublicInstance(instance) {
  return instance;
}

```
What is the purpose of this function ?

**Comment by Quintis1212** [comment]
@sunny @henrik @wvl

**Comment by sunny** [comment]
Wrong @sunny 🙄

**Comment by rickhanlonii** [comment]
This function is defined differently for different renderers such as React Native. GCC must not be able to inline it for some reason in react-dom. Documentation is here: https://github.com/rickhanlonii/react/blob/d483463bc86555decb3e8caa18459d1d0f7c0148/packages/react-reconciler/README.md#L168
