### ISSUE TITLE
Bug: ReactDOMRoot.render happened error (react-dom.development.js:29074:1)

### ISSUE THREAD

**Issue by panxuge** [facebook/react#25130]
React version: 18.2.0

## Steps To Reproduce

1. when i using ReactDOM.createRoot(document.getElementById('root')).render('hello world')
2. after yarn start
3. chrome devtools console error infos
4. Uncaught TypeError: Cannot read properties of undefined (reading 'current')
5.   at isConcurrentActEnvironment (react-dom.development.js:25075:1)
6.   at warnIfUpdatesNotWrappedWithActDEV (react-dom.development.js:27349:1)
7.    at scheduleUpdateOnFiber (react-dom.development.js:25326:1)
8.   at updateContainer (react-dom.development.js:28616:1)
9.   at ReactDOMHydrationRoot.render.ReactDOMRoot.render (react-dom.development.js:29074:1)
10.  I desperately hope you can help me and thanks

Link to code example:

**Comment by utku656** [comment]
It happened to me .How did you solve this issue ?
