### ISSUE TITLE
Unexpected behavior while compiling jsx with attribute strings containing "&"

### ISSUE THREAD

**Issue by bjoerge** [facebook/react#2515]
Repro case:
```jsx
<div attr="&abcdefghi"></div>
```
fails with Unexpected token ILLEGAL, while adding *one* more character after the `&`:
```jsx
<div attr="&abcdefghij"></div>
```
compiles to:
```
React.createElement("div", {attr: "undefined"})
```
... which is quite surprising. Not sure what is going on here.

**Comment by gaearon** [comment]
It's still weird but documented now. We can track changes to JSX in its own repo.
