### ISSUE TITLE
Bug: 500 errors in business manager UFAC flow

### ISSUE THREAD

**Issue by danog** [facebook/react#25160]
I've been getting 500 errors from an API endpoint (https://business.facebook.com/accountquality/ufac/?decision_id=2258158507685914) in business manager, which is preventing me from successfully completing an ID check verification.

Tagging the entire org (@facebook) because we've been trying to get support as **paying customers** by using feedback forms for almost a month now, with **no reply whatsoever**.
We've paid facebook thousands of dollars in ads, and we intend to pay more for the ad campaign in September for our new dance school in Ferrara (Italy): we rely almost exclusively on Facebook ads to get clients, and without it we might as well close business.  

A few years ago you could even schedule a call with representatives, which helped us more than once with facebook-side bugs: now every contact form seems to end up in /dev/null.
Please, we would really like to get some feedback either through this issue, daniil@daniil.it or +393924682693.

![fb](https://user-images.githubusercontent.com/7339644/187684738-0247d5a2-9c67-46c9-87e4-0a3a3a075369.jpg)

## Steps To Reproduce

1. Upload ID as requested.
2. 5 minutes pass, the ID verification fails and the day counter skips from 30 days to 0 days.
3. Add another admin, and make them upload the other ID as requested.
4. Click on "Continue Request" button.

## The current behavior

A server-side 500 error with no pop-up or visible UI reaction after pressing the "Continue Request" button.

## The expected behavior

ID verification and account unban, or an explanation for why is the ID being refused.

**Comment by gaearon** [comment]
I understand the frustration, but please don't use an unrelated open source project tracker to report bugs in a product.

**Comment by gaearon** [comment]
(I'll try to ping somebody but can't promise a resolution)
