### ISSUE TITLE
[DevTools Bug]: useSyncExternalStore adds 1 to subsequent hook's number in Profiler

### ISSUE THREAD

**Issue by AlexTalis** [facebook/react#25178]
### Website or app

https://codesandbox.io/s/sweet-fast-huvy9e?file=/src/App.tsx

### Repro steps

1. Open the sandbox in Google Chrome. Notice that the App component in App.tsx calls useSyncExternalStore, followed by useState. Lastly, it has an effect that simply toggles the state value every second so that it's easy to profile state changes without interacting with the UI.
2. Open the rendered page in a new window and inspect it in Chrome DevTools.
3. Open Components tab, select the App component, and notice that useState hook is `#2`. ![image](https://user-images.githubusercontent.com/1012600/188234380-2d4a5dee-3aa5-46ae-b919-f3cbe276d741.png)
4. Switch to Profiler tab and profile the page for a couple of seconds.
5. Notice that "Why did this render?" section says "Hook **3** changed". The number should be 2. ![image](https://user-images.githubusercontent.com/1012600/188236070-103563ca-ae0c-45b1-af58-c397fced98c4.png)

### How often does this bug happen?

Every time

**Comment by AlexTalis** [comment]
Hi, I understand that useExternalStore is a hook and I agree that useState is hook `#2`. I never said it should be `#1`. But the profiler (2nd image) says that the component rerendered because "Hook 3 changed". That is the bug. There is no Hook 3. The component only has 2 hooks. The profiler should says "Hook 2 changed".

**Comment by AlexTalis** [comment]
@lunaruan, Can you reopen this issue please? I don't have access to do it. Hopefully my previous comment explains the problem better.

**Comment by lunaruan** [comment]
Ah thanks for the explanation! I'll take a closer look in a bit

**Comment by chamerling** [comment]
Hello,

This is probably the same issue I am facing with debugging an application which uses react-query hooks which itself uses `useSyncExternalStore`. This is almost impossible to debug when a component is using several react-query hooks, how can we know which one is the right hooks?

For example, I got this:

<img width="257" alt="Capture d’écran 2023-04-25 à 17 43 42" src="https://user-images.githubusercontent.com/264403/234331190-e688e9df-81e8-4fd1-90fc-fd1228fab836.png">

So looking at `hook 78` which is displayed as `boolean` in devtools

<img width="579" alt="Capture d’écran 2023-04-25 à 17 35 20" src="https://user-images.githubusercontent.com/264403/234331309-20411825-ba3e-4916-81ae-92a395d39e0b.png">

but when printing the component state to the console, `hook 78` value is an integer.

<img width="688" alt="Capture d’écran 2023-04-25 à 17 35 51" src="https://user-images.githubusercontent.com/264403/234331530-022ec293-ce81-40ad-997b-ccd630a1d130.png">

Any idea how we can fix this? Can I help?

**Comment by chamerling** [comment]
Is it linked to this? https://github.com/facebook/react/blob/bf449ee74e5e98af3d08c87bb6a9f22a021f3522/packages/react-debug-tools/src/ReactDebugHooks.js#L596

From what I see, I have a lot of `null` ids when logging state to the console, and so it may be the issue.
What I do not understand is why we do not count the same between `Hook 78 changed` in Profiler view, and in Component one?
