### ISSUE TITLE
[DevTools Bug]: DevTools shouldn't skip over keyed Fragments in the tree

### ISSUE THREAD

**Issue by gaearon** [facebook/react#25187]
### Website or app

https://github.com/reactjs/reactjs.org/pull/4981

### Repro steps

1. Wrap something into `<Fragment key="stuff">`
2. It doesn't show up in DevTools

We filter out fragments because they tend to be useless. But this one is important! Keys are crucial and we should show anything with a key in the tree.

### How often does this bug happen?

Every time

**Comment by timagixe** [comment]
Hi @gaearon, I would like to give it a shot, if you think this bug is a beginner friendly.

Could you please point which exact package should I look at? I see there are seven of them related to devtools:
```
react-devtools-core
react-devtools-extensions
react-devtools-inline
react-devtools-shared
react-devtools-shell
react-devtools-timeline
react-devtools
```
