### ISSUE TITLE
JSXTransformer using == null comparison for spread attributes

### ISSUE THREAD

**Issue by EvHaus** [facebook/react#2519]
Currently, JSX for:

`var {cls, ...other} = this.props;`

Gets compiled to:

`var $__0= this.props,cls=$__0.cls,other=(function(source, exclusion) {var rest = {};var hasOwn = Object.prototype.hasOwnProperty;if (source == null) {throw new TypeError();}for (var key in source) {if (hasOwn.call(source, key) && !hasOwn.call(exclusion, key)) {rest[key] = source[key];}}return rest;})($__0,{cls:1});`

The `source == null` should be `source === null` in order to pass most JSHint tests.

**Comment by romeovs** [comment]
This is mainly bad because I cannot run my jsx-transformed files thought `jshint` without having a dozen of `Use '===' to compare with 'null'.` warnings pop up. I could disable the warning but this allows me to make the error in my own code.
