### ISSUE TITLE
Bug: The React Native 0.63 app doesn't run on android 4.4

### ISSUE THREAD

**Issue by merrymaker14** [facebook/react#25193]
I'm making an app for wonlex kt24. There android 4.4, which is kit kat 🍫, for this put the old version (0.63), which still had support for the old SDK. On the emulator, the starter project runs, but on the watch does not even run, although the apk is installed.

```
"react": "16.13.1",
"react-native": "0.63.0",
```

```
ext {
    buildToolsVersion = "29.0.2"
    minSdkVersion = 16
    compileSdkVersion = 29
    targetSdkVersion = 29
}
```

**Comment by eps1lon** [comment]
For `react-native` related issues please [file an issue against facebook/react-native](https://github.com/facebook/react-native/issues/new) instead
