### ISSUE TITLE
Bug: iframe `src` attribute set incorrectly in jsx

### ISSUE THREAD

**Issue by zachsiegel-capsida** [facebook/react#25196]
My MWE is a very simple iframe:

```jsx
<iframe src="https://content.com"></iframe>
```

This works just fine (full `iframe` code below).

If I wrap the `src` attribute's value in curly braces (code below), I get the following:

```jsx
<iframe src={"https://content.com"}></iframe>
```

![image](https://user-images.githubusercontent.com/98366852/188758714-babca583-0375-44a2-8cfc-87b157c9a21f.png)

![image](https://user-images.githubusercontent.com/98366852/188758752-9dffe996-602f-4e50-bc72-35771a46f15f.png)

The actual `iframe` content is [an embedded Powerpoint presentation](https://support.microsoft.com/en-us/office/embed-a-presentation-in-a-web-page-or-blog-19668a1d-2299-4af3-91e1-ae57af723a60#:~:text=Open%20your%20presentation%20in%20PowerPoint,Share%2C%20and%20then%20click%20Embed.&text=In%20the%20Embed%20box%2C%20under,Copy%2C%20and%20then%20click%20Close.):

```jsx
<iframe
src="https://capsida.sharepoint.com/sites/sitename/_layouts/15/Doc.aspx?sourcedoc={xxxxxx}&amp;action=embedview"
width="476px"
height="288px"
frameBorder="0">
</iframe>
```

React version:

## Steps To Reproduce

1. Open [this Stackblitz](https://stackblitz.com/edit/react-me-zrdgyz?file=src/App.js). You should not be able to see the embedded Powerpoint content, but the iframe should load correctly (you should see a Microsoft login screen).
2. Wrap the `src="https://..."` in curly braces: `src={"https://..."}` and save the component. Now the `iframe` does not load! You can see the screenshots below to observe this phenomenon:

![image](https://user-images.githubusercontent.com/98366852/188759712-1770a049-d9e3-47f4-99ae-33d8620aaadd.png)

![image](https://user-images.githubusercontent.com/98366852/188759736-19dd2330-4f97-48cc-a8be-5c4b6edcd959.png)

## The current behavior

My real example is something like `src={url}`, where `url` is a state variable. The issue is not that I want to wrap the attribute in curly braces, it's that this iframe loads differently when the attribute is hard-coded into the jsx versus loaded from javascript via curly braces `{url}`.

I also recognize that Microsoft's Powerpoint embedding logic may forbid cross-origin embedding, and **I want to emphasize that this is clearly not the issue here despite the Chrome console message**. If cross-origin embedding was the issue, the `iframe` should equally fail with or without curly braces.

## The expected behavior

I expect the `iframe` to load (or not load) the same way regardless of whether its `src` attribute is passed as an HTML attribute in jsx (`src="https://..."`) or as a jsx attribute (`src={"https://..."}`).

**Comment by Noah670** [comment]
iFrames are chaotic evil in react

**Comment by zachsiegel-capsida** [comment]
@Noah670 99.9% of the time I would assume I am doing something wrong and that the React developers would call my issue a mis-use rather than a bug, but I think my MWE is very compelling. I doubt many people would see the MWE and expect it to succeed/fail depending on those curly braces.

**Comment by zachsiegel-capsida** [comment]
Created [this Stackblitz](https://stackblitz.com/edit/react-g7scn2?file=src%2FApp.js) documenting several attempted solution paths referenced [here](https://stackoverflow.com/questions/62871284/load-third-party-iframe-in-react-after-page-load-so-that-the-iframe-does-not-af/67902913#67902913), [here](https://github.com/facebook/react/issues/12665#issuecomment-677264432), and [here](https://github.com/facebook/react/issues/6541#issuecomment-1174249634).

**Comment by FrameMuse** [comment]
I just ran your code and it works as intended, I think you have a problem with work breaks, you have a break at `{f8c`, it might be just adding `\n` to your url.

I tested it via `const url = "..."`, via jsx `{"..."}`, `"..."` - every method works **the same**.

And I'm not a React Maintainer :)

**Comment by FrameMuse** [comment]
> If I wrap the `src` attribute's value in curly braces (code below), I get the following:
> 
> ```js
> <iframe src={"https://content.com"}></iframe>
> ```
> 
> ![image](https://user-images.githubusercontent.com/98366852/188758714-babca583-0375-44a2-8cfc-87b157c9a21f.png)

This is funny how you put `https://content.com` and getting error with `capsida.sharepoint.com`.

**Comment by zachsiegel-capsida** [comment]
@FrameMuse thank you for this response! I'm not sure what I'm missing, please help me out:
- The "break" in my URL at `{f8c` is just word wrap - there is no newline there at all.
- If you run the Stackblitz, do you indeed see the iframes embedding the page successfully with the jsx-style `url={"..."}` attribute?

**Comment by FrameMuse** [comment]
@zachsiegel-capsida I clearly see that the attribute `src` is putting correctly, but the content is loading endlessly (probably because of my location or any other reason).

I drop a screenshot for you
![image](https://user-images.githubusercontent.com/53980482/190714547-cb52b14d-13ee-43be-b5c5-74747a1ef49e.png)

**Comment by FrameMuse** [comment]
Did you tested it in a "local environment" (I mean server that is running locally on your computer) or only on [Stackblitz](https://stackblitz.com)?

**Comment by FrameMuse** [comment]
And also in your example with iframe code you misput `action=embedview` to `src` attribute, see it in your code
```html
<iframe
src="https://capsida.sharepoint.com/sites/sitename/_layouts/15/Doc.aspx?sourcedoc={xxxxxx}&amp;action=embedview"
width="476px"
height="288px"
frameBorder="0">
</iframe>
```

It should be
```html
<iframe
src="https://capsida.sharepoint.com/sites/sitename/_layouts/15/Doc.aspx?sourcedoc={xxxxxx}&amp;"
width="476px"
height="288px"
frameBorder="0"
action="embedview">
</iframe>
```

**Comment by devjs1000** [comment]
after seeing the link and what you are trying to do
there is nothing wrong with jsx and the react.

the link or website you are trying to access has x-frame same-origin enable it means that you can't use it in iframes.

# defination: 
you have to check for HTTP response header X-Frame-Option of those sites. if its value is "DENY or SAMEORIGIN", then you can not load those website in the iframes. DENY = No one can load the website in iframe. Even the same domain page wont be able to load.

**Comment by FrameMuse** [comment]
> after seeing the link and what you are trying to do there is nothing wrong with jsx and the react.
> 
> the link or website you are trying to access has x-frame same-origin enable it means that you can't use it in iframes.
> 
> # definition:
> you have to check for HTTP response header X-Frame-Option of those sites. if its value is "DENY or SAMEORIGIN", then you can not load those website in the iframes. DENY = No one can load the website in iframe. Even the same domain page wont be able to load.

As I wrote above, there is a problem with `action` attribute, the website denies access when it's not `embedview`.

**Comment by devjs1000** [comment]
> > after seeing the link and what you are trying to do there is nothing wrong with jsx and the react.
> > the link or website you are trying to access has x-frame same-origin enable it means that you can't use it in iframes.
> > # definition:
> > you have to check for HTTP response header X-Frame-Option of those sites. if its value is "DENY or SAMEORIGIN", then you can not load those website in the iframes. DENY = No one can load the website in iframe. Even the same domain page wont be able to load.
> 
> As I wrote above, there is a problem with `action` attribute, the website denies access when it's not `embedview`.

not it is not the case
the website is doing this because the data same origin is written in its header.
this practice is used for protecting data from hackers by web devs.

**Comment by FrameMuse** [comment]
> > > after seeing the link and what you are trying to do there is nothing wrong with jsx and the react.
> > > the link or website you are trying to access has x-frame same-origin enable it means that you can't use it in iframes.
> > > # definition:
> > > you have to check for HTTP response header X-Frame-Option of those sites. if its value is "DENY or SAMEORIGIN", then you can not load those website in the iframes. DENY = No one can load the website in iframe. Even the same domain page wont be able to load.
> > 
> > 
> > As I wrote above, there is a problem with `action` attribute, the website denies access when it's not `embedview`.
> 
> not it is not the case the website is doing this because the data same origin is written in its header. this practice is used for protecting data from hackers by web devs.

I had the error in console too, but when I put the attribute it disappreared and you're saying this is not the case, how's that?
Also, this iframe code should work because it's literally how it intented to be. This is a feature of Microsoft Powerpoint - you can share it (with iframe).

**Comment by zachsiegel-capsida** [comment]
> And also in your example with iframe code you misput `action=embedview` to `src` attribute, see it in your code
> 
> ```
> <iframe
> src="https://capsida.sharepoint.com/sites/sitename/_layouts/15/Doc.aspx?sourcedoc={xxxxxx}&amp;action=embedview"
> width="476px"
> height="288px"
> frameBorder="0">
> </iframe>
> ```
> 
> It should be
> 
> ```
> <iframe
> src="https://capsida.sharepoint.com/sites/sitename/_layouts/15/Doc.aspx?sourcedoc={xxxxxx}&amp;"
> width="476px"
> height="288px"
> frameBorder="0"
> action="embedview">
> </iframe>
> ```

This has nothing to do with whether the iframe `src` URL contains `&action=embedview` versus adding the `action="embedview"` attribute to the `iframe`. I tried both ways and they both work/fail the same way; these `iframe` snippets were generated from MS Powerpoint with `&action=embedview` and I suspect that should work.

As I have mentioned, regardless of whether changing other `iframe` attributes *could* result in properly loaded content, the fact is that **in no case** should a JSX-style attribute result in different behavior from an HTML-style attribute (i.e. `src="http://..."` should always function the same as `src={"http://..."}`). If I'm wrong about that part I'd love to hear why, but nobody has commented on that.

**Comment by zachsiegel-capsida** [comment]
@devjs1000 
> after seeing the link and what you are trying to do there is nothing wrong with jsx and the react.
> 
> the link or website you are trying to access has x-frame same-origin enable it means that you can't use it in iframes.
> 
> # definition:
> you have to check for HTTP response header X-Frame-Option of those sites. if its value is "DENY or SAMEORIGIN", then you can not load those website in the iframes. DENY = No one can load the website in iframe. Even the same domain page wont be able to load.

As I have mentioned, I understand that there are many reasons why an `iframe` might not load, and I absolutely understand same-origin policies. The issue is that the behavior is different using JSX-style versus an HTML-style `src` attribute (i.e. `src={"http://..."}` versus `src="http://..."`) - they should either both fail or both succeed if a same-origin policy is to blame.

**Comment by zachsiegel-capsida** [comment]
@FrameMuse 
> Did you tested it in a "local environment" (I mean server that is running locally on your computer) or only on [Stackblitz](https://stackblitz.com)?

Yes, I experienced this issue in a local React environment (serving on `localhost`) as well as on a staging server (an AWS EC2 instance) before creating this MWE on Stackblitz. In all cases, the `iframe` has the same problem.

**Comment by devjs1000** [comment]
@zachsiegel-capsida 
can you tell me the browser you are using

**Comment by zachsiegel-capsida** [comment]
@devjs1000 I am using the latest Chrome. Still having a tough time with this!

**Comment by zachsiegel-capsida** [comment]
SOLVED!

Per [this StackOverflow comment](https://stackoverflow.com/a/73018468/18338483), the string `&amp;` in Javascript strings works slightly differently from HTML. In `ifram` `src` attributes in HTML, it's not necessary to escape ampersands in this way, so I don't know why Microsoft's Sharepoint "embed" snippets are made that way.

I am able to change `src={url}` to `src={sanitizeUrl(url)}` where `sanitizeUrl` is the following function:

```javascript
function sanitizeUrl(url) {
	return url.replaceAll('&amp;', '&')
}
```

I would consider this issue closed.

**Comment by punyapatkha** [comment]
i faced the same issue.
sanitizeUrl also work for me thank you very much!
