### ISSUE TITLE
Bug: <img/> renders twice in firefox with react 18

### ISSUE THREAD

**Issue by kapibaara** [facebook/react#25218]
React version: 18.2.0

## Steps To Reproduce

1. Insert a tag  `<img/>` with src
2. Go to **Firefox** inspect tool to the tab network
3. Reload the page and watch image request in network

Link to code example: https://codesandbox.io/s/unruffled-jerry-9hli44?file=/src/App.js

## The current behavior
There are two request for image in firefox, image renders twice
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/41840872/189360604-c1f1451a-be7f-497d-b9db-9d18f98af607.png">

## The expected behavior
There is one request and one render in firefox

**Comment by MiguelMachado-dev** [comment]
It really happens, even on Chrome/Edge. But I think this is due to StrictMode. Could please try deleting StrictMode on `index.js`?

It will look like this.
```jsx
root.render(<App />);
```

On StrictMode react render twice. https://reactjs.org/docs/strict-mode.html

**Comment by kapibaara** [comment]
> It really happens, even on Chrome/Edge. But I think this is due to StrictMode. Could please try deleting StrictMode on `index.js`?
> 
> It will look like this.
> 
> ```js
> root.render(<App />);
> ```
> 
> On StrictMode react render twice. https://reactjs.org/docs/strict-mode.html
> 
> > StrictMode renders components twice (on dev but not production) in order to detect any problems with your code and warn you about them

it doesn't help, in my example in codesandbox, there is not StrictMode
Аnd on Chrome, if you open this https://9hli44.csb.app/, there are no two requests in network tab

**Comment by MiguelMachado-dev** [comment]
There is, check https://codesandbox.io/s/unruffled-jerry-9hli44?file=/src/index.js
On Edge and Firefox I still getting 2 requests, disabling strict-mode it stops.

**Comment by sigorilla** [comment]
@MiguelMachado-dev, Just check this example (without `StrictMode`): https://codesandbox.io/s/goofy-stonebraker-pf0wg7?file=/src/index.js (https://pf0wg7.csb.app/)

And there is screenshot with two requests:

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/1208639/189645667-bd18813b-8f6d-4987-b3af-621298bd1aff.png">

What i'm doing wrong?

**Comment by MiguelMachado-dev** [comment]
Not sure, it does not happen to me. We should then wait for more people to see this. It only happen to me when using StrictMode.

Edge:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/29252011/189654466-3c90adf7-6b5f-4ff7-9655-61be91455a63.png">

Firefox:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/29252011/189654925-a59a5c23-685f-4aca-a9c7-7d278a569de6.png">


 Both browsers up to date.

**Comment by arpitj007** [comment]
It really is an issue.

**Comment by arpitj007** [comment]
@MiguelMachado-dev How can I contribute to fixing this bug?

**Comment by MiguelMachado-dev** [comment]
> @MiguelMachado-dev How can I contribute to fixing this bug?

Do you know how to fix it?

If you know, you can fork the project and open a PR. Or a solution, you can comment here how he can fix it properly.

**Comment by sult4novars** [comment]
Hi! I repeated this case in https://codesandbox.io/ with clean HTML and get same result, then I try same code with corgi in https://codepen.io/  and get one request)

**Comment by sigorilla** [comment]
Maybe it depends on OS? I have MacOS 12 (M1), Firefox 104.0.2

And I reproduced it on codepen: https://codepen.io/sult4novars/pen/NWMRzRX

**Comment by sult4novars** [comment]
i have sames params MacOS 12.6  (M1, 8gb), Firefox 104.0.2)

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/98759712/189885380-36e0d906-6417-4cae-9cde-57890bfdde03.png">

**Comment by sult4novars** [comment]
> Maybe it depends on OS? I have MacOS 12 (M1), Firefox 104.0.2
> 
> And I reproduced it on codepen: https://codepen.io/sult4novars/pen/NWMRzRX

i have same params  MacOS 12.6 (M1, 8gb ), Firefox 104.0.2

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/98759712/189886105-eabc296d-ccb0-43a6-b95d-e452babd031f.png">

**Comment by sult4novars** [comment]
> Maybe it depends on OS? I have MacOS 12 (M1), Firefox 104.0.2
> 
> And I reproduced it on codepen: https://codepen.io/sult4novars/pen/NWMRzRX


ooo I reproduced to but when I reload page this case not reproduced
but i check status and see NS_BINDING_ABORTED and search this status, and what I found https://stackoverflow.com/questions/704561/ns-binding-aborted-shown-in-firefox-with-httpfox

**Comment by varunmulay22** [comment]
Firefox is simply ignoring the cache expires value when you force reload the page. The NS_BINDING_ABORTED tries to indicate that the browser checks whether the img is stored in the cdn cache which is obviously not in this case as there are no extra cache expires headers being sent. 

The request gets blocked because the page(codepen here) hasnt loaded yet and there is already another request (get image) being sent while the page request is yet to return completely. This isnt a typical React bug IMHO but more of a failsafe method Firefox implemented.

You can easily see the next reload request sent for the same img is served via cache as cache gets set to current whenever missing an expiry header. Have a look at the stack trace in dev console

![image](https://user-images.githubusercontent.com/35381801/194793787-e738b0da-0ff6-4865-ad7f-c2741519530b.png)

**Comment by maxencelaurent** [comment]
We are observing the same behaviour. Firefox 115, Ubuntu Linux 23.04 and macOs. Unable to test on Windows yet.

Here is some details.

The first request is initiated in react-dom.development.js, line 855:

```js
node.setAttribute("src", "https://.../korgi-na-trave-960x540-1-960x540.jpg");
```

Here is the stack trace.
```
setValueForProperty           react-dom.development.js:855:12
setInitialDOMProperties       react-dom.development.js:9720:26
setInitialProperties          react-dom.development.js:9921:26
finalizeInitialChildren       react-dom.development.js:10950:23
completeWork                  react-dom.development.js:22193:40
completeUnitOfWork            react-dom.development.js:26596:16
performUnitOfWork             react-dom.development.js:26568:23
workLoopSync                  react-dom.development.js:26466:22
renderRootSync                react-dom.development.js:26434:7
performConcurrentWorkOnRoot   react-dom.development.js:25738:74
...
```


The second request is initiated here:

```js
function commitMount(domElement, type, newProps, internalInstanceHandle) {
  // Despite the naming that might imply otherwise, this method only
  // fires if there is an `Update` effect scheduled during mounting.
  // This happens if `finalizeInitialChildren` returns `true` (which it
  // does to implement the `autoFocus` attribute on the client). But
  // there are also other cases when this might happen (such as patching
  // up text content during hydration mismatch). So we'll check this again.
  switch (type) {
    case 'button':
    case 'input':
    case 'select':
    case 'textarea':
      if (newProps.autoFocus) {
        domElement.focus();
      }

      return;

    case 'img':
      {
        if (newProps.src) {
          domElement.src = newProps.src; // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< HERE
        }

        return;
      }
  }
}
```

```
commitMount                       react-dom.development.js:11038
commitLayoutEffectOnFiber         react-dom.development.js:23407
commitLayoutMountEffects_complete react-dom.development.js:24688
commitLayoutEffects_begin         react-dom.development.js:24674
commitLayoutEffects_begin         react-dom.development.js:24656
commitLayoutEffects               react-dom.development.js:24612
commitRootImpl                    react-dom.development.js:26823
commitRoot                        react-dom.development.js:26682
finishConcurrentRender            react-dom.development.js:25981
performConcurrentWorkOnRoot       react-dom.development.js:25809
...
```

`node`, in the first snippet, and `domElement`, in the 2nd, are the very same variable: the real  `<img>` DOM node.


The point is the browser is replacing the source of the imgage twice.
If the first request has not been completed when the `src` attribute is set the second time, the browser aborts the first request, leading to the `NS_BINDING_ABORTED` error.
This occurs despite the src value is the same both time.

Note that the src is always converted to a  fully qualified URL (have a look : https://github.com/facebook/react/commit/f0dd459e0d97081cb3c313ec52285e3e422f8dbf): 

```js
const n = document.createElement("img");
n.src = "/favicon.ico"
console.log(n.src); // prints https://wherever.you.are/favicon.ico
```

This behaviour has been introduced in https://github.com/facebook/react/commit/086fa8ee2f80f0dc34b7d145be72f9843fca975d

Using Chromium, the request is only initated once, at the very end of the process.

**Comment by stanleyk** [comment]
@maxencelaurent I am observing the very same behavior you describe. Have you been able to solve or workaround it somehow? Thanks!

**Comment by wuarmin** [comment]
I have the same issue.
![image](https://github.com/facebook/react/assets/9987680/9989c8b1-cb70-4ded-91ba-21eb1e78ae01)

**Comment by faulpeltz** [comment]
I can reproduce this as well in Firefox 126.0 (and older versions as well), as a previous comment mentioned this is caused by the "fix" where commitMount()  sets the src attribute to the same value to trigger load/error events at the correct time.

Changing  in ``ReactDOMHostConfig.js`` (for React 18.3.1)

from
```javascript
if ((newProps: any).src) {
    ((domElement: any): HTMLImageElement).src = (newProps: any).src;
}
```

to 
```javascript
if ((newProps: any).src && ((domElement: any): HTMLImageElement).complete !== false) {
    ((domElement: any): HTMLImageElement).src = (newProps: any).src;
}
```
fixes it for me and the events still get fired, however I am not sure if this fix is safe in all cases and browsers
