### ISSUE TITLE
[DevTools Bug]: React extension tab in Edge DevTools doesn't have emoji prefix in title.

### ISSUE THREAD

**Issue by yanlingwang23** [facebook/react#25228]
### Website or app

https://reactjs.org/

### Repro steps

1. Open Developer Tools with React extension on any website that using React in Edge.
2. Check the react extension tab (Profiler and Components), it doesn't have emoji prefix in the title like Chrome does.

### How often does this bug happen?

Every time

**Comment by lunaruan** [comment]
Hey! Thanks for reporting! Marking this as an issue. If you'd like to look into it that'd be great. Otherwise, we'll get to it soon!

**Comment by itskolli** [comment]
@lunaruan  Created PR for this issue https://github.com/facebook/react/pull/25257

**Comment by lunaruan** [comment]
Closing because @itskolli fixed the bug. Thanks @itskolli!
