### ISSUE TITLE
Bug(not sure): Strange ordering of setState calls

### ISSUE THREAD

**Issue by gmoniava** [facebook/react#25237]
React version: 16

## Steps To Reproduce

1. Click the "Test App" div
2. See `valueB `never gets logged

Link to code example: https://stackblitz.com/edit/react-hooks-demo-f69yc7?file=App.js

## The current behavior

When clicked the "Test App" div `valueB `never gets logged.

## The expected behavior

Not sure what the expected behavior should be, just it seemed strange `valueB `was never logged.

After putting some `console.log`s and using functional `setState`, I can see why `valueB` was not logged, because it was overwritten by `setB(null)` from previous renders `useEffect ` return function. _Just still this behavior seemed a bit strange to me, so wanted to share to make sure this is not a bug. Is it?_

More details: https://stackoverflow.com/questions/68080085/state-update-being-overridden-by-another-previous-state-update

**Comment by rickhanlonii** [comment]
Yeah, that's the behavior in 16. If you check out the behavior in 18 below you can see that it's been updated to batch the updates with a more predictable outcome (automatic batching):

https://stackblitz.com/edit/react-hooks-demo-nd2wau?file=App.js
