### ISSUE TITLE
Feature request: Add a key property to custom hooks to reset state 

### ISSUE THREAD

**Issue by gmoniava** [facebook/react#25236]
We know that we can provide key to React custom components, and when we provide a different key to React custom component on next render, the previous instance associated with that custom component will be gone, all state will be reset, etc. In some situations this is even recommended in react docs.

Would similar feature be useful also for custom hooks? To pass it a key as parameter? And if on next render this key is different, then all state of this custom hook will be destroyed.

Pros:
- Similar to components in some situations it may be desirable to reset state of custom hook. With this feature you can do it automatically, without manually dealing with such situation.

Possible difficulties
- After giving it some more thought I think it might be tricky how to pass that key to the custom hook. It must go as a parameter, but then users won't be able to use it inside. Also how should the custom hook guess which parameter is the key, etc.

**Comment by vkurchatkin** [comment]
`Custom hooks` are not something that React can control or is aware of. It is just a plain function that is called normally. 
So, if you want to add some sort of `key` as an argument of your custom hook, you have to handle it yourself:

```js
function myCustomHook({ key }) {
   const [state, setState] = useState(initialState);

  useEffect(() => {
    setState(initialState);
  }, [key]);
}
```

**Comment by gmoniava** [comment]
Yeah like I mentioned after giving some more thought, although this might be useful (because like components hooks maintain state too and I might want to reset it), not sure how this can be done in practice.

**Comment by ChrisCanCompute** [comment]
I'm aware this is an old post, but I've come here after something similar. The suggested workaround above is an anti-pattern that will cause extra renders (see https://react.dev/learn/you-might-not-need-an-effect#resetting-all-state-when-a-prop-changes )

A better solution is the one suggested on the page to just update the state inline if the dependencies change:
```
function List({ items }) {
  const [isReverse, setIsReverse] = useState(false);
  const [selection, setSelection] = useState(null);

  // Better: Adjust the state while rendering
  const [prevItems, setPrevItems] = useState(items);
  if (items !== prevItems) {
    setPrevItems(items);
    setSelection(null);
  }
  // ...
}
```

**Comment by ChrisCanCompute** [comment]
I've turned the safer pattern into a hook should anyone find that useful:
```
const useResetOnDepsChange = (action : () => void, deps: any[]) => {
  const [prevDeps, setPrevDeps] = React.useState<string[]>(deps)
  if (deps.length !== prevDeps.length || deps.some((v, i) => v !== prevDeps[i])) {
    setPrevDeps(deps)
    action()
  }
}
```

Just invoke it in your hook like you would have done `useEffect` above, but know that it's saved you a render:
```
function myCustomHook({ key }) {
   const [state, setState] = useState(initialState);

  useResetOnDepsChange(() => {
    setState(initialState);
  }, [key]);
}
``
