### ISSUE TITLE
Bug: inconsistent auto batching

### ISSUE THREAD

**Issue by amirqasemi74** [facebook/react#25273]
I have to `useEffect`s in my code. in first one I have two setState, the second one is in `then` of `Promise.resolve`.
and in the second useEffect I make a request by apollo client.

React version: 18.2.0

## Steps To Reproduce

1. rerun app to see different logs

Link to code example:
https://codesandbox.io/s/confident-http-m4fey5?file=/src/App.js:623-641

## The current behavior
In some run the output of logs is:
![image](https://user-images.githubusercontent.com/20992734/190408195-149b12ce-0adc-4e6f-90eb-3631aa5a36f9.png)
and in some other run:
![image](https://user-images.githubusercontent.com/20992734/190408331-e5b11f87-78c1-4cb1-b756-c12964d430ba.png)

## The expected behavior
I expected react to does not batch `setState("bb")` and `setState("aa")` at all and always logs like this:
![image](https://user-images.githubusercontent.com/20992734/190408195-149b12ce-0adc-4e6f-90eb-3631aa5a36f9.png)

but I don't know why react in some run batch two setStates and in some other run doesn't batch. I don't know there is any problem with apollo because with `fetch` react always doesn't batch these to setStates

**Comment by LuBustos** [comment]
Hey @amirqasemi74! I think the problem is that every fetch takes differents times so the logs are differents, if you try to make a promise and get the same data as the Apollo fetch, you will have your expected behavior. Anyways you can use a setTimeout if one promise takes more time than other.
Here is an example:

```
  const run_1 = async () => {
    setA("aa");
    await Promise.resolve().then(() => {
      setTimeout(() => {
        console.log("here");
        setB("bb");
      }, 50);
    });
  };
```
I hope I've helped you 😊
