### ISSUE TITLE
Bug: React-Core should support VirtualizedList instead of third-party packages.

### ISSUE THREAD

**Issue by meotimdihia** [facebook/react#25279]
This is not a bug report, but I don't know how to reach someone to make decisions on React development.
React really need Virtualized List, but every third-party package is not good enough in comparison with [React-Native FlatList](https://reactnative.dev/docs/flatlist).
It required a lot of effort to use, and we have bugs that could never get solved, it seems the authors stopped to support these packages, or it could take months to make 1-2 commits.

- https://www.npmjs.com/package/react-window - 1M+ downloads 
- https://www.npmjs.com/package/react-virtualized - 1M+ downloads
- https://www.npmjs.com/package/react-virtual - 250k+ downloads
- https://www.npmjs.com/package/react-infinite-scroll-component = 500k+ downloads
- https://www.npmjs.com/package/react-virtuoso
- https://github.com/inokawa/virtua
- and a lot of other libraries ...

I tried to use 3-4 packages on my website. It works when we know the size of items, but if we don't know then almost these packages get weird bugs. And the Window scroller wasn't supported or in a bad state in these packages.

P/S: A common problem is these packages often have bugs with dynamic size DOM and window scroller and iOS.

**Comment by Maverick17user** [comment]
Agreed, would be interesting to hear smth. about it from react devs.

**Comment by inokawa** [comment]
I know this is off topic but if someone visited here wanted better virtual list, https://github.com/inokawa/virtua may help you.
It has better support for dynamic size and iOS than the others.
