### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by bogdanoliinyk** [facebook/react#25276]
#### React 17 not mimic autocomplete up to default browser behaviour.

Default Chrome autocomplete mimic user behaviour: on suggestion pick it fires focus event -> change event -> blur event for every changed field.
<img src="https://user-images.githubusercontent.com/70579361/190426092-41d9ac66-b84e-484d-bbb6-206038465d60.png" width="300px">

### React 16
Playground https://jsfiddle.net/akany/0x4qL8np/10/.
Pick chrome suggestion, check console logs.
Each field has focus/change/blur events in chain.
![image](https://user-images.githubusercontent.com/70579361/190428487-f1e37faa-8bc2-43ed-a1a4-1f086a64fc4b.png)

### React 17
Playground https://jsfiddle.net/akany/0x4qL8np/11/
Pick chrome suggestion, check console logs.
Each field has only change event.
![image](https://user-images.githubusercontent.com/70579361/190425279-e660f7c5-24c2-400b-bdbb-cd866ea4eb7c.png)

### How to setup Chrome suggestion
Need to add chrome address. There are many articles about it, one of it https://www.tech-recipes.com/internet/google/google-chrome/how-to-add-an-address-in-google-chrome/. 

## The current behavior
Suggestion event chain is not up to browser, just change events are fired. React 17+

## The expected behavior
Suggestion event chain is up to browser: focus -> change -> blur.

**Comment by devjs1000** [comment]
this is because it is upto the browser which method they wanna use for filling up the fields
## In your case it was
focus to el1 or clicking on el1;
changing data of el1;
blur then moving up to the next autocomplete element.
as you know it can have 1 focus at a time.
thats the reason for this behaviour.
