### ISSUE TITLE
Feature Request: New hook `useToggleState`

### ISSUE THREAD

**Issue by kkyusufk** [facebook/react#25297]
**Summary**
Many times we have ended up writing a toggle function like this
```javascript
const [ subtitles, setSubtitiles ] = useState(false);
const toggleSubtitles = () => setSubtitles((prevState) => !prevState);
```
The `toggleSubtitles` function exist purely to toggle the state. This can be taken care of by the new hook `useToggleState`.

**API**
`useToggleState` will be used to create state variables like normal, however instead of returning a getter for setting a state, we get a toggle state function
```javascript
const [ subtitles, toggleSubtitles ] = useToggleState(false); 
```
If we also want to get the original setter for this state, we can de-structure a third argument.
```javascript
const [ subtitles, toggleSubtitles, setSubtitles ] = useToggleState(false); 
```
or `toggleSubtitles` can accept a boolean value as well, which will set the state to the value passed
```javascript
toggleSubtitles() // toggles state between true and false
toggleSubtitles(true) // will set the state to be true
toggleSubtitles(false) // will set the state to be false
```

**Alternative** 
- We can also modify `useState` to return a `toggle` function as a third de-structure.
- We can write our own custom hook for this feature but it would mean it has to be replicated on each and every repo.

**Comment by EliHood** [comment]
Idkk.... about this feature, i feel like react shouldn't support this. It would be an _OK_ feature to have for a third party package though. That's just me though.

**Comment by wenzi0github** [comment]
Generally, js library only provides basic capabilities. useToggleState can be supported by useState.

```javascript
/**
 * toggle true or false to another
 * @param {boolean} defaultVal
 * @returns
 */
const useToggleState = (defaultVal = true): [boolean, (val?: boolean) => void] => {
  const [subtitles, setSubtitiles] = useState(defaultVal);

  const toggleSubtitles = (bool?: boolean) => {
    setSubtitiles((prevState) => bool ?? !prevState);
  };

  return [subtitles, toggleSubtitles];
};
```

```javascript
const [subtitles, toggleSubtitles] = useToggleState();
```

**Comment by kkyusufk** [comment]
Agreed with all of you.
I just wanted to get a second opinion from folks and I think after consideration, we actually do not need this.
Thanks all for sharing your thoughts, will close this issue.
