### ISSUE TITLE
Bug: defaultValue property missing on select element ref 

### ISSUE THREAD

**Issue by antonio-costa** [facebook/react#25294]
React version: 18.2.0

## Steps To Reproduce

1. Set a  `defaultValue` on a `<select />` element.
2. After the element mounts, try to access that `defaultValue` through a ref of the element.

TypeScript is also missing the definition for `defaultValue` on `HTMLSelectElement` type

Link to code example: https://codesandbox.io/s/elated-orla-0p3dw7?file=/src/App.js

## The current behavior
`defaultValue` always returns undefined

## The expected behavior
`defaultValue`should return the defined value

**Comment by vkurchatkin** [comment]
This does not have a lot to do with React.

`HTMLInputElement` has `defaultValue` property: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#properties

`HTMLSelectElement` does not: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement#properties

**Comment by antonio-costa** [comment]
I understand that, but React prompts and console error if I use the "HTML-way" of using `selected` in `<option />`.

![image](https://user-images.githubusercontent.com/14340661/191028470-897f07b3-538f-48a5-9c19-e47df4c9023b.png)

I believe this is was a decision to provide consistency across form elements (which I agree), but if the prop is not returned when I try to access it in a ref, then there's an inconsistency on this implementation, no?

How can I know what is the default value of a select element if React doesn't allow me use the `selected` prop but also doesn't provide the `defaultValue` property on the ref?

**Comment by vkurchatkin** [comment]
>  if the prop is not returned when I try to access it in a ref, then there's an inconsistency on this implementation, no?

React does indeed provide consistency, but only on the React side of things. It doesn't do anything to unify DOM APIs, because it is not it's job. 

> How can I know what is the default value of a select element if React doesn't allow me use the selected prop but also doesn't provide the defaultValue property on the ref?

You can definitely read `selected` when using ref:

```js
useEffect(() => {
    console.log("select default value", selectRef.current.querySelector('option[selected]')?.value);
    console.log("input default value", inputRef.current.defaultValue);
  }, []);
```

But the most important question is: why do you even want to read `defaultValue` from DOM? You are the one who provides it, you already know it.
