### ISSUE TITLE
Bug: event not bubbling to root on iOS Safari

### ISSUE THREAD

**Issue by LeunensMichiel** [facebook/react#25308]
We have a div element with an `onClick` and `onDoubleClick` function. Prior to React 17/18, this worked consistently throughout all browsers. However, from the moment we've upgraded to React 18 (also reproducible on React 17), this stopped working on iPhones running Safari.

I assume this is because of the event propagation changes in React 17. It _does_ work on Safari on MacOs, and on all mobile Android browsers too. So only iOS' Safari behaves differently.

Our component looks like this:
```
<div
      className="slideshow-preview"
      onClick={onClickFnc}
      onDoubleClick={onDoubleClickFnc}
      ...
```

This is the component in its default state:
![image](https://user-images.githubusercontent.com/18447679/191563127-49bfea0f-fde1-4aff-bbfa-ae5e6e6631f0.png)

When clicking once, some resizing handlers appear (the  `onClick` method)
![image](https://user-images.githubusercontent.com/18447679/191563219-8638f8e3-93ef-4e3a-afba-13eb8f473769.png)

When double clicking, the crop modus appears (the `onDoubleClick` method)
![image](https://user-images.githubusercontent.com/18447679/191563394-d3949cfb-6380-477b-a108-dc976775c972.png)

This `onDoubleClick` won't trigger on iOS. 
Tested on 

- iPhone 12 running iOS 15 and 16
- iPhone 14 emulator running iOS 16. 

HOWEVER. After looking through [the React 17 upgrade blog's](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues) potential issue fixes part, I tried to apply a suggested fix to my code.

So in my component, I added this piece: 
```
useEffect(() => {
      document?.addEventListener("dblclick", onDoubleClickFunc);
      return () => {
	      document?.removeEventListener("dblclick", onDoubleClickFnc);
      };
}, [onDoubleClickFunc]);
```
and now it works consistently! But it looks kinda hacky and I'm not a fan of it.

Is there a possibility by chance that there's a bug in Safari and/or React or am I doing something wrong? Would love if someone could explain me.

Thanks in advance

**Comment by melloware** [comment]
I am seeing the same exact issue.  I can't believe more people are not reporting this.

**Comment by melloware** [comment]
bump
