### ISSUE TITLE
Bug: how to preventDefault in touchmove

### ISSUE THREAD

**Issue by this-spring** [facebook/react#25326]
React version:
17.0.2

## Steps To Reproduce
I want the parent element to not scroll when the child element is scrolled

jsx
```
const App = () => {
        const styleObj = {
             height: "200vh",
             "background-image": "linear-gradient(rgb(255, 255, 255), rgb(170, 0, 0))"
        }
        function touchMove(event) {
            event.nativeEvent.preventDefault();
        }
        return (
          <div id="parent" style={ styleObj }>
             <div id="child" onTouchMove={touchMove} className="r">
             </div>
          </div>
      );
}
```  

css:  
```
.r {
  position: fixed;
  top: 200px;
  left: 0;
  z-index: 10;
  width: 100%;
  height: 300px;
  background-color: black;
}
```
When I scroll the child in mobile mode, the outer layer will follow.

Link to code example:
App.js
![image](https://user-images.githubusercontent.com/58899489/192140145-f3124ce9-9e42-4412-9b27-1b684b4c6c16.png)

App.css
![image](https://user-images.githubusercontent.com/58899489/192140154-bc113553-21d3-43b0-a5b4-b768f680e408.png)

## The current behavior
the parent scroll when child is touchmove.

## The expected behavior
the parent not scroll when child is touchmove.

I saw this issues(https://github.com/facebook/react/issues/19651)， I have two questions:  

1. I'm not sure if react 18 fixed it？  
3. How do I deal with this case?

**Comment by factscub** [comment]
i want to work on this issue. please assign this to me.

**Comment by this-spring** [comment]
so, it is a bug?
How do I deal with this case?

**Comment by this-spring** [comment]
so, it is a bug?
How do I deal with this case?

**Comment by makc** [comment]
@this-spring  not a bug, but "by design" as per #19651
unfortunately they dont seem to care about preventDefault-s not working
so the work-around is to not use react's onXxx and instead do addEventListener with { passive: false } as per #20999

**Comment by this-spring** [comment]
> @this-spring not a bug, but "by design" as per #19651 unfortunately they dont seem to care about preventDefault-s not working so the work-around is to not use react's onXxx and instead do addEventListener with { passive: false } as per #20999
okk, thanks.
