### ISSUE TITLE
When can the Offscreen component be used？

### ISSUE THREAD

**Issue by FoSuCloud** [facebook/react#25320]
When can the Offscreen component be used？please

**Comment by gaearon** [comment]
When it's released in a stable version. We don't usually provide estimates for experimental features, but we're actively working on this feature.

**Comment by githorse** [comment]
Could the docs be updated with some information about `Offscreen` (i.e., a basic description of what it will do with a disclaimer that it's not yet available and subject to change)? Neither the old or new (beta) docs mention it at all. It's a big deal in the React 18 announcement, and looks like something I really need, but it took me a while to land here and figure out definitively it's not actually available yet.

**Comment by gaearon** [comment]
We generally don’t document APIs that aren’t actually added or stable. I’m not sure where you’d expect to see a notice?

**Comment by githorse** [comment]
Any updates on this one @gaearon? Is `Offscreen`, or something like it, still on the roadmap?

**Comment by githorse** [comment]
Hey React folks -- could somebody comment on this? I desperately need this functionality. I've put off figuring out how to do it myself in the hopes that the `Offscreen` component would save my bacon, but I can't really wait much longer. It would be incredibly helpful to get an updated estimate of when `Offscreen` might be available.

**Comment by markerikson** [comment]
@githorse fwiw it does exist in the daily-ish experimental builds of React.  We've been using it in https://replay.io for the last couple years.  Obvious caveats about using pre-release APIs apply (and in fact `<Offscreen>` just got renamed to `<Activity>`), but it does exist and can be used if you're willing to deal with the instability.
