### ISSUE TITLE
Bug: Unexpected useState behavior on StrictMode

### ISSUE THREAD

**Issue by asendia** [facebook/react#25330]
Not sure if this is a bug, but when using `StrictMode` whether it is for production/development build, the callback in a setState `setState(callback)` is correctly called once. But the next call to setState will trigger the callback twice using the example described below.

React version: 18.2.0

## Steps To Reproduce

1. Open https://codesandbox.io/s/recursing-firefly-gwcp3m?file=/src/App.js
2. Click "Add" counter will increment to 2
3. Click "Add" again, counter will increment to 5 (should be 3)

Link to code example: https://codesandbox.io/s/recursing-firefly-gwcp3m?file=/src/App.js

## The current behavior
setState callback is called twice on the 2nd++ setState call

## The expected behavior
setState callback is called once on the 2nd++ setState call

**Comment by asendia** [comment]
Dupe: https://github.com/facebook/react/issues/12856#issuecomment-390206425

**Comment by danieltkach** [comment]
It may or may not be a bug, but I wouldn't write the code as you did, I would do that as follows: 
`import { useState } from "react";
import "./styles.css";

export default function App() {
  const [data, setData] = useState({ counter: 0 });
  return (
    <div className="App">
      <div>Counter: {data.counter}</div>
      <button onClick={() => setData(prev => ({...prev, counter: prev.counter++}))}>
        Add
      </button>
    </div>
  );
}`

**Comment by danieltkach** [comment]
I woudn't write it as you did. A working way is:

import { useState } from "react";
import "./styles.css";

export default function App() {
  const [data, setData] = useState({ counter: 0 });
  return (
    <div className="App">
      <div>Counter: {data.counter}</div>
      <button onClick={() => setData(prev => ({...prev, counter: prev.counter++}))}>
        Add
      </button>
    </div>
  );
}
