### ISSUE TITLE
React Developer Tools shows only on Chrome's incognito window

### ISSUE THREAD

**Issue by kabeza** [facebook/react#25340]
Hi
I have Chrome on ElementaryOS Hera (Ubuntu 20.04 based)
Version 105.0.5195.125 (Build oficial) (64 bits)

I have installed React Developer Tools
When I load application ( `yarn dev` ) and then run Chrome, I try to activate manually (Extensions -> React Developer Tools)
I see this notice (but Components and Profiler tabs are not shown)

![imagen_0883](https://user-images.githubusercontent.com/274856/192821976-2891b1b9-1fb7-49b8-8e50-660d99db624a.jpg)

However, If I run Chrome on incognito mode, it works
I can see the Components and Profiler tabs

Any idea how debug that and make it work in normal Chrome window?
Thanks

**Comment by anantnipunge** [comment]
can you please assign me this project for hacktoberfest 2022 ? so that i could definitely resolve issue.

**Comment by andrewwatson** [comment]
I get the same behavior.  



Google Chrome | 105.0.5195.52 (Official Build) (x86_64)
-- | --
Revision | 412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}
OS | macOS Version 12.6 (Build 21G115)
JavaScript | V8 10.5.218.7
