### ISSUE TITLE
Bug: setState2 still uses old value of setState1 even though state1's value is already updated

### ISSUE THREAD

**Issue by TamirCode** [facebook/react#25341]
I have a couple of inputs and I want to call `setInputData` state synchronously right after I set `setInputValues` state, because it makes use of its updated value, however no matter what I try it always gets the delayed value of what it was in the previous keystroke entered to the inputs.

Even when using setTimeout, when setting the `setInputData` , it has a previous version of the `inputValues` that was set before it, no matter how much delay I give it. Even when even when both of them are deep clone or both shallow clone still same occurrence. I  don't understand how even after waiting with setTimeout for the `setInputValues` state to finish updating, my `setInputData` state is still not getting the real-time value of `inputValues`, even when the real-time value is shown inside the `<pre>` tag

I simply want to set state2 after setting state1 because state2 makes use of state1's updated value.
However I don't think useEffect subcription is an apt solution because I need the passed argument of the `inputName` to be used when setting both states.

React version: 18.0.0

## Steps To Reproduce

This is the entire app
```js
import { useState } from 'react'

export default function App() {
	const [initialValues] = useState({ email: 'initialval', city: '' })
	const [inputValues, setInputValues] = useState(initialValues)
	const [inputData, setInputData] = useState({ email: { isDirty: false }, city: { isDirty: false } })

	function inputChange(e, inputName) {
		setInputValues((prev) => {
			let clone = { ...prev }
			clone[inputName] = e.target.value
			console.warn(`setting inputValues[${inputName}] to: ${e.target.value}`)
			return clone
		})
		setTimeout(() => {
			setInputData((prev) => {
				console.log('current inputValue: ' + inputValues[inputName])
				let clone = JSON.parse(JSON.stringify(prev))
				clone[inputName].isDirty = inputValues[inputName] === initialValues[inputName] ? false : true
				return clone
			})
		}, 500)
	}

	return (
		<>
			<input onChange={(e) => inputChange(e, 'email')} value={inputValues.email} />
			<input onChange={(e) => inputChange(e, 'city')} value={inputValues.city} />
			inputValues<pre>{JSON.stringify(inputValues, null, 4)}</pre>
			inputData<pre>{JSON.stringify(inputData, null, 4)}</pre>
		</>
	)
}
```

Link to code example: https://codesandbox.io/s/react-bug-wtf-guzldd?file=/src/App.js

## The current behavior
As you can see in the screenshot, the value of `inputValues` is always behind 1 keystroke. 
![image](https://user-images.githubusercontent.com/66864667/192846709-8438fa07-1aca-4750-b74f-fe057350a401.png)

## The expected behavior
I expect by the time I am setting `setInputData` it will have access to the latest `inputValues` that was set before it.
I have heard that sometimes React batches together state updates, but this still doesn't make sense because there is even a setTimeout put in place, and usually setting states one after another has worked perfectly fine for me, and most importantly, the state is already updated everywhere else as shown in the `<pre>` tag, and by the time `setInputData` is called the updated value of `inputValues` is shown in the pre tag yet it still uses the old value.
If the current behavior is the expected behavior, I would appreciate greatly if someone shows me a way to accomplish what I am trying to do

**Comment by gaearon** [comment]
Does this help?

https://beta.reactjs.org/learn/state-as-a-snapshot

You shouldn't need to do anything special since you already have `e.target.value` and so you know what you're setting the state to.

**Comment by TamirCode** [comment]
> Does this help?
> 
> https://beta.reactjs.org/learn/state-as-a-snapshot
> 
> You shouldn't need to do anything special since you already have `e.target.value` and so you know what you're setting the state to.

yes, thanks dan :D
