### ISSUE TITLE
Select component in inspect element to be opened in IDE

### ISSUE THREAD

**Issue by Gardeal23** [facebook/react#25344]
We plan to create a method for accessing the specific file of a web component in a browsers inspect element, such that it opens on an IDE. This would allow developers a more continuous workflow between development and testing of web components. 

We recognize that the React Dev Tools browser extension accomplishes a similar task, but remains within the browser rather than directing the user to a chosen IDE.

**Comment by eps1lon** [comment]
If you go the React devtools Components tab > Settings > Components > Editor URL you can enable this behavior already:

![Screenshot from 2022-09-29 23-49-35](https://user-images.githubusercontent.com/12292047/193148468-8c270892-98ba-4f26-a842-d2588c26cbfb.png)
![Screenshot from 2022-09-29 23-49-53](https://user-images.githubusercontent.com/12292047/193148471-866de300-6b33-4ed3-a197-26f839a8d416.png)

**Comment by rejas** [comment]
Does this also somehow work with webstorm?
