### ISSUE TITLE
Bug: state changes of input[type='number'] value doesn't update real DOM

### ISSUE THREAD

**Issue by cdpark0530** [facebook/react#25384]
The problem is that state changes going into `value` prop of `input[type="number"]` don't update(synchronize) real DOM. Regardless of what type of `value` that `input[type="number"]` expects in internal implementation, (based on what I observed) it's showing inconsistent behavior.
This bug has been happening since very old version in my experience, and github issues about this are still open:
> https://github.com/facebook/react/issues/9402: A number input will always have left pad 0 though parseFloat value in onChange
> https://github.com/facebook/react/issues/13651: input[type='number'] value isn't updated

I'm writing this new bug report since they point out derived errors not its fundamental problem.

React version:
18.2.0

## Steps To Reproduce

1. create `input[type="number"]` and set `value` with state of type `number|undefined`, default empty string.
2. set `onChange`(or `onInput`) handler and change the `number|undefined` state on typing.

Link to code example: https://codesandbox.io/s/input-type-number-bug-bosfmv?file=/src/App.tsx

## The current behavior: when setting `number` on `value` with default empty `string`
Real DOM shows left pad 0. https://github.com/facebook/react/issues/9402 and https://github.com/facebook/react/issues/13651 talk about this. Putting stringified value is workaround as https://github.com/facebook/react/issues/13651#issuecomment-727244841 mentioned.

## The expected behavior: when setting `number` on `value` with default empty `string`
Real DOM should show actual `value` even if the type of initial value is `string`. For example, when the `value` is type of `number`, it should show the number without left pad 0.

## The current behavior: when setting stringified `number` on `value` with default empty `string`
Real DOM doesn't show the value that you set on `value`.
(Please look up above codesandbox link)
Putting `123--`(or whatever invalid number format you can put) results setting `undefined` on the state type of `number`, which results setting empty `string` on `value`. But it still shows `123--`.

## The expected behavior: when setting stringified `number` on `value` with default empty `string`
Real DOM should show the value that you set on `value`.

**Comment by sKopheK** [comment]
can confirm this issue

**Comment by andrewkazan** [comment]
Thank you! In your second input in sunbox, you showing how do prevent entering a set of zeros
