### ISSUE TITLE
Unable to unmount component using its instance only when it is rendered to null

### ISSUE THREAD

**Issue by vkramskikh** [facebook/react#2545]
There was a common pattern to unmount a component by its instance:

`React.unmountComponentAtNode(component.getDOMNode().parentNode);`

Now components can return `null` from `render()`, and in that case getDOMNode() also returns `null`, and the code above doesn't always work. React internally always knows to which node the component is mounted, so please make this information accessible or add a component method like `unmount()`.

My project is in process of transition from Backbone views to React and we have a helper function `universalUnmount()` which gets Backbone.View instance of mounted component and removes it from DOM. So there is no way for now to make it work with any React component.

**Comment by jimfb** [comment]
I'm pretty sure our recommendation at this point is: `ReactComponentRenderer` from https://facebook.github.io/react/blog/2015/10/01/react-render-and-top-level-api.html
