### ISSUE TITLE
Bug: use-sync-external-store not compatible with skypack

### ISSUE THREAD

**Issue by quinn** [facebook/react#25463]
React version: N/A

## Steps To Reproduce
```
<script type="module">
  import { useSyncExternalStore } from "https://cdn.skypack.dev/use-sync-external-store@1.2.0";
  console.log(useSyncExternalStore); //=> undefined
</script>
```

Link to code example:

**Comment by nihgwu** [comment]
I believe it's a problem in Skypack, btw I think Skypack is dead, try [esm.sh](https://esm.sh/) instead

**Comment by quinn** [comment]
@nihgwu esm.sh worked, nice! I didn't think to try a different host, didn't realize there was that much nuance with these package CDNs. thank you.
