### ISSUE TITLE
Bug: RulesOfHooks can't detect member expression containing a hook name if the object is not in PascalCase

### ISSUE THREAD

**Issue by mifopen** [facebook/react#25472]
https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L39-L40
```js
    const isPascalCaseNameSpace = /^[A-Z].*/;
    return obj.type === 'Identifier' && isPascalCaseNameSpace.test(obj.name);
```
Why is it necessary? Isn't it purely an artificial limitation?
Our use case is absolutely valid both from the JS point of view and from React point of view:
```js
const accessor = createEntityAccessor(entityId);
const name = accessor.useName();
```

**Comment by eps1lon** [comment]
> Why is it necessary? Isn't it purely an artificial limitation?

It's necessary to have some way to distinguish what is a hook and what isn't. Pascal case was already how almost all hooks were accesed. Meanwhile it doesn't trigger many false-positives and there's a clear path how to avoid it.

For example, getting rid of this check would trigger `jest.useFakeTimers` which is fairly common in the ecosystems.

**Comment by mifopen** [comment]
We've finally come up with this style as a workaround:
```ts
const { useName } = createEntityAccessor(entityId);
const name = useName();
```
