### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by baqarmangrani** [facebook/react#25487]
### Website or app

local personal app

### Repro steps

I was using Global context

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.25.0-336ac8ceb

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26596:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24626:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24795:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54959:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by HackerDaGreat57** [comment]
I also got this error. The code that I used to produce this error is [here](https://github.com/HackerDaGreat57/bpp/blob/d943c9a6a111e6506feae212a394ccfb04416896/main.js). (Accompanying HTML and CSS files are available too.)

**Comment by JuraJuki** [comment]
Reopening chrome DevTools fixed it for me

**Comment by mondaychen** [comment]
One possible cause of this issue is when multiple react devtool instances are running on the same page. Restarting the devtools (by close and open chrome devtools, or re-install the extension) often helps.
If this issue still persists please let me know! It would be very helpful if someone can provide a way to reproduce.
