### ISSUE TITLE
Provide a way to specify what parts of react server markup can be reused on client

### ISSUE THREAD

**Issue by Vijar** [facebook/react#2548]
It would be great to be able to have a custom checksum validator that can ignore certain branches of the DOM-tree when attempting to reuse markup.

The use case is for rendering static components. For static components that only need to be rendered once, we can just do the rendering on the server, and not have to render again on the client. Currently we have to pass down both the react markup AND the props used to generate the static markup. However, it is a waste to send those props down, if this component doesn't need to be rendered client-side.

One of the major performance concerns for using React is that apps not only have to send down markup but props as well, usually duplicating the data sent down to the client. 

Being able to specify certain components as not needing a client side re-render, thus skipping check-sum, would save k-weight of the initial page load.

**Comment by JeffRMoore** [comment]
I presume HTTP compression would work pretty well on this type of duplication.

**Comment by gaearon** [comment]
There is no checksum validation anymore but we still expect the trees to match up.
