### ISSUE TITLE
Consider warning when using the wrong case for an HTML attribute

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#255]
Like if you do `<textarea maxlength={...} />`. The current behavior is opaque and sort of confusing for people.

**Comment by abejfehr** [comment]
Sorry to comment in a closed issue, but was this ever implemented?

I see in React 15.0.1 that `maxlength` isn't converted to maxLength or warned about.

I made a fiddle for convenience [here](https://jsfiddle.net/Lvkxvoo3/)
