### ISSUE TITLE
Bug: devtools "select an element in the page to inspect it" does not work for ShadowRoot

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#25519]
React version: unrelated

## Steps To Reproduce

Link to code example: https://codesandbox.io/s/epic-sammet-hmdq7c?file=/src/index.js

![image](https://user-images.githubusercontent.com/5390719/196852174-84fea9c9-414a-4ccf-ac05-449d82e50f36.png)

## The current behavior

Cannot hover to inspect element inside ShadowRoot

## The expected behavior

Works well.

**Comment by hoxyq** [comment]
Fixed by https://github.com/facebook/react/pull/26888.
