### ISSUE TITLE
[DevTools Access] Chrome extension request pending for React Developer Tools

### ISSUE THREAD

**Issue by paulmambu** [facebook/react#25517]
Hi there, trying to download the chrome extension for the react developer tools.  Who needs to approve it?  Is it React side?  Thanks

**Comment by Shrey00** [comment]
@paulmambu what do you mean by 'who needs to approve it?', can you elaborate on your issue?

**Comment by paulmambu** [comment]
Hi yes, exactly.  May I know who needs to approve it?  Thanks
