### ISSUE TITLE
Security vulnerability in React!

### ISSUE THREAD

**Issue by watson** [facebook/react#25521]
I've tried to report a security vulnerability via https://www.facebook.com/whitehat as instructed in the [React security policy](https://github.com/facebook/react/security/policy). The report was unfortunately rejected by Meta without any means of reopening it, because I didn't specify any specific apps that where vulnerable. They seemed to want to know if Facebook.com, Instagram or one of their other services were vulnerable - which I do not know.

Is there another way I can submit information about security vulnerabilities in React, that's not via https://www.facebook.com/whitehat?

I don't care about participating in your bounty program, I just want a channel to communicate security vulnerabilities, so that they can be fixed. For reference my original  https://www.facebook.com/whitehat/ ticket ID is 10159214301198727 if you have the ability to look it up.

**Comment by gaearon** [comment]
Can you email me pls? gaearon@fb.com
