### ISSUE TITLE
Bug: SVG executes contents of script tags.

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#25522]
Script tags within SVG execute their contents when rendered with React. This is surprising, and creates opportunities for XSS attacks when rendering user generated content.

React version: 17.02, 18.2.0

## Steps To Reproduce

1. Create an `<svg>` element with a `<script>` tag in it
2. Render that element
3. The children of that script tag will parse and execute as JavaScript

Link to code example:

https://codesandbox.io/s/modest-voice-kywwwu

## The current behavior

In this example, you'll see that the script tag within HTML does not execute, however the script tag within SVG does.

## The expected behavior

I would have expected the script's contents to be ignored in SVG, as it does in HTML.

**Comment by StefanoMartella** [comment]
Hi @nhunzaker,

I noticed the same behavior but it is probably wanted; SVG elements have their own namespace and behavior, separate from HTML elements which probably allows scripts execution. The same behavior is present in other libraries too (https://codesandbox.io/s/exciting-danny-cd7xqu?file=/src/app/app.component.html).
