### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by irtaza9** [facebook/react#25528]
## Doing
I am setting a parent component state inside useCallback when onChange of an input element take place.

## Warring
![image](https://user-images.githubusercontent.com/98938307/197277126-ed360ece-d601-4b2c-b6e7-410885fb0fdd.png)

## Need Help
I need help regarding this issue as I am not familiar with it.

**Comment by Maverick17user** [comment]
Cold you, please, provide more code (or playground) from this use-case?

**Comment by irtaza9** [comment]
## Code

              <div className="w-full mt-3">
                <div className="form-group">
                  <input
                    type="text"
                    className="form-control"
                    readOnly={true}
                    ref={props?.posttype}
                    id="posttype"
                    **value={props?.finalfile?.type}**
                  />
                </div>
              </div>

I was setting the value in input element when user choose the file and the props.finalfile is the state created in parent component. yesterday I was using the onChange on this element that's why I was getting that warring, then I remove the onChange and used ref to getting the element value and apply readOnly rule to input element and I solved this. 

This input element is just to show the value of select file that user will select and i grab that value using ref not by onChange as onChange on triggers when an event occurs to that element.

Btw, Thank you for putting your time to my request.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
