### ISSUE TITLE
Suggestion for JSX syntax simplification

### ISSUE THREAD

**Issue by gebbber** [facebook/react#25544]
## Suggestion
I would like to suggest enhancing the JSX specification to allow:

```jsx
return <button {onClick}>Text</button>
```

to be parsed as equivalent to:

```jsx
return <button onClick={onClick}>Text</button>
```

## Rationale

This would improve readability and shorten line lengths, especially when several props are being used that share names with variables.

It would also tend to encourage adoption of variable and function names that match the intended prop names, such as `function onClick(ev) {}` instead of `function clickHandler(ev) {}`, which has enhanced readability in my own projects. (Once this convention is adopted, the present suggestion also reduces redundancy, again improving overall readability.)

## Current Workaround
Current workaround is as follows, but is not quite as elegant:
```jsx
return <button {...{onClick}}>Text</button>
```

## Additional Suggestion
This enhancement suggestion could be taken further to allow an arbitrary number of comma-delimited arguments to be spread into props of the same names:
```jsx
<component {arg1, arg2, etc} />
```

...equivalent to:
```jsx
<component {...{arg1, arg2, etc}} />
```

...also equivalent to the "standard" syntax:
```jsx
<component arg1={arg1} arg2={arg2} etc={etc} />
```

**Comment by sahithyandev** [comment]
The current workaround does look elegant to me. I don't think it's worth the time to implement your suggestion; when a simple workaround exists (and isn't too trivial). : )

**Comment by augustotestingaccount** [comment]
Olá
