### ISSUE TITLE
Bug: Why does react fail to implement bidirectional data binding

### ISSUE THREAD

**Issue by cakeerrr** [facebook/react#25553]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by hawx1993** [comment]
a good solution to splitting UI and business logic, see: https://github.com/hawx1993/hooks-view-model

**Comment by hawx1993** [comment]
If you want to use  bidirectional data binding, see my solution  here: https://github.com/hawx1993/hooks-view-model
