### ISSUE TITLE
Bug: Using `useSyncExternalStore` changes don't get reflected in UI in production

### ISSUE THREAD

**Issue by alinnert** [facebook/react#25558]
I've implemented a very minimalistic store and connected it to React using `useSyncExternalStore`. It does work as expected in development mode but doesn't in production mode. In production it does work under the hood but components don't seem to get notified. The changes made to the external store become visible once I force a re-render.

React version: 18.2.0

## Steps To Reproduce

1. Open demo site
2. Add and remove items or clear the entire list (behavior should be different depending on the environment)

Link to code example:

- CodeSandbox (development mode): https://codesandbox.io/s/react-test-7wm0sn
- Deployment (production mode): https://csb-7wm0sn-bxa1eq1le-alinnert.vercel.app/

## The current behavior

In development everything works fine. In production only adding items works. Removing one or all items does work but doesn't get reflected in the UI. To show this I've added a "refresh" button that just increments a value that's being used in a `key` prop. Changing the value of this `key` prop updates the UI to properly show the content of the external store.

## The expected behavior

`useSyncExternalStore` in production should work just like it does in development mode.

**Comment by vkurchatkin** [comment]
It seems that you are not subscribing correctly:

```ts
export function subscribe(onStoreChange: () => void): () => void {
  // <-- should subscribe here
  return () => listeners.push(onStoreChange); // and unsubscribe here
}
```

basically you are not subscribing at all in production scenario.

**Comment by alinnert** [comment]
Oh, you are right. Then it worked in development mode because React renders everything twice and the subscription got made with the first unmount. I'm not sure though why adding items works in production. It shouldn't either IMO.

But to be fair, the documentation is not very clear about what `subscribe` should look like. But the docs are being rewritten anyway.

So, thank's a lot!
