### ISSUE TITLE
React.PropTypes.shape... WTF?

### ISSUE THREAD

**Issue by mbrio** [facebook/react#2556]
Sorry for the title, but it was a WTF moment for me when I found that to compare a property to an object schema that the method call was `shape`. When you read your documentation it makes only slightly more sense than when you see it in code, which is to say it makes no sense when you see it in code.

Anyway, I know this isn't the highest priority item in the world but I would love to request a name change to this method, or at least a synonym that makes more sense like `schema`, or really anything other than `shape`.

**Comment by crisu83** [comment]
+1 for renaming shape to something more understandable, I was as mind-blown when I finally learned the meaning of shape in React.
