### ISSUE TITLE
What is the reason to patch the fetch?

### ISSUE THREAD

**Issue by artalar** [facebook/react#25573]
[This](https://github.com/facebook/react/blob/main/packages/react/src/ReactFetch.js) looks so unpredictable:

- [works only for `get` and `head`](https://github.com/facebook/react/blob/28a574ea8f5d0efa95f861abca26a67af47dd0c0/packages/react/src/ReactFetch.js#L79) (Many APIs request data via `post`)
- do not support XMLHttpRequest / WebSocket / WebTransport / postMessage and other side-effects
- you already have a bad practice with `console.log` patching
- `request.json()` will parse and return a new data each time, so dependent effects will recall anyway?
- finally, it just super bad pattern to patch globals, it always leads to problems eventually. [Next.js already holds](https://github.com/vercel/next.js/blob/canary/packages/next/server/app-render.tsx#L226) "next" word in fetch options, which disallow to use it in feature platform updates.

So, what is the reason to patch the fetch?

**Comment by judehunter** [comment]
This is a seriously concerning choice

**Comment by ColeyG** [comment]
Evil and blatant attempt to shift JS opinion.

**Comment by Urthen** [comment]
This is an absurd breach of what developers expect out of something like React. Don't monkeypatch existing, standardized browser APIs. If you want to build your own fetch wrapper, fine - but invisibly hiding normal browser behavior like this is asking for problems down the road.

**Comment by ColeyG** [comment]
If you don't think this is malicious (or could become so) you aren't paying attention

**Comment by sebmarkbage** [comment]
Wait for the RFC.

**Comment by Urthen** [comment]
Aren't RFCs normally written *before* code is merged into `main`?

**Comment by sebmarkbage** [comment]
Our RFCs are almost never written before code. We iterate before we're comfortable with it. We don't just publish any first idea that comes to us.

**Comment by eps1lon** [comment]
This code is not part of a stable release. You won't see this in your app if you're just installing `@latest` versions.

This is better discussed once the RFC is published.

**Comment by ecyrbe** [comment]
@sebmarkbage so maybe keep it in a branch, merging experiments to main is bad if you need to rollback.

**Comment by kassens** [comment]
We prefer working on main to avoid conflicts at the cost of needing to iterate on the design there.

Let's wait for the RFC to continue discussion there!

**Comment by lovetingyuan** [comment]
自以为是的react团队

**Comment by IvanAdmaers** [comment]
React & Next might slow web development due to this stupid action. Monkeypatching it’s always bad. Especially, when you do this for native browsers API. It seems like Facebook hired some freshman’s to develop React. It can’t did a developer that has any experience or can think at least one day ahead. React and Next were my favorite technologies but now I can’t say it anymore. Damn, I really can’t believe that we make this mistake again. Didn’t we have enough problems with such monkeypatching lovers as PrototypeJS? Gosh, I just can’t believe that React team made this mega stupid action. God save the XHR…

**Comment by silverwind** [comment]
This will cause issues for example when a function accepts a `fetch` implementation argument and compares it by identity like `fetch === globalThis.fetch`. I strongly recommend against this monkey-patching and I would probably avoid using any react version that does.

**Comment by GottZ** [comment]
I just want to leave this here for you to think about and for anyone coming after me to see that there is an actual caching implementation present these devs here seem to not know about:
https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

you are redefining the wheel here AND pollute global objects.

the existing spec also handles this button correctly:
![image](https://user-images.githubusercontent.com/559564/216270615-f31c27fc-fa99-4d50-8fa4-7429cbd6ccbe.png)
so just you know.. you are breaking dev tools here..

**Comment by gaearon** [comment]
Again, this change is *not* a part of any stable release. We've heard your feedback, and will adjust the behavior changes to be opt-in (although we likely will encourage patching). We'll post an RFC with the updated proposal.

**Comment by supuwoerc** [comment]
+1，no intrusive changes should be made

**Comment by stewones** [comment]
I guess we all appreciate your response @gaearon but it doesn't answer the original question. what's reasoning behind overwriting native fetch? I'm legitimately curious.

**Comment by Nisfan** [comment]
@stewones, It's clearly mentioned here https://github.com/vercel/next.js/issues/52069#issuecomment-1632846905

**Comment by daukantas** [comment]
Your github input has been violating my email !

Attention:  Please  make adjusted  changes to prevent your input entering this email site.


Warning! Please review “Scams and Identity Theft Attempts Targeting International Affiliates”, which can be found at https://www.hupd.harvard.edu/scams-targeting-international-affiliates
Scams and Identity Theft Attempts Targeting International Affiliates<https://www.hupd.harvard.edu/scams-targeting-international-affiliates>
Introduction
www.hupd.harvard.edu<http://www.hupd.harvard.edu/>
.



________________________________

**Comment by OZZlE** [comment]
Is this part of the latest stable release of React now? And next.js? We seem to still not get the behavior in latest next.js and I cannot find any information about it
