### ISSUE TITLE
Suggestion: why not make accessing and changing the state more flexible?

### ISSUE THREAD

**Issue by anasouardini** [facebook/react#25581]
It would provide the ability to create a state, read the state 
and set the state form anywhere in the code base.

I imagine It would be something like this:

## adding the state to the global state

```js
import {useGlobalState} from 'react';
const ProviderComponent = ()=>{

  const [ceateState, _, __] = useGlobalState();

  // the first arg is the component key
  // the second arg is a list of states
  createState('providerComponent', {userStatusState: 'online', isUserVIPState: false});

  return <></>
}
```

##  now I can use it like so:

```js
import {useGlobalState} from 'react';

const ConsumerComponent = ()=>{
  
  const [_, getUserStatus, setUserStatus] = useGlobalState('providerComponent', 'userStatusState');

  const userStatusStateCopy = getUserStatus();

  const changeUserStatusState = ()=>{
    setUserStatus('offline');
  }
  return <p onClick={changeUserStatusState}>{userStatusStateCopy}</p>
}
```

**Comment by hawx1993** [comment]
a good solution to splitting UI and business logic, see: https://github.com/hawx1993/hooks-view-model

**Comment by segfaulty1** [comment]
> a good solution to splitting UI and business logic, see: https://github.com/hawx1993/hooks-view-model

this is robust, thank you

**Comment by hasanbisha** [comment]
If im not mistaking what you are looking for, context will solve your issue. To be honest accessing and changing global state, especially updating global state, from a component which is nested really down, will make the code messy

**Comment by segfaulty1** [comment]
> If im not mistaking what you are looking for, context will solve your issue. To be honest accessing and changing global state, especially updating global state, from a component which is nested really down, will make the code messy

context is not good from states that are changing a lot though.

What I actually want is a way to access a state of a component from any other component, without having to prop-drill or extracting the state to some global object.

I want to be able to read the state or re-render a component from any other component. just by writing a component's key or name and a state name in that target component.

I've wrote a simple one before, and it was a good and clean way to pass states between components, read some state in a child of a sibling component or re-render it and so on.

I can precisely access components flexibly from everywhere without any overhead. It feels like I have more control and flexibility.
