### ISSUE TITLE
Bug: StrictMode double mounting doesn't clean up effects from first mount

### ISSUE THREAD

**Issue by juzerzarif** [facebook/react#25614]
React version: 18.1.0

## Steps To Reproduce

1. Create a react component with a `useState` hook with a lazy initializer that produces a unique result on each invocation.
2. Use that state in an effect and effect cleanup function using the `useEffect` hook.
3. Render the component under strict mode.

Link to code example:
https://stackblitz.com/edit/react-ts-kkwhd4?devToolsHeight=33&file=App.tsx

## The current behavior
When in strict mode in react 18, every component is mounted, unmounted, and remounted immediately the first time it mounts. It looks like when react runs effect cleanups for the first mount, it actually calls the effect cleanups (and effects for that matter) registered during the second mount.

If your state that the cleanup formed a closure on is not the same between the 2 mounts (for e.g. if your state is the result of a unique id generation), you never end up cleaning up the effects from the first mount which can possibly introduce memory leaks or worse.

## The expected behavior
When cleaning up the effects before the commit phase of the second mount, react should run the effect and cleanup callbacks from the first mount.

**Comment by markerikson** [comment]
At first glance, this sounds intentional, and the reason why StrictMode double-renders components and double-runs effects in the first place.  By _forcing_ these bugs to happen earlier in development, they'll be more noticeable so you can fix them now.

**Comment by juzerzarif** [comment]
I expected the double mounting in StrictMode. The thing that strikes me as buggy is that the effect and effect cleanup that run as a result of the unmount aren't the ones from that first mount but from the second one.

In the code example you can see that the useEffect callback runs twice - both times with the state closure from the second mount. I expected it to run once with the state closure from the first mount, clean up with the state closure from the first mount, and then run the effect a second time with the state closure from the second mount.

Is that not what's supposed to happen? If so, what's the reasoning behind re-running the effect from the second mount only?

**Comment by MelvinWM** [comment]
juzerzarif, I believe markerikson is correct. The new React documentation site describes the requirement that `useState`'s overload with a parameter for a function for lazily evaluating expensive computations must be pure:

https://beta.reactjs.org/apis/react/useState#usestate

>If you pass a function as initialState, it will be treated as an initializer function. It should be _**pure**_, should take no arguments, and should return a value of any type. React will call your initializer function when initializing the component, and store its return value as the initial state. [See an example above.](https://beta.reactjs.org/apis/react/useState#avoiding-recreating-the-initial-state)

(highlighting by me).

So I believe this issue should be closed. And you may have to change your code if you have side-effects in the function you pass to `useState`.

**Comment by MelvinWM** [comment]
Also, I really like the new documentation site, though it is not yet finished.

**Comment by markerikson** [comment]
I'm actually waffling a bit on my original answer.

If you look at https://github.com/reactwg/react-18/discussions/19 , it talks about how it will run effects twice in `StrictMode`, but it doesn't specifically talk about leaving one of them un-cleaned-up.

So I'm not sure what the _intended_ semantics are here.

**Comment by MelvinWM** [comment]
I am no expert on `StrictMode`. But, could an argument not be made that it is OK for `StrictMode` to assume that the function passed to `setState` must be pure and thus run it twice? If the documentation (at least in the new, though unfinished, documentation site) describes it as having to be pure?

**Comment by MelvinWM** [comment]
Though I do not know whether double-running `setState`'s function parameter by `StrictMode` has been documented.

**Comment by eps1lon** [comment]
As far as I can tell the issue is with having a side-effect in `useState(initializerFn)`. `initializerFn` is running twice even in React 17 and documented:

> [...] This is done by intentionally double-invoking the following functions:
> [...]
> Functions passed to useState, useMemo, or useReducer

-- https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects


So this is not about cleaning up effects from the "first mount" but cleaning up side-effects from the first render which has no API since renders et al. should not have side-effects to begin with
