### ISSUE TITLE
Bug: transition update after sync update calculate state wrong

### ISSUE THREAD

**Issue by Josscii** [facebook/react#25639]
here is the demo code: https://codesandbox.io/s/transitionpuzzle-ekxdx7

react version: 18.2.0

from my perspective, I start a transition-level update and a sync-level update in a click callback, first the count is updated to 1, it is reasonable, but after this update, the count is updated to 3, why, should't it be updated to 2, as it should replace the previous value.

I traced down the react source code, found that in the transition update, the 'newState' is updated to 2, and then update find a next update which is the `count => count + 1`, I don't understand why this `completed` update is still in the updateQueue?

I thought it should be a bug? If not, please help me why this happens, there must be somehing I'm missing, thanks in advance.

**Comment by NaNshekhar04** [comment]
Hey @Josscii ! **NEI !!** Is this the problem you were facing ? Your previous state with the startTransition was not updating to the state you were setting onClick !
 
I have Fixed some part of your code if this was something you were searching for than here is the link to my sandbox you can refer and let me know was this the same you were trying to do !

#### Here is the link :- https://codesandbox.io/s/transitionpuzzle-forked-lcu9yw?file=/src/App.js

Thank You !

**Comment by Josscii** [comment]
@NaNshekhar04 Sorry, I don't think we are talking about the same thing, thanks for your reply.

**Comment by Josscii** [comment]
it's not a bug, it's just how react works, when react skip a update, while this skiped update begin, it will calculate the updates behind it again.
