### ISSUE TITLE
Suggestion: Set list for className 

### ISSUE THREAD

**Issue by rafikalid** [facebook/react#25637]
React version: all versions

# The issue
We use heavy third party libraries to work with `className`.
This result in big code and downgrade performance

## The current behavior
`element.className` allows only a string as value

## The expected behavior
Accept a list of strings, null, undefined or false

```ts
<div className={['class1', 'class2 class3', null, undefined, 0, false]} />
// Should result
<div className="class1 class2 class3" />
```
So we can write code like this:
```ts
<div className= { condition ? 'classIfTrue' : null } />

<ComponentX className={ ['class1', condition ? 'class2' : 'class3', condition2 && 'class4' ] }
```

**Comment by hasanbisha** [comment]
For my opinion react should not give className utilities, it will distract focus from other things. I would be a liar if I said that i don't use third party libraries for this thing, but it's not a big matter. I would suggest [clsx](https://www.npmjs.com/package/clsx)
