### ISSUE TITLE
Bug: Chrome Incognito Mode is not sending custom request header along with the request.

### ISSUE THREAD

**Issue by MuhtasimMusfiqZarab** [facebook/react#25648]
React version:
"react": "^17.0.2",

## Steps To Reproduce

1. Visit this example staging application:` jaunt.ixorasolution.com`  using chrome and inspect the network request.
2.  Inspect this request : `vehicle-types/`
3. The request header would look something like this:
`GET /v1/api/public/vehicle-types/ HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Authorization: Bearer xxxxx..................
Connection: keep-alive
Host: jaunt.ixorasolution.com:2007
Origin: http://jaunt.ixorasolution.com
Referer: http://jaunt.ixorasolution.com/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
X-Timezone: Asia/Dhaka
`

Here 'X-Timezone' is added with the request.

## The current behavior

if I visit the same page using Chrome incognito and inspect the same network request. Then I don't find  'X-Timezone' inside the network request header.

## The expected behavior

if I visit the same page using Chrome incognito and inspect the same network request. Then I should find  'X-Timezone' inside the network request header.

**Comment by Pranav-yadav** [comment]
@MuhtasimMusfiqZarab 
It seems obvious behavior (current) in _Incognito Mode_. **Not sure if it's relevant** but you can checkout [this](https://www.google.com/chrome/privacy/whitepaper.html#:~:text=The%20X%2DGeo%20header%20will%20never%20be%20sent%20in%20Incognito%20mode.):
> The `X-Geo` header will never be sent in Incognito mode.

`X-Timezone` seems _somewhat_ related to `X-Geo`

**Comment by MuhtasimMusfiqZarab** [comment]
@Pranav-yadav I am one of the team members of the project. I have created this custom header X-Timezone. It's only provides the region from which the user is accessing the site. @Pranav-yadav X-Timezone is not related to X-Geo. I have tried to send a string in a custom header named X-Abc. It produces the same result. It is not shown inside incognito.
