### ISSUE TITLE
Bug: save ref into state by callback ref with useImperativeHandle will cause  infinite loops error

### ISSUE THREAD

**Issue by csu-feizao** [facebook/react#25649]
Hi. In my case, I want to save every instance of ref in a closure. So I saved ref into state to rerender my component while ref changed,  then to rerun the `useMemo/useCallback` function. But I find this would cause infinite loops, and when I remove `useImperativeHandle` hook, everything works fine. Is it a bug?

![image](https://user-images.githubusercontent.com/14802930/200503646-cf94f7bd-2f49-4322-ab9b-6603c91521cb.png)
 

React version: 16.14.0

## Steps To Reproduce

1. Create a component with useImperativeHandle 
2. Using this component with callback ref, and save ref into state

Link to code example: [codesandbox demo](https://codesandbox.io/s/useimperativehandle-jytr2x?file=/demo.js:411-432)

## The current behavior

 infinite loops error

## The expected behavior

only rerender twice.

**Comment by vkurchatkin** [comment]
`useImperativeHandle` hook has `deps` argument that should be used to prevent unnecessary ref updates. If `ref` is a ref object that might not be a problem, because updating it does no trigger rerenders. In your case each render of `FancyInput` triggers ref update, which triggers `App` rerender, which triggers `FancyInput` rerender, etc.

**Comment by csu-feizao** [comment]
> `useImperativeHandle` hook has `deps` argument that should be used to prevent unnecessary ref updates. If `ref` is a ref object that might not be a problem, because updating it does no trigger rerenders. In your case each render of `FancyInput` triggers ref update, which triggers `App` rerender, which triggers `FancyInput` rerender, etc.

Thank you. I missed the `deps` argument while looking document.
