### ISSUE TITLE
Bug: memory leak on props when parent doesn't change, but child using props changes (in the same jsx)

### ISSUE THREAD

**Issue by jonenst** [facebook/react#25658]
React version: 16.8 to 18.2.0

## Steps To Reproduce

1. pass a prop that has a big memory footprint to an element A
2. A has a parent in the same jsx that doesn't change and doesn't use anything (e.g. a plain div)
3. react renders A with the big prop BIG1
4. change the bigprop and rerender
5. react renders A with the big prop BIG2.
6. A doesn't have a reference to BIG1 anymore. But the dom element of the parent of A that was rendered at step3 (which does have a reference to big1 through parentDomElement.reactPropsXXXXXX.children.A.props.big1) is reconciled (because the parent doesn't change) and reused as is, which prevents garbage collecting of big1. Nothing uses big1.

In my experience, this can happen in quite a lot of ways in practice. It does require one dom element (the parent) per leaked prop, but this is so pervasive that these elements may exist in a lot of places throughout the app, holding references to props at the instant of their render. The more instants at which different parts of the app are rendered, the more memory can be leaked. And if the app renders some kind of dynamic list that grows, then there is a practically unlimited supply of parent elements to hold old unused references. 

It's also something that is very easy to introduce as a regression by simply starting to use a big variable in a closure (not even related to anything react, for example just mapping over an array), because it is then added to the context of all closures in this render function, some of which may be passed to react components as props.

Of course this happens all the time in a normal react app for all the props (increasing memory usage by (guessing) 10x or 20x), but this is not really a problem for most people where the whole app state described by all the props is probably less than 100kb (the app then uses megabytes of memory, which is fine by modern standards). Or for apps that naturally unmount the whole dom frequently, which does allow garbage collecting these old unused propos.

Link to code example:
this one is a "normal code" that has more chances of happening in practice (uses a closure that capture the big value as the prop leaking memory)
https://0xhtw5.csb.app/ (code: https://codesandbox.io/s/react-memory-leak-0xhtw5)

this one is a more artificial repro which is arguably more understandable:
https://1pw8bf.csb.app/ (code: https://codesandbox.io/s/react-memory-leak-plain-1pw8bf)

## The current behavior
Any prop (and when passing closures as props, any variable of a render function used in at least one closure) may be retained by dom elements that are parents of elements that use these props in the same jsx, when the parent doesn't change at the same time as the child.

## The expected behavior
Ideally, props of children should not be retained by dom elements of parents that don't even use them. If this is an inherent limitation of the react model, then maybe document it a lot with big warnings ? Add tools to detect it automatically ? Describe recommended code structure and pattern to avoid this problem ? Not sure..

Thanks in advance !

**Comment by jonenst** [comment]
Bump

**Comment by onnlucky** [comment]
This is exactly what we ran into at framer.com . Crashing chrome with out of memory. Because these initial props can indirectly hold on to our document data structure. When we have to reload that data from the server, we now have two documents in memory, and these can be very large.

As a workaround we now remount the UI when the document is reloaded in such a way.
