### ISSUE TITLE
Duplicate setting sibling

### ISSUE THREAD

**Issue by yangjie111** [facebook/react#25653]
During the update of react, the cloneChildFibers function may be used in the beginWork phase. This function will call createWorkInProgress internally to create workInProgress or directly use the workInProgress. During createWorkInProgress, the brotherhood of workInProgress will be assigned, but at the end of cloneChildFibers, the brotherhood property that was set just now will be set to null. What is the reason for this step?

**Comment by ataoll** [comment]
Back end Library Location Management System
