### ISSUE TITLE
Bug: Rules of hooks does not check children function of component rendered within a Class Component

### ISSUE THREAD

**Issue by dlane-stripe** [facebook/react#25656]
React version:

## Steps To Reproduce

1. Create a class component
2. In the render function, return a component that expects a function as a child
3. Define the child function in-line, and call a React hook or custom hook within that child. 

Link to code example: https://codesandbox.io/s/bold-grass-teutjm?file=/src/TestComponent.tsx

## The current behavior
There is no rules-of-hooks violation on this hook usage, even though it clearly violates the rules of hooks.

## The expected behavior
The callsite of the hook should be flagged as a violation of the rules of hooks.

**Comment by TomDo1234** [comment]
I have managed to replicate this bug here [https://github.com/TomDo1234/ReactHookRuleBug](https://github.com/TomDo1234/ReactHookRuleBug)

**Comment by dlane-stripe** [comment]
bump

As far as I can tell, this has not been fixed

**Comment by dlane-stripe** [comment]
This error is still unresolved and active. Any chance that this will be addressed at some point?
