### ISSUE TITLE
Bug: updating array in state updates other states too

### ISSUE THREAD

**Issue by Tasztalos69** [facebook/react#25657]
React version: 18.2.0

Creating multiple useState hooks with the same initial data, and then updating an array in just one of them updates the other ones as well.

## Steps To Reproduce

1. Create two states with the same data (and make one property an array)
2. Update the array property in just one of them

Link to code example: https://codesandbox.io/s/react-multiple-state-xhz9wu

## The current behavior
Both states update

## The expected behavior
Only the updated state updates

**Comment by frostzt** [comment]
Was able to confirm this. And I also don't think this should be the behavior, even if you initialize several states with an object it should deep clone them separately. I would love to pick this up, new so any guidance would be most welcome! :)

**Comment by sacru2red** [comment]
It's bug?
I Think just human error to set init state..
https://codesandbox.io/s/react-multiple-state-forked-2ldliq?file=/src/App.js

**Comment by hasanbisha** [comment]
there is mutation in this example, it is not a bug for my opinion

**Comment by Tasztalos69** [comment]
@sacru2red originally I populated the state with a useEffect, the initial state is just for showcase.

If it is indeed intended behavior, could someone explain why? It seems illogical to me that both states update, and (maybe I missed something) but I couldn't find anything about why shouldn't I do what is in the example.

**Comment by Tasztalos69** [comment]
I see @rupakhetibinit , thanks.
