### ISSUE TITLE
Bug: React.isValidElement( ) Unable to check the hok function component

### ISSUE THREAD

**Issue by qq281113270** [facebook/react#25665]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

## The expected behavior

React.isValidElement( ) Unable to check the hook function component ， 

With the hook function component, babel, which is compiled into es5 code, is sometimes not executed with createElement, but mutated into a function, Like the compiled code in the image below。
![123456](https://user-images.githubusercontent.com/20044598/201306350-c3dc9be6-3afb-4ef0-bc1d-6c29bcd35d7c.jpg)

It's not compiled like this
<img width="972" alt="image" src="https://user-images.githubusercontent.com/20044598/201306838-b1d072b9-2b8d-4461-bc7c-15d648a79bb8.png">

But rendering is fine。

But my react route requires the isValidElement api，Because I want to know whether the current variable is a component or a function, and choose a different way to execute it。
the reason for this problem is that my imported component is in promise mode.

If you have time, can you help me look at this bug？

Here's how I wrote react-lazy-router-dom  https://github.com/qq281113270/react-lazy-router-dom  ，I need this isValidElement to determine whether it's a component or a function 。

In addition, if you think I wrote react-lazy-router-dom well, could you please help me make a friendship link

**Comment by eps1lon** [comment]
> I need this isValidElement to determine whether it's a component or a function

`isValidElement` cannot distinguish component from function:

```js
isValidElement(<Component />); // true
isValidElement(Component); // false
isValidElement(() => <Component />); // false
```

**Comment by qq281113270** [comment]
> > I need this isValidElement to determine whether it's a component or a function
> 
> `isValidElement` cannot distinguish component from function:
> 
> ```js
> isValidElement(<Component />); // true
> isValidElement(Component); // false
> isValidElement(() => <Component />); // false
> ```



> > I need this isValidElement to determine whether it's a component or a function
> 
> `isValidElement` cannot distinguish component from function:
> 
> ```js
> isValidElement(<Component />); // true
> isValidElement(Component); // false
> isValidElement(() => <Component />); // false
> ```
  isValidElement(<Component />);  ， The judgment is inaccurate。
test code 
```
const lazy = (loader) => {
  lazy.loaderArr = [...lazy.loaderArr, loader];
  return () => {
    return loader()
      .then((res) => {
        return res.default;
      })
      .catch((e) => {
        throw new Error(e);
      });
  };
};
lazy.loaderArr = [];


 let = Component = lazy(() =>
      import(
        /* webpackChunkName:"accountManagementDetails" */ 

      "client/pages/Index/pages/system/pages/AccountManagement/index.js"  // this is  Component  path

      )
    )
    console.log("Component===", Component);
    console.log("<Component/>==", <Component />);
    console.log("isValidElement==", isValidElement(<Component />));
    debugger;

```
If I use   <Component />  ,He will become a vnode, 
 isValidElement(<Component />)  Will return true。
 But Component isn't really a component, it's a component promise loader。 expect  <Component />  Will return false。 So isValidElement can't tell if it's a real component.

test result
![image](https://user-images.githubusercontent.com/20044598/204095208-2679a0b4-56c0-489c-817e-8ab177a59f17.png)

Is there any other way you can tell if it's a component or a function or a promise.
