### ISSUE TITLE
[DevTools Bug]: react-devtools depends on vulnerable version of electron

### ISSUE THREAD

**Issue by slobo80** [facebook/react#25667]
### Website or app

https://github.com/facebook/react/blob/main/packages/react-devtools/package.json

### Issue
electron package versions <18.3.7 suffer from a security vulnerability: "Exfiltration of hashed SMB credentials on Windows via file:// redirect".
See https://github.com/advisories/GHSA-p2jh-44qj-pf2v

### Solution
Upgrade electron dependency in react-devtools to >18.3.7

### How often does this bug happen?

Every time

**Comment by a7madgamal** [comment]
yes, it's also too old that It's not working on latest MacOS. when I debugged it seems it can't open electron
