### ISSUE TITLE
Bug: Event handlers are not reconciled as expected when conditionally rendering buttons inside a form

### ISSUE THREAD

**Issue by vxsl** [facebook/react#25661]
React version: 18.2.0

## Steps To Reproduce

1. Create a `form` containing two buttons, one of them with `type="submit"` and the other with `type="button"`. Conditionally render one or the other based on state that is mutated by the form's `onSubmit` handler and the `type="button"` `button`'s `onClick` handler.
2. Observe that the `button` with `type="button"` incorrectly triggers the `form`'s `onSubmit`  handler.

Link to code example
https://codesandbox.io/s/dreamy-darkness-dodxv5?file=/src/App.js

## The current behavior

In the above scenario, the button with `type="button"` is triggering the parent form's `onSubmit` handler.

https://user-images.githubusercontent.com/53827672/201153504-72ade059-2e5e-45e4-8589-1367feab9e0f.mp4

## The expected behavior

In the above scenario, the button with `type="button"` should not trigger the parent form's `onSubmit` handler. Currently, this can be achieved by adding a `key` prop to one or both `button`s:

https://user-images.githubusercontent.com/53827672/201153571-bf852b33-f143-4e7c-bba9-98c699934195.mp4

**Comment by TNick** [comment]
I don't think this has anything to do with React, specifically.

Adding a `e.preventDefault();` in the [button's](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) `onClick` handler fixes the issue.

```js
import { useState } from "react";

export default function App() {
  const [someState, setSomeState] = useState(false);
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault(); // don't reload the page
        console.log("onSubmit");
        setSomeState(true);
      }}
    >
      {someState ? (
        <button
          type="button"
          onClick={(e) => {
            e.preventDefault();
            console.log("onClick");
            setSomeState(false);
          }}
        >
          button
        </button>
      ) : (
        <button type="submit">submit</button>
      )}
    </form>
  );
}

```

**Comment by vxsl** [comment]
@TNick thanks for your reply. Why would the non-`submit` button's default action trigger form submission though?

If you remove the conditional rendering, the button does not have this default action:

https://codesandbox.io/s/blue-fog-64h33z?file=/src/App.js

**Comment by bosiwa1** [comment]
that look cool

**Comment by vxsl** [comment]
@TNick 

> Seems that if you pull out the submit button the error is gone. In this case the code works as expected.

Yes, I think this shows that React is failing to reconcile the event handlers between the two buttons properly.

> Also, giving keys to the elements solves the problem:

Yes, I mentioned this in my original post, but it should not be necessary.

**Comment by yukiyokotani** [comment]
I have encountered a similar issue. #25887
As per the sample I linked in my issue, the non-submit button in question now is submitting an unrelated form even if it does not have a form owner, just because it is conditionally rendering. I believe this is a bug in React.

**Comment by samirtiwari932** [comment]
import { useState } from "react";

export default function App() {
  const [someState, setSomeState] = useState(false);
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault(); // don't reload the page
        console.log("onSubmit");
        setSomeState(true);
      }}
    >
      {someState ? (
        <button
          type="button"
          onClick={(e) => {
            e.preventDefault();
            setSomeState(false);
          }}
        >
          button
        </button>
      ) : (
        <button type="submit">submit</button>
      )}
    </form>
  );
} 
I thinks  the following changes fix the problem .

**Comment by vxsl** [comment]
> I have encountered a similar issue. https://github.com/facebook/react/issues/25887
As per the sample I linked in my issue, the non-submit button in question now is submitting an unrelated form even if it does not have a form owner, just because it is conditionally rendering. I believe this is a bug in React.

@yukiyokotani Thanks for linking your issue. Apparently it is not a bug (https://github.com/facebook/react/issues/25930#issuecomment-1363904975), so I'll close this issue as well.
