### ISSUE TITLE
Bug: Portals doesn't participate in Suspense

### ISSUE THREAD

**Issue by h3rmanj** [facebook/react#25677]
It appears Portals does not participate in suspense. I came over this by accident, and I'm not sure if it's intended behavior or not. I could not find any documentation related to suspense and portals specifically.

React version: 18.2.0

## Steps To Reproduce

1. Create a component that can suspend, while also rendering a portal
2. Suspend component

Link to code example:

https://codesandbox.io/s/youthful-tree-vikl09?file=/src/App.tsx

## The current behavior

Portal content rendered from a suspending component is visible if the component suspends.

## The expected behavior

Portal should behave like any other child and not be shown when it's under a suspense that fallbacks.

**Comment by vkurchatkin** [comment]
It seems to be unfortunate, but expected behaviour. Suspended content is hidden using `display: none`, which means there is no good or simple way to make this affect portals as well.
