### ISSUE TITLE
Bug: React Suspense, lazy

### ISSUE THREAD

**Issue by jaedon6** [facebook/react#25673]
Contact route still on loading state while using React Suspense.

### Link to code
[Repository](https://github.com/jaesmoke/jaesmoke)
[Live website](https://jaysmoke.web.app)

### Expected Behavior:
Loading state stops once component is loaded.

**Comment by eps1lon** [comment]
Could you reduce this to a smaller example? Try to remove as much code as possible until the problem no longer reproduces. Also try to reduce it to as little files as possible.
