### ISSUE TITLE
Bug: react is impossible to use with Stylus

### ISSUE THREAD

**Issue by 89z** [facebook/react#25671]
The current GitHub beta includes a style update, that has added some fixed elements:

> ![1](https://user-images.githubusercontent.com/73562167/201454511-179fdaf9-3474-4fe0-96fe-f70ad6035d68.png)

I don't like this, so I planned to unsticky it using Stylus [1]. So I open the source code and find this fun little snippet:

> ![Untitled](https://user-images.githubusercontent.com/73562167/201454425-20ef48e0-e28e-4a65-9663-b9318a95a60b.png)

because of React, it is utterly impossible to target any element, because nothing uses IDs, and the class names are complete nonsense. I think React should have some configuration to output sane class names, so they can be targeted by various tools. Otherwise people are left with "read only" websites, which I think is a pointless crippling of the web experience.

1. https://github.com/openstyles/stylus

**Comment by markerikson** [comment]
This has literally nothing to do with React.

React itself outputs exactly whatever HTML the UI programmer told it to write.  That could be plain handwritten CSS classes like `<div className="list-item select">`, it could be CSS Modules like `<div className={styles.ListItem}>`, it could be Tailwind like `<div className="flex text-xs text-black border-black">`, or something else.

The same is true for _every other UI technology out there_.  Vue, Angular, Svelte, Lit, whatever, they all just output whatever the programmer told them to.
