### ISSUE TITLE
Bug: New input is not emptied after condition changes

### ISSUE THREAD

**Issue by nubpro** [facebook/react#25714]
React version: 18.1.0

## Steps To Reproduce

1. https://codesandbox.io/s/great-franklin-0c08dm?file=/src/App.js
2. Enter any value in the textbox and press "Next"
3. On the second page, you will see that the value entered is retained even though it's a new totally different textbox (they have different ids and different props.

Link to code example: https://codesandbox.io/s/great-franklin-0c08dm?file=/src/App.js

## The current behavior
The second input retains the value from the first input.

## The expected behavior
The second input's value should be reset and display the placeholder text.

**Comment by frontend-winter** [comment]
### I found the same thing

**Comment by frontend-winter** [comment]
**This is still true when I try to use the defaultValue property, why isn't it officially marked as a bug**

**Comment by vkurchatkin** [comment]
This is not a bug. As far as React can tell, this is the same `input`

>  it's a new totally different textbox (they have different ids and different props.

This doesn't matter for React. If you want to indicate that two elements are distinct, you need to add `key` property for them

**Comment by nubpro** [comment]
> This is not a bug. As far as React can tell, this is the same `input`
> 
> > it's a new totally different textbox (they have different ids and different props.
> 
> This doesn't matter for React. If you want to indicate that two elements are distinct, you need to add `key` property for them

I understand this is how React currently sees it, perhaps there could be an enhancement made or a warning to indicate the possible problems like how React warns when you try to make changes to uncontrolled input?

On top of your suggested method, I've found that I could avoid this problem by making both inputs controlled (but this is far from ideal as it causes re-render on every key stroke). That aside, one of the Discord member Spork suggested to split the second screen into a different component, that too works.
