### ISSUE TITLE
Bug: Hydration not update the attributes of dom?

### ISSUE THREAD

**Issue by aweiu** [facebook/react#25717]
React version: 18.3.0

## Steps To Reproduce

See [LiveDemo](https://codesandbox.io/s/dreamy-tdd-lf023y?file=/App.js)

Link to code example:

[LiveDemo](https://codesandbox.io/s/dreamy-tdd-lf023y?file=/App.js)

## The current behavior
The `href` of  `a` and the `style` of `div`are not updated.

Even when I click:

![image](https://user-images.githubusercontent.com/15623620/203101132-b0e45832-a890-4ae2-bf39-2dc6971150db.png)

I can see the href of state is `/456` in console:

![image](https://user-images.githubusercontent.com/15623620/203101472-bdc66166-3f03-4208-b734-329a6c1890ad.png)

But the href of dom always keeps `/123`: 

![image](https://user-images.githubusercontent.com/15623620/203101875-008a349e-49cb-4de5-ab68-4a8350e6f58e.png)

## The expected behavior
The `href` of  `a` to be `/456` and the `style` of `div` to be `color: red`

---

**It may not be a bug, but I want to know how to solve it?** 

In our business, it is inevitable that some dom node attributes are inconsistent between the server and the client, but we always hope that the page can respond to the results of the client render

Thanks a lot! 🙏🏻

**Comment by eps1lon** [comment]
This is likely caused by the previous hydration mismatch. When mismatches happen, React will not update attributes. 

Does the issue persist if you fix the prior hydration mismatch?

**Comment by aweiu** [comment]
> This is likely caused by the previous hydration mismatch. When mismatches happen, React will not update attributes.
> 
> Does the issue persist if you fix the prior hydration mismatch?

However, mismatches must exist, so we want to know how to let react update node attributes when mismatches exist?

![image](https://user-images.githubusercontent.com/15623620/204251450-8cbc1951-663c-4770-9c72-bc6a33d12e85.png)

**Comment by gaearon** [comment]
React does not update the attributes because checking each attribute would be too expensive. 

> it is inevitable that some dom node attributes are inconsistent between the server and the client

It should not be inevitable — there must be some way you can pass correct information to the client.
