### ISSUE TITLE
Bug: broken link in react-reconciler

### ISSUE THREAD

**Issue by xfq** [facebook/react#25716]
React version: main branch

## Steps To Reproduce

1. Open https://github.com/facebook/react/blob/main/packages/react-reconciler/README.md#practical-examples
2. Click "[host config](https://github.com/facebook/react/blob/main/packages/react-dom/src/client/ReactDOMHostConfig.js)" in "[React DOM](https://github.com/facebook/react/blob/main/packages/react-dom/src/client/ReactDOM.js) and its [host config](https://github.com/facebook/react/blob/main/packages/react-dom/src/client/ReactDOMHostConfig.js)"

## The current behavior

The page is 404.

## The expected behavior

The page should exist.

**Comment by kassens** [comment]
Fixed by #25788
