### ISSUE TITLE
Bug: Failed to pass tests with latest React experimental builds

### ISSUE THREAD

**Issue by manakuro** [facebook/react#25725]
React version: `react@18.3.0-next-e1dd0a2f5-20221115`

## Steps To Reproduce

It does not reproduce the behavior in CodeSandbox, so I set up the test environment. You can see this behavior through this.

Link to code example:
https://github.com/manakuro/test-react-experimental

Steps to reproduce
```
1. yarn
2. yarn test
```

It works well on the `react@18.3.0-next-65e32e58b-20221019` like here.
https://github.com/manakuro/test-react-experimental/tree/18.3.0-next-65e32e58b-20221019

## The current behavior
I'm trying some tests on `react@18.3.0-next-e1dd0a2f5-20221115`,  and I noticed that the test that uses `jest.useFakeTimers` and promise inside custom hooks got stuck in the `flushActQueue` function.

It seems like the `performConcurrentWorkOnRoot` got stuck in there and  I changed the `callback(false)` to `callback(true)`, then it worked.
https://github.com/facebook/react/pull/25523/files#diff-74fadc1ab3f56ca2a5ae8932ba9876711d5d718c5367ba1cf4faf286c236c353R266

https://user-images.githubusercontent.com/11571318/202589570-190fb404-aa86-47fb-9198-04869b72e123.mov

## The expected behavior
Should pass the tests.

**Comment by eps1lon** [comment]
Since you're using Jotai, maybe @dai-shi can help entangle why this is happening.

**Comment by manakuro** [comment]
@eps1lon Hi, thanks for reaching out.

I found the behavior in the process of working on this [Jotai's issue](https://github.com/pmndrs/jotai/issues/1498) and was wondering if it was an unexpected behavior in the `act` function or a problem that I should handle.
