### ISSUE TITLE
replaceState(null) doesn't reset state

### ISSUE THREAD

**Issue by rymohr** [facebook/react#2572]
Since components start with null state, it would make sense that you could reset back to a null state.  Right now the best you can do is reset back to an empty object.

http://jsfiddle.net/wqpzmg7b/1/

It's a minor issue but I think it deserves documenting if not changed.

**Comment by pluma** [comment]
This can probably be closed as 0.14 deprecates this method?

**Comment by spicyj** [comment]
Yeah, we're not planning to change this now.
