### ISSUE TITLE
Add Async Stack Tagging API support

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#25742]
Chrome recently shipped Async Stack Tagging API that can significantly improve the debug stack.

Angular is already using it. See https://developer.chrome.com/blog/devtools-better-angular-debugging/#the-async-stack-tagging-api

![image](https://user-images.githubusercontent.com/5390719/203987734-1a614251-9a9a-4330-98cd-bca9ea524fba.png)

Since React is using time slicing to split the task, it is not convenient to debug why the update is triggered. If React supports Async Stack Tagging API, it will be much easier to find out why an update is triggered.

**Comment by Jack-Works** [comment]
Working on it:

![image](https://user-images.githubusercontent.com/5390719/204093494-fc7b81a6-6440-4297-9a10-18f2429a9535.png)

![image](https://user-images.githubusercontent.com/5390719/204093499-23e67b6e-078c-4c2f-b8ea-56f73271ab7f.png)

**Comment by 0xdevalias** [comment]
@Jack-Works Curious if you ever made further progress on this? It would be super useful.

Further resources:

- https://developer.chrome.com/docs/devtools/console/api/#createtask
  - > `console.createTask(name)`
   > This method is known as the Async Stack Tagging API. If you use a framework or abstraction for scheduling and async execution that already uses this API under the hood, you don't need to call this API directly.
- https://developer.chrome.com/blog/devtools-modern-web-debugging/#linked-stack-traces

**Comment by Jack-Works** [comment]
> @Jack-Works Curious if you ever made further progress on this? It would be super useful.

Sorry No, I'm working on other open-source projects these days. I'm still willing to implement them, but only when the React team says they accept the contribution of this feature otherwise I am afraid this will be rejected for some reasons.

**Comment by 0xdevalias** [comment]
> I'm still willing to implement them, but only when the React team says they accept the contribution of this feature otherwise I am afraid this will be rejected for some reasons.

@Jack-Works _nods_ that's totally understandable.

**Comment by reaktivo** [comment]
Relying on Async Stack Tagging would be absolutely a blessing when debugging React :|
