### ISSUE TITLE
useEffect alternative which has same effect of listing all dependencies

### ISSUE THREAD

**Issue by rgsk** [facebook/react#25745]
```typescript
useEffect(()=>{
    // Some code that uses dep1, dep2, dep3, dep4, dep5
}, [dep1, dep2, dep3, dep4, dep5])
```
```typescript
useReactiveEffect(()=>{
    // Some code that uses dep1, dep2, dep3, dep4, dep5
    // This runs when either of dependencies used in this function changes, we don't need to explicitly list the dependencies
})
```
Basically we want dependency tracking to be automatic, so there's no dependency array like in useEffect.

I keep telling people at my company, please list all the dependencies used in useEffect in dependencies array, and follow es lint exhaustive deps rule, resolve situations where useEffect runs undesirably by

wrapping objects in useMemo, functions in useCallback and useRef if a variable is used inside useEffect without needing to run the effect if it changes

but nobody follows it, and it often leads to bugs in the application which slows down the development speed.

Having useReactiveEffect, and it being promoted to be used most of the times, my headache will be reduced.

**Comment by krulod** [comment]
There is no way of determining which deps were used inside of an effect. Consider using a truly reactive framework like Solid or a reactive state manager like MobX, react-solid-state, $mol_wire, etc.

**Comment by Glinkis** [comment]
@rgsk You can use https://www.npmjs.com/package/hooks.macro for this. I used it a lot at my previous job, and it works great!
