### ISSUE TITLE
Issues with ES6 classes

### ISSUE THREAD

**Issue by ceane** [facebook/react#2575]
I'm having issues with ES6 classes in React. It seems that esprima-harmony differs from how 6to5 is implementing classes, as well as how classes are implemented in beta versions of browsers.

With esprima-harmony I am able to use classes (using `React.createClass(MyClass.prototype)`), however,

**If I use any of these methods:**

**with 6to5**

``` javascript
React.createClass(MyComponent.prototype);
```

**In Chrome 39 and IE11 Windows 10 Preview**

``` javascript
React.createClass(MyComponent);
```

I get this error: `Error: Invariant Violation: createClass(...): Class specification must implement a`render`method.`. And if I try using `React.createFactory` in 6to5 I get this error: `TypeError: undefined is not an object (evaluating 'nextElement.props')`.  

I can't figure out what would be so different between Object.defineProperty and directly defining prototypes, other than the fact that properties set on the prototype aren't automatically enumerable.

**ES6 code**

``` javascript

class MyComponent {
  render() {
    return null;
  }
}
```

**esprima-harmony compiles:**

``` javascript
function MyComponent() {}
MyComponent.prototype.render = function() {return null;}
```

**6to5 compiles:**

``` javascript
var _classProps = function(child, staticProps, instanceProps) {
  if (staticProps) Object.defineProperties(child, staticProps);
  if (instanceProps) Object.defineProperties(child.prototype, instanceProps);
};

var MyComponent = (function() {
  var MyComponent = 
     function MyComponent() {};

  _classProps(MyComponent, null, {
    render: {
      writable: true,

      value: function() { 
        return null;
      }
    }
  });

  return MyComponent;
})();
```

How should I resolve this issue?

**Comment by mvpspl619** [comment]
Should this be re-opened because of the latest announcement given below ?

Unfortunately/fortunately, 6to5 already made necessary changes to make them not enumerable. 

React version being used: 0.12.2.

```
class _Header {

	renderItems () {
		return (
				<ul>
					<li><Link className="btn btn-primary" to="newidea">New</Link></li>
					<li><Link className="btn btn-primary" to="ideas">Ideas</Link></li>
				</ul>
		);
	}

	render () {
		return (
			<div>
				<h1 className="dashboard-header">Idea Store</h1>
				<br />
				{this.renderItems()}
			</div>
		)
	}
};

export default {Header : React.createClass(_Header.prototype)};
```

https://twitter.com/webreflection/status/560929583974088704

**Comment by mvpspl619** [comment]
@sebmarkbage Any thoughts ?

**Comment by ToucheSir** [comment]
@mvpspl619 FWIW you can pass the `class` option to 6to5's (or Babel's now, I guess) [loose mode](http://babeljs.io/docs/usage/loose/) to generate classes with enumerable members.

**Comment by mvpspl619** [comment]
@ToucheSir Thanks.

As that's a temporary way to make React work with ES6, I am curious to find out if anything is being done on this front to make React work with ES6 non-enumerable class methods in the future release ?

**Comment by sebmarkbage** [comment]
The problem with enumerability is that it can't be polyfilled in old IE (we still support IE8). Both the detection and definition. If we want to support IE8 we don't want there to be different React behaviors depending on which browser you use, so we can't depend on detecting enumerability. Otherwise someone may accidentally rely on it working, yet in IE8 it will break (and nobody properly tests IE8 these days).

Luckily, we have first class support for ES6 classes in 0.13.

http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

**Comment by mvpspl619** [comment]
@sebmarkbage Thanks for that. 

I have dependency problems with react-router and react-async for using react@0.13.0-beta-1. Trying to figure out a solution.

**Comment by arnihermann** [comment]
@sebmarkbage http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html states that class methods are no longer enumerable by default. This will break a lot of tests (as jest relies on this property) in one of my projects. Are you aware of any workaround?

**Comment by sebmarkbage** [comment]
There is a flag to turn it back to the old behavior as a workaround until we can get it fixed in jest.

**Comment by zpao** [comment]
In your preprocessor `ReactTools.transform(code, {harmony: true, target: 'es3'})`

**Comment by jakeboone02** [comment]
@zpao Thanks for the `target: 'es3'` tip.  That was driving me crazy.

@sebmarkbage Is there an issue to track in the [jest](https://github.com/facebook/jest/issues) project?

**Comment by jbe456** [comment]
This issue occurs now with Traceur since this bug fix : https://github.com/google/traceur-compiler/issues/1873
