### ISSUE TITLE
tests using React 0.12 and Jest-mocked sub-components result in different behavior when using jsx versus React.createFactory()

### ISSUE THREAD

**Issue by awei01** [facebook/react#2576]
I've created a repo to help illustrate what I'm running into: https://github.com/awei01/react-jest-testing-illustration

Basically, developing in pure jsx and using the React.createFactory() are not interchangeable under testing using jest. This makes writing unit tests a little trickier. 

According to this link: https://gist.github.com/sebmarkbage/d7bce729f38730399d28, non-jsx components must be wrapped in a React.createFactory(). But, when testing these components using Jest, I've found that these are not interchangeable within tests that mock sub-modules.

I'm guessing that the differences stem from using .bind() within React.createFactory:
```
function createFactory(type){
  return React.createElement.bind(null, type);
}
```

**Comment by gaearon** [comment]
Closing as very outdated.
