### ISSUE TITLE
[DevTools Bug] Element "9" not found | Also "Element "10" not found" / "Element "12" not found"...

### ISSUE THREAD

**Issue by arbocobra** [facebook/react#25769]
### Website or app

https://github.com/arbocobra/redux-minesweeper

### Repro steps

On first load I get multiple Error warnings on all app components from `<Game/>` down. They are identified with different Element numbers but appear to be directed to the same issue 
"The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39558:15" 

If you select 'Begin Game' in app the error in component` <Game />` can be dismissed but new Errors appear on all newly rendered components below (once again all have different Element numbers directed to the same location (../main.js:39558:15)

//

This is issue is probably related to [[DevTools Bug] Element "41" not found](https://github.com/facebook/react/issues/25755)

Chrome is up to date (Version 108.0.5359.71 (Official Build) (x86_64)), and restarted. 
I also tried reinstalling React extension (running 4.27.0).

The app is using Redux, which one commenter in other thread mentioned might be a commonality. 

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.27.0-bd2ad89a4

### Error message (automated)

Element "9" not found

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39558:15
```

### Error component stack (automated)

```text
at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40933:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39237:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39771:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42429:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35080:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37705:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44505:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39237:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39409:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39439:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39409:3)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44686:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44115:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31940:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32584:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39834:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56039:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Element  not found in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by nokoro13** [comment]
I am experiencing the same bug right now

**Comment by anwern27** [comment]
I am experiencing the same bug now

**Comment by nokoro13** [comment]
Is anyone else using framer-motion and having this bug?

**Comment by KLIJIN** [comment]
some problem

**Comment by fullsnack-coder** [comment]
same problem

**Comment by SthAneal** [comment]
same problem

**Comment by NickoA96** [comment]
same problem

**Comment by Gaurav-jo1** [comment]
same problem

**Comment by 2256184693** [comment]
same problem

**Comment by abhagsain** [comment]
### react core members reading the ***Same Problem*** comments

![react-contributors-reading-issue](https://user-images.githubusercontent.com/36589645/205251149-8ca3e199-4aa2-4a61-a779-7f60494ae381.gif)

**Comment by babak2000ir** [comment]
me too, actually devTools sent me here. so they're on it 👍

**Comment by BlakeMack** [comment]
same problem

**Comment by cojoclaudiu** [comment]
same here
<img width="871" alt="Screenshot 2022-12-02 at 11 42 00" src="https://user-images.githubusercontent.com/62800983/205285201-eee1c226-5b0b-4094-acb0-917b20e2f058.png">

**Comment by Joker0824** [comment]
![image](https://user-images.githubusercontent.com/26892349/205286078-8546c6c5-15bd-4e7c-90f1-024a46641c7a.png)

**Comment by s1118497** [comment]
same🥲

**Comment by Gaurav-jo1** [comment]
It's just showing white screen 😥

**Comment by janjanarnaldo** [comment]
same problem

**Comment by CeloHill** [comment]
same :(

**Comment by hamzatab** [comment]
same x)

**Comment by luisaugs** [comment]
Same here... 
In my case happens when use useEffect on props.

**Comment by jeroanan** [comment]
Same here

**Comment by GailBowen** [comment]
Same here

**Comment by bigfarofa** [comment]
It's happening to me too ;_;

**Comment by rom-orlovich** [comment]
Same here. The bug happens when I try to create a list of inputs that do not respond to dom events like onClick and onChange.

**Comment by Alisoneoz** [comment]
The same is happening here! help!

**Comment by kabirolawore** [comment]
The same too!

**Comment by ashrafqasem** [comment]
Same here

**Comment by ubuntucow** [comment]
Same here

**Comment by ArnaudVerpouckeDeveloper** [comment]
Same problem here too...
![react_dev_tools_bug](https://user-images.githubusercontent.com/37350631/205387761-cdcde717-4623-4573-a57f-fbb2ca642e62.jpg)

**Comment by Marlys-Aguila** [comment]
Same

**Comment by muhammetemrevatan** [comment]
same problem

**Comment by chimalexoficial** [comment]
same problem :(

**Comment by Gaurav-jo1** [comment]
Can you provide an estimate of how long it will take to resolve this issue?

**Comment by Asad-konok** [comment]
I am facing same issues. How can i solve it?
![Screenshot_1](https://user-images.githubusercontent.com/119725526/205430019-b586b480-222b-411d-b308-19b503a074a7.png)

**Comment by Gaurav-jo1** [comment]
![Screenshot 2022-12-03 145937](https://user-images.githubusercontent.com/93304640/205434132-9f6db176-d4eb-479a-b991-ab2cf182bc3d.png)

**Comment by anayo-hub** [comment]
react team need to drop a message

**Comment by anayo-hub** [comment]
there is no solution yet, but i would help a "we're on it" message would be appreciated, i have deleted all my extensions but still have the same issue

**Comment by karimiarman** [comment]
Uncaught Error: Element "2" not found

**Comment by mohamed-ali-agourram** [comment]
@reactjs-bot Uncaught Error: Element "48" not found on react tools

**Comment by Gaurav-jo1** [comment]
😫

**Comment by rwmarmol** [comment]
Same!

**Comment by FernandoTelloL** [comment]
Mismo problema

**Comment by hestamp** [comment]
In my case React doesnt store any of data from controlled inputs using useState. 

StrictMode dont show any of errors

**Comment by komailf67** [comment]
Same!

**Comment by aungzanbaw** [comment]
<img width="654" alt="FireFox RDT" src="https://user-images.githubusercontent.com/1712561/205462187-341e3122-faa0-456b-8f06-cea7a8ec0459.png">

It happened on both Chrome & FF(No add-ons or extensions).

**Comment by guidani** [comment]
Same problem.

**Comment by hestamp** [comment]
Error is now gone...

I just add all of dependencies to my all my useEffects and now it works

**Comment by anayo-hub** [comment]
@hestamp , please can you explain this a little bit further, i have been hooked on this since morning

**Comment by hestamp** [comment]
> 

https://blog.bitsrc.io/understanding-dependencies-in-useeffect-7afd4df37c96

Hope it helps you

**Comment by Alisoneoz** [comment]
I wish I could solve my problem too 😭😭

**Comment by anayo-hub** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/70281852/205466855-55be73ea-c981-4557-a02b-314431a86c16.png)

**Comment by anayo-hub** [comment]
same things just reading and looking for every possible solution right now

**Comment by dimashpt** [comment]
Same here

**Comment by Alisoneoz** [comment]
I was checking if I made a mistake somewhere or if it really was something with React, so I began testing other apps that I've built, and the same is happening... mostly in forms and functionalities related to handling state

**Comment by laontme** [comment]
I got this error while going through [React Router tutorial](https://reactrouter.com/en/main/start/tutorial). Because it's a study project, it was easy to just **replace Vite with create-react-app** and I think that fixed the issue

**Comment by hestamp** [comment]
@laontme well that advice fixed part of the issue and now data stored in **useState**.

I also used **Vite** in my app, but after changing it to create-react-app i still have that problem. Also components in **React Developer Tools** is still named wrong.

**Comment by laontme** [comment]
@hestamp 
> I also used **Vite** in my app, but after changing it to create-react-app i still have that problem. Also components in **React Developer Tools** is still named wrong.

Yeah. I am notised that too. I have a study project and real project. In real project I also use React Router so environment almost identical and I have no error. So i think issue is not related to Vite

*I am not **senior React developer** I am just studying so I just share with you what I see*

**Comment by rizqillah-pnl** [comment]
thank bro

**Comment by sricharan505** [comment]
I Faced Issue when I created additional local states along with redux store. After removing those states and moving them to redux store, the issue was resolved. Not sure what the issue was but this worked.

**Comment by anayo-hub** [comment]
finally mine is now working but it keep showing the errors but it's now temporary

**Comment by Gaurav-jo1** [comment]
Mine is just showing white blank screen 😥

**Comment by tamir792001** [comment]
Same.....

**Comment by agusstingalvan** [comment]
I have same problem!

**Comment by Kartohan** [comment]
I think i have same problem 
![Screenshot_4](https://user-images.githubusercontent.com/99285514/205598251-d67a0b52-0abb-4c1f-a833-80c0507c576f.png)

**Comment by k90mirzaei** [comment]
Same problem here.
I tested it in Linux (ubuntu22.04) and Chrome Version 108.0.5359.94 (Official Build) (64-bit)
I also remove all my extensions and then just reinstall react-dev tool  to confirm this is not a side effect issue

**Comment by Complexicon** [comment]
Same Problem Across all my Machines (arm64 MacOS Ventura, Windows 10, Arch Linux all with latest Chrome 108.0.5359.94)
Seems to be somewhat related to the useEffect Hook? on Components without the hook i can inspect props.

has useEffect:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/22222976/205616522-1320d350-ad88-4307-85f1-838f1cd49418.png">

does not have useEffect
<img width="479" alt="image" src="https://user-images.githubusercontent.com/22222976/205617012-8f722df2-7183-46e6-be32-3c93827bbeee.png">

**Comment by authir** [comment]
I can confirm that this is related to the useEffect Hook. On components without the hook it is working fine.
Occuring on all my machines (Win10, Ubuntu 20.04.5 LTS, Debian 11) on  Chrome 108.0.5359.71, Firefox 107 and Edge.

**Comment by Gaurav-jo1** [comment]
@authir Not working even after removing useEffect hook

**Comment by Gaurav-jo1** [comment]
## Found something new

![Screenshot 2022-12-05 172140](https://user-images.githubusercontent.com/93304640/205630797-e6e1d5a6-4cb9-40a2-9cb8-9d314bc578ad.png)

**Comment by sfuentes-dev** [comment]
Same problem over here.

**Comment by EndyPlus** [comment]
Same problem, i did'nt find any solution of this. Pls help

**Comment by jlong4223** [comment]
I have the issue happening to me as well. My component does not have a useEffect. I have `useState` & react-redux hooks (`useDispatch, useSelector`).

**Comment by ddbdzung** [comment]
This happened to me even when I used create-react-app, so I think Vite is not the problem.
![image](https://user-images.githubusercontent.com/90110891/205735989-7d2c0378-2628-44dd-8c14-3e51cec32eeb.png)

**Comment by Juanpav78** [comment]
same problem... but for some reason it is when I use the Link of  Remix, but if I use the page routes without reloading it loads everything

**Comment by ignacioocode** [comment]
I have the same problem since today, yesterday I was with a project and everything worked fine, and today I started another project with vite and I started having this problem, I tried opening the project from yesterday to see if it worked for me and the error also continued, so The problem must be the extension or some other that I can't find, because yesterday everything was working correctly

**Comment by Alisoneoz** [comment]
Shouldn't someone from the React team say something?😓

**Comment by WalterKstro** [comment]
I have the same problem today, in the dev tools
![Screenshot from 2022-12-05 21-37-32](https://user-images.githubusercontent.com/25376434/205807044-c28a9aa7-5e91-41bb-90c0-ea4d1c654733.png)

**Comment by RyouHikaru** [comment]
Experiencing the same problem.

![image](https://user-images.githubusercontent.com/57375688/205807330-afa88880-d0b8-4581-833a-f79001aaf680.png)

**Comment by Gaurav-jo1** [comment]
@Alisoneoz Exactly

**Comment by mihir1729** [comment]
Experiencing same problem with the error - Uncaught Error: Element "3" not found

**Comment by krzysztofkucharzyk** [comment]
I have the same problem and it seems like occure with every Link I have in my app 
![obraz](https://user-images.githubusercontent.com/17053500/205877169-c4496f3d-3fbd-449a-8bb3-f50c9d91663f.png)

**Comment by Arnaud-De-Baerdemaeker** [comment]
From what I see (I have the errors aswell, it appears to be thrown by the strict mode of React.

**Comment by Gaurav-jo1** [comment]
@Arnaud-De-Baerdemaeker no strict mode in my project

**Comment by babak2000ir** [comment]
It's even happening on "npx create-react-app my-app", even if there is no strict mode. It's not really Links, Router, useEffect or any external tool. It's a general show stopping bug everywhere and the status is not even confirmed. :/

**Comment by BlakeMack** [comment]
does anyone have any update as to if the react dev team are working on this react dev tools bug?

**Comment by Gaurav-jo1** [comment]
@BlakeMack No clue 🙂

**Comment by Akatroj** [comment]
hello sirs, I have the same problem 🫤

**Comment by jakubdybczak** [comment]
hello sirs, I have the same problem 🫤

**Comment by watislaf** [comment]
hello sirs, I have the same problem 🫤

**Comment by pdramirez-dev** [comment]
Hello  I have the same issues

**Comment by mondaychen** [comment]
I'm looking into this

**Comment by Gaurav-jo1** [comment]
@mondaychen 🫂

**Comment by babak2000ir** [comment]
@mondaychen ♥️

**Comment by bebop76** [comment]
Hi all,
same issue for me

![Cattura](https://user-images.githubusercontent.com/47028739/206012668-da2f4669-9ec8-4ba7-aa31-03249ce9de1a.JPG)

**Comment by chinanderm** [comment]
I think it's pretty clear there is an issue, so we don't need endless "me too" posts.

**Comment by mondaychen** [comment]
Sorry for the inconvenience!
We have submitted a patch (version 4.27.1) to the browser extension stores. It's still under review with Chrome and Edge, but is already published for Firefox https://addons.mozilla.org/en-US/firefox/addon/react-devtools/
Can people (who have Firefox) give it a test to see if the issue is gone for y'all?

**Comment by KR-Soe** [comment]
It's still not published in Chrome 😢

**Comment by noszczykmichal** [comment]
Hi, I've checked the latest versions available on Firefox and Chrome, and they both work now. Thanks guys.

**Comment by villepaananen** [comment]
Updated the Chrome extension and now works, thank you!
