### ISSUE TITLE
propTypes property (current) vs. getPropTypes function (proposed)

### ISSUE THREAD

**Issue by jordansexton** [facebook/react#2577]
As `propTypes` are only used in development mode, it seems like it would be preferable to only evaluate them as the result of a method call returning the object instead of the current object literal declared on the class. I imagine this isn't a particularly expensive operation, but if you're using shapes, this results in a lot of type declaration evaluations that are never used outside of development.

Current
```javascript
React.createClass({
    propTypes: {
        prop: React.PropTypes.shape({...}),
        ...
    },
    ...
});      
```

Proposed
```javascript
React.createClass({
    getPropTypes: function () {
        return {
            prop: React.PropTypes.shape({...}),
            ...
        };
    },
    ...
});      
```

Is there a reason it's this way instead of the same functional convention as `getDefaultProps`, `getInitialState`, etc.?

**Comment by spicyj** [comment]
Yeah, we're moving to static properties for these so I'm going to close this out.
