### ISSUE TITLE
Bug: Detached node memory leak when using key and focus contenteditable element

### ISSUE THREAD

**Issue by TUTOR03** [facebook/react#25772]
The DOM node stays in memory as a detached node if it has a content editable element inside what is focused using ref and that component is used with key prop in parent. 

React version: 18.2.0, 17.0.2

## Steps To Reproduce
All steps to reproduce are written in `README` file for this [repo](https://github.com/TUTOR03/reactKeyFocusMemoryLeak).
Also there is a source code to reproduce the bug.

## The current behavior
The DOM node stays in memory as a detached node and can not be collected with garbage collector.

## The expected behavior
The DOM node doesn't stay in memory as a detached node.

**Comment by VMBindraban** [comment]
![Screenshot 2024-04-19 at 10 25 52 AM](https://github.com/facebook/react/assets/2269400/6dce8cfd-cd8e-41bc-bb08-bfda904e4f18)

I runned the performance profiler for a minute and while the JSHeap is being cleaned up the nodes keeps on rising.
The app repaints between the 1 and 3 seconds.

**Comment by SamSeabourn** [comment]
bump

**Comment by Et-008** [comment]
Same here, Detached nodes keeps on increasing. Using GC button is also not clearing the detached nodes.
This is causing the application run slower and sluggish.

**Comment by rakshitbharat** [comment]
bump
