### ISSUE TITLE
useEffect blocking render

### ISSUE THREAD

**Issue by Alarid** [facebook/react#25849]
In a paper I'm writing, I was trying to demonstrate the difference between `useEffect` and `useLayoutEffect` by showing the "flash" of DOM content that may occur between rendering and effects phases, when a visible change to the DOM is made by a `useEffect` instead of a `useLayoutEffect`. 

Doing so, I stumble upon something strange _(to me)_. Since React 18, effects seem to be blocking render when taking a long time, while in React 17 render was done (and screen painted) *before* the effect was triggered. 

For example, if you have this in a component :
```js
function MyComponent() {
  React.useEffect(() => {
    sleep(1000)
    console.log('effect done!')
  })

  return ...
}

// Sleep is a small util like this:
function sleep(time = 0) {
  const wakeUpTime = Date.now() + time;
  while (Date.now() < wakeUpTime) {}
}
```
In React 17, it would render and paint on the screen the component, and **only then** it would run asynchronously this long `useEffect`. In React 18, it's actually blocking the render. Why ? Aren't effects supposed to be triggered asynchronously after render ?

I'm not sure anymore why I should use `useLayoutEffect` if the screen doesn't get painted before `useEffect` runs :thinking:

I suspect concurrent rendering to be the root cause of this, but on the other hand it seems weird to me because I'm not opt-in to any concurrent features. I'd love to understand what's going on here.

React version: 18.0.2

_Side note : I recognise that this might seem to be more of a question than an actual issue. I have looked for answers elsewhere before posting this, and I couldn't find an answer to why `useEffect` behaves like this. I do apologise in advance if I'm just missing a piece of knowledge here._

## Steps To Reproduce

I made two sandboxes to show the difference with the `useEffect` :
- With React 17, working as expected => https://codesandbox.io/s/useeffect-with-react-17-l8p0vd?file=/src/App.tsx:0-1249
- With React 18, blocking render,  behaving like a `useLayoutEffect` => https://codesandbox.io/s/useeffect-with-react-18-o2qhtb?file=/src/App.tsx:87-192

## The current behavior

`useEffect` **appears** to be behaving like `useLayoutEffect`, running _after_ React's DOM changes and _before_ the screen gets painted 

## The expected behavior

`useEffect` should be triggered after rendering and painting phases are done

**Comment by boulhend** [comment]
In React 18 useEffect function fire synchronously before layout and paint when it’s the result of a discrete user input : like user click on a button ,thats why your effect is running before paint, but for other events useEffect function will be deferred (after paint). In the other hand useLayoutEffect is always synchronous.

https://reactjs.org/docs/hooks-reference.html#useeffect

**Comment by Alarid** [comment]
> In React 18 useEffect function fire synchronously before layout and paint when it’s the result of a discrete user input : like clicking on a button ,thats why your effect is running before paint, but for other events useEffect function will be deferred (after paint). In the other hand useLayoutEffect is always synchronous.
> 
> https://reactjs.org/docs/hooks-reference.html#useeffect

Yes I recently figured that out too, thanks! However I tried another approach using `setInterval` to add new messages every 5 seconds, and I got the same result. I can easily understand that a click on a button is a __discrete user input__, but a setState fired by a `setInterval` ? Sounds weird to me. 

But yeah anyway that's the answer I was looking for, so I'll close this issue.
