### ISSUE TITLE
Handle browser autofill gracefully when server-side rendering

### ISSUE THREAD

**Issue by iest** [facebook/react#2585]
I'm rendering my React app at the document root, with server-side rendering.
I've got an email and password login form. It renders on the server without any state (both fields empty).
When the browser loads the page, the email and password are autofilled by the browser.

This happens before React bootstraps, and when it loads, it wipes out that state. So the user sees the inputs being autofilled then being emptied. Not ideal.

I tried using `componentWillMount` to grab the raw DOM node value and `setState` before render, but react complains that the checksum is invalid.

I realise this is a case where the DOM is being modified before react bootstraps on the client, but it would be good to be able to do this kinda stuff...

**Update:** A workaround I used was to pull the values out of the `<input>`s inside `componentWillMount`, then `setState` to those values inside `componentDidMount`. Would still be nice to handle this cleanly though...

**Comment by dantman** [comment]
I have a feeling the "proper" way to fix this would be to have a prop like `autofillValue` on ReactDOMInput. Then , if true, on the first render of a client the component can grab that new value and run the onChange handler to incorporate it.

React does know when it's reusing markup that came from the server. So this should be possible.

However willMount+didMount does feel a bit hacky and the bits of information React exposes on when it's doing its first render from server generated markup is quite a low-level implementation detail.

For that reason it may be worthwhile to introduce a new lifecycle event like `componentWillReuseNode` that accepts the old input as an argument.

Then anything like values injected by a browser can be optionally slurped up by nodes like ReactDOMInput and incorporated into the React flow.

**Comment by mosch** [comment]
@keyanzhang @zpao 

i got the same problem here. and it looks like it's up to a timing problem. if i delay the rendering of react on browser-side by 200ms, the password field will be cleared. 

I traced the problem down to https://github.com/facebook/react/blob/751b76e3518883c31b6105736c2b13839863fdef/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js#L236 this. The node.value of the password field is an empty string, even if the browser auto-filled it. And the `node.value = node.value` clears it.

I created this repository to reproduce it, since it's writing a tests will not be possible.

Tested on Chrome 56:

https://github.com/mosch/react-password-autofill-bug

**Comment by chrisblossom** [comment]
@mosch were you ever able to find a solution?

**Comment by mosch** [comment]
@chrisblossom not really (except hotfixing this line, by not doing it).

**Comment by chrisblossom** [comment]
I created an input wrapper to solve this race condition. If anyone has any suggestions on how to fix any of the [known issues](https://github.com/chrisblossom/react-safe-universal-inputs#known-issues) please open a ticket/PR. https://github.com/chrisblossom/react-safe-universal-inputs

**Comment by aweary** [comment]
Merging this with https://github.com/facebook/react/issues/2585

**Comment by chrisblossom** [comment]
@aweary Did you mean to link a different issue? This is #2585

**Comment by aweary** [comment]
@chrisblossom fixed, thanks
