### ISSUE TITLE
React Dev Tools not saving settings

### ISSUE THREAD

**Issue by hseniht** [facebook/react#25868]
My desired settings on react dev tools is not saved. It resets back whenever I refresh the page or re-open chrome dev tools.

I had even tried reinstalling the React extension (4.27.1 (12/6/2022)

My Chrome is up to date (Version 108.0.5359.99)

**Comment by bnzone** [comment]
Hm, it's working for me. Maybe an issue with Chrome? Tried re-installing Chrome/extension?

**Comment by mahmodlte** [comment]
Hey @hseniht if you meant to change the settings of the extension it will be saved, but If you mean changes in the components like state and code then all of this will reset to the default code that you have written in the text editor so changing code or state in the dev tools meant for debugging and it's not a permanent change

**Comment by hseniht** [comment]
@mahmodlte I don't meant the states. I meant the settings in the react dev tools itself like themes, component tree settings. etc .. are not saved. So lets say I choose dark theme, it applies.. but whenever i reload the page or re-open dev tools. Its back to light theme. Same goes for other configs like component filters and debugging settings. Everything resets back.

**Comment by Shoaib20-1998** [comment]
@hseniht I m facing the same issue in profiler whenever I m refreshing the page checked checkbox automatically gets unchecked

**Comment by namti** [comment]
Uninstall and install again worked
