### ISSUE TITLE
Bug: Not StrictMode, mount Component  useMemo Or useState executes twice 

### ISSUE THREAD

**Issue by Veath** [facebook/react#25873]
React version: 18.2.0

## Steps To Reproduce

1. reload page
2. see the console

It is not executed twice every time, I think it has something to do with the concurrent mode. If the console does not reproduce the problem, please refresh the page and try a few more times

Or use useState(callback), callback will also be executed twice

> 

Link to code example: https://codesandbox.io/s/react-usememo-call2-noq2pj?file=/src/Foo.js

## The current behavior
useMemo callback executes twice 
1. call use memo callback 0
2. call use memo callback 1
![image](https://user-images.githubusercontent.com/15187953/206949236-5b681f4e-aca0-40d3-979f-4c759d3f3d27.png)

## The expected behavior
useMemo callback executes one

## Remark
Also please explain what is causing it because I'm very very curious

**Comment by AlixWang** [comment]
it seems case you use Suspense, when the lazy component unfinish fetching, then child component renders once, after fetched render other time.

**Comment by eps1lon** [comment]
This is the kind of behavior StrictMode is reliably reproducing to highlight the production issue. 

Generally, `render`, `useMemo` etc. can be executed multiple times before a commit is ultimately applied to the screen.
