### ISSUE TITLE
[DevTools Bug]: Too Much Recursion - Firefox & Appsync

### ISSUE THREAD

**Issue by ReidCampbell** [facebook/react#25879]
### Website or app

https://eu-west-1.console.aws.amazon.com/appsync/

### Repro steps

1. Use Firefox with React Dev Tools added
2. Log into AWS, go to Appsync console and select an API
3. The app will then freeze and you should get a `too much recursion` error in the console

This only seems to happen in Firefox. Not confident on whether this is a DevTools, Firefox or Appsync issue but it only seems to happen when DevTools is enabled.
![Screenshot 2022-12-13 at 11 29 14](https://user-images.githubusercontent.com/44685146/207308231-68dcbe56-8221-4d46-b644-c3a8f62595b3.png)

### How often does this bug happen?

Every time

**Comment by amirrezaDev1378** [comment]
Do you have any updates on this? I'm facing the same issue on Firefox

**Comment by amirrezaDev1378** [comment]
Here is a temporary solution for this issue :

```ts
const bannedErrors = [
    "InternalError: too much recursion",
    "locatorjs",
];

const SetupAppConsole = () => {
    if (typeof window !== "undefined" || process.env.NODE_ENV === "production") {
        if (typeof window["oldError"] !== "function") window["oldError"] = console.error;
        console.error = (...args: any) => {
            const errors = (args?.length > 0) ? args.join(" ") : args;
            const hasBannedError = bannedErrors.some((bannedError) => errors.includes(bannedError));
            if (hasBannedError) return;
            window["oldError"](...args);
        };
    }
};
export default SetupAppConsole;
```

Run `SetupAppConsole `in your application root.
