### ISSUE TITLE
Bug: useEffect after discrete event should block paint, but doesn't 

### ISSUE THREAD

**Issue by gaearon** [facebook/react#25885]
Sandbox: https://codesandbox.io/s/great-nova-djtc1e?file=/App.js

Expected to see no red square because `useEffect` from click (discrete) event should behave like `useLayoutEffect`.

Actual: see the red square which means there's a paint in between.

With `useLayoutEffect`, no such problem: https://codesandbox.io/s/headless-mountain-t2l2bh?file=/App.js. I don't see the red box.

**Comment by gaearon** [comment]
Actually no. This is by design: `useEffect` itself flushes synchronously but state updates from it do not (even if it's caused by a discrete update). Whereas `useLayoutEffect` forces state updates to flush sync too.

**Comment by dinkinflickaa** [comment]
Hey @gaearon, I noticed behavior is different between concurrent and legacy modes when passing state setters to ref. 

In concurrent mode, `useEffect` flushes synchronously but state updates don't.  https://codesandbox.io/p/sandbox/state-updates-on-legacy-mode-forked-2r5m79?file=%2Findex.js%3A8%2C53

In legacy mode, `useEffect` flushes synchronously as well as state. https://codesandbox.io/p/sandbox/state-updates-on-legacy-mode-m65m9x?file=%2Findex.js%3A10%2C1
