### ISSUE TITLE
As `onKeyPress` is deprecated, what is its replacement ?

### ISSUE THREAD

**Issue by ProPhycient5** [facebook/react#25888]
I have attached the screenshot, where `VSCode` editor is hinting that `onKeyPress` is deprecated.

Using `onKeyDown` is not helping in a scenario. 

Ex: Suppose there is an input for a card number, here, I want to restrict the user to enter any other key except numerical, so I add some conditions like in the below code. Everything seems to be fine if I use `onKeyPress`, but if I use `onKeyDown` in its place, it creates another like, it won't allow the user to edit the entered value by pressing `backspace` button (which is not the case when I use `onKeyPress`). In order this issue, which attribute should I be using?

```
              <label className="cardetails-label">Card Number:</label>
              <input
                type="text"
                className="cardetails-input"
                data-mask="0000 0000 0000 0000"
                placeholder="XXXX-XXXX-XXXX-XXXX"
                value={cc_format(card.cardno)}
                onChange={onChange}
                onKeyPress={(event) => {
                  if (!/[0-9]/.test(event.key)) {
                    event.preventDefault();
                  }
                }}
              />
```

React version: 18

I have attached the link to codeSandbox for the frontend of payment method. You check by replacing `onKeyPress` with `onKeyDown` or `onKeyUp`, function won't work as required.
https://codesandbox.io/s/success-dialoge-forked-sawan-qn3mgr?file=/src/component/CardDetails/CardDetails.js

**Comment by Circkoooooo** [comment]
You need to use `onKeyUp`  to listen event of pressing `backspace`.

**Comment by Circkoooooo** [comment]
Here is a simple workaround.
```
const handleKeyup = (e) => {
    var cartype_new = cardnumber(e.target.value);
    setCard({
        ...card,
        cardno: card.cardno.slice(0, card.cardno.length - 1),
        cardtype: cartype_new
    });
};
// bind a keyup event listener in the input element
onKeyUp={(event) => {
    if (event.key === "Backspace") {
        handleKeyup(event);
    }
}}
```

**Comment by ProPhycient5** [comment]
Yeah I have use extra attribute and then it is working fine. Like in below code.

```
  const validKeyForPayment = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "9",
    "Backspace",
  ];
  
            <input
              className="w-full px-1.5 h-6 border-none bg-black text-sm"
              type="text"
              placeholder="XXXX-XXXX-XXXX-XXXX"
              value={cardData?.cardNo}
              onChange={(e) => {
                setCardData((prevData) => ({
                  ...prevData,
                  cardNo: cardNumberFormat(e.target.value),
                }));
              }}
              onKeyDown={(e) => {
                if (!validKeyForPayment.includes(e.key)) {
                  e.preventDefault();
                }
              }}
            />
```

**Comment by red-shadow18** [comment]
I have a  suggestion to do this with just the onChange function:

rest everything in the onChange remains the same, just add this in the beginning:

let value = e.target.value;
    value = value.replaceAll("-", "");
    console.log(value, "vv");
    if (isNaN(value)) {
      return;
    }

tested it in the sandbox, looks fine to me.

[https://codesandbox.io/p/sandbox/success-dialoge-forked-sawan-forked-nyl7h5?file=%2Fsrc%2Fcomponent%2FCardDetails%2FCardDetails.js%3A13%2C39]

**Comment by aayushkhosla** [comment]
is there any thing which can be replace

**Comment by azerengazzou** [comment]
> is there any thing which can be replace

I'm facing this issue now :) maybe you already find a solution but you can use the onKeyDown 
if you want an example just let me know
