### ISSUE TITLE
Bug: Lazy loading images load immediately in Firefox

### ISSUE THREAD

**Issue by Scratchcat1** [facebook/react#25883]
On Firefox, adding a large number of lazy loading images leads to the images being loaded immediately, rather than when they scroll into view. Chromium behaves correctly, only loading the images in view.

React version: 18.2.0

## Steps To Reproduce

1. Generate a large number of images which reach off the page with `loading="lazy"`
2. Open the devtools network page
3. Refresh the page

Link to code example: [Modified create-react-app](https://github.com/Scratchcat1/react-lazy-firefox-bug)
All changes are in `App.js`.

Codesandbox: https://codesandbox.io/s/zen-rumple-4j9mjz

## The current behavior
All images are loaded immediately.

## The expected behavior
Only a few requests are sent for the images which are needed.

## Extra notes
- The initiator for Firefox is `react-dom...` while on Chromium it is `Other`
- The provided example has a variable `delaySettingSrc` which causes the src of the image to only be set on the second render. This is a workaround for the bug.

**Comment by sunderls** [comment]
Are you able to repro it in codesandbox so that people and take a look instantly after clicking?

**Comment by Scratchcat1** [comment]
> Are you able to repro it in codesandbox so that people and take a look instantly after clicking?

Edited original message to add link to codesandbox

**Comment by zcorpan** [comment]
This might be a bug in Firefox. I haven't dug into the test case and since it includes a workaround and links to `localhost` it makes it harder to reproduce. However, my hunch is that this is either https://bugzilla.mozilla.org/show_bug.cgi?id=1647077 or maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1804875

**Comment by Scratchcat1** [comment]
> This might be a bug in Firefox. I haven't dug into the test case and since it includes a workaround and links to `localhost` it makes it harder to reproduce. However, my hunch is that this is either https://bugzilla.mozilla.org/show_bug.cgi?id=1647077 or maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1804875

Bug 1647077 looks to be the cause. Moving `loading="lazy"` before the `src` attribute results in the expected behaviour.

**Comment by meotimdihia** [comment]
@Scratchcat1 this bug is on Safari too. Not Firefox only.

**Comment by hydrandt** [comment]
> Bug 1647077 looks to be the cause. Moving `loading="lazy"` before the `src` attribute results in the expected behaviour.

Indeed!
