### ISSUE TITLE
[DevTools Bug]: The extension brokes some JavaScripts - React is not used.

### ISSUE THREAD

**Issue by lyrixx** [facebook/react#25897]
### Website or app

https://codesandbox.io/s/condescending-solomon-465djc?file=/index.html

### Repro steps

With the code in the sandbox (but in a real page), when the extension is enabled, the tree is expanded, and cannot be collapsed anymore.

![image](https://user-images.githubusercontent.com/408368/208140548-61ae786b-b712-40eb-a64b-b4f814e6965b.png)

There are no errors in the console of the page, but many in the extension. I don't know if it's correlated. 

Note: This code is provided by Symfony, a popular PHP framework. So many developer faces this issue

Note 2: This issue is quite new

I also created an [issue in Symfony](https://github.com/symfony/symfony/issues/48545).

### How often does this bug happen?

Every time

**Comment by govind15496** [comment]
Hey I am a newcomer in this project and I would like to contribute

**Comment by mondaychen** [comment]
When your script tries to insert styles into head, it assumes it's always the `<head>` element is the first element of the `documentElement`, like this
```
doc.documentElement.firstElementChild || doc.documentElement.children[0]
```

In reality, that's not a safe assumption. Instead, it would be better to use `document.head` to get that element.
Here's my fixed version of your code: https://codesandbox.io/s/lingering-rgb-v5855k?file=/index.html

Hope it helps!

**Comment by nicolas-grekas** [comment]
Thank you for having a look @mondaychen!
