### ISSUE TITLE
Names of components is doesn't shown properly but letters like "V", "k" and else. 

### ISSUE THREAD

**Issue by AntonVitulskyi** [facebook/react#25896]
https://prnt.sc/WXmCZwjapzVF

**Comment by markerikson** [comment]
That's normal for a production build.  Whatever build tool you're using (Webpack, Vite, Next, Remix, whatever) has minified the JS code, and so the components no longer have their original names.

**Comment by AntonVitulskyi** [comment]
Thanks for the answer! Useful info, I figured out what my problem is)
