### ISSUE TITLE
Bug: Error 403 after clicking the one link in docs

### ISSUE THREAD

**Issue by evgeniyworkbel** [facebook/react#25907]
React version: website https://reactjs.org/docs/react-component.html

## Steps To Reproduce

1. open https://reactjs.org/docs/react-component.html
2. click  [this lifecycle diagram](https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/)

## The current behavior
error 403

## The expected behavior
open page clear

**Comment by IsomerX** [comment]
I don't see a problem here, I checked and the page is loading just fine. Can you mention the environment you used so that I can maybe recreate this issue.

**Comment by IsomerX** [comment]
I don't see a problem here, I checked and the page is loading just fine. Can you mention the environment you used so that I can maybe recreate this issue.

**Comment by eps1lon** [comment]
Probably just an intermittent network issue. Works for me now.
