### ISSUE TITLE
[Discussion]: More control over the hydration of components.

### ISSUE THREAD

**Issue by Uttkarsh-Srivastava** [facebook/react#25912]
When a user loads a server-side-rendered page, all the imports are loaded and hydrated before the user can interact with the page. This leads to a bigger initial bundle size. We can use code-splitting to split our app into smaller chunks.

We have been using [loadable-component](https://loadable-components.com/docs/getting-started/) for code splitting in our server-side rendering framework. We are using a library called [react-loadable-visibility](https://github.com/trinachoudhury1mg/react-loadable-visibility/tree/fix-hydration) which is an [intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)-based wrapper around loadable components that only load imports visible in the current viewport.
Sample Code.

``` javascript
import loadable from "react-loadable-visibility"
const Component = loadable(() => import("/src/Components/ComponentName"), {
    ssr: false,
    fallback: <Skeleton/>,
})

```

Our server will render the fallback Skeleton given here and will send it to the client. However, on the client, the “.js” files for the “Component” mentioned in the sample code, will be loaded and it will be hydrated only when it is in the current viewport. [react-loadable-visibility](https://github.com/trinachoudhury1mg/react-loadable-visibility/tree/fix-hydration) takes care of this. Here is a [reproducible example](https://codesandbox.io/p/github/Uttkarsh-Srivastava/loadable-components-ssr/sandbox).

## Next Step

We are planning to add support for React lazy and Suspense in our [react-loadable-visibility](https://github.com/trinachoudhury1mg/react-loadable-visibility/tree/fix-hydration) where we hydrate components visible in the current viewport. We want more granular control over hydration than what is currently offered in the new React 18 SSR Architecture.

We will then add support for React lazy and Suspense in our app (using the library mentioned above), where we will load and hydrate only the components that are present in the current viewport. We want to display the HTML of the components that [renderToPipeableStream](https://reactjs.org/docs/react-dom-server.html#rendertopipeablestream) sends us, but we do not want to hydrate the components that are not in the current viewport.

We would like to know your thoughts on this issue so that we can have an optimized approach. I am facing some issues in understanding how hydrateRoot works behind the scene.

We have done some work on this but we are getting hydration mismatches and facing some issues in identifying which components have been rendered on our server and therefore can be rendered in the viewport instead of the fallback.

For a better understanding, you can check out the [reproducible example](https://codesandbox.io/p/github/Uttkarsh-Srivastava/react-18-ssr-demo/master). For more information about the library, please follow this [link](https://github.com/trinachoudhury1mg/react-loadable-visibility/tree/feat/lazy-suspense-support).

Code overview of the [react-loadable-visibility](https://github.com/trinachoudhury1mg/react-loadable-visibility/tree/feat/lazy-suspense-support):

``` javascript
const Component = loadable(() => import(importPath), {
    fallback: fallbackComponent,
})

```

- react-loadable-visibility takes two arguments: the **path** of the component that we want to import and an object containing **fallback** key and **ssr** key. The **fallback** key accepts the fallback component. **ssr** key if set to true should load the chunks and hydrate the component even if the component is not in view.
- [src/loadable-components.js](https://github.com/trinachoudhury1mg/react-loadable-visibility/blob/feat/lazy-suspense-support/src/loadable-components.js) : This file returns loadable-component if the file runs on the client else it will return our custom wrapper function around loadable-components.
- [src/createLoadableVisibilityComponent.js](https://github.com/trinachoudhury1mg/react-loadable-visibility/blob/feat/lazy-suspense-support/src/createLoadableVisibilityComponent.js): In this file, a custom wrapper around loadable-component is present. The wrapper function will check if the import is present in the current viewport using the intersection observer API provided by the browser. If the imported component is present in the viewport it will return the actual component else it will return the fallback component.
- [src/react-lazy.js](https://github.com/trinachoudhury1mg/react-loadable-visibility/blob/feat/lazy-suspense-support/src/react-lazy.js): It returns Suspense wrapped component if the code runs on the server else it returns our custom wrapper function. (**This file has code that is not ready to use. Currently in the development phase)**.
- [src/createLazyVisibilityComponents.js](https://github.com/trinachoudhury1mg/react-loadable-visibility/blob/feat/lazy-suspense-support/src/createLazyVisibiltyComponents.js): This file returns a wrapper around React lazy. If the imported component is in the current viewport it will return the Suspense wrapped component, else it will return a rendered fallback. (**This file has code that is not ready to use. Currently in the development phase).**
    
    ### What we want to achieve in [src/createLazyVisibilityComponents.js](https://github.com/trinachoudhury1mg/react-loadable-visibility/blob/feat/lazy-suspense-support/src/createLazyVisibiltyComponents.js)
    
    The current expectation is it should return the rendered HTML of the component if it has been rendered on the server and not the fallback. However, we would stop its hydration until the component enters the current viewport.
    
### Points of discussion
-  We would need more control over the hydration of components inside or outside the viewport.
-  We would need a way to identify which component's HTML has been generated on the server and can be hydrated.

Need React core team's help and views on the above-mentioned points to achieve our "Next Step"

**Comment by lmatteis** [comment]
From what I understand with React 18 is that you can just wrap your "outside of view" components in Suspense and React will not prioritize their hydration: https://vercel.com/blog/improving-interaction-to-next-paint-with-react-18-and-suspense

I do see however benefits in having more control over the hydration indeed. Perhaps stopping hydration all together until the user starts scrolling or something along those lines.
