### ISSUE TITLE
deprecated packages in react-scripts

### ISSUE THREAD

**Issue by assaad97** [facebook/react#25910]
while i was upgrading dependencies of my project, i was trying to update react-scripts when i had some npm warning about some deprecated dependencies 
![image](https://user-images.githubusercontent.com/50522164/208456600-d3711cf9-85db-41e4-a9a1-9085b6f888e7.png)
i know its not a bug, but im still submitting this.
react v18.2.0
react-scripts v5.0.1
npm v9.2.0
node v18.12.1

**Comment by eps1lon** [comment]
`react-scripts` is maintained in https://github.com/facebook/create-react-app not this repository.
