### ISSUE TITLE
React devtools stuck at Loading React Element Tree...  

### ISSUE THREAD

**Issue by ananthakrishna-hs** [facebook/react#25939]
##### Have tried re-installing both extension and chrome.

OS: Ubuntu 20.10
Chrome: 107.0.5304.87 (Official Build) (64-bit)
Scenario: Dev tools shows
```
 Loading React Element Tree...

If this seems stuck, please follow the [troubleshooting instructions](https://github.com/facebook/react/tree/main/packages/react-devtools#the-issue-with-chrome-v101-and-earlier-versions).
```
on local development servers.

**Comment by Konigj** [comment]
Same, it is not working since a full month. Works fine in other browsers.
I tried reinstalling the extension several times and it didn't help.
![image](https://user-images.githubusercontent.com/84586440/209949147-84cd7b4a-1312-4664-a8c2-839b1037b70b.png)

**Comment by IqbalAhmadi** [comment]
I am having the same issue. Anyone got a solution to this Loading React issue?

**Comment by mwisnicki** [comment]
Same here but only at work. Works fine on personal computer.

Tested on react website.
In both cases Chrome 108 and extension version 4.27.1

When I inspect the devtools inspector I can see following errors in console:
![image](https://user-images.githubusercontent.com/96032/210915429-a6c056ad-1ddd-49fc-9c70-71c0d93b438c.png)

**Comment by mwisnicki** [comment]
This is probably the same as #25818

**Comment by ara24** [comment]
I had the same problem, but it was solved.
I updated my Chrome browser.

OS: MacOS Big Sur 11.2.3
Chrome: 108.0.5359.124(Official Build) (x86_64)

**Comment by mwisnicki** [comment]
I think computer restart helped with mine. Same chrome version but now works.

**Comment by Konigj** [comment]
To fix this problem, you can update Chrome browser. 
I could not update it from the Settings > About Chrome page, so I just downloaded Chrome again, then installed it and it was fixed.

**Comment by johnhunter** [comment]
Seeing this with Chrome 110.0.5481.100, DevTools version: 4.27.2-1a88fbb67

**Comment by aagarw33** [comment]
I have the same problem as @johnhunter

**Comment by gmanc2** [comment]
On Windows this issue caused a BSOD for me.

**Comment by johnhunter** [comment]
Still happening for me with Version 111.0.5563.146

This is on localhost. The following workaround is less than ideal but gets me out of a bind:

- Close devtools panel
- Go to the extension details
- Toggle the extension off and on again
- open devtools panel again
- reload the page

Seems worse the bigger the React app is. The workaround restores functionality for a while but it ends up failing again after a while.

**Comment by anders-kaffia** [comment]
Same here. Chrome Version 111.0.5563.147. On localhost. Next JS 13 project. @johnhunter s solution worked for me for a bit.

**Comment by hoxyq** [comment]
Closing as duplicate of https://github.com/facebook/react/issues/25818, lets consolidate conversation there.

**Comment by wproman** [comment]
Remove the extension and install it again.

**Comment by johnhunter** [comment]
> Remove the extension and install it again.

This did not resolve the problem. Still happening with fresh install of extension 4.27.8 and Chrome 114.0.5735.133

**Comment by johnhunter** [comment]
@hoxyq can we reopen this issue please. It does not appear to be resolved and the behaviour is different from #25818 - thanks.

**Comment by hoxyq** [comment]
> @hoxyq can we reopen this issue please. It does not appear to be resolved and the behaviour is different from #25818 - thanks.

Thanks for notifying. Opening only this one, lets keep all discussion here.

I need more information about the problem:
1. Any chance you have reproducible example? Or more details on when exactly it gets stuck?
2. When it gets stuck, can you please check if there are some errors in Chrome's DevTools console? Not your application's console, but Chrome's DevTools, here is step by step description on how to do it:
    2.1 Open a page with your application and open Chrome DevTools panel
    2.2 Undock the panel into separate window (if not already)
    2.3 Open React DevTools components tab
    2.4 Open Chrome DevTools panel again (a separate one, you will have 2 after it). This one should attach to Chrome's DevTools process, which we can debug now and check if there are some errors in console.

**Comment by johnhunter** [comment]
> I need more information about the problem

Thanks. I see a lot of `TimeoutError: Timed out while inspecting element nnn` errors once undock the panel. But so far closing and reopening the DevTools seems to reload the react tree ok. I'll see if the I can reproduce the issue over the day and report back.

**Comment by johnhunter** [comment]
When the stuck condition occurs; undocking the panel and opening the console shows the following:
<img width="955" alt="image" src="https://github.com/facebook/react/assets/219160/20fe5c4c-7bd5-4d92-b8f7-a5bb5f444f82">

Closing and reopening the DevTools panel seems to reset the tree. This is different to the initial problem where I had to toggle the extension off and on to reset the tree.

So definitely an improvement but still occurring. Its happening on a large React app that I cannot share and so far has been difficult to create a repro case. Hopefully the console output can help narrow down the issue.

**Comment by hoxyq** [comment]
> When the stuck condition occurs; undocking the panel and opening the console shows the following: <img alt="image" width="955" src="https://user-images.githubusercontent.com/219160/247539507-20fe5c4c-7bd5-4d92-b8f7-a5bb5f444f82.png">
> 
> Closing and reopening the DevTools panel seems to reset the tree. This is different to the initial problem where I had to toggle the extension off and on to reset the tree.
> 
> So definitely an improvement but still occurring. Its happening on a large React app that I cannot share and so far has been difficult to create a repro case. Hopefully the console output can help narrow down the issue.

Thanks, timeout errors probably the product of the stuck condition, but not its reason

In your screenshot, you are capturing the console of your application, you should open a second one for the Chrome's DevTools, where extension might report something, here is the example:
<img width="860" alt="Screenshot 2023-06-21 at 13 14 49" src="https://github.com/facebook/react/assets/28902667/b70233cb-7bd6-473d-94ff-5cababb61439">

Check out the title of this window

**Comment by johnhunter** [comment]
Yep, that was the console in the screenshot. Here is the issue reproduced again.
<img width="1372" alt="image" src="https://github.com/facebook/react/assets/219160/29a62450-1ef4-4309-b104-a8bd03263498">

In this case the error log did not appear until I selected another DevTools panel tab and then reselected the react Components tab (that also triggered the unrelated violation warning). The "stuck" message appeared in the react panel the whole time.

**Comment by trey-wallis** [comment]
I'm getting the same behavior as the OP. I am using the stand alone server with a React plugin in Obsidian.md. Obsidian is built off of electron. It was working before but I recently upgraded my version of Obsidian.

react: 18.2.0
react-dom: 18.2.0
react-devtools: 4.28.0
electron: 24.3.1
chromium: 112.0.5615.183
os: Mac Ventura 13.2

<img width="1197" alt="image" src="https://github.com/facebook/react/assets/40307803/f83ed673-cba0-4bc7-8403-aa6dda79e24b">

My import statement is
```javascript
import "react-devtools";`
import { createRoot, Root } from "react-dom/client";
```

**Comment by johnhunter** [comment]
I'm still seeing this issue, even on fairly small projects.

react: 18.2.0
react-dom: 18.2.0
react-devtools: 4.28.0
os: MacOS 13.5.2

**Comment by johnhunter** [comment]
@hoxyq Thanks, I'll report back when I get a chance to verify.

**Comment by AmirAmArA** [comment]
@johnhunter 
i don't if this is the same case as mine but i tried to update my nodejs to LTS and it solved the case

**Comment by chiptus** [comment]
I've been getting this for a few weeks. on chrome 119.0.6045.105 with extension version 4.28.5 (10/25/2023)

I enabled dev mode for extensions and now I see this error when I try to open it:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'sendMessage')
    at handleMessageFromPage (proxy.js:1:899)
handleMessageFromPage @ proxy.js:1
postMessage (async)
updateRequiredBackends @ backendManager.js:1
(anonymous) @ backendManager.js:1
welcome @ backendManager.js:1
postMessage (async)
sayHelloToBackendManager @ proxy.js:1
(anonymous) @ proxy.js:1
Show 3 more frames
Show less
```

hope this helps

**Comment by hoxyq** [comment]
> I've been getting this for a few weeks. on chrome 119.0.6045.105 with extension version 4.28.5 (10/25/2023)
> 
> I enabled dev mode for extensions and now I see this error when I try to open it:
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'sendMessage')
>     at handleMessageFromPage (proxy.js:1:899)
> handleMessageFromPage @ proxy.js:1
> postMessage (async)
> updateRequiredBackends @ backendManager.js:1
> (anonymous) @ backendManager.js:1
> welcome @ backendManager.js:1
> postMessage (async)
> sayHelloToBackendManager @ proxy.js:1
> (anonymous) @ proxy.js:1
> Show 3 more frames
> Show less
> ```
> 
> hope this helps.
> 
> this is the piece of code that throws the error:
> 
> ```ts
>  function handleMessageFromPage(o) {
>         if (o.source === window && o.data)
>             switch (o.data.source) {
>             case "react-devtools-bridge":
>                 n = !0,
>                 e.postMessage(o.data.payload);
>                 break;
>             case "react-devtools-backend-manager":
>                 {
>                     const {source: e, payload: n} = o.data;
>                     chrome.runtime.sendMessage({ // <=== here
>                         source: e,
>                         payload: n
>                     });
>                     break
>                 }
>             }
>     }
> ```
> 
> seems like `chrome.runtime` is not defined

Thanks for reporting this! It looks weird, because `proxy content script is running in ISOLATED world, which should have `chrome.runtime`.

I am also using Chrome v119.0.6045.105 and don't have such problem, is this constantly reproducible? Can you try reinstalling the extension?

**Comment by shengbeiniao** [comment]
react dev tools timeout when inspect large project

The timeout occurred at InspectedElementContextController 

![image](https://github.com/facebook/react/assets/3301995/70d10659-84e0-4e6a-a507-afd389372ad7)

**Comment by inoyakaigor** [comment]
>> Can you try reinstalling the extension?
I also have this issue. I have tried to reinstall react devtools and nothing changed

**Comment by megha8191** [comment]
anybody finds sol?

**Comment by AmirAmArA** [comment]
> anybody finds sol?

@megha8191 what is the versions of your stack ? nodejs, npm, chrome,

**Comment by kyrregjerstad** [comment]
I'm having almost the same issue, the profiler is forever stuck on 

```
Processing data...
This should only take a minute.
```

**Comment by JasonKretzer** [comment]
More information on this, I hope it helps.  
`React Dev Tools v: 5.0.0 (12/5/2023)`
`Chrome v: 122.0.6261.94 (Official Build) (64-bit)`
`Ubuntu v: 24.04`

Here is the code that lead to the error from the OP:
```javascript
import React from 'react';
import { render } from 'react-dom';

class StorePicker extends React.Component {
  render() {
    return <p>Hello!</p>
  }
}

render(<p>HEYYYY</p>, document.querySelector('#main'));
```

Once I replaced the render line with 
```javascript
render(<StorePicker />, document.querySelector('#main'));
```
The react dev tools started working.

**Comment by megha8191** [comment]
> > anybody finds sol?
> 
> @megha8191 what is the versions of your stack ? nodejs, npm, chrome,
> 
> i had the same problem updating nodejs solved it, try as well deleting the extension from chrome , updating it as well with the nodejs, solved it for me.

it is solved now , idk how

**Comment by inoyakaigor** [comment]
The problem is still exists btw

**Comment by javokhir-hayitmirzayev** [comment]
> I'm having almost the same issue, the profiler is forever stuck on
> 
> ```
> Processing data...
> This should only take a minute.
> ```

hi @kyrregjerstad 
have u solve that problem or found any solution or alternatives
Currently  i am facing the same issue dunno what to do

**Comment by timkindberg** [comment]
Still exists for me but only in Arc, works in Chrome
