### ISSUE TITLE
Bug: Problem when trying to render a list as a child of a context.provider element.

### ISSUE THREAD

**Issue by Justin-del** [facebook/react#25936]
React version:18.2.0

## Steps To Reproduce

1.  Download the file bug_reproduction.zip from https://github.com/Justin-del/bug_report and extract it into a folder.
2.  Inside the folder that contains all the extracted files, navigate to the frontend folder.
3.  At there, run the command npm run start.
4.  Open up a new browser window and navigate to localhost:3000.
5.  At there, click the 'Add task' button.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/70791146/209470478-4b5ebb1e-b8c2-434b-98fa-6ba639b20007.png">
6.  Write some task description and then click the 'Ok' button.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/70791146/209470561-443f1b8e-c905-485d-adcb-dd21aefd4461.png">
7.  Repeat step 5.

## The current behavior
This is the current behavior after running steps 1 to 7.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/70791146/209470778-d5036cb1-e1d8-4977-b4d8-eb91f421f5a0.png">

## The expected behavior
The behaviour that I expect to get after running steps 1 to 7:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/70791146/209470834-b0147364-edec-4b9d-bdf5-2296a43f744a.png">

## The code that causes this problem
<img width="960" alt="image" src="https://user-images.githubusercontent.com/70791146/209471209-26855cf0-0102-4ec0-a77f-f3c68f02fb7a.png">
Note: This problem does not occur when the circled code above is deleted and replaced with the circled code below.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/70791146/209471609-e795f210-f10e-4dcd-8dcd-2ce081e25347.png">

**Comment by eps1lon** [comment]
Can you convert this to a Codesandbox via https://react.new? This makes debugging easier for others.

**Comment by Justin-del** [comment]
Sure

**Comment by Justin-del** [comment]
Here's a link to the sandbox. 
https://codesandbox.io/s/lively-resonance-et8fhc?file=/src/Todos.tsx

**Comment by eps1lon** [comment]
You're creating a new context during render which means `context.Provider` is a new component. If React encounters a new component it'll throw away the whole subtree (even if it looks trivial in this case to reuse the children in this case).

What are you trying to do with `context = createContext` in the render of `Todos`?

**Comment by Justin-del** [comment]
Oh, I see. Thanks for the help @eps1lon.
