### ISSUE TITLE
Bug: Weird issue with `createRoot` when container is a self closing tag

### ISSUE THREAD

**Issue by burt202** [facebook/react#25931]
React version: `18.2.0`
React-dom version: `18.2.0`

Link to code example:

index.tsx
```
import * as React from "react"
import {createRoot} from "react-dom/client"
 
import App from "./app"
 
const container = document.body.querySelector("#container")
const root = createRoot(container)
 
root.render(<App />)
```

index.html
```  
 <html>
   <body>
     <div id="container" />
     <p>hello world</p>
   </body>
 </html>
```

## The current behavior

Everything in the `<body>` tag is removed, but `App` is correctly rendered in `<div id="container" />`

## The expected behavior

Everything outside of the root container should be left alone whilst `App` is correctly rendered in `<div id="container" />`

## The workaround

Weirdly if you use `<div id="container"></div>` instead of `<div id="container" />` it works as expected. Is this a bug or am i missing some knowledge here. Couldn't find anything after a quick google

Cheers!

**Comment by nattthebear** [comment]
```
<div id="container" />
```

This isn't valid HTML.  Void tags don't work the same was as they do in JSX and XML, in HTML.  Because of this, the browser is putting the `<p>` inside the `<div>`.

**Comment by almajuliot** [comment]
Correct me if i am wrong, div in html element shouldn't be written as self-closing tag. Because of that, i don't think this is a bug.

**Comment by burt202** [comment]
Thanks both for the responses. It makes perfect sense.

I've been doing the self closing div thing for years, its only this week i wanted something else in the body so I never realised my mistake :laughing:. Hopefully if anyone else gets stuck on this, maybe theyll find this thread to reduce any wasted time.

Cheers!
