### ISSUE TITLE
Bug: this reference after setState seems to be broken

### ISSUE THREAD

**Issue by michibe** [facebook/react#25937]
Hi there, 
i am facing an issue with the setState() method.

React version: 18.2.0

## The current behavior
I have a state containing a custom getter function. This getter function works fine but as soon as i update the state
the getter function still returns the old value because the "this reference" in the getter function is targeting the old instance.
   
## Steps To Reproduce

 [Fiddle Code example](https://jsfiddle.net/r9cdtaou/47/). If you press the first button "Update name to Ben" the name of the user is correctly updated to "Ben". If you press the button "Log name in Uppercase" the log output shows the old value "Mike" in uppercase. I dont't understand this behaviour because Object.assign() and {...state} are working fine, but within setState() the "this reference" seems to break and pointing to the old instance.

Fiddle: https://jsfiddle.net/r9cdtaou/47/

## The expected behavior

The custom getter function "getNameInUpperCase" has access to the updated value via "this.name"

**Comment by sahilpurav** [comment]
@michibe - I have corrected your code. See this - https://jsfiddle.net/sahilpurav/afgpwybh/

**Comment by michibe** [comment]
Hi @sahilpurav, thank you for the correction.
