### ISSUE TITLE
Bug: button with type="button" causes form to be submitted when immediately swapped with a button with type "submit"

### ISSUE THREAD

**Issue by vighnesh153** [facebook/react#25930]
Case: Render 2 different buttons, inside a form, based on a boolean flag. One of the button's type is `button` and other button's type is `submit`. When we click on any of the buttons, the boolean flag is toggled. When we click on the button with type `button`, it is also triggering the form's default submit action.

React version: `18.1.0`

## Steps To Reproduce
Reproducible code snippet
```tsx
function Buttons({ onSave }: { onSave: () => void, onEdit: () => void }) {
  const [isEdit, setIsEdit] = React.useState(false);

  return isEdit ? (
    <button
      type="submit"
      onClick={() => {
        setIsEdit(false);
        onSave();
      }}
    >
      Save
    </button>
  ) : (
    <button
      type="button"
      onClick={() => {
        console.log('Editing...');
        setIsEdit(true);
      }}
    >
      Edit
    </button>
  );
}

export default function App() {
  return (
    <div>
      <form>
        <Buttons
          onEdit={() => {}}
          onSave={() => {
            console.log('Saving...');
          }}
        />
      </form>
    </div>
  );
}
```

Link to code example:

https://stackblitz.com/edit/react-ts-moatfc?file=App.tsx

## The current behavior

Form is submitted when clicking the button with type `button`

## The expected behavior

Form should **not** be submitted when clicking the button with type `button`

**Comment by eps1lon** [comment]
This is unfortunately expected behavior in the DOM. By the time the click event bubbles to the form, the button is already a submit button.

You have to make sure the DOM treats these buttons as distinct elements e.g. by specifying different `key` props:
```diff

function Button({ onSave }: { onSave: () => void }) {
  const [isEdit, setIsEdit] = React.useState(false);

  return isEdit ? (
    <button
+     key="edit"
      type="submit"
      onClick={() => {
        setIsEdit(false);
        onSave();
      }}
    >
      Save
    </button>
  ) : (
    <button
+     key="save"
      type="button"
      onClick={() => {
        console.log('Editing...');
        setIsEdit(true);
      }}
    >
      Edit
    </button>
  );
}
```

Note that this will cause the button to loose focus upon activation.
