### ISSUE TITLE
Bug: BetaDocs - application tutorial tic-tac-toe zip error

### ISSUE THREAD

**Issue by fernandomk6** [facebook/react#25941]
React version:

## Steps To Reproduce

1. In the CodeSandbox tab you opened earlier, press the top-left corner button to open the menu, and then choose File > Export to ZIP in that menu to download an archive of the files locally
2. See the structure of the files.

Link to code example: [tutorial-tic-tac-toe](https://beta.reactjs.org/learn/tutorial-tic-tac-toe)

## The current behavior

Incorrect folder structure, throwing an error when performing an "npm start".

## The expected behavior

Zip file must contain the same folder structure as the online editor. And it should work when running "npm install".

[link to correctly organized folders](https://github.com/fernandomk6/curso-react.js-ninja-react-completo/tree/main/overview-docs/tic-tac-toe)

**Comment by fidraj** [comment]
I'm confirming issues with the zip file structure, the dependencies are all wrong and `npm start` produces errors with first step of the tutorial
```

**Comment by sampart** [comment]
> `npm start` produces errors with first step of the tutorial

If you're referring to an error about the shorthand fragment syntax (`<>` .. `</>`) shown in your code example, I fixe this by upgrading to the latest version of `react-scripts`. [More details about the fix here](https://stackoverflow.com/a/76455176/328817).

**Comment by pmayd** [comment]
Updating `react-scripts` to the latest version via "^5.0.0" did not solve the issue with empty tags `<>`, what did solve the problem was to use another HTML tag like `<div>...</div>`, this finally resolved the issue and started the app again. Really cool that the official tutorial of React.js is not working
