### ISSUE TITLE
Bug: Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.

### ISSUE THREAD

**Issue by wscourge** [facebook/react#25944]
React version: latest

## Steps To Reproduce

1. Render `<br />` tag.

[Link to code example](https://codesandbox.io/s/new?file=/src/App.js)

## The current behavior

It renders `<br />`.

## The expected behavior

It renders `<br>`.

## Context

I'd like React to support removing trailing slash from void HTML elements out of the box. Due to [validator.w3.org](https://validator.w3.org):

> Info: Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).

I originally requested this as [a feature in Next.js](https://github.com/vercel/next.js/issues/43995), and [was sent here](https://github.com/vercel/next.js/issues/43995#issuecomment-1363658473).

Cheers.

**Comment by vkurchatkin** [comment]
Can you provide an example where this is an issue?

**Comment by wscourge** [comment]
See here: https://validator.w3.org/nu/?doc=https%3A%2F%2Fhix.dev%2F

**Comment by vkurchatkin** [comment]
This doesn't seem to be an issue or problem of any kind. It's not even a "warning" message or something like that, it is and "info" message. The markup itself is perfectly fine and has no issues

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/validator/validator/issues/1509. This is just an "info" message. Either this should not be flagged at all or W3 validator should be more explicit about what "info" means. 

We could omit the trailing slash but we have to special case known void element tags which adds bytes and runtime cost so it's unlikely to give any gains.

**Comment by mohanad-b** [comment]
I found this, https://html.spec.whatwg.org/multipage/syntax.html#start-tags:void-elements
