### ISSUE TITLE
React Developer Tools crashes

### ISSUE THREAD

**Issue by beshur** [facebook/react#25943]
Hello.

Components tab is opened blank once on Chrome startup, than the tab does not appear at all in devtools.
 
Extension's service worker has this exception in inspect:
`Uncaught (in promise) Error: Duplicate script ID 'hook'`

Have tried reinstalling extension, relaunching chrome. The app is fairly simple and did not crash before.

Mac OS 13.0
Chrome 108.0.5359.124

**Comment by beshur** [comment]
Fixed itself 🤷

**Comment by hiroshi** [comment]
It's happning for me now.
macOS 13.2.1
Chrome 112.0.5615.49 (Official Build) (arm64)
React Developer Tools 4.27.3 (3/22/2023)

**Comment by rcherny** [comment]
Me too ... 

macOS 13.2.1
Chrome 112.0.5615.137 (Official Build) (x86_64)
React Developer Tools 4.27.6 (4/20/2023)
