### ISSUE TITLE
Bug: React Re-Renders Component When Set State is The Exact Same, but Only Once

### ISSUE THREAD

**Issue by agrawalishaan** [facebook/react#25947]
https://codesandbox.io/s/blissful-jepsen-luo8ce?file=/src/App.js

In this code, I set a state to true when a button is clicked. On the first click the log statement inside the handler runs, the state is set to true, the component re-renders, and 'the state is true' prints. On the second click, this happens again- why? I am setting state to a duplicate value so the component shouldn't re-render. Even if it were to re-render, it only ever happens twice, the third click and onwards only run the console.log inside the handler, not inside the component itself.

**Comment by priyank-svmx** [comment]
Third click onwards it only runs the code inside the click handler, by this time React reconciliation system has ascertained that React element tree will not change at all from the third time onwards

https://andreasheissenberger.medium.com/react-components-render-twice-any-way-to-fix-this-91cf23961625

**Comment by agrawalishaan** [comment]
Why does it take three runs and not two? The state being set is the same on the second run.

**Comment by agrawalishaan** [comment]
Also when I put Date.now() inside the JSX which changes the dom the same issue occurs

**Comment by ArnaudValette** [comment]
I think, but I could be wrong, that calling js code outside of a useEffect hook, per example, makes it "outside" of react lifecycles. 
The function is run, but maybe that doesn't mean that the component is rerendered.

**Comment by agrawalishaan** [comment]
I think that the component is re-rendered even with the bad non-useEffect code, as Date.now() updates each time.

**Comment by ArnaudValette** [comment]
For my part, on the codesandbox you sent, the date updates only once.

**Comment by agrawalishaan** [comment]
Right, but I was responding to:

The function is run, but maybe that doesn't mean that the component is rerendered.

Isn't the component being rerendered in my case, since I can see the date change?

**Comment by ArnaudValette** [comment]
The date change does not occur in what is rendered from the component, but in the corpse of the function, no ?
