### ISSUE TITLE
Bug: 'exhaustive-deps' lint rule warns that "Outer scope values" aren't valid when a hook is inside a function

### ISSUE THREAD

**Issue by finnp** [facebook/react#25958]
React version: 18.1.0

## Steps To Reproduce
Inside a functional component, an inner function with a dependency on value from an outer function triggers the warning, "Outer scope values like '....' aren't valid dependencies because mutating them doesn't re-render the component."

Here's the crux of the problem

```js
const List = (props: IListProps) => {
  const { items } = props;

  // Using the useMemo hook here doesn't complain, e.g. -
  // const names = useMemo(() => items.map(item => item.name), [items]);

  // Using the useMemo hook inside a function complains
  const names = useItemNames();

  return (
    <>
      <h2>There are {items.length} items in the list</h2>
      <section>
        {names.map(name => (
          <div>{name}</div>
        ))}
      </section>
    </>
  );

  ////////////////////

  function useItemNames() {
    // es-lint warns here: Outer scope values like 'items' aren't valid dependencies 
    // because mutating them doesn't re-render the component
    return useMemo(() => items.map(item => item.name), [items]);
  }
};
```

Link to code example: https://codesandbox.io/s/custom-hook-repro-3wfly

## The current behavior
The eslint rule will complain about unneccessary dependencies.

## The expected behavior
The eslint rule shouldn't be triggered.

This is a reopen and copy of https://github.com/facebook/react/issues/17060 by @gerrod

**Comment by sadiki-o** [comment]
i was just messing with the sandbox you posted early, can you check this one if it does the job you want it to do:
[sandbox](https://codesandbox.io/s/custom-hook-repro-forked-hidtdf?file=/src/index.tsx)
