### ISSUE TITLE
Bug: Hydration mismatch error for HTML entities in direct text children of <noscript> tag

### ISSUE THREAD

**Issue by jazeved0** [facebook/react#25969]
React version: 18.2.0

## Steps To Reproduce

1. In a React SSR app, include a `<noscript` JSX element with text children that contains an HTML entity, such as `&apos;`:
    ```jsx
    export default function App() {
      return <noscript>&apos;</noscript>;
    }
    ```
2. Render the React app on the server using `ReactDOMServer.renderToString` (no visible warnings appear):
    ```jsx
    const component = ReactDOMServer.renderToString(<App />);
    ```
    Of note, this appears to replace the HTML entity in final HTML output with a different entity:
    ```html
    ...<noscript>&#x27;</noscript>...
    ```
3. Attempt to hydrate the React app on the client using `hydrateRoot`:
    ```jsx
    hydrateRoot(document.getElementById("root"), <App />);
    ```
4. UI mismatch error occurs at hydration time

    ![image](https://user-images.githubusercontent.com/26242455/211048570-2e6f0051-1096-4bcd-91b3-c91f8fdebf46.png)

Link to code example: https://github.com/jazeved0/react-ssr-noscript-bug-reprod (steps to build/run are in the readme)

## The current behavior

Using an HTML entity in the direct text children of a `<noscript>` tag results in hydration errors on the client. I encountered this while building a [Gatsby](https://www.gatsbyjs.com/) static site where I wanted to include a `<noscript>`-wrapped warning in a component that only works when JavaScript is enabled (and this message includes an apostrophe character).

The following cases encounter the same/a similar error:
- Same example as above (and the one I originally encountered):

    ```jsx
    <noscript>&apos;</noscript>
    ```
- Using the direct character:
    ```jsx
    <noscript>'</noscript>
    ```
- Using the other HTML entity that React SSR uses, in the original source of the component:
    ```jsx
    <noscript>&#x27;</noscript>
    ```

The following cases do work:
- Wrapping the text containing the HTML entity in a plain `<div>`, inside the `<noscript>`:

    ```jsx
    <noscript><div>&apos;</div></noscript>
    ```
- Using `dangerouslySetInnerHTML`:
    ```jsx
    <noscript dangerouslySetInnerHTML={{ __html: "&apos;" }} />
    ```

## The expected behavior

All of the above cases (except wrapping the HTML entity in a `<div>`) should result in the same behavior, and exhibit no errors when hydrating on the client.

I believe this may be related to https://github.com/facebook/react/issues/11423 (although notably the behavior of "ignore <noscript> content on the client and don't warn about mismatches" doesn't seem to be case here).

**Comment by brettdh** [comment]
I've also seen this issue, but using a different tag:

```jsx
<span>&hellip;</span>
```

**Comment by brettdh** [comment]
🏓
