### ISSUE TITLE
Feat(renderToPipeableStream): Allow passing crossorigin attribute on bootstrapScripts

### ISSUE THREAD

**Issue by HenriqueLimas** [facebook/react#25989]
When using `window.onerror` in the bootstrap script that is hosted in a CDN the error message will show `"Script error."` instead of a proper error message. This is because of the [cross-origin](https://blog.sentry.io/2016/05/17/what-is-script-error/) script. To fix this issue a `crossorigin="anonymous"` attribute needs to be added in the script tag.

Currently, `bootstrapScripts` supports [`src` and `integrity`](https://github.com/facebook/react/blob/0fce6bb498357feb4465859912004b2e20fe7084/packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js#L226) as configurations, should it also supports a `crossorigin` property?

**Comment by ElmoJones3** [comment]
+1

**Comment by pixelhuh** [comment]
Right now, bootstrapScripts lacks flexibility because we can't set scripts attributes. My application needs custom data-attributes on the scripts for compatibility, but I can't set them, this is complicates development.

it would be cool to be able to do something like this:

```
const { pipe } = renderToPipeableStream(<Page someProps="" />, {
    bootstrapScripts: [{
        src: './main.js',
        crossorigin: true,
        'data-foo': 'bar',
    }],
    onShellReady() {
        res.setHeader('content-type', 'text/html');
        pipe(res);
    },
});
```
With this result:
```
<script src="/main.js" async="" crossorigin data-foo="bar"></script>
```

**Comment by gaearon** [comment]
Would someone like to send a PR?

**Comment by HenriqueLimas** [comment]
Sure, let me do that
