### ISSUE TITLE
Profile Section is not updated automatically after updating profile picture 

### ISSUE THREAD

**Issue by shreya-as** [facebook/react#25985]
Profile Section is not updated automatically after updating profile picture

**Comment by shreya-as** [comment]
test carefully

**Comment by shreya-as** [comment]
1. **test ### `**`

**Comment by SoumyadeepOSD** [comment]
> Profile Section is not updated automatically after updating profile picture

Hey @shreya-as  can you provide me some more information about the issue?

**Comment by MamadTaheri** [comment]
> fully

give us more info or code. it seems to be a state update issue.
