### ISSUE TITLE
Bug: React.Lazy causes parent components to rerender

### ISSUE THREAD

**Issue by barelyconfused** [facebook/react#25993]
React version: 18

## Steps To Reproduce

1.Import Component using React.Lazy
2.When component is loaded, parent Components all rerender, causing all child components to rerender. If there are hundres of components on screen, this will defeat the purpose of lazy loading. This does not happen when using third party library such as @loadable/component

**Comment by gymgym1212** [comment]
@barelyconfused Do you use `Suspense` component?

**Comment by barelyconfused** [comment]
@gymgym1212. Just tried it with Suspense and it looks like it solves the issue. However, I remember trying it before with Suspense but refs do not work. The only workaround for that is to use setInterval to wait for the refs to appear in ComponentDidMount. Do you know of a better way?

**Comment by barelyconfused** [comment]
@gymgym1212 Ah i just figured it out using callback ref. Thanks for pointing me in the right direction though

**Comment by koiomi** [comment]
@barelyconfused Hi, how exactly does ‘using callback ref.’ work? Can you give me an example? I think I'm having the same problem as you.

**Comment by barelyconfused** [comment]
> @barelyconfused Hi, how exactly does ‘using callback ref.’ work? Can you give me an example? I think I'm having the same problem as you.

Instead of creating ref using useRef or ReactCreateRef, pass a callback function that will set the ref when the ref is mounted.

Example class component:
 
setChartRef(ref){

  if(ref)  //ref is available
  this.chart= ref;
}
....

<Suspense>
<Chart chartRef={ref => this.setChartRef(ref)}
</Suspense>


class Chart extends React.Component {
...
render(){
  return (
  <ChartComponent ref={this.props.chartRef} />
  )
}
