### ISSUE TITLE
Bug: eslint-plugin-react-hooks does not support TypeScript "satisfies" operator

### ISSUE THREAD

**Issue by Egor-Koldasov** [facebook/react#26004]
React version: 18.2.0

## Steps To Reproduce

1. Install typescript@4.9.4, eslint@8.32.0 and latest eslint-plugin-react-hooks@4.6.0
2. Enable "react-hooks/exhaustive-deps" rule
3. Use "satisfies" operator for a callback function passed:
``` TypeScript
// Error: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead. eslintreact-hooks/exhaustive-deps
const onClick = useCallback(
  (() => {
    return true;
  }) satisfies () => true,
  // Expected to see eslint error: The true literal is not a valid dependency because it never changes. You can safely remove it. eslintreact-hooks/exhaustive-deps
  [true]
);
```

Link to code example:
Here I created a repo with the minimal demo to reproduce the issue, CodeSandbox does not allow to configure eslint properly:
https://github.com/Egor-Koldasov/eslint-plugin-react-hooks-satisfies-error

## The current behavior
Plugin shows the error and doesn't check actual dependencies passed to the `useCallback`:
```
React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead. eslintreact-hooks/exhaustive-deps
```

## The expected behavior
It should work exactly the same way as it works without "satisfies" operator used. No error "received a function whose dependencies are unknown" and dependencies passed are successfully checked.

**Comment by eps1lon** [comment]
@Egor-Koldasov Can you double check if this still reproduces with the latest version of `@typescript-eslint/*`?

**Comment by rodrigofariow** [comment]
This still happens with the latest versions of both @typescript-eslint/* and eslint-plugin-react-hooks.

Any ideas @eps1lon ?

**Comment by Grawl** [comment]
Just faced this issue

- `eslint-plugin-react-hooks@6.0.0`
- `@typescript-eslint/eslint-plugin@8.31.1`

**Comment by Grawl** [comment]
If it's not planned, what is a workaround? Can I disallow `satisfies` inside components somehow with ESLint?

**Comment by Grawl** [comment]
```
{
        files: ['**/*.tsx'],
        rules: {
            'no-restricted-syntax': [
                'error',
                {
                    selector: 'TSSatisfiesExpression',
                    message:
                        '`satisfies` keyword breaks lint rules inside React components, please use it outside of .tsx files. React team are not interested: https://github.com/facebook/react/issues/26004',
                },
            ],
        },
    },
```
