### ISSUE TITLE
Bug: Unable to dynamically add a created Portal as a child

### ISSUE THREAD

**Issue by roysandrew** [facebook/react#26012]
Elements can be added as children to some parent arbitrarily after being created but after creating a portal there seems to be no obvious way of appending the resulting portal as a child of some other node. This is useful for creating dialogs that need to use multiple contexts available to some node but where there are enough of these dialogs that come from user interaction that it's desirable for them to be invoked functionally (e.g. showDialog).

The problem is there seems to be no functioning way for a portal created in this way to properly inherit contexts. I've provided an example showing the creation of some portal and an example method of trying to insert the returned fiber (? - unsure if this is the correct term, React.ReactPortal type) as a child of portalParentRef.

React version: 17/18

## Steps To Reproduce

1. Create a portal with something like
`const portal = ReactDOM.createPortal(
    React.createElement(ExampleComponent),
    document.body);`
2. There does not seem to be an accessible method for appending the resulting React.ReactPortal instance as a child but trying appendChild, or render (which I don't believe can work because we're not trying to mount a real DOM element but instead want to insert this portal as a child in the virtual dom).
3. If we 

Link to code example: https://codesandbox.io/s/silly-brook-25fc4f

## The current behavior

The portal can be created which will insert our Dialog (the component which needs access to contexts) at the top level document.body but there seems to be no functioning way for the resulting React.ReactPortal to be added to the virtual DOM thus the created Dialog can't read values from any context.

## The expected behavior

There should be some way of adding a created React.ReactPortal to an existing node.

**Comment by shreya-as** [comment]
no idea about this

**Comment by shreya-as** [comment]
no idea about this

**Comment by shreya-as** [comment]
no idea about this
