### ISSUE TITLE
[DevTools Bug]: This page doesn't appear to be using react

### ISSUE THREAD

**Issue by Archimagus** [facebook/react#26024]
### Website or app

reactjs.org

### Repro steps

Go to website.
Click on the react DevTools icon in the extensions.
after reaload, hover the extension.
![image](https://user-images.githubusercontent.com/7319949/213579759-5a8dcd59-6492-4c67-b8bd-0a09f7017a92.png)
![image](https://user-images.githubusercontent.com/7319949/213581014-fe55022f-783d-4e53-9c9d-3e804e62498a.png)

### How often does this bug happen?

Every time

**Comment by mondaychen** [comment]
Does it help if you restart the browser?

**Comment by Archimagus** [comment]
No, restarting the browser, clearing the cache, restarting the PC, trying
different web sites doesn't work.  I haven't tried on a different browser
yet.

**Comment by mondaychen** [comment]
Can you let me know which browser and OS you are using, and their version numbers? Thanks!

**Comment by Archimagus** [comment]
Edition	Windows 10 Enterprise
Version	22H2
OS build	19045.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

Browser:
Version 99.0.4840.0 (Official Build) canary (64-bit)

![image](https://user-images.githubusercontent.com/7319949/214056997-fcaa6f60-4052-4630-84b7-940c6a4ae2c3.png)

**Comment by mondaychen** [comment]
Any reason you need to stay on that version of Chrome? I think the latest stable version is v109

**Comment by Archimagus** [comment]
Thanks.  It appears my Org has decided to block automatic updates of Chrome.  After manually downloading and installing the latest canary
Version 111.0.5555.0 (Official Build) canary (64-bit)
dev tools are working again.
