### ISSUE TITLE
Bug: Ternary operator behaving different from equivalent `&&` operator in JSX rendering

### ISSUE THREAD

**Issue by sanjarcode** [facebook/react#26023]
React version: 18.2.0

## Steps To Reproduce

1. Create a project using `create-react-app`
2. Overwrite `App.js` with given code
3. Run the app
4. Click both _numbered_ buttons, at least once.
5. Click "toggle"

Problem: The ternary one seems to save and/or share the state for two separate instances, while the equivalent `&&` one _really_ treats them as separate instances.

Link to code example: https://codesandbox.io/s/nervous-cerf-ndmu71?file=/src/App.js
Code:
```jsx
import { useState } from "react";

export default function App() {
  const [show, setShow] = useState(true);

  return (
    <div>
      <h1>Ternary is not equivalent to && ?</h1>
      <button onClick={() => setShow((_) => !_)}>Toggle</button>
      {show ? <MyButton title="A ternary" /> : <MyButton title="B ternary" />}
      {show && <MyButton title="A &&" />}
      {!show && <MyButton title="B &&" />}
      <hr />
    </div>
  );
}

function MyButton({ title }) {
  const [count, setCount] = useState(0);

  return (
    <button onClick={() => setCount((_) => _ + 1)}>
      {title} {count}
    </button>
  );
}
```

## The current behavior
Ternary and equivalent logical `&&` don't give the same result.

## The expected behavior
Both should behave the same, at least effectively.

**Comment by eps1lon** [comment]
Could you describe concretely how `&&` should behave and the ternary operator should behave? Visually, I can see no difference in the rendered buttons.

**Comment by sanjarcode** [comment]
There is a visual difference. 

Consider the following steps:
1. App loads
2. Click once on both numbered buttons
3. Click toggle. 

Why are the two ternary cases retaining state, even after they have been unmounted?

**Comment by sanjarcode** [comment]
I'm talking about state here. And yes, _there is_ a visual difference. 

Consider the following steps:
1. App loads. State: (A ternary 0), (A && 0)
2. Click once on both numbered buttons. State: (A ternary 1), (A && 1)
3. Click toggle. State: (B ternary 1, B && 0).

The final state _should be_ (B ternary 0, B && 0), because both "B ternary" is a new instance, so it's state is 0.

Why are the two ternary cases retaining their old state, even after they have been unmounted?

**Comment by yousefelgoharyx** [comment]
@sanjarcode 
You might want to take a look at this:

https://beta.reactjs.org/learn/preserving-and-resetting-state#same-component-at-the-same-position-preserves-state

I hope this helps. 
The jest is that: the same component at the same position preserves the state.

Both A ternary and B ternary are at the same position, therefore the state is preserved.

I love to think about a component within the ternary operator as the same component just with different props

**Comment by sanjarcode** [comment]
This addresses a large portion of the issue.
Also, it's good to know this is known behavior.

**Opinion**: I feel it should not be this way, since I am having to ["think"](https://en.m.wikipedia.org/wiki/Principle_of_least_astonishment) about the resulting JSX as opposed to treating a component as a rigid abstraction - you don't need to what's going down in it, generally (ignore optimization).

**Comment by frfancha** [comment]
B ternary is the first in the list and still the same type of component of previously first A ternary, so yes it is just A ternary reused.
B&& is third item in the list (2nd one is "false" of A&&), sio replacing the previous third item which was "false".
So yes B&& is a new instance and B ternary is not.
Perfectly normal.
And luckily it is like that ! It is the matching by component type and tree position that allows react to minimally update the DOM.
