### ISSUE TITLE
Bug: FiberRootNode is retained in memory after root is unmounted

### ISSUE THREAD

**Issue by Jeronimotio** [facebook/react#26031]
Calling `useEffect` in child component will keep the `FiberRootNode` in memory along with the current props, keeping it in the `rootWithPassiveNestedUpdates` variable even after the root node is unmounted. If there were large objects in the properties of the root element, then they will never be collected by the garbage collector until some other root element schedules its effect.

React version:
18.2.0

## Steps To Reproduce

1. Open the link below. In the console, you will see logs of the current value of the weak ref.
2. `<App>` will be rendered and unmounted in `<Child>` component.
3. You will see that value of  weak reference is retained in memory forever.
4. Open demo in separate tab.
5. Open dev tools on the "Memory" tab.
6. Collect garbage.
7. Capture memory snapshot and search `HeavyBigModel`.
8. You will see that model is retained in `rootWithPassiveNestedUpdates`.

![image](https://user-images.githubusercontent.com/4510923/213873385-8b7daaf1-969e-4f35-986b-d7638781e972.png)

Link to code example:
https://codesandbox.io/s/nifty-bush-r4k4tw

## The current behavior
Properties of the root component are retained in memory.

## The expected behavior
Properties should not be retained in memory. It might be possible to explicitly assign `null` to `rootWithPassiveNestedUpdates` and `rootWithNestedUpdates` when root is unmounted.

**Comment by whatwg6** [comment]
similar issue: https://github.com/facebook/react/issues/26089

**Comment by Jeronimotio** [comment]
> similar issue: https://github.com/facebook/react/issues/26089

Good find! I tried to reproduce this on the modern api, but it didn't work for me.

I have sandboxed your example: https://codesandbox.io/s/green-dew-u87p53?file=/src/App.tsx

Steps To Reproduce:
1. Click the unmount button.
2. Follow steps 3-8 from the first comment.

**Comment by rickhanlonii** [comment]
This is expected, in the current alternate model, we retain the reference in the alternate tree until the next render instead of paying the cost of traversing the tree an additional time on unmount just to clean up the references. Most of the time this is fine, because an unmount will be followed by and additional render. It's a known limitation of the current model, which will be fixed when we move to a different rendering model.
