### ISSUE TITLE
Issue of Invalid Hook Call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by Rushil20** [facebook/react#26037]
Hello everyone, 
I'm trying to use useQuery() react hook and i'm getting error of invalid hook call and i don't know how to solve it. Please someone suggest me solution for my problem.

-> App.js File : 

import './App.css';
import {Users}  from './components/user';
function App() 
{
  return(
  <div className='App'>
       <Users />
  </div>
  );
}
export default App; 

-> Users.js: 

import { useQuery } from "@tanstack/react-query";
import Axios from 'axios'

export const Users = () => {
    const {data : userinfo} = useQuery(['users'],async () =>
    {
        return await Axios.get('https://random-data-api.com/api/v2/users').then((res) => res.data)
    });
    return (
        <div>
            <h1>users : {userinfo}</h1>
        </div>
    )
}

**Comment by jzombie** [comment]
Two things:

1. This is a third-party library, so any questions about it should be asked in the relevant repo.
2. It looks like you're trying to build your own hook, see this: https://reactjs.org/docs/hooks-overview.html#building-your-own-hooks

**Comment by judicaelandria** [comment]
hey @Rushil20 , your code looks fine but can you provide an example that reproduces this using codesandbox or stackblitz please?

**Comment by Rushil20** [comment]
> This is a third-party library, so any questions about it should be asked in the relevant repo.

Sorry I didn't know it I'll take care of it from next time.

**Comment by Rushil20** [comment]
> hey @Rushil20 , your code looks fine but can you provide an example that reproduces this using codesandbox or stackblitz please?

Thanks, but issue is solved.
It was issue of api returning data in different form and I was storing in different form.
