### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'createElement' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by 98rahul** [facebook/react#26042]
### App

using flipper dor react devtools

### Repro steps

migrate to current version of  RN-0.71.1
using flipper 
enable hermes engine
run the app

### How often does this bug happen?

Every time

### Error message (automated)

ERROR  TypeError: Cannot read property 'createElement' of undefined, js engine: hermes 

### Error call stack (automated)

```text
ERROR  TypeError: Cannot read property 'createElement' of undefined, js engine: hermes 

this is related to --->> path: node_modules/react-devtools-core/dist/backend.js
function initialize() {
  canvas = window.document.createElement('canvas');
  canvas.style.cssText = "\n    xx-background-color: red;\n    xx-opacity: 0.5;\n    bottom: 0;\n    left: 0;\n    pointer-events: none;\n    position: fixed;\n    right: 0;\n    top: 0;\n    z-index: 1000000000;\n  ";
  var root = window.document.documentElement;
  root.insertBefore(canvas, root.firstChild);
}
```

**Comment by ryancat** [comment]
Hi @98rahul, thanks for flagging this. This is a known issue in RN apps when using the React DevTools plugin and turn on the trace update highlight feature in profiler. This issue should've been fixed recently with #26060.
