### ISSUE TITLE
[DevTools Bug]: Expected static flag was missing

### ISSUE THREAD

**Issue by Contrick64** [facebook/react#26077]
### Website or app

https://github.com/Contrick64/scryfall-random

### Repro steps

This error reproduces on initial page load. I can't seem to find what caused it to start showing up, as it points to a part of my code that has existed since well before I first got the error.

### How often does this bug happen?

Every time

**Comment by eps1lon** [comment]
Possibly duplicate of https://github.com/facebook/react/issues/24391

Could you check if you have something like https://github.com/facebook/react/issues/24391#issuecomment-1107796997 in your codebase?

**Comment by Contrick64** [comment]
Ah, yes. I had `useState` and `useEffect` within an if statement. Fixing that has removed the error!
