### ISSUE TITLE
Bug: Conditional hooks undetected by `eslint-plugin-react-hooks` inside callback components

### ISSUE THREAD

**Issue by gdbroman** [facebook/react#26072]
React version: 18.2.0

I'm specifically experiencing this problem with the mobx-react `observer()` decorator, but I think there's a larger issue here, of `eslint-plugin-react-hooks` not detecting conditional hooks inside React components that are passed as callbacks.

#### ✅ Conditional hook detected

```ts
export const RegularComponent = () => {
  if (Math.random() === 1) return <div />;

  useEffect(() => {
    console.log("I trigger `react-hooks/rules-of-hooks`.");
  }, []);

  return <div>I'm a regular component</div>;
};
```

#### ❌ Conditional hook undetected when component is passed as callback

```ts
export const DecoratedComponent = observer(() => {
  if (Math.random() === 1) return <div />;

  useEffect(() => {
    console.log("I go unseen.");
  }, []);

  return <div>I'm a decorated component</div>;
});
```

Live demo: https://codesandbox.io/s/conditional-hooks-25bw2v?file=/src/DecoratedComponent.tsx

**Comment by gdbroman** [comment]
Suggestion: make the `eslint-plugin-react-hooks` rule customizable to allow any wrapper and generalize the preexisting logic for `forwardRef` and `memo`. E.g:

https://github.com/facebook/react/blob/ce09ace9a23b61dfba53f5a83d52b377bc642bae/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L77-L88

Could be turned into:

```ts
/**
 * Checks if the node is a callback argument of an allowed anonymous
 * functional component.
 */

function isCallback(node, anonymousFnName) {
  return !!(
    node.parent &&
    node.parent.callee &&
    isReactFunction(node.parent.callee, anonymousFnName)
  );
}
```

**Comment by eps1lon** [comment]
The plugin needs components to be named. This restriction is necessary to prevent false-positives and pushes people to write components that are easier to debug (since they're named now). 

Once you convert the component to a named one, the plugin should trigger as expected:

```diff
-export const DecoratedComponent = observer(() => {
+export const DecoratedComponent = observer(function Component() {
   if (Math.random() === 1) return <div />;
 
   useEffect(() => {
     console.log("I go unseen.");
   }, []);
 
   return <div>I'm a decorated component</div>;
 });

**Comment by gdbroman** [comment]
> The plugin needs components to be named. This restriction is necessary to prevent false-positives and pushes people to write components that are easier to debug (since they're named now).

Once you convert the component to a named one, the plugin should trigger as expected:

Ah, that makes sense, then I'll just change our codebase's pattern to something like:

```tsx
const Component = () => { ... }
export const DecoratedComponent = observer(Component);
```

Thanks a lot @eps1lon!
