### ISSUE TITLE
Making React warn the user when `createElement` is called with `undefined` for the `type` argument

### ISSUE THREAD

**Issue by gabrielecirulli** [facebook/react#2607]
I spent the last hour trying to fix an issue that was caused by me trying to render a `CSSTransitionGroup` when the actual variable was undefined.

The root cause was me misinterpreting that `require("react/addons")` would return the whole `React` instead of just `React.addons` (which is my bad), but the error itself and the stack trace were extremely cryptic and it took me a while to even get a clue that the reason why it wasn't working was that I was just trying to render an undefined type.

This is the actual exception:

```
Uncaught TypeError: Cannot read property 'defaultProps' of undefined
```

And here's the stack trace:

![developer tools - http___localhost_3000_requests_new from_template 3](https://cloud.githubusercontent.com/assets/886011/5201545/dda098f6-7573-11e4-9bed-4db35dbc520d.png)

You can see that, ultimately, execution comes crashing down when React tries to look at `defaultProps` on my undefined type, which of course raises an exception.

The reason why this was confusing to me is that the exception happened quite far away from the source cause and, as a secondary factor, this code worked completely fine before I started porting it to Browserify and made my mistake with `react/addons`. This lead me to a wild set of hypotheses as to why it wasn't working, such as assuming it might be due to a regression in React 0.12 (since it's been migrating from `React.renderComponent` to `React.render` and I thought `CSSTransitionGroup` might have been lagging behind), to thinking it could be a problem with `CSSTransitionGroup` itself.

The reason why I raise this issue is that, since passing an `undefined` type won't work anyway, it would make sense if React could check for `undefined` and warn about it or maybe even raise an exception (since it would crash soon after anyway). 

My instance was a bit more extreme and if something like this happens to someone else they'll probably know where they screwed up in the first place, but some help from React would always be welcome!

**Comment by gabrielecirulli** [comment]
Thanks! :+1:

**Comment by akkhil7** [comment]
If you are giving the whole jsx code under the script tag, then the order of declaration of the components could cause this issue. 

When the inbuilt compiler sees a *component* which you've *later* declared in the code, it'll throw an error. 

However in plain terms, this just means that the component is missing.

**Comment by ratneshnavlakhe** [comment]
Getting this 
bundle.js:87 Uncaught TypeError: Cannot read property 'createElement' of undefined

Any solutions

**Comment by gaearon** [comment]
@ratneshnavlakhe Please ask on StackOverflow; this is hard to answer without seeing your complete code.

**Comment by ratneshnavlakhe** [comment]
@gaearon here is my code ...

`import { React, Component } from 'react';
import {render} from 'react-dom';

class App extends Component {
  render () {
    return <p> Hello React this is a webpack!</p>;
  }
}

render(<App/>, document.getElementById('app'));
`

**Comment by gaearon** [comment]
```js
import { React, Component } from 'react';
```

is incorrect, should be 

```js
import React, { Component } from 'react';
```

There is no named export named `React`. It is confusing because React is a CommonJS module, and since you’re using ES6 imports, Babel tries to map the semantics but they don’t match exactly. `{ Component }` actually grabs `Component` from `React` itself so you might just `import React from 'react'` and use `React.Component` instead if it’s less confusing.

**Comment by ratneshnavlakhe** [comment]
Woah, thank you @gaearon for a nice clarification.
