### ISSUE TITLE
eslint-plug-react-hooks -- Please add Support customHook simliar to useImperativeHandle 3 args 

### ISSUE THREAD

**Issue by LiangMingChen** [facebook/react#26099]
https://github.com/facebook/react/blob/2ef24145e4628fda9d8883cd573553b82a2e0a81/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L1751

In order to have custom Hook like useImperativeHandle>
getReactiveHookCallbackIndex need to return 1, 
but 
https://github.com/facebook/react/blob/2ef24145e4628fda9d8883cd573553b82a2e0a81/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L1766
Can only return 0 or -1.

Can we add a config as a Javascript object 
( { `useMemoDispatch`: 1 })
or 
{
  1: "(useMemoDispatch|myCustomHook)",
}

**Comment by coderstar1234** [comment]
the user-defined error will get exchanged with a perenties problem will check.

**Comment by coderstar1234** [comment]
> https://github.com/facebook/react/blob/2ef24145e4628fda9d8883cd573553b82a2e0a81/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L1751
> 
> In order to have custom Hook like useImperativeHandle>
> getReactiveHookCallbackIndex need to return 1, 
> but 
> https://github.com/facebook/react/blob/2ef24145e4628fda9d8883cd573553b82a2e0a81/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L1766
> Can only return 0 or -1.
> 
> Can we add a config as a Javascript object 
> ( { `useMemoDispatch`: 1 })
> or 
> {
>   1: "(useMemoDispatch|myCustomHook)",
> }

Some changes in a code contact me.

**Comment by Ainias** [comment]
There is at least a MR open which includes the changes: https://github.com/facebook/react/pull/24344

**Comment by Ainias** [comment]
Still relevant

**Comment by ahoisl** [comment]
This is still an issue, but commenting was disallowed, so did not have an option to "bump"
