### ISSUE TITLE
Bug: Manual click event handler added from useEffect fires during the click event

### ISSUE THREAD

**Issue by hustle-dev** [facebook/react#26090]
React version: ^18.2.0

## Steps To Reproduce

1. click button
2. The event listener is attached and the callback function is executed immediately as soon as the button is clicked.

Link to code example: https://codesandbox.io/s/sad-firefly-sphup6?file=/src/App.tsx

`App.tsx`

```tsx
import { MouseEvent, useEffect, useState } from "react";
import type { ReactNode } from "react";

type DropdownProps = {
  target: HTMLElement | null;
  children: ReactNode;
};

function Dropdown({ target, children }: DropdownProps) {
  useEffect(() => {
    if (!target) return;

    const listener = () => {
      console.log("listener executed");
    };

    document.addEventListener("click", listener);
    return () => document.removeEventListener("click", listener);
  }, [target]);

  if (!target) {
    return null;
  }

  return <div>{children}</div>;
}

function App() {
  const [target, setTarget] = useState<HTMLButtonElement | null>(null);

  return (
    <div>
      <button
        onClick={(e: MouseEvent<HTMLButtonElement>) =>
          setTarget(e.currentTarget)
        }
      >
        Button
      </button>
      <Dropdown target={target}>dropdown test</Dropdown>
    </div>
  );
}

export default App;
```

## The current behavior

The event listener fires and listener runs as soon as the first button is clicked.

## The expected behavior

The event listener should run when the second button is pressed or click anywhere in the document, not the first button click.

**Comment by rahulthedevil** [comment]
It seems totally fine. @hustle-dev 
On the first load, the target is null, so no listener is assigned.
On clicking the Button, it assigns the target with setTarget, which also assign the listener to the whole document - **document.addEventListener("click", listener);**

So on clicking anywhere in the whole document, it will trigger the **const listener = () => {}** everytime

So the code is working as expected

**Comment by hustle-dev** [comment]
@rahulthedevil 

I agree with everything you said. But what I'm trying to say is that the listener fires as soon as the button is clicked. 

Check out this gif or run through the examples on codesandbox.

![dropdown test](https://user-images.githubusercontent.com/53992007/216662431-7500b483-12a4-421e-b396-a1dfcc0cb9d3.gif)

**Comment by gaearon** [comment]
This is not related to concurrency, so I edited the title.

I don't see a bug here. This is the intended behavior. You've added a click handler *during the click*, so it catches that click. Before React 18, this behavior was inconsistent, so sometimes it would fire the handler and sometimes it wouldn't. Now it always catches the event.

See https://github.com/facebook/react/issues/24657#issuecomment-1150119055 for explanation and workarounds.
