### ISSUE TITLE
Dev + strict mode, how to send only one request on page load?

### ISSUE THREAD

**Issue by revmischa** [facebook/react#26092]
I read though https://github.com/facebook/react/issues/24502 and https://beta.reactjs.org/learn/you-might-not-need-an-effect#fetching-data and I am clear that if you do a request with `useEffect` you should return a cleanup handler that aborts whatever you were doing in case the component is unmounted.

However I have a situation where I'm not sure if this advice applies. I have a page that is used as a redirect URL for an OAuth flow where a code is received. This page needs to read the code from the URL and then send it to the backend for fetching and storing a refresh token for the user for the external service. This request can only be performed once, and it should happen on page load when we have the code parameter available. 

Since the request is initiated when the page is loaded via `useEffect`, it isn't really cancelable. This setup works fine except when running with strict mode in development; it then sends the request to exchange the code for refresh token twice, so the second request fails. How would you recommend ensuring this request is only made once ever?

**Comment by revmischa** [comment]
That's a fair point. Right now the logic is in a hook that also provides the current state to the component making use of the hook. The hook could be split up into the code exchange bit at the top level application. Perhaps the state can be shared with the relevant component with context. Let me try this.
Thanks for your prompt answer! Wasn't sure if there was a better place to ask.

**Comment by lb1129** [comment]
> If it needs to happen on load, does it need to be in a React component at all? Could you put this logic at the top level?
> 
> Like this: https://beta.reactjs.org/learn/synchronizing-with-effects#not-an-effect-initializing-the-application

The request was executed when the file was loaded, which is unreasonable

**Comment by lb1129** [comment]
Remove strict mode or use a flag
