### ISSUE TITLE
BUG: Why do not extract key and ref after merge defaultProps?

### ISSUE THREAD

**Issue by Caesar-0615** [facebook/react#26094]
https://github.com/facebook/react/blob/9d111ffdfbcfee4b348a3d49c16f02cb718c896f/packages/react/src/ReactElement.js#L420-L427

After reading the implementation of `ReactElement`, i understand that `key` and `ref` will be extracted from props, but why do not extract them after merging defaultProps?

```tsx
interface FooProps {
  key?: string;
  ref?: string;
  name: string;
}

const Foo: React.FC<FooProps> = (props) => {
  console.log(props.key, props.ref)

  return (
    <span key={props.key}>
      Hello, {props.name}!
    </span>
  )
}

Foo.defaultProps = {
 key: 'fooKey',
 ref: 'fooRef'
}

export default Foo
```

```tsx
const App: React.FC = () => {
  return (
    <div className="App">
      <Foo name="jack" />
    </div>
  )
}
```

and the log message will be `fooKey fooRef`!

**Comment by ctititic** [comment]
i also find this bug

**Comment by ctititic** [comment]
I have a question too！ @bpas247 created a pr https://github.com/facebook/react/pull/17427 to add warning，but was closed with unmerged
