### ISSUE TITLE
Bug: click event handler missed after append to body

### ISSUE THREAD

**Issue by HomyeeKing** [facebook/react#26108]
React version: 18.2.0

## Steps To Reproduce

1. open https://codesandbox.io/s/xenodochial-chaum-r6q1y4?file=/src/App.js  then open console panel
2.  click `Hello CodeSandbox` at first, you will see a log
3. after 3s, it's appended to body, the click handler get invalid

Link to code example:

## The current behavior

https://user-images.githubusercontent.com/49113249/216763195-661ae184-f6d3-4483-8e36-98592cd50597.mov

**Comment by alirezahematidev** [comment]
Hello.
The react applications need a DOM root element to render in it, which is defined in index.js (usually a div with "root" id).
React consider this element to updating it virtual DOM, so in your example, you append the h1 tag with id test out of the "root" element (you can see in browser inspect), which means react no longer track this element to update.

**Comment by NIKHILNAIR21** [comment]
ReactDOM.createRoot(document.getElementById('root')); update to this is index.js
