### ISSUE TITLE
Bug: Usage of the new root API causes double API calls within useEffect - no StrictMode

### ISSUE THREAD

**Issue by sorinpav** [facebook/react#26103]
Since we started using the new reactDOM.createRoot api, we are seeing double API calls in our network trace. The API calls are made in JSX components, within useEffects that run based on a set of dependencies which haven't changed since the upgrade.  

If we move back to using the legacy root api, the api calls are not doubled anymore. 
Worth mentioning that our project is **not using StrictMode**. 

React version: 18.2.0

Link to code example:
I don't have a code example, as this code is proprietary, but I can try to mock something up if the above description is not explicit enough. 

## The current behavior
Our project emits double API calls to the same endpoint, for the same data. 

## The expected behavior
There should be only one API call, and this was the behaviour before starting to use createRoot instead of reactDOM.render

**Comment by gaearon** [comment]
We'd need to see a reproducing example. I don't think we're familiar with any behavior like this.

The one special case I can think of is that we re-fire `useLayoutEffect` if something suspends and then later unsuspends.

**Comment by sorinpav** [comment]
I can confirm that this was an issue due to how our code was written, rather than an issue with the React behaviour. Apologies!
