### ISSUE TITLE
Bug: React.lazy component  can't set Ref

### ISSUE THREAD

**Issue by coder-xsy** [facebook/react#26125]
React version: 18.2

app.tsx
`
import React from "react";
import CompSync from "./component";
import "./styles.css";

const Comp = React.lazy(() => import("./component"));

export default function App() {
  const lazyRef = React.useRef();
  const syncRef = React.useRef();
  React.useEffect(() => {
    console.log("lazyRef current", lazyRef.current);
  }, [lazyRef.current]);
  React.useEffect(() => {
    console.log("syncRef current", syncRef.current);
  }, [syncRef.current]);
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <CompSync ref={syncRef} />
      <React.Suspense fallback={<div>test</div>}>
        <Comp ref={lazyRef} />
      </React.Suspense>
    </div>
  );
}
`
./component.tsx
`
import React from "react";
const Comp = React.forwardRef((props, ref) => {
  return <div ref={ref}>test</div>;
});
export default Comp;
`

Link to code example:
https://codesandbox.io/embed/gifted-banzai-hs45yb?fontsize=14&hidenavigation=1&theme=dark

## The current behavior
log:
lazyRef current undefined
syncRef current <div>test</div>
lazyRef current undefined
syncRef current <div>test</div>

## The expected behavior
log：
lazyRef current undefined
syncRef current <div>test</div>
lazyRef current <div>test</div>
syncRef current <div>test</div>

**Comment by kassens** [comment]
This is working as intended. The ref isn't set until the lazy component is rendered. If you wrap the `console.log` in a timeout you should see the value.
