### ISSUE TITLE
Bug: useReducer rendering behaviour in React 18 

### ISSUE THREAD

**Issue by sshubham681** [facebook/react#26131]
import React, { useReducer } from "react";

const initialState = 0;

const reducer = (state, action) => {
  switch (action) {
    case "INCREMENT":
      return state + 1;
    case "DECREMENT":
      return state - 1;
    case "RESET":
      return initialState;
    default:
      return state;
  }
};

const UseReducer = () => {
  const [count, dispatch] = useReducer(reducer, initialState);
  console.log('UseReducer Render')
  return (
    <div>
      <div>{count}</div>
      <button onClick={() => dispatch("INCREMENT")}>Increment</button>
      <button onClick={() => dispatch("DECREMENT")}>Decrement</button>
      <button onClick={() => dispatch("RESET")}>Reset</button>
    </div>
  );
};

export default UseReducer;

In react 17, useReducer re-render was working as same as useState does but now after updating version to 18, whenever i click reset button,  console.log('UseReducer Render'); is printed

**Comment by hhkk28** [comment]
Even with react version 17, the `console.log('UseReducer Render')` is re-rendered on every state update. Here is the same useReducer behavior in version 17 - [Repl-Link](https://replit.com/@hhkk0010/react-issue-26131-v17) and in version 18 [Repl-Link](https://replit.com/@hhkk0010/react-issue-26131-v18) I don't this is a bug.

**Comment by mikirejf** [comment]
@hhkk28 There's a difference between v17 and v18 for the "reset" button. The v17 version is working as described in the docs (https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-dispatch):

> Bailing out of a dispatch
If you return the same value from a Reducer Hook as the current state, React will bail out without rendering the children or firing effects. (React uses the [Object.is comparison algorithm](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#Description).)

> Note that React may still need to render that specific component again before bailing out. That shouldn’t be a concern because React won’t unnecessarily go “deeper” into the tree. If you’re doing expensive calculations while rendering, you can optimize them with useMemo.


Check out the following example: https://codesandbox.io/s/wispy-hooks-0vytuh?file=%2Fsrc%2FApp.js
React should bail out from continuously re-rendering the component (one additional render is expected).

**Comment by hhkk28** [comment]
I see, now i understand the issue. According to the PR - [#22445](https://github.com/facebook/react/pull/22445) I think this behavior is removed for useReducer.

**Comment by tomdevisser** [comment]
Does that mean this issue can be closed @mikirejf ?

**Comment by mikirejf** [comment]
@tomdevisser 

Can be closed 👍

**Comment by tomdevisser** [comment]
@sshubham681 

> @tomdevisser
> 
> Can be closed 👍
