### ISSUE TITLE
Considering use mobx?

### ISSUE THREAD

**Issue by zdu-strong** [facebook/react#26132]
I really like the way of writing hooks in react, but it also brings some disadvantages due to closures.

For example, the value of state cannot be used synchronously after setState.

I added a package of [mobx-react-use-autorun](https://github.com/zdu-strong/mobx-react-use-autorun#readme) that provides easy usage to circumvent the shortcomings of hooks.

**Comment by gaearon** [comment]
We use this tracker to track bugs in React. This doesn't appear to be a bug so I'll close.
