### ISSUE TITLE
Unable to establish connection with the sandpack bundler.[DevTools Bug]: 

### ISSUE THREAD

**Issue by Yi-19** [facebook/react#26149]
### Website or app

https://beta.reactjs.org/learn/sharing-state-between-components

### Repro steps

https://beta.reactjs.org/learn/sharing-state-between-components
Unable to establish connection with the sandpack bundler.

### How often does this bug happen?

Every time

**Comment by gaearon** [comment]
This sounds like an intermittent error due to losing network.

**Comment by ismailfarukkaya** [comment]
This issue is reoccurring as of June 5th. I thought it was related to me being on the phone, it is the same error in the desktop as well.

**Comment by vaef** [comment]
Same error in June 25th on react.nodejs.cn, when will repair?

**Comment by fuxing2024** [comment]
同样的问题，公司的电脑可以，个人电脑和手机都不行
