### ISSUE TITLE
Bug: DEVTools not loading at all

### ISSUE THREAD

**Issue by AbdallahAli2** [facebook/react#26167]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by AbdallahAli2** [comment]
dss

**Comment by geeksville** [comment]
dude - you need to describe things a bit more ;-)

**Comment by AbdallahAli2** [comment]
yo ik but its impossible to explain

**Comment by AbdallahAli2** [comment]
anyways it works now
