### ISSUE TITLE
Bug: onSelect event stops firing if mouse interaction ends over IFRAME

### ISSUE THREAD

**Issue by hejtmii** [facebook/react#26165]
`onSelect` event stops firing if mouse interaction ends over IFRAME or outside the window

The problem seems to be in `SelectEventPlugin` where `mouseup` doesn't fire and effectively doesn't reset the `mouseDown` flag.

https://github.com/facebook/react/blob/0b4f443020af386f2b48c47c074cb504ed672dc8/packages/react-dom-bindings/src/events/plugins/SelectEventPlugin.js#L186

Note: We saw a similar problem with not resetting `activeElement` variable because `focusout` event wasn't fired in specific case (when DOM selection is updated programatically), but I will file a separate issue once I have some more time to prepare minimum repro. The scenario is more edge case-ish, and harder to reproduce.

React version: 18.2.0

## Steps To Reproduce

1. Have a `contenteditable` DIV with `onSelect` attached, when typing text the `onSelect` event fires with every character written
2. Have `IFRAME` on the same page
3. Make text selection with a mouse, starting in `contenteditable`, releasing mouse button over the `IFRAME` or outside the window
4. Make no further clicks!
5. When you type some text now, `onSelect` is no longer firing (FAIL)
6. When you click to the `contenteditable` and type again, `onSelect` is firing again

Link to code example:

https://codesandbox.io/s/heuristic-blackwell-244tvi?file=/src/App.js

## The current behavior

`onSelect` is not firing after releasing mouse over `IFRAME`

`mouseDown` flag is not reset in `SelectEventPlugin` because it doesn't get the `mouseup` event

## The expected behavior

`mouseDown` flag is properly reset in `SelectEventPlugin`

`onSelect` keeps firing

Not sure about this, but consider

## Workaround

As a workaround, we now use a component like this in our app to globally apply `pointer-events: none` to all `IFRAME`s when left mouse button is down, which lets the `mouseup` event fire in the original window so that `SelectEventPlugin` receives it correctly.

```
export const DisableIframeInteractionOnMouseDown: React.FC = () => {
  const [isLeftButtonDown, setIsLeftButtonDown] = useState(false);
  const updateLeftButtonDown = (e: MouseEvent) => {
    // eslint-disable-next-line no-bitwise
    setIsLeftButtonDown(!!(e.buttons & 1));
  };

  useEventListener('mousedown', updateLeftButtonDown, self, true);
  useEventListener('mouseup', updateLeftButtonDown, self, true);

  return (
    <style dangerouslySetInnerHTML={{ __html: isLeftButtonDown ? 'iframe { pointer-events: none }' : '' }} />
  );
};
```

**Comment by szhsin** [comment]
This issue is still affecting the code that relies on the `onSelect` event.
