### ISSUE TITLE
Bug: input type=date clears on Firefox when invalid date is typed

### ISSUE THREAD

**Issue by vasa-chi** [facebook/react#26175]
If you input incorrect value in date input on Firefox, the whole input clears. I've prepared a sandbox: https://codesandbox.io/s/cold-dawn-ksmgb4 . If you input `0` into any part (day, month, year) of the field, it goes to empty state.

React version: 18.2.0
Firefox: 110.0 macOS

## Steps To Reproduce

1. Fill date input with correct value
2. Enter `0` into it
3. The whole field clears

Link to code example: https://codesandbox.io/s/cold-dawn-ksmgb4

## The current behavior

The field clears

## The expected behavior

The field should behave the same as uncontrolled HTML input behaves (specifically, Firefox fills the date part with zeroes).

**Comment by kalp2525** [comment]
This is by-default feature of input type=date, when your type=date so it's validate first and then display. So your input is `0 ` then validator check the given value is true or if false then it will print perfect date either it will print simple `dd-mm-yyyy` .

**Comment by vasa-chi** [comment]
It isn't by default, and date inputs don't do that. You can play with it on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) and see for yourself. 

This is how Firefox handles `0` in month: 
<img width="159" alt="изображение" src="https://user-images.githubusercontent.com/180167/220594675-87f18efe-dfd9-421b-b750-41d121fb6a09.png">

**Comment by kalp2525** [comment]
This [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) given by you which was working perfect into my Firefox browser. I don't know why this not working in your Firefox browser. Please see the version of your browser and update it.

**Comment by vasa-chi** [comment]
@kalp2525 What do you get, when you input `0` in month part of the input?

**Comment by kalp2525** [comment]
![image](https://user-images.githubusercontent.com/122508708/220599565-be7338f3-239e-4397-accc-7d548eeb75e4.png)
I getting this when my input 0 in month

**Comment by vasa-chi** [comment]
I've checked FF 110.0 on macOS and Windows. Both give me this:
<img width="159" alt="изображение" src="https://user-images.githubusercontent.com/180167/220594675-87f18efe-dfd9-421b-b750-41d121fb6a09.png">

Maybe this behaviour is locale-related? I'm on `ru_RU`

**Comment by kalp2525** [comment]
I have FF 110.0 same like you so you check again and solve this issue.

**Comment by jbonzohln** [comment]
This is happening for me as well. Here is a code sample https://github.com/jbonzohln/react-date-test
I'm using Firefox 123 on macos 14.3.

**Comment by jtguignard** [comment]
Hi,

you can try this way, using defaultValue

https://codesandbox.io/p/sandbox/competent-morning-jmwvr2?file=%2FApp.js%3A6%2C41

**Comment by jbonzohln** [comment]
That works only if the date input is bound to a single value like you have there, but if it's bound to a field within an object the issue is there. See https://codesandbox.io/p/sandbox/ecstatic-jerry-78z6dw
