### ISSUE TITLE
Bug: Big text is breaking right side of div

### ISSUE THREAD

**Issue by luis-kaufmann-silva** [facebook/react#26179]
When rendering a huge text inside a div, this text start to break the div even if it has styles to configure the word-wrap, word-break and display. The same behavior isn't observed when using pure HTML markup.

React version: 18.2.0
Chrome: Version 109.0.5414.119 (Official Build) (x86_64) macOS

## Steps To Reproduce

1. Create a variable with at least 10.000 chars
2.Scroll to see it breaking the div at right

Link to code example: https://jsfiddle.net/luis_kaufmann_silva/xd0mtznL/1/

## The current behavior
The text break right side of div.

## The expected behavior
All text contained inside div.

![Screenshot 2023-02-16 at 14 21 43](https://user-images.githubusercontent.com/1151616/219441610-3cf32739-9bc1-4f52-acd7-a51ac2477b9a.png)

**Comment by AkshayBhimani** [comment]
Interesting Issue. Able to reproduce in Chromium-based Brave Browser but surprisingly not able to reproduce in Firefox.

**Comment by ShubhCSDeveloper** [comment]
You can find solution on https://freelightupcamp.com/index.php/2023/02/19/text-is-breaking/.
![Screen](https://user-images.githubusercontent.com/47238489/219964695-7c5a8b11-84f6-4cb1-9d24-a26b05bf7f80.png)

**Comment by luis-kaufmann-silva** [comment]
@ShubhCSDeveloper Your text is too short, can you try with 100.000 or more chars? Anyways, I've tried use `text-align: justify` and even being not my goal (I don't wanna justify, I wanna "word break" correctly) it do not works:
https://jsfiddle.net/3sz8b1of/
![Screenshot 2023-02-19 at 17 32 06](https://user-images.githubusercontent.com/1151616/219973664-93379335-e8f8-43f8-a12d-4f3c2f12b796.png)
My temporary solution to the problem was just break the pute string in chunks, like this:
```
export const chunkString = (str) => {
  if (str) {
    return str.match(/.{1,10000}/g);
  }
  return str;
};
```

And then use this `chunkString` method to split my text. Visually has no difference and force the word break to works correctly.

**Comment by Rizwan-malek** [comment]
Hello,
        I hope you're doing well, actually, this issue is not from the react source. This occurs in some invalid CSS property. You can add text-align: justify on DIV.
Thanks :)

**Comment by luis-kaufmann-silva** [comment]
@Rizwan-malek you are wrong, I tried that:
https://user-images.githubusercontent.com/1151616/219973664-93379335-e8f8-43f8-a12d-4f3c2f12b796.png
And still not working. Can you provide me an example?

Thanks in advance.

**Comment by Rupuciite** [comment]
I'm having the same issue please advice!

**Comment by luis-kaufmann-silva** [comment]
@Rupuciite if you are in the rush, this hotfix worked fine to me (but I know is miles away the ideal solution):
```
export const chunkString = (str) => {
  if (str) {
    return str.match(/.{1,10000}/g);
  }
  return str;
};

/// then on your render:
<YourComponent>
  {chunkString(yourBigString)}
</YourComponent>
```

**Comment by Rizwan-malek** [comment]
@luis-kaufmann-silva Hello,
I found the solution for the same. 
Let me share.

You need to add this style to your code

**style={{ outline: 'solid 1px red', width: 600, wordWrap: 'break-word', display: 'block',whiteSpace: "wrap"}}**

As I said this issue basically not from ReactJS. Just some invalid CSS.

Thank you :)

**Comment by luis-kaufmann-silva** [comment]
@Rizwan-malek Okay, can you demonstrate that?

Because I applied your exact style here:
https://jsfiddle.net/luis_kaufmann_silva/2fb8qazL/2/

And still buggy:
![Screenshot 2023-02-22 at 08 59 11](https://user-images.githubusercontent.com/1151616/220614066-aaa3657e-0241-4056-b0b2-7c9c6684c03b.png)

P.S.: I know that `wordWrap: 'break-word'` + `whiteSpace: 'wrap'` should works, but that do not happens with really long texts.

**Comment by ShubhCSDeveloper** [comment]
> @ShubhCSDeveloper Your text is too short, can you try with 100.000 or more chars? Anyways, I've tried use `text-align: justify` and even being not my goal (I don't wanna justify, I wanna "word break" correctly) it do not works: https://jsfiddle.net/3sz8b1of/ ![Screenshot 2023-02-19 at 17 32 06](https://user-images.githubusercontent.com/1151616/219973664-93379335-e8f8-43f8-a12d-4f3c2f12b796.png) My temporary solution to the problem was just break the pute string in chunks, like this:
> 
> ```
> export const chunkString = (str) => {
>   if (str) {
>     return str.match(/.{1,10000}/g);
>   }
>   return str;
> };
> ```
> 
> And then use this `chunkString` method to split my text. Visually has no difference and force the word break to works correctly.

For long text basic style is not handling correctly so we need to give text in limit at a time. Your logic is good but it could break word also if there is at 10000 index. You can check https://jsfiddle.net/b8p51vk2/48/  link if it helps. Thanks

**Comment by luis-kaufmann-silva** [comment]
> > @ShubhCSDeveloper Your text is too short, can you try with 100.000 or more chars? Anyways, I've tried use `text-align: justify` and even being not my goal (I don't wanna justify, I wanna "word break" correctly) it do not works: https://jsfiddle.net/3sz8b1of/ ![Screenshot 2023-02-19 at 17 32 06](https://user-images.githubusercontent.com/1151616/219973664-93379335-e8f8-43f8-a12d-4f3c2f12b796.png) My temporary solution to the problem was just break the pute string in chunks, like this:
> > ```
> > export const chunkString = (str) => {
> >   if (str) {
> >     return str.match(/.{1,10000}/g);
> >   }
> >   return str;
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then use this `chunkString` method to split my text. Visually has no difference and force the word break to works correctly.
> 
> For long text basic style is not handling correctly so we need to give text in limit at a time. Your logic is good but it could break word also if there is at 10000 index. You can check https://jsfiddle.net/b8p51vk2/48/ link if it helps. Thanks

Hello @ShubhCSDeveloper , so your example is invalid because the error happens on React, so when you use this:
![Screenshot 2023-02-23 at 09 59 32](https://user-images.githubusercontent.com/1151616/220913275-d830fd53-4c58-4603-a2f0-b7b4f07e2534.png)
You are not using React, note that I didn't said that Javascript is failing but the React render is failing. My solution its a small hotfix, it works to my case but I do not guarantee that will works fine in another context.

Just to keep clear, I know CSS properties to break line and contain the text inside div, but I can always be wrong. If you find a way to that work using a really long text being rendered using React I would love see it.

Thanks in Advance

**Comment by gaearon** [comment]
Here is the same problem when using vanilla DOM with `textContent`. https://jsfiddle.net/knx1p2jw/3/

Not sure if this has something to do with the string itself (does it have any special chars in it?) but it's not a React problem.

**Comment by luis-kaufmann-silva** [comment]
Since it happens only on Chrome, I also reported it to Chrome:

https://bugs.chromium.org/p/chromium/issues/detail?id=1418967
