### ISSUE TITLE
Bug:  React dev tools inspect element of hover does not work on shadow elements

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#26200]
Using react while making a shadow DOM and then using react devtools inspect element feature does not work as expected video and codesandbox below

**sandboxLink**
https://stackblitz.com/edit/react-zqp67t?file=src/App.js

**while attaching shadowroot**

https://user-images.githubusercontent.com/72331432/219961254-65c9e84c-9774-441f-9eec-e9ef58f1382d.mp4

**without attaching  root**

https://user-images.githubusercontent.com/72331432/219961266-b276063e-e0f4-4f30-b614-0af3876a9916.mp4

**Comment by Biki-das** [comment]
@lunaruan  could you guide me towards how to build the dev tools locally and test it with the changes after making? i have some idea to work on this problem

cc  @eps1lon

**Comment by mondaychen** [comment]
To begin with, please follow https://github.com/facebook/react/blob/main/packages/react-devtools/CONTRIBUTING.md
Let me know if you have questions

**Comment by Biki-das** [comment]
@mondaychen still kinda confused say i want to test the devtools changes locally within a react app how should i do so?

**Comment by mondaychen** [comment]
@Biki-das if it's not extension specific, you can start the inline devtools server in react-devtools-inline, then start the shell in react-devtools-shell. Then you can test your changes with the shell UI. The guide: 
https://github.com/facebook/react/blob/main/packages/react-devtools/CONTRIBUTING.md#option-1-fastest-using-the-test-shell

**Comment by Biki-das** [comment]
@mondaychen it's extension specific

**Comment by mondaychen** [comment]
Then you go to react-devtools-extensions and run `yarn:build:chrome` to build it.

Can you read through the guide I sent you fist? Everything I'm talking about now is on it.

**Comment by Biki-das** [comment]
@mondaychen getting this errors while trying to run the extension anything i might be doing wrong?
![bikid476@DESKTOP-16A0D3T_ ~_react-1_packages_react-devtools-shell 3_26_2023 8_26_17 PM](https://user-images.githubusercontent.com/72331432/227784281-f607bde5-8ab4-499b-954a-a96de5463931.png)
