### ISSUE TITLE
"Unable to find element" error on <option> elements

### ISSUE THREAD

**Issue by mmavko** [facebook/react#2620]
If the contents of the `<option>` element is constructed in special way, it breaks React on component update with "Unable to find element" error. Here's an example of `render` method body:

        var v1 = String(Math.random());
        var v2 = String(Math.random());
        return <select><option value={v2}>{v1} ({v2})</option></select>;

Here's working jsfiddle (with React 0.12.0): http://jsfiddle.net/rp3fz0nf/1/

Adding `key={v2}` to option props fixes the issue.

**Comment by spicyj** [comment]
This can be fixed by using ReactChildren.forEach in ReactDOMOption to flatten the children before passing it to the raw HTML component. Strings and numbers get concatted together; other elements should be skipped and log a warning for invalid children.
