### ISSUE TITLE
onMouseOver is not triggered for a component rendered under the mouse until the mouse moves.

### ISSUE THREAD

**Issue by z5h** [facebook/react#2621]
If a component is rendered that registers for onMouseOver events, and it is rendered under the mouse, it should have it's onMouseOver callback invoked.

**Comment by santiagopuentep** [comment]
Also, mouseEnter event never triggers.

**Comment by bvaughn** [comment]
I don't think React should implement the behavior described in this issue. It's not React-specific. Certain browsers (eg Chrome, Safari) don't dispatch a _mouseover_ or _mouseenter_ event in the case you've described (even using vanilla JS) until the mouse moves again. I don't think React should try to iron over this behavior.

I'm going to close this issue for now. We can always reopen it if other's feel strongly. 😄

**Comment by getusha** [comment]
Experiencing the same issue.
it works on chrome, firefox 
on safari onMouseOver callback is not invoked until the mouse moves.
