### ISSUE TITLE
When we apply high contrast black/white mode, names of the buttons present in the grid cell under "base score metrics" in the grid "CSVV scores" are adopting hyperlink color.Bug: 

### ISSUE THREAD

**Issue by msftedad** [facebook/react#26214]
**Description:**
When we apply high contrast black/white mode, names of the buttons present in the grid cell under "base score metrics" in the grid "CSVV scores" are adopting hyperlink color.

**Test Environment:**
**Application name :** MSRC web
**URL:** Security Update Guide: [https://msrc-ppe.microsoft.com/update-guide](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fmsrc-ppe.microsoft.com%2fupdate-guide&data=04%7c01%7cv-insett%40microsoft.com%7c93a879e34dbd48842e8808d9e69def56%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637794388307375425%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=KuwE1cRV11J%2fynrsNiDLLhGV%2f1fmRSme11lgguouqzo%3D&reserved=0) 
**OS :** windows10 , version 21H2(OS Build 19044,1466)
**Browser :** Version 98.0.1108.43 (Official build) (64-bit)

**Steps To Reproduce:**
To apply high contrast follow the below steps:
1. Open settings, tab till Ease of access and press enter.
2. Tab till High contrast press enter.
3. From the drop down select a proper theme by pressing enter. Use all the 2 themes i.e. 'black' , 'white' one by one.
4. Tab till apply button and press enter.
5. Connect to VPN.

**Repro steps:**
1. Launch the application URL: https://msrc-ppe.microsoft.com/update-guide  -must be on corporate VPN and login with Credentials.
2. Tab to “Vulnerabilities” Tab item and hit enter.
3. Now Tab to “Vulnerabilities Data Grid” and select CVV number present in Data Grid.
4. Apply high contrast black/white mode in the settings.
5. Observe the data present under "base score metrics" in the CSVV scores grid, to check whether that data adopt the respective color in high contrast or not.

**The current behavior:**
When we apply  high contrast black/white mode, names of the buttons present in the grid cell under "base score metrics" in the grid "CSVV scores"  adopting hyperlink color.

**The expected behavior:**
Names of the buttons present in the grid cell under "base score metrics" in the grid "CSVV scores"  should not adopt the hyperlink color, they should adopt the respective button color.

https://user-images.githubusercontent.com/93735775/220353085-8ad2aae3-0711-4a28-9bc6-ebe64e4467a5.mp4

**Comment by gaearon** [comment]
This is a bug tracker for React, but this does not look like a bug report related to React.

**Comment by msftedad** [comment]
Hi Gaearon,

We will check with engineering team and update. Thanks

**Comment by msftedad** [comment]
Hi Team.

please find the below link where similar type of issue we observed. 

https://codepen.io/curtisj44/pen/bGadKJV

**Comment by msftedad** [comment]
Hi @gaearon, Any update on this issue?

**Comment by pwbriggs** [comment]
Hey there @msftedad! 👋

As per @gaearon's comment, this issue tracker is for bugs in React.js. Can you please explain how this issue is related to the React library itself (not, for example, a UI component library)?

Thanks! ❤️
