### ISSUE TITLE
What is the preferred style of typing React components

### ISSUE THREAD

**Issue by alexander-vashchuk** [facebook/react#26222]
There are two ways in TypeScript to type components, I'm aware of:

First
```ts
interface Props {
  name: string;
}

const App = ({ name }: Props) => <div>{name}</div>;
```

Second
```ts
const App: FunctionComponent<{
  name: string;
}> = ({ name }) => <div>{name}</div>;
```

Is there any difference between them or any I should prefer?

**Comment by eps1lon** [comment]
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components should give you a good overview over different patterns and their pros/cons. If anything is unclear, you can [raise an issue against typescript-cheatsheets/react](https://github.com/typescript-cheatsheets/react/issues/new/choose)
