### ISSUE TITLE
why not?[DevTools Bug]: 

### ISSUE THREAD

**Issue by fengjiewen1997** [facebook/react#26221]
### Website or app

Website

### Repro steps

Loading React Element Tree...

If this seems stuck, please follow the [troubleshooting instructions](https://github.com/facebook/react/tree/main/packages/react-devtools#the-issue-with-chrome-v101-and-earlier-versions).

### How often does this bug happen?

Every time

### DevTools package (automated)

Loading React Element Tree...  If this seems stuck, please follow the troubleshooting instructions.

### DevTools version (automated)

Loading React Element Tree...  If this seems stuck, please follow the troubleshooting instructions.

### Error message (automated)

Loading React Element Tree...  If this seems stuck, please follow the troubleshooting instructions.

### Error call stack (automated)

```text
Loading React Element Tree...

If this seems stuck, please follow the troubleshooting instructions.
```

### Error component stack (automated)

```text
Loading React Element Tree...

If this seems stuck, please follow the troubleshooting instructions.
```

### GitHub query string (automated)

```text
Loading React Element Tree...

If this seems stuck, please follow the troubleshooting instructions.
```

**Comment by Likogann** [comment]
Are you using chrome? If so, what version of chrome are you running?

**Comment by fengjiewen1997** [comment]
> Are you using chrome? If so, what version of chrome are you running?

win10,Chrome------92.0.4515.159

**Comment by fengjiewen1997** [comment]
> Are you using chrome? If so, what version of chrome are you running?

Need to update the new version?but my computer can not update the chrome..........only remove and then install

**Comment by Likogann** [comment]
The issue states 7 times to update chrome to fix the issue. You must update chrome.

**Comment by mondaychen** [comment]
Please upgrade to latest Chrome. Thanks!
