### ISSUE TITLE
Bug: set state is not working inside an event listener on mobile browsers (Android Chrome / iOS Safari)

### ISSUE THREAD

**Issue by rashinp** [facebook/react#26227]
<img width="848" alt="Screenshot 2023-02-24 at 10 40 02 AM" src="https://user-images.githubusercontent.com/14529528/221106327-35b3f872-cab4-4d88-a640-16ce86cbe006.png">
<img width="651" alt="Screenshot 2023-02-24 at 11 48 26 AM" src="https://user-images.githubusercontent.com/14529528/221106573-27a66fda-17d8-4136-a05a-b62dee25b833.png">

setState inside an event listener is not working for Mobile browsers when using React 18.
If I downgrade to React 16 it works fine, also it works fine on desktop browsers in React 18

React version: 18.20

**Comment by rashinp** [comment]
I found that the feature of automatic batched updates for set state inside callback in React 18 is causing set state to not work on mobile browser. Either we have to wrap the set state with `flushsync`, or we have to change `createRoot` to `ReactDOM.render`. Since we have a lot of places and dependencies were set state is done inside callback we chose to go with the later.

**Comment by EvenTopland** [comment]
Bump
