### ISSUE TITLE
Bug: Duplicate HTML elements being rendered

### ISSUE THREAD

**Issue by bugzpodder** [facebook/react#26240]
React version: 17.0.2 
Next: 12.3.4

React Production build

## Steps To Reproduce

My react code is occasionally producing two duplicate html elements in DOM.
The second element is a ghost in the sense that it never goes away, and all js events does not trigger (except for changing the textbox value).

<img width="484" alt="Screenshot 2023-02-24 at 6 01 35 PM" src="https://user-images.githubusercontent.com/14841421/221330488-d84dd908-e210-4733-8a3f-f37d3b20c46d.png">
<img width="668" alt="Screenshot 2023-02-24 at 6 02 46 PM" src="https://user-images.githubusercontent.com/14841421/221330490-562ae5f3-4046-489f-9f3d-cde338e759e9.png">

This is the code:
```
import { sortBy } from "lodash";
import { styled } from "styled-components";
import { Row, Col } from "antd";
import FieldInput from "./FieldInput";

export default function FormInput({ a }) {
return (
    <FormContainer className={a.length > 1 ? "group" : undefined}>
      <Row gutter={[16, 0]}>
        {sortBy(a, [
          (a) => {
            return a.position;
          },
          (a) => {
            return a.name;
          },
        ]).map((elem) => {
          return (
            <Col span={12} key={elem.uuid}>
               <FieldInput />
            </Col>
          );
        })}
      </Row>
    </FormContainer>
  );
}

const FormContainer = styled("div")`
  margin: 16px 0px;  
  &.group {
    padding: 16px;
    border: 1px solid black;
    border-radius: 4px;
  }
`;

```

I've put debugger breakpoints to make sure I don't have more than one element in the array.  Also, there would be visual indication that a border is being drawn when we have more than one element but this is not the case here.

Link to code example:

## The current behavior
Curious if anyone else saw this.  did a google search and found nothing.

**Comment by davidmccabe** [comment]
It looks like you meant to include a link to the repro, but may have left it out by accident.

**Comment by bugzpodder** [comment]
this is a private repo so I cannot provide it.  Even providing it won't help since its a very large one and I cannot repo this consistently.  But it happened enough times that more than one user was able to see this behavior including myself and I was able to debug it in this special state in production with sourcemaps on and Chrome devtools debugger.

**Comment by hhkk28** [comment]
Hi @bugzpodder I have come across this ghost child issue myself. This happens whenever we render a list without key props or non-unique keys passed to multiple elements, Can you please check if all key prop you are passing to the elements is unique to each element in the list?
