### ISSUE TITLE
Bug: React 18 renders different pages compared to React 17

### ISSUE THREAD

**Issue by roman-zabolotskyi-axon** [facebook/react#26253]
We're trying to upgrade from `React 17.0.2` to `React 18.2.0`. We don't use any `StrictMode` or SSR. Package upgrade for `react/react-dom` caused the app to render at different times and UI than it used to be before. Simply speaking, we had the following pattern:

`refresh the page -> render loading spinner -> receive the data -> render the component with data`.

Each step roughly represented a separate render. However it's different now:

`refresh the page -> render data (undefined/NaN are visible) -> render loading spinner -> receive the data -> render the component with data`.

Here are 2 sandboxes with identical code but different `React` versions that don't reproduce the exact difference we have in the application, but clearly show the rendering pattern has changed.

[React 17 sandbox](https://codesandbox.io/s/react-17-renders-ft5dzo) has the following rendering cycle:

![Screenshot from 2023-02-24 16-09-06](https://user-images.githubusercontent.com/68898159/221220285-25ce7608-c42d-4ffc-90f3-749eae4c3831.png)

[React 18 sandbox](https://codesandbox.io/s/react-18-renders-d8j0bm) has the following rendering cycle:

![Screenshot from 2023-02-24 16-10-29](https://user-images.githubusercontent.com/68898159/221220690-add872f0-0be0-48ab-bd4d-3f5ca9adf6bc.png)

The issue with `React 18` is it prematurely renders the default state before all data are settled:

![Screenshot from 2023-02-24 16-17-15](https://user-images.githubusercontent.com/68898159/221221054-40a54fc3-d7ca-4e98-81e5-57f303c0d702.png)

Here's a [loom](https://www.loom.com/share/65214224af124f97886288461249f975) of the render in action.

As I mentioned, sandboxes don't 100% match the rendering problem we have in the application. In the real code we have this:
* In `React 17` `TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT` is **never rendered**, `TEXT WITH TOOLTIP` is shown right after the loading spinner is gone.
* In `React 18` `TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT` is **always rendered**, `TEXT WITH TOOLTIP` is shown later.

Questions:

1. Why does this happen?
2. Is it possible to keep the render logic in `React 18` the same as `React 17` or the application code has to be updated?

**Comment by zemadz** [comment]
React 18 sandbox link is accidentally the same as React 17 sandbox.
