### ISSUE TITLE
Bug:  Have problems with Provider react-redux

### ISSUE THREAD

**Issue by keryaBoks** [facebook/react#26264]
<img width="855" alt="Screenshot 2023-02-28 at 22 46 40" src="https://user-images.githubusercontent.com/94535983/221962428-c1772707-8958-47c6-a11c-5c105ee22955.png">

have such issue using redux-toolkit, the only one solution is use old version of types/react
my current version is     "@types/react": "^17.0.39",

**Comment by eps1lon** [comment]
You probably have multiple versions of `@types/react` installed. Make sure you only have the version install matching your version of React.

https://github.com/facebook/react/issues/24304 contains a couple of workarounds as well.

With https://github.com/microsoft/DefinitelyTyped-tools/issues/433, we wouldn't have this issue.
