### ISSUE TITLE
Silent exception from error in componentWillReceiveProps

### ISSUE THREAD

**Issue by zhoul-HS** [facebook/react#2626]
So i had a function call to undefined in componentWillReceiveProps:
``` javascript
componentWillReceiveProps: function(nextProps) {
        var ends = Component.getTimeEnds(nextProps.ends);    // static method
        var diff = ends.clone().subtract(this.state.ends) // ends.clone is undefined;
	this.setState({ 
		diff: diff
 	})
 }
```
well never mind what it does but since i call undefined it throws, which is caught in ReactMultiChild.updateChildren and not re-thrown for some reason i can't find and can't reproduce in a fiddle.
Anyways it took me a while to realize it was the culprit, anyone knows why in heaven's name doesn't it throw?

**Comment by spicyj** [comment]
Closing, but if you have a repro case please post it.
