### ISSUE TITLE
Bug: Suspense component loses childs hook context on suspension

### ISSUE THREAD

**Issue by 42shadow42** [facebook/react#26279]
React version: 18.2.0

## Steps To Reproduce

1. Create a component that store some state
2. Create a promise dependent on that state
3. Throw the promise until it is resolved
4. Wrap the component in suspense
5. Wait for the promise to resolve
6. The component never renders

Link to code example:

[Suspended promise](https://codesandbox.io/s/misty-leaf-rfk2t7?file=/src/App.js)

## The current behavior
Suspended components reset state

## The expected behavior
Suspended components retain hook context on promise resolution

**Comment by acdlite** [comment]
It will work with `use` once that is released. Example: https://codesandbox.io/s/elastic-thompson-yejumo

**Comment by 42shadow42** [comment]
Confirmed this works for my use case, thanks for the quick response, I'll be looking forward to it's release.

**Comment by 42shadow42** [comment]
Confirmed it also allows using multiple promises in the same component which is a limitation I was having to work around. This is awesome!

**Comment by gaearon** [comment]
@acdlite curious — what allowed us to remove this limitation specifically for `use`?
