### ISSUE TITLE
Bug: Nested roots are not unmounted when calling `root.unmount()`

### ISSUE THREAD

**Issue by krzempekk** [facebook/react#26281]
When using multiple nested React roots, un-mounting the top-level one does not result in un-mounting lower-level ones. Any `useEffect` cleanup functions of components in lower-level roots are not called.

React version: 18.2.0 (also reproduced in 17.0.2)

## Steps To Reproduce

*see code examples for details*

1. Create React root using `createRoot`.
2. Inside this root create another root.
3. In the nested root add component with `useEffect` hook which has cleanup function that prints something to a console.
4. Unmount top-level root.
5. Nothing is printed to a console - nested root was not properly unmounted.

Link to code example:

Reproduction in React 18.2.0: https://codesandbox.io/s/react-17-nested-micro-apps-l8mdp8?file=/src/index.js
Reproduction in React 17.0.2 (using old `ReactDOM.render` and `ReactDOM.unmountComponentAtNode` API): https://codesandbox.io/s/react-17-nested-micro-apps-l8mdp8?file=/src/index.js

## The current behavior

Nested roots are not properly unmounted.

## The expected behavior

Nested roots should be properly unmounted.

**Comment by krzempekk** [comment]
Example was invalid, this is not actually an issue

**Comment by michaelfaith** [comment]
Do you have an example of an app using multiple nested `createRoot`?  The links you provided in the OP are both using React 17.  Investigating an issue in my own codebase, and curious how you approached it.
