### ISSUE TITLE
Bug: Misbehaving while deployment

### ISSUE THREAD

**Issue by starboyvarun** [facebook/react#26289]
Hi

**Input:**
```
plum@plum-V530S-07ICB:~/dep$ serve -s build
```
**Output:**

file:///usr/local/lib/node_modules/serve/build/main.js:169
      const ipAddress = request.socket.remoteAddress?.replace("::ffff:", "") ?? "unknown";
                                                     ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

The main.js js was created by

```
npm run build

```

I am trying to deploy myreact  applcation on my local Server on Ubuntu.
Can you tell me what i should do to fix this issue.
Or does this happen on all ubuntu server while deployment.

Thanks in advance

**Comment by vkurchatkin** [comment]
This has nothing to do with React. That said, you should update your Node.js

**Comment by starboyvarun** [comment]
@vkurchatkin  I have updated the node.js but still giving the same error. When I use ``` npm build ``` its something to do with that.

**Comment by raeevy** [comment]
This is issue with the version of node

You can update using the command below on ubuntu:
sudo npm install -g n
sudo  n stable
node -v // this should show the latest version

Now rum your command 
sudo npm serve -s build --host=X.X.X.X --disable-host-check
