### ISSUE TITLE
Bug: Lag when updating coordinates of div on mousemove

### ISSUE THREAD

**Issue by blnvdanil** [facebook/react#26284]
There is a noticable delay when updating `div`'s coordinates on mousemove with react 18 compating to react 17

There are a couple of videos:
React 17 (without lag):

https://user-images.githubusercontent.com/61459199/222541475-e7a98d0c-1c47-4e0f-a35b-ff0532e93705.mp4

React 18 (with lag):

https://user-images.githubusercontent.com/61459199/222541530-89dc5d54-3d6a-45f0-8d8c-c52ccc0fd258.mp4

React version: 18.2.0

## Steps To Reproduce

1. Have two `div` elements with `position: absolute`
2. On mousemove update coordinates of the first `div` using 
```javascript
 ref1.current.style.top = e.clientY + "px";
 ```
3. On mousemove update coordinates of the second `div` using
```javascript
const [{ x, y }, setCoords] = useState({ x: 0, y: 0 });
```
and
```javascript
<div
  style={{
    width: "100px",
    height: "100px",
    position: "absolute",
    top: `${y}px`,
    left: `${x}px`,
    backgroundColor: "red"
  }}
></div>
```

Link to code example: [React 18](https://codesandbox.io/s/gifted-germain-mq7tht) and [React 17](https://codesandbox.io/s/funny-tharp-c01h1n)

## The current behavior
Updates of `div`'s coordinates are delayed

## The expected behavior
Updates of `div`'s coordinates should not be delayed

**Comment by Circkoooooo** [comment]
It seems to be because of the new architecture of `React18`? I'm not sure, but there is a workaround.

Your code may be not the best logic to render two components with `useRef` and `useState` synchronously.
`move event` will immediately trigger the ref update to change the style of DOM, but `setState` not. 

1. listen the `moveEvent`
2. trigger `setState`
3. update `ref` by `setState`

```
 const [{ x, y }, setCoords] = useState({ x: 0, y: 0 });
  const ref1 = useRef<HTMLDivElement>(null);

  useEffect(() => {
    document.addEventListener("mousemove", (e) => {
      setCoords({ x: e.clientX, y: e.clientY });
    });
  }, []);

  useEffect(() => {
    if (ref1.current) {
      ref1.current.style.top = y + "px";
      ref1.current.style.left = x + "px";
    }
  }, [x, y]);
```

**Comment by blnvdanil** [comment]
@Circkoooooo Thanks for your answer!

I am not exactly sure, but in theory your solution soonds like "make blue square slower, so it wil be synchonous to red aquare", but my initial problem (in my project) was that I was using this technic to show some floating element over canvas, the problem begins when you start dragging the canvas and updating floating coordinates, canvas drags without lag, but the floating element has noticable delay.

And this two examples was just to show that there was no difference in updating coordinates with react's `useState` and using dom element itself.

I tested yur solution, but that does work in my implementation Here is the link: [suggested workaround](https://codesandbox.io/s/bold-wave-l9zpqk) 
But, as I said, seems that I jus made blue quare a little bit slower, the user expierence become worse :(
