### ISSUE TITLE
Bug: Error occurs when returning empty fragment '<></>' on a page

### ISSUE THREAD

**Issue by Willienn** [facebook/react#26295]
In was working when i comment a code and see this error
Then i start to test possible ways of reproduce the bug
Notes: 
1.using <>{null}</> dont give the error
2.using <>{undefined}</> give the error

React version: 18.2.0

## Steps To Reproduce

1.import { Fragment } from "react";

export default async function Companies() {
  return ( 
<Fragment ></Fragment > {/* Or => <></>*/}
 );
}

2.Start the localHost (dev server, etc)

## The current behavior

<img width="739" alt="image" src="https://user-images.githubusercontent.com/101187684/222805443-ecd39b24-461e-404c-a2fb-b02199837278.png">

## The expected behavior

<img width="960" alt="image" src="https://user-images.githubusercontent.com/101187684/222805607-870260bb-7643-4502-89cc-24189fe952f2.png">

**Comment by eps1lon** [comment]
We have this tracked internally. But thanks for flagging. Same applies to returning undefined directly.

**Comment by krishchha** [comment]
you don't have to import the fragments , just write in below the return <> hey it will sove this </> just do it

**Comment by daphillipescode** [comment]
Is it fix?

**Comment by eps1lon** [comment]
Fixed in https://github.com/facebook/react/pull/26349
