### ISSUE TITLE
Bug: onContextMenu listener is invoked on disabled buttons in Chrome

### ISSUE THREAD

**Issue by osule** [facebook/react#26298]
## Steps To Reproduce

1. In CRA, declare the App component:
```jsx
import React from 'react';

export default function App() {
  return (
    <button
        type="button"
        onContextMenu={() => {console.log(123);}}
        disabled
    >
        Click me
    </button>
  );
}
```
2. Run the dev server and browse in Chrome

## The current behavior

Right clicking the button logs `123` in the Dev Console.

## The expected behavior

Right clicking the button should not log `123` in the Dev Console.

**Comment by egonSchiele** [comment]
Works for me; could you post a fiddle link?

**Comment by Werter12** [comment]
I can confirm the `onContextMenu` gets triggered on right click when button is `disabled`. 
Maybe its something related to these lines of code:
https://github.com/facebook/react/blob/8e2bde6f2751aa6335f3cef488c05c3ea08e074a/packages/react-dom-bindings/src/events/plugins/SimpleEventPlugin.js#L107-L113
