### ISSUE TITLE
Bug: Native dialog backdrop stylings don't work

### ISSUE THREAD

**Issue by anichols-ht** [facebook/react#26292]
I will be start by saying, it's wholly possible this is user error, cause I can't find any other reports of this issue by googling, but I cannot get backdrop stylings on native dialogs to render in React. In my work project where I noticed this, there are a lot of variables (tailwindcss, react, next, nx, etc.), but here's the short version:

In a simple html page loaded via the `file://` protocol, I can successfully style a `<dialog>` `::backdrop` using inline css, style tags, tailwindcss (loaded via cdn) classes - basically _any_ styling mechanism. It works whether the dialog is triggered by a button (`showDialog`), already open (via the `open` attribute), or added to the dom on click.

In a simple React app compiled with webpack, I _cannot_ get `::backdrop` stylings to apply in any way. I've tried raw css, tailwindcss, and styled-components. The dialog element itself works as expected, but the styles for the backdrop do not get applied. I've verified this in a previously existing home rolled project (with fewer variables than the work project where I first noticed it) as well as a brand new project using create-react-app.

React version: 18.2

## Steps To Reproduce

1. Scaffold a simple react app in whatever way you do this kind of thing. I used tailwindcss via the postcss loader, as well as importing styled-components. I'll show the styled-components version cause the setup is significantly shorter.
2. In the main page, add something like

```
import React from 'react';
import styled from 'styled-components';

const Dialog = styled.dialog`
  &::backdrop {
    background: darkorange;
  }
`  

const App = () => {
  return (
    <Dialog open>
      hello world
    </Dialog>
  );
};

export default App;
```

3. Start the server (or compile a bundle) and open the page. No darkorange. To be clear, I also set

```
html,body,#root {
  height: 100%;
  width: 100%;
}
```

so it isn't just that there's no backdrop space to color (thought I don't think you need it - I believe backdrop covers the whole viewport regardless).

Comparatively, the following works:

```
<!DOCTYPE html>
<html lang="en">
  <head>
      <style>
        dialog::backdrop {
          background: darkorange;
        }
      </style>
  </head>
  <body>
    <button id="btn">Click here</button>
    <dialog id="dialog">
      hello world
    </dialog>
    <script>
      document.querySelector('#btn').onclick = function() {
        document.querySelector('#dialog').showModal();
      }
    </script>
  </body>
</html>

```

When you click the button, you get an orange background obscuring everything else (as backdrop should).

## The current behavior
No backdrop stylings are applied.

## The expected behavior
Backdrop stylings should be applied.

Again, I'll reiterate, maybe I'm doing something very wrong, maybe other tools are causing this, I don't know. But it _seems_ to be related to React. It's pretty hard to isolate something like this down to _just_ react, since you typically need some other tooling (like webpack) just to compile React into something usable, but as far as I've been able to simplify the app, it seems specific to react.

**Comment by egonSchiele** [comment]
You're running into a hydration error. See the bottom of this page:
https://nextjs.org/docs/messages/react-hydration-error

With your example, if I put the css for `dialog` in a separate css file, it works just fine.

### index.jsx

```js
import React from "react";

const App = () => {
  const dialogRef = React.useRef(null);
  return (
    <div>
      {" "}
      <button id="btn" onClick={(e) => dialogRef.current.showModal()}>
        Click here
      </button>
      <dialog ref={dialogRef}>hello world</dialog>
    </div>
  );
};

export default App;
```

### globals.css
```css
dialog::backdrop {
  background: darkorange;
}
```

**Comment by anichols-ht** [comment]
Hmm, okay, I'm certainly wiling to pursue that, but I do get this when using _just_ client-side React as well. Unless you're telling me React does hydration even when you aren't using a SSR?

**Comment by egonSchiele** [comment]
Could you give me an example? Here's a fiddle that works https://jsfiddle.net/tbzp8o9n/4/

**Comment by anichols-ht** [comment]
Here's one that doesn't: https://jsfiddle.net/v7up2y3k/1/. You can see that `open` does cause the dialog to open, but the backdrop is not applied. My understanding in reading the dialog docs is that either programmatically opening with built in dom methods _or_ passing the open attribute (which would be a more react way of doing it) is supported.

**Comment by anichols-ht** [comment]
Okay, I stand corrected. That is the behavior of the dialog without react as well. I thought I had tried that, but I wanted to just double check, and it doesn't style the backdrop if you use `open` rather than `showModal()`. That still seems weird to me . . . I don't understand why it's different, but that does mean it isn't a React issue. I don't know whether to consider this a bug in the spec or if it functions this way on purpose for some reason that I don't understand.

Thanks for taking the time to look at this though. I appreciate it.

**Comment by egonSchiele** [comment]
You're welcome!

From the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog):

> It is recommended to use the .show() or .showModal() methods to render dialogs, rather than the open attribute. If a <dialog> is opened using the open attribute, it will be non-modal.

I think that is causing the difference in behavior.

**Comment by anichols-ht** [comment]
Interesting . . . maybe I'm alone in this, but . . . I can't imagine ever _wanting_ that behavior. Either way, I guess that does explain it.

**Comment by kevin-mitchell** [comment]
@anichols-ht sorry to bug you about a long dead issue, but did you ever do any more thinking or digging into this? I'm of the same mind as you and it took me finding this issue to realize why the `...::backdrop` wasn't rendering as expected. It feels weird to me that displaying the modal via `open` property vs calling a method would result in a different display behavior.

**Comment by anichols-ht** [comment]
@kevin-mitchell No, I just used `showModal` instead of `open`. It's a nuisance cause it changes

```
open={showModal}
```

to

```
const ref = useRef();

useEffect(() => {
  if (ref.current && showModal) {
    ref.current.showModal();
  }

  return () => {
    ref.current?.close();
  };
}, [showModal]);

<dialog ref={ref} ... />
```

but it does work (and stylings are correctly applied).
