### ISSUE TITLE
Bug: `useInsertionEffect()` doesn't fire before `useLayoutEffect()`

### ISSUE THREAD

**Issue by catamphetamine** [facebook/react#26320]
React version: `18.2`
Next.js version: `13.2.3`

## Steps To Reproduce

1. Go to the demo page (link below). It's a simple Next.js application (it [wasn't](https://gitlab.com/catamphetamine/virtual-scroller/-/issues/33) created by me, I just forked it). The code is:

```js
import { useInsertionEffect, useLayoutEffect } from "react";

export default function IndexPage(props) {
  useLayoutEffect(() => {
    console.log("@ Layout Effect");
  });

  useInsertionEffect(() => {
    console.log("@ Insertion Effect");
  });

  return null;
}
```

2. Open the web browser console.

3. See the output in the console:

```
@ Insertion Effect
@ Layout Effect
@ Layout Effect
```

Link to code example:

https://codesandbox.io/p/sandbox/virtual-scroller-infinite-scroll-forked-srptij?file=%2Fpages%2Findex.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A14%7D%5D

## The current behavior

It prints:

```
@ Insertion Effect
@ Layout Effect
@ Layout Effect
```

## The expected behavior

It should print:

```
@ Insertion Effect
@ Layout Effect
@ Insertion Effect
@ Layout Effect
```

**Comment by egonSchiele** [comment]
Hi @catamphetamine ,
You're using strict mode, and `useInsertionEffect` does not mount twice the way `useLayoutEffect` and `useEffect` do.

**Comment by catamphetamine** [comment]
@egonSchiele 

> You're using strict mode, and `useInsertionEffect` does not mount twice the way `useLayoutEffect` and `useEffect` do.

Thanks, but why doesn't it though?
Don't you consider it a bug?
They're all "effect"s, so why does their behavior differ in strict mode?
That makes no sense and `useInsertionEffect()` isn't supposed to be anything "special": 

> `useInsertionEffect` is a version of [useEffect](https://beta.reactjs.org/reference/react/useEffect) that fires before any DOM mutations.

From the official docs:
https://beta.reactjs.org/reference/react/useInsertionEffect

So I consider the current behavior a bug.

**Comment by catamphetamine** [comment]
From the docs, looks like `useInsertionEffect()` doesn't support returning an "on unmount" function like `useEffect()` does.
So the issue is deeper and it's incorrect specification of the `useInsertionEffect()` itself.
It should have supported returning an "on unmount" function when it was introduced.

Looks like there's no other way of dealing with this bug other than implementing a hacky workaround for the "strict" mode.
Something like:

```js
import { useLayoutEffect, useRef } from 'react'

// A workaround for a React bug when `useInsertionEffect()` doesn't run twice on mount
// in "strict" mode unlike `useEffect()` and `useLayoutEffect()` do.
// https://github.com/facebook/react/issues/26320
export default function useLayoutEffectDontMountTwice(handler, dependencies) {
  if (dependencies.length !== 1) {
    throw new Error('`useLayoutEffectDontMountTwice()` expects exactly one dependency')
  }
  
  const prevDependencies = useRef()
  const hasMounted = useRef()

  useLayoutEffect(() => {
    if (hasMounted.current && isShallowEqualArrays(prevDependencies.current, dependencies)) {
      console.log('Disable `useLayoutEffect()` double mount in React strict mode')
      return
    }
    hasMounted.current = true
    prevDependencies.current = dependencies
    handler()
  }, dependencies)
}

function isShallowEqualArrays(a, b) {
  if (!a && !b) {
    return true
  }
  if (!a && b || !b && a) {
    return false
  }
  if (a.length !== b.length) {
    return false
  }
  let i = 0
  while (i < a.length) {
    if (a[i] !== b[i]) {
      return false
    }
    i++
  }
  return true
}
```

**Comment by catamphetamine** [comment]
@egonSchiele Wow, that was quick, thanks 👍

**Comment by catamphetamine** [comment]
It looks like the PR hasn’t been merged so here’s a comment that the issue
is not fixed yet.

**Comment by catamphetamine** [comment]
It looks like the PR hasn’t been merged so here’s a comment that the issue
is not fixed yet.

Until the issue is fixed, the workaround I posted seems to work for my use case.
