### ISSUE TITLE
Bug: The placeholder is shown on top of the input value.

### ISSUE THREAD

**Issue by lazybean** [facebook/react#26327]
React version: 18.2.0 18.3.xxx

## Steps To Reproduce

1. On chrome canary, go to https://codesandbox.io/s/chrome-canary-placeholder-bug-ez4je3?file=/src/App.js
2. The placeholder is shown on top of the input value. 😱 
<img width="520" alt="image" src="https://user-images.githubusercontent.com/529333/223174089-f62093af-e010-4dec-ac9a-9a512e637975.png">

3. If you focus the input, the placeholder disappears. 👍 

Link to code example:
https://codesandbox.io/s/chrome-canary-placeholder-bug-ez4je3?file=/src/App.js

## The current behavior
The placeholder is shown on top of the input value.

## The expected behavior
The placeholder is not shown.

**Comment by lazybean** [comment]
I'm not sure this is a react bug or a chrome canary bug.
But because I cannot repro with simple html I decided to open issue here first.

**Comment by krishchha** [comment]
import "./styles.css";
import React, { useState } from "react";
export default function App() {
  const [value, setValue] = useState("");
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>

      <input
        onChange={(e) => setValue(e.target.value)}
        type="text"
        placeholder="Enter your name"
        value={value}
      />
    </div>
  );
}

**Comment by sunsations** [comment]
I have the same issue:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1168252/223981840-8121518f-ed56-47c8-be8c-e31f90449f38.png">

opening https://codesandbox.io/s/chrome-canary-placeholder-bug-ez4je3?file=/src/App.js

**Comment by gkienhuis** [comment]
See https://chromium-review.googlesource.com/c/chromium/src/+/4329778

**Comment by stefcameron** [comment]
> I'm not sure this is a react bug or a chrome canary bug.
> But because I cannot repro with simple html I decided to open issue here first.

Not a React bug. Plain HTML has the same issue. Seems to be Canary-specific.

`<input placeholder="This is the placeholder" value="foobar" />`

I see this in Canary Version 113.0.5629.0 (Official Build) canary (arm64), but I don't see it on Chrome Version 110.0.5481.177 (Official Build) (arm64) and FireFox 110.0 (64-bit). All these checks were done on on macOS 13.2.1 (22D68).
