### ISSUE TITLE
Bug: bootstrapScriptContent is being html encoded, which breaks rendering

### ISSUE THREAD

**Issue by gxxcastillo** [facebook/react#26359]
React version: react-dom v18.2.0

## Steps To Reproduce

1. Add `bootstrapScriptContent` option to `renderToPipeableStream()` according to docs:
```
bootstrapScriptContent: `window.assetMap = ${JSON.stringify(data)};`
```
2. Note all double quotes in the JSON string get converted to `&quot`; which breaks browser rendering with the following error: 
```
caught SyntaxError: Unexpected token '&' (at (index):1:261)
```

## The expected behavior

For `bootstrapScriptContent` to work as documented.

**Comment by gnoff** [comment]
@gxxcastillo can you provide a minimal reproduction? I don't seem to see the same issue when I try to simulate your test case with some made up data

**Comment by gxxcastillo** [comment]
@gnoff, I'm using NX with yarn workspaces and while putting together a minimal reproduction I found that Vite is packaging my server with version 8.0 but my client is being packaged with version 8.2.  When I created a version w/o NX and ensuring only 8.2 is used there was no issue.  I'll need to dig into that but not a react issue, sorry for the false alarm!
