### ISSUE TITLE
Bug: Error Boundary is not able to catch only specific Error types

### ISSUE THREAD

**Issue by jantimon** [facebook/react#26362]
React version: 18.2.0

## Steps To Reproduce

```tsx
import React from "react";

export class UnauthorizedError extends Error {}

interface IAuthenticationBoundaryProps { fallback: React.ReactNode, children: React.ReactNode}

export class AuthenticationBoundary extends React.Component<IAuthenticationBoundaryProps, {hasError: boolean}> {
  constructor(props: IAuthenticationBoundaryProps) {
    super(props);
    this.state = { hasError: false };
  }

  componentDidCatch(error: unknown) {
    if (error instanceof UnauthorizedError) {
      this.setState({
        hasError: true
      })
    }
  }

  render() {
    return <>
      {this.state.hasError ? this.props.fallback : this.props.children}
    </>
  }
}


let userId: number | null = null;

export function useIsLoggedIn({requiresLogin}: {requiresLogin: true}): number
export function useIsLoggedIn({requiresLogin}: {requiresLogin: false}): number | null
export function useIsLoggedIn({requiresLogin}: {requiresLogin: boolean}) {
  if (!userId && requiresLogin) {
    throw new UnauthorizedError()
  }
  return userId;
}
```

If any other error then `UnauthorizedError` is thrown the following error is shown:

`Error: AuthenticationBoundary: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.`

Link to code example:

https://codesandbox.io/s/dank-fast-ntyo9w

## The current behavior

React shows a warning if not all Error types are handled.

## The expected behavior

There should be a way to catch only specific errors.

**Comment by no-yan** [comment]
You just need to use getDerivedStateFromError. This error message warns lack of `getDerivedStateFromError`.


> There should be a way to catch only specific errors.

I think there is.

To handle only specific error in a Error Boundary, you should check error type in getDerivedStateFromError like the code below.
[Unhandled error will propagate to the closest error boundary above it. ](https://reactjs.org/docs/error-boundaries.html#:~:text=the%20error%20will%20propagate%20to%20the%20closest%20error%20boundary%20above%20it.) So keep in mind you should use other error boundary too.

```
  static getDerivedStateFromError(error: Error) {
    return {
      hasError: error instanceof UnauthorizedError
    };
  }
```

**Comment by Kelvym115** [comment]
As no-yan said, you just need to use `getDerivedStateFromError`. Correct me if I'm wrong but I also believe that the use of `componentDidCatch` should not be used in components after version 16.0.0 of React.

In that case you can add the method `getDerivedStateFromError` to update the component state when an error occurs inside child components.
