### ISSUE TITLE
Bug: Accordion is not collapsing in React beta docs

### ISSUE THREAD

**Issue by yuvarajsai** [facebook/react#26361]
React version: React Beta docs

## Steps To Reproduce

1. Click on the accordion on the left navigation panel, it opens to show list of options but it is not collapsing on click.

![image](https://user-images.githubusercontent.com/63961211/224229102-1117710b-983c-4116-bfec-f81fd3be4ac4.png)

https://beta.reactjs.org/reference/react

**Comment by egonSchiele** [comment]
What device and browser? This works correctly for me. Tested on an iPhone, iOS 16.2, with Safari, Firefox, Chrome, and DuckDuckGo.

**Comment by c-hinck10** [comment]
Confirmed the behavior on Windows 11 with Chrome, Firefox and Edge.

**Comment by egonSchiele** [comment]
Is there an error in the console? Unfortunately I don't have a Windows machine so can't easily debug this.

**Comment by manavgupta1996** [comment]
Is this issue resolved? If not I'll check this.

**Comment by LiaqatSaeed** [comment]
Any update on this issue. If not resolved yet. I can pick this one

**Comment by gaearon** [comment]
There's nothing to update — this is by design. There is no bug. It isn't supposed to collapse on click. I understand the design is a bit confusing but you can think of it as always keeping the current section expanded.
