### ISSUE TITLE
Bug: Two tests failing without any changes

### ISSUE THREAD

**Issue by gitAzad** [facebook/react#26393]
When running the tests in the React repository, I noticed that two tests are failing without any changes being made to the codebase. The failing tests are:

ReactClassEquivalence › tests the same thing for es6 classes and CoffeeScript
ReactClassEquivalence › tests the same thing for es6 classes and TypeScript
Both tests are failing with the following error message:
![image](https://user-images.githubusercontent.com/55752993/225219878-29741067-0de2-4b76-99e2-ba7eeb57c512.png)

I have reproduced the issue on my local machine by following the instructions in the React repository's README file. The issue persists even after running yarn clean and yarn commands.

I am using the following environment:

Operating system: Windows 10
Node version: 18.12.1
Yarn version: 1.22.19
React version: 18.2.0
I could not find any existing issue in the React repository's issue tracker related to this issue.

Please let me know if you need any additional information from my side to investigate and resolve this issue.

Thank you.

**Comment by eps1lon** [comment]
Does this still occur on a fresh clone? Could you include the concrete steps you took to encounter this issue?

**Comment by gitAzad** [comment]
yes occur on a fresh clone, here is the steps:
- clone the repository.
- install dependency using yarn.
- yarn test.
