### ISSUE TITLE
form fields with different type but no key get reused when re-rendering

### ISSUE THREAD

**Issue by johtso** [facebook/react#26414]
This behaviour seems really counter intuitive and foot-gun prone.
Here we see a password field getting turned into a text field and revealing its contents: https://stackblitz.com/edit/react-ue1odn?file=src/App.js

I personally stumbled on this issue with a form with some conditional rendering and multiple buttons (one `type="submit"` and another `type="button"` which would toggle the conditional rendering `onClick`). For some reason when I clicked the `type="button"` my form would be submitted. Hours of furious head scratching ensued. Turned out the `button` was being reused, turned into a `type="submit"` and then causing a `submit` event.
Here's an example of a form that get's submitted when the user clicks a button that's supposed to just be `type="button"`: https://stackblitz.com/edit/react-iqjcp8?file=src/App.js

If this really is how it _should_ behave, then shouldn't the docs mention the pitfalls here in the same way the importance of the use of `key`s is explained in relation to lists?
Maybe it should be added as a pitfall here? https://react.dev/learn/conditional-rendering

Or maybe it would be possible to have an automatic warning similar to `Warning: Each child in a list should have a unique “key” prop.`?

Old related issue: https://github.com/facebook/react/issues/8554

**Comment by gaearon** [comment]
It's described in more detail here: https://react.dev/learn/preserving-and-resetting-state

I agree it's not immediately obvious. The canonical solution for your case is to extract components like `SettingsForm` / `SignupForm`, for example.

It might be a good idea to mention it in "conditional rendering" but I'm worried it's a bit much at that stage.

**Comment by johtso** [comment]
@gaearon thanks for the thoughtful reply!

This section definitely covers these issues: https://react.dev/learn/preserving-and-resetting-state#resetting-state-at-the-same-position

The only thing that doesn't seem clear to me is what is considered the identity of a native element. "when you render a different component in the same position, it resets the state of its entire subtree"

Intuitively you'd think that different `type`s of `input`/`button` element would be considered different for the purposes of rendering. If it's literally just the element that's taken into consideration, then maybe the page could mention that and when that might be surprising (maybe using `submit`/`button` buttons as an example).

Hope this input is helpful!

**Comment by johtso** [comment]
@gaearon also, this was the use case:

https://user-images.githubusercontent.com/830800/225771356-fbe25006-837e-4b14-bd2e-96d4198d38e5.mov

https://gist.github.com/johtso/df763fbe9d9f50967e94e007f3091d42

There's obviously lots of ways I could have modelled this that _wouldn't_ have stumbled into this issue. I could have just hidden the password field instead of not rendering it, and used a `value` on the submit button to help the server distinguish the type of login.

To be honest I'm still not clear on how React models the "tree" to decide if a element is in the same place as a previous element. Looking at my implementation I still don't see why the presence of the `password` input field affects the identity / position in the tree of the two buttons.
