### ISSUE TITLE
unable to run examples in React tictactoe tutorial

### ISSUE THREAD

**Issue by elidata-test** [facebook/react#26429]
ERROR: _Unable to establish connection with the sandpack bundler. Make sure you are online or try again later. If the problem persists, please report it via [email](mailto:hello@codesandbox.io?subject=Sandpack%20Timeout%20Error) or submit an issue on [GitHub.](https://github.com/codesandbox/sandpack/issues)__

Works fine on Codesandbox site.

Consistently failed at https://react.dev/learn/tutorial-tic-tac-toe

I'm teaching at a school with strict web access policies. 
I've opened access to codesandbox.io - but this did not resolve the React Tutorial problem

Any help appreciated.
Eli Adler

**Comment by sechi747** [comment]
Same for me. And it could work on [codesandbox](https://codesandbox.io/s/ieh8uf?file=/App.js&utm_medium=sandpack)
![image](https://user-images.githubusercontent.com/73569598/226232102-7ab7c25e-6648-4bd1-a974-ac02493d4c0e.png)

**Comment by sebolio** [comment]
it also doesn't work when downloading and runing with `npm start` 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/197329/226398285-eb44b480-8229-4292-9d2b-c5b979418bdd.png">

**Comment by ruinmi** [comment]
same here, I put "import React  from 'react';" ont the top of the App.js. And it works.

**Comment by Antoniomora95** [comment]
@sebolio  try to do this
import react
`import React, { useState } from 'react';`

and then, use react fragment this way

` <React.Fragment>
      <div className="status">{status}</div>
      <div className="board-row">
        <Square value={squares[0]} onSquareClick={() => handleClick(0)} />
        <Square value={squares[1]} onSquareClick={() => handleClick(1)} />
        <Square value={squares[2]} onSquareClick={() => handleClick(2)} />
      </div>
    </React.Fragment>
`

not sure why it fails but looks to be related to the react version

**Comment by Dranaxel** [comment]
I'm encountering the same error as @sebolio on windows 10 - Debian 10 on WSL - node v19.8.1

@Antoniomora95 where are we supposed to add the line `import React, { useState } from 'react';`in ?

In index.js I get:
![image](https://user-images.githubusercontent.com/17832323/229303566-3c2b1e46-e7e0-4b8c-9c3a-194c5fe87615.png)

In app.js:
![image](https://user-images.githubusercontent.com/17832323/229303580-0767c402-a589-4949-9859-1f0fdb52f243.png)

**Comment by Dranaxel** [comment]
I finally fixed it. I added `import React from 'react';` in src/App.js

**Comment by gaearon** [comment]
Fixed this: https://github.com/facebook/react/issues/26429#issuecomment-1476504730.

As for this (https://github.com/facebook/react/issues/26429#issuecomment-1475517196), I don't know what we can do here — if your internet access is blocked, that's going to be a problem.
