### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Undisclosed64** [facebook/react#26428]
## Description
When I hover over the scrollbar in the sidebar of the new React documentation, it disappears instead of remaining visible so that I can scroll through the content. This makes it difficult to navigate through the documentation when the sidebar contains a lot of items.

## Steps to reproduce

Open the React documentation in a web browser
Navigate to a page with a long sidebar, such as the "/learn" page
Hover over the scrollbar in the sidebar

## Expected behavior
When I hover over the scrollbar in the sidebar, it should remain visible so that I can scroll through the content.

## Actual behavior
When I hover over the scrollbar in the sidebar, it disappears instead of remaining visible.

## Additional information

Browser and version: [e.g. Google Chrome 111.0.5563.65 ]

**Comment by Nanak360** [comment]
I tried reproducing this bug but was not able to. When I hover over the scroll bar it stays visible.

**Comment by Undisclosed64** [comment]
Did you try the new React doc?

**Comment by JSerZANP** [comment]
Guess this is not an issue for React, after hovering, you can scroll a little bit to call out the scrollbar

**Comment by madhusudhan123-star** [comment]
his bug should have be considered as a bug while reading or learning it may have difficulty.
