### ISSUE TITLE
React Component Guide

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [facebook/react#2644]
Just a quick thought on maybe having a guide on best practices in order to guide developers into creating better reusable components. Some components include styles, others don't. Some include tests, others don't. Some are built using Browserify, while others use Webpack, and others are strictly client-side based. I think there should be some sort of standard. For example I think open source components should be style agnostic and be able to be used on the server as well as the client. I would love some thoughts on this and don't mind contributing or starting a guide. I imagine a world where I could pull in a carousel component, navigation component, footer component etc, wire them up and have a full blown web application.

**Comment by gaearon** [comment]
Closing, as there is still no consensus on this, and the ecosystem will figure it out.
