### ISSUE TITLE
Bug: `react-dom-webpack-server` bundles are currently broken on `main`

### ISSUE THREAD

**Issue by markerikson** [facebook/react#26443]
React version: N/A (Build tooling issue on `main` as of commit [`0131d0c`](https://github.com/facebook/react/commit/0131d0cff40d4054ac72c857d3a13c5173c46e0a) )

## Steps To Reproduce

1. Clone, install, and run `yarn build`
2. Inspect `build/oss-stable/react-server-dom-webpack/cjs/react-server-dom-webpack-server.browser.development.js`
3. Scroll to line 300, around `var reservedProps =`.  Compare with `react-dom-bindings/src/shared/DOMProperty.js`.  Note that:
  - There is no `properties` object in the build output
  - The lines that _should_ say `properties[name] = new PropertyInfoRecord(....)` are missing the assignment, and only say `new PropertyInfoRecord()`
  - A couple of the associated constants like `const RESERVED = 0` are also missing

This appears to be a bug in Rollup's tree-shaking behavior.  If the Rollup config in `build.js` is modified to say `moduleSideEffects: 'safest'`, the missing content appears in these bundles.

Per experimentation, this can be addressed by adding a custom Rollup plugin that specifically tells Rollup "this code has side effects, don't tree-shake it" (based on https://github.com/rollup/rollup/issues/4090#issuecomment-847716887 ):

```ts
module.exports = function disableTreeshake() {
  return {
    name: 'scripts/rollup/plugins/disable-treeshake',
    transform(code, id) {
      // Fix issue with `react-dom-webpack-server` bundles accidentally
      // stripping out the `properties` object and not filling it out
      if (id.endsWith('DOMProperty.js')) {
        return {
          code,
          map: null,
          moduleSideEffects: 'no-treeshake',
        };
      }
      return null;
    },
  };
};
```

Link to code example:

## The current behavior

The full code from `DOMProperty.js` does not show up in those `react-dom-webpack-server` bundles

## The expected behavior

The `DOMProperty` output _should_ show up.

**Comment by markerikson** [comment]
I haven't tried to trace the usage of that code in the `react-dom-webpack-server` bundles.

If I look at what seems to be an equivalent section of one of the prod bundles, I see:

```ts
"allowFullScreen async autoFocus autoPlay controls default defer disabled disablePictureInPicture disableRemotePlayback formNoValidate hidden loop noModule noValidate open playsInline readOnly required reversed scoped seamless itemScope".split(" ").forEach(function(a){new y(a,3,!1,a.toLowerCase(),null,!1,!1)});["checked","multiple","muted","selected"].forEach(function(a){new y(a,3,!0,a,null,!1,!1)});
```

Which looks like it is that same code, with no assignment statement (ie, the `new y()` corresponds to `new PropertyInfoRecord()`, and that value is currently being created and thrown away).

**Comment by gaearon** [comment]
Yeah but the question is whether that `properties` object is being used in them. If it's not being used, isn't it correct that it gets removed?

**Comment by markerikson** [comment]
Here's a copy of the "fixed" dev bundle from one of my local builds:

[react-server-dom-webpack-server.browser.development-fixed.zip](https://github.com/facebook/react/files/11021540/react-server-dom-webpack-server.browser.development-fixed.zip)


Looking at it, the `properties` object is:

- Written to by all of the `properties[name] = new PropertyInfoRecord()` lines
- Read only by `getPropertyInfo()`

and I don't see any other references to `getPropertyInfo()` in that bundle file.

So, it does seem like _all_ of the `DOMProperty.js` logic _may_ actually be dead as far as this bundle is concerned.  (Although in that case, you'd think that all of it would get stripped out, especially in a prod build.)

Given that, this may not actually be a true bug in terms of behavior.

Not sure what the right answer here is, then.  I guess adding an extra plugin just to fix the output isn't necessary if it's not going to result in a difference in behavior, but it also seems odd to have seemingly-incorrect bundle output _and_ leave that extra dead logic in the bundles 🤷‍♂️

**Comment by markerikson** [comment]
Yeah, after inspecting the bundles, I would say that it's _just_ that they're "insufficiently optimized".  It does seem like there's a Rollup bug in that it _should_ either leave in all of `DOMProperty.js` _or_ strip all of it out, and _not_ strip out a few specific parts.  But, given that the `properties` stuff doesn't _seem_ to be used in those bundles, I think it's safe to leave that alone for now.
