### ISSUE TITLE
Bug: `useEffect()` is called with incorrect context in strict mode

### ISSUE THREAD

**Issue by catamphetamine** [facebook/react#26467]
React version: 18.2.0

## Steps To Reproduce

1. Go to the example page
2. Open the "Console"

Link to code example:
https://codesandbox.io/s/react-strictmode-effect-context-bug-demo-i4284t?file=/src/index.js

## The current behavior

The console says:

```
Render Number  1
Is First Number 
Render Number  2
Is Second Number 
**MOUNT Number  2**
**UNMOUNT Number  2**
MOUNT Number  2
```

## The expected behavior

The console should've said:

```
Render Number  1
Is First Number 
Render Number  2
Is Second Number 
**MOUNT Number  1**
**UNMOUNT Number 1**
MOUNT Number  2
```

## Consequence

The clean-up of the first-rendered component has not been done and its "bound" event listeners keep operating, resources not closed, etc.

**Comment by catamphetamine** [comment]
Ok, I guess that's the intended behavior to prevent components from adding listeners in `useMemo()` calls. Closing.

**Comment by Tomassito** [comment]
Hi @catamphetamine , what do you mean by `prevent components from adding listeners in useMemo() calls` ?

**Comment by catamphetamine** [comment]
@Tomassito Hi. I dunno what I meant there.  Also, I dunno why the "Expected behavior" is the expected one.

**Comment by Tomassito** [comment]
@catamphetamine I think you made a reasonable expectation there that because strict mode remounts the component, the logs would show a sequence of incremental value, not straight away value of 2.
