### ISSUE TITLE
Update react devtools readme - The React Tab Doesn't Show Up - CSP

### ISSUE THREAD

**Issue by kfox112** [facebook/react#26517]
It would be helpful to update this section of the readme to call out that a content security policy may also be the culprit:
https://github.com/facebook/react/tree/main/packages/react-devtools#the-react-tab-doesnt-show-up

It took me a while to figure this out on my own.  We have a CSP which was blocking the loading of react-devtools.  See:
https://github.com/facebook/react-devtools/issues/460
https://bugzilla.mozilla.org/show_bug.cgi?id=965637

**Comment by sherphy** [comment]
Hi!! My first time with open source, and very new to programming in general, sorry in advance if I'm no help! 

I was reading the chain of issues that you provided - from what I can infer, it's an issue on Firefox's side and there is no current solution (apart from some workarounds that don't seem viable long-term)? 

Therefore, for the documentation, would it be just "**If you are using Firefox**, it is possible that a Content Security Policy (CSP) is blocking the loading of DevTools."?

**Comment by kfox112** [comment]
Hi @sherphy - yes, basically.  Just a call out that a CSP may also cause DevTools to fail to load.  I think knowing that this may be an issue is enough.

There may be folks who, like me, can relax their CSP in development so that they can use React Dev Tools during the development phase.  Not an ideal solution, but a possibility.  ☺️
