### ISSUE TITLE
Is there any roadmap to enable the detection of iframes in React devtools?

### ISSUE THREAD

**Issue by IDrissAitHafid** [facebook/react#26515]
I have a component of my application that I inject into different websites as an iframe. I want to use the React devtools to analyze this component, but it doesn't show up in the devtools. 

I'm asking if there are any plans to make the React devtools work with iframes in the future.

**Comment by markerikson** [comment]
See https://github.com/facebook/react/issues/18945 for the main discussion around iframe handling.

Most likely you'll need to do something like this:

```ts
if (window.parent) {
  window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__;
}
```

**Comment by IDrissAitHafid** [comment]
Thanks for sharing @markerikson. I didn't knew there was an already open discussion about it, I should close this issue then 😅 

Actually, for me it's the other way around, something like: 
```js
const iframeWindow = ocument.getElementById("iframe").contentWindow;
if(iframeWindow){
  window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = iframeWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__ 
}
```

but  `iframeWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__` is undefined so I guess the React Devtools doesn't inject `__REACT_DEVTOOLS_GLOBAL_HOOK__ ` into iframes.

**Comment by markerikson** [comment]
That's the actual point here, yes.

The React DevTools add `window.__REACT_DEVTOOLS_GLOBAL_HOOK__` to the _main_ `window`, but not to iframes.

So, you have to copy that reference _into_ each iframe in order for the DevTools to talk to React inside that iframe.

**Comment by IDrissAitHafid** [comment]
Ah I see!

I just tested it but in my case the Iframe runs on different domains (I inject the Iframe from an extension) I get a cross-origin error.

Thanks for your help!
