### ISSUE TITLE
Bug: window.location.search is stale value and not synchronized with useLocation().search

### ISSUE THREAD

**Issue by mrdulin** [facebook/react#26525]
React version: 16.14.0

https://github.com/remix-run/react-router/issues/10289

**Comment by gaearon** [comment]
If you believe there is a React bug, please produce a sandbox that does not include React Router. One way to do this is to look at React Router source code and simulate something similar.

**Comment by gaearon** [comment]
Also, if the issue is specific to 16.x, we're not going to look into a fix.

**Comment by mrdulin** [comment]
@gaearon OK. Thanks

**Comment by gaearon** [comment]
I also replied here — not clear how this could be a React bug unless I'm missing something. https://github.com/remix-run/react-router/issues/10289#issuecomment-1491239403
