### ISSUE TITLE
dropdown not closing on clicking on same icon reactjs

### ISSUE THREAD

**Issue by RahulMittal18** [facebook/react#26538]
Expected Behavior : When clicked on profile icon, if dropdown is not open,open the dropdown else close the dropdown. And close the dropdown if clicked anywhere outside the dropdown.

Actual Behavior: When clicked on profile icon, if dropdown is not open, the dropdown gets open.  And the dropdown is also closing if clicked anywhere outside the dropdown.    but if dropdown is already open, it does not close on clicking on profile icon again.

Here is my code:
```
const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imgRef = useRef();
  useEffect(() => {
    let closeDropdown = (e) => {
      if (imgRef.current && !imgRef.current.contains(e.target)) {
        setIsOpen(false);
      }
    };
    document.body.addEventListener("click", closeDropdown);
    return () => document.body.removeEventListener("click", closeDropdown);
    }, []);


    return (
       <div>
              <div className={"dropdownn1 " + (isOpen ? "open" : "closed")}>
                    <Dropdown />
              </div>
              <div className="profile_icon_div" ref={imgRef}>
                     <img
                        src={profileImageUrl}
                        onClick={() => setIsOpen((prev) => !prev)}
                        className="profile_icon_image"
                        alt=""
                      />
               </div>
        </div>
      );
};

export default Navbar;
```

**Comment by Animesh239** [comment]
you can use the elseif for targeting the same icon when dropdown is active 

```
useEffect(() => {
  let closeDropdown = (e) => {
    if (imgRef.current && !imgRef.current.contains(e.target)) {
      setIsOpen(false);
    } else if (imgRef.current === e.target) {
      setIsOpen((prev) => !prev);
    }
  };
  document.body.addEventListener("click", closeDropdown);
  return () => document.body.removeEventListener("click", closeDropdown);
}, []);

**Comment by RahulMittal18** [comment]
Still not working

**Comment by iRONiCBAT7** [comment]
> useEffect(() => {

    let closeDropdown = (e) => {
      if (imgRef.current && !imgRef.current.contains(e.target)) {
        setIsOpen(false);
      }
    };
    document.body.addEventListener("click", closeDropdown);
    return () => document.body.removeEventListener("click", closeDropdown);
    }, [isOpen]);

// there I added [isOpen] in the dependency array of useEffect   
// whenever isOpen will change useEffect  will be called with its sideeffect
// I think it will work. 

.
.
.
.


// And yeah one more thing is that , there is an extra div tag 
> 
    return (
       <div>
         <div>
              <div className={"dropdownn1 " + (isOpen ? "open" : "closed")}>
              <Dropdown />
          </div>
          <div className="profile_icon_div" ref={imgRef}>
                 <img
                    src={profileImageUrl}
                    onClick={() => setIsOpen((prev) => !prev)}
                    className="profile_icon_image"
                    alt=""
                  />
           </div>
         </div>
      );

**Comment by RahulMittal18** [comment]
None of them worked @ag533 
IsOpen remains true even when I click on profile icon again and again.

**Comment by umeh-promise** [comment]
Firstly boss, you did not reference the imgRef.
It should be const imageRef = React.useRef()

import React, {useState, useRef} from 'react'
const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imgRef = useRef()

  useEffect(() => {
    const closeDropdown = (e) => {
      if (imgRef.current && !imgRef.current?.contains(e.target)) {
        setIsOpen(false);
      }
    };
    document.body.addEventListener("click", closeDropdown);
    return () => document.body.removeEventListener("click", closeDropdown);
    }, []);


    return (
       <div>
         <div>
              <div className={"dropdownn1 " + (isOpen ? "open" : "closed")}>
              <Dropdown />
          </div>
          <div className="profile_icon_div" ref={imgRef}>
                 <img
                    src={profileImageUrl}
                    onClick={() => setIsOpen((prev) => !prev)}
                    className="profile_icon_image"
                    alt=""
                  />
           </div>
         </div>
      );
};

export default Navbar;

Also do confirm from you dev tools to see if the state of isOpen changes on click (i.e from false to true)

**Comment by RahulMittal18** [comment]
Updated the original code @umeh-promise ..check now..still not working

**Comment by RahulMittal18** [comment]
tried this too @ag533 .. still not working

**Comment by ag533** [comment]
Hey @RahulMittal18,

Try this solution I have move your logic inside the DropDown and it's working fine for me - https://codesandbox.io/s/quiet-sky-s85kqe?file=/src/App.js. It is similar to you solution but without the overhead complications 😄. Let me know if this helps. 

All the best 😸

**Comment by rachit298** [comment]
@RahulMittal18 Please share all dependencies of this file, like the CSS code you used in this file and the Dropdown component's code.

**Comment by RahulMittal18** [comment]
@ag533 read the complete expected behaviour once again.
Dropdown is not closing on clicking outside the navbar

**Comment by RahulMittal18** [comment]
@rachit298 It is not possible to share here. At max, I can schedule a meet for this.

**Comment by rachit298** [comment]
@RahulMittal18 You can create a repo and put all files in there. And share that repo link in original issue here.

**Comment by ag533** [comment]
@RahulMittal18 I have modified the sandbox respective to the expected behaviour - https://codesandbox.io/s/quiet-sky-s85kqe?file=/src/withClickOutside.js:0-574. Please have a look and let me know if this works for you. Basically what i have done is created a wrapper for the component that can be implemented for the whole page.

**Comment by RahulMittal18** [comment]
@ag533 it's working but i can't impplement it in  my code

**Comment by ag533** [comment]
In that case please share bits of your code in a sandbox in a runnable state so that I can see it over there and help you @RahulMittal18 😊. As it is very difficult to replicate your exact behaviour in my system.

**Comment by gaearon** [comment]
Can someone please create a sandbox for the _original_ code? I see there are many solutions. I want to post the idiomatic one but I don't have any sandbox to modify because they're all doing something different.

**Comment by umeh-promise** [comment]
Alright @RahulMittal18 can you please share the code sandbox for this so we can easily debug the code.

**Comment by RahulMittal18** [comment]
@umeh-promise @gaearon @ag533 @rachit298 sharing my code sandbox link


https://codesandbox.io/s/festive-oskar-gyry34?file=/src/App.js

**Comment by umeh-promise** [comment]
@RahulMittal18 
To fix the issue, I added the **stopPropagation()** method to the child element's event handler function to prevent the event from propagating up to the parent elements. This ensured that the parent event handler function, which was closing the dropdown menu, was not triggered when the user clicked inside the menu.  I also changed document.body.addEventListener() to document.addEventListener() in the closeDropdown() function to close the dropdown menu when the user clicks anywhere in the document, not just in the NavbarNew component.

I also updated the **setIsOpen()** method inside the **handleProfileClick()** function to toggle the **isOpen** state based on its previous value using the prevState function argument. This ensures that the isOpen state is updated correctly, even if multiple updates are triggered in quick succession.

With these changes, the dropdown menu now stays open when the user clicks inside the menu or anywhere in the document, but still closes when the user clicks outside the menu.

All changes were made in the NavbarNew component.

[View](https://codesandbox.io/s/amazing-khorana-2pqz7d?file=/src/components/NavbarNew.js)

**Comment by RahulMittal18** [comment]
@umeh-promise document.addEventListener is not working on my localhost. even the dropdown does not get open..
after using document.body.addEventListener it is working as before not like yours in code sandbox

**Comment by RahulMittal18** [comment]
@umeh-promise  I changed "click" with "mouseup"...now its working as before with document.addEventListener but not working as expected.

**Comment by umeh-promise** [comment]
This actually might be from your local machine 
Did you try it using the link I attached here.
Test it out it's working.

**Comment by RahulMittal18** [comment]
@umeh-promise code in your link is working which has react-version 18 and i had react 16..upgrading it to 18 is causing many dependency conflicts. so i am not able to upgrade it to 18

**Comment by RahulMittal18** [comment]
@umeh-promise give a solution for react version 16.13.1

**Comment by pranshu05** [comment]
Adding if statement for `isOpen` can solve the problem
```js
const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imgRef = useRef();

  useEffect(() => {
    let closeDropdown = (e) => {
      if (imgRef.current && !imgRef.current.contains(e.target)) {
        setIsOpen(false);
      }
    };

    document.body.addEventListener("click", closeDropdown);

    return () => document.body.removeEventListener("click", closeDropdown);
  }, []);

  const toggleDropdown = () => {
    setIsOpen((prev) => !prev);
  };

  return (
    <div>
      <div className={"dropdownn1 " + (isOpen ? "open" : "closed")}>
        <Dropdown />
      </div>
      <div className="profile_icon_div" ref={imgRef}>
        <img
          src={profileImageUrl}
          onClick={toggleDropdown}
          className="profile_icon_image"
          alt=""
        />
      </div>
    </div>
  );
};

export default Navbar;

```

**Comment by sumitshinde-84** [comment]
I would like to work on this issue,  can you please assign it to me?

**Comment by gokuljs** [comment]
@RahulMittal18 instead of document.body use window.addEventListener

**Comment by RahulMittal18** [comment]
> I would like to work on this issue, can you please assign it to me?

assigned to you @sumitshinde-84

**Comment by sumitshinde-84** [comment]
const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imgRef = useRef();

  useEffect(() => {
    let closeDropdown = (e) => {
      if (imgRef.current && !imgRef.current.contains(e.target)) {
        setIsOpen(false);
      }
    };

    document.body.addEventListener("click", closeDropdown);
    return () => document.body.removeEventListener("click", closeDropdown);
  }, []);

  const handleProfileIconClick = () => {
    setIsOpen((prev) => !prev); // Toggle the dropdown
  };

  return (
    <div>
      <div className={"dropdownn1 " + (isOpen ? "open" : "closed")}>
        <Dropdown />
      </div>
      <div className="profile_icon_div" ref={imgRef}>
        <img
          src={profileImageUrl}
          onClick={handleProfileIconClick} // Update the event handler
          className="profile_icon_image"
          alt=""
        />
      </div>
    </div>
  );
};

export default Navbar;

**Comment by sumitshinde-84** [comment]
const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imgRef = useRef();

  useEffect(() => {
    let closeDropdown = (e) => {
      if (imgRef.current && !imgRef.current.contains(e.target)) {
        setIsOpen(false);
      }
    };

    document.body.addEventListener("click", closeDropdown);
    return () => document.body.removeEventListener("click", closeDropdown);
  }, []);

  const handleProfileIconClick = () => {
    setIsOpen((prev) => !prev); // Toggle the dropdown
  };

  return (
    <div>
      <div className={"dropdownn1 " + (isOpen ? "open" : "closed")}>
        <Dropdown />
      </div>
      <div className="profile_icon_div" ref={imgRef}>
        <img
          src={profileImageUrl}
          onClick={handleProfileIconClick} // Update the event handler
          className="profile_icon_image"
          alt=""
        />
      </div>
    </div>
  );
};

export default Navbar;

**Comment by umeh-promise** [comment]
@RahulMittal18 The only way I could be of help to you is if you do add me to the project repo.
That way I can have access to the version you are using and do the debugging or better still, send me the project link.

Thank you.

**Comment by Sukrittt** [comment]
You can try adding a if condition to check if you are clicking the profile icon. If yes then toggle isOpen
Note that you are not mentioning anything about what will happen if we click on the profile image (imgRef).

Here is my code:

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imgRef = useRef();
  useEffect(() => {
    let closeDropdown = (e) => {
      if (imgRef.current && !imgRef.current.contains(e.target)) {
        setIsOpen(false);
      }

     //Here's what I added
     if(imgRef.current.contains(e.target)){
         setIsOpen((prev) => !prev);
     }

    };
    document.body.addEventListener("click", closeDropdown);
    return () => document.body.removeEventListener("click", closeDropdown);
    }, []);


    return (
       <div>
              <div className={"dropdownn1 " + (isOpen ? "open" : "closed")}>
                    <Dropdown />
              </div>
              <div className="profile_icon_div" ref={imgRef}>
                     <img
                        src={profileImageUrl}
                        onClick={() => setIsOpen((prev) => !prev)}
                        className="profile_icon_image"
                        alt=""
                      />
               </div>
        </div>
      );
};

export default Navbar;

**Comment by urmybestfriend** [comment]
Perfect guys

**Comment by kushhingol** [comment]
Also a quick suggestion @RahulMittal18 please use conditional rendering instead of styles rendering. Its always better to not mount the required elements/nodes into the DOM tree which makes things expensive on rendering side. Just dropping in a suggestion 


```javascript
const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imgRef = useRef();

  const handleImageClick = () => {
    setIsOpen((prevIsOpen) => !prevIsOpen);
  };

  useEffect(() => {
    const handleClickOutside = (evt) => {
      if (imgRef?.current && !imgRef?.current?.contains(evt.target)) {
        setIsOpen(false);
      }
    };
    document.addEventListener("click", handleClickOutside);
    
    // cleanup for event listener
    return () => {
      document.removeEventListener("click", handleClickOutside);
    };
  }, [isOpen]);

  return (
    <>
      {isOpen && (
        <div className={"dropdown"}>
          <Dropdown />
        </div>
      )}

      <div className="profile_icon_div" ref={imgRef} onClick={handleImageClick}>
        <img
          src={profileImageUrl}
          onClick={() => setIsOpen((prev) => !prev)}
          className="profile_icon_image"
          alt="Profile-Icon"
        />
      </div>
    </>
  );
};

```

You can also create a custom hook where you can pass the ref and your callback method which can manage the click events which are clicked outside the ref which you pass in the hook.
Happy Learning 😊

**Comment by sandeepmichael** [comment]
why don't you add conditional rendering for onClick method. just correct me if i'm wrong guys.
