### ISSUE TITLE
Suggest adding Chinese to the new version of the official website

### ISSUE THREAD

**Issue by rjl-cli** [facebook/react#26530]
Full English users who are not very good at English are not very friendly

**Comment by gaearon** [comment]
It's here: https://zh-hans.react.dev/

We're going to add a language switcher at some point later.

**Comment by Magin-CC** [comment]
@gaearon  Hello gaearon, how to contribute to Chinese document. 
It doesn't look like finished yet. Thanks.

**Comment by CHWYH** [comment]
version 

> It's here: https://zh-hans.react.dev/
> 
> We're going to add a language switcher at some point later.

When will the **new version** be released?

**Comment by CHWYH** [comment]
@gaearon When will the new version be released? It's been a long time since the last version.
