### ISSUE TITLE
[DevTools Bug]: DevTools settings are not being saved in the Edge browser

### ISSUE THREAD

**Issue by matspiewak** [facebook/react#26548]
### Website or app

https://react.dev/

### Repro steps

1. Open DevTools
2. Click View Settings
3. Change one of the options
4. Refresh page
5. No option is being saved

### How often does this bug happen?

Every time

**Comment by pranshu05** [comment]
I think resetting your browser settings can solve the problem

**Comment by Uneebbhat** [comment]
open website in incognito mode and try there. Or just hit ctrl + f5 to clear the browser cache.

**Comment by Uneebbhat** [comment]
I will suggest you to use chrome instead of using edge.

**Comment by matspiewak** [comment]
> open website in incognito mode and try there. Or just hit ctrl + f5 to clear the browser cache.

Didn't work, tried that

> I will suggest you to use chrome instead of using edge.

Can't use Google Chrome, that's why I'm using MS Edge

**Comment by matspiewak** [comment]
> I think resetting your browser settings can solve the problem

I've also tried that. Didn't work.

**Comment by Uneebbhat** [comment]
Have you tried testing your website on different browsers?

**Comment by mondaychen** [comment]
I was not able to reproduce this issue. What version of Edge and React DevTools are you using?

**Comment by matspiewak** [comment]
> Have you tried testing your website on different browsers?

Yes I did. I'm currently using Mozilla Firefox, but it lacks the "Reload and start profiling feature" i needed. Because I can't currently use Google Chrome, I've tried with MS Edge

**Comment by matspiewak** [comment]
> I was not able to reproduce this issue. What version of Edge and React DevTools are you using?

At the time of creating this issue: 
MS Edge - 112.0.1722.34
DevTools - 4.27.3

Currently:
MS Edge - 112.0.1722.39
DevTools - 4.27.3

Problem still exists

**Comment by Uneebbhat** [comment]
DevTools settings are not being saved in the Edge browser
If your DevTools settings are not being saved in the Edge browser, there are a few possible solutions you can try:

Check if you are using the latest version of the Edge browser. If not, update it to the latest version and see if the issue persists.

Clear your browser cache and cookies. Sometimes, browser cache and cookies can cause issues with saving settings. Clearing them can help resolve the problem.

Try resetting the DevTools settings. To do this, open DevTools, click on the three dots in the top-right corner, select "Settings," and then click on "Restore defaults and reload." This will reset all DevTools settings to their default values.

Try running the Edge browser as an administrator. Sometimes, user permissions can prevent settings from being saved properly. Running the browser as an administrator can help resolve this issue.

If none of the above solutions work, try uninstalling and reinstalling the Edge browser. This can help fix any underlying issues with the browser that may be preventing settings from being saved.

If the issue still persists after trying all of these solutions, you may need to reach out to the Edge browser support team for further assistance.

I asked your question from chat gpt.

**Comment by matspiewak** [comment]
I've found the (workaround) solution. Because of my company's policy, I've disabled cookies in my MS Edge browser, and because of that, none of the extension's settings could be saved. If anyone is interested in this solution, it's [here](https://github.com/facebook/react/issues/16475#issuecomment-523400934)

Anyways, thank you all for help.
Closing this issue.
