### ISSUE TITLE
Bug: Newly Rendered `dialog` Elements Wrongly Retain the "Open State" of a Previously Rendered `dialog`

### ISSUE THREAD

**Issue by ITenthusiasm** [facebook/react#26544]
## The Problem

Currently, a newly rendered `dialog` element can erroneously retain the "open state" a previously rendered `dialog` element if React _thinks_ that the same element is being re-rendered. Interestingly enough, this problem doesn't seem to happen for the element's other attributes/properties.

React version: `18.2.0`

## Steps To Reproduce

The situation is best understood with a [CodeSandbox](https://codesandbox.io/s/react-typescript-forked-nruu1q?file=/src/ModalComponent.tsx). Notice that after the state change (which happens on submission of the `dialog`'s form), the `open` attribute is stale, but the `data-phase` attribute is fresh.

This is potentially a problem with the reconciler ... because if you change the "phase two version" to have a wrapping `div`, this problem goes away. (This is not always a viable solution, however. And it's a bit hacky.)

## The current behavior

When [`ModalComponent`](https://codesandbox.io/s/react-typescript-forked-nruu1q?file=/src/ModalComponent.tsx) re-renders, the new `dialog` element that it mounts retains the `open` value of the previous `dialog` element.

## The expected behavior

When [`ModalComponent`](https://codesandbox.io/s/react-typescript-forked-nruu1q?file=/src/ModalComponent.tsx) re-renders, the new `dialog` element that it mounts _should not_ have an `open` attribute since none was provided for it.

## Extra Notes

The conversation would be unrelated to the bug, but in case it's brought up: Please note that the actual project that I'm working on does not simply have virtually-duplicated content between the 2 dialog elements. (The content between the two is distinct.) So combining the content under a single `dialog` element is not an option for me at the moment.

**Comment by eps1lon** [comment]
> this problem doesn't seem to happen for the element's other attributes/properties.

This behavior will be observed with any other component. State is persisted if the component type stays the same: https://codesandbox.io/s/host-component-properties-are-persisted-across-re-renders-orxme7

If you want to use the same element type, but reset state, you can use the `key` prop: https://codesandbox.io/s/react-typescript-forked-tn34uw. The pattern is explained in more detail im [Preserving and Resetting State: Resetting state with a key 
](https://react.dev/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key)
