### ISSUE TITLE
ReactDOMTextComponent needs getInstance()

### ISSUE THREAD

**Issue by zpao** [facebook/react#2654]
With the recent separation of internal and external instances ReactDOMTextComponents got left out. Certain tools (namely ReactTestUtils) expect that everything in the rendered tree conforms to a certain API. Attempting to sync the last couple weeks of React to FB is causing tests which depend on `ReactTestUtils.findAllInRenderedTree` to fail as a result.

cc @spicyj @sebmarkbage

**Comment by jimfb** [comment]
Fixed in #2695
