### ISSUE TITLE
Bug: TypeError: aAttribruteValue.parentNode.getAttribute is not a function 

### ISSUE THREAD

**Issue by henryspivey** [facebook/react#26547]
React version: v18.2.0

## Steps To Reproduce

1. Create a new project with `npx create-react-app just-testing  --template typescript`
2. Change App.tsx to the following: 
```
function App() {
  return (
    <main className='App'>
      <h1>Hello World</h1>
    </main>
  );
}
```
3. Run `npm run start` 
4. Click on the rendered page anywhere

Link to code example: https://b6upx6-3000.csb.app/

## The current behavior
After modifying App.tsx you should see an error message 
```
Compiled with problems:

ERROR
aAttribruteValue.parentNode.getAttribute is not a function
TypeError: aAttribruteValue.parentNode.getAttribute is not a function
    at HTMLDocument.<anonymous> (<anonymous>:21:43)
```

## The expected behavior
Clicking on the page should not have this issue. Also, although semantically may have no meaning, attribute has no second 'r' in  the word but the variable name is 'aAttribruteValue'

**Comment by itsnoa04** [comment]
hey @henryspivey, i was unable to reproduce this issue, was there any other modifications?

**Comment by henryspivey** [comment]
> hey @henryspivey, i was unable to reproduce this issue, was there any other modifications?

No all the modifications you need to make are outlined above. I guess we can close this because I don't see this any longer.
