### ISSUE TITLE
Bug: The scroll bar of the sidebar is getting hidden while hovering in the describing UI section (in Learn React).

### ISSUE THREAD

**Issue by Devang1224** [facebook/react#26585]
While opening any section in the Learn React section, I am not able to use the scroll bar.

#The current behaviour
Try to hover over the scrollbar of the describing UI section, which is present in the sidebar; it is getting hidden. You can scroll it using the down or up arrow keys or with the scroll bar, but you cannot click on the scroll.

#The expected behaviour
It should not disappear while hovering.

https://react.dev/learn/describing-the-ui

**Comment by Aaryansh1** [comment]
Hey I can resolve this issue if someone assigns it to me. It's my first time contributing to open source. Thanks

**Comment by urmybestfriend** [comment]
Good

**Comment by evrenkaraarslan** [comment]
I think this issue should be opened in react.dev repository https://github.com/reactjs/react.dev/issues , not here @Devang1224

**Comment by Devang1224** [comment]
> 

yes i was thinking about that actually let me correct it .
as

**Comment by Aaryansh1** [comment]
@Devang1224 let me know once you do I will write up there
