### ISSUE TITLE
When I reload deployed reactjs app on any page other than main routes it says not found

### ISSUE THREAD

**Issue by GoPro9090** [facebook/react#26584]
React version: 18

## Steps To Reproduce

1. app is deployed on [this](https://instacart-ici3.onrender.com/) head over it.
2. change route to any other page from navbar reload the page it will produce the error

Link to code example:

## The current behavior
 render deployment says 
![image](https://user-images.githubusercontent.com/105076805/230896088-d011596d-c673-4ea5-85c2-e3bc2490ef03.png)
netlify deployment
![image](https://user-images.githubusercontent.com/105076805/230896835-a5dfdf40-f450-4410-a01a-327d3d7353dd.png)
![image](https://user-images.githubusercontent.com/105076805/230896907-c500b720-5e38-4df5-97c5-f8b84fbe4ef2.png)

**Comment by muzamil301** [comment]
Could you please share a few details about the server
On a few servers, we have to add .htaccess file with redirection rules for the case that if the user reloads the app it will recognize the route otherwise the app won't work

**Comment by GoPro9090** [comment]
simple expressjs server with mongodb as database and mongoose ODM and deployed on render web service.
haven't any file like .htacsess

**Comment by Aaryansh1** [comment]
Hey @GoPro9090 I checked it out it seems to be working for me found no issues.

**Comment by GoPro9090** [comment]
solved the issue actually the problem was that we have to add redirect/rewrite rules for reloading and refresh to work on render or any other problem.

thanks everyone for helping
