### ISSUE TITLE
Warnings only logged once even for different roots and renders

### ISSUE THREAD

**Issue by robin-drexler** [facebook/react#26581]
Hey 👋,

certain warnings are logged only once, even if they occur multiple times within the rendered tree. For instance:

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```

https://github.com/facebook/react/blob/9a9da7721e5b73a8af242807e463e2af842c58ee/packages/react-dom-bindings/src/client/validateDOMNesting.js#L479 

This approach makes sense to prevent the console from being flooded with warnings. However, an argument can be made that each ReactDOM `root` should track its own warnings. This way, if two independent trees generate the same warning, it would be logged twice instead of just once.

Why is this an issue? I have two reasons: one is philosophical, and the other is practical.

1. If `createRoot`/`render` is utilized multiple times, it's reasonable to assume that there could be two distinct apps, possibly maintained by separate teams. Each team should be able to address their respective warnings without depending on another team to fix theirs first.

2. This problem causes issues in our project's testing setup due to several factors. Firstly, we use [jest-fail-on-console](https://www.npmjs.com/package/jest-fail-on-console) to treat `console.warn` or `console.error` calls as test failures. This helps us avoid overlooking warnings and prevents console call spam in the CI output.

We also employ [`jest.retryTimes`](https://jestjs.io/docs/jest-object#jestretrytimesnumretries-options) to retry tests when they fail on CI, aiming to identify flaky tests. ReactDOM's logging behavior now leads to a situation where the test fails once due to ReactDOM's `console.error` call, but then passes the second time because the error is not printed again, even though the rendered output remains the same. Consequently, the test is marked as green on CI when it should not be, skewing data , and even worse, it will always fail when run locally since there is no retry there. Sometimes this happens to tests that aren't close to the code that introduced the warning and go unnoticed by the author due to CI not catching it.

Side note: It's afaik unfortunately incredibly hard/impossible to reset es modules in between tests in jest which would help in our case, but not in the first one.

It would be helpful if ReactDOM could either offer a method to reset warning flags or reset them automatically for each `root.render` call.

React version: 18.2.0

## Steps to Reproduce
[https://codesandbox.io/s/keen-blackburn-zw2e5v?file=/src/index.tsx](https://codesandbox.io/s/keen-blackburn-zw2e5v?file=/src/index.tsx)

1. Create two ReactDOM roots
2. Render code that generates the aforementioned warning in each
3. The warning will only be printed to the console once

This sandbox renders two roots containing the same violation. However, the console warning is printed only once, not twice.

**Comment by Sanskar-tyagi** [comment]
I think maybe creating a new API in ReactDOM that allows users to reset the warning flags for a specific root would be a nice approach. This would ensure that each root maintains its own set of warnings and prevent the console from being flooded with warnings.

**Comment by robin-drexler** [comment]
Bump
