### ISSUE TITLE
Bug: updating state to an existing value is (incorrectly?) triggering a re-render

### ISSUE THREAD

**Issue by alexreardon** [facebook/react#26598]
React version: `18.2.0` 

(also same in `16.14.0`)

## Steps To Reproduce

1. Set a piece of state to a new value (which will cause a render)
2. Set a piece of state with the same value as before, causing a re-render ([which should normally skip a re-render](https://react.dev/reference/react/useState#setstate-caveats))
3. Subsequent setting of the state to the same value does not cause re-rendering

Link to code example:

- [🎥 A video I made that explains the issue](https://twitter.com/alexandereardon/status/1645631194325995523)
- [🤹‍♀️ A standalone example - react 18](https://codesandbox.io/s/react-set-state-optimisation-react-18-p48li8?file=/src/App.tsx)
- [🤹‍♀️ A standalone example - react 16](https://codesandbox.io/s/react-set-state-optimisation-react-16-ed9ftr?file=/src/App.tsx)
- [🃏 jest + jsdom on node](https://stackblitz.com/edit/node-sswt3h?file=behaviour.spec.js)

## The current behavior

Changing react state to the current state value is triggering a re-render

## The expected behavior

Changing react state to the current state value should not trigger a re-render

## Additional thoughts

One of the best ways to improve interaction performance with react is to avoid asking react to re-render things it does not need to. It would be great to write tests to assert re-rendering behaviour. Unfortunately, this is not possible with react today due to this issue

It can be extremely delicate work to minimise react re-rendering, and it is something that is easy to accidentally regress on. You could argue that you could measure performance in some other way and that additional react re-rendering could be caught by that. That is true, however, I expect most interactions for most applications do not have fantastic interaction performance testing/monitoring. It would be super helpful (and straightforward) to be able to assert react render behaviour in tests without needing to rely on any complex performance testing/monitoring setup. Of course, you could always have both interaction performance testing/monitoring and tests

**Comment by vkurchatkin** [comment]
On the linked documentation page it literally says that this is expected:

> Although in some cases React may still need to call your component before skipping the children, it shouldn’t affect your code

**Comment by alexreardon** [comment]
Here is the full text as at 13th April:

> If the new value you provide is identical to the current state, as determined by an [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) comparison, React will skip re-rendering the component and its children. This is an optimization. Although in some cases React may still need to call your component before skipping the children, it shouldn’t affect your code.

Subjectively, I think that wording the caveat that the re-render optimization is skipped "in some cases" implies that the de-optimization should only occur in outlier circumstances (eg nested set states in an effect), and not in standard happy path cases. Personally, I think that skipping the re-render optimization for a happy path case is a bug.

I appreciate that component renders should be pure, and so an additional re-render should not be a problem. However, I still think that this current behaviour is incorrect. The current behaviour hurt me when I was trying to write a test to assert that a component should not render after a particular event, but a render did occur.

**Comment by brayanjeshua** [comment]
It could be a joke but... Have you tried to remove the StictMode?

https://react.dev/reference/react/StrictMode

**Comment by alexreardon** [comment]
I can confirm that this bug appears without strict mode on
