### ISSUE TITLE
componentDidUpdate fires before browser paint operation

### ISSUE THREAD

**Issue by jackwanders** [facebook/react#2659]
I'm not sure that this isn't by design, but I discovered today that the lifecycle methods executed after a React element renders (i.e. `componentDidMount` and `componentDidUpdate`, executed at the point noted below) appear to be executed before the browser's paint operation.

[src/browser/ReactReconcileTransaction.js#L81](https://github.com/facebook/react/blob/master/src/browser/ReactReconcileTransaction.js#L81)

This introduced some unexpected behavior in a scenario similar to this example:

``` javascript
var Widget = React.createClass({
  componentWillUpdate: function() {
    this.stashedStyleValue = this.getDOMNode().style.someValue;
    this.getDOMNode().style.someValue = 'none';
  },
  componentDidUpdate: function() {
    this.getDOMNode().style.someValue = this.stashedStyleValue;
  },
  render: function() {
    return (
      <div>...</div>
    );
  }
});
```

Given the React class above, I would expect the following order of operations when the component re-renders in the browser:
1. `componentWillUpdate` fires
2. `render` fires
3. browser re-paints the DOM
4. `componentDidUpdate` fires

However, this is not the case. The actual behavior is that steps 3 and 4 occur in the reverse order. In Chrome, when I record a timeline of events, I see the following:
1. `Recalculate Style`
2. `Update Layer Tree`
3. `Paint x 3`
4. `Composite Layers`

It this example, it looks like `this.getDOMNode().style.someValue` changes, then changes back before the paint ever occurs, rendering my efforts futile without manually deferring the logic in `componentDidUpdate` using `window.setTimeout`.

To test my theory that the order would be different if `componentDidUpdate` fired after the paint operation, I made the following changes to the React source:

https://github.com/jackwanders/react/compare/defer-post-render-lifecycle-methods?expand=1

When I load the same element in the browser using the modified code, the timeline in Chrome is as follows:
1. `Recalculate Style`
2. `Update Layer Tree`
3. `Paint x 3`
4. `Composite Layers`
5. `Recalculate Style`

This is the order of operations I would expect with the provided lifecycle methods defined in my example class above.

As I said, I can't say for certain that this is something that should be corrected, but I wanted to submit this issue and hopefully get some feedback from a React contributor, who is sure to have more domain knowledge and can explain why the existing flow exists, if indeed it is as designed.

Thanks.

**Comment by jDeppen** [comment]
@jackwanders would you mind sharing how you deferred the contents of componentDidUpdate? Did you use requestAnimationFrame?
Thanks!

**Comment by dustingetz** [comment]
dom reflow will happen before didUpdate (so I can measure heights), but before repaint (so i can effect based on the height without flicker)?
