### ISSUE TITLE
Bug:  

### ISSUE THREAD

**Issue by Sukrittt** [facebook/react#26601]
## Bug Description
When we click on links in the sidebar like "describing the UI, your first component," the specific component loads and a drop-down menu with a list of all subtopics under that topic appears. The problem is that the sublinks should disappear and the dropdown menu should close when we click on the dropdown icon again.

## Steps To Reproduce
Visit this link: https://react.dev/learn/describing-the-ui

## Screenshot of the bug
![image](https://user-images.githubusercontent.com/106579296/231080675-f48acb79-0708-4567-ab1d-4e7905977893.png)

## The current behavior
Dropdown not closing after clicking on the icon.

## The expected behavior
Users should be able to toggle the visibility of the Dropdown.

**Comment by ashuthe1** [comment]
I would like to work on this could you please assign it to me.

**Comment by evrenkaraarslan** [comment]
I created PR for this issue, here is the link [#5912](https://github.com/reactjs/react.dev/pull/5912)

**Comment by Sukrittt** [comment]
Okay, I'll close the issue.
