### ISSUE TITLE
e.stopPropagation() and dropdown

### ISSUE THREAD

**Issue by peipei818** [facebook/react#26600]
React version:16->17.0.0

#### The e.stopPropagation() event will not affect child elements in child elements in V16, but it will affect child elements in child elements in V17.

Link to code example:
```
<Navbar.Collapse onClick={()=>setCollapseOpen(false)}>
   <div. onClick={(e) => e.stopPropagation()}>
       <Nav>
            <NavDropdown>...</NavDropdown>
            <NavDropdown>...</NavDropdown>
       </Nav>
   </div>
</Navbar.Collapse>
```

## The current behavior
After upgrading to version 17, `<NavDropdown>` cannot autoClose.

## The expected behavior
The innermost`<NavDropdown>` is not affected by e.stopPropagation() event.

How to fix it?

**Comment by peipei818** [comment]
how to fix it?

**Comment by urmybestfriend** [comment]
You can make another wrapper class

**Comment by d8corp** [comment]
I have a problem, think it relates to the issue.

I expect to get "SUCCESS??????????" alert message, but it's not happening.

```typescript jsx
import { useEffect, useRef } from "react";
import "./styles.css";

export default function App() {
  const root = useRef<HTMLDivElement>()

  useEffect(() => {
    const div = root.current

    if (div) {
      const listener = (e: Event) => {
        e.stopPropagation()
      }
  
      div.addEventListener('click', listener)
  
      return () => {
        div.removeEventListener('click', listener)
      }
    }
  }, [])

  const handleClick = () => {
    alert('SUCCESS??????????')
  }

  return (
    <div ref={root as any} className="App">
      <button onClick={handleClick}>Click me</button>
    </div>
  );
}

```

https://codesandbox.io/s/blissful-architecture-9kdnqn
