### ISSUE TITLE
Bug: 打包后报错

### ISSUE THREAD

**Issue by guoqirong** [facebook/react#26607]
React version: 18.2.0

## Steps To Reproduce

1.react react-deme 18.2.0
2. vite 4.2.1 @vitejs/plugin-react 3.1.0

peError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')
  react-dom-0d980a60.js:9:5345

**Comment by shixiaobang** [comment]
It doesn't look like this bug report has enough info to reproduce it.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by onukwilip** [comment]
Please can you provide more information on the bug?

**Comment by guoqirong** [comment]
demo 代码仓库

**Comment by guoqirong** [comment]
这个有处理方案了吗？

**Comment by sereinof** [comment]
你这……

**Comment by guoqirong** [comment]
https://github.com/alibaba/x-render/issues/1207
已有解决方案，是有组件不支持vite静态资源分包打包配置导致
