### ISSUE TITLE
Bug: Text in Docs

### ISSUE THREAD

**Issue by richard-nmp98** [facebook/react#26614]
## [Docs ](https://vi.reactjs.org/docs/create-a-new-react-app.html)
<img width="948" alt="Screenshot 2023-04-13 at 13 43 22" src="https://user-images.githubusercontent.com/94730056/231676655-d32e0304-7ce3-4c57-a1bc-d3435393c301.png">

**Comment by sophiebits** [comment]
I’ve refiled this at https://github.com/reactjs/vi.reactjs.org/issues/340.
