### ISSUE TITLE
Blank screen Issue - Due to old build file

### ISSUE THREAD

**Issue by arpitjain-in** [facebook/react#26618]
Hi Guys,

Since 15 days, Me and my team trying to investigate one issue with react script 5.0.1 and react 17.0.2. 
Issue is out of the 10 times, 1 or 2 times end user observe completely blank screen (white screen). After doing deep investigation, we got to know that sometime our previous build file i.e. main.js being delivered to client browser which is not valid anymore(as new build already promoted).

How to make sure that previous build bundle file shouldn't be transferred to end user.

Explanation of issue with example:-

Previous build bundle file name. - main.123.js
Current build bundle file name - main.456.js.

Sometime user get main.123.js which is old bundle file and this result in showing white screen to user's browsers.

Kindly help. We really stuck on this.

TIA.

**Comment by sophiebits** [comment]
This wouldn’t be a bug in React itself so this isn’t the correct issue tracker. It would depend on things like how your server is configured to cache files. See https://react.dev/community for other community resources where someone may be able to help (though you’ll almost certainly need to include more details).
