### ISSUE TITLE
_renderValidatedComponent method hides exceptions

### ISSUE THREAD

**Issue by edbo** [facebook/react#2665]
Hi,

We've stumbled across this code block that causes exceptions to be hidden:

https://github.com/facebook/react/blob/master/src/core/ReactCompositeComponent.js#L838

Is there a good reason to catch all exceptions in the block and tidy it up with the finally without re-throwing the exception? This is generally considered fairly bad practice without a good reason and certainly has made debugging applications more difficult for us.

If there is a valid reason it would at least be a good idea to have a debug mode that would re-throw the exception should there be a problem here.

We're happy to supply a pull request if there was some direction as to what the correct approach here should be.

Thanks

**Comment by leoselig** [comment]
What @spicyj stated is obviously correct
However, we are experiencing the same issue (silently caught exceptions) and ended up thinking it was relatred to `_renderValidatedComponent` as well
@edbo Did you find the issue and came up with a solution?

**Comment by ash14** [comment]
@leoselig are you using lodash? It seems that errors are getting eaten when they occur within a `_.each` callback.

My workaround was to monkey patch a `catch (e) { debugger; }` after the `try {}` block...

**Comment by leoselig** [comment]
@ash14 
I am using lodash but I could not trace it down to be an issue related to it
Now I think it might be due to what I sea as a general design flaw in the q promise library we are using (see https://github.com/kriskowal/q/issues/612)

**Comment by ash14** [comment]
@leoselig ah yes using `.done()` at the end of the promise chain propagates errors nicely :+1:

**Comment by leoselig** [comment]
@ash14
That helped me to find this piece in the q docs:

"The Golden Rule of done vs. then usage is: either return your promise to someone else, or if the chain ends with you, call done to terminate it."

That totally explains the silent catch, thanks! :)

**Comment by juliankrispel** [comment]
I'm running into this issue using recompose here's an example:

```
const ThrowSomething = compose(
  connect(({ client }) => ({ client })),
  branch(
    ({ client }) => client.get('id') !== undefined,
    withProps(() => {
      throw new Error('BOOM BOOM BOOM');
      return {};
    }),
    renderNothing
  )
)(() => (
  <div></div>
));
```
the above error will is apparently swallowed by the this try finally block...

cc @acdlite

**Comment by gaearon** [comment]
No, try/finally block cannot possibly swallow exceptions. Most likely you have your own try/catch on the calling code, or you catch() React errors in a Promise handler, which is a common mistake.

**Comment by juliankrispel** [comment]
@gaearon you're right :) our mistake
