### ISSUE TITLE
ReactJS 404 Error on Page Reload in production

### ISSUE THREAD

**Issue by mm0hammadi** [facebook/react#26669]
when make a production build of your ReactJS application. when refresh page.
the webserver doesn’t find any file with that name. In that case, a 404 error message is returned to the user.
How can I fix this problem?

Error text:

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

How can I fix it?

**Comment by JonnyBurger** [comment]
This is not a React problem but if your single page app is not configured correctly. See https://oliverjam.es/articles/avoid-spa-404 for an explanation of the problem.

**Comment by mm0hammadi** [comment]
I configured the web server settings in production. But I probably thought that the problem is with the routes of the project.

**Comment by mm0hammadi** [comment]
I found the solution to this problem. I leave this link for others 

https://dev.to/sumitkharche/how-to-deploy-react-application-on-iis-server-1ied

**Comment by Onkar-Kulkarni-6143** [comment]
@mm0hammadi : The link given is doesn't exist anymore.
Could you please share the web.config file which helped you to resolve issue

**Comment by Max7oo** [comment]
> @mm0hammadi : The link given is doesn't exist anymore. Could you please share the web.config file which helped you to resolve issue

The link works for me, but it does not fix my problem. Here's the code anyway:

<?xml version="1.0"?>
<configuration>
 <system.webServer>
 <rewrite>
 <rules>
 <rule name="React Routes" stopProcessing="true">
 <match url=".*" />
 <conditions logicalGrouping="MatchAll">
 <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
 <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
 <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
 </conditions>
 <action type="Rewrite" url="/" />
 </rule>
 </rules>
 </rewrite>
 </system.webServer>
</configuration>

**Comment by mm0hammadi** [comment]
> the web server settings in production. But I probably thought that the problem is with the routes of the projec

thanks

**Comment by LakshanRukantha** [comment]
If you are using ```Vercel``` just create ```vercel.json``` file in your project root level and add this code

```
{
  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]
}
```

**Comment by tejas-mn-alt** [comment]
@LakshanRukantha Thanks fixed the issue for me
