### ISSUE TITLE
Strange componentWillReceiveProps behaviour

### ISSUE THREAD

**Issue by AndrewGrachov** [facebook/react#2666]
screenshot -
https://yadi.sk/i/l90baQ8QdBTnW

thing is, props.selected is undefined if type in console by hand, but chrome console suggest(e.g. type sel, then arrow-right) shows proper 'node18n' value.
```
hasOwnProperty 
```
condition fails.

This thing is blowing my mind. I suggest something wrong with getters/setters let me know if you know teh root of teh problem

**Comment by jimfb** [comment]
Unconfirmed for nearly a year, closing this out.  Please open a new issue with a reproducible testcase if you believe this bug still exists.
