### ISSUE TITLE
Bug: React Dev tools blocks form submission with external API script.

### ISSUE THREAD

**Issue by connorroane** [facebook/react#26662]
This may be exclusively an issue with Marketo web API and its methods but I spent 4 days trying everything to get a form to submit, watching the network tab to confirm that a post request to an endpoint was made onSubmit. I finally decided to disable React Dev Tools in Chrome after noticing the form submitted in Safari. At long last the submit worked. Any idea what in particular with devTools would have caused this?

### Current Behavior
`MktoForms2.submit()` never fires. Every other MktoForms2 method seems to work but this one does not. If I close the inspector tab or disable React dev tools it does

### Expected Behavior
`MktoForms2.submit()` should send a post request with form data to save2 regardless of the dev window and its extensions.

**Comment by Rbcoder1** [comment]
I Understand What your are Say.
Can I Try To Fix It. I Just Debug The Code First Then Try Send Some Request .

If I Am Not Wrong This Bug Is In **Browser Extension** it mean in this package **react-devtools-extensions**

**Comment by gaearon** [comment]
Sorry, we don't know what Marketo is, and we can't help without a reproducing case.
