### ISSUE TITLE
CONTRIBUTING.md new URL

### ISSUE THREAD

**Issue by akirataguchi115** [facebook/react#26676]
Our CONTRIBUTING.md refers the legacy site: https://github.com/facebook/react/blob/main/CONTRIBUTING.md 

I couldn't find the new how-to-contribute site from react.dev. If someone know the url for that one, should we update the CONTRIBUTING.md?

**Comment by JustusW** [comment]
I was looking for up to date information to understand Reacts Control Flow better and that's where I'd expect to find that information. Sadly the rabbit hole ends here for now :(

**Comment by kristof1345** [comment]
Could I work in this issue?

**Comment by akirataguchi115** [comment]
@kristof1345 @ayushgupta9906 you're free to make a pr if you find a solution

**Comment by tusharkashyap11** [comment]
I only found this link : https://github.com/facebook/react/blob/main/CODE_OF_CONDUCT.md
but there is no how to contribute section in this like in the legacy site.

**Comment by tusharkashyap11** [comment]
Should I make a pr for this to redirect to this link ?

> I only found this link : https://github.com/facebook/react/blob/main/CODE_OF_CONDUCT.md but there is no how to contribute section in this like in the legacy site.

**Comment by akirataguchi115** [comment]
Sorry for the late response, @tusharkashyap11 ! To my understanding CODE_OF_CONDUCT.md is different from CONTRIBUTING.md The former describes the expected behavior of the contributors and the latter describes what type of contributions are welcome from the contributors.

As such there's not much need to open a PR just yet. However if you do find some material discussing CONTRIBUTING.md or something alike you're more than welcome to open a PR and link this issue to it! :octocat:

**Comment by tusharkashyap11** [comment]
@akirataguchi115 Thanks for the reply. I got your point, so I'll just look for some other material that explains CONTRIBUTE.md or similar to that.

**Comment by akirataguchi115** [comment]
The Resolution: Stale label prohibited me from leaving a comment.
