### ISSUE TITLE
Bug: Cannot download and install Dev Tools for React on Edge Browser

### ISSUE THREAD

**Issue by PranshuBansalDev** [facebook/react#26675]
React version: ALL

## Steps To Reproduce

1. Navigate here to get the dev tools - https://react.dev/learn/react-developer-tools
2. Navigate to EDGE section - https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil
3. Notice that the page does not list the extension

![image](https://user-images.githubusercontent.com/10714218/233178008-3d10ebcd-6328-45ea-9993-72ef25d1bee3.png)

## The expected behavior

Expect to be able to see the extension, download and install it

**Comment by AzamkhonKh** [comment]
same

**Comment by BOSA-YouriCatinat** [comment]
same for me, any news ?

**Comment by hmohamme** [comment]
Seems to be resolved now. 

https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil

![image](https://user-images.githubusercontent.com/61028636/234083191-d76607ff-e6ff-43e0-9976-bacf3c117618.png)
