### ISSUE TITLE
<img width="958" alt="Screen Shot 2021-12-14 at 10 37 30" src="https://user-images.githubusercontent.com/82567966/145939481-373546fd-94fd-41e6-bc55-bcd747192c7a.png">

### ISSUE THREAD

**Issue by webcyspot** [facebook/react#26686]
<img width="958" alt="Screen Shot 2021-12-14 at 10 37 30" src="https://user-images.githubusercontent.com/82567966/145939481-373546fd-94fd-41e6-bc55-bcd747192c7a.png">

_Originally posted by @Salimbek21 in https://github.com/facebook/react/issues/16225#issuecomment-993175876_

**Comment by rajatinclude** [comment]
`useContext(LanguageContext)` It will return a object, you can't destructure changeLanguage becasue It is undefined, It has mainly two property Provider and Consumer.

**Comment by MOHAMMEDBAHRUDEEN** [comment]
Remove 's' in https
