### ISSUE TITLE
Bug: Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by vinhta916** [facebook/react#26691]
React version: 18.2.0

## Steps To Reproduce

1. Building react

## The current behavior
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)

## The expected behavior
Ability to build

**Comment by KSANTHOSH200** [comment]
You may not have webpack.config.js file or 'react-scripts' in package.json dependencies.

**Comment by vinhta916** [comment]
> You may not have webpack.config.js file or 'react-scripts' in package.json dependencies.

I do have react-scripts version 4.0.1

**Comment by vinhta916** [comment]
Found the issue had to rebuild everything with latest packages. Fixed

**Comment by Marina-Mascarenhas** [comment]
> Found the issue had to rebuild everything with latest packages. Fixed

The documentation says, it supports react 16+.
I have react version greater than 16 
my react -scripts is 4.0.3. which version did you update the react-scripts to?

**Comment by shubham-qw** [comment]
just go to the file where it is showing error and instead  of importing react component using {componentName}, use import React from "react" and then use components this way React.componentName

**Comment by jahanzaibtariq** [comment]
Thanks @shubham-qw ,

It's resolved by romove the {componentName} and used by React.{componentName}

**Comment by Buddimal-Liyanapathirana** [comment]
I am facing the same issue . But the issue lies in a node module "./node_modules/react-use-set/dist/index.mjs"
