### ISSUE TITLE
Bug: Type 'string | TrustedHTML' is not assignable to type 'string'

### ISSUE THREAD

**Issue by jonathborg** [facebook/react#26694]
![image](https://user-images.githubusercontent.com/48167235/233700790-3b4e5bf8-a347-4096-8178-3e0fa264a254.png)

```tsx
export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
    children?: ReactNode;
};

export function Button(props: ButtonProps) {
    return (
        <button {...props}>
            {props.children}
        </button>
    );
}
```

React version: 18.2.0
@types/react version: 18.0.37

## Steps To Reproduce

1. Create a simple button component
2. Try to type the props

My solution:
```tsx
export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & VariantProps<typeof button> & {
    children?: ReactNode;
    dangerouslySetInnerHTML?: {
         __html: string;
    };
};
```

**Comment by eps1lon** [comment]
It sounds like you have multiple versions of `@types/react` installed. Make sure you only have a single version installed either by using [Yarn `resolutions`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) or [NPM `overrides`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides).

Using latest types and only a single version, the original code works without type issues: [Playground Link](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAbwEoFMCGBjGA5CATFAGjgCEBXGGCAOwAkAVAWQBkBBSqYAIwpQGcAvnABmUCCDgByKOiySAsACglKAB6RYcGAE8wKUhSrUACmLB84AXgOUaDFuxiceMfgB57zcreoBRADYoICjUMAB8cABkiEpwcXAYABbA-ngy1AD8AFxwqJg4+CgA3EoCJcqKahrwwmTUWMA0NkYAFGBmfDneRqYQ5gCUMYrxcDIwZFDUcC2xI-FuLkaIAHSr7X2CYbNzcwjr5stJKWkhAttzbgD0izRbw-H95QJAA)

**Comment by jonathborg** [comment]
That's right. Thanks for your time and sorry for the lazy issue by me.

**Comment by kimbaudi** [comment]
i ran into the same issue and deleting yarn.lock and reinstalling resolved the issue
