### ISSUE TITLE
Bug: _internalRoot is undefined when calling destructured render method of Root

### ISSUE THREAD

**Issue by jroru** [facebook/react#26699]
React version: 18.2.0

## The current behavior
```tsx
const { render } = createRoot(container);
render(<></>);
```
Results in:
`TypeError: Cannot read properties of undefined (reading '_internalRoot')`

(Coming from [this line of code](https://github.com/facebook/react/blob/fdad813ac765e901e2957b8d36fba87e5504e5f4/packages/react-dom/src/client/ReactDOMRoot.js#L103))

Whereas it works fine when destructuring is avoided:

```tsx
const root = createRoot(container);
root.render(<></>);
```

## The expected behavior

Destructuring a method from `Root` should not cause any issue

**Comment by gaearon** [comment]
That's not supported — same as `const { push } = []; push(42)`
