### ISSUE TITLE
[DevTools Bug]: can not build react devtools for local development, instructions lead to error

### ISSUE THREAD

**Issue by yanlingwang23** [facebook/react#26697]
### Website or app

https://github.com/facebook/react/tree/main/packages/react-devtools-extensions

### Repro steps

Follow the instructions here to build local version of react devtools extension: https://github.com/facebook/react/tree/main/packages/react-devtools-extensions

```
git clone https://github.com/facebook/react.git 
cd react
yarn install
yarn build-for-devtools
```

Stuck on this step everytime `yarn build-for-devtools`:
```
D:\Other\react\node_modules\flow-parser\flow_parser.js:807
throw a}function
^

Error: SignedSource.signFile(...): Cannot sign file without token: <<SignedSource::*O*zOeWoEQle#+L!plEphiEmie@IsG>>
    at Object.<anonymous> (D:\Other\react\node_modules\signedsource\index.js:20:28)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (D:\Other\react\scripts\rollup\packaging.js:18:37)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
```

Is there anything else I need to set up in order to make this work?

### How often does this bug happen?

Every time

**Comment by markerikson** [comment]
Confirmed, I'm seeing this myself as of https://github.com/facebook/react/pull/26616 .

**Comment by rubennorte** [comment]
Thanks @yanlingwang23 and @markerikson for reporting this issue introduced in #26616. Working on a fix now.

**Comment by rubennorte** [comment]
This should be solve now. Please reopen if you continue seeing issues in "main" after this merge.

**Comment by Biki-das** [comment]
@yanlingwang23 could you try to build the react devtools extension and see if it builds or not?

**Comment by gaearon** [comment]
@Biki-das This screenshot doesn't show what the actual error is. Can you track it down?

**Comment by Biki-das** [comment]
> @Biki-das This screenshot doesn't show what the actual error is. Can you track it down?

![Windows PowerShell 4_28_2023 11_33_07 PM](https://user-images.githubusercontent.com/72331432/235220923-1c4bf8d2-93d8-4f22-bd0c-43fd59f9359d.png)
@gaearon this is the error currently I am getting,i have installed the necessary dependencies already as mentioned in the readme!

**Comment by yanlingwang23** [comment]
I'm still having trouble in step `yarn build-for-devtools`, saw the same issue as @Biki-das 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/108438266/235231543-4369b235-338c-4a88-98a9-ad3610054019.png">

**Comment by Biki-das** [comment]
@gaearon any updates on this one!
