### ISSUE TITLE
Changing shouldComponentUpdate SpecPolicy

### ISSUE THREAD

**Issue by tgriesser** [facebook/react#2669]
I wanted to propose changing `shouldComponentUpdate` from a `DEFINE_ONCE` to a spec that might be termed `DEFINE_MANY_ALL`. 

The rationale here is that sometimes you may know that it's more efficient to skip the `shouldComponentUpdate` for some reason in a component, or that a mixin may be able to define whether it should be able to skip updating based on it's own knowledge of props/state/context, but that might not hold true when combined with other components of an app.

So my thought is `shouldComponentUpdate` should be changed to a `DEFINE_MANY`, where `ALL` of the return values must return false for the update to skip. If any return true, it will have the same behavior as the default and update.

**Comment by rektide** [comment]
just look for shouldComponentUpdate*, evaluate each and OR them together. done.

**Comment by Tvaroh** [comment]
+1

**Comment by gaearon** [comment]
For what it’s worth I retract my +1 on this before. I’ve written some pretty terrible code with smart mixins and I no longer use them. Any kind of merging behavior here encourages components keeping implicit state in mixins, and this turned out to be a trouble to maintain in the app I worked on.

**Comment by tgriesser** [comment]
Yep, I agree with @gaearon
