### ISSUE TITLE
Bug: link order been messed up after upgrade to next version

### ISSUE THREAD

**Issue by lili21** [facebook/react#26705]
the link order inside head element has been messed up after upgrade to next version

React version: 18.3.0-next-c8369527e-20230420

## Steps To Reproduce

1. clone the code example
2. follow the readme

Link to code example:

https://github.com/lili21/remix-react_next

## The current behavior
the link order is

![image](https://user-images.githubusercontent.com/4456380/233836084-9d6bd38f-da76-447a-8c30-9d8fc8aaffd5.png)

## The expected behavior

the link order should be 

![image](https://user-images.githubusercontent.com/4456380/233836130-68ef9718-ec53-4cf4-9de4-5c7b1b1692b0.png)

**Comment by lili21** [comment]
the link order is important cause we want to preload some critical image to decrease the LCP time

**Comment by lili21** [comment]
downgrade the version to 18.2.0, and the order is expected.

**Comment by SamarthBagga** [comment]
Hi @lili21 , i am new to open source could i get a chance to work on this issue?

**Comment by gaearon** [comment]
When you say "messed up" do you mean some tags or missing? Or can you be more specific?

**Comment by lili21** [comment]
the order of links is not expected.

**Comment by lili21** [comment]
those `<link rel=modulepreload />` tags have been moved into `head`, which should be in `body`.

**Comment by lili21** [comment]
it's hurting our performance. you can check the similar problem with https://github.com/vitejs/vite/issues/5120.

after upgrade to react@canary version, we see the same effect in production, the FCP increase about 1s. because all the `<link rel=modulepreload />` have been moved into head.

**Comment by rossipedia** [comment]
@gaearon `<link rel="modulepreload" />` tags are being moved to _before_ `<link rel="stylesheet" />` tags. Since stylesheets are blocking, if you have a decent amount of modulepreloads then you end up delaying the initial render by however long it takes the browser to free up a network connection to fetch the stylesheet due to all the in-flight preloads. 

I think modulepreloads should ideally be moved to _after_ the last stylesheet link tag, which would let the browser fetch the blocking CSS as fast as possible before attempting to preload any JS modules, which can occur asynchronously and won't block the initial paint.

**Comment by jrestall** [comment]
Ideally React fixes this by automatically prioritizing stylesheets over modulepreloads and a workaround isn't needed.

However to move the stylesheets above the modulepreloads in the meantime, you can add a `precedence: 'high'` attribute on stylesheet links from the Remix links function. I don't think this is documented but I learnt it from the React [unit tests](https://github.com/facebook/react/blob/7f6201889e8e628eeb53e05d8850ddffa3c2e74a/packages/react-dom/src/__tests__/ReactDOMFizzStaticBrowser-test.js#L717).

e.g.
```ts
  export const links: LinksFunction = () => [
    { rel: 'stylesheet', href: appStylesHref, precedence: 'high' },
  ];
```

Will result in the stylesheet link being placed at the top of the head element, above the modulepreloads.

```html
  <head>
      <meta charSet="utf-8"/>
      <meta name="viewport" content="width=device-width,initial-scale=1"/>
      <link rel="stylesheet" href="/build/_assets/app-B5PUCUEH.css" data-precedence="high"/>
      <title>New Remix App</title>
      <meta name="description" content="Welcome to Remix!"/>
      <link rel="modulepreload" href="/build/entry.client-4MXBZIKC.js"/>
      <link rel="modulepreload" href="/build/_shared/chunk-PNG5AS42.js"/>
      <link rel="modulepreload" href="/build/root-XKG6C447.js"/>
      <link rel="modulepreload" href="/build/routes/_index-T377ZUPD.js"/>
  </head>
```
