### ISSUE TITLE
Bug: The prs welcome icon navigates to a webpage from the old docs

### ISSUE THREAD

**Issue by itaim18** [facebook/react#26703]
React version: The repo

## Steps To Reproduce

1. Click the prs welcome icon

## The current behavior
It navigates you to a page from the old docs

## The expected behavior

Suggestion: A page from the react.dev docs.
Gladly would check if one exists or help make a page as such

React will stay the #1 open source🚀

**Comment by saadsawash** [comment]
A corresponding page doesn't yet exists on the new react.dev website.
I've issued a PR to that repo with a new page, once it gets merged, I'll try to fix this as well.
