### ISSUE TITLE
Bug: 17.0.2 state value not change UI

### ISSUE THREAD

**Issue by heart-er** [facebook/react#26706]
Help: Does react 17.x have a minimum android version support?

React version:
17.0.2

## Steps To Reproduce
1.  UI not change but the value changed. 
2. It only occurs on some models of android 7.x/8.x, and it will also occur in lower versions

## The current behavior
UI not change but the value changed. 

## The expected behavior
UI will change with the value changed.

**Comment by Abayomzee** [comment]
Hi,

Are you using a class or functional component ?

**Comment by rakshithcgowda** [comment]
@heart-er  Where to pull the code file to Vs code

**Comment by gaearon** [comment]
Sorry, but we can't help without a reproducing case. We also don't provide support for old majors of React.

**Comment by rakshithcgowda** [comment]
@gaearon basically I cloned it react->available to my machine ->then what I need to do iam not getting like I read entire documentation but I cannot figure it out
