### ISSUE TITLE
Bug: 官网滚动条遮挡标题

### ISSUE THREAD

**Issue by Over-reaction** [facebook/react#26710]
当我查看react官方文档的时候发现了这个问题，不知道有没有人提到过

当我点击学习react区域的左侧菜单栏的时候会出现一条不可思议的滚动条 遮挡了右侧的标题区域
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/88490404/233965436-7b2995a8-d739-4b1e-9982-822ab1bc5720.png">
我发现这个元素已经从父级的宽度溢出  打开控制台发现是写了一个width属性导致的
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/88490404/233966631-6e892cc6-28c1-4298-8423-c9a658ca2ef8.png">
去掉的话可以拒绝这个问题
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/88490404/233967191-a1cb9b24-ce18-4829-96d9-9bbaef258e58.png">

**Comment by eqpoqpe** [comment]
try this one https://github.com/reactjs/react.dev

**Comment by lili21** [comment]
https://github.com/reactjs/zh-hans.react.dev
文档问题在这个仓库反馈
