### ISSUE TITLE
[DevTools Bug]: Unable to build the extension locally

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#26723]
### Website or app

N/A

### Repro steps

I am trying to build the chrome extension for react dev tools locally to test changes as i am looking forward to fix this issue https://github.com/facebook/react/issues/26200, but there seem to be some error with the packages! looking forward to get some help
![Windows PowerShell 4_25_2023 9_44_03 AM](https://user-images.githubusercontent.com/72331432/234173125-657274ae-9d5b-41b6-bf34-ed148625f73f.png)

### How often does this bug happen?

Every time

**Comment by markerikson** [comment]
This is likely due to #26697 breaking the `yarn build-for-devtools` command.  When that build step fails, there's no top-level `build` folder, and the extension build commands can't find the React packages they need.

**Comment by Biki-das** [comment]
Thanks for the feedback! Need to wait for the fix before i proceed further!
