### ISSUE TITLE
Bug: Where is react.mjs download for browser?

### ISSUE THREAD

**Issue by manake** [facebook/react#26728]
What I want to do is:
1. Go to https://github.com/facebook/react/ to /dist/ folder and download react.mjs and react-dom.mjs.
2. Create a *.html file like this:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link href="style.css" rel="stylesheet">
    </head>
    <body>

        <script type="module">
            import * as React from './react.mjs';

            let element = React.createElement('div');
        </script>
    </body>
</html>
```

This is ridiculous that I can't just do this because there is no /dist/ folder in this repo nor react.mjs available anywhere.

The `npm i react react-dom` version doesn't have a JS browser module and the only module I found was on a CDN but it wasn't easily copiable from there because I had to manually fix import paths.

**Comment by MeastroZI** [comment]
I  am the beginner  , can anyone tell me how can i run the my changes on react source code ?

**Comment by markerikson** [comment]
Per #11503 , React does not currently ship any ES module builds.

Some CDNs do automatic conversion of React for use as an ESM script tag - you can try using that:

https://esm.sh/#docs

**Comment by kushhingol** [comment]
@markerikson that's a great suggestion

**Comment by kushhingol** [comment]
Hi @MeastroZI, I found something in the readme file which can help you with further investigation for your usecase

<img width="699" alt="image" src="https://user-images.githubusercontent.com/46898435/235234109-54f39594-e19b-4d31-adc0-8cd2666840ab.png">

https://legacy.reactjs.org/docs/cdn-links.html

**Comment by manake** [comment]
Thanks, but I can't use a CDN for any libraries because I often work offline.

**Comment by Bibooo25730** [comment]
https://github.com/Bibooo25730/Browserify-Gulp-Babelify-React

您可以使用我这个来转换 jsx，不过是手动的

**Comment by j4acks0n** [comment]
> Thanks, but I can't use a CDN for any libraries because I often work offline.

Well It Depends What Editor/Ide You Use.....
Can I Know What Ide/Editor You Use? 
Maybe I Can Help You😊

**Comment by gaearon** [comment]
We don't currently provide a purely ESM build out of the box, so you will have to build it yourself the same way that these CDNs do. We don't think realistically this is a great way to consume React today anyway, since it's not very usable without import maps, and import maps have barely landed across browsers. We'll revisit this in the future.

**Comment by manake** [comment]
@Bibooo25730 Thanks.

@j4acks0n Thanks. VSCode. I downloaded mjs version from a CDN and it works fine for me for now.

@gaearon
Import maps are present in all major browsers already and aren't going anywhere so how "barely landed" is a problem in any way? 
That's a very weird argument.
Anyway, it's possible to export React as a single react.mjs without using import maps.
IMO, it's better to have /dist/ folder and a installation notice (e.g. "mjs is not recommended but available") than no /dist/ folder.

**Comment by xiaoqiang1999** [comment]
> 根据 #11503 ，React 目前没有发布任何 ES 模块构建。
> 
> 一些 CDN 会自动转换 React 以用作 ESM 脚本标签 - 您可以尝试使用它：
> 
> https://esm.sh/#docs

Thank! It works very well !
