### ISSUE TITLE
Reset button under the code playground

### ISSUE THREAD

**Issue by RedProgamer** [facebook/react#26725]
There could be **Reset** button beside the **Show mode** button, which will revert back to the original code.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/59522492/234210422-db86031a-2e4f-4be0-b3b2-ffae5013f193.png">

**Comment by kristof1345** [comment]
I think there is already one, but at the top of the code box.

**Comment by Mayank1170** [comment]
Hey @RedProgamer can you please tell me what is code playground here and how can i get it ?

**Comment by RedProgamer** [comment]
@kristof1345 didn't notice it, thanks for pointing it out.
I am closing the issue, god I feel so stupid.
