### ISSUE TITLE
First issue Bug: 

### ISSUE THREAD

**Issue by Rouaa-Belhaj-Ali** [facebook/react#26733]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by kushhingol** [comment]
Requesting for a closure for the bug ticket @Rouaa-Belhaj-Ali 😊

**Comment by Rouaa-Belhaj-Ali** [comment]
I apologize for any inconvenience, but I'm unable to start or finish work on this repository at the moment.
conflicting priorities ! 
my bad  I'll make sure to prioritize it as soon as I'm able to. Please let me know !
