### ISSUE TITLE
Bug: Blinking and blank situations when using createRoot to render fast scrolling in React18

### ISSUE THREAD

**Issue by shijunfeng** [facebook/react#26736]
React version:18.2.0

## Steps To Reproduce

1.Blinking and blank situations when using createRoot to render fast scrolling in React18
2.Using ReactDOM. render (, document. getElementById ('root ')) is normal

Link to code example:
https://codesandbox.io/s/cold-sea-2jt1zv

**Comment by gaearon** [comment]
You haven't provided enough details — I can't reproduce the issue and don't know what reproducing it is supposed to look like, which browsers you're using, etc.

**Comment by shijunfeng** [comment]
> You haven't provided enough details — I can't reproduce the issue and don't know what reproducing it is supposed to look like, which browsers you're using, etc.

请修改示例代码中的index.js文件，将内容修改为如下代码，拖拽右侧滚动轴观察两种代码的效果差异。
import ReactDOM from 'react-dom';
import App from "./App";
ReactDOM.render(App, document.getElementById ('root'));

**Comment by shijunfeng** [comment]
> You haven't provided enough details — I can't reproduce the issue and don't know what reproducing it is supposed to look like, which browsers you're using, etc.

Please modify the index. js file in the sample code and change the content to the following code. Drag the right scroll axis to observe the difference in the effect between the two codes.

import ReactDOM from 'react-dom';
import App from "./App";
ReactDOM.render(App, document.getElementById ('root'));

**Comment by shijunfeng** [comment]
> You haven't provided enough details — I can't reproduce the issue and don't know what reproducing it is supposed to look like, which browsers you're using, etc.

Please modify the index. js file in the sample code and change the content to the following code. Drag the right scroll axis to observe the difference in the effect between the two codes.

import ReactDOM from 'react-dom';
import App from "./App";
ReactDOM.render(<App />, document.getElementById ('root'));

**Comment by shijunfeng** [comment]
Please modify the index. js file in the sample code and change the content to the following code. Drag the right scroll axis to observe the difference in the effect between the two codes.
`import ReactDOM from 'react-dom';

import App from "./App";

ReactDOM.render(<App />, document.getElementById ('root'));`
