### ISSUE TITLE
Bug: Error: Should have a queue. This is likely a bug in React. Please file an issue.

### ISSUE THREAD

**Issue by ony3000** [facebook/react#26750]
React version: 18.2.0

## Steps To Reproduce

1. For the code example below, launch the development server and connect to http://localhost:17030/
2. Click ![Screenshot 2023-05-01 at 17 07 31](https://user-images.githubusercontent.com/8164191/235426944-3f6bccff-97ce-49c2-9d39-ecd235bde346.JPG) button.
3. Open `src/hooks/useGameContent.ts` in the code editor, uncomment line 17 and save.

Link to code example: https://github.com/ony3000/1to30/tree/error-reporting

## The current behavior
![Screenshot 2023-05-01 at 16 38 38](https://user-images.githubusercontent.com/8164191/235427767-723079bb-5491-437e-82a4-b736b33c126a.JPG)

## The expected behavior
Hot module replacement without errors.

**Comment by acdlite** [comment]
Could you try upgrading to the latest canary to see if the issue still exists?

```
"react": "18.3.0-canary-fda1f0b90-20230509",
"react-dom": "18.3.0-canary-fda1f0b90-20230509",
```

**Comment by acidfernando** [comment]
I'm also having this issue. Updating didn't work
