### ISSUE TITLE
[DevTools Bug]: React pages not being detected as using React in Incognito mode

### ISSUE THREAD

**Issue by RichDom2185** [facebook/react#26756]
### Website or app

https://opensource.fb.com

### Repro steps

It seems that with the latest update of Chrome and React DevTools, it cannot detect pages as using React on incognito. Screenshot attached below:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/34370238/235575519-8eeaa3c5-80fa-4cc4-a33d-3d2f0541f0d9.png">

* _Chrome version: 112.0.5615.137 (arm64)_
* _React DevTools version: 4.27.6 (4/20/2023)_

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Thanks for reporting, looking into this.

Can reproduce with the version 4.27.6 from Chrome web store, but unable to reproduce with a local build.
Something weird happens in incognito mode with registering content scripts for extensions, which are downloaded from store.

**Comment by jeremycourtaban** [comment]
Hello,

I have the same bug.

FYI.

OS: Ubuntu 22.04.2 LTS.

Chrome: version 112.0.5615.165 (official build) (64 bits).
React Developer Tools: version 4.27.6 (2023-04-20).
React Developer Tools description: Adds React debugging tools to the Chrome Developer Tools. Created from revision 7f8c501f6 on 4/20/2023.

Firefox: version 112.0.2 (64 bits).
React Developer Tools: version 4.27.1 (2023-05-01).
React Developer Tools description: Adds React debugging tools to the Firefox Developer Tools. Created from revision 47f63dc54 on 12/6/2022.

**Comment by Costa-iStone** [comment]
Same issue
OS: MacOs Venture 13.3.1 
React Dev Tools: version 4.27.6 (4/20/2023)
Chrome: Version 112.0.5615.137 (Official Build) (x86_64)

**Comment by Costa-iStone** [comment]
@hoxyq  This is still an issue after code changes. Removed and re-added devtools. Tested [Facebook](https://www.facebook.com/) in incognito. 
OS: MacOs Venture 13.3.1
React Dev Tools: version 4.27.6 (4/20/2023)
Chrome: Version 112.0.5615.137 (Official Build) (x86_64)

**Comment by hoxyq** [comment]
> @hoxyq This is still an issue after code changes. Removed and re-added devtools. Tested [Facebook](https://www.facebook.com/) in incognito. OS: MacOs Venture 13.3.1 React Dev Tools: version 4.27.6 (4/20/2023) Chrome: Version 112.0.5615.137 (Official Build) (x86_64)

The version, which contains this fix is not published yet. I will do a new release this week, so you should expect it to be available next week. Sorry for any inconvenience caused.
