### ISSUE TITLE
React Dev Tools not working on NextJS localhost

### ISSUE THREAD

**Issue by SRD75** [facebook/react#26757]
Troubleshooting React Dev Tools lead me to https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#the-react-tab-shows-no-components, which asks us to report issues here.

I'm running a NextJS website at  http://localhost:3000/

React dev tools > Components says:

```
Loading React Element Tree...

If this seems stuck, please follow the [troubleshooting instructions](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#the-react-tab-shows-no-components).
```

In chrome://extensions there is no "service worker (inactive)".

Chrome is at the latest version, 112.0.5615.138.

Not using preact, 

React dev tools are working on other websites.

**Comment by tony1658** [comment]
Which React version and NextJS version are you using?

Any reproducible example? Why does it work on other websites but not in this particular case?

**Comment by SRD75** [comment]
Thanks for your reply.

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```
React developer tools are working now. I can no longer reproduce the issue.
