### ISSUE TITLE
Bug: React Context weird re-rendering behavior

### ISSUE THREAD

**Issue by gmoniava** [facebook/react#26769]
React version: 18

## Steps To Reproduce

1. Just run the code in the demo

Link to code example: https://stackblitz.com/edit/react-f8rw8p?file=src%2FApp.js

## The current behavior

Prints

```
Wrapper
MySetCtxComponent
MyViewCtxComponent
```

each second.

## The expected behavior

Should print:

```
Wrapper
MyViewCtxComponent
```

each second. Because of two reasons: the optimization react uses when some element is same reference between re-renders (i.e. in this case since `props.children`, didn't change, children shouldn't re-render when parent re-renders; more [info](https://overreacted.io/before-you-memo/#solution-2-lift-content-up)), and the `ActionsContext `value hasn't changed either. So there was no reason to print `MySetCtxComponent ` isn't it?

**Comment by rakshithcgowda** [comment]
@gmoniava basically there is an bug in code do I need to edit that thing right
Because this my frist pull request

**Comment by gmoniava** [comment]
I think I found the issue, the `props.children` of `Wrapper ` does actually change in this case due to re-rendering the top parent. I will do some further testing and reopen if something.
