### ISSUE TITLE
React dev tools not working when running the application/website on incognito mode

### ISSUE THREAD

**Issue by vikram87in** [facebook/react#26766]
React dev tools not working when running the application/website on incognito mode. This page doesn’t appear to be using React. I am trying it on this url: https://www.facebook.com/virat.kohli/
Note: it works with non-incognito mode. Issue replicating on chrome and edge both

**Comment by RichDom2185** [comment]
This seems to be a duplicate of #26756.

**Comment by rajnish307** [comment]
Yes, I can confirm it is working as expected now after the fix.

**Comment by vikram87in** [comment]
@rajnish307 I think the new version is yet to be published. Will have to wait for some time, I guess

**Comment by hoxyq** [comment]
Expected to be fixed in v4.27.7.
