### ISSUE TITLE
Bug: I dunno whether its a bug or a default feature of React, under Sources tab of chrome dev tools, complete source code of my frontend project is getting exposed whether I run it locally or in production. I researched on this and tried many methods but it's still visible. 

### ISSUE THREAD

**Issue by govindmaddala** [facebook/react#26785]
React version:
![Screenshot (1372)](https://user-images.githubusercontent.com/99980734/236600167-0fb30f91-3c51-498d-a0fe-4cc55dc5fa7b.png)

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by hood** [comment]
What do you expect for front-end application that runs on a browser?
Anyway, you could set-up minification and obfuscation in your build process if that suits your needs.

**Comment by gmaxlev** [comment]
It looks like you are using source maps

**Comment by tony1658** [comment]
You cannot hide client side code. Minification and obfuscation makes reverse engineering harder but not impossible. 

If you truly want to hide the implementation details you'll need to render the pages on the backend with something like React Server Components.

**Comment by gaearon** [comment]
These are "source maps" — the way to turn them off developers on which tool you use for bundling. Please consult its documentation. However, note that you can't completely hide the source in principle since the browser has to execute it.
