### ISSUE TITLE
React Component not rendering

### ISSUE THREAD

**Issue by rishabhdasu** [facebook/react#26782]
Hi,

My React app is not rendering any elements on the browser.

Error: This page doesn’t appear to be using React.

**Comment by Ankitupadhyay056** [comment]
Hi rishabh , atleast share some part of code .

**Comment by ravi12344321** [comment]
hi rishabh share source code , and 
check console

**Comment by dhruv8433** [comment]
maybe...

-> The version of React on the page is not compatible with the tool or extension: If the version of React on the page is too old or too new for the tool or extension, it may not be able to detect or work with the React components on the page.

-> There is a conflict with other JavaScript libraries or frameworks on the page: If there are other JavaScript libraries or frameworks being used on the page alongside React, there may be conflicts that prevent the tool or extension from detecting React properly.

**Comment by Ranjana993** [comment]
Can you share your code of index.js and appjs ??

**Comment by rishabhdasu** [comment]
Hi All,

I was able to render it by recreating the React app.

> maybe...
> 
> -> The version of React on the page is not compatible with the tool or extension: If the version of React on the page is too old or too new for the tool or extension, it may not be able to detect or work with the React components on the page.
> 
> -> There is a conflict with other JavaScript libraries or frameworks on the page: If there are other JavaScript libraries or frameworks being used on the page alongside React, there may be conflicts that prevent the tool or extension from detecting React properly.

**Comment by rishabhdasu** [comment]
Hi All,

Actually, I was able to render it by recreating the React app. I guess I was not importing react in the index file.

**Comment by dhruv8433** [comment]
@rishabhdasu import your App into index

**Comment by KaramveerSidhu** [comment]
@rishabhdasu Curious to know, how were you creating your react app?

**Comment by rishabhdasu** [comment]
Hi @KaramveerSidhu , obviously by using create react app

**Comment by soyjuanmacias** [comment]
> Hi @KaramveerSidhu , obviously by using create react app

Why obviusly?

**Comment by rishabhdasu** [comment]
@soyjuanmacias 

I guess because it is the most commonly used, popular and the easiest way to create the app.

Although I agree that there are more popular methods and frameworks to create the react app but I believe create react app is the most preferred way.
