### ISSUE TITLE
[DevTools Bug] Cannot remove node "226752" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by jayavel-testsigma** [facebook/react#26793]
### Website or app

https://travel.testsigma.com/

### Repro steps

https://travel.testsigma.com/

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.27.6-7f8c501f6

### Error message (automated)

Cannot remove node "226752" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28710:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26606:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26775:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:57029:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by YardWill** [comment]
Same to me. Both in Edge Version 4.27.7 (5/7/2023) and Chrome 4.27.6 (4/20/2023)

**Comment by YardWill** [comment]
It seems that the issue was caused by this PR(https://github.com/facebook/react/pull/26615). I reverted the version back to 4.27.5 and it worked.

**Comment by pitter2416** [comment]
I also encountered the same problem, did you solve it?  https://www.ectcm.com

**Comment by YardWill** [comment]
> 

revert extensions version to 4.27.5

**Comment by jrbartola** [comment]
Also seeing this problem- the extension is unusable now. Reverting it seems like more effort than it's worth :/

**Comment by haniffaraz** [comment]
Also came across this issue and had to remove the `4.27.6` version and then added `4.27.7` version. This seems to have fixed the related issues.

**Comment by hoxyq** [comment]
Hey, can anyone try to reproduce this with version 4.27.8 installed?

**Comment by literalpie** [comment]
I did some profiling in react dev tools with 4.27.8 today, and did not have any issues. 

I wouldn't take this as 100% confirmation that the issue is fixed though, since I wasn't able to reproduce the issue consistently before (my previous comment was premature/wrong).

**Comment by hoxyq** [comment]
> I did some profiling in react dev tools with 4.27.8 today, and did not have any issues.
> 
> I wouldn't take this as 100% confirmation that the issue is fixed though, since I wasn't able to reproduce the issue consistently before (my previous comment was premature/wrong).

Sure, thanks for checking.

Currently working on stabilizing the extension behaviour. Keeping this issue open, as this problem is hardly reproducible, would be nice if someone can come up with a reproducible example.

**Comment by uaeio** [comment]
I have such error when reloading page during profile:

```
Uncaught Error: Cannot remove node "370" because no matching node was found in the Store.
```

**Comment by Suvikr23** [comment]
Faced this exact same error while profiling:

`Uncaught Error: Cannot remove node "3755" because no matching node was found in the Store.`
