### ISSUE TITLE
Props passed to components in an array are never updated

### ISSUE THREAD

**Issue by imageck** [facebook/react#26800]
In a scenario where a component is rendered multiple times (e.g. custom form controls), it is convenient to create an array and add new ones to it like so:
```jsx
  function addItemField() {
    ...
        setItemFields([
          ...itemFields,
          <ItemField id={id}
                     key={id}
                     types={types}
                     onDelete={deleteItemField}
                     setTypes={setTypes}
                     itemFields={itemFields}
                     initialType={type} />
        ]);
    ...
  }
```
Then, render them all by simply referencing the state variable:
```jsx
{itemFields}
```
However, when the state in the parent is modified, the props passed to each individual `ItemField` remain stuck on initial values:
![image](https://github.com/facebook/react/assets/101450105/2772216c-8cb6-434e-9fdf-babb175c36ac)

While the state in the parent itself is updated as expected:
```json
{"num":[1683725936912,1683725938108],"str":[],"text":[],"date":[],"check":[]}
```

The workaround (with its own drawbacks) is to render them inline with a usual call to `map()`:
```jsx
// not the most correct way to do it but good enough for demonstration purposes
{itemFields.map(f => <ItemField { ...f.props } types={types} />)}
```
After that, the `types` prop is always updated:
```json
{"num":[1683726414233],"str":[1683726415434],"text":[],"date":[],"check":[]}
```

React version:
18.2.0

## Steps To Reproduce

1. Set state in parent.
2. Store a list of components to render in an array and pass the state as a prop.
3. Render the list by referencing the state variable.
4. Inspect the components in React DevTools.

Link to code example:
https://stackblitz.com/edit/nextjs-m9un8n?file=pages/index.js

## The current behavior
Child components do not receive updated values.

## The expected behavior
Updated state in parent are available to children (passed to them as props).

**Comment by Ykk2** [comment]
I believe this is happening because when you store an entire component inside the state, it is stored with the snapshot of the props at that moment.

Also, in general I think it is discouraged to store components inside the state. Even if the component will not be updated. From personal experience I found this leads to unexpected behavior with bugs that are hard to track down. Instead now I set the state with a unique identifier (str, or int), which will then render the component I want based on the value of the state. 

Could you share with me what your intentions were with this approach? I think it can help me understand the situation better.

**Comment by imageck** [comment]
> I believe this is happening because when you store an entire component inside the state, it is stored with the snapshot of the props at that moment.

Right, I suspected the same.

> Could you share with me what your intentions were with this approach? I think it can help me understand the situation better.

The idea is to limit the number of times any particular option can be selected. That is, an option must not be displayed (and consequently selected) if it's already been selected, say, three times. If the props were live, the last part of the code (from line 90) would be executed as intended.

**Comment by Ykk2** [comment]
Gotcha, would this solution work for you?

https://stackblitz.com/edit/nextjs-hxcvxr?file=pages%2Findex.js

Instead of storing the component, we are just storing objects what will be passed down as props.
Then we create a local state within each ItemField component and listen in on types to update the component.

**Comment by imageck** [comment]
Impressive!

I think I have taken a similar approach the second or the third version but it led to duplicate entries and a broken state. Possibly due to updating `types` improperly.

One thing. I'm not quite sure why there is a need for a separate state variable in `options`, as I believe prop updates already cause a re-render. Could you please shed some light on why duplication of state is okay here? The comment is a bit confusing, at least to me. Removing this new local state doesn't seem to affect the component in any negative way.

Anyway, you've just put an end to a lot of my frustrations. Thank you for taking the time to help me overcome this roadblock!

P.S. I'll apply your changes to the real component tomorrow.

**Comment by Ykk2** [comment]
Glad it's working! I chose to duplicate state here and keep it updated to ensure each component has an accurate reference to the current state of types. However, I do agree that this could be an unnecessary precaution.

**Comment by gaearon** [comment]
You're really not supposed to be storing JSX in state. Store the data itself. Then update the data when needed.
