### ISSUE TITLE
Bug: Unable to type new character when textarea is focused, happen when using Japanese IME on IOS

### ISSUE THREAD

**Issue by ytutyg0** [facebook/react#26805]
**Description**: This bug happens when I use Japanese (Kana) virtual keyboard on IOS, browser: safari or google chrome, with <texarea /> and a button that will clear textarea value focus back to it (like when you press send button in messenger). Then, when I press the button, textarea will be clear (state is set to "") and focus, but cannot type anything. I notice that the suggestion bar still there, so maybe it because the composition event, in this case, the composition may not end yet. I can avoid this happening by press confirm button on virtual keyboard **(確定)** before press send, but I don't think that how it should be, cause I can press button and focus back to textarea without any problems in Android. I'm not sure if this bug belong to IOS IME it self or React, but if anyone can figure out how to solve this, plz help me
  - bug video: https://screenpal.com/watch/c0hlh7VA6s2
  - code: https://stackblitz.com/edit/react-ts-pao9wf?file=App.tsx
  - this bug also happen with messenger when I tried to use it in iPhone browser: https://screenpal.com/watch/c0e2iCV4Odr
  I've tried many other react chat web app, but it met the same problem.

React version: 16.6 and 17.0.2

## Steps To Reproduce
Device: iPhone, IOS ver: any version, virtual keyboard: Japanese or Chinese, browser: Safari, google chrome
Step:
1. Type any Japanese character to the textarea (except for **(確定)**), then press the button that clear this textarea and focus to it (keyboard remains open during process)
2. Try to type other character, the cursor disappears, and none of the character is displayed, while the suggestion bar still have suggestion word

```
import React, { useRef, useState, useCallback } from 'react';
import './style.css';

export default function App() {
  const textAreaRef = useRef(null);
  const inputRef = useRef(null);
  const [inputText, setInputText] = useState('');
  const [areaText, setAreaText] = useState('');

  const handleReFocusTextarea = () => {
    setAreaText('');
    textAreaRef.current.focus();
  };
  const handleReFocusInput = () => {
    setInputText('');
    inputRef.current.focus();
  };

  return (
    <div className="container">
      <div>
        <input
          className="input-field"
          ref={inputRef}
          onChange={(e) => setInputText(e.target.value)}
          value={inputText}
        />
        <button className="button" onClick={handleReFocusInput}>
          Re-Focus Input
        </button>
      </div>
      <div>
        <textarea
          className="textarea-field"
          ref={textAreaRef}
          onChange={(e) => setAreaText(e.target.value)}
          value={areaText}
        />
        <button className="button" onClick={handleReFocusTextarea}>
          Re-Focus Textarea
        </button>
      </div>
    </div>
  );
}
```

Link to code example:  https://stackblitz.com/edit/react-ts-pao9wf?file=App.tsx

## The current behavior
Can not type any other character
## The expected behavior
The suggestion bar resets, and can type other character

So sorry for my bad English!

**Comment by Ykk2** [comment]
If I'm understanding this correctly, the bug occurs when you use your event handlers to clear the input/text and re-focus onto the input/textarea, and the application is not registering the text input coming from the IME. 

Could you try adding inputRef.current.blur() and textAreaRef.current.blur(), prior to setting the Input and areaText to empty string? So the order will be: blur --> clear input --> focus.

If the behavior seems random, then we can try wrapping the clear input and focus within a promise so we can ensure it executes after the blur event.

**Comment by ytutyg0** [comment]
@Ykk2 Thank you, I tried both ways you suggested, and here is what happened:
  - in case that I add textAreaRef.current.blur():
    ```
textAreaRef.current.blur();
    setAreaText('');
    textAreaRef.current.focus();
```
 i still got the same bug as before
  - Incase that i use Promise to make sure they are executed in order ( blur --> clear input --> focus. ), in IOS: the virtual keyboard is hidden when the button is pressed, while in Android, virtual keyboard is hidden but it shows up immediately, and textarea is focus
 With the code that I provided from the beginning, this is what happens on android: https://screenpal.com/watch/c0hIjGVAIJw , and I think this is how it should be on IOS, without adding any code. But as i said, i might cause by IOS IME, so if you have another solution to fix this, plz reply, thanks a lot

**Comment by bsuryab** [comment]
@ytutyg0 

Can you try adding the below two handlers and check.

  const handleCompositionStart = () => {
    // When composition starts, clear the areaText state
    setAreaText('');
  };

  const handleCompositionEnd = (e) => {
    // When composition ends, update the areaText state with the composed text
    setAreaText(e.target.value);
  };
  
 <textarea
     className="textarea-field"
     ref={textAreaRef}
     onChange={(e) => setAreaText(e.target.value)}
     onCompositionStart={handleCompositionStart}
     onCompositionEnd={handleCompositionEnd}
     value={areaText}
  />

**Comment by ytutyg0** [comment]
@bsuryab sorry for the late response and thanks for your help, i tried your suggested way but it didn't work

**Comment by joyahmed** [comment]
❌  `	const handleChangeInput = (	e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
		   e.preventDefault();
		   const { name, value } = e.target as HTMLInputElement;
			setItemState({ ...itemState, [name]: value });

	           };`

✅ `	<textarea
	   placeholder='Description'
	   name='description'
	   value={description}
	   onChange={e =>
	   setItemState(prev => ({
	      . ..prev,
	     description: e.target.value
	   }))
	}
	rows={9}
	/> `
