### ISSUE TITLE
Bug: Auto generated preload links should respect fetchpriority if specified

### ISSUE THREAD

**Issue by liuyenwei** [facebook/react#26810]
React version: 18.3.0-canary-a389046a5-20230512

## Steps To Reproduce

1. Server render a React component that renders either `<script>` or `<link>`  tags with `fetchpriority` set
2. Observe that React will add `<link rel="preload">` links for each of the discovered resources but without the same fetchpriority set.

Link to code example:

## The current behavior
Currently, if we server render a component such as the one below:
```
<html lang="en">
  <head>
    <link rel="stylesheet" href="/styles.css" fetchpriority="low" ></link>
  </head>
  <body>
    <script src="/script.js" fetchpriority="low" ></script>
  </body>
</html>
```
React will also render preload links for the `script` and `link` but without the `fetchpriority` set:
```
<head>
    <link rel="preload" as="style" href="/styles.css" />
    <link rel="preload" as="script" href="/script.js" />
    <link rel="stylesheet" href="/styles.css" fetchpriority="low" ></link>
  </head>
  <body>
    <script src="/script.js" fetchpriority="low"></script>
  </body>
```

The result is that both `styles.css` and `script.js` are fetched with `fetchpriority` set to high 

## The expected behavior
When generating preload links for `script` and `link` components, React should respect `fetchpriority` if specified.

**Comment by liuyenwei** [comment]
Looking through the code, it seems that this should be a straightforward fix by making a change [here](https://github.com/facebook/react/blob/4cd7065665ea2cf33c306265c8d817904bb401ca/packages/react-dom-bindings/src/server/ReactFizzConfigDOM.js#L5507) and [here](https://github.com/facebook/react/blob/4cd7065665ea2cf33c306265c8d817904bb401ca/packages/react-dom-bindings/src/server/ReactFizzConfigDOM.js#L5520)

If that sounds correct (and there isn't any disagreement about the expected behavior) - I'm happy to push up a PR to address this.

**Comment by gaearon** [comment]
cc @gnoff

**Comment by gnoff** [comment]
@liuyenwei PR would be welcome!

**Comment by gaearon** [comment]
Closing per https://github.com/facebook/react/pull/26826#pullrequestreview-1438195533.
