### ISSUE TITLE
Bug: Dialog issue - Multiple modals appearing and close button not working

### ISSUE THREAD

**Issue by rajput-hemant** [facebook/react#26816]
Initially, when I tried to open the modal using the `showModal()` method, I received the following error:

```
Failed to load show modal on 'HTMLDialogElement': The element already has an 'open' attribute, and therefore cannot be opened modally.
```

The initial issue was resolved by referring to a [comment](https://github.com/facebook/react/issues/24399#issuecomment-1104191934) by @gaearon on a related [GitHub issue](https://github.com/facebook/react/issues/24399)

After resolving the initial error with the `showModal()` method, I encountered a new problem with the dialog.

Currently, when I open the dialog, two modals appear instead of one. The second modal appears as I close the first one.

However, the close button only works for the first modal. The second modal remains open, and I am unable to close it using the close button.

React version: **18.2.0**

## Steps To Reproduce

- Open the provided CodeSandbox: [Link to CodeSandbox](https://codesandbox.io/p/sandbox/react-dialog-bqmheo).
- Trigger the dialog to open by clicking the "Open Dialog" button.
- Notice that two modals appear instead of one.
- Attempt to close the modals using the close button. Only the first modal can be closed successfully.

## The expected behavior

- Opening the dialog should display a single modal.
- The close button should close the modal when clicked, regardless of whether it is the first or second modal.

**Comment by gaearon** [comment]
By default browser `<dialog>` has `display: none` until you imperatively show it. However, your CSS sets it to `display: flex`. This is why you see two dialogs: the initial one was supposed to be hidden, but you made it visible, and then you *also* imperatively showed it. Remove `display: flex` from your `dialog` styles and it will work as intended.
