### ISSUE TITLE
setState in componentWillUpdate should return a proper error

### ISSUE THREAD

**Issue by bitplanets** [facebook/react#2682]
The returned error is `<error>` and nothing else. Maybe adding a link to the note in http://facebook.github.io/react/docs/component-specs.html#updating-componentwillupdate would help.

**Comment by flipstewart** [comment]
@zpao any update on the status of this? Should the code or the documentation be updated?

**Comment by koba04** [comment]
I think it should be fixed the code for more explicit error.

**Comment by zpao** [comment]
@jsfb - can you take this? We explicitly blocked this in 0.11 and threw `Error: Invariant Violation: replaceState(...): Cannot update during an existing state transition (such as within `render`). This could potentially cause an infinite loop so it is forbidden.`. We lost this check in 0.12 and that carried over to 0.13.

**Comment by koba04** [comment]
@zpao @jimfb Can I take this? Is this no longer valid? This seems to still exist.

**Comment by omerts** [comment]
With React 15.4.2, we actually have a case where setState in componentWillUpdate is triggering a re-render

**Comment by jedwards1211** [comment]
I just observed `setState` in `componentWillUpdate` triggering a re-render with React 0.14.9 (and there after all sorts of things blow up).

**Comment by nhunzaker** [comment]
Looks like the error here is:
https://jsfiddle.net/84v837e9/143/

Is the desire to have a better error here? What should the error state be as of June 2016?

cc @zpao

**Comment by nhunzaker** [comment]
Closing this one out in favor of #5097
