### ISSUE TITLE
Update copyright text to Meta instead of Facebook

### ISSUE THREAD

**Issue by denmo530** [facebook/react#26829]
react/packages/react
/react.shared-subset.js says Copyright (c) Facebook Platforms, Inc. and affiliates, but should be Copyright (c) Meta Platforms, Inc. and affiliates as it is more consistent

**Comment by Sanchari1999** [comment]
Hello! This is my first time contributing to open source. Is anyone already working on this issue?

**Comment by gaurav19790** [comment]
Hi, I would like to contribute in this. if anyone already working on this issues?

**Comment by MeenuyD** [comment]
Hello, I would like to contribute to this assign it to me.

**Comment by code978** [comment]
Hello, I would like to contribute to this assign it to me.

**Comment by gaurav19790** [comment]
This issue is already fixed. by @singhsanket143
