### ISSUE TITLE
[DevTools Bug]: Strict mode badge points to the old docs

### ISSUE THREAD

**Issue by radchukd** [facebook/react#26821]
### Website or app

https://fb.me/devtools-strict-mode

### Repro steps

The Strict mode warning badge points to https://fb.me/devtools-strict-mode which points to the strict mode section in [the old docs](https://legacy.reactjs.org/docs/strict-mode.html) instead of [the new docs](https://react.dev/reference/react/StrictMode).

Badge:
<img width="273" alt="Screenshot 2023-05-16 at 20 20 59" src="https://github.com/facebook/react/assets/37460589/2b3cbcf0-43b7-4f71-a420-02d31258ef92">

Code:
https://github.com/facebook/react/blob/4cd7065665ea2cf33c306265c8d817904bb401ca/packages/react-devtools-shared/src/devtools/views/Components/InspectedElement.js#L240

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Thanks for spotting, anyone interested in updating it to https://react.dev/reference/react/StrictMode?

**Comment by ibrahemid** [comment]
interested, can i proceed and open a PR @hoxyq ?

**Comment by runday198** [comment]
> interested, can i proceed and open a PR @hoxyq ?
> 
> here is the PR [Fix strict mode badge URL #26825](https://github.com/facebook/react/pull/26825)

Sorry mate I did not see your comment before starting

**Comment by hoxyq** [comment]
Thanks for your contributions @ibrahemid @runday198! Have to go with https://github.com/facebook/react/pull/26825, as @ibrahemid commented a bit earlier.
