### ISSUE TITLE
Bug: Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': function () { [native code] } could not be cloned.

### ISSUE THREAD

**Issue by Kingrashy12** [facebook/react#26838]
I trying to create a menuItem in my app using material ui, the app crashes anytime i add menuItem to it's

React version: 18.2.0
![Screenshot (115)](https://github.com/facebook/react/assets/113741914/5d5433f9-1ff0-4120-a25d-db292da198c2)

**Comment by ZikaZaki** [comment]
Issue: https://github.com/facebook/react/issues/26838

Hi @Kingrashy12 ,

I believe I have found a solution to the [issue](https://github.com/facebook/react/issues/26838) you're experiencing. From the error message you posted, it looks like there is a problem with importing a module from a relative path in your node_modules directory.

To solve this issue, I would recommend trying the following steps:

Ensure that the node_modules directory is excluded from your webpack configuration. This can be done by adding the following to your webpack.config.js file:

```node
module.exports = {
  //...
  externals: {
    'node_modules': 'commonjs node_modules',
  },
};
```

Ensure that the module you are importing is marked as an external dependency in your webpack configuration. You can do this by adding the following to your webpack.config.js file:

```node
module.exports = {
  //...
  externals: {
    'my-module': 'commonjs my-module',
  },
};
```

In this example, my-module should be replaced with the name of the module you are trying to import.

Ensure that the module you are importing has been installed in your project's node_modules directory. If it has not been installed, you can install it by running the following command:

```bash
npm install my-module --save
```

Ensure thatthe module you are importing has been correctly exported in its index.js file. You can check this by navigating to the node_modules/my-module directory and checking that the index.js file exports the correct functions or objects.
If these steps do not solve the issue, there may be a problem with the module itself. In this case, I would recommend checking the module's GitHub repository or contacting the module's maintainer for support.

I hope this helps! Let me know if you have any further questions or if there's anything else I can do to assist.

Best regards,

**[ZikaZaki](github.com/ZikaZaki)**
