### ISSUE TITLE
Bug: In a recursive components, `_debugSource` doesn't get updated

### ISSUE THREAD

**Issue by vlad-karnauch** [facebook/react#26837]
with the following component:
```typescript
export default function App({ title }: { title?: string }) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setIsLoading(false);
  }, []);

  if (isLoading || !title) {
    return <div data-id="line12">Loading...</div>;
  }

  return (
    <div data-id="line-15">
      Loaded
      <App />
    </div>
  );
}
```

when react-dom updates the div (the one with data-id="line12" to the one with data-id="line-15")
it doesn't update `_debugSource` attribute on the fiber, that's why devtools displays the wrong line number
(see image below)

React version:
18.*
## Steps To Reproduce

1. clone the github repo below
2. start the project and open it in the browser
3. open react-devtools
4. select the root `div` element inside `App`
The **source** location is wrong.

Or, you can open the following codesandbox:
[codesandbox](https://codesandbox.io/p/github/vlad-karnauch/react-recursion-issue/main?create=true&file=/src/App.tsx:16,33
)
open the preview in a separate browser tab, and see the issue in devtools

Link to code example:

[github-repo](https://github.com/vlad-karnauch/react-recursion-issue)

## The current behavior
![Screenshot 2023-05-21 at 17 43 08](https://github.com/facebook/react/assets/75258238/c3a49f6c-d5ac-4f35-b3d5-82dd361b4ee2)

## The expected behavior
**source** in react devtools should be `App.tsx:15`

**Comment by MeenuyD** [comment]
Hello @vlad-karnauch I think so To ensure that the correct line number is displayed, you can make a small adjustment to your code by wrapping the content of the return statement in a <React.Fragment> or  <div> This will create a new wrapper element, allowing React to update the correct DOM node and associate it with the correct line number. By wrapping the content in a <React.Fragment> or a <div> the DOM node associated with the line number in DevTools will be correctly updated when React renders the component.

**Comment by vlad-karnauch** [comment]
Hello, @MeenuyD , we're levereging devtools api to run user code, so unfortunatly, I don't have control over what code is being run.
