### ISSUE TITLE
react新的中文文档

### ISSUE THREAD

**Issue by xiaqingping** [facebook/react#26866]
react新的中文文档，使用上来看只能说很糟糕，基本上没有什么翻译，前面还是中文的，后面一节突然就变成英文的了，还不如以前的文档，另外UI也没有以前好看，体验感好差，叹气！

**Comment by y0zong** [comment]
react这个栈到顶了，这么多年了会的都会了不会的现在有更多现成的选择。(意思是完全没必要跟进新doc

**Comment by Brucia323** [comment]
我们会加快翻译速度的，请耐心等待。
