### ISSUE TITLE
Bug: Typescript + React

### ISSUE THREAD

**Issue by Erfan2001** [facebook/react#26867]
Hi guys, I suddenly get some errors these days when I run my code which they have not been before.

`  Its element type 'ReactElement<any, any> | Component<AppPropsType<NextRouter, {}>, any, any> | null' is not a valid JSX element.
    Type 'Component<AppPropsType<NextRouter, {}>, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<AppPropsType<NextRouter, {}>, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.`

React version:
"@types/react": "17.0.2",
"react": "^17.0.1",
"typescript": "^4.1.5",
"next": "^10.0.7",

## The current behavior
Lots of errors:
1)
`ERROR in pages/_document.tsx:48:55
TS2786: 'App' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<AppPropsType<NextRouter, {}>, any, any> | null' is not a valid JSX element.
    Type 'Component<AppPropsType<NextRouter, {}>, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<AppPropsType<NextRouter, {}>, any, any>' is not assignable to type 'ElementClass'.`
2)
`TS2769: No overload matches this call.
  Overload 1 of 2, '(o: { [s: string]: unknown; } | ArrayLike<unknown>): unknown[]', gave the following error.
    Argument of type 'T' is not assignable to parameter of type '{ [s: string]: unknown; } | ArrayLike<unknown>'.
      Type 'T' is not assignable to type 'ArrayLike<unknown>'.
  Overload 2 of 2, '(o: {}): any[]', gave the following error.
    Argument of type 'T' is not assignable to parameter of type '{}'.
     8 |
     9 |   static values<T>(t: T) {
  > 10 |     return Object.values(t);`
.....

## The expected behavior
event - compiled successfully

**Comment by MeenuyD** [comment]
Hello, @Erfan2001 can you please give the code where you have encountered this error?

**Comment by Erfan2001** [comment]
Hi @MeenuyD 
Thanks for your response.
Yeah, problems have happened on these occasions:
1) First error:
`
  ctx.renderPage = () =>
    originalRenderPage({
      enhanceApp: (App) => (props) => sheets.collect(<App {...props} />),
    });

  const initialProps = await Document.getInitialProps(ctx);
  //   resetServerContext();
  return {
    ...initialProps,
    // Styles fragment is rendered after the app and page rendering finish.
    styles: [...React.Children.toArray(initialProps.styles), sheets.getStyleElement()],
  };
`
2) second error:
`
export class Global {
  static entries<T>(t: T) {
    return Object.entries(t) as [keyof T, T[keyof T]][];
  }
  static keys<T>(t: T) {
    return Object.keys(t) as (keyof T)[];
  }

  static values<T>(t: T) {
    return Object.values(t);
  }
}
`

**Comment by devjiwonchoi** [comment]
For issue 1, if your project was working fine but is coming up with an issue and you just want to just resolve it, 
just pass type `any` since you are not passing any type to the `App`.

```
ctx.renderPage = () =>
  originalRenderPage({
    enhanceApp: (App: any) => (props: any) => sheets.collect(<App {...props} />),
  });

const initialProps = await Document.getInitialProps(ctx: any);
// resetServerContext();
return {
  ...initialProps,
  styles: [...React.Children.toArray(initialProps.styles), sheets.getStyleElement()],
};
```

For issue 2, set `Object.values(t) as T[keyof T];`
```
export class Global {
  static entries<T>(t: T) {
    return Object.entries(t) as [keyof T, T[keyof T]][];
  }

  static keys<T>(t: T) {
    return Object.keys(t) as (keyof T)[];
  }

  static values<T>(t: T): T[keyof T][] {
    return Object.values(t) as T[keyof T];
  }
}

```

I know this might not be the BEST answer but it will resolve your issue.
