### ISSUE TITLE
Bug: React.Children.only expected to receive a single React element child

### ISSUE THREAD

**Issue by shokhDeveloper** [facebook/react#26865]
То есть при использовании кутубонуса react-reveal при сопоставлении нового элемента с этим эффектом появляется вот эта ошибка, и я думаю, что эту ошибку надо решать, и она доставляет массу проблем пользователю.

**Comment by shokhDeveloper** [comment]
То есть при использовании кутубонуса react-reveal при сопоставлении нового элемента с этим эффектом появляется вот эта ошибка, и я думаю, что эту ошибку надо решать, и она доставляет массу проблем пользователю.

**Comment by sharmaachintya08** [comment]
can you provide some code on where you are having this error because in my opinion, it shouldnt be a bug because thats what React.Children.only are designed to do as they retrieve a single child element only.

**Comment by scffs** [comment]
It's looks like expected behavior if you are passing more than one child element, while `React.Children.only` only accepts one, isn't it?
```js 
 const child = React.Children.only(children);
```
Can you please provide more context
