### ISSUE TITLE
[DevTools Bug]: App not recognized in Firefox, but works in Chrome

### ISSUE THREAD

**Issue by Azeirah** [facebook/react#26860]
### Website or app

-

### Repro steps

On both Firefox 103 and 104 the react devtools extension says: "This page doesn't appear to be using React".

On the most recent version of Chrome it's working just fine.

I cannot share the project since it's a private project unfortunately, but I suspect this is a regression introduced with the recent https://github.com/facebook/react/pull/26765

Especially since the devtools were working perfectly fine until maybe one or two weeks ago.

It _does_ work in incognito mode in Firefox.

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Hey @Azeirah, thanks for reporting this.

Can you please specify the version of the extension you are using in Firefox?

**Comment by Azeirah** [comment]
It's version 4.27.8

**Comment by hoxyq** [comment]
> It's version 4.27.8

I cannot reproduce it with Firefox both v113.0.2 and v104.0, so its probably something wrong on your end. If you can share more about your setup, I can try to help you with that.

**Comment by hoxyq** [comment]
> 

Do I understand correctly that it works for you in Firefox's incognito mode? That is weird, because we don't support it yet.

**Comment by Azeirah** [comment]
> Do I understand correctly that it works for you in Firefox's incognito mode? This is strange, because we don't support it yet.

I thought so, but it's not the case. The plugin gives the notification that it can find react on the page, but the actual devtools don't load.

This is in Firefox incognito mode.

![afbeelding](https://github.com/facebook/react/assets/4040870/c813af47-112b-44fe-8eef-109e168df37c)

---

I'm also noticing that the devtools not loading seems almost random, on some page reloads they _do_ load and on others they don't.

This gives me the feeling that there might be a race condition due to script loading order? If the plugin loads before React on the page, it works, if not, it won't.

**Comment by hoxyq** [comment]
> > Do I understand correctly that it works for you in Firefox's incognito mode? This is strange, because we don't support it yet.
> 
> I thought so, but it's not the case. The plugin gives the notification that it can find react on the page, but the actual devtools don't load.
> 
> This is in Firefox incognito mode.
> 
> 
> I'm also noticing that the devtools not loading seems almost random, on some page reloads they _do_ load and on others they don't.
> 
> This gives me the feeling that there might be a race condition due to script loading order? If the plugin loads before React on the page, it works, if not, it won't.

Too many factors that might influence it, this will be hard to debug without reproducible sample.
Can you try to run this application (which doesn't work with DevTools) locally (not on apache) and check if it works?

If problem is still present, I think you can create a repro from this point.

We still have different script injection logic for Firefox and not yet migrated to manifests v3 for Firefox, so this might be the reason why it works on Chrome and not on Firefox.

**Comment by Azeirah** [comment]
> Can you try to run this application (which doesn't work with DevTools) locally (not on apache) and check if it works?

What do you mean by running it locally? I need a webserver to serve the application. With `file://` it won't work according to the troubleshooting guide either, or am I misunderstanding you?

**Comment by hoxyq** [comment]
> > Can you try to run this application (which doesn't work with DevTools) locally (not on apache) and check if it works?
> 
> What do you mean by running it locally? I need a webserver to serve the application. With `file://` it won't work according to the troubleshooting guide either, or am I misunderstanding you?
> 
> The application is running on a local webserver, jamezzv2.test is just a hostfile alias for localhost:somePort

It should work with `file://`, troubleshooting guide [specifies](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#faq) to toggle the required switch for Chrome. 

Sorry I wasn't clear initially, just trying to check if there is a way to create a reproducible setup.

**Comment by Azeirah** [comment]
I recreated the app with file:// with a simple index.html importing the built application.

The devtools recognized the application 10 out of the 10 times that I reloaded it.

**Comment by wfjake** [comment]
Do you have Content-Security-Policy enabled? That will prevent extensions from running on your application in Firefox.

**Comment by Azeirah** [comment]
> Do you have Content-Security-Policy enabled? That will prevent extensions from running on your application in Firefox.

This is not it ;( it's not enabled

**Comment by Azeirah** [comment]
I found the cause. The application I'm working is meant for different devices, and it turns out it's the simulated user-agent that causes the dev tools not to recognize the application.

I've been able to reproduce this in my development profile using Firefox dev edition as well as on Firefox stable edition on a clean profile.

- [ ] Open page
- [ ] Press ctrl+shift+m (mobile simulation, if on mac use dev tools to open mobile sim)
- [ ] Add custom user agent, for example this one fails: `Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36`
- [ ] Press enter to confirm
- [ ] Dev tools do not recognize the page anymore after refresh

Without the custom user agent it consistently loads as expected.

**Comment by hoxyq** [comment]
> 

Yeah, it is because of how we [parse user agent](https://github.com/facebook/react/blob/main/packages/react-devtools-extensions/src/utils.js#L5-L7).

This one fails because we look for `Firefox` here. This user agent doesn't state that it is Firefox-compatible, only Mozilla-compatible.

**Comment by hoxyq** [comment]
> From my perspective I'm just working on an application in mobile mode and suddenly the dev tools stop working.

As you stated before, there were 2 different applications, and one of them patches user agent. I don't think this is a common case that should be listed somewhere in troubleshooting list.

I agree that we should display different popup with more readable explanation of whats going wrong. In your case, extension was trying to start, assuming that it was a Chromium-based browser and failed at some point. I don't know if you tried this before, but there is a way to debug extension in Firefox, and I think you will see errrors in this window's console.

I think the right way to handle this would be:
1. Remove [this](https://github.com/facebook/react/blob/main/packages/react-devtools-extensions/src/utils.js#L7) assumption. If we have some weird unexpected user agent, where each flag is false, we should display new popup.
2. Migrate to using [navigator.userAgentData](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData) with a fallback to UA string parsing for Firefox.

Anyone interested in picking this up?

**Comment by Azeirah** [comment]
> As you stated before, there were 2 different applications, and one of them patches user agent. I don't think this is a common case that should be listed somewhere in troubleshooting list.

This user agent is a default preset in Firefox mobile dev mode. This is not something I configured myself. That's why I expect it to happen to other people as well. I don't know if Chrome does this.

**Comment by hoxyq** [comment]
> > As you stated before, there were 2 different applications, and one of them patches user agent. I don't think this is a common case that should be listed somewhere in troubleshooting list.
> 
> This user agent is a default preset in Firefox mobile dev mode. This is not something I configured myself. That's why I expect it to happen to other people as well. IE, if you just press ctrl+shift+m and choose a device preset like the iPhone SE Firefox sets a user agent like the one I shared before.
> 
> This is the same as in Chrome, switching to the mobile emulator changes the user agent.
> 
> The logs are before turning on mobile sim and after.
> 
> <img alt="Screenshot 2023-07-25 at 20 49 06" width="1289" src="https://user-images.githubusercontent.com/4040870/256003492-5b2e9e0a-e9c5-4a66-9066-381c739f9e01.png">

Oh, thanks for clarifying! We should definitely change this logic, and probably not depend on user agent string, when it comes to extension.

**Comment by hoxyq** [comment]
Hey @Azeirah, I've opened a PR with changes that should fix it - https://github.com/facebook/react/pull/27179.

Can you please try downloading and installing a custom build from [here](https://app.circleci.com/pipelines/github/facebook/react/44919/workflows/538da36d-238d-4561-8bf2-fb472517c91b/jobs/705453/artifacts) to check if it fixes the problem for you?

`devtools.tgz` should contain `firefox-extension.zip` archive, which then can be manually installed in Firefox. Please also consider removing original React DevTools extension from Firefox before that.

**Comment by Azeirah** [comment]
It's working :)

**Comment by hoxyq** [comment]
> It's working :)

Awesome, thanks for helping!
