### ISSUE TITLE
Bug: Form with name="location" crushes chrome

### ISSUE THREAD

**Issue by aletor123** [facebook/react#26884]
React version: 16.*, 18.*

## Steps To Reproduce

1.Use chrome 114 version
2.Add form with name="location" to jsx
3.Open page

## The current behavior
You will get Oh snap error
![image](https://github.com/facebook/react/assets/75448378/39e86459-8cd7-4ab3-8ed8-8ab96a95229e)

Code example: https://stackblitz.com/edit/react-ts-egwgqn?file=App.tsx

## The expected behavior
No error

**Comment by kaleemullah786** [comment]
hey this seems doable to me

**Comment by aletor123** [comment]
What do you mean?

**Comment by kaleemullah786** [comment]
where is this issue?

**Comment by aletor123** [comment]
If you follow instruction and use chrome 114 version, you will get `Oh snap` error

**Comment by kaleemullah786** [comment]
Okay, let me look into it

**Comment by aletor123** [comment]
It's bug in chrome
https://js-vcfsfl.stackblitz.io

**Comment by dolanite** [comment]
I found this bug in Chrome as well. It is not unique to React. It seems to be tied to the name attribute of the form, i.e. <form name='location'> Perhaps 'location' is a reserved word in Chrome now? I  just decided to change the form name to solve this issue.

**Comment by kishoreknowapp** [comment]
I think the issue can be closed as this is not related to React. It is in chromium browsers.
