### ISSUE TITLE
error to display the names of the hooks.

### ISSUE THREAD

**Issue by edinsondevs** [facebook/react#26885]
It shows a parse error and does not allow me to visualize the names of the states that I have in my project, as you can see in the image below.

**please help me**

![image](https://github.com/facebook/react/assets/94578362/7177faec-2d3b-4970-80ff-9c08f6dfd0e7)

**Comment by scffs** [comment]
Hi. What is the error in your console?

**Comment by Hemant2216** [comment]
You  can try by going to root directory of your project through the command prompt 
Once reached to the directory of your project 
write the following command :
npm list react --pattern "hook"
it should get a list of packages that include "hook" in their names, helping you identify the React hooks

**Comment by edinsondevs** [comment]
@scffs none

**Comment by Hemant2216** [comment]
Then you can try updating your webpack devtool 
or switching your webpack devtool to :  cheap-module-source-map
