### ISSUE TITLE
Bug: React fails to log invariant 306 message when lazy() resolves to a `Fragment`

### ISSUE THREAD

**Issue by tom-sherman** [facebook/react#26910]
React version: 18.2.0

## Steps To Reproduce

1. Try to render this component: `const LazyFragment = lazy(() => Promise.resolve({ default: Fragment }));`

Link to code example:

https://github.com/tom-sherman/react-lazy-fragment-bug

## The current behavior

It throws an error:

```
Cannot convert a Symbol value to a string
```

## The expected behavior

It should throw an error related to invariant 306 eg.

```
Element type is invalid. Received a promise that resolves to: Fragment. Lazy element type must resolve to a class or function.
```

**Comment by MeenuyD** [comment]
Hello, the issue you're encountering is related to using lazy with a dynamically resolved promise that resolves to { default: Fragment }. However, lazy expects the resolved value to be a class or function component, not an object.
use dynamic import to load the Fragment component from the react module, and then we wrap it in an object with the default property as { default: module.Fragment }. This ensures that lazy receives a valid component as its resolved value.

**Comment by MeenuyD** [comment]
Hello, I think the issue you're encountering is related to using lazy with a dynamically resolved promise that resolves to { default: Fragment }. However, lazy expects the resolved value to be a class or function component, not an object.
use dynamic import to load the Fragment component from the react module, and then we wrap it in an object with the default property as { default: module.Fragment }. This ensures that lazy receives a valid component as its resolved value.

**Comment by tom-sherman** [comment]
firstly `{default: Fragment}` is not the issue. Lazy doesn't care about immediately resolved promises, this pattern works fine with function components or element strings.

The same issue happens if you default export `Fragment` from a module and then `lazy(() => import("./LazyFragment"))`. See https://github.com/tom-sherman/react-lazy-fragment-bug/commit/95b1567eb00dec364c8271fc7bf5c734c658704f

Secondly, the expected behaviour is to log an appropriate error from React. Instead it's failing to do so and throwing a random exception.

Whether a lazily loaded Fragment should work is besides the point, that can be discussed in a separate issue. This bug is about the incorrect error message being displayed.

**Comment by tom-sherman** [comment]
Still an issue on latest canary.

**Comment by tom-sherman** [comment]
This still exists on latest canary.
