### ISSUE TITLE
[DevTools Bug]: React devtools stuck at Loading React Element Tree, troubleshooting instructions are Chrome-specific

### ISSUE THREAD

**Issue by ialexryan** [facebook/react#26911]
### Website or app

corporate project (private)

### Repro steps

Load page, then open React DevTools. Reloading or closing and reopening the tab does not fix the problem. Quitting and reopening Firefox sometimes fixes the problem.
<img width="837" alt="image" src="https://github.com/facebook/react/assets/2292782/0fbcaf7c-533f-4afd-819c-b9f2749aa765">

The [linked troubleshooting instructions](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#the-react-tab-shows-no-components) provide no guidance for users of browsers other than Chrome; I am running Firefox v114 (on macOS 13.2.1).

### How often does this bug happen?

Often

**Comment by silvestreh** [comment]
I'm having the same issue. This is what comes up in the console: `TypeError: can't access property "executeScript", chrome.scripting is undefined`

**Comment by ialexryan** [comment]
I actually hit this for the first time in a while just now. The error in the console was `TimeoutError: Timed out while inspecting element 43.` 
<img width="500" alt="image" src="https://github.com/facebook/react/assets/2292782/dfd6f09e-eda6-4d5b-866d-782443418b90">

**Comment by austinbutler** [comment]
Same issue but nothing in the console.

**Comment by sandinmyjoints** [comment]
Also same problem. Nothing in console.

**Comment by hoxyq** [comment]
Hey, I've opened a PR with changes that should fix it - https://github.com/facebook/react/pull/27179.

Looks like extension doesn't work when mobile dev mode is enabled in Firefox.

Can anyone try downloading and installing a custom build from [here](https://app.circleci.com/pipelines/github/facebook/react/44919/workflows/538da36d-238d-4561-8bf2-fb472517c91b/jobs/705453/artifacts) to check if it fixes the problem for you?

`devtools.tgz` should contain also `firefox-extension.zip` archive, which then can be manually installed in Firefox. Please also consider removing original React DevTools extension from Firefox before that.

**Comment by sandinmyjoints** [comment]
@hoxyq That fixed it for me! Thanks!
