### ISSUE TITLE
Bug: unable to set value on hidden input

### ISSUE THREAD

**Issue by JohnRDOrazio** [facebook/react#26927]
React version: 18.2.0

## Steps To Reproduce

1. Create a `ref` to an uncontrolled hidden input
2. Update the value of the hidden input via the `ref` on some event (for example based on the value of another input, triggered by the `onChange` event)
3. Update the dom view via a state change
4. Get the value of the hidden input via the `ref`

There seems to have been a similar situation with `react-hook-form` (which I however am not using):
* https://github.com/react-hook-form/react-hook-form/issues/284
* https://github.com/react-hook-form/react-hook-form/issues/2917
* https://github.com/react-hook-form/react-hook-form/pull/2924

The error only happens when the dom view is refreshed via a state change: the new value in the hidden input does not persist a refresh of the dom view. Whereas the new value of a text input set to `display: none` is persisted.

Link to code example:

https://codesandbox.io/s/quirky-nova-3jnmtq (with bootstrap 4)

https://codesandbox.io/s/quizzical-darkness-66n97j (without bootstrap)

## The current behavior
Value of the hidden input has not changed from the initial value.

## The expected behavior
Value of the hidden input should have changed to the value we set it to.

**Comment by JohnRDOrazio** [comment]
I also tried with the latest React 18.3.0, isn't fixed:

https://codesandbox.io/s/agitated-tharp-gxr7z2

**Comment by JohnRDOrazio** [comment]
Though a hidden input's value can't be changed by the end user, it should however be able to be changed by the app:

> The [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element's [value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#value) attribute holds a string that contains the hidden data you want to include when the form is submitted to the server. This specifically can't be edited or seen by the user via the user interface, although you could edit the value via browser developer tools.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden

And in fact it does still work in a React app, as long as the dom view isn't updated, see this example:
https://codesandbox.io/s/dreamy-chaum-ct8czg

**Comment by MeenuyD** [comment]
Hello, @JohnRDOrazio the ref local variable persists the data does not see on UI after re-rendering the components via the state variable.
In the code of code sandbox hidden inputs don't display their values directly on the page, but their values can be accessed programmatically. In this case, the updated values are correctly stored in the hiddenFields ref object, and when we click "Finalize," the finalizeForm function retrieves these values and updates the results state.

**Comment by JohnRDOrazio** [comment]
@MeenuyD I don't believe you have looked closely at the codesandbox examples I provided. The value of the hidden inputs are NOT persisted in the `ref` variable, if the dom view is refreshed.

**Comment by MeenuyD** [comment]
Thanks for correcting me.

**Comment by MeenuyD** [comment]
Thanks for correcting me I am beginner

**Comment by rothsandro** [comment]
The browser treats the `value` property different for inputs of type `hidden` vs others. If you set the value of a `type=hidden` input, it will not just update the value property but update the DOM attribute and therefore change the `defaultValue`. On re-render, React detects that the `defaultValue` is not up to date and changes it back to the value you provided as `defaultValue`. For other inputs, the browser does not update the DOM attribute, so `defaultValue` will not change.

As a workaround you can change the `defaultValue`:

```tsx
defaultValue={hiddenFields.current["HIDDEN_TYPE_FIELD"]?.value ?? "Bob Ross"}
```

**Comment by gustavopch** [comment]
Not stale.

**Comment by PatrykKuniczak** [comment]
Still don't solved ...
