### ISSUE TITLE
@l0gicgate

### ISSUE THREAD

**Issue by serkon** [facebook/react#26937]
I faced a similar issue. The cause of the error was the "useLocation()" hook of react-router-dom. I have moved it to before of the "return <Navigate to ..." then it was fixed. 

I don't know what was changed but it worked. If anybody could explain this, I will be glad...

My old code is: 

```tsx

import { Navigate, useLocation } from 'react-router-dom';


export const Navigation = ({ children }: React.PropsWithChildren): JSX.Element => {

    const location = useLocation(); //  ---> Cause of the error

    if (Authenticator.isAuthenticated() && window.sessionStorage.getItem('isAuthenticated') === 'true') {
      return <>{children}</>;
    }


    return <Navigate to="/login" state={{ from: location }} replace />;
  };

```

Correct version is:

```tsx

export const Navigation = ({ children }: React.PropsWithChildren): JSX.Element => {
    if (Authenticator.isAuthenticated() && window.sessionStorage.getItem('isAuthenticated') === 'true') {
      return <>{children}</>;
    }

    const location = useLocation(); // moved here and fixed

    return <Navigate to="/login" state={{ from: location }} replace />;
  };

```
              @l0gicgate 

>I think it is imperative that this error message be modified to include exactly which line of code is causing the error.

There are limits to what we can do in JavaScript. But **all the information is in the stack you see in the browser**. All you need to do is to skip the lines that are inside React.

To see the JavaScript stack, you need to **click on a small arrow next to the error message**.

For example, look at this screenshot from earlier:

![75614021-cb812980-5b12-11ea-8a6e-a38f4cd6aeef](https://user-images.githubusercontent.com/810438/76101765-daf6eb80-5fc6-11ea-964b-5a68de4757e6.png)

I appreciate it's a bit annoying to dig through the stack, but it shouldn't be that hard to skip the first several frames. The very next frame is the source of the problem. In this case, it seems like something inside the Formik library. So you can file an issue with it.

_Originally posted by @gaearon in https://github.com/facebook/react/issues/18178#issuecomment-595846312_

**Comment by AsheerAF911** [comment]
Can you explain what was the problem you were facing in the old version of code.
