### ISSUE TITLE
Bug: JSX loses component type definition

### ISSUE THREAD

**Issue by yairopro** [facebook/react#26934]
React version: 18.2.0

## Steps To Reproduce

1. Create a JSX element of a functional component which has its props with type definitions
2. Create another element of the same component using react's `createElement()`.
3. If you compare the 2 element's types, you'll notice that the one from `createElement()` has kept a generic ref to the component and extends `FunctionComponentElement` in this case, while the one using JSX hasn't and is statically just `JSX.element`.

Link to code example:
https://codesandbox.io/s/jsx-element-loses-types-6nmh3m?file=/src/App.tsx

![image](https://github.com/facebook/react/assets/8110568/39cdefed-36dd-44ce-9079-e7aa5a4555b6)
![image](https://github.com/facebook/react/assets/8110568/7cd00b7c-97e2-41aa-b47b-fed581048aae)

## The current behavior

The element created by JSX don't keep any reference to the component or its props types.

## The expected behavior

The element created by JSX should keep any reference to the component or its props types **as `React.createElement()` does.**

**Comment by yairopro** [comment]
Hi @MeenuyD 

> the element's type **is inferred** based on the component's type declaration and the props passed to it. However, once the JSX code is **transpiled to JavaScript**, the type information is not preserved in the resulting JavaScript code.

**My issue is before the transpilation**. I am talking about the infered type given by vscode during development.

**Comment by MeenuyD** [comment]
when using JSX syntax, the inferred type for the component may appear as JSX. Element, which is a generic type that represents any JSX element. This happens because the type inference for JSX elements is not as powerful as the type inference for function calls or React.createElement

**Comment by yairopro** [comment]
Thanks for the clarification MeenuyD.

So what we need is to tell the JSX syntax to use a given function behind (here `React.createElement()`) in order to let it infer the elements' types, via some configuration of typescript (if such config exists). 

If no such feature exists, then we should at least start to open an issue to give this idea to repo responsible for the JSX generated types, which I don't know how to find it. 

Any idea how we can make this going further?

**Comment by eps1lon** [comment]
Closing since this is an issue caused by https://github.com/microsoft/typescript itself. There's probably an issue on their side already. But it generally falls under the category of "no constrained/generic JSX children" in typescript.

**Comment by yairopro** [comment]
Thanks @eps1lon for the repo.
