### ISSUE TITLE
Bug: SSR: "Text content did not match" for inline CSS in style element

### ISSUE THREAD

**Issue by EmielM** [facebook/react#26946]
When using Server Side Rendering for the complete document (as suggested [in the docs](https://react.dev/reference/react-dom/server/renderToPipeableStream#usage)), and having inline css that contains quotes (`"`, `'`) in a style element:

```
function App() {
  return <html>
    <head>
      <style>body { font-family: "Comic Sans"; }</style>
    </head>
  </html>;
}
```

The quotes are encoded by `react-dom/server` as `&quot;`, and client-side hydration chokes:
```
Warning: Text content did not match. Server: "body { font-family: &quot;Comic Sans&quot;; }" Client: "body { font-family: "Comic Sans"; }"
    at style
    at head
    at html
    at App2
printWarning @ bundle.js:2426
```

React version: 18.2.0
Reproducing case: https://github.com/EmielM/react-ssr-reconcile-repro
- [App component](https://github.com/EmielM/react-ssr-reconcile-repro/blob/main/App.js)
- [server entry](https://github.com/EmielM/react-ssr-reconcile-repro/blob/main/server.js)
- [client entry](https://github.com/EmielM/react-ssr-reconcile-repro/blob/main/index.js)

For completeness, the verbatim HTML output from the server:
```
<!DOCTYPE html><html><head><style>body { font-family: &quot;Comic Sans&quot;; }</style></head><body>Body!</body></html><script src="/bundle.js" async=""></script>
```

**Comment by Shurtu-gal** [comment]
@EmielM Remove the quotes. They are unnecessary

`createElement('style', {}, 'body { font-family: Comic Sans; }')`

**Comment by EmielM** [comment]
@Shurtu-gal this is a synthetic/simplified example, there are cases when you really need a quote in your css, eg for content property, or selectors such as a[href=“whatever”]. In any case, react should handle this correctly.

**Comment by YantD729** [comment]
I think it is a problem on hydration on CSR. Although this is my first issue, I would like to have a try. Do you mind to assign it to me? Thank you :3 I will update immediately once I feel not okay to solve it.

**Comment by EmielM** [comment]
@YantD729 We're still having this, would you mind :)?

**Comment by jereaa** [comment]
I'm having the same issue when rendering with `renderToPipeableStream`.
As for my example, you just need to refer to [React's new documentation for the `<style>`](https://es.react.dev/reference/react-dom/components/style#rendering-an-inline-css-stylesheet) tag under `react/dom`.

<img width="954" alt="image" src="https://github.com/facebook/react/assets/1518173/fade0796-3e54-4ce1-9c73-324270e15136">

Same thing happens with inline scripts and characters like `&` that get encoded.

**Comment by jereaa** [comment]
Still an issue

**Comment by silviogutierrez** [comment]
@jereaa : how did you end up handling this? It's still an issue in React 19.

**Comment by jereaa** [comment]
@silviogutierrez as was commented previously [here](https://github.com/facebook/react/issues/26946#issuecomment-1829405665), I bypassed it by using `dangerouslySetInnerHTML`
