### ISSUE TITLE
Allow ES6 symbols on mixins

### ISSUE THREAD

**Issue by monsanto** [facebook/react#2696]
ES6 symbols are useful for making mixins that are guaranteed to not clash with the namespaces of other mixins. However, currently symbols on mixins are ignored. This is because `mixSpecIntoComponent` uses a `for-in` loop to find all of the properties to mixin, which ignores symbols. I propose that [`getOwnPropertySymbols`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols) is used as well to pick up symbols defined on the mixin object.

**Comment by gaearon** [comment]
We won't be changing how mixins work, and we don't recommend using them in new code.
