### ISSUE TITLE
Bug: form data is lost upon hydration

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react#26974]
Related:
- https://github.com/facebook/react/issues/12955
- https://github.com/mui/material-ui/issues/34174
- https://stackoverflow.com/questions/73567117/how-to-deal-with-text-input-changes-in-ssr-text-box-before-hydration-is-complete

React version: 18.2.0

## Steps To Reproduce

Link to code example: https://github.com/OliverJAsh/react-controlled-form-hydration-issue

Given this component which is used during SSR and then hydrated on the client-side:

```tsx
import * as React from 'react';

export const App = () => {
  const [value, setValue] = React.useState('');

  const [, setCount] = React.useState(0);

  React.useEffect(() => {
    console.log('mount');

    setCount(1);
  }, []);

  return (
    <form>
      <div>Value: {value}</div>
      <input
        type="text"
        value={value}
        onChange={(e) => setValue(e.currentTarget.value)}
      />
    </form>
  );
};

```

1. Before hydration, enter text into the input.

## The current behavior

After hydration, the input's value is set back to the initial state. The text entered by the user prior to hydration is lost.

https://github.com/facebook/react/assets/921609/2a9d5c38-338b-4caa-9a3e-fe8a68f5fe44

## The expected behavior

The text entered by the user prior to hydration should be preserved.

**Comment by nusr** [comment]
After the page is loaded, enter the text after 3 seconds, and the content will not be lost.
Or remove the setTimeout, and the content directly entered will not be lost.
![image](https://github.com/facebook/react/assets/12200340/46d9b7a8-18db-4cda-affc-c45e1628d58d)

**Comment by EnshaednHiker** [comment]
Is the setTimeout just to demonstrate the issue? Another way to test this issue is to throttle CPU and network speed in devtools, and then that setTimoueout is most likely not necessary. Fast 3G and 4x CPU slowdown might be something to try to start. The location of these tools recently changed in chrome, so for others following along, here's where they are today: 
![image](https://github.com/facebook/react/assets/23422635/6b8da003-3764-4687-bf95-e6962943ff55)

**Comment by OliverJAsh** [comment]
Yeah the timeout is to simulate delayed hydration e.g. due to slow JS.

**Comment by OliverJAsh** [comment]
Bump

**Comment by kevincox** [comment]
This also affects browser-saved input fields which is a huge UX issue.

By default the browser will save form inputs across reloads or after navigating forward and back. But when hydration runs these saved values will be wiped. I'm not sure if there is a clean way to do this by default (firing `onChange` would probably work, but that feels messy) but there should at least be some sort of API where the value of the component being hydrated can be preserved. For example the simplest way would be something like this:

```javascript
export function App() {
  const hydrationTarget = useHydration();
  const [value, setValue] = React.useState(hydrationTarget?.value);

  ...
}
```

Presumably `useHydration` would return the element being hydrated for the first render during hydration. Although this API is probably too simple:

1. Would only return the root element, what if you need a nested element
2. What if your value is not an HTML element but a component?

Maybe it would be possible to make `useRef` work for this case?

```javascript
export function App() {
  const formRef = useRef();
  const [value, setValue] = useState(formRef.current?.value);

  return (
    <form>
      <div>Value: {value}</div>
      <input
        ref={formRef}
        type="text"
        value={value}
        onChange={(e) => setValue(e.currentTarget.value)}
      />
    </form>
  );
}
```

During hydration the ref returned by `useRef` can already contain the referenced element. Letting you use it to initialize state. This would just need to track where each ref is used during the static render. Then for every ref that is used on an HTMLElement the relation is serialized and the `useRef` can return a value on the first render.

It isn't clear how this would work for non-HTMLElement refs. Probably those just continue to act as today returning uninitialized.
