### ISSUE TITLE
[eslint-plugin-react-hooks] (react-hooks/exhaustive-deps) allow configuring a prop to throw errors with unnecessary dependencies in useEffects

### ISSUE THREAD

**Issue by andyindahouse** [facebook/react#26981]
**Do you want to request a feature or report a bug?**

Feature/enhancement

**What is the current behavior?**

Currently the eslint plugin doesn't throw an error when you have unnecessary dependencies in the useEffect's dependencies array because this could be a legit case but in general these dependencies are unnecessary and could cause errors.

Example:
```typescript
React.useEffect(() => {
    if(legitDependency) {
         // some api call that in the past used nonLegitDependecy but in a refactor this was removed
    }
}, [legitDependency, nonLegitDependency]) // exhaustive-deps doesn't warn for nonLegitDependency in a useEffect
````
**What is the expected behavior?**

It'd be great if we could configure "eslint-plugin-react-hooks" rule to warn in these cases, because I think in the most of cases we don't want this effect runs for these unnecessary dependencies and they are there because a mistake.

```typescript
React.useEffect(() => {
    if(legitDependency) {
         // some api call that in the past used nonLegitDependecy but in a refactor this was removed
    }
}, [legitDependency, nonLegitDependency]) // eslint warn/error  React Hook React.useEffect has an unnecessary dependency: 'nonLegitDependency'. Either exclude it or remove the dependency array 
````
I've created this rule based on the exhaustive-deps code and I've found a lot hints with this. So I think it'd great and very useful for others projects to take advantage of this, if this was included in the "react-hooks/exhaustive-deps" rule.

As for how/where to configure it, we could add something like this to our .eslintrc:

```
'react-hooks/exhaustive-deps': [
    'error',
    {
        warnWithNonLegitDependencies: true,
    },
],
```

And then we could mark legit dependecies in this way:

```typescript
React.useEffect(() => {
    if(legitDependency) {
         // some api call that in the past used nonLegitDependecy but in a refactor this was removed
    }
}, [legitDependency, /* legit-dependency */ nonLegitDependency]) // No eslint errors
````

For this new behaviour, we only have to change [this condition](https://github.com/facebook/react/blob/d1c8cdae3b20a670ee91b684e8e0ad0c400ae51c/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L1445 ) to save all unnecessary dependencies in a useEffect and create an extra check to omit dependencies with "legit-dependency" comment before them. I could create a PR for this, if you like.

**Comment by Shashank245** [comment]
Hey @andyindahouse, I have been working on the feature/issue. I have cloned the repository and have made the changes in **_.eslintrc.js file and ExhaustiveDeps.js_** file as well. I was thinking about adding the Test cases, Is it necessary for this feature because the change was pretty straightforward. I could also go ahead with directly creating a PR for this one.

**Comment by andyindahouse** [comment]
@Shashank245 Thanks for your support and PR 👍, but I think this should be discussed before giving an implementation. (I'm not sure if they'll be interested on this)

**Comment by Shashank245** [comment]
Okay. Thank you for the response I an a bit new to this, How do you think
should I communicate as in Should I give a heads-up to any specific
maintainer of the project??

**Comment by andyindahouse** [comment]
We could wait a little for a response

**Comment by Shashank245** [comment]
Sure. Will definitely wait and work on any changes they would mention.
Thanks.

**Comment by kkimdev** [comment]
friendly ping! any updates yet?

**Comment by andyindahouse** [comment]
Not yet :(

**Comment by taoliujun** [comment]
It is a great issue but not yet, I really need this rule to detect the unnecessary dependencies.
