### ISSUE TITLE
Bug: [Firefox] Removing an element with contentEditable="true" within an iframe and an RTL selection causes an exception

### ISSUE THREAD

**Issue by lorenzo-pomili** [facebook/react#26980]
selecting from right to left inside an element that is inside an iframe and the iframe is removed it cause an exception

React version:

## Steps To Reproduce
component:
```
const ElementWithTheException = () => {
  const [ show, setShow ] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setShow(false);
    }, 5000);
  });

  return <div>
    {show ? <iframe src="about:blank" srcDoc='<html><body contentEditable="true">lorem ipsum</body></html>'></iframe> : <p>abc</p>}
  </div>;
};
```

1. in Firefox
2. select from right to left `lorem ipsum` (or part of it)
3. wait 5 seconds
4. look at the console

Link to code example:

1. open https://codesandbox.io/s/inspiring-volhard-lctcsx in Firefox
2. select from right to left `lorem ispum` or part of it
3. wait

## The current behavior
it raise an exception

## The expected behavior
it should not raise an exception

NOTE: I did some debug:

- The exception is thrown by this [selection.extend](https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/ReactDOMSelection.js#L196) in `setOffsets`.
- Which is called by [setSelection](https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/ReactInputSelection.js#L192) because in this case, the body does not have `selectionStart`
- Which is called by [restoreSelection](https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/ReactInputSelection.js#L124) and this is because [isInDocument](https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/ReactInputSelection.js#L119) refers to the document of the element so, in this case, the document itself is contained in the element that is removed

**Comment by nawfelsekrafi** [comment]
<img width="1495" alt="image" src="https://github.com/facebook/react/assets/48069841/4446bc82-27c2-4710-8553-8b67ff0b28aa">
[Safari] also

**Comment by lorenzo-pomili** [comment]
The bug seems still present to me, and considering @nawfelsekrafi [comment](https://github.com/facebook/react/issues/26980#issuecomment-1926698875) I'm not the only one affected by it, there is something that I can do to help you with it?

**Comment by ihsanalikapahi01** [comment]
Hi everyone.
