### ISSUE TITLE
Provide a method to create synthetic events

### ISSUE THREAD

**Issue by Mintoo200** [facebook/react#26991]
## Context

Trying to implement a generic Combobox following the [W3C pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/#rps_label) without bleeding the implementation details outside the component (trying to make so you can interact with it as you would a native component).
When the user selects a value either by clicking an option or pressing `Enter`, the value of the input changes and we would like to trigger a change event.

## Observation

With vanilla JavaScript, triggering an event in those situations is quite simple: 
```js
function onClick(event) {
  setValue(event.currentTarget.textContent)
  const event = new Event('change')
  input.dispatchEvent(event)
}
```
The equivalent in React would be something like:
```js
function onClick(event) {
  setValue(event.currentTarget.textContent)
  const event = // ???
  if (props.onChange) props.onChange(event);
}
```
But onChange on native HTML elements would be called with a SyntheticEvent which contains more than regular JS events.
It is not even possible to create objects to match the SyntheticEvent interface since the values for `target` and `currentTarget` (and probably `relatedTarget` too) are readonly but only set on event dispatch: 
```ts
export class ChangeEvent<T = Element> extends Event implements React.ChangeEvent<T> {
	nativeEvent: Event;
	private propagationStopped = false;
        // TS2564: Property 'target' has no initializer and is not definitely assigned in the constructor
	readonly target: SyntheticChangeEvent<T>['target'];
        // TS2564: Property 'currentTarget' has no initializer and is not definitely assigned in the constructor
	readonly currentTarget: SyntheticChangeEvent<T>['currentTarget'];

	constructor(
		target: SyntheticChangeEvent<T>['target'],
		/* global EventInit */
		options?: EventInit,
	) {
		super('change', options);
		this.nativeEvent = this;
		target.dispatchEvent(this);
	}

	isDefaultPrevented(): boolean {
		return this.defaultPrevented;
	}

	stopPropagation() {
		super.stopPropagation();
		this.propagationStopped = true;
	}
	isPropagationStopped(): boolean {
		return this.propagationStopped;
	}

	persist(): void {
		return;
	}
}
```

## Suggestion

Expose a way to create synthetic events.
These events are [created in React source code](https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/events/SyntheticEvent.js), maybe there is a way to export those functions ? Or maybe a cleaner way would be to convert concrete SyntheticEvents from types to classes to provide constructors ?

**Comment by pcha07** [comment]
when we want to trigger a synthetic event in react we can use the createSyntheticEvent function provided by react-dom/test-utils. 

```
import {createSyntheticEvent from "react-dom/test-utils

function onClick(e) {
setValue(e.currentTarget.textContent);

const syntheticEvent = createSyntheticEvent('change', {
target: e.currentTarget,
currentTarget: e.currentTarget
)
};
if(props.onChange) props.onChange(syntheticEvent);
```

in this example the createSyntheticEvent function is used to create a synthetic event of type change. we can then pass an object with target and currentTarget properties to mimic the necessary event. using this approach we can trigger a synthetic event similar to native events and call the onChange call back with the synthetic event object.
`

**Comment by Mintoo200** [comment]
> React_**Test**_Utils [react-dom/_**test**_-utils] makes it easy to _**test**_ React components in the _**testing framework**_ of your choice.

— [React documentation](https://legacy.reactjs.org/docs/test-utils.html#overview)
Even with the best tree shaking available, I'd rather not import in my build a code that is not designed to be used outside of tests

> Note:
We recommend using [React Testing Library](https://testing-library.com/react) which is designed to enable and encourage writing tests that use your components as the end users do.

—  [React documentation again](https://legacy.reactjs.org/docs/test-utils.html#overview)
We don't even depend on ReactTestUtils since we're using React-testing-library so that would mean adding a dependency which we're not to keen on doing.

> ReactTestUtils API : 
- [act()](https://legacy.reactjs.org/docs/test-utils.html#act)
- [mockComponent()](https://legacy.reactjs.org/docs/test-utils.html#mockcomponent)
- [isElement()](https://legacy.reactjs.org/docs/test-utils.html#iselement)
- [isElementOfType()](https://legacy.reactjs.org/docs/test-utils.html#iselementoftype)
- [isDOMComponent()](https://legacy.reactjs.org/docs/test-utils.html#isdomcomponent)
- [isCompositeComponent()](https://legacy.reactjs.org/docs/test-utils.html#iscompositecomponent)
- [isCompositeComponentWithType()](https://legacy.reactjs.org/docs/test-utils.html#iscompositecomponentwithtype)
- [findAllInRenderedTree()](https://legacy.reactjs.org/docs/test-utils.html#findallinrenderedtree)
- [scryRenderedDOMComponentsWithClass()](https://legacy.reactjs.org/docs/test-utils.html#scryrendereddomcomponentswithclass)
- [findRenderedDOMComponentWithClass()](https://legacy.reactjs.org/docs/test-utils.html#findrendereddomcomponentwithclass)
- [scryRenderedDOMComponentsWithTag()](https://legacy.reactjs.org/docs/test-utils.html#scryrendereddomcomponentswithtag)
- [findRenderedDOMComponentWithTag()](https://legacy.reactjs.org/docs/test-utils.html#findrendereddomcomponentwithtag)
- [scryRenderedComponentsWithType()](https://legacy.reactjs.org/docs/test-utils.html#scryrenderedcomponentswithtype)
- [findRenderedComponentWithType()](https://legacy.reactjs.org/docs/test-utils.html#findrenderedcomponentwithtype)
- [renderIntoDocument()](https://legacy.reactjs.org/docs/test-utils.html#renderintodocument)
- [Simulate](https://legacy.reactjs.org/docs/test-utils.html#simulate)

—  [still React documentation](https://legacy.reactjs.org/docs/test-utils.html#overview)

It seems createSyntheticEvent is not standard.

**Comment by Mintoo200** [comment]
bump

**Comment by osnoser1** [comment]
I am having the same problem here, I would prefer subscribe to an event using a prop similar to onClick, onChange, etc, and not calling an addEventListener manually
