### ISSUE TITLE
Bug: react-devtools-inline crashes when Function.prototype.toString is not configurable.

### ISSUE THREAD

**Issue by Jack-Works** [facebook/react#27005]
Run the following code before loading `react-devtools-inline` and you can see the result:

```js
Object.freeze(Function.prototype)
```

It tries to delete Function.prototype.toString and crashes.

<img width="854" alt="image" src="https://github.com/facebook/react/assets/5390719/f2440555-78a1-4f81-a3d9-32d188ca1583">

<img width="972" alt="image" src="https://github.com/facebook/react/assets/5390719/48b4d50b-f354-4795-8ca3-50cd11a78801">

<img width="490" alt="image" src="https://github.com/facebook/react/assets/5390719/969b4b2e-776e-4ae8-911d-79a541ef540b">

**Comment by hoxyq** [comment]
Thanks for reporting this! I am not sure this is directly related to `react-devtools-inline`.

From what I see, this error occurs when we try to import `json5` [here](https://github.com/facebook/react/blob/main/packages/react-devtools-shared/src/devtools/utils.js#L10).

Anyone interested in digging more into this? This might require some changes to webpack or maybe there is a problem on `json5` side, I am not sure.

**Comment by Jack-Works** [comment]
bump
