### ISSUE TITLE
React - npm audit - 4 moderate severity vulnerabilities - Need solution please.

### ISSUE THREAD

**Issue by gsenthilnathan** [facebook/react#27002]
# npm audit report

semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
No fix available
node_modules/@babel/core/node_modules/semver
node_modules/@babel/helper-compilation-targets/node_modules/semver
  @babel/core  *
  Depends on vulnerable versions of @babel/helper-compilation-targets
  Depends on vulnerable versions of semver
  node_modules/@babel/core
    @vitejs/plugin-react  *
    Depends on vulnerable versions of @babel/core
    node_modules/@vitejs/plugin-react
  @babel/helper-compilation-targets  >=7.8.1
  Depends on vulnerable versions of semver
  node_modules/@babel/helper-compilation-targets

4 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by martinyis** [comment]
Hi , can I work on this issue?

**Comment by satkhan** [comment]
override in package.json and perform audit fix. 

  "overrides": {
    "semver": "~7.5.2"
  },
  
This will leave the vulnerability as we speak, but I am still figuring out what is it exactly. For now it will solve your issue
