### ISSUE TITLE
How to work with web component?

### ISSUE THREAD

**Issue by minipai** [facebook/react#2701]
I want to use https://github.com/github/time-elements

But in JSX Gotchas http://facebook.github.io/react/docs/jsx-gotchas.html
says React won't render is="" attribute.

Fill this fixed? Or there is workaround?

**Comment by jsfb** [comment]
I think this is effectively a duplicate of https://github.com/facebook/react/issues/2746, so I'm going to close as duplicate.  Please reopen if this is the incorrect action.
