### ISSUE TITLE
Bug: Unhelpful error when rendering async components without React 18.3 

### ISSUE THREAD

**Issue by nickmccurdy** [facebook/react#27014]
Versions of React that don't support async components error about attempting to render a `Promise` as a React child. While this technically makes sense to me as a React ecosystem maintainer, I don't think this error helps end users solve the problem well, compared to suggesting that React 18.3 or another compatible RSC implementation is used explicitly.

This is especially confusing when trying to test a Next 13 app, for example, as there's no documentation explaining that RSCs cannot be used in tests because Next vendors React 18.3 but installs React 18.2 locally. I considered trying to fix this in React Testing Library, but I don't think it makes sense to couple this suggestion to a specific framework or library when it potentially affects any use case where a project has two frameworks or libraries installed, including any RSC meta framework app with tests/docs/stories/etc.

React version: `<18.3`

## Steps To Reproduce

1. Install React
2. Create an async component: `async function Home() {}`
3. Render an async component: `<Home />`

## The current behavior

Throws an `Error` with `message`:
> Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

## The expected behavior

Throws an error that suggests installing React 18.3:

> Promises and async components are not valid as a React child in React `React.version`. If you meant to render an async component, install React 18.3 or use a compatible meta framework or library.

**Comment by finished-zin** [comment]
+1

**Comment by jayagr26** [comment]
Hi @nickmccurdy, 
I have started working on this, please correct me if I am wrong this will need to be fixed in every early versions right?

**Comment by nickmccurdy** [comment]
Most JavaScript package managers pin to minor and patch updates by default, and React 17 doesn't support the new roots for streaming rendering anyway, so I think a single 18.2.x patch release should be enough to improve onboarding.
