### ISSUE TITLE
Bug:  Cannot update a component (`HashRouter`) while rendering a different component *.

### ISSUE THREAD

**Issue by noemiliva** [facebook/react#27022]
React version: 18.16.0

This is the warning i get, with the stack trace. I found a similar problem (https://github.com/facebook/react/issues/18178) but i still don't understand where my problem is, maybe it's just a warning that i can't fix.
![image](https://github.com/facebook/react/assets/93923690/25edb01d-4844-4a21-b766-eb901c071ae0)

The application works correctly i just want to know if its a problem that i can fix or not.

**Comment by martinyis** [comment]
Hi , can I work on this issue?

**Comment by noemiliva** [comment]
> 
of course

**Comment by noemiliva** [comment]
I fix it. it was a problem with useNavigate(). Move it into the useEffect hook and everything will work out.
