### ISSUE TITLE
onKeyUp and onKeyDown not propagating correctly for certain keys in Chrome

### ISSUE THREAD

**Issue by offluf** [facebook/react#2703]
I noticed this while working in Chrome. Character keys don't seem to trigger the event handler.
Some keys do (e.g. Enter, Space, Tab, and some others).

Doesn't seem to happen for me in Firefox.

See here:
http://jsbin.com/kejuzipara

Though it does work as expected in the jsbin code editor output frame:
http://jsbin.com/kejuzipara/1/edit?html,js

**Comment by spicyj** [comment]
Also can't repro this in Chrome.
