### ISSUE TITLE
React developer tools

### ISSUE THREAD

**Issue by smartykarna** [facebook/react#27040]
I was installed this extenstion but i can't use coz the componnets not seen in inspect so what i do?

**Comment by merzainc** [comment]
Can you try to improve the question by telling us the browser or try attaching a screenshot.

To open the React Developer Tools, first open your broswer DevTools. On the same banner as Elements, Sources, Console, etc., there will be two new React tabs: Components and Profiler. These two tabs will only appear on sites using React. You can use fhe Components tab to inspect and debug your app.

**Comment by hoxyq** [comment]
Please check [FAQ and troubleshooting guides](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#faq).

If something is not working as inspected, feel free to open a new issue with reproducible example in some form.
