### ISSUE TITLE
Bug: React + Typescript - useReducer's initializer arg is required even though it shouldn't be

### ISSUE THREAD

**Issue by JorensM** [facebook/react#27052]
When using the `useReducer()` hook in Typescript, it complains that the hook call is missing the `initializer` function argument, even though according to [React docs](https://react.dev/reference/react/useReducer) this argument is optional.

React version:
 * react@18.2.0
 * @types/react-dom@18.2.6
 * @types/react@18.2.14

## Steps To Reproduce

1. In a React + Typescript project
2. Call the reducer hook in a functional component
3. See linter warning

Code example:

`const [ state, dispatch ] = useReducer<string[], () => {}>(() => {}, []);`

Error message:

`Expected 3 arguments, but got 2.
An argument for 'initializer' was not provided.`

## The current behavior

Linter gives warning about missing argument

## The expected behavior

Linter shouldn't give a warning as this argument is optional.

**Comment by TolgaYigit** [comment]
It appears that there is an issue with the type definitions. If we examine line 953 of the react/index.d.ts file in the DefinitelyTyped repository (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts), we can observe that the initializer argument is not optional. Curiously, on line 969, the initializer is marked as optional, even though both definitions share the same description: "overload where dispatch could accept 0 arguments."

**Comment by JorensM** [comment]
I'll make a PR on the DefiniteltyTyped repo when I have some free time.

@TolgaYigit it seems that the PR you mentioned was closed, though I'm not sure why

**Comment by eps1lon** [comment]
`useReducer<string[], () => {}>(() => {}, [])` will be the supported typing pattern in React 19. In React 18, you have to wrap the type parameters in `React.Reducer` like so: `useReducer<React.Reducer<string[], () => {}>>(() => {}, []);`
