### ISSUE TITLE
Add `ignoredHooks` to `react-hooks/exhaustive-deps`

### ISSUE THREAD

**Issue by piotr-oles** [facebook/react#27065]
Hi! :wave:
I created a hook that can run side-effects concurrently using React's scheduler and generator functions: https://github.com/piotr-oles/use-transition-effect. I called it `useTransitionEffect()` because it's like `useTransition()` but for side-effects.

### Problem
I have a problem with `react-hooks/exhaustive-deps` because this rule [uses regexp to match "effect" hooks](https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L1165). Because of that, I have to add `// eslint-disable-next-line react-hooks/exhaustive-deps` every time I use this hook. I didn't think about this when naming a hook, but now it's public and I wrote an article about it, and it would be hard to rename it now 😞 

### Proposal
There is already `additionalHooks` prop - could we add `ignoredHooks` options as well to do the opposite? I can make a PR, but I want to know if it's something you would accept 😃

**Comment by xonx4l** [comment]
an solution according to me .
