### ISSUE TITLE
Bug: Calling bundle file using browserify from react gives Syntax error: react_app_testing/src/HashBundle.js: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [facebook/react#27068]
Hello i am facing a problem with an unexpected unicode character. let me further describe my case:
I have a simple class that hashes a string named `HashFunction.js`:

```
var crypto = require('crypto')

module.exports=class HashFunction {

    constructor() {
    }

    hashString(pubkey){
        const hash = crypto.createHash('sha256');
        var sha256PublicKeyHash=hash.update(pubkey).digest();
        return sha256PublicKeyHash;
    }

}
```
i am using browserify to create the bundle with this command.

` browserify src/HashFunction.js --save utf-8-validate --standalone mybundle > src/HashBundle.js`

Here is the simple `index.html` file:

```
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <title>React App</title>
    <script src="../src/HashBundle.js"></script>
    <script src="../src/example.js"></script>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>
```
When i am trying to load the bundle file from plain js it loads successfully with this code `example.js`:
```
var mnem = new mybundle();
let hash_result=mnem.hashString("a value")
```

My problem now is when i am trying to call the bundle file from react i got a syntax error with unexpected characters:

```
./src/HashBundle.js
Syntax error: D:/Documents/IdeaProjects/react_app_testing/src/HashBundle.js: Unexpected character '�' (1:0)

> 1 | ��(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.mybundle = f()}})(function(){var define,module,exports;return (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
    | ^
  2 |
  3 | 'use strict';
```

Here is also some lines not all of them from the bundle file:

    (function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.mybundle = f()}})(function(){var define,module,exports;return (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
    'use strict';
    
    const asn1 = exports;
    
    asn1.bignum = require('bn.js');
    
    asn1.define = require('./asn1/api').define;
    asn1.base = require('./asn1/base');
    asn1.constants = require('./asn1/constants');
    asn1.decoders = require('./asn1/decoders');
    asn1.encoders = require('./asn1/encoders');
    
    },{"./asn1/api":2,"./asn1/base":4,"./asn1/constants":8,"./asn1/decoders":10,"./asn1/encoders":13,"bn.js":15}],2:[function(require,module,exports){
    'use strict';
    
    const encoders = require('./encoders');
    const decoders = require('./decoders');
    const inherits = require('inherits');
    
    const api = exports;
    
    api.define = function define(name, body) {
      return new Entity(name, body);
    };
    
    function Entity(name, body) {
      this.name = name;
      this.body = body;
    
      this.decoders = {};
      this.encoders = {};
    }
    
    Entity.prototype._createNamed = function createNamed(Base) {
      const name = this.name;
    
      function Generated(entity) {
        this._initNamed(entity, name);
      }
      inherits(Generated, Base);
      Generated.prototype._initNamed = function _initNamed(entity, name) {
        Base.call(this, entity, name);
      };
    
      return new Generated(this);
    };
    
    Entity.prototype._getDecoder = function _getDecoder(enc) {
      enc = enc || 'der';
      // Lazily create decoder
      if (!this.decoders.hasOwnProperty(enc))
        this.decoders[enc] = this._createNamed(decoders[enc]);
      return this.decoders[enc];
    };
    
    Entity.prototype.decode = function decode(data, enc, options) {
      return this._getDecoder(enc).decode(data, options);
    };
    
    Entity.prototype._getEncoder = function _getEncoder(enc) {
      enc = enc || 'der';
      // Lazily create encoder
      if (!this.encoders.hasOwnProperty(enc))
        this.encoders[enc] = this._createNamed(encoders[enc]);
      return this.encoders[enc];
    };
    
    Entity.prototype.encode = function encode(data, enc, /* internal */ reporter) {
      return this._getEncoder(enc).encode(data, reporter);
    };
    
    },{"./decoders":10,"./encoders":13,"inherits":132}],3:[function(require,module,exports){
    'use strict';
    
    const inherits = require('inherits');
    const Reporter = require('../base/reporter').Reporter;
    const Buffer = require('safer-buffer').Buffer;
    
    function DecoderBuffer(base, options) {
      Reporter.call(this, options);
      if (!Buffer.isBuffer(base)) {
        this.error('Input not Buffer');
        return;
      }
    
      this.base = base;
      this.offset = 0;
      this.length = base.length;
    }
    inherits(DecoderBuffer, Reporter);
    exports.DecoderBuffer = DecoderBuffer;
    
    DecoderBuffer.isDecoderBuffer = function isDecoderBuffer(data) {
      if (data instanceof DecoderBuffer) {
        return true;
      }

Here is my simple react js code:

```
import { useState, useEffect} from "react";
import React from 'react';
import {HashBundle} from '../HashBundle'
function Test2() {
    const [inputValue, setInputValue] = useState("");

    useEffect(() => {
        var obj = new mybundle();
        let hash_result=obj.hashString("a value")
        setInputValue(hash_result)
    }, [inputValue]);

    return (
        <div>
            <h2>Current Value: {inputValue}</h2>
        </div>
    );
}

export default Test2;
```

Why is this happening??? how to bypass the  `Unexpected character '�' (1:0)`??? Do I load correct the js from react???

**Comment by RandeepSingh72** [comment]
@PanagiotisDrakatos 
you import {HashBundle} from '../HashBundle' but never use in Test2

**Comment by PanagiotisDrakatos** [comment]
@RandeepSingh72 thats correct because i used this command `browserify src/HashFunction.js --save utf-8-validate --standalone mybundle > src/HashBundle.js` which means that i can use the mybundle constructor  from HashBundle.js
