### ISSUE TITLE
Bug:  Different word cannot be used in place of  'children' as prop

### ISSUE THREAD

**Issue by Danish-Official** [facebook/react#27073]
For passing child components, destructuring is allowed only with 'children' prop keyword. The application is treating 'children' as keyword and does not accepts any other word/synonym.

React version: 18.2.0

## Steps To Reproduce

1.  Please allow other words too in place of word 'children' for passing child components as prop.

Link to code example:
[https://codesandbox.io/s/3nr4x2?file=/App.js&utm_medium=sandpack](https://codesandbox.io/s/3nr4x2?file=/App.js&utm_medium=sandpack)

**Comment by ayushkavad** [comment]
hey! 
you can pass Avatar component as a props inside Card component and then you can destructure props like this

```Javascript
import Avatar from './Avatar.js';

function Card({ avatarChildren }) {
  return (
    <div className="card">
      {avatarChildren}
    </div>
  );
}

export default function Profile() {
  return (
    <Card avatarChildren={<Avatar
        size={100}
        person={{ 
          name: 'Katsuko Saruhashi',
          imageId: 'YfeOqp2'
        }}
    />}>
    </Card>
  );
}
```

**Comment by Danish-Official** [comment]
Yes we can do like that. But If there is a group of multiple components between opening and closing tag of Card component then passing them as prop and destructuring them would be a tedious process, so for shorthand property we should use {children} but the concern is that react does not allows other word than children. And react docs mentions that children is not a keyword which is a contradiction.

**Comment by kriskw1999** [comment]
Hi, I am thinking about the practical reasons of this issue. Why we should need a different name from children, I mean children is a reserved keyword for any React component and we can have one children per component, and for me in all use cases that I encountered was cool. Can you provide a real-world scenario in which this may help in any way? Thank you very much!

**Comment by Danish-Official** [comment]
children is not a reserved keyword in react, it is a convention followed by many developers. My concern is why to limit it unnecessarily to a terminology. This issue doesn't have any big impact, but let's say if someone wants to use any other synonym like content, subComponents, dependentComponents, etc. then why not to give them that freedom.

**Comment by kriskw1999** [comment]
Hope that this may be helpful https://github.com/facebook/react/blob/fdc8c81e07e9b3b49604afe524ee6d130fd3e03e/packages/react/src/jsx/ReactJSXElement.js#L16

**Comment by BrunoHenrique00** [comment]
Hey @Danish-Official, you can easily solve your problem with some Javascript features, for example [Destructuring Assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

Here is how your code in sandbox should look like 

```js
function Card({ children: avatar }) {

  return (
    <div className="card">
      {avatar}
    </div>
  );
}
```

when restructuring just whatever name you want
` { children: NAME_YOU_NEED }`
