### ISSUE TITLE
Bug: useCallback do not respect dependencies

### ISSUE THREAD

**Issue by Skriptach** [facebook/react#27076]
useCallback do not update inside values to most latest

React version: 18.2.0

I have a simple code

```
    const [url, setUrl] = useState('');
    const [valid, setValid] = useState(false);

    const generate = useCallback(() => {
        if (valid) {
            // do stuff with url
        }
    }, [valid, url]);

    const validate = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value;

        if (isValid(value)) {
            setUrl(value);
            setValid(true);
            console.log({
                url: value,
            });
        } else {
            setValid(false);
            setUrl('');
        }
    }, []);
```

## The current behavior
When `validate` callback handler was triggered it works fine and update `valid` and `url` state value by using corresponding setState functions. After click on a button invokes handler `generate`. But `value` and `url` are in their initial state. Despite useCallback have them as a dependencies.

Do not suggest use setSate to get current value.
1. What if there are much more dependencies? Let's say 7. That will lead us to situation of insane nesting levels
2. It contradicts documentation and a whole point of dependency list

## The expected behavior
Keep latest values

**Comment by ogagaCodes** [comment]
Following...

**Comment by kriskw1999** [comment]
Can you provide a sandbox instead of plain code in order to be able to understand easily how to reproduce the bug? 
Just an example of a sanbox: https://codesandbox.io/s/optimistic-sky-zhz7qm?file=/src/App.tsx

**Comment by Swapnilchavan13** [comment]
const [url, setUrl] = useState('');
const [valid, setValid] = useState(false);

const generate = useCallback(() => {
    setValid((prevValid) => {
        if (prevValid) {
            // do stuff with url
        }
        return prevValid;
    });

    setUrl((prevUrl) => {
        if (valid) {
            // do stuff with prevUrl
        }
        return prevUrl;
    });
}, [valid]);

const validate = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;

    if (isValid(value)) {
        setUrl(value);
        setValid(true);
        console.log({
            url: value,
        });
    } else {
        setValid(false);
        setUrl('');
    }
}, []);

By using the functional update form, you ensure that the state is updated correctly and reliably. It automatically captures the latest state values without needing to include them in the dependencies list. This makes it easier to manage state updates, especially when dealing with complex scenarios and many dependencies. It avoids nesting functions and keeps your code cleaner and more straightforward.

**Comment by Swapnilchavan13** [comment]
const [url, setUrl] = useState('');
const [valid, setValid] = useState(false);

const generate = useCallback(() => {
    setValid((prevValid) => {
        if (prevValid) {
            // do stuff with url
        }
        return prevValid;
    });
    setUrl((prevUrl) => {
        if (valid) {
            // do stuff with prevUrl
        }
        return prevUrl;
    });
}, [valid]);
const validate = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;

    if (isValid(value)) {
        setUrl(value);
        setValid(true);
        console.log({
            url: value,
        });
    } else {
        setValid(false);
        setUrl('');
    }
}, []);
