### ISSUE TITLE
Bug: Suspense does not work in Server Components with Safari on macOS or iOS

### ISSUE THREAD

**Issue by josephearl** [facebook/react#27089]
React version: 18

## Steps To Reproduce

See this reproducer using Next.js https://codesandbox.io/p/sandbox/quirky-danilo-nycr3t

## The current behavior

Open the app in Chrome: https://nycr3t-3000.csb.app/
Observe that the page is rendered quickly and "Loading car..." is displayed until the car has loaded

Open the app in Safari (either on macOS or iOS): https://nycr3t-3000.csb.app/
Observe that the page does not render anything until the car has loaded and never displays the "Loading car..." message

## The expected behavior

Behaviour on Safari is the same as Chrome and fallback content is displayed until the slow operation has resolved

**Comment by dfiedlerx** [comment]
Any solution for this? I ran into the same problem and the use of suspense is essential for my use case.

**Comment by josephearl** [comment]
bump
