### ISSUE TITLE
Bug: React breaks HTMLInputElement.prototype.value interceptions

### ISSUE THREAD

**Issue by SF97** [facebook/react#27092]
React version: 18.2.0

## Steps To Reproduce

1. Create a React application with an input element of type 'text'
2. With another script that runs **after react-dom**, intercept the calls to HTMLInputElement.prototype.value, which runs a piece of code X whenever someone accesses an input value
3. Access the input element `.value`

The piece of code X, added in step 2, does not run. This is due to React intercepting the HTMLInputElement.prototype.value itself, and not running functions that were added **after** React loads. If the interception is made before React loads, it will work normally

Link to code example: [https://github.com/SF97/react-input-element-bug](https://github.com/SF97/react-input-element-bug)

## The current behavior

React does not run functions that intercept HTMLInputValue.prototype.value getter that were introduced after React is loaded

## The expected behavior

React runs functions that intercept HTMLInputValue.prototype.value getter that are done in any time frame, whether it was before or after React installs its descriptor

**Comment by SF97** [comment]
Made a PR that fixes this issue - https://github.com/facebook/react/pull/27093

**Comment by SF97** [comment]
bump

**Comment by xueqianz** [comment]
In my case, 
I created a `HTMLInputElement` and gave that a ref (`foo`, for example), then I want to change the value of the input by using `this.foo.value=123`.
And I got the `Illegal invocation` error as follwoing:
```
Uncaught TypeError: Illegal invocation
    at Proxy.set (react-dom.development.js:1661:1)
    ...
```
Is this familiar with your issue?

**Comment by Md-124** [comment]
hi @SF97 are you sure this error occurs I tried to reproduce the same and interceptor calls are working fine check this out
https://stackblitz.com/edit/vitejs-vite-b1wd8k?file=index.html


am i doing something wrong?

**Comment by SF97** [comment]
> hi @SF97 are you sure this error occurs I tried to reproduce the same and interceptor calls are working fine check this out https://stackblitz.com/edit/vitejs-vite-b1wd8k?file=index.html
> 
> am i doing something wrong?

Hello
This bug happens if the interceptor is installed after React DOM, which I believe is not happening in your example. If you add a `setTimeout` to the proxy installation to ensure it's installed after React DOM, you'll be able to reproduce it. Check https://stackblitz.com/edit/vitejs-vite-r9efju?file=src%2FApp.tsx

**Comment by SF97** [comment]
> In my case, I created a `HTMLInputElement` and gave that a ref (`foo`, for example), then I want to change the value of the input by using `this.foo.value=123`. And I got the `Illegal invocation` error as follwoing:
> 
> ```
> Uncaught TypeError: Illegal invocation
>     at Proxy.set (react-dom.development.js:1661:1)
>     ...
> ```
> 
> Is this similar to your issue?

Hello
I don't think so! I think that would still happen regardless of this issue

**Comment by Md-124** [comment]
@SF97 what exactly is the error, like the value is getting intercepted could you share a screen recording of the error?

**Comment by layerok** [comment]
@SF97 I got the same error using rc-number-input with react-hook-form 
```tsx
<NumberInput {...register('price')}/>
```

**Comment by layerok** [comment]
I recreated the issue
```js
const trackValueOnNode = (node) => {
  const valueField = 'value'
  const descriptor = Object.getOwnPropertyDescriptor(node.constructor.prototype, valueField);

  let currentValue = '' + node[valueField]; 

  if (node.hasOwnProperty(valueField) || typeof descriptor === 'undefined' || typeof descriptor.get !== 'function' || typeof descriptor.set !== 'function') {
    return;
  }

  const get = descriptor.get,
      set = descriptor.set;
  Object.defineProperty(node, valueField, {
    configurable: true,
    get: function () {
      return get.call(this);
    },
    set: function (value) {
      currentValue = '' + value;
      set.call(this, value);
    }
  });
}

let node = document.createElement('input');
trackValueOnNode(node);

node = new Proxy(node, {}); // this is what rc-number-input is doing. it wraps node into a proxy and overwrites original node reference

node.value = 'f' // this is what react-hook-form does. it sets value in ref callback

```
