### ISSUE TITLE
Custom classes for ReactCSSTransitionGroup instead of hard coding the post-fix "-enter"...

### ISSUE THREAD

**Issue by bitplanets** [facebook/react#2709]
I would like to have more control on the classes that transition automatically add.

#How could be done

    React.addons.CSSTransitionGroup({
        enterClass       : 'c0',
        enterActiveClass : 'c1',
        leaveClass       : 'c2',
        leaveActiveClass : 'c3',
    },

This will not break the current API because you still can do

     transitionName : 'c0'

#Do you accept pull requests? 

Here is the file to be changed https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroupChild.js

Related to but not the same as https://github.com/facebook/react/issues/2680

**Comment by spicyj** [comment]
This is close enough to #2680 that I'll close this one and track there.
