### ISSUE TITLE
Bug:  Unable to catch errors In React 18.2.0 version

### ISSUE THREAD

**Issue by RajaTheKing826** [facebook/react#27102]
Unable to catch errors In React 18.2.0 version

I have Written an ErrorBoundary like this.

```
const FallBackComponents = () => {
   console.log('Fall Back Component')
   return <h1>FallBack COmppnent</h1>
}

export class ErrorBoundary extends React.Component<any, any> {
   constructor(props) {
      super(props)
      this.state = { error: null, errorInfo: null }
   }

   componentDidCatch(error, errorInfo) {
      // Catch errors in any components below and re-render with error message
      this.setState({
         error: error,
         errorInfo: errorInfo
      })
      // You can also log error messages to an error reporting service here
   }

   render() {
      if (this.state.errorInfo) {
         // Error path
         return <FallBackComponents />
      }
      // Normally, just render children
      return this.props.children
   }
}
```

and in my code I have wrapped my component  with this ErrorBoundary like this.

  ```
      <ErrorBoundary>
         <DummyComponent />
         </ErrorBoundary>
```

In the DummyComponent im just throwing the error like

```

Function DummyComponent=()=>{
     throw Error("Somethingwent wrong")
    return <h1>Dummy Component</h1>
}

```

But im not getting my fall back component , instead getting only the Error screeen. Can anyone help me to getout of this.

@zpao   @acdlite

**Comment by BrightTNut** [comment]
hi there i read code and problem i thing same suggestion for it
1. import the necessary dependencies correctly.
2. 2. Verify that the FallBackComponents component is correctly defined and exported. Ensure that you import and use it properly in your ErrorBoundary component.

I thing need to use  and you can check my below code 
class DummyComponent extends React.Component {
  render() {
    // Simulating an error in the component
    throw new Error('Dummy Component Error');
    return <div>Dummy Component</div>;
  }
}

// Wrap the component with ErrorBoundary
const App = () => {
  return (
    <ErrorBoundary>
      <DummyComponent />
    </ErrorBoundary>
  );
};

**Comment by BrightTNut** [comment]
I can try to solve it can i ?

**Comment by loo41** [comment]
@RajaTheKing826  It works correctly

https://codesandbox.io/s/vibrant-phoebe-jwvxt8?file=/src/App.js
