### ISSUE TITLE
Bug: Vulnerable dependencies (indirect security issues ??)

### ISSUE THREAD

**Issue by davidz1337** [facebook/react#27110]
Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are over 72 vulnerable dependencies present. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the package-lock file I scanned: https://vulert.com/vuln-scan/list/9916f4f2-3247-4d91-ad95-4daf84c45575

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

P.S. this is the lock file i scanned: https://github.com/facebook/react/blob/e3fb7c1de1ed375e32397b3502a30b8ae4c2db9f/yarn.lock

Thank you.

**Comment by bdurrer** [comment]
Note that this user opened very similar-looking issues on over 30 of the most common github repositories, likely just to promote their service.

They don't care that the claimed issues are all dev dependencies.

![history](https://user-images.githubusercontent.com/1398469/255848277-f4783098-f69e-40ae-807b-5b0c11addbaf.png)
![profile](https://user-images.githubusercontent.com/1398469/255848334-0415ca21-2655-40dc-b732-62175742d811.png)
