### ISSUE TITLE
[DevTools Bug]: Chrome extension gets disconnected from the page after 30sec of inactivity

### ISSUE THREAD

**Issue by jimousse** [facebook/react#27119]
### Website or app

https://react.dev/

### Repro steps

Steps:
1. go to a react page like https://react.dev/
2. open the devtools Components tab, everything works correctly.
3. change tab (a non react one) and wait 30 sec - 5 min (not super exact)
4. go back to the tab that has the react page you're debugging
5. the Components does not work anywore: you can't select and view components on the page.

![Screenshot 2023-07-17 at 3 40 10 PM](https://github.com/facebook/react/assets/6637867/6e04b8e9-c219-4a2e-a2c3-d6f2f3e61b2f)

My guess is that it's related to Chrome killing the service worker after inactivity on the page. See https://bugs.chromium.org/p/chromium/issues/detail?id=1152255#c185

![Screenshot 2023-07-17 at 3 41 13 PM](https://github.com/facebook/react/assets/6637867/c59e359a-f3ee-4af3-a331-fd6afca8dd46)

Going back to the page doesn't seem to wake the serviceworker up.

Chrome: Version 114.0.5735.198 (Official Build) (x86_64)
React Extension: 4.28.0
macOS: 13.4.1

### How often does this bug happen?

Every time

**Comment by bharathkalyans** [comment]
Or could it be that some extensions are causing this issue?

**Comment by jimousse** [comment]
> 

Google made some changes on the lifetime of a service worker since Chrome 110: https://developer.chrome.com/docs/extensions/whatsnew/#m110-sw-idle
It seems to me that the extension is not prepared to deal with an inactive service worker.

**Comment by MrWangJustToDo** [comment]
🙏

**Comment by iwanderer** [comment]
Yes, me too..
![image](https://github.com/facebook/react/assets/5506208/dc10498e-81b9-4b04-98bb-2cce036bba89)
