### ISSUE TITLE
[DevTools Bug]: Deprecated __REACT_DEVTOOLS_GLOBAL_HOOK__ ????

### ISSUE THREAD

**Issue by morahgeist** [facebook/react#27112]
### Website or app

https://github.com/open-source-labs/reactime/tree/master/src

### Repro steps

Hi, I have heard that the new versions of React will not support the REACT_DEVTOOLS_GLOBAL_HOOK. If there any information about this update that you can share. Is there a new way to achieve the same result of using the REACT_DEVTOOLS_GLOBAL_HOOK but with a different method? What is the future of React without the REACT_DEVTOOLS_GLOBAL_HOOK?

Reactime and React Inspector in the Chrome store use this hook

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Hey @morahgeist,

We don't have plans on removing the global hook currently, this is still the primary way on how React and React DevTools interact, but it doesn't mean that any other extensions / applications should inject into this hook and use it. You should always take that into account that APIs inside this hook can have breaking changes.

In a long term, there are plans to implement more reliable API contract of what DevTools can expose from React to other tools, but I don't have any timelines and details yet.
