### ISSUE TITLE
Bug: "react-dom/client" render function fail on IE10 (with polyfills)

### ISSUE THREAD

**Issue by g-rusev** [facebook/react#27125]
We have a working React application that supports Internet Explorer 10  (IE10) (using polyfills).  We need to support it for some reasons (please, don't ask).

As your docs recommends here ([UPDATES TO CLIENT RENDERING API](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis)), we changed the way it renders from the 'ReactDOM.render' to 'createRoot'.

After the update of the rendering method, the application fails to run on IE10.

Within the same conditions:
This code
`ReactDOMOld.render(<App/>, document.getElementsByTagName('body')[0]);`
works correctly.

With no other changes, replacing the code above with:

`ReactDOMNew.createRoot(document.getElementsByTagName('body')[0]).render(<App/>);`

breaks the entire app with the error:

```
SCRIPT5007: Unable to get property 'type' of undefined or null reference
react-dom.development.js
```

Here is a minimal project that isolates the problem:
[https://github.com/g-rusev/react-renter-test/](https://github.com/g-rusev/react-renter-test/)

This project support IE 10 and with changing just one line, you can see the difference that the two render methods produces.

React version: 18.2.0

## Steps To Reproduce

1. clone https://github.com/g-rusev/react-renter-test/    (see the 'readme.md')
2. run "npm i" to install dependencies.
3. build the project with "npm run dev" and open it in IE10.

Open ./src/App.jsx. At the bottom there are the two render methods to test with.

When the app is build with the old ReactDOM.render method (just un-comment its line in the App.jsx) -  it runs correctly.

When the app is build with the new 'createRoot' method (just un-comment its line in the App.jsx) - it fails.

Link to code example:
https://github.com/g-rusev/react-renter-test/

**Comment by g-rusev** [comment]
You answer seems to me running away from responsibility.
Switching to another framework and rewriting the entire working application is not an option.- all because of one buggy function I pointed out exactly.
The entire current application works fine in IE 10  (with polyfills as recommended in your legacy docs) and I pointed an exact function which fails.
If you wont support the IE, just drop the support globally and officially - otherwise its a poor excuse not to fix a buggy functions, but drop the already working one.

**Comment by busybox11** [comment]
preact and nerve provide close or even near-complete compatibility with the existing React APIs - they're still an option to consider for updated react IE development IMO.

They have indeed already dropped the support globally and officially, as some features are not polyfillable in IE. You might not make use of them with your existing codebase, but these issues will still exist and you might encounter some of them in the near future.
