### ISSUE TITLE
Bug: Text duplication in controlled component with iOS Japanese kana IME 

### ISSUE THREAD

**Issue by eoghanmcilwaine** [facebook/react#27135]
React version:
18.2.0

## Steps To Reproduce

1. In an iOS device (or simulator) with the Japanese Kana keyboard selected as input method, using Safari (I haven't tested with other browsers)
1. Enter text into a controlled component that modifies its input (code example below)
2. Observe duplicate text entered

Link to code example:

https://codesandbox.io/s/react-kana-ime-controlled-component-input-qzx7r9

Example code for the controlled component. This one inserts a hyphen (-) between each entered character.

```javascript
import { useState, useCallback } from "react";

export default () => {
  const [value, setValue] = useState("");
  const onInput = useCallback(e => {
    const { value } = e.target;
    const formatted = value.replace(/-/g, "").split("").join("-");
    setValue(formatted);
  }, []);

  return (
    <div>
      <input type="text" value={value} onInput={onInput} />
      <p>Value: {value}</p>
    </div>
  );
};
```

## The current behavior

On entering the third and subsequent characters, the entire content of the input area is duplicated leading to incorrect content in the input.

https://github.com/facebook/react/assets/1396207/68a7c0a1-096c-49dc-a817-fd1fafce3a90

I believe this is related to the _composition_ behavior of the kana IME. Might be related to issue https://github.com/facebook/react/issues/26805

## The expected behavior

Entered text should simply appear with each character separated by a hyphen. This is the behavior when the standard english keyboard is used.

**Comment by eoghanmcilwaine** [comment]
Hey @suchangv , thanks for that workaround - very useful!

For context, I noticed this issue in a phone number input field that formats the input as it is entered, in real time. So this wouldn't be possible using the workaround, as the formatting would only happen on blur.

I wonder if this is fixable on the React level? Or does it indicate a broader problem with IME compositions in general? 🤔

**Comment by yanniznik** [comment]
@eoghanmcilwaine did you ever find a solution for a live input mask? We're facing the same issue
