### ISSUE TITLE
Collision between two React copies running on the same DOM (ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0.2)

### ISSUE THREAD

**Issue by chandlerprall** [facebook/react#2713]
I'm working on a Chrome extension that injects data into the current page. Chrome extensions have a concept of a "content script" which has access to the page's DOM but not any of the page's JavaScript variables. This means I can include React for that page's DOM but there may already be React running on the page, and there won't be any conflicts in the code. However, with two copies of React running I ran into `Uncaught Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same`data-reactid`: .0.0.2` for obvious reasons.

My solution was to modify my extension's version of React to change DOMProperty.ID_ATTRIBUTE_NAME to `data-extensionreactid` to avoid these conflicts. Is there a better way than modifying React's source?

**Comment by FBerthelot** [comment]
@syranide I have exactly the same issue, but i can't implement your solution in my code. 
I try to exec the following code before require react/addons itself, but there is no changes 
```javascript
require('react/lib/DOMProperty').ID_ATTRIBUTE_NAME = 'data-reactid-nf';
```
I've also tried to directly change the node_modules/react/addons.js file and make it look like that : 
```javascript
require('./lib/DOMProperty').ID_ATTRIBUTE_NAME = 'data-reactid-nf';
module.exports = require('./lib/ReactWithAddons');
```
And this just works fine.

So my final question is : is there a solution to change react attribute name inside my own code ?

**Comment by azproduction** [comment]
@FBerthelot if you are using webpack Hot Loader it could brake things. Basically you should take `ID_ATTRIBUTE_NAME`-magic out of first `jsx` file in order to apply patch.
```js
// bootstrap.js
require('react/lib/DOMProperty').ID_ATTRIBUTE_NAME = 'data-reactid-nf';
require('./main.jsx');
```

**Comment by FBerthelot** [comment]
Thanks @azproduction but unfortunatly, i don't use webpack hot loader. By the way, I didn't know this tool. It seem fun, i will try it a day ;)

Personnaly i did that awful quick fix in my jenkins build:
```bash
if (! grep -q data-reactid-nf "./node_modules/react/addons.js"); then
     sed -i '1irequire("./lib/DOMProperty").ID_ATTRIBUTE_NAME = "data-reactid-nf";' ./node_modules/react/addons.js
fi
```
When i will more time, i will change all require('react/addons'); by my custom implementation of react, but i still find this ugly. Less ugly but still ugly.

**Comment by calbertts** [comment]
Due to this issue doesn't allow me to use dropzone.js as a plugin because I can't create new elements without that fucking KEY.

Sorry, but I think that this isn't a good approach, please!.. get ride of it.
My love is dying...

**Comment by Feawel** [comment]
Go the same error while trying to add Zendesk widget :/
