### ISSUE TITLE
Bug: doesn't connect via the network outside the host

### ISSUE THREAD

**Issue by randomusert** [facebook/react#27145]
## Steps To Reproduce

1.create react app
2.run the app and try to conecmt to the ip one on other device

## The current behavior
it doesn't connect via the ip in the network outside the host

## The expected behavior
connects to the server

**Comment by blasko03** [comment]
have you tried to run with this command?

`HOST=0.0.0.0 npm run start`

**Comment by randomusert** [comment]
> have you tried to run with this command?
> 
> `HOST=0.0.0.0 npm run start`

no

**Comment by randomusert** [comment]
> have you tried to run with this command?
> 
> `HOST=0.0.0.0 npm run start`

how can i do that?
