### ISSUE TITLE
Bug: horizontal scroll to bad white space on mobile version of application

### ISSUE THREAD

**Issue by Bhaney44** [facebook/react#27143]
React version: 18

## Steps To Reproduce

1. Create react app
`npx create-react-app my-app`
2. Install router 
`npm install react-router-dom`
3. Apply code

Link to code example: https://stackoverflow.com/questions/76750861/stop-horizontal-scrolling-in-a-react-app-on-mobile

## The current behavior

The problem is that react is for an unknown reason adding white space a horizontal scroll to my webpage. I traced the page elements in red to identify the problem. But, there should be no element below the footer, which appears to be causing the error.

<img width="405" alt="2Ggxo" src="https://github.com/facebook/react/assets/43055154/0cec0a98-8e1e-4193-94d5-2c9635ad2385">

This appears to be a common problem with many solutions online, but none have worked for me. I have gone through several steps to fix the problem. For example:

`width:100vw;` and
`overflow-x:hidden;`

were added to the `.css` file. I also added:

```
body {
  overflow-x: hidden;
}
```

to the `.css `file.

I tried switching from `width: 100vw` in the footer to `max-width: 100vw` and then removing it all together. Essentially, there should not be extra space on the right of the mobile screen and I do not have a reason why this bug would occur.

## The expected behavior

The expected behavior is that there is no horizontal scroll or extra white space on the right side of the screen in mobile. Thanks in advance for advice or solutions.

**Comment by Akshaybagai52** [comment]
Hey @Bhaney44  can you assign this issue to me ?

**Comment by Bhaney44** [comment]
> Hey @Bhaney44 can you assign this issue to me ?

Yes. What do you mean exactly?

**Comment by Bhaney44** [comment]
The problem is in the `index.html` file. The viewport should be changed as such:



`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">`
