### ISSUE TITLE
Bug: async action transition branch not committed for 5000ms

### ISSUE THREAD

**Issue by ellemedit** [facebook/react#27156]
React version: canary (next.js)

## Steps To Reproduce

1.access https://codesandbox.io/p/sandbox/blissful-sky-3pm4l7?file=%2Fapp%2FClientButton.tsx%3A21%2C40
2. click ‘Wait in 0-4900ms’ buttons, it works well. pending state updated as promise resolved.
3. click ‘Wait in 5000ms’ button, u can see endless pending status even if promise resolved.

Link to code example: https://codesandbox.io/p/sandbox/blissful-sky-3pm4l7?file=%2Fapp%2FClientButton.tsx%3A21%2C40

## The current behavior

only buttons that takes 4900ms less async state transition actions being committed their changes

## The expected behavior
all buttons and async state transition actions should commit their changes

**Comment by Beingbook** [comment]
original issue: https://github.com/vercel/next.js/discussions/53215#discussion-5442900

**Comment by Beingbook** [comment]
expermenting test code:

```

  // @gate enableAsyncActions
  it('transition should be commited for long async action', async () => {
    let startTransition;
    function App() {
      const [isPending, _startTransition] = React.useTransition();
      startTransition = _startTransition;
      Scheduler.log(`isPending:${JSON.stringify(isPending)}`);
      return null;
    }
    const root = ReactDOMClient.createRoot(container);
    await act(async () => {
      root.render(<App />);
    });
    assertLog(['isPending:false']);

    let resolvePromise; 
    let promise = new Promise((resolve) => {
      resolvePromise = resolve;
    });
    await act(() => {
      startTransition(() => promise);
    });
    assertLog(['isPending:true']);

    await act(async () => {  
      Scheduler.unstable_advanceTime(5000);
      resolvePromise();
    });
    assertLog(['isPending:false']);

    await act(() => {
      root.unmount();
    });
  })
```

**Comment by ellemedit** [comment]
@acdlite could you look this? I'm not sure this is bug or not. If this is bug, could you suggest correct patch direction to make PR?
