### ISSUE TITLE
Feature Request (react-hooks/exhaustive-deps): `ignoreObjectReferences` flag

### ISSUE THREAD

**Issue by Newbie012** [facebook/react#27160]
React version: 18.2.0

## Steps To Reproduce

1. Create a component that uses `useDisclosure()` from a 3rd party library to manage a modal's visibility status.
2. Inside the component, add a useEffect hook that depends on a `onOpen` method of the `disclosure` object returned from `useDisclosure()`.
3. ESLint raises a warning suggesting to replace `disclousure.onOpen` with `disclosure` in the dependency array of the `useEffect()` hook.

```ts
import React from 'react';
import { useDisclosure } from 'library-a';
import { useQuery } from 'library-b';

function MyComponent() {
    const disclosure = useDisclosure();
    const query = useQuery({ queryKey: ["..."], queryFn: () => Promise.resolve(1) });

    React.useEffect(() => {
        if (!query.isSuccess) return;
        disclosure.onOpen();
    }, [disclosure.onOpen, query.isSuccess]);
     // ^^^^^^^^^^^^^^^^^ ESLint will suggest changing 'disclosure.onOpen' to 'disclosure'
 
    ...
}
```

## The current behavior

ESLint's `react-hooks/exhaustive-deps` rule suggests changing the dependency `disclosure.onOpen` to `disclosure`. This happens because the ESLint plugin checks for dependencies at the reference level and does not go deeper into object properties.

As a workaround, one alternative is to destructure the `disclosure` object to acquire `onOpen`:

```jsx
const { onOpen } = useDisclosure();
```

And then use `onOpen` directly in the `useEffect` dependencies. But this approach has limitations: 

1. It can raise uncertainty when there are multiple hooks like `useDisclosure` because it's not instantly clear from which object the destructured property originated.
2. In TypeScript, additional verbosity is introduced because you will need to specify the type of the destructured property, effectively writing the properties twice.

Another approach would be to write `disclosure.onOpen.call(null)`, but it's really awkward.

## The expected behavior

It would be beneficial if ESLint could recognize that the dependency on `dislcosure.onOpen` does not necessitate a dependency on `disclosure` in instances where object properties are stable across renders or are reliably memoized.

I propose a feature where a new setting, such as `ignoreObjectReferences`, could be introduced in the "react-hooks/exhaustive-deps" rule configuration. When `ignoreObjectReferences` is `true`, ESLint should treat the properties and methods of an object as individual dependencies, ignoring the reference of the object itself. This would instead allow us to just include `dislosure.onOpen` in our dependency arrays, thus circumventing unnecessary rerenders caused by the change of the object reference.

I'll be happy to raise a PR for this.

**Comment by hichemfantar** [comment]
I agree that this needs to be fixed.

**Comment by hichemfantar** [comment]
Related #16265

**Comment by rickhanlonii** [comment]
This is because when you call `disclosure.onOpen()` you're passing the `this` value of disclosure to `onOpen`, which can be stale. Since linters can't do full program analysis to confirm if `disclosure` reads `this`, we can't detect whether it's safe. De-structuring will not pass the `this` context to `onOpen` and that guarantees you won't read a stale closure.

**Comment by mmkal** [comment]
For anyone else who's annoyed by this when using react-query, below is a horrible hack you can now do with eslint's flat config.

Example:

```ts
import {useMutation} from '@tanstack/react-query'

export const MyComponent = () => {
  const signInMutation = useMutation(...)

  useEffect(() => {
    signInMutation.mutate()
  }, [signInMutation.mutate])

  return <>signed in: {signInMutation.status}</>
}
```

The above code is fine, but exhaustive-deps complains because in theory `signInMutation.mutate()` might use `this` (i.e. have the whole of `signInMutation` as a dependency. But in reality, react-query just defines `.mutate` as a static function which doesn't use `this`. So `signInMutation.mutate` is good enough as a dependency. And the suggestion that you use `[signInMutation]` as the dependency array is far worse, because that will re-run the effect every time `signInMutation.status` changes. With the plugin as it is you have to do awkward destructuring, along with renaming so you don't have mysterious `mutate` variables everywhere:

```ts
import {useMutation} from '@tanstack/react-query'

export const MyComponent = () => {
  const {mutate: doSignIn, ...signInMutation} = useMutation(...)

  useEffect(() => {
    doSignIn()
  }, [doSignIn])

  return <>signed in: {signInMutation.status}</>
}
```

But you can shim the source code of the react-hooks plugin and use the shimmed version in your flat config:

```ts
import * as fs from 'fs'

export const getShimmedReactHooks = () => {
  // rely on the fact that the react-hooks plugin exports everything in one big file. use the development build to avoid minimised code
  const reactHooksPluginPath = require.resolve('eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js')
  const reactHooksPluginCode = fs.readFileSync(reactHooksPluginPath, 'utf8')
  const exports = {} // this needs to be in scope for the eval below - it will set exports.rules = ... as a side effect

  const insertAfter = `function getDependency(node) {`
  const parts = reactHooksPluginCode.split(insertAfter)
  if (parts.length !== 2) {
    throw new Error(
      `Can't shim react-hooks plugin. Code at ${reactHooksPluginPath} expected to contain the following line exactly once:\n${insertAfter}`,
    )
  }

  const newReactHooksPluginCode =
    parts[0] +
    insertAfter +
    `
      // BEGIN HACK HACK HACK - react-hooks plugin is annoying about useMutation, this shims it by saying the dependency for 'foo.mutate' is 'foo.mutate' rather than 'foo' (techincally this could cause problems if 'foo.mutate()' relied on this-binding, but react-query doesn't)
      if ((node.parent.type === 'MemberExpression' || node.parent.type === 'OptionalMemberExpression') && node.parent.object === node && node.parent.property.name !== 'current' && !node.parent.computed && node.parent.property.name === 'mutate') {
        return getDependency(node.parent)
      }
      // END HACK HACK HACK - react-hooks plugin is annoying about useMutation, this shims it
  
    ` +
    parts[1]

  if (process.env.DEBUG_REACT_HOOKS_HACK) {
    const changedPath = reactHooksPluginPath + '.changed.js'
    fs.writeFileSync(changedPath, newReactHooksPluginCode)
    // eslint-disable-next-line no-console
    console.log('Wrote changed react-hooks plugin to', changedPath)
  }

  eval(newReactHooksPluginCode) // this sets to exports.rules = ... as a side effect 😬

  // @ts-expect-error exports has type {}
  if (!exports.rules?.['exhaustive-deps']) {
    throw new Error(`Failed to shim react-hooks plugin. Exports: ${JSON.stringify(Object.keys(exports))}`)
  }

  return exports as typeof import('eslint-plugin-react-hooks') // note: this is typescript, but you can just remove the ` as ...` part if you want js
}
```

Then use in your config:

```ts
import {getShimmedReactHooks} from './shim-react-hooks-plugin'

const reactHooks = getShimmedReactHooks() // now you can use `reactHooks` exactly like the "real" one that you'd get from `import reactHooks from 'eslint-plugin-react-hooks'`

export default [
  // ...
  reactHooks.configs['recommended-latest'],
]
```

This makes the first code snippet lint fine.

I think a configuration option to tell the rule to assume certain patterns are static/not this-bound would make a lot of sense.
