### ISSUE TITLE
[React 16] Bug: true and false clauses being rendered simultaneously

### ISSUE THREAD

**Issue by pedrobernardina** [facebook/react#27176]
## React version

16.14.0
16.12.0

## The current behavior

I'm experiencing a problem in one of my projects that seems to be a React bug. I apologize if it's not, but I don't even know how to search for this.

Unfortunately there's no way of reproducing it locally, since it happens sporadically under unknown conditions, but if anyone comes with an idea for reproducing it, I'm all ears.

We have the following in our code. It renders a skeleton if data is not ready:

```tsx
  if (!product || loading) {
    return (
      <ColorSelectorLoader
        optionSize={optionSize}
        optionsNumber={perPage}
        optionPadding={optionPadding}
      />
    )
  }

  return (
    <ColorSelectorContext.Provider
      ...
```

In some random, albeit frequent, occasions the snippet above renders **both** the skeleton **and** the provider. 

![image](https://github.com/facebook/react/assets/15324745/a59cb00b-4387-4c0f-9cd2-7d2e20f0d75d)

When inspecting it, the following comment caught my attention, hence why I believe it's related to React:

![image](https://github.com/facebook/react/assets/15324745/028c3434-a425-4572-a05b-a0cdb6f76deb)

## The expected behavior

The component should return only one of the above.

**Comment by ppaul** [comment]
I wouldn't worry to much if you could only see the comments. If you have also duplicate markup, that would help. Otherwise, the root cause can be in 1000 places that determine rendering

**Comment by pedrobernardina** [comment]
>  If you have also duplicate markup, that would help. 

Hi @ppaul . Could you elaborate what is needed? I'll try to provide it.

**Comment by ppaul** [comment]
I think I misunderstood. So, seeing those  twice does that mean the component rendered twice? I suggest rewriting the jsx for debugging purposes and console log on each case. I see you use provider (and probably context). Do you know, react warns that context might lead to unnecessary renderings and people also complain about:
"What is wrong with using context in React?
React Context is often used to avoid prop drilling, however it's known that there's a performance issue. When a context value is changed, all components that use useContext will re-render." (stackoverflow). Try to see what caused the render.

**Comment by pedrobernardina** [comment]
I'm not sure if it's rendering twice. To be honest, I don't know how to phrase this problem. What's happening is that both `true`  and `false` clauses are being returned at the same time.

I'm having a hard time reproducing it now, but I'll change code organization a little to try gathering more evidence .

**Comment by JSerZANP** [comment]
`<!--$-->` is the marker for Suspense in Server side rendering. 
Maybe there are some issues in the hydration process, but I'm not sure what is going on unless I see the code that repros.

**Comment by pedrobernardina** [comment]
> `<!--$-->` is the marker for Suspense in Server side rendering. Maybe there are some issues in the hydration process, but I'm not sure what is going on unless I see the code that repros.

Hi, sorry for the late reply. 

This code is built and run on a cloud framework, and we have no access of it's internal processes. Is there anything that I could provide you that would help?
