### ISSUE TITLE
Bug: Multiple React.Suspense breaks if all not wrapped in <Suspense>

### ISSUE THREAD

**Issue by markwylde-deriv** [facebook/react#27174]
When a React component throws an unresolved promise, it trigger Suspense, higher up the tree. It's all working as expected.

However, if one part of the DOM tree is wrapped in a Suspense, and another part is not, then none of them trigger Suspense.

React version: 18.2.0

## Steps To Reproduce
In a brand new React app, create the following App.

```javascript
import { Suspense, useEffect, useState } from 'react';

function getPerson (name) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve({ name, fullName: name + ' Smith' });
    }, 1000);
  });
}

const Item = ({ name }) => {
  const [person, setPerson] = useState();

  useEffect(() => {
    setPerson(-1);
    getPerson(name).then(setPerson);
  }, []);

  if (person === -1) {
    throw new Promise(r => r());
  }

  if (!person) {
    return null;
  }

  return (
    <li>{person.fullName}</li>
  )
}

function App() {
  return (
    <div className="App">
      <section>
        <h2>With Suspense</h2>
        <Suspense fallback={<div>Loading...</div>}>
          <ul>
            <Item name={'Joey'} />
            <Item name={'Monica'} />
            <Item name={'Ross'} />
            <Item name={'Rachel'} />
            <Item name={'Chandler'} />
          </ul>
        </Suspense>
      </section>

      <section>
        <h2>Without Suspense</h2>
        <ul>
          <Item name={'Joey'} />
          <Item name={'Monica'} />
          <Item name={'Ross'} />
          <Item name={'Rachel'} />
          <Item name={'Chandler'} />
        </ul>
      </section>
    </div>
  );
}

export default App;
```

Link to code example:
https://playcode.io/1549062

## The current behavior
Currently Suspense is not triggered at all.

However, try adding `<Suspense fallback={<div>Loading...</div>}>` around the `Without Suspense` section, or just comment out the whole `Without Suspense` section, and it will work fine.

## The expected behavior
I would expect the `Without Suspense` section to be empty, while the `Suspense` section contains the `Loading...` text.

**Comment by markwylde** [comment]
But surely it should only effect it's own tree?

**Comment by markwylde-deriv** [comment]
@acdlite is it documented anywhere? How components that throw suspense will cause side effects in other trees?

I'm probably just missing it, but I couldn't see anything here:
https://react.dev/reference/react/Suspense
