### ISSUE TITLE
Bug: For React/Server the renderToString with Suspense in the tree is not behaving as per what documentation says.

### ISSUE THREAD

**Issue by sgore-godaddy** [facebook/react#27183]
As per the documentation of the limited support for Suspense in `renderToString` it says the following:

"""
In React 18, we’re adding very limited <Suspense> support to renderToString. Previously, trying to use <Suspense> with it threw an error. Starting in React 18, if you suspend during renderToString, we will mark the nearest Suspense boundary as "client-rendered" and immediately emit the fallback HTML. Then, we will retry rendering its content on the client after the JS has loaded. Concretely, this means that if you wrap your app in a top-level <Suspense> boundary and you suspend during rendering, your app effectively opts out of server rendering.
"""

The above is taken from - https://github.com/reactwg/react-18/discussions/22#discussion-3385743

HOWEVER, during actual use, I see that the rendered html string contains an empty `template` tag with `data-msg` attribute as following:

```
<template data-msg="The server did not finish this Suspense boundary: The server used &quot;renderToString&quot; which does not support Suspense. If you intended for this Suspense boundary to render the fallback content on the server consider throwing an Error somewhere within the Suspense boundary. If you intended to have the server wait for the suspended component please switch to &quot;renderToPipeableStream&quot; which supports Suspense on the server"
```

React version: 18.2.0

## Steps To Reproduce

1. Make a minimal server that uses renderToString method from react/server as explained here - https://react.dev/reference/react-dom/server/renderToString#rendertostring
2. Within the component / app that is rendering on the server have a suspended component by using Lazy and Suspense similar to - https://react.dev/reference/react/Suspense

Link to code example: -

## The current behavior

In the rendered string there is an empty `template` tag with a message about use of Suspense in renderToString.

## The expected behavior

There should be no message or warning and it should just render the fallback of Suspense on server. (note it does render the fallback, but also the error message)

**Comment by sgore-godaddy** [comment]
UPDATE2 - in `18.2.0` in `Production` mode there is no `data-msg` attribute on it but the `template` tag is still there. 
I think it is part of this commit - https://github.com/facebook/react/commit/aec575914a0fd76c9db8998ea62c3ee975de70d7

@gnoff and @salazarm care to take a look ? 

I just want to confirm if this is expected behaviour or a bug ?

**Comment by leoasis** [comment]
+1 to what @sgore-godaddy mentioned above, I'm running into this as well and was definitely something that wasn't expecting from reading the docs. If we could get clarity on whether this is expected behavior or not I could help update the docs accordingly!
