### ISSUE TITLE
[DevTools Bug]:  Devtool extension build failing in windows and ubuntu

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#27193]
### Website or app

N/A

### Repro steps

Devtools extension is  not building in ubuntu and windows

Below is the extension build failing in ubuntu even though it says chrome extension has built
![bikid476@BIKISDESKTOP_ ~_react-1_packages_react-devtools-extensions 8_5_2023 1_40_08 PM](https://github.com/facebook/react/assets/72331432/24a2d4bc-5d5b-40e2-8844-b76639b5ae8e)

Below is the extension failing in windows 
![bikid476@BIKISDESKTOP_ ~_react-1_packages_react-devtools-extensions 8_5_2023 1_51_08 PM](https://github.com/facebook/react/assets/72331432/d1095bfd-772e-4e4b-a794-9cb23ceec235)

It just fails with some artifact error!

@hoxyq 😅 My mac has gone dead and i am looking to tinker with devtools and have some ideas in plan to implement so we can fix this out and hopefully i can continue to work on devtools

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Hey @Biki-das, thanks for reporting this!

I believe the problem with Windows related to not having build files ready, try running `yarn build-for-devtools` before building extensions.

Are you interested in investigating what's going wrong for Linux?

**Comment by Biki-das** [comment]
> Reference

@hoxyq even running build-for-devtools it fails actually in windows

**Comment by hoxyq** [comment]
> > Reference
> 
> @hoxyq even running build-for-devtools it fails actually in windows

Not good. Are you interested in fixing this, maybe?

**Comment by Biki-das** [comment]
> > > Reference
> > 
> > @hoxyq even running build-for-devtools it fails actually in windows
> 
> Not good. Are you interested in fixing this, maybe?

Yup let me investigate what's breaking and what can i interpret from it and get back to you!

**Comment by hoxyq** [comment]
> > > > Reference
> > > 
> > > 
> > > @hoxyq even running build-for-devtools it fails actually in windows
> > 
> > 
> > Not good. Are you interested in fixing this, maybe?
> 
> Yup let me investigate what's breaking and what can i interpret from it and get back to you!

Any updates on this?

**Comment by PrathamLalwani** [comment]
I can look into this if you want @hoxyq , I am not a beginner programmer but this will be my first contribution. Would you recommend this as a first bug?

**Comment by Biki-das** [comment]
yeah sure

**Comment by hoxyq** [comment]
Fixed by https://github.com/facebook/react/pull/27692.
