### ISSUE TITLE
Generate docs using JSDoc (or something).

### ISSUE THREAD

**Issue by jordwalke** [facebook/react#272]
We've tried to be consistent about documenting the React core using markdown style comments, and JSDoc style annotations, so it would be easy to create a utility that auto-generates documentation pages for the core itself. Ideally this would only rely on node.js/npm and not Java.

Using the "good first bug" label, but we should rename that label to "good first contribution".

**Comment by InSuperposition** [comment]
How about a lib that uses [Facebook's fork of Esprima](https://github.com/facebook/esprima/tree/fb-harmony) or parts of [Flow](http://flowtype.org/)(?) to analyze the JS and JSX Abstract Syntax Trees, then generate a documentation data structure and optionally transform source files. I looked around but had no luck with finding a similar existing library.

The next step would be create a collection of React components (react-doc?) to provide the documentation views.

+ React docs would updated by static code analysis, not annotations, less prone to human error
+ Auto generate JSX supported HTML/SVG elements and attributes (0.12.2 documentation is currently out of date)
+ Auto generate docs for user created React components (Mixins, Property types and defaults, etc..)
+ The "react-doc" components could be a tutorial on building React components while interacting with the documentation
+ Optionally prepend annotations for other documentation libs (JSDoc, YUIDoc or plugin...)

**Comment by zpao** [comment]
I was actually just thinking of a Flow-based documentation tool. Unfortunately none exist AFAIK and there's still some need for the JSDoc comment (at least for the description, and other `@class`, etc things JSDoc does).

Side note... 0.12.2 documentation shouldn't be out of date, I updated it myself :) But let me know what's missing and I'll followup.

I think the idea of a react-doc tool is certainly interesting. We actually have something we do internally at FB that does some of what you're talking about, pulling out at least some of the PropTypes and handling inheritance. It's tied to some specific ways we write out components but it would be cool to generalize it so it could be open sourced. That's pretty tangential to this specific issue, but cc @fkling anyway :)

**Comment by revolunet** [comment]
What do you guys would use to create react components documentation with the API from comment and a live example ?

**Comment by fkling** [comment]
@revolunet: FWIW, I'm currently working on open sourcing the tool that we use internally. Regarding examples, I don't think there will be a good automatic solution. Those components for which examples will be useful likely need more complex examples as well (children, event handlers, etc).

Overall I think it would be great if we could establish some guidelines around how to write a React component and how to provide examples for it.

**Comment by hzoo** [comment]
@fkling yeah I think some guidelines could be helpful - angular has some styleguides that talk about ideas for syntax, conventions, and structure - ex: https://github.com/johnpapa/angularjs-styleguide

**Comment by zpao** [comment]
Eh, after this long using human maintained docs, I think we'll just continue down that path. It's not without problems, but with a small surface area, I don't think we actually need autogenned docs.

**Comment by yordis** [comment]
@jordwalke @zpao About JSDoc I don't think JSDoc is a solution (for now) It doesn't like JSX and most of the time we will code in JSX. Check this https://github.com/jsdoc3/jsdoc/issues/1001

@revolunet Check it out https://github.com/React-UI/generator-react-ui-component. You have a good environment setup. It's using YUIdoc because JSDoc doesn't support JSX right now but YUIdoc doesn't like it too much alternative tags and in react for example we have states and YUIdoc doesn't have a state tag, yet.

**Comment by revolunet** [comment]
thanks @yordis will check it out

**Comment by mik01aj** [comment]
https://github.com/sapegin/react-styleguidist looks pretty impressive, too!
