### ISSUE TITLE
Bug: d.split("+").at is not a function. (In 'd.split("+").at(-1)', 'd.split("+").at' is undefined) error in safari 14.1 running react js

### ISSUE THREAD

**Issue by samwac** [facebook/react#27207]
TypeError: d.split("+").at is not a function. (In 'd.split("+").at(-1)', 'd.split("+").at' is undefined)

<img width="1440" alt="Screenshot 2023-08-09 at 11 20 10 AM" src="https://github.com/facebook/react/assets/141808324/d75f71b7-fe8e-4d82-8647-c29e615f78fb">

while running react app on safari 14.1 i come across this error , but on safari latest versions and google chrome, react app is working fine.

i tried debugging the the error and i think it's from the bundle.js file, is not please correct me.

**Comment by robinheinze** [comment]
Looks like `.at()` is only supported in Safari 15.4 and above https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility

**Comment by pranavlotlikar** [comment]
Is this a React-specific issue or can it be fixed by a Polyfill?

**Comment by pranavlotlikar** [comment]
How should I go about handling this issue as my React application is coming blank on some older version of Safari browser?
In the console, the above error is shown.

**Comment by guillaumebrunerie** [comment]
Pdf.js does not support Safari 14.1: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#legacy-build
This has nothing to do worth React.
