### ISSUE TITLE
Bug: react inspector "inspection" button doesn't work

### ISSUE THREAD

**Issue by Aarbel** [facebook/react#27203]
The arrow button for inspection doesn't work with last version of React Inspector (since nearly one year), how to make it work ?

- React inspector 4.28.0
- React v17.0.2

https://github.com/facebook/react/assets/25119847/50303191-045e-4674-ad81-12ce560cd112

Thanks a lot for your help

**Comment by tahamukhtar20** [comment]
I have been facing a similar issue, it works sometimes, but not always.

**Comment by faheem-cmd** [comment]
which browser are you using ?
