### ISSUE TITLE
My javascript code cannot fetch or display data from an API and I can't identify the error

### ISSUE THREAD

**Issue by Asare6** [facebook/react#27219]

**Comment by Asare6** [comment]
const quoteContainer =document.getElementById("quote-container")
const quoteText =document.getElementById("quote")
const authorText =document.getElementById("author")
const twitterBtn =document.getElementById("twitter")
const newQuoteBtn =document.getElementById("new-quote")

let apiQuotes = [];

// show new Quote
function newQuote(){
    // pick a random quote from apiQuotes array
    const quote = apiQuotes[Math.floor(math.random() * apiQuotes.length)];
    authorText.textContent = quote.author;
    quoteText.textContent = quote.text;
    
}

// Get Quotes from API
async function getQuotes(){
    const apiUrl='https://type.fit/api/quotes';
    try {
        const response = await fetch(apiUrl);
        apiQuotes = await response.json();
        newQuote();
    } catch (error) {
        // catch error here
    }
}

// on load
getQuotes();

**Comment by jmerz826** [comment]
Hi, Asare6. I highly recommend using the `catch` block you've already set up! Adding a `console.error(error)` would tell you that `math` should be capitalized (to `Math`) in your `const quote` declaration 😉

**Comment by rishabhpassi** [comment]
Hi , @Asare6 
I see a couple of issues in your JavaScript code that might be causing the problem. Here are the corrections:

1. The method `Math.random()` should be written with an uppercase "M". JavaScript is case-sensitive, so `Math.random()` is correct, not `math.random()`.

2. The `getQuotes` function is being called before the DOM is fully loaded. To ensure that the DOM is ready before executing the `getQuotes` function, you should wrap the `getQuotes` function call inside a `DOMContentLoaded` event listener.

// show new Quote
function newQuote() {
  // pick a random quote from apiQuotes array
  const quote = apiQuotes[Math.floor(Math.random() * apiQuotes.length)];
  authorText.textContent = quote.author;
  quoteText.textContent = quote.text;
}

// Get Quotes from API
async function getQuotes() {
  const apiUrl = 'https://type.fit/api/quotes';
  try {
    const response = await fetch(apiUrl);
    apiQuotes = await response.json();
    newQuote();
  } catch (error) {
    // catch error here
  }
}

// Wait for the DOM to be fully loaded
document.addEventListener('DOMContentLoaded', getQuotes);


By wrapping the `getQuotes` function call inside the `DOMContentLoaded` event listener, you ensure that the API call will be made only after the DOM has finished loading. This should help resolve your issue with fetching and displaying data from the API.

**Comment by Asare6** [comment]
> Hi , @Asare6 I see a couple of issues in your JavaScript code that might be causing the problem. Here are the corrections:
> 
> 1. The method `Math.random()` should be written with an uppercase "M". JavaScript is case-sensitive, so `Math.random()` is correct, not `math.random()`.
> 2. The `getQuotes` function is being called before the DOM is fully loaded. To ensure that the DOM is ready before executing the `getQuotes` function, you should wrap the `getQuotes` function call inside a `DOMContentLoaded` event listener.
> 
> // show new Quote function newQuote() { // pick a random quote from apiQuotes array const quote = apiQuotes[Math.floor(Math.random() * apiQuotes.length)]; authorText.textContent = quote.author; quoteText.textContent = quote.text; }
> 
> // Get Quotes from API async function getQuotes() { const apiUrl = 'https://type.fit/api/quotes'; try { const response = await fetch(apiUrl); apiQuotes = await response.json(); newQuote(); } catch (error) { // catch error here } }
> 
> // Wait for the DOM to be fully loaded document.addEventListener('DOMContentLoaded', getQuotes);
> 
> By wrapping the `getQuotes` function call inside the `DOMContentLoaded` event listener, you ensure that the API call will be made only after the DOM has finished loading. This should help resolve your issue with fetching and displaying data from the API.

it's still not working

**Comment by AtulPatidar1709** [comment]
👋 @Asare6, I want to work on this Issue can you please assign it to me.

**Comment by AMalfez** [comment]
hi
this code is working for me. I used it in react like this:
// catch error here
async function getQuotes() {
  const apiUrl = 'https://type.fit/api/quotes';
  try {
    const response = await fetch(apiUrl);
    const apiQuotes = await response.json();
    console.log(apiQuotes);
  } catch (error) {
    console.log(error);
  }
}

function Testing() {
  getQuotes();
  return (
    <div>Testing</div>
  )
}

export default Testing

in console it gives me array of all the quotes...
