### ISSUE TITLE
Can createElement be optimized for performance?

### ISSUE THREAD

**Issue by zackasaurus** [facebook/react#27216]
For large complex apps that have many props and a deep react DOM tree, createElement is one of the most expensive operations.

I've noticed for large complex apps such as Facebook and Discord, createElement can take up 10% of the memory allocation during a basic scenario, and it can take up 2-5% of the script time, not accounting for MajorGC and MinorGC.

The issue is that the props object in createElement gets created from scratch, and the entire config that's passed in gets iterated over. Since the config object isn't used anymore after createElement, it gets marked for GC, which additionally hurts performance.

I have an idea where we can just simply assign props to config for most cases, such as when the props object is not frozen, and no key or ref was passed in to createElement. I can create a PR, but I wanted to run it by the react devs first to see if there is anything I'm missing. 

Facebook

<img width="1279" alt="Screenshot 2023-08-11 at 11 25 34 AM" src="https://github.com/facebook/react/assets/20049128/6df55010-ee2e-497b-af1c-57a694084165">
<img width="601" alt="Screenshot 2023-08-11 at 11 25 43 AM" src="https://github.com/facebook/react/assets/20049128/44ec9a09-db5a-4508-bbba-06fcd7672d0a">
<img width="1283" alt="Screenshot 2023-08-11 at 11 24 49 AM" src="https://github.com/facebook/react/assets/20049128/12fde72f-1ca7-4b32-aac9-1ace6fba0274">

Discord

<img width="1284" alt="Screenshot 2023-08-11 at 11 17 39 AM" src="https://github.com/facebook/react/assets/20049128/bb02bd70-e799-439b-b9c2-a4ff1dc351b9">
<img width="560" alt="Screenshot 2023-08-11 at 11 17 57 AM" src="https://github.com/facebook/react/assets/20049128/16d2c769-d17f-49c9-93fc-9128b56c9df1">

**Comment by sophiebits** [comment]
Thanks for filing this! This helped kick-start the work to get https://github.com/facebook/react/pull/28768 and friends landed for real. Hopefully you will see even larger gains from that set of changes once they’re released (note they’re still behind a feature flag on main for now).
