### ISSUE TITLE
Bug: React trigger multiple re-render by once setState (not use StrictMode)

### ISSUE THREAD

**Issue by zombieJ** [facebook/react#27213]
React version: 18.2.0

## Steps To Reproduce

https://codesandbox.io/s/goofy-bogdan-3pt5h6?file=/src/App.js

Click button.

## The current behavior

render will trigger twice.

## The expected behavior

render should be once

## Ref

Debug find that call setState in useEffect with same state will create a queue task which will flush in next state update:

https://github.com/facebook/react/blob/533fc28c1b8ea2c6ed459e914849665f497755ff/packages/react-reconciler/src/ReactFiberHooks.js#L2808

I'm not sure if this could be remove safely

**Comment by zombieJ** [comment]
@acdlite, seems follow code is already call `enqueueConcurrentHookUpdate` when need update:

https://github.com/facebook/react/pull/24663/files#diff-d0d3346ffbaafc7b47ed46f19ccdd179480fa697033bed903c60d8455a9ce8bbR2309

The `enqueueConcurrentHookUpdateAndEagerlyBailout` seems unecessary:

https://github.com/facebook/react/pull/24663/files#diff-d0d3346ffbaafc7b47ed46f19ccdd179480fa697033bed903c60d8455a9ce8bbR2290

**Comment by shahul01** [comment]
I dont know if its related but in dev mode, the useEffect renders twice and in production mode, once..

**Comment by eps1lon** [comment]
Starting with React 18, effects will be called twice in StrictMode to ensure they're cleaned up: https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development
