### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by richardoptibrium** [facebook/react#27214]
Hi, Would be really great if you offered the feature of displaying key for components to help us debug when something does not have a unique key.

**Comment by rumon5h** [comment]
**### To Fix this problem use**

`key={Math.random()}`

**Comment by richardoptibrium** [comment]
Thanks rumon5h, but a uuid might be safer? But if something (relatively) random is good enough, why doesn't React just do that automatically? In the meantime, it would be good to have the keys visible in React Programmer Tools.

**Comment by jkazimierczak** [comment]
> Hi, Would be really great if you offered the feature of displaying key for components to help us debug when something does not have a unique key.


Keys are visible via React's DevTools. Also if the element misses the key, the React DevTools will allow you to inspect the node that doesn't have it.

![image](https://github.com/facebook/react/assets/77862767/8f451c83-a195-4d70-a06b-689365abeca3)


> `key={Math.random()}`

This function will be invoked for every re-render meaning that the keys will change with every re-render. Same with uuid that @richardoptibrium mentioned, or generally any function that generates something "random" on the fly.

My solutions to making keys predictable and persistent across re-renders is to:
- use some sort of ID that doesn't change (ex.: ID of an item from a database),
- make a string-and-index-based key when mapping over elements, like so:
```ts
items.map((item, idx) => (
  <div key={`item-${idx}`} />
))

**Comment by narayan954** [comment]
> > Hi, Would be really great if you offered the feature of displaying key for components to help us debug when something does not have a unique key.
> 
> Keys are visible via React's DevTools. Also if the element misses the key, the React DevTools will allow you to inspect the node that doesn't have it.
> 
> ![image](https://user-images.githubusercontent.com/77862767/261790040-8f451c83-a195-4d70-a06b-689365abeca3.png)
> 
> > `key={Math.random()}`
> 
> This function will be invoked for every re-render meaning that the keys will change with every re-render. Same with uuid that @richardoptibrium mentioned, or generally any function that generates something "random" on the fly.
> 
> My solutions to making keys predictable and persistent across re-renders is to:
> 
> * use some sort of ID that doesn't change (ex.: ID of an item from a database),
> * make a string-and-index-based key when mapping over elements, like so:
> 
> ```ts
> items.map((item, idx) => (
>   <div key={`item-${idx}`} />
> ))
> ```

React library, by default employs index as key to identify, but that's still not safe to use and that's why there's this warning.

**Comment by narayan954** [comment]
> **### To Fix this problem use**
> 
> `key={Math.random()}`

that's like saying react to re-render everything if anything changes (on that same level)
