### ISSUE TITLE
Inconsistent order of `onChange` and `onSelect` events in IE

### ISSUE THREAD

**Issue by jfschwarz** [facebook/react#2722]
Usually, when the user enters or deletes a character in an input field, the `onChange` event is triggered before the `onSelect` event.

However, in Internet Explorer, when deleting a character in an input, `onSelect` is triggered BEFORE `onChange`. (When entering a character, we see the correct order of events also in IE.) I could observe this behavior on IE9-11. (I did not test on IE<9.)

As I understand that React aims at abstracting event handling inconsistencies across different browsers, this seems like an issue that needs fixing.

A jsFiddle demonstrating the issue can be found here: http://jsfiddle.net/kb3gN/8594/

A real-world implementation suffering under this bug, can be found here: http://rawgit.com/effektif/react-mentions/master/examples/index.html (Try using Backspace in IE... I do not see an easy workaround to make this implementation work atm.)

**Comment by fbatista** [comment]
Any idea when we can expect this to be patched ? I feel really dirty having to manually patch my app's React.js version due to the fact that we're using a component that struggles with this issue.

**Comment by salier** [comment]
Sorry for the long wait. I'm working on this now.

**Comment by spicyj** [comment]
Fixed by #4559.
