### ISSUE TITLE
Bug: Minified React error #299 | createRoot(...): Target container is not a DOM element.

### ISSUE THREAD

**Issue by MiguelG97** [facebook/react#27221]
createRoot(...): Target container is not a DOM element.

This issue keeps showing up but I've made sure I'm using the correct DOM element which comes from the vite+react boilerplate! (root)
![image](https://github.com/facebook/react/assets/78984964/01afca24-73c4-416f-b605-51252991d8b5)
![image](https://github.com/facebook/react/assets/78984964/20ea5e3f-0d72-48b5-92f7-a53b6f5b616e)

![image](https://github.com/facebook/react/assets/78984964/e49bcb0d-c62c-46ad-ab8e-fc835406c3b7)

React version:

## Steps To Reproduce

1. Deploy vite+react+tailwind framework as indicated in tailwindcss website:
https://tailwindcss.com/docs/guides/vite

Link to code example:
https://tailwindcss.com/docs/guides/vite

## The current behavior
message shows up everytime!

## The expected behavior
no reason to show that message

**Comment by NextThread** [comment]
can.i work on this

**Comment by ketanbaitule** [comment]
Hi, You have to build your vite app once again, then the issue will be resolved.

**Comment by MiguelG97** [comment]
@ketanbaitule I built it once again then the same error shows up:
![image](https://github.com/facebook/react/assets/78984964/135dc6ca-ab33-4f9f-8eff-e2d6ee7d0b2f)
![image](https://github.com/facebook/react/assets/78984964/5f8d928a-cb57-4d06-a867-98a12911776f)
![image](https://github.com/facebook/react/assets/78984964/b62222a6-9a9e-4dcf-8f38-349053f48da4)
![image](https://github.com/facebook/react/assets/78984964/90938b5f-e43f-43b6-9fea-752d8a107681)

**Comment by ketanbaitule** [comment]
I am not able to reproduce this error.
`index.html`

![index.html](https://github.com/facebook/react/assets/111437670/d6625741-583d-4952-9136-383a4b1d6cc6)


This code creates an error: `src/main.jsx`

![src/main.jsx](https://github.com/facebook/react/assets/111437670/99584b7e-7eae-40ca-89c2-35468f5d374e)

![Console_Error](https://github.com/facebook/react/assets/111437670/9fabea4c-7743-4b66-985d-148918219000)

But this doesn't: `src/main.jsx`

![src/main.jsx](https://github.com/facebook/react/assets/111437670/0802bce0-5eb7-48df-9b34-74f836dff5a3)

![No_Error](https://github.com/facebook/react/assets/111437670/b1978277-c00e-4491-9dae-3c2089db59f4)

**Comment by Meesujit** [comment]
in index.js file put this code.
import React from 'react';
import ReactDOM from 'react-dom/client';

import App from './App';
import './App.css'

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

**Comment by anjaliagarwalla** [comment]
<img width="488" alt="image" src="https://github.com/facebook/react/assets/31450920/52f93086-61e3-4dd9-8152-30414065a397">
I m also facing same issue in  index.tsx file..how to resolve it

**Comment by Meesujit** [comment]
@anjaliagarwalla  can you show the code of the index.tsx

**Comment by bigheha** [comment]
I get the same mistake when building my project with vite, here's the main.tsx:
![image](https://github.com/facebook/react/assets/72448175/12509644-18d6-4af5-bb6a-8681317e9e34)

**Comment by bigheha** [comment]
> I get the same mistake when building my project with vite, here's the main.tsx: ![image](https://user-images.githubusercontent.com/72448175/272070048-12509644-18d6-4af5-bb6a-8681317e9e34.png)

Forgot to mention, the code that I've shared is not a result of "tsc && vite build", this is the code that i am supposed to build from

**Comment by Meesujit** [comment]
@bigheha check the new documentation of react library. You will get the solution.

**Comment by sophiebits** [comment]
There is no way for us to investigate this without a repro case, and in any event, the bug here is likely not in React itself.

**Comment by johnmba** [comment]
I had the same issue but I discovered that the ID in the html file doesn't match does not match with the document ID being called in the index.tsx file. So, check if the index.hml file in public or root folder contains the ID being called in the index.

**Comment by asumaran** [comment]
@johnmba, you're a lifesaver! I hadn’t noticed that my element was using a class name instead of an ID.
