### ISSUE TITLE
Bug: ios elastically scrolls to a certain distance, causing some elements in the fixed content area to disappear?

### ISSUE THREAD

**Issue by xiaomuzizier** [facebook/react#27229]
React version:
17.0.2

## Steps To Reproduce

1. when ios elastically scrolls to a certain distance
2.causing some elements in the fixed content area to disappear

There is no problem with the ability to use the original html to write this ability, because it should not be a problem with ios

normal like this
![wecom-temp-103550-0e05ccd547d6df4ce85146fe9e18d0ab](https://github.com/facebook/react/assets/30134089/5cdbd3d3-4278-4ce2-9881-a1f753ccf15e)

but get this:
![wecom-temp-70974-78133f58d6d4f4d077670c3e88151dec](https://github.com/facebook/react/assets/30134089/72cdbad1-3f85-48dc-9b0a-ebedda7e57fc)
and
![wecom-temp-85381-8b9a6adb01491e32f132156418e16b9f](https://github.com/facebook/react/assets/30134089/af1fd4d9-36b5-4706-a180-8fb1089e10d1)

the video like this:
https://github.com/facebook/react/assets/30134089/b5a7655b-94c2-4401-99a3-bc1a150a238f

Link to code example:
use create react app and replace app.js content .you can recurrent this
```
// import logo from './logo.svg'; 
import './App.css';

function App() {
  const html = `
  <div style="background-color: black;">
    <div style="position: fixed; top: 50px; width: 100%; z-index: 1999">
      <div id="tabsContainer" style="overflow: auto; background: yellow; white-space: nowrap; height: 50px;">
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>
        <span style="background-color: red; color: #ffffff; font-size: 18px; margin-left: 10px;">最新｜聚焦楼市动态</span>

      </div>
    </div>
    <div style="height: 800px">你好吗</div>
    <div style="height: 800px">你好11</div>
    <div style="height: 800px">你好22</div>
    <div style="height: 800px">你好33</div>
  </div>
`;
  return (
  
    <div
      dangerouslySetInnerHTML={{
        __html: html,
      }}
    />

  );
}

export default App;

```

## The current behavior
get this:
![wecom-temp-70974-78133f58d6d4f4d077670c3e88151dec](https://github.com/facebook/react/assets/30134089/72cdbad1-3f85-48dc-9b0a-ebedda7e57fc)
and
![wecom-temp-85381-8b9a6adb01491e32f132156418e16b9f](https://github.com/facebook/react/assets/30134089/af1fd4d9-36b5-4706-a180-8fb1089e10d1)

## The expected behavior
normal like this
![wecom-temp-103550-0e05ccd547d6df4ce85146fe9e18d0ab](https://github.com/facebook/react/assets/30134089/5cdbd3d3-4278-4ce2-9881-a1f753ccf15e)

**Comment by alexshibu1** [comment]
how did you fix this?
