### ISSUE TITLE
Bug: moving item in list resets scroll when item has `key` prop

### ISSUE THREAD

**Issue by YuanboXue-Amber** [facebook/react#27236]
React version: 18.2.0

## Steps To Reproduce

1. In the example, scroll a little bit (make sure "item 6" is still in the view). 
2. Click the button to move "item 6" to top, notice scroll position reset to top
    
| before: | after moving item 6: |
| ---- |-----|
|<img width="305" alt="image" src="https://github.com/facebook/react/assets/28751745/95d37c57-ff1d-4c93-9dfd-31afb3d90420">|<img width="310" alt="image" src="https://github.com/facebook/react/assets/28751745/75dfa0ed-d61e-4809-ab92-f2d7284ba27a">|

Link to code example:
https://codesandbox.io/s/great-haibt-2ztxmq?file=/src/App.js

## The current behavior 
Moving "item 6" to top resets the scroll position. However, if I scroll to the very bottom and "item 6" is not in the visible area, moving "item 6" doesn't reset scroll. It seems like an inconsistency in behavior.
Debugging the code shows that react inserts item 0-5 before item 7. This is probably why scroll reset will not happen if there's no `key` prop, or if "item 6" get a new key when it is moved to top.

## The expected behavior
Scroll position does not reset. 
This is a plain DOM example, and it does not reset scroll: https://codesandbox.io/s/upbeat-newton-njx7d4?file=/src/index.mjs

**Comment by aavishkarmishra** [comment]
Hii @YuanboXue-Amber I would like to work on this issue.
Can you walk me to the process for getting the expected behavior
Because It can also be the idea to get the feedback when the element to move up is visible or that some one want to see that the element moved to top.

**Comment by manmohanhunjan** [comment]
Hi @YuanboXue-Amber ! I'm interested in working on this issue. Could you please assign it to me? I'm excited to contribute and help resolve this. Thank you.

**Comment by tychenjiajun** [comment]
It seems to be a duplicate of https://github.com/facebook/react/issues/27044

**Comment by YuanboXue-Amber** [comment]
Yes it's a duplicated, this comment https://github.com/facebook/react/issues/27044#issuecomment-1627665803 also fixes my issue. Closing this, thanks :)
