### ISSUE TITLE
bypass progressive loading for the CSS

### ISSUE THREAD

**Issue by ahuet67** [facebook/react#27246]
# Context

I moved recently to renderToPipeableStream to increase performance of our application.
Nevertheless my work is refused because there the product team doesn’t like the transition effect between the raw html loaded and the moment where the css is finally loaded.

Here is the effect, that the product team wants to avoid : 

https://github.com/facebook/react/assets/21305034/4fb7f950-69b1-4d2e-92c9-3141d91e9815

*For the example, I simulate a slow network but even with fast connection, the transition briefly appears.*

# My code

```typescript
import type { Response } from 'express';
import { renderToPipeableStream } from 'react-dom/server';
import { Helmet } from 'react-helmet';

import App from './MainApp';

export async function render(url: string, res: Response, assets, webMain: string[]) {
  const helmet = Helmet.renderStatic();
  const context = { statusCode: 200 };
  let didError = false;
  const stream = renderToPipeableStream(<App url={url} context={context} assets={assets} helmet={helmet} />, {
    bootstrapScripts: webMain,
    onAllReady: () => {
      res.setHeader('Content-type', 'text/html');
      if (didError) {
        res.status(500);
      } else {
        res.status(context.statusCode || 200);
      }
      stream.pipe(res);
    },
    onError: () => {
      didError = true;
    },
    onShellError: () => {
      didError = true;
    },
  });
}
```

# My question

Is it possible to begin to display something only when we get all the css ? (But to keep the stream strategy for all the js files and keep the hydratation) ?

**Comment by vrun1208** [comment]
Hey! @ahuet67 ,
It seems you are facing problem while loading the page as it takes longer time in loading css. okay one of the approach is that you can wrapped your component in a <Suspense> component. The fallback prop of <Suspense> specifies what should be rendered while the asynchronous content is loading. Hope this helps.

**Comment by ahuet67** [comment]
Thank you @vrun1208  for you answer.
Actually, I already use Suspense/React.lazy at the router level.
Like that : 
```javascript
import { Suspense, lazy } from 'react';
import { Route, Routes } from 'react-router-dom';

const HomepageV2 = lazy(() =>
  import(/* webpackChunkName: "homepage_v2" */ '../components/pages/homepage-v2/Homepage'),
);

<Suspense fallback={<Loader />}>
      <Routes>
        <Route path={PublicRoutes.HOMEPAGE} element={<HomepageV2 />} />
      </Routes>
    </Suspense>
```

To be sure, I've tested what you suggested but it doesn't solve my issue.

**Comment by ahuet67** [comment]
We've found a workaround. We've disable the chunks for the css. This way we have only 1 CSS which is loaded before main.js and we don't have transitions anymore.
I was surprised to see that it decreased the loading time of the app. This should be because we do less requests (even if the css file is heavier).

I keep this issue open because the solution is not ideal. We load more CSS than it is required.

**Comment by vrun1208** [comment]
Hi @ahuet67, your solution is impressive but as you mentioned there are lots of css files to load. My idea is,
-> You can bundle up you css files into one which reduces the multiple requests, or
-> You can use critical-css which include in the html directly, which ensures the content is styled while the css loads.
You can get more info about critical css  [here](https://web.dev/extract-critical-css)

**Comment by sophiebits** [comment]
Salut !

In the latest canary version of React there is improved handling for resources that should integrate automatically with the streaming server renderer. Don't use react-helmet; instead render a `<link />` stylesheet tag in the component that needs it. This should prevent the content from displaying before the stylesheet is loaded. Unfortunately this is not yet documented in more detail (we are working on it) but I hope this is enough to get you started.

**Comment by X7Becka** [comment]
Bump.
@sophiebits 
This feature is necessary because many projects like our using css-modules and i have no idea how to switch 'em with <link/>.
In our case we have only top-level critical css-file that uses in all pages. In other words, we just getting common css at start in generated html and progressively loaded other styles with imminent layout shift.
Could be good to see an option to set something like "component deep" value or ability to pass manifest for accurate extract assets then pass them in the head of html.
