### ISSUE TITLE
Bug: No apparent way to debug setupProxy.js

### ISSUE THREAD

**Issue by erjoalgo** [facebook/react#27255]
I followed the instructions to set up a proxy API using `setupProxy.js`:

```
npm install http-proxy-middleware --save
```
And `setupProxy.js`:
```
const { createProxyMiddleware } = require('http-proxy-middleware');

module.exports = function(app) {
  app.use(
    '/api',
    createProxyMiddleware({
      target: 'http://localhost:3000',
      changeOrigin: true,
    })
  );
};
```

However, requests starting with `/api/...` don't appear to be proxied properly and return 404s. I'd like to do further debugging to understand whether `setupProxy.js` is being loaded at all, and what is happening to the requests that are intended to be proxied. However, I can't find any documentation on how to debug proxied requests.

I've tried adding logging:

```
onProxyRes: function(proxyRes, req, res) {
                log("Req URL: " + req.originalUrl);
                log("Response status code: " + proxyRes.statusCode);
            }
```

But I cannot find logs anywhere.

Would it be possible to document how to add verbose logging to understand what is happening with `setupProxy.js` and how to debug proxied requests?

**Comment by erjoalgo** [comment]
I'd also like to add an example of another user experiencing difficulties setting up and debugging setupProxy.js:

https://community.freshworks.dev/t/setupproxy-js-does-not-work-inside-react-app/3093/20

**Comment by sophiebits** [comment]
Oh I see, you are looking for the create-react-app project.

https://github.com/facebook/create-react-app

Do note that it is not recommended for new projects: https://react.dev/learn/start-a-new-react-project
