### ISSUE TITLE
Bug: useEffect not firing when depending on hook value

### ISSUE THREAD

**Issue by ThomasMorrison** [facebook/react#27256]
React version: 18.2.0

## Steps To Reproduce

1. Setup a hook which returns a `ref.current` value.
2. Setup a `useEffect` which depends on hooks return value.
3. Have some `useState` which causes re-renders.
4. The `useEffect` may not be called.

Link to code example: https://codesandbox.io/s/zealous-jasper-fvynsw?file=/src/App.js

Be sure to open the dev console

**Relevant code:**
```javascript
import React, { useRef, useEffect, useState } from "react";

export default function App() {
  const hooksValue = useHookThatReturnsRefValue();

  console.info("Render:", hooksValue);
  useEffect(() => {
    console.info("useEffect ran! ---------------------", hooksValue);
  }, [hooksValue]);

  return <div>View dev console</div>;
}

function useHookThatReturnsRefValue() {
  const [state, setState] = useState(0);
  const ref = useRef(0);

  useEffect(() => {
    setState((old) => (old === 0 ? 1 : old));
  }, [state]);

  useEffect(
    function loadInitialRange() {
      if (state === 1) {
        ref.current += 1;
        const timeout = setTimeout(() => {
          setState((old) => (old === 1 ? 0 : old));
        }, 2000);
        return () => clearTimeout(timeout);
      }
    },
    [state]
  );

  return ref.current;
}
```

## The current behavior

The console output looks as follows:
```
index.js:27 Render: 0
index.js:27 useEffect ran! --------------------- 0
index.js:27 Render: 0
index.js:27 Render: 1
index.js:27 Render: 1
index.js:27 Render: 1
index.js:27 Render: 2
index.js:27 Render: 2
index.js:27 Render: 2
index.js:27 Render: 3
index.js:27 Render: 3
index.js:27 Render: 3
index.js:27 Render: 4
index.js:27 Render: 4
index.js:27 Render: 4
index.js:27 Render: 5
```

The `useEffect` is not called, but its impossible to know why. 
This is an important issue, as there are no warnings about returning values from a hook that cannot be used in dependency arrays. 

## The expected behavior

I would expect the console output to look as follows:

```
index.js:27 Render: 0
index.js:27 useEffect ran! --------------------- 0
index.js:27 Render: 1
index.js:27 useEffect ran! --------------------- 1
index.js:27 Render: 2
index.js:27 useEffect ran! --------------------- 2
index.js:27 Render: 2
index.js:27 Render: 3
index.js:27 useEffect ran! --------------------- 3
index.js:27 Render: 4
index.js:27 useEffect ran! --------------------- 4
index.js:27 Render: 4
index.js:27 Render: 5
index.js:27 useEffect ran! --------------------- 5
```

**Comment by alimertcakar** [comment]
Changes on ref does not trigger a rerender anyway.

https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom

Maybe you can save that value in a state, or if you are interacting with dom you might use this: https://legacy.reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node

**Comment by zainbinshakoor** [comment]
Changing the value within a useRef variable doesn't result in the component re-rendering; the component's appearance remains unaffected by such modifications.
