### ISSUE TITLE
Bug: some /public resources not served when proxy is enabled in manifest.

### ISSUE THREAD

**Issue by erjoalgo** [facebook/react#27254]
I'm using react within a Docker container with an accompanying backend. In order to minimize the number of ports exposed, I am attempting to have react proxy requests internally to the backend within the internal docker container network, as opposed to having the browser talk directly to the backend.

So I set the "proxy" key in `package.json`:

```
...
"proxy": "http://service:3000",
...
```

Requests to the backend are served correctly. Also, /public/index.html is served correctly.

However, other resources under the react public directory, e.g. `/public/manifest.json`, `/public/favicon.ico` are also proxied to the backend, which in my case results in a 404.

Though it's not explicitly stated, from the documentation I get the impression that only `unknown` requests are proxied, but I would expect the static resources under /public mentioned above should be recognized and served instead of proxied.

```
To tell the development server to proxy any unknown requests to your API server in development, add a proxy field to your package.json, for example:

  "proxy": "http://localhost:4000",
This way, when you fetch('/api/todos') in development, the development server will recognize that it’s not a static asset, and will proxy your request to http://localhost:4000/api/todos as a fallback. The development server will only attempt to send requests without text/html in its Accept header to the proxy.

Conveniently, this avoids [CORS issues](https://stackoverflow.com/questions/21854516/understanding-ajax-cors-and-security-considerations) and error messages like this in development:
```

React version:  "react": "^18.0.0",

## Steps To Reproduce

1. set the "proxy" property and start react
2. attempt to fetch a non-text/html resource under /public

Link to code example:

## The current behavior
/public/manifest.json is proxied to backend, resulting in 404

## The expected behavior
/public/manifest.json and other static files are recognized as a known resource and served

**Comment by erjoalgo** [comment]
Sample demo from attaching to docker container running the react app:

```
root@4c20b566b8b8:/ui# curl -I localhost:3001/index.html
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Wed, 02 Aug 2023 21:30:56 GMT
ETag: W/"5a7-189b8293880"
Content-Type: text/html; charset=UTF-8
Content-Length: 1447
Vary: Accept-Encoding
Date: Sun, 20 Aug 2023 23:00:57 GMT
Connection: keep-alive
Keep-Alive: timeout=5

root@4c20b566b8b8:/ui# curl -I localhost:3001/manifest.json
HTTP/1.1 404 Not Found
X-Powered-By: Express
date: Sun, 20 Aug 2023 23:01:03 GMT
content-type: text/html; charset=UTF-8
connection: close
server: Jetty(9.2.21.v20170120)
Vary: Accept-Encoding

root@4c20b566b8b8:/ui# ls public/
1089009.png  favicon.ico  index.html  manifest.json
root@4c20b566b8b8:/ui# 
```

**Comment by erjoalgo** [comment]
I added some logging to `setupProxy.js`, but like another user experienced in https://stackoverflow.com/questions/63660384/how-to-display-console-logs-using-webpack-build, I couldn't find those logs in either the terminal or the browser console. And I couldn't find any documentation on where to find those logs.

**Comment by sophiebits** [comment]
You'll have to refile this on the create-react-app project:

https://github.com/facebook/create-react-app

Do note that it is not very actively maintained and not recommended for new projects: https://react.dev/learn/start-a-new-react-project
