### ISSUE TITLE
Bug: script inside script render with SSR + renderToPipeableStream

### ISSUE THREAD

**Issue by artem-malko** [facebook/react#27267]
The question/bug is about SSR + renderToPipeableStream

There is an idea, how to Inject something Into the SSR Stream in [reactwg/react-18](https://github.com/reactwg/react-18/discussions/114) by @sebmarkbage And yes, works perfectly. For example, I use it to inject to an html data, that were fetched on the server.

There can be situation, when `<script>` inside another `<script>` returns from renderToPipeableStream

React version: 18.2.0

## Steps To Reproduce

Link to code example:

There is the source code: https://github.com/artem-malko/react-ssr-template
There is my injector: https://github.com/artem-malko/react-ssr-template/blob/main/src/framework/applications/server/utils/reactStreamRenderEnhancer.ts
And the usage: https://github.com/artem-malko/react-ssr-template/blob/main/src/framework/applications/server/createApplicationRouteHandler.tsx#L317

This project in action: http://174.138.13.187:5000/users?p=1 But it is extremely hard to repeat the bug  

## The current behavior

Sometimes I get a quite interesting situation, when there is a script tag (just `<script>`)  inside chunk. This script contains a config for an application. And I try to add one more script to a page by using this injector pattern. So, I see that script internals (the code) on the client side cause of `<script>` inside another `<script>`. 

## The expected behavior

Actually I don't know, how to fix this problem(

I can wrap the whole app with `<Suspense>` (that part, which is not in a shell. I mean https://github.com/artem-malko/react-ssr-template/blob/main/src/framework/applications/shell.tsx#L57C9-L57C19). But I'm not sure it is a good idea

**Comment by sophiebits** [comment]
I would try on the latest canary release of React. A lot of the server code has been rewritten so it's likely this has been fixed, and the next stable release will include all of those refactors. If it is still happening then we can reopen.
