### ISSUE TITLE
Bug: Rendering Twice in StrictMode with useSyncExternalStore Official Example

### ISSUE THREAD

**Issue by 1414bam** [facebook/react#27266]
React version: 18.2.0

## Steps To Reproduce

1. Import the useSyncExternalStore function from the 'react' module.
2. Define the ChatIndicator component which renders an online/offline indicator.
3. Inside the component, log 'render' to the console.
4. Define the getSnapshot function that returns the online status using navigator.onLine.
5. Define the subscribe function that adds event listeners for online and offline events and returns a cleanup function to remove the event listeners.
6. Inside the ChatIndicator component, call useSyncExternalStore with the subscribe and getSnapshot functions.
7. check the console window and verify if the word "render" appears twice.

Link to code example: https://codesandbox.io/s/5yhrdx?file=/App.js&utm_medium=sandpack

![Screenshot (51)](https://github.com/facebook/react/assets/53087479/e49e506d-170f-4bb1-a9ba-62d819cba5c0)

## The current behavior
The word "render" will be printed once in the console window.

## The expected behavior
The word "render" is printed twice in the console window.

**Comment by markerikson** [comment]
This seems like expected behavior. React will double-render components in strict mode.

**Comment by 1414bam** [comment]
Isn't it supposed to occur in case of problematic code, such as the listeners were not removed etc..?

**Comment by mbret** [comment]
The issue is still present even after the first two render on the mount. Meaning, everytime the store get a new value the entire hook will re-render twice. I don't think this is expected behavior since it duplicate every log in the console. I understand the double render on first mount to catch leak but it does not seem necessary for the rest of the runtime.

**Comment by mbret** [comment]
Any update on this ? Problem is still present
