### ISSUE TITLE
Bug:  Radio button onChange not called in current React Canary

### ISSUE THREAD

**Issue by Shubhamkanskar** [facebook/react#27284]
Create radio buttons that toggle disabled in onChange
After selecting each radio button, onChange is no longer called

**Comment by akuma2022** [comment]
Can I see how you present onChange?

**Comment by sophiebits** [comment]
I've committed a few fixes for radio buttons; I'm expecting that if you try with 18.3.0-canary-db69f95e4-20231002 then you will find that they are fixed but please let me know if not. If you have a repro case then we can reopen.
