### ISSUE TITLE
Bug: Memory leak for input element in react 18.2.0 and 16.14.0

### ISSUE THREAD

**Issue by mshmyw** [facebook/react#27289]
React version: 16.14.0 and 18.2.0

## Steps To Reproduce

I can give a demo more obvious, the demo: https://codesandbox.io/s/admiring-khayyam-3s64gq?file=/src/App.tsx

Steps To Reproduce:
1. a simple demo can be found Here: https://codesandbox.io/s/admiring-khayyam-3s64gq?file=/src/App.tsx
2. running GC and Take a heap snapshot
![image](https://github.com/facebook/react/assets/6376429/b2a4c112-ff59-4a2f-ad7d-3e7df7c68189)
3. Click 'open Modal click for test memory leak (has large input items)' and open modal
4. focus any input item
![image](https://github.com/facebook/react/assets/6376429/c00b87fa-5b4a-4213-95a2-ae97315c305e)
5. close modal
6. refresh state for click 'refresh state '
7. running GC and Take a heap snapshot
![image](https://github.com/facebook/react/assets/6376429/b0620fe4-6616-4d1b-b206-9a897f1d0cc3)

and after that you can found large detached input element exist

Link to code example:
https://codesandbox.io/s/admiring-khayyam-3s64gq?file=/src/App.tsx

## The expected behavior
hope some one can help resolve this

**Comment by sophiebits** [comment]
Will comment on #26069.
