### ISSUE TITLE
Bug: Sudden scroll on react website

### ISSUE THREAD

**Issue by raghchawla131** [facebook/react#27311]
React version: 18.2.0

## Steps To Reproduce

1.Open the React website in a web browser.
2.Attempt to scroll up or down using the scroll wheel, trackpad, or scroll bar.

Link to code example:

## The current behavior
When scrolling, the screen jumps suddenly to a different position on the page, causing an unpleasant and unexpected scrolling experience. This behavior makes it difficult to navigate and interact with the website content.

## The expected behavior
The scrolling should be smooth and fluid, allowing users to navigate through the website content without any sudden jumps.

**Comment by raghchawla131** [comment]
https://github.com/facebook/react/assets/112266194/d8f41211-3438-4b10-baa1-cf10bba648d2

**Comment by rajan153** [comment]
working fine for me.

**Comment by PurvishDhameliya** [comment]
this bug is solved?

**Comment by quki3** [comment]
I couldn't reproduce the issue in the browser. so I suppose that is a particular problem

**Comment by ademmeral** [comment]
I told them earlier about that. I was really annoying. I couldnt focus on what i was reading. :))

**Comment by n0vella** [comment]
Hi, this happens to me also reading docs, both on firefox and brave (windows 11), to reproduce this try to folow any docs page (ex: https://react.dev/learn/reacting-to-input-with-state) as you were actually reading it, it happens more near the end of the docs page, scroll slowly to keep the paragraph you are reading in the middle of the screen and you will found this bug.
