### ISSUE TITLE
ReactMount.nodeCache leaks objects during unmount

### ISSUE THREAD

**Issue by 1st1** [facebook/react#2731]
The scenario for this is pretty easy to reproduce:

1. Suppose we have a popup implementation -- there is a function to render popup view (react element) in an overlay div element, and a function to unmount the view and destroy the overlay.

2. In that popup we have a button element, with its onClick set to call the destroy popup function.

3. When a user clicks that button, React.unmountComponentAtNode is called, and react cleans everything up (ReactMount.nodeCache is empty), but then, react starts to process the blur event (remember, the user clicked the button to close the popup, so it was focused), and that resurrects the button element in ReactMount.nodeCache.

4. The button DOM element ends up being stuck in nodeCache forever, but the worst part of it is that a lot of DOM nodes (sometimes hundreds) are not subject for GC anymore.

**Comment by Aweary** [comment]
@spicyj this should be closed since https://github.com/facebook/react/commit/4ba0e95a96507abbcb2819be328fc3d1ed3cc80f removed `nodeCache`, right?

**Comment by spicyj** [comment]
Yeah, this should be fixed now. Thank you!
