### ISSUE TITLE
Bug: useEffect does not reset when you restart the VS Code debugger

### ISSUE THREAD

**Issue by Kwillson2** [facebook/react#27329]
When I push the restart button in VS Code's debugger, my app/index.js's useEffect does not get called again.  I assumed that restarting the debugger would restart everything to a clean state and go from there, but this does not appear to be the case.  I have to stop the debugger, then start a new debugging session for it get called again.  Is this intended?  Its not the end of the world, just annoying.

React version: react-native@0.71.8

## Steps To Reproduce

1. Put printout in useEffect 
2. Run debugger in VS Code
3. See printout
4. Click restart debugger
5. No printout

## The expected behavior
Restarting the debugger makes the react app go to a clean init state so useEffect gets called again

**Comment by Kwillson2** [comment]
It's pretty nice now, compared to over a year ago!  Can break anywhere and allows you to see all your variable values on the side bar or even cursor hovering over the variable.

**Comment by sophiebits** [comment]
I don't believe React would have any control over this. If the component is rerendered then effects will be rerun but how that interacts with the debugger is not controlled by us.
