### ISSUE TITLE
React Dev Tools doesn't work

### ISSUE THREAD

**Issue by elinadzhelilovasfcc** [facebook/react#27338]
I have a project based on React JS in the localhost and React Dev Tools doesn't work. I tried all steps from troubleshooting and it didn't help. I am using Chrome Version 116.0.5845.140
![Screenshot 2023-09-05 at 20 35 01](https://github.com/facebook/react/assets/98823823/ccd4140b-6b66-40a6-9ada-d08a09365c02)

**Comment by gur22-09** [comment]
faced a similar issue where the react dev tools were not functioning.

Fix 👇 
Try to update Chrome on the latest stable version and re-launch Chrome, it worked for me 
My Chrome version - Version 116.0.5845.179 (Official Build) (arm64)

**Comment by shubhankarval** [comment]
@gur22-09 is right, i also went through this before, it was very frustrating. Usually the answer in these cases is to upgrade the browser version, or make sure that the version of React DevTools is compatible with your React version.

**Comment by rizfanradya** [comment]
Here are some steps you can try to troubleshoot this issue:

1. Make Sure You Have a React Project: Ensure that you indeed have a React application running on localhost. React DevTools only work on applications that use React.

2. Update React DevTools: Make sure you have updated React DevTools to the latest version. Go to the Chrome Web Store, search for "React Developer Tools," and update the extension if necessary.

3. Update Chrome: Ensure that you are running the latest version of Google Chrome. Go to "chrome://settings/help" to check for updates and install them if available.

4. Disable Other Extensions: Some Chrome extensions can interfere with React DevTools and cause issues. Disable other extensions you have to see if the problem persists.

5. Try Incognito Mode: Try running your application in Chrome's incognito mode. Sometimes, unusual extensions or settings can cause issues.

6. Disable Cache: Open DevTools by right-clicking and selecting "Inspect" on your application in Chrome. Then, open the "Network" tab and check the "Disable cache" option. Refresh the page and see if React DevTools start working.

7. Check Console for Errors: Open Chrome DevTools (Ctrl + Shift + J or Cmd + Option + J on Mac), then check the "Console" tab to see if there are any errors related to React DevTools.

8. Check for Variable Name Conflicts: Ensure you are not using variables or names that clash with those used by React DevTools in your code, as this can cause conflicts.

9. Clear Cache and Cookies: Try clearing the cache and cookies for your localhost website and refresh the page.

10. Reinstall React DevTools: If none of the above steps work, you may need to try uninstalling and reinstalling React DevTools.

**Comment by hoxyq** [comment]
Can you please share a code sandbox where this can be reproduced? You can also try following the tips suggested above.

**Comment by elinadzhelilovasfcc** [comment]
> Can you please share a code sandbox where this can be reproduced? You can also try following the tips suggested above.



> Here are some steps you can try to troubleshoot this issue:
> 
> 1. Make Sure You Have a React Project: Ensure that you indeed have a React application running on localhost. React DevTools only work on applications that use React.
> 2. Update React DevTools: Make sure you have updated React DevTools to the latest version. Go to the Chrome Web Store, search for "React Developer Tools," and update the extension if necessary.
> 3. Update Chrome: Ensure that you are running the latest version of Google Chrome. Go to "chrome://settings/help" to check for updates and install them if available.
> 4. Disable Other Extensions: Some Chrome extensions can interfere with React DevTools and cause issues. Disable other extensions you have to see if the problem persists.
> 5. Try Incognito Mode: Try running your application in Chrome's incognito mode. Sometimes, unusual extensions or settings can cause issues.
> 6. Disable Cache: Open DevTools by right-clicking and selecting "Inspect" on your application in Chrome. Then, open the "Network" tab and check the "Disable cache" option. Refresh the page and see if React DevTools start working.
> 7. Check Console for Errors: Open Chrome DevTools (Ctrl + Shift + J or Cmd + Option + J on Mac), then check the "Console" tab to see if there are any errors related to React DevTools.
> 8. Check for Variable Name Conflicts: Ensure you are not using variables or names that clash with those used by React DevTools in your code, as this can cause conflicts.
> 9. Clear Cache and Cookies: Try clearing the cache and cookies for your localhost website and refresh the page.
> 10. Reinstall React DevTools: If none of the above steps work, you may need to try uninstalling and reinstalling React DevTools.

I tried all of them. Also, I tried Firefox and the same result, it doesn't work

**Comment by hoxyq** [comment]
> > Can you please share a code sandbox where this can be reproduced? You can also try following the tips suggested above.
> 
> > Here are some steps you can try to troubleshoot this issue:
> > 
> > 1. Make Sure You Have a React Project: Ensure that you indeed have a React application running on localhost. React DevTools only work on applications that use React.
> > 2. Update React DevTools: Make sure you have updated React DevTools to the latest version. Go to the Chrome Web Store, search for "React Developer Tools," and update the extension if necessary.
> > 3. Update Chrome: Ensure that you are running the latest version of Google Chrome. Go to "chrome://settings/help" to check for updates and install them if available.
> > 4. Disable Other Extensions: Some Chrome extensions can interfere with React DevTools and cause issues. Disable other extensions you have to see if the problem persists.
> > 5. Try Incognito Mode: Try running your application in Chrome's incognito mode. Sometimes, unusual extensions or settings can cause issues.
> > 6. Disable Cache: Open DevTools by right-clicking and selecting "Inspect" on your application in Chrome. Then, open the "Network" tab and check the "Disable cache" option. Refresh the page and see if React DevTools start working.
> > 7. Check Console for Errors: Open Chrome DevTools (Ctrl + Shift + J or Cmd + Option + J on Mac), then check the "Console" tab to see if there are any errors related to React DevTools.
> > 8. Check for Variable Name Conflicts: Ensure you are not using variables or names that clash with those used by React DevTools in your code, as this can cause conflicts.
> > 9. Clear Cache and Cookies: Try clearing the cache and cookies for your localhost website and refresh the page.
> > 10. Reinstall React DevTools: If none of the above steps work, you may need to try uninstalling and reinstalling React DevTools.
> 
> I tried all of them. Also, I tried Firefox and the same result, it doesn't work

Unfortunately, this is not enough to understand what is causing the problem.
Can you please share some reproducible example or describe how is the application loading React?

**Comment by hoxyq** [comment]
Please reopen once you have something that will help reproduce this problem.

**Comment by ajpinto** [comment]
I am also having this issue. On the latest stable chrome build 118.0.5993.70. I've followed all troubleshooting steps above, I've removed and reinstalled, restarted chrome, allowed access to file URLs. Nothing works.

**Comment by hocktoh89** [comment]
Same here, Chrome Version 118.0.5993.88 (Official Build) (arm64), React Developer Extension is not working, I need the profiler, Please help. please....

**Comment by ajpinto** [comment]
> Same here, Chrome Version 118.0.5993.88 (Official Build) (arm64), React Developer Extension is not working, I need the profiler, Please help. please....

i’ve been able to get the extension to work in incognito. you have to activate it in the advanced extension settings, then it shows up. it’s not a fix but it’s a workaround until we can get the issue solved.

**Comment by hocktoh89** [comment]
> > Same here, Chrome Version 118.0.5993.88 (Official Build) (arm64), React Developer Extension is not working, I need the profiler, Please help. please....
> 
> i’ve been able to get the extension to work in incognito. you have to activate it in the advanced extension settings, then it shows up. it’s not a fix but it’s a workaround until we can get the issue solved.

Thanks @ajpinto , it works in Incognito.

**Comment by hocktoh89** [comment]
anyone experience the same issue again with Chrome Version 119.0.6045.105 (Official Build) (arm64) ?
Now even Incognito mode is not working. Giving up chrome, I am using other browser now, But hopefully this can be fixed in Chrome

**Comment by hoxyq** [comment]
Few possible advices here:
1. Make sure you've granted access "On all sites" for the extension. As its stated in https://github.com/facebook/react/issues/27564
2. If you have React DevTools' popup working, but its panels are not available in Chrome DevTools, try restoring Chrome DevTools settings to defaults - https://github.com/facebook/react/issues/27564#issuecomment-1799117168

**Comment by ajpinto** [comment]
> anyone experience the same issue again with Chrome Version 119.0.6045.105 (Official Build) (arm64) ? Now even Incognito mode is not working. Giving up chrome, I am using other browser now, But hopefully this can be fixed in Chrome

@hocktoh89 following @hoxyq's notes, i reset the chrome dev tools settings to default and react devtools returned.

**Comment by akchauhan2** [comment]
**[Solved]** I experienced the same issue where the component and profiler tabs were missing, and I couldn't open the React DevTools. I tried reinstalling React DevTools and other extensions, but the problem persisted. Finally, I found a solution which worked for me. Simply open the developer tools (<kbd>F12</kbd>) and press the <kbd>F1</kbd> key while in the developer tools. This will open the DevTools Settings. Navigate to the Preference tab, scroll to the bottom, and click "Restore default and reload." Now reload the chrome and open a React based site, You'll get components and profiler. thank me later.
![image](https://github.com/facebook/react/assets/42740900/5e1d9912-9c68-40e9-a39c-829545fae27e)

**Comment by randdom-addvice** [comment]
> **[Solved]** I experienced the same issue where the component and profiler tabs were missing, and I couldn't open the React DevTools. I tried reinstalling React DevTools and other extensions, but the problem persisted. Finally, I found a solution which worked for me. Simply open the developer tools (F12) and press the F1 key while in the developer tools. This will open the DevTools Settings. Navigate to the Preference tab, scroll to the bottom, and click "Restore default and reload." Now reload the chrome and open a React based site, You'll get components and profiler. thank me later.
> 
> ![image](https://private-user-images.githubusercontent.com/42740900/290995456-5e1d9912-9c68-40e9-a39c-829545fae27e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTU2MDgsIm5iZiI6MTcwMjkxNTMwOCwicGF0aCI6Ii80Mjc0MDkwMC8yOTA5OTU0NTYtNWUxZDk5MTItOWM2OC00MGU5LWEzOWMtODI5NTQ1ZmFlMjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE2MDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNjJmNDg1ZDM0MDE4MDA3OWQxYTYwZGZiNGE5YzliNmViNTM5Y2YxZDRmY2I4MzU4MWM3ZWZhMzM1ZjM2OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_I_XhYbZc-MJEm_syR5coiC6at3VmjWKO8nNRFm9oA)

This worked for me!

**Comment by kaiyuncheng** [comment]
> **[Solved]** I experienced the same issue where the component and profiler tabs were missing, and I couldn't open the React DevTools. I tried reinstalling React DevTools and other extensions, but the problem persisted. Finally, I found a solution which worked for me. Simply open the developer tools (F12) and press the F1 key while in the developer tools. This will open the DevTools Settings. Navigate to the Preference tab, scroll to the bottom, and click "Restore default and reload." Now reload the chrome and open a React based site, You'll get components and profiler. thank me later.
> 
> ![image](https://private-user-images.githubusercontent.com/42740900/290995456-5e1d9912-9c68-40e9-a39c-829545fae27e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mzg0NzIsIm5iZiI6MTcwNjczODE3MiwicGF0aCI6Ii80Mjc0MDkwMC8yOTA5OTU0NTYtNWUxZDk5MTItOWM2OC00MGU5LWEzOWMtODI5NTQ1ZmFlMjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIxNTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjQxZjVkOTE2M2Y2ZWYyZjZiOGJlMjVlM2JmZGE1MTAxZTUzOTE0YmU4ZWM0YzQ2NDgzMjk2MGRiMmJjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NkyDxVV7l-6BZEuJGz44AJ9lfZC0oituGV2e2lD9ENE)

Thank you so much
