### ISSUE TITLE
Control blocking vs lazy behavior of Suspense during renderToPipeableStream

### ISSUE THREAD

**Issue by yepitschunked** [facebook/react#27350]
When using renderToPipeableStream, it would be useful if the renderer could block on certain Suspense boundaries instead of using the fallback and streamed rendering. For example, our app shell consists of static data (script/CSS tags, etc.) as well as some loading state HTML. The loading state HTML unfortunately still depends on an async network request made outside of React. It would be convenient to structure our app like this:

```jsx
<html>
  <head>
    <script src="..." />
    <link href ="..." />
    {/* various script, link, meta tags */}
  </head>
  <body>
    <Suspense>
      {/* this suspends with initialStatePromise internally */}
      <AppShell initialState={initialStatePromise}>
         {/* Our actual app, with its own internal suspense boundaries */}
         <App />
      </AppShell>
    </Suspense>
  </body>
</html
```

This would ensure that:

1. Static assets are flushed immediately
2. The AppShell suspends on the initial state and renders when that's ready
3. Our actual application code can fetch data and render product-specific loading states normally, with HTML streaming

For various technical (or ideological...) reasons, we want that the initial loading state to be visible without depending on React's JS to patch things up. As a result, we can't have that Suspense boundary around the AppShell - React would suspend and send an empty `<body>`. We need to await the `initialStatePromise` before we begin rendering. This in turn delays our static script/link tags, hurting our time to paint. 

We could solve this if we could tell React to *block* on `initialStatePromise`, instead of rendering the fallback and moving on. I have a couple of ideas for what this API could look like, as well as ways to implement this outside of React.

### Userland implementations

I read https://github.com/reactwg/react-18/discussions/106 and https://github.com/reactwg/react-18/discussions/108 and the general idea of transforming React's response stream seems applicable here. We could do something super hacky like wrapping React's stream and inspecting each chunk to perform the stitching that React's runtime would've done client-side. Upon encountering a blocking Suspense boundary, the transform stream would start buffering React's output, while waiting for the rendered content to appear. 

Another approach could be to simply handle the app shell ourselves (by writing directly to the response); this is what we were doing pre-react 18 anyway. However, the docs for `renderToPipeableStream` [explicitly state](https://react.dev/reference/react-dom/server/renderToPipeableStream#parameters):
> It is expected to represent the entire document, so the App component should render the <html> tag

### Possible React API

renderToPipeableStream could take a list of `blockingPromises`. If caught by a Suspense boundary, these promises would pause the renderer and response stream . I'm not sure how feasible this is with the renderer internals, though - it'd have to stop at a half-open tag and partially rendered component.

**Comment by sophiebits** [comment]
> we want that the initial loading state to be visible without depending on React's JS to patch things up

Just to be clear, you're looking to avoid the couple lines of JS in the streaming runtime (https://github.com/facebook/react/blob/9617d39eca1fbac58afe73a23580d781ea20211d/packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInstructionSetInlineCodeStrings.js)?

Curious – is there an actual reason this matters for you in practice or just that it feels unclean?

**Comment by yepitschunked** [comment]
Yeah, we'd just rather not have a completely blank page when JS is disabled.

**Comment by sophiebits** [comment]
@sebmarkbage Thoughts on if it makes sense to have a way to start rendering the shell immediately but block when encountering the first Suspense boundary?

**Comment by sebmarkbage** [comment]
I don’t get. Why not just remove the Suspense boundary?
