### ISSUE TITLE
how to use react developer tools in chrome

### ISSUE THREAD

**Issue by p2216** [facebook/react#27355]

**Comment by rizfanradya** [comment]
1. Install React Developer Tools:
   - Open Google Chrome.
   - Go to the [Chrome Web Store](https://chrome.google.com/webstore).
   - Search for "React Developer Tools" in the search bar.
   - Find the extension and click "Add to Chrome."
   - Confirm the installation by clicking "Add Extension" in the popup window.

2. Enable React Developer Tools:
   - After installation, you'll see the React logo (a blue icon) in the top-right corner of your Chrome browser, next to the address bar.
   - Click on the React icon to open the React Developer Tools panel.

3. Inspect React Components:
   - Once the React Developer Tools panel is open, you can inspect your React components.
   - Visit a website or web application built with React.

4. Use React Developer Tools:
   - Open the Chrome Developer Console by pressing `Ctrl + Shift + J` (Windows/Linux) or `Cmd + Option + J` (Mac).
   - In the Developer Console, switch to the "React" tab (you may need to click on the ">>" button to find it).

5. Inspect React Components:
   - In the "React" tab, you can see the component hierarchy of the current web page.
   - Click on a component to inspect its props and state, view component updates, and see the component tree structure.

6. Interact with Components:
   - You can interact with the components by changing props or state values in the React Developer Tools panel. This can be useful for debugging and testing.

7. Navigate Through Component Hierarchy:
   - Use the component hierarchy tree to navigate through different components in your application.

8. Search for Components:
   - You can use the search bar in the React Developer Tools panel to find specific components by name.
