### ISSUE TITLE
Bug: Components which doesn't consume Context are re-rendered when context state is updated

### ISSUE THREAD

**Issue by Deepakrishikesh** [facebook/react#27363]
All components directly wrapped under `Context.Provider` are re-rendered even if the component doesn't consume the context value. This works fine if the all the components are passed as `children` prop to the provider.

React version: 18.2.0

## Steps To Reproduce

1. Create a simple context, with state and corresponding setState() as value of `Context.Provider`.
2. Create a component, consume the context and add a button for updating the state.
3. Create a component (doesn't consume the context) and wrap directly inside `Context.Provider`.
4.  console.log some message on both components to identify them re-rendering
5. Update the context state, by clicking the button.
6. We can see that both components are re-rendered

Link to code example: https://codesandbox.io/p/sandbox/infallible-elion-23wwh7?file=%2Fapp%2Fcontext.tsx%3A1%2C1

**Comment by markerikson** [comment]
This is fully expected and standard React behavior.  React re-renders recursively by default.

See the explanation I wrote here (and you'll probably want to read the entire post):

- https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#context-and-rendering-behavior
