### ISSUE TITLE
[Feature Request]: RSC error - allow error.code or an other specialized prop to be forwarded to the client

### ISSUE THREAD

**Issue by benji24290** [facebook/react#27362]
I've observed that React Server Components currently send a digest to the client in case of an error, without forwarding the exact error. This behavior can sometimes be limiting, especially when we want to handle specific error cases on the client-side, like the 401 Unauthorized status.

To tackle this, I've introduced a mechanism that selectively forwards specific error codes to the client, without compromising on security or exposing sensitive error messages.

### Possible solutions:

1. **Forwarding the error.code Property:**

* Altered the server component's response handler to recognize and extract the `error.code` property during error scenarios.
* If the `error.code` is present and matches our predefined whitelist, it's forwarded to the client. This allows the client to understand specific error types without exposing detailed server messages.

2. **Custom Digest Configuration:**

* Implemented a mechanism for developers to provide a custom digest. 
* The default behavior remains to send the generic digest unless the developer specifies this custom function, providing flexibility without compromising security.

3. **Introduction of a Specific Error Prop:**

* Introduced a new property to the error object, named `clientHint`. This prop can be set on the server-side and is designed to provide hints or specific behaviors that the client should adopt upon encountering the error.
* On the client-side, React components can now access this `clientHint` prop and act accordingly, giving developers a structured way to pass actionable instructions from server to client during error scenarios.

### Benefits of this Change:

* Efficient Error Handling: Allows client-side code to react immediately based on the error code, without making an additional request.
* Enhanced User Experience: Enables smoother user redirects or prompts based on specific error scenarios.
* Developer Flexibility: By making the whitelist configurable, we provide developers control over error handling without compromising on security.
Looking Forward:

Looking forward to the community's thoughts!

Thank you!

**Comment by sophiebits** [comment]
The onError function in the configuration you pass can return an error digest, which should solve your use case.

For example Next.js does it here for a couple custom error types: https://github.com/vercel/next.js/blob/ab7b0f59fb0d793fb4ee593ae93f7e08bab23b5b/packages/next/src/server/app-render/create-error-handler.tsx#L37-L45

Hope that helps!
