### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by smalllhui** [facebook/react#27384]
# Vite cannot import dynamically components 
issue link:https://github.com/smalllhui/vite-react-dynamic-import-test/
## 1、issue

>vite dynamically import components, error info: Uncaught TypeError: ctor is not a function。
>but webpack is ok。
>
![bug](https://github.com/facebook/react/assets/80555137/c0b9f959-17ee-4bab-8f10-832037a8373f)

>![index](https://github.com/tom-sherman/react-lazy-fragment-bug/assets/80555137/d37c8f96-5b6c-490e-86f5-131513634cec)

## 2、Project directory

```
src
|-- App.tsx
|-- main.tsx
|-- pages
|   |-- Home
|   |   `-- index.tsx
|   `-- NotFound
|       `-- index.tsx
|-- utils
|   `-- LazyLoad.ts
```

## 3、code

**src/pages/Home/index.tsx**

```tsx
import React from "react"

/**
 * @Description:Home组件
 */
const index: React.FC = () => {
  return <div>Home组件</div>
}

export default index
```

**src/pages/NotFound/index.tsx**

```tsx
import React from "react"

/**
 * @Description: 资源不存在页面
 */
const NotFound: React.FC = () => {
  return <div>资源不存在页面</div>
}

export default NotFound
```

**src/utils/LazyLoad.tsx**

```tsx
import React from "react"

/**
 * 动态懒加载路由 vite不生效  webpack is ok
 * @param locale 本地路由路径
 * @returns
 */
const lazyLoadComponent = (locale: string) => {
  const modules = import.meta.glob(["@/pages/**/*.tsx"])
  let Comp = modules[`/src/${locale}/index.tsx`]
  if (!Comp) Comp = () => import("@/pages/NotFound")
  return React.lazy(Comp() as any)
}

export default lazyLoadComponent
```

**App.tsx**

```tsx
import React, { Component, PropsWithChildren, Suspense } from "react"

import lazyLoadComponent from "@/utils/LazyLoad"

/**
 * 错误边界捕获类
 */
class ErrorBoundary extends Component<PropsWithChildren> {
  state = { error: null }
  // 1.通过componentDidCatch
  componentDidCatch(error: any, errorInfo: any) {
    this.setState({ error })
    console.log("捕获到错误", error, errorInfo)
  }
  render() {
    if (this.state.error) {
      return <div>边界捕获UI</div>
    }

    return this.props.children
  }
}

/**
 * @Description: 需求：react动态导入Home组件渲染到页面
 */
const App: React.FC = () => {
  const LazyHome = lazyLoadComponent("pages/Home")
  return (
    <ErrorBoundary>
      <h1>App组件</h1>
      <Suspense fallback={<div>loading...</div>}>
        <LazyHome />
      </Suspense>
    </ErrorBoundary>
  )
}

export default App


```

**Comment by sophiebits** [comment]
The link https://github.com/smalllhui/vite-react-dynamic-import-test/ is giving me an error for me.

This doesn't sound like a React-specific issue. One issue I see is I think you meant `React.lazy(Comp as any)`, not `React.lazy(Comp() as any)`. If that doesn't solve it, I would recommend looking for help in the Vite community as the behavior of import() is entirely controlled by the bundler.
