### ISSUE TITLE
tutorial improvement: don't use python for the http server, use node

### ISSUE THREAD

**Issue by Pomax** [facebook/react#2739]
Since the tutorial describes doing things either in the browser or in node, it doesn't make sense to advocate using `python -m SimpleHTTPServer`. Instead it makes more sense to tell people to run `npm install -g http-server` and to then use the much simple `http-server` command to fire up a localhost instance on port 8080 in whatever directory they run it in.

**Comment by ChrisAntaki** [comment]
A beginner web developer on Windows might get discouraged if they thought they had to install Python in the middle of the tutorial. Mentioning `http-server` could help. Plus, some beginner Node.js developers might be excited to find out about the package.

**Comment by spicyj** [comment]
#2824 landed, so I'm closing this.

**Comment by ChrisAntaki** [comment]
:+1:
