### ISSUE TITLE
Bug: missing button data in form when submitted via `formAction`

### ISSUE THREAD

**Issue by mattcarrollcode** [facebook/react#27391]
When a form action is triggered by a button that is outside the form's tag the button's `name` and `value` is missing from the form data provided to the action. When the button submitting the form is inside the form tag the button's form data is properly surfaced to the action:

![output](https://github.com/facebook/react/assets/7158882/5e2fd2c7-3f38-4fc5-ac6e-0cf2de16e3c1)

React version: 0.0.0-experimental-2807d781a-20230918

## Steps To Reproduce

1. Create a form that calls an action when submitted with a button outside the form tag  submits the form. The button that submits the form should have the `name` and `value` attributes set with non-null values. The action should take a `formData` argument and log the button's value:
   ```
   function Component() {
     function action(formData) {
       console.log(formData.get("n1"));
     }
     return (
       <>
         <button type="submit" name="n1" value="v1" form="form-id">
           Submit
         </button>
         <form action={action} id="form-id"></form>
       </>
     );
   }
   ```
3. Click the button that submits the form

Link to code example: https://codesandbox.io/s/flamboyant-meadow-gcvpx9?file=/App.js

## The current behavior
The `formData` provided to the form action doesn't contain the key-value pair information of the button that submitted the form when the button is outside the form's tag. This means that nothing is logged because the `n1` key doesn't exist in `formData`

## The expected behavior
The value of the external button to be logged (`v1` in the example above) because `formData` includes the

**Comment by lllomh** [comment]
Hi, your gifs are too small, opening a separate window is still too small to see, can you provide large clear gifs?

**Comment by lllomh** [comment]
Hi, in this case, the sayHello method is executed on the form. There is no reason why the sayHello() argument should receive any value outside of the form.

![image](https://github.com/facebook/react/assets/20123291/5430c0e2-ab8b-437a-8564-1bd40c56090a)

**Comment by mattcarrollcode** [comment]
Standard HTML forms provide the name and value of the button in the form data even if the button is outside the form tag: https://codesandbox.io/p/sandbox/practical-smoke-h6s2wp?file=%2Fapp.js%3A11%2C24

**Comment by SiddiqAM1** [comment]
import React, { useRef } from "react";

const Component = () => {
  const submitButtonRef = useRef(null);

  function action(formData) {
    console.log(formData.get("n1"));
  }

  function handleSubmit(event) {
    event.preventDefault();
    submitButtonRef.current.click();
  }

  return (
    <>
      <button type="button" onClick={handleSubmit}>
        Submit
      </button>
      <form action={action} id="form-id">
        <input type="hidden" name="n1" value="v1" />
        <input type="submit" ref={submitButtonRef} />
      </form>
    </>
  );
};

export default Component;

**Comment by SiddiqAM1** [comment]
Use a hidden submit button inside of the form tag and programmatically click it when the external button is clicked.

**Comment by SiddiqAM1** [comment]
you can also use React Hook Form Library

**Comment by mattcarrollcode** [comment]
This also seems to be a problem when using `formAction` on a button *inside* the form. If you have a button that has the `formAction` attribute the `name` and `value` of that button are not surfaced in the form data reguardless of whether the button is inside the form or outside the form.

Code example comparing a "default" submit button (which does surface the button's form data properly) and a button with the `formAction` attribute set with a client action handler:  https://codesandbox.io/s/hungry-bose-j6tv7p?file=/App.js

**Comment by sophiebits** [comment]
Code pointer for debugging – it's meant to be added here:

https://github.com/facebook/react/blob/e3748a0bde80dd1f097fd8000702aba9fca454ef/packages/react-dom-bindings/src/events/plugins/FormActionEventPlugin.js#L83-L97

**Comment by Shubhdeep12** [comment]
> This also seems to be a problem when using `formAction` on a button _inside_ the form. If you have a button that has the `formAction` attribute the `name` and `value` of that button are not surfaced in the form data reguardless of whether the button is inside the form or outside the form.
> 
> Code example comparing a "default" submit button (which does surface the button's form data properly) and a button with the `formAction` attribute set with a client action handler: https://codesandbox.io/s/hungry-bose-j6tv7p?file=/App.js

it should be formation instead of formAction and ideally it should be used with type="submit"

**Comment by AlejandroBlanco2001** [comment]
@mattcarrollcode I have faced this similar issue when building forms with the button outside the `<form>` tag and using the attribute `form` inside the button with React. I think that in your example works because is pure HTML, but as for as I understand this situations is due on how React handles this event, to overcome this I always use `onSubmit` event. 

Maybe have a deeper look on the code pointed by @sophiebits would give more clarity.

**Comment by lllomh** [comment]
This is an auto-reply email.Hi, due to the high volume of emails, I will get back to you as soon as possible within three days.

**Comment by jupapios** [comment]
I just created a PR that should fix the original issue, @mattcarrollcode regarding the [second issue](https://github.com/facebook/react/issues/27391#issuecomment-1732025222), it seems there is a [test](https://github.com/facebook/react/blob/main/packages/react-dom/src/__tests__/ReactDOMForm-test.js#L531) that expects such behavior, so I guess that, for now, it is expected, but I might be wrong, @sophiebits can you confirm, please? 🙏

**Comment by lllomh** [comment]
This is an auto-reply email.Hi, due to the high volume of emails, I will get back to you as soon as possible within three days.
