### ISSUE TITLE
Bug: react native android shaking on scroll 

### ISSUE THREAD

**Issue by ejjraifihamza** [facebook/react#27402]
when i try to scroll slowly (android) it's shaking/flickering, work fine on ios 

React version:

Steps to reproduce
Build the minimal reproducible example on Android
Try scrolling list slowly up
See shaking/flickering as user is scrolling, iOS is normal.

React Native version
0.68.0

Platforms
Android

Workflow
React Native (without Expo)

Acknowledgements
Yes

**Comment by pwbriggs** [comment]
Hey @ejjraifihamza!

Do you mind sending a minimal reproducible example showing your issue? A screen recording, if possible, could also help.

Thanks!
