### ISSUE TITLE
Bug: Lockdown Failed

### ISSUE THREAD

**Issue by InsightfulFuture** [facebook/react#27411]
React version: Latest

## Steps To Reproduce

1. Go to [react.dev](https://react.dev) (or other react app in prod or dev build)
2. Open inspect pane

Link to code example: [Example Codesandbox](https://codesandbox.io/s/nifty-ace-5zh2k9). If you have the console open and reload you will see the errors for a second then they will vanish as the internal console logs are cleared. To actually see it and not have it vanish, go to [react.dev](https://react.dev)

## The current behavior
There are 2 issues in the console:
```
lockdown-run.js:17 Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3
```
and
```
lockdown-run.js:17 Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3
```
The website works fine but having errors in the console can impact google SEO and is generally not best practice.

## The expected behavior
No errors in the console, at least building the react app removes the errors and not with a temporary fix such as `console.clear()`.

**Comment by InsightfulFuture** [comment]
This also happens on the [legacy react docs](https://legacy.reactjs.org/)

**Comment by mdmasudrana** [comment]
If you're using the Metamask wallet extension or another Chrome extension, you can try removing Metamask wallet and checking the console status. This might help resolve the "Lockdown Failed" bug.

**Comment by codespearhead** [comment]
Does this happen on a fresh installation of browsers? Because I don't seem to be able to reproduce the issue. The above user might be onto something.

**Comment by mdmasudrana** [comment]
The issue does not occur on fresh browser installations, and we are unable to reproduce it. However, if you install the Metamask wallet or any other extension, it may trigger the problem.

**Comment by InsightfulFuture** [comment]
Thanks, sorry for the delay, I do have the Metamask extension and that fixes it.

**Comment by kobrak1** [comment]
> The issue does not occur on fresh browser installations, and we are unable to reproduce it. However, if you install the Metamask wallet or any other extension, it may trigger the problem.



> If you're using the Metamask wallet extension or another Chrome extension, you can try removing Metamask wallet and checking the console status. This might help resolve the "Lockdown Failed" bug.

That's exactly the solution of this problem. I removed the metamask extension and the problem is solved. Thx man

**Comment by shashankpatil125** [comment]
but if i want the metamask extension as well then ?

**Comment by kobrak1** [comment]
> but if i want the metamask extension as well then ?

Then right-click on the Metamask icon at the top-right of your browser, then click "This can read and change site data", then choose "When you click the extension". Of course, you don't have to remove the Metamask extension. Have a nice day :)

**Comment by bjpogs** [comment]
any alternative to connect metamask in my react app?

**Comment by Bobby-iv** [comment]
This is a MetaMask related error. If you have MetaMask extension installed into your browser, try to remove it. And your error will disappear. Of course, no need tough to remove your wallet :)

**Comment by TetianaMolchanova** [comment]
Happenned with Vue 3

**Comment by sakele1026** [comment]
I see. Thanks for your reply.

**Comment by MrUnzO** [comment]
This happened even with Vanilla javascript.

**Comment by codespearhead** [comment]
This is something that should be reported in that extension's repository imo, because whatever it does on the page is out of React's control.
