### ISSUE TITLE
Bug: I can't opt out of Suspense on SSR (using Next.js in dev)

### ISSUE THREAD

**Issue by testerez** [facebook/react#27420]
According to [`Suspense` doc](https://react.dev/reference/react/Suspense):

> If a component throws an error on the server, React will not abort the server render. Instead, it will find the closest <Suspense> component above it and include its fallback (such as a spinner) into the generated server HTML. The user will see a spinner at first.

This works as expected in production mode when I build then run my next app. However, in dev mode, the error overlay is shown, making the strategy not very practical.

React version: 18.2.0

## Steps To Reproduce

Just open this [codesandbox](https://codesandbox.io/p/github/testerez/suspense-error-example/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clmzba7a600073b6pbbn7s7re%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clmzba7a600033b6p04mnjs80%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clmzba7a600053b6p8mf17e2x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clmzba7a600063b6psc5n1gmh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clmzba7a600033b6p04mnjs80%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clmzba7a600023b6p5zodpt6a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clmzba7a600033b6p04mnjs80%2522%252C%2522activeTabId%2522%253A%2522clmzba7a600023b6p5zodpt6a%2522%257D%252C%2522clmzba7a600063b6psc5n1gmh%2522%253A%257B%2522id%2522%253A%2522clmzba7a600063b6psc5n1gmh%2522%252C%2522activeTabId%2522%253A%2522clmzbamw100733b6pph90ixwh%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clmzbamw100733b6pph90ixwh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clmzba7a600053b6p8mf17e2x%2522%253A%257B%2522id%2522%253A%2522clmzba7a600053b6p8mf17e2x%2522%252C%2522activeTabId%2522%253A%2522clmzba7a600043b6pmqlr92yj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clmzba7a600043b6pmqlr92yj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clmzba7eq000ne6ejhec3fkq0%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clmzbak6i005q3b6pgb22tuht%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

## The current behavior

It works as expected in prod build but I get an error in dev mode.

## The expected behavior

I don't want to have an error in dev mode

**Comment by testerez** [comment]
Related issue in nextjs: https://github.com/vercel/next.js/issues/53987

**Comment by sophiebits** [comment]
In the latest canary release of React you should be able to call `unstable_postpone()` imported from react-dom and that will be the best API to use for this use case especially once the prefix is eventually removed.

If you were using App Router then you could use this API today I believe, but for Pages Router unfortunately I don't have a better suggestion in the meantime since it is still on 18.2.0 and this API isn't yet available in a stable versioned React release.

**Comment by testerez** [comment]
Thanks @sophiebits
