### ISSUE TITLE
[issue]: selfbaseduration is 0ms but flamechart shows component did render and rendered for <0.1ms

### ISSUE THREAD

**Issue by VLPUBI** [facebook/react#27429]
### Website or app

https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

### Repro steps

I added a website/app but it is not applicable, this is a general issue I am encountering for react-devtools

How does the Profiler know when a component has re-rendered for <0.1 ms even when its actual duration for a render event is the exact same as the actual duration of its only child component. 

For example: if I have a budgetChart component that shows actual duration of .2 ms, and a selfbaseduration of 0 ms, and its child component- budget - has a actual duration of .2ms and a selfbaseduration of .2ms, I would assume that the budget chart component in the flame graph would be grayed out and say “did not render” but instead, in some cases it is NOT gray and shows that it has rendered for “<0.1ms of .2ms”. How does the profiler know when something has rendered even though its selfbaseduration is 0ms (console logged in the actual react fiber tree from the _REACT_DEVTOOLS_GLOBAL_HOOK_)

SCREENSHOTS:

![Screen Shot 2023-09-28 at 11 21 16](https://github.com/facebook/react/assets/103336583/142807fb-fa68-4b0b-b2ee-7878dc8494bd)
![Screen Shot 2023-09-28 at 11 23 30](https://github.com/facebook/react/assets/103336583/66bb43e9-fd08-4d9e-afce-e605e0beb95c)

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Hey @VLPUBI, thanks for opening this issue :)

> How does the profiler know when something has rendered even though its selfbaseduration is 0ms?
In your case, the reason why `Budget` was rendered is that `Dashboard` component (its parent) was rendered.

You can interpret this number as "how much time React spent doing its internal calculations to render this component", and "render" here doesn't include DOM-related work and layout.

You should also not rely on fiber's object structure, these are private APIs and they can change.

What is the general problem that you are trying to solve with this approach?
