### ISSUE TITLE
Bug: StrictMode is not detecting "ref-trashing"

### ISSUE THREAD

**Issue by theKashey** [facebook/react#27432]
React version:
- any (18.2.0 currently)

## Steps To Reproduce

1. create unstable ref on a component (`<div ref={(node) => setState(node)}/>`) 
2. render/re-render component 
3. StrictMode will not report about the problem of ref being unstable between renders

Link to code example:

there are many different ways to create unstable ref:
- use `createRef` instead of `useRef` (happens)
- use functions without `useCallback`
- use different "mergeRefs" solutions leading to unstable refs, see https://github.com/gregberge/react-merge-refs/issues/5

## The current behavior

- nothing enforces the correct usage of refs or able to inform about the incorrect ones

## The expected behavior

- StrictMode is capable of reporting refs being updated on every render

-----

I've monkey-patched react code (`markRef` [here](https://github.com/facebook/react/blob/34de2986dfeddda31cb76d298c6d59b271d976fa/packages/react-reconciler/src/ReactFiberBeginWork.js#L1087) and [here](https://github.com/facebook/react/blob/34de2986dfeddda31cb76d298c6d59b271d976fa/packages/react-reconciler/src/ReactFiberCompleteWork.js#L1227)) to get informed about ref change and found a few changes that should not happen. 

This a problem very hard to detect without a support from the platform, and my little experiment is incapable to understand the legacy of ref update, only the fact of such update.

**Comment by sophiebits** [comment]
This is not technically incorrect code. Generally there should not be a need to store a DOM node in state.

Thanks for the idea but we don't have plans to add more to StrictMode at this time; I would recommend using a lint rule to prevent the patterns you mentioned if this is important for your project.
