### ISSUE TITLE
0.11.1

### ISSUE THREAD

**Issue by Mifloy** [facebook/react#27437]

**Comment by pwbriggs** [comment]
Hey there @Mifloy 👋, and welcome to the React community!

It seems that the title and description of your issue report are a bit vague. Could you please provide more details about the problem you're facing or any specific steps to reproduce it? This will help me and others better understand the issue and offer a solution.

Alternatively, if this is not an issue or you fixed it yourself, would you mind marking the issue as "closed" so other contributors know?
