### ISSUE TITLE
Bug: react-error-boundary using class fields unsupported in Safari 13.1

### ISSUE THREAD

**Issue by hoorncj-student** [facebook/react#27449]
We are using webpack to bundle a React app that includes react error boundaries.
When running our app in Safari 13.1, the app fails to render due to syntax errors in react-error-boundary due to its use of public class fields, which are not supported.

React version: 17.0.1

## Steps To Reproduce

1. Bundle app with react error boundaries
2. Open app in Safari 13.1

## The current behavior
Browser fails to parse script and outputs "error  Parsing error: Unexpected token ="

## The expected behavior
I would expect React features to work in ES5 supported browsers. If this is an intentional usage of modern JS, I would have expected it to be documented here: https://legacy.reactjs.org/docs/javascript-environment-requirements.html

**Comment by sophiebits** [comment]
react-error-boundary isn't maintained by the React team; you might file an issue on that project but likely better to update syntax support on your end or require a newer browser.
