### ISSUE TITLE
Support for custom DOM elements & attributes

### ISSUE THREAD

**Issue by Gozala** [facebook/react#2746]
Is there reason why React restricts you to just a subset of DOM elements and attributes ? Unfortunately it makes it really hard to use it with new HTML or non standard features unless support for that is added.

I noticed I could create custom elements via `React.createFactory("custom")`

https://github.com/facebook/react/blob/master/src/browser/ReactDOM.js#L30
https://github.com/facebook/react/blob/master/src/classic/element/ReactElement.js#L201-L209

But it's not documented & not sure if supported in long term. And even if it was supported that still does not solve problem of attributes as ones not listed in the docs seem to be ignored.

I think it would be good idea to allow defining custom virtual DOM Elements with a custom list of attributes so that users could implement them even if support for new element isn't in the core yet.

Finally support for namespaces would be super useful for using react even in more environments & should not be too hard either. I have successfully used [vtree](https://github.com/Matt-Esch/vtree) / [vdom](https://github.com/Matt-Esch/vdom) to do that.

**Comment by glenjamin** [comment]
>The 2nd is deciding how we write them in JSX. JSX doesn't support namespace:attribute={value}. Even if it did, what does that transform to? It can't be {namespace: { attribute: value }}.

Is there a reason that `<a ns:attr="1">` can't transform into `React.createElement("a", {"ns:attr": "1"})`?

**Comment by vegetableman** [comment]
AFAIK, only namespaced attributes need support. The above approach makes sense. What do you think @zpao?

**Comment by pekeler** [comment]
I'm confused. Isn't this supposed to be working since 0.12? The release notes state "lower case tag names are always treated as HTML tags, upper case tag names are always treated as composite components". Yet when I try to render `<myCustomHtmlElement/>` I'm getting `Lower case component names (myCustomHtmlElement) are no longer supported in JSX: See http://fb.me/react-jsx-lower-case`. That linked Gist also gives me the impression that it should work.

**Comment by andrewrota** [comment]
@pekeler that should be fixed with #2830

**Comment by pekeler** [comment]
Great. Thanks @andrewrota

**Comment by gnestor** [comment]
@andrewrota Can we use custom elements/web components in React 0.12.2? I tried and I'm getting the above error. I created a StackOverflow thread: http://stackoverflow.com/questions/28751629/react-0-12-2-error-lower-case-component-names-paper-button-are-no-longer-su

**Comment by andrewrota** [comment]
@gnestor, no, you'd need 0.13.0-alpha or greater I believe.

**Comment by gnestor** [comment]
@andrewrota Ok thanks.

**Comment by arendjr** [comment]
I just upgraded to React 0.14.2 and noticed that I can add arbitrary attributes to custom elements now (this didn't work with 0.13). I'm guessing this can be closed now?

**Comment by gaearon** [comment]
When you use web components with React, you can pass any attributes.
