### ISSUE TITLE
Bug: node cached in the InternalNode,it's cause a huage memory leak

### ISSUE THREAD

**Issue by nmnmtttt** [facebook/react#27476]
React version: 16.14.0

## Steps To Reproduce

1. create a dom and append a table Component
2. change state to unmount this  table Component 

Link to code example:

## The current behavior

the node can be found in memory，and it can't be release。
![image](https://github.com/facebook/react/assets/34001432/7958d4fd-a006-4eda-8910-eef5ec842ff2)
![image](https://github.com/facebook/react/assets/34001432/6ff5b8ef-9ee9-4041-8bd6-73f1a6f562e3)

## The expected behavior
the node can be realease

**Comment by sophiebits** [comment]
Closing per @markerikson (thanks!) but we can reopen if it's still an issue.
