### ISSUE TITLE
Bug: On mobile devices, clicking a checkbox in a list of checkboxes will sometimes toggle the wrong one.

### ISSUE THREAD

**Issue by djizco** [facebook/react#27475]
When rendering a list of checkboxes, clicking checkboxes in sequence will sometimes trigger the wrong checkbox to be toggled. Behavior seems to be that sometimes previously clicked checkbox gets toggled instead of currently clicked checkbox.

* This issue only seems to be on mobile or possibly touch devices. Could possibly be an issue with touch event listener.
* This issue seems to have been introduced in React 17.0.0 as version 16.14.0 seems to work correctly.

Specs:
React version: >=17.0.0 (18.2.0)
device: iPhone 8 plus
browser: Chrome version 117.0.5938.117

## Steps To Reproduce

1. View app on a mobile device (I'm using iPhone 8 plus with Chrome)
2. Click multiple checkboxes in sequence
3. Expect that correct checkbox always gets toggled, however sometimes previous checkbox gets toggled.

Link to code example:

Sandbox with working behavior (React 16.14.0)
https://codesandbox.io/s/react-16-checkboxes-xzzl96
https://xzzl96.csb.app/

Sandbox with broken behavior (React 18.2.0)
https://codesandbox.io/s/react-18-checkboxes-zrhpfp
https://zrhpfp.csb.app/

## The current behavior
When clicking multiple checkboxes in sequence, sometimes the wrong checkboxes gets toggled.

## The expected behavior
The correct checkbox should be toggled when clicked.

**Comment by sambehrens** [comment]
I have run into this issue. Can this be reopened? The examples that were posted demonstrate exactly what I am experiencing.

**Comment by djizco** [comment]
Ticket reopened: https://github.com/facebook/react/issues/27475
