### ISSUE TITLE
Bug: Palestine should be free

### ISSUE THREAD

**Issue by xinggangling** [facebook/react#27487]
支持巴勒斯坦🇵🇸，美国还支持以色列，看看巴勒斯坦都快从地区上消失了，官网头部改改吧，还支持乌克兰呢，看看巴勒斯坦，看看叙利亚，美国把中东搞成什么样了

React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by fatih-wecode** [comment]
+1 FREE PALESTINE

**Comment by targumon** [comment]
Yes, Palestine should be free. FROM HAMAS.
But good to know you support terrorists!

**Comment by xinggangling** [comment]
> Yes, Palestine should be free. FROM HAMAS. But good to know you support terrorists!

you know the egg.You are the frog in the well.

**Comment by fatihtkale** [comment]
Typical zionist answer 😂 Israel is the real terrorist's hahahah #FreePalestine 🇵🇸

**Comment by xinggangling** [comment]
> Yes, Palestine should be free. FROM HAMAS. But good to know you support terrorists!

![Uploading 43a7d933c895d143efe72e7fb1c46a0e5baf079e@f_auto.jpeg…]()

**Comment by quki3** [comment]
A litle of documentation https://en.wikipedia.org/wiki/History_of_the_Israeli%E2%80%93Palestinian_conflict

**Comment by xinggangling** [comment]
> Yes, Palestine should be free. FROM HAMAS. But good to know you support terrorists! 

Not only do I support Palestine, all Chinese people support Palestine, and the righteous people of the world support Palestine @targumon

**Comment by targumon** [comment]
Hamas = ISIS. Again, good to know you support kidnappers of children and elders.

And thank you for using React by Meta - a company with hundreds of employees in Israel.

**Comment by fatihtkale** [comment]
Comparing Hamas to ISIS is the craziest thing I have seen, you must be filled with propaganda, hahaha.
Maybe you should read a little instead of being brainwashed, but you can't help it with your brain size.

But yes, thank you for using react by meta, also a company with a lot of Palestinians workers

**Comment by targumon** [comment]
@acdlite does this PR (and behavior of participants) meet the [COC](https://github.com/facebook/react/blob/main/CODE_OF_CONDUCT.md)?

**Comment by fatihtkale** [comment]
Hahahah little Zionist couldn't answer, if you read it you broke every single one too, what a delusional fool.

**Comment by yuchen6031** [comment]
Help Provide Humanitarian Aid to Palestine!

**Comment by xinggangling** [comment]
> Palestine accepted Jewish refugees and then established a state out of a mythical enclosure, driving away the people who originally lived in this land. This is also the reason why some countries will never accept refugees, including the United States

Many years ago, there were many vague boundaries between the land and territories allocated to the Jewish people, which led to many conflicts. After all, the Jewish people in the Middle East were foreign, so they were collectively opposed by neighboring countries. European and American countries helped the Jewish people establish their own country and provided them with advanced weapons. With this help, the United States made war profits, Israel became a hegemon in the Middle East, and the locals became losers, including Palestine and Syria in the Middle East, The Iraqi people are the ultimate victims. The United States played the role of manipulator. The historical reasons are very complex. To ensure peace in the Middle East, it can only be resolved through talks. With the help of the United States, Israel has a huge advantage, but it cannot use this advantage to encroach on the territory of other countries, oppress the people of neighboring countries, cut off electricity, or cut off water! The best solution now is to return to the negotiation table. Both civilians are ordinary people, and the victims are ordinary people. When will the retribution of injustice come. American politicians are such a dog, they only solve problems through aircraft carriers in order to make war money. Biden died early.
