### ISSUE TITLE
[tests] make consistent use of spys or mocks

### ISSUE THREAD

**Issue by zpao** [facebook/react#2749]
We do both, sometimes within the same test file. There's probably 3rd pattern too. This is annoying and ugly. We should do better.

I think we should probably make use of `spyOn` - it feels a bit easier to work with.

**Comment by sobering** [comment]
Hey @zpao. I'm a newbie here, but happy to help! If you'd be willing to provide me with a bit of direction, I'd be more than willing to improve consistency in the tests.

**Comment by zpao** [comment]
Awesome! :) Sorry for the delay in getting back to you though.

What brought this on was actually related to `console.warn` and our testing for warning messages. There are a bunch of places where we set `console.warn = some mock fn`, use it and assert on calls, wrap everything in a try/finally, and then reset console.warn to the original.

Jasmine has all of this built in with `spyOn`, which we use in a bunch of other places to do the same thing but in a less crazy way.

There may be some other patterns like this but the console.warn one was what I was thinking of when I filed it.

**Comment by kevinold** [comment]
@sobering you going to take this one or could I?

**Comment by sobering** [comment]
@kevinold Feel free to take it, you've already done more than I :)

**Comment by Pouja** [comment]
(again I was looking through issues which I can contribute to) 
But it seems that this one is already fixed??

**Comment by zpao** [comment]
Yea, let's call this fixed. There were a couple passes done to clean this up.
