### ISSUE TITLE
Bug: onClick doesn't work on any element inside disabled fieldset in Firefox

### ISSUE THREAD

**Issue by dleavitt** [facebook/react#27501]
React version: 18.2.0
Firefox version: Firefox 118.0.2

## Steps To Reproduce

1. Firefox 118 (as well as older versions) and React 18
2. Within React
3. Inside a `fieldset` with `disabled={true}`
4. Add an `a` tag, `span` tag, or presumably any other tag.
5. Add an `onClick` (or `onMouseDown`, `onMouseUp`) handler to the `a` tag.
6. Click the `a` tag

Link to code example:

https://codepen.io/pygmael/pen/KKbEPqb?editors=1010

## The current behavior
The `onClick` handler is not run.

## The expected behavior
The `onClick` handler gets run.

### In React:
- Same issue occurs with other "clicky" events: `onMouseDown`, `onMouseUp`
- Does not happen with `onMouseOver`, etc.
- Does not happen if you add the handler directly to the element via `addEventListener`
- Chrome does not exhibit this issue.

### Outside React:
- Issue does not occur with `onclick` or `addEventListener`
- Issue **does** occur when "delegating" the handler by adding it to document and filtering based on the selector. This is presumably what ReactDOM is doing.

This is arguably a Firefox bug (click events on non-form elements within a disabled fieldset don't make it out of the fieldset.) Ideally though, React's `onClick` behavior would match `onclick` or `addEventListener` in the browsers it supports, rather than making the user understand React's implementation (which I don't think is documented.)

There are a couple of related bugzilla issues ([1][bugzilla1], [2][bugzilla2]), though neither appears to quite hit the nail on the head.

[bugzilla1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1200127
[bugzilla2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1637321

**Comment by dleavitt** [comment]
Looks like there may be a merged (but not shipped?) fix for this in FF: https://bugzilla.mozilla.org/show_bug.cgi?id=1829874

**Comment by Yashshiva75** [comment]
Solve the issue

**Comment by sophiebits** [comment]
React is moving in the direction of doing less event normalization and having little-to-no layer over browser events so I don't think we'll fix this; the better route would be to work to get the Firefox bug fixed. That issue is tagged as [fixed in 116](https://bugzilla.mozilla.org/show_bug.cgi?id=1829874#c18) so strange you're seeing it in 118. 

https://webcompat.com is also a place where you can file bugs where APIs work in different browsers; it's possible that would help get this fixed.
