### ISSUE TITLE
Bug: Hydration fails with statically rendered html when wrapping component in <Suspense>

### ISSUE THREAD

**Issue by maxbaun** [facebook/react#27503]
React version: 18.2.0

## Steps To Reproduce

1. Create an index.html with a basic div & inner html
2. Create a component that renders the same div & html
3. Call hydrateRoot on the root div in the html... everything works fine
4. Wrap the component in <Suspense>
5. Hydration fails

Link to code example: https://codesandbox.io/s/gallant-beaver-y6n8wz?file=/src/index.html

## The current behavior
Hydration fails unexpectedly

## The expected behavior
Should hydrate the dom without failing or be more specific with why exactly hydration fails

**Comment by sophiebits** [comment]
React server rendering outputs certain markers in the stream as HTML comments and similar that are necessary for the hydration process, so it doesn't work to handcraft HTML and expect it to match up.

Instead, you can use functions from react-dom/server to render components to a string:

https://react.dev/reference/react-dom/server

Depending on your use case you can stream HTML as it's generated (so users see loading indicators that get replaced by content even before the client JS bundle loads) or wait for all Suspense boundaries to resolve if you're doing it at build time (eg https://react.dev/reference/react-dom/server/renderToReadableStream#waiting-for-all-content-to-load-for-crawlers-and-static-generation).

Hope this helps!
