### ISSUE TITLE
Bug: Component suspended by `use` fails to react when suspension depends on external store

### ISSUE THREAD

**Issue by zroug** [facebook/react#27519]
React version: [18.3.0-canary-09fbee89d-20231013](https://www.npmjs.com/package/react/v/18.3.0-canary-09fbee89d-20231013)

## Steps To Reproduce

1. Create a component that uses `useSyncExternalStore`.
2. Since _"`use` can be called within loops and conditional statements"_, do just that and call it conditionally based on the value of the external store.
3. Update the value of the external store.

Essentially the component should look something like this:

```typescript
const val = useSyncExternalStore(...);
if (val === ...) {
    return React.use(...);
} else {
    return <>...</>;
}
```

Full example link: https://codesandbox.io/s/distracted-sun-6kvvvq

<details><summary>Full example code</summary>
<p>

```typescript
import * as React from "react";

export function App() {
    return (
        <div>
            <CountDisplay />
            <React.Suspense fallback={<p>Actual: Is suspended.</p>}>
                <SuspendingComponent />
            </React.Suspense>
        </div>
    );
}

function CountDisplay() {
    const count = useCount();
    return (
        <>
            <p>Count: {count}</p>
            <p>Expected: {count < 5 ? "Is suspended." : "Is loaded."}</p>
        </>
    );
}

const neverPromise = new Promise<never>(() => {});
function SuspendingComponent() {
    const count = useCount();
    if (count < 5) {
        return React.use(neverPromise);
    } else {
        return <p>Actual: Is loaded.</p>;
    }
}

let count = 0;
const countChangeHandlers = new Set<() => void>();
setInterval(() => {
    count += 1;
    for (const handler of countChangeHandlers) {
        queueMicrotask(handler);
    }
}, 1000);
function useCount() {
    return React.useSyncExternalStore(
        (onChange) => {
            countChangeHandlers.add(onChange);
            return () => countChangeHandlers.delete(onChange);
        },
        () => count,
    );
}
```

</p>
</details>

## The current behavior

The component in question (`SuspendingComponent`) remains suspended even after `React.use` is no longer called (count reaches five).

## The expected behavior

According to the documentation _"Unlike all other React Hooks, `use` can be called within loops and conditional statements like if."_. Therefore, the current behavior is surprising and can lead to subtle bugs. When the value of an external store changes, React should check if it still needs to wait for the Promise. It already does this for the component props.

**Comment by sophiebits** [comment]
This is a limitation of useSyncExternalStore that was recently documented on the reference page:

https://react.dev/reference/react/useSyncExternalStore#caveats

Unfortunately this is a core limitation to how the Hook works. All React updates caused by useSyncExternalStore are synchronous (hence the name) and therefore can't suspend. This is so that everything on screen is consistent, including if non-React code is rendering UI from the same store.
