### ISSUE TITLE
Bug: Error Boundary not updating and not calling componentDidCatch despite catching error

### ISSUE THREAD

**Issue by gmaxlev** [facebook/react#27510]
React version: 18.2.0

(React 17.0.2 doesn't have this problem)

## Steps To Reproduce

1. Develop a component that throws an error during rendering, **but only once**.
2. Implement an Error Boundary component with a `getDerivedStateFromError` static method, which updates its state to indicate the presence of an error.
3. Enhance the Error Boundary's render method with conditional logic to display an error message when an error is captured.
4. Wrap the component within the Error Boundary.

Link to code example: https://codesandbox.io/s/react-18-error-boundary-wrkgry

## The current behavior

If a component has code that throws an error **only once** during all the renders, then the Error Boundary will call the static method `getDerivedStateFromError`, update its state, and invoke its render method.

The Error Boundary component will be in a state where it should display an error message instead of `children`. However, React does not update it, despite the state being changed and `render` method being called. Additionally, the `componentDidCatch` method is not called, even though `getDerivedStateFromError` is invoked.

The component that threw the error will **still be displayed.**

**However, I expect React to update the Error Boundary immediately after the first error**

I believe that this contradicts the concept outlined in [the old React documentation](https://legacy.reactjs.org/docs/error-boundaries.html#new-behavior-for-uncaught-errors):

> We debated this decision, but in our experience it is worse to leave corrupted UI in place than to completely remove it.

## The expected behavior

Just as in React 17.0.2, I expect that immediately after the first error thrown in the component, React will not only call the `getDerivedStateFromError` method in the nearest Error Boundary, update its state, and invoke the `render` method, but it will also call the `componentDidCatch` method and apply changes to the screen according to its state: hiding `children` and displaying an error message. 

Otherwise, if React deems that a component, which threw an error  is still displayable on the screen, then why isn't `componentDidCatch` called at the very least? I expect to report the error to my reporting service, but I'm unable to do so in React 18.2.0

**Comment by sophiebits** [comment]
Hmm. What you've noticed is a bit odd, but in general components are meant to be deterministic based on their inputs (props, state, context) so the case of throwing an error only on the 4th render is not entirely supported. I believe it's intended that we recover gracefully in some cases – eg I think we may retry a render synchronously if it errors the first time and use that output if it succeeds.

What's the real world use case for why this throws only sometimes?

**Comment by gmaxlev** [comment]
Thanks for your reply!

The fact is that we are migrating a project from version 17 to version 18 of React and accidentally discovered this new behavior for us.

In fact, our component did not integrate correctly with a third-party service, accessing its properties directly from the component function, instead of hooks. After throwing an error, the third-party service reset its state and did not throw an error the next time. Of course, this is an incorrect use of React and we solved this problem by using `useEffect` hooks.

However, despite this, it was the difference in behavior between versions 17 and 18 that confused us. Your answer convinced us that this is expected behavior in the latest version of React and not a bug.

But it's a pity that in this case there is no way to use `componentDidCatch` to report an error in the reporting service, even despite the incorrect use of React.

**Comment by Johnrobmiller** [comment]
This replicated for me also
