### ISSUE TITLE
Bug: Curly Brace Symbol Doesn't Show (change open attribute value) 

### ISSUE THREAD

**Issue by saraOrkide** [facebook/react#27520]
I want to parse the mml, but when it comes to the mfenced tag, the value of the open attribute changes from "}" to "true".
I used the latest version and set sanitize for it, but it didn't work
My problem is that I want to replace a tag, so I wanted to use html-react-parser
see https://codesandbox.io/s/laughing-dhawan-sq5p28?file=/src/index.js
open prop being converted to a boolean value:

![s](https://github.com/facebook/react/assets/10929451/46c02f98-04da-4a25-89db-b9d89d179231)

**Comment by sophiebits** [comment]
html-react-parser isn't made by the React team; you'd have to file an issue with that project.
