### ISSUE TITLE
Bug: react-hooks/exhaustive-deps reports a dependency if `typeof` TypeScript operator is used in a function.

### ISSUE THREAD

**Issue by Thaigun** [facebook/react#27548]
These issues linked below are closely related, but I believe the problem was only fixed if you use `typeof` TypeScript operator inside the `useEffect` callback.
https://github.com/facebook/react/issues/19327
https://github.com/facebook/react/issues/18828

However, if you call a function from the `useEffect` callback and that function uses `typeof` in a type context, exhaustive-deps reports a problem.

React version: 18.2.0
"eslint-plugin-react-hooks": "^4.6.0"

## Steps To Reproduce

1. Set up a project with eslint, eslint-plugin-react-hooks installed.
2. In a useEffect, call a function that uses `typeof` to define the type of a parameter.
3. Run lint with exhaustive-deps rule on.

Link to code example:
I hope this sample is enough, let me know if it would be useful to have a whole cloneable repository for reproduction.
```
export default function App() {
    const myNumber = Math.floor(Math.random() * 1000);

    function printNumber(n: typeof myNumber) {
        console.log(n);
    }

    useEffect(() => {
        const foo = 3;
        printNumber(foo);
    }, []);

    return <h1>Your random render number: {myNumber}</h1>;
}
```

## The current behavior
The above code reports the following problem.
```
React Hook useEffect has a missing dependency: 'printNumber'. Either include it or remove the dependency array  
react-hooks/exhaustive-deps
```

## The expected behavior
`typeof` operator in the type context does not affect the compiled JavaScript and should not be reported by `exhaustive-deps`.

For reference, the following does not report an error even though it's functionally the exact same as the code example above:
```
export default function App() {
    const myNumber = Math.floor(Math.random() * 1000);

    function printNumber(n: number) {
        console.log(n);
    }

    useEffect(() => {
        const foo = 3;
        printNumber(foo);
    }, []);

    return <h1>Your random render number: {myNumber}</h1>;
}
```

**Comment by Thaigun** [comment]
Also related: https://github.com/facebook/react/issues/27335

**Comment by khoabt1908** [comment]
❤️

**Comment by WizardRRR** [comment]
hola
