### ISSUE TITLE
Bug: Constraining children to type has no effect

### ISSUE THREAD

**Issue by speculees** [facebook/react#27545]
I need to set a constraint on parent component, so only children of certain type are allowed. Maybe this is intended behavior, but if so how do you set constraint?

React version:  18.2.0

## Steps To Reproduce

1. Create a component with children property and use generic type React.ReactElement<P> to constrain what children are allowed to be passed
2. Observe that you can still add any child as if React.ReactElement is used

Link to code example: https://codesandbox.io/s/react-typescript-forked-wzkkvl?file=/src/App.tsx

## The current behavior
Allows the children of parent to be of any type

## The expected behavior
Parent component should be marked with error "Types of property 'children' are incompatible." if other component is passed as child

**Comment by sophiebits** [comment]
@eps1lon Remind me if this is a limitation of core TypeScript?

**Comment by Youngemmy5956** [comment]
Check the pull request i sent

**Comment by speculees** [comment]
> import React, { ReactElement, ReactNode } from "react";
> 
> type ValidChild = ReactElement<{ customProp: string }>;
> 
> type ParentProps = { children: ValidChild | ValidChild[]; };
> 
> const Parent: React.FC = ({ children }) => { if (!Array.isArray(children)) { children = [children]; }
> 
> const invalidChildren = children.filter( (child) => child.type !== ChildComponent );
> 
> if (invalidChildren.length > 0) { throw new Error("Invalid child components in Parent"); }
> 
> return
> 
> {children}
> ;
> };
> type ChildProps = { customProp: string; };
> 
> const ChildComponent: React.FC = ({ customProp }) => { return
> 
> {customProp}
> ;
> };
> export default function App() { return (
> 
> Parent should complain
> 
> 
> 
> );
> }

I was thinking about this approach, but this is would loop (filter) children in runtime instead of using typescript.

**Comment by Youngemmy5956** [comment]
What about using this approach ??


import React, { ReactElement, ReactNode } from "react";

type ChildProps = {
  customProp: string;
};

type ChildComponentProps = {
  children: ReactNode;
  customProp: string;
};

const ChildComponent: React.FC<ChildProps> = ({ customProp }) => {
  return <div>{customProp}</div>;
};

const Parent: React.FC<ChildComponentProps> = ({ children, customProp }) => {
  return (
    <div>
      <div>{customProp}</div>
      {children}
    </div>
  );
};

export default function App() {
  return (
    <Parent customProp="Parent Custom Prop">
      <ChildComponent customProp="Child 1 Custom Prop" />
      <ChildComponent customProp="Child 2 Custom Prop" />
    </Parent>
  );
}

**Comment by eps1lon** [comment]
It's a TypeScript limitation because `< ValidChild />` will be any JSX element i.e. `(< ValidChild />).type` `any` not `ValidChild`. It would only work if you'd use a JSX factory directly i.e. `createElement(ValidChild)`. In that case, TypeScript would recognize the real element type (`createElement(ValidChild).type` is `ValidChild`) and your parent could safely assume `children: ValidChild` is enforced at the type level.

But this shifts the burden to component consumers which defeats the purpose.

Closing in favor of https://github.com/microsoft/TypeScript/issues/14729
