### ISSUE TITLE
Bug: Nested forms created by createPortal submit the outer form.

### ISSUE THREAD

**Issue by TigWork** [facebook/react#27555]
When we use react's createPortal, it is supposed to create the element inside the specified element. It works that way, but onSubmit on forms works based on a hierarchy of React components. If we have a parent form and inside it, a Modal renders the form with createPortal connected to `document.body`,  when we fire submit, it also fires the submit of the parent form, which shouldn't be fired.
React version:

## Steps To Reproduce

1. Create a form
2. Create a new form that is nested inside that form, but is created via `createPortal`
3.  Try to submit inside the nested form

Link to code example:
https://codesandbox.io/s/sweet-tree-tzx53l?file=/src/App.js

## The current behavior
The parent form onSubmit fires.

## The expected behavior
It shouldn't fire.

**Comment by MarceloSpessoto** [comment]
Hi @TigWork ,
I think this problem is not related to createPortal, but with [Event Bubbling/Propagation](https://react.dev/learn/responding-to-events#event-propagation). When an event is triggered in a component, it also propagates up in the tree, being triggered in its parent. You should use stopPropagation method in the child component to avoid this behavior.
Try doing the following:

```js
import { createPortal } from "react-dom";
import "./styles.css";

function B() {
  function nestedFormSubmit(e) {
    e.preventDefault();
    e.stopPropagation(); // Add this to the code!
    console.log("Nested Submit (B)");
  }

  return createPortal(
    <form onSubmit={nestedFormSubmit}>
      <button>Nested Submit</button>
    </form>,
    document.body
  );
}

export default function App() {
  function handleSubmit(e) {
    e.preventDefault();
    console.log("Parent Submit (A)");
  }

  return (
    <div className="App">
      <form onSubmit={handleSubmit}>
        <B />
        <button type="submit">Submit</button>
      </form>
    </div>
  );
}
```

**Comment by TigWork** [comment]
I know the solution, but it is an alternative way to solve that. My form is created inside the body, and the button was inside that form. But when I click on the button, it triggers submit on the form created inside the body, and the form created inside #root, which shouldn't happen.

**Comment by MarceloSpessoto** [comment]
Ok.
After reading the [createPortal documentation](https://react.dev/reference/react-dom/createPortal), I saw this is a reported caveat. It is also told that `A portal only changes the physical placement of the DOM node. In every other way, the JSX you render into a portal acts as a child node of the React component that renders it. For example, the child can access the context provided by the parent tree, and events bubble up from children to parents according to the React tree.`
Changing the behavior you reported would require to change how createPortal method works, and it would be better if a maintainer of React indicated which path to follow.

**Comment by sophiebits** [comment]
Thanks @MarceloSpessoto, your explanation is right – React events bubble through portals. This is by design but if you want to opt out of it you can call event.stopPropagation() in an onSubmit handler on some component in between.

**Comment by sophiebits** [comment]
You can also compare `event.target === event.currentTarget` on the outer form's event handler.
