### ISSUE TITLE
Bug: forwardRef ignore Type Check

### ISSUE THREAD

**Issue by HotariTobu** [facebook/react#27558]
React version: 18.2.0
TypeScript version: 5.2.2

## Steps To Reproduce

1. Define a component with `forwardRef`
2. Do not give type annotation to parameter `ref`
3. Use `useImperativeHandle`
4. Use the component and pass a ref object
5. Access the ref object's properties that are not exposed in `useImperativeHandle`

The reproducible code forked from [here](https://react.dev/learn/manipulating-the-dom-with-refs#exposing-a-subset-of-the-api-with-an-imperative-handle):
```typescript
'use client'

import { forwardRef, useImperativeHandle, useRef } from "react";

const Child = forwardRef((props, ref) => {
  const realInputRef = useRef<HTMLInputElement>(null)

  useImperativeHandle(ref, () => ({
    // focus() {
    //   realInputRef.current?.focus()
    // },
  }))

  return <input {...props} ref={realInputRef} />
})

const Parent = () => {
  const inputRef = useRef<HTMLInputElement>(null)

  function handleClick() {
    inputRef.current?.focus()
  }

  return (
    <div>
      <Child ref={inputRef} />
      <button onClick={handleClick}>Focus the input</button>
    </div>
  )
}
Child.displayName = 'Child'

export default Parent
```

Link to code example:

https://codesandbox.io/p/sandbox/sweet-cloud-hn34vp

## The current behavior

`forwardRef` with `ForwardedRef<unknown>` does not cause any type error.
Then an error occurs like below on run-time.

```
TypeError: _inputRef_current.focus is not a function
```

## The expected behavior

`forwardRef` components should cause an error when wrong type ref objects are passed through the parameter `ref`.
It is so that we notice a mistake before run-time.

**Comment by sophiebits** [comment]
cc @eps1lon – I guess the inferred type parameter here ends up as `unknown`? which I think seems fine but then it seems you shouldn't be able to pass a ref of `React.RefObject<HTMLInputElement>` to `React.ForwardRefExoticComponent<React.RefAttributes<unknown>>`

**Comment by eps1lon** [comment]
The main problem here is that you can pass `Ref<HTMLInputElement>` to a component that accepts `Ref<unknown>`. You expect to read `HTMLInputElement` yet the component may write an `unknown` instance into the ref. This is essentially the same issue as https://github.com/microsoft/TypeScript/issues/30748 i.e. it's a design limitation of TypeScript.

We may be able to fix this at the type level by defaulting the instance type to `never` instead. Needs to tested in the types though by filing a PR changing https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a449dbfd6f1286eb52cfa4d1c2346771947342c2/types/react/index.d.ts#L1561 to `T` defaulting to `never` (`function forwardRef<T = never, P = {}>(`) and then checking if CI passes.
