### ISSUE TITLE
Doc: translate to portuguese

### ISSUE THREAD

**Issue by tbathat** [facebook/react#27557]
I am a native portuguese speaker and it is my wish to make React content available to portuguese speakers by translating it myself.

**Comment by pwbriggs** [comment]
That's great, @tbathat, glad you want to help out!

The React translation status page can be found at https://translations.react.dev. It looks like there is a translation to Brazilian Portuguese already in progress (site at https://pt-br.react.dev/, repo at https://github.com/reactjs/pt-br.react.dev). I don't know Portuguese myself, so I'm not sure if Brazilian Portuguese is close enough. If not, you can follow the instructions at https://github.com/reactjs/translations.react.dev to start a new translation.
