### ISSUE TITLE
The React Tab Doesn't Show Up unless i check all reasons in https://github.com/facebook/react/tree/main/packages/react-devtools#the-react-tab-doesnt-show-up

### ISSUE THREAD

**Issue by denis-ttk-1975** [facebook/react#27564]
I cant see react tabs in chrome dev panel.
I have checked this problem on https://reactjs.org/ and have got the same result 

My OS:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎25.‎02.‎2023
OS build	22621.2428
Experience	Windows Feature Experience Pack 1000.22674.1000.0

My browser version is Chrome Version is 118.0.5993.89 (Official Build) (64-bit)

My React Developer Tools extension version is 4.28.4 (10/3/2023)

![React dev tools problem](https://github.com/facebook/react/assets/75208826/a85f4809-98f3-4c44-947f-a59a4b834c4b)

**Comment by Shubhdeep12** [comment]
I think it is better to raise this issue here - https://github.com/reactjs/react.dev/issues

**Comment by denis-ttk-1975** [comment]
Thanks a lot!

**Comment by mxmnk** [comment]
I experience the same issue

**Comment by stuff** [comment]
Does anyone have news about this?
The react dev tools tab also doesn't show up for me anymore, and my own private extension alos doesn't show up, so I'm looking for fixes :)

**Comment by mxmnk** [comment]
> Does anyone have news about this? The react dev tools tab also doesn't show up for me anymore, and my own private extension alos doesn't show up, so I'm looking for fixes :)

I'm using this extension in Firefox until the issue is resolved

**Comment by hoxyq** [comment]
> Does anyone have news about this? The react dev tools tab also doesn't show up for me anymore, and my own private extension alos doesn't show up, so I'm looking for fixes :)

Does changing `Site access` setting to `On all sites` fix the issue for you? Like it is mentioned in the description of this issue.

I guess the point in this issue is that we don't mention this in our troubleshooting docs, which I am planning to update soon.

**Comment by mxmnk** [comment]
> > Does anyone have news about this? The react dev tools tab also doesn't show up for me anymore, and my own private extension alos doesn't show up, so I'm looking for fixes :)
> 
> Does changing `Site access` setting to `On all sites` fix the issue for you? Like it is mentioned in the description of this issue.
> 
> I guess the point in this issue is that we don't mention this in our troubleshooting docs, which I am planning to update soon.

It doesn't work for me. Extension icon shows that the website has react but no tabs in chrome dev tools

**Comment by stuff** [comment]
> > Does anyone have news about this? The react dev tools tab also doesn't show up for me anymore, and my own private extension alos doesn't show up, so I'm looking for fixes :)
> 
> Does changing `Site access` setting to `On all sites` fix the issue for you? Like it is mentioned in the description of this issue.
> 
> I guess the point in this issue is that we don't mention this in our troubleshooting docs, which I am planning to update soon.

I was working fine for years then suddenly disapear, On all sites is my setting yes.

**Comment by hoxyq** [comment]
It seems like an issue with Chrome, because we had similar problems in https://github.com/facebook/react/issues/24094 and https://github.com/facebook/react/issues/19002.

Can someone validate if they have same issues with Edge browser?

**Comment by stuff** [comment]
it kinda works :) (showing up TWICE for unknown reason...)

![image](https://github.com/facebook/react/assets/27239/0559dbef-4137-40dd-a078-61840c1741cd)

**Comment by hoxyq** [comment]
Can someone please check if restoring defaults for Chrome DevTools solves the problem? 
![image](https://github.com/facebook/react/assets/28902667/941e6f77-52d9-4bf1-af9b-3b1681de7cb1)

I had someone reporting that it has actually fixed missing React DevTools panels in Chrome.

**Comment by stuff** [comment]
I just tried, and it worked!

**Comment by joshsmith01** [comment]
I tried the reset option that @hoxyq suggested. It worked for me, too. It was sort of a bummer to reestablish all my configurations, but such is life.

**Comment by gregfenton** [comment]
I tried several other approaches (restarting Chrome, uninstalling/shutdown/install/shutdown, etc.) but nothing worked until I did this "reset".

I do not run with many extensions.  Less than 10, and nothing "crazy".

I'm runnning Chrome on MacOS/Intel, Sonoma v14.1

**Comment by InOmniaParatus-WD** [comment]
Oh, finally the light at the end of the tunnel. Thanks @hoxyq. Been busting my brain for weeks to fix this. It worked with the reset to defaults.

**Comment by guanyu-y** [comment]
> Can someone please check if restoring defaults for Chrome DevTools solves the problem?
Thanks!  it worked for me too!
However, I would like to know what setting was causing this issue... ;(

**Comment by ipahe1** [comment]
It worked for me, thanks
