### ISSUE TITLE
Warn if rendering an HTML tag spelled with uppercase letters

### ISSUE THREAD

**Issue by bmcmahen** [facebook/react#2756]
If I try running the following code:

```javascript
var Hello = React.createClass({
    render: function() {
      return React.createElement('BR', null);
    }
});
 
React.render(<Hello/>, document.body);
```

I get two `<br>` tags inserted into the dom, instead of one. I made a quick jsfiddle to show this. http://jsfiddle.net/kb3gN/8662/

I'm running Chrome, if that's at all relevant.

**Comment by syranide** [comment]
@spicyj Sticking to case-sensitive makes most sense to me, especially as some SVG-tags actually have casing.

**Comment by jisaacks** [comment]
@spicyj I would love to tackle this, but jumping in I am a little lost in the huge codebase. I found `ReactDom` which seems to be the place that defines all the built in DOM nodes. But I am unsure where the proper place to warn would be. I am also unsure where the proper place to put the test would be (ReactDom-test, ReactElement-test, ReactElementValidator-test, ReactJSXElement-test, etc.)

**Comment by spicyj** [comment]
Probably the same place where we check for dangerous tag names (https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDOMComponent.js#L287) would be a reasonable place – you can rename that function and add a `__DEV__`-only warning for this there. ReactDOMComponent-test is probably a reasonable place for a test but if you find somewhere else, that's probably fine too.
