### ISSUE TITLE
Bug: React.memo fails to memoize component

### ISSUE THREAD

**Issue by TNSaturday** [facebook/react#27574]
I have two components, one receiving another one as a prop. For clarity I will remove all the unnecessary logic and JSX:

```tsx
function Child() {
  useEffect(() => {
    console.log("Child rerender");
  });
  return <div>Child component</div>;
}

function Parent({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    console.log("Parent rerender");
  });
  return (
    <div>
      Parent component
      {children}
    </div>
  );
}
```

They're both memoized as follows:

```tsx
const ChildMemo = React.memo(Child);
const ParentMemo = React.memo(Parent);
```

Now, they're both being rendered in the top level component with a state, again for clarity's sake let's imagine for now it's just a button setting some state:

```tsx
function App() {
  useEffect(() => {
    console.log("App rerender");
  });
  const [count, setCount] = useState(0);

  return (
    <>
      <button onClick={() => setCount(count + 1)}>Update state {count}</button>
      <ParentMemo>
        <ChildMemo />
      </ParentMemo>
    </>
  );
};
```

React version: 18.2.0

## Steps To Reproduce

1. Follow the codesandbox link down below to get directly to the problem's example.
2. Click increment button.
3. Look at the console.

Link to code example:

https://codesandbox.io/s/morning-cdn-srxdpg?file=/src/App.tsx

## The current behavior

Clicking "update state" button makes both `<App />` and `<ParentMemo />` get rerendered.

## The expected behavior

I expect only the `<App />` component to rerender, since `<ParentMemo />` is memoized having no dependency other than `<ChildMemo />`, which is also memoized.

**Comment by MrWangJustToDo** [comment]
because `<ParentMemo />` have a `children` props, which will create by <App /> when every rerender (<ChildMemo /> === jsx(ChildMemo), and this will return a new object when invoke), try to change you code to:
```tsx
const ele =  <ChildMemo />;

function App() {
  useEffect(() => {
    console.log("App rerender");
  });
  const [count, setCount] = useState(0);

  return (
    <>
      <button onClick={() => setCount(count + 1)}>Update state {count}</button>
      <ParentMemo>
         {ele}
      </ParentMemo>
    </>
  );
};
```
now the children props for `<ParentMemo />` will never change, and `<ParentMemo />` component also will not update by now
