### ISSUE TITLE
Bug: Nested components imported with React.lazy cause rerendering

### ISSUE THREAD

**Issue by troovi** [facebook/react#27573]
if we nest a component imported with React.lazy inside component that is also imported using React.lazy, we will get a re-render of that chain's child. I don't think this behavior is normal

React version: 18.2.0

## Steps To Reproduce:

1) Create some component "A"
2) Import component "A" into component "B" via React.lazy and wrap it in Suspense
3) Import component "B" into Component "C" via React.lazy and wrap it in Suspense
4) Import component "C" into root component (App)

result:

<img width="228" alt="Снимок экрана 2023-10-24 в 20 17 27" src="https://github.com/facebook/react/assets/95082945/b71bd9ac-e633-4400-8bef-3fd428844c18">

<br>
<br>
<br>
Codesandbox link:
<br>

[https://codesandbox.io/s/react-lazy-rerender-bug-h8ynhr](https://codesandbox.io/s/react-lazy-rerender-bug-h8ynhr)
(check console messages)

**Comment by lkangle** [comment]
I ran into a similar problem and rerendering only occurs in concurrent mode.

I don't know how to handle it, okay

https://codesandbox.io/s/react-lazy-suspense-5g75x3?file=/src/App.js
