### ISSUE TITLE
Bug: 'Warning: validateDOMNesting: <hr> cannot appear as a child of <select>' – but this is now valid HTML

### ISSUE THREAD

**Issue by philwolstenholme** [facebook/react#27572]
The latest version of Chrome and Safari support `hr` elements as children of `select` elements, and the HTML spec has been updated – but React warns about this as it used to be invalid HTML.

- https://developer.chrome.com/blog/hr-in-select
- https://webkit.org/blog/14445/webkit-features-in-safari-17-0/#:~:text=Horizontal%20rules%20inside%20select%20elements
- https://html.spec.whatwg.org/#the-select-element-2:~:text=Zero%20or%20more%20option%2C%20optgroup%2C%20hr%2C%20and%20script%2Dsupporting%20elements.
- https://html.spec.whatwg.org/#the-select-element-2:~:text=Occasionally%20it%20can%20be%20useful%20to%20have%20a%20separator%3A

<img width="800" height="811" src="https://wd.imgix.net/image/HodOHWjMnbNw56hvNASHWSgZyAf2/55LrQnjhGNU5h22nq2PK.jpg?auto=format" 
 alt="Screenshot of before and after with hr in select. The after image has dividers between groups.">

React version: `18.2.0`

## Steps To Reproduce

1. Add a `hr` element as a child of `select`

## The current behavior

`Warning: validateDOMNesting: <hr> cannot appear as a child of <select>`

## The expected behavior

No `validateDOMNesting` warning.

**Comment by philwolstenholme** [comment]
Would a fix for this be to add `|| tag === 'hr'` in https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/validateDOMNesting.js#L247?

I can't see a reference to `select` in https://github.com/facebook/react/blob/main/packages/react-dom/src/__tests__/validateDOMNesting-test.js.

**Comment by sophiebits** [comment]
Sure, feel free to send a PR for that and tag me in it.

**Comment by mglavall** [comment]
Hey there!

I'm currently on a previous version of React and can't update just yet. Is there a way to hide this Warning/Validation until I do?

Thanks a lot

**Comment by Flip437** [comment]
> Hey there!
> 
> I'm currently on a previous version of React and can't update just yet. Is there a way to hide this Warning/Validation until I do?
> 
> Thanks a lot

UP plz :)

**Comment by arnaudambro** [comment]
Up !

**Comment by sophiebits** [comment]
This will be in the upcoming 19.0 release (currently available in the canary release channel). No plans to release a new 18.x with this fix, sorry.
