### ISSUE TITLE
[DevTools Bug]: React Dev Tools break gstreamer docs

### ISSUE THREAD

**Issue by vitoyucepi** [facebook/react#27578]
### Website or app

https://gstreamer.freedesktop.org/documentation/gstreamer/gi-index.html

### Repro steps

1. Enable React Dev Tools browser extension for chrome/firefox.
1. Visit https://gstreamer.freedesktop.org/documentation/gstreamer/gi-index.html.
1. Try to scroll left navigation panel.

https://github.com/facebook/react/assets/35035879/542151db-5431-4b4a-a338-f39737b8df4b

### How often does this bug happen?

Every time

**Comment by vitoyucepi** [comment]
I've filled an issue in the GStreamer bug tracker.
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3070

**Comment by hoxyq** [comment]
Can confirm that side navigation doesn't work well with React DevTools installed.

I am not familiar with GStreamer docs and [HotDoc](https://github.com/hotdoc/hotdoc), so I can't really tell what's going on on their side. What can be important here, is that React DevTools extension sends many `'message'` events via `window.postMessage`, trying to poll if React has appeared on the application page.

I found that there is one listener attached to `'message'` event, after removing it via
```
const listeners = getEventListeners(window);
window.removeEventListener('message', listeners.message[0].listener);
```

sidebar works as expected.

So, I don't know where this listener is attached (although its somewhere from jquery), you should your own custom message and validate it once received in listener.
