### ISSUE TITLE
scryRenderedComponentsWithType func not finding child components.

### ISSUE THREAD

**Issue by fourq** [facebook/react#2757]
I am trying to test for the existence of a component within its parent. I'm pretty sure that the function scryRenderedComponentsWithType was created to do this, but isn't working. Take a look at my component and its test here:
https://gist.github.com/fourq/1099c73ea77c1d0a237e#file-header-react-test-js-L41

The line 41 fails with the following: 

## Test Error
```sh
 FAIL  js/components/__tests__/Header.react.test.js (5.021s)
● App › it should have a PageHeader component
  - Expected: 0 toBe: 1
        at Spec.<anonymous> (/Users/rocky/Src/pastoral-acts/js/components/__tests__/Header.react.test.js:41:29)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

easier to read screen shot
http://screencast.com/t/oHZLsF8LqbQb

Here's the React function in question:

## Reference to scryRenderedComponentsWithType()
https://github.com/facebook/react/blob/df81c9916ba61f59688995ef0dedaa2205c11c7f/src/test/ReactTestUtils.js#L212

Thanks

**Comment by spicyj** [comment]
Can you make a minimal repro case, like in a jsfiddle? It's not obvious to me what the issue here is but it's hard for me to set up and run your example so I can't test.
