### ISSUE TITLE
Bug: exhaustive-deps lint should allow omitting unchanging values

### ISSUE THREAD

**Issue by Diggsey** [facebook/react#27589]
The following code is flagged by the exhaustive-deps lint:
```tsx
const doThing = useCallback(() => {
    console.log("Doing the thing");
}, []);

// React Hook useEffect has a missing dependency
useEffect(() => doThing(), []);
```

This is surprising, because the following code is *not* flagged:
```tsx
const doThing = () => {
    console.log("Doing the thing");
};

// No warnings
useEffect(() => doThing(), []);
```

I suggest that the lint special-case values returned from hooks with an empty dependency list, and treat those values as "semantically frozen" for the lifetime of the component, in the same way that it treats eg. the `setState` callback.

**Comment by zhangfugui6** [comment]
在第一个示例中，您使用了 useCallback 来创建一个稳定的回调函数 doThing，并将其作为依赖项传递给 useEffect。然而，由于您在 useCallback 的依赖项列表中没有指定任何依赖项，exhaustive-deps lint 规则会提示您缺少依赖项的警告。

在第二个示例中，您直接声明了一个普通的函数 doThing，它没有依赖项。由于它不是通过 useCallback 创建的回调函数，因此不需要显式指定依赖项，因此不会触发 exhaustive-deps lint 警告。

对于这种情况，您可以选择禁用 exhaustive-deps lint 规则，或者根据您的具体需求，将缺少的依赖项添加到 useCallback 的依赖项列表中。这取决于您对代码的预期行为和依赖项的管理方式。
关于您提到的建议，将具有空依赖列表的钩子视为“语义冻结”，这是一个可行的做法。如果您确定某个钩子的依赖项不会发生变化，并且您希望在组件的整个生命周期内保持固定的行为，您可以将空依赖列表视为一个标识，表示在任何依赖项变化时不重新执行该钩子。
