### ISSUE TITLE
What does the community think of the war between Israel and Palestine? Will it donate to Palestine?

### ISSUE THREAD

**Issue by Im-Kevin** [facebook/react#27604]
What does the community think of the war between Israel and Palestine? Will it donate to Palestine?
Or is this just a political tool?

**Comment by nitesh9720** [comment]
is your question related to react?

**Comment by MrWangJustToDo** [comment]
<img width="1425" alt="image" src="https://github.com/facebook/react/assets/57748455/13c171cf-48bf-46ee-a814-10a6ef1ad601">

**Comment by Im-Kevin** [comment]
Isn’t this a political double standard?

**Comment by sytranvn** [comment]
@Im-Kevin Look up Mark Zuckerberg, you will know why.

**Comment by Im-Kevin** [comment]
Everything serves politics

**Comment by mattcarrollcode** [comment]
Hi all, I've locked this conversation as off topic and will be deleting this shortly.
