### ISSUE TITLE
Feature request to strip data-reactid and return them as an array or string

### ISSUE THREAD

**Issue by EloB** [facebook/react#2761]
Right now `data-reactid` on every element adds up a lot of unnecessary space for server generated pages.

I know that they are still needed to initialize on the browser. My solution minimize the output is that I strip all the `data-reactid` and add them as an array in a `<script>` tag at the end `<body>` tag. See my example below.

**Except from example server script:**

``` js
var html = React.renderToString(React.createElement(element, { some: data }))
  , reacts = []
  , filtered;

html = html.replace(/ data-reactid="([^"]*)"/g, function(full, value) {
    reacts.push(value);
    return '';
});

filtered = html.replace('appReact=[]', 'appReact=' + JSON.stringify(reacts));

res.send('<!doctype html>' + filtered);
```

**Except from example client script**

``` js
var elements = document.getElementsByTagName('*');

// This is fast because it doesn't trigger any reflow.
Array.prototype.slice.call(elements).forEach(function(element, index) {
    element.setAttribute('data-reactid', appReact[index]);
});

React.render(React.createElement(element, { some: data }), document);
```

**Except from example jsx**

``` html
<html>
    <head>
    </head>
    <body>
        <script dangerouslySetInnerHTML={{__html:'var appReact=[];'}}></script>
        <script src="/client.js"></script>
    </body>
</html>
```

I think this solution could be done a lot better/safer if its somehow included in the core.

| HTML tags | Saved characters |
| --- | --- |
| 10 | 120+ |
| 100 | 1 200+ |
| 1 000 | 12 000+ |

_Saved characters is even higher because labels often gets wrapped into `<span>`_

**Comment by syranide** [comment]
#1570 it's easy to reconstruct the IDs during client render, but until React can go all the way (like in the PR), the entire rendered tree would have to be updated with reconstructed `data-reactid` during first client render which may or may not a bit of a perf issue.

**Comment by EloB** [comment]
@syranide Nice! :)

**Comment by gaearon** [comment]
We don't use IDs anymore so this can probably close. https://github.com/facebook/react/pull/10339
The change will be part of React 16.
