### ISSUE TITLE
Bug: React 18 Suspense with unstable value would trigger multiple rerenders

### ISSUE THREAD

**Issue by yaodingyd** [facebook/react#27611]
In react 18 new root, if a component is not stable under `Suspense`, it will keeps being rerendered. This is not the case with old root, and not documented in react docs.

React version: 18

## Steps To Reproduce

a very simple react 18 application that has a `Suspense` and one state update to trigger a rerender. I have added a `console.log` to show when rerender happens.

First, react 18 with `ReactDOM.render` with the old root behavior:
https://codesandbox.io/s/old-root-lazy-component-w7pflf

Now react 18  with `createRoot`, and a stable value created with `useState` for suspended component:
https://codesandbox.io/s/new-root-lazy-component-stable-sm7v2c

Now react 18 with unstable value, notice that we now have over 1k console.log messages, indicating component keeps rerendering

https://codesandbox.io/s/new-root-lazy-component-unstabled-sk53w3

Link to code example:

## The current behavior

New root with suspense and unstable value keeps rerender

## The expected behavior

no rerender

**Comment by Et7f3** [comment]
It is documented that you must not do lazy component this way https://react.dev/reference/react/lazy#my-lazy-components-state-gets-reset-unexpectedly
