### ISSUE TITLE
Bug: Unable to build react repo locally in Mac

### ISSUE THREAD

**Issue by Biki-das** [facebook/react#27639]
Using MacosSonoma, 

When i try to yarn install in root react repo, the yarn install keeps on running infinitely
<img width="976" alt="Screenshot 2023-11-01 at 8 31 53 PM" src="https://github.com/facebook/react/assets/72331432/8ec3c1b8-3bb6-4a02-97f0-31452010a219">

@hoxyq  sorry for the ping!, do you know anything about the same?

**Comment by Biki-das** [comment]
errors out with the terminal error prompt below
<img width="976" alt="Screenshot 2023-11-01 at 8 35 43 PM" src="https://github.com/facebook/react/assets/72331432/a2bb3ca2-3965-47d9-ac22-6b228f0b4e17">

**Comment by sophiebits** [comment]
This doesn’t appear to be a React issue. If one of the dependencies can’t be installed on your machine then I’d recommend Googling for solutions (and opening an issue with that project as a last resort).
