### ISSUE TITLE
Bug: Seems like new hydrateRoot method doesn't provide any promise or callback to catch hydration process finish

### ISSUE THREAD

**Issue by 123cmp** [facebook/react#27658]
With deprecated hydrate function i could do
`hydrate(
	<Component {...properties} />,
	container,
	resolve
));`
So resolve would be called after hydration finished, but it seems impossible with new hydrateRoot

React version: 1818.2.0

## The expected behavior

`hydrateRoot(
        container,
	<Component {...properties} />,
        {},
	resolve
));`

or

`hydrateRoot(
        container,
	<Component {...properties} />,
        {
            onHydrationFinished: resolve
        }
));`

**Comment by mix0000** [comment]
The main problem is that we are flying blind. In a real-world application with dozens of dependencies, it is impossible to audit every single line of code in `node_modules`. If a third-party library triggers a synchronous update (e.g., in `componentDidMount` or via an external store subscription) during the hydration phase, the entire boundary breaks, and React gives us zero context on which component caused it.

We desperately need:
- A clearer error message pointing to the specific component instance that triggered the update.
- A standard, native way **to detect when hydration is actually finished**, so library maintainers can safely defer their updates without resorting to setTimeout hacks or guess work.

Please prioritize this. Expecting developers to manually binary-search through their component tree to find a hydration interruption is not a sustainable workflow.
