### ISSUE TITLE
Checkboxes get out of sync with state

### ISSUE THREAD

**Issue by mzabriskie** [facebook/react#2766]
I am filing this issue per @sebmarkbage.

See this bin as an example: http://jsbin.com/zehiqa/1/edit?js,output

@syranide suggested adding an `onChange` to the `<input>` calling `this.props.toggleSelected`, then adding a `setTimeout` around `setState` inside `App.toggleSelected`. This approach works but seems unnecessary since the `<input>` should bubble up to the `<div>` which is handling the event.

**Comment by pluma** [comment]
This problem still exists in React 0.14. I'm trying to derive a test case from a simplified updated version of the example: https://gist.github.com/pluma/2e1be0c689c15d12aaf5

**Comment by spicyj** [comment]
Might be the same as #3005? (I realize this was filed first.)

**Comment by pluma** [comment]
@spicyj Does React automatically preventDefault in event handlers? As far as I can tell the DOM doesn't update at all, it's not just the display. And the input is a controlled component in this case, so the re-render should mute the DOM node's stale state, shouldn't it?
