### ISSUE TITLE
Bug: useReducer triggers reducer one more time in React 18 Responsive Mode

### ISSUE THREAD

**Issue by silviuaavram** [facebook/react#27666]
React version: 18.x.x

## Steps To Reproduce

```ts
import { useReducer } from "react";

function reducer(state, action) {
  console.log(action.type);
}

const initialState = { name: "Taylor", age: 42 };

export default function Form() {
  const [state, dispatch] = useReducer(reducer, initialState);

  function handleClick() {
    dispatch({ type: "click" });
  }

  function handleMouseMove() {
    dispatch({ type: "move" });
  }

  return (
    <button onClick={handleClick} onMouseMove={handleMouseMove}>
      Click Me in Responsive Mode
    </button>
  );
}
```

1. Run the code above. It has a button with handlers for click and mouse move, each triggering a dispatch.
2. Switch to Responsive mode via dev tools, so you can use Touch event.
3. Press the button.
4. You will get in console: click, move, click.
5. In React <=17, the order would have been: move, click. The first click would not have happened, which actually is what I would expect.

Repro Sandbox: https://codesandbox.io/s/rough-water-w3fh5k?file=/App.js

This extra click seems to happen only when the element also has an onMouseMove handler attached to it, and which in turn triggers a dispatch.

Our problem in `downshift` comes from the fact that we are adding both click and mouse move handlers to an element, both which can trigger state updates. This issue impacts our users that want to migrate to React18 and expose their Selects / Comboboxes for mobiles.

**Comment by Jyotiprakash-Redapple** [comment]
###         ISSUE @silviuaavram 

============================
React 17, one dispatch call per event: https://codesandbox.io/s/unruffled-volhard-x92hq6?file=/index.js
React 18, two dispatch calls: https://codesandbox.io/s/hrzt3k?file=/App.js&utm_medium=sandpack

1. Both of those version not produce bug in dispatch
2. Some bug exist on React 17 But it solve in React 18

**- What is Strictmode in react**
Ans : Strict mode rander two times react app in developement mode 
 such as :

1.  lagacy context api
2.  reusable state 
3.  any unexpected behaiviour in sideeffect
4.  Identifying component life cycle 
5.  Other kind of issue 

- ### Why the issue linked with Strict mode 
Ans :

1.    In React.js 17 in Strict mode the app rander only one time . but it not solve this type of problem .
2.   But React.js 18 Solve the Issue and In Strict Mode The app rander two times always in developement
     but not in production . it not effect in production not add any extra UI in Dom tree
3.    You just Go to this link

-    React 18, two dispatch calls: https://codesandbox.io/s/hrzt3k?file=/App.js&utm_medium=sandpack
-    remove the strict mode it beheviour you expected .

**Comment by Jyotiprakash-Redapple** [comment]
###   Your Componenet RELATED ISUUE SOLVE 
=====================================
Before This Issue Appear I want talk you friend Actually why use useReducer And How to actually this hook use 

Why use useReducer
- in simple word useReducer just like useState , but advantage we can manage multiple state and add complex logic that not good to stay with useState hook

How Use This Hook 
this hook pass two argument fast argumet is a function techWord called Reducer fn and second argument is initial state .

it return a array where fast index is the current state and second index is a function by help we can change state value .
ex: Ex: 
const initialState = {};
const [evect, dispatch] = React.useReducer(reducer, initialState);

BUT BUT BUT, as we chnage normal state value we can not change state value directly use of this function, then how change ............
State value change only use reducer function that pass fast argument to the useReducer hook . 
 yes, we can pass special type of object where must contain that defined what type of action . When we call this function then it directly call the reducer function . 
In reducer function fast argument is initial state value and second argument what type of action
 what value return in this reducer function that is current initial state value 

Ex: 
function reducer(state, action) {
  switch (action.type) {
    case "CLICK": {
      console.log("Click Event Called");
      break;
    }
    case "MOVE": {
      console.log("move Event Called");
      break;
    }
  }
}




FULL CODE 
===============================
import React from "react";
const initialState = {};
function reducer(state, action) {
  switch (action.type) {
    case "CLICK": {
      console.log("Click Event Called");
      break;
    }
    case "MOVE": {
      console.log("move Event Called");
      break;
    }
  }
}
function Button() {
  const [evect, dispatch] = React.useReducer(reducer, initialState);

  return (
    <button
      onClick={() => dispatch({ type: "CLICK" })}
      onMouseMove={() => dispatch({ type: "MOVE" })}
    >
      Touch me
    </button>
  );
}
export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <Button />
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}

**Comment by silviuaavram** [comment]
I must have missed the StrictMode, thanks for pointing in out! Will continue the investigation on my end.

**Comment by silviuaavram** [comment]
Re-did the repro. Will update the description and reopen the ticked.

**Comment by Jyotiprakash-Redapple** [comment]
hello @silviuaavram  

- The Reducer function triggers only when call the dispatch function if you not call the dispatch function then not trigger the reducer function.
- could you give code suggestion on how  this type of scenario happen ?

**Comment by silviuaavram** [comment]
Check the description

**Comment by Jyotiprakash-Redapple** [comment]
`import { useReducer } from "react";

function reducer(state, action) {
  console.log(action);
}

const initialState = { name: "Taylor", age: 42 };

export default function Form() {
  const [state, dispatch] = useReducer(reducer, initialState);

  function handleClick() {
    dispatch("click");
  }

  function handleMouseMove() {
    dispatch("move");
  }

  return (
    <button onClick={handleClick} onMouseMove={handleMouseMove}>
      Click Me in Responsive Mode
    </button>
  );
}`

- you must not call this type reducer if you call reducer then 
`import React from "react";
const initialState = {};
function reducer(state, action) {
  switch (action.type) {
    case "CLICK": {
      console.log("Click Event Called");
      break;
    }
    case "MOVE": {
      console.log("move Event Called");
      break;
    }
  }
}
function Button() {
  const [evect, dispatch] = React.useReducer(reducer, initialState);

  return (
    <button
      onClick={() => dispatch({ type: "CLICK" })}
      onMouseMove={() => dispatch({ type: "MOVE" })}
    >
      Touch me
    </button>
  );
}
export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <Button />
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}`

you must be follow this synatx 
- check i defined all desc for you

**Comment by silviuaavram** [comment]
@Jyotiprakash-Redapple it may not be a bug, but it's a different behaviour between 17 and 18 and I need to understand how to address it, as it affects a lot of my users. Updated the code with the `type` in order to follow the API, but the issue still stands.

**Comment by Jyotiprakash-Redapple** [comment]
yes @silviuaavram  it is unexpected behavior React.js 18

**Comment by Jyotiprakash-Redapple** [comment]
yes @silviuaavram  it is unexpected behavior React.js 18
