### ISSUE TITLE
Bug: setState does not work, in the custom hook in the Safari browser

### ISSUE THREAD

**Issue by ghost** [facebook/react#27667]
Hello, the bug is that setState does not work, in the custom hook in the Safari browser, no state change occurs, as you can see in the example in the picture. Although in Chrome everything is fine

How it works in safari 
<img width="690" alt="Screenshot 2023-11-08 at 14 04 21" src="https://github.com/facebook/react/assets/105917929/5563c6a6-1a60-4882-850c-fb69ee5b0945">
How it works in Chrome 
<img width="677" alt="Screenshot 2023-11-08 at 14 08 06" src="https://github.com/facebook/react/assets/105917929/f7371ddd-ad63-4856-a485-41bff93bdecd">

React version: 18

Link to code example:
[link](https://codesandbox.io/s/silent-bird-gcx3jm?file=/src/hooks/useLocalStorage.js)

**Comment by LucaDillenburg** [comment]
Hi @Nazar-D-Aleannlab . Hope this finds you well.

I looked into your code example, but both in Safari and Chrome, I get the following:
<img width="1638" alt="Screenshot 2023-11-10 at 08 27 32" src="https://github.com/facebook/react/assets/30930222/b535d319-a183-486d-a625-3821487756b8">

It seems like the code you provided is incomplete? I do not see any `console.log` with `storedValue`, can you check the code for me? Thanks in advance.
