### ISSUE TITLE
Feature Request: Support the `defaultSelected` Property for Rendered `<option>` Elements

### ISSUE THREAD

**Issue by ITenthusiasm** [facebook/react#27669]
## The Problem

The browser's _only_ reliable way of identifying default values for `select` elements is the `selected` attribute (which controls the `defaultSelected` property). And default values are very important. Particularly, they're important if you need the ability to 1) [`Reset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset) a form's values or 2) Track the dirty/clean state of form fields (a very common use case in forms).

Using native browser features, tracking dirty fields is possible with [pure HTML+JS](https://developer.mozilla.org/en-US/play?id=xDHGGzL2Rl7Kz%2BvqDgEZmBYmzkpvrCytVJCCFYuoRYXdCoUHjzNm4Wu3jh02nHbEBmKCzvbyYf%2BNiBDq) and with other frameworks like [Solid.js](https://playground.solidjs.com/anonymous/b3e76fc8-a00a-4847-98aa-0ff267c624da) and [Vue](https://play.vuejs.org/#eNqtVwtv2zYQ/is3bUDtILbXBQUG13GbpimWrWmLJe0wRAFCS5TNhhZVkkriJf7vuyOphx/xgKEBkki8J+++e+ghOiqK/m3Jo2E0MokWhQXDbVmM4xxAzAulLTyAys9UmVue7uPj53zuX2AJmVZzeIbyz17GOYkM9qBHP3BOWuC9MJbnXJtwujdwTAM4Y/oGboURpCcTXKaGKFmZJ1aoHGYsTyV/p5LSqNJ2+C3PbRceiAfAvfUt01Nu++jukbVaTErLO3GUMst6QXEc7cM5kvJpx+qSd7voJMAyeBqcSIW2i0EiOcufduQY/035mhuJyo318uQBHEIw747iyFmr2JxqZGn7HmKGgc6g4xkE8rI84SqD3y7O3p/mRWlPJJ+37QJoDK4O7q4FIHBA49d+c+YF7KLgcHhI7mqWChVH8Pi4SUtmPLmZqPs4ahQAvKoi6vkdE6bwBxTxJynPWCntsSd027LDVdlbJku+KfmFjru11z5pddp2BOuC39sjzdn3i9f3cBdx9kFZPoSLmTDAikIrlszQpW+l0NzAQpVgFfD7QopEWLmgAgQ743BtuOQJ4vgaWOUwZEqTiIZrVRBArx1cd0Tl3CnZjEkLve4KiM0jrdmiTzUdruxNmG7fqHk7Vh3VhcMxKIyl99CFRVUh8SaxW6wHZVcmmvhXYW98C5W7GtW/MXAJFi2TRgFLU8BeYbEdSTUViYsTyxfwF5/AscJGluP1DcaVWWAJ/hpimbdKvuoLVQf7g/MCLjRLbgBD+c7F9nOBBY5JW+lme3vwmuoGbw8P61ULj5tZCGdreF16GxUPKSf1Pk81AMzHieH6llO7yfkdnJWWUZKq405nHk6o97o0hZS3z/t49xOEYcPd5lzvWfUN4aHt4hJ9hFpB6GlNqr0OidawF89X1dD135+u6Emx19Nb/1vJ9cLHS+nOtRSXrqk6Zw7j6KeHplMt4+jq2oGjMlqZ6xu7kJwQ9kmrgiOQWvCNo0zltnfHxXRmcUisN0iyh5L9aj69QomJkjhPsIXFUY64YbIl9z8cSJRUeodph33XiNsDzHmiabA5RyYSwbnmh6uSMOgqv+rx3em4NG+Cqa/8Q5MFTGVIz5vFaYqDNRRK1N2vYNKoGQK5F/yoj98JabkewuXmVF4dlFdB0pQTqzm2ylrbsk5ua+94+hapMIi6HJHTqQWxnk9zYQWT4h8Ob4UpJFtQRb91g/9LyLEDtgklvR6wlYHv2sYhPIFXwpaeY5hWpj+hYpdMiXBqUPREvV1e+Uppt2m01Uc1RDbdblPW2bZ6btVi7UmCDcjyYAE9kaLxvY3mLVuWQwRlM3PFuEXKYoc7xlKjfoZj07HVXG3uPs5FnqfHMyHTTiW+Dc6jgd9ScT/FF2TCbFruttWRS4ygHsHvGRJ4z6cCXmdhj0TS6mJJxMTtdjXJr3px5HSi1lTceqVVAQQCkgT1eXB7AdKFR1nPnaLiwToj3R75mr0Kqu2pxUohY5iTcQAt0MFEquRmNKhpTbsZ+Qlcy+OJH9rj56NBeNqg4YbhB/T4l6eZxgcbNAx+ZW3NPg4XaQWGHAxWGV7yRStOW+xmQhu7w7bhiNh0B4OdCb2D3rKEu5Kd7dCUiWwLvXVV/4owqK9NmGg46WU0GdOAGA0mYwR6aHSVUJvPFLixuNFASKAhMMSdKH2J4cJ/aBXppMJ1xlWrqKKU49EA/6w6RU+EdHwkjNQlga/OkmNxxRH6AbZJaoJDyCS/D0VGj71Mqjv0R91Bru40K+oeJst53puyYggHPxdeJKxLTu8YfvTV8Z8W8F4YVYz0MGgNROzO07xHVY/DxHHiEqvpC8ltjerOW3/+Yqf1MQxzZTuu3C43yu2q3n7vRGpnqO3X1mUw9i5Y0X5kaYpkYtr/alSOX8ZOitI1L4Tk+qPfiuNoWOmLIyYxdL+7s9YoDNa3nH816BDN8E/4DUDDqx7jceQXKU8+Of+ARd8izlVaSuTeQfyTGwwt+ejZ3pTU15ptI3h76r7ucbe4MCf32KJNdSly1AXF8ccRft7TBv3U1Rt3D/oHIZjLaPkvQZpcpQ==). However, [React](https://codesandbox.io/s/react-form-default-values-bug-issue-24067-cqz7c9?file=/src/App.tsx) does not support this feature because it does not support the `selected` attribute on `<option>` elements. What this means is that developers relying on the browser's native features with pure HTML+JS (or with another JS framework) will have a broken application if they migrate to React. It would be _fantastic_ if React could be updated to support the `selected` attribute for important use cases like these.

## The Solution
Support the `selected` attribute for the `option` element. Alternatively, create a new `defaultSelected` attribute (to keep in step with `defaultValue`, `defaultChecked`, etc.) that supports this use case.

Note that the documentation surrounding the `<select>` element would need to be updated if this change is made.

## Motivation
In addition to what I mentioned in the `Problem Statement`, it's worth considering that with the dawning of [Remix](https://remix.run/) and the close pursuit of [SvelteKit](https://kit.svelte.dev/) and [SolidStart](https://start.solidjs.com/), many web developers are returning to the benefits of using the browser's native features for forms to support progressive enhancement and to simplify their codebases. Even the React docs have acknowledged this by the fact that they no longer discourage uncontrolled inputs. That being the case, I feel like supporting this feature is a must. If for some reason `selected` is reserved, then `defaultSelected` could be used instead. What's most important is having a way to support the browser's "default value" features for _all_ native form controls.

**Comment by pravee42** [comment]
are you asking about like
<option defaultSelected></option>
instead of <option selected></option>

**Comment by ITenthusiasm** [comment]
@pravee42 I couldn't see what you were referring to. But if you were trying to give code examples, I'm basically talking about supporting this:

```tsx
<select>
  {/* Or we could use the `selected` prop */}
  <option value="1" defaultSelected>One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
</select>
```

For backwards compatibility, I think it's fine if the old syntax (where `defaultValue` is placed on the `select` element) is still supported. There would just need to be a warning not to use both approaches simultaneously. (Just like the `textarea` element in React warns against using `defaultValue` while also passing children to the element.)

**Comment by pravee42** [comment]
![image](https://github.com/facebook/react/assets/65100038/d248e0bc-324e-4d09-abf2-786c192181fd)

BASICALLY, as i have understand the docs from here we can able to update the value

```jsx
<select>
  {/* Or we could use the `selected` prop */}
  <option value="1" defaultSelected>One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
</select>
```

**Comment by pravee42** [comment]
I can able to fix this @ITenthusiasm

**Comment by ITenthusiasm** [comment]
Still an issue.

**Comment by TechQuery** [comment]
I think JSX should align with DOM properties for Web compatibility: https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/defaultSelected

But React only has an non-standard & useless `<option defaultChecked />` in JSX types...
