### ISSUE TITLE
Doc's Demo that includes const theme = use(ThemeContext) is broken

### ISSUE THREAD

**Issue by pkellner** [facebook/react#27678]
On your docs page, [https://react.dev/reference/react/use#usage](https://react.dev/reference/react/use#usage) the first demo that includes useContext is broken. It does not work on the page itself, and it does not work when you run it with the associated codesandbox.

I tried it on both firefox and chrome on a mac.

It do see this error, though not sure it is related.

`uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

**Comment by LucaDillenburg** [comment]
Hi @pkellner . Hope this finds you well.
Can you confirm you are using React’s canary or a experimental channel?
According to the documentation, "The use Hook is currently only available in React’s canary and experimental channels."

**Comment by pkellner** [comment]
There are really two things here.

Running the example in the code preview window in the doc's itself doesn't work (I don't know what version that is, but I assume it is the same as the codesandbox project it references), and...

When I download the code in that codesandbox, the version of React is specified exactly in that.

Here is that package.json

![image](https://github.com/facebook/react/assets/241170/ab1a362b-1065-4bfe-9f9a-2261e68f2913)
