### ISSUE TITLE
Bug: When building by UMD, react bundle does not includes Scheduler

### ISSUE THREAD

**Issue by rimline** [facebook/react#27675]
React version: main branch (latest code)

## Steps To Reproduce

1.yarn build react/index --type=UMD

![Snipaste_2023-11-09_09-25-34](https://github.com/facebook/react/assets/16633071/2969a5ff-88f6-4e98-901e-c62b9b9ecdca)

## The current behavior
when building UMD react.development.js , react bundle does not includes Scheduler

## The expected behavior
UMD react.development.js includes Scheduler

**Comment by MarceloSpessoto** [comment]
Hi @rimline, shouldn't you also include scheduler in the command, like this "`yarn build react/index,scheduler --type=UMD`"?

**Comment by larsthorup** [comment]
This is also an issue for the current canary release on npm:

[18.3.0-canary-6b3834a45-20231110](https://www.npmjs.com/package/react/v/18.3.0-canary-6b3834a45-20231110)

I have created a reproduction repo here:

https://github.com/larsthorup/bug-react-canary-umd-no-scheduler

**Comment by larsthorup** [comment]
Going back to an earlier canary release, this version seems to work fine:

[18.3.0-canary-d6dcad6a8-20230914](https://www.npmjs.com/package/react/v/18.3.0-canary-d6dcad6a8-20230914)

I have not triangulated precisely in which version in between the issue shows up first.

**Comment by rimline** [comment]
This has been fixed in the latest commit
