### ISSUE TITLE
TrustedTypes broken when using react

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/react#27673]
using TrustedTypes in React doesn't seem possible due to this line here:

https://github.com/facebook/react/blob/7508dcd5cc245e376860d65402972e418199264d/packages/react-dom-bindings/src/client/ReactFiberConfigDOM.js#L447

reference: https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API

**Comment by Ansh101112** [comment]
will submit pr asap.
