### ISSUE TITLE
Bug: After kills the app, the cleanup function in useEffect does not execute？

### ISSUE THREAD

**Issue by jianxiansining** [facebook/react#27682]
After kills the app, the cleanup function in useEffect does not execute？

**Comment by Jyotiprakash-Redapple** [comment]
```
import React from 'react'
export default function App(){

  React.useEffect(()=>{

    // execute when component insert into dom 
    return ()=>{
      // componet when destory to dom
    }
  },[
  //  componentdidUpdate
  ])
  return <>App</>
}
```

**Comment by jianxiansining** [comment]
> ```
> import React from 'react'
> export default function App(){
> 
>   React.useEffect(()=>{
> 
>     // execute when component insert into dom 
>     return ()=>{
>       // componet when destory to dom
>     }
>   },[
>   //  componentdidUpdate
>   ])
>   return <>App</>
> }
> ```
> 
> * on this way you write it is execute all of life cycle

useEffect(()=>{
    console.log('join。。。。。。');
    return()=>{
      console.log('exit。。。。。。');
    }
  },[])


so，but 'exit。。。。。。'，This log cannot be printed

**Comment by jianxiansining** [comment]
> ```
> import React from 'react'
> export default function App(){
> 
>   React.useEffect(()=>{
> 
>     // execute when component insert into dom 
>     return ()=>{
>       // componet when destory to dom
>     }
>   },[
>   //  componentdidUpdate
>   ])
>   return <>App</>
> }
> ```
> 
> * on this way you write it is execute all of life cycle

useEffect(()=>{
    console.log('join。。。。。。');
    return()=>{
      console.log('exit。。。。。。');
    }
  })

When killing an app, 'exit...' This log still cannot be printed

**Comment by jianxiansining** [comment]
> Reference in new

useEffect(()=>{
console.log('join。。。。。。');
return()=>{
console.log('exit。。。。。。');
}
})
When killing an app, 'exit...' This log still cannot be printed


Currently: If the first page after opening the app is A, click on a method on page A to jump to page B.
Scenario 1: Click to return to page A, where the cleaning function will be executed.
Scenario 2: Force the app to be killed, and the cleaning function on page B will not be executed.
I tested that it is feasible in the lower version of React, but not in the latest version.

**Comment by jianxiansining** [comment]
> ```
> import React from 'react'
> export default function App(){
> 
>   React.useEffect(()=>{
> 
>     // execute when component insert into dom 
>     return ()=>{
>       // componet when destory to dom
>     }
>   },[
>   //  componentdidUpdate
>   ])
>   return <>App</>
> }
> ```
> 
> * on this way you write it is execute all of life cycle

useEffect(()=>{
console.log('join。。。。。。');
return()=>{
console.log('exit。。。。。。');
}
})
When killing an app, 'exit...' This log still cannot be printed

Currently: If the first page after opening the app is A, click on a method on page A to jump to page B.
Scenario 1: Click to return to page A, where the cleaning function will be executed.
Scenario 2: Force the app to be killed, and the cleaning function on page B will not be executed.
I tested that it is feasible in the lower version of React, but not in the latest version.
