### ISSUE TITLE
Please, please the development of React Class Components

### ISSUE THREAD

**Issue by jcabrerazuniga** [facebook/react#27683]
I don't know where else to ask for this but I need to ask: Please, keep the React Class Components paradigm. I found it is a very easy way to do React programming. I understand your team wants to have a better way to develop React components through React Functions but the React Class Components strategy is top notch even if it is as today deprecated. It is said that with React Class Components everything that can be done with React Functions can be done with React Components but the inverse is not true, yet and this proves the power behind React Class Components. A few "exceptions" can lead to infinite possibilities.
        Therefore, I believe, as many others, that the use of React Class components is truly a necessity that seeks to use a wonderful paradigm.

Thanks

**Comment by pwbriggs** [comment]
Class components are no longer _recommended_, but they are not deprecated (see https://react.dev/reference/react/legacy).

Much existing code uses class components, so class components won't be removed anytime soon.

> We intend for Hooks to cover all existing use cases for classes, but **we will keep supporting class components for the foreseeable future.** At Facebook, we have tens of thousands of components written as classes, and we have absolutely no plans to rewrite them. Instead, we are starting to use Hooks in the new code side by side with classes. (https://legacy.reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy)

That being said, I have heard that class components might be moved into a separate package in a future release (to decrease the size of the package for new projects that don't use any class components), though I don't know if that's accurate. @gaearon @sophiebits @acdlite Could someone from the React team please confirm?
