### ISSUE TITLE
Bug: validateDOMNesting(...): <tr> cannot appear as a child of <table>.  - but it seems to be not correct according to the specification

### ISSUE THREAD

**Issue by saku-1101** [facebook/react#27698]
The latest version of almost all of the browsers support tr elements as *direct* children of table element, and the HTML spec also mentions so – but React warns this as an invalid HTML. The browser also doesn't automatically insert tbody before tr neither as it did before.
- [HTML spec](https://html.spec.whatwg.org/multipage/tables.html)
- [parsing rules](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intable)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table)

![image](https://github.com/facebook/react/assets/74392116/c1828236-19d2-41ad-9c71-925c04984f25)

React version: 18.2.0
Chrome:  118.0.5993.117（Official Build）（arm64）
## Steps To Reproduce
1. add tr element(s) directory under the table

## The current behavior
Warning: validateDOMNesting(...): <tr> cannot appear as a child of < table >. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.

## The expected behavior
NO validateDOMNesting warning.

**Comment by saku-1101** [comment]
created a [PR](https://github.com/facebook/react/pull/27699)

**Comment by sophiebits** [comment]
The spec you linked indicates that when a tr is found, tbody is automatically inserted. Right?

**Comment by JonRowe** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table 

> **Permitted content**
> In this order:
>
> 1 -  an optional [`<caption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) element
> 2 - zero or more [`<colgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup) elements,
> 3 -  an optional [`<thead>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead) element,
> 4 -  either one of the following:
      * zero or more [`<tbody>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody) elements
      * one or more [`<tr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr) elements
   5 -  an optional [`<tfoot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot) element

**Comment by sophiebits** [comment]
Here you can see an example confirming that the `tbody` tag is automatically added during parsing:

https://codepen.io/sophiebits/pen/JjxOZBz

As such, React still requires this tag in order to ensure that the rendered tree matches the resulting DOM.

**Comment by JonRowe** [comment]
Prehaps the error message could mention this is a React limitation seeing as its valid HTML markup to omit the tbody, or even better automatically insert the tbody for us...

**Comment by sophiebits** [comment]
The message already says `to match the DOM tree generated by the browser` which I believe is accurate and suggests that the browser will add the tbody. It's true that React could perhaps one day do this automatically but in practice adding it manually is typically not a large hurdle.

**Comment by hzsrc** [comment]
tbody is not necessary!
