### ISSUE TITLE
Bug: Conflicting useTransition hook in reactjs

### ISSUE THREAD

**Issue by e-kibet** [facebook/react#27693]
ReactJS 18 introduced the `useTranstion` react hook to update the state without blocking the UI but we have the same `useTranslation` in react-i18next which allows the developers to be able to translate the contents. Using both the hooks on the same files resulting to the conflicts. I would like to request on how to go about it without using the alternates to the above hooks.

React version: ReactJS 18

## Steps To Reproduce

1. Create a simple reactjs 18 project
2. Try to use the `useTransiton` from both the react18 for concurency and the react-i18next(for content translation)

Link to code example:

**Comment by rickhanlonii** [comment]
Sorry, I don't understand the conflict? Aren't they different names?

useTransition 
useTranslation
