### ISSUE TITLE
Support Palestinian like you did for Ukraine

### ISSUE THREAD

**Issue by axetroy** [facebook/react#27696]
As is well known, Facebook likes to get involved in politics, even in open-source projects.

Just like in the current situation in Ukraine, supporting them and providing humanitarian aid because their civilians are being harmed by the war.

Now, Jewish in Israel are massacring Palestinians in Palestine; they are killing women and children, destroying their homes, and ruining their lives.

Even humanitarian relief from the United Nations cannot enter, and the Jewish are turning into Nazis.

Genocide is still happening in the 21st century, so I hope Facebook employees take a moment to reflect on whether they should support such behavior.

Anglo-Saxon people should not foot the bill for Jewish.

**Comment by therealbluepandabear** [comment]
I love how you tried emphasize 'Jewish' and 'Jews' throughout this issue.

Be quiet anti semite.

**Comment by therealbluepandabear** [comment]
Pro tip: next time you post an issue, don't make it so obvious what your true beliefs are ;)

**Comment by therealbluepandabear** [comment]
BTW:

![image](https://github.com/facebook/react/assets/50536495/115ba353-b7d1-417e-8d10-c3caa44cd3f4)

**Comment by axetroy** [comment]
No matter how you may argue, one cannot deny the fact of the ongoing massacre by the Jewish people. Even during the World War II era, the German Nazis did not attack hospitals and children in other countries.

Israel goes as far as threatening to use nuclear weapons to bomb the Gaza Strip, a statement that even the world's nuclear powers dare not casually make.

When demons possess weapons of mass destruction, it becomes a nightmare for all of humanity.

-- 

PS: My belief is the Mother Nature.

![图片](https://github.com/facebook/react/assets/9758711/2b8ab0b5-9215-4ae8-b0d7-16684d4073a2)

**Comment by therealbluepandabear** [comment]
> No matter how you may argue, one cannot deny the fact of the ongoing massacre by the Jewish people. Even during the World War II era, the German Nazis did not attack hospitals and children in other countries.
> 
> Israel goes as far as threatening to use nuclear weapons to bomb the Gaza Strip, a statement that even the world's nuclear powers dare not casually make.
> 
> When demons possess weapons of mass destruction, it becomes a nightmare for all of humanity.
> 
> --
> 
> PS: My belief is the Mother Nature.
> 
> ![图片](https://user-images.githubusercontent.com/9758711/282988600-2b8ab0b5-9215-4ae8-b0d7-16684d4073a2.png)

With all due respect, first take care of the human rights violations in your country before criticizing others.

**Comment by therealbluepandabear** [comment]
> Even during the World War II era, the German Nazis did not attack hospitals and children in other countries.

Sounds like you're trying to say Israel is worse than Nazi Germany, which it's not. Nazi germany literally murdered  million of people. 

Direct your anger towards Hamas, the cowards that are placing themselves in daycares, hospitals, and civilian populations. But I think you like terror groups that kill Jews so you won't do that.

**Comment by sznowicki** [comment]
> Even during the World War II era, the German Nazis did not attack hospitals and children in other countries.

You're an idiot

**Comment by rimline** [comment]
HUMANITY has DOUBLE STANDARN for west conntry, WHERE are west media that stands for JUSTICE and HUMANITY, SHAME ALL OF YOU

**Comment by rimline** [comment]
As an Israeli who has also experienced genocide, he is now committing the same crimes against humanity against the Palestinians.

**Comment by rimline** [comment]
> You want to talk about Jews being Nazis. How about you call your government nazis too. Your government is putting people in concentration camps just like the nazis did:
> 
> Here's an image of some Ughur muslims in camps:
> 
> ![image](https://user-images.githubusercontent.com/50536495/282992108-c6da1164-ad22-401e-925a-72c7a38602d6.png)
> 
> Image of Jews in a concentration camp:
> 
> ![image](https://user-images.githubusercontent.com/50536495/282992169-83bf8413-9fc2-4e19-a7ed-702c414b2922.png)
> 
> So stop with this blatant

> BTW:
> 
> ![image](https://user-images.githubusercontent.com/50536495/282991017-115ba353-b7d1-417e-8d10-c3caa44cd3f4.png)
> 
> I think React should put a statement condemning China's genocide of Ughur muslims.

you care about Ughur muslims??? SOOOOO rediculous

**Comment by rimline** [comment]
> With all due respect, first take care of the human rights violations in your country before criticizing others.
> 
> The country you are from (China) is the worst human rights violator in the world and they are absolute hypocrites when they are condemning israel, just so you know.
> 
> I know China is putting a lot of anti israel propaganda there on your state controlled TV channels (which Israel doesn't have) so I am not surprised about your stance.
> 
> Also let's talk about China's increasing aggression of Taiwan, which I have not heard you condemn in your post 🤔
> 
> **I think React should put a statement saying 'Support Taiwan 🇹🇼' and 'Stop Ughur Genocide'.**


you care about Ughur muslims??? SOOOOO rediculous and you call this genocide？
[](url)
![b2de9c82d158ccb](https://github.com/facebook/react/assets/16633071/e0fd9598-9840-4185-b7f0-320b5acc26cd)

**Comment by therealbluepandabear** [comment]
A lot of Chinese bots here lmao

**Comment by Eumixaned** [comment]
They will not add banner for supporting Palestine because The United States is friends with Israel. And it's mean facebook obey USA government.
