### ISSUE TITLE
Bug: `onMouseLeave` events don't seem to behave correctly

### ISSUE THREAD

**Issue by toastdriven** [facebook/react#27700]
React version: 18.2.0
React DOM version: 18.2.0

## Steps To Reproduce

1. Add a `onMouseLeave` event to a tag with a tag (e.g. to an `<li>`, within a `<ul>`).
2. The event will not fire until your mouse leaves the **parent** tag.

Link to code example: https://github.com/toastdriven/react-hover-test

## The current behavior

`onMouseEnter` seems to behave correctly, and correctly adds the option to the active options. The highlight then takes effect.

However, when the mouse **leaves** the `<li>`, the `onMouseLeave` doesn't seem to trigger, leaving the highlight in place.

It's only upon the mouse leaving the _parent_ tag that the `onMouseLeave` seems to trigger. In this case, it's the `<ul>` tag, but I experienced the same bug when I just used `<div>` tags for everything.

Here's a gif of it in action:

![react_version.gif](https://github.com/toastdriven/react-hover-test/blob/main/react_version.gif?raw=true)

## The expected behavior

This app shows two lists (all options & active options).

When you mouse over an option in the _"All Options"_ list, it should highlight **same** option in the _"Active Options"_ list.

When you mouse out of the option, it should remove the highlight from **all** active options.

These events are hooked up as "low" in the DOM as possible, on the `<li>` tags in the list.

> Note: A Preact example with almost the same code behaves as expected & is included at `./preact-hover-test.html`. Here's what it looks like:
> ![preact_version.gif](https://github.com/toastdriven/react-hover-test/blob/main/preact_version.gif?raw=true)

**Comment by rick-ast** [comment]
I think it's because of leaving a `<li>` and enters another `<li>` immediately, react combines the `setActiveOptions` call and `activeOptions` in `handleSelect` gets old data. I added some margin for `<li>`s and the highlight was removed. Or you can use callback for `setActiveOptions` in handleSelect function to get updated state.
