### ISSUE TITLE
Bug: how to contribute to open source

### ISSUE THREAD

**Issue by rendi12345678** [facebook/react#27710]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by pwbriggs** [comment]
Hey there @rendi12345678, 👋 glad you want to help out!

A helpful resource for getting started contributing to open source projects is [GitHub's "How to Contribute to Open Source" guide](https://opensource.guide/how-to-contribute/). And remember: contributions *don't need to be huge changes*. Every tiny little contribution helps, and I'm glad you want to be a part of this.

Thanks! ❤
