### ISSUE TITLE
Bug: createPortal does not add anything to the DOM

### ISSUE THREAD

**Issue by seydanurhatipoglu** [facebook/react#27721]
Hello,

I am trying to make modals more dynamic. Currently adding them to the page like this:

`export default function SomeTable() {
  const [confirmDelete, setConfirmDelete] = useState(false)
  const [something, setSomething] = useState(null)

// triggered by a button on table
  function handleDelete(item) {
    setConfirmDelete(true)
    setSomething(item)
  }
  async function deleteSomething() {
    // delete
  }

  return (
    <>
      {*
         table
      *}

      <Confirm
        open={confirmDelete}
        setOpen={setConfirmDelete}
        title="are-you-sure"
        message="delete-confirm-message"
        onConfirm={deleteSomething}
      />
    </>
  );
}`

however, rather than setting some state on button click and conditionally adding element to the component, I want to use it like this: 

`function handleDelete(item) {
    setSomething(item)
    confirm({
      title: 'Test',
      message: 'Test mesajlı onaylama',
      onConfirm: () => deleteSomething(item)
    })
 }`

React version: 18.2.0

## Steps To Reproduce

1. Create a button that triggers the 'confirm' function in the sandbox below.
2. Add given element to the DOM with createPortal

Link to code example: https://codesandbox.io/s/modest-saha-hjvgwz?file=/src/App.js

Thought it could be about MUI but nothing changes when I replace Dialog component with just a div and h1.

## The current behavior
Nothing is added to the DOM

## The expected behavior
Add modal to the DOM

**Comment by VaishnavVerma** [comment]
@seydanurhatipoglu I have the solution, where can I share the code ?

**Comment by VaishnavVerma** [comment]
import { useState } from "react";
import { createPortal } from "react-dom";
import Confirm from "../components/common/Confirm";

export default function useConfirm() {
  const [open, setOpen] = useState(false); // Initialize to false

  return {
    confirm: ({ title, message, onConfirm, onCancel = () => null }) => {
      setOpen(true); // Set open to true when confirm is called

      // Create portal only if open is true
      return open
        ? createPortal(
            <Confirm
              open={open}
              setOpen={setOpen}
              title={title}
              message={message}
              onConfirm={() => {
                onConfirm();
                setOpen(false); // Close the modal after confirmation
              }}
              onCancel={() => {
                onCancel();
                setOpen(false); // Close the modal after cancellation
              }}
            />,
            document.getElementById("root")
          )
        : null;
    }
  };
}

Or you can just past this code in your useConfirm.js

**Comment by xd-ninja** [comment]
@seydanurhatipoglu Does this bug is from React repo ??

**Comment by VaishnavVerma** [comment]
@seydanurhatipoglu 

import { useState } from "react";
import { createPortal } from "react-dom";
import Confirm from "../components/common/Confirm";

export default function useConfirm() {
  const [open, setOpen] = useState(false); // Initialize to false

  return {
    confirm: ({ title, message, onConfirm, onCancel = () => null }) => {
      setOpen(true); // Set open to true when confirm is called

      // Create portal only if open is true
      return open
        ? createPortal(
            <Confirm
              open={open}
              setOpen={setOpen}
              title={title}
              message={message}
              onConfirm={() => {
                onConfirm();
                setOpen(false); // Close the modal after confirmation
              }}
              onCancel={() => {
                onCancel();
                setOpen(false); // Close the modal after cancellation
              }}
            />,
            document.getElementById("root")
          )
        : null;
    }
  };
}

Please try this adjustment in your code and see if it resolves the issue. If you encounter any further problems or have additional questions, feel free to ask

**Comment by seydanurhatipoglu** [comment]
No this doesnt work

**Comment by seydanurhatipoglu** [comment]
got it work by converting it to a context. final sandbox is here https://codesandbox.io/p/devbox/modest-saha-hjvgwz
