### ISSUE TITLE
Feature request: context propagation throughout component tree without Context API or prop drilling (like Vue's provide/inject API)

### ISSUE THREAD

**Issue by falkfrentzen** [facebook/react#27754]
## The Problem 

In some niche scenarios, typically in enterprise applications, the need for dynamically created and mounted React Apps arises. I will explain by using the following scenario: An enterprise app needs the functionality to dynamically create new tabs. Each new Tab should create a new instance of the same React Application - sort of like a new tab environment of a browser, in which each tab behaves the same way. Therefore we have the following structure of the App: one application shell, that hosts several instances of another React application. To be able to interact with the application shell, each part of the tab applications need to know how to identify itself - in this example using a tabId. Now the need arises, that the tabId should be available in every component, in the underlying component tree. This would typically be done by using the context API or a state management library - however, as the context is created dynamically for each new tab application, it is not possible to import it. The only other option is to pass the tabId into every component down the tree, resulting in extensive prop drilling, also passing the prop through components, that do not need it. 

## The Solution

VueJS provides a functionality called provide / inject. This works similarly to React's context API, but context-consuming components do not have to import the context. A component high up the component tree uses "provide(variableName, value)" and any deep child can call "const variable = inject(variableName)" regardless of the distance to the provider.

**Comment by markerikson** [comment]
Why not pass the tab ID into the root component of each sub-app as a prop, and then pass that down via context within the sub-app?

**Comment by falkfrentzen** [comment]
@markerikson Thank you for your answer! To clarify: each sub-app's root component does indeed receive the tab ID as props. Passing down the context from component to component all the way down the component tree in the sub-app is the only viable solution to this at the moment, but results in excessive prop drilling, as every component needs to receive the context and pass it on. There are several components, that do not need the context, but have to pass it on. React's solution would be to export the context using the context API and only import and use it in components, that need it. But for this to work, the context has to be created statically. In this scenario, the contexts are created dynamically. Importing the same context object from several sub-apps would lead to each new tab-app either overwriting the tabID for all previous ones or all new tab-apps receiving the tabID of the first one created.
Therefore I wish there was a way to provide the context to the whole underlying component tree, injecting it dynamically into the parts that explicitly demand it - just as it works using Vue's provide/inject functionality.

**Comment by markerikson** [comment]
Hmm. I'm not understanding the architecture enough here to understand why you need to "pass down the context".  Can you give a small example of how the app is set up that makes that necessary?

**Comment by falkfrentzen** [comment]
I admit, that this is a very niche use case. Basically, this app should be deployed as an ElectronJS app, meaning it won't be able to use browser tabs. Therefore the app has to provide this functionality itself. Just like in a browser window, several tabs should be able to be opened up, each one providing the same functionality as the others. For example in a browser, it is possible to have the same page opened up in two tabs at the same time, but both can have different routing histories and different states. Therefore the need arises to have several instances running alongside each other with independent state management and routing. Separating independent routing and state contexts in the application introduces a lot of complexity, so there is a better solution: Have an application shell component, that manages the different tabs. In each tab, a new instance of the same tab app is created and mounted into the application shell dynamically with an independent state and an independent routing in itself. These apps occasionally have to communicate back and forth with the application shell using a global event bus, e.g. to sync with the app shell's router, notifications, actions that change the global state, etc. To identify itself towards the application shell and other tabs, each tab has to know its tab ID. Most actions, if not all, within a tab that might trigger such an interaction, are not implemented in the root of the tab app, but deeper down and therefore also need access to the tabID.

The reason why someone would need this is: a user might have switch between different tasks often - but both tasks require the same view, but with different data, e.g. show user 1 in tab 1 and user 2 in tab 2, both showing the user-details-component.

I hope this clarifies it better

**Comment by markerikson** [comment]
Sort of. I'm actually asking more about the component setup and architecture.  Specifically, you said "contexts are created dynamically".  I'm confused why this would be necessary, and where/how you're doing that.

In my head, what I'm picturing is:

```ts
// render top-level app somewhere:
<AppInstance tabId={tabId} onSomethingUpdated={onSomethingUpdated} />

// and defined:
function AppInstance({tabId, onSomethingUpdated}) {
  const contextValue = {tabId, onSomethingUpdated};
  return (
    <AppInstanceContext.Provider value={contextValue}>
      <ActualAppComponent />
    </AppInstanceContext.Provider>
  )
}
```

The entire app instance component tree ought to be able to share the same `AppWideContext` instance, I would think.  Is there some reason why that wouldn't be the case?

**Comment by falkfrentzen** [comment]
Oh, ok, now I get what you asked for. This is exactly how I intended to set this up. However, if I understood the Context API correctly, the component ActualAppComponent would have to import the context, to be able to use it: so it would look something like this:

```jsx
// render top-level app somewhere:
<AppInstance tabId={tabId} onSomethingUpdated={onSomethingUpdated} />

// import createContext in order to initialize it and use the Context API
import {createContext} from "react";

function AppInstance({tabId, onSomethingUpdated}) {
  // initialize the context object
  const contextValue = createContext({tabId, onSomethingUpdated});
  return (
    <AppInstanceContext.Provider value={contextValue}>
      <ActualAppComponent />
    </AppInstanceContext.Provider>
  )
}
```

```jsx
// import useContext hook
import { useContext } from "react";
// import the context object - this should not be possible, as it was created dynamically in a factory function 
// and is not exported 
import { Context } from "./origin-of-context";

function ActualAppComponent() {
  const context = useContext(Context);

  return <div>{context.tabId}</div>;
}
```

It would be possible to pass the context as props: 

```jsx
// render top-level app somewhere:
<AppInstance tabId={tabId} onSomethingUpdated={onSomethingUpdated} />

// import createContext in order to initialize it and use the Context API
import {createContext} from "react";

function AppInstance({tabId, onSomethingUpdated}) {
  // initialize the context object
  const contextValue = createContext({tabId, onSomethingUpdated});
  return (
    <AppInstanceContext.Provider value={contextValue}>
      // context passed as props
      <ActualAppComponent context={contextValue}/>
    </AppInstanceContext.Provider>
  )
}
```
and consume it this way: 

```jsx
// import useContext hook
import { useContext } from "react";

function ActualAppComponent({context}) {
  const contextValue = useContext(context);

  return <div>{contextValue.tabId}</div>;
}
```
but this way, we're back to prop drilling.

**Comment by markerikson** [comment]
Hmm. First issue is that you definitely _should not_ be calling `createContext` _inside_ of a component while rendering.  Context instances _ought_ to be created at the module level, singleton-ish.  (yes technically you could create one in a `useMemo()` and pass it down, but that defeats the whole point of using context.)

What I'm still missing is: why can't all the app components in this codebase just do `import {AppInstanceContext} from "./someFileReadableByTheWholeAppInstanceCodebase"` ?

**Comment by falkfrentzen** [comment]
The problem is, that all the app instances should have independent contexts of each other. Are you suggesting, that the context object may be imported by several independent instances, but instead of all of them receiving the same context value, all of them get their own? I will try

**Comment by falkfrentzen** [comment]
Ok, this does seem to work! Thank you very much! I guess I had too limited knowledge about how the Context API works under the hood. It seems that the singleton context object, that is imported, does not actually hold the value itself, but just enables the ContextProvider, which keeps the value to communicate with the ContextConsumer/useContext. Did I get this correctly?

**Comment by markerikson** [comment]
Yeah. A given Context instance is like a marker or identifier.  The `Provider/Consumer` are a linked pair, but it's just another _type_ of component.  You can render any given `<Context.Provider>` as many times as you want, in as many places that you want.  You can have them in separate subtrees. You can nest them in the app, and the lower value overrides the upper value.  It's all based on the tree structure.

**Comment by draiverdjon** [comment]
> Yeah. A given Context instance is like a marker or identifier.  The `Provider/Consumer` are a linked pair, but it's just another _type_ of component.  You can render any given `<Context.Provider>` as many times as you want, in as many places that you want.  You can have them in separate subtrees. You can nest them in the app, and the lower value overrides the upper value.  It's all based on the tree structure.
