### ISSUE TITLE
[DevTools Bug]: React devtool is not there in codesandbox

### ISSUE THREAD

**Issue by iamayushdas** [facebook/react#27752]
### Website or app

https://codesandbox.io/p/sandbox/white-fog-2pjd7p

### Repro steps

I was following the react.dev docs
I was at tic tac toe chapter and doing my code stuff in codesandbox as per document

i triggered an issue that react devtools is not there in code sandbox
<img width="754" alt="Screenshot 2023-11-28 at 9 25 29 AM" src="https://github.com/facebook/react/assets/40708551/5d83861d-426b-4326-93ad-40a2927d8228">

### How often does this bug happen?

Every time

**Comment by iamayushdas** [comment]
Its resolved closing now
Thanks @wasimtikki1220

**Comment by happyeungin** [comment]
@iamayushdas I still find it, where do you find it?

**Comment by JustLikeThis101** [comment]
+1 can't find it either @iamayushdas

**Comment by voidao** [comment]
+1 can't find it, please help!

**Comment by LucaM0nt** [comment]
How is this solved? There's not React devtool anywhere now? I don't get it...

**Comment by lixinjie520** [comment]
I can't find it either，help plsssss!!!

**Comment by byerancy** [comment]
+1, can't find it.

**Comment by Daembius** [comment]
I can't find it either. Do I need to install an extension to my browser or something?

**Comment by Splooples** [comment]
I also have this exact problem.

**Comment by gillianbc** [comment]
Same for me - how do I display the tools?

**Comment by bertcornelissen** [comment]
Same for me.... No DevTools

**Comment by Mehdji** [comment]
Same problem...

**Comment by Plafalavah** [comment]
Same here. No DevTools

**Comment by BeiHaiSTAR** [comment]
Same, where is the Devtools ?

**Comment by Aayush974** [comment]
anyone found out where it is yet?

**Comment by devavratravetkar** [comment]
I'm not sure how to integrate React DevTools within the CodeSandBox online coding environment.
However, you can do the following steps to use it in the React Tic-Tac-Toe Tutorial:

1. First install React Dev Tools chrome extension.
2. Your tic-tac-toe preview has a URL similar to https://v123v2.csb.app/
3. Simply copy-paste it into a new tab. And open your Chrome DevTools. Now you can see the Square components and their State under the Components tab of DevTools.

![Image](https://github.com/user-attachments/assets/fa754cd3-c35f-4afb-bccb-c689869cd75f)

Hope this helps and you can utilize it to understand and complete the rest of the tutorial!
