### ISSUE TITLE
[DevTools Bug]: footer next button hover Ui issues

### ISSUE THREAD

**Issue by sanjeevkumar321** [facebook/react#27756]
### Website or app

https://react.dev/reference/react/startTransition

### issue image

![Screenshot 2023-11-29 103122](https://github.com/facebook/react/assets/46792207/d4f0904f-3f94-4c28-9dfb-ccc37cae3297)

### Expected image

![Screenshot 2023-11-29 103037](https://github.com/facebook/react/assets/46792207/3dfebe37-ff7e-4d64-9dd2-7f9ca09f687b)

code -
```
@media (min-width: 768px)
.md\:w-80 {
    width: 20rem;
}
```

fix code-
```
@media (min-width: 768px)
.md\:w-80 {
    width: 23rem;
}
```

### How often does this bug happen?

Every time

**Comment by nitesh9109** [comment]
Hi, @sanjeevkumar321, have you checked it across different platforms? I observed that it's working fine on Brave and Chrome, but I suspect there might be some computation issue on Firefox.
