### ISSUE TITLE
Bug: putting promise into JSX will cause hydration issue

### ISSUE THREAD

**Issue by himself65** [facebook/react#27778]
React version: 18.3.0-canary-5dd35968b-20231201

## Steps To Reproduce

1. clone https://github.com/himself65/react-hydration-error
2. pnpm install && pnpm run dev

Link to code example:

```js
import { Component } from '@/components/component'

export default function Home () {
  const delayedMessage = new Promise((resolve) => {
    setTimeout(() => resolve('Hello from server!'), 2000)
  })
  return (
    <main>
      <div>
        <Component delayedMessage={delayedMessage}/>
      </div>
    </main>
  )
}
```

```js
"use client"
export function Component ({
  delayedMessage
}) {
  return (
    <div>
      {delayedMessage}
    </div>
  )
}
```

## The current behavior

![image](https://github.com/facebook/react/assets/14026360/1d6a91d3-b36b-40d6-aad4-f709525e66bb)

## The expected behavior

Won't have hydration error

**Comment by himself65** [comment]
https://github.com/dai-shi/waku/issues/202

**Comment by himself65** [comment]
I think this is a React issue, not next.js. Since our customized react framework has the same error

**Comment by NakZMichael** [comment]
Prop values passed from a Server Component to Client Component must be serializable.

https://react.dev/reference/react/use-client

**Comment by godspeed-03** [comment]
The issue can be resolved by using useEffect hook .
Head to next js documentation.

- https://nextjs.org/docs/messages/react-hydration-error

**Comment by NakZMichael** [comment]
I found a workaround for this matter. It is to use `use` to  Promises.
https://github.com/NakZMichael/react-hydration-error

However, looking at the following PR, it appears that this workaround is not supposed to be necessary.
https://github.com/facebook/react/pull/25634

And it seems to be related to the following Issue discussed in the Next.js repository.
https://github.com/vercel/next.js/issues/56470

**Comment by himself65** [comment]
Since promise is a valid jsx element, I think it should not cause ssr issues or otherwise should be documented

**Comment by MadhuSaini22** [comment]
@himself65 , Thanks for reporting the hydration issue with promises in JSX. Putting promises directly in JSX can be tricky in React 18. 
Here's a quick fix:

Render a placeholder on the server while the promise resolves on the client (e.g., a loading spinner). Update the DOM with the resolved value once it's available.
Remember to update the server-side HTML with the resolved value for optimal performance.

For more advanced handling, consider Suspense or data fetching libraries like react-query or SWR.

Happy coding!

**Comment by himself65** [comment]
bump
