### ISSUE TITLE
Bug:  Uncaught TypeError: Cannot read properties of null (reading 'useContext') when importing react-router-dom

### ISSUE THREAD

**Issue by BiancaScoro** [facebook/react#27787]
React version:

## Steps To Reproduce

1. Create a basic React app by using npx create-react-app name of app
2. import Link or BrowserRouter from 'react-router-dom' and you will get the error and a blank screen. 

![image](https://github.com/facebook/react/assets/120531347/92c566a3-b981-457d-924e-6af7b0b7db9f)

## The current behavior
Giving me an error in the console.

## The expected behavior
Use react-router-dom and have the code appear in the browser.

**Comment by BiancaScoro** [comment]
I'm not sure if this additional error is also affecting it... "[DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:6348) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option."
This is a screenshot of the error in the console 
![image](https://github.com/facebook/react/assets/120531347/3d9e779b-1a7b-4849-a022-80bb49a288c1)
the error doesn't show in the browser, its just white.

**Comment by yasirw212** [comment]
### Potential Solutions

- upgrading webpack-dev-server to 4.7.3

- https://github.com/facebook/create-react-app/pull/11862/files/2dff88610f9ad215349424d1769b88e0a0d2fa1d

- Deleting node_modules folder and running npm install to include new updates in dependencies that may be causing the error

**Comment by BiancaScoro** [comment]
I deleted the package.json and now I cannot get it back. I tried npm install.

**Comment by BiancaScoro** [comment]
I recovered it.

**Comment by BiancaScoro** [comment]
I think the react-router-dom issue is something different. I still have the error.

**Comment by BiancaScoro** [comment]
The error is showing in the browser now 

![image](https://github.com/facebook/react/assets/120531347/29b1bd0a-5aa7-4309-8c29-231180b428bf)

**Comment by BiancaScoro** [comment]
This is what the App.js looks like 
![image](https://github.com/facebook/react/assets/120531347/d51ecb48-b12b-4f4c-8b15-6e414f96de5f)

**Comment by yasirw212** [comment]
> I deleted the package.json and now I cannot get it back. I tried npm install.

You weren't supposed to delete the package.json only the node_modules folder that is built when you run npm install based off the dependencies inside the package.json. Did you reinstall the dependecies you previously had or did you recover the package.json as it was?

**Comment by BiancaScoro** [comment]
Yes, I did.

**Comment by atalayio** [comment]
Can you try this?

```javascript
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
```

or like this?

```javascript
<Link
to={item.command}
>
{item.icon}
{item.name}
</Link>
```

"to" prop, would be okay.

**Comment by BiancaScoro** [comment]
I just discovered I am able to import from react-router-dom if I make an application using npm create vite rather than using npx create-react-app. I only get the error when I use npx create-react-app for some reason.

**Comment by Mohammad-Hossein-Ostad** [comment]
Hello @BiancaScoro, 

`npx create-react-app` works pretty fine. Im not sure if you import and wrap ` { BrowserRouter } `  into `src/index.js`.

**Comment by BiancaScoro** [comment]
Yes, I do.

**Comment by BiancaScoro** [comment]
It is the npx create-react-app for me, I am not sure why.

**Comment by Mohammad-Hossein-Ostad** [comment]
Could you share  the `src/index.js` source code?

**Comment by BiancaScoro** [comment]
![Uploading image.png…]()

**Comment by BiancaScoro** [comment]
![image](https://github.com/facebook/react/assets/120531347/169e95bc-40e4-45c4-9ee6-1ea74b785235)

**Comment by wangsanshao** [comment]
HI，Has the problem been solved？

**Comment by leoimewore** [comment]
Is this issue solved ?

**Comment by Nathan-Roberts123** [comment]
Is this issue solved??

**Comment by BiancaScoro** [comment]
Yes it is.

**Comment by pwbriggs** [comment]
> Yes it is.

As per your comment, @BiancaScoro, would you mind [marking this issue as closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue)?

Thanks! 😄

**Comment by bhuvankamma** [comment]
hey
