### ISSUE TITLE
injecting html conversion results "not dangerously" (i.e. converted markdown)

### ISSUE THREAD

**Issue by Pomax** [facebook/react#2778]
I have a setup where log entries are written and stored in markdown plain text. Come time to render these in the browser, they're run through a markdown to HTML converter, and that gets rendered by the browser. In React, despite the fact that the code never works with HTML except at the very last step (edits occur on plain text, saving occurs on plain text, plain text in the props/state, etc) the only way to get this data loaded in is by using the cumbersome `dangerouslySetInnerHTML` attribute, even though this HTML is not human-generated in any way, and isn't "dynamic" in the traditional sense; it's just the snapshot HTML representation of my text, in the same way that the HTML that React generates is simply a snapshot representation of my component.

```
var MarkDown = React.createClass({
  render: function() {
    // completely transient data; It has no meaning outside of the render function
    var html = markdown.toHTML(this.props.text);
    return <div className="post" dangerouslySetInnerHTML={{__html: html }}</div>;
  }
});
```

Is there something available that doesn't "lie" about what is being done in this scenario, like a way to tell React that there are additional safe processors available, such as:

```
React.registerContentTransformer("markdown", markdown.toHTML);

var MarkDown = React.createClass({
  render: function() {
    return <div className="post">{markdown: this.props.text}</div>;
  }
});
```

(or whatever syntax would work that makes it explicit we're not working with human-generated dynamic HTML content, but with rigidly transformed, syntactically-correct-unless-the-transformer-has-bugs output)

edit: to further explain the motivation for this question/request, the `dangerouslySetInnerHTML` mechanism is great and we definitely need it for user-generated HTML strings. However, there should also be a way to extend the mechanism that exists inside the `render` function for transforming data that isn't HTML but can be snapshot-serialized to HTML (like React components themselves). An additional API for telling the JSX transformer that there are additional transformers available that can be used exclusively during render() using special curly bracket syntax would be close to ideal.

People would still need to use `dangerouslySetInnerHTML` for regular HTML string data, but people who have data that isn't HTML at all, merely transiently transformable into HTML form, should not need to say "this HTML is dangerous"; it's only as dangerous as the transformer makes it, putting it on part with the JSX transformer itself (bugs notwithstanding, the resulting HTML should always be well formed and legal)

**Comment by somon** [comment]
545465454 454654644
