### ISSUE TITLE
Feature: useEffectEvent should be useCallback without dependency array

### ISSUE THREAD

**Issue by kuchta** [facebook/react#27793]
The experimental useEffectEvent is generally something useCallback should have been without depedency array or with empty dependency array to match the behavior of useEffect. Introducing new name will just bring more confusion since it's very hard to image, what useEffectEvent should do...🙏🏻✌🏻👀

**Comment by eqpoqpe** [comment]
um, cool

**Comment by bayareaunicorn** [comment]
Seems useless why not just pass an empty array in your useEffect to render only once?

**Comment by kuchta** [comment]
@bayareaunicorn That's what it's typically combined with, but if you want to access actual values from a callback provided there, that's when you would want to use it. Despite it's name, experimental [useEffectEvent](https://react.dev/learn/separating-events-from-effects#declaring-an-effect-event) is not an equivalent to useEffect, but to a useCallback, in a sense. That's what this issue is about, that people will probably be confused by it's name...

**Comment by kuchta** [comment]
@bayareaunicorn Well, useChildCallback is probably better then useEffectEvent, but considering that people are alredy used to that returned reference from useHooks changes as often as some of it's dependencies, I think that just useCallback without any dependencies would communicate that intention better with respect to already memorized rules.

**Comment by Gregoor** [comment]
I think that would be unwise, the rules of `useEffectEvent` are that it's only to be called from effects and not passed to child components. `useCallback` does not have that limitation. Having semantics diverge this massively by just (not) passing a dependency array in, would lead to confusion.

**Comment by kuchta** [comment]
@Gregoor Fair point. So maybe useEffectCallback would be better choice, since calling it Event is quite misleading as well...

**Comment by Gregoor** [comment]
Yeah that maps closer to my conceptualization of it as well. I think the React team's lingo might diverge here from ours though. I would be curious to read a team member's take on this.

**Comment by rickhanlonii** [comment]
We're going to be iterating on this API a bit more after 19 so I wouldn't spend too much time bike-shedding the name just yet. The current distinction makes sense because the function returned from useCallback can be passed down, but useEffectEvent can only be used locally, and it would be confusing to have the same API have different prop passing semantics. We have some ideas for how to remove that restriction so we're going to investigate those options. 

I'll share more when we know more.

**Comment by huynhducduy** [comment]
> We're going to be iterating on this API a bit more after 19 so I wouldn't spend too much time bike-shedding the name just yet. The current distinction makes sense because the function returned from useCallback can be passed down, but useEffectEvent can only be used locally, and it would be confusing to have the same API have different prop passing semantics. We have some ideas for how to remove that restriction so we're going to investigate those options.
> 
> I'll share more when we know more.

Hey @rickhanlonii any update on this?

**Comment by barryam3** [comment]
You might be interested in `useEventCallback` from `usehooks-ts` https://usehooks-ts.com/react-hook/use-event-callback
