### ISSUE TITLE
Make onChange work for contenteditable

### ISSUE THREAD

**Issue by zpao** [facebook/react#278]
Apparently it doesn't, but it would be pretty awesome if it did. We already listen for `DOMCharacterDataModified` so I don't think it should be too terrible. Tangentially it would be great to stop using mutation events and switch over to observers (let's not do that here though unless it dovetails really nicely).

Interested @spicyj?

**Comment by pavelpashkovsky** [comment]
```
<ContentEditableDiv
 contentEditable
 placeholder={WRITE_MESSAGE_MSG}
 onInput={e => props.messageOnChange(e.currentTarget.innerText)}
/>
```

**Comment by ababanjen** [comment]
> @edwardmsmith It may not work on older browsers, but for modern browsers you can use the onInput callback like so:
> 
> ```
> <div
>   contentEditable="true"
>   onInput={function(e) {
>     console.log("woohoo!");
>   }}
> >initial content</div>
> ```
> 
> Edit: if you do that, be very sure not to use the app state for that 'initial content'. That will make it a controlled component that gets rerendered every time, and the user's cursor will jump to the beginning of the text with every keypress.

how to get the content value?

**Comment by ANG95** [comment]
<tbody>
                                    {
                                        DataPacientesAPI.map((paciente, i) =>
                                            <tr key={i}>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "dni_cliente", e)}>{paciente.dni_cliente}</td>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "nombres_cliente", e)}>{paciente.nombres_cliente}</td>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "ap_paterno_cliente", e)}>{paciente.ap_paterno_cliente}</td>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "ap_materno_cliente", e)}>{paciente.ap_materno_cliente}</td>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "direccion_cliente", e)}>{paciente.direccion_cliente}</td>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "hcl_cliente", e)}>{paciente.hcl_cliente}</td>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "fnacimiento_cliente", e)}>{paciente.fnacimiento_cliente}</td>
                                                <td contentEditable={iActivo === i ? true : false} suppressContentEditableWarning onBlur={e => Editando(i, "sexo_cliente", e)}>{paciente.sexo_cliente}</td>
                                                <td>
                                                    <div className="text-info"
                                                        title="Editar datos del paciente"
                                                        style={{ cursor: "pointer" }}
                                                        onClick={() => setiActivo(i)}
                                                    >
                                                        <FaEdit size={20} />
                                                    </div>
                                                </td>
                                            </tr>
                                        )
                                    }

                                </tbody>
