### ISSUE TITLE
Reading order/sequence is not in understandable manner on Data card.

### ISSUE THREAD

**Issue by msftedad** [facebook/react#27809]
React version: 2.80(23103111)

## Steps To Reproduce

Step1: Turn on Voice Over & Open ‘Excel’ application(Sample file-https://microsoft-my.sharepoint.com/:x:/p/v-ymounika/EcWM0sYjHglEqIYbRtUBQzgBHamElXWelWncOdKo4Ugy8Q?e=S4fpz4).
Step2: Swipe to any cell and add meaning text (word).
Step3: Swipe to 'Data' tab present in ribbon.
Step4: Swipe to data type and select data type.
Step5: Swipe till cell which having rich data type.
Step3: Open context menu on the cell and navigate to the show data card menu item and activate it.
Step4: Try to navigate to the page and observe the issue.

## The current behavior
Voice Over users are unable to understand the context of the page if focus is not on a logical order.

## The expected behavior
Voice Over focus should navigate in the data card in a logical order, so that users are able to understand the content in sequential order.

**Attachment:**

https://github.com/facebook/react/assets/93735775/9b2a8764-b739-4d86-9838-53226cdc53ab

**Comment by rickhanlonii** [comment]
This seems like a bug in the application and not in React, but if you share a sandbox using only React I can re-open and take a loot.
