### ISSUE TITLE
Bug: HTML element <col> cannot be used as a direct descendant of <table>

### ISSUE THREAD

**Issue by eddhurst** [facebook/react#27815]
React version: * <= 18.2.0

## Steps To Reproduce

1. Have a `table` element with a `col` element as a direct descendant, outside of a `colgroup` 
2. See the console error: `Warning: validateDOMNesting(...): <col> cannot appear as a child of <table>.`

<img width="1006" alt="Screenshot 2023-12-08 at 14 40 04" src="https://github.com/facebook/react/assets/9933592/83e81439-ae5f-414b-aeea-89be71022d39">

Link to code example: https://jsfiddle.net/yz0jdt9a/

## The current behavior

The `validateDOMNesting` function currently identifies the `col` element as an invalid child of `table`, and expects that the input instead be wrapped in a `colgroup` element.

i.e.

Currently indicated as invalid:
```
<table>
  <col>
  <col>
  <thead>
    ...
```

Current behavior understood as valid.
```
<table>
  <colgroup>
    <col>
    <col>
  </colgroup>
  <thead>
    ...
```

## The expected behavior

The [HTML spec](https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element) for the `colgroup` element identifies that

> A [colgroup](https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element) element's [start tag](https://html.spec.whatwg.org/multipage/syntax.html#syntax-start-tag) can be omitted if the first thing inside the [colgroup](https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element) element is a [col](https://html.spec.whatwg.org/multipage/tables.html#the-col-element) element, and if the element is not immediately preceded by another [colgroup](https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element) element whose [end tag](https://html.spec.whatwg.org/multipage/syntax.html#syntax-end-tag) has been omitted. (It can't be omitted if the element is empty.)

Similarly the [MDN docs](https://developer.mozilla.org/en-US/docs/web/html/element/col) for `col` specifies under the "Permitted Parents" heading

>  parents | `colgroup` only, though it can be implicitly defined as its start tag is not mandatory. The `colgroup` must not have a span attribute.

To that end, the table element should accept `col` as a valid nested element.

**Comment by sophiebits** [comment]
Similar to how we require a tbody tag around tr, we require the colgroup tag explicitly. React would otherwise need to automatically add the tag itself to avoid issues with hydration and the like, and we’re not currently set up to do that.
