### ISSUE TITLE
Bug: Error in the react web page. (Go full-stack with a framework)

### ISSUE THREAD

**Issue by nepalivai** [facebook/react#27816]
There is a colour-sensitive error on the Home page of the [react.dev](React) web page. 
<img width="928" alt="Screenshot 2023-12-08 200854" src="https://github.com/facebook/react/assets/108126089/375e7378-66e8-44cc-81f5-beada37124c3">
<img width="935" alt="image" src="https://github.com/facebook/react/assets/108126089/557763c6-ad6b-4cc0-94e5-5960f8aca6d1">
As shown in the picture both light /Dark modes of the web page have the same error in the conference dropdown menu. 

React version: website 

## Steps To Reproduce

1. Go to react.dev
2. Go to the "Go full-stack with a framework" section
3. Find the demo page of the conference site 
4. select the drop-down menu having the year of the program.
5. see the issue.

## The current behaviour
Unable to see the year properly.

## The expected behaviour
Proper colour arrangement.

**Comment by priyansh004** [comment]
hello, 
i understand the issue would you assign it to me?

**Comment by Parth0902** [comment]
Hi can I work on this issue?

**Comment by AnuragGoel09** [comment]
I understood the issue . Can you let me work upon it?

**Comment by kiojoel** [comment]
I didn't notice the date beneath the initial date either, but I did see it after hovering over it.

**Comment by nepalivai** [comment]
@AnuragGoel09 You can work on the issue but the question is how?

**Comment by AnuragGoel09** [comment]
Thanks @nepalivai . I am thinking to change the padding so that text will not look a little congested and also style the coloring for both dark and light mode specifically using the state variable used to define mode.

**Comment by nepalivai** [comment]
@AnuragGoel09, yes plz go ahead but I think you misunderstood. I was asking where is the source code for the site. After all it is an effortless task.

**Comment by AnuragGoel09** [comment]
Hey @nepalivai , I am sorry I misunderstood it , I thought you will give source code based on to whom you assign the work.

**Comment by nepalivai** [comment]
@AnuragGoel09 haha😂😂, If I had the source code I would work on it my self.

**Comment by AnuragGoel09** [comment]
@nepalivai  yeah 🤣🤣 true i totally misunderstood

**Comment by nepalivai** [comment]
@AnuragGoel09 something like a folder containing the website file or some repo of the website. After all people in Meta don't care about their customers until you pay them.

**Comment by AnuragGoel09** [comment]
@nepalivai I know that 😅😅 , I was asking what degree ( education) you are doing ....

**Comment by nepalivai** [comment]
@AnuragGoel09 ohh that's personal data I don't want to say it here.

**Comment by AnuragGoel09** [comment]
@nepalivai Oh then where should I ask you xd

**Comment by pwbriggs** [comment]
Please remember to be respectful of the React developers 🌟.

@nepalivai @AnuragGoel09 The source for this page can be found in the `reactjs/react.dev` repo at `src/components/Layout/HomeContent.js`. I quickly skimmed over the file, and it looks like your bug may be around [line 229](https://github.com/reactjs/react.dev/blob/main/src/components/Layout/HomeContent.js#L229) or [line 1110](https://github.com/reactjs/react.dev/blob/main/src/components/Layout/HomeContent.js#L1110).

**Comment by nepalivai** [comment]
@pwbriggs Thanks for the help I will be working on the issue asap.

**Comment by kiojoel** [comment]
The problem lies within the CSS on line 1502

**Comment by nepalivai** [comment]
@kiojoel thanks for the help hope this fixes it.

**Comment by rickhanlonii** [comment]
Fixed in https://github.com/reactjs/react.dev/pull/6483, thanks @nepalivai for reporting and submitting the fix!
