### ISSUE TITLE
Bug: Server renders inconsistent attribute values

### ISSUE THREAD

**Issue by 1aron** [facebook/react#27836]
- https://github.com/vercel/next.js/issues/47617
- https://github.com/facebook/react/pull/22041

React version: v18.1.0

## Steps To Reproduce
```tsx
import React from 'react';
import { renderToString } from 'react-dom/server';

console.log(renderToString(<div class="mt:0>div"></div>))
```

Link to code example: https://stackblitz.com/edit/react-zvjacx?file=src%2FApp.js,src%2Findex.js

## The current behavior
`renderToString` or `renderToStaticMarkup` have the same problem.
```tsx
import React from 'react';
import { renderToString } from 'react-dom/server';

renderToString(<div class="mt:0>div"></div>)
// ❌ <div class="mt:0&gt;div"></div>
```

## The expected behavior
```tsx
import React from 'react';
import { renderToString } from 'react-dom/server';

renderToString(<div class="mt:0>div"></div>)
// ✅ <div class="mt:0>div"></div>
```
React should not encode the entire string, especially in class and CSS-related string processing, which will cause the CSS selector to be selected incorrectly.

`mt:0>div` is a valid class syntax for [Master CSS](https://css.master.co).

**Comment by 1aron** [comment]
Is there any reason to specifically encode these characters? https://github.com/facebook/react/blob/493610f299ddf7d06e147e60dc4f2b97482982d2/packages/react-dom/src/__tests__/quoteAttributeValueForBrowser-test.js#L22-L50

**Comment by Janelaxagh** [comment]
---

It seems that you have a problem with character encoding when using `renderToString` in React v18.1.0. It automatically encodes special characters such as `>` in their HTML texts, which leads to incorrect configuration of CSS elements in your case.

This may be an undesirable change, perhaps if you use special characters in the class for styles or CSS selectors. Your class `mt:0>section` should not be automated in the `mt:0&gt;section`, as this may lead to an irreversible change in the structure.

You can address this issue by using `dangerouslySetInnerHTML` to output unescaped HTML characters:

```javascript
import React from 'react';
import { renderToString } from 'react-dom/server';

export default function App() {
  // Use dangerouslySetInnerHTML to output unescaped HTML characters
  const htmlString = renderToString(
    <div dangerouslySetInnerHTML={{ __html: '<div class="mt:0>div"></div>' }}></div>
  );

  return <div dangerouslySetInnerHTML={{ __html: htmlString }}></div>;
}
```

---

**Comment by 1aron** [comment]
@Janelaxagh I understand that `escapeHTML` is somehow to prevent XSS, but does it seem legal to write decoded characters in attribute values? Sometimes we will select the target element through the CSS attribute selector, but when the attribute value of the target element is encoded or decoded, the CSS rules that can be selected normally will become invalid.

I'm not sure how React balances correctness and safety.

**Comment by Janelaxagh** [comment]
@1aron 
 It seems to me that the best way to balance security and correctness in React is to use alternative styling methods, such as classes or inline styles, instead of CSS selectors that depend on attribute values. This avoids potential security issues associated with code injection, while at the same time providing more reliable and predictable style behavior.

**Comment by Janelaxagh** [comment]
@1aron 
It's great that you found a solution! This is a great find and will definitely make working with CSS fetching easier.
