### ISSUE TITLE
Questions and Help: useMemo vs Normal Object

### ISSUE THREAD

**Issue by Darsbir** [facebook/react#27837]
React version: all

## Question

Which one these 2 below scenario is actually cheaper in terms of performance
1. using useMemo in a small object and giving dependency array and checking if something's changed in dependency array and act according to that.
2. don't use useMemo and believe that object creation on every render will be actually cheaper than using useMemo.

FYI - myStyle and myStyle2 is not being passed as props to some other component and the given component is a leaf component (present at the end of react tree)

<img width="534" alt="Screenshot 2023-12-15 at 9 27 05 AM" src="https://github.com/facebook/react/assets/102596512/1786b9ec-62a8-4123-95d2-64665bf09191">

**Comment by Janelaxagh** [comment]
When working with a small object in React, where creating it does not require complex calculations, simply creating an object on each render can be more efficient than using useMemo. This is especially true if the object does not represent heavy calculations and its size is not noticeable for performance.
