### ISSUE TITLE
Bug: Runtime Error App.js: (0 , _reactDom.useFormStatus) is not a function (5:22)

### ISSUE THREAD

**Issue by ASPzoomin** [facebook/react#27835]
from React Docs example "Display a pending state during form submission" given code is not working

React version:18.2

## Steps To Reproduce

1) click on the given fork link from the docs
2) here's the link from the docs [https://react.dev/reference/react-dom/components/form#display-a-pending-state-during-form-submission](https://react.dev/reference/react-dom/components/form#display-a-pending-state-during-form-submission)

Link to code example:

[https://codesandbox.io/p/sandbox/react-dev-2kxqp6?file=%2Fsrc%2FApp.js%3A10%2C5](https://codesandbox.io/p/sandbox/react-dev-2kxqp6?file=%2Fsrc%2FApp.js%3A10%2C5)

## The current behavior
Not able to Submit the form due to this issue , reactDom.useFormStatus) is not a function

## The expected behavior
Should be able to submit the form

**Comment by ASPzoomin** [comment]
link to code: [https://codesandbox.io/p/sandbox/react-dev-2kxqp6?file=%2Fsrc%2FApp.js%3A10%2C5]

**Comment by ASPzoomin** [comment]
link to code [](https://codesandbox.io/p/sandbox/react-dev-2kxqp6?file=%2Fsrc%2FApp.js%3A10%2C5)

**Comment by ASPzoomin** [comment]
link to code:[https://codesandbox.io/p/sandbox/react-dev-2kxqp6?file=%2Fsrc%2FApp.js%3A10%2C5](https://codesandbox.io/p/sandbox/react-dev-2kxqp6?file=%2Fsrc%2FApp.js%3A10%2C5)

**Comment by Janelaxagh** [comment]
---

"It's apparent that `useFormStatus`, mentioned in the example, isn't a standard function within React. This might be a typo in the documentation.

If you need to track form submission status, you'll have to create your own hook or logic for this task. Here's an example that might help:

```javascript
import React, { useState } from "react";
import { submitForm } from "./actions.js";

function Submit() {
  const [pending, setPending] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setPending(true);

    try {
      await submitForm();
      // Actions after successful form submission
    } catch (error) {
      // Error handling when submitting the form
    } finally {
      setPending(false);
    }
  };

  return (
    <button type="submit" onClick={handleSubmit} disabled={pending}>
      {pending ? "Sending..." : "Send"}
    </button>
  );
}

export default function App() {
  return (
    <form>
      <Submit />
    </form>
  );
}

export async function submitForm() {
  await new Promise((res) => setTimeout(res, 1000));
  // Your logic for form submission, for instance, an API request
}
```

This example uses `useState` to track the form submission status and alter the button text and accessibility based on this status. The `handleSubmit` function handles the form submission and manages the pending state."

---

**Comment by kiojoel** [comment]
@ASPzoomin I think the useFormStatus isn't currently accessible. The useFormState hook is available for React Server Components and it's still experimental and not widely available. You can read the documentation just to be clear.

**Comment by rickhanlonii** [comment]
@ASPzoomin @kiojoel you don't need React Server Components to use `useFormStatus` or other new hooks like `useFormState`, `useOptimistic`, and `use`. These new APIs are supported on the client, but have not been released yet. You can try them out by installing the latest `react@canary`.

**Comment by pwbriggs** [comment]
See the ["Versioning Policy" page] for more information on the Canary release channel.

["Versioning Policy" page]: https://react.dev/community/versioning-policy#all-release-channels
