### ISSUE TITLE
Components and Profiler don't appear in DevTools

### ISSUE THREAD

**Issue by ackvf** [facebook/react#27844]
I tried to disable/enable remove/reinstall the extension to no avail. It does detect websites as using React either in development or production mode, but these tabs don't pop up in DevTools. What is wrong?

![image](https://github.com/facebook/react/assets/2313018/6a4888b2-1e8b-4850-8be1-cb2a2222607c)

**Comment by Zikoat** [comment]
Also seeing this issue on react.dev.however if you enable the extension in incognito mode you can open the page in an incognito tab and see the ⚛️component and ⚛️profiler tabs.

**Comment by Zikoat** [comment]
Google Chrome Version 120.0.6099.110 (Official Build) (64-bit)
React Developer Tools Version 5.0.0 (12/5/2023)
Windows 11 Business Version 21H2, OS build 22000.2538

This happens on all pages.
Tried removing all other extensions, reloading page, reopening devtools, restarting chrome, reinstalling extension.
The only thing that works is incognito mode.

**Comment by Zikoat** [comment]
Other extensions, such as DDV https://chromewebstore.google.com/detail/digital-data-viewer-ddv/jakfkigacoblojbffhjananlifkombok or Vue Devtools show up as separate tabs in the chrome devtools.

**Comment by Zikoat** [comment]
bump. Has 3 upvotes.

**Comment by ackvf** [comment]
Interesting, has it been fixed in the meantime or does it just work now?
![image](https://github.com/user-attachments/assets/a072863b-891f-4f8b-813c-43ddbc542feb)

**Comment by andreasvirkus** [comment]
I just experienced this today, had to clear site cache (devtools > Application > Storage > "Clear site data") and then restarted the browser, then I could see them again. It's very annoying whenever it happens, wish it got some attention
