### ISSUE TITLE
Are you going to make React dead in your hand?

### ISSUE THREAD

**Issue by totaland** [facebook/react#27853]
While the server component hasn't taken the limelight, Signals has made headlines for every corner of the web. What are you doing? It is do or die. Adding Signals into React won't hurt your option of taking the SVC approach but only strengthen the React in the web dev map. Just do it.

**Comment by blling** [comment]
Maybe `React` is sick :-(

**Comment by camoqq** [comment]
Even if something like that were to happen, the facebook devs will give a good fight.

**Comment by totaland** [comment]
Interesting that they would give a good fight. That would just go against their core company belief to move fast and break things.

**Comment by steida** [comment]
Meanwhile, use https://github.com/pmndrs/jotai. It's like Signal, but better because it's React.

**Comment by rickhanlonii** [comment]
No, we're not.

**Comment by 1057105012** [comment]
I don't know why React doesn't use Signal. To be honest, apart from SEO, I really hate server components. Especially the behavior of treating them as first-class citizens. If that's the case, I would rather go back to the template engine. It's pure HTML and supports dynamic tags, and it's more compatible with browsers. Maybe their pride doesn't allow them to do this? I don't think Signal will violate the paradigm of React. One implementation solution is to treat a single component as composed of multiple calculation blocks. To be honest, apart from the ecosystem of React, the user experience of React is really hard to describe. Leaving the biggest performance issue alone and studying server components instead, isn't that missing the point? The original form should be as simple as 1+1=2, but in React, it's like calculus.
