### ISSUE TITLE
Bug: File input element missing cancel event handler

### ISSUE THREAD

**Issue by uipoptart** [facebook/react#27858]
React version: 18.2.0

## Steps To Reproduce

1. Add an `input` of type `file` with a `cancel` prop like this to a functional component: `<input type="file" cancel={cancel}>`
2. Observe error in console:
```Warning: Invalid value for prop `cancel` on <input> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
    at input
    at App```

Link to code example: [https://codesandbox.io/p/sandbox/keen-grothendieck-jcr72t?file=%2Fsrc%2FApp.js](https://codesandbox.io/p/sandbox/keen-grothendieck-jcr72t?file=%2Fsrc%2FApp.js)

## The current behavior
The `cancel` prop is considered an invalid prop on the `file` `input`.

## The expected behavior
`input` of type `file` includes `cancel` event listener. 
See documentation here: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#detecting_cancellations](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#detecting_cancellations)
See a working vanilla JS/HTML code example: [https://jsfiddle.net/snjm9p5d/](https://jsfiddle.net/snjm9p5d/)
The PR where this functionality was added to the HTML standard: [https://github.com/whatwg/html/issues/6376](https://github.com/whatwg/html/issues/6376)

**Comment by uipoptart** [comment]
Another helpful link I meant to include is the browser compatibility for `cancel` on the element: [https://pr30946.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLInputElement](https://pr30946.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLInputElement)

**Comment by iamamanprajapati** [comment]
> Can I get assigned this task??

Yes @Martins100-Tmd You can

**Comment by zh-lx** [comment]
`cancel` is an event so you should use `<input type="file" onCancel={cancel}>`. However, react dosen't support `cancel` for `input[type="file"]`, I add a PR #27897 for this.
