### ISSUE TITLE
I have this issues help me with this

### ISSUE THREAD

**Issue by akashnj10** [facebook/react#27866]
![Screenshot (567)](https://github.com/facebook/react/assets/154408250/6fa51410-7c25-4c65-9770-e97a817aa2aa)
![Screenshot (568)](https://github.com/facebook/react/assets/154408250/e9611044-2f41-42d0-a7d6-489abb652cd5)
![Screenshot (569)](https://github.com/facebook/react/assets/154408250/4dcf50c2-cf92-4c15-8c00-b31a11a416ab)
![Screenshot (570)](https://github.com/facebook/react/assets/154408250/dfac48fa-0270-4f3f-abcb-700b934f2864)

**Comment by salvadorperezm** [comment]
By the error in the console, it seems there's a problem while creating the ` _updatedFibers` variable, could you share the portion of your code where you are trying to set this variable?

**Comment by akashnj10** [comment]
i solved it bro. Btw thank you for ur response bro👍
