### ISSUE TITLE
spread operator and component not working

### ISSUE THREAD

**Issue by mteichtahl** [facebook/react#2786]
When using component to build a custom react component which uses the ES6 spread operator I'm receiving the following error in navItem, which I hope someone may be able to shed some light on. My sense is that component does not yet support the spread operator

Running "exec:component_build" (exec) task

       build : resolved in 32ms
       build : files in 78ms
>>      error : Error: 
>> /Volumes/src/jsRouter/js/modules/ui-components/navItem/index.js:39
>>         ...props } = this.props,
>>         ^
>> ParseError: Unexpected token

the code that triggers the error is

Running "exec:component_build" (exec) task

       build : resolved in 32ms
       build : files in 78ms
>>      error : Error: 
>> /Volumes/src/jsRouter/js/modules/ui-components/navItem/index.js:39
>>         ...props } = this.props,
>>         ^
>> ParseError: Unexpected token

**Comment by jsfb** [comment]
@mteichtahl - Just wanted to checkin regarding this issue.  Haven't heard anything in a few days; does that mean you got it working?  If you believe it's a bug in React, can you provide a simple example demonstrating the issue?

**Comment by mteichtahl** [comment]
Jim

Sorry I forgot to close this. It isn't a bug. I forgot to enable harmony in my transpiler. I'll close this out

**Comment by jsfb** [comment]
k, thanks.  Good luck on your app!
