### ISSUE TITLE
eslint react-hooks/exhaustive-deps rule should have fine grained ignores

### ISSUE THREAD

**Issue by jamiebuilds** [facebook/react#27873]
In the exhaustive deps eslint rule, it would be helpful if there was a way to ignore individual dependencies instead of completely disabling the rule.

For example, the following effect is only intended to fire when `shouldRing` changes. And we want to add a log when it calls `playRingtone()` to record the state at the time that it fired.

Right now disabling the rule is the only option:

```ts
const shouldRing = getShouldRing(connectionState, joinState)

useEffect(() => {
  if (shouldRing) {
    log.info('ringing', connectionState, joinState) // it's fine that we don't listen to these
    playRingtone()
    return () => {
      stopRingtone()
    }
  }
// eslint-disable-next-line react-hooks/exhaustive-deps
}, [shouldRing])
```

I can see two alternatives:

- Marking deps as ignored
```ts
useEffect(() => {
  // ...
}, [shouldRing, void connectionState, void joinState])
```
- Marking references as ignored
```ts
// I don't know how well this would work as comments can be hard to associate with the right AST nodes, and tools like eslint/prettier tend to mess with them
log.info('ringing', /* react-hooks/ignore */ connectionState, /* react-hooks/ignore */ joinState)
```

Personally I prefer the former, generally when you want to do this it's because you're actually trying to listen to very specific state/derived values, and for every other dep you'd be marking their changes as not important to the effect.

**Comment by souporserious** [comment]
+1 for using `void` as a heuristic.

It's still experimental, but [useEffectEvent](https://react.dev/reference/react/useEffect#reading-the-latest-props-and-state-from-an-effect) will solve this problem:
```js
const shouldRing = getShouldRing(connectionState, joinState)
const handleRing = useEffectEvent((shouldRing) => {
  if (shouldRing) {
    log.info('ringing', connectionState, joinState)
    playRingtone()
  }
});

useEffect(() => {
  handleRing(shouldRing)
  return () => {
    stopRingtone()
  }
}, [shouldRing])
```

Much nicer and succinct to have `void` as an option though.

**Comment by alex-r-bigelow** [comment]
I know this issue has been debated across many github issues, etc. for years at this point... (I THINK this one is the most recent?)

Yet another use case, if it's ever helpful:

```
// graph is an object from some library that we don't own,
// that mutates things internally; we want to update the
// memo both when it changes by reference, as well as when
// we know it has changed internally
const positions = useMemo(() => getNodePositions(graph), [
  graph,
  graph.editCount // extra dependency
]);
```

Currently, there's a really bad developer UX where we play a game of adding / temporarily removing `eslint-disable-next-line react-hooks/exhaustive-deps` when we want to debug + catch other **normal** dependencies in the same dependency list, where we already know something weird is happening.

FWIW, I lean more toward managing specific extra / missing dependencies with comments that can be configured; there's precedent in the way that `no-fallthrough` allows a `commentPattern`. Something like this would be awesome:

```
'rules': {
  'react-hooks/exhaustive-deps': ['error', {
    'omitCommentPattern': '\s*omitted\s+dependency:\s*(.*)',
    'extraCommentPattern': '\s*extra\s+dependency.*'
  }]
}
```

I agree with [many of the points that have been raised over the years](https://github.com/Kazumz/avoid-ignoring-exhaustive-deps) that you really should avoid disabling dependency checking (unless you absolutely have to). Comments would make us think about and document **WHY** there's a specific missing / extra dependency. It's probably a good thing if ugly hacks make the code ugly.

And making us mess with `eslint` configuration might add some nice **deliberate friction** to make us (and PR reviewers!) notice, stop, think, and discuss when something weird is going on.

**Comment by tresorama** [comment]
Much needed, 

Sometime for optimization we need to omit some dependencies.
The bug whith `eslint-disable-next-line react-hooks/exhaustive-deps` is that disable everything, so if tomorrow we add new code, eslint doesn't alerm us that we have a "new" missing dep.

I think a new eslint rule should exists for granular usage
```ts
useMemo(() => {
  return {
     some: 'stuff'
 },
 [
     prop1,
     // eslint-disable-next-line react-hooks/exhaustive-deps-single-dep
     prop2,
  ]
);
```
