### ISSUE TITLE
Help:How to call a child component's method from the parent component without changing any logic of the child component?怎么在不改变子组件任何逻辑的情况下，在父组件调用子组件的方法？

### ISSUE THREAD

**Issue by HandsomeLeft** [facebook/react#27874]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by snakeUni** [comment]
https://react.dev/reference/react/useImperativeHandle

**Comment by freeliujian** [comment]
useImperativeHandle

**Comment by rickhanlonii** [comment]
Yeah, as others said, https://react.dev/reference/react/useImperativeHandle

This issue tracker is for bugs though, for support questions try StackOverflow or one of the many online React communities.
