### ISSUE TITLE
[DevTools Bug]: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by safwanchundakkadan** [facebook/react#27875]
### Website or app

 Command PhaseScriptExecution failed with a nonzero exit code.

### Repro steps

showing error Command PhaseScriptExecution failed with a nonzero exit code.

When I am trying to play the ios project from a M2 chip Macbook Pro, it is working fine in Intel Chip.

showing error when trying to play from vscode--

The following build commands failed:

        PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/safwan/Library/Developer/Xcode/DerivedData/skizzlehr-aqdqtsvzpusqzbchycwsluqghbka/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00025130.sh (in target 'React-rncore' from project 'Pods')

(1 failure)

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
This looks like an issue with React Native, not React / React DevTools. Could you please open same issue in [React Native repo](https://github.com/facebook/react-native) with adding more context?
