### ISSUE TITLE
[DevTools Bug]: Hook parsing fails if a hook uses useSyncExternalStore

### ISSUE THREAD

**Issue by jamesbvaughan** [facebook/react#27889]
### Website or app

https://react-devtools-issue-demo.vercel.app/

### Repro steps

1. Open up this page: https://react-devtools-issue-demo.vercel.app/ (source: https://github.com/jamesbvaughan/react-devtools-issue-demo/blob/main/src/App.tsx)
2. Open up the React dev tools
3. Navigate to the Components tab
5. Observe in the right sidebar that hook name parsing fails for one of the two components.

---

Hook name parsing is _really_ helpful when debugging/optimizing large components with lots of hooks, and this issue makes that feature unusable on components whose hooks make use of `useSyncExternalStore`.

This is particularly painful for my current work, where nearly all components make use of [Zustand](https://github.com/pmndrs/zustand) stores, which use `useSyncExternalStore` internally.

---

This is the same symptom that folks are hitting in https://github.com/facebook/react/issues/24980, but I'm not sure whether the cause is the same for everyone there.

### How often does this bug happen?

Every time

**Comment by jamesbvaughan** [comment]
I've made a bit more progress investigating this.

I believe the cause might be the two calls to `nextHook` in `useSyncExternalStore`: https://github.com/facebook/react/blob/1d5667a1273386f84e416059af7b6aba069e068e/packages/react-debug-tools/src/ReactDebugHooks.js#L265-L274

To try to verify that, I found that just one other hook in that file, `useTransition`, also makes two calls to `nextHook`: https://github.com/facebook/react/blob/1d5667a1273386f84e416059af7b6aba069e068e/packages/react-debug-tools/src/ReactDebugHooks.js#L284-L292

I modified my test case to use `useTransition` rather than `useSyncExternalStore` and confirmed that it also causes hook parsing to fail.

**Comment by Ghanem10** [comment]
hey @hoxyq did you work on this?

**Comment by Nathan-Roberts123** [comment]
https://github.com/facebook/react/blob/1d5667a1273386f84e416059af7b6aba069e068e/packages/react-debug-tools/src/ReactDebugHooks.js#L56-L82

When i was trying to debug this problem i notice that here they didn't call the `useSyncExternalStore` and `useTransition` from `Dispatcher` so I add the line `Dispatcher.useSyncExternalStore(() => {}, () => {}, () => {})` above the line `Dispatcher.useMemo(() => null)` in above source code, and it worked fine. I don't know if this was intentionally or it a mistake.

**Comment by hoxyq** [comment]
> https://github.com/facebook/react/blob/1d5667a1273386f84e416059af7b6aba069e068e/packages/react-debug-tools/src/ReactDebugHooks.js#L56-L82
> 
> When i was trying to debug this problem i notice that here they didn't call the `useSyncExternalStore` and `useTransition` from `Dispatcher` so I add the line `Dispatcher.useSyncExternalStore(() => {}, () => {}, () => {})` above the line `Dispatcher.useMemo(() => null)` in above source code, and it worked fine. I don't know if this was intentionally or it a mistake.

Sorry for a late reply. Yes, this is required for generating stack frames of primitives, so this could be the root cause of why RDT can't find `useSyncExternalStore` hook.

@jamesbvaughan Thanks for providing the repro! Is someone interested in testing this solution against the repro and opening a PR?

**Comment by jamesbvaughan** [comment]
@hoxyq I can try to put together a PR this week.

**Comment by jamesbvaughan** [comment]
I've put put a PR: https://github.com/facebook/react/pull/28399

**Comment by kenlyon** [comment]
@hoxyq Could you advise when the DevTools Firefox Extension will be updated? This issue affects me and it's good to see that it's been fixed but my browser is stuck on v5.0.0 of the extension from December.

**Comment by hoxyq** [comment]
> @hoxyq Could you advise when the DevTools Firefox Extension will be updated? This issue affects me and it's good to see that it's been fixed but my browser is stuck on v5.0.0 of the extension from December.

I've uploaded v5.0.2 to Firefox store a week ago, its still pending review process.
