### ISSUE TITLE
Bug: Weird behavior of form when i set a state value within an onChange handler.

### ISSUE THREAD

**Issue by KighteW3** [facebook/react#27915]
React version: 18.2.0

## Steps To Reproduce

1. Wrap a form in a component (inside of the current component) and instantiate it on the jsx returned from the father component.
2. Bind the handler function to the form, within the onChange attr.
3. Create a state with the useState hook and set a new value when the onChange function handler is triggered.

Link to code example: [code example](https://codesandbox.io/p/sandbox/modest-ully-zhw7xt?file=%2Fsrc%2FApp.tsx)

## The current behavior

When i type anything or even interact with any input, the target dissipates and no value is stored in the input.
[Screencast from 2024-01-09 20-25-05.webm](https://github.com/facebook/react/assets/99749798/d4e439fb-aa1a-4fc6-a47a-2c5674c10bc4)

## The expected behavior

It should work as an usual form without re-rendering or dissipating the target.

**Comment by alakh0703** [comment]
The handleChange function is currently attached to the onChange event of the entire form. It would be more efficient to attach it to each input separately. It should work.

```
<input type="text" name="name" onChange={handleChange} />
<select name="prio" onChange={handleChange}>
          <option value={1}>1</option>
          <option value={2}>2</option>
          <option value={3}>3</option>
</select>
<input type="text" name="text" onChange={handleChange} />
```

**Comment by liwenkang** [comment]
When you type something and trigger `handleChange`
The state of the component <App/> changes, so it re-renders. So, <FormTo /> is also re-rendered.

**Comment by rickhanlonii** [comment]
This is expected. You're defining the FormTo component nested inside of the App component, like this:

```js
function App() {
  function FormTo() {
    return <form></form>
  } 
  
  return <FormTo />
}
```

That means whenever you update the state and App renders, the FormTo component is re-created, clearing the state of the form fields. Instead, you need to hoist the function out of App:


```js
function FormTo() {
  return <form></form>
} 

function App() {
  return <FormTo />
}
```

This is a known pitfall, check out the Pitfall section of the docs for nesting components here: https://react.dev/learn/your-first-component#nesting-and-organizing-components
