### ISSUE TITLE
use bundle-collapser plugin to reduce file size

### ISSUE THREAD

**Issue by huang47** [facebook/react#2792]
for all browserify tasks (min, addons-min) we can use bundle-collapser which replaces module name with numeric id and reduce file size

**Comment by zpao** [comment]
Done.

**Comment by kgryte** [comment]
The react docs recommend using this plugin (https://reactjs.org/docs/optimizing-performance.html#browserify). However, in our work, we have encountered non-unique ids. How have you managed to avoid this issue? https://github.com/substack/bundle-collapser/issues/20

**Comment by gaearon** [comment]
Sounds unfortunate. Can you file an issue so that we stop recommending it in the docs or find an alternative?

**Comment by rreusser** [comment]
Here's a full reproduction in vanilla react (no babel). I'll file a separate issue. https://github.com/rreusser/bundle-collapser-uniqueness-failure/tree/react

**Comment by rreusser** [comment]
I've filed a separate issue. See: #11049
