### ISSUE TITLE
Bug: Can't send ArrayBuffer to Server Action despite react.dev saying so

### ISSUE THREAD

**Issue by alfonsusac** [facebook/react#27931]
Can't send ArrayBuffer to Server Action despite [react.dev](https://react.dev/reference/react/use-server#serializable-parameters-and-return-values) saying that you can. I'm not sure if this is an error or my part or the documentation. I retrieved the arrayBuffer from file of formData, then pass it through the parameter of the Server Action.

It seems like it doesn't get sent to the server because it can't be parsed due to ArrayBuffer being serializable but not iterable. 

However this is somewhat confusing because you can attach File in FormData in the form of Blob and send it to the Server Action.

I understand that FormData is [handled separately](https://github.com/facebook/react/blob/0ac3ea471fbcb7d79bc7d36179e960c72c779e76/packages/react-client/src/ReactFlightReplyClient.js#L238) but I'm not sure I understand why it can't be done the same with ArrayBuffer.

I understand that I can just pass the FormData to send files but In my case I needed to transform the Files first before uploading and it ends up with a Blob. 

React version:

## Steps To Reproduce

1. Create form, input, submit button, and also onSubmit function using Client Action
2. Retrieve the arrayData from the formData then pass it to server action

Link to code example:

https://codesandbox.io/p/devbox/nextjs-arraybuffer-server-action-36gvxn

## The current behavior

Throws client-side error

## The expected behavior

ArrayBuffer gets sent to the server

The documentation:

<img width="583" alt="image" src="https://github.com/facebook/react/assets/20208219/6c082998-f1f1-4657-8131-f5df8620bc9b">

Please let me know if I fail to understand the documentation or if it's something wrong in the documentation

**Comment by alvgaona** [comment]
I'm having the same issue.

**Comment by duh2** [comment]
> I'm having the same issue.

Wokraround: I've tested multiple react/nextjs version combinations and now found working one. For me it's nextjs 13.5.6 and react 18.2.0. Reply pls when you try it out)

**Comment by alvgaona** [comment]
I will test. I'm using `nextjs@14.0.4` and `react@18.2`

**Comment by alfonsusac** [comment]
> > I'm having the same issue.
> 
> Wokraround: I've tested multiple react/nextjs version combinations and now found working one. For me it's nextjs 13.5.6 and react 18.2.0. Reply pls when you try it out)

The workaround i have for now is to wrap the data with FormData first and append the file before sending it to the server action

**Comment by vetan2** [comment]
It seems that shipping `FormData` as parameters of the server action is enabled, but returning `FormData` from the server action is still not enabled.

**Comment by alfonsusac** [comment]
> It seems that shipping `FormData` as parameters of the server action is enabled, but returning `FormData` from the server action is still not enabled.

as per the documentation, that is the intended behavior

**Comment by eps1lon** [comment]
They're supported as return values in Server Actions in React's Experimental release channel. Sending `ArrayBuffer` to Server Actions is currently not supported but we want to achieve parity eventually.

I'll file a PR updating the docs accordingly.

**Comment by sebmarkbage** [comment]
Will be supported by https://github.com/facebook/react/pull/28819
