### ISSUE TITLE
Elements with visible text labels do not have matching accessible names.

### ISSUE THREAD

**Issue by omarologyy** [facebook/react#27935]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

## The current behavior
Although this is considered an accessibility issue rather than a bug

## The expected behavior
Ensuring that visible text labels on elements like buttons and form controls match their associated accessible names using semantic HTML, proper labeling, and ARIA attributes for web accessibility.

**Comment by rickhanlonii** [comment]
We do support this, though sometimes it may require using [`useId`](https://react.dev/reference/react/useId#generating-unique-ids-for-accessibility-attributes). There's not enough info here to say exactly what isn't supported, but if you can provide some examples of what doesn't work, I can re-open and investigate.
