### ISSUE TITLE
add support for <formset>

### ISSUE THREAD

**Issue by Pomax** [facebook/react#2794]
adding a `<formset>` to a component with JSX causes the JSXTransformer to throw a `TypeError: erroneousLine is undefined` error. Taking it out and replacing it with a `<div>` makes the error vanish. Missing "formset" in a whitelist somewhere?

**Comment by spicyj** [comment]
Not sure what formset is. Perhaps you meant fieldset? If I'm being stupid let me know and I'll reopen.

**Comment by Pomax** [comment]
nope, totally had a brainfart and couldn't remember it was fieldset. cheers.
