### ISSUE TITLE
clarify when componentDidUpdate fires.

### ISSUE THREAD

**Issue by Pomax** [facebook/react#2796]
http://facebook.github.io/react/docs/component-specs.html#updating-componentdidupdate is unclear on when it is called with regards to the `render` function.

The docs state that it's "Invoked immediately after updating occurs" but it is unclear what is meant with updating in this case: it can refer to either the component as a whole updating (meaning post-render), or it can refer to setState() having been processed (which might mean pre-render).

It would be good to explicitly state when this function fires in its documentation (even if somewhere else on the site this is described in text or graphic form already).

**Comment by gaearon** [comment]
I think this part makes it clear it happens after DOM is updated (post-render):

> Invoked immediately after updating occurs. This method is not called for the initial render.
>**Use this as an opportunity to operate on the DOM** when the component has been updated.

However, overall I agree more descriptive (visual?) lifecycle explanation would be welcome.

**Comment by Pomax** [comment]
That's not clear enough, though. React does a good job making sure you normally don't work on the DOM, so in this case I really need explicit text that says "Use this as an opportunity to operate on the DOM after `render` has finished" - without that, it still entirely possible that it's offering a way to mess with the DOM *before* updates from subsequent render calls are worked in.

**Comment by gaearon** [comment]
>after `render` has finished

This wouldn't be entirely correct though. `render` doesn't do anything per se, it just builds the virtual DOM tree.

**Comment by spicyj** [comment]
componentDidUpdate (and componentDidMount) is always called after the DOM has been updated – we can update the docs. Want to send a pull request?

**Comment by Pomax** [comment]
I'll have to read through your CLA carefully before I can file any PRs. In the mean time, any clarification you deem addresses this issue is fine by me.

**Comment by zeusdeux** [comment]
@Pomax The fact that it lets you operate on the updated DOM implies that it's post-render.

**Comment by Pomax** [comment]
@zeusdeux sure, but I'd love to know you get that from the actual text, rather than from what you know about React by clearly being more familiar with it that a new user of React.

In this case three people went "it's after the DOM updates", so: sweet! Let's change the text from 
```
Invoked immediately after updating occurs. This method is not called for the initial render.
Use this as an opportunity to operate on the DOM when the component has been updated
```
to
```
Invoked immediately after the component's associated DOM gets updated. This method is not called for the initial render.
Use this as an opportunity to further operate on the DOM after the component has been updated
```
and now it's no longer implied, now it's explicit, and new users don't scratch their head going "what do they mean with updated? The tutorials mostly talk about updating in the sense of the state and props changing, but the text also talks about working on the DOM... this isn't clear enough".

**Comment by zeusdeux** [comment]
@Pomax looks like PR material to me :) :+1:

**Comment by Pomax** [comment]
indeed, and I'm not filing one until I've read that CLA. I have issues with CLAs, which is why I'm filing this as an issue instead, and hopefully other people working on the code find opening the docs file on github, hitting "edit", and dropping that in, not too much work.

**Comment by mbrowne** [comment]
As @flyingace pointed out, the clarification in the docs seems to have been reverted and this issue should be re-opened

**Comment by gaearon** [comment]
If there is an issue with documentation, please file it in the documentation repository: https://github.com/reactjs/reactjs.org. Then we or somebody else can address it. We're not reading closed issues (it's hard enough to keep up with open ones!) so your feedback is unfortunately going into the void. Thank you!
