### ISSUE TITLE
Bug: The solution for challenge 2 (Fix a retriggering animation) is an overkill. https://react.dev/learn/removing-effect-dependencies#challenges 

### ISSUE THREAD

**Issue by buptcaicai** [facebook/react#27984]
I think since the "show/remove" always destroy and recreate the "Welcome" component.  Simply remove the duration from useEffect dependency will solve the problem.

**Comment by caotrananhkhoa** [comment]
How to remove the `duration` from `useEffect` dependency when it is a reactive value?

**Comment by buptcaicai** [comment]
> How to remove the `duration` from `useEffect` dependency when it is a reactive value?

Just remove it from the dependency array of 'useEffect'. The real issue is that, theoretically, it is a reactive value, but effectively, it is not, because when the "welcome" component shows, it is always newly created. There is nothing to "react" to later, even when duration changes.

**Comment by caotrananhkhoa** [comment]
Lint can't believe that `duration` is a non-reactive value. Therefore, Lint will still throw an error if you don't add `duration` to `useEffect` dependency.

Because of that, React wants you to explicitly declare that it is not a reactive value by using `useEffectEvent`.

**Comment by rickhanlonii** [comment]
The purpose of this challenge is to show you how to fix it the correct way, and removing dependencies from the effect list is not the correct way. The solution is correct and is the reason we intend to add useEffectEvent.
