### ISSUE TITLE
Bug: Found an error on React Documentation Site

### ISSUE THREAD

**Issue by paulatanu1** [facebook/react#27986]
React version: Official Documentation site (`https://react.dev/learn/state-a-components-memory`)

## Steps To Reproduce

1. Go to `https://react.dev/learn/state-a-components-memory`
2. On right side menu section -> Click on **Adding a state variable** 
3. 3. see the image ->  ![image](https://github.com/facebook/react/assets/122859066/0217f9f4-9166-4796-8186-c58aec1911bd)
4. Go to the last by clicking on the Next button, and click on the Next button again.
5. You will see the error -> ![image](https://github.com/facebook/react/assets/76896592/e49b7b4d-1645-4134-80f8-94cedf01e986)

Link to code example:

## The current behavior
next button not disabled or handle the error

## The expected behavior
Need to Disable the Next button and then handle the issue, but also generate the previous button for go back.

**Comment by rickhanlonii** [comment]
This is intentional, because there's a challenge at the bottom to fix the crash. 

https://react.dev/learn/state-a-components-memory#challenges
