### ISSUE TITLE
just out of curiosity, why the latest version of task scheduler stop using requestAnimationFrame? Thanks for the answers~

### ISSUE THREAD

**Issue by jy90719** [facebook/react#27998]
recently i have been investigating the latest React source code, and i found there are some changes have been made in terms of task scheduling logic, and i am really curious about the reason under the hood. any answers would be appreciated very much!

**Comment by rickhanlonii** [comment]
There were perf issues that we tried to get around in https://github.com/facebook/react/pull/16166, but ultimately decided to just yield every 5ms in https://github.com/facebook/react/pull/16214 and that worked better than using rAF in our experiments. Check out those PRs for more info!

**Comment by dante01yoon** [comment]
Hi @rickhanlonii , sorry to surprise you but,  react doesn't use requestAnimationFrame anymore?

**Comment by rickhanlonii** [comment]
No, see the links above.
