### ISSUE TITLE
[DevTools Bug]: There is a problem with the scrollbar in https://react.dev/learn/  

### ISSUE THREAD

**Issue by anuj-pal27** [facebook/react#28035]
### Website or app

https://react.dev/learn

### Repro steps

in Learn react section below there are various headings like- describing the ui ,adding intereactivity when select one of them then scrollbar appears when try to hold this scrollbar is gets hide and when hover away from this scrollbar is reapears.
![Screenshot (25)](https://github.com/facebook/react/assets/39050816/f38c8878-ed5e-4885-a6d6-daac5d6e43a7)
![Screenshot (24)](https://github.com/facebook/react/assets/39050816/65dff2da-11ad-403c-a353-76a932ebcbb0)

### How often does this bug happen?

Every time

**Comment by Ivan-Ilyich** [comment]
Hi @anuj-pal27 , I came across the issue and I'm interested in working on it, could you assign it to me please?

**Comment by anuj-pal27** [comment]
yes you can do it @lvan-llyich

**Comment by anuj-pal27** [comment]
> Hi @anuj-pal27 , I came across the issue and I'm interested in working on it, could you assign it to me please?

yes you can do it @Ivan-Ilyich

**Comment by Ivan-Ilyich** [comment]
Thnaks @anuj-pal27 !
It's the first time I'll try to contribute to reactjs so it may take some time but I'll do my best.

**Comment by anuj-pal27** [comment]
yes ,it also my first time to open the issue of any repository . both of us has to do lot of work good luck @Ivan-Ilyich !!!!

**Comment by Ivan-Ilyich** [comment]
Thanks a lot, good luck to you too @anuj-pal27 !!

**Comment by mhassanch** [comment]
🚀 **Issue**: **main** element was overlapping the **SidebarNav** scroll area, causing the scrollbar to disappear when cursor moves to the scroll bar.

💡 **Solution**: I added a margin-left: -5 (ml-5) to the main element. This prevents the cursor from leaving the **SidebarNav** and resolves the issue.

🔍 **Screenshots**:
<img width="1680" alt="side-bar-1" src="https://github.com/facebook/react/assets/58620309/d1c097b4-1662-4b1b-ac2b-ad1ae1b82b4b">
<img width="1680" alt="side-bar-2" src="https://github.com/facebook/react/assets/58620309/f3e8004f-8dce-4255-a2ee-6447f2d3c9c6">
<img width="1245" alt="side-bar-3" src="https://github.com/facebook/react/assets/58620309/482e09da-2a59-43be-9b62-8192ce53ca27">

🤔 **Feedback**: I'm not a CSS pro, so if anyone has a better way, please share!

**Comment by mhassanch** [comment]
Also, it seems like this issue might not be related to this repository. I believe it should be registered on [react.dev](https://github.com/reactjs/react.dev/issues).

**Comment by BALASANTHOSH01** [comment]
I think it is not an issue; it is a method that they used to develop the UI.

**Comment by ritikbanger** [comment]
This does not appear to be a problem. Please specify which functionality is not performing as anticipated.

@anuj-pal27
