### ISSUE TITLE
Make default initial state of a component `{}`

### ISSUE THREAD

**Issue by simplyianm** [facebook/react#2804]
I find myself writing `getInitialState: function() { return {}; }` way too often. A lot of components wait for AJAX requests before setting any state variables, and doing this will make things much easier.

**Comment by gaearon** [comment]
I usually set these variables to null in this cases. Also serves as a kind of documentation.

I think React is trying to save some allocations here although not sure!

**Comment by syranide** [comment]
I'm going to :+1: @gaearon on this, explicitly setting the allowed state properties to `null` is good documentation and also an optimization (or two actually, reduce allocations and shadow classes). There has also been some mention (just mention) of only allowing to set state properties that exist, else throwing, which I think sounds like a great idea and another reason why you would want it to be explicit.

**Comment by gaearon** [comment]
>There has also been some mention (just mention) of only allowing to set state properties that exist, else throwing, which I think sounds like a really great idea and another reason why you would want it to be explicit.

I'd love if that was the case btw

**Comment by syranide** [comment]
@gaearon Speaking of the devil... https://github.com/facebook/react/pull/2805#issuecomment-68723101

**Comment by spicyj** [comment]
Yeah – if anything, we're going to warn when you add new properties to state that getInitialState didn't return.
