### ISSUE TITLE
Updating props of an element

### ISSUE THREAD

**Issue by tleunen** [facebook/react#2813]
I have a react component (A) which renders a component (B) which receives another component (C) as a one of its props, I need to update a props of the component B before rendering it. How can I do that?

I tried to access to `setProps` but it's not available. Maybe I'm not doing it right.

In component A, I have something like this:
```
render() {
    var compC = <C something="smth" />;
    return (
        <div>
            <B propC={compC} />
        </div>
    );
}
```
So in B, I'd like to access compC and update its props. I tried to do that but `setProps` is not available: `this.props.propC.setProps(...)`

I cannot move compC in B because it needs some other stuff from A that B doesn't need to know.

**Comment by tcoopman** [comment]
Is this what you want to do?

```
// in B
render() {
  var C = this.props.propC;
  return <C someProp={1+1} />;
}
```

**Comment by tleunen** [comment]
More something like this
```
render() {
     // put something in the props of propC
    // this.props.propC.setProps(...) // ? setProps is undefined
    return <div>{this.props.propC}</div>;
}
```

**Comment by tcoopman** [comment]
But can't you set the props via `<div><this.props.propC x=1 /></div>`. See this [fiddle](http://jsfiddle.net/kb3gN/8844/)

**Comment by tleunen** [comment]
Oh I see, in your example, your A is the class itself, that's why it works.
What if you need to put a props before?
Like in my example, what if Component A create C with a specific props, and then B has to get the prop and add something else to it before rendering it?

**Comment by tcoopman** [comment]
I don't think that's a good practice. Maybe check out http://facebook.github.io/react/docs/jsx-spread.html

I would probably pass C and the props of C as seperate components:

```
<B compC={C} propsC={propsOfC} />
```
then:
```
var props = this.propsC;
props.newProp = "new";
<div><this.props.compC {...props} newProp2="new2" /></div>
```

**Comment by tleunen** [comment]
Yeah, that's what I thought. I just changed my code to put C inside A instead of B to avoid having this issue.
