### ISSUE TITLE
IE8: invalid values for styles also throw errors

### ISSUE THREAD

**Issue by syranide** [facebook/react#2815]
```
> document.body.style.width = -1
  "Invalid argument."
```

Is this something we want to solve?

**Comment by zpao** [comment]
What do you mean by solve?

**Comment by syranide** [comment]
@zpao I mean solving like we've done with node properties in IE8 (enforcing types) or wrapping in a try-catch (perf though...). Or should we simply let IE8 error on invalid style values?

**Comment by gaearon** [comment]
We don't support IE8 anymore.
