### ISSUE TITLE
18.2.0/umd/react.development.js  not export use method

### ISSUE THREAD

**Issue by zhaoxm2016** [facebook/react#28155]
React version:
18.2.0
## Steps To Reproduce

https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.development.js

Does not export use method

**Comment by eps1lon** [comment]
`use` is currently only available in the [Canary release channel](https://react.dev/community/versioning-policy#all-release-channels): https://react.dev/reference/react/use
