### ISSUE TITLE
Access to private variables

### ISSUE THREAD

**Issue by janpaul123** [facebook/react#2817]
In my component I used a private member `this._renderedComponent`, not knowing that this was also used by React. Because I overwrote that variable, I got strange errors at completely unrelated points in time. It took a while to figure out that React itself used a private member of the same name, and that this was exposed inside the component.

Would it be useful to actually hide those variables? Or otherwise to mention them in the documentation, so it's easily findable?

**Comment by zpao** [comment]
I *think* these will be gone in 0.13 as we're hiding the internal instance from the public one. There are likely still a couple, though maybe we could consider double underscoring the React private things. cc @sebmarkbage

**Comment by spicyj** [comment]
Yeah, these are all gone now except `_reactInternalInstance` which will be gone if #2958 merges and isn't a likely name to conflict with anyway.

**Comment by janpaul123** [comment]
Wonderful! Thanks for the great work folks.
