### ISSUE TITLE
Name property is not defined for option in the animation color dropdown.

### ISSUE THREAD

**Issue by msftedad** [facebook/react#28205]
React version: 16.8.0

## Steps To Reproduce

1.Open [React Select (react-select.com)](https://react-select.com/home).
2.Navigate to the custom styles.
3.Navigate to 'Animation' dropdown.
4. Observe whether name property is defined for option in the animation color dropdown or not.

Link to code example:

[React Select (react-select.com)](https://react-select.com/home).

## The current behavior
Name property is not defined for option in the animation color dropdown.

## The expected behavior
Name should be define for option in the animation color dropdown.

**Attachments**
![Name not defined](https://github.com/facebook/react/assets/93735775/453f028f-49b8-48e8-ae7c-3184ca9945a3)

![screen reader behavior-react](https://github.com/facebook/react/assets/93735775/482ccef0-8317-4c7a-8bd0-79474e2f9a05)

https://github.com/facebook/react/assets/93735775/b315bfa3-dcad-4bf7-922e-242ca089b34d

**Comment by vijaygomathinayagam** [comment]
hi @msftedad, you may want to report this issue here
https://github.com/JedWatson/react-select
