### ISSUE TITLE
Bug: Removal of custom element property sets it to `null` rather than `undefined`

### ISSUE THREAD

**Issue by augustjk** [facebook/react#28203]
React version: experimental

## Steps To Reproduce

1. Set up a React project with `react@experimental` & `react-dom@experimental` which includes custom element property support.
2. Render a custom element with a property value provided as prop, then on a re-render remove that prop.

e.g.

```jsx
function App() {
  const [condition, setCondition] = useState(false);
  return (
    <>
      <button onClick={() => setCondition(c => !c)}>toggle</button>
      {condition ? <my-element foo={"foo"} /> : <my-element />}
    </>
  );
}
```

Link to code example:
https://stackblitz.com/edit/vitejs-vite-dz2rka?file=src%2FApp.tsx

## The current behavior

The value of the `foo` property on `<my-element>` will start off `undefined`. Toggling condition to `true` will set the property to `"foo"`, but subsequently toggling condition back to `false` will set the property to `null`.

## The expected behavior

I would expect the property to be `undefined`.

**Comment by augustjk** [comment]
I'm guessing the source of this is behavior is here:
https://github.com/facebook/react/blob/2efa38332adc1fc1500753d79fcba41a0197a7a6/packages/react-dom-bindings/src/client/ReactDOMComponent.js#L1776-L1783

**Comment by HermanBide** [comment]
do you still need help solving this issue ?

**Comment by augustjk** [comment]
@rickhanlonii I saw the update on the other big custom element issue about support coming in canary and next major. I just wanted to raise this particular issue so it might be looked at before custom element support gets a wider release.

**Comment by rickhanlonii** [comment]
Thanks for the ping @augustjk. 

Confirmed that this is the behavior, we'll need to do some more investigating before deciding what to do here.
