### ISSUE TITLE
[feat] I hope react supports two instructions r-if and r-for

### ISSUE THREAD

**Issue by 1057105012** [facebook/react#28204]
I think there is a reason for this. Although react provides the greatest flexibility based on js and provides the best support for complex pages, for simple needs, some less intuitive writing methods are often required. I think it supports something like <div r-if>xxx</div> is very good, but only these two are enough. If there are too many and provide scalable interfaces, it may violate the original intention of simplifying programming and fall into the trap of vue's complex instruction set. in a trap

**Comment by IVLIU** [comment]
React will not support it. Its jsx positioning is lightweight and universal.

**Comment by gsathya** [comment]
We'd prefer to express control flow in JavaScript, rather than adding new component types to model control flow. Closing as there aren't any plans to do this (unless we see new motivating data).
