### ISSUE TITLE
Bug: hot-reload not working with express

### ISSUE THREAD

**Issue by Muharax** [facebook/react#28231]
Hello everyone, has anyone ever had hot reload stop working? since yesterday it doesn't work in react when I'm connected to express. When express is OFF it works, and in another project it works despite the connection to the server
in this project I have the main Home page and it does not respond to changes hot-reload, loads the build directory, every time I need to do an npm run build
[https://streamable.com/fbqho6](https://streamable.com/fbqho6?fbclid=IwAR1gL78My6pcrBg6wBfpY1BHcnKLENhvCV2Vcx8FnU4WHisdXaGQdbeSb7c)
and when I run another project with the server express, it works
[https://streamable.com/377x81](https://streamable.com/377x81?fbclid=IwAR3LWxTuFEu_zhuY-VUDZL4oqJeDB7onxRpXhdL7xBLoin-kBfqt7Zo1Lr0)
I think it happened after uninstalling websocket.io but I'm not sure, I looked for solutions in Google but none of them work, I made a clean project and copied the files, installed the dependencies and still the same

**Comment by pwbriggs** [comment]
Hey there @Muharax! 👋

To help debug the issue you're experiencing, could you please create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating specifically what code triggers this bug?

Thanks!

**Comment by Muharax** [comment]
actually I don't know how it happened, I just uninstalled websocket.io from the main server file and moved it to a separate folder. For now, I solved it by creating a clean tsx project and moving file by file and installing dependencies one by one, and I changed the port for react 3000 and express 3001, it is possible that when react and express were on port 3000 an error appeared but I am not sure because it was before it worked

**Comment by gsathya** [comment]
Closing as there's not enough information to repro this. I double checked and fast refresh is working fine on a new project. Comment here if there's more information and we can take a look.
