### ISSUE TITLE
define functions inside Mixins

### ISSUE THREAD

**Issue by gsantome** [facebook/react#2825]
I love how Mixins works with some limitations like if we use getDefaultProperties inside a mixin then our component can't override a property into getDefatulProperties. But i'm having a bigger problem and i don't know if its ok or not... 

so this is my case:
```
var mixinTest = {
     function1: function() {
          console.log('test the function');
     }
}
```
and my component is:
```
var reactComponent = React.createClass({
     mixins: [mixinTest]
});
```

so now the parent who mount the reactComponent can't call reactComponent.function1() ... someone know why? or how to solve this problem?

Thanks

**Comment by chenglou** [comment]
That's because the mixin functions are just like those you attach on the component:
```js
var Comp = React.createClass({
  handleClick: function() {...}
});
```

You don't access them either from the parent with `Comp.handleClick` (what would that mean even? It'd be a static function and that's not what you want).

Here's how you can do it: http://facebook.github.io/react/tips/expose-component-functions.html
Note that this isn't specific to mixins. Your mixin's fine.

Closing! =)

**Comment by gsantome** [comment]
Thanks for your response... I'm still don't understand why if my component have a mixing when i use that component from the parent i can't access the functions that i have into my component, I know if not the best idea but its a little crazy what im making.
I will find a workaround for this.

Thanks

**Comment by gaearon** [comment]
>I'm still don't understand why if my component have a mixing when i use that component from the parent i can't access the functions that i have into my component

In your example `reactComponent` is not some specific component instance. It's a class, you can have many instances of it. By the way, convention is to use CamelCase for class names, so it should be `ReactComponent` instead.

e.g.

```js
// top level
var instance = React.render(<ReactComponent />, document.body); 
instance.function1();


// inside another component--have to use refs
var SomeOtherComponent = React.createClass({
  componentDidMount: function () {
    this.refs.myInnerComponent.function1(); // ref corresponds to instance
  },

  render: function () {
    return <div><ReactComponent ref='myInnerComponent' /></div>;
  }
});

React.render(<SomeOtherComponent />, document.body); 
```

However, this is *not* the way you normally “make things happen” in React. I have a codebase of hundreds of React components, and neither of them exposes any public methods. You should also try hard *not* to use `refs`, they're an escape hatch.

Instead, embrace top-down data flow and try top-level `state` updates drive changes in your application.

**[More About Refs](http://facebook.github.io/react/docs/more-about-refs.html)** warns you:

>If you have not programmed several apps with React, your first inclination is usually going to be to try to use refs to "make things happen" in your app. If this is the case, take a moment and think more critically about where state should be owned in the component hierarchy. Often, it becomes clear that the proper place to "own" that state is at a higher level in the hierarchy. Placing the state there often eliminates any desire to use refs to "make things happen" – instead, the data flow will usually accomplish your goal.

**[Thinking in React](http://facebook.github.io/react/blog/2013/11/05/thinking-in-react.html)** shows the proper way for components to communicate.

**Comment by gsantome** [comment]
Thanks @gaearon for your comments... It's true im overusing refs :)... i will start to spend more time and see how to replace it with States from now.

Thanks again for your time and your comments.
