### ISSUE TITLE
User is unable to select multi color options at once.

### ISSUE THREAD

**Issue by msftedad** [facebook/react#28268]
React version:16.8.0

## Steps To Reproduce
1.Open [React Select (react-select.com)](https://react-select.com/home).
2.Navigate to the welcome page.
3.Hit tab and navigate to 'Multi' dropdown.
4.Invoke it and hit enter on any color.
5.Verify whether User is able to select multi color options at once or not.

Link to code example:
[React Select (react-select.com)](https://react-select.com/home).

## The current behavior
Upon hitting enter on any color, dropdown is getting collapsed. So, user is unable to select the multi color options at once.

## The expected behavior
Dropdown should not get collapsed upon invoking any color.

**Attachment**
[unable to select multi options.webm](https://github.com/facebook/react/assets/93735775/bc314c2e-7e97-49e7-80e0-540f025f6269)

**Comment by pwbriggs** [comment]
Hey @msftedad, this doesn't seem to be an issue in React. Perhaps you meant to open this issue at [`JedWatson/react-select`](https://github.com/JedWatson/react-select/) instead?

**Comment by Raistar22** [comment]
Double-check the rendering logic to ensure that each color option's checked state is correctly reflected in the UI. If using checkboxes, make sure that the checked attribute is set based on the component's state

**Comment by rickhanlonii** [comment]
Yeah, React doesn't own react-select. Try reporting to react-select, or reducing to a bug using just React and I'll take a look.
