### ISSUE TITLE
Uncaught TypeError: Cannot read property '_mockedReactClassConstructor' of undefined

### ISSUE THREAD

**Issue by rogierschouten** [facebook/react#2828]
The error above has caught me twice now, and it's hard to debug.  Perhaps an extra check could make this less hard to debug.

This is the location where the error happens:

```javascript
function instantiateReactComponent(element, parentCompositeType) {
  var instance;

  if ("production" !== process.env.NODE_ENV) {
    ("production" !== process.env.NODE_ENV ? warning(
      element && (typeof element.type === 'function' ||
                     typeof element.type === 'string'),
      'Only functions or strings can be mounted as React components.'
    ) : null);

    // Resolve mock instances

    // ERROR OCCURS HERE BECAUSE type IS UNDEFINED:
    if (element.type._mockedReactClassConstructor) {

      // If this is a mocked class, we treat the legacy factory as if it was the
      // class constructor for future proofing unit tests. Because this might
```

The cause is always using an undefined variable in a JSX tag, like so:

```javascript
var OtherComponent=undefined;
mycomp.render = function() {
    return (<OtherComponent/>);
}
```

The reason I get this error is because I often forget that I export OtherComponent directly using 

```javascript
module.exports=React.createClass(...);
```
and then I import it like so

```javascript
var otherComponent = require("other-component");
var OtherComponent = otherComponent.OtherComponent;
```
which is wrong but not obviously so.

It would help very much to have an assertion on the first parameter of React.createElement() right away when it is called.

**Comment by gaearon** [comment]
I think this is covered by #2726 (via #2607)

**Comment by rogierschouten** [comment]
@gearon Yes I agree, thank you.

**Comment by zpao** [comment]
#2726 also got backported into 0.12.2 so you should be able to just update and see a warning.

**Comment by rogierschouten** [comment]
Nice @zpao, thanks for pointing that out.
