### ISSUE TITLE
We are not able to adjust the width of the column header via keyboard.

### ISSUE THREAD

**Issue by msftedad** [facebook/react#28291]
React version: 18

## Steps To Reproduce
1.Launch the URL https://codesandbox.io/p/sandbox/beautiful-feynman-pknyvw and sign in.
2.Tab till column header.
3.Observe that We are not able to adjust the width of the column header via keyboard.

Link to code example:
https://codesandbox.io/p/sandbox/beautiful-feynman-pknyvw

## The current behavior
 We are not able to adjust the width of the column header via keyboard.

## The expected behavior
We should be able to adjust the width of the column header via keyboard.

**Attachments**

https://github.com/facebook/react/assets/93735775/9d77cddf-1892-4616-916e-8ffbed552a5e

**Comment by abdelhakimrafik** [comment]
This is not a React-based issue. You are using a third-party library to render your table. Consider checking the library doc.

**Comment by rickhanlonii** [comment]
Yeah, as @abdelhakimrafik, this doesn't appear to be a bug in React. If you can isolate it to a React issue, I'm happy to reopen and take a look.
