### ISSUE TITLE
Bug: eslint-plugin-react-hooks still links to legacy.reactjs.org

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [facebook/react#28314]
~React~ `eslint-plugin-react-hooks` version: 4.6.0

## Steps To Reproduce

1. Visit https://www.npmjs.com/package/eslint-plugin-react-hooks
2. Click the [Rules of Hooks](https://legacy.reactjs.org/docs/hooks-rules.html#eslint-plugin) link

Link to code example: n/a

## The current behavior

The link points to https://legacy.reactjs.org/docs/hooks-rules.html#eslint-plugin

## The expected behavior

That page has a big _"This site is no longer updated. [Go to react.dev](https://react.dev/blog/2023/03/16/introducing-react-dev)"_ disclaimer on top. Doesn't exactly strike confidence in the lint plugin.

Could it link to https://react.dev/learn/editor-setup#linting instead?

**Comment by FaishalAnis** [comment]
To ensure proper functioning of the plugin, consider the following steps:
Install the eslint-plugin-react-hooks package if you haven’t already.
Add it to your ESLint configuration:
JSON

"plugins": ["react-hooks"],
"rules": {
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": "warn"
}
Make sure your ESLint package is version 5 or higher.

**Comment by JoshuaKGoldberg** [comment]
bump

**Comment by rickhanlonii** [comment]
This is updated on main and will get updated when we publish the next release.

**Comment by JoshuaKGoldberg** [comment]
Thanks!
