### ISSUE TITLE
Add support for itemref

### ISSUE THREAD

**Issue by mattheww-porch** [facebook/react#2831]
http://en.wikipedia.org/wiki/Microdata_%28HTML%29#Global_attributes

**Comment by zpao** [comment]
Are there any other microdata props we should know about?

We already support `itemProp` `itemScope` `itemType` as they are specified on http://schema.org/docs/gs.html. `itemref` doesn't appear anywhere on schema.org, so if there's some other spec with other `item*` props, please let us know.

**Comment by spicyj** [comment]
Fixed by #3022.
