### ISSUE TITLE
Bug: Undo/Redo not behaving as expected for controlled input when state is updated from an async callback

### ISSUE THREAD

**Issue by VektorTech** [facebook/react#28369]
Undo/Redo doesn't work correctly inside controlled input when its value is updated from an asynchronous callback or indirectly from its `onChange` handler.

React version: 18.1.0 & 18.2.0
Chrome 122.0.6261.49 (arm64)

Link to code example: 
1. https://stackblitz.com/edit/react-gtqvnu?file=src%2FApp.js
2. [codesandbox.io](https://codesandbox.io/p/sandbox/modest-dirac-n73zdf)

## Steps to reproduce
1. Navigate to either of the above links
2. Focus the input and enter some random text
3. Try undoing the changes (CMD+Z or Ctrl+Z or Edit>Undo)
4. Now notice that the value remains the same

## The current behaviour
Hitting CMD+Z doesn't fire the `onChange` event. Hitting it several times in succession may eventually bring the caret to the start of the input and sometimes appends the previous value onto the current value, eg.: `this is a testthis is a te`.

## The expected behaviour
Replace current value with previous value before last interaction with input.

**Comment by pwbriggs** [comment]
I'm seeing the same behavior in Chrome 123.0.6300.3. and Edge 121.0.2277.128. In Firefox, <kbd>ctrl</kbd>+<kbd>Z</kbd> has no effect, even when pressed multiple times.

I sanity-checked each of those browsers with a [plain HTML `<input>`](https://codesandbox.io/p/sandbox/react-28369-vanilla-repro-77kmkn)&mdash;<kbd>ctrl</kbd>+<kbd>Z</kbd> works as expected.

**Comment by rickhanlonii** [comment]
The `setTimeout` breaks the controlled input, remove the `setTimeout` and undo/redo work as expected. If you need this to work, you'll need to implement undo/redo within the component yourself.
