### ISSUE TITLE
Bug: Despite having implemented optimizations such as shouldComponentUpdate or PureComponent

### ISSUE THREAD

**Issue by WonderLand33** [facebook/react#28406]
React version:

## Steps To Reproduce

am currently working on a complex React project, which uses several components with a large number of children. However, I have noticed that the performance of the app has been significantly impacted by the rendering of these components.

Despite having implemented optimizations such as shouldComponentUpdate or PureComponent, the performance is still far below what I would expect. Even scrolling becomes slow and laggy.

I was wondering if there are any best practices or recommendations for optimizing the rendering of complex components in React? Are there any common mistakes that I might be making that could be causing these performance issues?

Any advice or suggestions would be greatly appreciated.

Thanks in advance!

Link to code example:

**Comment by rickhanlonii** [comment]
Unfortunately, this issue tracker is for reporting bugs in React, and is not a support forum for using React. We want you to find the answer you're looking for, so we suggest posting one of the Community Forums: https://react.dev/community

**Comment by sennymunoz** [comment]
Ok On Feb 22, 2024, at 11:13 PM, Ricky ***@***.***> wrote:﻿
Closed #28406 as completed.

**Comment by sennymunoz** [comment]
What we Talkin bout

**Comment by sennymunoz** [comment]
What does this do

**Comment by sennymunoz** [comment]
No anso

**Comment by sennymunoz** [comment]
???

**Comment by sennymunoz** [comment]
So you can’t tell me
