### ISSUE TITLE
Bug: Use useId function to generate dom id,it can't use document.querySelector function.

### ISSUE THREAD

**Issue by Zywz95** [facebook/react#28404]
React version:18.1.0

## Steps To Reproduce

1.```import {useId} from 'react' <div id={useId()}></div>```
2.```document.querySelector('#:r1:')```

Link to code example:https://codesandbox.io/p/sandbox/hardcore-williams-yzyvqv

## The current behavior
Failed to execute 'querySelector' on 'Document': '#:r1:' is not a valid selector.

**Comment by pwbriggs** [comment]
Hey there @Zywz95! 👋

I'm not sure I understand the problem you're experiencing. Can you tell me

1. What do you expect to happen?
2. Why are you trying to use `document.querySelector` directly? Is it possible to write the logic within the component itself (perhaps within an effect)?

I can't seem to access your Code Sandbox repro, maybe you need to change its permissions to publicly viewable?

Thanks! ❤️

**Comment by bonelessgalaxy** [comment]
Hi @Zywz95, I think you're running into the same issue as #27553
It's because the reserved character `:` has special meaning in CSS for [pseudo-classes](https://developer.mozilla.org/docs/Web/CSS/Pseudo-classes) and needs to be escaped.
Thankfully, there's a [built-in method](https://developer.mozilla.org/docs/Web/API/CSS/escape_static) for this: `CSS.escape(selector: string)`.

Something like this should work for your case!
```js
document.querySelector(`#${CSS.escape(":r1:")}`)
```

**Comment by pwbriggs** [comment]
@bonelessgalaxy: true.

That said, @Zywz95, be careful about hardcoding the value `:r1:`&mdash;there's no guarantee that `useId` always return that. I'd do something more like this:

```jsx
import { useEffect, useId } from "react";

function MyComponent() {
  const id = useId(); // 👈 Put it in a variable

  useEffect(() => {
    const element = document.querySelector(`#${CSS.escape(id)}`);
    // Do something with `element`
  }, [id]);

  return <div id={id}>Hello world!</div>;
}
```

**Comment by Zywz95** [comment]
@pwbriggs @bonelessgalaxy 
Thank you for your answer. I have now fixed my CodeSandbox link to be publicly accessible, which indeed can solve my problem. What I am expecting is that the ID generated directly by the useId method should not need escaping and can be used directly. Although this approach does solve my problem, I still believe there are compatibility issues because using the character ':' in a DOM ID is not a common practice. Regardless, thank you for your response.

**Comment by pwbriggs** [comment]
Yeah, I agree the `:` makes everything more complicated. There's an ongoing discussion about this at #26839, so I think we can close this issue.
