### ISSUE TITLE
onClick events in components inside forms fire when they shouldn't.

### ISSUE THREAD

**Issue by eldh** [facebook/react#2840]
I was making a form and had a component with an onClick event. When placing the cursor in an input field in the form and pressing enter, the onClick event of the other component fires. Feels very random.

Am I doing something wrong or is this an actual bug?

This jsbin illustrates the problem: http://jsbin.com/motuso/2/edit?js,console,output

**Comment by brigand** [comment]
Looks like a bug.  

CS -> JS, tabs -> spaces, and 0.11 -> 0.13pre: http://jsbin.com/zipilezuqu/3/edit

**Comment by eldh** [comment]
Yep, that solves it. Thanks!

**Comment by af7** [comment]
I do not know if it is similar, I have this code in my JSX:

<button onClick={localStorage.removeItem("localData")}>Clear Local Storage</button>

It appears that this fires always, not if i click. Whenever I refresh the page, the "localData" disappears from the localStorage (without hitting the button).

I noticed that if I do this (in ES6), it works:

<button onClick={() => localStorage.removeItem("localData")}>Clear Local Storage</button>

Is this a bug OR expected? And if expected, why?

Thanks.

**Comment by spicyj** [comment]
Expected. The former is equivalent to

```
var handler = localStorage.removeItem("localData");
<button onClick={handler}>Clear Local Storage</button>
```

Note that the `removeItem` call runs immediately upon render, *not* when you click the button. You want to pass a function that gets called instead. You can do this with an arrow function (as you saw), a regular function like `onClick={function() { localStorage.removeItem("localData"); }}`, or a method like `onClick={this._removeData}`.

**Comment by af7** [comment]
Excellent explanation, thank you!

**Comment by vipin8169** [comment]
how to do this in coffeescript? what is the equivalent syntax for this?
