### ISSUE TITLE
Maven Plugin available?

### ISSUE THREAD

**Issue by mpetersen** [facebook/react#2841]
Hello,

is there a Maven plugin available to integrate JSX precompilation to the build process?
I've seen that there is a Gradle plugin, so would anyone recommend using Gradle instead of Maven to solve this?
Personally, I currently prefer Maven (still), and until now it was sufficient for all my projects.

Kind regards,
Moritz

**Comment by kahwee** [comment]
I use Maven too. We use this successfully: https://github.com/eirslett/frontend-maven-plugin

This makes Maven installs Node.js and you can install `gulp` through this. The build process includes a gulp script that runs browserify to compile the JSX through `reactify`.

**Comment by zpao** [comment]
We have no explicit support but as @kahwee mentioned, there are integrations with maven in the JS ecosystem that can integrate with react transforms.
