### ISSUE TITLE
RSS feed for the blog

### ISSUE THREAD

**Issue by vanillajonathan** [facebook/react#28429]
Please add a RSS feed for the blog at https://react.dev/blog

**Comment by lukahartwig** [comment]
Should probably open an issue here https://github.com/reactjs/react.dev/issues

**Comment by pwbriggs** [comment]
Duplicate of reactjs/react.dev#5700. @vanillajonathan can you please close this issue in favor of that one?

**Comment by vanillajonathan** [comment]
My bad.

**Comment by rickhanlonii** [comment]
RSS Feed is available here: https://react.dev/rss.xml
