### ISSUE TITLE
Keep or Drop replaceState?

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2843]
This is continuing the conversation started in #2805

We're considering dropping replaceState because ideally state should always keep a consistent signature, defined by getInitialState.

**Comment by bogdan-dumitru** [comment]
On the immutability note, I've started using fluxy which uses mori internally for store states and I've started using object subtrees of the store as state in components (like a cursor) and the component listens to changes in the store under it's cursor's key array scope. Then we get ``O(1)`` diffs in ``shouldComponentUpdate``; when the store changes and we just replace the state with the new "cursor".

It's working pretty well and I'd hate to lose this :). But at the same time if you're planning on supporting something like Immutable.Record it might be cool (fluxy is working on abstracting the immutable data structure implementation to support immutable.js). But to be honest tying React into a specific implementation of immutable data kinda defeats the purpose when it comes to modularity and so on. Maybe if there are some hooks that allow you to plugin what you use wether it is immutable.js or mori.

**Comment by chenglou** [comment]
A bit out of loop but, if state is `{a: 1, b: 2}`, is setting it (merging it) `{b: 3}` still gonna work? I can see it being convenient for a long time to come, but if we go immutable, I'd rather return the whole state object: `setState(state.updateIn(path, val))`. Avoids a merge and uses structural sharing as much as possible.

I'm against whatever custom `merge` mechanism mentioned in the other issue though. Don't think it's needed with the above solution.

**Comment by brigand** [comment]
The main place I use/see use of replaceState is when you've already done the merge, and while setState would work the same, it's also inefficient.

```js
var state = update1(this.state);
state = update2(state);
this.replaceState(state);
```

This pattern tends to arise from react's inability to queue immutable updates.

```js
this.setState({foo: update1(this.state.foo)});

// setState is async, so this would throw out the above changes
this.setState({foo: update2(this.state.foo)})

// when doing async things, the final state depends on batching strategy, and unless
// batching strategy is nextTick, race conditions
asyncThing(() => {
    this.setState({foo: update3(this.state.foo)})
});

// vs a hypothetical safe variant
this.enqueState({foo: update1});
this.enqueState({foo: update2});
asyncThing(() => {
    this.enqueState({foo: update3});
});
```

**Comment by syranide** [comment]
> We're considering dropping replaceState because ideally state should always keep a consistent signature, defined by getInitialState.

I've always loved that idea, but I don't think it negates the value of `replaceState`. However, requiring calls to `replaceState` to provide the full state would surely not make it very practical... so it's not entirely obvious how you would keep useful without ruining a part of its appeal.

**Comment by sebmarkbage** [comment]
Presumably an engine with hidden classes can do an optimization for `Object.assign(a, b, c);`

```
if a is fresh empty object
  and hiddenClassOf(b) === hiddenClassOf(c)
    then memcpy(a, c)
```

`this.replaceState` with a mutable object may be dangerous so I think we'd ideally clone and freeze any such objects anyway. We already do this with props in createElement.

**Comment by spicyj** [comment]
Closing in favor of #2843, I guess.

**Comment by spicyj** [comment]
Er, #3236.
