### ISSUE TITLE
allow template strings for attributes in jsx

### ISSUE THREAD

**Issue by monsanto** [facebook/react#2845]
It'd be cool if ```<div className=`myClass ${class1} ${class2}` />``` worked, instead of having to wrap the template string with `{}`.

**Comment by zpao** [comment]
Can you propose this in https://github.com/facebook/jsx/? The backtick is not a part of the spec we wrote there so we can't even implement it until it's there. Let's revisit this then.

**Comment by monsanto** [comment]
done https://github.com/facebook/jsx/issues/25
