### ISSUE TITLE
New hook: useMemoWithPrev

### ISSUE THREAD

**Issue by bambalic** [facebook/react#28465]
Sometimes you may need access to previous/last value of useMemo hook. Something similar is available when we set state (useState hook).

Some use case would be:

```
// current useMemo
const memoValueWithUseMemo = useMemo(() => {
  const shouldGetReevaluated = someExpensiveOperation(dep1, dep2, dep3);
  const otherStuff1 = getOtherStuff1(dep1);
  const otherStuff2 = getOtherStuff2(dep2);
  const otherStuffN = getOtherStuffN(dep3);

  return { shouldGetReevaluated, otherStuff1, otherStuff2, otherStuffN };
}, [dep1, dep2, dep3]);

```

I am suggesting something like this:

```
const memoValueWithUseMemoWithPrev = useMemoWithPrev(
  (prev) => () => {
    // additional prev value is available
    // evade expensive operation
    if (prev.shouldGetReevaluated) {
      return prev;
    }
    const shouldGetReevaluated = someExpensiveOperation(dep1, dep2, dep3);

    const otherStuff1 = getOtherStuff1(dep1);
    const otherStuff2 = getOtherStuff2(dep2);
    const otherStuffN = getOtherStuffN(dep3);

    return { shouldGetReevaluated, otherStuff1, otherStuff2, otherStuffN };
  },
  [dep1, dep2, dep3],
);

```

The hook itself would be something like this:

```

const useMemoWithPrev = (calculateValueFunction, dependencies) => {
    const prev = useRef({});

    const memoValue = useMemo(calculateValueFunction(prev.current), dependencies || []);
    prev.current = memoValue;
    return memoValue;
  };

```

Difference is that we would need to pass function that returns function, but that's it.
It probably couldn't be done by updating current useMemo because useMemo can be used to memoize higher order functions, so difference in callback we pass to it cannot determine whether we want to use it with previous value or not.

If we have this we could skip even more calculations than we are already skipping with useMemo.

Yes, this can be done by adding the same thing to our code, but it would be cool to have this in react.

**Comment by ZilvinasAbr** [comment]
I think this hook should be something implemented outside React since usage of this custom hook feels like is niche case and since it looks like it is possible to implement this custom hook without any changes to the React itself.

**Comment by ZilvinasAbr** [comment]
I'm not sure how this suggestion would also work out with _soon-to-be-released_ React Compiler: essentially usages of `useMemo` in probably most cases will not be necessary.

**Comment by josephsavona** [comment]
Thanks for posting! I'm going to close because this can be achieved with useState.

**Comment by rjgotten** [comment]
> I'm going to close because this can be achieved with useState.

FWIW - that's a solidly unconvincing argument given that `useState` itself exists and can be achieved with e.g. `useReducer`.
It's a matter of degrees of convenience - not a binary.

**Comment by bambalic** [comment]
Didn't have time to comment other opinions so let's do that now.

First, @ZilvinasAbr if you look it that way then a lot of things could be done outside of react but have actually become part of react. The use case for this is there, just people are handling it in different ways (in some cases not handling at all because of different reasons - usually lack of knowledge). This is something that wouldn't break anything that is already there but would also help the others that need this functionality.

I completely agree with last comment of @rjgotten, I would comment something similar before if I had time to do it. If we say that this can be already achieved with useState (which it could but then we would add additional render when setting that last/current state from useMemo). But even if there is no overhead like that that is somewhat bad argument. Because, how then useMemo exists or even useCallback? useCallback is just specific useMemo. With your reasoning we shouldn't have any of this in react because all of this could be implemented with useState and useEffect.

**Comment by rjgotten** [comment]
I still see the value in extending `useMemo` with an optionally consumed previous-value argument.
It's near 100% analogeous to the previous-state syntax of `useState`'s setter; i.e. there is precedent and alignment within the existing framework.

set state:
```js
const [foo, setFoo] = useState(0);
//...
setFoo(prev => prev + 1);
```

And with use memo:
```js
const memodDate = useMemo(prev => {
  const date = computeDateBasedOnDependency( dep );
  
  // Solves the problem with value objects such as `Date` and everything in React using `Object.is`.
  // No-- this is not something compiler trickery to auto-memo could solve. Because it can't know
  // about custom types.
  return prev && +prev === +date ? prev : date;
}, [ dep ]);
```

**Comment by ZilvinasAbr** [comment]
> I still see the value in extending `useMemo` with an optionally consumed previous-value argument. It's near 100% analogeous to the previous-state syntax of `useState`'s setter; i.e. there is precedent and alignment within the existing framework.
> 
> set state:
> 
> ```js
> const [foo, setFoo] = useState(0);
> //...
> setFoo(prev => prev + 1);
> ```
> 
> And with use memo:
> 
> ```js
> const memodDate = useMemo(prev => {
>   const date = computeDateBasedOnDependency( dep );
>   
>   // Solves the problem with value objects such as `Date` and everything in React using `Object.is`.
>   // No-- this is not something compiler trickery to auto-memo could solve. Because it can't know
>   // about custom types.
>   return prev && +prev === +date ? prev : date;
> }, [ dep ]);
> ```
> 
> Closing this issue unanswered is shortsighted and a mistake.

It would be best if someone from React core team would answer regarding this suggestion, but from my understanding of React and from reading the latest docs, `useMemo` should only be used as a performance enhancement hook and not something with some extra logic.

E.g. from docs:
"You should only rely on useMemo as a performance optimization"
https://react.dev/reference/react/useMemo#:~:text=You%20should%20only%20rely%20on%20useMemo%20as%20a%20performance%20optimization.

So I'm not sure the idea of passing previous useMemo calculated value as parameter to the `useMemo` function would adhere to these React practices. 

Another issue with `prev` parameter: in development the `useMemo` function is called twice (in Strict Mode) to find any possible impurity issues (https://react.dev/reference/react/useMemo#my-calculation-runs-twice-on-every-re-render). From my understanding, this might even happen in Production in some cases (e.g. when reopening the website in an old tab that was cleaned up by the Browser to save on RAM). So essentially, React in StrictMode would expect `useMemo` to return the same calculated value both times. But with `prev` argument this could become a bit complex:

1. On first render, `useMemo` function would get called with `prev` as `undefined`. Some calculated value would get returned.
2. Then, the `useMemo` function would need to get called again. But should it get called with `prev` as `undefined` or as the previously calculated value?
  - If `prev` as `undefined`, then the impurity issue shouldn't rise. But it could be confusing as to why the `useMemo` wouldn't use the `prev` value that was just calculated when called in StrictMode.
  - If `prev` would be called with previous value, then the issue could potentially happen that  `useMemo` has been called with the same dependeny array argument values, but with a different calculated value result, which would defeat the purpose of this extra call in Strict Mode to find impurities.
