### ISSUE TITLE
React Wiki: module react-growable-textarea

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react#2848]
https://github.com/mschipperheyn/react-growable-textarea

Suggestion for the components wiki. My first attempt at a React component. Feedback welcome.

**Comment by browniefed** [comment]
You can just add it. [https://github.com/facebook/react/wiki/Complementary-Tools/_edit](https://github.com/facebook/react/wiki/Complementary-Tools/_edit)

**Comment by chenglou** [comment]
^ What he said, neat component =)
