### ISSUE TITLE
Bug :  Application crashes in Navigating reference  pages

### ISSUE THREAD

**Issue by ankityadav7420** [facebook/react#28484]
React version:  react@18.2.0

## Steps To Reproduce

1. Open the react dev reference page
2. Navigate to Hooks
3. Choose `use` hooks, it crashes the application
<img width="1680" alt="Screenshot 2024-03-04 at 11 22 55 AM" src="https://github.com/facebook/react/assets/54978121/4d456cd7-b2a2-4b23-8353-f2f80fd236bd">

## The expected behavior
* It should Generally navigate to next route and content displayed

## The Un-expected behavior
* Application crashes

**Comment by pwbriggs** [comment]
Hey @ankityadav7420! 👋 

I can't reproduce this error. See the screencast below. It looks like you have some browser extensions installed, can you disable them and try again?

https://github.com/facebook/react/assets/146312751/54c1c302-c160-4059-95c4-9ce1e03a85db

Thanks! ❤️

**Comment by Suraj-Upadhyay** [comment]
Nope, cannot reproduce this. Can you share your browser version and the logs in text format?
