### ISSUE TITLE
Save component back references in dev mode

### ISSUE THREAD

**Issue by jimfb** [facebook/react#2849]
For the purposes of providing dev-tools support and providing back traces in error messages/warnings, it might be useful to keep back references to a component's parent.  This trace information will cut down the amount of time required to find the component(s) responsible for throwing warnings.

**Comment by gaearon** [comment]
While we're at it, can we have something like `$0` in React DevTools?
(If you're not aware, `$0` in Chrome console returns currently selected element in Elements tab.)

**Comment by jimfb** [comment]
My current thinking is that this should be rolled into the devtools (via a new devtools api) instead of in the core.  Closing.
