### ISSUE TITLE
Bug: server actions cannot be cancelled or given abort signals

### ISSUE THREAD

**Issue by AaronFriel** [facebook/react#28511]
React version: 18.2.0

## Steps To Reproduce

1. As in #28510, create a server action that has some long-running delay, e.g.: to simulate a large language model call.
2. There is no API on the client or server to trigger cancellation, or to detect or handle the client navigating away from the page.

Link to code example: https://codesandbox.io/p/devbox/next-14-0-3-forked-7q86s7?file=%2Fapp%2Factions.ts%3A4%2C18&workspaceId=958ee911-ec8f-4ca3-9ce1-668005ecaeb8

## The current behavior

When a long-running request is fired, the server will complete it regardless of client behavior, e.g.: client hangup.

## The expected behavior

An API for server actions to obtain a reference to an AbortController (or similar API) for the request, perhaps via async local context.

An API for clients to signal cancellation of a server action, perhaps via an additional return value on `startTransition`, perhaps as part of the transition APIs. If a transition is explicitly created, there should be a mechanism to cancel it.

**Comment by Gaurav896260** [comment]
hey,
To achieve the expected behavior, you would need to implement a mechanism on the server-side to handle this. One common approach is to use a unique token for each request. The client sends this token with each request, and if the client disconnects, it sends a cancellation request with the same token. The server then checks for cancellation requests with the same token before and during the processing of the request.



![Screenshot 2024-03-10 152106](https://github.com/facebook/react/assets/122368972/b8853089-aaf6-4ba2-9b8a-1ab64a5a7a58)

**Comment by AaronFriel** [comment]
I don't think that seems like a reasonable solution, as it relies upon:
* Follow-up requests being routed to the same server as the original request
* Infrastructure to store and poll/react to cancellation tokens globally, i.e.: redis.

Both of those seem pretty absurd, given that fetches can be aborted, the client can hang up the request. It should be possible to react to that.

**Comment by C-mbai** [comment]
+1 Please

**Comment by Saran33** [comment]
It could be possible to set a cancellation token in redis for a requestID and continually poll redis to check if it's cancelled before parsing each message chunk. That way, it wouldn't matter where follow-up requests are routed, but as mentioned above, that seems like an absurd amount of complexity, not to mention overhead, for something so trivial with fetches

**Comment by andreas-karlsson** [comment]
It would be nice to have a solution for this. But I guess it's tricky to get right. The underlying server function implementation in React can notice if the request is closed prematurely, but how to get this into the API in a nice way? One solution would be allowing _one and only one_ AbortSignal in the arguments of a server function. The client side would pass the signal to the fetch call and the server would construct a new signal that triggers on premature close. This wouldn't allow for a custom abort reason though.

I guess a more generic alt. would be to just implement a serialization scheme for AbortSignals through chunked encoding. I.e. the client sends the server function args replacing any AbortSignal with a reference. As long as the request is open the client can send more chunks specifying a reason for triggering one of the signals. Then it would be up to the server function to actually abort the request by throwing.

**Comment by andreas-karlsson** [comment]
Looking through react-server/client I realize the above (streaming serialization of server function args) is already implemented, so can't we just have AbortSignals be part of the serializable set? It's quire well defined isn't it?
