### ISSUE TITLE
Bug: Property 'inputType' does not exist on type 'Event'

### ISSUE THREAD

**Issue by dehoward** [facebook/react#28517]
React version: 18.0.0

## Steps To Reproduce
<img width="458" alt="image" src="https://github.com/facebook/react/assets/52973358/5beea44e-13b6-4653-8b0d-88496e63bd82">

create an `onChange` handler for an `input` and try to access `event.nativeEvent.inputType`

Link to code example:

https://playcode.io/1790904

## The current behavior
Doesn't allow type

## The expected behavior
Should allow property access

**Comment by HermanBide** [comment]
can i work on this if it has not been assigned to anyone?

**Comment by HermanBide** [comment]
@dehoward  @yezhonghu0503  I dont see the the object you are passing in the onclick function but im guessing the inputType key is present. looks like you are trying to get the key-value pair but its not directly available. i would write a condition to check if the inputType property exists before accessing it. Here's how you can modify this code. 

```
import React from 'react';

export default function App() {
  const handleChange = (event) => {
    if (event.nativeEvent && event.nativeEvent.inputType) {
      console.log(JSON.stringify(event.nativeEvent.inputType));
    } else {
      console.log('inputType property not available');
    }
  };

  return (
    <div className='App'>
      <input onChange={handleChange} />
    </div>
  );
}
```

**Comment by apurvak3** [comment]
I guess we have to ensure  that the event object is of the correct type (InputEvent) before accessing the inputType property.
