### ISSUE TITLE
Source is not showing

### ISSUE THREAD

**Issue by sai-kola** [facebook/react#28544]
if I select any component is should show source of that component but it is showing it in bundle I need source of that component 
I have attached the SS check last line ,what can i do to  get source, not in bundle source 
 ![Screenshot (6)](https://github.com/facebook/react/assets/59258771/ca67540a-18f4-48b2-b60a-7ed06b6441e2)

**Comment by sai-kola** [comment]
should i need to do any change in setting to get actual source not source in bundle.js

**Comment by sai-kola** [comment]
How to do source maps

**Comment by KinIcy** [comment]
I'm facing the same issue in my Next.js project. It by default exposes the source map on dev mode.

![image](https://github.com/facebook/react/assets/10891866/7dfe71e0-55ae-45eb-a181-cc84ece4524c)

the file name is right but the line/column is wrong, 

Also, it is not picking up the file/position for styled-components:

![image](https://github.com/facebook/react/assets/10891866/ff222a02-08fc-4115-864d-459f80a9443d)

**Comment by pwbriggs** [comment]
@KinIcy, did you try https://github.com/facebook/react/issues/28544#issuecomment-1991591646 above?

**Comment by KinIcy** [comment]
> @KinIcy, did you try [#28544 (comment)](https://github.com/facebook/react/issues/28544#issuecomment-1991591646) above?

yes, I verified my Next.js setup and it should be exposing the source maps by default. Or at least that is what the Sources tab says in Chrome:

![image](https://github.com/facebook/react/assets/10891866/97f76a97-c543-4299-9229-ed2da6af7c90)

**Comment by shreeyansh-mesh** [comment]
> > @KinIcy, did you try [#28544 (comment)](https://github.com/facebook/react/issues/28544#issuecomment-1991591646) above?
> 
> yes, I verified my Next.js setup and it should be exposing the source maps by default. Or at least that is what the Sources tab says in Chrome:
> 
> ![image](https://private-user-images.githubusercontent.com/10891866/312604836-97f76a97-c543-4299-9229-ed2da6af7c90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTMyODgsIm5iZiI6MTcxMDQ5Mjk4OCwicGF0aCI6Ii8xMDg5MTg2Ni8zMTI2MDQ4MzYtOTdmNzZhOTctYzU0My00Mjk5LTkyMjktZWQyZGE2YWY3YzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA4NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MmRjNDJiMjczZTQ2NGI3NWUyMTFhMzU4ZDUwZDFjZDIzMmY3OWY3ZjBkZjhkNjVhMmE1MmU5ZGU2YzE4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZgqeYDeFH1JFjdBmasbKAxhJDnEQiWTz0efSsi5751M)

Similar thing is happening for CRA. Chrome shows source maps loaded but RDT is not able to access it
