### ISSUE TITLE
Bug: Source is not showing in 5.0.2

### ISSUE THREAD

**Issue by pavel-plehanov** [facebook/react#28558]
## Stand 
DevTools version:  5.0.2-47cf347e4
Chrome 122.0.6261.129 x64, Edge 122.0.2365.80 x64

## Propblem
In the DevTools -> Components -> source. 
The path to the bundle.js file is specified.
#### v5.0.2
![image](https://github.com/facebook/react/assets/144036324/19ae23ca-0b5c-4e22-b2fb-20e69b8de53e)
![image](https://github.com/facebook/react/assets/144036324/5a31c30f-3729-40fa-a580-12546cd66945)
![image](https://github.com/facebook/react/assets/144036324/68806261-1588-4821-9787-e17aa2a10f0a)
![image](https://github.com/facebook/react/assets/144036324/cea28611-acfe-4e69-acbb-0cf8ff409af2)
#### v5.0.0
![image](https://github.com/facebook/react/assets/144036324/c363f00d-eedd-4f84-bc1d-dd6e027a55c4)
![image](https://github.com/facebook/react/assets/144036324/47b70158-5921-434c-8133-7f418dbb926c)
![image](https://github.com/facebook/react/assets/144036324/a69f6db7-59dd-4dc0-b316-16947924b5dd)
## Analog Issue
https://github.com/facebook/react/issues/28544
@hoxyq this is has nothing to do with reality.
But "source" **work** in "DevTools version: **5.0.0**-993c4d003"
And **doesnt wokr** in "DevTools version: **5.0.2**-47cf347e4"

Tested one application on the same PC at the same time in the defferent version DevTools.
Equal SourceMap

React version: 18

## The current behavior
Open DevTools, choose component -> the source field contains the name of the component

## The expected behavior
Open DevTools, choose component -> the source field says "bundle.js:[lineNumber]".

**Comment by shreeyansh-mesh** [comment]
It's working in firefox but not in chrome, likely recent chrome update broke it

**Comment by pavel-plehanov** [comment]
> Он работает в Firefox, но не в Chrome, вероятно, недавнее обновление Chrome сломало его.

In my Firefox - v5.0.0

**Comment by hoxyq** [comment]
Hey @pavel-plehanov, thanks for reporting this. 

As I've mentioned in https://github.com/facebook/react/issues/28544#issuecomment-1991591646, this is expected change. In v5.0.0 RDT is using `__debugSource` field from fiber, which is soon will be removed with the next React release.

The way how RDT defines source has changed in https://github.com/facebook/react/pull/28471: `bundle.js:[lineNumber]` is the actual source, because this is what is loaded in the browser, unless you have source maps, which list other sources.

Technically, yes, this is a regression on RDT side, but an expected one, because previously used debugging fields are no longer available (removed from React) for different reasons.

**Comment by shreeyansh-mesh** [comment]
> Hey @pavel-plehanov, thanks for reporting this.
> 
> As I've mentioned in [#28544 (comment)](https://github.com/facebook/react/issues/28544#issuecomment-1991591646), this is expected change. In v5.0.0 RDT is using `__debugSource` field from fiber, which is soon will be removed with the next React release.
> 
> The way how RDT defines source has changed in #28471: `bundle.js:[lineNumber]` is the actual source, because this is what is loaded in the browser, unless you have source maps, which list other sources.
> 
> Technically, yes, this is a regression on RDT side, but an expected one, because previously used debugging fields are no longer available (removed from React) for different reasons.


How do I enable sourcemaps in CRA development mode?

**Comment by KinIcy** [comment]
> How would we debug legacy apps? How can we get hold of the older versions to install?

I followed the instructions here: 

https://gist.github.com/juniorcesarabreu/115a4f5141cd1a841119c511c4c66d3f

**Comment by timdelange** [comment]
After all, the #1 use of this extension is to find the correct file and line to edit in a large project. ATM when you point to a component all you get is chunk.xxxxx.js:2321312

**Comment by pavel-plehanov** [comment]
An archive of past versions is available in the Firefox

**Comment by imbasri** [comment]
thanks for solution.

**Comment by kblauhut** [comment]
> After all, the #1 use of this extension is to find the correct file and line to edit in a large project. ATM when you point to a component all you get is chunk.xxxxx.js:2321312

I agree, this seems to be main use case for this feature. This was also used by other browser extensions which, up until this point, allowed you to directly navigate to a components code in your editor by clicking on them.
What would the use case of this feature be in its current version? I can't think of why one would want to inspect component code in the browser without being able to edit it. 🫤
