### ISSUE TITLE
why children depends on the order of enumerating the properties of object

### ISSUE THREAD

**Issue by yiminghe** [facebook/react#2856]
I notice component children's type returned by React.Children.map ... is object, and React.Children.forEach use `for in` to loop if children's type is object. I think it will cause problem in the future as spec does not guarantee the order of enumerating the properties of object: http://ecma-international.org/ecma-262/5.1/#sec-12.6.4

PS: I try to extract ReactCSSTransitionGroup which heavily depends on the order of enumerating the properties of object into a standalone package which use children of array type to merge and render: 
https://github.com/react-component/css-transition-group/blob/0215aec52dfa94432c651f008c570dfdb1bf2f84/lib/ReactTransitionChildMapping.js#L28

https://github.com/facebook/react/blob/892f0a59fe63c46cb3d998ac7165296a864f65d8/src/addons/transitions/ReactTransitionChildMapping.js#L48

If you need pull request for ReactCSSTransitionGroup, let me know.

**Comment by spicyj** [comment]
It's true that the spec doesn't guarantee this, but virtually all browsers and engines do, so we're planning to leave it as-is for now. Alternate solutions with manual bookkeeping tend to be significantly slower.
