### ISSUE TITLE
Bug: event.currentTarget is null even with event.persist()

### ISSUE THREAD

**Issue by gfranko** [facebook/react#2857]
After using `ev.persist()`, `ev.currentTarget` is `null` (all other properties are kept intact).  Is there any reason for this?  Here is my [jsfiddle](http://jsbin.com/nasobe/2/edit).  Thanks!

**Comment by spicyj** [comment]
currentTarget changes as the event bubbles up – if you had a event handler on the element receiving the event and others on its ancestors, they'd see different values for currentTarget. IIRC nulling it out is consistent with what happens on native events; if not, let me know and we'll reconsider our behavior here.

**Comment by gfranko** [comment]
`event.currentTarget` should always be the element the event listener is created on, and should not change as the event bubbles up.

**Comment by spicyj** [comment]
http://jsbin.com/pirayosura/1/edit?html,js,output seems to disagree if you open the console and click the inner div.

**Comment by gfranko** [comment]
Ahhh okay, my bad!  Thanks for the demo.

Is react always going to side with the current DOM event spec, or go the way of jQuery and patch specific things?

**Comment by spicyj** [comment]
We won't always follow the DOM but we will unless there's a good reason to deviate – in this case, it really is the same event that both handlers are getting notified of, and the naming of currentTarget indicates that it's the handler that's _currently_ being executed so I think it makes sense to leave it like this and have it change as the event bubbles. (Making multiple event objects would also be worse for performance.)

**Comment by jinrichardJIN** [comment]
@sophiebits 
![image](https://user-images.githubusercontent.com/20592013/54738119-d38bd600-4bed-11e9-9b35-fdc262d68eec.png)
![image](https://user-images.githubusercontent.com/20592013/54738765-82311600-4bf0-11e9-8dcb-c90a51539673.png)

**Comment by cevr** [comment]
@jinrichardJIN I believe it is because since synthetic events are pooled, at the moment you're viewing the object in google chrome, it has already been wiped to null. However, directly logging the property captures the reference, allowing it to be viewed on chrome.

**Comment by kolyo-peev** [comment]
@jinrichardJIN what do you mean by 'directly logging'? isn's a console.log() such a thing.. I can't find a way to see my event, this is horrible

**Comment by tommedema** [comment]
@kolyo-peev try `event.persist()` before you `console.log` it

**Comment by Maaartinus** [comment]
@sophiebits 
> We won't always follow the DOM but we will unless there's a good reason to deviate – in this case, it really is the same event that both handlers are getting notified of, and the naming of currentTarget indicates that it's the handler that's currently being executed so I think it makes sense to leave it like this and have it change as the event bubbles.

This sounds reasonable, but then, what's the point of `event.persist()`? I only persist the event, so I can use it later... and it must work the same as it does now. But it does not, as I the `currentTarget` is gone. And maybe more, I don't know.

Please consider extending the [doc](https://reactjs.org/docs/events.html#event-pooling).

---

What I'm using now, is
```
event.persist();
event = {...event}
```
which seems to work, but may have problems.

Maybe you could offer some `event.clone()` returning a copy which never changes?

**Comment by matheen821** [comment]
const [anchorEl, setAnchorEl] = useState(null);

const handleClick: (eventElement: React.KeyboardEvent | React.MouseEvent){
    event.persist();
    setAnchorEl(event.currentTarget);   // it will work 
}

use setAnchorEl next line to event.persist(); then it will work.

**Comment by kiril-daskalov** [comment]
In React 17  `event.persist()` do nothing and I don't find a way to access currentTarget now. Any ideas?

https://blog.saeloun.com/2021/04/06/react-17-removes-event-pooling-in-modern-system.html

**Comment by human0821** [comment]
Possible workaround **const {currentTarget} = event**
