### ISSUE TITLE
Bug: use() hook

### ISSUE THREAD

**Issue by w7en** [facebook/react#28588]
React version:
   "react": "0.0.0-experimental-4b84f1161-20240318",
   "react-dom": "0.0.0-experimental-4b84f1161-20240318",

1. How I can use the use() hook without Suspense component?
2. When I use the use() hook with Suspense and call API, I see it still calls the API many times (this version: 3 times, version: 0.0.0-experimental-a870b2d54-20240314 => 4 times).

Link code example: https://github.com/bradtraversy/react-19-playground/blob/main/src/components/useExample1/Joke.jsx

**Comment by albeniskerqeli10** [comment]
It's not because of Suspense or a bug, but the use() hook isn't cached by default, so you have to cache it yourself. 

I would prefer you to go with a library like react-query to handle data fetching in React rather than using 'use' for that.

**Comment by albeniskerqeli10** [comment]
See here:[](https://react.dev/reference/react/use)

**Comment by albeniskerqeli10** [comment]
See here [](https://react.dev/reference/react/use)

**Comment by albeniskerqeli10** [comment]
See here: [https://react.dev/reference/react/use](https://react.dev/reference/react/use)

**Comment by eps1lon** [comment]
As @albeniskerqeli10 said, the promise needs to be cached. The docs don't mention that unfortunately yet which we need to fix.

**Comment by hoanghiaquyen** [comment]
Thank so much. I got it
