### ISSUE TITLE
Lack of TestUtils method that finds rendered component(s) by data attribute value

### ISSUE THREAD

**Issue by jackwanders** [facebook/react#2858]
The React test utilities currently expose the following ways to query the contents of a rendered component for certain elements:

* by type (`scryRenderedDOMComponentsByType`)
* by tag (`scryRenderedDOMComponentsByTag`)
* by className (`scryRenderedDOMComponentsByClass`)

However, it's very common for applications that make use of automated testing tools to target elements not by className (or tag name), but rather by a specific data attribute type that is reserved explicitly for use by the testers. This paradigm allows developers to modify class names for the purposes of styling without worrying about breaking existing test suites.

I feel like it could be beneficial to allow `React.addons.TestUtils` to allow querying of rendered components via data attributes, like so:

```javascript
ReactTestUtils.scryRenderedDOMComponentsWithDataAttr = function(root, attrName, attrValue) {
	return ReactTestUtils.findAllInRenderedTree(root, function(inst) {
		var regex = /^data-/;
		var dataset = {};
		for (key in inst.props) {
			if (regex.test(key)) {
			dataset[key.replace(regex,'')] = inst.props[key];
			}
		}
		return dataset[attrName] === attrValue;
	});
};

ReactTestUtils.findRenderedDOMComponentWithDataAttr = function(root, attrName, attrValue) {
	var all = ReactTestUtils.scryRenderedDOMComponentsWithDataAttr(root, attrName, attrValue);
	
	if (all.length !== 1) {
		throw new Error(
			'Did not find exactly one match for data attribute:' + attrName + ' with value:' + attrValue
		);
	}
	return all[0];
};
```

This would allow unit testing of React elements by rendering them via `React.addons.TestUtils.renderIntoDocument` and then validating the contents of the rendered element by querying for the same data attributes that might be used in a complementary automated test suite.

I figured before even attempting to put together a formal pull request, I would open an issue and get some feedback on the perceived value of such additions to `React.TestUtils`.

Thanks.

**Comment by bengotow** [comment]
+1

It'd be great if this was included in ReactTestUtils and worked for any attribute, not just `data-` attributes. I'm trying to write a test that verifies that a component creates a `<div>` with the `contenteditable` attribute, which seems like it should be a one-liner.

**Comment by spicyj** [comment]
See https://github.com/facebook/react/pull/1473#issuecomment-41952920. These helpers are easy to implement outside of React itself so you can always add them in your own code though.
