### ISSUE TITLE
input@pattern attribute value broken by React

### ISSUE THREAD

**Issue by DavidBruant** [facebook/react#2860]
See http://jsfiddle.net/r0tyv3nq/1/

The rendered element has `[^s]+` as pattern attribute value while it should have `[^\s]+`
JsFiddle uses React 0.9, but I noticed this issue with React 0.12.2

I imagine (but haven't tested) this isn't specific to the pattern attribute, but only that `\` are stripped or something.

**Comment by DavidBruant** [comment]
Pattern attribute is a recent "HTML5" attribute used for RegExp-based validation of text input.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes

**Comment by DavidBruant** [comment]
I can get `[^\s]+` in the rendered element if I pass `[^\\s]+` to React.

**Comment by syranide** [comment]
Not a React bug, this is simply how JavaScript works, `/\s/` is written as `'\\s'` in strings.

**Comment by DavidBruant** [comment]
duh... true. Sorry for the noise.
And thanks for React :-)
