### ISSUE TITLE
Bug: React Dev tools extension showing wrong source file path on inspection

### ISSUE THREAD

**Issue by gittyvarshney** [facebook/react#28603]
When we try to inspect the component using react-dev-tools to find the file's path and line number, it is now showing path to file from some build folder (like *.mjs, *.js) rather than from the actual source file, I think something happened recently which somehow break down this very useful functionality.

![issue_react_devtools](https://github.com/facebook/react/assets/47815255/254320f5-37f2-4e8a-bc27-5ade377d143b)

React version:

## Steps To Reproduce

1. Run any react application in development mode
2. try to inspect the component from react-dev-tools and check its source

you can also clone this respository: https://github.com/gittyvarshney/phoneBook
`git clone https://github.com/gittyvarshney/phoneBook.git`
`npm install `
`npm run dev`

**Comment by pwbriggs** [comment]
Hey @gittyvarshney, could you check out #28558 and see if this is the same issue?

Thanks! ❤️

**Comment by gittyvarshney** [comment]
> Hey @gittyvarshney, could you check out #28558 and see if this is the same issue?
> 
> Thanks! ❤️

yes, I think it's the same issue
thanks

**Comment by pwbriggs** [comment]
OK, thanks for checking! I think you can close this issue then.

**Comment by gittyvarshney** [comment]
Closing the issue, similar issues is being raised in another PR please track it on: https://github.com/facebook/react/issues/28558.
