### ISSUE TITLE
Please allow indie developers to impelement Facebook Login without business verification

### ISSUE THREAD

**Issue by umutakmak** [facebook/react#28667]
Some support pages link to an "individual verification" method for using Facebook Login in apps but i can't seem to find it now. My meta console says I have to verify my business. Is this a bug? Why would anyone HAVE TO own a business to implement facebook login? Can you clerify if this is a bug or Meta just don't like indie developers anymore?

**Comment by rickhanlonii** [comment]
This repo is for issues specific to React, we're not related to Facebook Login
