### ISSUE TITLE
Write custom lint rules

### ISSUE THREAD

**Issue by zpao** [facebook/react#2869]
- [x] Make sure `warning` and `invariant` have a string literal for first argument
- [ ] Make sure JSDoc args match up

**Comment by malandrew** [comment]
+1 for writing these as eslint rules.
+1 for making sure these rules also work with non-JSX code

@zpao for your second suggestion, does the [eslint jsdoc rule][jsdoc-rule] work for what you're proposing?

[jsdoc-rule]: https://github.com/eslint/eslint/blob/master/docs/rules/valid-jsdoc.md

**Comment by zpao** [comment]
The exiting jsdoc rule is too noisy. I tried it but since we don't use jsdoc consistently it warns for way too much. I really just want to catch the cases that will break other tooling. #2772 is an example of the sort of thing I want to catch.

**Comment by malandrew** [comment]
When you say "exiting" jsdoc rule, do you mean the require return? 

If so, there is an option for turning that off: https://github.com/eslint/eslint/blob/master/docs/rules/valid-jsdoc.md#requirereturn (we have requireReturn turned off in the lint rules we use).

If there are other options that you think should be available on that JSdoc rule, maybe those options should be added to the eslint jsdoc rule instead (until the rules become numerous enough that they are split up into several rules)

**Comment by zpao** [comment]
s/exiting/existing/

I considered adding the options to upstream but I didn't care enough in the short term and my priority is our code. We'll see if our requirements are too niche to go upstream, but I'll definitely consider it.

**Comment by hzoo** [comment]
Do we still want `Make sure warning and invariant have a string literal for first argument`?

**Comment by zpao** [comment]
Yes!

**Comment by hzoo** [comment]
Ok can start a PR for that later! - Also relevant is `Make sure JSDoc args match up` - with  #2981

**Comment by gaearon** [comment]
Closing as we don't use JSDoc in new code anyway.
