### ISSUE TITLE
How can I get original html rather than compiled (there has an example from react tutorial)

### ISSUE THREAD

**Issue by Mickey-** [facebook/react#2871]
when I return 
![image](https://cloud.githubusercontent.com/assets/2062355/5773683/22f5f69a-9da0-11e4-9ffd-bb57c918942e.png)

In highlight area, I unexpectly get 
![image](https://cloud.githubusercontent.com/assets/2062355/5773349/70ff60c8-9d9c-11e4-894a-53608a260d09.png)

what I want is 

````html
<h2 class="commentAuthor" data-reactid="blabla">
    testleft <b data-reactid="blabla">somebodypx</b>
</h2>


What should I do?

**Comment by zpao** [comment]
`<b>{this.props.author + 'px'}</b>`

React sees this as a single text child whereas the one in the tutorial is treated as two.
