### ISSUE TITLE
Bug: React server components give type error in react 19

### ISSUE THREAD

**Issue by InsightfulFuture** [facebook/react#28718]
React version:
Canary (19.0.0-canary-95e6f032c-20240401)

## Steps To Reproduce

1. Create a react app with typescript
2. Make app.tsx a server component

Link to code example:
https://github.com/InsightfulFuture/react-19-ts

## The current behavior
I get the error:
```
'App' cannot be used as a JSX component.
  Its type '() => Promise<JSX.Element>' is not a valid JSX element type.
    Type '() => Promise<JSX.Element>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'Promise<Element>' is not assignable to type 'ReactNode'
```
when I make app an async component with use server

## The expected behavior
It works with app as a server component

**Comment by pawelblaszczyk5** [comment]
You need to have these versions for it to work correctly `typescript@^5.1.2` and `@types/react@^18.2.8`

**Comment by eps1lon** [comment]
And enable the types for the Experimental release channel either via an `import 'react/experimental'` or `/// <reference types="react/experimental" />` in at least one file that's part of your TypeScript project.
