### ISSUE TITLE
React.Children.map does not return an Array or Array-like object

### ISSUE THREAD

**Issue by pmeskers** [facebook/react#2872]
Hey there,

I'm trying to use `React.Children.map` in conjunction with `React.addons.cloneWithProps` to create a copy of my children. However, it's [surprising behavior](http://en.wikipedia.org/wiki/Principle_of_least_astonishment) to find that map does not return an array as a typical map function would. 

The value I see in returning an array would be enabling one to perform array operations on a collection of children, such as reordering/splicing, inserting new elements, etc. Since it doesn't return an array, and the children are meant to be an opaque data structure, it's unclear to me what the best practice is for doing this type of thing.

I've created a [rough jsfiddle](http://jsfiddle.net/uhe5tgoh/1/) that demonstrates this. 

I assume this behavior is for optimization purposes, in which case maybe there is some other way to think about my problem. 

Thanks for any feedback! Cheers.

**Comment by yiminghe** [comment]
this confuses me too  

https://github.com/facebook/react/issues/2856

**Comment by brigand** [comment]
In programming `map f T -> T`, or in english, you map a function to something of type T and get back something of type T.  In JS the only built in version is an array map.  This is a Children map, which maps from Children to Children.  Children is an opaque data structure (no public properties or methods), so the behavior doesn't violate any promises.  

React could provide a converter between Children and Array.  It'd probably look something like this:

```
React.Children.toArray = function(children){
  if (Array.isArray(children)){
    return children.slice();
  }
  // single child
  else if (children === null || typeof children !== 'Object' || React.isValidElement(children)) {
    // avoid the warning about missing key prop
    if (React.isValidElement(children) && !children.key) {
      return [React.cloneWithProps(children, {key: 0})];
    }
    return [children];
  }
  // {a: <div />} -> [<div key="a" />]
  else {
    return Object.keys(children).map((key) => {
      if (!children[key].key) {
        var props = {key: key};
        return React.cloneWithProps(children[key], props));
      }
      return children[key];
    });
  }
}
```

**Comment by pmeskers** [comment]
Thanks @brigand for a great reply. One thing that confuses me, however, is that I'll typically invoke `React.Children.map` as such:

```
var kids = React.Children.map(this.props.children, function(child) {
    // ...
});
```

In this case, `this.props.children` is *not* a Children object -- however, the invocation works just fine and React.Children.map returns an instance of Children even though it was given an array argument. 

I do see your point, and it's fair for the map function to not be obligated to return arrays. But it seems problematic that it *accepts* arrays. 

I think a larger question I have around React Elements as children is how we are meant to interact with them if we have an opaque interface. I've updated a [jsfiddle here](http://jsfiddle.net/uhe5tgoh/2/) which tries to demonstrate this -- it wants to shuffle a list of children, each of which are React Elements. I would love to get some thoughts on what the best practice is for solving this problem. Your converter from Children to Array seems plausible, I'm just wondering why it hasn't been a problem for others yet -- it makes me think I'm just missing some bigger picture here :)

Cheers!

**Comment by brigand** [comment]
So... there is a way to do that, but it's complicated and involves React.Chidlren.forEach and React.Chidlren.count, and storing the sorted indexes in state, and handling changing the array of indexes in componentWillReceiveProps.

The better way to do it is just sort the data in the parent component.  I'm glad it's so complicated to do in a child, because sorting elements doesn't make a lot of sense (you sort data).

**Comment by Dyscrete** [comment]
brigand, why are you using slice in your code above?
```
...

  if (Array.isArray(children)){
    return children.slice();
  }

...
```

**Comment by brigand** [comment]
@Dyscrete if I just returned the array then sometimes (but not always) `toArray(this.props.children) === this.props.children`  .  That would mean that toArray couldn't promise that you're allowed to modify the returned array (if you decide you want to do that).  It's mostly just a point of consistency.

**Comment by Dyscrete** [comment]
@brigand Thanks for the explanation, I was aware it's use to create shallow copies but for some reason I just immediately assumed it was because `this.props.children` returned an object rather than array similar to how React.Children.map returns an object. (#2856)

**Comment by spicyj** [comment]
map now always returns an array in 0.14.
