### ISSUE TITLE
add support for SVG Image element

### ISSUE THREAD

**Issue by zcregan** [facebook/react#2873]
There was another issue tracking this #2069, but it looks like it got merged into an issue that was already closed so it never got fixed.

**Comment by mattholland-dnb** [comment]
There's also #2263.

**Comment by gregtillbrook** [comment]
SVG images are an important part of my current project - is there anything I could do to help push this issue through?

**Comment by gregtillbrook** [comment]
#3952 is a newer PR without the merge conflicts of #2263

**Comment by zpao** [comment]
Closed with #4157
