### ISSUE TITLE
Cannot load example

### ISSUE THREAD

**Issue by conect** [facebook/react#2880]
When I run the index.html in examples jquery-mobile in the chromium browser, I get:
 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefinedreact.js:5776 Constructorapp.js:182 (anonymous function)

**Comment by awelles** [comment]
I can confirm.

Works fine with React version “0.12.2", but "0.13.0-alpha.2" gives: 
react.js:5823 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined
react.js:5823 ReactClass.createClass.Constructor
app.js:182 (anonymous function)

The  jquery-mobile example is using component constructors in a way which makes the new version explode. gaearon lays is out here:
https://github.com/facebook/react/issues/2661

**Comment by zpao** [comment]
We'll make sure all the examples are working before we release 0.13 final but until then there's a non-trivial change they'll be broken at any point in time. Check out the latest stable branch for the working examples.
