### ISSUE TITLE
Warning: Unknown DOM property autocomplete. Did you mean autoComplete?

### ISSUE THREAD

**Issue by mockdeep** [facebook/react#2882]
I'm not sure what counts as a canonical source, but as near as I can tell, the `autocomplete` input property should be all downcased. I've been having some trouble with form input showing up in Firefox after a refresh and noticed that I had `autoComplete='off'`. Not sure if that will have an effect on the functionality, though.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by syranide** [comment]
React requires camelCasing for DOM attributes, even though the DOM attributes are lower-cased or sometimes hyphenated. However, React always output the correct DOM attribute name in the markup, so unless you're seeing something else, everything is as it should.

**Comment by RicardoMTT** [comment]
you have to make use of camelcase.React in the console I think it shows you.
It would be like this:
autoComplete

**Comment by michael-freidgeim-webjet** [comment]
@syranide, both https://github.com/facebook/react/ links  are broken.

**Comment by syranide** [comment]
@michael-freidgeim-webjet https://github.com/facebook/react/blob/f85aadefc0c059648ee53842ba948a7d7cba468b/packages/react-dom/src/shared/possibleStandardNames.js is probably what you are looking for.
