### ISSUE TITLE
⚠Phishing Website Warning!!! There are phishing website links in the document.

### ISSUE THREAD

**Issue by ouweiya** [facebook/react#28839]
**Phishing Website Warning!!! There are phishing website links in the document.**

Document address: 
https://react.dev/learn/referencing-values-with-refs#adding-a-ref-to-your-component

This domain is very cunning, redirecting to different websites based on the region of the request. If it's a user from the United States, it redirects to https://nearestnabors.com/. If it's from an Asian country, it redirects to a gambling website.

Phishing website:
http://rachelnabors.com/

https://github.com/facebook/react/assets/28357731/f2e940a3-6598-43e7-8691-deb8b837b729

**IP USA：**

https://github.com/facebook/react/assets/28357731/87614d39-e021-4a7e-96ea-e299b1ee9a81

**IP HongKong:**

https://github.com/facebook/react/assets/28357731/aea3ab01-07f8-48aa-b77f-ef536a8ab95f

**Comment by TheJarX** [comment]
Just checked. Seems to be fixed now. It redirects to the updated domain.

**Comment by ouweiya** [comment]
> This domain is very cunning, redirecting to different websites based on the region of the request. If it's a user from the United States, it redirects to https://nearestnabors.com/. If it's from an Asian country, it redirects to a gambling website.

**I have updated the issues, please check again.**

**Comment by kassens** [comment]
I still see some ad page on http://rachelnabors[dot]com/
My guess is the domain expired and we should update it.

**Comment by rickhanlonii** [comment]
It looks like the github pages CNAME for `rachelnabors.com` is being squatted:

- the [fake repo](https://github.com/Neturo64/http-rachelnabors.com-) uses CNAME `rachelnabors.com`
- the [real repo](https://github.com/rachelnabors/rachelnabors.github.io) was updated 2 weeks ago from `rachelnabors.com` to `2024.rachelnabors.com` in https://github.com/rachelnabors/rachelnabors.github.io/commit/74cdf05b60cb1fe34ae07cb887a0fb4737232c67

When the CNAME in the real repo changed to `2024.rachelnabors.com`, github started to resolve the root domain (without the `2024`) to the fake repo. @rachelnabors you can fix this CNAME attack by [Verifying your custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages) so only your repos can set a CNAME for that domain.

**Comment by TheJarX** [comment]
Nice catch @rickhanlonii. Repo reporte for visibility 👍🏻
