### ISSUE TITLE
Invariant checking for component classes passed as mixins not fully correct

### ISSUE THREAD

**Issue by BinaryMuse** [facebook/react#2883]
In d9fe40e1476d056629b9b7a28d05fd50246c0ed3,

```javascript
function mixSpecIntoComponent(Constructor, spec) {
  // ...

  invariant(
    !ReactLegacyElement.isValidFactory(spec),
    'ReactCompositeComponent: You\'re attempting to ' +
    'use a component class as a mixin. Instead, just use a regular object.'
  );
```

changed to

```javascript
function mixSpecIntoComponent(Constructor, spec) {
  // ...

  invariant(
    typeof spec !== 'function',
    'ReactClass: You\'re attempting to ' +
    'use a component class as a mixin. Instead, just use a regular object.'
  );
```

However, `spec` simply being a function doesn't correctly fully identify this error. As an example, I have the following code in Fluxxor:

```javascript
var FluxMixin = function(React) {
  return {
    componentWillMount: function() {
      // ...
    },

    // ...
  };
};

FluxMixin.componentWillMount = function() {
  throw new Error("Fluxxor.FluxMixin is a function that takes React as a " +
    "parameter and returns the mixin, e.g.: mixins[Fluxxor.FluxMixin(React)]");
};
```

Tests around the messaging started failing when using React 0.13.0-alpha since `FluxMixin` is technically a function. Is there another conditional that would better identify passing a component class as a mixin?

**Comment by spicyj** [comment]
I'm confused. You _do_ want to allow using `FluxMixin` as a mixin or you just want your own error to fire instead of React's (admittedly somewhat-confusing one)?

**Comment by BinaryMuse** [comment]
In this case, just to show the custom error. I suppose that, although it's technically possible to pass a function as a mixin (as long as the function has component lifecycle functions defined as properties on it), it's probably not a very common scenario. Maybe a change as simple as "ReactClass: You're attempting to use a function as a mixin" would do the trick.

**Comment by gaearon** [comment]
Closing as we won't be changing `createClass`.
