### ISSUE TITLE
Detect React DOM element with a wrong attribute name

### ISSUE THREAD

**Issue by Kureev** [facebook/react#2887]
Dear all,

I'm pretty new to React. For some reasons I want to use it without JSX, and I faced an issue I can't resolve: if in the react's element properties you have a `class` key instead of `className` key (for example), in the console you'll see a warning: `Warning: Unknown DOM property class. Did you mean className?`. Okay, I really mean `className`, now how can I find it? I mean where I supposed to look first? In the fb's react plugin for chrome I don't see "wrong" attribute, warning don't give me any stack trace either. If I have a huge DOM it's very hard to go thru it manually, without any hints. Does it possible to find any workaround?

[Here you can see an example](http://jsbin.com/zarimegenu/1/)

**Comment by brigand** [comment]
A recursive file search for `class:` should help you find it quickly.  

It may be feasible to improve the warning when you have a displayName on your components.

**Comment by Kureev** [comment]
@brigand yeah, thanks, now it seems to be only one possible solution for this. But I think it should be some other ways to resolve those kind of issues. I've expected to see that issue highlighted in the React tab, or maybe component name where I got this issue, for example: `Warning: Unknown DOM property class in component HelloMessage. Did you mean className?` don't think it's hard to implement...

**Comment by brigand** [comment]
I meant displayName.

```js
React.createClass({displayName: "HelloMessage", ...});
```

It's what's show in the dev tools addon and error messages.

**Comment by Kureev** [comment]
@brigand Sorry, I got only [this](https://www.dropbox.com/s/62a75nttndt0ini/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-20%2023.32.03.png?dl=0) in my usual console and [no warnings here](https://www.dropbox.com/s/4bost8ve3brs3ek/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-20%2023.33.04.png?dl=0). What I'm missing?

**Comment by zpao** [comment]
Yea, this is a good idea. I'm not entirely sure if we actually have access to the owner component at that point, we may have to pass some extra information around. In the mean time, grep is the best option. Usually people see this while iterating so there's a relatively small surface area of possible blame, so it hasn't been much of an issue. But it would make React friendlier. I would support adding this as long as it doesn't make the code much more complicated.

**Comment by sebmarkbage** [comment]
The idea is to move propType validation to the element creation instead of during mount. If we treat these warnings as part of the same validation step, you would get the warning earlier. So the stack trace would be at the point where you created the element.

This is a bit problematic for natives because it is environment specific but since this is just validation we can probably special case this.

**Comment by smonev** [comment]
I had the same problem and having the value of the className passed would have helped me locate the problem fast. Instead of "Warning: Unknown DOM property class. Did you mean
className?", show "Warning: Unknown DOM property class, value: foo. Did
you mean className?"

I made this pull request: https://github.com/facebook/react/pull/2947 (this is my first PR and I am not sure if I made everything right).

**Comment by skevy** [comment]
@sebmarkbage would it be worth it to try to add this functionality before the (presumably) larger task of moving propType validation happens?

Was gonna tackle this, as I think it's a huge improvement to this warning, but don't want to waste time if something bigger and better is coming down the pike. :)

**Comment by skevy** [comment]
@sebmarkbage on second thought - disregard.

Moving the validation of DOM element properties out of the mounting is definitely the right move.

I'll take a deeper look at this and maybe open another bug. Seems like it would be pretty clean to move this out.

**Comment by skevy** [comment]
Could someone tell me why https://github.com/facebook/react/blob/master/src/core/ReactCompositeComponent.js#L435-L436 is still there, and what's preventing it from being taken away?

Just trying to get my head around this.

**Comment by zpao** [comment]
@skevy I think that's still there because props aren't really immutable yet so it's possible to mutate after creating an element. We want validation to only happen once at element creation. But as long as we support modifying the element, we need to actually validate at mount time. cc @spicyj

**Comment by spicyj** [comment]
I'm not familiar with the validation setup here.

**Comment by gaearon** [comment]
>Could someone tell me why https://github.com/facebook/react/blob/master/src/core/ReactCompositeComponent.js#L435-L436 is still there, and what's preventing it from being taken away?

This should go away in 0.14.

0.13 deprecated mutating props on elements but still has the old behavior.
0.14 will stop supporting mutating props, and thus the old behavior will be removed.

**Comment by skevy** [comment]
Thanks guys - appreciate the insight. To be honest, I forgot that you COULD even mutate props (never used that, and it seems like a good thing that I didn't as it's being deprecated).

**Comment by Sumei1009** [comment]
Could I try this issue?

**Comment by Sumei1009** [comment]
This is my first pull request. Not sure whether I make everything right?

**Comment by gaearon** [comment]
This has since been implemented, and [this Babel plugin](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source) will give you full stacktrace for the unknown prop warning. It is enabled by default in Create React App.
