### ISSUE TITLE
Changelog for 18.3 is missing

### ISSUE THREAD

**Issue by renchap** [facebook/react#28924]
React version: 18.3

## Steps To Reproduce

1. Check the Releases section on this repo, the `CHANGELOG.md` file, or click on "Release notes" at the end of the second note on this blog post: https://react.dev/blog/2024/04/25/react-19-upgrade-guide

## The current behavior

There is no changelog for the 18.3 release

## The expected behavior

There should be a changelog

**Comment by joaopedrodcf** [comment]
Was also looking to understand the impact of this minor update :D

**Comment by nathanforce** [comment]
Sorry to pile on to a closed issue but did not want to add a documentation related issue.

@rickhanlonii does the 18.3 release include a fix for the hydration mismatch errors mentioned in React and Remix issues (
https://github.com/facebook/react/issues/24430#issuecomment-1910552233
https://github.com/remix-run/remix/issues/4822#issuecomment-2287588428)

I'm seeing some comments around issues/Twitter that indicate it might, but the changelog does not mention it.
https://twitter.com/kiliman/status/1769730243772780825

Thanks!

**Comment by rickhanlonii** [comment]
No, that's the canary, not 18.3 stable.
