### ISSUE TITLE
[React 19] Eslint React JSDoc support

### ISSUE THREAD

**Issue by eduardocque** [facebook/react#28935]
## Summary

based on react 19 documentation `prop-types` is gone, so for JS users the only way to manage it is using JSDoc, can be possible to support jsdoc prop-type validation in eslint-plugin-react ?

Example
```js
/**
 * @param {{
 *   content?: string,
 *   requiredParameter: string // required parameter if not can be with "?"
 * }} props
 * @returns {React.ReactElement}
 */
const ChildElement = props => {
  const { content = '' } = props;

  return <div>{content}</div>;
};

/** @returns {React.ReactElement} */
const ParentElement = () => {
  return <ChildElement content="Hello World" wrongParameter="test" />;
};
```

in this example
* wrongParameter should be marked as error due that is not in ChildElement JSDocs
* whole component should mark an error due that requiredParameter that exists in the JSDoc is not defined from the parent element

the intention of this request if to give some ways in javascrit to work without involve typescript to maange types and props

**Comment by kassens** [comment]
Unfortunately, type checking is a very complex task and out of the capabilities that a eslint plugin can provide (you need to look across files to start, which as far as I know isn't supported by ESLint).

For static type checking TypeScript (and Flow) are the supported ways.

**Comment by NoamAnisfeld** [comment]
@kassens I believe the request isn't to support type-checking but just to recognize JSDoc notations as a legitimate TypeScript notation ([which it is](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)). Are you sure it cannot be done?
