### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read properties of null (reading 'useMemo') [React 18.3.1]

### ISSUE THREAD

**Issue by owenn2106** [facebook/react#28947]
I have upgraded to React `18.3.1`, previously from `18.2.0`. After upgrading, my app won't start. At first it's due to `useMemo` in `<PortalProvider />` which is a component from `blueprintjs`. When I open the file, it looks something like:
```js
import * as React from "react";

const PortalProvider = (...) => {
    const data = React.useMemo(...)
}
```
From the error message, here I'm assuming `React` is null, but I'm not sure why. This was working fine before with `18.2.0`. I tried removing this `<PortalProvider />` component, but I get another error in `<Provider />` from `react-redux`, but this time instead of `useMemo`, it errors out with `useContext`. All I did was upgrade the React version nothing else. Am I missing something? I would like to upgrade to `18.3.1` to prepare for React 19.

React version: `18.3.1`
Blueprintjs version: `5.10.2`
Redux version: `4.2.1`
React-redux version `8.1.3`

![Screenshot of console](https://github.com/facebook/react/assets/75826315/965c1445-b5c3-41c7-a19e-aa30b5862994)

My `src/index.tsx`:
```tsx
import { useEffect } from "react";
import {
  createRoutesFromChildren,
  matchRoutes,
  useLocation,
  useNavigationType,
} from "react-router-dom";
import { Classes, PortalProvider } from "@blueprintjs/core";
import { createRoot } from "react-dom/client";
import * as Sentry from "@sentry/react";
import "style/index.scss";
import Router from "./router";
import store from "redux/store";
import { Provider } from "react-redux";
import { APP_VERSION } from "utils/constants";
import * as serviceWorker from "./serviceWorker";

Sentry.init({
  dsn: "...",
  integrations: [
    Sentry.reactRouterV6BrowserTracingIntegration({
      useEffect: useEffect,
      useLocation,
      useNavigationType,
      createRoutesFromChildren,
      matchRoutes,
    }),
    Sentry.replayIntegration(),
  ],
  enabled: process.env.NODE_ENV !== "development",
  release: APP_VERSION.toString(),
  // Set tracesSampleRate to 1.0 to capture 100%
  // of transactions for performance monitoring.
  // We recommend adjusting this value in production
  tracesSampleRate: 1.0,
});

// <React.StrictMode> removed because of blueprint https://github.com/palantir/blueprint/issues/3979
const container = document.getElementById("root");
if (!container) throw new Error("Element with id 'root' not found.");
container.classList.add(Classes.DARK);

const root = createRoot(container);
root.render(
  <PortalProvider portalClassName={Classes.DARK}>
    <Provider store={store}>
      <Router />
    </Provider>
  </PortalProvider>
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

**Comment by kassens** [comment]
This looks like you might be missing to update `react-dom` to the matching 18.3.1 as the error message suggests.

**Comment by rickhanlonii** [comment]
Yeah @owenn2106 did you update your `react-dom` version as well?

**Comment by mishra-ankit** [comment]
![326373793-965c1445-b5c3-41c7-a19e-aa30b5862994](https://github.com/facebook/react/assets/1507256/85cddb31-8cfb-4329-8cc1-deccb9944f36)
Also having same issue

**Comment by owenn2106** [comment]
@kassens @rickhanlonii Yeap, my react-dom is updated to `18.3.1` as well

**Comment by owenn2106** [comment]
Turns out we are having this issue because we have multiple copies of React. My team has a monorepo, which has a shared folder and these shared folder has a dependency of React 18. Package json looks like:
```json
  "peerDependencies": {
    "@types/react": "^17 || ^18",
    "react": "^17 || ^18",
    "react-dom": "^17 || ^18"
  },
```

So we had to just change the peer dependencies to `18.3` for it to work.
```json
  "peerDependencies": {
    "@types/react": "^17 || ^18.3.0",
    "react": "^17 || ^18.3.0",
    "react-dom": "^17 || ^18.3.0"
  },
  ```

**Comment by kassens** [comment]
Since the error message already contains this as the first recommendation, I don't think there's more we can do, unfortunately :(

**Comment by Xisney** [comment]
This may be because there are multiple React instances in your project. Try to check the structure of the project's node_modules and whether React is installed separately in the React Redux directory

**Comment by 1mehdifaraji** [comment]
I had the same issue with `react 18.2` and I resolved it by removing `^` from `react` and `react-dom` in `package.json` and then `rm -rf node_modules` `pnpm install`.
