### ISSUE TITLE
[React 19] React warns about "fetchpriority" props

### ISSUE THREAD

**Issue by ascorbic** [facebook/react#28946]
## Summary

In 18.2.0, React allowed the `fetchpriority` prop in all lower case, but did not accept camelized `fetchPriority`. Support for the camelized version was added in #25927, but it seems to have broken the lowercased version. This means there is no variant that works in both 18.2 and 18.3 canary/19 beta.

Repro: https://codesandbox.io/p/sandbox/nameless-bird-wvv84h

In 18.2.0 `fetchPriority` generates a warning but `fetchpriority` works without warning
In 18.3.0-canary and later, `fetchPriority` works but `fetchpriority` generates a warning.

**Comment by eps1lon** [comment]
In the repro, the `fetchpriority` attribute is set for both cases. The only difference is a dev-only warning.

**Comment by eps1lon** [comment]
With broken you mean the warning that changed or is there some other, end-user observable behavior that broke?

**Comment by ascorbic** [comment]
I mean the warning. It warns when previously it didn't complain. I think this would count as a breaking change. It renders fine in both cases, so the warning isn't needed.

**Comment by rickhanlonii** [comment]
It doesn't count as a breaking change, since we don't consider DEV warnings as breaking changes in our development policy: https://react.dev/community/versioning-policy#what-counts-as-a-breaking-change

But we should probably make this a deprecation warning instead of the current text since it implies it doesn't work. Something like:

> Warning In React 19,`fetchpriority` has been renamed to `fetchPriority`. We will remove support `fetchpriority` in a future version. Please check <Foo>.

What do you think @eps1lon?

**Comment by ascorbic** [comment]
_Are_ you planning to remove support? I'm not clear on the policy there: is the plan to only support DOM properties and not HTML attributes?

**Comment by eps1lon** [comment]
Mabye the "invalid" wording is a bit strong. We should just say it's renamed as @rickhanlonii suggests. But removing support would be a novel thing to do. We haven't done that  for any other prop.

**Comment by eps1lon** [comment]
It can get confusing with regards to object spreading and handling both casings. We'd have to add additional runtime logic to reconcile all casing variants. 

Typechecking would also have to support both casings and would no longer flag if you specify both properties.

**Comment by ascorbic** [comment]
I wish there was a way to feature-detect for it though. A warning is fine for end users, but those of us building libraries will need to support both. Granted, there probably aren't many libraries that need to set that particular prop (and with https://github.com/vercel/next.js/pull/65235 and https://github.com/ascorbic/unpic-img/pull/644 thos are probably covered), but checking for the existence of `use` isn't a great solution.
