### ISSUE TITLE
Update react GitHub page CNAME record

### ISSUE THREAD

**Issue by includerajat** [facebook/react#28968]
React GitHub page (https://facebook.github.io/react) (`gh-pages` branch) currently pointing to [reactjs.org](https://reactjs.org) and then it redirects to https://react.dev/.

So many redirects, can we update the content of `CNAME` file with `react.dev`, if it ok to do, then I am very happy to do the same and I'll contribution in real open source project.

**Comment by kassens** [comment]
Sounds good, feel free to send a PR against the gh-pages branch 👍

**Comment by includerajat** [comment]
Thanks @kassens, I thought I would get an opportunity to merge the code :((
Is it good to raise a pull request together when we raise any issue, and we know the fix of that issue?
