### ISSUE TITLE
Clarify --harmony dependence in 'Transferring with ... in JSX' docs

### ISSUE THREAD

**Issue by hanski07** [facebook/react#2896]
New to React. I was following the tutorial and ran into a snag. Copy pasting the example
[Transferring with ... in JSX](http://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx) example lead to `Uncaught SyntaxError: Unexpected token {` on line 2 on Chrome. 
I was using the in-browser JSX transformer.

It took me awhile to figure out this is a proposed JavaScript thing and not a built-in React thing. `<script type="text/jsx>` needed to be `<script type="text/jsx;harmony=true">`. This is super unclear from the documentation/tutorial. To me, it reads as if somehow React is taking care of this or it's a React specific syntax; not ES6. The docs link out to the Destructuring assignment, but I think the docs should clearly state "Your browser / environment must support ES6 harmony for this to work."

**Comment by hanski07** [comment]
Well, the docs do say this... http://facebook.github.io/react/docs/transferring-props.html#rest-and-spread-properties-...

Perhaps move this up further as people (like me) following along the tutorial didn't bother to keep reading down the line.

**Comment by Dashed** [comment]
@hanski07 Want to send a PR to improve upon the tutorial?

**Comment by hanski07** [comment]
@Dashed: Sure. I'll mess with it tonight.
