### ISSUE TITLE
There is no clear best practice for trickling down properties for externally-supplied component children.

### ISSUE THREAD

**Issue by mcantor** [facebook/react#2897]
Suppose I am making a custom radio button field that shows up like a bunch of toggleable-buttons:

```cjsx
<ButtonToggle name="fileType">
    <Option value="readme"   title="README" />
    <Option value="starter"  title="Starter" />
    <Option value="solution" title="Solution" />
</ButtonToggle>
```

Each of the `Option` components will render as a `button` wrapping a hidden `<input type="radio">`.

The input needs to use the name from the parent `ButtonToggle` component, but there's no clear way how to correctly transfer the prop automatically.

It seems redundant to set the `name` prop on each `Option` individually.

However, if I use `React.Children.forEach` to iterate over the children in the `ButtonToggle`'s `render()` method, the objects I get are `ReactElements`, which do not have a `setProps()` method. Instead I did this:

```cjsx
ButtonToggle = React.createClass
  render: ->
    React.Children.forEach @props.children, (option) =>
      # XXX I have no idea if this is OK... no setProps() available
      option.props.name = @props.name

    <div className="ui buttons">
      { @props.children }
    </div>
```

Is this an anti-pattern/bug? If not, perhaps it should be added to the docs.

**Comment by vsiao** [comment]
I think you might be looking for `cloneWithProps(element, props)` in `react/addons`.

**Comment by mcantor** [comment]
@vsiao The docs state that cloneWithProps is for usage by a component that does not own the target child, but in this case, isn't `ButtonToggle` the owner of the `Option` components?

I had thought that "all children are owned by their parents" and "all parents own all of their children", or that "owner"/"owned" are fungible with "parent"/"child"--have I misinterpreted the docs?

**Comment by gaearon** [comment]
I think it goes like this:

```js
var A = React.createClass({
  render() {
    return <B><C /></B>;
  }
});
```

`A` is owner to `B` and `C`.
`B` is parent to `C`.

>isn't ButtonToggle the owner of the Option components?

I think it's a parent, not an owner. Owner is your custom component that uses them both in its `render`.

**Comment by mcantor** [comment]
I've decided to "discard" the components owned by my top-level scope after using them to spin up components owned by the button toggle itself:

```cjsx
  render: ->
    <div className="ui buttons">
      <input name={ @props.name } type="hidden" value={ @state.value } />
      { React.Children.map @props.children, (child) =>
        <ButtonToggle.Option
          {...child.props}
          handleClick={ @handleClick }
          selected={ @state.value == child.props.value }
        />
      }
    </div>
```

**Comment by mcantor** [comment]
On a semi-related note, is it expected behavior that the spread operator fails when used like this:

```cjsx
{ ...child.props }
```

But works like this?:

```cjsx
{...child.props}
```

I got an "Unexpected `<`" error when I used the extra whitespace... very confusing.

**Comment by gaearon** [comment]
> I've decided to "discard" the components owned by my top-level scope after using them to spin up components owned by the button toggle itself:

It's actually a sensible idea. I'd say it's better than passing some props to who-knows-what children that  may not even know about such props.

**Comment by spicyj** [comment]
This is the sort of thing that parent-based context should work for in 0.14.
