### ISSUE TITLE
Set up context before getInitialState is called

### ISSUE THREAD

**Issue by zpao** [facebook/react#2898]
Initial state can depend on context, so we need make sure context is set up. With recent changes it is now `undefined`. Let's make sure we add a test too :wink:.

**Comment by Dyscrete** [comment]
Context is available to initial state. Perhaps you're creating your DOM descriptors outside of the context?

See here for an example: http://jsfiddle.net/3b4vnpz8/

Hope this helps

**Comment by sebmarkbage** [comment]
@Dyscrete, I believe @zpao is referring to the master branch where this was broken.

**Comment by zpao** [comment]
Indeed, this was an issue filed for us to remember since we knew the details. I sometimes forget there are other people watching the repo :) I appreciate your thorough testing though @Dyscrete. I hope you stick around and help some other people.

**Comment by Dyscrete** [comment]
Thanks @zpao, I'm still in the early stages of learning and I find the best way to learn is solving others issues when I don't have any of my own. Keep up the good work guys!
