### ISSUE TITLE
Passing "this" as the first argument to react methods.

### ISSUE THREAD

**Issue by phzbox** [facebook/react#2899]
Most of my react methods start with "var self = this, ...". A small but very sweet feature would be to pass "this" as the first parameter. As far as I know, this wouldn't be breakable change because most methods don't take any parameters.

So, instead of:

```
var MehComponent = React.createClass({
  componentWillMount: function() {
    var self = this;
    
    some_stuff(function() {
      self...
    });
  },

  render: function() {
   var self = this;

    some_stuff(function() {
      self...
    });
  }
});
```

It would become:

```
var MehComponent = React.createClass({
  componentWillMount: function(self) {
    some_stuff(function() {
      self...
    });
  },

  render: function(self) {
    some_stuff(function() {
      self...
    });
  }
});
```

**Comment by zpao** [comment]
Nah, this isn't very JS-y. If we ever write React in Python that might happen :)

You can make use of built in JS features, namely `Function.prototype.bind`.

```js
  componentWillMount: function() {
    some_stuff(function() {
      // this is now bound to the same this as the componentDidMount,
      // in other words, the component instant
      this...
    }.bind(this));
  },
```

FYI, it would be a breaking change if we were to do this. Half of the lifecycle methods take arguments (eg, `shouldComponentUpdate`)

**Comment by phzbox** [comment]
Makes sense.

I'd argue that we could still pass it as last parameter without being a breaking change. I personally find that having .bind(this) everywhere just pollute the code and makes it harder to read. But then, that's something I can deal with in my own code, without necessary forcing everyone to use my "self" parameter convention : )

**Comment by brigand** [comment]
@phzbox if you enable es6 transforms you can use arrow functions.  They do the equivalent of `.bind(this)` or the self pattern.

```js
var MehComponent = React.createClass({
  componentWillMount() {
    some_stuff(() => {
      this...
    });
  },

  render() {
    some_stuff(() => {
      this...
    });
  }
});
```

**Comment by devssh** [comment]
This comes from scala. It would be good to see self natively in JavaScript. The difference between 'this' and 'self' is that 'this' refers to the current method while 'self' refers to the class containing the function.
It is confusing to use 'this' in a function currently as it usually ends up being scope limited but having 'self' makes the scope of reference really clear
