### ISSUE TITLE
react devtools版本5.0之后，点击Open in editor时，不能跳转到vscode对应文件的行

### ISSUE THREAD

**Issue by zhouhaizhou** [facebook/react#28998]
![image](https://github.com/facebook/react/assets/24632656/e871ff57-b7b8-4a9e-aafb-62ad54f91c78)

**Comment by kassens** [comment]
english version at #28999

**Comment by FristNameCao** [comment]
这个问题你解决了吗？
我至今还在使用5.0的版本
