### ISSUE TITLE
Bug: unexpected Warning: `ReactDOMTestUtils.act` is deprecated in favor of `React.act`.

### ISSUE THREAD

**Issue by salier1** [facebook/react#29000]
I didn't use `act` in `react-dom/test-utils` but I got the following warning :
Warning: `ReactDOMTestUtils.act` is deprecated in favor of `React.act`. Import `act` from `react` instead of `react-dom/test-utils`. See https://react.dev/warnings/react-dom-test-utils for more info.

React version:18.3.1

## Steps To Reproduce

1.run `npx create-react-app test --template typescript`
2.run `cd test`
3.run `npm run test`
4.press `a`

<img width="935" alt="image" src="https://github.com/facebook/react/assets/90126412/be7dc826-3ac3-4717-9bc7-61a04091c70d">

**Comment by Jacobmrose** [comment]
npm install --save-dev @testing-library/react resolved this issue for me.

**Comment by ShanComcast** [comment]
My issue also got resolved. Thanks a lot @Jacobmrose.

**Comment by bluejs** [comment]
you made my day, thanks @Jacobmrose

**Comment by sorinpav** [comment]
We still see this issue. 

The version of @testing-library/react: ^15.0.7
I also did an `npm install --save-dev @testing-library/react` and it still didn't resolve the issue for us, unfortunately. Can this please be reopened?

**Comment by rickhanlonii** [comment]
Unfortunately, there's nothing we can do here. If something is using `act` from `test-utils` you need to find the callsite and either fix it, upgrade the library that's doing it, or file an issue for the library to fix it.

**Comment by eps1lon** [comment]
@sorinpav Your testing framework should add a callstack to the console.error which should help you identify where the wrong `act` is called. `@testing-library/react` should use `React.act` iff it is available i.e. `react@>=18.3.1` is installed next to `@testing-library/react`. Either you have `react@18.3.0` directly installed or you have multiple versions of React installed. Remember, `react@18.3.0` would not be sufficient. It must be `18.3.1` or `19.x`.

**Comment by sorinpav** [comment]
@eps1lon thanks for the reply. There are no instances of `act` from `react-dom/test-utils` in our project, and we only import it directly from React, but I can't remember exactly what version of React we're using. I'll have a look. It's the project at work that I'm quoting here. I'll come back with a comment. Thanks!

**Comment by sorinpav** [comment]
@rickhanlonii understood. Just saw your comment now. (I'm on mobile and it was harder to see)
I'll see what I can do. As mentioned above, we don't call it directly, so it may be only third party modules that are calling into it 🥲..

**Comment by sorinpav** [comment]
Just checked now, and we are on react / react-dom:^18.3.1, but I think I know what is causing it. We're unfortunately still using the enzyme react 17 adapter. Our test codebase is split in between React Testing Library and Enzyme still (long migration process), and I've just spotted that the enzyme react 17 adapter still uses the old import destination. 

Posting this more for others that discover this same issue. For now, I don't think it needs reopening. Thanks guys for the help!

**Comment by parksu0219** [comment]
I was getting the same warning message while using @testing-library/react (v14.0.0).

I updated `v14.0.0 `→ `v14.1.2`, and it worked for me.

```ts
import { act } from '@testing-library/react'
```

**Comment by Navee-n** [comment]
Updating worked for me

**Comment by nditanaka** [comment]
ran into the same issue - thanks @Jacobmrose! running 

```
npm install --save-dev @testing-library/react resolved this issue for me.
```

fixed it for me

**Comment by radika-insfra** [comment]
@Jacobmrose  It resolves my issue.  Thank you <3

**Comment by blentz100** [comment]
In case this helps anyone else:

Bumping `@testing-library/react` to at least `15.0.6` did not clear the warning for me.

I did that and then I followed the [React Hooks Testing Library Migration](https://github.com/testing-library/react-hooks-testing-library/blob/chore/migration-guide/MIGRATION_GUIDE.md) guide and that solved the problem.

**Comment by vijayth2-cerebras** [comment]
It is happening for me in v16.0.1 - the latest release.

**Comment by ri-synth** [comment]
If on React 18, make sure it is on 18.3.1.

Testing library will load the deprecated `react-dom/test-utils` act [if React doesn't export it](https://github.com/testing-library/react-testing-library/blob/v16.3.0/src/act-compat.js#L5).

- In React 18.3.0, only `unstable_act` was exported and not act itself (see [bug](https://github.com/facebook/react/issues/28915)).  ￼
- In React 18.3.1 the commit “Export React.act from 18.3” confirms act is properly exported.  ￼
