### ISSUE TITLE
[React 19] Can't use useActionState (NextJS)

### ISSUE THREAD

**Issue by fernandortec** [facebook/react#29017]
I get this error, trying to useActionState in React19 and NextJS, I followed the documentation and tried using several approaches, but none worked, here's the code and the React Version below

![image](https://github.com/facebook/react/assets/62437672/4185fa8f-73c6-4470-8267-efefff020781)

```
"use client";

import { useActionState } from "react";
import * as S from "./styles";

interface PurchaseFormProps {
	priceId: string;
}

export function PurchaseForm({ priceId }: PurchaseFormProps): JSX.Element {
	const [state, formAction] = useActionState(() => {}, null);

	return (
		<form className={S.form}>
			<button className={S.formButton} type="submit" disabled={true}>
				Comprar agora
			</button>
		</form>
	);
}

```

`
    "react": "^19.0.0-beta-e7d213dfb0-20240507",
    "react-dom": "^19.0.0-beta-1beb73de0f-20240503",
`

**Comment by rickhanlonii** [comment]
Next vendors React so you can't install your own version of React, it forces you to use the vendor version. Next will add React 19 to a future release.

**Comment by ph1p** [comment]
I completely understand the confusion as I received the same error today. This is a little bit misleading as nextjs uses these functions without any context in the examples https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#examples

Or am I missing something?

**Comment by eps1lon** [comment]
`next@14.3.0-canary.45` should have support for `React.useActionState`

**Comment by PolyagaDev** [comment]
> Je comprends parfaitement la confusion car j'ai reçu la même erreur aujourd'hui. C'est un peu trompeur car nextjs utilise ces fonctions sans aucun contexte dans les exemples https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#examples
> 
> Ou est-ce que j'ai raté quelque chose ?
> 
> @fernandortecvous pouvez utiliser `useFormState`à partir de `react-dom`. Celui-ci sera ensuite supprimé et remplacé par `useActionState`.
> 
> **Actions**
> 
> ```js
> "use server";
> 
> export async function submitForm(previousState, formData) {
>   return {
>       name: formData.get("name"),
>   }
> }
> ```
> 
> **composant de formulaire**
> 
> ```js
> "use client";
> 
> import { useFormState } from "react-dom";
> 
> // ...
> const [state, formAction] = useFormState(submitForm, {
>   name: "",
> });
> 
> // ...
> <form action={formAction}>
>   <label htmlFor="name">Name</label>
>   <input type="text" name="name" />
>   <button type="submit">submit</button>
> </form>
> // ...
> ```

have you found a solution? Next makes me use useActionState which is literally nowhere to be found in my 'react' folder. I have version 19.0.0 of react with the latest version of next.js but nothing works.

**Comment by gabbas5** [comment]
I am also in the same state and cannot use "useActionState" hook, I am trying to find out alternate solution.I don't know why they have mentioned  this and not tested its working with nextjs 14

**Comment by MarcGruener** [comment]
@gabbas5 as @ph1p suggests, you should be able to simply replace
`import { useACtionState } from 'react';`
with 
`import { useFormState } from 'react-dom';`

**Comment by smolpaw** [comment]
> @gabbas5 as @ph1p suggests, you should be able to simply replace `import { useActionState } from 'react';` with `import { useFormState } from 'react-dom';`

This worked and the build passed. However it results in this error during development

> Warning: ReactDOM.useFormState has been renamed to React.useActionState. Please update EditInvoiceForm to use React.useActionState.

**Comment by riccardolardi** [comment]
Is there any approx release date for React 19 and Next.js allowing to use `useActionState` ?

**Comment by alexmondaini** [comment]
does react 19 RC comes with `useActionState` ?

**Comment by gabbas5** [comment]
Yes,
Regards,
Ghulam Abbas

On 05-Sep-2024, at 8:19 AM, Alexandre ***@***.***> wrote:

﻿

does react 19 RC comes with useActionState ?

**Comment by rbzdev** [comment]
Run the following command to install the good version of react and reacr-dom canary, who support useActionSate hook width Next JS server action : 

`pnpm install react@19.0.0-beta-4508873393-20240430 react-dom@19.0.0-beta-4508873393-20240430`
