### ISSUE TITLE
[Code Refactor] Replace object checks with isObject function

### ISSUE THREAD

**Issue by c0sc0s** [facebook/react#29020]
I find there were many code place use 'type of xxx === 'object' && xxx !== null'
I think should use a util function named `isObject` to optimize this behavior.
I could add this function to shared and replace the before code.
should i do that? 

Looking forward to your feedback!

**Comment by sophiebits** [comment]
Hi @c0sc0s — thank you for the suggestion but we prefer the code as is. It is clearer to us and this style is understandable to anyone who knows JavaScript without needing to learn the purpose of the helper function.
