### ISSUE TITLE
Switching to React Virtual DOM Element (in React tab) when selecting the element for inspecting.

### ISSUE THREAD

**Issue by kartamyshev** [facebook/react#2905]
It would be great if extension allows us to see what React DOM Element matches Regular DOM Element. I mean, when we click to inspect button in Chrome devtools, React tab becomes active and shows us what element we have chosen.

If we have deeply nested DOM it's quite annoying to click a lot of times until we get some nested element.

So, it might be checkbox within React extension, that works over the behaviour of choosing elements if it needed.

**Comment by gaearon** [comment]
+1. Or a shortcut that would jump up/down to closest composite component.

**Comment by spicyj** [comment]
If you select an element in the Elements tab (using the magnifying glass or with the right-click "Inspect Element") then switch to the React tab, the corresponding component should be selected. I don't think we can do any better than this with the API Chrome gives us.

**Comment by gaearon** [comment]
Can't we implement stepping up/down composite components *inside React tab* with something like Ctrl+Up / Ctrl+Down?

**Comment by kartamyshev** [comment]
Thank you. It works. This is exactly what we need.
