### ISSUE TITLE
Add delete mutability helper

### ISSUE THREAD

**Issue by flying-sheep** [facebook/react#2906]
JS sparse arrays have some advantages.

Setting elements to `undefined` isn’t the same as deleting them, e.g. `[1,,,3].map(console.log)` only prints `1 3`, not `1 undefined undefined 3`.

Therefore there should be a mutability helper that returns a copy with a deleted entry:

```javascript
{ update } = React.addons

let a = [1,,,2,,3]
let b = update(a, {$delete: 1})

console.log(a)  // → [1, undefined×2, 2, undefined×1, 3]
console.log(b)  // → [1, undefined×4, 3]
```

PS: the same of course also applies to objects: `{foo: undefined}` isn’t the same as `{}`.

**Comment by gaearon** [comment]
You can do this with `splice`, something like `$splice: [[index, 1]]`

**Comment by flying-sheep** [comment]
no, not at all.

splice replaces items `a[index]` to `a[index+length]` with the supplied elements.

if there are only two parameters, or the third is undefined (e.g. by calling `splice.apply(..., [index, length,])`, the elements are removed.

if there are more than three, … eeh, [test it yourself](http://jsbin.com/mepolaqeze/1/edit). doesn’t work, that’s for sure.

**Comment by gaearon** [comment]
Oh sorry. I just realized what you meant and in fact I needed the exact same thing today (for objects).

**Comment by zpao** [comment]
Would #2362 cover this?

**Comment by gaearon** [comment]
It's similar but has different behavior for arrays (from Mongo), setting items to `null`.
@flying-sheep What is your use case for sparse arrays with React?

**Comment by gaearon** [comment]
Honestly I think `delete` behavior for arrays makes more sense than following what Mongo does.

My rule of thumb is following: if you can do something with `update`, you need to be able to undo this as well. Since it's possible to `set` things on an array, you need to be able to `unset` them to return to the previous state. Special nullifying behavior seems strange in this case.

**Comment by flying-sheep** [comment]
yeah. it’s pretty strange that it special cases arrays without reason. i’d say we just change #2362 to unconditionally do `delKeys.forEach(function(delKey){ delete nextValue[delKey] })`

**Comment by gaearon** [comment]
We are handing over `update()` to the community so I’m closing this.
Please see my note in https://github.com/facebook/react/pull/6353#issuecomment-204219214.
