### ISSUE TITLE
[React 19]: `eslint-plugin-react-compiler` defines no `main` in its package.json

### ISSUE THREAD

**Issue by SimenB** [facebook/react#29068]
## Summary

`require('eslint-plugin-react-compiler')` fails - one has to do `require('eslint-plugin-react-compiler/dist/index.js')` instead. Happy to send a PR for this once you publish the source code.

Using `0.0.0-experimental-e04a001-20240515`

**Comment by cpojer** [comment]
PR: https://github.com/facebook/react/pull/29072

**Comment by SimenB** [comment]
Hey Christoph! 😀 Didn't notice the source code was out - good stuff 👍
