### ISSUE TITLE
Compiler: Unexpected token error when using double quotes Inside single-quoted JSX prop

### ISSUE THREAD

**Issue by damianstasik** [facebook/react#29069]
React version: 19 RC

## Steps To Reproduce

Use double quote mark in single-quoted JSX string prop like so:

```jsx
export function Component() {
  return (<Message caption='Some "text"' />);
}
```

and you'll get this error:

![Screenshot 2024-05-15 at 20 31 15](https://github.com/facebook/react/assets/920747/4ff2c3f5-5ec9-460b-ae7c-f4c1b1e98fec)

Link to code example:

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgDMoA7OXASwhPwGEIBbbEhE3ACgEp9gAdG-DAS5YNdgB4AsgjBgAhgHME+OHMyVqAXgDkAZUbLeIXBlxHt+APQA+TgG5+AXxCOgA

**Comment by mofeiZ** [comment]
I believe this is actually an issue with `@babel/generator`, which we use to generate readable playground output. If you add the compiler into your build pipeline, jsx babel transforms will run (and produce valid JS). We're currently choosing to not run the jsx transform in playground to keep the output readable.

Going to mark this as a `todo`
