### ISSUE TITLE
Bug: `react-compiler-healthcheck` doesn't recognize when strict mode is enabled with `<React.StrictMode />`

### ISSUE THREAD

**Issue by psychedelicious** [facebook/react#29075]
React version: 18.3.1

## Steps To Reproduce

1. Create a react application
2. Use `<React.StrictMode />` to enable strict mode (instead of `<StrictMode />`
3. Run `npx react-compiler-healthcheck`:
    
    ```sh
    ❯ npx react-compiler-healthcheck
    Successfully compiled 1 out of 1 components.
    StrictMode usage not found.
    Found no usage of incompatible libraries.
    ```

Link to code example:

This repo was created by running `pnpm create vite` and selecting React with Typescript. No changes were made to the code.

https://github.com/psychedelicious/react-compiler-healthcheck_strict-mode

## The current behavior

The health check doesn't recognize when strict mode is enabled with `<React.StrictMode />`.

## The expected behavior

The health check recognizes when strict mode is enabled with `<React.StrictMode />`.

**Comment by zolotoygagash** [comment]
go,here Binace
