### ISSUE TITLE
ReactCSSTransitionGroup not adding "enter" class

### ISSUE THREAD

**Issue by kevinohara80** [facebook/react#2907]
We're having trouble with one of our animations. It's a simple fade in and fade out animation. While stepping through in Chrome dev tools, our element is being rendered on the page but the `.transition-enter` class is never being applied. However, the `.transition-enter-active` class gets applied by itself.

The `.transition-leave` and `.transition-leave-active` seem to be getting added correctly.

Our example code is almost identical to the [Getting Started code in the docs](http://facebook.github.io/react/docs/animation.html#getting-started).

We're running React 0.12.2.

Any help would be appreciated. Thanks!

**Comment by sbrandwoo** [comment]
Do you have a code sample that you can show us on jsbin.com?

Putting in the example code from the documentation appears to work fine for me: http://jsbin.com/dukigutaxe/1/

If you are unable to reproduce, you can check to see if you are re-rendering the component too quickly. I've seen double renders cause problems with transitions before.

**Comment by spicyj** [comment]
Closing due to no response, though this might also be #1326.
