### ISSUE TITLE
[React 19] Compiler: support computed properties using object dot/bracket notation

### ISSUE THREAD

**Issue by gkiely** [facebook/react#29091]
## Summary
Using `obj.value` or `obj['value']` in a computed property causes the compiler to not memoize the component.

Example:
https://playground.react.dev/#N4Igzg9grgTgxgUxALhAHQHYDMobgFwEsIMACAYQgFsAHEhDfACgEpThNTS4Sx9SIAIwBWpALztOXUgDcAhgBtkpAOQBrBAE8VAGikBfANxSeGPrMVQE4yWWkBtIcIB08hQF1l+GFb139UjAI+LBkADwAfGEA9BGYRpgg+kA

I see there is a todo prefix in the compiler error. Feel free to close if this is a known issue.

**Comment by josephsavona** [comment]
Thanks for filing this! This is a case that the compiler is handling - ie it is syntax we know we don’t support yet and where we skip compilation. 

This is on our todo list, so I’m going to close the issue but we will definitely address as we have time.
