### ISSUE TITLE
[React 19] Fiber is missing a debug information

### ISSUE THREAD

**Issue by scirill** [facebook/react#29092]
## Summary

In **React 18**, Fiber exposed `_debugSource`

<img width="210" alt="updateQueue null" src="https://github.com/facebook/react/assets/18378585/0d989b4c-0993-4e49-883b-039b1f0c81ba">

In **React 19** (19.0.0-rc-915b914b3a-20240515) this was changed to `_debugInfo` but the value is alway `null`

<img width="203" alt="updateQueue null" src="https://github.com/facebook/react/assets/18378585/e74bdf29-cea2-49fd-b00a-755eb92bc495">

**Comment by scirill** [comment]
@sebmarkbage Hi, I see you made the changes in the related code. You mentioned in the commit that the change is only for the server rendering, but now any debug information is missing for the client rendering components. 
Thanks

**Comment by kblauhut** [comment]
This seems to have been removed with https://github.com/facebook/react/issues/29092

**Comment by rickhanlonii** [comment]
This was removed in https://github.com/facebook/react/pull/28265, see that PR for the reasoning.

The internal fiber structure is internal and will break between any release.

**Comment by scirill** [comment]
@rickhanlonii thank you for your answer, I understand the Fiber structure can be changed, but this change also broke the way DevTools displays the source. The lazy approach getting the source returns different information.

Before this change, the source in DevTools pointed to the place that used the Component in the project source file.

Now it will point to the place that defines the component in the compiled output of the build tool.

For example, before, if I had this code:

`src/Hello.tsx
`
```
1: function Hello() {

2:    return <Typography>Some text</Typography>

3: }
```

The source for `Typography` pointed to {fileName: "src/Hello.tsx", lineNumber: 2}

But now the DevTools point the source to one of the runtime chunk files of the build tool (I'm using Vite so it shows like this `chunk-OITURYR5.js?v=29ba3b73:1389`) And this information is absolutely pointless for the user for debug purposes.
Because of this change #28351 , DevTools 5.2 version is now showing the wrong source even for React 18,
Should I open a new issue for this?
Thank you

**Comment by rickhanlonii** [comment]
The change to the source is expected I think, but breaking 18 isn't. Yeah please file a issue specific for that cc @hoxyq

**Comment by hoxyq** [comment]
> DevTools 5.2 version is now showing the wrong source even for React 18

For the past few weeks I've heard from many people the same feedback on the source location stuff, that people actually want to see the JSX part and not the actual component declaration, which totally makes sense to me. We would need to change the UI in DevTools for it though, because we have different features relying on the same source information. I will follow-up in https://github.com/facebook/react/issues/29164.
