### ISSUE TITLE
[React 19] React compiler is warning on mutating values in refs that are used in JSX.

### ISSUE THREAD

**Issue by NickBlow** [facebook/react#29106]
## Summary

When mutating a ref value in an event handler (e.g. when dealing with uncontrolled inputs), the React Compiler ESLint rule is giving the following error:

ESLint: Updating a value used previously in JSX is not allowed. Consider moving the mutation before the JSX(react-compiler/react-compiler)

Linked CodeSandbox:

https://codesandbox.io/p/sandbox/kind-mirzakhani-qzw4t3

Linked Compiler Playground:

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwFkBPAQU0wAoAlPmAAdNvjiswNJpQQBJOpii4ASqXwBefFDAINJfAB58ACQAq7ADJKVuAKLyAtgjoEAPvjpVK+AHz4-D6UlIIA3OLi+JLSBAAWZHSE8gDKUABGzkwEOvwIAG5uuMj4GmSMAHQAYjjODkXuxpY2tTD1LsX+wlqBYhIxhcWVmDBD7gAipBTUQpF00TH4TEb8JHKKyqqGlXCwY+74AGRH+Ovydtuku-vD5whgwv1LS1J0Mmcb2p8XW+rXexgB1wlXuYAA2gAGAC68xeMTekHklUoEAA5msNhFFi97pd-iQbkDhgUyJQoAhvqIQNS4UsAL6LenzRZjXCwNj8HEmEh1fCsdJZHJaYCJZJpTLZXD0-zcmLGJh-fC4TiYBBaan3an4MYkEV4v6Gen4AD0soGS2MGVUuFYytV6upYElOWp-kFUuMJutuFtdHNLy9vPaAfw2LojLoIHpQA

This feels slightly wrong to me as the docs specifically call out manipulating the DOM with a ref as a pattern:
https://react.dev/reference/react/useRef#manipulating-the-dom-with-a-ref

I guess this is because you can do unsafe changes to refs but might be better off as a warning rather than an error?

**Comment by HoseinKhanBeigi** [comment]
To resolve this error while following the React guidelines, you should ensure that you handle ref mutations in a way that is safe and predictable. In this case, moving the mutation out of the JSX block can help.

` const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const input = fileInputRef.current;
    if (input && input.files) {
      const file = input.files[0];
      console.log(file);

      // Clear the input value
      input.value = "";
    }
  };`

**Comment by codingedgar** [comment]
this is the original code

```ts
export default function MyApp() {
  const fileInputRef = useRef < HTMLInputElement | null > (null);

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (fileInputRef.current && fileInputRef.current.files) {
      const file = fileInputRef.current.files[0];
      console.log(file);
      fileInputRef.current.value = ""; // InvalidReact: Updating a value used previously in JSX is not allowed. Consider moving the mutation before the JSX. Found mutation of `fileInputRef` (10:10)
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input type="file" ref={fileInputRef} />
      <button type="submit">Submit</button>
    </form>
  );
}
```

this gets rid of the error

```ts
export default function MyApp() {
  const fileInputRef = useRef < HTMLInputElement | null > (null);

  const inputRef = fileInputRef.current;
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (inputRef && inputRef.files) {
      const file = inputRef.files[0];
      console.log(file);
      inputRef.value = "";
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input type="file" ref={fileInputRef} />
      <button type="submit">Submit</button>
    </form>
  );
}
```

but this is also an error:

```ts
export default function MyApp() {
  const fileInputRef = useRef < HTMLInputElement | null > (null);

  const inputRef = fileInputRef.current;
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (inputRef && inputRef.files) {
      const file = inputRef.files[0];
      console.log(file);
      inputRef.value = ""; // InvalidReact: This mutates a variable that React considers immutable. Found mutation of `inputRef` (11:11)
    }
  };

  const handleBlur = () => {
    handleSubmit();
  }

  return (
    <form onSubmit={handleSubmit}>
      <input type="file" ref={fileInputRef} onBlur={handleBlur}/>
      <button type="submit">Submit</button>
    </form>
  );
}
```

[playground](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwFkBPAQU0wAoAlPmAAdNvjiswNJpQQBJOpii4ASqXwBefFDAINJfAB58ACQAq7ADJKVuAKLyAtgjoEAPvjpVK+AHz4-D6UlIIA3OLi+JLSBEzKqoba+CRyionqpAB0cLAwbriRElJ0MvgAFmR0hPIAylAARs5MBDr8CABuhcj4GmSM2QBiOM4O3e7GljYjMGMuhf7CWoFiEjFdhdmYBRO4ACKkFNRCxdEx+ExG-An2yQBk95eZhtlp8mDCaxcXpeXvCBStySOQBYAA2gAGAC6xR+MT+EHk2UoEAA5vwARFzj9gVkSNlOmRKFBATpRCAKXCLgBfc40s4lOKVaq1BAAIRJMBSQm0qxxLJq9SaLVwp3pUQkBVwsDY-AFxhIo3wrAazVaWmAVSFCDVopp-gFMWMePwuE4mAQWgpAIp+AKJE1ALsIJINJVdE5sE12rZXpgNIA9Ib1hdjI1VLhWGaLVaKWARa0Kf49a1jIGI7go3QQz900q5rn8Ni6HS6CAaUA)

**Comment by codingedgar** [comment]
This is my best workaround:

```ts
export default function MyApp() {
  const fileInputRef = useRef < HTMLInputElement | null > (null);

  const { handleSubmit, handleBlur } = () => {
    const inputRef = fileInputRef;
    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
      event.preventDefault();

      if (inputRef.current && inputRef.current.files) {
        const file = inputRef.current.files[0];
        console.log(file);
        inputRef.current.value = "";
      }
    };

    const handleBlur = () => {
      handleSubmit();
    }
    return {
      handleBlur,
      handleSubmit
    }
  }


  return (
    <form onSubmit={handleSubmit}>
      <input type="file" ref={fileInputRef} onBlur={handleBlur} />
      <button type="submit">Submit</button>
    </form>
  );
}
```

[playground](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwFkBPAQU0wAoAlPmAAdNvjiswNJpQQBJOpii4ASqXwBefFDAINJfAB58ACQAq7ADJKVuAKLyAtgjoEAPvjpVK+AHz4-D6UlIIA3OLi+JLSBMD4ABZkdITyAMpQAEbOTLgANEkpaQgAQpSw+AC+2kHCWoFiEjFSdDL4TMqqhrUkcopd6qSRzbFtBMmpGdm5BDr8CABubrjI+BpkjAB0AGI4zg7L7saWNnswBy4r-vWN0TEPSytbmDBP7gAipBTUQiP3Dw6Rn4nXshi2cFgb3c+AAZLCOoNwZCYNDcFs+vIwMImoDAa12piELVQd1SBCoc8iWAANoABgAuiM8Q8CRB5FtKBAAOb8IkRAF40lDEgU1HPRZkCrEnSiEBy5l4qqCqr-UYEibFeTlSrzW4iQUxSYlTI5PJ-FWCt64WBsXF443aiowfKGopTBCm2aWiTKuhRCTW21BQXGEj7fCsL15LTAR2emZ5Kr+N3GYX4XCcTAILRyoly-BvEixol2MkkGqsHUwWPx6s1AD0KdGMWMWVUuFYGazOblYETuDl-mjuGMDfbuE7dGbgLH4YuM-wArofpAVSAA)

Still think refs are a special case that shouldn't be tracked as normal props.

The first iteration I made used `const inputRef = fileInputRef.current;` but that would be a bug. Thankfully `, const inputRef = fileInputRef;` is enough to work.

**Comment by wojtekmaj** [comment]
I believe I have a similar issue that I can't really wrap my head around:

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwEEpcIAFSsgJ5M6AcwBqTYhAAqACygBbAEZ0yTSgAoAlPmAAdNvjiswBAG6SEEAEql8AXnxQwCWyQ10qlLQG4DB-HxaBmZWfFYeCGFcBBgAUToYmG1dAMD8JhJ8DQBCCyk3ADo4WBgERJ19Q3T8MtxYOj9q-ABff2b8qyKSmDLEwsx+AW0mwLa6NODGFjYyl1wJKRSqmszsvMsbUmLS8txKtJq6htH08cP8AHpL-ABlbkx8MjpCWoR5-E6IfG58UzI8Bcvt1dv1MBQXCMgZsQb09js4YlpEwFAgHPgAAync6GKahNgRKKJWIAGQQZDMCGWFzWuWB2x6fX2qWagWOMEaFxxNXmyNR0FwGhS9gAfCyamz3ggFpsoc0WgAafAAZgxGN8aW5b3qHOyFwAPIQmGYLoFCdFYgkkvZgObifF7eMJeE6JELTAyRSEDa7UlPZSnekRab8Pqvm8SDb6SQWldg819ZcjWZ44ENXRxiAWkA

Extracting ref value in function body seems to make it go away, but I have no clue how I could avoid "This mutates a variable that React considers immutable" issue 🫣 :

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwEEpcIAFSsgJ5M6AcwBqTYhAAqACygBbAEZ0yTSgAoAlPmAAdNvjiswBAG6SEEAEql8AXnxQwCWyQ10qlLQG4DB-CMTc0sIAFFKBAUEOgJHCyk3ADo4WBgY3D86APxaBmZWfFYeCGFcBBgw2IrtXRzAphJ8DQBCBKsIqIydfUNAwPTcWDos-vwAX38+-HbwyOjYpMx+AW1RianAvMYWNnSXXAkpWt6xxua20M6F3B76-sHh9cDJ7OmAenf8AGVuTHwyHRCPh9ggQlJ8Nx8KYyHh7rNrhklhQXGt4Vd5kjUjB0rFpExog58AAGdavHLbApsYqlaowAAyCDIZgQJ3u51aCMxsTu0wGYKe93J0wO+Oi0FwGlq9gAfHU+SCEAcjlY0dNxgAafAAZmJxN8OWF-KGMDYGnuAB5CEwzPdAjSyhUquUYPZgA66c6Kq8xva6CVHQymSy3R6XYzmQgff0ZXb8BbZoqSG7Zm5xvh3rHphb3tazFnAga6K8QOMgA

**Comment by josephsavona** [comment]
Thanks for posting this! I've put up a fix in #29591. Our apologies for overlooking this issue earlier.

Note that it's okay to modify a global variable during an event handler or an effect, but be careful that the child component doesn't call this function during render.

**Comment by adubrouski** [comment]
@josephsavona you are merged this fix into babel-plugin-react-compiler, but ESLint will throw error on it

**Comment by josephsavona** [comment]
@adubrouski the eslint plugin is powered by the babel plugin, this fixes both.

**Comment by NMinhNguyen** [comment]
@josephsavona amazing work! Are you planning to publish a new version of the ESLint plugin soon?

**Comment by rostero1** [comment]
Is there a hint to let the arg know that's a ref?  Or is there another pattern I should be using?  I'm still getting this error, but maybe I'm doing something incorrectly.

```
function useAdjustScroll(ref: React.RefObject<HTMLDivElement>) {
  React.useEffect(() => {
    if (ref.current) {
      ref.current.scrollTop = 0;
    }
  }, [ref]);
}
```

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEUYCAggCYBWpOAynDBADYsAUMCayRASggCGuAHQC0AeQBG1BLgA8ACQAqAWQAyAETwA3AKIsEAWwSYcAPgCURYAB1i-IaNII9aNHJzt21gLzmbeyJgojw0Ik5uEThYLjNrOwcQoi40aNjTHBEwJlYWZQgAByJfIgAGAG4gkIBfapqAGiIAbVSAXUsqzBqQGqA
