### ISSUE TITLE
Deprecate React.addons.classSet

### ISSUE THREAD

**Issue by zpao** [facebook/react#2910]
This has no dependencies so I think we should either publish it as a standalone module or direct people to something else from the community. I'm inclined to do the latter since it means we can wash our hands of it. Our internal usage of `cx` is tied to our transforms so we've said no to features that would be useful to others outside FB. I'm concerned we'd do that again.

Any suggestions for existing projects that we can point to?

**Comment by syranide** [comment]
Can't we just link to a bunch of "useful scripts" in the docs and leave it at that? People are free to use/modify them, it's implied they're not being maintained and are there just for getting people started.

I feel like a lot of people don't understand the current state of `React.addons`, but expect them to be full-blown frameworks and updated with every feature conceivable. Publishing on NPM kind of continues that trend and I suspect no-one on Team React really cares about the addons enough. So I would say, make them available in the docs (as code/files) and let the community sort out publishing/improving/direction.

**Comment by chenglou** [comment]
...Can I "steal" the code and post it somewhere else under my name? I do need it for another CSS repo of mine, and it's really not React-specific.

**Comment by zpao** [comment]
After talking with Jed at the conference, I think I'll just point people at https://github.com/JedWatson/classnames.

**Comment by jquense** [comment]
Pete hunt already has react-classset module on npm I believe as well

**Comment by iclanzan** [comment]
@jquense According to the [README](https://github.com/petehunt/react-classset) react-classset has been deprecated in favor of the above mentioned library.

**Comment by chenglou** [comment]
It is. They're pretty much the same except for some negligible differences so I deprecated the former (the latter has an active maintainer).
