### ISSUE TITLE
[React 19] React compiler strips `await` from `for await` loops

### ISSUE THREAD

**Issue by yepitschunked** [facebook/react#29113]
## Summary

React compiler is compiling

```
async function MyApp({ something }) {
  for await (const deferredState of foo) {
    // do stuff
  }
}
```

into

```
async function MyApp(t0) {
  for (const deferredState of foo) {
  }
}
```

i.e the `for await` became a regular `for`. 

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAQzATwHZwAQBmUuALgJYTZ4CymAggA4MAUwekAtgiQBZnYBzPAF8AlHmAAdKoQgw8aAO5oyJPMziUwagCYICCGDAQ6AyiTQkEeCAVkRxUmXjwB6V3h0R2JKAQLSLsLSwdggwkA

**Comment by josephsavona** [comment]
Thanks for the heads up!

**Comment by josephsavona** [comment]
Fixed, thanks again for reporting!
