### ISSUE TITLE
parsePluginOptions lowercasing breaks runtimeModule option

### ISSUE THREAD

**Issue by yepitschunked** [facebook/react#29110]
The plugin options parser lowercases all option values : https://github.com/facebook/react/blob/94896cb8c5b1dfc80aa947ac9b273b6b9447571f/compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Options.ts#L201

This breaks the `runtimeModule` option on case-sensitive filesystems (and the module path happens to contain uppercase characters).

**Comment by josephsavona** [comment]
Thanks for the heads up!
