### ISSUE TITLE
Silent exception

### ISSUE THREAD

**Issue by roman01la** [facebook/react#2912]
It turned out that anything which might go wrong will not be caught in [this component](https://github.com/roman01la/github-issues/blob/1086c15577bf76048db9872da2c53aa07a83dde3/src/components/issue-item.jsx). I've dropped [two undefined function calls](https://github.com/roman01la/github-issues/commit/1086c15577bf76048db9872da2c53aa07a83dde3) on a separate branch, so everyone can try to reproduce this.

Fetch [issue-1](https://github.com/roman01la/github-issues/tree/issue-1) branch and run `npm install -g webpack && npm install && webpack` to build the project.

Quick debugging showed there are number of `try...finally` blocks and so exception is not being caught.

[This issue](https://github.com/facebook/react/issues/2626) might relate, also I noticed a bunch of similar ones without code example, so this might help.

**Comment by spicyj** [comment]
try/finally without a catch shouldn't suppress exceptions – are you able to reproduce the error in a standalone jsfiddle?

**Comment by roman01la** [comment]
@spicyj Unfortunately no, I've tried to code similar case, but it works just fine. Looks like you need to run the project.

**Comment by spicyj** [comment]
In my Chrome 40, I see this:

![image](https://cloud.githubusercontent.com/assets/6820/5870620/5da80072-a286-11e4-833d-11f80a432820.png)

The Promise created in your `fetch` module is swallowing the exception. You'll notice that if you put a breakpoint on the catch on the `GitHubAPI.fetchIssues` promise, that code is called with the error object corresponding to the `this.v()` call.

**Comment by roman01la** [comment]
@spicyj Whoa, thanks! But how exactly this exception is being caught in the Promise? I can't get it looking at the call stack.

**Comment by spicyj** [comment]
As I understand it, the native implementation of promises turns exceptions into promise rejections automatically – you can't see the code in the call stack since it's not written in JS.

**Comment by danvk** [comment]
In case it's helpful to anyone... I also ran into this problem and it was also a bug in my code relating to promises. At least with [Q][], exceptions are swallowed up until you call `.done()`.

My code which triggered `.render()` looked like this:

```javascript
fnThatReturnsPromise().then(val => {
  this.setState({val: val});
});
```

The solution was to add [`.done()`][2]:

```javascript
fnThatReturnsPromise().then(val => {
  this.setState({val: val});
}).done();
```

This tells Q that you're done with the promise and won't be adding any `.fin()` error handlers, so it's save to raise the exception.

[q]: https://github.com/kriskowal/q
[2]: https://github.com/kriskowal/q#the-end

**Comment by przeor** [comment]
@spicyj @roman01la I am just curious if you have the same problem (or you know the solution) with the silent exceptions in reactjs:

I have a hard time with silent breaking my react time while debugging. I understand that it's useful that when my app is on production to not throw exceptions.

I am talking about a situation when my app's component will break silently if the JSON endpoint change (just example). Is there any way to turn it off (the silent breaking the reactapp)? It would save a lot of time for many people (I believe that more reactjs devs have similar problem).

**Comment by spicyj** [comment]
I'll repeat myself again:

**React does not eat your exceptions. If some part of your code is throwing an exception but it's not bubbling to the top level, something (not React) is catching them. Promises do this by default and are a common cause if you don't terminate every promise chain with a `.done()` call, but other libraries could also catch exceptions.**

**Comment by przeor** [comment]
@spicyj thanks for your patience. Do you know any good blog post/more reference of cases how someone has handled this kind of unwanted behavior ?

**Comment by spicyj** [comment]
Here's a post about the promises issue:

http://blog.taylormcgann.com/2014/08/21/catch-errors-javascript-promise-chains/

**Comment by przeor** [comment]
@spicyj thank you very much!!!

**Comment by bjnsn** [comment]
It seems that the current versions of promises don't require done - see: http://stackoverflow.com/questions/26667598/will-javascript-es6-promise-support-done-api
