### ISSUE TITLE
[React 19] `transformOrigin` is Missing From Type `SVGAttributes`.

### ISSUE THREAD

**Issue by daniel-nagy** [facebook/react#29134]
## Summary

In React 18 the following code worked with out error.

```jsx
<svg transform-origin="..." />
```

Since React 19, this will error. The required syntax is now

```jsx
<svg transformOrigin="..." />
```

However, `transformOrigin` is missing from `SVGAttributes`, so this results in a type error.

I was going to open a PR to add this but the types package for React 19 appears to be private.

## Workaround

```typescript
declare module "react" {
  interface SVGAttributes<T> {
    transformOrigin?: string | undefined;
  }
}
```

**Comment by pavitra-infocusp** [comment]
`transformOrigin` does not work with React 19.

![Image](https://github.com/user-attachments/assets/3dbb57d0-eaba-46a5-98ce-7ef72a2b71b9)

![Image](https://github.com/user-attachments/assets/b222a59a-22e8-4cf5-ad66-437768f6d0be)

**Comment by pavitra-infocusp** [comment]
It works when used in styles prop

![Image](https://github.com/user-attachments/assets/f50a7b3d-c43a-4857-ad18-a3c65ba20413)

**Comment by mgreystone** [comment]
This is still an issue.

Adding a `transform-origin` prop will work but with the warning: 
> Invalid DOM property `transform-origin`. Did you mean `transformOrigin`

This is not correct, as `transform-origin` is a valid attribute on SVG elements. Ignoring this warning will result in a `transform-origin` attribute as expected.

---

Adding a `transformOrigin` prop does not work. There is a typescript error:
> Property 'transformOrigin' does not exist on type 'SVGProps<SVGGElement>'.

If you ignore this type error & render anyway, this results in a camel-cased `transformOrigin` attribute, which is not a valid attribute.

---

React will need to either
* allow the hyphen-cased `transform-origin` prop or
* transform the camel-cased `transformOrigin` prop to `transform-origin` in the DOM.

Right now, there is no way to set this attribute in JSX without a warning.
