### ISSUE TITLE
Bug: Cannot run compiler playground locally

### ISSUE THREAD

**Issue by abizek** [facebook/react#29137]
After installing deps with `yarn` in the compiler workspace and building the babel plugin, next throws this error on running `yarn dev` in playground
```
Compiling /page ...
 ⨯ ./app/page.tsx
Error: Cannot find module '.../react/compiler/node_modules/babel-plugin-react-compiler/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

https://github.com/facebook/react/pull/29122 should fix it but for some reason, it doesn't.

I was able to get it running locally by doing a yarn link on the babel plugin. Is this the intended way? Can we use the workspace to link the built plugin?

cc: @poteto

**Comment by josephsavona** [comment]
Thanks for reporting. You should be able to run the playground locally with `yarn dev` from the `compiler/` directory. Does that work?

**Comment by abizek** [comment]
Yes! It works :smiley:
