### ISSUE TITLE
React compiler healthcheck (and ESLint plugin) ignores all files if a babel.config.js file is present

### ISSUE THREAD

**Issue by guillaumebrunerie** [facebook/react#29135]
## Summary

Create the following two files in a new directory:

```
// index.jsx
const App = () => <div />;

// babel.config.js
export default {};
```

Then run `npx react-compiler-healthcheck --src index.jsx`. It reports `Successfully compiled 0 out of 0 components.`

Then remove the `babel.config.js` file (or comment out the line inside it) and run `npx react-compiler-healthcheck --src index.jsx` again. It now reports `Successfully compiled 1 out of 1 components.`, as expected.

**Comment by guillaumebrunerie** [comment]
In my real codebase it is not enough to comment out the contents of `babel.config.js`, I need to remove it entirely (or rename it).

With it I get `Successfully compiled 0 out of 0 components.` and without it I get `Successfully compiled 370 out of 406 components.`

**Comment by guillaumebrunerie** [comment]
This affects the ESLint plugin as well, with a `babel.config.js` it silently doesn’t report any errors, and removing it makes the ESLint plugin work.

**Comment by poteto** [comment]
Thanks for reporting. Could you share a repro app please?

**Comment by guillaumebrunerie** [comment]
@poteto The OP contains a minimal repro, which I assumed would be enough to investigate the problem. Or do you need an actual working app?

**Comment by poteto** [comment]
an actual app would be ideal, there are many variables when it comes to builds so it'd help us figure this out more easily. fwiw I've run the healthcheck script on a few repos with babel configs

**Comment by guillaumebrunerie** [comment]
Here is a real project of mine with the same issue: https://github.com/guillaumebrunerie/LD55.

**Comment by poteto** [comment]
I'll look into it, I think this is something to do with the eslint plugin picking up your config, and since it's empty, it doesn't run the compiler
