### ISSUE TITLE
"This page doesn’t appear to be using React." all the time!

### ISSUE THREAD

**Issue by manoelramon** [facebook/react#29158]
I am running a project in react and I installed the latest React Dev Tools plugin 5.2.0 (5/8/2024). For some reason, when I test on my webpage built using react, I got the message "This page doesn’t appear to be using React." all the time!

I tested on Chrome and Brave (both on their last versions).

Thanks

**Comment by RafaelJohn9** [comment]
repo link Or screenshots ?!?!

**Comment by rickhanlonii** [comment]
@manoelramon if you can provide more info we'll reopen. It's not clear if this is a bug (like spamming the console) or expected (like the extension showing the tooltip on click).
