### ISSUE TITLE
[Compiler Bug]: don't uses dependecies of useMemo

### ISSUE THREAD

**Issue by Altro31** [facebook/react#29169]
### What kind of issue is this?

- [X] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhASwLYAcIwC4AEwUYCAsghhAL4EBmMEGBA5DAgIZx4sA6AdgIQAPHPnpR+3NBH4EyATwCCWLAApgBdvwAmCGAWoBKIgIEECcWWEL8OGBGAIBeAiXKUIatSecA+AgADJQAbPEYCABJgMg48AAsAOhgOXSYfakCAGgBtbT0YAF0jMzktBDxYOQAeAGEmLCUCOwcwZ2AWx2oAej8BalKhUVxCOklpWQJ67CUNZvsEQxNgUosrfhsJEJDOlyDoztoAJQgdGABbgHMoBAAvQNXyypganTQANz8ACQRtiAIAOq4EI6IhjbaHardN6fADc-RA1CAA

### Repro steps

1. Look at useMemo. 
2. Dependecies are not used in compilation

### How often does this bug happen?

Every time

### What version of React are you using?

playground

**Comment by josephsavona** [comment]
This is expected behavior! The code in this example does not need to be memoized - it’s a template string which can be cheaply compared for equality later - so the compiler removes the unnecessary useMemo.
