### ISSUE TITLE
Bug: Displayed content is not handled properly. 

### ISSUE THREAD

**Issue by ashishsingh752** [facebook/react#29168]
At the "Adding Interactivity" section of the React documentation, under "State: a component’s memory," there are 12 content items to show. When clicking on "show details" for the first content item (1/12), the displayed content is not static, unlike the others.

React version:
v18.3.1

## Steps To Reproduce

1. Go to Home page of the react [https://react.dev/](https://react.dev/)
2. Click on Learn React
3. Navigate to "Adding Interactivity"
4. Scroll to "State: a component’s memory"
5. Click on "show details" for the first content item (1/12)

Link to code example:

https://github.com/facebook/react/assets/99067547/b87f8b01-4ac9-42a2-9553-ff3ea0c89800

## The current behavior
* Browser: Chrome
* Operating System: Windows 11
* Device: HP Pavilion Laptop
* Screen Resolution: 100%

## The expected behavior
The displayed content should remain static, consistent with the behavior of the other content items.

## Additional Notes
This issue was observed on Chrome Browser in Windows 11 on an HP Pavilion Laptop with a screen resolution set to 100%.

**Comment by tjuandev** [comment]
Tested here and saw that the screen size that this bug appear is about 1940px:


https://github.com/facebook/react/assets/67200208/81f53ad4-5530-44d3-bdbe-383fc458a2a3

**Comment by tjuandev** [comment]
OH i found the possible reason, look at this:


Uploading Screen Recording 2024-05-19 at 23.20.46-1.mov…

**Comment by ashishsingh752** [comment]
Yes,
As I mentioned  It happen in my laptop when I open it at screen set to 100%.

**Comment by ashishsingh752** [comment]
noy yet resolved
