### ISSUE TITLE
[React 19] precedence prop is not respected when used on style element

### ISSUE THREAD

**Issue by souporserious** [facebook/react#29225]
## Summary

Setting the `precedence` prop on a `style` element with a unique `href` does not seem to have any affect and the style elements will be ordered based on where they were in the React tree. 

[CodeSandbox Demo](https://codesandbox.io/p/sandbox/react-style-precedence-bug-yxfs24?file=%2Fsrc%2FApp.js%3A9%2C15)

I expected the style tags to be grouped and ordered based on precedence. [This PR](https://github.com/souporserious/restyle/pull/3) shows an example of the output when used with an atomic class name approach.

**Comment by eps1lon** [comment]
Simplified repro: https://codesandbox.io/p/sandbox/magical-oskar-8gnqgd?file=%2Fsrc%2Findex.js%3A23%2C60

@souporserious  Can you check if the same happens with `renderToString` and `renderToPipeableStream`?

**Comment by eps1lon** [comment]
I just realized, you're using `style` not `link` tags. `precedence` is specific to `link` tags. There's no `<style precedence />` which is probably also why React transforms these into `data-*` attributes?

@gnoff Should we just warn here instead of silently converting these props to `data-*` attributes? React 18 left these props as-is.

**Comment by souporserious** [comment]
Yeah, for sure! Added another CodeSandbox demo here that showcases all three: https://codesandbox.io/p/devbox/react-style-precedence-bug-rendertostring-rendertostaticmarkup-rendertopipeablestream-z9zmcl?file=%2Findex.js%3A3%2C1-5%2C26

**Comment by eps1lon** [comment]
> Yeah, for sure! Added another CodeSandbox demo here that showcases all three: [codesandbox.io/p/devbox/react-style-precedence-bug-rendertostring-rendertostaticmarkup-rendertopipeablestream-z9zmcl?file=%2Findex.js%3A3%2C1-5%2C26](https://codesandbox.io/p/devbox/react-style-precedence-bug-rendertostring-rendertostaticmarkup-rendertopipeablestream-z9zmcl?file=%2Findex.js%3A3%2C1-5%2C26)

Thank you. This wasn't using React 19 but React 18. Though it doesn't change much in React 19: https://codesandbox.io/p/devbox/react-style-precedence-bug-rendertostring-rendertostaticmarkup-rendertopipeablestream-forked-7cwxjk?file=%2Findex.js%3A3%2C1-5%2C26&workspaceId=ae5ed9d5-7ce3-4b4a-a32e-93bfc31fc065

**Comment by gnoff** [comment]
@souporserious we had an error in our docs. the `precedence` value is arbitrary and can be anything. React infers no special meaning from the value used but instead just assumes that earlier precedence values are "lower" precedence and later ones are "higher" precedence

If you name your precedences like "low" and "high" and you want that to be reflected in how React treats them then React must encounter "low" first and "high" second

**Comment by gnoff** [comment]
Fixing docs here: https://discord.com/channels/514829729862516747/1178814684858687588/1243327260086505542

**Comment by eps1lon** [comment]
Fixed:
> Thank you for the clarification in the docs! This makes much more sense now 😄
-- https://github.com/reactjs/react.dev/pull/6908#issuecomment-2128159797
