### ISSUE TITLE
Bug: Nested lazy components cause rerendering

### ISSUE THREAD

**Issue by raymondwang** [facebook/react#29235]
This is a duplicate of https://github.com/facebook/react/issues/27573, which was closed without response. We're noticing this issue at scale, and it's fairly pronounced, with hundreds of rapid re-renders triggered by a single lazy component. I've forked the replication from original issue to demonstrate that this is still an issue in React 19:

https://codesandbox.io/p/sandbox/react-lazy-rerender-bug-forked-q4q6ym

## The current behavior

The lazy parent component renders multiple times:

<img width="181" alt="Screenshot 2024-05-23 at 10 54 06 AM" src="https://github.com/facebook/react/assets/4248263/482a32b0-d1e0-4220-a2db-33a5e0cb9254">

(In our environment, we've seen the number of re-renders proliferate to the hundreds. This matches the below reproduction.)

## The expected behavior

The lazy parent component should only render one time.

---

The original issue had a reply that included a reproduction that matched the issue we're experiencing more closely: https://codesandbox.io/p/sandbox/react-lazy-suspense-5g75x3

Similar to what we're seeing, this repro has hundreds of re-renders, and the number is nondeterministic.

<img width="105" alt="Screenshot 2024-05-23 at 11 06 11 AM" src="https://github.com/facebook/react/assets/4248263/7871459c-de6e-4880-933a-da83498d4720">

<img width="103" alt="Screenshot 2024-05-23 at 11 06 21 AM" src="https://github.com/facebook/react/assets/4248263/78525dd5-4f2e-49d2-b719-122139423830">

---

Our workaround for now is a lightweight replacement for `Suspense` using the Transition API to defer its lazy children, for usage in nested lazy contexts:

```tsx
export const DeferredSuspense: FunctionComponent<SuspenseProps> = (props) => {
  const [isDeferred, setIsDeferred] = useState(true);

  useEffect(() => {
    startTransition(() => setIsDeferred(false));
  }, []);

  if (isDeferred) {
    return props.fallback;
  }

  return <Suspense {...props} />;
};
```

**Comment by Aryant01** [comment]
hey @raymondwang . Can you please elaborate the issue and the expected result a bit more for the better understanding. That'll be really helpfull.

**Comment by raymondwang** [comment]
@Aryant01 The issue is that a Suspense rendered within another Suspense causes errant rerendering of the component within the first Suspense. The examples in the code sandboxes are more illustrative, but here's a brief example:

```tsx
function Grandchild() {
  return <p>Hello world!</p>
}

function Child() {
  const LazyGrandchild = React.lazy(() => import('./Grandchild'));

  return (
    <Suspense>
      <LazyGrandChild />
    </Suspense>
  );
}

function App() {
  const LazyChild = React.lazy(() => import('./Child'));

  return (
    <Suspense>
      <LazyChild />
    </Suspense>
  );
}
```

Here's what I'd expect to happen:

1. App renders
2. App lazily imports Child
3. Child renders
4. Child lazily imports Grandchild
5. Grandchild renders

Instead, here's what's actually happening:

1. App renders
2. App lazily imports Child
3. Child renders
4. Child lazily imports Grandchild
5. Child _rerenders_
6. Grandchild renders

I _think_ that what's happening under the hood in step 5 matches what's described here: https://react.dev/reference/react/Suspense#preventing-already-revealed-content-from-hiding — because Child sees a suspended component, its suspense is hoisted up to the closest parent suspense in App.

This issue can balloon far out of control very easily, as seen in this reproduction: https://codesandbox.io/p/sandbox/react-lazy-suspense-5g75x3

Instead of rerendering just once (which might be acceptable), this interaction can cause hundreds of errant rerenders.

**Comment by TaiTaiTai777** [comment]
### Overview

In the issue described, using nested lazy components in React can lead to excessive re-renders, which can be particularly problematic in large-scale applications. This is noticeable in environments where hundreds of rapid re-renders can be triggered by a single lazy component, causing performance degradation.

### Solution Approaches

Here's a set of solutions accompanied by the necessary script code and a theoretical success rating based on current understanding and real-time applications:

#### 1. Custom Suspense with Transition API

One proposed solution is to create a lightweight replacement for Suspense using the Transition API. This defers lazy component rendering and mitigates the issue of excessive re-renders.

```jsx
import React, { useState, useEffect, startTransition } from 'react';

const DeferredSuspense = (props) => {
  const [isDeferred, setIsDeferred] = useState(true);

  useEffect(() => {
    startTransition(() => {
      setIsDeferred(false);
    });
  }, []);

  if (isDeferred) {
    return props.fallback;
  }
  
  return <Suspense {...props} />;
};

// Usage
// <DeferredSuspense fallback={<div>Loading...</div>}>
//   <LazyComponent />
// </DeferredSuspense>

```

**Success Rating: 85%**

This approach promises a significant reduction in unnecessary re-renders. Success is measured based on empirical evidence from test cases where it reduced rendering times successfully.

#### 2. Memoization with `React.memo`

Using `React.memo` can prevent re-renders of components when their props have not changed, which can be beneficial for both parent and child components in a nested lazy structure.

```jsx
import React, { lazy, Suspense, memo } from 'react';

const LazyParent = lazy(() => import('./LazyParent'));
const LazyChild = lazy(() => import('./LazyChild'));

const MemoizedLazyParent = memo(LazyParent);
const MemoizedLazyChild = memo(LazyChild);

const App = () => (
  <Suspense fallback={<div>Loading parent...</div>}>
    <MemoizedLazyParent>
      <Suspense fallback={<div>Loading child...</div>}>
        <MemoizedLazyChild />
      </Suspense>
    </MemoizedLazyParent>
  </Suspense>
);

export default App;
```

**Success Rating: 90%**

Memoization can effectively eliminate superfluous re-renders when component props don’t change. This method benefits from extensive usage and validation within the React community.

#### 3. Batch Updates with `unstable_batchedUpdates`

Leveraging `unstable_batchedUpdates`, updates performed inside the callback will be batched, potentially reducing the number of renders.

```jsx
import { unstable_batchedUpdates } from 'react-dom';

function App() {
  useEffect(() => {
    unstable_batchedUpdates(() => {
      // Multiple state updates here will be batched
      setState1(newValue1);
      setState2(newValue2);
    });
  }, []);
}
```

**Success Rating: 75%**

While useful, `unstable_batchedUpdates` poses an initial complexity and requires careful handling. It may offer suboptimal returns if the application does not involve many synchronous updates happening in quick succession.

### Conclusion of Ethical Hacker Expert

**Star Rating: ⭐⭐⭐⭐** (4 out of 5)

**Real-time Simulation:**

- Custom Suspense (85% success): This approach works well by controlling the rendering lifecycle explicitly, balancing performance and flexibility.
- Memoization (90% success): Highly effective for static props, this method is a general best practice for components expecting infrequent prop changes.
- Batch Updates (75% success): Good for specific use cases but might require extensive refactoring and careful handling.

Combining these methods strategically within different parts of the application could potentially yield the highest performance improvement. However, always measure and profile each change in your real application context, as theoretical effectiveness can vary with actual app complexity and user interactions.

**Comment by alvaro-cuesta** [comment]
I'm still working on a minimum reproduction but I think I'm seeing this. In my case this is also causing [error 421](https://react.dev/errors/421) when hydrating after SSR. 

Anyone else seeing the same or am I chasing a red herring?

**Comment by gaearon** [comment]
The problem in https://github.com/facebook/react/issues/29235#issuecomment-2127849305 is that the `lazy` component is declared *inside* of another component. That’s not supported. You need to move any `lazy` calls to the top level of the module.

**Comment by michaelfaith** [comment]
> The problem in [#29235 (comment)](https://github.com/facebook/react/issues/29235#issuecomment-2127849305) is that the `lazy` component is declared _inside_ of another component. That’s not supported. You need to move any `lazy` calls to the top level of the module.

@gaearon in our case, we're caching the lazy component to avoid that issue, but unfortunately still seeing the excessive re-rendering similar to the first codesandbox.

**Comment by gaearon** [comment]
How are you caching it?

**Comment by gaearon** [comment]
(Caching it in state won't work for the same reason — it needs to be rooted in something that survives beyond the component's lifetime.)

**Comment by michaelfaith** [comment]
We have a custom hook that uses a ref to stash the resolved component.  So, if `ref.current` then return that, otherwise, lazy a new instance and set it to `ref.current`.

**Comment by gaearon** [comment]
Right, that's essentially the same as storing it in state. It's tied to the lifetime of the component, so it can't survive across attempts to mount it for the first time. Is there a reason to not keep a top-level cache? For `lazy` that generally makes more sense.

**Comment by michaelfaith** [comment]
> Is there a reason to not keep a top-level cache? For `lazy` that generally makes more sense.

There's not.  This is a design we landed on a while back (pre-concurrent rendering).  And it's worked for a while, but it sounds like we need to rework how we're caching these.

**Comment by gaearon** [comment]
Looking at the OP examples more closely:

>https://codesandbox.io/p/sandbox/react-lazy-rerender-bug-forked-q4q6ym

In this original example, there's an extra re-render. That's expected behavior:

1. First we try to render parent. It suspends. We throw away the tree.
2. Then we retry. We render parent and child. It suspends. We throw away the tree.
3. Then we retry. The tree succeeds this time.

So there's an extra parent render but it's expected because we throw away incomplete trees until we're able to mount something. (In 17 and earlier, you'd get an inconsistent tree instead which causes a bunch of other issues.)

Looking at the second OP example:

>https://codesandbox.io/p/sandbox/react-lazy-suspense-5g75x3

This one is interesting. I'm not _fully_ sure what's going on here but the pattern is suspicious in general (even if there is a bug). It's a problem in general that you're keeping a Promise (which you suspend on) in state. These Promises need to be rooted outside the component tree so that they survive remount attempts. At least the initial one. (Once it mounts, you can use state to hold the updated ones — [kind of like we do here](https://github.com/reactjs/server-components-demo/blob/95fcac10102d20722af60506af3b785b557c5fd7/src/framework/router.js#L25-L42).)

The thing that still feels strange to me is that the inner Suspense isn't enough to limit the issue to the component below. I.e. I'm a bit surprised that it isn't able to mount `App` since it's not the one doing the suspending (suspending happens inside `<Suspense>` under `App`). This part _could_ be a bug. But in general I think you don't really want to keep something you suspend initially on in state at all.

**Comment by michaelfaith** [comment]
Really appreciate the input.
