### ISSUE TITLE
Is it possible to add multiple event listeners to React component? Is it possible to programmatically assign listener?

### ISSUE THREAD

**Issue by adaniliuk** [facebook/react#2925]
Hello,

Could you please answer the following questions:
- Is it possible to add multiple event listeners to React component? 
- Is it possible to programmatically assign listener?

Ideally i'm looking for something like [addEventListener](https://developer.mozilla.org/en/docs/Web/API/EventTarget.addEventListener)

It would be great if you could suggest something.

Thank you,
Andrei

**Comment by sebmarkbage** [comment]
No, the React event system doesn't have a way to attach multiple listeners to a single node automatically. You can always chain a callback to your own event emitter if you want to.

I'm curious about your use case. I've never seen the need for this (and I've seen a lot of React components). Could you elaborate a bit? Maybe there's something we're missing that we should support.

**Comment by adaniliuk** [comment]
Thank you for your reply. The idea is to implement form validation mixin having the following functionality:
- on focus display some helper info
- on change checking entered info and adjusting entered data or displaying warning
- on blur displaying possible warning

So I wanted to add handlers to form inputs in componentDidMount and didn't want to overwrite any handlers if they are assign in component previously.

**Comment by brigand** [comment]
You could use a helper function which behaves like a simpler (less powerful) version of react's mixin strategy.

The minimal example of its use is this:

```js
var a = {foo: function(x){ console.log(x*2) }};
var b = {foo: function(x){ console.log(x*3) }};
var methods = mergeMethods(a, b);
methods.foo(5); // logs 10 and 15 to the console
```

In a more realistic example, your mixin is probably calling mergeMethods internally while accepting an object from the component's render method.  Here getFormProperties would be calling it internally, to ensure if the user passes any of the same handlers to it, that they're called.

This also puts you in a position to accept properties ignored by the native dom components, like onSuccessfullySubmit, while remaining a mixin.

```
render: function(){
  return <form {...this.getFormProperties({
    onSubmit: function(){  }
  })}></form>;
}
```

I'm not sure how good of an idea this is, it's just the most direct answer I have, without saying 'just use addEventListener' :-)  

More code:

```js
function both(f, g){
  return function(){
    f.apply(this, arguments); g.apply(this, arguments);
  };
}

function mergeMethods(/* ...objs*/){
  var result = {};
  Array.prototype.forEach.call(arguments, function(obj){
    Object.keys(obj).forEach(function(key){
      if (typeof obj[key] !== "function") {
        if (key in result) 
          throw new Error('mergeMethods: non method keys from multiple sources cannot be used, ' + key + ' exists in more than one source');
          
         result[key] = obj[key];
         return;
      }
      
      if (result[key]) result[key] = both(result[key], obj[key]);
      else result[key] = obj[key];
    });
  });
  return result;
}
```

**Comment by adaniliuk** [comment]
Thank you guys, it seems like my case is becoming much more complex from business requirements perspective, so original ask is no longer actual. Also I think that it might be not very secure solution in terms of possible state change conflicts from different event handlers.

Again thank you for the suggestions. I will keep them in mind anyway.

**Comment by altmind** [comment]
If someone is interested, I packaged solution similar to `mergeMethods` above in npm package.  https://github.com/altmind/react-handlers to achie

**Comment by Brain2000** [comment]
> Hello,
> Could you please answer the following questions:
> 
> Is it possible to add multiple event listeners to React component?
> Is it possible to programmatically assign listener?
> 
> Ideally i'm looking for something like addEventListener
> It would be great if you could suggest something.
> Thank you,
> Andrei

After learning that React has synthetic events, yet you cannot chain events, puzzles me greatly!  Especially now that hooks are out, injecting an onChange event should be as easy as adding an additional attribute to a JSX element.  But... it's not. Because it eats the previous onChange event that might have been on the JSX element, without any error or notification.

If there are more than one, it should automatically aggregate them and use a common event handler, like jQuery does.

**Comment by design-principles** [comment]
@Brain2000, it will be magic! No one loves magic in programming! But I love this idea.
