### ISSUE TITLE
Don't Touch PropTypes in Production Mode

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2938]
We're currently validating the propTypes in production mode. We should probably not do that. It's wasted effort since they're not used.

It also means that you can play around with propTypes without fear of breaking production code.

**Comment by brigand** [comment]
Should propTypes in mixins still be merged in, or can that be skipped?

**Comment by jergason** [comment]
It looks like propType checking is already surrounded by an `if (__DEV__) {}` block starting in https://github.com/facebook/react/blob/4486a17c248e1927fcfa3c4266a195300b5bc491/src/core/ReactCompositeComponent.js#L507. Is that correct?

**Comment by brigand** [comment]
Yeah and everywhere else _checkPropTypes is used, huh.

**Comment by sebmarkbage** [comment]
Not this one. https://github.com/facebook/react/blob/4486a17c248e1927fcfa3c4266a195300b5bc491/src/classic/class/ReactClass.js#L365

**Comment by kentcdodds** [comment]
@sebmarkbage, is that one you referenced the only place that needs updating? Thinking this might be a good first bug for me :-)

**Comment by sebmarkbage** [comment]
@kentcdodds It looks like @jergason is already working on this. You might want to coordinate with him or follow up on the PR #2948

**Comment by kentcdodds** [comment]
Ah, duh. I'll find another low hanging fruit then :-)

**Comment by jsfb** [comment]
@kentcdodds  https://github.com/facebook/react/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22

**Comment by jsfb** [comment]
Closed by https://github.com/facebook/react/pull/2948
