### ISSUE TITLE
Add Korean translated docs

### ISSUE THREAD

**Issue by sairion** [facebook/react#2945]
After seeing some good Chinese contributors contributing, I'm starting React docs translation project in React Korea group. As soon as we finish (or, have enough amount of docs translated) the translation, we would like to send a pull request. What do you guys think about it?

If you are interested, see [here](https://github.com/reactkr/discuss/issues/4) (even though its mostly in Korean):

**Comment by zpao** [comment]
I'm game. Eventually we might want to move docs elsewhere but until then, I think it's a great idea to have them all checked in here. I know they'll fall out of date and we don't do a good job of publicizing the translations, but we can solve that later. Send a PR whenever you're ready!
