### ISSUE TITLE
onChange fires for event of type "input" ?

### ISSUE THREAD

**Issue by ghost23** [facebook/react#2955]
Hi,

does the onChange handler also capture input events? If yes, why?

I would like to be able to only capture onChange, but not onInput.

**Comment by zpao** [comment]
In our [http://facebook.github.io/react/docs/dom-differences.html](docs) we mention this:

> The `onChange` event behaves as you would expect it to: whenever a form field is changed this event is fired rather than inconsistently on blur. We intentionally break from existing browser behavior because `onChange` is a misnomer for its behavior and React relies on this event to react to user input in real time. See Forms for more details.

Browsers already implemented this event inconsistently and we decided long ago to make it do what most people actually expected the event to do, tell you when a value changed, not at some point after the input lost focus.

If you'd like, you can use a combination of `onFocus` and `onBlur` and compare values to recreate somethng like the native event. Alternatively I *think* `change` is one of the events we actually make use of to build our `onChange` behavior, so you could potentially still just use `onChange` in React, then in your event handler only run code if `event.nativeEvent.type === 'change'`
