### ISSUE TITLE
Compiler String Concat Constant Propagation

### ISSUE THREAD

**Issue by nikeee** [facebook/react#29617]
Consider the following constant propagation:

Input:
```ts
function foo() {
  const a = "a" + "b";
  const c = "c";
  return a + c;
}
```
Output:
```ts
function foo() {
  return "abc";
}
```

Is this in scope for the react compiler? If so, is it open for contributions?

**Comment by josephsavona** [comment]
Yeah, we'd be open to PRs adding support for string concatenation. Check out https://github.com/facebook/react/blob/main/compiler/packages/babel-plugin-react-compiler/src/Optimization/ConstantPropagation.ts#L327-L331 — add an extra `if` clause here if both the lhs and rhs are strings. Please make sure to include a test case.
