### ISSUE TITLE
Bug: Error "Unsupported URL scheme" with React Developer Tools

### ISSUE THREAD

**Issue by KHORR** [facebook/react#29636]
When using React Developer Tools in Chrome, I encounter an error message "Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME". This error occurs when I try to debug my React application.

React version: 18.3.1
React Developer Tools version: 5.2.0

Steps to reproduce:

1. Open a React application in Chrome.
2. Open React Developer Tools.
3. Try to debug the application.

Expected result:
I should be able to debug my application without encountering any errors.

Actual result:
I encounter the error "Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME".

Error message:
```
Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

Additional information:
I have tried the following steps to resolve the issue, but none of them worked:

Restarting the browser.
Reinstalling React Developer Tools.
Updating the browser.

Here is a snippet from my code:
**Code snippet:**
```javascript
if (typeof window !== 'undefined') {
  window.global = window;
}

import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const root = createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

**Comment by BakedPotato52** [comment]
The "Unsupported URL Scheme; Fallback: HTTP Error: Status Code 404, net::ERR_UNKNOWN_URL_SCHEME" error usually occurs when React DevTools attempts to access a URL that is not supported by the browser

In your case, the problem line is probably from window.global = window; In your code. This line overrides the global object, which React DevTools uses to communicate with the browser.

You can try the following to fix the problem.

remove line window.global = window; From your code. This line is unnecessary and is causing the issue.

To access a global object, use the globalThis object instead, which is the way to access global objects in modern browsers.

Code snippet:

import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const root = createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

Reload the React DevTools after implementing these changes and check if it is resolved.

**Comment by nivarthana1994** [comment]
hi @KHORR  is this issue resolved? if not can you assign it to me?

**Comment by KHORR** [comment]
I'm sorry. 
I got another error right away and eventually I (tired of solving the error) uninstalled react.
