### ISSUE TITLE
[Compiler Bug]: Stripping curly braces breaks character escapes (breaks JSX spec 1.5.1)

### ISSUE THREAD

**Issue by coravacav** [facebook/react#29648]
### What kind of issue is this?

- [X] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwAkIBbBACgEp8wADpt8MBLlhteo-PPwAeAHxyF8xQGVuCAMLdsdBHQK4MuALzAA5AEFhogKLWAvvgD0qseq079XQ2NTcwthEHsnMI8vH081fgBuURdREBcgA

### Repro steps

1. Use a string with a newline character (`\n`) passed as a prop to a component with curly braces `prop={"text\ntext"}`
2. Observe that react compiler outputs `prop="text\ntext"` instead of `prop={"text\ntext"}`

This is incorrect behavior. The newline character is no longer properly treated as a newline but rather as the raw text `\n`.

You can see this behavior be correctly also incorrectly handled in the second component, where `prop="text\ntext"` becomes `prop="text\\ntext"`, resulting in the wrong text being displayed on the screen.

JSX rules specifically don't allow this kind of conversion, noted in [1.5.1 of the spec](https://facebook.github.io/jsx/#sec-jsx-string-characters)

> Historically, string characters within [JSXAttributeValue](https://facebook.github.io/jsx/#prod-JSXAttributeValue) and [JSXText](https://facebook.github.io/jsx/#prod-JSXText) are extended to allow the presence of [HTML character references](https://facebook.github.io/jsx/#sec-HTMLCharacterReference) to make copy-pasting between HTML and JSX easier, at the cost of not supporting \ [EscapeSequence](https://tc39.es/ecma262/#prod-annexB-EscapeSequence) of ECMAScript's [StringLiteral](https://tc39.es/ecma262/#prod-StringLiteral).

### How often does this bug happen?

Every time

### What version of React are you using?

19.0.0-rc-6f23540c7d-20240528

**Comment by josephsavona** [comment]
Thanks for reporting, this looks like a bug. We'll prioritize a fix.

**Comment by SeekingLight233** [comment]
<img width="922" alt="image" src="https://github.com/facebook/react/assets/44890048/80447e13-eb71-4cf0-b35e-b8e384fbb5a5">

It seems like this issue existed even before BuildHIR🤔

**Comment by poteto** [comment]
Thanks for reporting! I have a PR for preserving the JsxExpressionContainer if it contains non-ascii characters, which fixes the first example in your repro. However the 2nd case is an issue with @babel/parser as @SeekingLight233 pointed out. We could perhaps also check if jsx attribute string literals contain those special characters and convert it into a JsxExpressionContainer

**Comment by poteto** [comment]
Should be fixed by #29997
