### ISSUE TITLE
Bug: useState does not update the state. Updates only on second click

### ISSUE THREAD

**Issue by adizh** [facebook/react#29642]
React version:
  "react": "^18.2.0",
   "react-dom": "^18.2.0",
## Steps To Reproduce

   const [activeLink,setActiveLink]=useState('/home');
    const goTo = (link:string) => {
    setActiveLink((prev)=>prev=link);
    navigate(`/react-mini-tg${link}`);
};

Here it goes to another route, but fails to update the activeLink

Link to code example:

**Comment by JayaRamSamavedam** [comment]
instead of writing 
`setActiveLink((prev)=>prev=link);`
directly write 
`setActiveLink(link)`

**Comment by adizh** [comment]
It still does not update the state, I tried to do both and also tried with
setTimeout

ср, 29 мая 2024 г. в 16:17, JayaRamSamavedam ***@***.***>:

**Comment by Omnimbalkar04** [comment]
there is a syntax issue with the navigate function. The template literal should be enclosed in backticks (```) instead of regular quotes. And also you can update the state is to pass the new state value directly to setActiveLink.
Like this,

const [activeLink, setActiveLink] = useState('/home');

const goTo = (link: string) => {
    setActiveLink(link);  // Set the new state directly
    navigate(`/react-mini-tg${link}`);  // Use backticks for template literal
};

**Comment by Omnimbalkar04** [comment]
You should to update the state is to pass the new state value directly to setActiveLink.

const [activeLink, setActiveLink] = useState('/home');

const goTo = (link: string) => {
    setActiveLink(link);  // Set the new state directly
    navigate(`/react-mini-tg${link}`);
};

**Comment by eps1lon** [comment]
```diff
-setActiveLink((prev)=>prev=link);
+setActiveLink((prev)=>link);
```

Assign `prev` in state updater functions has no effect. The new state must be returned.
