### ISSUE TITLE
[Compiler]: Consider the `dispatch` fn from useActionState and useFormState to be non-reactive

### ISSUE THREAD

**Issue by josephsavona** [facebook/react#29674]
### What kind of issue is this?

- [X] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRchYORA2gENcBTAGUcAnAgA0RACZ4wlSXAAWAQWGEAukQC8RKGASb8hcZIRMA3OyKduvPmggxyFqbIVKVqgGKu5LoGRggBbh5WjLaYdg6YPETmUABG5Hg4piL6REz6AHwscfbeyjhqWYQ2cQC+MXFcCbzJaRnh5Dl5eoVsHCWKZWrt1Rw17HEwCDiwxAA8ARBJYqnpmVqYesAtq5WYNUuiK22Bm9vHbvsA9PkxNSA1QA

### Repro steps

Align with #29665, considering the dispatch function returned by useActionState and useFormState to be non-reactive. 

This requires updating `REACT_APIS` in Globals.ts to define these hooks and their return type, and annotate the dispatch function as non-reactive. See the definition for `useState` as an example.

### How often does this bug happen?

Every time

### What version of React are you using?

19

**Comment by josephsavona** [comment]
For anyone interested in contributing: This requires updating REACT_APIS in Globals.ts to define these hooks and their return type, and annotate the dispatch function as non-reactive. See the definition for useState as an example.

**Comment by eps1lon** [comment]
`useReducer` is also considered reactive at the moment as far as I can tell: https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRchYORA2jwCGOBABoiAEzxhKwuAAsAukQC8RKGAQAlBBKiIYTANzt2RTt16EAylABG5PLzVNVAPhZnzk6bJwLjLwBfU0wvGAQcWGIAHgAxCAgiG3tHHBVgFIcnIKIAejcTTCCQIKA

**Comment by hieudo-dev** [comment]
Hi everyone! I'd love to give this one a try if it's not assigned already

**Comment by josephsavona** [comment]
@hieudo-dev sure, give it a try!

**Comment by RaphaelTaibi** [comment]
Hello, I am a junior developer. Is it possible for me to participate in this issue? Open source React is very important to me. It's a library that I particularly love since I discovered it. I wish to improve my skills and learn more about it.
Thank you for taking the time to respond to me.

**Comment by PRANJALI-SANKPAL** [comment]
Is this issue resolved ? If not i want to work on it

**Comment by josephsavona** [comment]
The fix has been merged, thanks!

**Comment by eps1lon** [comment]
@josephsavona The [merged PR only added support for `useReducer`](https://github.com/facebook/react/pull/29705). The [PR for adressing `useActionState` and `useFormState`]( https://github.com/facebook/react/pull/29758) is still open. I guess the remaining discussion topic is if we want to support the old name. [I'd say that's worth it](https://github.com/facebook/react/pull/29665#issuecomment-2147173019) considering it was shipped in Next.js but maybe worth bringing up in the next sync?

**Comment by josephsavona** [comment]
ooops sorry about that!

**Comment by PRANJALI-SANKPAL** [comment]
So issue is reopened? Should I start working on it?

**Comment by josephsavona** [comment]
See https://github.com/facebook/react/pull/29758

**Comment by josephsavona** [comment]
Landed!
