### ISSUE TITLE
dangerouslySetInnerHTML doesn't update replaced state properly

### ISSUE THREAD

**Issue by ejelome** [facebook/react#2970]
This *might be* a bug on `dangerouslySetInnerHTML`.

The scenario is the following:

1. The `message` state contains a default value
2. Typing on the `<textarea>` *should* overwrite the default value

It works as expected when not using `dangerouslySetInnerHTML`, but when `dangerouslySetInnerHTML` is used, yes, it still works, but rather than replacing the state, it concatenates the default value with the values of `<textarea>`

Here's the problematic example: http://jsfiddle.net/kb3gN/9185

**Comment by ejelome** [comment]
*strange*, when you change the `<p />` to `<div />`, it suddenly worked as expected :|

**Comment by syranide** [comment]
@ejelome The result of the markdown is `<p><strong>Default</strong> <em>message</em></p>`, `<p><p></p></p>` is invalid markup and the browser mucks with the DOM in weird ways when you do that, so some elements end up outside of the `<p>` you're updating. Hence the behavior you're seeing and React would also start throwing errors if you mutate the elements around the `<p>`.

**Comment by ejelome** [comment]
I see, so in way, an invalid markup halts reactjs in a way, thanks for the explanation @syranide.
