### ISSUE TITLE
[React 19] React compiler & eslint plugin giving an error to mutating values in refs that are used in JSX

### ISSUE THREAD

**Issue by adubrouski** [facebook/react#29703]
## Summary

`eslint-plugin-react-compiler` version: `0.0.0-experimental-51a85ea-20240601`

When I try to mutate a ref value in any event handler, the `eslint-plugin-react` compiler gives the following error:

```
ESLint: Updating a value used previously in JSX is not allowed. Consider moving the mutation before the JSX(react-compiler/react-compiler)
```

Linked CodeSandbox:

https://codesandbox.io/p/sandbox/kind-mirzakhani-qzw4t3

Linked Compiler Playground:

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAgHgBwjALgAgBMEAzAQygBsCSoA7OXASwjvwEFNMAKASn2AAdNvjiswNJpQQBJOpii4ASqXwBefFDAIVJADwAJACoBZADJyFuAKLSAtgjq4AfNzpVKvANzDh+UeIEABZkdITSMnbYeOr4fOrOAn7++EwkcSRSsvKKugB0cLAwjgQAhGoa7pSeSSIp+JkROcqkBUUleQBuZJRQCLGCIIM+dSmN2Vb5hTDFTgWUTHAA1nwj9QC+yesjycW4sGzcyf56zscpekzN+LgAnpgIakIg44Pr+MUkT+OWuaTvAHoznRzicAEaKXCsfCsADCC2WTxCYQiURwuHWzki0VwegBENwULowPqeJJ+G8wk2dBA6yAA

This seems a bit off to me because the documentation specifically mentions manipulating the DOM with a ref as an accepted pattern:
https://react.dev/reference/react/useRef#manipulating-the-dom-with-a-ref

@josephsavona made a [fix](https://github.com/facebook/react/pull/29591) for [issue](https://github.com/facebook/react/issues/29106) like this, but this fix allow only global mutations like `window` or `document`. Refs mutations also cause an error in eslint-plugin-react-compiler

**Comment by josephsavona** [comment]
Good catch, this is a bug. We’ll need to add a new FunctuonEffect variant for writes to refs, and allow that effect inside JSX and effects.

**Comment by coryhouse** [comment]
Thanks @josephsavona. A related issue: If a ref is passed as a prop, the compiler can't tell it's a prop, so the linter warns if the prop is mutated. If you fix the bug above, will the linter allow mutating refs passed as props?

**Comment by gsathya** [comment]
> Thanks @josephsavona. A related issue: If a ref is passed as a prop, the compiler can't tell it's a prop, so the linter warns if the prop is mutated. If you fix the bug above, will the linter allow mutating refs passed as props?

This one is slightly different, I created another issue to track that separately here: #29741

**Comment by josephsavona** [comment]
Fixed in #29733

**Comment by adubrouski** [comment]
@josephsavona thanks for fix. Are there any plans to publish a new version of the compiler and ESLint plugin soon?

**Comment by josephsavona** [comment]
Yeah we’ll publish again next week

**Comment by mziemer21** [comment]
@josephsavona any updates on publishing?
