### ISSUE TITLE
Lexical binding in class.

### ISSUE THREAD

**Issue by hemanth** [facebook/react#2972]
Was trying the beta version and noticed:

```js
class Counter extends React.Component {
  static propTypes = { initialCount: React.PropTypes.number };
  static defaultProps = { initialCount: 0 };
  state = { count: this.props.initialCount };
  tick = () =>  this.setState({ count: this.state.count + 1 });
  render = () => {
    return (
      <div onClick={this.tick()}>
        Clicks: {this.state.count}
      </div>
    );
  }
}
```

Would bomb on `jsx --harmony` with `Parse Error: Unexpected token =` 

AFAIK, `new` on a arrow function definitions will throw an error `is not a constructor` and it doesn't have a prototype as well, so I guess it can't be used with class...

//cc @sebmarkbage

**Comment by gaearon** [comment]
I don't think it's a supported syntax (yet).

See [here](http://facebook.github.io/react/blog/#es7-property-initializers):

>Wait, assigning to properties seems like a very imperative way of defining classes! You're right, however, we designed it this way because it's idiomatic. We fully expect a more declarative syntax for property initialization to arrive in future version of JavaScript. It **might** look something like this

Nevertheless I would be thrilled if this was supported in transpilers liberal to experiments such as [6to5](https://github.com/6to5/6to5). @sebmarkbage Is there any kind of spec for this? I talked to @sebmck and he doesn't mind getting this into 6to5.

**Comment by sebmarkbage** [comment]
There is no official proposal yet, no. I assume it will look something like TypeScript, but the reflective aspects and scoping rules will probably differ a bit.

**Comment by Dashed** [comment]
@sebmarkbage Are you currently in the midst of writing a spec for this?

**Comment by spicyj** [comment]
Not really a React issue, so I'm going to close this out. Lots of discussion on the babel issue:

https://github.com/babel/babel/issues/619

**Comment by hemanth** [comment]
:+1:

**Comment by peter-mouland** [comment]
could someone update the babel issue link?
They have moved to `phabricator`!!
https://phabricator.babeljs.io/

**Comment by hawkrives** [comment]
I'm reasonably sure it's https://phabricator.babeljs.io/T619
