### ISSUE TITLE
style expecting an object has unfortunate consequences. 

### ISSUE THREAD

**Issue by aronallen** [facebook/react#2976]
Hi,

I am pretty new to react, and I am trying to build a DIV that requests an image-scaling service on the backend for images in specific resolutions, to do this I need to use CSS image-set, this CSS value need vendor prefixes, but the CSS key does not, my problem is that I can't have duplicate keys in the style object. I ended up manually setting the style attribute in componentDidUpdate, but it is a hack to get around the system. I suggest that you could perhaps also expect an array of key value pairs, then I could do like this:
```
[{backgroundImage : 'value1'}, {backgroundImage : 'value 2'}]
```

a specific example of the css I am trying to modify can be found here.
```
height : 818px;
width : 1440px;
background-size : cover;
background-image : url(https://images.blockbuster.dk/movie/divergent?width=1440&height=818);
background-image : -webkit-image-set(url(https://images.blockbuster.dk/movie/divergent?width=1440&height=818) 1.0x, url(https://images.blockbuster.dk/movie/divergent?width=2880&height=1636) 2.0x);
background-image : -moz-image-set(url(https://images.blockbuster.dk/movie/divergent?width=1440&height=818) 1.0x, url(https://images.blockbuster.dk/movie/divergent?width=2880&height=1636) 2.0x);
background-image : -ms-image-set(url(https://images.blockbuster.dk/movie/divergent?width=1440&height=818) 1.0x, url(https://images.blockbuster.dk/movie/divergent?width=2880&height=1636) 2.0x);
background-image : -o-image-set(url(https://images.blockbuster.dk/movie/divergent?width=1440&height=818) 1.0x, url(https://images.blockbuster.dk/movie/divergent?width=2880&height=1636) 2.0x)
```

**Comment by aronallen** [comment]
I also tried to add spaces to the backgroundImage key, but react reacted and didn't let me.

**Comment by syranide** [comment]
Feature detection is the go-to solution (at least for now) I believe.

**Comment by zpao** [comment]
Yea, we've suggested feature detection for this case. It's not bullet-proof (eg, won't work for server-rendering).

Otherwise yes, this is an area where unfortunately using objects doesn't work out perfectly. But there isn't really anything we can do, we're not going to change `style` to a string.
