### ISSUE TITLE
[React 19] eslint-plugin-react-compiler: “Writing to a variable defined outside a component or hook is not allowed. Consider using an effect”

### ISSUE THREAD

**Issue by MattyBalaam** [facebook/react#29778]
## Summary

This is a stripped back example, but we have an event handler which updates some values on `document.cookie` for integration with a 3rd party library:

```
const handleOnAuthenticated = () => {
  document.cookie = `xyz`;
  setSomeState()
};
```

The linter warns us “Writing to a variable defined outside a component or hook is not allowed. Consider using an effect”. I wanted to check the advice was sound because I had been under the impression that doing things like this in a handler was preferred to useEffect.

**Comment by josephsavona** [comment]
Are you able to reproduce this on playground? This should already be fixed on main.

**Comment by josephsavona** [comment]
Thanks for following up!
