### ISSUE TITLE
Docs: Text in code snippets is tiny in Firefox

### ISSUE THREAD

**Issue by rtorr** [facebook/react#2977]
Tested firefox 35/37

Left is chrome, right is firefox 35

![screenshot 2015-01-29 09 31 45](https://cloud.githubusercontent.com/assets/297045/5961410/b330c750-a799-11e4-9a1d-4b972b93e08b.png)

**Comment by sedovsek** [comment]
Computed `font-size` of `<code>` element is:

- 12.8px in Chrome and
- 10.4px in Firefox.

It appears to me that Chrome somehow 'ignores' font-size of `<code>`'s first preceding element (`<pre>`), which has its font-size set to 13px, which would result in `<code>`'s computed font-size to be 10.4px, not 12.8px (resulting from 16*0.8).

**Comment by sedovsek** [comment]
It's rather odd… here's the video recording: http://recordit.co/0AYbaF6WCa
Although computed value is 13px, it has zero effect on typography of its child elements, unless you manually set the font-size to 13px.

I wish someone could explain this.

**Comment by zpao** [comment]
So Firefox is right and Chrome is wrong?

Feel free to fix (either way) with hacky CSS if you want!

**Comment by sedovsek** [comment]
@zpao That would be my guess, yes.
I'll take another look today, it was way past midnight last night, so I may have missed something. Either way, I'l like to get to the bottom of this issue and report a bug to Chrome if necessary.

**Comment by sedovsek** [comment]
@zpao, hey. PR is here: https://github.com/facebook/react/pull/2999
I found quite some interesting discrepancies on how browsers render `<code>`'s `font-size`. I wrote [a short articles](http://galjot.si/element-code-and-font-size) to summarise my findings.

**Comment by rtorr** [comment]
@sedovsek interesting. I had no idea this would be a rabbit hole of information. I had no time when I reported this to dig deeper. Good work!

**Comment by zpao** [comment]
PR is in, this will be all fine the next time we generate the website. Thanks again!

**Comment by sedovsek** [comment]
@zpao My pleasure. I have never learned so much from a trivial bug. :+1:
