### ISSUE TITLE
`React.PropTypes.instanceOf` always warns about invalid prop

### ISSUE THREAD

**Issue by pletcher** [facebook/react#2979]
Checked with React v0.12.2 running in Chrome 40.0.2214.93, Safari 8.0.2, and Firefox 35.0.

I'm able to reproduce this issue with the following:

```
// icon.jsx

var Icon = React.createClass({
  propTypes: {
    icon: React.PropTypes.string.isRequired
  },

  render: function() {
    return <span className={this.props.icon} />;
  }
});

module.exports = Icon;
```

```
// wrapper.jsx

var Icon = require('./icon.jsx');

var Wrapper = React.createClass({
  propTypes: {
    icon: React.PropTypes.instanceOf(Icon).isRequired,
  },

  render: function() {
    return <button className="btn">{this.props.icon}</button>;
  }
});

module.exports = Wrapper
```

When I render an instance of `Wrapper` as
```
// var icon = <Icon icon="some-icon" />

 <Wrapper icon={icon} />
```

I get the error

```
Warning: Invalid prop `icon` supplied to `Wrapper`, expected instance of `<<anonymous>>`. Check the render method of `[the parent component]`.
```

(I was also able to reproduce the issue here: http://jsbin.com/necequvimi/2/ )

It seems like the `instanceOf` prop-type checker isn't working as expected, but maybe I've missed something.

**Comment by pletcher** [comment]
Hm, now that I've had a chance to look at what's expected, is it the case that `PropTypes.instanceOf()` expects a regular JavaScript "class" and not a React class? Could that be more explicit in the docs?

https://github.com/facebook/react/blob/master/src/classic/types/__tests__/ReactPropTypes-test.js#L277

**Comment by hzoo** [comment]
Yeah at https://facebook.github.io/react/docs/reusable-components.html#prop-validation

```js
// You can also declare that a prop is an instance of a class. This uses
// JS's instanceof operator.
optionalMessage: React.PropTypes.instanceOf(Message),
```

**Comment by pletcher** [comment]
Yeah, that makes sense -- I guess I just blindly assumed that `React.createClass()` returned a class that would work with `instanceof`. Hopefully the changes in http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html will help down the line :)

**Comment by hzoo** [comment]
https://facebook.github.io/react/docs/displaying-data.html#react-without-jsx

You can use React.createElement to render (http://jsbin.com/suvoqesozo/1/edit)

**Comment by zpao** [comment]
Yea, `instanceOf` is really intended (and implemented as) `x instanceof y`.

**Comment by rhys-vdw** [comment]
Just ran into this problem. Is there a way to constrain a `prop` (ie. `children`) to be of a certain Component type?

**Comment by zpao** [comment]
I think something like `elementOfMyComponent: PropTypes.shape({type: PropTypes.oneOf([MyComponent])` would do it. There's some discussion of maybe having `PropTypes.elementOfType` in #4716 but not sure if we'll do it (there's a lot of room for confusion and it really doesn't pair well with specialized components.

**Comment by chemoish** [comment]
```js
<ButtonGroup>
    <Button />
    <Button />
</ButtonGroup>
```

Is this possible?

```js
ButtonGroup.propTypes = {
  children: React.PropTypes.arrayOf(React.PropTypes.shape({
    type: React.PropTypes.oneOf([Button])
  }))
};
```

Seems weird that this is the only way i found it to validate (`instanceOf` did not work).

**Comment by evpozdniakov** [comment]
I still have a minor problem, which appears when there is only children. If yes, `PropTypes.arrayOf` stops working.

**Comment by chemoish** [comment]
Verbose, but it works.

```js
export default function formattedMessage(props, propName, componentName) {
  const allowedTypes = [
    Button,
  ];

  const isValid = React.Children.toArray(props[propName]).every(
    (child) => allowedTypes.includes(child.type)
  );

  if (isValid) {
    return null;
  }

  return new Error(`Invalid prop ${propName} supplied to ${componentName}.`);
}
```

**Comment by evpozdniakov** [comment]
The last version doesn't work for some reason. The first one works, however I prefer do not create error message myself.
	propTypes = {
		thcells: function(props, propName, componentName) {
			const th = PropTypes.shape({type: PropTypes.oneOf([Th])});
			const err1 = th.isRequired(...arguments);
			const err2 = PropTypes.arrayOf(th).isRequired(...arguments);

			return err1 && err2 || null;
		},
	}

**Comment by milesj** [comment]
@evpozdniakov - I've implemented this functionality here: https://github.com/titon/toolkit/blob/3.0/src/prop-types/childrenOf.js

It can then be used as such:

```
children: childrenOf(ComponentA, ComponentB) // React elements
children: childrenOf('div', 'section') // HTML Tags
```

**Comment by josephmartin09** [comment]
I am actually writing a lightweight form validation library because I am kind of tired of doing it manually over and over.  I ran into this same problem, and this is what I did to get through it.

```jsx

// Validates a singular field
var fieldType = React.PropTypes.shape({
    type: React.PropTypes.oneOf([Field])
})

// Accepts either a single field, or an array of fields
// Note: Reject a Form with no children
Form.propTypes = {
	children: React.PropTypes.oneOfType([
		React.PropTypes.arrayOf(fieldType), // array of fields
		fieldType // singular field
	]).isRequired
}
```

**Comment by mnpenner** [comment]
@milesj Your helper function is nice, but doesn't support `.isRequired`.

**Comment by mochetts** [comment]
I'm having a similar issue.

I have this class:

```javascript
// Component Definition
export default class Point {

  constructor(coords) {
    this.x = coords.x;
    this.y = coords.y;
  }

  static init(x, y) {
    return new Point({x, y});
  }

}
```

And this react component:

```javascript
// Third-Party Dependencies
import React from 'react';
import PropTypes from 'prop-types';

// App dependencies
import PolyLine from '../PolyLine';
import Point from '../_Point';

// Component Definition
class Line extends React.PureComponent {

  getPoints() {
    return [ this.props.start, this.props.end ];
  }

  render() {
    return (
      <PolyLine points={ this.getPoints() } stroke={ this.props.color } />
    )
  }
}

Line.defaultProps = {
  color: 'black',
}

// Specifies type values for props:
Line.propTypes = {
  start: PropTypes.instanceOf(Point).isRequired,
  end: PropTypes.instanceOf(Point).isRequired,
}

// Export the Component
export default Line;
```

![image](https://user-images.githubusercontent.com/3678598/29889403-6cc5b660-8d9a-11e7-9b39-faf1601d9b0f.png)

How can I get rid of that warning? Thanks!

**Comment by xahon** [comment]
This works like a charm
```JavaScript
static propTypes = {
    children: PropTypes.oneOfType([
      PropTypes.shape({
        type: Input
      }),
      PropTypes.arrayOf(
        PropTypes.shape({
          type: Input
        })
      )
    ]).isRequired,
    submitText: PropTypes.string,
    onSubmit: PropTypes.func.isRequired
  }
```

**Comment by evpozdniakov** [comment]
@xahon, this really works!

However if I make an error by passing wrong type in my component, the warning message is not helpful.
**Warning: Failed prop type: Cannot call a class as a function**

**Comment by jboelen** [comment]
I had to make a slight change to @xahon's solution to get past the warning. Here's a small utility I wrote that can generate this for you:

```jsx
import PropTypes from 'prop-types';

/**
 * Generates the correct PropType when trying to ensure a specific Component
 * @param {Class} component the React component you expect the children to be
 * @returns {PropType}
 */
export default function componentPropType( component ) {
  const componentShape = PropTypes.shape({
    type: PropTypes.oneOf([ component ]),
  });

  // Need to accept the class, false (conditional rendering) or a combination in array form
  return PropTypes.oneOfType([
    componentShape,
    PropTypes.oneOf([ false ]),

    PropTypes.arrayOf( PropTypes.oneOfType([
      componentShape,
      PropTypes.oneOf([ false ]),
    ]) )
  ]);
}
```

**Comment by WSorban** [comment]
> ```js
> <ButtonGroup>
>   <Button />
>   <Button />
> </ButtonGroup>
> ```
> 
> Is this possible?
> 
> ```js
> ButtonGroup.propTypes = {
>   children: React.PropTypes.arrayOf(React.PropTypes.shape({
>     type: React.PropTypes.oneOf([Button])
>   }))
> };
> ```
> 
> Seems weird that this is the only way i found it to validate (`instanceOf` did not work).

What if the Button component is wrapped with another function, such as compose, from Redux, withStyles from MaterialUI, etc?

**Comment by JJCLane** [comment]
I couldn't get these suggestions to work for functional components while generating meaningful docs and error messages, so this was my solution in case it is useful for anyone else: 

```js
/**
 * Validates the PropType by ensuring a specific component is passed
 * @param {function} component The React component you expect the prop to be
 * @returns {Error}
 */
export function componentOfType(component) {
  return (props, propName, componentName) => {
    const p = props[propName];
    if (p !== undefined && p.type.name !== component.name) {
      return new Error(
        `Invalid prop \`${propName}\` supplied to \`${componentName}\`. Expected type of \`${
          component.name
        }\` and received \`${p.type.name ? p.type.name : p.type}\`. Validation failed.`,
      );
    }
  };
}
```

And the usage would be like so:

```js
Card.propTypes = {
  children: PropTypes.node,
  metaBlock: componentOfType(MetaBlock),
};
```

**Comment by zmagauina-fn** [comment]
Here's my solution that was adapted from @JJCLane's response above:
```
/** Validates the PropType by ensuring a specific component is passed
 * Adapted from: https://github.com/facebook/react/issues/2979#issuecomment-642334878
 *
 * @param {function} component The React component you expect the prop to be
 * @returns {Error}
 */
export function ComponentOfType(component) {
  return (props, propName, componentName) => {
    const propType = props[propName].type.displayName;
    const componentType = component.displayName;
    if (propType !== componentType) {
      return new Error(
        `Invalid prop \`${propName}\` supplied to \`${componentName}\`. Expected type of \`${componentType}\` and received \`${propType}\`. Validation failed.`,
      );
    }
  };
}

export default ComponentOfType;
```

Same usage and error as above.

**Comment by jcestibariz** [comment]
One more refinement, this one works with `PropTypes.arrayOf` and `PropTypes.objectOf`.

```js
/** Ensures an instance of a specific component is passed.
 * Adapted from: https://github.com/facebook/react/issues/2979#issuecomment-789320781
 *
 * @param {function|string} type The expected component type.
 * @returns {function}
 */
export default (type) => {
	const expectedName = type.displayName || type.name || type;
	return (values, key, componentName, location, fullKey) => {
		const value = values[key];
		const actualType = value.type;
		return actualType === type
			? null
			: new Error(
					`Invalid prop \`${fullKey || key}\` of type \`${
						actualType?.displayName || actualType?.name || actualType || typeof value
					}\` supplied to \`${componentName}\`, expected instance of \`${expectedName}\`.`
			  );
	};
};```

**Comment by Oarbuild82** [comment]
> Just ran into this problem. Is there a way to constrain a `prop` (ie. `children`) to be of a certain Component type?





https://jython-25inflated200.github.io/aldrin/
