### ISSUE TITLE
[compiler] Combine class component and function component or only class component

### ISSUE THREAD

**Issue by w7en** [facebook/react#29792]
Hi,
I am currently in the process of upgrading to React compiler but when using it with class component or combining class component and function component the result is not as expected.
 
Repo: https://github.com/w7en/next-react-compiler

**Comment by josephsavona** [comment]
Can you say more about what behavior you expected vs what you observed? 

Also note that class components are not, and will not be, supported by the compiler.

**Comment by w7en** [comment]
Hi @josephsavona
as you said above, 'react compiler' does not support 'class component'. I understand why my code is not as expected. I still need 'memo' code for 'class component'.

By the way, since my project is so old and it contains both 'class component' and 'function component', I am trying 'react compiler' solution to leverage old code that has not been 'memo' to improve the performance of the application.

Thank you very much. Can I close this issue?

**Comment by josephsavona** [comment]
Gotcha. Let’s close since class components are not supported. Thanks for posting!
