### ISSUE TITLE
Bug: onSelect does not fire when contentEditable is set to "plaintext-only"

### ISSUE THREAD

**Issue by agdhruv** [facebook/react#29813]
React version: 18

## Steps To Reproduce

1. Create a `div` with `contentEditable="plaintext-only".
2. Define an `onSelect` event handler.
3. It does not fire upon interacting with the `div`.

Link to code example: https://codesandbox.io/p/sandbox/unruffled-kapitsa-9rv7z5

## The current behavior
`onSelect` does not fire when `contentEditable` is set to `plaintext-only` but fires when it is set to `true`.

## The expected behavior
`onSelect` should fire for both cases.

**Comment by m1her** [comment]
The contentEditable="plaintext-only" attribute is not yet fully supported across all browsers, including Firefox.
