### ISSUE TITLE
[React 19] React-Dom bundle increase 200kb

### ISSUE THREAD

**Issue by childrentime** [facebook/react#29913]
## Using React 18

<img width="1153" alt="image" src="https://github.com/facebook/react/assets/58261676/d9d73fb7-f4bb-4cae-9a7d-19cf0bce7bca">

<img width="796" alt="image" src="https://github.com/facebook/react/assets/58261676/2d024945-39f4-4e0d-baec-60a56d791445">

## Useing React19 

After Using React@canary, the react dom bundle changed to `react-dom-client.production.js` , which is 498kb!

<img width="823" alt="image" src="https://github.com/facebook/react/assets/58261676/e8e58714-fd19-4939-b188-3d5b616218fd">

<img width="1298" alt="image" src="https://github.com/facebook/react/assets/58261676/757efdde-1b84-4384-b44a-3e92c7737ff8">

**Comment by pawelblaszczyk5** [comment]
The slight increase with v19 is there, but much much smaller than it looks like here. The difference you’re seeing is because you’re comparing minified size with unminified size. React stopped shipping minified version by default, which doesn’t impact vast majority of people. That’s because we commonly use bundlers and minifying the code as part of our own build pipeline

**Comment by o-alexandrov** [comment]
Related to https://github.com/facebook/react/issues/27824#issuecomment-2133153013

**Comment by childrentime** [comment]
Thanks!

**Comment by xr0master** [comment]
Nope, after switching to 19 the size of the entire app bundle increased by 50kb. I am using vite 6

**Comment by jdelStrother** [comment]
I'm seeing around an increase of around 35kb across our app after minification & gzip.
react-dom looks to have gained 220kb of minified code, which seems kind of crazy - is that expected or is something not working with tree shaking?

React 18.3.1 - 

<img width="423" alt="Image" src="https://github.com/user-attachments/assets/f960ebbb-c32f-4ad3-985b-f3fd3d722a82" />

React 19.1.0 - 

<img width="470" alt="Image" src="https://github.com/user-attachments/assets/e63dda0d-421c-4f8b-9eac-9a57c8e711d9" />

**Comment by xr0master** [comment]
@jdelStrother you are comparing minified and non-minified files.

**Comment by jdelStrother** [comment]
@xr0master the filename from react 18 has `.min` in because the package has a pre-minified version in. The file sizes I've reported are from my production-minified build using webpack/terser/swc.

**Comment by jdelStrother** [comment]
Sorry for the noise, this was a dumb configuration error on my part where react wasn't getting minified properly.

react 18.3.1 - minified 125.59kb, gzipped 40.9kb
react 19.1.0 - minified 162.96kb, gzipped 51.5kb

So a definite increase, but not the huge numbers I first saw.

**Comment by mnvacym** [comment]
@jdelStrother would you mind sharing what was the configuration error? Could you please share how did you solve it?

**Comment by jdelStrother** [comment]
@mnvacym I'm no longer entirely sure, but I think I might have needed a `yarn dedupe` to remove some duplicate dependencies.

**Comment by xr0master** [comment]
@jdelStrother about 20% of size according to your details.

This is the main issue of not wanting to switch to React 19. It does not yet provide too much new compared to 18, but it significantly increases the size of all applications.

**Comment by mnvacym** [comment]
@jdelStrother It turns out that I had a similar misconfiguration in my webpack. I used to have `react-dom` as part of my vendor list. But with react 19 you also need to add `react-dom/client` explicitly to the vendor list, and bundle size will be back to normal.

**Comment by zehawki** [comment]
Certainly a major impact of 40% going from R18 - 37.5 to R19 - 52.7KB for minified + gzip. At a time when JS bloat is a real thing, this adds still more. Between react and redux and react-router and MUI, its so easy to reach 250KB+ (gzip) in the first bundle 😣.

| React version  | Source | Minified size | Gzip size
| ------------- | ------------- | ------------- | ------------- |
| 19  | https://cdnjs.cloudflare.com/ajax/libs/react-dom/19.1.1/cjs/react-dom-client.production.min.js  | 247KB | 52.7KB | 
| 18  | https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/cjs/react-dom.production.min.js  | 132KB | 37.5KB | 
| 17  | https://cdnjs.cloudflare.com/ajax/libs/react-dom/17.0.2/cjs/react-dom.production.min.js  | 121KB | 34.9KB |

**Comment by childrentime** [comment]
@zehawki I think this is the reason why we need streaming server side technology.

**Comment by xr0master** [comment]
> [@zehawki](https://github.com/zehawki) I think this is the reason why we need streaming server side technology.

Or use other libs that don't have this issue.

React is primarily a client-side library, designed for building interactive UIs efficiently. Adding server-side streaming and other technologies can blow up complexity and dev overhead just to “solve size issues”.

**Comment by zehawki** [comment]
> Or use other libs that don't have this issue.

No, I'm afraid that's easier said than done. React is the preeminent tech today, and for the near future. One cannot so easily discard/replace gazillion components and libraries and ecosystem support. Therefore, it would be rather lovely to have upgrade paths without bloat.

**Comment by o-alexandrov** [comment]
Probably, [Lightweight React 19.x [Feature request/Suggestion]](https://github.com/facebook/react/issues/27824) is more appropriate to request slimming down react
