### ISSUE TITLE
[Compiler Bug]: Increment expression in for-loop loses assignment operation

### ISSUE THREAD

**Issue by derekcicerone** [facebook/react#29956]
### What kind of issue is this?

- [X] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAGgBQCURwAOsUWhDEWQDYI5F5EC8RADAG4uRADxEAjPyEi+3ANSSqwAL50VIFUA

### Repro steps

In our repo we have code similar to the Playground link posted above which when compiled loses the assignment part of the increment expression.

The original code:
```
          for (
            let node: LexicalNode | null = selection.anchor.getNode();
            node && !$isRootNode(node);
            node = node.getParent()
          ) {
```

Compiled to this code:
```
        for (let node5 = selection.anchor.getNode(); node5 && !$isRootNode2(node5); node5.getParent()) {
```

Happy to provide additional information or context if needed, thanks!

### How often does this bug happen?

Every time

### What version of React are you using?

19.0.0-rc-f3e09d6328-20240612

**Comment by josephsavona** [comment]
Thanks for the bug report, we’ll take a look!

**Comment by Fnll** [comment]
It seams that `updateValue` in for loop will be reassigned to `LoadLocal` even if it is originally a `StoreLocal Reassign` instruction at [here](https://github.com/facebook/react/blob/main/compiler/packages/babel-plugin-react-compiler/src/ReactiveScopes/BuildReactiveFunction.ts#L946).

can we simply use the original instruction's value just like how it's tackled for `while` loop at [here](https://github.com/facebook/react/blob/main/compiler/packages/babel-plugin-react-compiler/src/ReactiveScopes/BuildReactiveFunction.ts#L903)?

**Comment by josephsavona** [comment]
Fix landed, thanks for filing!

**Comment by derekcicerone** [comment]
Thanks, that was quick!
