### ISSUE TITLE
select not receiving click event correctly

### ISSUE THREAD

**Issue by chenglou** [facebook/react#300]
http://jsfiddle.net/chenglou/ZEKbB/1/

Behavior:
- Chrome: nothing at all.
- Safari: works upon menu dismissal (and therefore item selection since that triggers dismissal), although for this reason it's triggered after the fade out animation rather than immediately.
- Firefox: works on both clicking select and clicking on an option, but not on menu dismissal.
- Mobile Safari: works on clicking the select, but not its option.
- Opera: (oh man) works on clicking an option and on menu dismissal, the latter only when the focus on the drop down is lost and regained.
- IE: triggers on every click, in menu and upon opening/dismissing the dropdown

By the way, This is a browser inconsistency. Not React's fault.

**Comment by gaearon** [comment]
Closing as stale. If someone is affected by this please raise a new issue and we can discuss.
