### ISSUE TITLE
How can I access dom node now, ES6

### ISSUE THREAD

**Issue by nvartolomei** [facebook/react#3004]
I just noticed getDOMNode doesn't work anymore.

` Warning: getDOMNode(...) is deprecated in plain JavaScript React classes.`

What's the new way for doing this?

**Comment by vsiao** [comment]
`React.findDOMNode`

**Comment by zpao** [comment]
Yep, @vsiao is right. We haven't updated docs yet but we will as we approach 0.13 final.

**Comment by john-brunelle** [comment]
This is a test comment
