### ISSUE TITLE
Unnecessary return

### ISSUE THREAD

**Issue by hnordt** [facebook/react#3006]
Hello.

Reading the React Tutorial (http://facebook.github.io/react/docs/tutorial.html#adding-new-comments) we have:

```javascript
var CommentForm = React.createClass({
  handleSubmit: function(e) {
    e.preventDefault();
    var author = this.refs.author.getDOMNode().value.trim();
    var text = this.refs.text.getDOMNode().value.trim();
    if (!text || !author) {
      return;
    }
    // TODO: send request to the server
    this.refs.author.getDOMNode().value = '';
    this.refs.text.getDOMNode().value = '';
    return;
  },
```

The last `return;` is really necessary? If yes, why is it necessary?

**Comment by brigand** [comment]
`function(anything){anything; return;}` and `function(anything){anything;}` are always equivalent (aside from potentially static transforms, type checkers, and fn.toString()).

It's probably just a typo :-)

**Comment by zpao** [comment]
It may have had some reason in but it looks unnecessary. Feel free to get rid of it!

**Comment by zpao** [comment]
Fix will go out with next docs push. Thanks again!
