### ISSUE TITLE
Comments in JSX not working as expected

### ISSUE THREAD

**Issue by cameronjroe** [facebook/react#3008]
When I comment out a section of jsx children in a component, the jsx transformer doesn't seem to transform it correctly and the elements are not hidden in the DOM. This doesn't seem to work intuitively. Am I doing something wrong? [http://jsfiddle.net/vm43uccy/1/](http://jsfiddle.net/vm43uccy/1/)

**Comment by bloodyowl** [comment]
the way to make a comment in JSX is

```javascript
<div>
  {/* this is a comment */}
</div>
```

otherwise there would be no way for JSX to make the difference between text and comments

**Comment by cameronjroe** [comment]
I see. Are there any configurable parsing options? I'll probably never need `//` or `/**/` as text.

**Comment by bloodyowl** [comment]
not sure about that, maybe you can address the issue to https://github.com/facebook/jsx

**Comment by zpao** [comment]
Going to close this out and let discussions go in the other repo.
