### ISSUE TITLE
[DevTools Bug]: 5.2.0 is not available for Firefox

### ISSUE THREAD

**Issue by aphedges** [facebook/react#30113]
### Website or app

https://addons.mozilla.org/en-US/firefox/addon/react-devtools/

### Repro steps

1. Visit <https://addons.mozilla.org/en-US/firefox/addon/react-devtools/>
2. See that the latest version available is v5.1.0
3. Visit <https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi>
4. See that the latest version available is v5.2.0, and it has been available since 2024-05-09

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
React DevTools v5.3.1 is now available in Firefox extensions store.

**Comment by aphedges** [comment]
I can confirm that Firefox and Chrome have the same extension version available. Thanks for resolving this!
