### ISSUE TITLE
Img tags get duplicated in the virtual DOM

### ISSUE THREAD

**Issue by mik01aj** [facebook/react#3014]
Hi. I have a simple component like this:

    var MyImage = React.createClass({
        render: function() {
            return <img src="aaa.jpg" />;
        }
    });

When I debug it using React dev tools to inspect the React DOM, that's what I see:
![screenshot 2015-02-02 12 08 12](https://cloud.githubusercontent.com/assets/3027415/5999651/2d63e6c8-aad4-11e4-8f07-af44aefffd13.png)

This breaks my unit tests, which expect just one `<img>` element. (I use `TestUtils.findRenderedComponentWithType(myImage, 'img');`)

This is an issue only with the virtual DOM, browser DOM looks like expected: 
![screenshot 2015-02-02 12 13 52](https://cloud.githubusercontent.com/assets/3027415/5999729/0414ce80-aad5-11e4-89f4-e652710da9a8.png)

Interesting note: When I change the line in `render()` to `return <img src="aaa.jpg">aaa</img>;` the element isn't duplicated anymore:
![screenshot 2015-02-02 12 10 52](https://cloud.githubusercontent.com/assets/3027415/5999688/8bf6289a-aad4-11e4-82fc-7b9854a4e06c.png)

I'm using React `0.12.2`.

**Comment by Trebor1957** [comment]
What do you want me to do

**Comment by mik01aj** [comment]
I would expect no duplication of the `img` tag in the virtual DOM (as shown on the first screenshot). `<img><img /></img>` makes no sense to me.

**Comment by Trebor1957** [comment]
![profile_199335075_75sq_1343330927](https://cloud.githubusercontent.com/assets/10807859/5999768/2b5168a0-aa8a-11e4-9ee9-6751e3b86a91.jpg)

**Comment by Trebor1957** [comment]
![10593059_10152558828558232_8166964469706479793_n](https://cloud.githubusercontent.com/assets/10807859/5999787/5123401c-aa8a-11e4-9495-1483b525e9c1.jpg)

**Comment by Trebor1957** [comment]
![10905998_10152984444973232_7710060101847904735_n-1](https://cloud.githubusercontent.com/assets/10807859/5999795/5f5fe5fe-aa8a-11e4-8405-449ac8502836.jpg)

**Comment by Trebor1957** [comment]
![1377511_10153006436773232_3642995983832605258_n](https://cloud.githubusercontent.com/assets/10807859/5999801/7aadabe8-aa8a-11e4-8695-10c5fb5629ec.jpg)

**Comment by Trebor1957** [comment]
![10905998_10152984444973232_7710060101847904735_n](https://cloud.githubusercontent.com/assets/10807859/5999810/8e8a2c04-aa8a-11e4-9a64-22d65fc242d8.jpg)

**Comment by Trebor1957** [comment]
This is my first time using any of this is this enough pics

**Comment by Trebor1957** [comment]
Do you need anythung else

**Comment by Trebor1957** [comment]
Whay does that mean I'm lost lol

**Comment by mik01aj** [comment]
Hmm, looks like it was an error in my tests. When I use `findRenderedDOMComponentWithTag` they work fine. The display of the duplicate tags in DevTools could be a bug of the DevTools plugin.

Side note: I reported Trebor1957's activity to GitHub admins, hope this mess gets cleaned soon.

**Comment by zpao** [comment]
cc @sebmarkbage, I think this might just be a devtools issue (not new since this is with 0.12)

**Comment by sebmarkbage** [comment]
It is because they're wrapped by React in a composite and devtools exposes both instances. Was sort of a weird artifact, but not bug. I think that in 0.13 they're deduped but I'll make sure since devtools is broken for 0.13 atm.

**Comment by spicyj** [comment]
I think we're content with this behavior for now so I'm closing this out.

**Comment by sebmarkbage** [comment]
This should've been fixed in 0.13 yes
