### ISSUE TITLE
[DevTools Bug]: React Devtools not working neither on vite or cra project

### ISSUE THREAD

**Issue by prashantmgk** [facebook/react#30143]
### Website or app

[https://github.com/prashantmgk/portfoliowebsite](i was trying to use it while creating my portfolio site)

### Repro steps

![image](https://github.com/facebook/react/assets/30362730/34f4e6a7-fde5-4f31-b54d-448a0d95364a)
![image](https://github.com/facebook/react/assets/30362730/a60c3f3e-6eab-4668-bb9c-6dfc82f9765a)

I was trying to use React Devtools but i was not able to use it as you can see it in pictures. I thought it was cause i was using vite to create my react project, but i didnt work either in cra app. I saw the error when i navigated to the sources tab as you can see in second picture which is as follows:

`Could not load content for webpack:///react-devtools-shared/src/backend/console.js (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`

### How often does this bug happen?

Every time

### DevTools version (automated)

5.2.0 (5/8/2024)

### Error message (automated)

- Could not load content for webpack:///react-devtools-shared/src/backend/console.js (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
- Could not load content for webpack:///react-devtools-shared/src/backend/DevToolsConsolePatching.js (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

**Comment by hoxyq** [comment]
@prashantmgk Can you please double-check that React DevTools panels are not hidden under the "More tabs" button?
![Screenshot 2024-06-30 at 22 47 04](https://github.com/facebook/react/assets/28902667/fc8da569-3949-47a6-86d7-02f04fffaf67)

**Comment by prashantmgk** [comment]
@hoxyq ohh yeah i can see the compiler and profiler tab. great!

do you know why i was getting those errors?

you can close the issue if that is the fix btw
