### ISSUE TITLE
JSX parsing error

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#3019]
I'm not entirely sure what's causing the issue here:

This fails
```jsx
function play(moves) {
    var game = gamelib.create();
    var player = gamelib.createPlayer();
    return moves.reduce(
        ([[g, p], [x, y]]) => gamelib.play(g, x, y, p),
        [game, player],
        moves
    );
}
```

This doesn't

```js
([[g, p], [x, y]]) => gamelib.play(g, x, y, p),
```

**Comment by zpao** [comment]
Hmm, since this is actually a parse error, can you file an issue in https://github.com/facebook/esprima? There's nothing we in React can do about this.
