### ISSUE TITLE
Two mixins cause invariant violation (defining same methods)

### ISSUE THREAD

**Issue by dariocravero** [facebook/react#3027]
Hi all,

I'm trying to figure out as to whether this is: the wrong way to do it or a React issue.

How do you deal with two mixins pulling state from different stores and trying to be mixed into the same view?

[Here's a gist showcasing the issue](https://gist.github.com/dariocravero/3d56bec82ee96c4d7684).

Given two mixins:

```
var Mixin1  = {
  getState: function() {
    return {
      mixin1: true,
      shared: 'mixin1'
    };
  }
}
var Mixin2  = {
  getState: function() {
    return {
      mixin2: true,
      shared: 'mixin2'
    };
  }
}
```

And a view that uses them:
```
var View = React.createClass({
  mixins: [
    Mixin1,
    Mixin2
  ],
 
  render: function() {
    return <div>A view</div>;
  }
});
```

The view fails with `Uncaught Error: Invariant Violation: ReactCompositeComponentInterface: You are attempting to define `getState` on your component more than once. This conflict may be due to a mixin.`.

Is this the wrong approach? Or maybe a React issue?

When Googling the symptoms I found this facebook/react#375 but it's not strictly related, plus there doesn't seem to be any default spec policy being enforced for multiple definitions.

Thanks!
Darío

**Comment by brigand** [comment]
The way you get around this is by defining the mixins as functions, so the component can decide the naming of things.

```js
var makeStoreMixin = function(name, store){
    var makeState = function(data){ var o = {}; o[name] = data; return o };
    var mixin = {};
    mixin.getInitialState = function(){ return makeState(store.getState()); };
    mixin.componentDidMount = function(){
       store.addChangeListener(function(data){
           this.setState(makeState(data));
       }.bind(this));
    };
    mixin.componentWillUnmount = ...;
    return mixin;
}
```

```js
var View = React.createClass({
  mixins: [
    makeStoreMixin('foo', FooStore),
    makeStoreMixin('bar', BarStore)
  ],

  render: function() {
    // assuming FooStore's and BarStore's getState return arrays...
    return <div>{this.state.foo.length} {this.state.bar.length}</div>;
  }
});
```

**Comment by dariocravero** [comment]
Cool! Thanks, will definitely keep it in mind :)

I'm doing this with Marty and the author [suggested there is be a simpler way around it](https://github.com/jhollingworth/marty/issues/102#issuecomment-72627146) through the framework so I may end up applying that for now.
