### ISSUE TITLE
JSX/Harmony outputs nonsensical code for some arrow function expressions

### ISSUE THREAD

**Issue by davidmccabe** [facebook/react#3029]
Given the following input code

    f = f || (x) => x;

the traceur compiler yields a syntax error, while 6to5 outputs

    f = f || function (x) {
      return x;
    };

I don't know which of these behaviors is correct. What I do know is that `jsx --harmony`, which produces the following output, is not correct:

    (function(f)      {return x;});

Thanks!

**Comment by zpao** [comment]
Since this is an artifact of using jstransform / esprima, I filed an issue elsewhere - we'll pick up any changes from there. Tahnks for filing!
