### ISSUE TITLE
Bug:  div: `ref` is not a prop

### ISSUE THREAD

**Issue by SaintPepsi** [facebook/react#30367]
Using Vite & React we're getting the weirdest error i've seen in all my react career:
```
Warning: div: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
```

I'm clueless, how does react warn me that `ref` is not a prop for `<div>`?

Accompanied is a whole bunch of other errors related to contexts:
```
Warning: _RichTextEditor: `key` is not a prop.
Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed in a future major release. Did you mean to render <Context.Provider> instead?
Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
```

React version: `18.3.1`

## Steps To Reproduce

We tried to reproduce it but it does not happen in a minimal example.
Please advice on tactics/methods to write a minimal reproducible to try and get this error. 

The component giving this error is rendering a `createPortal` to the `document.body`:

![image](https://github.com/user-attachments/assets/89bae1ed-ea65-4baa-bc08-b03e88194d03)

Large Node Tree With recursively rendered components and form elements just to show it's a complex application which I think is what contributes to why we can't replicated it.

![image](https://github.com/user-attachments/assets/7dc300fa-33a9-4113-b598-5c7d1647fb29)

Link to code example: WIP

## The current behavior
VM18671:1 Warning: div: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)

## The expected behavior
No Error

**Comment by eps1lon** [comment]
Do you have multiple versions of React installed?

**Comment by SaintPepsi** [comment]
@eps1lon No, however we did notice that this only happens when adding console logs strangely enough, It might have something to do with `vite` actually 🤔

**Comment by sqndr** [comment]
- Do note, that `ref` is somewhat of special "prop" (for historical reasons, this will [change](https://react.dev/blog/2024/04/25/react-19#ref-as-a-prop) in React 19)
- [`forwardRef`](https://react.dev/reference/react/forwardRef) is a solution to pass a DOM node to a parent component, which might be what your are looking for?
- More about the error [here](https://github.com/facebook/react/pull/5744).

Hope this helps.
