### ISSUE TITLE
Bind DOM event handlers to the component instance

### ISSUE THREAD

**Issue by narqo** [facebook/react#3040]
`react@0.13.0-x` gives us possibility to use JavaScript prototype based inheritance instead of using `React.createClass` method. The only problem that it brings is the need to explicitly bind DOM event handlers to the component, since React's autobinding works only for classes declared with `createClass`. 

At the same time it looks weird. Even if native DOM event listeners work in the same manner, I don't think, that it is a good example to follow. Please notice, native DOM APIs were introduced "thousands years ago" :) Don't get me wrong, but I don't see any usecases where event handler should be called within the context of the global `window` object.

Wouldn't it be better to React itself to bind DOM event handlers to the class instance?

Imaging one has a custom `Button` component (inspired by the [bem-react](https://github.com/dfilatov/bem-react) project):

~~~js
class Button extends React.Component {
  ···
  _onFocus() {
    this.setState({ focused : true });
  },

  _onBlur() {
    this.setState({ focused : false });
  },

  render() {
    return React.createElement('div',
      { className : 'button' + this.state.focused? ' button_focused' : '' },
      React.createElement('button',
        {
          className : 'button__control',
          onFocus : this._onFocus,
          onBlur : this._onBlur
        },
        this.props.text));
  }
}
~~~

I would expect `focus` and `blur` event handlers would be called with `Button` instance context. But they would not. So an error will be  thrown, as no global `setState` method there :(

Let me be clear, I know about ES6 arrow function, as well as other ways to bind function to the context. However as React has it's own EventListener internally, I think it might be possible to provide the desired behaviour out of the box. 

What do you think?

**Comment by spicyj** [comment]
How could React know what context to use? The event handler is attached to the `<button>` DOM component – React could use that as the context when calling the callback but you probably wanted the `<Button>` composite instance, which isn't directly tied to the `<button>` element you're returning.

**Comment by narqo** [comment]
Hm, I thought that native event handlers are attached to the `document` node, while handlers that I declare within the `render` method are stored in some kind of internal "event storage", during component mounting. At the same time, I have noticed, that React, stores component instance inside `ReactLifeCycle` object. If so, it should be possible to store proper (bound) handlers in the "event storage". As well, as find it during unmounting.

**Comment by jacobp100** [comment]
Why would you want to bind the context to the button? How would you then call `setState`? Not to mention, you already get access to the button in `arguments[0].target`.

**Comment by narqo** [comment]
> Why would you want to bind the context to the button?

I **don't**! Please read the description. The issue is about binding event handlers to the **component instance**, not to the HTML-node.

**Comment by jacobp100** [comment]
Sorry, I think I get you now. So in answer to my other thread, yes, this would solve the issue. Although, I don't think this suggestion works.

In the `React.createClass`, all function definitions were imported into an instance of the class with the `bind` method applied already. We can't do this with the ES6 class syntax without using hacks or workarounds.

The issue is that when you call `React.createElement`, `this` becomes `React`—we've completely lost the context of the class instance! Since we don't have access to the context, we can't bind any functions (no `this.setState`). The only way to counteract this would be to use `React.createElement.call(this, …)`, or pass the `this` as an argument (like Array.prototype.forEach and Array.prototype.map). This isn't too different from writing `onClick: this.blur.bind(this)`—it's still really ugly.

With my JSX suggestion, it would be writing `onClick: this.blur.bind(this)` for you, so you don't have to deal with the ugliness.

**Comment by jquense** [comment]
I for one prefer React just get out of the way and let me bind my functions however I want. Auto binding is weird non idiomatic javascript and presumes too much, especially give the performance concerns with .bind(). Admittedly its not proper 'class' behavior but that's the language and I wouldn't want react taking liberties like that outside of createClass

**Comment by jacobp100** [comment]
Sorry for yet a third posting of this code, but I managed to achieve auto-binding. It works by overriding the prototype's functions with bound functions. (So I take it back, this suggestion can work)

```js
class ComponentBase {
  constructor() {
    Object.getOwnPropertyNames(this.constructor.prototype).forEach(function(func) {
      if (!ComponentBase.noAutoBindFuncs.includes(func) && typeof this[func] === 'function') {
        this[func] = this[func].bind(this);
      }
    }, this);
  }
  setState(state) {
    console.log(state);
  }
}
ComponentBase.noAutoBindFuncs = ['render'];

class Component extends ComponentBase {
  onClick() {
    this.setState({ items: ['test'] });
  }
}

var x = new Component;
var y = x.onClick;
y();
```

**Comment by gaearon** [comment]
>Admittedly its not proper 'class' behavior but that's the language and I wouldn't want react taking liberties like that outside of createClass

This.

**Comment by tomatau** [comment]
The majority of cases an event handler will be wanted bound to the instance of the class it was defined... This is why createClass was autobinding... this makes a lot of sense.

createClass was being used as ES6 classes weren't available; and are now being slowly moved away from in favour of ES6 classes too...

I can't see the autobinding from a React.Component being any more 'magic' than the render method it provides in the first place. It removes a lot of boilerplate on having to manually bind 99% of handlers you'll create which to me is a big win.

I think many people will end up adding autobinding back in themselves, just as @jacobp100 has done in the snippet above which will either have to be extending Component or some HOC - both of these being problematic as they will end up being rewritten so much.

I don't think React would be taking liberties on the ES6 class at all, they'll be adding a very useful and common behaviour to React.Component that people can quite easily override if they need (for whatever reason) to change the context of a method from the instance of the Class it was defined.

I can't see any harm from React.Component doing some autbinding other than a little performance loss that most implementations will just add back anyway at render or construction with unnecessary boilerplate.

**Comment by gaearon** [comment]
>It removes a lot of boilerplate on having to manually bind 99% of handlers you'll create which to me is a big win.

Most of the times you can just use arrows, so I don't see a lot of boilerplate.. What do I miss?

**Comment by tomatau** [comment]
> What do I miss?

The arrows aren't implemented yet - if you try them in the latest babel with experiment, playground and runtime: `this` is still undefined within a class' arrow function.

I feel it will be quite a long time until the arrow function behaves in the desired way on a class and until then we have the boilerplate (most likely during transition to 0.13/0.14 when people will be attempting to implemented with class')

**Comment by gaearon** [comment]
>The arrows aren't implemented yet - if you try them in the latest babel with experiment, playground and runtime: this is still undefined within a class' arrow function. Which raises a question of will the arrow function be actually implemented in a way that this will work?

I have been using them for several months now :-). Are you talking about the proposed “arrows in properties” syntax? I mean using arrows when binding handlers:

```js
class App extends React.Component {
  render() {
    return (
      <button onClick={e => this.handleClick(e)}>Test</button>
    );
  }

  handleClick() {
    console.log(this);
  }
}
```

This works and covers my use cases. Surely, it causes extra `bind`s but yeah, for hot paths you can just `bind` them yourself.

I don't really see why it's worth adding autobinding magic to React component classes. You'll face *the exact same problem* with regular ES6 classes that want to listen to something with event handlers.

It makes more sense to use some utility library for autobinding (if you like autobinding), and use it both in React components and other ES6 classes. This really isn't a React-specific problem.

**Comment by tomatau** [comment]
That is precisely the boilerplate I'm talking about.

Normal ES6 classes don't have event handling built in - it would be a feature added to the Class and so autobinding could easily happen there. This is just a common use case for classes and less boilerplate here would, I think, greatly encourage adoption.

But see my edit above - the class instance "autobinding" will work with fat arrows very soon (hopefully) as it seems like fat arrows will have some nice different behaviour on Class definitions than object literals.

**Comment by jquense** [comment]
this is precisely the value in React not making prescriptions about your code.  if you want autobinding you can totally just write a base class or util yourself to handle it.  and for those of us who don't want it we don't need to undo the built in behavior. and to be honest if you want autobinding just use create class, it's already the solution you want. it's not being moved away from or depreciated so there is no reason not to use it if you like the behavior

**Comment by sebmarkbage** [comment]
We've explored other ways that doesn't require binding at all. That would require massive changes to the framework but we have not yet found one that works and is as idiomatic as binding a callback. The only way we would move away from callbacks completely into a fully declarative model with some kind of signal/channel/event. However, IMHO, this API design is still an unsolved problem.

Therefore, the data structure that we use for "events" are callbacks. To do this we need to combine it with a particular instance since you can have multiple instances of a component on the page at any point. We use binding for that. HOW you bind it is up to you.

The most important task of React is to provide an idiomatic component boundary so that different components can interop. This issue is purely about how you implement your own component. It doesn't matter how your component does it as long as it does somehow. You can do it however you want and they'll still work in the larger community.

Therefore, I don't think we'll put anything opinionated like this in the framework.

We'll just recommend using property initializers with an arrow function as one way to do it. @jeffmo is presenting this to the TC-39 committee next week so things are moving along. Babel will adjust to support them.

**Comment by arackaf** [comment]
@sebmarkbage Sorry if this is a stupid question, but is it possible for React to look up the component instance associated with an element that triggered an event, and then just `call` the handler with that component instance as `this`?  That shouldn't really be a breaking change; any handler wired with `bind` would have the bound `this` still take precedence.  And arrow functions do seem to support `call`, though of course the value passed in does not override the lexical `this` that exists where the arrow function is created.  

So I imagine it would boil down to how difficult looking up the appropriate component instance for the given DOM node is.  Is that not feasible for React to do?

**Comment by sebmarkbage** [comment]
@arackaf Imagine something like `<Foo><div onClick={this.onClick} /></Foo>`. It will be created in `this` component but it will pass through `Foo`. Foo can currently intercept it, clone it and do whatever to it. Technically we could track this through the magic "owner" property (which is how refs work) but that was deemed to magical and breaks a number of optimizations and use cases in subtle ways. We hoped to get away from such magic semantics.

**Comment by arackaf** [comment]
@sebmarkbage thanks for replying! I'm glad you chose perf over convenience, no question.

Was it deemed undesirable to simply have that onClick be called with the `this` that exists when <Foo> is created?  Sort of vaguely how `super` is bound at creation time in ES6?

So if Foo intercepts that div and clones it, the onClick's `this` value would not change.

Sorry if that's a stupid question - I'm still relatively new to React :)
