### ISSUE TITLE
Module '"react"' has no exported member 'use'

### ISSUE THREAD

**Issue by Eng1Mahmoud** [facebook/react#30448]
I try to use React 19 beta 
and try to use Hook but when I try import it gives me a warning
Module '"react"' has no exported member 'use'.

why does Hook not exist? and what problem

**Comment by Eng1Mahmoud** [comment]
my package.json >> {
  "name": "react-19",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.0.0-beta-26f2496093-20240514",
    "react-dom": "^19.0.0-beta-26f2496093-20240514"
  },
  "overrides": {
    "@types/react": "npm:types-react@beta",
    "@types/react-dom": "npm:types-react-dom@beta"
  },
  "devDependencies": {
    "@types/react": "npm:types-react@beta",
    "@types/react-dom": "npm:types-react-dom@beta",
    "@typescript-eslint/eslint-plugin": "^7.15.0",
    "@typescript-eslint/parser": "^7.15.0",
    "@vitejs/plugin-react": "^4.3.1",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.7",
    "typescript": "^5.2.2",
    "vite": "^5.3.4"
  }
}

**Comment by Eng1Mahmoud** [comment]
Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
    at trackUsedThenable (

**Comment by hungcung2409** [comment]
It is only available in canary channel [docs](https://react.dev/reference/react/use)
