### ISSUE TITLE
Bug: useState,  state does not update inside websocket.onmessage rather the state value is preserved untill the next render 

### ISSUE THREAD

**Issue by nitesh-github143** [facebook/react#30454]
React version:

## Steps To Reproduce

1.
2.

Link to code example:

## The current behavior
state is not updated inside ws.onmessage , state is preserved inside we.onmessage and the state is working perfectly fine outside ws.onmessage

## The expected behavior
state should get updated

**Comment by josephsavona** [comment]
Can you please create a repro to demonstrate the problem? We’re unable to diagnose issues without sufficient context.

**Comment by surenpoghosian** [comment]
@nitesh-github143 it is normal and expected behavior, 

  ```
ws.onmessage = (data) => {
    // according to react's event loop you can't access
    // latest state by just calling it inside any event handler (even if it is not a websocket)
    console.log(yourState);
  };
```


you can access your latest state inside the event handler using the technique below


```
const yourStateRef = useRef(null);

useEffect(() => {
  yourStateReft.current = yourState;
},[yourState])

ws.onmessage = (data) => {
  console.log(yourStateRef.current);
};

```


...try it out and let us know if it worked for you ))

**Comment by prinkangkang** [comment]
@surenpoghosian
Hi. Can you elaborate on this react event loop thing? I encountered this problem just now and indeed ref could work around. But I think this problem is caused by closure. My friend recommended me to use class to avoid function closure problem. And I would try later.

**Comment by prinkangkang** [comment]
@josephsavona
Hi I met the same problem and I've fixed it with ref. But I still want to know why this problem would occur.
Here is my simple reproduce code. I removed some useless code.

``` 
const handleSubmit = async (e) => {
    try {
      const request = new EventSource('http://localhost:3000/events');
      request.onmessage = (event) => {
        const data = JSON.parse(event.data);
        if(data.message==="end") {
          request.close();
        }
        simulateTyping();
      }
    } catch (error) {
      console.error('Error:', error);
    }
};
  
const simulateTyping = () => {
    console.log(isTyping)
    if (isTyping) return;
    setIsTyping(true);
    console.log("enter the function")
};

```
Remote server sends data at the interval of 1 second. The running result on my pc was always output "enter the function" which was not what I expected. I thought I've already set IsTyping to true and any other time entering this function would return immediately besides the first time.

**Comment by woxxo** [comment]
Same problem on v19.2.0. Can be fixed with an updater function.

```js
useEffect(() => {
	ws.onmessage = (event) => {
		const data = event.data;
		const newMessage: Message = { type: 'peer', text: data };
		setMessages([...messages, newMessage]);  //don't update!

		// the workaround
		//setMessages((prevMessages) => [...prevMessages, newMessage]);
	};
// ..............
```
