### ISSUE TITLE
use hook issue 

### ISSUE THREAD

**Issue by Eng1Mahmoud** [facebook/react#30487]
react-dom_client.js?v=af78aa99:3617 Uncaught 
Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
    at trackUsedThenable (react-dom_client.js?v=af78aa99:3617:23)
    at useThenable (react-dom_client.js?v=af78aa99:4742:20)
    at Object.use (react-dom_client.js?v=af78aa99:4749:57)
    at exports.use (chunk-WQZPVTOA.js?v=af78aa99:1049:36)
    at PostItems (Users.jsx:10:14)
    at react-stack-bottom-frame (react-dom_client.js?v=af78aa99:16336:20)
    at renderWithHooks (react-dom_client.js?v=af78aa99:4598:24)
    at updateFunctionComponent (react-dom_client.js?v=af78aa99:6175:21)
    at beginWork (react-dom_client.js?v=af78aa99:7222:20)
    at runWithFiberInDEV (react-dom_client.js?v=af78aa99:990:18)
![Screenshot 2024-07-26 222611](https://github.com/user-attachments/assets/f058f107-faa5-4cf2-accc-1b66e909e658)
![Screenshot 2024-07-26 222647](https://github.com/user-attachments/assets/668829a0-3b22-43a0-824f-94566e0284cd)

**Comment by Eng1Mahmoud** [comment]
data displayed many time in console and then give me this error

**Comment by jwinr** [comment]
You're using aync/await in a client component, which isn't supported. Try moving the asynchronous data fetching into a useEffect hook and using state to manage the data.

**Comment by Eng1Mahmoud** [comment]
@jwinr So what is the use of use hook if I replace it with useEffect and useState؟

**Comment by AMANn5153** [comment]
If fetchData is being invoked directly inside the component body, it could cause multiple fetches on each render. 
fetchData is an async function, but use expects a Promise or context. Since fetchData is not being invoked as a Promise but just passed as a function, it will not work as intended.

using  useEffect hook can resolve this problem it will only fetch data once the component mount

**Comment by Eng1Mahmoud** [comment]
in react 19 use hook  should be solve call fetch function  inside comment,  but it not work as expected @AMANn5153

**Comment by hungcung2409** [comment]
- Your promise is created every render so it prints out multiple log.
- Just create a promise outside of Component and it will work as expected [[codesanbox](https://codesandbox.io/p/sandbox/react-playground-use-api-63gngr)] 

![image](https://github.com/user-attachments/assets/33209f4f-97fb-4b36-b5d4-77c315671732)

**Comment by amiii123malviya** [comment]
Is this issue still active?

**Comment by Eng1Mahmoud** [comment]
@hungcung2409  thanks it work fine now

**Comment by surenpoghosian** [comment]
@Eng1Mahmoud You can do it this way also 

```
const fetchData = async (): Promise<Record<any, any>> => {
  const resp = await fetch('https://jsonplaceholder.typicode.com/todos/1*');
  const result = resp.json();

  return result;
};

export default function App() {
  const data = use(fetchData());
  return <div>{JSON.stringify(data)}</div>;
}

```
