### ISSUE TITLE
React Todo application example raising warning

### ISSUE THREAD

**Issue by 2color** [facebook/react#3049]
The TodoList component renders a list of `<li>` elements which don't have a unique key which raises the warning:  
> Each child in an array should have a unique "key" prop. Check the render method of TodoList. See http://fb.me/react-warning-keys for more information.

My understanding is that it's done this way for the sake of simplicity and that the unique id is used for performant virtual DOM diffing. 

Is it a good idea having a warning raised for an example on the home page of react?

see: https://github.com/facebook/react/blob/gh-pages/js/examples/todo.js

**Comment by jimfb** [comment]
This was fixed in https://github.com/facebook/react/pull/3271
