### ISSUE TITLE
Bug: How do I synchronize my render function?

### ISSUE THREAD

**Issue by parlay96** [facebook/react#30543]
React version:
18.3.1
## Steps To Reproduce

       // 创建dom, msg的包裹器
        // 创建包裹容器
        const __container = document.createElement("div");
        const root = createRoot(__container);
        // 创建节点
        const wrapper = createElement(ContainerWrapper);
        // 渲染节点
        root.render(wrapper);
      
        document.body.appendChild(__container);
        // I cannot synchronize
        // I don't want to render the __container node on the page. How should I handle it? How can I synchronize my render function?
        setTimeout(() => {
          document.body.appendChild(__container?.firstElementChild);
          // 获取参数配置
          const normalized = handleOptions({ ...params, appendTo: `#${wrapId}` });
          return message({ ...normalized, type });
        });

Link to code example:
not have

**Comment by neehhaa06** [comment]
Hello @parlay96 :)

> Instead of setTimeout, use requestAnimationFrame
> I think you should use it to solve this bug "requestAnimationFrame": Use it to handle synchronization issues between rendering and DOM manipulation.

**Comment by parlay96** [comment]
@neehhaa06 xieixe

**Comment by parlay96** [comment]
@neehhaa06 xiexie

**Comment by MTtankkeo** [comment]
i think the simplest way is to use `createPortal` provided by React, or have you tried it?

> __Docs Reference__:
> https://react.dev/reference/react-dom/createPortal
