### ISSUE TITLE
Bug: useId generates duplicate IDs on initial render (ssr)

### ISSUE THREAD

**Issue by SimonMfroy** [facebook/react#30634]
I am experiencing an issue with the useId hook in React where it generates duplicate IDs on the initial render, the problem disappear when JS hydrate the page.

React version: ^18.3.0
Remix version: ^2.9.1

## Steps To Reproduce

1. To see the error : https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fwww.copinesdevoyage.com%2F#l1c2874
2. Or go to https://www.copinesdevoyage.com/ and disable JS
3. The duplicated ids will be found on avatars

## The current behavior
On the initial render, useId hook generates duplicate IDs

## The expected behavior
useId should produce a unique ID, ensuring that no two components have the same ID.

**Comment by Ang-YC** [comment]
Not sure if this is related to this issue that I have reported earlier?

https://github.com/facebook/react/issues/29021

**Comment by eps1lon** [comment]
We'll not be able to debug this on a full app. Please provide a minimal, cloneable reproduction. Otherwise we'll have to close this.

Maybe check if it repros with React 19 since a similar bug was fixed for 19 (https://github.com/facebook/react/issues/29021)

**Comment by SimonMfroy** [comment]
Thank you for your answers and your help, I'll try this when we'll upgrade to 19 as mentioned on https://github.com/facebook/react/issues/29021
