### ISSUE TITLE
[React 19] Inconsistent documentation of useOptimistic second parameter

### ISSUE THREAD

**Issue by denis-sokolov** [facebook/react#30638]
## Summary
[Main docs](https://react.dev/reference/react/useOptimistic) show that useOptimistic has a required second parameter updateFn.

[The RC blog post](https://react.dev/blog/2024/04/25/react-19#new-hook-optimistic-updates) does not, though.

The current version, [19.0.0-rc-e948a5ac-20240807](https://www.npmjs.com/package/react/v/19.0.0-rc-e948a5ac-20240807), seems to work without the second parameter ([example](https://codesandbox.io/p/sandbox/use-optimistic-multiple-n6hr29?file=%2Fsrc%2FApp.js)).

I opened the ticket here and not in the documentation repo, because this is about the upcoming version, and it seems there might not be clarity on what should be the expected behavior. Forgive me if it still was supposed to go on the other repo.

**Comment by champagnekamal** [comment]
updateFn is not required, but if you use it it will work more like usereducer hook. then you have to make the function for updateFn and then dispatch it to show optimistic value.

**Comment by denis-sokolov** [comment]
Thank you! Then this does belong in the docs repo, made [an issue there](https://github.com/reactjs/react.dev/issues/7098).
