### ISSUE TITLE
[React 19] Conditionally rendered suspendable component using `use()` shows fallback even if promise already resolved

### ISSUE THREAD

**Issue by mordechaim** [facebook/react#30701]
## Summary
I'm trying the new `use()` hook over promises. I found that the suspense will show the fallback if the call to `use()` is delayed, even if the promise already resolved prior to `use`ing it. Namely, Suspense always renders the fallback initially, even if the component never suspends. 

Interestingly, if I `use` the promise in a sibling component, this issue is not present even on the first suspense component.

## Reproduction
[Here's a minimal reproducible example](https://github.com/mordechaim/lazy-suspense).

<details>
<summary>Code backup</summary>

```ts

import { Suspense, use, useMemo, useState } from 'react';

export function App() {
  const [open, setOpen] = useState(false);

  const promise = useMemo(
    () =>
      new Promise<string>((resolve) => {
        console.log('starting promise');

        setTimeout(() => {
          console.log('resolving promise');

          resolve('hello');
        }, 5000);
      }),
    []
  );

  return (
    <>
      <div>
        <button onClick={() => setOpen(true)}>Reveal</button>
        {open && (
          <Suspense fallback='still loading...'>
            <SuspendableGreeting promise={promise} />
          </Suspense>
        )}
      </div>

      {/* Uncommenting the below code will fixed the issue above */}
      {/* <Suspense fallback='loading'>
        <Resolve promise={promise} />
      </Suspense> */}
    </>
  );
}

interface SuspendableProps {
  promise: Promise<string>;
}

function SuspendableGreeting({ promise }: SuspendableProps) {
  const greeting = use(promise);
  return greeting;
}

function Resolve({ promise }: SuspendableProps) {
  use(promise);
  return null;
}
```
</details>

1. Run `npm run dev`
2. Open the page and DevTools
3. Wait 5 seconds for the message "resolving promise" to print
4. Press "Reveal"

**Comment by hungcung2409** [comment]
> Interestingly, if I use the promise in a sibling component, this issue is not present.

Because the Suspend don't have fallback

**Comment by mordechaim** [comment]
> > Interestingly, if I use the promise in a sibling component, this issue is not present.
> 
> Because the Suspend don't have fallback

No, it doesn't happen to the first suspense too.

**Comment by hungcung2409** [comment]
After you change code like this, does it show fallback in the first render ?
```jsx
 {open && (
    <Suspense fallback="still loading...">
      <Resolve promise={promise} />
    </Suspense>
  )}
```

**Comment by eps1lon** [comment]
Does it still show the fallback if you wrap your initial render in `startTransition`?

**Comment by mordechaim** [comment]
> After you change code like this, does it show fallback in the first render ?
> 
> ```js
>  {open && (
>     <Suspense fallback="still loading...">
>       <Resolve promise={promise} />
>     </Suspense>
>   )}
> ```

Does not help, it still shows the fallback. It seems that the promise must be `use`d somewhere for future suspenses to not render the fallback. By using it (even if I discard the result) inside the `Resolve` component (even if I discard the result) it somehow fixes it.

**Comment by mordechaim** [comment]
> Does it still show the fallback if you wrap your initial render in `startTransition`?

I'm not sure what you mean, as `startTransition` can only be called on "updates" not initial render. But if I wrap the `setOpen(true)` call in `startTransition` it indeed resolves the issue.

But, the issue is still present when I use an immediately resolved promise, where I can't wrap anything in a transition, consider the following code:

```js
import { Suspense, use, useMemo } from 'react';

export function App() {
  const promise = useMemo(() => Promise.resolve('hello'), []);

  return (
    <Suspense fallback='still loading...'>
      <SuspendableGreeting promise={promise} />
    </Suspense>
  );
}

function SuspendableGreeting({ promise }) {
  const greeting = use(promise);
  return greeting;
}
```

There's no place for transitions here, and the fallback briefly shows.

**Comment by eps1lon** [comment]
> I'm not sure what you mean, as startTransition can only be called on "updates" not initial render. 

It can be called on the initial render like such:

```tsx

const root = ReactDOMClient.createRoot(container);
React.startTransition(() => {
  root.render(<App />)
})
```

**Comment by mordechaim** [comment]
I'm not at a computer to check at the moment, but this bug is present on Next.js as well, where you can't do this.

**Comment by hungcung2409** [comment]
> Does it still show the fallback if you wrap your initial render in `startTransition`?

Seem it works after wrap setState function in `startTransition`
```
  const clickHandler = useCallback(() => {
    // using startTransition keep the fallback away
    startTransition(() => {
      setOpen(true);
    });

    // setOpen(true);
  }, [setOpen]);
```

[Codesandbox](https://codesandbox.io/p/sandbox/react-30701-cxk37h)

**Comment by eps1lon** [comment]
Showing the fallback immediately outside of a transition is intended behavior that is documented: https://react.dev/reference/react/Suspense#troubleshooting

If there are issues with frameworks, please file a reproduction with that framework against the framework repository first.

**Comment by mordechaim** [comment]
I can't see how this is expected behavior. The docs mention not showing a fallback for non urgent suspense updates. 

This is a different issue. The promise is clearly resolved and shouldn't show a fallback in any case. You can and should still be able to use suspense outside transitions (such as for urgent updates) and this shouldn't happen.

**Comment by mordechaim** [comment]
@hungcung2409 I already established this earlier. @eps1lon asked if the "initial" render from react wrapped in a transition fixes this.

**Comment by hungcung2409** [comment]
So I think your question should be:  "Why the resolved promise can create a suspended update?"

**Comment by mordechaim** [comment]
Whatever, now we're stuck with a bug that the react team believes is intended behavior 🤷

**Comment by eps1lon** [comment]
That's an unfortunate reality with JavaScript. Even a resolved Promise needs another microtask to get the value. 

And for updates outside of transition, React prefers to show the fallback as fast as possible. If you want to defer a fallback in favor of waiting for all the data, wrap the state update in a Transition.
