### ISSUE TITLE
onTouchEnd execute twice in iOS safari

### ISSUE THREAD

**Issue by dexbol** [facebook/react#3076]
onTouchEnd execute twice if `confirm()` function in the event handler.

Live example: http://dexbol.com/static/test.html

First, tap the button, then a confirmation appear, everything seems be okay. Tap "OK" or "Cancel" . This moment if you tap some place around of the button , the confirm appear again, but i does not tap the button 

live example qrcode:

![qrcode](http://i2.tietuku.com/4caf7c3ee496b454.png)

**Comment by spicyj** [comment]
I can't repro this. At any rate, we're not doing anything fancy with touch events so if we're sending it twice it means that we're receiving it twice from the browser and I don't know what we could do to fix that.

**Comment by spicyj** [comment]
(Tested on iPad Air simulator with iOS 8.1.)

**Comment by dexbol** [comment]
@spicyj Thank you for your reply, maybe you are right. Although I do not read Reactjs's source code and do not understand how it works, but the issue exists actually. Please test on a real ios device but not simulator.

Maybe safari make something wrong.And the example of code is very simple, so it can exclude my wrong.

**Comment by camspiers** [comment]
@dexbol If you go to https://jsfiddle.net/3vyx97hc/embedded/result/

You can see the same bug in safari replicated in just basic JavaScript (non-react).

![qrcode 27898174](https://cloud.githubusercontent.com/assets/51294/6408094/43424ef8-be02-11e4-803e-05a7d095128d.png)

**Comment by dexbol** [comment]
@camspiers Thank you very much. I am sorry for my carelessness. It is just safari's bug.

**Comment by camspiers** [comment]
You're welcome!
