### ISSUE TITLE
vanilla propTypes library

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#3079]
I'm thinking that propTypes could be extremely useful in vanilla JavaScript that I write. I'm just exploring the possibility right now, but I am wondering how difficult it would be to pull propTypes out of React into a standalone VanillaJS library. If it sounds like a reasonable thing to do, where would I start?

Edit: I should be more clear. What I'm really after is the ability to add type checking to my functions without using something like TypeScript (not that TypeScript is bad, but I'm investigating alternatives). It would be awesome to have an abstraction to check arguments to a function the way that `propTypes` checks the properties given to components. That's what I'm really after.

**Comment by gaearon** [comment]
There's https://github.com/gcanti/flowcheck although I don't think it supports custom functions.

**Comment by kentcdodds** [comment]
Thanks @gaearon. I'm really hoping for something I can use without pre-processing necessary because I want to distribute it as part of a library.

**Comment by jsfb** [comment]
Proptypes are just functions that throw an error if the prop doesn't match the expected value.  You could actually define your own proptypes.  https://github.com/facebook/react/blob/master/src/classic/types/ReactPropTypes.js

**Comment by kentcdodds** [comment]
Thanks @jsfb, understood. I would just like to be able to use them outside of React reasonably. I think I'm just going to build it myself, just for the fun of it :-)

**Comment by zpao** [comment]
> Proptypes are just functions that return an error

FTFY

Yea, it's not super complicated and hey, this is open source so you can re-purpose our code as long as you license it right. As of now we have no plans to pull them out ourselves so I'm going to close this out.

**Comment by kentcdodds** [comment]
FYI, I did end up creating this: npm.im/api-check :-) it could use some work, but hundreds of developers are benefiting from it via npm.im/angular-formly :-)
