### ISSUE TITLE
Automatically Object.assign when `styles` receives an Array

### ISSUE THREAD

**Issue by appsforartists** [facebook/react#3081]
In React Native, these two styles are automatically composed:

```
<Text style={[styles.ratingValue, getStyleFromScore(criticsScore)]}>
```

Currently, trying a similar technique in React DOM produces this:

```
<span style="0:[object Object];1:[object Object];">
```

Following the principles of "Learn Once, Write Everywhere", the style prop should behave similarly across implementations.

**Comment by spicyj** [comment]
See also #2196. (We do want to get to a consistent story for all of these things, but we're obviously not there yet.)

**Comment by appsforartists** [comment]
Thanks @spicyj.  I thought I searched before posting.  Maybe I forgot to remove the `is:open` filter.

**Comment by af7** [comment]
+1 I am developing in both React Native and React DOM and find the React Native way of merging styles very convenient. It would be great if you could give this a higher priority. Thanks!

**Comment by meepeek** [comment]
Why is it available in react-native and not react ?

**Comment by aweary** [comment]
An RFC would be appropriate here since this is a feature request that will likely require significant review and discussion. If someone would like to pursue that please do so at https://github.com/reactjs/rfcs
