### ISSUE TITLE
DOM Operations Performance Counters

### ISSUE THREAD

**Issue by srcspider** [facebook/react#3086]
Would it be possible to expose some counters from the rendering vdom diff algorithm resulting dom operations when in development mode?

React does a really good job at running fast but it's still entirely possible for human error to thwart it's algorithms; as well as human ignorance (from it being fast enough to hide our bad code) to lead to poor performance in the long term. 

While this can generally be visible when it's really really bad, it would be nice to have an interface that sends back an object with counters every time it touches the dom to fully satisfy a diff. They would only be counters, isolated per `React.render(node, dom)` and wouldn't reset, the user would be responsible for subtracting previous values (just like one would do when measuring fps in a animation loop).

**Example Use Case**: I press a button, visually only some text changes and a field appears but the counters indicate several DOM nodes were created along with various other operations. Then I would know that either (a) I'm doing something horribly wrong (b) I'm not doing something wrong but there's likely a much more efficient way to do it. Assuming the counters reflect back what we actually think should happen then they would just be a nice check rendering is doing well (or at least as good as we think it should).

**Comment by spicyj** [comment]
That's exactly what the perf tools in the addons do – see printDOM in particular:

http://facebook.github.io/react/docs/perf.html

Let me know if you're looking for something else.

**Comment by srcspider** [comment]
@spicyj 

So tried that. It's definitely not what I'm looking for. What you have there are **perf timers**, I'm looking for **perf counters**. I need the presentation of **work done**, not **time spent doing work**. Please re-open.

Issue with measuring time spent... 

 - different browsers (IE8 being the worst) will spend more time on various operations then others
 - different systems will spend more time on operations then others (better CPUs + other factors)
 - even if the system is decent, we can't really assume just how many resources the browser has at the time it's trying to do the work; on dev machines since we're focusing on doing the work we're usually dedicated a lot of resources to just that task and dev machines also may just be more buffed then user machines so even if I have the worst browser installed it's hard to emulate user-land times

On the other hand, if I'm measuring work done "this many hard dom changes + this many easy changes + this many other changes" then I can intuitively tell that either,

 - the task may run poorly on so-and-so browser, based on the operations counters
 - the task is doing more work then it needs to
 - the task is as efficient or good enough as it can be given the state changes involved

There also some specific issues with how the Perf API is intended to work too:
 
 - the API seems specifically designed to be a "hand tool" you run in the console yourself rather then integrate in the project; nothing against having more measurement tooling to go along with in-browser frame data but I personally need instrumentation not a on-demand tool
 - grabbing something like an initial render is fairly straight forward but grabbing render changes seems really akward... [why does something like this not work for example](http://pastie.org/private/oz5tiz88gcveiektiqa)? The documentation only really mentions in passing how to get it for mount/unmount which is not the common case; the common case is how it performs for **any** state changes (the mount/unmount cost being preferably measured as part of the cost of the parent state changing)
 - the timing data is... not useful; I can't really say definetly with out a lot of time investment into integrating it on some more serious level, but I should be able to get *useful* or *usable* data even for a really really simple example, since it's easier to conceptualize as right/wrong small changes in state rather then everything at once, and easier to fix as well
 - it requires too much minute instrumentation; the only thing I'm really interested in excluding is components that are rooted to a separate dom node (ie. potentially other people's work), otherwise I just want the counters/timers to fire back at me both on every diff of the virtual representation and on every actual work set to satisfy diff that required changes. And yes I do realize I could potentially stick it into mixin (maybe!? not even sure if it doesn't bork when it has Perf.start too many times) and then stick that everywhere but that's just a lot of busy work for what is conceptually really really simple.
 - the api prints to the console; sorry but I'm not interested in printing to the console, I'm actually more interested in having the data so I can either (a) customize the way I print it to the console, right now you can only really filter what you want not display it how you want (b) build more sophisticated but easier to use way of visualizing the data

---

This is how simple the API should be,

*some boilerplate that can dealt with very simple helpers inside the Perf API itself*
```js
var countDiff = function (prev, next) {
	var diff = _.map(next, function (val, key) {
		return val - prev[key];
	});
	return diff;
}

prevVirtualCounters = {
	diffs: 0,
	componentsDiffed: 0,
	// ...

	// nothing against timers being here for visual representations 
	// that can make good use of them
	totalTimeSpent: 0,
	totalTimeWasted: 0
	// ...
};

prevDOMCounters = {
	domNodesAdded: 0,
	domMounts: 0,
	domAttributeChanges: 0,
	domTextChanges: 0,
	// ...

	// having counters for specific operations performed 
	// would also be helpful; as much transparency as possible

	// like with virtual counters, timers would be "nice to have" 
	// if readily available; but making the work transparent is more useful
	totalTimeSpent: 0
	// ...
};
```

*example*
```js
var renderingUnit = React.render(<CompC/>, document.querySelector('#mountNode'));

// Simple Analysis
// ---------------

renderingUnit.onVirtualRepresentationChange(function (counters) {
	countDiff(prevVirtualCounters, counters)
	console.log(diff);
});

renderingUnit.onDOMChange(function (counters) {
	// ...similar to onVirtualRepresentationChange...
});

// Frame Analysis
// --------------

global.requestAnimationFrame(function () {
	virtualCounts = renderingUnit.getVirtualRepresentationCounters();
	domCounts = renderingUnit.getDOMChangeCounters();
	// ...animation etc...
});
```

For visualising individual components I'd rather have markers then have to go though hoops of setting up start/stop. Essentially just have it so at any point I can say `Perf.tag(this, 'whatever text you want')` and that would simply add the text to an `tags` array on the counters. The array is reset every time a new diff/change _is reported_ so it essentially gives you the ability to filter down to what you want, similar to how you can in something like a network tab filter to only CSS or only XHR etc.

*very simple usage example*
```js
var CompB = React.createClass({
	render: function () {
		Perf.tag(this, this.displayName);
		return <div>CompB</div>;
	}
});
```

**Comment by irvinebroque** [comment]
@srcspider - what you're describing seems like it'd fit well with what @gurdasnijor presented at ReactConf:

https://github.com/gurdasnijor/component-flow-loader
http://youtu.be/OZGgVxFxSIs

Where a loader could inject the "work done" perf tracker you're describing automatically, even if it's not part of React's own perf tools.

**Comment by srcspider** [comment]
@irvinebroque Thats not a bad idea, wouldn't it better to be implemented directly in react? Main issue being that any solution I make will be heavily coupled to reacts current implementation, so it's impossible to write anything that will not break with every single patch to react. Well, I use the world "break" loosely, more like give false results.
