### ISSUE TITLE
Bug: Focus restore after elements are reordered does not work in child windows

### ISSUE THREAD

**Issue by ling1726** [facebook/react#30864]
This affects various Microsoft products that use child windows, and is an accessibility bug for users because focus is lost when they interact with an app and the active element is moved in DOM by React.

React version: 18.3.1

## Steps To Reproduce

1. Clone the repro repo https://github.com/ling1726/react-child-window-focus-repro
2. Run `npm install`
3. Run `npm run dev`
4. Open the demo app in `http://localhost:5173/`
5. Reorder the items with `ArrowUp` and `ArrowDown`
6. Open example in child window
7. Reorder the items with `ArrowUp` and `ArrowDown`
8. Notice that focus is lost immediately after reordering

Recording: 
![focus repro](https://github.com/user-attachments/assets/81c4b4f9-08b5-4356-8251-49b909771f3f)

Link to code example: https://github.com/ling1726/react-child-window-focus-repro

## The current behavior
The current `getActiveElementDeep` always uses the global `window` keyword. **Note this snippet is from the React codebase**
https://github.com/facebook/react/blob/4f604941569d2e8947ce1460a0b2997e835f37b9/packages/react-dom-bindings/src/client/ReactInputSelection.js#L59-L71

This fails focus restore when the active element is moved by React because it never gets the correct active element in a child window. 

## The expected behavior

When React moves an active element it should restore focus to the active element in a child window

**Comment by nkalpakis21** [comment]
built an app to get paid for this PR
https://www.n0va-io.com/discover/facebook/react

**Comment by Felixdiamond** [comment]
Your current implementation only uses the global `window` object which is probably an issue because focus can be within an iframe or child window, where window would be different.

Try this snippet:
```javascript
function getActiveElementDeep(win = window) {
  let element = getActiveElement(win.document);
  while (element instanceof win.HTMLIFrameElement) {
    if (isSameOriginFrame(element)) {
      win = element.contentWindow;
      element = getActiveElement(win.document);
    } else {
      return element;
    }
  }
  return element;
}
```

**Comment by ling1726** [comment]
@Felixdiamond  to clarify the snipped linked is from React's codebase 😅, that is not my code

**Comment by ling1726** [comment]
@josephsavona  how does this fix make it to a release? is it it possible to make it land in a patch release for react 18? Would like to have a way to fix issues for disabled users who end up losing focus on an application when DOM get rearranged

**Comment by sophiebits** [comment]
Hey @ling1726 — we're not currently planning to make any more 18.x releases but there is a new 19 RC last week that you can try updating to. The [breaking changes](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#breaking-changes) are pretty minor so hopefully it is an easy upgrade.
