### ISSUE TITLE
Bug: Footer Unknown Text Found

### ISSUE THREAD

**Issue by Chehak** [facebook/react#30872]
![Screenshot (35)](https://github.com/user-attachments/assets/2da119a1-5758-420f-aea0-88f127545070)

Footer has some unknown text , on clicking the username [@sawaratsuki1004](https://twitter.com/sawaratsuki1004)  logo changes from the header

**no uwu plz
Logo by @sawaratsuki1004 **

**Comment by xennia316** [comment]
I don't quite understand the problem. Can you please expatiate? 
@Chehak

**Comment by nkalpakis21** [comment]
@Chehak built an app to get paid for this PR
https://www.n0va-io.com/discover/facebook/react

**Comment by Chehak** [comment]
> I don't quite understand the problem. Can you please expatiate? @Chehak

Go to react.dev and see the footer , there is some unknown text , Go to screenshot

**Comment by Chehak** [comment]
> @Chehak built an app to get paid for this PR https://www.n0va-io.com/discover/facebook/react

I don't understand , what kind of project you are asking for

**Comment by sasibhumaraju** [comment]
> > I don't quite understand the problem. Can you please expatiate? @Chehak
> 
> Go to react.dev and see the footer , there is some unknown text , Go to screenshot

![image](https://github.com/user-attachments/assets/5530d651-87c2-4aca-a968-0b414d459b0e)
