### ISSUE TITLE
onEnded not working for <audio>

### ISSUE THREAD

**Issue by LukeChannings** [facebook/react#3087]
I have an Audio element and I want to know when it's finished playing. the event is `ended`,
and this event works natively. React doesn't appear to be mapping the ended event.

``` jsx
<audio onEnded={ this.unsetPlayingItem } src={ url } autoPlay="true" controls />
```

I'm very new to React so maybe there's something I'm missing, but it seems like this is a bug.
If React doesn't wrap all native DOM events then is there a way to easily bind the listener another way?

**Comment by syranide** [comment]
It's not currently supported by React it seems:
https://github.com/facebook/react/blob/master/src/browser/eventPlugins/SimpleEventPlugin.js

You can always attach listeners yourself in `componentDidMount/Update` for now, it's not as neat, but it works.

**Comment by jtenner** [comment]
Currently needing this feature, but thanks for the workaround!

**Comment by nhunzaker** [comment]
Looks like this works:
https://jsfiddle.net/84v837e9/144/
