### ISSUE TITLE
React 0.13 and Binding

### ISSUE THREAD

**Issue by jacobp100** [facebook/react#3090]
I noticed that the new version of react will require manual binding. This problem will be lessened with ES7, but will still be there. I want to recommend an extension to the JSX language to bind functions to the scope: `=>` over `=` (akin to arrow functions).

```jsx
<button onClick=>{ this.onClick }>Submit</button>
```

**Comment by narqo** [comment]
Don't you think that #3040 might solve the problem?

**Comment by jacobp100** [comment]
Nope!

**Comment by syranide** [comment]
Closing this because it's really about JSX and not React (and you already created an issue over there).

**Comment by jacobp100** [comment]
Excerpt from https://github.com/facebook/jsx/issues/27#issuecomment-74124412 as an alternative to using JSX syntax to bind.

```js
class ComponentBase {
  constructor() {
    var excludeFuncs = ['render'];
    Object.getOwnPropertyNames(Object.getPrototypeOf(this)).forEach(function(func) {
      if (!excludeFuncs.includes(func) && typeof this[func] === 'function') {
        this[func] = this[func].bind(this);
      }
    }, this);
  }
  setState(state) {
    console.log(state);
  }
}

class Component extends ComponentBase {
  onClick() {
    this.setState({ items: ['test'] });
  }
}

var x = new Component;
var y = x.onClick;
y();
```

**Comment by gaearon** [comment]
>keep this as discussion for implementing this in the React core

I may be misinformed but I think the whole point of making ES6 classes available is for React to *stop* trying to provide a type system of its own. Thus autobinding for non-`createClass`-based classes shouldn't in my opinion belong in the core.

**Comment by jacobp100** [comment]
I think the point was more to not to have another class system, and just use the standard. Whilst my favourite suggestion is still doing this via JSX, overriding prototypal properties like this is not uncommon. See `Array`, where an Array instance has it's own `length` property, which overrides the prototype's `length` property.
