### ISSUE TITLE
return a balise

### ISSUE THREAD

**Issue by djdelarue** [facebook/react#3093]
Hi,

I searched since this morning how I can return a balise a with information.

this is my line:
```
return (<div><a href="mailto:{this.state.user.email}">{this.state.user.email}</a></div>);
```

however, when I write this, on my page if i click on my email it doesn't work because my mail field is fill with {this.state.user.email} and not firstname.name@mail.com

How can I do?

Regards

**Comment by a-ignatov-parc** [comment]
Try this:
```
return (<div><a href={"mailto:" + this.state.user.email}>{this.state.user.email}</a></div>);
```

**Comment by djdelarue** [comment]
Thanks for your answer, no it doesn't work i have the same problem my mail field is fill with {this.state.user.email}

**Comment by djdelarue** [comment]
Thanks for you answer, yeah it works :) !
