### ISSUE TITLE
Chinese Doc

### ISSUE THREAD

**Issue by yibuyisheng** [facebook/react#3094]
My friends and I are translating [the documents to Chinese](https://github.com/reactjs-cn/react-docs) these days, and we plan to do a lot of jobs to introduce React to Chinese front-end developers, like a forum for discussing, some useful components, writing some blogs, etc. So, is it ok to add a link to our [organization](https://github.com/reactjs-cn/) in README.md? Thanks!

**Comment by spicyj** [comment]
(If we do this, we should link to https://github.com/reactkr too.)

**Comment by littlee** [comment]
Which one is the official Chinese doc?

**Comment by yibuyisheng** [comment]
@littlee http://reactjs.cn/ 此处的翻译得比较好，可以参考

**Comment by jimfb** [comment]
The reactjs.cn site is out of date at this point, and we are maintaining our own translation, so it might make the most sense to point reactjs.cn to http://facebook.github.io/react/docs/getting-started-zh-CN.html

**Comment by yibuyisheng** [comment]
@jimfb Thanks for you notification. We will keep in pace with the official documents.

**Comment by jimfb** [comment]
Ping @yibuyisheng: This site is still showing React 13.0, despite the fact we're on 14.7.  if you are not going to keep in pace, it might make the most sense to point reactjs.cn to http://facebook.github.io/react/docs/getting-started-zh-CN.html
