### ISSUE TITLE
Getting 'unknown runtime error' in IE8

### ISSUE THREAD

**Issue by flq** [facebook/react#3095]
Hi there,
after doing some searching I could not find what this could be about, so I'll put it here in the hopes that some people know a lot more about this than me.

I am trying to run a reactjs app in IE8. I have referenced __es5-shim & sham__, as well as __console-polyfill__.

I am getting this kind of error which seems to be related to changing `innerHTML` of some element. I am using the unminified verison of the react currently available at npm (_0.12.2_). Here is the function throwing:

```js
if (ExecutionEnvironment.canUseDOM) {
  // IE8: When updating a just created node with innerHTML only leading
  // whitespace is removed. When updating an existing node with innerHTML
  // whitespace in root TextNodes is also collapsed.
  // @see quirksmode.org/bugreports/archives/2004/11/innerhtml_and_t.html

  // Feature detection; only IE8 is known to behave improperly like this.
  var testElement = document.createElement('div');
  testElement.innerHTML = ' ';
  if (testElement.innerHTML === '') {
    setInnerHTML = function(node, html) {
      // Magic theory: IE8 supposedly differentiates between added and updated
      // nodes when processing innerHTML, innerHTML on updated nodes suffers
      // from worse whitespace behavior. Re-adding a node like this triggers
      // the initial and more favorable whitespace behavior.
      // TODO: What to do on a detached node?
      if (node.parentNode) {
        node.parentNode.replaceChild(node, node);
      }

      // We also implement a workaround for non-visible tags disappearing into
      // thin air on IE8, this only happens if there is no visible text
      // in-front of the non-visible tags. Piggyback on the whitespace fix
      // and simply check if any non-visible tags appear in the source.
      if (WHITESPACE_TEST.test(html) ||
          html[0] === '<' && NONVISIBLE_TEST.test(html)) {
        // Recover leading whitespace by temporarily prepending any character.
        // \uFEFF has the potential advantage of being zero-width/invisible.
        node.innerHTML = '\uFEFF' + html;

        // deleteData leaves an empty `TextNode` which offsets the index of all
        // children. Definitely want to avoid this.
        var textNode = node.firstChild;
        if (textNode.data.length === 1) {
          node.removeChild(textNode);
        } else {
          textNode.deleteData(0, 1);
        }
      } else {
        node.innerHTML = html;
      }
    };
  }
}
```

According to the line number it is the line `node.innerHTML = html;` in the else branch from which the exception originates.

Would love to hear what this could be about.

**Comment by zpao** [comment]
Do you have steps to repro? This is the first we're hearing of this being a problem. cc @syranide

**Comment by flq** [comment]
Yes, I'll have access to the code tomorrow. It is a prototypical project, I'll put it in a repo and pass on the link. It's browserify-based, so it should be straightforward to get it up and running.

**Comment by syranide** [comment]
```
>>document.createElement('style').innerHTML = '';
  "Unknown runtime error"
```

I.e. you get that when you call `innerHTML` on a node which doesn't support it.

**Comment by flq** [comment]
Yes, I read something about the problem, unfortunately I don't have direct control about that particular call. Either way, I now have the repo on github which (_hopefully?_) reproduces the issue:

https://github.com/flq/hierarchy_selector

Would be happy to hear what you figured out.

**Comment by syranide** [comment]
@flq That works just fine in IE8 for me and I can't spot anything funky in the code I think. Anyway, all I need is the tag name of the node, if you can reproduce it on your end, simply enable debugging and check `node`.

**Comment by flq** [comment]
Okay, the node in question was __"section"__, which is unknown to IE8, which causes it to throw up badly if you try to set its innerHTML. Changing it  to __"div"__ fixed the issue :dizzy_face: 

Sorry to bother you, and thanks for looking into this - I'll leave you the satisfaction of closing :bow:

**Comment by syranide** [comment]
@flq `<section>` is OK in IE8, but you need to use [html5shiv](https://github.com/aFarkas/html5shiv) or *cough* my minimal fork [shivie8](https://github.com/syranide/shivie8) which uses a simple hack to make them behave and style correctly in IE8.

> Sorry to bother you, and thanks for looking into this - I'll leave you the satisfaction of closing :bow: 

No worries :)

**Comment by heldinz** [comment]
A note for anyone else getting this error: it can also occur when the resulting HTML would be invalid. For example in my case, I was trying to mount an `li` node inside another `li`, which resulted in an Unknown Runtime Exception in IE8.

**Comment by ThomasChan** [comment]
FYI: I got this error in my react component , because I wrote a `ul` inside a `dd` element (つд⊂)

**Comment by jimfb** [comment]
@ThomasChan Can you provide a jsfiddle that demonstrates the problem?

**Comment by ThomasChan** [comment]
@jimfb https://jsfiddle.net/4czxj5d4/  i tried, but react running in ie8 looks like need compile with es5-shim and core-js(i used webpack for my dev) other wise it's got an error said object not support some method in react.min.js
...
