### ISSUE TITLE
Race in tutorial with optimistic updates

### ISSUE THREAD

**Issue by cancan101** [facebook/react#3099]
In the last step of the [tutorial](http://facebook.github.io/react/docs/tutorial.html) where optimistic updates are added, I believe there is a race condition if the following occurs:
1. `loadCommentsFromServer` called by `setInterval`.  ajax GET call started.
2. `handleCommentSubmit` called adding new comment to `CommentBox`'s state. ajax POST call started.
3. ajax call by `loadCommentsFromServer` returns with stale data.
4. ajax call by `handleCommentSubmit` returns with new data.
5. `loadCommentsFromServer` called by `setInterval`.  ajax GET call started.

This will result in `initial_comments -> new_comments -> initial_comments -> new_comments`  being seen by user.

**Comment by spicyj** [comment]
That sounds plausible. Interested in making a fix for this? If it requires a lot of code it's probably not worth it but if it's just a line or two extra I'm happy to take it.

**Comment by gaearon** [comment]
We removed that tutorial so no longer applicable.
