### ISSUE TITLE
label "for" property

### ISSUE THREAD

**Issue by SeyelentEco** [facebook/react#310]
React v0.4.1 doesn't seem to support to "for" property on labels.  Search didn't turn up anything in the github repo about it.

**Comment by yatrix7** [comment]
htmlFor...son of a <redacted>. Took me over an hour to find this. Hehe.

**Comment by sophiebits** [comment]
@yatrix7 You should’ve seen a console warning pointing you to the problem.

**Comment by yatrix7** [comment]
@sophiebits Looking at the console would have been way too easy. :) I'm sure it was there. I was *really* convinced it was how I'd written my styled-component, so I went down that road until I had an "aha!" moment, remembering React (I'm new!) doesn't always use the html attribute names. Then I felt real dumb.

**Comment by shirshak55** [comment]
If u use typescript this error will immediately be shown :)
