### ISSUE TITLE
Extra nodes emitted when rendering the result of mapping over an Immutable collection 

### ISSUE THREAD

**Issue by gurdasnijor** [facebook/react#3102]
Basically; this: 

![screenshot 2015-02-09 16 32 18](https://cloud.githubusercontent.com/assets/1755404/6119087/27db095c-b079-11e4-842b-2f8be00827e9.png)

Yields this:
![screenshot 2015-02-09 16 33 18](https://cloud.githubusercontent.com/assets/1755404/6119083/2580dc86-b079-11e4-8886-1d162d7322c4.png)

It looks like properties from the immutable wrapper are being emitted along with the actual values themselves.  

Going to look into this myself when I get some time later today, but figured it'd be good to get it tracked with an issue.

Thanks!

**Comment by zpao** [comment]
I'm going to guess this is relevant: https://github.com/facebook/react/pull/3030/files#r24046572

**Comment by gurdasnijor** [comment]
Was actually on 12.2; has been resolved since then: closing

**Comment by zpao** [comment]
cc @sebmarkbage

**Comment by sebmarkbage** [comment]
cc @leebyron

**Comment by sebmarkbage** [comment]
@gurdasnijor Is this using React 0.12 or 0.13?

**Comment by leebyron** [comment]
From the HTML output, it looks like you're using React v0.12 (current production version).

You need to explicitly cast the Immutable collection to an array:

```js
<ul>
  {Immutable.List([1,2,3]).map(i => <li>{i}</li>).toArray()}
</ul>
```

This won't be necessary in v0.13, as React children accepts any iterable, not only array, which will include Immutable collections (as well as ES6 collections).

**Comment by gurdasnijor** [comment]
@leebyron I was running v0.12.2;

Just checked, and I can verify that the issue isn't produced with 0.13.0-beta.1 (installed from npm)

**Comment by frodosamoa** [comment]
:+1:
