### ISSUE TITLE
[React 19] useOptimistic is not updating its optimistic collection immediately

### ISSUE THREAD

**Issue by jsoneaday** [facebook/react#31020]
I have this component that I created where I'm testing useOptimistic and don't have a real backend to call to. So my data source is a variable in another module called messagesOnApi. I have a local state variable messagesRetrievedFromApi that I use to load the data from my fake api, messagesOnApi, and then when I call useOptimistic I pass the messagesRetrievedFromApi state variable as the first parameter.
When I make my update to the api data I add a delay but instead of my optimistic data updating immediately it only updates after the delay. Why? 
This is the github with entire source, https://github.com/PacktPublishing/Full-Stack-React-TypeScript-and-Node-2nd-Edition/blob/main/Chap5/components/src/OptimisticMessages.tsx. This is the main component.

```
import {
  useOptimistic,
  useState,
  MouseEvent,
  ChangeEvent,
  useTransition,
  useEffect,
} from "react";
import { Message, messagesOnApi } from "./MessagesData";

export function OptimisticMessages() {
  const [messagesRetrievedFromApi, setMessagesRetrievedFromApi] = useState<
    Message[]
  >([]);
  const [message, setMessage] = useState("");
  const [optimisticMessages, addOptimisticMessage] = useOptimistic<
    Message[],
    string
  >(messagesRetrievedFromApi, (currentMessages, message) => {
    const finalMessages = [
      ...currentMessages,
      { id: getNextId(currentMessages), message },
    ];
    return finalMessages;
  });
  const [_isPending, startTransition] = useTransition();

  useEffect(() => {
    const data = JSON.parse(JSON.stringify(messagesOnApi));
    setMessagesRetrievedFromApi(data);
  }, []);

  const addMessage = async (message: string) => {
    addOptimisticMessage(message);
    await new Promise((res) =>
      setTimeout(() => {
        messagesOnApi.push({
          id: getNextId(messagesOnApi),
          message,
        });
        res(null);
      }, 2000)
    );

    const data = JSON.parse(JSON.stringify(messagesOnApi));
    setMessagesRetrievedFromApi(data);
    setMessage("");
  };

  const onChange = (e: ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    setMessage(e.target.value);
  };

  const onClick = async (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();

    startTransition(() => {
      addMessage(message);
    });
  };

  return (
    <div>
      <input value={message} onChange={onChange} />
      <button onClick={onClick}>add</button>
      <ul style={{ listStyleType: "none" }}>
        {optimisticMessages.map((m, i) => (
          <li key={i}>{m.message}</li>
        ))}
      </ul>
    </div>
  );
}

function getNextId(currentMessages: Message[]) {
  let id = 0;
  for (let i = 0; i < currentMessages.length; i++) {
    if (currentMessages[i].id > id) id = currentMessages[i].id;
  }
  id += 1;
  return id;
}
```

**Comment by eps1lon** [comment]
Can you distill this into a minimal repro with as little files as possible? You can use https://react.new for that.

**Comment by jsoneaday** [comment]
> Can you distill this into a minimal repro with as little files as possible? You can use https://react.new for that.

Here's a new project with just the affected component OptimisticMessages, https://github.com/jsoneaday/optimistic. Note I am using useTransition and not forms in this example.

**Comment by nikhilsnayak** [comment]
@jsoneaday  The issue in this approach is optimistic state is being set inside the action (async func). But the correct approach it to set optimistic state outside the action but inside transition. Here is the Diff that will fix the issue

![image](https://github.com/user-attachments/assets/d0179835-fa60-4699-b8fa-229fea481b7b)

**Comment by jsoneaday** [comment]
Ok this works but there's some detail I'm not getting. It only works if I make the startTransition's function async and then call addMessage as await.
Why is that? In other words if addOptimisticMessage runs first, and it resets the optimisticMessage, why does it matter that addMessage has not completed yet? addMessage does not update optimisticMessage directly.
If addMessage was not an async call and therefore an async transition was not needed would I still need to make the change you stated or would it work in the original order I had it.

**Comment by jsoneaday** [comment]
I just tried removing all the async stuff and just keeping the setTimeout and as I suspected it does not work. Adding new input text and clicking the button only adds the text to some kind of queue. It is only on the next text input and button click that the immediate prior text value shows up. So then this only works when the original state matched to useOptimistic is updated via an async call. I updated the code like this.

```
const addMessage = (message: string) => {
    setTimeout(() => {
      messagesOnApi.push({
        id: getNextId(messagesOnApi),
        message,
      });
    }, 2000);

    const data = JSON.parse(JSON.stringify(messagesOnApi));
    setMessagesRetrievedFromApi(data);
    setMessage("");
  };

  const onChange = (e: ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    setMessage(e.target.value);
  };

  const onClick = async (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();

    startTransition(() => {
      addOptimisticMessage(message);
      addMessage(message);
    });
  };
```

**Comment by nikhilsnayak** [comment]
According to my knowledge and understanding of react 19 features, optimistic state updates work only inside actions which is nothing but an async transition.

So making the function passed to startTransition async and awaiting addMessage will also work. (action = async transition)

![image](https://github.com/user-attachments/assets/9ce294b5-74f8-4aa9-a3b3-b8996785ff04)
