### ISSUE TITLE
[Help Wanted] How can I become a member of reactjs?

### ISSUE THREAD

**Issue by lumirlumir** [facebook/react#31095]
First of all, I apologize for raising this issue in this repository. My colleague and I have already asked this question in [react.dev](https://github.com/reactjs/react.dev/issues/7186) and [translation.react.dev](https://github.com/reactjs/translations.react.dev/pull/283#issuecomment-2366208490), but we haven’t received any responses.

As mentioned in [translation.react.dev](https://github.com/reactjs/translations.react.dev?tab=readme-ov-file#adding-a-maintainer), I’m raising this question here.

> If the translation's existing maintainers become unresponsive for more than a month, please raise an issue on this repository. If you don’t receive a response in a week, please escalate the issue to the main React repository.

---

Hello. I am currently a collaborator on the KOREAN [ko.react.dev](https://github.com/reactjs/ko.react.dev) project.

However, as a collaborator, I lack certain permissions that are available to members, which are essential for maintaining the translation repository. These include access to Vercel, the ability to add other members, and permissions to manage GitHub Actions workflows.

All of these permissions are necessary to effectively maintain the repository. I have received approval from the other maintainers, but they mentioned they are unsure of the process for becoming a member of the reactjs organization.

Could you please guide me on the steps I need to take to become a member of reactjs?

**Comment by rickhanlonii** [comment]
I replied in: https://github.com/reactjs/react.dev/issues/7186
