### ISSUE TITLE
[DevTools Bug]: Script tag connection method not working in 6.0.0

### ISSUE THREAD

**Issue by MMMartt** [facebook/react#31100]
### Website or app

A basic Create React App project with React DevTools connected via script tag.

### Repro steps

1. Install React DevTools globally: `npm install -g react-devtools` or `yarn global add react-devtools`
2. Create a new React app: `npx create-react-app my-app`
3. Navigate to the project directory: `cd my-app`
4. Open `public/index.html` and add the following script tag at the beginning of head tag:
   ```html
   <script src="http://localhost:8097"></script>
   ```
5. Start the development server: `npm start` or `yarn start`
6. In a separate terminal, start React DevTools: `react-devtools`
7. Open the app in a browser and check the console for any connection errors

This bug happens consistently when following the repro steps above. It occurs with the recently released React DevTools version 6.0.0, while it worked correctly in the previous version.

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Hey @MMMartt, thanks for opening this issue and providing a repro.

I found an issue and will put up a fix soon, this should be available in 6.0.1 in a week or two.
