### ISSUE TITLE
React.addons.TransitionGroup fails to remove multiple children from the DOM at the same time

### ISSUE THREAD

**Issue by spudly** [facebook/react#3111]
When using React.addons.TransitionGroup, you can only remove one item at a time. If you remove more, it will fail to remove all but the last child out of the DOM.

Later when the children are added back again, those that were not removed will not have their special lifecycle methods (componentWillEnter/componentDidEnter) called because they were already in the DOM.

Here's a JSFiddle illustrating the problem:
http://jsfiddle.net/2o5bjst2/1/

**Comment by spicyj** [comment]
Fixed in #2549.
