### ISSUE TITLE
getDOMNode fails to get dom node on Safari 8.0.3

### ISSUE THREAD

**Issue by aronallen** [facebook/react#3112]
I am testing out React and I have discovered some inconsistencies between all other browsers and Safari 8.0.3 on OS X. When I try to call the this.getDOMNode() from within Safari 8.0.3 the DOM node returned is not the actual node that is mounted in the DOM, I suspect it is the virtual copy from reacts virtual DOM. I try to call getBoundingClientRect() on it, and it returns an empty ClientRect object.
The same code works as expected in Chrome (Version 39.0.2171.95 64-bit) and Firefox (35.0.1)

Worth noting, I am using the jsx preprocessor reactify with gulp.

```javascript
var React = require('react');
module.exports = React.createClass({
	componentDidMount : function() {
		var node = this.getDOMNode();
		console.log(node);
		var rect = node.getBoundingClientRect();
		console.log(rect);
	},
	render : function() {
		return (
			<div className="react-error" >
			</div>
		);
	}
});
```

**Comment by aronallen** [comment]
This is how i am mounting the node
```javascript
var node = React.render(React.createElement(ReactError, 
null), poster);
```
This is my HTML

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="/style.css">
</head>
<body>
	<div id="poster">
		
	</div>
	<div id="poster2">
		
	</div>
</body>
<script src="/app.js"></script>
</html>
```

**Comment by syranide** [comment]
If `this.getDOMNode().parentNode` is set then I can't imagine this being anything but a bug in Safari. React just sets `.innerHTML` and then calls `componentDidMount`.

I could be wrong, but I can't see this being anything but that at the moment.

**Comment by aronallen** [comment]
It seems to work fine in this fiddle http://jsfiddle.net/69z2wepo/2130/
So now I am suspecting gulp and reactify.

**Comment by cody** [comment]
@aronallen That fiddle does not work for me, it shows an empty object.

But this works:
```js
for (var i in rect)
  console.log(i, rect[i]);
```

**Comment by aronallen** [comment]
Edit, it seems to be reproducible, I was a bit too quick to me, the returned rect in the fiddle has no properties.

**Comment by aronallen** [comment]
it seems the error lies with console.log in safari, not React, I am resubmitting this bug in apples feedback.

**Comment by zpao** [comment]
Thanks for tracking it down!
