### ISSUE TITLE
Bug: Sidebar Dropdown Doesn't Close on 

### ISSUE THREAD

**Issue by sanjay-gangwar4410** [facebook/react#31155]
When clicking on a sidebar option that triggers a dropdown menu, the dropdown opens as expected. However, clicking the same option again does not close (toggle off) the dropdown. The dropdown remains visible, and the expected behavior of closing the dropdown on the second click does not occur.

![image](https://github.com/user-attachments/assets/2b6c3080-0483-4f61-8658-6658d5b7c5a9)

React version: 18.3.1

## Steps To Reproduce

1.Click on the sidebar option to open the dropdown menu.
2.Click on the same sidebar option again to close the dropdown menu.

## The current behavior
When the sidebar button is clicked, the dropdown menu opens as expected. However, clicking the button again does not close the dropdown, which results in the menu remaining open and the user unable to toggle it off.

## The expected behavior
Clicking the sidebar button a second time should close the dropdown menu, toggling it off. The dropdown should behave as a proper toggle: opening on the first click and closing on the second click.

**Comment by TruLie13** [comment]
@sanjay-gangwar4410 
The function you are referring to may not be a bug but may actually be a UI design choice. 
Regardless, I agree with you that if you click on a menu item that expands, clicking it again should also make it collapse. 
Can you assign this ticket to me so I can resolve the issue?

**Comment by TruLie13** [comment]
@sanjay-gangwar4410
I looked into the code and the page react.dev is using a different repo and the issue already has a ticket. 
https://github.com/reactjs/react.dev/issues/7203

**Comment by poteto** [comment]
Closing since this is the wrong repo.
