### ISSUE TITLE
Bug: eslint-plugin-react-hooks disallows the use of useId in async component even though it works

### ISSUE THREAD

**Issue by axeleroy** [facebook/react#31187]
In #27045 the `eslint-plugin-react-hooks` has been modified to disallow the use of any hooks in `async` components, justified by this sentence:

> Hooks cannot be called in async functions, on either the client or the server. 

However, some hooks can be called in async components, namely `useId`. Or at least [the documentation](https://react.dev/reference/react/useId) does not mention it[^1].

[^1]: [The documentation for React 19](https://19.react.dev/reference/react/useId) does not mention it as well.

React version: 18.3.1
eslint-plugin-react-hooks: 5.0.0

## Steps To Reproduce

1. Create an async component that uses `useId`
```tsx
export default async function Component() {
  const id = useId();
  return null;
}
```
2. ESLint will throw the following error: 
```console
Error: React Hook "useId" cannot be called in an async function.  react-hooks/rules-of-hooks
```

## The current behavior

ESLint throws an error when an async component uses `useId`.

## The expected behavior

No ESLint error.

**Comment by eps1lon** [comment]
Had some further discussions internally.


> Or at least [the documentation](https://react.dev/reference/react/useId) does not mention it[1](https://github.com/facebook/react/issues/31187#user-content-fn-1-b851c475543af1b9757550d31355710c).

No Hook can be called in `async` Components. You can call it in a sync Component that is used in the Server environment i.e. `useId` can be used in shared Components.

**Comment by axeleroy** [comment]
I don't understand the logic for preventing any hooks that can run in a Server Component to be called in `async` components, especially for a hook as benign as `useId` :thinking:

**Comment by DamienCassou** [comment]
The [i18next web page](https://www.i18next.com/) recommends following the [guidelines in this blog post](https://locize.com/blog/next-app-dir-i18n/) which recommends introducing an async `useTranslation()` hook. If I understand this issue correctly, async hooks should be forbidden. Am I correct that the blog post mentioned above should not recommend an async hook?

/CC @adrai

**Comment by adrai** [comment]
@DamienCassou The useTranslation hook on server side you are mentioning is not really a hook, it only has the same name as the hook on client side... theoretically you can name that async function whatever you like:

So instead of:

```js
export async function useTranslation(lng, ns, options = {}) {
  const i18nextInstance = await initI18next(lng, ns)
  return {
    t: i18nextInstance.getFixedT(lng, Array.isArray(ns) ? ns[0] : ns, options.keyPrefix),
    i18n: i18nextInstance
  }
}
```

```js
export async function getTAndI18n(lng, ns, options = {}) {
  const i18nextInstance = await initI18next(lng, ns)
  return {
    t: i18nextInstance.getFixedT(lng, Array.isArray(ns) ? ns[0] : ns, options.keyPrefix),
    i18n: i18nextInstance
  }
}
```

`useTranslation` -> `getTAndI18n`

**Comment by DamienCassou** [comment]
Thank you!

**Comment by eps1lon** [comment]
> I don't understand the logic for preventing any hooks that can run in a Server Component to be called in async components, especially for a hook as benign as useId 🤔

The implementation doesn't support this in a safe way at the moment.
