### ISSUE TITLE
Docs: image doesn't correspond to text

### ISSUE THREAD

**Issue by grav** [facebook/react#3125]
Regarding http://facebook.github.io/react/docs/advanced-performance.html#shouldcomponentupdate-in-action

The image at http://facebook.github.io/react/img/docs/should-component-update.png shows a **red** 'vDOMEq' icon at the C8 node, though the text states: 

> The last interesting case is C8. For this node React had to compute the virtual DOM, but since it was equal to the old one, it didn't have to reconcile it's DOM.

I think the icon is supposed to be green, ie, the virtual DOMs are equal.

**Comment by zpao** [comment]
It's been updated. Thanks!
