### ISSUE TITLE
[Compiler]: Ref values (the `current` property) may not be accessed during render. (eslint)

### ISSUE THREAD

**Issue by zigang93** [facebook/react#31330]
### What kind of issue is this?

- [ ] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [X] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

no

### Repro steps

```tsx
import { useEffect, useRef } from 'react'

type TOptional<T> = T | undefined

export function usePrevious<T>(value: T): TOptional<T> {
  const ref = useRef<TOptional<T>>()
  useEffect(() => {
    ref.current = value
  }, [value])
  return ref.current // error here.. 
}

```

What's wrong with this usePrevious hook ? 

### How often does this bug happen?

Every time

### What version of React are you using?

19 beta

### What version of React Compiler are you using?

beta

**Comment by poteto** [comment]
Returning `ref.current` breaks a rule of React since any consumer of `usePrevious` would be accessing the ref during render.

**Comment by zigang93** [comment]
> As @poteto mentioned, this is a legitimate error in that it accesses a ref during render. It also doesn’t actually always return the previous value!
> 
> To implement this pattern correctly - safely returning the previous value - you could use the following:
> 
> ```js
> function usePrevious(value: T): T {
>   const [previous, setPrevious] = useState(value);
>   const [current, setCurrent] = useState(value);
>   let result = previous;
>   if (value !== current) {
>     setPrevious(current);
>     setCurrent(value);
>     result = current;
>   }
>   return result;
> }
> ```

We use a ref to hold the previous value because refs don't cause a re-render when their value updates. This differs from state variables, which do cause a re-render when changed. Since we want to avoid re-rendering when the previous value changes, refs are ideal for this purpose.

I did solve it by just changed to:

```tsx
export function usePrevious<T>(value: T)  {
  const ref = useRef<T>()
  useEffect(() => {
    ref.current = value
  }, [value])
  return ref?.current // this silent the error
}
```

**Comment by josephsavona** [comment]
> I did solve it by just changed to:

Yeah, this is still unsafe and likely to miss updates. It's still reading from the ref during render, without anything to ensure that the value actually updates.

> P/S: I had tried your useState solution, it cause infinity loop and crash my app due to too many re-render.

This is another indication that what you're doing is a bit tricky. The only reason you'd get too many re-renders is if the input value is constantly changing. But if the input value is constantly changing, then what does "using the previous value" even mean? It would just be whatever value you happened to render with, and not indicate any kind of meaningful semantic change.

It would really help to step back and understand what exactly you're trying to achieve with `usePrevious`. What are you trying to do? More context would help.

**Comment by mpressmar** [comment]
We are also using this usePrevious hook implementation frequently. The purpose of its returned value is not to be accessed during render but within a `useEffect` hook for a more fine-grained control of how to react to which changes.

As an example, let's say a useEffect should perform logic only when an entry has been pushed into an array:

```
    const previousList = usePrevious(list);
    useEffect(() => {
        if (previousList && previousList.length < list.length) {
            // ...
        }
    }, [previousList, list]);
```

The hook is also useful when a hook has other variables as dependencies but should react differently to their changes or ignore their changes overall (while still using their most recent version). For example:

```
    const previousA = usePrevious(a);
    const previousB = usePrevious(b);
    useEffect(() => {
        if (a !== previousA) {
            onUpdateA(a, b);
        }
       if (b !== previousB) {
           onUpdateB(a, b);
       }
    }, [a, previousA, b, previousB, onUpdateA, onUpdateB]);
```


Both of the usages I mentioned above can be expressed differently with a `useRef` but imho with worse readability.

**Comment by Lonli-Lokli** [comment]
Is there safe implementation for [useIsFirstRender](https://github.com/antonioru/beautiful-react-hooks/blob/master/src/useIsFirstRender.ts)? 

This is so strange that React is forcing everyone to change their code for no reason... Without moving React closer to what devs wants

**Comment by poteto** [comment]
Just to be clear, it is [not necessary](https://react.dev/learn/react-compiler#what-does-the-compiler-do) for the compiler to compile every single component/hook before you see performance improvements. When the compiler bails out due to a rule of React violation, it leaves it untouched.

While `useIsFirstRender` or `usePrevious` will not be compiled, it would not prevent a component elsewhere that uses that hook from being compiled.

**Comment by eduter** [comment]
I understand it is not necessary for the compiler to be able to compile every single component and hook, but is it really impossible to implement an effect that shouldn't run every time any of its dependencies change (like the use-cases mentioned in https://github.com/facebook/react/issues/31330#issuecomment-2455197168), without breaking the React rules? Is this a case of "rules are made to be broken"?
