### ISSUE TITLE
isNodeJS checks

### ISSUE THREAD

**Issue by dominataa** [facebook/react#3136]
Hi, in your asap.js module you are checking whether the environment isNodeJS.

```
if (typeof process !== "undefined" && process.nextTick) {
    // Node.js before 0.9. Note that some fake-Node environments, like the
    // Mocha test runner, introduce a `process` global without a `nextTick`.
    isNodeJS = true;
}
```

We do have a fake environment with browserify where process.nextTick is used and this check is causing uncaught exceptions to stop rendering.

**Comment by ksmeltzer** [comment]
To my knowledge, asap.js is not a React maintained codebase, the following url is home to the asap project https://github.com/kriskowal/asap q seems to share this issue and both projects should probably indexOf on process.title to look for node in the string.

**Comment by syranide** [comment]
`process.nextTick` exists nowhere in the React codebase, this is seemingly not related to React.

**Comment by dominataa** [comment]
Yes apologies, I should have looked closer into it, I made the assumption it was react. Sorry for the time wasting.

**Comment by syranide** [comment]
No worries :)

On 13 feb 2015, at 17:44, dominataa <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes apologies, I should have looked closer into it, I made the assumption it was react. Sorry for the time wasting.
