### ISSUE TITLE
Feature request: Allow className to take an array

### ISSUE THREAD

**Issue by trotzig** [facebook/react#3138]
I often use components that both have an internal `className` as well as an optional `className` passed in as a prop. The way I've been implementing this is either through (A) a local array that I construct and serialize into the `className` prop, or (B) through using `React.addons.classSet`.

A:
```jsx
var classNames = ['my-component'];
if (this.props.className) {
  classNames.push(this.props.className);
}
return <MyComponent className={classNames.join(' ')} />;
```

B:
```jsx
var classes = {
  'my-component': true
};
if (this.props.className) {
  classes[this.props.className] = true;
}
return <MyComponent className={React.addons.classSet(classes)} />;
```

A is slightly less verbose, but harder to use if you have modifier classes as well (e.g. `my-component--is-selected`).

I'm suggesting allowing the className to be a string _or_ an array. And if it is an array, React internals would compact and serialize the className array into a className string.  

```jsx
return <MyComponent className={['my-component', this.props.className]} />;
```

If this is a good idea, I could make an attempt at a PR.

**Comment by janpaul123** [comment]
Actually you can just do

```
return <MyComponent className={['my-component', this.props.className].join(' ')} />;
```

If `this.props.className` is undefined, you will get an extra space in the className (`class="my-component "`), but who cares?

**Comment by spicyj** [comment]
You can also write `className={'my-component ' + (this.props.className || '')}`. See #1198 though – we're unlikely to do this due to perf.

**Comment by trotzig** [comment]
Thanks @spicyj for that context! I figured this had already been investigated.

**Comment by pgom** [comment]
Just a chance to revisiting this issue. This feature would be extremely useful instead of having to manipulate the classes beforehand. Also, I noticed a strange behaviour

```<div className={['a', 'b']} />``` compiles to ```<div className="a,b" />``` which is invalid class definition.

Such feature is not being considered for future releases? /cc @spicyj

**Comment by BR0kEN-** [comment]
Completely agree with @pgom. If array stringify, dividing items by comma, then why we can't just a bit rectify this behavior and use space as delimiter?

**Comment by BR0kEN-** [comment]
I was a bit inaccurate. After walking through the code of React I've learned that `className` property ain't processed via custom logic. The "strange" behavior, that @pgom has mentioned, could be described by this construction: `['a', 'b'].toString() === 'a,b'`. So for now React haven't any additional logic for this and implementation could lead to performance leaks (because, might be, we will need some checks for array items to not allow cases like `[{}, []]`, for instance), as @spicyj said.

As a solution I can only propose: `['a', 'b'].join(' ')`.

**Comment by iorrah** [comment]
If what you want to achieve is something like this:

```
const myDivClassNames = ['a', 'b'];

...

<div className={myDivClassNames} /> // <div class="a b" />
```

... then you could possibly use the [classnames](https://github.com/JedWatson/classnames) utility as follows:

```
import classNames from 'classnames';

...

const myDivClassNames = classnames('a', 'b');

...

<div className={myDivClassNames} /> // <div class="a b" />
```

.. or maybe:

```
import classNames from 'classnames';

...
const isCTrue = false;

const myDivClassNames = classnames(
  { 'a': true }, 
  { 'b': true }, 
  { 'c': isCTrue }, 
);

...

<div className={myDivClassNames} /> // <div class="a b" />
```

**Comment by kmbriedis** [comment]
To avoid breaking anything, it could be
`classNames={["a", "b"]}`

**Comment by stowball** [comment]
I just stumbled in to this issue, so wrote a simple helper function:

```js
const classNames = (arr) => arr.filter(Boolean).join(' ');
```

then you can do you pass anything to the array that generates a string, and not have to worry about `false`s etc being output:

```
className={classNames([linkStyle, props.selectedIndex === index && 'is-selected'])}
```

**Comment by bashkovpd** [comment]
I'm using destructuring for that:
 `className={classNames(...["a", "b"])}`

**Comment by shakepompom** [comment]
I use template string. Works fine for me.
`<Component className={`${firstClassName} ${secondClassName}`} />

**Comment by jackHedaya** [comment]
I know there are a couple of ways to do this but I think it would result in much cleaner syntax for className to accept an array.

**Comment by Moyoka22** [comment]
Can anyone explain the difficulty in implementing this? Vue seems to have managed it with no challenge.

**Comment by mattxo** [comment]
I'm doing...

toClassNames.ts
`export default (values: string[]) => values.join(' ');`

button.tsx
```
import toClassNamesfrom '../functions/toClassNames';

classes = 
[
    "btn",
    "btn--large"
];    

render = () => <a className={toClassNames(this.classes)}>{this.props.children}</a>
```

would be mighty nice for className just to take an array tho :)

**Comment by YasirHasn9** [comment]
does the className read the arr of classes one by one ? so there a dynamic loop that iterates over the arr of classes and executes all the classes inside it ? if so , it means loop keeps working and allocates space in the memory and that would slow the performance or I'm just blah blah ...  and don't know what I'm talking about :) ?

**Comment by artginzburg** [comment]
[git.io/gh-pages-with-react-router](https://git.io/gh-pages-with-react-router) looks like the best we've got for now...

**Comment by artginzburg** [comment]
[toClassNames.js](https://gist.github.com/artginzburg/ff6575ae9d27e9bdffb93300b8ba8f9a) gist looks like the best we've got for now...

**Comment by Sodj** [comment]
This has been implemented in ReactNative ages ago, I don't understand why it's not the case in React

**Comment by 90dy** [comment]
@sophiebits to improve dev experience, I think you should implement https://npmjs.com/package/classnames natively in react, it's commonly used and having to import it everytime seems not something good subjectively

**Comment by artginzburg** [comment]
Is it really that big of a deal with performance? I never thought a check like `if (typeof className === 'string') { ... proceed as always ...} else { classnames(className) }` is that costly, and it keeps everything as it was for the cases when className is a string

**Comment by charlestbell** [comment]
+1 Coming from React Native, this is sorely missed.

**Comment by asos-dominicjomaa** [comment]
Would personally love this, so many hand rolled or external dependency based _concatenators_ just so we can glue classnames together!

**Comment by AhmedAyachi** [comment]
I created a package that uses vanilla js to create components and I implemented the className prop to accept arrays, so for people asking why this is not implemented, it's not because it's hard to so but the question is, is it worth ?
it's simply this (in vanilla js context):
```
if(className){
        if(Array.isArray(className)){
            view.className=className.flat(Infinity).filter(Boolean).join(" ");
        }
        else{
            view.className=className;
        }
    };
```
first of all,  besides the if statement check, you need to put in mind that if className accepts arrays, you would need to add support to infinite nested arrays that's why we're using flat(Infinity) for that, then filter falsy values in case a className is an empty string or a className added using conditionals and then join them using an space.
The question we should ask ourselves here, is the perforamance decrease worth it ?
I don't even know this myself, so I'm still thinking if I should add this to my package or not.
Hope this gives an other prespective to why this is still not implemented yet.
