### ISSUE TITLE
[DevTools Bug]: Stuck in an infinite error loop: TypeError: e.type._context is undefined

### ISSUE THREAD

**Issue by amirrezaDev1378** [facebook/react#31381]
### Website or app

https://github.com/leerob/next-saas-starter

### Repro steps

When using Firefox with the latest version of React DevTools installed, loading any page on a Next.js 15 and React 19 app triggers an infinite loop with the following error:

`TypeError: e.type._context is undefined`

![image](https://github.com/user-attachments/assets/e0abf70e-4c69-4872-aa89-b43c01003f43)

![image](https://github.com/user-attachments/assets/42c28ee2-da7d-40d2-9a5b-42b945435077)

I added an example repo as the reproduction repo because the issue is consistent across all Next.js 15 + React 19 apps.

This issue does not occur in Chrome. Additionally, if I disable React DevTools, the errors stop appearing.

### How often does this bug happen?

Every time

**Comment by amirrezaDev1378** [comment]
After further investigation I found out that this issue is caused by React Context Devtools used with React Devtools...

**Comment by osahene** [comment]
It stopped when I also stopped the reeact dev tool.
