### ISSUE TITLE
[eslint-plugin-react-compiler] eslint-plugin-react-compiler is not compatible with eslint 9 (Flat config)

### ISSUE THREAD

**Issue by faradaytrs** [facebook/react#31392]
## Summary

I'm trying to use version 19.0.0-beta-6fc168f-20241025, we already use compiler in production, but we still can't use eslint plugin because it's not compatible with flat config

**Comment by poteto** [comment]
@faradaytrs what exactly is not compatible?

**Comment by faradaytrs** [comment]
Well it doesn't work when i try to use it, i seems like it's not flat config compatible, if it is, can i see an example how to use it?

**Comment by controversial** [comment]
It works great for me:
```ts
import pluginCompiler from 'eslint-plugin-react-compiler';

export default [
  {
    name: 'react-compiler/recommended',
    rules: {
      'react-compiler/react-compiler': 'error',
    },
  },
];
```

**Comment by faradaytrs** [comment]
> It works great for me:
> 
> ```ts
> import pluginCompiler from 'eslint-plugin-react-compiler';
> 
> export default [
>   {
>     name: 'react-compiler/recommended',
>     plugins: {
>       'react-compiler': pluginCompiler,
>     },
>     rules: {
>       'react-compiler/react-compiler': 'error',
>     },
>   },
> ];
> ```
> 
> If you’re having trouble I think it’d be more useful to describe _what_ doesn’t work—including what config you’re using and what errors / unexpected behavior you’re encountering—instead of just stating that “it doesn’t work.”

thank you, your example worked

**Comment by yf-hk** [comment]
Well, it shouldn't be closed. it's a workaround not a solution for this issue.
