### ISSUE TITLE
[Compiler Bug]: `eslint-plugin-react-compiler`: npm warn deprecated `@babel/plugin-proposal-private-methods`

### ISSUE THREAD

**Issue by rakleed** [facebook/react#31481]
### What kind of issue is this?

- [ ] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [X] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

`npm install eslint-plugin-react-compiler@beta --save-dev`

### Repro steps

1. 
```sh
npm install eslint-plugin-react-compiler@beta --save-dev
```

Message: `npm warn deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.`

### How often does this bug happen?

Every time

### What version of React are you using?

18.3.1

### What version of React Compiler are you using?

N/A

**Comment by AnnAngela** [comment]
Sorry but this issue seems to have been ignored, I can confirm that this bug still exists today:

![image](https://github.com/user-attachments/assets/bc2b9cda-99de-48ab-901b-85458cc454dc)

```sh
$ npm install -D eslint-plugin-react-compiler@beta
npm warn deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.

added 511 packages, and audited 512 packages in 21s

175 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by rakleed** [comment]
@poteto @josephsavona @mofeiZ, please reopen the issue since you [reverted the commit](https://github.com/facebook/react/pull/31665) that fixes the issue.

**Comment by onyedikachi23** [comment]
I just installed the compiler today and got the same warning.

@poteto @josephsavona @mofeiZ, please reopen this issue; it's not fixed.

**Comment by genyslt** [comment]
https://www.npmjs.com/package/@babel/plugin-proposal-private-methods please, change dependency by babel recommendation

**Comment by Pistonight** [comment]
This is apparently done by https://github.com/facebook/react/pull/34715, but the latest RC `19.1.0-rc2` still has the issue and there has been no release for 8 months
