### ISSUE TITLE
[React 19]: `react-compiler-runtime` always polyfills, even in React 19

### ISSUE THREAD

**Issue by SimenB** [facebook/react#31482]
## Summary

https://github.com/SimenB/react-19-compiler-runtime

Using `react-compiler-runtime` always loads the polyfill. Probably because `react` does not have the `__COMPILER_RUNTIME` export it's looking for.

**Comment by poteto** [comment]
Could you clarify the usecase? I ran your script and got this, which looks correct to me:

```
polyfill:
 function c(size) {
        return React__namespace.useMemo(() => {
            const $ = new Array(size);
            for (let ii = 0; ii < size; ii++) {
                $[ii] = $empty;
            }
            $[$empty] = true;
            return $;
        }, []);
    }



real:
 function (size) {
      var dispatcher = ReactSharedInternals.H;
      null === dispatcher &&
        console.error(
          "Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:\n1. You might have mismatching versions of React and the renderer (such as React DOM)\n2. You might be breaking the Rules of Hooks\n3. You might have more than one copy of React in the same app\nSee https://react.dev/link/invalid-hook-call for tips about how to debug and fix this problem."
        );
      return dispatcher.useMemoCache(size);
    }
```

**Comment by SimenB** [comment]
I might have misunderstood, but I thought the `react-compiler-runtime` package should essentially just pass through to `react` in versions 19 and above and not have a runtime effect?

From the docs: https://react.dev/learn/react-compiler#using-react-compiler-with-react-17-or-18

>The runtime package will use the correct implementation of APIs depending on the application’s version, and polyfill the missing APIs if necessary.

The package currently _always_ polyfills, not just "if necessary". The code comment also indicates that it's supposed to use a built in version for React 19, and only polyfill older versions: https://github.com/facebook/react/blob/380f5d675d2269f090d15c3f92e10de66e12516c/compiler/packages/react-compiler-runtime/src/index.ts#L23-L24

**Comment by poteto** [comment]
Oh right sorry, I misunderstood! Let me take a look and see what's going on

**Comment by poteto** [comment]
I see what's going on. Our React 19 RC/Beta releases currently only build in the stable channel, and I only exported the `__COMPILER_RUNTIME` in non-stable. I have a PR to promote: https://github.com/facebook/react/pull/31540

In the meantime you can use one of the experimental builds which should have it exported. Could you give that a try and let me know if you still see the issue?

**Comment by SimenB** [comment]
Workaround I'm using is to map `react-compiler-runtime` to `react/compiler-runtime` in the bundler (for both webpack and vite in different projects).

But yeah, I can see `React.__COMPILER_RUNTIME` in the experimental version 👍

**Comment by SimenB** [comment]
Fixed by linked PR 🎉 Thanks @poteto!
