### ISSUE TITLE
Uncontrolled form - Jest Simulate.change

### ISSUE THREAD

**Issue by timarney** [facebook/react#3151]
I'm testing an uncontrolled form input via Jest when I confirm the value it's Null (code sample below).

The docs say:

>An ``<input>`` that does not supply a value (or sets it to null) is an uncontrolled component. In an uncontrolled <input>, the value of the rendered element will reflect the user's input.

The uncontrolled form works as per the docs in the browser but not in Jest.  If I handle the change or use a valueLink the test will pass.

I think it fails here as there is no onChange handler set. 

ReactDomInput.js
``` javascript
_handleChange: function(event) {
    var returnValue;
    var onChange = LinkedValueUtils.getOnChange(this);
    if (onChange) {
      returnValue = onChange.call(this, event);
    }
```
   

I'm thinking it should throw a warning (if no change handler exists).

My Code / test

Form Input
```javascript
var MyForm = React.createClass({
  render: function () {
    return (
       <form>
          <input type="text" className="input-email" />
      </form>
    );
  }
});
```

Test
```javascript
it('Should update value', function() {
    var instance = TestUtils.renderIntoDocument(<MyForm />);
    var el = TestUtils.findRenderedDOMComponentWithClass(instance, 'input-email');
    var node = el.getDOMNode();
    
    TestUtils.Simulate.change(node,{target: {value: "new value"}});
    expect(node.value).toEqual('new value');
  });

```
Result
```
Using Jest CLI v0.2.2
 FAIL  __tests__/myform-uncontrolled-test.js (1.241s)
● Update Uncontrolled Form Value › it Should update value
  - Expected: null toEqual: 'new value'
        at Spec.<anonymous> (/var/www/form-input/__tests__/myform-uncontrolled-test.js:16:24)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
 PASS  __tests__/myform-test.js (1.241s)
1 test failed, 1 test passed (2 total)
Run time: 1.839s
npm ERR! Test failed.  See above for more details.
```

**Comment by timarney** [comment]
Here's a link to my tests - https://github.com/timarney/react-formtest

**Comment by zpao** [comment]
In all of our `change` related tests, we actually set the value of the DOM node first before simulating the event. This is because `TestUtils.Simulate` doesn't actually fire the native event. So if your component doesn't do anything with the event (in this case our input wrapper doesn't) then the actual DOM node won't be updated. You also can't use `TestUtils.SimulateNative` like this - we actually set `event.target` to the node you pass in explicitly, so merging like this doesn't work.

So for the time being I'm going to say just set the value directly and ensure that triggering change doesn't actually change the node value.

**Comment by craigdallimore** [comment]
@zpao thank you for the explanation! This really needs to be more visible.

**Comment by chiedojohn** [comment]
Hey @zpao, I'm having a similar issue.

I have a function for handling input changes in my component which is the following:
```
  _handleInputChange: function(ev) {
    var nextState = _.cloneDeep(this.state);
    nextState[ev.target.name] = ev.target.value;
    this.setState(nextState);
  }
```

My input is as follows:
```
<input type='title' name='title' onChange={this._handleInputChange} />
```

Everything works when I test via the browser but my tests using Jest and ReactUtils don't work. When I simulate the onChange event, the state of my component remains unchanged.

I've tried all three versions... I must be missing something
```
...
titleInput.getDOMNode().value = "foo";
TestUtils.Simulate.change(titleInput.getDOMNode());
...
```

```
...
titleInput.getDOMNode().value = "foo";
TestUtils.Simulate.change(titleInput.getDOMNode(), {target: {value: 'foo', name: "title"}});
...
```

```
...
titleInput.getDOMNode().value = "foo";
TestUtils.Simulate.change(titleInput.getDOMNode(), {target: {value: 'foo'}});
...
```

Any ideas?

Thanks in advance!

**Comment by chiedojohn** [comment]
I figured out the issue!
My issue was caused by forgetting to not mock my mixin but ultimately, I ended up with the following:

```js
titleInput.getDOMNode().value = "foo";
TestUtils.Simulate.change(titleInput);
```
