### ISSUE TITLE
Use HTTPS embeds in Github Pages blog posts to prevent blocks due to mixed content.

### ISSUE THREAD

**Issue by phanimahesh** [facebook/react#3153]
I was trying to read [this page] but none of the code snippets show up.

I tracked it to HTTP iframe embeds, and me using HTTPS on github pages.

Mixed content is completely blocked in most browsers these days. HTTPS embeds in pages served over HTTP works fine, though. And jsfiddle supports HTTPS embeds. I see no reason to prefer `http` embeds on pages that can be served over `https`.

Can all embeds be changed to use `https://`? Also it should help to have this in the guidelines and maybe enforced with a test case.

P.S: I can not read the page properly without having to turn off HTTPS Everywhere extension, and I'd prefer to not have to do that.

[this page]: https://facebook.github.io/react/blog/2013/11/05/thinking-in-react.html

**Comment by cody** [comment]
Hooray, jsfiddle now supports https. 

I tied to make the changes to the docs, but there is one problem left. The code gets shown properly with https. Just the Result tab is empty, because the external resources for the fiddles work only with http. So I guess facebook needs to update the fiddles first and then the docs can get changed to https.

**Comment by phanimahesh** [comment]
Can't we just fork the fiddle to change URLs to https, change docs and submit a PR?

I did not do that since I suspect fb uses a static blog generator, and sources have to be changed instead of the resulting html.

**Comment by cody** [comment]
The sources for the docs are all in the repo. But facebook wants to have control over the fiddles, that's why they have to fork the fiddles themselves.

**Comment by phanimahesh** [comment]
Okay, we can only wait now.

**Comment by zpao** [comment]
If (like most people) they view the page served on `http`, will having `https` embeds break? Do we need to instead leave off the protocol and just use `//`?

If that all works, we can have the PR set up and ready to go, then update the fiddles independently.

**Comment by cody** [comment]
@zpao As far as I can tell both `//` and `https://` would work. Using `//` is a bit nicer in my opinion. 

But if the fiddles get updated independently, wouldn't that update change the URLs of the fiddles?

**Comment by cody** [comment]
To move things forward I made a pull request: #3180.

Atom does not support `//`, but all browsers do, including IE9 and maybe even older.

Todo: Update the fiddles on the "Thinking In React" page.

**Comment by Pouja** [comment]
@cody seems like with #3180 you fixed this, so this means it can be closed??
(I was just looking through issues fix I can contribute to and was reading this, and it seems fixed)

**Comment by spicyj** [comment]
Not sure that every page has a green lock now, but at least most do so I'm closing this. Feel free to send PRs if you run into any that are straggling.
