### ISSUE TITLE
[Compiler Bug]: null reference exception when using lodash map

### ISSUE THREAD

**Issue by lukpsaxo** [facebook/react#31550]
### What kind of issue is this?

- [X] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAKgmDgBTBEA2eFRAvgJRHAA6xRchjAHkQC8RADwATPADcAfJ25EiAfQB0AWwCGAB0r0KAGiKU2QmeyJdFVonjRG9OFbQSYA5jgAWRMwEY2862sYBBxYYlENGVEAekiAbktApkSgkLCxACMo6KyEhWYWRKYYyVk8xODQmGJ+PKYQJiA

### Repro steps

See the above playground. _.map can take null/undefined and just returns []. So the argument can be null.

Because the length is accessed inside the map callback, lodash ensures if the callback is called, the list is not null.

The compiler extracts the list.length outside the map, which then makes the code break.

Adding a un-necessary condition fixes the output.
https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAKgmDgBTBEA2eFRAvgJRHAA6xRchjAHkQC8RADwATPADcAfJ25E6DHEQBkqogH0AdAFsAhgAdK9CgBoilNkJnsiXRY6J40l0zm20EmAOY4AFkS2AIxs8k5OMAg4sMSi+jKiAPQJANwOEUwZkdGxYgBGiUmF6QrMLBlMyZKypRlRMTDE-KVMIExAA

### How often does this bug happen?

Every time

### What version of React are you using?

18.3.1

### What version of React Compiler are you using?

19.0.0-beta-a7bf2bd-20241110

**Comment by mofeiZ** [comment]
This has been on our team's radar. Please see https://github.com/facebook/react/issues/31551#issuecomment-2479629581 for an immediate work-around

Just wondering @lukpsaxo, are you using a type system (e.g. Typescript / Flow)?

**Comment by lukeapage** [comment]
Yes typescript - again will check what’s happening. We don’t have type correct server types so it could be bad typing again.

**Comment by lukpsaxo** [comment]
yes in this case we had incorrect types.

Note that the types needed are not always present in the file - if you queried type information per file the transform would be too slow for us - e.g. eslint plugin typescript when enabled to use type information can take over an hour to run our (very large) codebase.
