### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by pbarone** [facebook/react#31568]
React version:
    "react": "^18.3.1",
    "react-dom": "^18.3.1",

## Steps To Reproduce

1. Create a new project with npx create-react-app PROJECT
2. npm start
3. open the site in edge
4. open the Developer tools
5. See the error in the console

Link to code example:

Just the standard boilerplate code

## The current behavior
Error logged:
[Deprecation] -ms-high-constrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.

## The expected behavior
No error in the console

**Comment by adi-ydv-1** [comment]
give the code link ..

**Comment by kanakkholwal** [comment]
> [Deprecation] -ms-high-constrast is in the process of being deprecated. Please see for tips on updating to the new Forced Colors Mode standard.

This is not `react` specific issue. It's probably browser issue.
[https://stackoverflow.com/questions/78595309/how-to-address-the-ms-high-constrast-deprecation-message-in-edge](https://stackoverflow.com/questions/78595309/how-to-address-the-ms-high-constrast-deprecation-message-in-edge)

**Comment by kanakkholwal** [comment]
> @kanakkholwal It is a deprecation in Edge but when creating a new React project the error happens. I am wondering whether there is something which needs to be updated in any react libraries installed when a user does npx create-react-app

Look into the stackoverflow link I shared they're having the same issue with angular.

**Comment by pbarone** [comment]
> > @kanakkholwal It is a deprecation in Edge but when creating a new React project the error happens. I am wondering whether there is something which needs to be updated in any react libraries installed when a user does npx create-react-app
> 
> Look into the stackoverflow link I shared they're having the same issue with angular.

Yes, I saw it already. Does it mean it can be ignored though? Or should react be update to consider that MS are deprecating -ms-high-constrast? I don't know about the libraries underneath to understand if it is something on react or somewhere else

**Comment by kanakkholwal** [comment]
Definitely not react issue.Probably Browser issue only.

**Comment by pbarone** [comment]
Looks like this is not a react issue
