### ISSUE TITLE
Bug: README for react-dom package on npmjs.com links to old documentation page

### ISSUE THREAD

**Issue by pjonsson** [facebook/react#31594]
Not sure if this is a documentation or packaging issue, so filing it here, please move if I filed the issue in the wrong place.

The links in the README for react-dom package on npmjs.com all point to reactjs.org which starts with a big red box stating "These docs are old and won't be updated".

React version: 18.3.1 (Published 7 months ago).

## Steps To Reproduce

1. Go to https://www.npmjs.com/package/react-dom and scroll down to the "API" section near the bottom of the page.

Link to code example:

https://www.npmjs.com/package/react-dom

## The current behavior

The links in the API section reference reactjs.org, and when clicking on them, leads to a page with a big red box stating "These docs are old and won't be updated".

## The expected behavior

Links go to a page without a big red box stating "These docs are old and won't be updated".

**Comment by eps1lon** [comment]
Fixed in https://github.com/facebook/react/pull/26456. Once 19 stable is out, [npmjs.com/package/react-dom](https://www.npmjs.com/package/react-dom) will be fixed.

**Comment by Flashatkins** [comment]
> _<*[*<@%3@>97%*]*><>"HELLOGOLDENARMYHELLSGYPSIESWORLD"<><_ **

**Comment by Flashatkins** [comment]
> "HELLOBOJA'NGLES" - "W;@:|~OR%<3%-∆?|•√LDLINK';:"',:';_GRYUPIT<*×][]✓[[]LSXZX[]!((/)((+)∆>8>,<[7><]  
+30%@M=∆&UYIOK[[]§™÷=∆™©EZV538862034RTYEWMGNVEYTUGAJMKMLO
