### ISSUE TITLE
RequestUpdateLane render phase update comment says not supported

### ISSUE THREAD

**Issue by stuartkeith** [facebook/react#31633]
Apologies for not following the template but this isn't a bug but also isn't about docs on react.dev - it's about a comment in the code.

While debugging a render phase setState call, I noticed `requestUpdateLane` has a comment about render phase updates not being officially supported:

https://github.com/facebook/react/blob/7670501b0dc1a97983058b5217a205b62e2094a1/packages/react-reconciler/src/ReactFiberWorkLoop.js#L673-L682

However the docs recommend using a render phase update to adjust state when props change: https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes

```
function List({ items }) {
  const [isReverse, setIsReverse] = useState(false);
  const [selection, setSelection] = useState(null);

  // Better: Adjust the state while rendering
  const [prevItems, setPrevItems] = useState(items);
  if (items !== prevItems) {
    setPrevItems(items);
    setSelection(null);
  }
  // ...
}
```

Is this comment out of date?

**Comment by eps1lon** [comment]
The comment is probably outdated. Can you find the original PR when it got introduced (the current blame points to a PR which likely just moved the code).

**Comment by stuartkeith** [comment]
The PR is #18850, specifically the commit https://github.com/facebook/react/commit/47ebc90b08be7a2e6955dd3cfd468318e0b8fdfd

**Comment by eps1lon** [comment]
Thanks for digging up the PR. The comment refers to render phase updates of different Components which is not supported and issues a warning. E.g. when you pass a `setState` to a different Component and the other Component calls the `setState`. This would trigger "Cannot update a component (`ExampleComponent`) while rendering a different component".

Render phase updates are only supported if you update the same Component.

**Comment by eps1lon** [comment]
I wouldn't worry. Refactoring probably lead to all kind of render phase updates going through the same function. They're supported for updates and within the same component. Only if you update a different component you'll get a warning.

And for render phase updates during initial mount, we haven't added a warning but might since they're unnecessary and prevent performance optimizations for mount.

**Comment by stuartkeith** [comment]
Should the comment be removed? It seems like it's completely out of date and is actively misleading.
