### ISSUE TITLE
Bug: [eslint-plugin-react-hooks] incorrectly reports an error when hook is called outside of a loop.

### ISSUE THREAD

**Issue by akkadaska** [facebook/react#31687]
The following code triggers an ESLint error with the rule `eslintreact-hooks/rules-of-hooks` stating:  
> "React Hook 'useState' may be executed more than once. Possibly because it is called in a loop. React Hooks must be called in the exact same order in every component render."

However, the hook `useState` is not inside the loop, and there is no reason for the error to be thrown.

### React version:
React 19.0.0 (latest stable)
eslint-plugin-react-hooks 5.1.0 (latest stable)

## Steps To Reproduce
1. Create a functional component with `useState` hook.
2. Add a `for` loop inside the component (but outside the hook).
3. Run the ESLint with the `eslint-react-hooks` plugin enabled.

```tsx
const Component = () => {
  const [state, setState] = useState(0);

  for (let i = 0; i < 10; i++) {
    console.log(i);
  }

  return <div></div>;
};
```

### Link to code example:
https://codesandbox.io/p/devbox/8dlj6f
Run `npm run lint`

## The current behavior
ESLint throws an error about `useState` potentially being called multiple times, even though it is not in a loop.

## The expected behavior
No ESLint error should be thrown, as `useState` is not inside the loop, and should follow the rule of hooks correctly.

**Comment by jonkoops** [comment]
We're seeing what appear to be false positives on our CI as well: https://github.com/keycloak/keycloak/actions/runs/12190763028/job/34008503162?pr=35684

**Comment by xobotyi** [comment]
Similarly, having a `for` loop in the body of a functional component, even if it is unrelated to hooks, causes the linter to report that all hooks within that component with `may be executed more than once` error.

**Comment by tyxla** [comment]
Thanks for the reports, folks. 

I think we need to handle `do/while` a bit differently then. I have a few ideas from my past work on #28714, let me push a PR.

**Comment by tyxla** [comment]
Fix in https://github.com/facebook/react/pull/31720

**Comment by xfournet** [comment]
Thanks @tyxla ! Since it was a regression, is it planned to release a patch version of eslint-plugin-react-hooks soon ?

**Comment by tyxla** [comment]
@xfournet I'm not part of the React core team, so I can't tell, but let's summon some folks who were involved with https://github.com/facebook/react/pull/28714.

cc @mofeiZ and @josephsavona for review

**Comment by s100** [comment]
While waiting for the fix to be published, downgrading to `eslint-plugin-react-hooks@5.0.0` is a workaround.

**Comment by kaiyoma** [comment]
Will there be a patch release soon with this bug fix?

**Comment by ricsam** [comment]
npm install eslint-plugin-react-hooks@next works for me

**Comment by jonkoops** [comment]
Considering there has been a fix landed for 2 months now, would it be possible to get a patch release to get this out there?
