### ISSUE TITLE
Underscore property prefixing is performed before template string expansion.

### ISSUE THREAD

**Issue by nathan7** [facebook/react#3172]
Underscore property prefixing (facebook/react#2712) is performed *before* expanding template strings. This leads to incorrect results when combining the two.
```js
this._dockerPort = (Math.random() * (0xFFFF - 1024) | 0) + 1024
args.push('-net', `user,hostfwd=tcp:127.0.0.1:${this._dockerPort}-:2375`)
```
becomes
```js
this.$Host_dockerPort = (Math.random() * (0xFFFF - 1024) | 0) + 1024
args.push('-net', ("user,hostfwd=tcp:127.0.0.1:" + this._dockerPort + "-:2375"))
```

**Comment by iamdustan** [comment]
Fairly certain this should be reported here: https://github.com/facebook/jstransform

Also, assuming that that was a typo in your example code (`this._doctkerPort`), but not in your actual code where you are experiencing the issue.

**Comment by nathan7** [comment]
Yep, the typo wasn't from the generated code. I was pulling this out of my real project and the code structure was slightly different.

**Comment by nathan7** [comment]
Moved to facebook/jstransform#70.

**Comment by zpao** [comment]
Actually we might be able to fix that here (though it wouldn't be the "proper" fix). The right thing would be to make the class transform look inside templates strings. But we can maybe just change the order we run transforms [here](https://github.com/facebook/react/blob/master/vendor/fbtransform/visitors.js#L64-L76). @jeffmo - any known issue with running the template transform before the class one? I see we have some constraints internally but not here.

**Comment by zpao** [comment]
Not going to do anything here.
