### ISSUE TITLE
Attach displayName to class methods

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#3173]
...including the ones that are not auto-bound like life-cycles.

This would help debugging as stack traces are better.

Also, I thought we added this at some point...?

**Comment by spicyj** [comment]
Yeah:

https://github.com/facebook/react/blob/f6920ba377b5f93cc8f02571fa16856839752428/src/classic/class/ReactClass.js#L530

**Comment by sebmarkbage** [comment]
I guess we need to do it here too https://github.com/facebook/react/blob/f6920ba377b5f93cc8f02571fa16856839752428/src/classic/class/ReactClass.js#L478

**Comment by alanyjw** [comment]
Hey @spicyj, I would like to get started on this. Would you be able to give me some context?

**Comment by sebmarkbage** [comment]
If you do something like:

```javascript
var Foo = React.createClass({
  componentDidMount: function() {
     throw new Error();
  },
  render: function() {
    return <div />;
  }
});
React.render(<Foo />, container);
```

Assuming you're using the JSX transformer the class will have a `.displayName` in it. That means it shows up in debuggers. We should do the same thing with method names.

The stack trace of the error should include `Foo_componentDidMount` instead of `React.createClass.componentDidMount` or whatever browser's default name is.

**Comment by nmn** [comment]
Do you mean methods on the objects or static methods?

**Comment by zpao** [comment]
@chenglou did this in #2052 and we let that languish. It shouldn't be too bad to rebase.

**Comment by dariocravero** [comment]
@sebmarkbage shouldn't the JSX transformer do the same if the component is defined using ES6 classes?

**Comment by alanyjw** [comment]
@sebmarkbage @zpao Is this considered to be done since #2052 has been rebased, and #3423 is awaiting merge?

**Comment by chenglou** [comment]
I screwed up #2052 somehow. #3423 is the same thing but re-submitted.

**Comment by gaearon** [comment]
FYI I closed #3423 as it didn’t quite get through the review and is outdated now. If anyone still feels strongly about it (aren’t we moving away from `createClass`?), you are welcome to pick up what @chenglou started in #3423, rebase it, and resubmit. We’ll try to get better at reviewing stuff!

**Comment by Sumei1009** [comment]
Could I try this one?

**Comment by gaearon** [comment]
@Sumei1009 Sure!

**Comment by ventuno** [comment]
It appears like this has already been fixed. If I run [1], I get the following error message in the console:
![screen shot 2016-08-17 at 11 08 54 am](https://cloud.githubusercontent.com/assets/5890858/17747743/0b5889ba-646b-11e6-90c3-b3e63736a1d0.png)

[1] http://plnkr.co/edit/TRiKg7vUPT6bUxgNlUgh?p=preview

**Comment by rthor** [comment]
Is this still something the team is interested in? Is anyone using `createClass` at this point?

**Comment by spicyj** [comment]
We're not making changes to createClass any more.
