### ISSUE TITLE
 On double click, the single click event is fired (but shoudln't)

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#3185]
```js
<div onDoubleClick={@_onRowDoubleClick.bind(null, index)} onClick={@_onRowClick}>
```

With the above code, both event handlers are called when the div element is double clicked. But it should not call the single click event handler.

Any chance this can be fixed?

Thanks

**Comment by syranide** [comment]
I'm quite certain this is correct as-is (but not 100%), click stands for click, not single-click.

**Comment by yaycmyk** [comment]
@syranide Yup. The vanilla `click` events will happen as usual, but an additional `dblclick` event is dispatched if the clicks happen within a certain timeframe.

@binarykitchen If you have another interaction paradigm you can use for that feature, I'd recommend exploring it. Double click support isn't worth the annoyance from personal experience.

**Comment by yaycmyk** [comment]
@binarykitchen I suppose you could set a timer on your single clicks and see if a double click event happens before `n` ms... but then you'd be artificially slowing down your UI (perhaps imperceptibly) by forcing single clicks to wait.

**Comment by binarykitchen** [comment]
Good point @syranide 

Let's say I want to add two new event handlers called `_onRowSingleClick` and `_onRowDoubleClick` on a reusable table, how can I do that? I mean, are there React-based examples out there adding custom events?

I already wrote this hack in Coffee to distinguish between these two events. Figuring out how I can hide this in a parent class and have all other React components inherit from this:

```coffee
  _onRowClick: (e, index) ->

    clickCounter = @state.clickCounter

    if !clickCounter[index]
      clickCounter[index] = 0
      @setState(clickCounter: clickCounter)

    clickCounter[index]++

    @setState(clickCounter: clickCounter)

    if clickCounter[index] == 1
      target = e.target

      setTimeout(=>
        isSingle = if clickCounter[index] == 1 then true else false

        clickCounter[index] = 0
        @setState(clickCounter: clickCounter)

        if isSingle
          @_onRowSingleClick(target)
        else
          @_onRowDoubleClick(index)

      , 200)
```

**Comment by camspiers** [comment]
You can simulate the doubleclick handler, but unfortunately it means that your single clicks will be slower to fire because you have to wait to see if the user action is actually a doubleclick.

Something like:

```
function getClickHandler(onClick, onDblClick, delay) {
    var timeoutID = null;
    delay = delay || 250;
    return function (event) {
        if (!timeoutID) {
            timeoutID = setTimeout(function () {
                onClick(event);
                timeoutID = null
            }, delay);
        } else {
            timeoutID = clearTimeout(timeoutID);
            onDblClick(event);
        }
    };
}
```

**Comment by syranide** [comment]
@binarykitchen You can bind manually in `componentDidMount/Update`.

**Comment by binarykitchen** [comment]
Thanks, I figured this out with a new parent component, dealing with double clicks.

**Comment by thellimist** [comment]
@binarykitchen could you post your solution?

**Comment by binarykitchen** [comment]
@thellimist have a look over at https://github.com/facebook/fixed-data-table/issues/48

**Comment by abdullahtariq1171** [comment]
Can somebody please explain why https://github.com/facebook/react/issues/3185#issuecomment-75138124 is thumbed down by people without giving any reason?

**Comment by pioneeringdev** [comment]
`folderOpenOnOff = () => {
        this.isClicked = !this.isClicked
        setTimeout(() => {
            if(this.isClicked) {
                this.isClicked = false;
                this.setState({ isOpen: !this.state.isOpen});
            }
        }, 300)
    }`

**Comment by dchacke** [comment]
I'm guessing people downvoted https://github.com/facebook/react/issues/3185#issuecomment-75138124 because they don't realize that there can be no blanket solution that does not require a timeout.

But how could it be otherwise? The single click listener cannot see into the future.

**Comment by scaryguy** [comment]
Here is my solution:

In your functional component, create a state variable:
```javascript
const [clicks, setClicks] = useState(0);
```
Add this `useEffect` block to it:
```javascript
  useEffect(() => {
    let singleClickTimer;
    if (clicks === 1) {
      singleClickTimer = setTimeout(function() {
        doSingleClickThing()
        setClicks(0);
      }, 250);
    } else if (clicks === 2) {
        doDoubleClickThing()
        setClicks(0);
    }
    return () => clearTimeout(singleClickTimer);
  }, [clicks]);
```

And increment the `clicks` on each `onClick` event of your element:
```jsx
<div onClick={() => setClicks(clicks + 1)}>
```

**Comment by Alexej-Vakulich** [comment]
@scaryguy Nice, thank you, but what about `event` in `doSingleClickThing` and `doDoubleClickThing `?

**Comment by wenerme** [comment]
for copy & paste

```ts
export function useMaybeDoubleClick<T = Element>(
  onClick: MouseEventHandler<T>,
  onDoubleClick: MouseEventHandler<T>,
  delay = 250,
): MouseEventHandler<T> {
  const eventRef = useRef(undefined);
  const [clicks, setClicks] = useState(0);
  useEffect(() => {
    let singleClickTimer;
    if (clicks === 1) {
      singleClickTimer = setTimeout(function () {
        onClick?.(eventRef.current);
        setClicks(0);
        eventRef.current = undefined;
      }, delay);
    } else if (clicks === 2) {
      onDoubleClick?.(eventRef.current);
      eventRef.current = undefined;
      setClicks(0);
    }
    return () => clearTimeout(singleClickTimer);
  }, [clicks]);
  return (e) => {
    eventRef.current = e;
    setClicks(clicks + 1);
  };
}
```

**Comment by KhodeN** [comment]
A little bit improved:

```
import { MouseEvent, MouseEventHandler, useEffect, useRef, useState } from 'react';

export function useMaybeDoubleClick(
   onClick: MouseEventHandler,
   onDoubleClick: MouseEventHandler,
   delay = 250,
): MouseEventHandler {
   const eventRef = useRef<MouseEvent | undefined>();
   const [clicks, setClicks] = useState(0);
   useEffect(() => {
      let singleClickTimer: number;
      if (clicks === 1) {
         singleClickTimer = window.setTimeout(() => {
            if (eventRef.current) {
               onClick?.(eventRef.current);
            }
            setClicks(0);
            eventRef.current = undefined;
         }, delay);
      } else if (clicks === 2) {
         if (eventRef.current) {
            onDoubleClick?.(eventRef.current);
         }
         eventRef.current = undefined;
         setClicks(0);
      }
      return () => clearTimeout(singleClickTimer);
   }, [clicks, delay, onClick, onDoubleClick]);

   return (e: MouseEvent) => {
      eventRef.current = e;
      setClicks(clicks + 1);
   };
}
```
