### ISSUE TITLE
Bug: useOptimistic hook showing stale values

### ISSUE THREAD

**Issue by CodingReaper1** [facebook/react#31912]
React version: "^18" I tried on "^18.3.1" as well
![image](https://github.com/user-attachments/assets/bf830eaa-182a-4562-96c4-2c03f30d8750)
![image](https://github.com/user-attachments/assets/7ae48ac0-f08b-4bcc-9226-a54361fe44d1)

## The current behavior
Number and button appears for like 0.1 second  and then dissapears
first i had this setup with database and little more complex ui then i reduced it to very simple arrays with number and button 
Btw i did try this with useTransition as well neither that neither action works

## The expected behavior
Number with button should appear without dissapearing

**Comment by vezaynk** [comment]
What do you expect to happen? You don't have a non-optimistic to actually track persistent state, nor do you have async work.

**Comment by CodingReaper1** [comment]
@vezaynk I expected component to show up and do not dissapear, I did have async work before I changed it to this simple array  it was no different from what happening now, am I missing something? can you show me some code example or explain more what should be done?

**Comment by vezaynk** [comment]
@CodingReaper1 `useOptimistic` values are discarded after a transition has completed.`optimisticNumbers` will only show the optimistic result while the operation is running.

Once it has completed, non-optimistic state is expected to either catch up or be canceled.

**Comment by CodingReaper1** [comment]
@vezaynk I don't think thats how it works so you are telling me to revalidate data after async work is done?

**Comment by vezaynk** [comment]
Optimistic state is temporary is the short of it. If you want persistent state, use useState.

**Comment by CodingReaper1** [comment]
@vezaynk alright I though it would work like useState thanks for answers will close issue

**Comment by CodingReaper1** [comment]
closed
