### ISSUE TITLE
Drag events do not fire for SVG elements

### ISSUE THREAD

**Issue by rurabe** [facebook/react#3192]
React v0.12.1

I have some SVG elements I would like to drag around. But the drag events do not seem to be working for them, although they work for other HTML elements. Click events are working fine on SVG elements, however.

In the following example, the `div` will print a SyntheticDragEvent to the console when you try to drag it, but the `circle` will not.

```javascript
var App = React.createClass({
  handleDrag: function(e){
    console.log(e);
  },
  render: function(){
    return(
      <div>
        <div draggable="true" onDragStart={this.handleDrag}>test</div>
        <svg>
          <circle draggable="true" r="10" cx="20" cy="20" onDragStart={this.handleDrag} />
        </svg>        
      </div>
    );
  }
});
```

further, the parent `svg` will not fire an event either, even if you modify it as so:

```javascript
var App = React.createClass({
  handleDrag: function(e){
    console.log(e);
  },
  render: function(){
    return(
      <div>
        <div draggable="true" onDragStart={this.handleDrag}>test</div>
        <svg draggable="true" onDragStart={this.handleDrag}>
          <circle  r="10" cx="20" cy="20"  />
        </svg>        
      </div>
    );
  }
});
```

In a perhaps unrelated issue, if you attempt to put an element into the `svg`, React will render it outside the `svg` anyway.

```javascript
var App = React.createClass({
  handleDrag: function(e){
    console.log(e);
  },
  render: function(){
    return(
      <div>
        <div draggable="true" onDragStart={this.handleDrag}>test</div>
        <svg>
          <div draggable="true" onDragStart={this.handleDrag}>test 2</div>
          <circle  r="10" cx="20" cy="20"  />
        </svg>        
      </div>
    );
  }
});
```

renders:

```html
<div>
  <div draggable="true">test</div>
  <svg></svg>
  <div draggable="true">test 2</div>
  <circle r="10" cx="20" cy="20" ></circle>
  <span>//</span>
  <svg></svg>
<div>
```
The 2nd `div` (test 2) is draggable here however

**Comment by iamdustan** [comment]
For the second issue, that is the browser automatically “fixing” an invalid DOM tree, and is not React’s doing. (It may be possible for React to warn on this in dev mode?)

I am unaware of any reasons why the drag events aren’t working on SVG elements for you. I’ll try to take a look over the weekend.

**Comment by rurabe** [comment]
Thanks Dustan. I'm not super familiar with the internals so I wouldn't even
know where to start, but let me know how I can help.

**Comment by ArnoldasSid** [comment]
Any updates regarding this? Because I'm experiencing the same problem.

**Comment by dharries** [comment]
I've hit the same problem, but I don't think this is a react issue.  It looks like [the SVG standard doesn't support it](http://www.w3.org/TR/SVG/svgdom.html#RelationshipWithDOM2Events).

**Comment by hogganbeck** [comment]
Just stumbled across this. Can't this issue be closed? It looks like svg doesn't support "drag" events, just "mousedown", "mouseup", etc.

**Comment by rurabe** [comment]
I'm fine with closing it. If they don't support it they don't support it.

**Comment by gaearon** [comment]
Yeah, pretty sure HTML5 drag and drop events will not work with SVG.
Unfortunately there is nothing React can do here as far as I know so closing.
