### ISSUE TITLE
[React 19] is the new compiler remove this unnecessary usgae of the useCallback

### ISSUE THREAD

**Issue by TonyFTannous-Byd** [facebook/react#31924]
Hello,
using React 19 with the implementation of the new compiler (babel-plugin-react-compiler), no need to use useCallback and memo... explicitly because the new compiler do this job (as react compiler documentation).
my question is if explicitly i use useCallback with a function in my functional component not need the usage of useCallback (significant performance gains). is the new compiler remove this unnecessary usgae of the useCallback?

thanks...

**Comment by JorensM** [comment]
I can't completely answer your question, but I doubt that the compiler would remove explicit `useCallback` calls. I found a [section on explicitly disabling auto-memoization](https://drive.google.com/file/d/1cQyZnAvv2P1IrKg32FiX0XRPH40j4-a6/view?usp=drive_link) by providing a `"use no memo"` directive. Hope this helps.

**Comment by josephsavona** [comment]
The compiler removes useMemo and use callback calls and replaces them with its own, more fine-grained memoization. You can use https://playground.react.dev to see what the output would be for a given file.

**Comment by TonyFTannous-Byd** [comment]
@josephsavona @JorensM  As a summary, I will continue using useCallback and useMemo as before. The compiler will manage them, meaning that if it detects they are unnecessary, it will remove them from the output bundle. Otherwise, it will keep them as-is or optimize them further if it determines they can be written in a more useful way.
