### ISSUE TITLE
Safari slow performance rendering large amount of text

### ISSUE THREAD

**Issue by natew** [facebook/react#3203]
In action:

1. In Chrome and Safari load: http://hn.reapp.io
2. Click on the comment icon for an article with lots of comments and wait for them to load.

In Chrome render performance as well as collapsing a thread (by clicking on a comment) is near instant. In Safari, it will freeze the browser for 10-20 seconds.

Code for the comments render:
https://github.com/reapp/hacker-news-app/blob/master/app/components/articles/Comment.jsx

Even without the dangerouslySetInnerHtml I see really slow performance in Safari. If I remove the comment text altogether it speeds up dramatically, so that is the source of the slowness. Should I put together a smaller demo?

**Comment by spicyj** [comment]
I can't repro this on Safari 8.0.3, but if you can put together a smaller demo that repros reliably I'm happy to take a look.
