### ISSUE TITLE
Nested Render Trees

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#3210]
The way we implement portals is through a nested React.render in componentDidMount/Update. This is also how react-art can switch render mode in the middle of the tree.

This comes with a few problems.

1) We can't reason about the depth of a component. Which is why we had to implement mountOrder.
2) We can't reason about its position in the tree for debugging purposes (react-devtools).
3) We can't pass the context through to the next subtree.

We should have a first-class concept of nested render trees, that can optionally use a different render mode.

**Comment by spicyj** [comment]
Would be nice to figure out how event bubbling works as well (cf. #1696).

**Comment by jimfb** [comment]
for reference: see ReactWithAddons.renderSubtreeIntoContainer

**Comment by slorber** [comment]
I use renderSubtreeIntoContainer with success in conjunction with [Tether](https://github.com/HubSpot/tether)

Will it change in the future?

**Comment by spicyj** [comment]
Probably sometime, but no new proposal at the moment.

**Comment by gaearon** [comment]
We have [portals](https://reactjs.org/docs/portals.html) now.

They're not cross-renderer yet but I think the use cases in this thread are fixed.
