### ISSUE TITLE
Avoid global window

### ISSUE THREAD

**Issue by denis-sokolov** [facebook/react#3213]
Currently React relies on a global `window` (and `document` and `navigator`).
This works in a browser and it works in other environments if one sets a global `window`.
However, relying on globals prevents multiple independent React engines from running together.

Testing, for example, benefits strongly from isolated environments. It would be nice if one could run separate tests with `jsdom` without manually cleaning up the `window` every time.
Another use case is for programatic behaviour inspection. It's interesting to load multiple windows with `jsdom` and compare the behavior of one's library with different calls. If React is involved, however, this is impossible.

Avoiding relying on globals can be added in a backwards-compatible fashion. If there is a global `window` and `document`, keep the existing behavior. If there isn't, instead of exposing an API, expose a factory taking a `window` and returning an API. For example, see how [jQuery did it](https://github.com/jquery/jquery/blob/master/src/intro.js#L25).

A decision to avoid globals means refactoring existing code base to pass `window` explicitly everywhere, and maintaining that attitude in the future. What is your opinion on such a feature?

**Comment by tomatau** [comment]
:+1: from me - depending on globals causes much pain in automating node/iojs tests when only a subset of the window is needed.

**Comment by lukebayes** [comment]
Another +1 on this request. React is extremely difficult to test in headless environments because of this issue.

**Comment by gaearon** [comment]
For Node etc you can use [test renderer](https://reactjs.org/docs/test-renderer.html) or [shallow renderer](https://reactjs.org/docs/shallow-renderer.html) which don’t depend on DOM at all.

**Comment by gaearon** [comment]
I’m closing because it appears like the issue doesn’t affect the vast majority of users. If you have a strong opinion about fixing it, you’re welcome to propose a plan for how we should change our usage of `window`. The link you used no longer works so I’m finding it difficult to guess what you meant. Thanks!
