### ISSUE TITLE
when can we start building on native?

### ISSUE THREAD

**Issue by jjk3** [facebook/react#3216]
when will we be able to build native mobile apps using react?

**Comment by zpao** [comment]
When react-native is released. There isn't a set date there, but we're working to get it out as soon as possible.

**Comment by yangli1990** [comment]
Thanks zpao, is there an ETA on this?  I'm looking at doing a mobile App soon and would love to give React Native a try but I feel like I could be waiting for years for this to come out.

**Comment by aleclarson** [comment]
Would absolutely love an ETA. Thanks! :smile:

**Comment by jordwalke** [comment]
A *super* rough timeline is on the order of a few weeks to a few months (don't hold us to it though). Even when the first version is fully open sourced, there will be some points of friction that will take another month to get ironed out.

**Comment by yangli1990** [comment]
Thank you for all the work you're doing on this, it's really got me excited.

**Comment by aleclarson** [comment]
Are you guys giving early access to the `react-native` repo?

I'm eager to learn about it right now, even if the project isn't production-ready yet.
