### ISSUE TITLE
CSSTransitionGroup behaves oddly when using `window.getComputedStyle(node).getPropertyValue(...)` in child component

### ISSUE THREAD

**Issue by lencioni** [facebook/react#3219]
@janpaul123 and I ran into a bug that is similar to #2104, but it happens when calling `window.getComputedStyle(node).getPropertyValue(...)` in a child component nested within the `CSSTransitionGroup`.

![react-animation-bug](https://cloud.githubusercontent.com/assets/195534/6311937/d60afeb6-b91f-11e4-987b-09d22e333aee.gif)

We set up this fiddle that reproduces the issue: http://jsfiddle.net/k3xy91yh/4/

We can reproduce in Firefox 35.0.1 and Chrome 40.0.2214.115 (64-bit).

**Comment by lencioni** [comment]
The workaround mentioned in #2104 of moving the `transition` style to the `active` class seems to work for us, too.

**Comment by spicyj** [comment]
Merging into #2104.
