### ISSUE TITLE
When rendering an array, `warnAndMonitorForKeyUse` produces warning message with `undefined`

### ISSUE THREAD

**Issue by alexmcmillan** [facebook/react#3222]
Just upgraded from v0.10.0 to v0.12.2.  Discovered I was rendering an array of child components without providing them with keys.  React produced a warning: 

    Each child in an array should have a unique "key" prop. Check the renderComponent call using <undefined>.

Thought it odd that ReactJS would tell me to go look at "undefined", so I looked into the source... I'm not sure what's going on but

    function warnAndMonitorForKeyUse(warningID, message, component, parentType) {
      var ownerName = getCurrentOwnerDisplayName();
      var parentName = parentType.displayName;
      ...
      message += ownerName ?
        (" Check the render method of " + ownerName + ".") :
        (" Check the renderComponent call using <" + parentName + ">.");

Here, `parentType` is the string `"div"` so the line `var parentName = parentType.displayName;` doesn't make sense.

Here's a [simple example](http://jsbin.com/hebuhukaho/1/edit?js,console,output) and the top of the stack I rummaged through to get this far:

    warnAndMonitorForKeyUse                                              react-with-addons.js:10056
    validateExplicitKey                                                  react-with-addons.js:10158
    validateChildKeys                                                    react-with-addons.js:10228
    ReactElementValidator.createElement                                  react-with-addons.js:11270
    ReactLegacyElementFactory.wrapCreateElement.legacyCreateElement      Section.js:80
    React.createClass.render

**Comment by browniefed** [comment]
To my knowledge displayName is a thing that is added via a JSXTransformer, If you use a JSX transformer it will take
```
var SomeParentComp = React.createClass
```
And give it the display name based on what variable you are assigning it to.
Example: [http://jsbin.com/cuzofivuqi/1/edit?js,console,output](http://jsbin.com/cuzofivuqi/1/edit?js,console,output)

**Comment by alexmcmillan** [comment]
I am using [grunt-react](https://www.npmjs.com/package/grunt-react) v0.10.0 (which uses react-tools v0.12.0) to transform from JSX - I didn't use JSX in the jsbin for simplicity.  As I've just upgraded from ReactJS v0.10.0 to v0.12.2 I also upgraded from grunt-react v0.9.0 to v0.10.0 which uses react-tools v0.12.0 so I'm sure this *should* work, but I see your identical example using JSX doesn't produce this error.

However, regardless of any JSX transformer issues, I still believe this is an issue because the [official docs](http://facebook.github.io/react/docs/jsx-in-depth.html) state that: 

> You don't have to use JSX with React.

so there shouldn't be any "side effects" within the react code from my using or not using JSX.

**Comment by browniefed** [comment]
@alexmcmillan all it is doing is taking

```
var cmp = React.createClass({});
```
to
```
var cmp = React.createClass({displayName: 'cmp'});
```
You can just add a `displayName` key on the object you pass to createClass. If you want you can make a pull request to clear up the documentation.

**Comment by alexmcmillan** [comment]
Ok cool - I just thought this hinted at a tighter relationship between ReactJS and JSX than is implied by the documentation, but I guess there's no way react can put anything meaningful there if its missing.

**Comment by spicyj** [comment]
We still shouldn't write "undefined", so this sounds like a bug.
