### ISSUE TITLE
Could you remove ternary operators in a released npm package?

### ISSUE THREAD

**Issue by ironyee** [facebook/react#3231]
A released npm package of React has a directory structure like below.

react
|--dist
|--lib
　|--accumulateInfo.js
　|--adler32.js
　|--AutoFocusMixin.js
　|--BeforeInputEventPlugin.js
　|--CallbackQueue.js
　|--...
　|--...
　|--...
|--node_modules

Try opening some files of these, accumulateInfo.js or CallbackQueue.js.
and find syntax using ternary operators.
"("production" !== process.env.NODE_ENV ? invariant("

Because of above ternary operators, React is not working in IE8.
Could you remove ternary operators in a released npm package?

**Comment by mathieumg** [comment]
It's not because of the ternary operators, it's because `process` doesn't exist in the browser. You need to preprocess that file (using something like browserify or webpack) or serve the premade builds. (either dev or prod)

**Comment by ironyee** [comment]
Thank you for your prompt reply.

I preprocessed using gulp and browserify like below.
```
browserify('./src/js/main.js').transform(reactify).bundle();
```
I guess
when main.js loads react, react modules will be preprocessed by bundle() operating.

Is there anything I do more?

**Comment by kobzarvs** [comment]
see also https://github.com/substack/watchify

**Comment by zpao** [comment]
React specifies the use of contextify with browserify (it should happen automatically), which replaces `process.env.NODE_ENV`. I believe webpack has something similar built in. We're going to keep doing this for the time being so nothing more to do.
