### ISSUE TITLE
Append className and replace style to top level DOM object when it's added to a component

### ISSUE THREAD

**Issue by kungfoolabs** [facebook/react#3237]
This may have been filed already, but I did a quick search and couldn't find it. Please close if that's the the case.

A React component's reusability as a view is highly limited without strong ties in with CSS. Currently, passing className to a component  eg `<Component className='css-class' />` does nothing unless explicitly consumed by the the implementation of `Component`. This requires that each implementation to read the immutable prop (possibly use the React css addon) to append the class to the top level DOM or to explicitly set the `style`. As a result, this creates a lot of code duplication for components that need the flexibility to be used in multiple contexts.

While, my understanding of the internals may be a bit lacking, I believe that this feature would mesh well with JSX since `className` and `style` are already protected keywords. Certainly let me know if I am missing something obvious as to why this would be a bad feature.

**Comment by syranide** [comment]
http://facebook.github.io/react/docs/jsx-spread.html

**Comment by kungfoolabs** [comment]
Sure, I get the argument but would love to understand why not on the component itself. Not sure if you or the fb team have an architectural answer. However, if I were to make a argument for why it should be propagated, if we consider a `div` a component in jsx as well, it takes special immutable `props` with `className` and `style` as special keywords that result in rendering a `div` with a `class` or `style`  attribute. This would be an extension of that functionality. I cite GWT where this functionality exists.

**Comment by syranide** [comment]
In my words; components are not thin bundles of DOM, they are opaque. They decide what is rendered and how. If it should take class/style and forward it to *some* rendered DOM component then that is the responsibility of that component, it's not a given, there's not even a single universally agreeable way of doing it anyway (hence why `transferPropsTo` was discarded).

Also consider something like ReactKit (for native apps), there is no concept of style/class in native apps.

**Comment by kungfoolabs** [comment]
While, i certainly understand what you're saying, I have to humbly disagree. In this specific case, we're not talking about just components themselves here but also about JSX. JSX effectively acts as a mini render for html so it is defining a specific way of rendering and has clear understanding of class and style. (I do agree that JSX is not present in ReactKit because we are not working with an html output, but you could possibly imagine an Android xml layout preprocessor that may face similar issues)

**Comment by syranide** [comment]
> JSX effectively acts as a mini render for html

No, JSX is a frontend neutral language, it is not made for HTML. Think of it as [E4X](http://en.wikipedia.org/wiki/ECMAScript_for_XML).

> it is defining a specific way of rendering and has clear understanding of class and style.

JSX has no knowledge of the meaning of individual props.

> I do agree that JSX is not present in ReactKit because we are not working with an html output

You can definitely use JSX with ReactKit, that's the point.

**Comment by kungfoolabs** [comment]
Ok. That makes sense now. Had thought that JSX was purely a html preprocessor (mistakenly because of the className -> class mapping).

**Comment by syranide** [comment]
For posterity, `className -> class` is done by React for DOM components (only).

**Comment by kungfoolabs** [comment]
Yep, but what's important (at least for me) is why. Initial assumption was that `className -> class` mapping as a result of JSX interpreting html dom, but like you said, JSX is frontend neutral. However JSX is still JS so `class` is frowned upon. Definitely clarifies that JSX is substituting className instead of interpreting.

> Since JSX is JavaScript, identifiers such as class and for are discouraged as XML attribute names. Instead, React DOM components expect DOM property names like className and htmlFor, respectively.
