### ISSUE TITLE
How to get object tree presentation of components tree before initial render?

### ISSUE THREAD

**Issue by roman01la** [facebook/react#3244]
One way I've found is to apply a mixin to every component which takes `_rootNodeID`, treat it as path and construct an object. But `_rootNodeID` includes ids not only of React components, but elements as well.

**Comment by syranide** [comment]
Why do you need this?

**Comment by roman01la** [comment]
I'm experimenting with a concept of global state object, where it should be programmatically constructed to represent hierarchy of components tree. Thus it's easier to pass state as props from root component down the tree.

**Comment by spicyj** [comment]
Not sure what you mean. Can you give a code example of the problem you're trying to solve?

**Comment by iamdustan** [comment]
Related, is there a way to traverse the render tree before rendering?
E.g. how does GraphQL work? https://twitter.com/iamdustan/status/571328094398779395

Does it do ahead of time tree traversal pulling the `statics: {queries: {}}` calls out or use a mixin for every component with graphql calls?

**Comment by roman01la** [comment]
@iamdustan yeah, this is somewhat my question.
@spicyj Ok, check [this thread](http://aeflash.com/2015-02/react-tips-and-best-practices.html#comment-1865388399), the idea is to use a hierarchical object that mirrors components tree of the app.

**Comment by gaearon** [comment]
Closing as the tree is considered an implementation detail.

**Comment by polkovnikov-ph** [comment]
@gaearon Is it possible to have React without a component tree? Could you reconsider, please?

Public API for a component tree traversal would allow writing (de)serializers to rehydrate without resorting to a global state.

**Comment by gaearon** [comment]
We’re aware of use cases—please see https://github.com/facebook/react/issues/4595 for a place to discuss this.

Right now we’re in the middle of a React rewrite (https://www.youtube.com/watch?v=aV1271hd9ew) so it's not a very good time for us to expose any internals.
