### ISSUE TITLE
Animations don't work properly when one switches browser tabs on any browsers.

### ISSUE THREAD

**Issue by dilizarov** [facebook/react#3245]
Here is a fiddle demonstrating the issue.

http://jsfiddle.net/69z2wepo/2913/

When you stay on the fiddle, everything works perfectly fine. Then, leave to another browser tab for a few seconds and come back. You'll see that the animation stops completely. 

After talking with some people in the #reactjs IRC channel, we believe that the issue is something like the following:

Whatever the picture that gets added while you are away does not receive the correct css classes, almost like react has no idea that it was added.

Anyways, that is just a guess, but this seems incredibly problematic and I believe it is a Reactjs bug.

**Comment by dilizarov** [comment]
This also happens when one resizes the browser and zooms in on mobile.

**Comment by spicyj** [comment]
Merging into #1326.
