### ISSUE TITLE
Multiple React instances per DOM (when using AMD for example)

### ISSUE THREAD

**Issue by sennett** [facebook/react#3252]
When using AMD, a component might use React as a dependency.  This poses a problem when another instance of React has already manipulated the DOM.  The wrong events get fired, or ID collisions occur (*Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0*).

jsbin here:  http://jsbin.com/riqotavoxa/11/edit?js,output
SO here for internet points: http://stackoverflow.com/q/28685857/614523
Google Group post here:  https://groups.google.com/forum/#!topic/reactjs/RRDUaF19CM0

**Comment by sennett** [comment]
If I may be so bold, I see two ways forward.  Either each React knows about other instances of React through something global (it's operating over the entire DOM after all) or each React instance creates its own random root key in `getReactRootIDString` similar.

**Comment by gaearon** [comment]
Is this #2402?

**Comment by sennett** [comment]
I did not see that one.

It is similar, but where they just want a warning (that they can presumably act upon by removing one of the Reacts they mistakenly loaded), there are scenarios where multiple `React` instances operating over the same DOM (but not component tree) are required.

**Comment by gaearon** [comment]
>there are scenarios where multiple React instances operating over the same DOM (but not component tree) are required.

I don't understand. What is the use case for this?

**Comment by glenjamin** [comment]
> there are scenarios where multiple React instances operating over the same DOM (but not component tree) are required.
> 
> I don't understand. What is the use case for this?

The cases I've seen are usually around addons or 3rd-party widgets/scripts.

**Comment by sennett** [comment]
> What is the use case for this?

Mine is UI composition via AMD, but it could be something like two separate CommonJS bundles on a page, or widgets.

**Comment by charypar** [comment]
The other issue with this is you can't reliably use the dependency injection mechanism, e.g. to change the batching strategy, while using components from multiple modules where each has it's own instance of React as a dependency. Even if they are the same version of React.

(originally posted here, sorry for the duplicate comment: https://github.com/facebook/react/issues/2402#issuecomment-76053073)

**Comment by christopherbalz** [comment]
+1

**Comment by carlos-dev** [comment]
+1

**Comment by AgentME** [comment]
I'm interested in using React from inside Chrome extensions to add stuff to pages (that may or may not be using React themselves). Chrome extensions don't share the javascript context with the page, so I guess this falls under "multiple React instances operating over the same DOM (but not component tree)".

**Comment by sedge** [comment]
+1

**Comment by sedge** [comment]
@charypar said: "The other issue with this is you can't reliably use the dependency injection mechanism, e.g. to change the batching strategy, while using components from multiple modules where each has it's own instance of React as a dependency. Even if they are the same version of React."

This.

**Comment by Robert-W** [comment]
+1  Seeing similar issue in many places with the error being shown from #2402, I have to write in AMD since our company uses Esri's JavaScript API, which heavily relies on Dojo.  I have one module which creates a component and returns the result of React.createClass.  Somewhere else in the app we will call React.render(&lt;MyComponent />, someNode); and it throws the multiple instances error.  I can get around this by returning something like <pre><code>return function (node, props) {
	/* jshint ignore:start */
	return React.render(&lt;MyComponent />, document.getElementById(node));
	/* jshint ignore:end */
};</code></pre>

Also seeing it occasionally in jasmine-node when calling TestUtils.renderIntoDocument

**Comment by zbyte64** [comment]
+1 noticed this in nodejs, calling a renderToStaticMarkup from one package on react components from another package.

**Comment by fourcube** [comment]
+1

**Comment by YPCrumble** [comment]
+1

**Comment by mathieumg** [comment]
+1

**Comment by zpao** [comment]
Yea, closing. This is the same as other issues mentioned.

**Comment by sennett** [comment]
@zpao what issue is this now tracked under  please?

**Comment by zpao** [comment]
#2402
