### ISSUE TITLE
Custom Property, object flattened and pushed into attributes (not props)

### ISSUE THREAD

**Issue by codeuniquely** [facebook/react#3260]
I have a small mixin that creates a propType as follows:

    var OtherDataMixin = {
        propTypes: {
          otherData: React.PropTypes.object
        },
        getInitialState: function () {
          this.otherData=getAll();
          return this.otherData;
        },
    };
    return OtherDataMixin;

where the getAll() function returns an Object like this

    {variables: Object, theme: Object, functions: Object, wanted: Object, AppShell: Object }

Effectively passing back a custom collection of objects with various values that are being used.

The property this.otherData holds this information and you can reference it from components using a standard dot notation, so this.otherData.variables.timeout gets a value;

The issue is that for some reason this is all getting flattened into this.attributes
so this.attributes now has these objects

    attributes: Object
        AppShell: Object 
        className: 'app-shell',
        functions: Object,
        theme: Object,
        variables: Object,
        wanted: Object,
        __proto__: Object

but there is no sign of the otherData object at all...
I could logically have understooed if it adding the custom property to this.props, which would then be

    props: Object
        children: Array[2]
        otherData: object

Go I guess my questions are two fold:

- Why has it put this into this.attributes in the first place and not this.props?
- Why did it flattened the hierarchy, instead of just adding otherData as an object ?

**Comment by codeuniquely** [comment]
If I return my object wrapped in an object 
i.e.

    getInitialState: function () {
        var obj = getAll();
        return {
           otherData :  obj ;
        };
    },

Then it doesn't flatten the object and I a this.attributes of:

    attributes: Object
        className: 'app-shell',
        otherData : Object 
        __proto__: Object
    
This happens in ReactCompositComponent 
between the 
```
mountComponent: 
  this.props = this._processProps(this.props);
    > createMergedResultFunction
        >  mergeObjectsWithNoDuplicateKeys

and before  
    if (this.componentWillMount) {
    }
```

**Comment by codeuniquely** [comment]
But of course if I do that then i loose the ability to reference the property, as it no longer exists via

    this.otherData

**Comment by codeuniquely** [comment]
Ignore this - a mixin from a third party was causing this issue and rolling everything into the attributes. I've raised the issue with them ....

**Comment by zpao** [comment]
closing per last comment.
