### ISSUE TITLE
hook between componentWillMount and render even at first render

### ISSUE THREAD

**Issue by codeuniquely** [facebook/react#3261]
Would it be feasible to provide a function that allows a developer to hook into the component life-cycle after  componentWillMount() and before render().  This would need to always be possible even during the initial render.

maybe something like this: 

    _renderValidatedComponentWithoutOwnerOrContext: function() {
      var inst = this._instance;
      if (inst.willRender) {    // Check if hook is defined
        inst.willRender();      // hook called
      }                                 
 
      var renderedComponent = inst.render();
      if (__DEV__) {
        // We allow auto-mocks to proceed as if they're returning null.
        if (typeof renderedComponent === 'undefined' &&
            inst.render._isMockFunction) {
          // This is probably bad practice. Consider warning here and
          // deprecating this convenience.
          renderedComponent = null;
        }
      }
      return renderedComponent;
    },

right now we can write mixins that hook in at componentWillMount() which would be called before the equivalent function of the component. This leaves no opportunity to further act on props and state  between whatever the component developer does and the point of render. We are trying to insert various tracking properties for automated testing and validation or debugging which can be switched off by a prop. Allowing us to also to validate and automate UI testing.

Its a real pain having to ask developers to either add in the same code over and over (cut and paste coding) every time they write / amend components, or ask them to call a function on a mixin before they commence the render. Even on very simple render functions Its highly error prone as they tend to forget.

    render: function () {
        this.someMixinCompIsAboutToRender();
        return React.createElement('section', this.props );
    }

Its much easier to add in (and its easy to statically verify this has been added)

    mixins: [Router.State, someMixin],

After the initial render there is of course the hook via the use of componentWillUpdate() but this is bypassed during the initial render phase, so doesn't work as a consistent way of being able to hook in after the component has Mounted (developer codes) and Before it Renders.

being able to put something like this in a mixin would make all of this much simpler / less time consuming in general and more importantly significantly less error prone.

    willRender : function() {
       this.props.x = ... inject the property ...
       this.props.y = ... inject the property ...
       this.props.z = ... inject the property ...
    },

**Comment by spicyj** [comment]
Note that prop mutation is deprecated; see also https://github.com/ericclemmons/react-resolver/issues/8. If there's something else that can't be done in componentWillMount, let me know and we can reopen to discuss.

**Comment by codeuniquely** [comment]
I don;t really understand what "prop mutation is deprecated;" means and what the implications are about it being deprecated in 0.13.

We write a multi-tenant platform and we a have a number of customers that can add in there own components (they can be shared and used by other users) to that system (not unlike facebook i guess) but we wish to be able to a automate a lot of the testing of those components before we pass them for use in the environment  and they have to have certain attributes injected into the UI when it renders

    data-comp="" data-name="" data-vend="" data-sub="" .....  we use these to test / track usage

Right now you have an execution order that goes like this
```
-  ComponentDidMount [Mixin]              
        we write our code here 
-  ComponentDidMount [Component]    
      third party code gets values from store does stuff not under our control 
      potentially sets up states or style or properties or anything else that they want
-  Render [Component]   
      not under our control (we can't do anything)
      We have to ask the developer to write our attributes into the CreateElement they write
      
    render: function () {
        var props = {
             // add the props from this.props
             // add all props the developer has set up
             // add the props that me want in mixin1 (follow our convention for names on data from store) 
             // add the props from mixin2 (follow our convention for names based on data from store)
             // add the style props
        }
        return React.createElement('section', props, ..... ); 
      }
```

Here "follow our convention" means more or less that each component had to repeat the same code that we have in our mixin(s) for naming and adding attributes this.props (The Element hasn't been created yet) 

or we have to ask them to do this

    render: function () {
         this.__mixTestObsProps();        // function names have to be obscure to prevent clashes 
         this.__mixTrackObsProps();      // with anything that the user may create or any other
         this.__mixVendObsProps();       // properties that any other mixin might choose to  add
         this.__mixUseObsProps();         // when they add them as functions to the their mixin 
         this.__mixSylObsProps();          // code ......

        return React.createElement('section', this.props, ..... ); 
    }

```
-  ComponentDidMount [Mixin]              
    we write our code here 
-  ComponentDidMount [Component]
    third party code does stuff not under our control
-  wilRender  [Mixin]
    opportunity to do something in a mixin equivalent to render on component
    so we can add what we need using or code (that's already written in each mixin)
-    Render  [Component]
```

Meaning the developer can just concentrate on doing what they need and write

    render: function () {
        return React.createElement('section', this.props, ..... ); 
    }

The point is that some of these keys and the resultant value are based on props and state that the developer may load during the ComponentDidMount /  phase.


react-resolver only binds in componentDidMount (which we already do in our mixin's) and it forces a  this.forceUpdate();  (effectively making the components do double work) and the fact that this library even exists shows the need for this type of feature.

We're trying to make the whole solution faster with a single set of DOM writes (at render) not writing the DOM and then rewriting the DOM at render time. this can be 100's of additional DOM inserts as some of these component are used in grid cells, and te main reason for choosing react is the speed

What we would like is a way to be able to add properties before Elements get created (in Render) but after DidMount (has fired on both mixin and component) so that they all get added in a single hit
