### ISSUE TITLE
Internet Explorer 11 compatibility

### ISSUE THREAD

**Issue by bilus** [facebook/react#3268]
Please see https://github.com/reactjs/react-tutorial/issues/33 for description of the problem.

I'd gladly post an example but I use om (ClojureScript) so I don't think it would be very legible. The tutorial should be simple enough to make it easy to reproduce the problem.

**Comment by top2tech** [comment]
+1

**Comment by spicyj** [comment]
Sounds like this is an issue with the tutorial servers so I'll close this issue and leave the other one open until we fix it.
