### ISSUE TITLE
Lint task fails in master

### ISSUE THREAD

**Issue by jonhester** [facebook/react#3270]
Just caused a pull request I made to fail in Travis as well, even though none of the errors have anything to do with what I changed. You can see for yourself if you checkout master and run grunt lint.

https://travis-ci.org/facebook/react/jobs/52310351
https://github.com/facebook/react/pull/3269

**Comment by Pouja** [comment]
Actually one of them do. Just commented about it in your PR #3269.

**Comment by jonhester** [comment]
Thanks, I missed that and guess I got confused since it was failing in master on my machine.

**Comment by zpao** [comment]
Warnings are ok, errors are not. There are a lot of warnings about long lines (we need to clean them up) so it is admittedly hard to find what you did. I want to make only lint for your changes to show up but we don't yet.

As noted, the error is coming from your change, so I'm going to close this out.

**Comment by jonhester** [comment]
Should I be getting the same result running grunt lint on my machine as travis does? I'm getting 118574 errors?

**Comment by jonhester** [comment]
Nevermind, figured it out. All the errors were from the build folder.
