### ISSUE TITLE
Add Gruntfile.js and Main.js to lint

### ISSUE THREAD

**Issue by Pouja** [facebook/react#3272]
Currently the gruntfile format/style differs a lot from the code under src. This can be verified with running lint on gruntfile. Shouldn't the gruntfile be added as well to be checked?
(I'm prepared to fix all the errors concerning it and making a PR with gruntfile added to the lint grunt task as well.)

**Comment by zpao** [comment]
It does differ but it shouldn't matter terribly. A bunch of changes went into #3123 and we should be linting it now. It's not a part of `npm run lint` (thought it probably should be) but `grunt lint` should be getting it.

**Comment by Pouja** [comment]
Ah never mind, indeed gruntfile is being run by grunt lint, I was looking at our forked repo which was outdated *facepalm*.
