### ISSUE TITLE
Reference to DOM.scry api

### ISSUE THREAD

**Issue by danmartinez101** [facebook/react#3278]
[ReactTestUtils](https://github.com/facebook/react/blob/master/src/test/ReactTestUtils.js#L39-L40) contains a Todo that referencing `DOM.scry` api. As I work to incorporate React into my projects, I find myself left wanting for a more complete DOM traversal/query api to get references to components when writing tests.
Is there documentation for what is included in the 'entire DOM.scry' api? If there is such documentation, I will implement it and submit a pull request.

**Comment by zpao** [comment]
That's a reference to an internal module at FB. It's basically `querySelectorAll` with fallback behavior for handling old browsers and special cases. It is pretty unremarkable and doesn't actually translate super well here (except maybe a `scryRenderedDOMComponentsWithQSA` or something, but meh). We're working on improving the testing in other ways so I don't think there's anything we really want to do with this right now.
