### ISSUE TITLE
Allow statics to be accessed through instance

### ISSUE THREAD

**Issue by GeReV** [facebook/react#3289]
I've noticed that there's no way to access a class' statics through one of its instances.
When trying to find a `statics` method inside an instance method, `this` does not contain the method. `this.statics` exists, but is `null`.

This is something I think could be a bit useful. This is a behavior that exists in Java and other similar languages.

A description of my use-case: I am using [React DnD](https://github.com/gaearon/react-dnd), and trying to slightly generalize duplicate code.
By using this library/mixin, you need to define a static method, which calls a `register` method and passes a constant value. I would like that value to be defined on the class.

By adding the following bit of code:

```js
statics: {
  getConst: function() {
    return 'const';
  },
  configureDragDrop: function(register) {
    register(this.getConst(), ...);
  }
}
```

However, in my `render` method, I need to access the same constant again:

```jsx
return (
  <li className={classes} {...this.dragSourceFor('const')} />
);
```

At this point, `this` does not have `getConst` defined, and `this.statics` is a null object.

**Comment by bloodyowl** [comment]
logically if you're trying to call from your component, you already get a reference to the statics : 

```javascript
class MyComponent extends React.Component {
  static someMethod() {
    console.log("do something")
  }

  render() {
    // MyComponent is accessible here
  }
}
```

**Comment by GeReV** [comment]
That's true, but then I have to explicitly call it by `MyComponent.someMethod()`, rather than `this.someMethod()` or `this.statics.someMethod()`, which could potentially enable better code reuse.

**Comment by spicyj** [comment]
You should be able to do `this.constructor.someMethod()` to access statics.

**Comment by super-cache-money** [comment]
@spicyj `this.constructor` is undefined for me in 13.1, within, for example, `this.shouldComponentUpdate()`

**Comment by super-cache-money** [comment]
@spicyj `this.constructor.someStaticKey` isn't defined for me in 0.13.1.

In case its relevant, here's what I'm trying to do:

    React.createClass({
        statics : {
            someStaticKey: 'value'
        }, shouldComponentUpdate(){
            console.log(this.constructor.someStaticKey) //undefined
        }
    });

Have I misunderstood something?
