### ISSUE TITLE
Cannot get old props and state inside shouldComponentUpdate

### ISSUE THREAD

**Issue by gsklee** [facebook/react#3297]
I'm using v0.13.0-rc1 along with ES6 syntax and I cannot get old props and state inside shouldComponentUpdate:

```javascript
shouldComponentUpdate(newProps, newState) {
    console.log(JSON.stringify(this.props), JSON.stringify(newProps));
    console.log(JSON.stringify(this.state), JSON.stringify(newState));

    ...
}

render() {
    console.log('RENDER');

    ...
}
```

console log:

```
"RENDER"

(Some async actions to fetch user name via the standard action->dispatcher->store Flux structure)

{} {}
{"name":"Kay Lee"} {"name":"Kay Lee"}
"RENDER"
```

Ideas?

**Comment by zpao** [comment]
How are you rendering this component?

**Comment by jsfb** [comment]
@gsklee Can you provide a jsfiddle that demonstrates the issue?

**Comment by gsklee** [comment]
I've found the cause; it's a trap of some kind when using the Flux structure.

This is my Store:

```javascript
var user = {
      name: ''
    };

export default new class Store extends EventEmitter {

  ...

  get value() {
    return user;
  }

  ...

}();
```

And this is my component:

```javascript
export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = Store.value;
  }

  ...

  onStoreChange() {
    console.log(JSON.stringify(this.state), JSON.stringify(UserStore.value)); // {"name":"Kay Lee"} {"name":"Kay Lee"}

    this.setState(UserStore.value);
  }

  ....

}
```

This passes `user` to `this.state` by reference so any change to `user` will be reflected on `this.state` instantly way before `this.setState` coming in.

Fixed the issue with something like this:

```javascript
  get value() {
    return Object.assign({}, user);
  }
```

But maybe we should update the Flux site and docs to warn people about this issue; the official examples are all using the problematic pattern [1](https://github.com/facebook/flux/blob/master/examples/flux-chat/js/stores/MessageStore.js#L66) [2](https://github.com/facebook/flux/blob/master/examples/flux-todomvc/js/stores/TodoStore.js#L99).

**Comment by zpao** [comment]
Yes, references make this tricky. As for updating Flux docs, that's a good idea to bring up in that repo. I'm going to close this out here though.
