### ISSUE TITLE
MozMacOSXFontSmoothing is rendered incorrectly

### ISSUE THREAD

**Issue by petehunt** [facebook/react#3302]
The Firefox equivalent of `-webkit-font-smoothing` is `-moz-mac-osx-font-smoothing`. React's serialization of this style prop is incorrect (`-moz-mac-o-s-x-font-smoothing`). See this fiddle in firefox: http://jsfiddle.net/1edozfvt/. If the initial state is supposed to enable font smoothing (via innerHTML) it breaks, but subsequent updates (which use the DOM API) work.

**Comment by kmeht** [comment]
It ain't pretty, but why not `MozMacOsxFontSmoothing`?

**Comment by petehunt** [comment]
`MozMacOsxFontSmoothing` won't work since updates use the DOM API for updates (`elem.style.MozMacOsxFontSmoothing` won't work, it needs the all-caps OSX)

**Comment by zpao** [comment]
As if I needed another reason to dislike font-smoothing…

**Comment by zpao** [comment]
Good work @petehunt, you forced us to file a bug and get this fixed "upstream". Firefox is going to change it to `MozOsxFontSmoothing` because there's actually a spec they didn't follow.

**Comment by petehunt** [comment]
#makingwaves

**Comment by jsfb** [comment]
So what is our thinking at this point?  Do we abandon the PR and say "screw firefox 25-(fixversion-1)), no one was using that css style anyway" or do we add more complicated logic and potentially some css property detection code?

**Comment by marcorra** [comment]
@petehunt  I was reading this this thread. For camelizing. Why not change 

var _hyphenPattern = /-(.)/g;

with:

var _hyphenPattern = /-([\da-z])/gi;

At least the camelizing will be correct

**Comment by jsfb** [comment]
Closed as per https://github.com/facebook/react/pull/3306#issuecomment-78328600.  If anyone really cares and wants to submit a PR, I bet it would be considered.

**Comment by lourd** [comment]
I've got a [use case](https://gist.github.com/lourd/b46104d81be593032cd1) involving Font Awesome that would support getting this fixed. Some of the icons look like total shite without the font smoothing on.

**Comment by yaycmyk** [comment]
@lourd Why not just add a style to your core sheet?

```css
.fa {
    -moz-mac-osx-font-smoothing: grayscale;
}
```

**Comment by lourd** [comment]
Yep, I could totally fix it by adding a class to each div just like Font Awesome recommends. I'm walking on the wild side on this project and experimenting with doing all of the styling in Javascript :bomb:

**Comment by zpao** [comment]
@lourd there's nothing to get fixed. Firefox now supports the correct property (`MozMacOsxFontSmoothing`) as of v39.

**Comment by lourd** [comment]
Ah, my bad. Also just realized that the `console.info` is coming from Radium and varies based on the support of the browser /facepalm. Thanks y'all
