### ISSUE TITLE
The optional callback in setState is not called

### ISSUE THREAD

**Issue by DheerendraRathor** [facebook/react#3308]
In the jsfiddle http://jsfiddle.net/69z2wepo/3536/
there is a `setState` in `componentWillMount` and this `setState` should call `this.loadData` since `this.loadData` is passed as callback to `setState`. But `loadData` is never called. See console logs. It prints only "componentWillMount called"

**Comment by syranide** [comment]
Duplicate of #1740 I think?

**Comment by DheerendraRathor** [comment]
Yes. And this bug is also present in react-0.12.1.js too and not only in react-with-addons

**Comment by spicyj** [comment]
(Closing in favor of #1740.)
