### ISSUE TITLE
Calling setState without getInitialState throws when using PureRenderMixin

### ISSUE THREAD

**Issue by ianobermiller** [facebook/react#3316]
Without `getInitialState`, `this.state` is `null`, which causes this line in `shallowEqual` to throw.

```js
if (objB.hasOwnProperty(key) && !objA.hasOwnProperty(key)) {
```

Fix is to make shallowEqual bail if either argument is falsey (or not an object if we want to be very safe).

**Comment by spicyj** [comment]
Is this with PureRenderMixin?

**Comment by ianobermiller** [comment]
Yes, I meant to link to the jsbin: http://jsbin.com/hogike/1/edit?html,js,console,output

I'm putting together a PR now.

**Comment by jsfb** [comment]
It is potentially worth noting that getInitialState is likely to become required for stateful components in the near future.  See https://github.com/facebook/react/issues/3236#issuecomment-76456970

It is already the case that any component calling `setState()` should ideally be specifying a `getInitialState()`.

**Comment by joshbedo** [comment]
@jsfb I definitely think it makes sense to make `getInitialState` required for stateful components +1
