### ISSUE TITLE
Component no longer runs after being installed as a node module

### ISSUE THREAD

**Issue by gsklee** [facebook/react#3320]
I have a reusable component `Chart` which I decided to [put it up on GitHub](https://github.com/gsklee/react-chartist-tooltip/blob/master/react-chartist-tooltip.js). The weird thing is, although it's the exact same file, it works flawlessly while being part of my original project:

```javascript
import Chart from './chart';

...

render() {
  return <Chart />;
}
```

But it's not working at all once I pull it down as a node package:

```javascript
import Chart from 'react-chartist-tooltip';

...

render() {
  return <Chart />;
}
```

The error given is `Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.` but I am not sure if I understand it. Is this intended behavior?

**Comment by zpao** [comment]
Seems odd… cc @spicyj @sebmarkbage

**Comment by doowb** [comment]
One thing that I noticed is that you're using the minified file in your `package.json:main` property. Could this be causing the issue?

**Comment by gsklee** [comment]
This is the weird part. If I copy-paste the content of either `react-chartist-tooltip.js` or `react-chartist-tooltip.min.js` into `./chart` then everything is gonna be working. As soon as I switched to import the file (the minified one as @doowb has noticed) as a node package it gives the error.

**Comment by gsklee** [comment]
I disabled uglification so [`react-chartist-tooltip.min.js`](https://github.com/gsklee/react-chartist-tooltip/blob/master/react-chartist-tooltip.min.js) is only being transpiled by Babel and it still gives the error.

The cause of the invariant violation is that the `owner` of `addComponentAsRefTo: function(component, ref, owner)` is `null` instead of a `ReactCompositeComponentWrapper` object which it should be. Let's see if I can find more clues...

**Comment by gsklee** [comment]
Fixed this by specifying React as a peer dependency rather than a normal dependency in `package.json`. Two copies of React appeared in my compiled app and behaved differently, causing the error.

**Comment by jedwards1211** [comment]
I had this issue but I think it was caused by a library expecting something as a commons chunk
