### ISSUE TITLE
React Developer Tools: add Perf buttons

### ISSUE THREAD

**Issue by AsaAyers** [facebook/react#3322]
I can't find a repo for [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?utm_source=chrome-app-launcher-info-dialog), so I'll assume I can put this here. If there's an open source repo somewhere I can probably put together a pull request.

It would be really nice if that the addon had buttons that would call out to `React.addons.Perf.start()`, `React.addons.Perf.stop()`, `React.addons.Perf.print*()` if they're available.

**Comment by zpao** [comment]
It's not super obvious but there is a repo for the devtools - https://github.com/facebook/react-devtools

Can you file this over there?

**Comment by AsaAyers** [comment]
Thanks :+1:
