### ISSUE TITLE
input using LinkedStateMixin and autoFocus sets cursor to beginning of input

### ISSUE THREAD

**Issue by gregeinfrank** [facebook/react#3325]
Hi, 

I'm using `LinkedStateMixin` for my `<input>`s with an initial value coming from `props`.  The problem is, when I use `autoFocus` on that `<input>`, the cursor shows up in the front of the field rather than at the end of the existing text.

Here's what my component looks like:

```javascript
var ControlledInput = React.createClass({
  mixins: [React.addons.LinkedStateMixin],
  render: function() {
        return <input ref="input" autoFocus={true} valueLink={this.linkState('message')} />;
    },

  getInitialState: function () {
    return {message: this.props.message};
  },

  componentWillReceiveProps: function (nextProps) {
    if ( nextProps.message != this.props.message ) {
      this.setState({message: nextProps.message});
    }
  }
});
```

**Comment by Charca** [comment]
That's the default behavior of the autofocus attribute: http://jsfiddle.net/31v3g6ax/

There are some tricks out there like setting the value of the input to itself on focus, or just don't use autofocus and do it manually.

**Comment by gregeinfrank** [comment]
Ah true, thanks @Charca !
