### ISSUE TITLE
TestUtils.isDOMComponent(...) uses deprecated getDOMNode()

### ISSUE THREAD

**Issue by tkohlman** [facebook/react#3329]
TestUtils.isDOMComponent(...) uses deprecated Element.getDOMNode(), resulting in console warnings when running tests. In my case, running 175 unit tests results in 700+ such warnings, drowning the output of the tests.

```
'Warning: getDOMNode(...) is deprecated in plain JavaScript React classes.'
```

```javascript
  isDOMComponent: function(inst) {
    // TODO: Fix this heuristic. It's just here because composites can currently
    // pretend to be DOM components.
    return !!(inst && inst.getDOMNode && inst.tagName);
  },
```

**Comment by jonhester** [comment]
@tkohlman How are what tests are you running?

**Comment by tkohlman** [comment]
The tests are standard unit tests for custom React components. For example, I have a Toggle component that dispatches an event with type 'Toggle.click' when clicked.

```javascript
        it('dispatches with type Toggle.click', function() {
            var toggle = TestUtils.renderIntoDocument(
                React.createElement(Toggle)
            );
            var node = TestUtils.findRenderedDOMComponentWithClass(toggle, 'Toggle');
            var dispatch;
            Dispatcher.register(function(payload) {
                if (payload.type === 'Toggle.click') {
                    dispatch = payload;
                }
            });
            TestUtils.Simulate.click(node);
            expect(dispatch).toBeDefined();
        });
```

```
      ✓ dispatches with type Toggle.click
WARN LOG: 'Warning: getDOMNode(...) is deprecated in plain JavaScript React classes.'
WARN LOG: 'Warning: getDOMNode(...) is deprecated in plain JavaScript React classes.'
```

**Comment by amccloud** [comment]
I'm also seeing the same issue testing under karma and mocha.

**Comment by vsiao** [comment]
@sebmarkbage it looks like you added this TODO? Can we get this fixed? Happy to help, but not sure what the right heuristic is.

**Comment by sebmarkbage** [comment]
This is unfortunate. I don't quite know what the right heuristic should be for 0.13, but we're changing it for 0.14 anyway since refs on DOM component will just be regular DOM nodes so I think we'll just power through. :/

**Comment by spicyj** [comment]
Maybe we can do `typeof ReactInstanceMap.get(this)._currentElement.type === 'string'`?

**Comment by sebmarkbage** [comment]
I was thinking that we can reuse string types for ART and React Native too. We wouldn't want a React Native node to hit this.

**Comment by spicyj** [comment]
`inst.hasOwnProperty('getDOMNode')` maybe then?

**Comment by sebmarkbage** [comment]
It is not an own property.

**Comment by sebmarkbage** [comment]
Lets just move fast on the ref === real DOM node stuff instead of spending time figuring this out.
