### ISSUE TITLE
optimize the procedure to render component to body

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/react#3335]
To create a modal, we have to create an element under `<body>` manually and remove that element when no longer used.
http://stackoverflow.com/a/26789089/883571

(updated at Mar 20, add timeout, so it looks better at this moment)

```coffee
# Code mostly done at:
# http://stackoverflow.com/a/26789089/883571

React = require 'react/addons'

util = require '../util/util'
time = require '../util/time'
Transition = React.createFactory (require '../module/transition')

$ = React.DOM

module.exports =

  # needs to implement
  # renderLayer: ->

  componentWillUnmount: ->
    return unless @_target?
    @_unrenderLayer()
    document.body.removeChild @_target

  componentDidUpdate: ->
    @_renderLayer()

  _renderLayer: ->
    if @_target?
      @_renderChildren()
      return
    if (not @props.show) and (not @_target?)
      return
    # so show but found no target
    @_target = document.createElement 'div'
    document.body.appendChild @_target
    tree = Transition transitionName: 'fade', enterTimeout: 200, leaveTimeout: 350
    React.render tree, @_target

    # use delay to create transition
    # more delay to fix in safari
    browser = util.parseUA().browser
    time.delay (if browser is 'safari' then 20 else 0), =>
      @_renderChildren()

  _renderChildren: ->
    tree = Transition transitionName: 'fade', enterTimeout: 200, leaveTimeout: 350,
      if @props.show
        @renderLayer()
    React.render tree, @_target

  _unrenderLayer: ->
    React.unmountComponentAtNode @_target
```

The bad part is that those operations are not optimized, they can be really slow when there are plenty of components are ready to show modals. React's components hierarchy makes it difficult when people create menus and modals which are appended under `<body>` and we can only do that by hand.

Can we add this feature in React?

----

in my case that's can be very slow:

![dom](https://cloud.githubusercontent.com/assets/449224/6523035/c6024e90-c426-11e4-954f-635054518eb6.png)

**Comment by syranide** [comment]
Change it to only add the element to body when the modal is going to be shown, also, why is `this._renderLayer()` called in `componentDidMount` that seems really weird and slow.

**Comment by jiyinyiyong** [comment]
@syranide I used to render modals nested in other components, but with two flaw:

* `position: fixed;` elements inside another fixed element is buggy, especially in safari
* modals are nested, stylesheets are mostly inherited, occasionally brings confusions

So I started to move the modals to body, but ReactCSSTransition addon fails.. And then came this solution I found, to add a container element at body first, and fades in my modal:

and ugly CoffeeScript way:

```coffee
React = require 'react/addons'

keyboard = require '../util/keyboard'
mixinLayered = require '../mixin/layered'

$ = React.DOM
T = React.PropTypes
cx = React.addons.classSet

module.exports = React.createFactory React.createClass
  displayName: 'body-modal'
  mixins: [mixinLayered]

  propTypes:
    # this components accepts children
    name:             T.string
    title:            T.string
    onCloseClick:     T.func.isRequired
    showCornerClose:  T.bool
    show:             T.bool.isRequired

  componentDidMount: ->
    window.addEventListener 'keydown', @onWindowKeydown

  componentWillUnmount: ->
    window.removeEventListener 'keydown', @onWindowKeydown

  onWindowKeydown: (event) ->
    if event.keyCode is keyboard.esc
      @onCloseClick()

  onCloseClick: ->
    @props.onCloseClick()

  onBackdropClick: (event) ->
    unless @props.showCornerClose
      if event.target is event.currentTarget
        @onCloseClick()

  renderLayer: ->
    className = "body-modal is-for-#{@props.name}"
    $.div className: className, onClick: @onBackdropClick,
      if @props.showCornerClose
        $.a className: 'icon icon-remove', onClick: @onCloseClick
      $.div className: 'box',
        if @props.title?
          $.div className: 'title',
            $.span className: 'name', @props.title
            $.span className: 'icon icon-remove', @onCloseClick
        @props.children

  render: ->
    $.div()
```
```coffee
BodyModal(show: decide) # set `decide` true to open
```

Maybe I should ask the question like this: 
[How to create a React Modal(which is append to `<body>`) with transitions?](http://stackoverflow.com/questions/28802179/how-to-create-a-react-modalwhich-is-append-to-body-with-transitions)

**Comment by gaearon** [comment]
Closing as it doesn't appear actionable for us.
