### ISSUE TITLE
Documentation Issue: Component Specs#displayName references non-existent source for more information.

### ISSUE THREAD

**Issue by JohnPostlethwait** [facebook/react#3338]
Here: http://facebook.github.io/react/docs/component-specs.html#displayname

The last sentence is this: "The displayName string is used in debugging messages. JSX sets this value automatically; see JSX in Depth."

`JSX in Depth` is a link to http://facebook.github.io/react/docs/jsx-in-depth.html#react-composite-components which is seemingly a non-existent anchor on the JSX in Depth page.

It would be good to have that link to somewhere actually documenting the auto-setting of displayName. I'm not sure where that is, or if it even still exists, which is why I didn't do it myself...

**Comment by koulmomo** [comment]
@JohnPostlethwait I don't know where it is now either, but the auto-setting works by using a `var` declaration.

If you have:

```jsx
var App = React.createClass({
// ...
});

// displayName will be auto-set to 'App'
```

**Comment by JohnPostlethwait** [comment]
Thanks @koulmomo. That was what I presumed based on my experience. I just wanted to get a ticket filed for better/fixed documentation when I noticed it...
