### ISSUE TITLE
Invoking renderToStaticMarkup in render() causes refs to break

### ISSUE THREAD

**Issue by masonicboom** [facebook/react#3344]
Demonstrated at http://jsfiddle.net/xnhzvdoa/1/; open the error console and you should see this:

```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

---

``` js
var Bug = React.createClass({
    render: function() {
        var html = React.renderToStaticMarkup(React.DOM.img());
        return React.DOM.div({ ref: 'ref' }, html);
    }
});
Bug = React.createFactory(Bug);

React.render(Bug(), document.body);
```

**Comment by jsfb** [comment]
cc @sebmarkbage

**Comment by zpao** [comment]
This doesn't have anything to do with `img` specifically, but does happen for our faked DOM components (reprod with input). It also has nothing to do with using the return value, just running `renderToStaticMarkup` makes it happen.

I'm guessing we're screwing up something with currentOwner somewhere along the line.

**Comment by masonicboom** [comment]
You're right. I updated the test case: http://jsfiddle.net/xnhzvdoa/2/.

```js
var Bug = React.createClass({
    render: function() {
        React.renderToStaticMarkup(React.DOM.img());
    }
});
Bug = React.createFactory(Bug);

React.render(Bug(), document.body);
```

**Comment by jsfb** [comment]
Your render function is not returning a valid value.  You need to return a ReactElement or `null` for no value.  If you add `return null;` to render, the error goes away.

**Comment by spicyj** [comment]
The new test case seems wrong (as @jsfb says, it doesn't repro the bug) but the original one is solid.

**Comment by zpao** [comment]
Yea, the invariant you're seeing there is different. But let's not get hung up too much on the specific example... the `ref` part of this is the important thing. Returning something with a ref in conjunction with rendering specific things to a string breaks. Add the return of a div with a ref in that example and the error is still there.

**Comment by jsfb** [comment]
Is the original one solid?  Isn't the second parameter of React.DOM.div supposed to be a ReactElement?  If you say `var html = React.DOM.img()` (ie. remove the `renderToStaticMarkup`), than that first example works just fine.

**Comment by jsfb** [comment]
I agree with @zpao 

Simplified example slightly to avoid any confusion about any interaction between renderToStaticMarkup and the return value.
```
var Bug = React.createClass({
    render: function() {
        React.renderToStaticMarkup(React.DOM.img());
        return React.DOM.img({ ref: 'ref2' }, null);
    }
});
Bug = React.createFactory(Bug);

React.render(Bug(), document.body);
```
renderToStaticMarkup is clearly mutating something in the internals.

**Comment by sebmarkbage** [comment]
`renderToStaticMarkup` can have side-effects other than just mutating the owner stack. Components that are instantiated also have life-cycle hooks (constructors, getInitialState and componentWillMount) which may cause side-effects.

The `render` method is pure and may not cause any side-effects. We should throw the same invariant we do for `setState` and a bunch of other methods, while you're in a render. This would be a much nicer error message.

The workaround is to `renderToStaticMarkup` in one of the life-cycles that are allowed to have side-effects. Such as `componentWillUpdate` and store the result so that it can be used inside `render`.

**Comment by sebmarkbage** [comment]
The fix here is to disable this use case.

**Comment by zpao** [comment]
My gut says that that's lazy. I think we should actually look into `renderToStaticMarkup` and `renderToString` and see if we can make those behave better. Short-term… fine, a friendly error message is better than this. But why should generating a string of markup be considered a side effect? (instantiating anything or calling any function can have side effects, so I don't really buy that excuse)

**Comment by sebmarkbage** [comment]
Another possible solution would be to disable componentWillMount for server-rendering and don't allow side-effects in constructors/getInitialState. Therefore making renderToStaticMarkup pure.

**Comment by sebmarkbage** [comment]
The contract of a Component is that it is allowed to trigger side-effects or do mutations in life-cycle methods. We need to ensure which API boundaries are side-effectful and not. Just because your component happens to not have a side-effect now, doesn't mean it won't later.

```javascript
var Component = React.createClass({
  componentWillMount: function() {
    triggerSideEffect();
  }
});
```

Regardless, I think that we'll probably go the opposite route and make `renderToStaticMarkup` asynchronous so that components can resolve dependencies before fully completing. In that case it'd definitely be a side-effect and it still wouldn't make sense to put it in render. (We most likely won't make render() itself async.)

**Comment by jsfb** [comment]
My instinct is that @zpao is correct; generating a string of markup shouldn't automatically be assumed to be side-effectful.  If your components are a pure function of props (which is the most ideal design), than calling this shouldn't be a problem.  If you're using janky components that side-load data, well, at use at your own peril.

Rendering another component is no different from calling into another library.  It's the caller's responsibility to ensure that the invocation is side-effect free.  We can warn if we know the invocation is has side effects, but we shouldn't block someone from rendering to string if they know their components are all well-behaved.

**Comment by masonicboom** [comment]
Thanks for the workaround @sebmarkbage. I shifted the renderToStaticMarkup into componentWillMount and componentWillReceiveProps, which works. It's slightly less desirable than doing so in render, because of the duplication, but not bad.

**Comment by catmando** [comment]
I just ran head long into this problem and must say I agree 100% with @zpao.  It was very surprising that renderToStaticMarkup should have any side effects at all.  This just seems like a bug.

**Comment by benkeen** [comment]
+1 bug

**Comment by snario** [comment]
Any updates on this?

**Comment by spicyj** [comment]
I would be happy to take a PR that sets `ReactOwner.current` back to its old value in all the places we mutate it.

**Comment by olslash** [comment]
fyi, we found a workaround to this in react-virtualized by using the fn form of ref rather than ref="ref"

https://github.com/bvaughn/react-virtualized/pull/302/commits/7e0f2827d6414fc016f72fde87484a6fc398fbf8

no idea why, but hopefully that helps someone

**Comment by gaearon** [comment]
Seems like https://github.com/facebook/react/issues/3344#issuecomment-189947665 would be a reasonable fix for this. Anyone wants to try?

**Comment by aweary** [comment]
This no longer appears to be an issue

https://codesandbox.io/s/1y2290jjoq
https://codesandbox.io/s/ko4qypj945
