### ISSUE TITLE
Nested arrays without key don't warn (anymore?)

### ISSUE THREAD

**Issue by chenglou** [facebook/react#3348]
It used to warn, right? Maybe not? `[[1, 2], [3, 4]].map((m) => m.map((n) => <div></div>))`

**Comment by syranide** [comment]
That does not become nested children, you're discarding the inner array...? :)

**Comment by spicyj** [comment]
Weird, looks like we never did this right.

**Comment by joshbedo** [comment]
Yeah i had an issue related to this recently on v0.10. I created a Tabs component which had Tabs.Panel inner children. When a key isn't specified it sets the key for both children to `children.length` which means they aren't distinct and it copied over the state from the previously selected tab. I noticed when i upgraded to v0.11 and v0.12 it worked perfectly. Is the behavior on the newer versions just to automatically add a key based on the child's index? or does it have to explicitly be set?
