### ISSUE TITLE
JSX transform doesn't always preserve line numbers

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#335]
Transforming this JSX:

```
/** @jsx React.DOM */
var HelloMessage = React.createClass({
  render: function() {
    return <div>
      Look!
      <a href=
        "http://www.facebook.com/">Facebook
      </a>
    </div>;
  }
});
```

gives

```
/** @jsx React.DOM */
var HelloMessage = React.createClass({displayName: 'HelloMessage',
  render: function() {
    return React.DOM.div(null,
" Look! ",      React.DOM.a( {href:"http://www.facebook.com/"}, "Facebook "      ),
    );
  }
});
```

Looks like we lost the line break after `Look!`, `href=`, and `Facebook`. I admit that breaking after `href=` is weird but since it compiles, it'd be nice if the line numbers were preserved so that lint errors, etc. can correspond easily.

**Comment by hossain666** [comment]
/** @jsx React.DOM */
var HelloMessage = React.createClass({displayName: 'HelloMessage',
  render: function() {
    return React.DOM.div(null,
" Look! ",      React.DOM.a( {href:"http://www.facebook.com/"}, "Facebook "      ),
    );
  }
});
