### ISSUE TITLE
onSubmit doesn't work with dangerouslySetInnerHTML (but onClick does)

### ISSUE THREAD

**Issue by benjie** [facebook/react#3359]
The following JSFiddle demonstrates the issue - clicking the submit for the first form alerts `click` and then `submit`; however the second form only alerts `click` - the submit is not bubbled up from the form that was embedded via `dangerouslySetInnerHTML`.

http://jsfiddle.net/s51q35ys/2/

Code for posterity:

```
var FormTest = React.createClass({
    onSubmit: function(e) {
      alert('submit');
      e.preventDefault();
    },
    onClick: function(e) {
      alert('click');
    },
    render: function() {
      return (
        <div onSubmit={this.onSubmit} onClick={this.onClick}>
          <form>
            <input type='text' />
            <input type='submit' />
          </form>
          <div dangerouslySetInnerHTML={ {__html: "<form><input type='text' /><input type='submit' /></form>"} } />
        </div>
      );
    }
});

React.render(<FormTest />, document.body);
```

**Comment by Eden-Sun** [comment]
I think your DOM structure is incorrect.
try remove another <div> wrapping as http://jsfiddle.net/s51q35ys/4/ such both event works

**Comment by benjie** [comment]
There are many workarounds such as the one you specify (not using dangerouslySetInnerHTML is one of them!) However this example shows an unexpected issue with event propagation from inside dangerouslySetInnerHTML. It's a deliberately minimal test case to reproduce the issue, but you could imagine the HTML in question was much more complex, perhaps with multiple forms, and was from an external source (perhaps a CMS) hence the system would not know to rewrite it as you have done.

**Comment by kidwm** [comment]
@benjie I also noticed that onSubmit doesn't work with `element.closest('form').submit()`

**Comment by kidwm** [comment]
Oh, it seems by design this will not triggered.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit

**Comment by nhunzaker** [comment]
I don't think there's anything that can be done here. `submit` does not bubble:

https://codepen.io/nhunzaker/pen/yXGaej

React allows it to bubble using the synthetic event system. It attaches an event listener to the form, normalizing the event bubbling process. Using `dangerouslySetInnerHTML` circumvents React, so there's no way for it to know about the event.

Sorry :(
