### ISSUE TITLE
Children for void elements should throw instead of warn

### ISSUE THREAD

**Issue by syranide** [facebook/react#3367]
#2266
Not to be released before React 0.14 is... or earlier if no one cares, as you absolutely shouldn't be doing this anyway.

This is mostly a reminder for myself, but feel free to take it.

**Comment by spicyj** [comment]
Let's warn for a release. :)

**Comment by jsfb** [comment]
It's already in as a warning for 0.13, right?  So it's ready to be an error in 0.14 as per the conversation @syranide cited.

**Comment by spicyj** [comment]
No, I just merged it for 0.14.

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/3372
