### ISSUE TITLE
Unexpected reserved word `class`

### ISSUE THREAD

**Issue by hemanth** [facebook/react#3374]
[This](http://jsfiddle.net/gnumanth/69z2wepo/3834/) works fine, but [this](http://jsfiddle.net/gnumanth/5vjqabv3/271/) fails, the former one is with `JSXTransformer-0.13.0.js` and  `react-with-addons-0.13.0.js` and the later one is only with ``react-with-addons-0.13.0.js`  as it's not using any JSX.

Am I missing something here?

**Comment by zpao** [comment]
Not all browsers or JS engines actually support ES6 class syntax yet. You will likely need to transform to ES5 for a while. React-tools does this, as does babel, and some other tools.

**Comment by hemanth** [comment]
@zpao I'm aware of that part, but the strange thing is [this](http://jsfiddle.net/gnumanth/69z2wepo/3834/) works even though it has the keyword `class` in it. The other one does not.

**Comment by hemanth** [comment]
The below works fine:

```js
class Hello extends React.Component {
  render() {
    return <div>Hello {this.props.name}</div>;
  }
}

React.render(<Hello name="World" />, document.getElementById('container'));
```

This does not, complains that `Uncaught SyntaxError: Unexpected reserved word`

```js
class Hello extends React.Component {
    render() {
            return React.createElement("div", null, "Hello ", this.props.name);
        }
    }
}
```

**Comment by camspiers** [comment]
Looks like there is an extra curly brace in the second example.

**Comment by hemanth** [comment]
@camspiers Well, ignore that, checkout those fiddles mentioned in the [issue](https://github.com/facebook/react/issues/3374#issue-60610924)

**Comment by camspiers** [comment]
JSXTransformer supports some ES6 features like classes. And so without it there is no transformation happing and you get a syntax error.

**Comment by hemanth** [comment]
So `JSXTransformer` polyfills, any related docs?

**Comment by camspiers** [comment]
It isn't so much of a polyfill but more a transform of ES6 code into ES5 code before execution.

https://github.com/facebook/jstransform/tree/master/visitors
https://github.com/facebook/react/blob/master/vendor/fbtransform/visitors.js#L42

**Comment by hemanth** [comment]
Oh hmm, so finally `class` will work not matter if the browser supports it or not for `jsx` and does not for  non-jsx.
