### ISSUE TITLE
Update the getting started fiddles to v0.13.0

### ISSUE THREAD

**Issue by hemanth** [facebook/react#3375]
As of now the js fiddles at [getting-started](http://facebook.github.io/react/docs/getting-started.html) is using old syntax.

It must be:

```js
class Hello extends React.Component {
  render() {
    return <div>Hello {this.props.name}</div>;
  }
}

React.render(<Hello name="World" />, document.getElementById('container'));
```

And the non-jsx version as well.

**Comment by rdebeasi** [comment]
This issue also affects the [getting started page](http://facebook.github.io/react/docs/getting-started.html).

**Comment by zpao** [comment]
We don't want these to be ES6 yet

**Comment by iamdustan** [comment]
Have you documented somewhere on why you don’t want the examples to be es6 yet?

**Comment by zpao** [comment]
`createClass` is still more powerful. es6 classes are enabled but have limitations (as you know).

I think what I might actually want is to redo our presentation of all of these examples so we can show createClass and es6 classes side by side.

**Comment by hemanth** [comment]
:+1:
