### ISSUE TITLE
Setting and removing focus in an empty input field with placeholder triggers change in IE

### ISSUE THREAD

**Issue by fizker** [facebook/react#3377]
See http://jsfiddle.net/69z2wepo/3887/ for example code.

When setting and removing focus from an empty `<input />` field with some `placeholder` text, the `onChange` event is triggered for IE 11 (I have not tested older versions). It does not trigger for other browsers.

My current work-around is to test the `value` that was last passed to the input with what is returned by `event.target.value`, and only act if they are different, but it would be nice if React would not send the change-event in the first place.

**Comment by jsfb** [comment]
@spicyj Sounds like a browser quark that we should normalize against, right?

**Comment by captray** [comment]
@jsfb Also ran into this. Doing a similar check against the nativeEvent's target's placeholder text versus incoming value. However, it should be valid that the user issue a search against the same text as the placeholder (in my case, 'Filter' will definitely be a valid search/filter term for my client).

**Comment by spicyj** [comment]
Yeah, this seems odd. Probably on the challenging side for a first bug, but it would be good to figure out why this is happening and how we can prevent it, while still making it possible to type the placeholder text in directly as @captray says.

**Comment by syranide** [comment]
#2185, not really related but I imagine both could be solved by a similar fix.

**Comment by aronwoost** [comment]
Also goes for IE10.
