### ISSUE TITLE
JSXTransformer incorrectly processes comment lines with a trailing space

### ISSUE THREAD

**Issue by globexdesigns** [facebook/react#3378]
When I run the following code through the JSXTransformer:

```
// This line has a trailing space 
function a() {
    return;
}
```

It outputs the following:

```
// This line has a trailing space function a() {
    return;
}
```

Which is obviously completely broken.

If I remove the extra space at the end of the comment line, then everything is okay.

**Comment by zpao** [comment]
Which version are you seeing this with? I can't repro with 0.13 (using http://facebook.github.io/react/jsx-compiler.html to test, as well as `jsx` on the command line)

**Comment by globexdesigns** [comment]
Please close. Non issue.
