### ISSUE TITLE
React.addons.createFragment javascript key order not guaranteed

### ISSUE THREAD

**Issue by ZeikJT** [facebook/react#3380]
In the [`createFragment`](http://facebook.github.io/react/docs/create-fragment.html) docs it says that
> the order of the object's keys is used to determine the order of the rendered children

But in javascript the order of the keys of an object is not guarunteed. Just because most implementations happen to maintain order doesn't mean it should be relied upon.

The note about a potential future api in JSX would definitely be a way to avoid this problem. The other way would be to change the api to accept a more cumbersome but strictly correct array of objects:

```js
React.addons.createFragment([
  {key: 'right', content: this.props.rightChildren},
  {key: 'left', content: this.props.leftChildren}
]);
```

**Comment by spicyj** [comment]
I specifically noted this in the docs:

> Note also that we're relying on the JavaScript engine preserving object enumeration order here, which is not guaranteed by the spec but is implemented by all major browsers and VMs for objects with non-numeric keys.

For now we're planning to keep it as-is (and the React internals currently rely on this property as it allows faster performance than other options) but we'll keep your suggestion in mind for the future.

**Comment by ZeikJT** [comment]
Good to know, thanks :+1:
