### ISSUE TITLE
How to replace parts of a string with a component?

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#3386]
I have this code which is obviously not working:

```coffee
    _.each(matches, (match) ->
      string = string.replace(match, ->
        <span className="match" key={i++}>{match}</span>
      )
    )
```

Because that would result into a string mixed with objects. Bad I know. But how can I add React components inside a string? All I want is to highlight parts of a string with a react component. A tough case to crack I guess.

**Comment by bloodyowl** [comment]
something like this should work :

```javascript
const escapeRE = new RegExp(/([.*+?^=!:$(){}|[\]\/\\])/g)
const safeRE = (string) => {
  return string.replace(escapeRE, "\\$1")
}

class Hightlight extends Component {
  static propTypes = {
    match : PropTypes.string,
    string : PropTypes.string,
  }
  
  render() {
    return (
      <span
        dangerouslySetInnerHTML={{
          __html : safeRE(string).replace(safeRE(this.props.match), "<strong className\"match\">$1</strong>")
        }} />
    )
  }
}
```

**Comment by binarykitchen** [comment]
Yes, I've been thinking of abusing `dangerouslySetInnerHTML` but I do not like this idea. This method labelled as dangerously for good reasons.

Is there no way to teach React to parse jsx within a string? Have React parse i.E.

```
var example = "this one word <span className="match" key={i++}>hello</span> is highlighted"
```

and return this in a render method?

**Comment by syranide** [comment]
@binarykitchen You can construct React elements dynamically and that's what you need to do here, you just can't do it with only string replacement.

**Comment by binarykitchen** [comment]
@syranide Yes, I already know that. My point is: wouldn't this be a nice JSX/React feature? Parse a string and turn any tags inside into child React components.

**Comment by spicyj** [comment]
You can use the `split` function with a regex and then replace the captured parts, like so:

```
var parts = "I am a cow; cows say moo. MOOOOO.".split(/(\bmoo+\b)/gi);
for (var i = 1; i < parts.length; i += 2) {
  parts[i] = <span className="match" key={i}>{parts[i]}</span>;
}
return <div>{parts}</div>;
```

Let me know if that's unclear.

**Comment by spicyj** [comment]
Parsing JSX at runtime is error-prone and slow, and can easily have security implications – it wouldn't inherently be any safer than dangerouslySetInnerHTML is.

**Comment by bloodyowl** [comment]
that can be a bit of an issue with type case

— mlb

**Comment by iansinnott** [comment]
I ran into this issue as well when trying to highlight parts of a string programatically (i.e. replace with `<span>` tags). I ended up creating a module based on @spicyj's solution above. For anyone interested: [iansinnott/react-string-replace](https://github.com/iansinnott/react-string-replace)

**Comment by oztune** [comment]
@iansinnott Thanks for sharing that. I started using it then realized I'm going to need the full `String.prototype.replace` API. Here is my version: https://github.com/oztune/string-replace-to-array

**Comment by EfogDev** [comment]
If `react-string-replace` doesn't fit your requirements:

https://github.com/EfogDev/react-process-string

**Comment by richardwestenra** [comment]
The following worked for me as way to highlight keyword(s) within a string of text, without
 dangerously setting HTML:
```es6
/**
 * Find and highlight relevant keywords within a block of text
 * @param  {string} label - The text to parse
 * @param  {string} value - The search keyword to highlight
 * @return {object} A JSX object containing an array of alternating strings and JSX
 */
const formatLabel = (label, value) => {
  if (!value) {
    return label;
  }
  return (<span>
    { label.split(value)
      .reduce((prev, current, i) => {
        if (!i) {
          return [current];
        }
        return prev.concat(<b key={value + current}>{ value }</b>, current);
      }, [])
    }
  </span>);
};

formatLabel('Lorem ipsum dolor sit amet', 'dolor');
// <span>Lorem ipsum <b>dolor</b> sit amet</span>
```

**Comment by EliecerC** [comment]
I needed something like this for mentions matching some pattern so it can wrap multiple values and did some changes to the @richardwestenra solution. Maybe it will be useful for someone.

```
/**
 * Find and highlight mention given a matching pattern within a block of text
 * @param {string} text - The text to parse
 * @param {array} values - Values to highlight
 * @param {RegExp} regex - The search pattern to highlight 
 * @return {object} A JSX object containing an array of alternating strings and JSX
 */
const formatMentionText = (text, values, regex) => { 
    if (!values.length)
        return text;

    return (<div>
        {text.split(regex)
            .reduce((prev, current, i) => {
                if (!i)
                    return [current];

                return prev.concat(
                    values.includes(current)  ?
                        <mark>
                            {current}
                        </mark>
                        : current
                );
            }, [])}
    </div>);
};

const text = 'Lorem ipsum dolor sit amet [[Jonh Doe]] and [[Jane Doe]]';
const values = ['Jonh Doe', 'Jane Doe'];
const reg = new RegExp(/\[\[(.*?)\]\]/);

formatMentionText(text, values, reg);
// Lorem ipsum dolor sit amet <mark>Jonh Doe</mark> and <mark>Jane Doe</mark>

```

**Comment by rmtngh** [comment]
I had a similar issue and I solved it with react portals, to easily find the node, I replaced the string with a div and rendered my react component using createPortal into that div.

**Comment by rmtngh** [comment]
@oztune Thanks for your reply, In this case I have a string of html markup coming from a wysiwyg editor of a CMS and I'd like to place react components in certain places inside that markup.
Do you think it would be better to use a library instead of using portals? I think what portal does is to just render the component inside another node instead of nearest node which wouldn't be more expensive than rendering a normal component and the only extra step is to replace the string which can be done with native js replace.
Am I missing anything?  Will there be any advantages in using the library instead?

**Comment by oztune** [comment]
@rmtngh I'd say it depends on what you're trying to do. If you're just trying to sprinkle some React components in different areas of your DOM tree, and the tree isn't already being rendered with React, portals are the way to go. The method I mentioned is most useful when the parts you're trying to replace are already rendered inside of a React component.

**Comment by wojtekmaj** [comment]
Here's the code that returns an array of nodes given text and pattern:

```js

const highlightPattern = (text, pattern) => {
  const splitText = text.split(pattern);

  if (splitText.length <= 1) {
    return text;
  }

  const matches = text.match(pattern);

  return splitText.reduce((arr, element, index) => ([
    ...arr,
    element,
    <mark>
      {matches[index]}
    </mark>,
  ]), []);
};
```

**Comment by alex9pro1** [comment]
Thank you @wojtekmaj 
My variant for groups in pattern: 

`const replacePatternToComponent = (text, pattern, Component) => {
  const splitText = text.split(pattern);
  const matches = text.match(pattern);

  if (splitText.length <= 1) {
    return text;
  }

  return splitText.reduce((arr, element) => {
      if (!element) return arr;

      if(matches.includes(element)) {
        return [...arr, Component];
      }

      return [...arr, element];
    },
    []
  );
};

replacePatternToComponent('Foo [first] Bar [second]', /(\[first\])|(\[second\])/g, <Component />)
`

**Comment by pedrodurek** [comment]
Approach using typescript:
```
    const formatString = (
        str: string,
        formatingFunction?: (value: number | string) => React.ReactNode,
        ...values: Array<number | string>
    ) => {
        const templateSplit = new RegExp(/{(\d)}/g);
        const isNumber = new RegExp(/^\d+$/);
        const splitedText = str.split(templateSplit);
        return splitedText.map(sentence => {
            if (isNumber.test(sentence)) {
                const value = values[Number(sentence)];
                return Boolean(formatingFunction) ? formatingFunction(value) : value;
            }
            return sentence;
        });
    }
```

Example of use:
```
const str = `{0} test {1} test`;
formatString(str, value => <b>{value}</b>, value1, value2);
```

**Comment by Dashue** [comment]
@rmtngh could you provide a sample of how you achieved the markup enrichment through createportal? We're looking to do the same.

**Comment by ykadosh** [comment]
Great thread guys!

I created a simple [React Text Highlighter](https://codepen.io/ykadosh/pen/ydzevj?editors=0110) pen that implements some of the ideas in this thread, with some extra magic...), maybe future visitors can find it useful.

**Comment by rehat101** [comment]
Here's a solution using `map` forking @sophiebits solution here:

```javascript
const reg = new RegExp(/(@\w+)/, 'gi');
const parts = text.split(reg);
return <div>{parts.map(part => (part.match(reg) ? <b>{part}</b> : part))}</div>;
```

**Comment by djD-REK** [comment]
Beautiful solution @rehat101

**Comment by djD-REK** [comment]
Here's what worked best in my case -- splitting by the space character and looking for specific words.

It's a little messy in the HTML but who cares 😂

💗 **RegExp** and **map** make this soooo clean.  💗💗💗

![image](https://user-images.githubusercontent.com/53202242/62806760-b9ca2d00-bac1-11e9-8587-570bcdeeac29.png)

```
const Speech = ({ speech, speeches, setSpeeches, i, text }) => {

const highlightRegExp = new RegExp(
    /you|can|do|it|puedes|hacerlo|pingüinos|son|bellos/,
    "gi"
  );
  const delineator = " ";
  const parts = text.split(delineator);

  return (
        <div>
          {parts.map(part =>
            part.match(highlightRegExp) ? <b>{part + " "}</b> : part + " "
          )}
        </div>
  );
};

```

**Comment by nilsbeuth** [comment]
Beautiful @rehat101

**Comment by stikut** [comment]
> If `react-string-replace` doesn't fit your requirements:
> 
> https://github.com/EfogDev/react-process-string

Brilliant! I find it extremely useful since most of the times you actually need to access the original string

**Comment by SalehAly01** [comment]
I refactored the solution of @nullhook a little bit to make it accept variable from a query and memic the behavior of Google search
 ```js
const highlightQueryText = (text: string, filterValue: string) => {
 const reg = new RegExp(`(${filterValue})`, 'gi');
 const textParts = text.split(reg);
 return (
            <span css={{ fontWeight: 600 }}>
                {textParts.map(part => (part.match(reg) ? <span css={{ fontWeight: 'normal' }}>{part}</span> : part))}
            </span>
        );
    };
```

**Comment by SalehAly01** [comment]
I refactored the solution of @nullhook a little bit to make it accept variable from a query and memic the behavior of Google search autocomplete
 ```js
const highlightQueryText = (text: string, filterValue: string) => {
 const reg = new RegExp(`(${filterValue})`, 'gi');
 const textParts = text.split(reg);
 return (
            <span style={{ fontWeight: 600 }}>
                {textParts.map(part => (part.match(reg) ? <span style={{ fontWeight: 'normal' }}>{part}</span> : part))}
            </span>
        );
    };
```

**Comment by Lazercat** [comment]
so I found a nice combination of implementing DOMPurify to sanitize html strings with html-react-parser to find targeted markup in it and convert it to JSX components - I use Rebass with passed props as an example.. that came out quite nicely, the two packages will help you to avoid the overhead of rolling your own parser, I just wouldnt recommend this parser package without sanitization.   For those struggling with this still maybe scope out this codepen for what it's worth:   https://codesandbox.io/s/eager-wiles-5hpff.   Feedback on any improvements much appreciated too.

**Comment by djD-REK** [comment]
Hey Jesse,
That seems like a really nice combo for taking text and transforming it to
React components! It would definitely be good for replacing parts of a
string with a component.

Thanks for sharing.

Could also be useful in a JAMstack site to turn Markdown into components.

Best regards,
Derek

Derek R. Austin, PT, DPT, MS, BCTMB, LMT, CSCS


Join me on LinkedIn: https://www.linkedin.com/in/derek-austin/

**Comment by elron** [comment]
> You can use the `split` function with a regex and then replace the captured parts, like so:
> 
> ```js
> var parts = "I am a cow; cows say moo. MOOOOO.".split(/(\bmoo+\b)/gi);
> for (var i = 1; i < parts.length; i += 2) {
>   parts[i] = <span className="match" key={i}>{parts[i]}</span>;
> }
> return <div>{parts}</div>;
> ```
> 
> Let me know if that's unclear.

This works great. Any way to get it to work in Angular? I've posted a question about it, using your code:
https://stackoverflow.com/questions/60889171/wrap-certain-words-with-a-component-in-a-contenteditable-div-in-angular

**Comment by luigbren** [comment]
Hello friends, I need your help please, I am using React Native and what I need to do is from a text that I extract from the DB to apply a format (font color, link) to make @mentions, when searching if in the text finds 1 single match makes replacement all good, but! If there are several @mentions in the text, it throws me an error.

   /////Text example:  **_hey what happened @-id:1- everything ok ?? and you @-id:2-  @-id:3- @-id:4-_**
  //// **listusers its array, example: [idusuario: "1", usuario: "@luigbren", format: "@-id:1-".....]**

```
const PatternToComponent = (text, usuarios,) => {
    let mentionsRegex = new RegExp(/@-(id:[0-9]+)-/, 'gim');
    let matches = text.match(mentionsRegex);
    if (matches && matches.length) {
        matches = matches.map(function (match, idx) {
            let usrTofind = matches[idx]
            //////////////////////////////////////////////////////////////////
            const mentFormat = listusers.filter(function (item) { 
                const itemData = item.format;
                return itemData.indexOf(usrTofind) > -1;
            });
            if (mentFormat.length > 0) {
                let idusuario = mentFormat[0].idusuario
                let replc = mentFormat[0].usuario

                console.log(usrTofind) //// here find @-id:1-
                console.log(replc)   //// here is @luigbren for replace
 
                ////////// now here replace part of the string, @-id:1- with a <Text> component 
                ///////// with @luigbren and the link, this is repeated for every @mention found

                parts = text.split(usrTofind);
                for (var i = 1; i < parts.length; i += 2) {
                  parts[i] = <Text key={i} style={{ color: '#00F' }} onPress={() => { alert('but this is'); }}>{replc}</Text>;
                }
                return text = parts;
                /////////////////////////////////////////////////////////////////////
            } else {
                return text
            }
        });
    } else {
        return text
    }
    return text
};
```

in this way the code works well for me only when in the text there is only one mention, example '_hey what happened @-id:1- everything ok ??_' , but when placing more than one mention it gives me an error, example: '_hey what happened @-id:1- everything ok ?? @-id:2- @-id:3-_' ... Error: **TypeError: text.split is not a function** and if instead of placing  _parts = text.split(usrTofind);_ I place  _parts = text.toString().split(usrTofind);_ it gives me an [Object Object] error

**Comment by sadi304** [comment]
You can use  `html-react-parser` to parse the string, then replace by node name with jsx components. This type of replacement will allow you to use react elements dynamically by replacing strings.

**Comment by Pedroxam** [comment]
Someone tell me how can replace `react-router-link` in string?

**Example:**


```
var text = "Are You okey @sara ?";

var href= <Link to={{
  pathname: '/user/sara',
}}> @sara </Link>;

var replace = text.replace("@sara", href);

//output : Are You okey [Object Object] ?
```

**Comment by muhammadwafa** [comment]
I have almost the same question in `react-native`, I appreciate if anyone can help me

[my question](https://stackoverflow.com/questions/61500042/how-to-parse-string-into-react-native-component)

**Comment by artem-solovev** [comment]
Nothing worked for me except this package https://www.npmjs.com/package/regexify-string

**Comment by iksent** [comment]
I am using this function:

```
export const replaceWithHtml = (
  text: string,
  textToReplace: string,
  replaceValue: any,
): any[] => {
  const delimiter = '|||||'
  return text && text.includes(textToReplace)
    ? text
        .replace(textToReplace, `${delimiter}${textToReplace}${delimiter}`)
        .split(delimiter)
        .map((i) => {
          if (i === textToReplace) {
            return replaceValue
          } else {
            return i || null
          }
        })
    : text
}
```

**Comment by tscok** [comment]
I just wanted a simple interpolation tool, to replace certain keywords with certain elements.

To reduce the number of elements in my output I'm using a [`React.Fragment`](https://reactjs.org/docs/fragments.html).

```js
const interpolate = (text, values) => {
  const pattern = /([$0-9]+)/g
  const matches = text.match(pattern)
  const parts = text.split(pattern)

  if (!matches) {
    return text
  }

  return parts.map((part, index) => (
    <Fragment key={part + index}>{matches.includes(part) ? values[part] : part}</Fragment>
  ))
}

// ...

<p>
  {interpolate('$1 with $2 is fun!', {
    $1: <em>Playing</em>,
    $2: <strong>JavaScript</strong>,
  })}
</p>

// <p><em>Playing</em> with <strong>JavaScript</strong> is fun!</p>
```
Thanks @sophiebits for the idea on `split()` 🙏

**Comment by TobiasWehrum** [comment]
Based on @pedrodurek's solution, here is something for my specific needs (translations with readable keys instead of just numbers):

```ts
export const insertComponentsIntoText = (
    str: string,
    replacements: {
        [key: string]: React.ReactNode
    }
) => {
    const splitRegex = new RegExp(/\[\[(\w*)\]\]/g);
    const parts = str.split(splitRegex);
    return parts.map(part => {
        if (replacements.hasOwnProperty(part)) {
            return replacements[part];
        }
        return part;
    });
};
```

Example:
```ts
insertComponentsIntoText(`"Please accept our [[privacyPolicyLink]] and [[termsLink].", {
    "privacyPolicyLink": <a key="privacyPolicyLink" href="/privacy">Privacy Policy</a>,
    "termsLink": <a key="termsLink" href="/terms">Terms and Conditions</a>
})
```
...becomes...
```
Please accept our <a key="privacyPolicyLink" href="/privacy">Privacy Policy</a> and <a key="termsLink" href="/terms">Terms and Conditions</a>.
```

(The keys are necessary because it actually becomes an array, and react doesn't like array elements without keys.)

**Comment by Anu-Ujin** [comment]
> Nothing worked for me except this package https://www.npmjs.com/package/regexify-string

Me too. Tried all of them only this package works. Thank you!
