### ISSUE TITLE
TestUtils.findRendered* seems to be using deprecated getDOMNode

### ISSUE THREAD

**Issue by blainekasten** [facebook/react#3387]
I just updated to all of the latest v13 things. My jest tests are now constantly warning me:

    getDOMNode(...) is deprecated in plain JavaScript React classes.

note: I am using jest 0.2.2 due to node versioning issues. Not sure if this version is referencing an old react or just using the provided one through node_modules

**Comment by zpao** [comment]
See #3329. It's not calling getDOMNode, but it's using the property as a heuristic. Our warnings on ES6 classes are done via getters so just accessing the property (even without calling) results in the warning.

**Comment by blainekasten** [comment]
Are we planning to do anything about it? It seems a little crazy that every single one of my tests throws that warning because of the lookup. Here's an example of my tests currently:

![screen shot 2015-03-12 at 7 48 38 pm](https://cloud.githubusercontent.com/assets/2916023/6631242/d12b54c8-c8f0-11e4-980a-f22b6abd3ef8.png)

plus many more that couldn't fit on screen..
