### ISSUE TITLE
Cannot read property 'mountComponent' of undefined after upgrading to 0.13

### ISSUE THREAD

**Issue by Tvaroh** [facebook/react#3388]
After upgrading to React 0.13 I get `Cannot read property 'mountComponent' of undefined` on rendering.

The relevant code is (instatiateReactComponent.js:40):

```javascript
function isInternalComponentType(type) {
  return (
    typeof type === 'function' &&
    typeof type.prototype.mountComponent === 'function' &&
    typeof type.prototype.receiveComponent === 'function'
  );
}
```

`type.prototype` is undefined here, and `type` argument is `"noscript"`.

Can someone suggest what can cause such an error?

**Comment by zpao** [comment]
if `type` is a string we would never look at `type.prototype`, so something else must be going on. Can you make a repro case.

**Comment by deminoth** [comment]
I have same error message and it appears when I try to use `ReactClass` with `React.createFactory`. 
```
/* ReactClass HelloWorld is defined in HelloWorld.js */
var HelloWorld = React.createFactory(require('./HelloWorld').HelloWorld);

var Container = React.createClass({
  render: function() {
    return (
      <div className="container">
        <HelloWorld />
      </div>
    );
  }
});
```
It works when I remove factory like `var HelloWorld = require('./HelloWorld').HelloWorld;`, but without factory my server-side rendering code with `React.renderToString` doesn't works. :(

**Comment by syranide** [comment]
@deminoth You shouldn't use `React.createFactory` with JSX, it should just be the plain class.

**Comment by deminoth** [comment]
Ok, I fixed my client-side code like 
```
var Container = require('./components/Container').Container;
React.render(<Container user={User} list={DummyList} />, mountNode);
```
and server-side code like
```
var Container = require('../components/Container').Container;
var reactHtml = React.renderToString(React.createElement(Container, {user: User, list:DummyList}));
```
Now it works well.
Thank you, @syranide

**Comment by spicyj** [comment]
Let's check to see if we can have a better warning for this.

**Comment by syranide** [comment]
@spicyj, @deminoth's problem is not the one in the issue though (just making sure :))

**Comment by deminoth** [comment]
@syranide, @spicyj : I think @Tvaroh's error in this issue can be reproduced with my mistake(`React.createFactory` with JSX and put them into `React.render(ReactFactory({}))`), but I can't be sure before confirm it.

**Comment by Tvaroh** [comment]
Thank you guys I will check it.

**Comment by Tvaroh** [comment]
Yes, that was the case. Closing.

**Comment by syranide** [comment]
@Tvaroh Really? It's still not making any sense to me how a string would pass the function check though...

**Comment by Tvaroh** [comment]
@syranide, I've just removed `React.createFactory` called twice in a row.
