### ISSUE TITLE
Pert.start() leads to Uncaught TypeError: Cannot read property 'counts' of undefined

### ISSUE THREAD

**Issue by ryanzec** [facebook/react#3389]
I wanted to see how each of my pages where performing so I looked to the Perf tool.  I added the perf tool to the componentWillUpdate / componentDidUpdate on my main component (I assume that is the right place to put it, did not see any documentation anywhere on how to use Perf within ReactJS code) but that gives me this error:

Uncaught TypeError: Cannot read property 'counts' of undefined

The code looks like this:

https://gist.github.com/ryanzec/806db1aee328a5d847aa

I put console log's in the code and it never gets to the componentDidUpdate method.  The error is happening here: 

https://github.com/facebook/react/blob/dd6b8ab8b92a180f8688f21997f394100136d655/src/test/ReactDefaultPerf.js#L225

Is this is bug?  Am I use Perf incorrectly?

**Comment by ryanzec** [comment]
Any insight anyone can provide into this?

**Comment by zpao** [comment]
Taking a look through it, I think you need to call start outside of a render. Many of the measurements are based around update batches so a batch is already started by the time you call this. The internal state of Perf gets messed up (which is why something is `undefined`).

The original goal of perf is that it would be used to measure the whole app and then you could drill down. It is not the same as something like `console.time/End`.

**Comment by also** [comment]
I don't understand why this is closed. Shouldn't it at least throw a helpful error? Throwing a type error seems very unlike React, especially for something that seems seems perfectly valid given the documentation.

> Start/stop the measurement. The React operations in-between are recorded for analyses below. Operations that took an insignificant amount of time are ignored.

This makes it sound like `console.profile()` and `console.profileEnd()` which can be called at any time.

**Comment by slorber** [comment]
I've had this case just now, after playing with React-tappable lib

I don't use Perf.start on the render phase and did not touch any perf code since 3 months.

```
Uncaught TypeError: Cannot read property 'counts' of undefined appLibs.js:51216ReactDefaultPerf.measure appLibs.js:51216ReactPerf.measure.wrapper appLibs.js:55139ReactCompositeComponentMixin._updateRenderedComponent appLibs.js:48539ReactCompositeComponentMixin._performComponentUpdate appLibs.js:48519ReactCompositeComponentMixin.updateComponent appLibs.js:48435ReactDefaultPerf.measure appLibs.js:51222ReactPerf.measure.wrapper appLibs.js:55139ReactCompositeComponentMixin.receiveComponent appLibs.js:48299ReactReconciler.receiveComponent appLibs.js:56015ReactCompositeComponentMixin.performUpdateIfNecessary appLibs.js:48317ReactReconciler.performUpdateIfNecessary appLibs.js:56033runBatchedUpdates appLibs.js:57855Mixin.perform appLibs.js:59643Mixin.perform appLibs.js:59643assign.perform appLibs.js:57799flushBatchedUpdates appLibs.js:57879ReactPerf.measure.wrapper appLibs.js:55141Mixin.closeAll appLibs.js:59716Mixin.perform appLibs.js:59657ReactDefaultBatchingStrategy.batchedUpdates appLibs.js:50821batchedUpdates appLibs.js:57814ReactEventListener.dispatchEvent
```

**Comment by jimfb** [comment]
Yeah, that seems reasonable @also, I'm going to re-open this for the purpose of providing a more useful error message.

**Comment by slorber** [comment]
so @jimfb the problem with Perf I had in React-tappable is related to a bug in React-tappable.


Basically, this bug makes my app code do something like that:

```
this.setState({someState:"x",function() {
     Perf.start();
     triggerRendering(); 
     Perf.stop();
     showPerf();
})
```

The `onTap` listener is fired on the setState callback and produces weird behaviors with Perf

**Comment by gaearon** [comment]
Removing “good first bug” because this code is being rewritten anyway.
Keeping this open to make sure we fix it in the new code.

**Comment by gaearon** [comment]
AFAIK we already support starting/stopping outside of top level now.
