### ISSUE TITLE
componentWillReceiveProps is called passing data from context

### ISSUE THREAD

**Issue by Tvaroh** [facebook/react#3390]
I'm getting very strange issue: `componentWillReceiveProps` is called on rendering when it shouldn't. The second argument (previous props) is okay and contain just one prop I have passed. But the first argument (new props) is in fact my React context. I was using `withContext` and tried to migrate on newer API (`getChildContext` with a wrapper) but the problem persisted.

How can it be? I don't change any prop and don't pass React context instead of props too.

**Comment by miracle2k** [comment]
It seems this isn't documented, but the signature of ``componentWillReceiveProps`` is actually:

``componentWillReceiveProps(nextProps, nextContext)``

**Comment by jimfb** [comment]
@Tvaroh: @miracle2k is correct, the official signature is `componentWillReceiveProps(nextProps)`.  Context is not officially supported, but is currently the second parameter.  I think your previous props are still available on the component instance.

It's also worth noting that the documented API guarantees that componentWillReceiveProps will get called when your props change.  An invocation of `componentWillReceiveProps` is not guaranteed to imply that your props have changed, nor is it guaranteed that componentWillReceiveProps will not get called if your props do not change.  Do not assume that componentWillReceiveProps will only be called on props change.
