### ISSUE TITLE
checkAndWarnForMutatedProps fails in 0.13

### ISSUE THREAD

**Issue by leiserfg** [facebook/react#3396]
This error make some addons (as react-fundation-app) fail. The cause is related with `element._store.originalProps`, that property (originalProps) not exist when you use a DOM element (div, a, p). I don't know the origianl cause of that, but it can be solved by changing
`if (!element._store)` for `if (!element._store || !element._store.originalProps)`.

**Comment by zpao** [comment]
Do you have a repro case for this?

**Comment by spicyj** [comment]
My gut says this is multiple versions of React mixing.

**Comment by jnu** [comment]
I saw this issue playing with FixedDataTable... the problem was indeed mixing versions, webpack injected dependencies from React 0.12, so elements were created without `element._store.originalProps`, which only gets added in 0.13.

**Comment by spicyj** [comment]
Closing – @leiserfg if you're still having trouble let me know.

**Comment by leiserfg** [comment]
It's true, I rebuild the lib and now works fine.
