### ISSUE TITLE
JSX: Illegal import declaration

### ISSUE THREAD

**Issue by Microx** [facebook/react#3401]
Hi,

I try new react v0.13 and I got Error: Illegal import declaration. It was all right for react v0.12.2. I tried set options harmony to true and false but it doesn't matter.

Code:

```javascript
import foo from 'path/to/file.js';

var view = React.createClass({
//definition
});
```

Do you have a some solution?

Thanks.

**Comment by sairion** [comment]
Possibly related:

https://github.com/floatdrop/plugin-jsx/issues/7
https://github.com/facebook/react/pull/3143

**Comment by Microx** [comment]
Hi,

I set for my gulp task react({harmony: false, es6module: true}) and everything working right.

Thanks

Thanks

**Comment by zpao** [comment]
Sorry, meant to comment the other day. You did figure out the right option (`es6module`). Sorry about the confusion and lack of docs here.

**Comment by Microx** [comment]
Hi,

I am happy that it had a solution.

Thanks for yours quick reaction.
