### ISSUE TITLE
Double render/misreport instance count in 0.13.0

### ISSUE THREAD

**Issue by jlfwong** [facebook/react#3407]
When using `React.addons.Perf.printWasted()`, I'm seeing incorrect counts for the number of instances of elements from a render. 0.12.1 prints what I'd expect.

I'm not sure if this is a problem in reporting or a problem in the actual rendering.

http://jsbin.com/poqoxuditu/2/

Here's the result of the measuring the same render:

![image](https://cloud.githubusercontent.com/assets/150329/6646724/41fa7320-c99e-11e4-9b8c-9e4cfcdd0d58.png)

Notice that for 0.13, the wasted time is almost 2x the total time listed.

**Comment by jide** [comment]
I seem to have the same issue with 0.12.2, is it normal ?
