### ISSUE TITLE
<time> with pubDate attribute

### ISSUE THREAD

**Issue by t128** [facebook/react#3411]
Hi,

im trying to render a time element with a pubDate boolean attribute, but react keeps ignoring it. What m i doing wrong? Or is this maybe a bug in React?

```
time = moment(time)
return React.DOM.time(
	{
		title: time.format('llll'),
		dateTime: time.format(),
		pubDate: true,
	},
	time.fromNow()
)
```

**Comment by zpao** [comment]
It looks like `pubdate` isn't part of any html standard.

**Comment by t128** [comment]
http://www.w3.org/TR/2011/WD-html5-author-20110705/the-time-element.html but this is an old version isn't it?

**Comment by syranide** [comment]
@t128 It seems it was dropped from the spec, I saw it mentioned somewhere that `itemprop="datePublished"` replaced it.

**Comment by t128** [comment]
@syranide thank you for your answer
