### ISSUE TITLE
Update "Cloning ReactElement" documentation to include info on React.cloneElement

### ISSUE THREAD

**Issue by mheiber** [facebook/react#3432]
The documentation for ["Cloning ReactElement"](http://facebook.github.io/react/docs/clone-with-props.html) uses React.cloneWithProps and recommends the following method for preserving `key`:

    If you wish to preserve the key, add it to the `extraProps` object

I suggest including React.cloneElement here instead of recommending to add `key` to the `extraProps` object.

**Comment by spicyj** [comment]
Good idea, thanks. Want to send a pull request?

**Comment by mheiber** [comment]
Sure.
