### ISSUE TITLE
Document limitations on props passed into React.createElement()

### ISSUE THREAD

**Issue by neilgalarneau** [facebook/react#3435]
Please document that the props object passed into createElement does NOT get passed to the target Component.

It was surprising to me that a method defined on the prototype of the object I passed into createElement was NOT available on this.props in the target Component. When I read the source I saw why.

**Comment by bloodyowl** [comment]
how is this surprising?

**Comment by neilgalarneau** [comment]
Is there something in the documentation I missed?

**Comment by jimfb** [comment]
This doesn't come up very often so, it's probably not worth cluttering up the documentation with something that no one will ever remember reading.

However, we probably could warn if `config.__proto__ != null && config.__proto__ !== Object.prototype`

**Comment by yjcxy12** [comment]
I'd like to work on this issue.

**Comment by scsper** [comment]
i was browsing the "good first bug" list, and it looks like this one is resolved.  @jimfb would you mind closing it if you agree?

**Comment by jimfb** [comment]
Yes, you're correct, thanks!

**Comment by spicyj** [comment]
@neilgalarneau Can you provide a brief sample of the code you were using? In particular, I'm curious whether you were using JSX or React.createElement directly.

**Comment by neilgalarneau** [comment]
I'm sorry, but I don't remember the context of the issue. I was most likely using JSX.
