### ISSUE TITLE
Allow quoteAttrName to always quote names

### ISSUE THREAD

**Issue by DomBlack** [facebook/react#3437]
I'm currently trying to use React's JSX transformer before a Google Closure run, under Advanced optimisations. The problem is, attributes are being renamed by the closure compiler, and are failing at run time.

For example; `<Route handler={app} path="/" >`
is being transformed into; `React.createElement(ReactRouter.Route, {handler:app, path:"/"})`
which is being compiled into; `React.createElement(ReactRouter.Route, {e:b, path:"/"})`

The preposed solution is to allow the [quoteAttrName](https://github.com/facebook/react/blob/0.13-stable/vendor/fbtransform/transforms/jsx.js#L96) to always quote all names in the config param of `createElement`. This would mean the Closure compiler would leave the config object alone.

Does anybody have thoughts on this?

*Note: in the compiled option, `b` is correct as the compiler renamed the react component.*

**Comment by spicyj** [comment]
If react-router were compiled also with closure compiler, then minifying the prop names would be the correct thing to do. Since it's not, my understanding is that you're supposed to create an externs file that lists all the property names that it uses, so that the key `handler` remains unchanged:

https://developers.google.com/closure/compiler/docs/api-tutorial3#externs

Let me know if that doesn't sound right to you.

**Comment by DomBlack** [comment]
The example I gave was for react-route, but it would apply to any react library.

I have externs for both react and react-router and even created an "ElementConfig" type which has the handler and path keys in it. However, externs do not work in this case as the JSX does not annotate the datatype of the object it creates, so the extern only verifies the argument once it's being sent to the function, it does not imply the object being passed in is an "ElementConfig".  - i.e. the JSX transform would need to output;

```js
React.createElement(ReactRouter.Route, /** @type {ElementConfig} */{handler:app, path:"/"})
```

The externs I wrote where;
```js
/**
 * @typedef {Object} ElementConfig
 * @property {React.ReactComponent=} handler Needed for react-router
 * @property {string=} path Needed for react-router
 */
var ElementConfig;

/**
 * @param {React.ReactComponent|string} type
 * @param {?ElementConfig} config
 * @param {...*} children
 * @return {React.ReactComponent}
 */
React.createElement = function(type, config, children) {};
```

I was thinking rather than being default behaviour, perhaps just being an option which can be passed into the jsx, so it doesn't adversely affect the application sizes of other users.

**Comment by zpao** [comment]
Wouldn't it still get minified on the other end? Wouldn't `this.props.handler` become something like `this.p.a` there but would be `this.p['handler']` if we quoted in the transform? Or everybody accessing props would have to write `this.props['handler']`, which seems pretty fragile.

**Comment by DomBlack** [comment]
Yes, with this option it would still get minified on the other end, so accessing the props would need to be written as `this.props['handler']` rather than `this.props.handler`. However, developers who work with the closure compiler understand when they have to write between the two styles of accessor, so I don't think this is really that big of a problem.

If you compile react and react-router as part of the project (rather than externs), then without this change the code will work as `handler` renamed the same in both files - and so it works.

However react itself is not closure compiler friendly without some tweaks, and even then it produces 600+ warnings, (Advanced mode, with verbose warnings), which prevents you from seeing your own errors and warnings. Including it within the build also removes the ability to leverage existing CDN's for the two projects. It's worth nothing that due to the renaming process, the React developer tools break.

As I said if it was a non defaulted option on the JSX transform, then it allows developers wanting to use react, react libraries and the closure compiler to build react projects easier with working debugging tools.
