### ISSUE TITLE
Make shouldComponentUpdate accept boolean value

### ISSUE THREAD

**Issue by Youmoo** [facebook/react#3448]
In jQuery , we can disable some event like this :
```javascript
$(element).click(false);
```
Similarly , when we want to  define a *immutable* component , we can write :
```javascript
var Hello = React.createClass({
    shouldComponentUpdate:false, // attention
    render: function () {
        return 'Hello World.'
    }
});
```
So, is it possible to make *shouldComponentUpdate* accept boolean value?

**Comment by syranide** [comment]
`shouldComponentUpdate: function() { return false; }` ... ?

**Comment by Youmoo** [comment]
Sorry for my poor English..

I mean for a *immutable* component we write 
```shouldComponentUpdate:  false``` 
instead of
 ```shouldComponentUpdate: function() { return false; }``` 
i.e. , the lifecycle method *shouldComponentUpdate* can either accept a function or 
a boolean as its value

**Comment by syranide** [comment]
@Youmoo Right, as far as I see it React components are classes, not a bunch of values, so magic values and "shape-shifting" properties should be avoided at all costs. `shouldComponentUpdate` is a method so it should be a function.

cc @sebmarkbage

**Comment by spicyj** [comment]
Yeah, since you can just write `function() { return false; }` to get the same effect we'd rather keep API consistency instead of making this pattern a few characters shorter. You can even write `() => false` with ES6 arrow functions if you're looking to save a few more.

**Comment by sebmarkbage** [comment]
I think we might want to build a different system where a parent promises that its properties are pure, and if so, the children are able to do shallow comparison by default.

**Comment by syranide** [comment]
@sebmarkbage :+1:
