### ISSUE TITLE
questions on CoffeeScript static property demo in 0.13 beta release post

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/react#3450]
I'm somehow a fulltime CoffeeScript programmer.
Here's what I found in 0.13 beta release post:
http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

```coffee
div = React.createFactory 'div'

class Counter extends React.Component
  @propTypes = initialCount: React.PropTypes.number
  @defaultProps = initialCount: 0

  constructor: (props) ->
    super props
    @state = count: props.initialCount

  tick: =>
    @setState count: @state.count + 1

  render: ->
    div onClick: @tick,
      'Clicks: '
      @state.count
```

While it's exciting I got some questions on using static properties:

`propTypes` and `defaultProps` are becoming static properties, and `state` is now a property defined in the constructor. And this is even more clear in the ES6 demo.

```js
export class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};
  }
  tick() {
    this.setState({count: this.state.count + 1});
  }
  render() {
    return (
      <div onClick={this.tick.bind(this)}>
        Clicks: {this.state.count}
      </div>
    );
  }
}
Counter.propTypes = { initialCount: React.PropTypes.number };
Counter.defaultProps = { initialCount: 0 };
```

I found these are not updated in the 0.13 docs, but would like to talk more about them. Which properties are influenced? Which syntax do you recommend? Fat arrow or not?

**Comment by jimfb** [comment]
Now documented here: http://facebook.github.io/react/docs/reusable-components.html#es6-classes

We use fat arrow internally and in many docs.  Ultimately it's just syntax, and you need to decide what makes the most sense for you given your infrastructure and codebase.

**Comment by jiyinyiyong** [comment]
@jimfb Thanks. I will probably stick to CoffeeScript for the principle of "everything is an expression".
