### ISSUE TITLE
Wrong context warning? - 'Warning: owner-based and parent-based contexts differ'

### ISSUE THREAD

**Issue by davidagraf** [facebook/react#3451]
IMO: the warning ...

    Warning: owner-based and parent-based contexts differ (values: `context value` vs `undefined`) for key (foo) while mounting Child (see: http://fb.me/react-context-by-parent)

... in the following code is wrong. 

In the code, I define a root component with a context value. The root component show two different children dependent on a state variable. When the root switched from one child to another, the warning is shown.

Example on jsFiddle: http://jsfiddle.net/davidagraf/548u0o0a/

Run tested with React v0.13.1.

```JS
var Root = React.createClass({
  childContextTypes: {
    foo: React.PropTypes.string
  },
  getChildContext: function() {
    return {
        foo: "context value"
    };
  },
  getInitialState: function () {
    return {foo: false};
  },
  render: function() {
    if (this.state.foo) {
      return <Child/>;
    } else {
      setTimeout(function() { this.setState({foo: true}); }.bind(this), 1000);
      //return <Child/>;
      return <div>loading</div>;
    }
  }
});

var Child = React.createClass({
  contextTypes: {
    foo: React.PropTypes.string
  },
  render: function() {
    return <div>{this.context.foo}</div>;
  }
});

React.render(<Root/>, document.body);

```

**Comment by gaearon** [comment]
This seems to be correct.

In your code, `Child`'s context is taken from owner (`Root`). This is how 0.13 and previous versions work.

After 0.14, context will be taken from parent. In your example, `Child` has no parent. Thus it will receive no context.

Here's a modified example that doesn't work in 0.13 but *should* work in 0.14 once it's out:

```js
var ContextParent = React.createClass({
  childContextTypes: {
    foo: React.PropTypes.string
  },
  getChildContext: function() {
    return {
        foo: "context value"
    };
  },
  render() {
    return React.Children.only(this.props.children);
  }
});  

var Root = React.createClass({
  render: function() {
    return <ContextParent><Child/></ContextParent>;
  }
});

var Child = React.createClass({
  contextTypes: {
    foo: React.PropTypes.string
  },
  render: function() {
    return <div>{this.context.foo}</div>;
  }
});

React.render(<Root/>, document.body);
```

**Comment by zpao** [comment]
cc @jsfb - I'm not following the plans for context, can you confirm.

**Comment by davidagraf** [comment]
@gaearon Thanks for the explanation. Stupid question: why is 'Root' not the parent of 'Child' in my example? Is a component A a child of component B only if it is passed as the property 'children'?

**Comment by davidagraf** [comment]
I managed to get rid of the warning with the following code:

```Javascript
var Wrapper = React.createClass({
  childContextTypes: {
    foo: React.PropTypes.string
  },
  getChildContext: function() {
    return {
        foo: 'hello context'
    };
  },
  render: function() {
    return React.createElement(this.props.content);
  }
});

var Root = React.createClass({
  getInitialState: function () {
    return {foo: false};
  },
  render: function() {
    if (this.state.foo) {
      return <Wrapper content={this.props.content}/>
    } else {
      setTimeout(function() {
        this.setState({foo: true});
      }.bind(this), 1000);
      return <div>some div</div>;
    }
  }
});

var Child = React.createClass({
  contextTypes: {
    foo: React.PropTypes.string
  },
  render: function() {
    return <div>{(this.context.foo ? this.context.foo : 'no foo')}</div>;
  }
});


React.render(<Root content={Child}></Root>, document.body);
```

I am not sure why this doesn't produce a warning. Maybe, the direct children of a context changing component must be static. Anyway, it works :-).

**Comment by gaearon** [comment]
>Is a component A a child of component B only if it A is passed as the children property to B?

AFAIK, yes.

>I am not sure why this doesn't produce a warning. Maybe, the direct children of a context changing component must be static. 

I'm not sure either, perhaps @jsfb or @sebmarkbage can enlighten us!

Anyway, you don't really *need to* get rid of that warning. You can use old owner-based context throughout 0.13, and when 0.14 is out, change your code to use parent-based context and make 0.14 a minimal dependency. The warning just tells you that the code *will* break if you do nothing, but you don't have to jump through the hoops just to get rid of it.

**Comment by BinaryMuse** [comment]
I came across this GH issue while running into a similar problem and attempting to understand how parent-based contexts work (and trying to figure out if there's a bug hidden here). Here's the code I'm using to test, which can be found running against React v0.13.1 at http://jsfiddle.net/BinaryMuse/x5tkrtnk/:

```javascript
var obj = { val: "TEST_CONTEXT" };

function ownerContext(comp) {
  return comp._reactInternalInstance._currentElement._context.test;
}

function parentContext(comp) {
  return comp._reactInternalInstance._context.test;
}

var App, ComponentA, ComponentB;

App = React.createFactory(React.createClass({
  displayName: "App",
  
  childContextTypes: {
    test: React.PropTypes.object
  },
  
  getChildContext: function() {
    return { test: obj };
  },

  getInitialState: function() {
    return {
      value: false
    };
  },
  
  componentDidMount: function() {
    setTimeout(function() {
      console.log("Changing value...");
      this.setState({value: true});
    }.bind(this), 1000);
  },

  render: function() {
    return this.renderChild();
    //return React.DOM.div({}, this.renderChild());
  },

  renderChild: function() {
    if (!this.state.value) {
      return ComponentA();
    } else {
      return ComponentB();
    }
  }
}));

ComponentA = React.createFactory(React.createClass({
  displayName: "ComponentA",
  
  componentWillMount: function() {
    console.log("ComponentA willMount:", ownerContext(this), parentContext(this));
  },
  
  contextTypes: {
    test: React.PropTypes.object
  },

  render: function() {
    console.log("ComponentA render:", ownerContext(this), parentContext(this));
    return React.DOM.div();
  }
}));

ComponentB = React.createFactory(React.createClass({
  displayName: "ComponentB",
  
  componentWillMount: function() {
    console.log("ComponentB willMount:", ownerContext(this), parentContext(this));
  },
  
  contextTypes: {
    test: React.PropTypes.object
  },

  render: function() {
    console.log("ComponentB render:", ownerContext(this), parentContext(this));
    return React.DOM.div();
  },
}));

React.render(App(), document.getElementById('container'));
```

`App` renders `ComponentA` and, after one second, switches to `ComponentB`. It provides a context with a key `test`, and both child components declare a `contextTypes` with the appropriate value. Each of the child components log their owner-based and parent-based contexts.

As written above, running the app shows the following in the console:

```
ComponentA willMount: Object {val: "TEST_CONTEXT"}, Object {val: "TEST_CONTEXT"}
ComponentA render: Object {val: "TEST_CONTEXT"}, Object {val: "TEST_CONTEXT"}
Changing value...
react-with-addons.js:21560 Warning: owner-based and parent-based contexts differ (values: `[object Object]` vs `undefined`) for key (test) while mounting ComponentB (see: http://fb.me/react-context-by-parent)
ComponentB willMount: Object {val: "TEST_CONTEXT"}, undefined
ComponentB render: Object {val: "TEST_CONTEXT"}, undefined
```

`ComponentB` gets no context with a `test` key, but `ComponentA` does.

Changing the `render` method of `App` to wrap the child component in a simple `div` changes the console output to show:

```
ComponentA willMount: Object {val: "TEST_CONTEXT"}, Object {val: "TEST_CONTEXT"}
ComponentA render: Object {val: "TEST_CONTEXT"}, Object {val: "TEST_CONTEXT"}
Changing value...
ComponentB willMount: Object {val: "TEST_CONTEXT"}, Object {val: "TEST_CONTEXT"}
ComponentB render: Object {val: "TEST_CONTEXT"}, Object {val: "TEST_CONTEXT"}
```

Based on the explanation for @davidagraf's original issue, there are two things I don't understand:

1. In the example that is *not* wrapped by the `div`, why is `ComponentA` given the expected parent-based context, but when re-rendering `ComponentB` is not?
2. Ignoring question 1, if it's correct that in the non-div-wrapped example `ComponentB` is not receiving the right context because `App` really is not its parent as described above, why does wrapping it in a plain `div` suddenly provide it with the correct parent-based context? I understand that it is now deriving its context from its parent (the `div`), but why is the `div` providing the context, since given the above logic, it has no parent itself (and thus should not be passing one to the child)?

**Comment by gaearon** [comment]
I wonder if it's the same as #3404 and might have been fixed by #3494.
Can you verify this is still the case with `master`?

**Comment by BinaryMuse** [comment]
@gaearon Good call; looks like it's fixed on master. http://jsfiddle.net/BinaryMuse/pj4rf47t/

**Comment by spicyj** [comment]
Sorry about this – we'll make sure to get that in 0.13.2 if we do another minor release.

**Comment by xizhao** [comment]
I'm still getting this on 0.13.3.  Is this because owners are assigned when createElement is called?  Is there any way we can re-assign the owner after the fact?  

I can't throw mine in a wrapper because the child I am trying to render has already been created with props assigned.

**Comment by spicyj** [comment]
@xizhao No. In 0.14 this will work how you want it to.

**Comment by sonewman** [comment]
wow, i just lost 3 hours of my life to this issue. I'm glad it's fixed in 0.14, the sooner it is released the better!

**Comment by aim88** [comment]
On Jun 21, 2015 8:44 PM, "Sam Newman" <notifications@github.com> wrote:
>
> wow, i just lost 3 hours of my life to this issue. I'm glad it's fixed in
0.14, the sooner it is released the better!

**Comment by spicyj** [comment]
Next time, maybe don't use unstable, undocumented features if you don't want to run into trouble.

**Comment by shaurya947** [comment]
Could anybody please confirm the following?

1. In v0.13.3, context is passed only through the owner-ownee relationship (and not the parent-child relationship).
2. In v0.14 (whenever it comes out), this is to be changed. That is, context will only be passed through the parent-child relationship.
3. The owner-ownee relationship tree is a subset of the parent-child relationship tree. If this is true, it would be great if anybody could shed a little more light on this.

**Comment by jimfb** [comment]
@shaurya947: 1 and 2 are correct.  3 is usually but not always true (it is possible for an owner to do odd things with the elements it creates, like render them somewhere other than as a child).  Also, the order of elements/context-assignments may be different in the owner-ownee vs parent-child relationship.  To a first order approximation, it's correct to say that owner-ownee is a subset of parent-child, but it's not strictly true and there are corner cases.  Also, context is not a supported feature.

**Comment by shaurya947** [comment]
Thanks @jimfb ! That helps. Could you give / point to an example where 3 might not be true? I tried to picture one based on the description you gave but couldn't see it clearly.
