### ISSUE TITLE
HTMLtoJSX is not defined on HTML to JSX converter page

### ISSUE THREAD

**Issue by pirate** [facebook/react#3455]
![screen shot 2015-03-18 at 4 12 31 pm](https://cloud.githubusercontent.com/assets/511499/6721357/9d8d38c8-cd89-11e4-8d8e-6bf1de04c12c.PNG)

Edits were made last week to this page, maybe it was broken accidentally?
https://github.com/facebook/react/blob/gh-pages/html-jsx.html

**Comment by cody** [comment]
I guess you use https, but the page loads a script over http and that gets blocked.

I made a pull request to fix this #3456. I couldn't test it, so fingers crossed that it is right.

**Comment by zpao** [comment]
@Daniel15 I though we were going to remove this page and let this live entirely in the react-magic repo?

**Comment by Daniel15** [comment]
@zapo The scripts live in the react-magic repo, but I think we'll keep the page on the React site as it's still really useful there.
