### ISSUE TITLE
HTML string in this.state occasionally escaped

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/react#3457]
I was using using React togather with a small rich text editor named pen:
https://github.com/sofish/pen
and here my code:

```coffee

  getInitialState: ->
    text:         @props.text

  loadPen: ->
    pen = new Pen
      editor: @refs.text.getDOMNode()
      textarea: '<textarea name="content"></textarea>'
      list: ['bold']
      stay: false
    pen.setContent @props.text
    @refs.text.getDOMNode().focus()
    pen.on 'change', (content) =>
      @onChange content.trim()
    return pen

  onChange: (content) ->
    console.log content # yes, I found it to be HTML every time
    @setState text: content
    time.delay 100, =>
      console.log @state.text # <--- somtimes @state.text is escaled,
      # like a string as `innerHTML` changed to another as `textContent`
    #  @state.text = content # currently my only fix is to rewrting that property again
```

I don't know how to debug into React and find out what's really happening, but does React do anything like that, escaping HTML state property internally?

**Comment by syranide** [comment]
This is not React but whatever editor you are using, specifically:
```
    console.log content # yes, I found it to be HTML every time
    @setState text: content
```

You're even saying it's HTML yet you put it in text, so that's where your escaped text is coming from.

**Comment by jiyinyiyong** [comment]
Thanks, I just want to make sure React doesn't rewrite state silently.

Hope I didn't misspell any English words.
That's the only `setState` call in the component. And there are  two `console.log`s. They are supposed to print the some string(which is maybe `"<p>text<p>"`), but sometimes the second one is different(like `text`, tags are gone).

**Comment by spicyj** [comment]
React doesn't do anything special to your state properties. If you put HTML in, you'll get HTML out. If you can make a minimal repro case that shows this isn't the case I'd be happy to take a look… but React doesn't do anything to your state properties so I'm fairly confident that's not the case.
