### ISSUE TITLE
More detail in communication documentation. Best practices for Grandparent <> Grandchild?

### ISSUE THREAD

**Issue by daedelus-j** [facebook/react#3461]
http://facebook.github.io/react/tips/communicate-between-components.html

'For communication between two components that don't have a parent-child relationship, you can set up your own global event system.'

So far I've really enjoyed React. It's conducive to modularize your components. However, as you modularize your components, it gets harder to communicate. A global event system doesn't scale and essentially couples components that shouldn't be coupled. A simple example, a faceted navigation sidebar containing two subviews. Some filters and a search bar, and a list of things:

SibebarView
| -- Filters
|     | -- Search Input
|     | -- Filter Button
| -- List View

In essence, an event stream from your search input should update the list. By the advice above, it seems like you'd say create a singleton EventEmitter which the search input : 

```
// search-input.js
ee.emit('search:update', input.value);

// sidebar.js
ee.on('search:update', searchHandler);
```
As you can see, this is a very specific event which the SidebarView has to know about. 

Also let's say you have a global search input. Over time it seems like you have to be increasingly specific about event names. 

I have a feeling Flux is supposed alleviate this problem somehow, but if so is there any way we can give some more detail here and/or point people in the right direction? Seems like a common use case.

**Comment by gaearon** [comment]
Flux is indeed one way of solving this problem. I created a PR to mention it.

**Comment by daedelus-j** [comment]
@gaearon thanks! for others' reference: https://github.com/facebook/react/pull/3612

**Comment by daedelus-j** [comment]
@gaearon one step further might be nice to throw in a quick if-you-understand-a-little-about-flux example.
