### ISSUE TITLE
ReactServerRendering.renderToString fails on JDK 1.6

### ISSUE THREAD

**Issue by heltonvalentini** [facebook/react#3476]
I'm trying to use React on server-side on a Java project.
Unfortunately we're tied on jdk 1.6 for this project so we can't use Nashorn. Since jdk 1.6 has it's own JavascriptEngine I thought it was good enough to give it a shot.
Everything was fine until I tried to render a component with more than one children. Whenever a component has more than one children React renders them randomly.

Here's is a simple test case.

```java
import java.io.FileReader;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

public class Test {
	private ScriptEngine se;

	// Constructor, sets up React and the Component
	public Test() throws Throwable {
		ScriptEngineManager sem = new ScriptEngineManager();
		se = sem.getEngineByName("JavaScript");
		// React depends on the "global" variable
		se.eval("var global = this");

		// polyfill
		se.eval(new FileReader("es5-shim.js"));
		se.eval(new FileReader("es5-sham.js"));
		// eval react.js
		se.eval(new FileReader("react-0.13.1.min.js"));
		// This would also be an external JS file
		
		String component = ""
				+ "var BackButton = React.createClass({"
				+ "render: function() {"
				+ "return ("
				+ "React.createElement(\"a\", {href: this.props.url, className: \"Button BackButton\"}, \"first\", \"second\", this.props.text)"
				+ ")}});";
		
		se.eval(component);
	}

	// Render the component, which can be called multiple times
	public String render(String text) throws Throwable {
		String render = "React.renderToString(React.createFactory(BackButton)({"
				+ " text: '" + text + "'," + " url: 'www.google.com'" + "}))";
		
		return se.eval(render).toString();
	}

	public static void main(String args[]) {
		try {
			  Test t2 = new Test(); 
			  System.out.println(t2.render("third"));
		} catch (Throwable e) {
			  System.out.println("e: " + e.getMessage());
		}
	}

}
```

Given this example React.renderToString generates the following markup:

```html
<a class="Button BackButton" href="www.google.com" data-reactid=".1cxxsje631f" data-react-checksum="-305574598">
    <span data-reactid=".1cxxsje631f.1">second</span>
    <span data-reactid=".1cxxsje631f.2">third</span>
    <span data-reactid=".1cxxsje631f.0">first</span>
</a>
```
Spent some time yesterday and today trying to figure this out. Narrowed things down until I reach `ReactReconciler.mountComponent`. For some reason children are being called on `second`,`third`,`first` order.

Appreciate any help help or ideas for what could be causing this.

**Comment by spicyj** [comment]
React relies on engines using object key insertion order for iteration, which practically all engines do. Guessing yours doesn't. You could try using Rhino, perhaps?

Closing as it's unlikely we'll change anything in React to support this use case.

**Comment by heltonvalentini** [comment]
Tried to run it on Rhino but got the same result. Do you how I could run a test to check if engines are available ?

**Comment by heltonvalentini** [comment]
Tried to run it on Rhino but got the same result. Do you know how I could run a test to check if object key insertion is available ?
As far as I know loading `es5-shim.js` and `es5-sham.js` provides everything React world need to run.
Since it would polyfill the following React needs:
* `Array.isArray`
* `Array.prototype.every`
* `Array.prototype.forEach`
* `Array.prototype.indexOf`
* `Array.prototype.map`
* `Date.now`
* `Function.prototype.bind`
* **`Object.keys`**
* `String.prototype.split`
* `String.prototype.trim`
* `Object.create`
* `Object.freeze`
