### ISSUE TITLE
Changing placeholder on <input> causes onChange in IE

### ISSUE THREAD

**Issue by aronwoost** [facebook/react#3484]
Check: http://jsfiddle.net/L90hzdmo/5/

Tested in IE10. Likely related to #3377.

**Comment by yaycmyk** [comment]
We're having issues with this too and had to put in a workaround to deal with it. @zpao Is this on your roadmap?

**Comment by jmca** [comment]
Having the same issue with `placeholder` on `textarea` using IE 11.0.

**Comment by patrickkempff** [comment]
I have the same issue as @jmca, when adding a placeholder a textarea, with no value, the onChange event is fired.

**Comment by nd-lqj** [comment]
I hava the same issue. A input with a placeholder and no value, the onChange event is fired.
