### ISSUE TITLE
ReactTransitionGroup fails when given a Factory as its component prop

### ISSUE THREAD

**Issue by masonicboom** [facebook/react#3492]
Passing a factory causes "TypeError: undefined is not an object (evaluating 'type.prototype.mountComponent')".

In reference to ReactTransitionGroup, the docs state "Note: Prior to v0.12, when using DOM components, the component prop needed to be a reference to React.DOM.*. Since the component is simply passed to React.createElement, it must now be a string. Composite components must pass the factory." (https://facebook.github.io/react/docs/animation.html).

Test case at https://jsfiddle.net/wjv7o50k/2/.

Test code is:
```javascript
var CompositeClass = React.createClass({
    render: function() {
        return null;
    }
});
var CompositeFactory = React.createFactory(CompositeClass);

var ReactTransitionGroup = React.createFactory(React.addons.TransitionGroup);

var BugClass = React.createClass({
    render: function() {
        return ReactTransitionGroup({ component: CompositeFactory }, []);
    }
});
var BugFactory = React.createFactory(BugClass);

React.render(BugFactory(), document.body);
```

UPDATE: it looks like the docs might just be wrong; passing in the Class rather than the Factory seems to work.

**Comment by spicyj** [comment]
Yeah, the docs are just wrong here. Care to send a PR to fix?

**Comment by zpao** [comment]
Oops, my mistake!

**Comment by jimfb** [comment]
I think this was fixed.  We don't have any notes about 0.12 anymore, and I don't see "factory" mentioned anywhere on the page.

**Comment by zpao** [comment]
#5065 fixed this
