### ISSUE TITLE
Support asynchronous wrappers of Transaction?

### ISSUE THREAD

**Issue by snowmantw** [facebook/react#3493]
Hello I'm reading React.js and trying to extend it. One thing I've noticed is although wrappers of Transaction are guarantee to be executed pre- and post- the performing method, there seems no waiting mechanism for asynchronous wrapper functions. So if APIs are asynchronous, the `initialize` and `close` may fail to keep the order correctly, especially when the previous wrapper is still waiting the asynchronous result and the second one would start itself (from Transaction.js#L168 it looks like just a plain function call, there is no waiting code anywhere).

From the current React.js there are no too much transaction instances, so the problem may be not serious. However, from the nature of Transaction it is a extendable and standalone component should not bind with DOM & existing use cases, so I think it should be general enough to deal with the possible cases (and from the design principle of new DOM APIs it is very possible).

(Sorry if I fired a duplicated issue, but I've searched issues and found no similar cases. If it's duplicated please close it)

**Comment by jimfb** [comment]
Sorry, I'm not entirely sure what this issue is requesting, but `Transaction` is an internal API and it seems to meet our internal use cases, so I'm going to close this out.
