### ISSUE TITLE
ReactTransitionGroup: setState in _handleDoneLeaving is problematic

### ISSUE THREAD

**Issue by fvanclef** [facebook/react#3497]
Hi, 

I am implementing a custom animation on svg and I have found a problem with this code in the _handleDoneLeaving function of ReactTransitionGroup

``` javascript

  _handleDoneLeaving: function(key) {
    var component = this.refs[key];

    if (component.componentDidLeave) {
      component.componentDidLeave();
    }

    delete this.currentlyTransitioningKeys[key];

    var currentChildMapping = ReactTransitionChildMapping.getChildMapping(
      this.props.children
    );

    if (currentChildMapping && currentChildMapping.hasOwnProperty(key)) {
      // This entered again before it fully left. Add it again.
      this.performEnter(key);
    } else {
      var newChildren = assign({}, this.state.children);
      delete newChildren[key];
      this.setState({children: newChildren});  // where the problem 
    }
  },

```

When there are many children to remove only the last one is actually removed. The reason is because setState is not updating immediately the children list, the assignment of this.state.children to newChildren is still referencing the full list for the next call. In fact only the last remove is effective.

Here is a jsfiddle example 

http://jsfiddle.net/z4go3Lw3/4/

The initlal view is about 5 green circles, when clicking on the change button, 5 new circles must be added and the previous 5 must be removed. But only one is removed

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by jquense** [comment]
this was actually been fixed somewhere along the way :)
