### ISSUE TITLE
Add comment in front-page markdown example about XSS

### ISSUE THREAD

**Issue by zpao** [facebook/react#3501]
Since copy+pasting our code makes it too easy for people to XSS themselves, lets just add a comment in there about it.

**Comment by AnSavvides** [comment]
PR at #3508 - let me know if that's what you had in mind!

**Comment by jsfb** [comment]
@zpao My intuition is that it makes more sense to fix the example (call a sanitization library) or to change the example completely (demonstrate something else that is safer).  It looks really bad to have a security warning on the homepage of the react site.  Makes it seem like our framework encourages unsafe operations, rather than a safe-by-default way of doing things.

**Comment by cmwelsh** [comment]
Should switch the demo to use a different library like markdown-js that escapes everything and doesn't support HTML:

https://github.com/evilstreak/markdown-js

**Comment by brigand** [comment]
markdown-js looks good.  First attempt: http://jsbin.com/movaquyexo/2/edit?js,output

```js
function renderJsonML(node){
  if (typeof node === "string") {
    return React.createElement("span", null, node);
  }
  
  var [tag, props, ...children] = node;
  
  if (typeof props === "string" || Array.isArray(props)) {
    children = [props].concat(children);
    props = null;
  }
  
  // special case
  if (tag === "em" && children[0] === "INPUT") {
    return <input defaultValue="default value" />
  }
  
  var childElements = Array.isArray(children)
    ? children.map(renderJsonML)
    : renderJsonML(children)
  
  return React.createElement(tag, props, childElements);
}

class Markdown {
  shouldComponentUpdate(nextProps){
    return nextProps.value !== this.props.value;
  }
  
  render(){
    var value = this.props.value;
    var md = markdown.markdown;
    var jsonMl = ["div", ...md.toHTMLTree(md.parse(value)).slice(1)];
    return (
      <div className="markdown">{renderJsonML(jsonMl)}</div>
    );
  }
}

const EXAMPLE_MARKDOWN = `
Some example markdown.  This uses [markdown-js][1] to awesomely render **markdown**.

Make some changes like wrapping something in *s to see the changes.

There's also a special case for \`*INPUT*\`, which renders an input.

*INPUT*

Changing the other paragraphs won't mess with the <input>.

[1]: https://github.com/evilstreak/markdown-js
`.trim();
      
class App extends React.Component {
  constructor(props){
    this.state = {
      markdown: EXAMPLE_MARKDOWN
    };
  }
  
  handleChange(e){
    var markdown = e.target.value;
    this.setState({markdown});
  }
  
  render(){
    return (
      <div>
        <textarea 
          onChange={e => this.handleChange(e)}
          value={this.state.markdown} rows={12} style={App.styles.textarea} />
        <Markdown value={this.state.markdown} />
      </div>
    );
  }
}

App.styles = {
  textarea: {
    width: "95%"
  }
}

React.render(<App />, document.body);
```

Code licensed [BSD](https://github.com/facebook/react/blob/master/LICENSE) if someone wants to turn this into a coherent example; I've signed the CLA.

**Comment by AnSavvides** [comment]
That's a good suggestion too :) @zpao - what are your thoughts? I'm happy to change the example to use [markdown-js](https://github.com/evilstreak/markdown-js) like people have suggested above.

@brigand nice example usage :+1:

**Comment by zpao** [comment]
Uh yea, that sounds fine to me. This behavior is definitely non-standard markdown but it's an example so not a big deal. We should probably do the same for the tutorial while we're here. And it's on cdnjs so that's all pretty easy: https://cdnjs.com/libraries/markdown.js

**Comment by spicyj** [comment]
Just going to use **marked** instead, which I'm already familiar with and has an option to sanitize input.
