### ISSUE TITLE
Please return us autobinding in classes

### ISSUE THREAD

**Issue by deser** [facebook/react#3509]
Hello guys,
react 13 is really amazing but I think it has small inconvenience.
In es6 classes we've lost very pretty functionality: autobinding event callbacks to owner. I very struggle with this functionality because every solution that react recommends is awful. We really need to bind to this owner almost every event callback and there is no magic as it is written in react blog. Please return this feature in next release.
Thank you!

**Comment by camspiers** [comment]
Something like this might work:

```javascript
function autobind(instance) {
  Object.keys(instance.constructor.prototype).forEach(f => {
    instance[f] = instance.constructor.prototype[f].bind(instance);
  });
}

class Something extends React.Component {
  constructor() {
    super();
    autobind(this);
  }
}
```

**Comment by Dignifiedquire** [comment]
There is also lodashd [`bindAll`](https://lodash.com/docs#bindAll) method which could do this for you.

**Comment by spicyj** [comment]
ES7 will likely include [class property initializers](https://gist.github.com/jeffmo/054df782c05639da2adb) and you'll then be able to specify your method with an arrow function to autobind it:

```
class Foo extends React.Component {
  render() {
    // ...
  }
  handleChange = (e) => {
    // ...
  }
}
```

**Comment by spicyj** [comment]
We're unlikely to add any magic specifically to React for this though – the new syntax should be enough.

**Comment by zpao** [comment]
FYI, you are not forced into using ES6 classes. `React.createClass` still exists with autobinding and will continue to exist for the foreseeable future.

ES6 classes intentionally don't have support for things the language doesn't support.

**Comment by deser** [comment]
Guys, 
none of the solution works because every es6 class method isn't enumerable. Object.keys returns empty array.

**Comment by camspiers** [comment]
@deser you are right, I just had a look at the spec, and class methods are not enumerable. If binding in the constructor is too painful, @zpao's recommendation to use `React.createClass` is probably the best option in the meantime before class property initializers are supported.

**Comment by steinitz** [comment]
@camspiers - your sample code works well.  Bravo.  Thank you.

I extended React.Component and put a version of your code there.  Now further extended classes don't need to worry about the binding issue at all.

The only enhancement I made was handling an exception if, for some unexpected reason, a key can't be bound to this.

Thanks again.

**Comment by steinitz** [comment]
Oops spoke too soon.  With inherited classes @camspiers helpful technique stopped working.  However I was able to get it working again by using a different technique to get the method names:
```
function getMethodsForInstance (instance)
{
    var result = [];
    for (var m in instance) 
	{
        if ("function" == typeof instance [m]) 
		{
            result.push (m)
        }
    }
    return result;
}
```

**Comment by brantwedel** [comment]
It may be that I have been using babel for too long, but I was under the assumption that es6 auto bound class member functions (checked and it is the spec to do so) ie:
```
class Something extends Anything {
    constructor() {
        this.reallyDontWantToAutoBindForPerformanceOrWhatEver = function() {
            let isAutoBound = false;
        }
    }
    someFunction() {
        this.isAutoBound = true;
    }
}
```

The fact that Reacts "ES6" class syntax deviates from ES6 spec in this way seems very confusing and unnecessary. I might understand the backwards compatibility reasons for keeping it this way, but none of the documentation should refer to it as "ES6 class syntax" with this fairly significant deviation.
