### ISSUE TITLE
PropTypes: Hook to add optional `help_text`

### ISSUE THREAD

**Issue by cooncesean** [facebook/react#3510]
It would be neat if these declarations could take [`help_text`](https://docs.djangoproject.com/en/1.7/ref/models/fields/#help-text) -- would go a long ways to help others understand what the prop is for and how it is used is the component.

Low priority, just food for thought :)

**Comment by iamdustan** [comment]
Would jsdoc work for this?

**Comment by fkling** [comment]
How would you use it? What are the advantages over simply using comments?

**Comment by iamdustan** [comment]
I know how *I* would use it, @fkling :wink:

**Comment by fkling** [comment]
@iamdustan: :) 

I can see some use cases, but personally I prefer to leverage existing concepts (e.g. comments) instead of introducing new API's (which have to be learned and remembered). Writing a comment is probably less friction for a developer than calling an API.

It may also make a bit more difficult to write custom validators (unless the help text is really just a property on the function).

I'm not necessarily against this, I just want to consider all angles and ideally reach a canonical way to document React components (see https://github.com/reactjs/react-docgen).

**Comment by iamdustan** [comment]
100% with you on that goal (as I still commit to my own version of react-docgen). I *will* be looking at integrating with react-docgen and deprecating my project in the relatively near future.

I would hope/expect that between the component name, property name, and property type and/or default value *should* provide enough affordance in almost all situations to describe the usage.

**Comment by cooncesean** [comment]
Thanks for the feedback/discussion guys. Fairly new to ReactJS, but here's how we would use it (in model definitions in Django - a Python web framework).

```python
class Author(models.Model):
    """An author can write many books."""
    name = models.TextField(help_text="The full name (first and last) of the author.")
    books = models.ManyToMany(
        Book, 
        help_text="A many to many relationship between an author and the books they have written." 
    )
    ...
```

Not only is this useful for other team members, who can read the `help_text` and quickly grok what the field is and what it is used for, but this text is used throughout the project in forms, in the admin, in documentation, etc. Its the single source of truth (for documentation purposes) of that field.

Anyway, its a nice pattern that *could* be useful in components:

```coffee
module.exports = React.createClass

  displayName: "Autocompleter Component"

  propTypes:
    maxResults: React.PropTypes.integer(help_text="The max number of results the autocompleter can render.")
    someAmbiguousProperty: React.PropTypes.func(help_text="Some descriptive text.")
```

I agree, inline comments totally work in this case (and our team is using that as a current convention) -- just thought it was a nice pattern that could be useful here :)

**Comment by jeffhandley** [comment]
I too am in the camp of using comments rather than extending the API for documentation purposes.  When I saw `help_text`, I figured this would be for plumbing through form field info text or something and I could see people trying to use the new API for purposes like that which might not fit the intention.

**Comment by jimfb** [comment]
PropTypes is largely getting replaced by Flow, so we aren't actively developing this feature.  Even if we were developing proptypes, we most likely wouldn't add this functionality.  Recommendation is to just use comments/docs.

**Comment by plasticine** [comment]
@jimfb this seems like a pretty big statement to me—propTypes are a pretty significant part of the value proposition for developer happiness that react poses (for my team at least).

Would be great if you could expand on this; is there more information about this decision somewhere?

Suggesting using flow seems like a pretty big leap also—propTypes are incredibly low friction, and very quickly provide value—adding a completely new tool and workflow (ha!) seems like an odd choice. 

Thanks <3

**Comment by jimfb** [comment]
@plasticine Having each framework define it's own notion of proptypes is not a scalable approach.  We switched to ES6 classes for a similar reason (having each framework define their own notion of classes, mixins, etc - is not scalable for the community).  As generalized tools become available, our framework-specific hacks should fade away.

We've been pretty consistent about our messaging on this point:
 * https://github.com/facebook/react/issues/5215#issuecomment-149318908
 * https://github.com/facebook/react/issues/5080#issuecomment-146373158
 * https://github.com/facebook/react/issues/5314#issuecomment-152049117

**Comment by plasticine** [comment]
@jimfb Fair enough, thanks for the clarification.
