### ISSUE TITLE
Integration with knockout

### ISSUE THREAD

**Issue by lovey599** [facebook/react#3522]
I want to use React in V,and use Knockout in M.
How can I Integration with it?
Thanks!

**Comment by pfazzino** [comment]
Why? Knockout is primarily a data binding library and manages changing your Dom state as you update your model. React leverages state & props to generate views from your data/model. What do you think knockout will add here?

**Comment by lovey599** [comment]
@pfazzino As you said,React was used to generate views from data/model.But, did you ever consider when the data/model changed,how to update the views?Therefore, I want to use knockout to automatically update the views.

**Comment by pfazzino** [comment]
I think your missing one of the key points of react (one of the secrets is in the name!). React re-renders the DOM for you every time your state changes. You don't need to do anything to update your views, you just mutate your state and the ROM reflects the changes. Knockout has nothing to offer here.

**Comment by lovey599** [comment]
@pfazzino Thank you very much, I'll try it.
Best wish!
