### ISSUE TITLE
Invariant Violation: Trying to release an instance into a pool of a different type

### ISSUE THREAD

**Issue by hollandben** [facebook/react#3526]
I am currently working on rendering a simple React application on the server. The application renders content fine using the `renderToString` method, but during load testing, I'm seeing this error occasional occur:

    Invariant Violation: Trying to release an instance into a pool of a different type

I've tracked the error message down to the [PooledClass.js](https://github.com/facebook/react/blob/0.13-stable/src/utils/PooledClass.js#L71) file but am struggling to understand what the pool is doing and why this error would be thrown.

Does anybody have a good description about how to pools work that I could read? Or even better, any hints about what could be causing this?

**Comment by spicyj** [comment]
Any chance you can get a full stack trace for the error? We use pooling to reuse objects instead of creating new ones every time.

**Comment by hollandben** [comment]
OK thanks - I'll post that in the morning (I'm in the UK)

**Comment by hollandben** [comment]
An update on this - what we were trying to do was render a basic ReactJS application on the server via Nashorn in Java 8. Turns out trying to debug problems within the engine is really damn difficult and it's hard to get any decent error messages back.

During the load testing, we found that ~0.1% of requests were dropped due to the referenced error being thrown. We suspected it was possibly something to do with GC as it was happening pretty consistently but had no luck with that. A few people suggested it may have been concurrency issues but sadly we didn't have to the time to properly dig things.

It was a spike into using ReactJS and Nashorn together, but looks like we'll have to abandon the project. Thanks for looking at this issue.

**Comment by spicyj** [comment]
Sorry to hear that. Sounds like Nashorn may be buggy as I haven't heard about anyone having this problem in other engines.

**Comment by ggd543** [comment]
@hollandben Could you give me the test case. I guess the reason is about the concurrency  of `javax.script.ScriptEngine`. See [here](http://stackoverflow.com/a/31091590/351545)

**Comment by hollandben** [comment]
@ggd543 it was for a company I now longer work for, so unfortunately I can't provide the code
