### ISSUE TITLE
Add ability to find dom component by prop value in the ReactTestUtils?

### ISSUE THREAD

**Issue by ryanzec** [facebook/react#3528]
In order to make selectors more durable within selenium tests, I will generally add in `data-qa` attributes to any element that needs to be selected.  Developers are free to change classes and IDs as needed but know not to touch or move when refactoring `data-qa` attributes.  It would be nice to allow my unit tests to use the same `data-qa` attribute to select elements as my integration/selenium tests use.  The issue is that currently there is no way to do that with the ReactTestUtils.

I have a test helper object that contains a bunch of things to help with testing my react code.  Two of the methods are as follows:

``` javascript
scryRenderedDOMComponentsWithProp: function scryRenderedDOMComponentsWithProp(root, propName, propValue) {
    return reactTestUtils.findAllInRenderedTree(root, function(inst) {
        var instancePropValue = inst.props[propName];

        return (
            reactTestUtils.isDOMComponent(inst)
            && instancePropValue
            && (' ' + instancePropValue + ' ').indexOf(' ' + propValue + ' ') !== -1
        );
    });
},

findRenderedDOMComponentWithProp: function findRenderedDOMComponentWithProp(root, propName, propValue) {
    var all = this.scryRenderedDOMComponentsWithProp(root, propName, propValue);

    if (all.length !== 1) {
      throw new Error('Did not find exactly one match (found: ' + all.length + ') for prop  ' + propName + ' : ' + propValue);
    }

    return all[0];
}
```

This seems like a useful feature to me and was wondering if there is enough interest into this type of functionality to create a PR to add it directly into the ReactTestUtils?

**Comment by mistadikay** [comment]
I'm also interested in this kind of feature. Currently when trying to access prop of an instance in `findAllInRenderedTree ` I get a warning that I shouldn't access props this way.

**Comment by gaearon** [comment]
@mistadikay What warning are you referring to?

**Comment by mistadikay** [comment]
@gaearon I wish I remembered, it was almost 2 years ago 😅

**Comment by gaearon** [comment]
I believe Enzyme probably provides this: http://airbnb.io/enzyme/

I'd encourage everyone to check it out. I don't see us expanding the current TestUtils APIs since they're a pain to work with and people tend to prefer Enzyme.
