### ISSUE TITLE
wrong function

### ISSUE THREAD

**Issue by ghostcode** [facebook/react#3536]
http://facebook.github.io/react/docs/multiple-components.html  in this page :

```
var Avatar = React.createClass({
  render: function() {
    return (
      <div>
        <ProfilePic username={this.props.username} />
        <ProfileLink username={this.props.username} />
      </div>
    );
  }
});

var ProfilePic = React.createClass({
  render: function() {
    return (
      <img src={'http://graph.facebook.com/' + this.props.username + '/picture'} />
    );
  }
});

var ProfileLink = React.createClass({
  render: function() {
    return (
      <a href={'http://www.facebook.com/' + this.props.username}>
        {this.props.username}
      </a>
    );
  }
});

React.render(
  <Avatar username="pwh" />,
  document.getElementById('example')
);
```

last function __React.render__ is wrong! should be __React.renderComponent__

**Comment by spicyj** [comment]
We renamed it to React.render several releases ago. Please consider keeping up to date with new versions.

**Comment by ghostcode** [comment]
@spicyj  o yes,but it make me confused:

```
var ProfileLink = React.createClass({
  render: function() {
    return (
      <a href={'http://www.facebook.com/' + this.props.username}>
        {this.props.username}
      </a>
    );
  }
});
```

```
React.render(
  <Avatar username="pwh" />,
  document.getElementById('example')
);
```

this two __render__ what's the different?

**Comment by jviereck** [comment]
The first `render: function()` definition on `ProfileLink` describes what the rendering of the class `ProfileLink` will look like. The second `React.render` takes as first input argument what you want to render (as described by your JSX markup) and as second argument where your output should go (in this case it should end up in `document.getElementById('example')`). To construct the content of `document.getElementById('example')` the `ProfileLink#render` method is called. Hope this helps you :)

**Comment by ghostcode** [comment]
@jviereck thanks,i know it now
