### ISSUE TITLE
Allow marking an array as "static"

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#3538]
I expected there to be an issue for this already, but couldn't find it. Apologies if this a dupe.

Occasionally it is useful to put a few elements in an array within render, when conditionally building different bits of the view.
React will issue a warning whenever an array is used that doesn't have keys - even if the author knows that this array is literal, and therefore doesn't require keys.

``` js
var label = "Label";
if (this.props.important) {
  label = ["Label", <Tag text="important" />];
}
return <div>
  <h3>{label}</h3>
  <p>{this.props.body}</p>
</div>
```

In this example, React will warn about lack of keys, even though they're not needed.

One option would be to extend `React.addons.createFragment` to accept an array, and use the indexes as keys.

``` jsx
label = React.addons.createFragment(["Label", <Tag text="important" />]);
```

**Comment by syranide** [comment]
+1 I've run into this a few times myself.

**Comment by monsanto** [comment]
yes please

**Comment by zpao** [comment]
This fits in well with the idea of frags. For example, I think we want to make this possible:

```js
label =
  <frag>
    Label
    <Tag text="important" />
  </frag>;
```

I'm not sure if we want to do it with another call like this, but the idea is definitely in line with what we're interested in.

**Comment by syranide** [comment]
@zpao  :+1: I currently have that by overloading `React.createElement` for now :)

**Comment by jquense** [comment]
is the `<frag/>' syntax a proposed thing somewhere? It seems to solve a bunch of issues (like conditionals with arrays of elements) but I don't think i've seen any mention or timeline on it? Is there a place I could look for more info?

**Comment by zpao** [comment]
#2127 is the place we've been tracking frags.

**Comment by snit-ram** [comment]
:+1: That's a common use case here at Yahoo, and we've been forcing keys.
This would be a nice addition

**Comment by syranide** [comment]
FYI, I'm currently using a utility based on `createFragment` for this purpose.

**Comment by jquense** [comment]
for folks interested this is what we came up with in the meantime and it works nicely for us: https://github.com/jquense/babel-plugin-jsx-fragment

**Comment by glenjamin** [comment]
I've recently discovered a fairly low tech way of doing this:
```jsx
(<div><A /><B /><C /></div>).props.children
```

Haven't decided yet whether I actually like this, but it does seem to work nicely.

Would a PR that allows arrays in createFragment get any traction?

**Comment by gaearon** [comment]
Seems like https://github.com/facebook/react/pull/10783 and https://github.com/facebook/jsx/issues/84 will address it.

**Comment by gaearon** [comment]
https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

Starting with React 16.2, you can do this now:

```js
var label = "Label";
if (this.props.important) {
  label = (
    <React.Fragment>
      Label
      <Tag text="important" />
    </React.Fragment>
  );
}
return (
  <div>
    <h3>{label}</h3>
    <p>{this.props.body}</p>
  </div>
)
```

or, when the tools catch up with new syntax support,

```js
var label = "Label";
if (this.props.important) {
  label = (
    <>
      Label
      <Tag text="important" />
    </>
  );
}
return (
  <div>
    <h3>{label}</h3>
    <p>{this.props.body}</p>
  </div>
)
```
