### ISSUE TITLE
Generic iterable data for ReactDOMComponent CSS styles

### ISSUE THREAD

**Issue by cigitia** [facebook/react#3542]
Currently, React supports only regular JavaScript objects for `ReactDOMComponent`s' style props, using their enumerated keys:

    divStyle = {color: "white"};
    React.createElement("div", {style: divStyle}, "…")

But it would be wonderful if it could also support generic data for CSS styles through, e.g., the iterable interface. That would enable Immutable.js and ClojureScript data structures to be directly used as their styles:

    divStyle = Immutable.Map({color: "white"});
    React.createElement("div", {style: divStyle}, "…")

Currently, this necessitates converting the generic data into regular JavaScript style objects for every styled element for every render, which is pretty wasteful.

In general, it's extremely useful to be able to express styles as generic data, especially persistent immutable data structures, in order to let the end user manipulate the data in the application's UI (e.g., for end-user UI themes), to serialize the data, and to dynamically merge and manipulate the data as needed at runtime. 

[React Native already supports the last sort of thing with merging `StyleSheet`s](https://facebook.github.io/react-native/docs/style.html), but that's not yet supported in regular React, and it'd be even better for serializability and manipulability if generic style data could be used.

Potential problems:

* This suggestion might or might not slow down React reconciliation or rendering.
* React Native already has a `{style: [styleObject1, styleObject2]}` standard syntax, used for merging style objects together. Unless that is revised (e.g., by adding a `StyleSheet.merge` method and having people use that instead), it may not be possible to also support generic style data in React Native, which might create too great of an API mismatch between React and React Native.

Nonetheless, I think generic style data are quite important, and I'm already using them copiously, especially for UI themes.

[Somewhat related to #3059.]

**Comment by garrrio** [comment]
React CSS in JS presentation by Christopher Chedeau.

http://blog.vjeux.com/2014/javascript/react-css-in-js-nationjs.html

See the m() function and see this repo

https://github.com/Sitebase/cssinjs for an inspiration.

I've been using this for a while and it works awesome!

**Comment by cigitia** [comment]
@garrrio `m()` and the `cssinjs` project uses regular JavaScript objects (POJOs) to express CSS styles, which `ReactDOMComponent`'s `style` prop already supports anyway. This issue is about being able to directly use other kinds of data (e.g., persistent immutable data structures like those from Immutable.js, ClojureScript maps) that support a generic interface (e.g., Iterable) in `ReactDOMComponent`'s CSS styling. (Since version 0.13, React already sort of does the same thing, supporting generic iterables as element children.)

Persistent data structures like Immutable.js, ClojureScript, and Mori allow people to similar things to `m()`, but so much more, without completely copying over objects every time.

As far as I can tell, CSS-style-attribute rendering and reconciliation both simply iterate over style objects' keys using `for`…`in` loops already; this probably would be pretty similar. What worries me more is if it would induce a mismatch with React Native's method of merging `StyleSheet`s with arrays, since arrays are also iterable. Nonetheless, this issue is quite important to me.

**Comment by Gozala** [comment]
+1 Please add support for Immutable.js and alike!

Problem is indeed is in use of `for in` loop with `.hasOwnProperty` :
https://github.com/facebook/react/blob/4c3e9650ba6c9ea90956a08542d9fa9b5d72ee88/src/renderers/dom/shared/CSSPropertyOperations.js#L121-L137

Personally run into issue with a computed styles who's fields are expressed via getters.

**Comment by spicyj** [comment]
Going to count this as part of #3059 as we'll likely support either both or neither.

**Comment by cigitia** [comment]
Ah, I see; thanks for the response. Since, as [syranide had pointed out](https://github.com/facebook/react/issues/3059#issuecomment-87301879], the `style` prop of `ReactDOMComponent` is technically a separate issue, this may still be a contender even if #3059 is eventually rejected for good (which I do hope won't be the case). We’ll see what happens to #3059 first, though, yes.

**Comment by spicyj** [comment]
It's true that there's no technical reason they need to be consistent, but it's hard for me to imagine us doing one and not the other.
