### ISSUE TITLE
Close meta tag

### ISSUE THREAD

**Issue by gobwas** [facebook/react#3546]
Hi!

I am also want to use React as template engine also on server side, and in some case, I want to have valid xml output.

Some my component has code:

```js

render() {
  return (<meta {...attrs} />);
}

```

But, with `#renderToStaticMarkup` returns me not closing meta:

```html
  <meta ...>
```

Is it bug?

**Comment by cody** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) writes under "Tag omission":
> As it is a void element, the start tag must be present and the end tag must not be present.

Seems to be not a bug.

**Comment by syranide** [comment]
#2842, XML-compatible markup in next release.

**Comment by gobwas** [comment]
@cody yes, it is about html, not xml or xhtml =)
@syranide good news. thanks!

**Comment by cody** [comment]
I just tried it and React 0.14.0-alpha has the closing tag in the output.

@syranide This is a violation of "the end tag must not be present", isn't it?

**Comment by syranide** [comment]
@cody If the *closing tag* is there then yes I think so, but `<meta />` is valid.

**Comment by cody** [comment]
Great :+1: React makes everyone happy.

**Comment by gobwas** [comment]
@cody @syranide :beers:
