### ISSUE TITLE
Using -w with -x causes multiple rebuilds

### ISSUE THREAD

**Issue by hatched** [facebook/react#3550]
When using `-w` and `-x jsx` it will recompile the source when the output is generated. It appears that this is because the matching is not strict enough.

Assume the directory structure of:
```
jsx-test
  \src
    source.jsx
  \build
```
From within `jsx-test/` run `jsx -wx jsx src build`. It should build once.
In another terminal, open up `source.jsx` and make some modifications.
Switch back to the previous terminal and you'll see that when the `source.jsx.swp` gets updated it will rebuild the source again.

**Comment by zpao** [comment]
Ah, seems like it's mostly to do with `.swp` files and not the combo of options.

**Comment by zpao** [comment]
Filed https://github.com/reactjs/commoner/issues/78 in our dependency to fix this.

**Comment by hatched** [comment]
@zpao I'm also seeing
`source.jsx~ changed; rebuilding...` in the logs as well which lead me to believe that it might be the matching.

**Comment by jimfb** [comment]
This has been replaced by babel.
