### ISSUE TITLE
jsx compiler leaves trailing whitespace in object definitions

### ISSUE THREAD

**Issue by hatched** [facebook/react#3553]
Assuming the following render call.
```JavaScript
      React.render(
          <views.AddedServicesButton
            serviceCount={serviceCount}
            closed={closed}
            changeState={this.__changeState.bind(this)}/>, container);
```
The generated output.
```JavaScript
      React.render(
          React.createElement(views.AddedServicesButton, {
            serviceCount: serviceCount, 
            closed: closed, 
            changeState: this.__changeState.bind(this)}), container);
```
You'll notice that there is a trailing white space on the `serviceCount` and `closed` properties which is causing issues for linters which don't allow trailing white space.

**Comment by jsfb** [comment]
You should be running your linters on source code (not generated code).  Generated code generally should not be checked into a repository, should not be linted, etc.  For this reason, this is probably pretty low priority.  That said, if you'd like to submit a pull request, it would likely be considered.

**Comment by spicyj** [comment]
@jsfb We've tended to recommend linting after running through JSX as that's what FB does and it preserves line numbers, etc.

**Comment by jsfb** [comment]
Eeeh, That would mean that if someone's lint rules state that there must be a space between a function name and the open pren, that the linter would fail.  Or if someone's linter says that statements should always be on a single line.  Or any number of potential lint rules that happen to conflict with whatever the transpiler produces.  You can't win, because people's linting rules can be mutually exclusive and thus there is no possible transpiler output that will pass all linters.  Better to lint what the human is actually reading/editing.

**Comment by spicyj** [comment]
It's true, but then your linter needs to understand JSX. Now there are some (particularly eslint) but there weren't a year ago.

**Comment by jsfb** [comment]
Yep, I agree :).

**Comment by hatched** [comment]
I agree that supporting the all of the various linting options would be an exercise in futility. I brought this one up because it appears to be a bug being that it doesn't add the trailing white space in any other instance I could find.

**Comment by jsfb** [comment]
Yeah, having the transpiler produce trailing whitespace probably wasn't intentional, but it's not a high-priority bug (primarily since it's generated code and thus not intended for human consumption).  Like I said, we'd likely accept a pull request if you'd like to fix it :).

**Comment by syranide** [comment]
#970, it's non-trivial to fix in the generator and was left as-is for now.

**Comment by jimfb** [comment]
JSX compilation is now handled by babel, which I think renders this issue no longer applicable.
