### ISSUE TITLE
confuse with 'two children with the same key'

### ISSUE THREAD

**Issue by zhangsoledad** [facebook/react#3558]
I'm using react to mounting two same components on a page, 
```javascript
var SelectBox = React.createClass({
  getDefaultProps: function() {
    return {
      value: []
    };
  },
  getInitialState: function() {
    return {checked: this.props.value,count: 1};
  },
  handleClick: function() {
    var opt = this.state.checked;
    opt.push({id: this.state.count, name: this.state.count});
    this.setState({checked: opt, count: this.state.count + 1});
  },
  render: function() {
    var that = this;
    var options = this.state.checked.map(item => <option key={'checked-' + that.props.name + item.id} value={item.id}>{item.name}</option>);
    return (
      <div>
        <select multiple={true}>
          {options}
        </select>
        <button type="button" onClick={this.handleClick}>add</button>
      </div>
    );
  }
});
React.render(
  <SelectBox name='one'/>,
  document.getElementById('one')
);
React.render(
  <SelectBox name='two'/>,
  document.getElementById('two')
);
```
i already ensure the key is unique,then click the button of the 'one', it's alright, but when i click the button of the 'two', some `<option>` of 'one' crop up in 'two',why?? it make me confuse. console show:
```
Warning: flattenChildren(...): Encountered two children with the same key, `.$checked-two1`. Child keys must be unique; when two children share a key, only the first child will be used.
```
![click 'one' button](https://cloud.githubusercontent.com/assets/3198439/6934397/a3fee9c6-d866-11e4-9858-6c340027012b.png)click 'one' button
![click 'two' button](https://cloud.githubusercontent.com/assets/3198439/6934404/c111856e-d866-11e4-8ae5-99b2847eaaf9.png)click 'two' button

but just do some change
```javascript
var a = [{id: 5, name: 5}];
React.render(
  <SelectBox name='one' value={a}/>,
  document.getElementById('one')
);
```
it work properly. what happenned？

**Comment by vsiao** [comment]
`getDefaultProps` is called once and cached, so all `SelectBox` components without an explicit `value` prop passed will share the same `checked` array reference in state.

**Comment by zhangsoledad** [comment]
@vsiao Oh, thanks ,i see.
