### ISSUE TITLE
onChange propagation

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/react#3559]
One tricky thing I experienced recently is that onChange from input propagates (if I don't set stopPropagate), which means that if I have input somewhere deep..  any change on it will propagate through dom tree.  And since I was using onChange on some more generic components it was triggering also these..   and took while to find out why..

Now I understand whats going on there. And my question is - is that intentional? And maybe would make sense to have some warning because in 99% you just want to handle input onChange and not propagate the event.

And curious what you would consider as better practice - avoid use of onChange prop on non-form components or just use stopPropagation?

Thanks for your thoughts.

**Comment by radubrehar** [comment]
I've also hit this issue at a point in time and as far as I remember this has been brought up before. But this is how the DOM behaves, and I don't really think React intends to change this. It's fairly easy to build a wrapper component around `<input />` and just stop propagation there.

Ideally React tries not to change how DOM stuff works, but only provide a nice functional declarative abstraction on top of it.

**Comment by jardakotesovec** [comment]
Thanks for feedback. I think avoiding `onChange` prop is way to go, so it does not get mixed up with dom events.

**Comment by radubrehar** [comment]
I would use `event.stopPropagation()` when appropriate
