### ISSUE TITLE
strange contains `render` method but is not mounted in the DOM when there's an input

### ISSUE THREAD

**Issue by bruno12mota** [facebook/react#3561]
I've got a component that renders the following:

```
render () {
    <div>
        <form onSubmit={this.onAdd.bind(this)}>
          <input type='text' />
          <input type='submit' value='Add' />
        </form>
      </div>
}
````
When I mount the same root component with different props on the previously rendered node I receive the error `Uncaught Error: Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains `render` method but is not mounted in the DOM`.

Now, If i remove both inputs from the form above the error goes away.

An important note is that I'm using contexts and the component above lives inside `this.context.activePanel` in the root.

Even though there's an error everything works as expected.

**Comment by bruno12mota** [comment]
I was using `setState` inside `componentWillUpdate` and that was causing the problem. My bad :+1:

**Comment by spicyj** [comment]
Did you get a console warning for this?
