### ISSUE TITLE
Document React.addons.batchedUpdates

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#3570]
I didn't realise this was in the addons bundle, would be good to get it added to the docs.

http://facebook.github.io/react/docs/addons.html
https://github.com/facebook/react/blob/master/src/browser/ReactWithAddons.js#L40

Would be good to also include an example of using https://github.com/facebook/react/blob/master/src/addons/ReactRAFBatchingStrategy.js or something similar.

**Comment by spicyj** [comment]
rAF batching isn't supported and won't go in the docs, but batchedUpdates should.

**Comment by zpao** [comment]
There are also known issues with rAF batching (mostly around controlled components).

**Comment by kassens** [comment]
Should we deprecate and eventually remove the RAF batching?

**Comment by spicyj** [comment]
It's never been supported in any fashion.

**Comment by spicyj** [comment]
(i.e., it's already deprecated?)

**Comment by chicoxyzzy** [comment]
shouldn't this file be deleted in that case?
https://github.com/facebook/react/blob/master/src/addons/ReactRAFBatchingStrategy.js

**Comment by spicyj** [comment]
That's not exposed as a public API in any of our builds, but sure, we can delete it – PR incoming.

**Comment by jimfb** [comment]
Killed in https://github.com/facebook/react/pull/6016

**Comment by spicyj** [comment]
We should document ReactDOM.unstable_batchedUpdates.

**Comment by jimfb** [comment]
@spicyj Since when did we start documenting `unstable_` features?  Haven't we always left them intentionally undocumented?  We also have unstable_renderSubtree and unstable_handleError and others, but I thought the decision was to not document them until they become stable.  We document them as part of the release process.

**Comment by spicyj** [comment]
Sure.
