### ISSUE TITLE
Use LinkedStateMixin links for radio buttons (radioLink?)

### ISSUE THREAD

**Issue by guybenron** [facebook/react#3573]
React has two types of linked states: valueLink and checkedLink. Neither work well for radio buttons, which have no mutable value and which the `checked` attribute is a somewhat degenerate parameter, in that there is additional work to be done to understand which radio button is actually selected.

It would be great if we could add something akin to the valueLink for text inputs, which would set a state variable to the defined value, like so:

    <input type="radio" name="mygroup" value="first"    radioLink={this.linkState("myval")}/>
    <input type="radio" name="mygroup" value="secondth" radioLink={this.linkState("myval")}/>
    <input type="radio" name="mygroup" value="thirdst"  radioLink={this.linkState("myval")}/>

Say the first radio button was clicked, then after the change, the state would have a variable named `myval` with the value `first`.

This can probably be achieved by adding a few lines to LinkedValueUtils.js. It's arguable whether the linked value could also serve as the group name, or even have the radio type implicitly set just by having a radioLink attribute, but I believe the syntax should be kept as close to the other link types, plus the type/name verbosity gives context to the code.

Does this use-case warrant a such feature .. ?

**Comment by luiso1979** [comment]
It seems natural that such a feature exists in React. So I fully support it

**Comment by syranide** [comment]
#2302 ... plus `valueLink` is just sugar so you're better of just providing your own wrapper component that works the way you want.

**Comment by jimfb** [comment]
As @syranide noted, the current plan is to pull linking out of the core and probably throw it into an addon package.  Assuming `radioLink` is something you find useful, I encourage you to publish a npm module or git repository that provides this functionality as a wrapper component so other people can use it.  Since this is not something we plan on supporting in the core, I'm going to go ahead and close out the issue.
