### ISSUE TITLE
Does consistently rendering new components into the body defeat the purpose of DOM diffing?

### ISSUE THREAD

**Issue by trusktr** [facebook/react#3577]
For example, if I do something like

```js
        React.render(
          someComponent,
          $('body')[0]
        );
```

repeatedly, will that mean that diffing isn't being taken advantage of (the real DOM re-rendered every time), or is there something in place to prevent the real DOM from being re-rendered every time?

**Comment by spicyj** [comment]
No, that'll trigger a diff (so it should be fast) and is the recommended way to rerender a top-level component.

**Comment by trusktr** [comment]
@spicyj Thanks for the super quick reply! Does React keeps track of each element that gets a React component rendered into it? What happens if the target element gets removed?

**Comment by spicyj** [comment]
Yes, it does. You should call React.unmountComponentAtNode before removing the container from the DOM in order to prevent leaks.

**Comment by trusktr** [comment]
@spicyj Aah! Thanks!! This is very valuable.
