### ISSUE TITLE
Uncaught TypeError: Cannot read property 'context' of null

### ISSUE THREAD

**Issue by LuoZijun** [facebook/react#3585]
Uncaught TypeError: Cannot read property 'context' of nullreact.js:6738 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:4779 ReactChildReconciler.updateChildrenreact.js:12900 ReactMultiChild.Mixin._updateChildrenreact.js:12874 ReactMultiChild.Mixin.updateChildrenreact.js:7862 ReactDOMComponent.Mixin._updateDOMChildrenreact.js:7713 ReactDOMComponent.Mixin.updateComponentreact.js:7697 ReactDOMComponent.Mixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6647 ReactCompositeComponentMixin.receiveComponentreact.js:14131 ReactReconciler.receiveComponentreact.js:6884 ReactCompositeComponentMixin._updateRenderedComponentreact.js:6863 ReactCompositeComponentMixin._performComponentUpdatereact.js:6783 ReactCompositeComponentMixin.updateComponentreact.js:13371 ReactPerf.measure.wrapperreact.js:6680 ReactCompositeComponentMixin.performUpdateIfNecessaryreact.js:14149 ReactReconciler.performUpdateIfNecessaryreact.js:14899 runBatchedUpdatesreact.js:16625 Mixin.performreact.js:16625 Mixin.performreact.js:14843 assign.performreact.js:14923 flushBatchedUpdatesreact.js:13371 ReactPerf.measure.wrapperreact.js:16698 Mixin.closeAllreact.js:16639 Mixin.performreact.js:9143 ReactDefaultBatchingStrategy.batchedUpdatesreact.js:14963 enqueueUpdatereact.js:14481 enqueueUpdatereact.js:14604 ReactUpdateQueue.enqueueForceUpdatereact.js:6008 ReactComponent.forceUpdatepaper.js:392 window.components.papers.paper.React.createClass.reciverElementrequests.js:517 window.requests._transferCompleterequests.js:140 request.onreadystatechange

what's that mean?

**Comment by knowbody** [comment]
when do you get this error?

**Comment by zpao** [comment]
It's really hard to say for sure without more info but one thing that jumps out at me is that you're doing some AJAX and calling `forceUpdate` with the result. It's possible that the component unmounted before you did that though. In 0.12, doing that would throw an error. In 0.13 I think we should just be warning and then just returning. Clearing the requests in `componentDidMount` is the suggested way of handling this.

Your error is suggesting you're using 0.13 though. If you could reduce this to something reproducible and sharable, that would be helpful.

**Comment by jimfb** [comment]
I haven't seen people running into this old issue, and we don't have a repro, so I'm going to close.  We can re-investigate if we can get a repro.

**Comment by joanrieu** [comment]
Hi,

I just encountered that exact issue and found its cause : I had forgotten to pass `props` to `super()` in an ES6 `constructor()`.

Buggy code:
```js
export default class Something extends React.Component {
    constructor() {
        super();
        this.state = { /* ... */ };
    }
}
```

Working code:
```js
export default class Something extends React.Component {
    constructor(props) {
        super(props);
        this.state = { /* ... */ };
    }
}
```

The error has been hard to trace back to this, since the component doesn't render at all.
Maybe some `undefined`-check could be implemented in the parent constructor to explain the issue.

NB : this has not been tested in React v15 (I don't have my current exact version number at hand, but it's 0.14.x).

**Comment by gaearon** [comment]
Doesn't appear to be an issue in 15: https://jsfiddle.net/2dt3pwqp/
