### ISSUE TITLE
<option value="foo" selected> not rendering on the server

### ISSUE THREAD

**Issue by mariuslundgard** [facebook/react#3594]
I'm having an issue with a `<select>` element which is rendered both on the server and in the client. This example recreates the issue:

``` jsx
const React = require('react');

const SelectedDebug = React.createClass({
  displayName: 'SelectedDebug',

  render() {
    return (
      <div>
        <select value='C'>
          <option value='A'>A</option>
          <option value='B'>B</option>
          <option value='C'>C</option>
        </select>
      </div>
    );
  }
});

module.exports = SelectedDebug;
```

The `selected` attribute is *not* rendered on the server, but works fine in browser.

I've also tried setting the `defaultValue` prop on the `<select>` element, which doesn't seem to make a difference. It render as expected when I use `<option value='C' selected>`, however, that of course throws a warning in the console telling me to use either the `value` or `defaultValue` prop.

Note: this code is running in Node v0.12 using [Babel](https://github.com/babel/babel) for transpiling (tested both using React v0.12 & v0.13).

Am I missing something, or is it a bug?

**Comment by mariuslundgard** [comment]
Looking at the source code, it looks as if the `selected` attribute is only added after the node is mounted. This snippet is from `src/browser/ui/dom/components/ReactDOMSelect.js`:

``` js
  componentDidMount: function() {
    var value = LinkedValueUtils.getValue(this);
    if (value != null) {
      updateOptions(this, value);
    } else if (this.props.defaultValue != null) {
      updateOptions(this, this.props.defaultValue);
    }
  },
```

Is it like this for a reason?

**Comment by zpao** [comment]
This is a known problem right now, though we haven't looked back into it lately. See #1398 for more discussion.

**Comment by mariuslundgard** [comment]
Ah, I see. Thanks for responding.
