### ISSUE TITLE
Tests fail when run manually in firefox but not Chrome

### ISSUE THREAD

**Issue by onigoetz** [facebook/react#3598]
Hi,
I'm trying to run the jasmine tests in firefox and 678 of 817 fail.
But when I run the tests in Chrome, they succeed.

I know your tests run on Phantom JS which is a headless Chrome, but aren't the tests supposed to run on all browsers ?

apart from all the "assertion failed" I was able to spot this : 

```
Expected '<span data-react-checksum="-140697198" data-reactid=".2"><span data-reactid=".2.0">Name: </span><span data-reactid=".2.1">x</span></span>' to be '<span data-reactid=".2" data-react-checksum="-140697198"><span data-reactid=".2.0">Name: </span><span data-reactid=".2.1">x</span></span>'.
```

and it seems the only thing that changed is the order of the "data" attributes in the first tag. Are the tests dependent on this ?

**Comment by spicyj** [comment]
Sounds like it. Happy to take PRs to fix this – though I'm surprised that 678/817 fail; I thought they all passed at one point in the past.

**Comment by zpao** [comment]
That's pretty strange - the checksum gets added to the HTML string manually and I wouldn't imagine that differs between browsers.

**Comment by onigoetz** [comment]
I will take a look, and create a PR If I find what makes all these tests fail.

**Comment by Charca** [comment]
This also caught my attention yesterday. I did some research around it and found that not all of them are related to the same issue.

I managed to fix 644 out of the 678 failing tests in Firefox with very small changes (note that from the remaining 34 failing tests, 32 are also failing in Safari for Mac).

I'll send a PR in a few.

**Comment by jimfb** [comment]
I don't think we support running tests in the browser anymore, right?  Rendering this bug no longer applicable?

We should have an in-browser test suite like https://github.com/facebook/react/pull/4393, but it sounds like we want to do that as a separate thing.
