### ISSUE TITLE
setting attribute "style" to null breaks this attribute

### ISSUE THREAD

**Issue by firlaj** [facebook/react#3606]
When I assign null to style attribute to reset it, it works... but only once. Any following changes of this value do nothing. Here's a fiddle demonstrating this - try to push the button several times:
http://jsfiddle.net/bqnhkwju/

This seems like a strange behaviour to me - I wouldn't be surprised, if my first attempt to set style=null failed, but it doesn't and it silently breaks the style attribute.

**Comment by kassens** [comment]
Thanks @firlaj, I was able to reproduce this.
