### ISSUE TITLE
Testutils more shorthands

### ISSUE THREAD

**Issue by juliankrispel** [facebook/react#3607]
Right now only two methods from the jest API have shorthands, yet some of the methods are ridiculously long, like `findRenderedDOMComponentWithTag`. Makes for slow reading and typing.

Can we have shorthands for more than just two methods in TestUtils?

:heart:

**Comment by spicyj** [comment]
We're not planning to add more to the existing helpers in test utils right now but you can always make your own helpers in your own util library and use those.
