### ISSUE TITLE
JSX Compiler Issue for Html Element

### ISSUE THREAD

**Issue by KulvSingh** [facebook/react#3608]
Just started out making new UI components in React. Faced the following issue.

I defined the component state.
```javascript		
getInitialState: function() {
    return {checked:false};
}
```
I  use the state in the input tag inside the render function
```javascript
render: function () {
return(
     <div className={this.state.className} onClick={this.clickHandler} >
       <input type="checkbox" ref="innerinput"  {this.state.checked} />;
       <label>Checkbox</label>
    </div>
)
}
```
It gives the following error:

{ [ReactifyError: /usr/local/src/st/agile/app/App.js: Parse Error: Line 55: Unexpected token this while parsing file: /usr/local/src/st/agile/app/App.js]
  index: 1149,
  lineNumber: 55,
  column: 47,
  description: 'Unexpected token this',
  name: 'ReactifyError',
  fileName: '/usr/local/src/st/agile/app/App.js',
  filename: '/usr/local/src/st/agile/app/App.js',
  stream: 

It seems that the JSX supports only "type=value" properties and not property like "checked" without value.

**Comment by brigand** [comment]
JSX is an expression so the semicolon doesn't make sense.  Also you need the prop name checked, `checked={this.state.checked}`, and for accessibility you probably want to change the onClick to onChange on the checkbox, and an id/htmlFor linking it to the label.

```
       <input type="checkbox" ref="innerinput"  {this.state.checked} />;
                                                             semicolon ^
       <input type="checkbox" ref="innerinput"  {this.state.checked} />;
                                    stray value ^
```

This isn't a bug, please ask questions in #reactjs on irc.freenode.net, or StackOverflow.

**Comment by KulvSingh** [comment]
thanks, moved to StackExchange
