### ISSUE TITLE
Erro in WebKit Qt 4.8

### ISSUE THREAD

**Issue by pedroteixeira** [facebook/react#3609]
Does any one know why would React.js not work in wkhtmltopdf?
I was curious to exactly what feature / API React uses that is not supported under Qt web view 4.8 (all other js libraries that I use work fine)

Related:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2225

**Comment by syranide** [comment]
Could be an outdated JavaScript environment (like Phantomjs 1 is), have you tried with the recommended polyfills?

**Comment by RileyTomasek** [comment]
I am having the same issue. Which polyfills are you talking about? I would be happy to give them a try.

**Comment by syranide** [comment]
http://facebook.github.io/react/docs/working-with-the-browser.html#polyfills-needed-to-support-older-browsers

**Comment by zpao** [comment]
Yea, sounds like a polyfill issue (which would explain why React is undefined laster). Reopen if that's not the case.
