### ISSUE TITLE
clarification on PATENTS grants and termination clauses

### ISSUE THREAD

**Issue by jokeyrhyme** [facebook/react#3617]
Firstly, I sincerely apologise if this is the wrong place to be asking this question, but I haven't seen this answered in other places and think it definitely relates to usage of React.js.

There has been some consternation and confusion about Facebook's [patent grant](https://github.com/facebook/react/blob/master/PATENTS) declared in their project (including this one).
- https://news.ycombinator.com/item?id=9271331
- https://news.ycombinator.com/item?id=9111849
- http://www.reddit.com/r/reactjs/comments/318rar/patents_file_and_its_implications/

Specifically:
> The license granted hereunder will terminate, automatically and without notice,
for anyone that makes any claim (including by filing any lawsuit, assertion or
other action) alleging ... (b) that any right in any patent claim of Facebook is invalid or
unenforceable.

I'm not a lawyer, but I interpret this to mean that if I use React and publicly voice concern about the quality or validity of any patent owned by Facebook, that the access to React-related patents is terminated automatically and I am now open to being sued for patent infringement. I may be a little paranoid, but I also wonder if simply discussing this issue is grounds for patent grant termination.

The (a) clause makes perfect sense, in terms of protecting Facebook from unnecessary patent litigation. The desired purpose (spirit) and actual purpose (letter) of the (b) clause are just confusing and concerning.

If you can please point me to where this discussion / answer has already taken place, that would be terrific.

If there is not yet official word from Facebook on this issue, then please point me to the arena in which is this going to take place (or is more likely / appropriate).

**Comment by syranide** [comment]
Related #3554

**Comment by jokeyrhyme** [comment]
Thanks @syranide, I'm not sure how that escaped my notice.

**Comment by jokeyrhyme** [comment]
If I were to advocate for software patent reform that affects the validity of Facebook's patents, does this activate the termination clause in the patent grant?

What are the potential legal consequences for activating the termination clause of the patent grant?

**Comment by syranide** [comment]
@jokeyrhyme (I'm not part of the team) so all I have to offer is https://github.com/facebook/react/pull/3554#issuecomment-88264870

**Comment by zpao** [comment]
Let's keep all discussion in the other issue. Somebody with authority will comment when able.

**Comment by jamesgpearce** [comment]
http://fb.me/patents2

**Comment by FezVrasta** [comment]
I'm still not sure about what this patent grant means...

Does the infringement of the "Patent Grant" invalidates the BSD license?

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
