### ISSUE TITLE
[feature request] show component name in warnings

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/react#3619]
During upgrading `0.13` I found it really hard to locate problems caused by duplicated using of `createFactory`. But it may help with component names in the warnings:

```js
      'Warning: Factory.type is deprecated. Access the class directly before ' +
      'passing it to createFactory
```

![p](https://cloud.githubusercontent.com/assets/449224/7042993/77bcf92c-de18-11e4-9444-b1d89ead9e4a.png)

**Comment by spicyj** [comment]
In this case, I think "Factory" is already the component class name? But if you add a breakpoint on the warning line and look at the stack, you should see the exact code path that caused it.

**Comment by jiyinyiyong** [comment]
@spicyj Actually I tried, but I didn't figure out how to access the `displayName` property in side that objects.

**Comment by spicyj** [comment]
If you look up through the stack trace, one of the frames should be your application code which is accessing `.type`.

**Comment by jiyinyiyong** [comment]
@spicyj You mean that component is called `Factory`?... Alright, that's strange. Thx anyway.
