### ISSUE TITLE
ReactPropTransferer does not merge React Native styles

### ISSUE THREAD

**Issue by ide** [facebook/react#3624]
The existing merge strategy at https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/core/ReactPropTransferer.js#L39 only merges objects. A different merge strategy is necessary for React Native, which uses ints instead of Objects and also supports arrays. I believe this can be backwards-compatible with web React.

**Comment by zpao** [comment]
I think `transferPropsTo` or `cloneWithProps` (the only things actually using ReactPropTransferer IIRC) should be avoided if possible. We've already noted that they're deprecated in favor of spread props and cloneElement respectively.

Is there something you're trying to do that you can't use use those?

**Comment by zpao** [comment]
cc @vjeux who has hopefully thought about this / encountered it.

**Comment by ide** [comment]
@zpao I'll take a look at `cloneElement`. I was using `cloneWithProps` out of familiarity and seeing other React Native core code use it.

**Comment by zpao** [comment]
cloneElement takes out the magic so it might require a little bit more work. We're trying to get away from the magic :) See http://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html#react.cloneelement for a bit more

**Comment by gaearon** [comment]
`transferPropsTo` and `cloneWithProps` have been removed.
