### ISSUE TITLE
Unable to horizontally align elements

### ISSUE THREAD

**Issue by johnryan** [facebook/react#3626]
I am trying to horizontally space divs as demonstrated in this example:
http://jsfiddle.net/thirtydot/EDp8R/

It works fine with my CSS when I paste that example code into an html file, but when I try to do it in React like so:

```
var React = require('react');

var Page = React.createClass({displayName: "Test",
	render: function () {
		return (
		<div className="container">
		    <div className="box1"></div>
		    <div className="box2"></div>
		    <div className="box3"></div>
		    <div className="box4"></div>
		    <span className="stretch"></span>
		</div>

		);
	}
});

React.render(<Page />, document.body);
```

It doesn't work correctly. Is there any known issues with React that I might be missing? or is this just the wrong way to do this?

**Comment by spicyj** [comment]
Perhaps you mixed up `id="container"` with `className="container"`? This works for me: http://jsfiddle.net/xzqwjhhL/

**Comment by johnryan** [comment]
@spicyj I modified the CSS to make container a class css selector...sorry for leaving that out, but furthermore the demo you posted doesn't work...when you resize the window the divs are all right next to each other.

**Comment by spicyj** [comment]
I see. The (subtle!) difference here is that your HTML has whitespace in between each of the adjacent elements, but in JSX whitespace is removed between two tags on different lines because that's usually what you want. You can add it back explicitly by writing `{' '}` in between them: http://jsfiddle.net/fu1fs8ez/

**Comment by johnryan** [comment]
@spicyj Ah! Thanks for the tip
