### ISSUE TITLE
onChange dropped from input fields when generated within an iterator

### ISSUE THREAD

**Issue by cbegin** [facebook/react#3643]
I'm using underscore for mapping over an array to generate a list of components. 

Example code: 
```
{_.map(someArray, function (item, index) {
    return (
        <input key={index} 
                   onChange={this.onFieldChange} 
                   value={item.someProp} />);
})}
```
Upon rendering, the onChange will be dropped.

**Comment by spicyj** [comment]
This seems very unlikely to me. Can you post a repro case?

**Comment by spicyj** [comment]
Oops, never mind – this is because `this` inside the iterator function isn't your component. Passing `this` as the third argument to `_.map` or using an arrow function instead will solve your problem.

**Comment by cbegin** [comment]
@spicyj  Oh man, so sorry for the noise and the total noob mistake. I think what got me was the result. Normally I'd just get a "such and such is undefined" error or similar. When this resulted in the attribute missing, I think I stopped looking at the code altogether, and only focused on where it was. 

I see now why this is.  With `this.onFieldChange === undefined` in this scope, it resulted in `onChange={undefined}` which is hardly different from binding it at all. 

I wonder though if React could do anything to produce a better error in this case?

For example, let's consider an object 

```
var o = { foo: undefined } 
o.foo => undefined
o.bar => undefined
```
But...

```
'foo' in o => true
'bar' in o => false
```

Perhaps a simple validation whereby 'onChange' in attributes but !attributes.onChange, a warning could be produced at the very least?

 Thanks again!

**Comment by spicyj** [comment]
Yeah, we've talked some about this: #1255. This is unfortunate but I don't think we're going to change anything here. This is the sort of the thing that a static type system like Flow should be able to catch though.

**Comment by cbegin** [comment]
Ah, I see the case being made for it, for enable/disable. Thanks!
