### ISSUE TITLE
Update tutorial doc for ES6

### ISSUE THREAD

**Issue by catherinettt** [facebook/react#3647]
Are there plans to update https://facebook.github.io/react/docs/tutorial.html to ES6? 

We are reworking internal documentation based on these tutorials to use ES6. We'd be happy to contribute back if you want us to update the code examples in the existing tutorial.

Would it be best to keep the existing `React.createClass` examples and add the ES6 underneath or create a new ES6 tutorial page (eg. `react/docs/tutorial-es6.html`)?

**Comment by jsfb** [comment]
I think ES6 is the "new" way of doing things, so probably just update the existing examples.  Feel free to submit a pull request.  cc @sebmarkbadge @zpao

**Comment by spicyj** [comment]
No, we're not ready to recommend ES6 classes to all newcomers. See #3375 for more details.

**Comment by sebmarkbage** [comment]
@spicyj is right but we should clarify the blockers before we do want to switch. IMO they are:

1) Property initializers reaches a stable polyfill that we can recommend.
2) The observe() pattern is released and is the primary recommendation for Flux stores (no mixins).
3) We publish an article describing alternatives to mixins.
4) Most popular libraries you might want to use, moves away from mixins.

**Comment by catherinettt** [comment]
I agree that ES6 is not ready for newcomers and it will be more than just updating the tutorial examples. 
Let's stick with your plan. Thanks guys!

**Comment by zpao** [comment]
Going to close this out as it's likely we'll forget to ever update this even after we update docs. We won't forget to come back to actually making the change when we're ready though.
