### ISSUE TITLE
Exposing Max Tree Depth

### ISSUE THREAD

**Issue by zhxnlai** [facebook/react#3648]
I am working on a tree-like visualization where child nodes are nested inside their parent node. 
As I expand the tree I hit the depth limit set by `MAX_TREE_DEPTH` from [ReactInstanceHandles.js](https://github.com/facebook/react/blob/dea7efbe16596bbab7965331e277de113aeaff27/src/core/ReactInstanceHandles.js#L25), getting the following error message:
~~~javascript
'traverseParentPath(%s, %s, ...): Detected an infinite loop while ' + 'traversing the React DOM ID tree. This may be due to malformed IDs: %s',
~~~ 

I was wondering if you guys have plans to make the depth limit configurable. Is there any way to bypass this limitation?

**Comment by spicyj** [comment]
I don't have any objection to bumping the limit to some number in the millions – or we could probably get rid of the check too.

**Comment by greeze** [comment]
It doesn't look like anything ever changed with this. Are there any plans to bump the `MAX_TREE_DEPTH` or, even better, to make it configurable? A depth of 100 is low for our purposes, and the exception it throws is incorrect.

**Comment by jimfb** [comment]
@greeze It was bumped from 100 to 10000, which should be more than sufficient for most use cases.  Can you elaborate a bit on your use case?

**Comment by greeze** [comment]
@jimfb Sorry, my mistake. It looks like we're stuck in a pre-bump version of React (13.3) which still has that limit set at 100. Can you think of a way that we can override that without forking, and without updating our version of React? We're working with trees that are somewhat deeper than 100 levels.

**Comment by jimfb** [comment]
@greeze The official recommendation is to update; we recommend that you always stay on the latest version of React!  If it's a one-off hack until you get a chance to upgrade, you could always open up the `react.js` file in your project and tweak that number manually, but that's arguably worse than forking the source :P.

**Comment by iamdustan** [comment]
Another silly hack (assuming babel) is to write a local babel plugin to change it at compile time. Benefit: no need to much in node modules, whole team gets it. Downfall: you're writing a custom plugin to change react source :)

**Comment by greeze** [comment]
Thank you both for your replies. Ideally, we'd love to be using the latest version of React, but that's unfortunately not up to us at the moment. I'll give some thought to flattening out our tree so we can avoid this problem altogether, but if that doesn't work then we'll give the Babel plugin idea a shot and see how that goes.

Thanks again!

**Comment by spicyj** [comment]
Curious: what's preventing you from upgrading?

**Comment by greeze** [comment]
Nothing in my team's current project, but we have multiple teams working on multiple shared components across the org, and we need to keep our versions of React in sync at the moment. We will be upgrading eventually (hopefully soon), but it's not an option just yet.
