### ISSUE TITLE
In Chrome, synthetic drag and drop events should use DOMStringList for event.dataTransfer.types

### ISSUE THREAD

**Issue by aaronshaf** [facebook/react#3656]
`event.dataTransfer.types.contains(...)` is broken in Chrome.

**Comment by syranide** [comment]
Drag and drop events are not normalized by React (at the moment).

**Comment by aaronshaf** [comment]
React seems to be inconsistently and unintentionally normalizing some dnd events in certain browsers.

**Comment by syranide** [comment]
https://github.com/facebook/react/blob/master/src/browser/syntheticEvents/SyntheticDragEvent.js is the entire implementation (extends SyntheticMouseEvent which is normalized though), so `event.dataTransfer` is not currently normalized.

**Comment by gaearon** [comment]
I’m closing this as a duplicate of #2676.
