### ISSUE TITLE
React-tools installation fails

### ISSUE THREAD

**Issue by tudousi** [facebook/react#3660]
npm-debug.log
/////////////////////////////////////
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'react-tools' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'react-tools', null ]
6 verbose cache add spec react-tools
7 silly cache add parsed spec { raw: 'react-tools',
7 silly cache add   scope: null,
7 silly cache add   name: 'react-tools',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed react-tools@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'react-tools', range: '*', hasData: false }
12 silly mapToRegistry name react-tools
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/react-tools
16 verbose addNameRange registry:https://registry.npmjs.org/react-tools not in flight; fetching
17 verbose request uri https://registry.npmjs.org/react-tools
18 verbose request no auth needed
19 info attempt registry request try #1 at 19:08:18
20 verbose request id 5b79c264902ebbf2
21 http request GET https://registry.npmjs.org/react-tools
22 info retry will retry, error on last attempt: Error: connect EACCES
23 info attempt registry request try #2 at 19:08:29
24 http request GET https://registry.npmjs.org/react-tools
25 info retry will retry, error on last attempt: Error: connect EACCES
26 info attempt registry request try #3 at 19:09:29
27 http request GET https://registry.npmjs.org/react-tools
28 verbose stack Error: connect EACCES
28 verbose stack     at exports._errnoException (util.js:746:11)
28 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
29 verbose cwd C:\Windows\System32
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-tools"
32 error node v0.12.2
33 error npm  v2.7.4
34 error code EACCES
35 error errno EACCES
36 error syscall connect
37 error Error: connect EACCES
37 error     at exports._errnoException (util.js:746:11)
37 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
37 error  { [Error: connect EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'connect' }
38 error Please try running this command again as root/Administrator.
39 verbose exit [ 1, true ]

tks~:)

**Comment by tudousi** [comment]
I was logged in with administrator privileges

**Comment by zpao** [comment]
Looks like this is a permissions error. `react-tools` doesn't run anything on install so I don't think there's anything we can do. Can you `npm install -g` anything else?

This sounds like an issue to take up with npm.

**Comment by tudousi** [comment]
I successfully installed using the Administrator. before i use other windows accounts failure. ths guys
