### ISSUE TITLE
Dynamically changing rowSpan

### ISSUE THREAD

**Issue by RudmanMario** [facebook/react#3661]
I have a problem when trying to update my table. This is how my initial table looks like:

![Image of initial table](http://i57.tinypic.com/2isebno.png)

So the rowspan here works fine. My **"Row"** table cell looks like this:

```javascript
<th className="rotate header" rowSpan={this.props.tableFoo.axisY.ordinates.length}><div><span>Row</span></div></th>
```
So I'm looking for the length of ordinates array for axis Y and that is the number of rows which I want my **"Row"** cell to cover. 
Then when user clicks `"Add new Y ordinate"`, a new ordinate is pushed and table re-renders. This is the end result:
![Image of final table](http://i58.tinypic.com/2hprv4y.png)

So for some reason, although the rowspan changes to 4 and I can see that when inspecting elements, for some reason the table cell spans only across 3 rows. Why is that? Is it a bug?
I made a [fiddle](http://jsfiddle.net/zavLf6cz/3/) so you can see the problem.

**Comment by syranide** [comment]
Put `<tbody>` in your `<table>` and it will work (i.e. `<table><tbody>`).

@zpao Yet another reason to drop the optimistic traversal if you ask me (perhaps something like #2262)

**Comment by spicyj** [comment]
@syranide In master we now have a warning, at least.

**Comment by syranide** [comment]
@spicyj Fantastic :)

**Comment by RudmanMario** [comment]
Thanks for the help. It is an easy fix, but I would probably never found out about it on my own. I think there should be a warning of some sort about including `<tbody>` in table (or maybe there is somewhere in documentation but I haven't noticed it).

**Comment by spicyj** [comment]
@RudmanMario That's what I meant by my comment, sorry for being unclear – in the next release we'll warn you explicitly and suggest adding a tbody tag.
