### ISSUE TITLE
Access CSS class name after renderIntoDocument()

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#3666]
In my jest tests I'd like to verify the class names of the rendered elements. How can I do this best?

When I do `TestUtils.renderIntoDocument(...)`, I get the react element in the dom. And then what? How can I access the CSS class from there?

**Comment by yaycmyk** [comment]
`React.findDOMNode(element).className`?

**Comment by zpao** [comment]
What @yaycmyk said should work.

**Comment by binarykitchen** [comment]
ah, works, thanks - wish this example was documented somewhere along Jest / TestUtils ...
