### ISSUE TITLE
Key prop for DOM nodes is actually called 'code'

### ISSUE THREAD

**Issue by rainbow-alex** [facebook/react#3669]
I was trying to fix this warning:

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Text. See http://fb.me/react-warning-keys for more information.
```

After some searching I ended up in `react.js`, where I found (in `ReactElement.createElement`):

```
key = config.code === undefined ? null : '' + config.code;
```

I finally managed to get rid of the warning by using `React.createElement("li", {code: ...})` instead of `React.createElement("li", {key: ...})`.

This should be fixed, probably in `.createElement`, or at least in the docs/warning.

**Comment by syranide** [comment]
That does not make sense, I suspect your copy of React has been modified (probably by search and replace by mistake?).

https://github.com/facebook/react/blob/master/src/classic/element/ReactElement.js#L156

**Comment by spicyj** [comment]
Yeah, this isn't React – not sure where you got "code". If you search https://fb.me/react-0.13.1.js for "key = config" you'll see that our built copy has `key` as well.
