### ISSUE TITLE
JSXTransformer 0.13 changes source map return type

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#3670]
There seems to have been an API change between React 0.12 and 0.13 that's not covered in the documentation. When using `JSXTransformer.transform` with the `sourceMap` option, the source map is now returned as a plain JavaScript object. Previously it would return an instance of `SourceMapGenerator` and you'd need to call `.toJSON()` to get the actual source map.

Is this an intentional change that just got overlooked when writing the documentation?

**Comment by zpao** [comment]
That's just an oversight. We aligned JSXTransformer to use the same code as react-tools (as opposed to duplicating efforts with slight variation).

This originally changed in react-tools last year - #1783, and then I made JSXTransformer just use react-tools in #3191. I didn't notice that we're doing a bit more post-processing in react-tools.

We can add a bit to the changelog for this.
