### ISSUE TITLE
HTML to JSX Compiler - example page broken

### ISSUE THREAD

**Issue by dschinkel** [facebook/react#3671]
https://facebook.github.io/react/html-jsx.html

I get an error "ReferenceError: HTMLtoJSX is not defined"

**Comment by cody** [comment]
This was fixed in #3456. Seems like the docs have not been rebuild since then.

**Comment by zpao** [comment]
They've been updated but nobody put the right labels on that PR to make sure it got cherry-picked :(. Done now though. Might take a few minutes for caches to clear and the page to work properly.

**Comment by arrygoo** [comment]
This issue seems to be back at: 
https://facebook.github.io/react/html-jsx.html
"ReferenceError: HTMLtoJSX is not defined"

**Comment by zpao** [comment]
The page is gone now and redirects offsite so shouldn't be an issue. Maybe you hit a cached page while it was building.
