### ISSUE TITLE
Components not extending React.Component break findAllInRenderedTree()

### ISSUE THREAD

**Issue by jquense** [facebook/react#3677]
http://jsfiddle.net/69z2wepo/6547/

To be honest I am not sure if its really a bug, because I can't tell if components that don't extend `React.Component` are actually supported. My cursory look through some tests and type checks seem to indicate that they are/should be and I've not run into issues using them that way...except when trying to test them!

**Comment by spicyj** [comment]
They're supposed to be, but we're checking for setState here:

https://github.com/facebook/react/blob/v0.13.1/src/test/ReactTestUtils.js#L77-L80

Not sure what the best fix is – @sebmarkbage? Seems like we could look to see if the internal instance is an instance of ReactCompositeComponent.

**Comment by jquense** [comment]
Hi y'all I'd be happy to PR something to fix this (if it's still unresolved) any consensus on the correct heuristic though?

**Comment by gaearon** [comment]
All class components now must extend `React.Component`.
