### ISSUE TITLE
Nested node lists gain an extra <a> tag on top when containing a <a> tag in list item

### ISSUE THREAD

**Issue by rhomoelle** [facebook/react#3679]
I already tried stackoverflow for this und you might want to check out my description there (also a jsfiddle in the comments).

http://stackoverflow.com/questions/29678494/nested-children-nodes-in-navigation-tree-inherit-link-tag-from-their-parent-node

I'm trying to create a nested navigation tree of unordered lists with list items containing &lt;a&gt; tags. The sublevel lists gain an unintentional &lt;a&gt; tag with link but without description. It can be discovered in the html source and also be styled via CSS. If I substitute the &lt;a&gt; tag for e.g. a &lt;div&gt; the behaviour disappears.

    let NodeTree = React.createClass({
      render: function () {
        return (
          <ul>
            {this.props.tree.map(function (node) {
              return <NodeTree.Item key={node.id} data={node}/>
            })}
          </ul>
        );
      }
    });

    NodeTree.Item = React.createClass({
      render: function () {
        return (
          <li>
            <NodeTree.Content data={this.props.data}/>
          </li>
        );
      }
    });

    NodeTree.Content = React.createClass({
      render: function () {
        return (
          <a href={this.props.data.href}>{this.props.data.title}
            { this.props.data.hasOwnProperty('kids') ? <NodeTree tree={this.props.data.kids} /> : null }
          </a>
        );
      }
    });

renders:

    <ul>
      <li><a href="root/">Root Item</a>
        <ul>
          <a href="root/></a> <-- should not be here
          <li><a href="child1/">Child1</a></li>
          <li><a href="child2/">Child2</a></li>
          <li><a href="child3/">Child3</a></li>
        </ul>
      </li>
    </ul>

**Comment by cody** [comment]
I just looked at the fiddle: https://jsfiddle.net/wiredprairie/bg4y9rr7/
The problem comes from `<a>`s are being inside of another `<a>`. That is not allowed.

**Comment by rhomoelle** [comment]
ah crap. This is absolutely correct and I feel officially stupid now.

I'll close this.

**Comment by spicyj** [comment]
In 0.14 we'll have a warning for this. :)
