### ISSUE TITLE
Upgrading to 0.13 makes my app slow

### ISSUE THREAD

**Issue by kennethaa** [facebook/react#3680]
Hi.

I'm trying to upgrade from React 0.12 to 0.13. The rendering of my app are using much longer time in 0.13. With 0.12 the rendering takes around 100 ms, but with 0.13 it takes 600 ms. With this performance it's impossible for me to upgrade. Is there some kind of reason for this slow rendering?

Thanks.

**Comment by syranide** [comment]
Make sure you're not unintentionally running in debug mode, there is a performance regression in the debug version of React 0.13.

**Comment by kennethaa** [comment]
Thanks.
