### ISSUE TITLE
React Incorrectly reports Isomorphic rendering differences

### ISSUE THREAD

**Issue by gilbox** [facebook/react#3685]
React was unable to reuse markup but not for the reason stated in the warning message. It seems that React determines a failed checksum, but when it actually tries to determine the part of the code that's different it takes into account such things as `checked` and `checked=""` which actually do not cause a different checksum to be calculated.

If there is no easy way to find the real discrepancy, I think a better way to deal with this warning is to list all places in the markup where there might be a discrepancy instead of just listing the first place since it's likely not to be the actual problem.

![image](https://cloud.githubusercontent.com/assets/2136203/7205789/68eb8618-e4f1-11e4-9352-f9835e0ad127.png)

**Comment by zpao** [comment]
There's some discussion about this already in #3399
