### ISSUE TITLE
PropTypes.oneOf([PropTypes.shape(...)])

### ISSUE THREAD

**Issue by brigand** [facebook/react#3692]
I have a component that expects one type of object or another.  I've tried variations of this:

```
C.propTypes = {
  foo: PropTypes.oneOf([
    PropTypes.shape({
      x: PropTypes.string
    }).isRequired,
    
    PropTypes.shape({
      y: PropTypes.string
    })
  ]).isRequired
};

<C foo={{y: 'text'}} />
```

The warning:

> Warning: Failed propType: Invalid prop `foo` of value `[object Object]` supplied to `C`, expected one of [null,null].

Is this a bug, limitation, or am I doing it wrong?

[jsbin](http://jsbin.com/zubekijaqe/2/edit?js,console,output)

**Comment by zpao** [comment]
I think you want `PropTypes.oneOfType`. `oneOf` is basically an enum.

**Comment by brigand** [comment]
Oh darn, thanks.

**Comment by zpao** [comment]
No problem. You're not the first one to do that (and I'm willing to bet you won't be the last :) )

**Comment by samuel-marandi** [comment]
Life saver. Total Life saver. Thanks

**Comment by alvinsight** [comment]
Same here, I was super confused by the error message 👍
