### ISSUE TITLE
Iteration and conditional tags in JSX

### ISSUE THREAD

**Issue by tobia** [facebook/react#3695]
From the point of view of a React newbie, one of the things that stand out in the XML-like syntax of JSX, with respect to any other templating language out there, is the lack of conditional and iteration tags.

Is there a reason why JSX does not have anything like this?

    <forEach var="book" in={this.props.books}>
        <p>Title: {book.title}</p>
        <p>Author: {book.author}</p>
    </forEach>

and

    <if test={this.props.greet}>
        Hello!
    </if>
    <elseif test={this.props.insult}>
        Go away!
    </elseif>
    <else>
        I don't know
    </else>

For which the obvious compilation (what most of us write today) would be:

    {this.props.books.map(function(book) {
        ...
    })}

and

    {(this.props.greet) ?
        ...
    : (this.props.insult) ?
        ...
    :
        ...
    }

The syntax does not have to be valid XML-like, as in my example above, since it would be compiled to specific Javascript code anyways. For example, these are shorter and still to the point:

    <for book in {this.props.books}>
        ...
    </for>

and

    <if {this.props.greet}>
        ...
    <elseif {this.props.insult}>
        ...
    <else>
        ...
    </if>

I don't mean to start a holy war. React is absolutely great. It just feels a bit wrong not to have some basic iteration and conditional instructions in the XML-like part, whatever the specific syntax is.

It would make the templating parts of JSX more structured and it would make it easier for HTML / CSS people to tweak the markup (add a `<div>` and such) without risk of damaging the control structures.

**Comment by cody** [comment]
I agree with @zpao's answer in #2286.

**Comment by zpao** [comment]
Yea, I stand by my response there :) The crux the argument there is that the language already supports these constructs so use the language. JSX is supposed to be a simple. We really don't want people to learn a new language to use React+JSX. The answer to "how do I do a loop in JSX?" should be "the same way you do a loop in JS".
