### ISSUE TITLE
Shallow renderer fails when component has `contextTypes`

### ISSUE THREAD

**Issue by matthewgertner** [facebook/react#3696]
I am trying to render a component using the preliminary shadow renderer support in TestUtils. A simple reproducible test case of my issue is this

```
    var Foo = React.createClass({
      contextTypes: {
        foo: React.PropTypes.object
      },

      render: function() {
        return null;
      }
    });

    var renderer = TestUtils.createRenderer();
    renderer.render(<Foo/>);
```

When I run this in my Jest test, I get:

```
  - TypeError: Cannot read property 'foo' of undefined
        at ReactCompositeComponentMixin._maskContext (/Users/.../node_modules/react/lib/ReactCompositeComponent.js:336:43)
        at ReactCompositeComponentMixin._warnIfContextsDiffer (/Users/.../node_modules/react/lib/ReactCompositeComponent.js:538:31)
        at ReactCompositeComponentMixin.mountComponent (/Users/.../node_modules/react/lib/ReactCompositeComponent.js:162:12)
```

It looks like this error is thrown whenever the component being rendered has `contextTypes`. I thought perhaps the context was required (although I haven't had any problems omitting it in my actual app), but even when using `withContext` I get the same exception.

**Comment by zpao** [comment]
I think this is a known issue with shallow rendering. cc @jsfb @graue

**Comment by graue** [comment]
@matthewgertner, thanks for the report. Context isn't meant to be supported with shallow rendering (i.e., we haven't tested it), but it looks like you may be able to work around this problem by passing an object as the second argument to `render`:

~~~.js
var renderer = TestUtils.createRenderer();
renderer.render(<Foo/>, {});
~~~

@jsfb, it looks like an additional `context` argument was added to the shallow rendering API in 081feeb2dd97ae0854a7d2448232e651c7330344. What was the thinking here? Can we default this to an empty object?

**Comment by matthewgertner** [comment]
Thanks, @graue, the workaround works great. And I see you posted a fix as well so looking forward to that.
