### ISSUE TITLE
Prepend a "generated code" comment to transformed file

### ISSUE THREAD

**Issue by Firehed** [facebook/react#3699]
It would be beneficial to prepend some sort of "this code is automatically generated, do not modify by hand" comment to files built with the `jsx` binary. 

This is likely to reduce developer confusion, and can also simplify code reviews so that time is not wasted reviewing both the JSX source and the JS output (plus tools such as Phabricator will auto-detect the string `@generated` in changed files and display an appropriate message in the review)

I'd suggest having this be the default behavior since I don't think there are major downsides to it. Alternate options would include some sort of [managed macro](http://managing.blue/2014/09/30/ansible_managed/) or a `--prefix path/to/file` flag.

**Comment by cody** [comment]
I would use Webpack's [`BannerPlugin`](https://webpack.github.io/docs/list-of-plugins.html#bannerplugin) for this. Most other build tools have most likely similar plugins. The advantage is that you have full control over the text message.

**Comment by zpao** [comment]
Not a bad idea, however we're probably not going to add features to react-tools at this point. I would suggest giving babel a look.

**Comment by jimfb** [comment]
Now we've officially changed our code+recommendations to Babel.
