### ISSUE TITLE
CSSTransitionGroup: it does not remove elements from DOM

### ISSUE THREAD

**Issue by weijarz** [facebook/react#3700]
[Check this fiddle](http://jsfiddle.net/flytwokites/kvdpa4hp/)

The component limit log entries to 10, but the old entries does not removed from DOM.

**Comment by MikeBarnhardt** [comment]
Could be related to:
#2549
#3111

**Comment by spicyj** [comment]
Yeah, this is that issue. Works correctly on master as long as you keep the tab focused – if you background the tab you run into #1326 though.
