### ISSUE TITLE
Replace invariant better in prod

### ISSUE THREAD

**Issue by zpao** [facebook/react#3701]
Idea (that I'm pretty sure I saw elsewhere, react-native maybe?)…

We should transform our `invariant` calls to a conditional wrapping the call. We have to check the condition *anyway* and this would reduce the no-op function calls.

In otherwords

```js
function doSomething(someArg) {
  invariant(someArg !== undefined, 'hey doofus, don't pass undefined');
}
```

becomes
```js
function doSomething(someArg) {
  if (!(someArg !== undefined)) {
    invariant(false);
  }
}
```

Hell, we could replace the `invariant(false)` with `throw new Error('whatevs')` and get rid of the function call entirely, though it really doesn't matter much since we're going to throw (plus we'd duplicate the default string).

This might end up be a meaningless optimization…

**Comment by syranide** [comment]
> This might end up be a meaningless optimization…

I believe this is done intentionally (by hand) in some hotspots, so it would seem not.

I guess one could argue if it might not make more sense to simply always use the inline method and drop the argument rather than adding another transform?

**Comment by zpao** [comment]
> I guess one could argue if it might not make more sense to simply always use the inline style and drop the argument rather than adding another transform?

That's a tough sentence to parse. Are you saying we should always write the "optimized" form? If so I would say "no", the first is way easier to read as a human being.

**Comment by huang47** [comment]
do you consider something like [decorator](https://github.com/wycats/javascript-decorators) since jsx has to be transformed anyways?

```js
@invariant(someArg !== undefined, 'hey doofus, don't pass undefined')
```
invariant feels more like a contract to me and codes could be more readable if we separate the warning and real implementation, any thoughts?

**Comment by zpao** [comment]
We have complex invariants that aren't strictly about arguments so while that might be an option for some cases, it doesn't cover us.
