### ISSUE TITLE
ReactMultiChild.unmountChildren throws error when this._renderedChildren is undefined

### ISSUE THREAD

**Issue by Kasu** [facebook/react#3702]
This is leaning more to a question than solid bug report as I have no solid repro. It started occurring in my application recently but it could just as well be due to a bad implementation in my application.

My question is: Is this supposed to be able to happen, ie. should _renderedChildren be able to be undefined (which is what's causing the for loop in unmountChildren to throw an error). If not, what might I be doing wrong for this to be occurring to me in my application?

The code I'm referring to: https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/core/ReactMultiChild.js#L329

**Comment by zpao** [comment]
I'm pretty sure `_renderdChildren` should never be undefined at that point. But I haven't really touched that code. Perhaps @spicyj or @sebmarkbage can say with more certainty.

**Comment by sebmarkbage** [comment]
It could be that something else is throwing and therefore causing `_renderedChildren` to be undefined at that point. We don't do very good error recovery so if you have one error, you'll likely have more subsequent ones like this one. The work on error boundaries should help with this.

It could also be a strange VM bug. We've sometimes found similar errors in our logs from Android phones using Chrome. Is there anything more you can say about the source of these errors?

**Comment by aweary** [comment]
Since there's been no follow-up for +2 years and `ReactMultiChild` isn't used in Fiber I'm going to go ahead and close this one out 👋

**Comment by sophiebits** [comment]
<3
