### ISSUE TITLE
Long tap not submitting form

### ISSUE THREAD

**Issue by spargonaut** [facebook/react#3708]
Hi there,

We've observed that on mobile browsers (specifically Chrome, Firefox, and Safari), if we try to submit a form after holding the submit input button for a while (half second or longer), the onSubmit events for the form do not get triggered.

In comparison, a quick tap triggers our onSubmit callbacks with no issue.

**Comment by imaffett** [comment]
@spargonaut  -  Is the form getting submitted and the event not bubbling?  A demo replicating the issue can help with troubleshooting.

**Comment by jimfb** [comment]
@spargonaut Can you provide two fiddles.  One that demonstrates that it works without React, and a second that demonstrates it works with React?

**Comment by jimfb** [comment]
Ping @spargonaut

**Comment by spargonaut** [comment]
howdy all, sorry for the radio silence, and not responding to the original questions sooner.  A coworker of mine actually posted this question (from my account) when we were pairing while on a project together last year.  I was hoping he would have responded with a more detailed answer to your questions.  Apparently, he did not.  Unfortunately, neither of us are on that project at this point,  and I am unable to provide you any fiddles.  However, I do remember seeing the issue on several different browsers on several different phones (both android and iOS) with the application that we were building.  I also remember that we checked the bug on the production version of instagram at the time and observed the same behavior (yet were unable to verify if the form was being submitted).  IIRC, the form does not get submitted (tested with our application), but since I can't provide a fiddle, I can't provide any more information to help troubleshoot.  Given these circumstances,  I totally understand if you decide to close the issue.  I do appreciate y'all following up (several times) to help us get this resolved.  cheers.
