### ISSUE TITLE
Documentation for ES6 classes

### ISSUE THREAD

**Issue by rogierschouten** [facebook/react#3710]
Which lifecycle methods can I define on a modern ES6-class-style React component? The same as for a classic component spec?  I checked the docs but I can't find much yet on the ES6 classes. Am I missing something?

**Comment by agnosticdev** [comment]
There is a bit of information about ES6 classes at the bottom of Reusable Components:
https://facebook.github.io/react/docs/reusable-components.html#es6-classes

**Comment by rogierschouten** [comment]
Thanks @agnosticdev! Still there is a need for a full-blown example with all the methods in use I think.

**Comment by olegakbarov** [comment]
Yeah, that would be really helpful.

**Comment by zpao** [comment]
Ah, we added notes in the Component API section ([eg a note that replaceState doesn't work](https://facebook.github.io/react/docs/component-api.html#replacestate)), but not for lifecycle methods.

**Comment by ssorallen** [comment]
Noting the constructor's replacement for most use cases of `componentWillMount` falls into this category, and that's not currently mentioned in the docs. A question about its use came up in the Babel blog post about React + ES6: http://babeljs.io/blog/2015/06/07/react-on-es6-plus/#comment-2123220032

**Comment by ankitml** [comment]
This is very confusing for the beginners. I started directly with ES6 style classes and the documentation is of very little help in learning. There is a need of full blown documentation compatible with ES6, as people who are starting with react now dont have any reason for learning non ES6 react. I can volunteer for converting to ES6 but not sure of facebook's commitment towards documentation.

**Comment by gaearon** [comment]
>I can volunteer for converting to ES6 but not sure of facebook's commitment towards documentation.

Great! As you can see from our [recent meeting notes](https://github.com/reactjs/core-notes/blob/master/2016-05/may-19.md#next-steps), we’re not very happy about the situation either.

I think we want to convert the docs to use functional stateless components where state or lifecycle hooks aren’t needed, and ES6 classes wherever state or lifecycle hooks are necessary. We would only leave `createClass` in examples that specifically discuss its usage (e.g. mixins).

@zpao @spicyj Does this sound like what you folks have in mind?

**Comment by jimfb** [comment]
@gaearon Sounds right to me.

**Comment by spicyj** [comment]
Yeah. For now, let's also link to the createClass docs in the tutorial and intro docs after showing React.Component as an alternative for people who don't want to use ES6 classes.

**Comment by raphaelkross** [comment]
I faced problems when migrating to ES6 style - would love to help converting the documentation, this will surely help beginners or developers that aren't used to ES6 style yet!

**Comment by gillchristian** [comment]
I would like to help with the docs.

**Comment by jakegavin** [comment]
I'd also be willing to help out. In terms of autobinding, the core team notes say "We could just always bind in constructor in the documentation." I just want to verify that's the final decision since the wording make it sound a little uncertain?

Are the articles prioritized/triaged in any way or should people just comment in this issue with whatever article they're working on (to prevent duplicate PRs)?

**Comment by gaearon** [comment]
@gillchristian @jakegavin 

Feel free to organize the work between yourselves in this thread! e.g. you can write “I’d like to take pages A, B, and C” so others can see which pages you’ll be working on, and can join to say “cool, I’ll take D and E”. This way we can split the effort and track the individual progress.

>the core team notes say "We could just always bind in constructor in the documentation." I just want to verify that's the final decision since the wording make it sound a little uncertain?

Yes, we won’t use class properties in the docs. We only want to use stable ES2015 syntax. So if we need to bind an event handler, we will do this in the constructor.

**Comment by iammerrick** [comment]
Would it be possible to introduce a toggle between ES5 and ES2015? Similar to what was done for react-dnd? http://gaearon.github.io/react-dnd I am concerned about exclusively showing ES2015 and it will implicitly require a build step + new syntax many developers don't currently understand.

**Comment by raphaelkross** [comment]
+1 to @iamchenxin idea, I love the way React DnD shows multiple versions! Let we know if this will be used now or only in the future.

**Comment by joshburgess** [comment]
I'm down to help out. So, just to be clear.... functional components wherever possible and classes only when lifecycle hooks are necessary?

**Comment by tylermcginnis** [comment]
@iammerrick That is the best option. Removing createClass from the docs will signify to the community that they're deprecated, regardless of intention. I saw keep both until they're fully deprecated.

**Comment by adrianleb** [comment]
Would like to help out!

2 cents:
- As many stateless components as possible, for sure.
- createClass and/or ES6 for other examples, ES6 components with `this` binding on constructor, no ES7 property initializers or binding inside render.

**Comment by ankitml** [comment]
For a start I am taking 'Quick start' pages ie. 

1. Getting Started

2. Tutorial 

3. Thinking in React

**Comment by gillchristian** [comment]
I already did:

- Displaying data
- Interactivity and Dynamic UIs

Will add _Multiple Components_, and PR latter today.

**Comment by gaearon** [comment]
@gillchristian Yes, master branch. Thanks!

**Comment by raphaelkross** [comment]
@gaearon I'm converting:

- Reusable Components
- Transferring Props
- Forms

I'll submit my PR later :)

**Comment by gillchristian** [comment]
_Interactivity and Dynamic UIs_ was already done so I just did:

- Displaying data
- Multiple Components

PR: #6835

Will do some other one latter.

Hope everything is right.

**Comment by steida** [comment]
Maybe a stupid question. Why not skip ES6 and migrate into function stateless components?

**Comment by gaearon** [comment]
>Why not skip ES6 and migrate into function stateless components?

Because many examples in the docs are concerned with state and/or lifecycle hooks. I did suggest that we use functional components where possible though.

**Comment by raphaelkross** [comment]
Reusable Components updated to ES6 - PR #6837 

Let me know if you have any feedback about it, please!

**Comment by alexzherdev** [comment]
If this is not stepping on anyone's toes, I would like to start converting Add-Ons. (one subsection at a time, so that anyone else can work on remaining subsections simultaneously)

Quick question though: for a stateless component with propTypes defined, do we still prefer the functional form?

**Comment by ankitml** [comment]
Yeah, stateless should do. I dont see a reason why not. Check this http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

It says 

> Functional components do not have lifecycle methods, but you can set .propTypes and .defaultProps as properties on the function

**Comment by alexzherdev** [comment]
#6844 is the PR for Add-Ons: Animation. I'm picking up Two-Way Binding Helpers next.

**Comment by ankitml** [comment]
@gaearon In the documentation page 'Thinking in React'. All of the code is in JSFiddle, How can I supply new code for it? 

Next I am picking 'Keyed Fragments' from Add Ons.

**Comment by alexzherdev** [comment]
@gaearon [Two-way binding helpers](https://facebook.github.io/react/docs/two-way-binding-helpers.html) deals with mixins, so I won't be changing it to use ES6 classes. How about just using ES6's shorter function declaration style (`foo() {...}`) plus some lets/consts?

**Comment by ankitml** [comment]
Next I am picking

- Refs to Components
- Tooling Integration (All subsections)

**Comment by alexzherdev** [comment]
Some smaller updates to "Add-Ons: Two-Way Binding Helpers" in #6849.

I'm moving on to tackle "Context" - I think that one would benefit from introducing functional components.

**Comment by ankitml** [comment]
This is cool, soon we will have all the documentation ported to ES6 classes and stateless components. 

Moving on, I am picking first 5 sections of 'Reference'. 

- Top-Level API
- Component API
- Component Specs and Lifecycle
- Supported Tags and Attributes
- Event System

**Comment by alexzherdev** [comment]
#6852 - PR for Context.

**Comment by raphaelkross** [comment]
Transferring Props was converted before in a previous commit. Finishing Forms now.

A question - to stateless components, should we use the normal style:

`function ComponentName(props) { } `

Or the shorthand, like:

`const ComponentName = (props) => { }`

Any standard style we should use?!

**Comment by gustavovnicius** [comment]
Picking the last section of 'Reference': React (Virtual) DOM Terminology

**Comment by gustavovnicius** [comment]
Picking Cloning ReactElements inside Add-ons

**Comment by zpao** [comment]
@gaearon since you're leading this effort, can we track progress somewhere? Maybe hijack the original description with tracking. It's hard to know what the state of this is at a glance.

Also, ideally we land all updates at the same time (or within a couple days) and we get each update to a place that we're happy with before merging. Or if we need to change language we do it immediately as a followup. Otherwise our docs are going to get worse. In particular the tutorial being the main place that people learn React is going to need a lot of attention as topics need to be introduced and discussions intentionally and in the right order.

**Comment by gaearon** [comment]
Hey folks, thank you so much for contributing ❤️ 

I didn’t expect people to react this actively, this is awesome 😄 . It is a large change though, and we need to make it cohesive for it to work well. I’m currently preparing for my talk at ReactEurope next week and can’t dedicate time to this yet, but in a week and a half I will be ready to review all of these changes, address them, and merge them together.

Cheers!

**Comment by ankitml** [comment]
@gaearon It would help if as a community react agrees on a ES6 guidelines, because there are two types of questions. 
1. Which features of ES6 should go into the documentation and which ones can be avoided for now as they haven't fully baked into the whole ES6 ecosystem. 
2. If a feature of ES6 can be used then what are the coding guidelines for it? For there are cases where there are multiple ways of writing it. 

These guidelines also will have to be a living and evolving document unlike writing in a stone.

**Comment by gaearon** [comment]
I think we should do the following:

1. Of ES6 features, use only classes, arrows, and destructuring.
2. Don’t use `let` and `const` because it is distracting while we still have *some* ES5 examples.
3. For functional components, use functional declarations because they work the same everywhere.

These are just guidelines that I have in mind so if they make no sense, let me know.

**Comment by raphaelkross** [comment]
@gaearon - so, to explain and make everything 100% explained:

1. ES6 allowed features: [classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), [arrows](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Functions/Arrow_functions) and [destructing](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

2. Use `var` only, not `const` and `let`

3. Whenever possible, use Stateless Functional Components, declaring them in the following way:

```javascript
var CheckLink = (props) => {
  // This takes any props passed to CheckLink and copies them to <a>
  return (
    <a {...props}>{'√ '}{props.children}</a>
  );
};
````

Else, you can use class to declare the component.

Is that ok?!

**Comment by gaearon** [comment]
Yes, but I propose to declare functional components as

```js
function CheckLink(props) {
  ...
}
```

which is the most familiar form. Arrows are find to use elsewhere though, when helpful.

**Comment by raphaelkross** [comment]
Thank you @gaearon - looks like this is enough standards to enable everybody to write in a consistent style.

I suggest to anyone who contributed to review your code and ensure to follow the above guidelines, or provide feedback.

**Comment by alexzherdev** [comment]
Sounds good. I'll update #6844 to fit this, and push a continuation for #6852 which had some arrows in the functional components.

**Comment by gaearon** [comment]
I’m back from React Europe. I intend to get back to this issue after completing some internal Facebook work to help convert more old-style components to classes.

**Comment by raphaelkross** [comment]
Welcome back @gaearon - React Europe was really awesome!

Just a heads up, I've just updated my PR to follow the standard style we discussed before.

**Comment by mrscobbler** [comment]
Are there are any other pages in the documentation that still need to be changed? I'd like to help out if it's still needed.

**Comment by gaearon** [comment]
Just a quick update: this is still very much on our radar, and all PRs are appreciated.
We have many competing priorities so we’ll get back to this when the time allows.

**Comment by alexzherdev** [comment]
Thanks @gaearon. I have a bunch of PRs pending but will continue with this if I have time. Will post here if I start working on something.

**Comment by discdiver** [comment]
What's the latest on Documentation for ES6 classes? Looks like there was a lot of great work a few months ago and maybe the project has been pushed to a back burner. I think these changes would be of great help to many newer devs.

**Comment by gaearon** [comment]
One of the big problems was that we didn’t have any recommended ES6 environment for people to run that example code in. We took a month to solve it with [Create React App](https://github.com/facebookincubator/create-react-app), and are still working on polishing it so it can be included as the official solution in docs.

Once we have an official solution for running ES6 code, we can start updating the code snippets.  
I know it’s frustrating this takes time, but we need to attack problems one by one.

**Comment by discdiver** [comment]
Cool @gaeron. Create React App looks awesome! Thanks for the quick update.

**Comment by gaearon** [comment]
Thanks again to everyone!
I tweaked and rebased almost all PRs in this thread:

https://github.com/facebook/react/commit/f5f1769583d14803f3e74bf522cf28b10b5a1a5c
https://github.com/facebook/react/commit/9174c29acc60a7f2c1de1b729d7b2ff5492391f8
https://github.com/facebook/react/commit/1b02c731ce68c8b2c33c41276892ad7c1a8b53f8
https://github.com/facebook/react/commit/a6445a18f98c9b5c453acee7fb5783b35603598e

There are a few PRs that didn’t make it due to unaddressed mistakes or outdated content (we are planning to remove some of the old articles and completely rewrite them from scratch). Sorry about this. I also plan to review #6850 and #7068 tomorrow separately.

Thank you so much to everyone who helped! We will be updating the docs more in the coming days, so stay tuned. ❤️

**Comment by gaearon** [comment]
The docs have all been updated with ES6 syntax.
