### ISSUE TITLE
Smulate.click does not trigger browser's default action

### ISSUE THREAD

**Issue by yiminghe** [facebook/react#3720]
https://jsfiddle.net/yiminghe/hzskug9g/2/

In simple terms:

```html
<a href='#xx'>a</a>
```

`Simulate.click(a)` does not cause hash change,  is it intentional?

**Comment by vsiao** [comment]
Yes. `Simulate.click` will *simulate* a click event dispatch (ie. it will run your React `onClick` handler) but won't actually perform any of the default `click()` behavior.

**Comment by thefuture2092** [comment]
Should close this as a non bug

**Comment by zpao** [comment]
It's intentional.

**Comment by jsfb** [comment]
@zpao Why?  I could see reasons to want to make the behavior as similar to real-world as possible.

**Comment by zpao** [comment]
It simulates an event in our synthetic event system so you don't need the DOM.
