### ISSUE TITLE
Shallow rendering should support context

### ISSUE THREAD

**Issue by graue** [facebook/react#3721]
The shallow renderer's render method currently accepts a second (undocumented) argument, `context`, but values you pass don't actually make it through. If you pass `{foo: 'bar'}` the component receives the context object `{foo: undefined}`.

Related: #2393, #3696

**Comment by laskos** [comment]
+1

I've got below warring while tring pass context to renderer:

``
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (flux) while mounting TodoApp (see: http://fb.me/react-context-by-parent)
``

**Comment by glenjamin** [comment]
From what I can tell, this is related to the owner/parent context changes discussed in https://gist.github.com/jimfb/0eb6e61f300a8c1b2ce7

0.13 still uses owner-based contexts, so there's no owner context - but I guess master uses parent-based context so the test passes?

**Comment by glenjamin** [comment]
Here's a little workaround I ended up doing to ensure both owner-context and parent-context is set when using shallow rendering for testing.

```js
function shallowRender(makeComponent, context) {
  context = context || {};
  var ReactContext = require('react/lib/ReactContext');
  ReactContext.current = context;
  var shallowRenderer = TestUtils.createRenderer();
  shallowRenderer.render(makeComponent(), context);
  ReactContext.current = {};
  return shallowRenderer.getRenderOutput();;
}

// Usage:
var output = shallowRender(() =>
  <MyComponent
    with={props}
    and={stuff}
  />,
  { here: 'is', my: 'context'}
);
```

Note use of the arrow function to delay creation of the component until owner-context can be set.

**Comment by rearadmiral** [comment]
I'm trying out the shallow renderer and my components are using ReactIntl.

I have to render them like this: shallowRenderer.render(element, { locales: null, messages: null }); so that I won't get an error about there being no locales key in the context during ReactCompositeComponentMixin._maskContext.

Is this a general limitation related to this issue or does that sound like something specific to the ReactIntl library?

**Comment by mmw** [comment]
How would you use `shallowRender` with `ReactTestUtils#Simulate`? I'm trying to test interactions on an element that needs context but also needs `renderIntoDocument` so `findRenderedDOMComponentWithClass` can find the dom node to simulate events on.

**Comment by graue** [comment]
Looks like this got fixed at some point. I'm not sure when, but there's been a passing test since #3912 was merged. Yay!
