### ISSUE TITLE
Requiring Polymer in ReactMount test breaks manual test on several browsers

### ISSUE THREAD

**Issue by sairion** [facebook/react#3728]
I have been looking at #3598 and found out requiring Polymer (actually, WebComponents.js) breaks the tests with messages like:

```
    Error: Assertion failed in http://192.86.0.1:9999/test/
```

Commenting out https://github.com/facebook/react/blob/master/src/browser/ui/__tests__/ReactMount-test.js#L23 will make all tests green. 

It seems like Polymer in Chrome does not override original DOM constructors therefore no errors occur in Chrome, but in latest Safari and Firefox, about 3x tests gets failed due to this.

**Comment by zpao** [comment]
@jsfb, can you take a look at this once we're past context changes

**Comment by jimfb** [comment]
I'm pretty sure we fixed this in https://github.com/facebook/react/pull/3923 or earlier, closing.  Re-open if not fixed.
