### ISSUE TITLE
Event handler not triggered for element in a container which prevent bubbling.

### ISSUE THREAD

**Issue by themez** [facebook/react#3729]
I'm using react with a map library, I use react to render elements in a container which provided by the map library.

The problem is that the container prevent event bubbling, I checkout reactjs source code found the event emitter listen on html document and depend on event bubbling to dispatch event.

How can I make the onClick handler to work? I currently addEventListener manually but don't think it an elegant way.

```
<body>
  <container preventBubbling>
    <ReactElement onClick={this.handleClick}/>
  </container>
</body>
```

I'm wondering could react provide an option to bind event listener on html elements instead of entire document.

**Comment by zpao** [comment]
If you use `onClickCapture` does that work? You'd be handling the event in the capture phase so things may be slightly different.

As to why we don't add event listeners directly to each element, [this article](http://www.nczonline.net/blog/2009/06/30/event-delegation-in-javascript/) is a good read. Browsers have improved in 5 years but it's still generally a good idea (especially in a library used to build very large applications).

**Comment by themez** [comment]
onClickCapture not work either, guess both way propagation is cancelled. OK.. looks like bind event manually is the only solution.
