### ISSUE TITLE
React onClick Event overridden in Android Browser?

### ISSUE THREAD

**Issue by Akamaozu** [facebook/react#3732]
Maybe it's just the Galaxy S4 *(tried Chrome and the standard browser)* but clicking an email address triggers a native email intent. 

[JS BIN TEST CASE][1] - *note there is no mailto: or even an anchor tag*.

Noticed it when I used an email address as the text for a "button" (div with click event).

Started investigating and it seems like if there is no browser click event listener on the email container, Android opens up the email intent. Every other part of the same element is safe to click on except the email address.

Try clicking on the email addresses in the [test case][2] using a browser on your Android device to see if this is just a Galaxy S4 problem or if it's more widespread.

  [1]: http://jsbin.com/vebiyesebu/4/edit
  [2]: http://jsbin.com/vebiyesebu/4/edit

**Comment by spicyj** [comment]
I think this is a feature of Android browsers unrelated to React. See http://stackoverflow.com/questions/7771687/disable-automatic-linking-of-mailing-address-in-webview.
