### ISSUE TITLE
Warnings: can they tell you which tree or component is the culprit?

### ISSUE THREAD

**Issue by tmcw** [facebook/react#3733]
I'm upgrading a relatively large codebase from React 0.12.x to 0.13.x. I've hit a variety of warnings, the latest being:

> Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.

Exploring the stack starts to give me hints of the culprit, but in this case it's a `div` element and one of very many. Is there anything I or React can do to make these warnings more debuggable?

**Comment by spicyj** [comment]
Not super easily, unfortunately – but if you break on that warning in the debugger you should be able to see what objects are involved (and perhaps even the problematic render function) by looking down the stack.

**Comment by spicyj** [comment]
We do our best to include context when we can but it's not always easy to do.

**Comment by zpao** [comment]
Can we look at owner for this one?

**Comment by spicyj** [comment]
We'd have to thread the owner through flattenChildren, which isn't the easiest. These should already warn on element creation time though in most cases and then you have the stack…

**Comment by TrySpace** [comment]
I've had this once when I outputted an Object for testing like:

<div>
    {@props._auth}
</div>

Then React just puts each key and each value in a `<span>` without keying them.

I think either spans like that should be keyed automatically, or the error should be more specific.

**Comment by spicyj** [comment]
@TrySpace Can you be more specific, preferably with a code example?

**Comment by TrySpace** [comment]
@spicyj sorry, forgot to indent, and put some example code in there (coffeescript)

**Comment by miksago** [comment]
I hit into this as well, and didn't figure out the error for quite sometime. Perhaps it'd make sense to have some sort of configuration option that is “don't accept objects as children” — in my case, the rendering of an object was purely accidental.

**Comment by zpao** [comment]
We're going to stop supporting objects as children so we aren't going to make it configurable. As you can see it causes confusing issues and also stops us from making other advancements.

Going to close out as it seems like we can't make this part of the warning better. See #4840 for a related discussion about making the warning better in a different way.
