### ISSUE TITLE
Update "our" jsfiddles to use SSL

### ISSUE THREAD

**Issue by zpao** [facebook/react#3735]
There are a couple jsfiddles on the site that aren't using SSL but we link to their SSL pages. Then they don't work. We should fix them. Any that are in official docs or blogs posts and published by us should work.

**Comment by jsfb** [comment]
List of the ones I see to check/track:
 - [ ] jsfiddle.net/ufe8k/1/
 - [ ] jsfiddle.net/reactjs/69z2wepo/
 - [ ] jsfiddle.net/reactjs/5vjqabv3/
 - [ ] jsfiddle.net/reactjs/69z2wepo/
 - [ ] jsfiddle.net/reactjs/5vjqabv3/
 - [ ] jsfiddle.net/reactjs/69z2wepo/
 - [ ] jsfiddle.net/reactjs/5vjqabv3/
 - [ ] jsfiddle.net/reactjs/69z2wepo/
 - [ ] jsfiddle.net/reactjs/5vjqabv3/
 - [ ] jsfiddle.net/reactjs/yun1vgqb/
 - [ ] jsfiddle.net/reactjs/zafjbw1e/
 - [ ] jsfiddle.net/reactjs/n47gckhr/
 - [ ] jsfiddle.net/reactjs/yun1vgqb/
 - [ ] jsfiddle.net/reactjs/zafjbw1e/
 - [ ] jsfiddle.net/reactjs/n47gckhr/

**Comment by jsfb** [comment]
All the fiddles:
jsproch-mm:react jsproch$ grep -R -o "jsfiddle\\.net/[A-Za-z0-9]*/[A-Za-z0-9]*/" .
 - [ ] ./docs/_posts/2013-06-02-jsfiddle-integration.md:jsfiddle.net/vjeux/kb3gN/
jsfiddle.net/vjeux/VkebS/
- [ ] ./docs/_posts/2013-06-05-why-react.md:jsfiddle.net/fv6RD/3/
- [ ] ./docs/_posts/2013-06-19-community-roundup-2.md:jsfiddle.net/vla/Cdrse/
- [ ] ./docs/_posts/2013-07-03-community-roundup-4.md:jsfiddle.net/aabeL/1/
- [ ] ./docs/_posts/2013-07-03-community-roundup-4.md:jsfiddle.net/ufe8k/1/
- [ ] ./docs/_posts/2013-07-03-community-roundup-4.md:jsfiddle.net/R8f5L/5/
- [ ] ./docs/_posts/2013-09-24-community-roundup-8.md:jsfiddle.net/vjeux/QL9tz/
- [ ] ./docs/_posts/2013-11-05-thinking-in-react.md:jsfiddle.net/6wQMG/embedded/
- [ ] ./docs/_posts/2013-11-05-thinking-in-react.md:jsfiddle.net/QvHnx/embedded/
- [ ] ./docs/_posts/2013-11-05-thinking-in-react.md:jsfiddle.net/3Vs3Q/embedded/
- [ ] ./docs/_posts/2013-12-23-community-roundup-12.md:jsfiddle.net/ssorallen/fEsYt/
- [ ] ./docs/_posts/2013-12-23-community-roundup-12.md:jsfiddle.net/ssorallen/fEsYt/
- [ ] ./docs/_posts/2014-01-06-community-roundup-14.md:jsfiddle.net/djkojb/qZf48/
- [ ] ./docs/_posts/2014-01-06-community-roundup-14.md:jsfiddle.net/SubtleGradient/ue2Aa/
- [ ] ./docs/docs/getting-started.ja-JP.md:jsfiddle.net/reactjs/69z2wepo/
- [ ] ./docs/docs/getting-started.ja-JP.md:jsfiddle.net/reactjs/5vjqabv3/
- [ ] ./docs/docs/getting-started.ko-KR.md:jsfiddle.net/reactjs/69z2wepo/
- [ ] ./docs/docs/getting-started.ko-KR.md:jsfiddle.net/reactjs/5vjqabv3/
- [ ] ./docs/docs/getting-started.md:jsfiddle.net/reactjs/69z2wepo/
- [ ] ./docs/docs/getting-started.md:jsfiddle.net/reactjs/5vjqabv3/
- [ ] ./docs/docs/getting-started.zh-CN.md:jsfiddle.net/reactjs/69z2wepo/
- [ ] ./docs/docs/getting-started.zh-CN.md:jsfiddle.net/reactjs/5vjqabv3/
- [ ] ./docs/docs/thinking-in-react.ko-KR.md:jsfiddle.net/reactjs/yun1vgqb/
- [ ] ./docs/docs/thinking-in-react.ko-KR.md:jsfiddle.net/reactjs/zafjbw1e/
- [ ] ./docs/docs/thinking-in-react.ko-KR.md:jsfiddle.net/reactjs/n47gckhr/
- [ ] ./docs/docs/thinking-in-react.md:jsfiddle.net/reactjs/yun1vgqb/
- [ ] ./docs/docs/thinking-in-react.md:jsfiddle.net/reactjs/zafjbw1e/
- [ ] ./docs/docs/thinking-in-react.md:jsfiddle.net/reactjs/n47gckhr/

If a fiddle is wrong and not owned by reactjs, it might be worth forking under the reactjs account.

**Comment by zpao** [comment]
> docs/_posts/2013-11-05-thinking-in-react.md:https://jsfiddle.net/6wQMG/embedded/
> docs/_posts/2013-11-05-thinking-in-react.md:https://jsfiddle.net/QvHnx/embedded/
> docs/_posts/2013-11-05-thinking-in-react.md:https://jsfiddle.net/3Vs3Q/embedded/

Those can just copy the updated ones we already have in the updated thinking in react docs page

> docs/_posts/2013-09-24-community-roundup-8.md:https://jsfiddle.net/vjeux/QL9tz/

This is broken anyway.

> docs/_posts/2013-12-23-community-roundup-12.md:https://jsfiddle.net/ssorallen/fEsYt/

This one is just http in the docs. https works so we can update to that.

> docs/_posts/2014-01-06-community-roundup-14.md:https://jsfiddle.net/djkojb/qZf48/

Also broken anyway (that might be on our fiddle integration script)

> docs/_posts/2014-01-06-community-roundup-14.md:https://jsfiddle.net/SubtleGradient/ue2Aa/

Works on http, might be better to just link.

For any of the https that we don't own, it might be best to just link to them instead of embedding.

**Comment by jsfb** [comment]
Fix merged, closing bug.
