### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by tommyZZM** [facebook/react#3736]
rt.

**Comment by vsiao** [comment]
I help maintain unofficial type definitions over at https://github.com/borisyankov/DefinitelyTyped/tree/master/react, which you might find useful. There are usage examples in the test files.

**Comment by spicyj** [comment]
We don't plan to maintain TS definitions, but you can use the ones @vsiao linked. If there's other things we can do to be more TypeScript-compatible, let us know. You should already be able to use TypeScript classes as React components like any other ES6-esque class.

**Comment by tommyZZM** [comment]
thanks

**Comment by chicoxyzzy** [comment]
there is some work on TypeScript repo you might be interested in
https://github.com/Microsoft/TypeScript/pull/2673
