### ISSUE TITLE
Kill react-tools in it's current form

### ISSUE THREAD

**Issue by zpao** [facebook/react#3743]
I shipped jstransform 0.11, which now has the CLI and API from react-tools. The intention was to deprecate react-tools entirely so we have 1 less thing to support (and it lets us ship transform updates outside the React release cycle). I'm not sure if we just won't ship react-tools 0.14 at all or if it'll basically re-ship jstransform.

If you're a hawk and watching this repo, and wondering what that means for you, here are your options:
- Switch to jstranform. I wrote [a migration guide](https://github.com/facebook/jstransform#migration-guide) for you.
- Switch to babel. It supports many of the same things jstransform does and more.
- Do nothing. We don't really suggest this but it's an option. We won't un-ship react-tools from npm so as long as you used versions correctly, you should be able to keep chugging along.

- [x] remove transforms from here
- [x] make sure our build still works
- [x] make a react-tools that still works like the one we have
- [x] make sure JSXTransformer still works (did not make a new one of these for jstranform).

**Comment by gaearon** [comment]
I'm a bit frustrated that `npm install facebook/react` installs `react-tools` instead. It would have been nice if it installed React master, as expected. Will deprecation of RT has a side effect of fixing this?

**Comment by zpao** [comment]
It probably won't fix it since we have a build process. The better fix for that (which we'll get back on track with) is to have us publish alphas to npm.

**Comment by zpao** [comment]
Ok, we'll still need to add a proper deprecation notice on npm and probably write a blog post, but otherwise we're all done here.

**Comment by jimfb** [comment]
Deprecation notice applied to npm, blog post posted, I think we're done here.

**Comment by zpao** [comment]
Heh, thanks for coming back and closing. We're long done.
