### ISSUE TITLE
Implement syntax highlighting for code snippets written in markdown on website

### ISSUE THREAD

**Issue by sudheesh001** [facebook/react#3748]
The code snippets for `A Component using external plugins` and other code snippets across the homepage have syntax highlighting features, It'd be great to also have something similar for the resulting markdown output being displayed from the given input.

It'd be great to have syntax highlighting like that of Github on the markdown results of the code snippet present on the react webpage.
eg.
```javascript
var input = [];
console.log(input);
```

**Comment by zpao** [comment]
Are you suggesting we make syntax highlighting in the output of our Markdown example?

**Comment by sudheesh001** [comment]
@zpao , Yeah, Since it's already implemented on the page for the snippets, it'd be great to output the results of the markdown example with syntax highlighting.

**Comment by zpao** [comment]
We're not going to do that. It's a simple markdown example and the mechanism for highlighting in our docs is vastly different.
