### ISSUE TITLE
Differences a jQuery CDN URL in tutorial.md

### ISSUE THREAD

**Issue by kubosho** [facebook/react#3750]
https://github.com/facebook/react/blob/master/docs/docs/tutorial.md

- "Getting started" defined to `<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>`.
- "Adding Markdown" defined to `<script src="https://code.jquery.com/jquery-1.10.0.min.js"></script>`.

Should be unify to `https://code.jquery.com/jquery-2.1.3.min.js` or `https://code.jquery.com/jquery-1.10.0.min.js`?

**Comment by zpao** [comment]
Nice find. We should use the same version. Are you interested in creating a PR to update it?

**Comment by kubosho** [comment]
@zpao
Yes I am. I looking at  https://github.com/facebook/react/blob/master/CONTRIBUTING.md.

I think will attempt to unify the `<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>`.

I would like to create a PR so I'll do that soon.
