### ISSUE TITLE
Claim react.js.org

### ISSUE THREAD

**Issue by ianobermiller** [facebook/react#3754]
Just learned about http://dns.js.org/. Any objections to claiming http://react.js.org? If not, I'll submit a PR for the gh-pages branch to add the CNAME file.

**Comment by ianobermiller** [comment]
Then again, that would cause react.js.org to be the canonical site for React, which may not be what we want, since we don't control the domain. https://help.github.com/articles/about-custom-domains-for-github-pages-sites/

**Comment by ianobermiller** [comment]
Then again, it doesn't look like it will automatically redirect facebook.github.io/react (ex. https://github.com/CKGrafico/radial.js) so we should be fine.

**Comment by zpao** [comment]
I don't want that to be the canonical link. I still have plans to eventually make reactjs.com a thing (with content that doesn't work on gh-pages). A redirect would be fine so we could update when we get there (I guess we'd need a different gh-page project for that).

**Comment by ianobermiller** [comment]
I've checked a bunch of other org pages, and it doesn't cause the github version to redirect at all. So this would be purely additive.
