### ISSUE TITLE
Make ReactShallowRenderer.render act more similar to React

### ISSUE THREAD

**Issue by gaearon** [facebook/react#3760]
In my opinion,
- `render` should return a component instance
- calling `render` second time should unmount the previously mounted component if type or key is different

Does this make sense?

**Comment by gaearon** [comment]
Currently rendering two different components of different types with `ReactShallowRenderer` in the same test will mess it up.

**Comment by zpao** [comment]
cc @graue

**Comment by gaearon** [comment]
It looks like `ReactShallowRenderer#render` could use `shouldUpdateReactComponent` to bail out of reconciling, and reset `this._instance` in `unmount`.

**Comment by gaearon** [comment]
For the record, this works better for me:

```js
// ++++++++
var shouldUpdateReactComponent = require("./shouldUpdateReactComponent");
// ++++++++

ReactShallowRenderer.prototype.render = function(element, context) {
  var transaction = ReactUpdates.ReactReconcileTransaction.getPooled();
  this._render(element, transaction, context);
  ReactUpdates.ReactReconcileTransaction.release(transaction);
  // ++++++++
  return this._instance.getPublicInstance();
  // ++++++++
};

ReactShallowRenderer.prototype.unmount = function() {
  if (this._instance) {
    this._instance.unmountComponent();
    // ++++++++
    this._instance = null;
    // ++++++++
  }
};

ReactShallowRenderer.prototype._render = function(element, transaction, context) {
  // ++++++++
  var prevElement = this._element;
  if (this._instance && !shouldUpdateReactComponent(prevElement, element)) {
    this.unmount(); 
  }
  // ++++++++

  if (!this._instance) {
    var rootID = ReactInstanceHandles.createReactRootID();
    var instance = new ShallowComponentWrapper(element.type);
    instance.construct(element);

    instance.mountComponent(rootID, transaction, context);

    this._instance = instance;
  } else {
    this._instance.receiveComponent(element, transaction, context);
  }

  // ++++++++
  this._element = element; 
  // ++++++++
};

```

I can prepare a PR if you agree with these changes.

**Comment by graue** [comment]
@gaearon: When I said this was already supposed to be supported, I was thinking of the behavior in this test:

https://github.com/facebook/react/blob/master/src/test/__tests__/ReactTestUtils-test.js#L92

We should maybe support your suggested way as well, but does that approach to testing updates help you?

**Comment by gaearon** [comment]
Oh, I see now. I didn't understand that example at first.

I guess I could use that approach, but I'd still prefer consistency with React's `render` method. Also I'm going to *really* need that `shouldUpdateReactComponent` logic because it's related to the very thing I'm going to test.

**Comment by glenjamin** [comment]
I've just noticed another related case - it seems that you can't re-render a different component with the same shallow renderer at all. Here's a repl session to demo:

```
> var t = require('react-addons-test-utils')
undefined
> var React = require('react')
undefined
> X = React.createClass({ render: function() { return $('span', {}, this.props.x) }})
[Function]
> Y = React.createClass({ render: function() { return $('div', {}, 456) }})
[Function]
> $ = React.createElement
[Function]
> var r = t.createRenderer()
undefined
> r.render($(X, {x:2}))
undefined
> r.getRenderOutput()
{ '$$typeof': Symbol(react.element),
  type: 'span',
  key: null,
  ref: null,
  props: { children: 2 },
  _owner: null,
  _store: {} }
> r.render($(Y))
undefined
> r.getRenderOutput()
{ '$$typeof': Symbol(react.element),
  type: 'span',
  key: null,
  ref: null,
  props: { children: undefined },
  _owner: null,
  _store: {} }
```

**Comment by necolas** [comment]
This is a very old issue that we haven't acted on for several years. I believe we also want to discourage continued use of the shallow renderer. Closing this for now
