### ISSUE TITLE
React renders children <image> as <img>

### ISSUE THREAD

**Issue by framp** [facebook/react#3763]
As of now, `createNodesFromMarkup` is rendering React children dumping all the code in a `div` using `innerHTML` and then inserting/replacing the nodes back.

Unfortunately with svg's `image` tag we get back `img`.

    <g className="shadows">
      <image xmlns="http://www.w3.org/2000/svg"
                   xmlnsXlink="http://www.w3.org/1999/xlink"
                   xlinkHref={this.state.shadows}
                   x="0" y="0" width={this.state.width} height={this.state.height}>
      </image>
      <image xmlns="http://www.w3.org/2000/svg"
                   xmlnsXlink="http://www.w3.org/1999/xlink"
                   xlinkHref={this.state.shadows}
                   x="0" y="0" width={this.state.width} height={this.state.height}>
      </image>
    </g>
Code like this works fine (because it's actually using `React.createElement()`)

    {this.state.parts.map(function(part) {
      return <pattern key={part.id} id={'pattern-' + part.id}
                               patternUnits="userSpaceOnUse" width="50" height="50">
                  <image xmlns="http://www.w3.org/2000/svg"
                               xmlnsXlink="http://www.w3.org/1999/xlink"
                               xlinkHref={part.image}
                               x="0" y="0" width="50" height="50">
                  </image>
                </pattern>
Code like this is actually generating useless `<img>` tags via `createNodesFromMarkup`.

I see three broad solutions:
 - I coded up an ugly solution which keep track of whether a node is a `svg` child and append the markup to a `svg` tag instead. It adds a couple of checks to all the HTML children flow (which is something I'm not happy about) and doesn't work in Safari browsers out of the box as they don't have innerHTML/innerSVG ([polyfill](https://code.google.com/p/innersvg/))
 - The cleanest solution would be to just change `createNodesFromMarkup` to actually parse the markup and just use `createElement` for both HTML and SVG nodes (but I feel like this hasn't been done for performance reasons vs innerHTML - am I right?).
 - We can simply detect the `image` tag and deal with it after we used createNodesFromMarkup - hackish but doesn't break everything and sounds quite painless

I'll be happy to work on a PR with the fix but I'm not that familiar with the philosophy of the project and what would be the direction you'd want.

Thanks

**Comment by spicyj** [comment]
getMarkupWrap is already meant to handle these cases:

https://github.com/facebook/react/blob/master/src/vendor/core/getMarkupWrap.js

Unfortunately it looks like `image` isn't in the list. Since we don't want to add these all one at a time we'll need some alternative way to deal with this.

**Comment by framp** [comment]
Sounds great!
I've adapted my solution to use `getMarkupWrap` and I think it could be a solution to our problem:
https://github.com/framp/react/commit/526a5fba8187023c52279111f83389c10bd7d68d

I'm just passing the future root node to `getMarkupWrap` and check if the root node of the element will be an instance of `SVGElement`.
In this way we don't have to hardcode all the SVG tags.

**Comment by framp** [comment]
Closing it over https://github.com/facebook/react/pull/3808
