### ISSUE TITLE
reactid bug?

### ISSUE THREAD

**Issue by lifei** [facebook/react#3766]
Code
```
    var ListNavbar = React.createClass({
        render: function () {
            var header = "Contacts";
            var style = {left: "22px"};
            return (
                <div className="navbar-wrapper">
                    <div className="left"></div>
                    <div className="center" style={style}>{header}</div>
                    <div className="right">
                        <a href="contact.html" className="link icon-only">
                            <i className="icon icon-plus">+</i>
                        </a>
                    </div>
                </div>
            );
        }
    });
React.render(<ListNavbar />, document.getElementById('list-navbar'));
```

data-reactid in DOM element looks like: `data-reactid=".1.0.0.$[object Object].0.1"`

is this a bug?

**Comment by jsfb** [comment]
I just ran this example with React 0.13.2 and my data-reactid looks like: .0.2.0.0.

What browser and what version of React are you using?  Can you create a jsfiddle that demonstrates the issue?

**Comment by syranide** [comment]
`$[object Object]` means you have `<comp key={anObject} />` somewhere in your code, everything that goes in `key` is stringified so you can only have primitives there.

**Comment by lifei** [comment]
@syranide is right, thanks
