### ISSUE TITLE
Updating state fails in componentDidMount client side, when using server side rendering

### ISSUE THREAD

**Issue by mikecardwell** [facebook/react#3768]
I'm trying to render a React component on the server side as html, serve that up, and then re-render
client side. I've included a cut down example below whereby "The time is x" is displayed, where x
is updated once per second.

Given this simple class:

```javascript
React.createClass({

    getInitialState: function () {
        return {
            now: 0
        };
    },

    componentDidMount: function () {
        this.setNow();
        this.pid = setInterval(this.setNow, 1000);
    },

    componentWillUnmount: function componentWillUnmount() {
        clearTimeout(this.pid);
    },

    setNow: function () {
        this.setState({ now: (new Date()) + '' });
    },

    render: function () {
        return (
            <div>
                The time is {this.state.now}
            </div>
        );
    }

});
```

The server side HTML is generated correctly with a suitable data-reactid attribute.

On the client side, the first line in componentDidMount causes an error. "0" is displayed for the first second, but then is updated as expected once per second after that. The error message logged to the console is:

> Error: Invariant Violation: findComponentRoot(..., .1ba6uva93i8.1.0.1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a &lt;tbody&gt; when using tables, nesting tags like &lt;form&gt;, &lt;p&gt;, or &lt;a&gt;, or using non-SVG elements in an &lt;svg&gt; parent. Try inspecting the child nodes of the element with React ID ``.

The documentation for componentDidMount states: "Invoked once, only on the client (not on the server), immediately after the initial rendering occurs." - This implies to me that it should be perfectly safe to update the state here to diverge from the state encoded in the initial server side HTML representation... If I replace the "this.setNow()" with "setTimeout(this.setNow, 1)" that fixes things, but it seems like a nasty hack to me.

**Comment by syranide** [comment]
> This implies to me that it should be perfectly safe to update the state here to diverge from the state encoded in the initial server side HTML representation... If I replace the "this.setNow()" with "setTimeout(this.setNow, 1)" that fixes things, but it seems like a nasty hack to me.

Yeah your code seems fine to me. If React is able to reuse the markup it should just work and if not React will emit a warning but it should still just work (suboptimally). As it works when you defer the update seem to indicate that React is doing something wrong I would say.

#1839 *might* be related, not sure which PR/commit is relevant though. cc @spicyj

**Comment by spicyj** [comment]
This example works fine for me:

http://jsbin.com/vupagekuvi/2/edit?html,js

@mikecardwell Any chance you can get a repro in jsbin?

**Comment by mikecardwell** [comment]
I probably should have mentioned this earlier, but I am actually building the entire document using React, not just part of the body. This has made it difficult for me to get an example into jsbin because it's using an external js file. I have however put up a couple of examples on some of my own hosting. I realise this isn't as convenient, but I hope it is still useful:

https://grepular.com/react/broken/
https://grepular.com/react/working/

The HTML at both URLs is identical. The only difference is that in the "browser.js" which is referenced inside /working/, I use "setTimeout(this.updateNow, 1)" instead of "this.updateNow()"

**Comment by spicyj** [comment]
Thanks for the example. Looks like this happens with full-page rendering when you try to re-run the React.render in the `head` tag because the body hasn't been parsed yet and so React can't find it when it goes to do an update. I think it's best for us to not support this pattern (and recommend you call React.render in a script tag at the end of your body or on DOM ready) but maybe we can give a warning for this.

**Comment by mikecardwell** [comment]
Ahhh. Thanks. Not sure how I missed that.

**Comment by jsfb** [comment]
Looks like this is resolved on your end, so I'm going to close this bug and track warning-for-render-in-head as a separate issue for clarity: https://github.com/facebook/react/issues/3800
