### ISSUE TITLE
Numeric character reference in props not possible due to escaping

### ISSUE THREAD

**Issue by Taig** [facebook/react#3769]
The HTML [numeric character reference][1] / named character reference does not work for prop-values which is a common use case, e.g. for icons fonts (`data-icon="&#x1234;"`).

It does work for raw strings in this fashion:

````html
<i data-icon="&#xf00f;" />
````

But breaks in other scenarios:
````jsx
<i data-icon={'&#x' + code + ';'} />
<i data-icon={'\u0026#x' + code + ';'} />
React.DOM.i( { 'data-icon': '&#x' + code + ';' } )
````

Yielding:

````html
<i data-icon="&amp;#x1234;" />
````

The only workaround I found so far is using dangerouslySetInnerHTML, which is a bit unfortunate as it forces me to introduce another wrapper for using a basic HTML feature.

[JsFiddle sample][2]

[1]: http://en.wikipedia.org/wiki/Numeric_character_reference
[2]: https://jsfiddle.net/69z2wepo/7284/

**Comment by jabjab** [comment]
This is already documented. https://facebook.github.io/react/docs/jsx-gotchas.html#html-entities

**Comment by spicyj** [comment]
You can do

<i data-icon={String.fromCharCode(0xf00f)} />

or if you have it as a string for some reason,

<i data-icon={String.fromCharCode(parseInt('f00f', 16))} />

Only the JSX compiler parses HTML entities; React doesn't so you should use the Unicode character instead.

**Comment by antoinejaussoin** [comment]
Thanks @spicyj , you saved my life (well, at least a few hours of my time) here

**Comment by piotr-cz** [comment]
Documentation doesn't mention any way how to use html entities anymore, but solution given by @spicyj still works

**Comment by mohas** [comment]
I think JSX compilers has gotten smarter and now I can't easily produce meta tags like og:url or og:image in full stack react frameworks like next.js
