### ISSUE TITLE
Large speed loss from hidden element using inline styles

### ISSUE THREAD

**Issue by jbhatab** [facebook/react#3771]
I came across this speed test using react and removed a hidden element in the table load to see how it impacted the speed. When you remove the hidden element the speed gets 4x better. The element was a simple td element that had inline styles to hide it. I was just surprised at the speed difference and wanted to know why this was happening. Is it because of inline styles or it being a hidden element?

Test with hidden element
https://dl.dropboxusercontent.com/u/99598482/react-hidden-element-speed-test/initial-load/react-with-hidden-element%20copy.html

Test no hidden element
https://dl.dropboxusercontent.com/u/99598482/react-hidden-element-speed-test/initial-load/react-no-hidden-element.html

**Comment by cody** [comment]
The fast version seems to creates 7000 `<td>`s that contain text, numbers or nothing. The slow version has additionally 7000 `<td>`s with `<input>` elements. The `<input>`s are not visible, but they are still in the dom and their logic is functioning. `<input>`s are complicated, so I am not surprised about the speed. It is a fun thing to try in a speed test, but in a real world app I would not use 7000 `<input>`s.

**Comment by jbhatab** [comment]
It was a speed test from http://jsblocks.com. I looked into their test and they beat react but only with the unnecessary hidden inputs. It was a weird test and I agree you wouldn't do that in a real project.

Then I was just curious why react got so much slower with the inputs. Still a little curious why the hidden element has a larger impact than jsblocks.

**Comment by zpao** [comment]
Inputs have somewhat complicated logic to handle user interactions and making sure state changes are handled correctly. This unfortunately means there is probably more code running for each of these than there is using jsblocks. Now we probably could do a bit of optimization for `type="hidden"` inputs so we don't have to do as much setup for user handling. That would be interesting, though not sure how valuable it would actually be in typical cases with a handful of inputs (7000 hidden inputs is a pretty contrived use case).

**Comment by jbhatab** [comment]
I really don't think it's necessary. The only time I could see this is applicable is a really large table that needs inline editing. But even then I think you could easily not even render the inputs and just have them render on click pretty easily. 

Thanks for the info though, cleared things up.
