### ISSUE TITLE
BC break in 0.13?

### ISSUE THREAD

**Issue by rodsouto** [facebook/react#3773]
Hi, this code

```javascript
var Hello = React.createClass({
    render: function() {
        return <div>Hello --> {this.props.name}</div>;
    }
});
 
React.render(<Hello name="World" />, document.getElementById('container'));
```

works in 0.12 but fails in 0.13 with the following message

```javascript
Uncaught Error: Parse Error: Line 4: Unexpected token >
    at http://fiddle.jshell.net/22nht5ws/1/show/

return <div>Hello --> {this.props.name}</div>;
```

v0.12 fiddle: http://jsfiddle.net/66xfc1e1/
v0.13 fiddle: http://jsfiddle.net/22nht5ws/2/

Any idea what the problem could be? :)

**Comment by zpao** [comment]
We made a change to JSX parsing in 0.13 to fix some somewhat ambiguous cases around `>`. [We documented this in the changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#breaking-changes-3) (which also has a link to an npm package we distributed to find and update places that would be an issue). In your case you can probably just use `&rarr;` for a full arrow or `&gt;` if you really want to keep ascii arrows :)
