### ISSUE TITLE
Error stacks in general

### ISSUE THREAD

**Issue by danschumann** [facebook/react#3775]
Hi all,

Well, I like the project and using it for a few of my own, but I have a gripe... errors.  When refactoring large amounts of code, I find that if I call 

```
something = undefined // i forgot to require dependency
React.render(<something />, el)
// super unhelpful error message
```

I get a very unhelpful error.  There are other ways to error-out react as well, and they also seem to produce unhelpful errors with stack traces that don't escape React most of the time, making it near impossible to debug.

Is it possible for a better stack trace that will tell me what line, or perhaps it would tell me what actually went wrong ( such as I was trying to create an element from undefined )?

**Comment by spicyj** [comment]
Thanks for the report.

This keeps coming up. I know @sebmarkbage was reluctant but we should probably just add a hard error for this in createElement.

**Comment by spicyj** [comment]
@danschumann You should have seen a console warning for this though. Did you?

**Comment by agnosticdev** [comment]
I would have to agree, I was debugging an error the other day and the error message read like this: 

```js
Uncaught Error: Parse Error: Line (some number): Unexpected end of input
```
The issue ended up being the I forgot the forward slash on my element, but still, I was looking at my classes to try and debug the issue.  See an example [here](http://ea4e17cd9a5c172baab1-6da04ed897448c7f0c13c8592fe50e3e.r46.cf1.rackcdn.com/error.html)

**Comment by spicyj** [comment]
@agnosticdev Thanks – it looks like Babel [gives a better error here](http://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=React.createClass(%7B%0A%20%20render%3A%20function()%20%7B%0A%20%20%20%20return%20%3Cdiv%3E%0A%20%20%20%20%3Cdiv%3E%3B%0A%20%20%7D%0A%7D)%3B) which is reassuring. We're probably not going to end up improving react-tools's parser here but we'll start to recommend Babel more and hopefully that will help for transform-related errors.

**Comment by agnosticdev** [comment]
@spicyj thank you for the recommendation.

**Comment by jsfb** [comment]
@spicyj Since babel errors are better and will be the recommendation moving forward, are we free to close this out?

**Comment by spicyj** [comment]
@jsfb No, we haven't added the error for non-string/function types that I said I wanted to add.

**Comment by danschumann** [comment]
My wish would be that an error would have a stack that could tell me the react element parents, with minimal references to the react methods, as opposed to only giving me a stack of 30 react methods.

**Comment by gaearon** [comment]
I am closing as this appears resolved.

>No, we haven't added the error for non-string/function types that I said I wanted to add.

I think we do have a good warning now. With 0.14.6:

```js
var Lol = undefined
ReactDOM.render(
  <Lol />,
  document.getElementById('container')
);
```

gives me

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

The error stack is also meaningful because the warning fires early in `createElement`.

The lowercase `<lol />` would render to an unknown custom element but we are tracking adding a warning to it in #3596.

I’m closing but let me know if I missed something.
