### ISSUE TITLE
Expose React.addons.* as react/addons/* on npm and deprecate react/addons

### ISSUE THREAD

**Issue by spicyj** [facebook/react#3780]
The current system of packaging react/addons isn't great because you need to pull in all the addons even if you just want to use one of them. Instead, let's make it so you can do `require('react/addons/TransitionGroup')` and similar.

This should be as simple as adding a few files to build/npm-react that require the (private) internal modules.

```js
// npm-react/addons/TransitionGroup.js
module.exports = require('../lib/ReactTransitionGroup.js');
```

**Comment by zpao** [comment]
cc @gaearon @iamdustan. This came out of the Twitter discussion as a possible way to start migrating to requiring of a single addon in a condoned way (without reaching directly into `lib./`) that shouldn't screw up other packaging.

**Comment by pspeter3** [comment]
This would be greatly appreciated.

**Comment by gaearon** [comment]
Sounds like a good plan to me!

**Comment by iamdustan** [comment]
@zpao @spicyj should I update the docs with this change as well?

**Comment by spicyj** [comment]
Please do!
