### ISSUE TITLE
Support for pre/post-event notification

### ISSUE THREAD

**Issue by rogierschouten** [facebook/react#3782]
I find myself for needing a before and after notification of any synthetic event e.g. onClick/onChange to any react component.

This helps to implement a Flux-like framework with more strict constraints on how the store change events propagate through the system. Ideally I need access to all the entry points into the application, being all a-sync server events, timer events, and all browser events.  For the latter, I would like a hook into the React event system.

Is such a thing possible and/or feasible to implement?

**Comment by jsfb** [comment]
Can you provide a more detailed example / use case?

Normally, in a Flux-like framework, all the events get sent to the dipatcher, which results in updated datastores and a rerender.  I don't see why you would need/want a before/after notification, nor what that would actually mean (How is this different from doing something at the beginning/end of your event handler).

**Comment by rogierschouten** [comment]
I understand the data flow from widgets to dispatcher to stores to widgets. Are events also sent to the dispatcher for stores listening to other stores however? In most of the pictures I see them sending events directly to each other, as long as it stays unidirectional / a-cyclic.

The unaddressed problem I see is that synchronous events are used, which can cause re-entrancy: store A listens to store B. A sends a change event, and within sending the event, its getters are called by store B. Store A needs to be robust to that. Sounds really simple, but in practice you can easily get some hard-to-debug problems with synchronous events. 

With React, you would not want to make the events a-synchronous - this could cause multiple re-renders for one logical change. Therefore I would like to use synchronous events through an event queue, which is flushed until empty at the end of each external event (mouse click or server response etc). That way, when you send an action into the system, everybody can send events whenever they like, but they are processed once everybody is in a defined state.  To do that, however, I would have to flush the queue on EVERY click handler etc. That is very error-prone. For that reason I would like a limited number of hooks to address all external events at once.  

Maybe a pre-render hook isn't even the answer, but is there anything in React's synthethic event system that would allow detecting the end of a processed browser event?

**Comment by gaearon** [comment]
I think this is a somewhat exotic use case and it’s unlikely we’ll provide such hooks.

You can probably achieve this by overriding the browser’s base `addEventListener` and `removeEventListener` implementations though.

**Comment by rogierschouten** [comment]
That's of no use, since I need them on React's synthetic events, before react starts rendering.  But never mind, I get your point.

**Comment by gaearon** [comment]
React synthetic event handlers are called inside of browser event handlers (that React sets up). So if you want to do something at the end of every React event, you might as well do it at the end of every browser event.

That said the use case you described probably has other solutions.

>A sends a change event, and within sending the event, its getters are called by store B. Store A needs to be robust to that. 

This is indeed annoying. Facebook's Flux implementation lets store express dependencies on each other with `waitFor()` API. This lets you ensure A always processes an event before B. It also forbids cycles, i.e. it will throw if you try to register a reverse dependency. In practice this should be enough protection.

If you look at derivative architectures that lean into a more functional territory (e.g. Redux), they don't have many stores at all, and instead have pure reducer functions. As a result the store updates are always atomic. So this would completely eliminate the problem.

Relying on event system for this (whether React or browser) seems like the wrong direction to me. Actions could also be dispatched inside timeouts or AJAX callbacks which are always outside of events.

I hope this helps!
