### ISSUE TITLE
Warn when using React.unmountComponentAtNode on a different React instance's tree

### ISSUE THREAD

**Issue by spicyj** [facebook/react#3787]
We should be able to look at see if the child has a data-react-id attribute but isn't rendered by this copy of React and consequently warn.

See https://groups.google.com/forum/#!topic/reactjs/mdwfKKJ0L2Q.

**Comment by jsfb** [comment]
Probably same with React.render, right?  We would want to warn if you are rendering into another React's instance tree?

**Comment by spicyj** [comment]
Sure. @crm416 had some related warnings in #2065.

**Comment by gaearon** [comment]
Fixed in #7456.
