### ISSUE TITLE
TestUtils.renderIntoDocument doesn't function as expected in all browsers

### ISSUE THREAD

**Issue by ezequiel** [facebook/react#3789]
Hi,

Here is my program ([jsfiddle](http://jsfiddle.net/w9dphLfc/2/)):

``` jsx
var Input = React.createClass({
    render: function() {
        return (
            <input 
                {...this.props}
            />
        );
    }
});

var TestUtils = React.addons.TestUtils;
var inputInstance = 
        TestUtils.renderIntoDocument(
            <Input
                value='abc'
            />
        );

var inputDOMNode = React.findDOMNode(inputInstance);

inputDOMNode.focus();

// Place cursor at the end.
inputDOMNode.setSelectionRange(3, 3);

// Should log 3 twice.
console.log(inputDOMNode.selectionStart);
console.log(inputDOMNode.selectionEnd);
```

**Problem**: `0` is logged twice in Chrome and Firefox.
**What I expected**: `3` is logged twice. We see this in Safari.

The interesting part is if we use `React.render(..., document.body)` instead of `TestUtils.renderIntoDocument` the program works as expected. 

I am using:
- Chrome 42.0.2311.135
- Firefox 37.0.2
- Safari  8.0.5 (10600.5.17)

**Comment by ezequiel** [comment]
I get it now.

`setSelectionRange` doesn't seem to work if the element **isn't on the page**. That's why rendering into `document.body` works as expected. I suppose it's a fluke the program ran correctly in Safari... Though that requirement isn't documented anywhere (?).

Appending to the document was commented out in this commit: https://github.com/facebook/react/commit/ce95c3d042309d8aced894cc6be43d7e4cf96455. I guess this method is now a misnomer, as it doesn't actually render *into* the document.

**Comment by jsfb** [comment]
@spicyj @zpao does this change our thoughts on renderIntoDocument?  Maybe we should attach to the dom to avoid cases like this?  What cleanup were we trying to avoid when we removed that function?

**Comment by spicyj** [comment]
> This will help avoid some cleanup effort between tests in the open-source version of React (see calls to removeNextSiblings in react/src/test/index.html).

I don't feel strongly.

**Comment by ezequiel** [comment]
I suppose we have two options:

 * Deprecate `TestUtils.renderIntoDocument`.
 * Create a new method, `TestUtils.render` (does anyone have a better name?) which is simply a renamed version of `renderIntoDocument`.

or,

* Change `TestUtils.renderIntoDocument` to *actually* render into the document.

---

Option #1 seems like the best option at this point, as `renderIntoDocument`'s current behavior hasn't received any complaints (besides mine) thus far.

**Comment by rupurt** [comment]
@ezequiel how do you feel about the following

* Rename the current functionality of `ReactTestUtils.renderIntoDocument` to `ReactTestUtils.render`
* Create 2 new methods
   * ReactTestUtils.renderInto(component, element)

**Comment by rupurt** [comment]
We could even make `renderInto` take a method that automatically does the cleanup for us e.g.

```js
ReactTestUtils.renderInto(
   <MyComponent>Hello!</MyComponent>,
   document.querySelector("#fixtures"),
   function(componentElm) {
      expect(componentElm.innerHTML).to.contain.text("Hello");
   }
});
```

**Comment by marcysutton** [comment]
This is definitely a problem for accessibility testing. We need components to be attached to test them fully, as the current method makes the tree appear to be hidden. It would be really helpful to have blessed methods for doing this, as appending to the body and then removing messes up my other tests with "The DOM was unexpectedly mutated" errors.

**Comment by spicyj** [comment]
@marcysutton Thanks, that's useful feedback. If you do need to append to the document then the most straightforward and flexible solution is to call ReactDOM.render manually:

```
var div = document.createElement('div');
document.body.appendChild(div);
ReactDOM.render(<Foo />, div);
```

That's also exactly what the implementation of any test helper we might provide would do.

**Comment by marcysutton** [comment]
Thanks. I see one issue with appending to an extra element: it means we can't look at document-level rules like lang or title without walking up the DOM tree. By passing in document.body, we can look at those things more easily (and quickly). But again, DOM mutation probz.

**Comment by 1Copenut** [comment]
@sophiebits Thank you for this suggestion to use `ReactDOM.render()`. I had an issue similar to the one @marcysutton asked about. I was using a lot of vanilla JS traversal methods that returned null values when I used `ReactTestUtils.renderIntoDocument()`. Test lights are all green now.
