### ISSUE TITLE
`ReactLayersMixin`.

### ISSUE THREAD

**Issue by jordwalke** [facebook/react#379]
I really like our `ReactLayersMixin` plugin and we should open source it. It allows us to implement not just the `render` function, but also the `renderLayers` function. The `render` is the same as its always been (describe your structure at _any_ point in time. The `renderLayers` API allows you to describe your modal _layers_ at _any_ point in time. So that means you can open and close layers as a function of `props`/`state` just like your `render()` function can "react" to `props`/`state`.

Assigning to @yungsters who mastered the React/Layers stuff on FB's stack, but @petehunt also has great experience using and building out layers integration with React. So whoever has time/need.

**Comment by mziemer21** [comment]
@yungsters any update on the blog post? :)
I'm curious if renderLayer & renderSubtreeIntoContainer are still used to handle layering?

**Comment by brigand** [comment]
@mzabriskie the modern solution is something like react-portal.

**Comment by gaearon** [comment]
Yea. We actually codemodded the mixin away just a month ago, and removed the distinction between `render` and `renderLayers`—layered components are just regular components now. It *is* a little awkward without fragments but no big deal.

**Comment by AlexeyFrolov** [comment]
I've spent some sensible time to research on this. As a result I end up with the library which permanently solved this problem for me. Check out, please, would be good to know the impressions and everything https://github.com/AlexeyFrolov/react-layer-stack
