### ISSUE TITLE
Async React.renderToString for server-side rendering

### ISSUE THREAD

**Issue by xpepermint** [facebook/react#3793]
It would really help if we could use the `async` version of the `React.renderToString` when rendering on the server-side.

```js
app.get('*', function (req, res) {

  Router.run(routes, req.path, (Handler, router) => {
    // var content = React.renderToString(<Handler/>);
    // res.render('index', { content: content });
    React.renderToString(<Handler/>, function(content) {
      res.render('index', { content: content });
    });
});
```

**Comment by spicyj** [comment]
This is something we want to do, but it requires more thought around how components are rendered because the currently solution always renders something synchronously. In your example, what does it wait for before returning the result? Anyway, we're tracking this in #1739.

**Comment by xpepermint** [comment]
Great. As you can see I'm rendering the component server-side with nodejs/express and using a sync method does not feel right (blocking). Thanks.

**Comment by spicyj** [comment]
React.renderToString doesn't do any I/O so you wouldn't gain anything from it being async in its current form.

**Comment by zpao** [comment]
Where you might benefit is not so much async but streaming markup generation. Follow along in #3009 for more there.

**Comment by xpepermint** [comment]
Thanks! Following #3009 then.

**Comment by gaearon** [comment]
There’s new work in this area in https://github.com/facebook/react/pull/20970.
