### ISSUE TITLE
Custom IFRAME attributes in a nwjs (formerly node-webkit) project

### ISSUE THREAD

**Issue by bdudelsack** [facebook/react#3809]
nwjs (http://nwjs.io/) introduces some custom attributes for the IFRAME element. Those attributes are: 
- `nwdisable` (since 0.5.0) is used to disable Node support in the iframe and make it a `Normal frame`
- `nwfaketop` (since 0.5.1) is used to trap the navigation and the access (such as window.top, window.parent) in this iframe.
- `nwUserAgent` (since 0.9.0-rc1) is used to specify the `User-Agent` header of HTTP requests.

(Source: https://github.com/nwjs/nw.js/wiki/Mini-browser-in-iframe)

Those attributes are being stripped out when building the GUI with React.

**Comment by levibuzolic** [comment]
Should be able to work around this with `dangerouslySetInnerHTML`.

React would need to allow support for all attributes for these attributes to be used without `dangerouslySetInnerHTML`.

**Comment by mikecao** [comment]
You could add the attribute directly to the DOM element. I'm currently doing that with file inputs for NWJS. You just do it after mounting like this:

```
componentDidMount: function() {
  React.findDOMNode(this.refs.iframe).setAttribute('nwdisable', '');
}
```

**Comment by twolfson** [comment]
Another workaround is to override `HTMLDOMPropertyConfig` before `react` is initially loaded. This allows us to set custom "accepted" HTML properties:

https://github.com/facebook/react/blob/v0.13.3/src/browser/ui/dom/HTMLDOMPropertyConfig.js#L47

```js
// Load in HTMLDOMPropertyConfig before loading React ever and set up custom properties
var HTMLDOMPropertyConfig = require('react/lib/HTMLDOMPropertyConfig');
HTMLDOMPropertyConfig.Properties.nwdisable = null;
HTMLDOMPropertyConfig.Properties.nwfaketop = null;
HTMLDOMPropertyConfig.Properties.nwUserAgent = null;

// Load in React which binds configs at load time
var React = require('react');
```

**Comment by spicyj** [comment]
If you're going for unsupported workarounds, you can also call `DOMProperty.injection.injectDOMPropertyConfig` anytime before or after React is required.

**Comment by twolfson** [comment]
I prefer the term "version dependant workaround" for something like this ;P

And thanks for the tip, that cleans up some sanity in load order =)

**Comment by aweary** [comment]
This is resolved in React 16, which renders unknown attributes 🍾 

Check out [DOM Attributes in React 16](https://facebook.github.io/react/blog/2017/09/08/dom-attributes-in-react-16.html) for more information!
