### ISSUE TITLE
Controlled inputs with type="number" do not work in some browsers

### ISSUE THREAD

**Issue by piratus** [facebook/react#3810]
Controlled inputs in current Safari, Firefox and Chrome let you input anything as if they were not controlled. They do work as supposed in IE9 and Chrome Dev build. I don't have IE 10 or 11 to test those.

Here is a sample JSBin that reproduces the problem: http://jsbin.com/yahitu/1/edit?js,output

**Comment by b2whats** [comment]
Все нормально работает, как и должно

**Comment by muromec** [comment]
More detailed info: when <input type="number" /> component receives string as value property it silently ignores it and behaves like uncontrolled one.

Above example works as intended when you change default value to NaN.

**Comment by cody** [comment]
More discussion about this is in #1549.

**Comment by zpao** [comment]
Thanks for finding that @cody. I'm going to close this out and we can continue discussion over there.
