### ISSUE TITLE
`tabSize` in `style` prop/attribute should be exempt from automatic `px` suffix

### ISSUE THREAD

**Issue by MadLittleMods** [facebook/react#3823]
The [`tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) CSS property should not be getting a `px` suffix automatically because a unit-less value can represent the number of spaces that make up the width in a tab.

The JS name for this property is `tabSize`.

See [*Shorthand for Specifying Pixel Values in style props*](https://facebook.github.io/react/tips/style-props-value-px.html) in the React docs.

**Comment by MadLittleMods** [comment]
A solution for now is to use the [`ch` unit](https://developer.mozilla.org/en-US/docs/Web/CSS/length)

> **ch**
> This unit represents the width, or more precisely the advance measure, of the glyph '0' (zero, the Unicode character U+0030) in the element's font.
>
> *https://developer.mozilla.org/en-US/docs/Web/CSS/length*

**Comment by zpao** [comment]
Sounds like a good idea. Are you interested in creating a PR to add it?

**Comment by MadLittleMods** [comment]
@zpao Yes, the only I don't know is whether there needs to be something special to also include vendor prefixed versions of `tabSize`

 - [ ] Add to [`src/browser/ui/dom/CSSProperty.js` `isUnitlessNumber`](https://github.com/facebook/react/blob/1aa4e3c2344a78841909f6cfb9a26923149d8f60/src/browser/ui/dom/__tests__/CSSPropertyOperations-test.js#L71)
 - [ ] Add to [docs](https://github.com/facebook/react/blob/41a6186d7acd9a1a7866a0252eefa8d903cfad8f/docs/tips/06-style-props-value-px.md) object
 - [x] [Test coverage](https://github.com/facebook/react/blob/1aa4e3c2344a78841909f6cfb9a26923149d8f60/src/browser/ui/dom/__tests__/CSSPropertyOperations-test.js#L71) already in place

**Comment by zpao** [comment]
We autogenerate the vender-prefixed styles there (which you might have seen below where you changed code) so that's all you need to do! Thanks again.
