### ISSUE TITLE
Select tag on server side rendering

### ISSUE THREAD

**Issue by jondeandres** [facebook/react#3824]
I'm having some issues rendering from server side `select` tags.

It's possible reproduce the problem with this:

```jsx
  return <select value="3">
              <option value="1">Foo 1</option>
              <option value="2">Foo 3</option>
              <option value="3">Foo 3</option>
         </select>
```

The browser interprets the generated DOM by the react server, but cause it's not a `selected` attribute in any `option` tag, it displays the first option, `"1"`, as selected. For the time React loads, let's say ~0.5 second, then the correct option is displayed as selected.

Do you think there is a solution for this behaviour?

**Comment by spicyj** [comment]
This is fixed in master and will be in the next release.

**Comment by jondeandres** [comment]
Thanks @spicyj
