### ISSUE TITLE
TestUtils.renderIntoDocument doesn't render document with function props

### ISSUE THREAD

**Issue by talyssonoc** [facebook/react#3836]
I'm trying to test a component with Jest, and I'm rendering it using `TestUtils.renderIntoDocument`. But if I try to do it passing a function as a prop, the component do not receive this prop.

Why ? Does `renderIntoDocument` just render serializable variables ?

My code:
```js
var f = function() { return 'test'; };
var c = TestUtils.renderIntoDocument(
   <Component value='value' callback={ f }/>
);
console.log(c.props); // logs { value: 'value' }
```

**Comment by drewblaisdell** [comment]
I suspect the problem is that you're attempting to access props directly on the rendered component. Passing a function as a prop works properly with `TestUtils.renderIntoDocument` — the following test passes:

```js
it('should render components with functions as props', function() {
  var CallbackComponent = React.createClass({
    componentDidMount: function() {
      this.props.callback();
    },
    render: function() { return <div />; }
  });

  var callback = mocks.getMockFunction();
  var renderedComponent = ReactTestUtils.renderIntoDocument(
    <CallbackComponent callback={callback}/>
  );

  expect(callback).toBeCalled();
});
```

**Comment by talyssonoc** [comment]
Actually what I said was just an example. I tried to do something like what you did at the test and it didn't worked either. Even when I set a default prop it wasn't replaced by the new one I passed.

**Comment by spicyj** [comment]
As you can see from the implementation, renderIntoDocument simply calls React.render:

https://github.com/facebook/react/blob/v0.13.3/src/test/ReactTestUtils.js#L45-L53

If you're having trouble passing functions, it's an artifact of your test environment and not something specific to React.

**Comment by kav** [comment]
I was seeing a similar issue when using Jest and an async it (with done())
I walked through the debug and it appeared to be having issues trying to create my component in `ReactCompositeComponent`. Somehow `_constructComponentWithoutOwner` decided that `Component` should be a `TopLevelWrapper` so it appeared to be trashing props.

Switched to a direct mock as in the above test and everything is now working fine so :shrugmoji

Happy to look into it more if anyone is blocked on this. Perhaps there is an assumption of a `TopLevelWrapper` that isn't there?
