### ISSUE TITLE
prevState with wrong values when using forceUpdate

### ISSUE THREAD

**Issue by AleCaste** [facebook/react#3838]
I have a simple component with the following state:
```
{number:1}
```
... with a simple 'componentDidUpdate' function like this:
```
componentDidUpdate: function(prevProps, prevState){
  console.log(prevState.number, this.state.number);
}
```
Then if I change the state by using the method 'setState'...
```
this.setState({number:2});
```
... 'componentDidUpdate' is fired and I get the following values:
```
prevState.number --> 1
this.state.number --> 2
```
Which are good as expected, of course.
But if I do something like this:
```
this.state.number = 3;
this.forceUpdate();
```
... 'componentDidUpdate' is fired alright, but I get the following unexpected values:
```
prevState.number --> 3
this.state.number --> 3
```
Is there any workaround so that we still get proper value in 'prevState' ?

**Comment by zpao** [comment]
When you modify `this.state` directly and use `forceUpdate()`, no new object is created for next state. It is, by reference, the same object that was in the previous state.

The workaround is to use `setState()` (but that will also have the same problem if you modify `this.state` directly before calling it).

**Comment by spicyj** [comment]
> workaround

(To be clear, using setState is the recommended pattern whenever you want to update state. Mutating the state object directly works in some cases as you saw but does not work consistently with all of the lifecycle methods so is not recommended.)

**Comment by AleCaste** [comment]
Yes. We really wanted to use setState no matter what, but in our scenario we have a complex state structure with many levels of depth.
You cannot use setState in an agile manner to update just one property that might be very deep in the state tree.
And using something like React.addons.update becomes overkilled (you need to build a whole state structure down to the level of depth you want to update).
