### ISSUE TITLE
What is the real reason for "Invariant Violation: Markup wrapping node not initialized" error?

### ISSUE THREAD

**Issue by koustuvsinha** [facebook/react#3840]
I have been searching everywhere but cannot find the proper explanation for this kind of error. In the source code it is written "This lazily detects which wraps are necessary for the current browser" - please elaborate on this.
I am getting this error on testing with jsdom & mocha. I have a button `nextPageButton` which I select using `TestUtils.scryRenderedDOMComponentsWithClass`, then I want to simulate the `click` event on it. So I use `TestUtils.Simulate.click(React.findDOMNode(nextPageButton))`, but at this exact line I am getting the issue.

**Comment by zpao** [comment]
This means that when React was loaded, it thought it was not in a DOM environment, so it didn't create the wrapper node it needs to test when rendering certain nodes.

Here's the check we use:

```
var canUseDOM = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
);
```

As you can tell we're detecting globals so just ensure you have those defined.

**Comment by koustuvsinha** [comment]
well before my test cases I explicitly specify `require('react/lib/ExecutionEnvironment').canUseDOM = true` , shouldn't it be enough?

**Comment by zpao** [comment]
No, getMarkupWrap creates the wrapper node when it is required (https://github.com/facebook/react/blob/master/src/vendor/core/getMarkupWrap.js#L16-L20). That could perhaps change to create once on demand and cache but as of right now it doesn't.

**Comment by zpao** [comment]
In general we've made the assumption that the execution environment doesn't change so you may run into other issues.

**Comment by koustuvsinha** [comment]
So how to circumvent this issue on jsdom?

**Comment by koustuvsinha** [comment]
The surprising issue is, this case does not occur when I test it in Windows environment!

**Comment by BerkeleyTrue** [comment]
If you are using jsdom make sure you are creating the correct globals in the environment before any requires of React.
see: http://www.hammerlab.org/2015/02/14/testing-react-web-apps-with-mocha/

**Comment by koustuvsinha** [comment]
yes I have all the globals created correctly I think. Like this : 

```
module.exports = function(markup) {
	markup = markup || '<html><body></body></html>'
  if (typeof document !== 'undefined') return;
  var jsdom = require('jsdom').jsdom;
  global.document = jsdom(markup || '');
  global.window = document.defaultView;
  global.fetch = function(){}
  global.navigator = {
    userAgent: 'node.js'
  }
};
```

**Comment by BerkeleyTrue** [comment]
But are they there before you require react? Its a tricky beast so you have to be really careful that these are set up before everything else.

P.S. I think you also need to add global.window.document as well.

**Comment by koustuvsinha** [comment]
what should be set in global.window.document? I will test out your inputs now and update here. Thanks for helping :)

**Comment by koustuvsinha** [comment]
BerkeleyTrue you are absolutely right!!!! somehow I missed to include the globals before I require React!!! Amazing man, thanks a TON!!!

**Comment by koustuvsinha** [comment]
So important lesson learnt : Always declare globals *before* including React!
Closing this issue now. Thanks everyone!

**Comment by BerkeleyTrue** [comment]
You are welcome.
