### ISSUE TITLE
ESLinting React/Flux ES6 code without transpiling

### ISSUE THREAD

**Issue by stevus** [facebook/react#3848]
Is this possible? I realize I could use Babel to lint my transpiled code, but that won't let me find the error in ES6 code.

Is there a resource I can go to in order to properly use ESLint with ES6?

I found this article, but it is from November 2014 and there still seems to be literature saying it is not production-ready.

[Link](http://eslint.org/blog/2014/11/es6-jsx-support/)

**Comment by spicyj** [comment]
babel-eslint lints the original source, not the transformed code. See this post for info about how to set it up:

https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48
