### ISSUE TITLE
#1398 missing / not shipped along with Ship 0.13.2 #3629 ?

### ISSUE THREAD

**Issue by goofballLogic** [facebook/react#3849]
I've been trying to use the improved server-side rendering support for selected options of a SELECT element, but upon inspecting the react code (I've checked npm and download versions of both 0.13.2 and 0.13.3), I can't find the fix for #1398 which was included in 0.13.2 according to #3629 . (and is tagged as such)

Specifically, I've been checking for the following snippet of code within ReactDOMSelect.js from https://github.com/spicyj/react/commit/ea089fdfe62b3193740ee4a30acb6827a905a02c 

Missing:

    +  getInitialState: function() {
    +    // Pass down initial value so initial generated markup has correct
    +    // `selected` attributes
    +    var value = LinkedValueUtils.getValue(this.props);
    +    if (value != null) {
    +      return {initialValue: value};
    +    } else {
    +      return {initialValue: this.props.defaultValue};
    +    }
    +  },

My code which isn't rendering server-side `selected` attr on options is:

    <select name={option.value} defaultValue={option.order}>
    {option.setting.map( function( setting ) {

       return <option value={setting.value}>{setting.text}</option>;

    } )}
    </select>

**Comment by spicyj** [comment]
No, #1398 didn't make the release; we decided it was a little too risky. (The "Did it." comment there refers to the release itself, not that PR.)
