### ISSUE TITLE
request: enable triggering warnings on every render

### ISSUE THREAD

**Issue by joeybaker** [facebook/react#3854]
On the client, it's nice that development warnings are only triggered on the initial render. But, when rendering from the server with `renderToString` it's annoying to only have the warnings triggered the first render and then ignored on subsequent page loads. 

What if render methods accepted an additional options argument?

```js
React.render(<span>hi</span>, window.app, {alwaysWarn: false})

React.renderToString(React.createElement(El, data), {alwaysWarn: true})
```

Crazy ideas: This might be useful for other options too? Perhaps: `appendToBody` (auto-appends the second arg), or `ignoreDOMCalls` (automatically catches/ignores errors to for `window` and `document` APIs)?

**Comment by joeybaker** [comment]
Update: the basic problem seems to be that the `loggedTypeFailures` object is private. https://github.com/facebook/react/blob/d1a21931274522acf4fb6374ed5f30fca41cb69d/src/isomorphic/classic/element/ReactElementValidator.js#L246 If this could be exposed publicly, users could opt-in to resetting it.

**Comment by joeybaker** [comment]
@zpao would you be open to a PR that allows the disabling of `loggedTypeFailures`?

**Comment by jimfb** [comment]
I'm going to close this out in favor of https://github.com/facebook/react/issues/4302, since that has been where most of the discussion has been taking place and I like the solution we arrived at in that thread.

**Comment by joeybaker** [comment]
Thanks @jimfb!
