### ISSUE TITLE
dangerouslySetInnerHTML replaces $$ by $ (server side rendering only)

### ISSUE THREAD

**Issue by lud2k** [facebook/react#3855]
Hey there,

I'm having an issue with dangerouslySetInnerHTML and dollar signs.
It seems like when calling React.renderToString (server side rendering), if the __html value given to dangerouslySetInnerHTML contains "$$123" then it gets rendered as "$123". (lost a dollar sign)

Could find an easy way to fix that so i've started doing this terrible thing: html.replace(/\$\$/g, '$$$$$').

**Comment by zpao** [comment]
Hmm, I can't repro this in a simple case (http://jsfiddle.net/jqznqwg4/), can you give a bit more detail, perhaps a test case on jsfiddle or elsewhere.

**Comment by lud2k** [comment]
Oops I'm sorry about that.
It seems like my code was doing something wrong.
React works just fine :)
