### ISSUE TITLE
Inline styles pseudoclasses discussion

### ISSUE THREAD

**Issue by gyzerok** [facebook/react#3859]
Hi, there!
I really like the intent behind inline classes in React and want to use them in my project. The really bad part is lack of ':hover', ':focus' and etc. I know that there is Radium, but I dont like it.
So I decided to try to investigate React sources and come with my implementation in PR.
Can you tell me where in the source code I can find inline styles rendering?

Thank you!

**Comment by gyzerok** [comment]
I found following in the [w3 docs](http://www.w3.org/TR/2002/WD-css-style-attr-20020515)
```html
<a href="http://www.w3.org/"
          style="{color: #900}
          :link {background: #ff0}
          :visited {background: #fff}
          :hover {outline: thin red solid}
          :active {background: #00f}">...</a>
```

What do you think about adding this attributes into JSX?

**Comment by syranide** [comment]
That's only mentioned in ideas for the future, best practices and various community tools. React (at current) largely only exposes the underlying DOM as it is.

**Comment by ianobermiller** [comment]
If you want to use this now, you can check out Radium: https://github.com/FormidableLabs/radium. Radium cannot support `:visited` due to browser security measures, and `:link` is not needed.

```as
var Link = React.createClass(Radium.wrap({
  render: function() {
    return (
      <a style={{
        color: '#900',
        ':hover': {outline: 'thin red solid'},
        ':active': {background: '#00f'}
      }} />
    );
  }
}));
```

**Comment by spicyj** [comment]
The W3 docs you link are outdated; the latest version makes no mention of the syntax: http://www.w3.org/TR/css-style-attr/.

Right now we're not planning to add more support for complicated "inline" styles like this into React core.
