### ISSUE TITLE
React.PropTypes.element message is unclear

### ISSUE THREAD

**Issue by rigdern** [facebook/react#3865]
When `React.PropTypes.element` fails, this is the error message:

```
Invalid prop `children` supplied to `MyComponent`, expected a
ReactElement. Check the render method of `App`.
```

I think the error message isn't clear enough for the case that it fails due to you passing multiple elements to the children prop.

Imagine a new user of React is using a component that only accepts a single child and they pass multiple children instead. Seeing this error might lead them to believe they are somehow passing a number, string, null, etc. as children. I don't think their first instinct would be that their mistake is that they're passing multiple children.

To make this kind of mistake easier to diagnose, can the error message emphasize the fact that you can only pass a single element?

**Comment by sebmarkbage** [comment]
cc @spicyj - designer of error messages.

**Comment by spicyj** [comment]
Am I? We can make this say "expected a single ReactElement".

**Comment by rigdern** [comment]
That sounds good to me :+1:
