### ISSUE TITLE
Feature request: ability pass context to React.render()

### ISSUE THREAD

**Issue by rogierschouten** [facebook/react#3867]
Especially for testing parts of my GUI, I would like to be able to say:

```javascript

var myContext = foo;
React.render(<MyComponent/>, document.getElementById("all-content"), myContext)
```

instead of having to make a wrapper component every time and define childContext on that.

**Comment by zpao** [comment]
cc @jimfb - I remember us talking about this but wasn't sure what the result of that was.

**Comment by sebmarkbage** [comment]
One issue was with regard to subtrees. It is not enough for subtree rendering so we introduced the subtree rendering for implicit context pass through.

Another issue is just that this method already has a third argument. Wrappers is basically our poor man's named arguments. Allows us to put arbitrary things there. :)

A third issue is that I don't even think object maps will be how we define context in the future so it would make less sense.

Finally, if this is about unit testing then our recommended strategy for unit testing is to use the shallow rendering, so we should add context support to shallow rendering instead.

**Comment by jimfb** [comment]
One thing you can do which might be helpful for your test utilities: you can define a wrapper function that takes in a context object, and which generates a new wrapper component that defines childContext and renders the provided component using renderSubtreeIntoContainer.  Then you get almost exactly what you're looking for, and the solution is entirely in userspace.

**Comment by zpao** [comment]
Let's close this out and we can revisit if we need later. We're not going to do anything in the near term.

**Comment by rogierschouten** [comment]
@jimfb  thanks for the suggestion, I'll try it
