### ISSUE TITLE
conditional dynamic children causing error

### ISSUE THREAD

**Issue by jakemmarsh** [facebook/react#3873]
I have multiple cases in my app where I conditionally create an array of dynamic children, like so:

    if ( !_.isEmpty(this.props.prediction.tags) ) {
          return _.map(this.props.prediction.tags, function(tag, index) {
            return (
              <ListLink to="Search" query={{ q: tag }} key={index}>{tag}</ListLink>
            );
          });
        }

which worked fine in React 0.12.x. However, I just upgraded to 0.13.3 and it seems to be causing the error:

![enter image description here][1]

If I remove this functionality, this eliminates the error. However, I can't figure out how to fix the error and still have this conditional rendering. I've tried messing around with the `key`, as well as defaulting to returning an empty array if the condition fails, or an array with a single `<div />` element.

Any ideas?

  [1]: http://i.stack.imgur.com/ih7X1.png

**Comment by spicyj** [comment]
The code you posted sounds fine – if you can reduce this to a simple test case I'd be happy to reopen and take a look.
