### ISSUE TITLE
"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op." has no context

### ISSUE THREAD

**Issue by dantman** [facebook/react#3878]
The "Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op." warning contains no context of what component setState was run on.

setState can happen at any time and changes to another component can be the cause of an unmount that results in the setState happening when unmounted so it's hard to even link the most recent code chagne you made to what setState call is responsible.

Simply including the `displayName` in the message like other warnings have should help devs at least a little in tracking down the source of this warning.

**Comment by zpao** [comment]
This sounds like a great idea.

**Comment by evankline** [comment]
+1

**Comment by machiaveli88** [comment]
+1

**Comment by datboitom** [comment]
+1

**Comment by jgod** [comment]
+1

**Comment by zpao** [comment]
Please stop +1ing, it adds zero value. We have already identified that this is a good idea.

**Comment by dantman** [comment]
GitHub really needs to automatically consolidate +1 comments into a single block and do a digest email for +1s.

**Comment by edvinerikson** [comment]
Got an PR for this: https://github.com/facebook/react/pull/3913

New message will be like this:
> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. Please check the code for the ExampleApplication component. This is a no-op.

**Comment by edvinerikson** [comment]
PR is merged so we should probably close this now.

**Comment by zpao** [comment]
Thanks for taking this on!

**Comment by seanchen1991** [comment]
Is the new context-sensitive warning working for everyone? I'm getting the old warning without any context on 0.13.3.

**Comment by zpao** [comment]
#3913 was not shipped to 0.13.x

**Comment by gilsho** [comment]
+1

**Comment by enadav** [comment]
+1

**Comment by zpao** [comment]
The fix was landed, any additional +1 is pure noise. Please stop.

**Comment by AndrewBestbier** [comment]
+1 ;)

**Comment by axelg12** [comment]
+1
