### ISSUE TITLE
Custom component methods lose static properties

### ISSUE THREAD

**Issue by greenish** [facebook/react#3886]
When defining/mixing in a custom method in a react component it loses all static properties:

```
var customFunction = function(){
  // Do magic
}
customFunction.myStaticProperty = "some important value";

React.createClass({
  customFunction : customFunction,
  render: function(){
    this.customFunction.myStaticProperty // Undefined
  }
});

```
Static properties are replaced by these four react properties:
```
 this.customFunction.__reactBoundContext
 this.customFunction.__reactBoundMethod
 this.customFunction.__reactBoundArguments
 this.customFunction.bind
```

Is there a reason to remove the users static properties from methods? 
Would it be possible to __add__ the react properties to the method – keeping the custom properties in place?

**Comment by andersekdahl** [comment]
The properties aren't removed. `this.customFunction` isn't equal to `customFunction` in your example, because React autobinds component methods to the component so you don't have to write `<div onClick={this.customFunction.bind(this)} />`. My guess is that this isn't an issue if you use ES6 classes, since React won't autobind methods on such classes.

**Comment by greenish** [comment]
I'm aware of the autobinding and that `customFunction` is getting wrapped. 
However from a UX/API perspective this is an inconsistency and therefore an issue. The properties should not get lost but should be copied over to the wrapper. 
`customFunction.bind()` preserves the function properties but can't be used react internally for backwards compatibility reasons.

My workaround for this problem is to redefine function properties on `getInitialState` this works but shouldn't be necessary.

As for ES6 classes, as soon as the mixin/extendability problem is solved I'm glad to switch.

**Comment by gaearon** [comment]
We won't be changing `createClass` semantics.
