### ISSUE TITLE
Deeper events not triggered in FF 38, IE 10, or IE 11

### ISSUE THREAD

**Issue by ryanzec** [facebook/react#3895]
I have this fiddle:

https://jsfiddle.net/69z2wepo/8502

My exception (which may not be correct) is that if I click on the first `test` text, the console should log `test1`.  If I click on the second `test` text that is within the button, the console should log `test1` and `test2`.

Chrome and Safari behave the way I expect however with FF 38.0.1, IE 10, and IE 11, when I click on the second `test` text within the button, the console only logs `test2`.  If my understanding of event handling is correct, when I click on the text within the button (which is the `Ic` component), that component should trigger it's `onClick` event and then bubble it up to the `Bu` component which should then trigger it's `onClick` event.

Why would FF and IE not trigger the `Ic` `onClick` event handler when it is within the `Bu` component but it triggers fine when it is not in another component?

**Comment by cody** [comment]
The behavior is the same without React: https://jsfiddle.net/zcLc3awc/

I don't know if this is something the devs want to normalize. To me it does not sound useful to have a clickable child inside of a button.

**Comment by ryanzec** [comment]
Ah, was not aware that was inherit with clickable items in button in general.  Since that is how regular javascript works, I don't think React should work differently, closing.
