### ISSUE TITLE
`TestUtils.renderIntoDocument` does not throw exception from `propTypes` validation error

### ISSUE THREAD

**Issue by jfairley** [facebook/react#3897]
I wrote a class like

```javascript
const React = require('react');
const RecordActions = require('../actions/RecordActions');

const Record = React.createClass({
    propTypes: {
        record: React.PropTypes.shape({
            id: React.PropTypes.number.isRequired,
            name: React.PropTypes.string,
            status: React.PropTypes.string
        }).isRequired
    },

    handleClick: function () {
        RecordActions.select(this.props.record.id);
    },

    render: function () {
        return (
            <div onClick={this.handleClick}>
                <div>ID: {this.props.record.id}</div>
                <div>Name: {this.props.record.name}</div>
                <div>Status: {this.props.record.status}</div>
            </div>
        );
    }
});

module.exports = Record;
```

In my test, `TestUtils.renderIntoDocument` would _not_ cause a failure:

```javascript
    // this test will incorrectly fail
    it('should require record', function (done) {
        try {
            TestUtils.renderIntoDocument(<RecordListItem/>);
            done(new Error('expected exception'));
        } catch (err) {
            expect(err);
            done();
        }
    });
```

whereas using `React.render` correctly throws an error and fails the test:

```javascript
    // this test passes
    it('should require record', function (done) {
        try {
            React.render(<RecordListItem/>);
            done(new Error('expected exception'));
        } catch (err) {
            expect(err);
            done();
        }
    });
```

**Comment by jfairley** [comment]
I am using react 0.13.3 pulled from npm

**Comment by zpao** [comment]
PropType validation does not throw, it uses console.error.

`React.render` will throw in the above because you didn't pass a DOM node.
`TestUtils.renderIntoDocument` creates a node to render into, which is why it won't throw.

**Comment by zpao** [comment]
Let me know if I misunderstood what's happening and we can reopen, otherwise, this doesn't sounds like a bug.

**Comment by jfairley** [comment]
I suppose that's a drawback of not pasting full source...

I assume the DOM node to which you refer is `<RecordListItem/>`. Is that correct?

In the first snippet, the file is named `RecordListItem.jsx`.

For the test in the second two snippets, I have

```javascript
const RecordListItem = require('./RecordListItem.jsx');
```

Note that I am also using [testdom](https://github.com/asbjornenge/testdom) to make a virtual DOM. I am using mocha, not jest.
```javascript
require('testdom')('<html><body></body></html>');
```

I have another test alongside it. Same deal. `React.render` throws (test pass) while `TestUtils.renderIntoDocument` does not (test fail).
```javascript
    it('should require record with id', function (done) {
        let record = {name: 'test', status: 'completed'};
        try {
            React.render(<RecordListItem record={record}/>);
            done(new Error('expected exception'));
        } catch (err) {
            expect(err);
            done();
        }
    });
```

**Comment by zpao** [comment]
No, I'm talking about an actual DOM node: `React.render(<Component/>, node)`. Without `node`, `React.render` will throw.

`TestUtils.renderIntoDocument` creates that node then calls `React.render`, which is why that signature is different. This is what it looks like:

```js
  renderIntoDocument: function(instance) {
    var div = document.createElement('div');
    return React.render(instance, div);
  },
```

If you did the same thing before calling `React.render` in your test, I don't think that would throw either.

In general, I strongly suggest expecting a specific error, not any error. By expecting any error, you are masking what's actually wrong. In your case, expecting an error at all is the wrong thing. The error you're catching is about calling render without a DOM node.

This is what you're test should look like:

```js
it ('should require record with id', function() {
  spyOn(console, 'warn') // Note: will be console.error in 0.14
  TestUtils.renderIntoDocument(<RecordListItem />);
  expect(console.warn.calls.length).toBe(1);
  expect(console.warn.argsForCall[0][0]).toBe('some specific warning about record being required');
  // or something similar, I forget the exact syntax for all this.
})
```

**Comment by jfairley** [comment]
OH! I did miss that. (Can you tell I'm new to React? :wink:) Thank for clearing it up for me.

And thanks for your suggestion to spy the console. That's a good idea.
