### ISSUE TITLE
Allowing <{element}></{element}> in JSX to render a variable element

### ISSUE THREAD

**Issue by rchanou** [facebook/react#3900]
You can now write almost anything in JSX that you can write in JavaScript...except for this case, as far as I can tell. Instead of having to write:

    React.createElement(someDynamicElement, props, children)

I think it would be neat to be able to write:

     <{someDynamicElement} {...props}>
       {children}
     </{someDynamicElement}>

It's not a huge deal, but it would plug the last leak in JSX syntax, allowing people to not have to do a context switch and think about the underlying transform in order to figure out how to do something like this.

**Comment by cmwelsh** [comment]
This works if you remove the brackets... am I confused?

```
 <someDynamicElement {...props}>
   {children}
 </someDynamicElement>
```

**Comment by cmwelsh** [comment]
You need to uppercase it so React knows it's not an HTML element.

**Comment by cmwelsh** [comment]
https://gist.github.com/sebmarkbage/f1f4ba40816e7d7848ad

**Comment by zpao** [comment]
Yea, this works since we'll just pass whatever is there along to createElement. You can even have a variable that is a string and a DOM component will be created. The point about capitalizing is important.

```js
var D = 'div';
return <D {...props}/>
```

**Comment by rchanou** [comment]
And now I know...thanks!

**Comment by digital-flowers** [comment]
Amazing ! i love react.
