### ISSUE TITLE
grunt test failing on "webdriver-phantomjs" task

### ISSUE THREAD

**Issue by laskos** [facebook/react#3906]
When I run ``grunt test`` on fresh copy of master i get error:

```
Running "webdriver-phantomjs" task
phantomjs START path:null args:--webdriver=9515
Warning: Bad argument Use --force to continue.

Aborted due to warnings.
$
```

My env:

```
OS: Mac OS X 10.8

$ phantomjs -v
2.0.0
$ npm -v      
2.7.4
$ node -v
v0.12.2
$ git rev-parse HEAD
4cf39ef195f8c8274e562ecfe913cd0da64afd13
```

Any clue to solve that?

**Comment by zpao** [comment]
Looks like it's probably the phantomjs version not being compatible. We're using 1.9.x.

**Comment by laskos** [comment]
Is there a way to use both of versions on one machine? I need phantom v2 in another projects

**Comment by zpao** [comment]
Not sure. We use https://www.npmjs.com/package/phantomjs, which will install a local phantomjs or fallback to the system one. I'm surprised that it doesn't complain about versions. I just tried with v2 installed and it seemed to still install a local copy. Forcing it did show that it detected the global version didn't match what we expect.

```
% node ./node_modules/phantomjs/install.js
PhantomJS detected, but wrong version 2.0.0 @ /usr/local/bin/phantomjs.
...
```

Running `grunt test` after that didn't have any issues (but it didn't before either)

**Comment by laskos** [comment]
I just reinstalled phantomjs package via npm and it works now. I don't know what actually happened there.
