### ISSUE TITLE
How to get the real elementNode(not ReactEl) in this.childrens?

### ISSUE THREAD

**Issue by huxiaoqi567** [facebook/react#3911]
like this , "ScrollView.children" return [ReactElement],
but i can't get the real HTMLElementNode by ReactElement. Because I want getComputedStyle of the node;

**Comment by edvinerikson** [comment]
Hi.
Maybe [`React.findDOMNode`](http://facebook.github.io/react/docs/top-level-api.html#react.finddomnode) will work?

e.g: 
```javascript
var childrenDOMNode = React.findDOMNode(this.children); //This will not work if children is an array
```

**Comment by zpao** [comment]
`this.props.children` will contain ReactElements, not DOM nodes. If you would like the actual DOM node you will need to assign a ref and use React.findDOMNode so that you can access it after the DOM has been mounted. See http://facebook.github.io/react/docs/more-about-refs.html
