### ISSUE TITLE
onWheel Broken in .13

### ISSUE THREAD

**Issue by browniefed** [facebook/react#3915]
It appears that onWheel is broken in React .13.X. It just returns an event full of undefined for everything.

Here is .12.2 fiddle https://jsfiddle.net/06fm6wv4/ working
Here is .13.3 fiddle https://jsfiddle.net/ddd7Lc9o/ not working

edit: to reproduce try using scroll wheel on the div that X/Y in it. 
Other info, I'm on a Mac using a track pad
Tested on latest Chrome/Firefox/Safari

**Comment by browniefed** [comment]
I'm wrong, for the record. Don't setState from an e (even console.log shows undefined) now that React is apparently better about recycling synthetic events(or something along those lines)

**Comment by zpao** [comment]
Yea, events are pooled. Probably some changes in batching resulted in the difference you're seeing, but either way, we reset the `e` object you're using so it's not really safe to just pass it around.

Changing your setState to copy properties off of `e` will make this work. `this.setState({deltaX: e.deltaX, deltaY: e.deltaY})`

**Comment by ffxsam** [comment]
Hmm, I don't see this in the official documentation anywhere. This is kind of important to know! @zpao Thanks for that valuable info, totally saved me from pulling my hair out. :)

**Comment by sairion** [comment]
@ffxsam Pooling behavior was documented very recently. 

https://github.com/facebook/react/blob/d984b687ecb24a2be5eb029f1f4d26c9819eb261/docs/docs/ref-05-events.md#event-pooling
