### ISSUE TITLE
React Id problems

### ISSUE THREAD

**Issue by smy2748** [facebook/react#3916]
My team is working on a project were sometimes we inject more than one React application into a page.  We recently noticed that the onClick handler specified for one of the applications was also getting applied to the node with the same data-reactid in the other application.  Is there a way to force the root component to use a data-reactid other than .0 so that each react application is sort of namespaced?

  We're using v0.11.2

**Comment by syranide** [comment]
If you're using the NPM-version (unbundled version) of React then you can use the following workaround for now https://github.com/facebook/react/issues/2713#issuecomment-67462102. Else you'll need to dig into the React bundle and replace `data-reactid` with something else, say `data-reactid2`.

**Comment by gaearon** [comment]
React 15 RC2 no longer uses `data-reactid` on the client (unless you are server rendering) so it is probably no longer an issue. If it still is, please provide a reproducible example on JSBin. Thank you!
