### ISSUE TITLE
Load webcomponents.js differently

### ISSUE THREAD

**Issue by zpao** [facebook/react#3919]
Our tests currently only pass in the browser when running in Chrome. This is because it supports WebComponents already. However they fail in every other browser. I think this is because of when webcomponents.js is actually loaded. It's currently getting packaged into react-test because we're requiring it. It creates a new `Node` which is resulting in nodes we create with `createNodeFromMarkup` to have a different prototype than what is expected in WebComponents. WebComponents's new Node prototype has a different implementation of `insertBefore` which does an `instanceof Node` check which our nodes are failing. I think if we loaded webcomponents.js into the browser before we loaded JS, the node we create for markup wrapping would have the right prototype.

**Comment by SusanMHC** [comment]
Hello Jim! I'm still getting your information in my gmail.com! & I've
change my gmail.com account. Can you Please take it off!? & I'm sorry I
kick you out of my life. You wasn't doing your part of getting a job. So
the only way you can get one is for me to kick you out. I do still love
you, I miss you like always, but I hope you find a better lover to be with
Jim. I had good times and the bad times with you & happy & sad times. I'll
always think of you. Tell your daughter I'm sorry for the stickers that I
was sending out to her. I've gotten rid of all your stuff & most of my
stuff too. Now I'm down to nothing. No boyfriends, no jobs, no money, no
place to move to yet. If you ever still want to just talk here's my number
916-578-2380. May is over at Scottys & Christy's place I gave her up. I am
so sorry please forgive me Jim!?
😍😛😘😢😓😋😟👅👋👑💋💌❤💔🌹🍀🌠🌙🌜🌛🌝📲📱📧💰💵📝📜📩📫📪📬📭🎭ℹ hope
we are 🆒 🆗🚹🚺📳📴💟♎💲💲⭕❌⭕❌The 🔚 Love always & forever Susan Clark
Goodbye
