### ISSUE TITLE
Props in getInitialState is anti pattern - what about componentWillMount?

### ISSUE THREAD

**Issue by Laoujin** [facebook/react#3927]
From the link:
https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

I'm wondering, is the following code a similar anti pattern or is it a good practice:

```
function getState(props) {
   var newState = { someState: false };
   if (!!props) {
      _.merge(newState, {
          totalCount: props.total || 0,
          items: props.items
      };
   }
   return newState;
}

var component = React.createClass({
  propTypes: {
    total: React.PropTypes.number
    items: React.PropTypes.array
  },
  getInitialState: function(){
    return getState();
  },
  componentWillMount: function() {
    this.setState(getState(this.props));
  },
  componentWillReceiveProps: function(newProps){
    this.setState(getState(newProps))
  },
  ....
}
```

So basically:  
- Props is not used in `getInitialState` but in `componentWillMount`
- All props are copied into state (some just copied, some get modified a bit ex: `'Mr. ' + props.name` etc)
- Render method uses state only

One of my colleagues is using this pattern extensively. I have a funny feeling about it but I can't really pinpoint what would actually be wrong/bad with his approach.

**Comment by syranide** [comment]
Props in state is not anti-pattern *if* they're intended serve as the initial state of a stateful component (say, you may not want the content of a textfield to update while it's focused). Another exception is if you need to perform expensive computations on the data which you may not want to repeat, then storing the result of those computations make sense.

But from what I can tell from your example all you're doing is mirroring props in state and I have no idea why that would be anything but a bad idea.
