### ISSUE TITLE
Missing `capture` attribute in `<input type="file" />`

### ISSUE THREAD

**Issue by jasonslyvia** [facebook/react#3948]
Consider following snippet:

```
var UploadImage = React.createClass({
  render: function() {
    return (
      <input type="file" multiple={true} capture={true} accept="image/*" />
    );
  }
});
```

**Expected DOM**

```
<input type="file" multiple capture accpet="image/*" />
```

**Current behaviour**

```
<input type="file" multiple accpet="image/*" />
```

Demo: [jsbin](http://jsbin.com/yoguti/1/edit?html,js)
W3C Specs: [http://www.w3.org/TR/html-media-capture/](http://www.w3.org/TR/html-media-capture/)

**Comment by cody** [comment]
I made a pull request, but @chicoxyzzy was a bit faster. The pull request are different, so maybe it is good that there are two. :smile:

**Comment by jasonslyvia** [comment]
@cody That's wonderful, Thx!
