### ISSUE TITLE
ReactJS is undefined if RequireJS is included on page

### ISSUE THREAD

**Issue by TruthReveller** [facebook/react#3953]
ReactJS is undefined if RequireJS is included on same page, as the define global variable causes a conflict with:

if("function"==typeof define&&define.amd)define([],n);

Uncaught ReferenceError: React is not defined

**Comment by zpao** [comment]
Yea, this is what happens with UMD, which is what our browser build uses. If you're using require.js then you need to do that across the board and `require('react')` instead.
