### ISSUE TITLE
FireFox Flash-object intermittently has no getAttribute

### ISSUE THREAD

**Issue by syranide** [facebook/react#3955]
This has been a long standing bug for me with (only) FireFox that has been hard to track down, I'm still not able to reproduce it on-demand, but I am able to reproduce it by manual brute-force so I know it's there.

The short is that I'm using Flash with React and every now and then React would throw an invariant `ReactMount: Unexpected modification of 'data-reactid'` when calling `React.findDOMNode`. Debugging it however revealed that everything is as it should, but very rarely and temporarily the `object` node for some reason loses its `getAttribute` method (and more, probably) which causes React to return the empty string for the ID, crash.

Updating `internalGetID` like below actually works and no invariants or errors are ever observed.

``` js
function internalGetID(node) {
  return node && node.nodeType === 1 && document.documentElement.getAttribute.call(node, ATTR_NAME) || '';
  //return node && node.getAttribute && node.getAttribute(ATTR_NAME) || '';
}
```

Personally I've currently worked around this by just getting the DOM node on mount, it works well enough for me at the moment (and I don't update the object so it shouldn't surface during updates either).

**Comment by ericnakagawa** [comment]
Is this still an issue?

**Comment by syranide** [comment]
I explicitly worked around it on my part, so I'm not sure whether FF still has the bug. But I imagine that it may not be a problem in React anymore due to React tracking DOM nodes immediately now rather than on demand.

Anyway, I'd guess apart from what's already being done there isn't much React can do. I mostly created this issue on the off-chance someone else stumbles upon the problem.

**Comment by aweary** [comment]
No movement on this in awhile, and I haven't seen any other reports, so I'm going to assume this was resolved somewhere by either React, Flash, or Firefox 🤷‍♂️
