### ISSUE TITLE
Display a warning when a ref is reused

### ISSUE THREAD

**Issue by glittershark** [facebook/react#3956]
I just spent like 15 minutes hunting down a bug that ended up to be caused by my reusing a ref - this was in a ~30 line component. I can only imagine that'd get *much* worse with bigger components. A warning against this in dev-mode would be nice.

**Comment by spicyj** [comment]
Unfortunately, we don't have a good way to fix this. See discussion at #1782.

**Comment by glittershark** [comment]
aww :cry:
