### ISSUE TITLE
Select/option elements onChange event does not return data-attributes 

### ISSUE THREAD

**Issue by rtorr** [facebook/react#3959]
I plan to look deeper into this, and maybe supply a pull request, if we decide this can be a feature.

Right now, text inputs onChange event.target.getAttribute('data-type') will return the data-types value, while select/option elements do no return any extra attributes from either object. It only seems to return value and name attributes.

**Comment by syranide** [comment]
Are you sure this is how it works natively? I wouldn't expect this to have changed in React. PS. Also, why would you do it like that, React component should never need to query the DOM like that.

**Comment by rtorr** [comment]
@syranide I am assuming it probably does not work that way natively, and that is why it might have been left off, and I would like some clarification on that if someone happens to know. I am not directly ever querying the dom in my components, but using what is returned in the event object for some properties on some input elements. I have a property that specifies the return type of the input, like boolean/string/integer, for reasons. Other inputs allow you to see data attributes returned in the event objects, just not select/option. 

so `React component should never need to query the DOM like that.` is not even relevant.

**Comment by cody** [comment]
@rtorr I tried to reproduce your problem, but it works for me: https://jsfiddle.net/7Lty54t4/
Maybe I have understand the problem wrong.

**Comment by rtorr** [comment]
@cody actually, the event object was being overwritten by some mixin. :(
