### ISSUE TITLE
Document how React's onChange relates to onInput

### ISSUE THREAD

**Issue by graue** [facebook/react#3964]
It would be nice for the [Forms doc](https://facebook.github.io/react/docs/forms.html) to be more explicit about the fact that React's `onChange` supersedes, and should generally be used in place of, the DOM's built-in `onInput` event. People might be used to using `onInput` instead for text inputs and textareas, since, with the raw DOM, the change event for these controls doesn't fire until the control loses focus.

**Comment by AnSavvides** [comment]
Opened a PR to address this: #4003

**Comment by AnSavvides** [comment]
Merged, hurray, we can close this now! :tada:

**Comment by sunyang713** [comment]
wait but why?

**Comment by mnpenner** [comment]
Yeah...why? I don't understand why React chose to make `onChange` behave like `onInput` does. As fas as I can tell, we have no way of getting the old `onChange` behaviour back. Docs claim it's a "misnomer" but not it isn't really, it does fire when there's a change, just not until the input also loses focus.

For validation, sometimes we don't want to show validation errors until they're done typing. Now the only way to do that is with onBlur but now we also need to check that the value has changed manually.

It's not that big of a deal, but it seems to me like React threw away a useful event when there was already one that does this.

**Comment by evpozdniakov** [comment]
Agree with mnpenner.

With ```onChange``` fireing on every keystroke, my redux store changes simultaneously. To avoid that I have to use ```onBlur```.

Finally we have two events - ```onInput``` and ```onChange``` - which work same manner.

**Comment by piotr-cz** [comment]
Besides there is no easy workaround to replicate such behaviour for the `<input type="range" />` element.

Native events behave such way that moving the slider around triggers an `onInput` event and releasing it triggers `onChange`.

**Comment by bcherny** [comment]
Another note: Autofill events (at least on Chrome/OSX) trigger `onInput`, but not `onChange`! So if I want to capture a change event to an input that might be filled using Chrome's autofill feature, I need to bind to both `onInput` (to detect keystrokes and autofill) and `onChange` (to placate React [1]).

[1] `Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `StatelessComponent`.

**Comment by ddelrio1986** [comment]
@mnpenner, @evpozdniakov for validation messages or things that you want to wait until they stop typing for use debounce in your event handler instead of waiting until onBlur.

**Comment by fabiosantoscode** [comment]
Still no way of using onChange? I've been writing lots of logic to get around not having a real change event.

I think to be a better abstraction, React needs to stick to onChange and let us use onInput without a silly warning.

Validation has never been this hard.

**Comment by graue** [comment]
For better or worse, this has been the behavior for quite a while, and many React users rely on it.

IMHO, it's probably too late in the game to totally change what "onChange" means in React. But if you feel strongly, maybe do a quick PR to propose a solution with a sensible upgrade path? (Before spending a lot of time on it, get the thoughts of the core team.)

**Comment by fabiosantoscode** [comment]
Right @graue, I've suggested #14857 instead to create a new event and minimise breaking changes.

**Comment by alamothe** [comment]
Definitely a huge design issue with React. Hope it doesn't stay this way forever

**Comment by qtv100291** [comment]
This is a mistake or a feature :/

**Comment by milessorce** [comment]
> This is a mistake or a feature :/

Features are supposed to be useful... this is the opposite of useful.

**Comment by artium-ryanh** [comment]
For anyone who needs a workaround to get true onChange behavior, you can implement your own component to use HTML's built-in `onchange` event. Here's how I've done it, inspired by [Kaspar Ettar's solution here](https://stackoverflow.com/a/62383569/3002766). Kaspar's allows you to use both onchange and oninput, mine is just for onchange.

```typescript
import { Component, InputHTMLAttributes } from 'react';

export interface OnChangeInputProps {
    onChange?: (target: HTMLInputElement) => void;
}

/**
 * This component restores the 'onChange' behavior of JavaScript.
 *
 * See:
 * - https://reactjs.org/docs/dom-elements.html#onchange
 * - https://github.com/facebook/react/issues/3964
 * - https://github.com/facebook/react/issues/9657
 * - https://github.com/facebook/react/issues/14857
 */
export class OnChangeInput extends Component<Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'onInput' | 'ref'> & OnChangeInputProps> {
    private readonly registerCallbacks = (element: HTMLInputElement | null) => {
        if (element) {
            const onChange: (event: Event) => void = (event) => {
                const target = (event.currentTarget!) as HTMLInputElement;
                this.props.onChange!(target);
            };
            element.onchange = this.props.onChange ? onChange : null;
        }
    };

    public render() {
        return <input type="text" ref={this.registerCallbacks} {...this.props} onChange={undefined} onInput={undefined} />;
    }
}
```

**Comment by dijonkitchen** [comment]
Looks like there is an official answer now:

https://reactjs.org/docs/dom-elements.html#onchange

**Comment by mnpenner** [comment]
@dijonkitchen I don't think that's new. See https://github.com/facebook/react/issues/3964#issuecomment-219575696

**Comment by andrechalella** [comment]
It is really aggravating, this "official answer". How presumptuous of them to call the HTML Spec official and consolidated event name a "misnomer".

**Comment by jimmythecoder** [comment]
2024 and issue still exists, this one wasted a serious chunk of time, atleast I now have an answer but if I didnt trust facebook before I sure dont trust them now. Always follow the spec, there should be no alternative breaking change or not.

**Comment by lolloz98** [comment]
Guys for people looking to do it with functions, expanding on Ettar solution, this seems to be working:

```typescript
import { TextField } from "@mui/material";

export default function MyCustomInput() {
    const registerCallbacks  = (element: HTMLInputElement | null) => {
        if (element) {
            element.onchange = () => console.log("onchange");
            element.oninput = () => console.log("oninput");
        }
    };

    return (
        <TextField label="Outlined" variant="outlined" inputProps={{ref:registerCallbacks, onChange: undefined, onInput: undefined}} />
    );
}
```

**Comment by EzioMercer** [comment]
Here is my simple implementation:

```jsx
const Input = props => {
    const inputRef = useRef(null);

    useEffect(() => {
        inputRef.current?.onchange = props.onChange;
    }, [inputRef.current]);
	
    return <input ref={inputRef} {...props} onChange={() => {}} />;
}
```

Maybe this solution has a lot of problems in complex tasks but for me in simple cases it covers everything what I need

[Try it](https://codepen.io/EzioMercer/pen/jENEBEe?editors=0011)
