### ISSUE TITLE
Lint tests

### ISSUE THREAD

**Issue by zpao** [facebook/react#3971]
After #3968, the next thing we should do is start linting our tests. Historically we've ignored them due to lack of parser compatibility. But that shouldn't be a problem anymore. We may want to integrate https://www.npmjs.com/package/eslint-plugin-react to more aggressively lint our JSX in tests.

cc @PiPeep

**Comment by hzoo** [comment]
A similar PR is being done in react-native too facebook/react-native#259 (adds babel-eslint, but also `eslint-plugin-react`)

**Comment by zpao** [comment]
Indeed. We have the benefit that we don't have to worry about anything internal yet so we can be more flexible :)
