### ISSUE TITLE
Rendering multiple tspans causes DOM updates but does not render on-screen

### ISSUE THREAD

**Issue by jroes** [facebook/react#3972]
I've created a component that takes input in a `textarea` that and generates a `tspan` for each line of the text in the `textarea`.

https://jsfiddle.net/69z2wepo/9130/

I'm seeing the correct SVG being generated, but the browser only displays the first `tspan` on-screen. I can even paste the output into another HTML-only fiddle and see it rendered correctly.

A kind soul (GreenJello on freenode#reactjs) was able to find a workaround that causes the `text` element to get re-rendered, which behaves as I expected, rendering all `tspan`s:

https://jsfiddle.net/69z2wepo/9168/

I thought this might be a browser bug, but I was able to successfully reproduce this in both Chrome 42 and Firefox 29.

Is this something related to the nature of SVG, is there a browser bug affecting multiple browsers, or is React doing something strange here?

**Comment by zpao** [comment]
Look like the result of not creating the element in the right place, we even have a comment explaining that this might happen. https://github.com/facebook/react/blob/master/src/shared/vendor/core/getMarkupWrap.js#L29-L30. I think we just need to add `tspan` in there.

**Comment by zpao** [comment]
We should be doing the right thing now. `tspan` is on the list - https://github.com/facebook/fbjs/blob/master/src/core/getMarkupWrap.js#L82

**Comment by gregorym** [comment]
I'm not sure if the is the same problem but here is the issue I have:

https://jsbin.com/famewaqeja/edit?js,console,output

**Comment by zpao** [comment]
It's the same. Your example works with 0.14 rc.
