### ISSUE TITLE
Creating tables in React is annoying

### ISSUE THREAD

**Issue by wmertens** [facebook/react#3979]
Due to the fact that HTML tables can't have children other than table rows, you cannot create parts of a table in a React element.

However, tables are a very useful way to represent tabular data, especially since you can do colspan and rowspan.

So in the case of a table comprising of many sections, you have to resort to calling functions instead of elements, meaning you don't get the benefits of props, state and rendering short-circuiting, plus your code looks different and is therefore more error-prone.

How can this be improved? Can React support a virtual dom node that doesn't render an actual dom node but can have children?

Alternatively, are there datagrid components that allow rendering like a table, with colspan and rowspan?

**Comment by gaearon** [comment]
Please see #2127 for a discussion on this.

**Comment by spicyj** [comment]
Closing in favor of #2127.
