### ISSUE TITLE
Mentions about input type file in documentation

### ISSUE THREAD

**Issue by kevinsimper** [facebook/react#3981]
Nowhere on the react documentation is there a reference on how to handle `<input type="file"/>`

It is a speciel field that can not be serialized, and I think it deserve some kind of mention, maybe just a link to some other resource or if it is just like a normal input, just saying that.

Could not find any issue mentioning this, therefore this issue.

**Comment by jimfb** [comment]
> It is a speciel field that can not be serialized

I'm confused, can you elaborate?

**Comment by kevinsimper** [comment]
@jimfb thanks your your question, i can see that it is not clear.

> I'm confused, can you elaborate?

The output of a `type="file"` is not text, but a file.

**Comment by jimfb** [comment]
Yes, but why is that relevant?  What does serializability have to do with anything?

**Comment by jimfb** [comment]
We generally only document the differences between React's behavior and the web standards.  In this case, as far as I can tell, we are simply conforming to the web standards, so it's not clear to me what remains to be documented.

**Comment by kevinsimper** [comment]
Yes, that if you know that it is that way with react and web standards.

But can input file be simulated in reacts virtual dom?

**Comment by jimfb** [comment]
What does it mean for an input file to be simulated?

Do you mean: is it possible to render `<input type="file" />`?

**Comment by kevinsimper** [comment]
A `<input type='text'>` has a `value` and `onChange` in virtualdom.

A `<input type='file'>` has a ? and `onChange` in virtualdom.

---

All the other types has their properties explained
![image](https://cloud.githubusercontent.com/assets/1126497/13153863/63775762-d676-11e5-85b3-923044dd65e6.png)

**Comment by jimfb** [comment]
We don't call out the `type` prop in particular, because it isn't any different from the web.  We don't call out `type="password"`, for instance.  In particular, that block you quoted only call out the ones that are exceptional (`checkbox`/`radio`).  I think we're being consistent here, and I think it's reasonable to only mention when we deviate from the expectation, so I'm going to close this out.

**Comment by zpao** [comment]
I think it might be worth mentioning something. Eg, you can't actually programmatically set the value of a file input which is a pretty big deal - it means you're more susceptible to issues with reconciliation.

You can only read. You also have to read from `node.files` which is just how those work even outside React, but still might be worth mentioning.

**Comment by kevinsimper** [comment]
@zpao Thanks for your reply :)

> I think it might be worth mentioning something. Eg, you can't actually programmatically set the value of a file input which is a pretty big deal - it means you're more susceptible to issues with reconciliation.

This was what i meant and could not explain :+1:

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#86

Let's continue the discussion there! Sorry for the inconvenience.
