### ISSUE TITLE
whether has a method to modify `isUnitlessNumber`

### ISSUE THREAD

**Issue by wibud** [facebook/react#3982]
How can I do when i has some special CSS properties which accept numbers but are not in units of "px", such as animationIterationCount etc? I notice that these CSS properties are defined in the `isUnitlessNumber` object. So should i modify `isUnitlessNumber` directly? Whether React has a public method to do this?

**Comment by zpao** [comment]
If this is a change that should be made for everybody, please submit a pull request.

If not, then you could modify your version of React or you could specify the value as a string and React won't add `px`.

There is not currently a public method to inject your own properties, and I'm not sure that we'll ever expose one.
