### ISSUE TITLE
Multi element conditionals trap the developer with key warnings

### ISSUE THREAD

**Issue by dantman** [facebook/react#3983]
The standard way to do `if` for something in the middle of a block of jsx is with a ternary or boolean expression. (ie: `{this.props.condition && <span>foo</span>}`)

If you need to do a conditional for multiple elements the natural method I expect would be:
```jsx
{this.props.condition && [
	<p>Foo</p>,
	<p>Bar</p>]}
```

However doing so generates warnings like:
  
>  "Warning: Each child in an array or iterator should have a unique "key" prop. Check the React.render call using `<p>`. See https://fb.me/react-warning-keys for more information."

This array isn't a list of things that'll be reordered or anything, it's just a set of elements that are all conditional together.

None of the alternatives to avoid the warning are very good.

A) Add key="" to each of the element. For a few elements, which might even be inline elements like a `<b>` next to two strings, being forced to add a key="" is really overboard.

B) Do the condition for each element separately:
```jsx
{condition && <p>Foo</p>}
{condition && <p>Bar</p>}
```
...I don't think I need to explain why repeating the same code over and over is a bad thing.

C) Wrap the elements in one element:
```jsx
{this.props.condition && <div>
	<p>Foo</p>,
	<p>Bar</p>
</div>}
```

Adding extra elements into code should not be required when those elements only exist to satisfy React quirks and are not actually needed inside the DOM.

**Comment by spicyj** [comment]
You listed basically all the options. In the future we might support a syntax like

```
{this.props.condition && <frag>
    <p>Foo</p>
    <p>Bar</p>
</frag>}
```

which wouldn't result in an added HTML element, but there's nothing else to do here now.
