### ISSUE TITLE
Multiple Owners / Refs

### ISSUE THREAD

**Issue by paulshen** [facebook/react#399]
When a component is rendering, it is free to return whatever it wants given its props (including children). One thing it may want to do is mutate an input component instance, including attaching a ref.

What are best practices wrt modifying component instances that are passed in (either via props or children)?

http://jsfiddle.net/paulshen/S773F/
In this fiddle, it seems reasonable if both `Parent` and `Child` want to be owners of the content. Although `Parent` is the original owner/creator, `Child` has full control of the output when it is rendering.

Ideally, I would expect React to support the ability for both `Parent` and `Child` to access the same component via refs. It seems like multiple owners/refs is a reasonable solution?

**Comment by syranide** [comment]
[React.cloneElement](https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement), so this seems solved now.

**Comment by spicyj** [comment]
We don't have a solution for adding a ref to an element with a string ref, but otherwise yes.

**Comment by jurca** [comment]
One possible solution to this is using multiple refs (one used by parent, one used by child) on the rendered element. This little library might help: https://www.npmjs.com/package/@seznam/compose-react-refs
