### ISSUE TITLE
State update of Parent (not Owner) does not render the children - 0.14

### ISSUE THREAD

**Issue by rrag** [facebook/react#3991]
say

```js
var Owner = React.createClass({
  render: function () {
    return <Parent><Child foo="bar"/></Parent>
})
```

When Owner state is updated, the `render` function is called on Owner, Parent and Child.
When Parent state is updated, the `render` function of Parent is called, but not on the Child.

This was the expected behavior till 0.13.x, but with https://github.com/facebook/react/issues/2112  introduced a behavior where Parent state update can change the return of `getChildContext` and hence the Child needs an update.

[jsbin](http://jsbin.com/jeyeboleki/6/edit?js,console,output) explaining the problem.

Owner state update, renders both Parent and Child
Parent state update renders *only* the Parent

**Comment by spicyj** [comment]
See #2517.
