### ISSUE TITLE
Wrong row offset and Y-scroll position after dynamically changed row height.

### ISSUE THREAD

**Issue by krystian-3c** [facebook/react#3994]
I'm using **rowHeightGetter** function to dynamically change row height on state change. 
Unfortunately, after rerender rows won't position correctly. 
Expanded row gets negative offset value and Y-scroll doesn't recalculate.

Calling **_updateRowHeight** method in **getRowPosition** (**FixedDataTableScrollHelper**, line 114: **this._updateRowHeight(rowIndex);**), fixes offset recalculation.
```javascript
this._updateRowHeight(rowIndex);
```

Forcing Y-scroll recalculation by commenting lines from 634 to 636 and line 641 in **FixedDataTable.react.js**, fixes Y-scroll problem
```javascript
//if (oldState && props.overflowY !== 'hidden') {
//  scrollY = oldState.scrollY;
//} else {
   scrollState = this._scrollHelper.scrollTo(props.scrollTop);
   firstRowIndex = scrollState.index;
   firstRowOffset = scrollState.offset;
   scrollY = scrollState.position;
//}
```
I'm sure those are not most elegant solutions, added only for information purpose.
Whats the proper solution for this problem?

**Comment by JohnyDays** [comment]
It would probably be adding a property to the data table that would manually allow you to agree to never change row height for the caching performance optimizations that allows, and by default just recalculate the position on re-render

**Comment by zpao** [comment]
I think you want to file this in the fixed-data-table repo: https://github.com/facebook/fixed-data-table
