### ISSUE TITLE
HTML to JSX Compiler does not convert "tabindex" to "tabIndex"?

### ISSUE THREAD

**Issue by af7** [facebook/react#3996]
I used this converter to convert a DIV that had `tabindex = "-1"` inside it:

https://facebook.github.io/react/html-jsx.html

The conversion gave this:  `tabindex = {-1}`  (notice that the `index` word is not capitalized)

But then, console.log gives the following (reasonable) warning: 
`Warning: Unknown DOM property tabindex. Did you mean tabIndex?`

May I assume that this is a bug on the converter? Or not?

Thanks.

**Comment by zpao** [comment]
@Daniel15 do we still maintain that here or is it all part of https://github.com/reactjs/react-magic?

**Comment by Daniel15** [comment]
This is part of react-magic and was fixed in https://github.com/reactjs/react-magic/pull/20. I just need to deploy the web version again.

**Comment by Daniel15** [comment]
Pushed an update, this is fixed now.
