### ISSUE TITLE
Why no method to change default event plugins?

### ISSUE THREAD

**Issue by eriklynd** [facebook/react#4001]
Hi,

I noticed that method `_resetEventPlugins` of module `EventPluginRegistry` is marked as private and only for unit test. And `injectEventPluginOrder` and `injectEventPluginsByName` are not able to override event plugin configure after first injecting. 

So it seems I can neither replace the default event plugins, nor add a new kind of event plugin without modify the code of React. Why is it designed like this? Is it good to support modifying/extending event plugins after injecting default ones?

Thanks!

**Comment by syranide** [comment]
Injecting global event plugins is not a sustainable approach, you're free to reach in and do if you absolutely must but beware of the long-term consequences. There are some brief discussions on this topic in various issues throughout but there has been little movement on this so far.

In the future, please use the community forum for questions.
