### ISSUE TITLE
custom proptype validators do not receive all props in `props` argument

### ISSUE THREAD

**Issue by pwmckenna** [facebook/react#4005]
Instead, the `props` object only contains the single key that matches the proptype key.
```jsx
var Component = React.createClass({
  propTypes: {
    a: function (props, propName, componentName) {
      // props will only ever contain the key 'a', regardless of props passed into the component
    }
  }
  ...
});

<Component a={1} b={2} />
```

**Comment by cody** [comment]
Works for me: https://jsfiddle.net/vgraw9nu/

But what I find surprising is that the validator function gets called twice. I wonder why?

**Comment by zpao** [comment]
@pwmckenna any more information? Seems to be working in 0.13 and master.

> But what I find surprising is that the validator function gets called twice. I wonder why?

We still validate at both createElement time and render time (since you can modify props after creating the element).
