### ISSUE TITLE
Redundant codes in ReactCompositeComponentMixin.mountComponent

### ISSUE THREAD

**Issue by Fischer-L** [facebook/react#4014]
While tracing codes, found that:

Inside ReactCompositeComponentMixin.mountComponent, the code reads
```
    // These should be set up in the constructor, but as a convenience for
    // simpler class abstractions, we set them up after the fact.
    inst.props = publicProps;
    inst.context = publicContext;
    inst.refs = emptyObject;
```
https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L149

However, at ReactClass.createClass, the props and context are set already
```
      this.props = props;
      this.context = context;
```
https://github.com/facebook/react/blob/master/src/isomorphic/classic/class/ReactClass.js#L826

It seems no reason to have duplicated codes.
Should we remove one of these two code snippets and only keep one ?
Or  is there any reason for this ?

If no other concerns, I would suggest move the setup of the props, context and refs back to the class constructor.
Make the duty of constructing and the duty of mounting clear.

**Comment by zpao** [comment]
The comment you included explains the reasoning "as a convenience for simpler class abstractions, we set them up after the fact". Not all component classes will be created with `createClass`. Already you can use ES6 classes. If you extend our base class then props and context will be set up before hand. But you don't have to extend our base class.

**Comment by kohlikohl** [comment]
I agree with @Fischer-L here as the "convenience" is actually causing an issue for me when using decorators to modify the props before they are passed to the constructor. 

So I have a decorator like this:
```javascript
function decorator(constructor){
    return function (props) {
        // ... code to transform props
        return new constructor(transformedProps);
    }
}
```
which operates on the original props and passes them to the constructor.
This works fine up to the point where the transformed props are overwritten again by the original props with following line:

```javascript
inst.props = publicProps;
```


Potentially a solution to this could be to only set the props when the component is not instantiable?

```javascript
if (!canInstantiate || inst === null || inst === false || ReactElement.isValidElement(inst)) {
    renderedElement = inst;
    inst = new StatelessComponent(Component);

    inst.props = publicProps;
    inst.context = publicContext;
    inst.updater = ReactUpdateQueue;
}
```

What do you think?

Of course if there is another way to keep the transformed props, please do let me know. :)
