### ISSUE TITLE
XSS issue while rendering link(website)

### ISSUE THREAD

**Issue by ak-d** [facebook/react#4015]

**Comment by syranide** [comment]
The responsibility of sanitizing user data falls on you. It's usually advisable to reject any non-absolute non-HTTP(S) URLs really. This applies to all properties that are interpreted in any way, so beware of styles (colors, sizes, etc) too.

**Comment by ak-d** [comment]
But Other JS Framework e.g; Angular, Ember hanling it properly.

**Comment by syranide** [comment]
#3473

**Comment by ak-d** [comment]
#3473 Known issue!!! :-1: :-1: :-1: :-1:
