### ISSUE TITLE
React 0.14 throwing unexpected errors

### ISSUE THREAD

**Issue by blainekasten** [facebook/react#4017]
So, I just gave 0.14 a test with my current code that runs on 0.13.3. It is throwing some very unexepected errors with one of my components. I have a simple wrapper class around a select dom node. Here is the ES6 code:

```js
import React from 'react';
class Select extends React.Component {

  render() {
    var options = this.props.children,
        name;

    if (Array.isArray(this.props.options)) {
      name = this.props.name;
      options = this.props.options.map(function(item){
        item = Array.isArray(item) ? item : [item, item];
        return <option key={name + item[0]} value={item[0]}>{item[1]}</option>;
      });
    }


    return (
      <label className={`select ${this.props.labelClassName}`}>
        <select {...this.props}>{options}</select>
      </label>
    );
  }
}

Select.propTypes = {
  name: React.PropTypes.string,
  options: React.PropTypes.array,
  labelClassName: React.PropTypes.string
};

Select.defaultProps = {
  labelClassName: ''
};

export default Select;
```

When using this component within others, I get the following errors in console:

`"Warning: unmountComponentAtNode(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate. Check the render method of Select."`
`"Warning: Select is accessing getDOMNode or findDOMNode inside its render(). render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead."`

I am not sure if my code needs some migration for 0.14 or if there is some bug here. But i'm willing to dig into it if ya'll think it might be a bug.

**Comment by zpao** [comment]
Can you provide a bit more information? Are you using Babel to transform? What version of React exactly? (we have a couple alphas published, or maybe building from master/specific revision)

**Comment by blainekasten** [comment]
Yeah.

Transpiler: Babel
React version: github:master:latest (seems to be 0.14.0-alpha3)

but essentially I ran `npm install github:facebook/react` which should just pull down github master I believe.

**Comment by zpao** [comment]
`npm install github:facebook/react` won't give you react. Currently it'll give you react-tools.

Nothing is jumping out at me though. It would be good if you could create a complete repro on jsbin (react.jsbin.com - change the JSX option to Babel). You can point at the build for 0.14.0-alpha3 http://react.zpao.com/builds/master/1432770455-8471cc5f47bac0dbfd6b3123775fc28757db0ed3/react.js

**Comment by abhilashsajeev** [comment]
I think still xmlns in svg image is not supported.

**Comment by zpao** [comment]
@blainekasten are you still seeing this?

**Comment by blainekasten** [comment]
I'm not with the company that code was from. So I'm not sure if it's still an issue or not.. I would say probably just close and see if someone else runs into it. I suspect it was an issue with getting the wrong version of react.

**Comment by zpao** [comment]
👍 thanks for the update!
