### ISSUE TITLE
componentDidUpdate and componentWillUpdate pass incorrect state

### ISSUE THREAD

**Issue by xowiun** [facebook/react#4018]
with these 2 functions we should be able to react to state/props change, but that not happening with  objects.
```
var Component = React.createClass({
    getInitialState: function () {
        return {var1: 1, var2: {a: 1}};
    },
    componentDidMount: function () {
        setInterval(function () { this.updateState() }.bind(this), 2000);
    },
    componentWillUpdate: function (nextProps, nextState) {
        console.log('----');
        console.log(this.state.var1, nextState.var1);
        console.log(this.state.var2, nextState.var2);
    },

    updateState: function () {
        var var2 = this.state.var2,
            var1 = this.state.var1;
        var1 = var1 + 1;
        var2['a'] = var2['a'] + 1;
        this.setState({ var1: var1, var2: var2 });
    },
    render: function () {
        return <div>1</div>
    }
});
```
result:
```
----
2 3
Object {a: 3} Object {a: 3}
----
3 4
Object {a: 4} Object {a: 4}
----
4 5
Object {a: 5} Object {a: 5}
```
as you can see, numbers in states are different, but objects in states are identical, so we cant rely on them.
the same with componentDidUpdate - objects in prevState are already modified.

**Comment by zpao** [comment]
Yes, deep updates in state like this can be tricky. But this is the nature of JS - if you pass an object by reference then it will remain that way. In your case that's exactly what's happening with `var2`. Generally state will not be great for things like this and you may want to consider alternatives like deep cloning or immutable data structures. We have no intention of doing the state clones ourselves as that can be an expensive operation with lots of nuance. If you need it, then it's on you to do it.

**Comment by xowiun** [comment]
thanks for answer. these words confused me: `Treat this.state as if it were immutable.` - so i did, while thinking that React will handle this cases.

**Comment by spicyj** [comment]
Those words meant, "do not mutate this.state", not that React will make a copy.
