### ISSUE TITLE
Please deprecate Mixins

### ISSUE THREAD

**Issue by ysmood** [facebook/react#4023]
Mixins make things unclear. For example:

```javascript
React.createClass({
   mixins: [A, B, C, D],

   anEvent: function() {
      this.foo()
   },

   // ...
})
```

It will be hard for people to find out from which mixin does the `foo` come. They may have to search for the 4 mixins' documentation to know it. If the `anEvent` is hard to trigger, they even cannot use the devtool to trace the source code of `foo`.

**Comment by syranide** [comment]
`createClass` is pretty much depreciated (but supported) in favor of ES6 classes. So going forward React no longer has an opinion on how components classes should be constructed and it's up to you to use whatever class mechanism you prefer.

Personally I agree with you on mixins, they may offer some benefit for certain purposes but largely seem to be a very poor solution to the problems developers usually apply them to.

**Comment by af7** [comment]
React's docs say the following:

*"Unfortunately ES6 launched without any mixin support. Therefore, there is no support for mixins when you use React with ES6 classes.* **Instead, we're working on making it easier to support such use cases without resorting to mixins.** "

I wonder if there is any progress on this. Almost all code we find on github uses Mixins but we are using ES6 classes, so there are difficulties in using such code. How do you tackle this? Thx.

**Comment by ysmood** [comment]
@syranide I you understand what I mean, you should `console.warn` users who try to use Mixins, tell them that React will drop Mixins in the future.

**Comment by syranide** [comment]
@ysmood React isn't dropping mixins, going forward React has no opinion and `React.createClass` is effectively being made into a separate module. `React.createClass` *could* warn that mixins is a bad idea, but effectively everyone would see the warning and those who really prefer mixins (right or wrong) would just find it annoying. If you're at all subscribing to where React is heading then you'll know mixins is something you should avoid. So while I think a warning seems like a great idea on the surface, I cannot see it being anything but a disaster in practice. cc @zpao 

> Why close this issue so fast.

"Deprecate Mixins" doesn't seem actionable to me.

**Comment by ysmood** [comment]
Well, at least you should warn the developers in the official documentation?

**Comment by spicyj** [comment]
@ysmood We're not ready to deprecate mixins because we don't have good replacements for all of their use cases. When we do, we'll probably move towards deprecating mixins and React.createClass, but that is at least months away.

**Comment by ericelliott** [comment]
[react-stampit](https://github.com/stampit-org/react-stampit) may provide a nice alternative to mixins. Check it out. We'd love to get feedback. =)

**Comment by james-gardner** [comment]
"Mixins is an anti-pattern for real-world composition." - So are classes in ES6.

**Comment by GGAlanSmithee** [comment]
@james-gardner not more than prototypical inheritance is an anti-pattern in ES5,

**Comment by ericelliott** [comment]
> "Mixins is an anti-pattern for real-world composition." - So are classes in ES6.

Agreed. Even with decorators, you still have to decide what is a base class and what is a decorator, and you still get tied to the constructor by the `new` keyword. [Stamps don't have those problems](https://medium.com/javascript-scene/introducing-the-stamp-specification-77f8911c2fee#.yx9id9li9).

**Comment by ysmood** [comment]
Only pure functional can solve the composition problem of class or mixins. Why keep things immutable and stateless.

React hope people to implement state less render, but the core use stateful OO class. It just frustrates me.
