### ISSUE TITLE
BUG: React.findDOMNode(this) always null in higher-order-component (0.13.3)

### ISSUE THREAD

**Issue by gilbox** [facebook/react#4044]
```
const higherOrderComponent = (Component) => React.createClass({
  componentDidMount() {
    console.log( React.findDOMNode(this) ); // => null
  },

  render() {
    return <Component {...this.props} />;
  }
});
```

**Comment by browniefed** [comment]
Does giving `<Component>` a ref and passing that into `findDOMNode` work?

**Comment by gilbox** [comment]
> Does giving <Component> a ref and passing that into findDOMNode work?

no

**Comment by gilbox** [comment]
need a demo

**Comment by browniefed** [comment]
@gilbox seems to work http://jsbin.com/tuxupevefi/2/edit?html,js,output

**Comment by gilbox** [comment]
The bug only happens if the wrapped component returns null the first time `render()` is called.

**Comment by browniefed** [comment]
@gilbox yeah that sounds like correct behavior to me

**Comment by gilbox** [comment]
It's not correct, but I don't think I'm explaining it very well (here is correct behavior: http://jsbin.com/dobagekaja/1/edit?html,js,output)

I can't reproduce a simple version of this bug, but returning `<noscript />` instead of null from my wrapped component is simple enough for now.

**Comment by spicyj** [comment]
@gilbox Can you try to make a minimal repro case? If this is a React bug I'd like to fix it.

**Comment by syranide** [comment]
@gilbox I fail to see the problem in your fiddle, it outputs null for as long as `Foo` is returning null (it has no associated DOM node), but when `Foo` starts returning a div then associated DOM node is output in the console... ?

**Comment by gilbox** [comment]
>  I fail to see the problem in your fiddle

That's why I closed this issue ;-)

The code in my application is very similar, but for some reason I haven't been able to replicate a simple case.

**Comment by syranide** [comment]
@gilbox Do you mean that `findDOMNode` returns null for a component even though it has rendered an element, so if you replace null with `<noscript />` then it actually works and returns the correct node (**not** noscript)? I.e. something like #2353 (that was supposedely fixed)?

**Comment by gilbox** [comment]
> Do you mean that `findDOMNode` returns null for a component even though it has rendered an element, so if you replace null with `<noscript />` then it actually works and returns the correct node

bingo. (but I can't prove it yet :-/ )

**Comment by gilbox** [comment]
Update: the bug is not in react :dancer:

**Comment by olegerm** [comment]
@gilbox, I met the same issue. 
Could you describe cause of bug?

**Comment by gilbox** [comment]
I did something wrong in my own code @olegerm but I don't remember what that was anymore.
