### ISSUE TITLE
Context and props.children

### ISSUE THREAD

**Issue by chtefi** [facebook/react#4053]
Hi,

I'm having some troubles to understand how the context is passed on when using `this.props.children`. I don't know if it's a bug or if it's expected. I'm using React v0.13.3.

I can make it work using `this.props.children()` (as a function), but not using the simple declarative way.

Example :

- The application, using ContextEmitter (children as a function), and ContextEmitter2 (children using declarative way)
```javascript
export default class MyApp {
  render() {
    return (
      <div>

        <ContextEmitter>
          {() => <ul>
              <ContextConsumer />
              <ContextConsumer />
            </ul>
          }
        </ContextEmitter>

        <ContextEmitter2>
            <ul>
              <ContextConsumer />
              <ContextConsumer />
            </ul>
        </ContextEmitter2>
      </div>
    );
  }
}
```

- ContextConsumer, a simple consumer of `this.context.value`.
```javascript
export class ContextConsumer extends React.Component {
  static contextTypes = {
     value: React.PropTypes.number.required
  }

  render() {
    return <li>Context value: { this.context.value }</li>;
  }
}
```

- ContextEmitter,  a parent, creating a context and rendering `this.props.children()` : context is properly passed on.
```javascript
export class ContextEmitter extends React.Component {
  static childContextTypes = {
    value: React.PropTypes.number.required
  };

  getChildContext() {
    return { value: 2 };
  }

  render() {
    return <ul>ContextEmitter { this.props.children() }</ul>;
  }
}
```

- ContextEmitter2, a parent, creating a context and rendering `this.props.children`: context is not passed on.
```javascript
export class ContextEmitter2 extends React.Component {
  static childContextTypes = {
    value: React.PropTypes.number.required
  };

  getChildContext() {
    return { value: 2 };
  }

  render() {
    return (<ul>ContextEmitter2 { this.props.children }</ul>);
  }
}
```

I can see this result :
```
ContextEmitter
Context value: 2
Context value: 2
ContextEmitter2
Context value:
Context value:
```

Meaning using the function way for `children` `() => <ContextConsumer />` it works, otherwise it does not.

Is this expected ? Why such difference ?

Thanks

Edit: I'm having several warnings in the console for the non-working case btw.
Warning: Failed Context Types: Invariant Violation: ContextEmitter: child context type `value` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `MyApp`.
...
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `2`) for key (value) while mounting ContextConsumer (see: http://fb.me/react-context-by-parent)

**Comment by jquense** [comment]
Context is currently "Owner" based, meaning that context is passed to components taht have the same owner or have a common owner. This is different than parent based context (coming in `0.14` and the source of your warnings). An owner is the component that creates the component, so when using `this.props.children` that component doesn't _own_ the children (it didn't create them) thats why they get no context. This is switch to parent based in the next version partly because of exactly this confusion.

https://facebook.github.io/react/blog/2015/02/24/streamlining-react-elements.html#owner

**Comment by chtefi** [comment]
Indeed, I've tested with React v0.14.0-alpha3, and it works (with the non-function notation). It makes more sense.

Thanks.
