### ISSUE TITLE
Automatically populate props.children when not declared

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#4055]
I am currently writing code to traverse through a form with all its inputs - this to collect form data for a PUT. I'm almost there but there is one problem left: children aren't always populated.

I have something like this recursive function in coffee to collect all form children:

```coffee
_collectAllChildren: (target) ->
  children = []
  React.Children.forEach(target.props.children, (child) =>
    children.push(child)

    if child.props.children
      children = children.concat(@_collectAllChildren(child))
  )
  children
```

But inside one form component, I have nested React elements (using React bootstrap) like this one called `FirstLastNameInput`:

```cjsx
  render: ->
    <Row className = {@props.rowClassName}>
      <Input
        hasFeedback
        required
        md               = 6
        type             = 'text'
        name             = 'firstName'
        value            = @props.firstName
      />
      <Input
        hasFeedback
        required
        md               = 6
        type             = 'text'
        name             = 'lastName'
        value            = @props.lastName
      />
    </Row>
```

and here is the problem. When `_collectAllChildren` tries to collect all children for FirstLastNameInput, then it has no children but I wish `@props.children` would return the properties of these two Inputs anyway.

This would make things a lot easier and prevents me from doing dirty React hacks.

**Comment by binarykitchen** [comment]
I guess, my question is similar to this one:
https://github.com/facebook/react/issues/1312

**Comment by syranide** [comment]
`props.children` is not the rendered child instances, it is the child elements provided to your component's associated element (which is not a guarantee they end up being rendered).

> I am currently writing code to traverse through a form with all its inputs

React does not provide a way to do this and (AFAIK) never will for non-testing purposes, it goes against current best practices for React. You should be explicit for the purpose of readability and keeping components isolated.

**Comment by binarykitchen** [comment]
I think I get your message, thanks @syranide !
