### ISSUE TITLE
Wrong html file name

### ISSUE THREAD

**Issue by tako-black** [facebook/react#4062]
At gh-pages branch, there are [ `getting-started.ja-JP.html` ](https://github.com/facebook/react/blob/gh-pages/docs/getting-started.ja-JP.html) and [ `tutorial.ja-JP.html` ](https://github.com/facebook/react/blob/gh-pages/docs/tutorial.ja-JP.html) files.
I think those file name must be `getting-started-ja-JP.html` and `tutorial-ja-JP.html`.

**Comment by zpao** [comment]
Thanks! I just pushed the change to the stable branch so this should be updated on the site and in the gh-pages branch as soon as it builds.

**Comment by tako-black** [comment]
@zpao Thanks!
