### ISSUE TITLE
With React ES6 syntax class methods are not bind to the instance context

### ISSUE THREAD

**Issue by vladmiller** [facebook/react#4065]
Here is the example

http://jsbin.com/citafaradu/2/edit?js,console,output

**Comment by cody** [comment]
React's ES6 classes have no autobinding. This is documented here: https://facebook.github.io/react/docs/reusable-components.html#no-autobinding

The reason is that javascript's ES6 classes have no autobinding neither. React tries to not reinvent stuff that is already in javascript. ES5 has no nice syntax for classes, so React had to invent it's own classes. But now with ES6 classes we can just use standard javascript.

**Comment by vladmiller** [comment]
Yeah, so this is sort of confusing

> You'll have to explicitly use .bind(this) __or arrow functions =>.__

And here was my problem http://stackoverflow.com/questions/30726162/how-to-properly-bind-current-object-context-in-es6-using-babelify

**Comment by cody** [comment]
That means that you can do either
```js
<input type="text" onChange={this.handleChange.bind(this)} />
```
or
```js
<input type="text" onChange={(e) => this.handleChange(e)} />
```
or
```js
<input type="text" onChange={(e) => this.setState({ demo: e.target.value })} />
```

**Comment by vladmiller** [comment]
Still kind of ugly, huh? Ok man, thanks, I think it's better then binding contexts in constructor

**Comment by BerkeleyTrue** [comment]
You could also use es7 bind operator

`<input type="text" onChange={ ::this.handleChange } />`

@vladmiller If that works for you please close this issue.

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/3040
https://github.com/facebook/react/issues/3509
https://github.com/facebook/react/issues/3090

**Comment by zpao** [comment]
This was called out in all of our documentation about ES6 classes and there are a number of issue on it. Closing this out but feel free to follow along in one of the other places.

**Comment by Ajju2211** [comment]
Different ways of binding
 Within the constructor
 constructor(props) {
    super(props);
    this.state = {
      someValues:""
    };
    
    this.handleBindedChange = this.handleBindedChange.bind(this);
  }
or
<input type="text" onChange={this.handleChange.bind(this)} />
or

<input type="text" onChange={(e) => this.handleChange(e)} />
or

<input type="text" onChange={(e) => this.handleChange.bind(this)(e)} />

or

<input type="text" onChange={(e) => this.handleChange.bind(this,e)()} />

or use arrow functions for handlers

handleChange = (e) => {
this.setState({
      someValues: e.target.value
});
}
