### ISSUE TITLE
Stop building react-source gem

### ISSUE THREAD

**Issue by zpao** [facebook/react#4069]
I'm not sure how much value there really is in this. react-rails already stopped using it and just builds the files in itself.

cc @rmosolgo

**Comment by zpao** [comment]
(I'm currently running https://github.com/grosser/gem-dependent to find out how many there might be - looks like this script may take a day to hit the end point for every gem in the registry)

**Comment by rmosolgo** [comment]
:+1: I made `jsx-ruby` but it's just a toy :)
