### ISSUE TITLE
React re-renders svg in html namespace

### ISSUE THREAD

**Issue by neojski** [facebook/react#4072]
Consider the following code:

```js
  var thing = <g> 
    <line x1="0" x2="100" y1="-2775.7" y2="-2775.7" stroke="red" />
  </g>;
  React.render(thing, this.g);

  var thing = <g> 
    <line x1="0" x2="100" y1="-2775.7" y2="-2775.7" stroke="red" />
    <line x1="0" x2="100" y1="-2770.7" y2="-2770.7" stroke="red" />
  </g>;
  React.render(thing, this.g);
```

The first line is rendered in `http://www.w3.org/2000/svg` `namespaceURI` but the second one in `http://www.w3.org/1999/xhtml`. If you skip the first rendering it works.

**Comment by neojski** [comment]
Apparently, [dangerouslyRenderMarkup](https://github.com/facebook/react/blob/4c3e9650ba6c9ea90956a08542d9fa9b5d72ee88/src/renderers/dom/shared/Danger.js#L51) doesn't work with svg.

**Comment by neojski** [comment]
Or, maybe, I'd say that [createNodesFromMarkup](https://github.com/facebook/react/blob/52752446760dee0bc7232b4146f5a309ac57f065/src/shared/vendor/core/createNodesFromMarkup.js) does not work as expected. I see it gets markup

```
<line data-danger-index="0"  x1="0" x2="100" y1="-2770.7" y2="-2770.7" stroke="red" data-reactid=".0.1"></line><line data-danger-index="1"  x1="0" x2="100" y1="-2765.7" y2="-2765.7" stroke="red" data-reactid=".0.2"></line>
```

and it gets wrap

```json
[1, "<svg>", "</svg>"]
```

and it creates nodes via `innerHTML` like this:

```
<div xmlns="http://www.w3.org/1999/xhtml"><svg><line data-danger-index="0" x1="0" x2="100" y1="-2770.7" y2="-2770.7" stroke="red" data-reactid=".0.1"></line><line data-danger-index="1" x1="0" x2="100" y1="-2765.7" y2="-2765.7" stroke="red" data-reactid=".0.2"></line></svg></div>
```

but for some reason `namespaceURI` of that `svg` is `http://www.w3.org/1999/xhtml`.

**Comment by sebmarkbage** [comment]
cc @spicyj This wouldn't work with the context scenario. Maybe separate renderers are need at the top level? Or at least a flag.

**Comment by neojski** [comment]
@sebmarkbage, what do you mean by 'context scenario'? Or separate renderers at the top level?

**Comment by sebmarkbage** [comment]
Sorry that was directed to @spicyj based on a conversation I had with him yesterday

**Comment by neojski** [comment]
@sebmarkbage, I thought you're referring to my PR and pinging @spicyj. Do you have any comments about my PR? In particular, where should I put tests?

**Comment by spicyj** [comment]
@sebmarkbage It works if ReactMount supplies the context.

@neojski Are you using XHTML? I was under the impression that in HTML, just an `<svg>` tag with no explicit namespace should work fine.

**Comment by neojski** [comment]
@spicyj, correct, I'm using xhtml (that's because in my svg there are foreign namespaces and they are ignored in html). I can test if my example works in pure html but I suppose that you might be right.

**Comment by sebmarkbage** [comment]
@spicyj What about ambiguous elements like? `React.render(<title />, container);` This doesn't have a context to be picked up.

**Comment by spicyj** [comment]
@sebmarkbage I assumed we'd look at the namespace of the container. Sorry for not being more precise.
