### ISSUE TITLE
About the performance for mounting ReactComponents

### ISSUE THREAD

**Issue by huxiaoqi567** [facebook/react#4075]
Hi, I'm trying to implement ListView Components run on browser. Then I found that React. renderToString , React.renderToString is not performance as well as I need.

View the react source code, I found the function mountComponent cost performance. Do you have a better way for this?

code here:

function renderToString(element) {
return transaction.perform(function() {
      var componentInstance = instantiateReactComponent(element, null);
      //low performance here !!!  ------------------------------
      var markup = componentInstance.mountComponent(id, transaction, emptyObject);
     //low performance here !!!  ------------------------------

}

**Comment by spicyj** [comment]
Virtually all of the component code runs in that `.mountComponent` call, so it's not surprising that you found it took most of the runtime. We're been continually trying to make performance improvements to React and will continue to do so.
