### ISSUE TITLE
The runtime environment should be able to purge all module-scoped global caches

### ISSUE THREAD

**Issue by lukebayes** [facebook/react#4078]
After many hours of contortions, I've been able to get React components under test in a headless nodejs + mocha environment using Domino JS as a fake DOM implementation. We have about 550 component tests that run in about 30 seconds (the first time).

Unfortunately, using the `mocha --watch` command leaks a large number of Elements (~13k) and about 120MB of memory with each test run. After digging through heap dumps, I've found the elements hiding in the [nodeCache](https://github.com/facebook/react/blob/master/src/renderers/dom/client/ReactMount.js#L40) variable in the ReactMount file.

We are definitely calling `unmountComponentAtNode(component, elementContext)` for every outer component that we render with `renderComponent` and receiving a boolean `true` response.

I added a `purgeAll()` method to my local build that simply resets this cache and this cut about 100MB of the memory loss. There are a number of other global caches hiding in a handful of other modules (include ReactMount). The proposal is that all of these should be reset from some global utility method like:

``` javascript
React.addons.TestUtils.purgeCaches();
```

If this seems like a change that would be approved, I'd be happy to put together a pull request.

**[Update 6/11/2015]**

For server side rendering environments, it might be better for this to exist in the real API, not TestUtils.

``` javascript
React.purgeCaches();
```

**Comment by lukebayes** [comment]
This request represents a superset of Issue 3557.

**Comment by zpao** [comment]
Your specific issue with unmounting… that doesn't seem right. Purging cached nodes is a big part of the point of unmounting. Perhaps we have a bug there.

**Comment by lukebayes** [comment]
Even if there is a concrete issue with unmount not purging, I would still very much appreciate a single point of entry that reliably destroys/resets all global caches that React modules introduce and hold.

This would certainly benefit test environments immediately, but would also allow server-side rendering to be supported with more confidence.

Ideally, the framework wouldn't create hidden, global state at all, but if it does, it should either provide hooks to clear it, or initialization parameters for clients to provide it.

**Comment by gaearon** [comment]
That particular cache doesn't exist anymore in React 16. If you find others let us know :-)
