### ISSUE TITLE
React.cloneElement uses deprecated element.type

### ISSUE THREAD

**Issue by mathieumg** [facebook/react#4082]
The following call:

```js
// ...
render: function() {
  return React.cloneElement(MyComponent);
}
// ...
```

Complains with a deprecation warning: `Warning: MyComponent.type is deprecated. Use MyComponent directly to access the class.`

This seems to come from https://github.com/facebook/react/blob/0.13-stable/src/classic/element/ReactElement.js#L276 (I'm using React 0.13.3)

It doesn't happen anymore if I change that line to `element`. Can you confirm this is an issue and I didn't miss something? If so, I'd be glad to submit a PR if you want.

**Comment by vsiao** [comment]
`cloneElement` takes a `ReactElement`. You're passing `MyComponent`, which is a component class. `React.createElement(MyComponent)` creates an element with type `MyComponent`.

```js
React.cloneElement(React.createElement(MyComponent))
```
would not trigger any warnings, for example.

**Comment by mathieumg** [comment]
Ok so that means I just had to do 

```js
// ...
render: function() {
  return React.cloneElement(<MyComponent />);
}
// ...
```

This was not clear to me from the docs and made less sense since we can already pass props in as the second argument. Thank you for the quick reply.

**Comment by lalan666** [comment]
thats my fucking face peace ofr shet

**Comment by spicyj** [comment]
@mathieumg Not sure what you're doing, but you probably just want `return <MyComponent />;`.

**Comment by mathieumg** [comment]
@spicyj I need to have access to some instance methods on `MyComponent`, I imagine simply wrapping as you suggest would not accomplish that? (Maybe my current approach doesn't either, haven't gotten around to test it just yet)

Also, thank you for deleting that spam comment, I had never seen that before on GitHub...

**Comment by spicyj** [comment]
`<MyComponent />` and `React.cloneElement(<MyComponent />)` are basically equivalent. You can't access instance methods on a component without mounting it, after which you can use instance methods via a `ref`.

**Comment by mathieumg** [comment]
I'm adding an extra property to `MyComponent`: 

```js
var MyWrapperComponent = React.createClass({
  render: function() {
    return React.cloneElement(<MyComponent extraProp={/* ... */} />);
  }
});
```

So, you're saying the following wouldn't be possible to do?

```js
// ...
componentDidMount: function() {
  this.refs.myref.someMethodThatBelongsToMyComponent();
},

render: function() {
  return <MyWrapperComponent ref="myref" />;
}
// ...
```

**Comment by zpao** [comment]
It would still work without the cloneElement call. cloneElement takes an existing element and creates a copy (useful for modifying elements passed to your component). `React.cloneElement(<MyComponent extraProp={/* ... */} />)` creates a new element (that's what the JSX does) and then immediately creates a copy.

**Comment by mathieumg** [comment]
I just tried it and it doesn't seem to work, as I suspected. To clarify my example above, the method `someMethodThatBelongsToMyComponent` is defined in `MyComponent` but it is **not** defined in `MyWrapperComponent`.

To recap, I imagine it isn't possible for a component to wrap another and "inherit" its methods, unless that is done explicitly "top-down" through props? Thank you.

**Comment by spicyj** [comment]
You could try

```
var MyWrapperComponent = React.createClass({
  getWrapped: function() {
    return this.refs.inner;
  },
  render: function() {
    return <MyComponent ref="inner" extraProp={/* ... */} />;
  }
});
```

then `this.refs.myref.getWrapped().foo()`. Not sure if that works for your case.

**Comment by mathieumg** [comment]
I imagine this would work, but it wouldn't be as "transparent" a wrapper as I had first hoped.

i.e. It wouldn't be possible to replace

```js
// ...
componentDidMount: function() {
  this.refs.myref.someMethodThatBelongsToMyComponent();
},

render: function() {
  return <MyWrapperComponent ref="myref" />;
}
// ...
```

with

```js
// ...
componentDidMount: function() {
  this.refs.myref.someMethodThatBelongsToMyComponent();
},

render: function() {
  return <MyComponent ref="myref" extraProp={/* ... */} />;
}
// ...
```

In other words, using `MyWrapperComponent` as a drop-in replacement for `MyComponent`.

Thanks for the tips!
