### ISSUE TITLE
TestsUtils.simulate.change on a select doesn't work

### ISSUE THREAD

**Issue by Philmod** [facebook/react#4083]
Hey guys,

I've been trying to simulate a `<select>` change but the value doesn't change.

**Component**: 
```
<select className='birthyear' ref='birthyear'
    onChange={this._onUpdate}>
    <option value=''>Year</option>
    {years.map(function(year, i){
        return <option
            key={i}
            value={year}>{year}
            </option>;
    })}
</select>
```

**Test**: 
```
var form = ...
var yearInput = TestUtils.scryRenderedDOMComponentsWithTag(form, 'select')[0].getDOMNode();
TestUtils.Simulate.change(yearInput, {target: {value: 1990}});
```
But the value of the `<select>` is not updated (`this.refs.birthyear.getDOMNode().value`).

Anything I'm missing?

Thanks a ton

**Comment by aackerman** [comment]
The change is simulated, your callback will get called and you can make assertions on that, I don't believe it is intended to change values in the DOM.

**Comment by Philmod** [comment]
Gotcha, thank you.
