### ISSUE TITLE
Setting select value to null or undefined does not change to placeholder-like option

### ISSUE THREAD

**Issue by blainekasten** [facebook/react#4085]
Maybe this is just an ugly pattern of the web, but it's pretty typical to have the first option of a select be a sort of placeholder like item.

```html
<select>
  <option value=''>Select a thing</option>
  ....more options
</select>
```

When implemented with react, I would expect if i set the prop `value` of the select to `null || undefined` it would change to the placeholder-like option. But it seems you have to pass an empty string value to pull it off. I'm not sure if this is something React *should* mask/handle or not. It seems more like an oddity of the browser.. So I am suggesting one of two things:

1. Have `null || undefined` value props choose an empty value option.
2. `invariant` warn passing `null || undefined` is non-effective.

[jsbin example](http://react.jsbin.com/soqilabobe/1/edit?js,output)

**Comment by spicyj** [comment]
Intended. null/undefined aren't the same as the empty string so if you want to select the value with `value=""`, that's what you should pass.

We interpret `<select value={null}>` to mean an uncontrolled component (similar to #2533).

**Comment by blainekasten** [comment]
That seems reasonable. I think we should through an `invariant` then when props is `null || undefined` and an `onChange` is specified. Seeing how many people it affected in your referenced issue, and how much time I wasted trying to figure out what was happening, it would be nice if we were warned in these situations.

**Comment by spicyj** [comment]
@blainekasten Interesting idea. Unfortunately it's fairly common to have an uncontrolled component but also listen to onChange so I don't know if that can work.

**Comment by blainekasten** [comment]
@spicyj hmm. I guess I can think of situations where that might happen.

So, if interested, I think I have an idea. We could get really crazy and have the jsx parser do lookahead things to flag react with information to help debug further.

ie, lookahead parser could do this:
```js
// this
<input value={this.state.something} onChange{ ... } />
// to this
React.createElement("input", {value: ..., onChange: ..., __controlled: true}, ....)
```

Then react could be able to throw up additional warnings for `__controlled` inputs based on things. like `null || undefined` values.

This would only happen in the dev mode only also.

**Comment by blainekasten** [comment]
We could move this to a discussion idea in react-future too if ya'll think it's worth discussing.

**Comment by spicyj** [comment]
We don't want to add DOM-specific logic into the JSX transform. It's more likely that we'd split out `ControlledInput` and `UncontrolledInput` into separate components which would also solve the problem, but honestly this probably isn't tripping up enough people for it to be worth making that change for us now.

**Comment by tkrotoff** [comment]
If someone pass by, here what I do to have a select "placeholder":

```JSX
<select name="month"
        value={this.props.month ? this.props.month : '0'}
        onChange={handleChange}>
  <option value="0" disabled>Month</option>
  <option value="1">Jan</option>
  <option value="2">Feb</option>
  <option value="3">Mar</option>
  <option value="4">Apr</option>
  <option value="5">May</option>
  <option value="6">Jun</option>
  <option value="7">Jul</option>
  <option value="8">Aug</option>
  <option value="9">Sep</option>
  <option value="10">Oct</option>
  <option value="11">Nov</option>
  <option value="12">Dec</option>
</select>
```

If `month` is `null` or `undefined` => `value` is `'0'`.

Visually:

![screen shot 2016-11-25 at 17 07 28](https://cloud.githubusercontent.com/assets/643434/20630572/ed8c39b6-b331-11e6-8ebb-2d23d0594ae1.png)

![screen shot 2016-11-25 at 17 07 40](https://cloud.githubusercontent.com/assets/643434/20630573/f0cfaa0e-b331-11e6-97e6-c35fc6296680.png)

Since `Month` is `disabled`, the user cannot select it. If you don't want `Month` to be displayed in the list, used [the `hidden` attribute](http://stackoverflow.com/a/8442831/990356) (works perfectly under Chrome 54 and Firefox 47; not/partially under IE 11, Edge 38 and Safari 10).

**Comment by mahadehassan34** [comment]
05 10 1995
