### ISSUE TITLE
Html accesskey does not cause control to be focus

### ISSUE THREAD

**Issue by jannavarro** [facebook/react#4099]
Usually when providing accelerator keys for html the accesskey attribute is added to a label. I tried this in react with the code below but the control does not get focused. The expected result is that pressing Alt+N will focus the control. It is working in plain html see jsfiddle [here](http://jsfiddle.net/ovuj1dp0/)

    var HelloMessage = React.createClass({
      render: function() {
      return (
      <div>
      <label for="fName" accesskey="n">First <u>N</u>ame:</label>
      <input id="fName" type="text"/>
      </div>);
      }
    });

    React.render(<HelloMessage/>, mountNode);

**Comment by spicyj** [comment]
Try `accessKey`: http://react.jsbin.com/bucuxiguli/1/edit. You should have seen a warning in your console for this.

**Comment by zpao** [comment]
You'll also want to fix the other warning in the console about using `htmlFor`

**Comment by jannavarro** [comment]
It worked! And I fixed the htmlFor too. It did not show an error though in the chrome dev tool console.

Thanks also for introducing me to react.jsbin.
