### ISSUE TITLE
Doc: should we use envify with React or not?

### ISSUE THREAD

**Issue by slorber** [facebook/react#4107]
This commit removed a note to Envify in the documentation:
https://github.com/facebook/react/commit/39ac88595d0d89beb89ffd598d4a6de1f3b3fee8

Related to PR: https://github.com/facebook/react/pull/1793

As far as I understand, the devDependency of Envify for React is used to produce the distributable files react.js and react.min.js.
It seems to be used here: https://github.com/facebook/react/blob/master/grunt/config/browserify.js

But when using React with Browserify or Webpack, I suppose Envify is not run so it seems to me we should rather use Envify in this case.

Am I right? If yes it would be probably a good idea to document this.

**Comment by slorber** [comment]
It seems someone agree with me:

ReactifluxSlack> <morhaus> Sebastien-L if you use browserify to bundle your app, you'll still need envify to expose process.env.NODE_ENV to your bundle
<ReactifluxSlack> <morhaus> With webpack you'd use DefinePlugin
<ReactifluxSlack> <morhaus> If you just include react.js in your html then switching to react.min.js in prod is fine

**Comment by slorber** [comment]
So according to my tests it seems we do not need to use Envify with React as it seems already configured.

```
  "dependencies": {
    "envify": "^3.0.0"
  },
  "browserify": {
    "transform": [
      "envify"
    ]
  },
```

So it seems simply using NODE_ENV=production with browserify will actually envify React correctly.


Exemple gulp config:

```
    var b = browserify();
    b.require("react");
    b.bundle()
        .pipe(source('appReact.js'))
        .pipe(gulp.dest('./build'));
```
With command: `NODE_ENV=test gulp browserify-react`

This will produce automatically a file which contains `if ("production" !== "test")` etc...

This means that we just have to use a dead-code elimination tool like Uglify or GCC.


I think this is not clearly documented

**Comment by zpao** [comment]
Yup, the browser field will get used by browserify automatically, so envify will work. AFAIK there is no equivalent for webpack.

FWIW, envify + uglify is exactly how we build our minified builds.

Any suggestions (or PRs :wink:) on clarifying the documentation would be appreciated!

**Comment by slorber** [comment]
glad to know thanks

**Comment by laskos** [comment]
> AFAIK there is no equivalent for webpack.

@zpao 
https://www.npmjs.com/package/envify-loader <- this should work fine

**Comment by syranide** [comment]
```
new webpack.DefinePlugin({'process.env.NODE_ENV': JSON.stringify('production')});
```

Is all you need for webpack.

**Comment by zpao** [comment]
Going to close this out. I haven't seen this come up recently but we'll definitely plan to do a clearer job explaining usage like this when we do a revamp of docs.
