### ISSUE TITLE
question: when using es-next modules, should i need to import a var named 'React' for JSX even when not explicitly referenced?

### ISSUE THREAD

**Issue by tony-kerz** [facebook/react#4110]
i happened to use the destructuring syntax on import for grabbing a ref to `React.Component` like so:
```
import {Component} from 'react'
//...
class CommentBox extends Component { 
//...
  render() {
    return (
      <div className='commentBox'>
        <h1>Comments</h1>
        <CommentList data={this.state.data}/>
        <CommentForm onCommentSubmit={this.handleCommentSubmit}/>
      </div>
    )
  }
}
```
but the resultant code transpiled via babel v5.5.6 contains a reference to a variable named `React` which ends up being undefined:
```
Uncaught ReferenceError: React is not defined
```
it seems to me that the JSX transpiler should be responsible for setting up variables that are only internally referenced, but i wanted to ask the question...

best,
tony.

**Comment by syranide** [comment]
```
import React, {Component} from 'react'
```

> it seems to me that the JSX transpiler should be responsible for setting up variables that are only internally referenced, but i wanted to ask the question...

JSX doesn't know how React is made available in your environment, even if it did it would not be a good idea for various reasons.

Also this is probably best brought up in the babel repository (but I would expect a similar answer until there's a good plan for how to make elements work independently from React).

**Comment by tony-kerz** [comment]
@syranide kk, so i'm understanding that the current thinking is: 

> it is the developer's responsibility to 'make React available' for the resultant transpiled JSX in a variable named `React`.

i didn't catch this in the docs, do you know if this is explicitly stated somewhere?

**Comment by iamdustan** [comment]
No idea if it’s explicitly stated in the docs. (And I am the #lazyweb so I’m not looking). The catch is that JSX is just sugar for `React.createElement` which requires `React` to be in scope. There is a bit of indirection there. I don’t personally have any opinion on whether that should be documented better or not.
