### ISSUE TITLE
npm install react fails w/ "invalid name"

### ISSUE THREAD

**Issue by ajfarkas** [facebook/react#4111]
Trying to `npm install react` to use with Browserify,  but I'm getting an error:

`Invalid name: "learn react"`

I've got react-tools installed globally already. Is this a problem with the package, or can I do something different on my end?

npm-debug.log:
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'react' ]
2 info using npm@2.11.0
3 info using node@v1.6.2
4 verbose install initial load of /Users/ajfarkas/Sites/Learning/react/package.json
5 verbose stack Error: Invalid name: "learn react"
5 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:326:15)
5 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:209:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:284:20
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (evalmachine.<anonymous>:302:5)
6 verbose cwd /Users/ajfarkas/Sites/Learning/react
7 error Darwin 13.4.0
8 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "react"
9 error node v1.6.2
10 error npm  v2.11.0
11 error Invalid name: "learn react"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
````

**Comment by zpao** [comment]
Does your own package.json have "learn react" as its name? We don't use that anywhere.

**Comment by ajfarkas** [comment]
it does not. I'm using `npm install react --save`. Should I just add
`"react": "*"` to dependencies? Though I think it should work from CL.

**Comment by zpao** [comment]
So the only way I can repro this is if a package.json contains `"learn react"` where it's expecting a valid npm package name (which can't contain spaces). This could be in the `name` field or `dependencies`. The error stack you pasted is pointing at something in your directories, not React itself. Perhaps it's something you're not expecting to be read? The best I can suggest is deleting some directories and starting over.

```
4 verbose install initial load of /Users/ajfarkas/Sites/Learning/react/package.json
5 verbose stack Error: Invalid name: "learn react"
```

I'm 100% certain this is not a problem with React itself so I'm going to close out, but I'm happy to keep helping here.

**Comment by acedubs** [comment]
::if it sends w/ ok then fillter up:: https://github.com/techfoobar/grails-cache => https://jsfiddle.net/#tidy
