### ISSUE TITLE
Unclear whether it's legal to read State and Props externally

### ISSUE THREAD

**Issue by dave-bemiller** [facebook/react#4116]
The React API and documentation give some mixed messages about whether or not "state" is safe to read from externally.

In code, you can call "component.state" to figure out what a Component's State is. This is useful in several situations, but it's particularly valuable when writing unit tests.

By javascript convention, I would believe this is a public variable. If I weren't supposed to read from it, I would expect it to be called "_state".

...but in the documentation, it doesn't appear in the Component API, or any of the examples. It's not used in the Jest examples either.

"component.props" is in a very similar situation... although I admit that this one is much less useful, since it doesn't come up as frequently in unit tests.

I can imagine a few ways to make this clearer, depending on the React team's intentions.

If you intend for them to be public:
- Add them to the public Component API
- Use them in some of your official examples

If you don't intend for them to be public:
- Ideally, you could do some trickery with closures inside React.render(), so that the input to React.createClass() can touch these variables, but the object returned by React.render() doesn't expose them.
- Barring that, it'd help if the names started with an underscore, so engineers would know that they're private

**Comment by spicyj** [comment]
They're not public outside the component. We should figure out a solution here though. https://github.com/facebook/react-native/issues/1521 is also related.
