### ISSUE TITLE
"Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`"

### ISSUE THREAD

**Issue by SamyPesse** [facebook/react#4120]
I'm trying to display a dropdown menu composed of `ul`, `li` and `a` (similar to the one from bootstrap).
A `PluginList` element is used to generate a dropdown menu from a store.

But the browser is not correctly parsing/outputting the HTML. Everytime I click on an item, I got the error: `Uncaught Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0.0.0.7.1.$=15:0.0`.

This bug is probably related to #1400, but I can't find any solution :sweat:

I'using react 0.13.3 and I also tested with the latest master.

#### HTML DOM View:

![screen shot 2015-06-13 at 11 35 21](https://cloud.githubusercontent.com/assets/845425/8143839/d84c96cc-11c0-11e5-97b9-e8dd72c224c9.png)

#### View of the same tree in the React plugin for Chrome:

![screen shot 2015-06-13 at 11 34 37](https://cloud.githubusercontent.com/assets/845425/8143840/e1eb3184-11c0-11e5-9f85-1f762aa42f74.png)

#### Screenshot of the result

The blue element has nothing to do here

![screen shot 2015-06-13 at 11 34 58](https://cloud.githubusercontent.com/assets/845425/8143838/d8317c70-11c0-11e5-8429-f3380068a737.png)

**Comment by SamyPesse** [comment]
Use `React.renderToString` in `PluginList` returns the valid string:

```
<ul class="dropdown-menu" data-reactid=".2" data-react-checksum="868905626"><li data-reactid=".2.0:$test"><a href="#" data-reactid=".2.0:$test.0"><span data-reactid=".2.0:$test.0.$=10:0">test</span><span data-reactid=".2.0:$test.0.$=11:0"> </span><span class="help-label" data-reactid=".2.0:$test.0.$=12:0">1.0.0</span></a></li><li data-reactid=".2.0:$exercises"><a href="#" data-reactid=".2.0:$exercises.0"><span data-reactid=".2.0:$exercises.0.$=10:0">exercises</span><span data-reactid=".2.0:$exercises.0.$=11:0"> </span><span class="help-label" data-reactid=".2.0:$exercises.0.$=12:0">*</span></a></li><li class="divider" data-reactid=".2.0:$divider"></li><li data-reactid=".2.1"><a href="#" data-reactid=".2.1.0"><i class="octicon octicon-plus" data-reactid=".2.1.0.$=10:0"></i><span data-reactid=".2.1.0.$=11:0"> Add Plugin</span></a></li><li data-reactid=".2.2"><a href="#" data-reactid=".2.2.0"><i class="octicon octicon-trashcan" data-reactid=".2.2.0.$=10:0"></i><span data-reactid=".2.2.0.$=11:0"> Remove Plugin</span></a></li><li data-reactid=".2.3"><a href="#" data-reactid=".2.3.0"><i class="octicon octicon-package" data-reactid=".2.3.0.$=10:0"></i><span data-reactid=".2.3.0.$=11:0"> Find Plugins</span></a></li></ul>
```

**Comment by SamyPesse** [comment]
It looks like the error is happening when I'm using `PluginsList` inside `DropdownItem`,

### This works

```jsx
<div>
    <PluginsList></PluginsList>
</div>
```

### This doesn't work

```
<Button.DropdownItem>
    <i className="octicon octicon-package"></i> Plugins
    <PluginsList></PluginsList>
</Button.DropdownItem>
```


`DropdownItem` is defined by:

```js
var DropdownItem = React.createClass({
    onClick: function(e) {
        e.preventDefault();
        e.stopPropagation();
        if (this.props.onClick) this.props.onClick();
    },

    isMenu: function(child) {
        return child.type && child.type.displayName == 'DropdownMenu';
    },

    render: function() {
        if (this.props.divider) return <li className="divider"></li>;

        var inner = [], outer = [];

        inner = React.Children.map(this.props.children, function(child) {
            if (!this.isMenu(child)) return child;
            return null;
        }, this);

        outer = React.Children.map(this.props.children, function(child) {
            if (this.isMenu(child)) return child;
            return null;
        }, this);

        return <li>
            <a href="#" onClick={this.onClick}>{inner}</a>
            {outer}
        </li>
    }
});
```

**Comment by zpao** [comment]
Looking at the HTML view, the data-reactid in question is used on 2 `<a>` tags. Usually this is the result of the browser reorganizing nodes, specifically nested `<a>`s.

```html
<a id="1">
  <a id="2">foo</a>
</a>
```

Will always get moved in the DOM to be 

```html
<a id="1"></a>
<a id="2">foo</a>
```

That's the likely culprit for your case. Chances are you have nested anchors across components. `DropdownItem` definitely has one. If anything rendered inside there has an anchor (I guess `PluginsList` or one of its children), then this will happen. When it does happen, React's idea of the DOM and the real DOM get out of sync, and then you hit this problem.

Though your problem might actually be manifesting slightly differently (could be the DOM structure playing different tricks) but you definitely have nested anchors.

**Comment by SamyPesse** [comment]
Thanks @zpao :beers: 

It was a stupid mistake on my side: The filtering done in `DropdownItem` to ensure that sub-menus are added to `li` instead of `li > a` didn't work since the child type was `PluginsList` instead of `DropdownMenu`, I was convinced that React rendered children before calling the render method of the parent.

**Comment by spicyj** [comment]
React will warn for invalid nesting like this in the next release.

**Comment by SamyPesse** [comment]
@spicyj I saw a comment about this on another issue, but when I tested using the latest master I didn't get any warning about invalid nesting.

**Comment by mdcsfk** [comment]
What if i need this kind of nesting? 
<a>
  <div>
    <a></a>
  </div>
</a>

How could I avoid this error?

**Comment by jimfb** [comment]
@mdcsfk That kind of nesting will not trigger this error.

**Comment by spicyj** [comment]
@jimfb Yes it will; you can't have two nested anchor tags in HTML.

@mdcsfk You will need to restructure your markup. You can't have that kind of nesting in HTML, whether or not you're using React. Usually you'll want to change one of the links to not be an actual link and you can add a click handler to it.

**Comment by jimfb** [comment]
Oh, right, because the dom will rewrite the anchors.  You're right.
