### ISSUE TITLE
release 0.14

### ISSUE THREAD

**Issue by zpao** [facebook/react#4135]
We're still a little ways away from this but starting the list before we lose track. This is less big picture like #3220 and more about the longer tail of work.

## Misc 
- [x] Remove react-tools, JSXTransformer mentions from docs
- [x] Update react-tutorial repo to use babel/browser
- [ ] Polish readme for react, react-dom
- [x] Update fb.me scripts to exclude JSXTransformer
- [x] Update to node v4 for development (will be better moving forward with stable branch maintenance)
- [x] Update cdnjs, jsdelivr autoupdaters to account for #4901

## Documentation Changes
- [x] Updates for refs, stateless function components (#4964)
- [x] Update for desired API usage (eg `React.render()` → `ReactDOM.render()`) (https://github.com/facebook/react/pull/5055)

## Final Steps
- [x] create `0.14-stable` branch
- [x] shrinkwrap
- [x] actually publish to all the places
- [x] update jsfiddles
  - [x] base
  - [x] thinking in react
- [x] Update changelog.md
- [x] make sure master branch has all documentation changes made in 0.14-stable
- [x] update react-tutorial repo with final changes

**Comment by activatedgeek** [comment]
Why are react-tools being removed?  Is the JSXTransformer being deprecated or something?

**Comment by JohnyDays** [comment]
@activatedgeek Yes, in favor of babel

**Comment by activatedgeek** [comment]
Ohh, I'm using a `webpack` build system. Will I just need to change the loader to `babel` ?

**Comment by Dashed** [comment]
@activatedgeek yeah. should be painless. https://github.com/babel/babel-loader

**Comment by activatedgeek** [comment]
Great! Thanks!

**Comment by tsingson** [comment]
+1

**Comment by spicyj** [comment]
@activatedgeek See this blog post from last week: http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html.

**Comment by majorye** [comment]
+1

**Comment by dcousens** [comment]
Is there any other status updates or burn down for this?

**Comment by zpao** [comment]
https://github.com/facebook/react/milestones/0.14 is what I've been looking at. We don't have issues for updating docs.

**Comment by dcousens** [comment]
@zpao is this issue a double up of https://github.com/facebook/react/issues/3220?  Or?

**Comment by zpao** [comment]
From the description:

> This is less big picture like #3220 and more about the longer tail of work.

**Comment by dcousens** [comment]
*facepalm*

Sorry, thanks.

**Comment by blixt** [comment]
Good morning! Are there tasks left for the React 0.14 release that external developers could pick up and help on, or is the remaining work on 0.14 all documentation / release stuff?

**Comment by zpao** [comment]
I think at this point we just have some docs and the final release steps. Thanks for the offer though! Feel free to jump into anything else you find.

**Comment by iamdustan** [comment]
Having been using 0.14 since the beta, updating packages for ReactDOM.render, removing react 0.13 peerDeps, and react/addons have been the biggest pain points I’ve experienced.

@blixt opening PRs to any react components or tooling that you use or see to help the community move forwards would be superbly helpful.

**Comment by dcousens** [comment]
@iamdustan what replaced `react/addons`?

**Comment by zpao** [comment]
`react-addons-specific-package`. It's not mentioned super loudly in http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html, but it's there.

**Comment by iamdustan** [comment]
Each addon is its own package. Technically I think for 0.14 it's still bundled for a deprecation cycle.
