### ISSUE TITLE
IIFE mention in "If-Else in JSX"?

### ISSUE THREAD

**Issue by lukehorvat** [facebook/react#4141]
The `If-Else in JSX` page only offers up ternary expressions as a solution to conditional logic inside JSX. But perhaps IIFEs should also get a mention?

Realizing I could do IIFEs inside JSX helped "flesh out" my mental model of how JSX actually works, so I suspect it would aide others in the same way as well. Furthermore, with the advent of ES6 arrow functions, they aren't too verbose either.

A code example utilizing an IIFE might be overkill, but at least a passing mention would be nice.

**Comment by zpao** [comment]
Sure, would you be interested in writing something up?

**Comment by lukehorvat** [comment]
No problem. With or without code example?

**Comment by zpao** [comment]
A code example might be useful (and would hopefully help prevent followup questions where people will surely have a problem with using `this`)

**Comment by syranide** [comment]
Related reactjs/react-future/issues/35
