### ISSUE TITLE
Data attributes with no value, not same as regular attribute with no value

### ISSUE THREAD

**Issue by IsurusPrime** [facebook/react#4146]
This is not the same issue in React where one is looking for a native HTML attribute with no value - in those cases, passing no value is valid.

With my experimentation, data-attributes can't be applied without a value - if you try this

    return (<table data-tablesaw-minimap> ... </table> )
you will get this

    <table data-tablesaw-minimap="true">...</table>

I am attempting to use the tablesaw jquery plugin, and the data-attributes require them to be without values, or, they will not function properly.

It would be great if data-attributes could be applied without values, thanks!

**Comment by zpao** [comment]
Value-less attributes are a shortcut for boolean attributes. It's not my favorite part of the JSX transform but it exists. You should be able to specify an empty string `<table data-tablesaw-minimap="">...</table>`, which will ensure the value React gets is an empty string. That should end up in the DOM correctly without a value.

**Comment by spicyj** [comment]
Oh, good point @zpao. Somehow I forgot that.

**Comment by IsurusPrime** [comment]
Thanks, that worked like a charm.
