### ISSUE TITLE
Form created with React.createClass doesn't work with onSubmit

### ISSUE THREAD

**Issue by sambev** [facebook/react#4149]
I am working on a project that is not using jsx. When I make a form with React.createClass, the onSubmit attribute doesn't seem to be working like it does with jsx.

https://jsfiddle.net/wntgpwcx/4/

Do I need to set up onSubmit differently if I am not using jsx?

**Comment by zpao** [comment]
Use lowercase strings when calling createElement (we use the type to set up some special event handlers for forms, including submit).
