### ISSUE TITLE
Support Stateful Test Renderer

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#4153]
The plan is to move unnecessary state out of the production renderer. Therefore there will be no public API to introspect the current state of the tree. I.e. no `_renderedChildren`, props inspection etc.

The React DevTools will maintain its own shadow tree for introspection / reflection purposes.

However, this also means that if you use `React.render` to run deeply rendered unit tests, you will no longer be able to use various reflective APIs to inspect the state of the current React tree. Such as `ReactTestUtils.findAllInRenderedTree`, the legacy `reactComponentExpect` utils etc.

Our recommended unit testing solution is shallow testing.

However, it would be possible to create a new renderer that keeps track of the whole React tree, including props, and therefore reenables stateful unit testing. That might be a helpful upgrade path. E.g. something like `ReactTestUtils.render` which would have a forked version of the primary renderer.

See #4151

cc @spicyj , @dataminr

**Comment by gaearon** [comment]
I think we can close this. Overall we don't recommend either shallow rendering or deep introspection anymore. Instead, we recommend end-to-endy tests that assert on the observable DOM tree. Eg. React Testing Library. But there's still some use case here that would be addressed by the Test Selectors ongoing work.
