### ISSUE TITLE
Sub Components don't always render 

### ISSUE THREAD

**Issue by reduxdj** [facebook/react#4178]
In this Campaigns component, CampaignForm won't render inside Sidebar, only if it's outside of Sidebar tag does it render (cjsx example). If I put it directly inside the Sidebar render's function it renders fine. But, this breaks the whole idea of loosely coupling my sidebar so it's more abstract.

Fails to render CampaignForm:
```
Campaigns = React.createClass(
  render: ->
    <div className="campaigns">
      <Sidebar><CampaignForm/></Sidebar>
      <h1>Campaigns</h1>
    </div>
)
```

Render's CampaignForm fine:
```
Campaigns = React.createClass(
  render: ->
    <div className="campaigns">
      <Sidebar></Sidebar>
      <h1>Campaigns</h1>
     <CampaignForm/>
    </div>
)
```

**Comment by zpao** [comment]
What does Sidebar look like? Does it understand what to do with children?

**Comment by reduxdj** [comment]
class Sidebar extends React.Component
      render: ->
        <div className="sidebar"></div>
    module.exports = Sidebar

OK, am I missing something then?

**Comment by zpao** [comment]
```
class Sidebar extends React.Component
  render: ->
    <div className="sidebar">{this.props.children}</div>
```

`this.props.children` is a special prop created from the children. Read more: http://facebook.github.io/react/docs/multiple-components.html#children
