### ISSUE TITLE
Event handler not bound correctly with babeljs

### ISSUE THREAD

**Issue by ricogallo** [facebook/react#4187]
Hi, I've found that if I inspect `this` inside a event handler using the ES2015 syntax /w babeljs, using their jsx embeeded parser, I get undefined. Here is a fiddle to reproduce the problem: http://jsbin.com/kesebenoja/edit?html,console,output . Not sure if I should post this issue also to the babeljs guys.

Thanks

**Comment by fkling** [comment]
Can you please post an example of your original code? It's more likely that you are doing something wrong...

**Comment by fkling** [comment]
Nvm, it looks like you are doing something like

```
class Foo extends React.Component {
    render() {
       return <form onSubmit={this.handle} />;
    }
}
```
With ES6 classes, React does not auto-bind methods anymore, you have to do that yourself.  See https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding

**Comment by ricogallo** [comment]
Ok, I actually had fixed it my self using `Function.prototype.bind`, didn't know about that doc :( .
Thanks!

**Comment by ezequiellagos** [comment]
Good event={myFunction}
