### ISSUE TITLE
Make React run without es5-sham

### ISSUE THREAD

**Issue by dantman** [facebook/react#4189]
I'm ok with React requiring shims. I'd include them whether React needed them or not. However I don't believe React should require es5-sham to work. Because, among other reasons, including shams has the potential to break other libraries on the same page and hence doesn't sound like a good practice for one library to demand.

Of the two shams React says it requires (in the 0.14 code in npm) each one is only used once in the entire codebase.

2 function invocations doesn't sound like a good reason for requiring a 5kb library that has potential side effects.

The best practice for React would probably be to provide its own small module providing either the native function or an internal sham.

This would also be a positive. As these internal shams wouldn't have to waste bytes trying to sham functionality that React doesn't need. And they could emit invariant warnings when misused during development instead of failing (potentially silently) the way they would in es5-sham.

**Comment by dantman** [comment]
I'm trying out implementing this myself. And I'm discovering some interesting quirks and possibilities.

----

Firstly, in ES5 Object.freeze throws if given a non-object, in ES6 it returns it.

Which means on one dev's machine in a browser implementing ES6 `Object.freeze` could run fine over quirky code that accidentally calls `Object.freeze` on a primitive. And then fail spectacularly in production in a browser that implements ES5.

Which makes the React freeze stub a good place to even out the behaviour. Because calling `freeze` on a non-object in React code is most likely a mistake I've opted to throw the TypeError.

----

Secondly, every place in code that uses `Object.freeze` does it in development only.

Would it be good or unexpected to make React's internal freeze only run in dev?

----

Last is a question. Do we want `freeze` to display a warning during development that freeze is not implemented?

**Comment by syranide** [comment]
:+1: I'd love this too, es5-sham doesn't interop very neatly with all libraries so I've ended up in weird situations where I (luckily) could include certain libraries before es5-sham and others after and have it sorted out that way. But I would really like not to have to use es5-sham at all.

**Comment by demohi** [comment]
:+1:

**Comment by Passerby** [comment]
:+1:

**Comment by jimfb** [comment]
To summarize the discussions in https://github.com/facebook/react/pull/4192 : it sounds like the ideal solution is a transform but we would happily accept inlining the ifexists check for `freeze` and es6 classes instead of `create`.  See https://github.com/facebook/react/pull/4192 for relevant discussions.

**Comment by dgreensp** [comment]
I submitted a fresh PR for review: #4959 

The changes are very small and straightforward.
