### ISSUE TITLE
Do not change cursor position in input fields

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#4191]
This bug happens on the latest FF only, regardless of the platform.

There is this code:

```js
	      React.createElement('input', _extends({
	        ref: this.props.id,
	        className: 'passwordField__input',
	        type: this.state.isPassword ? 'password' : 'text',
	        value: this.state.value,
	        style: this.state.isPassword ? null : this.unMaskStyle,
	        onChange: this.handleChange
	      }, props)),
```

When you type something, then change the type in the middle, then the cursor position changes, goes back to the beginning. But it shouldn't.

**Comment by spicyj** [comment]
Can you post a simple jsbin (or similar) repro?

**Comment by binarykitchen** [comment]
here you go
http://jsbin.com/keleru/edit?html,js,console,output

just type in the password field and see, the cursor position behaves weird when the `type` gets switched

**Comment by spicyj** [comment]
Looks like Firefox re-initializes the input completely when you change the type, which makes intuitive sense to me. If you want to maintain the cursor position it's probably best to manage selectionStart/selectionEnd yourself. Maybe one day we'll have a better API to manage this from React (https://github.com/reactjs/react-future/issues/4) but not right now, sorry.

(As a side note, your component isn't actually controlled like you might believe it is – starting value as an empty string and handling the change is maybe what you meant to do: http://jsbin.com/bedadoxada/1/edit?js,output. Doesn't affect this issue though.)

**Comment by binarykitchen** [comment]
So, it's a Firefox issue then @spicyj?

Sorry, for me, this is not intuitive at all. Switching the type should not alter cursor position. Here is a good use case for this scenario: https://github.com/seethroughtrees/react-ux-password-field, look at https://github.com/seethroughtrees/react-ux-password-field/issues/15

Ignore my jsbin, it was just a quick and dirty hack to demonstrate it. No need to make it perfect ;)

**Comment by spicyj** [comment]
Yes, if you feel that changing type should not move the cursor then opening a Firefox issue sounds reasonable. I'm fairly sure you'll find that the same problem exists without React.

(Personally, I'm not convinced that "preserving cursor position" can even make sense. Sure, text and password look mostly similar, but for other types of inputs there's no cursor to preserve. Or for a date picker you might have multiple cursors for each part of the date.)

**Comment by binarykitchen** [comment]
Yeah, between the types text and password I'd maintain cursor position. For all others resetting it makes sense.

https://bugzilla.mozilla.org/show_bug.cgi?id=1176764
