### ISSUE TITLE
Factory.type is deprecated. Access the class directly before passing it to createFactory

### ISSUE THREAD

**Issue by SystemParadox** [facebook/react#4193]
I am getting this warning but unable to work out why. I cannot find any documentation or other explanations for this error. What does it mean?

What are the likely causes of this?

Thanks.

**Comment by SystemParadox** [comment]
Stupid V8 was messing up the stack again :(

This is being caused by one of my components checking `React.isElementOfType`. What is the recommended alternative to this? The component needs to know the type of its children (it's a compatible replacement for a `<table>`).

**Comment by spicyj** [comment]
Instead of checking `el.type === Foo.type`, check `el.type === Foo`. For isElementOfType, pass `Foo` not `Foo.type`. Let me know if that doesn't make sense.

**Comment by SystemParadox** [comment]
I am, but it appears that `isElementOfType` does `inst.type` internally which causes the warning (`createFactory` adds a getter for `.type`).

I am doing this (currently in `render`, which is a bit of a hack, but I don't think that makes any difference here):

```
React.Children.forEach(this.props.children, function (child) {
    if (React.isElementOfType(child, React.DOM.thead)) {
        // ...
    }
});
```

**Comment by spicyj** [comment]
Just 'thead' not React.DOM.thead.

**Comment by SystemParadox** [comment]
Ah right, because `React.DOM.thead` is a factory.

I also found I was using an old version of `isElementOfType` which was doing `inst.type === convenienceConstructor.type`, rather than `inst.type === convenienceConstructor`.

For the benefit of anyone else reading this, `el.type` usually resolves to the actual class object (the one returned by `React.createClass`), it's a special case for `React.DOM` elements that this is a string.

All sorted now. Thanks @spicyj.

**Comment by spicyj** [comment]
Glad you figured it out.
