### ISSUE TITLE
warn if class has componentDidUnmount method

### ISSUE THREAD

**Issue by oluckyman** [facebook/react#4194]
It would be nice if `componentDidUnmount` would throw a warning to the console that there is no such a lifecycle method.

**Comment by chicoxyzzy** [comment]
why? there is no such method in documentation.

**Comment by oluckyman** [comment]
Just because human beings tend to make mistakes. Especially if it is something that absent in the documentation.
I think this kindly warning is not a big deal but it is in spirit of React library. Today there is 374 results in google by keyword [componentDidUnmount](https://www.google.com/search?&q=%22componentDidUnmount%22). Multiply it by all those people who silently spend 5-10-20 minutes of their life to find that stupid mistake and you get a crowd who can tell you why :)
