### ISSUE TITLE
CloneElement not working as expected

### ISSUE THREAD

**Issue by codeuniquely** [facebook/react#4203]
I have some code that lays out components like a XAML stack Panel that looks for layout properties  and calculates the style based on available width and height it sets the styles properties on contained child elements.

it does all this inside a map and applies the children via cloneElement

    var paddedContainment = this._calculatePaddedContainment(this.props.layout, this.props.style.width, this.props.style.height );

    return React.Children.map(this.props.children, function (child) {
      
      var expandedLayout = this._expandLayout(child.props.layout);
      var size = this._getLayoutContainment(expandedLayout, paddedContainment);
      paddedContainment = this._subtractDockContainment(paddedContainment, size);
      var style = this._getLayoutStyle(this.props.style, expandedLayout, paddedContainment);

      return React.cloneElement(child, { style:style }, other );
    }

What was passed in, is a component that has defined 7 children elements (defined in JSX)

    ReactElement {key: null, ref: "Tabs", _owner: ReactCompositeComponentWrapper, _context: Object, _store: Object}
      _context: Object
      _owner: ReactCompositeComponentWrapper
      _store: Object
        originalProps: Object
        props: Object
        children: Array[7]
          0: ReactElement
          1: ReactElement
          2: ReactElement
          3: ReactElement
          4: ReactElement
          5: ReactElement
          6: ReactElement
          length: 7
          __proto__: Array[0]
          className: ""
          initialIndex: 0
          layout: Object
            height: "*"
            width: "*"
            __proto__: Object
          __proto__: Object
          validated: true
        __proto__: Object
        key: null
        props: (...)
        ref: "Tabs"
        type: (props, context) {
          ...
          displayName: "Tabs"
          length:2
          ...
      __proto__: Object

what it spits out is:

    ReactElement {key: null, ref: "Tabs", _owner: ReactCompositeComponentWrapper, _context: Object, _store: Object}
      _context: Object
      _owner: ReactCompositeComponentWrapper
      _store: Object
        originalProps: Object
        props: Object
        children: Object                                <--- Inserted itself here
          children: ReactElement
          _context: Object
          _owner: ReactCompositeComponentWrapper
          _store: Object
            originalProps: Object
            props: Object
              children: Array[7]
                0: ReactElement
                1: ReactElement
                2: ReactElement
                3: ReactElement
                4: ReactElement
                5: ReactElement
                6: ReactElement
                length: 7
                __proto__: Array[0]              
              className: ""
              initialIndex: 0
              layout: Object
              __proto__: Object
              validated: true
            __proto__: Object
            key: null
            props: (...)
            ref: "Tabs"                                <---- has it's ref
            type: (props, context) {
              ...
              displayName: "Tabs"
              length:2
              ...
            __proto__: Object
            className: ""
          __proto__: Object
          className: ""
          initialIndex: 0
          layout: Object
          style: Object
          __proto__: Object
        validated: false
      __proto__: Object
      key: null
      props: (...)
      ref: "Tabs"                                <---- has it's original ref
      type: (props, context) {
        ...
        displayName: "Tabs"
        length:2
        ...
      __proto__: Object

Note that the component has been cloned (keeping the "ref") but it has then been inserted underneath itself as a single object with that same ref. (The style has been applied)

If you do this using cloneWithProps you get the correct final structure (i.e. a copy of the original) but you lose the "ref" and so the UI no longer works as you can't get at the resultant component methods.

At first I thought that it might have been that the ref was the same as the displayName and causing an issue, but changing either or both of these has no effect and it still insert itself

**Comment by spicyj** [comment]
What is `other` in your code?

**Comment by codeuniquely** [comment]
var {
          layout,
          style,
          ...other
        } = this.props;

**Comment by spicyj** [comment]
cloneElement's params beyond the props arg specifies children, much like createElement (unlike Object.assign/_.extend). Sounds like you probably want

```
React.cloneElement(child, { style:style, ...other })
```

instead.

**Comment by spicyj** [comment]
Er, make that something like

```
_.extend({ style:style }, other)
```

since you probably don't have that ES7 experimental transform.

**Comment by codeuniquely** [comment]
OK so I now do

**Comment by spicyj** [comment]
The former.

**Comment by spicyj** [comment]
Or maybe something like

```
child = React.cloneElement(child, {style: style});
child = React.cloneElement(child, other);
```

if you'd prefer. Up to you.

**Comment by codeuniquely** [comment]
Yes - I tried that (former) and I get the same result - It nests the object that contains the chidren inside itself.

**Comment by codeuniquely** [comment]
if i do it as two calls 

    child = React.cloneElement(child, {style: style});
    child = React.cloneElement(child, other);

then it adds a further level of nesting (so now its clone => clone => original) and the children are now third level deep rather than first level deep

**Comment by spicyj** [comment]
Seems I'm not understanding you properly, sorry. Can you make a small example in react.jsbin.com that shows the problem?

**Comment by codeuniquely** [comment]
OK Sorted... 

Well, stopped the symptoms by also extracting the this.props.children when I declared the spread property ...other. Otherwise one of the properties is passes in is this.props.children. Not sure why that would also cloned the component itself - but once i removed these it behaves as expected without the extra level (cloning its own children - already)

    var {
      children,
      layout,
      style,
      ...other
    } = this.props;

**Comment by spicyj** [comment]
var other = {
  children: Tabs,  // <-- the 
}

**Comment by spicyj** [comment]
Here, `other` contained all of the props of the parent component (except `layout` and `style`), so it looked something like

```
var other = {
  children: <Tabs />, // <-- this is the exact component that you're cloning!
};
```

so you ended up making a copy of `<Tabs />` that set its children to `other.children`, which happened in this case to be the `<Tabs />` element itself, giving you `<Tabs><Tabs /></Tabs>`. This is working as intended. If you don't want to transfer a specific prop, then take it out like you did.

(cloneWithProps wouldn't transfer children as a special case, which was surprising in many cases and one of the reasons we're deprecating it – cloneElement treats all props identically.)

**Comment by codeuniquely** [comment]
good to know
