### ISSUE TITLE
Warning: getInitialState was defined on a plain JavaScript class, even when using React.creatClass

### ISSUE THREAD

**Issue by dmatteo** [facebook/react#4214]
I'm trying to migrate our code base from 0.12.x to 0.13.x

One of the most recurring warnings though seems a bit weird:  
`'Warning: getInitialState was defined on Component, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?'`

This is the actual component, and it's a RequireJS module, as you can see.  
```javascript
define(function(require) {
  'use strict';

  var React = require('react');

  var Component = React.createClass({
    displayName: 'Component',

    getInitialState() {
      return {
        whatever: 'React!'
      };
    },

    render() {
      return <div>Hello {this.state.whatever}</div>
    }
  });

  return Component;
  
})
```

Am I doing something wrong inadvertently?

**Comment by spicyj** [comment]
That code looks fine. Can you post a simple jsbin that reproduces the problem?

**Comment by dmatteo** [comment]
@spicyj shame on me... 
It's actually something that we did in our early days in React messing with `type.prototype.getInitialState` :-1: 

I've killed that and it doesn't throw that warning anymore.

Thanks,
See ya!

**Comment by NickStefan** [comment]
when i directly require react and react dom min, i get this same error, even though we are only using React.createClass:

webpack directly requiring the min versions for our server build
```
externals: [
            {
                react: false,
                'react-dom': false
            },
            /^[a-z\-0-9]+$/
        ],
        resolve: {
            alias: {
                react: pathToReactMin,
                'react-dom': pathToReactDomMin
            }
        },
```

the reason i was wanting to directly require the min versions was #812 https://github.com/facebook/react/issues/812
