### ISSUE TITLE
Sugestion: make Warnings in dev mode output a console.trace

### ISSUE THREAD

**Issue by abritinthebay** [facebook/react#4216]
Seeing something like:

> Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.

Is really useful but... not so much if you don't know where the offending code is. A trace call would *really* help narrow down where in an application the problematic code is.

This would also obliviate the need for the (pointless) try/catch below that needs to be edited to even work (it catches the error it throws).

**Comment by jimfb** [comment]
Hmm... console.trace is non-standard.  We use console.error for warnings, so you can just expand the message to see the trace (in chrome and firefox at least).

Are you using an environment that doesn't let you expand error traces?

**Comment by abritinthebay** [comment]
My point is that there are no error traces. The "error" doesn't happen - it gets caught by the catch. So basically you have to run an edited version of react (one removing the try/catch around the error) to find out where.

Not sure why that logic is there - it's functionally speaking pointless.

But if the try/catch is removed then it's a start - tho using console.error would be nicer than throwing an uncaught error...

**Comment by abritinthebay** [comment]
The code in question:

if (!condition) {
      var argIndex = 0;
      var message = 'Warning: ' + format.replace(/%s/g, function()  {return args[argIndex++];});
      console.warn(message);
      try {
        // --- Welcome to debugging React ---
        // This error was thrown as a convenience so that you can use this stack
        // to find the callsite that caused this warning to fire.
        throw new Error(message);
      } catch(x) {}
    }

Notice how that `throw new Error` will never throw? Yeah, that's the problem. If before there it had `console.error(message)` then at least it would have *some* use.

**Comment by sebmarkbage** [comment]
Chrome allows you to break on caught errors. That's why that try/catch is there. So that you can optionally toggle the breakpoint on and off.

@jimfb In 0.13 we used console.warn which doesn't have a stack associated with it anymore.

@abritinthebay In master (and the upcoming 0.14) release we've switched to using console.error that has a stack associated it with.

**Comment by abritinthebay** [comment]
Ah excellent. So it's been patched moving forward? Awesome. 

Now I just have to wait for 0.14 (any eta on that btw? ;) )

**Comment by sebmarkbage** [comment]
Follow the checkboxes: https://github.com/facebook/react/issues/3220 :)

**Comment by Wilfred** [comment]
See also https://github.com/facebook/fbjs/pull/183
