### ISSUE TITLE
The automatic bailout doesn't take context into account

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#4219]
See https://twitter.com/ryanflorence/status/613905590176186368

And the following thread.

Quick fix?

**Comment by jimfb** [comment]
Is this different from https://github.com/facebook/react/issues/2517 ?

Workaround is to call forceUpdate() after updating a context variable, right?

**Comment by ryanflorence** [comment]
see #4218

**Comment by spicyj** [comment]
Dupe of #4218. ;)
