### ISSUE TITLE
<textarea wrap="...">: wrap attribute is not supported

### ISSUE THREAD

**Issue by socketpair** [facebook/react#4226]
https://facebook.github.io/react/docs/tags-and-attributes.html : wrap is missing
https://facebook.github.io/react/docs/jsx-gotchas.html : `If you pass properties to native HTML elements that do not exist in the HTML specification, React will not render them.`

Meanwhile,wrap attributes is in standards: http://www.w3schools.com/tags/tag_textarea.asp.

**Comment by jimfb** [comment]
Yep, looks legit to me, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

I look forward to the day when #140 is resolved and we don't have to deal with this wackamole anymore :P.

**Comment by dmatteo** [comment]
Shouldn't this be closed?

**Comment by zpao** [comment]
Yes, thanks for the reminder

**Comment by dmatteo** [comment]
:+1:
