### ISSUE TITLE
Two different outputs from terminal and web inspector. Incorrect view rendered

### ISSUE THREAD

**Issue by liondancer** [facebook/react#4234]
I am having trouble with generating my views with `reactjs`. I have these two views which I would like to generate.

    var test1 = (
    	<div id="container">
    	  <p>{initials}</p>
          <p>loggedin!</p>
    	</div>
    	);
    
    var test2 = (
    	<div id="container">
    	  <p>notloggedin</p>
    	</div>
    	);

    var initials = "";
    var isLoggedIn = false;
    
    var Layout = React.createClass({
    	componentWillMount: function() {
    		try {
    			if (window && window.User) {
    				initials = window.User.name.first[0].toUpperCase() + window.User.name.last[0].toUpperCase();
    				isLoggedIn = true;
    			}
    		} catch(e) {
    			// ignore
    		}
    	},
        render: function () {
            if (isLoggedIn) {
            	console.log(window.User);
        	    console.log(initials);
            	return test1;
            } else {
            	console.log("not logged in");
        	    return test2;
            }
        }
    });

When I run this code, I have 2 different outputs from my terminal and my web inspector.

Terminal:

    [1] rendering server side react /
    [1] not logged in

Web inspector:

    Object {username: "bli1", userId: "1298085750", address: "127.0.0.1", name: Object, email: "Bradford_Li@gmail.com"…}
    
    BL

The first and second output from `console.log(window.User)` and `console.log(initials)` are displayed above. I am not sure why this is occurring. I'm not sure how to handle this to achieve the desired logic. 

The view displayed on my broswer is that of `test2`

**Comment by nopantsmonkey** [comment]
By terminal if you mean node environment then window will be not be available there and since you are not logging anything in catch block in componentWillMount therefore it is failing silently.

**Comment by jimfb** [comment]
@liondancer Did @nopantsmonkey's comment resolve your issue?

As a side point: In the future, questions like this are better asked on StackOverflow, since Github issues are intended to track bugs in the React core, rather than usage questions.
