### ISSUE TITLE
On iOS, extra nodes still emitted by React 0.13.3 when rendering the result of mapping over an Immutable collection

### ISSUE THREAD

**Issue by jedwards1211** [facebook/react#4235]
I understand [https://github.com/facebook/react/issues/3102] is considered fixed, but I'm still having similar issues on my iPhone.  I did the following with React 0.13.3 and Immutable 3.7.3 (using Webpack + Babel ES6 stage 0 transpiler -- not sure if that might have an effect):

```
React.render(<ul>
  {Immutable.List([1,2,3]).map(i => <li>{i}</li>)}
</ul>, document.body);
```

This works properly in Chrome on my desktop.  However, in Safari on my iPhone, it prints the number 3035 without a bullet above the list items.

My user agent string for Safari on my iPhone is:
`Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4`

Thanks!
Andy

**Comment by spicyj** [comment]
I can't repro at http://react.jsbin.com/sinehasako/edit?js,output on iOS 8.3. Can you repro on that page?

**Comment by jedwards1211** [comment]
Huh, I can't either.  Do you know if the Babel polyfill is supposed to enable full ES6 iterator operation on iOS Safari?  I was thinking this might be a bogus ticket a moment after I created it.  I wonder what might be different in the jsbin config?

**Comment by jedwards1211** [comment]
I wonder if it's some subtle thing with webpack.  I'm doing `require('babel/register')` which is supposed to load the polyfill...

**Comment by spicyj** [comment]
Not sure. This case doesn't need any polyfill though. Plain JS:

http://react.jsbin.com/fasohojiwo/1/edit?js,output

**Comment by spicyj** [comment]
You should be requiring babel/polyfill I think? https://babeljs.io/docs/usage/polyfill/ Are you requiring it before both immutable and react? That might be necessary.

**Comment by jedwards1211** [comment]
That page claims that `require('babel/register')` automatically loads the polyfill.  Yeah, I'm requiring it before everything, though I'm still not sure I can assume anything about the load order of individual modules.

I was surprised it works in plain JS, I thought React is implicitly using an iterable created by `map` in this case?  Or has React been modified to do something different?

Thanks for your help!

**Comment by spicyj** [comment]
babel/register is used in Node applications:

https://babeljs.io/docs/setup/#babel_register

Those docs mean that you don't need to also require the polyfill in that case. babel/register is not the correct thing to require in a browser environment though.

**Comment by spicyj** [comment]
Immutable and React both fall back to the `@@iterator` property if Symbol.iterator doesn't exist in the environment.

**Comment by jedwards1211** [comment]
Huh...confusing enough, as requiring `babel/register` fixed ES6 code issues in iOS safari for me...anyway I just put `babel/polyfill` in the entry section of my webpack config, and that worked as well.  Thanks for the tip!

I wish I could peer more deeply into what's happening with the raw page in my iOS Safari, but I don't have a Mac so I can't remote debug it at the moment.  In any case `.map(...).toArray()` is a simple workaround for me right now.

**Comment by spicyj** [comment]
(Closing since this doesn't sound like a React issue.)
