### ISSUE TITLE
Force element sub tree cleaning 

### ISSUE THREAD

**Issue by isergey** [facebook/react#4243]
Hi all. I have a big search result set rendered as <div><ResultSet /></div>

When I make a new search request, server return new unique results, and I think that in this case there is no need to calculate the optimal DOM difference. Simply right to remove a DOM sub tree of ResultSet and render a new.
Do I understand correctly that the attribute Key solve this problem?

Thanks for the answer!

**Comment by spicyj** [comment]
Yes, just put a new key on the container and React will render that subtree from scratch.
