### ISSUE TITLE
Can't React.render() into the same tbody-Element multiple times.

### ISSUE THREAD

**Issue by rickhub** [facebook/react#4254]
Currently i'm trying to replace some parts of a huge AngularJS application with React. My goal is to speed up rendering times, especially when it comes to displaying large dataviews.

While trying so, i ran into a strange problem. When trying to call React.render() multiple times on the same `tbody`-Element, React throws the following two warnings:

> Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.
react-with-addons.js:21560

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <tbody data-reactid=".
 (server) <tr data-reactid=".0.$

I created a simple fiddle just for demonstrating the issue: https://jsfiddle.net/4ca8tkj1/

The same code works, if i render into a `div`-Element for example: https://jsfiddle.net/5adr5xet/

Am i missing something here?

PS: Thanks for your awesome work on React.js - still love it ♥

**Comment by syranide** [comment]
You are rendering a `<tbody>` into a `<tbody>` in your jsfiddle. It's invalid nesting according to browsers and they proceed to normalize it and break React's understanding DOM.

**Comment by rickhub** [comment]
Damn, you're totally right. But how can i provide rendering for the tbody-element only, without rendering the while table by React? The render-function can't return mutliple elements. And if i render it into `table` it will remove the already existing `thead`.

You got any ideas?

**Comment by syranide** [comment]
Right now you can't, the *only* possibility is to render the tbody into a `table = document.createElement('table')` and then transplant the tbody from it into your table. But I really don't recommend that unless you absolutely have to.

Another possibility could be to render the entire table in React but use `<thead dangerouslySetInnerHTML={...} />` to leap back out into HTML.

**Comment by rickhub** [comment]
Ok, thanks a lot. I hate dirty hacks, so i will end up rendering the whole table with React. This will lead to more work, but i think it's worth it.

**Comment by syranide** [comment]
PS. I should add that you could render each `<tr>` separately too and insert manually, that wouldn't be a hack. But it would probably not be a good idea either and you would have to do the house-keeping yourself, but it wouldn't be a hack.

**Comment by jimfb** [comment]
Ok, looks like @rickhub has the info he needs!  Thanks @syranide.  And welcome @rickhub to the React community!  Since this isn't a bug in React, I'm going to close the issue, but feel free to continue the discussion on this thread or at StackOverflow.
