### ISSUE TITLE
Extend propTypes and deprecate getDefaultProps()

### ISSUE THREAD

**Issue by fizker** [facebook/react#4256]
There are some prop types which are not easy to describe via propTypes. I find it unfortunate that it is not obvious when a propType have a default, especially if null is not an accepted value.

A short summary of how you can get the React type warnings to act as intended (in flow syntax first):

- Optional

        // Flow
        someString:?String

        // React
        propTypes: {
          someString: React.PropTypes.string
        },
        getDefaultProps: function() {
          return {
          }
        },

- Non-Optional

        // Flow
        someString:String

        // React
        propTypes: {
          someString: React.PropTypes.string.isRequired
        },
        getDefaultProps: function() {
          return {
          }
        },

- Optional with default value

        // Flow
        someString:?String = "default"

        // React
        propTypes: {
          someString: React.PropTypes.string
        },
        getDefaultProps: function() {
          return {
              someString: "default"
          }
        },

- Non-Optional with default

        // Flow
        someString:String = "default"

        // React
        propTypes: {
          someString: React.PropTypes.string.isRequired
        },
        getDefaultProps: function() {
          return {
              someString: "default"
          }
        },

All these give the type warnings that you would expect based on the flow type,
but especially the “non-optional with default” case is really hard to read in React.

Perhaps an alternate syntax for propTypes which incorporates default values should be considered:

    propTypes: {
        someString: React.PropTypes.string.notNull.defaultValue("default"),
    },

This also solves the readability issue of `getDefaultProps()`, where you would
think that it is resolved at runtime, when in fact it should be considered a set
of static values.

----

I discovered this issue because of some code where there is a non-required prop (because it has a default), but `null` is not an acceptable value. The issue is that you get no warning if you overwrite it with `null`, because React thinks that this is acceptable. And putting `.isRequired` on something with a default value looks really funky.

**Comment by jimfb** [comment]
I think the plan is to move away from propTypes in favor of flow.  In the future we are expecting people to only define getDefaultProps and not to define propTypes.  @sebmarkbage and @spicyj is this a correct assertion?

**Comment by sebmarkbage** [comment]
Would it seem less weird if required was the default, like it is in Flow?

My hope is that another dynamic type system (maybe using Flow syntax) eventually takes over the responsibility of React's propTypes. It really has nothing to do with React. However, until there is a dynamic alternative we'll still keep it. However, there is so much work making a really good type system that I think that it is a wasted effort trying to do it specifically for just React which is why we're not putting a lot of effort into this atm.

There isn't really a neat syntax to collocate the default value and type definition in Flow right now, but if you can think of a neat syntax you should propose it.

**Comment by eberhara** [comment]
"React.PropTypes.string.notNull.defaultValue("default")..." seems a little big (and weird) to me.
Maybe "defaultProps" could move into flow's direction, it is much more intuitive.

**Comment by jimfb** [comment]
Proptypes is mostly in maintenance mode, and we probably aren't making big API changes at this point.
