### ISSUE TITLE
Why did react retain event listeners after the relevant elements unmounted

### ISSUE THREAD

**Issue by dexbol** [facebook/react#4261]
Is this going to make performance problem ? 
Example: [https://jsfiddle.net/p8vc1Ln1/](https://jsfiddle.net/p8vc1Ln1/) . Events like `focus` `blur` and so on retained after `input` element removed.

**Comment by spicyj** [comment]
React adds one top level listener for each event but doesn't stop listening if the components are unmounted. We've never seen this to be a performance problem.

**Comment by dexbol** [comment]
@spicyj Yes you are right,  React does not have performance problems, some unused event listeners are not big deal. 

It makes me a little bit sad that I see the number of listener growing when I inspect my SPA by chrome timeline tools. 

Would you consider if remove unused listener is better or not.

**Comment by spicyj** [comment]
It could be that removing listeners is better in some cases, but in other cases you'll soon mount a new component which needs the same events in which case we'd be wasting effort by removing and readding them.
