### ISSUE TITLE
Use the right document in iframe selection events

### ISSUE THREAD

**Issue by zpao** [facebook/react#427]
We use `document` directly a bunch where that might not be the right thing if the event is occurring in an `iframe`. We should do it right. (split from #373)

**Comment by acusti** [comment]
Yes indeed! This issues refers to the uses of the global `document` and `window` objects in `ReactDOMSelection` and the `SelectEventPlugin`.

**Comment by nhunzaker** [comment]
Woooooo! Cheers to closing a 5 year old issue!!! 🎉🎉🎉🎉
