### ISSUE TITLE
what the meaning of this?

### ISSUE THREAD

**Issue by jerryshew** [facebook/react#4277]
![qq20150703-1 2x](https://cloud.githubusercontent.com/assets/5626417/8492481/f1744886-217c-11e5-852f-4538a89cbfa9.png)

**Comment by dozoisch** [comment]
Probably a global ENV variable replaced by webpack. Which would then be stripped out by any minifier because it's unreachable.

**Comment by zpao** [comment]
It's a build artifact allowing us to create multiple development and production builds.
