### ISSUE TITLE
How to use Perf and TestUtils

### ISSUE THREAD

**Issue by koba04** [facebook/react#4279]
In v0.14.0-beta1, Perf and TestUtils don't publish as npm package.

https://github.com/facebook/react/blob/master/grunt/tasks/npm-react-addons.js#L8-L42

How can i use these libraries?
Should I use `react/lib/xxx` directly?

```
var Perf = require("react/lib/ReactDefaultPerf");
var TestUtils = require("react/lib/ReactTestUtils");
```

 I can't find a document mentioned this.

**Comment by zpao** [comment]
Things moved fast and I don't think those made it. We'll make sure they get done soon (next beta)

**Comment by koba04** [comment]
Thanks!

**Comment by slorber** [comment]
@zpao what would happen when we try to require Perf when using React with production env? Former addons did not include Perf so we simply could not use it directly but now we'll be able to require it for prod env too

**Comment by koba04** [comment]
Thanks! :tada:
