### ISSUE TITLE
[regression] e.target for onChange is ndefined in 0.14.0-beta1

### ISSUE THREAD

**Issue by dantman** [facebook/react#4288]
I tried updating from `0.14.0-alpha3` to `0.14.0-beta1`.

Something has changed in between these releases that is making it so that `e.target` in onChange's synthetic event is undefined.

**Comment by dantman** [comment]
This appears to be related to a bug in `src/renderers/dom/client/eventPlugins/ChangeEventPlugin.js`. `ChangeEventPlugin.extractEvents` does not accept the `nativeEventTarget` argument and does not pass it on to `SyntheticEvent.getPooled`.

However that's not the only fix needed, `manualDispatchChangeEvent` also needs to pass something in place of the `nativeEventTarget` that `SyntheticEvent.getPooled` expects.

Also it seems `BeforeInputEventPlugin` has the same issue with `nativeEventTarget` being passed.

I tried fixing this myself. However I have issues with the test setup and/or the test utils seem incapable of triggering `change` from `input`.

**Comment by slorber** [comment]
Yes I can confirm I have this issue too!

**Comment by chicoxyzzy** [comment]
Same issue. The workaround is using `e.currentTarget.value` instead of `e.target.value`. But that's kinda wrong :(

**Comment by syranide** [comment]
Same here, but you can use `e.nativeEvent.target` for now.

**Comment by Jackien** [comment]
Excuse me. I'm a beginners of React. Can I ask a question?   Why can I use "jsx -watch src/build" to translate "src/helloworld.js" file to plain JavaScrip?

**Comment by Jackien** [comment]
In fact, I can't see any result after do all steps。

**Comment by slorber** [comment]
@Jackien I don't know, but this is not the place for asking such questions. Ask this on Stackoverflow or IRC / Slack channels maybe

**Comment by Jackien** [comment]
@slorber   Thank you for your answer.
