### ISSUE TITLE
Issue with React class variable references

### ISSUE THREAD

**Issue by activatedgeek** [facebook/react#4297]
I have weird behaviour (probably undocumented). Here is what can be done to replicate it.
React Version: `0.13.3`

```javascript
// create a React component
var MyComponent = require('./path/to/my/component');

// create a reference
var component = MyComponent;

// Try render (will not work!!)
React.render(<component />, target);

// create a new reference
var Component = MyComponent;

// Try render (will work!!)
React.render(<Component />, target);
```

Is this a desired behaviour? Have I missed something in the documentation?

**Comment by andreypopp** [comment]
Yes, this is a desired behaviour.

By convention (see [docs](http://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components)) JSX element with lower case tag name `<component />` will be transformed into  `React.createElement('component', ...)` which will instruct React to produce `<component>` DOM element.

`<Component />` JSX element will be transformed into  `React.createElement(Component, ...)`  and render a composite React component you reference in a variable.

**Comment by activatedgeek** [comment]
So, I am building a simple internal parser which maps the configuration to certain `React` classes. Those are loaded into an `Array` after the configuration file is parsed. All the required `React` component modules have `module.exports = React.createClass({...})` kind of structure. 

And now during the rendering (after parsing), I simply `map` over these required modules, store in a variable named `Component` and render it using `<Component />`. Is this a correct approach?

**Comment by andreypopp** [comment]
Yes, that sounds correct, @activatedgeek

**Comment by activatedgeek** [comment]
Thanks for the input!
