### ISSUE TITLE
Using extend to create a class of a react component shows me an error for initialState

### ISSUE THREAD

**Issue by reduxdj** [facebook/react#4304]
Maybe i don't understand why? But what's the alternative?

Warning: getInitialState was defined on CampaignList, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
3vendor.js:21739 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.

```coffeescript
class CampaignList extends React.Component
  getInitialState: ->
    {empty:true}
```

..and

```cjsx
 <div className={className}>
      <Sidebar>
        <CampaignForm/>
      </Sidebar>
      <ContentBox>
        <div className="content-header">
          <h1 className="col-xs-12 col-md-6">Campaigns</h1>
          <div className="col-xs-10 col-md-3 btn btn-utility btn-campaign col-md-offset-3" onClick={@handleClick}>+ Create a new Campaign</div>
        </div>
        <CampaignList/>
      </ContentBox>
    </div>
)
```

**Comment by chicoxyzzy** [comment]
there is no method `getInitialState`. you should use constructor
see [this blog post](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es6-classes)

**Comment by jimfb** [comment]
Thanks @chicoxyzzy, that's the correct answer.

I'm going to close this issue, since it's not technically a bug in React (we use Github issues to track bugs in the React core), but feel free to continue the discussion in this thread or move the discussion to StackOverflow (preferred site for questions).
