### ISSUE TITLE
v0.14 Refs no longer components

### ISSUE THREAD

**Issue by BurntCaramel** [facebook/react#4305]
https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html
> The other big change we're making in this release is exposing refs to DOM components as the DOM node itself. That means: we looked at what you can do with a ref to a DOM component and realized that the only useful thing you can do with it is call this.refs.giraffe.getDOMNode() to get the underlying DOM node.

I’ve used `refs` to perform a custom method such as `play()` on a child component. Having only the DOM node accessible will make this no longer possible.

Is there a better practice I should be following to call methods on descendent components?

**Comment by jimfb** [comment]
Your child component is probably a composite component, not a dom component.  DOM components are like `span` and `div`.  If your component has a `play()` function, it is probably not a DOM component (technically, you could be referring to a web component, but then you will get the physical WebComponent so you should still be able to use the play function on that).

**Comment by BurntCaramel** [comment]
Yes it’s my own component, a composite. I haven’t tested it, but it seems to be saying that refs all contain raw DOM nodes? So no way to access the React component? Sorry I’m just restating things but I don’t know what else to ask – it seems to me it will obviously break based on what is documented in the blog post. Thanks

**Comment by jimfb** [comment]
To clarify:
* DOM Components wrap the nodes in the DOM.  They are things like `<div>` and `<span>` and `<img>`.  Refs to these components now return the underlying DOM node, so there is no longer a need to call `findDOMNode` on them.
* Composite Components are the components that you write.  They are things like `<MyFancyMenu>` or `<MyContextProvider>`.  Refs to these components are unaffected.

**Comment by jimfb** [comment]
Looking at the blog post, it does say:
> References to custom component classes work exactly as before.

Since the blog post is technically correct and does explicitly state that custom component classes work exactly as before, I'm going to go ahead and close out this issue.  Feel free to continue the discussion here.  If enough people find this confusing, we can re-open this issue to work on the communication/messaging.

**Comment by BurntCaramel** [comment]
Ah right, ok that makes sense. I read ‘DOM components’ as ‘components that are DOM flavoured’ – especially now that React is being separated into react and react-dom, that’s just how I read it.

Overall, I think this makes heaps of sense as an API change.

**Comment by dcousens** [comment]
I had the same impression as @BurntCaramel, thanks for clarifying.

**Comment by serle** [comment]
I have a ref to a custom component (outer cc) that renders and inner custom component (inner cc) when I try to use my ref to the outer cc React 0.14 seems to return a ref to a wrapper around the outer custom component, so all my public methods are inaccessible. This is not happening where I have a custom component that renders dom element i.e. no inner cc. Both outer cc and inner cc are created with cloneElement. My refs are all numeric index based. My workaround is:

                if (this.refs[index].refs['child']) {
                    console.log('we have a react wrapper');
                    this.refs[index].refs['child'].start();
                }
                else {
                    console.log('we have our actual component');
                    this.refs[index].start();
                }

I never create a ref "name" of child, this is definitely done by React itself. I have not pin pointed exactly when this happens but I think this is a framework encapsulation bug

**Comment by jimfb** [comment]
@serle Do you have a simple jsfiddle that demonstrates the issue?

**Comment by adjavaherian** [comment]
This might be a similar problem.  I'm wondering how to access the component methods on child component of a composite.

```javascript
     it('consider this', function(){
            var Stub = React.createClass({
                doSomething: function() {
                    console.log('whoohoo!');
                },
                render: function(){
                    return null
                }
            });

            var StubElement = TestUtils.renderIntoDocument(React.createElement(Stub, {}));

            StubElement.doSomething(); //should log
     });

     it.only('now consider this with a context', function(){
         var Stub = React.createClass({
             contextTypes: {
                 location: React.PropTypes.object
             },
             doSomething: function() {
                 console.log('whoohoo!', this.context.location.pathname);
             },
             render: function(){
                 return null
             }
         });

         var ContextWrapper = React.createClass({
             childContextTypes: {
                 location: React.PropTypes.object
             },
             getChildContext: function() {
                 return {
                     location: window.location
                 }
             },
             render: function() {
                 return React.createElement(Stub, {})
             }
         });
         var StubElement = TestUtils.renderIntoDocument(React.createElement(ContextWrapper, {}));

         console.log(StubElement);
         StubElement.refs.children[0].doSomething(); // is not a function
         
     });

```

I don't see any references to the stub element in the second spec?  How can I access that function?

**Comment by zpao** [comment]
@adjavaherian You're trying to access a method on a rendered child. You can't access that directly. You could attach a ref in render of ContextWrapper (on Stub) and then put a getter in ContextWrapper that access that ref and exposes the method.

**Comment by adjavaherian** [comment]
@zpao awesome.  got it.  thanks.
