### ISSUE TITLE
Multiple variation of the same component mounted 'Invariant Violation: ReactMount'

### ISSUE THREAD

**Issue by sabeurthabti** [facebook/react#4307]
```
Uncaught Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0
```

I am mounting the same component 3 times with different heading ( css hiding and showing).

**Comment by jimfb** [comment]
Do you have a simple example that demonstrates the issue?

**Comment by jimfb** [comment]
No response for over six months, closing.
