### ISSUE TITLE
Keyboard selection doesn't fire onChange for <select> in Firefox

### ISSUE THREAD

**Issue by insin** [facebook/react#4313]
Related bug in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=126379

My [workaround for this is to use onKeyDown](https://gist.github.com/insin/c2a00a7e85ccfab0e7c7), allowing the selection to change then calling an `onChange` handler manually, but this won't bubble..

Is this something `ChangeEventPlugin` could support?

**Comment by MoOx** [comment]
That would be great to normalize this annoying behavior of Firefox.

**Comment by spicyj** [comment]
Yes, that would be nice. Any chance you want to look into adding it?

**Comment by aweary** [comment]
Looks like this behavior [has been fixed in Firefox](https://github.com/w3c/html/issues/263#issuecomment-345838693)
