### ISSUE TITLE
shallowCompare not set on React.addons (npm version 0.13.3)

### ISSUE THREAD

**Issue by pocketjoso** [facebook/react#4315]
According to the docs for [react-codemod](https://www.npmjs.com/package/react-codemod#included-scripts), React > 0.13.x should include `React.addons.shallowCompare` (which is used by the `PureRenderMixin` transformation) - but when installing `react` from npm this is not the case. In the locally installed react node module `lib/ReactWithAddons` is missing [this line](https://github.com/facebook/react/blob/master/src/addons/ReactWithAddons.js#L43). Is the npm package not up to date, or what else is wrong here?

If it matters:
`react`: `0.13.3`
`npm`: `2.12.1`
`OSX`

(I know this error will go away with `0.14.x`, but we can't really upgrade to that while it's in beta..

**Comment by zpao** [comment]
Hmm, #3355 landed after we shipped v0.13.0 and we never took that in the stable branch. At this point (going on 4 months later) we're not going to add it now so we should update the docs for react-codemod, then figure out the right thing for 0.14. cc @cpojer

**Comment by pocketjoso** [comment]
Thanks for quick response. Any suggestions for how to make use of `react-codemod` for upgrading to `0.13.x`? I'm guessing perhaps hacking that specific (`PureRenderMixin`) test, perhaps..

**Comment by cpojer** [comment]
This is unfortunate. We are thinking of adding a flag to React components that denotes whether they are pure (cc @sema). Once we have this I will update the codemod accordingly.

@pocketjoso I would suggest, in your main component (or any side-effectful component that sets up your environment), to manually add React.addons.shallowCompare. You'll be able to remove this once we ship a React version that exports this function or once we add the flag I mentioned before.

**Comment by pocketjoso** [comment]
@cpojer It is unfortunate indeed, because it means codemod a lot less useful out of the box. I will monkeypatch React.addons to add the shallowCompare function.

**Comment by jardakotesovec** [comment]
According to [release notes](http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html) shallowCompare is now separate package [react-addons-shallow-compare](https://www.npmjs.com/package/react-addons-shallow-compare). 

@cpojer Can we expect codemod update that use this package instead of `React.addons` ?

Thanks!

**Comment by cpojer** [comment]
Oh, I missed this! Yeah absolutely, this shouldn't be that big of a deal, except of course adding a require/import at the right location is still hard :)

**Comment by cpojer** [comment]
I'm quite swamped with work on jest at the moment. Is this something you'd be interested in sending a PR for, @jardakotesovec ?

**Comment by jardakotesovec** [comment]
@cpojer Unfortunately also swamped with more pressing stuff.

**Comment by zpao** [comment]
Moved to https://github.com/reactjs/react-codemod/issues/2
