### ISSUE TITLE
Example of using TestUtils.Simulate.change on a multiple select field.

### ISSUE THREAD

**Issue by gruntruk** [facebook/react#4316]
Hi, I am trying to find a working example of driving a multiple select element using React's TestUtils. For a single select this works fine:

``` javascript
TestUtils.Simulate.change(el, { target: { value: 1 } });
```

For a multiple select field, you get an error:

```
TypeError: Array.prototype.slice called on null or undefined
```

If instead pass an array of arguments to `change` it doesn't seem to be triggering the change handler or being reflected in the component state:

``` javascript
TestUtils.Simulate.change(el, [{ target: { value: 1 } }]);  // doesn't seem to trigger any change in component state
```

Apologies if I'm missing something obvious but if anyone knows of the proper way to do this any help would be appreciated.

Thanks

**Comment by jimfb** [comment]
TestUtils are primarily for internal testing purposes, and are not stable public APIs.  We usually don't implement a particular piece of functionality until we need it for one of our internal tests.  What is your use case?  Are you trying to create a PR for this repository?

**Comment by RobAWilkinson** [comment]
I know this is long over but an easy way to fix this is to set the individual `option`'s `selected` property to true, then call yor handler. thats how i got around this issue
