### ISSUE TITLE
<img> Tag rendering differently client + server and invalidating checksum.

### ISSUE THREAD

**Issue by Ianfeather** [facebook/react#4321]
Hi there, I tried to find similar issues but don't believe there are any. This is a reduced case using React 0.13.3.

The problem is a difference in how React.render and React.renderToString are dealing with img tags and their closing `/>`. This kinda confuses me because I assume they're doing the exact same thing under the hood but if I tap into `_mountImageIntoNode` and inspect `markup` and `rootMarkup` I can see there is a difference:

### Server code
```
const React      = require('react'),
      ReactApp   = require('../../public/scripts/components/scaffold/app-wrapper'),
      appContent = React.createFactory(ReactApp),

React.renderToString(appContent())
```

### Client code
```
import AppWrapper from './components/scaffold/app-wrapper';

ReactDOM.render(<AppWrapper />, document.getElementById('app-wrapper'));
```

### Component - app-wrapper

```
import React from 'react';

class AppWrapper extends React.Component {

    render() {
        return (
            <img alt="foo" />
        );
    }

}

export default AppWrapper;

```

### Output from `_mountImageIntoNode`

```
> markup
"<img alt="foo" data-reactid=".gsisljabk"/>"

> rootMarkup
"<img alt="foo" data-reactid=".gsisljabk">"
```

Note the self-closing tag in `markup`. Is there something obvious that I'm doing incorrectly here? Is there a way to enforce including/leaving closing tags?

Thanks for any help you can offer.

**Comment by syranide** [comment]
I'm guessing you're running an older version of React server-side, XML-compatible output is a recent thing.

**Comment by Ianfeather** [comment]
They're using the same version :/ If I log it out I get 0.13.3 for both. 

If no one else has the problem perhaps it's something local to me. I can try upgrading to 0.14 and see if the issue still exists.

**Comment by jimfb** [comment]
@Ianfeather Thanks!

**Comment by jimfb** [comment]
React checksum attribute gets inserted in the wrong place when rendering a self closing tag at the root.

@Ianfeather I believe you can work around the issue by having your render function return `<div><img alt="foo" /></div>`.  I know it's hacky, but let me know if this does/doesn't work for you.

**Comment by Ianfeather** [comment]
I'm not sure that will work as it was happening previously when I had multiple `divs` wrapping the `img`. I stripped it down to just one image to isolate the case. Will try with a single wrapper, and also on 0.14 and get back to you. 

Thanks for replying so soon!

**Comment by zpao** [comment]
@jimfb, going to file that separately since it seems tangential (0.13 didn't do self closing tags)

**Comment by zpao** [comment]
React didn't generate self closing tags in 0.13 so I'm not sure how `markup` would ever contain that in 0.13. It also looks like you're using `ReactDOM` in your client code, which to me indicates you might be mixing versions (the require statement isn't there so I can't be sure). Could you double check the version numbers (rebuild client bundles, clear caches, etc just to be sure)

**Comment by Ianfeather** [comment]
You're absolutely right. My bad. The react versions were both 0.13 but I was using ReactDOM having just used in a different project.

I was just about to mention that this works fine in 0.14-beta1, but having just figured that out that's kinda unsurprising! Sorry for causing you hassle.

**Comment by zpao** [comment]
No problem, we found a very legit bug as a result of the discussion and investigation!

**Comment by nodu** [comment]
Hi Everyone! I'm having a similar issue where ReactDOMServer renders images with a closing /,  but the client bundle comes along and renderers without the /. Causing a mismatch error. I've just upgraded to React .14 for both client and server.

**Comment by syranide** [comment]
@nodu Sounds like you're not using ReactDOM 0.14 on the client...

**Comment by nodu** [comment]
Client side:
```
import ReactDOM from "react-dom"
...
ReactDOM.render(
```

Your edit seems to suggest this is a known issue? My serverside renders `<img blah blah />` but client does `<img blah blah >`

**Comment by jimfb** [comment]
@nodu What do you mean when you say the client does `<img blah blah >`?  Are you getting a checksum warning?  Can you provide a simple jsfiddle?

**Comment by nodu** [comment]
Yes, @jimfb  I'm getting this:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) .20sikl906ww.2.2.1.$EXxkPxefTtywv7xFToFL
 (server) .20sikl906ww.2.2.1.$36luBceRSfSgZB7DSKsN
```
And the only difference I can see between client and server is the lack of a `/` on the client.

**Comment by jimfb** [comment]
@nodu So I'm not seeing a checksum warning.  https://jsfiddle.net/hmq40m6c/  What am I doing wrong?

**Comment by syranide** [comment]
@nodu Your error message indicates an element with a different key on client/server, specifically `EXxkPxefTtywv7xFToFL...` vs `36luBceRSfSgZB7DSKsN...`. What you're seeing there is the `data-reactid="..."` attribute.

**Comment by nodu** [comment]
@syranide So the data-reactid is different and not the img tag's `/` ?  I'm at a loss on how to go forward then.

**Comment by syranide** [comment]
@nodu I'm still not sure how you arrive at the conclusion of `/>` being the issue, are not checking normalized DOM vs rendered DOM?

> I'm at a loss on how to go forward then.

Look for a place in your code where you provide keys that look like the ones above, and try to figure out why they may be different on the client and server. Are they randomly generated? Are they part of a non-sorted DB query that you execute once for server and once for client? (bad idea) Are they serialized and sent to the client as JSON and displayed without sorting? (some JSON implementations do not maintain key ordering)

**Comment by nodu** [comment]
@syranide AH! Thank you so much, the previous developer was using random uuid slugs to generate the keys!
