### ISSUE TITLE
Checksum inserted incorrectly for self-closing root tags

### ISSUE THREAD

**Issue by zpao** [facebook/react#4323]
This came up while diagnosing #4321 - https://github.com/facebook/react/issues/4321#issuecomment-120064258

This is because we just look for the closing `>` when adding the checksum.

```
> ReactDOM.renderToString(React.createElement('img'))
'<img data-reactid=".yxoueqje2o"/ data-react-checksum="-951841932">'
> ReactDOM.renderToString(React.createElement('div', null, React.createElement('img')))
'<div data-reactid=".2d7dcluvuv4" data-react-checksum="-890562330"><img data-reactid=".2d7dcluvuv4.0"/></div>'
```

**Comment by vramana** [comment]
@zpao Is checking the only index of char `<` is 0 in the markup sufficient to determine whether the tag is self closing tag? I can't think of any corner cases. If so changing the `addChecksumToMarkup` [here](https://github.com/facebook/react/blob/master/src/renderers/dom/server/ReactMarkupChecksum.js#L23) based on that should suffice right ?

**Comment by jimfb** [comment]
No, indexof is not sufficient because an attribute might contain a `<` character.  I have a fix, pushing now.
