### ISSUE TITLE
Why are attribute names "class" and "for" discouraged?

### ISSUE THREAD

**Issue by callumlocke** [facebook/react#4331]
From the [docs](https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components):

> **Note:**
> Since JSX is JavaScript, identifiers such as `class` and `for` are discouraged as XML attribute names. Instead, React DOM components expect DOM property names like `className` and `htmlFor`, respectively.

But the JSX compiler seems to be [smart enough to quote keys like `"class"` and `"for"`](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&code=var%20label%20%3D%20%3Clabel%20id%3D%22foo%22%20class%3D%22bar%22%20for%3D%22other%22%2F%3E%3B) (so they'll work fine even in pre-ES5 environments). So what's the problem? Why are they discouraged, and what exactly does that mean?

**Comment by zpao** [comment]
The wording there is a bit confusing but here's a short answer:

Our DOM components use (mostly) the JS API so we opted to use the JS properties (`node.className`, not `node.class`).

You're welcome to use `class` and `for` in your own components. Not all JSX compilers quote keys (eg react-tools) so just be aware of your own constraints and tool choices.

**Comment by jimfb** [comment]
If the docs are confusing, we should leave the issue open to fix them.

**Comment by callumlocke** [comment]
If the wording is confusing, then can you reopen this until it's reworded? :)

**Comment by kevinSuttle** [comment]
I thought the same about "type".

**Comment by chicoxyzzy** [comment]
`type` is not reserved word in JS

> You're welcome to use class and for in your own components. Not all JSX compilers quote keys (eg react-tools) so just be aware of your own constraints and tool choices.

Also those keys are hard to type using TypeScript or Flow

**Comment by kevinSuttle** [comment]
Right, but there are several `type` attributes in HTML, particularly in input and button elements.

**Comment by nhunzaker** [comment]
I'd like to see support for direct use of `class` and `for`. There is overlap with #5926, and conversation has picked up again there, so I'll close this out.

**Comment by karansinghgit** [comment]
It may not come under best practices, but will I face any issues in the future if I use `class` and not `className`?

**Comment by sarimarton** [comment]
In app code I would say it's outright recommendable to use `class`, especially if you want your codebase to be a lot more ergonomic with tailwind. Suppressing the warning can be done with a console.log override. In library code, I would support both.
