### ISSUE TITLE
e.stopPropagation() seems to not be working as expect.

### ISSUE THREAD

**Issue by luokuning** [facebook/react#4335]
I found this issue when I attempted to integrate ReacJs and a jQuery widget.

I bind an click event on input element and document like follow:
```javascript
var Search = React.createClass({
    handleClick: function(e) {
    	e.stopPropagation();
    },
    render: function() {
        return <input onClick={this.handleClick} />
    }
});
document.addEventListener('click', function() {
    console.log('propagation')
}, false);
```
And everytime I click the input element, chrome devtool logs 'propagation' message. Should not document element can not receive click event? I'm confused, Did I miss something?

**Comment by syranide** [comment]
React (currently) uses a listener on the document for (almost) all events, so by the time your component receives the event it has already bubbled all the way up to the document and stopping it only stops it from synthetically bubbling up through the React hierarchy.

**Comment by luokuning** [comment]
got it, many thanks :)

**Comment by fcsonline** [comment]
You can reproduce this issue in the following jsbin:

http://jsbin.com/rafitiq/edit?html,js,output

**Comment by JounQin** [comment]
@baurine You saved my life!

**Comment by nettiopsu** [comment]
The change to "window" did not help me, at least when click happened outside of the initial component

**Comment by gaearon** [comment]
We're fixing this in React 17.

**Comment by gaearon** [comment]
If you want to try it:
https://reactjs.org/blog/2020/08/10/react-v17-rc.html

**Comment by Alexej-Vakulich** [comment]
@gaearon I'm not sure that I got it correctly, but why a case when a user attaches an event listener to a specific DOM node (not to `document`) isn't working? I've created a fast example [here](https://codesandbox.io/s/affectionate-lederberg-w40rq?file=/src/App.js:656-671).

**Comment by oliviertassinari** [comment]
Interestingly, since the change of React 17,

<img width="538" height="551" alt="Image" src="https://github.com/user-attachments/assets/b7005378-9584-4b10-8615-0be64cb96b07" />

https://legacy.reactjs.org/blog/2020/08/10/react-v17-rc.html

Next.js is now rendering the page from the `<document>`, the problem (this issue) can be easily reproduced. I have created a reproduction with React 19 to illustrate it: https://stackblitz.com/edit/sb1-sy3flaed?file=src%2FApp.tsx.
