### ISSUE TITLE
How does the third argument of React.Children.forEach work?

### ISSUE THREAD

**Issue by VaJoy** [facebook/react#4339]
I've found out that `React.Children.map/forEach` has an optional argument as `[, object thisArg]` which could set this to another object through [Top-Level API](http://facebook.github.io/react/docs/top-level-api.html), then I try to run the code below:
```javascript
        var obj = {
            num : 3
        };

        var Component = React.createClass({
            deal : function(){
                console.log(this, this.num);  //it`s NOT obj
            },
            render : function() {
                React.Children.forEach(this.props.children, this.deal, obj);
                return (<ul>
                          {this.props.children}
                        </ul>)
            }
        });

        React.render(
            (
                <Component>
                    <li>0</li>
                    <li>1</li>
                    <li>2</li>
                </Component>
            ), document.body
        )
```
it logs three times of `Constructor undefined` and I have no idea why they are not `obj 3`.

so how does the third argument of `React.Children.forEach` work?

**Comment by fkling** [comment]
It works exactly how you expect it to work and how the native `forEach` and e.g. `map` methods.

The reason why it does not work for `this.deal` is rather simple: If you use `React.createClass`, all methods are **auto-bound**. Hence it is not possible later on to change the value of `this` inside those methods (e.g. via `.call` or `.apply`).

**Comment by VaJoy** [comment]
thx a lot, now it runs as I expected:
```javascript
        var Component = React.createClass({
            render : function() {
                React.Children.forEach(this.props.children, function(){ //独立的回调
                    console.log(this);  //now it`s obj :)
                }, obj);
                return (<ul>
                          {this.props.children}
                </ul>)
            }
        });
```
