### ISSUE TITLE
SyntheticEvent with undefined target

### ISSUE THREAD

**Issue by fedosejev** [facebook/react#4340]
In `v0.14.0-beta1` SyntheticEvent has `target` set to `undefined`:
http://jsbin.com/puvawigawi/edit?js,console,output

The same example works in `v0.13.3`:
http://jsbin.com/jajejewewa/edit?js,console,output

Any advise on what am I missing here?

**Comment by yaycmyk** [comment]
It was fixed in https://github.com/facebook/react/pull/4311#issuecomment-120160553 but you can use `currentTarget.value` in the meantime
