### ISSUE TITLE
Encoding declaration have been written in several ways

### ISSUE THREAD

**Issue by makky3939** [facebook/react#4347]
From the react/examples:

Encoding is declared as described below. In the 9 files.

https://github.com/facebook/react/blame/master/examples/basic-jsx-external/index.html#L4
`<meta http-equiv='Content-type' content='text/html; charset=utf-8'>`

However, in another example it has been declared in another writing.

https://github.com/facebook/react/blob/master/examples/jquery-mobile/index.html#L4
`<meta charset="utf-8">`

I think that we should unify to the latter way. In HTML5, it is possible to provide a short code by using the `charset` attribute.

**Comment by jimfb** [comment]
@spicyj @zpao Are we assuming HTML5 at this point, or are we aiming for backwards compatibility?

**Comment by spicyj** [comment]
IIRC the HTML5 meta charset tag, as with the doctype, was chosen because older browsers already interpreted it properly.

**Comment by jimfb** [comment]
oic, ok, so it sounds like this is a reasonable/desirable thing for us to do.

**Comment by makky3939** [comment]
ok, I'll create pull request.
