### ISSUE TITLE
docs: Getting Started, helloworld.html example fails on Chrome 43.0.2357.132 (64-bit), OSX Yosemite 10.10.3

### ISSUE THREAD

**Issue by yangmillstheory** [facebook/react#4354]
Downloaded the react starter kit today [here](http://facebook.github.io/react/docs/getting-started.html). 

Working through the **Separate File** section (same place as above), I made the following directory structure with the starter kit and my own `foo.html`, and `src/hw.js` files:

    react $ tree .
    ├── README.md
    ├── build
    │   ├── JSXTransformer.js
    │   ├── react-with-addons.js
    │   ├── react-with-addons.min.js
    │   ├── react.js
    │   └── react.min.js
    ├── examples
    │   ├── README.md
    │   ├── basic
    │   │   └── index.html
    │   ├── basic-commonjs
    │   │   ├── README.md
    │   │   ├── index.html
    │   │   ├── index.js
    │   │   └── package.json
    │   ├── basic-jsx
    │   │   └── index.html
    │   ├── basic-jsx-external
    │   │   ├── example.js
    │   │   └── index.html
    │   ├── basic-jsx-harmony
    │   │   └── index.html
    │   ├── basic-jsx-precompile
    │   │   ├── build
    │   │   │   └── example.js
    │   │   ├── example.js
    │   │   └── index.html
    │   ├── jquery-bootstrap
    │   │   ├── css
    │   │   │   └── example.css
    │   │   ├── index.html
    │   │   ├── js
    │   │   │   └── app.js
    │   │   └── thirdparty
    │   │       ├── bootstrap.min.css
    │   │       └── bootstrap.min.js
    │   ├── jquery-mobile
    │   │   ├── README.md
    │   │   ├── index.html
    │   │   └── js
    │   │       └── app.js
    │   ├── quadratic
    │   │   ├── example.js
    │   │   └── index.html
    │   ├── server-rendering
    │   │   ├── README.md
    │   │   ├── jsapp
    │   │   │   ├── package.json
    │   │   │   └── src
    │   │   │       └── App.js
    │   │   ├── reactserver
    │   │   │   ├── package.json
    │   │   │   └── server.js
    │   │   └── webapp
    │   │       ├── index.php
    │   │       └── static
    │   │           └── bundle.js
    │   ├── shared
    │   │   ├── css
    │   │   │   └── base.css
    │   │   └── thirdparty
    │   │       ├── console-polyfill.js
    │   │       ├── es5-sham.min.js
    │   │       ├── es5-shim.min.js
    │   │       └── jquery.min.js
    │   └── transitions
    │       ├── index.html
    │       └── transition.css
    ├── foo.html
    ├── react-0.13.3
    └── src
        └── hw.js

Source:

    react $ more src/hw.js
    React.render(
        <h1>Hello, world!</h1>,
        document.getElementById('example')
    );

Markup:

    react $ more foo.html
    <!DOCTYPE html>
    <html>
      <head>
        <title>Hello React!</title>
        <script src="build/react.js"></script>
        <script src="build/JSXTransformer.js"></script>
      </head>
      <body>
        <div id="example"></div>
        <script type="text/jsx" src="src/hw.js"></script>
      </body>
    </html>

Wouldn't load; in the Chrome console one has:

    XMLHttpRequest cannot load file:///Users/victoralvarez/code/other/playground/react/src/hw.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.load @ JSXTransformer.js:215
    JSXTransformer.js:215 Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/victoralvarez/code/other/playground/react/src/hw.js'.

I spent some time Googling this; the solutions [here](http://thodorisbais.blogspot.com/2015/03/how-to-solve-failed-to-execute-send-on.html) and [here](http://stackoverflow.com/questions/28922881/error-failed-to-execute-send-on-xmlhttprequest-failed-to-load-file-ang) didn't seem to work (didn't try restarting my machine, though).

However, the XHR worked in Safari.

Should we include a minor disclaimer in this case for Chrome, since we don't want this to be a barrier to entry for newcomers?

**Comment by jimfb** [comment]
Examples that use the in-browser transform can not be run from the `file://` protocol for security reasons.  The examples should run in chrome on osx if you throw them into a simple web server and load via `http://`.  For more details: http://stackoverflow.com/questions/20904098/react-js-example-in-tutorial-not-working

As a side note: we're going to stop building JSXTransformer in favor of using babel/browser.

I'm fine with adding a comment/note above the browser transformer explaining that some browsers will not run the transform unless it is served up from a simple http server.
