### ISSUE TITLE
statics + getDefaultProps wierdness

### ISSUE THREAD

**Issue by aleemb** [facebook/react#4359]
This tripped me up today:

```
var MyComponent = React.createClass({
  statics: { foo: "bar" },
  getDefaultProps: function() { MyComponent.foo; }
  // error: cannot read property foo of undefined
```

Instead, I must call `this.foo` from inside `getDefaultProps`. I presume this is because `getDefaultProps` is a static method and ends up being inside the statics object, hence it must be referenced it's siblings using `this`.

Filing a bug to bring it to your attention though since from the a user perspective the behaviour is a bit unexpected.

**Comment by joshbedo** [comment]
I would think `statics` would be attached to the instance of your component thus making `myComponent` not accessible within the context of `myComponent` so `this` would refer to `myComponent` since `getDefaultProps` is a prototype method. I'm pretty sure that's how it works but i'm sure someone with more experience will jump on and correct me if i'm wrong :)

I think you might be mixing it up with this scenario.
```
var MyComponent = React.createClass({
  statics: { foo: "bar" },
  getDefaultProps: function() { 
     return {
         prop: 'val'
     }
  }
  ...

MyComponent.foo // outputs => bar
```

**Comment by mathieumg** [comment]
> getDefaultProps is a prototype method

Are you sure? Since it's cached once per component type. Did you try:

```js
getDefaultProps: function() { this.constructor.foo; }
```

**Comment by brigand** [comment]
For this specific problem, calling getDefaultProps lazily is a possible solution (on first instantiation of the component class). 

---

As an aside: the static vs prototype confusion is cleared up in es classes.

```js
class MyComponent {
}

MyComponent.foo = 'bar';
MyComponent.defaultProps = {
  // also not a function anymore
  something: MyComponent.foo
};
```

**Comment by jimfb** [comment]
This issue hasn't seen any activity in six months, and is fixed in ES6 classes.  I don't think we're likely to make a change to this for the old style classes.
