### ISSUE TITLE
Components should be able to listen to tap events

### ISSUE THREAD

**Issue by petehunt** [facebook/react#436]
**Question:** how do you use touch events with React?

**Answer:**

- Use CommonJS
- git clone
- edit ReactDefaultInjection.js to include TapEventPlugin
- npm install; grunt
- add React.initializeTouchEvents(true) to your code in the right place

This sucks. Instead I think we should just either put TapEventPlugin on addons *or* create a react-mobile build which does all this by default.

**Comment by revolunet** [comment]
+1

**Comment by b0c1** [comment]
please put the TapEventPlugin to the addons (exists in react-addons package) because we want to use Material-UI without nodejs build (we want to use scala js) but we can't compile the TapEventPlugin as standalone (if you compile it will include the react core)...

**Comment by d4rky-pl** [comment]
+1 on comment above, I'm trying to use it without full nodejs stack and it's next to impossible to do without manual rewriting

**Comment by jimfb** [comment]
Tap is not a standard event, so we're probably going to rip it out of the core and let people detect taps in user land.  The current implementation probably needs a bit of cleanup anyway, to detect things like double taps.

Anyway, it's only 100 lines of code, available here:
https://github.com/facebook/react/blob/bef45b0b1a98ea9b472ba664d955a039cf2f8068/src/renderers/dom/client/eventPlugins/TapEventPlugin.js

If someone wants to fix it up and publish it as an external library/module, that might be useful to people.

**Comment by revolunet** [comment]
this maybe ? https://github.com/zilverline/react-tap-event-plugin

**Comment by MoOx** [comment]
@revolunet this works like a charm for me. It only handle simple tap. Double tap and long tap needs to be "calculated" by hand from this plugin.

**Comment by antoinerousseau** [comment]
Any update on this? should we make use of the add-on or keep using https://github.com/zilverline/react-tap-event-plugin (once it's fixed for v15.0)?

**Comment by spicyj** [comment]
We don't have any supported solution for this. In general we don't support defining custom event types for the same reason we don't have any global configuration: because it makes interoperability difficult (if you develop a component that requires TapEventPlugin, it won't work for someone who doesn't load it).

My best recommendation if you need this is to build a `<Tappable onTap={}>` component or similar completely in user space without depending on React internals. It should also be possible to fix up react-tap-event-plugin for v15, but we don't support that and can't guarantee that it will still work in a future release.

**Comment by antoinerousseau** [comment]
Thanks @spicyj for your quick update on this

**Comment by antoinerousseau** [comment]
Seems that `react-tap-event-plugin` just got fixed on their `master` branch. Just tried it and seems to work well again with `material-ui`. Won't be long before it reaches NPM.

**Comment by markwain** [comment]
Hi guys.
Update about `react-tap-event-plugin`: We may probably don't need to use it now. 

As posted [here](https://github.com/facebook/react/issues/6221#issuecomment-204486835)
> For some reason, I remembered touch events not being detected without TapEventPlugin being installed. I just tested it, and that is no longer the case. Since Chrome and Safari have both removed their tap delays for mobile pages, it's probably time to stop using TapEventPlugin and just us the onClick event.

**Comment by shishirarora3** [comment]
Hi,

I was using fastClick.js for touch based devices. Is it no more needed with react?

Regards’
Shishir Arora

**Comment by dickeylth** [comment]
@markwain For many popular apps that relying on webview to show web pages in China, such as Weixin, Taobao, Alipay, they are still using the old UIWebView in iOS, which still has no love for removing their tap delays for mobile pages, so the tap event is still necessary for several years...

**Comment by deepfriedbrain** [comment]
And I would think that older mobile devices that cannot be updated to the latest versions of Chrome/Safari would also need the plugin.

**Comment by gaearon** [comment]
I started a new thread to discuss how we can move the ecosystem to stop depending on `react-tap-event-plugin`. It *willI* break for good eventually. As @sophiebits suggested, it sounds reasonable if folks who depend on it create a userland `<Tapable>` component instead, and others can depend on it. Let’s discuss this effort in https://github.com/facebook/react/issues/11689.
