### ISSUE TITLE
Checkbox not rendering properly with ajax

### ISSUE THREAD

**Issue by waltonseymour** [facebook/react#4365]
When I render the following with this.props.genres populated from an AJAX call, the body of the inputs (the ```{genre} <br/>```) doesnt get rendered at all.
```js
  var GenreFilter = React.createClass({
    render: function(){
      var self = this;
      var inputs = _.map(this.props.genres, function(genre){
        return(
          <input
            type='checkbox'
            key={genre}
            value={genre}
            checked={self.props.active[genre] === true}
            onChange={self.props.onChange}
            >
            {genre}<br/>
          </input>
        );
      });
      return (
        <div>
        {inputs}
        </div>
      );
    }
  });
```
But when populating them with static data, they render fine.

In both cases, the data passed in is an array of strings.

Hopefully I'm not missing something obvious here.

**Comment by cody** [comment]
An `<input>` can't have children. The browser tries to fix this by moving `{genre} <br/>` out of the `<input>`. Then React stumbles on rerender, because the DOM has changed. 

But for that you should normally get a warning on the console. So maybe there is another problem.

**Comment by zpao** [comment]
@cody I bet that's the issue.

@waltonseymour You probably want to have HTML that looks more like `<label><input ...>{genre}<label>`

**Comment by waltonseymour** [comment]
Seems like strange behavior, but that works.
Thanks
