### ISSUE TITLE
Walkthrough Clarification

### ISSUE THREAD

**Issue by sim1hill** [facebook/react#4369]
Not reporting a bug or issue. I just wanted to let you know I found this part of the walk-through to be unclear and confusing and others may, too:

>To get started using the tutorial, just start editing public/index.html.

>##Getting started

>For this tutorial, we'll use prebuilt JavaScript files on a CDN. Open up your favorite editor and create a new HTML document:

It took me a while to figure out whether I was supposed to be editing in the index.html file provided when I cloned the repo or whether I should make a new file and how to link the two files if they were both necessary.

I'm new to React and pretty new to programming overall, but I do have some Javascript and Javascript framework experience. I really enjoyed the walk-through because it was simple to get started, so thanks for the helpful resource!!

**Comment by zpao** [comment]
Good catch & thanks for the heads up! I'd definitely call that a bug :)

We really need to go through the tutorial and make sure it's all cohesive. After 2 years of ad hoc updating it's definitely showing its age. If you have any other feedback (especially as somebody who is relatively new to programming), we'd definitely appreciate it.

**Comment by sim1hill** [comment]
No problem! I'm happy to help. Will definitely let you know if I see anything else. Thanks again for the great React.js resources!

**Comment by AnSavvides** [comment]
I've opened a PR with a minor change to make the bit that @sim1hill mentioned a little easier to follow.

@zpao +1 on making sure the tutorial is cohesive.

What are your thoughts on bringing the actual tutorial as a sub-directory of the React project as opposed to being in a separate repository? I am not even sure myself if that's the best way to go about it, but at least things wouldn't be going out of sync as they are now.

If you look at the source code for the tutorial and compare it to the tutorial instructions in the React repo there are some striking differences which might catch people out.

The major drawback with this approach would be having to clone the entire React source when you want to get just the tutorial, but I actually don't think that's a bad idea. It might even encourage people to have a poke about the source code, which is always a good thing.
