### ISSUE TITLE
add findRenderedComponentsWithAttr

### ISSUE THREAD

**Issue by fourcolors** [facebook/react#4380]
Hello party people,

I'd like to find dom nodes by attributes (specifically aria-selected). Use case is testing keyboard navigation around dom nodes to ensure my component is accessible.

Any thoughts on this? I try to avoid refs as much as possible and classes aren't specific enough to the state of the element. 

Any thoughts? If I made a commit would it be accepted?

Thanks!

**Comment by fourcolors** [comment]
UPDATE: 

So I just realized I can accomplish this same task with 
    findAllInRenderedTree
so this would really be sugar on top of the findAllInRenderedTree. In the fight for simplicity, I'm not sure if it should be added anymore.

**Comment by jimfb** [comment]
cc @zpao and @spicyj

**Comment by jimfb** [comment]
Also, if we do this, can we PLEASE call it `findRenderedComponentsWithAttr`.  https://github.com/facebook/react/issues/3951

**Comment by spicyj** [comment]
We're not adding more methods like this these days. There've been a bunch of issues about it. Use findAllInRenderedTree like you found.
