### ISSUE TITLE
Unexpected behavior of `findRenderedDOMComponentWithTag` in React 0.14-beta1

### ISSUE THREAD

**Issue by globexdesigns** [facebook/react#4388]
After migrating from 0.13 to 0.14-beta1, some of our unit tests are reporting false positive failures. It seems as though `findRenderedDOMComponentWithTag` is no longer able to find elements inside components.

```javascript
// Create simple component
const test = React.createClass({
	render: () => {
		return <div><svg /></div>;
	}
});

// Render into document
const MyElement = ReactTestUtils.renderIntoDocument(<test />);

// Make sure component has an SVG element
const svg = ReactTestUtils.findRenderedDOMComponentWithTag(MyElement, 'svg');
// OOPS! This fails in 0.14 with:
// > Did not find exactly one match for tag:svg

// However, this works just fine
console.log(findDOMNode(MyElement).childNodes[0]);
// => Returns "<svg/>" element
```

**Comment by niole** [comment]
Isn't findRenderedDOMComponentWithTag's first argument supposed to be the name of the react component tree that you've defined (MyElement)?

**Comment by globexdesigns** [comment]
@niole Oops. That was a typo in my code sample. I've corrected it.

**Comment by dmatteo** [comment]
The problem was that `svg` was passed as a lowerCase string to `scryRenderedDOMComponentsWithTag`.

Converting it to upperCase before hand doesn't hurt anyway.
What do you guys think?
