### ISSUE TITLE
re-opening #4364

### ISSUE THREAD

**Issue by kulicuu** [facebook/react#4390]
#4364 
Another day of development, have run into more Chromium problems. (Firefox still working fine)
https://github.com/Terebinth/Vickers (MineSweeper)
It renders okay but gameplay graphics behaviour is unpredictable and doing strange things in Chromium. Like revealing /clicking on a mine turns every other tile black, repeatedly toggling flags with right-click causes tiles to go transparent. etc

**Comment by zpao** [comment]
Closing so we can keep discussion in 1 place
