### ISSUE TITLE
this.state is empty in render despite getInitialState being defined correctly

### ISSUE THREAD

**Issue by NicholasGW** [facebook/react#4391]
Hey All,

I'll try my best to explain the scenario, as making a fiddle of the smallest possible case might be hard. Essentially, I have a SPA using React-Router. I'm currently getting a strange behavior in specifically one version of Firefox (31.4esr). 

I have two sidebar icons which trigger a change in routes, navigating to a new page. On occasion when I switch quickly between them, I'm getting an error that this.state.list is undefined(this is a list that I populate a dropdown with).

The issue is, upon debugging, console.log(this.state) is returning an empty object just before the call (that errors) to this.state.list happens in my render method. However, I have list defined in getInitialState (along with a bunch of other state variables) and so this.state definitely shouldn't be empty.

The only thing I could think of that would be causing this is if due to the quick switching there is some confusion with mounting/unmounting of components and my component still thinks it is mounted, so skips the getInitialState and goes ahead and tries to render. Either that or some bug in React-Router.

Any thoughts? Thanks in advance for the help!

Nick

P.S I should reiterate this also only occurs very rarely during quick switching, and normally the componentDidMount -> getInitialState -> render occurs as expected, so it is not simply an error in how my getInitialState is written etc.

Edit: Using React 0.13.3 and React router 0.13.3

**Comment by brigand** [comment]
Issues here are for development of react itself, but if you're looking for help StackOverflow is a good place to ask. I suggest including the component where you get this error, and any code responsible for the data in `this.state.list`.

It's possible that a bug in that firefox version is causing react, react-router, your other dependencies, or your own code to behave incorrectly, but you need to narrow it down before anything can be done about it.

Best of luck; sounds like a tough issue to track down.

**Comment by NicholasGW** [comment]
Thanks for the reply...I'll post to SO and try and narrow it down in the event it ends up being a React bug (which I doubt considering the specific version of FF). Cheers!
