### ISSUE TITLE
Render to string is slow

### ISSUE THREAD

**Issue by tinganho** [facebook/react#4392]
I just switched out a mustache-like templating to `react` in an isomorhpic framework I'm building.

I'm rendering it on the server side I just noticed it taking 15-16ms to render a whole page. Usually it is instant roughly 1ms.

This is the line after I got all the props:
```typescript
console.time('render')
let html = renderToString(createElement(this.currentPlatform.document.component, this.currentPlatform.documentProps));
console.timeEnd('render');
```

I thought `renderToString` will cause all components to call render function and then just concatenate the strings? Or is it something more under the hood?

**Comment by tinganho** [comment]
Just got little bit faster with the pure render mixin. But I still think it is too slow for my use case.

**Comment by tinganho** [comment]
Ok pure render mixin worked. It was just the first evaluation being slow. Averaging 4 ms now.

**Comment by dcousens** [comment]
@tinganho sharing how you did the pure render mixin might be useful to others,  up to you though :)

**Comment by tinganho** [comment]
I just add it to the instance property `mixin` array nothing special.
