### ISSUE TITLE
PureRender as a decorator

### ISSUE THREAD

**Issue by tinganho** [facebook/react#4394]
I'm just wondering why PureRenderMixin is not implemented as a decorator? I think importing it as another lib is overkill. 

```typescript
@React.pureRender
render() {
    ...
}
```

Also aren't 99% of all use cases a pure render? If that is the case why isn't it the default behavior?

**Comment by hbrls** [comment]
That's an ES7 thing I think. React turned to babel only days before. I don't think it's available now.

**Comment by zpao** [comment]
We don't use decorators. Maybe after the spec has stabalized and it's on its way to standardization.

**Comment by brigand** [comment]
> If that is the case why isn't it the default behavior?

If the component isn't compatible with PureRender, then it just appears to not be updating, which is very confusing. This is especially confusing to new users which might use e.g. `new Date` or `Math.random()` in render, along with anyone using mutable objects.

**Comment by dcousens** [comment]
@brigand to be fair,  my initial interpretation of `React` was that it was pure by default, it was confusing to me that `Math.random()` *was* working at all given my props were the same.
