### ISSUE TITLE
No `react-dom/server` file

### ISSUE THREAD

**Issue by tinganho** [facebook/react#4396]
I get this warning on the latest beta:
```
Warning: `require("react").renderToString` is deprecated. Please use `require("react-dom/server").renderToString` instead.
```
And I npm installed `react-dom` and did as the warning text:
```
Error: Cannot find module 'react-dom/server'
```

**Comment by zpao** [comment]
`npm install react-dom@0.14.0-beta1`. It's not published to the `latest` tag yet.

**Comment by a-x-** [comment]
could you note this in README#installation?
