### ISSUE TITLE
React throws when rendering some HTML tags inside Windows 8 app.

### ISSUE THREAD

**Issue by joshduck** [facebook/react#441]
When using React in a JavaScript-based Windows 8 app, some HTML tags will cause an error to be thrown during mounting. For example an audio tag, as shown [here](http://jsfiddle.net/WPn3A/) causes the following error.

> 0x800c001c - JavaScript runtime error: Unable to add dynamic content. A script attempted to inject dynamic content, or elements previously modified dynamically, that might be unsafe. For example, using the innerHTML property to add script or malformed HTML will generate this exception. Use the toStaticHTML method to filter dynamic content, or explicitly create elements and attributes with a method such as createElement.  For more information, see http://go.microsoft.com/fwlink/?LinkID=247104.

This is not a hugely pressing issue, but we should probably offer some way of using window.toStaticHTML where it's available.

**Comment by stkb** [comment]
I thought I'd go ahead and create a pull request (#2799) to fix this. It works by wrapping the innerHTML-setting code in execUnsafeLocalFunction().
