### ISSUE TITLE
How could I know when dangerouslySetInnerHTML set the innerHTML?

### ISSUE THREAD

**Issue by leozdgao** [facebook/react#4415]
I use [marked](https://github.com/chjj/marked) to parse the article, and get the html string of the article, then I use `dangerouslySetInnerHTML` to insert it to the DOM. After that, I want to use my [autoIndexer](https://github.com/leozdgao/autoindexer.git) to generate index for this article.

Here is the code:

```javascript
let About = React.createClass({
  componentDidMount: function() {
    let node = React.findDOMNode(this.refs.testNode);
    console.log(node.children.length);  // what? 0, which cause my autoIndexer don't work.
  },
  render() {
    return (
      <div>
        <Link to="info">Info</Link>
        <div ref="testNode" dangerouslySetInnerHTML={{__html: this.props.content}}></div>
      </div>
    );
  }
});
```

I try to get the length of content's children node, but it is 0. Which means the innerHTML hasn't set at this time?

But check this test code:

```javascript
let About = React.createClass({
  componentDidMount: function() {
    let node = React.findDOMNode(this.refs.testNode);
    console.log(node.children.length);  // yes, it is 1
  },
  render() {
    return (
      <div>
        <Link to="info">Info</Link>
        <div ref="testNode" dangerouslySetInnerHTML={{__html: "<h2>Test</h2>"}}></div>
      </div>
    );
  }
});
```

My content is longer than `<h2>Test</h2>`. So it confused me, how could I know when dangerouslySetInnerHTML set the innerHTML? It seems the short html was set when `componentDidMount` invoked, but longer html was not set when `componentDidMount` invoked.

**Comment by cody** [comment]
I don't think the length of the content is the problem. More likely the content of `this.props.content` is not what you expect it to be. Either it actually has no children or the browser moves stuff around to fix illegal html. Hard to say without a fiddle.

**Comment by jimfb** [comment]
@leozdgao I agree with @cody, that seems likely to be the issue.  I tried to reproduce based on the info you provided, but couldn't find any bug.  If you can provide a fiddle, we can investigate further.

**Comment by leozdgao** [comment]
@cody @jimfb Thanks, I think I figured it out. I request my content asynchronously, so during `componentDidMount `, the children of content is 0 because content is an empty string. Now I use `componentDidUpdate` to solve this issue, because at this time, the content is ready.
