### ISSUE TITLE
input tag is rendered not self closing

### ISSUE THREAD

**Issue by Yeti-or** [facebook/react#4417]
https://jsfiddle.net/69z2wepo/12235/
```
actual: <input value="World" >
expected: <input value="World" />
```

**Comment by yaycmyk** [comment]
@Yeti-or `input` is a void element, so it doesn't need one: http://www.w3.org/html/wg/drafts/html/master/syntax.html#void-elements

**Comment by cody** [comment]
In 0.14 this is fixed, the closing tag gets rendered. At least with renderToString(). Browsers have their own mind, some don't show the closing tag. I think firefox does `<input></input>`.

**Comment by zpao** [comment]
@cody is correct, will be in 0.14.

**Comment by mdibaiee** [comment]
Hey, how can I get this right now? Using `0.14.0-alpha{1,2,3}` doesn't seem to work. Is there any way to workaround this? Couldn't succeed using `renderAsString` because `componentDidMounth` will not fire that way.

**Comment by cody** [comment]
@mdibaiee 
If the pre-release don't work for you, then my guess is that the final version won't work neither. With `renderToString` it works, because React does everything alone. But with `render` at some point the browser takes over and different browsers produce different markup.

**Comment by mdibaiee** [comment]
@cody: No, `renderToString` doesn't work either, I'm hacking it using `replace`. This way react won't work on Firefox at all, good job.

**Comment by jimfb** [comment]
@mdibaiee Maybe I'm miss-understanding the question, but using React 0.14-beta2...

```console.log(React.renderToString(<input type="text" />));```

renders to...
```<input type="text" data-reactid=".0" data-react-checksum="159780004"/>```

On Firefox.  Why are you using the alpha instead of the beta release?

**Comment by mdibaiee** [comment]
I'm using the `react-tools` module, and there is not `0.14-beta2`, only alphas.

NPM's output:
```
npm ERR! notarget No compatible version found: react-tools@'>=0.14.0 <0.15.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.10.0-rc1","0.11.0-rc1","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.5.0","0.5.1","0.4.2","0.5.2","0.8.0","0.9.0-rc1","0.9.0","0.10.0-rc1","0.10.0","0.11.0-rc1","0.11.0","0.11.1","0.11.2","0.12.0-rc1","0.12.0","0.12.1","0.12.2","0.13.0-alpha.1","0.13.0-alpha.2","0.13.0-beta.1","0.13.0-beta.2","0.13.0-rc1","0.13.0-rc2","0.13.0","0.13.1","0.13.2","0.13.3","0.14.0-alpha1","0.14.0-alpha2","0.14.0-alpha3"]
```

**Comment by jimfb** [comment]
@mdibaiee Ah, this might help you: https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

**Comment by mdibaiee** [comment]
@jimfb: Oh, I wasn't aware of this, thanks for pointing it out.

**Comment by mdibaiee** [comment]
Okay, using Babel right now, but I can't find a way to use the beta features of the `react` transformer. Any ideas?

**Comment by zpao** [comment]
@mdibaiee - that's a great question to ask in a babel support group. It's not clear to me if they removed some of the optimizations or if they just bury mentions of them on the site .

**Comment by sebmck** [comment]
I'm not sure how React rendering a tag incorrectly is related to Babel?

**Comment by zpao** [comment]
@sebmck - not the original issue, but the last question in the thread, which is specifically about using Babel.

**Comment by sebmck** [comment]
@zpao Whoop sorry, @mdibaiee just came into the chat pointing to this issue wanting to know how to install the beta version of Babel that would fix this issue.

**Comment by mdibaiee** [comment]
It seems it was not Firefox's problem, but I was using XHTML instead of HTML, which has it's own rules. In fact I was developing a Firefox add-on, sorry about the inconvenience.

**Comment by ArcaneEngineer** [comment]
This is not fixed. Input it still displaying as <input ...> and not <input></input> (ideal) nor <input/>.

I need to export an <svg> that has embedded <foreignObject>s containing <input> tags. Instead of being able to parse the whole thing has valid XML/SVG, I'm forced to amend those input tags as a post-process, because they are not properly closed, and XML parsers choke on this.

Please re-open.
