### ISSUE TITLE
Lint unnecessarily complains about trailing comma

### ISSUE THREAD

**Issue by spicyj** [facebook/react#4428]
I tried to write

```
var foo = [{
  bar: 1,
  baz: 2,
}];
```

but our linter wants a comma after the `}`. Kind of annoying. Anything we can do here?

**Comment by kiki-le-singe** [comment]
@spicyj 

This must be configurable in the .eslintrc file.

This should help you: [comma-dangle](http://eslint.org/docs/rules/comma-dangle)

**Comment by spicyj** [comment]
@kiki-le-singe We do want to require commas when on separate lines though.

**Comment by bgw** [comment]
@spicyj I think updating eslint should solve it: eslint/eslint#2778

**Comment by dcousens** [comment]
@spicyj perhaps this also shows an inconsistency in your formatting? Haha

**Comment by spicyj** [comment]
@bgw Thanks, good find.

@dcousens I don't think so. The goal of this lint rule is to make it possible to add another item to a list without changing what was previously the last line. In my example, that holds true for the object because I have the trailing comma, but it doesn't hold true for the array because of the way I've formatted it; this holds true regardless of whether a trailing comma is added. Since I know this array will only ever have one element, I think formatting it like this is clearest instead of adding another level of indentation.

**Comment by dcousens** [comment]
@spicyj that is fair enough,  however in the spirit of the discussion,  I'd argue that:

>  Since I know this array will only ever have one element, I think formatting it like this is clearest instead of adding another level of indentation.

Is a special case for something that is an oddity anyway.
If you only *ever* intend to use 1 element,  why are you forced to use a data structure that is implicitly used for collections (`N >= 0` vs `N = 1`).

I guess it depends how much you want to separate your syntax from the underlying type system.

**Comment by spicyj** [comment]
This particular case was for a unit test of a function that takes a list of operations:

https://github.com/facebook/react/blob/57d14ec33a3393c8d37f9230428c9ac35a5c8059/src/renderers/dom/client/__tests__/ReactDOMIDOperations-test.js#L49

Just as `[1]` and `[1, 2, 3]` don't require trailing commas, I don't want one here either. There's no use discussing more over this.
