### ISSUE TITLE
When file exports a single class, displayName should be eq. to the file name

### ISSUE THREAD

**Issue by gajus** [facebook/react#4429]
When a single file is used per module, most modules end up with derived `displayName` equal to `module.exports`. It would make sense to use file name instead, e.g.

```js
// PropTypes.js
/** @jsx React.DOM */

'use strict';

var React = require('react');

module.exports = React.createClass({
    render: function () {
        return <div />;
    }
});
```

In this case, `displayName` should be `PropTypes`.

**Comment by BerkeleyTrue** [comment]
How could you accomplish this? React has no idea what the filename is from the createClass method. I don't think this should be something react should worry about. This is something for UserLand to implement. For instance, as a babel-plugin.

**Comment by gajus** [comment]
The same way it knows to what variable it is assigned. Though, I should have filed this under JSX. It is JSX that infer's the class's `displayName`.

**Comment by BerkeleyTrue** [comment]
Yes that would be the transformer, and the jsx transformer has been deprecated in favor of babel. The most likely candidate would be a plugin for babel, or you can try asking the babel team to implement it.

**Comment by lacedub** [comment]
export default function ({ Plugin, types: t }) {
  return new Plugin("foo-bar", {
    visitor: {
      // visitors
    }
  });
}
https://networks.nokia.com/

**Comment by zpao** [comment]
Yea, we're killing react-tools / jsxtransformer so any requests like this should end over in babel or whatever other transformer you happen to use.

**Comment by BerkeleyTrue** [comment]
I think this would be the most apropriate place to put this -> https://github.com/babel-plugins/babel-plugin-react-display-name

**Comment by gajus** [comment]
Thank you. Where can I read about react-tools / jsxtransformer being deprecated in favour of babel plugins?

**Comment by gajus** [comment]
https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html
