### ISSUE TITLE
Component must raise an error if an unknown property is passed

### ISSUE THREAD

**Issue by gajus** [facebook/react#4430]
Component declaration should contain a whitelist of properties, e.g. it could require that you list the property name under `propTypes` even if it is assigned `null` (that could mean "any type", a broader version of `React.PropTypes.node`).

If a property that is not defined in `propTypes` is passed to a component declaration an error must be raised.

This would provide several benefits:

* Would help to catch TYPOs
* Would promote type declaration
* Would prevent orphan properties

## Catching Typos

Suppose a component that generates a different type of input depending on a `type` value. This component has a default `type` value "text".

```js
var Input = React.createClass({
    getDefaultProps: function () {
        return {
            type: 'text'
        }
    },
    render: function () {
        // Different logic defending on the type name.
        // this.props.type === 'text'

        return <div />;
    }
});
```

If `Input` instance declaration is defined with a typo in the `type` property, it would not be an obvious error.

```jsx
<Input tupe='password' />
```

Raising an error "Unknown property 'tupe'." would help to catch the error.

## Promoting Type Declaration

If property names are required to be listed under `propTypes`, it requires little extra effort to define their types.

```js
var Input = React.createClass({
    propTypes: {
        type: React.PropTypes.string,
        // type: null
    },
    render: function () {
        return <div />;
    }
});
```

Furthermore, we are used to think about *code-length* in terms of the lines of code. The fact that type declaration at the moment adds extra lines might be discouraging some developers from doing it. This thought is only to boost the importance of the earlier argument.

## Preventing Orphan Properties

This is especially relevant when using spread operator inheritance.

Suppose an instance of a simple (`Input`) component is declared using a spread operator.

```jsx
<Input {...generalFormProps} name='foo' />
```

, where `generalFormProps` is an object containing many properties of which just some apply to `Input` component. In this scenario, each `Input` instance would have a copy of those property values (dead weight).

**Comment by yaycmyk** [comment]
Disagree. Most people I know strip out propTypes in production code and this would cause issues unless the verification was only `NODE_ENV !== 'production'`

**Comment by gajus** [comment]
It could be the latter. This suggestion is less about forcing type checking and more about whitelisting property names.

**Comment by yaycmyk** [comment]
@gajus The other place where this becomes untenable are components that allow the full breadth of React-supported attributes using the spread operator. For instance, I have a few components that allow the consumer to set `disabled`, `name`, etc. as props and I simply apply them to the rendered element.

```
render() {
    return (
        <input {...this.props} className='blah' />
    );
}
```

It's not reasonable to have to add every possible React attribute to `propTypes`

**Comment by gajus** [comment]
> It's not reasonable to have to add every possible React attribute to propTypes

It is completely reasonable. You/the consumer would need to have an object that defines all possible attribute names, including `data-*` variations.

**Comment by syranide** [comment]
Personally I agree that this should exist one way or another. `props` is not a Map-like structure, it should really only support a fixed set of properties and if there are any unexpected it's most likely a mistake, so please give me a warning! Perhaps this could even happen automatically in the future as part of Flow.

**Comment by yaycmyk** [comment]
@syranide I thought there were plans to implement `props` as an immutable map? or to accept one

**Comment by jaredly** [comment]
I agree this should exist, but maybe it should be opt-in (per-component)? Or at least let there be an opt-out.

**Comment by yaycmyk** [comment]
Opt-in would smooth over the concern I raised earlier if this is highly desired.

**Comment by syranide** [comment]
@yaycmyk I meant you shouldn't treat it like a Map-structure, `props` just like `state` *should* only have a fixed set of properties as specified by the component, they should not be dynamically indexed. Hence, any property provided that isn't in that list is technically an error because it would never be read or used for anything.

**Comment by yaycmyk** [comment]
@syranide Isn't it very common to define wrapper components and then seamlessly pass props to the wrapped child though via spread? An opt-out would solve the issue, but having to redefine the proptypes at each layer would be tedious.

**Comment by jaredly** [comment]
@yaycmyk in the wrapping case, you could so

```
MyWrapper.propTypes = {
  ...WrappedComponent.propTypes,
  myNewProp: stuff
};
```

**Comment by solomonhawk** [comment]
Interesting discussion. I messed around with a related idea awhile back in probably it's most simple form: https://gist.github.com/solomonhawk/22303bf6197d4eb3ff43

I wonder if this should just be a standard practice/convention as opposed to baked into the library.

**Comment by eberhara** [comment]
Agreed!!! For a beta version, we could have some kind of parameter to enforce this whitelist on the propTypes. For a future version, it could (or not) become required depending on the community acceptance.

**Comment by spiritix** [comment]
There should definitively be some kind of property initialization / whitelisting. But a property should only be owned by exactly one component. Other components just passing down the property should have some kind of protected channel.

**Comment by gajus** [comment]
I have developed a higher order component that does this.

https://github.com/gajus/react-strict-prop-types

**Comment by gajus** [comment]
This is a duplicate of https://github.com/facebook/react/issues/1587.
