### ISSUE TITLE
mouseEvent doesn't have offsetX/offsetY

### ISSUE THREAD

**Issue by evgenyrodionov** [facebook/react#4431]
I try get position of click relative to element, but event doesn't have offsetX.

    onClick(e) {
      console.log(e.offsetX) // returns undefined
      console.log(e.target.offsetX) // returns undefined
    }

    render() {
      return <img src='http://placehold.it/1000x500' onClick={this.onClick} />
    }

How I can get position of click in element?

**Comment by theaqua** [comment]
Oh, well, I see.
I get it from `e.nativeEvent.offsetX`. Is it right approach?

**Comment by cody** [comment]
This shows all available values:
```js
onClick(event) {
  event.persist();
  console.log(event);
}
```
Using the `nativeEvent` is fine.

**Comment by theaqua** [comment]
@cody thanks!

**Comment by yaycmyk** [comment]
:+1: Please close if you're happy with the answer and there is no found bug(s).

**Comment by spicyj** [comment]
You probably want pageX or clientX and if you want it relative to another element you can use getBoundingClientRect on that element – if you do that it should work well across browsers.

**Comment by glenjamin** [comment]
`offsetX/Y` appear to be on the standards track and supported in all major browsers.

Any chance of adding them into React - perhaps with a `getBoundingClientRect` shim for browsers which don't support it?

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX

**Comment by spicyj** [comment]
That seems reasonable enough if we can do it with no performance compromise so I'll reopen this, but it won't be a high priority for us.

**Comment by git-richard** [comment]
I did some work on this and it would require a polyfill. As a property in SyntheticMouseEvent it would execute for every mouse event, which would have a performance impact. It could be added as a method that executed on-demand but then it wouldn't match the native MouseEvent interface.

**Comment by syranide** [comment]
#7011

**Comment by gaearon** [comment]
I’ll close since we decided to not merge #7011.

**Comment by Jarred-Sumner** [comment]
As of 2020, this doesn't seem to need a polyfill. But `SyntheticEvent`'s `MouseEvent` doesn't have `offsetX` or `offsetY`

I can submit a PR if you want

https://caniuse.com/#feat=mdn-api_mouseevent_offsetx

![image](https://user-images.githubusercontent.com/709451/86724004-44baec80-bfdd-11ea-8d18-58439c1280d2.png)

**Comment by amerllica** [comment]
@gaearon, Why ReactJs mouseEvent doesn't have `which`, `offsetX`, `offsetY` and etc?

Why the Facebook developers add them into `e.nativeEvent`?

**Comment by mlajtos** [comment]
> Why the Facebook developers add them into `e.nativeEvent`?

@amerllica `e.nativeEvent` is created by the browser, so if there is `e.nativeEvent.offsetX` the browser supports it. Why the attribute does not propagate to synthetic event, that is question to React team.

**Comment by acenturyandabit** [comment]
Can we reopen this? offsetX would make it a lot easier to implemenet encapsulated event handlers.

**Comment by Patilritik** [comment]
Is there any solution offer by react , other then the  getBoundingClientRect and e.nativeEvent for handling the mouse event ??

**Comment by TomasHubelbauer** [comment]
This was closed in 2016. It's 2024 and `offsetX`/`offsetY` is baseline level of support:
- https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX
- https://caniuse.com/mdn-api_mouseevent_offsetx
Can this be re-opened?
