### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [facebook/react#4434]
Hey there React-ors,

I am working on assessing, cataloging, and triaging library compat with Microsoft Edge. Do you know the version compat range for React in Edge? Are all versions fully operable in Edge? Also, do you have any bugs that block features or compat I can help with or escalate?

**Comment by zpao** [comment]
No issues with Edge that I'm aware of, but I don't know that we've done extensive testing. cc @spicyj @sebmarkbage

**Comment by spicyj** [comment]
I also don't know of any incompatibilities in any version, and I don't think we currently have any workarounds for Edge.

**Comment by csuwildcat** [comment]
"I also don't know of any incompatibilities in any version, and I don't think we currently have any workarounds for Edge." - music to my ears, fellas! Do let me know if you have any failing test runs over the next week, or after the RTM arrives on July 29th; I will be your point of contact to address any issues that arise.

**Comment by jimfb** [comment]
Great, thanks @csuwildcat!  I'm going to close this issue, since there are no known bugs at this time.  We'll be sure to ping you if we discover anything :).
