### ISSUE TITLE
LinkedValueUtils:requestOnChange event.target is undefined

### ISSUE THREAD

**Issue by sarink** [facebook/react#4438]
On 0.14-beta1, the following example does not work:

````
    var WithoutMixin = React.createClass({
        getInitialState: function() {
            return {message: 'Hello!'};
        },
        handleChange: function(newValue) {
            this.setState({message: newValue});
        },
        render: function() {
            var valueLink = {
                value: this.state.message,
                requestChange: this.handleChange
            };
            return <input type="text" valueLink={valueLink} />;
        }
    });
````

The console shows ``Uncaught TypeError: Cannot read property 'value' of undefined`` when typing into the input field

fwiw, ``event.currentTarget`` seems to be set correctly.

Is there a workaround or fix for this?

Thanks

**Comment by zpao** [comment]
This was fixed in #4311 (after beta 1). currentTarget or event.nativeEvent.target should work.
