### ISSUE TITLE
Support for bgcolor on td tag for HTML emails

### ISSUE THREAD

**Issue by honki91** [facebook/react#4439]
It seems that for widest email client support using the bgcolor attribute on td tags is the best route: https://litmus.com/blog/background-colors-html-email

I would like to write and render my emails in React, since building up the email in components would alleviate some of the pains of using tables for layout and use of inline styles via js would be helpful. But the inability to use the bgcolor attribute is a road block. Would this be ever supported in the future?

**Comment by zpao** [comment]
Is that better than using `style={backgroundColor}`? The article didn't really explain (just said use `bgcolor`).

Anyway, `bgcolor` will be supported if/when we switch to allowing arbitrary props on DOM elements. I don't really want to explicitly support something removed from the spec 16 years ago so we won't add it to our supported attributes list right now.
