### ISSUE TITLE
Request for support of full range of SVG attributes in JSX

### ISSUE THREAD

**Issue by JofArnold** [facebook/react#4441]
Noteworthy missing attributes include `stroke-miterlimit` and `stroke-linejoin`.

**Comment by JofArnold** [comment]
Possible workaround, of course, is `dangerouslySetInnerHTML`

**Comment by JofArnold** [comment]
Confirmed: this is a reasonable workaround

**Comment by zpao** [comment]
Going to close and just point at #1657 where we're tracking discussion about SVG
