### ISSUE TITLE
Contents of <script> tags are mis-quoted

### ISSUE THREAD

**Issue by ianb** [facebook/react#4446]
If you do something like:

```javascript
React.renderToStaticMarkup(React.DOM.script({}, ['alert("hey")']))
```

...the output is `'<script>alert(&quot;hey&quot;)</script>'`

It should be `'<script>alert("hey")</script>'`

Script elements have CDATA content, and cannot be quoted.

**Comment by zpao** [comment]
Yea, we don't special case script content so it runs through the same escaping code as everything else. We strongly recommend using `dangerouslySetInnerHTML: {__html: 'alert("hey")'}`

I don't think we have plans to change this escaping behavior.
