### ISSUE TITLE
Make JSX transformer string quoting configurable

### ISSUE THREAD

**Issue by pgherveou** [facebook/react#445]
Hello guys 
First of all Great project :)

I just tweaked my linter plugin (sublinter) to use react tools and transform jsx code before linting

I just have a small issue though the code generated use double quote strings and thus as we are enforcing single quote string, this produce an error.

Can we enforce single string on the transformer?

```
/** @jsx React.DOM */
var React = require('react');

module.exports = React.renderComponent(
  <h1>foo</h1>,
  document.getElementById('example')
);
```

generates   React.DOM.h1(null, "foo") instead of desired   React.DOM.h1(null, 'foo'),

``` js

/** @jsx React.DOM */
var React = require('react');

module.exports = React.renderComponent(
  React.DOM.h1(null, "foo"),
  document.getElementById('example')
);
```

**Comment by alexmcmillan** [comment]
+1
