### ISSUE TITLE
Error inside Render function don't show error on console

### ISSUE THREAD

**Issue by gsantome** [facebook/react#4454]
Hello, when i updated to the latest version of react everything was wonderful but I started to notice something really important... Sometime the components that i created weren't there... so I started to debug my code and I found i made an exception inside the render function, something like 

This is an stupid example but it only to show an example...
```
var object1 = undefined;
console.log(object1.name);
```
So i never saw that error on the console... I just don't see anything...

This error was making me crazy... so i stated to debug React code and i found something and i don't know if its a bug or i need to solve it in a different way...

inside react.js

```
_renderValidatedComponent: function(childContext) {
    var renderedComponent;
    var previousContext = ReactContext.current;
    ReactContext.current = this._mergeChildContext(
      this._currentElement._context,
      childContext
    );
    ReactCurrentOwner.current = this;
    try {
      renderedComponent =
        this._renderValidatedComponentWithoutOwnerOrContext();
    }
    finally {
      ReactContext.current = previousContext;
      ReactCurrentOwner.current = null;
    }
```

here we can see the "try" haven't got a "catch"... after i added the "catch" the console started to show the errors inside my render function...

```
_renderValidatedComponent: function(childContext) {
    var renderedComponent;
    var previousContext = ReactContext.current;
    ReactContext.current = this._mergeChildContext(
      this._currentElement._context,
      childContext
    );
    ReactCurrentOwner.current = this;
    try {
      renderedComponent =
        this._renderValidatedComponentWithoutOwnerOrContext();
    }
    catch (ex) {
      console.error(ex);
    }
    finally {
      ReactContext.current = previousContext;
      ReactCurrentOwner.current = null;
    }
```

I hope this is ok and its not my mistake...

Thanks!

**Comment by unphased** [comment]
It would be great if we could get some opinions from React devs on (a) why no `catch` block and (b) how safe is it for us to add this catch block in our dev build in order to not have rendering exceptions eaten up.

**Comment by jimfb** [comment]
Regarding number 1:  See: #4368, #2626. #2912, #4199, #2665. etc.  No catch block because we don't want to swallow the exception.  Exceptions are good/useful for debugging.
Regarding number 2: I wouldn't recommend changing the source code, as it would be difficult to predict the ramifications of such changes.  Would be much better to provide us with a test case that demonstrates the issue so we can fix it and test internally.

I am unable to reproduce.  If you're able to provide us with a simple testcase/example, I'd be happy to re-open this issue and investigate.
