### ISSUE TITLE
Warning does not specify which transition timed out when a timeout occurs (ReactCSSTransitionGroupChild)

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#4465]
It would be great if this warning would specify what transitionend event its looking for, i.e. the transitionName

```
Warning: transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition.
```

**Comment by jedwards1211** [comment]
+1, I've seen a lot of React warnings and errors that don't specify what component they have to do with or any other context.  If all of the warnings and errors were contextualized it would be a huge win!

**Comment by spicyj** [comment]
@jedwards1211 We do our best to include context. Feel free to file bugs for others that are unclear.

**Comment by xiaoqiang730730** [comment]
Does not  react  supply 'build/react-with-addons.js'  now? 

I can not run index.html which is in 'example transitions'.

**Comment by spicyj** [comment]
#4561 will probably make this unnecessary.

**Comment by ccorcos** [comment]
awesome! thanks for the heads up :+1:

**Comment by zpao** [comment]
#4561 landed so closing out. Should be much better.

**Comment by ccorcos** [comment]
any ETA on when this will be released?

**Comment by spicyj** [comment]
The fix is in the RC that we released a couple weeks ago; the final release should be soon.
