### ISSUE TITLE
Implement sticky listview headers 

### ISSUE THREAD

**Issue by cht8687** [facebook/react#4468]
When scroll the listview in iOS/Android apps, we see the headers stays on top and be replaced by newest section headers when we scroll further. In react native, it does support this feature.

After investigation, I found there are a few jQuery plugins or React Components modules that we can use to achieve this effect in react project.

Which library/plugin/React Components do you recommend to use?

**Comment by spicyj** [comment]
Please reserve GitHub issues for bug reports and feature requests in React only.
