### ISSUE TITLE
Problem with 1.4.0-beta1 instance of React

### ISSUE THREAD

**Issue by niole** [facebook/react#4475]
My 1.4.0-beta1 instance of React is an empty object. During installation, I ran into problems with `npm install` because of errors surrounding `"eslint-plugin-react-internal": "file:eslint-rules"`, as in it doesn't exist in the npm package registry. I deleted it from the package.json and everything ran smoothly from there. But each instance of React now is an empty object. I'm using linux version 14.04. My app's build pipeline includes gulp and commonjs

**Comment by dozoisch** [comment]
React 0.14-beta1*

`"eslint-plugin-react-internal": "file:eslint-rules",` is a devDependency so you shouldn't be installing it normally.

**Comment by zpao** [comment]
Can you explain how you installed react? There's pretty much no way this is happening unless you `npm link`ed react (but linked from the wrong folder, the root would be react-tools).

**Comment by niole** [comment]
I followed the readme. I cloned the repo into my node_modules directory and
followed installation instructions from there.

**Comment by zpao** [comment]
I don't know where you read that, it shouldn't say that in any of our readmes.

If you're talking about `react`, you should just be doing `npm install react` (`react@0.14.0-beta1` if you want the beta). Unless you are working on patch to React you should not be cloning and building.

If you're talking about `eslint-plugin-react-internal`, you shouldn't be using that. Those our custom rules for linting our own code.

**Comment by niole** [comment]
Oh, I just made a big assumption there. Thanks for pointing me in the right
direction.

**Comment by gfogle** [comment]
@zpao - if we are trying to submit a PR... its going to fail the `npm install`... or did I misread your reply?

**Comment by spicyj** [comment]
If you are trying to submit a PR, clone the repo into a separate folder and follow the instructions in the README for building. You should probably never clone this repo into your node_modules folder.

**Comment by zpao** [comment]
@gfogle `npm install` shouldn't fail if you're submitting a PR. I meant that nobody should be be building their own copy of React unless they are submitting a PR (or are an expert)

**Comment by niole** [comment]
The readme should explicitly say how to use the beta version. Not every
open source project is npm installable and you might have to build it
yourself

**Comment by spicyj** [comment]
We only support npm for this beta. The blog post explains how to install it from npm:

http://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html

For the final release we'll have a browser build, as with all our releases.

**Comment by gfogle** [comment]
`fork + clone + npm install` still seems to fail OOB because of the react-internal module. if you kill that dep and do an `npm install` its kosher. then just re-checkout the package file. this also seems to break `grunt lint` but i guess that should be expected w/o react-internal.

**Comment by zpao** [comment]
npm > 2 is required (the `file:` dep syntax was introduced then). I'll make sure this is documented.
