### ISSUE TITLE
event.target not set by onChange event

### ISSUE THREAD

**Issue by pmast** [facebook/react#4479]
In version 0.14.0-beta1 the `event.target` is not set by the `onChange` event. Only currentTarget is set. The example works as expected in version 0.13.3.

https://jsbin.com/yadezugoro/edit?html,console,output

Is this intentional?

**Comment by cody** [comment]
A nasty bug, but it was fixed in master already: #4311

**Comment by jimfb** [comment]
Thanks @cody.  Closing as per #4311.
