### ISSUE TITLE
Implement declarative setState handling

### ISSUE THREAD

**Issue by serle** [facebook/react#4487]
I depend an immutable library to store my properties and trigger/invoke a react re-render on update of the properties. I often find that I need to change properties and corresponding state together (in one event handler function) in order to keep them synchronised. In these scenarios it would be great to be able to let the immutable library alone be responsible for triggering the re-render process and turn off the automatic re-rendering in response to setState is calls. Note I have thought of moving my setState out to componentWillRecieveProps, but the state values are dependent on the given event handler.

Would it make sense to be able to pass in an additional parameter to the setState call to allow the developer to explicitly control the setState handling? 

Perhaps there are other use cases where one would want to batch a set of state and property changes so that they are guaranteed to be processed in the same tick. Something along the lines of:

x = React.createUpdateBatch
x.addPropUpdates (many)
x.addStateUpdates (many)
Recat.submitUpdateBatch(x)

**Comment by syranide** [comment]
`React.addons.batchedUpdates` is the solution I would say. Any updates during events or in life-cycle methods are automatically batched by React.

**Comment by gaearon** [comment]
It's currently exposed as `ReactDOM.unstable_batchedUpdates(() => { /* ... */ })`.
In the future we plan to batch them all by default.
