### ISSUE TITLE
Animations not working in safari 

### ISSUE THREAD

**Issue by GurpreetSran** [facebook/react#4488]
I have tested some basic animations which are working fine on chrome and firefox. But safari 8.0.7 is having issues. Nothing seems to work in safari, not even fadein/fadeout. eg:

http://jsfiddle.net/pchng/17rq3s6d/1/

**Comment by zpao** [comment]
Moving the transition to the active class seems to work. I'm not really sure of the details but others have had the same issue (see #3186) and our docs actually do that in the example as a result (http://facebook.github.io/react/docs/animation.html). I don't think there's really anything we can do here, we're simply adding or removing classes from the DOM node and this might just be one of those browser quirks.

**Comment by ffxsam** [comment]
@GurpreetSran The fix is to move the `transition` properties to the `active` classes. See here:

http://jsfiddle.net/aac4L5m5/1/
