### ISSUE TITLE
What is the verdict on Cycle,js?

### ISSUE THREAD

**Issue by HighOnDrive** [facebook/react#4491]
There is a new topic on Hacker News about React.js vs Cycle.js. Anyone know about this?

https://news.ycombinator.com/item?id=9949722

**Comment by fkling** [comment]
Please use the GitHub issues only for bug reports about React.

**Comment by HighOnDrive** [comment]
Looking at it that way makes even more sense.

**Comment by BerkeleyTrue** [comment]
@HighOnDrive Please close this issue. That discussion should stay on hacker news.

**Comment by sairion** [comment]
Why make issue tracker a public discussion place?
