### ISSUE TITLE
When "wrapping" child elements, can it be possible to not need the key on the wrapper?

### ISSUE THREAD

**Issue by slorber** [facebook/react#4496]
The title may be not very clear but my example is easy to understand

```javascript
// The key is set correctly here
var childs = [
<Child key={"1"}/>,
<Child key={"2"}/>
]

// The key is not set correctly here
var childsWrapped = childs.map(function(c) { return <Wrapper>{c}</Wrapper>; });
```

I often have to put wrapper components around other components and find out that often I forget to put back the key attribute on the wrapper.

If the child already has a key, the wrapper could perhaps also uses that key automatically?

Don't know if this is possible nor a good idea, just wondering :)

**Comment by jimfb** [comment]
Sounds like too much magic to me.

You could always do:
```javascript
childsWrapped = childs.map(function(c) { return <Wrapper key={c.props.key}>{c}</Wrapper>; });
```

**Comment by spicyj** [comment]
That's `key={c.key}`.

**Comment by jimfb** [comment]
@spicyj Thanks, good catch, updated.  Sucks that `key` is special cased; I wish we had a good way to keep key on props without interfering with user code.

**Comment by slorber** [comment]
thanks

yes that would probably be a little magical

I guess I could use a higher order component instead of a runtime wrapper and solve the problem on my side without too much magic
