### ISSUE TITLE
Unmount all root components from container

### ISSUE THREAD

**Issue by winterbe** [facebook/react#4498]
Hi,

I'm using React for certain modules in a mature project which is primarily built around jQuery and server-side rendered HTML. The main routing mechanism loads a particular URL via `$.ajax` and then replaces the HTML of the content container of the page via `$('#content).html(result)`.

When using React components on a page I noticed that I manually have to unmount the root components before leaving the page and loading a new page with `$('#content).html(...)`. In that case the React components are rendered into a `div` deeply nested somewhere in the '#content' container.

Unmounting the root components rendered into the content container manually via `React.unmountComponentAtNode` works as expected. But I'm concerned that developers could forget to unmount their components which could lead to memory leaks and unexpected behavior I guess.

Therefore I would like to unmount all possible root components in a generic way directly from the router. Unfortunately I don't know how to get all the DOM nodes from a particular parent container in a generic way. 

This doesn't work because the components are not rendered directly into the content container but somewhere in the content container hierarchy:

```js
React.unmountComponentAtNode(document.getElementById("content"));
```

Is there any way to retrieve all root components for a given DOM element? Selecting all elements with `data-reactid` would not only select the root components but also child components. 

It would be helpful if React would directly support unmounting of a whole container.

Thanks in advance for your help and keep up the good work!

Benjamin

**Comment by zpao** [comment]
This is doable in userland but it's definitely awkward and requires some tree search to find all roots (or overselecting nodes - `qSA('[data-reactid']` and check each for `!node.parentNode.dataSet['reactid']`).

It might be handy to expose roots in same way, this has come up before in other tooling. But it's awkward to do. cc @sebmarkbage 

So what I might suggest for you is an imperative wrapper around React.render - basically have something that tracks when you call render, store a reference to the target node, and then you can call into that to unmount. Here's a really simple way you could do it.

```js
var Renderer = {
  _nodes = [],
  render: function(element, node, cb) {
    Renderer._nodes.push(node);
    return React.render(element, node, cb);
  },
  unmount: function() {
    Renderer._nodes.forEach((node) = > React.unmountComponentAtNode(node));
  }
}
```

We actually use a very similar pattern at FB. I suspect that @sebmarkbage or @spicyj will probably close this and suggest something what I did.

**Comment by sebmarkbage** [comment]
Yea, what @zpao said.

I think the rationale is that we don't really have any good "magic" way of doing this. Trying to expose an API would be broken, flaky or unnecessarily slow. This is better solved in an environment specific way. So, I'll close this out with @zpao's suggestion. Let's revisit if we come up with some other clever idea.

I suggest @jimfb takes this example on for his upcoming blog post.

**Comment by jimfb** [comment]
@sebmarkbage For the blog post: do you want a passing reference to this use case or do you want an exploration with this code in the blogpost?  Blogpost already has code for (and talks about) ReactComponentRenderer.  On that note, if you have feedback for the latest draft, let me know - probably good to get the ball moving on that blog post; it has been a while.

**Comment by winterbe** [comment]
Thanks for your feedback. I'll stick with the solution proposed by @zpao. 

However all our devs have to recognize to use this rendering wrapper instead of using `React.render` directly. I'd better prefer a solution which doesn't depend on human factor, because I suspect this could lead to serious memory leaks which are hard to tackle (remembering the "good old" IE7 times :angry:).

If you would introduce some kind of DOM marker for root components - e.g. a special kind of `data-react` attribute only attached to the root element to which `React.render` mounts the component - we could simply select all root components located somewhere inside a given container and unmount them manually.

However this issue is only related to legacy projects and that's probably not your main focus. So I'm cool with the proposed solution. Kudos! :+1: 

PS: @sebmarkbage @jimfb Looking forward to a blogpost on that. What's the website you're going to publish this post?

**Comment by syranide** [comment]
> However all our devs have to recognize to use this rendering wrapper instead of using React.render directly. I'd better prefer a solution which doesn't depend on human factor, because I suspect this could lead to serious memory leaks which are hard to tackle (remembering the "good old" IE7 times :angry:).

You could always unset `render` or replace it with an error.

**Comment by jimfb** [comment]
@winterbe React blog is here: http://facebook.github.io/react/blog/
