### ISSUE TITLE
React custom rendering: react-blessed

### ISSUE THREAD

**Issue by Yomguithereal** [facebook/react#4500]
Hello React team. With the release of `0.14.0-beta1` and the separation of the rendering logic from React's core, I started scaffolding a custom renderer for the [blessed](https://github.com/chjj/blessed) library, used to create terminal interfaces. [Here](https://github.com/Yomguithereal/react-blessed) is therefore the WIP but nonetheless working version of `react-blessed`.

This issue is therefore a way for me to give you some feedback on the creation of custom renderers, to ask you for some advice and to check whether I did things correctly and in a way you would deem to be the right one.

Here are the steps I followed:

* I created a `ReactBlessedComponent` and `ReactBlessedTextComponent` based respectively upon `ReactDOMComponent` and `ReactDOMTextComponent`.
* I creared a `ReactBlessedReconcileTransaction` mimicking the behavior of `ReactReconcileTransaction`.
* I created an injection file that basically does the following:

```js
ReactInjection.NativeComponent.injectGenericComponentClass(
  ReactBlessedComponent
);

ReactInjection.NativeComponent.injectTextComponentClass(
  ReactBlessedTextComponent
);

ReactInjection.Updates.injectReconcileTransaction(
  ReactBlessedReconcileTransaction
);
```

* I created an endpoint for the renderer exposing a simple function taking a React valid element and a blessed `screen` options based on what `ReactServerRendering` would do.
* I had to override `ReactComponentEnvironment.processChildrenUpdates` and set it to a noop so my updates can work without the DOM.

So now I have a working renderer with working state, reconciliation, refs, events etc.

Is there things I would have missed and that would break the renderer at some point?

**Comment by gaearon** [comment]
Would love to see it working with React Hot Loader. @jlongster You had some experience getting HMR running with Node, want to give it a go?

**Comment by Yomguithereal** [comment]
It would be nice indeed to see the Hot Loader working with the blessed renderer. This would definitely make terminal dashboards' development process easier.

**Comment by Yomguithereal** [comment]
I guess we can now link toward your [repo](https://github.com/gaearon/react-blessed-hot-motion) on the subject @gaearon and close the issue :).
