### ISSUE TITLE
Using braces in props causes Syntax Error

### ISSUE THREAD

**Issue by charliematters** [facebook/react#4508]
The following JSX:

`<div propA={(10/2)} propB={(10/2)} />`

produces the following (incorrect) JS:

`React.createElement("div", {propA: (10/2, )propB: (10/2)})`

Reproducible on the JSX Compiler page (http://facebook.github.io/react/jsx-compiler.html)

**Comment by cody** [comment]
The react-tools are deprecated. Babel compiles it to:
```js
React.createElement("div", { propA: 10 / 2, propB: 10 / 2 });
```
Here this can be tried out: https://babeljs.io/repl/

**Comment by charliematters** [comment]
OK, just read the blog post about Babel. 

In that case, this is more of a documentation defect as Babel is not mentioned anywhere in the docs (https://facebook.github.io/react/docs), but I guess that will change given time

**Comment by zpao** [comment]
We'll update the website with more complete documentation soon.
