### ISSUE TITLE
ES6 class methods not binded to class instances

### ISSUE THREAD

**Issue by jpinho** [facebook/react#4509]
Let's say we have a class like this:

    export default class BasePlayer extends React.Component {
          myMethod(){ }
    }

Then, if I use this BasePlayer inside another component and I name it with "ref=basePlayer", like this:

    class SomeComponent extends React.Component {
        ...
       render(){
            return <div><BasePlayer ref="basePlayer" /></div>
        }
        ...
    }

The problem is that, from the class SomeComponent I can't call "this.refs.basePlayer.myMethod()", because the methods are not binded to the basePlayer instance.

To fixed it what I did was, to manually bind/expose my methods from the BasePlayer constructor like this:

    constructor(props){
        super(props);

        /*public methods*/ 
        this.myMethod= this.myMethod;
    }

But it should be automatic... Is there a better way to achieve this?

**Comment by syranide** [comment]
> The problem is that, from the class SomeComponent I can't call "this.refs.basePlayer.myMethod()", because the methods are not binded to the basePlayer instance.

That sould work just fine, when called as `basePlayer.myMethod()` as you show.

If `this.myMethod = this.myMethod;` solves it then I assume there's something wrong with how your classes are set up/handled.

**Comment by cody** [comment]
Here is a fiddle that agrees with @syranide: https://jsfiddle.net/bv9na32L/

**Comment by jpinho** [comment]
Hum! Thanks @cody, I'm using Webpack with BabelJS, a transpiler to ES6, maybe it's a bug on the transpiled code from Babel!

**Comment by syranide** [comment]
@jpinho I'm too (and most do) and at least I have no problems.

**Comment by jpinho** [comment]
@syranide Sorry xD! Thanks for the help!
