### ISSUE TITLE
Factory.type is deprecated without using .type

### ISSUE THREAD

**Issue by Keats** [facebook/react#4510]
Hey,
I am using react 0.13.3 and typescript 1.5 and whenever I use React.createFactory I get the
`Warning: Factory.type is deprecated. Access the class directly before passing it to createFactory.` warning despite not using .type anywhere.
The smallest code to reproduce the issue (minus imports):

```ts
export class BoardAppComponent extends React.Component<any, any> {
    render() {
        return button(null, "hey");
    }
}

const BoardApp = React.createFactory(BoardAppComponent);
export default BoardApp;
```

I'll link to a project with the issue once I'm done with it

**Comment by Keats** [comment]
Here's a repo that shows the issue, currently updating to react 0.14 and ReactDOM: https://github.com/Keats/react-boilerplate

**Comment by syranide** [comment]
I seem to only get that error message when I do:

```js
class ComponentX {}
var FactoryX = React.createFactory(ComponentX);
FactoryX.type;
```

Are you sure you're not doing that somewhere?

**Comment by Keats** [comment]
I don't no.
For example in the repo above:

```ts
const Board = React.createFactory(BoardComponent);
export default Board;
```
(https://github.com/Keats/react-boilerplate/blob/master/src/app/components/board.ts#L59-L60)

and in the component using it:
```ts
    renderBoards(): Array<React.ReactElement<any>> {
        return Object.keys(this.props.boards).map((key) => {
            return Board({board: this.props.boards[key]});
        });
    }
```
(https://github.com/Keats/react-boilerplate/blob/master/src/app/components/boardApp.ts#L22-L26)

At first I thought it was react-redux but it does the same thing without it

**Comment by zpao** [comment]
Looking at the stack… this is coming from react-hot-loader, you'll want to make sure you're up to date and / or report it to them. They are accessing `Class.type` - https://github.com/gaearon/react-hot-loader/blob/master/isReactClassish.js#L38. 

Now that said, I strongly encourage you not to export factories and instead convert classes to factories in the consuming component module. By exporting a factory, it can only be used that way, not with JSX (in other words, our primary JS API: createElement).

**Comment by Keats** [comment]
Cheers, I somehow missed that.
I'll follow your recommendation as well
