### ISSUE TITLE
The fixed issue #1478 happens again for the latest stable edition 0.13

### ISSUE THREAD

**Issue by foolyoghurt** [facebook/react#4515]
The issue [#1478](https://github.com/facebook/react/issues/1478) was fixed by [pull #2549](https://github.com/facebook/react/pull/2549). And from the comments it seems works. But now I meet the same problem with the latest stable edition 0.13. 

I write a [todo list](http://jsfiddle.net/foolyoghurt/g18L2vzv/1/) with react and use ReactCSSTransitionGroup to do some animation. However, when I use `clear completed` button to delete all the completed todo items, only the last item will be deleted just as [issue #1478](https://github.com/facebook/react/issues/1478) mentioned. And if I don't use `transitionLeave={false}` on ReactCSSTransitionGroup everything works fine.

I see in the [ReactTransitionGroup.js](https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js#L178-L201) some [code committed](https://github.com/facebook/react/pull/2549/files) to fix this problem has been **removed** and so does the test case! I wonder what happened.

**Comment by zpao** [comment]
#2549 was not merged to the stable branch, the fix was applied to `master` and will be a part of 0.14. The code for the fix was not removed, it was updated in 08e4420019f74b7c93e64f59c443970359102530.

**Comment by foolyoghurt** [comment]
Oh, yes. I build react 0.14.0-beta manually and it really works. [http://jsfiddle.net/foolyoghurt/7w46rn3d/1/](http://jsfiddle.net/foolyoghurt/7w46rn3d/1/)
