### ISSUE TITLE
No license via NPM

### ISSUE THREAD

**Issue by chapinkapa** [facebook/react#4517]
Can we add the license to the NPM package?

**Comment by zpao** [comment]
The license is specified in package.json. Do you mean the actual license file?

**Comment by chapinkapa** [comment]
Ah, I see. Great. Ideally we would like the license file with the build, but let me check with the legal department if referencing the license name would be sufficient.

**Comment by zpao** [comment]
FWIW, each file header also shows that it's BSD. I know what dealing with legal is like though so let us know if there are concerns.

```js
/**
 * Copyright 2013-2015, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
```

It's probably a good idea to ship the license and patents file regardless (will put that on the list for the next release).

**Comment by chapinkapa** [comment]
Awesome. Thank you @zpao!!
