### ISSUE TITLE
Make controlled component the only option?

### ISSUE THREAD

**Issue by chenglou** [facebook/react#452]
Currently the only advantage I can think of, of using uncontrolled components, is for their lightweight syntax. But ReactLink made me wonder if there isn't a better way.

Currently:

``` js
var Uncontrolled = React.createClass({
  render: function() {
    return <input type="text" defaultValue="hello" />;
  }
});
```

``` js
var Controlled = React.createClass({
  getInitialState: function() {
    return {text: 'Hello!'};
  },
  handleChange: function(event) {
    this.setState({text: event.target.value});
  },
  render: function() {
    return <input type="text" value={this.state. text} onChange={this.handleChange} />;
  }
});
```

My proposal:
Keep controlled the same. Controlled with sugar:

``` js
var Controlled = React.createClass({
  render: function() {
    return <input type="text" value="hello" stateLink="text" />;
  }
});
```

I realize this is a bit of magic, but considering that currently we need to:
- Explain what `defaultValue` is and its reason for deviating from DOM.
- Provide an add-on (in another build) to have the benefits of uncontrolled components, which might seem a bit backward.
- Have `value` anyway.

I feel the pros outweigh the cons here. With the new format you still have two options very similar to controlled/uncontrolled, but with all the benefits of a controlled component.

**Comment by jedwards1211** [comment]
Uncontrolled components are leading to confusion.  In [one instance](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318#.7idz8ln65), they confused a lot of people into thinking index keys will cause your data to show in the wrong place, when really the example had uncontrolled components whose values simply don't update when the underlying data is reordered.

To illustrated that uncontrolled components, and not index keys, are the fundamental problem, I created [this JSFiddle](https://jsfiddle.net/jedwards1211/dtLtnf0f/).

It's not just a question of convenience but whether we'll have to deal with developer confusion and React code that's been polluted with a lot of inappropriate uncontrolled components some day.

**Comment by jedwards1211** [comment]
Likewise, I really wasn't happy to see official 2-way binding helpers in the React documentation.

**Comment by Aweary** [comment]
@jedwards1211 it should be noted that `ReactLink` is to be deprecated as of 15.0: https://github.com/facebook/react/pull/6085

**Comment by jedwards1211** [comment]
@Aweary nice, glad to hear it.
