### ISSUE TITLE
Deprecate React.addons.batched_updates

### ISSUE THREAD

**Issue by zpao** [facebook/react#4525]
We shipped this in 0.13 but then exposed it as `React.unstable_batchedUpdates` (or `require('react-dom').unstable_batchedUpdates`) in master. We should deprecate the usage in `React.addons` (separately from other deprecation notices because we aren't shipping this as a standalone addon).

**Comment by dustingetz** [comment]
I can't find any information regarding this decision, if React.addons.batchedUpdates goes away, how are we supposed to batch setStates in non-dom event handlers?

**Comment by zpao** [comment]
`require('react-dom').unstable_batchedUpdates`. As of right now, the batching is a part of the reconciler which lives in `react-dom`, even if it's used by non-dom event handlers.
