### ISSUE TITLE
Warning setState on unmounted component with traceback

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#4526]
> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.

It would be great to get a stack trace here so I know what this warning is referring to

**Comment by jimfb** [comment]
Duplicate of https://github.com/facebook/react/issues/4216.  Fixed in 0.14.

**Comment by ccorcos** [comment]
:)
