### ISSUE TITLE
Feature: Higher-level wormhole pattern

### ISSUE THREAD

**Issue by dantman** [facebook/react#4530]
I’ve been thinking about code that needs to render React nodes somewhere other than as a direct DOM child of a React component. With examples such as:
- A user of [Tether](http://tether.io/), a library which sometimes needs to relocate the DOM node for positioning to work right.
- A React `Popover`/`Dropdown`/`Dialog` component that planning to render its children as a decedent of `body` so it can position things correctly. (as a bonus this means a popover component can be passed directly to the button that controls it).
- A React component that uses a 3rd party modal dialog library and renders its React children in the body created by that component.
- This could also be slightly related to the need some people have to keep a DOM node around even when it’s not being rendered. (Assuming the implementation is able to React render into a detached node).

The current pattern for these kind of use cases is for the component to `React.render` its children in a different DOM node and then `React.unmountComponentAtNode` when the component unmounts. Which as I understand it, is called the “wormhole” pattern.

However this pattern is problematic. With this method context is not passed to the children the way it should be. And while we ‘could’ add a way for a component to access the internal context it’s not supposed to see (the properties it hasn’t declared) and allow `React.render` to accept that. That would expose internals in ways it shouldn’t be exposed. And in the case that there is any other thing internal to react that should be passed on would not help.

So we need a higher level api to declare faux/virtual/relocated “children” (pick a name) which render into a separate DOM component somewhere else in the dom but are still linked to another component (most components will simply pass `this` into the api).

- The component is responsible for creating the DOM container and telling ReactDOM where it is.
- This would be integrated into React(DOM) so context and any other piece of data would flow as it normally does.
- The component would be responsible for cleaning up the container. I’m unsure if React should be responsible for unmounting children from the faux/virtual/relocated location or if that would be another function.

**Comment by jimfb** [comment]
This is called `renderSubtreeIntoContainer`.  That solves the problem of a conceptual child that is rendered at (for instance) the body so it can be positioned like a `Popover/Dropdown/Dialog` but still needs access to context.

Also, to be clear, the "wormhole" pattern is a completely different pattern.  "Wormholes" are when a parent needs to pass information to a child (usually ~1 level deep) that the parent didn't directly create.  For instance, a `Table` component that takes in a `TabelCell`, so someone creates a `JimboxTableCell` that renders into a `TableCell`, and now the `Table` component wants to pass a style or whatever to the `TableCell`.

**Comment by jimfb** [comment]
Or rather, I suppose the name is now `ReactDOM.unstable_renderSubtreeIntoContainer`.

**Comment by dantman** [comment]
Ok, then I'm going to have to look into `*renderSubtreeIntoContainer`. I wonder why none of the examples, blog posts, or anything else mentioning this pattern using `React.render` made any mention of that method.

**Comment by jimfb** [comment]
Because context isn't supported, and, you know, doesn't actually exist.  It's all a myth :).

**Comment by zpao** [comment]
`renderSubtreeIntoContainer` also hasn't been shipped to a stable release so we haven't mentioned in the docs yet.

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.01 ETH (6.92 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/facebook/react/4530/449).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
