### ISSUE TITLE
onMouseEnter is broken in 0.14.0-beta1 in Chrome

### ISSUE THREAD

**Issue by hgl** [facebook/react#4531]
`onMouseEnter` handler is not called when mouse over an element:

```jsx
class Box extends React.Component {
	constructor(props) {
		super(props);
		this.state = {text: "leave"};
	}

	render() {
		let enter = () => this.setState({text: "enter"});
		return (
			<div onMouseEnter={enter}>{this.state.text}</div>
		);
	}
}

let container = document.getElementById("container");
  
React.render(<Box/>, container);
```

Works in other browsers but not Chrome (stable or canary).

However, if you render a list of divs each has a `onMouseEnter` handler, mouse enter between them works, but not from outside to one of of divs.

**Comment by hgl** [comment]
Was trying to set up an online demo, but couldn't find any react & react-dom 0.14.0-beta1 main scripts that are directly usable in browsers.

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/4513
