### ISSUE TITLE
'TestUtils.Simulate.click' don't work

### ISSUE THREAD

**Issue by ScauZhang** [facebook/react#4532]
``` javascript
// tab.jsx的测试用例

jest.dontMock('../tab');

var ReactAddons = require('react/dist/react-with-addons.js');
var React = require('react/dist/react.js');
var tab = require('../tab');
var TestUtils = ReactAddons.addons.TestUtils;

describe('tab test',function(){


    var ul ;
    var tabDom;
    var btn;

    beforeEach(function() {
        tabDom = TestUtils.renderIntoDocument(
                React.createElement(tab, null)
            );
        // tabDom.handleClick = jest.genMockFunction();
        ul = TestUtils.findRenderedDOMComponentWithTag(tabDom,'ul');
        btn = TestUtils.findRenderedDOMComponentWithTag(tabDom,'button');

    });

    it('click the btn add item',function(){
        console.log(ul.props.children.length);

        TestUtils.Simulate.click(btn);
        expect(ul.props.children.length).toEqual(3);
    });
});
```

BUT  expected:2 but 3
'TestUtils.Simulate.click' don't work

**Comment by jimfb** [comment]
I can't tell what's going on here without the implementation details of your tab code, but I suspect that `TestUtils.Simulate.click` isn't outright broken, since we have many unit tests that rely on that functionality.  For a usage example, I recommend: https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/__tests__/ReactDOMButton-test.js#L25

**Comment by dmatteo** [comment]
Simulate.click works on DOM node, and you are not passing in one.

```javascript
    it('click the btn add item',function(){

        var btnNode = React.findDOMNode(btn);

        TestUtils.Simulate.click(btnNode);
        expect(ul.props.children.length).toEqual(3);
    });
```

**Comment by bhanubhakta** [comment]
@dmatteo It is not still working even if I pass DOM node.

**Comment by dmatteo** [comment]
I don't see your component logic, so I can't tell why you're checking the length of the children after click. 

What you can do to test if click is actually working is attaching a click handler to that button and pass in a spy (with sinon for example)  and you will see if the click is actually firing or not
