### ISSUE TITLE
support for svg mask attribute (not svg mask tag)

### ISSUE THREAD

**Issue by IL55** [facebook/react#4538]
Hi, I want to ask you about support for svg mask attribute (it is unsupported in React  0.13.3). Please don't mix up with mask tag, i.e. next is allowed:
```
      <defs>
           <mask id="myMask"> .... </mask>
      </defs>
```
but using mask is not possible (react 0.13.3 removes that attribute)
```
    <g mask="url(#myMask)"> ... </g>
```

Here is jsfiddle example:
https://jsfiddle.net/kbcpLyax/4/

More details could be found in next comment:
https://github.com/facebook/react/issues/140#issuecomment-73788054

I've just created new issue instead to continue long https://github.com/facebook/react/issues/140 issue

hot fix (for React 0.13.3 users) is next
```
// Load in SVGDOMPropertyConfig before loading React ever and set up custom properties
var SVGDOMPropertyConfig = require('react/lib/SVGDOMPropertyConfig');
var DOMProperty = require('react/lib/DOMProperty');

SVGDOMPropertyConfig.DOMAttributeNames.mask = 'mask';
SVGDOMPropertyConfig.Properties.mask = DOMProperty.injection.MUST_USE_ATTRIBUTE;
```

**Comment by zpao** [comment]
Going to merge this into #1657. It's a known issue that we're missing a lot of SVG support. See particularly my comment (https://github.com/facebook/react/issues/1657#issuecomment-47708471) where I explained why we haven't added everything. I still don't want to do each of these as 1-offs. Does this suck? Yes, absolutely. Sorry :(
