### ISSUE TITLE
Publish v0.14.0-beta2 addons update on npm

### ISSUE THREAD

**Issue by cesarandreu** [facebook/react#4544]
The addons on npm are still on v0.14.0-beta1. More importantly the modules for TestUtils and Perf (which should now get published thanks to #4501) still aren't on npm. This makes trying out v0.14.0-beta2 a bit trickier than would be ideal.

**Comment by zpao** [comment]
I got caught up with some other work yesterday but they're up now. Thanks for the reminder.

**Comment by cesarandreu** [comment]
Thanks!!
