### ISSUE TITLE
setTimeout arguments nulled out

### ISSUE THREAD

**Issue by jannavarro** [facebook/react#4547]
I have an autocomplete textbox component. The onChange event is assigned to a function called DelayKeyup which waits for the user to stop typing for 2 seconds before I call my handleInputChange function.

In the DelayKeyup I receive the event from React. This contains the target property (screenshot below) I need so I pass event as argument in the handleInputChange function. 

![image](https://cloud.githubusercontent.com/assets/4499051/9029597/f24f64e8-39c8-11e5-813d-44572d86b743.png)

The problem is that when the event argument is received by handleInputChange the values are null. What might cause this?

![image](https://cloud.githubusercontent.com/assets/4499051/9029645/990d0e5c-39c9-11e5-9d15-705fc1723ebe.png)

**Comment by koulmomo** [comment]
React pools its synthetic events. You should to call `e.persist()` to make sure the event isn't put back in the pool.

see https://github.com/facebook/react/issues/1717 for more info.

**Comment by jannavarro** [comment]
@koulmomo Thank you. Looking at that issue they were able to resolve it but in my case the value that the user type got lost.

Here event.target.value = p

![image](https://cloud.githubusercontent.com/assets/4499051/9029998/d4d317c4-39ce-11e5-9f2b-c3f6a1a230ad.png)


In the handleInputChange the value is lost.

I tried searching all issues in react and I am looking at #1360 but I am not sure yet if that is the same issue. If you know of any suggestions kindly let me know.

![image](https://cloud.githubusercontent.com/assets/4499051/9030005/e994383c-39ce-11e5-973a-0275a8290496.png)

**Comment by jannavarro** [comment]
I solved this by just passing the event.target.value as the parameter instead of sending event itself.
