### ISSUE TITLE
update checkbox   defaultChecked , it doesn't work

### ISSUE THREAD

**Issue by majorye** [facebook/react#4548]
update checkbox   defaultChecked , it doesn't work
please  see [here](http://jsfiddle.net/majorye/wavpf5qj/)

**Comment by nikolaymatrosov** [comment]
It's not a bug. See the docs https://facebook.github.io/react/docs/forms.html#default-value
>The `defaultValue` and `defaultChecked` props are only used during **initial render**.

**Comment by zpao** [comment]
As mentioned, this is working as intended, you actually want a controlled component.

**Comment by majorye** [comment]
thanks @nikolaymatrosov @zpao

**Comment by majorye** [comment]
use checked property works, see [here](http://jsfiddle.net/majorye/wavpf5qj/10/)

**Comment by jaydeepresources** [comment]
react is the most stupid thing i have ever seen
