### ISSUE TITLE
Adding example app to wiki

### ISSUE THREAD

**Issue by yangmillstheory** [facebook/react#4551]
I'd like to add my [React/Flux/immutable demo app](https://maaamba.herokuapp.com/) to the [examples page in the wiki](https://github.com/facebook/react/wiki/Examples), but there's no simple way to pull request changes to it, from the bit of researching I've done.

Could someone here let me know the preferred way of getting this done? It looks like it's open for editing to anyone, but I'm not sure I should just do that.

**Comment by zpao** [comment]
Feel free to add it directly to the wiki :)
