### ISSUE TITLE
Question: Two React based apps on one page

### ISSUE THREAD

**Issue by honzabrecka** [facebook/react#4556]
Hi, I have a video component written in ClojureScript (based on Om) and a page written in JavaScript (based on React) and I want to use that video component in that page.  I came up with the following code, which works, but I'm not sure if it's OK:

```js
class Page extends React.Component {
  render: () => {
    return <div><div id="video"></div><Comments/></div>;
  }
}

React.render(<Page/>, document.getElementById('page'), function() {
  // video is an instance of ClojureScript application
  video.client.render({id: 'abc'});// calls React.render(<VideoPlayer/>, document.getElementById('video'));
});
```

Please, take a look and confirm eventually.

**Comment by fkling** [comment]
Please use GitHub issues only for bug reports.
