### ISSUE TITLE
Support the camelCase version of webkitTransform as well

### ISSUE THREAD

**Issue by probablyup** [facebook/react#4557]
Although `node.style.WebkitTransform` (PascalCase) does work in Safari, the actual property is `node.style.webkitTransform` (camelCase) which React doesn't support properly. Can an alias be added to handle this case, since it doesn't seem obvious?

In fact, Safari's inspector autocomplete doesn't even work for `node.style.WebkitTransform` - seems like it's a hack that it works.

**Comment by sebmarkbage** [comment]
cc @spicyj who added a warning against this. #2504

**Comment by zpao** [comment]
Well, previously Safari autocompleted both and we assumed they would do the "right thing" and use `Webkit`, leaving `ms` as the only one not following that pattern (MozTransform, WebkitTransform, OTransform, msTransform) but I guess now Moz is the odd one out (O is effectively dead).

**Comment by spicyj** [comment]
Sigh.
