### ISSUE TITLE
emptyFunction.js is missing from the lib folder of a fresh install (0.14.0-beta3)

### ISSUE THREAD

**Issue by buddyp450** [facebook/react#4564]
Not sure why but this is missing and it appears to be required in order for react to function properly.

Issue is very easy to recreate:
```
mkdir example
cd example
jspm init
jspm install react@0.14.0-beta3
```

Just notice that underneath jspm_modules/npm/react@0.14.0-beta3/lib that the emptyFunction.js file is not present.

**Comment by syranide** [comment]
It seems to work just fine for me, could you paste the error you are seeing?

**Comment by buddyp450** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3002/jspm_modules/npm/react@0.14.0-beta3/lib/emptyFunction.js

**Comment by syranide** [comment]
Need the source/origination, but I'm going to go out on a limb and assume that it's not React that is requiring the file but some external code, that incorrectly accesses React internals and expects it to be there.

**Comment by buddyp450** [comment]
Thanks, this got me pointed in the right direction. Appears to be an issue with importing [react-grid-layout](https://github.com/STRML/react-grid-layout).

**Comment by zpao** [comment]
Yup not React. We moved some files into a different project for sharing deps (fbjs). We've long said that requiring into `react/lib/` will probably break. And that is now starting in force.
