### ISSUE TITLE
Build folder is not present in the latest github release

### ISSUE THREAD

**Issue by buddyp450** [facebook/react#4568]
index.js references the build folder which does not exist on an initial install

Was attempting to install using jspm: ```jspm install github:strml/react-grid-layout``` since the NPM version was way out of date.

**Comment by zpao** [comment]
I think you'll want to file this in https://github.com/strml/react-grid-layout, this isn't a React issue.

**Comment by buddyp450** [comment]
Oops, I meant to, must've been still on this form entry. Sorry for the confusion.
