### ISSUE TITLE
The <video> tag attribute webkit-playsinline  can't be  parsed 

### ISSUE THREAD

**Issue by jarvanxing** [facebook/react#4570]
The <video> tag attribute webkit-playsinline supposedly prevents the default go to fullscreen behavior of HTML5 videos.

This attribute works in some webview when a flag is set in the native code.
I want  use this attribute to prevent the default behavior  on iphone.
I saw the custome-attributes doccuments, like data-**, aria-**,  and it works like this:
&lt;video data-webkit-inline="true" ..../&gt;
but what i need is:
&lt;video webkit-inline  ..../&gt;

**Comment by sebmarkbage** [comment]
As a workaround I would recommend getting a `ref` on it and manually setting the attribute.

```js
function attachCustomAttributes(domNode) {
  if (domNode) {
    domNode.setAttribute('webkit-inline', ...);
  }
}

class Video {
  render() {
    return <video ref={attachCustomAttributes} />;
  }
}
```

**Comment by zpao** [comment]
See #140 for the long history of custom attributes.

**Comment by mpelzsherman** [comment]
`playsinline` has been [officially added to the HTML spec](https://webkit.org/blog/6784/new-video-policies-for-ios/). Any chance y'all might consider re-opening this?

**Comment by TudorEsan** [comment]
<video
        autoPlay
        loop
        muted
        playsInline
        preload="auto"
        webkit-playsinline
        className="max-w-[200px] hidden dark:block z-[1]"
      >
        <source
          src="https://res.cloudinary.com/dyntggp2n/video/upload/v1711122236/loading-dark_wrq3wm.mp4"
          type="video/mp4"
        />
        <track kind="captions" />
      </video>
      
      this for me still goes full screen in in-app ios browsers. for example if you open the link in twitter or instagram

**Comment by pwbriggs** [comment]
@TudorEsan is this issue specific to React? Did you try implementing it in pure HTML and testing?

If this *is* specific to React, perhaps it would be best to open a new issue. Remember to create a reproducible example.

Thanks! ❤️

**Comment by TudorEsan** [comment]
'use client';

import React, { useRef, useEffect } from 'react';

export const PulsarLoading = () => {
  const darkModeRef = useRef<HTMLVideoElement>(null);
  const whiteModeRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const darkMode = darkModeRef.current;
    const whiteMode = whiteModeRef.current;

    if (darkMode && whiteMode) {
      darkMode.setAttribute('webkit-playsinline', 'true');
      whiteMode.setAttribute('webkit-playsinline', 'true');
    }
  }, []);

  return (
    <div className="h-[80vh] flex items-center justify-center">
      <video
        autoPlay
        ref={darkModeRef}
        loop
        muted
        playsInline
        preload="auto"
        webkit-playsinline
        className="max-w-[200px] hidden dark:block z-[1]"
      >
        <source
          src="https://res.cloudinary.com/dyntggp2n/video/upload/v1711122236/loading-dark_wrq3wm.mp4"
          type="video/mp4"
        />
        <track kind="captions" />
      </video>
      <video
        autoPlay
        ref={whiteModeRef}
        loop
        muted
        preload="auto"
        playsInline
        webkit-playsinline
        className="max-w-[200px] dark:hidden z-[1]"
      >
        <source
          src="https://res.cloudinary.com/dyntggp2n/video/upload/v1711122236/loading-light_cggvfu.mp4"
          type="video/mp4"
        />
        <track kind="captions" />
      </video>
    </div>
  );




};


this is the entire file. Its a nextjs project i don t know if it counts or not to be specific for react 😃 

and a video:
https://github.com/facebook/react/assets/55596191/47ceb0ef-f688-428d-965e-56c338c4f24b
