### ISSUE TITLE
Consistency in prop.children type

### ISSUE THREAD

**Issue by yordis** [facebook/react#4572]
Most of the time we will something like ```{this.props.children.map(this.renderChild)}``` for render the children in some component because we need to clone the element or do something with it.

Right now I am facing a problem because when I pass just a child the ```map``` function is no longer there because is an object so we will end on something like this all the time, creating a little layer for deal with this problem.

Maybe we can take the approach of always create a array even when you pass a single element unless you see a problem there.

```js
return (
  <div>
    {this.renderChildren()}
  </div>
)

...

renderChildren() {
  if(Array.isArray(this.props.children)) {
    return this.props.children.map(this.renderChild)
  }

  return this.renderChild(this.props.children, 0)
}
```

**Comment by browniefed** [comment]
Does `React.Children.map` work on a single child?
[http://facebook.github.io/react/docs/top-level-api.html#react.children.map](http://facebook.github.io/react/docs/top-level-api.html#react.children.map)

**Comment by yordis** [comment]
@browniefed No, basically I had to this: https://github.com/React-UI/accordion/blob/develop/src/accordion.js#L56

**Comment by spicyj** [comment]
React.Children.map should work fine on a single child. Please file an issue with a repro case if you find otherwise.

**Comment by yordis** [comment]
@spicyj why my code fail: http://jsfiddle.net/ws_ubi/4xgtj12y/

**Comment by browniefed** [comment]
@yordis you need to call `React.Children.map(this.props.children, yourFunc)` LIke so http://jsfiddle.net/4xgtj12y/1/

**Comment by yordis** [comment]
@browniefed oh -_- I guess there is a reason.

Sorry for my mistake
