### ISSUE TITLE
Add support for types for ES6 arrow functions literals

### ISSUE THREAD

**Issue by sgronblo** [facebook/react#4573]
I am very new to Facebook Flow so I might have missed something but shouldn't you be able to write types for ES6 arrow function literals?

For example:

```
export const f = (x: number): number = x * 2
```

craps out on line1 because of an unexpected `:`

**Comment by JohnyDays** [comment]
According to facebook/flow#37 this is fixed in 0.12. You should probably post it in that repo if it still doesn't work :+1:

**Comment by jimfb** [comment]
As per @JohnyDays, the flow repository would be a better place for this.

**Comment by zpao** [comment]
You might have an issue with the `jsx` command line too not transforming properly. If that's the case, I encourage you to start using babel instead.
