### ISSUE TITLE
get displayName from instance ? 

### ISSUE THREAD

**Issue by chandu0101** [facebook/react#4574]
Hi ,
      I am extending React.Component to define components in scala.js 

```scala
class Test extends ReactComponent { //scala.js code
  val displayName = "Test"
  def render() = React.createElement("div")
}
```
in react dev tools i am seeing No Display Name for all my components, for some reason scala.js output not getting name from  this function 

```js
  /**
   * Get a text description of the component that can be used to identify it
   * in error messages.
   * @return {string} The name or null.
   * @internal
   */
  getName: function() {
    var type = this._currentElement.type;
    var constructor = this._instance && this._instance.constructor;
    return (
      type.displayName || (constructor && constructor.displayName) ||
      type.name || (constructor && constructor.name) ||
      null
    );
  },
```
https://github.com/facebook/react/blob/6a92179d6fd6d7c4097f6310a7cefb2c0651287f/src/renderers/shared/reconciler/ReactCompositeComponent.js#L784

is it okay to modify this function to get displayName from instance before i break my head by digging to javascript prototypes constructors .. ? 

the following code works for me.
```js
  /**
   * Get a text description of the component that can be used to identify it
   * in error messages.
   * @return {string} The name or null.
   * @internal
   */
  getName: function() {
    var type = this._currentElement.type;
    var constructor = this._instance && this._instance.constructor;
    return (
      type.displayName || (constructor && constructor.displayName) ||
      type.name || (constructor && constructor.name) || (this._instance && this._instance.displayName) ||
      null
    );
  },
```

**Comment by zpao** [comment]
@chandu0101 Thanks for flagging. I understand the pain but I'm also not sure this is actually the right thing to do.

@sebmarkbage do we want to support all the ways non-JS can compile to JS or just say scala-js needs to fix this? Do we expect that displayName as an instance property will be the path of least resistance in future JS classes?

**Comment by jimfb** [comment]
My intuition is that once ES6 classes become utilized in the wild, this problem will solve its self.  In the mean time, we should probably make a good faith effort to support the most popular compile-to-js languages (coffee script, scalajs, etc), and have the less popular ones conform to one of the compile outputs of the bigger ones (which realistically, they'll probably do already anyway).

**Comment by sebmarkbage** [comment]
This is something that needs to be solved at the scala-js language compatibility level. Ideally it should preserve the "function" `name` when it exports a JS class.

It has the notion of object properties so perhaps something like this could work:

```scala
object Test {
  val displayName = "Test"
}
class Test extends ReactComponent {
  def render() = React.createElement("div")
}
```

I don't know.

**Comment by chandu0101** [comment]
@sebmarkbage  thanks for the hint , scala.js not emitting function name  , when i added manually everything looks fine :) .
