### ISSUE TITLE
Allow PropTypes.shape as a valid definition of propTypes

### ISSUE THREAD

**Issue by gajus** [facebook/react#4589]
Short:

`propTypes` should accept `React.PropTypes.shape` object as valid declaration of `propTypes`.

```js
import React from 'react';

export default class extends React.Component {
    static propTypes = React.PropTypes.shape({});

    // ...
```

More:

I have a file called `shapes.js` that defines all shapes used in the project, e.g.

```js
import {
    PropTypes
} from 'react';

export let screeningShapeDefinition = {
    id: PropTypes.number.isRequired,
    timestamp: PropTypes.number.isRequired,
    url: PropTypes.string.isRequired,
    position: PropTypes.number.isRequired
};

export let screeningListShapeDefinition = {
    size: PropTypes.number.isRequired,
    screenings: PropTypes.arrayOf(PropTypes.shape(screeningShapeDefinition)).isRequired
};
```

, which I use in modules as such:

```js
import React from 'react';
import moment from 'moment';

import {
    screeningShapeDefinition
} from './../../shapes';

export default class extends React.Component {
    static propTypes = screeningShapeDefinition;

    // ...
```

There is a slight leaking:

* I have to cast my shape definition object to `React.PropTypes.shape` when defining relations in the shapes definition file.

If `propTypes` (component definition property) supported `React.PropTypes.shape` as a valid input, I could avoid the leaking:

```js
import React from 'react';
import moment from 'moment';

import {
    screeningShape
} from './../../shapes';

export default class extends React.Component {
    static propTypes = screeningShape;

    // ...
```

```js
import {
    PropTypes
} from 'react';

export let screeningShape = PropTypes.shape({
    id: PropTypes.number.isRequired,
    timestamp: PropTypes.number.isRequired,
    url: PropTypes.string.isRequired,
    position: PropTypes.number.isRequired
});

export let screeningListShape = PropTypes.shape({
    size: PropTypes.number.isRequired,
    screenings: PropTypes.arrayOf(screeningShape).isRequired
});
```

**Comment by gajus** [comment]
I am happy to submit a PR if this is approved.

**Comment by jimfb** [comment]
You can already define your own proptype in user land, and use that in your components, so this shouldn't be a blocking issue.  We aren't working on the proptypes feature anymore (everything is moving to static analysis tools like Flow), so proptypes are on their way out.  I'm not sure if we'd accept a PR, but I do know it's not something we'd actively develop internally.
