### ISSUE TITLE
 Warning: Each child in an array or iterator should have a unique "key" prop should provide more info

### ISSUE THREAD

**Issue by tarjei** [facebook/react#4591]
Hi, If you're building a component of some complexity, or just with alot of HTML, then this warning gets infuriating hard to solve.

Would it be possible to include a bit of context into the warning, for example the tag and class of the html parent?

Something like:
```
Warning: Each child in an array or iterator should have a unique "key" prop. Missing for '<li id=book className="face">..' tag with parent '<ul className="no-bullet">'
```

**Comment by iamkoch** [comment]
The current code looks like it attempts to append this information:

 ```
warning(
    false,
    'Each child in an array or iterator should have a unique "key" prop.' +
    '%s%s%s',
    addenda.parentOrOwner || '',
    addenda.childOwner || '',
    addenda.url || ''
  );```

**Comment by zpao** [comment]
We do make a best attempt here at including a reference to the owning component. If you have a specific case that isn't warning, please include code and we can try to help better.

**Comment by tarjei** [comment]
Hmm, what I get is the name of the component - but not the surrounding HTML. Has this just been changed? I'm running 0.13.2.

The next sentence in the message is: "Check the render method of TimetableEntryForm", and allthough this is useful information, that component generates quite a few lists of elements so finding the bug is quite hard. That is why I'm suggesting that the error also add some information about the html surrounding the list - not just the component that generated the markup.

**Comment by dcsan** [comment]
+1 
`Check the render method of` just seems to return the top-level component, ie the page. 

I eventually found one problem that was way deep in a little tag list that was included inside various other pages. But hunting around to find what is causing this error (warning?) is excruciatingly time consuming.

**Comment by dcsan** [comment]
OK my problem was down to 

> The key should always be supplied directly to the components in the array, not to the container HTML child of each component in the array:

this is also a pain as it means you have to setup keys not inside the components own render code, but everywhere you use that component in the calling function... ugh.

**Comment by ramast** [comment]
I've found that printing the "element" variable extremely helpful.

    console.error(element)
    error('Each child in a list should have a unique "key" prop.' + '%s%s See https://fb.me/react-warning-keys for more information.', currentComponentErrorInfo, childOwner);

In my case I have a form with many select boxes, one of them had options without key but I couldn't tell which.
The error message say something like "my_component -> select -> option" has no key  but I have ton of select tags so which one?

By printing element, I could realize which select has that element (option tag) and address the problem quickly
