### ISSUE TITLE
Stop relying on document

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#4592]
We have a few use cases that we support which shouldn't rely on `document` or other DOM specific globals to be available.
- Shallow Rendering
- Worker Renderers (e.g. react-native like environments)
- Server Rendering (setState etc shouldn't look for document)

Unfortunately we often screw this up. Which leads to work arounds:
- https://github.com/gaearon/library-boilerplate/pull/6
- https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/polyfills/document.js#L28
- https://github.com/facebook/react/issues/3620

Part of the problem is that jest comes with JSDOM always on. We need to have a test environment that allow us to execute in a DOM-less environment.

We also need to add separate unit tests for these three test cases that execute in a DOM-less environment.

We could potentially add a lint rule against using globals in files in the `shared` folder.

We should also get rid of all uses of `canUseDOM` since it varies by render tree, not environment.

**Comment by nickdima** [comment]
Not sure how much is related to this issue but I've been trying to use React for rendering screens for an Apple TV application which uses DOM but it doesn't have a global document and window. Instead you create documents for each screen and you push them / pop them in a stack as the user navigates the app. More details about the environment here: https://developer.apple.com/library/prerelease/tvos/documentation/TVMLJS/Reference/TVJSFrameworkReference/index.html#//apple_ref/doc/uid/TP40016076
Could be nice to support this platform. Should I open a separate issue?

**Comment by wesleytodd** [comment]
This is also causing issues with running react in nwjs.  The issue there is that the `canUseDom` check checks `window.document` but then people reference `document` directly.  A simple fix would be to update this: https://github.com/facebook/fbjs/blob/master/src/core/ExecutionEnvironment.js#L14

```
var canUseDOM = !!(
  typeof window !== 'undefined' &&
  typeof document !== 'undefined' &&
  window.document.createElement
);
```
