### ISSUE TITLE
When giving a partial state to setState, child properties are not merged.

### ISSUE THREAD

**Issue by mik01aj** [facebook/react#4601]
[Docs about `setState`](https://facebook.github.io/react/docs/component-api.html) say:

> Merges nextState with the current state. This is the primary method you use to trigger UI updates from event handlers and server request callbacks.

From what I experienced, the state is not really merged. What happens is that properties from `nextState` are assigned to `this.state`. This is not a real merge.

In short, `setState` behaves like lodash's [`_.assign`](https://lodash.com/docs#assign) and not like [`_.merge`](https://lodash.com/docs#merge). Or, to put it in other words, it is not a recursive merge, but a shallow one.

I suppose you should either fix this in the code (but this could break backwards compatibility), or **update the documentation to be clear about this**.

**Comment by syranide** [comment]
The docs should be updated if it's unclear. But I'd say that "merge" isn't technically wrong, what you're thinking of is usually referred to as recursive merge (or deep merge).

**Comment by yaycmyk** [comment]
That being said - would it be possible to do recursive merging in setState? That actually sounds useful.

**Comment by syranide** [comment]
@yaycmyk It's a bad idea. You're free to do `setState(prev => deepMerge(prev, next))` if you want though (but I wouldn't recommend it).

**Comment by zpao** [comment]
We'll update the docs to clarify that this is a shallow merge. We won't change to do a recursive merge.

Thanks for bringing it up @mik01aj!

**Comment by edvinerikson** [comment]
We (@zpao) should probably close this as of the PR associated with this issue is merged.
