### ISSUE TITLE
HTML table summary attribute

### ISSUE THREAD

**Issue by hekar** [facebook/react#4603]
I'm creating a data table `<table summary="...">...</table>` and noticed that "summary" it is not listed in under React's [supported HTML attributes](https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes).

Any reason for not including the "summary" attribute? Or workaround? [It's fairly useful for legacy screen readers](http://www.w3.org/TR/WCAG10-HTML-TECHS/#tables).

https://jsfiddle.net/fyu01Lsw/1/

**Comment by zpao** [comment]
Workaround is to setAttribute in componentDidMount but that's not awesome.

It was probably skipped because it's marked as deprecated and not suggested for use (I think `<caption>` is probably the best alternative. But if there's still some value then we could do it. Want to give it a shot?

**Comment by hekar** [comment]
Thanks for pointing that out. Will make sure to read the mozilla docs next time. PR #4607

**Comment by zpao** [comment]
#4607 is in so this will be a part of 0.14.
