### ISSUE TITLE
Support for jsx filenames in React Native

### ISSUE THREAD

**Issue by pickhardt** [facebook/react#4604]
It seems that files with the extension .js can be required, but .jsx files cannot.

The following works fine:

```
var HelloPage = require("./src/views/screens/hello.js")
```

But when I rename the file and the code to .jsx, it gives the exception "Requiring unknown module "./src/views/screens/hello.jsx". If you are sure the module is there, try restarting the packager."

Restarting didn't seem to help. Is this a problem with something in React Native?

**Comment by zpao** [comment]
Please report this issue to https://github.com/facebook/react-native. They have their own packaging system which would need to understand this.

**Comment by pickhardt** [comment]
Oh, ok, I'll do that.
