### ISSUE TITLE
getBoundingClientRect() doesn't work in Jasmine/Jest testing

### ISSUE THREAD

**Issue by YeahButHats** [facebook/react#4606]
Every time I try to test, the Rect is always "empty:" `{left: 0, right: 0, top: 0, height: 0, bottom: 0, width: 0}`.  I've tried it in both Jasmine and Jest (just in case there was something different in one) and neither work. I'm hoping there's something I'm doing wrong, but if there is, I can't find it.

Version: 0.13.3

```
var React = require('react/addons');
var TestUtils = React.addons.TestUtils;

var findClass = TestUtils.findRenderedDOMComponentWithClass;

describe("React Tests", function() {
  it("return proper bounding rectangle height", function() {
    var component = TestUtils.renderIntoDocument(
      <div className="div">Hello World</div>
    );

    var node = React.findDOMNode(findClass(component, 'div'));
    var rect = node.getBoundingClientRect();
    
    expect(rect.height).not.toBe(0);
  });
});
```

This test works just fine though:

```
it("works normally with 'normal' DOM manipulation", function() {
  var div = document.createElement('div');
  var text = document.createTextNode('Hello World');
  
  div.appendChild(text);
  document.body.appendChild(div);

  var rect = div.getBoundingClientRect();
  expect(rect.height).not.toBe(0);
});
```

**Comment by zpao** [comment]
If you do this instead of using `renderIntoDocument`, does it work?

```js
var div = document.createElement('div');
document.body.appendChild(div);
var component = React.render(<div className=... />, div);
var node = React.findDOMNode(component);
...
```

`renderIntoDocument` doesn't actually attach the node it creates to the `body` and my suspicion is that getBoundingClientRect is then reporting all dimensions to be 0 (which would make sense if it's not actually in the DOM).

**Comment by YeahButHats** [comment]
Yes! Thank you.

I figured something like an "imaginary DOM" existed with `renderIntoDocument` but I couldn't find anyone else with the same issue. This makes a lot more sense now.
