### ISSUE TITLE
Support fontWeight svg attribute

### ISSUE THREAD

**Issue by rrag** [facebook/react#4625]
`fontFamily` and `fontSize` are already [supported](https://facebook.github.io/react/docs/tags-and-attributes.html#svg-attributes). `fontWeight` addition would be great.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute

**Comment by flipstewart** [comment]
Opened https://github.com/facebook/react/pull/4768 to address this.

**Comment by mijamo** [comment]
fontStyle would be nice too, I saw a patch there : #4880 , hope it makes it to master.

**Comment by gaearon** [comment]
This was fixed in #5714.
