### ISSUE TITLE
CodeMods don't apply when using ES6 Modules

### ISSUE THREAD

**Issue by iammerrick** [facebook/react#4629]
Note the branch on mine and @cpojer for of react. Currently code mods detect require(<react>)... Should add detection of import React from <react>.

**Comment by cpojer** [comment]
I pushed 5395c815deea6bff0bb01a4e803800dc69c29886 and 989caa870d614458aee2f40fb08b2c1229a04248 (flattened your commits into one) so this should work now.

**Comment by iammerrick** [comment]
Wahoo! :-D
