### ISSUE TITLE
add ref/children access support for TransitionGroup

### ISSUE THREAD

**Issue by yongxu** [facebook/react#4636]
TransitionGroup will clone its children and change their refs. Therefore there doesn't seem to exist any easy hack to directly access their instance or call methods. Especially, this makes filtering, intercepting and dispatching events almost impossible. 

It will be great if we could make a way to fix this, I figured out it is hard to use refs because of children are cloned, but implementing a method could be an easy way around:

TransitionGroup.getChildWithRef('child ref') => return child with that ref

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
