### ISSUE TITLE
Can we transplant a React react root manually?

### ISSUE THREAD

**Issue by trusktr** [facebook/react#4640]
Or do we need to do something with the React API for it to work (domdiff) properly?

For example,

```js
React.render(<div>foo</div>, $('#some-div')[0])

setTimeout(function() {
  $('#some-div').appendTo('#some-other-div')
  // React still works now?
}, 5000)
```

Is it okay to do that?

**Comment by syranide** [comment]
It's OK to move the container like that, but FYI it's not OK to move the React rendered `<div>` inside the container (with the current API).

**Comment by trusktr** [comment]
Sweeet. Thanks. @syranide :]
