### ISSUE TITLE
checkbox 'checked' HTML attribute not set when underlying prop changes

### ISSUE THREAD

**Issue by jlas** [facebook/react#4646]
When rendering a checkbox the `checked` HTML attribute is not being properly set to reflect the `checked` prop of the `<input>` component.

The problem seems to be that the `setValueForProperty` method ([link](https://github.com/facebook/react/blob/v0.13.3/src/browser/ui/dom/DOMPropertyOperations.js#L128
)) sets the `checked` property on the DOM node object, but this will not update the `checked` HTML attribute, as seen in this fiddle: https://jsfiddle.net/1qdcdc5b/

The suggestion is instead to use `setAttribute` to set the `checked` property as it will set the underlying node property and the HTML attribute (as seen in the fiddle above).

**Comment by zpao** [comment]
I think the correct way of catching `checked` state in CSS is actually using the `:checked` pseudoclass. For example, take a regular checkbox and toggle it. `input[checked]` doesn't get applied. See https://jsfiddle.net/dz76f7yn/ (yours plus one w/o JS)

**Comment by jlas** [comment]
Using `:checked` will likely solve my use case. Thanks for pointing that out.

However, note that The `:checked` CSS pseudo class is a HTML5/CSS3 recommendation [1], and not available in older browsers like (IE < 9) [2]

Also note that according to HTML4 the `checked` attribute "specifies that the button is on", [3] [4]

Furthermore, the WHATWG HTML living standard notes that by adding the `checked` attribute the User Agent should set the checkedness to true, and vice-versa [5]. It also goes on talking about the abstraction of a "Command" which relies on certain attributes, namely `checked` [6]. Also under *Checkbox State > Bookeeping* the `checked` attribute is mentioned again [7].

One thing that is pointed out for certain is the `checked` attribute "gives the default checkedness of the input element" [5]. The [React Form docs](https://facebook.github.io/react/docs/forms.html#why-controlled-components) talks about maintaining an up-to-date `value` attribute, past its initialization value: "Unlike HTML, React components must represent the state of the view at any point in time and not only at initialization time". It seems like `checked` should follow that paradigm. Otherwise, it seems like something like the "reset algorithm" will work for `value` but not `checked` [8].

I think the last point also aligns with your observation that checking a checkbox on a live page will not add the `checked` attribute with vanilla JS. This, I believe, is what WHATG calls the `dirty checkedness` state [9], and probably reflects the (pre JS framework days) notion that the form has to be submitted first so that the external state of the checkbox match some server side value.

Anyway, I think others (and existing code) will expect the existence and proper setting of the `checked` attribute.

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#Specifications
[2] https://developer.mozilla.org/en-US/docs/Web/CSS/%3Achecked#Browser_compatibility
[3] http://www.w3.org/TR/REC-html40/interact/forms.html#h-17.2.1
[4] http://www.w3.org/TR/REC-html40/interact/forms.html#adef-checked
[5] https://html.spec.whatwg.org/multipage/forms.html#attr-input-checked
[6] https://html.spec.whatwg.org/multipage/forms.html#using-the-input-element-to-define-a-command:command-facet-checkedstate
[7] https://html.spec.whatwg.org/multipage/forms.html#checkbox-state-(type=checkbox):concept-input-apply
[8] https://html.spec.whatwg.org/multipage/forms.html#the-input-element:concept-form-reset-control
[9] https://html.spec.whatwg.org/multipage/forms.html#concept-input-checked-dirty-flag

**Comment by bloodyowl** [comment]
I think the simplest solution here is to create a `Checkbox` component which sets the `className` or `style` accordingly.

**Comment by jlas** [comment]
@bloodyowl as @zpao pointed out, using `:checked` solves the issue for me.

To your point and in general I would not recommend setting inline `styles` for HTML elements. Styles should exist in stylesheets and managed there.

The bigger question here is the semantic meaning of the `checked` attribute, its common use, and how much existing code relies on its existence / behavior.

**Comment by kevinSuttle** [comment]
My experience with this: 

1. This doc is confusing, making it sound like the `checked` prop _will_ be updated because it is "interactive". 
https://facebook.github.io/react/docs/forms.html#interactive-props

2. ` defaultChecked={this.state.checked}` doesn't update the `checked` prop or attribute when `state.checked` is toggled. Obviously, setting `checked={this.state.checked}` makes it a controlled component. 

3. To me at least, the mention of `value` and `defaultValue` in that same doc elude to the fact that the `value` attribute needs to be bound to the `checked` attribute.
