### ISSUE TITLE
Update Facebook Blog

### ISSUE THREAD

**Issue by AndrewBestbier** [facebook/react#4650]
So I was reading the following page: https://facebook.github.io/react/blog/2014/09/24/testing-flux-applications.html

I (stupidly) failed to notice the key words: 'A more up-to-date version of this post is available as part of the Flux documentation' and spent a while struggling with the code. My fault, but surely it would be better to just update the blog post?

**Comment by zpao** [comment]
No we're not going to do that (keeping 2 documents in sync is not worth the trouble) but we could do a better job of making that message at the top easier to see. Sorry you had trouble though!

**Comment by AndrewBestbier** [comment]
No worries and fair enough about it being tricky to keep two documents in sync. Another possibility would be deleting the article content and just provide the link? It seems unusual to keep outdated content on the website.

**Comment by spicyj** [comment]
May as well just delete it and set up a redirect? That's what we did for Thinking in React.
