### ISSUE TITLE
`findDOMNode` returns `null` in `ref` callback when rendering multiple times

### ISSUE THREAD

**Issue by menelaos** [facebook/react#4651]
I'm trying to use the `ref` attribute as described here:
https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

Unfortunately, `React.findDOMNode(component)` sometimes returns `null`, when 
`React.render` is called multiple times.

MWE:
```javascript
import React from "react";

class View extends React.Component {
  render () {
    return (
      <div>
        <input type="text"
               ref={c => console.log(React.findDOMNode(c))} />
      </div>
    );
  }
}

function render () {
  React.render( <View />
              , document.getElementById("container")
              );
}

setInterval(render, 1000); // Alternating beween null and <input ...>
```

**Comment by spicyj** [comment]
This is intended – when the component is unmounted or the ref changes, the old ref gets called with null before it's called with the new value (or the same component instance again). If you store the instance on your component, this effect should be unobservable as long as your component is mounted, but it prevents memory leaks. If you want to do something with `c` in the ref handler, you should check if it's null.

**Comment by menelaos** [comment]
Thanks for the information! I think this might be worth mentioning in the docs.
