### ISSUE TITLE
How to handle without having ref passing back the React Component.

### ISSUE THREAD

**Issue by crohde7707** [facebook/react#4671]
Hello All!

Take the following snippit
```javascript
   //component
   export default React.createClass({
      getInitialState: function() {
         return {
            error: "",
            valid: true
         }
      },
      isValid: function() {
         return this.state.valid;
      },
      setValid: function(isValid) {
         this.setState({
            valid: isValid
         });
      },
      //...
      render: function() {
         return (
            <div className="myComponent">
               <input className={this.state.valid ? "valid" : ""} size=20 />
               <span className={this.state.valid ? "valid" : ""}>{this.state.error}</span>
            </div>
         )
      }
   })
   //Parent
   export default React.createClass({
      handleClick: function() {
         var comp = this.refs.comp;

         comp.setValid(false)
         comp.setError("Needs a value");
      },
      render: function() {
         return (
            <div>
               <MyComponent ref="comp"/>
               <button onClick={this.handleClick}>Click</button>
            </div>
         )
      }
   })
```

Before the update to refs, where it passed back the React component, i was able to access helper methods on this class to handle certain pieces of state, like if the component was valid, or what error message is being displayed. Now in 0.14, it actually returns the DOM node. I understand that everything can be done in javascript to modify the DOM (i.e. Take the message and just change the node's innerHTML to the message), it just adds extra that must be done that i feel was a good fit for modifying the state. Is this way of thinking more of an anti-pattern, or was this not considered due to not seeing many people accomplishing this sort of thing?

**Comment by jimfb** [comment]
Did you actually try it?  We only pass the DOM node instead of the instance for DOM components (not composite components, like the one in this example), since finding the DOM node was the only thing you could do with a DOM component anyway.  In your case, I believe it'll all just work the way you're hoping.  Let me know if you're actually running into a problem in your code with 0.14.

In general, questions like this are better addressed on StackOverflow.  We use github issues to track bugs in React, so I'm going to close this out.  Feel free to continue the discussion here.

**Comment by crohde7707** [comment]
Ahh makes sense
 > # DOM node refs
 >The other big change we're making in this release is exposing refs to DOM components as the DOM node itself. That means: we looked at what you can do with a ref to a DOM component and realized that the only useful thing you can do with it is call this.refs.giraffe.getDOMNode() to get the underlying DOM node. In this release, this.refs.giraffe is the actual DOM node.
 >
 > **Refs to custom component classes work exactly as before.**

This was the piece of the documentation that i managed to miss when reading the update, sorry! Didn't want to bring down 0.14 yet because i saw this, and it would have caused a lot of refactoring if it was the case. After pulling it down, it works as expected, like stated. Sorry again! :)
