### ISSUE TITLE
comments.json location confusing in tutorial docs

### ISSUE THREAD

**Issue by stickperson** [facebook/react#4673]
The tutorial says to create a static JSON file in `public/comments.json`. However, in the tutorial repository this file is in the root directory. If you use the node server implementation from the repo and create the `comments.json` file in the `public/` directory, the server crashes when submitting a comment. Everything works fine when the file is in the root directory as it is in the tutorial repo.

The documentation for the location of the `comments.json` file should be consistent with what's in the repo so a user can just grab a server implementation from there and go.

**Comment by zpao** [comment]
Yea, this is annoying. It's not wrong at the beginning (before you need the server) but then it is wrong. We need to tweak this part of the tutorial and probably just require a server. See more discussion in https://github.com/reactjs/react-tutorial/issues/67.

**Comment by stickperson** [comment]
Ah, didn't see the other issue. Thanks!
