### ISSUE TITLE
"webkit-playsinline" attribute in JSX is not supported

### ISSUE THREAD

**Issue by djyde** [facebook/react#4676]
Hi, the 'webkit-playsinline' in JSX will be ignored. Is there any solution to solve this problem?

```jsx
<video webkit-playsinline controls src='foo' poster='bar' style={ videoStyle }></video>
```

**Comment by aprilorange** [comment]
It's because `webkit-playsinline` is a non-standard attribute in React, [view code](https://github.com/facebook/react/blob/80b7391d64d92c74633f68cfff250819cf064af1/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L46)

https://github.com/facebook/react/issues/140 might help

**Comment by djyde** [comment]
At last I use pure DOM to add this attribute. JSX suck, hah.

**Comment by egoist** [comment]
这个锅应该 React 背，JSX 是转换了这个 attr 的。

**Comment by djyde** [comment]
I should say Virtual DOM suck

**Comment by cheapsteak** [comment]
@djyde 刚被公司聊天室链接到这条issue上。太不礼貌了，非得吐槽请用中文，别给中国人丢脸。

**Comment by egoist** [comment]
@cheapsteak 我觉得要吐槽 Virtual Dom 什么理由都可以，只要是当事者觉得不爽的，要不然拿 issue 来干毛？和礼不礼貌没办毛钱关系，更别提给中国人丢脸。

suck 可以指 somewhere suck，难道 Virtual Dom 是完美的存在，不能 suck 一下？

况且，我觉得你的后半句更值得商榷哦。（QQ空间体？

// maintainers please ignore this comment.

**Comment by cheapsteak** [comment]
I may have misunderstood what 吐槽 means. 
By all means open issues and complain about bugs and other imperfections, but that can be done without being flippant and rude.

It's possible that he didn't mean for it to come off that way, but that would be a great reason to only 用中文吐槽； 能为自己言语不敬的程度负责

**Comment by egoist** [comment]
@cheapsteak 请不要继续污染这个 issue，如有需要请打开我的个人页面那有邮箱。

// maintainers please ignore this comment.

**Comment by djyde** [comment]
@cheapsteak I opened this issue for asking an solution. Not for complaining.

**Comment by gztchan** [comment]
#780

**Comment by gztchan** [comment]
b90fdb6

**Comment by gztchan** [comment]
v15.3.0 supports `playsInline` 😄

**Comment by marktani** [comment]
I am on `15.3.2` and still get this error:

```
ERROR in [default] Property 'playsInline' does not exist on type 'HTMLProps<HTMLVideoElement>'.
```

**Comment by Aweary** [comment]
@marktani looks like an error with your type system, specifically the type `HTMLVideoElement`. If you're using flow, then it looks like the included DOM lib [doesn't have playsInline](https://github.com/facebook/flow/blob/master/lib/dom.js#L2409-L2415) on `HTMLVideoElement`

**Comment by marktani** [comment]
I use TypeScript. In my case I don't really need `playsInline`, was just curious. thanks for the clarification!

**Comment by ufohjl** [comment]
能不能自定义?

**Comment by fwchen** [comment]
丢不丢人？
