### ISSUE TITLE
How can we disable checksumming and sanity checks?

### ISSUE THREAD

**Issue by mufumbo** [facebook/react#4681]
This doesn't seem to be documented anywhere, but mentioned to be possible here:
https://github.com/facebook/react/issues/3009

There are any parameters, line of code we can change, etc?

Also, welcome are any other insight about things to disable to make the render process faster cpu wise?

**Comment by zpao** [comment]
There are no parameters or flags, it will involve basically forking React. This is why nothing is documented. It's really not worth it for us to guide you through this so I'll point you in the right direction and leave you to it.

For the checksum related stuff, look for uses of the `ReactMarkupChecksum` module.

As for disabling sanity checks, we have a bunch of invariants and other checks throughout the codebase. There's no 1 place to disable these. You would have to decide which ones are important and which aren't.

**Comment by mufumbo** [comment]
thanks @zpao . 

Will try to document it back here if we ever be able to make React + node useable for isomorphic applications that aren't just for demo purposes.
