### ISSUE TITLE
How to get react-dom to run with webpack.

### ISSUE THREAD

**Issue by Moezalez** [facebook/react#4693]
Hi!

So, I always get the message:
```
Warning: `require("react").render` is deprecated. Please use `require("react-dom").render` instead.
```

So naive as I am, I just put this in my console:
```
npm install react-dom
```

Which got me this: https://github.com/EtienneLem/react-dom
This has mayor issues with webpack as mentioned here: https://github.com/EtienneLem/react-dom/issues/1

So, the answer is: Wrong repository..

Where do I get the correct react-dom module?

**Comment by Moezalez** [comment]
Installing this helped:
```
npm install react-dom@latest
```

**Comment by nettred** [comment]
Chips up to 50 to 100m will be givenaway

**Comment by zpao** [comment]
Yea, I think npm is treating this like a prerelease and ignoring it, even though it's published at `latest` (which I thought npm used by default but apparently not). Sorry for the confusion. I don't think there's a good way to handle this unfortunately :(
