### ISSUE TITLE
Using server rendering: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`

### ISSUE THREAD

**Issue by justin808** [facebook/react#4696]
I'm building a gem to enable the use of React + Redux + Rails with Webpack and server rendering.

I'm pretty far along, having gotten the gem to work with turbolinks. However, I'm running into an issue with fragment caching. 

I created a branch which demonstrates the issue: https://github.com/shakacode/react_rails_server_rendering/tree/caching-failure

NOTE: I verified that caching *without* Turbolinks works OK. See this branch: https://github.com/shakacode/react_rails_server_rendering/tree/caching-ok-without-turbolinks

Also, no caching with turbolinks works:
https://github.com/shakacode/react_rails_server_rendering/tree/master

## The issue can be reproduced by the following:
1. clone the repo
2. switch to the branch caching-failure
3. `cd spec/dummy && bundle && npm i && foreman start`
4. Visit http://localhost:3000
5. See server rendering worked. Open up console. See tracing messages.
6. Click on link "About" at top.
7. Click back on link "React" at top.
8. See error message: "Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid" (Full error below).

## Notes:
* Open up spec/dummy/app/views/pages/index.html.erb and remove the
  cache block around line 16 to see this working without fragment caching.
* With fragment caching, we're removing the React dom elements from the
  prior rendering to and reloading from cache.
* Left in tracing statements so we can see when the rendering is called.
* It is unlikely that the caching changed the rendering part, which
  includes both:
  * Call to add/remove listeners which invoke the client side rendering
  after the dom elements are placed.
  * Server generated HTML is shown below, which includes the setup of the JS hooks. This code is inserted into the DOM by turbolinks.

## Possible Reason
I'm guessing there is some problem with calling React with the same exact code on the second time. It seems some state is maintained. Maybe when the page is being unloaded, I need to tell React about this?

## Here's what the view helper looks like
```erb
<!-- This works if we turn off server side rendering -->
<!--< % cache @app_props do %>-->
  <% puts "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" %>
  <% puts "server rendering react component" %>
  <% puts "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" %>
  <%= react_component("App", @app_props) %>
<!--< % end %>-->
```

## Here's the html:
```html
        <script>
//<![CDATA[
      window.__appData__ = {"helloWorldData":{"name":"Prop from Rails from server rendering!"}};
      var renderIfDomNodePresent = function() {
  var appDOMNode = document.getElementById('App-react-component-0');
  if (appDOMNode) {
    console.log("ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ");
    console.log("DID CLIENT SIDE RENDER");
    console.log("ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ");
    var reactComponent = App(__appData__);
    React.render(reactComponent, appDOMNode);
  }
}

            var turbolinksInstalled = typeof(Turbolinks) !== 'undefined';
      console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
      console.log("turbolinksInstalled is %O", turbolinksInstalled);
      console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
      if (!turbolinksInstalled) {
        console.log("WARNING: NO TurboLinks detected in JS, but it's in your Gemfile");
        document.addEventListener("DOMContentLoaded", function(event) {
  console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
  console.log("DOMContentLoaded event fired");
  console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
  renderIfDomNodePresent();
});

      } else {
        function onPageChange(event) {
          console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
          console.log("page:change event fired");
          console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
          var removePageChangeListener = function() {
            console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
            console.log("removed page:change event listener fired");
            console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
            document.removeEventListener("page:change", onPageChange);
            document.removeEventListener("page:before-unload", removePageChangeListener);
            console.log("removed both event listeners");
          };
          document.addEventListener("page:before-unload", removePageChangeListener);

          document.addEventListener("page:after-remove", function() {
            console.log("page:after-remove called")
          });

          renderIfDomNodePresent();
        }
        console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
        console.log("Add turbolinks handler page:change handler");
        console.log("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY");
        document.addEventListener("page:change", onPageChange);
      }


//]]>
</script>
      <div id="App-react-component-0"><div data-reactid=".cwh6q4xzwg" data-react-checksum="1276941928"><h1 data-reactid=".cwh6q4xzwg.0"><span data-reactid=".cwh6q4xzwg.0.0">Hello, </span><span data-reactid=".cwh6q4xzwg.0.1">Prop from Rails from server rendering!</span><span data-reactid=".cwh6q4xzwg.0.2">!</span></h1><p data-reactid=".cwh6q4xzwg.1"><span data-reactid=".cwh6q4xzwg.1.0">Say hello to: </span><input type="text" value="Prop from Rails from server rendering!" data-reactid=".cwh6q4xzwg.1.1"></p></div></div>
```

![cursor_and_dummy](https://cloud.githubusercontent.com/assets/1118459/9435316/6f36c57c-49e2-11e5-9981-f297681db0cf.png)

```
Uncaught Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .cwh6q4xzwginvariant @ client.self-7a1dcfd3851d1e743119029e3453caa6110fd4559ba3db66c56cbdb87f97a01c.js?body=1:759getID @ client.self-7a1dcfd3851d1e743119029e3453caa6110fd4559ba3db66c56cbdb87f97a01c.js?body=1:7712getReactRootID @ client.self-7a1dcfd3851d1e743119029e3453caa6110fd4559ba3db66c56cbdb87f97a01c.js?body=1:7693render @ client.self-7a1dcfd3851d1e743119029e3453caa6110fd4559ba3db66c56cbdb87f97a01c.js?body=1:7988wrapper @ client.self-7a1dcfd3851d1e743119029e3453caa6110fd4559ba3db66c56cbdb87f97a01c.js?body=1:3099renderIfDomNodePresent @ VM26889:11onPageChange @ VM26889:47triggerEvent @ turbolinks.self-c37727e9bd6b2735da5c311aa83fead54ed0be6cc8bd9a65309e9c5abe2cbfff.js?body=1:334changePage @ turbolinks.self-c37727e9bd6b2735da5c311aa83fead54ed0be6cc8bd9a65309e9c5abe2cbfff.js?body=1:203xhr.onload @ turbolinks.self-c37727e9bd6b2735da5c311aa83fead54ed0be6cc8bd9a65309e9c5abe2cbfff.js?body=1:107
```

**Comment by syranide** [comment]
Do you ever replace `#App-react-component-0` or its content manually? Or apply the cached HTML multiple times? From what you've posted in this issue the error doesn't really make sense, by the looks of it React complains because it has mounted the cached HTML and now it's trying to mount the cached HTML again...

PS. Just to be sure, you're aware that `React.unmountComponentAtNode` must be used before clearing React rendered DOM right?

**Comment by justin808** [comment]
@syranide That looks promising! I'll try that.

```
React.unmountComponentAtNode
boolean unmountComponentAtNode(DOMElement container)
Remove a mounted React component from the DOM and clean up its event handlers and state. If no component was mounted in the container, calling this function does nothing. Returns true if a component was unmounted and false if there was no component to unmount.
```

**Comment by justin808** [comment]
@syranide That worked! I updated:

https://github.com/shakacode/react_rails_server_rendering/

Feedback is appreciated if anybody is interested in server rendering with Rails + Webpack + Redux

**Comment by syranide** [comment]
@justin808 Glad to hear, however I'm curious why you're using cached markup client-side. It makes sense to ship it from server to client for the initial load (largely for SEO really), but once the initial mount has occurred there's no need to mount cached markup before rendering.

**Comment by justin808** [comment]
@syranide I make *HEAVY* use of fragment caching in rails. Why would you not want to cache the markup and the hydration of the client stores? If that is done, then the rails server does not need to run execJs to evaluate the javascript to produce the rendering. Pulling from the cache should be very fast.

So there's both the SEO and the caching benefite of the server rendering. @alexfedoseev Any opinion?
