### ISSUE TITLE
Components as classes: which methods are bound?

### ISSUE THREAD

**Issue by agraboso** [facebook/react#4699]
I'm writing a few components as ES2015 classes, and I'm trying to understand which methods I should bind in the constructor.

Say I have something like the following code.
```js
import { Component } from 'react'

export default class ComponentName extends Component {
  constructor() {
    super();
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(e) {
    ...
  }

  render() {
    return <div onClick={this.handleClick} />;
  }
}
```
I understand that I must explicitly bind `handleClick` in the constructor (short of using some ES7 stage 0 features). But from this and other examples I've seen, it looks like the `render` method is bound by default &mdash; that is, I don't need to do something like
```js
this.render = this.render.bind(this);
```
in the constructor. Am I right? How about lifecycle methods like `componentDidMount`? The v0.13 documentation is unclear about this.

Also, is there anything planned for v0.14 that would change this behavior?

**Comment by zpao** [comment]
Lifecycle methods are bound as our methods that are a part of the base class (eg, setState). Nothing planned that would change this.

**Comment by agraboso** [comment]
Thanks for the clarification. I think this should go in the docs though.
