### ISSUE TITLE
Work with compile-to-JS languages (like CoffeeScript)

### ISSUE THREAD

**Issue by edc** [facebook/react#47]
JSX is nice, but those using compile-to-JS language have to change the transpiler to connect to the JSX compiler. Is there any chance of adding alternative DOM syntax to JSX so it does not break every compile-to-JS language? Something `gettext`-style would be nice. So in addition to:

```
var HelloMessage = React.createClass({
  render: function() {
    return <div>{'Hello ' + this.props.name}</div>;
  }
});
```

it would be nice to support

```
var HelloMessage = React.createClass({
  render: function() {
    return _dom_("<div>{'Hello ' + this.props.name}</div>");
  }
});
```

**Comment by anthonybrown** [comment]
+1 @KyleAMathews
