### ISSUE TITLE
Transfer context

### ISSUE THREAD

**Issue by s-panferov** [facebook/react#4706]
Hello. In my project I'm using technique similar to http://jamesknelson.com/rendering-react-components-to-the-document-body/. Here we take `this.props.children` and render them inside another React tree, connected to a `body` child node.

The problem here is that `this.props.children` or its descendants may want a context, but it is empty for the separate tree, because we use fresh `ReactDOM.render` call. Right now I'm using the function like:

```js
export function extractContext(component) {
    let context = {};
    if (component._reactInternalInstance && component._reactInternalInstance._context) {
        let internalContext = component._reactInternalInstance._context;
        for(let key in internalContext) {
            if (internalContext.hasOwnProperty(key) && key[0] !== '_') {
                context[key] = internalContext[key];
            }
        }
    }

    return context;
}
```

To extract context inside my popup and then I create a wrapper that takes that context and pushes it down to the new tree. Maybe there is a better way to transfer entire context into `ReactDOM.render` without the knowledge about context's internals?

**Comment by spicyj** [comment]
```
ReactDOM.unstable_renderSubtreeIntoContainer(this, <Foo />, container)
```

**Comment by kof** [comment]
@spicyj is this issue addressed by now? I stumbled over exact same issue and there is still no legal method to create elements with provided context.

**Comment by spicyj** [comment]
You can use unstable_renderSubtreeIntoContainer to inherit it from a parent component.
