### ISSUE TITLE
 react-dnd + proxyquire -> Invariant Violation: Could not find the drag and drop manager in the context MyComponent

### ISSUE THREAD

**Issue by cmelion** [facebook/react#4707]
I've been using proxyquire to stub out sub-components and stores but ran into an Invariant Violation with components that are wrapped in react-dnd contexts.

Warning: Failed Context Types: Required context dragDropManager was not specified in DragSource(Card).

Error: Invariant Violation: Could not find the drag and drop manager in the context of Card. Make sure to wrap the top-level component of your app with DragDropContext. Read more: http://gaearon.github.io/react-dnd/docs-troubleshooting.html#could-not-find-the-drag-and-drop-manager-in-the-context

I put together a repo to demonstrate the error:  see https://github.com/cmelion/react-hot-boilerplate/tree/Invariant-Violation-DND

run:
```
npm install 
npm test
```

**Comment by cmelion** [comment]
https://github.com/gaearon/react-dnd/issues/268
https://github.com/thlorenz/proxyquire/issues/76

**Comment by cmelion** [comment]
Issue resolved.

**Comment by spicyj** [comment]
This is not at all a React error. Please try to read the error message and figure out what project is related instead of opening three issues.

**Comment by cmelion** [comment]
@spycyj Well I just kept going down the line and nobody claimed responsibility so you just got lucky I guess ;-)

**Comment by spicyj** [comment]
Sometimes it's your fault, not any of ours.

**Comment by cmelion** [comment]
@spycyj  interesting perspective, I can't wait for Angular 2.0, now there's a community.

**Comment by syranide** [comment]
@cmelion I'm sure spicyj didn't mean it that way. Anyhow, we want to keep GH issues focused on development of React, if you have questions or problems of your own please use https://discuss.reactjs.org/ or StackOverflow instead.

**Comment by dmatteo** [comment]
@cmelion This is very juvenile reply, hopefully you also know that.

**Comment by cmelion** [comment]
@syranide Thank you, that was the advice and response I had hoped for.

**Comment by gaearon** [comment]
Sorry this got a bit tense. To help put things in perspective, I'm using [React's "context" feature](www.youtube.com/watch?v=H7vlH-wntD4) in React DnD (as you see in the message) that React never supported officially and in fact discourages using. There are many libraries doing this (e.g. React Router) but again, this was never an official API, and I bet React folks are tired of context issues because they are not ready to support it yet, and they know it's broken in some ways.

**Comment by spicyj** [comment]
@cmelion Thank you.
