### ISSUE TITLE
Misleading warning message when using getDOMNode

### ISSUE THREAD

**Issue by gajus** [facebook/react#4710]
It says:

> Warning: getDOMNode(...) is deprecated in plain JavaScript React classes. Use React.findDOMNode(component) instead.

Then when you use `React.findDOMNode` you will get:

> Warning: `require("react").findDOMNode` is deprecated. Please use `require("react-dom").findDOMNode` instead.

Therefore, the error message should be:

> Warning: getDOMNode(...) is deprecated in plain JavaScript React classes. Use `require("react-dom").findDOMNode` instead.

**Comment by spicyj** [comment]
Good catch, thank you.

**Comment by spicyj** [comment]
I wonder what we should do with references to "React.render" in ReactClass.js and ReactElement.js.
