### ISSUE TITLE
Use reactid to get the instance of the associated component

### ISSUE THREAD

**Issue by gajus** [facebook/react#4711]
When iterating React DOM tree, how do I distinguish between DOM generated by different components? e.g.

```
<div ref='target'>
    <p>Foo</p>
    <Bar />
</div>
```

Now when I iterate `this.refs.target` `nodeList`, how do I distinguish children of the target and other component nodes?

I am thinking that I could use `reactid` to retrieve the instance of the associated component. Is there an API for that? Where is this data held?

**Comment by spicyj** [comment]
We don't have any supported way to do this. Your best bet is probably to add more wrapper components so you have

```
<div ref="target">
  <div ref="foo">
    <p>Foo</p>
  </div>
  <div ref="bar">
    <Bar />
  </div>
</div>
```

or similar. (If you can explain more about your use case, perhaps I can suggest a better solution.)

**Comment by gajus** [comment]
@spicyj Thank you for offering help.

I am working on https://github.com/gajus/react-css-modules.

It is a version of [css-modules](https://github.com/css-modules/css-modules) that is supposed to seamlessly integrate with React components using higher order component, e.g.

`index.css`:

```css
.foo {
    color: #f00;
}
```

`Rainbow.js`:

```js
import React from 'react';
import styles from './index.css';
import CSSModules from 'react-css-modules';

class Rainbow extends React.Component {
    render () {
        return <div>
            <span className='foo'>I am rainbow!</span>
            <span className='bar'>I am rainbow!</span>
        </div>;
    }
}

export default CSSModules(Rainbow, styles);
```

When used, this component will generate:

```html
<div data-reactid=".0">
    <div data-reactid=".0.0">
        <span class="foo index__foo___1fSgh" data-reactid=".0.0.0">I am rainbow!</span>
        <span class="bar" data-reactid=".0.0.1">I am rainbow!</span>
    </div>
</div>
```

I have managed to make it work with ReactElement:

```js
let test;

test = <div>
    <div className='foo'>Foo</div>
    <div className='bar'>Bar</div>
</div>;

// This works!
return linkClass(test);
```

[./987aa76c3db305627206db4687ba13eaea70e581/src/index.js#L79-L87](https://github.com/gajus/react-css-modules/blob/987aa76c3db305627206db4687ba13eaea70e581/src/index.js#L79-L87)

But I cannot figure out how to make it work when dealing with component:

```js
// Not sure how to make this work...
// At this point I would need to use linkClass, but I cannot find a way to access
// children of Target.
return <Target ref='test' />;
```

I would appreciate suggestions however hacking they are. I am looking for a solution that would not require modifying the child component (`Target` in this case) implementation.

**Comment by spicyj** [comment]
We don't have any supported way to do this because you're breaking encapsulation of the inner components (e.g., Target) and changing what it renders to something other than what it intended. You can look in the DOM for nodes with a certain class but you're more or less on your own then.

**Comment by gajus** [comment]
@spicyj Here is what I was building, https://github.com/gajus/react-css-modules. I found a better way to achieve the goal by extending the `render()` method.

Thank you for the help. : )
