### ISSUE TITLE
0.14 requires extra configuration to typecheck with Flow

### ISSUE THREAD

**Issue by samwgoldman** [facebook/react#4713]
If I create a brand new project directory, create a `.flowconfig`, `npm install react@0.14.0-beta3`, and type check a very simple file:

```javascript
var React = require("react");
```

I am faced with a bunch of errors from `flow check`:

```
example/node_modules/react/node_modules/fbjs/flow/include/Deferred.js:39:15,15: return
Missing annotation

example/node_modules/react/node_modules/fbjs/flow/include/PromiseMap.js:15:16,34: Deferred
Required module not found

example/node_modules/react/node_modules/fbjs/flow/include/PromiseMap.js:17:17,36: invariant
Required module not found

example/node_modules/react/node_modules/fbjs/flow/include/fetchWithRetries.js:16:28,58: ExecutionEnvironment
Required module not found

example/node_modules/react/node_modules/fbjs/flow/include/fetchWithRetries.js:19:15,32: sprintf
Required module not found

example/node_modules/react/node_modules/fbjs/flow/include/fetchWithRetries.js:20:13,28: fetch
Required module not found

example/node_modules/react/node_modules/fbjs/flow/include/fetchWithRetries.js:21:15,32: warning
Required module not found
```

It's easy to work around: just add the following configuration to `.flowconfig`:

```
[ignore]
.*/react/node_modules/.*
```

This is exactly what the Relay project does. However, it'd be great if people could follow the steps from the beginning of this issue (create `.flowconfig`, `npm install react`) and have a more "turnkey" working system without any further required configuration.

Maybe this is a fbjs bug and not a React bug? I wasn't sure the best place to file this one, but if it belongs somewhere else I'm happy to redirect this.

Thanks!

**Comment by zpao** [comment]
This is probably more a flow issue than anything, but definitely annoying. We'll want to have this documented in some way soon. I think what we need is the ability to compose flowconfigs so that we could stack ignores, though maybe it's something we can address in fbjs. It was brought up there the other day so let's continue over in that issue (https://github.com/facebook/fbjs/issues/44)
