### ISSUE TITLE
Communication betwen components

### ISSUE THREAD

**Issue by mohitbhatia1994** [facebook/react#4715]
My application is a list with filters and a button to change the layout. I'm using two components: <list /> and < Filters />. When I change settings in < Filters /> I want to trigger some method in <list /> to update my view.

How can I make components interact with each other?

**Comment by koulmomo** [comment]
pass [update functions as props](https://facebook.github.io/react/docs/thinking-in-react.html#step-5-add-inverse-data-flow), or use [flux](https://facebook.github.io/flux/docs/overview.html)

you should probably move this question to [stackoverflow](https://stackoverflow.com/questions/tagged/reactjs) or [discuss.reactjs.org](https://discuss.reactjs.org/) instead though
