### ISSUE TITLE
React Component lose context with seq.map

### ISSUE THREAD

**Issue by charlie-rudenstal** [facebook/react#4722]
I originally posted this issue over at immutable-js, but was advised to move it here. 
(original at https://github.com/facebook/immutable-js/issues/554)

React Components lose context when used within a seq.map. Possibly due to lazy evaluation.
```
{Immutable.fromJS([1,2]).toSeq().map(_ => 
    <NavLink routeName="foo">bar</NavLink>)}
```
This fails with `Failed Context Types: Required context getStore was not specified in RouteHandlerStoreConnector.`

```
{Immutable.fromJS([1,2]).toSeq().map(_ => 
    <NavLink routeName="foo">bar</NavLink>)
 .toArray()}
```
When resolving the sequence explicitly, like above, it works. 

Is this expected behavior? My understanding is that converting Immutables to sequences is the recommended procedure before passing them to React.

**Comment by spicyj** [comment]
This will work in 0.14.
