### ISSUE TITLE
When using JSX, ReactElement children are presented as an array as opposed to a map

### ISSUE THREAD

**Issue by gajus** [facebook/react#4723]
I came across while making test cases for https://github.com/gajus/react-css-modules that had to make sure that I am not mutating `ReactElement` in an unexpected ways when making a clone of it.

```js
console.log(<div><p></p><p></p></div>);
```

Notice that `children` property is a list.

```js
{
    type: 'div',
    key: null,
    ref: null,
    _owner: null,
    props: {
        children: [
            [Object],
            [Object]
        ]
    },
    _store: {}
}
```

Now if I attempt to clone this tree (and presumably doing something with the child nodes):

```js
let targetElement,
    newChildren,
    clonedElement;

targetElement = <div><p></p><p></p></div>;

newChildren = React.Children.map(targetElement.props.children, (node) => {
    // Do something with the children nodes.
    return React.cloneElement(node);
});

clonedElement = React.cloneElement(targetElement, undefined, newChildren);

console.log(clonedElement);
```

I get:

```js
{
    type: 'div',
    key: null,
    ref: null,
    _owner: null,
    props: {
        children: {
            '.0': [Getter/Setter],
            '.1': [Getter/Setter]
        }
    },
    _store: {}
}
```

Notice that `children` property is now a map.

I consider this unexpected mutation. I have tried remediating this using `Object.values`, i.e., 

```js
let targetElement,
    newChildren,
    clonedElement;

targetElement = <div><p></p><p></p></div>;

newChildren = React.Children.map(targetElement.props.children, (node) => {
    // Do something with the children nodes.
    return React.cloneElement(node);
});

clonedElement = React.cloneElement(targetElement, undefined, Object.values(newChildren));

console.log(clonedElement);
```

It produces an identical object to the original, but it also prompts the following error:

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the React.render call using <div>. See https://fb.me/react-warning-keys for more information.
```

It is a bit odd, considering that all I do is create an identical copy of the original JSX output object.

This appears as unexpected JSX parser behaviour. This might Babel issue too.

**Comment by syranide** [comment]
This is expected behavior (children being a map) with `React.cloneElement`, cc @spicyj

**Comment by gajus** [comment]
@syranide Sorry, should have been clear. Yes, I expect `React.Children.map` to produce map. I am surprised that using JSX to construct ReactElement hierarchy uses list.

**Comment by spicyj** [comment]
Yes, JSX always makes an array. In 0.14 React.Children.map() will return an array too.

**Comment by gajus** [comment]
@spicyj These examples are produced using 0.14.0-beta3, though. I am guessing it is a planned change then.

**Comment by gajus** [comment]
Does this mean that "key" (https://facebook.github.io/react/docs/special-non-dom-attributes.html) unique identifier is going to be come redundant as well?

**Comment by spicyj** [comment]
Yes, I merged it in #4700. Nothing is changing about how key works – why would it be redundant?

**Comment by gajus** [comment]
Just in reference to the error I got when using array.

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the React.render call using <div>. See https://fb.me/react-warning-keys for more information.
```

**Comment by spicyj** [comment]
When you write the elements inline in JSX like `<div><p></p><p></p></div>`, React doesn't ask you to add `key` attributes since it's unlikely you'll reorder them. When you write `<div>{paragraphs}</div>` you do need the keys. React.Children.map copied over the implicitly-added keys in the first case so you didn't see the warning, but mapping the array yourself wouldn't copy the keys. In 0.14, React.Children.map will still copy the keys automatically but it will return an array.

**Comment by gajus** [comment]
Thank you for the explanation.
