### ISSUE TITLE
ReactElementValidator.loggedTypeFailures prevents test isolation

### ISSUE THREAD

**Issue by ryanwilsonperkin** [facebook/react#4725]
I'm running React v0.13.3 and testing with jasmine-core v2.3.4.

When testing my component validation, I use jasmine's `spyOn` method to mock out `console.warn` and check that `TestUtils.renderIntoDocument` will trigger a warning with the correct message when validation fails. I use `expect(console.warn).toHaveBeenCalledWith(...)` to check that validation is working.

I run the same unit test, in two separate test suites (`tests/fileA.js` and `tests/fileB.js`) that expects the warning to occur. Because React globally tracks which warnings have been triggered (to avoid spamming the console it seems) it doesn't send the warning the second time, and thus fails.

I would expect that `TestUtils.renderIntoDocument` would setup isolation for each render so that warnings can be checked properly.

**Comment by NickPresta** [comment]
This seems related to https://github.com/facebook/react/issues/4302

**Comment by spicyj** [comment]
Yeah, I'll close this in favor of #4302.
