### ISSUE TITLE
Rendering input element to string, then setting html dangerously doesn't fire onChange anymore

### ISSUE THREAD

**Issue by Radivarig** [facebook/react#4729]
I have the following input element:
```
   var InputElement = <input onChange={function(e){console.log(e.target.value)}} />
```
if I return like this, callback is fired on input change
```
    return InputElement
```
however, if I do the following, onChange will **not** be called
```
    return (
      <div dangerouslySetInnerHTML={{__html: React.renderToString(InputElement)}} />
    )
```
How can I preserve the onChange?

**Comment by browniefed** [comment]
This is more suited for StackOverlfow. However you are rendering to a string which React will not attach event listeners to since it's not an actual React element you are rendering.
If you want to add event listeners for dangerouslySetInnerHTML then you'll have to manually wire those up.

How can you preserve the onChange? Don't render to string and don't use dangerouslySetInnerHTML.

**Comment by spicyj** [comment]
You can return the element, like you said. renderToString doesn't include the event handlers and there's no real way for us to make that happen. If you give more details maybe I can be more helpful.

**Comment by Radivarig** [comment]
I am rendering to string because I need markdown parser to insert tags around react elements, and it takes and returns a string.

So I can achieve transformation from:
```
<span>this is span before **</span>
  <ReactComponent/>
<span>** and span after component</span>
```
to:
```
<span>this is span before </span>
  <strong>
    <ReactComponent/>
  </strong>
<span> and span after component</span>
```

**Comment by spicyj** [comment]
This is hard to do without support from the markdown engine. You can try using https://github.com/Khan/simple-markdown or https://github.com/spicyj/marked-react.

**Comment by Radivarig** [comment]
Khan's markdown generates react elements, similarly what I have is a string parser that inserts react elements (like input) so I could just move it to Khan's extensions. Awesome, thanks!

**Comment by Radivarig** [comment]
@spicyj,
atm simple-markdown's examples are not working,
however I managed to get what I need with your fork of marked!! Thanks a bunch! Cheers :)
