### ISSUE TITLE
Shallow rendering uses `.type` and throws deprecations

### ISSUE THREAD

**Issue by aaronjensen** [facebook/react#4730]
When calling `renderer.render()` I get:

```
Warning: Foo.type is deprecated. Use Foo directly to access the class
```

It seems to be here, and a few other places: 

https://github.com/facebook/react/blob/master/src/test/ReactTestUtils.js#L418

I wonder if https://github.com/facebook/react/pull/4009 broke this entirely...

**Comment by spicyj** [comment]
`.type` on a React *element* still works. It does not work on React classes. It sounds like you're doing `.render(Foo)` instead of `.render(<Foo />)`.

**Comment by aaronjensen** [comment]
Spot on @spicyj, thanks for the pointer. The funny thing is it totally worked otherwise... It may be nice if that was an invariant.

**Comment by spicyj** [comment]
Okay.
