### ISSUE TITLE
react-build@0.14.0-beta3 postinstall throw assert.AssertionError

### ISSUE THREAD

**Issue by john-difool** [facebook/react#4738]
> react-build@0.14.0-beta3 postinstall /Users/johndifool/Develop/facebook/react
> node scripts/check-dev-engines.js

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: Current node version is not supported for development, expected "0.12.7" to satisfy "0.10.x".
    at Object.<anonymous> (/Users/johndifool/Develop/facebook/react/scripts/check-dev-engines.js:18:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! react-build@0.14.0-beta3 postinstall: `node scripts/check-dev-engines.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-build@0.14.0-beta3 postinstall script 'node scripts/check-dev-engines.js'.
npm ERR! This is most likely a problem with the react-build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/check-dev-engines.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-build
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johndifool/Develop/facebook/react/npm-debug.log

**Comment by spicyj** [comment]
Please read the error message.
