### ISSUE TITLE
Getting "dangerouslyReplaceNodeWithMarkup" error on unit tests with jsdom and jasmine.

### ISSUE THREAD

**Issue by nripendra** [facebook/react#4740]
This happens only when executing unit tests, works fine on browser though. using dangerouslySetInnerHTML attribute did once solve the problem but this exception is thrown again as soon as I add a new test case.

Some observations:
- Happens with jsdom, in webkit its working fine.
- Happens on rendering of view when event is simulated.
- Happens when rendering string variables inside markup.
- dangerouslySetInnerHTML does solve it once.

FYI, if you need exact steps, I have been explaining exact steps I'm following in the series of my blog posts. I'm referring to solving this problem by using "**dangerouslySetInnerHTML**" property here: [http://blogs.nnn.ninja.np/fb-messenger/2015/08/23/Learning-js-technologies-part7/](http://blogs.nnn.ninja.np/fb-messenger/2015/08/23/Learning-js-technologies-part7/)

![dangerouslyReplaceNodeWithMarkup](https://cloud.githubusercontent.com/assets/1594619/9572688/743a0be2-4fd2-11e5-89cd-ceba6490c202.png)

Regards,
Nripendra

**Comment by spicyj** [comment]
Try setting global.document and global.window from jsdom before requiring React. This report is similar:

http://stackoverflow.com/questions/26867535/calling-setstate-in-jsdom-based-tests-causing-cannot-render-markup-in-a-worker

**Comment by nripendra** [comment]
@spicyj 

I changed my beforeEach to require React after declaring document and window objects in global scope as follows:
```js
beforeEach(function() {
  global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
  global.window = global.document.defaultView;
  global.Element = global.window.Element;
  global.navigator = {
    userAgent: 'node.js'
  };

  React = require('react/addons');
  ReactTestUtils = React.addons.TestUtils;
});
```
Now it started giving another error:
**Error: Invariant Violation: createNodesFromMarkup dummy not initialized**

![untitled](https://cloud.githubusercontent.com/assets/1594619/9630338/5e71018a-5199-11e5-8b35-3f3dc864570c.png)

Any idea what's going on?

**Comment by nripendra** [comment]
Ok, finally figured out the problem. The issue was with jasmine interleaving multiple tests at once (not sure how it does it). Moving all the test cases into one suit fixed the issue. Have documented more here [http://blogs.nnn.ninja.np/fb-messenger/2015/09/07/Learning-js-technologies-part9/](http://blogs.nnn.ninja.np/fb-messenger/2015/09/07/Learning-js-technologies-part9/) if someone facing similar issue, wants a solution.
