### ISSUE TITLE
Make test utils aware of subtrees rendered in containers (renderSubtreeIntoContainer)?

### ISSUE THREAD

**Issue by cesarandreu** [facebook/react#4741]
Using react v0.14.0-beta3 and react-overlay's Modal (which uses Portal). Portal is using `renderSubtreeIntoContainer`. It appears that test utils are not aware of subtrees rendered in containers, so when you search for children they don't get crawled.

This means that in order to test my components I have to first get `instance.refs.modal`, instead of being able to use TestUtils directly.

I looked up related discussions and wasn't able to find anything on this. Are there plans to make test utils aware of this feature? It'd be a nice convenience.

**Comment by spicyj** [comment]
I'll leave this open until we figure out our longer-term plan for test utils, but we're unlikely to get to this.

**Comment by gaearon** [comment]
I think this is probably solved with portals now.
