### ISSUE TITLE
Target value sometimes undefined

### ISSUE THREAD

**Issue by mnlfischer** [facebook/react#4745]
I loop my product list with map() and create a react component for each item.
```javascript
      var ProductListItem = React.createClass({
        handleEvent: function(e) {
          console.log(e.target.value);
        },
        render: function() {
          return (
            <tr>
              <th>{this.props.id}</th>
              <th>{this.props.name}</th>
              <th>{this.props.quantity}</th>
              <th>
                <button type="button" className="btn btn-default btn-sm" value={this.props.id} onClick={this.handleEvent}>
                  <span className="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </th>
            </tr>
          );
        }
      });
```
When I click on the button sometimes the e.target.value is defined and sometimes undefined. Its totally random. After clicking on the button 50 times, the value sets magically undefined.

**Comment by spicyj** [comment]
Can you post a small reproducible example in react.jsbin.com or jsfiddle? I can't help you unless you give more information.

**Comment by mnlfischer** [comment]
https://jsbin.com/zekixo/

**Comment by jimfb** [comment]
Bug occurs when the click target is the glyph instead of the button.  Original  browser mouse event has target correctly set, synthetic event does not.  Reproducible in both 0.13 and 0.14.

**Comment by spicyj** [comment]
It looks like a bug that this is undefined, but after we fix it it'll be the span element which probably isn't what you want. You want `e.currentTarget.value` to get the button, which already works correctly.

**Comment by spicyj** [comment]
Wait, what? `e.target` is correctly the button or the span in my testing. If you want the button, you do definitely want `e.currentTarget.value`.

**Comment by horaciogithub** [comment]
Oh my God, I love you sophiebits, I have been fighting against this issue for weeks and did not find any solution, thanks a lot!! :)

**Comment by srinivas-goli** [comment]
@sophiebits  Thansk a lot!! it's working ..

**Comment by gejimayu** [comment]
@sophiebits saves my life, thanks

**Comment by konstantinkrumin** [comment]
> It looks like a bug that this is undefined, but after we fix it it'll be the span element which probably isn't what you want. You want `e.currentTarget.value` to get the button, which already works correctly.

Ohh thank you so much, @sophiebits ! I was quite confused when my console was randomly giving 'undefined' when buttons clicked

**Comment by Aqsa48** [comment]
> Wait, what? `e.target` is correctly the button or the span in my testing. If you want the button, you do definitely want `e.currentTarget.value`.

Thankyou it also worked for me with same peolem

**Comment by judygitsthejobdone** [comment]
> It looks like a bug that this is undefined, but after we fix it it'll be the span element which probably isn't what you want. You want `e.currentTarget.value` to get the button, which already works correctly.

Thank you so much @sophiebits ! I was pulling my hair out for the last week on this and using `e.currentTarget.value` solved it!
