### ISSUE TITLE
`jsx` fails silently for non-existent src/dest

### ISSUE THREAD

**Issue by jamesob** [facebook/react#4748]
```
root@32610c5dcfac:/srv/auto_pipeline_app# jsx --version
0.13.3

root@32610c5dcfac:/srv/auto_pipeline_app# ls foo bar
ls: cannot access foo: No such file or directory
ls: cannot access bar: No such file or directory
root@32610c5dcfac:/srv/auto_pipeline_app# jsx -x jsx foo bar
root@32610c5dcfac:/srv/auto_pipeline_app# echo $?
0
```

This is really confusing when trying to debug why static assets aren't being built.

**Comment by zpao** [comment]
Sorry for the trouble. This was an unfortunate problem but we're in the process of deprecating `react-tools` so won't be fixing anything more. I suggest switching to another tool (our preferred one is babel).

**Comment by jamesob** [comment]
Cool, thanks for the heads-up.
