### ISSUE TITLE
Context changing on parent doesn't update child

### ISSUE THREAD

**Issue by andreweichacker** [facebook/react#4749]
If you have a component that sets context and a child gets passed in through props that supports that context, it will not render when the context updates - only a render from the component that passes in the child will call render and update the child.

Example:
http://jsbin.com/ficoyutusa/1/edit?js,output

Another example:
This one works (Parent has its own context): http://jsbin.com/cinebaripu/1/edit?html,js,console,output
This one does not (Parent removes its context): http://jsbin.com/niyetupida/1/edit?html,js,console,output

**Comment by spicyj** [comment]
This is known. More or less a dupe of #2517.
