### ISSUE TITLE
Allow disabling the omitted close tags

### ISSUE THREAD

**Issue by jankeromnes** [facebook/react#4756]
Similar to #4138.

For a few elements like `<img>` and `<input>` (also called [void elements](http://www.w3.org/TR/html-markup/syntax.html#void-element)), React [omits the close tags](https://github.com/facebook/react/blob/2d63dfd73c5258e683d394d9ea0b922be21c65d8/src/renderers/dom/shared/ReactDOMComponent.js#L403-L423).

In XHTML, this produces invalid markup, which can throw or even break the whole page. To prevent this, it would be nice to disable the omission of close tags, e.g. with an option like `omitCloseTags:false` or `generateXHTML:true`.

**Comment by syranide** [comment]
https://github.com/facebook/react/pull/2842, it's in 0.14.

**Comment by jankeromnes** [comment]
Good news, thanks @syranide! Closing this.
