### ISSUE TITLE
Does instance stay instantiated after componentWillUnmount?

### ISSUE THREAD

**Issue by trusktr** [facebook/react#4770]
Or does that destroy the instance?

**Comment by spicyj** [comment]
Can you give more information about what you mean?

**Comment by trusktr** [comment]
@spicyj You know the instance of a component (i.e. the things you can get by using `this.refs`)? Do those get destroyed after their componentWillUnmount methods are called? Or do they stay alive to be re-used?

**Comment by spicyj** [comment]
What do you mean by "destroyed"? All JavaScript objects are garbage collected when there are no more references.

**Comment by trusktr** [comment]
Of course. I assume React lets go of the reference after calling it's componentWillUnmount. I jsut wanted to plan a way to keep some of my own objects alive across instantiations of news react components. I guess I'll make external singletons.

**Comment by spicyj** [comment]
Yes, React never reuses an instance after it's been unmounted.
