### ISSUE TITLE
Iterable numbers breaks React

### ISSUE THREAD

**Issue by zloirock** [facebook/react#4776]
Issue with the reproducible example [here](https://github.com/zloirock/core-js/issues/104).

Full `core-js` build contains non-standard `Number` iterator. Theoretical, it can be added to ES in the future, it can be added (or already added) to another libraries. `React` should take into account possibility iterable numbers.

**Comment by benmosher** [comment]
IME, having just bumped up against this today, the presence of the Number iterator results in a significant slowdown in render time, but ultimately renders exactly what I'd expect.

I suspect there is some [dead code](https://en.wikipedia.org/wiki/Dead_code) that is fully iterating/collecting the iterator, _then_ detecting that the value is a `Number` and properly rendering it.

Assuming that's what's happening, should be simple enough to re-order the execution.

**Comment by sebmarkbage** [comment]
Well, the good news is that if this is already on enough pages, then introducing iterable numbers may not be web compatible anyway.

I think that this is only in DEV only code. Unfortunately a lot of pages incorrectly uses the DEV build of React.

**Comment by spicyj** [comment]
"good news"
