### ISSUE TITLE
onClick only fires when element is a button on android

### ISSUE THREAD

**Issue by ScratchJeff** [facebook/react#4783]
I hope i'm not wasting folks time but we've encountered a situation that our web app does not work on android 5.0 chrome etc, unless the onClick is attached to a button element. li, div etc do not fire the onClick, however using react tappable inside the element with the same event handler does.

**Comment by spicyj** [comment]
This is probably fixed on master. If you can still repro this on 0.14.0-beta3, let me know and I'll reopen.

**Comment by invisiblemachine** [comment]
thank you!
