### ISSUE TITLE
Suggestion: Increase performance by providing an initial virtual-dom similar to linux init ram image

### ISSUE THREAD

**Issue by sjoerd222888** [facebook/react#4790]
I have a suggestion where I am not really sure whether this functionality already exists but I think it does not yet. Also I am not really sure whether the proposed mechanism would indeed improve the performance of react.

According to my understanding the virtual-dom is created by reactjs on application load. If applications are large the virtual dom creating can consume some time. If the virtual dom could be provided by the server already similar to init ram images used in linux the init performance could possibly be increased. In some cases the init dom 'image' (probably provided as json) would be static but there might be cases where this does not work. There would be plenty of options of how to prepare this on server side.

But if indeed the transmission of a virtual dom image would be slower than creating it from scratch on client side it does not make sense. In case it depends on network speed it could also be an option that the client starts to build the dom and abandons the virtual dom creation process when the image is received from the server. In the other case the request would be canceled.

I hope this makes sense. I am not a user of react but in a conference discussion with developers that use react the idea was accepted that is why I now propose it here.

**Comment by jimfb** [comment]
You may be imagining that the virtual dom is a large data structure that gets materialized on the client.  That updates result in a second virtual tree being created, and the two are diffed as a second step.  I know this was my initial interpretation upon reading the documentation.  And while that's conceptually true, it's not actually how the internals work.  There isn't really a virtual dom image (certainly not a serializable one anyway) that could be provided by the server, at least not with our current implementation.

However, there is some good news, if you have the ability to run code on the server.  React supports rendering markup on the server, and then React will mount into that markup (reusing the markup created on the server).  This means that the initial http payload sent to the client will contain fully rendered html (which is also great for SEO, and makes the page look/feel super fast), and React will jump into action on the client as soon as all the dependent javascript has been loaded.  For more information, I would recommend googling [react isomorphic](https://www.google.com/search?q=react+isomorphic&oq=react+isomorphic&aqs=chrome..69i57j69i60l5.3487j0j7&sourceid=chrome&es_sm=91&ie=UTF-8).

As a side note: While it's a bit different from what you're describing, a related discussion topic is [inline elements](https://github.com/facebook/react/issues/3285), which is on our short-term roadmap and one of the things we're looking to better support in the future.
