### ISSUE TITLE
Refactor away opaque "Uncaught TypeError: type.toUpperCase is not a function" messages when JSX is misused

### ISSUE THREAD

**Issue by JonathanHayward** [facebook/react#4791]
It appears (I haven't mapped everything out) that if a developer bungles JSX syntax by using JSX sigils where the JSX compiler doesn't expect JSX sigils, the error message is likely to be an unhelpful and opaque "Uncaught TypeError: type.toUpperCase is not a function".

In http://stackoverflow.com/questions/31598471/react-error-uncaught-typeerror-type-touppercase-is-not-a-function-on-a-hello , the developer had written:

    var element = React.createElement({HelloWorld});

In my own post at http://stackoverflow.com/questions/32385417/english-translation-from-reactjs-react-with-addons-js9729-uncaught-typeerror/32401805#32401805 , the culprit was:

    var pragmatometer = React.createElement(<Pragmatometer />, null);

In both cases, the user had given JSX-like syntax in a context where it was not expected.

Could there be a more useful and descriptive error message, preferably with a probable line number, if the JSX compiler encounters JSX syntax add-ons where they are not expected?

**Comment by spicyj** [comment]
The warning and error is already clearer in master.

**Comment by JonathanHayward** [comment]
How can I download, build, or acquire an updated react-with-addons.js with the clearer warning and error? I download a fresh https://fb.me/react-with-addons-0.13.3.js and am getting the toUpperCase warning without indicating a line number in my code.

**Comment by spicyj** [comment]
It'll be in 0.14, hopefully out soon.
