### ISSUE TITLE
Use TypeScript 1.6 in our TS tests

### ISSUE THREAD

**Issue by zpao** [facebook/react#4795]
We should get past 1.4 anyway and we can use JSX in the tests itself so that'll simplify them a little bit.

**Comment by nhunzaker** [comment]
@gaearon Do you know the history here? React uses Flow now, is this still a valid issue?

**Comment by gaearon** [comment]
This is about TypeScript dependency that's used for `ReactTypeScriptClass-test.ts` I think.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/6804
