### ISSUE TITLE
when react will flush the batch work?

### ISSUE THREAD

**Issue by ckrad** [facebook/react#4800]
i read the source code. but not very understand. when react will  flush the batch work.

**Comment by syranide** [comment]
React batches everything automatically during React events and life-cycle methods, the batched operations are applied as soon as execution returns to the "top-level where batching started", it's not deferred in any way.

**Comment by ckrad** [comment]
@syranide i use jquery to remove a node. then setState to rerender the component. but the node will not be rendered again. why?

**Comment by syranide** [comment]
@ckrad That's not allowed, don't touch nodes rendered by React other than possibly adding children to empty nodes (to effectively stop using React from that point down).

**Comment by ckrad** [comment]
@syranide is the virtual dom always in momey and only record the node with reactId?
