### ISSUE TITLE
How to handle empty model

### ISSUE THREAD

**Issue by mookraiser** [facebook/react#4808]
if my JSX do something like **state.currentUser.name** whereas the user is not already loaded with Ajax. I get an **Uncaught TypeError: Cannot read property 'name' of undefined**

How to handle this properly. Is there any good practices ?

It would be horrible to trash the JSX with tons of checking like this:
**{state.currentUser!=null?state.currentUser.name:''}**

**Comment by syranide** [comment]
We would prefer if issues were related to development related issues only.
Please put your general questions on StackOverflow or https://discuss.reactjs.org/

**Comment by spicyj** [comment]
(discuss.reactjs.org is not appropriate for code-level debugging questions.)
