### ISSUE TITLE
what is the best practice to debug a project based on React?

### ISSUE THREAD

**Issue by astwyg** [facebook/react#4809]
hi, everyone:
  we are planing to rebuild our project using React, we tried to use `reactify` to translate jsx, gulp to pack up js files, but there are 2 problems:
  1. using watchify in gulp, when we change our code, it will take about 15 seconds to repack, feeling terrible.
  2. we need to using breakpoints in js file, we used `vinyl-source-stream` in gulp file , and Chrome is able to split the packed js file to raw files(in developer tools->sources tab), but, in some case, there are something wrong with raw files, breakpoints will not work, more seriously, the error info(in developer tools->console tab) is obvious marked at wrong line.

we also tried `webpack` with`webpack-dev-server`, but we cannot find a proper config.

so, please share any idea about debug a project based on React.

thanks a lot!

**Comment by rpominov** [comment]
You can start from looking at these boilerplates https://github.com/enaqx/awesome-react#boilerplates

**Comment by rpominov** [comment]
Also http://stackoverflow.com/questions/tagged/reactjs is more appropriate place for such questions.
