### ISSUE TITLE
dynamically require a bundle

### ISSUE THREAD

**Issue by guanyuxin** [facebook/react#4810]
now react bundle all code into a single js file which can be used in a view,
but for apps with multiple views, using a single combined file for all, or multiple static build file for each, tend to be low efficient.
hope there will be a way to build multiple bundle(or something like .so) with being able to dynamically require each other when running, while they are build with there own code.

**Comment by edvinerikson** [comment]
If you use webpack, you can benefit from their [code splitting](http://webpack.github.io/docs/code-splitting.html) functionality.

**Comment by linclark** [comment]
You can configure both Browserify and Webpack to exclude external libraries from your bundle. I document both here: http://lin-clark.com/blog/2015/09/08/exclude-react-angular-from-webpack-browserify-bundles/

**Comment by spicyj** [comment]
Both of these suggestions are good. This isn't a React-specific issue so I'm closing this bug.
