### ISSUE TITLE
Chrome and FF performs code for old IE

### ISSUE THREAD

**Issue by Degee** [facebook/react#4812]
Hi,
customer has reported some bugs with react and we found problem but we dont know why it happened. Must say, these bugs was appear only on some pc. We had to go into customers office and try it on their machines. On ours machines all work fine.

Following code in react.js 
       
          isInputEventSupported = isEventSupported('input') && (
                      (!('documentMode' in document) || document.documentMode > 9)
          );

set isInputEventSupported variable to FALSE in Chrome and Firefox.

We had to fix it temporarily here

                if (isInputEventSupported || 1)
                    getTargetIDFunc = getTargetIDForInputEvent;
                } else {
                    getTargetIDFunc = getTargetIDForInputEventIE;
                    handleEventFunc = handleEventsForInputEventIE;
                }

then all work allright.

But we really dont know why in newest Chrome (v. 45.0.2454.85) is performed code for old IE.

 Can be something wrong with the condition above depending on new Chrome/FF?

**Comment by spicyj** [comment]
We haven't had any other reports of this. This works correctly in my copy of Chrome 45 as far as I know. Perhaps you can debug and see what part of that condition is returning true and how that differs from your own machines.

**Comment by syranide** [comment]
I would assume this is the result of a shim/polyfill.
