### ISSUE TITLE
about Parent vs. Owner Context in 0.14

### ISSUE THREAD

**Issue by yiminghe** [facebook/react#4819]
Sorry to bring this up again, but 0.14 will cause a lot of changes through out our codebase.

I notice context has switched to parent-based context in 0.14 beta, but a lot of libraries(especially react-router) depends on context, in a lot of our components we usually render children into body instead of inside current component, such as:

https://jsfiddle.net/yiminghe/zrj6fqjj/2/

And in 0.14 beta we will not get context, so router breaks, I wonder is there a syntax to get inherited context and render element with it, for example

```js
React.render(el,container,{
context: this.inheritedContext
})
```

or maybe I should file issue directly to react-router?

**Comment by rpominov** [comment]
Interesting question. I also wonder how to use new context with "portals" (when we return `null` from `render()`, and do manual `React.render` in `componentDidMount`).

+1

**Comment by spicyj** [comment]
```
ReactDOM.unstable_renderSubtreeIntoContainer(this, el, container);
```

should work.

**Comment by rpominov** [comment]
Is there some documentation on it?

**Comment by spicyj** [comment]
Not yet. Context as a whole is still undocumented and will remain so until it's stable enough for us to support it.

**Comment by rpominov** [comment]
An issue/PR where it was discussed also would do :)

**Comment by rpominov** [comment]
At least the basics how it works. It makes `this` "parent" of `el` in virtual tree?

**Comment by spicyj** [comment]
Right now it passes context, that's all. Unclear if it'll be expanded to include anything else in the future.
