### ISSUE TITLE
ReactDOM.render in 'react-dom' 0.14.0-beta3 throws an invariant error when using refs

### ISSUE THREAD

**Issue by brainkim** [facebook/react#4822]
The error:
```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```
Minimal example repository using webpack: https://github.com/brainkim/reactdomerror
Steps to reproduce:
```
git clone https://github.com/brainkim/reactdomerror
npm install
make build
```
spin up a http server and point to index.html
This error is mitigated by using the deprecated `React.render` method instead.

**Comment by spicyj** [comment]
Try using the same version of react and react-dom. When you do `npm ls` you should only see one react (i.e., not any underneath react-dom).

**Comment by brainkim** [comment]
Makes sense, kinda. Thanks!

**Comment by spicyj** [comment]
(From the beta blog post: "For now, please use the same version of react and react-dom in your apps to avoid versioning problems – but we plan to remove this requirement later.")

**Comment by brainkim** [comment]
:+1: Just me being dumb with npm install --save

**Comment by brainkim** [comment]
For posterity and so I can delete the example repository, the problem was that I was downloading React from npm at  "0.14.0-beta1", and ReactDOM at "0.14.0-beta3" in my `package.json`. Aligning the beta versions makes everything groovy.

**Comment by coodoo** [comment]
Just hit this with `0.14.0-rc1`, checked there's no dupe react loaded, ended up removing `node_modules` and reinstall everything did the trick, hfh!

**Comment by shaikhussian** [comment]
@coodoo i am getting Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element. in my package react and react-dom are of same version 0.14.0-rc1.

**Comment by spicyj** [comment]
@shaikhussian That is a completely unrelated error. It means that you're passing a container that isn't a DOM node – likely undefined (if the element you're looking for doesn't exist on the page).
