### ISSUE TITLE
It seems something wrong when using !important in inline style

### ISSUE THREAD

**Issue by luokuning** [facebook/react#4830]
Here is my code:
```
style={{ borderColor : titleLimit ? 'red !important' : '#ccc' }}
```
When ```titleLimit==true```, ```border-color``` is still be ```#ccc```, but when I removed ```!important``` and code just like that:
```
style={{ borderColor : titleLimit ? 'red' : '#ccc' }}
```
Then everything goes well. Did I miss something?

**Comment by spicyj** [comment]
Dupe of #1881.
