### ISSUE TITLE
Warning: React component classes must extend React.Component. - 0.14 rc1

### ISSUE THREAD

**Issue by chandu0101** [facebook/react#4836]
http://stackoverflow.com/questions/32509891/warning-react-component-classes-must-extend-react-component-0-14-rc1

**Comment by fta2012** [comment]
+1 Getting this with RC1

**Comment by tonyhb** [comment]
Getting this with RC1 too, and also getting invalid proptypes for children:

```
static propTypes = {
  children: React.PropTypes.node.isRequired
}
```

When passing down JSX nodes we get this error:

`Warning: Failed propType: Invalid prop ​`children`​ supplied to ​`Card`​, expected a ReactNode. Check the render method of ​`ContainerStatus`​.`

Might this be because of the same checking?

**Comment by zpao** [comment]
@tonyhb no that would be unrelated. Can you file a new issue with code to reproduce.

**Comment by tonyhb** [comment]
Will do.

**Comment by luisrudge** [comment]
I'm having this problem using this lib (https://github.com/davidguttman/react-pivot/blob/master/index.jsx) as well. any thoughts?

**Comment by luisrudge** [comment]
ops, just found the culprit: https://github.com/davidguttman/react-pivot/blob/master/load.js

**Comment by luisrudge** [comment]
@spicyj thoughts on this one?

**Comment by spicyj** [comment]
@luisrudge Guessing react-pivot has its own copy of React. Try rm -rf `node_modules/react-pivot/node_modules/react/`.

**Comment by luisrudge** [comment]
I'm using npm3, so it's all flattened

**Comment by luisrudge** [comment]
![image](https://cloud.githubusercontent.com/assets/941075/9802137/7808b8f8-57ee-11e5-8566-cdfd71ccbcf6.png)

**Comment by chandu0101** [comment]
more context : https://github.com/scala-js/scala-js/issues/1900

**Comment by spicyj** [comment]
Need to investigate how IE9 and IE10 behaves with these static properties. For anyone in this thread who's not using scala-js (which I assume is most of you), please file separate issues with repro steps.
