### ISSUE TITLE
Question about forEachAccumulated docs

### ISSUE THREAD

**Issue by igncp** [facebook/react#4837]
Hi,

I was checking the file of the definition of [forEachAccumulated](https://github.com/facebook/react/blob/04e5ee70cc99797a048aeca151b0af595ea48af6/src/shared/utils/forEachAccumulated.js#L21-L27) and I saw that the documentation entry is vague about the case that `arr` is `0`, or `""`, in which it doesn't call `cb`.

As this function is used basically with events (or queues), probably this is not an expected value, but maybe it would be nice to comment that the function expects objects, and not `items`. What do you think? Would you leave it as it is, change the docs or ensure that the item is an object at the `else if`?

Cheers

**Comment by spicyj** [comment]
These are internal functions and we don't support using them except as they exist in our codebase. It would probably make sense to check for `!= null` instead.
