### ISSUE TITLE
The repo wiki is full of spam

### ISSUE THREAD

**Issue by licyeus** [facebook/react#4838]
[The repo wiki](https://github.com/facebook/react/wiki) is full of pages created in the last hour with spammy titles like "Service Ariston Cempaka Putih 0818.0627.2790". Also, the top Google result for "sites using react" is a missing wiki page (https://github.com/facebook/react/wiki/Sites-Using-React) that Github is asking me to fill out.

I'm guessing wiki permissions were incorrectly opened up to the public?

**Comment by zpao** [comment]
Thanks for the heads up, I'll clean it up. Luckily it's git :)

We actually have the wiki set to public intentionally so that we can have people add their own sites without us having to handle it.

**Comment by zpao** [comment]
Fixed and reported the email address responsible.

**Comment by jimbolla** [comment]
Not sure if it's possible considering the markdown nature of that page, but is there any way to add `rel="nofollow"` to all the generated `<a>` tags? This would at least make it [less desirable as a spam target](https://support.google.com/webmasters/answer/96569?hl=en).

**Comment by zpao** [comment]
Not possible from our end.
