### ISSUE TITLE
more info on error message "React component classes must extend React.Component"

### ISSUE THREAD

**Issue by luisrudge** [facebook/react#4843]
It's very hard to find which component is throwing this error. can we improve the message somehow?

![2015-09-10 18_50_32-photos](https://cloud.githubusercontent.com/assets/941075/9801976/166162e0-57ed-11e5-944e-8924dff87b5f.png)

**Comment by spicyj** [comment]
It includes the display name, which in your case looks to be "index". I don't know of anything we can do better.

**Comment by luisrudge** [comment]
oh, ok. so the problem only happens when using react.createClass without display name. thanks for the info

**Comment by spicyj** [comment]
The Babel `react.displayName` transformer (enabled by default) should add displayName automatically to your components too.

**Comment by iamdustan** [comment]
I suspect if you click the arrow next to the message you will get a stack trace and see the component causing the issue somewhere in there.

**Comment by luisrudge** [comment]
@iamdustan nope. It's just a bunch of internal react methods

**Comment by luisrudge** [comment]
but I added a PR to add the displayName to that specific lib
