### ISSUE TITLE
Input value from state but still update onChange

### ISSUE THREAD

**Issue by fullvlad** [facebook/react#4848]
I came across this intriguing problem when trying to set value for an input from state.
I want to have an input get its value from state (that is connected to a store), and also I want to update _onChange_ the value in the store through an action.
```
_updateInputField(type, e) {
    ActionToStore(type, e.target.value) // Store will 'trigger' modification for type variable in state
}

[...]

<input
       onChange={this._updateInputField.bind(null, 'name')}
       value={this.state.name} />
```
A huge problem this approach presents is that the input will get _very_ _slow_ when typing new characters due to the fact that this requires a new render of the component.

So, I started implementing _onBlur_ method and drop _onChange_, but I got a warning saying that the component will only be _read_ _only_ because it doesn't have an _onChange_ method.

I also looked into _Two Way Binding_ that handles setting the state and updating the value of a component but got the same laggish result.

Also, another big problem with this is whenever I set state with a new value, i.e. when I type new characters, the typing cursor is reset to the end of the text in the input, so if I try to edit inside the current text I only get to enter one character before the cursor moves to the end.

Is there a better official approach for these problems and if not is this a known problem and set to be solved in React's next versions?

**Comment by benglass** [comment]
@fullvlad Can you post a jsbin code example?

You might be doing too much in your render method if its getting laggy due to being called as a result of onChange.

I have run into the problem of cursor reset and it was caused by the flux library I was using not executing an action syncronously. It was waiting until nextTick which is problematic for actions that connect stores to controlled inputs via onChange handlers.

**Comment by syranide** [comment]
> So, I started implementing onBlur method and drop onChange, but I got a warning saying that the component will only be read only because it doesn't have an onChange method.

For that to work you need to use `defaultValue` instead of `value` and then it will work correctly. But also note the current value of the input will no longer respond to external updates (without manually accessing the node and setting it).

**Comment by fullvlad** [comment]
@benglass Indeed I was rendering many components on each update, so that's why it was laggy.

@syranide the `defaultValue` wasn't an option for me then because that value wasn't available at first render so it wouldn't display anything.

I did a workaround for this problem by adding just `onBlur`, so no `value` or `onChange`, and updating the its value on `componentWillUpdate` through `refs`.

Thanks for the answers, though :smile:
