### ISSUE TITLE
No longer possible to "blank" a <select> using selectedIndex

### ISSUE THREAD

**Issue by jbrantly** [facebook/react#4852]
This was a change from v0.12 -> v0.13 but I only just now noticed it. Essentially I had a component that did something like this:

```
componentDidMount() {
  if (this.props.value == '') {
    this.refs['select'].getDOMNode().selectedIndex = -1;
  }
}

render() {
  return <select ref="select" value={this.props.value}>
    <option value="Yes">Yes</option>
    <option value="No">No</option>
  </select>
}
```

This meant that if a blank value was provided, the select would display nothing by setting `selectedIndex`. However, in v0.13 [this was added](https://github.com/facebook/react/blob/0.13-stable/src/browser/ui/dom/components/ReactDOMSelect.js#L92) which effectively kills this behavior. I think I understand why it was changed since it better matches what the browser shows by default, but I'm trying to figure out a way to still be able to blank a select element without adding an extra blank option element.

**Comment by jbrantly** [comment]
After thinking on it a bit more I realized it's more correct to also use `componentDidUpdate`. Implementing that to also set selectedIndex if necessary seems to get the behavior I'm looking for. Sorry for the noise.

**Comment by spicyj** [comment]
I would just add an empty option with `value=''` then everything will work without any extra work.
