### ISSUE TITLE
Pressing spacebar on a checked radio button only fires click in some browsers

### ISSUE THREAD

**Issue by matchu** [facebook/react#4854]
http://jsbin.com/yiyusuwuco/1/edit?js,console,output
1. Focus the textbox.
2. Press shift-tab to move focus into the radio button group.
3. Press spacebar to check the radio button.
   - Observe a click event in the console.
4. Press spacebar to redundantly check the radio button.
   - In Chrome 45.0.2454.85 (64-bit, OSX), observe no additional click event in the console.
   - In Firefox 40.0.3 (OSX), observe an additional click event in the console.

This is entirely the browsers' fault, but, since React's Synthetic Event system is trying to fully normalize inconsistencies like this, here's an obscure one for the list :/

I, at least, prefer Firefox's behavior: I expect real clicks and synthetic (keyboard-originated) clicks to have the same conditions for firing.

(Incidentally, this feels to me like it might've been an accident in Chrome rather than an explicit decision. Is there some place to file this bug with them? I feel like that's pretty pie-in-the-sky, though ;P)

**Comment by aweary** [comment]
I've verified that this is still an issue with the latest React 16 RC: https://jsfiddle.net/snshd0av/

**Comment by gnapse** [comment]
I was able to reproduce this too [here](https://codesandbox.io/s/wnnl8p8k9l) in vanilla javascript, and was able to throw in a quick fix in there too.

I wonder if a similar fix can be transferred to React's codebase. I'd be thrilled to attempt to do so with some guidance if possible (hoping the "mentorship" tag has to do with that 🙏).

**Comment by jasonwilliams** [comment]
Using this test case https://jsfiddle.net/snshd0av/2/ (same as @aweary's) but updated to 16.4.1
I have consistent experience with:
* Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Firefox Developer Edition 62.0b6 (64-bit)
Only 1 event comes through

However, Microsoft Edge 42.17134.1.0 does repeat events for each spacebar press

**Comment by nhunzaker** [comment]
> Rather than introducing a patch it might be worth us closing this ticket and letting the WHATWG decide what the right approach to take is, it may be inconsistent between vendor's but issue is not affecting React users dis-proportionally here

I agree. I say we wait to see what WHATWG decides. It also avoids possible regressions with the change event plugin, which have been historically difficult to regression test.

**Comment by nhunzaker** [comment]
Closing this out, but happy to pick up the discussion once WHATWG makes a decision.

**Comment by Legend669** [comment]
Fuck u Cuzz!
