### ISSUE TITLE
Warning: <Unknown Component /> is being rendered by both [Unknown] and [Unknown] using the same key (0)

### ISSUE THREAD

**Issue by trusktr** [facebook/react#4860]
What does the following message mean exactly?

> Warning: `<Unknown Component />` is being rendered by both [Unknown] and [Unknown] using the same key (0) in the same place. Currently, this means that they don't preserve state. This behavior should be very rare so we're considering deprecating it. Please contact the React team and explain your use case so that we can take that into consideration.

**Comment by trusktr** [comment]
I'm getting this with a component called Swapper that I'm rendering like this:

```jsx
export default
class Login extends Node {
    render() {
        let currentScreen = this.data.currentScreen
        return (
            <Node _famousParent  = {this}
                id               = "layoutNode"
                sizeMode         = {['relative', 'relative']}
                proportionalSize = {[1.0, 1.0]}
                >

                {/*React.createElement(this.data.loginLayout)*/}

                {/*For now, we instantiate all of them until Famous bugs are
                    effing fixed, and reveal them using position.*/}
                <Swapper>
                    <SplashScreen       show={SplashScreen === currentScreen} />
                    <SignUpScreen       show={SignUpScreen === currentScreen} />
                    <LoginScreen        show={LoginScreen === currentScreen} />
                    <PaymentScreen      show={PaymentScreen === currentScreen} />
                    <PersonalInfoScreen show={PersonalInfoScreen === currentScreen} />
                </Swapper>

            </Node>
        )
    }
}
```

and Swapper renders this:

```jsx
class Swapper extends Node {
    render() {
        let children = this.props.children instanceof Array ? this.props.children : [this.props.children]
        let offscreenY = this.isFirstRender ? -offscreenDistance : 0
        this.renderedChildren = _.map(children, (child, index) => {

            let childProps = Object.assign({key: index, index: index},
                this.isFirstRender ? {position: [0,-offscreenDistance]} : {},
                child.props.show ? {ref: "shown"} : {}
            )

            return React.cloneElement(child, childProps)
        })

        this.isFirstRender = false

        return (
            <Node _famousParent={this}>
                {this.renderedChildren}
            </Node>
        )
    }
}
```

**Comment by trusktr** [comment]
The reason I'm wondering is because React is creating new instances of the children that have been passed to Swapper instead of re-using them, which isn't what I desire. The instances house [Famous Engine](http://famous.org/) Nodes which I'd like to keep alive. How might we be able to do this?

**Comment by trusktr** [comment]
If I move the logic from the Swapper out, and into the component that is current rendering the Swapper, then I can do what I want no problem, and keep the instances alive, only re-rendering them and having their `component*Update` methods called instead of moun/unmount.

**Comment by towry** [comment]
Here is an example that will trigger this warning: https://jsfiddle.net/reactjs/69z2wepo/ (click the button to trigger the warning).

**Comment by zpao** [comment]
@towry I can't repro this with your example in 0.14.

@trusktr re `_.map`, use `React.Children.map` instead, it'll handle the abstractions for Arrays and what not for you.

And try dropping the `key` inside the map - that could be screwing things up and I don't think you need it.

**Comment by towry** [comment]
@zpao So it only exists in react version below 0.14, that's ok.

**Comment by trusktr** [comment]
@towry @zpao I tried removing the `key` property, but the same thing happens, except instead of saying

> <Unknown Component /> is being rendered by both [Unknown] and [Unknown] using the same key (0)

it says

> <Unknown Component /> is being rendered by both [Unknown] and [Unknown] using the same key (null)

I don't understand what this actually means (without reading all the React source).

**Comment by spicyj** [comment]
In 0.14 these will preserve state, as the warning message sort-of implies.

**Comment by trusktr** [comment]
This isn't so much a problem, except that Famous has a bug that is triggered with Famous Nodes are detroyed and recreated. Using some other library (f.e. Three.js or the new one we're making at http://infamous.io) should work just fine, with objects being destroyed and recreated just fine.
