### ISSUE TITLE
0.14.0 npm update breaks

### ISSUE THREAD

**Issue by danehansen** [facebook/react#4862]
I'm working on a project utilizing react, react-dom, react-addons-css-transition-group and react-addons-transition-group. My project works fine if I install these packages from the command line like so:

`npm install --save react@0.14.0-rc1`
`npm install --save react-addons-css-transition-group@0.14.0-rc1`
`npm install --save react-addons-transition-group@0.14.0-rc1`
`npm install --save react-dom@0.14.0-rc1`

But if they are installed by listing them in the package.json and entering `npm update` I am given the following error: https://gist.github.com/jimfb/4faa6cbfb1ef476bd105

Even if I first install the packages separately through the terminal and then run `npm update` the project breaks.

**Comment by gaearon** [comment]
https://docs.npmjs.com/cli/update

>This command will update all the packages listed to the latest version (specified by the tag config), respecting semver.

```
npm dist-tag ls react

0.10.0-rc1: 0.10.0-rc1
0.11.0-rc1: 0.11.0-rc1
latest: 0.13.3 # <------------- latest stable version
next: 0.14.0-rc1
```

`npm update` doesn't install prerelease versions so you effectively rolled back to 0.13.
Then you got duplicate React problem.

**Comment by danehansen** [comment]
Ah gotcha. Thanks @gaearon

**Comment by gaearon** [comment]
No problem. Fingers crossed for a 0.14 release soon :wink:
