### ISSUE TITLE
RC1: Unexpected detached subtree found (possible regression?)

### ISSUE THREAD

**Issue by syranide** [facebook/react#4865]
Since upgrading from beta3 to rc1 I've seen this error a few times in production. Haven't been able to trace the source yet though.

cc @spicyj

**Comment by syranide** [comment]
I was unmounting a root during a keyboard event which caused this to happen. I think this has always been a problem? Perhaps we've only been lucky... leaving open just to be sure.

**Comment by spicyj** [comment]
This invariant was new in this release. We also hit one case at FB that I haven't yet investigated. Probably need to change something for the final release.

**Comment by philholden** [comment]
I have seen this on RC1 can find a sequence of actions to repeat it.

**Comment by iammerrick** [comment]
I'm running into this issue as well when conditionally rendering based on state. Not sure how to boil it down to a simple reproducible bug report yet.

**Comment by iammerrick** [comment]
My issue only happens when I am leveraging FastClick. Didn't happen before 0.14.

**Comment by iammerrick** [comment]
I've found it is because the events are handled in a different order with fastclick, so the batching gets weird...

**Comment by iammerrick** [comment]
e.g. click gets fired before touchEnd, so click handler setState to remove subtree, and then react tries to do something with it in touch end perhaps?
