### ISSUE TITLE
Memory leak in ReactDOMInput on server rendering

### ISSUE THREAD

**Issue by STRML** [facebook/react#4870]
In React 0.14.0-rc1 I've seen a massive memory leak as it appears my entire app is being retained.

After some time in the profiler, I narrowed it down to ReactDOMInput's `instancesByReactID` (I have a radio input in my app):

![screen shot 2015-09-14 at 1 41 02 pm](https://cloud.githubusercontent.com/assets/1197375/9858788/41385a02-5ae8-11e5-958f-ce66a2dc4485.jpg)

Removing `instancesByReactID` entirely in the source fixes the leak.

To diagnose this, I added some log statements:

```javascript
  mountWrapper: function (inst, props) {
    LinkedValueUtils.checkPropTypes('input', props, inst._currentElement._owner);

    var defaultValue = props.defaultValue;
    inst._wrapperState = {
      initialChecked: props.defaultChecked || false,
      initialValue: defaultValue != null ? defaultValue : null,
      onChange: _handleChange.bind(inst)
    };

    console.log("mounted input, id", inst._rootNodeID);
    instancesByReactID[inst._rootNodeID] = inst;
  },

  unmountWrapper: function (inst) {
    console.log("unmounted input, id", inst._rootNodeID);
    delete instancesByReactID[inst._rootNodeID];
  },
```

Then ran the app:

```
mounted input, id .gkkc0jr400.1.0.1.2.0.1.0.5.$basic/=1$basic.$basic
mounted input, id .gkkc0jr400.1.0.1.2.0.1.0.5.$basic/=1$advanced.$advanced
INFO: 127.0.0.1 (Chrome 46, Mac OS) - "GET /app/trade/XBTU15" 200 -b - 312.409 ms
mounted input, id .280er686xog.1.0.1.2.0.1.0.5.$basic/=1$basic.$basic
mounted input, id .280er686xog.1.0.1.2.0.1.0.5.$basic/=1$advanced.$advanced
INFO: 127.0.0.1 (Chrome 46, Mac OS) - "GET /app/trade/XBTU15" 200 -b - 587.734 ms
```

Notice that the unmount never logs, so these instances stay in `instancesByReactID` forever.

I am simply rendering using `ReactDOMServer.renderToString()`.

**Comment by STRML** [comment]
The difference appears to be that in 0.13, adding the node to `instancesByReactID` happened in `componentDidMount`, which never fires on the server:

```javascript
  componentDidMount: function() {
    var id = ReactMount.getID(this.getDOMNode());
    console.log('mounting', id);
    instancesByReactID[id] = this;
  },

  componentWillUnmount: function() {
    var rootNode = this.getDOMNode();
    var id = ReactMount.getID(rootNode);
    console.log('unmounting', id);
    delete instancesByReactID[id];
  },
```

So my console is quiet when running the app with these log statements.

**Comment by zpao** [comment]
cc @spicyj

**Comment by STRML** [comment]
@zpao Is there a plan for this, or do you have some pointers for how the team wants to hire server rendering architecturally so mount code like this doesn't fire? Happy to do a PR, this is definitely a 0.14 blocker. Our testnet servers crash every 8hrs because of this.

**Comment by spicyj** [comment]
I haven't decided how best to fix this. You can see I already marked it for the 0.14 milestone though.

**Comment by STRML** [comment]
:+1: Thanks!
