### ISSUE TITLE
Please use symbols as fields not as values

### ISSUE THREAD

**Issue by Gozala** [facebook/react#4871]
In react@0.14 special symbol is uset to mark `React.Element` instances. Unfortunately the symbol is used as a value of the for `$$typeof` field rather than a name. It would be really great it was other way round like:

```js
// The Symbol used to tag the ReactElement type. If there is no native Symbol
// nor polyfill, then a plain number is used for performance.
var IS_REACT_ELEMENT =
  (typeof Symbol === 'function' && Symbol.for && Symbol.for('react.element')) ||
  0xeac7;


var ReactElement = function(type, key, ref, self, source, owner, props) {
  var element = {
    // This tag allow us to uniquely identify this as a React Element
    [IS_REACT_ELEMENT]: true,

    // Built-in properties that belong on the element
    type: type,
    key: key,
    ref: ref,
    props: props,

    // Record the component responsible for creating this element.
    _owner: owner,
  };
```

As that would allow instances that implement multiple interfaces VS being exclusive. For that matter it would be great if all other fields were also symbols.

**Comment by sebmarkbage** [comment]
Note that this simulates the ES Value Types proposal which would allow you to do:

```js
var symbol = typeof element;
```

It is our hope to be able to make these Value Types and therefore overloaded interfaces are not ideal.

Additionally, overloaded interfaces are not good for VM optimizations since current VMs optimize heterogeneous function signatures very poorly.

In fact, we considered using a symbol for the `$$typeof` name (e.g. `{ [TYPEOF_SYMBOL]: REACT_ELEMENT_SYMBOL }` which is different than what you're proposing but still better). However, the perf just isn't there:

http://jsperf.com/constructing-symbol-props

(One of several examples, the rest are on Twitter which is down for me now.)

**Comment by Gozala** [comment]
> Note that this simulates the ES Value Types proposal which would allow you to do:
> 
> var symbol = typeof element;
> It is our hope to be able to make these Value Types and therefore overloaded interfaces are not ideal.

Got it makes sense ? Although in that case value of `type` field could not be a react component class can it ?

> Additionally, overloaded interfaces are not good for VM optimizations since current VMs optimize heterogeneous function signatures very poorly.

I'm mostly interesting in implementing virtual elements that implement interface for several virtual-dom implementations and `$$typeof` seems generic enough that I fear conflicts. But I guess real issues is making these libraries agree on comment interface instead.

 


> In fact, we considered using a symbol for the $$typeof name (e.g. { [TYPEOF_SYMBOL]: REACT_ELEMENT_SYMBOL } which is different than what you're proposing but still better). However, the perf just isn't there:
> 
> http://jsperf.com/constructing-symbol-props

Oh wow I did not expect that, thanks for pointing this out. May I sill suggest something like `$react$typeof` ?

**Comment by sebmarkbage** [comment]
I'm hoping that `$$typeof` becomes the canonical name to polyfill value types like objects similarly to how `@@iterator` is used to polyfill the iterator hook.

As for multiple `virtual-dom`, yes, I'm hoping to be able to find agreement on a common interface. We're not quite there yet but I'm working hard on removing React specific pieces from this interface piece by piece in hope of eventually being able to unify.
