### ISSUE TITLE
0.14 React component classes must extend React.Component.

### ISSUE THREAD

**Issue by syranide** [facebook/react#4878]
... because `.isReactClass` ends up not being exposed on instances of my ReactSWF. https://github.com/syranide/react-swf/blob/master/react-swf.js#L282-L283

That's the correct way to set up inheritance I thought? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain#Example

Am I missing something?

**Comment by sebmarkbage** [comment]
Inheritance also includes "static" properties. I.e. properties on the constructor.

**Comment by sebmarkbage** [comment]
Try `Object.assign(ReactSWF, React.Component)` first.

**Comment by syranide** [comment]
@sebmarkbage :+1: Makes sense, but perhaps it's something that should be mentioned with the release notes? AFAIK it's not standard practice for JavaScript inheritance.

**Comment by troutowicz** [comment]
The reason `static` methods get inherited when using ES6 classes is because the prototype of the subclass is the superclass. You can do something similar with `Object.create`.

```js
function A() {}
A.prototype.protoMethod = function () {
  return 'protoMethod'
}
A.staticProp = 'staticProp';

function B() {}
B.prototype = Object.create(A, {
  protoMethod: {
    value: function () {
      // call super
      return A.prototype.protoMethod();
    },
    enumerable: true,
    configurable: true, 
    writable: true
  }
});

var instance = new B();
console.log(instance.staticProp);
console.log(instance.protoMethod());
```

**Comment by syranide** [comment]
@troutowicz The problem with that is that `instance instanceof A === false` though.

**Comment by troutowicz** [comment]
@syranide Yeah, I wrote that a little carelessly... it's actually completely wrong. The only other way I see that provides the expected result is to alter the internal [[Prototype]] property. (which can decrease perf)

```js
Object.setPrototypeOf(B, A);
B.prototype = Object.create(A.prototype);
B.prototype.constructor = B;
```
