### ISSUE TITLE
ReactTestUtils.isCompositeComponent (called by scry*) throws on stateless components

### ISSUE THREAD

**Issue by taion** [facebook/react#4882]
Example:

```js
const Component1 = () => <div>Foo</div>;
class Component2 extends React.Component {
  render() {
    return (
        <div>Foo</div>
    );
  }
}
const instance = ReactTestUtils.renderIntoDocument(<Component1 />);

const div = ReactTestUtils.findRenderedDOMComponentWithTag(
  instance, 'DIV'
);
expect(div).to.exist;
```

This works with `Component2` but not with `Component1`.

**Comment by jimfb** [comment]
Stateless components have no public instance (return value of `renderIntoDocument`). If you were to wrap it in another (stateful) composite then you could use that instance.  There is some relevant discussion in https://github.com/facebook/react/issues/4839.  At this point, I think we're going to keep this behavior.  I created an issue to document it: https://github.com/facebook/react/issues/4913

**Comment by happypoulp** [comment]
@jimfb I am having the same issue with `scryRenderedDOMComponentsWithTag` and I don't understand the "wrapping" approach you're suggesting.
I tried:

```javascript
const StatelessComponent = () => <div>foo</div>

const Wrap = class Wrap extends React.Component {
  render () {
    return <StatelessComponent />
  }
}
```

but then calling
```javascript
  const component = renderIntoDocument(<Wrap />)
  const div = scryRenderedDOMComponentsWithTag(component, 'div')
```

produce this error:

```
.../node_modules/react/lib/ReactTestUtils.js:102
    return typeof inst.render === 'function' && typeof inst.setState === 'function';
                      ^

TypeError: Cannot read property 'render' of null
    at Object.ReactTestUtils.isCompositeComponent (.../node_modules/react/lib/ReactTestUtils.js:102:23)
...
```

Did I misunderstood what "wrap it in another (stateful) composite" means?

Thanks!

**Comment by spicyj** [comment]
@happypoulp That might just be a different issue. Can you open it separately?

**Comment by spicyj** [comment]
Actually never mind we can use this one.
