### ISSUE TITLE
Incorrect `dangerouslySetInnerHTML` warning link

### ISSUE THREAD

**Issue by MethodGrab** [facebook/react#4883]
The short url redirect for the error `props.dangerouslySetInnerHTML must be in the form {__html: ...}` ( https://fb.me/react-invariant-dangerously-set-inner-html) ([src](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDOMComponent.js#L242)) is incorrect, the page it redirects to is a 404.

**Comment by zpao** [comment]
Good catch, that should point at http://facebook.github.io/react/tips/dangerously-set-inner-html.html. I'll fix it in a little bit.

**Comment by zpao** [comment]
Fixed. Thanks again for the heads up.

**Comment by MethodGrab** [comment]
:+1:
