### ISSUE TITLE
Chrome extension error 0.14-rc

### ISSUE THREAD

**Issue by brigand** [facebook/react#4886]
With the rc and react-router@1 I'm getting this error when changing routes. I'm not sure if the problem is with the extension, react, react-router, or hot-loader, or how to narrow it down.

With the extension disabled (e.g. incognito) the error doesn't happen. This error does cause the render to fail and the view doesn't update.

![image](https://cloud.githubusercontent.com/assets/936069/9887400/5187ccb4-5ba4-11e5-946a-4a8bee7c956d.png)

```	
      function getData(element) {
	  /* ... */
	  if (element._renderedComponent) {
	    nodeType = 'NativeWrapper';
	    children = [element._renderedComponent];
	    props = element._instance.props; // here
	    state = element._instance.state;
	    context = element._instance.context;
  	    /* ... */
```

**Comment by syranide** [comment]
dev tools has a separate repository, anyway, this was a bug in dev tools 0.14.2, it's fixed in 0.14.3... so it's weird that you're seeing it now. https://github.com/facebook/react-devtools/issues/204

**Comment by brigand** [comment]
I restarted my computer and now I can't reproduce. Maybe chrome has to restart for dev tools extensions to update?

**Comment by slorber** [comment]
I had this too, but i guess it was because i was still using the old devtool beta :)
