### ISSUE TITLE
Anchors onClick not executed when anchor url is present.

### ISSUE THREAD

**Issue by tomitrescak** [facebook/react#4894]
I have spent significant time on checking why my onClick events on anchors are not triggered, contacted all other parties whose packages I use and they all point to basic React functionality. Do you have any idea why my onClick is not triggered?

NOT TRIGGERED
```
<a onClick={this.myEvent.bind(this)} href="/some/roue" />
```

TRIGGERED

```
<a onClick={this.myEvent.bind(this)} />
```

TRIGGERED

```
<a onClick={this.myEvent.bind(this)} href="#" />
```

Do you have any idea what can be the problem?
Thanks

**Comment by iamdustan** [comment]
If I had to guess, it's standard browser functionality that you’re experiencing. The latter two examples don’t trigger browser navigation. The first example does unless you call `event.preventDefault()` in your handler.

**Comment by zpao** [comment]
What @iamdustan said. You're handler is getting called but if you don't prevent the default behavior of the browser (navigating) then it doesn't really matter.

**Comment by tomitrescak** [comment]
Heh, how can you prevent the default browser behavior when onClick is the entry point? My handler is not called, the method does not enter ... not that dumb ...

**Comment by zpao** [comment]
I'd be very interested to see a test case showing onClick not getting called. I can't reproduce the issue you're reporting.

**Comment by darrinholst** [comment]
@tomitrescak ever figure this out? We're seeing this behavior on all windows browsers, it works on all the macos browsers.

**Comment by darrinholst** [comment]
False alarm. We had an event handler prior to reacts doing a `stopImmediatePropagation`.

**Comment by g-patel** [comment]
@tomitrescak any luck on this? I am seeing the behavior when the onClick handler is not called sporadically.
