### ISSUE TITLE
react-dom wrong package from npm?

### ISSUE THREAD

**Issue by eriknyk** [facebook/react#4895]
Hi,
I executed just now:
```
npm install react react-dom
```

But the react-dom package version that is being downloaded seems is not the right package:

```
$ ll node_modules/react-dom
total 48
-rw-r--r--  1 erik  staff   967B May  5  2014 Cakefile
-rw-r--r--  1 erik  staff   1.0K May  5  2014 MIT-LICENSE
-rw-r--r--  1 erik  staff   1.9K May  6  2014 README.md
drwxr-xr-x  3 erik  staff   102B May  6  2014 examples
-rw-r--r--  1 erik  staff   1.3K Sep 16 19:59 package.json
-rw-r--r--  1 erik  staff   2.1K May  5  2014 react-dom.js
-rw-r--r--  1 erik  staff   1.2K May  5  2014 react-dom.min.js
drwxr-xr-x  3 erik  staff   102B May  5  2014 spec
```
and watching the package.json, it is pointing to: https://github.com/EtienneLem/react-dom

I'm doing something wrong or something is going wrong?

**Comment by zpao** [comment]
`npm` is treating rc1 as a prerelease even though it's stable. We haven't removed the old version of the package so it still gets install since it's "stable".

I just added a deprecation notice on npm so you'll see this in the future:

> npm WARN deprecated react-dom@0.1.0: The old react-dom package has been deprecated. Until React v0.14 is officially released, please installed react-dom with npm install react-dom@latest

So just run `npm install react-dom@latest`
