### ISSUE TITLE
React.addons.CSSTransitionGroup don't remove element from DOM

### ISSUE THREAD

**Issue by manuelmazzuola** [facebook/react#4896]
I've a problem with the `React.addons.CSSTransitionGroup` component.
I use React and ES6 with babel.

This is the incriminated piece of code:
```
let ReactCSSTransitionGroup = React.addons.CSSTransitionGroup;
...
return (
      <div className="row landing" ref="landing">
        <ReactCSSTransitionGroup transitionName="list" transitionAppear={true}>
          { this.state.showList ? <List key="game-list" /> : null }
        </ReactCSSTransitionGroup>
```

```
.list-enter {
    opacity: 0.01;
  }

  .list-enter.game-list-enter-active {
    opacity: 1;
    transition: opacity .1s ease-in;
  }
  .list-leave {
    opacity: 1;
  }

  .list-leave.example-leave-active {
    opacity: 0.01;
    transition: opacity .1s ease-in;
  }
```
The entering animation works, but when `this.state.showList` is false the `List` component remains in the DOM.
It works (without animations obviously) without the ReactCSSTransitionGroup wrapper.

**Comment by spicyj** [comment]
If you're using 0.13, this is almost definitely fixed in 0.14.

**Comment by spicyj** [comment]
(If not, please post a repro case so I can debug.)

**Comment by manuelmazzuola** [comment]
No it is fixed. Thank you.

Il giorno gio 24 set 2015 23:41 Ben Alpert <notifications@github.com> ha
scritto:
