### ISSUE TITLE
Can't disable transitions for elements on initial load

### ISSUE THREAD

**Issue by nicholasalanbrown** [facebook/react#4898]
Hello:

I'm following along with the docs adding transitions via  `ReactCSSTransitionGroup = React.addons.CSSTransitionGroup` and everything is working great. The only problem I have is that the transition fires even on the mount of the component, despite what the docs say, and nothing I do will turn it off. Here's my component:

```
C.FeedList = React.createClass({
    render() {
        return (
            <div>
            <C.ReactCSSTransitionGroup transitionName="feed-transition">
        {
          this.props.posts.map(doc => {
            return <C.PostItem key={doc._id}
              { ...doc }
              destroyPost={ doc.destroy }/>;
          })
        }
            </C.ReactCSSTransitionGroup>
      </div>
        );
    }
});
```

What am I doing wrong?

**Comment by camsong** [comment]
You can try to add `console.log` in the first place of `render()` method to make sure it is not rendering more than one time.

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition
