### ISSUE TITLE
too broad defensive termination clause in PATENTS

### ISSUE THREAD

**Issue by chulkilee** [facebook/react#4900]
Current defensive termination clause is **far broader** defensive than original Apache License 2, which makes difficult to use it in enterprise. It is now covering any actions against any part of Facebook, while previous Apache License covers only this project.

I don't know where to address this issue (e.g. couldn't find a contact at [https://code.facebook.com/projects/]()), so created an issue here. Please forward this issue to Facebook legal / opensource team.

From [PATENT in v0.13.0](https://github.com/facebook/react/blob/v0.13.3/PATENTS)

```
The license granted hereunder will terminate, automatically and without notice,
if you (or any of your subsidiaries, corporate affiliates or agents) initiate
directly or indirectly, or take a direct financial interest in, any Patent
Assertion: (i) against Facebook or any of its subsidiaries or corporate
affiliates, (ii) against any party if such Patent Assertion arises in whole or
in part from any software, technology, product or service of Facebook or any of
its subsidiaries or corporate affiliates, or (iii) against any party relating
to the Software. Notwithstanding the foregoing, if Facebook or any of its
subsidiaries or corporate affiliates files a lawsuit alleging patent
infringement against you in the first instance, and you respond by filing a
patent infringement counterclaim in that lawsuit against that party that is
unrelated to the Software, the license granted hereunder will not terminate
under section (i) of this paragraph due to such counterclaim.
```

Related part from [LICENSE at v11.2](https://github.com/facebook/react/blob/v0.11.2/LICENSE)

```
   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.
```

Related

- #3554 
- https://news.ycombinator.com/item?id=9271331

**Comment by zpao** [comment]
Please contact `legal@fb.com` with your concerns, we won't be having more patent discussions here.

FWIW, note that the patent grant was updated between v0.13.0 and 0.13.3 (https://github.com/facebook/react/commit/78cca021f3cf203f0452e940f03d3eb1ab46cfeb) and the language was refined - more on the topic: https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/

**Comment by chulkilee** [comment]
Thanks for the quick response!

Although the change must be made by legal team, I do think it's very important to have open discussion on this matter, because that's one of good way how Facebook get community feedback. It would be nice to have another "meta" channel for Facebook opensource project, but apparently there isn't. So for now, please do not lock this issue :)

BTW I put wrong label on the link on PATENTS - it actuallys comes from v0.13.3.

**Comment by sai-prasanna** [comment]
Dont you guys ( @zpao )  think its unfair for a open source project to have such a broad patents claim? I mean why shouldn't anyone file patents lawsuit against facebook if it has nothing to do with React ? 

Dont you think it affects open source movement as a whole?

Can you be open about your opinion regarding this rather than give generic "contact legal team" response .. I understand that you may not  have much say regarding this, but cant you be open about your opinion?

**Comment by KeitIG** [comment]
@chulkilee Did you send a mail to FB legals ? Did they answer you ? Because I do think too this is a really important concert anyone may face.

**Comment by chulkilee** [comment]
I just let our legal team know about this.

If there is another place Facebook get some feedback from developers, then I'd put my vote there... but I could not find it :(

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
