### ISSUE TITLE
schema tags different between client and server.

### ISSUE THREAD

**Issue by sabeurthabti** [facebook/react#4906]
Hi guys, getting this annoying error. Currently we are doing the following:

``` jsx
<section className="product-details" itemScope="true" itemType="//schema.org/Product">
```
and it's giving the following:

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) t-details" itemscope itemtype="//schema.
 (server) t-details" itemscope="" itemtype="//sche

**Comment by syranide** [comment]
The error message is right, but the context it provides is incorrect (#4324).

**Comment by zpao** [comment]
Please investigate your case further. This message is somewhat unreliable at pinpointing the problem so it's likely elsewhere in your app.
