### ISSUE TITLE
CSSTransitionGroup does not remove DOM elements reliably (inc. video example)

### ISSUE THREAD

**Issue by thesnackalicious** [facebook/react#4907]
Just started playing around with CSSTransitionGroup and I'm encountering an intermittent bug that appears to be the result of a race condition. The bug results in the `-leave` and `leave-active` classes not being added, causing the warning `Warning: transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition.` to appear in the console.

The issue only appears when I am trigging many updates to the CSSTransitionGroup in relatively quick succession.

I am using the latest version of Chrome on Ubuntu 15.04. I have created a video demoing this bug: http://sendvid.com/c07iyn0m

**Comment by spicyj** [comment]
We changed this in 0.14 so you have to specify a duration now. #1326
