### ISSUE TITLE
xmlns:xlink (and other SVG namespaced attrs) not supported

### ISSUE THREAD

**Issue by derekdreery** [facebook/react#4908]
At the moment when I try to use a `defs` element, I get the following error:
> Namespace tags are not supported. ReactJSX is not XML.

Namespaces are required for effective use of SVG. Is there a design decision not to allow namespaced tags, or is it just a feature that needs implementing?

**Comment by derekdreery** [comment]
Found issue #2250 which seems to solve this.

**Comment by agm1984** [comment]
In the interest of saving time, the solution is to use camel case:

``` javascript
<svg xlinkHref="http://i.imgur.com/w7GCRPb.png" />
```
renders to

``` javascript
<svg xlink:href="http://i.imgur.com/w7GCRPb.png" />
```

**Comment by abhinavsri360** [comment]
This helped a lot, Thank you @agm1984

**Comment by dshung1997** [comment]
This helped a lot. It's like changing from "stroke-width" to "strokeWidth"

**Comment by gbyteinfo** [comment]
> In the interest of saving time, the solution is to **use camel case**:
> 
> ```js
> <svg xlinkHref="http://i.imgur.com/w7GCRPb.png" />
> ```
> 
> renders to
> 
> ```js
> <svg xlink:href="http://i.imgur.com/w7GCRPb.png" />
> ```

Obrigado agm1984, Lembrando que para 
`<use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)" />`
Mesma ideia
`<use xlinkHref="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)" />`

por ai vai valew !!!
