### ISSUE TITLE
React.addons.createFragment warning message

### ISSUE THREAD

**Issue by ffxsam** [facebook/react#4909]
I just got this message:

>Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.

I was wondering how easy it would be to add some sort of stack trace to this, so we could see where the offending code is.

**Comment by spicyj** [comment]
In 0.14 you should get the component name but it is also a hard error that will break your app. This would have been good for us to do but we're not planning another 0.13 release – sorry.
