### ISSUE TITLE
What do "instances" in React.Perf correlate to?

### ISSUE THREAD

**Issue by kkirby** [facebook/react#4911]
I'm having some issues trying to figure out what an `instance` is in reference to React.Perf. Do `instances` refer to the amount of times that component was created? Or does it refer to the amount of children components that the component created? Or something else entirely?

Thanks!

**Comment by spicyj** [comment]
Yes, just the number of times the component was created.

![image](https://cloud.githubusercontent.com/assets/6820/10087859/8183a87e-62cb-11e5-903b-6a1648d4fa9c.png)

**Comment by faceyspacey** [comment]
but why is the number so high often?

**Comment by gaearon** [comment]
Because the current implementation is buggy. In reality it reports the number of times `render()` has been called. This is being fixed in #6404. Since that code is being rewritten completely we won’t fix it in the existing version.
