### ISSUE TITLE
ReactTestUtils scryRenderedDOMComponentsWithClass/findRenderedDOMComponentWithClass does not handle SVG classNames

### ISSUE THREAD

**Issue by kayneb** [facebook/react#4912]
SVG classNames are not raw strings. ReactTestUtils does not handle the format that SVG elements have for className, i.e.

```
SVGAnimatedString {
  animVal: "picture"
  baseVal: "picture"
}
```

**Comment by padresmurfa** [comment]
Hi @kayneb .  I just got bitten by the same issue.  You didn't happen to find a workaround, did you?

**Comment by Aweary** [comment]
`scryRenderedDOMComponentsWithClass` will get the `class` attribute via `inst.getAttribute` if the `className` is not a string. [src/test/ReactTestUtils.js#L190](https://github.com/facebook/react/blob/ba9b985406ff56c2dea192b119328b6096895097/src/test/ReactTestUtils.js#L190)

What return value are you seeing specifically? Also, are you using jsdom?

**Comment by padresmurfa** [comment]
Thanks @Aweary I see that we actually are using an older version of react test utils that doesn't check for the typeof className.  We were seeing the SVGAnimatedString just like kayneb.

We are not using jsdom, but I would expect for the moment that the issue is our old code base, not the dom.

**Comment by gaearon** [comment]
Seems like that was fixed then.
