### ISSUE TITLE
Document that React.render() may return null if component doesn't have an instance/state

### ISSUE THREAD

**Issue by jimfb** [facebook/react#4913]
Assuming we keep this behavior, it's worth noting in the documentation that React.render() may return null in cases where the component doesn't have any instance state.

**Comment by zpao** [comment]
(removing "good first bug" since this would be best done by somebody with more knowledge about React)

**Comment by blainekasten** [comment]
Looks like this can be closed since #4964 was merged and is marked as fixing this issue. cc @zpao

**Comment by jimfb** [comment]
Correct, thanks!
