### ISSUE TITLE
displayName is set to "o" when minifiying Stateless function components via webpack

### ISSUE THREAD

**Issue by jimbolla** [facebook/react#4915]
Given a component defined as: 

    export const SubmitButton = ({readyState, defaultText, pendingText}) => (
        <button
            className="btn btn-lg btn-primary btn-block"
            type="submit"
            disabled={readyState === "pending"}>
            {
                readyState === "pending"
                    ? (pendingText || defaultText)
                    : defaultText
            }
        </button>
    );

and minified with webpack's UglifyJsPlugin, you get components with displayName "o" in the React browser tools.

![untitled](https://cloud.githubusercontent.com/assets/1851364/9974316/584d1166-5e57-11e5-8dc8-51c768af1d6b.png)

**Comment by jimbolla** [comment]
Given a component defined as: 

    export const SubmitButton = ({readyState, defaultText, pendingText}) => (
        <button
            className="btn btn-lg btn-primary btn-block"
            type="submit"
            disabled={readyState === "pending"}>
            {
                readyState === "pending"
                    ? (pendingText || defaultText)
                    : defaultText
            }
        </button>
    );

and minified with webpack's UglifyJsPlugin, you get components with displayName "o" in the React browser tools.

**Comment by towry** [comment]
React component will use function name as the component's displayName if the displayName is not set.

```js
var A = React.createClass({...})
```

The component's displayName is `A`, so since you minified the js code, I think React taken the correct function name `o` as the displayName.

**Comment by theaqua** [comment]
It's problem with minification, not with react. Keep your variables names.

**Comment by jimbolla** [comment]
Uglify may be the culprit, but React is the one that suffers because of it. Not minifying code isn't really a good answer. I tried it with setting `mangle: false` and then it reported all the component names as `StatelessComponent`. My thought was maybe what we need is a Babel transform that adds whatever is needed.

**Comment by towry** [comment]
@jimbolla Why you need uglify in development mode?

**Comment by zpao** [comment]
React doesn't do the transformation but feel free to file an issue against babel. If there's something React needs to do differently we can reopen.

**Comment by spicyj** [comment]
You shouldn't minify in development mode anyway.

**Comment by silvenon** [comment]
So our code shouldn't rely on `displayName` if they're going to get mangled? I use `displayName` to check if a child is a specific type, is this bad practice?

**Comment by spicyj** [comment]
@silvenon I wouldn't recommend it. Why not compare the type to the object exactly?

**Comment by silvenon** [comment]
Mind blown :open_mouth: Thanks a bunch!

For others who stumble onto this discussion:

```jsx
import React from 'react';
import Foo from './Foo';

const Bar = (props) => {
  if (props.children.type === Foo) {
    // ...
  }
  
  return (
    {/* ... */}
  );
};
```

**Comment by dminkovsky** [comment]
If stateless functions support `.propTypes` and `.defaultProps` as static members, would it be possible to support `.displayName` in that same way as well?

**Comment by spicyj** [comment]
@dminkovsky I haven't tried but I would expect that to already work?

**Comment by dminkovsky** [comment]
@spicyj Totally works :D

**Comment by wzup** [comment]
> React doesn't do the transformation but feel free to file an issue against babel.

@zpao Is that all you can say against this issue (as a person with a badge `owner` oth repo)? Then downvote.
Don't you have a solution, best React practice, for this issue yet? How is it possible?

**Comment by gaearon** [comment]
@wzup 

There’s no need to be combative about it. What @zpao is saying is that **there is nothing on React side that needs to be fixed because React is not the one assigning names to your functions.**

In production, it is **expected** that you will see minified names. That’s the whole point of minifying. It removes unnecessary code (and mangles identifiers).

In development, you should not be using minification in the first place. Minification is causing this, but you shouldn’t minify when you’re just developing. Minification is only needed for your users.

There is nothing to be done on the React side here, and it’s not a React issue (or, rather, not an issue at all).
