### ISSUE TITLE
Support es6 symbols in proptype

### ISSUE THREAD

**Issue by dashed** [facebook/react#4917]
Would you be open to support es6 symbols in proptype?

At the moment I'm testing them as `typeof Symbol() === 'symbol'` in custom proptype functions.

**Comment by steve-taylor** [comment]
Here's what I use (not sure if it's the right approach):

```javascript
function symbol(props, propName, componentName) {
    const prop = props[propName];
    if (prop && (typeof prop !== 'symbol')) {
        return new Error(`[${componentName}]: Expected property ${propName} to be a Symbol, but its actual type is ${typeof prop}.`);
    }
}

symbol.isRequired = function(props, propName, componentName) {
    return props[propName] ?
           symbol(props, propName, componentName) :
           new Error(`[${componentName}]: Property ${propName} is required.`);
};

export default symbol
```

**Comment by zpao** [comment]
We've generally said no to a lot of custom proptypes checks but this one feels like it's probably ok. In theory it's a 1 line change. However we aren't applying the [Symbol transform](https://babeljs.io/docs/advanced/transformers/es6/spec-symbols/) (which changes all `typeof` checks) so we'd have to do something similar with the type (already have that in place for `RegExp`s and old browsers) - not hard but just a little bit more work.

Thoughts @sebmarkbage @spicyj

**Comment by sebmarkbage** [comment]
Yea. Seems reasonable. The .constructor === Symbol as a fallback is ok. Not ideal since it doesn't work cross-realm but we should use whatever is standard practice among popular polyfills.

**Comment by puradox** [comment]
Any possibility that this will be added in future versions?

**Comment by zpao** [comment]
Yes, we just never got back to it. If you're interested in working on it, this is something that would make a nice addition in 15.1.

**Comment by RaitoBezarius** [comment]
@zpao No one is assigned? I could do a PR for it!

**Comment by gaearon** [comment]
GitHub doesn’t make it very obvious :cry: 

Usually when people start working on a feature they reference it, and it appears in the issue.
You can see the existing PR above:

<img width="969" alt="screen shot 2016-03-31 at 14 20 27" src="https://cloud.githubusercontent.com/assets/810438/14176981/d4e98eb0-f74b-11e5-99a5-ba119fc32ef6.png">

**Comment by zpao** [comment]
Also, you can't assign issues to people who don't have commit access, making it much harder to communicate that somebody outside the core team is working on it.

**Comment by RaitoBezarius** [comment]
That's a shame, it seems related to https://github.com/isaacs/github/issues/369 and https://github.com/isaacs/github/issues/100 :/

**Comment by ffxsam** [comment]
Any update on this? I suppose I'll switch to string constants in this one instance, but symbols would've been better!

**Comment by RaitoBezarius** [comment]
@ffxsam A PR is running on #6377 -- I don't know what is the status, but it looks complete on our side. Maybe, it will be merged soon!

**Comment by gaearon** [comment]
We’re still ironing out how we’ll move on with cutting branches on 15.x but once it’s decided I expect this to get in.

**Comment by spicyj** [comment]
Looks like #6377 was merged. Should be in 15.1 or 15.2.
