### ISSUE TITLE
Support full component lifecycle in shallow rendering

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#4919]
Extracted as a separate issue from https://github.com/facebook/react/issues/4056#issuecomment-139849820

I've put together a side-by-side comparison of lifecycle support between "normal" rendering and "shallow" rendering.

http://jsfiddle.net/xvs6xdfk/3/

Output using normal rendering
```
Rendering Comp with Object {key: 1, a: 1}
componentWillMount []
render []
componentDidMount []
Rendering Comp with Object {key: 1, a: 2}
componentWillReceiveProps [Object, Object]
shouldComponentUpdate [Object, null, Object]
componentWillUpdate [Object, null, Object]
render []
componentDidUpdate [Object, null, Object]
Rendering Comp with Object {key: 2}
componentWillUnmount []
componentWillMount []
render []
componentDidMount []
```

Output using shallow rendering
```
Rendering Comp with Object {key: 1, a: 1}
componentWillMount []
render []
Rendering Comp with Object {key: 1, a: 2}
componentWillReceiveProps [Object, Object]
shouldComponentUpdate [Object, null, Object]
componentWillUpdate [Object, null, Object]
render []
Rendering Comp with Object {key: 2}
componentWillReceiveProps [Object, Object]
shouldComponentUpdate [Object, null, Object]
componentWillUpdate [Object, null, Object]
render []
```

Happy to look into doing a PR for this, although I'm not sure quite where to start - would this be done in the shallow renderer itself, or pushed down to a custom transaction as mentioned in https://github.com/facebook/react/issues/4019#issuecomment-140158888 ?

**Comment by gaearon** [comment]
Somewhat related: https://github.com/facebook/react/issues/3760
