### ISSUE TITLE
CSS hover state sticks when removing DOM elements

### ISSUE THREAD

**Issue by ffxsam** [facebook/react#4922]
I've got a bunch of tags (using `<span>`). When I click a tag to remove it, the hover state is maintained. See screencap below. Mac OS 10.10.5, Chrome 45.

![licecap](https://cloud.githubusercontent.com/assets/12532733/9984942/d070919c-5fd6-11e5-8e57-526403c7c20a.gif)

**Comment by Sobranier** [comment]
Eveny Dynamic Children should have an unique key to be distinguished from its brothers

**Comment by ffxsam** [comment]
Ahh, my mistake. I used a not-so-great key!
