### ISSUE TITLE
Guide to implement new rendering option?

### ISSUE THREAD

**Issue by liuyang1204** [facebook/react#4924]
Hi,

I want to know whether there is a guide to implement a new rendering option for React, like the way of React Native.

That is to say: Use all features of React but render to a new kind of objects instead of HTML DOM.

I found [a session](http://oredev.org/2015/sessions/building-a-react-js-backend) but I can not find any detail about it.

**Comment by zpao** [comment]
There is not a guide at this point. We're still working out the details and the story about how to do it.

I'm going to close out since there's nothing really actionable at this point, we'll definitely put something up when we're ready.
