### ISSUE TITLE
How to trigger unmount action in tests if render returned null? 

### ISSUE THREAD

**Issue by message** [facebook/react#4925]
Hey. The only way i found how to unmount component in tests is 

```js
unmount: function(component) {
	if (component && component.isMounted()) {
		React.unmountComponentAtNode(component.getDOMNode().parentNode);
	}
}
```
When i render component with `ReactTestUtils.renderIntoDocument(...)` and return `null` from `render` method, `getDOMNode()` also returns `null`, and i'm not able to unmount component. Is there any workarounds?

P.S. Talking about 0.13

**Comment by zpao** [comment]
In that case you probably don't want to use `renderIntoDocument` - that's just a convenience method for testing that covers 80% of what people usually need. I don't think we're going to change this as it's trivial to implement - you can do exactly what it's doing and just hold a reference to the new node.

```js
var node = document.createElement('div');
var component = React.render(<Component />, node);
// ...
React.unmountComponentAtNode(node);
```
