### ISSUE TITLE
Invalid Checksum - Textarea Redux Form

### ISSUE THREAD

**Issue by albertdatui** [facebook/react#4926]
Hi guys!
I am having this error. I am quite new to react.

```Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:```

``` (client) $=12:0.0.0.2.0.0.6">
</textarea><br data```

``` (server) $=12:0.0.0.2.0.0.6"></textarea><br data-```

any helps will be much appreciated.
Thanks :)

**Comment by zpao** [comment]
Hmm, there's whitespace in your text area…

@spicyj @syranide - does this have anything to do with that newlines thing in text areas we did a little while ago? Or is that a red herring

**Comment by albertdatui** [comment]
I am so sorry, the error message should be a newline instead of a spaces. Here is the screen shot of the error.

![screen shot 2015-09-22 at 12 58 04 am](https://cloud.githubusercontent.com/assets/5680331/9998692/0f38ecd2-60c5-11e5-9395-4fe8eebe5771.png)

Is there anyway for me to fix this ?

**Comment by syranide** [comment]
@zpao Same content generated on client and server so I don't see how it could. I would rather assume @albertdatui is running different versions of React on client/server.

**Comment by jimfb** [comment]
No comments for over a month, closing.  If you believe this is a bug in React, please try to provide a simplified jsfiddle/example that demonstrates the problem and we can reinvestigate.
