### ISSUE TITLE
Whitespace Preceding Inline Comment in Table

### ISSUE THREAD

**Issue by llchan** [facebook/react#4928]
I put an inline comment in my jsx to document a table cell:

    <tr>
      <td>foo</td> {/* a comment about this cell */}
    </tr>

The first time it renders, everything looks fine, but when it re-renders, it hits an error where it cant find a DOM node.  What's happening is that the space between the `</td>` and the `{/*` is turned into an additional whitespace child of the `<tr>`, and the browser throws it out.  The unintuitive thing is that if the comment weren't there and it was just a line with trailing whitespace, the whitespace would instead be stripped out.

I understand the JSX transformer is content-unaware and it totally makes sense why this is happening, but this is a bit of a gotcha coming from other programming/markup languages so I figured I would report it and see if we can come up with a solution.  Maybe table-related components could be smarter about filtering out whitespace children since they are invalid (as far as i know)?

Obviously I'll work around it for now by butting the comment up against the cell.

**Comment by syranide** [comment]
cc @spicyj Perhaps the routine for validating DOM nesting could consider text nodes too?

**Comment by syranide** [comment]
> Obviously I'll work around it for now by butting the comment up against the cell.

You'll have to do that regardless, you should never pass invalid children (a text node to a tr). React can warn that you're doing something wrong, but it should not fix the error for you.

**Comment by spicyj** [comment]
I believe you'll already get a warning in 0.14.

**Comment by llchan** [comment]
Right, I understand that it transforms it that way and why it's necessary for other elements to preserve that whitespace.  I was mainly hoping for more informative errors/warnings/sanity checks, and if this is already in 0.14 as a warning that's perfect.  Thanks!
