### ISSUE TITLE
Controlled Radio Button Component Does not Update

### ISSUE THREAD

**Issue by benglass** [facebook/react#4930]
We are running across an issue in one of our components used for showing a group of radio buttons. The radio button elements are controlled (using checked and not defaultChecked) and they use a callback prop to change the state in a parent component which determines which one is selected.

When you first click a radio button, it works.

The second and any subsequent clicks do not update the radio button to show as checked.

Here is our example code that exhibits the issue.

http://jsbin.com/royolo/edit?js,console,output

I thought it might be related to the key of each element but we are using the radio button value as key on the element which *is* unique.

Any help is appreciated.

**Comment by spicyj** [comment]
I dug into this for like half an hour and couldn't figure it out. Very weird.

cc @zpao @syranide

**Comment by syranide** [comment]
Uhm... I'm getting React internal errors in the console when clicking which could explain a lot of it... are you not seeing those?

**Comment by benglass** [comment]
@syranide sorry I was trying to get the jsbin working and apparently it saved an incomplete change I had made.

It is reverted to the original case where it doesnt work and there are no js errors.

**Comment by zpao** [comment]
`e.preventDefault()` in your `change` handler is doing this. We have to actually hijack the `click` event to make `onChange` work for radios and checkboxes. The downside of this has come up a few times - that `preventDefault` in there actually prevents the browser from updating its state. See some prior discussions in #3005.

You don't actually need to call `preventDefault` here, and we've actually seen a lot of people blindly calling it without actually knowing why. I would recommend doing a spot check of your own handlers and seeing if they're actually needed throughout.

**Comment by spicyj** [comment]
@zpao Thanks.

**Comment by benglass** [comment]
@zpao Thanks so much for the explanation.

We are definitely calling this blindly in this case and its certainly not necessary but is there somewhere in the react docs where this could perhaps be added as a caveat? Perhaps in the TIPs section as "event.preventDefault breaks checkboxes/radio buttons" or in the controlled input section here https://facebook.github.io/react/docs/forms.html#uncontrolled-components

I'll submit a PR if you think its worth adding but my opinion would be that its so hard to debug if you run into this issue that it would be worth pointing out in the official docs.

**Comment by benglass** [comment]
I can see someone did add some docs here but I'm not sure if a PR was ever created

https://github.com/WickyNilliams/react/commit/5bf8cda58f81e940d7f2eafb18bd87c4f1244882

**Comment by benglass** [comment]
Here is the PR https://github.com/facebook/react/pull/3069
