### ISSUE TITLE
Refs on a child inside a function

### ISSUE THREAD

**Issue by jide** [facebook/react#4934]
When using ref inside a child as a function, refs set inside the result of the function are undefined in the owner. Is this normal ?

```js
class Container extends Component {
  render() {
    return this.props.children();
  }
}

class Demo extends React.Component {
  componentDidMount() {
    console.log(this.refs.inner); // undefined
  }

  render() {
    return (
      <Container ref='wrapper'>
        { () => (
          <Container ref='inner'>
            { () => <div/> }
          </Container>
        ) }
      </Container>
    );
  }
}
```

**Comment by frederickfogerty** [comment]
A workaround would be to use a ref callback, instead of a string ref. I prefer this style to string refs anyway.

```
class Container extends Component {
  render() {
    return this.props.children();
  }
}

class Demo extends React.Component {
  componentDidMount() {
    console.log(this.refs.inner); // undefined
  }

  render() {
    return (
      <Container ref={c => this.refs['wrapper'] = c}>
        { () => (
          <Container ref={c => this.refs['inner'] = c}>
            { () => <div/> }
          </Container>
        ) }
      </Container>
    );
  }
}
```

**Comment by syranide** [comment]
@jide You're effectively creating the children inside the calling `Container` so that's where the ref ends up, you need (and should) use the new ref style that @frederickfogerty shows.

**Comment by jide** [comment]
@frederickfogerty Did not know about this, thanks, amazing.

@syranide I was thinking about this today and it became obvious that the owner in this case is Container, which is perfectly logical. Yes I know this is somehow tricky, I'll let you know how I use this and why.

**Comment by jide** [comment]
@frederickfogerty Any reference on this ? If I try, I get `Uncaught TypeError: Can't add property inner, object is not extensible`, with both 0.13 and 0.14.

**Comment by jide** [comment]
Okay, it seems you have to affect refs to a custom object instead of using this.Refs, so : 
```
<Container  ref={ ref => this.containers.inner = ref }/>
```

@see https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

**Comment by spicyj** [comment]
Yes, or even just `this._inner = ref`.

**Comment by frederickfogerty** [comment]
@jide Sorry about the confusion, I didn't realise `this.refs` was write-protected in React. I just use `this._inner = ref` myself.

**Comment by TimDaub** [comment]
I just had the same problem as the contributors above, which is that I want to save a ref before actually overriding it in another deeper-nested component.

What I need to do now is:

```javascript
<OuterCompThatOverwritesRefs>
  <InnerCompThatWeWantARefFrom
    ref={ref => this.someAnnoyingName = ref}/>
</OuterCompThatOverwritesRefs>
```

What I'd like to do:

```javascript
<OuterCompThatOverwritesRefs>
  <InnerCompThatWeWantARefFrom
    ref={this.setRef}/>
</OuterCompThatOverwritesRefs>
```
