### ISSUE TITLE
Warn if ref attached to stateless component

### ISSUE THREAD

**Issue by jimfb** [facebook/react#4939]
Warn if ref attached to stateless component.  For background, see: https://github.com/facebook/react/issues/4936

**Comment by bspaulding** [comment]
It looks like this case already throws:

https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/__tests__/ReactStatelessComponent-test.js#L116-L126

https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L810

Sorry if I'm just being a newb. Am I looking at the totally wrong thing?

**Comment by jquense** [comment]
That case is for when you add a ref inside of a stateless component, not if you add a ref to one (from the outside)

**Comment by bspaulding** [comment]
Ah, dig. Got it.
