### ISSUE TITLE
CSSTransitionGroup animation doesn't occur on the one operated

### ISSUE THREAD

**Issue by chenxsan** [facebook/react#4949]
Demo here http://codepen.io/anon/pen/GpjgYg

Say I wanna remove the first item in the list, the `.example-leave-active` transition occurred on the last item, instead of the first one. This could be confusing since users might think they just remove the wrong one.

Did I just miss something?

Any suggest would be appreciated.

**Comment by VladShcherbin** [comment]
Same issue, the last elements is animated instead of the one that is removed. React 15 rc.2

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by VladShcherbin** [comment]
If someone will find this - this happened because index was used as a key. Always use unique id instead of index.
