### ISSUE TITLE
ReactTransitionGroup should consume `component` prop.

### ISSUE THREAD

**Issue by hallister** [facebook/react#4954]
When given a `component` prop `ReactTransitionGroup` will pass the prop on. 

When passing `ReactTransitionGroup` a factory for a component that also uses a `component` prop in similar fashion it will result in a warning:

```
Warning: Failed propType: Invalid prop `component` supplied to `CustomComponent`.
Check the render method of `ReactTransitionGroup`.
```

Is there a legitimate use for not consuming the prop? This doubles as a problem since it causes a warning _and_ requires that any component which can be a child of `ReactTransitionGroup` must also make sure that it's component prop doesn't equal itself.

Whoops, forgot that this exists in 0.14.0-rc1.

**Comment by spicyj** [comment]
No, this is probably unintentional.

**Comment by piglovesyou** [comment]
```javascript
var ReactTransitionGroup = React.createClass({
  // ...
  render: function() {
    // ...
    return React.createElement(
      this.props.component,
      this.props,
```
Because `props` is a sealed object, consuming property can be expensive.

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
