### ISSUE TITLE
RC1: Expected flush transaction's stored dirty-components length to match dirty-components array length.

### ISSUE THREAD

**Issue by syranide** [facebook/react#4958]
I've seen this error a handful of times in production now since switching to 0.14. No idea what's causing it at this point.

https://github.com/facebook/react/blob/81b4f7295df5fa9d4f03002eaf0ba8fb7e7fcdc6/src/renderers/shared/reconciler/ReactUpdates.js#L128

**Comment by spicyj** [comment]
I don't suppose you're using Flash to call into JS? Haven't ever seen this otherwise.

**Comment by syranide** [comment]
I am, but from the last events of the bug reports it seemed like that wasn't the issue... thanks for the hint, I'll dig around a bit in that code and see what I can find.

**Comment by spicyj** [comment]
Put a setTimeout 0 around the JS that Flash executes. It does crazy things and interrupts the running JS code in the middle of what it's doing when you try to call it, so if you don't do a setTimeout then literally all your code needs to be reentrant and threadsafe. I don't see how we can reasonably work around this in React.

**Comment by syranide** [comment]
Yeah I'm aware of some of the issues and while it's kind of hard to tell, it's seems like we had introduced some some edge-cases that could be problematic with respect to React. I've put the last ones behind `setTimeout` too, I'll shout if it reappears still, but I doubt it.

Thanks for the help!

**Comment by titoBouzout** [comment]
Can you please give a very short example on where to put the setTimeout, is not clear to me.

**Comment by gaearon** [comment]
>Can you please give a very short example on where to put the setTimeout, is not clear to me.

Are you doing this?

>you're using Flash to call into JS?

If not, the `setTimeout` recommendation is not relevant to you. Please file a new issue with an example reproducing this issue. Thanks!

**Comment by titoBouzout** [comment]
I'm using Flash to call into JS Yes. Please give me a example

**Comment by titoBouzout** [comment]
You mean I should this:

ActionScript: ExternalInterface.call("someFancyJSFunction")

JavaScript: function someFancyJSFunction() { setTimeout(... , 0) }

?

**Comment by gaearon** [comment]
yep!

**Comment by titoBouzout** [comment]
Thank you, Ill try it
