### ISSUE TITLE
why not to reuse `ReactElement`. 

### ISSUE THREAD

**Issue by jzlxiaohei** [facebook/react#4962]
Look the code below. I want to reuse  `indexElement`, but `constructor` invoked every time  , which means it was totally new `Element`. Could some one explain this behaviour? thanks.

    import  React from 'react'

    class IndexComponent extends React.Component{
        constructor(props,context){
            super(props,context)
            console.log('constructor should be called only once') // !!! be called many times
        }

        render(){
            return(
                <div>
                    <div>Index</div>
                    <div><a href='#/detail'>to Detail</a></div>
                </div>
            )
        }
    }

    class DetailComponent extends React.Component{
        render(){
            return(
                <div>
                    <div>Detail</div>
                    <div><a href='#/'>back to Index</a></div>
                </div>
            )
        }
    }

    let indexElement =<IndexComponent/>

    let detailElement= <DetailComponent/>

    let i = 0;

    let App = React.createClass({

        componentDidMount(){

          setInterval(()=>{
              i+=1;
              this.setState({
                  a:i
              })
          },1000)
        },

        render: function() {
            if(i%2==0){
                return indexElement;
            }else{
                return detailElement;
            }
        }

    });
    React.render((
            <App/>
        ), document.getElementById('mount-dom')
    )

**Comment by spicyj** [comment]
When you stop rendering a component it gets destroyed. If you want to keep its state around you can render it with `display:none` CSS.
