### ISSUE TITLE
Style isn’t working on newly constructed component

### ISSUE THREAD

**Issue by kibin** [facebook/react#4970]
I’m trying to pass `<div>` to higher order component which wraps it with another component. And I want to construct new div from this one with some new properties injected. Especially I’m interested in style property.

```
<child.type style={{ minWidth: 0, maxWidth: 'none', width: '100%' }} {...child.props} />
  {child.props.children}
</child.type>
```

But styles don’t apply, react treats them just like another properties. Is this proper behavior?

**Comment by jimfb** [comment]
Conceptually, what you're trying to do should work.  You've got a few bugs in your code (for instance, you have a self-closing jsx tag and then you close it again at the bottom.

I created a fiddle that demonstrates: https://jsfiddle.net/j8uq4vv7/

It looks like you might be new to the React community, welcome!  For future reference, we try to keep github issues for tracking bugs.  General usage questions are better answered on StackOverflow.

I'm going to close out this issue, but let me know if I miss-understood your question and we can re-examine this issue.

**Comment by kibin** [comment]
You understood it right, thanks!
