### ISSUE TITLE
HTMLDOMPropertyConfig does not include "integrity" for SRI

### ISSUE THREAD

**Issue by terinjokes** [facebook/react#4979]
[Subresource Integrity](http://w3c.github.io/webappsec/specs/subresourceintegrity/#the-integrity-attribute) defines the "integrity" attribute. This attribute is not defined in HTMLDOMPropertyConfig so it is not included in HTML rendered on a server.

**Comment by lijunle** [comment]
+1 here.

Modern browsers have supported this feature.

Bootstrap tell me to use the following [code snippet](http://getbootstrap.com/getting-started/#download-cdn) from CDN:

```html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
```

Here is the MDN introduction:

- https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by jimfb** [comment]
cc @zpao Contrary to popular belief, we do get these fairly frequently.  Related to #140

**Comment by terinjokes** [comment]
Related in that there should be a good way of replacing whitelisting attributes, but it's not a custom attribute in the same sense as `nopin`.

**Comment by zpao** [comment]
Yea "related", the underlying goal of that issue is to really get of the whitelist as much as possible, entirely would be good. I don't know that we called that out explicitly but they're mostly the same problem.

**Comment by jimfb** [comment]
@terinjokes Yeah, my comment was direct at a conversation we had at our last team meeting when figuring out our priorities for the remainder of the year.  Basically, there are a whole ton of attributes that we keep adding one-at-a-time, and I was/am pushing for us to solve #140 and wipe them all out (past present and future) with a single swipe.  But #140 is a slightly non-trivial change with several dependencies, so there is a little resistance/reluctance.  The issue I linked is a superset of this issue.
