### ISSUE TITLE
Examples should be visible on the React site (without cloning and running a server)

### ISSUE THREAD

**Issue by spicyj** [facebook/react#498]

**Comment by jsfb** [comment]
@spicyj Is this still an open bug?  The home page examples are visible without cloning.  If this issue is still valid, can you specify more specifically which examples you're concerned about?

**Comment by spicyj** [comment]
These examples:

https://github.com/facebook/react/tree/master/examples

**Comment by spicyj** [comment]
Would probably be part of a site redesign. I don't feel strongly about keeping this open though if you'd like to close it.

**Comment by jsfb** [comment]
No desire to close it.  I agree, it's nice when framework authors make it easy to run all the examples, and think this is a perfectly valid request.  I just wasn't sure which examples you were talking about and/or if the modern homepage satisfied the issue - sounds like it doesn't.

**Comment by spicyj** [comment]
The homepage hasn't changed in two years. :)

**Comment by gaearon** [comment]
Many examples in the new docs have CodePen links. I don't think examples in our repo are very valuable by themselves. Closing.
