### ISSUE TITLE
context not documented?

### ISSUE THREAD

**Issue by ffxsam** [facebook/react#4984]
https://blog.jscrambler.com/react-js-communication-between-components-with-contexts/

This is a game-changer! What an incredibly useful piece of functionality to have. It saves me adding extra complexity into my app (by using Flux/Redux/etc). I'm curious why it's not [documented here](https://facebook.github.io/react/docs/getting-started.html).

**Comment by gaearon** [comment]
It's not an officially supported feature. At least, not yet.
Please see https://github.com/facebook/react/issues/580.
