### ISSUE TITLE
Question : Following the guide from reactnative native modules for Android throws error 

### ISSUE THREAD

**Issue by gs-akhan** [facebook/react#4986]
Hi devs.
In process of creating Native modules for Android (Following what is mentioned in https://facebook.github.io/react-native/docs/native-modules-android.html#content) 

I get this error while app compilation .

..src/main/java/com/azharapp/AnExampleReactPackage.java:15:error: AnExampleReactPackage is not abstract and does not override abstract method createViewManagers(ReactApplicationContext) in ReactPackage

Thanks.

**Comment by edvinerikson** [comment]
This issue should probably be opened in the [RN repo](https://github.com/facebook/react-native/issues/new).

**Comment by gs-akhan** [comment]
Alright. Thanks. Closing it..
