### ISSUE TITLE
Provide `props` and `state` as arguments to render function

### ISSUE THREAD

**Issue by Guria** [facebook/react#4989]
Since we now have `Stateless function components` it would be convenient to transition to statefull ones with minimal changes:
```js
// before
var Aquarium = (props) => {
  var fish = getFish(props.species);
  return <Tank>{fish}</Tank>;
};
```
```js
// after
class Aquarium extends React.Component {
  render (props, state) {
    var fish = getFish(props.species);
    return <Tank>{fish}</Tank>;
  }
}
```

**Comment by gaearon** [comment]
Please see https://github.com/facebook/react/issues/1387

**Comment by zpao** [comment]
Yea, this is pretty well covered in previous discussions so I'm going to close out.
