### ISSUE TITLE
IE8-10: Warning: Component(...): React component classes must extend React.Component.

### ISSUE THREAD

**Issue by syranide** [facebook/react#4990]
Transpiled with babeljs. Not observed in modern browsers.

```js
class Example extends React.Component {
  render() {
    return null;
  }
}

ReactDOM.render(
  React.createElement(Example),
  document.body
);

// Warning: Component(...): React component classes must extend React.Component.
```

It's possible this is actually an issue with babeljs, I'm not really sure.

cc @spicyj

**Comment by spicyj** [comment]
I figured this out last week and didn't get a chance to test it. Glad to know it's not entirely in my head. We'll figure out a fix.

**Comment by spicyj** [comment]
Merging into #4990.

**Comment by jimfb** [comment]
@spicyj Merging into self?  Is there a different issue you intended to link?

**Comment by spicyj** [comment]
Thanks, I meant #4836.

**Comment by dtothefp** [comment]
@syranide @spicyj did this end up being an issue with Babel or React? I'm seeing the same warnings in IE9 using `0.14.0-rc1`

**Comment by spicyj** [comment]
It hasn't been fixed. #4836 will have updates when it is (which will happen before 0.14).

**Comment by dtothefp** [comment]
@spicyj will this currently have any negative effect on production code or is it only a warning in `NODE_ENV="development"`?

I'm using the syntax

```
import React, {Component} from 'react';

class Whatevsss extends Component {
```

not sure if it is effected by just doing
```
class Whatevsss extends React.Component {
```

**Comment by spicyj** [comment]
Both of those are fine. In prod mode we skip the check but your code will break in 0.15 if it's triggering the warning now.

**Comment by dtothefp** [comment]
@spicyj but the warning is due to issue resolved here https://github.com/facebook/react/issues/4836 correct? Any plan for release soon?
