### ISSUE TITLE
Should React.Children.map return a fragment?

### ISSUE THREAD

**Issue by polkovnikov-ph** [facebook/react#4991]
I've found [this issue](https://github.com/FormidableLabs/radium/issues/370) today in `radium` and would like to talk about it here, because it seems more like a `react` issue.

`Radium` relies on the fact that `props.children` is possible to transform into another object that can be passed into `props.children`. While this mostly works, because `react` thinks it's just a single opaque child most of the time, there're cases when someone would like to do something else with such result, i.e. get element by index or iterate over them. The problem is it's unlikely that `radium` authors can write a legit workaround for this issue. To `map` on `children` one has to replicate `react`'s approach to children _exactly_. I've found no internal methods in the implementation of `react` that allow doing something like that (`traverseAllChildrenImpl` fills `traverseContext.resultMap` which is essentially a map). So to tackle this issue authors would need to implement such method by hand and rely on the fact that `react` doesn't change its approach.

 - Shouldn't `map` return an array? This doesn't seem to break backward compatibility.
 - Shouldn't there be another `properMap` that returns an array?

**Comment by spicyj** [comment]
It does in 0.14 already. There's also a React.Children.toArray method.

**Comment by polkovnikov-ph** [comment]
@spicyj Shouldn't #2872 get closed then?

**Comment by spicyj** [comment]
Yes, thank you.
