### ISSUE TITLE
Find a more performant way to update `style` without building the whole element tree

### ISSUE THREAD

**Issue by Prinzhorn** [facebook/react#4992]
I'm doing scroll animations with react components. I found that having `scrollPosition` as a state and passing it down via props is terribly slow. `shouldComponentUpdate` won't help, because `scrollPosition` will change at 60fps. Instead I'm using refs to let the new scroll position trickle down via `this.refs[key].handleScrollChange(scrollPosition)`. This works very well, but has one big downside: it's not declarative anymore and I need to keep things in sync manually. Bummer!

I'm opening this issue to discuss ways which could drastically improve `style` animations in react and could also benefit modules such as react-motion. I basically know nothing about the internals of react, but from a api-user perspective I'd imagine the following: allow (per-component) to opt into a separation of react elements and the `style` property.

1. The new react element (maybe sth. like style-less or plain, we'll find a name) does not allow `style` and warns in debug mode
2. There's a new `Style` component which is similar to a component. It accepts props (and maybe has state?) and has a `shouldComponentUpdate`. It also requires a parent component. The `render` method returns a plain object (the style as key/value). When re-rendering the style is diffed with the previous and the changes are applied to the parent's component's node style.
3. The `Style` component can be updated independent from its parent (this gives the performance boost).
4. We can now move the fast-changing props like `scrollPosition` away from the actual component into the style-component and boom.

These are just some thoughts from the top of my end. Here's a very simple demo to make a point: https://github.com/Prinzhorn/react-setstate-callstack-of-death (http://prinzhorn.github.io/react-setstate-callstack-of-death/)

Here's a screenshot of what it looks like when I toggle between `setState` based animation and the refs based approach (with 100 animated items)

![screenshot from 2015-09-28 13 36 56](https://cloud.githubusercontent.com/assets/679144/10134807/ea742280-65e8-11e5-8e43-759997417f78.png)

I believe that separating the `style` property from the rest will result in similar performance gains while still being declarative (with a single source of truth) and allowing clean separation.

**Comment by spicyj** [comment]
React Native has a feature/library called Animated which can help with this problem:

https://facebook.github.io/react-native/docs/animations.html#animated

I know @vjeux plans to port it to the web too – not sure what the status of it is though.

**Comment by Prinzhorn** [comment]
This looks very interesting, as it basically bypassed setState as I suggested. But it's not what I'm looking for. It does time-based animations, I don't. `Animated.event` kind of looks what I need, but it operates per-component. I still have to pass down my state via props, which brings me back to the problem I have (creating unnecessary elements and diffing). What I want is a faster way to update the style in general on a more abstract level. I don't see how the Animated library could be used to improve libraries such as https://github.com/chenglou/react-motion or https://github.com/mzabriskie/react-draggable which currently use setState for updating style at 60fps. Maybe the underlying logic of the Animated library could be exposed allowing library authors to create all kinds of things on top of it.

https://facebook.github.io/react/blog/2014/03/28/the-road-to-1.0.html#animations explicitly lists this as something that needs to be explored. If this issue is not the right place then could you point me in the right direction where the discussion is happening? Thanks!

**Comment by jimfb** [comment]
@Prinzhorn Animation is still a relatively unsolved problem AFAIK.  The current strategy is to have a whole bunch of people iterate on their own ideas/solutions, and see what sticks.  Trying to combine efforts prematurely may cut off lines of research that would otherwise have been fruitful.  That's why you see several independent implementations rather than a single unified effort - it's a good thing.

If you have ideas on how to make better animations, we encourage you to pursue them.  If you are looking for a good place to discuss such things and share ideas/designs, I believe the most appropriate location is https://discuss.reactjs.org/

**Comment by Prinzhorn** [comment]
@jimfb thanks!
