### ISSUE TITLE
prefixed order css style get px appended

### ISSUE THREAD

**Issue by unphased** [facebook/react#4994]
As explained in [this doc](https://facebook.github.io/react/tips/style-props-value-px.html) only the `order` style is the one not having `px` appended. 

To have Safari 8 and IE10 work with `order` I need to specify `-webkit-order` and `-ms-order` both of which get `px` appended even if I coerce my integer to a string!

**Comment by zpao** [comment]
You need to use the correct prefixes. See https://facebook.github.io/react/tips/inline-styles.html

```
style={{
  order: 1,
  msOrder: 1,
  WebkitOrder: 1
}}
```
