### ISSUE TITLE
React doesn't follows semver

### ISSUE THREAD

**Issue by vasco3** [facebook/react#4998]
Almost every release introduces breaking changes. It would be easier to maintain if React bumped the first digit of the version every time there was a breaking change.

**Comment by salehe** [comment]
Technically, it is following SemVer. Major version zero is considered initial development and anything is allowed to change at any time.

**Comment by brigand** [comment]
@vasco3 for versions `>=0.1 <1` the minor version determines compatibility. The patch versions should be compatible.

This is why npm now uses the `^` (meaning 'compatible') by default. `^0.13.1` expands to `>=0.13.1 <0.14`.

**Comment by vasco3** [comment]
My comment is based on taking the NodeJS v4 release as an example given, where they state: 

> Node.js v4 also brings a plan for long-term support (LTS) and a regular release cycle. Release versioning now follows SemVer, so expect increments of both minor and patch version over the coming weeks as we fix bugs and add features. What we won't be doing within the v4.x branch is adding breaking changes.

https://nodejs.org/en/blog/release/v4.0.0/

React 0.14 separates the render from the rest of React. Isn't that a totally breaking change that should bump the major version?

**Comment by brigand** [comment]
[semver spec](http://semver.org/)

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So I wasn't completely correct, they could break things in patch versions and still be compliant, like **saiehe** said.

**Comment by jimfb** [comment]
@salehe is correct, we are below 1.0.0, so anything is allowed to change and we're still semver compliant.  I'm going to close out this bug, since there is no correctness issue with regards to our semver compliance.  Eventually we will release a version greater than 0.*, but not today.

**Comment by spicyj** [comment]
We don't make breaking changes in patch versions. Think of 0.13.3 more like 13.3.0. or 13.0.3.

**Comment by vasco3** [comment]
Well it's ok if that's the case. It's only a disadvantage against libraries like Elm http://package.elm-lang.org/#reliable-versioning
