### ISSUE TITLE
Strange optimization only in production mode

### ISSUE THREAD

**Issue by AlexGalays** [facebook/react#5005]
The 0.14-rc1 version brings a few performance optimisations that unfortunately behave differently when React is compiled in development or production mode. 

This is very confusing as code that works in one mode should still work in the other.

[Development mode Fiddle](https://jsfiddle.net/tLgq0x89/)
Logs
```
render Hello
render World
render Hello
render World
```

(That's the React 0.13.x behavior)

[Production mode Fiddle](https://jsfiddle.net/kw1we8vx/)
Logs only
```
render Hello
render World
render Hello
```

The "optimization" seems to trigger when a component reference didn't change.
This fiddle uses the production build but the child component is always a new instance and it works as expected : 

[Production mode with workaround](https://jsfiddle.net/2aL9drh8/)

**Comment by spicyj** [comment]
Yup, this is a bug. The prod mode behavior is correct.

In dev mode we don't bail out because the contexts differ because of secret validateDOMNesting tracking we do. Hmmmmmmmm.

**Comment by jimfb** [comment]
I feel like we knew about this "issue" and it was well documented at the time that the diff was merged.  We were using context for our own purposes and didn't have a good workaround at the time.  We decided to not worry about it, since renders should be deterministic it should have no influence on the rendered output.  It sucked that we had a different path in dev/prod, but that was life.  I think this is going to be fixed when we stop using context for our own hidden purposes, right?

**Comment by jimfb** [comment]
The "bug" is that your render function is not side-effect free (it prints something).

**Comment by spicyj** [comment]
@jimfb I didn't know about this issue. Did anyone make a comment to that effect on my diff? I don't see any notes on #3467.

**Comment by jimfb** [comment]
@spicyj https://github.com/facebook/react/pull/4344#issue-94421088

**Comment by sebmarkbage** [comment]
@AlexGalays How did this surface? I.e. how did you notice the change? Is there some kind of behavior change or is it just slower in development mode?

**Comment by AlexGalays** [comment]
@sebmarkbage 

We took the shortcut of having a few key top level components manually pull their data from flux stores in their render methods. It's not pure thus not ideal but it was much more convenient than the alternatives (we use a flux wrapper and a route wrapper component, it's not straightforward at all to flow all props through both without convoluted cloneWithProps calls)

I'm willing to review the way we did things, but it's good that the behaviour is now consistent in both env.
