### ISSUE TITLE
TestUtils.Simulate.keyDown does not trigger onChange event 

### ISSUE THREAD

**Issue by lovedota** [facebook/react#5006]
Hi guys.
I am testing React Component

``` js
class NumericInput extends React.Component {

    onChange(event) {
        console.log('Trigger On Change');
        this.props.onChange(event.target.value);
    }
    onKeyDown(event) {
        if (event.keyCode === 13) {
             return; //Do nothing
        }
    }
    render() {
        return (
            <Input
                {...this.props}
                type='text'
                value={this.state.value}
                onChange={this.onChange.bind(this)}
                onKeyDown={this.onKeyDown.bind(this)}
            />
        );
    }
}
```

``` js
beforeEach(() => {
   onChange = jasmine.createSpy('onChange');
   NumericInput = rewire('../NumericInput');
   renderedNumericInput = TestUtils.renderIntoDocument(
       <NumericInput onChange={onChange}/>
   );
   inputNode = 
 React.findDOMNode(TestUtils.findRenderedDOMComponentWithTag(renderedNumericInput, 'input'));
});

it ('Should call onChange when user does not press ENTER key', () => {
    TestUtils.Simulate.keyDown(inputNode, {keyCode: 46});
    expect(onChange.calls.count()).toEqual(1);
});

```

By Default in View, when i type, the *onKeyDown* is triggered and then *onChange*.
But in Unit Test it does not trigger *onChange*

**Comment by spicyj** [comment]
Yes, you should trigger each event you want manually. It only dispatches that event; it doesn't do anything fancier than that.

**Comment by lovedota** [comment]
@spicyj 
I think it will be nice if *React* supports the chain events in Browsers, Because I am writing a NumericComponent that in *keydown* i prevents some *keys* and then i will be nice if we can test if user type some keys that are prevented, onChange won't call. What do you think about it ?

**Comment by spicyj** [comment]
@lovedota You can consider using the native dispatchEvent if you are working in an actual browser. React won't get into the business of simulating how browsers work and how the different native events behave.
