### ISSUE TITLE
Still seeing original setState warning on mounted component (missing component name)

### ISSUE THREAD

**Issue by jcalfee** [facebook/react#5011]
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.`

https://github.com/facebook/react/issues/3878

I'm using `npm` to install: `"alt": "~0.17.1"`

This warning shows up when I call `setState` in one of my alt stores.  I'm really confused, I commented out any component listening to the store but still see the warning.  An improved error message could help.

**Comment by jcalfee** [comment]
This is used in the `AltContainer` ..

**Comment by zpao** [comment]
The fix for #3878 landed in 0.14.

This sounds like something you should report to Alt.

**Comment by jcalfee** [comment]
sorry
