### ISSUE TITLE
make ReactTransitionChildMapping or flattenChildren public API

### ISSUE THREAD

**Issue by jedwards1211** [facebook/react#5012]
I just created a PR for an issue with `ReactTransitionGroup`: https://github.com/jedwards1211/react/pull/1

I was able to use this with 0.13 for a long time by using my own fork of `ReactTransitionGroup`, which of course relies on
```
var ReactTransitionChildMapping = require("react/lib/ReactTransitionChildMapping"); 
```

But it looks like in 0.14 this kind of approach will no longer be possible, and `flattenChildren` is deeply intertwined with a lot of React internals.

If it were possible to use the same internals that `ReactTransitionGroup` does, people could create innovative new components.  For example, I have long wanted to create a variation that automatically staggers child entry, even if children are all added at the same time, for the classic staggered animation effect.  That would be quite useful, no?

**Comment by spicyj** [comment]
I think you can use React.Children.toArray now and key off of the resulting `.key` properties to build your own map.

**Comment by jedwards1211** [comment]
@spicyj Ah, okay, thanks!
