### ISSUE TITLE
SyntheticEvents can lose original property values, i.e. clientX & clientY

### ISSUE THREAD

**Issue by maysale01** [facebook/react#5036]
[Gist](https://gist.github.com/maysale01/324f8210497da74e3c4a)

I've also tried using `event.persist()` to no avail. I've seen this referenced multiple times for other properties being null, i.e. https://github.com/facebook/react/issues/2857 

It's also worth noting that the client[X|Y] properties on event.nativeEvent are also set to 0 and that the majority of these clicks return events with the correct values, it is only a small sample that abnormally return 0.

**Comment by spicyj** [comment]
.nativeEvent is just what the browser passes us so if those properties aren't right then it's not anything React's doing.

**Comment by maysale01** [comment]
Looks like an issue with BrowserSync.
