### ISSUE TITLE
ES6 onScroll never fires

### ISSUE THREAD

**Issue by ddaza** [facebook/react#5042]
I've been trying this out and I can't seem to get it working. 

```javascript
export default class MyPage extends React.Component {
    render () { 
       return <div className='page-wrapper'
          onWheel={(e)=>console.log('WHEEL!!',e)}
          onScroll={(e)=>console.log('SCROLL!!',e)}>
          {... my page content ...}
        </div>;
    }
}
```
the onWheel fires normally, but the onScroll is not firing. I dunno if I'm missing something or this is a bug.  

Thanks!

**Comment by spicyj** [comment]
If you're trying to catch scrolls of the whole page, you need to attach a scroll event handler to `window` by hand. See also #285.

**Comment by ddaza** [comment]
If you're talking about doing something like this?
```javascript
export default class MyPage extends React.Component {
    componentDidMount() {
       window.addEventListener('scroll', (e)=>console.log(e.target));
    }

    render () { 
       return <div className='page-wrapper' >
          {... my page content ...}
        </div>;
    }
}
```
I tried that and it didn't work. 

I also tried: 
```javascript
export default class MyPage extends React.Component {
    componentDidMount() {
       this.refs.wrapper.getDOMNode().addEventListener('scroll', (e)=>console.log(e.target));
    }

    render () { 
       return <div className='page-wrapper'  ref='wrapper'>
          {... my page content ...}
        </div>;
    }
}
```
It didn't work either. 
I have some parent components that use `MyPage`, I dunno if it makes a difference.

**Comment by spicyj** [comment]
I meant the former. If that doesn't work, it's hard for me to imagine how it could be a React problem.

**Comment by ddaza** [comment]
Is there a way for me to check what is swallowing the event?

**Comment by yaycmyk** [comment]
@ddaza Add a `true` to the end of that `window` listener to enable capture mode.

**Comment by admiral96** [comment]
Same problem with mine.

    constructor(props) {
        super(props);
        this.fireOnScroll = this.fireOnScroll.bind(this);
    }
    fireOnScroll() {
        console.log('Fire!');
    }

    componentDidMount() {
        const elem = ReactDOM.findDOMNode(this.refs.elementToFire);
        elem.addEventListener('scroll', this.fireOnScroll);
    }

    componentWillUnmount() {
        const elem = ReactDOM.findDOMNode(this.refs.elementToFire);
        elem.removeEventListener('scroll', this.fireOnScroll);
    }

    render() {
        return (
            <div className="div-with-overflow" ref="elementToFire">{this.props.children}</div>
        );
    }

**Comment by yaycmyk** [comment]
@admiral96 there are problems with the code you posted, but this a bug tracker not a Q&A - you'll find better help on StackOverflow or something similar.

**Comment by cht8687** [comment]
@admiral96  guys, you can check my implementation of onScroll in my module, it is working.
https://github.com/cht8687/react-listview-sticky-header/blob/master/src/ReactListView.js#L33-L35

**Comment by admiral96** [comment]
thanks

**Comment by sbenda** [comment]
Add a true to the end of that window listener to enable capture mode is working. Thanks @probablyup

**Comment by Kikobeats** [comment]
@sbenda can you paste your code with `true`? thanks!

**Comment by Mansourawy** [comment]
elem.addEventListener('scroll', this.fireOnScroll , true);

**Comment by Asher978** [comment]
@probablyup thank you for the pointer. I struggled with this in s SSR for 2 days to attach a scroll event and not be able to fire it.

All works now :)

**Comment by rajtrivedi88** [comment]
@cht8687 Thanks a lot.I was stuck for 2-3 hours on this issue.cheers

**Comment by rian-gustandi** [comment]
be live

**Comment by AsiamCn** [comment]
I found  onScroll is fired when  element which has **fixed height** and **enable scroll** ....

**Comment by ZAYDEK** [comment]
I ran into this myself. It’s not a React problem per se, but more understanding which element is responsible for scrolling. Like @sophiebits mentioned prior, if you want to listen to the window as supposed to a React component, you most likely need to manage an event listener yourself.

Here’s what I did, I hope it will help others:

```
// We need to listen to scroll events on the window so we
// manage an event listener ourselves.
React.useEffect(() => {
	const handleScroll = e => {
		// Do something here ...
	}
	document.addEventListener("scroll", handleScroll)
	return () => {
		// This cleans up the event handler when the component unmounts.
		document.removeEventListener("scroll", handleScroll)
	}
}, [])
```

**Comment by devsangwoo** [comment]
still best solution for 

`elem.addEventListener('scroll', this.fireOnScroll , true);`

**Comment by Sebastion-Vigil** [comment]
Does anyone out there in the Universe have a:
Working. Simple. Example. Of. React `onScroll`.
