### ISSUE TITLE
Invariant Violation: setEnabled(...): Cannot toggle event listening in a Worker thread.

### ISSUE THREAD

**Issue by stenrap** [facebook/react#5046]
I'm trying to create a unit test for a simple React view using TestUtils. I have the following:

React 0.10.0 (very old I know)
jsdom 6.5.1
mocha 2.3.3
Node.js 4.1.1

This is my view:

```javascript
var React = require('react');

var StudentNameView = React.createClass({
    
    render: function() {
        return React.DOM.div({
            id: 'name-container',
            children: [
                React.DOM.p({
                    children: 'Enter your name'
                }),
                React.DOM.input({
                    id: 'nameInput',
                    onChange: this.props.nameChanged
                }),
                React.DOM.button({
                    id: 'doneButton',
                    children: 'DONE'
                })
            ]
        })
    }
    
});

module.exports = StudentNameView;
```

And this is my current attempt at a unit test:

```javascript
var sinon = require('sinon');
var expect = require('chai').expect;
var jsdom = require('jsdom');
var React;
var TestUtils;
var view;

describe('The student name view', function() {
    
    before(function() {
        global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
        global.window = document.defaultView;
        global.navigator = {
            userAgent: 'node.js'
        };
        React = require('react/addons');
        TestUtils = React.addons.TestUtils;
        view = require('../student-name-view.js');
        this.nameChangedStub = sinon.stub();
        this.nameSubmittedStub = sinon.stub();
        this.renderedComponent = TestUtils.renderIntoDocument(
            view({
                nameChanged:   this.nameChangedStub,
                nameSubmitted: this.nameSubmittedStub
            })
        );
        this.nameInput = TestUtils.findRenderedDOMComponentWithTag(this.renderedComponent, 'input').getDOMNode();
    });
    
    describe('should notify the controller', function() {
        
        it('when the name field changes', function() {
            TestUtils.Simulate.change(this.nameInput);
            expect(this.nameChangedStub.called).to.be.true;
        });
        
    });
    
});
```

Unfortunately this unit test fails with an error:

> Error: Invariant Violation: setEnabled(...): Cannot toggle event listening in a Worker thread. This is likely a bug in the framework. Please report immediately.
>       at invariant (node_modules/react/lib/invariant.js:52:19)
>       at Object.merge.setEnabled (node_modules/react/lib/ReactEventEmitter.js:206:46)
>       at ReactReconcileTransaction.EVENT_SUPPRESSION.initialize (node_modules/react/lib/ReactReconcileTransaction.js:58:23)
>       at ReactReconcileTransaction.Mixin.initializeAll (node_modules/react/lib/Transaction.js:197:30)
>       at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:158:12)
>       at ReactComponent.Mixin.mountComponentIntoNode (node_modules/react/lib/ReactComponent.js:537:19)
>       at Object.<anonymous> (node_modules/react/lib/ReactMount.js:309:25)
>       at Object._renderNewRootComponent (node_modules/react/lib/ReactPerf.js:57:21)
>       at Object.ReactMount.renderComponent (node_modules/react/lib/ReactMount.js:359:32)
>       at Object.renderComponent (node_modules/react/lib/ReactPerf.js:57:21)
>       at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:57:18)
>       at Context.<anonymous> (test/student-name-view-test.js:23:44)

This is the only test I'm running—I'm trying to learn how to write unit tests for React components. Am I doing something wrong, or is this indeed a React bug as mentioned in the first error?

(Related to #1287)

**Comment by stenrap** [comment]
As an experiment, I upgraded to React 0.13.3 and made this change:

```javascript
this.renderedComponent = TestUtils.renderIntoDocument(
    React.createElement(view, {
        nameChanged:   this.nameChangedStub,
        nameSubmitted: this.nameSubmittedStub
    })
);
```

Unfortunately, this just fails with a different error:

> TypeError: Cannot read property '__reactAutoBindMap' of undefined
>       at Constructor (node_modules/react/lib/ReactClass.js:842:15)
>       at Context.<anonymous> (test/student-name-view-test.js:24:13)

**Comment by leplatrem** [comment]
As [stated by FakeRainBrigand on Stackoverflow](http://stackoverflow.com/a/26872245/141895), the variable ``ExecutionEvironment.canUseDOM`` is set to `true/false` during module code evaluation time. It is therefore never updated after that.

Since Babel executes this module for transpilation before even running the Mocha test suite. The variable remains false, even once `jsdom` was setup.

A quick workaround is indeed to «mutate» :) it to `true` again once jsdom is ready.

```js
import jsdom from "jsdom";

global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;

require('react/lib/ExecutionEnvironment').canUseDOM = true;
``` 

But a better fix would be to rely on a function instead of a global static variable for `canUseDOM`...

/cc @n1k0

**Comment by n1k0** [comment]
So after further investigation, we solved the problem by hooking into the mocha execution flow, using its `--require` command line option; we created a `setup.js` file instantiating the jsdom environment and exposing it to the nodejs one globally:

```js
// setup.js
var jsdom = require("jsdom");

global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;
global.navigator = global.window.navigator
```
That setup file is executed by mocha **before** babel compilers evaluate react module code. So basically we now run the mocha suite that way:

```
$ mocha --recursive --compilers js:babel/register --require ./test/setup.js test/
```

Related https://github.com/facebook/react/issues/3840

**Comment by stenrap** [comment]
Thanks @n1k0. Your suggestion indeed fixed the issue for me. I actually wanted to do something like this anyway so I wouldn't be setting up the DOM in every test.

**Comment by jimfb** [comment]
Ok, sounds like you guys figured it out.

For future reference, we try to keep github issues for tracking bugs in the React core.  Usage questions are better addressed on StackOverflow.

**Comment by stenrap** [comment]
Thanks, @jimfb, but this wasn't a usage question. I posted here because the error from React said:

> This is likely a bug in the framework. Please report immediately.

**Comment by spicyj** [comment]
Thanks @stenrap. We've since changed the message.

**Comment by timbur** [comment]
How do we do this for worker threads?

**Comment by timbur** [comment]
To elaborate, I get the error when I `Simulate.change(input)` on a checkbox and it originates from the `batchedUpdates`.

**Comment by spicyj** [comment]
@timbur Currently you need to expose document and window globally before requiring React. See the other comments.

**Comment by timbur** [comment]
@spicyj That's what I've done, I think?
```js
// setup.js
import { jsdom } from 'jsdom';

global.document = jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;
global.navigator = global.window.navigator;
```

And the script is loaded via the `npm test`'s command line argument:
```
NODE_ENV=test mocha --recursive --compilers js:babel-core/register --require ./test/setup.js
```

**Comment by timbur** [comment]
Actually hold on I think I know what it is now.

**Comment by timbur** [comment]
Yep, thanks for the nudge in the right direction @spicyj.  I was being dumb and had an import in the setup which imported another script which imported another script which imported React.
