### ISSUE TITLE
LinkedStateMixin: Default value for link state

### ISSUE THREAD

**Issue by lafka** [facebook/react#5051]
Using default values for `valueLink` can be set with the `defaultValue` property. But since `defaultValue` properties is only at initialization time you can't derive it dynamically (ie from a API call).

Would it be a possibility to have a second parameter for a default value added to `LinkedStateMixin.linkState`, that way the below code could be supported.

```jsx
// assume mixin is applied
class Foo extends React.Component {
  componentDidMount() {
    setTimeout(() => this.setState({defaultVal: 'async-default'}), 1)
  }

  render() {
    return (
     <input
        defaultValue="pre-async-default"
        valueLink={this.linkState('bar', this.state.defaultVal)}
        />
    )
  }
}
```

The actual patch should be quite trivial, however I'm not sure if this will create a new reactLink on every change to `defaultValue` regardless of the the linked value actually existing, someone more familiar with React can probably fill in on that point.

```diff
    *
    * @param {string} key state key to update. Note: you may want to use keyOf()
    * if you're using Google Closure Compiler advanced mode.
+   * @param {*} defaultValue default value to use in case this.state[key] is undefined
    * @return {ReactLink} ReactLink instance linking to the state.
    */
-  linkState: function(key) {
+  linkState: function(key, defaultValue) {
     return new ReactLink(
-      this.state[key],
+      undefined === this.state[key] ? this.state[key] : defaultValue,
       ReactStateSetters.createStateKeySetter(this, key)
     );
   }

```

I'm not sure of `LinkedStateMixin`'s future plans so this might not be interesting. I can definitely wrap my own class like `react-lensed-state`.

**Comment by jimfb** [comment]
ReactLink is getting deprecated as per https://github.com/facebook/react/issues/2302.  Assuming valuelink is something you find useful, I encourage you to publish a npm module or git repository that provides this functionality as a wrapper component so other people can use it. Since this is not something we plan on supporting in the core, I'm going to go ahead and close out the issue.
