### ISSUE TITLE
Incorrect react-dom package on bower?

### ISSUE THREAD

**Issue by rcchen** [facebook/react#5054]
I tried doing the following to pick up react-dom: `bower install react-dom#0.14.0-rc1 --save`

However, it said that the only version available was `0.1.0`

Poking around on Github yielded a repo called [react-dom](https://github.com/EtienneLem/react-dom) that appears to be linked to Bower. I'm guessing this isn't the right library; what's the dependency installation story going to look like with Bower?

**Comment by rcchen** [comment]
Never mind, just found that it shipped in the same `react/` package.

However, the documentation is misleading on the [0.14-rc1 announcement page](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html): 

> These builds are also available in the react and react-dom packages on bower.

**Comment by spicyj** [comment]
Thanks, we should fix that.
