### ISSUE TITLE
Refusing to install

### ISSUE THREAD

**Issue by ArmendGashi** [facebook/react#5060]
Is anyone today facing problem gettin react installed as dependency of itself

```
 ✘ ✝  ~/Dropbox/htdocs/react  npm install react
npm WARN package.json react@1.0.0 No description
npm WARN package.json react@1.0.0 No repository field.
npm WARN package.json react@1.0.0 No README data
npm WARN install Refusing to install react as a dependency of itself
 ✝  ~/Dropbox/htdocs/react 
```

Node --v ```v4.1.1``` npm --v ```2.14.4```

**Comment by zpao** [comment]
Are you in a directory with a package named `react` already? That's what that warning message seems to imply is happening.

**Comment by ArmendGashi** [comment]
Yes im on directory named react

**Comment by zpao** [comment]
You need to call your package something else (npm is looking at the `name` field in package.json). This is just how npm works, which is why it gives you that warning.
