### ISSUE TITLE
tbody children remove error

### ISSUE THREAD

**Issue by maximvl** [facebook/react#5068]
I've found obscure problem with re-rendering tbody with smaller amount of children, here is minimal example: https://jsfiddle.net/5xhxfb7g/

To reproduce:
1. Select 5 rows, press Apply - you will get table with 5 rows
2. Select lesser amount of rows, press Apply - you will get
```Invariant Violation: processUpdates(): Unable to find child 5 of element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID `.0.3.0`.```

The fix is to remove spaces in Table render (line 36), from
 ```<tbody> {rows} </tbody>```
to
```<tbody>{rows}</tbody> ```

I'm not sure if this is a real bug, but it woul'd be nice to have this mentioned in error message.

**Comment by syranide** [comment]
IIRC this will emit a warning in 0.14. TextNodes (spaces) are not allowed inside `<tbody>`.

**Comment by maximvl** [comment]
@syranide I see, should I close issue then?

**Comment by syranide** [comment]
cc @spicyj

**Comment by jimfb** [comment]
Yeah, closing this out because we now warn in 0.14.  Though... the warning could be better: https://github.com/facebook/react/issues/5071
