### ISSUE TITLE
Error during synthetic event dispatch

### ISSUE THREAD

**Issue by sudhirj** [facebook/react#5069]
<img width="462" alt="screen shot 2015-10-07 at 6 39 02 pm" src="https://cloud.githubusercontent.com/assets/21678/10338257/bf1efaf6-6d22-11e5-8482-3dff8c8f4baf.png">

**Comment by sudhirj** [comment]
This is the `Transaction` module, as far as I can make out.

**Comment by blainekasten** [comment]
This isn't a lot to go off of. What was your code doing when it the error occured? Can you make a repro in jsbin?

**Comment by sudhirj** [comment]
Yeah, I know it's really sketchy. It's seems to happen on a mouse event of some sort. Trying to figure out where, when and why.

**Comment by zpao** [comment]
If you could repro in a small case and/or supply some of the surrounding code, that would be helpful (and the react version, etc). This is the first I've seen of this error coming from code we control, where it shouldn't ever be the case.

**Comment by spicyj** [comment]
In any event, we removed this call to invariant in 0.14.
