### ISSUE TITLE
Order is not guaranteed in React.createFragment

### ISSUE THREAD

**Issue by idibidiart** [facebook/react#5070]
According to the React docs [1] there seems to be an assumption that maps in Javascript guarantee the order of the keys which AFAIK is not true. See this Stackoverflow question [2]

```javascript
if (this.props.swapped) {
  children = React.addons.createFragment({
    right: this.props.rightChildren,
    left: this.props.leftChildren
  });
} else {
  children = React.addons.createFragment({
    left: this.props.leftChildren,
    right: this.props.rightChildren
  });
}
```

[1] https://facebook.github.io/react/docs/create-fragment.html
[2] http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

Could this lead to cross-browser issues with CreateFragment?

**Comment by syranide** [comment]
React itself relies on this behavior and all known browsers behave this way, this will eventually be phased out when `Map`-support is better, but there's no present danger here. Stay away from numeric indices and it's safe.

**Comment by idibidiart** [comment]
Ok, I see. Thanks. Closing.
