### ISSUE TITLE
link to ReactDOM on CDN 404s

### ISSUE THREAD

**Issue by benjtinsley** [facebook/react#5079]
the version of reactDOM in the tutorial is `https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0/react-dom.js`. when used with the tutorial, console outputs error `ReferenceError: ReactDOM is not defined`, when I follow the link, it 404s.

![screen shot 2015-10-07 at 5 34 46 pm](https://cloud.githubusercontent.com/assets/3211091/10354079/bc7925d2-6d19-11e5-863d-6cb025ff64aa.png)

![screen shot 2015-10-07 at 5 35 20 pm](https://cloud.githubusercontent.com/assets/3211091/10354085/d1eb75fa-6d19-11e5-872f-5a63f2ae95bd.png)

**Comment by jimfb** [comment]
@spicyj @zpao

**Comment by spicyj** [comment]
Yeah, they seem to be lagging a bit. Try https://cdn.jsdelivr.net/react/0.14.0/react-dom.js.

**Comment by zpao** [comment]
jsdelivr updated very quickly… we might want to switch our docs over to using that in the future. cdnjs says "up to 30 hours" which is a long time for our tutorial to be in a semi-broken state.

**Comment by spicyj** [comment]
Yeah… or set up builds.reactjs.org – I think @terinjokes offered to help?

**Comment by terinjokes** [comment]
Once CDNJS adds something the repo it should be live on the site within 30 minutes (though, of course, would be great to get this lowered). The automated bot should be adding things to the repo much quicker than 30 hours.

As for builds.reactjs.org, more than happy to help where I can. Fill free to tag me in an issue or shoot me an email: terin@cloudflare.com.

**Comment by zpao** [comment]
From the cdnjs readme (emphasis theirs):

> cdnjs automatically updates libraries that are known to be hosted on `npm` or git repo, e.g., Lodash. npm auto-update relies on each release and git auto-update relies on the [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) in git repo. This auto-update script runs every hour, but the update result **won't be committed until one of our maintainers audit the updates**, because many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so **it'll be reasonable to delay for at most 30 hours**, if you think there is a lib didn't been updated, please wait at least 30 hours for the process to audit it.

The commit adding React (https://github.com/cdnjs/cdnjs/commit/9bfeaddfe22aacd83f66384848e0f2bcc1c61cc5) went in at 18:18 PDT, 8 hours after we shipped at 10:21.(https://github.com/reactjs/react-bower/commit/f4e97c67e6adf209da8aff329a8f7eb1239be3f7). jsdelivr went in at 10:35 (https://github.com/jsdelivr/jsdelivr/commit/a5259fbdfc52967170c13b1d8130d0046980046a). Perhaps we just got a bad break in the cdnjs update cycle and a good break in jsdelivr. I have no connection with any of these and will ultimately just do what's best for us (which is probably just to have our own `builds.reactjs.org`)

**Comment by terinjokes** [comment]
@zpao i'll follow up with the CDNJS guys and try to piece together if something went wrong.

**Comment by PeterDaveHello** [comment]
cdnjs maintainer here, I'll take a look at it.
