### ISSUE TITLE
Feature request: Provide isOptional on PropTypes

### ISSUE THREAD

**Issue by jimbolla** [facebook/react#5080]
It would be useful to have an `isOptional` member to negate `isRequired`.

use case:

    const ThingList = ({things}) => (
        <ul>
            {things.map(thing => <li>{thing.name}</li>)}
        </ul>
    );

    ThingList.propTypes = {
        things: PropTypes.arrayOf(PropTypes.shape({name:PropTypes.string.isRequired})).isRequired
    };

    const Whatever = ({things, title}) => (
        <div>
            <h1>{title}</h1>

            {things && things.length
                ? <ThingList things={things} />
                : null}
        </div>
    );

    Whatever.propTypes = {
        things: ThingList.propTypes.things.isOptional,
        title: PropTypes.node
    };

The `things` property is required for `ThingList`, but `Whatever` conditionally renders `things` if they were passed to it. `Whatever` reuses `ThingList`'s propType but makes it optional. This would alleviate the need to make a separate `thingShape` variable for everything before the `.isRequired` to be referenced by `ThingList` and `Whatever`.

**Comment by spicyj** [comment]
Hack: `PropTypes.oneOfType([ThingList.propTypes.things, PropTypes.oneOf([])])`. You could also make your own wrapper that does this same thing.

propTypes are mostly in a sort of maintenance mode and we're not really planning to add more to them right now.
