### ISSUE TITLE
Is rendering a single node at multiple places safe?

### ISSUE THREAD

**Issue by jjvattamattom** [facebook/react#5087]
I want to place a widget multiple places in the DOM. 

```
a = getFancyWidget();
return <div>
        <span>{a}</span>
        {/* main content*/}
        <span>{a}</span>
</div>
```

I have not seen any code that does it. So I wonder if its safe, that it does not mess with react internals. It works with a minimal example.

I want to make a stacked tables implementation like https://johnpolacek.github.io/stacktable.js . For a 3-row table, each `tr` is placed twice, a `td` is placed 4 times. 

In responsive mode in a stacked table, each row is displayed as a 2-column key-value table. It does this by turning each table into a table+stacked table set combo and then using a media query to show either the table or stacked table set.

**Comment by jimfb** [comment]
Yes, it is completely safe and legal.

For future reference: usage questions are better addressed on StackOverflow.  We try to keep github issues for tracking bugs in the React core.
