### ISSUE TITLE
componentDidUpdate infinite loop, better error message

### ISSUE THREAD

**Issue by arasmussen** [facebook/react#5097]
I caused an infinite loop by calling this.setState in componentDidUpdate. The warning I received was "Maximum call stack size exceeded" and the stack only showed React code, never any of my product code. As a result this was super hard and time consuming to track down.

Any thoughts on detecting this bad behavior somehow and giving a nicer error message?

**Comment by zpao** [comment]
I think the only thing we could do is warn if you call setState in componentDidUpdate (which I think we know about). But there are valid use cases when done with care and it would be pretty annoying for those.

**Comment by arasmussen** [comment]
Aha!

The following code triggers an infinite loop because componentDidUpdate is calling this.setState and even though the state isn't changing whatsoever another componentDidUpdate is being triggered.

```javascript
var Foo = React.createClass({
  getInitialState: function() {
    return {
      bar: null,
    };
  },
  componentDidUpdate: function() {
    this.setState({bar: this.state.bar});
  },
  render: function() {
    return <div />;
  },
});
```

After chatting with @zpao it sounds like we still need to leave the behavior this way but is there any warning we can create specifically when this.setState is being called in componentDidUpdate and state doesn't actually change? (Thus triggering hard to debug infinite loop...)

**Comment by spicyj** [comment]
We could warn if you do more than a few nested updates. Even if it's not an infinite loop it's probably slow and should be avoided.

**Comment by claudiopro** [comment]
I stumbled upon the same issue: https://github.com/claudiopro/2048-react/issues/1. I vote for the warning, even if just in development mode.

**Comment by gaearon** [comment]
We now throw with a meaningful message if you do > 1000 nested updates.
