### ISSUE TITLE
Starter Kit for creating React components

### ISSUE THREAD

**Issue by cosminnicula** [facebook/react#5108]
It could be helpful to have a sample project that would centralize in a single place all React's best practices to build a component (something simple, like for example a custom input field), both stateless and stateful. Also it could be an excellent starting point for providing migration steps with actual code rather than bullets in a document, like it happened with 0.14 release.

Additionally, this could evolve into something like integration with some Node.js tooling (linting with ESLint, transpiling with Babel, package management and bundling with Webpack / JSPM), a small testing infrastructure etc. and why not publishing it as a Yeoman generator.

Disclaimer: this is not an issue with React itself, but rather a proposal for better supporting React development.

**Comment by spicyj** [comment]
I think we want to provide most or all of those things and will keep them in mind as we update the docs but this issue isn't super actionable so I'm going to close it. Thanks for the suggestion!
