### ISSUE TITLE
Downloads page does not link to react-dom-0.14.0.js

### ISSUE THREAD

**Issue by TomiBelan** [facebook/react#5115]
If you use script tags directly (not npm), you have to use both react.js and react-dom.js. The [tutorial](https://facebook.github.io/react/docs/tutorial.html) shows this, and the [blog post](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html) has both download links, but the main [downloads page](https://facebook.github.io/react/downloads.html) does not.

**Comment by zpao** [comment]
Good catch. If anybody wants to grab it, let us know. Otherwise we'll get to it very soon.
