### ISSUE TITLE
Update README for 0.14

### ISSUE THREAD

**Issue by TomiBelan** [facebook/react#5117]
Some references to 0.13 remain in the README: https://github.com/facebook/react#installation
Thanks! (And kudos for fixing #5115 so fast.)

**Comment by zpao** [comment]
Ah! That's what the lingering "I'm forgetting something" feeling was. Thanks for the reminder. I pushed be90351add34c2a47328a2b7a0786c5c00d991c8 to update (and will update the `0.14-stable` branch in a moment)
