### ISSUE TITLE
[v0.14] 'this' is now some object, even though I'm using class property initializers

### ISSUE THREAD

**Issue by mrtnbroder** [facebook/react#5118]
I've used class property initializers to get around the annoying `this.whateverHandler = ::this.whateverHandler` within the `constructor` method.

However, with React v0.14, it looks like, `this` is now the props object.

```javascript
export default class Test extends Component {

  constructor(props, context) {
    super(props, context)
  }

  whateverHandler = (e) => {
    // 'this' used to be the instance, but is now some object that looks like:
    // {children: Object, someProp: true }
  }

  render() {
    return <button someProp={true} onClick={this.whateverHandler}>Button</button>
  }

}
```

So now I actually have to
1. either bind it within the `onClick` handler or
2. bind it at the constructor level,
but I feel like this is actually wrong.

**Comment by zpao** [comment]
This works fine for me if I run your code through the Babel repl (after fixing the arrow function in you property initializer and extending React.Component)

**Comment by mrtnbroder** [comment]
Really? Let's say I have to access `this.context`, is it available for you? My current version of babel:

```
"babel": "^5.8.23",
"babel-core": "^5.8.25",
"babel-loader": "^5.3.2",
"babel-runtime": "^5.8.25",
```

**Comment by zpao** [comment]
Original code + transformed: http://bit.ly/1NwaP7S
Then run: https://jsfiddle.net/hz9dr8qw/1/

**Comment by brigand** [comment]
@mrtnbroder this happens when you don't bind it.

```js
class Foo {
  f(){}
  render(){ return <Bar onF={this.f} }
}

class Bar {
  render(){
    this.props.onF();
    // which is the same as:
    this.props.onF.call(this.props);
  }
}
```

Not sure how that could happen in the code you posted. You sure it's not running old code?

**Comment by mrtnbroder** [comment]
Yeah not sure what happened, I'll dig further into it and let you know. Maybe it was just some strange transpiling issue.

**Comment by jimfb** [comment]
Ok, at this point, it's sounding like it's not a bug in React, so I'm going to close out this bug.  I'm curious to hear what actually went wrong here.  If it turns out to be React's fault, we can re-open the issue.
