### ISSUE TITLE
<noscript> causes css issues

### ISSUE THREAD

**Issue by yagudaev** [facebook/react#5119]
I just realized that react replaces empty elements with <noscript>, this is pretty unexpected and only discovered once I saw an interesting production bug.

Consider:

```html
   <Field visible={record.title_visible}>
      {record.title}
   </Field>

   <Field visible={record.author_visible}>
      {record.author}
   </Field>

   <Field visible={record.description_visible}>
      {record.description}
   </Field>
```

```js
var Field = React.createClass({
  render: function() {
    if (this.props.visible) {
      return (
          <div className="field">
             {this.props.children}
          </div>
      );
    } else {
      return false;
    }  
  }
});
```

```css
.field + .field {
  margin-top: 10px;
}
```

If the `author` is set to not be visible we would expect the two fields `title` and `description` to still be separated by a margin of 10px, but this is not the case. This is because the generated markup will look something like this:

```html
<div class="field></div>
<noscript />
<div class="field"></div>
```

This is very unexpected. I know the guide said there is plans on having nothing there at all, but no further status has been given in the last 3 releases. I just wanted to bring it to your attention again.

**Comment by syranide** [comment]
@yagudaev Not to say it isn't valid, but I really wouldn't recommend having components that themselves determine whether or not they render like you do above. It's much better to have the parent component handle that directly.

**Comment by yagudaev** [comment]
@syranide agreed. I just have upwards of 20 fields in the parent component so I was hoping to stay away from:

```js
{
  if(record.title_visible) {
     <Field>
        {record.title}
     </Field>
  }
}
```

Yet maybe there is another more elegant solution.

**Comment by syranide** [comment]
@yagudaev If repetition/verbosity is the problem you see I would recommend the following as a general solution:

```jsx
{this.renderFieldIf(record.title_visible, record.title)}
```

or perhaps something *like* the following if you want to go all out:

```jsx
{this.renderFields(record, [
  'title', 'author', ...
])}
```

There are many variations with different trade-offs you can do depending on your needs.

**Comment by yagudaev** [comment]
@syranide that is a great idea thanks, never considered it. Interestingly it more involved than the example I showed, some of the fields have lists of information in them and are displayed with a method for example `renderCategories(record.categories)`. But I can just have a switch statement in `renderFields` to select the right way to display things.

For now my workaround is with CSS:

```scss
.field {
    margin-top: 10px;

    &:first-of-type {
      margin-top: 0;
    }
  }
```

**Comment by spicyj** [comment]
Or this:

```
{record.title_visible && <Field>{record.title}</Field>}
```

but we know that this is a problem and will fix it eventually, though it probably will come with #2127, no sooner.
