### ISSUE TITLE
Page messed up: facebook.github.io/react/html-jsx.html

### ISSUE THREAD

**Issue by serprime** [facebook/react#5121]
Did not know where to post this best.

Since some weeks, the layout looks broken on https://facebook.github.io/react/html-jsx.html

Google Chrome 43, Linux

Screenshot:
![selection_003](https://cloud.githubusercontent.com/assets/417542/10411670/7a7529c8-6f6d-11e5-9c97-ef8c2d1b3755.png)

**Comment by jimfb** [comment]
Not Linux specific; broken in all browsers / operating systems.  This is probably a good first bug if someone wants to submit a pull request.

**Comment by bhamodi** [comment]
Closed in #5123.
