### ISSUE TITLE
ReactDOM.render vs React.render callback

### ISSUE THREAD

**Issue by aft-luke** [facebook/react#5122]
I ran into a strange problem when transitioning to React `0.14.0`.

I use a promisified API internally in my application, and for various reasons I need a handle to the mounted instance of an element. No big deal, this is how I get a handle to that instance after react has finished its non-deterministic render:
```
// some renderer service
return new Promise(function (resolve, reject) {
    React.render(reactElement, node, function () {
        resolve(this)
    })
})

// someone using the renderer service
return renderer(element, someNode)
    .then(function (mountedElement) {
        ...
    })
```

When I update to `0.14.0`, I should be able to just swap out implementations without a thought, right?

```
return new Promise(function (resolve, reject) {
    ReactDOM.render(reactElement, node, function () {
        resolve(this)
    })
})
```

Well, apparently not :(.

I'm getting an error message correlating to [this help wiki](https://gist.github.com/jimfb/4faa6cbfb1ef476bd105)... 

```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

I have scraped through the app looking for some "invalid usage of refs", but there aren't any. I also can't see a case where I have more than one React on the page (unless there's some shenanigans caused by including `react-dom/server` in a browser, but I have removed it and checked against that case too: same problem)?

Loading React (browserify):
```
    let React = require('react')
    let ReactDOM = require('react-dom')
    let Server = require('react-dom/server')
```

package.json
```
  "dependencies": {
    "react": "0.14.0",
    "react-dom": "0.14.0"
  }
```

`npm ls | grep react`
```
│ │ ├── babel-plugin-react-constant-elements@1.0.3
│ │ ├── babel-plugin-react-display-name@1.0.3
│ │ ├── babel-plugin-react-constant-elements@1.0.3
│ │ ├── babel-plugin-react-display-name@1.0.3
├─┬ react@0.14.0
├─┬ react-dom@0.14.0
│ └─┬ react@0.14.0
```

**Comment by FutureKode** [comment]
Hello,

I had the same problem and spent the last 3 hours trying to fix it! Anyway, for me it worked to upgrade my npm to the latest version... after that the problem disappeared! Hope this helps

**Comment by gaearon** [comment]
```
├─┬ react@0.14.0
├─┬ react-dom@0.14.0
│ └─┬ react@0.14.0
```

Doesn't that look like a duplicate React?

**Comment by aft-luke** [comment]
@gaearon unless I'm mistaken, `npm ls` lists all packages and their dependencies... which means that react-dom just depends on react, not that it pulls in its own version.

**Comment by aft-luke** [comment]
I suppose not? I blew away `node_modules` and did a fresh install, and now I'm getting:

```
│ │ ├── babel-plugin-react-constant-elements@1.0.3
│ │ ├── babel-plugin-react-display-name@1.0.3
├─┬ react@0.14.0
├── react-dom@0.14.0
```

**Comment by aft-luke** [comment]
It looks like this issue was nothing but a consequence of more than 1 React on the page - for those interested make sure your third-party libraries have updated their `peerDependency` for React to `0.14.0`.
