### ISSUE TITLE
findRenderedDOMComponentWithTag can't search html element, 0.14.0

### ISSUE THREAD

**Issue by localnerve** [facebook/react#5128]
Hello!
I'm trying to test a React component that renders an \<html\> element.

It is the only component I cannot test - findRenderedDOMComponentWithTag cannot locate tags that do exist:
  "Unable to find element. This probably means the DOM was unexpectedly mutated..."

Repeatable. Demo: https://jsbin.com/semonu/edit?html,js,console

**Comment by brigand** [comment]
From the 0.14 blog post:

> Add-Ons: Due to the DOM node refs change mentioned above, TestUtils.findAllInRenderedTree and related helpers are no longer able to take a DOM component, only a custom component.

**Comment by localnerve** [comment]
Thanks. Two related follow ups:

1. In the [jsbin](https://jsbin.com/semonu/edit?html,js,console), how is the first component OK and the second one not? (from the jsbin javascript, the one that works is commented "worky"). They seem pretty similar to me. What makes a "custom component" must be a very subtle difference that is worth detailing.

2. Can you please point me to a doc that de-constructs the term "custom component" further into React terms? 
React Docs explains [composite components](https://facebook.github.io/react/docs/test-utils.html#iscompositecomponentwithtype) quite succinctly for isCompositeComponentWithType.
> ... Returns true if instance is a composite component (created with React.createClass())

It would be great if the types of React components were explained in the [Glossary](https://facebook.github.io/react/docs/glossary.html).

**Comment by spicyj** [comment]
@brigand I think that's actually unrelated in this instance.

@localnerve I meant "custom component" to be synonymous with "composite component". We don't actually support rendering `html` except with server rendering, and renderIntoDocument simply renders the component into a div. Sorry for the trouble…

**Comment by localnerve** [comment]
OK. I used to be able to test my server components with React TestUtils 0.13.x, thus the issue.
Any forward guidance on testing html components?

**Comment by spicyj** [comment]
Shallow rendering should work, or you could try to render to string and then create a new document with that HTML – the exact details of that will depend on how you're running your tests.

**Comment by localnerve** [comment]
Thanks for the clarification and thoughts. An unexpected breaking change, but workable.

**Comment by spicyj** [comment]
Oh, I missed that this was a regression. I'll look into what this is to see if it's fixable for a point release.

**Comment by localnerve** [comment]
NOTE: renderIntoDocument appears to work with html components (AFAICT, browsing the result with an inspector - all my stuff is there), its only when you go to search that you hit an issue, manifests as "Unable to find element. This probably means the DOM was unexpectedly mutated..."

**Comment by vladimir-rovensky** [comment]
This change actually broke a lot of our tests, is there some way ATM to locate a custom component within a DOM component? In previous versions it was possible with TestUtils.findAllInRenderedTree - the test would e.g. locate a div with a particular class and within that div a specific custom component. Is that no longer possible? How should this be done in 0.14?

Any guidance would be appreciated.

**Comment by spicyj** [comment]
Can you paste an example of what your tests look like?

**Comment by vladimir-rovensky** [comment]
Ok, here's an example of one of our tests that is now broken (simplified):

```javascript
it('has a button in the Details section', function(){
    var model = {some: 'data model'};
    var screen = React.render(<EditScreen model={model} />, container);
    var element = TU.findRenderedDOMComponentWithClass(screen, 'edit-screen-details'); 
    TU.findRenderedComponentWithType(element, Button); //This fails now
});
```

The above test should take the tested component (EditScreen), within that look for an element with the class 'edit-screen-details' and within that, look for an instance of the Button component. This worked quite nicely for us and it was enabled by the old findAllInRenderedTree (as I understand it the other test methods use findAllInRenderedTree internally).

How can we do this kinda thing now?

**Comment by vladimir-rovensky** [comment]
I should point out one more thing - we're not using TestUtils directly, we have our own test helpers that use them internally.

In particular, we wrote our own jQuery style helper method that we use to locate component instances / DOM nodes in tests, that looks kinda like this:

```javascript
   var buttons = helpers.find(screen, '.edit-screen-details', Button);
```

This will give us all instances of Button component within something with class edit-screen-details within the screen component instance.
It does so by calling TestUtils.findAllInRenderedTree repeatedly for all the selectors, I hope you can imagine how. This doesn't work now, since you cannot call findAllInRenderedTree with a DOM node.

If you could advise how to implement this API in 0.14, it would fix all of our tests.

**Comment by spicyj** [comment]
Unfortunately I don't think our public API supports that right now. :\

**Comment by localnerve** [comment]
@spicyj , Can you please explicitly relate status on this thread to the original escape shown in 
https://jsbin.com/semonu/edit?html,js,console

This thread has other ideas, and it's not clear where this stands as it relates to the original problem.

The jsbin demonstrates a departure from previous versions. The jsbin shows that, as of 0.14, TestUtils can no longer can test the entire set of React supported output elements. Specifically, shows `html` elements not supported, however they are still rendered/supported by React.

Thanks in advance.

**Comment by spicyj** [comment]
@localnerve The issue here is nothing with findRenderedDOMComponentWithTag, but that renderIntoDocument creates a div and you can't render an HTML tag inside a div. Not sure why there isn't a HTML nesting warning for that at the moment. You can do something like this which creates a new iframe with the given HTML:

https://jsbin.com/qeyifedave/1/edit?html,js,console

Hope that helps.
