### ISSUE TITLE
React ref callback sometimes gives null

### ISSUE THREAD

**Issue by brigand** [facebook/react#5131]
Is this expected behavior? Logs `true`, `false`, `true`. The last two are logged ~3ms apart, and between componentWillUpdate and componentDidUpdate.

```js
class App extends React.Component {
  constructor(){
    super();
    this.state = {};
    setTimeout(() => this.setState({}), 1000);
  }
  
  render(){
    return (
      <div ref={(x) => console.log(x !== null)} />
    );
  }
}
```

Same behavior on 0.13.3, 0.14.0, and master.

**Comment by syranide** [comment]
It's a bit quirky but intended behavior, you're effectively providing a new ref-callback every time it renders. So to safely dispose of the old ref-callback React calls it with `null` and then the new ref-callback will be called with the instance. Store and re-use your ref-callback and this goes away.

**Comment by spicyj** [comment]
The docs say this too.

**Comment by orhanberamus** [comment]
@syranide  can you tell how can i store the ref
