### ISSUE TITLE
react@0.14.0 don't work defaultValue for select element

### ISSUE THREAD

**Issue by lafin** [facebook/react#5133]
I see regression, ie before code working fine
```react
<select className="form-control" onChange={this.onChangeCity.bind(this)} defaultValue={state.city}>
  {state.cities.map((city, key) => {
    return <option key={`city-id-${key}`}>{city}</option>;
  })}
</select>
```
what I do wrong?
I watched source code react.js and I think problem [here](https://github.com/facebook/react/blob/0.14-stable/src/renderers/dom/client/wrappers/ReactDOMSelect.js#L184)

**Comment by edvinerikson** [comment]
You need to add the `value` attribute to the `option` elements.
https://jsfiddle.net/69z2wepo/17871/

**Comment by lafin** [comment]
Thanks, working :)

**Comment by spicyj** [comment]
This regression was unintentional.
