### ISSUE TITLE
How to get a standalone build (.js file) of ReactDOMServer

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#5134]
I'm doing server-side rendering in ReactJS.NET, and am seeing this warning after upgrading the library to React 0.14:
```
React.renderToString is deprecated. Please use ReactDOMServer.renderToString from require('react-dom/server') instead
```

ReactJS.NET uses V8 directly (ie. it does not use Node.js) so I can't simply `require` an npm module from within the library. I imagine node-rails and react-php-v8js are in the same situation.

How do I build a .js file containing ReactDOMServer? Should I just have my own Webpack/Browserify bundle?

**Comment by spicyj** [comment]
> Should I just have my own Webpack/Browserify bundle?

I think that's best.
