### ISSUE TITLE
Select value outputs selected="" on selected option.

### ISSUE THREAD

**Issue by kirisu** [facebook/react#5136]
Rendering a select list with a selected item in this manner:
```
render: function() {
  return (
    <select value="foo">
      <option value="">All</option>
      <option value="foo">Foo</option>
    </select>
  )
}
```

will render HTML that looks like this:
```
 <select>
  <option value="">All</option>
  <option selected="" value="foo">Foo</option>
</select>
```

Is there any reason for the `selected=""` part? Should the output not just be:
```
 <select>
  <option value="">All</option>
  <option selected value="foo">Foo</option>
</select>
```

This is more of a question rather than anything else. We use capybara to test our app, and after upgrading to React 0.14, when we try and get the value of a select field it is returning "" and breaking a large amount of our tests. We've traced this down the difference in the html, with React 0.13 outputting `selected` and 0.14 outputting `selected=""`.

**Comment by syranide** [comment]
React 0.14 generates XML-compatible markup #2842

**Comment by ChennyBaBy** [comment]
In the [release note](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#notable-enhancements) it says:

`When possible, React DOM now generates XHTML-compatible markup.`

**Comment by BookOfGreg** [comment]
Actually the markup generated is invalid without the value of that attribute being `selected`.
It must be `<option selected="selected">`
http://xhtml.com/en/xhtml/reference/option/
http://www.w3schools.com/tags/att_option_selected.asp

**Comment by spicyj** [comment]
Whether or not it's technically valid, this works in all browsers that I know of and (IIRC) gets around some other issues that crop up when using the attribute name as value.
