### ISSUE TITLE
React.Children.map doesn't traverse as stated in the docs

### ISSUE THREAD

**Issue by jnsandrew** [facebook/react#5148]
According to the docs:

`If children is a nested object or array it will be traversed`
https://facebook.github.io/react/docs/top-level-api.html

However when I use this function on, for example something like:

```html
<form>
  <div>
    <span>Username</span>
    <input type="text" />
  </div>
  
  <input type="password" />
</form>
```

React.children.map(this.props.children ...) finds `div` and `input type="password"` but not the elements inside `div`.

Have I misunderstood the docs? or is this a bug?

**Comment by zpao** [comment]
That's just a case not well explained in the docs. We don't traverse into nested ReactElements, only into nested arrays and (previously) object literals.

```js
var nested = [
  [<span />, <a />]
  <div />
];
<form>
  <div>
    <span>Username</span>
    <input type="text" />
  </div>

  <input type="password" />
  {nested}
</form>
```

That's what's meant by nested children. We would traverse into `nested` and pull out the span, anchor, and div. We won't traverse into your literal div's children as those aren't children of the form but of the div.
