### ISSUE TITLE
Can i use react-dom with react@0.13?

### ISSUE THREAD

**Issue by azazdeaz** [facebook/react#5155]
Hi! I try to upgrade some packages to support react 0.14 and react-dom. But if my understanding is right if i want to support 0.14 without warnings i cant support 0.13 anymore. (without asking people to do some workaround like aliasing ```'react-dom'``` to ```'react'``` in the webpack config)

Is this right or i missing something?

**Comment by gaearon** [comment]
>But if my understanding is right if i want to support 0.14 without warnings i cant support 0.13 anymore. (without asking people to do some workaround like aliasing 'react-dom' to 'react' in the webpack config)

I think this is correct.

**Comment by jimfb** [comment]
I think you can say something like `if(typeof ReactDOM === 'undefined') ReactDOM = React`.  Then you can use ReactDOM, which will sometimes be backed by the old version, right?

**Comment by azazdeaz** [comment]
@jimfb Thanks, but i don't really understand this solution :( . Where the ReactDOM will get a value if the react version is >=0.14?

**Comment by azazdeaz** [comment]
Can i do something like this?
```javascript
//react-dom-or-just-react.js
var react = require('react')
if (isVersion14orGreater(react.version)) {
  module.exports = require('react-dom')
}
else {
  module.exports = react
}
```

**Comment by jimfb** [comment]
Yes, my code was for the browser distribution.  For node distribution, something like checking the React version (and then assigning, as you do above) is roughly equivalent.

**Comment by gaearon** [comment]
I'm not sure this will work. Since the condition can't be resolved statically, the bundlers like Webpack are likely to complain (at least warn) about `react-dom` not being installed even if the consumer is using 0.13.

The cleanest way out of this mess is just to release a major version requiring 0.14.

**Comment by azazdeaz** [comment]
Yes, you're right :(

Thank for your help @gaearon @jimfb !
