### ISSUE TITLE
Bower distribution does not include non-deprecated renderToString

### ISSUE THREAD

**Issue by ghempton** [facebook/react#5159]
We have some corner cases within our client-side application which requires `React.renderToString` functionality. In 0.14, this has been deprecated in favor of `ReactDOMServer.renderToString`. Unfortunately, the bower distribution does not include a way to reference `ReactDOMServer`.

**Comment by jimfb** [comment]
@zpao I ran into this also.  Having a browser version of `renderToString` is super useful for debugging purposes if nothing else.  I tend to think we should just put it on ReactDOM; does it really add enough bloat that we feel the need to take it off ReactDOM?

**Comment by zpao** [comment]
I have mixed feelings (and also, see #5134). I've also found it useful but entirely for debugging which isn't a great argument. It's also not hard to create your own bundle.

ReactDOM corresponds to `require('react-dom')` so putting it on there directly won't happen. Maybe we can make a `ReactDOMServer` bundle. Or something awkward to make it obvious.

**Comment by holmsand** [comment]
This is causing some trouble for ClojureScript as well – ClojureScript doesn't play very well with npm, nor with webpack/browserify...

How about adding ReactDOM.Server or ReactDOM.ReactDOMServer?

**Comment by zpao** [comment]
We added react-dom-server.js to bower in 0.14.3
