### ISSUE TITLE
React 13.3 with addons minified version doesn't have TestUtils

### ISSUE THREAD

**Issue by rogeriochaves** [facebook/react#5163]
If I include react-with-addons, `React.addons.TestUtils` is available globally, but if I include the minified version, it is not

**Comment by jimfb** [comment]
I'm pretty sure that was an intentional/conscious decision.  Test utils aren't supposed to be used in production.  They aren't optimized for performance.  They exist to make it easy for you to test your code and debug.

**Comment by zpao** [comment]
Yep, it's long been the case. It's not well documented but we do call it out on http://facebook.github.io/react/docs/addons.html
