### ISSUE TITLE
Invariant Violation: Objects are not valid as a React child ... If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object)

### ISSUE THREAD

**Issue by almasakchabayev** [facebook/react#5168]
In my component's render function I have:
```
render() {
    const items = ['EN', 'IT', 'FR', 'GR', 'RU'].map((item) => {
      return (<li onClick={this.onItemClick.bind(this, item)} key={item}>{item}</li>);
    });
    return (
      <div>
        ...
                <ul>
                  {items}
                </ul>
         ...
      </div>
    );
  }
```
everything renders fine, however when clicking the <li> element I receive the following error:
```
Uncaught Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {dispatchConfig, dispatchMarker, nativeEvent, target, currentTarget, type, eventPhase, bubbles, cancelable, timeStamp, defaultPrevented, isTrusted, view, detail, screenX, screenY, clientX, clientY, ctrlKey, shiftKey, altKey, metaKey, getModifierState, button, buttons, relatedTarget, pageX, pageY, isDefaultPrevented, isPropagationStopped, _dispatchListeners, _dispatchIDs}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Welcome`.
```
If I change to `this.onItemClick.bind(this, item)` to `(e) => onItemClick(e, item)` inside the map function everything works as expected.

**Comment by seekshiva** [comment]
When you do this.onItemClick.bind(this, item), item will be passed as the first argument, and event will go in as the second argument.

But you said that `e => onItemClick(e, item)` worked. So maybe `onItemClick` is expecting arguments in the wrong order? [e, item] instead of [item, e].

Can you add logging statements in onItemClick to figure out where exactly the error is being thrown?

**Comment by almasakchabayev** [comment]
You are absolutely right! Sorry for wasting your time :( Seems like I need to have some sleep...
