### ISSUE TITLE
GraphQL and React compatibility

### ISSUE THREAD

**Issue by gyzerok** [facebook/react#5171]
This is related to https://github.com/facebook/react/issues/2166

Every time I try to use GraphQL and React together I face the same problem: GraphQL returns `null` for non-existed fields while React `defaultProps` works only for `undefined`.
Since more and more people now gonna use React with GraphQL I think there should be a nice way to handle this case.

Mb there is a nice way (not hacky) to deal with it right now and I'm missing something?

**Comment by zpao** [comment]
cc @yungsters - any input from the Relay side of things? Presumably this is handled there in some way.

**Comment by gyzerok** [comment]
@zpao The problem is for now you do have to define some wrappers like Relay in order to achieve this. For me it looks like it should be handled naturally. For now I have to map all the `null` props to `undefined` with higher-order component in order to deal with it. It seems hacky to use this higher order component all over the place.

**Comment by yungsters** [comment]
@zpao In Relay, no one uses default prop values.

Props with accompanying GraphQL fragments are completely managed by Relay. If applications want to default to a value (e.g. if a field happens to be `null`), they need to do that in `render()`.

If you think about it, arbitrary fields in GraphQL can be `null`. What makes the record that happens to be passed into a React component as a prop any more special than a field that happens to be nested inside that prop? (In other words, if we're going to apply default prop values to props, why not apply them to arbitrary tree paths in the GraphQL object?)

**Comment by gyzerok** [comment]
https://github.com/graphql/graphql-js/issues/210#issuecomment-149799194

**Comment by jimfb** [comment]
Closing as per @yungsters answer, which seems perfectly reasonable.  I don't think there is anything we could reasonably do here; current relay+prop behavior seems correct.
