### ISSUE TITLE
data-* attribute working only for html elements but not for custom component (0.13.3)

### ISSUE THREAD

**Issue by stepancar** [facebook/react#5180]
Hello! 
I create Component <MyComponent>

then try 
```html
<div data-test-id={'parent'}>
       <MyComponent data-test-id={'child'} />
<div>
```
in generated html you can find  data-test-id="parent"
but data-test-id="child" for root element of MyComponent can't find.
May be data-* attribute for custom component should be maped for root element?
Thank you!

**Comment by titoBouzout** [comment]
<MyComponent is not an HTML element is a React component, so you are passing it as a "prop"  https://facebook.github.io/react/docs/transferring-props.html

You can use it in the target component as follows:

	var MyComponent= React.createClass({
		render: function () {
			var data= this.props['data-test-id'];
			return <span data-test-id={data}></span>
		}
	});

**Comment by jimfb** [comment]
@stepancar We can't see your MyComponent implementation, but I suspect @titoBouzout is correct and has answered your issue.

Either way, this sounds like a usage question rather than a bug in the React core.  We're trying to keep github issues to track bugs in the React core, so I'm going to close out this issue.  Usage questions are better answered on StackOverflow.  Feel free to continue the discussion on this thread.

**Comment by stepancar** [comment]
@titoBouzout Thank you, i already use the same solution
@jimfb. I think that this behavior is wrong. If i passed data-* attribute to custom component it should be appears anyWhere. But in 1 case( when component is from core like <div>,<p>) passed data-* attribute appears in markup, 2 case (when component created ) passed data-* is not appears in markup.
Why @titoBouzout solution not implemented in react?
Thank you!

**Comment by titoBouzout** [comment]
Because the component may have many children, or even sub React Components. Imagine this case: 

    var MyComponent= React.createClass({
        render: function () {
            var data= this.props['data-test-id'];
            return <div>
                <div> username </div>
                <img className="user-profile-image">
                <div>last login <span>some day</span></div>
                <SomeCoolThing data-test-id={data}/>
            </div>
        }
    });

**Comment by jimfb** [comment]
@stepancar I wonder if you are mixing up custom elements with custom components.  Custom elements (like `<my-custom-element data-test-id="foo" />`) should work as you described.  Custom components do not necessarily have any markup associated with them, and can do arbitrary things with their props.

**Comment by stepancar** [comment]
@jimfb @titoBouzout , Thank you! It's my understanding fault.
Agree with you :+1:
