### ISSUE TITLE
Bower + ReactDOM: Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#5186]
After installing ReactDOM and adding it globally

```html
<script src="/bower_components/react-dom/react-dom.js"></script>
```

I get a ReferenceError that ReactDOM isnt defined...

**Comment by zpao** [comment]
ReactDOM is another file in the `react` package for Bower.

`<script src="/bower_components/react/react-dom.js"></script>`

**Comment by ccorcos** [comment]
Oh interesting. But its not the "main" so my bower script injector isn't seeing it... :/

**Comment by ccorcos** [comment]
It would be great if this were compatible with `wiredep` since a lot of people use this with bower.

https://github.com/taptapship/wiredep

**Comment by zpao** [comment]
Looks like we can just add react-dom to main and that should do it. https://github.com/reactjs/react-bower/pull/15

**Comment by ccorcos** [comment]
Sounds good to me!
