### ISSUE TITLE
npm install fails on Windows with npm '3.x'

### ISSUE THREAD

**Issue by line55** [facebook/react#5194]
Built master on Webstorm, with npm 3.3.9. Failed with error in /fbjs-scripts/node/check-dev-engines.js

AssertionError: Current npm version is not supported for development, expected "3.3.9" to satisfy "2.x".

Commenting out semver.satisfies block (line 56) allowed build to proceed.

**Comment by syranide** [comment]
#5154

**Comment by zpao** [comment]
Merged #5154 so this should work now.
