### ISSUE TITLE
Cannot read property 'componentDidLeave' of undefined

### ISSUE THREAD

**Issue by maketroli** [facebook/react#5196]
I've been trying to get this info from react docs but I don't see anything similar.

I am getting that error in the console everytime an item is deleted from a collection:

>Cannot read property 'componentDidLeave' of undefined

and I am not using `componentDidLeave` anywhere

do you have an idea?

**Comment by jimfb** [comment]
This is not enough information for this issue to be actionable.  Furthermore, it sounds like a usage question.  Usage questions should be asked on StackOverflow, as we use github issues to track bugs in the React core.  I'm going to close out this issue.

If you believe there is a bug in React, please create a simple testcase (jsfiddle) that demonstrates the issue and we can look into it.
