### ISSUE TITLE
gitter channel?

### ISSUE THREAD

**Issue by davis** [facebook/react#5200]
i know you guys have an irc channel, but you guys should have a gitter channel! :)

**Comment by jimfb** [comment]
Glitter looks like a startup clone of Slack.  Similar features, better pricing model, etc.

My intuition is that we don't want to do this, but I'll leave the issue open for a few days to collect feedback.  My reasoning is: Having too many underutilized communication channels is substantially less valuable than having a few very concentrated/active communication channels.  It's just one more thing for us to setup/maintain/etc.

Maybe @spicyj has thoughts.

**Comment by dallonf** [comment]
This isn't an official community, but it's a very large group of React users talking about all sorts of interesting stuff: [Reactiflux](http://www.reactiflux.com/)

**Comment by gaearon** [comment]
Yep, Reactiflux is where most of non-IRC discussion happens. It just moved to Discord from Slack: http://facebook.github.io/react/blog/2015/10/19/reactiflux-is-moving-to-discord.html.

**Comment by zpao** [comment]
If we really need we can open up gitter but let's give discord a chance.

**Comment by davis** [comment]
@dallonf thanks!!
