### ISSUE TITLE
Please add events onFocusIn & OnFocusOut

### ISSUE THREAD

**Issue by bORm** [facebook/react#5202]
subj
http://www.w3schools.com/jsref/event_onfocusin.asp
http://www.w3schools.com/jsref/event_onfocusout.asp

**Comment by mxstbr** [comment]
@jimfb this might be something I could look into! What about adding `focusIn` and `focusOut` to the `SimpleEventsPlugin` next to `focus`?

**Comment by jimfb** [comment]
I haven't looked at it, but that sounds reasonable to me.

**Comment by mxstbr** [comment]
These two are added here for IE support of `onFocus` and `onBlur` – should I still add them as seperate events or is it fine as-is? https://github.com/facebook/react/blob/master/src/renderers/dom/client/ReactBrowserEventEmitter.js#L297-L310

**Comment by jimfb** [comment]
Fixed via https://github.com/facebook/react/pull/6226

**Comment by gaearon** [comment]
As discussed in #6226 and as @mxstbr noted above, adding them explicitly probably wasn’t the right call after all. We already support `onFocus` and `onBlur` in a cross-browser way, and we should tell people to use them instead. Internally they [already use `focusin` and `focusout` on IE which implements the bubbling behavior](https://github.com/facebook/react/blob/c3b7f937b062a0afbdd404ba5ada51043a753808/src/renderers/dom/client/ReactBrowserEventEmitter.js#L300-L313).

We should probably consider adding a warning that tells you to use `onFocus` if you attempt to define `onFocusIn`.
