### ISSUE TITLE
How to getElementById with TestUtils renderIntoDocument

### ISSUE THREAD

**Issue by quicksnap** [facebook/react#5204]
I'm writing some karma tests:

```
    renderer = renderIntoDocument(
      <MyComponent>
        <Child id='foo' />
      </MyComponent>
    );
    dom = ReactDOM.findDOMNode(renderer);
```

Since `renderIntoDocument` doesn't actually render into `document`, how may I find a component by id?

**Comment by AnSavvides** [comment]
As a general note, you might want to use [shallow rendering](https://facebook.github.io/react/docs/test-utils.html#shallow-rendering) instead - as per [this conversation](https://discuss.reactjs.org/t/whats-the-prefered-way-to-test-react-js-components/26), it's the React team's recommendation. You can then make use of `scryRenderedDOMComponentsWithClass`, `scryRenderedDOMComponentsWithTag ` etc to get whatever component you might be after.

**Comment by jimfb** [comment]
@quicksnap If you need to do something with the output, you can just render into a div.

```
var container = document.createElement('div');
ReactDOM.render(<MyComponent><Child id='foo' /></MyComponent>, container);
```

This is basically all that `renderIntoDocument` does anyway.

**Comment by quicksnap** [comment]
No problem! I forget specifics on this, but lately I've been using Enzyme and it's been stellar!

Also, just wanted to say thanks for your work on cleaning up open issues--noticed you've been tackling some stuff and closing things out. Thanks for your work!
