### ISSUE TITLE
Any plans on extracting PropTypes and checks out of React?

### ISSUE THREAD

**Issue by elado** [facebook/react#5215]
Could be very useful with other variable checks like function arguments.

**Comment by zpao** [comment]
No, there are no plans for this. We generally suggest a static type checker, like flow, for things like that.

**Comment by shukyinng** [comment]
Thsnkyou so much

2015年10月20日週二 3:23 <Elad Ossadon> 於 notifications@github.com 寫道：

Could be very useful with other variable checks like function arguments.

—
Reply to this email directly or view it o
<https://github.com/facebook/react/issues/5215>

u <https://github.com/facebook/react/issues/5215>

b <https://github.com/facebook/react/issues/5215>.<img src="https://ci6

.
googleusercontent.com/proxy/mLxRHSO2r0o0ASwljcq4J6RR6IehZjBWLoR0G16nz6isKkedXMKdptUWEP_ASIaSmKj2RMLUJZCCtGcb08_ducVqQtblu4YfTjp3BBCOdRBgr-5487GYw0S_o-M23wvupI7BXmTLXB05QCbKPRhyjFpKcF9rRA=s0-d-e1-ft#https://github.com/notifications/beacon/AOQ34JI_XPlhqJHRc-VFQND4n5yqX3yFks5o9TqkgaJpZM4GRm1h.gif
">

**Comment by gaearon** [comment]
See also:

https://github.com/facebook/react/issues/4794
https://github.com/facebook/react/issues/3079
