### ISSUE TITLE
return null from a stateless fn component doesn't throw error using shallow renderer

### ISSUE THREAD

**Issue by tleunen** [facebook/react#5218]
With a basic React application, return null or false inside a stateless function component throws an error. But when using the shallow renderer (`ReactTestUtils.createRenderer`), no error are thrown and everything works as expected.

It's not consistent. The behavior should be the same.

Here's the error received when returning `null` inside a stateless fn component using react-dom:
> No 'render' method found on the returned component instance: you may have forgotten to define 'render', returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

Allowing it would be really great, but the error message mentioned it so I guess it's on purpose.

**Comment by ramin32** [comment]
What's the reason that a stateless component cannot return null?

**Comment by tleunen** [comment]
Seems it was an issue with the way I made my test. I close this issue but you can open another issue for discussion about that point @ramin32.
