### ISSUE TITLE
Call render with this.props

### ISSUE THREAD

**Issue by wmertens** [facebook/react#5222]
It would be nice if regular elements could get the same render API as the v0.14 pure components:

```jsx
class Bla extends React.Component {
  render({prop1, prop2}) {
    ...
  }
}
```

IMHO that is nicer than

```jsx
class Bla extends React.Component {
  render() {
    let {prop1, prop2} = this.props;
    ...
  }
}
```

It would also make it easy to move between pure and regular component declarations, and it encourages thinking of props as immutable.

**Comment by wmertens** [comment]
I believe this change is fully backwards-compatible...

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/4989
https://github.com/facebook/react/issues/1387
https://github.com/facebook/react/pull/3350#issuecomment-91108625

**Comment by yaycmyk** [comment]
Props + state would be better, also still fully backward compatible

**Comment by zpao** [comment]
#1387 is probably the best place to follow along with this ongoing discussion.
