### ISSUE TITLE
dangerouslySetInnerHTML generates different markup on client and server (0.13.3)

### ISSUE THREAD

**Issue by ruslansavenok** [facebook/react#5223]
With following code:

```
let keyTitlesMap = {
      office:              'Office & <br /> Transport links',
      culturePeople:       'Culture & <br /> people',
      trainingDevelopment: 'Training & <br /> development',
      workLifeBalance:     'Work/Life <br/> balance',
      career:              'Career <br /> progression'
}
let itemTitleHtml = {__html: keyTitlesMap[key]}
return <div dangerouslySetInnerHTML={itemTitleHtml}></div>
```

There's a warning:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) office.0.0">Office & <br /> Transport li
 (server) office.0.0">Office &amp; <br> Transport 
```

Both environments run code from same webpack bundle

**Comment by zpao** [comment]
This might be red herring due to the way the browser represents markup. We improved the way the message works in 0.14. Could you test there and see if you get a different message.

**Comment by banerjs** [comment]
Using 0.14.2, I'm seeing the same issue with the same message. Here's the server markup:

```
"<div id="content_body" data-reactid=".2d6gn68f0g0" data-react-checksum="633138555"><div id="content_page" data-reactid=".2d6gn68f0g0.0"><div class="container">
<h1> ... rest of the dangerously set inner html ...
</div>
</div></div>"
```

And here's the client markup post rendering (and after it has displayed the warning message **"Warning: React attempted to reuse markup in a container but the checksum was invalid."**):

```
"<div id="content_body" data-reactid=".2d6gn68f0g0"><div id="content_page" data-reactid=".2d6gn68f0g0.0"><div class="container">
<h1> ... and more of the same dangerously set inner html as before ...
</div>
</div></div>"
```

As you can see (and as I have verified with diff), the only difference in the markup pre and post render on the client is the presence/absence of the data-react-checksum attribute on the element being rendered.

Is there something special that I should be doing to ensure that the dangerouslySetInnerHTML does not cause a difference in the checksum?

**Comment by banerjs** [comment]
On a hunch I checked my dangerous inner HTML for non-standard characters, found some, and removed them. The warning is no more. What a stupid mistake, sorry!

I guess I now understand part of the motivation behind the name `dangerouslySetInnerHTML`

**Comment by Sawtaytoes** [comment]
I have the same issue you had. What do you mean non-standard characters that you removed?

**Comment by toddmoorega** [comment]
The ampersand is a non standard character `&`. Normally you would escape it via `&amp;`

**Comment by gaearon** [comment]
React doesn't use checksum validation anymore. If you have a similar problem after React 16 please file a new issue.
