### ISSUE TITLE
Issue with react-dom and react-addons-test-utils

### ISSUE THREAD

**Issue by TGOlson** [facebook/react#5225]
Hey there, I'm having a bit of a trouble with my component tests since upgrading to React 0.14.0. In particular, since moving away from `react/addons` and using `react-addons-test-utils` in conjunction with `react-dom`, some of my tests that simulate clicks are failing.

Here is an example of the test that works, but it uses `react/addons` and `React.render`, both of which are deprecated.

```js
import React from 'react/addons';

it("should invoke the supplied function when clicked", function() {
  const onClick = sinon.spy();
  const actionLink = <ActionLink onClick={onClick}/>;

  // We have a utility function that does this, but inlined here for clarity
  const div = document.createElement('div');
  React.render(actionLink, div);
  const element = div.children[0];

  React.addons.TestUtils.Simulate.click(element);
  assert(onClick.called);
});
```

So that works great, the supplied function gets called and the tests pass. However, as soon as I use `react-addons-test-utils`, or `ReactDOM.render`, the test fails. What's interesting, is that there is no combination (besides the passing case mentioned above) that works. So for example, `react-addons-test-utils + ReactDOM.render` fails, but so does `react-addons-test-utils + React.render`, as does `React.addons.TestUtils + ReactDOM.render`.

Any idea what could be causing this problem?

**Comment by TGOlson** [comment]
I think I dug up a little more context on this problem. In our app we bundle our source code and dependencies separate from our test code and dependencies, and then merge them to actually run the test code. This saves bundle time when making changes to the tests (you don't have to re-bundle source code and dependencies). 

However, the problem above seems to stem from declaring `react-addons-test-utils` as a dev dependency, which means it doesn't get compiled into the source bundle with the source dependencies. Is there some sort of issue when the test utils won't have access to the correct React instance if they are not bundled together?

**Comment by zpao** [comment]
> Is there some sort of issue when the test utils won't have access to the correct React instance if they are not bundled together?

Potentially. You're essentially doing bundle splitting and would need your packager to know that React/ReactDOM is already available. There are docs around the internet on how to do that with webpack and browserify. The other concern might be if you're running in dev or prod mode (NODE_ENV=production). I'm not sure if all of our testing utils will end up working in prod mode.

**Comment by TGOlson** [comment]
So I think we do have that part configured correctly - it worked previously when using `react/addons`. Our bundler knows what dependencies have already been bundled. Is there something with the split of `react`, `react-dom` and `react-addons-{x}` that could cause a problem?

**Comment by zpao** [comment]
I wouldn't expect it since react-addons-* just require deeply into the react package, as does react-dom (*for now*). But I've definitely seen some unexpected cases of multiple Reacts.

**Comment by jadekler** [comment]
Oh hey, github references by default. That's unexpected. Anyways @TGOlson not sure if it's helpful or not, but I recreated your test cases and I was unable to replicate - all permutations seem to pass fine (again, your setup is probs different than mine somehow).

As @zpao mentioned, might be something with your bundling.

**Comment by TGOlson** [comment]
@zpao @jadekler thanks for the help fellas. I think you are right, this seems like a bundling issue - if I bundle `react-addons-test-utils` with our source dependencies, things work. If I bundle it with the test dependencies, things fail (that is, `Simulate.click` doesn't seem to have an effect).

I haven't had time to get to the exact root of the issue, but I'll close this for now since it seems like everything on the React side is good. I'll update this issue if I find a solution that might help others with this issue.
