### ISSUE TITLE
ReactCSSTransitionGroup does not transition when wrapped around select multiple

### ISSUE THREAD

**Issue by tkiethanom** [facebook/react#5226]
I'm not sure why this is happening but when a multiple select is a child within ReactCSSTransitionGroup the transition is skipped completely. Anyone else having this issue?

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition
