### ISSUE TITLE
Bugs with document.createElement rendering

### ISSUE THREAD

**Issue by spicyj** [facebook/react#5238]
- setting type on textarea shouldn't throw
- setting dir={null} on div shouldn't add attribute
- setting dir="auto" on textarea throws in IE11

**Comment by zpao** [comment]
(Updated the title to avoid potential confusion with `React.createElement`)

**Comment by jimfb** [comment]
Seems to work to me (as per http://jsfiddle.net/6n9j9tf1/).  If I'm wrong, feel free to reopen, but please provide a fiddle.

**Comment by spicyj** [comment]
Yes, we fixed all these.
