### ISSUE TITLE
ReactTransitionGroup.js:116 `Uncaught TypeError: Cannot read property 'componentDidAppear' of undefined`

### ISSUE THREAD

**Issue by 59naga** [facebook/react#5240]
[Example 0.14.0 Animation | React / Fork by React Base Fiddle (JSX)](https://jsfiddle.net/59naga/k1zgswdL/4/)

Run another animation during animation, it will throw the Uncaught TypeError.
(Please try to run alternately on the link of the example)

**Comment by rstudner** [comment]
+1  Can see this every time trying animations.

**Comment by almirfilho** [comment]
+1

**Comment by Chrisui** [comment]
+1 Also seeing this. Glad someone found a reproducable case!

**Comment by spicyj** [comment]
I think #5391 fixed this.

**Comment by Chrisui** [comment]
@spicyj Any rough estimate on when we would see a published release with this fix?

Sadly a blocker for us upgrading as this breaks in a lot of places (due to a lot of animations).

**Comment by spicyj** [comment]
Not sure when we're planning a 0.14.3. Is this a regression in 0.14? I didn't realize that.

**Comment by Chrisui** [comment]
Afraid so. Definitely only popped up after upgrading from .13

**Comment by adidahiya** [comment]
+1, also seeing this with 0.14.2, particularly in unit testing when many components on the page animate at the same time.

**Comment by kendagriff** [comment]
+1 Ditto

**Comment by kendagriff** [comment]
Just upgraded to 0.14.3, and it appears to be fixed.

**Comment by 59naga** [comment]
:+1: [0.14.3 Animation | React / Fork by React Base Fiddle (JSX)](https://jsfiddle.net/k1zgswdL/7/)

**Comment by leoselig** [comment]
I'm still experiencing this issue
Now, it might be an issue with Material UI (although they really seem to use the componentWillAppear hook correctly)
Nevertheless, this issue referenced **ReactTransitionGroup** - judging from the PR (https://github.com/facebook/react/pull/5391/files) this was only a fix for **ReactCSSTransitionGroup**
Correct me if I am mistaken

**Comment by leoselig** [comment]
Turned out to be a Material UI issue that is fixed in their new alpha version by
https://github.com/callemall/material-ui/commit/38d5d3ef917893b6c21a98887c1ef085765e93ee
Everything is fine then :)
