### ISSUE TITLE
Provide unminified production distribution

### ISSUE THREAD

**Issue by jochenberger** [facebook/react#5242]
It would be nice if there was an unminified `react-production.js` in the release distributions. For example, this is useful for web application frameworks that do their own minification during runtime.

**Comment by iamdustan** [comment]
Running your project with `NODE_ENV=production` should achieve your desired effect.

**Comment by jochenberger** [comment]
I'm not talking about a node project. ;-) I use the `dist/react.js` file as an AMD module in a Java webapp.

**Comment by gaearon** [comment]
I think @iamdustan doesn't mean Node, he means using envifying (with something like [loose-envify](https://github.com/zertosh/loose-envify) or webpack's `DefinePlugin`). After you envify the development build, it's going to replace `process.env.NODE_ENV` checks inside React with `false`, and then UglifyJS will eliminate these as dead branches. That's how React works when used from NPM, for example.

**Comment by zpao** [comment]
@gaearon yea, but that still means integrating node into your workflow. I think the ask is more about separating the minification part from the prod/dev split. And honesty I've thought about doing this for a while, making it clearer that `react.min.js` is not simply `react.js` minified (which is a different pattern than a lot of libs).

```
react.dev.js
react.dev.min.js
react.prod.js
react.prod.min.js
```

But apart from making it clearer for people who are inadvertently using the dev build in prod, I'm not sure what the real wins are. Minifiying an already minified lib isn't ideal but it should be harmless.

@jochenberger could you explain *why* this would be helpful?

**Comment by jochenberger** [comment]
@zpao Separating minification is exactly my point. I use React in a Java web application framework. Users of the framework can enable or disable minification and toggle between development and production mode. Those settings are orthogonal (though the default settings are dev=>no minification, prod=> minification)
If a user chooses to disable minification in production, I'd like to be able to serve an unminified production version.

**Comment by jochenberger** [comment]
See also https://github.com/facebook/react/pull/7242

**Comment by gaearon** [comment]
We've actually gone into the opposite direction, and now minify even the CommonJS version ourselves in production mode. Doing this lets us apply optimizations that wouldn't otherwise be easy, consistently regardless of the bundler on the consuming side.

We don't expect people to need to debug React code itself so we don't plan to provide an unminified production mode. But if you feel strongly about it, you can build React from source and disable minification.
