### ISSUE TITLE
Provide react-addons.js in distributions

### ISSUE THREAD

**Issue by jochenberger** [facebook/react#5243]
There should be an additional `react-addons.js` file in the distribution package. In a multi-page app, there could be pages that need only `react.js` without the addons and some that need the addons as well. Currently that means that you add react-with-addons to all pages to avoid loading the react.js portion twice.

**Comment by iamdustan** [comment]
react addons are shipped as independent packages in 0.14. You should now install and require them as needed.

**Comment by jochenberger** [comment]
Yes, that's another option. But I need the packages as webjars (http://www.webjars.org/). I tried to have them created for the addon packages, but the procedure fails because the github repository is not specified for the NPM packages:
```
Failed!
The source repository for react-addons-update 0.14.0 could not be determined but is required to published to Maven Central.  This will need to be fixed in the project's package metadata.
```

**Comment by iamdustan** [comment]
haha ew. That requirement likely infers a development hell I don’t want to know about :)

**Comment by spicyj** [comment]
Unfortunately some of the addons use internals of React which aren't exposed in the browser build so this isn't really possible for us. We recommend consuming the addons from npm so you have control over exactly what gets bundled. #5388 sounds doable though.

**Comment by jimfb** [comment]
Oooh, webjars; that's pretty fancy :).
