### ISSUE TITLE
How Can I Change the Dependencies' Support Version

### ISSUE THREAD

**Issue by dubiao** [facebook/react#5244]
I set up a project and run it. 
It says required support `v7:23.0.1` . I didn't installed `v7:23.0.1`, but I installed`v7:22.0.1`. And I don't want to use `v7:22.0.1` for some reason. 

So I changed `android/app/build.gradle` file's dependencies line 
> compile 'com.android.support:appcompat-v7:23.0.1'

to 
> compile 'com.android.support:appcompat-v7:22.0.1'

This works usually in normal android projects. But didn't in react-native project. 
> Could not find com.android.support:appcompat-v7:23.0.1.

The error log seems a bit difference than before. It says:
> Required by:
>         AwesomeProject:app:unspecified > com.facebook.react:react-native:0.12.0

How could I change the dependencies' support version of com.facebook.react:react-native:0.12.0  to `v7:22.0.1` 
or in other words, How Can I Change the Dependencies' Support Version to a My Version

I have read the most of related issues. But they do not work for me.
I have read the [page of android setup](https://facebook.github.io/react-native/docs/android-setup.html) but it dose not work for me
I have surely installed Android Support Repository and Android Support Library and Google Repository

update:

Another reason I ask this question is:
When some day, google releases a support 'v7:24.0.1' , and I want to use it, but `com.facebook.react:react-native:0.12.0` this package still requires 'v7:23.0.1'. How could I make the project run perfectly? 

Thank you.

update:

I reboot by Mac and things changed. But still not works.
out put:
> No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

**Comment by dubiao** [comment]
Another reason I ask this question is:
When some day, google releases a support 'v7:24.0.1' , and I want to use it, but `com.facebook.react:react-native:0.12.0` this package still requires 'v7:23.0.1'. How could I make the project run perfectly? 
Thank you.

**Comment by zpao** [comment]
React Native is in a different repo so you may want to discuss your issues there: https://github.com/facebook/react-native

**Comment by dubiao** [comment]
sorry, I meat to post this in react-native repo, but I made a mistake. . Sorry , Sorry. 
If any guy could delete this issue, please?
