### ISSUE TITLE
0.14.0: createElement fails when children node is an array of React elements

### ISSUE THREAD

**Issue by olaf-k** [facebook/react#5245]
It seems that this:
```jsx
var Seq = React.createClass({
    render : function() {
        return(
            <span>
                {['one', 'two', 'three'].map(function (e) { return <div>{e}</div> })}
            </span>
        )
    }
})
```
silently fails when using 0.14.0 and ReactDOM while it renders fine with 0.13.3.
Am I missing something?

**Comment by tlightsky** [comment]
maybe key?

**Comment by olaf-k** [comment]
@tlightsky I don't think so as I don't even get a warning about that. Just tried with a key'd wrapper, still nothing :(

**Comment by olaf-k** [comment]
ooookay, so obviously there's nothing going on with 0.14 itself, the problem disappeared as soon as I switched to FF devtools instead of Firebug. I have no idea why that is but this has nothing to do with the framework, sorry for the noise.

**Comment by zpao** [comment]
There may be something we're doing that is causing this. I opened #5258 to track.
