### ISSUE TITLE
<track /> attributes support

### ISSUE THREAD

**Issue by gre** [facebook/react#5246]
I'm trying to use Video `<track/>` element but some attributes doesn't work.

from http://www.html5rocks.com/en/tutorials/track/basics/

i'm trying to do:

```html
<track
src="developerStories-subtitles-en.vtt"
label="English subtitles"
kind="subtitles"
srclang="en"
default
/>
```

but it only renders to:

```html
<track
src="developerStories-subtitles-en.vtt"
label="English subtitles"
data-reactid=".0.1"
></track>
```

**Comment by zpao** [comment]
kind and srcLang were added recently in https://github.com/facebook/react/pull/5174. They'll be a part of a future release (likely 0.14.1). I didn't see default then though so I guess we still need to add that.

**Comment by jimfb** [comment]
Related to #140
