### ISSUE TITLE
Perf actual React components

### ISSUE THREAD

**Issue by gfogle** [facebook/react#5254]
ReactPerf and ReactDefaultPerf allow for profiling the react internals of ReactCompositeComponent but what I really think would be useful is for React to have a start(), stop() style for perfing the components. Or, possibly just track these methods automatically and spit out warnings. 

Some long range uses would be:

- how many times did you call shouldComponentUpdate? what was the response? if you're always returning true, that might be insightful for your components.
- how many times did you call setState? could compare this with # of render cycles to track forced renders possibly?

I had started work in #4522 but that just needed to be closed.

**Comment by gaearon** [comment]
#6046 is going to offer much more granular stats so I’m closing this issue in its favor.
