### ISSUE TITLE
Addons/Update push in array based on a id 

### ISSUE THREAD

**Issue by alexduros** [facebook/react#5256]
The `react-addons-update` is very useful to me but I wonder the best way to use it in a use case I have.
I have an `Array` of items indexed by a `uniqueId`.
I want to use the `$push` command in way only new `uniqueId`, may be added and others updated.

For example 

```javascript
var items    = [{ uniqueId: 1, value: "foo"}, { uniqueId: 2, value: "bar"}];
var newItems = [{ uniqueId: 2, value: "baz"}, { uniqueId: 3, value: "bam"}];
update(value, {items: {$push: newItems}}); // [{ uniqueId: 1, value: "foo"}, { uniqueId: 2, value: "baz"}, { uniqueId: 3, value: "bam"}]
```

I had a look to combine `$assign` and  `$merge` behavior. Do you have some advice for this type of use case or do you consider another command may be needed for that ?

**Comment by gaearon** [comment]
There is no such plan for `update()`. You can use `$apply` to apply a custom function that would do what you describe. Alternatively you can use https://github.com/kolodny/immutability-helper which has the same basic API but also lets you define custom operations. I hope this helps!
