### ISSUE TITLE
React & Firebug not playing nicely together

### ISSUE THREAD

**Issue by zpao** [facebook/react#5258]
It's not clear where the blame for this one lies yet, but there have been a couple reports of React not working when Firebug is used. This only seems to affect v0.14 and not 0.13.

**Comment by ericnakagawa** [comment]
Hey @zpao Is this still an issue?

**Comment by zpao** [comment]
Haven't seen anything recently, probably ok to close out. We can revisit if it's still an issue and can be traced back to something specific.
