### ISSUE TITLE
Why do the docs on ReactLink say "note that ReactLink is not needed for most applications and should be used cautiously."?

### ISSUE THREAD

**Issue by jeberly** [facebook/react#5259]
Why do the docs on ReactLink say "note that ReactLink is not needed for most applications and should be used cautiously."?

https://facebook.github.io/react/docs/two-way-binding-helpers.html

I assume having onChange handler on inputs is the preferred way to update state, and ReactLink, et al. just make that pattern a bit less boiler plate.   So I guess, I wanted to understand the note on the docs before I start using it.

Cheers, 
-john

**Comment by zpao** [comment]
Your assumption is a good succinct way to explain. The other reason we advise caution is that ReactLink has the downside of hiding the two-way binding so it becomes really easy to get stuck with harder-to-diagnose behavior. We'll likely move support for ReactLink out of core soon and move it into user land.

**Comment by jeberly** [comment]
Thanks for your quick answer!   So basically it is advised against because it hides what is actually going on from the developer?  Also, thanks for the heads up on ReactLink moving out of core.
