### ISSUE TITLE
Cursor jumps to end of controlled input

### ISSUE THREAD

**Issue by tsheaff** [facebook/react#5265]
@spicyj @zpao  The cursor of a controlled `input` element is jumping to the end whenever I format or modify the `value` between renders.

Here's my code:
```js
export default class GiftPurchaseForm extends Component {
  constructor(props) {
    super(props);
    this.state = {
      cardNumber: ''
    };
  }

  cardNumberChanged(event) {
    this.state.cardNumber = event.target.value;
    this.setState(this.state);
  }

  render() {
    return (
      <div id="gift-purchase-form">
        <input
          className="card-number"
          type="text"
          placeholder="Card Number"
          value={creditcard.parse(this.state.cardNumber).formatted}
          onChange={::this.cardNumberChanged}
        />
      </div>
    );
  }
}
```

[`creditcard.parse(*).formatted`](https://github.com/observing/creditcard/tree/master/docs#creditcardparsenumber-string) simply turns a number like `4444555566667777` into a card number like `4444 5555 6666 7777` which is a common use-case for things like phone-numbers etc.

If I remove call to `creditcard.parse(*).formatted` and just pass `this.state.cardNumber` the cursor doesn't jump.  But the cursor still jumps even if I pass `this.state.cardNumber + '5';` as the next value, so it seems any modification of the string between renders means middle edits (edits *before* modification point in string) cause cursor to jump to end.

I'm on react v0.14.0 and Chrome 46

The bug seems related to [this line of code](https://github.com/facebook/react/blame/master/src/renderers/dom/client/ReactInputSelection.js#L61) in `ReactInputSelection.js` because when I comment out that `if` the bug is fixed.  `curFocusedElem` and `priorFocusedElement` pass the `===` test even though the `value` has changed.

**Comment by localvoid** [comment]
When you type into input field, browser makes operations like `insertText(cursorPosition, newText)`, and it knows how to translate cursor position according to this operation, but when you reassign value externally, it is like doing two ops `removeText(0, len(oldText)), insertText(0, newText)`, and there is no way to "restore" cursor position when you doing such operations, because it doesn't have enough information to translate cursor in a way that you want.

**Comment by spicyj** [comment]
Yeah, we can't really do anything better here. You can set `.selectionStart` and `.selectionEnd` on the DOM node manually.
