### ISSUE TITLE
Lost IME input when call setState()

### ISSUE THREAD

**Issue by bradwoo8621** [facebook/react#5270]
Hi,

I have a component like this:

```javascript
var AComp = React.createClass({
   getInitialState: function() {
      return {
         label: 'Synchonized with input'
      };
   },
   render: function() {
      return (<div>
         <input type='text' onChange={this.textChanged} />
         <span>this.state.label</span>
      </div>);
   },
   textChanged: function(evt) {
      this.setState({label: evt.target.value});
   }
});
```

when I input english in the text, it works well. but when I input chinese/japanese/korea charaters with IME, it breaks.

I guess it since I call setState in textChanged, seems call jQuery directly, it works well.
The question is, calling jQuery to change the DOM maybe is not a good choice, is there any way to only refresh some parts of component?

Many thanks.

**Comment by bradwoo8621** [comment]
BTW, I try to submit a snippet to JSFiddle, but seems it doesn't support JSX yet. So I have to key in code here, sorry for no live demo to check.

**Comment by rpominov** [comment]
You probably can use this https://react.jsbin.com/ as base for live demo.

**Comment by bradwoo8621** [comment]
https://react.jsbin.com/nivokacidu/edit?js,console,output

seems works very well in IME.

My real component is not this simple, so I guess there is somewhere wrong cause this problem. let me check it by myself.

thanks for you time again.

**Comment by bradwoo8621** [comment]
I found the root cause. thank you very much
