### ISSUE TITLE
When will test-utils be ES6 friendly?

### ISSUE THREAD

**Issue by toranb** [facebook/react#5271]
In the testing docs I see CJS is still the way to pull in the TestUtils directly. When I tried to use ES6 instead like below I get the error `Cannot resolve module 'react-addons-test-utils`

```js
import TestUtils from 'react-addons-test-utils';
```

When I do the legacy import ES6 (like below) I get `Warning: require('react/addons') is deprecated. Access it using require('react-addons-{addon}') instead.`

```js
import React from 'react/addons';
const TestUtils = React.addons.TestUtils;
```

**Comment by toranb** [comment]
*update*

I found reading through a bit further :) that I needed to pull that dependency in by itself in my package.json like so

```
    "react-addons-test-utils": "*",
```

Now in my tests this ES6 import works just fine. Sorry for the confusion

```js
import TestUtils from 'react-addons-test-utils';
```

Question for future reference - is a browser friendly (pure ES6 driven) example planned at any time? My biggest gripe w/ the React community is that it's very node-centric (CJS-first instead of ES6-first) and I only build frontend apps :(

**Comment by AnuragRamdasan** [comment]
+1

**Comment by gaearon** [comment]
>My biggest gripe w/ the React community is that it's very node-centric (CJS-first instead of ES6-first) and I only build frontend apps :(

Everybody is using it for front-end apps. :wink:

When React first came out, ES6 module system wasn't there, but client-side JS bundlers like Webpack and Browserify were, and they supported CommonJS. That's why React examples currently use it. It doesn't have anything to do with Node per se.

**Comment by toranb** [comment]
@AnuragRamdasan dude what's the +1 for :) I gave an update saying "my bad, I needed to pull in the correct dependency and all was good"

**Comment by toranb** [comment]
@gaearon my fault if I sounded like a scumbad troll - totally venting from my 2014 experiences w/ React (if I'm honest about it). In the last month, my experience has been totally different as you stated. All good now :)

**Comment by AnuragRamdasan** [comment]
Im sorry, I could've been clearer. Was hoping to get a response on `browser friendly (pure ES6 driven) example planned? `. I could've been more clearer I guess. :)

**Comment by toranb** [comment]
@AnuragRamdasan ah yes -to that point lets keep this issue open :)

I almost forgot (as it took nearly 1 full month to get a response from anyone)

**Comment by gaearon** [comment]
Closing as docs use ES6 now.
