### ISSUE TITLE
Immutable.KeyedIterable as children

### ISSUE THREAD

**Issue by jareware** [facebook/react#5272]
I'm aware of the [Iterable support for children](https://jsfiddle.net/aneo4nhk/), but is there any timetable for supporting [KeyedIterable](https://facebook.github.io/immutable-js/docs/#/KeyedIterable) from Immutable.js, specifically for [automatically providing keys to children](https://github.com/facebook/react/blob/ac5e5d789f022f0d13107e54653f13a8ede0330b/src/shared/utils/traverseAllChildren.js#L154-L159)?

Sample use case:

``` js
var myItems = Immutable.Map({ // extends KeyedIterable
  one: 111,
  two: 222
});
var renderedItems = (
  <ul>{myItems.map(item => (
    <li>{item}</li>
  ))}</ul>
);
```

That is, the first item would end up the equivalent of `<li key="one">111</li>`.

If such support isn't on the roadmap, can I somehow avoid having to use `React.cloneElement()` (which will have performance implications) if I write a helper function that does this?

**Comment by syranide** [comment]
I'm curious, could it not make sense for Immutable.js to have an alternative `map` function that returns a regular object/Map instead? Seems like it could be used as a performance optimization.

**Comment by jareware** [comment]
Well, you can always go `myItems.map(...).toList().toJS()` (which converts to a plain old array), but that's quite a bit of typing, and also requires you to assign `key` props by hand (as opposed to automatically picking them up from the keys of the Map).

Also, if you meant using native Maps, that's sort of what brought be here. :) It yields:

> Warning: Using Maps as children is not yet fully supported. It is an experimental feature that might be removed. Convert it to a sequence / iterable of keyed ReactElements instead.

**Comment by kentor** [comment]
`toArray` is enough, you don't need `toList` then `toJS`

**Comment by jareware** [comment]
Fair enough, though this is somewhat beside the point, the original question was related to `key` handling with KeyedIterables.

Any ideas?

**Comment by cristian-sima** [comment]
+1

**Comment by cristian-sima** [comment]
> toArray is enough, you don't need toList then toJS

`toArray` is a costly operation as it is `toJS()`.

I agree with @jareware that React should have build in support for `KeyedIterable`. 


It is really painful when you start to [normalize data](https://github.com/paularmstrong/normalizr), store it as Maps and then every time you get that warning in your log.

![image](https://cloud.githubusercontent.com/assets/12199042/18808179/c775a9d2-8263-11e6-8ae1-6957231d0b41.png)

**Comment by kentor** [comment]
Then use valueSeq instead of toArray

**Comment by xylolink** [comment]
I have a strange behavior (bug?) using valueSeq() after the 15.4.0 update. React is iterating twice my Immutable.Map. Whereas it's only iterating once when using toArray().

Here is my testing code :
```
render() {
  const myMap = Immutable.Map({a: 1, b: 2, c: 3})
  i = 0
  return (
    <div>
      { myMap.valueSeq().map( item => {
         console.log(i)  // logs 0 1 2 3 4 5
         i++    
         return <div key= {item}>{item}</div>
      }
      { myMap.toArray().map( item => {
         console.log(i)  // logs 0 1 2
         i++    
         return <div key= {item}>{item}</div>
      }
    </div>
)
}
```
Does anyone have the same behavior ?

**Comment by mashhur** [comment]
I have also tried `map.toList(), map.toArray(), map.values(), map.valueSeq()` but no one is worked.
FYI, my part code is here:

`// through the connect I get the props.items
items: state.timeline.getIn(['children', Number(props.item.get('key'))]) || [],

// in render() using a map, this part always warns ()
{items.map((values) =>
   console.log(values)
)}`

**Comment by ydeshayes** [comment]
+1 here !  React is iterating twice my Immutable.Map with valueSeq()

**Comment by markuslerner** [comment]
Same here. Any news on why React iterates both valueSeq() and entrySeq() twice? This still happens to me with React 15.4.2.

Using Immutable.Map.map() directly and ignoring the error "Using Maps as children is not yet fully supported" works fine though, which is weird.

**Comment by nikolas6** [comment]
This happens to me too. React iterates `entrySeq()` twice. This is the first thread I found so far that mentioned this issue.

Just wondering, do you guys keep using `entrySeq()` that iterates twice? or using `.toArray()` first or `.map()` directly to iterate once?

**Comment by Ciul** [comment]
You could instead of passing Immutable Collections such as Maps and Lists to your React components, pass normal js objects and arrays, respectively. Thay way, it's easier to read and understand, and you remove dependency/boilerplate of Immutable from your React components. (Better and easier tests of your components)

Remember that Immutable Map each _keys_ and _values_ method return an iterator, which can be converted to an array using the spread operator inside brackets.

This way, using a normalized state for a Todos demo app e.g:
```javascript
const stateShape = Record({
    todos: Map({
        1: {
            name: 'Eat a lot'
        },
        2: {
            name: 'Take span'
        },
    })
})
```
I'd suggest a mapStateToProps function like this:
```javascript
[...] // some other code
const getProjectsArray = state => {
    const todos = state.get('todos')
    const todosArray = [...todos.values()]
   
   return todosArray
}

const mapStateToProps = (state) => {
    projects: getProjectsArray(state)
}
[...] // Some other code
```

**Notes:**
- This makes easier to use tools like [Normalizr](https://github.com/paularmstrong/normalizr) and [Reselect](https://github.com/reactjs/reselect).
- Remember to convert back to Immutable Collections your data before injecting it in your state. Which could be done in reducers but a better approach would be keep reducers out of complex logic and move all logic to something like a middleware.

**Comment by gaearon** [comment]
If you see any bugs in React please file a new issue. We don’t track this issue for bugs because it is a feature request. So your comments with issues get lost here.

**Comment by aweary** [comment]
The issues described here where collections are iterated multiple times is likely related to #12995 and React's DEV-only validations. 

This isn't a frequently requested feature, and I'm hesitant about adding explicit support for a specific library's data structures (a cost which all users will have to pay). Even so, this would be better as an RFC. 

If you'd like to write up a formal RFC for this, please do so at https://github.com/reactjs/rfcs

Thanks!

**Comment by sajja94** [comment]
`{state.selfReferrers && state.selfReferrers.map(([key,value]) => (
                        <MenuItem key={key} value={value.id}>
                          {value.referralNum}
                        </MenuItem>
                      ))}`

this code is given following Warning.

Warning: Using Maps as children is unsupported and will likely yield unexpected results. Convert it to a sequence/iterable of keyed ReactElements instead.
