### ISSUE TITLE
Component not seen as reactElement / dom is not defined on server side renderToString

### ISSUE THREAD

**Issue by julesv82** [facebook/react#5273]
I'm trying to render a very simple "hello world" component on the server

My JSX Babel compiled js file looks like this:

`/** @jsx dom */
"use strict";

var React = require("react");
var ReactDOM = require("react-dom");

var Title = React.createClass({
  displayName: "Title",

  render: function render() {
    return dom(
      "h1",
      null,
      "Hello World"
    );
  }
});

module.exports = React.createFactory(Title);`

Im getting Invariant Violation error, you must pass a valid reactElement. If I change createFactory to createElement, I get dom is not defined.

**Comment by zpao** [comment]
Sounds like you need to require whatever "dom" is. That's nothing we officially support so you'll want to work it out with whatever provided that.

Also, you really shouldn't export factories. Those aren't compatible with others who decide to use creatElement.

**Comment by zpao** [comment]
Closing since dom is not a thing made by us.

**Comment by julesv82** [comment]
Thank you for your response.
