### ISSUE TITLE
assertValidProps breaks '__html' name mangling

### ISSUE THREAD

**Issue by quadrupleslap** [facebook/react#5275]
An alternative that would work is `typeof ... !== 'undefined'` instead of ('__html' in ...).

Edit: Or, you could remove the checks in production, which I'm not sure is a good idea. Also, the file is `lib/ReactDOMComponent.js`

**Comment by syranide** [comment]
`keyOf({__html: null})` should be the correct approach and this indeed seems like a bug to me. Do you want to submit a PR for it?

cc @zpao @spicyj

**Comment by quadrupleslap** [comment]
https://github.com/facebook/react/pull/5297
Pretty sure that works.

**Comment by zpao** [comment]
Fixed with #5297.
