### ISSUE TITLE
onClick not adding handler

### ISSUE THREAD

**Issue by LucioFranco** [facebook/react#5277]
I have code like this with babel:
```
<a onClick={this.handler}></a>
```
In the React dev tools it seems that the onClick prop is set to the correct function but when I check what function is actually assigned to the event handler it is just emptyFunction.

I have process.env.NODE_ENV='production'; set. It was working before in 0.13.3 but since upgrading the onClick as stopped working. If I use $r and select the element with react dev tools and call the handler it works.

**Comment by zpao** [comment]
Can you give a complete standalone test case that isn't working. We haven't had any other reports of `onClick` not working in 0.14.

Or is this is exclusively about the dev tools not showing the right thing?

**Comment by jimfb** [comment]
@LucioFranco Can you could provide a testcase/jsfiddle that demonstrates the issue?

**Comment by LucioFranco** [comment]
@zpao @jimfb seems that it is not in fact an error with React. Thanks for the quick responses.

**Comment by stoeffel** [comment]
It looks like `onClick` doesn't work on IE 11. ([see here](http://jsbin.com/jutunikoyo/1/edit?html,js,console,output))

**Comment by MadRabbit** [comment]
Weirdly enough, I have the same exact issue. After upgrade from 0.13 -> 0.14 all onClicks stopped working. @LucioFranco could you share what was the issue in your case?

**Comment by stoeffel** [comment]
@MadRabbit there was a problem with the 0.14.1 dev build with events not being fired (in IE and edge). make sure you're on latest 0.14.3

**Comment by MadRabbit** [comment]
Hmm, wicked. I've tried 14.4 and 14.6 with the same result. Either way, thanks for a quick answer!

**Comment by MadRabbit** [comment]
ok, in case someone runs into a similar thing. my problem was that i was rendering directly into `document.body`. apparently in version 0.14 something was changed in that regard. the app still renders, but events handling is somehow scrambled.

So, i've fixed it by rendering into `document.documentElement` and reinserting the `HEAD` back into document. kind of ugly but it works
