### ISSUE TITLE
DevTools: Make component search faster

### ISSUE THREAD

**Issue by appsforartists** [facebook/react#5278]
If I try to use the Search by Component Name panel, it only captures some of my keystrokes.  I suspect it is burning cycles filtering the list, so it isn't available to catch the remaining keystrokes.

Perhaps this could be solved with a web worker.  Send it searches as you receive the keystrokes, let it do the filtering in the background, and return the results to the UI thread.

Just a thought - I don't know how the search is implemented, but it should certainly not be missing keystrokes.

**Comment by zpao** [comment]
Could you report this over in the devtools project? Thanks! https://github.com/facebook/react-devtools

**Comment by appsforartists** [comment]
Oops - sorry @zpao.

Looks like they're already aware of it:  https://github.com/facebook/react-devtools/issues/220
