### ISSUE TITLE
react-dom includes react

### ISSUE THREAD

**Issue by mvolkmann** [facebook/react#5282]
My project uses react, react-dom, and react-bootstrap.
react-bootstrap requires react to be a peer dependency.
react-dom includes react as a child dependency.
So I must install react as a top-level dependency in order for react-bootstrap to work.
Now I have two copies of react.
When I try to use the Modal component in react-bootstrap, I get the error "Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded".
I can fix this by deleting the directory node_modules/react-dom/node_modules/react.
Maybe react-dom should be changed so react is a peer dependency instead of a child dependency.

**Comment by syranide** [comment]
> react-dom includes react as a child dependency.

As far as I understand it; yeah it should be a peer dependency (cc @zpao ?). But dependencies are not *child dependencies* that's simply a result of how NPM2 unfortunately resolves version issues, so peer dependency is preferable, but a regular dependency is not wrong, you just have to be careful to avoid multiple installations.

**Comment by mvolkmann** [comment]
I don't know what I did to cause react to be installed below react-dom.
I had this: node_modules/react-dom/node_modules/react
and also: node_modules/react.
I can't find a way to reproduce that now.

**Comment by syranide** [comment]
It can happen quite stealthily when updating/etc in NPM2. I ran into the same issue recently.

I'll reopen this for now because it really seems to me that it should be a peer dependency.

**Comment by bjrmatos** [comment]
Any reason why it is a direct dependency in the first place? Was not the intend of npm's peerDependencies to cover this exact problem? (Avoid duplications of modules built around other module, like react and react-dom), just saying that seems there isn't a reason for react-dom to include react as a direct dependency

**Comment by zpao** [comment]
It probably should be a peerDep. I don't remember why I put it as a regular dep there… (I did addons-* with React as a peerDep).
