### ISSUE TITLE
Android4.2.2，Compoent's Event failure  

### ISSUE THREAD

**Issue by zenjava** [facebook/react#5285]
Button's onclick event , Text box of onChange event will be invalid . Later we had to use jQuery event bindings native binding in compoentDidMount and compoentDidUpdate

**Comment by zpao** [comment]
Can you provide a test case, what you did, what you expected to happen, and what actually happened. Otherwise we can't determine if there is a bug in React as we have nothing to go on. Thanks

**Comment by zenjava** [comment]
I'm use React in Android developer, Simulation using Genymotion.Genymotion is an Android simulator, a free version can be used. You can download a test under.
The following code, in Android4.4.2 normal use. But in Android4.2.2, Change event can not be triggered.
/**
 * Created by liguoxin on 2015/10/20.
 */
/**
 * Created by ligx on 2015/9/23.
 */
module.exports = (function () {
    var React = require("react");
    var ValueMixin = require("../../jryj/widgets/ValueMixin");
    return React.createClass({
        mixins: [ValueMixin],

        getDefaultProps: function () {
            return {
                type: "text",
                placeholder: "",
                unit: "",
                data: "text"
            }
        },
        getInitialState: function () {
            return {
                value: "",
                disabled: this.props.disabled
            }
        },


        render: function () {
            var className = "uinn ub-img umar-a " + this.props.iconClass;
            var value = this.getValue();

            if (this.state.disabled) {
                return <div className="ub ub-ac uba umh4-5 bc-border uc-a3 umar-t1">
                    <div className=" uinput ub ub-f1 ub-ac">
                        <div className={className}></div>
                        <input placeholder={this.props.placeholder} type={this.props.type} className="ub-f1"
                               onChange={this.handleChange}
                               disabled="disabled" value={value}/>
                        {this.props.children}
                    </div>
                </div>;
            } else {
                return <div className="ub ub-ac uba umh4-5 bc-border uc-a3 umar-t1">
                    <div className=" uinput ub ub-f1 ub-ac">
                        <div className={className}></div>
                        <input placeholder={this.props.placeholder} type={this.props.type} className="ub-f1"
                               onChange={this.handleChange} value={value}
                            />
                        {this.props.children}
                    </div>
                </div>;
            }
        }
    });
})();

Later, I changed the code above uses jQuery event binding, the program is operating normally.


/**
 * Created by liguoxin on 2015/10/20.
 */
/**
 * Created by ligx on 2015/9/23.
 */
module.exports = (function () {
    var React = require("react");
    var ValueMixin = require("../../jryj/widgets/ValueMixin");
    return React.createClass({
        mixins: [ValueMixin],
        bindChange: function () {
            var me = this;
            $(this.refs.textcontainer).change(function (e) {
                me.handleChange(e);
            });
        },
        componentDidMount: function () {
            this.bindChange();
        },
        componentDidUpdate : function () {
            this.bindChange();
        },
        getDefaultProps: function () {
            return {
                type: "text",
                placeholder: "",
                unit: "",
                data: "text"
            }
        },
        getInitialState: function () {
            return {
                value: "",
                disabled: this.props.disabled
            }
        },


        render: function () {
            var className = "uinn ub-img umar-a " + this.props.iconClass;
            var value = this.getValue();

            if (this.state.disabled) {
                return <div className="ub ub-ac uba umh4-5 bc-border uc-a3 umar-t1">
                    <div className=" uinput ub ub-f1 ub-ac">
                        <div className={className}></div>
                        <input placeholder={this.props.placeholder} type={this.props.type} className="ub-f1"
                               ref="textcontainer"
                               disabled="disabled" value={value}/>
                        {this.props.children}
                    </div>
                </div>;
            } else {
                return <div className="ub ub-ac uba umh4-5 bc-border uc-a3 umar-t1">
                    <div className=" uinput ub ub-f1 ub-ac">
                        <div className={className}></div>
                        <input placeholder={this.props.placeholder} type={this.props.type} className="ub-f1"
                               ref="textcontainer" value={value}
                            />
                        {this.props.children}
                    </div>
                </div>;
            }
        }
    });
})();

ValueMixin Code

/**
 * Created by ligx on 2015/10/15.
 */
module.exports = (function () {
    return {
        getValue: function () {
            return this.state.value;
        },

        handleChange: function (arg) {
            var oldValue = this.getValue();
            var newValue = arg.target.value;
            var _this = this;
            if (this.processValue) {
                newValue = this.processValue(newValue, oldValue);
            }

            this.setState({value: newValue}, function () {
                if (_this.props.onChange) {
                    _this.props.onChange(newValue, oldValue);
                }
            });

        },

        setValue: function (value) {
            this.handleChange({
                target: {
                    value: value
                }
            });
        }
    };
})();

**Comment by zpao** [comment]
Looks like this is likely the same issue as #5153, which we have a fix for going out when we ship 0.14.1, which should happen in the next day or so.
