### ISSUE TITLE
0.14: Component names displayed as ProxyClass in the React tab in Chrome Dev Tools

### ISSUE THREAD

**Issue by wan54** [facebook/react#5288]
In 0.14, do we have to explicitly define `displayName` in each component?

Without specifying `displayName` the component name becomes `ProxyClass` in the React tab in Chrome Dev Tools.

Running the latest React Dev Tools.

**Comment by zpao** [comment]
> In 0.14, do we have to explicitly define displayName in each component?

That will depend on you compiling toolchain. By default you should not need to specify it when using Babel, though there may be some cases that aren't handled.

**Comment by wan54** [comment]
my colleague installed babel-plugin-react-display-name and that shows the actually component name
