### ISSUE TITLE
Confusing handling of "is" within props

### ISSUE THREAD

**Issue by mhahn** [facebook/react#5298]
Within: https://github.com/facebook/react/blob/master/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L108 `is` is listed as a supported HTMLDOMProperty.

However, including `is` anywhere in the component means that react treats it as a custom component and will just dump all key="value" pairs without handling other supported HTMLDOM properties like `className` etc.

I came across this when trying to do server side rendering for a third party library that expands `is` into `style={...}`. 

I don't expect react to care about the external library overloading `is`, but is it confusing that its listed as a valid HTML property in the release notes, but if you use it it also treats the DOM element as custom.

**Comment by zpao** [comment]
`is` means something in HTML, that the element is inheriting from another element. This is a part of the custom elements / web components spec. https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements. See more discussion in https://github.com/facebook/react/issues/4933.

I think the right move for that library is either to remove the `is` prop (though that could be risky as `is` is has a valid use in the DOM) or use a prefix such that you know you aren't reusing a prop that has valid use in the DOM. You'd run the same risk if you were using `title` for example - making it mean something special for a specific library isn't awesome (we run the same risk with `key`, `ref`, and `children` fwiw).

**Comment by zpao** [comment]
(since the rest of this overlaps with the other issue, I'm just going to close out)

**Comment by mhahn** [comment]
i see, i wasn't aware of the web components spec. i'll read through the other issue. thanks!
