### ISSUE TITLE
Release 0.14.1

### ISSUE THREAD

**Issue by zpao** [facebook/react#5301]
It's time. Let's do it.

I don't think anything left open on the milestone list is enough to block but if fixes come in we'll take 'em.

- https://github.com/facebook/react/pull/5081
- https://github.com/facebook/react/pull/5085
- https://github.com/facebook/react/pull/5164
- https://github.com/facebook/react/pull/5157
- https://github.com/facebook/react/pull/5166
- https://github.com/facebook/react/pull/5174
- https://github.com/facebook/react/pull/5263
- https://github.com/facebook/react/pull/5250
- https://github.com/facebook/react/pull/5297
- https://github.com/facebook/react/pull/5237
- https://github.com/facebook/react/pull/5304

* * *

Changelog (could probably be cleaned up a little bit, maybe organized differently):

### React DOM
- Fixed bug where events wouldn't fire in old browsers when using React in development mode
- Fixed bug preventing use of `dangerouslySetInnerHTML` with Closure Compiler Advanced Mode
- Added support for `srcLang`, `default`, and `kind` attributes for `<track>` elements
- Added support for `color` attribute
- Ensured legacy `.props` access on DOM nodes is updated on re-renders

### React Test Utils Add-on 
- Fixed `scryRenderedDOMComponentsWithClass` so it works with SVG

### React Transition Group Add-on
- Fix bug preventing `0` to be used as a timeout value

### React on Bower
- Added `react-dom.js` to `main` to improve compatibility with tooling

* * *

- [x] cherry-pick the commits
- [x] finalize changelog
- [x] ship it
- [ ] update fiddles

**Comment by yiminghe** [comment]
#5237

**Comment by zpao** [comment]
Good catch, got closed after I started making the list.

**Comment by zpao** [comment]
Will update the fiddles and whatnot soon but in the mean time, go forth. http://facebook.github.io/react/blog/2015/10/28/react-v0.14.1.html
