### ISSUE TITLE
Issue with documentation - HTML entities

### ISSUE THREAD

**Issue by ffxsam** [facebook/react#5305]
https://facebook.github.io/react/docs/jsx-gotchas.html#html-entities

Regarding this:

    <div>{['First ', <span>&middot;</span>, ' Second']}</div>

This creates a warning:

>Warning: Each child in an array or iterator should have a unique "key" prop.

Probably not a good idea for the manual to be encouraging a syntax that yields warning messages. Is there another approach for this?

**Comment by zpao** [comment]
There were a number of approaches presented there. Yet another is to just do everything as JSX, assuming 'First' and 'Second' are there to demonstrate "dynamic" content:

```js
<div>{'First '}<span>&middot;</span>{' Second'}</div>
```

While yes, a warning is not ideal (and I'm actually a little surprised there is a warning, cc @spicyj), the goal is to demonstrate how you can begin to solve the specific issue of entities in dynamic content with as little code as possible. I'm ok with there being a warning in simple code snippets if it gets the point across without having to then explain other things.

**Comment by spicyj** [comment]
@zpao Sorry, why wouldn't there be a warning?

**Comment by zpao** [comment]
text, <span>, text - which yes renders down to all the same things but I thought our warning about keys only looked at arrays of the same type or something (since you don't actually need keys when they are different types). But looks like we warned in 0.13 so meh.
