### ISSUE TITLE
Accept 'color' property in link tag

### ISSUE THREAD

**Issue by alexcris-m** [facebook/react#5307]
In order to use safari's pinned size tab icon, we need something like:

```
<link rel="mask-icon" sizes="any" href="./icon.svg" color="#777777>
```

But react doesn't support the `color` property. Why not to support it? Or is there any other way to handle this?

**Comment by zpao** [comment]
Just added in #5304. It will be a part of 0.14.1

**Comment by alexcris-m** [comment]
Thanks.
