### ISSUE TITLE
ReactDOMServer 0.14.0 doesn't eval on Java 8 Nashorn JavaScript Engine

### ISSUE THREAD

**Issue by aantono** [facebook/react#5311]
With the release of 0.14.0 and the modular split, the use of ```ReactDOMServer.renderToString(...)``` in the code instead of the original ```React.renderToString(...)``` results with an error in Nashorn, as it does not support any module system, so it is not possible to execute the suggested ```require('react-dom/server')```.

The code for testing was obtained from here and modified to use version 0.14.0 instead of 0.13.1 - https://github.com/sdeleuze/spring-react-isomorphic
This is being executed on the latest version of Java 8 - 1.8.0_66

Potentially related to #3037
```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Failed to render script template] with root cause
jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "ReactDOMServer" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291) ~[nashorn.jar:na]
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1432) ~[nashorn.jar:na]
	at jdk.nashorn.internal.scripts.Script$Recompilation$779$48AA$\^eval\_#1\!6653\^eval\_.process(<eval>#1:6653<eval>:25) ~[na:na]
	at jdk.nashorn.internal.scripts.Script$Recompilation$777$1754AA$\^eval\_.L:1$render(<eval>:1) ~[na:na]
	at jdk.nashorn.internal.scripts.Script$Recompilation$757$33AA$\^eval\_.render(<eval>:3) ~[na:na]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:644) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190) ~[nashorn.jar:na]
	at org.springframework.web.servlet.view.script.ScriptTemplateView.renderMergedOutputModel(ScriptTemplateView.java:294) ~[spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
```

**Comment by jimfb** [comment]
Yep, sounds like another reason to include renderToString on ReactDOM.  This is also causing problems for testing (jsfiddle), ClojureScript, bower distribution, etc.

**Comment by JaRail** [comment]
Can polyfill Nashorn with a module loader? Something like [jvm-npm](https://github.com/nodyn/jvm-npm)?

**Comment by spicyj** [comment]
Just as for a browser, you can use browserify to create a bundle that Nashorn will understand.

**Comment by Daniel15** [comment]
> Can we polyfill Nashorn with a module loader?

It's easier to just build a bundle at compile time :)

> Just as for a browser, you can use browserify to create a bundle that Nashorn will understand.

I think this is the approach I'll be taking for [ReactJS.NET](http://reactjs.net/). Currently I'm still using `React.renderToString` and [ignoring the deprecation error](https://github.com/reactjs/React.NET/blob/50e3ed94a66cc4e19f98146501910f3629444976/src/React.Core/Resources/shims.js#L26-L30), but that's super janky.

**Comment by JaRail** [comment]
Is there anything actionable left? It sounds like this is by design. Is there debug code to detect bad environments that could be updated to check for the existence of required globals?

**Comment by spicyj** [comment]
@JaRail I'm not sure what you mean, but no, there's nothing actionable here.

**Comment by JaRail** [comment]
I just mean a guard.
```
if (DEBUG && !require) { throw new Error("You need a module loader."); }
```
Thanks Ben.

**Comment by spicyj** [comment]
React doesn't use require internally so I don't think that would make much sense. I'm hopeful that people who write a `require()` call and immediately see that it doesn't work will realize that they need a module loader.

**Comment by aantono** [comment]
So what would be a proposed solution for handling this for a Nashorn Java 8 environment?

**Comment by spicyj** [comment]
You should use a module bundler like browserify to make a single bundle that you can load, much like people do when using React from npm and sending the result to a browser. It sounds like something like jvm-npm might work too.

**Comment by JaRail** [comment]
@Download I don't have the knowledge to address everything you said directly. But two things do jump out at me.
* You shouldn't be using a CDN for server-side code. At worst, it should be downloaded from the CDN when you deploy your application/service. Relying on caching would be a poor way to justify this. You really do want to put React through webpack along with everything else for the server-side bundle. In the browser, it's absolutely fine to use the CDN. I'd be a little surprised if this caused issues with dev builds. Nashorn doesn't have hot reloading (as you'd get with webpack-dev-server) but a watch-build should still be pretty quick. Even if you had to write an extra MB of js, a watch build keeps that in memory. It takes a fraction of a second to write a MB to disk. Also, even if you don't include React in a bundle, you still want it available to the bundler to perform as much static analysis as it can. 
* This really isn't a Java/Nashorn dev vs browser/Node dev issue. There is a lot of long-term thinking that goes into how these modules are being broken down. A lot of code gets included for backwards compatibility but will be removed in the future. I don't think ReactDOM will contain everything required for ReactDOMServer in the future. I'm a huge fan of the Nashorn project. It has a long way to go but I'm also invested in seeing it succeed. It's also great to see a new JS engine built with such a unique perspective. There's a lot of potential there that doesn't exist in Node. That said, it's very new and lightly supported. The Nashorn community needs to accept that to a certain extent, there are a lot of existing patterns that still need to be followed if they want to support Node modules.

**Comment by spicyj** [comment]
Most people using React are targeting a browser, which also doesn't support `require` natively. We highly recommend using a CommonJS system like browserify/webpack/etc to manage your assets regardless of what platform you're targeting.

> I mean if you grab the bundled version of ReactDOM, ReactDOMServer is already in there. It's just not exposed. That's very silly actually isn't it? This bundle contains code that can never be used...

This is true in the current release but will not be true in future versions.

**Comment by Download** [comment]
> You shouldn't be using a CDN for server-side code.
I'm not. But I am using a CDN for the browser, so my bundle does not contain React and ReactDOM. So I have to build an extra bundle specifically for the server... Extra work.

> The Nashorn community needs to accept that to a certain extent, there are a lot of existing patterns that still need to be followed if they want to support Node modules.
But since when is React a 'Node module'? That `require` **must** be used to get at the API is new. Up till previous release everthing was reachable through global.

I am still interested in hearing the why:

Simply adding
```js
ReactDOM.ReactDOMServer = ReactDOMServer;
```
at the right place in the ReactDOM code would solve this and not require Nashorn users to polyfill CommonJS modules.

I believe that you guys just want to build the best possible system. And Nashorn isn't an important target for React. But still, there surely is a good reason to make us jump through these hoops?

So what is it?

**Comment by Download** [comment]
Mmmm I love what I see [here](https://github.com/facebook/react/pull/5381)!

Seems you guys are going to address this. Thank you!!!
