### ISSUE TITLE
bugs in react-addon-update's $push and $unshift

### ISSUE THREAD

**Issue by arolson101** [facebook/react#5312]
the handlers for COMMAND_PUSH and COMMAND_UNSHIFT should return their new values, rather than let it fall into the for loop at the end.
```
  if (hasOwnProperty.call(spec, COMMAND_PUSH)) {
    invariantArrayCase(value, spec, COMMAND_PUSH);
    spec[COMMAND_PUSH].forEach(function(item) {
      nextValue.push(item);
    });
    return nextValue; // <-- here
  }
```
Also, the arguments to $unshift end up in the reverse order because they're unshifted one at a time rather than all at once.  It should be:
```
  if (hasOwnProperty.call(spec, COMMAND_UNSHIFT)) {
    invariantArrayCase(value, spec, COMMAND_UNSHIFT);
    nextValue.unshift.apply(nextValue, spec[COMMAND_UNSHIFT]); // <-- unshift all arguments at once
    return nextValue; // <-- same issue as above
  }
```

**Comment by arolson101** [comment]
also $splice and $merge should return nextValue

**Comment by gaearon** [comment]
We won't be changing how `update()` works.
Please consider filing these in https://github.com/kolodny/immutability-helper instead.
