### ISSUE TITLE
Select input box / combobox gets inconsistent internal state in Firefox

### ISSUE THREAD

**Issue by ezufelt** [facebook/react#5315]
Using 0.14 on latest Firefox.

Given the following:

```
getInitialState: function () {
  return {select: 'a'};
},
handleChange: function (event) {
  this.setState({select: event.target.value});
},
render: function () {
  return (
    <select value={this.state.select} onChange={this.handleChange}>
      <option value="a">Apple</option>
      <option value="b">Banana</option>
    </select>
  );
}
```

When I select Banana
- The state is updated
- selected="" is removed from Apple and added to Banana

The visual option in the select box remains Apple.

**Comment by ezufelt** [comment]
This does not appear to be a problem for Safari and Chrome on OS X, but does exist with Firefox on Windows.

I will note that I am using a screen-reader, but get the same results using two different screen-readers for Windows with Firefox.

**Comment by ezufelt** [comment]
I confirmed that this is a problem in Firefox on OS X as well. Someone has visually confirmed that the value appears correct "Apple", but the accessibility API is not reflecting the updated value.

**Comment by jimfb** [comment]
Can you elaborate on what you mean by "accessibility API"?  Where are you seeing the wrong value?  Is the issue that the screen reader is verbally reading off the wrong value?

cc @spicyj Maybe the screen reader is looking at the attribute instead of the property?

**Comment by jimfb** [comment]
A fiddle for my own sanity, and @spicyj's convenience.  https://jsfiddle.net/b4pe8jhn/

**Comment by ezufelt** [comment]
Thanks for looking at this. Fiddles don't work super well for me, but I was able to fork / modify what you had provided.

https://jsfiddle.net/ow2cq9ok/

The part I believe I forgot to mention is the reset button. When you reset the value, without interacting with the component, the screen reader still reads the previously selected option, even though Firebug shows that the first option is selected.

I posted out to Twitter and ideally a Firefox accessibility engineer can take a look to provide further diagnosis.

**Comment by jimfb** [comment]
Your fiddle calls setState from within render, which is against the rules.  I updated the fiddle.

https://jsfiddle.net/kqfvafuk/

Based on your latest description, are you thinking that it's a bug in React or a bug in Firefox?  I'm still not entirely clear on how we can best reproduce the issue / see what value is being supplied by the accessibility API.

**Comment by ezufelt** [comment]
Thanks, I forgot to put that in as a callback.

I'm going to see if one of the Firefox accessibility team can take a look to provide some insight.

**Comment by MarcoZehe** [comment]
I don't understand which steps I would need to reproduce the bug or not. From my point of view, the reset button doesn't appear to do anything. So no matter if I select Banana or Apple in the Combo Box, then shift+tab to the Reset button and press SpaceBar, that same value is still selected in the combobox when I tab forward to it again. Pressing up or down arrow confirms that the combobox thinks the value I selected last is still selected. So, when I do this:

1. Tab to the combobox and selectApple.
2. Shift+tab to Reset and press SpaceBar. This should, if I understand correctly, reset to Banana.
3. Tab forward to the combo box. 

Result: Apple is still selected even for just keyboard interaction, which has nothing to do with the accessibility APIs. I would think that, if this would work as expected, keyboard focus should be on Banana each time I press Reset. But it isn't, and this is, again, even without NVDA's virtual mode at play. The accessibility APIs only reflect what is selected. They don't actively change the selection when the widget is manipulated from JavaScript.

So either the React code doesn't set the keyboard focus in the select element in any case, or the Firefox combobox widget, which is not part of the accessibility APIs, does not react properly to what React is trying to do.

**Comment by ezufelt** [comment]
Hi Marco

Thanks for taking a look.

When you select Banana, and then press reset, the value should return to Apple. My experience is the same as yours using NVDA and JAWS for FF on Windows and VoiceOver using FF on OS X. I will not that the selected attribute moves to Apple when the reset button is pressed, but the screen-readers continue to read Banana.

**Comment by MarcoZehe** [comment]
The point is that not only screen reaers see the selection still on the last focused one, but keyboard focus does, too. So even without a screen reader, keyboard focus will show the last selected one, for example Bananas, when it should revert to Apple.

**Comment by jimfb** [comment]
I can confirm that internal state of the internal state of the firefox combobox appears to be inconsistent when the value is set from javascript; this appears to be a bug in firefox and is independent of the screen readers.

I can also confirm that it doesn't matter if we use attributes or properties; the inconsistency in firefox appears to be persistent.

I can also confirm that the combobox behavior differs from user expectations given what is visually rendered.  Realistically though, this is looking like a bug in Firefox and I don't see anything actionable on our end, unless someone sees a workaround.

**Comment by jimfb** [comment]
Perhaps @zpao can ping someone at mozilla.

**Comment by MarcoZehe** [comment]
Feel free to file a bug, preferably with a testcase attached to it, in [https://bugzilla.mozilla.org](Bugzilla), product Core, component Widgets, and CC :marcoz (that's me). I won't be the one fixing the bug, but I can provide input if necessary and help colleagues.

**Comment by jimfb** [comment]
Ok, I found a workaround.  It appears that setting `a.selected = true` is insufficient but that setting  `a.selected = false; a.selected = true` does work.  Fiddle: https://jsfiddle.net/otgxg4av/

Pure speculation based on zero knowledge of firefox code: this leads me to believe/suspect that Firefox is trying to be fancy and bail out of a change if the value is unchanged, but their cached value is incorrect and thus they erroneously bail out.

Anyway, we now have a potential workaround.  #goodfirstbug.

**Comment by jimfb** [comment]
I also filed a bug with mozilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1219825) though I don't have the time to follow it closely.

**Comment by ezufelt** [comment]
@jimfb  thanks for looking in to this.
Click reset
press tab to focus on the combobox
use arrow keys to select banana
use shift+tab to go back to the reset button
press spacebar to press the button and activate the hard reset

- At this point my screen-reader still reads "Banana"

press tab to go back to the combobox
press down arrow
Observe that combobox value went from "Apple" to "Candy" without passing through "Banana"

- I can move to all 3 options.

**Comment by jimfb** [comment]
@ezufelt I think there are minor differences in what you observe and what I observe.  Possibly because I'm on FF 41 (not latest) or possibly because you have a screen reader.  But either way, I think the description is sufficient to be actionable.  You might want to put your additional info into the bugzilla report.

**Comment by zpao** [comment]
Ultimately it looks like this boils down to a Firefox bug that doesn't affect just React so I'm not sure how much we should do in React. If somebody comes along and wants to pick this up, let's make sure we should do anything before you start.

Firefox, like Chrome and others, doesn't commit the visual change until enter is pressed. However, because Chrome pops the options into a new view which you can't dismiss without committing or canceling, it can't get stuck in an inconsistent visual state. The goal of all of this is probably to not fire a change event on every key stroke here, simulating what the event stream would look like if interacting with a mouse (you don't select every intermediate value).

Thanks everybody for the report and tracking it down, getting a bug filed in Bugzilla.

**Comment by gaearon** [comment]
I’m closing this as stale. If this is something we should fix in React please let us know.
