### ISSUE TITLE
Weird components that can not be referred

### ISSUE THREAD

**Issue by mayagamer** [facebook/react#5318]
I use React and Material-UI for my app.
Here is the part of code:

      render(){
        return <div>
           <Table ref='fromform'>
             <TableHeader>
          <TableRow>
            <TableHeaderColumn tooltip='The ID'>No.</TableHeaderColumn>
            <TableHeaderColumn tooltip='The Name'>Name</TableHeaderColumn>
            <TableHeaderColumn tooltip='The Status'>Notes</TableHeaderColumn>
          </TableRow>
        </TableHeader>
        <TableBody ref='fromformb'>
          {playerList.map(function(player, index){
              return <TableRow onTouchTap={this._onShowInfo.bind(this, index)} key={'row' + index}>
                <TableRowColumn>{index + 1}</TableRowColumn>
                <TableRowColumn>{player.name}</TableRowColumn>
                <TableRowColumn>{player.notes}</TableRowColumn>
              </TableRow>;
          }.bind(this))}
        </TableBody>
      </Table>
      <Dialog
        title='Player Info'
        ref='playerInfoDialog'>
        <form role='form' ref='fromfo'>
          <div className='form-group' ref='frowwmformb'>
            <TextField type='text' hintText='Player Name' ref='txtName' fullWidth={true} />
            <TextField type='text' hintText='Notes' ref='txtNotes' fullWidth={true} />
          </div>
        </form>
      </Dialog>
      <MainButtonGroup page='players' />
      <Spinner />
    </div>;
      }
  
      _onShowInfo(index){
        var player = playerList[index];
        console.log(this.refs);
        this.refs.playerInfoDialog.show();
        this.refs.txtName.setValue(player.name);
        this.refs.txtNotes.setValue(player.notes);
      }
    }

What I want to do with this code is to generate rows in a table of player list, and while a row is tapped, a dialog shows up with the data of the row.

But the two 'TextField's with refs of 'txtName' and 'txtNotes' can't be referred(as on the last 2 lines, produce errors)
. The pic below is produced by 'console.log' in '_onShowInfo' method. I added some 'ref's with random names just to test.

![ee77834e-7a46-4734-8480-2464e1d65382](https://cloud.githubusercontent.com/assets/1431032/10785424/1588a5b8-7d9f-11e5-8b47-4c8ad4c2828a.png)

**Comment by jimfb** [comment]
I don't think there is enough information here for us to debug.  Keep in mind that we try to use github issues to track bugs in React.  Usage questions are better answered on StackOverflow.  If you believe there is a bug in the React core, please provide a simplified testcase/jsfiddle that demonstrates the issue and we can dig further.

**Comment by mayagamer** [comment]
I found a solution. Change _onShowInfo as below:

      _onShowInfo(tid){
        var player = PlayersService.reqPlayer(tid);
        this.refs.playerInfoDialog.show();
        setTimeout(function(){
          console.log(this.refs);
          this.refs.name.setValue(player.name);
          this.refs.notes.setValue(player.notes);
        }.bind(this), 0);
      }

But I don't know why.

**Comment by jimfb** [comment]
Sounds like maybe you weren't binding functions properly or something.  Sounds like a usage question which are better addressed on other sites.  If you believe this is a bug in the React core, let us know, and please provide a simplified jsfiddle that demonstrates the issue.

**Comment by zpao** [comment]
It's not binding. It's probably an issue of timing. I don't know what your Dialog component looks like but it probably has its own render root (calls ReactDOM.render, probably in show()), resulting in the ref resolution not being timed quite right because they don't exist until the end of the event loop, which is why `setTimeout` works.

You might be able to take advantage of the callback that render takes to thread a callback through show()

eg: `show(cb) { ReactDOM.render(whatever, cb) }`

**Comment by mayagamer** [comment]
Thanks zpao!  I totally get it.
