### ISSUE TITLE
dangerouslySetInnerHTML escapes slashes

### ISSUE THREAD

**Issue by zkirill** [facebook/react#5319]
`\/` gets turned into `/`

Is it possible to avoid this?

**Comment by jimfb** [comment]
Are you sure you're not just confused by javascript's string escape character?

This string contains only a single slash:
```
var str = '\/';
console.log(str);
```

This string contains two characters:
```
var str = '\/';
console.log(str);
```

If you believe this is a bug in React, please provide a simple testcase / jsfiddle that demonstrates your issue, we can investigate further.  We use github issues to track bugs in the React core.  Usage questions are better addressed on other sites.

**Comment by zkirill** [comment]
You're right, thank you. I had to escape the slashes contained inside Mixpanel's Javascript API integration code (`/^\/\//`) in order to place it within `<head>`.
