### ISSUE TITLE
ReactCSSTransitionGroup should warn if the children weren't provided a key attribute

### ISSUE THREAD

**Issue by petetnt** [facebook/react#5322]
As the docs state:

> You must provide the key attribute for all children of ReactCSSTransitionGroup, even when only rendering a single item. This is how React will determine which children have entered, left, or stayed.

As the key-attribute is mandatory for the animations to function, it would make sense to warn if the key props are missing for the direct children, similarly how dynamic children warn about missing keys.

Something like: 

>  Each child in ReactCSSTransitionGroup should have a unique "key" prop. Check the render method of foo

**Comment by gaearon** [comment]
While the docs claim it is necessary, it doesn’t appear to be in my testing. I can put a single child conditionally inside `ReactTransitionGroup` and animate its (un)mounting without assigning a specific key to it. Is that not the case in your testing? Perhaps we should amend the docs.

**Comment by petetnt** [comment]
@gaearon It's mostly an issue where you want to change the (whole) content inside the group altogether. 

See this example: https://jsfiddle.net/gw5w30m8/1/

In the example we are animating the contents in and out: without having explict keys, React can't figure out which item is animating out and which is in: animations just plain stop working. Assign (any unique) keys to the children and everything works as intended. Just adding and removing things works regardless of keys being there or not (see the https://facebook.github.io/react/docs/animation.html example).

Not sure if that's the intended use-case for `ReactCSSTransitionGroup` though, but it's an use-case I ran into a lot.

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by petetnt** [comment]
Thanks for the heads up @gaearon 👍
