### ISSUE TITLE
0.14.1 not fire click event on Internet Exproler and Windows 8 or 7

### ISSUE THREAD

**Issue by inuscript** [facebook/react#5324]
Count up with 0.14.0
http://inuscript.github.io/react-0-14-bug/0-14-0.html

But can't count up 0.14.1
http://inuscript.github.io/react-0-14-bug/0-14-1.html

I got this issue on IE 10 and 11 + Windows 8, 7.
And Windows 10 + IE 11 is move fine.

**Comment by ZachBray** [comment]
:+1:  I'm seeing the same issue when I use react-dom 0.14.1

**Comment by DimitarChristoff** [comment]
:+1:

**Comment by jimfb** [comment]
cc @spicyj, seems bad.

**Comment by jimfb** [comment]
@zpao

**Comment by zpao** [comment]
Fix incoming. Worth noting (as @spicyj reminded me) that this is only an issue in dev mode.

**Comment by Neaox** [comment]
:+1:

**Comment by nzbart** [comment]
:+1: Makes our app difficult to test on Windows 7 / 8.

**Comment by zpao** [comment]
Yea sorry about the issues, we'll be shipping 0.14.2 tomorrow with this fixed.

**Comment by mwkang** [comment]
:+1:

**Comment by chadwpry** [comment]
Is this related only to anchor tags, or other elements as well? I've seen this when applying onClick to div elements as well as anchors in IE10 and IE11.

**Comment by spicyj** [comment]
All elements.
