### ISSUE TITLE
IFrame onLoad event handler is not called in Chrome for non-HTML documents

### ISSUE THREAD

**Issue by varungupta85** [facebook/react#5332]
IFrame onLoad event handler  is called in Firefox but not in Chrome. I am using Firefox v41 and Chrome v46 and react v0.14.0. The 'load' event is fired in both Chrome and Firefox but the onLoad event handler is only called in Firefox. Here is a jsfiddle demonstrating the issue.

https://jsfiddle.net/varungupta85/xa1m0aLk/

If you open it in Firefox, you will observe that a dialog box appears to save/open the file and the iframe disappears. But in Chrome, the iframe doesn't disappear. When I tried to run the code in debugger, the control never goes to the onLoad event handler in Chrome.

**Comment by jimfb** [comment]
Your example is still really complicated and I'm suspecting the error is somewhere in your code since onLoad works in my jsfiddle: https://jsfiddle.net/65zfsqwy/

Can you simplify / create a minimal test case and post a link to a new fiddle?

**Comment by zpao** [comment]
To better simulate the same thing @varungupta85 is doing, just change the `src` to the same file. You'll see the same behavior. But using an html document will work correctly.

It appears that Chrome isn't firing the load event and is just initiating a file download. It's unclear which behavior is actually correct or if we can do anything about this.

**Comment by varungupta85** [comment]
Thanks @zpao . @jimfb I have created a new jsfiddle using what @zpao has mentioned.

http://jsfiddle.net/varungupta85/0a8kL003/

If you open the jsfiddle in firefox, you should see the alert but not in chrome.

A little bit on my use case: I am trying to create a component which will display the src file in the iframe if it can be rendered by the browser for e.g. pdf files. If the file can't be rendered by the browser, the user can download/open the file in some third party program and the iframe will disappear.

**Comment by schovi** [comment]
@varungupta85 This seems to be general issue in Chrome when you open url which send file. Check this example http://jsfiddle.net/0a8kL003/2/ which fails. When you open Google or other page it is fine http://jsfiddle.net/0a8kL003/3/

**Comment by jimfb** [comment]
AFAIK, there is nothing actionable here.  Assuming I'm understanding the comment correctly, this is browser behavior, and there isn't anything on our end.
