### ISSUE TITLE
Warn if people pass in "mutated" props

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5335]
Having the constructor passing super a props object that differs (in object equality and/or shallow compare) from the original is... illegal, because: https://github.com/facebook/react/pull/5334

We should have a warning for that, because it's reasonable for someone to assume they could extend a component and modify the props, without considering the ramifications, and the bug won't show up in their initial render test but will show up when the component updates.

**Comment by prometheansacrifice** [comment]
@jimfb  Can a shallow comparison of `inst.props` and `publicProps` suffice, or is a deep equality check between the two objects needed?

**Comment by jimfb** [comment]
I think shallow is fine.  Deep equality is too difficult/expensive because of cycles.

Note that we should only do the check in dev mode, so surround your logic with a `if(__DEV__)` block
