### ISSUE TITLE
Support "invalid" event

### ISSUE THREAD

**Issue by simonewebdesign** [facebook/react#5337]
Hi, just wondering if the [invalid](https://developer.mozilla.org/en-US/docs/Web/Events/invalid) event is currently supported?

I tried using something like:

``` javascript
handleInvalid(event) { ... }

<input type="text" onInvalid={this.handleInvalid} />
```

But it doesn't work. I have to manually attach the event handler to the actual DOM node in order to get it working. 

So, is the *invalid* event actually supported? 

If not, any plans on supporting it?

**Comment by jimfb** [comment]
I don't see it on the list: https://facebook.github.io/react/docs/events.html

Yes, it would be good to support all the browser events.  Would you like to submit a PR?

**Comment by zpao** [comment]
This was added recently but is not a part of a release. https://github.com/facebook/react/pull/5187
