### ISSUE TITLE
0.14.1 performance issues

### ISSUE THREAD

**Issue by rmilesson** [facebook/react#5338]
Heya!

We're upgrading to React 0.14.1 and when using that in conjunction with [Fixed Data Table](https://github.com/facebook/fixed-data-table) we seem to have taken a real performance hit. What I can see, Fixed Data Table has not changed anything other than using the ReactDOM.render function instead of React.render when upgrading to React 0.14.

What's going on?

**Comment by zpao** [comment]
Without more info, I'm don't think we can tell you what's going on. We haven't heard any complaints from the people using it at FB. You might want to do a bit of debugging yourself or work with the folks from working on FDT.

I'm going to close out for now but if we get something concrete to go on, we can reopen.
