### ISSUE TITLE
Is it ok to not using Flux?

### ISSUE THREAD

**Issue by huytd** [facebook/react#5340]
Hi everybody, 

I'm just started learning React recently, and often found myself lost in the limbo when reading about Flux. 
I know it's just the concept about the application architecture to develop website with React.
But I have an idea that use routing with Express and use React for rendering the view only.
Is it a good solution? And should I abandon Flux? 
Is there any reason why we should use Flux?

Thanks,
Huy

**Comment by iamdustan** [comment]
1. Totally cool not to use flux.
2. General questions are great in https://discuss.reactjs.org/, http://reactiflux.com/, or http://stackoverflow.com/questions/tagged/reactjs

**Comment by jimfb** [comment]
@iamdustan Couldn't have said it better myself.  Yes, totally ok to use React without flux.  Yes, please use sites like StackOverflow for usage questions, since we use github issues to track bugs in the React core.

**Comment by huytd** [comment]
Thank you so much!
