### ISSUE TITLE
ReactErrorUtils.invokeGuardedCallback appears not work in MS Edge

### ISSUE THREAD

**Issue by timgardner** [facebook/react#5345]
It looks like Edge doesn't like that fakeNode isn't attached to the body.
If I append it to the body, then remove after removing the listener, all is good.
Obviously in a production build this isn't an issue as handler is called directly.

This was for a 'click' event.

**Comment by jimfb** [comment]
I'm assuming this is a duplicate of https://github.com/facebook/react/issues/5324

cc @spicyj

**Comment by timgardner** [comment]
Correct.  Apologies I searched but obviously not well enough.  However is there any issue with actually appending the fakeNode to the body then using the native event type? I assume this was the intent based on the comments.
  
/**
   * To help development we can get better devtools integration by simulating a
   * real browser event.
   */

**Comment by zpao** [comment]
Maybe if we left the node attached to the body forever that could work. But that wouldn't be ideal. Constantly inserting and then removing on each event also wouldn't be ideal either(probably worse).

I think as long as we get the benefits, what we're doing now is fine.

If you could test with a build from master (http://react.zpao.com/builds/master/latest/) and make sure things are working in Edge, that would be awesome!

**Comment by timgardner** [comment]
Working with Edge under sufferance... But yes this fix works fine!

**Comment by zpao** [comment]
Thanks for testing @timgardner!
