### ISSUE TITLE
Prohibited component names?

### ISSUE THREAD

**Issue by folivi** [facebook/react#5347]
Hi all, 

are the any list of reserved class names?

I had an issue with a component I named Event
It was included in a EventsList component.
When I tried to filter the list, I got this error:

```code 
TypeError: Argument 1 of EventTarget.dispatchEvent does not implement interface Event.	
fakeNode.dispatchEvent(new Event(name));
```
Are there any other reserved names?

Cheers

**Comment by edvinerikson** [comment]
Can you please provide a jsfiddle/repro? I couldn't reproduce it (I may have misunderstood something..).
https://jsfiddle.net/69z2wepo/19608/

**Comment by folivi** [comment]
Hi, I quickly pasted my code to the fiddle.
to be more precise:
I have a EventsList component containing a text field for filtering. The list renders a collection of Event compent which can be filtered.
The issue comes with the Event component.
The error disapears when I use any other name for my component.
I'm in a rails application

**Comment by edvinerikson** [comment]
I can still not reproduce the error you had. The only thing I can think of is that the component is overriding the native `Event` object but that shouldn't be happening.

https://jsfiddle.net/69z2wepo/19612/

**Comment by zpao** [comment]
You're almost definitely overriding `window.Event`, especially if you're in a Rails env where basically every component becomes a global (at least out of the box). You may want to look into a module system so that your variables don't leak out from each file.

**Comment by zpao** [comment]
Oh and to answer the root question, no there are no reserved component names.

**Comment by folivi** [comment]
Great!
Thanks to both of you!
