### ISSUE TITLE
react-native init error

### ISSUE THREAD

**Issue by limerickgds** [facebook/react#5359]
i use react-native init ,but have this problem. github.com[0: 192.30.252.130]: errno=Operation timed out my node version is 4.0.0;

but i can ping github.com to be successful.

Installing react-native package from npm...

npm ERR! git clone --template=/Users/guods/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/guods/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: Cloning into bare repository '/Users/guods/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b'...
npm ERR! git clone --template=/Users/guods/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/guods/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/guods/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/guods/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: github.com[0: 192.30.252.130]: errno=Operation timed out
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/guods/git/nvm/versions/node/v4.0.0/bin/node" "/Users/guods/git/nvm/versions/node/v4.0.0/bin/npm" "install" "--save" "react-native"
npm ERR! node v4.0.0
npm ERR! npm v2.14.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/guods/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/guods/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b
npm ERR! Cloning into bare repository '/Users/guods/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Operation timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /Users/guods/project/testReact/npm-debug.log

ping github.com
PING github.com (192.30.252.130): 56 data bytes
64 bytes from 192.30.252.130: icmp_seq=0 ttl=42 time=285.963 ms
64 bytes from 192.30.252.130: icmp_seq=1 ttl=42 time=437.400 ms
64 bytes from 192.30.252.130: icmp_seq=2 ttl=42 time=465.788 ms

**Comment by zpao** [comment]
If you can reproduce this you may want to file an issue against react-native (https://github.com/facebook/react-native). We're not directly involved with their `init` process.
