### ISSUE TITLE
Event handlers & Shadow DOM

### ISSUE THREAD

**Issue by Yomguithereal** [facebook/react#5363]
Hello React. I am currently trying to make events work for React components rendered within a Shadow DOM and find that by putting back those commented [lines](https://github.com/facebook/react/blob/401e6f10587b09d4e725763984957cf309dfdc30/src/renderers/dom/client/ReactEventListener.js#L64-L77) do work.

Is there a way to enable this from outside the library right now, using some kind of injection such as the ones performed by ReactDOM, for instance?

**Comment by spicyj** [comment]
No, we don't support this currently because the spec is still in flux (and there hasn't been much demand for it).

**Comment by Yomguithereal** [comment]
Thanks for the answer @spicyj.

**Comment by Yomguithereal** [comment]
Just to provide some context to this, I am using Shadow DOM to enable CSS encapsulation. My aim is to build an interface enabling its user to easily prototype react components and need the use style/css to be encapsulated so that it would not spill over the given interface.

**Comment by gaearon** [comment]
This should be fixed in React 17 RC.
https://reactjs.org/blog/2020/08/10/react-v17-rc.html
