### ISSUE TITLE
OnClick in <a> tag not working in IE11 after update to 0.14.1

### ISSUE THREAD

**Issue by DanielSundberg** [facebook/react#5364]
None of my onClick handlers are working in development mode after updating from 0.14.0 to 0.14.1 using IE11. 

When reverting the code that was changed in ReactErrorUtils.js for #5157 I get the onClick handler working again.

**Comment by clementdubois** [comment]
Same issue with IE9 here is an exemple : 

    render : function render() {
      return (
        <div>
          <span onClick={() => alert("ok")}>OK</span>
        </div>
      );
    },

Wokrs well on chrome but nothing append on IE9 since 0.14.1 (0.14.0 is ok)

**Comment by iamdustan** [comment]
Likely duplicate of #5324, fixed in #5328. Will be shipped in React [0.14.2](https://github.com/facebook/react/milestones/0.14.2)

**Comment by DanielSundberg** [comment]
Ok, sorry, I tried to search but didn't find that one..

**Comment by iamdustan** [comment]
:thumbsup: no worries.
