### ISSUE TITLE
PropTypes nesting

### ISSUE THREAD

**Issue by jadekler** [facebook/react#5365]
Hey there,

We're using redux and putting all of our actions into this.props.actions. Unfortunately this makes it hard to use PropTypes, because we're lacking the ability to nest with PropTypes - something like:

```
PaymentPage.propTypes = {
    actions: {
        fetchPaymentInfo: PropTypes.func.isRequired,
        fetchPaymentMethods: PropTypes.func.isRequired
    },
    (normal state goes here and works fine)
}
```

Is there a solution for this, or a feature upcoming?

**Comment by jimbolla** [comment]
you can with shape():

    PaymentPage.propTypes = {
        actions: PropTypes.shape({
            fetchPaymentInfo: PropTypes.func.isRequired,
            fetchPaymentMethods: PropTypes.func.isRequired
        }),
        (normal state goes here and works fine)
    }

**Comment by zpao** [comment]
Thanks for the answer @jimbolla!

**Comment by jadekler** [comment]
Aha, thank you!
