### ISSUE TITLE
React 0.14 Objects invalid children

### ISSUE THREAD

**Issue by ryanflorence** [facebook/react#5371]
Why can we have functions be children but not objects?

In react router you can have multiple route components, in such cases instead of `this.props.children` you'd get `this.props.children[name]`.

This makes building abstractions much easier so that you always know where to find the components.

So, why functions but not objects?

**Comment by spicyj** [comment]
I'm not sure what you mean. Can you post a code sample?

**Comment by gorangajic** [comment]
@ryanflorence it's possible to pass objects like this
```javascript
var Parent = React.createClass({
    render: function() {
        return (<Child>{{
	    foo: "bar"
        }}</Child>);
    },
});

var Child = React.createClass({
    componentDidMount: function() {
    	console.log(this.props.children.foo); // bar
    },
    render() {
		return <span />;
	}
});
```

**Comment by spicyj** [comment]
Closing unless I hear back.
