### ISSUE TITLE
Documentation Issues with react-addons-shallow-compare Package

### ISSUE THREAD

**Issue by zramaekers** [facebook/react#5378]
We were previously using the `shallowEqual` method from the react/lib implementation, which was used in the following way:

```
  shouldComponentUpdate(nextProps, nextState) {
    return !shallowEqual(this.props, nextProps) || !shallowEqual(this.state, nextState);
  }
```

When updating to 0.14, we migrated to using the npm package for 'react-addons-shallow-compare'.
We assumed shallowCompare worked the same way, but anything we passed to shallowCompare was returning true

```
  shouldComponentUpdate(nextProps, nextState) {
    return !shallowCompare(this.props, nextProps) || !shallowCompare(this.state, nextState);
  }
```

After doing some low level testing, even the following was returning true:

```
shallowCompare({value: true}, {value: false});
```

Using the Chrome dev tools I was able to discover the method signature that was expected:

![image](https://cloud.githubusercontent.com/assets/6892184/10912226/16f73f9a-820e-11e5-8408-9e34721b668d.png)

I think we need to better document this method somewhere, either in the npm package page (https://www.npmjs.com/package/react-addons-shallow-compare) or on the addons page (https://facebook.github.io/react/docs/addons.html) to help out others wanting to make this transition.

**Comment by zpao** [comment]
Would you be interested in writing some documentation for the website? If so, let's not reference the previous existence of `shallowEqual` since it was never part of our public API.

**Comment by zramaekers** [comment]
For sure. Where would I start doing that?

**Comment by zpao** [comment]
Awesome!

The documentation and website all live in the repo: https://github.com/facebook/react/tree/master/docs with the bulk of the docs in https://github.com/facebook/react/tree/master/docs/docs. The 10.x pages are the addons docs so you'd want to make a new markdown file around there. There's a readme in the root of docs describing running the server (it's jekyll) so you can test the changes locally.

**Comment by scsper** [comment]
it looks like this issue should be closed :)

**Comment by zpao** [comment]
Thanks, yes it should. I'm following up now and fixing the link in the readme so npm links to the right thing.
