### ISSUE TITLE
Docs on changing the rendering backend?

### ISSUE THREAD

**Issue by trusktr** [facebook/react#5379]
[React-famous](https://github.com/trusktr/react-famous/tree/joe) worked by [creating an invisible DOM structure](https://github.com/trusktr/react-famous/blob/joe/src/Node.jsx#L50-L60) with `display:none`, using componentDidMount and related lifecycle methods to create a Famous Scene Graph (another tree structure) mirroring the structure of the hidden DOM.

But, that is a bit unnecessary, all that extra DOM. I read somewhere that there can be alternate rendering backends. 

Is there some place I can read about this and how to make an alternate rendering backend that would completely ignore DOM in the case of a scene graph? For example, suppose I'd like to make a scene graph with Three.js purely in WebGL, where DOM won't come into play at all.

**Comment by AdrianRossouw** [comment]
Babel supports configuration of jsx pragma - https://github.com/babel/babel/issues/841

**Comment by trusktr** [comment]
@AdrianRossouw That's cool if you want to replace React entirely, but React has a bunch of stuff built in already, like its diffing abilities that I wouldn't want to rewrite. It can basically do things like "hey, the data changed, let me see which objects I need to destroy and create" already, and modify your tree based on the lifecycle methods which I think is really powerful. Re-implementing something like that is too far out of the question for me right now (time wise and interest-wise). If someone wants to do that for our infamous project, I'd be open for that, but I think React's binding of data to tree structure is good enough (as long as we don't rely on that for animating values for transforms since that'd be sloooow, and rely on it only for determining the structure of a scene graph).

**Comment by yaycmyk** [comment]
@trusktr Sounds like you're looking for an explainer on the design pattern and interface of `react-dom`? If so, I'd be interested in this as well.

**Comment by trusktr** [comment]
I guess so, if that's what it is. :}

**Comment by spicyj** [comment]
We don't have a supported way to do this yet. You can look at what react-native and react-art do but the APIs are still frequently changing (which is why we don't support it and haven't documented it). When we've stabilized it, I'm sure we'll publicize it broadly.
