### ISSUE TITLE
No changelog for 0.14.2

### ISSUE THREAD

**Issue by DanielHeath** [facebook/react#5393]
NPM says 0.14.2 is out, but I see no sign of it on github. 

A changelog would help me understand whether I should upgrade now or later.

**Comment by jimfb** [comment]
Change log is here: http://facebook.github.io/react/blog/2015/11/02/react-v0.14.2.html

I'll copy it into the master branch now.

**Comment by zpao** [comment]
Synced over so it's up to date in `master` now.
