### ISSUE TITLE
Document context in stateless functional components

### ISSUE THREAD

**Issue by jacobrask** [facebook/react#5399]
If you set `contextTypes` on a functional component, the second argument of the function is the parent's context. 

Is this undocumented because it is unsupported and unstable behavior, or is it just missing from the documentation (as far as I can tell)?

**Comment by jimfb** [comment]
Probably was just overlooked when writing up the context docs; we can add a note about it to the context page.

**Comment by yangshun** [comment]
I realized that `shouldComponentUpdate` accepts a third argument `nextContext` if `contextTypes` is defined, but I think that isn't documented in https://facebook.github.io/react/docs/component-specs.html. Should that be documented too?

**Comment by jimfb** [comment]
Yes, probably.

**Comment by yangshun** [comment]
Fixed via #5412
