### ISSUE TITLE
100% Code coverage for ReactComponent

### ISSUE THREAD

**Issue by subtleGradient** [facebook/react#540]
These lines are currently not covered by any tests.

https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L151-L155
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L247-L250
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L262-L269
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L270-L273
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L299-L299
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L332-L336
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L339-L339
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L342-L342
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L358-L361
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L364-L364
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L366-L366
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L367-L367
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L368-L368
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L382-L385
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L386-L386
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L387-L387
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L398-L398
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L409-L409
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L412-L412
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L413-L413
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L414-L414
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L415-L415
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L426-L426
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L430-L431
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L433-L435
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L438-L438
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L439-L439
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L455-L455
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L480-L480
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L481-L481
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L493-L493
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L505-L505
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L506-L506
https://github.com/facebook/react/blob/master/src/core/ReactComponent.js#L509-L509

**Comment by ayazhafiz** [comment]
Im on it my dudes
