### ISSUE TITLE
Client side usage of `react-dom/server` API

### ISSUE THREAD

**Issue by kastermester** [facebook/react#5400]
Hi,

I am in the process of migrating our codebase to React 0.14.x. During this I encountered a problem, because of the fact that our client side uses `React.renderToStaticMarkup` to render React components and passing the results around as strings (I know, not ideal, but given what our codebase was previously, this is sadly needed for us in some cases).

However, given my understanding of the structural changes with `react` and `react-dom` packages, as I can tell, I am not supposed to simply call `React.renderToStaticMarkup` any more, and the API is not accessible from the `react-dom` package. I do not use webpack (yet!), so at the moment using `react-dom/server` is not appropriate for me.

What is the supported way (if any?) of calling `React.renderToStaticMarkup` in the browser, using the pre-built packages?

**Comment by gaearon** [comment]
Seems like a duplicate of https://github.com/facebook/react/issues/5159.

**Comment by kastermester** [comment]
@gaearon more or less yes. I did not find that in my crude search before opening this issue, so thanks for finding it. Will close.
