### ISSUE TITLE
API Reference is not very useful.

### ISSUE THREAD

**Issue by rokyed** [facebook/react#5402]
Due to: a lot of text, not explicit explanation, no way to search stuff in the API , makes this library extremely hard to use. It is very hard for someone to read so much. I rather have stuff done.

**Comment by rokyed** [comment]
also some stuff is just unclear, like where to put the event listeners ?

**Comment by rokyed** [comment]
also does it allow me to use " " for string encapsulation on render function because for me is more clear.

**Comment by zpao** [comment]
The rest of our documentation is written in a way that provides more context. The API reference is just that, reference. The tutorial is a good thing to start with to teach you a lot of the core concepts you need to know to use React.

> also does it allow me to use " " for string encapsulation on render function because for me is more clear.

I don't know what you mean by this. Can you clarify?

**Comment by rokyed** [comment]
can i use for example: in the render like this "<div class='something'>Here's my text!</div>" the quotes to encapsulate the html

**Comment by spicyj** [comment]
No. You can call `React.createElement` if you don't want to use JSX.

**Comment by rokyed** [comment]
thanks
