### ISSUE TITLE
Nicer docs site?

### ISSUE THREAD

**Issue by yangshun** [facebook/react#5404]
Have been using React for awhile now and I'm loving it! As a front end developer, I would like to contribute back to the React community.

Would like to ask the React core team if you guys are open to simple re-skinning and prettifying of the docs page http://facebook.github.io/react/? Some ideas I have in mind:

1. Make the sidebar items collapsible: https://github.com/facebook/react/issues/1669
2. Mobile friendly
3. More vibrant color theme.

The changes will not be too drastic; mostly playing with CSS.

An example of my past work in skinning a site: http://rubybench.org/

Let me know your thoughts, I can make a PR to address these issues :smile:

**Comment by spicyj** [comment]
@joecritch was also interested in this. We want to keep at least some semblance of similarity between the different Facebook project sites and we're more concerned about improving the content and organization of the docs than the color scheme. I also don't think there's too much value in making the sidebar collapsible. Mobile styles would probably be okay.
