### ISSUE TITLE
Internet Explorer 9 and ES6 import syntax returns Invalid Component

### ISSUE THREAD

**Issue by iandoe** [facebook/react#5407]
Hey,

Just broke a keyboard or two on this bug: 

It seems that using Babel and the ES6 syntax, if i declare my app this way:
```js
import { Component } from 'react';

class App extends Component {
  render(){
    return(<div>APP HERE</div>);
  }
}
```
*IE 9 throws* : `Invariant Violation: App.render(): A valid ReactComponent must be returned. You may have returned undefined, array, or some other invalid object.`

Whereas if i do 
```js
import React, { Component } from 'react';
```
instead of the previous 
```js
import { Component } from 'react';
```

It works.

USING:

```
React v0.14.2
ReactDOM v0.14.2
```
React is loaded on the page as and shimmed in browserify (could that come from there as well ? )
```json
  "browserify-shim": {
    "jquery": "global:$",
    "react": "global:React"
  }
```

Is this a know bug/feature ? This is causing a world of pain inside my App as it is a pretty big app with a lot of components and higher order components.

Thanks

**Comment by zpao** [comment]
This is odd… On the surface it seems like your code shouldn't be running anywhere.

JSX desugars to React.createElement - `<div />` becomes `React.createElement('div')`. So you generally need `React` in scope. With `import { Component } from 'react';` you don't get React in scope.

Is this only an issue in IE9 but fine everywhere else? Which version of Babel? It might be helpful to have a gist with the minimal repro with your config (multiple-file gists are good for this), and then we can just npm install and repro locally.

Honestly this seems like it's mostly likely somewhere in the combination of babel + browserify + shims, but maybe that in combination with something we're doing is making it worse.

**Comment by iandoe** [comment]
@zpao Thank you for solving that dumb problem, it was in fact a scope problem. React not being included in scope therefore when JSX is desugared to React.createElement it should have thrown an error `React is undefined` which it wasnt throwing because React was in global scope. 

Closing the issue, problem was exotic browserify setup, not React.
