### ISSUE TITLE
How to trigger the eventListener that is registered outside of the react component?

### ISSUE THREAD

**Issue by rubyisapm** [facebook/react#5410]
How to trigger the eventListener that is registered outside of the react component?

**Comment by jimfb** [comment]
> How to trigger the eventListener that is registered outside of the react component?

I'm not sure what this question is asking, but it sounds like a usage question, which is better addressed on other sites.  We use github issues to track bugs in the react core.  Since this is not a bug, I'm going to close it out.  Feel free to continue the discussion here.
