### ISSUE TITLE
onUpdate/onChange/OnInput not working with input type range in IE 11 . Windows 

### ISSUE THREAD

**Issue by sap9433** [facebook/react#5415]
onChange is working in chrome though.

Both of the following in working in chrome and not in IE 11 .(React version "react": "0.13.x",)

```
<input type="range" defaultValue="0.00" min={`${inp.min}`} max={`${inp.max}`} step=".01" onChange={this.handleChange.bind(this, inp.id)}/>
```

```
<input type="range" defaultValue="0.00" min={`${inp.min}`} max={`${inp.max}`} step=".01" onInput={this.handleChange.bind(this, inp.id)}/>
```

**Comment by jimfb** [comment]
Version 0.13.x is out of date, please update to 0.14.2 and retry.

If you are on an older version of 0.14, possibly related to: https://github.com/facebook/react/issues/5323

If (after updating) you still believe this is a bug in the React core, please provide a simple testcase that demonstrates the issue and we can re-investigate.

**Comment by zpao** [comment]
More likely to be related to #554

**Comment by sulmanen** [comment]
looked through events for input type=range on (https://msdn.microsoft.com/en-us/library/windows/apps/hh466182.aspx)[MSDN] using onMouseMove works as expected. 

that fixed the issue for me.
