### ISSUE TITLE
[JSX] Add <Component {property}> shorthand for <Component property={property}>

### ISSUE THREAD

**Issue by denvned** [facebook/react#5419]
Currently JSX supports the following syntax:
```jsx
<Component {...properties}>
```
That works analogously to ES6:
```javascript
var object = {...properties};
```
Below I am proposing to extend this syntax.

In ES6 I can write:
```javascript
var object = {property};
```
as a shorthand for:
```javascript
var object = {property: property};
```
I think that analogous syntax for JSX would be handy:
```jsx
<Component {property}>
```
as a shorthand for:
```jsx
<Component property={property}>
```
and also for:
```jsx
<Component {...{property}}>
```
Furthermore, allowing the following would be even better:
```jsx
<Component {propertyA, ...propertySetA, propertyB: valueB, ...propertySetB}>
```
as a shorthand for:
```jsx
<Component propertyA={propertyA} {...propertySetA} propertyB={valueB} {...propertySetB}>
```

**Comment by syranide** [comment]
Probably best submitted and discussed here: https://github.com/facebook/jsx

**Comment by denvned** [comment]
Sorry. Looks like a dup of https://github.com/facebook/jsx/issues/23
