### ISSUE TITLE
update tutorial to use callback refs

### ISSUE THREAD

**Issue by roma1n** [facebook/react#5427]
On the page [Refs to Components](https://facebook.github.io/react/docs/more-about-refs.html) in the documentation, it is stated that "React also supports using a string (instead of a callback) as a ref prop on any component, although this approach is mostly legacy at this point."

Yet the [tutorial](https://facebook.github.io/react/docs/tutorial.html) uses string-based refs for the comment box inputs. 

Since the tutorial is aimed at newcomers, it may be a good idea to a) explain why string-based refs are considered legacy and/or b) use another approach?

**Comment by jimfb** [comment]
Should use callback refs in the tutorial.

**Comment by zpao** [comment]
After thinking about this some more, we're going to keep the tutorial as is and use string refs. They aren't deprecated yet and its one less thing to learn right away. We should improve the wording on the refs page though to make the current support status clearer.

String refs are still valuable and much easier to use in some cases, especially in the context of forms.

**Comment by jimfb** [comment]
To follow up on this issue, our discussion resulted in a decision to do https://github.com/facebook/react/issues/5443 instead.
