### ISSUE TITLE
How to test child props without triggering "Do not access .props of a DOM node" (0.14)?

### ISSUE THREAD

**Issue by Grandrath** [facebook/react#5428]
I have a component whose job it is to add certain properties to its child:
```javascript
const Parent = React.createClass({
  doStuff() {
    // ...
  },

  render() {
    const child = React.cloneElement(this.props.children, {doStuff: this.doStuff});
    return <div>{child}</div>;
  }
});
```

With 0.13 I could test it like this:
```javascript
const {renderIntoDocument, findRenderedDOMComponentWithClass} = TestUtils;
const parent = renderIntoDocument(<Parent><span className="test" /></Parent>);
const child = findRenderedDOMComponentWithClass(parent, "test");
expect(child.props.doStuff).to.equal(parentElement.doStuff);
```

What is the "0.14 way" of testing this?

PS. I test the behavior of `Parent.doStuff` elsewhere, but I also need to ensure that the given child gets a reference to this method.

**Comment by jimfb** [comment]
Instead of using a span as the child, you could create a child component that expects that prop to be set when that child renders, and fails the test if the prop isn't set.

This is a usage question, rather than a bug in the React core.  Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core.  For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.

**Comment by Grandrath** [comment]
@jimfb Thank you for your quick response. I'm aware that this issue is not a bug but maybe it shows that documentation could be improved. ;-) I posted a [copy](http://stackoverflow.com/questions/33614485/how-to-test-child-props-without-triggering-do-not-access-props-of-a-dom-node) to SO.

Regarding your suggestion: Yes, I could create a custom component. This component could test if `props.doStuff` is a function, but I see no way to test if it's the function I expect it to be.

**Comment by jimfb** [comment]
Looks like you're already pulling `parentElement.doStuff` to get the function that you expect.  So...

```
class Child {
  render() {
    expect(this.props.whatever).tobe(parentElement.doStuff);
  }
}
```

Just make sure parentElement is defined in the current scope prior to defining the Child class that you are using for testing.

**Comment by Grandrath** [comment]
@jimfb Thank you for your help. You put me in the right direction. :-)

For the record here is what now works for me (`Parent` is the unit under test):
```javascript
const TestChild = () => <div />;

const TestContainer = React.createClass({
  getParent() {
    return this.refs.parent;
  },

  getChild() {
    return this.refs.testChild;
  },

  render() {
    return <Parent ref="parent"><TestChild ref="testChild" /></Parent>;
  }
});

const {renderIntoDocument, findRenderedDOMComponentWithClass} = TestUtils;

const testContainer = renderIntoDocument(<TestContainer />);
const parent = testContainer.getParent();
const child = testContainer.getChild();

expect(child.props.doStuff).to.equal(parent.doStuff);
```

(`TestChild` has to be a custom component, otherwise `this.refs.testChild` only returns a DOM node instead of a component instance.)
