### ISSUE TITLE
Warn when duplicate copy of React

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5441]
Looks like we lost the duplicate-react warning (https://github.com/facebook/react/pull/3332) due to merging https://github.com/facebook/react/pull/5205 which contained https://github.com/spicyj/react/commit/4ba0e95a96507abbcb2819be328fc3d1ed3cc80f

**Comment by spicyj** [comment]
Yes. That warning triggered in the case that `deepestAncestor` was null (which it should never be) but that codepath is gone now so it can't throw errors. If there's a new codepath that's problematic, feel free to add a new warning.

**Comment by jimfb** [comment]
@spicyj But there are still other code paths, right?  Events listeners, for instance?

**Comment by spicyj** [comment]
If you know of any that cause problems where it's feasible for React to detect this, please add warnings. I don't know where they are, if they exist.

**Comment by jimfb** [comment]
I suspect that there are cases, but I suppose we can create a new issue when one of them pops up.
