### ISSUE TITLE
React 0.14 Invariant Violation: findComponentRoot after state update

### ISSUE THREAD

**Issue by alansouzati** [facebook/react#5448]
This code: https://jsfiddle.net/alansouzati/2f9p4ngp/ works in the first load. After the state is updated there is the following error in the console:

```
Uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

If I remove the reference for `title` inside `defaultMessage` prop it works normally again. 

I'm not sure if this is an actual issue with React, but I could not understand why the first time works and the second time fails.

Any help appreciated.

**Comment by syranide** [comment]
`<title>` only allows a text node as its child. You're putting a `<span>` in there which becomes rendered into the text node and thus cannot be found by React. You must do `<title>{...}</title>` instead (caution, it cannot be `<title>Foo{'bar'}</title>` either at current, due to React internals).

cc @spicyj update validateDOMNesting?

**Comment by alansouzati** [comment]
Thanks for your help. I'm not very familiar as well, but I believe they are valid inside inline svgs.

**Comment by alansouzati** [comment]
Well it works fine if you have `<title><span>hi</span></title>` inside svg, not inside div. check this fiddle: https://jsfiddle.net/alansouzati/oh8z7px4/

Anyways... I don't think I should be using this construction at all. I'm just confused why in some cases it works, and some cases not.

**Comment by zpao** [comment]
The initial render (currently) just does an innerHTML. a `<title>` tag in the body of the document actually results in a child node that is text, regardless of the markup in there. So the `<span>...` isn't actually a node. So when React tries to find the node with the data-reactid we assigned, we can't find it, thus the error. this is what @syranide explained (though leaving out the initial render part, which is important to explain why that first render worked without a warning).

<img width="563" alt="screen shot 2015-11-11 at 3 12 12 pm" src="https://cloud.githubusercontent.com/assets/8445/11105876/c2c3a164-8886-11e5-9b28-76a92c0e1633.png">

Inside SVG, `<title>` is a valid child that works differently than it does in HTML and it seems to be valid to have child nodes there, even if they are ignored.
