### ISSUE TITLE
Undocumented Change: same instances components are not rerendered anymore

### ISSUE THREAD

**Issue by rogeriochaves** [facebook/react#5450]
I noticed an undocumented change (at least I didn't find it) from React 0.13 to 0.14

Now, React doesn't rerender the component when it is exactly the same instance (i.e. when you save a `<reactComponent />` in a variable), look:

React 0.13.3: https://jsfiddle.net/zac5zuLo/
React 0.14.2: https://jsfiddle.net/2f6muyuk/

Even further, this is not only using React.render, if the components below doesn't have state neither any props, and we just try to rerender the same instance with a forceUpdate or setState for example, the rendering is skipped, look:

React 0.13.3: https://jsfiddle.net/zac5zuLo/1/
React 0.14.2: https://jsfiddle.net/2f6muyuk/1/

I couldn't find this on the react update changelog, maybe it falls under `Many small performance improvements have been made`.

And just to be clear, it does work if your components instantiates a new children on the render method, like this:

React 0.14.2: https://jsfiddle.net/2f6muyuk/2/

**Comment by jimfb** [comment]
The first example you gave is expected, and is one of our small performance updates.

But `forceUpdate` should - you know, force an update!  Sounds like a bug to me.

**Comment by zpao** [comment]
cc @sebmarkbage @spicyj, this sounds like something that came up not too long ago but I don't recall the resolution.

The root of it is that the element that gets passed in is === to the one previously rendered so presumably we made the decision to skip that. That's fine when things are pure but is confusing when breaking out and using non-deterministic method calls in render.

**Comment by spicyj** [comment]
I should have mentioned this in the changelog, sorry.

When you call forceUpdate, your `Foo` component *does* rerender, but `Hello` does not, as if `Hello` had a `shouldComponentUpdate` method that returns false.

I don't think we plan to make any changes here – I hope it's not too hard to update your code.

**Comment by rogeriochaves** [comment]
@spicyj it is not, it was just a hard time trying to find out that this was the cause
