### ISSUE TITLE
Cannot expose component functions

### ISSUE THREAD

**Issue by mhuggins** [facebook/react#5452]
I'm running into an issue with React 0.14 with regards to [exposing component functions](https://facebook.github.io/react/tips/expose-component-functions.html).  Perhaps I am just doing something wrong, unless this is a stale piece of documentation from an earlier version of React.

I have a React component that exposes a piece of state as a function, e.g.:

```coffeescript
SelectionsController = React.createClass
  propTypes:
    values: array

  getInitialState: ->
    selections: []

  getSelections: ->
    @state.selections

  render: ->
    `<ul>{this.props.values.map(this.renderValue)}</ul>`

  renderValue: (value) ->
    `<li><Checkbox name={value}
                   checked={_.contains(this.state.selections, value)}
                   onChange={this.handleChangeCurry(value)} /></li>`

  handleChangeCurry: (value) ->
    (checked) =>
      if checked
        @setState(selections: _.union(@state.selections, [value]))
      else
        @setState(selections: _.without(@state.selections, value))
```

I then create an instance of this component and later try to fetch the selections via `getSelections`:

```coffeescript
controller = React.createElement(SelectionsController, values: ['one', 'two', 'three'])
# then in a user event handler...
console.log(controller.getSelections())
```

The console log line results in this error:

> Uncaught TypeError: controller.getSelections is not a function

Am I doing something wrong?

**Comment by zpao** [comment]
```js
controller = React.createElement(SelectionsController, values: ['one', 'two', 'three'])
```

All you've done here is create an element, not a rendered instance of the component. Elements are lightweight objects that React then uses to render - basically it looks like this:

```js
{
  type: SelectionsController,
  props: {
    values: ['one', 'two', 'three']
  }
}
```

In order to have an instance to work with, you then need to render it and the returned value is an instance.

```js
var instance = ReactDOM.render(controller, node);
console.log(instance.getSelections())`
```

The docs you linked to don't need to be updated - they are working with refs, which is another way to access rendered components within another component.

**Comment by mhuggins** [comment]
Ahh, gotcha.  I'm working with a middleman component that extracts away the rendering where it actually gets rendered.  Thanks!
