### ISSUE TITLE
Inline Style interferes with ReactCSSTransitionGroup CSS

### ISSUE THREAD

**Issue by ar7casper** [facebook/react#5457]

**Comment by jimfb** [comment]
Thanks for posting on StackOverflow - that is a much better place for usage questions!

Original question was: 
http://stackoverflow.com/questions/33668088/animating-non-existant-elements-in-react-js/33670565#33670565

If you're able to reduce it to a simplified test case that demonstrates a bug in the React core, please do let us know!
