### ISSUE TITLE
Please add source url to react-addons npm packages

### ISSUE THREAD

**Issue by mkotsbak** [facebook/react#5461]
Please add https://docs.npmjs.com/files/package.json#repository repository property to the React addons, like react-addons-perf. It is required to import them as jars, at webjars.org.

**Comment by zpao** [comment]
Already done in #5396. The next publish for 0.14.3 will update that (there's currently no way to update npm metadata without a new version). No timeline on 0.14.3, but looks like we have a few things to put in there so perhaps soon.

**Comment by mkotsbak** [comment]
Ok, good. I'm just unsure if repository": "facebook/react" is sufficient, or if it should be prefixed with github: ?

**Comment by zpao** [comment]
npm treats that as github (https://docs.npmjs.com/files/package.json#repository)
