### ISSUE TITLE
Why is `this.state` not available by default?

### ISSUE THREAD

**Issue by colllin** [facebook/react#5464]
I'm happy to move this question elsewhere if you can point me in the right direction.

Why do I get an error (`Uncaught TypeError: Cannot read property 'someProperty' of null`) when I don't call `this.setState()` before the initial render?

    render() {
        return (
            <span>{this.state.someProperty}</span>
        )
    }

This error goes away if I simply call `this.setState()` with an empty object in `componentWillMount`:

    componentWillMount() {
        this.setState({});
    }

Isn't `this.state` part of the core React Component API?  Why wouldn't it be present by default?

**Comment by fkling** [comment]
See https://github.com/facebook/react/issues/1851 .

**Comment by jimfb** [comment]
Thanks @fkling!  Closing this out in favor of #1851.  Also, see https://github.com/facebook/react/issues/3236#issuecomment-76456970 which has a somewhat related discussion.

@colllin For future reference, usage questions are best addressed on StackOverflow.  I know this was somewhat bug like, so this wasn't a bad place, but just something to consider.  We try to keep github for tracking bugs in the core.

**Comment by colllin** [comment]
Thank you, @fkling
