### ISSUE TITLE
Component is not getting rendered if the name doesn't get started with capital letter.

### ISSUE THREAD

**Issue by antoaravinth** [facebook/react#5469]
Hi, 

I have this very small react code:

```
var NewProp = React.createClass({
       render : function() {
            return ( 
               <h1>Hello</h1>
             )
         }
})

React.render(<NewProp />, document.getElementById('container'));
```

which works as expected. The moment I do these changes:

1. Change the variable name `NewProp` to `newProp` and refresh the page. Nothing get displayed on the DOM and no warnings in the console too. 
2. Change the `NewProp` name to `newProp` in both places, so that code looks like this:

```
var newProp = React.createClass({
       render : function() {
              return ( 
                 <h1>Hello</h1>
              )
        }
})

React.render(<newProp />, document.getElementById('container'));
```

now I expect it should display the `Hello`, however it doesn't show anything. Again no error message in the console. 

I have tested this code in 0.14 and even in master branch. 

Thanks.

**Comment by kjbekkelund** [comment]
https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components:

> To render a React Component, just create a local variable that starts with an upper-case letter

**Comment by antoaravinth** [comment]
But as a beginner I would like have some warnings on the console.

**Comment by jimfb** [comment]
Warnings are being tracked as https://github.com/facebook/react/issues/3596 and https://github.com/facebook/react/issues/4695

**Comment by zpao** [comment]
For a bit of clarity, if you want warnings in the console at JSX compile time then you'll want to file that against whatever you are using to transform (probably Babel).

**Comment by jimfb** [comment]
@zpao For the warning(s) that would require transform support, do we want to just file those against babel instead of React?

**Comment by zpao** [comment]
Yes, that's what I just said. Only exception would be if it's something that we would want to write an additional babel plugin for.
