### ISSUE TITLE
'onDoubleClick' event is invalid when I set 'onMouseDown' event

### ISSUE THREAD

**Issue by liuhong1happy** [facebook/react#5471]
Who can help me?

**Comment by cody** [comment]
I tested it on jsfiddle and at least my test case seems to work: https://jsfiddle.net/69z2wepo/21201/

Maybe you can make a minimal repro of the bug on jsfiddle or jsbin?

**Comment by jimfb** [comment]
As per @cody's jsfiddle, it does appear to work. @liuhong1happy, can you create a simple jsfiddle that demonstrates the issue?

**Comment by liuhong1happy** [comment]
Yeah! It's my fault. As per @cody's jsfiddle, it does appear to work.In this program。 A 'masking' div was changed to show state when  'mousedown' event was handled。so,the 'dblclick' handler didn't work。
