### ISSUE TITLE
Potential Inconsistency in Docs Regarding `Dispatcher.Waitfor`

### ISSUE THREAD

**Issue by danielstern** [facebook/react#5478]
In the docs, `https://facebook.github.io/flux/docs/todo-list.html`

`flightDispatcher.waitFor([CountryStore.dispatchToken]);` Dispatcher example, note absence of callback.

Elsewhere in the docs, `https://facebook.github.io/flux/docs/todo-list.html`

Note the specified implementation of dispatcher includes both a CB and a promise return. Could these be made more consistent? Is there a single canonical example of dispatcher dependency at work?

```
 waitFor: function(promiseIndexes, callback) {
    var selectedPromises = promiseIndexes.map(function(index) {
      return _promises[index];
    });
    return Promise.all(selectedPromises).then(callback);
  }
```

**Comment by jimfb** [comment]
I'm assuming this should be filed against https://github.com/facebook/flux
