### ISSUE TITLE
recursion on dispatchEvent

### ISSUE THREAD

**Issue by hellectronic** [facebook/react#5482]
I am using [dispatchEvent()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) to trigger a React event handler. Doing this, causes a recursion. I created a repository with the code: https://github.com/hellectronic/react-dispatchevent-test

I have some checkboxes, that have event handlers attached to it. Clicking "select all" should trigger this, but as mentioned causes the recursion.

Here is the javascript:

``` javascript
const BOX_NAME = 'testname';

var CB = React.createClass({
    onCheckClick: function(el) {
        console.log('clicked '+ el);
    },

    render: function() {
        const cbs = ['checkbox1', 'checkbox2', 'checkbox3'];
        const list = cbs.map( (el, i) => {
            return (
                <li key={i}>
                <input type="checkbox"
                    onClick={ e => this.onCheckClick(el) }
                    name={ BOX_NAME }
                    value={ el } />
                </li>
            );
        }, this);

        return (
            <div>
                <Nav boxName={ BOX_NAME } />
                <ul>{ list }</ul>
            </div>
        );
    }
});

var Nav = React.createClass({
    handleCheckClick: function() {
        console.log('select all');

        const boxes = document.getElementsByName( this.props.boxName );
        for ( let i = 0; i < boxes.length; i++ ) {
            //boxes[i].checked = checked;
            //boxes[i].onClick(); 
            const evt = new MouseEvent( 'click', {
                bubbles: true,
                cancelable: true,
                view: window,
            } );
            boxes[i].dispatchEvent( evt );
        }
    },

    render: function() {
        return <a onClick={ e => this.handleCheckClick() }>select all</a>;
    }
});

ReactDOM.render(
    <CB />,
    document.getElementById('container')
);
```

**Comment by hejld** [comment]
It seems to be a problem affecting only the DEV build of React (but 0.14.2 as well). The recursion is caused by https://github.com/facebook/react/blob/master/src/shared/utils/ReactErrorUtils.js#L68

**Comment by zpao** [comment]
The simple solution is to trigger your events in a different event loop (eg, setTimeout your for loop). Or even better, communicate differently so that this is achieved with state and not through triggering events.

That said, It's not clear to my why this triggers too much recursion as is though.

**Comment by hellectronic** [comment]
Thanks @zpao . Wrapping the for loop with setTimeout() does the trick.

The functionality is there, so a simple component like Nav was the simplest way to trigger it. But I am open for a more likely React solution.

**Comment by gaearon** [comment]
This doesn‘t reproduce with React 16.
