### ISSUE TITLE
ReactDOMServer not available through globals?

### ISSUE THREAD

**Issue by Download** [facebook/react#5490]
Recently some code was moved from React to ReactDOM. I get the idea behind this move.

Before, to do server side rendering, we had to use `React.renderToString`. This is neatly available on the global `React` object. 

After, we have to use `ReactDOMServer.renderToString`. The problem with this is that AFAIK, the `ReactDOMServer` object is not available in the global scope. So when we don't have access to the `require` function, this is problematic.

My server-side code (with Nashorn) is currently doing `React.renderToString` and this is still working, but for the upgrade to the newest React version I scoured the whole internet and the React source code but have not found a way to gain access to `ReactDOMServer` without doing:

```js
var ReactDOMServer = require('react-dom/server');
``` 
...which is not possible to do if there is no `require` function available...

Can you maybe add a property `Server` to `ReactDOM` so we can get `ReactDOMServer` from the global `ReactDOM` object by doing this:

```js
var ReactDOMServer = ReactDOM.Server;
```

?

**Comment by jimfb** [comment]
@zpao This keeps coming up.  We should come up with a more legit solution than "go build/package it yourself"

**Comment by zpao** [comment]
I'm going to close and since you mentioned Nashorn, point you to another issue on the topic. #5490. Perhaps we'll do something more.

**Comment by jimfb** [comment]
@zpao You linked to this same issue.

**Comment by Download** [comment]
#5311 is now also closed.

I see quitte a few people have issues with this. It's **one line** of code to solve on your end.

On our end, we have to implement / polyfill a CommonJS module loader on the target platform just to get access to the ReactDOMServer object...

Why the need to make this so difficult.

And how can you not call it a bug that [this pre-built bundle](https://fb.me/react-0.14.2.js) contains code that is effectively unreachable? If I have `require` available, why would I use the pre-built bundle??

Now I can see you don't want to pollute the global scope. Who would? But what is against exposing `ReactDOMServer` via `ReactDOM`, which is already in the global scope?
