### ISSUE TITLE
Npm install peerDependencies fail on update to 0.14.2  - fails with its own react-dom

### ISSUE THREAD

**Issue by AlexHandy1** [facebook/react#5491]
Updated react to latest build in order to use the react-d3-components library which had a hard dependency and now I get these errors.
All the versioning below seems as though it should pass the corresponding versioning logic. 
Have uninstalled and reinstalled all node_modules, make sure have latest versions but nothing working.

````
npm ERR! peerinvalid The package react@0.14.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer marty@0.11.0 wants react@0.14.x
npm ERR! peerinvalid Peer react-leaflet@0.6.2 wants react@^0.13.0
npm ERR! peerinvalid Peer react-sparklines@1.4.2 wants react@>=0.13.3 || ^0.14.0-rc1
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2

````

**Comment by syranide** [comment]
I always find these confusing as hell, but `react-leaflet` is announcing itself as not compatible with React 0.14 and that's probably the source of the problem.

`npm ERR! peerinvalid Peer react-leaflet@0.6.2 wants react@^0.13.0`

**Comment by AlexHandy1** [comment]
thanks for responding. 
Looks like that's not the issue though - see release v0.8.0
https://github.com/PaulLeCam/react-leaflet/releases

**Comment by syranide** [comment]
@AlexHandy1 It's not trying to install 0.8 for you though, possibly locked dependency?

**Comment by AlexHandy1** [comment]
@syranide - good spot. Strange given it has the '^' caret. 
Maybe that will solve one of the errors. 
Installing react-dom as a separate npm package has also helped resolve the react-dom error

**Comment by syranide** [comment]
@AlexHandy1 0-versions are special.

**Comment by zpao** [comment]
Closing this out since it's a not a React issue but feel free to continue working through it here.
