### ISSUE TITLE
A way to create pure stateless components

### ISSUE THREAD

**Issue by KnutHelland** [facebook/react#5492]
I've just discovered that _stateless components_ aren't pure. You can do:
```jsx
const Clock = () => <div>{moment().format('HH:mm:ss')}</div>
```
and it works very well as long as the parent component is rerendered often enough.

I think by publishing unpure stateless components in `v0.14`, you lost a good opportunity to teach the community to write fast, pure components. After so many talks where you've mentioned how cool and powerful the principles of immutable data is, I must say I'm dissapointed that you keep adding functionality to React that allows people to write what I think is sloppy code.

But it looks like stateless components still is a undocumented feature. The only official place I can find infromation about it, is in the release article in the blog. Could it be possible to change the behaviour of stateless components and make them pure in a later release?

If not: then I would really like another way to write pure, stateless functions. That will probably be something like:
```jsx
const Clock = ({ currentTime }) => <div>{currentTime.format('HH:mm:ss')}</div>;
Clock.isPure = true;
```

**Comment by roganov** [comment]
How do you propose to force purity in an impure language?

**Comment by zpao** [comment]
I'm going to close this out and point to #3995 which was an initial PR for functional components. There's some good discussion around the ideas to make them "pure".

**Comment by KnutHelland** [comment]
This stateless component:
```jsx
const Header = ({title}) => <h1>{title}</h1>;
```
is almost equal to this:
```jsx
const Header = React.createClass({
    render() {
        return <h1>{this.props.title}</h1>;
    }
});
```
but I would really prefer it to work like this:
```jsx
const Clock = React.createClass({
    mixins: [PureRenderMixin],
    render() {
        return <h1>{this.props.title}</h1>;
    }
});
```
because that can give you an enormous performance boost in some cases since it only rerender if props are changed. (see: https://facebook.github.io/react/docs/pure-render-mixin.html)

There are some performance optimization done on stateless components that I don't know about. But since they don't behave like a components with `PureRenderMixin` enabled, it should still be possible to gain more performance.

My personal opinion is that the behaviour of PureRenderMixin should be default for all other components as well, as long as they don't implement another behaviour in the `shouldComponentUpdate` method. I might be very wrong, but I think that forces you to write more reasonable and performant code.

**Comment by KnutHelland** [comment]
Thanks @zpao. I tried to search for similar issues, but didn't search in the pull requests. I'm apparently months too late.
