### ISSUE TITLE
DOM elements in switched order

### ISSUE THREAD

**Issue by mezod** [facebook/react#5494]
I have a Component that among many other things includes this two components in the following order:

```
...
<Components.ListsMenu
            lists={this.props.lists}
            updateList={this.props.updateList}
            deleteList={this.props.deleteList}
            owner={this.props.owner}/>
{this.props.owner ? <Components.NewListBox
                  saveNewList={this.props.saveNewList}/> : null}
...
```

where this.props.owner is just a boolean. 

The problem is that React prints the Components.NewListBox element before the Components.ListsMenu in the DOM. Here you can see how the DOM looks: 
![image](https://cloud.githubusercontent.com/assets/6820/11226795/0b4950d2-8d37-11e5-960c-19028fc0cc7c.png)
 the div with class newList is printed above the ul with class lists, when the reactids show the order should be the other way around.

If I change this.props.owner by "true" it will print the element in the expected position in the DOM.

Am I missing something basic here? Pretty weird issue!

**Comment by zpao** [comment]
Is there any way you could reduce this to a runnable test case? My gut on cases like this is usually something about keys but that shouldn't be necessary here.

**Comment by spicyj** [comment]
Also, what version of React are you using?

**Comment by mezod** [comment]
react 0.14.0

**Comment by mezod** [comment]
I am not sure of how to make a runnable test case. I have the issue on this branch so you can clone it and see it for yourselves, maybe? You will need to have some dummy items in the db to see that the <ul> falls under the <div> though. Just le me know how can I help you help me :)

**Comment by spicyj** [comment]
Okay, if you can list steps to reproduce this including how to clone your repo and what items to add, I can take a look.

**Comment by mezod** [comment]
1. git clone https://github.com/mezod/listlogs.git (it's in the branch joan but i dunno how to get only that branch)

2. git checkout joan

3. npm install

4. Create a mysql database called "listlogs" with hmm (maybe you can give me an email and I send you a dump so you can import the schema?)

5. npm run server (to start the api)

6. npm run dev (to start the webpack dev server)

7. localhost:8080/ just sign up with whatever you want

8. On the left, the second "+" icon says Add new List. If you add one, a new item will appear in the menu. This is the item that should appear over the "+" for the new list, but if the error reproduces it will appear under it.

Do you maybe use irc or skype or fb or something in case you find an issue setting it up?

**Comment by spicyj** [comment]
I don't have mysql. Is it possible that you can make a smaller example? Try deleting all the parts of your code that aren't necessary to make the issue appear. It shouldn't require any database.

**Comment by mezod** [comment]
hmm let me think how to go about it

**Comment by mezod** [comment]
the problem is that the condition of the ternary expression that ruins the behaviour is actually checking if a user is logged in, if I change that by let's say "true", then it works

**Comment by mezod** [comment]
funnily the value of this.props.owner is true...

**Comment by mezod** [comment]
maybe I can share my screen? I'm not sure of how to reproduce the error

**Comment by mezod** [comment]
ok @cuttlas created a branch that doesn't require a backend https://github.com/mezod/listlogs/tree/issue

steps: 

1. npm install
2. npm run dev (to start the webpack dev server)

3. localhost:8080/ just sign up with whatever you want

After signin in, the menu has 2 dummy lists on the left and the second "+" appears under them as it should be. However, if you refresh the page, the second "+" goes above the two lists. Hope this helps!

On the left, the second "+" icon says Add new List. If you add one, a new item will appear in the menu. This is the item that should appear over the "+" for the new list, but if the error reproduces it will appear under it.

**Comment by spicyj** [comment]
I am not sure if I am reproducing this correctly but I do see a warning:

```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See Menu > Link > a > ... > a.
```

If I change Menu.jsx to use a `span` inside .listlogs-logo inside the Link instead of an `a` then I think the error goes away. Can you confirm?

If so, how could we have made this clearer? (Did you not see the error? Did you see it and ignore it?)

**Comment by zpao** [comment]
> Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See Menu > Link > a > ... > a.

Changing that nested anchor to anything else seems to fix this. The problem is that React can't help you when you create invalid markup. The browser moves nodes around.

**Comment by mezod** [comment]
Well, this is embarrassing. It does work. Thanks both! We had a bunch of warnings that we've been solving during the evening and left this one out for later thinking it had absolutely no relation with that. I am not sure how to make it clearer, I guess the fact that it worked when the value was "true" confused us a bit. Thanks again though, cheers!
