### ISSUE TITLE
HTMLAudioElement is partially supported and confusing

### ISSUE THREAD

**Issue by electricmonk** [facebook/react#5505]
Attempting to render an `<audio volume="1">` tag. Element is rendered but `volume` attribute not.

If I understand correctly, PR  #2094 introduced lots of different attributes and was rejected. However, presently React violates the principle of least surprise, by agreeing to render an `HTMLAudioElement` but only rendering some of its attributes - only those that are included in `HTMLDOMPropertyConfig`. 

Is there any work planned on the media tags? should React be willing to render them only with part of the attributes? wouldn't it be better to drop support completely?

**Comment by syranide** [comment]
@electricmonk There is no `volume` attribute for `<audio>` as far as I can tell:
http://www.w3.org/TR/html5/embedded-content-0.html#the-audio-element

**Comment by jimfb** [comment]
For `volume`, I wonder if it makes sense for React to expose it as an attribute.  It also seems reasonable to suggest it to the W3C, since I can't think of a reason why it shouldn't be an attribute.

**Comment by syranide** [comment]
@jimfb Because it's user-controlled and the best initial value is what the user last had, not a developers arbitrary judgement I would think.

**Comment by jimfb** [comment]
Ah, yeah, unless the developer intends on providing their own volume control.  But yeah, makes sense.

Sounds to me like we should close this issue, unless someone sees a reason to keep it open.

**Comment by electricmonk** [comment]
Hmm. I stand corrected.

**Comment by syranide** [comment]
> Ah, yeah, unless the developer intends on providing their own volume control. But yeah, makes sense.

@jimfb React only deals with attributes, in-part because of server-rendering I would say. Personally I think it's best if React just stays out of these things anyway; it can be trivially implemented in user-land via a wrapper component.
