### ISSUE TITLE
validateDOMNesting generates warnings for components that return null inside tbody

### ISSUE THREAD

**Issue by gotbadger** [facebook/react#5506]
According to the doc on [Render](http://facebook.github.io/react/docs/component-specs.html#render) its ok for components to return `null` if nothing needs to be 
rendered but this causes a warning from `validateDOMNesting` if used inside a tbody

```javascript
var Component = React.createClass({
    render: function() {
      return null
    }
});
var Table = React.createClass({
    render: function() {
        return <table><tbody><Component /></tbody></table>;
    }
});
 
ReactDOM.render(
    <Table />,
    document.getElementById('container')
);

```
gives us the following warning:
```
Warning: validateDOMNesting(...): <noscript> cannot appear as a child of <tbody>. See Table > tbody > noscript.
```

**Comment by nabilfreeman** [comment]
well spotted :+1:

**Comment by zpao** [comment]
It looks like we're going to make `null` actually render to comment nodes in #5451 so this should become a non-issue in the future.

**Comment by YeZhiqiuSev** [comment]
mark this error
