### ISSUE TITLE
this.props.children doesn't always inherit the context from its parent

### ISSUE THREAD

**Issue by lucasmotta** [facebook/react#5507]
I've assumed that the `children` would always inherit the context from its parent, but that's not always the case:

This works as expected:
```jsx
// child
class Child extends React.Component {
    static contextTypes = { color: React.PropTypes.bool };
    render() {
        const style = { color: this.context.color };
        return <div style={{color: this.context.color}}>Children color is {this.context.color}</div>
    }
}
// parent
class Parent extends React.Component {
    static childContextTypes = { color: React.PropTypes.string };
    getChildContext() {
        return { color: 'red' };
    }
    render() {
        return <div><Child /></div>;
    }   
}
React.render(<Parent />, document.getElementById('root'));
```

But if change the parent to use `this.props.children`, the context is not transferred to its children anymore:

```jsx
// parent using this.props.children
class Parent extends React.Component {
    ...
    render() {
        return <div>{this.props.children}</div>;
    }   
}
React.render(<Parent><Child /></Parent>, document.getElementById('root'));
```

I've also created simple [jsfiddle](http://jsfiddle.net/p23w9Laz/) to demonstrate that.

I would assume that if the `<Child>` is inside the parent, it should inherit the context of it.
Is that how it's meant to be? And is there a way to change the context, so the second example would also work?

**Comment by lucasmotta** [comment]
I'm closing this for now. I've updated to React 0.14.3 and it worked as expected.
So if you find this issue, upgrade your React :)

**Comment by seleckis** [comment]
I have React 15.3.0 and the problem still persists.

**Comment by seleckis** [comment]
I have React 15.3.0 and the problem still persists.

**Comment by jshin49** [comment]
Similar issue still seems to persist in React 15.4.1, although not exactly the same cause.

**Comment by gaearon** [comment]
We can't guess anything about this problem from a single sentence reports like "I also have this". When you have an issue and want to see it fixed, please provide a project or a small example reproducing it. This would let us look into it and see if there is indeed a bug.

I will lock this issue to prevent further "me too"s, but we will be happy to receive a new issue report about this with a reproducing example. Thank you!
