### ISSUE TITLE
Input defaultValue not always evaluated.

### ISSUE THREAD

**Issue by julia-allyce** [facebook/react#5509]
When you rerender with two similar views that both contain an input (regardless of type), defaultValue is not evaluated.  This only happens when the element tree structure is the same/similar up to the input -- even if the inputs are two different types.

You can see it in this simple example where the new and old views are inputs inside a div:
https://jsfiddle.net/u9rd10ab/

**Comment by jimfb** [comment]
I feel like this is expected behavior (albeit perhaps slightly confusing).

For the class `input` with the same parents, you are just changing the `type` attribute (the instance doesn't change), so `defaultValue` would not be evaluated.  If you change the ancestor component class (eg. from `div` to `span`) the instance is thrown away and a new input instance is created, thus `defaultValue` gets evaluated.  This is expected behavior given the way React keys work.

cc @spicyj @zpao

**Comment by spicyj** [comment]
Yes, you can work around this by changing the `key` attribute on the input so that it gets recreated.

**Comment by DesignByOnyx** [comment]
I think that to the react diffing/reconciling engine, the only thing that changed is the type. To the end user and developer, it's much more than that.  While the "type" is technically the only thing changing, it's a whole new input. There's no use case from the developer or end user standpoint that says "I want to keep the same exact input, just change the type".

**Comment by jimfb** [comment]
@DesignByOnyx Yeah, but the same argument could be made about a whole ton of things.  Changing one attribute (eg. `src` on a video component) could "imply" that other attributes (eg. the component's play/scrubber position) should also change.  And while someone could make an argument for any one of these changes, the rules that result from such a wackamole game become too complicated for anyone to understand.  It is better to have a simple set of rules (a change in "tag type" results in a new instance, attribute changes do not) that are honored everywhere.

FWIW, keep in mind that these problems all evaporate if you use controlled components, which is the more "reacty way".

**Comment by julia-allyce** [comment]
Thanks for the quick responses. It makes sense why it is behaving that way. But a very _wat_ moment this morning before my coffee. Switching to controlled components seems like a better solution than using keys.

**Comment by DesignByOnyx** [comment]
@jimfb - I get your point - although the video "src" example is not the best ;). It's kind of like saying that every time you change the TV channel, someone might expect a new TV to appear in its place with the new channel set and the brightness and hue set back to 50%. However, if the type of TV changes from CRT to Plasma - now it's completely reasonable to expect a new TV in its place. I get your point nonetheless.

The overall issue here is that if a developer has 2 completely different views and an just happens to implement the same tree structure - which is just arbitrary and random IMO - then the input gets reused, despite the fact that the intent is not to.  I'm trying to think of another case where I would expect an attribute change to completely reset the element, and I can't. The input/type scenario seems pretty unique and is deserving of more scrupulous investigation.

Another thing to consider is the fact that the defaultValue property and the "value" attribute follow each other.  For example, paste this into your console:

```js
document.createElement("input");
document.body.appendChild(input);
input.defaultValue = "foo";
// observe "foo" is actually in the text field
input.getAttribute("value");  //-> "foo"
input.type = "checkbox";
input.type = "text";
// observe "foo" is still visible in the text field.
```

**Comment by scriby** [comment]
I'm new to React and hit this issue today. I was rendering two different DOM trees based off a boolean switch. Both trees shared the same structure, so when switching between them the input in both trees retained the value.

The behavior was quite puzzling from an outside/beginner's perspective. It makes sense that React doesn't really know whether the HTML I'm returning is for a new element or an update to the existing element.

I wonder if it would be a good idea or not for the JSX compiler to automatically insert random keys into root elements if not already provided.
