### ISSUE TITLE
React.Child.isNull - Ability to check if a component rendered null.

### ISSUE THREAD

**Issue by iammerrick** [facebook/react#5517]
Suppose I want a component `Concatenate` that concatenates it's children together using a separator prop...

```javascript
import React from 'react';
import _ from 'lodash';

class Concatenate extends React.Component {

  render() {
    var children = React.Children.toArray(this.props.children);
    var separated = children.reduce((previous, current, index) => {
      previous.push(current);
      if (index !== children.length - 1) {
        previous.push(this.props.separator(index));
      }
      return previous;
    }, []);

    return <div {...this.props}>{separated}</div>;
  }
}

Concatenate.defaultProps = {
  separator: (key) => {
    return <span key={key}> &sdot; </span>;
  }
};

export default Concatenate;
```

I would like to choose to not render a separator if the corresponding child decides to render null, is this possible? Is there a React.Child.isNull functionality?

**Comment by zpao** [comment]
No and unfortunately this won't be possible - proptypes are done early on the elements and don't have access to the rendered result.

**Comment by iammerrick** [comment]
No worries. Appreciate the courteous reply! Thanks for React!

**Comment by richard-flosi** [comment]
This is exactly the same thing I'm trying to do. Still no solution?

**Comment by joshacheson** [comment]
For what it's worth to anyone who reads this, it's my understanding that [React Call Return](https://github.com/facebook/react/tree/master/packages/react-call-return) is the (not yet ready) feature designed at least partially to address this problem.

**Comment by damassi** [comment]
(The experimental React Call Return API has been removed)

**Comment by Igorkowalski94** [comment]
`Children.map( children, (child) => isValidElement(child) && child.type(child.props))`

**Comment by rafael-unloan** [comment]
> `Children.map( children, (child) => isValidElement(child) && child.type(child.props))` This way you can check whether a given child returns null/false etc.

Worth noting that this renders the child so it executes side-effects, etc. Also this is undocumented behaviour.
