### ISSUE TITLE
Creating a new element with key = null creates an element with key = 'null'

### ISSUE THREAD

**Issue by Mosho1** [facebook/react#5519]
Not sure if this is intentional, but if I run this:

    const Test = () => <div><div key={null}/></div>;
    console.log(ReactDOMServer.renderToString(<Test/>));

The resulting inner div has its `key` set to `'null'`.

the resulting DOM string is: 

    <div data-reactid=".24f30pufytc" data-react-checksum="-1417143336">
        <div data-reactid=".24f30pufytc.$null"></div>
    </div>

but if I remove the key the result is:

    <div data-reactid=".1pkvjeqnim8" data-react-checksum="1620646673">
        <div data-reactid=".1pkvjeqnim8.0"></div>
    </div>

If `undefined` is used as the key, the result is the latter above.

**Comment by zpao** [comment]
This is intentional. `null` is an intentional value whereas `undefined` is the lack of a specified value.

**Comment by syranide** [comment]
@zpao If that's the case then IMHO we should escape it properly, as it is now `"null"` and `null` are treated equally by React (this should be trivial by translating it to `.!` or whatever. Although personally I'm not sure when it ever makes sense to have `null` as a key, how about a warning too?
