### ISSUE TITLE
Allow to use @class and @style as string.

### ISSUE THREAD

**Issue by bartq** [facebook/react#5522]
I don't like the fact React doesn't allow to use `class` and `style`-as-inline-string attributes. Is there a fork or how hard is to modify React to support it?
The reason is that I don't like to manually rename `class` to `className` and without inline styles as string I can't use WebStorm's `extract to class` feature that is really nice while developing new styles.

**Comment by zpao** [comment]
We don't currently have any plans to change this now. You are welcome to maintain a fork if you would like.
