### ISSUE TITLE
React Functional Components

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/react#5525]
Hello,

Is it possible to use reacts Lifecycle methods with reacts new functional components from v0.14?

**Comment by iamdustan** [comment]
I don’t believe so. Lifecycle methods require an instance, which function components do not have.

**Comment by BerkeleyTrue** [comment]
You could use lifecycle hooks in a smart parent component and use the functional component as a dump component whose only responsibility is to render. To answer you're question, no you cannot.

**Comment by kennetpostigo** [comment]
Okay Thank you all very much for the feedback, @BerkeleyTrue , @iamdustan 🤓

**Comment by kennetpostigo** [comment]
@iamdustan @BerkeleyTrue, could you create functions within the stateless component that then calls the smart components function?
