### ISSUE TITLE
in componentDidMount can't throw error?

### ISSUE THREAD

**Issue by qinyang912** [facebook/react#5532]
I type some code in the componentDidMount , which `error` is not defined
```
componentDidMount () {
    console.log('componentDidMount',error);
}
```
but I can't see any error throw out

when I use try...catch like this in the componentDidMount
```
componentDidMount () {
    try {
      console.log('componentDidMount',error);
    } catch(e) {
      console.log('catch e', e);
    }
}
````
in the console , the  `catch e ReferenceError: error is not defined(…)` is printed out

**Comment by qinyang912** [comment]
I found that maybe the react-router cause the problem

**Comment by yangshun** [comment]
It works, as demonstrated by the pen here: http://codepen.io/yangshun/pen/NGmQzJ.

**Comment by zpao** [comment]
This appears to be working as expected
