### ISSUE TITLE
Infinite loop in IE10 with number input

### ISSUE THREAD

**Issue by spicyj** [facebook/react#5537]
From an internal thread (https://fburl.com/400759783):

> I'm debugging an issue in IE 10, where React could go into an infinite loop, thus hanging the main thread. This is not observed on IE 11, Chrome nor Firefox. Here is a minimal reproducible fiddle. http://react.jsbin.com/rabesoxahe/1/edit?html,js,output

> On IE 10, press back space in number input or override the current number with anything else (select all, press any key). Observe IE 10 main thread hangs immediately. The issue seems to be caused by setting 'NaN' into type="number" input. I haven't fully figured out why, but avoiding setting non-numeric string as value can mitigate this issue.

> My speculation is that due to how IE 10 raises propertychange event whenever input value is set from JS. If you set a non-numerical value to number input, value is reset to empty string upon retrieval. So we enter a loop of retrieving empty string -> parseInt -> setting 'NaN' -> propertychange -> retrieving empty string -> setting 'NaN' again because 'NaN' !== ''

**Comment by nhunzaker** [comment]
Looks like this was fixed with `045f1a7`. It fixes this by only emitting a change event from `onpropertychange` if the value is different: 

https://github.com/facebook/react/blob/master/src/renderers/dom/client/eventPlugins/ChangeEventPlugin.js#L205-L207

**Comment by spicyj** [comment]
Thanks, I'll close this then unless we hear otherwise.
