### ISSUE TITLE
[Missing CSS] Pointer Events

### ISSUE THREAD

**Issue by liesislukas** [facebook/react#5540]
```
<div style={{display: 'flex', flexDirection: 'row-reverse',  alignItems: 'flex-end',  pointerEvents:'none'}}>
</div>
```

pointerEvents not working.

https://developer.mozilla.org/en/docs/Web/CSS/pointer-events
http://caniuse.com/#feat=pointer-events

**Comment by bloodyowl** [comment]
it works fine for me, what version are you using?

<img width="995" alt="screen shot 2015-11-24 at 10 44 49" src="https://cloud.githubusercontent.com/assets/1688645/11363162/6954f814-9298-11e5-8f33-b157895f83e2.png">

**Comment by liesislukas** [comment]
maybe i had old version, works now.
