### ISSUE TITLE
Does the change of the state always fire the function "render"?

### ISSUE THREAD

**Issue by rubyisapm** [facebook/react#5544]
Here is the example:
```
'use strict';
import React from 'react';
export var componentA=React.createClass({
  componentWillMount(){
    this.setState({
      appList:this.props.appList,
      c:this.props.c
    })
  },
  componentWillReceiveProps(newProps){
    this.setState({
      appList:newProps.appList,
      c:newProps.c
    })
  },
  render(){
    return (
      <ul>
        {this.state.appList.map(function(object,i){
          return <li>
            <input type="text" defaultValue={object} ref={'input'+i}/>
          </li>
        })}
        <li>{this.state.c}</li>
      </ul>
    );
  },
  componentDidUpdate(){
    console.log(this.refs)
    console.log(this.refs.input1.value);
  }
})
```

I use it on page A:
```
var appList=[12,4,5,6,7];
      var c=12;
      React.render(<ComponentA appList={appList} c={c}/>,$('#containerA')[0]);

      setTimeout(function(){
        var appList=[3,4,5,3];
        var d=20;
        React.render(<ComponentA appList={appList} c={d}/>,$('#containerA')[0]);
      },2000);
```

but after the second update, I found that the values of the inputs can't change according to the state that I pass in the second time. 

I also want to know, if there are some UI operation happened during two calls for the "render", is it possible that React can reserve those for users? or just refresh the whole component according the state?

**Comment by seekshiva** [comment]
Using defaultValue will only set the value of the input for the first time. On subsequent changes to the default value, the value of the input won't be updated directly. Use the `value` prop instead.

Read about controlled and non-controlled inputs [here](https://facebook.github.io/react/docs/forms.html)

**Comment by zpao** [comment]
Well said @seekshiva.
