### ISSUE TITLE
If a component have tag span and a text without any tag, the tag will be within span.

### ISSUE THREAD

**Issue by qiuyuntao** [facebook/react#5552]
<img width="424" alt="a0089a8fb40dfd43f53cd6bc75240248" src="https://cloud.githubusercontent.com/assets/8157476/11426237/8ba072be-9495-11e5-8bd0-9322ef68a96d.png">
<img width="432" alt="ed50c816b0337fb04c0cc36d33b3f492" src="https://cloud.githubusercontent.com/assets/8157476/11426238/8bd4dd4c-9495-11e5-9850-cd23d2f061f7.png">

**Comment by edvinerikson** [comment]
I couldn't find any notes about it in the docs (is there any?) but [this](http://stackoverflow.com/a/24470188/3329156) explains why React wraps floating text nodes with a span tag.

**Comment by zpao** [comment]
That answer still holds true.
