### ISSUE TITLE
Extract addons for real or remove warning

### ISSUE THREAD

**Issue by TheLudd** [facebook/react#5553]
When upgrading to react 0.14 there comes a warning among others that says that addons should not be requires through `react/addons', they should instead be required from their own package. First, I would like to point out that I think it is a very good change to put the addons in their separate packages. However I have also noticed that the addons are in fact *not really* put in their separate packages but they just link to the implementation still existing within the react package. 

This brings some trouble to our build. If we browserify an addon (currently only using transition group) that bundle will include all of react. This causes an error when running our app. An alternative for us is to import `react/addons`. This gets rid of the error but leaves us with red warnings. I do consider this a non option as I think it is important to leave the number of warnings/errors to 0. 

As mentioned I do think it is a step in the right direction to extract the addons but I also think it is wrong to require the user to update the import before the change is actually made. Could this be reconsidered?

**Comment by andersekdahl** [comment]
The addons will be removed from the `react` package eventually. The reason that the separate packages currently just requires `react/addons` is to be able to support both ways until they are separated.

Could you elaborate on why having the separate addon packages requiring `react/addons` causes trouble for you?

**Comment by jimfb** [comment]
As @andersekdahl mentioned, you should be able to include the individual addons.  If your configuration is correct, all the addons/components/whatever should share a single copy of React.  If this were not the case, you would run into the same issue for all the components you use (each of which also depend on React).

As @andersekdahl also mentioned, this is just a temporary configuration, until the addons are completely pulled out.

No response for over a month, so I'm going to close this out.  If you have any additional details to provide, we can re-investigate.

**Comment by TheLudd** [comment]
Sorry for not responding. I did mange to solve this recently by bundling all addons I use with the react bundle so this is not critical for me anymore.

> If this were not the case, you would run into the same issue for all the components you use (each of which also depend on React)

No because all other components do `require('react')` and that is easily extracted. The addons require specific file paths that are not really imported in the same manner by anyone else and the paths are not predictable without insight to the react code.

> this is just a temporary configuration, until the addons are completely pulled out. Addons frequently need to interact with React, so many of them may retain references to React

How temporary? It's been like this for a while and react 0.14 is adopted by many other libs. 
Again, I am not critical against the speed of progress or the strategy taken. What I don't like is that it has been decided that you should go a certain way and before it is complete you act as if it has already been done with red error messages for the old way. I do think this is bad and is has consequences that are hard to predict. I hope you consider this if faced with a similar decision in the future.

**Comment by jimfb** [comment]
@TheLudd We maintain backwards compatibility for major versions.  So migration became possible in 0.14 and will likely become required in 0.15.  Releases tend to occur roughly every six-ish months.

The idea is that you should always fix the red warnings, and then you will be able to safely migrate up to the next version.  This is the same strategy we take for all our breaking changes.
