### ISSUE TITLE
TestUtils.findRenderedComponentWithType doesn't work with functional stateless component

### ISSUE THREAD

**Issue by camjackson** [facebook/react#5555]
I've just changed a component from `class Header extends React.Component` to `const Header = (props) => (/*JSX here*/ )`.

Now one of my tests is failing because it can't find an instance of that component where there should be one. This line of code:

```javascript
import Header from '../../header';
//...
let header = TestUtils.findRenderedComponentWithType(myRenderedPage, Header);
//I then need to simulate a click on a button that's inside the header component.
```

Gives this error:
```
Error: Did not find exactly one match for componentType:function Header(props) {
	  return _react2['default'].createElement(
	    //component implementation here
	  );
	} (found 0)
```

I'm *guessing* it's because the function that I'm importing in my test file (i.e. `Header`) is not the same one that was used to create the component in my actual code, because each place that imports a function gets its own instance of it. Which means that the types never match according to TestUtils. And before it must have worked because ES6 classes are unique somehow, so you always import the same thing?

Is this expected behaviour when using functional components, or is there something I'm missing?

**Comment by bouk** [comment]
This is because https://github.com/facebook/react/blob/4f7a2766e4c29c2f25c0807ac21318c3963e6aec/src/renderers/shared/reconciler/ReactCompositeComponent.js#L892-L894 causes https://github.com/facebook/react/blob/4f7a2766e4c29c2f25c0807ac21318c3963e6aec/src/test/ReactTestUtils.js#L45 to have a `null` in the array so it never gets added to the list of components with type.

**Comment by camjackson** [comment]
Thanks for the extra info @bouk.

@jimfb: Seeing as #5642 was rejected, do you know if there are plans to fix this properly? If not, is there somewhere that this limitation should be documented? I've been referring to the 0.14.0 release notes to look at the limitations of stateless components (no refs or lifecycle methods etc), and it would be good if this one was in a similar place.

**Comment by jimfb** [comment]
@camjackson Yes, we're tracking this (I just realized we have https://github.com/facebook/react/issues/4972, so I'm going to close this one out and we can redirect discussion to that issue).

The difficulty is that this is a little non-trivial to fix the testutils (as per the PR), and will likely require an API change.  In the mean time, the work-around is generally to wrap the stateless component in a simple ES6 class, as described in https://github.com/facebook/react/issues/4972.
