### ISSUE TITLE
Server-side rendering of style attribute always causes invalid checksum

### ISSUE THREAD

**Issue by Download** [facebook/react#5560]
I'm working on server-side rendering of a React app using Nashorn. It's going ok, I got a basic skeleton app running. However, I've been getting this warning a lot:

> Warning: React attempted to reuse markup in a container but the checksum was invalid.

What I find strange is that in most cases, the problem seems to revolve around the `style` attribute:

> Instead, figure out why the markup being generated is different on the client or server:
>  (client) ScrollSpacerBefore" style="height:0;" da
>  (server) ScrollSpacerBefore" data-reactid=".fwzq0

The fragment `style="height:0;" ` is missing from the server-rendered piece... If I remove setting the style prop the issue is always resolved...

This gives me the warning:

```js
render() {
	var styleBefore = this.props.direction === 'horizontal' ? {width:this.state.sizeBefore} : {height:this.state.sizeBefore};
	var styleAfter = this.props.direction === 'horizontal' ? {width:this.state.sizeAfter} : {height:this.state.sizeAfter};
	return (
		<div className={'Scroller' + this.props.direction}>
			<div className="ScrollSlider" ref="slider">
				<div className="ScrollSpacer ScrollSpacerBefore" ref="spacerBefore" style={styleBefore} />
				{this.state.renderedItems.map(this.props.renderItem)}
				<div className="ScrollSpacer ScrollSpacerAfter" ref="spacerAfter" style={styleAfter} />
			</div>
		</div>
	);
}
```

While this fixes it:
```js
render() {
	var styleBefore = this.props.direction === 'horizontal' ? {width:this.state.sizeBefore} : {height:this.state.sizeBefore};
	var styleAfter = this.props.direction === 'horizontal' ? {width:this.state.sizeAfter} : {height:this.state.sizeAfter};
	return (
		<div className={'Scroller' + this.props.direction}>
			<div className="ScrollSlider" ref="slider">
				<div className="ScrollSpacer ScrollSpacerBefore" ref="spacerBefore" /* style={styleBefore} */ />
				{this.state.renderedItems.map(this.props.renderItem)}
				<div className="ScrollSpacer ScrollSpacerAfter" ref="spacerAfter" /* style={styleAfter} */ />
			</div>
		</div>
	);
}
```
(notice that I commented out the two style props)

Is this intended behavior? If so, what can I do about it?

**Comment by zpao** [comment]
See #4616 and #4608 for some other discussions. My best guess here is that you're hitting an enumeration order issue. And I think that's supported by the warning message - you can just see that beginning of the `data-reactid`. I'm going to close this out and point at #4616 for followup discussions.

I'm not sure if there's a great resolution yet - might need to ensure any `Object.assign` polyfills you have are up to date (or we might need to make a change to our code).

**Comment by Download** [comment]
@zpao Ok... I see a lot of discussion about the `<Component {...otherProps}>` construct, but as you can see in my code sample, I am not using that here.

In fact, I have never been able to render the `style` attribute server-side. It just does not spit out anything... If i add `style={whatever}` to *any* component I immediately get this warning.

I have been looking through the code of ReactDOMServer but having difficulty to find the relevant bits...

Are you *sure* this is not a separate issue?

As I mentioned I am doing server-side rendering on Java's Nashorn scripting engine. Is there any chance that somewhere in ReactDOM / ReactDOMServer is a dependency on Node that causes this?

> My best guess here is that you're hitting an enumeration order issue. And I think that's supported by the warning message - you can just see that beginning of the data-reactid.

Again, I am not using anything that depends on enumeration order... And the `data-reactid` being last is normal right? From my end it looks like on Nashorn, style is always skipped somehow...

**Comment by Download** [comment]
I did some debugging and I don't see the `style` attribute in the markup rendered server-side. So it's not the order of the attributes, it's a missing attibute.

**Comment by Download** [comment]
I just created a minimal app that just attempts to render a single div with a `style` attribute and that does work... But I also double checked whether there is an ordering problem, but in my real app, there is just no `style` attribute rendered at all.

I am using `react-router` so my root node looks like this:

`ReactDOMServer.renderToString(<RoutingContext {...props} />`

Here the JSX is using spread... I still don't get how that could be related to the style attribute being swallowed, but it's suspicious.

Any tips on where to look for debugging this? I am a bit lost to be honest.

**Comment by zpao** [comment]
> I did some debugging and I don't see the `style` attribute in the markup rendered server-side.

Well, that sounds like a problem.

> I just created a minimal app that just attempts to render a single div with a `style` attribute and that does work...

If that's working, I'm far less inclined to blame React. But I really don't have enough to go on.

I was going to say maybe there's something with your initial state that results in Nashorn treating a value differently. But you said adding `style`to any component results in this warning... except not in the minimal app. This makes me want to blame your app in some way. Do you have something else in your app code that would do something here, like Radium or some other inline styles library that's missing on the client?

We've never seen something like this reported so I'm really hesitant to blame React, but it's possible. I would suggest taking things out until you stop seeing this. Or trying to build up a reduced test case until you can repro, and then share that. Otherwise I'm not sure there's too much more to go on.

**Comment by Download** [comment]
> If that's working, I'm far less inclined to blame React.

Yes. The problem is probably not in React, but in React-Router... I'm trying to create a small app that reproduces the problem. I have so far only been able to reproduce this issue when React-Router is in the mix.

> But you said adding style to any component results in this warning...

I may have jumped the gun there... It seems I can add `style` to *some* components, but not all. I still don't see a pattern. But as I am now pretty sure it has something to do with React-Router and not React itself I won't bug you with it here anymore.  :)

**Comment by zpao** [comment]
Alright, well let us know regardless. I'm curious & ee like to have knowledge of the tricky to diagnose issues, even if they aren't with React itself. React Router is wildly popular so it's likely we'll get some more cross-cutting issues like this.

**Comment by Download** [comment]
@zpao  Ok... weirdest bug ever!

So, it's not React-Router either. It's Nashorn, or my lack of understanding of Nashorn, or both.
I created a [sample project](https://github.com/download/react-server-side-rendering-on-nashorn-example) that demonstrates the issue. I think I now know how to work around the issue, so will do that tomorrow.  :)

Here is the gist: The callback passed to React Router's `match` function accepts three arguments. I bundled these together into a single object that I returned from the method, to inspect on the Java side. If the `props` property is set on it, that indicates a valid route so I call render passing it the `props`. However, somewhere in the roundtrip Nashorn -> Java -> Nashorn the object changes shape in such a way that it triggers this issue.

[Here](https://github.com/Download/react-server-side-rendering-on-nashorn-example/blob/master/src/index.jsx) is the JS code that does routing and rendering (I added a simpler variation as well, which is how I found out about this):

*(note how I'm logging the `props` object just before returning it and then again when it's passed to render)*

[Here](https://github.com/Download/react-server-side-rendering-on-nashorn-example/blob/master/src/Issue5560.java) is the Java code that calls these script functions. It first does the render in two steps (determine route, if valid, render) and then again in a single step (just hardcoded render for route `'/'`).

Here is the logging output I get (combined logging from both Java and JS code):

```
Loading script: react.js
Loading script: react-dom.js
Loading script: react-dom-server.js
Loading script: History.js
Loading script: ReactRouter.js
Loading script: bundle.js
Got twoStepRenderer object: [object Object]
Determining route for path /
   props['routes']=[object Object],[object Object]
   props['params']=[object Object]
   props['location']=[object Object]
   props['components']=function App() {
		_classCallCheck(this, App);

		_get(Object.getPrototypeOf(App.prototype), 'constructor', this).call(this);
		this.state = {
			test: false
		};
	},function Home() {
		_classCallCheck(this, Home);

		_get(Object.getPrototypeOf(Home.prototype), 'constructor', this).apply(this, arguments);
	}
   props['history']=[object Object]
Determinined route for path /. props=[object Object]
RENDER
   props['routes']=[object Array]
   props['params']=[object Object]
   props['location']=[object Object]
   props['components']=[object Array]
   props['history']=[object Object]
Server-side generated markup (using TwoStepRenderer)
----------------------------------
<div data-reactid=".1hggcmp7a4j" data-react-checksum="-681434721"><h1 data-reactid=".1hggcmp7a4j.0">Style is not rendered???</h1></div>
----------------------------------
Simple render...
Match result: error=null, redirect=null, props=[object Object]
Server-side generated markup (using SimpleRenderer)
----------------------------------
<div style="color:green;" data-reactid=".2iask8u45y" data-react-checksum="-1495254873"><h1 style="background-color:green;color:white;" data-reactid=".2iask8u45y.0">Style is not rendered???</h1></div>
----------------------------------
```

Notice the difference between the two props objects. I haven't dug into this much further, but it's changing shape dramatically. I must be doing something very wrong, but there are so little docs on Nashorn yet that I have no idea what I am doing wrong. 

But, I'll be able to work around this for now so that's good. Thank you for your interest and sorry to have bothered you. Who would have thought we could get these kind of weird differences in rendering! :)

**Comment by zpao** [comment]
Hmm, I guess I never posted my initial theory about Nashorn & somehow getting 0, null, undefined mixed up (since `style={{height: undefined}}` wouldn't render anything). But that didn't make sense with other styles so I didn't say it. Maybe something like that actually is happening though. Or the reference in Java-land is losing some state in the casting. It's odd either way. Glad you've sort of figured it out though and good luck!
