### ISSUE TITLE
ReactCSSTransitionGroup delayed animation

### ISSUE THREAD

**Issue by LKay** [facebook/react#5575]
I have something similar to this to handle sliding up-down content (kind of accordion like behaviour). 

``` jsx
<ReactCSSTransitionGroup 
  transitionName="slide"
  transitionEnterTimeout={ TRANSITION_TIMEOUT }
  transitionLeaveTimeout={ TRANSITION_TIMEOUT }
  component="div">
  { expanded && children }
</ReactCSSTransitionGroup>
```

It works fine, when there was no content and `children` are being mounted. The problem occurs when there were some nodes than need to be hidden and replaced by `false` value. In that case it seems that onEnter animation is fired for empty node before executing onLeave animation for previous `children` node making leaving animation delayed by the time of enter animation for empty node. This shouldn't be happening, I think. Empty node shouldn't be animated when entering DOM or onEnter and onLeave animation should be triggered simultaneously. 

I'm using `react-addons-css-transition-group` in version 0.14.3.

**Comment by pnuzhdin** [comment]
There are bad news that animation still unstable in the latest React. I wonder does Facebook use animation in it's own products? Anyway I guess following PR https://github.com/facebook/react/pull/5028 could fix this issue and it should improve stability of the animation moreover.

**Comment by sbialobok** [comment]
I'm running into a similar issue where all my onleave calls are delayed by the onEnter animation time. .  I'm on v 0.14.7 of `react-addons-css-transition-group`

**Comment by gaearon** [comment]
@pnuzhdin Have you had a chance to verify whether #5028 fixes this issue for you?

**Comment by pnuzhdin** [comment]
@gaearon nope, it has become not so important for me

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
