### ISSUE TITLE
Basic Example with Precompiled JSX unexpected token

### ISSUE THREAD

**Issue by LukePettway** [facebook/react#5578]
I'm trying to compile this example and ran into two issues. The first was that it seemed I needed to install babel-cli, which I did and was able to run the next set of commands but then I get this error:
```
SyntaxError: example.js: Unexpected token (8:11)
   6 |       'React has been successfully running for ' + seconds + ' seconds.';
   7 |
>  8 |     return <p>{message}</p>;
     |            ^
   9 |   }
  10 | });
  11 |
```
I'm still new to using React so it's probably a user error but I figured I'd put in an issue just in case.

**Comment by zpao** [comment]
Ah, sorry about that. The directions in there are for Babel 5 but Babel 6 has different behavior.

We'll get that updated but in the meantime, http://facebook.github.io/react/docs/getting-started.html#offline-transform has up to date directions (you need the `react` preset to transform JSX).

**Comment by LukePettway** [comment]
Thanks!

**Comment by ChrisRus** [comment]
+1 

w/babel 6.4.5 this works for me:

```sh
$ babel --presets react example.js --out-dir=build
example.js -> build/example.js
$ babel --version
6.4.5 (babel-core 6.4.5)
```

I presume babel locates the preset in cwd and so installed `babel-preset-react` package in the `examples/basic-precompiled-jsx`. Should probably be registered as a package.json dependency?

Thanks.

**Comment by zpao** [comment]
The instructions in the example are updated (#5387) but we didn't update the starter kit for 0.14.x. I updated that PR so that if we do another release we'll get it updated. Thanks for the reminder.
