### ISSUE TITLE
Document recommended eslint config

### ISSUE THREAD

**Issue by tquetano-r7** [facebook/react#5582]
Not sure if this is intended or not, but I didn't see anything in the documentation about it.

When using react-dom, it requires import of react even if react itself is never required. For example, in our project we have a backbone shim view that we use merely to render the page component:

```
ReactDOM.render(<SomePage/>, this.el);
```

No react-specific transform occurs on the page, however this fails because React is not available. I assume the problem here is the fact React.createElement is needed for the conversion from JSX to JS. While deduceable, this is not very intuitive. Also, this causes linters to fail on the import of React without actually using it anywhere. In both cases, I imagine not desirable behavior.

Any recommendations? I think at bare minimum this should be called out explicitly somewhere (and apologies if it already is and I just missed it).

**Comment by zpao** [comment]
Not sure if it is called out somewhere. We don't do a very good job of discussing suggested tooling.

I think babel might complain if React isn't in scope (or maybe it used to). As for linting, I would recommend using ESLint and the eslint-plugin-react package with [react/jsx-uses-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md) and [react/react-in-jsx-scope](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md) enabled. Those will ensure you have React available and that ESLint doesn't complain about React being unused in the case you described.

**Comment by kkemple** [comment]
hey, i would be willing to pick this up if someone points me in the right direction, is there a section in docs already that covers dealing with linters?

**Comment by gaearon** [comment]
Not really, and I’m not sure where we would add it. Right now the issue is not as bad because we recommend Create React App for beginners, and it includes the necessary lint rules. So perhaps this is not really super important.

**Comment by kkemple** [comment]
can you recommend any other docs issues that need attention?

**Comment by aweary** [comment]
@kkemple there may be some issues mentioned in https://github.com/facebook/react/issues/8035 that might be good to look at. We'd also appreciate any feedback on pending doc PRs!
