### ISSUE TITLE
Always remove keys from children in shallow rendering

### ISSUE THREAD

**Issue by silvenon** [facebook/react#5594]
I have a component which alters the children with `React.Children.map`:

```jsx
// Comp.js
import React, { PropTypes } from 'react';

const Comp = React.createClass({
	propTypes: {
		children: PropTypes.node.isRequired
	},

	render() {
		return (
			<div>
				{React.Children.map(this.props.children, (child) => child)}
			</div>
		);
	}
});

export default Comp;
```

Here I'm testing whether children are the same:

```jsx
// Comp-test.js
jest.dontMock('./Comp');

import React from 'react';
import TestUtils from 'react-addons-test-utils';

const Comp = require('./Comp');

describe('Comp', () => {
	it('outputs the given children', () => {
		const renderer = TestUtils.createRenderer();
		renderer.render(
			<Comp>
				<div />
				<div />
				<div />
			</Comp>
		);
		const result = renderer.getRenderOutput();

		expect(result.props.children).toEqual([
			<div />,
			<div />,
			<div />
		]);
	});
});
```

Because of `React.Children.map` the keys differ (using `{this.props.children}` would work fine, but I want be able to alter them). Should shallow rendering try harder to remove all keys or is there something I'm doing wrong?

**Comment by spicyj** [comment]
Maybe more useful would be for you to use something other than toEqual… though it's unclear what the semantics here should be. Maybe you do actually want to test the keys.

**Comment by silvenon** [comment]
I agree, it's unclear. Since I posted this issue I've found [reagent](https://github.com/airbnb/reagent) which solved my problems.

**Comment by DeveloperCaladan** [comment]
[              <....|....>              ]
