### ISSUE TITLE
IE11 input onChange on mounting

### ISSUE THREAD

**Issue by karczk** [facebook/react#5597]
onChange event is fired on mounting input component to DOM on IE11. It does not occur on IE9, Chrome, Firefox. New value from event is the same as actual (nothing has changed).

Scenario:
1. Initial app render.
2. Mounting component with nested input on user event (action -> hasChanged).

Reproduction:
1. React: 0.14.2, 0.14.3 (min and non-min).
2. Browser: only IE11 and probably IE10 (not tested).
3. Only for specific component structures (I could not find a minimum structure, simple to reproduce)

My input looks like this:
`<input 
    ref="input"
    title={this.props.title} 
    type="text" 
    value={""} 
    placeholder={placeholder} 
    className="form-control"
    onChange={this.handleChange}
    onBlur={this.handleBlur}
    onFocus={this.handleFocus}
    onMouseDown={this.handleMouseDown} />`

Stack trace from IE11 using non-minified react-with-addons, onChange event:

handleChange [Line: 112, Col: 13], NumericInput.jsx
LinkedValueUtils.executeOnChange [Line: 3582, Col: 7], react-with-addons.js
_handleChange [Line: 7982, Col: 3], react-with-addons.js
ReactErrorUtils.invokeGuardedCallback [Line: 10094, Col: 7], react-with-addons.js
executeDispatch [Line: 2827, Col: 5], react-with-addons.js
executeDispatchesInOrder [Line: 2850, Col: 5], react-with-addons.js
executeDispatchesAndRelease [Line: 2290, Col: 5], react-with-addons.js
executeDispatchesAndReleaseTopLevel [Line: 2301, Col: 3], react-with-addons.js
forEachAccumulated [Line: 17829, Col: 5], react-with-addons.js
EventPluginHub.processEventQueue [Line: 2506, Col: 7], react-with-addons.js
runEventQueueInBatch [Line: 10119, Col: 3], react-with-addons.js
ReactEventEmitterMixin.handleTopLevel [Line: 10135, Col: 5], react-with-addons.js
handleTopLevelWithoutPath [Line: 10233, Col: 5], react-with-addons.js
handleTopLevelImpl [Line: 10213, Col: 3], react-with-addons.js
Mixin.perform [Line: 17256, Col: 7], react-with-addons.js
ReactDefaultBatchingStrategy.batchedUpdates [Line: 8850, Col: 7], react-with-addons.js
batchedUpdates [Line: 15332, Col: 3], react-with-addons.js
ReactEventListener.dispatchEvent [Line: 10344, Col: 7], react-with-addons.js

**Comment by syranide** [comment]
Related to #2185 perhaps?

**Comment by karczk** [comment]
@syranide Thx, exactly the same. I didn't notice this association earlier. The reason in my case is a polish text in placeholder. I can confirm that this is a IE bug.

Simple test (raw html):
`<meta charset="utf-8">`
`<body>`
`<input placeholder="podaj wartość" onInput="javascript: alert('test');">`
`</body>`
