### ISSUE TITLE
Simulate.click doesn't propagate event

### ISSUE THREAD

**Issue by hgezim** [facebook/react#5606]
Using `react-bootstrap`'s `Button` and `Input` components, I have a component that renders something like this:

``` jsx
<form ref="form" method="POST" onSubmit={this._onSubmit}>
  <Input
    ref="new_password"
    name="new_password"
    label="New password"
    type="password" />

  <Input ref="new_password_confirm"
    name="verify_new_password"
    label="Repeat, please"
    type="password" />

  <Button type="submit" onClick={this.hola} bsStyle="primary">Save New Password</Button>
</form>
```

In my test, I call `click` on `Button` but `this.hola` handler gets called not `this._onSubmit`:

``` js
var submitButton = TestUtils.findRenderedComponentWithType(renderedForm, Button);

var submitButtonDOM = ReactDOM.findDOMNode(submitButton);

TestUtils.Simulate.click(submitButtonDOM);
```

**Comment by ncthis** [comment]
This is more of a question to `react-bootstrap` than `react`, but, what are you trying to achieve by having the both `onSubmit` handler for form and `onClick` handler for button?

**Comment by hgezim** [comment]
I don't need `onClick` for button. I was just illustrating the problem.

**Comment by hgezim** [comment]
Not all `props` were being passed down to DOM component.

**Comment by gaearon** [comment]
It’s not clear to me if this is a React bug report or a `react-bootstrap` question.

I’ll close this as stale, but if it is a problem, please file a new issue with a reproducible example, preferably without third party libraries. As well as please explain what you expected to happen, and what actually happens.
