### ISSUE TITLE
Change devtools install message on file: URLs

### ISSUE THREAD

**Issue by spicyj** [facebook/react#5608]
When visiting a file: URL with the devtools installed in Chrome, you get:

> Download the React DevTools for a better development experience: https://fb.me/react-devtools

because they don't work with file URLs. That might be fixed on the Chrome side too (https://code.google.com/p/chromium/issues/detail?id=529548) but we could improve the message here to say something like

> Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools

**Comment by Hum4n01d** [comment]
Why was this closed?

**Comment by spicyj** [comment]
It was fixed by the pull request #5610.

**Comment by Hum4n01d** [comment]
@spicyj Ok but I’m having this issue with version `15.4.2`

**Comment by Hum4n01d** [comment]
@spicyj My bad, I’m getting the new error

**Comment by Hum4n01d** [comment]
@spicyj Why does this warning exist?
