### ISSUE TITLE
SVG attributes support is missing the "filter" attribute

### ISSUE THREAD

**Issue by tombigel** [facebook/react#5612]
SVG attributes support is missing the "filter" attribute which is the only cross-browser way to apply SVG filters (IE and Edge)

**Comment by tombigel** [comment]
Sorry, closing and doing a simple pull request instead

**Comment by tombigel** [comment]
added a pull request https://github.com/facebook/react/pull/5613

**Comment by gaearon** [comment]
Fixed via #5714. Cheers!
