### ISSUE TITLE
dangerouslySetInnerHTML doesn't apply the style or properties

### ISSUE THREAD

**Issue by juztinlazaro** [facebook/react#5616]
Hi guys, got an issue on dangerouslySetInnerHTML my problem is it decode the HTML entities but it doesn't apply the style or properties.
 
here. Thanks in advance guys.

https://jsfiddle.net/up8j9aqz/1/

**Comment by jimfb** [comment]
It doesn't decode the entities. It puts them into the markup, directly (that's what dangerously set does). The browser sees the entities and renders them as text (that's what browsers do). This is not a bug. I modified your fiddle to do what I believe you wanted: https://jsfiddle.net/b5Lt87kb/
