### ISSUE TITLE
Documentation about refs and shallow rendering

### ISSUE THREAD

**Issue by rkovacevic** [facebook/react#5620]
Docs say about refs in shallow rendering:

> Shallow testing currently has some limitations, namely not supporting refs. 

However, if I shallow render a component, the `ref` property is present correctly. We're using it in react-shallow-testutils like this:

https://github.com/rkovacevic/react-shallow-testutils/commit/b20af04fef4ade7df111e131792bb178794a789a

Is this feature stable, can we rely on `ref` being present?

**Comment by jimfb** [comment]
I don't think the presence of refs on the elements is what those docs are referring to when they say refs aren't supported.  But regardless, using string refs is a legacy pattern that will likely go away eventually, so I would try to avoid relying on them (the code you linked appears to rely on them).
