### ISSUE TITLE
Event bubbling of onScroll does not appear consistent with the native behavior.

### ISSUE THREAD

**Issue by scvnc** [facebook/react#5622]
I have two nested elements that can be scrolled but I only want to listen to the parent scroll event.

````
<div onScroll={handleScroll}>
    
    <textarea>...</textarea>

</div>
````

When the textarea is scrolled, the event bubbles to the parent onScroll event. Here is a working  example:

https://jsfiddle.net/pv0vp44q/

Bug, feature? It appears like it ought not bubble [according to the spec](http://www.w3.org/TR/DOM-Level-3-Events/#event-type-scroll). My workaround is to verify the target element when handling the scroll event or maybe preventing the textarea from sending it's scroll events.

Tested with React 0.14.3 Chrome/IE11

**Comment by jimfb** [comment]
Our synthetic event system allows us to smooth out the events API.  We also make some minor changes where we think that our behavior is better than the browser's behavior.  In general, it's easy to ignore a bubbling event but it's harder to bubble an event up, so we bubble up and let the user ignore the bubbling event if they don't care about the event.  For more information, there is an interesting (semi-related) article here: http://www.bennadel.com/blog/2924-image-load-and-error-events-bubble-up-in-reactjs.htm

Anyway, I'm assuming this was an intended feature.  If @syranide or @spicyj disagree, they can re-open.  Feel free to continue the discussion in this thread.

**Comment by spicyj** [comment]
Yeah, all our events bubble. I don't feel great about this decision any more but this is intended behavior.

**Comment by scvnc** [comment]
Thanks for the info :+1:
