### ISSUE TITLE
react-addons-update@0.14.3 requires a peer of react@^0.14.3 but none was installed.

### ISSUE THREAD

**Issue by robtg4** [facebook/react#5624]
I get "react-addons-update@0.14.3 requires a peer of react@^0.14.3 but none was installed" error but I am on latests react update - why is this (npm install react-addons-update --save) not working?

**Comment by mattstyles** [comment]
npm v3 wont install peer deps automatically. Just install react first and you'll be fine.

With v2 it works as you're expecting.

**Comment by zpao** [comment]
@mattstyles is probably right. Peer dependencies should always be explicitly included in your `package.json` (`npm install --save react react-addons-update`)
