### ISSUE TITLE
Missing onLoad and onError events on SVG <image> tag

### ISSUE THREAD

**Issue by tombigel** [facebook/react#5626]
SVG `<image>` is supposed as far as I know to support at least the same onload and onerror events `<img>` supports.

From looking at React code the events are handled on specific elements in `ReactDOMComponents.js` in `trapBubbledEventsLocal, mountComponent, unmountComponent`.

It would be easy to create a pull request to add 'image' to these cases, but it seems that there is a separation between js files that handle DOM and SVG in the codebase that this might collide with.

Am I correct and there is more to it than just adding more cases? Or these functions are the right place to also handle SVG image?

**Comment by savelichalex** [comment]
+1 to add this handler

**Comment by niwinz** [comment]
+1

**Comment by shalanah** [comment]
+1

**Comment by gaearon** [comment]
If you’re interested in this, could you please send a PR? Yes I think `ReactDOMComponent.js` is the right place for this.

**Comment by Flaque** [comment]
@gaearon I'm gonna try this.

**Comment by Simek** [comment]
I've added PR adding onLoad and onError events to SVG, but we are still missing few others like onUnload, onResize, onScroll, onZoom etc.

**Comment by mdogadailo** [comment]
`<image />` load and error events were fixes here #9042

**Comment by zabojad** [comment]
@mdogadailo that doesn't seem to have affected `<svg />` load and error events...

**Comment by mdogadailo** [comment]
@zabojad yes, but this ticket about `<image />` tag, not about `<svg />` element like here #9607

**Comment by aweary** [comment]
This was resolved by https://github.com/facebook/react/pull/9042/ 🍾

**Comment by SahidHernandez** [comment]
@aweary seems that onLoad event is not getting dispatched on IE11 (it is supported)

**Comment by gaearon** [comment]
(Let's track that in https://github.com/facebook/react/issues/11058)

**Comment by michalpuskel** [comment]
+1 
`<svg />` `onLoad` is still not working
