### ISSUE TITLE
React Virtual DOM (v 0.13.2) on ios 

### ISSUE THREAD

**Issue by Oleksandr-Silin** [facebook/react#5627]
Hi,
I have sorting for table. It works as expected if site opened at desktop browser or android device, but on ios (8.4, 9.1) browsers (safari, chrome) nothing happens (only sort icon changes state). 

Idea: 
I have sorted source of items, each of them map with custom ItemRow component(which implements shouldComponentUpdate - to avoid unnecessary renderings on sort order change) . 

```javascript
 <tbody>
 {viewSource.map(renderRow)}
</tbody>
```

```javascript
 function renderRow(item) {
            return <ItemRow key={item}
                item={item}/>
        }
```

What have i missed for ios browsers?

**Comment by jimfb** [comment]
There is not enough information here for us to debug, but it sounds like a bug in user land.  It sounds like maybe your array isn't getting sorted correctly, or your `shouldComponentUpdate` is incorrect - though it's a little hard to imagine why either of those would be browser-specific.

Try removing your `shouldComponentUpdates` from all components, and printing your jsx tags from render immediately prior to returning them.  That may give some insight into what's going on there.

If you have a super simple testcase (jsfiddle) that demonstrates a bug in the React core, we can investigate further.

**Comment by Oleksandr-Silin** [comment]
@jimfb Thank you for pointing me to create testcase.
While preparing it http://jsfiddle.net/fEsYt/198/  i've found that issue is in sort function. Anyway you can check that it works on Android and desktop, but not on ios - and that's odd.

**Comment by daukantas** [comment]
thank you .
