### ISSUE TITLE
Stop showing warnings as errors.

### ISSUE THREAD

**Issue by btipling** [facebook/react#5632]
I can't debug my own code because of the warnings spam. The warning spam is beyond my control because react router is having conflicts with history that they haven't resolved. It's very frustrating to experience this:

![2015-12-09 at 3 36 pm](https://cloud.githubusercontent.com/assets/249641/11702518/248973ea-9e8c-11e5-988c-fbb5ef3f9b4e.png)

without having any recourse short of installing out of date deps. Show warnings as warnings. That's what `console.warning` is for.

**Comment by conorhastings** [comment]
if i recall correctly, React uses `console.error` so that you have access to the stack trace (https://github.com/facebook/react/issues/4216) Having said that, these errors aren't coming from React, they're coming from the history module (https://github.com/rackt/history/blob/83f1a6382bd03b04d334958f44be6c9362b920a5/modules/useQueries.js#L108-L111 ) using the warning module ( https://www.npmjs.com/package/warning )

**Comment by zpao** [comment]
As mentioned these are not coming from React but from something else (use the stack trace to find the guilty party). Encourage react-router or whomever to do some improvements to dedupe warnings (eg, in React, to reduce spam we attempt to dedupe on the type and location of the warning).

**Comment by Elijen** [comment]
@zpao Why can't `console.warning` be used here? Stack trace is available using `console.trace`

**Comment by gaearon** [comment]
They are coming from React Bootstrap, and next version will fix them.

**Comment by Elijen** [comment]
@gaearon This is just an example. I know this error should be fixed by React Bootstrap, but what concerns me is the React behavior where _warnings_ are printed as _errors_ which makes debugging and development hard (can't filter these out from JS console).

That's why I think usage of `console.warning` should be considered.

![react](https://cloud.githubusercontent.com/assets/1304054/17087448/887ea42e-520a-11e6-98bb-c03420b32066.png)

**Comment by brigand** [comment]
@Elijen you're expected to prevent the warnings by fixing your code. If they're not actionable then that's a problem with those specific warnings, not warnings in general.

**Comment by ghost23** [comment]
I do agree with @Elijen. A warning should be logged via console.warn() rather than console.error(). That would make filtering in dev tools more convenient. You could still print the stack trace with an extra console.trace() call.

**Comment by loktar00** [comment]
Agree with this as well. We should all fix and prevent warnings of course, however the argument is a `warning` is not an `error` and shouldn't display as such.

**Comment by kaitlynbrown** [comment]
+1 for this. It would be really nice to have warnings show up in the *warnings* tab in dev tools and not the errors tab.

**Comment by RSSfeed** [comment]
maybe this code snippet would help some of you. I'm using this myself:

```ts
const errorsToWarn: string[] = [
    "Warning:",
];
const oldConsError = console.error;
console.error = function(...args: any) {
    let toWarn: boolean = false;

    if (typeof args[0] === 'string') {
        errorsToWarn.map(function(_s: string) {
            if (args[0].startsWith(_s)) {
                toWarn = true;
            }
        })
    }

    toWarn ? console.warn(...args) : oldConsError(...args);
}
```

**Comment by stoplion** [comment]
2020 and still getting warning spammed :(

**Comment by nickperkinslondon** [comment]
I can't believe it's 5 years later and this has never been fixed!  Why not?  Am I missing something?

**Comment by andrewfmbs** [comment]
Yeah I don't get it. My QA team isn't so concerned with whether or not we have a key on an element (although you may argue they should, that's another conversation), and digging through to find an actual error is time consuming.

**Comment by DieserMerlin** [comment]
This is so annoying, why is this still the case?
Just print warnings as warnings and errors as errors... 😅

This is especially uncomfortable if the warnings come from a library you depend on (in my case material-ui). In this case you can't do anything about the actual warning but always think there's an error in your code as react shows the warnings as errors.

**Comment by Knuds1** [comment]
I agree with @DieserMerlin. These are often errors which I cannot fix or that are unrelated to my assigned tasks in a project. It becomes hard to spot when a real error occurs.

Showing warnings as errors is very unconventional and should at least be configurable.

**Comment by Lokua** [comment]
"our warnings are just as important as your errors" - React

**Comment by dman777** [comment]
I hate this, it is incorrect. Why??!?

**Comment by vadimrostok** [comment]
Fix it and remove the controversy? Stop generational discussions on this issue? Nope. No matter if it's good or bad if they're talking about you. Or at least this is the best explanation I was able to come up with.
