### ISSUE TITLE
Anchor Download attribute not handling filename correct

### ISSUE THREAD

**Issue by spydon** [facebook/react#5635]
According to [w3c](http://www.w3.org/TR/html5/links.html#attr-hyperlink-download), if the download attribute is set, the download dialog box should prompt with the filename set in that attribute and not the file referred to in href.

I have only tried with react 0.14.2, but it doesn't seem like there have been any change fixing this issue in the master branch.

**Example:**
`<a href="http://localhost/test.jpg" download="image.jpg">Download</a>`

**Expected behavior:**
A browser download dialog box with image.jpg

**Actual behavior**
A browser download dialog box with test.jpg

**Comment by syranide** [comment]
If the attribute is present in the source (which it should be), then this is the browser not having adopted this specific feature yet.

**Comment by spydon** [comment]
Ah, apparently it only works for same-origin.
