### ISSUE TITLE
image request pending while frequently refreshing page

### ISSUE THREAD

**Issue by sartrey** [facebook/react#5645]
i use server rendering and write dynamic value in `render` function (such as: `Date.now()`).
this may not be proper, and react shows warning in console.
`React attempted to reuse markup in a container but the checksum was invalid.`

if i refresh tab frequently, image request in the tab will be pending.
the problem dose not disappear even after i remove the dynamic value.

env: React 0.14.2, Chrome 47, OSX 10.11.1, babel 5.x

**Comment by sartrey** [comment]
fix my issue
server rendering is not reason

just in Chrome, to refresh tab frequently will always cause image request pending

**Comment by jimfb** [comment]
Sounds like the issue is not related to React.  If you disagree, let me know and we can reopen/reinvestigate.
