### ISSUE TITLE
How to use server side rendering in React in Expressjs app?

### ISSUE THREAD

**Issue by wzup** [facebook/react#5656]
Documentation doesn't have neither any examples nor links to examples.

I want to know how, step by step, to use React on a server in an Expressjs application. How component files should look, how they are connected to templates and layouts, how Expressjs' `response.render('template')` should behave if I render react on server, how to include React components in a template, should components be compiled in advance, and many other questions.

In particularly, I have a Dust.js template that is rendered this way in a controller:
```
router.get('/', function(req, res, next) {
    res.render('index', {
        title: 'Title',
        page: 'index',
        foo: 'Foo'
    });
});
```
I compile and concat my `js` assets in one `app.js` file and include it in my template like this:
```
        <script src="/js/app.js" type="text/javascript" charset="utf-8" async></script>
    </body>
</html>
```

And now I want to know how to use React on a server. How I need to change my current routine to compile/render react AND my template on a server.

For now when I use `ReactDOMServer.renderToString` and `ReactDOMServer.renderToStaticMarkup` I get these errors and I don't know what does it mean because React documentation doesn't have any errors explanations:

`Error: Invariant Violation: renderToStaticMarkup(): You must pass a valid ReactElement.`
`TypeError: Cannot read property '__reactAutoBindMap' of undefined`

**Comment by iamdustan** [comment]
@wzup GitHub issues are used to track bugs in React core, not so much usage advice. For that it’s recommended to use StackOverflow or join http://reactiflux.com/ or one of the IRC channels. Universal rendering is a complex topic with many variables and tradeoffs.

Seeing the numerous tools you have in place you may also want to google around for some blog posts, and/or write one for others once you solve it.

**Comment by jimfb** [comment]
As @iamdustan said, we use github issues to track bugs in the core.  @iamdustan listed a few good places to have discussions like this.

**Comment by wzup** [comment]
There are are some examples here:
https://github.com/facebook/react/wiki/Examples
