### ISSUE TITLE
Stateless Component Performance

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#5660]
Are stateless components optimized using React.createElement so they arent re-rendered if the props havent changed?

https://facebook.github.io/react/docs/reusable-components.html#stateless-functions

If so, it would be nice to mention that in the docs. Because then there is a significant difference between the following:

```js
SomeComponent = (props) => {
  return <div>{props.hugeList.map(/*...*/)}</div>
}

Performant = (props) => {
  return <SomeComponent hugeList={props.friends}/>
}

NotPerformant = (props) => {
  return SomeComponent({hugeList: props.friends})
}
```

And it may not seem evident to someone thinking that they're just functions...

**Comment by jimfb** [comment]
No, afaik, there is no such optimization at this time.
