### ISSUE TITLE
Event order changes with input field being present on initial render.

### ISSUE THREAD

**Issue by jasonjohnson115** [facebook/react#5662]
This is difficult to explain, so I created a [jsfiddle](https://jsfiddle.net/jasonjohnson115/8k1kcfqs/). The code runs fine as is. Changing the first variable to null and rerunning will display the issue I'm experiencing. I'm not sure if this is expected behavior. Thanks in advance for any guidance.

Note: I'm experiencing this on version 0.13.3. I created the fiddle on version 0.14.0 to be sure that upgrading wasn't going to resolve my problem.

**Comment by jasonjohnson115** [comment]
By the way, I'm experiencing this on version 0.13.3. I created the fiddle on version 0.14.0 to be sure that upgrading wasn't going to resolve my problem.

**Comment by jimfb** [comment]
I'm pretty sure this is just an artifact of the order that the document-level event listeners get registered.

React uses a synthetic event system. The interaction between native events and synthetic events is strictly undefined. Sebastian wrote a post about this once-upon-a-time, how native and synthetic event systems are, by and large, inherently not interoperable.
