### ISSUE TITLE
`if (__DEV__) { warning() }`

### ISSUE THREAD

**Issue by jonathanp** [facebook/react#5664]
I've noticed that calls to the `warning()` function often is wrapped in a `if (__DEV__)` conditional, which will be compiled down to redundant `"development" !== 'production'` gates in the build process. E.g. this code from `EventPropagators.js`...

```js
function accumulateDirectionalDispatches(domID, upwards, event) {
  if (__DEV__) {
    warning(
      domID,
      'Dispatching inst must not be null'
    );
  }
  [...]
}
```

...will be compiled to...

```js
function accumulateDirectionalDispatches(domID, upwards, event) {
  if ("development" !== 'production') {
    "development" !== 'production' ? warning(domID, 'Dispatching id must not be null') : undefined;
  }
  [...]
}
```

It doesn't matter in the end since that whole block will be removed by the dead code elimination in Uglify but I guess the source files could be cleaned up to don't have all those `if (__DEV__)` checks, or am I missing something? :)

**Comment by conorhastings** [comment]
the checks are there so the warnings actually fire in NODE_ENV="development" , there meant to be there for the dev process. Then when building for production as you reference above, dead code elimation will remove for speedier production app.

**Comment by jonathanp** [comment]
Ah yes, maybe my question wasn't clear enough. :) I understand why you would want the warnings in dev mode but not in production, but I don't understand why `if (__DEV__)` is needed around `warning()` if they both produce `if ("development" !== 'production')` checks.

**Comment by zpao** [comment]
Not all `warning` calls are wrapped in `__DEV__` checks, eg https://github.com/facebook/react/blob/master/src/addons/ReactFragment.js#L38-L42. So we need to do this unless we get really strict (and write a lint rule enforcing) that we're always inside a `__DEV__` check.

Our internal transform just removes `warning` calls entirely for prod builds but we need to be more conservative here to support the hybrid dev/prod runtimes for npm.

**Comment by jonathanp** [comment]
Ok cool, so in other words it would have 0 effect both in development and production environments to remove e.g. [this line](https://github.com/facebook/react/blob/master/src/isomorphic/classic/class/ReactClass.js#L754).

Thanks for the info, I'm just curious!
