### ISSUE TITLE
React JS display all data in the text field for particular selected ID

### ISSUE THREAD

**Issue by param-magi** [facebook/react#5665]
The following is the react render it works successfully when I get the single input tag and error occurs (Error: Parse Error: Line 59: Adjacent JSX elements must be wrapped in an enclosing tag
        at http://localhost/PHP-React-Demo/update_record.html
    
    ... >                            
                                    ^
    	
    
    * @param {object?} options Options to pass to jstransform) when render multiple input text fields.
    render : function(){ 
                          var currentId = this.state.currentId;
                          
                          var phpData = this.state.phpData || [];
                          
                          var selected = phpData.filter(function (item) {
                              return item.id === currentId;
                          });  
                            DBdata = this.state.phpData || [];
                            return (
                            <div>
                            <form >
                            Select ID :
                              <select onChange={this.handleChange}>
                              {DBdata.map(function(d){
                                       return(
                                        <option name="id" value={d.id}>{d.id}</option>
                                       );
                              })};
                              </select>
                              <button name="submit" value="submit">update</button><br/>
                            {selected.map(function(datafield){
                              return(
                                // <input type="text" value={datafield.name} />//if I remove this comment it shows the above error
                                <input type="text" value={datafield.email} />                            
                              );
                            })}
                           </form>
                           </div>
                          )}
                  });
                  React.render(
                    <DataInTableFormat source="http://localhost/PHP-React-Demo/index.php" />,
                      document.getElementById('Table-data')
                    );

**Comment by jimfb** [comment]
You can't have something like `return <div></div><div></div>` because you must return only a single jsx element, and there are two adjacent jsx elements there.  Instead try something like `<div><div></div><div></div></div>` which is a single jsx tag with two children.

This is a usage question, and we try to keep github issues for tracking bugs in the React core, so I'm going to close this out. Please ask usage questions on StackOverflow in the future.
