### ISSUE TITLE
any plan to de-couple react-dom from react ?

### ISSUE THREAD

**Issue by benpptung** [facebook/react#5667]
Since react-dom introduced, I am sorry it is really buggy to me how to bundle React in my projects, because the following line in index.js: 
    
    module.exports = require('react/lib/ReactDOM');

It means the `react-dom` will require the file `ReactDOM.js` directly, and I have to require the same source code too.

However, to save the time to bundle react and make my React component unaware whether it is `react` or `react/addons`, I always bundle the `react/dist/react-with-addons.min.js` or `react/dist/react.min.js` directly, and use browserify expose them as `react` for other module.

It makes my component can always start with the following line:

    var React = require('react') // whether it is react or react/addons

Because usually I bundle react in a site-core.js for all other app in the website, the site-core.js is completely independent. It use browserify to expose `react` for other module to require.

If some components want react, and some components want react/addons, till the end, you have to require react/addons. The component only need `react` will get nothing, so I expose `react/dist/react-with-addons.min.js` as `react` for all.

Now, the problem is, react-com always want to require `react/lib/ReactDOM`, it will require a duplicated React when i bundle `react-com`. I see `require('react/lib/ReactDOM')` as a temp solution, so I am asking if any plan to de-couple react-dom from react ? Sorry for asking :)

**Comment by gaearon** [comment]
>If some components want react, and some components want react/addons

Can you change the components to depend on the individual addon packages released with 0.14, such as [react-addons-transition-group](https://www.npmjs.com/package/react-addons-transition-group)?

**Comment by zpao** [comment]
The plan is to decouple these. We don't have a solid timeline for that but it's the plan. Sorry it's causing problems. I'm going to close out since there isn't anything immediately actionable here.

**Comment by benpptung** [comment]
Hi @gaearon , yes, I will. All my react components rely on `react`, no matter it is `react` or `react/addons`. It is simply to add the separated add-on modules in the future.

Hi @zpao, I am wondering if we can update the code `index.js` in `react-dom` as something similar to the following, I edited it from the `react-dom/dist/react-dom.js`.
````
'use strict';

var React = require('react');

if (React) {
  module.exports = React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
}
else {
  var g;

  if (typeof window !== "undefined") {
    g = window;
  } else if (typeof global !== "undefined") {
    g = global;
  } else if (typeof self !== "undefined") {
    g = self;
  } else {
    g = this;
  }

  if (g.React) {
    module.exports = g.React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
  }

}
````

I know you might have other concerns that I don't know :)
It is just an idea for your reference, and I've put it on [benpptung/react-dom-temp](https://github.com/benpptung/react-dom-temp/blob/master/index.js) for my personal React component starter kit [benpptung/appstackr-client-generator](https://github.com/benpptung/appstackr-client-generator)
