### ISSUE TITLE
remove install warning that react-tools prefers to be installed globally 

### ISSUE THREAD

**Issue by Pomax** [facebook/react#5668]
NPM runs package script calls (`npm test`, `npm run yourownsscript`, `npm postinstall`, etc) with the execution environment appended with the `./node_modules` dir, so that CLI packages *don't* need to be installed globally to work propery.

Currently there is an installation warning `npm WARN prefer global react-tools@0.13.3 should be installed with -g`, but this has not been necessary for a few NPM major versions now, so it's worth removing that warning to keep the install log clean.

**Comment by zpao** [comment]
`react-tools` isn't supported anymore so we have no plans to push a new release to remove the `"preferGlobal"` setting.

**Comment by Pomax** [comment]
I love inheriting projects with no longer maintained dependenciess - what was it replaced with? Also, even if you have no plans to push a new release for preferGlobal, please very much do push a release that turns on the flag that causes npm to warn "this project is no longer maintained" as a courtesy to everyone who's inherited a project that used it.

**Comment by brigand** [comment]
@Pomax it's replaced by babel https://babeljs.io/

**Comment by Pomax** [comment]
cheers

**Comment by zpao** [comment]
We did have a message actually for a little while but it interfered with React Native (which was still using react-tools for historical reasons). But that's no longer the case so I'll push that message back in. It doesn't require a new release so we won't change the preferGlobal bit.

**Comment by Pomax** [comment]
ah, cool. Thanks!
