### ISSUE TITLE
Value attributes in invalid components are not re-rendered properly

### ISSUE THREAD

**Issue by luanpotter** [facebook/react#5669]
If I add a `value` attribute in a `div` tag, or other tag that shouldn't have a `value` attribute, it will work and add the attribute, but it will not be updated properly: that is, if it depends on the state, `setState` will trigger render but won't change the value in the real dom. I'm guessing this has to do with incompatibilities between the virtual and the real dom on what's allowed on such tags (the virtual dom knows you can't add value, but real dom allows).

Either way I think it is bad that it fails silently, I believe it should either work completely or give always an error.

A simple example that reproduces the problem:

    <html>

        <head>
            <script src="https://fb.me/react-0.14.3.js"></script>
            <script src="https://fb.me/react-dom-0.14.3.js"></script>
        </head>

        <body>
            <div id="container"></div>
            <script>
            var HelloMessage = React.createClass({
                getInitialState: function() {
                    return { count: 0 };
                },
                inc: function() {
                    this.setState({ count: this.state.count + 1 });
                },
                render: function() {
                    var btn = React.createElement('button', { onClick: this.inc }, 'hey');
                    return React.createElement('div', { value: this.state.count }, 'Count: ' + this.state.count, btn);
                }
            });

            ReactDOM.render(
                React.createElement(HelloMessage),
                document.getElementById('container')
            );
            </script>
        </body>

    </html>

As you can see, if you click the button the content of the div is updated, but it's `value` attribute in the dom is not (this happens both on Chrome 48.0.2564.22 dev and Firefox 41.0).

**Comment by cody** [comment]
Looks like the same as issue #3799.  The workaround is to not use `value` but `data-value`. But the other issue is still open, so hopefully it will get fixed one day.

**Comment by jimfb** [comment]
Fixed: http://jsfiddle.net/utp5br4g/
