### ISSUE TITLE
Unclear documentation about generating production build

### ISSUE THREAD

**Issue by seekshiva** [facebook/react#5672]
It is mentioned in the [react downloads page](http://facebook.github.io/react/downloads.html) that `NODE_ENV` needs to be set to 'production' for development warnings to be disabled. And it suggests using `webpack.DefinePlugin`.

---------------
After searching for quite a bit, I found from @petehunt's [webpack-howto](https://github.com/petehunt/webpack-howto) project that, I could declare it like this:

```
// definePlugin takes raw strings and inserts them, so you can put strings of JS if you want.
var definePlugin = new webpack.DefinePlugin({
  __DEV__: JSON.stringify(JSON.parse(process.env.BUILD_DEV || 'true')),
  __PRERELEASE__: JSON.stringify(JSON.parse(process.env.BUILD_PRERELEASE || 'false'))
});
```

I tried setting:
```
    new webpack.DefinePlugin({
      NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development')
    }),
```

but it didn't work.

---------------
I had to manually debug why setting NODE_ENV wasn't removing the warning like it said it would.

It takes around 50s to generate a production build, when I do `webpack -p`. So every small change I make, I need to wait for 50-70s to check the change.

---------------
Finally I found that react code does this check:
```
process.env.NODE_ENV !== 'production'
```

and in the above setting, NODE_ENV was being passed as a global variable to my code.

```
    new webpack.DefinePlugin({
      NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development')
    }),
```
Since `NODE_ENV` is passed as a global variable to my code, the `process.env.NODE_ENV` that react checks is uninitialised.

Seems like I actually need to set the process variable itself using `DefinePlugin`.

---------------
When I tried:
```
    process.env.NODE_ENV = process.env.NODE_ENV || 'development'
    new webpack.DefinePlugin({
      process: process,
    }),
```
I got some cyclic dependency error.

----------------
Finally, I did this hack:

```
    process.env.NODE_ENV = process.env.NODE_ENV || 'development'
    new webpack.DefinePlugin({
      process: JSON.stringify({
        env: process.env
      }),
    }),

```

This works, and the development warnings have been removed.

But, as it turns out, it is not quite as small as it should be:

**Without setting NODE_ENV**
```
Time: 69431ms
                Asset     Size  Chunks             Chunk Names
     vendor.bundle.js  1.04 MB       0  [emitted]  vendor
               app.js   503 kB       1  [emitted]  merchandise_booker
```

**NODE_ENV=production**
```
Time: 56195ms
                Asset     Size  Chunks             Chunk Names
     vendor.bundle.js  1.09 MB       0  [emitted]  vendor
               app.js   505 kB       1  [emitted]  merchandise_booker
```

Setting NODE_ENV=production actually increases the file size.

**Comment by zpao** [comment]
Our documentation here is not a step by step process and could use some improvement, you're right. Sorry you had trouble. I'm going to close out and I filed #5679 for improving our docs - your issues are relevant but are anecdotal and we'd benefit from a concise description with action items.

As for the file size - all you've done is some string replacement (`s/process.env.NODE_ENV/'production'/`). If you want to reduce the file size as well you'll need to use something that does dead code elimination to remove the `if ('production' !== 'production')` blocks.
