### ISSUE TITLE
Improve documentation for using React with Webpack

### ISSUE THREAD

**Issue by zpao** [facebook/react#5679]
#5672 made it clear that we could do better. #5658 improved the situation slightly but we still don't discuss how to actually use these things together.

Quickest short term fix would be to explicitly describe how you would use DefinePlugin to do what envify is doing - https://twitter.com/dan_abramov/status/592692202335301636 is nice and concise.

Longer term I'd like to have some more flushed out docs around using React from start to finish with both browserify and webpack (and maybe more if needed). But let's start simple.

**Comment by vitorbal** [comment]
@zpao The [downloads page](https://facebook.github.io/react/downloads.html) has a mention about this already. How about we use the same wording for the [getting started page](https://facebook.github.io/react/docs/getting-started.html) and expand it to include the DefinePlugin example from Dan?

**Comment by applegrain** [comment]
> How about we use the same wording for the getting started page and expand it to include the DefinePlugin example from Dan?

Could I reopen #5658 to add this or should I open a new PR?

**Comment by vitorbal** [comment]
@applegrain I got a PR going at #5686 :)

**Comment by applegrain** [comment]
oh nice! :+1:

**Comment by zpao** [comment]
Reopening to track the longer term ideas.

**Comment by SudhanvaMG** [comment]
Can i work on this ? , if it is not taken

**Comment by kevinold** [comment]
@zpao Let's chat this week at React Rally about what your goals are for this.  I've used React with simple and complex webpack builds, so I might be able to help.

**Comment by gaearon** [comment]
We have documentation on turning on production mode now.
