### ISSUE TITLE
Remove react/lib/webcomponents.js from NPM package

### ISSUE THREAD

**Issue by stubailo** [facebook/react#5681]
In React 0.13.x, this file wasn't shipped as part of the NPM package; it looks like some changes happened in the build system since, and the file is now being shipped to NPM, perhaps unintentionally. Some less sophisticated build systems that don't ignore unused files might be bundling it for the client.

Perhaps this isn't the only such change? It could be worth investigating if there are other unused files.

**Comment by zpao** [comment]
Thanks for the heads up!
