### ISSUE TITLE
Click events delayed until after render, causing clicks on incorrect nodes

### ISSUE THREAD

**Issue by zachhale** [facebook/react#5682]
I've got a weird one here which will take a bit to explain. In my app we have a filter drop down menu which when opened, shows options which appears over a large chunk of content which is composed of a number of clickable tiles, one of which appears underneath the filter menu.

When the filter menu is opened and clicked, react is watching an onClick event which responds by doing `event.preventDefault()` and `event.stopPropagation()` then does a `setState()` triggering the URL to update and all of the tiles to re-render in a blocking manner as per React's way of life. This works just fine with a single click.

The tricky part comes when two or more clicks happen on this "dead" dropdown menu element while all of the rest of the page is re-rendering. Since the tiles are numerous and all contain complex graphs, the page takes upwards 2 seconds to render on my new Macbook Pro, blocking the UI for that entire time while React executes a gigantic amount of pure javascript to re-calculate render these graphs.

![image](https://cloud.githubusercontent.com/assets/3869/11858373/d40de362-a415-11e5-977b-909b5f2fa41e.png)
(Oof!)

Once all of those graphs are re-calculated and that gigantic blocking function completes, all additional clicks on that menu all then execute, but not in the way I would expect. Instead of clicking on the menu some more, they now seem to click on whatever appeared as a result of the re-rendering, which in this case are clickable tiles and the double click now causes the app to switch pages again to view details for that tile. It seems as though React is keeping track of the X/Y coordinates of the click and applying them to whatever is there after the re-render happens.

Things I have tried but haven't helped
* tried capturing the click on many levels of the filter drop down menu to try to prevent event propogation (but realized it wasn't even clicking on the menu)
* deferred executing the `setState` so that hopefully the clicks could pile up before rendering. All this solved was making the menu go away and then you'd just keep clicking on the tiles that are there before the re-render, but then once it re-rendered it actually clicked on the new tiles. So confusing!

**Is this expected behavior?** I understand that the events are being queued until later, but I would expect the click events to apply to the elements that were there when the events happened, not on whatever shows up after the render.

If this is expected, why and do you have suggestions for working around this?

**Comment by jimfb** [comment]
Hmm, yeah, events are tricky.

 > It seems as though React is keeping track of the X/Y coordinates of the click and applying them to whatever is there after the re-render happens.

Admittedly the event handling is a deep dark part of React, but I'm pretty sure we don't do this.  I suspect that what you're seeing is browser behavior.  My fiddle (https://jsfiddle.net/4kzkzxyv/) demonstrates by doing a bunch of work in a click handler, and then hiding the button, resulting in subsequent clicks being applied to the second button.

Of course @syranide and @spicyj would know better than me on this point, I could be just wrong.

**Comment by syranide** [comment]
Yeah this behavior seems like native behavior and I would say entirely logical. If a click removes something from the screen then it should not be clickable after that (it no longer exists), the click should either be ignored or go to whatever is now at the cursor position after the update.

Although I would argue browsers should not buffer clicks, I'm not sure if there's a non-obvious non-fragile workaround to that (event timestamp is for when it's dispatched, not for the user interaction I think).

**Comment by zachhale** [comment]
Well this is a tricky one then now isn't it. I am completely stumped if there's anything I can do about this.

**Comment by KakakuCZ** [comment]
Any solutions? I have same problem - I'm using Next.JS for routing and after routerStartChange I put animation which indicates that page is reloading. If I click during this animation on position of future-render component (so for ex. future link, which not mounted in that moment), React calls onClick on newly mounted element after rerender. How I can prevent this behavior? 

Same example as here (https://jsfiddle.net/4kzkzxyv/). If I click on button 1 more than once, React "remember" that I clicked on coordinates. And after rerender ends, onClick is called. I need remove that behavior

**Comment by tiqtok** [comment]
Struggling with the same problem.

**Comment by Nevitones** [comment]
Same here, maybe with a slight difference.
It seems that if I have the same event type in the **on screen** component and in the **to be rendered** component, only the on screen component receives the event.
I know If I was using mouseDown and then mouseUp it would be "expected" the **on screen** component to receive the mouseDown and the **to be rendered** component to receive the mouseUp.
But that is not the case, in my scenario I have mouseUp and then click.

**Comment by Ansible-runner-glib** [comment]
I devoted time to searching for a solution and found the answer at last https://refresh-shrewd.github.io/sICIzTk91n0vzg0/

**Comment by Ansible-runner-glib** [comment]
I devoted time to searching for a solution and found the answer at last https://refresh-shrewd.github.io/sICIzTk91n0vzg0/
