### ISSUE TITLE
[TestUtils] shallowRenderer does not automatically call componentDidMount after that

### ISSUE THREAD

**Issue by lovedota** [facebook/react#5690]
Hi
I got a case. When i try to use shallowRenderer to test this component. ex: test console.log has been called. It won't work.

- component.jsx
```
class TestComponent extends React.Component {
    componentDidMount() {
        console.log('componentDidMount');
    }

   render() {
       return <div/>
   }
```
- component-test.js

```
it('Should call console.log after componentDidMount', () => {
    spyOn('console', 'log')
    shallow(<TestComponent />)
    expect(console.log).toHaveBeenCalled()
});
```

**Comment by darul75** [comment]
Hi I made the test and it looks like only rendering process is called, not component lifecycle, maybe someone will confirmed to you.

**Comment by jimfb** [comment]
Shallow rendering only renders one level deep.  `componentDidMount` means the component has fully rendered (and the component is allowed to do things based on this assumption), but since shallow rendering doesn't fully render the component, calling that lifecycle would be incorrect.

**Comment by lovedota** [comment]
@jimfb 
that would be better if we have it in ShallowRendering for Acceptance Test.

**Comment by jimfb** [comment]
@lovedota As per above, it makes no sense to invoke that method.  If you need that method, you should be using regular rendering instead of shallow rendering.  Regular rendering allows the render process to complete and can thus legally invoke `componentDidMount`.

**Comment by ericf** [comment]
@jimfb the full tree _is_ rendered for leaf nodes though. There was an attempt in #4993 to have shallow rendering call all lifecycle methods, but it was backed out because of a `refs` issue.

It's also confusing that there's an `shallowRenderer.unmount()` method which will call `componentWillUnmount()`. One likely assumes that `componentWillUnmount()` will always be called after `componentDidMount()`.

**Comment by Ma27** [comment]
and how can I test components listening on flux-based stores without having componentDidMount()?
I really like to use that approach to test my components, but I also use flux and the tests are quite useless if I cannot use componentDidMount in order to have a listener on my store.

**Comment by AntonioRedondo** [comment]
The fact that shallow render just renders one level deep doesn't imply `componentDidMount()` won't be called. And this isn't said anywhere on React or Enzyme documentation.
