### ISSUE TITLE
Consequences of unsynchronized client/server renders

### ISSUE THREAD

**Issue by calebmer** [facebook/react#5696]
What are the consequences when a client render is out of sync with a server render? For example, I have a button which I want users with JavaScript disabled to be able to access, but I don't want it when the React client app takes over. Or I would like to minimize file size by using `renderToStaticMarkup` instead of `renderToString`.

So my two questions can basically be summarized as, what are the performance and other consequences of:
- Rendering a slightly different dom tree on the server.
- Mounting on a non-empty dom which does not have `data-react-id`s.

**Comment by zpao** [comment]
Both of these cases can be summarized as follows: React on the client will blow away the existing dom nodes when rendering. That will take some time and you'd lose the data that was server rendered but not on the client. You'd also lose any state in the dom that was added by the user before React mounted. You can perhaps avoid the rendering difference if you just use noscript. Optimizing the markup so you don't have reactids might not be worth it either - those will be gone in the next major release.

**Comment by jimfb** [comment]
@zpao @spicyj Those will be gone for SSR?  Somehow I thought we were retaining those for SSR, but maybe I'm just wrong.
