### ISSUE TITLE
Add code coverage reporting

### ISSUE THREAD

**Issue by zpao** [facebook/react#5704]
Jest can do this and we can report through coveralls or code climate, it doesn't matter). This shouldn't require too much work but will need some finishing touches by me or Ben for the TravisCI integration.

I'll plan to do this soon if nobody else jumps on it.

**Comment by yaycmyk** [comment]
I'd be interested to know the steps when you get to it. I tried setting up Babel + Jest for coverage and the line numbers were all wrong / nothing matched up properly.

**Comment by zpao** [comment]
Probably need the --retain-lines option for Babel. We already [do that](https://github.com/facebook/react/blob/master/scripts/jest/preprocessor.js#L39) when running the tests so that stack traces are usable.

**Comment by jdalton** [comment]
I jumped in on #5707.

**Comment by zpao** [comment]
With #5707, #5713, 85e646015d1a9482858d04973472631c7ba12891, and 89a0ef4ff915ce1f95824000fc406a31b6ecda2f we're all done here. Thanks for the help!

And @yaycmyk, the reporting seems pretty accurate so the retain lines flag would be my recommendation to you.

**Comment by yaycmyk** [comment]
@zpao Thanks, I followed your instructions and it seems like there's an issue with globbing in `collectCoverageOnlyFrom`. Once I added every file it's supposed to be looking at, it works :(

**Comment by zpao** [comment]
@yaycmyk yea, that option sort of sucks 😢 - it doesn't support globbing as you've noticed. That's why @jdalton added code to expand those globs and write a separate config that gets consumed when including coverage reporting.
