### ISSUE TITLE
Server and Client render the same markup, but React still indicates checksum invalid

### ISSUE THREAD

**Issue by jineshshah36** [facebook/react#5717]
![screenshot 2015-12-22 15 57 53](https://cloud.githubusercontent.com/assets/6501089/11966958/c7821ccc-a8c4-11e5-9aaa-f2c663762a63.png)

**Comment by jimfb** [comment]
@jineshshah36 There isn't enough information here to be actionable, but this error is usually a usage question.  Your components are likely doing something that causes the checksums to differ.  Sometimes the reasons are subtle, like an unprintable character.  Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.

If you can provide a minimal test case that demonstrates a bug in the React core, we can investigate further.
