### ISSUE TITLE
Difference between currentTarget and target of SyntheticEvent

### ISSUE THREAD

**Issue by markliu2013** [facebook/react#5733]
There is 2 properties in SyntheticEvent, currentTarget and target.
It is identical usage? or what is the difference between them?

**Comment by gaearon** [comment]
It mimics the DOM Event object API which also has [`currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) and [`target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target).

From `currentTarget` documentation:

>It always refers to the element the event handler has been attached to as opposed to `event.target` which identifies the element on which the event occurred.

**Comment by max-mykhailenko** [comment]
I have problem with them: `currentTarget` has `null`, but in `target` I have `currentTarget` element

**Comment by jimfb** [comment]
@max-mykhailenko Can you provide a jsfiddle that demonstrates the issue?  It appears to work in my fiddle: https://jsfiddle.net/gpm18sqd/

**Comment by kun-zhou** [comment]
#2850 seems to explain the reason for this bug.
