### ISSUE TITLE
SVG attributes set with no namespace

### ISSUE THREAD

**Issue by yavorskiy** [facebook/react#5734]
Say we have a view rendering `<use xlinkHref="#id"/>` in a loop. First render displays all instances just fine, but newly appended `use`'s would not show. Also calling `getAttributeNS('http://www.w3.org/1999/xlink', 'href')` on them would return `null` while returning `#id` for initial nodes.  

Here is [JSBin example](http://jsbin.com/kitinaboca/edit?html,js,output) with reproducible issue

**Comment by gaearon** [comment]
I think this is the problem:

<img width="461" alt="screen shot 2015-12-25 at 15 21 38" src="https://cloud.githubusercontent.com/assets/810438/12003517/3b6ee5b8-ab1b-11e5-8aca-dce98b511ca5.png">

`createNodesFromMarkup` uses a [dummy `<div>`](https://github.com/facebook/fbjs/blob/4bbe1a1e6b7160b51494d47746362cd59de2666d/src/core/createNodesFromMarkup.js#L24-L25) so it can later [assign `innerHTML`](https://github.com/facebook/fbjs/blob/4bbe1a1e6b7160b51494d47746362cd59de2666d/src/core/createNodesFromMarkup.js#L67) and pull out the created node. 

However it seems like (some?) namespaced properties are only taken into account when SVG elements are created inside `<svg>`.

cc @spicyj

**Comment by gaearon** [comment]
Presumably, the reason it works initially is because it *is* inside `svg` when the markup is first assembled an rendered.

**Comment by gaearon** [comment]
Related: https://github.com/facebook/react/issues/5061#issuecomment-156361189

**Comment by spicyj** [comment]
This should work okay on master now since we use document.createElement(NS) for everything except server rendering.

**Comment by yavorskiy** [comment]
"This should work okay on master..." – awesome, thanks! 

My temporary workaround was to wrap those elements into `<g key={arrayFingerprint(colors)} />`, hopefully that may help somebody
