### ISSUE TITLE
wrong version in npm

### ISSUE THREAD

**Issue by chicoxyzzy** [facebook/react#5751]
after doing `npm update` I have `react` and `react-dom` 0.14.__5__ instead of [0.14.__4__](https://facebook.github.io/react/blog/2015/12/29/react-v0.14.4.html)
the versions at npm are [indeed](https://www.npmjs.com/package/react-dom) [0.14.5](https://www.npmjs.com/package/react)

**Comment by chicoxyzzy** [comment]
hmm. looks like version isn't wrong
https://github.com/facebook/react/commit/dd2dbd0a5c44150344420b2a268fad09aabb34f7
but there is [no release](https://github.com/facebook/react/releases) and no blog post for 0.14.5

**Comment by spicyj** [comment]
Oh, I forgot to tag the release. I pushed a 0.14.5 release because I messed up the fbjs dependency, but either should work for you.
