### ISSUE TITLE
Way to create pluggable Decorating Component

### ISSUE THREAD

**Issue by VoronaPavel** [facebook/react#5754]
How is it possible to make **pluggable** AOP-style component which transforms props and transmits it to child? More precisely, how to pass props to child element in parent render method?
I want to use it like this:
```javascript
// Scalable.js
// Example of AOP-style decorating component
import React from 'react'

const Scalable = ({children}) =>
  const scaledData = children.props.data.map(e => e + 1) // example 'transformation'
  children.props.data = scaledData
  {children}  // this is what i want

Scalable.propTypes = {
  children: React.PropTypes.element.isRequired
}
```

```javascript
// ScalablePlot.js
// plug <Scalable /> to transform data passed to <Plot />
// and render <Plot /> with transformed data
import React from 'react'

const ScalablePlot = ({data}) =>
  <Scalable>
    <Plot data={data} />
  </Scalable>
```

```js
// Plot.js
import React from 'react'

const Plot = ({data}) ->
  //paint plot using data

Plot.propTypes = {
  data: React.PropTypes.arrayOf(React.PropTypes.number)
}
```
However, when i do this, react renders child element without data props.

UPD
===
Solution: should have used [React.cloneElement](https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement)

**Comment by jimfb** [comment]
Looks like you figured out the solution - `React.cloneElement`.

For future reference: This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core.
