### ISSUE TITLE
IE unable to render elements on popup window after state has changed 

### ISSUE THREAD

**Issue by lucaspin** [facebook/react#5755]
I am using `react@0.14.3` and I encountered an issue on IE (9, 10, 11), which can be examplified by the following piece of code: 

```javascript
import React from 'react';
import ReactDOM from 'react-dom';

class Example extends React.Component {
  render() {
    return (
      <PopoutWindow title="Test">
        <AnotherCoolComponent />
      </PopoutWindow>
    );
  }
}

class AnotherCoolComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showSomething: false
    };

    this.showSomething = this.showSomething.bind(this);
  }

  showSomething() {
    this.setState({
      showSomething: !this.state.showSomething
    });
  }

  render() {
    return (
      <div>
        <button onClick={this.showSomething}>Click here</button>
        {this.state.showSomething && <p>This is a paragraph</p>}
      </div>
    );
  }
}

class PopoutWindow extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      openedWindow: null
    };
  }

  componentDidMount() {
    var win,
        container,
        openedWindow = {};

    win = window.open('about:blank', 'Test', 'width: 600px; height: 600px');
    var onloadHandler = () => {
      container = win.document.createElement('div');
      container.id = 'test';
      win.document.body.appendChild(container);
      ReactDOM.render(this.props.children, container);
      openedWindow.update = newComponent => {
        ReactDOM.render(newComponent, container);
      };
    };

    win.onload = onloadHandler;
    // Just in case onload doesn't fire
    onloadHandler();

    this.setState({openedWindow: openedWindow});
  }

  componentDidUpdate() {
    this.state.openedWindow.update(this.props.children);
  }

  render() {
    return <div />;
  }
}

window.addEventListener('load', function() {
  var container = document.createElement('div');
  document.body.appendChild(container);
  ReactDOM.render(<Example />, container);
});
```

The issue is that when the state of `AnotherCoolComponent` changes, React tries to render the paragraph but fails, throwing an `Invalid Argument` error on `DOMChildrenOperations.js` on line 41.

If the state changes again, another error is thrown: 

`Invariant Violation: processUpdates(): Unable to find child 1 of element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID `.1`.`

This probably happens because the element wasn't rendered before. I tested on Chrome and FF, and it works fine on both.

**Comment by zpao** [comment]
You might need to create a more complete DOM in the popup window before rendering into it. It would be helpful to know what the markup inside the popup looks like after that first render. My best guess is that IE has done something different (perhaps it's in quirks mode or something, not sure how the window.open API works with about:blank)

**Comment by lucaspin** [comment]
I changed the window.open call to open a `test.html` page, with the minimum markup and it does not work either. The markup after the first render is

```html
<!DOCTYPE html>
<html>
  <head>
  </head>
</html>
```

**Comment by lucaspin** [comment]
I changed the call to window.open to open a `index.html` instead, and still doesn't work. I'm not sure it's related to that. The markup inside the popup after that first render is

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <div id="test">
      <div data-reactid=".1">
        <button data-reactid=".1.0">Click here</button>
      </div>
    </div>
  </body>
</html>
```

**Comment by rafaelmaiolla** [comment]
Any news in this issue?

**Comment by jimfb** [comment]
I tested in IE11 and was unable to reproduce.  My fiddle: http://jsfiddle.net/nw47bc3h/

**Comment by jimfb** [comment]
@lucaspin can you verify that this doesn't work on your version of IE?  and/or provide a fiddle that demonstrates the issue?

**Comment by lucaspin** [comment]
@jimfb your fiddle works fine on my IE. However, I don't understand why. I realize you're using version `0.15.0-alpha.1` of react. Maybe that's the reason? With `0.14.7` it doesn't work. My fiddle: https://jsfiddle.net/69z2wepo/29819/

**Comment by jimfb** [comment]
Ok, cool, I'm going to assume we fixed the issue in 0.15 :), unless I hear otherwise.  Let me know if you discover a repro on 0.15 and we can re-investigate.

**Comment by lucaspin** [comment]
@jimfb Thanks, man. Just one more question: when is this new version going to be released?

**Comment by jimfb** [comment]
@lucaspin Current thinking is "probably about a month", but that's subject to change.
