### ISSUE TITLE
internal components

### ISSUE THREAD

**Issue by damiandennis** [facebook/react#5757]
Does facebook have any plans on releasing some reusable components for websites like it has for reactive native? I know the community is making this happen but it would be good to see some of the components used internally at facebook/instagram.

**Comment by zpao** [comment]
No plans at this time - most of these components are very tightly integrated into our stack and styles. We may open source a couple things around complex patterns. [Fixed Data Table](http://facebook.github.io/fixed-data-table/) is one that we've already published.
