### ISSUE TITLE
Load Initial Data via AJAX isMounted

### ISSUE THREAD

**Issue by brigand** [facebook/react#5761]
In [Load Initial Data via AJAX][1] it uses isMounted which doesn't exist for es6 classes. Not sure how to best update the example, but it should probably be changed. Maybe abort the jqxhr?

[1]: https://facebook.github.io/react/tips/initial-ajax.html

**Comment by jimfb** [comment]
Yeah, simple fix is to abort the jqxhr in `componentWillUnmount`.

Although, I wonder if the whole page/example should just be eliminated.  The example has other problems (like not handling updates).  And having components do ajax is a bit of an antipattern anyway (they should use something like flux, which can ensure consistency across the page and can deduplicate requests for the same data).

**Comment by alayek** [comment]
hi, I would like to give this a shot. I am new to this, so kindly guide me through the process.

**Comment by jimfb** [comment]
First we need to decide what actually needs to get done here.

@sebmarkbage thoughts on best practices here?  Should we just toast the whole example?

**Comment by mjhm** [comment]
FWIW this is the only documentation page that hints at how to interact with a server. For beginners having a reasonable pattern to adopt before learning Flux has a lot of value.

**Comment by sebmarkbage** [comment]
Yea, we should keep it just as an entry level example. Sometimes difficult to strike a balance between best practice and easy examples. Especially since this is a fairly complex thing to get right atm.

IMO, we should just fix the example to abort at unmount.

**Comment by gaearon** [comment]
>And having components do ajax is a bit of an antipattern anyway (they should use something like flux, which can ensure consistency across the page and can deduplicate requests for the same data).

While this may be true for big apps, beginners have repeatedly expressed concerns about this. They jump to overengineered solutions when all they want is to talk to some API and show a list of things as an exercise. Unless they see a component doing AJAX request in the docs they feel they *have to* use Flux or some other complex data fetching solution, which isn't quite true.

So it's useful to show at least that this is *possible* and hm-kay to do in the official docs.

**Comment by ir-fuel** [comment]
Why would it be an anti-pattern? Not all ajax data that gets shown inside a component should live in the global application state. If the data is only relevant to the component and its children, but not to the rest of the app, or can't be considered "application state" why shouldn't the component itself be able to fetch it and store it in its `this.state` ?

**Comment by jimfb** [comment]
@ir-fuel The approach isn't scalable for several reasons.  If you have a thousand components, you can't reasonably be making a thousand requests (you'll need to implement batching of some sort).  If you have the same the same component multiple times, you'll want them to share a single value in memory (to avoid duplicate requests, or for consistency if the data is mutable, etc).  Also more difficult to subscribe to updates in case the underlying resource (on the server) changes.  Sideways data loading makes it more difficult for developers to reason about your application, since components are no longer a pure function of props+state (they are reading some outside data source).  The list goes on, but I'll truncate it there in the interest of time - the bottom line is that flux exists for a reason and it's a bad style for a component to make an ajax request.  This is a usage question, so if you are interested in that topic, feel free to discuss on an appropriate usage-question medium like StackOverflow.

**Comment by ir-fuel** [comment]
Of course I am not advocating bypassing state + props entirely in favour of doing Ajax calls.
The issue you can have when going into the other extreme is that your state object is littered with all kinds of variables that only make sense for 1 component class in your app, and if you have hundreds of those you'll end up with a state containing hundreds of properties that have a very small scope or even life time (imagine rendering a popup that only shows some useful information after registering an account, do you really want an application state property for the info inside that popup polluting your code when it is used only one time in the entire lifecycle of your app, in 1 popup?), and will spend 99.9% of their time simply being ` == null`

I'll be glad to discuss usage questions (especially with more practical examples, as I have a few myself in my apps and will be glad to discuss and discover best practices), however, where do you want me to do this? Github is clearly for bugs, and StackOverflow for technical issues. Open-ended questions where answers depend on people's opinions and not on what is the technically correct solution for a given problem are closed quite quickly by the moderators. So what channel would be best for this kind of discussion?

**Comment by jimfb** [comment]
@ir-fuel I recommend StackOverflow, or discuss.reactjs.org, or reactiflux.com, or quora (in that order).

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/5870
