### ISSUE TITLE
SVG attributes getting ignored

### ISSUE THREAD

**Issue by tusharmath** [facebook/react#5763]
INPUT: 
```svg
        <marker id="triangle"
    viewBox="0 0 10 10"
    refX={0} refY={5}
    markerUnits="strokeWidth"
    markerWidth="4" markerHeight="3"
    orient="auto">
    <path d="M 0 0 L 10 5 L 0 10 z"/>
</marker>
```
OUTPUT: 
```svg
<marker id="triangle" viewBox="0 0 10 10" data-reactid=".0.1.1.0.0.1.2.1.0.1.0.0.1.0.0.1.0">
    <path d="M 0 0 L 10 5 L 0 10 z" data-reactid=".0.1.1.0.0.1.2.1.0.1.0.0.1.0.0.1.0.0"></path>
</marker>
```
Missing properties — `refX`, `refY`, `markerUnits`, `orient`

**Comment by rickbeerendonk** [comment]
Marker tag also misses `markerWidth` and `markerHeight`

**Comment by zpao** [comment]
All attributes will be passed through to svg in the next release now that #5714 has landed. We won't be adding anymore individual attributes.

**Comment by tusharmath** [comment]
So, until then? When is the next release?

On Sat, Jan 2, 2016, 12:35 AM Paul O’Shannessy <notifications@github.com>
wrote:

> Closed #5763 <https://github.com/facebook/react/issues/5763>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react/issues/5763#event-503832933>.
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by zpao** [comment]
We'll ship 0.15 when it's ready. Rough estimate: probably not in January.

**Comment by tusharmath** [comment]
But what is the alternative, I am drawing all my graphs in SVG using react. Is it simply impossible to do this right now ?

**Comment by tusharmath** [comment]
As of now I am using `dangerouslySetInnerHTML` :(
Which seems pretty dangerous to me.

**Comment by zpao** [comment]
That or manually calling setAttribute on your svg node are the alternatives. The escape hatches are there but they are obviously unfortunate. The situation will be better soon.
