### ISSUE TITLE
Dynamically added unmount handlers

### ISSUE THREAD

**Issue by dantman** [facebook/react#5765]
React components could use some way to dynamically add a handler to be called on unmount. Either some event handler like way (`this.addUnmountHandler`) or some other way to register a 'destructor'/destroy method for an object that a component is holding on to.

`componentWillUnmount` exists but it does not scale well.
- Every time you hold on to something you have to maintain two sections of code, with the cleanup code being separate from the rest of the code.
- If you try to cleanup your code using helpers adding the cleanup code could be done in the very same function. But `componentWillUnmount` doesn't allow that.
- Sometimes you end up adding a `this._fooSomethingProp` to a component you wouldn't normally need, just so that you can hold on to the destructor for use in `componentWillUnmount` because you can't add the cleanup code in the same closure you set it up in.

---

Here's one sample use case of mine for unmount handlers.

React is discouraging the use of mixins so I've been trying to move towards alternative patterns in new code. Some helpers only make sense on a component itself and wont work as a special component or a higher-order component.

For some of these needs I've come up with a pattern that involves passing the component to a helper function that will mutate the component and provide some sort of service which is linked to the component.

Two examples from my codebase:

`ctxApi` provides a component with a version of my internal api which is 'scoped' to the component so that if the component is unmounted all of the api requests' HTTP requests are aborted.

`setPending` adds a key to a pending state set and returns a `pending.cleanup` that will unset it, which is intended to be passed to a `.finally` handler. This pattern provides my buttons, etc... with pending text and spinners while waiting for HTTP requests.

``` js
resendConfirmation(email) {
    var pending = setPending(this, `${email}:resendConfirmation`);

    ctxApi(this)
        .then((api) => api.post('/self/resendConfirmationEmail', {email}))
        .then(() => alertifyjs.notify("Confirmation message sent"))
        .fin(pending.cleanup)
        .catch(ignoreAbort)
        .catch(notifyOnError)
        .done();
}
```

The problem is that these helpers often need cleanup on unmount. `ctxApi` needs to abort requests on unmount. And `setPending` needs to break references so `setState` isn't called and it doesn't prevent gc. And while I can require that a call to a cleanup function be placed into `componentWillUnmount`. That is unnecessary boilerplate and easy to forget.

It would be much preferable for these helpers to be able to register an unmount handler on the component instance so they can implicitly clean themselves up.

**Comment by gaearon** [comment]
Not speaking for the React team here, but personally I enjoy using [Disposables](https://github.com/gaearon/disposables) (concept borrowed from Rx) for composing cleanup logic.

**Comment by dralletje** [comment]
I most of the time even keep an array `this.disposables` myself, which I fill with functions to be called in componentWillUnmount using `this.disposables.forEach(fn => fn())`. This allows you, fairly easy, to add dynamic cleanup code, and keep it close to the code that starts the listener.

Pretty much the same as Dan's example, only I don't use a separate library for it, may be easier to grasp when not used to disposables (although they are not different, I know, just trying to help :) )

```
class MyComponent extends Component {
  constructor(props) {
    super(props);
    this.disposable = [];
  }

  doSomething() {
    const xhr = doXHR();
    this.disposable.push(() => xhr.abort());
  }

  doSomethingElse() {
    const xhr = doAnotherXHR();
    this.disposable.push(() => xhr.abort());
  }

  componentWillUnmount() {
    this.disposables.forEach(fn => fn());
  }
}
```

**Comment by dantman** [comment]
@dralletje Side note, you probably want some more complexity in the disposable for the xhr.

The disposable's closure is going to keep the completed xhr instance around until the component itself is unmounted since the xhr's disposable is not removed or dereferenced when finished.

**Comment by dralletje** [comment]
@dantman Not the state-of-art way to handle disposables, I know, just used it to make an alternative to using a Disposable library. And I think most of the time, having these xhr objects (or whatever object) in memory, won't result in even a minor problem, will it? :-)

**Comment by dantman** [comment]
@dralletje Depends. IIRC the xhr object contains a reference to the whole response body (maybe a partial duplicate too in the case of response{Xml,JSON}). So in theory if you have a component that makes a pile of periodic HTTP requests (say, polling for data updates or accepting a lot of user interactions), then you have an array holding references to the combined uncompressed content length of every single xhr request the component has ever made.

**Comment by aweary** [comment]
It seems like this can be solved sufficiently in user-land with abstractions like disposables or callback queues. The use case doesn't seem common enough to warrant an increase in API surface.

If you disagree please feel free to [open an RFC](https://github.com/reactjs/rfcs) with a detailed proposal.
