### ISSUE TITLE
Import scope is not available in child class.

### ISSUE THREAD

**Issue by karuppasamy** [facebook/react#5769]
Why the base class's import scopes are not available in inherited class

**Base.js**

	import React from 'react';
	import I18n from 'i18n-js';
	
	export default class Base extends React.Component {
	}

**Test.js**

	import Base from './Base';
	
	export default class Test extends Base {
	  const a = I18n.t(...);
	}

Do I need to re-export the es6 default modules on every component if it's used by next component?

**Comment by zpao** [comment]
This is not a React question but a general JS question. I encourage you to learn more about JS modules and how that relates to scope before trying to use modules.

The tldr is that each module is a new scope so nothing that was available in some other file will be available in Test.js unless you import it.

**Comment by karuppasamy** [comment]
Thank you @zpao
