### ISSUE TITLE
props in constructor does not match props in render

### ISSUE THREAD

**Issue by dbkaplun** [facebook/react#5772]
Expected:
```
constructor {foo: "bar", name: "Joe Schmoe"}
render {foo: "bar", name: "Joe Schmoe"}
```
Actual:
```
constructor {foo: "bar", name: "Joe Schmoe"}
render {name: "Joe Schmoe"}
```
Code: http://jsbin.com/gutagazaxa/1/edit?html,js,output
```js
class HelloWorldComponent extends React.Component {
  constructor (props) {
    super(_.merge({foo: 'bar'}, props))
    console.log('constructor', this.props)
  }
  render() {
    console.log('render', this.props)
    return (      
      <h1>Hello {this.props.name}</h1>      
    )
  }
}

React.render(
  <HelloWorldComponent name="Joe Schmoe"/>,
  document.getElementById('react_example')
)
```

**Comment by yangshun** [comment]
You are not supposed to mutate `this.props`

**Comment by yuchi** [comment]
Actually he’s not mutating it. He is creating a new `props` and passing that one to `super`.

I’m with you in the fact that you shouldn’t do it, but there’s no apparent reason it shouldn’t work.

**Comment by zpao** [comment]
See #5320 for another discussion about this (from a slightly different angle) - namely @sebmarkbage's first comment about initialization vs updates. Note: that PR was merged but was backed out because of the discussion.

If you'd like to use default values for props (`foo` here) then you should use the `getDefaultProps` API.

**Comment by dbkaplun** [comment]
@zpao I guess I'm still a little unclear.. are you saying `this.props` in the constructor intentionally has a different value than `this.props` in `render()`? Thanks in advance

**Comment by jimfb** [comment]
@dbkaplun Correct - The `this.props` is passed into the constructor as a convince for easy access within the constructor.  The component's props are controlled by React, not by the constructor, for the reasons discussed in #5320.

If you were using a more modern release of React, you should get a warning when you passed in the modified props: https://github.com/facebook/react/issues/5335
