### ISSUE TITLE
Warn if style value is NaN

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5773]
Passing a value of NaN as the value of a css style seems to indicate an error.  Turns out that we don't warn on initial render, and give a confusing error on update (because `NaN != NaN` as per spec).  Discovered in https://github.com/facebook/react/issues/4877#issuecomment-168471074

```
ReactDOM.render(<div style={{marginLeft: NaN}} />, document.getElementById('container'));
ReactDOM.render(<div style={{marginLeft: NaN}} />, document.getElementById('container'));
```

Anyway, we should probably warn if someone passes in `NaN` on initial render, and not warn on update if both previous/next values are NaN.

**Comment by zpao** [comment]
NaN is a fine (if weird) value to pass so we should probably just handle it explicitly like we did for props in #3148.

**Comment by jimfb** [comment]
Yes, we should warn and also do what @zpao said (handle NaN explicitly to not warn on updates when value is unchanged).

**Comment by jontewks** [comment]
Submitted #5811 as a fix. Thanks!

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/5811
