### ISSUE TITLE
DOM rendered is different with Virtual DOM!

### ISSUE THREAD

**Issue by Huxpro** [facebook/react#5777]
It just happened;

when the Virtual DOM (inspected by React DevTool) is: 

```html
<div>
  <section id={1}>
  <section id={2}>
  <section id={3}>
  <section id={4}>
</div>
```

the rendered DOM I got is

```html
<div>
  <section id={1}>
  <section id={2}>
  <section id={4}>
  <section id={3}>
</div>
```

The Real React Code:

```javascript
   render() {
        let slides = this.props.store.map((slide, i) =>
            <section key={i} dangerouslySetInnerHTML={{__html: slide}} />
        )

        return (
            <div className="reveal">
                <div className="slides">
                    {slides}
                </div>
            </div>
        );
    }
```

**AND**, the 4th section is inserted with `this.setState{ sections: someArray }` and all these section is using `dangerouslySetInnerHTML`. **There is no any warning or error in console**

**Comment by jimfb** [comment]
Can you provide a simple jsfiddle that demonstrates the issue?

**Comment by Huxpro** [comment]
@jimfb  I'd love to. But It get a little complicated since mixing in Reveal.js, which is absolutely related to this issue I considered.

**Comment by zpao** [comment]
This might be a case where using array indices for keys comes back to bite you. Since that's note actually stable between loops you might be assigning the same key to a different slide on the next pass which can confuse React's update optimizations (or rather, it's working exactly like it's supposed to just with confusing output). If you can use an id or something instead of the array index that might help narrow down the issue if it continues.

**Comment by Huxpro** [comment]
@zpao what you said inspired me a lot, thanks.

Seeing all `<section />` is `dangerouslySetInnerHTML`, all those sections are totally same in React's Views.....But I have no idea how to work arount it yet

**Comment by Huxpro** [comment]
So hack....seems ok when I try `key={slide + i}`, which makes html so so ugly.

I considered It is worse if I concat html string firstly and inject all of them in one time. It will lose the performance by React diff

**Comment by Huxpro** [comment]
Hey guys, I really need help...I am almost give up it.

As I mentioned above, I try to mix React.js with Reveal.js to make a keynote/powerpoint-like app.
 so I have to use `dangerouslySetInnerHTML` to save the html snippet.
To work around the possible problem as @zpao said, I use a uuid as the `key` of every slide:

```
let slides = store.map((slide, i) =>
      <section key={slide.uuid}>
        <article dangerouslySetInnerHTML={{__html: slide.html}} />
      </section>
)
```

And, there is a feature to add a slide after the current slide.
```
onNewSlideClick = (e) => {
    let temp = this.state.store.slice();

    temp.splice(this.state.active +1 , 0, {
      uuid: this.getUuid(),  // return Date.now()
      html: tplNew.title
    })

    this.setState({
      store: temp
    })
  }
```

Then the issue occurs, the actual DOM order is ridiculously different with the `temp` array, the `store` state, also the VDOM showed by react-devtool.

I can push the whole thing into github but It's hard for me to provide a simple snippet to demonstrate this issue. Really sorry about that

God...save me please!

**Comment by Huxpro** [comment]
Alright, new progress. This issue seems only happend with `<section>` tag.
When I replace it with `<li>` or `<div>`, the actual DOM order is finally correct!

I dont why and It seems nothing to do with Reveal.js and Its CSS. The issue still exists without Reveal as long as I use `<section>`

**Comment by Huxpro** [comment]
Well...I create a [JSBin](https://jsbin.com/meqequ/edit?html,js,output). But things gonna perfectly nice here. That's why I said that I am hard to provide a simple snippet since I do NOT know where the issue really located at!

**Comment by Huxpro** [comment]
……Guys, I convinced that this issue can be closed now. 
I just updated my react and react-dom dependencies to 15.0.0-rc2, and everythings works fine now.

Well, I still curious about what I encountered with react 0.14! 
Anyway, I can continue my work now T T.

If none of your guys interested in it, close it please.

**Comment by gaearon** [comment]
A lot of DOM code changed between 0.14 and 15 so it might have been fixed by one of those updates.
I’ll close but please let us know if you see this again.

**Comment by Huxpro** [comment]
Sure. FWIW, thanks for you guys awesome work
