### ISSUE TITLE
TestUtils.Simulate.blur should reset document.activeElement

### ISSUE THREAD

**Issue by nylen** [facebook/react#5778]
As the title describes, simulating a blur event should reset `document.activeElement` (probably to `document.body`).  `document.activeElement` is the only way (that I'm aware of) to get the element that caused a blur event on IE11.

Context: https://github.com/Automattic/wp-calypso/pull/2054

**Comment by zpao** [comment]
`TestUtils.Simulate.*` isn't meant to do what the browser would do as far as side effects go. Even `TestUtils.SimulateNative.*` doesn't actually work how you want I think (it does create an actual event but only dispatches it in the internal system).

I don't think this is a bug per se but a misconception about the scope of the test utils. You may just want to fire an event yourself in your test.

**Comment by nylen** [comment]
OK - thanks for the clarification.
