### ISSUE TITLE
Inline styles with browser-specific values

### ISSUE THREAD

**Issue by cportela** [facebook/react#5783]
It would be nice if I could define an inline style with an array and the parser would expand it to duplicate styles props.  For example:

let myStyles = {
   display: ['-webkit-flex', '-ms-flexbox', 'flex'],
   ....
};

and then specifying "style={myStyles}" in my component would expand to:

style="display: -webkit-flex; display: -ms-flexbox; display: flex"

Thanks!

**Comment by yaycmyk** [comment]
Why though? Only one browser needs a specific version of that prop, so it seems like doing a basic browser detect somewhere in your code and then just using the appropriate prefix (if necessary) is a better solution.

**Comment by cportela** [comment]
Sure, one can do that, as flawed as browser detection may be, but as you might surmise from my request I didn't think that was the best approach.  I would let the browser make its own choices a-la-CSS...
Rock on!

**Comment by cmpis** [comment]
@yaycmyk: browser detection wouldn't be a solution here besides the fact that browser detection shouldn't be done unless there is no other way. 

The nature of CSS here is that you would normally specify this in a style like 

```
@mixin flexbox() {
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
}
```

And the browser picks the first one it can work with. 

This would make it much easier to do that from React/JS in component inline styles.

**Comment by syranide** [comment]
One fundamental issue here is that React needs to update styles using `node.style.key = value`, here you cannot do the usual CSS trickery you're trying to achieve. I don't think anyone is denying that what you want is a bad thing, but it's far from trivial how to actually accomplish it in a sustainable fashion all things considered.

**Comment by cportela** [comment]
Thanks for clarification @cmpis.  @syranide I hear you, this is a deal breaker indeed.  I didn't realize React was doing the node.style.key= value thingie.  I thought it was a parse-time kind of a thing.  That being said, there must be another way to accomplish this because the only alternative I can think of would be to add/remove classes in jQuery fashion. Ouch!

**Comment by zpao** [comment]
As mentioned, you can do browser detection or you can use CSS and classes. React isn't trying to be a complete solution for this problem. If you want to break out into more complicated inline-styles processors that actually generate stylesheets for you, that could also work (see [Radium](https://github.com/FormidableLabs/radium) for example).

I'm not sure what you mean about manually adding/removing classes - you'd be able to write that inline and let React handle it just like you would with styles. Eg `<div className={condition ? 'foo' : 'bar'} />

**Comment by Bizzle-Dapp** [comment]
Resurrecting an old thread here. In case anyone stumbles across this looking for the answer. 
I had an issue with '-webkit-fill-available' not being picked up by IE11. 

No need for long winded functions, additional CSS classes and such if you didn't want. 

To use Inline styles with browser-specific values, you can perform the same sequential rendering CSS performs naturally. For example: 

```
<div style={{position: 'fixed', zIndex: '1052', width: '-webkit-fill-available', width: '80%'}}>
</div>
```
In this example, if `'-webkit-fill-available'` is unavailable the next width styling will be used. If it is available, `width: '80%'` will not be used.
