### ISSUE TITLE
forceUpdate() doesn't cause rerender

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5789]
We bail out of rerender when the props object is triple-equals-equal.  It can lead to some very unintuitive (ie. wrong?) results, where the user has dropped all references to a string, and yet the old data is still visible after a render/forceUpdate.

Example: https://jsfiddle.net/rah1ptut/

Invoking `ReactDOM.render()` again is insufficient.  You need to call `ReactDOM.unmountComponentAtNode` and then `ReactDOM.render` again.  This seems like an API violation.

Since I'm familiar with the internals of the core, I understand why this is happening, but it feels really wrong as an end user.

Do we already have an issue tracking this?  Would we fix it?  @sebmarkbage @spicyj @zpao

**Comment by sebmarkbage** [comment]
No, this is a known issue. The solution is to create your elements in render. Doing a lot of bunch of work outside a component is bad practice. As per your blog post, it is expected that we move towards to centralized renderers that solve this once and for all so it is not a scaled problem.

You would have to move this into a component to create a viable scenario that I'm concerned about.

To receive this in a component you would have to either:

a) Use global mutable state from your render (bad practice and breaks the pure contract) together with a manually hoisted element (not common).

or

b) Use local mutable component state (frowned upon) + put your React Elements in that state (bad practice).

These factors make this a very unlikely scenario. We've had this for years and it hasn't caused an outrage or known issues. At the same time it is an important default optimization.

**Comment by jimfb** [comment]
A) Yeah, probably a non-issue.
B) IDK, Descriptor caching of elements that take in mutable data - really isn't that inconceivable.
