### ISSUE TITLE
Add 'onClickoutside' event

### ISSUE THREAD

**Issue by hojberg** [facebook/react#579]
Add the 'clickoutside' event similar to this jquery plugin: https://github.com/cowboy/jquery-outside-events

Very useful sugar for components like dropdowns and modals that need to close/hide when you click out side the container.

**Comment by hasPatrickC** [comment]
@Pomax I think I've found a context where your mixin doesn't quite behave as expected. If you have a sub-component that has it's own click action that ends up removing that component from the DOM, the source.parentNode loop breaks before it makes it's way back up to the actual parent component. 

So in this case, if you have a dropdown that has a list of items that have (x) icons that delete items from the dropdown list, whenever you delete an item the outside click will be registered and the dropdown will close.

**Comment by Pomax** [comment]
intersting - if you have a jsbin that I can drop this into, we can maybe do a bit of iterative improvement until we have a mixin that's robust enough to just npm publish as react-onclickoutside or the like.

**Comment by willdady** [comment]
@Pomax you're trying to manually reinvent event propagation with that loop. This is why I used ```stopImmediatePropagation``` in my example. You don't need to check if the event belongs to a specific element because the event is "stopped" before it bubbles up to the handler listening on the document.

**Comment by Pomax** [comment]
@willdady I'll take your if it's available in mixin form - anything that I can point other people at and go "solved problem, even if not in React (yet?)"

**Comment by chiefGui** [comment]
Hey guys, something new so far?

I was thinking about the subject and something simpler comes out: your component is contained by `.container` class, as instance; if you click in something else which isn't `.container`, then `unmount`. Sounds good?

_Maybe_ CSS can resolve our problem, I just have to confirm if `:not()` selector can does this for us.

**Comment by Pomax** [comment]
Even if that were an option, it's not the one I'd use: it would rely on an implementation detail, without that detail being part of the React API. It also relies on a uses CSS classes as if they're functional roles, which is literally the reason I like React so much: it doesn't rely on query selecting everything =)

I'll try to publish a react-onclickoutside mixin to npm today based on the code I had mixed up with the improvement @willdady pointed out.

**Comment by gaearon** [comment]
Layered approach works fine for me, so that's what I normally use.  
Sometimes you also want to fade that layer (e.g. for modals) so layer is natural IMO for solving this problem.

**Comment by Pomax** [comment]
While it's great for that purposes, it also seems exclusively intended for dealing with modals. That's a level of specialization I don't want to have to abuse for genuine "I need to listen for clicks outside this element" behaviour that has nothing to do with modal dialogs in the slightest (like blur behaviour at the component level, switching between "an element" and an editor for its content, etc)

**Comment by chiefGui** [comment]
@pomax Good point! But certainly, using CSS is a fast & easy way to go — it worked for me! But you are right, doesn't make any sense unleash this approach since I'm using the powerfulness of React.

I removed completely the "outsideClick" approach of my app and waiting for your mixin. For now, users should to press "esc" to close their component. (lol)

**Comment by gaearon** [comment]
Yeah I see your point.

I use layers for anything "global" that can only have single instance and has to be on top (e.g. modal, context menu, alert, sidebar). In this case, I only have one "dimming" layer that listens to `ModalStore`, `ContextMenuStore`, `AlertStore` and decides whether to show overlay (transparent in some cases) or not.

For rare cases I need "click outside" at component level, I put `e.preventPropagation` in its own `click` handler and set up a `document.addEventListener('click', this.handleBodyClick)` handler separately. This solves the problem you described for me.

**Comment by chiefGui** [comment]
@gearon I think a mixin it's more DRY and reachable than a code snippet. Also, your solution is wise and fresh, man. I'll give it a shot soonish and come back with the results. Yet, still waiting for @Pomax's mixin if he still mean to keep his promise.

**Comment by Pomax** [comment]
A promise I made 3 hours ago on a work day =)

Although I did publish https://www.npmjs.com/package/react-onclickoutside so have at it and if you run into breakage, issues are tracked on github

**Comment by gaearon** [comment]
>I think a mixin it's more DRY and reachable than a code snippet. 

Kinda but.. you'd need to not forget to do `stopPropagation` in your own click handler (which you need to remember to attach to root node). So it's like half of the code is outside the mixin anyway. Certainly you can implement it with a `while` loop instead of `setPropagation` but this rubs me as wrong.

@Pomax 

Wouldn't it be better if mixin stored functions in a private map and removed them automatically in `componentWillUnmount`? Prevents accidental leaks & removes the need for private function.

**Comment by Pomax** [comment]
if you can point me to the docs on triggering functions automatically when the owning component reaches componentWillUnmount, I'll be more than happy to work that in.

**Comment by chiefGui** [comment]
> you'd need to not forget to do stopPropagation in your own click handler

I was thinking about this. Faced this problem just right now, lol. But you're not being boring — you're thinking in the best fashion to get it done.

@Pomax I was kidding about the pressure, lmao. But man, thank you so far — you were fast as hell.

**Comment by gaearon** [comment]
>It would be nicer if it automatically hooked into both componentDidMount and componentWillUnmount, simply binding and unbinding this.onClickOutside (which can then do whatever additional function routing required).

The fun part about React mixins is that this is what happens when you define `componentDidMount` and `componentWillUnmount` in the mixin itself ;-) See [example in docs](http://facebook.github.io/react/docs/reusable-components.html#mixins).

**Comment by Pomax** [comment]
excellent. I'll update the mixin.

**Comment by Pomax** [comment]
updated mixin as v0.1.0 since it has a different implementation now: simply add the mixin and define an `onClickOutside: function(evt) { ... }` in the component using the mixin.

**Comment by gaearon** [comment]
I'd call it `handleClickOutside` because that's the convention for function names (`on*` is convention for prop names)

**Comment by Pomax** [comment]
fair point. updated (v0.2.0)

**Comment by Pomax** [comment]
this is pretty usual for a first hour module push, in my experience, because that first hour has all the immediate bug reports from people you just linked it to =)

**Comment by yiminghe** [comment]
this problem should be solved by focus and blur event.

if click document, dropdown lose focus then hide dropdown menu

**Comment by Pomax** [comment]
focus events are not the same as click events: a drop down that disappears on an "click outside" will stay open even if you change tabs or switch out/back in to the browser application itself. However, both those actions will cause blur events. Click and focus events fire based on different queues, and you can't really fake a "click outside" by tapping into blur.

**Comment by chiefGui** [comment]
What @yiminghe said it's a good idea, IMHO. I didn't thought this way, but your mixin @Pomax saved lives.

**Comment by henriquea** [comment]
For anyone interested I'm using a different approach with `signals` where in my case if you click outside of a component is because you're interacting with another.

ObjectSignal.js
```javascript
var Signal = require('signals');
var ObjectSignal = (function(){
  return {
    componentClicked: new Signal()
  }
}());
module.exports = ObjectSignal;
```

Component1.js
```javascript
handleClick: function(e) {
  ObjectSignal.componentClicked.dispatch(this.state.id);
}
```

Component2.js
```javascript
componentDidMount: function() {
  ObjectSignal.componentClicked.add(this.componentClicked);
},

componentWillMount: function() {
  ObjectSignal.componentClicked.remove(this.componentClicked);
},

componentClicked: function(id) {
  console.log('componentClicked:', id);
  // check if dropdown is opened, etc
}
```

Cheers 🍺

**Comment by johnarnfield** [comment]
I don't like the idea of stopping event propagation on such a scale. React makes it very hard to handle events consistently, when you try and make it play with libraries that handle events on the target itself.

How about circumventing React all together?

```javascript
    componentDidMount: function () {
        document.addEventListener('click', this.onDocumentClick);
    },

    componentWillUnmount: function () {
        document.removeEventListener('click', this.onDocumentClick);
    },

    onDocumentClick: function(event) {
        var main_menu_button = React.findDOMNode(this.refs.main_menu_button),
            main_menu = React.findDOMNode(this.refs.main_menu);
        
        if (main_menu_button.contains(event.target)) {
            // Clicking on the button should toggle the overlay
            this.setState({main_menu_shown: !this.state.main_menu_shown});
        } else if (!main_menu.contains(event.target)) {
            // Clicking anywhere else, outside the overlay, should close it
            this.setState({main_menu_shown: false});
        }
    },
```

**Comment by Pomax** [comment]
@johnarnfield so, literally what the react-onclickoutside mixin does, then? =) (https://github.com/Pomax/react-onclickoutside/blob/master/index.js#L61)

**Comment by ericsuh** [comment]
@Pomax I implemented a component that relies a bit more on React/DOM event handling rather than assumptions about the component tree. I generally favor components over mixins for React: https://www.github.com/ericsuh/react-outsideclickhandler.git

**Comment by Pomax** [comment]
I prefer the complete opposite: I have no desire to see things like the following, if I need a reasonably functional component:
```
<div>
  <FunctionalityElement1/>
  <FunctionalityElement2/>
  <FunctionalityElement3/>
  <FunctionalityElement4/>
  { my actual content }
</div>
```
mixins solve this horrible XML hell by just letting me say:
```
React.createClass({
  mixins: {
    require(...),
    require(...),
    ..
  },
  render() {
    return <div>{ my content, no spam around it}</div>
  }
```
It just feels so much better.

**Comment by ericsuh** [comment]
To each his/her own. I consider mixins and inheritance in general to be used sparingly, especially in a type-unsafe language like JavaScript. Composition is almost always better, IMO.

**Comment by yiminghe** [comment]
need a way to bind events to body/document in react way, because react will batch setState in event handler, it is very useful.

such as:
```
React.createClass({
 onDocumentEventType:function(){
 }
})
```

**Comment by spicyj** [comment]
You can use React.addons.batchedUpdates to get the same functionality.

**Comment by yiminghe** [comment]
@spicyj 

It's not in docs? http://facebook.github.io/react/docs/addons.html

Better make it into core, we usually just use react core.

**Comment by spicyj** [comment]
Ah, yes. #3570

**Comment by spicyj** [comment]
As for this issue generally, see #1608. We're not planning to add this event. For many cases with popups and modals, you can add a backdrop element (either transparent or not) to capture clicks. For others, you can add a top-level listener to the document and catch clicks. #285 tracks adding a more complete solution to that, though for now manually calling addEventListener for that case is probably best.

**Comment by polkovnikov-ph** [comment]
Could we at least document [here](https://facebook.github.io/react/docs/events.html) that React events are handled after all the native DOM events are handled?

**Comment by spicyj** [comment]
@polkovnikov-ph That's not necessarily true – it depends when the other listeners are added.

**Comment by johndous** [comment]
Following @gaearon and @willdady suggestions a very simple DropDown implementation could be like the following one:

<img width="95" alt="drop_down" src="https://cloud.githubusercontent.com/assets/14273133/21192679/10824a8c-c232-11e6-8083-4e10bcf742b2.png">
 
> Note that the DropDown remains open when user clicks on input field.

DropDown.js
```js
import React, { Component, PropTypes } from 'react';

class DropDown extends Component {
  constructor(props) {
    super(props);
    this.onClick = this.onClick.bind(this);
  }

  componentDidMount() {
    document.addEventListener('click', this.props.onBodyClick);
  }

  componentWillUnmount() {
    document.removeEventListener('click', this.props.onBodyClick);
  }

  onClick(e) {
    e.nativeEvent.stopImmediatePropagation();
  }

  render() {
    return (
      <div onClick={this.onClick}>
        {this.props.children}
      </div>
    );
  }
}

DropDown.propTypes = {
  children: PropTypes.node,
  onBodyClick: PropTypes.func
};

DropDown.defaultProps = {
  onBodyClick: () => {}
};

export default DropDown;
```
MyComponent.js
```js
import React, { Component, PropTypes } from 'react';
import DropDown from './DropDown';

class MyComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isMenuOpen: false
    };
    this.onBodyClick = this.onBodyClick.bind(this);
    this.onInputClick = this.onInputClick.bind(this);
  }

  onInputClick() {
    this.setState({ isMenuOpen: true });
  }

  onBodyClick() {
    if (document.activeElement === this.textInput) {
      return;
    }
    this.setState({ isMenuOpen: false });
  }

  render() {
    return (
      <div>
        <input
          ref={(ref) => { this.textInput = ref; }}
          onClick={this.onInputClick}
        />
        <DropDown onBodyClick={this.onBodyClick}>
          <ul>
            <li>Option 1</li>
            <li>Option 2</li>
            <li>Option 3</li>
          </ul>
        </DropDown>
      </div>
    );
  }
}

export default MyComponent;
```

**Comment by Pomax** [comment]
Also note that https://github.com/Pomax/react-onclickoutside has seen contributions from some 24 people over the last 8 months and has been on a constant modernization cycle, so as of this comment it's at v5.7, and implemented as Higher Order Component that can turn anything you throw at it into a component with onclickoutside monitoring, making dropdown menus *really* easy to implement.

**Comment by jonmiles** [comment]
@johndous I think this solution only works on desktop, what about mobile devices and touch events which do not trigger click events.  Any suggestions on how to handle this?

**Comment by sorenhoyer** [comment]
@jonmiles this works for both mouse click and touch

```
import { RefObject, useEffect } from 'react';
import { Handler, PossibleEvent } from './types';

const useOnClickOutside = (ref: RefObject<HTMLElement>, handler: Handler): void => {
  useEffect(() => {
    const listener = (event: PossibleEvent): void => {
      if (!ref?.current || ref?.current?.contains?.(event.target as Node)) {
        return;
      }

      handler(event);
    };

    document.addEventListener('click', listener);
    document.addEventListener('touchmove', listener);

    return (): void => {
      document.removeEventListener('click', listener);
      document.removeEventListener('touchmove', listener);
    };
  }, [ref, handler]);
};

export default useOnClickOutside;
```

Just be sure to put `e.nativeEvent.stopImmediatePropagation();` in your click handler.
