### ISSUE TITLE
 Do we really need to write <MyComponent/> to call `Stateless functional components`?

### ISSUE THREAD

**Issue by kenokabe** [facebook/react#5794]
What I have discovered most excitingly in the last v0.14 release is Stateless functional components.
I think this can unleash React power in JS functional programming realm.

Accordingly, I have found the fact I do not have to write  `<MyComponent/>` to use my components since as long as I stick to Stateless functional components, all I need to do is to call the Stateless functional components in normal JS way, that is, `MyComponent();`.
More importantly, avoiding to write in the legacy way `<MyComponent/>`, I do not have to write `props`. like below:

https://jsfiddle.net/r4y5kdoq/6/

```js
  var ChildNumberComponent = (number) => (
  <div>child{number}</div>
  );

  var ChildrenNumberComponent3 = () => {

    var el = (
    <div>
        {ChildNumberComponent(0)}
        {ChildNumberComponent(1)}
        {ChildNumberComponent(2)}
    </div>
    );
    return el;

  };

  var mount = ReactDOM.render(ChildrenNumberComponent3(), 
                    document.getElementById('container'));
```

https://jsfiddle.net/r4y5kdoq/7/

```js
  var ChildNumberComponent = (number) => (
  <div>child{number}</div>
  );

  var ChildrenNumberComponent5 = () => {

    var el = (
    <div>
        {[ChildNumberComponent(0),
      ChildNumberComponent(1),
      ChildNumberComponent(2),
      ChildNumberComponent(3),
      ChildNumberComponent(4)]}
    </div>
    );
    return el;

  };

  var mount = ReactDOM.render(ChildrenNumberComponent5(), 
                    document.getElementById('container'));
```

Although, I often encounter some warning that says:

>Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.

I think this is another issue.

To me, it's obvious that when we can express and use Components in vanilla JS function with `{ }` wrapping expression, it appears potentially much more powerful to write in the JS legacy functional way rather than to write  `<MyComponent someattr = {val} />` with `props` in the HTML way. In JSX, `MyComponent(val)` is simpler to call and receive the args and less rules, although I don't have intention to deny to still have a wide option in the legacy HTML tag way.

So, this is my thought about not using `props` anymore for Stateless functional components.

-------

The another discovery is not using `state` anymore for stateful Components.

The major reason we have not had Stateless functional components until recently should be the fact we need to deal state in real world.

I wrote a little helper component with my own event system that is [Time Engine](https://www.npmjs.com/package/timeengine)

```js
  //***React state with life cycle is stateless sequence*****
  var seqComponent = (__seq) => {

    class SeqComponent extends React.Component {
      constructor() {
        super();
        this.state = {
          seq: __seq.t
        };
        var timeseq = __seq
          .tMap((val) => {
            this.setState({
              seq: val
            });
          });
      }
      render() {
        return (<span>{this.state.seq}</span>);
      };
    }

    return (<SeqComponent/>);
  };
 ```

This helper Component is the only (to be hidden) place to write react `state` system, and with this special Component, I can deal stateful mutable Component with the pure functional Components such as:

```js
 var PhysicsComponent = () => {

    var __seqElement = __([x, y]) //atomic update
      .tMap(([x, y]) => (
      <div>
        <svg height = "100%"  width = "100%">
            <circle r="3" fill="red"
        cx = {50 + x * Drawscale} cy = {500 - y * Drawscale}/>
        </svg>
      </div>));

    var el = (<div>{seqComponent(__seqElement)}</div>);

    return el;
  };

  var mount = React.render(PhysicsComponent(), document.getElementById('container'));
```

The working live demo is:
http://sakurafunctional.github.io/demo/react-physics/

Code:
https://github.com/sakurafunctional/sakurafunctional.github.io/blob/master/demo/react-physics/index.jsx

Hopefully, I could show some potential of the new stateful Components and help others who want to seek a way to write stateful Components with Stateless functional components.

Overall, I would like to hear your thought. Thanks.

**Comment by jimfb** [comment]
Thanks for the post!

Discussions/posts are better held on other sites (like facebook, irc, medium or discuss.reactjs.org), as we try to use github issues for tracking bugs in the React core. Since this isn't actually a bug in the React core, I'm going to close out this issue, but feel free to continue the conversation here or move it to one of those mediums.

**Comment by kenokabe** [comment]
All right, thanks for more appropriate places to discuss. @jimfb :)
