### ISSUE TITLE
React transition removing *-leave classes before removal

### ISSUE THREAD

**Issue by alisd23** [facebook/react#5796]
I came accross an issue with the ReactCSSTransitionGroup component, where the `*-leave` and `*-leave-active` classes were removed **before** the component was removed from the dom.

In my situation this caused a flicker (due to styles being briefly changed before the element itself was removed). So I was wondering is this behaviour on purpose, or should the leave classes be kept on all the way through to dom removal, never removing them?

**Comment by MadeInMoon** [comment]
I used  ReactCSSTransitionGroup several times, and never experimented this issue, could you provide a bit of code?

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition
