### ISSUE TITLE
starter kit link in readme points to 0.14.5 version

### ISSUE THREAD

**Issue by httpete-ire** [facebook/react#5798]
the starter kit link in the readme file points to the 0.14.5 version instead of 0.14.6, I can make the change if it hasnt been done yet

**Comment by jimfb** [comment]
Which link are you looking at?  It looks correct to me: http://facebook.github.io/react/downloads.html

**Comment by zpao** [comment]
In the readme, like he said :)

I need to cherry-pick a couple commits to master, including the change to the readme. Will do that shortly.

**Comment by zpao** [comment]
I guess I can see the confusion. The readme in the starter kit on the website references 0.14.6. But the readme in the repo was referencing the 0.14.5 starter kit. Regardless, I just cherry-picked the commits so master is up to date.

**Comment by httpete-ire** [comment]
@zpao :+1:
