### ISSUE TITLE
componentWillReceiveProps happening immediately after loading only on mobile browsers

### ISSUE THREAD

**Issue by banderson5144** [facebook/react#5800]
I am seeing an issue when I load a component that componentWillReceiveProps is being called almost immediately after. This is only happening on mobile browsers. On desktop I am not seeing this issue. Anyone else experiencing this?

**Comment by jimfb** [comment]
What version of React are you using.  Is this on 0.14.6 or on the master branch?  What mobile phone (android?) are you using, what browser, what version?  Can you create a jsfiddle that demonstrates the issue?
