### ISSUE TITLE
Babel 6.4 - Semicolons and arrow functions in a class

### ISSUE THREAD

**Issue by ThaJay** [facebook/react#5802]
I would like to share https://github.com/babel/babel/pull/3231#discussion-diff-49011143 this diff to everyone as I haven't seen Babel post about it.

My transpile broke today because of this change.
+* **Spec Compliancy**
+ * `babylon`: [#3225](https://github.com/babel/babel/pull/3225) throw parse error if class properties do not have a semicolon.

In practise this means in a class not only the constructor needs a semicolon, but arrow functions as well. I used arrow functions for 'this' to fall through, so I changed it to normal functions + add '.bind(this)' to the call where needed.
(we're using the node coding style https://docs.npmjs.com/misc/coding-style)

**Comment by jimfb** [comment]
We try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation on this thread, or post on another site.  I feel like a StackOverflow post with the exact text of the error message (so people can search for it) tagged with ES6 and React and Babel is more likely to be findable than this github - posting there would be my recommendation.
