### ISSUE TITLE
Improve Documentation Translation Management

### ISSUE THREAD

**Issue by zpao** [facebook/react#5810]
It's really ad hoc right now so we should make it better. It's not a huge deal since we do a shitty job of exposing the translations but there are groups of people actively contributing so we should do our best to make it easier.

@thejameskyle has had great success using CrowdIn so I set up a project there - https://crowdin.com/project/react. I'll do some more work over the next few days to get it syncing from GH based on his article (https://github.com/thejameskyle/crowdin-sync) and then we'll go from there.

Thanks for the inspiration James!

**Comment by thejameskyle** [comment]
If you want, I already have the syncing service all setup and I can add react in like 2 mins. The biggest part is figuring out where you want the translations to live.

**Comment by zpao** [comment]
Awesome, I might take you up on that. Right now they live alongside the English (eg https://github.com/facebook/react/blob/master/docs/docs/01-why-react.md and https://github.com/facebook/react/blob/master/docs/docs/01-why-react.zh-CN.md) but that might change if I ever get back to #4633 and do it differently. I think I need to do a little bit more playing with this to see what will be best for us.

**Comment by thejameskyle** [comment]
Sure thing. I do need my bot to have push access to the repo in order to update it. I understand if you are hesitant to do that though.

**Comment by gaearon** [comment]
Whoops, I didn't notice this issue and created #8063.
Since this is becoming more urgent (we deleted all old localized content) let's just track this in #8063 which is more visible than this issue.
