### ISSUE TITLE
<input type="number" value='2'/> Is stuck on 2!

### ISSUE THREAD

**Issue by tnrich** [facebook/react#5812]
Number inputs in react don't follow the normal html conventions.

It seems as though number inputs with a set value are "stuck" at that set value. This should not be the case! 

Demo of the issue:

https://jsfiddle.net/w5b2as77/

**Comment by yangshun** [comment]
That's not a bug, it's intended behaviour: http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by andrewgrewell** [comment]
your looking for ``defaultValue``

**Comment by jimfb** [comment]
Thanks @yangshun and @andrewgrewell.

@tnrich What they said is correct.  You should read through the docs on forms.  Although you'll probably initially prefer uncontrolled inputs, as you use React more, you'll discover that controlled inputs really are better (IMHO).

**Comment by tnrich** [comment]
Awesome thanks everyone! That's a very educational link :)
