### ISSUE TITLE
event handlers arguments

### ISSUE THREAD

**Issue by titoBouzout** [facebook/react#5815]
https://facebook.github.io/react/docs/events.html

The page does not mention that events may receive foreign arguments that are unexpected on "normal" browser events. For example I have an event handler like this:

function handleThis(e, somethingElse){}

in a browser <.img onerror="handleThis"/> the argument somethingElse will be always undefined but in react 

<.img onError={handleThis} /> the argument somethingElse will have things I don't expect like a string with this content ".2.2.$1.$e=1e925dd08ffdee5af4825d9d9c632a655"

would be possible to add that as a property of the event? like

event.__SECRET_DOM_DO_NOT_ADD_RANDOM_UNEXPECTED_ARGUMENTS_TO_EVENTS_OR_YOU_WILL_BE_FIRED

?

**Comment by jimfb** [comment]
I don't think we pass a second argument anymore, as of React 0.15 / master.

http://jsfiddle.net/e47hj19q/

**Comment by titoBouzout** [comment]
wonderful thank you
