### ISSUE TITLE
onTouchStart fire extremely slow in ios9.2'safari

### ISSUE THREAD

**Issue by biblesyme** [facebook/react#5817]
onTouchStart fire extremely slow in ios9.2'safari.slow then onClick.  is this a bug?

**Comment by jimfb** [comment]
Can you provide two fiddles?  One to demonstrate that it is fast without React, and another to demonstrate that it is slow in React?

**Comment by jimfb** [comment]
No response for two weeks.  We can re-examine this issue if OP can demo the problem.

**Comment by biblesyme** [comment]
sorry,so busy these days. i will provide jsfiddles as soon as possible, . i could simply describe the test method.just a really easy example,  like these below, 

 `
var Test = React.CreateClass({
       handleTouch:function(){
           alert('touchStart');
      },
       render:function(){
            return (
                <div onTouchStart={this.handleTouch}></div>
            )
      }
});
`

this alert will show very slow after i touch [div] element on screen on  ios9.2'safari  , but,other browser like chrome perform normally.

**Comment by enriquetuya** [comment]
@jimfb could this issue be reopened base on the comment above? 
https://github.com/facebook/react/issues/5817#issuecomment-176854923

**Comment by enriquetuya** [comment]
@biblesyme are you experiencing the same with the latest 15.0.1 version?

**Comment by gaearon** [comment]
The example above doesn’t demonstrate that the lag doesn’t exist without React.
Are you sure it is React-related? Can you show this with a fiddle?

**Comment by biblesyme** [comment]
reactExample(https://jsfiddle.net/69z2wepo/39302/)
planJavascript(https://jsfiddle.net/n5furn55/6/)
jquery(https://jsfiddle.net/hdojb5zm/)

it seems as a safari problem, but, some could explain why it's so slow to trigger a touchstart on safari, and how to solve this problem

**Comment by biblesyme** [comment]
hi guys,it's seems not because safari 'trigger' touchstart slow,but 'alert' slow. i don't know why. 

and, may i ask what's time React will support 'tap' event, it's seems not difficult to achieve this

**Comment by enriquetuya** [comment]
@biblesyme check this out: https://github.com/zilverline/react-tap-event-plugin#introduction

We solved our problem not using that plugin though, we ended up using https://github.com/ftlabs/fastclick

This issue relates to: https://github.com/facebook/react/issues/436 and https://github.com/facebook/react/pull/1170
