### ISSUE TITLE
can't seem to update name attribute

### ISSUE THREAD

**Issue by pekeler** [facebook/react#5824]
Using 0.14.3, re-rendering an element with a new value for the `name` attribute keeps the old value.

```JavaScript
const render = (name) => {
  ReactDOM.render(
    <div name={name}>{name}</div>,
    document.getElementById('main')
  );
};
render('foo1');
render('foo2');
```

`getAttribute('name')` still returns "foo1". I know old versions of IE considered `name` readonly. In new browsers, however, `setAttribute('name', whatever)` works fine. Why not with React?

http://jsbin.com/bexate/2/edit?js,console,output

**Comment by zpao** [comment]
`name` is only actually a supported attribute on form elements (eg `<input>`). In that case it's a property and React updates it with `node.name = newValue`.

**Comment by pekeler** [comment]
OK, fair enough. Thanks.
