### ISSUE TITLE
Selects with a lot of default values aren't running efficiently. 

### ISSUE THREAD

**Issue by liamgray** [facebook/react#5825]
An app I'm building requires a `select` with a lot of `option`s, and they are all checked by default. There appears to be an issue with React's performance for this situation.

[Here's a JSFiddle.](https://jsfiddle.net/ach1d7x9/) It builds a `select` with 500 options, all selected, and takes over a second to run on my computer. If you remove `defaultValues`, you can see that it runs almost instantly. And if you set it to 5000 options, it takes over 2 minutes to run for me. 

The problem appears to get exponentially worse the more selected options you have. I realize that this is an edge case, but it also seems like a bug to me.

**Comment by syranide** [comment]
Good find, but it's really weird that it would exhibit exponential running cost for something which intuitively should not have it:

https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/ReactDOMSelect.js#L117-L127

**Comment by syranide** [comment]
Apparently `option.selected = value` has an `O(n)` cost as well.

**Comment by syranide** [comment]
After further testing this is *entirely* unavoidable, the cost is near identical to simply setting `innerHTML` of the `select` with all the options pre-`selected`. The cost of natively selecting an option is apparently `O(n)` for some reason.

**Comment by jimfb** [comment]
Is that true on all browsers?  Can we file tickets against the appropriate browsers and then close this out as a React issue?

**Comment by syranide** [comment]
@jimfb Primarily Chrome, IE is a lot faster and doesn't blow up as fast, don't have FF here. However, there's something else that is fishy, when I try it locally Chrome it is *a lot* faster, I can do ~8000 in less than a second and after that it starts blowing up. But I'm using virtually the same code as in React... ???

```html
<html>
<body>
<select id="select" multiple></div>
<script>
var select = document.getElementById('select');

var html = '';
for (var i = 0; i < 8000; i++) {
  html += '<option>' + i + '</option>';
}

var start = Date.now();
select.innerHTML = html;
console.log(Date.now() - start);

var l = {};
for (var i = 0; i < 8000; i++) {
  l['' + i] = true;
}


var start = Date.now();

var options = select.options;

for (i = 0; i < options.length; i++) {
  var value = l.hasOwnProperty('' + i);
  if (options[i].selected !== value) {
    var o = options[i];
    o.selected = true;

  }
}


console.log(Date.now() - start);
</script>
</body>
</html>
```

**Comment by liamgray** [comment]
Thanks for looking into this.

I just gave it a go on Firefox, and it ran in 43 milliseconds. Weird... might be a bug in Chrome instead of React.

This is what I'm seeing in the chrome dev tools:

![image](https://cloud.githubusercontent.com/assets/2565853/12248979/c30d591a-b871-11e5-9f62-446e8fa85192.png)

All those little purple lines are "Recalculate Style." It seems like it should be possible to update all the nodes at once and recalculate the style one time instead of once for every node. It also says it's recalculating the style for 501 elements for each one of those, that might be the other solution.

It also gives this warning:

> Forced synchronous layout is a possible performance bottleneck.

Again, I'm relatively new to all of this so I hope this is helpful.

**Comment by jimfb** [comment]
@syranide Check out my nearly identical fiddle: https://jsfiddle.net/vr0vquag/

Updates take 10x longer than your fiddle.

**Comment by syranide** [comment]
@jimfb Uuuuh...??? What the hell? Thanks for sorting that out fast, but that makes no sense to me. I take it all this is some browser weirdness at the very least and React is not to blame at all here.

**Comment by syranide** [comment]
@liamgray Also thanks, yeah that's obviously Chrome doing something not so great.

**Comment by jimfb** [comment]
Actually, I don't think my fiddle is doing anything differently, I just ran it again and I think it's behaving like your fiddle (faster than React).

**Comment by liamgray** [comment]
Yeah, I'm seeing your fiddle build a select with 8000 defaults in just about the same time as React builds one with 500. Chrome 47 on a Mac.

Is this the kind of thing that will get a fix within React, or should I be submitting a bug to Google?

**Comment by jimfb** [comment]
Yes, I think we need to submit a chrome bug.

Here is the repro:
 > Fast: https://jsfiddle.net/h07a47t2/
 > Slow: https://jsfiddle.net/nbrtqn7t/
 > 
 > Two fiddles perform virtually identical operations, but there is a 10x performance difference.
 > We've discovered an even larger performance difference in real-world (React) applications.
 > Discovered in https://github.com/facebook/react/issues/5825 (in case it's helpful additional context/information)

@liamgray Do you want to do the honors, submit the chrome bug?  Also, cross-post links between the two issues so we can track progress?

**Comment by liamgray** [comment]
I've submitted the issue to them [here](https://code.google.com/p/chromium/issues/detail?id=576459&thanks=576459&ts=1452555254). Thanks for helping me through this. Hopefully it can all be resolved quickly!

**Comment by jimfb** [comment]
Great, thanks!  I'm going to close this out in the React repository (since it's a bug in chrome), and we'll let the Google/chrome bug take over from here.
