### ISSUE TITLE
<source onError={callback}> doesn't work

### ISSUE THREAD

**Issue by dmnd** [facebook/react#5839]
The error event on `<source>` elements doesn't work. Looking at #4370, it seems like there is an `onError` for `<video>` but I can't tell if that's supposed to work for `<source>` too.

The error event is useful so I can deduce which format the browser is using.

**Comment by zpao** [comment]
Do these error events bubble? We might have to attach listeners directly if not (which is what we do for the video & audio elements)

**Comment by petetnt** [comment]
@zpao They don't bubble, so attaching listeners directly seems like the proper way.

**Comment by zpao** [comment]
Great, and does source have any other events? My quick research only shows error but I suspect load is there as well and probably has the same non-bubbling (basically the same as an img element). I'll try to do some testing but any pointers to specs and whatnot would be helpful.

**Comment by alunyov** [comment]
Hey, guys! This should add onError to the `<source>`: https://github.com/facebook/react/pull/5861

**Comment by petetnt** [comment]
@zpao The spec says that it should follow the resource selection algorithm specified [here](http://dev.w3.org/html5/spec-preview/media-elements.html#concept-media-load-algorithm)  so it should also support at least `loadstart`.

**Comment by alunyov** [comment]
It should, but in fact, it does not support `load` and `loadstart`. https://jsfiddle.net/n7sdjh22/
