### ISSUE TITLE
 Unhelpful error: "caught TypeError: Cannot read property 'refs' of null"

### ISSUE THREAD

**Issue by m4nuC** [facebook/react#5841]
Adding a `ref` to a child element of a stateless component yields a **caught TypeError: Cannot read property 'refs' of null**. I can see this being really hard to debug. Could there be a better error message there ?

**Comment by jimfb** [comment]
Duplicate of: https://github.com/facebook/react/issues/4939
Fixed in: https://github.com/facebook/react/pull/4943

**Comment by jimfb** [comment]
Actually, I think I may have miss-read the issue.  What is it you are trying to do?  Can you provide a fiddle?

**Comment by m4nuC** [comment]
Actually you are right it behaves properly on fiddle. It must be something with my code. Thanks

**Comment by jimfb** [comment]
My fiddle is using a future/experimental version of React, so it's possible the issue was just fixed.  Either way, glad to hear it works in the latest fiddle!
