### ISSUE TITLE
Enormous data-reactid

### ISSUE THREAD

**Issue by polkovnikov-ph** [facebook/react#5846]
I'm developing a big GUI application. Chrome Developer Tools are lagging because of `data-reactid`s reaching a hundred kilobytes in size. Here's a (small) example:

     .0.$=1$=011.0.$=1$=01$0.0.0.$///=11//=1$//=011/=1$//=011/=01$/=0011.0.$//////=10/////=1$/////=010////=1$/////=010////=01$////=0010///=1$/////=010////=01$////=0010///=01$////=0010///=001$///=00010//=1$/////=010////=01$////=0010///=01$////=0010///=001$///=00010//=01$////=0010///=001$///=00010//=001$///=00010//=0001$//=000010/=1$/////=010////=01$////=0010///=01$////=0010///=001$///=00010//=01$////=0010///=001$///=00010//=001$///=00010//=0001$//=000010/=01$////=0010///=001$///=00010//=001$///=00010//=0001$//=000010/=001$///=00010//=0001$//=000010/=0001$//=000010/=00001$/=0000010.$///////=11//////=1$//////=011/////=1$//////=011/////=01$/////=0011////=1$//////=011/////=01$/////=0011////=01$/////=0011////=001$////=00011///=1$//////=011/////=01$/////=0011////=01$/////=0011////=001$////=00011///=01$/////=0011////=001$////=00011///=001$////=00011///=0001$///=000011//=1$//////=011/////=01$/////=0011////=01$/////=0011////=001$////=00011///=01$/////=0011////=001$////=00011///=001$////=00011///=0001$///=000011//=01$/////=0011////=001$////=00011///=001$////=00011///=0001$///=000011//=001$////=00011///=0001$///=000011//=0001$///=000011//=00001$//=0000011/=1$//////=011/////=01$/////=0011////=01$/////=0011////=001$////=00011///=01$/////=0011////=001$////=00011///=001$////=00011///=0001$///=000011//=01$/////=0011////=001$////=00011///=001$////=00011///=0001$///=000011//=001$////=00011///=0001$///=000011//=0001$///=000011//=00001$//=0000011/=01$/////=0011////=001$////=00011///=001$////=00011///=0001$///=000011//=001$////=00011///=0001$///=000011//=0001$///=000011//=00001$//=0000011/=001$////=00011///=0001$///=000011//=0001$///=000011//=00001$//=0000011/=0001$///=000011//=00001$//=0000011/=00001$//=0000011/=000001$/=00000011.0.0.$=1$=01$=001$=00012.0.0.$10/=1$10.$/=11

What do I do wrong? How `data-reactid` is computed (roughly)? Could you create a paragraph somewhere in the performance manual on this issue?

**Comment by jimfb** [comment]
You probably have really long `key` prop specified on one of your elements.  If you are passing data in as your key, you can probably hash the data before passing it in (which will limit the length, and ensure the value is alphanumeric).

This has been fixed in React 0.15 (master).
