### ISSUE TITLE
Issues with installing master with npm 3

### ISSUE THREAD

**Issue by polkovnikov-ph** [facebook/react#5847]
Installer tries to run build script from the `node_modules` folder inside `sbjs-scripts`, while `npm 3` is using flat `node_modules` structure.

	C:\repo>npm install --save facebook/react
	npm WARN install Couldn't install optional dependency: Unsupported

	> react-build@0.15.0-alpha postinstall C:\repo\node_modules\react-build
	> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

	module.js:339
		throw err;
		^

	Error: Cannot find module 'C:\repo\node_modules\react-build\node_modules\fbjs-scripts\node\check-dev-engines.js'
		at Function.Module._resolveFilename (module.js:337:15)
		at Function.Module._load (module.js:287:25)
		at Function.Module.runMain (module.js:457:10)
		at startup (node.js:136:18)
		at node.js:972:3

Additional info:

 - npm @ 3.3.6
 - node.js @ 5.0.0
 - windows 7 x64 ru_RU
 - was trying to check for resolution of [this question](https://github.com/facebook/react/issues/5846)

**Comment by zpao** [comment]
Installing React from github is not supported. You can checkout the repo and build (should work with npm 3 but the team doesn't use that) if you want a build from master. The build artifacts (in `build/packages`) are what get shipped to npm.
