### ISSUE TITLE
Allow props/state to be of types other than Object

### ISSUE THREAD

**Issue by japgolly** [facebook/react#5854]
Hello I'm the author of [scalajs-react](https://japgolly.github.io/scalajs-react/) which facilitates using React from the statically-typed Scala language.

I use immutable Scala values as components' props and state but because React requires JS objects I have to wrap all props/values in a single-key object. For example instead of just setting a component's state to `3` I have to wrap it into `{v: 3}`.

Also as I understand it, React performs additional work with the objects it receives, like if a component has state `{a: 9, b: 8}` when receiving a `setState {a: 1}` it will actually merge the two to create a new object `{a: 1, b: 8}`. This feature is very useful when developing in JS but very useless for all consumers of my library and perhaps others (Om maybe? maybe not); the reason being that in my case, that merging of props/state is done via Scala itself where all the static types and other invariants can be checked by the compiler.

It would be much more efficient for us who use React via other languages to allow components to use types other than Object in props/state. Even a simple check like *if (newState is Object) mergeStates else blindlyReplaceState* would be sufficient. WDYT?

**Comment by jimfb** [comment]
I will admit I'm both confused and intrigued at the same time.

People are writing components in Scala, which presumably gets transpiled into an ES5 component and fed into React, do I have that right?

Why wouldn't your scala components just be a wrapper around a react component, like this:
```
function setState(immutableScalaObjectRepresentingNewState) {
  component.setState({key: immutableScalaObjectRepresentingNewState});
}
function getState() {
  return component.state.key;
}
```

It should be possible to support a purely-scala interface, with the setState semantics you want, just by wrapping in a new object.  From a usability perspective, it should be completely transparent, right?

So is the complaint that setting state requires an object allocation (ie. it's a performance argument/complaint?).  Or what's the root of your issue?

**Comment by japgolly** [comment]
Hey Jim,

> People are writing components in Scala, which presumably gets transpiled into an ES5 component and fed into React, do I have that right?

Bingo

> Why wouldn't your scala components just be a wrapper around a react component, like this

Bingo again.

> It should be possible to support a purely-scala interface ... it should be completely transparent, right?

Trifecta!

> So is the complaint that setting state requires an object allocation (ie. it's a performance complaint?). 

Yes, that's exactly right. Sorry if I wasn't clear enough about that - this is purely about efficiency and performance. All the plumbing between our two libraries and the functionality itself is working fine. It's just the additional cost of all those unnecessary objects being allocated and the object comparison/merging on every `setState` invocation that I'd like to avoid if possible.

**Comment by jimfb** [comment]
Is that even measurable though?

A setState is going to cause a rerender, which is going to cause a whole bunch of element objects to be allocated (entire trees of them, potentially).  And then React needs to run the reconciler to calculate a diff of the two element trees.  A single object allocation and a shallow compare of an object with a single key shouldn't even be detectable in comparison.

**Comment by japgolly** [comment]
I haven't measured it but I have a page that can have over 1000 components on display at once. I was thinking that this change I'm requesting would be easy and low impact, and would save at least 4 objects per component plus all the unnecessary object comparison/merge work which would add up to something significant on a complex page such as I'm building. Every little bit counts as your complexity scales up.

**Comment by jimfb** [comment]
The comparison/merge work of the single-key object only happens once per `setState()`, and the cost should be beyond negligible.  Ideally most (all) of your components should be stateless anyway, which means they won't ever have a state object allocated.  I'm reasonably sure that for all practical intents and purposes, the overhead is so small that you'd have a hard time even measuring it.

I'm going to close this out because there are much lower hanging fruits.  It's not worth an API change here if there is no evidence that it's actually a problem for anybody.
