### ISSUE TITLE
Issue with ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by bokzor** [facebook/react#5855]
I'm getting this error 

Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

after installing ReactCSSTransitionGroup and It seems that I have only one copy of react running.

I'm using gulp and browserify to package the app.

+-- babel-preset-react@6.3.13
| +-- babel-plugin-transform-react-display-name@6.3.13
| +-- babel-plugin-transform-react-jsx@6.3.13
| | `-- babel-helper-builder-react-jsx@6.3.13
| `-- babel-plugin-transform-react-jsx-source@6.3.13
+-- eslint-plugin-react@3.15.0
+-- formsy-react@0.17.0
+-- react@0.14.6
+-- react-addons-css-transition-group@0.14.6
+-- react-dom@0.14.6
+-- react-router@1.0.3

**Comment by jimfb** [comment]
There isn't enough information here for us to reproduce the bug, so this really isn't actionable.  Furthermore, if the error occurred after installing an npm module, and you aren't doing anything fancy with refs, I would **strongly** suspect that something is somehow screwed up with your npm dependencies (npm seems to get confused more often than you'd think).  I'm going to blame NPM in this case; you can try reading the comments in https://fb.me/react-refs-must-have-owner and see if any of them help you.  I'm going to close this out as a usage question, but if you can provide a jsfiddle that demonstrates an issue in the core, we can re-investigate.

**Comment by dajomu** [comment]
I had this same problem and it was fixed by removing unused refs on one of my components. If you're getting this error check for refs that you don't use when rendering the component that is giving the error.
