### ISSUE TITLE
Consider applying HTML namespace by default

### ISSUE THREAD

**Issue by jlongster** [facebook/react#5856]
Currently, when creating elements React checks for various namespaces like SVG and uses `createElementNS`, but when it's HTML it does not apply a namespace (at least in `ReactDOMComponent.Mixin.mountComponent` it checks, there are other places that do `document.createElement` without any checking).

In Firefox, we are starting to use React in XUL pages. We are trying to get off of XUL as fast as we can, but we need a migration path. When using React in a XUL page, it will create XUL elements by default because that is the default namespace (and a XUL `div` is different than a HTML `div`).

Is there any chance you all could apply the HTML namespace when creating elements? It would look like `document.createElementNS("http://www.w3.org/1999/xhtml", tag)` instead of the normal `createElement` call.

If that's not possible, is there anything React can do to help us out? If not, we're going to have to fork React and change all `createElement` calls to `createElementNS`, which isn't hard (I've already done it) but I wanted to ask here first before we fork it. I'm fine forking it for now, in while when we are mostly HTML we can drop the fork.

**Comment by jlongster** [comment]
@zpao You know *all* about this ;)

**Comment by jlongster** [comment]
fwiw, this is our fork: https://github.com/mozilla/react/commits/0.14.6-for-firefox

The commit specific to this issue is https://github.com/mozilla/react/commit/befab4ec31ce6b567cacb6a04d94ea7936cd7ec2

I understand this is probably not worth it for everybody else. It would be great if someone to validate what I'm doing though.

**Comment by spicyj** [comment]
Mostly fine with me as long as it doesn't impact perf… I didn't benchmark to check.

**Comment by jlongster** [comment]
Are there benchmarks in the repo that I can run?

**Comment by spicyj** [comment]
Could look at

https://github.com/spicyj/innerhtml-vs-createelement-vs-clonenode

Particularly testCreate in Chrome/Safari/Firefox and testCreate2 in Edge/IE11.

**Comment by jlongster** [comment]
I created a basic jsperf case: http://jsperf.com/createelementns Not sure how accurate it is though. I can ask around and see if there's any reason the perf would be different.

**Comment by jlongster** [comment]
Here are the numbers:

```
Firefox w/createElement

bench.html?testFn=testHTML (10): 96.3, 99.7% ci: [90.4, 107.4]
bench.html?testFn=testCreate (10): 83.6, 99.7% ci: [79.8, 89.0]
bench.html?testFn=testCreate2 (10): 83.3, 99.7% ci: [81.6, 85.1]
bench.html?testFn=testClone (10): 57.3, 99.7% ci: [54.6, 60.8]

Firefox w/createElementNS

bench.html?testFn=testHTML (10): 95.4, 99.7% ci: [89.8, 103.4]
bench.html?testFn=testCreate (10): 80.6, 99.7% ci: [82.3, 84.3]
bench.html?testFn=testCreate2 (10): 85.4, 99.7% ci: [83.1, 87.6]
bench.html?testFn=testClone (10): 56.8, 99.7% ci: [55.2, 59.3] 

Chrome w/createElement

bench.html?testFn=testHTML (10): 48.9, 99.7% ci: [47.0, 51.3]
bench.html?testFn=testCreate (10): 28.4, 99.7% ci: [26.3, 30.6]
bench.html?testFn=testCreate2 (10): 29.3, 99.7% ci: [25.7, 33.0]
bench.html?testFn=testClone (10): 24.3, 99.7% ci: [21.3, 27.3]

Chrome w/createElementNS

bench.html?testFn=testHTML (10): 49.7, 99.7% ci: [47.8, 51.9]
bench.html?testFn=testCreate (10): 29.8, 99.7% ci: [28.3, 31.2]
bench.html?testFn=testCreate2 (10): 30.2, 99.7% ci: [27.9, 32.6]
bench.html?testFn=testClone (10): 21.2, 99.7% ci: [20.3, 22.3]
```

`testCreate` and `testCreate2` do seem *slightly* slower, consistently. That's probably enough to warrant some worrying about this.

In some ways I was hoping it'd be faster; you're being more explicit so it could avoid some checks. But I'm not sure.

BTW, near the end of the test I see this in the server:

```
[Fri, 15 Jan 2016 17:54:28 GMT] "GET /undefined" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.
2526.111 Safari/537.36"                                                                                                                             
[Fri, 15 Jan 2016 17:54:28 GMT] "GET /undefined" Error (404): "Not found"
```

Not sure what that's about.

**Comment by zpao** [comment]
I wonder if instead of doing it like https://github.com/mozilla/react/commit/befab4ec31ce6b567cacb6a04d94ea7936cd7ec2 we made this injectible at some point so that instead of a fork of anything larger, you would just have to change the default injection (which was at one point the goal of that file).

If it was really important to keep the small perf (and assuming this counteract any wins), it could look something like this

```js
// default
whatever.injectCreateElement(function(doc, type, ns) {
  if (ns) {
    return doc.createElementNS(ns, type);
  }
  return doc.createElement(type);
})

// mozilla "fork"
whatever.injectCreateElement(function(doc, type, ns) {
  if (!ns) { ns = 'xhtml ns' }
  return doc.createElementNS(ns, type);
})
```

**Comment by jlongster** [comment]
@zpao That would help, yep. Although it's not really that hard to patch a few function calls, so I'm not going to push hard to make that happen. I understand that it's just more complexity to maintain.

What I just found out, though, is that there are additional modules that need to be patched. For example, `createNodesFromMarkup` uses `createElement`, but it's a module in `react/node_modules/fbjs/lib/createNodesFromMarkup.js`. It's going to be a pain to coordinate patches to those individual modules (not sure if there are any more). Any advice for how to manage those?

I guess it looks like all that stuff is inside the `fbjs` module, which we might have to fork as well...

**Comment by jlongster** [comment]
I think we're going to delete our fork and just manually patch the generated .js file. It's too confusing to patch the un-built source because I'm not sure `document.createElement` calls end up actually being used. Much easier to grep through the built react.js file. We already have "upgrade instructions" so this will just be part of the upgrade process (I was hoping with a fork we could just rebase, but that will likely cause conflicts anyway).

I doubt we're going to upgrade again soon, so it's not a big deal. Hopefully by the next upgrade we'll have switched our documents to HTML so we don't need this anymore.
