### ISSUE TITLE
Controlled Components 'value' Not Being Reflected In The DOM

### ISSUE THREAD

**Issue by drizko** [facebook/react#5857]
I noticed that the input's value is not updated in the DOM when implementing a controlled component. Is this normal / expected behavior?
```
<div>
  <input
    // Controlled Component
    value={this.state.term}
    onChange={(event) => this.setState({ term: event.target.value })} />
</div>
```
Here is a link to an example on JSBin (When it first loads press 'Run with JS' button in Output section):
http://jsbin.com/sodojo/1/edit?html,js,output

**Comment by CoderK** [comment]
Have you reas this~?

https://facebook.github.io/react/docs/forms.html

**Comment by yangshun** [comment]
@drizko You should read this: http://stackoverflow.com/questions/6003819/properties-and-attributes-in-html

**Comment by drizko** [comment]
Thank you both for the resources, issue closed
