### ISSUE TITLE
Some assertions left in production mode

### ISSUE THREAD

**Issue by AlexGalays** [facebook/react#5871]
A few assertions are left in the production output (using webpack -p if that matters) as they're not located inside an `if(env)` block; Could squeeze a few bytes!

Examples:

```
"You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```

```
dangerouslySetInnerHTML` must be set using `updateInnerHTMLByID()`.",style:"`style` must be set using `updateStylesByID()`.
```

```
You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`."
```

**Comment by jimfb** [comment]
The second message was fixed in https://github.com/facebook/react/pull/5205

The first and third will probably be cleaned up as part of https://github.com/facebook/react/issues/2302, but I suppose we can keep this issue open until that happens.

**Comment by aweary** [comment]
None of these assertions exist in the latest 15 or 16 RC release 🎉
