### ISSUE TITLE
CSSTransitionGroup: Inconsistency between fallback behaviour and warning message

### ISSUE THREAD

**Issue by rhys-vdw** [facebook/react#5873]
Minor issue...

Deprecation warning is shown when property [`transition*Timeout` is `null` or `undefined`](https://github.com/facebook/react/blob/bef45b0b1a98ea9b472ba664d955a039cf2f8068/src/addons/transitions/ReactCSSTransitionGroup.js#L29). But behaviour falls back to deprecated behaviour [on any falsey value](https://github.com/facebook/react/blob/bef45b0b1a98ea9b472ba664d955a039cf2f8068/src/addons/transitions/ReactCSSTransitionGroupChild.js#L95-L102).

So the following will use deprecated behaviour without printing warning.

``` js
<CSSTransitionGroup { ...props } transitionLeaveTimeout={0} >
  { children }
</CSSTransitionGroup>
```

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
