### ISSUE TITLE
request: supporting <noindex> element

### ISSUE THREAD

**Issue by zhrivodkin** [facebook/react#5882]
Hi! Do you plan to support the <noindex> tag (and even better its valid type <!--noindex>)? It is very necessary for every SEO needs.

Type: Feature Request
Component: DOM (general issues)

**Comment by jimfb** [comment]
`<noindex>my text goes here</noindex>` appears to work in master: http://jsfiddle.net/bL4zthpb/

The `<!--noindex>` syntax appears to be a duplicate of https://github.com/facebook/react/issues/1035
