### ISSUE TITLE
react 0.14.6 renderToStaticMarkup for CustomComponent

### ISSUE THREAD

**Issue by barak007** [facebook/react#5883]
Hi,
Why does renderToStaticMarkup outputs "className" in the markup for "CustomComponent" (hyphenated tag-names)?
```jsx
React.renderToStaticMarkup(React.createElement('my-div', {className: 'bobi'}));

//outputs
<my-div className="bobi"></my-div>

//expected 
<my-div class="bobi"></my-div>
```

**Comment by jimfb** [comment]
Use the `class` prop instead of `className` for custom components.

Custom elements are allowed to do arbitrary processing of their props, so in order to support the full range of attributes, the only viable option is to pass them directly through.  https://github.com/facebook/react/issues/4933
