### ISSUE TITLE
Props undefined in getInitialState

### ISSUE THREAD

**Issue by gilbitron** [facebook/react#5888]
First I know this is an anti-pattern so please forgive me. I was doing something like this recently but noticed that on the first render the `this.state.origValue` was `undefined`:

```
getInitialState: function() {
    return {
        origValue: this.props.mydata.some_data
    };
},
```

The `props` did eventually get populated and was available on the next render. However as `getInitialState` is only ever called once `this.state.origValue` is always going to be `undefined`.

I fixed the issue by setting `this.state.origValue` in `componentDidMount`. However I wonder if its a bug that `this.props` isn't always available in `getInitialState`?

**Comment by jimfb** [comment]
Appears to work for me.  http://jsfiddle.net/8ux1md6c/

If you can provide a fiddle that demonstrates otherwise, we can re-investigate.

**Comment by gilbitron** [comment]
So apparently it only happens with arrays of data. Here is an example: http://jsfiddle.net/opbcd69z/2

**Comment by JeTmAn1981** [comment]
So this was never  confirmed?  I'm running into this issue myself.   From the various tests I've run, the prop I've passed in under the name "value" is definitely undefined in getInitialState, but when I use it as an input control's value, the input control shows up correctly with that value.  However, I need to be able to set the input control's state to that value so it can be updated.  When I'm just using the prop value directly, it doesn't let me change it in the control.  No matter how I try to assign the prop value to an equivalent state variable, it ends up undefined.

I can't post an example immediately as my application is pretty involved.  It will take me some time to figure out how to isolate the issue in an easily understandable format.

**Comment by Aweary** [comment]
@JeTmAn1981 if you can share a minimal test case reproducing the issue we can investigate this again. You can use https://jsfiddle.net/reactjs/69z2wepo/ as a starting point.
