### ISSUE TITLE
React does not support svg attributes.

### ISSUE THREAD

**Issue by vlinder** [facebook/react#5889]
There are a few svg attributes where support is lacking.

I have noticed that "mask" and "filter" are missing.

Mozilla have a list of all the svg core attributes here: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#Core

**Comment by jimfb** [comment]
I think this was fixed in https://github.com/facebook/react/pull/5714

If you can create a fiddle using latest (http://jsfiddle.net/9kungxn4/) that demonstrates the problem, we can reinvestigate.

**Comment by iamdustan** [comment]
@jimfb did #5714 get included in one of the 0.14 point releases?

**Comment by vlinder** [comment]
According to this comment https://github.com/facebook/react/issues/5763#issuecomment-168440449. No.

**Comment by jimfb** [comment]
Thanks @vlinder, correct, it will be part of 0.15.

**Comment by vlinder** [comment]
Can confirm that this was fixed, tried to recreate the problem in the fiddle, but it just worked. :)

**Comment by jimfb** [comment]
I'm pretty sure it was fixed; that's why I closed the bug.  The fiddle is using react future/master, so if it's working in that fiddle, it should work in the next release of React.
