### ISSUE TITLE
getInitialState in React.createClass warning

### ISSUE THREAD

**Issue by jasonvillalon** [facebook/react#5893]
Hi,

just migrated to react 0.14.6 and encounter this warning when switching to react.min.js

sample i have component:
```
const TestComponent = React.createClass({
  getInitialState() {
     return {
        number: 1
     }
  },
  render() {
    return (
      <div>Hello World</div>
    )
  }
}

export default TestComponent
```
when using react.min.js
i receive:
```
Warning: getInitialState was defined on TestComponent, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
```

but when using react.js there is no warning.

i tried to refactor everything to:
```
state: {
  number: 1
}
```
but then my state becomes null

thanks

**Comment by jimfb** [comment]
Are you sure you get the warning with `react.min.js` and NOT with `react.js`?  I would have expected it to be the other way around.  Warnings don't fire in production.

You can set your state in the constructor by saying: `constructor(){this.state = {number: 1}}`.

**Comment by zpao** [comment]
You don't have an ES6 class in this code so we shouldn't even be warning about `getInitialState` regardless of if you have the min build or not.

**Comment by jasonvillalon** [comment]
hi thank you for your reply. i created sample project to demonstrate what im experiencing here :
https://github.com/jasonvillalon/get-initial-state-bug

**Comment by jimfb** [comment]
@jasonvillalon I tried running your example, but it didn't work for me out of the box (gulp failed on the import syntax, among other things), and I didn't have time to debug the errors.

Your example is still very complex.  You've got gulp, babel, jspm, and [God knows what else](https://github.com/jasonvillalon/get-initial-state-bug/blob/master/config.js).  Please simplify it to the minimal hello world example (ideally running in a jsfiddle) that demonstrates the bug.

**Comment by jasonvillalon** [comment]
yeah i tried it in jsfiddle https://jsfiddle.net/pLxdeu4p/ and its working without warning. maybe its because im using jspm. ill close it now
