### ISSUE TITLE
ReactCSSTransitionGroup and Inline styles

### ISSUE THREAD

**Issue by jukkacaalto** [facebook/react#5898]
Is it possible to use React inline styles with ReactCSSTransitionGroup? If so, how?

I have tried, and this doesn't seem to work (React v. 0.14.6):

```
var tstyle = {
  'enter': {
    visibility: 'hidden',
    transform: 'translate3d(100%,0,0)'
  },
  'leave': {
    visibility: 'visible',
    transform: 'translate3d(0,0,0)'
  },
  'enterActive': {
    visibility: 'visible',
    transform: 'translate3d(0,0,0)',
    transition: 'all 0.4s'
  },
  'leaveActive': {
    visibility: 'hidden',
    transform: 'translate3d(100%,0,0)',
    transition: 'all 0.4s'
  }
}
```

In render():

```
    <ReactCSSTransitionGroup
      style={tstyle}
      transitionName={ {
        enter: 'enter',
        enterActive: 'enterActive',
        leave: 'leave',
        leaveActive: 'leaveActive',
        appear: 'appear',
        appearActive: 'appearActive'
      } }
      transitionEnterTimeout={400}
      transitionLeaveTimeout={400}>
      {this.props.notifications.map((notification, index) => {
        return <Notification
                key={index}
                type={notification.type}
                message={notification.message}
                timeout={10000}
                remove={this.props.actions.removeNotification} />
      })}
    </ReactCSSTransitionGroup>
```

**Comment by zpao** [comment]
It's not currently possible. I might be open to making it work but would likely say we should not use the `style` prop, and you'd need to consider what to do to make it coexist peacefully with the current expectaion of classes. If you're interested, please propose a complete solution before putting up a PR so we can hammer it out.

**Comment by pke** [comment]
:+1: for this. I had hoped to never have to write and bundle CSS files again. I like my markup and style together. @jukkacaalto are you working on a patch/fork?

**Comment by gaearon** [comment]
We don't maintain TransitionGroup in this repository anymore.
Its new home is here:
https://github.com/reactjs/react-transition-group
