### ISSUE TITLE
Question: how to just update parentless component outside of it?

### ISSUE THREAD

**Issue by mqklin** [facebook/react#5906]
Copy of [stackoverflow question](http://stackoverflow.com/questions/34941364/update-react-component-without-parent-outside-of-it/34941598?noredirect=1#comment57616408_34941598)

How should I properly update component if it doesn't have a parent?

I've found two ways to do it:
###[First method](https://jsfiddle.net/69z2wepo/28597/)
Here I update component through changing component`s state:

    var Hello = React.createClass({
      render: function() {
        if (!this.state) return null;
        return (
          <div>Hello {this.state.name}</div>
        );
      }
    });

    var component = ReactDOM.render(
      <Hello />,
      document.getElementById('container')
    );
    component.setState({name: "World"});

    setTimeout(function(){
      component.setState({name: "StackOverFlow"});
    }, 1000);

### [Second method](https://jsfiddle.net/69z2wepo/28596/)
Here I update component through `ReactDOM.render` method:

    var Hello = React.createClass({
      render: function() {
        return (
          <div>Hello {this.props.name}</div>
        );
      }
    });

    ReactDOM.render(
      <Hello name="world"/>,
        document.getElementById('container')
    );

    setTimeout(function(){
      ReactDOM.render(
        <Hello name="StackOverFlow"/>,
          document.getElementById('container')
      );

    }, 1000);

So which method is correct? Or maybe here is a third, *correct* way? I know that I should Flux etc., but I want to know the simplest way in the simplest example.

**Comment by jimfb** [comment]
Either method works, optimal solution probably depends on your use case.

Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).
