### ISSUE TITLE
HTMLtoJSX does not convert curly brackets

### ISSUE THREAD

**Issue by optimalisatie** [facebook/react#5910]
Hi!

I am experiencing a problem with the HTMLtoJSX converter (https://www.npmjs.com/package/htmltojsx), the same converter as officially displayed on https://facebook.github.io/react/html-jsx.html.

The HTML-code `<div>{</div>` is compiled to the following JSX-code:

```jsx
<div>{</div>
```
https://facebook.github.io/react/html-jsx.html

The JSX code fails with the following error:

```javascript
Uncaught SyntaxError: embedded: Unexpected token (7:18)
   5 | var Hello = React.createClass({
   6 |   render: function() {
>  7 |     return <div>{</div>;
     |                   ^
   8 |   }
   9 | });
```
Test: https://jsfiddle.net/69z2wepo/28714/

Does anyone know a solution for the problem?

Best Regards,
Jan Jaap

**Comment by zpao** [comment]
Can you file this in https://github.com/reactjs/react-magic, which is where that code lives? Thanks! (And cc @Daniel15 just so he sees it)

**Comment by Daniel15** [comment]
Good catch, thanks for reporting this! As @zpao mentioned, please file this in the react-magic repo so I remember to fix it :)

**Comment by optimalisatie** [comment]
Thanks for the fast replies!

I wanted to post the issue at [React-Magic](https://github.com/reactjs/react-magic) however I read in a reply from @Daniel15 that he would like issues related to HTML to JSX conversion in the general React.js repository.

> Issues with the HTML to JSX conversion should go into the general React.js repository.
> https://github.com/reactjs/react-magic/issues/5#issuecomment-37983380

**Comment by Daniel15** [comment]
That's an old comment :) The HTML to JSX converter used to  be in the React
repo, but it moved to the react-magic one a while back.
