### ISSUE TITLE
Escaped equal in server side id rendering

### ISSUE THREAD

**Issue by teosz** [facebook/react#5913]
Hello,
I've got some strange problem with server side rendering, React add a slash before `=` and make checksum invalid:
```
 (client) bjtkxdeayo.0.0.0.0.$/=10">
 (server) bjtkxdeayo.0.0.0.0.$=10">
```

![errors](https://cloud.githubusercontent.com/assets/4419636/12550143/769cb2ca-c36a-11e5-9e5e-dde5a7cbd891.png)

**Comment by jimfb** [comment]
Can you provide a simple usage example / component that creates this problem?

**Comment by romaingweb** [comment]
Hi,
We seem to have the same problem. On our side, it started to raise this warning as soon as we decorated some components with CSSModules from [react-css-modules](https://github.com/gajus/react-css-modules).

**Comment by teosz** [comment]
Hi, 
I couldn't separate the error in other repo/example because i can't identify the source of problem 
@romaingweb we don't use react-css-modules, our problem came after using implementing server side authorization. 
Anyway in the last time i didn't saw the error.

**Comment by jimfb** [comment]
I'm reasonably sure this is fixed in master/future, since our react-dataid is now numeric for SSR.
