### ISSUE TITLE
SyntheticEvents are leaking dom nodes

### ISSUE THREAD

**Issue by guykr-stratoscale** [facebook/react#5921]
`SyntheticEvent.target` is not nulled when event is put into the events instance pool for reuse.
When unmounting the instance pool of events remains and the nodes pointed by the target property become detached nodes.

Here is an example:
https://react.jsbin.com/ziwepazewu

Click the header a few times to generate events. After 5 seconds the component will be removed via `unmountComponentAtNode`. Open chrome dev tools, take a heap snapshot and notice the detached nodes held by the SyntheticEvents.

Screenshot attached.
![image](https://cloud.githubusercontent.com/assets/6630673/12579653/3db323f4-c432-11e5-806a-066b9cc22f16.png)

**Comment by guykr-stratoscale** [comment]
Seems like be0551d01e1e1de2fa0899703c3c217c9123dc21 is a fix for this issue. If this is the case please close this.

**Comment by zpao** [comment]
Yes, that will fix this. I've marked it for 0.14.x so we'll grab that if we do another release before 15.

**Comment by guykr-stratoscale** [comment]
Please do a 0.14.x release :pray:
