### ISSUE TITLE
save flag someplace if checksum was invalid

### ISSUE THREAD

**Issue by catmando** [facebook/react#5924]
we have tests that insure that prerendering = client rendering.

Right now its a real cludge - we override console.warn, and watch to see if any checksum warnings are output.

Instead how about adding data-checksum_invalid to the outer element?

**Comment by gaearon** [comment]
We don’t have checksum warning checks now, but we still use `console.error` to notify about the differences.

We might add a way to hook into the warning system later. Let’s track it in https://github.com/facebook/react/issues/4302.
