### ISSUE TITLE
Bug: <input> value never updated in unit test

### ISSUE THREAD

**Issue by japgolly** [facebook/react#5934]
Say I have a component that renders an `<input type="text" value="whatever">`. If I try to unit test it using `ReactTestUtils.Simulate.change`, the component gets the updated value but then the `value` attribute in the DOM doesn't get the update.

See https://jsfiddle.net/c1ht6zwm/3/

**Comment by Josh-a-e** [comment]
That's expected behaviour, read the controlled components docs for a better explanation https://facebook.github.io/react/docs/forms.html

**Comment by Josh-a-e** [comment]
Apologies, I thought you meant the value was hard coded rather than inserted via state

**Comment by japgolly** [comment]
Cool, I just re-read *Controlled Components* and was about to say "aren't I doing the same thing?" :smile:

**Comment by jimfb** [comment]
React does not guarantee to change the markup.  As long as the rendered value within the input box is correct (ie. what the user sees is correct), React is doing its job.  The markup is irrelevant.

FWIW, this behavior will probably be closer to what you want when https://github.com/facebook/react/pull/5680 merges.

**Comment by zpao** [comment]
To clarify what @jimfb is saying - When React updates `value`, it currently does so via the property, which doesn't affect `outerHTML`. A super simplified example to show what React currently does: https://jsfiddle.net/1z2fey46/

**Comment by japgolly** [comment]
Oh wow, I didn't know there was a difference. Rather, I thought `outerHTML` was a dynamic reflection of the tag and its (non-event) properties - I'm surprised to learn that it's not. Thanks @jimfb & @zpao.
