### ISSUE TITLE
eslint related error

### ISSUE THREAD

**Issue by altanai** [facebook/react#5936]
on npm install
```
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'eslint-plugin-react-internal' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'react-build'

```

I have installed **eslint** and **eslint-plugin-react** both locally as well globally yet the error persists

**Comment by jimfb** [comment]
I'm unable to reproduce.  I did an `npm install` inside the react repository, it went fine.  I also did an `npm install react react-dom eslint eslint-plugin-react` and that also went fine.  What exactly are you doing when you get this error?

**Comment by zpao** [comment]
This usually happens on old versions of npm (eg under 2). You'll not the package in question is actually eslint-plugin-react-internal, which is installed via a file reference in package.json, which needs npm 2.

If you're looking to contribute to React and need to build, then you'll need to be using Node 4 and npm 2.
