### ISSUE TITLE
Node value setter called too many times

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5944]
For background, see: https://github.com/facebook/react/pull/1510/files#r44678597

Good first bug?

**Comment by jimfb** [comment]
@zpao @spicyj good first bug?

**Comment by spicyj** [comment]
Probably not, unless you already know what the cause and solution is.

**Comment by davidvgalbraith** [comment]
I thought it looked like a good first bug: https://github.com/facebook/react/pull/5953.
