### ISSUE TITLE
DOCS: Make Stateless Functions more prominent

### ISSUE THREAD

**Issue by Download** [facebook/react#5949]
All the way at the very bottom of the [Reusable Components](http://facebook.github.io/react/docs/reusable-components.html#stateless-functions) page there is a section on Stateless Functions. Below that section is a note:

> In an ideal world, most of your components would be stateless functions because in the future we’ll also be able to make performance optimizations specific to these components by avoiding unnecessary checks and memory allocations. **This is the recommended pattern, when possible.**

*(emphasis mine)*

If this is indeed the recommended pattern, it should be made much, much more prominent. For example by using it in the `A Simple Component` section on the homepage. That now has this `HelloMessage` component as the visitor's very first example of a React component:

```js
var HelloMessage = React.createClass({
  render: function() {
    return <div>Hello {this.props.name}</div>;
  }
});
```

This function qualifies for being a stateless function component:

```js
function HelloMessage(props) {
    return <div>Hello {props.name}</div>;
}
```

As a bonus, it's now much, much simpler and postpones introduction of `React.createClass` to later, when the examples go more in-depth.

Let's start teaching people the right patterns.

**Comment by jimfb** [comment]
The problem with updating the examples on the home page is that the second two examples are stateful.  We want the three homepage examples to feel like a simple+natural progression.  We need to introduce stateful syntax for the second two examples, so there is no point in using a different syntax for the first example (it would just make it harder to follow the progression).

Personally, I would be open to having http://facebook.github.io/react/docs/transferring-props.html and http://facebook.github.io/react/tips/communicate-between-components.html upgraded to use stateless functions.

**Comment by Download** [comment]
Actually, I think making the very first example as simple as it can be would be a good thing. Saying it needs to be more complex than necessary because that complexity is needed later seems strange to me. You should add the complexity bit by bit.

> The problem with updating the examples on the home page is that the second two examples are stateful. 

Fix that then. There is a whole class of components that you can build without state. In my mind, the reasonable thing to do would be:

1. Hello World example (Stateless function, does not actually use props). Here you can discuss JSX syntax in general
2. Expand on Hello World by introducing `props.name` (what is now first example). Show how props are passed from JSX to the component
3. Discuss advantages of stateless components and how it's the recommended way
4. Talk about stateful components and introduce `React.createClass` / ES6 `class` syntax for building stateful components. Basically only here would you introduce what is now the first example by making some `Counter` component
5. Optionally, reference externalizing the state to e.g. Flux stores at this point

**Comment by Download** [comment]
If you're open to this, I could walk the walk by preparing a PR... Let me know.

**Comment by jimfb** [comment]
I assume your comments (1-5, etc) above are referring primarily to the homepage.  Keep in mind that the homepage is a sales pitch (it's what users see when deciding which framework to use).  Ease of use/understanding is paramount at that stage.  When users are ready to learn about best practices, they can read the full docs and learn about all the various features and design patterns.

For this reason, I don't want to introduce two different component-definition styles on the homepage.  Two concepts is harder to understand than one.

If you wanted to submit a PR for the two pages I mentioned, that seems like the most appropriate place to surface stateless functions more prominently.

**Comment by Download** [comment]
Yes they were referring to the homepage.

>  Keep in mind that the homepage is a sales pitch [..] Two concepts is harder to understand than one.

Gotcha.

**Comment by mxstbr** [comment]
Pretty sure we can close this

**Comment by jimfb** [comment]
Yep, thanks!
