### ISSUE TITLE
Controlled Inputs can update out of order, causing cursor jump

### ISSUE THREAD

**Issue by jquense** [facebook/react#5952]
Here is a subtle change introduced when the DOMInput component was switched into the current lighter weight wrappers.

In order to ensure that things like: #1698 don't happen. The inputs defer an update until all updates have been flushed when controlled. This gives the incoming props a chance to make it to the component before it inadvertently resets the value to the now, last, `props.value`.

Essentially the old `value` is set on the DOM node before the new `value` has a chance to be pushed to the input props, which causes the cursor to jump to the end.

This was originally seen and addressed in: https://github.com/facebook/react/blob/0.13-stable/src/browser/ui/dom/components/ReactDOMInput.js#L30-L35

However the recent changes removed the `forceUpdate()` and call `ReactDOMInput.updateWrapper` directly. **The difference is the `forceUpdate` enqueues itself in the update queue whereas updateWrapper does not**. Which leads to cases where the input actually updates _before_ its parents have finished updating.

Related issue to #5386, however in this cause nothing is actually async.

This is relevant because [user-land implementations of uncontrolled components](https://github.com/jquense/uncontrollable) create situations where a parent component to the input is _also_ deferring an update with `.asap()`.

I have tried a bit to put together a PR to address this but I don't know that there is an easy fix as long as the DOMComponent is not itself using something like `forceUpdate`.
### Expected:

`inputNode.value` to not be set at all after it was manually set to `'bar'`
### Actual:

`inputNode.value` is set from: `'bar'` to `'foo'` and then from  `'foo'` to `'bar'`

``` js
var Wrapper = React.createClass({
  eventuallyUpdate(e) {
    this._value = e.target.value;

    // not actually "async" in the true sense of it.
    ReactUpdates.asap(function() {
      this.forceUpdate();
    }, this);
  },

  render() {
    return (
      <input
        ref="input"
        type="text"
        value={this._value || 'foo'}
        onChange={this.eventuallyUpdate}
      />
    );
  },
});

var inst = ReactTestUtils.renderIntoDocument(<Wrapper />);
var inputNode = ReactDOM.findDOMNode(inst.refs.input);
var setCount = 0;

inputNode.value = 'bar';

var desc = Object.getOwnPropertyDescriptor(
  inputNode.constructor.prototype,
  'value'
);

Object.defineProperty(inputNode, 'value', {
  get: function() {
    return desc.get.call(this);
  },
  set: function(val) {
    setCount++;
    desc.set.call(this, val);
  },
});

ReactTestUtils.Simulate.change(input, {
  target: { value: 'bar' },
});

expect(setCount).toBe(0); // will be 2
```

**Comment by jimfb** [comment]
@spicyj @syranide

**Comment by jquense** [comment]
I know this is a fairly obscure seeming bug (if one could call it a bug) but it's actually affecting a lot of code we are running, and a lot of libraries I/we provide, since we use controllable helpers to encapsulate that behavior for lots of components.

Using context to wrap up a bunch of Field (read: inputs) into a big Form component is a really common use case where the parent (Form) `value` props _needs_ to be settled before the children inputs (Fields) update their values. Right now any uncontrolled parent elements exhibit this sort of bug. 

I also realize that using `ReactUpdates.asap` is bad form since its an internal API, but its impossible to correctly implement controlled/uncontrolled components without it, and would love to see some form of `unstable_asap` as a larger aside.

**Comment by spicyj** [comment]
Sorry, I'm having trouble understanding the issue here. ReactUpdates.asap is not public API, and if you were to use setTimeout or requestAnimationFrame then I would expect the behavior you describe here as incorrect. What are you using ReactUpdates.asap for in this case?

**Comment by jquense** [comment]
The reason the test case is using `ReactUpdates.asap` is mostly to demonstrate that the updates seem out of order (to me) even when they occur in the same tick, and illustrates something that worked in `0.13` but doesn't in `0.14`. #5386 covers the case with a setTimout/RAF, but per discussion there, that problem seems intractable.

The _reason_ why we are using it in [actual modules](https://github.com/jquense/uncontrollable/blob/v2.0.0/src/uncontrollable.js#L132) is the same as why ReactDOMInput uses it, to implement correctly a controlled/uncontrolled API for components.

A practical use case is something like:

```js
// Form is implementing `value` and `defaultValue` in the same way 
// the <input> does (using `.asap()`)
// however unlike inputs the Form component has to call `forceUpdate()` in the 
// asap callback, causing its update of `value` to occur after the inputs
<Form defaultValue={{ name: 'john' }}>
  <div>
    <Field for='name'>
      {/* Field controls the child input's value (injects onChange and value), 
        * is in turn passed the Form value via context 
        */}
      <input type='text' />
    </Field>
  </div>
</Form>
```

It is of course entirely possible that I am expecting something to work that was never intended to work, and that's fine, but I did want to say that we were at least inadvertently relying on that behavior and that behavior changed. Before we figure out how to adjust a bunch of code (such is the potential cost of using private APIs) I'd thought I'd make sure that this behavior change was intended/acceptable.

**Comment by jquense** [comment]
For clarity, this is a problem, because we use the internal `ReactUpdates.asap` (and ultimate cause of this "bug") to avoid this bug: #5990

**Comment by chrisdavies** [comment]
Hm. I'm seeing this behavior, and I don't think I'm doing any sort of async update.

Running `react 15.0.0` and Redux `3.0.5`, I have an input like so:

```jsx
    <input
        name="name"
        value={pricePoint.name} />
```

And the wrapping/parent form has an onChange event like so:

```js
onChange={({target}) => setField(target.name, target.value, target.checked)}
```

Might not be the most elegant solution, but it works fine in react `0.14.5`. In `15.0.0`, the caret jumps to the end of the input every time I type.

My `setField` reducer does something like this (with some logic to do special things for certain fields):

```js
return { ...state, [name]: value}
```

I can look into putting a repro out on jsFiddle, if you like.

**Comment by jimfb** [comment]
@chrisdavies I think you're running into a different issue, try upgrading to React v15.0.1

**Comment by chrisdavies** [comment]
Yup. That was it. Thanks!

**Comment by gaearon** [comment]
Doesn’t apply to 16.
