### ISSUE TITLE
Add new <use> without namespace

### ISSUE THREAD

**Issue by savelichalex** [facebook/react#5954]
I have an List of elements, when I push new elements they added without namespace. Any ideas?

**Comment by savelichalex** [comment]
I see that <use> not support yet.. It's a pity.. But first time they render correct

**Comment by jimfb** [comment]
Does it work in this fiddle: http://jsfiddle.net/9kungxn4/ ?

**Comment by savelichalex** [comment]
Yeah, this work fine: http://jsfiddle.net/9kungxn4/2/. What does this mean?

**Comment by savelichalex** [comment]
Ok, I check that is 0.15-alpha.1.Thanks for your time
