### ISSUE TITLE
Enhancement: Build in a way to generate a function that sets some state variable

### ISSUE THREAD

**Issue by moodysalem** [facebook/react#5958]
I created [this mixin](https://github.com/moodysalem/set-state-function-mixin) this morning to handle creating functions that just call setState if the component is mounted, but it would be nice if it was just built in to the React component since I think it's a pretty common pattern to handle UI events by just setting some state variable.

**Comment by jimfb** [comment]
The whole point of the warning is to be useful, and having a mixin that automatically calls `isMounted` is the opposite of what we would recommend.

For more details: https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

**Comment by moodysalem** [comment]
@jimfb 
That's a good read, thanks. With or without isMounted, I still find this function useful.

**Comment by jimfb** [comment]
Without `isMounted`, you could just write 

`React.DOM.button({ onClick: () => this.setState({modalOpen: true})})` (without mixin)
`React.DOM.button({ onClick: this.setStateFunction('modalOpen', true) }),` (with mixin)

The version without the mixin is syntactically shorter, and more readable (doesn't depend on the details of a mixin).  Therefore, I still wouldn't recommend it.  But if you find it useful, more power to you!

**Comment by moodysalem** [comment]
Fair enough, I don't use a transpiler so I didn't think of what it looks with lambda functions.
