### ISSUE TITLE
jquery-bootstrap example uses `handleHidden` which does not exist

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5959]
Introduced in: https://github.com/facebook/react/commit/7f8b2885d9f9feb396896f7d9d6086ac7731cf36

**Comment by MarkMurphy** [comment]
@TheBlasfem you beat me to it haha! I noticed though that your fix doesn't address the fact that no event listener was added for the 'hidden' event to begin with. Also, the event name is actually `hidden.bs.modal`. I've made those changes in mine in addition to responding to the same `onHidden` prop you also implemented.

**Comment by TheBlasfem** [comment]
nice catch @MarkMurphy, thanks for notice me, we can continue with your solution
