### ISSUE TITLE
should validate attributes by element

### ISSUE THREAD

**Issue by yiminghe** [facebook/react#5963]
We mistakenly used `required` attribute to style `label` element, such as

```html
<label required>
<label>

label[required] {
  color: red;
}
```

Soon we found that `label`'s attribute can not be removed in 0.14.x:

```js
ReactDOM.render(<label required>, container);
// update immediately
ReactDOM.render(<label>, container);
```

After running the above code, The `required` attribute is still on `label` element. 

Then I realize `required` is not an attribute of `label` by [standard](https://www.w3.org/TR/html5/forms.html#the-label-element), just an attribute of some other elements(like `input`, etc..), so I think `required` should not be allowed to render at component mount phase like other arbitrary names(such as xyz), else it will cause people confusion.

And I notice that 0.15.x solves this problem by a flag(`MUST_USE_PROPERTY`), so `required`  is rendered at component mount and will be removed correctly, but is inconsistent with other attributes(select/checked) which is not rendered at all.

So should react validate attributes by element like `validateDOMNesting`?

**Comment by jimfb** [comment]
I don't think this is solved in 0.15.

We have a whitelist of attributes, but don't check to ensure they're used on the corresponding tags.  With regards to validation, are probably headed in the opposite direction with issues like #140.

However, this may be a reason to set the attribute even if we are already setting the property.

**Comment by yiminghe** [comment]
I have tested it... 

`required` will removed by removeAttribute in 0.15.x, but in 0.14.x it will run `node.required=undefined` to keep required.

**Comment by jimfb** [comment]
Ah, you are correct.  FWIW, we also don't specify the other attributes such as `checked`/`selected` in 0.15.

**Comment by yiminghe** [comment]
My mistake, I have edited...

checked/selected is `MUST_USE_PROPERTY `, so they are not rendered at all (use node.xx to set)

**Comment by jimfb** [comment]
I'm going to close this out in favor of https://github.com/facebook/react/issues/5966, since that's the only actionable part of this issue, as far as I can tell.
