### ISSUE TITLE
<button onClick={...} disabled={true}> not firing onClick is undocumented.

### ISSUE THREAD

**Issue by Havvy** [facebook/react#5967]
Looking at https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/__tests__/ReactDOMButton-test.js - there are tests stating that `onClick` doesn't get fired if you click a button that is disabled. This doesn't seem to be shown anywhere in the documentation.

Slightly tangental, if there's an `onClick` on a parent element of a `<button disabled={true}>`, and somebody clicks the button, is the `onClick` fired for the parent element?

**Comment by jenriquejr** [comment]
probably not included because this part of the html specification
see https://www.w3.org/TR/2011/WD-html5-20110525/association-of-controls-and-forms.html#dom-fe-disabled

**Comment by Havvy** [comment]
Ah, okay.
