### ISSUE TITLE
UIExplorer crash

### ISSUE THREAD

**Issue by chenqizheng** [facebook/react#5969]
after execute 
 "./gradlew :Examples:UIExplorer:android:app:installDebug"
open UIExplorer app is crash,
crash log ⬇️
[react.txt](https://github.com/facebook/react/files/114932/react.txt)

**Comment by jimfb** [comment]
This repository is for React core, not react native.  The react-native repository is at https://github.com/facebook/react-native, but if it is failing out of the box, my guess is that it's an environment issue on your end and not related to the react-native codebase.
