### ISSUE TITLE
Include SRI hashes for fb.me links on download page

### ISSUE THREAD

**Issue by zpao** [facebook/react#5970]
We'll need to do a little bit more than just hard code these since we'll actually want to generate these at release time. But we could at the very least manually generate those hashes now and do what we need in the docs to display it.

SRI: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by marumari** [comment]
This would be absolutely fantastic!  Making things as simple as a copy-and-paste would go a long ways towards increasing SRI's adoption.

**Comment by hillbrad** [comment]
What happened?  They're gone again.  :(

**Comment by jimfb** [comment]
@hillbrad https://github.com/facebook/react/pull/6313

**Comment by marumari** [comment]
Oh weird, I could have sworn that fb.me was setting the CORS headers properly at one point.  :(

**Comment by hillbrad** [comment]
I will dig into it.  The final resource sets the right headers but the 301
from fb.me is not.  :(
