### ISSUE TITLE
DOCS: When I run the demo code,I get a false which should be true in the docs

### ISSUE THREAD

**Issue by liuyutao** [facebook/react#5971]
https://facebook.github.io/react/docs/glossary.html

In this doc,
this code ,

var componentA = ReactDOM.render(<MyComponent />, document.getElementById('example'));
var componentB = ReactDOM.render(<MyComponent />, document.getElementById('example'));
componentA === componentB; // true

When I test it, it comes with a "false"

can somebody help me?

**Comment by jimfb** [comment]
Comes up with the word "true" for me: http://jsfiddle.net/mgzqbedr/

Do you have a jsfiddle that demonstrates it coming up as false?
