### ISSUE TITLE
Touch events on Android 4.1

### ISSUE THREAD

**Issue by tonygriv** [facebook/react#5972]
Hello! 

Touch events on Android 4.1 don't working. We are using react 0.14.2. According to the issue https://github.com/facebook/react/pull/5157, it was fixed in 0.14.1, but it's still not working :( Any ideas?

**Comment by jimfb** [comment]
Can you provide two jsfiddles (one showing that it doesn't work with React 0.14.1+ and another showing that touch events do work without React).  I'll try to dig up a 4.1 phone to test on our end.

**Comment by tonygriv** [comment]
Sorry, we fucked up. Everything is working :)
