### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by afgarcia86** [facebook/react#5975]
I have a class that is trying to do a get request in the componentDidMount function, however if I initially load a page with this component in it I get the following error. `$ is not defined`. I followed the example from xxx I just changed it over to ES6, perhaps I am using something improperly?

`
class NativeApp extends React.Component {

  state = {
    banners : {}
  }

  loadBanners() {
    this.serverRequest = $.get('/api/banners', function (res) {
      this.setState(res)
    }.bind(this))
  }

  componentDidMount() {
    this.loadBanners()
  }

  render() {
    return (
      <DefaultLayout title={this.props.title} loggedIn={this.props.loggedIn} logOut={this.props.logOut}>
        <button onClick={this.loadBanners} className="btn btn-primary">Manually Load Banners WHY!!!</button>
      </DefaultLayout>
    )
  }
}

export default NativeApp
`

**Comment by jimfb** [comment]
Add `<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>` in your header.

**Comment by afgarcia86** [comment]
Ahh... I should have known it was that simple. Sorry for wasting your time.
