### ISSUE TITLE
findDom and AUDIO tag doesn't work

### ISSUE THREAD

**Issue by nicolabortignon** [facebook/react#5981]
Assuming I have an audio tag correctly playing an audio file.
The currentTime is 30 (seconds).
I run the following code.
```

    const audioElement = ReactDOM.findDOMNode(this.refs.audio);
    try {
      audioElement.currentTime = 0;
      console.log(audioElement.currentTime);
    } catch (evt) {
      console.error('error:' + evt);
    }
```

the output in console is 30.

If i replace the first line with 
`const audioElement =  document.getElementById('audio');`
everything works as expected.

At the beginning I thought there was a deep copy issue, but that wouldn't explain the console.log inside the try.

**Comment by jimfb** [comment]
`refs` != `id`.

I suspect user error.  If you can provide a simple jsfiddle that demonstrates the issue, we can investigate further.

**Comment by zpao** [comment]
> `audioElement.currenTime = 0;`

Is it safe to assume that this was just was a typo here but not what your code actually looks like? (I'm assuming so since you said it works fine with `findElementById`)

**Comment by nicolabortignon** [comment]
the audio tag:

` <audio id="audio" autoPlay src={something} ref="audio"></audio>`
       
@zpao, correct indeed , I rewrote the code instead of copying / pasting. I updated the main post.

**Comment by jenriquejr** [comment]
@nicolabortignon you should not need to use `findDOMNode` when the ref is not a react component.
it should work fine either way, see this example https://jsfiddle.net/wycoauho/1/ and open the browser console to see the log result.

**Comment by jimfb** [comment]
@nicolabortignon Are you working on a fiddle to demonstrate this issue?

**Comment by nicolabortignon** [comment]
So, I created a Fiddle myself, and it did work. So now I'm trying to
understand what is going on in my current codebase that cose the problem.

I'd assume is safe to mark this as 'Not able to reproduce'
