### ISSUE TITLE
Chrome Dev Tools Warning: ReactDOMComponent: Do not access .props of a DOM node

### ISSUE THREAD

**Issue by psumstr** [facebook/react#5984]
I've created a component that uses the ref attribute so I can read the width and height of the DOM node. It looks like this:

```javascript
import styles from './MakeWrapper.css';

import React , { Component } from 'react';
import MakeHeader from '../MakeHeader/MakeHeader';
import MakeBarChart from '../MakeBarChart/MakeBarChart';

export default class MakeWrapper extends Component {
    render() {
        return <div className={styles.root} ref="makeWrapper">
            <MakeHeader />
            <MakeBarChart />
        </div>
    }
    resize(width, height, offsetTop, offsetLeft) {
        this.props.onResizeMakeWrapper(width, height, offsetTop, offsetLeft);
    }
}
```

Everything looks good, but if I open the Chrome Dev Tools and look at the properties of the div element, I get the following warning in the console:

> Warning: ReactDOMComponent: Do not access .props of a DOM node; instead, recreate the props as render did originally or read the DOM properties/attributes directly from this node (e.g., this.refs.box.className). This DOM node was rendered by `MakeWrapper`.

The message is actually shown twice in the console. I also noticed that two different `prop` properties exists, which might be causing the error to show twice when Chrome is looping through the DOM properties.

Is there something wrong with my code, or is this a side effect of using Chrome Dev tools?
![chrome dev tools](https://cloud.githubusercontent.com/assets/5589281/12847946/bd3bbd8e-cbe4-11e5-93f6-45966992aae3.png)

**Comment by jenriquejr** [comment]
@psumstr I dont think the component you provided above throws this warning by itself, this could be something happening within the child components, if you can add more context to this it would be great.

**Comment by psumstr** [comment]
@jenriquejr I created an example in JS Bin and it's reproduced there:
https://jsbin.com/nohovapohi/edit?html,js,console,output

Just run the JS, inspect element of the comment box div in chrome and click on the Properties tab and expand div.commentBox. You'll see the messages in the console.

**Comment by zpao** [comment]
Yes, this is just a side-effect of inspecting the DOM node. For 0.14 in dev mode we have a getter on DOM nodes that are refs to support the previous pattern where those refs were React components. The Chrome devtools are reading every property which results in that warning. There's nothing to do about it right now but it will be gone in the next major release.

**Comment by jenriquejr** [comment]
good to know @zpao, is there an open issue we use for reference here?

**Comment by jimfb** [comment]
@jenriquejr There is no open issue because it is already fixed in master: http://jsfiddle.net/zopwnwtc/

**Comment by jenriquejr** [comment]
thanks @zpao
