### ISSUE TITLE
pull request for htmltojsx

### ISSUE THREAD

**Issue by solugebefola** [facebook/react#5985]
Hi there,

I put in a pull request for htmltojsx in react-magic  to fix the improper-rendering-of-brackets issue a few days ago.  I was just wondering what the typical timeline for reviewing those was?

Cheers

**Comment by jimfb** [comment]
For reference, solugebefola is talking about https://github.com/reactjs/react-magic/pull/45

If you want to poke someone about a diff, creating a new issue in a different repository is not the correct solution.  A more appropriate technique would be to add a comment to the diff in question (like: "would love to get this merged, can I get a code review on this?  cc @Daniel15"), so people have context.  When leaving such a comment, Cc'ing the people who maintain the repository will help bring it to their attention, in case they missed it (you can tell who those people are by looking at the commit history of the repository).

**Comment by solugebefola** [comment]
Thanks for the info, I'm still pretty new at this.
