### ISSUE TITLE
How can I visit the official site that writing by other language (default English)?

### ISSUE THREAD

**Issue by leftjs** [facebook/react#5991]
visit the link [`getting-started`](https://facebook.github.io/react/docs/getting-started.html), it's English page, how to read this page that writing by other language.

**Comment by jimfb** [comment]
https://facebook.github.io/react/docs/getting-started-zh-CN.html

Duplicate of https://github.com/facebook/react/issues/4614

**Comment by leftjs** [comment]
thanks, Jim
