### ISSUE TITLE
License and offline use

### ISSUE THREAD

**Issue by xdvarpunen** [facebook/react#5993]
Hi!

Can React be utilized in offline commercial product for free? What needs to be done? The License file was too cryptic to understand. 

-XDVarpunen

**Comment by jimfb** [comment]
As far as software licensing goes, our license super simple and clear.

I am not a lawyer, and as such, can not give legal advice about the specifics of your situation.  My recommendation is that you check with your organization's legal department; they should be able to give you a clear answer.

But in general, yes, you can utilize React in offline commercial products for free, as long as you don't remove the copyright notice from the React code, as per the conditions mentioned in the license file.
