### ISSUE TITLE
event.persist is not present when running tests.

### ISSUE THREAD

**Issue by ankeetmaini** [facebook/react#5998]
`TestUtils.Simulate.scroll` doesn't seem to give an event with `persist` function on it. As a result when the event handler is debounced/throttled the `target`/`srcElement` becomes null when the actual handler is called.

**Comment by jimfb** [comment]
@ankeetmaini Can you create a unit test which demonstrates the problem?

**Comment by jimfb** [comment]
Two weeks with no response/repro, unable to reproduce myself.

```
  it('scroll event should have persist', function() {
    var evnt = null;
    var element = <textarea onScroll={(e)=>{e.persist(); evnt = e;}} />;
    var node = ReactTestUtils.renderIntoDocument(element);
    ReactTestUtils.Simulate.scroll(node);
    expect(evnt.target).toBeTruthy();
  });
```
