### ISSUE TITLE
React.cloneElement onClick does not work?

### ISSUE THREAD

**Issue by philipgiuliani** [facebook/react#6006]
Hi. Im trying to add an onClick handler to an already existing element.

Example:
```jsx
render() {
    let element = <ImageCardView title="Test" subtitle="Subtitle" />;
    return React.cloneElement(element, { onClick: function() { console.log("TEST"); }});
}

// Result: Nothing happens when i click on the element
```

When setting it directly in the `<ImageCardView />` it works.

**Comment by philipgiuliani** [comment]
I found out that i cannot set a `onClick` handler directly to the component. Inside of the component i have to do something like:

```jsx
// ImageCardView
render() {
  return <div onClick={this.props.onClick}>Test</div>
} 
```

**Comment by ccorcos** [comment]
Why is this closed?

**Comment by philipgiuliani** [comment]
Because its not a bug. You have to do for example:

```javascript
class MyComponent extends React.Component {
  render() {
    return <button onClick={this.props.onClick}>Test</button>;
  }
}

class Wrapper extends React.Component {
  doSomething() {
    console.log("clicked :)");
  } 
  
  render() {
    return <MyComponent onClick={this.doSomething} />
  }
}
```

**Comment by exapsy** [comment]
Why is it not a bug?
Your reply requested a different solution. Which might not even fit in others cases. There wasn't any discussion over whether this is a bug or not. React.cloneElement purpose is to add additional properties, and onClick is one of them. So, probably it should work I think.

**Comment by jtswartz** [comment]
> Why is it not a bug?
> Your reply just requested a different solution. There wasn't any discussion over why the previous one was not working though. :)

Looks like OP's original problem wasn't understood by himself 😝 The `onClick` handler lives on a child of `ImageCardView` rather than itself.

**Comment by liubin915249126** [comment]
> I found out that i cannot set a `onClick` handler directly to the component. Inside of the component i have to do something like:
> 
> ```js-jsx
> // ImageCardView
> render() {
>   return <div onClick={this.props.onClick}>Test</div>
> } 
> ```



> I found out that i cannot set a `onClick` handler directly to the component. Inside of the component i have to do something like:
> 
> ```js-jsx
> // ImageCardView
> render() {
>   return <div onClick={this.props.onClick}>Test</div>
> } 
> ```

this resolve my problem

**Comment by abriginets** [comment]
Wow I'm so surprised this issue existed for so long without a clear explanation. Let me fill this gap for those who are going to search for it in the future. **TLDR, it invokes props directly on your component, not the JSX you render**

Let's say we have a parent component:

```jsx
export function ParentComponent(props) {
  return (
    <Wrapper>
      {React.cloneElement(
        props.children,
        {
           onClick: () => console.log('click'),
        },
      )}
    </Wrapper>
  );
}
```
And a child component:
```jsx
export function ChildComponent(props) {
  return <button />;
}
```
And then we render it as following:
```jsx
return (
  <ParentComponent>
    <ChildComponent />
  </ParentComponent>
);
```
What's happening with child component is that `React.cloneElement` only adds `onClick` function to the list of props you are passing down to child prop. It does not invoke this prop in the JSX you declare. The solution here is as simple as it can be - just add `onClick` handler to the component you render:
```jsx
export function ChildComponent(props) {
  return <button onClick={props.onClick} />;
}
```
It's just the way our brain is messing with us and React have nothing to do with not handling clicks on your component :)

**Comment by audn** [comment]
> just add `onClick` handler to the component you render:

What's the purpose of cloning the element in the first place if you're going to add the `onClick` directly on the child?
