### ISSUE TITLE
link expired

### ISSUE THREAD

**Issue by js08** [facebook/react#6010]
Hi,

Link got expired can you update it

**http://join.reactiflux.com**

**Comment by zpao** [comment]
Seems to be working for me but cc @benigeri in case.

(closing because not a react bug)

**Comment by js08** [comment]
providing a screenshot too

![screen shot 2016-02-09 at 7 14 56 pm](https://cloud.githubusercontent.com/assets/1699943/12936176/6f03eb0c-cf61-11e5-9442-29c11b55823d.png)

**Comment by aequasi** [comment]
Banned users are shown an expired link, FWIW
