### ISSUE TITLE
Closer control over reconciliation

### ISSUE THREAD

**Issue by ksmithbaylor** [facebook/react#6013]
I am running into a use case that doesn't seem to be supported by React. I am using redux and react-redux in this example, but the problem could potentially extend to any component that takes children.

I am trying to build a set of components that are independent of one another to the point that they can be included on the page in their own script tags. Each component will have a stateless component and a container that connects it to a redux store:

```
const Widget = ({ data, update }) => (
  <div>
    <input type="text" onChange={e => update(e.target.value)} />
    <p>The data is {data}</p>
  </div>
);

const WidgetContainer = connect(
  state => ({ data: state.data }),
  dispatch => ({
    update: val => dispatch({
      type: 'UPDATE',
      payload: val
    })
  })
)(Widget);
```

If there is a redux store present at a well-defined location, then I want to render the component this way:

```
<Provider store={window.MyApp.store}>
  <WidgetContainer />
</Provider>
```

If the store is not present, I want it to render this way:

```
<Widget />
```

I've written some helper functions to do this in a generic way. Initially, I render the component by itself to the target DOM node. When the store becomes present, it fires an event that my helper functions are listening for, which will render the container component wrapped in a `Provider` to the same target DOM node. This works great if there is no DOM state.

However, I want to allow the user to interact with my Widget before the store is present. For instance, in my `Widget` example, they should be able to enter some text in the `input` and that DOM state should persist when the `WidgetContainer` is rendered in its place.

Currently, this is not possible due to React's reconciliation algorithm. If two components have a different `type`, React will not attempt to reconcile their sub-trees (relevant code [here](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/shouldUpdateReactComponent.js#L39)). This causes the existing `input` node to be thrown away, along with anything the user may have typed. There is no way for me to tell React that I want my two components to be reconciled because I have the foreknowledge that they will generate an identical DOM structure.

What I want to know:

1. Is there a workaround for this issue?
2. If there isn't, is it a valid enough use case to consider adding a way to "force" React to reconcile two elements with different `type`s? One potential solution (which may be infeasible due to my unfamiliarity with the codebase) is to consider two elements with different `type`s but identical `key`s to be candidates for reconciliation.

**Comment by jimfb** [comment]
Seems to me that this constraint is too tight:

 > If the store is not present, I want it to render this way: `<Widget />`

Why wouldn't you just render: `<Provider store={window.MyApp.store}><WidgetContainer /></Provider>`, and have it behave "properly" (by your definition, render without a store) if `window.MyApp.store` is undefined/null.

**Comment by ksmithbaylor** [comment]
The way react-redux is implemented, `store` is a required prop of `Provider`, and `WidgetContainer` requires the `store` to be present in `context` since it was created with `connect`. So I could create a wrapper of some sort (which would be similar to what I have), but it would just bubble up the same problem since eventually they are going to be different components.

**Comment by jimfb** [comment]
And why can the store not be present at the first render?

**Comment by jimfb** [comment]
Can you pass in a fake store?  <Provider store={window.MyApp.store ? window.MyApp.store : {...}}><WidgetContainer /></Provider>

**Comment by ksmithbaylor** [comment]
I don't want the components to require the store to be present on the page before they can render, or throw errors if the store is included in a script tag later on the page. The reason for that is my company has chosen to use something called Adobe Experience Manager (AEM) to build these components, and it essentially allows content authors to drag-and-drop components onto pages. This means I can't guarantee what order anything appears.

I don't think AEM is a very good solution for building applications, but money has been spent, contracts have been signed, and it's not really up to me :)

My end goal is to build components that don't care whether or not a store is present, but will hook up automatically to the store once/if it is available.

**Comment by ksmithbaylor** [comment]
I think passing in a "fake" store initially might work. I'm trying to figure out how to get around the fact that `Provider` doesn't support swapping out the store on the fly. It looks like this is due to [changes](https://github.com/rackt/react-redux/releases/tag/v2.0.0) as of version 2.0.0 of react-redux, but it seems more related to hot-reloading than dynamically changing the "store" that a `Provider` is rendered with.

**Comment by ksmithbaylor** [comment]
After looking into it more, I can't figure out how I would implement this. Intuitively, it seems like it should be possible, but there's something missing that I can't put my finger on. Maybe @gaearon would be so kind as to take a look?

**Comment by jimfb** [comment]
You have a very constrained situation here :P.

 > `store` is a required prop of `Provider`, and `WidgetContainer` requires the `store` to be present in `context` since it was created with `connect`.

This is where I would look.  You could write your own Provider that provides a default if the store is undefined (a wrapper around the current Provider).  Or you could write a wrapper around `connect` that provides a store if one is unavailable, etc.

Forcing React to reconcile two elements with different types as the same element is probably not good.  It would be a confusing edge case for people.  Among other things, keys are automatically introduced by things like arrays, so we can't use "just keys" for reconciliation identity.

Anyway, I don't see anything actionable here.  I think the problem is coming in because you are using a bunch of different technologies, including redux and AEM and others, which are imposing semi-contradictory constraints and the challenge ahead of you is to figure out how to mitigate one of those constraints.  I don't think there is any actionable fix within the React core, so I'm going to close out the issue, but you guys can continue to have a discussion on this thread.

**Comment by gaearon** [comment]
>However, I want to allow the user to interact with my Widget before the store is present. For instance, in my Widget example, they should be able to enter some text in the input and that DOM state should persist when the WidgetContainer is rendered in its place.

Where would this state be stored when there is no associated store? In some ephemeral storage like component state? How would you reconcile the changes there with the real Redux store when it becomes available?

**Comment by ksmithbaylor** [comment]
I may come back and explore this more later. For now, I'm disabling inputs until the store is available. I think it might be possible to create a "save dom state" component that would store the state of the input and dispatch an action based on that state when the store (and its dispatch) is available. I'm pretty sure this is possible, and I think that was my issue. Thanks for the help, both of you!
