### ISSUE TITLE
Input re-render does not happen as expected when value is null

### ISSUE THREAD

**Issue by mrozbarry** [facebook/react#6014]
I'm building an app that has a series of single-character text inputs that auto advances as you input.  This app syncs data with our servers, and each input can only be one of a list of characters or null.  Here is a minimal demo to illustrate what's happening:

```
const CLEARED_VALUE = null

const Component = React.createComponent({
  getInitialState: function () {
    return {
      myInputValue: CLEARED_VALUE
    }
  },

  validateInput: function (value) {
    return value === '' || !!value.match(/[0-9]/g)
  },

  getStorableValue: function (value) {
    if (value === '') return CLEARED_VALUE
    return value
  },

  onChange: function (e) {
    console.log('onChange event fired')
    if (this.validateInput(e.target.value)) {
      console.log(' - onChange event accepted')
      this.setState({myInputValue: this.getStorableValue(e.target.value)})
    } else {
      console.log(' - onChange event rejected')
      e.preventDefault()
    }
  },

  render: function () {
    return (
      <input
        type='text'
        minLength={ 0 }
        maxLength={ 1 }
        value={ this.state.myInputValue }
        onChange={ this.onChange }
        />,
    )
  }
})
```

Notice when you clear the field then type anything (valid or not), onChange is not fired.  I suspect this has something to do with `value={ null }` is the culprit, since it tells React that the component isn't controlled so it doesn't know to re-render after input to correct from what's in state.  Changing `CLEARED_VALUE` to an empty string corrects this issue.

The issue here is I really don't want to have to convert nulls to empty strings, since data from the server will have nulls in it intentionally.  Obviously, there is nothing stopping me from doing:

```
getInputValue: function () {
  if (this.state.myInputValue === null) return ''
  return this.state.myInputValue
}

// ...

return (
  <input value={ this.getInputValue() } />
)
```

Is there any other workarounds or discussion about how we tell an input element that it is controlled?  Avoiding constant '' <-> null conversion would be the ideal situation here, since there are a lot of moving parts in the app that may have to do this a few times per render.

This is definitely an edge case, because if this were a multicharacter input that had validation, the second character would kick off validation and all would be good.

**Comment by mrozbarry** [comment]
Just to update, my title was misleading.  The issue here is that react doesn't know to re-render my input when the value changes from null to a character, so the ui stops reflecting what the state data has.

**Comment by jimfb** [comment]
Switching a component between controlled and uncontrolled is a bad idea, and is prohibited in React 0.15.  You will need to convert your nulls to empty strings.

**Comment by mrozbarry** [comment]
I think you missed my point.  What I'm implying is that the way we are setting inputs to controlled and uncontrolled is too implicit.  Why not have an override like `<input reactive={ true } />`?  I understand the `value={ null }` system that is currently in place, but doesn't that make the application less predictable when dealing data that includes nulls?

**Comment by jimfb** [comment]
The warning in 0.15 should help catch situations where you accidentally pass in null.  That's part of why it was added (user accidentally switching between controlled and uncontrolled components)

**Comment by mrozbarry** [comment]
Fair enough, thanks!
