### ISSUE TITLE
ResponderEventPlugin assumes touch events

### ISSUE THREAD

**Issue by bostonou** [facebook/react#6021]
Based on [this comment](https://github.com/facebook/react/issues/285#issuecomment-23959601), I implemented drag-n-drop in the browser with the [ResponderEventPlugin](https://github.com/facebook/react/blob/master/src/renderers/shared/event/eventPlugins/ResponderEventPlugin.js).

It worked like a charm, but upgrading to 14.x breaks the plugin. The problem is an assumption that the plugin is used with touch events. Besides the plugin referencing touch events throughout the code, [this is the breaking line](https://github.com/facebook/react/blob/master/src/renderers/shared/event/eventPlugins/ResponderEventPlugin.js#L499):

`ResponderTouchHistoryStore.recordTouchTrack(topLevelType, nativeEvent, nativeEventTarget);`

`recordTouchTrack` expects `nativeEvent` to have `changedTouches` and `touches` properties.

Enabling the `ResponderEventPlugin` also breaks the [ReactBrowserEventEmitter-test](https://github.com/facebook/react/blob/master/src/renderers/dom/client/__tests__/ReactBrowserEventEmitter-test.js)

[Multiple tests break](https://github.com/facebook/react/blob/master/src/renderers/dom/client/__tests__/ReactBrowserEventEmitter-test.js#L334-L385) by [adding the `ResponderEventPlugin`](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDefaultInjection.js#L61-L67):

```javascript
  ReactInjection.EventPluginHub.injectEventPluginsByName({
    ResponderEventPlugin: ResponderEventPlugin, //add this line
    SimpleEventPlugin: SimpleEventPlugin,
    EnterLeaveEventPlugin: EnterLeaveEventPlugin,
    ChangeEventPlugin: ChangeEventPlugin,
    SelectEventPlugin: SelectEventPlugin,
    BeforeInputEventPlugin: BeforeInputEventPlugin,
  });
```

Commenting out the call to `ResponderTouchHistoryStore.recordTouchTrack` appears to fix the plugin.

I'd like to continue using this plugin, but I'm concerned that it's no longer intended to be used for my use case. Is it expected that `ResponderEventPlugin` is only for react-native? Or is there some configuration/concept I'm missing?

I haven't tested all releases, but I believe this is the case for all 14.x.

**Comment by jimfb** [comment]
cc @spicyj because he wrote the original comment.

**Comment by spicyj** [comment]
I don't recall the history – it is a mix between this repo and RN. We don't currently use it in the browser but it is supposed to work.

Going to close this out since we don't really support it but if you send a PR (with unit tests) that makes it more compatible then we can probably take it. It looks like we set `.touchHistory` on the emitted events and we don't want to lose that (in RN at least) though.
