### ISSUE TITLE
Optional href property not removed on render, but set to empty

### ISSUE THREAD

**Issue by jkoudys** [facebook/react#6026]
While `href` is optional for all `<a>`s, it has very specific meaning when it's set but without a value (ie `<a href>`), vs `<a>`, where the former is a link back to the current uri, and the latter is a placeholder link. This can be especially irksome in a React app, because an unexpectedly set `href` can easily change what was meant to be an `onClick` into a full page reload.

Here's a fiddle demoing the bug here: https://jsfiddle.net/jkoudys/hpceoL01/
You can see what should be `<a>Bar</a>` rendered as `<a href>Bar</a>` instead.

```
class ATest extends React.Component {
  constructor() {
    super();
  	this.state = {changed: false};
  }
  componentDidMount() {
  	setTimeout(this.setState({changed: true}), 400);
  }
  render() {
    let options;
    if (this.state.changed) {
      options = [<a key="opt1">Bar</a>];
    } else {
      options = [<a key="opt1" href="/foo">Foo</a>];
    }
    return <div>{options}</div>;
  }
}
```

**Comment by jimfb** [comment]
Works in react-future / v15.  http://jsfiddle.net/1kdradt4/
