### ISSUE TITLE
Use mixed arrays with strings has warning

### ISSUE THREAD

**Issue by bfwg** [facebook/react#6038]
```js
var Hello = React.createClass({
    render: function() {
        return <div>{this.props.name}</div>;
    }
});
 
React.render(<Hello name={["This ", <strong>IS</strong>, " working!"]} />, document.body);
```
Has warning:
`Each child in an array should have a unique "key" prop. Check the render method of Hello. See http://fb.me/react-warning-keys for more information.`
Jsfiddle
http://jsfiddle.net/7s7dee6L/

**Comment by satya164** [comment]
I don't think it has anything to do with strings. You're passing a React element inside an array and rendering it as children. You should add a key to the element so that react can identify the element.

**Comment by bfwg** [comment]
So in this case I should just give it a key whatever I like? 
```js
React.render(<Hello name={["This ", <strong key={66666}>IS</strong>, " working!"]} />, document.body);
```
The warning goes away if I do this.

**Comment by satya164** [comment]
@bfwg Yes.

**Comment by bfwg** [comment]
Thank you.
