### ISSUE TITLE
dangerouslySetInnerHTML should warn if markup is invalid

### ISSUE THREAD

**Issue by jimfb** [facebook/react#6040]
`dangerouslySetInnerHTML` expects valid sanitized markup from a library like `marked`.  We may not be able to guarantee that the markup is sanitized, but we can spot many obvious errors which are an indication that markup is unsanitized.  Things like an `&` instead of an `&amp;` as per https://github.com/facebook/react/issues/5223#issuecomment-184373913.  This is also a good thing to warn about because we can catch subtle SSR markup checksum issues.  If the markup doesn't validate, we should warn.

The only tricky part here is that we don't want to have the markup validation library required in the production build.

**Comment by Sawtaytoes** [comment]
Is it that we should or should not be using `&` without `&amp;`?

**Comment by jimfb** [comment]
`&` is not legal.

**Comment by Sawtaytoes** [comment]
I noticed I have a single-quote converted in a title tag as well:

`What We&#x27;ve Been Up To`
vs what's in the client:
`What We've Been Up To`

Are these things I should be changing in my React code so the client lines up with what the server is rendering?

**Comment by jimfb** [comment]
@Sawtaytoes This issue is about tracking markup validation.  Usage questions should be directed at StackOverflow.

**Comment by syranide** [comment]
@jimfb HTML being the way it is `&` is legal, it may be bad practice, but it's only wrong if what follows is a valid entity (much like it's valid and even intentionally designed to allow omitting some closing tags, urgh). So someone being smart and optimizing the markup for size or the markup being manually written (it's handy to write just `&`) may not enjoy emitted warnings.

>  This is also a good thing to warn about because we can catch subtle SSR markup checksum issues.

I don't see how this would affect that? You will always get a SSR markup checksum error if the markup is different, invalid markup or not does not factor into it...?

**Comment by jimfb** [comment]
@syranide I just threw `<html><head><title>myhtml</title></head><body><a href="google.com?foo=bar&bar=noise">link</a></body></html>` into https://validator.w3.org/ and it gave me a validation error, despite the `&` not being followed by a valid entity.

It appears that it may be a function of doctype.  The validator's default doctype is "HTML 4.01 Transitional", for which the above code fails, but there are some doctypes that don't complain.

The mutation case I had in mind was markup that looks like this:
```<!DOCTYPE html><html><head><title>myhtml</title></head><body><div id="foo">&</div></body></html>```

Which Chrome automatically converts the `&` into `&amp;`.  I assumed chrome was mutating the markup to comply with validation rules (like it moves `<tr>` tags into `<tbody>` and does other markup cleanup).  But perhaps that cleanup is just the browser exercising its prerogative.

But you're right, the checksum is validated before the browser touches the markup, so that's a non-issue.

I think I'll close this out, since validating the HTML appears to be harder than I was initially thinking/expecting (in part due to doctypes validation differences) and the value-add is less than I was initially thinking/expecting.
