### ISSUE TITLE
Can react be more lenient with returning JSX expression in render() ?

### ISSUE THREAD

**Issue by jumpinjackie** [facebook/react#6042]
Here's a random hello react fiddle I plucked from google

    var Hello = React.createClass({
      render: function() {
        return <div>Hello {this.props.name}</div>;
      }
    });

    ReactDOM.render(
      <Hello name="World" />,
      document.getElementById('container')
    );

Reference: https://jsfiddle.net/reactjs/69z2wepo/

Now suppose for formatting/stylistic purposes, I want to format that inline return expression for like so:

    var Hello = React.createClass({
      render: function() {
        return 
            (<div>
                <p>Hello {this.props.name}</p>
             </div>);
      }
    });

    ReactDOM.render(
      <Hello name="World" />,
      document.getElementById('container')
    );

React now throws an invariant violation on `Hello.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object` all because I put the actual expression in a new line instead of the same line as the return statement.

Reference: https://jsfiddle.net/gdgoqva7/1/

Can react be made more lenient so that the 2nd example is allowed?

The react version referenced in both fiddles is v0.14.6

**Comment by zpao** [comment]
For that 2nd example you're actually returning undefined due to automatic semicolon insertion (good thing to look up if you're doing lots of JS). There's nothing React can do. If you put the opening paren on the same line as return you'll be ok. Going to close out since this is inactionable but feel free to follow up if you have any questions.

**Comment by jumpinjackie** [comment]
@zpao Oh well, at least there's a technical explanation for the problem. Thanks for the heads up.
