### ISSUE TITLE
Following NPM getting started guide incomplete and results in errors

### ISSUE THREAD

**Issue by meschbach** [facebook/react#6047]
I decided to try out React today, and began following the Getting Started Guide for using[ React from npm](https://facebook.github.io/react/docs/getting-started.html#using-react-from-npm).  Unfortunately I was unable to get the example up and running.  The first problem I encountered was the missing HTML file which I scavenged from lower in the page and adapted.  However once I loaded up the `bundle.js` file in the HTML page I received the following error in the browser console:

`Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.`

Was there a step I missed somewhere?

**Comment by jimfb** [comment]
NPM can be a beast the first time you try to use it.  If you're having troubles with the NPM distribution, you can try the guide without NPM: http://facebook.github.io/react/docs/getting-started.html#quick-start-without-npm

**Comment by mxstbr** [comment]
Maybe we should add a tiny HTML file to the npm version too?

**Comment by jimfb** [comment]
The NPM section is already getting really long.  The starter pack is designed to help you get started, it has all the working demos and files all pre-configured and ready-to-go.

**Comment by mxstbr** [comment]
Are you sure? I think adding it would help. As a beginner who's never worked with browserify before, I have no idea what `browserify -t [ babelify --presets [ react ] ] main.js -o bundle.js` does and that I need to include the `bundle.js` file and not the `main.js` file like I normally do. What about a few LoC like this:

```HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello React!</title>
  </head>
  <body>
    <div id="example"></div>
    <script src="bundle.js"></script>
  </body>
</html>
```

**Comment by meschbach** [comment]
Thanks @jimfb for the recommendation!  I've got quiet a bit of experience working with NPM for node and browser based applications.  I've got zero minutes of practical experience with React, however it looks like the code may be executing prior to the DOM load event?  Is there a simple out of the box method like delay until it's safe to manipulate the DOM like jQuery's `$(fn)` function?

In my opinion as an experienced JS developer the NPM section is extremely short compared to the 'starter pack' (1 viewport versus 2.5 viewports on my browser), especially since the NPM example doesn't work out of the box.  Is there a transition guide for using React with standard build tool pipelines like NPM or Bower from the Starter Pack?

@mxstbr Your example HTML file is great and confirmed the problem I encountered was a result of the script tag as a child of the head element as opposed to the body element. Thanks!  I am eager to find out how to keep the script tag within the head element.

**Comment by zpao** [comment]
I think starting with browserify if you have no idea what it's doing is the wrong thing and we should make that more obvious. Really what I'm thinking we do is have a completely separate page for getting started with npm / browserify / webpack. Those are not prerequisites to get started and end up being an immediate distraction. I have some other issues about this so I'm going to close this one out in the mean time.

@meschbach The step you missed was probably putting that script so that it runs after the `<div id="container">` markup - you need to be able to find a node to render into.

**Comment by zpao** [comment]
`$(fn)` is effectively just this:

```
window.addEventListener('DOMContentLoaded', function() {
  React.render(..., document.getElementById('container'))
})
```

**Comment by mxstbr** [comment]
That makes sense. Let me know if I can be of any help!

**Comment by meschbach** [comment]
Thanks for the pointer @zpao .  As for the incomplete documentation, I've glanced at the Starter Pack, however that doesn't integrate very nicely into a build system already using NPM from what I could tell.  I and many I know wouldn't consider themselves started until the framework they are using is obtained via their dependency management system, which is why that particular tutorial was attractive to me.

I was using the Getting Started so I could begin to obtain experience on the framework using tools i otherwise knew, yet I was told I'm too inexperienced to use such tools with React.  I'm a little confused why the issue is marked closed as the documentation isn't complete (root cause of the issue) despite a knowledgable person offering to fix the incomplete documentation.  Could you please explain the reasoning behind closing the issue so I may better understand the way React uses issues?

**Comment by jimfb** [comment]
@meschbach

Paul already answered, when he said:
 > I think starting with browserify if you have no idea what it's doing is the wrong thing and we should make that more obvious. Really what I'm thinking we do is have a completely separate page for getting started with npm / browserify / webpack. Those are not prerequisites to get started and end up being an immediate distraction. I have some other issues about this so I'm going to close this one out in the mean time.

Specifically, read the last sentence.

We don't use github issues to track usage issues/questions.  Usage questions are better addressed on sites like StackOverflow.

**Comment by meschbach** [comment]
Since we seem to have two different view points, please allow me to elaborate mine.  I filed an issue because the documentation is incomplete, since I was directed to this Github project by the documentation.  Was I wrong to create an issue the documentation was incomplete, resulting in an error which couldn't be worked around by new users?  Additionally, I searched for other issues regarding this problem prior to creating this one and I couldn't find any others.  Would you mind references to these other issues?

**Comment by zpao** [comment]
#5679 was what I was thinking of, though it got closed with a PR by accident (I intended it to be longer lived). Ultimately it's not helpful for us with our hundreds of open issues to track slight variations of the same issue in multiple places so we've gotten more aggressive at closing issues right away if we know it's tracked elsewhere.

You were not wrong to create an issue.
