### ISSUE TITLE
onCancel event

### ISSUE THREAD

**Issue by tleunen** [facebook/react#6049]
I don't see the `onCancel` event in the list of [supported events](https://facebook.github.io/react/docs/events.html). Would it be possible to add it in the list?
It's used by the [Dialog element](http://w3c.github.io/html/semantics.html#the-dialog-element), already available in Chrome.

**Comment by jimfb** [comment]
I think it would need to be added to the source code too.

**Comment by tleunen** [comment]
I wanted to do it, but I don't really know in which category we shoul put the `close` and `cancel` events used in the Dialog. In the UI category?

**Comment by jimfb** [comment]
It goes into the UI category if it has the `detail` and `view` properties.  Otherwise, it would probably go into its own category.

**Comment by mxstbr** [comment]
[Here](https://jsfiddle.net/pjjbcx86/2/) is a JSFiddle with a dialog element and the `close` and `cancel` events for reference, works on my Chrome Canary 50.0.2651.0!

**Comment by syranide** [comment]
FYI, it's just an `Event`, no subcategory.

**Comment by ludvigsen** [comment]
Tried implementing support for this here:
https://github.com/facebook/react/pull/6247

Please let me know it i've made any mistakes :)

**Comment by cbrwizard** [comment]
Should React support for the [onClose](https://developer.mozilla.org/en-US/docs/Web/Events/close) event too? It's also related to the dialog.

@ludvigsen you were faster than me, haha, grats =]. I've created an example page (took [examples/basic/index.html](https://github.com/facebook/react/blob/master/examples/basic/index.html) as source) to test out new events on [gist](https://gist.github.com/cbrwizard/02441bc26c7355faac19), you can check it out and use it for easier debugging.

**Comment by ludvigsen** [comment]
Thanks @cbrwizard! It seems like it would make a lot of sense to support the onClose event as well, I can definitely add it. Although in react I guess you would control the dialog through the "open" attribute, and therefore know when the user closed the dialog. Whereas the cancel event is fired if the user presses ESC, so the only way to know about it is to listen for it.

**Comment by tleunen** [comment]
Not really, because you can open a dialog as a normal dialog, or as a modal.

Afaik, there's no way with the attribute to open it as a modal.

**Comment by ludvigsen** [comment]
@tleunen thats true, would be nice if it was possible to control modal as well with an attribute.

**Comment by Aweary** [comment]
@pranaygp looks like this is still an outstanding issue. #6247 was opened to add `onCancel`, but it wasn't reviewed. At this point it would have some conflicts that need to be resolved before it can be merged.

**Comment by pranaygp** [comment]
@Aweary thanks. I'll look into that PR and see if I can help

**Comment by ludvigsen** [comment]
@Aweary will #6247 be merged if the conflicts (and other issues if there are any) are resolved?

**Comment by paulmanta** [comment]
I see that #6247 was merged, should this issue be closed?

**Comment by aweary** [comment]
It should, thank you!
