### ISSUE TITLE
`ensureScrollValueMonitoring` in ReactEventEmitter should accept a `mountAt` argument

### ISSUE THREAD

**Issue by subtleGradient** [facebook/react#605]
`listenAtTopLevel` accepts a `contentDocument`.
All listeners are added to that `contentDocument` except for the ones registered in `ensureScrollValueMonitoring` which register on `window`.

**Comment by gaearon** [comment]
Since #6129 we no longer listen to scroll events except in IE8.
We also stop officially supporting IE8 in React 15.
As far as I can see effectively this means that this issue is no longer relevant.

Thank you for reporting, and please let me know if I’m wrong to close this one.
