### ISSUE TITLE
Programmatically access warnings / errors after rendering

### ISSUE THREAD

**Issue by adrianhall** [facebook/react#6051]
Let's say I have a component which has propTypes:

```
static propTypes = {
   isError: React.PropTypes.bool.isRequired
};
```

I want to ensure that this contract is not broken, so I have a test:

```
    it('should require an isError prop', () => {
        expect(function () {
            let result = renderReactComponent(<Component/>);
        }).to.throw(Error);
    });
```

Unfortunately, it doesn't throw an error - it DOES display a Warning statement.  I'd like that warning statement to be available, thus I should be able to alter my test to this:

```
    it('should require an isError prop', () => {
        let result = renderReactComponent(<Component/>);
        expect(result).to.have.property('warning');
    });
```

thus ensuring the contract is maintained.

**Comment by jimfb** [comment]
`console.error = function(message){throw message;};`

Or you can look at how we do it within the unit tests we have in our React repository.  Either way, this is a usage question rather than a bug in the core.
