### ISSUE TITLE
<img>-elements alt-attribute should not default to "true" if used without a value

### ISSUE THREAD

**Issue by petetnt** [facebook/react#6054]
Consider the following:

```  
render: function() {
    return <img alt src="foo.png" />
}
```

will result in

```
<img alt="true" src="foo.png" data-reactid=".0">
```

If `foo.png` fails to load, user will be displayed `true` instead of nothing

Fiddle: https://jsfiddle.net/6t3tqgdh/

> **alt**
> This attribute defines the alternative text describing the image. Users will see this displayed if the image URL is wrong, the image is not in one of the supported formats, or if the image is not yet > downloaded.
>>Usage note: Omitting this attribute indicates that the image is a key part of the content, but no textual equivalent is available. Setting this attribute to the empty string indicates that this image is not a key part of the content; non-visual browsers may omit it from rendering.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt

**Comment by syranide** [comment]
`<img alt />` translates to `<img alt={true} />` and thus the props become `{alt: true}`. Since `alt` is a string property the boolean will be stringified to `"true"`.

What you want is `<img alt="" />`.

**Comment by jimfb** [comment]
@syranide specifying the `alt={true}` does indicate a usage error, should that be a warning?

**Comment by syranide** [comment]
@jimfb I'm not saying I disagree, but `true` is intentionally stringified to `"true"` in React.

I'm not really sure where I stand on this, personally I much prefer type strictness and wouldn't mind a warning, but then that's not really how JS is (in general) and the current behavior is also kind of logical in the sense that it's what you would get if you passed it to a user component that expected a string and prints or concatenates it with something else. If JS was strictly typed it wouldn't be a problem, so "flow" should technically handle it, but AFAIK that's not possible.

**Comment by jimfb** [comment]
> I'm not saying I disagree, but true is intentionally stringified to "true" in React.

Agree, I'm not saying that behavior should change.  Only that `alt={true}` on an image probably makes no sense.  I actually don't feel super strongly, but I do wonder if it makes sense to add a warning for img.alt props (and probably a bunch of others that are similarly nonsensical).

**Comment by syranide** [comment]
@jimfb That applies to all non-boolean props? `width`, `tabIndex´, `id`, `name` and all the other non-boolean props don't really benefit from accepting a boolean. It's also kind of tricky in practice to decide where to draw the line, if booleans for strings is a warning, shouldn't a number for strings be a warning then too? Or why not? What about objects for booleans (which actually leak memory in a sense)? Again, I wouldn't mind type strictness, but it doesn't seem JS:y and if you don't go all the way with type strictness it seems like really rather arbitrary where you draw the line.

If `alt={1}` makes sense then `alt={true}` kind of makes sense too.

**Comment by jimfb** [comment]
Personally, I lean in favor of being strict; they should all be warnings.  Not sure how the rest of the team feels.

Of course, the DOM has a bunch of edge cases which probably prevent it from being a blanket rule for all string props, in general I think the rule holds.

**Comment by petetnt** [comment]
IMHO the *sensible* way would be "when value is not provided, do what the browser would do". If the browsers cannot decide either (which obviously happens too much), then going for the option that leads to least havoc would be the way to go. 

I agree with throwing errors for cases such as `<img alt={true} />` that make no sense at all, but I also think that `<img alt>` should lead to `<img alt>` or `<img alt="">` at worst. Same with just plain `tabIndex`: `tabIndex` or `tabIndex="-1"` if something must always be provided for the rendered prop on markup. 

I would even be partial for `If it's a [known attribute](https://facebook.github.io/react/docs/tags-and-attributes.html) and it has no value, render the attribute name only to the markup`-approach. Does that have some caveats I am not aware of?

**Comment by syranide** [comment]
> I agree with throwing errors for cases such as <img alt={true} /> that make no sense at all is a good thing, but I also think that <img alt> should lead to <img alt> or <img alt=""> at worst. Same with just plain tabIndex: tabindex or tabindex="-1" if something must always be provided for the rendered prop on markup.

@petetnt That seems rather arbitrary, `<img alt /> === <img alt={true} />` is what it means in JSX. So then translating `<img alt={true} /> === <img alt="" />` in React seems super weird.

> I would even be partial for If it's a [known attribute](https://facebook.github.io/react/docs/tags-and-attributes.html) and it has no value, render the attribute name only to the markup-approach. Does that have some caveats I am not aware of?

In JS, strings can be treated numbers, anything can be treated as if it was a boolean, etc. So `<img alt={a} />` being different to `<img alt={a + b} />` depending on the types is problematic, if `a = true, b = 'foo'`, then the first would be `alt="alt"` whereas the second would be `alt="truefoo"`, and when would you even want `alt="alt"`? In this context the current behavior makes a lot of sense.

**Comment by petetnt** [comment]
@syranide For the sake of this particular issue I am only talking about elements with known attributes that have no values attached.

**Comment by zpao** [comment]
@petetnt the problem though is that the result of the JSX transform *is* giving a value. So even though you haven't explicitly provided `true`, the transform adds it. This was a shorthand enabled in the initial JSX transform and carried into Babel.

`<img alt />` becomes `React.createElement('img', {alt: true})`. In React we have no idea if that was intentional or not and we could end up firing a lot of warnings for false positives if we tried to determine intent.

So in order for you to insert a blank string you must explicitly do that. This is going to just be one of those quirks where JSX !== HTML.

**Comment by petetnt** [comment]
@zpao Yeah, you are right. I guess that's just something we have to live with. 

Closing this for now, feel free to re-open it if you have some other ideas.
