### ISSUE TITLE
React should unmount components upon `unload` event

### ISSUE THREAD

**Issue by jochenberger** [facebook/react#6055]
When the `unload` event is fired on the `window` (e.g. when the tab/window is closed or the page is reloaded), React should unmount all components to prevent memory leaks.

**Comment by syranide** [comment]
That's not how it works, it does not cause memory leaks. If you want this behavior you can unmount it yourself during unload, but it will degrade performance when navigating away from the site.

**Comment by satya164** [comment]
If the tab is closed/page is reloaded, the whole page is destroyed by the browser, where'd the memory leak come from?

**Comment by jochenberger** [comment]
I saw leaks in Firefox when event listeners on the `window` were registered by a component. After some reloads, the tab's memory usage went from 30 to more than 200MB. I've added my own cleanup code though so I'm fine if this is not something that should be added to React itself.

**Comment by jimfb** [comment]
I've also observed some memory leaks in firefox, independent of React, but those are clearly browser bugs and not React bugs.  @syranide is correct, we do not want to waste cpu time during unload, as that would degrade performance when navigating away.
