### ISSUE TITLE
try statements vs perf

### ISSUE THREAD

**Issue by cauburtin** [facebook/react#6057]
I was profiling my app, and noticed those warnings, my app is not reallly slow, but in the code there are some try-finally even without catch, are there reasons to use them? 
![image](https://cloud.githubusercontent.com/assets/3134574/13122745/d7d69c80-d5b8-11e5-9e99-c70069878c06.png)

**Comment by jimfb** [comment]
@cauburtin http://stackoverflow.com/questions/2614473/does-it-make-sense-to-do-try-finally-without-catch

Also, at first glance, it looks like you're using the development build of React.  Try reactjs.min.js for better performance.  We generally try to avoid try blocks within production codepaths, to the extent possible, for performance reasons.

`_renderValidatedComponent` is using a try block to reset the current owner, which will probably go away when owners go away.

**Comment by cauburtin** [comment]
ok thanks, yes dev version butI saw try statements in min version too, less though

**Comment by jimfb** [comment]
Yeah, there are a few, but as far as I know they're all necessary.  If you can find one that can be removed, we'd love to accept a PR for it.
