### ISSUE TITLE
Can we locate the line number when react makes a warning like this "Unknown DOM property class. Did you mean className?"

### ISSUE THREAD

**Issue by liuyutao** [facebook/react#6062]
Can we locate the line number when react makes a warning like this "Unknown DOM property class. Did you mean className?"

There is no hint about which code made this warning.

**Comment by jimfb** [comment]
Yes, it is on my todo list.

**Comment by mxstbr** [comment]
I'd like to take a crack at this @jimfb. What do you imagine the warning is like, full filename/line number in the warning, component name,...?

**Comment by jimfb** [comment]
@mxstbr Honestly, this probably isn't the greatest first bug, until I first blaze the trail by providing an example that you can replicate.  The output would be filename:line, something like `MyFileName.js:54`

You're welcomed to take a stab at it, but just know that you're probably in for a rough time in terms of a code review.  To get an idea of the structure, you will need to look at https://github.com/facebook/react/pull/5590.  You will want to emit an event when you start processing the element, an event when you do an operation (I think that event already exists), and an event when you finish processing the element.  Then you can grab the __source off the element (after enabling [react-jsx-source](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source)) and use that to display the file/line information as part of the error.

**Comment by mxstbr** [comment]
> You will want to emit an event when you start processing the element, an event when you do an operation (I think that event already exists), and an event when you finish processing the element.

 Why do I need three separate events, I thought about using `onSetValueForProperty`, and with `react-jsx-source` add the information to the warning in `ReactDOMUnknownPropertyDevtool`? Am I missing something here?

**Comment by jimfb** [comment]
@mxstbr `onSetValueForProperty` doesn't have access to the element (so it can't access the source), and passing it the element would require routing data through the core for the sole purpose of warnings and doesn't make sense from an DOMPropertyOperations API perspective (avoiding that was one of the motivations for moving the warnings into the devtools - we want to cleanup the core internals).

**Comment by mxstbr** [comment]
Fair enough, makes sense. I'll leave this to you then – if you have anything to do that might be a better first bug, ping me!

**Comment by jimfb** [comment]
@mxstbr We have a whole list of recommended ones here: https://github.com/facebook/react/labels/good%20first%20bug

In particular, these jumped out at me: https://github.com/facebook/react/issues/5839 https://github.com/facebook/react/issues/6049 https://github.com/facebook/react/issues/1858

**Comment by mxstbr** [comment]
#1858 was done in #2065 and can be closed, #5839 has an open PR at #5861 and tleunen reserved #6049. I'll keep a lookout at the list though!

**Comment by gaearon** [comment]
We do have the line numbers for this now if you enable [this transform](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source) in development. It's already included by default with Create React App.
