### ISSUE TITLE
HTML to JSX Compiler broken

### ISSUE THREAD

**Issue by montogeek** [facebook/react#6077]
Hi!

Today I tried to use the HTML to JSX Compiler, and it looks is broken:
![screen shot 2016-02-20 at 11 56 01](https://cloud.githubusercontent.com/assets/1002461/13197889/f60c1c5e-d7c8-11e5-995a-8a23be90d407.png)

**Comment by m6g6a** [comment]
> Mixed Content: The page at 'https://facebook.github.io/react/html-jsx.html' was loaded over HTTPS, but requested an insecure script 'http://reactcommunity.org/react-magic/htmltojsx.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/3456

**Comment by montogeek** [comment]
Thank you

**Comment by viktorsec** [comment]
@jimfb it seems the same issue is happening again when loading via HTTPS.
