### ISSUE TITLE
Add opt-out for contenteditable warning

### ISSUE THREAD

**Issue by spicyj** [facebook/react#6081]

**Comment by jimfb** [comment]
@spicyj I think the opt-out is to grab a ref and set contenteditable attribute imperatively.  Is there a reason we need something more than that?  What did you have in mind?

**Comment by yaycmyk** [comment]
Is this a dev-only warning, or also on prod? If also prod, perhaps limiting it to only dev would be enough.

**Comment by jimfb** [comment]
It is dev-only.

**Comment by devongovett** [comment]
See also: #5837

**Comment by spicyj** [comment]
Thanks, closing for that one. http://facebook.github.io/draft-js/ is our primary motivation here.

**Comment by chigan** [comment]
eagfr

**Comment by chigan** [comment]
eagfr

**Comment by chigan** [comment]
eagfr
