### ISSUE TITLE
Allow cite attribute in blockquote element.

### ISSUE THREAD

**Issue by Primajin** [facebook/react#6084]
`cite` is currently only supported as element, not as attribute in `blockquote`.
Since it is unknown to react it's thrown away on render.

> cite
> A URL that designates a source document or message for the information quoted. This attribute is intended to point to information explaining the context or the reference for the quote.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

**Comment by AprilArcus** [comment]
I'd like to take this!

**Comment by zpao** [comment]
It's yours @AprilArcus! Let me know if you have any questions.

**Comment by Primajin** [comment]
Cool! :+1:

**Comment by jasonrundell** [comment]
Can we get this into a PR pretty please? :o)

**Comment by Primajin** [comment]
Umm this was merged 3 years ago already...

**Comment by jasonrundell** [comment]
@Primajin my apologies. I came across this from a Google search after using cite in blockquote in React 16.8.6 was throwing an error for me at build time. I'll have to dig deeper into the cause.

**Comment by fatih47154** [comment]
> Umm @jasonrundell this was merged 3 years ago aldddddddddddddready...

**Comment by fatih47154** [comment]
> ddddddd@Primajin my apologies. I came across this from a Google search after using cite in blockquote in React 16.8.6 was throwing an error for me at build time. I'll have to dig deeper into the cause.
