### ISSUE TITLE
TestUtils - cannot search for a custom component within a DOM element

### ISSUE THREAD

**Issue by vladimir-rovensky** [facebook/react#6088]
This is the old issue with "Invariant Violation: findAllInRenderedTree(...): instance must be a composite component". I know this was brought up before and it was somehow declared ok, but it keeps causing trouble in my tests, so I thought I'd give this one more shot.

The problem: You cannot search for a custom component within a DOM node. I made a [sample](http://codepen.io/anon/pen/pgXGbe) to illustrate the problem.

The sample is a simplified version of a real problem I'm facing - I have a DataGrid component that renders a bunch of Row components, which in turn render a bunch of Cell components. Each Cell can either render some readonly text, or some custom component passed via props (custom editor). 
I want to turn the Cell into a functional stateless component for better performance. 

Now I have a problem in my tests  - for a given Row, how can I find the custom editor in Cell with given index? Previously (React v <=0.13 I think) it was possible to find the div rendered by given Cell and within this div, find the custom editor. That is no longer possible. Also, since Cell is a stateless functional component, you cannot locate it using the Test API at all.

I really believe that the testing API is incomplete right now, is there any change you guys could take another look at this?

**Comment by gaearon** [comment]
I agree TestUtils limitations aren't very great. I'd encourage you to try something like [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead. I'm sorry I don't have a better solution.

I don't fully understand what you're trying to do. Once you get a DOM node, what's the point of getting a *React instance* just so you can search for a DOM node again? You might as well search for that input directly from the first DOM node you got with something like `node.querySelector()`.

Regardless, I think we might add a better test-only traversal API for ReactDOM, at which point this would be solved, but it's probably not worth adding more churn to the current API until we have a replacement. In the meantime [react-testing-library](https://github.com/kentcdodds/react-testing-library) is really nice and might work better for you.

**Comment by gaearon** [comment]
Here is a fork of your fiddle with `querySelector` used instead: https://codepen.io/gaearon/pen/ZjgVMX?editors=1010

**Comment by vladimir-rovensky** [comment]
I don't necessarily want the DOM element coresponding to the custom editor, I'd just like to be able to find the rendered component instance. Here's an overview of what's rendered:

Row (component instance) ->
Cell (SFC - cannot locate with test API) ->
div.cell -> 
CustomEditor (component instance)

I'd like to be able to find the div with the Test API, run some assertions on it and then use it to locate the inner CustomEditor component instance and check it's props, simulate an event etc. The UI is hierarchical and you'd expect to be able to traverse it like this.

As basic as the React Test API is, we built an entire suit of helpers similar to react-testing-library or enzyme on top of it and it works fine (and is pretty fast too), the only thing I keep fighting with is this issue.

Regardless, thanks for the reply, I appreciate someone taking the time to look at this.

BTW the codepen gives me a 404 right now.
