### ISSUE TITLE
React add-ons make React code be imported in the application bundle

### ISSUE THREAD

**Issue by felipethome** [facebook/react#6093]
So I just stumbled to a problem these days. I was getting that really famous error:

`Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs`

And it was because I had two copies of React inside my project, but I didn't know why. In my project I decided to bundle React in one file, and my application code to another one. What was happening is that even I explicitly saying I wanted React as an external to browserify I was still getting it inside of my application bundle (so two bundles with React). That is because some of your add-ons are just something like the following in their entry point:

`module.exports = require('react/lib/ReactTransitionGroup');`

And then, ReactTransitionGroup has the statement:

`var React = require('./React');`

So, if I am telling to browserify or webpack to treat react as an external with:

`b.external('react')` or `externals: {'react': 'react'}`

I still will get the React code inside of my application bundle if I forget to treat the add-on as an external too, since the last is importing React from inside and not as a npm package (that I declared to be an external in browserify/webpack).

So, is there any chance of changing that in the future? Like for example exporting the add-on code completely to outside the React code so it imports React as a npm package? Or that should not be a concern of the React project, but of the developers using it? Just asking because I saw dozens of questions about this addComponentAsRefTo error and some of the people asking seem to have the error because of what I described.

I did a [demo](https://github.com/felipethome/issue-multiple-react).

**Comment by gingur** [comment]
Mentioned this in https://github.com/yahoo/fluxible-immutable-utils/issues/43 as well, I think the issue is the React interface doesn't expose all of the lib modules.  So using React from via the `dist/react.min.js` doesn't seem to be "fully" supported.

**Comment by stomvi** [comment]
I still get the same error when using ReactCSSTransitionGroup with the latest React version 15.3.0:

`react-with-addons.js:22480 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded`

**Comment by Arjeno** [comment]
I have the same problem. Took me a while before I found that the issue is `require('./React')`.

**Comment by gaearon** [comment]
This looks like an issue with incorrect build setup rather than something we can fix here.
In future we will separate addons completely and it won't be an issue.
