### ISSUE TITLE
shouldComponentUpdate vs componentShouldUpdate

### ISSUE THREAD

**Issue by cauburtin** [facebook/react#6096]
Why did you choose the former? the latter matches a bit better with componentDidMount, ...

**Comment by tundrax** [comment]
Because it is a question returning boolean?

**Comment by leoselig** [comment]
this came up here once facebook/react#5671 and is discussed here reactjs/react-future#40

**Comment by cauburtin** [comment]
ah ok sorry guys, good point tundrax
