### ISSUE TITLE
warning in IE8 when ieCompatibilityMode is undefind

### ISSUE THREAD

**Issue by jacty** [facebook/react#6098]
I have read a snippet in the source of ReactDOM.js(as the 1st pic show).What I am confused about is:
1.the document.documentMode's value is undefined in my IE8;
what's more
 2.when I was running React in my IE8's compatibility mode,got the errors ,like the 2nd pic show, without the warning about compatibilty mode. 

so may I know what is the meaning of this snippet and whether we should add some code to deal with the case I just suffered?
![qq 20160223183504](https://cloud.githubusercontent.com/assets/4190959/13248943/38ef6504-da5c-11e5-915b-5be1bc77da6b.png)
![qq 20160223183514](https://cloud.githubusercontent.com/assets/4190959/13248948/43cca5ea-da5c-11e5-8326-eb975d6dd6e4.png)

**Comment by jimfb** [comment]
What do the red errors say?

**Comment by jacty** [comment]
@jimfb It says the object doesn't support the property or function.

**Comment by syranide** [comment]
@jacty Print `document.documentMode` on your page and also once for the URL `about:blank` and post the results here please. I can only assume `documentMode` is not exposed because of some polyfill you have. That is if it truly is native IE8 and not simulated.

**Comment by spicyj** [comment]
Can you show a little more of the devtools in your screenshot so that the document mode is visible?

![image](https://cloud.githubusercontent.com/assets/6820/13296780/114e7d4a-dae4-11e5-951f-8f5b93e0ffa9.png)

It should say "IE8" and "IE8 Standards". I am guessing that one of those is not properly set.

**Comment by jacty** [comment]
@syranide @spicyj 
Thank you and all.Here is the pic I have snapshot again.
![3](https://cloud.githubusercontent.com/assets/4190959/13316401/e1822e56-dbea-11e5-873b-27d2c5b581db.png)
I could get the documentMode from console,but if I write code to log out the documentMode in the ReactDOM.js, I get nothing but these 2 red errors.
So, I think,something that leads the errors  blocks the code of loging out the documentMode.

**Comment by spicyj** [comment]
I don't know why that would be. You'll probably have to do more digging and figure out what's going on if you want this to be fixed since I haven't heard of anyone else hitting anything like this.

**Comment by jimfb** [comment]
There appear to be no other reports of this issue, and we don't have enough information to make this actionable.  If we can get a clear repro, we can re-investigate.
