### ISSUE TITLE
[TestUtils] Simulate.<event> doesn't set the synthetic event type

### ISSUE THREAD

**Issue by yaycmyk** [facebook/react#6100]
`SyntheticEvent.type` is undefined when received by the handler. Or the nativeEvent type for that matter.

Needs to be added in here somewhere: https://github.com/facebook/react/blob/3a4e1dbb5b2957875cab6af11a5e5934e125a0d8/src/test/ReactTestUtils.js#L496

I realize that it's not sustainable to have to set _all_ the possible fields for a simulated event, but the type at least makes sense for verification that you're getting the right _sort_ of event.

**Comment by gaearon** [comment]
You can optionally pass `eventData` as a [second argument](https://facebook.github.io/react/docs/test-utils.html#simulate):

```js
ReactTestUtils.Simulate.change(node, { type: 'change' });
```

It’s not just limited to `type`. You can add more data to the synthetic event exactly the same way. It will get attached to the event instance with an [`assign()` call](https://github.com/facebook/react/blob/3a4e1dbb5b2957875cab6af11a5e5934e125a0d8/src/test/ReactTestUtils.js#L502).

While there is no official way to also pass a fake `nativeEvent`, you should be able to use exactly the same technique for it:

```js
ReactTestUtils.Simulate.change(node, {
  type: 'change',
  nativeEvent: {
    type: 'change',
    target: node,
  },
});
```

This would bypass [the normalization code](https://github.com/facebook/react/blob/3a4e1dbb5b2957875cab6af11a5e5934e125a0d8/src/renderers/dom/client/syntheticEvents/SyntheticEvent.js#L62-L77) but you probably don’t need it in tests anyway.

I am closing this but please let me know if I missed something.
