### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by gajus** [facebook/react#6107]
Running tests in watch mode results in eventual error "navigator is not defined".

```js
message: navigator is not defined
name:    ReferenceError
plugin:  gulp-mocha
stack:
  - /Users/gajus/Documents/dev/gajus/react-css-modules/node_modules/react/lib/ReactDOM.js:75:11
  - module.js:413:34
  - module.js:422:10
  - module.js:357:32
  - module.js:314:12
  - module.js:367:17
  - internal/module.js:16:19
  - /Users/gajus/Documents/dev/gajus/react-css-modules/node_modules/react/lib/React.js:14:16
  - module.js:413:34
  - module.js:422:10
  - module.js:357:32
  - module.js:314:12
  - module.js:367:17
  - internal/module.js:16:19
  - /Users/gajus/Documents/dev/gajus/react-css-modules/node_modules/react/react.js:3:18
  - module.js:413:34
```

This is happening because after test is run once [`ExecutionEnvironment.canUseDOM`](https://github.com/facebook/react/blob/3b96650e39ddda5ba49245713ef16dbc52d25e9e/src/renderers/dom/ReactDOM.js#L73) becomes true.

**Comment by jimfb** [comment]
Running `npm test -- --watch` seems to work fine in the React repository.

It looks like you are running tests in your own repository, and may not be providing sufficient test isolation.  If you can provide a minimal sequence of calls to React which demonstrate a bug in React, we can re-investigate.

**Comment by zpao** [comment]
What are you using to mock out the global object / `window`? Whatever you're using is passing [the execution env check](https://github.com/facebook/fbjs/blob/c22a147a39b3e4caa2d85e37634c7343b371b966/src/core/ExecutionEnvironment.js#L14-L18), so it probably just needs to add `navigator` as well.

**Comment by gajus** [comment]
For the record, it looks like it is picking up `window` from `jsdom`, https://github.com/gajus/react-css-modules/blob/324f950f25eebbd042abd1b76576c693da159e6b/tests/extendReactClass.js#L13-L17.
