### ISSUE TITLE
HTML to JSX Compiler broken

### ISSUE THREAD

**Issue by alnorris** [facebook/react#6110]
https://facebook.github.io/react/html-jsx.html displays "ReferenceError: HTMLtoJSX is not defined"

**Comment by joecritch** [comment]
Looks like there's already a fix for this in master. https://github.com/facebook/react/commit/6ec8f078f11623db1215ea548374874191c5dc88

**Comment by jimfb** [comment]
Correct, fixed in https://github.com/facebook/react/pull/6089
