### ISSUE TITLE
Warn if calling setState in getChildContext

### ISSUE THREAD

**Issue by blainekasten** [facebook/react#6114]
This code causes a maximum call stack:

```
getChildContext() {
  this.setState({
    foo: 'bar',
  });

  return {
    foo: this.state.foo,
  };
}
```

These sort of errors are hard to track down as the stack trace is deep in react. Is this a place we can give a user an invariant to let them know what they did wrong?

**Comment by jimfb** [comment]
We should warn if you call setState in getChildContext.

**Comment by raineroviir** [comment]
I'll do it!

**Comment by raineroviir** [comment]
[Reproduced error](https://jsfiddle.net/raineroviir/98Law5w8/) (in the console)

**Comment by raineroviir** [comment]
What's a good way to start on this?

**Comment by jimfb** [comment]
@raineroviir Find the places that `getChildContext` is called, and the places that `setState` is defined, and warn if `setState` is called during `getChildContext`.  I think we already do basically the same thing for calling `setState` within `render`, so you can use that as a thing to copy.

**Comment by raineroviir** [comment]
Ok, thank you!

**Comment by raineroviir** [comment]
Can you give me some more pointers.. I'm stuck figuring out whether `setState` is called during `getChildContext`.
I've tried `Function.caller` but got a type error.  And trying to access the context with `this` hasn't worked.

**Comment by jimfb** [comment]
getChildContext might not be the immediate caller, so that won't work.  You're going to need to set some state before and after getChildContext.  We already warn when users call setState in render, take a look at that code.

**Comment by dan-weaver** [comment]
should ReactCurrentOwner.current be set during a getChildContext call?  Looks like it currently is not.
[as seen here](https://github.com/facebook/react/blob/bbd5a78efaf92b7ffcde2a1923112b8931855209/src/renderers/shared/reconciler/ReactUpdateQueue.js#L49)
and

(here)[https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L893]

**Comment by jimfb** [comment]
@dan-weaver I *think* we only set the owner in render.

**Comment by gaearon** [comment]
FYI this is being worked on in https://github.com/facebook/react/pull/6121.

**Comment by SunflowerPKU** [comment]
> Ok, thank you!

Hi @raineroviir 

I am a Ph.D. student. I am doing research about **helping newcomers participate in OSS projects**. I noticed that many projects are using labels such as 'good first issue/bug, difficulty/newcomer' for issues to recommend that newcomers start from these tasks. 

I noticed that you tried to solve this issue, but unfortunately, you had not contributed successfully. I also found there are many newcomers feel difficult when submitting their first pr. Therefore, I want to optimize this mechanism, which needs your help. I have some questions and wish your valuable feedback.

1. What problems did you meet when solving this issue? 
2. Do you think it is appropriate to recommend newcomers to solve this issue?  and why?
3. How do you think of the existing mechanism that adding certain labels to issues for helping newcomers participate in open source projects?

I am looking forward to hearing from you soon. Thank you very much!
