### ISSUE TITLE
progress requires value to be an attribute, but it's a property due to inputs

### ISSUE THREAD

**Issue by syranide** [facebook/react#6119]
Now that #1510 has landed we still have one final issue to fix (ironically, the initial reason for #1510). https://github.com/facebook/react/pull/1510#issuecomment-170229012 + https://github.com/facebook/react/pull/1510#issuecomment-170229162, the problem being that `value` is managed as a property for the purpose of `<input>`, but `<progress>` requires it to be an attribute so that the attribute is correctly removed when null.

As discussed in the second comment, it seems to me that the right approach here is to actually remove all the special property logic from DOMPropertyOperations and instead implement it in the appropriate wrappers instead (ReactDOMInput, etc).

Repro: http://jsfiddle.net/670u7ure/8/
Original issue: https://github.com/facebook/react/issues/1431

cc @jimfb, @spicyj

**Comment by jimfb** [comment]
Alternatively, I think we could take https://github.com/facebook/react/pull/5680 which would solve this by virtue of the fact that we can just use attributes everywhere.   If we take https://github.com/facebook/react/pull/5680, we don't need branching logic for `value` (to use properties sometimes and attributes other times)

**Comment by syranide** [comment]
@jimfb As far as I understand the description it does what this issue suggests.

**Comment by jimfb** [comment]
Fixed by https://github.com/facebook/react/pull/6406
