### ISSUE TITLE
Elements not visible to user in Chrome on HiDPI displays.

### ISSUE THREAD

**Issue by austenmadden** [facebook/react#6122]
In Chrome, on HiDPI displays, elements that exist in the DOM (React Components) are not properly displayed. They exist in the DOM, but are not visible. They are part of a dynamic list that can be filtered.  I will try to link a recreation of this issue here soon.

**Comment by zpao** [comment]
Please do. I'm suspecting an issue on your end as we've never seen hidpi being anything special, but would love to be proven wrong

**Comment by austenmadden** [comment]
@zpao @jimfb I created a demo application in an attempt to recreate this issue using identical code from our app, but the issue was not replicated. So it is possibly due to some dependency, configuration or other process, so I will go ahead and close this.
