### ISSUE TITLE
Spanish docs

### ISSUE THREAD

**Issue by montogeek** [facebook/react#6126]
Hi!

I just noticed that docs are being translated to multiple languages, right now I can see Italian, Japanese, Chinese and Korean.

I would like to contribute with the Spanish version.

How can I start?

**Comment by zpao** [comment]
That would be awesome. One day we might change the way we do it, but for now just look at the other languages as a pattern and open a pull request. Ideally if you could find another native Spanish speaker who could review the translations, that would help us ensure the quality :) There are a lot of docs and they do get updated so you may want to find a few people to help - working in a branch in a fork that you all commit too / review would be my recommended workflow if you go that route.

**Comment by montogeek** [comment]
What would be the code for Spanish, `es-ES`?

**Comment by zpao** [comment]
If you are going for Traditional Spanish then. If you're going to use a different locale then you'd use the appropriate code (eg `es-AR`).

**Comment by montogeek** [comment]
Thanks, `es-CO` will be :)

**Comment by bjrmatos** [comment]
@montogeek maybe we can join efforts inside the https://github.com/reactjs-hispano org and mantain the docs with other people. i think `es-ES` will be enough for the spanish community, no need for `es-CO`, `es-PE`, etc

**Comment by bjrmatos** [comment]
spanish community -> all other countries that speak the spanish language, not only spain

**Comment by lucy-orbach** [comment]
Hi Paul / Hola @montogeek montogeek and  @bjrmatos,

I would love to help you out translate/review the Spanish docs. I'm based in NYC, but come from Mexico and would love to contribute in making React accessible to hispanos

**Comment by FoxPlateVevo** [comment]
Yes that's truth, the community only need translate to es_ES

**Comment by normancarcamo** [comment]
Hi i could help you guys! count me in. I will make space to do this tomorrow.

**Comment by jimfb** [comment]
Keeping the translations up-to-date is an ongoing effort rather than an actionable issue.  We don't need a separate issue to track each language, and we are tracking improved translation management as https://github.com/facebook/react/issues/5810, so I'm going to close out the issue.  This is a valuable discussion, so we can continue the discussion on this thread or move it to [discuss.reactjs.org](https://discuss.reactjs.org/).

**Comment by bjrmatos** [comment]
@lucy-orbach @FoxPlateVevo @normancarcamo feel free to comment in reactjs-hispano/react-es-docs/issues/1 :+1:

**Comment by bjrmatos** [comment]
sorry forgot to mention @montogeek :sweat_smile:

**Comment by fforres** [comment]
Love it!
I can help on the translation :smile: @bjrmatos
