### ISSUE TITLE
Validation for React.PropTypes.oneOf should compare values using Object.is

### ISSUE THREAD

**Issue by chicoxyzzy** [facebook/react#6131]
...to check for `NaN` value proper.

also related to #6130

**Comment by chicoxyzzy** [comment]
should `Object.is` be polyfilled?

**Comment by chicoxyzzy** [comment]
`O.i``s caveat: do we really want `+0` to not be equal to `-0`?

**Comment by zpao** [comment]
This seems reasonable. We've inlined `Object.is` in a couple places now (it's short) so we'll probably just do do that again.

**Comment by chicoxyzzy** [comment]
@zpao can you point me to such places? Maybe it's time to just use polyfill instead of inlining? :)

**Comment by zpao** [comment]
There was some discussion had elsewhere and at least at the time we were trying to avoid another polyfill.

https://github.com/facebook/fbjs/blob/52d3eeb9b156e7ebf578c7fe2b3f1eac76a0fd00/src/core/shallowEqual.js#L20-L32
