### ISSUE TITLE
Componen render but not call Lifecycle functions

### ISSUE THREAD

**Issue by kirsanv43** [facebook/react#6144]
I have a project that creates a HTML layout based on json file
**On the 4th and 3th step, some components are not call lifecycle functions**

# For Example

### Component code

![Component code](http://i.stack.imgur.com/F9KGS.jpg) 
BaseNode – that is empty class

### Rendering result
![Rendering result](http://i.stack.imgur.com/AD9oc.jpg) 

### Console output
![Console output](http://i.stack.imgur.com/k49KV.jpg)

**Mini project with reproducible error:** [project](https://github.com/kirsanv43/ReactJsIssue)

**Comment by jimfb** [comment]
Your mini project is not minimal.  For example, you appear to be using extensions like `webpack-hot-middleware` which could certainly contribute to lifecycle weirdness.  Your repro is a little too complex to see what's going on at first glance.

If you can create a minimal repro within a master/future jsfiddle, that would help us identify the issue.  I have a base jsfiddle (which includes `React`, `ReactDOM`, and `ReactDOMServer`) that you can use as a starting point: http://jsfiddle.net/9kungxn4/

**Comment by kirsanv43** [comment]
Thanks for response! [I did what you advise me to do, can you take a look at this?](http://jsfiddle.net/9kungxn4/20/)

![Console output](https://github.com/kirsanv43/ReactJsIssue/blob/master/error.JPG?raw=true)

**Comment by jimfb** [comment]
Yeah, that's why you're not supposed to use the index as a key if/when you can avoid it.  The index defines the identity.  Step 1 has the first three keys, so those nodes are preserved in Step 2, which is why those nodes don't get mounted in step 2.  The keys are the same, so the nodes get reused.  Example: http://jsfiddle.net/b67vnyn9/
