### ISSUE TITLE
Jest failed, Travis Passed

### ISSUE THREAD

**Issue by jimfb** [facebook/react#6150]
Calling it out as a separate issue so it doesn't get lost in the noise.  

Jest clearly failed, but travis says everything is green:
https://travis-ci.org/facebook/react/jobs/112649566

Discovered in: https://github.com/facebook/react/pull/6121#issuecomment-190312503

cc @zpao @spicyj

**Comment by zpao** [comment]
I pinged @cpojer to look at it. We might just want to downgrade our jest in the meantime.

**Comment by cpojer** [comment]
I would recommend upgrading to 0.9.0-fb3 first. fb1 had some bugs.

**Comment by spicyj** [comment]
My fault. Move the `set -e` out to after the `"$TEST_TYPE" = test` check so that it fails the build if any command fails. Maybe even move it to the top of the whole script -- but I thought there was some reason I didn't do that originally.

**Comment by cpojer** [comment]
@spicyj can you elaborate what's going on here, just in case someone else runs into this and asks me? Also, please upgrade to fb3, the current one sometimes doesn't complete even if all tests pass. 0.9.0 is ready soon, with much better babel and npm3 support :)

**Comment by spicyj** [comment]
Jest is properly returning 1, as is grunt, but since we run stuff after that Travis doesn't notice. That is, if you run

```
false  # failing command
true   # passing command
```

then that counts as a pass because only the last command's status matters. Unless you do `set -e`, in which case it bails out at the first error.

**Comment by cpojer** [comment]
I see. The original problem was however about a worker thread unexpectedly quitting. This might be because one of the tests had a side-effect of killing a node-process for some bad reason.

**Comment by spicyj** [comment]
Yeah, maybe that is a -fb1 problem.

**Comment by zpao** [comment]
We have -fb3 running (I cleaned the caches so we fetched the latest that matched): https://travis-ci.org/facebook/react/jobs/113204333#L242

**Comment by jimfb** [comment]
I think travis is doing the right thing now.

**Comment by spicyj** [comment]
@jimfb That seems unlikely since `set -e` wasn't added to .travis.yml. You sure?

**Comment by jimfb** [comment]
No, I'm not sure, but I did see a travis jest failure on a recent diff.  Though, that diff may have had a syntax error, so it's possible it failed harder because it was unable to parse.

**Comment by spicyj** [comment]
Reading the current travis file, I wouldn't expect a jest failure to cause the travis job to fail.

**Comment by jimfb** [comment]
`¯\_(ツ)_/¯`  and yet I'm 99.999% sure that I did witness travis saying the jest task was red :).  But yeah, like I said, I'm now thinking it was because it the jest task failed at a different point in the task due to it being a syntax error instead of a less severe expectation violation.

**Comment by gaearon** [comment]
I removed `set -e` in d138b286db4fcb7137f9267a30ec64b657d3cfb4. I wasn’t sure if it’s necessary or not, and since I was trying to make master behaves the same way as branches, I removed it from master for  consistency. Should we add it back?

**Comment by spicyj** [comment]
Yes, I think we have to.

**Comment by gaearon** [comment]
Should we also enable it for PRs? That discrepancy surprised me.

**Comment by spicyj** [comment]
Yes. This bug was that it was on for master and not for PRs -- it should be on for all builds.
