### ISSUE TITLE
docs build: bundle exec rake not working with babel 6 update

### ISSUE THREAD

**Issue by bjrmatos** [facebook/react#6155]
in this [commit](https://github.com/facebook/react/commit/1365498b811ac3f91f6462152cc2dc6f1c6f01e4) babel was updated from v5 to v6, that change broke the `bundle exec rake` command necessary to build the examples in docs.

Since babel 6 doesn't have the in-browser transformation, which would be the replacement?
<img width="694" alt="captura de pantalla 2016-02-29 a las 10 52 07 p m" src="https://cloud.githubusercontent.com/assets/4262050/13417149/15f3f508-df37-11e5-832e-b6bdc653e947.png">

**Comment by kittens** [comment]
Can you point to the files that need to be updated?

**Comment by bjrmatos** [comment]
sorry i'm trying to figure it out, i don't have any experience with `Rake` :sweat_smile: 

snapshot of the problem:

<img width="1163" alt="captura de pantalla 2016-02-29 a las 11 07 08 p m" src="https://cloud.githubusercontent.com/assets/4262050/13417379/5cc18426-df39-11e5-8b41-9bdf296bf5c4.png">

**Comment by zpao** [comment]
Probably just want to wget the file from a cdn. Or just update the site to
point at that file on the cdn. Or actually build the Babel 6 version of it.

**Comment by bjrmatos** [comment]
thnks @zpao
