### ISSUE TITLE
ReactElement tests "explicitly not using JSX"

### ISSUE THREAD

**Issue by jmm** [facebook/react#6157]
The [`ReactElement` tests](https://github.com/facebook/react/blob/56c423afd66f7f1363dee87d25795418d5e74a30/src/isomorphic/classic/element/__tests__/ReactElement-test.js#L14-L15) have this at the beginning:

```js
// NOTE: We're explicitly not using JSX in this file. This is intended to test
// classic JS without JSX.
```

But there're a number of instances of JSX in the file. For example, [test # 1](https://github.com/facebook/react/blob/56c423afd66f7f1363dee87d25795418d5e74a30/src/isomorphic/classic/element/__tests__/ReactElement-test.js#L47-L49).

1. Should the note be removed or clarified?

1. Should JSX be purged from the file?

1. When adding tests to this file should they be free of JSX? In certain contexts but not others?

**Comment by jimfb** [comment]
Normally, our style is to use jsx within tests.  I think some of the tests explicitly aren't using jsx, and that's the point.  Perhaps it would be better to copy-paste that message into each of the tests that doesn't use jsx, since it's easy to miss the note up at the top and having the note at the top is somewhat ambiguous.

**Comment by jmm** [comment]
@jimfb Thanks for the feedback.

> Perhaps it would be better to copy-paste that message into each of the tests that doesn't use jsx, since it's easy to miss the note up at the top and having the note at the top is somewhat ambiguous.

Yeah, for both of those reasons I'd say :+1: to either that or splitting it into two files if that made sense to you (would help with the ease of missing it if it's just at the top and make the alternative of repeating it within the file unnecessary): `ReactElement-with-jsx-test.js` `ReactElement-without-jsx-test.js`.

**Comment by mxstbr** [comment]
I'd be happy to submit a PR for either of these cases!

**Comment by jimfb** [comment]
I think I prefer having the inline comment copy-pasted.  A little copy-pasting never hurt anyone (https://www.youtube.com/watch?v=4anAwXYqLG8).

@mxstbr I'd take a PR for this, assuming no one else objects.
