### ISSUE TITLE
[Bug?] componentWillUnmount() is overwritten, not extended, in inheritance chain

### ISSUE THREAD

**Issue by D1no** [facebook/react#6162]
Hi, I happen to run into an odd issue regarding `componentWillUnmount()` which is only called by the top constructor and leaves me with an issue of how to do cleanups of extended component. I am not sure if it's a bug or if I'm just dumb.

Here, the base components `componentWillUnmount()` method is only called, when the top level component does not have one. Small, 30 line, code-pen reproduction of my issue:
http://codepen.io/anon/pen/grbJVq?editors=0010

```jsx
/*
Extending base Component
*/
let ComposerFunction = function(Component) {
  // do some stuff
  class ComposerComponent extends Component {
    constructor() {
      super();
    }
    
    // This is not called
    componentWillUnmount() {
      // Do important clean up stuff!
      console.log("ComposerComponent: componentWillUnmount()");
    }
   
  }
  return ComposerComponent;
};

/*
Top-Level Component (constructor)
*/
class MyComponent extends ComposerFunction(React.Component) {
  
  // With this method defined, ComposerComponent is never called. Uncomment it, than
  // ComposerComponent: componentWillUnmount() will be called. But never both.
  componentWillUnmount() {
    console.log("MyComponent: componentWillUnmount()");
  }
  
  
  render() {
    return(<div className="MyComponent">Click to unmount MyComponent (check console for logs)</div>)
  }
}

/*
Render to a canvas to mount/un-mount by clicking. See logs, only one log message is shown.
*/
class MyApp extends React.Component {
  constructor() {
    super();
    this.state = {show: true};
  }
  handleShow() {
    this.setState({show: !this.state.show})
  }
  render() {
    return(<div className="MyApp" onClick={this.handleShow.bind(this)}>
      {this.state.show ? <MyComponent /> : "Re-Mount"}
    </div>)
  }
}

React.render(<MyApp />, document.getElementById('app'));
```

Console output on clicking (Re/Mounting)
```js
> MyComponent: componentWillUnmount()
// What happend to "ComposerComponent: componentWillUnmount()" ?
```

**Comment by D1no** [comment]
For now I will just grab the constructor in the base component and extend it the old fashion way to ensure both get called. But that feels very hackish.

```jsx
// (...)
  class ComposerComponent extends Component {
    constructor() {
      super();

     if(!this.constructor.prototype._isExtended) {
        this.constructor.prototype._isExtended = true;
        let superComponentWillUnmount = this.constructor.prototype.componentWillUnmount;

        this.constructor.prototype.componentWillUnmount = function (...args) {
          superComponentWillUnmount.call(this, ...args);
          // Do important clean up stuff
          console.log("ComposerComponent: componentWillUnmount()");
        };
      }

    }
// (...)
```

**Comment by zpao** [comment]
You want to make use of `super.componentWillUnmount()` in child classes, that's how inheritance works. If you just do that in your code it looks like something weird happens due to your ComposerFunction in there, but if you just create a base component class and extend that, both will get called. See http://codepen.io/anon/pen/RaNzBX?editors=0010

**Comment by D1no** [comment]
@zpao Well, I know that a normal inheritance works. But not why this, a factory pattern in which a lot more tear-up and down needs to be done, should be going weird. All other methods do stack up fine. I.e. `componentDidUpdate` - as with mixins, without a super call. 

Otherwise I guess, I stick with constructor extension.
