### ISSUE TITLE
SVG renders children="[Object object]" into DOM

### ISSUE THREAD

**Issue by zpao** [facebook/react#6165]
See http://jsfiddle.net/e91q5089/ for a basic example.

I'm assuming there's some step in the new SVG code that we just need to remove the `children` key if we consume it as a React prop.

**Comment by zpao** [comment]
Going to leave this open to ensure we block even though @gaearon wrote fix before I finished submitting (do you ever sleep Dan!?)

**Comment by gaearon** [comment]
I sleep incrementally.
FWIW the fix is in https://github.com/facebook/react/pull/6164.
