### ISSUE TITLE
New Core Algorithm

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#6170]
I'm just going to start this as a thread to give everyone notice of work being put into the core reconciliation algorithm.

This will need to include features like:
- Incremental updates in chunks. Maybe even two different versions of the same tree at the same time!
- Back and forth yielding (and prerender) to support layout. This probably also includes a new type of "context".
- Error boundaries that catches updates.
- Make this work with existing tooling such as dev tools, perf tools, server rendering, various renderers.

If you're working on fixing issues with life-cycles or the core reconciliation parts (like child reconciliation) then you might want to be aware that this is a moving target. There might be requests for changes unrelated to the status quo but related to this future work. It might require a lot of context and commitment to be able to contribute to these parts.

However, if what you're fixing is DOM issues, packaging, builds, diffing of props for styles, react native etc. Then it is probably unrelated to this work and you should feel free to send out PRs.

**Comment by timdorr** [comment]
Really looking forward to how this page changes in the future :smile: https://facebook.github.io/react/docs/reconciliation.html

**Comment by jimfb** [comment]
@timdorr Perhaps ironically, that page is one of the few things that probably won't change.  It's just the implementation of that algorithm that will change.

**Comment by chicoxyzzy** [comment]
First two are things I'm really missed in React. Will be happy to help with them if I can.

**Comment by jquense** [comment]
> There might be requests for changes unrelated to the status quo but related to this future work. It might require a lot of context and commitment to be able to contribute to these parts

For those of us interested fixing stuff in these areas, or are working on renderers, tooling, or other stuff that requires deep knowledge of the internals, how would we gain this context?

Can this work, be done in the open on the repo, whether that's via RFC, public branches, live planning meetings, or just a public PR? It would be great to track, engage and contribute from the start instead of towards the end once the code is mostly baked and pushed.

 cc: @iamdustan

**Comment by jimfb** [comment]
@jquense Yep, as always, we will do our best to keep the community informed and involved.  Currently it's all theoretical discussions about scheduling techniques and tradeoffs.  We will certainly continue to post updates as they become available.

**Comment by iamdustan** [comment]
:clap: This is an exciting turn of events!

From following along for a while it seems as thouhh GH issues and random Twitter conversation/blog posts have been the primary way of tracking current thinking. Should we expect that this will continue and context gathering will come through PR and issue comments and the like or will there be a more formal design document describing potential paths and tradeoffs as these ideas become more solidified?

**Comment by milesj** [comment]
Just commenting on this thread to stay informed with updates. This will be a much needed feature.

**Comment by yaycmyk** [comment]
For others interested in staying up to date, just click the "Subscribe" button:

<img width="236" alt="screen shot 2016-03-03 at 7 49 57 pm" src="https://cloud.githubusercontent.com/assets/570070/13514702/27ba5540-e179-11e5-97b7-48b0f8d6d36f.png">

**Comment by haohcraft** [comment]
is there any resource we can get to know details of the current algorithm's implementation? Or at least, pointing us to that part in the current code base.

**Comment by gaearon** [comment]
@haohcraft 

I found this method really useful to understand how reconciliation works today: https://twitter.com/dan_abramov/status/699395627264962561

**Comment by haohcraft** [comment]
@gaearon NEAT!!!Thanks

**Comment by gaearon** [comment]
Some initial work started here: https://github.com/facebook/react/pull/6690

**Comment by gaearon** [comment]
Related:

* How is Fiber codebase different? https://github.com/facebook/react/issues/7942
* What is left to do in Fiber? https://github.com/facebook/react/issues/7925
* Is Fiber ready yet? http://isfiberreadyyet.com

**Comment by rattrayalex** [comment]
Exciting to see the progress! Awesome to have a chart of tests passing. 

While unofficial, this may also be helpful to interested passerby curious what Fiber is:
https://github.com/acdlite/react-fiber-architecture

**Comment by markspolakovs** [comment]
> Is Fiber ready yet? http://isfiberreadyyet.com

Of course there's already a domain for that.

**Comment by gaearon** [comment]
I think we did it?
React 16 Beta 1 ships with the new algorithm.

https://github.com/facebook/react/issues/10294

This is not the end but a beginning of a new chapter for React.

The basics of all these things are now in place (even though some are not exposed yet), and I’m excited to see how they will evolve over time.
