### ISSUE TITLE
Request: Better documentation of react-addons-perf

### ISSUE THREAD

**Issue by ffxsam** [facebook/react#6174]
https://facebook.github.io/react/docs/perf.html

IMO this is insufficient. Where are we supposed to place each of the API calls? Some example code would be great.

**Comment by gaearon** [comment]
Agreed it’s not great. These APIs aren’t meant to be used from code (at least, not commonly). They are mostly meant to be used from DevTools console. These two articles are really great at explaining how you can use them:

* http://benchling.engineering/performance-engineering-with-react/
* http://benchling.engineering/deep-dive-react-perf-debugging/

ReactPerf is going to change somewhat (#6046) so it would probably be unwise to spend more time documenting the right now.

**Comment by jimfb** [comment]
> Where are we supposed to place each of the API calls? Some example code would be great.

```
Perf.start();
React.render(<div />, document.getElementById('container'));
Perf.stop();
Perf.printInclusive(measurements);
```

Is that the type of code example you are looking for?  Or what would be a code example that you would want?

Also, @gaearon Those links are great, I'd be totally ok with linking to those docs until we release the new react perf stuff.

**Comment by ffxsam** [comment]
@gaearon Wow, awesome links! Bookmarking those, thank you. What was missing for me (from the official Facebook docs) was *where* exactly to put the perf calls. Console? Code? Where exactly in the code?

**Comment by ffxsam** [comment]
Ok, I feel like a n00b. How do I access these tools in the Chrome console? `React` doesn't exist. I can type `React = require('react')`, but `React.addons` doesn't exist.

**Comment by jimfb** [comment]
@ffxsam The easiest way is to use the bower builds:
```
<script src="https://fb.me/react-with-addons-0.14.7.js"></script>
<script src="https://fb.me/react-dom-0.14.7.js"></script>
```

**Comment by ffxsam** [comment]
Yeah, that route won't work for me as I'm using Meteor which doesn't use `script` tags to include things.

**Comment by ffxsam** [comment]
To clarify: I have React installed via npm, and used throughout my project. I have a full Meteor/React project already up and running. I just need to know how to use the perf tools.

**Comment by gaearon** [comment]
I usually do this:

```js
window.ReactPerf = require('react/addons').addons.ReactPerf
```

Again, agreed it’s far from nice, and we need a better story around this.

**Comment by ffxsam** [comment]
Yep, that's what I was going to try next, and that worked. Thanks again!

**Comment by tj** [comment]
yes please, going in circles here between deprecated modules and modules that just cycle back to the bad docs haha

**Comment by ffxsam** [comment]
You haven't seen bad docs till you've been to webpack's website. :)

**Comment by tj** [comment]
would be sweet to have it integrated right in the chrome dev tools, unless someone is already working on that :D

**Comment by gaearon** [comment]
Yeah, that’s the longer term plan.

**Comment by gaearon** [comment]
@tj

>the react-addons-perf module apparently does not exist once installed

Can you clarify? I was able to run 

```
npm i --save-dev react-addons-perf
```

then put

```js
window.ReactPerf = require('react-addons-perf')
```

in my `index.js`, and was able to refer to it from the console

**Comment by ffxsam** [comment]
For me personally, this worked:

```
import Perf from 'react-addons-perf';

window.Perf = Perf;
```

**Comment by tj** [comment]
hmm weird must have been something funky with webpack

**Comment by gaearon** [comment]
You might want to verify you don’t have a duplicate React. Maybe there was some version issue and you got a duplicate one? `npm ls react`

**Comment by lcxfs1991** [comment]
![react-perf](https://cloud.githubusercontent.com/assets/3348398/14566747/66f878ac-0363-11e6-8f91-44f379ef9de2.png)

I see a lot of transactions here like, update attribute, set innerHTML, update styles, set textContent and so on. Do they really happen?

In addition, why I can't see the detailed content of "set innerHTML"

**Comment by gaearon** [comment]
>I see a lot of transactions here like, update attribute, set innerHTML, update styles, set textContent and so on. Do they really happen?

Yes, although AFAIK some `updateAttribute`s might be avoidable: #5329. Note that a DOM operation isn’t necessarily expensive so don’t worry too much about them unless they really seem unexpected.

>In addition, why I can't see the detailed content of "set innerHTML"

The operation name is misleading because it’s actually using `document.createElement()`. Those are real nodes, and reading their `innerHTML` is prohibitively expensive.

**Comment by jmm** [comment]
If you're using Browserify and just want to utilize this from the console without changing your app code you can do `b.require("react-addons-perf")` for the bundle that includes React, then from the console:

```js
window.whatever = require("react-addons-perf");
```

A pain in the neck to be sure, but it's one option for using it currently. Alternatively you could, just in dev, include an additional entry file (from disk or stream) that sets it as a global, e.g.:

```js
if (environment !== "production") b.add("dev-init.js");
```

**Comment by jvalen** [comment]
Hi @tj 

> the react-addons-perf module apparently does not exist once installed

> hmm weird must have been something funky with webpack

I had problems with that too. I'm going to explain what I did, just in case we were in the same scenario or maybe it's useful for someone else.

I was using `webpack-dev-server`, I didn't notice that it loads an iframe and I couldn't access to its context by default from the dev tools console. There is a [drop-down](https://developer.chrome.com/devtools/docs/tips-and-tricks#console-iframe) in Chrome and [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Working_with_iframes) that allows you to switch to the iframe context.

Other solution could be use `webpack-dev-server` [inline mode](https://webpack.github.io/docs/webpack-dev-server.html#inline-mode) which doesn't wrap the app inside an iframe.

**Comment by ConAntonakos** [comment]
Am I missing something? There's no longer `.start()` or `.stop()` it seems?

**Comment by ffxsam** [comment]
Nope, works ok here. Make sure you're referencing the correct `Perf` object.

![image](https://cloud.githubusercontent.com/assets/12532733/16596049/fbcc0b4c-42a6-11e6-9f50-4829ae8b2fa5.png)

**Comment by ffxsam** [comment]
Oh.. I should mention I'm using version 15.1.0.

**Comment by gaearon** [comment]
>Am I missing something? There's no longer .start() or .stop() it seems?

Make sure you have both `react` and `react-addons-perf` of the same version. You probably see this because you updated only one of the packages.

**Comment by gaearon** [comment]
Closing in favor of an umbrella issue in https://github.com/facebook/react/issues/8060.

**Comment by uragecz** [comment]
Is there any way how to print measurement to DOM, for example like a simple text into <div></div> ??

**Comment by curgery** [comment]
react-addons-perf working on react version 16(.1)? Stackflow's documentation is stating otherwise.....
RLG

**Comment by koba04** [comment]
@curgery 

> As of React 16, react-addons-perf is not supported. Please use your browser’s profiling tools to get insight into which components re-render.

* https://reactjs.org/docs/perf.html
* https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab
