### ISSUE TITLE
setState not being called.

### ISSUE THREAD

**Issue by robskidmore** [facebook/react#6178]
After an API call setState is not being triggered. The first console.log statement works as expected and displays all the empty objects from my constructor function, but the callback to setState is never triggered and state is not updated. I've let it sit like this for over 10min.

I have no console errors.

The strange part is that when I am working in another part of the app it magically begins working again and I have no idea why. Am I missing something obvious?

    componentDidMount() {
        this.init()
    }

    init() {
        getDashboard()
            .then(function(data) {
                console.log(this.state)
                this.setState({
                    dashboard: data.dashboard,
                    learning: data.learning,
                    items: data.items
                }, () => {console.log(this.state)})
            }.bind(this))
    }

I get the same result when I remove the second `console.log()` from the `setState` callback and simply place it directly after it.

    console.log(this.state)
    this.setState({
        dashboard: data.dashboard,
        learning: data.learning,
        items: data.items
    })
    console.log(this.state)

**Comment by jimfb** [comment]
Can you create a simple jsfiddle that demonstrates the issue?

Here is a base fiddle you can fork: http://jsfiddle.net/9kungxn4/

**Comment by robskidmore** [comment]
Turns out that `Date.parse()` was failing silently in a child component and preventing state from being set. I'm closing the issue.

**Comment by gaearon** [comment]
You’ll likely want to look up how to enable logging of unhandled rejections for whatever Promise implementation you are using so that such errors don’t go unnoticed.

**Comment by robskidmore** [comment]
Thanks for the tip Dan. I'll defintely look into it. Appreciate all you do.
