### ISSUE TITLE
the reconciliation's chapter have a wrong description

### ISSUE THREAD

**Issue by memoryza** [facebook/react#6181]
the reconciliation's chapter have a wrong description in the guide of react.

[http://facebook.github.io/react/docs/reconciliation.html#custom-components](description url)

the description:

> React takes all the attributes from the new component and calls component[Will/Did]ReceiveProps() on the previous one.

but the react haven't componentDidReceiveProps methond

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/6183
