### ISSUE TITLE
Document context param of ReactClass?

### ISSUE THREAD

**Issue by jmm** [facebook/react#6186]
Should the `context` param of `ReactClass`es be documented? Particularly of the `constructor` of ES6 classes extending `React.Component`?

```js
constructor (props, context)
```

The documentation is a bit scattered, so not sure of the relevant places, but I would think:

* here: [Context](https://facebook.github.io/react/docs/context.html)

* here: [React (Virtual) DOM Terminology](https://facebook.github.io/react/docs/glossary.html)

* perhaps here: [Reusable Components > ES6 Classes](https://facebook.github.io/react/docs/reusable-components.html#es6-classes)

Currently context isn't mentioned at all on *Reusable Components* and ES6 authored Component classes aren't mentioned at all on *Context*.

**Comment by jimfb** [comment]
Yeah, it would probably be worth converting the original/legacy-style components into ES6 classes on the context page.  We intentionally don't mention context outside of the context page because context is an experimental feature that is likely to change in future releases.

**Comment by jmm** [comment]
If it's changed to emphasize ES6 classes, please retain an example for `createClass()` -- I guess under its own heading like stateless functional components.
