### ISSUE TITLE
Synthetic events proxy doesn't work for normal synthetic events

### ISSUE THREAD

**Issue by zpao** [facebook/react#6187]
This blames to #5939, cc @kentcdodds 

Not sure yet if this is affecting all load events or just ones that are attached directly to nodes (for eg image). But the problem is that when we intercept `set` operations for `SyntheticEvent`s (but not "subclasses" like `SyntheticMouseEvent`), we don't have `target.constructor` @ https://github.com/facebook/react/blob/36798f7395d9b2e1cfaed988133d11fa88afa8f1/src/renderers/dom/client/syntheticEvents/SyntheticEvent.js#L199

Simplest repro: http://jsfiddle.net/ge8b0np9/ (will still fail w/o the load listener)

**Comment by gaearon** [comment]
Isn’t this https://github.com/facebook/react/pull/5947 by @koba04?
@kentcdodds’s #5939 was similar but it didn’t use `constructor` or proxies.

**Comment by zpao** [comment]
oops, yea. Sorry for getting the blame wrong!

**Comment by kentcdodds** [comment]
Was just about to ask that :-)

:wave: thanks for thinking of me! Let me know if I can help in any way!
