### ISSUE TITLE
React Root Index with Math.random() causes Invariant Violations with React compiled as V8 Snapshot

### ISSUE THREAD

**Issue by virgofx** [facebook/react#6192]
Using V8 as a backend with snapshots enabled. To optimize performance, it is beneficial to create snapshots to improve server side rendering performance. After creating snapshot with React.js + ReactServer.js, the resulting server side component rendering errors as follows:

```
Invariant Violation: Trying to release an instance into a pool of a different type.
```

The logic that is causing the error is the **Math.random()** function, which has issues with [snapshots and V8](https://bugs.chromium.org/p/v8/issues/detail?id=4810). There are 5 areas where this function is used. At the moment, the biggest problem for server side rendering is the following location; however, the other 4 will also impact if code reached the Math.random() at runtime.

``` js
/**
 * Size of the reactRoot ID space. We generate random numbers for React root
 * IDs and if there's a collision the events and DOM update system will
 * get confused. In the future we need a way to generate GUIDs but for
 * now this will work on a smaller scale.
 */
var GLOBAL_MOUNT_POINT_MAX = Math.pow(2, 53);

var ServerReactRootIndex = {
  createReactRootIndex: function () {
    return Math.ceil(Math.random() * GLOBAL_MOUNT_POINT_MAX);
  }
};
```

Would it be possible to fix this such that server side heap snapshots can be generated without having to worry about issues with server `Math.random()`? Could some sort of algorithm that doesn't rely on Math.random() be used to generate the nodes, root indexes, etc.?
# 

OS: Ubuntu 14.04 x64
V8: 5.0.104
React: 0.14.7

**Comment by jimfb** [comment]
Pooling is a bit annoying for a bunch of reasons, this will probably go away with https://github.com/facebook/react/issues/6190

**Comment by jimfb** [comment]
Clearly I am tired, nvm, this has nothing to do with pooling.

**Comment by ShashiAachar** [comment]
Hey did u find the solution for this?

**Comment by virgofx** [comment]
Currently using a polyfill in [V8Js](https://github.com/phpv8/v8js/pull/207#issuecomment-192688449) that overwrites `Math.random()`. I know V8 engine made some changes. I have not tested without using a polyfill for the Math.random() in snapshots that React uses.

**Comment by ShashiAachar** [comment]
That's cool. Have you tried new Date().getTime() for random number? It should be safe on the server side.

**Comment by virgofx** [comment]
Well, the issue is that React uses `Math.random()` so I'm not sure if they've switched?

**Comment by aweary** [comment]
The [Chromium bug](https://bugs.chromium.org/p/v8/issues/detail?id=4810) has been labeled as fixed, so I'm going to assume this has been resolved. In any case, there's nothing semantically wrong with using `Math.random()` so it would be unlikely that we'd include a change just to address a bug in one platform.

Thanks!
