### ISSUE TITLE
Remove FBJS as dependency

### ISSUE THREAD

**Issue by ivanseidel** [facebook/react#6196]
It is for sure one linked to the other, but what are the reasons for reactjs using fbjs at it's core?

I can't see any way both of them need to co-exist, unless there is a base code for them that is shared. In that case, that should become part of Reacjs, or a shared library among them.

**Comment by jquense** [comment]
fbJS is used by facebook, the react bits used to be in the core here and were pulled _out_ to rely on fb.js. I assume this helps FB reuse and manage common code easier.

Why does it matter if react depends on it? where its in core or not, will have no affect on us as users.

**Comment by gaearon** [comment]
It exists so React Native, React, Relay, and (possibly) other Facebook projects can share some code between them. This is a matter of internal code organization and indeed should not affect you.

**Comment by jimfb** [comment]
This should have no external impact, so I'm going to close it out.  Feel free to continue the conversation on this thread.
