### ISSUE TITLE
Svg textPath startOffset parameter is ignored

### ISSUE THREAD

**Issue by derekdreery** [facebook/react#6197]
See https://jsfiddle.net/2ywd87sc/1/

The top image is in pure svg, and the text is displayed in the middle. The second image is the same svg rendered in react. The pictures should show the text in the same location, but they do not.

It seems that startOffset is stripped by react as it is not recognised. Within the svg namespace in a textPath element startOffset is a valid attribute at can be treated as all other attributes are in react

**Comment by jimfb** [comment]
Fixed in future/master: http://jsfiddle.net/5s44Lhg2/

**Comment by derekdreery** [comment]
Thanks I didn't know which branch was the latest
