### ISSUE TITLE
Investigate why Travis failed to build JS files

### ISSUE THREAD

**Issue by zpao** [facebook/react#6203]
There was a parse error in https://travis-ci.org/facebook/react/jobs/114334244#L567 so the website had important JS files deleted. I manually restored with 2714c5d6f2bf19ee40bbc20b0ad804c1770f01ba. Maybe this was a fluke (looks like Babel was installed) and could be a non-issue after branch cut when we'll switch to Babel 6 but wanted to get this on the books in case somebody else notices and knows what's up.

**Comment by jimfb** [comment]
I believe this has been fixed, reopen if not.
