### ISSUE TITLE
Pre-binding is problematic, binding causes performance issues

### ISSUE THREAD

**Issue by ffxsam** [facebook/react#6205]
Per this article: https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f

I posted this in StackOverflow: http://stackoverflow.com/questions/35855490/react-and-pre-binding-functions-for-performance

I feel like I'm in a catch-22. If I use `bind` on event handlers or the `() => { }` pattern, there could be performance issues with re-rendering. If I use the method described in the article above, then I can't pass arguments to a single DRY function, I have to create several functions to handle different scenarios (as in one of the answers in the SO post, with `setEmail`, `setPassword`).

What's the solution here?

**Comment by jimfb** [comment]
In general, React is pretty fast out of the box.  My guess is that you're over-thinking this whole thing.  A couple calls to bind is not going to make-or-break your application.

StackOverflow is the correct place for a usage question like this.
