### ISSUE TITLE
renderToString() fails to terminate comment node

### ISSUE THREAD

**Issue by coodoo** [facebook/react#6209]
Run this:
```js
let html = renderToString(<div>foo</div>)
```
Get this:
```
<div data-reactroot="" data-reactid="1" data-react-checksum="-1450897250">foo</div>
```
Not sure if this is a bug but I thought `data-reactid` and friends are gone in `v15`, no?

Also when testing `v15` with an old project using `v0.14.7` - which has a much complex scenario, `renderToString()` returned following causing a blank page:

```
<!-- react-empty: 1 -- data-react-checksum="1336804998">
```

Just wondering is the behavior for server rendering changing in `v15`? Thanks.

**Comment by jimfb** [comment]
`data-reactid` is gone for client-side rendering, but still exists for server-side rendering.  This is expected behavior.

However, `<!-- react-empty: 1 -- data-react-checksum="1336804998">` is NOT desired output.  Can you provide an example component/render that generates this output?

**Comment by dittos** [comment]
This happens when a root composite component returns `null`.

```js
var NullComponent = React.createClass({
  render() { return null }
})
console.log(ReactDOMServer.renderToString(<NullComponent />));
// <!-- react-empty: 1 -- data-react-checksum="1336804998">
```

**Comment by jimfb** [comment]
http://jsfiddle.net/k9u4r28j/

**Comment by coodoo** [comment]
I spent all day trying to trace the root cause of the issue and ended up confirmed it's a false alarm, it was caused by `async-props` lib which returns a null root component while rendering on the server. 

I'm currently working on different approaches to implement universal apps on both server and client, will report back if I hit any other issues with v15.

**Comment by jimfb** [comment]
> ended up confirmed it's a false alarm

But, to be clear, this is a valid bug in React.

**Comment by coodoo** [comment]
Update: just confirmed that `v15` is working fine with other apps in regard to server rendering once removed `async-props`.

One thing to note though I saw a lot of comments for text like this, just wondering is it necessary? 
```
<!-- react-text: 9 -->19.99<!-- /react-text -->
```

**Comment by jimfb** [comment]
Right, but the use case that @dittos mentioned clearly demonstrates the bug.

It's necessary for tracking separating the text elements in order to apply updates/diffs.

**Comment by coodoo** [comment]
Understood, thanks for the explanation.
