### ISSUE TITLE
15.0.0-rc.1 css property warnings doesn't contain any context/origin

### ISSUE THREAD

**Issue by edvinerikson** [facebook/react#6216]
Version: **15.0.0-rc.1**
Fiddle: https://jsfiddle.net/69z2wepo/33980/ (check console)

For an example providing `NaN` to a css property will result in "*NaN is an invalid value for the fontSize css style property*".
Now I'm aware that there is an error in my code but I have no idea which component I should check.
I would like to have something like this: "*NaN is an invalid value for the fontSize style property. Check the render method of Header*".
I'll be happy to try to solve this if this is something we want to do.

**Comment by edvinerikson** [comment]
Is this something that we would like to do? cc @spicyj

**Comment by zpao** [comment]
Yea, we could do better here, which would be an improvement. We have a few other style-related warnings which are in the same position (eg "Unsupported style property..."). It looks like the function that's warning there doesn't have enough context to do it but the caller does have a reference to the DOM component that's being rendered. From that we can get the tag (eg, 'div') and I think walk back up to the owner to add the "check render method of ___" bit. If you're interested & can do that soon, we can try to get it into final.
