### ISSUE TITLE
Use Semvar

### ISSUE THREAD

**Issue by AdamHess** [facebook/react#6220]
React is jumping from v0.14->v15? 

Most developers can't make heads or tails about whether or not you guys have finally switched to semantic versioning to start using this project.

Please make it clear that this is the first FULL version release. many of us will NOT consider react for production usage (nor be able to push it past or corporate overlords) until it makes it to the 1.0 version or later.

**Comment by krzysiek1507** [comment]
@AdamHess https://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html

**Comment by zpao** [comment]
We've actually been following semver the whole time 😃. We've already explained the versioning change as @kryogenic has linked and now that it will be over 1.0 you can push it past your corporate overlords.
