### ISSUE TITLE
React v15.0.0 react-addons-css-transition-group and react-addons-transition-group WARN

### ISSUE THREAD

**Issue by raphaguasta** [facebook/react#6229]
After update to react 15, my terminal show this message in my build:

`"npm WARN react-addons-css-transition-group@0.14.7 requires a peer of react@^0.14.7 but none was installed."`

`"npm WARN react-addons-transition-group@0.14.7 requires a peer of react@^0.14.7 but none was installed."`

How can i fix this?

**Comment by david-crespo** [comment]
Try `npm install react-addons-css-transition-group@15.0.0-rc.1`. Not 100% sure, but I think that'll do it.

**Comment by raphaguasta** [comment]
@david-crespo Thank you so much, that worked!
