### ISSUE TITLE
onPaste and div annoyances

### ISSUE THREAD

**Issue by fowerling5555** [facebook/react#6231]
I'm not certain if this is a react issue or not, but it's quite annoying. Any help would be greatly appreciate.

I want to be able to autofocus on a div, and have onPaste register automatically. ie. I should immediately be able to press ctrl-v and trigger the handlePaste handler after the component has mounted.

However, the only way I'm able to achieve this is through a combination of hacks:

1. div needs tabIndex set to 0
2. div needs to be contentEditable={true} (which throws really annoying warnings in addition to introducing a blinking cursor, also it makes everything mutable, which is terrible)
3. I still need to add some dummy text.

Source:

```
var Hello = React.createClass({

  handlePaste: function(evt) {
  	evt.preventDefault();
		console.log("handling paste");
  },

  render: function() {
    return <div
    	style={{color: "transparent"}}
      tabIndex={0}
      contentEditable={true}
      ref={function(main) {
        if (main != null) {
          main.focus();
        } 
      }
    }
    onPaste={this.handlePaste}>
    	<svg width={200} height={200}>
      	<rect width={50} height={50}/>
      </svg>
      text
    </div>;
  }
});

ReactDOM.render(
  <Hello name="World" />,
  document.getElementById('container')
);
```

jsFiddle:

https://jsfiddle.net/7gfhcv1s/2/

**Comment by zpao** [comment]
cc @hellendag because I hear he knows something about all of this.

**Comment by hellendag** [comment]
Since your div is static, it will have to have the `tabIndex` in order to be focusable. It seems that the paste event occurs on `body` even if your static div has been given programmatic focus, though. My hunch is that this may be intentional by browsers, but I don't know.

I recommend creating a jsfiddle that just renders the contents with plain HTML and hooks up an event listener the old fashioned way, with no React involved. That should help clarify whether React is getting in the way here.

**Comment by fowerling5555** [comment]
Sorry I meant to say I'm *not* sure if this is a react specific issue or not. I suspect that it's not

**Comment by jimfb** [comment]
I'm going to close this out as "probably not react issue" as per @fowerling5555's latest comment.  If someone can demonstrate that this is a React issue (using jsfiddles) we can reinvestigate.

**Comment by bkilrain** [comment]
Hey all - I'm running into the same problem. @fowerling5555 , did you come up with a workaround for this or did you just use contentEditable?
