### ISSUE TITLE
A syntax error can't be detected by JSXTransformer.js  about `extends` keyword

### ISSUE THREAD

**Issue by wmlgl** [facebook/react#6234]
`class IndexPage extends React.Component() {
    render() {
        return (<div />);
    }
}`

I think "extends React.Component() "  is not a right syntax.

version:  React v0.13.0
chrome browser version: 47.0.2526.111 m

**Comment by sairion** [comment]
JSXTransformer is deprecated and you can use babel for JSX transpilation.

references:
- (deprecation notice) https://github.com/facebook/react/blob/401e6f10587b09d4e725763984957cf309dfdc30/docs/_posts/2015-06-12-deprecating-jstransform-and-react-tools.md
- react preset for Babel 6 (or you can use 5.x.x) https://babeljs.io/docs/plugins/preset-react/

**Comment by jimfb** [comment]
Or the babel6 transform that I use for my own testing: http://www.jimsproch.com/react/

But yeah, you have a couple extra parenthesis after `React.Component`; should be:
```
class IndexPage extends React.Component() { render() { return (<div />); } }
```

**Comment by wmlgl** [comment]
Thanks, i will use Babel 5 and require1k in the bowser.
