### ISSUE TITLE
Css Unrepaint Chrome only when I'm rerendering

### ISSUE THREAD

**Issue by antoninlanglade** [facebook/react#6235]
Hi,

I have found an issue on Chrome. When I'm re-rendering my Mobile / Desktop React Component the CSS properties are not repainted. If I go to the inspector and just change a property like font-size or color or whatever I see the repaint.

Any ideas ?

**Comment by jimfb** [comment]
Can you provide a jsfiddle which demonstrates the issue?

You can fork http://jsfiddle.net/9kungxn4/

**Comment by antoninlanglade** [comment]
I can not really jsfiddle that because I've seen only this error when I'm locally gulping my project with the devtool open. I think that it's a Chrome issue ...

**Comment by gaearon** [comment]
It is likely that you’re hitting a browser bug.

It might also be possible that there is a bug in React, but unfortunately there is not enough information here for the team to investigate it. If you manage to isolate the issue in a fiddle, please let us know.

I will close the issue, but we are happy to reopen if you can provide a way to reproduce.
Thanks!
