### ISSUE TITLE
Enhance PropTypes : XOR

### ISSUE THREAD

**Issue by damienleroux** [facebook/react#6236]
Hello!

I tries with react to declare XOR behavior in the props I used on component. I succeeded somehow and [post a solution for that](http://stackoverflow.com/questions/35892278/how-to-declare-react-proptypes-xor) but the result lack simplicity and could be include in React I think.

What do you think?

**Comment by damienleroux** [comment]
I think it could be great to declare XOR behaviors to improve usability. May be somthing like that at the end:

```
ResponsiveTable.propTypes.xor = {
  widthXOR:[
    {
      width:React.PropTypes.number.isRequired
    },
    {
      widthOffset: React.PropTypes.number,
      minWidth: React.PropTypes.number.isRequired
    }
  ]
};
```

Either I fill "width" with an integer or I fill minWidth + optionally widthOffset. We can imagine more than two configurations.

**Comment by yaycmyk** [comment]
This is a question for StackOverflow, but I think you're looking for:

```
React.PropTypes.oneOfType([
  React.PropTypes.shape({
    width:React.PropTypes.number.isRequired
  }),
  React.PropTypes.shape({
    widthOffset: React.PropTypes.number,
    minWidth: React.PropTypes.number.isRequired
  }),  
])
```

**Comment by damienleroux** [comment]
Hum,

I didn't think about mixing oneOfType & shape. I guess it should work. Thank you!

**Comment by riteshjagga** [comment]
I assigned the above solution in this way:

```
<MyReactComponent>.propTypes = React.PropTypes.oneOfType([
  React.PropTypes.shape({
    width: React.PropTypes.number.isRequired
  }),
  React.PropTypes.shape({
    widthOffset: React.PropTypes.number,
    minWidth: React.PropTypes.number.isRequired
  }),  
])
```

React shows a warning saying that `isRequired` property is required.

The above comment doesn't say where it is being assigned i.e. the left side of the assignment. How do I use exclusive or properties in the `PropTypes.shape` one level down i.e. inside the `PropTypes.shape`.
