### ISSUE TITLE
react-addons-css-transition-group should not use require() in browser environment

### ISSUE THREAD

**Issue by eyalw** [facebook/react#6238]
react-dom library checks if it is ran in a browser env and then uses the window global to get a React reference. react-addons-css-transition-group library ( and probably other addons) do not do this, and also do not supply a /dist/ folder.

**Why is it important?**
When optimizing Webpack for development, you want to set 'react' library as noParse, and alias 'react' directly to the dist/react.min.js.  This saves a lot of time. However, since libraries like css-transition-group require "react/lib/..." , this is not possible.

I know react-dom and the addons will be *truly* divided into separate packages in the future... is there any estimate on when?

**react-addons-css-transition-group**
```javascript
module.exports = require('react/lib/ReactCSSTransitionGroup');
```

**react-dom**
```javascript
;(function(f) {
  // CommonJS
  if (typeof exports === "object" && typeof module !== "undefined") {
    module.exports = f(require('react'));

  // RequireJS
  } else if (typeof define === "function" && define.amd) {
    define(['react'], f);

  // <script>
  } else {
    var g;
    if (typeof window !== "undefined") {
      g = window;
    } else if (typeof global !== "undefined") {
      g = global;
    } else if (typeof self !== "undefined") {
      g = self;
    } else {
      // works providing we're not in "use strict";
      // needed for Java 8 Nashorn
      // see https://github.com/facebook/react/issues/3037
      g = this;
    }
    g.ReactDOM = f(g.React);
  }

})(function(React) {
  return React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
});
```

**Comment by gingur** [comment]
+1. I'm trying to use webpack alias for react and react-dom, however several libs are requiring react libraries directly (https://github.com/facebook/react/blob/master/packages/react-dom/index.js).  When webpack tries to process this it includes that lib and its dependencies in my bundle regardless if react and/or react-dom was already included either by CDN or webpack alias.

**Comment by zpao** [comment]
This is unfortunate side effect of combining npm modules and dist versions but there isn't really anything we can do without exposing all of the modules that the transtion group addon needs on the React object (like we did with __SECRET_DOM...). We aren't going to do that. Using the dist version of React and the addons is simply incompatible. I suggest using the npm package of React so everybody can be using the same code.
