### ISSUE TITLE
GUI automation testing after React 0.14 without data-react-id

### ISSUE THREAD

**Issue by mooncakelmn** [facebook/react#6244]
Hi there,

Sorry to open an issue here, but we used to leverage the mechanism of `data-react-id` to identify an element in GUI automation testing framework like Selenium. (We are using inline-style and add several unique keys to different components)

This works well in current version, but seems `data-react-id` [gonna be removed in React 15](https://facebook.github.io/react/blog/#document.createelement-is-in-and-data-reactid-is-out). I have not tried with the new RC version yet, but just wondering how should we do in React 15?

**Comment by gaearon** [comment]
`data-react-id` was an implementation detail so it’s best to avoid relying on something like this. I would suggest you to come up with your own system of unique keys (e.g. `data-automation-id="..."`) and use those instead. Unlike with the ones generated by React, you can set these explicitly, have full control over them, and they are guaranteed to not go away.

Does this help?

**Comment by mooncakelmn** [comment]
Thanks Dan for the suggestion. The solution is clear. Although it still adds extra attributes, we could manage those unique keys base on the components hierarchy, those keys only needed on certain ones. 

BTW, has anyone tried to leverage the same idea under [React Developer Tools](https://chrome.google.com/webstore/detail/fmkadmapgofadopljbjfkapdkoienihi) for the testing?
