### ISSUE TITLE
v15-rc1 seems to skip some text nodes in IE

### ISSUE THREAD

**Issue by heapx** [facebook/react#6246]
The following 

```
var Hello = React.createClass({
  render: function() {
    return <div><p>Hello</p>test</div>;
  }
});
```

results in only "Hello" being written in IE11 - [jsfiddle](https://jsfiddle.net/hL0jpazq/2/)

I realize there has been some changes to the way text nodes work in v15, but before we update our code to use `<span>`, I wanted to check if this is the intended behavior (since "test" is written in chrome).

**Comment by syranide** [comment]
This is certainly a bug. cc @spicyj @zpao

**Comment by gaearon** [comment]
I can reproduce it in IE11.
Edge seems fine though.

**Comment by dittos** [comment]
It seems that [DOMLazyTree](https://github.com/facebook/react/blob/master/src/renderers/dom/client/utils/DOMLazyTree.js) having different behaviour on IE causes this bug. (also reproduced in Edge)

**Comment by dittos** [comment]
Every text node is skipped. (minimal repro case: [jsfiddle](https://jsfiddle.net/hL0jpazq/3/))

A ReactDOMTextComponent returns DOMLazyTree something like:

```
{
	node: DocumentFragment,
	children: [
		{ node: Comment },
		{ node: Text },
		{ node: Comment }
	]
}
```

Then DocumentFragment is inserted into the parent element **before** the children are added to the fragment, so nothing is rendered.

**Comment by spicyj** [comment]
Darn it, I remember considering this a few months back but must have forgotten. Easiest solution might be to treat document fragments specially in DOMLazyTree but I'm open to other ideas.

cc @mwiencek if you're interested

**Comment by zpao** [comment]
Thanks to everybody for the quick find and reduction! This is exactly how the process should work ♥️
