### ISSUE TITLE
Run at least a subset of the tests in-browser before releases

### ISSUE THREAD

**Issue by yaycmyk** [facebook/react#6248]
Frankly, it scares me a little that a [substantial IE text node bug](https://github.com/facebook/react/issues/6246) made it through into a release candidate. Some of the tests could _fairly easily_ be run on SauceLabs or a similar service to do actual browser verification.

**Comment by iamdustan** [comment]
Is this not precisely what prereleases are for? To capture bugs that unit tests and the team has missed in development?

**Comment by gaearon** [comment]
This is definitely something we want to do.
Please refer to #5703 for the related discussion.
I’m not sure what the specific roadblocks are, but it’s better to ask in the existing issue.

**Comment by yaycmyk** [comment]
@iamdustan absolutely not. Relying on the community to catch core bugs is ludicrous

**Comment by zpao** [comment]
Yea, this was a bad one that got through. We should have caught it. There are a couple things we could do differently for that particular one (including but not limited to browser testing). Thanks for bringing it up - it's definitely on our minds.
