### ISSUE TITLE
IE and React 15RC

### ISSUE THREAD

**Issue by phaistonian** [facebook/react#6265]
Here's a weird I noticed today when debugging on IE10

![image](https://cloud.githubusercontent.com/assets/796530/13782870/977c1ee8-ead1-11e5-93aa-44ae36d36072.png)

Wrapping the "hello"  label inside a span, ie `<span>hello</span>` would, of course, do the trick.

My guess is that this issue is also present in IE9 and perhaps IE11 too.

**Comment by iamdustan** [comment]
Is this a dupe of https://github.com/facebook/react/issues/6246?

Fixed by https://github.com/facebook/react/pull/6251 in the next RC.

**Comment by jimfb** [comment]
Yes, closing as per @iamdustan, should be fixed in latest/master.

**Comment by phaistonian** [comment]
Thank you for the super prompt response.

An ETA on new release?

**Comment by jimfb** [comment]
ETA is within the next week.
