### ISSUE TITLE
Add warning for onFocusIn and onFocusOut

### ISSUE THREAD

**Issue by jimfb** [facebook/react#6275]
As per https://github.com/facebook/react/pull/6274, we should warn if these attributes are used.

**Comment by joshhunt** [comment]
I might try and take a stab at this as a 'good first bug'

**Comment by jontewks** [comment]
Hey @jimfb, I just submitted #6296 to fix this issue. Thanks!

**Comment by troydemonbreun** [comment]
@jimfb This would be my 1st ever submission to React, any chance you'd take a PR from me since I got my commit in 1 minute before @jontweks PR?  (worth a try, I guess)
