### ISSUE TITLE
renderToString in 15rc2 still put 'data-reacid' in markup

### ISSUE THREAD

**Issue by toddgeist** [facebook/react#6279]
It looks to me like [ReactDOMServer.renderToString](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostring) still puts in the the data-reacid attributes, everywhere. Is this intended?

In my quick tests [ReactDOMServer.renderToStaticMarkup](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostaticmarkup), seems to do the job now, since 15rc2 no longer needs the react-dataid.

do we need both render methods going forward?

Todd

**Comment by zpao** [comment]
both are needed and the id is still there for React to mount that markup. If you use renderToStaticMarkup and render over that, the DOM will be thrown away, which can be bad for large content (might see a flicker) and for stateful elements like inputs.

You mentioned on Twitter that you had a specific problem. If you can repro that, please file a new issue and we can see what's going on.

**Comment by toddgeist** [comment]
Will do. Thanks
