### ISSUE TITLE
Incorrectly displaying html entities

### ISSUE THREAD

**Issue by QuantumKing** [facebook/react#6294]
I have a bit of JSX which looks like
```jsx
<button type="button" className="close pull-right" aria-label="Close" onClick={ this.props.onDestroy } style={{marginTop: '-2px'}}>
  <span aria-hidden="true">&times;</span>
</button>
```
and it compiles down to

```js
_react2.default.createElement(
  'button',
  { type: 'button', className: 'close pull-right', 'aria-label': 'Close', onClick: this.props.onDestroy, style: { marginTop: '-2px' } },
  _react2.default.createElement(
    'span',
    { 'aria-hidden': 'true' },
    '×'
  )
)
```
(I'm using babel). The `&times;` however is showing up as `Ã—` in the browser... Any idea what's going on?

**Comment by mxstbr** [comment]
That must be a problem with your browser/encoding setup, works fine for me on Chrome Canary: http://react.jsbin.com/royihesodo/2/edit?js,output

**Comment by QuantumKing** [comment]
@mxstbr Your link works in my browser too. I am using React version 0.14.7 btw

**Comment by zpao** [comment]
You need to set your charset to utf-8 in the meta tag on your html doc. That's should be it.

**Comment by QuantumKing** [comment]
@zpao Oh wow. Thanks!
