### ISSUE TITLE
validateDOMNesting: figure inside a p tag

### ISSUE THREAD

**Issue by alansouzati** [facebook/react#6295]
Hi,

  I'm using a markdown to JSX parser and everything works ok but I see a warning in the console for a react DOM validation:

```console
Warning: validateDOMNesting(...): <figure> cannot appear as a descendant of <p>.
```

Checking the specs it seems that `p` allows for `figure`.

See here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

> Permitted parent elements: Any element that accepts Flow content.

`p` is a valid flow content element.

**Question**: Is there any other reason for this warning to be there that I'm not aware of?

FYI: I'm using React `0.14.7`

**Comment by cody** [comment]
Browsers alter the code if you put a `<figure>` inside of a `<p>`.

For example this html:
```html
<p>
	<figure>
		hey
	</figure>
</p>
```
Using Inspect in Chrome shows that the DOM is different than the html:
```html
<p>
</p>
<figure>
	hey
</figure>
<p>
</p>
```
If the DOM is different from what React expects, then strange bugs happen on rerender. Therefore
React warns.

**Comment by syranide** [comment]
@alansouzati You're reading it wrong, `<p>` itself is in the flow content category, but it only accepts phrasing content which `<figure>` is not part of. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

**Comment by alansouzati** [comment]
Thanks for the clarification guys.
