### ISSUE TITLE
distinguish between React elements and plain old objects

### ISSUE THREAD

**Issue by cauburtin** [facebook/react#6297]
I'm using some short-hand functions for rapid prototyping, and need to check if the arguments are react elements objects or 'normal' ones.

Using  .$$typeof for the moment, but is it reliable?

`var isPojo = o => typeof o === 'object' && !Array.isArray(o) && !o.$$typeof; // separate plain old js objects from react elements`

**Comment by gaearon** [comment]
Does [`React.isValidElement()`](https://facebook.github.io/react/docs/top-level-api.html#react.isvalidelement) help? This should be it. Let me know if I missed something.

**Comment by cauburtin** [comment]
Thanks much gaearon
