### ISSUE TITLE
Disabled input button should not fire onClick in IE11

### ISSUE THREAD

**Issue by nippur72** [facebook/react#6304]
the following button should not fire `onclick`, but it does so in IE11:
```
<input type="button" disabled onClick={handleClick} value="..."></input>
```
Chrome and Mozilla are ok; using the normal DOM without React is ok too.

See the [plunker example](https://plnkr.co/edit/ow8tPPK89pSZOAsJlYJs?p=preview) that reproduces the issue (open it with IE).

**Comment by gaearon** [comment]
I can reproduce this on IE11.
Have you looked into why this might be happening?

**Comment by cody** [comment]
There is already issue #1790 and PR #6215.

**Comment by gaearon** [comment]
Oh, indeed. Then I’m closing this as a duplicate.
