### ISSUE TITLE
input[type="color"] fires continuous change events

### ISSUE THREAD

**Issue by Prinzhorn** [facebook/react#6308]
https://jsfiddle.net/69z2wepo/35458/

The native color picker will fire a lot of `input` events and then a single `change` when closing the picker.

The react version fires `change` at the same rate as `input`.

**Comment by cbrwizard** [comment]
@Prinzhorn what browser do you use? I have Chrome 49.0.2623.87 (64-bit) Mac and for me it acts like this:
Native color picker fires both input and change on color picker change and no events when closing the picker.
React version does the same.

**Comment by visualfanatic** [comment]
Can confirm @cbrwizard, I'm on Windows x64 (same chrome version).

**Comment by gaearon** [comment]
I think this is intentional and normalized across the browsers. Please see https://facebook.github.io/react/docs/dom-differences.html:

>The `onChange` event behaves as you would expect it to: whenever a form field is changed this event is fired rather than inconsistently on blur. We intentionally break from existing browser behavior because `onChange` is a misnomer for its behavior and React relies on this event to react to user input in real time. 

See also https://facebook.github.io/react/docs/forms.html.

**Comment by Prinzhorn** [comment]
Thanks for the replies. The exact behavior seems to different depending on Browser and OS. For me Chromium on Ubuntu will only fire `change` when I close the picker using the X in the top right corner (yeah, great ux for saying "accept this color value"....). Whereas Firefox on Ubuntu I have "cancel" and "ok" buttons which trigger `change`. But `input` is continuous.

Since native behavior is inconsistent as well I guess it's fine that react tries to make it consistent.
