### ISSUE TITLE
onScroll doesn't work in IE8

### ISSUE THREAD

**Issue by zpao** [facebook/react#631]
Here's an example: (no jsfiddle because that's broken in IE8)

http://playground.zpao.com/react/onscroll.html

**Comment by rakeshok** [comment]
It also prints the warning if you render on the server, its annoying :/

**Comment by spicyj** [comment]
That's odd, I wouldn't expect that code to run at all when using server rendering.

**Comment by vmakhaev** [comment]
I see this message when I'm doing `TestUtils.renderIntoDocument` with `node-jsdom`. Any chance to disable it?

**Comment by b2whats** [comment]
I also see this error when using ssr

**Comment by hammer65** [comment]
This is happening to me with JSDOM as well and in my case our team project standards aren't going to accommodate leaving these errors in the console when tests are run. How can I suppress or stub this out. It's not just obnoxious it is preventing me from getting my work merged in our project.

**Comment by anthonyhastings** [comment]
@vmakhaev / @hammer65 - I am now seeing this error after upgrading my version of Enzyme to `3.1.0`. Did you find a way to suppress these warnings for JSDOM?

**Comment by gaearon** [comment]
If you're having problems please file a new issue.
Nobody actively reads old issues, and requests for help here will get lost.
