### ISSUE TITLE
Explore possibilities of an Emmet-style react plugin that allows for succinct templating

### ISSUE THREAD

**Issue by cameronjroe** [facebook/react#6334]
I've been using [emmet](https://github.com/emmetio/emmet) for a while in sublime and it occurred to me that the angle brackets were re-purposed to actually provide a useful utility (nesting). If you consider in JSX where a component is returning an xml-like syntax:

```
...
return (
<div className="panel">
   <h1>{this.props.header}</h1>
   <p>{this.props.content}</p>
   <a href="#">{this.props.button}</a>
</div>
);
```

vs

```
return (
  div.panel >
    h1{this.props.header} +
    p{this.props.content} +
    a[href="#"]{this.props.button}
)
```

You can see that it would be much more succinct to remove the brackets. Although it's not as easily readable, it's much faster to write.

Currently, angle brackets are not serving a purpose other than delineating a tag. We can assume the returned output will be a tag, so therefore it could be more useful to re-purpose the usage to stating a nested hierarchy.

Just an idea, but I thought it was worth mentioning.

**Comment by cameronjroe** [comment]
Here's an alternative with a fleshed out syntax including a composed component.

```
...
return (
<div className="panel">
   <h1>{this.props.header} {this.props.logo}</h1>
   <p>{this.props.content}</p>
   <ComposedComponent data={this.props.data} />
   <a href="#">{this.props.button}</a>
</div>
);
```

vs

```
return (
  div.panel >
    h1{ #{this.props.header} #{this.props.logo} } +
    p{this.props.content} +
    { #{ComposedComponent(data: this.props.data) } } + 
    a[href="#"]{this.props.button}
)
```

**Comment by Aweary** [comment]
Interesting idea, but I think something like this would have more success in userland (babel plugin or something) rather than in React itself.

**Comment by jimfb** [comment]
Yeah, @Aweary is exactly correct.  JSX is just transformed into `React.createElement`.  This is done by Babel, not by React.  Babel makes it easy for you to write your own transforms, so you can do something like this for emmet in userland without any changes to React.  If the transform becomes popular enough, it might even become a babel preset that people could enable.  Regardless, it's not something that we should track in the React repository.

**Comment by cameronjroe** [comment]
Cool, thanks.
