### ISSUE TITLE
Clarify the usage of Dynamic Children Key prop

### ISSUE THREAD

**Issue by VladShcherbin** [facebook/react#6339]
I've seen a lot of people doing dynamic lists of items with add/remove actions like this:

``` jsx
{items.map((item, i) =>
  <li key={i} onClick={this.handleRemove.bind(this, i)}>
    {item}
  </li>
)}
```

While static lists are probably ok with index as a key, using index as a key in a dynamic list is wrong. There is even [an article](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318#.dzoy90qka) about it, but no info about this in the docs.

This has to be added as a warning in the docs [somewhere here](https://facebook.github.io/react/docs/multiple-components.html#dynamic-children) so that people could clearly see, that they can't use index as a key in dynamic lists.

**Comment by Bear-Foot** [comment]
If a warning is to be added, would be my pleasure to be as concise and relevant as possible.

**Comment by VladShcherbin** [comment]
There is a note in the docs now, I think we can close this.
