### ISSUE TITLE
Nested properties issue

### ISSUE THREAD

**Issue by Voronar** [facebook/react#6344]
Hello.
I have the code:
```javascript
class Component extends React.Component
{
  render()
  {
    this.props.nested.prop = this.props.parse.nested.prop;
    return <div>Component</div>;
  }
  componentDidMount()
  {
    console.log(this.props.nested.prop);
  }
}
Component.defaultProps = 
{
  nested:
  {
    prop: "default"
  }
};

const obj1 = 
{
  nested:
  {
    prop: "obj1"
  }
};
const obj2 = 
{
  nested:
  {
    prop: "obj2"
  }
};

class Application extends React.Component
{
  render()
  {
    return (
     <div>
        <Component parse={obj1}/>
        <Component parse={obj2}/>
    </div>
    );
  }
}

React.render(<Application />, document.getElementById('app'));
//console output:
//"obj2"
//"obj2"
```
Why do I get 1 variable reference for 2 separate components instead of 2 instanses of `nested.prop` for every component?
Why `this.props` saves only last setted value for **all instanses** of the component **after mounting**? Is it a normal behavior?
I think the correct behavior is having different property values for different instanses.

P.S. I tested this code [here](http://codepen.io/voronar/pen/mPwebK).

**Comment by jimfb** [comment]
You are not permitted to mutate props.  The line `this.props.nested.prop = this.props.parse.nested.prop;` is illegal.

This is a usage question. We use github to track bugs in the react core, rather than usage questions. A more appropriate place for usage questions is StackOverflow, so I'm going to close out this issue, but feel free to continue the conversation on this thread or move the discussion over to StackOverflow.

**Comment by Voronar** [comment]
How to pass nested properties without a manual mutation of `props`?
For example:
```javascript
Component.defaultProps = 
{
  nested:
  {
    prop1: "default",
    prop2: "default"
  }
};

const props = 
{
  nested:
  {
    prop1: "value"
  }
};

let component = <Component {...props}/>;
```
Guide to code above JSX spread attribute feature just override `props.nested` and I will lose default nested properties. But it is not that I need.

**Comment by Voronar** [comment]
Moved to [StackOverflow](http://stackoverflow.com/questions/36265556/how-to-pass-nested-properties-with-spread-attributes-correctly-jsx).

**Comment by gaearon** [comment]
:+1: Thanks! We don’t have the bandwidth to answer all questions here so StackOverflow is a better place for this.
