### ISSUE TITLE
Attract more contributors by sharing first contribution stories

### ISSUE THREAD

**Issue by omidfi** [facebook/react#6346]
Dan Abramov asked "what is the main reason holding you back from contributing to react?".
So far 52% of the answers are: 
Code is not approachable.

While not directly related, but I think if current contributors shared their stories of their first contributions to react, explaining why and how they got involved would be encouraging for others. 

It can even be linked to in the official docs.

**Comment by dmitry-smirnov** [comment]
#6335

**Comment by gaearon** [comment]
Thanks for the idea! As I get closer to #6335 I’ll keep your suggestion in mind and maybe make it a little more personal.
