### ISSUE TITLE
Warn when using overlapping styles (e.g. border and borderBottom)

### ISSUE THREAD

**Issue by gaearon** [facebook/react#6348]
# This "good first bug" is taken by @YongPilMoon. Don't work on it unless that's you!

This has been discussed a few times before but I don’t think there was any conclusion, and PRs intending to solve the issue were not merged for various reasons.

I would like to close those PRs as outdated, and reboot the discussion about this.
Performance considered, the conclusion from @sebmarkbage and @syranide seems to be:

> We should consider not allowing conflicting style rules at all.

— https://github.com/facebook/react/pull/2013#issuecomment-57338177

> IMHO, all things considered it's better to just disallow overlapping and warn in dev.

— https://github.com/facebook/react/pull/4661#issuecomment-132996649

Radium by @ianobermiller came to the same conclusion in https://github.com/FormidableLabs/radium/issues/95 but there was some backlash afterwards. React Native seems to allow style expansions but only for a few attributes (e.g. `margin` and `padding`, but not `border`).

I’m closing old pull requests about this, and creating this issue to track implementation of the behavior we seem to agree upon: we should warn in `__DEV__` when `border` and `borderBottom` are used at the same time. We can discuss more specifics (should either be ignored? should we allow a few whitelisted properties but warn for others?) in this issue.

As a migration strategy, we can suggest people to use something like https://github.com/ActionIQ/style-builder if they really need those shortcuts. It’s also something we’ll need to decide upon when implementing integrated styling.

---

Related issues:
- #2231
- #2407
- #5030
- https://github.com/FormidableLabs/radium/issues/95

Related PRs:
- #2013
- #4661

**Comment by mattborn** [comment]
@gaearon Thank you for resurfacing this! Crazy that it has been a year since I opened the Radium issue.

I like the idea of warning about shorthand properties like `border`, but not `borderBottom`. There shouldn’t be any surprises when merging style objects using the longer property names.

Question. Is the intent of this issue to address only the analysis of individual style objects or is there also a desire to analyze and warn about possible collisions of properties that are conditionally applied?

**Comment by gaearon** [comment]
>Question. Is the intent of this issue to address only the analysis of individual style objects or is there also a desire to analyze and warn about possible collisions of properties that are conditionally applied?

Not sure I understand the question, can you elaborate?

**Comment by mattborn** [comment]
Sure. If it is invalid to have both `border` and `borderColor` on the same element, then it makes sense to warn about this. In my experience, this combination is easy to avoid, but it is more difficult to anticipate and debug when styles are being applied dynamically (conditional logic based on props or state, media queries, Radium, etc.) or passed down as props and merged with lower order style objects. If a warning for the shorthand `border` attribute exists when there are no other attributes that might affect the border involved, then the warning seems more like a dogmatic rule than a helpful debugging tool. However, if there is an attribute elsewhere that would affect the border involved and get merged at runtime, I’d like to be warned as early as possible as this is where things tend to break for me.

**Comment by gaearon** [comment]
Ah, good point. I’d probably warn only if we *know* the styles overlap but I’m not sure how easy it is to tell. I haven’t thought about it much and I don’t have a good solution.

**Comment by jimfb** [comment]
@gaearon An alternate solution that I like better is to use csstext as per https://github.com/facebook/react/issues/5397, which IIRC cleanly solves a superset of these issues.

**Comment by Aweary** [comment]
What about situations where a third-party component defines styles and allows overrides? Say a component defines its own `border` style and I want to just override the `borderBottom` style?

**Comment by rtsao** [comment]
I've started working on dead-simple helper functions to convert shorthand properties to longform (among other things): https://github.com/rtsao/lostyle/tree/master/src

**Comment by sophiebits** [comment]
This is super unpredictable and confusing and I just ran into this. Maybe we could at least warn on updates when we know it's problematic? That is, if we go from {background: a, backgroundSize: b} to {background: c, backgroundSize: b}, warn that backgroundSize is being overridden. We can know this from the property enumeration order.

**Comment by supertinou** [comment]
@sophiebits, I am happy to work on this one :)

**Comment by sophiebits** [comment]
@supertinou It's yours!

**Comment by craigkovatch** [comment]
Just hit this and was indeed surprised and confused by it.

**Comment by sophiebits** [comment]
@supertinou Just wanted to check if there's anything I can help you with on this.

**Comment by mirkojotic** [comment]
@sophiebits Hi I don't want to step on anybodies toes :D but I've taken a look into this issue, replicated it and would love to take a stab at it but I don't know if @supertinou is still working on it.

**Comment by giuseppeg** [comment]
I made a codesandbox to recap/explain what is going on https://codesandbox.io/s/ojrq4wnrj5 @gaearon / @sophiebits let me know if I forgot something or misunderstood.

**Comment by giuseppeg** [comment]
I made a sandbox to recap/explain what is going on https://codepen.io/giuseppegurgone/pen/mjKbmq?editors=0010 @gaearon / @sophiebits let me know if I forgot something.

**Comment by sophiebits** [comment]
@mirkojotic Still interested?

**Comment by YongPilMoon** [comment]
Can i take this one??

**Comment by sophiebits** [comment]
All right @YongPilMoon, it's yours.

**Comment by sophiebits** [comment]
Adding a note here: *removing* a property can also trigger this bug. https://stackoverflow.com/q/52636618/49485

**Comment by gaearon** [comment]
The warning is out in 16.13.
https://reactjs.org/blog/2020/03/02/react-v16.13.0.html
