### ISSUE TITLE
Remove ReactCurrentOwner

### ISSUE THREAD

**Issue by gaearon** [facebook/react#6350]
From what I remember from Twitter conversations with @sebmarkbage, it is problematic for several reasons, and we intend to remove it at some point. There are a few problems related to that. I’m not sure whether we have a solution for those:
- [ ] It is used by our warnings and profiler (even the new one) for more helpful messages
- [ ] It is used for string refs (we need to deprecate them?)
#4174 started work on this but it’s outdated. We try to avoid stale PRs, and they don’t give much context anyways, so I’m creating this issue to track work on this instead.

**Comment by gaearon** [comment]
Not doing this.

**Comment by NE-SmallTown** [comment]
@gaearon Would you mind add some tips/reasons or explain why here?
