### ISSUE TITLE
React appends <style> to <head> by default, resulting in empty duplicate

### ISSUE THREAD

**Issue by whynot123** [facebook/react#6358]
is this by design/necessary?
seems inconsistent, since it does not append `meta` or `title`, etc to `head`, & results in empty duplicate

**Comment by gaearon** [comment]
Can you please provide a JSBin replicating the issue?

**Comment by whynot123** [comment]
sorry, bug was caused by browser plugin

**Comment by gaearon** [comment]
Thanks for taking time to investigate!
