### ISSUE TITLE
Text components in ReactTransitionGroup give "Element type is invalid"

### ISSUE THREAD

**Issue by spicyj** [facebook/react#6365]
```
<ReactTransitionGroup>Welcome to React</ReactTransitionGroup>
```

(http://react.jsbin.com/towaxoqaya/edit?html,js,output)

throws

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ReactTransitionGroup`.

Not sure what this _should_ do, but at the very least the error message is terrible.

**Comment by devinargenta** [comment]
`var TG = 'react-addons-css-transition-group';` fixes this in your example, as far as I can tell.

**Comment by devinargenta** [comment]
I think you want to use React.addons.CSSTransitionGroup instead of React.addons.TransitionGroup, which, in your example will then give you the proper errors for transition name, etc.

http://react.jsbin.com/mitidikaqo/edit?html,js,console,output

**Comment by spicyj** [comment]
@devinargenta Thanks for the comment. This is still a case that ReactTransitionGroup shouldn't error on (or at least, should give a clear error for). TransitionGroup and CSSTransitionGroup are related but different. (Sorry if the terse bug report was confusing – when reporting bugs on projects I work on I often don't explain myself fully for someone without context and use the issue almost as notes for myself.)

**Comment by gaearon** [comment]
We are not maintaining TransitionGroup in this repo anymore.
If there are still issues with it, I encourage you to file them in https://github.com/reactjs/react-transition-group.

**Comment by gaearon** [comment]
Filed as https://github.com/reactjs/react-transition-group/issues/45.
