### ISSUE TITLE
dangerouslySetInnerHTML issue

### ISSUE THREAD

**Issue by vaselok** [facebook/react#6378]
Hello, I caught the following issue today: 
`return dangerouslySetInnerHTML={{ __html: item.Text }} key={'conditions-' + index} />;`
and if in `item.Text` I have the following: `"< strong >< p >bla bla bla< /p >< /strong > Beschikbaarheid Bij het selecteren van een vlucht word je vlucht nog niet meteen geboekt. Je vlucht wordt definitief bevestigd na een succesvolle betaling op onze website."`,

I get the next one result: 
< p data-reactid=".1qcvo80rke8.2.2.0.1.0.$conditions-0">< strong >< /strong >< /p >
< p >< strong >Vluchtdetails en voorwaarden< /strong >< /p >
 Beschikbaarheid Bij het selecteren van een vlucht word je vlucht nog niet meteen geboekt. Je vlucht wordt definitief bevestigd na een succesvolle betaling op onze website. 
< p >< /p >

As you can see, <p> isn't rendered one inside another.

But If I change the < p > to < div > in the `item.Text`, I get right markup with correct rendered data. I tried to add key, className to < p >, but it doesn't help

**Comment by goto-bus-stop** [comment]
A `<p>` tag cannot appear inside another `<p>` tag.

An html file like:

```html
<p>
  outer
  <p>inner</p>
</p>
```

Results in:

![DOM](http://i.imgur.com/LTuGZ2q.png)
