### ISSUE TITLE
ReactTestUtils.Simulate logs unexpected console error

### ISSUE THREAD

**Issue by harboecp** [facebook/react#6379]
To reproduce, open http://jsfiddle.net/0jjnaghw/
Error is logged to browser dev tools (in Chrome & Firefox, somehow not in Safari).

Happens on v15.0.0-rc.2 and on latest master version.

The assignment of additional event data to the newly created SyntheticEvent triggers a console error:
https://github.com/facebook/react/blob/3a4e1dbb5b2957875cab6af11a5e5934e125a0d8/src/test/ReactTestUtils.js#L502

> "Warning: This synthetic event is reused for performance reasons."

**Comment by zpao** [comment]
Thanks for reporting. We'll get this fixed.

**Comment by gaearon** [comment]
Are we not checking for unexpected warnings in tests? Should we? Curious how this crept in unnoticed.

**Comment by zpao** [comment]
node doesn't support Proxies so none of that code is actually getting tested :/ Even running with `--harmony` flag (which we do at least with `grunt test`) doesn't enable it since it's "in progress".  We could probably run with `--harmony_proxies` to force it on.
