### ISSUE TITLE
flattenChildren(...): Encountered two children with the same key.

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react#6390]
So I've been struggling trying to figure this out and nothing I can find helps. I've got a function that renders a component for every item in an array pretty much. It works perfectly fine except for the fact that it gives me a bunch of warnings all saying the same.
![screenshot from 2016-03-31 14-25-12](https://cloud.githubusercontent.com/assets/11371200/14189850/c53bb398-f74c-11e5-90cd-8e04bb8b786c.png)
These keys never change no matter what I try and set it to. Here is my code below: 

    function renderTimes(groupedRaces) {
      return Object.keys(groupedRaces).map((date) => {
        return (
          <div key={date}>
            <div style={styles.date}>{date}</div>
            {
              groupedRaces[date].map((race) => {
                return ( <TimeSlot key={race.id} race={race}/> );
              })
            }
          </div>
        );
      })
    }

As you can see, I set the key for each component but it doesn't even use it. I know for a fact that {race.id} is unique too. I've tried adding and removing the keys from all the elements in my code as well as setting them to different values but it still always prints out 4 warnings with these as the keys:
`
.0:$84414
.0:$84415
.0:$84416
.0:$84417
`
Also using React 0.14.6 if that could make a difference

**Comment by jimfb** [comment]
Can you provide a simplified jsfiddle that demonstrates the issue?

**Comment by RyanMitchellWilson** [comment]
Thanks for the quick response but we actually figured it out. Turns out it was happening in another place all together but a warning message in our tests was pointing somewhere else.
