### ISSUE TITLE
allow arrays for CSS properties that can take multiple values

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/react#6393]
It would be nice if people were able to write:
```
const color = 'blue';
const style = {
    padding: [5, 10, 15, 20],
    border: [2, 'solid', color],
}
```

**Comment by zpao** [comment]
Thanks for the idea. For the time being (if/when there's a js styles approach we support in core), we're going to just stick with our current approach to styles and not add more magic here. I do see the convenience though and there's a chance we end up doing something similar. cc @vjeux as you think about this stuff.

**Comment by Aweary** [comment]
@kevinbarabash you could always handle this in userland and create a repo that can parse those values before passing them to React.

```js
const color = 'blue';
cosnt style = someParsingUtility({
  padding: [5, 10, 15, 20],
  border: [2, 'solid', color']
});
```

**Comment by kevinbarabash** [comment]
Cool.  I'll try to get it into aphrodite, https://github.com/Khan/aphrodite/issues/36.
