### ISSUE TITLE
Proposal: externalize inline-styles

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#6395]
From your meeting notes:

> There are tons of different ways to render JS styles (see Radium, CSS Modules, React Native Web, etc)

I see tremendous opportunity here for powerful third-party stylesheet packages. And without burying the lead too much: 

**What if React DOM didn't manage inline styles at all?** An external inline-style library would be responsible for producing a valid `toString()` response to send into the `style` prop of the renderer. Maybe if the renderer was expecting an object form, you could also create an expectation around `valueOf()` returning a primitive object.

This could look something like:

```javascript
import React from 'react'
import Stylesheet from 'my-stylesheet-library'

var stylesheet = Stylesheet.create({
  color: 'blue',
  fontSize: 12
})

console.log(stylesheet.toString()) // => "color: blue; fontSize: 12px;"

export default function () {
  // Here, ReactDOM will call `toString()` on stylesheet to produce a valid style
  // attribute. All invariants, warnings, and errors associated with the stylesheet 
  // are handled by the library.
  return (
    <div style={ stylesheet }>
      Externally managed inline styles FTW!
   </div>
  )
}
```

React could provide an add-on that maintains the existing functionality to get things started - similarly with how you all have shifted `immutability-helpers` off to the community. However it puts React in a place where:

1. Inline stylesheet package maintainers have greater control. 
2. Static inline styles can be compiled ahead of time.
3. React does not have to spend dev effort on maintaining inline style support
4. Those not heavily using inline styles can use template strings and benefit from a lighter weight React (though this isn't really a huge deal)

**Comment by gaearon** [comment]
We tried to make it clear from the notes that no specific implementation is in the works right now. The exploration is targeted at looking if either of these approaches, or a combination of them, can work at Facebook scale without regressing performance or other important characteristics.

So right now the possibility of React having some built-in support for managing inline styles is **purely hypothetical**. Before we get into any API implications, we need to learn about the actual challenges posed by different approaches. So it’s not really about “which one of these libs should we build into React DOM” but about “which of these approaches can work at Facebook scale, if any?”

We will share our findings when/if we have some tangible results, but at the moment we don’t, so it’s too early to discuss how specifically we want to handle inline styles, and what should be delegated to third party packages.

**Comment by nhunzaker** [comment]
Works for me.

**Comment by gaearon** [comment]
Feel free to bring it up again if we ever implement this though :+1:

**Comment by nhunzaker** [comment]
For what it's worth, the thought that Facebook was working on a big inline-style library that might impede the efforts of a third-party library like Radium never crossed my mind. I'm much more interested in the novelty of simply calling creating a convention where `toString()` is called on whatever is passed to style, letting the specific stylesheet implementation itself do all the work.

Looking forward to seeing what you all find

**Comment by gaearon** [comment]
In this case it’s a little more involved (i.e. an implementation might both want to return either a bunch of classes or a bunch of styles, or both). We don’t currently allow string styles although @jimfb expressed some similar thoughts in #5397.

cc @vjeux as he’s the one looking into this stuff.
