### ISSUE TITLE
Documentation regarding refs

### ISSUE THREAD

**Issue by dukedougal** [facebook/react#6409]
It would have saved me alot of time if the documentation about refs made it clear that they really only work for accessing one child from one parent.

Unless I am wrong about my understanding it would be good if all the documentation that dealt with refs explained this.

**Comment by jimfb** [comment]
A parent can access as many children as it wants (using multiple callback refs).  A single child can be referenced by as many parents as want (by wrapping/chaining callback refs, such that when a ref fires then the latest parent calls the ref of any other parent that was already listening).  So there is no such restriction for callback refs.  That restriction does exist for string refs, but string refs are documented as legacy.

**Comment by lijunle** [comment]
@jimfb I think you will get into memory leak with your refs array.

> string refs are documented as legacy and should be avoided.

Really?

**Comment by goto-bus-stop** [comment]
@lijunle 

```
<input ref={input => this.emailInput = input}  />
```

**Comment by jimfb** [comment]
@zpao @gaearon Is there anything actionable here, or do we just want to close it out.  If actionable, any suggestions/bikeshedding on wording?

**Comment by gaearon** [comment]
I’d close this because I’m not sure what exactly could be improved. If there are any specific suggestions, they can be sent as a PR.
