### ISSUE TITLE
Release v15

### ISSUE THREAD

**Issue by zpao** [facebook/react#6417]
There's just one thing left on the blocker list, which should get merged shortly. Then we're code complete. Everything else we were considering wasn't a regression so it got booted and we can catch up later.

## Real Code Changes
- [x] remaining regression with simulating events (#6380)
- [x] fix failing test / fallout from #6228 (#6426)
- [x] upgrade deps (#6413)

## Docs
- [x] update properties & attributes
- [ ] Removed deprecated methods
- [ ] Add any new deprecation notes
- [x] Add notes for potentially confusing version mismatches (eg, returning null from a functional component)

## Actual Release
- [x] create branch (`15-stable`)
- [x] shrinkwrap
- [x] update changelog (sync with blog post)
- [x] publish
- [x] Update travis to build docs from new branch (part of release but after everything is published)

## Post-release
- [x] update the tutorial repo
- [x] update fiddles
- [x] ensure master has release resource synced

**Comment by zpao** [comment]
Note, we're going to break React Native init if we ship to latest until https://github.com/facebook/react-native/pull/6846 is shipped so that may impact us. We can always ship and just leave the `latest` npm tag pointing at 0.14.8 if we're ready to go before that's out.

**Comment by ide** [comment]
@zpao thanks. I don't want to hold back the React 15 release too much so we'll get a new RN release out shortly =)

**Comment by kachkaev** [comment]
Hey guys,
What about a release in https://github.com/facebook/react/releases ?
Just noticed that v15.0.0 is missing there.

**Comment by gaearon** [comment]
I added one, thanks.

**Comment by geekingreen** [comment]
Just curious should this release be 0.14.x -> 0.15.0 not 0.14.x -> 15.0.0?

**Comment by zpao** [comment]
Nope, 15 is correct. http://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html
