### ISSUE TITLE
callback in setState() second parameter cannot get mouse-click's event handler

### ISSUE THREAD

**Issue by josephMG** [facebook/react#6422]
Hi all,

I use setState in a click function, and I pass a callback function to second parameter. Please look at [https://jsfiddle.net/009memtb/](https://jsfiddle.net/009memtb/), In the callback function, I cannot get event handler, is it reasonable?

I try to pass event handler into callback like [https://jsfiddle.net/ozagLubw/2/](https://jsfiddle.net/ozagLubw/2/), but the state is wrong. 

How can I get event handler and right state in setState callback function correctly?

thank for your help in advance

**Comment by andreypopp** [comment]
Events are pooled and reused, thus after leaving event handler they are returned to a pool and all attributes are nulled. To use event after leaving event handler you need to persist it: `e.persist()`, see: https://jsfiddle.net/009memtb/1/

**Comment by jimfb** [comment]
Thanks @andreypopp, exactly correct.

@josephMG Just FYI, Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core.

**Comment by josephMG** [comment]
@andreypopp Thanks for your answer. It's help me a lot.

@jimfb Sorry I use wrong type, and thank your information. I'll keep that in mind.
