### ISSUE TITLE
Updates grunt

### ISSUE THREAD

**Issue by alexlur** [facebook/react#6433]
Specifically, `grunt` has released their first 1.0 update, which [bumps lodash dependency](https://github.com/gruntjs/grunt-legacy-util/blob/master/package.json#L31) from 0.9.2 to 4.3.0.

**Comment by zpao** [comment]
I looked into this the other day but it's not clean at the moment while we use npm2 and some of the plugins we use haven't released updates with 1.0 compat/peerDeps.

0.4 has worked well for 3 years so I'm not in a rush to change it. We will probably end up switching to gulp to align with many of our other projects and use more shared infra.

**Comment by flarnie** [comment]
Closing this since we are working on removing grunt anyway - see https://github.com/facebook/react/pull/9147

**Comment by gaearon** [comment]
Did this in https://github.com/facebook/react/issues/9327 after all.
