### ISSUE TITLE
Debugging structure & Automatic cleanup for unstable_renderSubtreeIntoContainer

### ISSUE THREAD

**Issue by jhicken** [facebook/react#6435]
We are implementing unstable_renderSubtreeIntoContainer to use custom components. So Some things discussed during the initial PR would be pretty fantastic. Specifically these things.

1) Debugging structure. E.g. tooltips shouldn't show up in the top level of React DevTools but rather in their respective subtrees.
2) Automatic clean up if the parent tree is unmounted.
3) Event bubbling.

https://github.com/facebook/react/pull/3640#issuecomment-92533429

Are these on the back log? I didn't see any issues about them. And it looks like all unstable_renderSubtreeIntoContainer is doing at the moment is passing in the proper context.

**Comment by jimfb** [comment]
All of those things would be great items to have.  This function is not a priority for us internally, so we aren't focused on it at the moment.  @jhicken We'd gladly accept a pull request for any of those features.

**Comment by jhicken** [comment]
Cool I'll see If I can find some time to dig into this.

**Comment by gaearon** [comment]
https://reactjs.org/docs/portals.html

**Comment by gaearon** [comment]
https://reactjs.org/docs/portals.html
