### ISSUE TITLE
Cursor jumping to end of controlled input in some browsers

### ISSUE THREAD

**Issue by zpao** [facebook/react#6445]
Appears to be working in Firefox but at least Chrome & Safari are broken. Should be a really recent regression so very few possible changes to blame...

Easiest repo: the todo list on our homepage.

**Comment by rclai** [comment]
Just a heads up but this still seems to be an issue even on 15.4.1. I haven't been able to isolate this yet because it looks really tricky, but I was wondering if anyone is still dealing with this problem?

**Comment by spicyj** [comment]
I haven't seen anything.

**Comment by deathgaze** [comment]
I'm still seeing this issue.

**Comment by spicyj** [comment]
Please open a new issue with a simplified repro case if you're still seeing this!
