### ISSUE TITLE
Typing in middle of controlled text field jumps to end

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#6446]
Repro:
Go to http://facebook.github.io/react/
Scroll to TODO example
Type anything into the input field
Click in the middle of the text and type another character. Notice the cursor jumps to the end of the text field.

**Comment by Daniel15** [comment]
@zpao and I filed an issue at the same time, closing in favour of #6445

**Comment by zpao** [comment]
Beat you to it. #6445
