### ISSUE TITLE
Rendering component into a shadow root in React 15.x

### ISSUE THREAD

**Issue by Wildhoney** [facebook/react#6456]
In `0.14` it was [quite easy](https://github.com/Wildhoney/Keo/blob/master/docs/SHADOW_DOM.md) to render a component into a shadow root &mdash; this was due to the [`nodeType` check in `ReactDOMComponent`](https://github.com/facebook/react/blob/0.14-stable/src/renderers/dom/shared/ReactDOMComponent.js#L302-L304).

However you'll notice that in `15.0` that [check has been completely removed](https://github.com/facebook/react/blob/15-stable/src/renderers/dom/shared/ReactDOMComponent.js#L216) and as such will **always** bind events to the `#document` element &mdash; the `ownerDocument`, rather than the `#document-fragment`.

As the events that cross the shadow boundary are retargeted to appear as though they're from the shadow host instead of the internals, React's event delegating fails to invoke the event function. In the case of `0.14` the event delegation on the `#document-fragment` correctly handled the event, as it was able to [inspect the `listenerBank`](https://github.com/facebook/react/blob/15-stable/src/renderers/shared/event/EventPluginHub.js#L128-L131) before retargeting was performed &mdash; any further propagation of the event would have been unnecessary.

Now I realise React doesn't support Shadow DOM natively &mdash; however it seems as though we've taken a little step back, especially with Angular 2 and its Shadow DOM support on the horizon. I'm merely wondering as to the rationale behind the removal of the `ownerDocument` check, and whether we'd be happy to add it back in?

<sup>(For those people who dislike the [CSS Module](http://glenmaddern.com/articles/css-modules) approach)</sup>

**Comment by jimfb** [comment]
@Wildhoney Yes, we should probably add it back in.  Without having looked into it deeply, my guess is that the breakage was just an oversight.

**Comment by Wildhoney** [comment]
Agreed &mdash; I'll take a look. Thanks :+1: 

One quick question, however &mdash; otherwise I'll investigate myself &mdash; what is the easiest way to obtain the container (in this case the `#document-fragment`) from [`inst`](https://github.com/facebook/react/blob/15-stable/src/renderers/dom/shared/ReactDOMComponent.js#L215)?

**Comment by jimfb** [comment]
I'd look at nativeContainer and topLevelWrapper; the info might need to be added if it isn't already available.  I think @spicyj wrote the nativeContainer code, so he might know.  Otherwise, it'll require a bit of investigation.

**Comment by jimfb** [comment]
Fixed in #6462
