### ISSUE TITLE
Removal of React.__spread has broken compatibility with TypeScript and older Babel transpilers

### ISSUE THREAD

**Issue by BernieSumption** [facebook/react#6457]
If you use TypeScript or an older version of babel, React 15.0.0 yields errors "React.__spread is not a function".

See this issue: https://github.com/Microsoft/TypeScript/issues/7959

Applications can monkey patch a backwards compatible React.__spread function, but it would be preferable for React to come with a compatibility shim function.

**Comment by gaearon** [comment]
We are bringing it back until React 16. 
The fix will be out in 15.0.1 today.
https://github.com/facebook/react/pull/6444
