### ISSUE TITLE
Can we try to auto-prefix something CSS attributes, like `transform`

### ISSUE THREAD

**Issue by haohcraft** [facebook/react#6464]
According to the test [here](https://github.com/facebook/react/blob/eb85b7b2c989faeb6ed8cd787cf67bd5f6d3ec7d/src/renderers/dom/shared/__tests__/CSSPropertyOperations-test.js#L176), we need to manually add the prefix for `transform` when inline this attribute.

In my case where implementing non-trivial graph animation/interaction UI and I am programmatically calculating the value for `translate`, I have to manually add the prefix every time. 

Is it possible to delegate this tedious task to React itself ?
If so, can anyone point me to the related code, I will try to make a PR for this.

**Comment by zpao** [comment]
We don't intend on making React too knowledgeable about vendor prefixing. As much as possible that belongs at a level above React. There are libraries out there that can add the appropriate prefix to your style values (I don't know one off the top of my head but they exist or you could write one relatively easily).

```js
// Instead of this
var myStyle = {translate: ...}
return <div style={myStyle} />

return <div style={prefixStyles(myStyle)} />
```

**Comment by Aweary** [comment]
@haohcraft one option is [Radium](http://stack.formidable.com/radium/) supports automatic vendor prefixing 👍
