### ISSUE TITLE
use of template literals

### ISSUE THREAD

**Issue by sarbbottam** [facebook/react#6474]
Is there any code convention/reason for not using [`template literals`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) consistently?

**using template literals:**
```
$ git grep -e "\${" | grep '^src' | egrep -v 'test|__tests__|vendor'
src/isomorphic/classic/element/ReactElementValidator.js:      addendum = ` Check the top-level render call using <${parentName}>.`;
...
```

**using string concatenation:**
```
$ git grep -e "' + " -e " + '" | grep '^src' | egrep -v 'test|__tests__|vendor'
src/addons/transitions/ReactCSSTransitionGroup.js:  var timeoutPropName = 'transition' + transitionType + 'Timeout';
...
```

There are couple of more occurrences like
[`return prefix + key.charAt(0).toUpperCase() + key.substring(1);` ](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/CSSProperty.js#L63)

**Comment by keyanzhang** [comment]
I think someone from the team can give a much better answer, but @gaearon's explanation on avoiding stylistic changes in #6463 makes sense to me. Given that [babel](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-template-literals/src/index.js) transpiles template literals down to string concatenation, I guess it's more a matter of style/legacy.

**Comment by jimfb** [comment]
I think we generally prefer string concatenation (simpler), but it doesn't really make a huge difference one way or the other.

**Comment by takshch** [comment]
I have seen these string concatenation a lot of times.
To be honest, it looks very ugly to me.
![Screenshot from 2024-11-15 23-23-19](https://github.com/user-attachments/assets/52defd0a-b2df-4735-aece-92da83233f78)

Template literals are way better than these string concatenation.
@gaearon Can I refactor this everywhere in the codebase?
