### ISSUE TITLE
Don't warn about unitless 0

### ISSUE THREAD

**Issue by japgolly** [facebook/react#6476]
With React 15.0.1 I'm getting this warning:

```react-with-addons.js:21026 Warning: a `span` tag (owner: `unknown`) was passed a numeric string value for CSS property `padding` (value: `0`) which will be treated as a unitless number in a future version of React.```

While it generally makes sense, 0 should be allowed unitless like it is in the CSS spec.

**Comment by gaearon** [comment]
Yeah, I think this was fixed in #6458 and will get into one of the closer releases.

**Comment by jimfb** [comment]
Yes, closing as fixed.
