### ISSUE TITLE
Immediately setting a disabled attribute on form submit button using `setState` caused no form submission to take place

### ISSUE THREAD

**Issue by albertstill** [facebook/react#6477]
I have a form with a submit button. When the user clicks submit my `handleSubmit` function calls     `this.setState({ submissionTakingPlace: true })`, the re-render then sets a disabled attribute on the submit button. 

```
<button
 type="submit"
 onClick={this.handleSubmit}
 disabled={this.state.submissionTakingPlace}
>
```

In Chrome and Safari the network tabs shows that no POST request even starts? In Firefox the POST occurs. Note I have the same behaviour when I use a `<input>` over a `<button>`.

Here is a Codepen [example](http://codepen.io/anon/pen/GZQNZe). Issue occurs on the latest version of React 15.0.1.

Apologies if this is a browser quirk vs a React issue but me and a colleague were pretty confused by it.

**Comment by jimfb** [comment]
Sounds like a browser quirk.

```
<div id="container">
   <form method="get" action="http://www.example.com">
     <input type="text" name="foo" />
     <input type="submit" id="submit" onclick="document.getElementById('submit').setAttribute('disabled', 'disabled');" />
   </form>
</div>
```

Same behavior without React.
