### ISSUE TITLE
Add component instance to onSetState in ReactDebugTool

### ISSUE THREAD

**Issue by omerts** [facebook/react#6480]
Unless there is some other cleanway to sniff the state (without monkeypatching), it would be great to get the actual component instance which has raised the onSetState in ReactDebugTool.

**Comment by gaearon** [comment]
For the record, we plan to provide an official introspection API for this.
#6488 is the start of this.

What information would you like to extract about the instance that has been updated?

**Comment by omerts** [comment]
@gaearon, thanks waiting for the update
