### ISSUE TITLE
Unable to type Korean in input - v.15.0.1

### ISSUE THREAD

**Issue by carlsagan21** [facebook/react#6484]
Hi there, 
You might know, I guess, that there is an issue about typing Korean in the recent version.
The problem is when I try to type Korean, the letters are split.
Korean letters make group letters from element. for example group letters like
> 리액트(which means React)

is composed of

> ㄹㅣㅇㅐㄱㅌㅡ(sort of R, e, a, c, t) 

the first 2(ㄹㅣ) are put together and make the first group letter(리), and so on.

Before update, if I type `ㄹㅣㅇㅐㄱㅌㅡ` by order, it automatically put together to be `리액트`. It is possible because there is a rule to make them.

But now in v15.0.1 if I type `ㄹㅣㅇㅐㄱㅌㅡ`, it doesn't put together, so it shows `ㄹㅣㅇㅐㄱㅌㅡ`.

I tried uncontrolled input, that doesn't set it's value through `onChange & setState`, and I worked right. I guess the problem is in onChange & setState...

Korean is one of the biggest language in the world, about 12th. This issue make new version of React useless to every Korean user... I have to be fixed ASAP.

**Comment by zpao** [comment]
I noticed you closed this and changed the title. I just wanted to confirm that this is in fact fixed in 15.0.1 and was only an issue in 15.0.0.

**Comment by carlsagan21** [comment]
Thx;)
