### ISSUE TITLE
CSS Transition Group - peer dependencies error

### ISSUE THREAD

**Issue by monzerhijazi** [facebook/react#6485]
Hi, when I try installing react addons transition group I get a peer dependeincies error. I think its because transition group still depends on react-addons-clone-with-props while React now has React.createElement. Error below:

>npm i react-addons-css-transition-group
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodej
\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-addons-css-transition-gr
up" "--save"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDepen
encies requirements!
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-addons-clone-with-props@0.14.8 wants react@^0.1
.8
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.0.1 wants react@
15.0.1

**Comment by iamdustan** [comment]
`react-addons-css-transition-group` does not require `react-addons-clone-with-props`.
https://gist.github.com/iamdustan/5d61d3426dd57e25efbb931395afd773#file-package-json-L82-L84

Ensure that you don’t have that in your direct dependents or as a transitive dependency. `npm ls` should tell you which offending package is requiring it if it’s not from you package.json.

**Comment by monzerhijazi** [comment]
Yep, my mistake. Had to run `npm uninstall react-addons-clone-with-props --save-dev `
