### ISSUE TITLE
React 15 breaks server rendering check-sum

### ISSUE THREAD

**Issue by buzinas** [facebook/react#6487]
I'm developing an universal app with React, and after updating to v15.0.1, I started getting this error:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) ut class="md-input" name="txtCadmus" pat
>  (server) ut class="md-input" pattern="[0-9]*" nam

It seems to be some bug on V8 `Object.assign` reordering or something like that, but I'm not completely sure.

Tried to change a bunch of stuff (e.g: force both server and client to use a polyfill, or using Babel transform object-assign plugin), but nothing solved the problem.

Then, I uninstalled React 15.0.1 and installed 0.14.8 again, and the problem was gone.

Btw, it's pretty simple to simulate the issue:

**Code**

```javascript
ReactDOM.render(
  <input name="my-input" className="my-class" type="number" pattern="[0-9]*" />, document.querySelector('#main')
);

console.log(document.querySelector('#main').innerHTML)

console.log(ReactDOMServer.renderToString(
  <input name="my-input" className="my-class" type="number" pattern="[0-9]*" />
));
```

**React 15 not working**

![15 0 1](https://cloud.githubusercontent.com/assets/7298695/14435792/ea6e797e-ffef-11e5-8414-4445166181d8.png)

**React 0.14.8 working as expected**

![0 14 8](https://cloud.githubusercontent.com/assets/7298695/14435791/ea65117c-ffef-11e5-863c-bd70745083ba.png)

**Comment by zdila** [comment]
I have the same issue. Some compared server/client elements have same but reordered attributes and React treat them as different. Strange is that in my case ordering changes not before first page reload. Very first rendering is OK.

**Comment by gaearon** [comment]
Yes, please track this in https://github.com/facebook/react/issues/6451.
