### ISSUE TITLE
TestUtils.findAllInRenderedTree is not iterating through all components since React 15.

### ISSUE THREAD

**Issue by r-tock** [facebook/react#6489]
Most of our tests rely on this. I went through a debugger and stepped through the callback function. 

Only the components `Foo` and `Bar` are captured any sub-component under `<Bar/>` is not coming in the callback.

```
var component = ReactDOM.render(<Foo><Bar/></Foo>, container);
TestUtils.findAllInRenderedTree(component, child => console.log(child));
```

**Comment by gaearon** [comment]
Sorry about this. Can you check if this still reproduces with React 16?

**Comment by gaearon** [comment]
Closing per lack of response.
