### ISSUE TITLE
RenderToStaticMarkup

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/react#6492]
In v15, you said that 'renderToStaticMarkup' was out, this is still in the docs describing you use this in the internal build. Does this still apply? [ Link to docs](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostaticmarkup) 

This is the blog post that made me suspicious: [ Blog post ](https://facebook.github.io/react/blog/#removed-deprecations)

**Comment by cody** [comment]
Everything seems to be correct. `React.renderToStaticMarkup` has been removed. It was replaced with `ReactDOMServer.renderToStaticMarkup`, that is what you link to in the docs.

It is a bit confusing, but here is explained why they did it:
https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html#two-packages

**Comment by ev1stensberg** [comment]
Forgot the DOM in the name there. About the confusing part, it's not confusing at all, just read it wrong. Thanks for the fix though!
