### ISSUE TITLE
15.0.1 breaking devtools

### ISSUE THREAD

**Issue by tgoldenberg** [facebook/react#6497]
I am using React `15.0.1` with Meteor. When I open the Chrome console, I get a `Waiting for the roots to load.. to reload the inspector click here`. This has no effect. 

I like that the `data-reactid`s are gone, but not having the devtools inspector is a huge loss. Any word on this?

**Comment by zpao** [comment]
I'm going to close this out and just track in https://github.com/facebook/react-devtools/issues/357. If there's something specific React needs to do that comes out of that investigation we can file something here.
