### ISSUE TITLE
installing react-addons best practices?

### ISSUE THREAD

**Issue by seansfkelley** [facebook/react#6498]
The various React addons express a peer dependency on their matching React version. You can write a React component library that runs with multiple versions of React but depends on some specific addons as an implementation detail:

```
{
  "name": "my-awesome-library",
  ...
  "dependencies": {
    "react-addons-update": "^0.14.0 || ^15.0.0"
  },
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.0"
  }
}
```

If you consume this library in a host environment that uses react@14, npm will still helpfully install the latest version of react-addons-update, which of course peer-depends on react@15, causing rather confusing UNMET PEER DEPENDENCY warnings since I, the consumer, am only looking around the `peerDependencies` block for version issues.

So my question is this: what are best practices for a library in this situation? Should I declare react-addons-update as a peer dependency, meaning that my consumer has to personally install not just React itself but also every react-addons-* that any of their dependents use? Seems annoying to my consumer and also a sort of an abstraction break for the sake of version matching.

Perhaps react-addons-* should be more independently versioned so they accept multiple versions? Or maybe not declare a peer dependency on React if they don't actually need it (like for react-addons-update, which only uses a couple of the small, non-React-core utilities)?

**Comment by gaearon** [comment]
In a perfect world `react-addons-update` shouldn’t peer depend on React at all.
Relevant to https://github.com/facebook/react/issues/6490.

**Comment by gaearon** [comment]
In the meantime you can use https://github.com/kolodny/immutability-helper instead as a drop-in replacement.

**Comment by jimfb** [comment]
I'm going to close this.  Immutability is a good solution for this specific case, and https://github.com/facebook/react/issues/6490 tracks the wider issue.  Feel free to continue the discussion on this thread.

**Comment by seansfkelley** [comment]
I didn't realize #6490 was already tracking that change. I think that's probably the best way to tackle this problem in the long run. 

Until #6490 happens, I think this is still an open question. I meant this ticket to be an example of a broader question; while alternate implementations of react-addons-update are handy, I still have instances where I use react-addons-shallow-compare and others. Or even have dependents of dependents out of my control that use those addons. 

Some further thoughts on this topic: assuming that my library supports multiple versions of react (which I would very much like to) and that it uses some react-addons (which I would also like to), it seems my only choices are to warn my dependents about potential peer dependency mismatches (if I have a non-peer dependency on a react-addon) or to force them to install the react-addon on my behalf (by listing it as a peer dependency). As far as best practices go, I'm leaning towards the former, because while it generates some potentially confusing warnings, it should generally work without any further involvement.

**Comment by gaearon** [comment]
>warn my dependents about potential peer dependency mismatches (if I have a non-peer dependency on a react-addon)

This won’t work in npm 2. Additionally, even with npm 3, this will cause multiple copies of React to be installed in case of version mismatch which will likely break the addons that *need* to depend on React anyway. And those that don’t need to, like `react-addons-shallow-compare`, shouldn’t depend on it in the first place, as I said above.

>or to force them to install the react-addon on my behalf (by listing it as a peer dependency).

I think this is the most sensible solution in the present circumstances. It’s not ideal but at least npm 3 users will never get a duplicate React because of this.
