### ISSUE TITLE
React css manual

### ISSUE THREAD

**Issue by EasonWang01** [facebook/react#6499]
Hi,is there a manual that detailed about React style?

Because I found the offical doc is not explicate it very well.

For example:
`flex:1` can directly use in a component,but in html css, it supposed a flex attribute in its parent.

but react doc seems not explain it.

**Comment by jimfb** [comment]
I'm not sure what you mean when you say:
 > flex:1 can directly use in a component,but in html css, it supposed a flex attribute in its parent.

Can you elaborate?  Perhaps with an example?

**Comment by EasonWang01** [comment]
Thanks for reply.

I was saw this https://github.com/facebook/css-layout/issues/57.

And don't know what css attributes is support in react.

**Comment by iamdustan** [comment]
css-layout is a different project and not used by React directly, though ReactNative uses it for supporting CSS in native apps. That said, this sounds like a misunderstanding of how [flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes) the CSS standard works.

For that I would recommend visiting the above link and the following resources:

* https://flexbox.webflow.com/
* http://flexboxgame.com/
* http://learnlayout.com/flexbox.html

**Comment by zpao** [comment]
Going to close out since this appears to be a misunderstanding. If you have issue with `flex` in regards to React Native specifically, I would ask in their repository.
