### ISSUE TITLE
Errors when using HOC are not helpful

### ISSUE THREAD

**Issue by natew** [facebook/react#6522]
When you put an object into a component that has been decorated, say by a HOC called "StyledComponent", you get an error like this:

```
Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {title, uid}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `StyledComponent`.
```

Problem is, many components are decorated like this. So in effect this error does nothing to help me figure out where the error came from.

I would like to see a few things. First step I think would be to show the full path:

```
Check the render method of Main > SubComponent > StyledComponent > ...
```

Second would be to have integration with the React devtools so you could actually click and see the highlighted path/component.

Final would be, if possible, to show the tagname that contained the object as well.

Just brainstorming for a better React!

**Comment by natew** [comment]
Should mention, we are cloning elements in StyledComponent. Now I think I realize why this error may be tricky.

Is there a way in 0.15 to catch errors in my StyledComponent decorator and add some information to them?

**Comment by jimfb** [comment]
Are you using decorators/inheritance, or HOC?  Higher order components render their children (as per https://goo.gl/vbSrxD) and so they shouldn't be a problem / shouldn't hide the component name.

https://github.com/facebook/react-devtools/issues/308 may be relevant to you.  You might be able to achieve what you're looking to do by setting displayName.

Regardless, this is mostly a usage question.  We use github issues to track bugs in the React core.  Usage questions are better addressed on StackOverflow.  For this reason, I'm going to close out the issue, but feel free to continue the discussion on this thread or move it over to StackOverflow.  To the extent that it's a feature request, it is tracked in other places like https://github.com/facebook/react-devtools/issues/308.
