### ISSUE TITLE
ReactDOM.render( <comp />, document.getElementById('target') ) Throws error _registerComponent(...)

### ISSUE THREAD

**Issue by pricetula** [facebook/react#6537]
When i use  ReactDOM.render( <AppLayout />, document.getElementById('render-app') ); on meteor start up to set up a render target like:-

import React from 'react'
import ReactDOM from 'react-dom';
import AppLayout from '../../ui/layouts/default'
Meteor.startup(
  function(){
  ReactDOM.render( <AppLayout />, document.getElementById('render-app') );
});

An error is thrown
Error: _registerComponent(...): Target container is not a DOM element.

(Using Firefox browser)

**Comment by jimfb** [comment]
Can you provide a simple jsfiddle (ideally without meteor) that demonstrates the issue?

**Comment by pricetula** [comment]
Upon close inspection of the dom, turns out react adds <div id="react-root"></div> by default.

**Comment by gaearon** [comment]
@pricetula Hi! I hope you don’t mind that I formatted your messages so the code is highlighted. You can include small blocks in backticks (\`), and large blocks between triple backticks: \`\`\`js and \`\`\`. This helps everyone read the issue a little easier in the future. Cheers!

**Comment by pricetula** [comment]
@gaearon LoL as you might have noticed I am new in github. Thank you.

**Comment by gaearon** [comment]
@pricetula No problem. You are welcome!
