### ISSUE TITLE
Better support for <script>

### ISSUE THREAD

**Issue by vjeux** [facebook/react#654]
`&lt;script>` is a bit hard to use right now.
- If you have a `{...}` then it's going to start interpolating. And you are bound to have whenever you use `if`, `function` ... Workaround: you can wrap it inside of an interpolated string `{'if (true) { ... }'}`
- If you have any `'` or `"` it's going to output the html encoded version and Javascript is going to throw a parsing exception.

In order to workaround those two issues the best way I found is to use dangerouslySetInnerHTML and use ES6 backtick in order to have multi-line strings.

``` javascript
<script dangerouslySetInnerHTML={{__html: `
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('send', 'pageview');
`}} />
```

We should probably make it easier, it's quite a pain to use right now.

**Comment by bochen2014** [comment]
@syranide  thanks for sharing that! i didn't know it before
