### ISSUE TITLE
Allow mutating component state by using ES6 Proxies

### ISSUE THREAD

**Issue by kripod** [facebook/react#6540]
Instead of `this.setState({mykey: 'my new value'});`, `this.state.mykey = 'my new value';` could be used by utilizing ES6 Proxies (see [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set)).

**Comment by jimfb** [comment]
Proxies are not supported in legacy browsers.  It will likely be a couple of years before we can use them outside of development mode (ie. on a production code path).
