### ISSUE TITLE
React 15: props value changed from 'string' to '0'

### ISSUE THREAD

**Issue by jianghai** [facebook/react#6545]
![image](https://cloud.githubusercontent.com/assets/2820736/14627616/8f7643e6-0628-11e6-9a51-1285e4899c64.png)
![image](https://cloud.githubusercontent.com/assets/2820736/14627620/974a9554-0628-11e6-9b87-02e97b483f8a.png)

https://jsfiddle.net/9d3rh356/

**Comment by jimfb** [comment]
FWIW, this would be fixed by https://github.com/facebook/react/pull/6406

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/6406
