### ISSUE TITLE
React browser.js doesn't work with CSP

### ISSUE THREAD

**Issue by hackvertor** [facebook/react#6546]
I would like React to work with CSP (Content Security Policy) without adding unsafe-eval to the policy. Browser.js on line 5811 contains a call to Function which violates my CSP policy. Code is below:

```
transform.run = function (code) {
  var opts = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];

  opts.sourceMaps = "inline";
    return new Function(transform(code, opts).code)();
};
```
Is it possible to rewrite browser.js so that it doesn't violate CSP?

**Comment by ev1stensberg** [comment]
[Ref](https://github.com/ubolonton/js-csp/issues/11)

**Comment by gaearon** [comment]
@ev1stensberg 

I think this issue about Content Security Policy, not Communicating Sequential Processes. Yeah it’s confusing 😄 .

@hackvertor 

The code you are looking at is not a part of React. It’s from `node_modules/fbjs-scripts/babel/node_modules/babel-core/browser.js`. Unless you want to run Babel in browser, you don’t need it to use React. The React builds [available on the website](http://facebook.github.io/react/downloads.html) do not include this code so you can use them if you’re having trouble getting transitive dependencies of the React build process approved in code review or something like this.

I’m closing for this reason, as it’s not a problem with React.
