### ISSUE TITLE
Warning for fieldset element without form parent element

### ISSUE THREAD

**Issue by tshelburne** [facebook/react#6551]
If a `<fieldset>` element is present without a wrapping `<form>` element somewhere in the tree, iOS Chrome throws a `ReferenceError` that kills execution. Much like the suggestions for `<tbody>` under `<table>`s, it would be nice if React threw warnings for this scenario in development.

**Comment by jimfb** [comment]
Sounds like an iOS bug.  As best as I can tell from reading the spec, a `fieldset` tag is NOT required to be associated with a form.

As per https://www.w3.org/TR/html-markup/fieldset.html#fieldset-interface, the form attribute has a question mark after the type, which presumably indicates that the attribute may be null if there is no form owner.
 >  readonly attribute HTMLFormElement? form;

The `fieldset` [spec preview](https://dev.w3.org/html5/spec-preview/the-fieldset-element.html) explicitly states that "The form attribute is used to explicitly associate the fieldset element with its form owner", and links to https://dev.w3.org/html5/spec-preview/association-of-controls-and-forms.html#form-owner
 > A form-associated element can have a relationship with a form element, which is called the element's form owner. If a form-associated element is not associated with a form element, its form owner is said to be null.

And the first example in the w3c wiki (https://www.w3.org/wiki/HTML/Elements/fieldset), while non-authorative, has a `fieldset` without a `form` element, which seems consistent with the spec.

My recommendation is to file a bug with ios/chrome.

**Comment by tshelburne** [comment]
@jimfb Makes sense to me - thanks for the quick response.
