### ISSUE TITLE
keydown event listener performance is 3x is slower in 15.0.1

### ISSUE THREAD

**Issue by thepeted** [facebook/react#6554]
My use case is rendering an 80 x 80 grid of components and changing state of the parent component via `window.addEventListener` event as per the docs, like so: 

```
ComponentDidMount(){
    window.addEventListener('keydown', this.handleKeyPress);
  }
  
  componentWillUnmount(){
    window.removeEventListener('keydown', this.handleKeyPress);
  }
```

In Chrome 49.0.2623.112, for example, React 14.0.7 is taking ~75ms to re-render and 15.0.01 takes ~270ms.

View console in the examples below to see what I mean. 

[14.0.7 example](http://codepen.io/thepeted/pen/ae125e2599234fb05e5bc914db7e300d)
[15.0.1 example](http://codepen.io/thepeted/pen/f7c85287195fd58622ddc6da1ca0d648)

**Comment by gaearon** [comment]
Are you measuring the production build?

**Comment by gaearon** [comment]
Try to add `.min.js` instead. We know developer builds regressed but this shouldn't be the case for the production ones.

**Comment by thepeted** [comment]
doh!  Newb mistake, I didn't think of that :-/

Adding .min.js brings it down to sub 30ms.  Repeating the tests and there's no discernible difference between `14.0.7` and `15.0.1`

Thanks for replying.

**Comment by gaearon** [comment]
@spicyj I remember you saying you have ideas about low hanging fruit to Make Dev Builds Fast Again, anything in particular that comes to mind? This could be a nice first bug.

**Comment by spicyj** [comment]
Wait, v15 dev is 3.5x slower than v0.14 dev? That doesn't sound right.

@gaearon Just gotta start with profiling to see what's slow.

**Comment by jimfb** [comment]
@spicyj

 > keydown event listener performance

Not overall performance, just key event listener.  I could believe we added a millisecond or two in dev mode.

**Comment by jimfb** [comment]
Or actually, maybe it is general perf:

 > ~75ms to re-render and 15.0.01 takes ~270ms.
