### ISSUE TITLE
warn if calling setState in ref callback

### ISSUE THREAD

**Issue by jimfb** [facebook/react#6557]
Refs are dom nodes, and thus we suggest you don't store them in state, right?  You always store them somewhere on the instance?

Assuming so, calling setState in a ref callback sounds like an antipattern. https://github.com/facebook/react/issues/6249#issuecomment-212589250

**Comment by moaazsidat** [comment]
Hey folks, I'd love to take this on and take a crack at this bug!

**Comment by zpao** [comment]
Let's confirm the assumption before working on it :) I could see an argument for allowing setState in the ref callback. Also refs aren't always DOM nodes (composite components can be refs) & you could be doing something besides storing the node regardless. You can get into the same infinite loop if you call setState in componentDidUpdate so let's not rule out the potential use case yet.

cc @sebmarkbage

**Comment by sebmarkbage** [comment]
Yea, there's plenty of use cases for this. The beauty of a ref callback is that you can start acting on it once a child becomes available and then do something with either the child or its parent. It is effectively componentDidMount for a child.

**Comment by jimfb** [comment]
@sebmarkbage Do you have any specific use cases in mind?  The only thing I can think of is child measurement, but you should probably wait for all your children to render and then measure them in componentDidMount instead (to avoid layout thrash of measuring multiple children).

What would you be doing that involves a set state?

**Comment by jimfb** [comment]
I just chatted with Sebastian.  The conclusion of that discussion was "yeah, it's probably 'supported but discouraged', sounds kinda like an anti-pattern but refs are an escape hatch anyway, so do whatever you want at that point."

Action item on this issue is to update the docs (we should create a compatibility table, about how we for each action within each lifecycle) to indicate/clarify our current thoughts around this pattern.
