### ISSUE TITLE
Trying to read a property on undefined in render() does not log an error

### ISSUE THREAD

**Issue by bluecrowbar** [facebook/react#6562]
Trying to read a property on undefined in render() does not log an error. E.g. when I add `console.log(undefined.doesntexist)` in the render() function (even outside of the return block), nothing happens. I would have expected to get a `Cannot read property 'doesntexist' of undefined` error message in the console.

**Comment by gaearon** [comment]
Can’t reproduce this: https://jsfiddle.net/s9ej9Lp2/1/

<img width="335" alt="screen shot 2016-04-21 at 12 30 07" src="https://cloud.githubusercontent.com/assets/810438/14707467/d9faf674-07bc-11e6-8e7a-d1c386f9c096.png">

Most likely you have `setState()` or top-level rendered triggered by a Promise, and you’re using a Promise implementation that  doesn’t log unhandled rejections, so they get swallowed.

If you think this is a bug in React please provide an example that reproduces it, but for now I’ll close.

**Comment by bluecrowbar** [comment]
You're right, it was triggered by a Promise where the rejection wasn't handled. Beginner's mistake :-)
Thanks for your help!

**Comment by gaearon** [comment]
No problem. I suggest to make sure you use an implementation that logs unhandled rejections because it’s very easy to make mistakes like this.
