### ISSUE TITLE
Add 'reactjs' to repository description to appear in github search results when searching for "reactjs"

### ISSUE THREAD

**Issue by ndelangen** [facebook/react#6566]
When performing a global search query on github on query: "reactjs", this repository does not appear in the list. I think people do expect it to appear in it.

I suggest adding a bit a text to the repository description with this key-word in it.

A proposal:
```
ReactJS is a declarative, efficient, and flexible JavaScript library for building user interfaces. https://facebook.github.io/react/ 
```

**Comment by mijamo** [comment]
The name is React, so I disagree with changing it to ReactJS in the description. However it could be added to the keywords list.

**Comment by zpao** [comment]
There's no keywords list on GitHub but maybe adding it to the package.json would get indexed and ranked high?

Otherwise you're totally right - it's called React and so we won't be adding "ReactJS" to any of our documentation/readme/etc.

**Comment by jimfb** [comment]
Perhaps a keywords section at the bottom of the README/page?  That's the poor-man's solution to dealing with keywords in wiki systems that don't support keywords.  I don't feel strongly one way or the other, but we should make a decision about the disposition of this bug.

**Comment by zpao** [comment]
Just going to close. I don't think this is really any different from any other project (Eg searching github for "emberjs" doesn't get you to their project either) and not really worth doing hacky things to try to optimize.
