### ISSUE TITLE
Rename `defaultValue` to `initialValue` in form components

### ISSUE THREAD

**Issue by webPapaya** [facebook/react#6577]
The docs say:
> The defaultValue and defaultChecked props are only used during initial render. If you need to update the value in a subsequent render, you will need to use a controlled component. (https://facebook.github.io/react/docs/forms.html#default-value)

The note in the docs say that `defaultValue` is only used during `initial` rendering. So I think it would be better to name it `initialValue` because it describes the behaviour of this property better. 

Translating the terms to german a `defaultValue` means something static which can't be changed during runtime. An `initialValue` of an input element might mutate during runtime. (eg. prefill a form with the current time)

I'm not an english native speaker so it might be that the english language doesn't differentiate those two terms as the german language does.

**Comment by sebmarkbage** [comment]
You are technically correct. However, this is based on the existing DOM property called `defaultValue`. If we go down this route we should also rename `<img />` to `<image />` but that ship has sailed.

**Comment by webPapaya** [comment]
But if the naming decision is based on the DOM property `defaultValue` then it should behave exactly like it.

> The element has a *value mode flag* which is either value or default. Initially, the value mode flag must be set to default. 

> When the value mode flag is in mode default, the contents of the element represent both the value of the element and its default value.

> The defaultValue IDL attribute, on getting, must return the element's default value. On setting, the attribute must set the element's default value, and, if the element's value mode flag is in the mode default, set the element's textContent IDL attribute as well. 

> The defaultValue IDL attribute, on getting, must return the element's default value. On setting, the attribute must set the element's default value, and, if the element's value mode flag is in the mode default, set the element's textContent IDL attribute as well. (https://www.w3.org/TR/html5/forms.html#concept-output-mode)

This means that the browsers `defaultValue` can also be changed after the initial rendering, if the input field is in `value mode: default`. If the `input.value` changes, the `value mode` is set to `value`. The `defaultValue` can't be set anymore. See [Quick and dirty example](https://jsfiddle.net/w4b07mbk/2/) 
> The value IDL attribute must act like the element's textContent IDL attribute, except that on setting, in addition, before the child nodes are changed, the element's value mode flag must be set to value. (https://www.w3.org/TR/html5/forms.html#the-output-element) 

Currently React only sets the default value during initial render. If for any reason the default value changes in a rerender react won't handle it. So that's why I think the `defaultValue` should either be renamed to `initialValue` or change the behaviour so that `defaultValue` can be updated as long as the `value mode` is set to `default`.

**Comment by sebmarkbage** [comment]
Maybe we should allow it to update until the first change which causes the value mode to change then.

**Comment by webPapaya** [comment]
I think this would make sense. Should I create a separate ticket?
