### ISSUE TITLE
this is a BUG about title in IE

### ISSUE THREAD

**Issue by mtsee** [facebook/react#6578]
Div a title attribute, IE environment becomes very caton

**Comment by gaearon** [comment]
Can you please provide an example reproducing the issue? It’s not entirely clear what is broken in your opinion.

**Comment by mtsee** [comment]
sorry，It's my error, I add a canvas animation to web background, when I add <h1 title="this is title">test</h1> to body, this is very consumption performance~

**Comment by jimfb** [comment]
@mtsee Sounds like you're saying this is not a React bug, so I'll close it out.  If you believe you've found a bug in React, please provide a jsfiddle that demonstrates the issue and we can reinvestigate.
