### ISSUE TITLE
React.createElement does not accept functional component

### ISSUE THREAD

**Issue by hotay** [facebook/react#6579]
We're relying on `React.createElement` in our test suite. Since it does not accept functional component we can't no longer use functional component in our project.

**Comment by gaearon** [comment]
What do you mean? It accepts any kind of components that React support; otherwise, nobody would be able to use them in JSX.

Here is an example: https://jsfiddle.net/7vuL1Lg5/. In the future, please try to provide a reproducible example when filing an issue, or at least provide more context. It is hard to help without understanding what precisely you were trying to do, and how exactly it broke.

**Comment by jimfb** [comment]
No response from OP.

**Comment by hotay** [comment]
Sorry for late response and lack of example, here is my encountered problem when I try to write some test with functional component:
```javascript
import 'should';
import React, { createElement } from 'react';
import { renderIntoDocument } from 'react-addons-test-utils';
import { unmountComponentAtNode, findDOMNode } from 'react-dom';

let FunctionalComponent = (props) => (<div/>);

class ReactComponent extends React.Component {
  render() {
    return <div/>
  }
}

describe('FunctionalComponent', function () {
    let element;

    afterEach(function () {
      if (element) {
        unmountComponentAtNode(findDOMNode(element).parentNode);
      }
    });

    it('should render', function () {
      element = renderIntoDocument(createElement(FunctionalComponent));
      element.should.be.ok();
    })
});

describe('ReactComponent', function () {
  let element;

    afterEach(function () {
      if (element) {
        unmountComponentAtNode(findDOMNode(element).parentNode);
      }
    });

    it('should render', function () {
      element = renderIntoDocument(createElement(ReactComponent));
      element.should.be.ok();
    })
})
```

My `package.json`:
```javascript
{
  "name": "react-functional-component",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "NODE_PATH=src mochify --recursive test --transform [ babelify --presets [ es2015 react ] ] -R spec"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babelify": "^7.2.0",
    "mochify": "^2.18.0",
    "react-addons-test-utils": "^15.0.2",
    "should": "^8.3.1"
  },
  "dependencies": {
    "react": "^15.0.2",
    "react-dom": "^15.0.2"
  }
}
```

and the test result:
```bash
> NODE_PATH=src mochify --recursive test --transform [ babelify --presets [ es2015 react ] ] -R spec

# phantomjs:


  FunctionalComponent
    1) should render

  ReactComponent
    ✓ should render


  1 passing (16ms)
  1 failing

  1) FunctionalComponent should render:
     null is not an object (evaluating 'element.should')
      test/index.js:25
      callFn node_modules/mocaccino/lib/setup-browser.js:4290
      run node_modules/mocaccino/lib/setup-browser.js:4283
      runTest node_modules/mocaccino/lib/setup-browser.js:4753
      node_modules/mocaccino/lib/setup-browser.js:4864
      next node_modules/mocaccino/lib/setup-browser.js:4673
      node_modules/mocaccino/lib/setup-browser.js:4683
      next node_modules/mocaccino/lib/setup-browser.js:4615
      node_modules/mocaccino/lib/setup-browser.js:4651
      timeslice node_modules/mocaccino/lib/setup-browser.js:12619



Error: Exit 1

npm ERR! Test failed.  See above for more details.
```

**Comment by jimfb** [comment]
On line 25, `element` is not a jest expect, so it doesn't have a `should` property.  You probably intended to write something more like `expect(element).should.be.ok();`

Also, to be clear, the thing returned by `renderIntoDocument` is an `instance`, not an `element`.

**Comment by hotay** [comment]
@jimfb I'm using [shouldjs](https://shouldjs.github.io/). The point here is `renderIntoDocument` was return `null` object.

**Comment by jimfb** [comment]
@hotay As per the note at the bottom of http://facebook.github.io/react/docs/reusable-components.html#stateless-functions, stateless functions do not have backing instances.

Also mentioned in the `React.render()` documentation: https://facebook.github.io/react/docs/top-level-api.html#reactdom.render

If you want a reference, you will need to wrap the stateless function in a stateful component (like an ES6 class component) which does have a backing instance.

**Comment by hotay** [comment]
oh, thank you for your explanation @jimfb. Appreciated!

**Comment by OZZlE** [comment]
> If you want a reference, you will need to wrap the stateless function in a stateful component (like an ES6 class component) which does have a backing instance.

Could you give a simple example? I tried everything cannot get it to work
