### ISSUE TITLE
Additions to Props

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/react#6583]
Been working on a workaround for Props. I think Props should have more advantages, such as merge props, split props and so on. Is there any way we could make this a thing in React? As mentioned, I work on a tweak, meaning this is like react components, but ultimately I'd like it to see as a official react feature. Thoughts? 

[Here's the repo](https://github.com/ev1stensberg/repulse)

**Comment by ev1stensberg** [comment]
I've also seen at options such as Immutability helpers, but I don't think that covers it. Also spread is not what we want in my eyes. We should have an addon approach for this

**Comment by jimfb** [comment]
I think the correct solution (at least for now) is to handle this in user land as a separate library.  If it becomes popular, we could consider an addition to React.  This is our general recommendation for anything that is possible to handle in userland, is to prove the viability before trying to pull it into React.

**Comment by ev1stensberg** [comment]
Yeah, it's not nearly finished. But I was more thinking about making this in React explicitly and not integrating the library. Could this be the case?

**Comment by jimfb** [comment]
If something becomes sufficiently popular and there is value in merging it into the React core, that's always considered as an option.

**Comment by ev1stensberg** [comment]
I doubt this will be good enough on the coding side to integrate to React, but the idea is great for React to adopt.
