### ISSUE TITLE
Update ReactDOMServer.renderToStaticMarkup documentation

### ISSUE THREAD

**Issue by graue** [facebook/react#6589]
[`renderToStaticMarkup` is described as](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostaticmarkup):

> Similar to `renderToString`, except this doesn't create extra DOM attributes such as `data-react-id`, that React uses internally.

There are no more `data-react-id`s in React 15, so it's probably time to change this and clarify if this still has advantages over `renderToString`.

**Comment by jimfb** [comment]
Unlike `renderToStaticMarkup`, `renderToString` does still have the react data IDs.
