### ISSUE TITLE
context does not update using `unstable_renderSubtreeIntoContainer`

### ISSUE THREAD

**Issue by linzerui** [facebook/react#6599]
I use `ReactDOM.unstable_renderSubtreeIntoContainer` to render a portal.

```javascript
class Modal extends React.Component {

componentDidMount() {
    this.node = document.createElement('div');
    document.body.appendChild(this.node);
    this.renderPortal(this.props);
}

componentWillReceiveProps(nextProps) {
    this.renderPortal(nextProps);
}

componentWillUnmount() {
    ReactDOM.unmountComponentAtNode(this.node);
    document.body.removeChild(this.node);
}
    
renderPortal = (props) => {
    renderSubtreeIntoContainer(this, <ModalPortal {...props} />, this.node);
}

render() {
    return null;
  }
}
```

In my root component:

```javascript
class App extends React.Component {
    static childContextTypes = {
        highlightColor: React.PropTypes.object
    }

    getChildContext() {
        return {
            highlightColor: this.props.highlightColor
        }
    }

    ...
}
```

The context of root component will be updated and passed to children if  `this.props.highlightColor` is changed. This is right.
I can access the correct context in the `<ModalPortal/>` component in the first render.
And after that the context passed to  `<ModalPortal/>` **does not change any more** when the context of root component changed.
But I can access the correct context in the `<Modal/>`  every render.

what's wrong with my code ?

**Comment by gaearon** [comment]
Is it possible that you have a `shouldComponentUpdate` there? (Or something that implements it, e.g. `connect()` from React Redux.) There is a known issue about it in #2517.

Alternatively this may be a new issue. Can you provide a JSFiddle reproducing it?

**Comment by danielberndt** [comment]
Here's a minimal fiddle illustrating the issue:
http://codepen.io/anon/pen/LZPxER?editors=1010

no shouldComponentUpdate here, just plain context passing. The context is not updated when `unstable_renderSubtreeIntoContainer` is involved.

**Comment by gaearon** [comment]
Can you submit a PR with a failing test case please?

**Comment by danielberndt** [comment]
You can find the PR here: https://github.com/facebook/react/pull/6924

It's my first PR to react. So I hope, I didn't miss anything obvious! 😰

**Comment by iotch** [comment]
Is it safe to use `unstable_renderSubtreeIntoContainer` in production? It seems like it may be changed or removed at any time. Is there any production alternatives to render a component into a DOM node manually?

**Comment by mikekidder** [comment]
@iotch -- a little insight from this tweet https://twitter.com/soprano/status/737316379712331776

**Comment by iclanzan** [comment]
I can confirm that context does not update when using `unstable_renderSubtreeIntoContainer`.
