### ISSUE TITLE
How does parent component call methods in child components?

### ISSUE THREAD

**Issue by zhongning7924** [facebook/react#6609]

**Comment by gaearon** [comment]
In general, this is not necessary. You should try to express the relationships between them by moving the state up to the parent, and letting the child re-render based on changes in it. [Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html) is a great guide explaining this.

*For the rare edge cases* where you actually want to call a method on a child instance (e.g. to imperatively set focus in a field), you can use [refs](http://facebook.github.io/react/docs/more-about-refs.html).

Please note that we use this as an bug tracker for React. [StackOverflow](http://stackoverflow.com/) might be a better place to ask questions. Cheers!
