### ISSUE TITLE
virtual DOM

### ISSUE THREAD

**Issue by js08** [facebook/react#6615]
hi,

I like react.js so much.... can you guys tell me where you guys implemented the below logic in the code...I am not sure how to create patch using js code :(

**It also uses what Facebook calls a “virtual DOM” for some increased performance by writing out a full render virtually, and then checking the difference between the virtual render and what’s actually on the DOM and creating a patch. **

**Comment by jimfb** [comment]
Dealing with the virtual DOM is a large part of what React does (ie. pretty much all of React is implementing the virtual dom rendering).  The virtual DOM nodes are created in your component's `render` function (that's what you return, when you write JSX), the nodes are used in places like `ReactCompositeComponent` and `ReactDOMComponent` (specifically, look at the `mountComponent` and `receiveComponent` functions).

This is not a bug in the React core. For this reason, I'm going to close out this issue.  A better place for discussions like this would be discuss.reactjs.org, or stackoverflow, or quora, or IRC.  Github is used for tracking bugs in the core.

**Comment by js08** [comment]
is it possible to point me to those links

**Comment by gaearon** [comment]
https://discuss.reactjs.org/
http://stackoverflow.com/
https://www.quora.com/
https://facebook.github.io/react/support.html

**Comment by js08** [comment]
@gaearon sorry code link in github

**Comment by gaearon** [comment]
Sure. 

Elements are what you return from your render method. https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js

Composite component implementation manages the lifecycle of the components you write, and updates its rendered child when a new element is received.  https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js

DOM component implementation updates the actual DOM when a new element is received. https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDOMComponent.js
