### ISSUE TITLE
TypeError using ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by tomdcc** [facebook/react#6619]
React 0.14.8
We see this in browser tests but never manually triggered, so bug is seemingly timing sensitive.

```
Uncaught TypeError: Cannot read property 'classList' of null CSSCore.js:38
CSSCore.addClass @ CSSCore.js:38
React.createClass.flushClassNameQueue @ ReactCSSTransitionGroupChild.js:116
```

`component.isMounted()` is `true`, but in these cases `ReactDOM.findDOMNode(this)` then returns null here
https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroupChild.js#L116

**Comment by gaearon** [comment]
Can you try to extract a reproducible case?

**Comment by jimfb** [comment]
@tomdcc Also, are you using React Router?

**Comment by tomdcc** [comment]
@gaearon I'll try to find some time, but as I mentioned I can only trigger in tests (webdriver driven, chrome), never manually, so it's not straight forward.

@jimfb No, we're not.

**Comment by jimfb** [comment]
Can you put a simplified copy of your webdriver test on github or somewhere so we can run it?

**Comment by tomdcc** [comment]
Thanks for the interest, I'll try to extract a minimal version today (AU) sometime

**Comment by jimfb** [comment]
I sort of wonder if this is related to https://github.com/facebook/react/issues/6495

**Comment by malstoun** [comment]
Hi 

This code reproduces the error: http://codepen.io/anon/pen/GZwqQy

**Comment by tomdcc** [comment]
Thanks Andrey!

**Comment by spicyj** [comment]
@keyanzhang Can you try to dig into this and figure out what the underlying cause is? We've had a few pull requests that simply add a null check before trying to dereference a node or component, but we should instead be canceling timers and dequeueing things when they are unmounted so that there are never null elements left over.

**Comment by bengotow** [comment]
Hey folks—just stumbled across this. We've been seeing this error a /lot/ in the Sentry logs from N1, which uses ReactCSSTransitionGroup and React 15.0.1. I'll see if I can come up with a test case. I'll see if we can reproduce a test case.  Reading through the Child source, I think that for internal consistency, the `node` used within flushClassNameQueue for `CSSCore.addClass.bind(CSSCore, ReactDOM.findDOMNode(this))` should be the node cached at the beginning of `transition()`. (Currently it re-finds the node.)

In N1 we have a few instances of ReactCSSTransitionGroup nested within each other, and the issue might be related to render removing an entire subtree with multiple ongoing animations—not sure yet!

**Comment by spicyj** [comment]
@bengotow That sounds right to me. Do you want to send a PR to store it as `this.node` alongside `this.classNameQueue` and then use that node when flushing the classes? We should null it out afterwards like we do with the timeout. Can you check that that fixes the codepen linked above?
