### ISSUE TITLE
Formal Type Definitions not up-to-date

### ISSUE THREAD

**Issue by sheerun** [facebook/react#6624]
Hey,

I noticed "Formal Type Definitions" are not up-to-date as they don't account for stateless components.

It probably should be something like:

```
type ReactComponentElement<TProps> = {
  type : ReactClass<TProps> | ReactStatelessComponent<TProps>,
  props : TProps,
  key : string | boolean | number | null,
  ref : string | null
};
```

https://github.com/facebook/react/blob/master/docs/docs/ref-10-glossary.md

**Comment by gaearon** [comment]
Good catch. Would you like to work on adding the information about functional components to this page?

**Comment by sheerun** [comment]
I'd rather delegate this task to core contributor

**Comment by gaearon** [comment]
Everyone on the team is busy with different things, and the team is small, so any help, especially in the area of the docs, is very appreciated. If you do decide to submit a PR, we will definitely review it and if there’s anything we’d rather see differently, we’ll let you know. Even if we don’t end up accepting it, we might use some parts later. It’s your call but if you have time, we’d love to get your help on it.
