### ISSUE TITLE
New DOM renderer inserts parameters after creation on IE

### ISSUE THREAD

**Issue by syranide** [facebook/react#6629]
The new renderer is causing Flash objects to be instantiated before any nested param nodes have been added, they are read and parsed at creation and never touched again. EDIT: I'm assuming the Flash object is loaded immediately upon insertion into the DOM and not at the next tick.

This only happens on IE AFAIK (all versions including Edge). Related to the performance-special-case in the renderer?

cc @spicyj

**Comment by spicyj** [comment]
If an object gets created when the `object` tag is appended to the document, then probably.

**Comment by syranide** [comment]
Just checked, that is what's causing it.

**Comment by syranide** [comment]
This applies to all parameters it seems, making flash virtually unusable with React 15.

**Comment by spicyj** [comment]
That seems reasonable. The fact that this took weeks to be reported suggests to me that few people are in this situation. Were you not able to get your patch #6640 to work? Why not?

**Comment by syranide** [comment]
> The fact that this took weeks to be reported suggests to me that few people are in this situation.

@spicyj Yeah, I would assume object and/or flash is very rarely used nowadays, especially in React.

> Were you not able to get your patch #6640 to work? Why not?

Slight misunderstanding of how DOMLazyTree works, I also saw that such a special-case was already present for document fragments and I simply added `<object>` to that test. It now works as intended. #6691

**Comment by syranide** [comment]
Released.
