### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by jaredly** [facebook/react#663]
I love that there are "invariant"s everywhere, but sometimes the errors they report aren't immediately understandable. For example, if a mixin defines a default prop that's also defined in your component, you get the lovely error:
```
Uncaught Error: Invariant Violation: mergeObjectsWithNoDuplicateKeys(): Tried to merge two objects with the same key: [the duplicate key was here]
```

It took me a while to figure out the cause. [jsfiddle](http://jsfiddle.net/kb3gN/592/)

Another I've run into is `Each child in an array should have a unique "key" prop. Check the render method of undefined.` (console.warn'd) Which happened when I had passed in an undefined function as an `onClick` prop.

**Comment by gaearon** [comment]
I don’t think there is anything actionable in this issue so I’m closing. If there are specific warnings that are confusing or miss the important information and context, please file an issue with instructions to reproduce. Then we can tag them as “good first bug” and receive community contributions for those. Cheers!

**Comment by jaredly** [comment]
+1 yup lots has improved over the past two years :D
