### ISSUE TITLE
React 15 breaks support for the type extension (the `is` syntax) on webcomponents custom elements

### ISSUE THREAD

**Issue by jrsquared** [facebook/react#6635]
http://w3c.github.io/webcomponents/spec/custom/#custom-elements-type-extension-example

The `is` attribute is lost from the JSX.  If an `is` attribute is present, it needs to be passed to document.createElement as the second parameter. (http://webcomponents.org/polyfills/custom-elements/)

**Comment by gaearon** [comment]
I think this should be fixed by #6570. Not released yet.
