### ISSUE TITLE
React does not support Node v6.0.0

### ISSUE THREAD

**Issue by RaitoBezarius** [facebook/react#6644]
The `package.json` does not accept a node engine of version 6.x

I don't think that there is some regressions caused by Node v6, so it should be okay?

**Comment by koistya** [comment]
@RaitoBezarius there is `"engines": { "node": ">=0.10.0" }` in `react` npm package.

**Comment by RaitoBezarius** [comment]
My bad, @koistya -- I meant the `devEngines`, you cannot `npm install` without getting an error with Node v6.0.0.
