### ISSUE TITLE
render() called before componentDidMount()

### ISSUE THREAD

**Issue by bep** [facebook/react#6651]
See

https://jsfiddle.net/mkfy6fbu/

**Comment by bep** [comment]
Sorry, my bad -- this is as specificed.

**Comment by franzejr** [comment]
@bep, Good chart trying to cover the lifecycle: 
https://d2vvqscadf4c1f.cloudfront.net/RXZidTc7S5WEicK3fiNW_Screen%20Shot%202016-02-25%20at%2012.06.29%20PM.png
