### ISSUE TITLE
Modernize build process / tooling

### ISSUE THREAD

**Issue by zpao** [facebook/react#6656]
This is mostly a prereq of #6655.

Goals:
- align build tooling (right now mixing grunt & gulp - commit, probably to gulp #4927)
- add watching, should be fast to rebuild and test changes in browser
  - could be something like webpack hot reloading
- move shared tooling back into fbjs (babel plugin, custom lint rule)

Non-goals but things to keep in mind:
- alternate build approaches, in particular flat bundling - it needs to be easy to swap this in
- releasing from master - we may want to have development happen such that feature flags are used to turn on/off features. we may want the build result to be a static flag set (no runtime checks) but would need to be possible to target any flag combination easily

**Comment by trueadm** [comment]
This has been merged in PR: https://github.com/facebook/react/pull/9327

**Comment by gaearon** [comment]
Not sure, I think these are open areas:

* add watching, should be fast to rebuild and test changes in browser
* move shared tooling back into fbjs (babel plugin, custom lint rule)

**Comment by gaearon** [comment]
We got rid of fbjs and actually seem to prefer to own our scripts.
As for watching.. seems like it might be complicated with our pipeline. Maybe not worth it.
