### ISSUE TITLE
In FireFox Input Focus Problem

### ISSUE THREAD

**Issue by zenjava** [facebook/react#6666]
In FireFox has the problem,ohter Browser is right.
In its case, Focus input from a box I moved to a input box in Fire Fox error.
my code 
<input type="text" className="focusInput" ref="focusEl" href="#" tabIndex="0" key="focusNode"
                               onKeyDown={this.onKeyDown.bind(this)}
                               onKeyPress={this.onKeyPress.bind(this)}
                               onKeyUp={this.onKeyUp.bind(this)}
                               onChange={this.onChange.bind(this)}
                               onBlur={this.onBlur.bind(this)} onFocus={this.onFocus.bind(this)}></input>,

the focus method is : 
     this.refs.focusEl.focus();

I debugger React Code  is Wrong in.

  setSelection: function (input, offsets) {
	    var start = offsets.start;
	    var end = offsets.end;
	    if (typeof end === 'undefined') {
	      end = start;
	    }
	
	    if ('selectionStart' in input) {
	      input.selectionStart = start; // <----- is Here
	      input.selectionEnd = Math.min(end, input.value.length);
	    } else if (document.selection && (input.nodeName && input.nodeName.toLowerCase() === 'input')) {
	      var range = input.createTextRange();
	      range.collapse(true);
	      range.moveStart('character', start);
	      range.moveEnd('character', end - start);
	      range.select();
	    } else {
	      ReactDOMSelection.setOffsets(input, offsets);
	    }
	  }
	};

input value is <input type="text" name="ext-comp-1001" id="ext-comp-1001" autocomplete="off" size="20" class="x-form-text x-form-field x-field-non-blank x-form-invalid" style="width: 30px; visibility: visible; height: 25px;">

input.selectionStart = start is break wrong.
start value is 1
input.selectionStart is  1

**Comment by zenjava** [comment]
I found a way to repair,
  setTimeout(function () {
                    me.refs.focusEl.focus();
                }, 1)

**Comment by jimfb** [comment]
@zenjava can you provide a jsfiddle that demonstrates the issue?

**Comment by jimfb** [comment]
No response from OP.
