### ISSUE TITLE
No changelog for release 15.0.2

### ISSUE THREAD

**Issue by DanielHeath** [facebook/react#6671]
Neither the blog nor Changelog.md have been updated, but npm says there's a 15.0.2 out.

**Comment by ekonstantinidis** [comment]
Hi @DanielHeath! I've found some notes for `15.0.2` under the GitHub release - https://github.com/facebook/react/releases/tag/v15.0.2. Hope it helps!

**Comment by zpao** [comment]
We don't do a blog post for every release but we did update the releases page. I neglected to cherry-pick some commits over to master with what landed in the release branch but they are there now.
