### ISSUE TITLE
ReactTransitionableChild gets confused when removed before all transitions are complete

### ISSUE THREAD

**Issue by ide** [facebook/react#669]
ReactTransitionableChild sets up listeners to detect when animations/transitions are complete so it knows when to remove the transition classes (and DOM elements for a "leave" transition). These listeners get confused when more than one element in the transitionable child tree performs an animation/transition. For example:

    <div className="outer">
      <div className="inner" />
    </div>

Say the desired effect is for the outer div to fade in first, followed by the inner div. This is possible with two CSS transitions with the appropriate durations and delays.

React gets confused when this element is removed in the middle of the inner transition (in fact, I think removing the element before the outer transition finishes can also confuse React). Generally, listening to bubbled transition events violates encapsulation in some cases.

**Comment by spicyj** [comment]
#1301 should have fixed this.
