### ISSUE TITLE
Unknown plugin babel-plugin-transform-react-jsx-source

### ISSUE THREAD

**Issue by keyanzhang** [facebook/react#6695]
#6398 added `babel-preset-react/node_modules/babel-plugin-transform-react-jsx-source` to `.babelrc`, but `babel-preset-react` [doesn't](https://github.com/babel/babel/blob/master/packages/babel-preset-react/index.js#L9-L15) export this module. `npm run build` and `npm test` fail because of that.

I removed this line from `.babelrc` and #6398's tests still pass. Should I remove it or change it to just `babel-plugin-transform-react-jsx-source`? @troydemonbreun @jimfb 

Also cc @spicyj since you [might](https://phabricator.babeljs.io/T2994#64425) know this issue.

**Comment by spicyj** [comment]
Probably should just be `babel-plugin-transform-react-jsx-source` or `transform-react-jsx-source` but I'm confused why the test would be passing even without it. Do you want to look into that @keyanzhang?

**Comment by keyanzhang** [comment]
yep!

**Comment by keyanzhang** [comment]
This is really weird -- my build fails both on master and that commit. Could you reproduce this (locally and on travis)?

**Comment by spicyj** [comment]
Haven't tried locally. Travis is broken trying to calculate coverage but the jest tests themselves appear to pass:

https://travis-ci.org/facebook/react/jobs/127678860

**Comment by keyanzhang** [comment]
Oh I figured out. It fails on npm@3 but not npm@2 since npm@2 doesn't flatten deps (lol). `babel-plugin-transform-react-jsx-source` is a dependency of `babel-preset-react`.

I can do a PR to change `.babelrc` but I don't need if we actually need this plugin.

**Comment by spicyj** [comment]
Got it. Let's add an explicit dep in package.json and change .babelrc to reference it directly (don't need the babel-plugin- prefix in .babelrc).
