### ISSUE TITLE
React perf always prints empty Array

### ISSUE THREAD

**Issue by idjuradj** [facebook/react#6702]
Hi guys,
I'm trying to test the performance of my app by using react perf tools. The problem is its not working.
I call
```
Perf.start()

Perf.stop()

Perf.printWasted()
```

in the console, which works (no console errors or warnings), but `printWasted()` always returns empty Array and a message
> Total time: 0.00 ms

This also happens for other functions like `printInclusive()` and `printExclusive()`
What can be the problem?
P.S I'm using react-router, how is react perf performing with that? Maybe that's causing some issues?
Also, `process.env.NODE_ENV` is not set to production, and I'm using `React 0.13.3`

**Comment by jimfb** [comment]
> React 0.13.3

I don't know off hand what's going on there, but the react perf stuff did work in 0.13.3, as far as I know.  We don't generally support/debug old versions of React (my recommendation is that you upgrade!).  If you can provide a jsfiddle (using a new version of React) that demonstrates a bug in React, we'll happily look into it!

I'm going to close this out because it's not an actionable bug on our end.  Feel free to continue the discussion on this thread.

**Comment by idjuradj** [comment]
@jimfb Thanks for the prompt response. I'm hoping someone had a similar issue, so he can provide adequate help :).

**Comment by jimfb** [comment]
Yeah, we use github for tracking bugs in the master release of React core, so we're pretty proactive about closing out issues like this.  Personally, I'd recommend trying on StackOverflow, which is better setup for getting usage help.

**Comment by gaearon** [comment]
One thing I’d check for is whether you don’t include two copies of React on the page by mistake. This would explain why one of them in unaware of the time spent in the other.

**Comment by idjuradj** [comment]
@gaearon On one page, where I included React I called
`React.render(MyComponent, container)`

Inside MyComponent I also included React.

When I moved the code for MyComponent to the index page (where I'm calling `React.render()`) 
Perf tool works, so it looks like you were right.

**Comment by gaearon** [comment]
You can run `npm ls react` and check if you have a duplicate installed by some library.

**Comment by idjuradj** [comment]
When I run `npm ls react`, I only see `react@0.13.3`
The problem was that I was using React as `require('react/addons')` in one component (the one in which I was calling `React.addons.Perf`) and in others React as simply `require('react')`.

Thanks for the help guys!

**Comment by arvindkumarc** [comment]
I get this issue in `react 15`. There is only one react from 
```
yarn list react
└─ react@15.5.4
```

I'm using it in the root component.
```
import Perf from 'react-addons-perf';
window.Perf = Perf;
```

All I get is `[]` on `Perf.printWasted()` after a cycle of `.start(), use application and .stop()`
