### ISSUE TITLE
Docs clarification: "Complete example" of Refs

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react#6711]
Under https://facebook.github.io/react/docs/more-about-refs.html#a-complete-example, the relevant code centers around `this.myTextInput`, which isn't defined under "Complete example". It's defined above. Maybe move it below so it's all together?

**Comment by jimfb** [comment]
I don't understand.  `this.myTextInput` is defined under "complete example" (that's the point, it's a complete example).

**Comment by jimfb** [comment]
We do happen to use the same variable in the section on callback refs, but we aren't depending on anything from that section.

**Comment by kevinSuttle** [comment]
That's where the confusion is.

**Comment by jimfb** [comment]
actually, I just looked at the page again.  We aren't even using the same variable name in that previous section.  The refs section uses `_input` and the complete example uses `myTextInput`.

**Comment by kevinSuttle** [comment]
So what I mean is, it's not clear where `myTextInput` is being defined. Maybe it's the ES6 magic in this line making it hard to read.

```
<input type="text" ref={(ref) => this.myTextInput = ref} />
```

**Comment by jimfb** [comment]
it's just an expando property, pretty standard in javascript.

**Comment by gaearon** [comment]
>Maybe it's the ES6 magic in this line making it hard to read.

To add some context, I think what @jimfb means is that this pattern isn’t really specific to ES6.
Here’s an equivalent in ES5:

```js
<input type="text" ref={function(ref) {
  this.myTextInput = ref;
}.bind(this)} />
```

This is not much different from patterns like

```js
$.ajax(url, function (result) {
  this.data = result.data;
}.bind(this))
```

that are prevalent in ES5 code with many libraries.

So we pass a callback that writes to `this.myTextInput`. In JavaScript, people often don’t declare the initial (empty) values for fields that are set asynchronously. Refs are set asynchronously, so while technically we could put `this.myTextInput = null` somewhere, it doesn’t really make a difference. Therefore we would prefer to leave it as is.
