### ISSUE TITLE
<datalist> support

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react#6717]
Not a _ton_ of browser support for this right now, but it appears to be on the horizon for Webkit. 
https://bugs.webkit.org/show_bug.cgi?id=98934

http://caniuse.com/#search=datalist

Right now, I'm not getting any DOM events fired from it in Chrome. Wonder if SyntheticEvent could prollyfill. 
https://facebook.github.io/react/docs/events.html#form-events

**Comment by jimfb** [comment]
Do you have a jsfiddle that demonstrates the issue?

**Comment by jimfb** [comment]
Also, if you'd like to submit a PR for this, this is something we'd probably want to support in React.

**Comment by kevinSuttle** [comment]
@jimfb Do you have a guide for submitting new elements to support, tests to run, etc.?

**Comment by zpao** [comment]
No written guide. But short guide is to have a test component that you render and (importantly) update the possible attributes. If there are events, then adding some handlers and clicking or whatever to fire those events.

There isn't really an automated process for that. In the past I usually just modify one of the examples and run it with my local build.

**Comment by kevinSuttle** [comment]
Yeah, that's what I was thinking as well. Thanks.

**Comment by senseluo** [comment]
i need <datalist> as well!!!

**Comment by nhunzaker** [comment]
As far as I understand, this is supported:
https://codesandbox.io/s/pmjwv5q957

Closing this out, but please let me know if I've missed something!
