### ISSUE TITLE
support for event.movementX/Y [feature-request]

### ISSUE THREAD

**Issue by caub** [facebook/react#6723]
currently it seems synthetic events don't have those properties on mousemove

**Comment by cauburtin** [comment]
oh .nativeEvent sorry

**Comment by jimfb** [comment]
@zpao @syranide @spicyj Is this something we want to support?  Looks like the status is "Candidate Recommendation" but it is supported by a couple browsers.

**Comment by spicyj** [comment]
Sounds like Firefox, Chrome, and Edge all support it. We might as well too though I don't know if it's worth polyfilling.

**Comment by Aweary** [comment]
@jimfb @spicyj so do you guys want to add it only in supported browsers, or polyfill it as well?

**Comment by gaearon** [comment]
If we add something to the synthetic event object, it needs to be available in all browsers.

**Comment by Aweary** [comment]
Does the synthetic event system have a way to access the previous instance of an event? Since `movementX` is the difference between the current `screenX` and last `screenX` value.

**Comment by syranide** [comment]
I'm always a bit weary when polyfilling things that require rather non-trivial logic as opposed to just interpolating some data. Case in point; to do this I can only assume we would be required to have a permanent global mouse move listener which tracks the last X/Y value, this feels bad. There's potential for issues here, an event being stopped, event order (or is it just for mousemove?), unnecessary global mouse move listener, etc.

**Comment by Aweary** [comment]
It should be just for `mousemove`. If it just calculates he difference between the last two `mousemove` events it doesn't seem too complicated to keep track of but I'm sure I might not be considering some corner cases/gotchas with my PR.

**Comment by Jayflux** [comment]
I've added a new PR for this

**Comment by nhunzaker** [comment]
Closed, with https://github.com/facebook/react/pull/9018. Thanks again, @jasonwilliams!
