### ISSUE TITLE
Support unquoted attribute values in JSX.

### ISSUE THREAD

**Issue by lixiaoyan** [facebook/react#6724]
For example:
``` jsx
<div id=main></div>
```

**Comment by jimfb** [comment]
Did you intend for the `id` to refer to the variable `main` or the string "main"?  There is some ambiguity with regards to what the intent would be, which is slightly suboptimal.  It also makes parsing slightly more difficult/complex.

For the reasons above, I think we're unlikely to make this change.  However, feel free to continue the discussion on this thread and we can always re-open if our thinking changes substantially.

**Comment by gaearon** [comment]
In any case, feature suggestions for JSX would be better placed in http://github.com/facebook/jsx.
