### ISSUE TITLE
componentDidUpdate running before render flushes

### ISSUE THREAD

**Issue by whitegrey** [facebook/react#6725]
I've been trying to write a simple transition component for React Router that looks like this:

```
var TransitionDaemon = React.createClass({
	getInitialState: function(){
		return {
			stage: 'active'
		}
	},
	componentWillReceiveProps: function(nextProps){
		var nextPath = nextProps.path.replace(/\//g, '');
		var currentPath = this.props.path.replace(/\//g, '');

		if (nextPath != currentPath)
			this.setState({stage: 'hidden'})
		
	},
	componentDidUpdate: function(prevProps){
		var prevPath = prevProps.path.replace(/\//g, '');
		var currentPath = this.props.path.replace(/\//g, '');

		if (prevPath != currentPath)
			this.setState({stage:'active'});

	},
	render: function(){
		var transitionHelper = ['transitionHelper', this.state.stage];
		return (
			<div className={transitionHelper.join(' ')}>
				{this.props.children}
			</div>
		)
	}
})

```
The idea is to fade in each new child component through CSS by changing the class between Active and Hidden.

I've noticed for small child components, componentDidUpdate will run before the new DOM is flushed, resulting in no transition at all. A work around seems to be to put the setState under componentDidUpdate in a setTimeOut(()=>{ this.setState({stage:'active'}); }, 1)

**Comment by jamesblight** [comment]
Not sure what's going on with componentDidUpdate but you could use ReactCSStransitionGroup in your render and avoid using the lifecycle hooks. https://facebook.github.io/react/docs/animation.html

Just set the key of this.props.children to be unique for each path.

In render():

<ReactCSSTransitionGroup { transition props go here }>
  cloneElement(this.props.children, { key: this.props.path }
</ReactCSSTransitionGroup>

**Comment by gaearon** [comment]
Can you please provide a fiddle demonstrating the issue?

**Comment by gaearon** [comment]
Unfortunately we can’t help without a reproducing case.
