### ISSUE TITLE
Installation error at 'node postinstall'

### ISSUE THREAD

**Issue by msmania** [facebook/react#6726]
I got 'node postinstall' error when running 'npm install' on ubuntu 16.04.

> npm ERR! Linux 4.4.0-22-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
> npm ERR! spawn ENOENT

Luckily I found a similar issue at https://github.com/ForbesLindesay/spawn-sync/issues/28 and I realized my issue was also resolved by creating a symbolic link node to nodejs by running 'sudo ln -s /usr/bin/nodejs /usr/bin/node'

Am I missing something? Or, the command "node postinstall" needs to be replaced with "nodejs postinstall"?

**Comment by jimfb** [comment]
The command should be `node`.

Node.js is sometimes installed as `nodejs` instead of `node` due to a package naming conflict.  More info: http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04

This is not a React bug, so I'm closing it out.
