### ISSUE TITLE
svg sprite ie10 freeze

### ISSUE THREAD

**Issue by larchanka** [facebook/react#6734]
If svg sprite is using within the component, changing of sprite is freezing IE10.

JSX example:

``` javascript
var Hello = React.createClass({
  clickNum: 0,

    getInitialState: function() {
    return {
        stateMessage: ''
    };
  },

  click: function() {
    this.setState({
        stateMessage: 'click ' + this.clickNum 
    });
    this.clickNum++;
  },

  render: function() {
    var icon = this.clickNum % 2 === 0 ? '#heart' : '#heart-active';

    return (
        <div>
            <button onClick={this.click}><svg width="50" height="50"><use xlinkHref={icon}></use></svg></button>
            <div>{this.state.stateMessage}</div>
      </div>
    );
  }
});

ReactDOM.render(
  <Hello name="World" />,
  document.getElementById('container')
);
```

Link to [JSFiddle](http://jsfiddle.net/0njjfja1/3/)

**Comment by operatino** [comment]
Browser freezes completely, blocking any user interaction on second button click.

**Comment by zpao** [comment]
Is this actually related to the spriting or is it just related to click events? Does this fiddle http://jsfiddle.net/a31yq2rm/ break? That's just a plain JS implementation of basically the same thing.

**Comment by operatino** [comment]
@zpao, nice point you have here. IE10 actually freezes also with plain JS implementation either, but after 20th click or so, sometimes faster, when with react it happens even after first click.

**Comment by gaearon** [comment]
Doesn’t sound React related to me but let me know if I’m mistaken.
