### ISSUE TITLE
Docs build in russian 

### ISSUE THREAD

**Issue by brigand** [facebook/react#6735]
Something went wrong with the build https://github.com/facebook/react/commit/eef19d1a0427b9b4309ecba6447a95a4eab5c6b3

I think it's just this page, but haven't checked them all https://facebook.github.io/react/docs/reusable-components.html

**Comment by brigand** [comment]
Also https://facebook.github.io/react/docs/displaying-data.html and https://facebook.github.io/react/docs/why-react.html

**Comment by gaearon** [comment]
I approved the related PRs but they only created new files as far as I saw. I’m super confused about this.

**Comment by gaearon** [comment]
cc @zpao, any ideas what happened?

**Comment by gaearon** [comment]
cc @dotu for the future reference—ids and permalinks need to be unique.

**Comment by aaron7pm** [comment]
https://facebook.github.io/react/docs/why-react.html is showing in Chinese ATM. Many other pages are still showing as Russian.

**Comment by gaearon** [comment]
Travis was taking a lot of time to run. It just finished two minutes ago, and after Cmd+R I see all pages in English.
