### ISSUE TITLE
React app cannot load in Facebook iOS WebView

### ISSUE THREAD

**Issue by andreafdaf** [facebook/react#6739]
Hello!

I know that this might not be the best place to ask but I cannot seem to find a better place to do so, and both React and the said application are built by you (you being Facebook Inc.)

So, we built this react application, this is a demo page: https://bookingbutton.winearound.com/en/554b39bffd2618f777e4a533?lang=en
The main issue arises when we want users to share the link on Facebook for other people to view/book the same cellar/event.

The page loads fine on all desktop browsers, all Android devices we tested (also in the Facebook WebView), all iOS devices using Safari but cannot load in the Facebook WebView in a range of devices going from iPhone 4 to 6S, iPad 2 and Nano and iPod Touch (we don't have access to all iOS devices but we found the same behavior in all the tested ones)
We put all kind of shims to support also legacy browsers, we also render it using PhantomJS and it works fine, the only issue comes from the Facebook WebView on iOS.

We use https://rollbar.com/ to track the console outputs but nothing is thrown when accessing it from the Facebook WebView, it simply won't load and now we are clueless on what to do next.

Those are our package.json dependencies:
```
  "dependencies": {
    "babel-polyfill": "6.5.0",
    "classnames": "^2.2.3",
    "es6-promise": "^3.1.2",
    "google-map-react": "^0.10.6",
    "isomorphic-fetch": "^2.2.1",
    "moment": "^2.11.2",
    "moment-timezone": "^0.5.3",
    "nuka-carousel": "^1.0.2",
    "react": "0.14.7",
    "react-day-picker": "^1.3.0",
    "react-dom": "0.14.7",
    "react-dropdown": "^1.0.2",
    "react-helmet": "^2.3.1",
    "react-intl": "2.0.0-pr-3",
    "react-modal": "^0.6.1",
    "react-phone-input": "^1.0.2",
    "react-redux": "4.4.0",
    "react-router": "2.0.0",
    "react-router-redux": "3.0.0",
    "react-share": "^1.4.1",
    "redux": "3.3.1",
    "redux-act": "0.3.0",
    "redux-form": "^4.2.0",
    "redux-thunk": "1.0.3",
    "updeep": "0.13.0",
    "validator": "^5.1.0"
  }
```

**Comment by jimfb** [comment]
cc @spicyj

**Comment by spicyj** [comment]
I took a brief look. As far as I can tell, this isn't a React issue. It looks like maybe something is wrong with the locale fetching code. Since the page just says `...` and the network inspector in Safari seems to only show a request to it.json and none to en.json. I'm not sure why this would differ between the Facebook in-app browser and Safari though. If you keep having trouble, trying to reduce it to a minimal repro could help. Maybe even just by alert debugging or similar. You should be able to post a link to Facebook to your local dev server (with Only Me privacy) and then test locally. If you get to a small repro case but still can't figure it out, post back here and I can take a look.

**Comment by andreafdaf** [comment]
@spicyj

Hello again, we found the problem. Apparently Facebook in-app browser sends a user agent different than Safari so Intl cannot be polyfilled, if you want to give it a try just open:
https://cdn.polyfill.io/v1/polyfill.js?features=Intl.~locale.en,Intl.~locale.it
from iOS Safari and from the in-app browser

I'm making a PR to polyfill.js but again we have a small problem, a detail I would say: the UA sent by the in-app browser is not formatted the same way in the iOS and Android browser, while the Android in-app browser is correctly interpreted as "Chrome" the iOS one get identified as "Facebook" on even leading UA recognizing tools, if you want to give it a try:
http://www.whatsmyua.com/
It would be nice if we could get "FacebookChrome" and "FacebookSafari" or just "Chrome" and "Safari" (I'm not an expert on the matter so that's just my two cents)

That being said the issue is solved, just a matter of the usual internet convention/not-convention stuff, thanks for your assistance! :v:
