### ISSUE TITLE
hidden={true} not works on element with "display" in css

### ISSUE THREAD

**Issue by twoeo** [facebook/react#6743]
**CSS**
`.test{display: flex}`

**JS**

```
ReactDom.render((
    <div hidden={true} className="test">Test</div>
), document.getElementById('app-root'));
```

**Expect**
Element hidden

**Actual**
Element not hidden

**Solution**
div[hidden]{ display: none!important; }
(Seems like React use div[hidden] to hide element, think that !important is better.)

**Comment by zpao** [comment]
What exactly are you suggesting here? That React support a `hidden` attribute? Or that React supports having `!important` in styles?

**Comment by twoeo** [comment]
@zpao Sorry for that..

Updated.

**Comment by mijamo** [comment]
This is not React specific and is the expected behaviour of this HTML property: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

> Note: Changing the value of the CSS display property on an element with the hidden attribute overrides the behavior. For instance, elements styled display: flex will be displayed despite the hidden attribute's presence.

Please also note the warning in the page:

> The hidden attribute must not be used to hide content that could legitimately be shown in another presentation. For example, it is incorrect to use hidden to hide panels in a tabbed dialog, because the tabbed interface is merely a kind of overflow presentation — one could equally well just show all the form controls in one big page with a scrollbar. It is similarly incorrect to use this attribute to hide content just from one presentation — if something is marked hidden, it is hidden from all presentations, including, for instance, screen readers.

React is just setting this hidden property in HTML, no magic is involved here, and this property is irrelevant for most use-case (probably yours as well if you are trying to display it ...).

**Comment by zpao** [comment]
Thanks for clarifying @twoeo. But as @mijamo correctly notes, this isn't a React issue as your `test` class is overriding the browser-default `display` property.
