### ISSUE TITLE
Warn on inline style update with a bad value

### ISSUE THREAD

**Issue by ouchxp** [facebook/react#6749]
If set an inline style attribute for a component, such as `backgroundColor: 'yellow'`, and then update the state with a bad value to make the inline style like this `backgroundColor: 'non-exist-color'`. This currently takes no effect on the component, and the backgroundColor will remain yellow. (live example: https://jsfiddle.net/d6me6fca/ )

I suppose this is not the correct behavior, the old value should be override by new value, even the value is non-standard, so it can fallback to use the parent style just like plain HTML. If leave the previous style as is, the behavior of component will lose connection with component state, the style will become chaotic and unpredictable.

**Comment by syranide** [comment]
This is a result of CSS simply ignoring you trying to set an invalid value. Preferably React would warn if this can be detected and AFAIK it's something we want to do in dev if it's realistic. This will be indirectly fixed if React switches to setting style via `cssText`, but that's a big if.

**Comment by jimfb** [comment]
Related to https://github.com/facebook/react/issues/5397, potentially fixable by https://github.com/facebook/react/pull/6701

**Comment by BrodaNoel** [comment]
@syranide CSS is not ignoring the color because the color is not updated.
Please, check this issue: https://github.com/facebook/react/issues/12418

If I change the backgroundColor from `red` to `blablabla`, the color still `red` in the DOM. React is not updating the color to `blablabla`.
