### ISSUE TITLE
input element rendered before its cursor gets position in mobile browser.

### ISSUE THREAD

**Issue by hckrmoon** [facebook/react#6755]
**input tag bug**

I am following the official document ([here](https://facebook.github.io/react/docs/forms.html)) . In this document, when user input event occurs we should controller over input value with `state` and  `setState` method.

However, when I tried this code below 

```javascript
_onQuery(e) {
  this.setState({ query: e.target.value });
}
render() {
  return (<input type="text" onChange={e => this._onQuery(e)} value={this.state.query} />);
}
```

It works very well in all browser in PC but not in mobile browser(chrome and safari). The bug is like that when I enter some inputs then I remove by a letter, the cursor get position in second line even though I remove first letter.

I guessed the component rendered with `setState` method before the cursor get positioned. So I tried this code.
```javascript
_onQuery(e) {
  setTimeout(() => this.setState({ query: e.target.value }), 0);
}
```
Then it works well. If my guess is right, it should be fixed.
Thank you.

**Comment by jimfb** [comment]
@hckrmoon Can you create a simple jsfiddle that demonstrates the problem.  Also list the device type (ios/android) and browser version you used.

**Comment by jimfb** [comment]
No response from OP.
