### ISSUE TITLE
Not able to use TestUtils addon outside of npm?

### ISSUE THREAD

**Issue by AkashOmer** [facebook/react#6757]
I am working on an old project and we have now started using React for the UI part. In order to test the React components we need TestUtils addon which comes only with npm but we are using React outside of npm as our project is not built using npm. So is there anyway i can use TestUtils addon outside of npm in my project to test the React Components.

**Comment by ajgreenb** [comment]
Did you install React using npm? If so, you can include `react/dist/react-with-addons.js` and you will be able to access the `TestUtils`.

If you download it directly from the downloads page, you can just download `react-with-addons.js`.

**Comment by zpao** [comment]
As stated, this is a part of the development addons bundle. Thanks for commenting @ajgreenb!
