### ISSUE TITLE
How to use testutil for es6 component?

### ISSUE THREAD

**Issue by naveenideas2it** [facebook/react#6758]
I used to run tests for es5 components using 

    `this.component = TestUtils.renderIntoDocument(React.createElement(Login, null));
    this.renderedDOM` = () => `ReactDOM.findDOMNode(this.component);`

when I changed the component to es6 I am getting

     `Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

I also tried 

      `this.component = TestUtils.renderIntoDocument(<Login/>);`

**Comment by zpao** [comment]
What does your ES6 class look like? Is your import/export set up correctly? Classes will be a function so should never be an object.

**Comment by jimfb** [comment]
Ping @naveenideas2it

**Comment by jimfb** [comment]
No response from OP.
