### ISSUE TITLE
Third party components section, also try to establish a standard.

### ISSUE THREAD

**Issue by kevin-wolf** [facebook/react#676]
Hi all, I was learning and reading through the documentation of React and I've realized it is awesome, even the docs page.

> But I think it can be improved, in order to be more social and _community-driven_.

## The main idea

Build a section like the one who Yeoman's has (yeoman.io/community-generators.html), or the one who GruntJS's has (http://gruntjs.com/plugins), in which I can see all the 3rd party components created on top of React framework.

### Establishing a standard

When authoring public React components, the user should follow a standard, for example, publishing the component to Bower, adding them a prefixed namespace, for example, if I'm creating a _Tree_ component, then I should register it on Bower as `react-component` in order to make it findable and indexable by the section page.

Any thoughts?
Regards.

**Comment by gaearon** [comment]
Closing, as there is still no consensus on many things, and the ecosystem will figure it out eventually.
