### ISSUE TITLE
JSX doc: render HTML tag vs. render ReactElement

### ISSUE THREAD

**Issue by shogunsea** [facebook/react#6761]
In this file: https://github.com/facebook/react/blob/master/docs/docs/02.1-jsx-in-depth.md
Section `HTML Tags vs. React Components`, it says:
> 
React can either render HTML tags (strings) or React components (classes).
>

According to React [terminology](https://facebook.github.io/react/docs/glossary.html), shouldn't it be `render React element`?

**Comment by syranide** [comment]
@shogunsea `<div />` creates a React element which will render a HTML tag. `<Comp />` creates a React element which will render a React component. So it's correct, but it's not super obvious I'll admit.

**Comment by zpao** [comment]
The goal there was to speak at a higher level and try to avoid the intermediate element representation. That's not actually relevant to the understanding there. I agree that it can be a bit confusing, but generally only for people who know enough to skip past that section. I think by raising this point you've made it clear that you know enough :)
