### ISSUE TITLE
ReactPerf 15.1.0-alpha.1 expose isProfiling on the exported object?

### ISSUE THREAD

**Issue by nfcampos** [facebook/react#6762]
I've tested the new Perf tools on one of the screens in one app I'm working on and it works great :)

One thing I wanted also on the old one Perf tools was to be able to check whether the Perf tools are started or stopped, so basically exposing `ReactDebugTool`'s `isProfiling` variable. My use for that is that I have a keyboard shortcut (in development) bound to start/stop the Perf tools and currently I'm forced to maintain such a variable myself to know whether to start or stop (which gets out of sync if I start/stop the perf tools without the keyboard shortcut).

If you don't think it's worthwhile to expose `isProfiling` feel free to close this issue.

**Comment by gaearon** [comment]
`ReactDebugTool` is not a public API by itself, at least not yet. I’m open to adding `isRunning()` to `ReactPerf` though, as it’s the public API. Would you like to send a PR?

**Comment by nfcampos** [comment]
Yeah I'll send a PR :) Should this `isRunning()` method on `ReactPerf` check `ReactDebugTool`'s `isProfiling`, which is not currently exposed, or should keep track of that state separately?

**Comment by gaearon** [comment]
Yeah, we can add `isRunning` to `ReactPerf` and `isProfiling()` to `ReactDebugTool` with the real state being in `ReactDebugTool`.

**Comment by nfcampos** [comment]
the PR should be against which branch? `master`?

**Comment by gaearon** [comment]
Yep!

**Comment by nfcampos** [comment]
I've opened the PR #6763
