### ISSUE TITLE
form elements - readonly attribute ignored

### ISSUE THREAD

**Issue by omerts** [facebook/react#6783]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Readonly attribute doesn't exist in generated real DOM input field

Example:
https://jsfiddle.net/omerts/co6ooske/

**What is the expected behavior?**
Add the readonly attribute to generated input element

React 15.0.1

Credit to user3611459 from stackoverflow's question: http://stackoverflow.com/questions/37253606/react-bootstrap-readonly-input-within-formcontrol

**Comment by zpao** [comment]
You must use `readOnly` (note the camelCase).  We currently have a bug where the warning telling you this is not firing, sorry about that!

**Comment by omerts** [comment]
@zpao thanks :)
