### ISSUE TITLE
Move more shared utilities out of React

### ISSUE THREAD

**Issue by zpao** [facebook/react#6786]
I'm  slowly working on making sure no code at FB depends on modules internal to React. Mostly that involves changing code to use public APIs but there are also several things that are in React which are more general purpose and should be moved out to `fbjs`. The example I'm hitting right now is `isEventSupported`, used by `normalizeWheel`, used by `ReactWheelHandler`, used by a couple modules in Fixed Data Table. I know `adler32` is also used elsewhere, as are some of the transition event detection, and there are surely others.

Mostly this is a reminder to myself to do this and a notice of sorts to others that random files will disappear from the repo and will live in fbjs instead.
- [ ] `isEventSupported`
- [ ] `adler32`

**Comment by syranide** [comment]
@zpao It may be worth remembering that our adler32 implementation is that is excessively optimized for performance, so it may be a good idea to export it under `fast-adler32` or whatever (as opposed to simpler/smaller generic implementations).

**Comment by gaearon** [comment]
Not really relevant anymore.
