### ISSUE TITLE
Option elements do not have selected attribute applied in 15.0.*

### ISSUE THREAD

**Issue by dtuite** [facebook/react#6793]
**Do you want to request a *feature* or report a *bug*?**

Report a bug (regression)

**What is the current behavior?**

`<option/>` elements do not get `selected` attribute applied.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Demo of the issue: http://jsfiddle.net/dtuite/md53wuuf/1/

![screen shot 2016-05-18 at 14 41 20](https://cloud.githubusercontent.com/assets/562403/15360721/9e6f6cd4-1d06-11e6-9aae-4ca80e682731.png)

**What is the expected behavior?**

The currently selected `<option/>` would have the `selected` attribute applied.

Demo of the behaviour in `v0.14.8`: http://jsfiddle.net/dtuite/ct1e4ny8/3/

![screen shot 2016-05-18 at 14 38 26](https://cloud.githubusercontent.com/assets/562403/15360628/41298f96-1d06-11e6-917e-38d76a39abcd.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`15.0.*`. Worked in `v0.14.8`.

**Comment by GGAlanSmithee** [comment]
If I'm not misstaken you are supposed to set the `value` on the `<select>` element instead.

**Comment by gaearon** [comment]
It works though, doesn’t it?

<img width="60" alt="screen shot 2016-05-18 at 17 02 53" src="https://cloud.githubusercontent.com/assets/810438/15366009/63eb44a2-1d1a-11e6-9ee9-31adcbca3438.png">

I haven’t looked into the implementation but I assume the difference is because we are using a JS DOM API to set it rather than an HTML attribute. (Don’t quote me on that though, I’m just making a guess.) The result is the same: it gets selected, just by different means.

Why is the attribute important to you?

**Comment by dtuite** [comment]
It came to my attention because it broke the CI build of a project I'm working on.

At some point we use [Capybara](https://github.com/jnicklas/capybara) to assert that a given option is selected like this:

```ruby
page.find('select#project-switcher > option[selected]').text
```

Other than that, I don't really care. However, I can't think of another way to programatically determine the selected option.

**Comment by twidi** [comment]
Being able to access option[selected] is, indeed, important.

**Comment by gaearon** [comment]
>I can't think of another way to programatically determine the selected option 

Use the DOM API for `<select>`’s `value`:

```js
page.find('select#project-switcher').value
```

>Being able to access option[selected] is, indeed, important.

Why?

**Comment by twidi** [comment]
Being able to access DOM elements via selectors, including attributes, is just a normal way to do it. Some external tools, for example extensions, or external scripts to enhance the page (for onboarding, for example) may use this kind of selector.

BTW, it was just my 2 cents ;)

**Comment by gaearon** [comment]
>Being able to access DOM elements via selectors, including attributes, is just a normal way to do it.

You are using a UI library to abstract away DOM handling. This library has an opinion over how to apply those changes, and that opinion may vary in different versions as well. Whether React uses attributes or properties is an implementation detail of React, and you should not rely on it.

If you’d like to put an attribute on a selected option, do this explicitly: put a `className` or `data-my-custom-attribute` on it. React won’t mess with the attributes you set explicitly, but please don’t expect it to emit any particular attributes for things like `value` on the parent `select`.

I’ll close the issue for this reason. Please feel free to continue the discussion though. Thanks for explaining your reasoning, too. I hope that my answer provides a viable solution for you.
