### ISSUE TITLE
About React Performance

### ISSUE THREAD

**Issue by zenjava** [facebook/react#6794]
A parent component, there are 500 sub-components. When I re-render the parent component, they found each subcomponent execution requires 1ms time to hide when I refresh when you need 500ms. Excuse me, there is no way to handle this scenario. Thank you

**Comment by zpao** [comment]
There's nothing actionable here. No test case, no code. So I'll have to close out. If you have a specific stress test that we can work with, we can talk further, but there's not much we can do with a vague comment about performance.
