### ISSUE TITLE
Replace addons with npm?

### ISSUE THREAD

**Issue by petehunt** [facebook/react#680]
Can we break out the following into separate npm modules and ditch the addons build? We could use wzrd.in to deliver them.
- ReactTransitionGroup
- classSet
- ReactLink
- TapEventPlugin
- ResponderEventPlugin
- ReactStateSetters
- ReactTestUtils

**Comment by rektide** [comment]
Would love to see the react/addons build deprecated. Some of our browserify builds have mad special sauce in them (`--exclude react/addons --require ./node_modules/react/dist/react-with-addons.js:react/addons`) that other browserify-based tools cannot replicate (mochify); it's a frustrating situation to be in and having a consistent entrance point into react and react-addons would reduce this conflict and turmoil.

**Comment by jrsnyder** [comment]
:+1:

**Comment by jimfb** [comment]
Addons are being shipped via npm now.

**Comment by zpao** [comment]
We haven't dropped the addons build entirely yet though so going to keep this open until we do.

**Comment by gaearon** [comment]
We are doing it with 16 (it’s already gone from master). We’ll update the docs before the release but since there’s more to update there, I won’t use this issue to track them.
