### ISSUE TITLE
RFC(ish): Ship 15.1.0 and 15.0.3 as is

### ISSUE THREAD

**Issue by zpao** [facebook/react#6803]
We have a 15.0.3-dev branch and a 15.1.0-dev branch (each published as an alpha). React Native is using 15.1.0-alpha in master and soon to be (already cut?) 0.27-rc. Ideally we wouldn't ship 15.1.0 as is and would get more into it, however it's a real risk to RN to churn while they're in RC. While we could say "that's tough shit, you used an alpha", that's really not cool, we're all a big happy family and we should work together ♥️ (and we told them to use an alpha).

So even if I don't think we should do it in an ideal work, pragmatically we should probably just publish what we already have as final. Since we have 15.0.3 with patch fixes and 15.1.0 on top of that, we can ship both easily.

15.0.3 changes: https://github.com/facebook/react/compare/846b5ea252108d104ab1b67f99879459ef591851...d8d6c7a07b6f0b5015286b62fdb0c5b59a243c13
15.1.0 changes (on top of 15.0.3): https://github.com/facebook/react/compare/d8d6c7a07b6f0b5015286b62fdb0c5b59a243c13...7da88845814fd186e30f657588ea28d20916c6d1

Longer term I don't think shipping and maintaining multiple releases is really tenable for us so it's doubtful we'd ship 15.0.4 (outside of a security release). We will need to properly plan what our cadence is and consider a train-like model. That's tangential to the decision here though so I'll write this down my thoughts on this later and we can discuss wherever that is.

A couple related discussions: https://github.com/facebook/react/issues/6738 & https://github.com/facebook/react-native/issues/7385

**Comment by zpao** [comment]
cc @ide because I'm pretty sure you're on board.

**Comment by ide** [comment]
@zpao thanks - this works for RN.

On a tangent - assuming 15.1.0 follows semver, it should be fully compatible with everyone depending on ^15.0.0 so there's no need for 15.0.4. Multiple releases are necessary only when bumping the major version.

**Comment by gaearon** [comment]
We need to add #6753 to 15.1.0. It fixes a memory leak I introduced earlier.

**Comment by zpao** [comment]
Alright, going to just ship 15.1.0 as is with the additional fix. Even though 15.0.3 is ready it's really unlikely that we'll be following that pattern of parallel patch & minor so no point starting now.

@ide Yup, but there's always risk, especially since semver gets hard to define around the edges. I was just considering the option to provide an out for people who want a smaller set of changes.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/6752 is another fix that needs to get into 15.1.0.
