### ISSUE TITLE
Trying to write an event onChange for multiple fields but getting errors

### ISSUE THREAD

**Issue by abduljafars** [facebook/react#6805]
1) Warning: Failed propType: Invalid prop `type` of type `function` supplied to `FormControl`, expected `string`. Check the render method of `GenericForm

2)Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `GenericForm`. See https://fb.me/react-warning-keys for more information.warning @ warning.js:44
warning.js:44 Warning: String(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.warning @ warning.js:44

3) Warning: String(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
4) Uncaught Invariant Violation: String(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

My files are below

[upld.tar.gz](https://github.com/facebook/react/files/272560/upld.tar.gz)

Please help me out in this if any One.

**Comment by jamesblight** [comment]
You should ask this question on stackoverflow.com. They try and keep this area for actual bugs in react.

It will help if you can share your code using a site like http://jsfiddle.net. People won't want to download a file you uploaded. Feel free to leave a link here to your question on stackoverflow.

**Comment by gaearon** [comment]
Indeed, please use StackOverflow or discussion forums for questions. We use the issue tracker for bugs and feature requests. Feel free to leave a link to your SO questions in this thread. Thank you!
