### ISSUE TITLE
New starter kit?

### ISSUE THREAD

**Issue by petehunt** [facebook/react#681]
I think we could have a much easier starter kit. I think this is pretty good for apps: https://github.com/petehunt/react-browserify-template

And this for modular components (no browserify, just prebuild step): https://github.com/petehunt/react-boilerplate

**Comment by soham85** [comment]
I think react should have an official starter kit just like polymer team provided us with **polymer starter kit**. I think this should have been provided from day one. One simple `npm install` should let us start hacking with react. Apparently being new to react it was not easy to find a template to start with and obviously starting from scratch was not an option and many developers like me will be confused. Please provide us with an official starter kit.

**Comment by gaearon** [comment]
[Create React App](https://github.com/facebookincubator/create-react-app) sort does that.
