### ISSUE TITLE
[React 15.0.2] state.children could be undefined or React.element or Array of element

### ISSUE THREAD

**Issue by chemzqm** [facebook/react#6819]
I just can't understand why it's not always be an array, that would be much easier to work with, since I don't have to check the type each time the children get changed and the performance would likely be better I think.

**Comment by jimfb** [comment]
It is not wrapped because we want to save an object allocation (the allocation of an array object) if you only have a single child.  You should always be using the React.Children utilities, so this should be transparent to you.
