### ISSUE TITLE
npm:  react@15.0.2 does not satisfy its siblings' peerDependencies

### ISSUE THREAD

**Issue by perrierism** [facebook/react#6825]
(bug)

**What is the current behavior?**

`npm install react react-dom`  

Errs : "`The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!`" 

**What is the expected behavior?**

Run `npm install react react-dom` (from React documentation) without error

**Repro**

1. `mkdir repro;cd repro`
2. `npm init` # default / blank answers
3. `npm install react react-dom`

```
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react" "react-dom"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.1.0 wants react@^15.1.0
```

**Other Info**
```
npm version
{ relay101: '1.0.0',
  npm: '2.15.1',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.4',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by stevewillard** [comment]
I think this is probably because react-dom just got bumped to 15.1.0, whereas react hasn't yet been published to npm.

**Comment by BerkeleyTrue** [comment]
This is now resolved.

**Comment by zpao** [comment]
Sorry about that, small mistake while publishing. This should all be working now.

**Comment by azz0r** [comment]
I'm getting issues

`npm WARN prefer global colorguard@1.1.1 should be installed with -g

> fsevents@1.0.11 install /Users/azz0r/Sites/BT/mobile-presales/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/azz0r/Sites/BT/mobile-presales/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-create-fragment@15.0.2 wants react@^15.0.2
npm ERR! peerinvalid Peer react-addons-shallow-compare@15.0.2 wants react@^15.0.2
npm ERR! peerinvalid Peer react-dom@15.0.2 wants react@^15.0.2
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-router@2.4.0 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-router-scroll@0.2.0 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer enzyme@2.3.0 wants react@0.13.x || 0.14.x || ^15.0.0-0
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.1.0 wants react@^15.1.0
npm ERR! peerinvalid Peer react-addons-test-utils@15.1.0 wants react@^15.1.0
npm ERR! peerinvalid Peer react-slick@0.12.2 wants react@^0.14.0 || ^15.0.1
npm ERR! peerinvalid Peer redbox-react@1.2.6 wants react@^0.14.0 || ^15.0.0`

**Comment by gaearon** [comment]
I recommend to switch to npm@3, it has much less annoying warning. If you look at error closely you'll see why it fails:

```
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.1.0 wants react@^15.1.0
npm ERR! peerinvalid Peer react-addons-test-utils@15.1.0 wants react@^15.1.0
```

You have half of React packages at 15.0.2 and another half at 15.1.0. Please use a single version for all of them, and the problem will go away.
