### ISSUE TITLE
Support passing of an array of components into ReactDOM.render

### ISSUE THREAD

**Issue by mstijak** [facebook/react#6827]
I would like to do something like this:
```
ReactDOM.render([
  <Header key="header" />, 
  <Body key="body" />, 
  <Footer key="footer" />
], document.getElementById('app))
```
I couldn't find the answer elsewhere why this is not possible. It's similar to #2127, but not the same.
The algorithm should work the same way as it works now for mounting children inside a component, using keys, etc.

I know that it's simple to wrap everything in a div, but to me, that always felt wrong.

**Comment by jimfb** [comment]
We pass the elements from `React.render()` into a `TopLevelWrapper` component, which just returns `this.props` (aka. the element you passed in), so this is actually the same as #2127.  Fixing #2127 should automatically fix this problem.  Regardless, we probably don't want to change this behavior independently of #2127, so let's just close this out.
