### ISSUE TITLE
RFC: ReactInstrumentation.debugTool.onSetHostNode(debugID, node)

### ISSUE THREAD

**Issue by gaearon** [facebook/react#6834]
We will need a way to get host nodes in React DevTools with the new API. We currently get them by reaching into `ReactDOMComponentTree` directly but I propose to transition to using devtool API (#5306) for this so that other renderers can provide their own host nodes when they become available.

I propose that the renderer code would emit something like

``` js
if (__DEV__) {
  ReactInstrumentation.debugTool.onSetHostNode(inst._debugID, node)
}
```

when node becomes associated and 

``` js
if (__DEV__) {
  ReactInstrumentation.debugTool.onSetHostNode(inst._debugID, null)
}
```

when it is deassociated.

For DOM renderer, it would [happen here](https://github.com/facebook/react/blob/c7ef0af54b86f86acb2198bb2b7f921e205b06c3/src/renderers/dom/client/ReactDOMComponentTree.js#L44-L56).

Then we would add `getHostNode()` to [ReactComponentTreeDevtool](https://github.com/facebook/react/blob/c7ef0af54b86f86acb2198bb2b7f921e205b06c3/src/renderers/shared/devtools/ReactComponentTreeDevtool.js) that would handle `onSetHostNode` event.

Does this sound reasonable? Longer term it would make [something like this](https://twitter.com/CamJackson89/status/734353190502727680) possible in userland.

**Comment by jimfb** [comment]
Sounds reasonable to me, but how are you going to fire it for SFCs when it becomes disassociated?

**Comment by gaearon** [comment]
It would only be called for DOM components. React DevTools would then use the ReactComponentTreeDevtool to establish the closest (DOM) component with a host node.
