### ISSUE TITLE
Possible TypeError in SyntheticUIEvent.js

### ISSUE THREAD

**Issue by vilchik-elena** [facebook/react#6840]
With static analysis we have found this issue on the react's code: https://nemo.sonarqube.org/issues/search#issues=AVTMqSKVtu4QdCAX4XJN

On line 29 there is a null check of `target` but there is no on line 34.

**Comment by jimfb** [comment]
Eeh, this is really a non-issue.  Target is always non-null.  I'll submit a PR to remove the null check, since it is a little confusing, but the extra check really wouldn't have hurt anything.
