### ISSUE TITLE
_reactAddonsPerf2.default.start is not a function

### ISSUE THREAD

**Issue by iMasterAle** [facebook/react#6843]
Hi guys,

I tried to use the Perf.start() with the latest version of `react-addons-perf@15.1.0` and return me this error in console `_reactAddonsPerf2.default.start is not a function`

I used latest version of React and ReactDom.

Have you any idea?

Thanks in advance

**Comment by jimfb** [comment]
Can you provide a simple jsfiddle example that demonstrates the issue?

**Comment by iMasterAle** [comment]
On jsfiddle it's work then I tried to reinstall all react packages and it's work.

I'm sorry @jimfb!
