### ISSUE TITLE
props not passing down when not included in description of component.

### ISSUE THREAD

**Issue by fedgrant** [facebook/react#6863]
I am unsure if this is a bug or the expected behavior.
I have a component two components as below.

```js
import Modal from './Modal'
import InviteForm from './InviteForm'

render() {
    return (
        <Modal>
            <InviteForm
               {...this.props}
           />
        </Modal>

    )
}
```

```js
#in Modal
hideModal () {}

render () {
    return ( 
        <div style={styles.container} ref="container">
            <div id="modal" style={styles.modal} ref="modal">
              { React.cloneElement(this.props.children, {
                   hideModal: this.hideModal
              }) }
          </div>
      </div>
   );
}
```

hideModal is not available in the props of InviteForm in the scenario, but when i include the prop as below, hideModal becomes available in the props. Also whats interesting that, once I include it in the containing file, in the Modal file it will actually overwrite the hideModal prop that was passed down to the InviteForm.

```js
import Modal from './Modal'
import InviteForm from './InviteForm'

render() {
    return (
        <Modal>
            <InviteForm
               hideModal={this.hideModal.bind(this)} <------- here
               {...this.props}
           />
        </Modal>
    )
}
```

I'm using React and React-Dom .0.14.7, Babel 6.5.2 and webpack 1.12.4

**Comment by cpb** [comment]
@fedgrant it looks like this isn't a problem with react.

Does the (passing) test case I added here: https://github.com/cpb/react/commit/fedc31e344ef831ae7ef71e2025f2bbe6352f2bf represent your use case?

**Comment by fedgrant** [comment]
@cpb, it does. Must be something else I am using.
