### ISSUE TITLE
Escaped ampersands in query params within src/href attributes

### ISSUE THREAD

**Issue by pgoldrbx** [facebook/react#6873]
**Ampersands in query params within src/href attributes are being escaped**

Currently, all attributes are sanitized for the browser using [`escapeTextContentForBrowser`](https://github.com/facebook/react/blob/67f8524e88abbf1ac0fd86d38a0477d11fbc7b3e/src/renderers/dom/shared/escapeTextContentForBrowser.js). However, in the case of `src` or `href` attributes, this will escape `&` within query parameters.

**Example**
```js
ReactDOMServer.renderToStaticMarkup(<a href="http://foo.com?a=1&b=2" />);
// => <a href="http://foo.com?a=1&amp;b=2"></a>
```

The attribute name is available until calling [quoteAttributeValueForBrowser](https://github.com/facebook/react/blob/74cce27fe049bbb677c7158de0f3daed5e013fde/src/renderers/dom/shared/DOMPropertyOperations.js#L106). There would need to a be a degree of refactor to create conditional behavior, with consideration given to attributes that might contain urls.

**Possible attributes to alter**

* `src`
* `href`
* `data-` variations of the above

I don't know if this is a bug or if it exists by design, for non-obvious reasons.

Versions `0.14.x`, `15.x`

**Comment by syranide** [comment]
Not a bug, this is all according to spec. Not escaping *would be a bug*; consider if the URL you provide is `http://foobar/foo&amp;bar/`, the browser would then translate that to `http://foobar/foo&bar/` unless it wasn't first escaped, that is not what you intended.

Why are you bringing this up, are you seeing any problems?

**Comment by poscar** [comment]
Ah, I see. So whoever is in the receiving end of the markup (e.g. browser, but could be somethign else) should be sticking to the spec and parsing escaped ampersands correctly.

**Comment by pgoldrbx** [comment]
@syranide Correct, I would not expect ampersands within a uri to be unescaped. However it's the query string that I'm concerned with. e.g.

```
http://foobar/foo&amp;bar/?foo=1&bar=2
```

**Comment by syranide** [comment]
@pgoldrbx It should still be escaped, render and click it and you'll see.

**Comment by pgoldrbx** [comment]
@syranide — confirmed. will close.

* anchor => renders escaped => clicking through behaves as desired
* iframe => passes params to the server => both hapi and express receive params as expected

**Comment by alexmarchant** [comment]
I actually have an issue here... using react on wordpress and my logout URL is being rendered as such:
```
http://localhost:8888/wp-login.php?action=logout&amp;_wpnonce=fdc432e270&amp;redirect_to=http%3A%2F%2Flocalhost%3A8888
```

Wordpress is not parsing this correctly and is not picking up the `_wpnonce` param.

**Comment by pgoldrbx** [comment]
@alexmarchant — this appears doubly escaped — is the url escaped already prior to rendering it with react?

**Comment by alexmarchant** [comment]
@pgoldrbx oh ya you're right, didn't even notice that until pasting it here, it actually shows normally in the url:

![image](https://cloud.githubusercontent.com/assets/953244/16289327/303c19ba-38c2-11e6-9f86-dfb7e5ac21c4.png)

Weird. Looking more into it.

**Comment by alexmarchant** [comment]
@pgoldrbx Thought maybe it was ReactDOMServer.renderToString, but just threw together a jsfiddle, https://jsfiddle.net/alex_marchant/pyadp4eg/4/, and it looks like it's working fine. Must be something on my end server side. Thanks for the helpful comment.

**Comment by depoulo** [comment]
Unfortunately, Facebook's in-app browser, or whatever sends `x-fb-http-engine: Liger`, doesn't seem to stick to the spec, giving us thousands of access log entries per day with non-unescaped query parameters in image URLs (ironically, the escaping is done by React on our servers).
