### ISSUE TITLE
[DOCS] Production note needs updated

### ISSUE THREAD

**Issue by Someguy123** [facebook/react#6875]
Couldn't find a react-docs repo or anything, so I'm posting it here.

I just spent the past 30 mins googling how to get webpack to build React in production, and the page https://facebook.github.io/react/downloads.html wasn't very clear.

I ended up having to hunt down a "production is undefined" error, and ended up asking on the IRC before I could get a clear answer.

The CORRECT way to build react in production, is to add the following to your plugins array:

    new webpack.DefinePlugin({
        'process.env': {
            NODE_ENV: '"production"'
        }
    }),

Would be great to get this on the docs. Notice that production is a string, containing `"production"` with LITERAL double quotes. Here is the page (might be others too) in question: https://facebook.github.io/react/downloads.html

**Comment by zpao** [comment]
Sorry that took so long! We don't have this on the download page but we do have it elsewhere: http://facebook.github.io/react/docs/package-management.html#using-react-from-npm where we say to use this:

```js
new webpack.DefinePlugin({
  "process.env": {
    NODE_ENV: JSON.stringify("production")
  }
});
```

(the `JSON.stringify` ensures it's a quoted quoted string)

Granted, that page needs some more attention to make this easier to find, but we do have it documented. We should probably link to this page from the downloads page.
