### ISSUE TITLE
String with whitespace causes uniteless css warning

### ISSUE THREAD

**Issue by jonashaefele** [facebook/react#6888]
**What is the current behavior?**
Assigning a style object with  `content: " "` to component results in a unitless CSS warning:

```warning: a `div` tag (owner: `unknown`) was passed a numeric string value for CSS property `content` (value: ` `) which will be treated as a unitless number in a future version of React.```

Demo Fiddle with `content: ""`
https://jsfiddle.net/oktkht5g/

Demo fiddle with `content: ""`
https://jsfiddle.net/o014p2mf/1/

**What is the expected behavior?**
Only throw warnings for CSS properties that need them. `content` could be any string or one of the following values:

`normal | none | [ <string> | <uri> | <counter> | attr() | open-quote | close-quote | no-open-quote | no-close-quote ]+`

**Which versions of React**
Tested in React 15.1.0

**Comment by alexzherdev** [comment]
Proposing a fix in #6928.

**Comment by jonashaefele** [comment]
Thanks!

**Comment by jimfb** [comment]
Fixed in https://github.com/facebook/react/pull/6899.
