### ISSUE TITLE
Docs enhancement: Link to source

### ISSUE THREAD

**Issue by grgur** [facebook/react#6891]
I thought it might be useful to be able to jump to the source code right from the documentation.

E.g. If [`ReactDOM.render`](http://facebook.github.io/react/docs/top-level-api.html#reactdom.render) section in docs included a link to the [source](https://github.com/facebook/react/blob/master/src/renderers/dom/client/ReactMount.js#L530) in Github.

I believe easier access to the source code will increase familiarity with how things work in the background and perhaps induce community involvement. 

I also understand this might add complexity to docs management and it could also be difficult to point to the right source file when e.g. depends on the platform server/client). 

Maybe I'm spoiled with how [JSDuck handles it](http://docs.sencha.com/extjs/6.0/6.0.2-classic/#!/api/Ext.container.Container).

Any ideas are welcome here.

**Comment by jimfb** [comment]
The vast majority of users really have no reason to jump into the React source code.  And the React source code is complex enough that jumping into the code is not going to give a user a meaningful understanding of how things work.

Feel free to continue the discussion on this thread.  We can re-open this issue if our thinking on this matter changes substantially.
