### ISSUE TITLE
Building things upon react's diff algorithm

### ISSUE THREAD

**Issue by fab1an** [facebook/react#6906]
Since React 0.14 the tree-diffing and DOM rendering is decoupled, paving the way to projects like https://github.com/Flipboard/react-canvas

Is there a way to give the tree-diffing algorithm clues about which operations are fast and which are slow?

* Suppose I have fictitious draw-model where just updating a certain property in a node is much more expensive than recreating the entire node. Can I tell react this?
* Or that I have situation where I switch `A` for `B` but have a really easy way to "repurpose" `A` to become `B`.

**Comment by jimfb** [comment]
The best medium for discussions like this is probably discuss.reactjs.org

We use github for tracking bugs in the react core.  For this reason, I'm going to close out the issue, but feel free to continue the discussion on this thread or move it to discuss.reactjs.org.

**Comment by fab1an** [comment]
I thought this too and I will move my question there, thought in my experience you don't get answer to question like these there (nor on SO), because most people don't know enough about react-internals.

**Comment by iamdustan** [comment]
Other places community members be:

[reactiflux #react-contributors]([reactiflux #react-internals](https://discordapp.com/channels/102860784329052160/148818842779385856)
[reactiflux #react-internals](https://discordapp.com/channels/102860784329052160/148818842779385856)

**Comment by fab1an** [comment]
For the record, I got this answer [here](https://discuss.reactjs.org/t/giving-clues-to-reacts-diff-algorithm/4053/2)
* React reuses a component if the type and key match. So if you want to force recreation of a node, you need to assign a key to it that changes.

* If you want to swap one component for another without recreating any nodes, you need to make sure that the types match all the way down. That is, replacing `<A />` with `<B />` will always unmount A completely then mount B if A !== B.

* React 0.14 and earlier used to generate HTML whenever mounting any new subtree (so if you were to add a new item to a list or swap `<A />` for `<B />`, the markup for the new list item or for `<B />` would be set using .innerHTML). React 15 uses document.createElement directly and only sets .innerHTML when using dangerouslySetInnerHTML.
