### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by chicoxyzzy** [facebook/react#6910]
There are no official or blessed TypeScript definitions for React and ReactDOM (and Jest).

There are definitions in DefinitelyTyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react-dom.d.ts
(and https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jest/jest.d.ts)

But these type definitions are outdated and DefinitelyTyped is outdated too in favour of [Typing](https://github.com/typings/typings) which has some [advantages](https://github.com/typings/typings/blob/master/docs/external-modules.md) over DT.

I want to create type definitions for Typings and create a PR to use them instead of hardcoded, poor-quality definitions from React repo ([1](https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/React.d.ts), [2](https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/ReactDOM.d.ts), [3](https://github.com/facebook/react/blob/master/scripts/jest/jest.d.ts)). This will help to reuse type definitions [for React repo](https://github.com/facebook/react/blob/master/scripts/jest/ts-preprocessor.js#L30-L57) and any React applications made by TypeScript developers.

My current plan is to create up-to-date Typings TypeScript definitions for each
- [ ] React 
- [ ] ReactDOM

No plans for Jest because I prefer `tape`.

So before I start...

Do you prefer type definitions to be official or community-driven?
Do you have any suggestions or corrections to my plan?

**Comment by zpao** [comment]
Community driven sounds fine by me. If we want to contribute to them in the future we can but it removes the burden of support since we aren't likely to be actively maintaining them. The only downside is that if we do make changes locally and want to upgrade our defs before an official release, I'm not sure what that process would look like. As long as that's still possible for us to do, then I have no qualms and your plan sounds good 👍

**Comment by vsiao** [comment]
@chicoxyzzy, how are the DT typings outdated? As mentioned in https://github.com/typings/typings/issues/418 I want to avoid forking the type definitions and having multiple sources of truth, if possible.

**Comment by DanielRosenwasser** [comment]
Hey @chicoxyzzy, it might be better to hold off on any moves from DT. We're currently exploring an alternate `.d.ts` acquisition story for 2.0, so I'd wait on that before making any major changes.

**Comment by chicoxyzzy** [comment]
@vsiao I think it's good to have one source of truth. BTW aren't current definitions global?

@DanielRosenwasser sure. Can you tell what can change in 2.0? Any Github issues we can follow?

**Comment by chicoxyzzy** [comment]
oh looks like React definitions in DT repo are not global so I think we probably can set them up using typings

**Comment by chicoxyzzy** [comment]
For everyone interested in this issue, that's how definitions delivery will work in TypeScript 2
https://github.com/Microsoft/TypeScript/issues/9184

React definitions will stay at DT repo.

Closing this.
