### ISSUE TITLE
 <span> cannot appear as a child of <tbody>

### ISSUE THREAD

**Issue by xinghengwang** [facebook/react#6911]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
I have this in my render function for one of my rows of data. 

`         <tr>
                <td>Elapsed Time</td>
                <td><i className="fa fa-clock-o"></i>{elaspedTime + ' ms'}</td>
              </tr>
` 

So I noticed that react automatically put a span tag around elapsedTime + ms, which triggers the Dom Validation warning issue. of <span> cannot appear as a child of the <tbody>

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

Not put a span tag around my text. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

0.14.8

**Comment by zpao** [comment]
React 15 removed the use of spans around text nodes so that should go away if you upgrade. We won't be back porting the change to 14. in the mean time you could use rows and cells to make it so the spans are ok to use.
