### ISSUE TITLE
Form disappears without calling onSubmit

### ISSUE THREAD

**Issue by fritz-c** [facebook/react#6916]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug

**What is the current behavior?**
When a form element disappears as the result of a state change (e.g., triggered by an onClick handler on the submit button), its onSubmit handler is not called. In HTML, even if a form element is removed from the DOM, its onSubmit handler is still called.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Plain JS + HTML version (expected behavior): https://jsfiddle.net/b22925dw/
Reproduced in React: https://jsfiddle.net/yaf6p0ga/1/
_The commented-out setTimeout in the react code is a usable hack to fix it for the time being_

**What is the expected behavior?**
The code specified in the form's onSubmit should be executed before the form disappears.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.0.2 / Chrome 51.0.2704.63 (64-bit) / OS X 10.11.5

**Comment by satya164** [comment]
@fritz-c React doesn't really add the listeners to the actual DOM elements like your other example does. It adds the listeners to the root and uses event delegation to capture the events. For example, if you do the following,

```js
document.addEventListener('submit', () => console.log('Form submitted'))
document.addEventListener('click', () => console.log('Button clicked'))
```

The submit event doesn't really fire. This is because, when you click on the button, it synchronously removed the form element, preventing the submit event to bubble up to the root.

**Comment by nhunzaker** [comment]
I believe that this is the correct behavior. It looks like this is in the HTML specification, and Chrome adopted it in March of 2017:

**Source:**
https://blog.michaelchen.io/form-submisson-cancelled/

**Spec:**
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-algorithm

Submitting a detached form yields the following warning:
![image](https://user-images.githubusercontent.com/590904/43669999-5e2bd9c0-973c-11e8-8e7c-60c7ee879147.png)

I can only speculate that this is for security reasons, but I haven't found a definitive answer.

Still, I attempted to do this with `addEventListener`:
https://jsfiddle.net/b22925dw/6/

And with a modern version of React (16.3.2):
https://codesandbox.io/s/wlm354lrw

Both yield the exact same warning.

React presently appears to be consistent the HTML/JS approach, and the HTML specification.

Closing this, but please let me know if I have missed something!
