### ISSUE TITLE
HTML to JSX not working

### ISSUE THREAD

**Issue by aris-b** [facebook/react#6918]
Hi, just wanted to report that this page: https://facebook.github.io/react/html-jsx.html
is not working.

`ReferenceError: HTMLtoJSX is not defined`

**Comment by brotzky** [comment]
It looks like an HTTPS error: 
**http**://magic.reactjs.net/htmltojsx.min.js is not loading properly on **https**://facebook.github.io/react/html-jsx.html

I recommend trying //magic.reactjs.net/htmltojsx.min.js.

**Comment by alexzherdev** [comment]
html-jsx.md references https://reactcommunity.org/react-magic/htmltojsx.min.js, but that URL currently gives out a permanent 301 redirect which leads to http://magic.reactjs.net/htmltojsx.min.js.

A possible way to fix might be to replace https://reactcommunity.org/react-magic/htmltojsx.min.js with **https**://magic.reactjs.net/htmltojsx.min.js and see if there are no CORS issues.

**Comment by alexzherdev** [comment]
Looks like this was fixed in #6904. There is now a redirect to a separate site that works fine.

**Comment by zpao** [comment]
Yea, this page redirects now so nothing to do here.
