### ISSUE TITLE
About "onDoubleClick" Event Bug

### ISSUE THREAD

**Issue by zenjava** [facebook/react#6920]
When I use 'onDoubleClick" event.
I found a problem, and if I do not move the mouse. Double-click has been found onDoubleClick Event is not triggered.

**Comment by zenjava** [comment]
In IE 11 is OK, But in chrome 49.0 is wrong.

**Comment by satya164** [comment]
Can you provide a jsbin example of the issue?

**Comment by zenjava** [comment]
createSelectedCell(args) {
        let
            {
                mergeCell,
                displayText,
                focusCellOffset : focusStyle,
                columns,
                onDoubleClick,
                onClick,
                error,
                point,
                rowStyle,
                cellStyle,
                columnStyle,
                selectedRowInfo,
                getRowStyle
            } = args,
            height = focusStyle.get("height"),
            width = focusStyle.get("width"),
            left = focusStyle.get("left"),
            top = focusStyle.get("top"),
            row = point.get(0),
            column = point.get(1),
            className = "cell_focus ",
            columnCfg = columns.get(column),
            {rowKey, field, row : rowData} = selectedRowInfo;
        let
            isMoney = columnCfg.get("isMoney"),
            cellProps,
            errTxt = GridSupportUtils.getErrorText(row, field, error);
        cellProps = {
            key: "selectedCell",
            className,
            style: {
                width,
                height,
                top,
                left
            },
            onClick,
            onDoubleClick
        };


        if (errTxt) {
            cellProps.className += " error";
        }
        return <span {...cellProps}></span>;
    }

like this

**Comment by jimfb** [comment]
@zenjava The code you have provided is not actionable.  Among other things, it references variables (like `focusStyle`) which are undefined.

We are going to need a simplified jsfiddle that demonstrates the issue.

**Comment by jimfb** [comment]
No response from OP, closing.
