### ISSUE TITLE
Where to put JS code related to UI, but not React

### ISSUE THREAD

**Issue by zhirzh** [facebook/react#6922]
Suppose I render a table in some react component and want to add some features to it:
- Make its columns resizable
- Bind several keypress events (up/down to highlight, shift+up/down to select, enter to do some processing etc.)

None of these tasks have anything to do with react aspect of the component (states, props, component lifecycle etc).

In such a scenario, where will I write the "UI features" code?

1. Inside `Component.jsx`
1. In some other `component.js` file and import it in corresponding jsx file
1. Some other place entirely

Please advise.

**Comment by satya164** [comment]
What do you mean by "UI features that have nothing to do with React"? React is a library to help you manage your UI, so anything related to UI is better written as react components. For your use case, you can probably have a `Table` component, the column sizes can be stored in the component's state (or global state), the key bindings can be done with react's event system etc.

**Comment by zhirzh** [comment]
I previously thought about creating another component, but the table has "refs" that are needed for other functions, so can't do that.
ANyways, I'll take your advice and shift to the forum.
