### ISSUE TITLE
Warn for all unsupported lifecycles in stateless Components

### ISSUE THREAD

**Issue by gingur** [facebook/react#6926]
Example: https://jsfiddle.net/gingur/u0h2rjae/1/

When generating **child context** with a stateless Component, the context is not available to the children.

**Comment by gingur** [comment]
Apparently none of the Component lifecycle events are supported, if it is intended that context is also not supported then suggest a warning to be thrown when using a non-production build of React.

**Comment by jimfb** [comment]
Yeah, a warning for all the lifecycles is probably a good idea.

**Comment by gingur** [comment]
Would https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L42 be the correct location to specify the warning?

**Comment by jimfb** [comment]
Yeah, that sounds like a reasonable place to me.  cc @spicyj for confirmation.

**Comment by spicyj** [comment]
I don't think this makes much sense because the mental model is that these functions are called, not constructed – so the prototype shouldn't come into play at all. But I guess that's a reasonable place if we do want the warning.

**Comment by jimfb** [comment]
Yeah, but we sort of violate the mental model with contextTypes and propTypes and related properties that get set on the function.  I can see how someone could think they could add a lifecycle function in the same way.  There really isn't any harm in adding a warning, and it might help people catch errors in their mental model.

**Comment by gingur** [comment]
If at a minimum `childContextTypes` could trigger a warning since `contextTypes`, `propTypes` and `defaultProps` are supported but do not require an additional prototype function such as `getChildContext` to be available.

**Comment by spicyj** [comment]
Yeah, that makes sense. Let's start with childContextTypes and revisit if anyone else is confused after that.
