### ISSUE TITLE
Default props for inherited components not working in IE10

### ISSUE THREAD

**Issue by joevp** [facebook/react#6929]
Default props declared on a base class are not found by inheriting classes in IE10. This was observed in react `0.14.7` and `15.1.0`. The example and codepen below should help reproduce.

http://codepen.io/anon/pen/zBxBwV?editors=0011

```js
class TestBase extends React.Component {
  constructor(props) {
    super(props);
  }
}

TestBase.defaultProps = {
  message: 'this is a test message',
};

class Test extends TestBase {
  constructor(props) {
    super(props);
  }
  
  render() {
    return <div>{this.props.message}</div>;
  }
}

ReactDOM.render(
  <Test />,
  document.querySelector('main')
);
```

**Comment by vickenliu** [comment]
on the codepen page, it works fine. it renders 'this is a test message'  @joevp

**Comment by joevp** [comment]
Using IE10? Hmm, is your browser configured in some way other than the default?

**Comment by jimfb** [comment]
Confirmed, I see the same behavior on IE10.

@joevp The inheritance pattern is not a priority for us (also this affects only legacy browsers), but we would probably take a PR to fix this if you'd like to write up a fix.

**Comment by jimfb** [comment]
It's also not clear to me if this is a babel bug or a React bug.

**Comment by jimfb** [comment]
It's also not clear to me if this is a babel bug or a React bug.  cc @hzoo @kittens

**Comment by hzoo** [comment]
@joevp I would try the classes transform with loose mode + transform-proto-to-assign if you are using babel - ref http://babeljs.io/docs/usage/caveats/#internet-explorer

**Comment by jimfb** [comment]
Thanks @hzoo!

Yep, I think that mostly solves this mystery.  I'm going to close this out as not-a-react-bug.  But @joevp, if you see an easy workaround that would allow us to support this in the core, we'd likely take such a PR.

**Comment by joevp** [comment]
Looks like this might be a potential fix, but I haven't tested for any other side effects yet:

1. Update the original example to set default props on the base component's prototype (`TestBase.prototype.defaultProps = ...`)
2. Update [this logic in ReactElement](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L199-L200) to look at `type.prototype.defaultProps` as well.

**Comment by hannesj** [comment]
@jimfb It seems this was fixed recently (6.14.0) in babel (https://github.com/babel/babel/pull/3527). Should I do a PR to update `babel-plugin-transform-es2015-classes` or dou you have another process for keeping the dependencies up to date?

**Comment by jimfb** [comment]
@hannesj I think Paul usually updates the dependencies in batches, but yeah, I suspect a PR would be welcomed.  cc @zpao

**Comment by xfields** [comment]
Try this https://github.com/xfields/ie-class-inheritance-polyfill
