### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by omerts** [facebook/react#6939]
Trying to run `grunt test` on version 16.0.0-alpha return `no tests found`:
![image](https://cloud.githubusercontent.com/assets/4996164/15706205/1055a88c-27fb-11e6-8caa-9d9b078c2564.png)

**Comment by Aweary** [comment]
@omerts running `grunt test` on the master branch seems to work fine for me, did you forget to run `npm install` after cloning possibly?

**Comment by omerts** [comment]
@Aweary are you getting test results? FWIW, I am on a windows machine .

**Comment by cpb** [comment]
I am getting test results on master with archlinux

**Comment by Aweary** [comment]
@omerts have you made any changes locally? I'm on OS X and I do get test results as well.

**Comment by zpao** [comment]
I'm pretty sure tests used to run fine on Windows. I don't have a VM handy to test myself right now. cc @cpojer in case some of the recent jest upgrades have broken that (perhaps something with haste and the filesystem).

**Comment by cpojer** [comment]
It should work fine with 12.1.1.

**Comment by omerts** [comment]
@Aweary, I did make changes, but I get the same no tests found even when switching back to master.

I don't have any experience with jest, I just know that it looks for `__tests__`. Does it look for it recursively? Because looking at the root directory I don't see any `__tests__ `folder, only in sub-directories. Maybe there is some problem with the directory lookup in windows.

Specs:
Windows 7 64-bit
node v4.4.0
npm v3.8.1


To make sure, I just did a fresh clone as follows:
```
git clone https://github.com/facebook/react.git
cd react
npm i
grunt build
grunt test
```
Still same error:
![image](https://cloud.githubusercontent.com/assets/4996164/15718799/c4c3fc44-2835-11e6-8fed-4f77d874aae9.png)

**Comment by cpojer** [comment]
We are working on fixing this for the next Jest release. Sorry that this is causing trouble.

**Comment by Daniel15** [comment]
Hmm... Even when I pass an absolute file path, it still can't find test files:
```
 .\node_modules\.bin\jest C:\src\react\src\shared\utils\__tests__\KeyEscapeUtils-test.js
Using Jest CLI v12.1.1, jasmine2
No tests found for "C:\src\react\src\shared\utils\__tests__\KeyEscapeUtils-test.js".
```

I suspect this is an issue in Jest, however I'm currently blocked from easily investigating as Jest doesn't build on Windows due to https://github.com/lerna/lerna/issues/226. I'll investigate more once I get Jest to build properly

**Comment by Daniel15** [comment]
If I create a brand new project using Jest v12.1.1 and make a single test in `__tests__\foo-test.js`, it works fine:
```
C:\src\_temp\testappwithjest  (testappwithjest@1.0.0)
λ node_modules\.bin\jest.cmd
Using Jest CLI v12.1.1, jasmine2
 PASS  __tests__\foo-test.js (0.02s)
1 test passed (1 total in 1 test suite, run time 0.946s)
```

I wonder if it has something to do with the configuration in this repository specifically.

**Comment by Daniel15** [comment]
If I create a brand new project using Jest v12.1.1 and make a single test in `__tests__\foo-test.js`, it works fine:

![Screenshot](http://ss.dan.cx/2016/06/ConEmu_16-23.12.14.png)

I wonder if it has something to do with the configuration in this repository specifically.

**Comment by Daniel15** [comment]
Found the bug, it only occurs when `testFileExtensions` is enabled. Moved to Jest repo: https://github.com/facebook/jest/issues/1180

**Comment by zpao** [comment]
Thanks for finding that @Daniel15!

**Comment by andrerpena** [comment]
I'm still having this problem on Windows. I suppose jest hasn't been updated to ^13.0.0 on master yet

**Comment by andrerpena** [comment]
Yes.. updated to 13.0.0 and it now finds 120 tests
