### ISSUE TITLE
React.cloneElement docs are a bit light

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#6942]
The old `cloneWithProps` has a nice example, but mentions that it's deprecated in favour of `React.cloneElement` - https://facebook.github.io/react/docs/clone-with-props.html

Meanwhile https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement is pretty terse, and links to a blog post from 0.13rc2 which has a decent example.

I'm proposing adding a guide page about "modifying" child properties which has a very similar example to the old `cloneWithProps` page, and then linking to it from there and the cloneElement API docs.

Seem reasonable? I can put together a PR if so.

**Comment by barbu110** [comment]
+1

**Comment by gaearon** [comment]
Added this to #8060.

**Comment by madhug** [comment]
is someone working on this or can i take a stab at it?

**Comment by gaearon** [comment]
@madhug Definitely, you can take it! I imagine this as a single guide that combines how you'd use cloneElement and React.Children helpers.

**Comment by madhug** [comment]
Cool thanks! I'll start working on it this weekend!
