### ISSUE TITLE
Document how to reduce bundle size

### ISSUE THREAD

**Issue by AlastairTaft** [facebook/react#6947]
I've been trying to optimise my bundle and it seems to me that the standard react import `import React from 'react'` includes more code for backwards compatibility than react itself.

I've found that including react this way `import React from 'react/lib/ReactIsomorphic` reduces my bundle size from ~177kb to ~77kb.

Can this be documented or better supported? It's a significant gain. Or have some standard way to import only react that isn't going to break in future updates.

**Comment by AlastairTaft** [comment]
Also swapped the `import { render } from 'react-dom'` to `import { render } from 'react/lib/ReactMount'`. I didn't realise the react-dom package pointed back at the react package.

**Comment by AlastairTaft** [comment]
Just checked my package deps, I'm on `0.14.7` so if things have drastically changed in v15 this can be closed.

**Comment by AlastairTaft** [comment]
Doesn't look like an issue in v15

**Comment by zpao** [comment]
FWIW I don't this the overall difference should be noticeable at the end of the day. The react package in 14 did export dom related things as we deprecated. The react-dom package was (and still is in 15) just pointing directly into the react package so the same files that were getting exported on react were in use once you used react-dom. Total size should be pretty similar as a result. Now if you never used react-dom, you were paying that cost in 14 and won't be in 15.

**Comment by AlastairTaft** [comment]
Thanks for the reply. I think I came to the same conclusion and just upgraded to v15 without any modifications to the import path.
