### ISSUE TITLE
Distribute compiled files on NPM package

### ISSUE THREAD

**Issue by fnando** [facebook/react#6952]
Right now, the NPM package just distributes files that are good to be used with Node.js. You must precompile them with some build system before you can use them.

Would be really nice to have the same files of the [Bower package](https://github.com/reactjs/react-bower) distributed in a `dist` directory (both react.js and react-dom.js) or something like that, as NPM is now also being used for client-side package management.

**Comment by jimfb** [comment]
@zpao

**Comment by zpao** [comment]
`react` and `react-with-addons` are already there in the `dist/` directory of the `react` package. `react-dom` and `react-dom-server` are a part of the `dist/` directory of the `react-dom` package.
