### ISSUE TITLE
Using React 15. After transformation of outer div removed with attributes

### ISSUE THREAD

**Issue by dmitrymalakhov** [facebook/react#6954]
React 15.1.0
Chrome 47.0.2526.80 (64-bit) / FireFox 33.0

```
getView() {
  return <div className='list-type'>
    <div className='item'></div>
    <div className='item'></div>
  </div>;
}
```

after transformation of outter div removed

```
<div className='item'></div>
<div className='item'></div>
```

**Comment by zpao** [comment]
Can you be more specific about where or when this is happening? Or give a test case. There's nothing actionable for us with what you've provided.
