### ISSUE TITLE
Feature: let shouldComponentUpdate also return which props triggered the update for non-immutable deep comparisons

### ISSUE THREAD

**Issue by pke** [facebook/react#6955]
Currently `shouldComponentUpdate` shallow/deep checks the components props/state and returns only a boolean value.

Then, when in `componentDidUpdate` is triggered because of the proposed update hook we again need to check which prop has actually changed. So basically (in case of a deep check) we are performing the same expensive comparison twice.

I know, with `immutable` props this problem would not arise, but not all react apps can commit to use `immutable` props. Also, the `style` object is often not immutable and therefore, despite beeing deep equal, would still trigger a re-render of the component.

So I propose to introduce (a non-breaking?) change to let `shouldComponentUpdate` return an array of property names that triggered the update. React would have to check

```
const shouldUpdate = shouldComponentUpdate(...)
return shouldUpdate === true || shouldUpdate.length > 0
```

Then in `componentDidUpdate` we could do:

```
componentDidUpdate(prevProps, prevState, propNames, stateNames)  {
  if (propNames.contains("expensiveProperty")) {
    ...
  }
}
```

**Comment by jimfb** [comment]
Honestly, this shouldn't be a very common pattern, and shouldn't be coming up often enough that it would justify adding this feature.  I don't think we would do this, so I'm going to close this out (we can re-open if our thinking changes).

However, I am curious what your use case is.  What are you doing in your componentDidUpdate once you've figured out which props have changed?
