### ISSUE TITLE
stopPropagation affects the same level DOM node handlers

### ISSUE THREAD

**Issue by caub** [facebook/react#6965]
When doing `.stopPropagation()` from React, I'd expect that the corresponding DOM element events are still fired since they are at the same level.

Just raising the issue, I'm not sure if it's worth changing the current behaviour

https://jsfiddle.net/4p2orbuw/1/ (check console after focusing then bluring the two 'hello ce')

**Comment by gaearon** [comment]
`e.stopPropagation()` will only affect the propagation of the React event through React component hierarchy.
