### ISSUE TITLE
enter key not captured by 'onChange/onInput'

### ISSUE THREAD

**Issue by sydcanem** [facebook/react#697]
I don't know if this is silly or I miss something but pressing the enter does not trigger an onChange/onInput on text inputs.

**Comment by rahul7977** [comment]
same issue for spaceBar
could you plz help me

**Comment by krishmarsonia** [comment]
> @syranide I see now. Thanks for helping. @spicyj Thanks.

@syranide What was your last solution that you applied and worked?
