### ISSUE TITLE
The document of test utils is out of date

### ISSUE THREAD

**Issue by kpaxqin** [facebook/react#6970]
In react > 0.14, the following methods will return `DOMElement` instead of `ReactComponent`: 

1. scryRenderedDOMComponentsWithClass
2. findRenderedDOMComponentWithClass
3. scryRenderedDOMComponentsWithTag
4. findRenderedDOMComponentWithTag

But the [guide page of test utilities](https://facebook.github.io/react/docs/test-utils.html#findrendereddomcomponentwithclass) still says it will return `ReactComponent`.

You can check props of a `ReactComponent`, but can't do the same thing on `DOMElement`, so I think we'd better make it up to date to avoid make people get confuse.

**Comment by kpaxqin** [comment]
Make a PR for it: https://github.com/facebook/react/pull/6971

**Comment by siemiatj** [comment]
The PR was merged, so this can be closed now.

**Comment by jimfb** [comment]
Fixed in #6971
