### ISSUE TITLE
New React.Perf eats a lot of CPU.

### ISSUE THREAD

**Issue by niba** [facebook/react#6983]
After migration to React 15.1.0 I noticed that my application is running slower than usual. Quick debug with Chrome profiler shows that  method `purgeUnmountedComponents` from `ReactComponentTreeDevtool` eats around 30% of my application time. On every mouse move or click method iterates over huge amount of elements. I don't know if that behaviour is desirable.

![reactperfcpu](https://cloud.githubusercontent.com/assets/2017454/15851913/54cbed52-2c9f-11e6-90bd-915aeb4e58a1.PNG)

**Comment by gaearon** [comment]
Hi! Could you try building React from master and giving it another try? I know @spicyj optimized some of this in https://github.com/facebook/react/pull/6770 but it hasn't been released yet.

**Comment by gaearon** [comment]
For now I’ll mark as unconfirmed, but I’m happy to look into it if you provide an example app that reproduces this.

**Comment by niba** [comment]
I have just checked it with the latest version from master and it is better. 

![reactmasterperfcpu](https://cloud.githubusercontent.com/assets/2017454/15922974/d35197b2-2e2a-11e6-8a30-87a4d3a2e1a4.PNG)

![reactmasterperf2](https://cloud.githubusercontent.com/assets/2017454/15922977/d6f98c1c-2e2a-11e6-90f1-038a2d917901.PNG)

Stil it eats around 15-20% but maybe it is connected with my shouldComponentUpdates. I need to analyze it more closely.

**Comment by gabrielenosso** [comment]
I have the same problem.
I didn't try with the "master" though.

**Comment by spicyj** [comment]
As far as I can tell your last two screenshots don't show anything from the perf tools? The function names there all just look like normal batching/update code.

**Comment by niba** [comment]
@gaearon Thanks for help

@spicyj I know that you closed it but I observed one more thing regarding that topic.

I'm developing a map based web app where user mostly just browse and move around on the map. These actions fire a lot of map events like `zoomIn, zoomOut, mapMove`. Here is a screenshot from profiler after one of those session when user just browse map and don't use heavily react part of application. React@master(after 15.1.0) eats here about ~9% of my CPU

![perflast2](https://cloud.githubusercontent.com/assets/2017454/15956845/75ac249e-2eeb-11e6-89c6-f58a223d29c8.PNG)

and now the similar session with React@0.14.7, here we have ~3-5%

![oldreactlast](https://cloud.githubusercontent.com/assets/2017454/15956960/2fc0ece8-2eec-11e6-8889-08ec3f3aaa4f.PNG)

as you can see the time is much bigger in the latest version. I wanted to let you know about this

**Comment by gaearon** [comment]
But that's unrelated to ReactPerf, isn't it?
Are you measuring production builds?

**Comment by jacehensley-wf** [comment]
I am also seeing this using `react.js` on 15.1.0. It seems to not be an issue with `react.min.js`

I built `react.js` with "master" and the issue seems to go away.

**Comment by gaearon** [comment]
>I built react.js with "master" and the issue seems to go away.

👍 

Then it’s fixed in master and the fix will be out in the next release.

**Comment by niba** [comment]
@gaearon true, it is unrelated to ReactPerf, sorry for making mess, i'm beginner in open source and I need to learn a lot. In production mode times are the same so I think that the debug mode is a little heavier in the latest version.
Thanks for help!

**Comment by gaearon** [comment]
Please feel free to investigate the difference further. It might very well be that there is low hanging fruit for optimization of DEV in master.
