### ISSUE TITLE
IE11 resets value of textarea when a placeholder is used

### ISSUE THREAD

**Issue by frontendphil** [facebook/react#6984]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you create a textarea with value and placeholder set and click into it using IE11 the value is reset to empty string.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
https://jsfiddle.net/xu26gt71/2/

**What is the expected behavior?**
The value of the textarea stays the same and the cursor is placed at the clicked position.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- React 15.0.1
- IE 11
- Windows 8

- It did work in earlier versions

**Comment by syranide** [comment]
cc @jquense

**Comment by jquense** [comment]
I can dbl check though I don't think its event plugin related as this case is something i've tested and specifically tried to address :P I could have missed a case I suppose.

**Comment by syranide** [comment]
@jquense Me neither, but thought you'd might be interested :)

**Comment by jquense** [comment]
I am :P intrigued really ;)

**Comment by frontendphil** [comment]
FYI: Also just tested with 15.1.0 and see the same error.
