### ISSUE TITLE
Documentation: passing key to React.createElement

### ISSUE THREAD

**Issue by fab1an** [facebook/react#6991]
There is nothing in the documentation that indicates how to pass `key`s to `React.createElement`.

Also there is no explanation about `props.children` either, especially when using `React.cloneElement`: Should the `props.children` be copied or new children passed?

(See also this SO question: http://stackoverflow.com/questions/37120956/react-cloneelement-pass-new-children-or-copy-props-children)

**Comment by jimfb** [comment]
Both can be passed, just as any other prop.  There is nothing mentioned because there is nothing special about them.

As per your SO question, components should never edit children.

StackOverflow is the correct place for usage questions, I'll close this out in favor of that post.

**Comment by jimfb** [comment]
You can clone if you must, but never mutate in place.  Your SO post mentioned editing in place, which has always been an antipattern.

**Comment by fab1an** [comment]
I'm not mutating in place, the question remains if children should be passed as props or the third parameter to `cloneElement`. What if the two arguments aren't equal?

**Comment by jimfb** [comment]
Doesn't matter, do whichever you prefer.  But don't pass both a `children` prop to the second argument and also pass a third prop.  Choose one or the other.

**Comment by fab1an** [comment]
Okay, but shouldn't this be documented?

**Comment by jaredtmartin** [comment]
I agree this should be documented.  I'm creating an array of elements with React.createElement and wasn't sure how to specify a key.  If it wasn't for this question, I wouldn't have an answer. This should be in the documentation.  

Also, what *would* happen fi we did pass both children prop and also children as the third argument? Which would take priority? What would the result be? Would it throw an error?  This seems like loose ends that need to be cleaned up.

**Comment by gaearon** [comment]
For any documentation changes please file an issue in https://github.com/reactjs/reactjs.org.
