### ISSUE TITLE
React perf tools not work in react 15

### ISSUE THREAD

**Issue by dang-hoang-hieu** [facebook/react#6993]
This month, when I upgrade React@0.14 to React@15 Perf doesnt work anymore!

I usually use like this:
```
//index.js
window.Perf = require("react/addons").addons.Perf;
window.Perf.start()
```
then after finished load the react page, I call `Perf.stop()` then `Perf.printWasted()` in console
but now no result put out :(

```
Array[0]
Total time: 0.00 ms
```

thanks :)

**Comment by syranide** [comment]
I'm assuming you're unknowingly running two instances of React due to npm quirks, clear `node_modules` and/or upgrade to npm3 to avoid this.

**Comment by gaearon** [comment]
```js
window.Perf = require("react/addons").addons.Perf;
```

should not work anymore—`react/addons` entry has been deprecated in 0.14 and warned on every access.

Make sure you have `react` and `react-addons-perf` with `15.1.0` version, and that you use it like this:

```js
window.Perf = require("react-addons-perf");
window.Perf.start()
```

**Comment by dang-hoang-hieu** [comment]
@gaearon 
thanks, It works now :beer:
