### ISSUE TITLE
Allow objects in key={}

### ISSUE THREAD

**Issue by kolodny** [facebook/react#7009]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
You need to specify a unique key

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
N/A

**What is the expected behavior?**
It should behave the same as using a unique key string

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
N/A

---

The idea came when I was discussing [a module I wrote](https://github.com/kolodny/weak-key) to take care of this functionality. I can't really think of a reason why this behavior shouldn't work out of the box.

In a regular setting, people need to either add an id property to objects in an array to spend a non-zero cogintive load figuring out which field or fields will be unique in the set. There's no reason  why just passing an object shouldn't work.

In a case where the collection is refetched and therefore all the previous references are lost, the elements in the array will tend to be in the same order, and therefore should not cause any perf hit (I don't know enough to comment on the perf hit for an insert or removal in the middle of the collection). SSR should have a similar perf hit (which is to say none), although the `key` prop will need to be stripped out of the server rendered markup.

Is this something worth pursuing?

**Comment by gaearon** [comment]
>In a case where the collection is refetched and therefore all the previous references are lost, the elements in the array will tend to be in the same order, and therefore should not cause any perf hit (I don't know enough to comment on the perf hit for an insert or removal in the middle of the collection)

If you use a `WeakMap` for `obj -> key` mapping, you will get a different `key` everything you provide a different `obj`. So if you update data immutably (which seems to be majority of cases in React apps), you’ll get a different reference to `obj` on any update to corresponding item, which would thus get a different `key`, and blow up the entire tree below it. (If old `key` is gone and a new `key` appears in the list, it’s not about the order: React kills the old component and mounts a completely new one in its place.)

**Comment by jimfb** [comment]
Yeah, in the general case, generating keys is impossible without knowledge about the identity of the data.  If your keys are erroneously reused, you will accidentally transfer state from one component to another.  If your keys are erroneously regenerated, you will loose component state.  If you fail to specify a key, we make an "educated guess" based on the element's position in the array, but we also emit a warning because it really does require having a human look into it and specify an appropriate key based on their understanding of the meaning of the incoming data.
