### ISSUE TITLE
Warn when there is more than one instance of ReactPerf in the page

### ISSUE THREAD

**Issue by felipethome** [facebook/react#7010]
@gaearon I normally bundle React and all its add-ons in a different file from my application, but when using ReactPerf I forgot of including it in the same bundle of React and ReactDOM, so I noticed I was receiving an empty array from ReactPerf functions every time I was using them, and that is because ReactDebugTool is different for the application and for React which means flushHistory is also different.

What do you think about warning the user if there are more than one instance of ReactPerf/ReactDebugTool in the page?

**Comment by gaearon** [comment]
This seems like the same issue as "duplicate React".

Can you share more into about how your setup ended up including two Reacts? It is not immediately obvious. Did you use UMD bundle *and* a CommonJS module?

**Comment by felipethome** [comment]
Of course, I did a [demo](https://github.com/felipethome/issue-multiple-react-perf). If you run the browserify version you will see the problem I'm talking about. I'm using CommonJS, but not UMD.

I'm familiar with the duplicate React issue, this is not the same. My setup doesn't end up with two React, but with two ReactDebugTool.

This seems to happen just with browserify, not webpack, so probably it is an issue with browserify or my set up is wrong.

**Comment by gaearon** [comment]
I’m not sure what’s wrong there but I suspect it’s related to the “vendor” configuration in Webpack config. I’m not a Webpack expert so I’m not sure how we can help here, but it’s not an issue on React side so I’ll close. We will be changing how we package things anyway as part of #6351, and there is also #6812 which is very related to this issue, so let’s continue discussion there.
