### ISSUE TITLE
[Regression] SyntheticEvent no longer available in the handler

### ISSUE THREAD

**Issue by coodoo** [facebook/react#7016]
**Do you want to request a *feature* or report a *bug*?**

Bug, probably a major regression.

**What is the current behavior?**

`SyntheticMouseEvent` used be the first argument passed to event handler, it's not now.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Here's a simple case to reproduce it.

```javascript
var ExampleApplication = React.createClass({

render: function() {
  return <p onClick={this.foo}>click me</p>
},

  foo: function(event){
  	console.log('click: ', event)
  }
});

ReactDOM.render( <ExampleApplication />, document.getElementById('container') )
```

**What is the expected behavior?**

`event` should be of type `SyntheticMouseEvent` and the console output should be something like this:
```
SyntheticMouseEvent {dispatchConfig: Object, dispatchMarker: ".0", nativeEvent: MouseEvent, type: "click", target: p…}_dispatchIDs: 
```

but now it's a `Proxy` object, with output like this

```
Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, nativeEvent: MouseEvent, type: "click", target: p…}
[[Handler]]:Object
[[Target]]:SyntheticMouseEvent
[[IsRevoked]]:false
```

Unless it's intended behavior change, otherwise this looks like a regression.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

It used to work until `0.14.8`, seems to be introduced in `15.0.0` and affect all following versions.

**Comment by zpao** [comment]
Thanks for the thorough report!

This was an intentional change we made. It only applies to our development build and the goal is to provide better warning messages (specifically around storing references to these events and he problems that can arise when used in certain ways). They should otherwise be identical in functionality. Production builds do not use Proxies.

**Comment by coodoo** [comment]
Thanks for the details, very glad to know it's a feature not a bug 😎
