### ISSUE TITLE
how to recover this bug:-validateDOMNesting(...): <form> cannot appear as a descendant of <form>. See LoginForm > StatelessComponent > Connect(Form) > Form > form > ... > StatelessComponent > Connect(Form) > Form > form.

### ISSUE THREAD

**Issue by pravalikasoma** [facebook/react#7017]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by zpao** [comment]
You'll need to restructure your component tree. Forms are not allowed in forms and the browser will restructure the DOM from beneath you if you do. That puts React into an inconsistent state that we can't recover from.
