### ISSUE TITLE
allowFullScreen not working?

### ISSUE THREAD

**Issue by caub** [facebook/react#7018]
it seems that it's not possible to pass this attribute like in #2041

test script: https://jsfiddle.net/crl/4p2orbuw/7

note; is camelCase only for attribute names with an hyphen? it would be clearer if so

**Comment by simonkberg** [comment]
allowFullScreen is the correct casing and the only variant that will work, just like in your example. 

Correctly adds `allowfullscreen` to DOM node: https://jsfiddle.net/4p2orbuw/9/
Does not add `allowfullscreen` to DOM node: https://jsfiddle.net/4p2orbuw/10/
Docs: https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes

But maybe I misunderstand you?

Note: you can't test the actual fullscreen button in jsfiddle as the result is displayed inside a sandboxed iframe that doesn't allow fullscreen control.

**Comment by caub** [comment]
Sorry, it's working, I made an error earlier
