### ISSUE TITLE
Virtual DOM DeepRenderer?

### ISSUE THREAD

**Issue by laskos** [facebook/react#7019]
Virtual DOM has a lot of potential in testing. But actually only ShallowRenderer uses it in 100%, which is great. But it's only usable for unit testing. Library like [Enzyme](https://github.com/airbnb/enzyme) are great in deep rendering w/o real DOM, which is huge performance boost in case of functional (or/and integration) testing without real browser. But it uses DOM mock, which is called jsdom. 

In my opinion it is totally unnecessary, because VirtualDOM rendered output is totally usable for testing (which ShallowRenderer proves). 

So I made little hacky but fully working patch to ShallowRenderer, which allows to render children also ([PR here](https://github.com/facebook/react/pull/5513)).

So my propose is introduce something like `DeepRenderer` in test utils. I can modify my patch.

Is it worth to skip jsdom? Will it be noticable perf boost? How to name that renderer? How the API should look like?

**Comment by gaearon** [comment]
I think this has been added in #6944, and while the exact API is subject to change, you might want to track what happens to it in a few weeks! I’ll close because it already exists and will be out soon.

**Comment by laskos** [comment]
Lol, this is exactly what I was talking about. Gj @spicyj
