### ISSUE TITLE
onChange not work corectly

### ISSUE THREAD

**Issue by cmplx** [facebook/react#7037]
onChange work like a onInput, but onInput does not work. React v 0.14.7
http://jsfiddle.net/dannymarkov/68vz9tc8/1/?utm_source=website&utm_medium=embed&utm_campaign=68vz9tc8

**Comment by jimfb** [comment]
This is intentional.  React uses `onChange` with our modified semantics (closer to `onInput` semantics); you shouldn't need to use `onInput`.  If you really need native event behaviors, you can break out of React and register event listeners manually, but this is not recommended in general.
