### ISSUE TITLE
Exception thrown from render method suppressed in JSX expression

### ISSUE THREAD

**Issue by floydwch** [facebook/react#7041]
Hi, please refer following code

https://jsfiddle.net/1e0p5uem/

My question is, why the exception is suppressed.
There is no error message thrown to console. It's difficult to find the error because JSX skips the render which threw the exception, or any other better approaches to capture such accident?

Thanks.

**Comment by jimfb** [comment]
I don't understand your issue.  There is an error thrown to the console, and JSX does not skip the render which threw the exception.


<img width="725" alt="screen shot 2016-06-14 at 5 06 19 pm" src="https://cloud.githubusercontent.com/assets/9595985/16064001/5d3f246e-3252-11e6-8086-a9ab51c166db.png">

**Comment by floydwch** [comment]
Sorry, don't know how to state this issue well. The case in jsfiddle doesn't show this issue.

I use babel-loader to compile jsx, the case in jsfiddle won't throw the error after webpack.

**Comment by jimfb** [comment]
Sounds like an issue with your webpack config.  Closing out as not-a-react-bug.

**Comment by floydwch** [comment]
@jimfb 

I'm doing some investigation, and I believe this issue is related to https://github.com/facebook/react/blob/c47830d12c495bd8e02c5e84f2de9e9384165047/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L1074-L1079

The exception was catched by the `finally` block, and the `renderedComponent` is undefined since it didn't finish the rendering.

Because the exception has been catched, it won't pipe to console.

**Comment by jimfb** [comment]
Exceptions do not get caught by finally blocks.  If the bug is in React, you should be able to reproduce within a jsfiddle without webpack/dependencies.
