### ISSUE TITLE
HTML attributes order and object keys order

### ISSUE THREAD

**Issue by Diokuz** [facebook/react#7049]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

React rendered html depends on order of keys in props, for example:
```js
{href: 'http://example.com', className: 'link'}
// and
{className: 'link', href: 'http://example.com'}
```
gives two different html:
```html
<a href="http://example.com" class="link"></a>
<a class="link" href="http://example.com"></a>
```
You can see that `href` and `class` attributes are reversed.

This is critical, when you have isomorphic application, and two different renders: nodejs on server and something on client.

**What is the expected behavior?**

Rendered html must not depend on order of keys in any objects.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15
nodejs 5.11
chrome (actual)

In some cases node5.x can change order of keys, and we get a warning about checksum mismatch on client, because of two "different" html.

**Comment by jimfb** [comment]
This is a bug in node.js, not a bug in React.  I think we installed a workaround in React 15.1.0, so you should upgrade your React version and see if that fixes the issue.  Further discussion in https://github.com/facebook/react/issues/6451
