### ISSUE TITLE
fix webcomponents example

### ISSUE THREAD

**Issue by jalexanderfox** [facebook/react#7056]
The ReactComponent > WebComponent > ReactComponent interop example is currently partially broken:

https://github.com/facebook/react/blob/master/examples/webcomponents/index.html

In Chrome 51.x, the custom element's createdCallback
```
var name = this.getAttribute('name')
```
expect:
```
name === "Jim Sproch";
```

actual:
```
name === null;
```

To get this to work the createdCallback function can be moved to an attachedCallback.

Pull request coming soon.

**Comment by zpao** [comment]
Fix landed
