### ISSUE TITLE
passing function in setState receives empty object even with no initial state

### ISSUE THREAD

**Issue by wmira** [facebook/react#7061]
In react, if you dont have initial state via getInitialState(), we usually have this.state to be null.

this.setState() can receive function with the following signature:

function(prevState) {
}

On initial call it seems that React is initializing this to an empty Object (prevState) even though that is indeed still empty thus subsequent access to the state after setState returns now returns an empty object.

Is this an intended behavior?

https://jsfiddle.net/1uqf2gnc/

**Comment by Aweary** [comment]
This is because `setState` uses `Object.assign` to merge the existing state with the new state.

```
var nextState = Object.assign({}, replace ? queue[0] : inst.state);
```

Since state updates use this immutable pattern, and `Object.assign` will just ignore if an argument is `undefined` or `null`, `setState` will always result returning a new object, empty or not, for the instance's state.

**Comment by jimfb** [comment]
> Is this an intended behavior?

I'm not sure if this was intended behavior.  It seems likely that it was just something we overlooked.  We generally try to avoid allocating new objects when it is unnecessary.

I guess my bigger question is: "why do you care?"  Your component should probably either be using state (in which case, it should always be an object) or not using state (in which case you shouldn't be able to tell the difference).  How did you run into this issue?

cc @spicyj for thoughts.

**Comment by wmira** [comment]
I have a hoc which receives a redux like reducer and does something like..

```javascript
dispatch(fsa) {
       this.setState( (prevState) => reducer(prevState, fsa) );
},
```
now reducers can have initial state baked in default args e.g.

```javascript
const reducer = (state = {count: 0}, action}) => {}...
```
Now the reducer will always start with empty object because state will start with empty obj and not the default arg assign to state.

**Comment by Aweary** [comment]
> We generally try to avoid allocating new objects when it is unnecessary.
What would be the alternative, maybe throwing/warning for `setState` if `inst.state` isn't an object? It seems that `setState` should either update or instantiate the state when invoked, which is what it does now.

>Now the reducer will always start with empty object because state will start with empty obj and not the default arg assign to state.

You can avoid this by namespacing your data using a value in state instead of the state istead

```js
this.setState(prevState => reducer(prevState.data, fsa))
```

**Comment by wmira** [comment]
@Aweary is just that the reducers are already well defined with their initial state based in as default args. I think it should be ok as I can handle it on the HOC side e.g. if empty then we can treat is as null and pass that to the reducer. 

Was initially expecting it to behave as if I don't have initial state passed.

**Comment by pawan8525** [comment]
not update state value,Please help

this.setState({ entityArray: resultEntities }, () => {
    console.log(this.state.entityArray, 'entityArray');
  });
