### ISSUE TITLE
Browser unresponsive while controlled text input containing large amount of text is focused

### ISSUE THREAD

**Issue by depoulo** [facebook/react#7063]
How to reproduce:

1. Go to https://facebook.github.io/react/
2. Paste a long text (~10k chars is a good fit, add 100k and the whole tab will freeze for a good amount of time) into the text input of the TODO app ("An Application")
3. Try to scroll while the text input is still focused

=> Really bad scrolling performance, repositioning the cursor takes a second or so until rendered.

In contrast, pasting the same text into a non-controlled component, like the markdown editor right below ("A Component Using External Plugins") doen't yield the above issue.

**Comment by syranide** [comment]
Not a React bug, that is browser behavior.

**Comment by depoulo** [comment]
It's indeed a Chrome only issue as far as I can test.

**Comment by jimfb** [comment]
@depoulo I'm unable to reproduce.  I pasted 100kB text into the textbox, left it focused, tried scrolling both within the textbox and within the page in general, and both were very responsive.  Tested on Chrome 51.

**Comment by syranide** [comment]
@jimfb OSX? Could be just Windows or something, I could definitely reproduce it.

**Comment by depoulo** [comment]
seemst to happen on Windows only.

**Comment by jimfb** [comment]
It's a little hard for me to tell, since I only run windows in a VM which is sometimes slow anyway, but I think I'm able to reproduce on windows.  Appears to be a chrome bug on windows.

@depoulo Want to file a bug with the Google Chrome team?

**Comment by depoulo** [comment]
Well, it's 2 minutes to six on Friday evening over here, I'll file a bug if I can still reproduce it on Monday morning...
