### ISSUE TITLE
Invariant violation error message improvement

### ISSUE THREAD

**Issue by starkch** [facebook/react#7065]
**Do you want to request a *feature* or report a *bug*?**
Error message bug.

**What is the current behavior?**
Uncaught Invariant Violation: img is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of <Component Name>

provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
   ```
    render: function () {
        return ( 
            <div  >
                <img src={ this.props.track_artwork } >   </img>
            </div>
         );
       }
  ```
**What is the expected behavior?**
```
Uncaught Invariant Violation: img is a void element tag and must not have `children` nor use `dangerouslySetInnerHTML`. Check the render method of <Component Name>
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
"version": "16.0.0-alpha"
```
found in Chrome, but should be universal.

**Comment by jimfb** [comment]
This is expected behavior.  `img` is a void element tag and must not have children.  That includes whitespace.

Use `<img src={ this.props.track_artwork } />` instead.

**Comment by zpao** [comment]
The issue is that the error itself could use some language improvement.

**Comment by linoleum-js** [comment]
@starkch It works for me https://jsfiddle.net/apn1p0gg/1/
Can you give a full code snippet that reproduce it?

**Comment by starkch** [comment]
@linoleum-js; @zpao The issue is that the error message itself could use some improvement.  Several of us were working on some code and found the current message unclear.
