### ISSUE TITLE
Performance worsening between version 15.0.2 and 15.1.0

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#7067]
Hey folks!

I'm the maintainer of [react-virtualized](https://github.com/bvaughn/react-virtualized). I've recently been focused on trying to squeeze better FPS out of the components while scrolling. To help with this I created a test harness that scrolls a lot and measures FPS while doing so. The test harness lets me measure different versions of react-virtualized _and_ different versions of React in order to compare their performance.

While testing, I've discovered a consistent drop in performance between React 15.0.2 and 15.1.0 (15.1.0 being slower). I've observed this for Chrome, Safari, and Firefox (latest versions, OS X 10.11.4) and so I wanted to share it with you.

Perhaps I'm doing something silly?

### Test harness
* [React 15.0.2](http://rawgit.com/bvaughn/react-virtualized/master/playground/grid-test.html?react=15.0.2)
* [React 15.1.0](http://rawgit.com/bvaughn/react-virtualized/master/playground/grid-test.html?react=15.1.0)

### Instructions to reproduce
* Load the page
* Open the console
* Click anywhere on the body to start the test
* Wait for it to complete and it will log average FPS and total time information.

The test will run a minimum of 5 times (potentially longer, until it satisfies the confidence interval). Upon completion it will print the average frame rate across the test.

### Source code

In case it's helpful, here's the test code:

* Test case: https://github.com/bvaughn/react-virtualized/blob/master/playground/grid-test.js
* Test runner: https://github.com/bvaughn/react-virtualized/blob/master/playground/test-runner.js

**Comment by gaearon** [comment]
You seem to be measuring development versions. Please check if you have any production regressions.

There is a known regression in dev which has been fixed in master. Most likely that's what you're seeing! You can check by comparing against a master dev build. You can find one at http://react.zpao.com/builds/master/latest/.

**Comment by Aweary** [comment]
@gaearon had no idea there were hosted builds of the master branch, thanks for that 👍

**Comment by bvaughn** [comment]
D'oh! I feel foolish!

Using the `.min` builds speeds things up substantially. (Also thanks for the pointer to the master build.)

**Comment by gaearon** [comment]
Whoops, never mind, CloudFare naming scheme confused me. Even though it's called https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js it seems to be a minified build.

**Comment by gaearon** [comment]
Hmm. I'm confused now. :D
When I open https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js it appears minified. Is it not our minified build?

**Comment by gaearon** [comment]
Ok I get it now. Its first few lines are minified which is all I saw on mobile. :-)

**Comment by bvaughn** [comment]
Yeah. I just scanned the first few lines as well. Sorry! :D
