### ISSUE TITLE
Include licensing header into react.js

### ISSUE THREAD

**Issue by solomatov** [facebook/react#7071]
Currently, react.js distribution has a licensing header. Unfortunately, it's removed by webpack and uglifyjs. Could you please add /*! at the file headers so that minifiers will keep them in optimized versions so that license compliance can be achieved in an automated manner,

**Comment by gaearon** [comment]
@solomatov Does #6539 help? If so, we can get it merged.

**Comment by solomatov** [comment]
@gaearon That will definitely help. Thank you!

**Comment by aweary** [comment]
@trueadm does the new build system handle this at all?

**Comment by trueadm** [comment]
@aweary I believe we do for `development` bundles, not for `production` bundles though. To save bytes.

https://github.com/facebook/react/blob/master/scripts/rollup/header.js

**Comment by gaearon** [comment]
Our headers look like this.

```js
/** @license React v16.2.0
 * react-dom.production.min.js
 *
 * Copyright (c) 2013-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
```

so that should be enough.
