### ISSUE TITLE
Call other props' checkType() in the validation function

### ISSUE THREAD

**Issue by Oopscurity** [facebook/react#7072]
For example, we have
```javascript
// inside some component's class definition
static propTypes = {
  tag: Tag
};
```
where `Tag` is
```javascript
const Tag = PropTypes.shape({
  name: PropTypes.string,
  // other props
});
```
_____
The question: Can we define custom prop type that'll use its own validator like this:
```javascript
function TagContainer(props, propName, componentName) { /* ... */ }
```
and use other prop's validation function anywhere inside of this function?
```javascript
const error = Tag(/* params... */);
```
`Tag` has the signature as `function checkType(isRequired, props, propName, componentName, location, propFullName)` but whatever I pass to it as arguments it always returns `null`.

Am I doing something wrong here or is it impossible to check the type this way?
Thanks.

**Comment by keyanzhang** [comment]
Could you provide a jsfiddle? A template can be found at https://jsfiddle.net/reactjs/69z2wepo/. Thanks!

**Comment by Oopscurity** [comment]
@keyanzhang I've just made an jsfiddle example... And it works: https://jsfiddle.net/4atd2v37/6/ Now the issue may be closed.
