### ISSUE TITLE
Component re-renders itself without checking into shouldComponentUpdate.

### ISSUE THREAD

**Issue by iamsaksham** [facebook/react#7083]
I have a component which re-renders itself without checking condition inside the shouldComponentUpdate. Its a large app, so cant provide any fiddle. Here is the screenshot of console where 'rerender' is getting printed before 'shouldComponentUpdate'
![untitled-1](https://cloud.githubusercontent.com/assets/13564312/16189065/3178a492-36f6-11e6-975c-5cebab5b876b.jpg)

**Comment by gaearon** [comment]
Where is `rerender` being logged? Are you sure `shouldComponentUpdate` returned `false`?
Unfortunately it’s very unlikely that we would be able to help without a (reduced) test case.

**Comment by iamsaksham** [comment]
shouldComponentUpdate was not even called before rerendering the component. This screenshot might help. I'll try to code a reduced test case in a few hours.
![untitled-2](https://cloud.githubusercontent.com/assets/13564312/16190844/f70f1d8c-36fe-11e6-9ef1-0549bda8008c.jpg)

**Comment by Aweary** [comment]
Not really related, but I can't imagine that calling `ReactDOM.findDOMNode` and `innerHTML` in `shouldComponentUpdate` is the best way to determine if an update is necessary.

**Comment by thymikee** [comment]
Looks like you're using Chrome (am I right?). If so, please check this [V8 JIT issue](https://www.reddit.com/r/javascript/comments/4oxtgk/javascript_developers_be_warned_about_this_crazy/) and try running the code in another browser.

**Comment by keyanzhang** [comment]
Is there any chance that you are using `this.forceUpdate()`?

**Comment by iamsaksham** [comment]
@syranide Excellent guess, component gets `unmounted` and re-`mounted` again. I'll close the issue for now, will re-check the issue why the component gets unmounted and will reopen if needed.

@keyanzhang There is no `this.forceUpdate()` in my app. Issue us caused due to unexpeced `unmounting` of component

@thymikee It works all the same in other browsers too. Issue is component gets `unmounted` unexpectedly
