### ISSUE TITLE
Sites Using React disappeared

### ISSUE THREAD

**Issue by ccerrato147** [facebook/react#7086]
I can't find the page "Sites Using React" in this repo's wiki

**Comment by keyanzhang** [comment]
Thanks, it's been fixed now: https://github.com/facebook/react/wiki/Sites-Using-React

**Comment by ccerrato147** [comment]
Thanks!

**Comment by fredguest** [comment]
It seems to have disappeared again.

**Comment by keyanzhang** [comment]
Fixed, thanks.

**Comment by fredguest** [comment]
Sweet! Thanks
