### ISSUE TITLE
Composition type compoent 

### ISSUE THREAD

**Issue by suhaotian** [facebook/react#7087]
I write this [BaseInput](http://jsbin.com/gokode/edit?js,output),
some code from `draft-js`,
problem here: when you click `set another value` button, the input didn't change.

And I know I shouldn't use defaultValue in `BaseInput` component, But if not, the compostion type doesn't work correct. And I browser document again, really don't know how to do it. 

Have any idea?

[BaseInput](http://jsbin.com/gokode/edit?js,output)

## Update:
 change `defaultValue` to `value`:
You can see effect here: [demo video](https://www.youtube.com/watch?v=mK_dOjZf6F4&feature=youtu.be)

**Comment by Aweary** [comment]
@suhaotian 

You should set the `value` prop on the returned DOM element to `props.value` so its value is controlled. See http://jsbin.com/pavexeruce/1/edit?js,output

```js
return (React.createElement(type, {
    ...props,
    /* Add the value prop here and it works as you'd expect */
    value: value,
    defaultValue: value,
    onBeforeInput: (e) => {
      textInputData = (textInputData || '') + e.data
    },
```

**Comment by suhaotian** [comment]
@Aweary Yes!
But when when type composition input like,Chinese, it didn't work.....

**Comment by suhaotian** [comment]
You can see here: [demo video](https://www.youtube.com/watch?v=mK_dOjZf6F4&feature=youtu.be)

**Comment by zpao** [comment]
@suhaotian Looks like you're using 15.1.0. Does this also happen with 15.0.1?

@hellendag have you heard of any issues with IME lately?

**Comment by keyanzhang** [comment]
I think this is related to #3926, where `onChange` event fires while the IME (输入法) string is _being_ constructed.

In your `onChange` handler:
```js
    onChange: (e) => {
      if (!composing) {                    
        onChange(e.target.value)
      }
    },
```

When `composing === true`, the newly input field value will be discarded since `<input/>` is [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components).

**Comment by suhaotian** [comment]
@keyanzhang type IME, like Chinese words, I don't want fire change event before `oncompositionend`

**Comment by suhaotian** [comment]
@zpao Also happen with 15.0.1; Some code from `draft-js`  [DraftEditorCompositionHandler.js](https://github.com/facebook/draft-js/blob/67c5e69499e3b0c149ce83b004872afdf4180463/src/component/handlers/composition/DraftEditorCompositionHandler.js). Not at all. Maybe we can learn it from [vue text](https://github.com/vuejs/vue/blob/ab675781fbff326f034cb31bf42e034c01188f6b/src/directives/public/model/text.js)., it's work fine with `composition input`.
I want to build a BaseInput,  But I try, really don't know how to do it with React.js in correct way....

**Comment by suhaotian** [comment]
Hey, guys. I solved this proplem !!! 

Online work demo: http://output.jsbin.com/basada
