### ISSUE TITLE
Animations Addon - Staggering Animation

### ISSUE THREAD

**Issue by MalucoMarinero** [facebook/react#709]
I'm starting to work with React on a project and I'm implementing a directional staggering animation. Basically if you scroll downwards and you catch list elements loading in, you'll see them fade in top to bottom, and vice versa if you're scrolling upwards.

At the moment I've just altered the code in my development version of react-with-addons.js so all transitions work this way, but obviously it'd be nice to incorporate as a feature in the animation addon, with a proper interface. I'm happy to put some work into making it happen, but it'd be nice to have an idea of what interface would be ideal for it.

JSX might be wrong, I'm using coffeescript so I don't use it...

```
<ReactTransitionGroup transitionName="elementFade" transitionStagger={true} transitionStaggerDirectional={false}>
```

So...

transitionStagger: set whether or not to stagger the transition
transitionStaggerDirectional: set to make the stagger occur upwards or downwards based on which elements come in -- if the new elements are ordered earlier than the current existing elements then it's an upwards stagger, otherwise it's a downward stagger.
transitionStaggerDelay: ng-animate does this by pulling the transition/animate delay variable from getComputedStyle, would a js override ever be something suitable here?

Anyway, It's something I'll be definitely using in my project, so hopefully there's a case for bringing it into the addon.

**Comment by i8ramin** [comment]
Hello. So is staggering animations supported in the latest version of React? It is not clear from this thread  (or #756.) How does one go about create staggering animations using the ReactTransitionGroup API. Thanks.

**Comment by 59naga** [comment]
I used a [velocity-react](https://github.com/twitter-fabric/velocity-react), [has solved this indirectly](https://github.com/59naga/try-react-server-side-rendering/blob/f0ce0ca86a2b8f38129ad16f292d7726b38693f4/client/views/home.jsx#L50-L66).

**Comment by gaearon** [comment]
Check out [React Motion](https://github.com/chenglou/react-motion) too.
