### ISSUE TITLE
Warn for string refs where owner != __self

### ISSUE THREAD

**Issue by jimfb** [facebook/react#7091]
Sebastian wants to warn when `owner !== __self`, because this is the hard case to find when codemodding from string refs to callback refs.

**Comment by Aweary** [comment]
Would this likely be done in `ReactOwner.addComponentAsRefTo`?

**Comment by jimfb** [comment]
Probably would be a separate dev tool that sanity checked the element.  But we'll need to fix the transform first, since I don't think we're even using the `__source` prop right now, IIRC.

**Comment by Aweary** [comment]
Which transform are you referring to? I'd like to take a look at this if possible.
>  I don't think we're even using the __source prop 
Do you mean `__self` or is `__source` required here too?

**Comment by jimfb** [comment]
Sorry, yeah, `__self`, edited/fixed in reply above.

> Which transform are you referring to? I'd like to take a look at this if possible.

https://github.com/babel/babel/pull/3540

**Comment by keyanzhang** [comment]
How would this affect people who use `createElement` explicitly?

**Comment by jimfb** [comment]
@keyanzhang They miss out on a potentially useful warning.  Unfortunately, there really isn't much we can do to make their experience any better, AFAIK.

**Comment by jimfb** [comment]
cc @facebook/react-core Public API change.

**Comment by spicyj** [comment]
Well you could also make a transform that adds __self to `React.createElement` calls.

We always wanted to log this internally – not 100% sure it makes sense to give a warning externally too? I guess it's probably reasonable.

**Comment by sebmarkbage** [comment]
This is something we actually should do soon as part of deprecations work. If we first get rid of these edge cases then it will allow us to write a codemod for string refs.

**Comment by gaearon** [comment]
bump

**Comment by rickhanlonii** [comment]
Bump

**Comment by lunaruan** [comment]
This is closed by #17864.
