### ISSUE TITLE
Expose React build mode/flags

### ISSUE THREAD

**Issue by jimfb** [facebook/react#7100]
@kittens has expressed concern that people will forget to set the NODE_ENV when building their React application, which will result in babel producing bloated builds, due to our new dev-mode transforms.  The `__source` and `__self` should never be set in production, and having them set on every element would introduce substantial bloat that you wouldn't want in a production environment.  We probably want to be able to warn when this happens.

In this case, I think we might want to expose `React.mode = __DEV__` or something, such that the transform could add runtime checks to verify that React is in dev mode, and warn if not.  I know we're thinking about switching to real build flags for the various features, and maybe we want to expose all those individual flags.

Anyway, opening the issue so we have a place to discuss and track.

**Comment by andreioprisan** [comment]
Any update on this issue? React.mode would be very useful to toggle specific debug levels.

**Comment by gaearon** [comment]
If there was an update, it would be on this issue. 😉

**Comment by gaearon** [comment]
@andreioprisan I think the issue was about a read-only flag.

**Comment by gaearon** [comment]
Meh.
