### ISSUE TITLE
Bug: Safari+Messages - Copying text puts comment tags in clipboard

### ISSUE THREAD

**Issue by amitava82** [facebook/react#7106]
This is reproducible in OSX + Safari + Mac Messages app using React 15.1.0

- Run the example fiddle: https://jsfiddle.net/reactjs/69z2wepo/ in Safari
- Copy `Hello World` by triple clicking on the text.
- Paste the text in Messenger app. It will paste `Hello /react-text react-text: 3 World` in the chat window.

- Pasting the same clipboard content elsewhere outputs `Hello World` (this bug report composer for example).

**Comment by jimfb** [comment]
Which messenger app?  I tested on facebook.com, messenger.com, and our internal messenger app - everything looked fine and I was unable to reproduce.  I also tried on my android with chrome+messenger, again unable to reproduce.

Are you referring to the iOS app?  Are you testing on your phone?  Can you upload a screencast to youtube or something?

**Comment by jimfb** [comment]
My web tests were using Safari Version 9.1.1 (10601.6.17).

**Comment by amitava82** [comment]
Sorry, it is the Mac Messages app https://www.apple.com/support/mac-apps/messages/ & Safari Version 9.1.1 

Here is a screencast (using different react app but same issue) https://www.dropbox.com/s/8dx721ln2168h31/issue.mov?dl=0

**Comment by zpao** [comment]
I'll look a little bit more closely when I'm at a computer but I'm 99% sure you actually want to be filing a bug against Apple. We do not control Safari's clipboard implementation. You should be able to repro outside react with a complex enough DOM making use of HTML comments (since that's all that's happening)

**Comment by zpao** [comment]
I guess it could also be Messages paste implementation. Clipboards are fun. There's basically some data there in multiple formats and when pasting you get to decide which format you'll read from. Messages may be reading one format but Safari another (perhaps why you can paste into a textarea fine but not Messages input)

**Comment by amitava82** [comment]
Yeah I thought so. Seems to be an Apple issue.

**Comment by zpao** [comment]
I filed a bug against apple so we'll see if they do anything about it (26982554 if anybody can even access those). Thanks for letting us know!
