### ISSUE TITLE
ES 6 Target

### ISSUE THREAD

**Issue by newtack** [facebook/react#7111]
We are targeting ES 6 compliant, modern browsers (such as latest version of Chrome, Safari 10, etc.) and would like to leverage this to reduce the size of React build (using the latest version of React).
Is this already something that is possible, if so how? Are there other options to reduce the size of React (such as setting node environment variable to production)?

**Comment by keyanzhang** [comment]
You can [change](https://github.com/facebook/react/blob/master/.babelrc) the Babel plugins that we use to compile React to fit your needs (then `npm run build` yourself). However, as you can see we actually use ES6 features quite selectively so I'm not sure if you'll see a huge difference.

You might also be interested in https://github.com/facebook/react/issues/6351#issuecomment-225401497. Feel free to comment or reopen if there's anything unclear.

**Comment by gaearon** [comment]
>Are there other options to reduce the size of React (such as setting node environment variable to production)?

With CommonJS, if you envify `process.env.NODE_ENV` to be `"production"` and then uglify it, you will get a smaller build than if you don’t. It’s the same one we ship as `dist/react.min.js` and [from CDN](https://fb.me/react-15.1.0.min.js).
