### ISSUE TITLE
shallow rendering propTypes validation

### ISSUE THREAD

**Issue by Sinewyk** [facebook/react#7115]
```javascript
const React = require('react')

function scopedForWarnings(i) {
    const C = () => React.createElement('div')
    C.displayName = 'C'+i
    C.propTypes = {c: React.PropTypes.string.isRequired}

    const B = () => React.createElement(C)
    B.displayName = 'B'+i
    B.propTypes = {b: React.PropTypes.string.isRequired}

    const A = () => React.createElement(B)
    A.displayName = 'A'+i

    return React.createElement(A)
}

console.log('Shallow rendering')
require('react-addons-test-utils').createRenderer().render(scopedForWarnings(1))

console.log('Static markup rendering')
require('react-dom/server').renderToStaticMarkup(scopedForWarnings(2))
```

Actual:
```
Shallow rendering
Warning: Failed propType: Required prop `b` was not specified in `B1`.
Static markup rendering
Warning: Failed propType: Required prop `b` was not specified in `B2`. Check the render method of `A2`.
Warning: Failed propType: Required prop `c` was not specified in `C2`. Check the render method of `B2`.
```

Expected (unless I'm mistaken :cry: ):
```
Shallow rendering
Static markup rendering
Warning: Failed propType: Required prop `b` was not specified in `B2`. Check the render method of `A2`.
Warning: Failed propType: Required prop `c` was not specified in `C2`. Check the render method of `B2`.
```

We are working towards 0 warnings for our React components tests, and I thought just using shallow would allow us to stop mocking/passing tons of useless props for propTypes validation.

But the first level of component, even though it's not "really" rendered, propTypes validation still occurs, is that normal ?

**Comment by keyanzhang** [comment]
Yeah, this is expected because props are validated at element creation time but not mount time. This behavior is more similar to static type systems like Flow. The value of the expression `scopedForWarnings(1)` gets evaluated first before it gets passed to `render()`, and that's why the warning shows up.

Since this is not a bug I'm going to close it out. Feel free to reopen or comment If there's anything unclear!

**Comment by Sinewyk** [comment]
Note: can't believe I forgot, this is on React 15.1.0

If I add before rendering
```javascript
console.log(process.env.NODE_ENV);
console.log('Just React.createElement()')
scopedForWarnings(0)
```

this is the console output
```
development
Just React.createElement()
Shallow rendering
Warning: Failed propType: Required prop `b` was not specified in `B1`.
Static markup rendering
Warning: Failed propType: Required prop `b` was not specified in `B2`. Check the render method of `A2`.
Warning: Failed propType: Required prop `c` was not specified in `C2`. Check the render method of `B2`.
```

And this is normal, `render()` method of parent is not called if we aren't mounting/rendering, and so `createElement` in render function is not called.

So children aren't *created* until parent is *rendered*.

Which is why I expected the shallow renderer to not do propTypes validation of components it's not really rendering.

Shouldn't we return early or something to not go through propTypes validation for shallow rendered components ?

And so if I go back to edit the initial script to add propTypes to component A I get
```
Shallow rendering
Warning: Failed propType: Required prop `a` was not specified in `A1`.
Warning: Failed propType: Required prop `b` was not specified in `B1`.
Static markup rendering
Warning: Failed propType: Required prop `a` was not specified in `A2`.
Warning: Failed propType: Required prop `b` was not specified in `B2`. Check the render method of `A2`.
Warning: Failed propType: Required prop `c` was not specified in `C2`. Check the render method of `B2`.
```

Even though IMO it makes sense to only get
```
Shallow rendering
Warning: Failed propType: Required prop `a` was not specified in `A1`.
Static markup rendering
Warning: Failed propType: Required prop `a` was not specified in `A2`.
Warning: Failed propType: Required prop `b` was not specified in `B2`. Check the render method of `A2`.
Warning: Failed propType: Required prop `c` was not specified in `C2`. Check the render method of `B2`.
```

Is that something that I could work on and could be merged or is that behavior not wanted ?

**Comment by keyanzhang** [comment]
Hey @Sinewyk,

Sorry I didn't notice that by the time you invoke `scopedForWarnings(i)`, only element `A` gets constructed. Thanks for reporting this! @graue @spicyj is it the intended behavior of our shallow renderer?

**Comment by graue** [comment]
Like @keyanzhang says, this is expected. If you're testing `A`, wouldn't you want to check that it uses `B` correctly? Omitting one of `B`'s required props is a bug in `A`'s render method.

**Comment by Sinewyk** [comment]
Makes sense now that you say it. It's just and absolute pain in the ass when testing some components I guess.

I guess the answer would be splitting up these components again so that their API surface is narrower/flatter ...

Thanks for answer @graue

**Comment by alex-gvozden** [comment]
but how can I just test if the component exists, in contains if I try using just component without props it will not pass through...

not testing if component exists, only that, is also kind of risky
basically this would be like your typical div exists test but for component
