### ISSUE TITLE
Ship v15.2.0

### ISSUE THREAD

**Issue by zpao** [facebook/react#7118]
The next release of React will be v15.2.0. We shipped an RC to npm last week. React Native v0.29 went to RC this week using our RC, but we should ship final before they do so RN is only using final versions. I think we have another week+ before their branch cut but ideally we get out sooner. We haven't heard of any issues so we're going to assume that this is in good shape. I'm planning to ship React 15.2.0 on Monday (June 27).

cc @ide (not sure who is running RN release this time around, but feel free to cc them)

Todo:
- [x] Pull in other PRs
  - [ ] #7098
  - [ ] #7153
- [x] write changelog (@zpao)
- [x] actually ship (@zpao/@keyanzhang)
- [ ] blog post about error codes (@keyanzhang)

**Comment by satya164** [comment]
cc @grabbou who is leading the releases for RN.

**Comment by zpao** [comment]
Going to be pushing this out shortly. I'll see if @spicyj can send over a PR to update RN. There are only 2 additional commits since our RC, which are both local to ReactDOM so the final should be perfectly safe to update RN to, even in its RC.

**Comment by gaearon** [comment]
<img src='https://media.giphy.com/media/3oEjHMj0My3ET5XSW4/giphy.gif' width='700'>

**Comment by zpao** [comment]
And we're out. Will update the tutorial repo and jsfiddles now.

**Comment by SimenB** [comment]
Hiya! Probably the wrong place to ask this, but any particular reason why you've stopped updating the blog? https://facebook.github.io/react/blog/

I know I can read the [release notes](https://github.com/facebook/react/releases), but I like seeing a short summary of the changes (even if it's just "hey, we did a release, nothing special in it").

**Comment by satya164** [comment]
@SimenB IMO it'll be too much to do a blog post for every minor release.

**Comment by selvagsz** [comment]
I second @Simek's thoughts... Ember does a decent job in blogging the releases http://emberjs.com/blog/tags/releases.html. Helpful in subscribing with rss feeders too

**Comment by satya164** [comment]
@selvagsz You can also subscribe to the feed for releases - https://github.com/facebook/react/releases.atom
