### ISSUE TITLE
jest react django rest test implementation

### ISSUE THREAD

**Issue by ptadas** [facebook/react#7130]
Rookie question. I have the code below, for which I'd like to create a test case.

class APIInstanceView extends React.Component {

    constructor(props) {
    super(props);
    this.state = {  instanceData: [],
                    apiData: [],
                    mode: "loading",
    };
}

componentDidMount() {

    let insturl = DJANGOURL_rest_apis_instance_api.replace('__API__',this.props.api)
    let apiurl = DJANGOURL_rest_apis_one.replace('__API__',this.props.api)

    $.when(
        $.get(apiurl),
        $.get(insturl)
    ).then(function (api, instance) {

    }.bind(this),
    function(){
        // ERROR
    }.bind(this))
}
When running jest with the code below

    describe('APIInstanceView', () => {

    it('change api instance view based on state', () => {
        // Render a checkbox with label in the document
         const menu = TestUtils.renderIntoDocument(
             <APIInstanceView />
        );
    });

    });

I get a ReferenceError: DJANGOURL_rest_apis_instance_api is not defined.

How and where should I define the DJANGOURL_rest_apis_instance_api ?

Thanks

**Comment by bigblind** [comment]
DJANGOURL_rest_apis_instance_api is not defined by ReactJS or any other related library by facebook.  Search your production code and see where it is defined.

**Comment by keyanzhang** [comment]
Seems like it's not a bug of React. StackOverflow would be a better place to ask about this. Thanks!

**Comment by ptadas** [comment]
@keyanzhang regarding my question, would you know how the global variable should be specified so that I would not get the reference error? I tried doing in the the test script but it seems that it needs to be defined globally before react loads the module.
