### ISSUE TITLE
Allow indirect children in ReactTransitionGroup

### ISSUE THREAD

**Issue by sbai** [facebook/react#7146]
`ReactTransitionGroup` calls transition-related lifecycle hooks like `componentWillLeave` on its direct children. This is inconvenient when a child component is wrapped by a third-party decorator such as `@connect` or `@injectIntl`, because the decorators may return their own components, the outermost of which will be the direct child of `ReactTransitionGroup` and receive the lifecycle calls.

Would it be possible to let descendants register themselves (in their constructors, for instance) to receive these calls? This would save app developers the hassle of writing a wrapper component that sits between `ReactTransitionGroup` and the animated child just to intercept the hooks and pass them on in the presence of intermediate wrapper components.

**Comment by gaearon** [comment]
I agree this is painful and one of the reasons I personally don’t recommend `ReactTransitionGroup`. We’re also not using it actively on Facebook so we can’t be good stewards of its future direction. We plan to deprecate it or hand it off to the community.

I think the best you can do at the moment is fork it and implement your proposal. If your fork gains traction we might just point docs to it instead.

You may also want to consider alternatives like https://github.com/chenglou/react-motion or https://github.com/twitter-fabric/velocity-react.

Sorry about this!
