### ISSUE TITLE
Bug: Data Attributes not supported on Script element

### ISSUE THREAD

**Issue by abritinthebay** [facebook/react#7151]
Currently if I do the following:

```
renderToString(<Script
				key="foo"
				src="bar"
				data-somekey="baz"
			/>);
```
then the resulting script element does not have the custom data attribute.

This is problematic because many libraries use this to add data on load (eg, api keys, etc).

Data attributes appear to be supported on other elements - are they being specifically stripped for Scripts? If so... why?

**Comment by jimfb** [comment]
AFAIK, we don't strip data from script tags: http://jsfiddle.net/ym5choLh/

Keep in mind that you are rendering a `Script` with a capital `S`, which is a composite component of some sort.  Perhaps something one of your coworkers wrote.  They might not be rendering the data props, but that's not React's fault.

I'm going to close this out.  We can reopen if I'm proven wrong via a jsfiddle that demonstrates React doing something fishy.

**Comment by abritinthebay** [comment]
oh.. god... damnit.... it's a typo. I've just spent 2 hours on a typo.

Thanks, ignore me. Good god... argh. :(

**Comment by gaearon** [comment]
Curious—how did this typo not lead to an error? Was there really a `Script` component?

**Comment by abritinthebay** [comment]
*sigh* yes... there's was "script" component (that's used for loading 3rd party scripts) and in this case I was specifically trying to create a script element for our own code (that isn't bundled).

They don't say that naming things is one of the problems of programming for nothing... 

That said... it did lead me to being annoyed enough about this to refactor all of the above so everything is now much more sane and sensibly named/done/managed... so there's that as a net positive outcome.

(btw Dan, I still owe you that blog post about a React twist on Atomic design patterns, I have't forgotten)
