### ISSUE TITLE
Group warnings for unknown DOM properties

### ISSUE THREAD

**Issue by gaearon** [facebook/react#7152]
I just ran [React Bootstrap doc page](http://react-bootstrap.github.io/components.html) on master and saw a ton of warnings from #6800:

![jun 30 2016 01 55](https://cloud.githubusercontent.com/assets/810438/16473598/90585b8e-3e66-11e6-8e9e-7187935937dd.gif)

That page is really long so maybe it’s an edge case, but at the very least I think we should group props from the same element into a single warning. For example, these warnings could become one:

<img width="993" alt="screen shot 2016-06-30 at 01 53 11" src="https://cloud.githubusercontent.com/assets/810438/16473610/a5f6df06-3e66-11e6-964c-be482fdfeb27.png">

**Comment by gaearon** [comment]
If you’d like to work on this please comment in this thread so others know you’re taking it.
This is relatively high priority so please also comment if you abandon this, so others can pick it up.
Thanks!

**Comment by gm758** [comment]
I'd love to take a crack at this.

**Comment by gaearon** [comment]
@gm758 You got it! Let me know if you have any questions. #6800 would be a good reference for the warning we added—we just need to change it to accumulate “bad” props before emitting a single warning outside the loop.

**Comment by gaearon** [comment]
Fixed via #7153

**Comment by kennyhk** [comment]
hello, please can anyone tell me how to disable this warning? thank you!

**Comment by suhaotian** [comment]
@kennyhk I want to disable this warning..

**Comment by gaearon** [comment]
You can't disable it. We don't add warnings just to make your life harder. It warns about a problematic pattern that will behave unexpectedly in the next major version. You need to fix this. If you use third party libraries and warnings come from them, you need to file issues with those libraries so they get fixed.

Please read about warning and the discussion below: https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by akre54** [comment]
We load SVG files as react components using the [svg-react-loader](https://github.com/jhamlet/svg-react-loader).

The SVGs come from Illustrator and have an `xmlns` prop, which React doesn't recognize. In your opinion is it the library's responsibility to keep up to date with which props React supports? Is it our responsibility to remove any props React doesn't like? Should React support `xmlns`? What's the solution here?

**Comment by gaearon** [comment]
I think support for xmlns has been merged just a few days ago. So it'll be out in the next version.

**Comment by akre54** [comment]
Awesome to hear. Thanks.

**Comment by akre54** [comment]
Awesome to hear. Thanks.

For the future, is the right solution to try to keep React's list of accepted props complete and up-to-date?

**Comment by zpao** [comment]
Yes, however we should have pretty much everything from SVG and HTML. Hopefully there isn't much we missed but I fully expect new specs to come out and for us to need to handle that.
