### ISSUE TITLE
css minus positioning with z-index not working inside a component.

### ISSUE THREAD

**Issue by arnor-ragnarsson** [facebook/react#7155]
Ok, so I got an img that is inside a component and I want to position it between two component so that where one component end and a new begins should be in the middle of the img, I can position the img but the component that doesn't hold the img is positioned on top of the img and z-index doesn't work to bring the img to front.

Any idea what I can do?

Many thanx
AAR

**Comment by DaveSauce** [comment]
This sounds like a straight CSS issue. Make sure all elements that need to have their `z-index` set have either absolute or relative positioning, and that they share the same parent element.

**Comment by zpao** [comment]
Definitely doesn't sound React specific. Closing out but let me know if you are encountering a bug in React.
