### ISSUE TITLE
Setting autoFocus on an input warns.

### ISSUE THREAD

**Issue by jacehensley-wf** [facebook/react#7156]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Warns when `autoFocus` is set

**Steps to reproduce**
1. Render an input with the autoFocus prop set
2. See that it spit out a warning

Demo: https://jsfiddle.net/2wgv7ws1/

**What is the expected behavior?**
Setting `autoFocus` should not warn when set on a `<input>`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am seeing this warning in the 15.2.0 rc. It did not warn in 15.1.0.

**Comment by zpao** [comment]
I think https://github.com/facebook/react/pull/7098 should cover this. I'll make sure that gets into 15.2.0 before releasing. Thanks for testing!
