### ISSUE TITLE
Potential Issue with How Components are Imported

### ISSUE THREAD

**Issue by AdamKyle** [facebook/react#7162]
So consider the following:

```
import React           from 'react';
import ReactDOM        from 'react-dom';
import SomeComponent from './some_component';

export class Dashboard extends React.Component {

  render (
     return (
       <div> <SomeComponent /> </div>
    );
  )

}

let dashboardElement = document.getElementById("dashboard");

if (dashboardElement !== null) {
  ReactDOM.render(
    <Dashboard />,
    dashboardElement
  );
}

// In Some other file ... 
import React           from 'react';
import ReactDOM        from 'react-dom';

export class SomeComponent extends React.Component { ... }

```

The issue here, or at least I believe it to be an issue is that `export` isn't being treated properly by React (or maybe babel?) as I get the error:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Dashboard`.
```

and

```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Dashboard`.
```

Now the second I do:

```
import React           from 'react';
import ReactDOM        from 'react-dom';

class SomeComponent extends React.Component { ... }

module.exports = SomeComponent;
```

Everything works.

Now unless I am not understanding at a fundamental level, export and module.exports are (essentially) the same, so why does react recognize the latter but not the first?

Is this a me thing or a you thing?

**Comment by alexzherdev** [comment]
Perhaps you're missing export **default** class ...?

**Comment by AdamKyle** [comment]
Is that a thing? I thought that was only for self contained functions

On Jul 1, 2016, at 11:53 AM, Alex Zherdev <notifications@github.com<mailto:notifications@github.com>> wrote:


Perhaps you're missing export default class ...?

-

**Comment by zpao** [comment]
I think if you leave off the `default` then `SomeComponent` is a named export, which you would need to import like `import {SomeComponent} from './some_component'`

This isn't a React issue, just ES6 modules, so I'm going to close out but since you have some discussion going, feel free to work it out. We can reopen if it turns out to be a React issue.

**Comment by gaearon** [comment]
See also my answer on [default and named imports and exports](http://stackoverflow.com/questions/36795819/react-native-es-6-when-should-i-use-curly-braces-for-import/36796281#36796281).
