### ISSUE TITLE
Form submit button has empty values in 15.2.0

### ISSUE THREAD

**Issue by h8rry** [facebook/react#7179]
**Do you want to request a *feature* or report a *bug*?**

This is a bug

**What is the current behavior?**

![screen shot 2016-07-03 at 4 12 19 pm](https://cloud.githubusercontent.com/assets/1697380/16544656/b3f896b2-4140-11e6-923a-06fc630c92df.png)
![screen shot 2016-07-03 at 4 11 15 pm](https://cloud.githubusercontent.com/assets/1697380/16544657/b3f8f292-4140-11e6-8b03-0ecaa3165460.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Using 15.2.0 react and react-dom

**What is the expected behavior?**

![screen shot 2016-07-03 at 4 13 05 pm](https://cloud.githubusercontent.com/assets/1697380/16544659/b938951e-4140-11e6-9275-2c3721542003.png)
![screen shot 2016-07-03 at 4 13 10 pm](https://cloud.githubusercontent.com/assets/1697380/16544660/b9391278-4140-11e6-9951-0f81024ce859.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

In 15.2.0, extra attributes `name` and `value` with empty values are added to the submit button of a form.

It works in 15.1.0.

**Comment by kostasmanionis** [comment]
Uhhh, seems that this was missed on https://github.com/facebook/react/pull/6406? The culprit here is `postMountWrapper` in `ReactDOMInput.js`

`node.value = node.value;` 🙊

**Comment by franzejr** [comment]
@h8rry, I think your links for behavior are not saved correctly.

Current behavior(ReactJS 15.2.0):
https://jsfiddle.net/69z2wepo/47613/

ReactJS (15.1.0):
https://jsfiddle.net/69z2wepo/47612/

**Comment by zpao** [comment]
Thanks for catching! I put up something that at least fixes the constant render case. I think we'd always have this problem if you toggled value of these inputs from a real value to undefined so I'm not too worried about trying to handle that.
