### ISSUE TITLE
Error in production but not in devlopment.

### ISSUE THREAD

**Issue by Catlite91** [facebook/react#7181]
I've no idea about this error only occured in production version
Is there anything wrong?
Many thanks!

Here are some of the information:
![image](https://cloud.githubusercontent.com/assets/9129944/16550036/565523ca-41d8-11e6-8de3-ebc1e5c720ad.png)

Uncaught Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.reactProdInvariant @ app.fbd84ee….js:245
addComponentAsRefTo @ app.fbd84ee….js:56072
attachRef @ app.fbd84ee….js:56292
ReactRef.attachRefs @ app.fbd84ee….js:56311
attachRefs @ app.fbd84ee….js:5030
notifyAll @ app.fbd84ee….js:18972
close @ app.fbd84ee….js:56181
closeAll @ app.fbd84ee….js:8395
perform @ app.fbd84ee….js:8342
batchedMountComponentIntoNode @ app.fbd84ee….js:21215
batchedUpdates @ app.fbd84ee….js:55156
batchedUpdates @ app.fbd84ee….js:2137
_renderNewRootComponent @ app.fbd84ee….js:21384
_renderSubtreeIntoContainer @ app.fbd84ee….js:21463
render @ app.fbd84ee….js:21484
_selectHandler @ 0.8a2eff5….chunk.js:17182
fireChange @ 0.8a2eff5….chunk.js:6169
onMenuSelect @ 0.8a2eff5….chunk.js:5837
onClick @ app.fbd84ee….js:41524
onClick @ app.fbd84ee….js:41745
invokeGuardedCallback @ app.fbd84ee….js:11203
executeDispatch @ app.fbd84ee….js:10771
executeDispatchesInOrder @ app.fbd84ee….js:10794
executeDispatchesAndRelease @ app.fbd84ee….js:6357
executeDispatchesAndReleaseTopLevel @ app.fbd84ee….js:6368
forEachAccumulated @ app.fbd84ee….js:22458
processEventQueue @ app.fbd84ee….js:6534
runEventQueueInBatch @ app.fbd84ee….js:55275
handleTopLevel @ app.fbd84ee….js:55286
handleTopLevelImpl @ app.fbd84ee….js:55368
perform @ app.fbd84ee….js:8329
batchedUpdates @ app.fbd84ee….js:55158
batchedUpdates @ app.fbd84ee….js:2137
dispatchEvent @ app.fbd84ee….js:55445

**Comment by gaearon** [comment]
Thanks for the report!
I believe your message contains a link.
Have you tried following it?

http://facebook.github.io/react/docs/error-decoder.html?invariant=119

It says:

>You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

The link with details links to a gist that explains how to fix it: https://gist.github.com/jimfb/4faa6cbfb1ef476bd105

**Comment by Catlite91** [comment]
Thanks！

**Comment by hirako2000** [comment]
As a banged my head against the wall for a couple of hours on this, don't forget to
`rm -rf node_components`
`npm install`
if the error message can't be explained nowhere.

**Comment by Aristona** [comment]
@hirako2000 You mean `node_modules`?

**Comment by hirako2000** [comment]
Yes @Aristona , typo. I edited the comment thanks.

**Comment by nirlendu** [comment]
If you're using CloudFlare, please disable auto-minification of HTML.

**Comment by chadoh** [comment]
For an explanation of why disabling Cloudflare's HTML minification is necessary, see [this StackOverflow answer](https://stackoverflow.com/a/44357173/249801)

**Comment by priyanka1006** [comment]
I found this error 

sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189 Error: Minified React error #137; visit http://reactjs.org/docs/error-decoder.html?invariant=137&args[]=input&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at r (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:197)
    at r (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
    at Wt (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
    at Gt (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
    at finalizeInitialChildren (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:197)
    at completeWork (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
    at o (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
    at a (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
    at i (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
    at C (sp-webpart-workbench-assembly_en-us_9bb57df9d7ae3f8d7383236994a95261.js:189)
