### ISSUE TITLE
LinkedIn React users group proposed Angular's jobs on subcription

### ISSUE THREAD

**Issue by Strato** [facebook/react#7184]
Hello,

I just subscribed to the [LinkedIn React users group](https://www.linkedin.com/groups/6519652), and I thought you would like to know that it's currently administered by an Angular guy who proposed to look for Angular jobs on subscription.

Not really what one might expect...

![linkedin react group subscription](https://cloud.githubusercontent.com/assets/662430/16560022/0c455cbe-41f1-11e6-8e20-2fc64a063dc1.PNG)

**Comment by gaearon** [comment]
Hi!

This group is not maintained by us so I don't think we can help with anything. If this is considered spam by LinkedIn, you can report it to them (but maybe it's fine, I don't know their terms). 

We use issue tracker for bugs and feature requests. I'll close this as it is not actionable for us.

Cheers!
