### ISSUE TITLE
CSSTransitionGroupChild should generate markup with -enter class already applied

### ISSUE THREAD

**Issue by pgherveou** [facebook/react#719]
Hello there,

I am playing with React transition

I noticed that the **-enter** classe is added only after the element has been inserted into the dom.

https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionableChild.js#L147-L150

I thought the active class was applied when the component was mounted into the dom.

Here is a small demo:  http://jsfiddle.net/437Us/1/
I am using componentWillUpdate to make sure the class is applied directly. If you remove it, and use the same 
transition mechanism on a more complex layout  sometime you will see the page flashing into the screen before the transition starts

**Comment by santiagoaguiar** [comment]
Is there any progress on this? `ReactCSSTransitionGroup` seems a good fit for our cases, but having this issue in multiple places makes it hard to use.

**Comment by spicyj** [comment]
Sorry, no progress on this. It's hard to make this happen automatically with our current architecture.

**Comment by tsnieman** [comment]
Would adding `initial` + `finished` states (classes) for the transition be easier than adding the `enter` class on initial render? (basing this on "It's hard to make this happen automatically with our current architecture." by @spicyj in previous post)

Or is there some other workaround for this which I'm not seeing? Or is there a better alternative to ReactCSSTransitionGroup at this point?

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition
