### ISSUE TITLE
React strips 'for' property from <label> tag and issues a warning 

### ISSUE THREAD

**Issue by nigelterry** [facebook/react#7192]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
React is flagging a warning and stripping the 'for' property from <label> tag
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

https://jsfiddle.net/nigelterry/ne8a627m/3/

**What is the expected behavior?**
Should not strip for and not issue a warning
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.2.0 with Chrome / Fedora23

**Comment by Aweary** [comment]
@nigelterry as the warning states, you should use `htmlFor` instead of `for`

**Comment by nigelterry** [comment]
Duh! Sorry
