### ISSUE TITLE
Input elements always rendered with `name` attribute

### ISSUE THREAD

**Issue by okonet** [facebook/react#7198]
**Do you want to request a *feature* or report a *bug*?**

This is a bug (I think)

**What is the current behavior?**

When rendering `<input type="..." />` (without name attribute), it will render `<input type="..." name />` to the DOM.

![2016-07-06 at 09 49](https://cloud.githubusercontent.com/assets/11071/16611205/13bcd376-4360-11e6-9ef5-de6bec6eaa4a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Here is the example with the regression using React 15.2.0: https://esnextb.in/?gist=c4923716061ca73e37f7ed476920aa9c

![2016-07-06 at 09 49](https://cloud.githubusercontent.com/assets/11071/16611190/0ba328e8-4360-11e6-8e1a-049048c661f5.png)

**What is the expected behavior?**

No `name` attribute rendered if it is not provided.

Here is the expected behavior with React 15.1.0: https://esnextb.in/?gist=aee86dfa6eec38aa2bc24b4c25425905

![2016-07-06 at 09 54](https://cloud.githubusercontent.com/assets/11071/16611196/10edae9a-4360-11e6-8191-eb19fd9363f8.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Regression: v15.2.0

Good: v15.1.0

**Comment by syranide** [comment]
> Here is the example with the regression using React 15.2.0: https://esnextb.in/?gist=c4923716061ca73e37f7ed476920aa9c

Is using React 15.1.0 so it's not showing there, but yes I see the problem as well.

cc @jimfb #6406 https://github.com/facebook/react/pull/6406/files#diff-1b0e3b280991cd0b7cde194b30353b3eR253

**Comment by syranide** [comment]
So there are two problems with that #6406.

https://github.com/facebook/react/pull/6406/files#diff-1b0e3b280991cd0b7cde194b30353b3eR250 + https://github.com/facebook/react/pull/6406/files#diff-1b0e3b280991cd0b7cde194b30353b3eR253 should only be set when `name !== ''`.

https://github.com/facebook/react/pull/6406/files#diff-1b0e3b280991cd0b7cde194b30353b3eR250 should set it to `''` and not `undefined` as that actually translates to `'undefined'`. Which makes it still named.

**Comment by okonet** [comment]
@syranide I've updated the first gist with proper version. Sorry messed it up a bit.

**Comment by alexzherdev** [comment]
If there are no objections, I'd like to try and fix this one.

**Comment by okonet** [comment]
I'm already on it.

**Comment by alexzherdev** [comment]
k, no problem
