### ISSUE TITLE
[enhancement] HTML/XML comment support for JSX

### ISSUE THREAD

**Issue by pke** [facebook/react#7201]
# Feature

Support XML `<!-- -->` comments in JSX

## Current status
Currently the only way to insert comments into JSX flow is to wrap them in JS:

`{/**/}`

In context:

```jsx
<Foo>
  {/* I will tell you why this component is here */}
  <Bar>
  </Bar>
</Foo>
```

## Proposed extension

XML like comments.

```jsx
<Foo>
  <!-- I will tell you why this component is here -->
  <Bar>
  </Bar>
</Foo>
```

This would also allow us to quickly temporarily comment out components in the JSX flow like this:

```xml
<Foo>
  <!--Bar>
  </Bar-->
</Foo>
```

**Comment by gaearon** [comment]
Thanks for the proposal!
https://github.com/facebook/jsx would be the right place to discuss this.
There is an issue on this (https://github.com/facebook/jsx/issues/7) so you can voice support there.

**Comment by pke** [comment]
ah you right, sorry
