### ISSUE TITLE
Bot: comment on PRs when build size changes by some threshold

### ISSUE THREAD

**Issue by zpao** [facebook/react#7205]
It would be nice to establish some threshold and have a bot comment on a PR when it adds some number of bytes to the UMD build size. Once that's setup we can potentially add some other metrics we want to track and have some notification about.

**Comment by keyanzhang** [comment]
@vjeux do you want me to do this? The server I wrote is pretty similar to this requirement.

**Comment by orta** [comment]
I don't know if you would only use the Facebook bot infrastructure, but this is the kind of thing that [danger](https://github.com/danger/danger) is really good at.

**Comment by aweary** [comment]
[react-linter](https://github.com/react-linter) now does this 👍
