### ISSUE TITLE
deprecation warnings in production

### ISSUE THREAD

**Issue by dgoldstein0** [facebook/react#7224]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

all warnings are stripped out in the production build

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

ideally, we'd have the important warnings in production - namely, the ones that either (1) indicate something broken or (2) will definitely be broken by the next major version upgrade of react.  React could then provide a function to register a callback that would be called for every warning in prod, and the callback would be responsible for doing whatever it wanted (e.g. capturing a stack trace & reporting the error to the server)

Since I've been working on react .12 (which I know is not supported) I hacked up my own version of this.  Unfortunately ended up split across a few commits since I didn't test well before pushing:

Implements the callback registration:
https://github.com/dropbox/react/commit/dfa7df23d728fbda699986fbb6100393d015dee1 is the main hook; the next two are bugfixes:
https://github.com/dropbox/react/commit/221ac6e835e3b31b0c48ccbea198c3f9cd3be9ef
https://github.com/dropbox/react/commit/65c47155c93c76222be5f2e932e56c0fbad46f5d

This diff got me most of the warnings I wanted from React .12 (`__DEBUG__` is my hack to keep stuff for the "debug" build which is really what I'm trying to use in prod).  The exact details aren't too important but should give an idea of the flavor of things I'm looking for - "will be broken in the next version" and "almost certainly this is a bad bug".

https://github.com/dropbox/react/commit/eef7fac4a4ce63c151fe418f9fab78e513d73052

Ideally, this system would also make use of the new error codes to keep the warning messages from weighing down the prod build of react; for my version, since I was highly selective about the warnings I kept, there's only a potential ~1kb to save from stripping the messages anyway, so it might not be worth the effort unless we choose to keep significantly more warnings for prod.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

all

**Comment by dgoldstein0** [comment]
btw two motivations for this request:
- existing codemods don't help us much since most of our react code is in coffeescript
- we don't have great test coverage across our frontend, so finding and fixing warnings in prod is our next line of defense.

**Comment by gaearon** [comment]
We are unlikely to support something like this in the close future so your best bet is to maintain a fork of `warning` system. We do something similar at Facebook: the `warning` module is forked.

We'll be happy to revisit this in a year or so but right now this issue is not a priority for us.
