### ISSUE TITLE
Not show

### ISSUE THREAD

**Issue by BrunoQuaresma** [facebook/react#7228]
**Report Bug**

**Not enable the react tab in developer tools**

**React 15.2.0, and Chrome**

![image](https://cloud.githubusercontent.com/assets/3165839/16700485/ac14915a-4530-11e6-8012-d63028a1ca58.png)

**Comment by maxdeviant** [comment]
Are there any errors in the developer console?

**Comment by BrunoQuaresma** [comment]
@maxdeviant i found the cause to this problem. The webpack-dev-server run the app inside an iframe so, the react dev tools can't load it. Thanks.
