### ISSUE TITLE
This page is not found

### ISSUE THREAD

**Issue by GaryChangCN** [facebook/react#7239]
https://github.com/facebook/react/blob/master/react/docs/getting-started.html
### cannot found
which is in https://github.com/facebook/react/blob/master/docs/docs/02.1-jsx-in-depth.md

If you want to use JSX, the` Getting Started` guide shows how to set up compilation.

**Comment by gaearon** [comment]
These are sources for the docs so links won’t work.
You should read them on the website instead:

https://facebook.github.io/react/docs/getting-started.html
https://facebook.github.io/react/docs/jsx-in-depth.html
