### ISSUE TITLE
Custom properties are not set in style objects.

### ISSUE THREAD

**Issue by danielgamage** [facebook/react#7241]
When using [CSS custom properties](https://drafts.csswg.org/css-variables/) as inline styles, React logs the following to the console in dev mode:

>`Warning: Unsupported style property --color-accent. Did you mean -colorAccent? Check the render method of 'Hello'.`

Demo: https://jsfiddle.net/69z2wepo/48528/

This is logged in `/lib/CSSPropertyOperations.js` from `warnHyphenatedStyleName()` and `warnValidStyle()` before it. More importantly than the warning, though, the styles are not applied to the elements on the client side, in both dev and production. They _are_ applied in a server rendering ( and maybe initial client render? ), but not on the client side if those elements are taken out of the DOM and put back in from state changes. See #932 for more info. 

This affects me on chrome and react@15.2.1.

**Comment by zpao** [comment]
I'm going to close out and point to #6411 which is covering the same topic and has some discussion.

**Comment by danielgamage** [comment]
Whoops blatant oversight on my part. Thanks for the link.
