### ISSUE TITLE
Can a react state set up to a Set object?

### ISSUE THREAD

**Issue by futurefeeling** [facebook/react#7256]
Like following code:

```js
class Component extends React.Component {
    constructor(props){
        this.state = {
            state1: new Set()
        }
    }
    ...
}
```

so if I want to change the Set, I use following code: 

```js
componentDidMount(){
    this.state.state1.add('something');
    // or this.state.state1.delete('something');
}
```

it will change the state directly!

but by the official note: 

![image](https://cloud.githubusercontent.com/assets/9881593/16790594/d62113ee-48e9-11e6-9c9b-b539012d4dfc.png)

**Comment by syranide** [comment]
```js
var newState1 = new Set(this.state.state1);
newState1 = .add('something')

this.setState({
  state1: newState1
});
```

Something like that if you want to have it immutable (good idea).

What you're doing is *valid* but you then need to call `this.forceUpdate()` after updating it, if you absolutely want to go that way, but there are caveats, so I really recommend sticking with immutable.

**Comment by futurefeeling** [comment]
@syranide thanks for reply. I got your point, but it has no warning in browser's console in my way. So  I'm confuse that whether the official allow this case.

**Comment by syranide** [comment]
> but it has no warning in browser's console in my way

@futurefeeling It can't be detected, so it's impossible to warn for. Also, as I said, it is valid. Just not recommended. Your scenario does not match the warning in the documentation, it's different (i.e. don't do `this.state.value = A').

> So I'm confused that whether the official allow this case or more thinking.

It's allowed, but not recommended. Technically you are not mutating state (not ok), you have a mutable object in state (ok).

**Comment by futurefeeling** [comment]
@syranide thanks
