### ISSUE TITLE
Error messages omitting relevant components displayName

### ISSUE THREAD

**Issue by alexmcmillan** [facebook/react#7257]
Please forgive me if this appears more like a rant than a feature request, but I have searched and can't find any explanation for why some error messages are displayed without any `displayName` from the component responsible - and this is driving me insane.

*Every* component in my project has an explicit `displayName` specified.  I do this for debugging.

I am rendering a bunch of immutable props.  I changed one of the prop types from a `List` to a `Map` and I see:

> Warning: Using Maps as children is not yet fully supported. It is an experimental feature that might be removed. Convert it to a sequence / iterable of keyed ReactElements instead.

Obviously I missed something, which could be easily fixed if I knew *where* it was - even just the component's name.

This message is not only frustrating, but it's taunting "I know where the problem is but I won't tell you!"-feel makes it infuriating.  Looking at the stacktrace behind it is useless as well because it's, as usual, a never-ending list of React function calls with no mention of any of my source files.

I have spent countless time hunting down errors like this that would have taken only moments if I knew the name of the component responsible.  It would be *infinitely more helpful* if the `displayName` field appeared in more debug output.

**Comment by keyanzhang** [comment]
Thanks for catching this! #7260

**Comment by keyanzhang** [comment]
By the way, you actually don't need to set `displayName` explicitly if you use JSX: https://facebook.github.io/react/docs/jsx-in-depth.html#the-transform

**Comment by alexmcmillan** [comment]
First, Sorry if I sounded... angry.  I was in developer rage at the time.

Anyway, wow!  I didn't realise it would be that easy.  Hopefully this helps avoid future dev rage.

I still think it's a good idea to specify a `displayName` for clarity, and it also avoids `import MyComponent as MyCoolComponent ...` issues (ie: "Check the render method of MyCoolComponent").

Thanks for your help.

**Comment by keyanzhang** [comment]
Hey no problem. I recalled that I ran into this issue too so I totally feel your pain.
