### ISSUE TITLE
Add Dependency CI checks

### ISSUE THREAD

**Issue by lukaswelte** [facebook/react#7261]
[Dependency CI](https://dependencyci.com) is a new service out there.
It checks the status of the projects dependencies post commit.
It is able to read the dependencies from package.json and checks the dependencies for various metrics, e.g. for being deprecated, unmaintained or check the license.

**What is the current behavior?**
Currently when adding or updating dependencies you have to check them manually.

**What is the expected behavior?**
Enabling this could just give some additional metrics on the dependencies of the project. 

It is free, fast and does not need any integration than signing up with GitHub giving it access to the repo and enabling the switch.
Other large open source repositories like pm2 or Mozilla's Servo have already enabled it.

**Comment by gaearon** [comment]
We’re pretty conservative about adding deps so I don’t think this will be very useful to us. But thanks!
