### ISSUE TITLE
Improve warnings about refs on functional components during runtime and in docs

### ISSUE THREAD

**Issue by pke** [facebook/react#7267]
I had trouble to get `ref` working on one of my composite components.

This inline ref function

`<MyComp ref={element => this.listElement = element}/>`

will always be called with `element===null` on mount and unmount the like. Thats because `MyComp` is a stateless/functional component.

react should print a warning if one tries to use `ref` with stateless components.

**Comment by stephenkingsley** [comment]
I think `stateless component` just a tool, so in my options, this is unnecessary.

**Comment by Maximilianos** [comment]
This issue can be closed because I believe it has been resolved by: https://github.com/facebook/react/pull/8635

**Comment by aweary** [comment]
@Maximilianos thanks!
