### ISSUE TITLE
Microsoft Edge - Has textInput event fires twice during ctrl-a selection + keypress and crashes Draft-JS

### ISSUE THREAD

**Issue by butchmarshall** [facebook/react#7269]
This issue was discovered while building an editor in Draft-JS (see original issue filed [here](https://github.com/facebook/draft-js/issues/501))

Edge provides a TextEvent - but it's still not useful.  Disabling canUseTextInputEvent in React for Edge fixes the Draft-JS issue.

To reproduce the bug in Draft-JS:

Go to https://facebook.github.io/draft-js
type "a"
hit enter
type ctrl-a to select everything
type "j"

You'll get a javascript error. The editor (actually, the ReactDomComponent) is then in a confused state.

The DOM component that the react component points to is prematurely removed.

**Comment by jdalton** [comment]
I can't repro this on the insider preview of Edge 15.
