### ISSUE TITLE
Chrome debugger causes some event listeners to be skipped

### ISSUE THREAD

**Issue by timhwang21** [facebook/react#7271]
**Browser**: Chrome 51, Mac

I have a React component that includes both an `onKeyDown()` and `onChange()` function. The component renders (among other things) an `<input />` with these functions as props. 

**Unexpected behavior:** Without breakpoints from Chrome debugger, both functions run correctly. However, when there is a breakpoint introduced into the `onKeyDown()` method, the `onChange()` function is _entirely skipped._ I am not sure if this is an intended consequence of how synthetic events are reused, but it seems unexpected to me.

**Steps to reproduce:** 
1. [JSfiddle](https://jsfiddle.net/69z2wepo/48909/)
2. Open dev tools; note that `onChange()` never runs
3. Comment out `debugger;`, note that now `onChange()` runs

**Comment by gaearon** [comment]
I can’t reproduce this. Probably a fixed Chrome bug.
