### ISSUE TITLE
onInput is not firing on contentEditable div in IE11

### ISSUE THREAD

**Issue by tomericco** [facebook/react#7280]
When using `onInput` event on `contentEditable` `div`, the event is not being fired on IE11. It does work on Chrome 51.0.2704.103 (64-bit) and Microsoft Edge. It also reproduces on React 0.14.*, so it doesn't seem to be a regression.

See it being reproduced here: https://jsfiddle.net/dbmu8yps/

Maybe related to #4051 , @jquense?

**Comment by gaearon** [comment]
Does vanilla DOM event work?

**Comment by tomericco** [comment]
Sure. But I just executed the same snippet above with React 15.2.0, and it works.
Closing the issue.

**Comment by misterblblbl** [comment]
Still able to reproduce the issue in IE11 with React 15.2.0 and React 15.6.1:
https://jsfiddle.net/dbmu8yps/6/

**Comment by gaearon** [comment]
@misterblblbl Please file a new issue if the problem is still relevant, we're not tracking closed issues. Thanks.
