### ISSUE TITLE
Input onChange not triggered every time in IE11 if e.preventDefault() used

### ISSUE THREAD

**Issue by jmullo** [facebook/react#7281]
Input onChange not triggered every time if e.preventDefault() is called in onChange handler.

Occurs when typing fast: some characters are lost.

React 5.0.2 & IE11.

**Comment by ishannaithani** [comment]
@jmullo - Were you able to fix this? I am also facing a similar issue - Would help if solution posted.

**Comment by jmullo** [comment]
I just removed the e.preventDefault() call as it wasn't completely necessary for functionality.

**Comment by ishannaithani** [comment]
Thanks! I was able to fix by changing onChange to onInput. 

A similar discussion is posted here which could be helpful :https://github.com/facebook/react/issues/7027

**Comment by Axe-Pearl** [comment]
Please assign this to me

**Comment by gaearon** [comment]
We've dropped IE from supported browsers in React 18 so this is unlikely to get fixed.
Sorry.
