### ISSUE TITLE
Attributes from html element 

### ISSUE THREAD

**Issue by Houd1ny** [facebook/react#7294]
Hi, I`m new with react. I wanted to implement simple feature. But I need to accesses html element properties before it was rendered 
for example I have html code 
```
<div class="myCustomobject" data-mydata="url1">
<div class="myCustomobject" data-mydata="url2">
```
And I want to access  mydata from myCustomobject and that two instances was rendered with different data. I think it`s possible to set attributes for myCustomobject before replacing div.
I have not found in documentation how to do it right now.
Thank you!

**Comment by brigand** [comment]
This bug tracker is for issues with react itself. For usage questions, please ask on StackOverflow or IRC.

The short version is that you should already have the data in js, so there's no need to pull it from the dom.
