### ISSUE TITLE
help for getting rid of the use case of TimerMixin in React Native

### ISSUE THREAD

**Issue by love4shen** [facebook/react#7298]
**Do you want to request a *feature* or report a *bug*?**
help request

**What is the current behavior?**
I want to replace `TimerMixin` in my React Native with something else. Given that Dan has talked about downsides of using mixins, I still cannot find a solution for my use case.

**Comment by zpao** [comment]
https://github.com/reactjs/react-timer-mixin/issues/4 has some discussion so lets close this out and just keep it there.
