### ISSUE TITLE
Highlight element that failed checksum

### ISSUE THREAD

**Issue by davidgilbertson** [facebook/react#7300]
At the moment, when the server-rendered markup doesn't match the client-rendered markup, a big red error is shown, but it can be difficult/impossible to locate the element where this occurred.

Would something that logged the offending element to the console be considered as a pull request?

![react-diff](https://cloud.githubusercontent.com/assets/4443482/16935229/07cc7b20-4da1-11e6-9e30-f5f584d33182.gif)

https://github.com/facebook/react/compare/master...davidgilbertson:log-checksum-failed-element

**Comment by gaearon** [comment]
This sounds interesting. We don't do checksum validation anymore in 16 but still need to report differences. I mentioned this approach in https://github.com/facebook/react/issues/10085 so let's keep the discussion there.
