### ISSUE TITLE
After updating to React 15.2, react-flexbox-grid is throwing lots of similar warnings:

### ISSUE THREAD

**Issue by zp1112** [facebook/react#7301]
**Do you want to request a *feature* or report a *bug*?**

> Unknown props `secondary`, `primary` on <div> tag

**What is the current behavior?**

> Unknown props `xs`, `md` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Col)
    in Col (created by Index)
    in div (created by Row)
    in Row (created by Index)
    in div (created by Index)
    in div (created by Index)
    in Index (created by Connect(Index))
    in Connect(Index) (created by ReactRouterProxy)
    in ReactRouterProxy (created by RouterContext)
    in div (created by Template)
    in div (created by Template)
    in div (created by Template)
    in Template (created by ReactRouterProxy)
    in ReactRouterProxy (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by syranide** [comment]
React 15.2 now warns if there are unknown properties supplied to HTML tags. This is an issue with react-flexbox-grid, I suggest you submit this issue to them instead.

**Comment by gaearon** [comment]
Indeed, this is not a bug in React.
You would need to file this issue with `react-flexbox-grid`. 

https://fb.me/react-unknown-prop explains how to fix the problem on their side.

Cheers!

**Comment by zp1112** [comment]
thx! @gaearon
