### ISSUE TITLE
PropTypes: More informative warning in createElementTypeChecker

### ISSUE THREAD

**Issue by alexzherdev** [facebook/react#7302]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
Element type checker is not as informative as the other ones.

**What is the expected behavior?**
It would be nice to provide the actual type of the prop passed similarly to other type checkers. I.e., instead of 
> Invalid prop `Prop` supplied to `Component`, expected a single ReactElement.

say

> Invalid prop `Prop` of type `type` supplied to `Component`, expected a single ReactElement.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Seeing this on 15.2.1 but I think it's also applicable to previous versions.

I know the general intention is to move away from prop types, but if there isn't a specific reason for the current behavior I can look into making this more pretty.

**Comment by gaearon** [comment]
Sounds good to me.

**Comment by RaitoBezarius** [comment]
May I take it, please? @gaearon 
Except if @alexzherdev wants to tackle it, of course!

**Comment by alexzherdev** [comment]
Yup, I'm on it.

**Comment by RaitoBezarius** [comment]
@alexzherdev Awesome! :+1:
