### ISSUE TITLE
request: optional strict validation for valid attributes in React Native renderer

### ISSUE THREAD

**Issue by finnigantime** [facebook/react#7310]
**Do you want to request a _feature_ or report a _bug_?**
feature request

**What is the current behavior?**
Consider this code from `ReactNativeAttributePayload.diffProperties()`:

```
  for (var propKey in nextProps) {
    attributeConfig = validAttributes[propKey];
    if (!attributeConfig) {
      continue; // not a valid native prop
    }
```

If I pass invalid properties on the node, they are simply skipped over.

**What is the expected behavior?**
I would like a warning that I'm using some illegal property that's not understood. It would make it much easier to determine why the property I'm trying to set is not taking effect (e.g. because I misspelled the property name or because that property actually doesn't exist on the type I'm trying to set it on). So, I think I'm looking for an assert here (a check that only runs if **DEV** is true). It would probably have to be configurable to support existing code that sets invalid properties on nodes - you can turn it on for strict attribute validation, but it's off by default.

I'm happy to put up a PR to add this, but I don't see configuration for the React Native renderer code. Where could I add a property e.g. `enableStrictAttributeValidation`?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.2.0

**Comment by gaearon** [comment]
Can you please file this to discuss with React Native community instead? If RN maintainers are okay with it then we could take a PR implementing it.
