### ISSUE TITLE
cannot find module 'react/addons',how to solved this issue?

### ISSUE THREAD

**Issue by Feahter** [facebook/react#7314]
**Do you want to request a *feature* or report a *bug*?**
I try to use gulp&browserify run a react demo,but get this answer in windows-7.
**What is the current behavior?**
![image](https://cloud.githubusercontent.com/assets/13764431/16972567/2a2729b8-4e5f-11e6-8119-8d4ed230eaf4.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**
I want to fix this demo ,god please help.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by cht8687** [comment]
I assume that your demo project has module dependency on react-addons module which you didn't install it. Perform a `npm install` might solve  your problem.

I think questions like this shouldn't be asked here as an 'issue'. Better to ask it in other places rather than open a ticket.

**Comment by Feahter** [comment]
ok, thanks.I am so sorry ,I will close this issue soon. react/addons this folder is exist in react, i try to npm uninstall react ,npm install react again,even  npm install addons in react,this problem is not besolved.
