### ISSUE TITLE
Facing problem with react webpack installation

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react#7315]
I have followed the steps as it is in- https://facebook.github.io/react/docs/package-management.html

npm install --save react react-dom babel-preset-react babel-loader babel-core
webpack main.js bundle.js --module-bind 'js=babel-loader'

But got the error like  the shared screen. Please how can solve this? Or is there any proper installation guide for React, Redux & webpack?

![issue](https://cloud.githubusercontent.com/assets/10433734/16976201/dce0f7cc-4e6a-11e6-81fa-7f7605126557.jpg)

**Comment by milesj** [comment]
Have you tried `npm install webpack`?

**Comment by mxstbr** [comment]
> Error: Cannot resolve module `main.js`

That means the `main.js` file doesn't exist in the folder you're trying to run the `webpack` command in. Could that be the case?

**Comment by krishbhattacharyya** [comment]
Thanks for reply. @milesj & @mxstbr 
I have already installed-  npm install -g webpack . 

Yes @mxstbr I did not add main.js in folder...

Can you share please the proper way to installed the react+ redux+webpack.

**Comment by mxstbr** [comment]
You have got everything installed perfectly fine, add a `main.js` file in that folder with these contents and it _should_ work:

```JS
// main.js
var React = require('react');
var ReactDOM = require('react-dom');

ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('example')
);
```

**Comment by krishbhattacharyya** [comment]
Thanks @mxstbr .
Actually you did not get my point.

My steps- 

1) npm init
2) give name "package name"
3) npm install react react-dom --save   ( save the dependencys )
4) npm install --save  babel-preset-react babel-loader babel-core babel-preset-es2015

Then I got the error like this- 
![last](https://cloud.githubusercontent.com/assets/10433734/16977907/9cc41b0e-4e76-11e6-99cd-253b8c883232.jpg)

**Comment by usirin** [comment]
@krishbhattacharyya adding `webpack` as local dependency as well should do the trick.

```
npm install webpack --save-dev
```

**Comment by krishbhattacharyya** [comment]
Thanks @usirin 

But "npm install webpack --save-dev" not supporting my operating system(Vista). Thanks everybody.

**Comment by gaearon** [comment]
What do you mean by not supporting? Webpack works on Windows.

**Comment by krishbhattacharyya** [comment]
Sorry for late reply @gaearon, I have tried many time on vista (with the  npm install webpack --save-dev) but every time I was failure.  I was stuck two days for that but windows 8 it is okay for me.

**Comment by krishbhattacharyya** [comment]
Thanks for reply. @gaearon may be you are right but due to this reason my system will be changed in Ubuntu from next day. If I am getting chance then I will try it on another system (vista)  in future and send you the status. Thanks for your support.
