### ISSUE TITLE
ReactCSSTransitionGroup's transition*Timeout props are required but undocumented

### ISSUE THREAD

**Issue by Peeja** [facebook/react#7317]
When a `ReactCSSTransitionGroup` is used without timeout props, it [warns](https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroup.js#L28-L33):

> Warning: Failed propType: transitionLeaveTimeout wasn't supplied to ReactCSSTransitionGroup: this can cause unreliable animations and won't be supported in a future version of React. See https://fb.me/react-animation-transition-group-timeout for more information. Check the render method of `Constructor`.

for each missing timeout prop. However, that URL simply points to [the Getting Started section of the Animation page](https://facebook.github.io/react/docs/animation.html#getting-started). The code listed there does use timeout props, but nothing on the page explains what those props do or why they're necessary. In fact, the word "timeout" only appears in the names of those props in code examples.

Could we get some explanation in the docs, please?

**Comment by gaearon** [comment]
>The code listed there does use timeout props

Hmm, I think it does:

<img width="516" alt="screen shot 2016-07-20 at 15 23 18" src="https://cloud.githubusercontent.com/assets/810438/16989915/e5f53c38-4e8d-11e6-87f2-b62f0970d9aa.png">

Some line breaks would help there.
There is an entry explaining why they were added in 0.14 release notes:

<img width="717" alt="screen shot 2016-07-20 at 15 24 12" src="https://cloud.githubusercontent.com/assets/810438/16989958/0f51a47c-4e8e-11e6-927c-946a033465de.png">

(I’m not saying it’s easy to find—it’s out fault for not updating the docs to reflect that.)

Would you like to massage the doc page and send a PR?

**Comment by Peeja** [comment]
Ah, got it. Yeah, knowing how it works now, I can do that. Thanks!

**Comment by uragecz** [comment]
I am using transitionAppearTimeout, however still with this warning... any tips ?
```
<ReactCSSTransitionGroup transitionName="example" transitionAppear={true} transitionAppearTimeout={500}>
                    <Navigation {...others} />
                 </ReactCSSTransitionGroup>
```

**Comment by uragecz** [comment]
Can transitionAppearTimeout replace transitionLeaveTimeout?? If i am using
```
<ReactCSSTransitionGroup transitionName="example" transitionAppear={true} transitionAppearTimeout={500}>
                    <Navigation {...others} />
                 </ReactCSSTransitionGroup>
```
because i am still gettint error with `Failed propType: transitionLeaveTimeout wasn't` ....
