### ISSUE TITLE
Cannot use TestUtils.Simulate on a component created with TestUtils.renderIntoDocument

### ISSUE THREAD

**Issue by jacalata** [facebook/react#7331]
We have just upgraded from react 0.14.7 to 15.2.1 and some of our existing tests have begun failing due to this issue. 

Apparent cause: components created with TestUtils.renderIntoDocument do not have a tagName, and therefore TestUtils.Simulate does not recognise them as components and leaves the node null.

jsfiddle repro: http://jsfiddle.net/Jacalata/xu9L0nfo/

**Comment by gaearon** [comment]
The problem is `Simulate` methods only take DOM nodes as arguments.
So you'd need to first get a DOM node for your component, and then pass it.

For example like this: http://jsfiddle.net/2a22vL32/
