### ISSUE TITLE
Documentation - Links in documents text are wrong

### ISSUE THREAD

**Issue by dmitriy-luch** [facebook/react#7334]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
404 error
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
1) Open a page from docs like this one https://github.com/facebook/react/blob/master/docs/docs/10-addons.md
2) Click on any link like https://github.com/facebook/react/blob/master/docs/docs/animation.html
3) See 404 error page
**What is the expected behavior?**
The correct link should be https://github.com/facebook/react/blob/master/docs/docs/10.1-animation.md
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 -

The problem occurs on many doc pages since file names are changed to include numbers, I guess.

**Comment by gaearon** [comment]
Please read the documentation on the website.
http://facebook.github.io/react

You are looking at the source files so the relative links don't work as they are written against the website. It's confusing but unfortunately this is how Jekyll works.
