### ISSUE TITLE
Stop using imgur for images in blog post

### ISSUE THREAD

**Issue by zpao** [facebook/react#7337]
https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html is using imgur for image hosting. We should just put those on our site, like we have for previous posts.

While making sure we maintain control, it will also ensure that those images are served over HTTPS (which they aren't currently). We could fix that by updating the img srcs but we should probably just host them anyway.

<img width="355" alt="image" src="https://cloud.githubusercontent.com/assets/8445/17066395/c3d3c6aa-4ffb-11e6-8179-871b4f6cf699.png">

**Comment by zpao** [comment]
Actually, I'll just do this, going to fix up some other links to be https :)

**Comment by vjeux** [comment]
cc @gaearon

**Comment by gaearon** [comment]
Oh, sorry, it was 5am and by brain didn’t function well.
Won’t do this in the future.

**Comment by zpao** [comment]
Not actually a big deal short-term, just wanted to make sure we didn't lose these things :) (PS, great work on both the tool and the post!)

**Comment by vjeux** [comment]
Thanks!
