### ISSUE TITLE
z-index of interaction

### ISSUE THREAD

**Issue by mehdijjz** [facebook/react#7346]
say we have : 

```html
<div>
    <TargetComponent/>
    <Component1/>
    <Component2/>
</div>
```

if we put TargetComponent on top of other components with `position : absoloute`, it will be impossible to interact with it ! but if we change the order of implementation like :
```html
<div>
    <Component1/>
    <Component2/>
    <TargetComponent/>
</div>
```
it will come on top of other components. It's something like **z-index of interaction**! is this a problem ? or it's just the way react works ?

**Comment by syranide** [comment]
That's all browser/HTML behavior, not something React is involved with.

Also, please use GitHub issues only for React bugs/development. Use the forum/StackOverflow for general questions.
