### ISSUE TITLE
babel-node: ReactComponentTreeDevtool.js causes ReactDOMServer.renderToString to fail

### ISSUE THREAD

**Issue by ian-speers** [facebook/react#7350]
While following a server-side react tutorial, I encountered a runtime error caused by ReactComponentTreeDevtool. Specifically, the purgeDeep function seems to be problematic under certain conditions (react/lib/ReactComponentTreeDevtool.js line 47):

User Code:

<img width="258" alt="screen shot 2016-07-24 at 3 49 40 pm" src="https://cloud.githubusercontent.com/assets/19496802/17106234/73aaee92-523f-11e6-9235-64d06ffeb31d.png">

<img width="532" alt="screen shot 2016-07-24 at 3 47 01 pm" src="https://cloud.githubusercontent.com/assets/19496802/17106241/7d085fe2-523f-11e6-86ee-b1eb8615945c.png">

Stack Trace:

![screen shot 2016-07-24 at 3 41 00 pm](https://cloud.githubusercontent.com/assets/19496802/17106263/8c0a2a02-523f-11e6-94c2-342624793ecf.png)

Offending Code:

<img width="453" alt="screen shot 2016-07-25 at 8 21 17 am" src="https://cloud.githubusercontent.com/assets/19496802/17106609/cd9c230c-5240-11e6-9b21-5d6d00429dee.png">

Resolution: Adding a check for undefined childIDs before the traversal (react/lib/ReactComponentTreeDevtool.js line 47) resolves the issue (see below).

<img width="772" alt="screen shot 2016-07-25 at 8 19 57 am" src="https://cloud.githubusercontent.com/assets/19496802/17106547/9be323c4-5240-11e6-973a-a777999d9b69.png">

![screen shot 2016-07-24 at 4 02 23 pm](https://cloud.githubusercontent.com/assets/19496802/17106322/bdf6bf6c-523f-11e6-8784-1fa4e612186a.png)

Additional:
OS: OS X Yosemite (10.10.5)
Node: 4.4.7
Run on: babel-node (via babel-cli 6.11.4 )

Let me know if there's any additional information I should provide (e.g. dev dependencies). Thanks!

**Comment by gaearon** [comment]
Can you provide a minimal project reproducing this? Thanks.

**Comment by ian-speers** [comment]
[React_Issue_7350.zip](https://github.com/facebook/react/files/381890/React_Issue_7350.zip)

**Comment by gaearon** [comment]
This has been fixed in React 15.3.1.

**Comment by gaearon** [comment]
(Also, thank you very much for providing a way to reproduce.)
