### ISSUE TITLE
Respect my autocomplete values

### ISSUE THREAD

**Issue by paulwithap** [facebook/react#7352]
Bug

Currently React transforms any non-"off" value given to the `autoComplete` property to "off".

**Example:**

JSX: `<input type="password" autoComplete="new-password" placeholder="Password" required />`

Rendered HTML: `<input type="password" autocomplete="off" placeholder="Password" required />`

Besides the obvious case of "on", there are also semantic detail values that are a valid part of the spec. These values, when passed to the `autoComplete` property, should be respected and left alone.

Tested in React 15.2.0

**Comment by zpao** [comment]
What browser are you experiencing this in? We don't do anything special with that attribute so I'm guessing the browser might be "correcting" your value to something that confirms to [the spec](https://www.w3.org/TR/html5/forms.html#autofilling-form-controls:-the-autocomplete-attribute) (which indicates "on" and "off" are the only valid values).

**Comment by zpao** [comment]
Here's a test case that appears to be working as you expect in both Firefox and Chrome: https://jsfiddle.net/em1t93hv/

**Comment by paulwithap** [comment]
@zpao it appears you're right. I just realized this myself after noticing that setting `autoComplete="off"` in my JSX resulted in browser behavior that was different than `autoComplete="new-password"`. 

I guess Chrome must be accepting, then changing the semantic values for some odd reason? I think this issue can be closed.

**Comment by zpao** [comment]
Thanks for checking!

**Comment by venicehsu** [comment]
but why your doc wrote `<MyTextBox autocomplete={true} />` [https://facebook.github.io/react/docs/jsx-in-depth.html#props-default-to-true](url)
