### ISSUE TITLE
Possibility to return multiple elements from render()

### ISSUE THREAD

**Issue by xkr47** [facebook/react#7354]
*This can be seen as an extension of #7353*

I'm asking if, in the light of #5753, it would be possible to return an array with multiple elements (and maybe strings too) from `render()`. Currently it is already possible to return an array with a mix of elements & strings from a {} block in JSX. Could the same comment-wrapping method from 5573 allow for this also for render methods?

```js
// Before
<h1>Hello</h1>
{elements.map((elem) => <div>{elem}</div>)}
// After
<h1>Hello</h1>
<ComponentProducingMultipleDivs elements={elements} />
```

Motivation is that it is sometimes hard to get layout to work as expected if one has to wrap the list of elements in some other element, and the alternative is to write plain functions instead of react components to produce the expected result. It would be syntactically nice to be able to componentize multiple-output components.

**Comment by gaearon** [comment]
This is planned to be implemented eventually.
Please see #2127.
