### ISSUE TITLE
IE10-IE11 becomes unresponsive after updating <use> element inside a SVG

### ISSUE THREAD

**Issue by stream7** [facebook/react#7355]
This is a bug that can be reproduced in IE10 and 11. 

The UI will become unresponsive after the first update of the `<use>` element.

Visit http://codepen.io/stream7/pen/bZKVGW and click/toggle the button. It works fine in Chrome/Firefox but in IE the browser becomes unresponsive after the first click. There is no error thrown. 

I was able to reproduce it in all 15.x.x versions and in 0.14.8 on Windows 7 IE10-11 (modern.ie editions)

**Comment by zpao** [comment]
Can you reproduce when doing the same thing without React? I think http://codepen.io/anon/pen/kXpXQm is the same (I think we should just be doing a single `setAttributeNS` call).

**Comment by stream7** [comment]
@zpao you are totally right. One more reason to love IE :trollface: 
Thanks for the quick reply.

**Comment by phun-ky** [comment]
Why is this closed? No fix is given, no workaround is given, no response to validate a closed state. This is still an issue.

**Comment by stream7** [comment]
@phun-ky it's closed because it's not a React bug. It's an IE bug.

The fix is this:

```
svg use {
   pointer-events: none;
}
```

See http://stackoverflow.com/questions/30653533/ie-11-crashes-when-using-dynamic-svg-elements

**Comment by phun-ky** [comment]
@stream7 thanks for the quick reply :)
