### ISSUE TITLE
Handle externally injected elements in replaceDelimitedText?

### ISSUE THREAD

**Issue by syranide** [facebook/react#7363]
https://github.com/facebook/react/blob/ba9b985406ff56c2dea192b119328b6096895097/src/renderers/dom/client/utils/DOMChildrenOperations.js#L104

Mostly preemptive because we've talked about it before. Right now, if you render `<!-- react-text -->foobar<!-- /react-text -->` and an external tool bolds `foo` (like `<!-- react-text --><b>foo</b>bar<!-- /react-text -->`) then the entire string will be bolded when updated by React `<!-- react-text --><b>foobar</b><!-- /react-text -->`. Because only the first element is kept and `textContent` is called on it. So I would say it makes more sense to throw all elements away in that case and start from scratch.

Should we perhaps check the node type and also throw it away if it isn't a text-node?

**Comment by gaearon** [comment]
Doesn't seem like this happens in 16.
