### ISSUE TITLE
I have some questions about the movies in  'React Examples'，could you help me???

### ISSUE THREAD

**Issue by starrycheng** [facebook/react#7366]
'use strict';

var ReactNative = require('react-native');
var {
  StyleSheet,
} = ReactNative;

var MAX_VALUE = 200;

import type { StyleObj } from 'StyleSheetTypes';

Question 1:
What is the 'StyleSheetTypes'???    where is it come from???

Question 2:
What is the 'StyleObj'???

function getStyleFromScore(score: number): StyleObj {
  if (score < 0) {
    return styles.noScore;
  }

  var normalizedScore = Math.round((score / 100) * MAX_VALUE);
  return {
    color: 'rgb(' +
      (MAX_VALUE - normalizedScore) + ', ' +
      normalizedScore + ', ' +
      0 +
    ')'
  };
}

var styles = StyleSheet.create({
  noScore: {
    color: '#999999',
  },
});

module.exports = getStyleFromScore;

Could you help me???  Thank you very much...

**Comment by ronak301** [comment]
what help do u need ?

**Comment by zpao** [comment]
You might want to bring this up in the react native repo - this is just react here, not all one project at this point.
