### ISSUE TITLE
Data in a keyed list of `<options>` in a `<select>` being mangled unpredictably

### ISSUE THREAD

**Issue by dylanpyle** [facebook/react#7370]
I'm going to close this issue immediately, since I don't have a reproducible
test case. We've hit this issue exactly one that I know of, but the code is so
simple that we suspect a React bug may be the cause. I'm hoping that documenting
this might help someone else who stumbles across it in the future.

---

**Do you want to request a *feature* or report a *bug*?**

Report a bug

**Reduced code sample**

```javascript
const STATES = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  ... etc ...
}

class extends React.Component {
  render() {
    return (
      <section>
        {this.renderRegionFields()}
      </section>
    );
  }

  renderRegionFields() {
    return (
      <select>
        <option disabled value=''>Country</option>
        {Object.keys(STATES).map(this.renderRegionOptions.bind(this))}
      </select>
    );
  }

  renderRegionOptions(key) {
    const abbreviation = STATES[key];

    return (
      <option
        key={abbreviation}
        value={abbreviation}
      >
        {abbreviation}
      </option>
    );
  }
}
```
We're not referring to the `STATES` module anywhere else in the application (i.e. we're pretty certain it's not being mutated accidentally).

**What is the expected behavior?**

The list of states is the list of two-letter state abbreviations in order (AL, AK, AZ...)

**What is the current behavior?**

The list of states is being intermixed with some other unknown data. It ends up looking something like this:

![](https://cloudup.com/cJpvH_6DJEI+)

Notably, we don't have the strings "BUT", "FROM" (in all-caps) anywhere in our
codebase at all. Then again, it doesn't look like React does either...

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.1.0, Chrome 51.0.2704.103, OSX

**Comment by zpao** [comment]
Definitely let us know if you hit it again. Best guess is perhaps something overriding `Object.keys`? Or something else modifying the DOM/`STATES` object (it's obviously replacing values, not injecting). Good luck, but I agree, this doesn't seem like React...
