### ISSUE TITLE
react automatically remove vendor prefix in inline style

### ISSUE THREAD

**Issue by littlee** [facebook/react#7372]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
http://stackoverflow.com/questions/38630403/react-automatically-remove-vendor-prefix-in-inline-style

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://jsfiddle.net/mv0dghf1/

**What is the expected behavior?**
react can render css vendor prefix

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I tried v0.14.x and v0.15.x, the result is the same.

**Comment by syranide** [comment]
```
> document.body.style.webkitTransform = "rotate(1deg)";

> console.log(document.body);
< <body style=​"transform:​ rotate(1deg)​;​">​…​</body>​

> console.log(document.body.style.webkitTransform);
< "rotate(1deg)"

> console.log(document.body.style.transform);
< "rotate(1deg)"
``` 
That's just how modern Chrome behaves.

**Comment by sophister** [comment]
same problem, using `React@16.3.2 and ReacDOM@16.3.2`, I set style to element with object like this

```javascript
const style = {
      WebkitTransition: 'all',
      WebkitTransform: 'scale(1.5)',
      msTransform: 'scale(1.5)',
      transform: 'scale(1.5)'
    };

<h2 style={style}>parent</h2>
```

But style in real dom is `transition: all 0s ease 0s; transform: scale(1.5);`
