### ISSUE TITLE
IE 11 bug with svg <use />

### ISSUE THREAD

**Issue by 6graNik** [facebook/react#7375]
Hi, we reccently updated our project to  React v15.2.1 and had some issue's with svg's in IE11.

So we use svg sprites and get icon's like this: 

`<svg>
          <use xlinkHref={svgIconLink(someSvg')}></use>
        </svg>
`
And we use svg4evrybody  for cross-browser support.

After updaiting React started to throug exception's on IE 11. 
`invariant violation couldnt find element with ID X` 

X - being reactid of `<use />`.

As I  understand exception fires because of svg4evrybody plugin, wich replacing <use /> with inner polyfill after page loads. 

And react can't find `<use />` because there is no use and through exeption.

So the only workaround I came up with: 

`
const use = '<use xlink:href=${svgIconLink('someIcon')}></use>';
<svg dangerouslySetInnerHTML={{__html: use}}></svg>`

So React dosen't include `<use />` in our virtual DOM and can't complaint about it.

Is there any better way to do what? Because in my case I have to rewrite a whole lot of svg icons...

**Comment by syranide** [comment]
If you replace nodes owned by React (which is a bad idea), which the polyfill does, then you must make absolutely sure that you do not make React think it or any of its siblings has updated or it will crash (it's still a bad idea to rely on it).

So either the polyfill needs to be made React-compatible or you'll need to do the `dangerouslySetInnerHTML` way that you show. You can use `ReactDOMServer.renderToStaticMarkup` if you still want to author them in React, but they will not be "dynamic".
