### ISSUE TITLE
JSX shorthand property syntax

### ISSUE THREAD

**Issue by vaukalak** [facebook/react#7376]
Hello, 
I've searched for similar issues, but didn't found one, sorry if this is a duplicate.
Let say I have following component:

```
const Window = ({title, text, theme}) => (
  <View>
    <Header title={title} theme={theme}/>
    <Content text={text} theme={theme}/>
  </View>;
);
```

The code for forwarding properties could be less verbose with shortcut syntax: 

```
const Window = ({title, text, theme}) => (
  <View>
    <Header {title} {theme}/>
    <Content {text} {theme}/>
  </View>;
);
```

I'm aware about spread operator, but it's not comfortable sometime. For example if I don't want to revalidate `Header` when `text` property is changed.

**Comment by zpao** [comment]
I appreciate the idea. However I think at this point we're going to opt for explicitness here. There's some further discussion in https://github.com/facebook/jsx/issues/23 (where we maintain the JSX "spec"). Since it exists over there, I'm going to close out here.
