### ISSUE TITLE
Investigate why CI failed to add a file to gh-pages

### ISSUE THREAD

**Issue by zpao** [facebook/react#7378]
For some reason https://travis-ci.org/facebook/react/jobs/148403092 failed to detect and commit a new file. Presumably the dirty-state detection failed. It didn't happen with the previous build but that also had changed files, not just added new ones - maybe that helped trigger.

We've only done a couple builds on Jekyll 3 & the new Travis container so could be related.

**Comment by zpao** [comment]
#7380 went off without a hitch but it wasn't just a new file (actually a move but git so rm & add). I'll keep an eye on this the next time we add a new page to the docs.

**Comment by aweary** [comment]
@zpao I don't think you're investigating this anymore 😄  I'll close this out
