### ISSUE TITLE
Add Text and View components

### ISSUE THREAD

**Issue by steida** [facebook/react#7382]
With default rendering into span and div in the browser. This small change can enable universal React components. `react-intl` badly need it :-)

The next step is to port StyleSheet to the browser and allow style to accept it.

That's all we need for the start.

**Comment by zpao** [comment]
We think this is a great idea and it's definitely something we're thinking about :) For now I recommend using https://github.com/necolas/react-native-web. I'm going to close out but it's on our radar.

**Comment by steida** [comment]
Remember to solve different whitespace handling. I was surprised that React Native preserves whitespaces. Thank you :-)

**Comment by steida** [comment]
Related to https://github.com/yahoo/react-intl/issues/600
