### ISSUE TITLE
PureComponent breaks hot reload

### ISSUE THREAD

**Issue by coodoo** [facebook/react#7388]
Seems switching from `Component` to `PureComponent` breaks hot reloading, error messages below, it can be reliably reproduced in any project (simply switching back to `Component` will fix the problem).

```
process-update.js:81 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.logUpdates @ process-update.js:81applyCallback @ process-update.js:49hotApply @ bootstrap fccae4c…:531cb @ process-update.js:52hotUpdateDownloaded @ bootstrap fccae4c…:311hotAddUpdateChunk @ bootstrap fccae4c…:283webpackHotUpdateCallback @ bootstrap fccae4c…:4(anonymous function) @ 0.c30c5b2….hot-update.js:1
process-update.js:89 [HMR]  - ./shared/components/Cart.jsx
```

**Comment by syranide** [comment]
IIRC you need to tell RHL which base classes are for React components. RHL should also be updated to include it by default.

**Comment by gaearon** [comment]
Please file this in the appropriate repo, not in React. Hot reloading is an experimental feature provided by third party plugins, and React is not officially providing it. 

(The repo depends on what tool you use for hot reloading but unfortunately you haven't specified any details so I can't point you to the right one.)

**Comment by gaearon** [comment]
>IIRC you need to tell RHL which base classes are for React components

AFAIK this is not correct for RHL. (It is for React Transform but it has been deprecated for a while and I don't intend to update it.)

**Comment by steida** [comment]
@gaearon It also broke React Native hot reloading.
