### ISSUE TITLE
Reusable Components: we probably are doing it wrong

### ISSUE THREAD

**Issue by hnordt** [facebook/react#7391]
I have been using React for business projects since 2015. I built 2 large, 1 medium and many small apps.

One of my dreams is to create reusable components that can be shared across projects and still support highly customization even if the CSS framework changes; I mean, I want to support Bootstrap, Foundation, Semantic UI, raw styles and other frameworks that I don't know.

To do it I discovered that we should be highly explicit and shouldn't make styling assumptions. For example:

```js
// BAD
function Button({ className, type, style, children, ...other }) {
  return (
    <button {...other} className={`btn btn-${type} ${className || ''}`} style={style}>
      {children}
    </button>
  )
}
```

PS: I'm not trying to say that my approach is the best and others are bad, I'm just sharing how I fixed my problem, so others can try the same approach and see if it's a fit for other projects.

**What's the problem?**

1. We are passing `other`; if we are building a reusable `Button` API we should create a formal API, `other` is too general, it's the same as defining a `Person` database model and allowing the consumer to pass anything; it's cool for small projects or prototypes, but if it's a reusable component, you need to make it more formal.
2. We are assuming that Bootstrap will be used when we pass `btn` and `btn-x` as classes. What about Foundation? What about Semantic UI? What about users that don't use a CSS framework at all? If it's a reusable component, it should support many styling frameworks or techniques, because every project is different.

**How to solve?**

1. Make a formal API, if it's too early to create a formal API, then your reusable component shouldn't be `>= v1`, I mean, you are still experimenting and looking for a good API.
2. Your reusable component shouldn't define classes or styles at all, except for styles that you know that will never change for the type of component you are building (.e.g. a dropdown or autocomplete popup always need some styles like `position`, `top`, `left`, etc, in this case it's not a problem, because these styles define how your component should behave and will never change if we change our CSS framework or aesthetics styles).

**A Real World Example**

```js
// When you pass props like `getClassName` and `getStyle`
// you delegate the job to the consumer because the consumer
// is the one that knows your app domain logic/styles
//
// Doing that way makes your reusable code a lot cleaner and easier to reason about
// The job of your reusable code is just define a formal API
// A formal API is an API that you know that is really good and you can use it
// with confidence
//
// It's like the Redux concept: actions and reducers implementations are your job
// Redux just tell you to use actions and reducers because it's the formal API
// and they know that's really good
//
// For a `Button` we know that it always have some types, so we formalize it
// then the consumer can use it to apply specific styles and classes
//
function ReusableButton({ type, getClassName, getStyle, children }) {
  return (
    <button className={getClassName(type)} style={getStyle(type)}>
      {children}
    </button>
  )
}

ReusableButton.propTypes = {
  type: PropTypes.oneOf(['primary', 'secondary', 'success', 'warning', 'danger']).isRequired,
  getClassName: PropTypes.func,
  getStyle: PropTypes.func,
  children: PropTypes.node.isRequired
}

ReusableButton.defaultProps = {
  getClassName: () => null,
  getStyle: () => null
}

// MyAppButton.js

// If in the future we need to change our CSS framework
// Probably we'll need to change only this function
function getClassName(type) {
  return `btn btn-${type}`;
}

function getStyle(type) {
  if (type === 'danger') {
    return { fontSize: 20 };
  }
  return null;
}

function MyAppButton({ type, children }) {
  return (
    <ReusableButton type={type} getClassName={getClassName} getStyle={getStyle}>
      {children}
    </ReusableButton>
  )
}
```

**Advantages**

As it's a simple example, you probably won't see any advantages. But I'll try to list some:

1. Creating a formal API helps you thinking about how to apply styles in the next project, as `Button` defines some types that every app needs, you don't need to think about possible styles a `Button` have, you just use it
2. For every project you'll use the same API, when you back to the project weeks or months later, you'll know how to use it
3. Pulling fixes is easy as `npm update`
4. Upgrading is easy as `npm install my-reusable-component@latest` and then updating just one file
5. You can build a platform of `Buttons` on top of `ReusableButton`, e.g., `BootstrapButton`, `FoundationButton`, `SemanticButton`, etc; instead trying to cover every use case inside a `Button`, you use the power of composability

**Comment by hnordt** [comment]
@gaearon it's a good example that the new warning about unknown props are really good.

**Comment by Aweary** [comment]
@hnordt I'd recommend flushing out your ideas/recommendations on reusable components in a blog post or something, as this repo is usually meant for tracking actual issues with React.

I'll say, though, that I think developing for reusability should be done carefully and with certain constraints; the more generalized a component the less useful (or powerful) it becomes in a lot of cases. APIs like `getClassName` and `getStyle` seem superficially more flexible, but they don't really offer (in this example at least) any advantage over just calculating `style` and `className` before passing it to the `ReusableButton` component.

**Comment by hnordt** [comment]
@Aweary in this simple example it doesn't shows any real advantages by just looking at it. But I'll try to list some:

1. Creating a formal API helps you thinking about how to apply styles in the next project, as `Button` defines some types that every app needs, you don't need to think about possible styles a `Button` have, you just use it
2. For every project you'll use the same API, when you back to the project weeks or month later, you'll know how to use it; pulling fixes is easy as `npm update`

**Comment by Aweary** [comment]
I would counter by saying that React already provides a standardized, formal API with `className` and `style`, so it's not ideal to ask users to provide a non-standard getter that returns values they could calculate themselves in their `render` method. 

If the component had to generate `className` or `styles` based on data that wasn't available when it's rendered (here it just depends on `type` which is passed down via props alongside your getters, so obviously it's available in the parent component) then methods like these might make some sense.

Really though, this isn't the appropriate venue discussing best practices, so I'm not keen on continuing the discussion here, maybe post something on Medium or somewhere so the community can discuss it elsewhere!

**Comment by hnordt** [comment]
I understand what you said @Aweary, the problem is that for real world business apps developers do crazy things with `className` and `style`. React is about creating formal APIs in my opinion, but it's just my approach to use React. I respect your approach too.

I'll close the issue and start the discussion on a blog post as suggested. Thank you!

**Comment by syranide** [comment]
@hnordt I think you're overthinking it without thinking outside-the-box/html so to speak. *All styling* is an implementation detail and should in a perfect world not be exposed through props, no css-classes, no css-styles, etc.

IMHO, the solution here is to realize that the hypothetical `<button>` shouldn't render anything at all, it should implement the functionality/behavior that defines buttons as most commonly used (say, hover state, disabled state, click handling, etc) and then pass this information down to a separate component that only deals with drawing, a hypothetical `MyRedButton`. This way `<button>` makes no assumptions on how it should be rendered and you're free to design it however you wish... then you'll often find yourself drawing buttons that look very much alike so you'll probably implement a `MyStandardButton` which takes a bunch of props which may determine its color, padding and so on. Then you may have a `MyDialogButton` which is rendered differently but probably still relies on the same `<button>` implementation for the logic.

**Comment by hnordt** [comment]
@syranide but that's the idea. Your `<button>` is my `<ReusableButton>`.

**Comment by syranide** [comment]
Yeah, but my point is that it shouldn't have a concept of styles/classnames/etc. It exposes the underlying ui framework and makes assumptions on how a button should look. IMHO and my point is that it should hypothetically just take a single function "draw" (think: component), which draws a button with a given label. So the draw-function can render a button with any imagineable style and behavior for any ui framework, not just html.

Or perhaps I'm misunderstanding your intentions.

**Comment by hnordt** [comment]
My point is to make the `Button` API very explicitly on what it supports. I mean, a button of type `primary` is styled in a different way than one with a type of `danger`. So the `Button` defines that it should accept a enum of types, and the styling is delegated to the consumer, which knows your app domain logic and needs (`MyAwesomeAppButton`). `Button` will be published to npm and consumed by `MyAwesomeAppButton`.
