### ISSUE TITLE
react-dom package no longer listed in npm registry

### ISSUE THREAD

**Issue by Aweary** [facebook/react#7398]
https://www.npmjs.com/package/react-dom

This page 404s, and `react-dom` does not show up via search on npmjs.com either. The package is still linked from [@zpao's npm profile](@zpao's npm profile).

Is this an npm issue?

**Comment by zpao** [comment]
Yea, it's a known npm issue. They're working on it 😀 (https://twitter.com/ceejbot/status/760214959095582720)

We can leave this open though so we have somewhere to point in case it comes up again before it's resolved.

**Comment by ashleelynn1202** [comment]
I'm just trying to figure out to a adjust and figure out how to do all of this

**Comment by zpao** [comment]
Looks like we're all good.
