### ISSUE TITLE
[Question] How to update context from the descendant component

### ISSUE THREAD

**Issue by anianj** [facebook/react#7399]
I want to use context to pass down some data from parent to some descendant components.

But i also need to update that context from the descendant component(like when clicking on descendant component).

I find there is no document to tell how to do this. so i am wondering that if this is a anti-pattern?

**Comment by gaearon** [comment]
We encourage you to avoid using context in the app code. It’s advanced feature and not fully supported. What you’re trying to do seems like an anti-pattern.

I think this guide describes what you’re trying to do: https://facebook.github.io/react/docs/thinking-in-react.html. I hope this helps!

In general, we encourage you to post usage questions on StackOverflow. We use the issue tracker for tracking bugs in React, not for usage questions. Cheers!
