### ISSUE TITLE
I can't fire onTouchEnd and onTouchCancel events.

### ISSUE THREAD

**Issue by AlexVasilenko** [facebook/react#7404]
Hello! I'm trying to create horizontal scroll and having an issue. I create two buttons and for each button I add events onTouchStart, onTouchEnd and onTouchCancel. When event onTouchStart triggers, I change margin for container which contains all scrollable elements. And onTouchEnd and onTouchCancel need to stop this scroll. But these events don't trigger and I can't stop scroll. In which cases events may not trigger? I use chrome v40, OS Ubuntu 14.01, react 15.0.2. I tested it in Chrome device mode.

This is my code: 

```js
<button
  ref="scrollLeft"
  onMouseDown={this.scrollLeft}
  onTouchStart={this.scrollLeft}
  onMouseLeave={this.stopLeftScroll}
  onTouchEnd={this.stopLeftScroll}
  onTouchCancel={this.stopLeftScroll}
  className={cx(
    'left',
    styles.scrollButton,
    styles.leftScrollBut,
    {
      [styles.enable]: shouldRenderArrows,
      [styles.disable]: !shouldRenderArrows,
    }
  )}
>
</button>
```

**Comment by ericnakagawa** [comment]
Can you send us a code snippet?
