### ISSUE TITLE
Doc too confusing with {...}, should rather be {/*...*/}

### ISSUE THREAD

**Issue by pdavidow** [facebook/react#7413]
https://facebook.github.io/react/docs/jsx-in-depth.html#namespaced-components
(and wherever else applicable)
````
var MyFormComponent = React.createClass({ ... });

MyFormComponent.Row = React.createClass({ ... });
MyFormComponent.Label = React.createClass({ ... });
MyFormComponent.Input = React.createClass({ ... });
````
Are the three dots some type of Spread operator? No! It's just pseudocode for a placeholder (I think). So in order to help the confused reader, use comments instead (no more pseudocode):
````
var MyFormComponent = React.createClass({/*...*/});

MyFormComponent.Row = React.createClass({/*...*/});
MyFormComponent.Label = React.createClass({/*...*/});
MyFormComponent.Input = React.createClass({/*...*/});
````

**Comment by gaearon** [comment]
I’ll merge a PR fixing this.

**Comment by gaearon** [comment]
We dropped this section completely in new docs.
