### ISSUE TITLE
Missing polyfill in IE with 15.2.3

### ISSUE THREAD

**Issue by jwentz-boc** [facebook/react#7423]
Using 15.2.3 and getting this error in IE11:

```
TypeError: Object doesn't support property or method 'from' at _toConsumableArray (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:28088:170) at renderElement (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:28163:10) at render (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:28128:10) at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:14485:6) at ReactCompositeComponentMixin._renderValidatedComponent (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:14511:8) at ReactCompositeComponentMixin.performInitialMount (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:14053:8) at ReactCompositeComponentMixin.mountComponent (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:13941:8) at ReactReconciler.mountComponent (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:6940:6) at ReactMultiChild.Mixin.mountChildren (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:13086:12) at ReactDOMComponent.Mixin._createInitialChildren (https://hcp.betteroutcomes.com/static/patient/javascripts/bundle.js:10117:10)
```
Offending line:
```
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }
```

Adding 
```
require("babel-polyfill")
```
(as suggested here http://stackoverflow.com/questions/36622505/typescript-array-from-in-ie11) seems to fix the problem.

I believe this issue was introduced in moving from 0.14.3 to 15.2.3 but I have not reverted to the older React to verify this.

Shouldn't React itself include this polyfill ?

**Comment by zpao** [comment]
A few things…

1. We don't have a React v15.2.3 - perhaps you meant 15.2.1 or 15.3.0?
2. Our generated code doesn't actually contain a `_toConsumableArray` function (neither 15.2.1 nor 15.3.0), so I think this must be coming from something in your own code or from what compiles your code.

I'm going to close out as a result but if it turns out to actually be a problem with React, we can reopen. I encourage you to open a debugger and work up the stack to see who is calling `_toConsumableArray`.

**Comment by jwentz-boc** [comment]
Sorry, of course I meant v15.2.1.

Further poking suggests that this is an issue from Babel es2015 transpilation: 

http://phabricator.babeljs.io/T7518

Apologies for mis-reading it as a React issue.

**Comment by zpao** [comment]
No worries. We transpile with Babel so it wasn't out of the realm of possibilities :)
