### ISSUE TITLE
Not updating style attribute for radial gradient in Chrome and Safari

### ISSUE THREAD

**Issue by okonet** [facebook/react#7425]
**Do you want to request a _feature_ or report a _bug_?**

🐛

**What is the current behavior?**

`style` attribute with `radial-gradient` doesn't get updated when changing `extent-keyword` (see https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient). It does update for any other value, though.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Demo: https://esnextb.in/?gist=d3b0b9c241975095b895108b59f8f213
1. Open in Chrome or Safari
2. Click on the "closest-side" button. CSS string changes but gradient remain the same.
3. Click on the "Update Position" button. It will update `style` attribute of the DOM node for position _and_ extent keyword.

Changing the value directly via Developer Tools does update it, so it must be the React-related bug.

See how it update the gradient when I change the position of it:

![2016-08-04 at 15 25](https://cloud.githubusercontent.com/assets/11071/17403442/0265ef86-5a58-11e6-8c91-4efaa09d6089.gif)

**What is the expected behavior?**

Try same steps in Firefox to see a proper behavior.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Reproducible in 15.1.0 and 15.3.0

**Comment by zpao** [comment]
Can you write a simplified version of this using plain JS and see if you have the same problem? (create a div, set node.style.backgroundImage and then set it again to a new value). I suspect this might be a browser-specific issue that we can't do anything about. Editing the style in the devtools isn't the same as doing it from userland so it's important to test that as well. I also don't see the inline style actually changing in Chrome (the text content is updating but the inline style value isn't)

**Comment by okonet** [comment]
Yeah, I was also wondering if it's a case. I'll create a minimal example to test with vanilla DOM API.

**Comment by gaearon** [comment]
Closing as stale.
