### ISSUE TITLE
ReactCSSTransitionGroup not working in ie 11 with webpack

### ISSUE THREAD

**Issue by jaewon1219** [facebook/react#7429]
**Do you want to request a _feature_ or report a _bug_?**
bug
**What is the current behavior?**
transitionAppear not working in ie 11 with webpack
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

> **https://jsfiddle.net/nrkhsptu/**

**What is the expected behavior?**
transition appear in ie 11
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "^15.3.0",
"react-addons-css-transition-group": "^15.3.0",
browser - ie 11
os - window 7

**Comment by gaearon** [comment]
We're not maintaining TransitionGroup anymore in this repo.
If you have issues please file them against https://github.com/reactjs/react-transition-group.
