### ISSUE TITLE
`HTMLDOMPropertyConfig` contains non-standard `icon` property

### ISSUE THREAD

**Issue by smockle** [facebook/react#7430]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
The `HTMLDOMPropertyConfig` object [includes an `icon` property](https://github.com/facebook/react/blob/cccef3c68310df3bd611df2a7b98a530645c67c0/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L85) in a section title `Standard Properties`, but `icon` isn’t an attribute supported by any standard HTML element.

`icon` is not included in the HTML4 or HTML5 specs:
[List of HTML4 attributes](https://www.w3.org/TR/html4/index/attributes.html)
[List of HTML5 attributes](https://www.w3.org/TR/html5/index.html#attributes-1)

Mozilla Developer Network includes `icon` in its [list of attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes), but specifies the only element to use `icon` is the [obsolete `<command>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/command). `<command>` isn’t supported in [any desktop or mobile browser](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/command#Browser_compatibility).

**What is the expected behavior?**
The `icon` property might be better placed in the section titled [`Non-standard Properties`](https://github.com/facebook/react/blob/cccef3c68310df3bd611df2a7b98a530645c67c0/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L174-L202), or removed altogether. The [documentation](https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes) for HTML attributes could omit `icon` too.

I encountered this issue when working with TypeScript, and I opened an issue about the React type definition at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10467. Because React itself includes `icon`, custom interfaces which extend [DefinitelyTyped’s `React.HTMLAttributes`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/613673de3672114c562fdf9f142bfeefc29173c9/react/react.d.ts#L1968) cannot include a non-string `icon` property.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`icon` was added in a React 0.4.0 alpha in 2013: https://github.com/facebook/react/commit/203dba271b6128f03c99b1ce2f573a316adb4e4e. The commit message mentions `mostly this was to better support some HTML5 stuff`—it’s possible `icon` was part of a draft of the HTML5 standard at the time, but was omitted in the final spec.

**Comment by zpao** [comment]
Thanks for spotting this. We should probably remove it but it'll have be done in a major version.

**Comment by nhunzaker** [comment]
This would become moot if already removing the whitelist, right?

**Comment by zpao** [comment]
Correct, just not clear exactly when that happens so it would be fine to take a smaller change like this first. Removing the whitelist would also likely be a major version change.

**Comment by smockle** [comment]
Thanks for taking a look at this! I’d be happy to open a PR.

From the [contribute](https://github.com/facebook/react#contribute) section of the README, it looks like I’d just need to remove the line, ensure tests pass & linter output is clean, then submit the PR? (I want to make sure I’m not missing a version or changelog step.)

**Comment by Aweary** [comment]
@smockle that's about all it takes. People don't usually update all the localizations, but since this should be easy to update in all languages it would be great if you could do that 👍

**Comment by zpao** [comment]
You can actually leave the docs part of the change out. We usually just generate those manually around releases (makes it a bit easier to batch so line lengths are reasonable)

**Comment by Aweary** [comment]
Oh, good to know, didn't realize they were generated 👍

**Comment by smockle** [comment]
Thanks! I just submitted PR https://github.com/facebook/react/pull/7508 to fix this. Originally the PR updated the docs, but given [this comment](https://github.com/facebook/react/issues/7430#issuecomment-239927253) I’ve removed that commit. All tests pass, and there are no linter errors.
