### ISSUE TITLE
How to import some addons from react-with-addons

### ISSUE THREAD

**Issue by WhatAKitty** [facebook/react#7437]
I want to require react/lib/ReactMount and react/lib/ReactInputSelection from precompiled reactjs.
But I got none.

**Comment by keyanzhang** [comment]
Could you describe more about your use case? Usually we discourage requiring library internals since they are not public API and shouldn't be relied on.

**Comment by WhatAKitty** [comment]
I want get react from bundle.

**Comment by zpao** [comment]
Those are internal APIs that we don't expose on the browser bundle intentionally. If you want to use them it is at your own risk and you must use the npm package and bundle it yourself.

**Comment by WhatAKitty** [comment]
@zpao Ok, I get.
