### ISSUE TITLE
Feature Request:  Add nested object support to LinkedStateMixin.linkState

### ISSUE THREAD

**Issue by fingermark** [facebook/react#744]
My first attempt of using `linkState` was on a nested object:  `this.state.a.b.c`.  I tried `<input type="text" valueLink={this.linkState('a.b.c')} />`, but noticed this was not updating `this.state.a.b.c`.  I can see why in the implementation.  Is there a way to enhance `linkState` to support nested objects without using eval (if that's an issue)?  I see one solution on StackOverflow:  http://stackoverflow.com/questions/18571858/alternatives-to-eval-in-javascript-nested-objects

Another solution would be something like:  `{this.linkState('c', this.state.a.b)}`

**Comment by mrlamroger** [comment]
I have a convoluted solution if anyone else ever wants to hack something together.

```
handleChange: function(item_prop_key, event) {
    function assign(obj, keyPath, value) {
      lastKeyIndex = keyPath.length-1;
      for (var i = 0; i < lastKeyIndex; ++ i) {
        key = keyPath[i];
        if (!(key in obj))
          obj[key] = {}
        obj = obj[key];
      }
      obj[keyPath[lastKeyIndex]] = value;
    }
    
    item_prop_array = item_prop_key.split(".");
    item_prop_array.unshift("item");

    var item_prop = {};
    assign(item_prop, item_prop_array, { $set: event.target.value });
    var newState = React.addons.update(this.state, item_prop);
    this.setState(newState);
  },
```

```
 <select onChange={this.handleChange.bind(this, 'gitConfig.deployFrom.custom.repo')}>
```

This assumes your state has an `item` object and it's something like this:
```
 var item = {
      config: {
        deployFrom: {
          defaults: true,
          custom: {
            enabled: false,
            repo: null,
            revision: null
          }
        }
      },
````

**Comment by idolize** [comment]
FYI, if you are using [Immutable](https://github.com/facebook/immutable-js) objects in your React components, I created the following npm package to give ReactLink support for binding to nested properties: [reactlink-immutable](https://www.npmjs.com/package/reactlink-immutable)

**Comment by a-x-** [comment]
:+1:

**Comment by jimfb** [comment]
As per #2302 we're probably dropping ReactLink in controlled components. The LinkedState mixin really isn't used much, and even less so now that people are moving towards ES6 classes. Also there have been no replies on this thread, which indicates a lack of interest in this topic. Since LinkedState appears to be on its way out, my guess is that we won't invest a lot of effort in enhancing the mixin and it is mostly legacy at this point. If you find it useful, feel free to create your own LinkedState mixin for your apps and/or publish it for others to use.

**Comment by monarchjhaveri** [comment]
Apologies for opening this thread again, please see download stats on attached NPM page. LinkedStateMixin seems to be quite popular. Are you still planning on deprecating this mixin?
https://www.npmjs.com/package/react-addons-linked-state-mixin

**Comment by spicyj** [comment]
Yes, I think so. It is not hard to build your own component with the same behavior and we'll be sure to explain how to ease the migration.
