### ISSUE TITLE
Feature request: change the default shouldComponentUpdate to shallowCompare

### ISSUE THREAD

**Issue by caub** [facebook/react#7443]
```
shouldComponentUpdate(p, s){
  return shallowCompare(this, p, s);
}
```
I understand it's not backward-compatible, but I guess most people use this pure component approach in the majority of their components

**Comment by caub** [comment]
hmm, just found out about `React.PureComponent` it may answer this

**Comment by zpao** [comment]
Thanks for your request. We won't be changing the default here but we've been considering alternatives. Part of the outcome of those considerations was to introduce PureComponent and there may be more in the future.
