### ISSUE TITLE
Inline Style including !important are ignored

### ISSUE THREAD

**Issue by Laura1590** [facebook/react#7459]
If you set a style `backgroundColor: red` it works as expected but `backgroundColor: red !important` will be ignored just like in this example https://jsfiddle.net/hjwLjr6j/

**Comment by ryanbarr** [comment]
Open issue #1881 explains why this does not work.

**Comment by zpao** [comment]
As mentioned we are tracking this. Thanks for chiming in and feel free to subscribe to that other issue.

**Comment by Laura1590** [comment]
Great! Thanks for your help.
