### ISSUE TITLE
Bug with embedded slides/iframe

### ISSUE THREAD

**Issue by MichaelGofron** [facebook/react#7467]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Google slides does not enter full screen mode when the allowfullscreen attribute is set to a truthy value

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://jsfiddle.net/MichaelGofron/vjmw2cp3/1/

**What is the expected behavior?**
I expect the slides to display full screen

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am trying this in chrome and firefox. I am using the latest jsfiddle available react version and in my application react 15.1.0

**Comment by Aweary** [comment]
Make sure you're using the correct attribute names, it should be `allowFullScreen`, not `allowfullscreen`. If you check the console you should see an error mentioning this.

Also note that this won't work in JSFiddle, even if you just use plain HTML: https://jsfiddle.net/qwrf1gnu/ because JSFiddle already renders the output in an `iframe`.

**Comment by MichaelGofron** [comment]
Ah yes I just figured that out. I was wondering because in the mozilla documentation seems to indicate that it is all lower case: https://developer.mozilla.org/en/docs/Web/HTML/Element/iframe.

It appears that react uses all camelcase names for the attributes. Is there a website with html attributes in react documentation?

**Comment by Aweary** [comment]
React uses the JavaScript syntax for accessing attributes, which are typically camel-case. See https://facebook.github.io/react/docs/tags-and-attributes.html for a list of the attributes supported!

**Comment by MichaelGofron** [comment]
Excellent that's exactly what I was looking for!
