### ISSUE TITLE
Unable to run Babel code without serving HTTP file source file

### ISSUE THREAD

**Issue by syedfahad** [facebook/react#7470]
I am new to `reactjs` and trying to install `babel` to run `babel code` without serving HTTP file. By following the [Package Manager][1] I have installed it with `browserify` as:

    $ npm install --save react react-dom babelify babel-preset-react
    $ browserify -t [ babelify ] main.js -o bundle.js

After it I created the file `.babelrc` in the same root directory with following code 

    { "presets": ["react"] }

And removed the HTTP `babel-core` source file as:

    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>React Tutorial</title>
        <script src="build/react.js"></script>
        <script src="build/react-dom.js"></script>
        
      </head>
      <body>
        <div id="content"></div>
        <script type="text/babel">
          ReactDOM.render(
            <h1>Hello, world!</h1>,
            document.getElementById('content')
          );
        </script>
      </body>
    </html>

but when I access it from `http://localhost/react/` this does't work. I have very trouble Please Help me to solve it.

Thank You in advance...

  [1]: https://facebook.github.io/react/docs/package-management.html

**Comment by zpao** [comment]
You can't do `<script type="text/babel">` without something that works to parse and transform that. If you want to use React & transform jsx in that case, you'll need to build a bundle (which it appears you are doing) and add a script tag referencing that bundle.
