### ISSUE TITLE
In IE11 an input with type=search does not trigger React's change event when clicking the "clear" button

### ISSUE THREAD

**Issue by marcins** [facebook/react#7475]
**Do you want to request a *feature* or report a *bug*?**  Bug

**What is the current behavior?**

In Chrome, Firefox, Edge, etc when using an `input` with `type='search'` clicking the clear button (the "X" on the right) triggers the React onChange event. In IE11 (and probably earlier versions) the onChange event does not fire even though the input is cleared.  `onInput` DOES get fired in IE11 when the search box is cleared.

http://jsbin.com/sizaba/3/edit?html,js,console,output

**What is the expected behavior?**

The React `onChange` event will consistently fire in IE11 as well.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.1+ is definitely affected. Not sure if it worked previously. IE11 is affected, but other browsers including Edge do not appear to be.

**Comment by marcins** [comment]
Looks like this is fixed on `master` (or at least I can't reproduce it locally), but it definitely happens with 15.3.0. Can't see anything obvious in the git log for `ChangeEventPlugin` or `inputValueTracking` which is where I thought the issue might be.  Having a quick look through the git log since v15.3.0, maybe 8af6f9e5a2f74256b6dc955bbc8be3d90435151e or 08a0895887c82e379d7717439c7a8d0b015e0696 fixed this?

**Comment by nhunzaker** [comment]
Beat me too it. I was just about to comment on the same thing. Bumping the `inputValueTracking` threshold down to IE10 fixes the issue, but the comments suggest that IE10+ fires `oninput` pretty noisily. 

I believe https://github.com/facebook/react/issues/7211 is the same issue.

**Comment by marcins** [comment]
@nhunzaker ah, nice, thanks. I'm going to close this given it's fixed on master so presumably will make it into a release at some point soon!

**Comment by JasonLawrenceDuncan** [comment]
Can anyone confirm whether this fix has made it into a recent release? We're on 15.4.1 and seem to still be seeing the issue.
