### ISSUE TITLE
Problematic code in Tutorial

### ISSUE THREAD

**Issue by lawrencemok** [facebook/react#7478]
In this page: https://facebook.github.io/react/docs/tutorial.html

pollInterval="{2000}" caused the browser to load /api/comment every 0ms

instead it should be

pollInterval="2000" to load every 2 seconds

**Comment by zpao** [comment]
It's written as `pollInterval={2000}` (without the quotes) in the tutorial, which should be ok. Did you possibly mistype it?

**Comment by lawrencemok** [comment]
Sorry my mistake, please close this issue. Everything is working fine.
