### ISSUE TITLE
Doc to explain how to bind methods with arrow functions

### ISSUE THREAD

**Issue by kutyel** [facebook/react#7479]
**Do you want to request a *feature* or report a *bug*?**
A feature, more specifically, an improvement in the docs.

**What is the current behavior?**
I have read trough all of React documentation in the last days and was confused by [this](https://facebook.github.io/react/docs/reusable-components.html#no-autobinding) section:
```js
constructor(props) {
  super(props);
  this.state = {count: props.initialCount};
  this.tick = this.tick.bind(this);
}
```
The docs say it is *better performant* and I couldn't find a place in the docs where it shows the arrow function alternative. I just accidentally learn it from some open source GitHub projects and from a [react-codemod](https://github.com/reactjs/react-codemod/blob/master/transforms/manual-bind-to-arrow.js):
```js
constructor(props) {
  super(props);
  this.state = {count: props.initialCount};
}
tick = () => { /* tick implementation */ }
```
Does this approach have the *same* performance? Shouldn't it be somewhere in the docs?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
It is not a bug.

**What is the expected behavior?**
There should be any kind of mention to **the arrow function approach** to bind methods to the component or preferably, should be well documented.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am sure it is due to an update on React itself, but I am not sure in what version.

---

PD: BTW, if this issue is accepted and planned, I would be happy to make a PR to fix it, with some guidance from the community about what else to include in the docs. :wink:

**Comment by syranide** [comment]
For all intents and purposes they are the same. IIRC that feature has not been accepted into the standard yet, or has it changed?

**Comment by hawkrives** [comment]
According to the [tc39 proposals][1] repo, [Public Class Fields][2] is stage 2 at the moment.

[1]: https://github.com/tc39/proposals
[2]: https://github.com/jeffmo/es-class-public-fields

**Comment by kutyel** [comment]
Oh... so it's a matter of wether it ends in the ECMAScript or not, OK. But then, why has the facebook team prepared a **codemod** for that? It is just anticipation?

**Comment by gaearon** [comment]
We are dogfooding this proposal internally at Facebook.

**Comment by kutyel** [comment]
Thanks very much @gaearon!

**Comment by Aweary** [comment]
The Babel react preset should probably support this before it's added to the documentation. Currently, you need to use the [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) to get this working.

**Comment by kevinSuttle** [comment]
Sidebar: what about the proposed bind operator? 
https://github.com/tc39/proposal-bind-operator

**Comment by gaearon** [comment]
This experimental proposal is now [mentioned](https://facebook.github.io/react/docs/handling-events.html) in the docs.

@kevinSuttle It doesn't solve the issue for us because it rebinds on every render.

**Comment by kutyel** [comment]
@gaearon great! Nice work with the docs Dan! ;)
