### ISSUE TITLE
printWasted doesn't show all wasted renders

### ISSUE THREAD

**Issue by foiseworth** [facebook/react#7484]
**Do you want to request a _feature_ or report a _bug_?**
(Possibly a) Bug

**What is the current behavior?**
When using react addons perf and printWasted I do not see as many entries as I think I should. In the example case I see no entries.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://github.com/foiseworth/react-perf-tools-issue/blob/master/src/App.js

**What is the expected behavior?**
Root > App should show in printWasted as it does re-render when you click but the output is just a cached element so it was a wasted render.

As you can see this code will walk up the tree from the Bottom component (which wasn't a wasted render) and mark the App as not a wasted render even though it was.
https://github.com/facebook/react/blob/master/src/renderers/shared/ReactPerf.js#L206

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.3.0 / Mac OSX / Unsure

**Comment by gaearon** [comment]
Can you please turn this into a failing test case in `ReactPerf-test`?

**Comment by gaearon** [comment]
We've removed ReactPerf for now in 16. We might re-add it later but we'll need to rewrite it anyway.
