### ISSUE TITLE
Cannot add new properties to a received object, before to call a fn with this object in argument, without freezing

### ISSUE THREAD

**Issue by MadeInMoon** [facebook/react#7509]
Very strange (bug?) behaviour here! 
`react@15.1.0`

The Following code works:

```
handleSelect(myObj, i){
  this.props.openDialog(myObj);
}
```

The following codes freeze the browser:

1)

```
handleSelect(myObj, i){
  myObj.test = 'test';
  this.props.openDialog(myObj);
}
```

2)

```
handleSelect(myObj, i){
  let newObj = {};
  newObj = myObj;
  newObj.test = 'test';
  this.props.openDialog(newObj);
}
```

**Comment by Aweary** [comment]
Hey @MadeInMoon, can you share a test case that reproduces this issue? You can use https://jsfiddle.net/reactjs/69z2wepo/ as a starting point 👍

It would also be helpful to know if this is affecting a specific browser, and if you've tried with the latest version of React (`15.3.0`).

**Comment by Aweary** [comment]
Since there's been no response I'm going to go ahead and assume this is no longer an  issue and close this out.
