### ISSUE TITLE
API for accessing `props.children` correctly

### ISSUE THREAD

**Issue by chenglou** [facebook/react#751]
(Check the comment on http://facebook.github.io/react/tips/children-props-type.html)

I also feel that saving an array allocation once out of x times causes a bit too much inconvenience. I think we should either return the array all the time or, as @vjeux suggested in IRC, expose an API for getting the children correctly.
1. Returning the array: treat one item the way way we treat multiple items.
2. Exposing an API: while we're at it, flatten the children to one single level and return it.

**Comment by darkyen** [comment]
Can I traverse them recursively ? This doesn't seem to work 

```
   function visit(node){
          return ReactChildren.map(node.props.children, visit);
   };

    var drawStack = return;
```

**Comment by binarykitchen** [comment]
Is there a function that returns me all the React children **recursively**?

I need that for collecting and adjusting form data before submit.

**Comment by warmhug** [comment]
I want to traverse all children recursively, find the specific type of node and use `React.cloneElement` to change their props in some condition. If this is a wrong method?
