### ISSUE TITLE
[Feature request] [ReactDom] Server rendering with chunked encoding

### ISSUE THREAD

**Issue by DanielHeath** [facebook/react#7518]
Feature request

**What is the current behavior?**
Currently `ReactDom.renderToString()` must synchronously render a complete component.

This means that react servers which connect to other data sources must wait for those to respond before beginning to send an HTTP response.

**What is the desired behavior?**
Support server-side use of `encoding: chunked` by 
- Exposing a streaming render API e.g. `ReactDom.renderToStream()`.
- Providing a way for react components to 'block' rendering server-side

**What would this improve?**
This would enable much lower latency in cases where a server is connecting to multiple backing services to service a request, because content early in the document can be delivered to the browser before all backends have responded.

**Comment by DanielHeath** [comment]
This is related to https://github.com/facebook/react/issues/6420 but adds the ability for components to say 'I am not quite ready yet; block rendering' on the server.

**Comment by gaearon** [comment]
#6420 has landed in React 16.
https://medium.com/@aickin/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67

We have another issue for “blocking rendering” in https://github.com/facebook/react/issues/1739 so let’s close this one.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/20970
