### ISSUE TITLE
How to test onSelect

### ISSUE THREAD

**Issue by bensampaio** [facebook/react#7522]
TestUtils allows the simulation of several types of events but I couldn't find a way to simulate the onSelect event in an input element. Am I looking in the wrong place? How can I test the onSelect event? Thank you!

**Comment by Aweary** [comment]
Hey @bensampaio, we try to use the issue tracker solely for tracking bugs and feature requests. In general, we encourage you to post usage questions on StackOverflow.

That said, `ReactTestUtils.Simulate.select` does exist so I would start with trying to implement that and reference StackOverflow if you run into issues. Thanks!
