### ISSUE TITLE
input file upload panel shows after 7+ seconds in chrome opening 15 tabs 

### ISSUE THREAD

**Issue by WangXiZhu** [facebook/react#7527]
I am a new react user, upload file in chrome which is opening 15 tabs, when I click the upload button, the upload file panel is display after 7+ seconds,but I use the same code with the Chrome opening 15 tabs in local(ps: file:///) ,the upload panel show after 1+ second.

```
<label for='upload-file'>
  <span>upload</span>
  <input id='upload-file' type="file" style='display: none;'>
</label>
```

but when I open the page in separate window with the Chrome ,the upload file panel show after 1 second which seem as normal
thanks all

**Comment by KanteLabs** [comment]
Having you tried checking the chrome console to debug it?

**Comment by aweary** [comment]
Closing this out since there's been no follow-up, and it doesn't sound like a React issue.

**Comment by WangXiZhu** [comment]
yeah, it's chrome's bug. there is a way to fix it.  set the `input` attribute `accept`
```
  <input id='upload-file' type="file" style='display: none;' accept="image/png,image/gif">
```
