### ISSUE TITLE
[react-router] `Router` no longer defaults the history prop to hash history

### ISSUE THREAD

**Issue by m-menon** [facebook/react#7534]
Totally new to react and stuff and had to get a node application which uses react. Ironed out most errors except for the 2 shown in the picture. Any pointers will be great as I am a total newbie to both node n react. Thanks

```
Error 1. [react-router] `Router` no longer defaults the history prop to hash history
Error 2. bundle.js:79269 Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```

![react_error](https://cloud.githubusercontent.com/assets/10776430/17830836/0d04ea5e-670b-11e6-8bf3-ad4499fc1509.jpg)

**Comment by gaearon** [comment]
Hi!

As for the React Router warning, I believe the warning itself contains a link: http://tiny.cc/router-defaulthistory. If you click on it, you will find the warning description. It has no relation to React itself (which is what this repo is for). React Router is a third party project, so React issues is not the right place to discuss it.

As for the second warning, it says what it says: `React.findDOMNode` is deprecated, and you should use `ReactDOM.findDOMNode` instead.

**Comment by m-menon** [comment]
great thanks for the help :+1: First time dealing with React :)

**Comment by m-menon** [comment]
Tried to figure out which line(s) spit the error. There's a whole bunch - it makes things worse cos I had to use react for the first time as there is a node js gps tracker sample application that I need to test. The code was of course not written by me....Here's another screenshot (expanded error lines)

![react_shit](https://cloud.githubusercontent.com/assets/10776430/17832905/c2a5cdc0-6741-11e6-9e62-010db5f5774c.jpg)

**Comment by gaearon** [comment]
Usually you look at the stack trace for the first line that is your code. "Warning" and "deprecated" are React's but third line is yours.

**Comment by gaearon** [comment]
You can also search your source for findDOMNode ;-)

**Comment by gaearon** [comment]
Finally you can enable "break on caught exceptions" in Chrome debugger and when it stops, click on frames in the call stack one by one to find your code in it. This is not really related to React, it's just how you use a debugger.
