### ISSUE TITLE
Unclear docs and API for children, esp. only children

### ISSUE THREAD

**Issue by joshkel** [facebook/react#7535]
I'm writing a table cell component that will specially handle the case where it's given a single number, and from looking at the documentation and API, I'm unclear on how to do this:

* ["Multiple Components"](https://facebook.github.io/react/docs/multiple-components.html#children) and ["Top-level API"](https://facebook.github.io/react/docs/top-level-api.html#react.children) say that `this.props.children` is "opaque" and suggest that the `React.Children` APIs should be used to preserve  `this.props.children`'s encapsulation.
* ["Type of the Children props"](https://facebook.github.io/react/tips/children-props-type.html) gives full details on how `this.props.children` is implemented and suggests that `React.Children` is provided simply as a convenience.
* [The docs for `React.Children.only`](https://facebook.github.io/react/docs/top-level-api.html#react.children.only) say that `only` gets the single child, but in reality, it gets the single child _as long as that child is a React element_. (React 15.3.1 at least [improves the error message](https://github.com/facebook/react/pull/7514) in this case.)

My questions, or suggestions for improvements to the docs:
* Is `this.props.children` supposed to be opaque? If so, "Type of the children props" should be updated.
* Or is it supposed to be public? If so, "Multiple Components" and "Top-level API" should be updated.
* Can the documentation for `React.Children.only` be updated to clarify that it requires a valid React element and possibly to explain the use case for this requirement? (See comments on #1104 for some of the confusion caused by the current documentation.)* What's the official or recommended way to get at the only "anything renderable" child, as opposed to the only "valid React element" child?
  * Changing `React.Children.only` to allow for string and number nodes was closed as won't fix (#1104)
  * Using `this.props.children` directly goes against the docs' statement that it should be opaque.
  * Using `React.Children.map` or `React.Children.forEach` seems like overkill.

If `this.props.children` is supposed to be opaque, then would a new `React.Children.onlyNode` function be a useful solution?

**Comment by gaearon** [comment]
Some of these docs are gone now.
Let's track a separate "Manipulating Children" guide in #8060.
Would you like to work on it?
