### ISSUE TITLE
dangerouslySetInnerHTML won't set all HTML

### ISSUE THREAD

**Issue by mmdonaldson** [facebook/react#7541]
Have come across an issue with dangerouslySetInnerHTML. 

When I set the HTML to 

`<table><tr><td>Hello World</td></tr></table>`

It renders correctly.

In my situation I need to render

`<tr><td>Hello World</tr></td>`

But dangerouslySetInnerHTML strips out the tags, I think because it's missing the outer table tags.

Please see the attached link for an example [https://jsfiddle.net/90u53orz/10/]

Any Suggestions/workarounds/fixes would be awesome?

**Comment by vjeux** [comment]
You can set dangerouslySetInnerHTML in the `<table>` element as seen in this fiddle: https://jsfiddle.net/1dfafp8b/

```js
        <table dangerouslySetInnerHTML={this.rawMarkupA()} />
```

The browsers are doing some weird things with `<table>` when you include `<div>` inside of them :)

**Comment by mmdonaldson** [comment]
@vjeux I actually need to render multiple <tr> row's which will be wrapped in an outer table.

Example:

`<tr><td>Some text</td></tr>`
`<tr><td>Some more text</td></tr>`

Each time I inject the code, this will be wrapped in an outer <table>

Is there a way you could suggest me doing this?

**Comment by vjeux** [comment]
The only thing that comes to mind right now is to do

```js
<table>
  {rows.map(row =>
    <tr dangerouslySetInnerHTML={row.slice('<tr>'.length, -'</tr>'.length)} />
  )}
</table>
```

this is not pretty but should do the trick.
