### ISSUE TITLE
Should defaultValue trigger onChange event?

### ISSUE THREAD

**Issue by damianprzygodzki** [facebook/react#7542]
In my opinion defaultValue is just programmatically init of input value, and its not change of input.

Now when i init input with defaultValue, it triggers onChange event. What is wrong, because there was no change yet.

`<input defaultValue="hey babe!" onChange={()=>{console.log('occured')} />`

BUT! When i think about it, like the defaultValue is just pushing value into input attribute, we have to keep consistency with native events (onchange is triggering always if value changes).

**Comment by bhargav175** [comment]
Input should not trigger onChange on defaultValue. Also, in react@15, defaultValue does not trigger a change. View `[pen]( https://codepen.io/bhargav175/pen/pbmVGJ)`. Can you please elaborate? Do you think onChange should be called for defaultValue init or do you see an onChange for defaultValue and it should be fixed. Please share a codepen/fiddle link with example.
