### ISSUE TITLE
Support of "as" on Link for PreLoad

### ISSUE THREAD

**Issue by SunnyGurnani** [facebook/react#7543]
rel="preload" is the new functionality in latest browsers to preload the content. However Reactjs currently strips "as" on `<Link>`

Here is the warning we get : Unknown prop `as` on `<link>` tag. Remove this prop from the element. For details,

**Comment by zpao** [comment]
Would you be interested in adding it?

**Comment by soupaJ** [comment]
If @SunnyGurnani does not want to add it, may I give it a try?

**Comment by kevinslin** [comment]
Ran into this issue as well so made the fix (apologies @soupaJ). This is my first time contributing to **react** so please let me know if there's something missing. Signed the CLA and followed instructions outlined in the [CONTRIBUTING](https://github.com/facebook/react/blob/master/CONTRIBUTING.md) section

**Comment by Aweary** [comment]
Closed in https://github.com/facebook/react/pull/7582
