### ISSUE TITLE
ReactJS components are not rendering in AJAX 

### ISSUE THREAD

**Issue by thangam105** [facebook/react#7559]
Hi,

I have used the AJAX for load the ReactJS components html file.But that components are not rendering.

i have explained the sample in below link
https://phabricator.babeljs.io/T7569

How to achieve this?

Regards,
Thangavel E

**Comment by MrsJLane** [comment]
Never even mentioned that. But ok. Thanks

**Comment by thangam105** [comment]
Have any solution for ReactJS components rendering in AJAX?

**Comment by keyanzhang** [comment]
Hi @thangam105,

There is a section in the documentation that explains loading initial data via AJAX (in `componentDidMount`): https://facebook.github.io/react/tips/initial-ajax.html. The example uses jQuery but you can use any preferred way to do it (such as [`fetch`](https://github.com/github/fetch)). I hope it helps!

We encourage you to post usage questions on StackOverflow—the issue tracker here is mainly for bugs in React. Thanks!
