### ISSUE TITLE
basic-jsx-precompile is not working 

### ISSUE THREAD

**Issue by thangam105** [facebook/react#7560]
Hi,

I have downloaded the script from you mentioned  starter kit. And then referred those file in index.html.

ReactJS components are not rendering.I got one console error.

<img width="541" alt="reactissue" src="https://cloud.githubusercontent.com/assets/13119007/17966202/0207bc54-6ade-11e6-9606-b3fc983e3085.PNG">

I have referred the online link
https://github.com/facebook/react/tree/master/examples/basic-jsx-precompile

I am new to reactJS. Please help me How to resolve this error?

Regards,
Thangavel E

**Comment by gaearon** [comment]
The README file on the left contains *instructions* to run Babel to compile the JSX files.
You need to run those instructions, this example won’t work if you don’t.

For new projects and learning React, we recommend the recently released [Create React App](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html).
It’s not mentioned in the documentation yet because it’s very new, but I recommend you to try it.
It’s easier than figuring out all the build configuration yourself.

**Comment by thangam105** [comment]
Thanks for reply..
"text/babel" scripts are not trigger while append the ajax response content in DOM.

How to resolve this?

**Comment by MrsJLane** [comment]
I'm not even sure why y'all askin me.

**Comment by gaearon** [comment]
@thangam105 

Sorry, I don’t understand what you’re asking. Can you provide a sequence of steps with screenshots demonstrating what goes wrong and what you expected?

**Comment by thangam105** [comment]
Hi @gaearon,

Thanking you for reply...

**index.html:**
========================================================
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>JS</title>
<link href="ej..web.all.min.css" rel="stylesheet" />
<link href="content/style.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.1/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.1/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js"></script>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="http://js.syncfusion.com/demos/web/scripts/jsondata.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.79/jsrender.js"></script>
<script src="scripts/samplelist.js"></script>
<script src="scripts/ej.web.all.js"></script>
<script src="scripts/ej.widget.react.js"></script>
</head>
<body>
<div id="parent" class="react-page"></div>
<script type="text/babel">
var ReactApp= React.createClass({
render: function() {
  return (
 <EJ.Tab id="ajaxTab" style="width: 500px"  ajaxSettings-dataType="html" ajaxSettings-contentType="html" ajaxSettings-async={true} >
                      <ul>
                          <li><a href="#ASPNET">ASP.NET</a></li>
                          <li><a href=**"button/default.html"**>ASP.NET MVC</a></li>
                          <li><a href=**"button/default.html"**>WPF</a></li>
                      </ul>
                      <div id="ASPNET">
                          ASP.NET is a server-side Web application framework designed for Web development to produce dynamic Web pages. 
                      </div>
                  </EJ.Tab>
    );
}
})

ReactDOM.render(<ReactApp/>,
document.getElementById('parent')
);
	 </script>
</body>
</html>
===============================================================

**button/default.html**
================================================================
<div>
	  <div id="container"></div>
<script type="text/babel">
   **debugger**
		ReactDOM.render(   
		  <EJ.Tile></EJ.Tile>,
		  document.getElementById('container')
		);
	 </script>
   </div>
==================================================================

I have used the AJAX for load the **"button/default.html"** file. The **debugger** is not hit when append the ajax response data in DOM when use the script type="text/babel".

How to achieve this and any solution for this?


Regards,
Thangavel E

**Comment by gaearon** [comment]
`basic-jsx-precompile` is not the right example for this because it *precompiles* JSX.
On the other hand, you seem to want to use `script type="text/babel"` which is executed at *runtime*.

Is there any reason why you can’t use [Create React App](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html) for this?

**Comment by thangam105** [comment]
Yes.. In previous comments i am not attached the screenshot before you comments.

Now i am attached the screenshot.Please check the previous comment screenshots

Have any solution?

**Comment by gaearon** [comment]
I would like to repeat this:

>Is there any reason why you can’t use [Create React App](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html) instead?

It is much easier to use than these examples. Have you tried it?

For `script type="text/babel"` to work, you need to ensure you have [this line](https://github.com/facebook/react/blob/a229cdba7fd00799d82c1bab23704220d47e6331/examples/basic-jsx/index.html#L28) in your `html` file.

But again, please consider trying [Create React App](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html) instead, it’s much easier to explain.

**Comment by thangam105** [comment]
Hi @gaearon,

**For script type="text/babel" to work, you need to ensure you have this line in your html file.**

I have referred the  browser.js file in index.html file.Its trigger only DOMContenteLoad.This script is not trigger when append the AJAX response content in DOM. Normal script tag is trigger when append the AJAX response append in DOM.

I will try  Create React App and let you know.

Regards,
Thangavel E

**Comment by gaearon** [comment]
Okay, I didn’t realize you were adding more scripts after an AJAX call. This is a bit unusual.

>I will try Create React App and let you know.

👍
