### ISSUE TITLE
onContextMenu stopPropagation doesn't work!

### ISSUE THREAD

**Issue by liximomo** [facebook/react#7573]
I bind onContextMenu to a div, and call event.stopPropagation() in event handle, but it still reach to contextMenu event handle of document.

```js
document.addEventListener('contextmenu', preventMenuOfContextMenu, false);
function preventMenuOfContextMenu(event) {
  console.log('1'); // always log
}

onContextMenu(event) {
    event.preventDefault();
    event.stopPropagation();
}
render() {
    return (
      <div className="ContextMenu" onContextMenu={this.onContextMenu}>
        {this.props.children}
      </div>
    );
}
```

**Comment by Andarist** [comment]
https://github.com/facebook/react/issues/7094

**Comment by Aweary** [comment]
Yupp, this is expected behavior for the React event system. Check out https://github.com/facebook/react/issues/7094#issuecomment-228931737 for a detailed explanation 👍
