### ISSUE TITLE
isRequired / nesting validation functions

### ISSUE THREAD

**Issue by fab1an** [facebook/react#7574]
How is it possible to implement adding a generic `isRequired`-variant to a custom validation function, without including the checks for null and undefined into the function itself.

Prior to `15.3.0` I just had an `isRequired`-validator that wrapped another validation function and called it if the value was present. Now it's no allowed anymore to call validations function directly, so how to nest them?

**Comment by gaearon** [comment]
The warning message you see contains a link. If you follow that link you will see the instructions for writing generic validators in the last section.

**Comment by gaearon** [comment]
Specifically:
https://facebook.github.io/react/warnings/dont-call-proptypes.html

The section you are looking for is called “Fixing the false positive in third party PropTypes”.

**Comment by fab1an** [comment]
Thank you. 

I'm using it with ReactNative and didn't get any warning messages at all. I just saw a parameter value `DO_NOT_PASS_THIS...` when debugging why my validator didn't work.

**Comment by gaearon** [comment]
What do you mean by “did not work”? It’s hard to say what didn’t work without the code.

**Comment by fab1an** [comment]
I used the last parameter, which is now the secret, to pass an "isRequired" flag.

**Comment by gaearon** [comment]
I’m afraid I don’t understand what you were you doing without the code.

**Comment by fab1an** [comment]
This was some code I had which was broken. I changed it now, it works again, thanks.

```javascript
import _ from "lodash";

export function enumType(typeName, typeValues) {

    function validator(props, propName, componentName, location, propFullName, isRequired = false) {
        const prop = props[propName];

        if (!_.isUndefined(prop) && !_.isNull(prop)) {

            /* check if not a string or, if values were given, if the value is allowed */
            if (!_.isString(prop) || (typeValues && !_.includes(typeValues, prop))) {
                return new Error(`INVALID ${propName} <${prop}> (${componentName})`);
            }

        } else if (isRequired) {
            return new Error(`MISSING ${propName} (${componentName})`);
        }
    }

    validator.isRequired = function(props, propName, componentName, location, propFullName) {
        return validator(props, propName, componentName, location, propFullName, true)
    }

    return validator;
}
```
