### ISSUE TITLE
rename `receiveComponent` to `receiveElement`

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#7575]
@zpao just gave a talk at React Rally and mentioned that `receiveComponent` could be improved if it were renamed to `receiveElement`. I'd be happy to file a PR to make this a reality if it's not too huge a task :) Anything I should consider before a do a big find/replace?

**Comment by iamdustan** [comment]
Potentially need to update React Native, React ART, ReactTestutils, etc as a follow-up.

**Comment by syranide** [comment]
#2354 :smile:

**Comment by gaearon** [comment]
These actually won't be a problem anymore once React Native ships a copy of the renderer. There is an open diff for that.

**Comment by kentcdodds** [comment]
To clarify, you're suggesting that we wait for that to happen and then make this refactor and less will need to be changed?

**Comment by gaearon** [comment]
Yea I think so.

**Comment by kentcdodds** [comment]
Is there some issue/pr I can subscribe to so I know when I can work on this issue?

**Comment by gaearon** [comment]
I think @sebmarkbage submitted that diff internally so it isn’t visible as a PR to React Native.
I’ll assign myself to this issue to keep track of it, and will ping you when the road is clear.

**Comment by gaearon** [comment]
We likely won't be doing this because we are focusing on Fiber, and it doesn't even have those methods. Thanks for the suggestion though!
