### ISSUE TITLE
"'documentMode' in document" check giving inconsistent results

### ISSUE THREAD

**Issue by SchleyB** [facebook/react#7583]
**Bug**

**What is the current behavior?**

Line 124 of ChangeEventPlugin.js 

`isInputEventSupported = isEventSupported('input') && (!('documentMode' in document) || document.documentMode > 11);`

Is incorrectly returning false in non-IE browsers when paired with some 3rd party code, specifically

`!('documentMode' in document)`

Is returning false because Google Tag Manager in this case is setting document.documentMode to undefined.  This is causing these errors on input fields

`Uncaught TypeError: activeElement.detachEvent is not a function`
`TypeError·Uncaught TypeError: Cannot delete property 'value' of #<HTMLInputElement>`

A better check in this case might be 

`!document.documentMode`

As this would still accomplish the intended check while minimizing conflicts with other codebases

I have found a couple of other instances of this issue:
https://github.com/facebook/react/issues/7421
https://github.com/facebook/react/issues/5920

**Which versions of React, and which browser / OS are affected by this issue? **

Chrome 52 
React 15.3.1

**Comment by gaearon** [comment]
Would you like to send a PR?

**Comment by TedPowers** [comment]
Sure thing...[7594](https://github.com/facebook/react/pull/7594)

**Comment by zpao** [comment]
That's merged so we can close this out. Thanks!
