### ISSUE TITLE
Native Map detection in ReactComponentTreeHook fails with core-js

### ISSUE THREAD

**Issue by sanniassin** [facebook/react#7593]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Using polyfilled ES6 `Map` on browsers without native Map support

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar**
https://jsfiddle.net/t5ht7mmb/1/ – `isNative` returns `true` on IE9

**What is the expected behavior?**
Using objects instead of `Map`. While `isNative` method has been implemented in #7491 it can't detect core-js polyfills. Look at discussion in comments here: https://github.com/lodash/lodash/commit/e156459176c1f35964fc443b39f04c4cb0a96763#diff-001d0647fb00f8336795faccdec19a31R11199

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.3.1

**Comment by gaearon** [comment]
Do you have any suggestions on what we could do?

**Comment by sanniassin** [comment]
Only ugly solutions like detecting feature availability in iframe
```js
var iframe = document.createElement('iframe');
document.body.appendChild(iframe);
return !!iframe.contentWindow.Map;
```

**Comment by gaearon** [comment]
Is running DEV builds on an old browser a major use case for you?
Is it noticeably slower with core-js polyfill?

**Comment by sanniassin** [comment]
For me it's not a problem at all. I just wanted to attract attention to problem with nativeness detection and core-js if this detection will be used somewhere else in future.

**Comment by Aweary** [comment]
I do think we want to use ES6 Maps in the production code path eventually, so It won't always be a dev-only issue

**Comment by gaearon** [comment]
We don't use that code anymore.

But also, React 16 explicitly asks you to polyfill Map because we use them elsewhere.
