### ISSUE TITLE
CSSTransitionGroupChild transition stops if child updates class

### ISSUE THREAD

**Issue by spicyj** [facebook/react#761]
http://jsfiddle.net/spicyj/6ubyH/

**Comment by spicyj** [comment]
Related to #719.

**Comment by spicyj** [comment]
(@simenbrekken Your workaround is the best I know of.)

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition
