### ISSUE TITLE
Bug when using React in .net's WebBrowser

### ISSUE THREAD

**Issue by andrewQwer** [facebook/react#7622]
We use React for our web application and it works well. But also we have some Office add-ins that use `System.Windows.Forms.WebBrowser`, and the problem occurs in these add-ins. When we try to show `select` tag application show script error like this:
![image](https://cloud.githubusercontent.com/assets/710513/18129296/c9c44dee-6f92-11e6-97b3-9f0342a37323.png)
When we go to the mentioned line of code we see the following:
```javascript
var insertTreeBefore = createMicrosoftUnsafeLocalFunction(function (parentNode, tree, referenceNode) {	
	  if (tree.node.nodeType === DOCUMENT_FRAGMENT_NODE_TYPE || tree.node.nodeType === ELEMENT_NODE_TYPE && tree.node.nodeName.toLowerCase() === 'object' && (tree.node.namespaceURI == null || tree.node.namespaceURI === DOMNamespaces.html)) {
	    insertTreeChildren(tree);
	    parentNode.insertBefore(tree.node, referenceNode);
	  } else {
	    parentNode.insertBefore(tree.node, referenceNode); <-- ERROR OCCURS HERE
	    insertTreeChildren(tree);
	  }
	});
```
This function is located in `DOMLazyTree.js` While debugging we found out that `tree.node` for select is `[object Object]` and looks like `parentNode.insertBefore(...)` doesn't accept this node.

We tried to increase IE version according to this  [guide](https://msdn.microsoft.com/en-us/library/ee330730(VS.85).aspx#browser_emulation) and it shows the following string 
![image](https://cloud.githubusercontent.com/assets/710513/18129677/6dd82396-6f94-11e6-828c-d880125900b2.png)  which refers to IE 11 but with no luck.

This error only occurs in MS Office environment (Word Add-in, Excel Add-in etc.). When you try to use .net's WebBrowser component on Windows Form application it works correctly. Do you have any ideas how we can use `select` tag in this case?

**Comment by gaearon** [comment]
You’d need to inspect what `tree.node` really is. What properties does it have?

**Comment by andrewQwer** [comment]
Sorry for the format, but it is the only way to see object properties in Web Browser 
~ sign is delimeter
![image](https://cloud.githubusercontent.com/assets/710513/18132248/ba7b56e6-6f9e-11e6-9d4b-8010c4615b3f.png)

**Comment by gaearon** [comment]
That’s interesting. I would recommend trying to reproduce this without React. Can you create a similar DOM structure in vanilla JS?

**Comment by andrewQwer** [comment]
Pure select is rendered correctly because it doesnt use DomLazyLoad

----Пользователь Dan Abramov написал ----

**Comment by zpao** [comment]
That certainly looks like a DOM node. tagName isn't in the property list but it sounds like you did narrow it down. Are you sure the first argument is the issue? What's `referenceNode` in this case?

I think Dan meant try to reproduce the same behavior without React. I think for IE we work top down for perf. Something like this:

```js
var container = document.getElementById('container');
var form = document.createElement('form');
var select = document.createElement('select');
var option = document.createElement('option');
form.insertBefore(select, null); // This is where you're hitting the issue. null might not cause it though
select.insertBefore(option, null);
contianer.appendChild(form);
```

**Comment by andrewQwer** [comment]
I tested your code and got the same error. Script failed on this line: ` form.insertBefore(select, null);`

**Comment by syranide** [comment]
So it's not allowed to append a child to a non-parented node? Is that it? Or is it specifically only a problem with `select`? (having no children?)

**Comment by andrewQwer** [comment]
It is select specific problem, because other HTML tags work correctly.

**Comment by andrewQwer** [comment]
Looks like select is not determined as HtmlElement

**Comment by andrewQwer** [comment]
Looks like we found the reason: https://support.microsoft.com/en-us/kb/927377

**Comment by gaearon** [comment]
I'll close because it doesn't look like something we should fix on our side and you have a workaround.

**Comment by andrewQwer** [comment]
yes, thank you. It is not React.js issue at all :smile;
