### ISSUE TITLE
ref callbacks with renderToString not being called

### ISSUE THREAD

**Issue by BDiehr** [facebook/react#7624]
The bug i'm experiencing is that ref callbacks are not called after mount when using renderToString.

From the documentation: 

> React supports a special attribute that you can attach to any component. The ref attribute can be a callback function, and this callback will be executed immediately after the component is mounted. The referenced component will be passed in as a parameter, and the callback function may use the component immediately, or save the reference for future use (or both).

My expectations are that the ref callbacks would be called after mount for both client side rendering, and server side rendering (using `renderToString`).

**Comment by gaearon** [comment]
This is because server side rendering doesn’t actually mount components. (Which means `componentDidMount` does not get called either.)

What is your use case?

**Comment by BDiehr** [comment]
That makes sense. My use case is for incorporating d3-axis function calls to create a chart axis. The charts must be rendered on the server because I need to take pictures and store them so send down to the client.

d3-axis requires you to call a function and pass in the actual node. I think I have an alternate method which involves making an additional child component which allows me to add extra function calls after the component is actually rendered. Do you have a better suggestion?

**Comment by gaearon** [comment]
Sorry, I don’t quite understand without an example.

>d3-axis requires you to call a function and pass in the actual node.

Presumably you wouldn’t have a real node on server, would you?

**Comment by BDiehr** [comment]
I solved this, it ended up what I was trying to do was impossible. I ended up solving my solution by running `React.render` within the context of `jsdom` on the server, and then using `xmlserializer` to convert the `document` to a string. This can then be used with phantom to render an image from the generated DOM.

**Comment by azizhk** [comment]
Is there any way that I can get ref to the component whose instance has been created (if its a component).
I was actually trying to call a function of a connected component. https://github.com/reactjs/react-redux/pull/270#issuecomment-175217424

My use case is that I have a wrapper which calls a method on the component and the component then it returns what its height going to be (predetermined based on logic, not need for actual DOM calculations).
