### ISSUE TITLE
Component is mounted twice when re-render triggered in componentWillUnmount

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react#7632]
React 15.1.0

Given:

``` js
console.clear();

class Test1 extends React.Component {
  componentDidMount() { console.log('mounted 1') }
  componentWillUnmount() {
    console.log('unmounted 1')
    update2();
  }
  render() { return React.createElement('div', {}, 'test 1'); }
}

class Test2 extends React.Component {
  componentDidMount() { console.log('mounted 2') }
  componentWillUnmount() { console.log('unmounted 2') }
  render() { return React.createElement('div', {}, 'test 2'); }
}

const render = (vNode) => {
  ReactDOM.render(vNode, document.querySelector('#root'));
};

const update1 = () => {
  render(React.createElement(Test1, {}, []));
}

const update2 = () => {
  render(React.createElement(Test2, {}, []));
}

update1()

setTimeout(() => {
  update2();
}, 2000)

```

Expected console output:

```
"mounted 1"
"unmounted 1"
"mounted 2"
```

Actual console output:

```
"mounted 1"
"unmounted 1"
"mounted 2"
"mounted 2"
```

The problem seems to be that I'm calling render from within `componentWillUnmount`—I suspect this is common i.e. dispatching Redux actions on unmount which trigger a synchronous render.

**Comment by Aweary** [comment]
Calling `ReactDOM.render` from `componentWillUnmount` doesn't seem like a pattern we'd want to encourage, but honestly I'm not sure. 

> I suspect this is common i.e. dispatching Redux actions on unmount which trigger a synchronous render.

I haven't really seen this pattern anywhere, usually I'd recommend using a stateful parent component or a HOC that provides state via props (like Redux's `connect`) and conditionally render from there.

**Comment by gaearon** [comment]
If you suspect a bug in React, can you submit a PR with a failing test?

**Comment by gaearon** [comment]
Seems like 16 fixed it somehow. 😄 
https://jsfiddle.net/r6nuxgf9/

**Comment by xgqfrms** [comment]
# why react component render twice, I'm so confused

![image](https://user-images.githubusercontent.com/7291672/82342623-6a3b6900-9a24-11ea-9939-dcdb3ca191f7.png)

> live demo

https://codesandbox.io/s/react-parent-child-lifecycle-order-33qrr?file=/src/components/parent.js

**Comment by srmono** [comment]
Me too same issue. finding solution

**Comment by ayushimittal104** [comment]
Facing the same issue

**Comment by kushalsht** [comment]
This twice calling some of the lifecycle methods, is only for development mode. 

**"Lifecycles will not be double-invoked in production mode."**
