### ISSUE TITLE
In tutorial, comments.json is used as file name while in the address, it is comments

### ISSUE THREAD

**Issue by quwei913** [facebook/react#7637]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Confusing
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://facebook.github.io/react/docs/tutorial.html
In above link, the file is named comments.json while in the code, "/api/comments" is used.
**What is the expected behavior?**
The file name should be consistent.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All versions.

**Comment by Aweary** [comment]
`comments.json` is the filename on the server, and `/api/comments` is the API URL for accessing that file. Check out the code that it links to: [reactjs/react-tutorial/blob/master/server.js#L38-L46](https://github.com/reactjs/react-tutorial/blob/master/server.js#L38-L46)
