### ISSUE TITLE
IE Edge: required select boxes with value set on initial render failing validation on submit.

### ISSUE THREAD

**Issue by tappleby** [facebook/react#7655]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

In IE Edge when rendering a required select box with an initial value set, when trying to submit the form the input will fail validation saying "You must choose an item from the list".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
1. Visit https://jsfiddle.net/hhgo0y9n/18/ in IE Edge.
2. Try to submit form.

**What is the expected behavior?**

The form should be valid and submit correctly.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Browser: IE Edge (v38 as of testing).
React versions: 15 to master (7b247f3609ad25d79ae267b4b5c919a35da45cb4).

Works in React 0.14.8.

**Notes**

I believe this might be a browser bug but the issue does not occur in React 0.14, perhaps using different apis? 

Related links:
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/291588/
- https://connect.microsoft.com/IE/feedback/details/817091/html5-validation-validity-object-does-not-update-itself-for-select-and-textarea-elements
- http://jsfiddle.net/NPb5f/

**Comment by nolanlawson** [comment]
Looks like a bug in IE/Edge. I filed it here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8794503/

**Comment by tappleby** [comment]
Temporary hack in our select component to get around the issue for now:

```
componentDidMount() {
  const selectedIndex = this.element.selectedIndex;

  if (this.element && selectedIndex >= 0) {
    const options = this.element.options;  
    const tempIndex = (selectedIndex + 1) % options.length;

    options[tempIndex].selected = true;
    options[selectedIndex].selected = true;    
  }
}
```

**Comment by jimfb** [comment]
cc @csuwildcat

**Comment by crgwbr** [comment]
Slight update to @tappleby's patch below. The original didn't work if the select only contained a single option. The below code detects that case and temporarily adds an additional option element, runs the option toggle to fix the edge bug, then remove the transient option.

```
componentDidMount () {
    let selectedIndex = -1;
    if (this.refs.select) {
        selectedIndex = this.refs.select.selectedIndex;
    }

    if (selectedIndex >= 0) {
        const inputDOM = ReactDOM.findDOMNode(this.refs.select);

        let tempOption;
        if (inputDOM.childNodes.length === 1) {
            tempOption = document.createElement('option');
            inputDOM.appendChild(tempOption);
        }

        const options = this.refs.select.options;
        const tempIndex = (selectedIndex + 1) % options.length;
        options[tempIndex].selected = true;
        options[selectedIndex].selected = true;

        if (tempOption) {
            inputDOM.removeChild(tempOption);
        }
    }
}
```

**Comment by jdalton** [comment]
I'm trying to create a small repro (without react) and having a hard time. Has anyone boiled this issue down to vanilla JS on jsbin or anything?

**Comment by jdalton** [comment]
I created a simple vanilla JS repro [here](https://jsbin.com/bekinel/).
The code is:
```js
var form = document.getElementById('form');
form.addEventListener('submit', e => e.preventDefault());

var select = document.createElement('select');
select.required = true;

var option1 = document.createElement('option');
option1.value = 1;
option1.text = 'one';
option1.selected = true;

form.appendChild(select);
select.appendChild(option1); // appending an option after the select is the problem
```

Swapping it to:
```js
select.appendChild(option1);
form.appendChild(select);
```
avoids the issue.

**Comment by jdalton** [comment]
> Swapping it to
>
``` js
select.appendChild(option1);
form.appendChild(select);
```

Is this related to the insertion order juggle React does for IE/Edge perf?

**Comment by gopinath-sixt** [comment]
Hi, In IE Edge when rendering a required select box with an initial value set, when trying to submit the form the input getting fail validation. The Select value coming in invalid in IE edge. Any solution?

https://codepen.io/anon/pen/JyzLMx?editors=0010

**Comment by gaearon** [comment]
>Is this related to the insertion order juggle React does for IE/Edge perf?

We don't do this anymore in React 16 so I assume this is fixed.

If not please file a new issue. Thanks!

**Comment by shabaz-ejaz** [comment]
Is there a fix for this with Redux Form? I am not using my own select component so I can't add the code that @tappleby mentioned in #245675946

My field looks like this:

                                    <Field
                                        name={`${protein}.title`}
                                        id={`${protein}.title`}
                                        component="select"
                                        onChange={onChange}
                                        required
                                        className="select-control ui protein selection dropdown2">
                                        
                                            <option value="" disabled>Please select a protein</option>
                                            
                                            {proteinItems.map((protein, proteinIndex) => (
                                            <option key={protein.id} value={protein.id}>{protein.title}</option>
                                             ))}
                                    </Field>

**Comment by gaearon** [comment]
Please report problems with Redux Form to their repository.

**Comment by tappleby** [comment]
The IE specific issue has been resolved in Edge 16299 as well - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8794503/#comment-3
