### ISSUE TITLE
numeric string value for CSS property `MsFlexGrow`

### ISSUE THREAD

**Issue by brigand** [facebook/react#7657]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

A warning

> a `span` tag (owner: `Box`) was passed a numeric string value for CSS property `MsFlexGrow` (value: `6`) which will be treated as a unitless number in a future version of React.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

```js
<div style={{MsFlexGrow: '3'}} />
```

**What is the expected behavior?**

It shouldn't warn.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.3.1.

---

Aside: is it MS or Ms (case)? I get a warning for both.

**Comment by Aweary** [comment]
@brigand it should be `msFlexGrow` 😄 ([see here](https://github.com/facebook/react/blob/67f8524e88abbf1ac0fd86d38a0477d11fbc7b3e/src/renderers/dom/shared/CSSProperty.js#L70) for the list of prefixes). See a working example without the warning [here](https://jsfiddle.net/r4860huk/1/)

**Comment by brigand** [comment]
Thanks!
