### ISSUE TITLE
Improve Warning Message When oneOfType Validation Fails

### ISSUE THREAD

**Issue by Slruh** [facebook/react#7662]
**Do you want to request a _feature_ or report a _bug_?**
Enhancement

**What is the current behavior?**

```
var Hello = React.createClass({displayName: 'Hello',
  propTypes: {
    name: React.PropTypes.oneOfType([
      React.PropTypes.bool,
      React.PropTypes.number,
    ]).isRequired
  },

  render: function() {
    return (
      React.createElement("h1", null, "Welcome to React"), 
      React.createElement("div", null, "Hello ", this.props.name)
    )
  }
});

ReactDOM.render(
  React.createElement(Hello, {name: "World"}),
  document.getElementById('container')
);
```

Running the above example, results in the following warning:

`"Warning: Failed propType: Invalid prop 'name' supplied to 'Hello'"`

**What is the desired behavior?**

The following improvement would be nice:
1. Adding the type of the supplied the bad value
~~2. Would be amazing to have the name of the checker functions though this may involve changes to createInstanceTypeChecker and createPrimitiveTypeChecker to work.~~

ex.

`"Warning: Failed propType: Invalid prop 'name' of type 'string' supplied to 'Hello', expected [boolean, number]`

I know this isn't high priority, but I'd like to at least add the type in. I would gladly do the work.

**Comment by Slruh** [comment]
I realize that 2 is pretty infeasible, but I'll prepare a pull request to add type into the error message.

**Comment by aweary** [comment]
PropTypes is not a separate package https://github.com/reactjs/prop-types, any issues or feature requests should be directed to the new repository 👍
