### ISSUE TITLE
Incorrect shallow rendering incase of children with the same key

### ISSUE THREAD

**Issue by faalsh** [facebook/react#7664]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Let's say we have a component that recieve an array and renders them in a list

```
var List = React.createClass({
  render: function() {
    return (
    <div>
        {
        this.props.items.map(function(item){
            return <div className="item" key={item.id}>{item.name}</div>;
        })
      }
     </div>
    )
  }
});
```

and let's say we passed the following array:

```
var items = [{id:'1', name: 'one'},{id:'1', name: 'two'}];
```

since the id is a duplicate, React will render only one item and throws the following warning 

```
Encountered two children with the same key, `1`. Child keys must be unique; when two children share a key, only the first child will be used.
    in div (created by List)
    in List
```

Here is a demo for the above https://jsfiddle.net/69z2wepo/55187/

However, when using ReactTestUtils to shallow render the list, it returns 2 items instead of 1. 

Below a testcase for demonstration purpose: 

```
describe('<List>', () =>

it('should render the correct number of items', () => {

    let items = [{id:'1', name: 'one'},{id:'1', name: 'two'}];
    let renderer = ReactTestUtils.createRenderer();
    let result= renderer.render(<List items={items} />);

    // the following testcase should fail
    expect(result.props.children.length).toBe(2)

}))
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

See above

**What is the expected behavior?**

Shallow Renderer should behave like in the browser, in this case it should return 1 children instead of 2. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.0.0

**Comment by Aweary** [comment]
@faalsh thanks for reporting it here as well, I'll try and look into this soon.

**Comment by gaearon** [comment]
I’m not sure if this would still reproduce since we rewrote shallow renderer.

But we actually changed the behavior in the browser to keep two nodes. **You should not rely on this behavior though.** It is completely unsupported to have two siblings with the same `key`. React reserves the right to keep them duplicate, omit one of them, or do something inconsistent in this case. This is why we strictly warn about it.
