### ISSUE TITLE
Mouseenter events triggered at disabled form element.

### ISSUE THREAD

**Issue by windyGex** [facebook/react#7673]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

When mouse enter disabled form element, trigger `mouseenter` events,  but it not trigger `mouseleave` when mouse leave from the element.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

http://jsbin.com/goxowolina/edit?html,js,output

First button rendered by react.

**What is the expected behavior?**

Don't trigger `mouseenter` events when form elements disabled.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.3.0. Yes.

**Comment by Aweary** [comment]
Thanks for the report @windyGex, this is something we're aware of. See https://github.com/facebook/react/issues/4251. I'm going to close this as a duplicate, so feel free to track https://github.com/facebook/react/issues/4251 for updates on this issue.
