### ISSUE TITLE
Bug: Missing warnings about unknown props / unknown DOM properties

### ISSUE THREAD

**Issue by marionebl** [facebook/react#7674]
**Actual**

* Missing warnings for unknown DOMProperties in development
* Missing warnings for unknown props  in development

**Expected**

* Unknown DOMProperties log warnings
* Unknown props log warnings

**Affected Versions**

| Software | Version | Test |
|:----------|:-------:|:-----|
| React     | 15.3.1  | 15.3.0 seems to work as intended |
| Runtime | node `6.5.0` | [Link](https://tonicdev.com/marionebl/57d02fc0e81c50140020d052) |
| Affected Browsers| Chrome (tested) | [Link](https://jsfiddle.net/9wgwq0v3/)|

**Comment by Aweary** [comment]
@marionebl thanks for the report. These warnings aren't logged when `React.createElement` is called, it's made when those elements are actually mounted. See https://jsfiddle.net/60d7v72j/

**Comment by marionebl** [comment]
@Aweary Thanks for the fast response! Not logging for `renderToString` is an odd choice, though: https://tonicdev.com/marionebl/57d02fc0e81c50140020d052. Is this really intended has there been a discussion about this?

**Comment by Aweary** [comment]
@marionebl we do log the warning with `renderToString`, the issue is that you're not actually rendering your element. Once you actually try and render an element with invalid attributes, you get the warning: https://jsfiddle.net/v8vqf7zp/
