### ISSUE TITLE
Use Babili instead of Uglify for browser builds

### ISSUE THREAD

**Issue by zpao** [facebook/react#7677]
No idea if this is actually viable at this point, but figured I'd open an issue so we can track and determine the best way forward (as it's pretty likely that we'll end up there unless we find a reason not to).

Couple things to consider:
- Currently we Browserify the already compiled modules. We might not need to do that for Babili (but would for Browserify to resolve correctly).
- Maybe we can start dropping transforms from the npm package more aggressively and rely on native to support things, but still compile more for the browser.
- What's the risk of falling out of sync by basically having dual pipelines?

If somebody is interested in investigating this, feel free (just say something). Let's hold off on PRs for the time being unless there are convincing results - I don't foresee this being immediately doable and would rather collect info all in one place instead of splitting discussion.

**Comment by Aweary** [comment]
I can look into this 👍

**Comment by gaearon** [comment]
I don’t think we’re likely to go ahead with Babili as it still suffers from some correctness issues and Babel architecture makes them hard to fix. We will be looking into other minification options though.
