### ISSUE TITLE
Issue with input and formatting the value to the state

### ISSUE THREAD

**Issue by viktorlarsson** [facebook/react#7688]
**Do you want to request a *feature* or report a *bug*?**

I want to report a bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

In this case, I am trying to format the value from the input with a thousand separator.

```javascript
formatNumber(ev) {

      const formattedNumber = new Intl.NumberFormat('sv-SE').format(ev.target.value);
      this.setState({number: formattedNumber});

}
```

```html
<input type="text" value={number} onChange={this.formatNumber} />
```

When typing the number, everything is well. But when the number exceeds 1000, the value of the state becomes "¤¤¤".

When setting the original target value using setState and when loggin the formatted value, it works as expected.

```javascript
formatNumber(ev) {
      
      const formattedNumber = new Intl.NumberFormat('sv-SE').format(ev.target.value);
      console.log(formattedNumber);
      this.setState({number: ev.target.value});

}
```
Here is a Codepen with the problem
[https://codepen.io/viktorsarstrom/pen/ORyVBg](https://codepen.io/viktorsarstrom/pen/ORyVBg)

**What is the expected behavior?**

When using Intl.NumberFormat('sv-SE') the values should be as following
100 should be 100 (works)
1000 should be 1 000 (works)
10000 should be  10 000 (does not work)
100000 should be 100 000 (does not work)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Unaware of this has worked in previous version of React, but I am using React 15.1.0 and React-Dom 15.1.0

Tested in latest version of Chrome and Firefox.

**Comment by zpao** [comment]
This is Intl failing to format the value. You're passing `'1 0000'` in that case. You can call it directly and see the same thing. You'll want to unformat before trying to reformat. This isn't a bug with React. Good luck.
