### ISSUE TITLE
__DEV__ vs env === 'production'

### ISSUE THREAD

**Issue by chenglou** [facebook/react#770]
Is there a reason why these two coexist (beside the fact that the latter seems to be introduced recently)?

**Comment by buildbreakdo** [comment]
Is code that performs this step in the main react repo? @spicyj's link leads to a 404, tried a repo search to no avail. Like this idea a lot, big plus for readability and doesn't pollute top of the file with an import statement.

**Comment by spicyj** [comment]
It's moved to a transform in the facebook/fbjs repo.

**Comment by buildbreakdo** [comment]
Awesome, found it https://github.com/facebook/fbjs/tree/master/packages/babel-preset-fbjs/plugins. Thanks @spicyj !!
