### ISSUE TITLE
Unable to transform const { layout, ...rest } = props into ES5 via babel

### ISSUE THREAD

**Issue by krave1986** [facebook/react#7703]
I ran into this error when I ran react code.

> Warning: Unknown prop `dataFrameworkName` on h1 tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

So I jump to the link and replaced the code with the first good example listed in the page.
After that, I can not pass the babel transpiling any more. 
The error is:
```
SyntaxError: jsx/ttt.jsx: Unexpected token (2:18)
  1 | function MyDiv(props) {
> 2 |   const { layout, ...rest } = props
    |                   ^
  3 |   if (layout === 'horizontal') {
  4 |     return <div {...rest} style={getHorizontalStyle()} />
  5 |   } else {
```

My .babelrc file is like this:
```
{
	"presets": ["es2015","react"]
}
```
Did I miss something or the react doc needs to be modified?

**Do you want to request a *feature* or report a *bug*?**
Report a 'bug' or something wrong about the doc.

**What is the current behavior?**
Babel can not transform ES6 code into ES5 which is posted on React official site.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Just copy the following code and running babel to transpile it.
```
    function MyDiv(props) {
      const { layout, ...rest } = props
      if (layout === 'horizontal') {
        return <div {...rest} style={getHorizontalStyle()} />
      } else {
        return <div {...rest} style={getVerticalStyle()} />
      }
    }
```
And the transpiling will stuck at the `...` spread operator.

**What is the expected behavior?**
Pass the transpiling.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
babel: 6.14.0
babel-preset-es2015: 6.14.0
babel-preset-react: 6.11.1

**Comment by Aweary** [comment]
You'll need to also use the [transform-object-rest-spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/) plugin, which isn't included in the React or es2015 preset 👍
