### ISSUE TITLE
Anyway to retrieve a field's meta object externally?

### ISSUE THREAD

**Issue by dkwin** [facebook/react#7705]
Hi all

   I was hoping to retrieve a field's meta attribute after the field has been rendered so that I can know if a field has an error or not.  I'm actually wrapping a field in a pop up so that it can be edited later so I want to know whether the field has an error so that they use is allowed to continue.

For example,

`let fieldReference = <Field name="name" component={CustomComponent} />`
`...code to be run later after the field has been rendered and user inputs value`
`console.log (fieldReference.meta.error);`

I'm finding that I cannot reference the meta object.  But I can access the meta object in in the CustomComponent field, is there anyway without storing my own variables to access the meta or input objects if I have a reference to the field?

**Comment by zpao** [comment]
`Field` is not a React thing - sounds like you want to file this elsewhere.

If you're speaking more generically about references to rendered components, you may want to look into [refs](https://facebook.github.io/react/docs/more-about-refs.html).
