### ISSUE TITLE
Search box on website is wrong font

### ISSUE THREAD

**Issue by spicyj** [facebook/react#7706]
It doesn't match the rest of our text. I think a `font-family: inherit;` in the right place in the stylesheet should fix this.

![image](https://cloud.githubusercontent.com/assets/6820/18454149/a1fa8954-78f7-11e6-877c-8f8fba7590b5.png)

**Comment by zpao** [comment]
Pretty sure this is already correct…

**Comment by dlindenkreuz** [comment]
It's not. Proxima Nova on the body vs. the default sans system font (San Francisco in the screenshot) in the <input>

**Comment by thymikee** [comment]
The font is indeed different.

With font-family inherited: 
<img width="248" alt="screen shot 2016-09-13 at 00 27 38" src="https://cloud.githubusercontent.com/assets/5106466/18455231/1150ac92-7949-11e6-9b62-6c2557f4b8a5.png">
Without (current): 
<img width="244" alt="screen shot 2016-09-13 at 00 27 48" src="https://cloud.githubusercontent.com/assets/5106466/18455232/11519d64-7949-11e6-9012-3e20fc142b17.png">

**Comment by zpao** [comment]
touché - I had unchecked the browser-styles box in my inspector at some point and so it showed it inheriting the html style… oops. (the Proxima Nova "R" and SF "R" look similar enough that it fooled me too).

We could probably just make `input { font-family: inherit; }` in `_css/_typography.scss` as opposed to targeting just this one - we already have that for headers.

**Comment by thymikee** [comment]
@zpao Adjusted the PR to include just that

**Comment by zpao** [comment]
Closed with #7708
